### PR TITLE
sqlmigrations: correctly set the start key while upgrading descriptors

### PR DESCRIPTION
**Pull request by vivekmenezes**
Prior to this change, if the underlying transaction retried it would
miss upgrading some keys.

Release note: None

### CODE REVIEW

**Comment by vivekmenezes** [comment]
@andreimatei FYI

**Comment by andreimatei** [comment]
LGTM

Good find! Consider adding a test.

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sqlmigrations/migrations.go, line 653 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26861#-LFTN-Ar6jkTGXttIvDt:-LFTN-Ar6jkTGXttIvDu:bg49myd) ([raw file](https://github.com/cockroachdb/cockroach/blob/83835797cf5ac3ca04ec54377c0e0b4132828adf/pkg/sqlmigrations/migrations.go#L653)):*
> ```Go
> 	startKey := sqlbase.MakeAllDescsMetadataKey()
> 	endKey := startKey.PrefixEnd()
> 	for done := false; !done; {
> ```

as long as you're here, please draw attention in a comment to the batching that happens below. I missed that.

---

*[pkg/sqlmigrations/migrations.go, line 654 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26861#-LFTO1AW4D9QvafEuZZI:-LFTO1AW4D9QvafEuZZJ:b8i3sli) ([raw file](https://github.com/cockroachdb/cockroach/blob/83835797cf5ac3ca04ec54377c0e0b4132828adf/pkg/sqlmigrations/migrations.go#L654)):*
> ```Go
> 	endKey := startKey.PrefixEnd()
> 	for done := false; !done; {
> 		// It's safe to use multiple transactions here. Any table descriptor that's
> ```

This comment makes little sense to me. It's talking about `InterleavedFormatVersion` but that function has nothing to do with it. Also I don't see what the fact that new descriptors are created with a specific cluster version has to do with the ability to use a single or multiple transactions - if we used a single txn but new descriptors would be created afterwards with an old format, we'd still have a problem.
Consider moving part of the comment in the caller and seeing if references to one txn vs many make sense.

---

*[pkg/sqlmigrations/migrations.go, line 662 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26861#-LFTNHV21nT97qASKc3g:-LFTNHV21nT97qASKc3h:be2mqfa) ([raw file](https://github.com/cockroachdb/cockroach/blob/83835797cf5ac3ca04ec54377c0e0b4132828adf/pkg/sqlmigrations/migrations.go#L662)):*
> ```Go
> 		var nextKey roachpb.Key
> 		if err := r.db.Txn(ctx, func(ctx context.Context, txn *client.Txn) error {
> 			// Scan a limited batch of keys.
> ```

it's quite hard to read this function. Consider extracting the txn closure into its own function.

---

*[pkg/sqlmigrations/migrations.go, line 672 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26861#-LFTMhJN2LyxrDKgf5P9:-LFTMhJN2LyxrDKgf5PA:b-ue0qft) ([raw file](https://github.com/cockroachdb/cockroach/blob/83835797cf5ac3ca04ec54377c0e0b4132828adf/pkg/sqlmigrations/migrations.go#L672)):*
> ```Go
> 			}
> 			// Store away the start key for the next batch.
> 			nextKey = kvs[len(kvs)-1].Key.Next()
> ```

instead of this, I'd look into plumbing the "resume key" returned by the ScanResponse.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26861#-:-LFTOqXMByZmPRbNPAnv:btkdsrn)*

**Comment by benesch** [comment]
Nice find! :lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sqlmigrations/migrations.go, line 654 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26861#-LFTO1AW4D9QvafEuZZI:-LFYFstb9wFMLihSOLH6:bbw8p1h) ([raw file](https://github.com/cockroachdb/cockroach/blob/83835797cf5ac3ca04ec54377c0e0b4132828adf/pkg/sqlmigrations/migrations.go#L654)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

This comment makes little sense to me. It's talking about `InterleavedFormatVersion` but that function has nothing to do with it. Also I don't see what the fact that new descriptors are created with a specific cluster version has to do with the ability to use a single or multiple transactions - if we used a single txn but new descriptors would be created afterwards with an old format, we'd still have a problem.
Consider moving part of the comment in the caller and seeing if references to one txn vs many make sense.
</blockquote></details>

It's a vestige of when this code was directly part of the interleaved upgrade migration. Someone factored out this function without updating the comment.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26861#-:-LFYH9qlE2_u0NTgYGz1:bli3xsu)*

**Review by vivekmenezes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26861)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sqlmigrations/migrations.go, line 653 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26861#-LFTN-Ar6jkTGXttIvDt:-LH4F1g8DnZtxC5sjjmD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83835797cf5ac3ca04ec54377c0e0b4132828adf/pkg/sqlmigrations/migrations.go#L653)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

as long as you're here, please draw attention in a comment to the batching that happens below. I missed that.
</blockquote></details>

Done.
___
*[pkg/sqlmigrations/migrations.go, line 654 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26861#-LFTO1AW4D9QvafEuZZI:-LH4F24ZAwK9JeVaYuNp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83835797cf5ac3ca04ec54377c0e0b4132828adf/pkg/sqlmigrations/migrations.go#L654)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

It's a vestige of when this code was directly part of the interleaved upgrade migration. Someone factored out this function without updating the comment.
</blockquote></details>

Done.
___
*[pkg/sqlmigrations/migrations.go, line 662 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26861#-LFTNHV21nT97qASKc3g:-LH4F75n4qiq7CHv__Pk:b5m4xvd) ([raw file](https://github.com/cockroachdb/cockroach/blob/83835797cf5ac3ca04ec54377c0e0b4132828adf/pkg/sqlmigrations/migrations.go#L662)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

it's quite hard to read this function. Consider extracting the txn closure into its own function.
</blockquote></details>

I'm leaving it as is for now. This code might just get deleted eventually!
___
*[pkg/sqlmigrations/migrations.go, line 672 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26861#-LFTMhJN2LyxrDKgf5P9:-LH4DHcS8nKF62Uh0XCh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83835797cf5ac3ca04ec54377c0e0b4132828adf/pkg/sqlmigrations/migrations.go#L672)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

instead of this, I'd look into plumbing the "resume key" returned by the ScanResponse.
</blockquote></details>

Done.

**Review by vivekmenezes — COMMENTED** [review]
@benesch worth another look considering that the implementation now uses resume-span

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26861#-:-LH4LcwVDznfnR9yAUh4:b-f58ub2)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by vivekmenezes** [comment]
@benesch any further thoughts on this?

**Review by benesch — CHANGES_REQUESTED** [review]
Whoops, sorry, didn't realize you were waiting on me.

:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26861#-:-LHEDqEl6QxRWAaeUzS8:b-f9imu0)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sqlmigrations/migrations.go, line 655 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26861#-LHEAyc0-acozWXdrvow:-LHEAyc0-acozWXdrvox:b1i34s6) ([raw file](https://github.com/cockroachdb/cockroach/blob/391f4f7cedd0d407a0203cff7d27a4dbcc6e048b/pkg/sqlmigrations/migrations.go#L655)):*
> ```Go
> 	startKey := sqlbase.MakeAllDescsMetadataKey()
> 	span := roachpb.Span{Key: startKey, EndKey: startKey.PrefixEnd()}
> 	for resumeSpan := (roachpb.Span{}); span.Key != nil; span = resumeSpan {
> ```

Any reason for the separate variable? I.e., can you just do this instead?

```
diff --git a/pkg/sqlmigrations/migrations.go b/pkg/sqlmigrations/migrations.go
index 0c52d4c51..0b775aeb3 100644
--- a/pkg/sqlmigrations/migrations.go
+++ b/pkg/sqlmigrations/migrations.go
@@ -652,7 +652,7 @@ func upgradeDescsWithFn(
 	// table descriptors while running this upgrade process.
 	startKey := sqlbase.MakeAllDescsMetadataKey()
 	span := roachpb.Span{Key: startKey, EndKey: startKey.PrefixEnd()}
-	for resumeSpan := (roachpb.Span{}); span.Key != nil; span = resumeSpan {
+	for span.Key != nil {
 		// It's safe to use multiple transactions here because it is assumed
 		// that a new table created will be created upgraded.
 		if err := r.db.Txn(ctx, func(ctx context.Context, txn *client.Txn) error {
@@ -666,7 +666,7 @@ func upgradeDescsWithFn(
 			result := b.Results[0]
 			kvs := result.Rows
 			// Store away the span for the next batch.
-			resumeSpan = result.ResumeSpan
+			span = result.ResumeSpan
 
 			var idVersions []sql.IDVersion
 			var now hlc.Timestamp
```

**Review by benesch — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26861#-:-LHEE0os4pszKdlOR7Ju:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by vivekmenezes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26861)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sqlmigrations/migrations.go, line 655 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26861#-LHEAyc0-acozWXdrvow:-LHIefVlBwMb_Rvknwiu:b-m88x9p) ([raw file](https://github.com/cockroachdb/cockroach/blob/5208d1801e7a229c92699f89fdc527ec7c0a38f7/pkg/sqlmigrations/migrations.go#L655)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Any reason for the separate variable? I.e., can you just do this instead?

```
diff --git a/pkg/sqlmigrations/migrations.go b/pkg/sqlmigrations/migrations.go
index 0c52d4c51..0b775aeb3 100644
--- a/pkg/sqlmigrations/migrations.go
+++ b/pkg/sqlmigrations/migrations.go
@@ -652,7 +652,7 @@ func upgradeDescsWithFn(
 	// table descriptors while running this upgrade process.
 	startKey := sqlbase.MakeAllDescsMetadataKey()
 	span := roachpb.Span{Key: startKey, EndKey: startKey.PrefixEnd()}
-	for resumeSpan := (roachpb.Span{}); span.Key != nil; span = resumeSpan {
+	for span.Key != nil {
 		// It's safe to use multiple transactions here because it is assumed
 		// that a new table created will be created upgraded.
 		if err := r.db.Txn(ctx, func(ctx context.Context, txn *client.Txn) error {
@@ -666,7 +666,7 @@ func upgradeDescsWithFn(
 			result := b.Results[0]
 			kvs := result.Rows
 			// Store away the span for the next batch.
-			resumeSpan = result.ResumeSpan
+			span = result.ResumeSpan
 
 			var idVersions []sql.IDVersion
 			var now hlc.Timestamp
```
</blockquote></details>

this will update span and if a txn retry happens it will be retried with a new value of span which we don't want.

**Comment by knz** [comment]
Is this a change that needs to be backported?

**Pull request merged**
