### PR TITLE
[WIP] protectedts: add cluster setting to disable protectedts

### PR DESCRIPTION
**Pull request by adityamaru**
TODO

Release note: None

### CODE REVIEW

**Comment by adityamaru** [comment]
@ajwerner this is a strawman that I wanted your opinion on since I am not familiar with some parts of PTS such as the cache. It seems hard to find a single point where we can disable all interactions with the PTS subsystem. My concern with this approach is untested NPEs, but I was planning on adding `BACKUP`, `CHANGEFEED` and `IMPORT` tests with the setting set to true.

Do you suggest a more localized change that only disables a subset of the interface methods such as `Protect`, `Verify`?

**Review by ajwerner — COMMENTED** [review]
What's the end goal here? Is it to stop the KV layer from respecting any protected timestamps or to stop writing them? If it's the former (which I suspect it is), then we can do something very targeted. Like honestly we could just make protection no-op return no errors and then have `checkProtectedTimestampsForGC` also return as though there are no protected timestamps. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67960#-:-MfG9Ukz7VK7aUvRtMhQ:b-4pa48x)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by adityamaru** [comment]
The deadlock that was introduced was when we were attempting to serve an AdminVerifyProtected the protected timestamp. So I think we also want to stop writing them, and consequently verifying them?

**Comment by ajwerner** [comment]
My suggestion was to make that request no op succeed.

**Pull request closed without merging**
