### PR TITLE
sqlsmith: complexity refactor

### PR DESCRIPTION
**Pull request by madelynnblue**
Release justification: Category 1: Non-production code changes

### CODE REVIEW

**Comment by mjibson** [comment]
@jordanlewis @rafiss could I get a review on these? I'd be happy to have a hangout if that would help, since this code isn't really familiar to anyone but myself.

**Comment by jordanlewis** [comment]
Sorry for the delay - I'll get to this soon.

**Comment by mjibson** [comment]
Thanks. I added some commits to do more vec stuff.

**Review by rafiss — COMMENTED** [review]
reviewed up to revision8. thanks for splitting up the commits, it made the reviews very easy to do!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40698#-:-Lp9iV_R-16U5z40-Uhp:bk2xm7a)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @mjibson, and @rafiss)

___
*[pkg/internal/sqlsmith/relational.go, line 459 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40698#-Lp9a0yl1OvnWrBF5F6B:-Lp9a0yl1OvnWrBF5F6C:b2k5s5b) ([raw file](https://github.com/cockroachdb/cockroach/blob/0504b4b9e8e5f4e14cebd31959795e5f2a94592c/pkg/internal/sqlsmith/relational.go#L459)):*
> ```Go
> 		// columns, which we could support here. Also see #39240 which
> 		// will support this more generally.
> 		if !s.schema.vectorizable && s.d6() <= 2 && s.canRecurse() {
> ```

just wondering about how to think of this intuitively -- it seems like there used to be `1/3` probability of this, but now it's `complexity * 1/3` probability (which ends up being `1/15` with the default setting). Why do we want to reduce the probability? Or phrased another way, why do we have both the complexity and the d6?

**Review by rafiss — APPROVED** [review]
i got through all the commits now. i think i was able to follow everything and lgtm, but just had some questions for background understanding

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40698#-:-Lp9m82W2wYrzByEHUFr:b-wbfsra)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @mjibson, and @rafiss)

___
*[pkg/internal/sqlsmith/relational.go, line 645 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/40698#-Lp9lXPoEoTkHHNSvzoT:-Lp9lXPoEoTkHHNSvzoU:b5ja22u) ([raw file](https://github.com/cockroachdb/cockroach/blob/05116ac8be40e4bfd0251ea25e0eb0b2f337b53e/pkg/internal/sqlsmith/relational.go#L645)):*
> ```Go
> 		Exprs: tree.SelectExprs{
> 			{
> 				Expr: countStar,
> ```

doesn't need to be in this PR, but just wondering if you plan to / if it's easy to add other aggregate expressions later?

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40698)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rafiss)

___
*[pkg/internal/sqlsmith/relational.go, line 459 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40698#-Lp9a0yl1OvnWrBF5F6B:-LpARWl0COuad3TNnXwN:b4objs) ([raw file](https://github.com/cockroachdb/cockroach/blob/0504b4b9e8e5f4e14cebd31959795e5f2a94592c/pkg/internal/sqlsmith/relational.go#L459)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

just wondering about how to think of this intuitively -- it seems like there used to be `1/3` probability of this, but now it's `complexity * 1/3` probability (which ends up being `1/15` with the default setting). Why do we want to reduce the probability? Or phrased another way, why do we have both the complexity and the d6?
</blockquote></details>

If the complexity is set to 0 then canRecurse will always return false, causing these blocks to never be taken. That's why this was added. It allows us to change the implementation of canRecurse in the future but still have the idea of it be "should I make more complicated things or not?".
___
*[pkg/internal/sqlsmith/relational.go, line 645 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/40698#-Lp9lXPoEoTkHHNSvzoT:-LpAQVSR-Js9U8cRhFtI:bpx9m9x) ([raw file](https://github.com/cockroachdb/cockroach/blob/05116ac8be40e4bfd0251ea25e0eb0b2f337b53e/pkg/internal/sqlsmith/relational.go#L645)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

doesn't need to be in this PR, but just wondering if you plan to / if it's easy to add other aggregate expressions later?
</blockquote></details>

Yes I'd like to do this at some point. sqlsmith can already do all of the aggregate functions. The difficulty here is that not all of them are always available. For example if you GROUP BY you can'd do `sum(_date)` because sum isn't defined for dates. `count` works for all of them, so it's used here. It would be nice to have some smarts that can choose from available options.

**Pull request merged**
