### PR TITLE
sql: Check zone config TTL changes only when re-processing system config 

### PR DESCRIPTION
**Pull request by vivekmenezes**

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Nice change @vivekmenezes! Could we add a test to make sure it all works as expected?

---

Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[pkg/sql/schema_changer.go, line 1232 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24983#-LAn_n3Q65qiKfHQrPn2:-LAn_n3Q65qiKfHQrPn3:b-a4kdeh) ([raw file](https://github.com/cockroachdb/cockroach/blob/473b091a37fe9b2cfc058db2e49bf85ecbfc2a2e/pkg/sql/schema_changer.go#L1232)):*
> ```Go
> 				timer = s.newTimer(s.schemaChangers)
> 
> 			case <-gcTimer.C:
> ```

This is a lot of duplicated code. Can it be factored out?

---

*[pkg/sql/schema_changer.go, line 1112 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24983#-LAnaV6ICbQ7BHTS6LOQ:-LAnaV6ICbQ7BHTS6LOR:b69zdg0) ([raw file](https://github.com/cockroachdb/cockroach/blob/185fde9f60195858fa560a749d73736c2ba0a59f/pkg/sql/schema_changer.go#L1112)):*
> ```Go
> 				})
> 				if zoneCfgModified {
> 					// Check to see if the GC TTL has changed.
> ```

Could you expand this comment? Explain why are we checking this.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24983#-:-LAnbe7eDYaPvR3GeJMF:b-9tydqx)*

**Comment by vivekmenezes** [comment]
Thanks for taking a look at this PR. I'm sorry that I didn't get back to it until now. Thanks!

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/schema_changer.go, line 1232 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/24983#-LAn_n3Q65qiKfHQrPn2:-LBNJ0dl4N5V3z1meAdu:b-u53sxa) ([raw file](https://github.com/cockroachdb/cockroach/blob/473b091a37fe9b2cfc058db2e49bf85ecbfc2a2e/pkg/sql/schema_changer.go#L1232)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This is a lot of duplicated code. Can it be factored out?
</blockquote></details>

I've factored it into a single method in a new commit.

---

*[pkg/sql/schema_changer.go, line 1112 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/24983#-LAnaV6ICbQ7BHTS6LOQ:-LBNJLTV4XObA9gAN0mH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/185fde9f60195858fa560a749d73736c2ba0a59f/pkg/sql/schema_changer.go#L1112)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Could you expand this comment? Explain why are we checking this.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24983#-:-LBNJMY31Dtos3bHgnpX:bpiuvip)*

**Comment by vivekmenezes** [comment]
TestDropTableDeleteData tests this change. A new zone config is pushed in that test

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24983#-:-LBQIwJV22xeE0A-_IZA:b1dteek)*

**Comment by nvanbenschoten** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24983#-:-LBWthWIAzFrjOWCl2s-:bnfp4nl)*

**Pull request merged**
