### PR TITLE
distsql: write out table stats in SampleAggregator

### PR DESCRIPTION
**Pull request by RaduBerinde**
Finishing the implementation of the sample aggregator.

Release note: none

### CODE REVIEW

**Comment by rytaft** [comment]
:lgtm: 

Some minor comments inline.

---

Reviewed 8 of 9 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/sample_aggregator.go, line 215 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20275#-KzzLAddCIraPrMl7kUk:-KzzLAddCIraPrMl7kUl:b-b125za) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7a356506ed8bd3d696f5664010fb930d61b925/pkg/sql/distsqlrun/sample_aggregator.go#L215)):*
> ```Go
> 
> 			if si.spec.GenerateHistogram {
> 				colIdx := int(si.spec.Columns[0])
> ```

Are you already checking somewhere else that there is exactly 1 column whenever `GenerateHistogram` is true?

---

*[pkg/sql/distsqlrun/sample_aggregator.go, line 235 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20275#-KzzIRdVwBCpZIFoTiPi:-KzzIRdVwBCpZIFoTiPj:b8n4mgg) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7a356506ed8bd3d696f5664010fb930d61b925/pkg/sql/distsqlrun/sample_aggregator.go#L235)):*
> ```Go
> 			}
> 
> 			statID++
> ```

why not move this up below line 209 where `statID` is defined?

---

*[pkg/sql/distsqlrun/sample_aggregator.go, line 247 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20275#-KzzIu--nIRBCTQLdRek:-KzzIu--nIRBCTQLdRel:baimgs3) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7a356506ed8bd3d696f5664010fb930d61b925/pkg/sql/distsqlrun/sample_aggregator.go#L247)):*
> ```Go
> 				fmt.Fprintf(&colsBuf, "%d", s.sampledCols[c])
> 			}
> 			colsBuf.WriteString("}")
> ```

You could do something like this and pass it directly without casting (possibly more efficient?):

```
	columnIDs := tree.NewDArray(types.Int)
	for _, c := range si.spec.Columns {
		if err := columnIDs.append(tree.NewDInt(tree.DInt(int(s.sampledCols[c])))); err != nil {
			return err
		}
	}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20275#-:-KzzOzZmLLOZR6G2lcDI:b8jydw1)*

**Comment by rytaft** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/sample_aggregator.go, line 202 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20275#-KzzPWxWFTqbNxU3Opzq:-KzzPWxWFTqbNxU3Opzr:bvcezkq) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7a356506ed8bd3d696f5664010fb930d61b925/pkg/sql/distsqlrun/sample_aggregator.go#L202)):*
> ```Go
> 		datums, err := s.flowCtx.executor.QueryRowInTransaction(
> 			ctx, "get-statistic-id", txn,
> 			`SELECT IFNULL(MAX("statisticID"), 0) FROM system.table_statistics WHERE "tableID" = $1`,
> ```

Does this really do what you want it to? If there are no statistics for the given tableID, I think this would just return no rows.  In that case, you'd need to add an extra check below before accessing datums[0]

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20275)*

**Comment by RaduBerinde** [comment]
TFTR! Updated.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/sample_aggregator.go, line 202 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20275#-KzzPWxWFTqbNxU3Opzq:-KzzViUm-IFW9nRFA-T5:b-q9qxa8) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7a356506ed8bd3d696f5664010fb930d61b925/pkg/sql/distsqlrun/sample_aggregator.go#L202)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Does this really do what you want it to? If there are no statistics for the given tableID, I think this would just return no rows.  In that case, you'd need to add an extra check below before accessing datums[0]
</blockquote></details>

MAX always returns exactly 1 row. It just returns NULL if there are no rows.

---

*[pkg/sql/distsqlrun/sample_aggregator.go, line 215 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20275#-KzzLAddCIraPrMl7kUk:-KzzVmd6MmQgMSMkVwSR:builmok) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7a356506ed8bd3d696f5664010fb930d61b925/pkg/sql/distsqlrun/sample_aggregator.go#L215)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Are you already checking somewhere else that there is exactly 1 column whenever `GenerateHistogram` is true?
</blockquote></details>

Good point, added to newSampleAggregator

---

*[pkg/sql/distsqlrun/sample_aggregator.go, line 235 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20275#-KzzIRdVwBCpZIFoTiPi:-KzzWGS11qt1CHkTWG2x:b-fwj7nf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7a356506ed8bd3d696f5664010fb930d61b925/pkg/sql/distsqlrun/sample_aggregator.go#L235)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

why not move this up below line 209 where `statID` is defined?
</blockquote></details>

We're in a loop

---

*[pkg/sql/distsqlrun/sample_aggregator.go, line 247 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20275#-KzzIu--nIRBCTQLdRek:-KzzWQZBbLxR75iKjsO7:bay2hva) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7a356506ed8bd3d696f5664010fb930d61b925/pkg/sql/distsqlrun/sample_aggregator.go#L247)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

You could do something like this and pass it directly without casting (possibly more efficient?):

```
	columnIDs := tree.NewDArray(types.Int)
	for _, c := range si.spec.Columns {
		if err := columnIDs.append(tree.NewDInt(tree.DInt(int(s.sampledCols[c])))); err != nil {
			return err
		}
	}
```
</blockquote></details>

Ahh nice, I didn't realize you can pass Datums to ExecuteStatementInTransaction. Your code worked on the first try :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20275#-:-KzzWuMrq_4E47aaMOSI:b-p0fj95)*

**Comment by rytaft** [comment]
:lgtm_strong: 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsqlrun/sample_aggregator.go, line 202 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20275#-KzzPWxWFTqbNxU3Opzq:-KzzZnaRjV90FCI1Qm0u:b-iaxb1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7a356506ed8bd3d696f5664010fb930d61b925/pkg/sql/distsqlrun/sample_aggregator.go#L202)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

MAX always returns exactly 1 row. It just returns NULL if there are no rows.
</blockquote></details>

Ah right - oops!

---

*[pkg/sql/distsqlrun/sample_aggregator.go, line 235 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20275#-KzzIRdVwBCpZIFoTiPi:-Kzza1TniG1yA0ApEuIg:b-w194oo) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7a356506ed8bd3d696f5664010fb930d61b925/pkg/sql/distsqlrun/sample_aggregator.go#L235)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We're in a loop
</blockquote></details>

Ah ok I understand now - thanks!  I think it could be clearer if you move it just inside the start of the for loop - now line 216

---

*[pkg/sql/distsqlrun/sample_aggregator.go, line 247 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20275#-KzzIu--nIRBCTQLdRek:-Kzz_A_H6qLc_rgK_-lE:btojbfd) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7a356506ed8bd3d696f5664010fb930d61b925/pkg/sql/distsqlrun/sample_aggregator.go#L247)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Ahh nice, I didn't realize you can pass Datums to ExecuteStatementInTransaction. Your code worked on the first try :)
</blockquote></details>

Great!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20275#-:-KzzanW54THoiT4o33--:b-uwkowd)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsqlrun/sample_aggregator.go, line 235 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20275#-KzzIRdVwBCpZIFoTiPi:-KzzdGrAGjX3B1DD1gOr:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7a356506ed8bd3d696f5664010fb930d61b925/pkg/sql/distsqlrun/sample_aggregator.go#L235)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Ah ok I understand now - thanks!  I think it could be clearer if you move it just inside the start of the for loop - now line 216
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20275)*

**Comment by rytaft** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20275)*

**Pull request merged**
