### PR TITLE
ui:  backport 21.1 custom chart changes 

### PR DESCRIPTION
**Pull request by vladlos**
backport:
- fix for extra space on custom charts page
- add drag-to-select time range feature on custom charts page

### CODE REVIEW

**Review by Santamaura — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66594#-:-McoWnsv3miSGTVX2MTy:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @koorosh and @nathanstilwell)

___
*[pkg/ui/src/views/cluster/components/linegraph/index.tsx, line 407 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66594#-McoVuZu05h7LmcaFMwf:-McoVuZu05h7LmcaFMwg:bu27nyo) ([raw file](https://github.com/cockroachdb/cockroach/blob/b83d9f76f0dcc0eae782bf45af898c63fac9fd77/pkg/ui/src/views/cluster/components/linegraph/index.tsx#L407)):*
> ```XML
>   // automatically when a narrower time frame is selected.
>   setNewTimeRange(startMillis: number, endMillis: number) {
>     if (startMillis === endMillis) return;
> ```

BTW, just wondering why this is needed but was not added to the original (66261) PR, is this related to the error when no metric is selected?

**Review by Santamaura — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66594)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @koorosh and @nathanstilwell)

___
*[pkg/ui/src/views/cluster/components/linegraph/index.tsx, line 406 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66594#-McoX9TJ1qNA0AuOGOYI:-McoX9TJ1qNA0AuOGOYJ:b-r5zk50) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6cce94bf1e0f1d5744e876aaa045268cad98c8c/pkg/ui/src/views/cluster/components/linegraph/index.tsx#L406)):*
> ```XML
>   // TODO(davidh): figure out why the timescale doesn't get more granular
>   // automatically when a narrower time frame is selected.
>   setNewTimeRange(startMillis: number, endMillis: number) {
> ```

BTW why is this required? Is it related to the error where no metric is selected?

**Review by koorosh — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66594)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @elkmaster and @nathanstilwell)

___
*[pkg/ui/src/views/cluster/components/linegraph/index.tsx, line 506 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66594#-McrcFbj0E2d16f4TWRK:-McrcFbj0E2d16f4TWRL:b-oymd4g) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6cce94bf1e0f1d5744e876aaa045268cad98c8c/pkg/ui/src/views/cluster/components/linegraph/index.tsx#L506)):*
> ```XML
>         this.u.destroy();
>       }
>       try {
> ```

@elkmaster , what causes a crash here? Is it corrupted data or wrong uPlot options? Is it possible to validate input data for uPlot to avoid try-catch here?

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66594)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @elkmaster and @nathanstilwell)

___
*[pkg/ui/src/views/cluster/components/linegraph/index.tsx, line 448 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66594#-Mcrl8CYD4LKHwH3AVjL:-Mcrl8CYD4LKHwH3AVjM:bb3pmwx) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6cce94bf1e0f1d5744e876aaa045268cad98c8c/pkg/ui/src/views/cluster/components/linegraph/index.tsx#L448)):*
> ```XML
> 
>   componentDidUpdate(prevProps: Readonly<LineGraphProps>) {
>     if (!this.props.data || !this.props.data.results) {
> ```

I suggest to extend this condition to validate if at least one result has some datapoints:
```typescript
if (
      !this.props.data ||
      !this.props.data.results ||
      !this.props.data.results.some((r) => r.datapoints?.length > 0)
    ) {
      return;
    }
```
This change can be alternative to try-catch below

**Review by vladlos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66594)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @koorosh, @nathanstilwell, and @Santamaura)

___
*[pkg/ui/src/views/cluster/components/linegraph/index.tsx, line 407 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66594#-McoVuZu05h7LmcaFMwf:-MdMf8L10KaEB8P19qxO:b-vjv9we) ([raw file](https://github.com/cockroachdb/cockroach/blob/b83d9f76f0dcc0eae782bf45af898c63fac9fd77/pkg/ui/src/views/cluster/components/linegraph/index.tsx#L407)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

BTW, just wondering why this is needed but was not added to the original (66261) PR, is this related to the error when no metric is selected?
</blockquote></details>

original pr for this change is 66321, this line present there.
___
*[pkg/ui/src/views/cluster/components/linegraph/index.tsx, line 406 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66594#-McoX9TJ1qNA0AuOGOYI:-MdMfA61-t23MxYd4NB9:bnr2mb8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6cce94bf1e0f1d5744e876aaa045268cad98c8c/pkg/ui/src/views/cluster/components/linegraph/index.tsx#L406)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

BTW why is this required? Is it related to the error where no metric is selected?
</blockquote></details>

when metric no selected start and end values equals now(), if user try to select  something without this check we will get an error
___
*[pkg/ui/src/views/cluster/components/linegraph/index.tsx, line 448 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66594#-Mcrl8CYD4LKHwH3AVjL:-MdMiEpW71M9bMzxtid9:b31nyqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6cce94bf1e0f1d5744e876aaa045268cad98c8c/pkg/ui/src/views/cluster/components/linegraph/index.tsx#L448)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

I suggest to extend this condition to validate if at least one result has some datapoints:
```typescript
if (
      !this.props.data ||
      !this.props.data.results ||
      !this.props.data.results.some((r) => r.datapoints?.length > 0)
    ) {
      return;
    }
```
This change can be alternative to try-catch below
</blockquote></details>

not relevant anymore after https://github.com/cockroachdb/cockroach/pull/66897
___
*[pkg/ui/src/views/cluster/components/linegraph/index.tsx, line 506 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/66594#-McrcFbj0E2d16f4TWRK:-MdMiLK97ODnGZ43Z_Oo:b-ht236g) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6cce94bf1e0f1d5744e876aaa045268cad98c8c/pkg/ui/src/views/cluster/components/linegraph/index.tsx#L506)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

@elkmaster , what causes a crash here? Is it corrupted data or wrong uPlot options? Is it possible to validate input data for uPlot to avoid try-catch here?
</blockquote></details>

I do not found original reason, all front end related code is same as in 20.2 and master. Seems to be something protobuf related, but my fix is not relevant anymore after https://github.com/cockroachdb/cockroach/pull/66897

**Review by koorosh — APPROVED** [review]
> Reviewed 2 of 3 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66594)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nathanstilwell)

**Pull request merged**
