### PR TITLE
 sql/tree: fix the walk recursions into WindowDef and OrderBy

### PR DESCRIPTION
**Pull request by knz**
Prior to this patch, the handling of Walk() and Format() for WindowDef
was, let's say, very ad-hoc and "not following convention".
This patch cleans the code up and makes it more regular.

Additionally, there may have been a bug in the Walk recursion for
SelectClause with window definitions. This patch averts it.

### CODE REVIEW

**Comment by knz** [comment]
@rytaft my fix here is revealing a bug/error in the name resolution for window functions. Please check the attached CI failure: 
```
panic: scopeColumn must be replaced before evaluation [recovered]
    panic: panic while executing 1 statements: SELECT avg(_) OVER (PARTITION BY _) FROM _ ORDER BY _; caused by scopeColumn must be replaced before evaluation

goroutine 1164 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc421232600, 0xb3b000, 0xc4218719c0, 0x3bc060, 0xc420506350)
    /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:669 +0x36f
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc421232600, 0xb3b000, 0xc4218719c0)
    /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:411 +0x61
panic(0x3bc060, 0xc420506350)
    /usr/local/go/src/runtime/panic.go:502 +0x229
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*scopeColumn).Eval(0xc420d54f98, 0xc421232ac0, 0xb5bdc0, 0xc4210ca130, 0x0, 0x0)
    /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scope_column.go:130 +0x68
github.com/cockroachdb/cockroach/pkg/sql.(*renderNode).renderRow(0xc4212b8f20, 0xc421232ac0, 0x7, 0x7)
    /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/render.go:557 +0xba
github.com/cockroachdb/cockroach/pkg/sql.(*renderNode).Next(0xc4212b8f20, 0xb3b0c0, 0xc4212d36e0, 0xc421232ac0, 0xc421232a30, 0x8, 0xc42174c978, 0x18fa363)
    /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/render.go:362 +0xdd
github.com/cockroachdb/cockroach/pkg/sql.(*windowNode).Next(0xc421104500, 0xb3b0c0, 0xc4212d36e0, 0xc421232ac0, 0xc421232a30, 0x1, 0x1, 0x0)
    /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/window.go:172 +0xbe
github.com/cockroachdb/cockroach/pkg/sql.(*sortNode).Next(0xc420d65b90, 0xb3b0c0, 0xc4212d36e0, 0xc421232ac0, 0xc421232a30, 0xc42076e2d0, 0x0, 0xc42174cab8)
    /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/sort.go:259 +0x148
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).forEachRow(0xc421232600, 0xb3b0c0, 0xc4212d36e0, 0xc421232ac0, 0xc421232a30, 0xb2f5c0, 0xc420d65b90, 0xc42174cb28, 0x2999cc1, 0xb3b0c0)
    /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:943 +0x60
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithLocalEngine(0xc421232600, 0xb3b0c0, 0xc4212d36e0, 0xc421232a30, 0x3, 0x805000ae0, 0xc42111aea0, 0x0, 0x0)
    /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:886 +0x286
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc421232600, 0xb3b0c0, 0xc4212d36e0, 0xb3d680, 0xc420a69a40, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:802 +0xa7e
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc421232600, 0xb3b0c0, 0xc4212d36e0, 0xb3d680, 0xc420a69a40, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:401 +0xb1e
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc421232600, 0xb3b0c0, 0xc4212d36e0, 0xb3d680, 0xc420a69a40, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:95 +0x358
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc421232600, 0xb3b000, 0xc4218719c0, 0xc4203f5bb0, 0x0, 0x0)
    /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1076 +0x2055
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc4211dc000, 0xb3b000, 0xc4218719c0, 0xc420e84026, 0x4, 0xc420e84030, 0x4, 0x0, 0x0, 0xb20e80, ...)
    /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:413 +0x1bb
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func3(0xc4211dc000, 0xb3b000, 0xc4218719c0, 0xc4201e4c40, 0x5400, 0x15000, 0xc420750600, 0xc4203f5bb0, 0xc4203f5ba0, 0xc4203a2d90, ...)
    /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:267 +0x122
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
    /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:266 +0xf27
```

Also I am getting an optbuilder test error. 

Can you have brief look and provide guidance as to how to investigate this?

**Review by yuzefovich — APPROVED** [review]
Very nice changes!

:lgtm: pending a question about `ret` vs `windowDef`.

> Reviewed 3 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27695#-:-LHhSAPa1_RCBIVXEsio:b816wvs)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/sem/tree/walk.go, line 217 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27695#-LHhOtwf5xSti9II5piL:-LHhOtwg7FLAot7VmP_x:b-8vtvpq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bdfe6e19b1ca0d494e35666a14c7986692260ed/pkg/sql/sem/tree/walk.go#L217)):*
> ```Go
> // CopyNode makes a copy of this WindowFrame without recursing.
> func (node *WindowFrame) CopyNode() *WindowFrame {
> 	ret := *node
> ```

[super nit]: for consistency with other `CopyNode` methods, I'd use `nodeCopy` variable name. Same in two methods below.
___
*[pkg/sql/sem/tree/walk.go, line 278 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27695#-LHhQTjL22ORqubhI9L0:-LHhQTjL22ORqubhI9L1:bnwvrfg) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bdfe6e19b1ca0d494e35666a14c7986692260ed/pkg/sql/sem/tree/walk.go#L278)):*
> ```Go
> 				ret = windowDef.CopyNode()
> 			}
> 			windowDef.Partitions = exprs
> ```

I might be wrong, but I think we want to modify `ret` and not `windowDef`. Same in two `if`s below.
___
*[pkg/sql/sem/tree/walk.go, line 307 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27695#-LHhRW1r4Pc5XIKOwXol:-LHhRW1r4Pc5XIKOwXom:b-xgsbjv) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bdfe6e19b1ca0d494e35666a14c7986692260ed/pkg/sql/sem/tree/walk.go#L307)):*
> ```Go
> 	ret := expr
> 	for i := range expr.Exprs {
> 		e, changed := WalkExpr(v, expr.Exprs[i])
> ```

Can we use `WalkExprSlice` here?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27695)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/sem/tree/walk.go, line 217 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27695#-LHhOtwf5xSti9II5piL:-LHhZPDHCQ1Lin_YAtfV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bdfe6e19b1ca0d494e35666a14c7986692260ed/pkg/sql/sem/tree/walk.go#L217)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[super nit]: for consistency with other `CopyNode` methods, I'd use `nodeCopy` variable name. Same in two methods below.
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/walk.go, line 278 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27695#-LHhQTjL22ORqubhI9L0:-LHhZT2FBbj_splbf5OR:bwf26b) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bdfe6e19b1ca0d494e35666a14c7986692260ed/pkg/sql/sem/tree/walk.go#L278)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I might be wrong, but I think we want to modify `ret` and not `windowDef`. Same in two `if`s below.
</blockquote></details>

D'oh. Yes, of course. Thanks. Done.
___
*[pkg/sql/sem/tree/walk.go, line 307 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27695#-LHhRW1r4Pc5XIKOwXol:-LHhZXJmCDAPij8YyXuW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bdfe6e19b1ca0d494e35666a14c7986692260ed/pkg/sql/sem/tree/walk.go#L307)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Can we use `WalkExprSlice` here?
</blockquote></details>

Done.

**Comment by rytaft** [comment]
@knz can you give me more info about the test that failed? I tried to reproduce the error in a copy of your branch and it seems to be just falling back to the heuristic planner (error (0A000): window functions are not supported).

**Comment by knz** [comment]
Look at the panic: the heuristic planner is finding `*scopeColumn` objects after the fallback.

**Comment by rytaft** [comment]
I see that, but was hoping to find a test case that I can use to reproduce the error. Just running `SELECT avg(k) OVER (PARTITION BY v) FROM kv ORDER BY w;` doesn't seem to trigger it (no panic when I run it from the command line).

But no problem if you don't have that info - I see that the logic tests are failing on this error so I can dig around.

**Comment by rytaft** [comment]
Ok I've reproduced it - will get back to you.

**Comment by rytaft** [comment]
I know what the problem is, but I'm not sure of the best way to fix it.

During name resolution in the optimizer (similar to the heuristic planner, I think), we modify the AST by replacing some nodes. For example, `tree.Subquery` gets replaced with `scope.subquery`, and `tree.ColumnItem` gets replaced with `scope.scopeColumn`. If we discover an unsupported feature (e.g., a window function) after we have already replaced some nodes, then the heuristic planner starts over using the modified AST.

One option is to somehow make a copy of the AST before starting the optimizer, and if we need to fall back to the heuristic planner we should use the copy. cc @RaduBerinde, @andy-kimball - thoughts?

**Comment by knz** [comment]
I thought that name resolution uses the tree.Walk infrastructure  and thus any modifications cause automatically a deep copy. Is that bypassed in the opt code somehow?

**Comment by knz** [comment]
Also if indeed that's the explanation, why does this show up only in this PR and not earlier?

**Comment by RaduBerinde** [comment]
I think @andy-kimball found and fixed something similar before. The `Walk` infrastructure is designed to do copy-on-write - when the callback returns a new expression, all its parents get recreated. But the callback must also make sure to not modify things in-place, which is probably what's happening here.

**Review by RaduBerinde — COMMENTED** [review]
From a quick look, this code looks like it's modifying `t` in-place: https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/opt/optbuilder/scope.go#L667 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27695#-:-LHhqmjEAYFNcPbKjI8w:b-tr275o)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by rytaft** [comment]
I commented out that line but the error is still happening.

To highlight which variable is a `scopeColumn`, I modified the `scopeColumn` output function to prefix the column name with `scopeColumn!`. Here is the output after it falls back:
`SELECT k, concat_agg(s) OVER (PARTITION BY k ORDER BY scopeColumn!w) FROM kv ORDER BY 1`

**Review by RaduBerinde — COMMENTED** [review]
Another option is that the Walk-related code doesn't do the copy-on-write as necessary. Maybe SelecClause.CopyNode needs to do a deeper copy of the window stuff? https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/tree/walk.go#L1054

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27695#-:-LHhsjnMACrL45zCwPkW:bublqzi)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by knz** [comment]
@RaduBerinde this is what my PR here is addressing.

**Review by RaduBerinde — COMMENTED** [review]
Oh, sorry, I had just followed the discussion. Then it needs a bit more work :) Posted a comment below.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27695#-:-LHhth860FGRhyl7J5Pa:ba7u294)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/sem/tree/walk.go, line 263 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27695#-LHhtvgY3S_tn0Pkajw1:-LHhtvgY3S_tn0Pkajw2:b-94zz5b) ([raw file](https://github.com/cockroachdb/cockroach/blob/e502eebba9c9217f9c15b24b14ab31c2eaa50d9d/pkg/sql/sem/tree/walk.go#L263)):*
> ```Go
> // copyNode makes a copy of this WindowDef without recursing.
> func (node *WindowDef) copyNode() *WindowDef {
> 	nodeCopy := *node
> ```

Don't we need to copy the `OrderBy` here? since it's a `[]*Order`
Same for Exprs, maybe Frame?

**Comment by knz** [comment]
OrderBy and Exprs have `walkOrderBy()` and `walkExprSlice()` which do the copy of the slice already. Is that insufficient?

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/sem/tree/walk.go, line 263 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27695#-LHhtvgY3S_tn0Pkajw1:-LHhw8-OAgA5JjYknaxD:bdw9s9i) ([raw file](https://github.com/cockroachdb/cockroach/blob/e502eebba9c9217f9c15b24b14ab31c2eaa50d9d/pkg/sql/sem/tree/walk.go#L263)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Don't we need to copy the `OrderBy` here? since it's a `[]*Order`
Same for Exprs, maybe Frame?
</blockquote></details>

Oh, never mind, that should happen in `walkOrderBy`. Let me take a deeper look.

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/sem/tree/walk.go, line 1029 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27695#-LHhxtMOAzim7WIz_zqX:-LHhxtMOAzim7WIz_zqY:bv1ihss) ([raw file](https://github.com/cockroachdb/cockroach/blob/e502eebba9c9217f9c15b24b14ab31c2eaa50d9d/pkg/sql/sem/tree/walk.go#L1029)):*
> ```Go
> 				copied = true
> 			}
> 			order[i].Expr = e
> ```

@knz is this right? We have `type OrderBy []*Order` so `order[i].Expr` is actually `(*order[i]).Expr. We copied the slice but not the `Order`

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27695)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/sem/tree/walk.go, line 1029 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/27695#-LHhxtMOAzim7WIz_zqX:-LHi2Vtx53xxOBL2r2FC:b-p2uod3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e502eebba9c9217f9c15b24b14ab31c2eaa50d9d/pkg/sql/sem/tree/walk.go#L1029)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

@knz is this right? We have `type OrderBy []*Order` so `order[i].Expr` is actually `(*order[i]).Expr. We copied the slice but not the `Order`
</blockquote></details>

Ouch. No it's not right, but wasn't before either. I wonder how things could work in the first place!

Fixed, and now the tests pass.

I'll look at the 2.0 code and perhaps backport a fix.

**Comment by knz** [comment]
Thank you radu! :100:

**Comment by knz** [comment]
thanks all!

bors r+

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> Reviewed 4 of 6 files at r3, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27695#-:-LHiAmLy0jy6kca1QU4i:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Pull request merged**
