### PR TITLE
[prototype] kv: support committing txns in parallel with writes

### PR DESCRIPTION
**Pull request by nvb**
This change adds support for parallel commits following the approach presented in the [associated RFC](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20180324_parallel_commit.md).

### Summary

This change cuts the commit latency for the final batch of a transaction in half, from two rounds of consensus down to one. It does so by addressing a shortcoming of the transactional model which did not allow `EndTransaction` to be sent in parallel with other writes.

This is made safe by defining a committed transaction as a transaction that meets one of the two following commit conditions:
1. a transaction is *explicitly committed* if it has a transaction record with a COMMITTED status
2. a transaction is *implicitly committed* if it has a transaction record with a STAGING status and intents written for all writes declared as "in-flight" on the transaction record

Using these new commit semantics, we're able to satisfy the implicit commit condition while performing all writes in a transaction, including the `EndTransaction` write, in parallel.

In conjunction with transaction pipelining, which pushes all of the consensus latency into the final batch of a transaction, this change effectively cuts the latency of a transaction down to a single consensus round, the theoretical minimum.

### Approach

The approach begins at the `txnCommitter` interceptor, which is overhauled to become aware of parallel commits. The interceptor is responsible for determining the set of writes that will be in-flight during a parallel commit and attaching these to its EndTransaction request. It then collects the response of parallel commit batches when they return. Based on the outcome of the requests in the batch, the interceptor determines whether the transaction successfully committed by satisfying the implicit commit condition. If this is the case then the interceptor launches an async task to make the commit explicit by moving the transaction record's status from STAGING to COMMITTED. This state transition, which is executed asynchronously, is what kicks off intent resolution.

The change also required modifications to the transaction model. Transactions can now enter a new `STAGING` state, which indicates that a transaction has issued all of its writes and is in the process of committing. While in this state, mutations made as part of the transaction may still be in-flight and can not be assumed to have succeeded. Various request types are made aware of this and the transaction record state machine changes significantly (see replica_tscache.go).

This new state has a big effect on `PushTxn` request, which is used both in concurrency control and garbage collection. Pushing a STAGING transaction acts as expected if the push fails. However, if the push succeeds it's not allowed to directly modify the STAGING transaction record. Instead, it now returns a new `IndeterminateCommitError`. This error is captured by a store and triggers a new transaction recovery mechanism. The mechanism queries all of the STAGING transaction's in-flight writes using `QueryIntent(IfMissing=PREVENT)` requests. The process then passes whether or not it found all declared writes to a new `RecoverTxnRequest` that takes care of recovering the transaction record from the STAGING state to either a COMMITTED or ABORTED state.

### Benchmarking

On single-node clusters or multi-node clusters in a single DC this doesn't seem to be having a dramatic effect, which is somewhat expected. The reason for this is that we're still performing the same number of WAL writes as before for multi-range implicit transactions and we are performing an extra WAL write for multi-range explicit transactions. For workloads where the number of writes completely dominates performance due to inefficiencies in our Raft entry application pipeline (see #17500 and some recent experimentation from @ajwerner), reducing latency without reducing the number of writes we perform won't directly improve performance.

However, the change has a tremendous effect on multi-AZ and multi-Region clusters where consensus latency dominates performance.

Here's a test running `kv0 --secondary-index --concurrency=64` on a 3-node cluster with an `n1-standard-16` vm in `us-east1-b`, `us-west1-b`, and `europe-west2-b`. All leases are in `us-east1-b`, next to the load generator. The top graph is QPS and the bottom graph is p50 latency.

screen shot 2019-02-22 at 8 41 44 pm

I run `SET CLUSTER SETTING kv.transaction.parallel_commits = true;` between 01:37 and 01:38. We see throughput jump from about **96%** and average latency drop exactly in **half**, from `142.6ms` to `71.3ms`. This is exactly the effect that we expected this change to have on workloads that are dominated by distributed consensus round-trip latency.

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
My plan for this isn't to push it through review immediately. It's not making it into 19.1. Instead, I just wanted to get it off my computer and give interested parties (@tbg, @andreimatei, @ajwerner, @bdarnell) a chance to take a look and leave input before I split it into a series of a few PRs (with significantly more testing) to actually be merged. My goal is to get the pieces of this ready to merge over the next month so that it can get in as soon as `master` opens for 19.2.

**Comment by petermattis** [comment]
Those charts are super exciting! I'd like to print them out and mount them on the wall.

**Comment by nvanbenschoten** [comment]
I polished off a good amount of this, so I think it's ready for a high-level review. Specifically, transaction recovery is pretty solid at this point (see `pkg/storage/txnrecovery`, `PushTxnRequest`, `RecoverTxnRequest`, `txn_recovery_intergration_test.go`, etc.). This is the logic I'm planning on splitting into its own PR first. The transaction coordinator changes in the `txnCommitter` are also solid and well-tested now.

The biggest remaining work items are:
1. Figuring out what to do in `DistSender`. This is really the only place that people should avoid looking at at this time. Parallel commits requires that we send `QueryIntent` and `EndTransaction` requests concurrently but in separate batches, even if they are headed to the same Range. That fits in pretty poorly with the existing code structure.
2. On a similar note, making AmbiguousCommitErrors aware of parallel commits.
3. Polishing off `pkg/storage/batcheval/cmd_end_transaction.go`, clarifying the contract around staging EndTransaction requests, and adding some `storage`-level testing in this area (for instance, to `TestCreateTxnRecord`).
4. Reworking a few (not too many!) existing tests to understand parallel commits.

**Comment by nvanbenschoten** [comment]
Superseded by https://github.com/cockroachdb/cockroach/pull/37719.

**Pull request closed without merging**
