### PR TITLE
storage: do not truncate past the last Raft log index

### LINKED ISSUE #15437: storage: requested entry at index is unavailable errors
I'm seeing these entries periodically in the log with a very simple setup. To reproduce, run:

`$ rm -rf cockroach-data/ ; ./cockroach start --insecure --store=cockroach-data/1 --logtostderr`
`$ go run loadgen/kv/main.go --batch=10`

```
I170427 19:53:22.689866 24 server/status/runtime.go:225  [n1] runtime stats: 514 MiB RSS, 165 goroutines, 77 MiB/50 MiB/156 MiB GO alloc/idle/total, 264 MiB/344 MiB CGO alloc/total, 74954.75cgo/sec, 2.34/0.18 %(u/s)time, 0.00 %gc (25x)
E170427 19:53:25.952894 105 storage/queue.go:634  [raftlog,n1,s1,r12/1:/Table/51{-/1/10040…}] requested entry at index is unavailable
E170427 19:53:32.580697 105 storage/queue.go:634  [raftlog,n1,s1,r13/1:/{Table/51/1/1…-Max}] requested entry at index is unavailable
```

### PR DESCRIPTION
**Pull request by petermattis**
RaftStatus.Progress.Match is updated on the leader when a command is
proposed and before it is written to stable storage. This
getQuorumIndex() can return a value in advance of the last index we've
written to the Raft log. Don't try to truncate those indexes.

Fixes #15437

### CODE REVIEW

**Comment by tamird** [comment]
>  This
> getQuorumIndex() can return a value in advance of the last index we've
> written to the Raft log.

s/this/thus/

:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/storage/raft_log_queue.go, line 182 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15466#-KipDxm45TbET0N6lI8a:-KipDxm45TbET0N6lI8b:b-elkjyx) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9acc9710323d2f39c8f3e2d430a75f963c96a6e/pkg/storage/raft_log_queue.go#L182)):*
> ```Go
> 	}
> 	// Never truncate past the last index. Naively, you would expect lastIndex to
> 	// never be smaller that quorumIndex, but RaftStatus.Progress.Match is
> ```

s/that/than/

---

*[pkg/storage/raft_log_queue_test.go, line 84 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15466#-KipE4rqCBaR081-NcpS:-KipE4rqCBaR081-NcpT:b-8pfkpo) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9acc9710323d2f39c8f3e2d430a75f963c96a6e/pkg/storage/raft_log_queue_test.go#L84)):*
> ```Go
> 		expected        uint64
> 	}{
> 		{[]uint64{1, 2}, 100, 1, 1, 0, 1},
> ```

I think it might be time to make these keyed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15466#-:-KipDs88BwK2zNFSwHwy:bez6sj6)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/raft_log_queue.go, line 182 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15466#-KipDxm45TbET0N6lI8a:-KipG0K4AGmB24dLRRrg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9acc9710323d2f39c8f3e2d430a75f963c96a6e/pkg/storage/raft_log_queue.go#L182)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

s/that/than/
</blockquote></details>

Done.

---

*[pkg/storage/raft_log_queue_test.go, line 84 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15466#-KipE4rqCBaR081-NcpS:-KipGJadg3C2ytmPMn8L:b9m8nr5) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9acc9710323d2f39c8f3e2d430a75f963c96a6e/pkg/storage/raft_log_queue_test.go#L84)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I think it might be time to make these keyed.
</blockquote></details>

That would add a ton of verbosity which I feel would actually obscure the test cases.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15466)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/raft_log_queue_test.go, line 84 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15466#-KipE4rqCBaR081-NcpS:-KipGpT3KG5qqQaLK1SG:b2nhktp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9acc9710323d2f39c8f3e2d430a75f963c96a6e/pkg/storage/raft_log_queue_test.go#L84)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

That would add a ton of verbosity which I feel would actually obscure the test cases.
</blockquote></details>

OK.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15466)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15466#-:-KipJtg9aQYjHXUM-ntp:bnfp4nl)*

**Pull request merged**
