### PR TITLE
distsql: join planning (WIP)

### PR DESCRIPTION
**Pull request by RaduBerinde**
The testing part is blocked on some issues we are investigating.

`TestLogic` passes with `COCKROACH_DISTSQL_MODE=on`.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12221)

### CODE REVIEW

**Comment by irfansharif** [comment]
:lgtm:, but would be better to get a second set of eyes on atleast r4, r5. I have very little context into those packages. additionally I think we can definitely do with some more documentation for r1, it becomes a little tricky to follow following `p.mergePlan(rightPlan)` where not _all_ aspects of the two plans are _ completely_ merged, for e.g. `rightPlan.planToStreamColMap`. 

additionally `joinToStreamColMap[d] = len(joinerSpec.OutputColumns)` initially threw me off before realizing that `joinerSpec.OutputColumns` kept getting appended to. this probably is the cleanest way by a comment explaining it wouldn't hurt, feel free to ignore this.

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 5 of 5 files at r4.
Review status: 8 of 11 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql_physical_planner.go, line 761 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12221#-KYntPILBE3Yi5or24tE:-KYntPILBE3Yi5or24tF:bc5di0b) ([raw file](https://github.com/cockroachdb/cockroach/blob/705237d775076f9639b166ffad8956145795d5ae/pkg/sql/distsql_physical_planner.go#L761)):*
> ```Go
> ) []sqlbase.ColumnType_Kind {
> 	numCols := 0
> 	for _, streamCol := range p.planToStreamColMap {
> ```

general question, when is it that `p.planToStreamColMap`, other than `-1`, is not strictly incrementing? i.e. `[0 1 -1 2]` is still _incrementing_ (0, 1 then 2) but `[0 2 1]` isn't.

---

*[pkg/sql/distsql_physical_planner.go, line 828 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12221#-KYnj9GHu0HsS4JsTHSa:-KYnj9GHu0HsS4JsTHSb:b-xjz4f3) ([raw file](https://github.com/cockroachdb/cockroach/blob/705237d775076f9639b166ffad8956145795d5ae/pkg/sql/distsql_physical_planner.go#L828)):*
> ```Go
> 		}
> 
> 		// Set up the equal columns.
> ```

`// equality`

---

*[pkg/sql/distsql_physical_planner.go, line 840 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12221#-KYo2itnUaVL_RXJhgMJ:-KYo2itnUaVL_RXJhgMK:b-xi0ew2) ([raw file](https://github.com/cockroachdb/cockroach/blob/705237d775076f9639b166ffad8956145795d5ae/pkg/sql/distsql_physical_planner.go#L840)):*
> ```Go
> 
> 		if jp.mergeEqualityColumns {
> 			d := 0
> ```

what is `d` here a short form for? 

---

*[pkg/sql/distsql_physical_planner.go, line 955 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12221#-KYnxv3nBLqsokAJX0bX:-KYnxv3nBLqsokAJX0bY:b-gxm6z3) ([raw file](https://github.com/cockroachdb/cockroach/blob/705237d775076f9639b166ffad8956145795d5ae/pkg/sql/distsql_physical_planner.go#L955)):*
> ```Go
> 	//p.ordering = dsp.convertOrdering(n.Ordering(), joinToStreamColMap)
> 	p.ordering = distsql.Ordering{}
> 	return p, nil
> ```

general question, I see now we we leave the adding of the unordered no-op processor to the end, when finalizing the plan but what if the results of this are to be fed into another processor? like a sorter for example? who is responsible for adding the input synchronizer in that case?

---

*[pkg/testutils/sqlutils/sql_runner.go, line 103 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12221#-KYo4qed17HXLblS3psr:-KYo4qed17HXLblS3pss:b8czbe) ([raw file](https://github.com/cockroachdb/cockroach/blob/74dd406b2dacc92dd297a2ab98bf64b151568ec9/pkg/testutils/sqlutils/sql_runner.go#L103)):*
> ```Go
> 	}
> 	res := [][]string{}
> 	for i := 0; rows.Next(); i++ {
> ```

we're not really using `i` here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12221#-:-KYo6CSVSQui1UXKa8Ci:b-go98db)*

**Comment by RaduBerinde** [comment]
TFTR! I will rebase and fix the code to work with the new `joinNode` changes and then address your comments.

---

Review status: 8 of 11 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql_physical_planner.go, line 761 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12221#-KYntPILBE3Yi5or24tE:-KYoOzl5aOc_9aywYCHs:b-37a47f) ([raw file](https://github.com/cockroachdb/cockroach/blob/705237d775076f9639b166ffad8956145795d5ae/pkg/sql/distsql_physical_planner.go#L761)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

general question, when is it that `p.planToStreamColMap`, other than `-1`, is not strictly incrementing? i.e. `[0 1 -1 2]` is still _incrementing_ (0, 1 then 2) but `[0 2 1]` isn't.
</blockquote></details>

An example is `SELECT v, k FROM kv`. In the scanNode the map would be `[0 1]`; when we process the selectNode we realize we don't need an evaluator and just make the map `[1 0]`.

---

*[pkg/sql/distsql_physical_planner.go, line 840 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12221#-KYo2itnUaVL_RXJhgMJ:-KYoPR1qLZnG9J5MFiwK:b-2f4ua3) ([raw file](https://github.com/cockroachdb/cockroach/blob/705237d775076f9639b166ffad8956145795d5ae/pkg/sql/distsql_physical_planner.go#L840)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

what is `d` here a short form for? 
</blockquote></details>

No idea, I used the same stuff that was used in joinPredicate. I will have to update this code given Raphael's new changes though.

---

*[pkg/sql/distsql_physical_planner.go, line 955 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12221#-KYnxv3nBLqsokAJX0bX:-KYoPrOK8Mau1jS1r057:b-pp4j6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/705237d775076f9639b166ffad8956145795d5ae/pkg/sql/distsql_physical_planner.go#L955)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

general question, I see now we we leave the adding of the unordered no-op processor to the end, when finalizing the plan but what if the results of this are to be fed into another processor? like a sorter for example? who is responsible for adding the input synchronizer in that case?
</blockquote></details>

each stage configures its own input synchronizers, as well as the previous stage's output routers.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12221#-:-KYoPcDMyuNZRTMbnjSR:b-6c2zim)*

**Comment by RaduBerinde** [comment]
Updated. I think I made things a lot clearer (with respect to both the `p/rightPlan` thing which is indeed kind of sketchy, and the `OutputColumns`). Current commits r6-r10.

---

Review status: 0 of 12 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/sql/distsql_physical_planner.go, line 828 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12221#-KYnj9GHu0HsS4JsTHSa:-KYp0wsM9qNvS52tHCjn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/705237d775076f9639b166ffad8956145795d5ae/pkg/sql/distsql_physical_planner.go#L828)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

`// equality`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12221#-:-KYozGuRJD0dgz2M05Ti:b-f2qm63)*

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 12 files reviewed at latest revision, 13 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql_physical_planner.go, line 276 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12221#-KYoqgwzX5vzS8kiXLvR:-KYoqgwzX5vzS8kiXLvS:b2oif56) ([raw file](https://github.com/cockroachdb/cockroach/blob/705237d775076f9639b166ffad8956145795d5ae/pkg/sql/distsql_physical_planner.go#L276)):*
> ```Go
> // newPlanToStreamColMap initializes a new physicalPlan.planToStreamColMap. The
> // columns that are present in the result stream(s) should be set in the map.
> func newPlanToStreamColMap(numCols int) []int {
> ```

nit: I guess `makePlanTo..` would be better

---

*[pkg/sql/distsql_physical_planner.go, line 305 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12221#-KYotWDag7jVwpwKgcoU:-KYotWDag7jVwpwKgcoV:b5z8zop) ([raw file](https://github.com/cockroachdb/cockroach/blob/705237d775076f9639b166ffad8956145795d5ae/pkg/sql/distsql_physical_planner.go#L305)):*
> ```Go
> 	p.streams = append(p.streams, q.streams...)
> 	for i := range q.resultRouters {
> 		q.resultRouters[i] += pIdxStart
> ```

so now `q.resultRouters` points to processors in `p`? And also `planToStreamColMap` is not touched. Would it be better if this function returned a tuple of constituents rather than modifying `p`?

---

*[pkg/sql/distsql_physical_planner.go, line 757 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12221#-KYoxMiBt929g5lBWLZ8:-KYoxMiBt929g5lBWLZ9:b-qbvq5c) ([raw file](https://github.com/cockroachdb/cockroach/blob/705237d775076f9639b166ffad8956145795d5ae/pkg/sql/distsql_physical_planner.go#L757)):*
> ```Go
> // getTypesForPlanResult returns the types of the elements in the result streams
> // of a given plan that corresponds to a given planNode.
> func (dsp *distSQLPlanner) getTypesForPlanResult(
> ```

nit: you could have this take `p.planToStreamColMap` instead of `p` and name it `mapNodeTypes`

---

*[pkg/sql/distsql_physical_planner.go, line 953 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12221#-KYp0mADQkU9Md6GNAtr:-KYp0mADQkU9Md6GNAts:b-7gx0ue) ([raw file](https://github.com/cockroachdb/cockroach/blob/705237d775076f9639b166ffad8956145795d5ae/pkg/sql/distsql_physical_planner.go#L953)):*
> ```Go
> 	// TODO(radu): the ordering in the join node can be screwed up (#12037),
> 	// ignore it for now.
> 	//p.ordering = dsp.convertOrdering(n.Ordering(), joinToStreamColMap)
> ```

this has been fixed, right?

---

*[pkg/sql/distsql_physical_planner.go, line 857 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/12221#-KYpGLGA6vtiRvg9OJiJ:-KYpGLGA6vtiRvg9OJiK:b-ihetgl) ([raw file](https://github.com/cockroachdb/cockroach/blob/cce1c5b059dc509b2cb84384cd432f611329468b/pkg/sql/distsql_physical_planner.go#L857)):*
> ```Go
> 
> 	// The join columns are in three groups:
> 	//  - numEq "merged" columns (corresponding to the equality columns)
> ```

s/numEq/numMergedEqualityColumns

---

*[pkg/sql/distsql_physical_planner_test.go, line 130 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/12221#-KYpHVMcIoJ8JjZgJp4A:-KYpHVMcIoJ8JjZgJp4B:befvfz3) ([raw file](https://github.com/cockroachdb/cockroach/blob/65f1fcfef8402ea136d3166cf743859c30b54413/pkg/sql/distsql_physical_planner_test.go#L130)):*
> ```Go
> 	}
> 
> 	if err := tc.TransferRangeLease(rightRange, tc.Target(1)); err != nil {
> ```

comment that this transfer is necessary

---

*[pkg/sql/distsql_physical_planner_test.go, line 133 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/12221#-KYpICo--PGk3fxKbV45:-KYpICo0E8yXSvPrt9xe:b-h3gex5) ([raw file](https://github.com/cockroachdb/cockroach/blob/65f1fcfef8402ea136d3166cf743859c30b54413/pkg/sql/distsql_physical_planner_test.go#L133)):*
> ```Go
> 		t.Fatal(err)
> 	}
> 	if _, err := tc.RemoveReplicas(splitKey, tc.Target(0)); err != nil {
> ```

probably worth some comment around here about how we want this query to be distributed. And you probably want to leave a TODO to assert that it actually is distributed, no?

---

*[pkg/sql/distsql_physical_planner_test.go, line 138 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/12221#-KYpHPuT8aDyljpdZZs3:-KYpHPuUpM5vHYbMQTAS:ben0q1e) ([raw file](https://github.com/cockroachdb/cockroach/blob/65f1fcfef8402ea136d3166cf743859c30b54413/pkg/sql/distsql_physical_planner_test.go#L138)):*
> ```Go
> 
> 	r := sqlutils.MakeSQLRunner(t, tc.ServerConn(0))
> 	r.Exec("SET DIST_SQL = ALWAYS")
> ```

call `r.DB.SetMaxOpenConns(1)` to make me feel good

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12221#-:-KYpIOv8s-hV-6VcYwJB:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 12 files reviewed at latest revision, 13 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql_physical_planner.go, line 276 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12221#-KYoqgwzX5vzS8kiXLvR:-KYt2-fjiLF3vbNowPZx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/705237d775076f9639b166ffad8956145795d5ae/pkg/sql/distsql_physical_planner.go#L276)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: I guess `makePlanTo..` would be better
</blockquote></details>

Done.

---

*[pkg/sql/distsql_physical_planner.go, line 305 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12221#-KYotWDag7jVwpwKgcoU:-KYt3QYi-p-ZgX37SNHB:bb4dtvq) ([raw file](https://github.com/cockroachdb/cockroach/blob/705237d775076f9639b166ffad8956145795d5ae/pkg/sql/distsql_physical_planner.go#L305)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

so now `q.resultRouters` points to processors in `p`? And also `planToStreamColMap` is not touched. Would it be better if this function returned a tuple of constituents rather than modifying `p`?
</blockquote></details>

Done, much better.

---

*[pkg/sql/distsql_physical_planner.go, line 757 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12221#-KYoxMiBt929g5lBWLZ8:-KYt21nli7KtdI6X_nTV:bg4c0f6) ([raw file](https://github.com/cockroachdb/cockroach/blob/705237d775076f9639b166ffad8956145795d5ae/pkg/sql/distsql_physical_planner.go#L757)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: you could have this take `p.planToStreamColMap` instead of `p` and name it `mapNodeTypes`
</blockquote></details>

Heh, I had already done this in r6 :)

---

*[pkg/sql/distsql_physical_planner.go, line 953 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12221#-KYp0mADQkU9Md6GNAtr:-KYt5N67YrWvrHU6YPSf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/705237d775076f9639b166ffad8956145795d5ae/pkg/sql/distsql_physical_planner.go#L953)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

this has been fixed, right?
</blockquote></details>

Done.

---

*[pkg/sql/distsql_physical_planner.go, line 857 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/12221#-KYpGLGA6vtiRvg9OJiJ:-KYt5I8Co9rpRl0X0Ynx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cce1c5b059dc509b2cb84384cd432f611329468b/pkg/sql/distsql_physical_planner.go#L857)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

s/numEq/numMergedEqualityColumns
</blockquote></details>

Done.

---

*[pkg/sql/distsql_physical_planner_test.go, line 130 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/12221#-KYpHVMcIoJ8JjZgJp4A:-KYt7KaA2AzTPAYf_8tz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/65f1fcfef8402ea136d3166cf743859c30b54413/pkg/sql/distsql_physical_planner_test.go#L130)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

comment that this transfer is necessary
</blockquote></details>

Done.

---

*[pkg/sql/distsql_physical_planner_test.go, line 133 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/12221#-KYpICo--PGk3fxKbV45:-KYt7M3g87a4edYPzaMS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/65f1fcfef8402ea136d3166cf743859c30b54413/pkg/sql/distsql_physical_planner_test.go#L133)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

probably worth some comment around here about how we want this query to be distributed. And you probably want to leave a TODO to assert that it actually is distributed, no?
</blockquote></details>

Done.

---

*[pkg/sql/distsql_physical_planner_test.go, line 138 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/12221#-KYpHPuT8aDyljpdZZs3:-KYt778JkHIrv_30F9TA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/65f1fcfef8402ea136d3166cf743859c30b54413/pkg/sql/distsql_physical_planner_test.go#L138)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

call `r.DB.SetMaxOpenConns(1)` to make me feel good
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12221)*

**Comment by irfansharif** [comment]
:lgtm:, this was much easier to read

---

Reviewed 1 of 9 files at r5, 1 of 11 files at r11, 1 of 1 files at r12, 1 of 1 files at r13, 5 of 5 files at r14, 2 of 2 files at r15, 1 of 1 files at r16.
Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks pending.

---

*[pkg/sql/distsql_physical_planner.go, line 856 at r16](https://reviewable.io:443/reviews/cockroachdb/cockroach/12221#-KYtWMfrs4DRuQ0H-_Qv:-KYtWMfsvA5_qzXBilf-:bt74f1x) ([raw file](https://github.com/cockroachdb/cockroach/blob/c84d736b26a84cc9d6635fac587cab745fdc5d78/pkg/sql/distsql_physical_planner.go#L856)):*
> ```Go
> 	// addOutCol appends to joinerSpec.OutputColumns and returns the index
> 	// in the slice of the added column.
> 	addOutCol := func(col uint32) int {
> ```

this is much cleaner, thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12221#-:-KYtWovIrUe47I0_vx-3:bee53vd)*

**Comment by RaduBerinde** [comment]
Rebased and updated the test - it now does a join on 5 nodes.

---

Review status: 0 of 6 files reviewed at latest revision, 14 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12221#-:-KYu3inoqY3rmbLyZ6Xr:bbiucqh)*

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsql_physical_planner.go, line 784 at r17](https://reviewable.io:443/reviews/cockroachdb/cockroach/12221#-KYy2P5CRi9CmBVLsTx3:-KYy2P5CRi9CmBVLsTx4:b-b9cdhm) ([raw file](https://github.com/cockroachdb/cockroach/blob/57ffd708f046a1402661f8aa5df9c33af4fea6d6/pkg/sql/distsql_physical_planner.go#L784)):*
> ```Go
> }
> 
> func (dsp *distSQLPlanner) createPlanForJoin(
> ```

I think this deserves a method-level comment describing how we're gonna do the deed.
- create the left and right plans, and keep track of the output routers of those plans
- merge the plans
- insert hash joiners
- connect the hash joiners to the left/right output routers
- the routers from the hash joiners are the output routers of the resulting plan

---

*[pkg/sql/distsql_physical_planner.go, line 932 at r17](https://reviewable.io:443/reviews/cockroachdb/cockroach/12221#-KYy29iS8wC9Hvq0BkXw:-KYy29iS8wC9Hvq0BkXx:bpjb0zm) ([raw file](https://github.com/cockroachdb/cockroach/blob/57ffd708f046a1402661f8aa5df9c33af4fea6d6/pkg/sql/distsql_physical_planner.go#L932)):*
> ```Go
> 	for pIdx := pIdxStart; pIdx < pIdxEnd; pIdx++ {
> 		// Connect left routers to the processor's first input.
> 		dsp.mergeResultStreams(&p, leftRouters, p.ordering, pIdx, 0)
> ```

as we were discussing, let's make the `dsp.streams` structure more explicit about the input/output slots in the processor that each stream needs to be connected to

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12221#-:-KYy2xTZF_LL_k3k_H7M:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 6 files reviewed at latest revision, 11 unresolved discussions.

---

*[pkg/sql/distsql_physical_planner.go, line 784 at r17](https://reviewable.io:443/reviews/cockroachdb/cockroach/12221#-KYy2P5CRi9CmBVLsTx3:-KYy50tu5uJddi8PLEmS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/57ffd708f046a1402661f8aa5df9c33af4fea6d6/pkg/sql/distsql_physical_planner.go#L784)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think this deserves a method-level comment describing how we're gonna do the deed.
- create the left and right plans, and keep track of the output routers of those plans
- merge the plans
- insert hash joiners
- connect the hash joiners to the left/right output routers
- the routers from the hash joiners are the output routers of the resulting plan
</blockquote></details>

Done.

---

*[pkg/sql/distsql_physical_planner.go, line 932 at r17](https://reviewable.io:443/reviews/cockroachdb/cockroach/12221#-KYy29iS8wC9Hvq0BkXw:-KYy52x475Iw5w1vVRnv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/57ffd708f046a1402661f8aa5df9c33af4fea6d6/pkg/sql/distsql_physical_planner.go#L932)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

as we were discussing, let's make the `dsp.streams` structure more explicit about the input/output slots in the processor that each stream needs to be connected to
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12221)*

**Comment by RaduBerinde** [comment]
This is the plan for TestDistSQLJoin. *wipes tear*
join-5way

**Pull request merged**
