### PR TITLE
ccl/workloadccl: fix get fixture for-loop

### LINKED ISSUE #30793: roachtest: import/tpcc/warehouses=1000/nodes=4 failed
SHA: https://github.com/cockroachdb/cockroach/commits/031748232a601aab191fd3fb00dc298ca20e4506

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stressrace instead of stress and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
make stress TESTS=import/tpcc/warehouses=1000/nodes=4 PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-stderr=false -maxtime 20m -timeout 10m'
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=932135&tab=buildLog

```
The test failed on master:
	test.go:779: test timed out (5h0m0s)
	test.go:498,cluster.go:890,import.go:43,cluster.go:1199,errgroup.go:58: /home/agent/work/.go/bin/roachprod run teamcity-932135-import-tpcc-warehouses-1000-nodes-4:1 -- ./workload fixtures make tpcc --warehouses=1000 --csv-server='http://localhost:8081' --gcs-bucket-override=cockroach-tmp --gcs-prefix-override=teamcity-932135-import-tpcc-warehouses-1000-nodes-4 returned:
		stderr:
		
		stdout:
		Connection to 35.232.31.125 closed by remote host.
		Error:  exit status 255
		: exit status 1
	test.go:498,cluster.go:1220,import.go:46,import.go:56: Goexit() was called

```

### LINKED ISSUE #31054: roachtest: import/tpcc/warehouses=1000/nodes=32 failed
SHA: https://github.com/cockroachdb/cockroach/commits/32346197937265bbc71dd3629b1137df9bf16fb4

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stressrace instead of stress and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
make stress TESTS=import/tpcc/warehouses=1000/nodes=32 PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-stderr=false -maxtime 20m -timeout 10m'
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=948285&tab=buildLog

```
The test failed on master:
	test.go:819: test timed out (5h0m0s)
	test.go:500,cluster.go:897,import.go:50,cluster.go:1219,errgroup.go:58: /home/agent/work/.go/bin/roachprod run teamcity-948285-import-tpcc-warehouses-1000-nodes-32:1 -- ./workload fixtures make tpcc --warehouses=1000 --csv-server='http://localhost:8081' --gcs-bucket-override=cockroach-tmp --gcs-prefix-override=teamcity-948285-import-tpcc-warehouses-1000-nodes-32 returned:
		stderr:
		
		stdout:
		Connection to 35.184.6.175 closed by remote host.
		Error:  exit status 255
		: exit status 1
	test.go:500,cluster.go:1240,import.go:53,import.go:63: dial tcp 35.239.118.172:26257: connect: connection refused

```

### PR DESCRIPTION
**Pull request by petermattis**
Obey the max-retries setting (10) so as to avoid retrying forever.

Fixes #30793
Fixes #31054

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
The for-loop is still a bit suspicious in that it retries 10 times before declaring that the fixture doesn't exist. Can't it determine that from the `b.Objects` error code?

**Review by danhhz — COMMENTED** [review]
:lgtm: thanks for the fix!

> The for-loop is still a bit suspicious in that it retries 10 times before declaring that the fixture doesn't exist. Can't it determine that from the b.Objects error code?

Yes. In fact, there's already a check for this and the retry loop simply does the wrong thing:

```
			if err == iterator.Done {
				return errors.Errorf(`fixture not found: %s`, fixtureFolder)
```

I wish it were easier to write tests for this

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31107#-:-LOKZrAkAzIqXXdqsXo_:b-w240dm)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by petermattis — COMMENTED** [review]
Yeah, I saw that bit didn't know if it was intentional. I've added a small bit of logic to exit the loop if the fixture can't be found.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31107#-:-LOKa4O79o1mAEqceUeT:bvirf9f)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by danhhz — APPROVED** [review]

**Comment by petermattis** [comment]
bors r=danhhz

**Pull request merged**
