### PR TITLE
tree: modify TimestampTZ operators to use ctx loc for operations

### LINKED ISSUE #54: Interval math across dst works differently from PostgreSQL (and other databases)
(Note that daylight saving time "fall back" is Nov. 7 in 2010.)

On PostgreSQL (no time zone active):
``` sql
> CREATE TABLE "example" ("id" serial NOT NULL PRIMARY KEY, "a" timestamp with time zone NOT NULL); 
> INSERT INTO "example" ("a") VALUES ('2010-11-03T12:42:10.234567-05:00'::timestamp); 
> SELECT * FROM "example";
"2010-11-03 12:42:10.234567-04"

> UPDATE "example" SET "a" = ("a" + '15 days 0.000000 seconds'::interval);
> SELECT "a" FROM "example";
"2010-11-18 12:42:10.234567-05"
> TRUNCATE "example";
```
Time zone changes from -04 to -05 but hour remains the same at 12.

With time zone active:
```sql
> SET TIME ZONE "America/Chicago";
> INSERT INTO "example" ("a") VALUES ('2010-11-03T12:42:10.234567-05:00'::timestamp); 
> SELECT * FROM "example";
"2010-11-03 12:42:10.234567-05"

> UPDATE "example" SET "a" = ("a" + '15 days 0.000000 seconds'::interval);
> SELECT "a" FROM "example";
"2010-11-18 12:42:10.234567-06"
```
Time zone changes from -5 to -6 but no hour change.

On cockroachdb:
```sql
> CREATE TABLE "example" ("id" integer NOT NULL PRIMARY KEY DEFAULT unique_rowid(), "a" timestamptz NOT NULL);
> INSERT INTO "example" ("a") VALUES ('2010-11-03T12:42:10.234567-05:00'::timestamptz);
> SELECT * FROM "example";
          id         |                a                  
+--------------------+----------------------------------+
  497354447372025857 | 2010-11-03 17:42:10.234567+00:00  
> UPDATE "example" SET "a" = ("a" + '15 days 0.000000 seconds'::interval) WHERE id=497354447372025857;
> SELECT * FROM "example";
          id         |                a                  
+--------------------+----------------------------------+
  497354447372025857 | 2010-11-18 17:42:10.234567+00:00

> TRUNCATE "example";
```
Fine, but with a time zone active...
```sql
> SET TIME ZONE "America/Chicago";
> INSERT INTO "example" ("a") VALUES ('2010-11-03T12:42:10.234567-05:00'::timestamptz);
> SELECT * FROM "example";
          id         |                a                  
+--------------------+----------------------------------+
  497355106025603073 | 2010-11-03 12:42:10.234567-05:00 

>  UPDATE "example" SET "a" = ("a" + '15 days 0.000000 seconds'::interval) WHERE id=497355106025603073;

> SELECT * FROM "example";
          id         |                a                  
+--------------------+----------------------------------+
  497355106025603073 | 2010-11-18 11:42:10.234567-06:00  
```
Time zone changes from -5 to -6 AND hour changes from 12 to 11.

Failing Django test:
```
======================================================================
FAIL: test_delta_update (expressions.tests.FTimeDeltaTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/python3.7.0/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/opt/python3.7.0/lib/python3.7/unittest/case.py", line 615, in run
    testMethod()
  File "/home/tim/code/django/tests/expressions/tests.py", line 1232, in test_delta_update
    self.assertEqual(expected_ends, new_ends)
  File "/opt/python3.7.0/lib/python3.7/unittest/case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/opt/python3.7.0/lib/python3.7/unittest/case.py", line 1045, in assertListEqual
    self.assertSequenceEqual(list1, list2, msg, seq_type=list)
  File "/opt/python3.7.0/lib/python3.7/unittest/case.py", line 1027, in assertSequenceEqual
    self.fail(msg)
  File "/opt/python3.7.0/lib/python3.7/unittest/case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: Lists differ: [date[198 chars], 10, 14, 9, 24, 15), datetime.datetime(2011, 2, 1, 9, 24, 15)] != [date[198 chars], 10, 14, 9, 24, 15), datetime.datetime(2011, 2, 1, 8, 24, 15)]

First differing element 5:
datetime.datetime(2011, 2, 1, 9, 24, 15)
datetime.datetime(2011, 2, 1, 8, 24, 15)

  [datetime.datetime(2010, 10, 4, 9, 24, 15),
   datetime.datetime(2010, 10, 5, 9, 24, 15, 253000),
   datetime.datetime(2010, 10, 4, 9, 24, 59),
   datetime.datetime(2010, 10, 9, 6, 32, 15),
   datetime.datetime(2010, 10, 14, 9, 24, 15),
-  datetime.datetime(2011, 2, 1, 9, 24, 15)]
?                                ^

+  datetime.datetime(2011, 2, 1, 8, 24, 15)]
?                                ^
```

### PR DESCRIPTION
**Pull request by otan**
Resolve https://github.com/cockroachdb/django-cockroachdb/issues/54.

This PR involves my audit of eval.go and builtins.go to make sure all
TimestampTZ operations are performed in the context timezone for
TimestampTZ. Results are described in the release note.

Important to note we can't parse everything as the current context
location, because it can be subject to change mid-session.

Release note (bug fix, sql change): Previously, some TimestampTZ
operations did not correctly take context timezone (set by `SET TIME
ZONE`) into account.

This caused a few bugs:
* it leads to bugs involving daylight saving in arithmetic,
e.g. with `America/Chicago`, evaluating
'2010-11-06 23:59:00-05'::timestamptz + '1 day'::interval would return
incorrect results as it assumed it was a fixed offset of `-5` instead.
* text conversion from timestamptz to string sometimes used the wrong
timezone offset if the location of the session does not match the
location when the timestamptz was parsed.
* to_json builtins with timestamptz does not take session timezone
into consideration.

These have all been fixed by the PR.

### CODE REVIEW

**Review by solongordon — APPROVED** [review]
> Reviewed 10 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44812)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

**Comment by otan** [comment]
bors r=solongordon

**Comment by otan** [comment]
bors r=solongordon

**Comment by yuzefovich** [comment]
Just noticed that this PR hasn't been backported to 19.2 when backporting my own PR. Just a friendly ping to consider whether this needs to be backported.

**Comment by otan** [comment]
I've kind of left my time changes to 20.1 as it's a large batch which is
sometimes hard to make compatible. There'd be a slew of PRs which together
I think is relatively high risk.

**Comment by awoods187** [comment]
I'm fine avoiding the backport if it's risky.

**Pull request merged**
