### PR TITLE
opt: add CommuteJoin rule

### PR DESCRIPTION
**Pull request by RaduBerinde**
Adding a CommuteJoin rule and simplifying the code that generates
merge joins. This will also simplify upcoming rules for lookup join.

Note that this can lead to more MergeJoin expressions in the memo
(when both sides present the same interesting ordering).

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
I pushed a commit that adjusts the hash join cost to prefer a smaller right side. This should be a nice improvement over 2.0.

**Comment by rytaft** [comment]
This looks good to me, just a couple of questions
1. There are several tests where the merge join was preferred before, and now it has reverted to hash join. Do you think those diffs are all reasonable?
2. One concern that was brought up at our recent meetings was that since we don't have real stats right now, the optimizer could make the wrong choice about join ordering, and there is no way to override. Do you think we need some sort of override mechanism, or should we just tell dissatisfied customers to turn the optimizer off if they are getting the wrong join order?

---

Reviewed 6 of 6 files at r1, 15 of 15 files at r2.
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/opt/xform/rules/join.opt, line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27081#-LGCKl3vDoUQCcnSGPdt:-LGCKl3wBaGnrQhWWXvV:b-7rhlu2) ([raw file](https://github.com/cockroachdb/cockroach/blob/37340b9031481271cc6373667602582e962fc5df/pkg/sql/opt/xform/rules/join.opt#L5)):*
> ```
> # =============================================================================
> 
> # CommuteJoin creates a Join with the left and right inputs swaped. This is
> ```

swaped -> swapped

---

*[pkg/sql/opt/xform/testdata/external/tpch, line 2109 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27081#-LGCMkz74PpVcPKB52Ou:-LGCMkz74PpVcPKB52Ov:by3m6s2) ([raw file](https://github.com/cockroachdb/cockroach/blob/394be929db8b06deed1aa453d883bbc8e981014d/pkg/sql/opt/xform/testdata/external/tpch#L2109)):*
> ```
>  ├── key: ()
>  ├── fd: ()-->(27)
>  ├── project
> ```

Is this a good thing that we're no longer choosing the merge join?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27081#-:-LGCN8qW8Qr-j4x4-Z-H:banojcn)*

**Comment by RaduBerinde** [comment]
TFTR!

I adjusted the cost a bit, I believe I restored the previous choices for merge vs hash.

On 2, this does not affect multi-join ordering, it just affects the execution of each individual join. So the difference even if we make the wrong choice shouldn't be too dramatic in most cases. It's still a good question whether we want some kind of override, not sure..

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/opt/xform/rules/join.opt, line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27081#-LGCKl3vDoUQCcnSGPdt:-LGCSOTI0DaOOrgob5P_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/37340b9031481271cc6373667602582e962fc5df/pkg/sql/opt/xform/rules/join.opt#L5)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

swaped -> swapped
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/testdata/external/tpch, line 2109 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27081#-LGCMkz74PpVcPKB52Ou:-LGCSOvV6S8aCbP1gKX0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/394be929db8b06deed1aa453d883bbc8e981014d/pkg/sql/opt/xform/testdata/external/tpch#L2109)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Is this a good thing that we're no longer choosing the merge join?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27081#-:-LGCS3CmCIc3Gh2n3-Ua:bxe4mdg)*

**Comment by rytaft** [comment]
:lgtm: Maybe wait for Andy to weigh in on the need for an override

---

Reviewed 7 of 7 files at r3.
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27081#-:-LGCWYGE3NrnDhmo7-aX:b19ag1l)*

**Comment by RaduBerinde** [comment]
Updated. I split the rule in three, I wasn't changing a left-join to a right-join when swapping (and vice-versa).

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 2 of 17 files at r4, 14 of 14 files at r5.
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/opt/norm/testdata/rules/combo, line 283 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/27081#-LGRZH0Y0D3NC5LaeykB:-LGRZH0Z9NXxZjIfkQv3:b-mwmzs2) ([raw file](https://github.com/cockroachdb/cockroach/blob/787766e1336c926b02bc05a5150161471bb24d36/pkg/sql/opt/norm/testdata/rules/combo#L283)):*
> ```
>               └── a.k = xy.x [type=bool, outer=(1,6), constraints=(/1: (/NULL - ]; /6: (/NULL - ])]
> --------------------------------------------------------------------------------
> GenerateIndexScans (higher cost)
> ```

I think you need to run `make generate`

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27081#-:-LGR_FgB9VTzOMYG5HfW:bnfp4nl)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/opt/norm/testdata/rules/combo, line 283 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/27081#-LGRZH0Y0D3NC5LaeykB:-LGRb2v06S3dFPGUGokP:b-c5bdxq) ([raw file](https://github.com/cockroachdb/cockroach/blob/787766e1336c926b02bc05a5150161471bb24d36/pkg/sql/opt/norm/testdata/rules/combo#L283)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I think you need to run `make generate`
</blockquote></details>

I think I forgot in the previous version :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27081)*

**Comment by rytaft** [comment]
*[pkg/sql/opt/norm/testdata/rules/combo, line 283 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/27081#-LGRZH0Y0D3NC5LaeykB:-LGRbYmK3eIv3DA9jKrO:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/787766e1336c926b02bc05a5150161471bb24d36/pkg/sql/opt/norm/testdata/rules/combo#L283)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I think I forgot in the previous version :)
</blockquote></details>

:thumbsup: 

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27081)*

**Comment by andy-kimball** [comment]
:lgtm:

---

Review status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/opt/exec/execbuilder/testdata/join, line 49 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/27081#-LGRh8lt5YULUsxl7gOG:-LGRh8lu67xy1y1-pK21:bpni9py) ([raw file](https://github.com/cockroachdb/cockroach/blob/787766e1336c926b02bc05a5150161471bb24d36/pkg/sql/opt/exec/execbuilder/testdata/join#L49)):*
> ```
> ]
> ----
> render          ·         ·
> ```

How come an extra render gets created now?

---

*[pkg/sql/opt/xform/testdata/rules/join, line 84 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/27081#-LGRiR5B2xXSZ7trqI-_:-LGRiR5B2xXSZ7trqI-a:bjtqp7x) ([raw file](https://github.com/cockroachdb/cockroach/blob/787766e1336c926b02bc05a5150161471bb24d36/pkg/sql/opt/xform/testdata/rules/join#L84)):*
> ```
> # --------------------------------------------------
> 
> memo
> ```

Why use `memo` rather than `opt` (or maybe in addition to)? I'd have test cases where we filter one side and not the other, and make sure we flip the sides so that the smaller set is on the right. Perhaps it's my personal preference to favor `opt`, because I do find it easier to read and verify its correctness.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27081#-:-LGRioGQB9OTftW0fq9i:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

---

*[pkg/sql/opt/exec/execbuilder/testdata/join, line 49 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/27081#-LGRh8lt5YULUsxl7gOG:-LGS7Nv_2q3Vgqyo4NtL:baav6co) ([raw file](https://github.com/cockroachdb/cockroach/blob/787766e1336c926b02bc05a5150161471bb24d36/pkg/sql/opt/exec/execbuilder/testdata/join#L49)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

How come an extra render gets created now?
</blockquote></details>

We have to rearrange the columns (they happened to match the join node output before).

---

*[pkg/sql/opt/xform/testdata/rules/join, line 84 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/27081#-LGRiR5B2xXSZ7trqI-_:-LGUy9z456t_Bt2YC0Lp:b-hs3imm) ([raw file](https://github.com/cockroachdb/cockroach/blob/787766e1336c926b02bc05a5150161471bb24d36/pkg/sql/opt/xform/testdata/rules/join#L84)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Why use `memo` rather than `opt` (or maybe in addition to)? I'd have test cases where we filter one side and not the other, and make sure we flip the sides so that the smaller set is on the right. Perhaps it's my personal preference to favor `opt`, because I do find it easier to read and verify its correctness.
</blockquote></details>

Memo ones are useful to see that the correct expressions get added to the memo, and that we don't add duplicates. I added these tests before adjusting the coster so there wasn't really a way to see the result with `opt`. You're right that I can now add tests with a smaller left side, done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27081)*

**Pull request merged**
