### PR TITLE
jobspb: allow progress to be either a fraction or a timestamp highwater

### PR DESCRIPTION
**Pull request by danhhz**
It's been named lowwater since it was introduced, but it's really been a
highwater all along. Renamed for consistency with the newly introduced
generalized job progress `highwater`.

Release note: None

### CODE REVIEW

**Review by benesch — COMMENTED** [review]
I think this makes a lot of sense! Two high-level thoughts:

1. What are we going to do with `SHOW JOBS`? Just add another `highwater` column? The admin UI is actually much easier because we can just switch between the progress bar and the high-water timestamp.

2. The term "highwater" is exactly opposite from what restore uses ("lowwater"). I _think_ they're referring to the same thing. Perhaps neither of these terms is clear enough? 

> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28043#-:-LIgBD_Q8z3Hm9OZckYm:b-lap0wy)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by danhhz — COMMENTED** [review]
> What are we going to do with SHOW JOBS? Just add another highwater column? The admin UI is actually much easier because we can just switch between the progress bar and the high-water timestamp.

Yeah, that's what I'm thinking. Was planning on a followup PR for SHOW JOBS/crdb_internal.jobs.

> The term "highwater" is exactly opposite from what restore uses ("lowwater"). I think they're referring to the same thing. Perhaps neither of these terms is clear enough?

That's an interesting observation. I could rename the field to something more general, like timestamp. But dunno that RESTORE would use it even then, since the lowwater there isn't externally observable in any way and the current fraction_completed is a better indicator of progress for the user. Or did you have something else in mind?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28043#-:-LIgWtwV4reUfsOEgAN8:bx7lffx)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by benesch** [comment]
> That's an interesting observation. I could rename the field to something more general, like timestamp. But dunno that RESTORE would use it even then, since the lowwater there isn't externally observable in any way and the current fraction_completed is a better indicator of progress for the user. Or did you have something else in mind?

Yeah, definitely not a problem that impacts end-users, but I'm personally now very confused about the meaning of lowwater/highwater in this context. I don't have something else in mind, but there must be some actual term for this! Maybe @arjunravinarayan knows something from data flow land?

**Comment by danhhz** [comment]
> Yeah, definitely not a problem that impacts end-users, but I'm personally now very confused about the meaning of lowwater/highwater in this context. I don't have something else in mind, but there must be some actual term for this! Maybe @arjunravinarayan knows something from data flow land?

Oh, now that I think about it more closely, restore's should also be called a highwater

**Comment by benesch** [comment]
> Oh, now that I think about it more closely, restore's should also be called a highwater

Yeah, just renaming that field SGTM.

**Comment by danhhz** [comment]
Okay, I think this is ready to go @benesch

**Review by benesch — APPROVED** [review]
:lgtm_strong:

> Reviewed 5 of 5 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28043#-:-LIgyTIt2RRKyIIVw3_T:b-jbsf8z)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/jobs/jobspb/jobs.proto, line 169 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28043#-LIgxouC-NCJp8zC_cHJ:-LIgxouC-NCJp8zC_cHK:b-7lm8oj) ([raw file](https://github.com/cockroachdb/cockroach/blob/de27c2e4b7425c4936b774a33f452e985e87ec0b/pkg/sql/jobs/jobspb/jobs.proto#L169)):*
> ```protobuf
>   oneof progress {
>     float fraction_completed = 1;
>     util.hlc.Timestamp highwater = 3;
> ```

This reads funny to me. High water is two words, so my brain wants `high_water` or `highWater`. I don't care that much though.

**Review by danhhz — COMMENTED** [review]
Thanks for the review!

bors r=benesch

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28043#-:-LIhIr4ECR5CTgCH26wL:bqx2naq)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/jobs/jobspb/jobs.proto, line 169 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28043#-LIgxouC-NCJp8zC_cHJ:-LIhIgzu2Ipz2aUyx3hN:b-bn7rt4) ([raw file](https://github.com/cockroachdb/cockroach/blob/de27c2e4b7425c4936b774a33f452e985e87ec0b/pkg/sql/jobs/jobspb/jobs.proto#L169)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

This reads funny to me. High water is two words, so my brain wants `high_water` or `highWater`. I don't care that much though. 
</blockquote></details>

Googled around a bit and I'm surprised by how uncommon "highwater" is as a shortening. Done, here and everywhere I found.

**Pull request merged**
