### PR TITLE
colexec: make hash joiner more dynamic

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: clean up the hash joiner a bit**

When we have unmatched tuples from the left in case of left/full outer
hash joins, we still copy the whole vectors according to `buildIdx`
selection vector from the right side and then set nulls only for the
tuples that didn't have a match. Such approach is a lot more performant
then if we were to check for each tuple whether it had a match and copy
only the matched ones. This works ok since we assume that `buildIdx`
value for unmatched tuples is left as 0 which we didn't explicitly do in
distinctCollect variation. Note that it still worked correctly in all
cases (both in in-memory hash joiner and external hash joiner) because
we're zeroing out the slice when resetting (which is important for the
external hash joiner).

Given the observation that we're now always setting the correct values
in `buildIdx`, `probeIdx`, `probeRowUnmatched`, this commit additionally
removes zeroing out of those slices during resetting.

Release note: None

**colexec: make hash joiner more dynamic**

This commit refactors the hash joiner slightly in order to avoid
allocating slices with big fixed size which makes the algorithm more
dynamic.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
The benchmarks [here](https://gist.github.com/yuzefovich/32ac6fb7397d6eedc0111e88f99388f7) don't show significant changes (which is expected).

In order to make the hash joiner truly dynamic, we'll need to reduce the initial number of buckets used by the hash table (currently at `coldata.BatchSize()`). This will require retuning some constants (probably), and I started looking into that, but I think this PR can proceed as is.

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56783)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/hashjoiner.go, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56783#-MMKg9jq9oJ79otXa_SW:-MMKg9jq9oJ79otXa_SX:bl2yu9p) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe910e6c3a574029f10819e8aa17b5ecb624f00e/pkg/sql/colexec/hashjoiner.go#L82)):*
> ```Go
> 
> 	// outer specifies whether an outer join is required over the input.
> 	outer bool
> ```

Why remove this field? It seems like you have to rewrite the same condition multiple times. It might be nice to make it a `joinType` method.
___
*[pkg/sql/colexec/hashjoiner_tmpl.go, line 144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56783#-MMKcvSH8uZ1_qWXeNdn:-MMKcvSH8uZ1_qWXeNdo:bmmrltr) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe910e6c3a574029f10819e8aa17b5ecb624f00e/pkg/sql/colexec/hashjoiner_tmpl.go#L144)):*
> ```Go
> 		id := hj.ht.probeScratch.groupID[i]
> 		hj.probeState.probeRowUnmatched[i] = id == 0
> 		if id > 0 {
> ```

Why not keep the `rowUnmatched` variable and switch the if clauses (i.e. `if rowUnmatched { buildIdx = 0} else { buildIdx = id - 1}`)

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56783)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/hashjoiner.go, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56783#-MMKg9jq9oJ79otXa_SW:-MMM5Nwn1PXMOst3Ne2k:b-j876r2) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe910e6c3a574029f10819e8aa17b5ecb624f00e/pkg/sql/colexec/hashjoiner.go#L82)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why remove this field? It seems like you have to rewrite the same condition multiple times. It might be nice to make it a `joinType` method.
</blockquote></details>

This field is currently being used only for left/full outer joins, yet it is also set for right outer joins but not used. I find that spelling out the join types explicitly in this case to be easier to read, so minor repetition doesn't bother me.

I also don't see a good understandable method name on `joinType` that would return `true` for left and full outer joins only.
___
*[pkg/sql/colexec/hashjoiner_tmpl.go, line 144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56783#-MMKcvSH8uZ1_qWXeNdn:-MMM57D5DrE_8CFoaTpO:btnmmk5) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe910e6c3a574029f10819e8aa17b5ecb624f00e/pkg/sql/colexec/hashjoiner_tmpl.go#L144)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why not keep the `rowUnmatched` variable and switch the if clauses (i.e. `if rowUnmatched { buildIdx = 0} else { buildIdx = id - 1}`)
</blockquote></details>

This is what we have in `collectProbeOuter` above, so I made this change for consistency.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56783#-:-MMPxDia1Y97IiZmPc1w:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/hashjoiner.go, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56783#-MMKg9jq9oJ79otXa_SW:-MMPwkA02qSCU7CRIwTm:b-r3axcq) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe910e6c3a574029f10819e8aa17b5ecb624f00e/pkg/sql/colexec/hashjoiner.go#L82)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

This field is currently being used only for left/full outer joins, yet it is also set for right outer joins but not used. I find that spelling out the join types explicitly in this case to be easier to read, so minor repetition doesn't bother me.

I also don't see a good understandable method name on `joinType` that would return `true` for left and full outer joins only.
</blockquote></details>

`IsLeftOrFullOuterJoin`?
___
*[pkg/sql/colexec/hashjoiner_tmpl.go, line 144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56783#-MMKcvSH8uZ1_qWXeNdn:-MMPwq5F7kT2_61m6XoV:b-n87bbe) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe910e6c3a574029f10819e8aa17b5ecb624f00e/pkg/sql/colexec/hashjoiner_tmpl.go#L144)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

This is what we have in `collectProbeOuter` above, so I made this change for consistency.
</blockquote></details>

Maybe you could change `collectProbeOuter` to be more like the previous version of this code. I like the named variable and the `else` in the new version also implies `id < 0`. Anyway, this is more of a nit than anything else, so feel free to ignore.

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56783#-:-MMREO6X0kg8hsG_nStv:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

___
*[pkg/sql/colexec/hashjoiner.go, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56783#-MMKg9jq9oJ79otXa_SW:-MMRHEdv9Yz_oC0ULXUU:b-6ybiy0) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe910e6c3a574029f10819e8aa17b5ecb624f00e/pkg/sql/colexec/hashjoiner.go#L82)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

`IsLeftOrFullOuterJoin`?
</blockquote></details>

Ok, I added several utility methods like this for consistency.
___
*[pkg/sql/colexec/hashjoiner_tmpl.go, line 144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56783#-MMKcvSH8uZ1_qWXeNdn:-MMREJln6ZRlO7ntI4N1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe910e6c3a574029f10819e8aa17b5ecb624f00e/pkg/sql/colexec/hashjoiner_tmpl.go#L144)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Maybe you could change `collectProbeOuter` to be more like the previous version of this code. I like the named variable and the `else` in the new version also implies `id < 0`. Anyway, this is more of a nit than anything else, so feel free to ignore.
</blockquote></details>

Done.

**Pull request merged**
