### PR TITLE
server: use the internalClientAdapter on in-process tenants 

### PR DESCRIPTION
**Pull request by andreimatei**
This patch makes tenants talking to in-process KV servers bypass gRPC
for Batch requests by using the internalClientAdapter, just like the
non-tenant code does.

Using the adapter has a big effect on the latency of small queries,
showing things like:
```
SQL/TenantCockroach/Delete/count=1-24                        973µs ± 6%    723µs ± 6%  -25.65%  (p=0.008 n=5+5)
SQL/TenantCockroach/Delete/count=10-24                      1.11ms ± 1%   0.86ms ± 2%  -22.75%  (p=0.008 n=5+5)
SQL/TenantCockroach/Delete/count=100-24                     2.20ms ± 3%   1.98ms ± 5%   -9.98%  (p=0.008 n=5+5)
```
Full BenchSQL results in
https://gist.github.com/andreimatei/67a39b71091f8254d471d25efb53c01d

Release note: None
Epic: CRDB-14537
Informs: #84591

### CODE REVIEW

**Comment by andreimatei** [comment]
Only the first commit is to be reviewed here.

**Review by knz — COMMENTED** [review]
> Only the first commit is to be reviewed here.

I didn't see this as first. Did you mean the last?
Anyway I looked at all of them. All commits but the last LGTM and are good to merge.

For the last commit (the main one)  I am largely OK with the architecture. But I have a few comments and questions stills.

> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 3 of 3 files at r6, 19 of 19 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-:-NJGI8vf6UjCtO74rdmq:b-luu8cj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[`pkg/rpc/context.go` line 661 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-NJGIvOV8NK42VLFV-33:-NJGIvOV8NK42VLFV-34:b-pw3tj2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b95a3187df04492a376d39cd3143bb22290275d1/pkg/rpc/context.go#L661)):*
> ```Go
> // https://github.com/cockroachdb/cockroach/pull/73309
> func (rpcCtx *Context) GetLocalInternalClientForAddr(
> 	ctx context.Context, nodeID roachpb.NodeID,
> ```

you don't need the ctx; you can remove it, which will allow you to drop the (new) use of `context.TODO` below as well.
___
*[`pkg/rpc/context.go` line 757 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-NJGIjU6EP-8lVGJqcyi:-NJGIjU91SEY0E20I746:bposyyl) ([raw file](https://github.com/cockroachdb/cockroach/blob/b95a3187df04492a376d39cd3143bb22290275d1/pkg/rpc/context.go#L757)):*
> ```Go
> 			// Create a new context from the existing one with the "local request" field set.
> 			// This tells the handler that this is an in-process request, bypassing ctx.Peer checks.
> 			ctx = grpcutil.NewLocalRequestContext(ctx, log.ServerIdentificationFromContext(ctx).TenantID().(roachpb.TenantID))
> ```

If we start relying on the server ID payload in non-logging code, we should extract this functionality into a top-level package out of `log`.

Alternatively perhaps you could use the new IsLocalRequestContext instead?

Incidentally, it seems strange to me that we store the tenant ID _both_ in a server ID payload _and_ also with the localRequestKey. 
I do remember we talked about this, but I don't recall what we said. Could you write something about this in comments around ServerIdentificationFromContext and IsLocalRequestContext?
___
*[`pkg/server/status.go` line 578 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-NJGJG1d66ZgBIbMJFxc:-NJGJG1d66ZgBIbMJFxd:b-rvhrl1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b95a3187df04492a376d39cd3143bb22290275d1/pkg/server/status.go#L578)):*
> ```Go
> ) *statusServer {
> 	ambient.AddLogTag("status", nil)
> 	ambient.AddLogTag("tenant1", rpcCtx.TenantID)
> ```

this can be reverted.
___
*[`pkg/util/grpcutil/grpc_util.go` line 42 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-NJGJg772zyVzKc4TMtt:-NJGJg772zyVzKc4TMtu:b-22idx3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b95a3187df04492a376d39cd3143bb22290275d1/pkg/util/grpcutil/grpc_util.go#L42)):*
> ```Go
> // IsLocalRequestContext returns true if this context is marked for local (in-process) use.
> func IsLocalRequestContext(ctx context.Context) (roachpb.TenantID, bool) {
> 	val := ctx.Value(localRequestKey{})
> ```

see my comment above.

Also, another interesting problem: how do you envision the following chain of calls to work:

- tenant 123 makes KV request to KV layer (uses local client interface, with a tenant boundary)
- KV layer then makes another KV request to itself (target node ID = local node ID). We also want that to use the local client interface, *but without a tenant boundary*. 

How does this second call learn that it should not be using the tenant ID of the original request in the context?
I think what's needed here is for the local client interface to override the tenant ID to system tenant ID. But I don't see it in your PR yet. If it works already, maybe you can add a few words in your commit message to explain how that works.
___
*[`pkg/util/tracing/grpcinterceptor/grpc_interceptor.go` line 255 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-NJGL4P46R6goUv5pzPh:-NJGL4P46R6goUv5pzPi:b-d598ax) ([raw file](https://github.com/cockroachdb/cockroach/blob/b95a3187df04492a376d39cd3143bb22290275d1/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L255)):*
> ```Go
> 			// Tracer, which is illegal.
> 			parentOpt = tracing.WithRemoteParentFromLocalSpan(tracing.SpanFromContext(ctx))
> 			tracer = localKVTracer
> ```

In this case, where is the code that pulls the trace recording from the sub-span into the recording of the parent (tenant) span?
___
*[`pkg/util/tracing/grpcinterceptor/grpc_interceptor.go` line 337 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-NJGLBz11ltgFTSkXSX3:-NJGLBz11ltgFTSkXSX4:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/b95a3187df04492a376d39cd3143bb22290275d1/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L337)):*
> ```Go
> 			// Tracer, which is illegal.
> 			parentOpt = tracing.WithRemoteParentFromLocalSpan(tracing.SpanFromContext(ctx))
> 			tracer = localKVTracer
> ```

ditto

**Review by andreimatei — COMMENTED** [review]
I meant the last commit, yeah. But I've worked on this more; now all commits are original.

cc @ajwerner for the first commit (`rpc: don't require address to get internalClientAdapter`)
cc @ajstorm for the 2nd commit (`server: add test utility for shared-process tenant`)

Thanks for reading!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-:-NJGmiLL1NQoXU-RY5SB:b-jut1q2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @knz, and @srosenberg)

___
*[`pkg/rpc/context.go` line 661 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-NJGIvOV8NK42VLFV-33:-NJGn7grB4Jm6bMqaZY-:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b95a3187df04492a376d39cd3143bb22290275d1/pkg/rpc/context.go#L661)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

you don't need the ctx; you can remove it, which will allow you to drop the (new) use of `context.TODO` below as well.
</blockquote></details>

done
___
*[`pkg/rpc/context.go` line 757 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-NJGIjU6EP-8lVGJqcyi:-NJSzmsZBtyd2TZGlKpO:b-6qaokn) ([raw file](https://github.com/cockroachdb/cockroach/blob/b95a3187df04492a376d39cd3143bb22290275d1/pkg/rpc/context.go#L757)):*
> If we start relying on the server ID payload in non-logging code, we should extract this functionality into a top-level package out of log.

Moved to a new pkg under `base`.

> Alternatively perhaps you could use the new IsLocalRequestContext instead?

`IsLocalRequestContext` is the pair of `NewLocalRequestContext` - which is what we're doing here, so I'm not sure I understand. Maybe you meant something else?

> Incidentally, it seems strange to me that we store the tenant ID both in a server ID payload and also with the localRequestKey.

Well, they're different things. In the ServerIdentification thing, the tenantID refers to the server's tenant. In the request key, it refers to the tenant that's the client of an RPC. 
___
*[`pkg/util/grpcutil/grpc_util.go` line 42 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-NJGJg772zyVzKc4TMtt:-NJT0A272yvFCtO56apN:b-4010fg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b95a3187df04492a376d39cd3143bb22290275d1/pkg/util/grpcutil/grpc_util.go#L42)):*
> How does this second call learn that it should not be using the tenant ID of the original request in the context?

In the 2nd call, the `NewLocalRequestContext()` done by the `internalClientAdapter` will use KV's server identifier. When the 1st RPC gets to the server, the ctx is annotated with KV's identity through one of the many `AmbientContexts`.
___
*[`pkg/util/tracing/grpcinterceptor/grpc_interceptor.go` line 255 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-NJGL4P46R6goUv5pzPh:-NJGn_jAEtz0dXb-3eWC:b-p1ydha) ([raw file](https://github.com/cockroachdb/cockroach/blob/b95a3187df04492a376d39cd3143bb22290275d1/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L255)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

In this case, where is the code that pulls the trace recording from the sub-span into the recording of the parent (tenant) span?
</blockquote></details>

This is where that happens for the `Batch` RPC: https://github.com/cockroachdb/cockroach/blob/c7537a37cf893e4eedfc7a00010a3dd7dbee6c64/pkg/kv/kvclient/kvcoord/transport.go#L231
Other RPCs don't have trace collection. DistSQL does a different thing, whereby trace recordings make it to the gateway as flow metadata messages.

Anyway, I've changed my mind about how to deal with tracing, so this code changed; I've reverted this interceptor to not dealing with local requests. See changes to `internalClientAdapter` instead. 
___
*[`pkg/server/status.go` line 578 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-NJGJG1d66ZgBIbMJFxc:-NJGnIcRC5TId9wGCwAV:b32vj2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b95a3187df04492a376d39cd3143bb22290275d1/pkg/server/status.go#L578)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

this can be reverted.
</blockquote></details>

:S

**Review by abarganier — APPROVED** [review]
:lgtm_strong: - heads up that there will be some minor merge conflicts with https://github.com/cockroachdb/cockroach/pull/94432
related to the repackaging of `ServerIdentificationPayload` out of `pkg/util/log` (for whoever loses the merge race :stuck_out_tongue:). 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-:-NKxoLtl9rGkdI8LyOSn:b-q03vl0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @herkolategan, @knz, and @srosenberg)

___
*[`pkg/util/tracing/grpcinterceptor/grpc_interceptor.go` line 255 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-NJGL4P46R6goUv5pzPh:-NKxnEXVBJuAtklqW4R9:b-pmwxx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b95a3187df04492a376d39cd3143bb22290275d1/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L255)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

This is where that happens for the `Batch` RPC: https://github.com/cockroachdb/cockroach/blob/c7537a37cf893e4eedfc7a00010a3dd7dbee6c64/pkg/kv/kvclient/kvcoord/transport.go#L231
Other RPCs don't have trace collection. DistSQL does a different thing, whereby trace recordings make it to the gateway as flow metadata messages.

Anyway, I've changed my mind about how to deal with tracing, so this code changed; I've reverted this interceptor to not dealing with local requests. See changes to `internalClientAdapter` instead. 
</blockquote></details>

Changes in `internalClientAdapter` to handle this :lgtm:

**Comment by andreimatei** [comment]
@knz please give this another review
cc @ajstorm

**Review by knz — COMMENTED** [review]
I like the simplification.

> Reviewed 39 of 39 files at r21, 13 of 13 files at r22, 1 of 1 files at r23, 1 of 1 files at r24, 5 of 5 files at r25, 36 of 37 files at r26, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-:-NLX8R0j5V76NNqV7WpA:b-x4zvvd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm and @andreimatei)

___
*[`-- commits` line 30 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-NLX4hz8DceXxhhNvzJf):*
That is incorrect.  *Different* knobs are used in that case: BaseConfig.SecondaryTenantKnobs from the KV server.
___
*[`pkg/cli/democluster/demo_cluster.go` line 405 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-NLX4xIoDHbtOy-Z3sHf:-NLX4xIoDHbtOy-Z3sHg:b-v1y76) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b4d15c05cc0432c49f2274865fe5eafb95cad1c/pkg/cli/democluster/demo_cluster.go#L405)):*
> ```Go
> 
> 				var ts serverutils.TestTenantInterface
> 				if c.demoCtx.DisableServerController {
> ```

Beware that we do not _currently_ have unit tests for the behavior under DisableServerController, so we'll need to hand-test this.
___
*[`pkg/cli/democluster/demo_cluster.go` line 408 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-NLX576GEnDfxHx3peNC:-NLX576GEnDfxHx3peND:b-k0e90t) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b4d15c05cc0432c49f2274865fe5eafb95cad1c/pkg/cli/democluster/demo_cluster.go#L408)):*
> ```Go
> 					tenantStopper := stop.NewStopper()
> 					args := base.TestTenantArgs{
> 						// We set the tenant ID to i+2, since tenant 0 is not a tenant, and
> ```

This comment is stale and can be removed.
___
*[`pkg/cli/interactive_tests/test_log_config_msg.tcl` line 13 at r26](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-NLX7TX53mNlvrvPWMRP:-NLX7TX53mNlvrvPWMRQ:b6nqt1o) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6273b1f305412c88f4194cd37fe75d2edd09684/pkg/cli/interactive_tests/test_log_config_msg.tcl#L13)):*
> ```Tcl
> spawn tail -n 1000 -F logs/db/logs/cockroach.log
> eexpect "node startup completed"
> eexpect "start.go*ClusterID:"
> ```

please don't change this.  We've learned that we have customer automation that parses it.
___
*[`pkg/rpc/context.go` line 757 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-NJGIjU6EP-8lVGJqcyi:-NLX7fhL6SVhq5U5SjRh:bm2c7qp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b95a3187df04492a376d39cd3143bb22290275d1/pkg/rpc/context.go#L757)):*
This is pretty good. Thank you.

> Well, they're different things. In the ServerIdentification thing, the tenantID refers to the server's tenant. In the request key, it refers to the tenant that's the client of an RPC.

Can you emphasize this difference in explanatory comments above each interface; and also in the commit message. Thanks.
___
*[`pkg/rpc/context.go` line 980 at r26](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-NLX7oWX3C_fkZj_fdcD:-NLX7oWX3C_fkZj_fdcE:b-umifxv) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6273b1f305412c88f4194cd37fe75d2edd09684/pkg/rpc/context.go#L980)):*
> ```Go
> 	ctx context.Context, args *roachpb.RangeFeedRequest, opts ...grpc.CallOption,
> ) (roachpb.Internal_RangeFeedClient, error) {
> ```

nit: empty line.
___
*[`pkg/server/server_controller.go` line 173 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-NLX5ijD0-llxmmTh77s:-NLX5ijD0-llxmmTh77t:b-rzjcpi) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b4d15c05cc0432c49f2274865fe5eafb95cad1c/pkg/server/server_controller.go#L173)):*
> ```Go
> 	defer c.mu.Unlock()
> 	if s, ok := c.mu.servers[tenantName]; ok {
> 		if errorOnExistingName {
> ```

I don't understand what you did here. Why is this needed? Can you walk me through it step by step?
___
*[`pkg/server/testserver.go` line 812 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-NLX5oUR1sDYgWSijd23:-NLX5oUR1sDYgWSijd24:brnlqrj) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b4d15c05cc0432c49f2274865fe5eafb95cad1c/pkg/server/testserver.go#L812)):*
> ```Go
> ) (serverutils.TestTenantInterface, *gosql.DB, error) {
> 	// Insert the tenant metadata.
> 	_, err := ts.InternalExecutor().(*sql.InternalExecutor).ExecEx(
> ```

The fact this is unconditional seems wrong. In e.g. `cockroach demo --nodes 3`, we want 3 in-memory servers for just 1 tenant. The tenant should be created only 1 time.
___
*[`pkg/util/grpcutil/grpc_util.go` line 42 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-NJGJg772zyVzKc4TMtt:-NLX8-jCAL19ZW9kO7qv:b-ff4wuy) ([raw file](https://github.com/cockroachdb/cockroach/blob/b95a3187df04492a376d39cd3143bb22290275d1/pkg/util/grpcutil/grpc_util.go#L42)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> How does this second call learn that it should not be using the tenant ID of the original request in the context?

In the 2nd call, the `NewLocalRequestContext()` done by the `internalClientAdapter` will use KV's server identifier. When the 1st RPC gets to the server, the ctx is annotated with KV's identity through one of the many `AmbientContexts`.
</blockquote></details>

Very nice. Can you explain this in the commit message too (with an example).
___
*[`pkg/base/serverident/server_ident.go` line 24 at r26](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-NLX7KaM1zeMC8qDOPO8:-NLX7KaM1zeMC8qDOPO9:bqqofhm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6273b1f305412c88f4194cd37fe75d2edd09684/pkg/base/serverident/server_ident.go#L24)):*
> ```Go
> type ServerIdentificationContextKey struct{}
> 
> func ContextWithServerIdentification(
> ```

Can you docstring this and the below.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93559)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm, @knz, and @miretskiy)

___
*[`-- commits` line 30 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-NLX4hz8DceXxhhNvzJf):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

That is incorrect.  *Different* knobs are used in that case: BaseConfig.SecondaryTenantKnobs from the KV server.
</blockquote></details>

Except that nobody reads `TestArgs.SecondaryTenantKnobs` to copy them to a `BaseConfig` lolo. But good thing you told me about it; I've prepended a commit getting rid of `TestArgs.SecondaryTenantKnobs` now that they can be passed in explicitly to `StartSharedProcessTenant`.
Your point is taken though that I've misinterpreted the `demo_cluster` code when writing this message: I assumed that the `TestingKnobs` I was referring to were intended to work both when `UseServerController` is set and when it's not set - because all the other args that are specific to `!UseServerController` were set conditionally, elsewhere. I've also prepended a commit moving them where they belong.
___
*[`pkg/cli/democluster/demo_cluster.go` line 405 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-NLX4xIoDHbtOy-Z3sHf:-NLXV1hm8SJsJ69YhSN1:b3ac9g7) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b4d15c05cc0432c49f2274865fe5eafb95cad1c/pkg/cli/democluster/demo_cluster.go#L405)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Beware that we do not _currently_ have unit tests for the behavior under DisableServerController, so we'll need to hand-test this.
</blockquote></details>

I launched `demo` with the flag, fwiw.
___
*[`pkg/cli/democluster/demo_cluster.go` line 408 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-NLX576GEnDfxHx3peNC:-NLXUv1FAZO9KDvwjAB2:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b4d15c05cc0432c49f2274865fe5eafb95cad1c/pkg/cli/democluster/demo_cluster.go#L408)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

This comment is stale and can be removed.
</blockquote></details>

done
___
*[`pkg/rpc/context.go` line 757 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-NJGIjU6EP-8lVGJqcyi:-NLY-ao26nmAFzvXFEYf:b3vz150) ([raw file](https://github.com/cockroachdb/cockroach/blob/b95a3187df04492a376d39cd3143bb22290275d1/pkg/rpc/context.go#L757)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

This is pretty good. Thank you.

> Well, they're different things. In the ServerIdentification thing, the tenantID refers to the server's tenant. In the request key, it refers to the tenant that's the client of an RPC.

Can you emphasize this difference in explanatory comments above each interface; and also in the commit message. Thanks.
</blockquote></details>

I sprinkled comments in a couple of places. Also renamed some of these ctx methods to be more suggestive.
___
*[`pkg/rpc/context.go` line 980 at r26](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-NLX7oWX3C_fkZj_fdcD:-NLY-mFrENV4w5Y9zZRm:b-hfpv0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6273b1f305412c88f4194cd37fe75d2edd09684/pkg/rpc/context.go#L980)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: empty line.
</blockquote></details>

removed
___
*[`pkg/server/server_controller.go` line 173 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-NLX5ijD0-llxmmTh77s:-NLY3c7N2FyRVDHOJ9nK:b-busku0) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b4d15c05cc0432c49f2274865fe5eafb95cad1c/pkg/server/server_controller.go#L173)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I don't understand what you did here. Why is this needed? Can you walk me through it step by step?
</blockquote></details>

I didn't do much; I've extracted this `getOrCreateServerInner` method to be called directly from the `TestServer`, so that the `TestServer` can pass in the args. This `errorOnExistingName` was used by the `TestServer` to say that it doesn't want to tolerate the server already existing. But now that you point to this, I wasn't happy with the structure I put in; I don't know how I ended up in such a random place. See now, I've massaged it a bit more.

Does it help?
___
*[`pkg/server/testserver.go` line 812 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-NLX5oUR1sDYgWSijd23:-NLXT3bK0QOSi4lnXHfH:bs2q7oo) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b4d15c05cc0432c49f2274865fe5eafb95cad1c/pkg/server/testserver.go#L812)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

The fact this is unconditional seems wrong. In e.g. `cockroach demo --nodes 3`, we want 3 in-memory servers for just 1 tenant. The tenant should be created only 1 time.
</blockquote></details>

yeah, figured this out the hard way. See now.
___
*[`pkg/util/grpcutil/grpc_util.go` line 42 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-NJGJg772zyVzKc4TMtt:-NLY0M5l9QdWM-j3BSia:b-7tfmjp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b95a3187df04492a376d39cd3143bb22290275d1/pkg/util/grpcutil/grpc_util.go#L42)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Very nice. Can you explain this in the commit message too (with an example).
</blockquote></details>

added
___
*[`pkg/base/serverident/server_ident.go` line 24 at r26](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-NLX7KaM1zeMC8qDOPO8:-NLXwejI0N9oapIF2P_k:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6273b1f305412c88f4194cd37fe75d2edd09684/pkg/base/serverident/server_ident.go#L24)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Can you docstring this and the below.
</blockquote></details>

done
___
*[`pkg/cli/interactive_tests/test_log_config_msg.tcl` line 13 at r26](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-NLX7TX53mNlvrvPWMRP:-NLXSqxi0CNgjR7vvT93:b-25412u) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6273b1f305412c88f4194cd37fe75d2edd09684/pkg/cli/interactive_tests/test_log_config_msg.tcl#L13)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

please don't change this.  We've learned that we have customer automation that parses it.
</blockquote></details>

this was a sed gone wrong, thanks

**Review by knz — APPROVED** [review]
> Reviewed 6 of 13 files at r30, 4 of 5 files at r33, 30 of 37 files at r34, 14 of 14 files at r35, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93559)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm, @andreimatei, and @miretskiy)

___
*[`-- commits` line 30 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-NLX4hz8DceXxhhNvzJf):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Except that nobody reads `TestArgs.SecondaryTenantKnobs` to copy them to a `BaseConfig` lolo. But good thing you told me about it; I've prepended a commit getting rid of `TestArgs.SecondaryTenantKnobs` now that they can be passed in explicitly to `StartSharedProcessTenant`.
Your point is taken though that I've misinterpreted the `demo_cluster` code when writing this message: I assumed that the `TestingKnobs` I was referring to were intended to work both when `UseServerController` is set and when it's not set - because all the other args that are specific to `!UseServerController` were set conditionally, elsewhere. I've also prepended a commit moving them where they belong.

</blockquote></details>

Thanks
___
*[`-- commits` line 174 at r35](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-NLeQ8Th4D_6xd2-wwnC):*
Maybe extend this commit message or squash it.
___
*[`pkg/server/server_controller.go` line 173 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-NLX5ijD0-llxmmTh77s:-NLePUA-8sPXQ75F8R2N:b-85mlf5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b4d15c05cc0432c49f2274865fe5eafb95cad1c/pkg/server/server_controller.go#L173)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I didn't do much; I've extracted this `getOrCreateServerInner` method to be called directly from the `TestServer`, so that the `TestServer` can pass in the args. This `errorOnExistingName` was used by the `TestServer` to say that it doesn't want to tolerate the server already existing. But now that you point to this, I wasn't happy with the structure I put in; I don't know how I ended up in such a random place. See now, I've massaged it a bit more.

Does it help?
</blockquote></details>

yes thank you :+1:

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93559)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm, @knz, and @miretskiy)

___
*[`-- commits` line 174 at r35](https://reviewable.io/reviews/cockroachdb/cockroach/93559#-NLeQ8Th4D_6xd2-wwnC):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Maybe extend this commit message or squash it.
</blockquote></details>

squashed, sorry

**Pull request merged**
