### PR TITLE
sql/catalog: consolidate the descs.Collection resolution-by-name APIs

### PR DESCRIPTION
**Pull request by thoszhang**
This PR replaces the `descs.Collection`'s methods for descriptor resolution by name, previously split across two methods (for immutable and mutable access) for each each type of descriptor except schemas, with methods `GetDatabaseByName`, `GetSchemaByName`, `GetTableByName`, and `GetTypeByName`. It deduplicates the logic previously shared (partially and inconsistently) between the immutable and mutable access implementations, as well as a third internal implementation for physical descriptor access left over from the former `UncachedPhysicalAccessor`. All the new methods aim to respect the `Required` and `Include{Dropped,Offline}` flags, which their predecessors did not consistently do.

It remains to do the same thing for the `*ByID` methods, and to abstract out the physical descriptor access with some interfaces so we can write unit tests, but this seemed like a reasonable stopping point.

See individual commits for details.

### CODE REVIEW

**Comment by lucy-zhang** [comment]
I'm not sure what we want to do about the by-ID resolution methods. I'm not convinced we actually just want `GetDescriptorByName`, since for schemas we need something that will return `catalog.ResolvedSchema` or something like it. I'm also just trying to understand what actually needs to get descriptors by ID, since the callers are all pretty disparate. In the meantime, I didn't want to sit on these changes for too long.

**Review by ajwerner — COMMENTED** [review]
Nice! Nothing really substantive from me. 

> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, 3 of 3 files at r3, 6 of 6 files at r4, 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56083#-:-MNOp-2V2BPhNXGgLEL3:b-t0aaen)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang)

___
*[pkg/sql/temporary_schema.go, line 218 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/56083#-MNOogNa9z21RCZ3qovf:-MNOogNa9z21RCZ3qovg:b3mswum) ([raw file](https://github.com/cockroachdb/cockroach/blob/093a90d37039198e58698eef67c7ff5150ba9943/pkg/sql/temporary_schema.go#L218)):*
> ```Go
> 	schemaName string,
> ) error {
> 	dbDesc, err := catalogkv.MustGetDatabaseDescByID(ctx, txn, codec, dbID)
> ```

why aren't we using the `descsCol` here? 
___
*[pkg/sql/catalog/descs/collection.go, line 285 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56083#-MNO_4-lEs1G42bHFz-4:-MNO_4-m0U5Det-Oxhea:b-4n9hps) ([raw file](https://github.com/cockroachdb/cockroach/blob/50b2cebc18d1d85f1ce7cceed2b830e52e5d4646/pkg/sql/catalog/descs/collection.go#L285)):*
> ```Go
> 	ctx context.Context, txn *kv.Txn, name string, flags tree.DatabaseLookupFlags,
> ) (catalog.DatabaseDescriptor, error) {
> 	// TODO (lucy): How does this even work? We're just returning the same
> ```

I don't think I see the problem here. 
___
*[pkg/sql/catalog/descs/collection.go, line 1310 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56083#-MNOdMM93BxP20jM9SfF:-MNOdMM93BxP20jM9SfG:b-3ey4ge) ([raw file](https://github.com/cockroachdb/cockroach/blob/50b2cebc18d1d85f1ce7cceed2b830e52e5d4646/pkg/sql/catalog/descs/collection.go#L1310)):*
> ```Go
> ) (refuseFurtherLookup bool, desc uncommittedDescriptor) {
> 	// Walk latest to earliest so that a DROP followed by a CREATE with the same
> 	// name will result in the CREATE being seen.
> ```

TODO better lookup structure lest we make N updates in a transaction N^2 operations here. 
___
*[pkg/sql/catalog/descs/collection.go, line 438 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56083#-MNOll_1AHMl_Z42Mbze:-MNOll_1AHMl_Z42Mbzf:b-d1mzem) ([raw file](https://github.com/cockroachdb/cockroach/blob/732e40a4acdba0e468f62e42353b979ac983e6f2/pkg/sql/catalog/descs/collection.go#L438)):*
> ```Go
> 
> // TODO (lucy): Should this just take a database name? We're separately
> // resolving the database name in lots of places where we (indirectly) call
> ```

On some level I think that that re-resolution is okay. We should make some decision on what you need to provide to resolve a schema: either and ID or a name. Ideally we'll make it cheap enough. 
___
*[pkg/sql/catalog/descs/collection.go, line 514 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56083#-MNOnP980LmszqXZvkZ0:-MNOnP980LmszqXZvkZ1:b-dv0oxy) ([raw file](https://github.com/cockroachdb/cockroach/blob/732e40a4acdba0e468f62e42353b979ac983e6f2/pkg/sql/catalog/descs/collection.go#L514)):*
> ```Go
> 	} else if !found {
> 		if flags.Required {
> 			return nil, sqlerrors.NewUndefinedSchemaError(schemaName)
> ```

should we be qualifying these schema name errors? We have the database name. I think it would make for a better error. Maybe just stick a TODO on this error constructor?

**Review by thoszhang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56083)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/temporary_schema.go, line 218 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/56083#-MNOogNa9z21RCZ3qovf:-MNPDkje1tCiWxo5pD87:bqi4h08) ([raw file](https://github.com/cockroachdb/cockroach/blob/093a90d37039198e58698eef67c7ff5150ba9943/pkg/sql/temporary_schema.go#L218)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

why aren't we using the `descsCol` here? 
</blockquote></details>

No reason other than that it came from the former `getTemporaryObjectNames` implementation. I'd like to just keep this and clean up all the usages of `catalogkv` in this function later (especially since they're all descriptor accesses by ID), if that's fine with you.
___
*[pkg/sql/catalog/descs/collection.go, line 285 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56083#-MNO_4-lEs1G42bHFz-4:-MNP01zy0JwFpEugSxiT:babrrw5) ([raw file](https://github.com/cockroachdb/cockroach/blob/50b2cebc18d1d85f1ce7cceed2b830e52e5d4646/pkg/sql/catalog/descs/collection.go#L285)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I don't think I see the problem here. 
</blockquote></details>

`systemschema.MakeSystemDatabaseDesc()` returns a new copy of a hard-coded `system` database descriptor (such that no user has permissions to drop or alter it). I didn't understand why we even allow mutable resolution for `system`.

I just tried inserting a panic in the mutable case to figure out where we actually attempt to resolve a mutable `system` descriptor. Apparently we do it in, e.g., `ALTER DATABASE system RENAME TO ...`, at which point we read the privileges on the descriptor and return an error. I'm ambivalent about having this special case at the level of the collection where we allow mutable access but assume it will never be necessary. I'll just clarify the comment and leave it.
___
*[pkg/sql/catalog/descs/collection.go, line 1310 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56083#-MNOdMM93BxP20jM9SfF:-MNPJMzjBqd-TGzqYKS4:b-hcikfn) ([raw file](https://github.com/cockroachdb/cockroach/blob/50b2cebc18d1d85f1ce7cceed2b830e52e5d4646/pkg/sql/catalog/descs/collection.go#L1310)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

TODO better lookup structure lest we make N updates in a transaction N^2 operations here. 
</blockquote></details>

I added a TODO on `uncommittedDescriptors`.
___
*[pkg/sql/catalog/descs/collection.go, line 438 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56083#-MNOll_1AHMl_Z42Mbze:-MNP129W0ZoiCCbBmlYx:b-ycifmi) ([raw file](https://github.com/cockroachdb/cockroach/blob/732e40a4acdba0e468f62e42353b979ac983e6f2/pkg/sql/catalog/descs/collection.go#L438)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

On some level I think that that re-resolution is okay. We should make some decision on what you need to provide to resolve a schema: either and ID or a name. Ideally we'll make it cheap enough. 
</blockquote></details>

I think we will want a database name eventually. `planner.LookupSchema` takes a database name and resolves it, and the alter/drop/etc. implementations for schemas also separately resolve the database name.
___
*[pkg/sql/catalog/descs/collection.go, line 514 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56083#-MNOnP980LmszqXZvkZ0:-MNPH7zQBRg9A5hqOAwN:bn2umz1) ([raw file](https://github.com/cockroachdb/cockroach/blob/732e40a4acdba0e468f62e42353b979ac983e6f2/pkg/sql/catalog/descs/collection.go#L514)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

should we be qualifying these schema name errors? We have the database name. I think it would make for a better error. Maybe just stick a TODO on this error constructor?
</blockquote></details>

I added a TODO.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r6, 1 of 3 files at r7, 2 of 6 files at r9, 6 of 6 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56083#-:-MNU21IQ4CZ8SFH9DGRa:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by lucy-zhang** [comment]
TFTR

bors r+

**Comment by lucy-zhang** [comment]
Rebased on top of #57201.

bors r+

**Pull request merged**
