### PR TITLE
clone args.Txn when copying into reply.Txn

### LINKED ISSUE #2537: Data race between TxnCoordSender and Multiraft
There is a data race between txn_coord_sender.go and multiraft.go for errors that contain a Transaction record.  On the txn_coord_sender side, this occurs in `updateState()` whenever the transaction wrapped in the error is modified.  In multiraft, the offending error is a simple log statement:

https://github.com/cockroachdb/cockroach/blob/f470396a766e93f2fa917866951f2aaf14afc119/multiraft/multiraft.go#L912

Apparently both threads have access to the error at the same time.

A full print-off of the detected race from my machine:

```
Read by goroutine 169:
  encoding/base64.(*Encoding).Encode()
      /Users/matt/golang15/src/encoding/base64/base64.go:118 +0x3ed
  encoding/json.encodeByteSlice()
      /Users/matt/golang15/src/encoding/json/encode.go:640 +0x262
  encoding/json.(*structEncoder).encode()
      /Users/matt/golang15/src/encoding/json/encode.go:582 +0x361
  encoding/json.(*structEncoder).(encoding/json.encode)-fm()
      /Users/matt/golang15/src/encoding/json/encode.go:596 +0x5e
  encoding/json.(*structEncoder).encode()
      /Users/matt/golang15/src/encoding/json/encode.go:582 +0x361
  encoding/json.(*structEncoder).(encoding/json.encode)-fm()
      /Users/matt/golang15/src/encoding/json/encode.go:596 +0x5e
  encoding/json.(*ptrEncoder).encode()
      /Users/matt/golang15/src/encoding/json/encode.go:704 +0x119
  encoding/json.(*ptrEncoder).(encoding/json.encode)-fm()
      /Users/matt/golang15/src/encoding/json/encode.go:709 +0x5e
  encoding/json.(*encodeState).reflectValue()
      /Users/matt/golang15/src/encoding/json/encode.go:297 +0x78
  encoding/json.(*encodeState).marshal()
      /Users/matt/golang15/src/encoding/json/encode.go:270 +0xb6
  encoding/json.Marshal()
      /Users/matt/golang15/src/encoding/json/encode.go:135 +0xbe
  github.com/cockroachdb/cockroach/util/log.getJSON()
      /Users/matt/go/src/github.com/cockroachdb/cockroach/util/log/structured.go:53 +0xfb
  github.com/cockroachdb/cockroach/util/log.makeLogArg()
      /Users/matt/go/src/github.com/cockroachdb/cockroach/util/log/structured.go:168 +0x260
  github.com/cockroachdb/cockroach/util/log.parseFormatWithArgs()
      /Users/matt/go/src/github.com/cockroachdb/cockroach/util/log/structured.go:148 +0xdb3
  github.com/cockroachdb/cockroach/util/log.setLogEntry()
      /Users/matt/go/src/github.com/cockroachdb/cockroach/util/log/structured.go:60 +0x8e
  github.com/cockroachdb/cockroach/util/log.AddStructured()
      /Users/matt/go/src/github.com/cockroachdb/cockroach/util/log/structured.go:38 +0x102
  github.com/cockroachdb/cockroach/util/log.logDepth()
      /Users/matt/go/src/github.com/cockroachdb/cockroach/util/log/log.go:65 +0x8c
  github.com/cockroachdb/cockroach/util/log.Warningf()
      /Users/matt/go/src/github.com/cockroachdb/cockroach/util/log/log.go:113 +0x73
  github.com/cockroachdb/cockroach/multiraft.(*state).processCommittedEntry.func1.1()
      /Users/matt/go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:912 +0x91a
  github.com/cockroachdb/cockroach/multiraft.(*state).start.func1()
      /Users/matt/go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:572 +0x2225
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1()
      /Users/matt/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:88 +0x5f

Previous write by goroutine 21:
  runtime.slicecopy()
      /Users/matt/golang15/src/runtime/slice.go:110 +0x0
  github.com/gogo/protobuf/proto.mergeAny()
      /Users/matt/go/src/github.com/gogo/protobuf/proto/clone.go:176 +0x12f9
  github.com/gogo/protobuf/proto.mergeStruct()
      /Users/matt/go/src/github.com/gogo/protobuf/proto/clone.go:84 +0x3a8
  github.com/gogo/protobuf/proto.Clone()
      /Users/matt/go/src/github.com/gogo/protobuf/proto/clone.go:52 +0x23c
  github.com/cockroachdb/cockroach/proto.(*Transaction).Update()
      /Users/matt/go/src/github.com/cockroachdb/cockroach/proto/data.go:477 +0xc2
  github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).updateState()
      /Users/matt/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:655 +0x120
  github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).SendBatch()
      /Users/matt/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:439 +0x1701
  github.com/cockroachdb/cockroach/client.SendCallConverted()
      /Users/matt/go/src/github.com/cockroachdb/cockroach/client/provisional.go:48 +0x3d8
  github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).Send()
      /Users/matt/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:295 +0xae
  github.com/cockroachdb/cockroach/client.(*txnSender).Send()
      /Users/matt/go/src/github.com/cockroachdb/cockroach/client/txn.go:50 +0x14f
  github.com/cockroachdb/cockroach/client.(*DB).send()
      /Users/matt/go/src/github.com/cockroachdb/cockroach/client/db.go:461 +0x426
  github.com/cockroachdb/cockroach/client.(*DB).send()
      /Users/matt/go/src/github.com/cockroachdb/cockroach/client/db.go:478 +0xabb
  github.com/cockroachdb/cockroach/client.(*Txn).send()
      /Users/matt/go/src/github.com/cockroachdb/cockroach/client/txn.go:426 +0x673
  github.com/cockroachdb/cockroach/client.(*Txn).(github.com/cockroachdb/cockroach/client.send)-fm()
      /Users/matt/go/src/github.com/cockroachdb/cockroach/client/txn.go:287 +0x59
  github.com/cockroachdb/cockroach/client.sendAndFill()
      /Users/matt/go/src/github.com/cockroachdb/cockroach/client/db.go:407 +0x79
  github.com/cockroachdb/cockroach/client.(*Txn).Run()
      /Users/matt/go/src/github.com/cockroachdb/cockroach/client/txn.go:287 +0xbd
  github.com/cockroachdb/cockroach/storage.(*Replica).ChangeReplicas.func1()
      /Users/matt/go/src/github.com/cockroachdb/cockroach/storage/replica_command.go:1550 +0x5fe
  github.com/cockroachdb/cockroach/client.(*Txn).exec()
      /Users/matt/go/src/github.com/cockroachdb/cockroach/client/txn.go:359 +0x35c
  github.com/cockroachdb/cockroach/client.(*DB).Txn()
      /Users/matt/go/src/github.com/cockroachdb/cockroach/client/db.go:443 +0x1ff
  github.com/cockroachdb/cockroach/storage.(*Replica).ChangeReplicas()
      /Users/matt/go/src/github.com/cockroachdb/cockroach/storage/replica_command.go:1551 +0x92e
  github.com/cockroachdb/cockroach/storage.replicateQueue.process()
      /Users/matt/go/src/github.com/cockroachdb/cockroach/storage/replicate_queue.go:131 +0x669
  github.com/cockroachdb/cockroach/storage.(*replicateQueue).process()
      <autogenerated>:197 +0xfb
  github.com/cockroachdb/cockroach/storage.(*baseQueue).processOne()
      /Users/matt/go/src/github.com/cockroachdb/cockroach/storage/queue.go:359 +0x89a
  github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1.1()
      /Users/matt/go/src/github.com/cockroachdb/cockroach/storage/queue.go:293 +0x36
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunTask()
      /Users/matt/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:114 +0x237
  github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
      /Users/matt/go/src/github.com/cockroachdb/cockroach/storage/queue.go:294 +0x21a
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1()
      /Users/matt/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:88 +0x5f
```

### PR DESCRIPTION
**Pull request by tbg**
fixes #2537 (or so I think). I think the race stems from an EndTransaction
which doesn't find a record on disk, using a shallow copy of args.Txn as
reply.Txn, which then gets set into a TransactionRetryError which can be
accessed out-of-band while args.Txn is still being used for retries.

### CODE REVIEW

**Comment by tamird** [comment]
Did you mean to reference #2537 in the commit message? LGTM.

**Comment by tschottdorf** [comment]
yep, updated it in the meantime.

**Comment by bdarnell** [comment]
LGTM

**Comment by mrtracy** [comment]
LGTM

**Pull request merged**
