### PR TITLE
backupccl: switch backup processor to worker pool + queue

### PR DESCRIPTION
**Pull request by dt**
Release note: none.

### CODE REVIEW

**Review by miretskiy — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51536)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @pbardea)

___
*[pkg/ccl/backupccl/backup_processor.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51536#-MCSFer_C7b_cGDDCsp6:-MCSFer_C7b_cGDDCsp7:b-c223ks) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1aecaa90ba8c91f94bc85b656ef1d0fc8cb19bd/pkg/ccl/backupccl/backup_processor.go#L106)):*
> ```Go
> 	settings := flowCtx.Cfg.Settings
> 
> 	todo := make(chan spanAndTime, len(spec.Spans)+len(spec.IntroducedSpans))
> ```

why do we need buffering for this channel?
Ahh... I see.  Consumers started below.

Do you think it would make sense to split this function into 
2 parts: backupProducer() and backupConsumer()?

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51536)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @pbardea)

___
*[pkg/ccl/backupccl/backup_processor.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51536#-MCSFer_C7b_cGDDCsp6:-MCSIRd_3v6ieVqP3D5B:b-yurnmd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1aecaa90ba8c91f94bc85b656ef1d0fc8cb19bd/pkg/ccl/backupccl/backup_processor.go#L106)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

why do we need buffering for this channel?
Ahh... I see.  Consumers started below.

Do you think it would make sense to split this function into 
2 parts: backupProducer() and backupConsumer()?


</blockquote></details>

No, don't think so -- we previously were making `[]foo, len=n` whereas now we're making `chan foo, len=n`... which just maps to a `chan foo`  with a len n backing slice again. 

Switching to a smaller or unbuffered chan and adding a goroutine to feed it would just add another goroutine to schedule / context switch,add  more contention on the chan mutex, and, most of all, in the follow-up change we want workers to put work that encounters errors _back on the queue_. With the chan also serving as the work queue this is easy -- just push back on to it --  but it gets much more difficult to avoid deadocks in a small/unbuffered chan: pushing on to it will block until there is space, but if everyone tries to push, no one will pull and make said space. So then we'd need a separate return chan, buffered to at least len workers, and then we'd need to drain it in the producer chan to put items on the back of our queue slice, and keep track of that for iteration.... it's just overall much more complicated for no benefit.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51536)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @pbardea)

___
*[pkg/ccl/backupccl/backup_processor.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51536#-MCSFer_C7b_cGDDCsp6:-MCSoMAq46mxaXJ4MDAu:b-2u05pp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1aecaa90ba8c91f94bc85b656ef1d0fc8cb19bd/pkg/ccl/backupccl/backup_processor.go#L106)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

No, don't think so -- we previously were making `[]foo, len=n` whereas now we're making `chan foo, len=n`... which just maps to a `chan foo`  with a len n backing slice again. 

Switching to a smaller or unbuffered chan and adding a goroutine to feed it would just add another goroutine to schedule / context switch,add  more contention on the chan mutex, and, most of all, in the follow-up change we want workers to put work that encounters errors _back on the queue_. With the chan also serving as the work queue this is easy -- just push back on to it --  but it gets much more difficult to avoid deadocks in a small/unbuffered chan: pushing on to it will block until there is space, but if everyone tries to push, no one will pull and make said space. So then we'd need a separate return chan, buffered to at least len workers, and then we'd need to drain it in the producer chan to put items on the back of our queue slice, and keep track of that for iteration.... it's just overall much more complicated for no benefit.
</blockquote></details>

I'm not sure I buy that.  Adding one more worker does not make it more expensive -- you already start numSender of them.

In addition, buffered channel does not save you from deadlock just makes them less likely.
Pushing more work from the consumers back onto the channel, buffered or unbuffered could
still result in deadlocks, and is not safe.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51536)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @pbardea)

___
*[pkg/ccl/backupccl/backup_processor.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51536#-MCSFer_C7b_cGDDCsp6:-MCSw-ob2bQHGxup2YpE:b-wj6lp0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1aecaa90ba8c91f94bc85b656ef1d0fc8cb19bd/pkg/ccl/backupccl/backup_processor.go#L106)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I'm not sure I buy that.  Adding one more worker does not make it more expensive -- you already start numSender of them.

In addition, buffered channel does not save you from deadlock just makes them less likely.
Pushing more work from the consumers back onto the channel, buffered or unbuffered could
still result in deadlocks, and is not safe.


</blockquote></details>

I don't think that's correct: as long as we're only pushing the one request we dequeued back on to the channel, it is guaranteed to have capacity to receive it -- it started with enough capacity to hold all items, and the only way an additional item will have been put on it is by a worker which had to take one off first.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51536)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @pbardea)

___
*[pkg/ccl/backupccl/backup_processor.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51536#-MCSFer_C7b_cGDDCsp6:-MCSz5Ma3B2cbTYzVYSv:buof5lw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1aecaa90ba8c91f94bc85b656ef1d0fc8cb19bd/pkg/ccl/backupccl/backup_processor.go#L106)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I don't think that's correct: as long as we're only pushing the one request we dequeued back on to the channel, it is guaranteed to have capacity to receive it -- it started with enough capacity to hold all items, and the only way an additional item will have been put on it is by a worker which had to take one off first.
</blockquote></details>

Ahh... right. I assumed that you can push more than 1 unit of work.  Would that be something we require and depend on?  If workers can push >1 unit of work -- deadlock could happen.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51536)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @pbardea)

___
*[pkg/ccl/backupccl/backup_processor.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51536#-MCSFer_C7b_cGDDCsp6:-MCT-mFF7kNRPJTN1OAW:baoflak) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1aecaa90ba8c91f94bc85b656ef1d0fc8cb19bd/pkg/ccl/backupccl/backup_processor.go#L106)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Ahh... right. I assumed that you can push more than 1 unit of work.  Would that be something we require and depend on?  If workers can push >1 unit of work -- deadlock could happen.
</blockquote></details>

I don't anticipate pushing anything other than the original work back on to the chan. If/when that changes, we can bite the bullet of an extra return chan and a feeder goroutine that drains it and feeds the work chan, but for now this is much simpler.

See also some discussion form last week: https://cockroachlabs.slack.com/archives/C4X2J0RH6/p1594309679188900?thread_ts=1594309229.186800&cid=C4X2J0RH6

**Review by miretskiy — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51536#-:-MCT1qQ12r7WHY4P_aTl:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @pbardea)

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51536)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @pbardea)

___
*[pkg/ccl/backupccl/backup_processor.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51536#-MCSFer_C7b_cGDDCsp6:-MCT2iK58047LOuwPCdp:b4wx1fi) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1aecaa90ba8c91f94bc85b656ef1d0fc8cb19bd/pkg/ccl/backupccl/backup_processor.go#L106)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I don't anticipate pushing anything other than the original work back on to the chan. If/when that changes, we can bite the bullet of an extra return chan and a feeder goroutine that drains it and feeds the work chan, but for now this is much simpler.

See also some discussion form last week: https://cockroachlabs.slack.com/archives/C4X2J0RH6/p1594309679188900?thread_ts=1594309229.186800&cid=C4X2J0RH6
</blockquote></details>

Actually, 1 more question... What guarantees we have that if you have a worker that, after timeout, decides to put back unit of work onto the channel, that that work would go to the "back" of the queue?  Are you concerned that go runtime may just decide that instead of blocking this go routine, it will immediately pop that work item from the channel queue because this go routine is runnable, and has more work?

Wouldn't we be safer if we did have extra chan feeding work?

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51536)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @pbardea)

___
*[pkg/ccl/backupccl/backup_processor.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51536#-MCSFer_C7b_cGDDCsp6:-MCT3cHm-EEOwkh2W2J7:b-ovf3jx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1aecaa90ba8c91f94bc85b656ef1d0fc8cb19bd/pkg/ccl/backupccl/backup_processor.go#L106)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Actually, 1 more question... What guarantees we have that if you have a worker that, after timeout, decides to put back unit of work onto the channel, that that work would go to the "back" of the queue?  Are you concerned that go runtime may just decide that instead of blocking this go routine, it will immediately pop that work item from the channel queue because this go routine is runnable, and has more work?

Wouldn't we be safer if we did have extra chan feeding work?  
</blockquote></details>

Huh? It'd push, which would acquire the chan mutex and append to the backing slice, then release the mutex. then the worker, which is runnable, loops around to the top of the loop and reads from chan, which acquires the mutex and reads from the front of the slice. I'm not sure what you're worried about.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51536)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @pbardea)

___
*[pkg/ccl/backupccl/backup_processor.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51536#-MCSFer_C7b_cGDDCsp6:-MCU58Xk-rTXWJlVv_w6:bro4snw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1aecaa90ba8c91f94bc85b656ef1d0fc8cb19bd/pkg/ccl/backupccl/backup_processor.go#L106)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Huh? It'd push, which would acquire the chan mutex and append to the backing slice, then release the mutex. then the worker, which is runnable, loops around to the top of the loop and reads from chan, which acquires the mutex and reads from the front of the slice. I'm not sure what you're worried about.
</blockquote></details>

Nah... It's alright...

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51536)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt and @pbardea)

___
*[pkg/ccl/backupccl/backup_processor.go, line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51536#-MCgPxVJ77nBhR4DxYow:-MCgPxVJ77nBhR4DxYox:b-nvpj2h) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1aecaa90ba8c91f94bc85b656ef1d0fc8cb19bd/pkg/ccl/backupccl/backup_processor.go#L137)):*
> ```Go
> 		for {
> 			select {
> 			case <-done:
> ```

Now that we've moved the `done` check to the start of the worker loop, will the worker be able to stop working in the case of a backup cancellation/failure?

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51536)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @pbardea)

___
*[pkg/ccl/backupccl/backup_processor.go, line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51536#-MCgPxVJ77nBhR4DxYow:-MCg_tQZD5QHMsSe0iK8:b2xn1ix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1aecaa90ba8c91f94bc85b656ef1d0fc8cb19bd/pkg/ccl/backupccl/backup_processor.go#L137)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Now that we've moved the `done` check to the start of the worker loop, will the worker be able to stop working in the case of a backup cancellation/failure?
</blockquote></details>

it still checks before each de-queue of a work item, so in that respect it is the same as the old old code. The work itself is sending an export request and waiting for a reply -- and since we pass the same ctx to distsender, it'd bail when it cancels. I believe the behavior w.r.t. cancel is the same as before?

**Review by pbardea — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51536)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/ccl/backupccl/backup_processor.go, line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51536#-MCgPxVJ77nBhR4DxYow:-MCgdJwHBBH2-Im8zFjZ:b-nhghaz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1aecaa90ba8c91f94bc85b656ef1d0fc8cb19bd/pkg/ccl/backupccl/backup_processor.go#L137)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

it still checks before each de-queue of a work item, so in that respect it is the same as the old old code. The work itself is sending an export request and waiting for a reply -- and since we pass the same ctx to distsender, it'd bail when it cancels. I believe the behavior w.r.t. cancel is the same as before?
</blockquote></details>

Ah, right. Got confused with the old nested block.

**Comment by dt** [comment]
TFTRs!

bors r+

**Pull request merged**
