### PR TITLE
opt: Support HAVING and DISTINCT in the builder

### PR DESCRIPTION
**Pull request by rytaft**
This commit is one of several needed to build a "memo"
structure from a parsed SQL query. The memo is the primary data
structure in the query optimizer, used for maintaining the forest of
query plan trees that the optimizer considers as part of its search
for the optimal plan.

This commit includes support for building a memo for queries
which include `HAVING` and `SELECT DISTINCT`. The test cases have been
adapted from the aggregate and distinct tests in logictests.

This commit also cleans up the test code in opt/builder so that
it no longer requires starting up a test cluster. Instead, it
creates a TestCatalog with the required tables.

Future commits will add support for other features in aggregates
such as `FITLER`, well as other types of queries including `VALUES`,
`UNION` and complex joins.

This code is based on code originally written by @petermattis and
@andy-kimball in the opttoy project.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
The current planning code converts HAVING to a projection on top of a filter. Do you envision doing something similar with a normalization rule?

---

Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/opt/build/testdata/aggregate, line 8 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22473#-L4mUd5JirGyZ_EruVPg:-L4mUd5JirGyZ_EruVPh:b-hxlz1u) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e1bf7fcaf7f20fa49f19349d312f8ccfef40d0f/pkg/sql/opt/build/testdata/aggregate#L8)):*
> ```
> 
> exec-raw
> CREATE TABLE t.kv (
> ```

This makes the test files harder to read.. You could just find the table definition in the same file, now you have to know where to look.. And you need to modify the source code if you need a different table. I'm not sure not spawning a server is worth it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22473#-:-L4mVoWae1Ea7VEtf6ES:b24ky65)*

**Comment by rytaft** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/opt/build/testdata/aggregate, line 8 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22473#-L4mUd5JirGyZ_EruVPg:-L4mWlV_y03F6ZsNuxDN:b-gdbgpi) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e1bf7fcaf7f20fa49f19349d312f8ccfef40d0f/pkg/sql/opt/build/testdata/aggregate#L8)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This makes the test files harder to read.. You could just find the table definition in the same file, now you have to know where to look.. And you need to modify the source code if you need a different table. I'm not sure not spawning a server is worth it.
</blockquote></details>

What if I just add a comment with the table definitions?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22473)*

**Comment by RaduBerinde** [comment]
Never mind - that's exactly what your code is doing. I misread the test output and thought we were putting the having expression as a child of the groupOp.

---

Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22473#-:-L4mY07OfA6ko1lodroK:boj2jav)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/opt/build/testdata/aggregate, line 8 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22473#-L4mUd5JirGyZ_EruVPg:-L4mYPFE0Tr3x4y48lfM:b-imm8sz) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e1bf7fcaf7f20fa49f19349d312f8ccfef40d0f/pkg/sql/opt/build/testdata/aggregate#L8)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

What if I just add a comment with the table definitions?
</blockquote></details>

I imagine they would rot easily.. And it's still non-intuitive what you need to do to add a new one.

I wonder if we could we have a special `exec-ddl` directive that parses a create table statement and creates a test table from the info in `tree.CreateTable`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22473)*

**Comment by rytaft** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/opt/build/testdata/aggregate, line 8 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22473#-L4mUd5JirGyZ_EruVPg:-L4maHlo_Mg8hr0QKKPv:bvl89) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e1bf7fcaf7f20fa49f19349d312f8ccfef40d0f/pkg/sql/opt/build/testdata/aggregate#L8)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I imagine they would rot easily.. And it's still non-intuitive what you need to do to add a new one.

I wonder if we could we have a special `exec-ddl` directive that parses a create table statement and creates a test table from the info in `tree.CreateTable`
</blockquote></details>

Yea, that's basically what create_table.go was doing in the opttoy code. Maybe that's the best solution.  I'll give that a try...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22473)*

**Comment by andy-kimball** [comment]
Review status: 0 of 11 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/build/testdata/aggregate, line 8 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22473#-L4mUd5JirGyZ_EruVPg:-L4m_qe8QhbEqcrr8URc:bxrnjk2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e1bf7fcaf7f20fa49f19349d312f8ccfef40d0f/pkg/sql/opt/build/testdata/aggregate#L8)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Yea, that's basically what create_table.go was doing in the opttoy code. Maybe that's the best solution.  I'll give that a try...
</blockquote></details>

Looking at the schema we use for this test, it is pretty involved compared to the one I was using for my other tests. There does seem to be a crossover point where interleaving DDL in the tests makes sense. However, if we did have a create_table testing helper, that'd hopefully be the best of both worlds.

---

*[pkg/sql/opt/build/testdata/distinct, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22473#-L4mbtwZPDAJSBF9Vhpz:-L4mbtwZPDAJSBF9Vhq-:b-nitfpn) ([raw file](https://github.com/cockroachdb/cockroach/blob/5067c318689c2fa00eecedf12970d0746fed79c3/pkg/sql/opt/build/testdata/distinct#L1)):*
> ```
> # tests adapted from logictest -- aggregate and distinct
> ```

I think it'd be interesting to test cases where the columns are not variables. What about constants, computed expressions, etc? What about cases where distinct is used in combination with groupby/having? Like `SELECT DISTINCT MAX(x) FROM a GROUP BY x`.

---

*[pkg/sql/opt/build/testdata/having, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22473#-L4mclFw_2bdLBzF7FdP:-L4mclFw_2bdLBzF7FdQ:b-i0comp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5067c318689c2fa00eecedf12970d0746fed79c3/pkg/sql/opt/build/testdata/having#L1)):*
> ```
> # tests adapted from logictest -- aggregate
> ```

What's the impact of mixing differently qualified names together? Like `SELECT MAX(a.x) FROM a GROUP BY x HAVING a.x > 5`. I'd make sure our syntactic equivalence is doing the right thing when it comes to cases like this (add agg tests as well).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22473)*

**Comment by petermattis** [comment]
Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/build/testdata/having, line 14 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22473#-L4n0nOzr3f2-rHmOxij:-L4n0nOzr3f2-rHmOxik:br3wcxt) ([raw file](https://github.com/cockroachdb/cockroach/blob/5067c318689c2fa00eecedf12970d0746fed79c3/pkg/sql/opt/build/testdata/having#L14)):*
> ```
>  │    │    │    └── columns: kv.k:int:1 kv.v:int:null:2 kv.w:int:null:3 kv.s:string:null:4
>  │    │    ├── projections [type=tuple{}]
>  │    │    └── projections [type=tuple{}]
> ```

Can we name these lists `groupings` and `aggregations`? It is mildly confusing to see two empty `projections`. This might be a question for @andy-kimball.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22473)*

**Comment by andy-kimball** [comment]
Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/build/testdata/having, line 14 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22473#-L4n0nOzr3f2-rHmOxij:-L4nULdNIsVWLFQ2tqlz:b6gthcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/5067c318689c2fa00eecedf12970d0746fed79c3/pkg/sql/opt/build/testdata/having#L14)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Can we name these lists `groupings` and `aggregations`? It is mildly confusing to see two empty `projections`. This might be a question for @andy-kimball.
</blockquote></details>

Yeah, I was actually thinking that as well. Right now we print the operator type of the node rather than the name of the parent field. But for the Projections op, I think we should use the name of the parent field and also omit the type, which is always a tuple of the projected column types (which we already show).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22473)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/build/testdata/having, line 14 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22473#-L4n0nOzr3f2-rHmOxij:-L4ncYBoH8LrkFa7xJTD:b-2bansp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5067c318689c2fa00eecedf12970d0746fed79c3/pkg/sql/opt/build/testdata/having#L14)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Yeah, I was actually thinking that as well. Right now we print the operator type of the node rather than the name of the parent field. But for the Projections op, I think we should use the name of the parent field and also omit the type, which is always a tuple of the projected column types (which we already show).
</blockquote></details>

How would you do this? Special case the group-by, or do it always for any ProjectionOp? In the latter case, how do we get the name of the parent field?

Maybe we should prepend the field name in all cases?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22473)*

**Comment by andy-kimball** [comment]
Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/build/testdata/having, line 14 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22473#-L4n0nOzr3f2-rHmOxij:-L4pRuRtj7saukeXRD8x:bbsf4mg) ([raw file](https://github.com/cockroachdb/cockroach/blob/5067c318689c2fa00eecedf12970d0746fed79c3/pkg/sql/opt/build/testdata/having#L14)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

How would you do this? Special case the group-by, or do it always for any ProjectionOp? In the latter case, how do we get the name of the parent field?

Maybe we should prepend the field name in all cases?
</blockquote></details>

One idea is to just add new more specialized operators rather than reusing `Projections`. Like we could just create `Aggregations` and `Groupings`. I can't see much advantage to making them all the same operator.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22473)*

**Comment by rytaft** [comment]
Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/build/testdata/having, line 14 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22473#-L4n0nOzr3f2-rHmOxij:-L4pml2HHZ7zQmlMo685:bh49qt6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5067c318689c2fa00eecedf12970d0746fed79c3/pkg/sql/opt/build/testdata/having#L14)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

One idea is to just add new more specialized operators rather than reusing `Projections`. Like we could just create `Aggregations` and `Groupings`. I can't see much advantage to making them all the same operator.
</blockquote></details>

New operators sounds like the cleanest solution. Will you make that change, Andy, or should I?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22473)*

**Comment by andy-kimball** [comment]
Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/build/testdata/having, line 14 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22473#-L4n0nOzr3f2-rHmOxij:-L4q5EusWsnT7IxAyrE1:b-qtrgn8) ([raw file](https://github.com/cockroachdb/cockroach/blob/5067c318689c2fa00eecedf12970d0746fed79c3/pkg/sql/opt/build/testdata/having#L14)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

New operators sounds like the cleanest solution. Will you make that change, Andy, or should I?
</blockquote></details>

I can make it today.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22473)*

**Comment by rytaft** [comment]
Review status: 0 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/build/testdata/aggregate, line 8 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22473#-L4mUd5JirGyZ_EruVPg:-L4qAtWtGzFJE9Wo-rKT:bedgs57) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e1bf7fcaf7f20fa49f19349d312f8ccfef40d0f/pkg/sql/opt/build/testdata/aggregate#L8)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Looking at the schema we use for this test, it is pretty involved compared to the one I was using for my other tests. There does seem to be a crossover point where interleaving DDL in the tests makes sense. However, if we did have a create_table testing helper, that'd hopefully be the best of both worlds.
</blockquote></details>

Added the new `exec-ddl` directive and `create_table` testing helper.

---

*[pkg/sql/opt/build/testdata/having, line 14 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22473#-L4n0nOzr3f2-rHmOxij:-L4qCkhu-KogH8F0GLDC:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/5067c318689c2fa00eecedf12970d0746fed79c3/pkg/sql/opt/build/testdata/having#L14)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I can make it today.
</blockquote></details>

Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22473)*

**Comment by rytaft** [comment]
Thanks for the reviews!  I think I've addressed all the feedback now. Please take another look.

---

Review status: 0 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/build/testdata/distinct, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22473#-L4mbtwZPDAJSBF9Vhpz:-L4qT0cIYdQJsH_HGyYq:b51dhys) ([raw file](https://github.com/cockroachdb/cockroach/blob/5067c318689c2fa00eecedf12970d0746fed79c3/pkg/sql/opt/build/testdata/distinct#L1)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I think it'd be interesting to test cases where the columns are not variables. What about constants, computed expressions, etc? What about cases where distinct is used in combination with groupby/having? Like `SELECT DISTINCT MAX(x) FROM a GROUP BY x`.
</blockquote></details>

Added some tests.

---

*[pkg/sql/opt/build/testdata/having, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22473#-L4mclFw_2bdLBzF7FdP:-L4qSyDjlM9vNZq9rI7p:b51dhys) ([raw file](https://github.com/cockroachdb/cockroach/blob/5067c318689c2fa00eecedf12970d0746fed79c3/pkg/sql/opt/build/testdata/having#L1)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

What's the impact of mixing differently qualified names together? Like `SELECT MAX(a.x) FROM a GROUP BY x HAVING a.x > 5`. I'd make sure our syntactic equivalence is doing the right thing when it comes to cases like this (add agg tests as well).
</blockquote></details>

Added some tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22473#-:-L4qT2op-1Tukq9e2Z4E:biwi40n)*

**Comment by RaduBerinde** [comment]
Very nice! :lgtm_strong: 

---

Review status: 0 of 12 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22473#-:-L4qTgK1-u-8rkvDjLKd:b-il1ii9)*

**Comment by andy-kimball** [comment]
I like the create table solution a lot. I'll have to switch my tests to use it. :lgtm:

---

Review status: 0 of 12 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22473#-:-L4qc1YPMRPUDieh94M4:bao923s)*

**Comment by rytaft** [comment]
TFTRs!

---

Review status: 0 of 12 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22473#-:-L4qdWCCmmyzc15ylpbW:bz5mair)*

**Pull request merged**
