### PR TITLE
lint: fix lint warnings

### PR DESCRIPTION
**Pull request by maryliag**
We have a lot of lint warnings that make hard
to easily look for errors or even new introduce
warnings.
This commit fixes the majority of these warnings.

Release justification: non-production change
Release note: None

### CODE REVIEW

**Comment by laurenbarker** [comment]
Exciting! I haven't looked at everything in the PR, but if you get rid of all of one type of warning, I'd recommend removing the override that makes it a warning and not an error from the eslint config. If the rule causes and error, no one will introduce more warnings on accident :)

https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/cluster-ui/.eslintrc.json#L13

**Review by sjbarag — APPROVED** [review]
+1 to what @laurenbarker said w.r.t. removing the warning override but the diff looks great!  I think I just heard a sigh of relief from everyone who works with this code 🤔

**Comment by maryliag** [comment]
The majority of the ones I fixed are `@typescript-eslint/explicit-module-boundary-types`, which is not on that list. 
I did fixed quite a few of `@typescript-eslint/no-unused-vars`, but I don't think we can remove that, there are some weird cases on fixtures that consider not used that we can't really remove because is the parameter on the original function that was not being used on that test.

**Pull request merged**
