### PR TITLE
cherrypick-1.1: sql: support casting strings to arrays

### PR DESCRIPTION
**Pull request by justinj**
Cherry-pick of #18588, needed for navicat support.

### CODE REVIEW

**Comment by bdarnell** [comment]
Is this sufficient to get navicat working? #5583 says it still depends on correlated subqueries. I'd be happy to get this in if it meant that navicat could work, but otherwise I'm wary of cherry-picking this. 

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18855#-:-Kv7wtkJ3NTGbfJ4_Sxm:b-xhzwmq)*

**Comment by justinj** [comment]
cc @jordanlewis for that question

**Comment by jordanlewis** [comment]
Ben's right - this wouldn't get us navicat support by itself.

**Comment by justinj** [comment]
Ok, I'll close this then, agreed not worth a cherry-pick in that case.

**Pull request closed without merging**
