### PR TITLE
storage: don't open the breaker on deadline exceeded errors

### PR DESCRIPTION
**Pull request by petermattis**
Don't open the circuit breaker to a node if a snapshot encounters a
deadline exceeded error.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13816)

### CODE REVIEW

**Comment by tamird** [comment]
LGTM but is this feasible to test?

**Comment by petermattis** [comment]
Of course it is possible, though see https://github.com/cockroachdb/cockroach/issues/9593.

**Comment by tamird** [comment]
Oy.

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/raft_transport.go, line 601 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13816#-Ke-fV_617vvvaOCrhBN:-Ke-fV_617vvvaOCrhBO:bn8nfl2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9d390ea6eab85f53a099c5c347220ee78a7ec08/pkg/storage/raft_transport.go#L601)):*
> ```Go
> type snapshotClientWithBreaker struct {
> 	MultiRaft_RaftSnapshotClient
> 	breaker *circuit.Breaker
> ```

Maybe we should just get rid of snapshotClientWithBreaker and ignore all snapshot errors for the purposes of the breaker. Snapshots are much less common than regular messages so if there's a real problem we'll probably notice it with the regular message soon (and conversely, any error that happens on a snapshot and not a regular message is probably because snapshots are "weird" and we don't want them to block regular messages anyway).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13816#-:-Ke-g0vNKfbxXCA8blO3:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/storage/raft_transport.go, line 601 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13816#-Ke-fV_617vvvaOCrhBN:-Ke-iQMNQtfhQLxwuxwM:b-m5e7h6) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9d390ea6eab85f53a099c5c347220ee78a7ec08/pkg/storage/raft_transport.go#L601)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Maybe we should just get rid of snapshotClientWithBreaker and ignore all snapshot errors for the purposes of the breaker. Snapshots are much less common than regular messages so if there's a real problem we'll probably notice it with the regular message soon (and conversely, any error that happens on a snapshot and not a regular message is probably because snapshots are "weird" and we don't want them to block regular messages anyway).
</blockquote></details>

That's a good point. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13816)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13816#-:-Ke-iow3EWajEVePQFP-:bnfp4nl)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/storage/raft_transport.go, line 633 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13816#-Ke-isHYSVVGSfngHXV-:-Ke-isHYSVVGSfngHXV0:b-mfo3om) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ed459f7163a95e5057da51867da071d1fbec753/pkg/storage/raft_transport.go#L633)):*
> ```Go
> 	// want to disrupt normal messages.
> 	defer func() {
> 		if err := stream.CloseSend(); err != nil && grpc.Code(err) != codes.DeadlineExceeded {
> ```

You've removed the `breaker.Fail` call; why bother with this grpc code check?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13816)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/raft_transport.go, line 633 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13816#-Ke-isHYSVVGSfngHXV-:-Ke-tKTEEtrpzw9bfgt8:b-341g9i) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ed459f7163a95e5057da51867da071d1fbec753/pkg/storage/raft_transport.go#L633)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

You've removed the `breaker.Fail` call; why bother with this grpc code check?
</blockquote></details>

To not log the warning here. We'll be logging at a higher level anyways if the snapshot failed to apply. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13816)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/raft_transport.go, line 633 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13816#-Ke-isHYSVVGSfngHXV-:-Ke-ulDdBY0WncYw7H2y:b-ivvrz3) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ed459f7163a95e5057da51867da071d1fbec753/pkg/storage/raft_transport.go#L633)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

To not log the warning here. We'll be logging at a higher level anyways if the snapshot failed to apply. 
</blockquote></details>

This is an odd detail to look for, here. It's also the case that returning an error from `CloseSend` is very unlikely. I'd rather we over-log in this case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13816)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/storage/raft_transport.go, line 633 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13816#-Ke-isHYSVVGSfngHXV-:-Ke-vH8GTd2wkMtxYoUI:b-mye756) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ed459f7163a95e5057da51867da071d1fbec753/pkg/storage/raft_transport.go#L633)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

This is an odd detail to look for, here. It's also the case that returning an error from `CloseSend` is very unlikely. I'd rather we over-log in this case.
</blockquote></details>

It really doesn't matter. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13816)*

**Comment by tamird** [comment]
Right, it's just FUD.

**Pull request merged**
