### PR TITLE
cli: learn to dump a store's SSTs in JSON

### PR DESCRIPTION
**Pull request by benesch**
Add a '--json' flag to the 'debug sstables' command. The JSON output can
be significantly more verbose than the standard summary that's printed,
as it's not meant for direct human consumption.

Release note: None

### CODE REVIEW

**Comment by benesch** [comment]
Eh, ignore this PR for now. I have something better in mind.

**Comment by petermattis** [comment]
> Eh, ignore this PR for now. I have something better in mind.

Curious what your thinking is here. The `clearrange` saga has me interested in better visualizing the sstables and the inputs and outputs of every compaction. 

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26577#-:-LEj2XtI1Ci-icFZ4aLe:b-qi8mx)*

**Comment by benesch** [comment]
Yeah, exactly. I’m working on an events log that I hope to plug into a D3
viz.

**Comment by benesch** [comment]
Here's a sample of what I put together last night: https://gist.github.com/benesch/87f6e7f112fcc3c0c151be5312b71b1b

I think with another day of work it could be fantastically useful. Hopefully I'll have some time this Friday.

**Comment by benesch** [comment]
Not gonna happen any time soon.

**Pull request closed without merging**
