### PR TITLE
opt: Simplify and optimize orderings

### PR DESCRIPTION
**Pull request by andy-kimball**
This PR contains five separate commits that all work towards the goal
of simplifying and optimizing orderings (i.e. ORDER BY clauses):

1. Replace opt.Ordering with props.OrderingChoice.
2. Remove redundant ordering columns.
3. Add constant columns to functional dependencies.
4. Simplify orderings in additional cases (constrained scan, project).
5. Prune unneeded EXPLAIN input columns after optimizing ordering.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
This is fantastic! :lgtm_strong: 

---

Review status: :shipit: complete! 1 of 0 LGTMs obtained

---

*[pkg/sql/opt/exec/execbuilder/testdata/orderby, line 581 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26975#-LFweFmdBeKPhCtNvldm:-LFweFmdBeKPhCtNvldn:b-kctvf1) ([raw file](https://github.com/cockroachdb/cockroach/blob/fff745c36a3ff69f089aa3dcecf82fbac7946a2e/pkg/sql/opt/exec/execbuilder/testdata/orderby#L581)):*
> ```
>  │         render 2  block_num       ·                                           ·
>  │         render 3  block_id        ·                                           ·
>  └── scan  ·         ·               (block_id, writer_id, block_num)            ·
> ```

In principle distsql should be allowed to plan multiple tablereaders each with limit 1 and get the first result (and it relies on this ordering to know what "first" means). I think we are fine right now, but please add a comment [here](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/distsql_physical_planner.go#L984), something like "Note that if we have a hard limit of 1, the scanNode won't necessarily have an ordering; if we ever plan multiple tablereaders in this case, we must make sure to set the merge ordering below to the natural order of the index we are scanning.

---

*[pkg/sql/opt/memo/private_defs.go, line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26975#-LFw_Psh7N3LW06H61cz:-LFw_PsiBlXGWbuTqJWW:bnusapr) ([raw file](https://github.com/cockroachdb/cockroach/blob/128530a1e1440f34df2ef77b8368186e2656d9c0/pkg/sql/opt/memo/private_defs.go#L126)):*
> ```Go
> 			return false
> 		}
> 		j++
> ```

`j` doesn't do anything.

Oh, this goes away in a subsequent commit so it doesn't matter.

---

*[pkg/sql/opt/memo/private_storage.go, line 152 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26975#-LFwaQgu8Rcanxuxyx2r:-LFwaQgu8Rcanxuxyx2s:b-q7dj8z) ([raw file](https://github.com/cockroachdb/cockroach/blob/128530a1e1440f34df2ef77b8368186e2656d9c0/pkg/sql/opt/memo/private_storage.go#L152)):*
> ```Go
> // internOrderingChoice adds the given value to storage and returns an id that
> // can later be used to retrieve the value by calling the lookup method. If the
> // value has been previously added to storage, then internOrdering always
> ```

[nit] internOrderingChoice

---

*[pkg/sql/opt/memo/private_storage.go, line 477 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26975#-LFwamfO0C4ZjZDZJZV0:-LFwamfO0C4ZjZDZJZV1:b-krvrdt) ([raw file](https://github.com/cockroachdb/cockroach/blob/128530a1e1440f34df2ef77b8368186e2656d9c0/pkg/sql/opt/memo/private_storage.go#L477)):*
> ```Go
> 		}
> 
> 		// Always add a separate between groups (column IDs cannot be 0).
> ```

[nit] separator

---

*[pkg/sql/opt/xform/physical_props.go, line 23 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26975#-LFwlw1cAhUSaYgvILID:-LFwlw1cAhUSaYgvILIE:b-4devxa) ([raw file](https://github.com/cockroachdb/cockroach/blob/b01b216698779aab49777d87eece86272c868f3a/pkg/sql/opt/xform/physical_props.go#L23)):*
> ```Go
> )
> 
> // canProvide returns true if the given expression can provide the required
> ```

[nit] canProvidePhysicalProps

---

*[pkg/sql/opt/xform/physical_props.go, line 31 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26975#-LFwm6_gCP8zK72FcKmT:-LFwm6_gCP8zK72FcKmU:b-ja1hnf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b01b216698779aab49777d87eece86272c868f3a/pkg/sql/opt/xform/physical_props.go#L31)):*
> ```Go
> // physical property, but do "pass through" the requirement to their input.
> // Operators that do this should return true from the appropriate canProvide
> // method and then pass through that property in the buildChildProps method.
> ```

[nit] buildChildPhysicalProps

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26975#-:-LFwml974ozMfcWDHvfP:bbhqh8v)*

**Comment by rytaft** [comment]
:lgtm_strong: 

---

Reviewed 32 of 32 files at r1, 16 of 16 files at r2, 37 of 37 files at r3, 15 of 15 files at r4, 4 of 4 files at r5.
Review status: :shipit: complete! 2 of 0 LGTMs obtained

---

*[pkg/sql/opt/memo/logical_props_builder.go, line 1082 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26975#-LFy7SwF2ExreQRWikot:-LFy7SwF2ExreQRWikou:b-d8i9du) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa8576969f63d9147fb99bb5dee244072de9867a/pkg/sql/opt/memo/logical_props_builder.go#L1082)):*
> ```Go
> }
> 
> func (b *logicalPropsBuilder) applyConstantConstraint(
> ```

All of these changes are redundant with #26937 - just FYI for whoever merges second and needs to rebase

---

*[pkg/sql/opt/norm/ordering.go, line 117 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26975#-LFy35Fd3bQV2dP9usGI:-LFy35Fd3bQV2dP9usGJ:bdb629m) ([raw file](https://github.com/cockroachdb/cockroach/blob/fff745c36a3ff69f089aa3dcecf82fbac7946a2e/pkg/sql/opt/norm/ordering.go#L117)):*
> ```Go
> 	if len(simplified.Columns) == 0 {
> 		// Discard any optional columns as well if there are no required columns.
> 		simplified = props.OrderingChoice{}
> ```

Doesn't `Simplify` already do this?

---

*[pkg/sql/opt/norm/rules/ordering.opt, line 36 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26975#-LFy3xYj7qvEXRrAZN6_:-LFy3xYj7qvEXRrAZN6a:b-tvdnwp) ([raw file](https://github.com/cockroachdb/cockroach/blob/fff745c36a3ff69f089aa3dcecf82fbac7946a2e/pkg/sql/opt/norm/rules/ordering.opt#L36)):*
> ```
>     $input:*
>     $offset:*
>     $ordering:* & (CanSimplifyLimitOrdering $input $ordering)
> ```

Since you're reusing this function for Offset, maybe call it `CanSimplifyLimitOffsetOrdering` or `CanSimplifyOrderingPrivate` or something like that....

---

*[pkg/sql/opt/ops/relational.opt, line 296 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26975#-LFwVKmJAxcT0ZPM4isy:-LFwVKmJAxcT0ZPM4isz:b6aan7j) ([raw file](https://github.com/cockroachdb/cockroach/blob/128530a1e1440f34df2ef77b8368186e2656d9c0/pkg/sql/opt/ops/relational.opt#L296)):*
> ```
> # Limit returns a limited subset of the results in the input relation.
> # The limit expression is a scalar value; the operator returns at most this many
> # rows. The private field is an props.OrderingChoice which indicates the row
> ```

[nit] an -> a

---

*[pkg/sql/opt/optbuilder/testdata/ordinality, line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26975#-LFwWGWX3ZqrU1YEizM3:-LFwWGWX3ZqrU1YEizM4:bhacyhi) ([raw file](https://github.com/cockroachdb/cockroach/blob/f46948f255ed234a2710b37f3b8983e1bda8f6ed/pkg/sql/opt/optbuilder/testdata/ordinality#L69)):*
> ```
> 
> build
> SELECT a, ordinality FROM (SELECT * FROM abcd ORDER BY a) WITH ORDINALITY ORDER BY ordinality
> ```

Why did you get rid of this test case?

---

*[pkg/sql/opt/props/ordering_choice.go, line 216 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26975#-LFwXV57CGpllmiglF1p:-LFwXV57CGpllmiglF1q:b-sv04le) ([raw file](https://github.com/cockroachdb/cockroach/blob/128530a1e1440f34df2ef77b8368186e2656d9c0/pkg/sql/opt/props/ordering_choice.go#L216)):*
> ```Go
> // as the input set? Here are some examples:
> //
> //   <empty            matches <empty>
> ```

[nit] missing >

---

*[pkg/sql/opt/props/ordering_choice.go, line 343 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26975#-LFxzLD5Bf8mhvqoB7Tt:-LFxzLD5Bf8mhvqoB7Tu:bhzap3c) ([raw file](https://github.com/cockroachdb/cockroach/blob/128530a1e1440f34df2ef77b8368186e2656d9c0/pkg/sql/opt/props/ordering_choice.go#L343)):*
> ```Go
> 
> 	closure := optional
> 	for i := range oc.Columns {
> ```

The logic in this loop is a bit confusing - a comment would help

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26975#-:-LFyF1fk-59DNDqaNpS5:b-uwkowd)*

**Comment by andy-kimball** [comment]
Review status: :shipit: complete! 2 of 0 LGTMs obtained

---

*[pkg/sql/opt/exec/execbuilder/testdata/orderby, line 581 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26975#-LFweFmdBeKPhCtNvldm:-LFy6_BY10rcPeMgLmFb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fff745c36a3ff69f089aa3dcecf82fbac7946a2e/pkg/sql/opt/exec/execbuilder/testdata/orderby#L581)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

In principle distsql should be allowed to plan multiple tablereaders each with limit 1 and get the first result (and it relies on this ordering to know what "first" means). I think we are fine right now, but please add a comment [here](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/distsql_physical_planner.go#L984), something like "Note that if we have a hard limit of 1, the scanNode won't necessarily have an ordering; if we ever plan multiple tablereaders in this case, we must make sure to set the merge ordering below to the natural order of the index we are scanning.
</blockquote></details>

Done.

---

*[pkg/sql/opt/memo/private_storage.go, line 152 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26975#-LFwaQgu8Rcanxuxyx2r:-LFy2VtqEh4-tpY1i2DD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/128530a1e1440f34df2ef77b8368186e2656d9c0/pkg/sql/opt/memo/private_storage.go#L152)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] internOrderingChoice
</blockquote></details>

Done.

---

*[pkg/sql/opt/memo/private_storage.go, line 477 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26975#-LFwamfO0C4ZjZDZJZV0:-LFy2YHz2PYqAvdwRzvA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/128530a1e1440f34df2ef77b8368186e2656d9c0/pkg/sql/opt/memo/private_storage.go#L477)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] separator
</blockquote></details>

Done.

---

*[pkg/sql/opt/norm/ordering.go, line 117 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26975#-LFy35Fd3bQV2dP9usGI:-LFz5sMTC9gkclxtTS-Z:b-th7g6q) ([raw file](https://github.com/cockroachdb/cockroach/blob/fff745c36a3ff69f089aa3dcecf82fbac7946a2e/pkg/sql/opt/norm/ordering.go#L117)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Doesn't `Simplify` already do this?
</blockquote></details>

Good catch, I once had a version of `Simplify` where it didn't and never removed this. Removed here and in another place.

---

*[pkg/sql/opt/norm/rules/ordering.opt, line 36 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26975#-LFy3xYj7qvEXRrAZN6_:-LFz7KhR424s-SP17tb6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fff745c36a3ff69f089aa3dcecf82fbac7946a2e/pkg/sql/opt/norm/rules/ordering.opt#L36)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Since you're reusing this function for Offset, maybe call it `CanSimplifyLimitOffsetOrdering` or `CanSimplifyOrderingPrivate` or something like that....
</blockquote></details>

Done.

---

*[pkg/sql/opt/ops/relational.opt, line 296 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26975#-LFwVKmJAxcT0ZPM4isy:-LFz7pxyE_Hw6CpIVUaa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/128530a1e1440f34df2ef77b8368186e2656d9c0/pkg/sql/opt/ops/relational.opt#L296)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] an -> a
</blockquote></details>

Done.

---

*[pkg/sql/opt/optbuilder/testdata/ordinality, line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26975#-LFwWGWX3ZqrU1YEizM3:-LFz7uG47ZnT-F5xIxm7:b931wn) ([raw file](https://github.com/cockroachdb/cockroach/blob/f46948f255ed234a2710b37f3b8983e1bda8f6ed/pkg/sql/opt/optbuilder/testdata/ordinality#L69)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why did you get rid of this test case?
</blockquote></details>

Because it's an exact duplicate of the one above. : )

---

*[pkg/sql/opt/props/ordering_choice.go, line 216 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26975#-LFwXV57CGpllmiglF1p:-LFz82zZDlG5b3RCVvfz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/128530a1e1440f34df2ef77b8368186e2656d9c0/pkg/sql/opt/props/ordering_choice.go#L216)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] missing >
</blockquote></details>

Done.

---

*[pkg/sql/opt/props/ordering_choice.go, line 343 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26975#-LFxzLD5Bf8mhvqoB7Tt:-LFz9bRy7ySPU_SkWW0O:b-hawbpj) ([raw file](https://github.com/cockroachdb/cockroach/blob/128530a1e1440f34df2ef77b8368186e2656d9c0/pkg/sql/opt/props/ordering_choice.go#L343)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

The logic in this loop is a bit confusing - a comment would help
</blockquote></details>

It should parallel the logic in `Simplify` almost exactly, as it's just meant to be a no-allocation version of that method. I added some additional comments to help.

---

*[pkg/sql/opt/xform/physical_props.go, line 23 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26975#-LFwlw1cAhUSaYgvILID:-LFy2eq15GPeRN-ZkbJb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b01b216698779aab49777d87eece86272c868f3a/pkg/sql/opt/xform/physical_props.go#L23)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] canProvidePhysicalProps
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/physical_props.go, line 31 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26975#-LFwm6_gCP8zK72FcKmT:-LFy2jnY8m-rRvopWAyh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b01b216698779aab49777d87eece86272c868f3a/pkg/sql/opt/xform/physical_props.go#L31)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] buildChildPhysicalProps
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26975)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/opt/exec/execbuilder/testdata/orderby, line 581 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26975#-LFweFmdBeKPhCtNvldm:-LG0TOSv5kAdg045LvH5:b-9w69bp) ([raw file](https://github.com/cockroachdb/cockroach/blob/fff745c36a3ff69f089aa3dcecf82fbac7946a2e/pkg/sql/opt/exec/execbuilder/testdata/orderby#L581)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Haha, `here` was a link, I meant in this code: https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/distsql_physical_planner.go#L984

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26975)*

**Comment by rytaft** [comment]
Review status: :shipit: complete! 2 of 0 LGTMs obtained

---

*[pkg/sql/opt/optbuilder/testdata/ordinality, line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26975#-LFwWGWX3ZqrU1YEizM3:-LG0XMEg2chvhnNQevJp:bs4lyqp) ([raw file](https://github.com/cockroachdb/cockroach/blob/f46948f255ed234a2710b37f3b8983e1bda8f6ed/pkg/sql/opt/optbuilder/testdata/ordinality#L69)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Because it's an exact duplicate of the one above. : )
</blockquote></details>

haha good catch

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26975)*

**Pull request merged**
