### PR TITLE
exec: get rid of Bools and Bytes; add some testing utils

### PR DESCRIPTION
**Pull request by jordanlewis**
opTestInput and opTestOutput allow testing operators without having to
construct ColBatches by hand, with a natural syntax inspired by
ProcessorTestCase.

Also, get rid of `Bools` in favor of `[]bool`, and `Bytes` in favor of `[][]byte`, as it's up to 4x slower at least on the Distinct benchmark.

Split from #31693.
Based on #31554.

### CODE REVIEW

**Review by asubiotto — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, 4 of 4 files at r3, 5 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31705)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/testutil.go, line 2 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31705#-LPSFSzq6LxITA81Ds8h:-LPSFSzq6LxITA81Ds8i:b-ao9smy) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4cfe3dd255b854b3aeba530a7ed36ec2bd08906/pkg/sql/exec/testutil.go#L2)):*
> ```Go
> // Copyright 2018 The Cockroach Authors.
> //
> ```

Is there a benefit to calling this file `util{s}_test.go` rather than `testutil.go`?
___
*[pkg/sql/exec/testutil.go, line 59 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31705#-LPSGEUnAmbPIawSFZcN:-LPSGEUnAmbPIawSFZcO:byg74g4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4cfe3dd255b854b3aeba530a7ed36ec2bd08906/pkg/sql/exec/testutil.go#L59)):*
> ```Go
> // The extraCols slice represents any extra columns that the batch must have
> // for output or temp columns for operators in the test.
> func newOpTestInput(tuples tuples, extraCols ...types.T) *opTestInput {
> ```

re: `extraCols`, I went down the route of allocating and reusing a batch inside the operator that is returned through `Next` instead of passing down output batches. What's your thinking here?
___
*[pkg/sql/exec/testutil.go, line 96 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31705#-LPSHPA5AhZHyiUaV_QC:-LPSHPA5AhZHyiUaV_QD:b-ail5oh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4cfe3dd255b854b3aeba530a7ed36ec2bd08906/pkg/sql/exec/testutil.go#L96)):*
> ```Go
> 	for i := range tuples {
> 		if len(tuples[i]) != tupleLen {
> 			panic(fmt.Sprintf("mismatched tuple len: found %d expected %d",
> ```

Maybe print out the tuple in question and index here.
___
*[pkg/sql/exec/testutil.go, line 183 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31705#-LPSI_pJDp4sDRojDIna:-LPSI_pJDp4sDRojDInb:b-p9wi3y) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4cfe3dd255b854b3aeba530a7ed36ec2bd08906/pkg/sql/exec/testutil.go#L183)):*
> ```Go
> func assertTupleEquals(expected tuple, actual tuple) error {
> 	if len(expected) != len(actual) {
> 		return errors.Errorf("expected %+v, actual %+v", expected, actual)
> ```

Consider adding some new lines here, the output might be easier to read
___
*[pkg/sql/exec/testutil.go, line 223 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31705#-LPSIq4m8CO24FVj4-6M:-LPSIq4m8CO24FVj4-6N:bwat0mt) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4cfe3dd255b854b3aeba530a7ed36ec2bd08906/pkg/sql/exec/testutil.go#L223)):*
> ```Go
> func (s *repeatableBatchSource) Next() ColBatch {
> 	s.internalBatch.SetSelection(false)
> 	s.internalBatch.SetLength(ColBatchSize)
> ```

Shouldn't this already have a set length that might be less than `ColBatchSize`?

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31705)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/testutil.go, line 2 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31705#-LPSFSzq6LxITA81Ds8h:-LPSNgJA2H88P0FkUzWp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4cfe3dd255b854b3aeba530a7ed36ec2bd08906/pkg/sql/exec/testutil.go#L2)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Is there a benefit to calling this file `util{s}_test.go` rather than `testutil.go`?
</blockquote></details>

Done.
___
*[pkg/sql/exec/testutil.go, line 59 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31705#-LPSGEUnAmbPIawSFZcN:-LPSKgtLEPWVWCWVQ4Vf:blmpp3b) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4cfe3dd255b854b3aeba530a7ed36ec2bd08906/pkg/sql/exec/testutil.go#L59)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

re: `extraCols`, I went down the route of allocating and reusing a batch inside the operator that is returned through `Next` instead of passing down output batches. What's your thinking here?
</blockquote></details>

Distinct is different from aggregate - it doesn't change the shape of the data. So it doesn't make sense to have the distinct operator allocate a new batch for its output - it should reuse its input batch as much as possible. This means that its input batch needs to have pre-allocated space for the output bool column. Planning will take care of making this happen - the eventual goal is that the top level operator would be in charge of allocating this extra space.
___
*[pkg/sql/exec/testutil.go, line 96 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31705#-LPSHPA5AhZHyiUaV_QC:-LPSKzDCE88qNzX7F4fZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4cfe3dd255b854b3aeba530a7ed36ec2bd08906/pkg/sql/exec/testutil.go#L96)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Maybe print out the tuple in question and index here.
</blockquote></details>

Done.
___
*[pkg/sql/exec/testutil.go, line 183 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31705#-LPSI_pJDp4sDRojDIna:-LPSLPXFA6cQvQDHdtXW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4cfe3dd255b854b3aeba530a7ed36ec2bd08906/pkg/sql/exec/testutil.go#L183)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Consider adding some new lines here, the output might be easier to read
</blockquote></details>

Done.
___
*[pkg/sql/exec/testutil.go, line 223 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31705#-LPSIq4m8CO24FVj4-6M:-LPSLTUp3MXpTGXjlmkJ:bl8lja6) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4cfe3dd255b854b3aeba530a7ed36ec2bd08906/pkg/sql/exec/testutil.go#L223)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Shouldn't this already have a set length that might be less than `ColBatchSize`?
</blockquote></details>

Good point. Fixed.

**Review by changangela — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31705)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/testutil.go, line 86 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31705#-LPSOmgnARR2IESlTfeM:-LPSOmgnARR2IESlTfeN:br175z8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4cfe3dd255b854b3aeba530a7ed36ec2bd08906/pkg/sql/exec/testutil.go#L86)):*
> ```Go
> 		return s.batch
> 	}
> 	batchSize := uint16(ColBatchSize)
> ```

Might be useful to allow the test cases to specify the input operator's batch size so that we can have more than one batch.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31705)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/testutil.go, line 86 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31705#-LPSOmgnARR2IESlTfeM:-LPSQ3Jr6VSRw4AoA8Og:bpca3dm) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4cfe3dd255b854b3aeba530a7ed36ec2bd08906/pkg/sql/exec/testutil.go#L86)):*
<details><summary><i>Previously, changangela (Angela Chang) wrote…</i></summary><blockquote>

Might be useful to allow the test cases to specify the input operator's batch size so that we can have more than one batch.
</blockquote></details>

Yeah, that's a good idea. I was envisioning that eventually it would be a configuration parameter, so you could run each test case with lots of different batch sizes without having to modify the code. I think this could be a future addition, though.

**Review by changangela — APPROVED** [review]

**Review by asubiotto — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31705)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/testutil.go, line 59 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31705#-LPSGEUnAmbPIawSFZcN:-LPSf95L3QARwaqeNJIb:b-b664bp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4cfe3dd255b854b3aeba530a7ed36ec2bd08906/pkg/sql/exec/testutil.go#L59)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Distinct is different from aggregate - it doesn't change the shape of the data. So it doesn't make sense to have the distinct operator allocate a new batch for its output - it should reuse its input batch as much as possible. This means that its input batch needs to have pre-allocated space for the output bool column. Planning will take care of making this happen - the eventual goal is that the top level operator would be in charge of allocating this extra space.
</blockquote></details>

What would be the downside of having all operators be in charge of preallocating their necessary output batches (or the upside of giving the top level operator that responsibility?)

**Comment by jordanlewis** [comment]
> What would be the downside of having all operators be in charge of preallocating their necessary output batches (or the upside of giving the top level operator that responsibility?)

That would introduce a required copy between each operator, I think. Otherwise, how do you propose tacking on the newly-allocated columns to the batch for downstream operators to look at?

Perhaps you could do something like that by appending new `memColumns` on the first call to `Next` for each operator. But it seems kind of weird to me, since each of those operators is really operating on the same underlying batch.

**Comment by jordanlewis** [comment]
TFTRs! Will merge now, we'll definitely need to keep working on this over time as our tests become more advanced.

bors r+

**Comment by jordanlewis** [comment]
Seems like a hosed agent? Let's try again:

bors r+

**Comment by jordanlewis** [comment]
It was a downed Debian repo. I think it should work now.

bors r+

**Pull request merged**
