### PR TITLE
sql/schemachanger: enhance coverage for drop index

### LINKED ISSUE #107733: sql/schemachanger: add better coverage for DROP INDEX
Currently, we need coverage for foreign keys and composite indexes in the end-to-end testing framework. Adding coverage here will allow us to ensure plan sanity and avoid bugs like #107576. Let's be more diligent and consider more scenarios in this area as well

Jira issue: CRDB-30175

Epic CRDB-30350

### PR DESCRIPTION
**Pull request by fqazi**
Previously, our DML injection testing for DROP index did not include any foreign key references or composite indexes. This patch adds extra coverage to include foreign key references with composite indexes in DML injection.

Fixes: #107733

Release note: None

### CODE REVIEW

**Comment by rafiss** [comment]
do you know if we need the test in this framework, versus the one in pkg/sql/schemachanger/dml_injection_test.go? just asking since that one is a bit simpler, so might have less maintenance overhead

**Comment by fqazi** [comment]
> do you know if we need the test in this framework, versus the one in pkg/sql/schemachanger/dml_injection_test.go? just asking since that one is a bit simpler, so might have less maintenance overhead

We probably should have it in both, since we did see a planning/builder bug dropping the wrong foreign keys, which that one won't cover.

**Review by fqazi — COMMENTED** [review]
I added this in that test framework too but the coverage we will get is limited, since we have no way of inserting into the table that can use the FK reference. It does however cover composite indexes, which just makes things a tad bit safer.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114044#-:-NikIGcgCvNhhN6pqw11:b-mxebml)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by rafiss — APPROVED** [review]

**Comment by rafiss** [comment]
ty for following up with this! glad we have this test now

**Comment by fqazi** [comment]
@rafiss TFTR!

bors r+

**Pull request merged**
