### PR TITLE
server,rpc: use an in-memory loopback connection for self-dials

### LINKED ISSUE #92054: *: use in-memory transport for local gRPC traffic
In https://github.com/cockroachlabs/support/issues/1875, we found several components attempting to connect to the local node via a gRPC network transport (and failing due to a missing DNS entry). These should use an internal in-memory transport instead. In particular:

* Range merges: to verify all replicas are initialized before merging.
* Consistency checks: to fetch the computed checksum from each replica.
* Below-Raft upgrade migrations: to verify the migration has been applied on all replicas.
* Tracing: to collect trace results.

These use `Dialer.Dial` to obtain a networked gRPC connection to the target. We have a separate method `DialInternalClient` that instead uses an in-memory transport:

https://github.com/cockroachdb/cockroach/blob/6e98b39bc6b14da51e43265c5512e23c88b91b2e/pkg/rpc/nodedialer/nodedialer.go#L140-L145

However, this method can only obtain a client for the `Internal` gRPC service (which in particular provides the `Batch` RPC method). The components above need access to different gRPC services, in particular the `PerReplica` service.

We'll either need to add separate dial methods with in-memory transports for each gRPC service that may need to connect to the local node, or generalize the in-memory transport in such a way that it can work regardless of the gRPC service.

Jira issue: CRDB-21548

### PR DESCRIPTION
**Pull request by knz**
Fixes  #92054.
Informs #84591.
Needed as prereq for #92524.

This change ensures that a server is always able to perform RPC dials
to itself. It also makes self-dial more lightweight (no compression,
no keepalive, etc).

Note that despite this PR, we still have two separate code paths
for self-dials:

- the distsender works at a higher level and performs dials using
  `(rpc.Dialer).DialInternalClient()`, which returns a
  `rpc.RestrictedInternalClient` (an interface with just the KV
  methods needed by distsender). This uses direct Go function
  calls for the API functions, and eschews data
  serialization/deserialization entirely.

- everything else works at a lower level, using `(rpc.Dialer).Dial()`
  which returns a `grpc.ClientConn`, followed by
  `pkgpb.NewXXXClient(conn)` that defines the gRPC client-side
  implementation of the API. This mandates uses of a network
  pipe, forces data serialization/deserialization, and (currently)
  force use of TLS for authentication.

  This is the path that is simplified with this PR, using
  an in-memory pipe for the network dial instead of a TCP connection.

An alternate approach to this PR would be to convert all uses
of `(rpc.Dialer).Dial` and replace them with a `(rpc.Dial).GetClient`
call, which conditionally bypasses the network dial and returns
an interface able to call the underlying RPC functions directly
(without data serialization/deserialization, etc). However, this would
be a much larger lift - there's currently more than 50 such API
boundaries.

### CODE REVIEW

**Comment by knz** [comment]
@erikgrinaker @tbg do you want to have a preliminary look to check if I've got the general direction right?

Regarding test, it seems to me this is already plenty tested by all our multi-node unit tests.

But depending on what you and CI think, i'll implement some additional testing.

**Comment by erikgrinaker** [comment]
I'm not very familiar with the RPC layer, so I'm not particularly qualified to comment on this, but it seems reasonable to me. Is the plan to also replace the `Dialer.DialInternalClient` logic and `internalClientAdapter` with this? If not, is there any value in combining this with the `internalClientAdapter` logic? It appears to have a bunch of performance optimizations and such.

**Comment by knz** [comment]
> Is the plan to also replace the Dialer.DialInternalClient logic and internalClientAdapter with this?

No, there is no such plan.

> If not, is there any value in combining this with the internalClientAdapter logic?

There's theoretical value, but it's much more complex. I have extended the commit message / PR description to explain why.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92662)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @knz)

___
*[`-- commits` line 2 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92662#-NI8DifR3nOgRg8Z4yAe):*
packate?
___
*[`-- commits` line 5 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/92662#-NI8Me5l3VU4QeXmbNbK):*
you seemed to concede the wrapping at 80 cols argument, but the comments in this patch are not right :)
___
*[`pkg/rpc/context.go` line 1379 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/92662#-NI8G7Ub9kFTu1VOfUsH:-NI8G7Ub9kFTu1VOfUsI:b-x2ewp9) ([raw file](https://github.com/cockroachdb/cockroach/blob/190c6733f38a34e7f0ff3de7ea17aa133f4f62ec/pkg/rpc/context.go#L1379)):*
> ```Go
> }
> 
> // GRPCNetworkDialOptions returns suitable `grpc.DialOption`s necessary to connect
> ```

Something here doesn't seem right to me. `GRPCNetworkDialOptions` is passing `""` for `target`. I think that's bogus - always bogus, or at the very least bogus when the intended connection is over the network. So I don't think this function is "suitable" for anything, as the comment says. I think we should squash this commit with the next; I think it makes little sense on its own. And then I think the one real caller of this function needs to change, and this function needs to take the target I think. 
___
*[`pkg/rpc/context.go` line 1380 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/92662#-NI8E9DYARRwk9NFCnoM:-NI8E9DYARRwk9NFCnoN:b-k587kd) ([raw file](https://github.com/cockroachdb/cockroach/blob/190c6733f38a34e7f0ff3de7ea17aa133f4f62ec/pkg/rpc/context.go#L1380)):*
> ```Go
> 
> // GRPCNetworkDialOptions returns suitable `grpc.DialOption`s necessary to connect
> // to a server created with `NewServer` over the network.
> ```

s/created with `NewServer`/
___
*[`pkg/rpc/context.go` line 1382 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/92662#-NI8K6iR7xqy4YVAXGte:-NI8K6iR7xqy4YVAXGtf:b-mifno5) ([raw file](https://github.com/cockroachdb/cockroach/blob/190c6733f38a34e7f0ff3de7ea17aa133f4f62ec/pkg/rpc/context.go#L1382)):*
> ```Go
> // to a server created with `NewServer` over the network.
> func (rpcCtx *Context) GRPCNetworkDialOptions() ([]grpc.DialOption, error) {
> 	return rpcCtx.grpcDialOptions("", DefaultClass)
> ```

if this `""` remains, I think it deserves a `/* target */`, so that everybody sees that something dubious is going on
___
*[`pkg/rpc/context.go` line 1393 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/92662#-NI8EjBE7O9SosFZO_Qi:-NI8EjBE7O9SosFZO_Qj:bitjwqs) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bf05dd235a680ac58363220a76809b9e300b183/pkg/rpc/context.go#L1393)):*
> ```Go
> // grpcDialOptions produces dial options suitable for connecting to the given target and class.
> func (rpcCtx *Context) grpcDialOptions(
> 	target string, class ConnectionClass, overNetwork bool,
> ```

The new arg deserves a comment. But better yet, can we use a sentinel value for `target` to signify a local connection? I don't think `target == "" && overNetwork` should be allowed.
___
*[`pkg/rpc/context.go` line 1455 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/92662#-NI8OAYA-y0lLlzsdBEr:-NI8OAYA-y0lLlzsdBEs:bd7k9nb) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bf05dd235a680ac58363220a76809b9e300b183/pkg/rpc/context.go#L1455)):*
> ```Go
> // dialOptsNetwork compute options used only for over-the-network RPC connections.
> func (rpcCtx *Context) dialOptsNetwork(
> 	target string, class ConnectionClass,
> ```

nit: get rid of the named return values in these functions; the code was better without them. They don't serve any purpose here. I don't know how you feel about this, but I think it's generally considered bad forms to use them to gratuitously introduce vars in scope. So I think they're only used when either you need them in a `defer`, or when you want them for docs cause you've got 7 bools being returned in a row - but then you should only use them for the vals where they're useful, and use `_` for the rest.
___
*[`pkg/rpc/context.go` line 394 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/92662#-NI8UvDQ78s60y8xPwmj:-NI8UvDQ78s60y8xPwmk:b-phn49i) ([raw file](https://github.com/cockroachdb/cockroach/blob/e254f6eb9cfe4b1f49cd2633cd4555b6b9b2af78/pkg/rpc/context.go#L394)):*
> ```Go
> 	logClosingConnEvery log.EveryN
> 
> 	// loopbackDialFn, when non-nil, is used for local dials.
> ```

maybe here would be a good place to mention the `internalClientAdapter` and when that one is used
___
*[`pkg/rpc/context.go` line 1799 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/92662#-NI8P5HVCXsThjWX0s1j:-NI8P5HW4zSiQ-r9L2I_:b4g1kpm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e254f6eb9cfe4b1f49cd2633cd4555b6b9b2af78/pkg/rpc/context.go#L1799)):*
> ```Go
> ) (*grpc.ClientConn, error) {
> 	overNetwork := true
> 	if rpcCtx.loopbackDialFn != nil && rpcCtx.Config.AdvertiseAddr == target {
> ```

who needs the nil protection? If it's just `rpcCtx` tests, and those tests want to connect to `AdvertiseAddr`, are we doing them a favor by letting them not exercise the production code path?
___
*[`pkg/rpc/context.go` line 1859 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/92662#-NI8V8Gy7zPyAhZQUPfl:-NI8V8Gy7zPyAhZQUPfm:b6v52tz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e254f6eb9cfe4b1f49cd2633cd4555b6b9b2af78/pkg/rpc/context.go#L1859)):*
> ```Go
> 		}
> 	} else {
> 		dialerFn = func(ctx context.Context, _ string) (net.Conn, error) {
> ```

before I make up my mind about whether this `loopbackDialFn` is worth it, let me ask you this - if you take the regular, network listener, and do `l.Addr()`, does that give you an address that you can always connect to, no matter how the node was configured - i.e. regardless of whether it was told to listen on all network interfaces or not and whether the advertise address is a DNS name?
___
*[`pkg/server/start_listen.go` line 115 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/92662#-NI8U83M27KPpnwordpl:-NI8U83M27KPpnwordpm:bhbjur2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e254f6eb9cfe4b1f49cd2633cd4555b6b9b2af78/pkg/server/start_listen.go#L115)):*
> ```Go
> 	}
> 
> 	loopbackL := netutil.NewLoopbackListener(ctx, stopper)
> ```

I was surprised to see a second loopback listener. I didn't even know before this that a grpc server can serve on multiple listeners. Wouldn't it be worth having just one, for both grpc-gw and this new self-dial?

**Comment by knz** [comment]
> before I make up my mind about whether this loopbackDialFn is worth it, let me ask you this - if you take the regular, network listener, and do l.Addr(), does that give you an address that you can always connect to, no matter how the node was configured

Nope - there's no guarantee that an arbitrary IP interface in the system is available to _local processes_ for connection. Firewall rules are typically per interface and it's somewhat common to restrict listeners on _external_ interfaces to only be reachable from outside.

The only one that's guaranteed reachable is the "advertise address" which is the one we want to avoid here.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92662)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @knz)

___
*[`pkg/rpc/context.go` line 1462 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/92662#-NI8_xzL5JkVCHaQEWAa:-NI8_xzL5JkVCHaQEWAb:b-krvu3k) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bf05dd235a680ac58363220a76809b9e300b183/pkg/rpc/context.go#L1462)):*
> ```Go
> 	}
> 
> 	// Compression is enabled separately from decompression to allow staged
> ```

Consider seeing if we can simplify whatever cruft this is talking about.
___
*[`pkg/rpc/context.go` line 1808 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/92662#-NI8aMn02g6MfzH_cmHP:-NI8aMn02g6MfzH_cmHQ:bz04wzy) ([raw file](https://github.com/cockroachdb/cockroach/blob/e254f6eb9cfe4b1f49cd2633cd4555b6b9b2af78/pkg/rpc/context.go#L1808)):*
> ```Go
> 
> 	if overNetwork {
> 		// Lower the MaxBackoff (which defaults to ~minutes) to something in the
> ```

doesn't this crap belong in the functions dealing with dialing options?
___
*[`pkg/rpc/context.go` line 1859 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/92662#-NI8V8Gy7zPyAhZQUPfl:-NI8Za_p7N7ZTiIjS3PQ:b37utnr) ([raw file](https://github.com/cockroachdb/cockroach/blob/e254f6eb9cfe4b1f49cd2633cd4555b6b9b2af78/pkg/rpc/context.go#L1859)):*
(copying answer to the right thread...)

> Nope - there's no guarantee that an arbitrary IP interface in the system is available to local processes for connection. Firewall rules are typically per interface and it's somewhat common to restrict listeners on external interfaces to only be reachable from outside.

> The only one that's guaranteed reachable is the "advertise address" which is the one we want to avoid here.

OK, this makes sense to me then. Please put a comment somewhere saying that this self-dial is about making sure you can always connect to yourself.
Please run something like 'BenchmarkKV`to see if this makes any difference (I don't think it will).

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92662)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @erikgrinaker)

___
*[`-- commits` line 2 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92662#-NI8DifR3nOgRg8Z4yAe):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

packate?
</blockquote></details>

Done.
___
*[`-- commits` line 5 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/92662#-NI8Me5l3VU4QeXmbNbK):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

you seemed to concede the wrapping at 80 cols argument, but the comments in this patch are not right :)
</blockquote></details>

I'm trying to find them but I don't see it. Do you have an example?
___
*[`pkg/rpc/context.go` line 1379 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/92662#-NI8G7Ub9kFTu1VOfUsH:-NI9S-lT-zPvgOg2D-N4:b-bhp3w2) ([raw file](https://github.com/cockroachdb/cockroach/blob/190c6733f38a34e7f0ff3de7ea17aa133f4f62ec/pkg/rpc/context.go#L1379)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Something here doesn't seem right to me. `GRPCNetworkDialOptions` is passing `""` for `target`. I think that's bogus - always bogus, or at the very least bogus when the intended connection is over the network. So I don't think this function is "suitable" for anything, as the comment says. I think we should squash this commit with the next; I think it makes little sense on its own. And then I think the one real caller of this function needs to change, and this function needs to take the target I think. 
</blockquote></details>

Yeah that target thing was bogus. Removed. The function does not need the target.
___
*[`pkg/rpc/context.go` line 1380 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/92662#-NI8E9DYARRwk9NFCnoM:-NI9U3npEpiLqwfhF7JP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/190c6733f38a34e7f0ff3de7ea17aa133f4f62ec/pkg/rpc/context.go#L1380)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

s/created with `NewServer`/
</blockquote></details>

Done.
___
*[`pkg/rpc/context.go` line 1382 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/92662#-NI8K6iR7xqy4YVAXGte:-NI9U4PTEcnnAYwoRFT4:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/190c6733f38a34e7f0ff3de7ea17aa133f4f62ec/pkg/rpc/context.go#L1382)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

if this `""` remains, I think it deserves a `/* target */`, so that everybody sees that something dubious is going on
</blockquote></details>

Removed.
___
*[`pkg/rpc/context.go` line 1393 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/92662#-NI8EjBE7O9SosFZO_Qi:-NI9U5jW-mj7vwL-_TMv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bf05dd235a680ac58363220a76809b9e300b183/pkg/rpc/context.go#L1393)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

The new arg deserves a comment. But better yet, can we use a sentinel value for `target` to signify a local connection? I don't think `target == "" && overNetwork` should be allowed.
</blockquote></details>

Done.
___
*[`pkg/rpc/context.go` line 1455 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/92662#-NI8OAYA-y0lLlzsdBEr:-NI9LgUgECLnlL7-h5AN:b-7wcw8u) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bf05dd235a680ac58363220a76809b9e300b183/pkg/rpc/context.go#L1455)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: get rid of the named return values in these functions; the code was better without them. They don't serve any purpose here. I don't know how you feel about this, but I think it's generally considered bad forms to use them to gratuitously introduce vars in scope. So I think they're only used when either you need them in a `defer`, or when you want them for docs cause you've got 7 bools being returned in a row - but then you should only use them for the vals where they're useful, and use `_` for the rest.
</blockquote></details>

I don't have a strong opinion here, so i'll just run by your book here. Done.
___
*[`pkg/rpc/context.go` line 1462 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/92662#-NI8_xzL5JkVCHaQEWAa:-NI9W5rf4qgi7iBSg5lE:b-wxo95y) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bf05dd235a680ac58363220a76809b9e300b183/pkg/rpc/context.go#L1462)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Consider seeing if we can simplify whatever cruft this is talking about.
</blockquote></details>

I have checked and there's no cruft - Tamir was explaining here that compression is opt-in for each client, and a server supports both compressed and non-compressed requests. It wasn't so clear though, so I reworded that

What I also found interesting is that compression is not enabled by default; and that we've bothered to import our own snappy compression instead of using grpc's native gzip. I'm not sure that's ever been justified. Added a comment to explain that too.
___
*[`pkg/rpc/context.go` line 394 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/92662#-NI8UvDQ78s60y8xPwmj:-NI9_rvZ4saoYOMGADw_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e254f6eb9cfe4b1f49cd2633cd4555b6b9b2af78/pkg/rpc/context.go#L394)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

maybe here would be a good place to mention the `internalClientAdapter` and when that one is used
</blockquote></details>

Done.
___
*[`pkg/rpc/context.go` line 1799 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/92662#-NI8P5HVCXsThjWX0s1j:-NI9dItx6tuFjz65teB2:bqryhzr) ([raw file](https://github.com/cockroachdb/cockroach/blob/e254f6eb9cfe4b1f49cd2633cd4555b6b9b2af78/pkg/rpc/context.go#L1799)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

who needs the nil protection? If it's just `rpcCtx` tests, and those tests want to connect to `AdvertiseAddr`, are we doing them a favor by letting them not exercise the production code path?
</blockquote></details>

Good point. Only very few tests need this special case. Added a knob.
___
*[`pkg/rpc/context.go` line 1808 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/92662#-NI8aMn02g6MfzH_cmHP:-NI9MyC02k1jRu8BY66a:b-qu6n94) ([raw file](https://github.com/cockroachdb/cockroach/blob/e254f6eb9cfe4b1f49cd2633cd4555b6b9b2af78/pkg/rpc/context.go#L1808)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

doesn't this crap belong in the functions dealing with dialing options?
</blockquote></details>

Good point. Done.
___
*[`pkg/rpc/context.go` line 1859 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/92662#-NI8V8Gy7zPyAhZQUPfl:-NI9YvYYCrUjfK4rDdiB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e254f6eb9cfe4b1f49cd2633cd4555b6b9b2af78/pkg/rpc/context.go#L1859)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

(copying answer to the right thread...)

> Nope - there's no guarantee that an arbitrary IP interface in the system is available to local processes for connection. Firewall rules are typically per interface and it's somewhat common to restrict listeners on external interfaces to only be reachable from outside.

> The only one that's guaranteed reachable is the "advertise address" which is the one we want to avoid here.

OK, this makes sense to me then. Please put a comment somewhere saying that this self-dial is about making sure you can always connect to yourself.
Please run something like 'BenchmarkKV`to see if this makes any difference (I don't think it will).
</blockquote></details>

Done.
___
*[`pkg/server/start_listen.go` line 115 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/92662#-NI8U83M27KPpnwordpl:-NI9RsVA7U-4tXn1tMB6:bopd9ps) ([raw file](https://github.com/cockroachdb/cockroach/blob/e254f6eb9cfe4b1f49cd2633cd4555b6b9b2af78/pkg/server/start_listen.go#L115)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I was surprised to see a second loopback listener. I didn't even know before this that a grpc server can serve on multiple listeners. Wouldn't it be worth having just one, for both grpc-gw and this new self-dial?
</blockquote></details>

Oops :facepalm: 
This was meant to be deleted. Done.

**Review by andreimatei — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92662#-:-NIE6ZHI0wUSefcRNk3I:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @erikgrinaker and @knz)

___
*[`-- commits` line 5 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/92662#-NI8Me5l3VU4QeXmbNbK):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I'm trying to find them but I don't see it. Do you have an example?
</blockquote></details>

Literally every single comment touched in this PR. I went through the first few, below, and then I stopped.

Every paragraph in
```
	// loopbackDialFn, when non-nil, is used when the target of the dial
	// is ourselves (== AdvertiseAddr).
	//
	// This special case is not merely a performance optimization: it
	// ensures that we are always able to self-dial. Reasons that could
	// block a self-dial, and have been seen in the wild, include:
	//
	// - DNS is not ready so AdvertiseAddr does not resolve.
	// - firewall rule only allows other machines to connect to our
	//   listen/external address, not ourselves.
	// - TCP port shortage on the local interface.
	//
	// The loopback listener is guaranteed to never talk to the OS'
	// TCP stack and thus always avoids any TCP-related shortcoming.
	//
	// Note that this mechanism is separate (and fully independent) from
	// the one used to provide the RestrictedInternalClient interface
	// via DialInternalClient(). RestrictedInternalClient is an
	// optimization for the "hot path" of KV batch requests, that takes
	// many shortcuts through our abstraction stack to provide direct Go
	// function calls for API functions, without the overhead of data
	// serialization/deserialization.
	//
	// At this stage, we only plan to use this optimization for the
	// small set of RPC endpoints it was designed for. The "common case"
	// remains the regular gRPC protocol using ser/deser over a link.
	// The loopbackDialFn fits under that common case by transporting
	// the gRPC protocol over an in-memory pipe.
```

```
// ErrLocalListenerClosed is returned when the listener
// is shutting down.
```

```
	// loopbackTransport is used for in-memory connections that bypass
	// the TCP stack entirely, using the loopback listener.
```


```
// GRPCLoopbackDialOptions returns the minimal `grpc.DialOption`s necessary to connect
// to a server created with `NewServer` using an in-memory pipe.
```

```
// grpcDialOptions produces dial options suitable for connecting to the given target and class.
```

both paragrpahs in
```
	// We need to include a TLS overlay even for loopback connections,
	// because currently a non-insecure server always refuses non-TLS
	// incoming connections, and inspects the TLS certs to determine the
	// identity of the client peer.
	//
	// We can elide TLS for loopback connections when we add a non-TLS
	// way to identify peers, i.e. fix these issues:
	// https://github.com/cockroachdb/cockroach/issues/54007
	// https://github.com/cockroachdb/cockroach/issues/91996
```

**Review by dhartunian — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 12 of 12 files at r13, 5 of 5 files at r14.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92662)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @erikgrinaker, and @knz)

___
*[`pkg/rpc/context.go` line 1446 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/92662#-NJBJDzp--5sTM-ExPTj:-NJBJDzp--5sTM-ExPTk:b-doli30) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a5cb5109d6b7e122e996a44f940bfd61698cd81/pkg/rpc/context.go#L1446)):*
> ```Go
> 		}
> 	}
> 	if rpcCtx.Knobs.InjectedLatencyOracle != nil {
> ```

I don't see where the latency injection code is moved to. Does it need to stay?

**Comment by knz** [comment]
> I don't see where the latency injection code is moved to. Does it need to stay?

**Comment by knz** [comment]
> I don't see where the latency injection code is moved to. Does it need to stay?

lol, yes. Guess why CI is complaining :)

I'm on it.

**Comment by knz** [comment]
TFYRs!

bors r=andreimatei

**Pull request merged**
