### PR TITLE
upgrades: fix idempotence issue in system table role id migrations

### LINKED ISSUE #91449: sql: rerunning an intermediate system table user ID migration will fail
I came across this issue when trying to write a series of migrations adding user ID columns to the `system.role_members` table.

For every schema change migration, a `schemaExistsFn` (defined [here](https://github.com/cockroachdb/cockroach/blob/c37505829d0604d34d9618077deaa7d3339256c5/pkg/upgrade/upgrades/schema_changes.go#L43) and used [here](https://github.com/cockroachdb/cockroach/blob/c37505829d0604d34d9618077deaa7d3339256c5/pkg/upgrade/upgrades/schema_changes.go#L110)) needs to be provided, which checks whether the schema change already exists. One such function is `hasColumn` (defined [here](https://github.com/cockroachdb/cockroach/blob/c37505829d0604d34d9618077deaa7d3339256c5/pkg/upgrade/upgrades/schema_changes.go#L179-L212)), which verifies that either the column does not already exist or it matches the table descriptor in `pkg/sql/catalog/systemschema/system.go` exactly.

The previously merged internal user ID migrations, which can be found in `pkg/upgrade/upgrades/system_users_role_id_migration.go` and `pkg/upgrade/upgrades/role_options_table_migration.go`, roughly performs a system table schema change through the following series of migrations:
1. Add the new column(s) as nullable (`NULL`) columns to the table and create indexes for them
2. Backfill the column(s)
3. Change the column(s) to be not nullable (`NOT NULL`)

The migrations in step 1 for both of the existing migrations make use of `hasColumn` and so if the migration were to be run again after the adding of the columns has succeeded (but before the step 3 migration successfully completes), they would fail since `hasColumn` expects the column to either not exist, or be `NOT NULL` (to match the desired final state specified in the descriptor). This would prevent the completion of that migration as well as any further migrations. I believe this issue can be fixed by writing a custom `schemaExistsFn` for the migration in step 1 that basically mirrors `hasColumn` but allows the expected column descriptor to have `Nullable == false` while the actual column descriptor has `Nullable == true`.

However, I'm not sure if this would actually ever be a problem because it would mean that the migration succeeded in adding the column, but was somehow forced to run again. This only occurred during my local development because I had an incorrect query later on in my step 1 migration.

Jira issue: CRDB-21269

Epic CRDB-19134

### PR DESCRIPTION
**Pull request by andyyang890**
This patch fixes an idempotence issue in the role id migrations for
the system.users and system.role_options tables.

Fixes #91449

Release note: None

### CODE REVIEW

**Comment by andyyang890** [comment]
Depends on #91756

**Comment by andyyang890** [comment]
Depends on #91755

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91756#-:-NGwTOf4912MIeHKU0MH:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss)

**Review by rafiss — APPROVED** [review]
> Reviewed 3 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91756)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andyyang890)

**Comment by andyyang890** [comment]
blathers failed to auto backport #91755 so I'll need to manually backport both of these

**Comment by andyyang890** [comment]
bors r=ajwerner,rafiss

**Comment by andyyang890** [comment]
test flakes

bors r=ajwerner,rafiss

**Pull request merged**
