### PR TITLE
stability: support context cancellation in replica queues

### LINKED ISSUE #9027: storage: single bad replica can muck up Replica queues
Similar to #8638, a single bad replica can muck up the Replica queues that try to acquire a leader lease and perhaps for other reasons as well. `baseQueue.processReplica` does not set a timeout on the context used for replica processing. If a replica is part of a range that doesn't have a quorum, we won't be able to acquire the leader lease and will block forever trying to do so. There might be other ways in which a single Replica can block up a queue. We should be more defensive here and set a timeout for processing of a single Replica on a queue.

### PR DESCRIPTION
**Pull request by spencerkimball**
Fixes #9027

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9312)

### CODE REVIEW

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[storage/queue.go, line 211 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9312#-KRXtsjTXvKHsxkTt31W:-KRXtsjTXvKHsxkTt31X:bsrjxo9) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c57489877bf6592c7b51d93ad8fb53fed4e3550/storage/queue.go#L211)):*
> ```Go
> ) baseQueue {
> 	// Always insist on at least the default timeout.
> 	if cfg.processTimeout == 0*time.Second {
> ```

The comment implies that this should be `cfg.processTimeout < defaultProcessTimeout`. (or you could change the timeout since it looks like you rely on this in tests)

Nit: the `*time.Second` is unnecessary

---

*[storage/queue_test.go, line 615 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9312#-KRXuwZHMCpAp6QezKYj:-KRXuwZHMCpAp6QezKYk:bqmb5vt) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c57489877bf6592c7b51d93ad8fb53fed4e3550/storage/queue_test.go#L615)):*
> ```Go
> 		},
> 	}
> 	bq := makeBaseQueue("test", ptQueue, tc.store, tc.gossip, queueConfig{maxSize: 1, processTimeout: 1 * time.Millisecond})
> ```

Wrap this line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9312#-:-KRXv-qbWevcrqG7H1RJ:bnfp4nl)*

**Comment by spencerkimball** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[storage/queue.go, line 211 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9312#-KRXtsjTXvKHsxkTt31W:-KRYiR7Vf8sJGBHr8T3k:b6r96yn) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c57489877bf6592c7b51d93ad8fb53fed4e3550/storage/queue.go#L211)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> The comment implies that this should be `cfg.processTimeout < defaultProcessTimeout`. (or you could change the timeout since it looks like you rely on this in tests)
> 
> Nit: the `*time.Second` is unnecessary
</details>
I updated the comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9312)*

**Comment by tschottdorf** [comment]
Reviewed 5 of 7 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[storage/queue.go, line 44 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9312#-KRZ6L1x-04CycbxVdZL:-KRZ6L1x-04CycbxVdZM:b3bmb2g) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3228a5fb1b214881360998ecb72a43be6bf0c31/storage/queue.go#L44)):*
> ```Go
> 	// defaultProcessTimeout is the timeout when processing a replica.
> 	// The timeout prevents a queue from getting stuck on a replica.
> 	// For example, a replica whose range is not be reachable for
> ```

s/is not be/is not/

---

*[storage/verify_queue.go, line 101 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9312#-KRZ6koA3SFHiGqp509i:-KRZ6koA3SFHiGqp509j:bivfne1) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3228a5fb1b214881360998ecb72a43be6bf0c31/storage/verify_queue.go#L101)):*
> ```Go
> 		// Check the context for cancellation.
> 		select {
> 		case <-ctx.Done():
> ```

This seems like a random place to test this. Why does this make sense here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9312)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[storage/verify_queue.go, line 101 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9312#-KRZ6koA3SFHiGqp509i:-KRZ6uSTlrL9oZZ5mhSp:b-rdk63m) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3228a5fb1b214881360998ecb72a43be6bf0c31/storage/verify_queue.go#L101)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> This seems like a random place to test this. Why does this make sense here?
</details>
Also, on an unrelated note, the consistency checker should also already touch that data, so perhaps this queue can go away completely.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9312)*

**Comment by spencerkimball** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[storage/verify_queue.go, line 101 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9312#-KRZ6koA3SFHiGqp509i:-KRZhbhrEAfO70pUoV8Y:biu6cqm) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3228a5fb1b214881360998ecb72a43be6bf0c31/storage/verify_queue.go#L101)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Also, on an unrelated note, the consistency checker should also already touch that data, so perhaps this queue can go away completely.
</details>
Yeah, I was thinking the same thing.

My thought here was there's something wrong with accessing a disk. Checksum errors and retries at the disk level or something along those lines. Probably not something to worry about in practice.

Going to create an issue to remove the verify queue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9312)*

**Pull request merged**
