### PR TITLE
cli: Make unsafe-remove-dead-replicas work with multiple stores

### PR DESCRIPTION
**Pull request by bdarnell**
Release justification: Non-production changes

### CODE REVIEW

**Review by darinpp — APPROVED** [review]
Looks good. It needs to be back-ported to 19.1 too.

**Comment by bdarnell** [comment]
I don't know that this really needs to be backported - this will only be used in exceptional cases and it seems reasonable to use a custom binary for the current cases (and in the future a 19.2 release).

**Comment by bdarnell** [comment]
This approach turns out to be unsound (the new test is flaky). I thought I'd be able to remove the two dead replicas and let the surviving replicas campaign for raft leadership, in which case the one with the longer log will win and catch the other one up. But it's possible that this catching up will overwrite changes made by the repair tool, leading the replicas to diverge. (specifically, if there was a rebalance in progress, writing an intent to the range descriptor key. The repair tool would delete the intent from any replicas that had it, but wouldn't prevent it from re-applying on  any that needed to catch up)

So we can't recover from two replicas unless they happen to be at the same log position. I think that means this tool will have to be changed to take the range down to one replica, and either destroy the other one directly or ensure that it will be GC'd. I need to think some more about whether editing the range descriptor and bumping NextReplicaID (like we used to do) would be sufficient.

**Comment by andy-kimball** [comment]
@bdarnell, can we delete all replicas (dead or otherwise), except the replica with the longest log?

**Comment by bdarnell** [comment]
Yes, that's the idea. The problem is that in this offline tool we can't determine locally which one has the longest log, so it's going to have to be a multi-step process to figure out exactly what to do.

**Comment by bdarnell** [comment]
In the specific occurrences that motivated this update, the raft logs were in sync. That simplifies things greatly: we can pick an arbitrary replica as the winner. I've updated this PR to do that (picking the replica with the highest store ID). If the raft logs on the surviving replicas were unequal we might lose some committed writes that could have been salvaged by picking the other one, but we can save that for future work.

**Review by tbg — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41266)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @bdarnell)

___
*[pkg/cli/debug.go, line 1258 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/41266#-LqThdK45H5I8_nA0Jht:-LqThdK45H5I8_nA0Jhu:b-wzrhtw) ([raw file](https://github.com/cockroachdb/cockroach/blob/c30e0a7266638812f606c3284ee7a8859d992da7/pkg/cli/debug.go#L1258)):*
> ```Go
> 	}
> 
> 	return batch, nil
> ```

Hmm, this batch rewrites the range-local copy of the range descriptor, but not the one in the meta ranges. Isn't that a problem? I thought we CPut these everywhere. Furthermore, the copy you're restoring here might be missing a split that is reflected in meta2.
___
*[pkg/cli/debug.go, line 1300 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/41266#-LqTgsZ63idb0XoQlzAV:-LqTgsZ63idb0XoQlzAW:bq4lu5t) ([raw file](https://github.com/cockroachdb/cockroach/blob/c30e0a7266638812f606c3284ee7a8859d992da7/pkg/cli/debug.go#L1300)):*
> ```Go
> }
> 
> var debugClusterLogicalTimestampCommand = &cobra.Command{
> ```

```
$ ./cockroach demo -e 'select cluster_logical_timestamp()';
    cluster_logical_timestamp
+--------------------------------+
  1570325622579125000.0000000000
(1 row)
```

Just saying that this exists, not opposed to keeping this helper.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41266)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @bdarnell)

___
*[pkg/cli/debug.go, line 1258 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/41266#-LqThdK45H5I8_nA0Jht:-LqTzf1C-lTfcJ2vI7vQ:btny6ly) ([raw file](https://github.com/cockroachdb/cockroach/blob/c30e0a7266638812f606c3284ee7a8859d992da7/pkg/cli/debug.go#L1258)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Hmm, this batch rewrites the range-local copy of the range descriptor, but not the one in the meta ranges. Isn't that a problem? I thought we CPut these everywhere. Furthermore, the copy you're restoring here might be missing a split that is reflected in meta2.
</blockquote></details>

Ooh, we simply `Put` the range addressing - nevermind.

If we're undoing a split or merge though, we're going to be screwed. I guess we're just going to assume that this is not likely to happen.

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41266)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @tbg)

___
*[pkg/cli/debug.go, line 1258 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/41266#-LqThdK45H5I8_nA0Jht:-LqWWs0o5MECAlRELgIu:b-c0zpce) ([raw file](https://github.com/cockroachdb/cockroach/blob/c30e0a7266638812f606c3284ee7a8859d992da7/pkg/cli/debug.go#L1258)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Ooh, we simply `Put` the range addressing - nevermind.

If we're undoing a split or merge though, we're going to be screwed. I guess we're just going to assume that this is not likely to happen.
</blockquote></details>

Added some comments to explain how this is safe:

```
		// Write the rewritten descriptor to the range-local descriptor
		// key. We do not update the meta copies of the descriptor.
		// Instead, we leave them in a temporarily inconsistent state and
		// they will be overwritten when the cluster recovers and
		// up-replicates this range from its single copy to multiple
		// copies. We rely on the fact that all range descriptor updates
		// start with a CPut on the range-local copy followed by a blind
		// Put to the meta copy.

```

```
			// We rely on the property that transactions involving the range
			// descriptor always start on the range-local descriptor's key.
			// This guarantees that when the transaction commits, the intent
			// will be resolved synchronously. If we see an intent on this
			// key, we know that the transaction did not commit and we can
			// abort it.
			//
			// TODO(nvanbenschoten): Does this need updating for parallel commits?
```

I was about to say that we can't undo a committed split or merge this way, but now I see what you're saying. The split could have committed and applied on 2/3 replicas (and the meta ranges), and we're recovering from one replica that didn't get the message. Yeah, that would be bad. That's another reason why this tool is unsafe; guaranteed-correct recovery from this situation is impossible. 
___
*[pkg/cli/debug.go, line 1300 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/41266#-LqTgsZ63idb0XoQlzAV:-LqWXaNx150wDvOzhn3J:b-lan4hg) ([raw file](https://github.com/cockroachdb/cockroach/blob/c30e0a7266638812f606c3284ee7a8859d992da7/pkg/cli/debug.go#L1300)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

```
$ ./cockroach demo -e 'select cluster_logical_timestamp()';
    cluster_logical_timestamp
+--------------------------------+
  1570325622579125000.0000000000
(1 row)
```

Just saying that this exists, not opposed to keeping this helper.
</blockquote></details>

Good point. This is also no longer a part of the workflow so I'll remove this commit when I rebase.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41266)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @bdarnell, and @tbg)

___
*[pkg/cli/debug.go, line 1235 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/41266#-LqaPHALD3hcpyVrOW8u:-LqaPHALD3hcpyVrOW8v:b-ydi78y) ([raw file](https://github.com/cockroachdb/cockroach/blob/46278066f633d2456cbcf873aed51dbe0f443784/pkg/cli/debug.go#L1235)):*
Give an example of what happens here and explain how the cluster will actually recover from this:

> For example, if we have replicas on s1-s4 but s3 and s4 are dead, we will rewrite the replica on s2 to have peers `{s1,s2}` only. When the cluster is restarted (and the dead nodes remain dead), the rewritten replica will be the only one able to make progress.

Now it's getting fuzzier for me:

> The replicaGCQueue could notice that this rewritten replica has a new replicaID, but this does not trigger any action. It won't touch the non-rewritten replicas because they haven't changed, until the replicate queue performs further actions on the range.
> The consistency checker will not fire because even though the logs diverge between the rewritten replica and the others, ___?

Also, isn't this dangerous without a quorum loss check? If a range has replicas s1s2s3s4s5 and the s5 is dead, when we unsafe-remove s5 we don't want s4 to be made a singleton range because this range hasn't even lost quorum. Take a look at `desc.Replicas().CanMakeProgress`.
___
*[pkg/cli/debug.go, line 1250 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/41266#-LqaNpa0AWY_Q1imBYsM:-LqaNpa0AWY_Q1imBYsN:b-vk1bw2) ([raw file](https://github.com/cockroachdb/cockroach/blob/46278066f633d2456cbcf873aed51dbe0f443784/pkg/cli/debug.go#L1250)):*
If you find a staging record, you're screwed because the txn status needs to check all of the potential writes. We should simply make sure that we're not writing staging records in these cases, but I think we don't already.

 Could you also mention that this tool won't be guaranteed to give consistent results? Like

> Note however that the most recent writes to the raft log may have been lost. In the most unfortunate cases, this means that we would be "winding back" a split or a merge, which is almost certainly to result in irrecoverable corruption (for example, not only will individual values stored in the meta ranges diverge, but there will be keys not represented by any ranges or vice versa).
___
*[pkg/cli/debug_test.go, line 380 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/41266#-LqaOzFp55YEik4-LtDG:-LqaOzFp55YEik4-LtDH:bm6yqus) ([raw file](https://github.com/cockroachdb/cockroach/blob/46278066f633d2456cbcf873aed51dbe0f443784/pkg/cli/debug_test.go#L380)):*
> ```Go
> 					// maxLivePeer in debug.go.
> 					//
> 					// TODO(bdarnell): It doesn't look to me like this is
> ```

The first node in the list is probably special in the sense that it has all leases/leaderships. Once you add a second node that survives, that second node has a higher storeID than the other survivor so it gets preferred over the old choice but without the perk of starting out with leases/leaderships. Maybe that's it?

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41266)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @bdarnell, and @tbg)

___
*[pkg/cli/debug.go, line 1235 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/41266#-LqaPHALD3hcpyVrOW8u:-LqaUTNZ2oQgeAdG08x0:b-n7yxwf) ([raw file](https://github.com/cockroachdb/cockroach/blob/46278066f633d2456cbcf873aed51dbe0f443784/pkg/cli/debug.go#L1235)):*
> we will rewrite the replica on s2 to have peers {s1,s2} only

No, we will rewrite the replica on s2 to be the only member of the range. Then it will be able to elect itself leader, the replicate queue will see that it only has one replica and up-replicate it to 2+ other stores. 

> Also, isn't this dangerous without a quorum loss check?

Good point. I was assuming that by the time this tool was run the only remaining replicas on a dead store would be those that prevented a quorum, but there should be an explicit check. 
___
*[pkg/cli/debug_test.go, line 380 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/41266#-LqaOzFp55YEik4-LtDG:-LqaVXDx4VHtfyD-pEnx:bx22v0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/46278066f633d2456cbcf873aed51dbe0f443784/pkg/cli/debug_test.go#L380)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

The first node in the list is probably special in the sense that it has all leases/leaderships. Once you add a second node that survives, that second node has a higher storeID than the other survivor so it gets preferred over the old choice but without the perk of starting out with leases/leaderships. Maybe that's it?
</blockquote></details>

Yeah, that makes sense.

**Review by tbg — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 3 of 3 files at r2, 4 of 4 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41266)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @bdarnell, and @tbg)

___
*[pkg/cli/debug.go, line 1235 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/41266#-LqaPHALD3hcpyVrOW8u:-Lqac6-753bOQm_xSjeR:bexp9b9) ([raw file](https://github.com/cockroachdb/cockroach/blob/46278066f633d2456cbcf873aed51dbe0f443784/pkg/cli/debug.go#L1235)):*
> No, we will rewrite the replica on s2 to be the only member of the range.

Oh, sorry, yes that's what I meant. The replicate queue will then make additional copies which blindly update the meta ranges, so at that point the old ranges become GC'able. (put that in the comment). Until they are gc'ed, we're in sort of a.. weird situation, but we expect that to resolve itself.

Please also document in `(*replicaGCQueue).process` the case in which we find a replica in the descriptor but the local copy has a higher replicaID. Just mention that this is expected after unsafe-remove-dead-replicas and should be treated as if the replica were still a member. (This is probably what happens today "by accident")

The consistency checker won't fire because it only asks the followers known to the leaseholder. The leaseholder doesn't know the "removed" replicas any more (nor does it catch them up), so it doesn't ask them. Please work that in as well.

**Comment by bdarnell** [comment]
OK, I've added some more comments and a quorum-loss check.

**Review by tbg — APPROVED** [review]
> Reviewed 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41266)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @bdarnell, and @tbg)

___
*[pkg/cli/debug.go, line 1300 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/41266#-LqTgsZ63idb0XoQlzAV:-LqbRVv-EwxqHzAnW31a:b-8dahjt) ([raw file](https://github.com/cockroachdb/cockroach/blob/c30e0a7266638812f606c3284ee7a8859d992da7/pkg/cli/debug.go#L1300)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Good point. This is also no longer a part of the workflow so I'll remove this commit when I rebase. 
</blockquote></details>

Still there
___
*[pkg/cli/debug.go, line 1196 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/41266#-LqbRJAxDJbZIXPB1Rds:-LqbRJAxDJbZIXPB1Rdt:b-aac55v) ([raw file](https://github.com/cockroachdb/cockroach/blob/3de6e92c5d63011cab9b3d24e391fb0a737f9d00/pkg/cli/debug.go#L1196)):*
> ```Go
> 			})
> 			if canMakeProgress {
> 				return false, errors.Errorf("Range %s can still make progress, aborting repair", &desc)
> ```

I thought we would skip the range, not abort the whole operation. As written, the system ranges are probably going to be available thanks to 5x replication but a partition at 3x may be permanently wedged, so now the tool won't work in that case until we kill more nodes first.

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41266)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @bdarnell, and @tbg)

___
*[pkg/cli/debug.go, line 1300 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/41266#-LqTgsZ63idb0XoQlzAV:-LqbSKTH7omr5kSDoG5a:bet1c5m) ([raw file](https://github.com/cockroachdb/cockroach/blob/c30e0a7266638812f606c3284ee7a8859d992da7/pkg/cli/debug.go#L1300)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Still there
</blockquote></details>

Yeah, haven't rebased yet. I'll do that next. 
___
*[pkg/cli/debug.go, line 1196 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/41266#-LqbRJAxDJbZIXPB1Rds:-LqbSN8jDIp_EKN9-r1n:b124du7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3de6e92c5d63011cab9b3d24e391fb0a737f9d00/pkg/cli/debug.go#L1196)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I thought we would skip the range, not abort the whole operation. As written, the system ranges are probably going to be available thanks to 5x replication but a partition at 3x may be permanently wedged, so now the tool won't work in that case until we kill more nodes first.
</blockquote></details>

If the system ranges are able to make progress, they will do so and will remove the dead replicas. I'd rather abort early in this tool to make sure we're only running in expected situations.

**Review by tbg — APPROVED** [review]
> Reviewed 7 of 7 files at r9, 3 of 3 files at r10, 5 of 5 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41266)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @bdarnell, and @tbg)

___
*[pkg/cli/debug.go, line 1196 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/41266#-LqbRJAxDJbZIXPB1Rds:-LqbV1df8g2brppHz6F1:b2ao4ug) ([raw file](https://github.com/cockroachdb/cockroach/blob/3de6e92c5d63011cab9b3d24e391fb0a737f9d00/pkg/cli/debug.go#L1196)):*
Makes sense, please change the error to something like

> range %s has dead peers but has not lost quorum; run the cluster in current state until these replicas are removed and then retry the operation
___
*[pkg/cli/debug.go, line 1097 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/41266#-LqbVCE161rZH8iCqP0O:-LqbVCE161rZH8iCqP0P:b-94r54f) ([raw file](https://github.com/cockroachdb/cockroach/blob/1291db37157521d473df372b714498ed12e11f16/pkg/cli/debug.go#L1097)):*
> ```Go
> This comand will prompt for confirmation before committing its changes.
> 
> Limitations: Can only recover from a single replica. If a range with
> ```

Needs update

**Comment by bdarnell** [comment]
bors r=tbg

**Comment by bdarnell** [comment]
bors r=tbg

The release-justification linter apparently wants to see it in the PR description, not just the commits.

**Pull request merged**
