### PR TITLE
system,tablemetadatacache: add table_type col to table_metadata table

### PR DESCRIPTION
**Pull request by kyle-a-wong**
The new table metadata update job includes views, materialized views, an sequence tables (in addition to regular tables) when writing rows to the `system.table_metadata` table. While it is expected that these are included, the new APIs that retrieve this data may only care about regular tables.

As a result, a new column `table_type` has been added to `system.table_metadata` to differentiate between the types.

The following additional changes have been made to the API layer:
 - The `GET /table_metadata/` API has been altered to only include rows where `table_type = 'TABLE'`,
 - The `GET /database_metadata` API has been altered to only include rows where `table_type = 'TABLE'` for the table_count value. The size_bytes value remains the same (includes all table types)

Epic: CRDB-37558
Release note: None

### CODE REVIEW

**Comment by angles-n-daemons** [comment]
Could the information schema be used for this?

```sql
select * from information_schema.tables where table_type == 'BASE TABLE'
```

**Comment by kyle-a-wong** [comment]
> Could the information schema be used for this?
> 
> ```sql
> select * from information_schema.tables where table_type == 'BASE TABLE'
> ```
`information_schema.tables` would work if we only cared if it was a base table or not. The main issue is that for views, the table_type  `VIEW` whether its materialized or not so we would have to use something else to determine this. Also this table doesn't include sequence tables.

Since we have the information when updating table_metadata, we decided to just go with the approach of storing this data to make retrieval more simple.

**Review by xinhaoz — APPROVED** [review]
Changes look good - I have a question that I'll say is non-blocking since we can add it later if required. Maybe the table type should be a param on the API for more flexibility. I don't think there's any drawback in excluding it for now though since we don't have any views showing other table types so :lgtm:.

**Comment by kyle-a-wong** [comment]
TFTR 

bors r+

**Pull request merged**
