### PR TITLE
cli,democluster: defer simulated latency until after cluster setup

### LINKED ISSUE #76305: multitenant: demo startup performance is poor with multiple tenants and simulated latencies
`cockroach demo --global --nodes 9 --empty` takes several minutes to startup.  When multi-tenancy is disabled, it takes only a few seconds.  It's not clear what's causing this poor performance, but a quick peek into the logs shows that each tenant takes between 20 and 60 seconds to start.  

```
I220209 13:16:17.066637 1 cli/democluster/demo_cluster.go:389 ⋮ [start-demo-cluster,phase=8] 2880  starting tenant nodes
I220209 13:16:17.066657 1 cli/democluster/demo_cluster.go:394 ⋮ [start-demo-cluster,phase=8] 2881  starting tenant node 0
I220209 13:16:38.293483 1 cli/democluster/demo_cluster.go:394 ⋮ [start-demo-cluster,phase=8,nsql1] 6010  starting tenant node 1
I220209 13:16:57.371877 1 cli/democluster/demo_cluster.go:394 ⋮ [start-demo-cluster,phase=8,nsql1] 8435  starting tenant node 2
I220209 13:17:15.858256 1 cli/democluster/demo_cluster.go:394 ⋮ [start-demo-cluster,phase=8,nsql1] 10585  starting tenant node 3
I220209 13:18:01.189788 1 cli/democluster/demo_cluster.go:394 ⋮ [start-demo-cluster,phase=8,nsql1] 13284  starting tenant node 4
I220209 13:18:52.356343 1 cli/democluster/demo_cluster.go:394 ⋮ [start-demo-cluster,phase=8,nsql1] 15015  starting tenant node 5
I220209 13:19:31.760119 1 cli/democluster/demo_cluster.go:394 ⋮ [start-demo-cluster,phase=8,nsql1] 17341  starting tenant node 6
I220209 13:20:20.155604 1 cli/democluster/demo_cluster.go:394 ⋮ [start-demo-cluster,phase=8,nsql1] 20181  starting tenant node 7
I220209 13:21:19.373402 1 cli/democluster/demo_cluster.go:394 ⋮ [start-demo-cluster,phase=8,nsql1] 23542  starting tenant node 8
```

More investigation is required.

Epic: CRDB-18596

Jira issue: CRDB-13070

### PR DESCRIPTION
**Pull request by ajwerner**
### democluster,serverutils/regionlatency,rpc: extract code for simulating latency

We'll want to leverage these helpers in some tests to measure behavior under
simulated latency.

### cli,democluster: defer simulated latency until after cluster setup

Cluster creation and tenant setup is chatty. That's an okay thing: we don't
really care about cluster creation being that slow in general. In the case of
demo when we want to simulate latency and use tenants, it was particularly
painful. Starting the 9 tenants would take many minutes. This patch alleviates
this problem by keeping latency between the simulated nodes low until just
before we pass control to the user.

Fixes https://github.com/cockroachdb/cockroach/issues/76305

Release note (cli change): `cockroach demo --global` will now start up more
quickly. The latency which will be injected is not injected until after the
initial cluster is set up internally.

### CODE REVIEW

**Review by knz — APPROVED** [review]
LGTM but please also seek review from @rafiss

**Review by rafiss — APPROVED** [review]
this is great to have, lgtm!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92231#-:-NHUyTwkCzlf8IgRUGR7:b-rhxqeg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[`pkg/testutils/serverutils/regionlatency/region_latencies.go` line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92231#-NHUxVEG6DvPqfJWdTza:-NHUxVEG6DvPqfJWdTzb:b-y68uvf) ([raw file](https://github.com/cockroachdb/cockroach/blob/034fa2ed866791958850eaef533ae4087c80c502/pkg/testutils/serverutils/regionlatency/region_latencies.go#L117)):*
> ```Go
> 
> // RoundTripPairs are pairs of round-trip latency between regions.
> type RoundTripPairs map[Pair]time.Duration
> ```

nit: should the value-type be `RoundTripLatency`?

**Review by ajwerner — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92231#-:-NHVsT0_-_QUIFlMCsYz:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/testutils/serverutils/regionlatency/region_latencies.go` line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92231#-NHUxVEG6DvPqfJWdTza:-NHVsRxTCgccrQOfCFNZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/034fa2ed866791958850eaef533ae4087c80c502/pkg/testutils/serverutils/regionlatency/region_latencies.go#L117)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: should the value-type be `RoundTripLatency`?
</blockquote></details>

Done.

**Comment by ajstorm** [comment]
Nice.  Thanks for getting to this @ajwerner!

**Pull request merged**
