### PR TITLE
Return ZoneConfig from Admin API TableDetails

### PR DESCRIPTION
**Pull request by mrtracy**
Returns ZoneConfiguration info when querying TableDetails from the Admin API.
The returned ZoneConfig is the most specific config applicable to the table,
which may be specified at the table level, database level, or cluster level. The
TableDetailsResponse message also includes a new enumeration field indicating
the "level" at which the ZoneConfig is applied to the table.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7436)

### CODE REVIEW

**Comment by tamird** [comment]
Looks like you forgot to regenerate embedded.go. Not your fault, you need https://github.com/cockroachdb/cockroach/pull/7435.

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[server/admin.go, line 1080 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7436#-KKythd9UKl4BH65DUmV:-KKythd9UKl4BH65DUmW:55585079) ([raw file](https://github.com/cockroachdb/cockroach/blob/36f2a709219a92004fbbdba728e5e794117155ac/server/admin.go#L1080)):*
> ```Go
> // with this system.
> 
> // queryZone retrieves the specifics ZoneConfig associated with the supplied ID, if it exists.
> ```

specific

---

*[server/admin.go, line 1082 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7436#-KKytkdBT3dcR6HWiTzU:-KKytkdBT3dcR6HWiTzV:959091626) ([raw file](https://github.com/cockroachdb/cockroach/blob/36f2a709219a92004fbbdba728e5e794117155ac/server/admin.go#L1082)):*
> ```Go
> // queryZone retrieves the specifics ZoneConfig associated with the supplied ID, if it exists.
> func (s *adminServer) queryZone(ctx context.Context, session *sql.Session, id sqlbase.ID) (
> 	*config.ZoneConfig, error) {
> ```

this doesn't follow the style guide

---

*[server/admin.go, line 1082 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7436#-KKyu3SK4qxi7aw-4GH5:-KKyu3SK4qxi7aw-4GH6:1602629121) ([raw file](https://github.com/cockroachdb/cockroach/blob/36f2a709219a92004fbbdba728e5e794117155ac/server/admin.go#L1082)):*
> ```Go
> // queryZone retrieves the specifics ZoneConfig associated with the supplied ID, if it exists.
> func (s *adminServer) queryZone(ctx context.Context, session *sql.Session, id sqlbase.ID) (
> 	*config.ZoneConfig, error) {
> ```

can this return a value? doesn't seem like the pointer helps here

---

*[server/admin.go, line 1138 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7436#-KKyuQIbyIkZgV6PtQg3:-KKyuQIcZXbdNPsw2t1t:564052829) ([raw file](https://github.com/cockroachdb/cockroach/blob/36f2a709219a92004fbbdba728e5e794117155ac/server/admin.go#L1138)):*
> ```Go
> 	result := r.ResultList[0]
> 	if len(result.Rows) == 0 {
> 		return 0, fmt.Errorf("namespace %s with ParentID %d not found", name, parentID)
> ```

is this a user-facing error? consider errors.Errorf instead.

---

*[server/admin.go, line 1155 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7436#-KKytrVP_kFGVlTNZGAG:-KKytrVP_kFGVlTNZGAH:-469765787) ([raw file](https://github.com/cockroachdb/cockroach/blob/36f2a709219a92004fbbdba728e5e794117155ac/server/admin.go#L1155)):*
> ```Go
> // of the root namespace ID, the databases ID, and the table ID (in that order).
> func (s *adminServer) queryDescriptorIDPath(ctx context.Context, session *sql.Session, names []string) (
> 	[]sqlbase.ID, error) {
> ```

ditto

---

*[server/serverpb/admin.proto, line 31 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7436#-KKytFRss-0aQ797-fIs:-KKytFRss-0aQ797-fIt:557416622) ([raw file](https://github.com/cockroachdb/cockroach/blob/36f2a709219a92004fbbdba728e5e794117155ac/server/serverpb/admin.proto#L31)):*
> ```protobuf
> enum ZoneConfigurationLevel {
>   // CLUSTER indicates that this object uses the cluster default Zone Configuration.
>   CLUSTER = 0;
> ```

usually not a great idea to use 0 as a real value. can you make this `UNKNOWN = 0;`?

---

*[server/serverpb/admin.proto, line 142 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7436#-KKyuk5Mq3KkW5wAjpe1:-KKyuk5Mq3KkW5wAjpe2:743027786) ([raw file](https://github.com/cockroachdb/cockroach/blob/36f2a709219a92004fbbdba728e5e794117155ac/server/serverpb/admin.proto#L142)):*
> ```protobuf
>   cockroach.config.ZoneConfig zone_config = 6;
>   // The level at which this object's zone configuration is set.
>   ZoneConfigurationLevel zone_config_level = 7;
> ```

these should both be non-nullable

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7436#-:-KKytUBlLMZApHN6ZaI0:253055161)*

**Comment by mrtracy** [comment]
Review status: 0 of 8 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[server/admin.go, line 1080 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7436#-KKythd9UKl4BH65DUmV:-KL2v9_w4-mbKOZPm9WO:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/36f2a709219a92004fbbdba728e5e794117155ac/server/admin.go#L1080)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> specific
</details>
Done.

---

*[server/admin.go, line 1082 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7436#-KKytkdBT3dcR6HWiTzU:-KL2v9tSAuEDMhp35I0y:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/36f2a709219a92004fbbdba728e5e794117155ac/server/admin.go#L1082)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this doesn't follow the style guide
</details>
Done.

---

*[server/admin.go, line 1082 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7436#-KKyu3SK4qxi7aw-4GH5:-KL2vtEoR-Gi8VbPCpRK:-772096427) ([raw file](https://github.com/cockroachdb/cockroach/blob/36f2a709219a92004fbbdba728e5e794117155ac/server/admin.go#L1082)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can this return a value? doesn't seem like the pointer helps here
</details>
It had to be a pointer anyway because the proto field was nullable; however, now that it's non-nullable, i've converted these all to values.

---

*[server/admin.go, line 1138 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7436#-KKyuQIbyIkZgV6PtQg3:-KL305V2VkooDdiAf4OJ:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/36f2a709219a92004fbbdba728e5e794117155ac/server/admin.go#L1138)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> is this a user-facing error? consider errors.Errorf instead.
</details>
Done.

---

*[server/admin.go, line 1155 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7436#-KKytrVP_kFGVlTNZGAG:-KL305GsARxbTAeC-ugS:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/36f2a709219a92004fbbdba728e5e794117155ac/server/admin.go#L1155)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> ditto
</details>
Done.

---

*[server/serverpb/admin.proto, line 31 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7436#-KKytFRss-0aQ797-fIs:-KL2zdXiqnV1ClwnC-aH:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/36f2a709219a92004fbbdba728e5e794117155ac/server/serverpb/admin.proto#L31)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> usually not a great idea to use 0 as a real value. can you make this `UNKNOWN = 0;`?
</details>
Done.

---

*[server/serverpb/admin.proto, line 142 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7436#-KKyuk5Mq3KkW5wAjpe1:-KL2yAsvm43RErnuUvbE:-1397189846) ([raw file](https://github.com/cockroachdb/cockroach/blob/36f2a709219a92004fbbdba728e5e794117155ac/server/serverpb/admin.proto#L142)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> these should both be non-nullable
</details>
ZoneConfigurationLevel is an enum, it's already non-nullable. Fixed the other.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7436)*

**Comment by tamird** [comment]
Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/admin.go, line 1072 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7436#-KL3OknHHYdfZlpQN2zm:-KL3OknIGi4uWEZrLRTB:-459432233) ([raw file](https://github.com/cockroachdb/cockroach/blob/36f2a709219a92004fbbdba728e5e794117155ac/server/admin.go#L1072)):*
> ```Go
> 
> // TODO(mrtracy): The following methods, used to look up the zone configuration for a
> // database or table, use the same algorithm as a set of methods in cli/zone.go for the same purpose.
> ```

oops?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7436)*

**Comment by mrtracy** [comment]
Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[server/admin.go, line 1072 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7436#-KL3OknHHYdfZlpQN2zm:-KLIMcb9IloGclrBZcl8:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/36f2a709219a92004fbbdba728e5e794117155ac/server/admin.go#L1072)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> oops?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7436)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7436)*

**Comment by mrtracy** [comment]
@cuongdo @petermattis May I pester one of you for a quick review of this?  Would be best to have a look from someone familiar with the code.

**Comment by cuongdo** [comment]
looks fine from an admin API point of view, but I can't comment on the zone config code

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7436#-:-KLIiai7kWWdidB2doIC:-2023442172)*

**Pull request merged**
