### PR TITLE
sql/parser: Permit nil builtin function impls if only return type is needed

### PR DESCRIPTION
**Pull request by nvb**
[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3793)

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
@tamird Let me know what you think.

**Comment by tamird** [comment]
LGTM

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/parser/builtins.go, line 639 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3793#-K7rtLEjOrq0ae8BKuAu:-K7rtLEjOrq0ae8BKuAv:358664263) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea2e7f1c70ff7070adc5cb93a5cf501aa8797ea9/sql/parser/builtins.go#L639)):*
I think you can also gut this guy (not on this line, but you know what I mean).

---

*[sql/parser/expr.go, line 637 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3793#-K7rtlMiSNWpJLn77Tvz:-K7rtlMjuFMcmEdBEnBo:1267416009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea2e7f1c70ff7070adc5cb93a5cf501aa8797ea9/sql/parser/expr.go#L637)):*
Comments should be complete sentences, whenever possible.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3793#-:-K7rtqahdC-hdwqG6JsN:676834233)*

**Comment by nvanbenschoten** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/parser/builtins.go, line 639 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3793#-K7rtLEjOrq0ae8BKuAu:-K7ruTAN6jqbcMMhP5b2:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea2e7f1c70ff7070adc5cb93a5cf501aa8797ea9/sql/parser/builtins.go#L639)):*
Done.

---

*[sql/parser/expr.go, line 637 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3793#-K7rtlMiSNWpJLn77Tvz:-K7ruibjcwusYCW-3wtc:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea2e7f1c70ff7070adc5cb93a5cf501aa8797ea9/sql/parser/expr.go#L637)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3793)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3793)*

**Pull request merged**
