### PR TITLE
store pool cleanups

### PR DESCRIPTION
**Pull request by andrewbaptist**
Clean up some usages of liveness within the store pool. This doesn't remove all the functionality in store pool, but reduces the uses of soon-to-be deprecated methods.

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 3 of 3 files at r2, 5 of 5 files at r3, 4 of 4 files at r4, 1 of 1 files at r5, 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104746)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist)

___
*[`-- commits` line 28 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104746#-NYIwWbKElhBHzvi6pxc):*
If the purpose of this refactoring was to centralize liveness/vitality-related logic in one place, doesn't this run counter to that since we're now spreading this logic to 4 places?
___
*[`pkg/kv/kvserver/liveness/livenesspb/liveness.go` line 207 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104746#-NYIojAN8Esa57br8Qtm:-NYIojAN8Esa57br8Qtn:b-afvhrf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eb68bb08e2db4ba33e1258b40d45089a01f3595/pkg/kv/kvserver/liveness/livenesspb/liveness.go#L207)):*
> ```Go
> type NodeVitalityMap map[roachpb.NodeID]NodeVitality
> 
> type VitalityUsage int
> ```

It seems backwards to frame this in terms of who the caller is, rather than the semantics of the check. If we have e.g. 10 callers that all want the "standard" `isAlive()` check, then we'd have to add 10 cases here that all do the same thing, which doesn't seem useful.

Considering there are only 3 cases, we could simply expose them as methods, e.g. `IsAlive()`, `IsAliveAndConnected()`, and `IsAliveForEpochLease()` or something. Hopefully we'd be able to cut this down to one or two cases.

The `Admin` case isn't used btw.
___
*[`pkg/kv/kvserver/liveness/livenesspb/liveness.go` line 283 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104746#-NYIq_hd7SYbU7HUl0rE:-NYIq_hd7SYbU7HUl0rF:bvhqy0y) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eb68bb08e2db4ba33e1258b40d45089a01f3595/pkg/kv/kvserver/liveness/livenesspb/liveness.go#L283)):*
> ```Go
> 	}
> 
> 	// If we have a 0 epoch, the expiration time won't be written, so we assume
> ```

Is this the case where there is no liveness record? Does this only happen when bootstrapping a new node? Is there a compelling reason not to wait for it to bootstrap?
___
*[`pkg/kv/kvserver/liveness/livenesspb/liveness.go` line 324 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104746#-NYIsbqb0yegjI1Qb7Zl:-NYIsbqb0yegjI1Qb7Zm:b-j6nufa) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eb68bb08e2db4ba33e1258b40d45089a01f3595/pkg/kv/kvserver/liveness/livenesspb/liveness.go#L324)):*
> ```Go
> // TODO(baptist): If we are not updating the expiration use the store descriptor
> // time.
> func (nv NodeVitality) GenLiveness() Liveness {
> ```

We presumably want to get away from relying on the liveness record, given that we duplicate it in `NodeVitality`, so let's add a TODO to move the admin server to use a separate response type and remove this method.
___
*[`pkg/kv/kvserver/liveness/livenesspb/liveness.go` line 493 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104746#-NYItIkEBkrOxYvY-527:-NYItIkEBkrOxYvY-528:bvblgjs) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eb68bb08e2db4ba33e1258b40d45089a01f3595/pkg/kv/kvserver/liveness/livenesspb/liveness.go#L493)):*
> ```Go
> // the new interface for tests that previously used IsLiveMap. It doesn't
> // directly look at timestamps, so the status must be manually updated.
> type TestNodeVitalityEntry struct {
> ```

Can we move these types out to a separate `_test.go` file/package?
___
*[`pkg/server/admin.go` line 2215 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104746#-NYIuSP53MpsNWD7tNdd:-NYIuSP6DE6biD1tpaxQ:b-5dm2ky) ([raw file](https://github.com/cockroachdb/cockroach/blob/0514a3dac06896bf9f42517f24d15f52b7d6bf3c/pkg/server/admin.go#L2215)):*
> ```Go
> 	ctx context.Context, nl *liveness.NodeLiveness, now hlc.Timestamp, st *cluster.Settings,
> ) (map[roachpb.NodeID]livenesspb.NodeLivenessStatus, error) {
> 	nodeStatusMap, err := nl.ScanNodeVitalityFromKV(ctx)
> ```

nit: `nodeVitalityMap`
___
*[`pkg/server/admin.go` line 2241 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104746#-NYIvFdU4UUkwE67x49P:-NYIvFdU4UUkwE67x49Q:b-f4xont) ([raw file](https://github.com/cockroachdb/cockroach/blob/0514a3dac06896bf9f42517f24d15f52b7d6bf3c/pkg/server/admin.go#L2241)):*
> ```Go
> 	statusMap := make(map[roachpb.NodeID]livenesspb.NodeLivenessStatus, len(nodeStatusMap))
> 
> 	for nodeID, status := range nodeStatusMap {
> ```

This returns them in a random order, which may be inconvenient/unexpected for API clients and users. Should we sort this to keep it stable, which is presumably the API behavior in 23.1?

**Review by andrewbaptist — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104746)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

___
*[`-- commits` line 28 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104746#-NYIwWbKElhBHzvi6pxc):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

If the purpose of this refactoring was to centralize liveness/vitality-related logic in one place, doesn't this run counter to that since we're now spreading this logic to 4 places?
</blockquote></details>

This method is really a strange method anyway that I want to get rid off in a few more commits. We are centralizing all the logic, but this is a method to compute a "derived stat" on the data and is only used in tests today.
___
*[`pkg/kv/kvserver/liveness/livenesspb/liveness.go` line 207 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104746#-NYIojAN8Esa57br8Qtm:-NYT8cic6wNim3ioXNMd:b-4dvtgf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eb68bb08e2db4ba33e1258b40d45089a01f3595/pkg/kv/kvserver/liveness/livenesspb/liveness.go#L207)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

It seems backwards to frame this in terms of who the caller is, rather than the semantics of the check. If we have e.g. 10 callers that all want the "standard" `isAlive()` check, then we'd have to add 10 cases here that all do the same thing, which doesn't seem useful.

Considering there are only 3 cases, we could simply expose them as methods, e.g. `IsAlive()`, `IsAliveAndConnected()`, and `IsAliveForEpochLease()` or something. Hopefully we'd be able to cut this down to one or two cases.

The `Admin` case isn't used btw.
</blockquote></details>

I was going back and forth on this. The advantage of having this all centralized is that it allows easily seeing who is using which methods and also the variations that they currently use. There will be ~15 uses and ~10 different ways they do it before changes are made. By centralizing this it prevents more growth and allows simplification even though more of the cases are similar today. I pulled in a commit that moves all the uses here.
___
*[`pkg/kv/kvserver/liveness/livenesspb/liveness.go` line 283 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104746#-NYIq_hd7SYbU7HUl0rE:-NYT901o8t-ycJy_JfW_:b-p0q575) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eb68bb08e2db4ba33e1258b40d45089a01f3595/pkg/kv/kvserver/liveness/livenesspb/liveness.go#L283)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Is this the case where there is no liveness record? Does this only happen when bootstrapping a new node? Is there a compelling reason not to wait for it to bootstrap?
</blockquote></details>

It is when bootstrapping, but many of the tests don't wait and I was hesitant to change the bootstrapping logic. I'm hoping this can be simplified in the future but I wanted to keep the backwards compatibility.
___
*[`pkg/kv/kvserver/liveness/livenesspb/liveness.go` line 324 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104746#-NYIsbqb0yegjI1Qb7Zl:-NYT9AD723DvmOuoHe2R:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eb68bb08e2db4ba33e1258b40d45089a01f3595/pkg/kv/kvserver/liveness/livenesspb/liveness.go#L324)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

We presumably want to get away from relying on the liveness record, given that we duplicate it in `NodeVitality`, so let's add a TODO to move the admin server to use a separate response type and remove this method.
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/liveness/livenesspb/liveness.go` line 493 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104746#-NYItIkEBkrOxYvY-527:-NYT9qm34OXa3xqWCzfJ:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eb68bb08e2db4ba33e1258b40d45089a01f3595/pkg/kv/kvserver/liveness/livenesspb/liveness.go#L493)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Can we move these types out to a separate `_test.go` file/package?
</blockquote></details>

Done
___
*[`pkg/server/admin.go` line 2215 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104746#-NYIuSP53MpsNWD7tNdd:-NYTFekt2cXAAX8Wvmc5:b-vk78s9) ([raw file](https://github.com/cockroachdb/cockroach/blob/0514a3dac06896bf9f42517f24d15f52b7d6bf3c/pkg/server/admin.go#L2215)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

nit: `nodeVitalityMap`
</blockquote></details>

Thanks! changed.
___
*[`pkg/server/admin.go` line 2241 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104746#-NYIvFdU4UUkwE67x49P:-NYTENw19RT3a4iX8Pm9:bdoyo9a) ([raw file](https://github.com/cockroachdb/cockroach/blob/0514a3dac06896bf9f42517f24d15f52b7d6bf3c/pkg/server/admin.go#L2241)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

This returns them in a random order, which may be inconvenient/unexpected for API clients and users. Should we sort this to keep it stable, which is presumably the API behavior in 23.1?
</blockquote></details>

Good catch! Added a sort to this.

**Comment by andrewbaptist** [comment]
@erikgrinaker let me know if you want to take one more pass at this. Otherwise I'll merge this tomorrow. The remaining PRs to move everything over to the new interface are on this PR https://github.com/cockroachdb/cockroach/pull/105091. I might split that out into two as there are still a few tests that are failing on it.

**Review by erikgrinaker — COMMENTED** [review]
Go for it.

> Reviewed 24 of 24 files at r7, 3 of 3 files at r8, 4 of 4 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104746#-:-NYXXvn8178UTvzWzO3f:b-x2mi87)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist)

___
*[`-- commits` line 28 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104746#-NYIwWbKElhBHzvi6pxc):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

This method is really a strange method anyway that I want to get rid off in a few more commits. We are centralizing all the logic, but this is a method to compute a "derived stat" on the data and is only used in tests today.
</blockquote></details>

Ah, I see, if it's test only then I don't care what we do with it. Would be good to split it out to a `_test.go` file or package to make that clear, and avoid polluting the main struct/interface.
___
*[`pkg/kv/kvserver/liveness/livenesspb/liveness.go` line 207 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104746#-NYIojAN8Esa57br8Qtm:-NYXWRUj7afiKL6OdlN3:b7q7x9y) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eb68bb08e2db4ba33e1258b40d45089a01f3595/pkg/kv/kvserver/liveness/livenesspb/liveness.go#L207)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

I was going back and forth on this. The advantage of having this all centralized is that it allows easily seeing who is using which methods and also the variations that they currently use. There will be ~15 uses and ~10 different ways they do it before changes are made. By centralizing this it prevents more growth and allows simplification even though more of the cases are similar today. I pulled in a commit that moves all the uses here.
</blockquote></details>

Ok. I still think this is misguided though, hopefully we can get rid of it before long.
___
*[`pkg/kv/kvserver/liveness/livenesspb/liveness.go` line 353 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/104746#-NYXX0HD-Kca-ddWpQl_:-NYXX0HD-Kca-ddWpQla:bsu4qfz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b64ce6e3447e83d751eba3a61aa824f68968c4e4/pkg/kv/kvserver/liveness/livenesspb/liveness.go#L353)):*
> ```Go
> // 2) Epoch leases
> // Avoid using this method as the Liveness expiration is not always populated.
> func (nv NodeVitality) GetInternalLiveness() Liveness {
> ```

This now does exactly the same as `GenLiveness()`, let's merge them. Also, `GetInternalLiveness()` seems inaccurate and confusing, there is no internal liveness that we're fetching here.
___
*[`pkg/kv/kvserver/liveness/livenesspb/liveness.go` line 429 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/104746#-NYXXH_1AtD2v_2LxaVz:-NYXXH_1AtD2v_2LxaW-:b-fmkm56) ([raw file](https://github.com/cockroachdb/cockroach/blob/b64ce6e3447e83d751eba3a61aa824f68968c4e4/pkg/kv/kvserver/liveness/livenesspb/liveness.go#L429)):*
> ```Go
> 	// If it expired longer than timeUntiLNodeDead ago, then treat as DEAD,
> 	// otherwise it is UNAVAILABLE. If livenessEpoch is 0, we don't want to assume
> 	// its dead since it hasn't had a chance to update its expiration yet.
> ```

What if it never does? Shouldn't we consider it dead in that case?

**Comment by andrewbaptist** [comment]
bors r=erikgrinaker

**Comment by andrewbaptist** [comment]
bors retry

**Comment by andrewbaptist** [comment]
bors retry

**Comment by andrewbaptist** [comment]
bors retry

**Pull request merged**
