### PR TITLE
storage: code movement

### PR DESCRIPTION
**Pull request by tamird**
Moves some protos that should never have been in roachpb out into storage.

This change requires a stop-the-world upgrade because of RPC method renaming but we already have such a change on deck #8495.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8542)

### CODE REVIEW

**Comment by BramGruneir** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 19 of 19 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/api.proto, line 17 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8542#-KPDgaR-wpxQNdQVAkdZ:-KPDgaR-wpxQNdQVAkd_:brtwtqa) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc9a6eba6677a2d0212048d72ecfb89a53bccca9/storage/api.proto#L17)):*
> ```protobuf
> // Author: Tobias Schottdorf (tobias@cockroachlabs.com)
> 
> syntax = "proto2";
> ```

What's the status on the proto3 vs proto2?  Maybe make this a proto3?

---

*[storage/store.go, line 2299 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8542#-KPDg-SkvZ7cZvfTnN-U:-KPDg-Sl6xB-n2OF9_Qd:bmd3kt2) ([raw file](https://github.com/cockroachdb/cockroach/blob/78f64180c616927d7674eb166f0ccb9012b71ebf/storage/store.go#L2299)):*
> ```Go
> 		switch val.GetDetail().(type) {
> 		case *roachpb.ReplicaTooOldError:
> 			if err := s.stopper.RunTask(func() {
> ```

Any idea why this was in a runtask to begin with?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8542#-:-KPDhDMg1gEoAAnPCigK:bnfp4nl)*

**Comment by BramGruneir** [comment]
This makes the code a lot more readable.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8542#-:-KPDhIWcdekXq_ONlyYa:bumzp7x)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[storage/api.proto, line 17 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8542#-KPDgaR-wpxQNdQVAkdZ:-KPDhyRys-jE3IQnPV1u:b-ix523c) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc9a6eba6677a2d0212048d72ecfb89a53bccca9/storage/api.proto#L17)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary>
> What's the status on the proto3 vs proto2?  Maybe make this a proto3?
</details>
It had to be proto2 because of the nullability of ReservationResponse.range_count, but that changed in the final commit here. Done.

---

*[storage/store.go, line 2299 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8542#-KPDg-SkvZ7cZvfTnN-U:-KPDhlQAXd47hMlN-VWp:b-nroys3) ([raw file](https://github.com/cockroachdb/cockroach/blob/78f64180c616927d7674eb166f0ccb9012b71ebf/storage/store.go#L2299)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary>
> Any idea why this was in a runtask to begin with?
</details>
None. @petermattis added it in https://github.com/cockroachdb/cockroach/pull/8172, perhaps he can comment? I couldn't see any reason for it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8542)*

**Comment by BramGruneir** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8542)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/store.go, line 2299 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8542#-KPDg-SkvZ7cZvfTnN-U:-KPEkBtDELhuYil93_CL:b8x43rv) ([raw file](https://github.com/cockroachdb/cockroach/blob/78f64180c616927d7674eb166f0ccb9012b71ebf/storage/store.go#L2299)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> None. @petermattis added it in https://github.com/cockroachdb/cockroach/pull/8172, perhaps he can comment? I couldn't see any reason for it.
</details>
Please don't make functional changes in PRs titled "code movement", especially without waiting for a response from the person called out as most knowledgeable about the code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8542)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/store.go, line 2299 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8542#-KPDg-SkvZ7cZvfTnN-U:-KPElzlwUq82RP87E9Vt:b-bbs43e) ([raw file](https://github.com/cockroachdb/cockroach/blob/78f64180c616927d7674eb166f0ccb9012b71ebf/storage/store.go#L2299)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Please don't make functional changes in PRs titled "code movement", especially without waiting for a response from the person called out as most knowledgeable about the code.
</details>
I believe the intention was to avoid calling `replicaGCQueue.Add` when the stopper had been stopped. Seems related to #8551.

PS Please wait before merging something like this if you want someone's opinion. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8542)*

**Pull request merged**
