### PR TITLE
backupccl: don't delete restored schemas if they have new child objects

### PR DESCRIPTION
**Pull request by thoszhang**
For databases and schemas being restored, it's unlikely but possible
that new child objects can be separately added to them between when the
descriptors are made public and when the job completes. (This was more
of a concern before descriptors were kept offline while data was being
restored, but it's still possible.) If the job has to be rolled back
after the descriptors have already been made public, we need to avoid
deleting the databases and schemas with new child objects. We do this
already for databases; this PR update schemas to have the same behavior,
and adds tests for the database case.

Touches #54403.

Release note (bug fix): Fixed a bug where adding child tables or types
to a schema being restored would cause those new child objects to become
corrupted with no parent schema if the restore job had to be rolled
back.

### CODE REVIEW

**Comment by lucy-zhang** [comment]
I'm still struggling to understand something weird going on with the tests, where inserting or not inserting extra `USE <databasename>` statements that I think should be idempotent cause subsequent statements to fail because the current database session variable gets set to a database that was dropped earlier. I'll post a diff describing what I mean and solicit more input later, but my best guess is that this has something to do with how the sql driver is handling sessions/connections. Also, the success/failure behavior appears deterministic and not a matter of racy cache invalidation or something.

Anyway, I do think the change itself is sound. I'm aiming for 20.2.1 so no real rush in reviewing it.

**Review by ajwerner — APPROVED** [review]
:lgtm: though I'd like to see that caching TODO handled as it seems easy. 

> my best guess is that this has something to do with how the sql driver is handling sessions/connections. 

This has bitten me before. `SET` only applies to an individual connection. If you need to be assured that you're getting the same connection, call `Conn()` on the `*gosql.DB`. Otherwise, you're going to get any connection. In general if you make sure to not leave any queries open, it should always be the same connection but that's fragile. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55157#-:-MIdyDVz-TOT5_QWSLDd:b-yh5lcn)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @lucy-zhang, and @pbardea)

___
*[pkg/ccl/backupccl/restore_job.go, line 808 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55157#-MIdxNT_AqQEag-im5zH:-MIdxNT_AqQEag-im5zI:b2nm6z5) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d3f1d403df1b1ccdd9f18139de9621e6cff2fb2/pkg/ccl/backupccl/restore_job.go#L808)):*
> ```
> // TODO (lucy): We should refactor the usages of this and isDatabaseEmpty to
> // avoid the repeated lookups of all descriptors.
> ```
This should be trivially easy to do. The descs.Collection caches the value of `GetAllDescriptors`. We have one of those in scope when we call this and `isDatabaseEmpty`. Can we just pass that to these two calls and replace the `catalogkv` call with the `descs.Collection.GetAllDescriptors`?

**Review by thoszhang — COMMENTED** [review]
Oh, I see, I think I originally didn't really realize that `TestCluster.Conns` is a slice of `*gosql.DB`s and not of `*gosql.Conn`s and was confused about what was going on. What you're describing seems to be working with the setup where I was previously getting errors, so I think we're good.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55157#-:-MIeESiUBOmIJr7gIJHq:b-54201r)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @pbardea)

___
*[pkg/ccl/backupccl/restore_job.go, line 808 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55157#-MIdxNT_AqQEag-im5zH:-MIeFA65BLqxb1HX6x69:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d3f1d403df1b1ccdd9f18139de9621e6cff2fb2/pkg/ccl/backupccl/restore_job.go#L808)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> // TODO (lucy): We should refactor the usages of this and isDatabaseEmpty to
> // avoid the repeated lookups of all descriptors.
> ```
This should be trivially easy to do. The descs.Collection caches the value of `GetAllDescriptors`. We have one of those in scope when we call this and `isDatabaseEmpty`. Can we just pass that to these two calls and replace the `catalogkv` call with the `descs.Collection.GetAllDescriptors`?
</blockquote></details>

Done.

**Review by ajwerner — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55157)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @lucy-zhang, and @pbardea)

___
*[pkg/ccl/backupccl/backup_test.go, line 6632 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55157#-MIemeB7DcclNb2HoxEM:-MIemeB7DcclNb2HoxEN:b-blcsdp) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e76a787dcc5c9694711cd7274a141fc02ad2dfe/pkg/ccl/backupccl/backup_test.go#L6632)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> 		// Use the same connection throughout (except for the concurrent RESTORE) to
> 		// preserve session variables.
> 		conn, err := tc.Conns[0].Conn(ctx)
> 		require.NoError(t, err)
> 		sqlDB := sqlutils.MakeSQLRunner(conn)
> ```
</details>

nit: you could still call `Conn(ctx)` on `sqlDB`. No need to get rid of that. 
___
*[pkg/ccl/backupccl/restore_job.go, line 792 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55157#-MIemNWsAzgTdLCfADBW:-MIemNWsAzgTdLCfADBX:b-dymk5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e76a787dcc5c9694711cd7274a141fc02ad2dfe/pkg/ccl/backupccl/restore_job.go#L792)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 	allDescs, err := catalogkv.GetAllDescriptors(ctx, txn, keys.SystemSQLCodec)
> 	if err != nil {
> 		return false, err
> 	}
> ```
</details>

garbage now?
___
*[pkg/ccl/backupccl/restore_job.go, line 817 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55157#-MIemR6b8ude4zSuyF1f:-MIemR6b8ude4zSuyF1g:b-f5hikn) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e76a787dcc5c9694711cd7274a141fc02ad2dfe/pkg/ccl/backupccl/restore_job.go#L817)):*
> ```Go
> 	if err != nil {
> 		return false, err
> 	}
> ```

garbage now?

**Review by thoszhang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55157)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @pbardea)

___
*[pkg/ccl/backupccl/backup_test.go, line 6632 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55157#-MIemeB7DcclNb2HoxEM:-MJ8eP67AN6pKO89PUyt:boum8dw) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e76a787dcc5c9694711cd7274a141fc02ad2dfe/pkg/ccl/backupccl/backup_test.go#L6632)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 		// Use the same connection throughout (except for the concurrent RESTORE) to
> 		// preserve session variables.
> 		conn, err := tc.Conns[0].Conn(ctx)
> 		require.NoError(t, err)
> 		sqlDB := sqlutils.MakeSQLRunner(conn)
> ```
nit: you could still call `Conn(ctx)` on `sqlDB`. No need to get rid of that. 
</blockquote></details>

I don't think so? `sqlDB` from `BackupRestoreTestSetup` is a `*sqlutils.SQLRunner`.
___
*[pkg/ccl/backupccl/restore_job.go, line 792 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55157#-MIemNWsAzgTdLCfADBW:-MJ8evyMELAJfgB4KLs9:b-p4ybu) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e76a787dcc5c9694711cd7274a141fc02ad2dfe/pkg/ccl/backupccl/restore_job.go#L792)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	allDescs, err := catalogkv.GetAllDescriptors(ctx, txn, keys.SystemSQLCodec)
> 	if err != nil {
> 		return false, err
> 	}
> ```
garbage now?
</blockquote></details>

Oops, fixed.
___
*[pkg/ccl/backupccl/restore_job.go, line 817 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55157#-MIemR6b8ude4zSuyF1f:-MJ8ex1J6g9eYxOvnmEq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e76a787dcc5c9694711cd7274a141fc02ad2dfe/pkg/ccl/backupccl/restore_job.go#L817)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

garbage now?
</blockquote></details>

Done.

**Review by pbardea — APPROVED** [review]

**Comment by lucy-zhang** [comment]
TFTRs

bors r+

**Pull request merged**
