### PR TITLE
backupccl: Support BACKUP and RESTORE TENANT

### PR DESCRIPTION
**Pull request by dt**
backupccl: tenant backup/restore support

Tenants are made up of three things:
 1) a tenant ID 2) some metadata bytes and 3) the tenant's key-span.

Backing up a tenant consists of exporting their keyspan, and restoring a
tenant means creating a tenant record for that ID and importing that
keyspan.

In many ways this is much simpler than table, database or cluster backup
and restore, since we don't need to worry about individual tables or
databases or how they are related or not -- by simply importing and
exporting the tenant's entire keyspan, we've captured all of their data,
and things like jobs or schema changes or migrations will simply pick up
from where they left off just as if they were resuming from a reboot.

BACKUP and RESTORE TENANT are only available to the system tenant.

Tenants can only be backed up and restored completely -- there is no way
currently for the system tenant to peek into a tenant's key-space and
find individual tables or databases to backup. Similarly backed up
tenants are opaque spans of keys in the backup -- we do not know what or
even how many tables are in that backed up keyspan.

Additionally, tenants can only be restored to the same ID -- i.e. if you
BACKUP TENANT 5, you can only restore them as TENANT 5 in the restoring
cluster, which thus must not already contain an existing tenant 5. In
theory we could re-key the tenant's data the same way RESTORE can rekey
table data, however the fact that the tenant ID may appear in values
as well complicates this. One example is jobs which checkpoint spans or
high-watermark keys in their progress info -- these are encoded with the
tenant ID, meaning they'd need to be found and rewritten to support
RESTORE'ing to a new tenant ID.

Since a tenant is just a target span like a table, other backup/restore
features work the same on tenant backups as they do on table backups:
Changes to a tenant's key=space since the last backup can be backed up
incrementally, just like with table backups, and other features like
partitioning, AS OF SYSTEM TIME, revision_history and encryption should
work as well.

Release note (enterprise change): Support BACKUP TENANT and RESTORE TENANT.

### CODE REVIEW

**Comment by dt** [comment]
Couple things still not in this initial impl: 
 * `BACKUP TENANTS 1, 2, 3...` to capture multiple tenants at a time. Most of the code/protos/etc should already handle this but it needs syntax and a test. 
* `BACKUP TO x` (aka cluster backup) by the system tenant should learn to include all tenants.
* fetching tenants from `system.tenants` needs to learn about `AS OF SYSTEM TIME` and `revision_history`.
    * `AS OF SYSTME TIME` shouldn't be _too_ hard -- we just need to use our own txn to read it instead of the planner txn and set the timestamp to the backup time.
    * `revision_history` is going to be trickier -- exporting the actual data with revisions is easy enough, but tracking changes to the set of tenants will be the hard part. Currently we just do a `SELECT system.tenant` to find this set, but there's no way via SQL (or the ScanRequest it is built on) to read multiple revisions of rows, so e.g. it'd be missing a tenant that was deleted mid-way though the backup window, and consequently not export their data either. We'll probably need to do the same thing we do for schemas -- export the whole tenant table as SSTable(s) during planning, load them into memory and iterate them and do sql-like decoding by-hand to interpret the kvs.

**Review by pbardea — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 5 of 5 files at r2, 11 of 14 files at r3, 1 of 5 files at r5, 11 of 14 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50967)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @nvanbenschoten, @pbardea, and @tbg)

___
*[pkg/ccl/backupccl/backup_planning.go, line 544 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50967#-MBZqvlKECegKfEOpVQa:-MBZqvlL4JK5M9bRawJf:b-e8nfm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/23b17b581c7e8c30e2175ae7f9ebbc01b2c23bfe/pkg/ccl/backupccl/backup_planning.go#L544)):*
> ```Go
> 			}
> 			if !tree.MustBeDBool(res[0][0]) {
> 				return errors.Errorf("tenant %d is not active", id)
> ```

Hmm, is there a way to re-activate tenants? Or is it the case that once you destroy a tenant you can't restore a tenant back into it?
___
*[pkg/ccl/backupccl/restore_planning.go, line 997 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50967#-MBZUxtw5wA7H-OHJc3L:-MBZUxtw5wA7H-OHJc3M:bbald1e) ([raw file](https://github.com/cockroachdb/cockroach/blob/5aeaeebb05a52b2da005c73acadfd6b878af2b99/pkg/ccl/backupccl/restore_planning.go#L997)):*
> ```Go
> 			res, err := p.ExecCfg().InternalExecutor.Query(
> 				ctx, "restore-lookup-tenant", p.ExtendedEvalContext().Txn,
> 				`select active from system.tenants where id = $1`, i.ID,
> ```

nit: I'd prefer standard SQL formatting "SELECT active FROM ...", here and in backup.
___
*[pkg/ccl/backupccl/targets.go, line 19 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50967#-MBZVffDDPKQSFB62_Uo:-MBZVffDDPKQSFB62_Up:b-416gnm) ([raw file](https://github.com/cockroachdb/cockroach/blob/5aeaeebb05a52b2da005c73acadfd6b878af2b99/pkg/ccl/backupccl/targets.go#L19)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/keys"
> 	"github.com/cockroachdb/cockroach/pkg/kv"
> 	roachpb "github.com/cockroachdb/cockroach/pkg/roachpb"
> ```

huh, i've also noticed this happen automatically on a few of my branches. is there a reason that the alias is added here?
___
*[pkg/sql/tenant.go, line 91 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50967#-MBZf-Z64MpSGtSj_bis:-MBZf-Z70ymrfZ9eW5wM:b2ljdv5) ([raw file](https://github.com/cockroachdb/cockroach/blob/5aeaeebb05a52b2da005c73acadfd6b878af2b99/pkg/sql/tenant.go#L91)):*
> ```Go
> // CreateTenant implements the tree.TenantOperator interface.
> func (p *planner) CreateTenant(ctx context.Context, tenID uint64, tenInfo []byte) error {
> 	if err := CreateTenantRecord(ctx, p.Txn(), p.ExecCfg(), tenID, true, tenInfo); err != nil {
> ```

Can we add a `/*active*/` comment on the bool?

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50967)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @nvanbenschoten, @pbardea, and @tbg)

___
*[pkg/ccl/backupccl/backup_test.go, line 3955 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50967#-MBZr6D94mmKMfafe3UZ:-MBZr6D94mmKMfafe3U_:b-wyzprh) ([raw file](https://github.com/cockroachdb/cockroach/blob/23b17b581c7e8c30e2175ae7f9ebbc01b2c23bfe/pkg/ccl/backupccl/backup_test.go#L3955)):*
> ```Go
> 		systemDB.ExpectErr(t, "tenant 21 not in backup", `RESTORE TENANT 21 FROM 'nodelocal://1/t20'`)
> 		systemDB.ExpectErr(t, "file does not exist", `RESTORE TENANT 21 FROM 'nodelocal://1/t21'`)
> 	})
> ```

Can we add a test to restore into a destroyed tenant?

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50967)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten, @pbardea, and @tbg)

___
*[pkg/ccl/backupccl/backup_planning.go, line 544 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50967#-MBZqvlKECegKfEOpVQa:-MB_DtsV2kuDQemrzRns:bghmrbn) ([raw file](https://github.com/cockroachdb/cockroach/blob/23b17b581c7e8c30e2175ae7f9ebbc01b2c23bfe/pkg/ccl/backupccl/backup_planning.go#L544)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Hmm, is there a way to re-activate tenants? Or is it the case that once you destroy a tenant you can't restore a tenant back into it?
</blockquote></details>

I think the _intent_ is that after they are marked inactive, their data is dropped and then the tenant record is deleted, much like a table desc for a dropped table, but i'm not sure. Right now DestroyTenant isn't actually implemented though so waiting to see what their plan is there.
___
*[pkg/ccl/backupccl/backup_test.go, line 3955 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50967#-MBZr6D94mmKMfafe3UZ:-MB_Detn1d85AFBNQ-nU:bk2w36o) ([raw file](https://github.com/cockroachdb/cockroach/blob/23b17b581c7e8c30e2175ae7f9ebbc01b2c23bfe/pkg/ccl/backupccl/backup_test.go#L3955)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Can we add a test to restore into a destroyed tenant?
</blockquote></details>

`destroy_tenant` doesn't clear the tenant's keyspan yet, so it wouldn't work yet, so I added a TODO for now.
___
*[pkg/ccl/backupccl/restore_planning.go, line 997 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50967#-MBZUxtw5wA7H-OHJc3L:-MBfsgsN-OVByBMyWOr8:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/5aeaeebb05a52b2da005c73acadfd6b878af2b99/pkg/ccl/backupccl/restore_planning.go#L997)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

nit: I'd prefer standard SQL formatting "SELECT active FROM ...", here and in backup.
</blockquote></details>

done.
___
*[pkg/ccl/backupccl/targets.go, line 19 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50967#-MBZVffDDPKQSFB62_Uo:-MBfr5nX4Ovya2kkZw7U:b1u71yk) ([raw file](https://github.com/cockroachdb/cockroach/blob/5aeaeebb05a52b2da005c73acadfd6b878af2b99/pkg/ccl/backupccl/targets.go#L19)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

huh, i've also noticed this happen automatically on a few of my branches. is there a reason that the alias is added here?
</blockquote></details>

huh, nope. fixed.
___
*[pkg/sql/tenant.go, line 91 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50967#-MBZf-Z64MpSGtSj_bis:-MBfsiOA2kODj8x-FdYi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5aeaeebb05a52b2da005c73acadfd6b878af2b99/pkg/sql/tenant.go#L91)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Can we add a `/*active*/` comment on the bool?
</blockquote></details>

Done.

**Review by nvb — APPROVED** [review]
:lgtm: very nice. Thanks for writing this up.

> Reviewed 9 of 20 files at r4, 5 of 5 files at r5, 9 of 14 files at r6, 5 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50967#-:-MBk9M-j8HS8eIYcDSrs:bmqfqqh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt, @pbardea, and @tbg)

___
*[pkg/ccl/backupccl/backup_planning.go, line 544 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50967#-MBZqvlKECegKfEOpVQa:-MBk6jtj8tMpOMzxiGVL:bxm0gd9) ([raw file](https://github.com/cockroachdb/cockroach/blob/23b17b581c7e8c30e2175ae7f9ebbc01b2c23bfe/pkg/ccl/backupccl/backup_planning.go#L544)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I think the _intent_ is that after they are marked inactive, their data is dropped and then the tenant record is deleted, much like a table desc for a dropped table, but i'm not sure. Right now DestroyTenant isn't actually implemented though so waiting to see what their plan is there.
</blockquote></details>

Yes, that is the intent, but it's not super well defined and could be changed to better suit bulk-io's needs. David described improvements that he'd like to see in https://github.com/cockroachdb/cockroach/issues/48775.
___
*[pkg/ccl/backupccl/backup_planning.go, line 533 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50967#-MBk6ZU26NE87ILYRzUs:-MBk6ZU26NE87ILYRzUt:b-3l248w) ([raw file](https://github.com/cockroachdb/cockroach/blob/953f3cb2da70d5fac12e7bd9cfb8c29dc03b159a/pkg/ccl/backupccl/backup_planning.go#L533)):*
> ```Go
> 			id := backupStmt.Targets.Tenant.ToUint64()
> 
> 			res, err := p.ExecCfg().InternalExecutor.Query(
> ```

Can/should you use `QueryRow` here?
___
*[pkg/ccl/backupccl/backup_planning.go, line 551 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50967#-MBk7Tov9jx6InJpYLjw:-MBk7Tov9jx6InJpYLjx:b2725er) ([raw file](https://github.com/cockroachdb/cockroach/blob/953f3cb2da70d5fac12e7bd9cfb8c29dc03b159a/pkg/ccl/backupccl/backup_planning.go#L551)):*
> ```Go
> 			}
> 
> 			prefix := keys.MakeSQLCodec(backupStmt.Targets.Tenant).TenantPrefix()
> ```

You can just use `keys.MakeTenantPrefix` here.
___
*[pkg/ccl/backupccl/backup_test.go, line 3955 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50967#-MBZr6D94mmKMfafe3UZ:-MBk7kFvA5d3GilxIIwu:b-j2136m) ([raw file](https://github.com/cockroachdb/cockroach/blob/23b17b581c7e8c30e2175ae7f9ebbc01b2c23bfe/pkg/ccl/backupccl/backup_test.go#L3955)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

`destroy_tenant` doesn't clear the tenant's keyspan yet, so it wouldn't work yet, so I added a TODO for now.
</blockquote></details>

Mind pointing the TODO to https://github.com/cockroachdb/cockroach/issues/48775?
___
*[pkg/ccl/backupccl/backup_test.go, line 3911 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50967#-MBk7bCU4TVjjcXe8FHf:-MBk7bCU4TVjjcXe8FHg:bgqa1ux) ([raw file](https://github.com/cockroachdb/cockroach/blob/953f3cb2da70d5fac12e7bd9cfb8c29dc03b159a/pkg/ccl/backupccl/backup_test.go#L3911)):*
> ```Go
> }
> 
> // Ensure that backing up and restoring an empty database succeeds.
> ```

This comment looks off.
___
*[pkg/ccl/backupccl/restore_job.go, line 1094 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50967#-MBk907C9X9kOOOE6Dn3:-MBk907C9X9kOOOE6Dn4:brkbd4s) ([raw file](https://github.com/cockroachdb/cockroach/blob/953f3cb2da70d5fac12e7bd9cfb8c29dc03b159a/pkg/ccl/backupccl/restore_job.go#L1094)):*
> ```Go
> 		// Since we have already created any new databases that we needed,
> 		// we can return without importing any data.
> 		log.Warning(ctx, "no tables to restore")
> ```

`s/no tables/nothing/`
___
*[pkg/ccl/backupccl/restore_job.go, line 1104 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50967#-MBk936r47HP890JIutT:-MBk936r47HP890JIutU:bfpyrqi) ([raw file](https://github.com/cockroachdb/cockroach/blob/953f3cb2da70d5fac12e7bd9cfb8c29dc03b159a/pkg/ccl/backupccl/restore_job.go#L1104)):*
> ```Go
> 
> 	for _, tenant := range details.Tenants {
> 		prefix := keys.MakeSQLCodec(roachpb.MakeTenantID(tenant.ID)).TenantPrefix()
> ```

Same point about `keys.MakeTenantPrefix`.
___
*[pkg/ccl/backupccl/restore_planning.go, line 995 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50967#-MBk7rrN20F-9Swy4ZBO:-MBk7rrN20F-9Swy4ZBP:bl9s0tk) ([raw file](https://github.com/cockroachdb/cockroach/blob/953f3cb2da70d5fac12e7bd9cfb8c29dc03b159a/pkg/ccl/backupccl/restore_planning.go#L995)):*
> ```Go
> 		}
> 		for _, i := range tenants {
> 			res, err := p.ExecCfg().InternalExecutor.Query(
> ```

Same question about `QueryRow`.
___
*[pkg/sql/tenant.go, line 54 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50967#-MBk8dasCvczA1tstczf:-MBk8dasCvczA1tstczg:b-vgqihg) ([raw file](https://github.com/cockroachdb/cockroach/blob/953f3cb2da70d5fac12e7bd9cfb8c29dc03b159a/pkg/sql/tenant.go#L54)):*
> ```Go
> func CreateTenantRecord(
> 	ctx context.Context,
> 	txn *kv.Txn,
> ```

Based on the other two functions here, `execCfg` should come before `txn`.
___
*[pkg/sql/tenant.go, line 94 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/50967#-MBk8O6K5Df1GW09kZj9:-MBk8O6K5Df1GW09kZjA:b-lmfyxa) ([raw file](https://github.com/cockroachdb/cockroach/blob/953f3cb2da70d5fac12e7bd9cfb8c29dc03b159a/pkg/sql/tenant.go#L94)):*
> ```Go
> 		return err
> 	}
> 	// Initialize the tenant's keyspace.
> ```

nit: we lost a line above here.
___
*[pkg/sql/parser/sql.y, line 4535 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50967#-MBk53AK-9V5pmaIDZQ0:-MBk53AK-9V5pmaIDZQ1:b73uzzo) ([raw file](https://github.com/cockroachdb/cockroach/blob/124847e0e1309ffe6957bb4986513a8db8e8e793/pkg/sql/parser/sql.y#L4535)):*
> ```Yacc
> | TENANT iconst64
>   {
>     $$.val = tree.TargetList{Tenant: roachpb.MakeTenantID(uint64($2.int64()))}
> ```

`MakeTenantID` currently panics on an ID of 0. We should detect that here like we do in `tenantIDWrapper`.
___
*[pkg/sql/parser/sql.y, line 4535 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50967#-MBk5azF4wD4QzR0u3-b:-MBk5azF4wD4QzR0u3-c:b-2u58oa) ([raw file](https://github.com/cockroachdb/cockroach/blob/124847e0e1309ffe6957bb4986513a8db8e8e793/pkg/sql/parser/sql.y#L4535)):*
> ```Yacc
> | TENANT iconst64
>   {
>     $$.val = tree.TargetList{Tenant: roachpb.MakeTenantID(uint64($2.int64()))}
> ```

Do we want to support backing up the system tenant? If so, should `BACKUP TENANT system` work?
___
*[pkg/sql/sem/builtins/builtins.go, line 5966 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/50967#-MBk4Rqz8oedoDpEdVeD:-MBk4Rqz8oedoDpEdVeE:b-6inhpn) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e99062fe4ca5df6e7ebd270d5071c48c22f2113/pkg/sql/sem/builtins/builtins.go#L5966)):*
> ```Go
> }
> 
> var invalidNull = pgerror.New(pgcode.InvalidParameterValue, "input cannot be NULL")
> ```

nit: add this to the list of errors at the top of this file.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50967)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten, @pbardea, and @tbg)

___
*[pkg/ccl/backupccl/backup_test.go, line 3955 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50967#-MBZr6D94mmKMfafe3UZ:-MBlbw0O2h-m4sBjYC6t:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/23b17b581c7e8c30e2175ae7f9ebbc01b2c23bfe/pkg/ccl/backupccl/backup_test.go#L3955)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Mind pointing the TODO to https://github.com/cockroachdb/cockroach/issues/48775?
</blockquote></details>

Done.
___
*[pkg/sql/parser/sql.y, line 4535 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50967#-MBk5azF4wD4QzR0u3-b:-MBkViLd995quV0VdVbF:b5fes1s) ([raw file](https://github.com/cockroachdb/cockroach/blob/124847e0e1309ffe6957bb4986513a8db8e8e793/pkg/sql/parser/sql.y#L4535)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we want to support backing up the system tenant? If so, should `BACKUP TENANT system` work?
</blockquote></details>

I don't think we do -- RESTORE of a system tenant would be a mess since you'd be overwriting yourself and your own jobs table, where that restore job is.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 20 files at r8, 5 of 5 files at r9, 14 of 14 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50967#-:-MBtFJBqBnrbqj-lFohq:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @pbardea)

___
*[pkg/sql/parser/sql.y, line 4535 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50967#-MBk5azF4wD4QzR0u3-b:-MBtFDS2-vwjFfX_kWXX:bwfk0zb) ([raw file](https://github.com/cockroachdb/cockroach/blob/124847e0e1309ffe6957bb4986513a8db8e8e793/pkg/sql/parser/sql.y#L4535)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I don't think we do -- RESTORE of a system tenant would be a mess since you'd be overwriting yourself and your own jobs table, where that restore job is.
</blockquote></details>

Ok, then should we reject that somewhere?

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50967)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten and @pbardea)

___
*[pkg/sql/parser/sql.y, line 4535 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/50967#-MBk5azF4wD4QzR0u3-b:-MC3BaW7CbvrhDOzYJ5I:b-y2jfgu) ([raw file](https://github.com/cockroachdb/cockroach/blob/124847e0e1309ffe6957bb4986513a8db8e8e793/pkg/sql/parser/sql.y#L4535)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Ok, then should we reject that somewhere?
</blockquote></details>

We already do, as a side-effect of there not actually being a tenant 1, so you can't make a tenant backup of the system tenant. Added a test-case that verifies this.

**Comment by dt** [comment]
TFTRs!

bors r+

**Pull request merged**
