### PR TITLE
server: fix crdb_internal.cluster_inflight_traces in shared process mode

### LINKED ISSUE #106182: sql: `SELECT * FROM crdb_internal.cluster_inflight_traces WHERE trace_id = 1;` panics for shared-process tenants
Easy to reproduce in `./cockroach demo`.

Run as the app tenant:
```
demo@127.0.0.1:26257/demoapp/movr> SELECT * FROM crdb_internal.cluster_inflight_traces WHERE trace_id = 1;                                                                                                                             
*
* ERROR: a panic has occurred!
* runtime error: invalid memory address or nil pointer dereference
* (1) attached stack trace
*   -- stack trace:
*   | runtime.gopanic
*   | 	GOROOT/src/runtime/panic.go:884
*   | runtime.panicmem
*   | 	GOROOT/src/runtime/panic.go:260
*   | runtime.sigpanic
*   | 	GOROOT/src/runtime/signal_unix.go:839
*   | github.com/cockroachdb/cockroach/pkg/server.newSQLServer.func9
*   | 	github.com/cockroachdb/cockroach/pkg/server/server_sql.go:918
*   | github.com/cockroachdb/cockroach/pkg/util/tracing/collector.(*TraceCollector).StartIter
*   | 	github.com/cockroachdb/cockroach/pkg/util/tracing/collector/collector.go:96
*   | github.com/cockroachdb/cockroach/pkg/sql.glob..func44
*   | 	github.com/cockroachdb/cockroach/pkg/sql/crdb_internal.go:1947
*   | github.com/cockroachdb/cockroach/pkg/sql.(*virtualDefEntry).makeConstrainedRowsGenerator.func1
*   | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:823
*   | github.com/cockroachdb/cockroach/pkg/sql.setupGenerator.func3
*   | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:127
*   | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
*   | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:484
*   | runtime.goexit
*   | 	GOROOT/src/runtime/asm_amd64.s:1594
* Wraps: (2) runtime error: invalid memory address or nil pointer dereference
* Error types: (1) *withstack.withStack (2) runtime.errorString
*
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1047271be]

goroutine 5785 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).recover(0xc004b647f8?, {0x1072e86c0, 0xc001420a20})
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:230 +0x6a
panic({0x1052ef000, 0x10a964500})
	GOROOT/src/runtime/panic.go:884 +0x212
github.com/cockroachdb/cockroach/pkg/server.newSQLServer.func9({0x1072e86c0?, 0xc001420a20?})
	github.com/cockroachdb/cockroach/pkg/server/server_sql.go:918 +0x3e
github.com/cockroachdb/cockroach/pkg/util/tracing/collector.(*TraceCollector).StartIter(0xc00488e9f0, {0x1072e86c0, 0xc001420a20}, 0x1)
	github.com/cockroachdb/cockroach/pkg/util/tracing/collector/collector.go:96 +0x79
github.com/cockroachdb/cockroach/pkg/sql.glob..func44({0x1072e86c0, 0xc001420a20}, {0x107357270?, 0xc00141a338?}, 0xc00141a338?, {0x0?, 0x0?}, 0xc002847440)
	github.com/cockroachdb/cockroach/pkg/sql/crdb_internal.go:1947 +0xa5
github.com/cockroachdb/cockroach/pkg/sql.(*virtualDefEntry).makeConstrainedRowsGenerator.func1({0x1072e86c0, 0xc001420a20}, {0x1072a4f80, 0xc003b05de0})
	github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:823 +0x574
github.com/cockroachdb/cockroach/pkg/sql.setupGenerator.func3({0x1072e86c0, 0xc001420a20})
	github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:127 +0x114
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:484 +0x146
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:475 +0x43b
```

System tenant output for reference:
```
demo@127.0.0.1:26257/system/defaultdb> SELECT * FROM crdb_internal.cluster_inflight_traces WHERE trace_id = 1;                                                                                                                         
  trace_id | node_id | root_op_name | trace_str | jaeger_json
-----------+---------+--------------+-----------+--------------
(0 rows)

Time: 4ms total (execution 3ms / network 0ms)
```

As of commit 9e84bfea0add1953e5bad881c6081ac633dfe8ac

Jira issue: CRDB-29440
Epic: CRDB-26691

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit fixes a panic that would previously occur when querying `crdb_internal.cluster_inflight_traces` virtual table when running in shared-process multi-tenant mode. In particular, the problem was that we tried to access node liveness which isn't available, and now we will fall back to the multi-tenant way of doing things (using the instances reader). Additionally, this commit extends the existing test to also run in shared-process multi-tenant config which serves as a regression test for this bug. There is no release note since it's not a user-visible bug.

Fixes: #106182.
Epic: CRDB-26691

Release note: None

### CODE REVIEW

**Review by knz — APPROVED** [review]
:lgtm: but please consider the extra step suggested below.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106238#-:-NZeggEN0iNdLIhqyMBZ:b-pmy974)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier, @stevendanna, and @yuzefovich)

___
*[`pkg/server/server_sql.go` line 914 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106238#-NZegTlA1aPtYskACm4F:-NZegTlA1aPtYskACm4G:b46bsux) ([raw file](https://github.com/cockroachdb/cockroach/blob/f65fd0b8e652ba2eadbbbe75fda6acf3304ed15d/pkg/server/server_sql.go#L914)):*
> ```Go
> 	var getNodes func(ctx context.Context) ([]roachpb.NodeID, error)
> 	if isMixedSQLAndKVNode && hasNodeLiveness {
> 		// TODO(dt): any reason not to just always use the instance reader? And just
> ```

@yuzefovich could you investigate this comment by david? Maybe the simplification would work outright.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106238)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier, @knz, and @stevendanna)

___
*[`pkg/server/server_sql.go` line 914 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106238#-NZegTlA1aPtYskACm4F:-NZghKjFBoXrT2yh-hpx:b7eplkd) ([raw file](https://github.com/cockroachdb/cockroach/blob/f65fd0b8e652ba2eadbbbe75fda6acf3304ed15d/pkg/server/server_sql.go#L914)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

@yuzefovich could you investigate this comment by david? Maybe the simplification would work outright.
</blockquote></details>

I also thought about it initially but decided it would be more error-prone for the backport. I typed up this suggestion over in #106326, but my inclination is still to merge this PR as is (and backport it to 23.1), and then merge the unification PR only to master. Thoughts?

**Review by knz — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106238)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier, @stevendanna, and @yuzefovich)

___
*[`pkg/server/server_sql.go` line 914 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106238#-NZegTlA1aPtYskACm4F:-NZlr7Wg95Hwhm68ujr5:bopuxg0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f65fd0b8e652ba2eadbbbe75fda6acf3304ed15d/pkg/server/server_sql.go#L914)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I also thought about it initially but decided it would be more error-prone for the backport. I typed up this suggestion over in #106326, but my inclination is still to merge this PR as is (and backport it to 23.1), and then merge the unification PR only to master. Thoughts?
</blockquote></details>

Agreed, sgtm.

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by adityamaru** [comment]
This is nice, I found myself recently reading this code because I want to add the ability to capture traces of a running job as part of the observability work we are doing. Andrei had a (justified) gripe with the bespoke service that this virtual table uses - https://github.com/cockroachdb/cockroach/blob/e7c890ef7cbab5775cca0f0bdb8a23ad351b3a45/pkg/util/tracing/service/service.go#L49 and wanted it migrated to use the `Snapshot` RPCs on the admin server. I was going to make this change sometime in the next few weeks as part of https://github.com/cockroachdb/cockroach/issues/105440

**Pull request merged**
