### PR TITLE
prereqs: update to packages API

### PR DESCRIPTION
**Pull request by jordanlewis**
The go/build API is deprecated and doesn't work with modules anymore.

A few tests had to be modified and/or deleted because of changes to the way `packages.Load` works, but the meat of the testing is still there.

Release note: None

### CODE REVIEW

**Comment by jordanlewis** [comment]
n.b. I also included a `strings.Sort` in the prereqs output because there was some weird reordering going on, so a bunch of tests changed in a no-op way because of that.

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50144#-:-M9cvKJbC_a6X1Jz-4YQ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @otan, @petermattis, and @tbg)

___
*[pkg/cmd/prereqs/prereqs.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50144#-M9ctSPr0rpbtaahse_n:-M9ctSPr0rpbtaahse_o:b-97uajz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba151427792881831f64091bc93219c958be9e06/pkg/cmd/prereqs/prereqs.go#L106)):*
> ```Go
> 		sourceFileSets := [][]string{
> 			// Include all Go and Cgo source files.
> 			pkg.GoFiles, pkg.OtherFiles,
> ```

Does `OtherFiles` contain everything that was previously being explicitly included? I think the answer is yes, I'm just checking.
___
*[pkg/cmd/prereqs/prereqs.go, line 131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50144#-M9ctHO_97rBPqJXLfbk:-M9ctHO_97rBPqJXLfbl:b-iwu037) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba151427792881831f64091bc93219c958be9e06/pkg/cmd/prereqs/prereqs.go#L131)):*
> ```Go
> 		for _, imp := range pkg.Imports {
> 			// Only the root package's tests are included in test binaries, so
> 			// unconditionally disable includeTest for imported packages.
> ```

This comment seems to be out of date, referring to a parameter that is no longer present.

Did this functionality of only including the root package's tests in test binaries disappear?

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50144)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @otan, @petermattis, and @tbg)

___
*[pkg/cmd/prereqs/prereqs.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50144#-M9ctSPr0rpbtaahse_n:-M9cyHQFCuupd7iT0hRD:bvdjjcx) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba151427792881831f64091bc93219c958be9e06/pkg/cmd/prereqs/prereqs.go#L106)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Does `OtherFiles` contain everything that was previously being explicitly included? I think the answer is yes, I'm just checking.
</blockquote></details>

I believe it does. They got rid of the specificity here for some reason.

```
	// OtherFiles lists the absolute file paths of the package's non-Go source files,
	// including assembly, C, C++, Fortran, Objective-C, SWIG, and so on.
	OtherFiles []string
```
___
*[pkg/cmd/prereqs/prereqs.go, line 131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50144#-M9ctHO_97rBPqJXLfbk:-M9cyXWq0lEtK9_DmN07:brffmxd) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba151427792881831f64091bc93219c958be9e06/pkg/cmd/prereqs/prereqs.go#L131)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This comment seems to be out of date, referring to a parameter that is no longer present.

Did this functionality of only including the root package's tests in test binaries disappear? 
</blockquote></details>

The functionality remains. It's just done by the packages command now it seems. I checked by hand. Fixed the comment.

**Review by petermattis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50144)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @otan and @tbg)

**Pull request merged**
