### PR TITLE
server,cli: fix improperly wrapped errors

### PR DESCRIPTION
**Pull request by rafiss**
refs #42510

I'm working on a linter that detects errors that are not wrapped
correctly, and it discovered these.

Release note: None

### CODE REVIEW

**Review by knz — APPROVED** [review]
very nice. I already love your linter.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72352#-:-MnXcmP11BGGd7KTeLIS:b-p7qino)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/cli/clisqlclient/conn_test.go, line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72352#-MnXcaF5DPyv_kSLslRH:-MnXcaF72hbJjRtgmStX:b34tqb) ([raw file](https://github.com/cockroachdb/cockroach/blob/659812e9dcc7771beea995c332bd4e9639286da3/pkg/cli/clisqlclient/conn_test.go#L68)):*
> ```Go
> 	testutils.SucceedsSoon(t, func() error {
> 		if sqlRows, err := conn.Query(`SELECT 1`, nil); !errors.Is(err, driver.ErrBadConn) {
> 			return errors.AssertionFailedf("expected ErrBadConn, got %v", err)
> ```

`NewAssertionErrorWithWrappedErrf`? same below
___
*[pkg/server/drain_test.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72352#-MnXciiuCp9QrxgkPvUK:-MnXciiuCp9QrxgkPvUL:bz94qzl) ([raw file](https://github.com/cockroachdb/cockroach/blob/659812e9dcc7771beea995c332bd4e9639286da3/pkg/server/drain_test.go#L90)):*
> ```Go
> 			return nil
> 		}
> 		return errors.AssertionFailedf("server not yet refusing RPC, got %v", err)
> ```

assertion with wrap

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72352)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/cli/clisqlclient/conn_test.go, line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72352#-MnXcaF5DPyv_kSLslRH:-MnXiwtc6py8Q-rJ-U8h:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/659812e9dcc7771beea995c332bd4e9639286da3/pkg/cli/clisqlclient/conn_test.go#L68)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`NewAssertionErrorWithWrappedErrf`? same below
</blockquote></details>

Done.
___
*[pkg/server/drain_test.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72352#-MnXciiuCp9QrxgkPvUK:-MnXj6wi-L2JJfrwdbzN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/659812e9dcc7771beea995c332bd4e9639286da3/pkg/server/drain_test.go#L90)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

assertion with wrap
</blockquote></details>

Done.

**Comment by rafiss** [comment]
tftr!

bors r=knz

**Comment by rafiss** [comment]
bors r=knz

**Comment by rafiss** [comment]
bors r=knz

**Comment by knz** [comment]
made a mistake in review

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72352)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rafiss)

___
*[pkg/server/drain_test.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72352#-MnXciiuCp9QrxgkPvUK:-MnalQV2ExRFcVvzwtFL:b-8zg0qr) ([raw file](https://github.com/cockroachdb/cockroach/blob/659812e9dcc7771beea995c332bd4e9639286da3/pkg/server/drain_test.go#L90)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

please revert this one. we want an error to be returned by this function when Dial returns a nil error.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72352)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/server/drain_test.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72352#-MnXciiuCp9QrxgkPvUK:-Mnam0EbDEnsGWjsrwFB:by7giul) ([raw file](https://github.com/cockroachdb/cockroach/blob/659812e9dcc7771beea995c332bd4e9639286da3/pkg/server/drain_test.go#L90)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

please revert this one. we want an error to be returned by this function when Dial returns a nil error.
</blockquote></details>

not sure what the best way to do this is while still keeping the forthcoming linter happy. i could do
```
		errS := "<nil>"
		if err != nil {
			errS = err.Error()
		}
		return errors.Newf("server not yet refusing RPC, got %s", errS)
```

which seems gross.

should i keep it as is and instead allow a `//nolint` directive similar to https://github.com/cockroachdb/cockroach/blob/f339331028cd518a05e9c69c763701b847dacd1b/pkg/testutils/lint/passes/fmtsafe/fmtsafe.go#L274

**Comment by knz** [comment]
yes a nolint comment in this case seems appropriate.
you can also do:

```go
if err != nil {
   if grpc.XXX(err) {
     return nil
   }
   return errors.NewAssertion...(err, "...")
}
// nil err
return errors.AssertionFailed("dial did not fail")
```

**Review by knz — APPROVED** [review]

**Comment by rafiss** [comment]
tftr!

bors r=knz

**Pull request merged**
