### PR TITLE
sql: allow unbounded size columns in empty families

### PR DESCRIPTION
**Pull request by danhhz**
Bugfix.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7969)

### CODE REVIEW

**Comment by knz** [comment]
:lgtm: but I'd enjoy reading a SQL logic test that illustrates this, perhaps by creating some family then unbounded columns and see with the output of SHOW CREATE that they land in respective empty families.

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/descriptor_mutation_test.go, line 206 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7969#-KNEKI95inKS3fggnwcp:-KNEKI95inKS3fggnwcq:646717357) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8181c1a916a888cfa347de164d9ae9dddbf3f12/sql/descriptor_mutation_test.go#L206)):*
> ```Go
> 	if _, err := sqlDB.Exec(`
> CREATE DATABASE t;
> CREATE TABLE t.test (k CHAR PRIMARY KEY, v CHAR, i CHAR DEFAULT 'i', FAMILY (k), FAMILY (v), FAMILY (i));
> ```

Can you explain (perhaps in a comment) why it's important to have them in separate families?

---

*[sql/drop_test.go, line 40 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7969#-KNEKP-6yi9afw_pQERu:-KNEKP-7VxltNH78_Ic_:-2073021532) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8181c1a916a888cfa347de164d9ae9dddbf3f12/sql/drop_test.go#L40)):*
> ```Go
> 	if _, err := sqlDB.Exec(`
> CREATE DATABASE t;
> CREATE TABLE t.kv (k CHAR PRIMARY KEY, v CHAR, FAMILY (k), FAMILY (v));
> ```

Same as above

---

*[sql/sqlbase/structured.go, line 848 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7969#-KNENKq1N3GY49reC8D5:-KNENKq2TRbx_5i82g5l:536186750) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8181c1a916a888cfa347de164d9ae9dddbf3f12/sql/sqlbase/structured.go#L848)):*
> ```Go
> 	size, isBounded := upperBoundColumnValueEncodedSize(col)
> 	if !isBounded {
> 		size = FamilyHeuristicTargetBytes
> ```

If I understand properly, this happens to work just because if the family is empty, familySize+size below will be equal to FamilyHeuristicTargetBytes for the first empty family encountered. Is that correct?

If that is so, this way to deal with the situation feels a bit too much of a hack; I would then suggest setting size to 0, and then special case isBounded below:

```
                if !isBounded && familySize == 0 {
                         return i, true
                }
		if familySize+size <= FamilyHeuristicTargetBytes {
			return i, true
                }
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7969#-:-KNEON1IxDJ8dcmBj1wH:-1731420004)*

**Comment by paperstreet** [comment]
I changed the logic test I added to do two unbounded columns (plus pk columns) and show we end up with two families.

Thanks for the review!

---

Review status: 7 of 11 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[sql/descriptor_mutation_test.go, line 206 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7969#-KNEKI95inKS3fggnwcp:-KNEPLx-I_605Jao-hF5:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8181c1a916a888cfa347de164d9ae9dddbf3f12/sql/descriptor_mutation_test.go#L206)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Can you explain (perhaps in a comment) why it's important to have them in separate families?
</details>
Done.

---

*[sql/drop_test.go, line 40 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7969#-KNEKP-6yi9afw_pQERu:-KNEPLN3PgihixkRze3R:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8181c1a916a888cfa347de164d9ae9dddbf3f12/sql/drop_test.go#L40)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Same as above
</details>
Done.

---

*[sql/sqlbase/structured.go, line 848 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7969#-KNENKq1N3GY49reC8D5:-KNEVrbOWwcs5nBrETfK:-651921572) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8181c1a916a888cfa347de164d9ae9dddbf3f12/sql/sqlbase/structured.go#L848)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> If I understand properly, this happens to work just because if the family is empty, familySize+size below will be equal to FamilyHeuristicTargetBytes for the first empty family encountered. Is that correct?
> 
> If that is so, this way to deal with the situation feels a bit too much of a hack; I would then suggest setting size to 0, and then special case isBounded below:
> 
> ```
>                 if !isBounded && familySize == 0 {
>                          return i, true
>                 }
> 		if familySize+size <= FamilyHeuristicTargetBytes {
> 			return i, true
>                 }
> ```
</details>
Done, though yours has a bug : - p

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7969#-:-KNEVyJyMSNA5EczNP3q:1642050070)*

**Comment by knz** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/sqlbase/structured.go, line 883 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7969#-KNHqa--Q87cne8Jmow_:-KNHqa-0XvgcBK5OjnBp:-379668786) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e87b776790c25485362c5d454838f4cceb82585/sql/sqlbase/structured.go#L883)):*
> ```Go
> 			}
> 		}
> 		if familySize == 0 || isBounded && familySize+size <= FamilyHeuristicTargetBytes {
> ```

As usual I had a double take on the relative priority of || and &&. The code is fine, but to make reading easier I'd strongly suggest the parentheses.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7969)*

**Comment by knz** [comment]
:smile_cat: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7969#-:-KNHr7N7DWl6gn2h5ZEU:905692816)*

**Comment by paperstreet** [comment]
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/sqlbase/structured.go, line 883 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7969#-KNHqa--Q87cne8Jmow_:-KNI26K2cxb7nRm3SfQP:-742602422) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e87b776790c25485362c5d454838f4cceb82585/sql/sqlbase/structured.go#L883)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> As usual I had a double take on the relative priority of || and &&. The code is fine, but to make reading easier I'd strongly suggest the parentheses.
</details>
I think people have different opinions on whether this sort of thing is good or not. But you're the reviewer on this particular PR so here you go

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7969)*

**Pull request merged**
