### PR TITLE
server: reduce flakiness of TestEnsureSQLStatsAreFlushedForTelemetry

### LINKED ISSUE #66826: server: TestEnsureSQLStatsAreFlushedForTelemetry failed
server.TestEnsureSQLStatsAreFlushedForTelemetry [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3113610&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3113610&tab=artifacts#/) on master @ [95028269160e0bfa2b94477238e72670bf780e9d](https://github.com/cockroachdb/cockroach/commits/95028269160e0bfa2b94477238e72670bf780e9d):

```
=== RUN   TestEnsureSQLStatsAreFlushedForTelemetry
    test_log_scope.go:73: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestEnsureSQLStatsAreFlushedForTelemetry543294354
    test_log_scope.go:74: use -show-logs to present logs inline
    stats_test.go:152: expected to not find stat, but did
    stats_test.go:157: -- test log scope end --
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestEnsureSQLStatsAreFlushedForTelemetry543294354
--- FAIL: TestEnsureSQLStatsAreFlushedForTelemetry (0.22s)
```
<details><summary>Reproduce</summary>
<p>
<p>To reproduce, try:

```bash
make stressrace TESTS=TestEnsureSQLStatsAreFlushedForTelemetry PKG=./pkg/server TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```
</p>
<p>Parameters in this failure:

- GOFLAGS=-parallel=4
</p>
</p>
</details>
<details><summary>Internal log</summary>
<p>

```
rohany marked as alumn{us/a}; resolving to solongordon instead
```
</p>
</details>

/cc @cockroachdb/server solongordon
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestEnsureSQLStatsAreFlushedForTelemetry.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by Azhng**
Previously, this unit tests generates statements with the fingerprint
'INSERT INTO _ VALUES (_)'. However, this is a very common fingerprint
and can collide with actual statements issued by other subsystems, which
in turn cause test failure.
This commit change the test cases to use uncommon statements that should
not cause fingerprint collision

Resolves #66826

Release note: None

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68614)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[-- commits, line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68614#-MggrLVB6xEFDB0JEDHb:-MggrLVB6xEFDB0JEDHc:b1wufh2) ([raw file](https://github.com/cockroachdb/cockroach/blob/d63db558b979e9e7d3846892b1995c6fa337651a/-- commits#L8)):*
nit: the wording here is a little confusing. You mean the new cases should NOT cause collision?

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68614)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[-- commits, line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68614#-MggrLVB6xEFDB0JEDHb:-MggumjD53s0PMoGBJgN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d63db558b979e9e7d3846892b1995c6fa337651a/-- commits#L8)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: the wording here is a little confusing. You mean the new cases should NOT cause collision?
</blockquote></details>

Done.

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68614)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[-- commits, line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68614#-MggrLVB6xEFDB0JEDHb:-MggzGON2HYR8h446ztc:biq87j2) ([raw file](https://github.com/cockroachdb/cockroach/blob/d63db558b979e9e7d3846892b1995c6fa337651a/-- commits#L8)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can you update on the PR description too?

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68614)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[-- commits, line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68614#-MggrLVB6xEFDB0JEDHb:-Mgh-Yf2EDzS-LztCMwM:beoor4x) ([raw file](https://github.com/cockroachdb/cockroach/blob/d63db558b979e9e7d3846892b1995c6fa337651a/-- commits#L8)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

Can you update on the PR description too?
</blockquote></details>

Oops forgot to hit the "Update" button

**Review by maryliag — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68614#-:-MgkAnf14hfgTlYHsQAS:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng)

**Pull request merged**
