### PR TITLE
sql: implement crdb_internal.transaction_statistics

### PR DESCRIPTION
**Pull request by Azhng**
Depends on #68715 and #69022

# First Commit 

roachpb,sql,server: add TransactionFingerprintID to
 roachpb.CollectedTransactionStatistics

Previously, roachpb.CollectedTransactionStatistics does not contain
TransactionFingerprintID. This results in SQLStatusServer's
/_status/statements endpoint not able to return transaction
fingerprint id in the response.
This commit adds transaction fingerprint id into CollectedTransactionStatistics
and simplifies the API in multiple layers.

Release note: None

# Second Commit 

sql: introduce crdb_internal.transaction_statistics virtual table

This commit introduces crdb_internal.transaction_statistics virtual
table that exposes both cluster-wide in-memory transaction statistics
as well as persited transaction statistics. This new virtual table
will be used to replace crdb_internal.node_transaction_statistics
virtual table, which only surface node-local in-memory transaction
statsitics.

Follow up to #68715

Release justification: Category 4

Release note (sql change): introduced new crdb_internal.transaction_statistics
 virtual table that surfaces both cluster-wide in-memory transaction statistics
 as well as persisted transaction statistics.

### CODE REVIEW

**Review by maryliag — APPROVED** [review]
:lgtm: 

> Reviewed 15 of 15 files at r1, 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69049#-:-Mhn9QGF1QGtz6q1aPyR:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng)

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 15 of 15 files at r1, 5 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69049#-:-MhnL80h1v5w22tEXFJN:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/sql/crdb_internal.go, line 5066 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69049#-MhnHr9FEGuJuWQUaN6v:-MhnHr9G6gUN5uyjWGSp:bd1tir7) ([raw file](https://github.com/cockroachdb/cockroach/blob/263c92b46c49bcd4a0a5673e95c889e393216a3c/pkg/sql/crdb_internal.go#L5066)):*
> ```Go
> 		if err != nil {
> 			return nil, nil, err
> 		}
> ```

thoughts on adding the memory in use for these stats to the monitor here and then releasing it in the worker? It's not perfect but it's better than nothing. 
___
*[pkg/sql/sqlstats/sslocal/temp_sql_stats.go, line 51 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69049#-MhnKourDlIaSrf3BKsn:-MhnKourDlIaSrf3BKso:bwuib9k) ([raw file](https://github.com/cockroachdb/cockroach/blob/263c92b46c49bcd4a0a5673e95c889e393216a3c/pkg/sql/sqlstats/sslocal/temp_sql_stats.go#L51)):*
> ```Go
> // Less implements the sort.Interface interface.
> func (t txnResponseList) Less(i, j int) bool {
> 	return strings.Compare(t[i].StatsData.App, t[j].StatsData.App) == -1
> ```

This is usually written as `< 0` but also, why not `t[i].StatsData.App < t[j].StatsData.App`?

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69049)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner and @maryliag)

___
*[pkg/sql/crdb_internal.go, line 5066 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69049#-MhnHr9FEGuJuWQUaN6v:-MhnX3svAXN0MQcXEiPn:b9zlity) ([raw file](https://github.com/cockroachdb/cockroach/blob/263c92b46c49bcd4a0a5673e95c889e393216a3c/pkg/sql/crdb_internal.go#L5066)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

thoughts on adding the memory in use for these stats to the monitor here and then releasing it in the worker? It's not perfect but it's better than nothing. 
</blockquote></details>

Done. I think it's ok for a stopgap solution for now. Left a TODO here that reference the tracking issue. 
___
*[pkg/sql/sqlstats/sslocal/temp_sql_stats.go, line 51 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69049#-MhnKourDlIaSrf3BKsn:-MhnXEY06Jy3OyoqxMQF:b-ayfte7) ([raw file](https://github.com/cockroachdb/cockroach/blob/263c92b46c49bcd4a0a5673e95c889e393216a3c/pkg/sql/sqlstats/sslocal/temp_sql_stats.go#L51)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This is usually written as `< 0` but also, why not `t[i].StatsData.App < t[j].StatsData.App`?
</blockquote></details>

Done. TIL `<` works on strings.

**Comment by Azhng** [comment]
TFTR!

bors r=ajwerner,maryliag

**Pull request merged**
