### PR TITLE
sql: implement combined iterator for transaction statistics

### PR DESCRIPTION
**Pull request by Azhng**
Follow up to #68675

Release note: None

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69022)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69022#-MhJkc8V1t9uN9kyUxzt:-MhJkc8V1t9uN9kyUxzu:bwcs0g3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e179dcf6cb302afa2891048ceffa6e68fe85ccb9/-- commits#L4)):*
Can you add a little more description here for future reference?
___
*[pkg/sql/sqlstats/persistedsqlstats/combined_iterator.go, line 342 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69022#-MhJlFWY9KraGENRCWXH:-MhJlFWY9KraGENRCWXI:b-nz7u6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e179dcf6cb302afa2891048ceffa6e68fe85ccb9/pkg/sql/sqlstats/persistedsqlstats/combined_iterator.go#L342)):*
> ```Go
> }
> 
> // Cur returns the roachpb.CollectedStatementStatistics at the current internal
> ```

nit: CollectedTransactionStatistics
___
*[pkg/sql/sqlstats/persistedsqlstats/reader_test.go, line 123 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69022#-MhJljbC83sFTiROYG2-:-MhJljbC83sFTiROYG20:bf6iw9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e179dcf6cb302afa2891048ceffa6e68fe85ccb9/pkg/sql/sqlstats/persistedsqlstats/reader_test.go#L123)):*
> ```Go
> 					statistics *roachpb.CollectedTransactionStatistics,
> 				) error {
> 					if len(statistics.StatementFingerprintIDs) == 1 {
> ```

you're iterating transactions, but checking statements fingerprint, is that correct?
___
*[pkg/sql/sqlstats/persistedsqlstats/reader_test.go, line 177 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69022#-MhJlxt90Xwyx62idP2a:-MhJlxt90Xwyx62idP2b:ba3dxip) ([raw file](https://github.com/cockroachdb/cockroach/blob/e179dcf6cb302afa2891048ceffa6e68fe85ccb9/pkg/sql/sqlstats/persistedsqlstats/reader_test.go#L177)):*
> ```Go
> 				statistics *roachpb.CollectedTransactionStatistics,
> 			) error {
> 				if len(statistics.StatementFingerprintIDs) == 1 {
> ```

same thing here: you're iterating transactions but checking statements

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69022)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69022#-MhJkc8V1t9uN9kyUxzt:-MhKCTvG2vwRTiJt9CxM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e179dcf6cb302afa2891048ceffa6e68fe85ccb9/-- commits#L4)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

Can you add a little more description here for future reference?
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/combined_iterator.go, line 342 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69022#-MhJlFWY9KraGENRCWXH:-MhKBSRlAhs08IgZ9sDL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e179dcf6cb302afa2891048ceffa6e68fe85ccb9/pkg/sql/sqlstats/persistedsqlstats/combined_iterator.go#L342)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: CollectedTransactionStatistics
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/persistedsqlstats/reader_test.go, line 123 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69022#-MhJljbC83sFTiROYG2-:-MhKBTvE8xxkB09_23Gy:bpkvzsb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e179dcf6cb302afa2891048ceffa6e68fe85ccb9/pkg/sql/sqlstats/persistedsqlstats/reader_test.go#L123)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

you're iterating transactions, but checking statements fingerprint, is that correct?
</blockquote></details>

Yes, since the test cases here is keyed using the statement fingerprint string (this is because it's difficult to compute transaction fingerprint id directly from the statement fingerprint string), and we don't have a way to lookup transaction using statement fingerprint string directly, we do an indirect lookup by using the statement fingerprint id associated with that transaction to lookup the test case result. 
___
*[pkg/sql/sqlstats/persistedsqlstats/reader_test.go, line 177 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69022#-MhJlxt90Xwyx62idP2a:-MhKBpm6-MESvX97Xwc2:bki013v) ([raw file](https://github.com/cockroachdb/cockroach/blob/e179dcf6cb302afa2891048ceffa6e68fe85ccb9/pkg/sql/sqlstats/persistedsqlstats/reader_test.go#L177)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

same thing here: you're iterating transactions but checking statements
</blockquote></details>

replied in the thread above

**Review by maryliag — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69022#-:-MhKE6MG2DRHXN_URSYF:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag)

**Comment by Azhng** [comment]
TFTR!

bors r=maryliag

**Comment by Azhng** [comment]
bors r=maryliag

**Pull request merged**
