### PR TITLE
sql: fix multiple UX shortcomings with zone configs

### LINKED ISSUE #35756: sql: SHOW ZONE CONFIGURATION FOR TABLE <table_name> PARTITION <partition_name> doesn't work
**Describe the problem**

I partitioned a table, created replication zones for the partition, viewed one of the replication zones with the `SHOW ZONE CONFIGURATION FOR PARTITION <partition_name> OF TABLE <table_name>` syntax (this worked), and then tried to do the same thing with the `SHOW ZONE CONFIGURATION FOR TABLE <table_name> PARTITION <partition_name>` syntax (didn't work).

**Cockroach version**

```
~$ cockroach version
Build Tag:    v2.2.0-alpha.20190211-100-g10f8010fa5-dirty
Build Time:   2019/02/13 03:42:25
Distribution: CCL
Platform:     darwin amd64 (x86_64-apple-darwin17.7.0)
Go Version:   go1.11
C Compiler:   4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.10.44.4)
Build SHA-1:  10f8010fa5778e740c057905e2d7664b5fd5d647
Build Type:   development
```

**To Reproduce**

1. Start up a local cluster.

2. Open the SQL shell.

3. Set an enterprise license.

4. Create a database:

```
CREATE DATABASE roachlearn;
```

5. Create a table with partitions:

```
CREATE TABLE roachlearn.students (
    id INT DEFAULT unique_rowid(),
    name STRING,
    email STRING,
    country STRING,
    expected_graduation_date DATE,   
    PRIMARY KEY (country, id))
    PARTITION BY LIST (country) (
      PARTITION north_america VALUES IN ('CA','US'),
      PARTITION europe VALUES IN ('DE', 'CH'),
      PARTITION australia VALUES IN ('AU','NZ'),
      PARTITION DEFAULT VALUES IN (default)
    );
```

6. Create replication zones for partitions:

```
ALTER PARTITION north_america OF TABLE roachlearn.students     CONFIGURE ZONE USING constraints='[+region=us]';

ALTER PARTITION europe OF TABLE roachlearn.students     CONFIGURE ZONE USING constraints='[+region=de]';
ALTER PARTITION australia OF TABLE roachlearn.students     CONFIGURE ZONE USING constraints='[+region=aus]';
```

7. View the replication zone for one of the partitions:

```
SHOW ZONE CONFIGURATION FOR PARTITION north_america OF TABLE roachlearn.students;
              zone_name             |                                           config_sql
+-----------------------------------+------------------------------------------------------------------------------------------------+
  roachlearn.students.north_america | ALTER PARTITION north_america OF INDEX roachlearn.public.students@primary CONFIGURE ZONE USING
                                    |     range_min_bytes = 16777216,
                                    |     range_max_bytes = 67108864,
                                    |     gc.ttlseconds = 90000,
                                    |     num_replicas = 3,
                                    |     constraints = '[+region=us]',
                                    |     lease_preferences = '[]'
(1 row)
```

8. Try to use an alternative syntax to view the replication zone:

```
SHOW ZONE CONFIGURATION FOR TABLE roachlearn.students PARTITION north_america;
  zone_name |                config_sql
+-----------+------------------------------------------+
  .default  | ALTER RANGE default CONFIGURE ZONE USING
            |     range_min_bytes = 16777216,
            |     range_max_bytes = 67108864,
            |     gc.ttlseconds = 90000,
            |     num_replicas = 3,
            |     constraints = '[]',
            |     lease_preferences = '[]'
(1 row)
```

### PR DESCRIPTION
**Pull request by knz**
Fixes #35756.

This patch resolves several separate but related SQL zone config bugs.

1. SHOW ZONE CONFIG would print out nonsensical ALTER statements
   for inherited database zone configs or the default zone config.

   This was happening because of a conjunction of two implementations
   shortcuts:

   - `(*ZoneSpecifier).Format()` would print out the "PARTITION"
     keyword as soon as the partition name was set, even for zone
     specifiers for ranges or databases (only tables or indexes can
     have partitions). This is nonsensical.

   - the code for SHOW ZONE CONFIG would determine a zone specifier
     to use for the output ALTER syntax by filling fields from
	 the resolved zone details *on top* of the initial zone specifier.
	 So when doing SHOW ZONE CONFIG FOR PARTITION ..., *and*
	 there was no zone config for that partition (so that a database
	 or range config would apply), the resulting zone specifier
	 would still have its "Partition" field populated.

   This patch fixes the issue by both omitting the PARTITION clause
   for non-table, non-index zone specifiers, and erasing the partition
   field in the ALTER zone specifier in SHOW ZONE CONFIG.

2. parser does not recognize ALTER syntax printed by SHOW ZONE CONFIG.

   When using SHOW ZONE CONFIG on a partitioned index, the output
   ALTER syntax printed by SHOW would say `ALTER PARTITION ... OF
   INDEX tbl@idx  CONFIGURE ZONE ...`.

   However, the SQL grammar did not recognize `ALTER PARTITION OF
   INDEX`, resulting in poor UX. This patch adds support for the
   missing syntax.

3. SHOW ZONE CONFIG would accept but *ignore* a partition name
   specifier when using the syntax variant `... FOR TABLE
   ... PARTITION ...`. (The partition name was properly handled when
   using the variant `... FOR PARTITION ... OF TABLE ...`).

   This was causing suprising/incorrect results when using that
   syntax (especially when combined with the first two bugs).

   This patch ensures that the partition name is not ignored in this form.

4. SHOW ZONE CONFIG would accept two (equivalent) syntax forms for
   partitioned tables, but just one for indexes. This was
   inconsistent.

   This patch ensures that both the forms `FOR INDEX ... PARTITION
   ... ` and `FOR PARTITION ... OF INDEX ...` are supported,f or
   consistency.

Release note (bug fix): `SHOW ZONE CONFIGURATION` does not any more
emit invalid ALTER syntax in its output when displaying the zone
configuration for a table or index partition that is inheriting from
the database or the default configuration.

Release note (enterprise change): It is now possible to alter the zone
configuration for a secondary index partition using the syntax `ALTER
PARTITION OF INDEX <tablename>@<indexname> CONFIGURE ZONE ...`.

Release note (bug fix): `SHOW ZONE CONFIGURATION FOR TABLE t PARTITION
p` does not ignore the clause "PARTITION p" any more and properly
displays the zone configuration for that partition instead.

### CODE REVIEW

**Comment by knz** [comment]
cc @jseldess @nvanbenschoten 

@jordanlewis I think this should be backported to 19.1 (after the release, for the .1 patch). Do you agree?

**Comment by knz** [comment]
cc @nstewart this is what we were talking about

**Comment by awoods187** [comment]
cc @andy-kimball bc he looked here recently

**Review by madelynnblue — APPROVED** [review]
LGTM, with the caveat that I'm not qualified to review zone config or partition specifics.

**Comment by knz** [comment]
> LGTM, with the caveat that I'm not qualified to review zone config or partition specifics.

Now you are. :)

(AFAIK no one else in the org has up-to-date expertise in this area at this time.)

**Comment by jseldess** [comment]
Thanks, @knz!

**Pull request merged**
