### PR TITLE
colexec: fix vectorized eval test

### LINKED ISSUE #51032: colexec: fix vectorized eval test harness and present bugs
We have been incorrectly running vectorized eval test (because the expression have been preevaluated to a constant before the vectorized operators get planned), and we already have a couple of bugs crop in:
```
--- FAIL: TestEval (0.18s)
    --- FAIL: TestEval/vectorized (0.18s)
        --- FAIL: TestEval/vectorized/arithmetic_operators (0.00s)
            datadriven.go:165: 
                ../testdata/eval/arithmetic_operators:61: 9 // 2
                expected:
                4
                found:
                9
        --- FAIL: TestEval/vectorized/boolean (0.00s)
            datadriven.go:165: 
                ../testdata/eval/boolean:26: true AND NULL
                expected:
                NULL
                found:
                unexpected error from the vectorized engine: interface conversion: coldata.Column is *coldataext.datumVec, not coldata.Bools
FAIL
FAIL	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval_test	2.670s
```

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: fix a bug with FloorDiv**

FloorDiv operators in sql is `//` and we were using it as is in the
generated code for floor division of integers. However, in Go this is
a symbol for an inline comment, so we ended up not doing any operation
and simply used the first argument as is. This is now fixed.

Release note: None (no stable release with this bug).

**colexec: fix logical operations with NULL constant values**

Previously, AND and OR logical projection operators assumed that both
input vectors are `Bool`s, but it is also valid to have a constant NULL
value on one of the sides (which is represented by `UnknownFamily`), and
in such scenario we would run into a runtime conversion error. Now the
template has been refactored to support constant NULL values on either
side. Also note that we do not support NULL vs NULL because we assume
that the optimizer is smart enough to reduce such case to NULL on its
own.

Release note: None (no stable release with this bug)

**eval_test: fix vectorized test**

Previously, we were using `Expression.Expr` (a serialized expression) to
pass in the expression to evaluate. Such expression, when deserialized,
preevaluates the constants, and since all eval tests operate on
constants, we would always preevaluate the whole expression during that
deserialization step. As a result, we actually didn't test the
vectorized engine itself. Now this is fixed by passing in `TypedExpr`
which the vectorized engine then transforms into the appropriate
operators.

Fixes: #51032.

Release note: None

**colexec: refactor unit tests in overloads_test into eval tests**

This commit refactors all unit tests that we have in `overloads_test.go`
into the equivalent eval tests (if similar tests didn't already exist).
This allows us to remove the annoying `overloads_test_utils.eg.go` file.

Release note: None

### CODE REVIEW

**Review by jordanlewis — APPROVED** [review]
> Reviewed 6 of 6 files at r1, 5 of 5 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51531)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/sql/colexec/and_or_projection_tmpl.go, line 398 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51531#-MCUPoAO-qMxY3nbKSrm:-MCUPoAP6SebAqkOWbk6:b-emckum) ([raw file](https://github.com/cockroachdb/cockroach/blob/6379efaf6429521c3763c90d8835cc4bd51806f8/pkg/sql/colexec/and_or_projection_tmpl.go#L398)):*
> ```Go
> 		rightVal = rightVals[idx]
> 		// {{end}}
> 		// The rules for performing a logical operation on two booleans are:
> ```

Neat simplification.

Now that I've seen what this operator could look like in #51117 I wish this code review was in that model too, but I can just rebase that on top of this because I'm taking forever over there.
___
*[pkg/sql/colexec/execgen/cmd/execgen/overloads_bin.go, line 215 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51531#-MCULeZS6foeT3myfIXa:-MCULeZS6foeT3myfIXb:b-bq5rvq) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e8fd6b2f837c1787f8012f4fdba7e901e8cc4a9/pkg/sql/colexec/execgen/cmd/execgen/overloads_bin.go#L215)):*
> ```Go
> 		opStr = "^"
> 	case tree.FloorDiv:
> 		// tree.FloorDiv is "//" when stringified, but that would be a begging
> ```

nit: the beginning.
___
*[pkg/sql/colexec/execgen/cmd/execgen/overloads_bin.go, line 216 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51531#-MCULgMs9YSWJKz7DvSt:-MCULgMs9YSWJKz7DvSu:bkipw84) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e8fd6b2f837c1787f8012f4fdba7e901e8cc4a9/pkg/sql/colexec/execgen/cmd/execgen/overloads_bin.go#L216)):*
> ```Go
> 	case tree.FloorDiv:
> 		// tree.FloorDiv is "//" when stringified, but that would be a begging
> 		// of a comment in Go ad we need to use "/"
> ```

nit: s/ad/and, and add a period to the end.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51531)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/colexec/and_or_projection_tmpl.go, line 398 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51531#-MCUPoAO-qMxY3nbKSrm:-MCUdYkK-nKxeQ6H8AXl:b761afy) ([raw file](https://github.com/cockroachdb/cockroach/blob/6379efaf6429521c3763c90d8835cc4bd51806f8/pkg/sql/colexec/and_or_projection_tmpl.go#L398)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Neat simplification.

Now that I've seen what this operator could look like in #51117 I wish this code review was in that model too, but I can just rebase that on top of this because I'm taking forever over there.
</blockquote></details>

Yeah, I was actually kind of waiting for you to merge that PR, but it's been a while, so I decided to proceed here. I also thought that fixing a bug and refactoring the template at the same time would be too complicated, and I briefly thought about rebasing on top of your PR myself, but I didn't want this PR to get blocked on the other one. I think it'll be relatively easy for you to rebase.

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by yuzefovich** [comment]
"pebble closed" flake

bors r+

**Pull request merged**
