### PR TITLE
ui: add connected component for jobs pages

### PR DESCRIPTION
**Pull request by ericharmeling**
This PR adds "connected" components for the jobs pages. These components can be imported from the `cluster-ui` package into the `managed-service` repo and used on the CC console **for Dedicated clusters** (serverless clusters do not support the admin server that handles job requests).

Related to https://github.com/cockroachdb/cockroach/issues/71324.

Release note: None

### CODE REVIEW

**Comment by ericharmeling** [comment]
On the CC Console (with local `cluster-ui`):
https://www.loom.com/share/dae5fb6c6c964b87b3b257c8bd3cfca0

On the DB Console:
https://www.loom.com/share/29028dd627254c46880b875a06029340

**Review by maryliag — APPROVED** [review]
Awesome job on the Jobs! :smile: 
:lgtm:   

> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83901#-:-N6UMrsA6vpQ8xSCmYD-:b-e6opu)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling)

___
*[`pkg/ui/workspaces/cluster-ui/src/store/utils/selectors.ts` line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83901#-N6UMeGs-ldzD89sZgZV:-N6UMeGs-ldzD89sZgZW:b-7k1ax7) ([raw file](https://github.com/cockroachdb/cockroach/blob/74f1441bd4f3d113aed95d0c3fc316fa18887a8c/pkg/ui/workspaces/cluster-ui/src/store/utils/selectors.ts#L22)):*
> ```XML
>   adminUISelector,
>   adminUiState => adminUiState.localStorage,
> );
> ```

Really nice refactor!!

**Review by ericharmeling — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83901#-:-N6UTpZc8Zm2aNBXhh1n:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/store/utils/selectors.ts` line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83901#-N6UMeGs-ldzD89sZgZV:-N6UTlRw7SrvyPSnxFTO:b2x9v3l) ([raw file](https://github.com/cockroachdb/cockroach/blob/74f1441bd4f3d113aed95d0c3fc316fa18887a8c/pkg/ui/workspaces/cluster-ui/src/store/utils/selectors.ts#L22)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

Really nice refactor!!
</blockquote></details>

:blush:

**Comment by ericharmeling** [comment]
bors retry

**Pull request merged**
