### PR TITLE
sql,server: use aggregate sql stats functions everywhere

### PR DESCRIPTION
**Pull request by xinhaoz**
Previously `crdb_internal.merge_statement_stats`,
`crdb_internal.merge_transaction_stats`,
 and `crdb_internal.merge_stats_metadata` were used to merge
groupings of sql stats rows in the statement and transaction
tables for various purposes (serving sql activity page responses,
creating table views, debug zip queries). These builtins require
the use array_agg which can be memory intensive when operating
on large data sets. We now use the aggregate functions
`merge_stats_metadata`, `merge_transaction_stats`, and
`merge_statement_stats` which do not require an array allocation.

Note that removing the use of
`crdb_internal.merge_aggregated_stmt_metadata` is intentionally
skipped in this PR to reduce complexity as this will be a new
array agg function requiring a version gate.

Epic: none

Release note: None

Part of: https://github.com/cockroachdb/cockroach/issues/119309

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
Thanks for looking into this! I have some comments to consider.

> Reviewed 12 of 12 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119283#-:-NrCubiqBrZADIgcnORJ:bza6k8q)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @DrewKimball, and @xinhaoz)

___
*[`-- commits` line 22 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119283#-NrCsQTm9dFudjouCsi2):*
nit: `crdb_internal.merge_aggregated_stmt_metadata` too.
___
*[`-- commits` line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119283#-NrCtQDn5U7vzLcrTJXh):*
We might need to be careful with this change in mixed-version clusters. In particular, if the gateway node uses the new aggregate functions and the query gets distributed, the remote nodes might not be aware of such functions, so I'd expect the distributed query to error out. It would be nice to confirm this.

I wrote my understanding of the situation at the top of [this comment](https://github.com/cockroachdb/cockroach/pull/111303#pullrequestreview-1647448808) that introduced some of these aggregates originally. What allowed us to backport them safely was the fact that we only used new aggregates in write queries (INSERT, UPDATE, etc) which we cannot distribute, but your change adjusts read queries, so now we need to think whether these queries can get distributed, and if so, how to properly gate the rollout of this update.
___
*[`pkg/sql/sem/builtins/aggregate_builtins.go` line 1832 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119283#-NrCoGyk2Pa2pvvSDJq4:-NrCoGyk2Pa2pvvSDJq5:b-rszje4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7638e11f430a667f6db3d59e9ca3a1fd10ec5d5a/pkg/sql/sem/builtins/aggregate_builtins.go#L1832)):*
> ```Go
> }
> 
> // Aggregate function for the appstatspb.AggregatedStatementMetadata type.
> ```

nit: both this new aggregate as well as existing `aggStatementMetadata` operate on `appstatspb.AggregatedStatementMetadata` - it'd be nice to highlight the differences between the two in the comments.
___
*[`pkg/sql/sem/builtins/aggregate_builtins.go` line 1839 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119283#-NrCobPx3HvoYeGgsZT7:-NrCobPx3HvoYeGgsZT8:b-rhjwa) ([raw file](https://github.com/cockroachdb/cockroach/blob/7638e11f430a667f6db3d59e9ca3a1fd10ec5d5a/pkg/sql/sem/builtins/aggregate_builtins.go#L1839)):*
> ```Go
> 
> func newAggregatedStmtMetadataAggregate(
> 	p []*types.T, evalCtx *eval.Context, _ tree.Datums,
> ```

nit: if an argument is not used, give it `_` as the name.
___
*[`pkg/sql/sem/builtins/aggregate_builtins.go` line 1942 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119283#-NrCqg7184pOvv6sq8eQ:-NrCqg7184pOvv6sq8eR:baiynsn) ([raw file](https://github.com/cockroachdb/cockroach/blob/7638e11f430a667f6db3d59e9ca3a1fd10ec5d5a/pkg/sql/sem/builtins/aggregate_builtins.go#L1942)):*
> ```Go
> 	}
> 
> 	var other appstatspb.AggregatedStatementMetadata
> ```

It'd be good to check whether `other` escapes to heap. If so, then we should pass a pointer to a "scratch" `appstatspb.AggregatedStatementMetadata` as an argument to `mergeAggregatedMetadataHelper` to reduce the number of allocations. (Note how in the original code in the builtin we defined this `other` outside of the `for` loop - we could do the same by embedding it into the new aggregate function.)
___
*[`pkg/sql/sem/builtins/aggregate_builtins.go` line 1944 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119283#-NrCp07a7qNpu_mMXFou:-NrCp07a7qNpu_mMXFov:b-t77nx0) ([raw file](https://github.com/cockroachdb/cockroach/blob/7638e11f430a667f6db3d59e9ca3a1fd10ec5d5a/pkg/sql/sem/builtins/aggregate_builtins.go#L1944)):*
> ```Go
> 	var other appstatspb.AggregatedStatementMetadata
> 
> 	metadataJSON := tree.MustBeDJSON(datum).JSON
> ```

nit: to be conservative, use `AsDJSON` since `MustBeDJSON` might panic.
___
*[`pkg/sql/sem/builtins/aggregate_builtins.go` line 1950 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119283#-NrCpKpO965VseU3-YjK:-NrCpKpO965VseU3-YjL:bgphi68) ([raw file](https://github.com/cockroachdb/cockroach/blob/7638e11f430a667f6db3d59e9ca3a1fd10ec5d5a/pkg/sql/sem/builtins/aggregate_builtins.go#L1950)):*
> ```Go
> 		// Set the constant info only if they haven't yet been set.
> 		err = sqlstatsutil.DecodeAggregatedMetadataJSON(metadataJSON, &other)
> 		// elements then we can skip this as we are already at the zero values.
> ```

nit: this comment seems incomplete.
___
*[`pkg/sql/sem/builtins/aggregate_builtins.go` line 1962 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119283#-NrCps9G12I54NKOjN8C:-NrCps9G12I54NKOjN8D:b-ooltvr) ([raw file](https://github.com/cockroachdb/cockroach/blob/7638e11f430a667f6db3d59e9ca3a1fd10ec5d5a/pkg/sql/sem/builtins/aggregate_builtins.go#L1962)):*
> ```Go
> 	}
> 
> 	// Aggregate relevant stats.
> ```

nit: it's intentional that `FormattedQuery` and `FingerprintID` are not set, right? If so, consider adding a quick comment.
___
*[`pkg/sql/sem/builtins/aggregate_builtins.go` line 1964 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119283#-NrCqGUP1XP2hgQtS4O4:-NrCqGUP1XP2hgQtS4O5:b-fnke2z) ([raw file](https://github.com/cockroachdb/cockroach/blob/7638e11f430a667f6db3d59e9ca3a1fd10ec5d5a/pkg/sql/sem/builtins/aggregate_builtins.go#L1964)):*
> ```Go
> 	// Aggregate relevant stats.
> 	aggMetadata.Databases = util.CombineUnique(aggMetadata.Databases, other.Databases)
> 	aggMetadata.AppNames = util.CombineUnique(aggMetadata.AppNames, other.AppNames)
> ```

`AppNames` were previously unset in `crdb_internal.merge_aggregated_stmt_metadata` builtin - is including them here a bug fix? If so, it'd be good to extract it into a separate commit with a unit test.
___
*[`pkg/sql/logictest/testdata/logic_test/builtin_function` line 4071 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119283#-NrCrdiL6myV9UDprg76:-NrCrdiM-Yzb2Kyttjrx:b-ic6gri) ([raw file](https://github.com/cockroachdb/cockroach/blob/7638e11f430a667f6db3d59e9ca3a1fd10ec5d5a/pkg/sql/logictest/testdata/logic_test/builtin_function#L4071)):*
> ```
> SELECT crdb_internal.merge_aggregated_stmt_metadata(ARRAY[ '{ "db": [ "defaultdb", "tpcc" ], "distSQLCount": 1, "failedCount": 2, "fullScanCount": 0, "implicitTxn": true, "query": "SELECT 1", "querySummary": "SELECT 1", "stmtType": "TypeDML", "totalCount": 33, "vecCount": 0 }'::JSON, '{ "db": ["tpcc"], "distSQLCount": 23, "failedCount": 0, "fullScanCount": 99, "implicitTxn": true, "query": "SELECT 1", "querySummary": "SELECT 1", "stmtType": "TypeDML", "totalCount": 3, "vecCount": 2 }'::JSON, '{"hello": "world"}'::JSON ])
> ----
> {"appNames": [], "db": ["defaultdb", "tpcc"], "distSQLCount": 24, "failedCount": 2, "fingerprintID": "", "formattedQuery": "", "fullScanCount": 99, "implicitTxn": true, "query": "SELECT 1", "querySummary": "SELECT 1", "stmtType": "TypeDML", "totalCount": 36, "vecCount": 2}
> ```

Looks like there are some bug fixes here. I wonder whether it's because we now allocate fresh `other appstatspb.AggregatedStatementMetadata` (i.e. `other.Databases = nil` is insufficient - we should've done `other = appstatspb.AggregatedStatementMetadata{}`). It'd be nice to understand what exactly fixed the bug here and extract the fix into a separate commit.

**Review by xinhaoz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119283)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @yuzefovich)

___
*[`-- commits` line 22 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119283#-NrCsQTm9dFudjouCsi2):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: `crdb_internal.merge_aggregated_stmt_metadata` too.
</blockquote></details>

Including this in followup PR.
___
*[`-- commits` line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119283#-NrCtQDn5U7vzLcrTJXh):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

We might need to be careful with this change in mixed-version clusters. In particular, if the gateway node uses the new aggregate functions and the query gets distributed, the remote nodes might not be aware of such functions, so I'd expect the distributed query to error out. It would be nice to confirm this.

I wrote my understanding of the situation at the top of [this comment](https://github.com/cockroachdb/cockroach/pull/111303#pullrequestreview-1647448808) that introduced some of these aggregates originally. What allowed us to backport them safely was the fact that we only used new aggregates in write queries (INSERT, UPDATE, etc) which we cannot distribute, but your change adjusts read queries, so now we need to think whether these queries can get distributed, and if so, how to properly gate the rollout of this update.
</blockquote></details>

Thanks for catching this. I confirmed these queries will error when distributed on a mixed version cluster without the aggregate functions. I discussed with the team what our options are and we're going to pursue a separate measure for previous versions - https://github.com/cockroachdb/cockroach/issues/120443. I'm also separating the introduction of the new aggregate functions with the version gate with some mixed version testing. I believe the aggregate functions that are now being used in this PR were all backported to 23.1 so I think we can at least backport these changes to 23.2.
___
*[`pkg/sql/logictest/testdata/logic_test/builtin_function` line 4071 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119283#-NrCrdiL6myV9UDprg76:-NrLkSoD90VZcdflu4Pq:bdxik99) ([raw file](https://github.com/cockroachdb/cockroach/blob/7638e11f430a667f6db3d59e9ca3a1fd10ec5d5a/pkg/sql/logictest/testdata/logic_test/builtin_function#L4071)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Looks like there are some bug fixes here. I wonder whether it's because we now allocate fresh `other appstatspb.AggregatedStatementMetadata` (i.e. `other.Databases = nil` is insufficient - we should've done `other = appstatspb.AggregatedStatementMetadata{}`). It'd be nice to understand what exactly fixed the bug here and extract the fix into a separate commit.
</blockquote></details>

Filed - https://github.com/cockroachdb/cockroach/issues/119533.
___
*[`pkg/sql/sem/builtins/aggregate_builtins.go` line 1832 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119283#-NrCoGyk2Pa2pvvSDJq4:-NrMiOxIBVrWSxaOLvYh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7638e11f430a667f6db3d59e9ca3a1fd10ec5d5a/pkg/sql/sem/builtins/aggregate_builtins.go#L1832)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: both this new aggregate as well as existing `aggStatementMetadata` operate on `appstatspb.AggregatedStatementMetadata` - it'd be nice to highlight the differences between the two in the comments.
</blockquote></details>

Done.
___
*[`pkg/sql/sem/builtins/aggregate_builtins.go` line 1839 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119283#-NrCobPx3HvoYeGgsZT7:-NrLoXoeCyHKdacnigZt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7638e11f430a667f6db3d59e9ca3a1fd10ec5d5a/pkg/sql/sem/builtins/aggregate_builtins.go#L1839)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: if an argument is not used, give it `_` as the name.
</blockquote></details>

Done.
___
*[`pkg/sql/sem/builtins/aggregate_builtins.go` line 1942 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119283#-NrCqg7184pOvv6sq8eQ:-NrLspmTAnm32NQ1igEf:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/7638e11f430a667f6db3d59e9ca3a1fd10ec5d5a/pkg/sql/sem/builtins/aggregate_builtins.go#L1942)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

It'd be good to check whether `other` escapes to heap. If so, then we should pass a pointer to a "scratch" `appstatspb.AggregatedStatementMetadata` as an argument to `mergeAggregatedMetadataHelper` to reduce the number of allocations. (Note how in the original code in the builtin we defined this `other` outside of the `for` loop - we could do the same by embedding it into the new aggregate function.)
</blockquote></details>

Fixed.
___
*[`pkg/sql/sem/builtins/aggregate_builtins.go` line 1944 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119283#-NrCp07a7qNpu_mMXFou:-NrH7bCNEw1DTWm9drSj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7638e11f430a667f6db3d59e9ca3a1fd10ec5d5a/pkg/sql/sem/builtins/aggregate_builtins.go#L1944)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: to be conservative, use `AsDJSON` since `MustBeDJSON` might panic.
</blockquote></details>

Done.
___
*[`pkg/sql/sem/builtins/aggregate_builtins.go` line 1950 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119283#-NrCpKpO965VseU3-YjK:-NrHJEqw6aWjswDPvJK9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7638e11f430a667f6db3d59e9ca3a1fd10ec5d5a/pkg/sql/sem/builtins/aggregate_builtins.go#L1950)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: this comment seems incomplete.
</blockquote></details>

Done.
___
*[`pkg/sql/sem/builtins/aggregate_builtins.go` line 1962 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119283#-NrCps9G12I54NKOjN8C:-NrHJFsr1r19tQGSX8hD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7638e11f430a667f6db3d59e9ca3a1fd10ec5d5a/pkg/sql/sem/builtins/aggregate_builtins.go#L1962)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: it's intentional that `FormattedQuery` and `FingerprintID` are not set, right? If so, consider adding a quick comment.
</blockquote></details>

Done.
___
*[`pkg/sql/sem/builtins/aggregate_builtins.go` line 1964 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119283#-NrCqGUP1XP2hgQtS4O4:-NrHJHyZA_OHmvr75_xL:bj7j75w) ([raw file](https://github.com/cockroachdb/cockroach/blob/7638e11f430a667f6db3d59e9ca3a1fd10ec5d5a/pkg/sql/sem/builtins/aggregate_builtins.go#L1964)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

`AppNames` were previously unset in `crdb_internal.merge_aggregated_stmt_metadata` builtin - is including them here a bug fix? If so, it'd be good to extract it into a separate commit with a unit test.
</blockquote></details>

It was left out on purpose because for the use cases of this builtin, aggregating app names wasn't ever read - we only use this function to aggregate the metadata column for the activity tables, and it seemed as though `appNames` is always empty in that column.

I included it here since I regretted omitting it just for the reason above since it can lead to future bugs if it's assumed to aggregate all fields. LMK if you'd still like me to file a ticket for this though!

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 18 of 18 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119283#-:-NtIw-VXC9H4G8B32aI6:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @abarganier and @xinhaoz)

___
*[`-- commits` line 22 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119283#-NrCsQTm9dFudjouCsi2):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Including this in followup PR.
</blockquote></details>

Ack - then mention of `crdb_internal.merge_aggregated_stmt_metadata` should be removed from the commit message and the PR description.
___
*[`-- commits` line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119283#-NrCtQDn5U7vzLcrTJXh):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Thanks for catching this. I confirmed these queries will error when distributed on a mixed version cluster without the aggregate functions. I discussed with the team what our options are and we're going to pursue a separate measure for previous versions - https://github.com/cockroachdb/cockroach/issues/120443. I'm also separating the introduction of the new aggregate functions with the version gate with some mixed version testing. I believe the aggregate functions that are now being used in this PR were all backported to 23.1 so I think we can at least backport these changes to 23.2.
</blockquote></details>

Thanks, sounds good to me.

This means that backport-23.1 label should be removed, right?
___
*[`pkg/sql/sem/builtins/aggregate_builtins.go` line 1964 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119283#-NrCqGUP1XP2hgQtS4O4:-NtIva7aEtjwO-sleixZ:bfkian4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7638e11f430a667f6db3d59e9ca3a1fd10ec5d5a/pkg/sql/sem/builtins/aggregate_builtins.go#L1964)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

It was left out on purpose because for the use cases of this builtin, aggregating app names wasn't ever read - we only use this function to aggregate the metadata column for the activity tables, and it seemed as though `appNames` is always empty in that column.

I included it here since I regretted omitting it just for the reason above since it can lead to future bugs if it's assumed to aggregate all fields. LMK if you'd still like me to file a ticket for this though!
</blockquote></details>

SGTM, no need for an issue.

**Comment by xinhaoz** [comment]
TFTR! Commit msg updated and backport label for 23.1 removed.
bors r+

**Pull request merged**
