### PR TITLE
syntheticprivilegecache: scan all privileges at startup 

### LINKED ISSUE #93182: sql: leasing of virtual table privileges adds to latency on first use
**Describe the problem**
In 22.2 we added synthetic privileges which are used for things like external connections, and, critically, virtual tables. These privileges need to be checked when iterating through various system catalog schemas (`pg_catalog`, `information schema`, `SHOW TABLES`, ...).

We populate these caches lazily. 

**Describe the solution you'd like**
We could eagerly launch routines to populate these caches for the different virtual tables concurrently rather than serially.

**Describe alternatives you've considered**
We could do some sort of special initialization to preload data. These tables are almost always empty and are small when populated. We could scan it all and avoid the cost of all the parallel work.

Epic: CRDB-18596

Jira issue: CRDB-22207

### PR DESCRIPTION
**Pull request by ajwerner**
#### syntheticprivilegecache: move caching logic out of sql
This is a pure refactor to move the logic for caching synthetic privileges
from the sql package. This will make it easier to add features later.

#### syntheticprivilegecache: scan all privileges at startup 

Fixes https://github.com/cockroachdb/cockroach/issues/93182

This commit attempts to alleviate the pain caused by synthetic virtual table
privileges introduced in 22.2. We need to fetch privileges for virtual tables
to determine whether the user has access. This is done lazily. However, when a
user attempts to read a virtual table like pg_class or run SHOW TABLES it will
force the privileges to be determined for each virtual table (of which there
are 290 at the time of writing). This sequential process can be somewhat slow
in a single region cluster and will be very slow in an MR cluster.

This patch attempts to somewhat alleviate this pain by scanning the table
eagerly during server startup.

Release note (performance improvement): In 22.2 we introduced privileges on
virtual tables (system catalogs like pg_catalog, information_schema, and
crdb_internal). A problem with this new feature is that we now must fetch those
privileges into a cache before we can use those tables or determine their
visibility in other system catalogs. This process used to occur on-demand, when
the privilege was needed. Now we'll fetch these privileges eagerly during
startup to mitigate the latency when accessing pg_catalog right after the
server boots up.

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
feel free to merge if you do any of the nits

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93557#-:-NJGZ-jPDQC7fRwWH_YM:b-8qdyjl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[`pkg/sql/syntheticprivilegecache/accumulator.go` line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93557#-NJGLHHD1_LIjk0pmITh:-NJGLHHD1_LIjk0pmITi:b8hlj6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff32dbbde83b1e452dbbcc8bdc751a17d39990c4/pkg/sql/syntheticprivilegecache/accumulator.go#L21)):*
> ```Go
> )
> 
> // Accumulator accumulates different rows of system.privileges
> ```

nit: should be lower case
___
*[`pkg/sql/syntheticprivilegecache/cache.go` line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93557#-NJGMaon-HQ5G3Bl2dlh:-NJGMaon-HQ5G3Bl2dli:b-wwscfr) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff32dbbde83b1e452dbbcc8bdc751a17d39990c4/pkg/sql/syntheticprivilegecache/cache.go#L130)):*
> ```Go
> 		catconstants.SystemPrivilegeTableName,
> 	)
> 	// TODO(ajwerner): Use an internal executor bound to the transaction.
> ```

could we add a `sqlutil.InternalExecutor` as a parameter and pass `initInternalExecutor(ctx, p)` as the argument? i guess that's uglier?
___
*[`pkg/sql/syntheticprivilegecache/cache.go` line 98 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93557#-NJGLiMT-x76uPTuFyIm:-NJGLiMT-x76uPTuFyIn:b9gq1uk) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f590331159c1f0758a2fcc7a10d61644dc83041/pkg/sql/syntheticprivilegecache/cache.go#L98)):*
> ```Go
> 	// Before we launch a goroutine to go fetch this descriptor, make sure that
> 	// the logic to fetch all descriptors at startup has completed.
> 	if err := c.waitForWarmed(ctx); err != nil {
> ```

should this wait be before we call `getFromCache`?

**Comment by rafiss** [comment]
is the performance impact bad enough that we need to backport?

**Review by ajwerner — COMMENTED** [review]
> is the performance impact bad enough that we need to backport?

Yes. Added the tag. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93557#-:-NJGaphgA31NfoXoLhTU:bsj2r9a)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/syntheticprivilegecache/accumulator.go` line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93557#-NJGLHHD1_LIjk0pmITh:-NJGaoYK8Sg9IT4Xq8nF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff32dbbde83b1e452dbbcc8bdc751a17d39990c4/pkg/sql/syntheticprivilegecache/accumulator.go#L21)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: should be lower case
</blockquote></details>

Done.
___
*[`pkg/sql/syntheticprivilegecache/cache.go` line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93557#-NJGMaon-HQ5G3Bl2dlh:-NJGaLG16EIcbRW8on8p:bn3erw5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff32dbbde83b1e452dbbcc8bdc751a17d39990c4/pkg/sql/syntheticprivilegecache/cache.go#L130)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

could we add a `sqlutil.InternalExecutor` as a parameter and pass `initInternalExecutor(ctx, p)` as the argument? i guess that's uglier?
</blockquote></details>

All of this is going away very soon with https://github.com/cockroachdb/cockroach/pull/93218 which is why I left it.
___
*[`pkg/sql/syntheticprivilegecache/cache.go` line 98 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93557#-NJGLiMT-x76uPTuFyIm:-NJGaCr34SLbNk8ZTTQA:b-cp1m55) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f590331159c1f0758a2fcc7a10d61644dc83041/pkg/sql/syntheticprivilegecache/cache.go#L98)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

should this wait be before we call `getFromCache`?
</blockquote></details>

It could, but I don't think it matters. If we found something in the cache, then it was warmed.  I'd rather not have to check the channel in the common case.

**Review by ajwerner — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93557#-:-NJGb4GC2KVW6hcrSkYo:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

**Pull request merged**
