### PR TITLE
opt: inverted-index accelerate filters of the form j = ... and j IN (...)

### LINKED ISSUE #96658: opt: inverted-index accelerate filters of the form: `j = ...` and `j IN (...)`
An inverted index can be used to accelerate queries, using the `=` and the `IN` operator, with filters having the fetch value operator present; eg: `j->0  = '{"b": "c"}'` and `j->0 IN ('1', '2')` where j is a JSON column. This has been done completed here: #96471 and #94666. However, support has to be added to use inverted indexes for queries using the `IN` and the `=` operator *without* the fetch value operator (`->`), eg: `j = '{"b": "c"}'` and `j IN ('1', '2')`.

As a proposal for a solution, we could use inspiration from #96202 and #94666 in creating `JSON` objects and calling the required helpers for generating the inverted spans for scanning. 

Jira issue: CRDB-24268

### PR DESCRIPTION
**Pull request by Shivs11**
An inverted index can be used to accelerate queries, using the = and the IN operator, 
with filters having the fetch value operator present; 
`eg: j->0  = '{"b": "c"}'` and `j->0 IN ('1', '2')`

where j is a JSON column. 
This has been done completed here: #96471 and #94666

This PR aims to add support to generate inverted spans for queries not involving the 
fetch val operator and having the `=` operator or the `IN` operator. This was done by
creating JSON objects from the JSON values present on the right side of the equality or 
the IN expression. Moreover, in this case, no "keys" were extracted from the left hand 
side of the operators while creating these JSON objects which were useful for creating the 
inverted spans.

Epic: CRDB-3301

Fixes: #96658

Release note (performance improvement): The optimizer now plans
inverted index scans for queries that do not use the JSON fetch value operator (`->`) alongside 
the `IN` and the `=` operators. eg: `json_col = '{"b": "c"}'` OR `json_col IN ('"a"', '1')`

### CODE REVIEW

**Comment by rytaft** [comment]
This hasn't been reviewed yet. I think maybe you meant to bors the other PR?

**Comment by Shivs11** [comment]
> This hasn't been reviewed yet. I think maybe you meant to bors the other PR?

Ah my apologies. Changes have been made.

**Review by rytaft — APPROVED** [review]
:lgtm: Nice work!

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101178#-:-NSkx4tgAT9PS2U7TAIL:bcmw7ss)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @Shivs11)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101178#-NSktJwW08WDCLbyIPG_):*
I don't understand this last sentence
___
*[`pkg/sql/opt/invertedidx/json_array.go` line 591 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101178#-NSkv6wK1IhNLAlL1-RM:-NSkv6wK1IhNLAlL1-RN:b-15unfn) ([raw file](https://github.com/cockroachdb/cockroach/blob/f93a42e2ba21be35262bb5dacd130ec473570fa4/pkg/sql/opt/invertedidx/json_array.go#L591)):*
> ```Go
> 	// on which an inverted index is constructed. Other entries inside of this
> 	// index, such as JSON arrays and objects, may consist of the element 1 present
> 	// within them. Since the encodings inside the index do not contain the position
> ```

nit: "may consist of the element 1 present within them" sounds a bit convoluted. I'd change this to "may contain the element 1 along with other elements" or something like that.
___
*[`pkg/sql/logictest/testdata/logic_test/inverted_index` line 829 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101178#-NSkvZ755nsKpjREqRIq:-NSkvZ76EkOKU1r6r5gF:b67xpjn) ([raw file](https://github.com/cockroachdb/cockroach/blob/f93a42e2ba21be35262bb5dacd130ec473570fa4/pkg/sql/logictest/testdata/logic_test/inverted_index#L829)):*
> ```
> 
> query T
> SELECT j FROM f@i WHERE j = '{"a": "a"}' ORDER BY k
> ```

this is a duplicate of the one above it

**Review by Shivs11 — COMMENTED** [review]
Thank you for the review @rytaft !

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101178#-:-NSlHCd93gUWgzcGg6CO:b-d5jk3)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101178#-NSktJwW08WDCLbyIPG_):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I don't understand this last sentence
</blockquote></details>

Replaced this with the intended PR numbers.
___
*[`pkg/sql/opt/invertedidx/json_array.go` line 591 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101178#-NSkv6wK1IhNLAlL1-RM:-NSlGtxPCTrXLiXlLXHS:b-el989i) ([raw file](https://github.com/cockroachdb/cockroach/blob/f93a42e2ba21be35262bb5dacd130ec473570fa4/pkg/sql/opt/invertedidx/json_array.go#L591)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: "may consist of the element 1 present within them" sounds a bit convoluted. I'd change this to "may contain the element 1 along with other elements" or something like that.
</blockquote></details>

I agree. Done.
___
*[`pkg/sql/logictest/testdata/logic_test/inverted_index` line 829 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101178#-NSkvZ755nsKpjREqRIq:-NSlH5nf5uuhm-nTHL8E:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/f93a42e2ba21be35262bb5dacd130ec473570fa4/pkg/sql/logictest/testdata/logic_test/inverted_index#L829)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

this is a duplicate of the one above it
</blockquote></details>

Removed.

**Review by mgartner — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101178)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft and @Shivs11)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101178#-NSktJwW08WDCLbyIPG_):*
<details><summary><i>Previously, Shivs11 (Shivam) wrote…</i></summary><blockquote>

Replaced this with the intended PR numbers.
</blockquote></details>

Did you push your latest changes? The last sentence looks incomplete: "This has been completed here:"
___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101178#-NSlI_mf9IA4q-wQyDn1):*
nit: Should "and" be "or" here?
___
*[`-- commits` line 13 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101178#-NSlIhKM8deQVzaKIkxl):*
I don't understand this last sentence. Are you suggesting that keys from the LHS were useful in creating inverted spans previously, but no longer are useful? Or simply that there are not keys on the LHS?
___
*[`-- commits` line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101178#-NSlJ4qOEGYHwjK_EVOH):*
It's odd to write this with the negative perspective: "queries that do not use...". I think you can word it something like "for queries of this form..." to be less confusing.
___
*[`pkg/sql/opt/invertedidx/json_array.go` line 437 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101178#-NSlJmomDDVlD77uPGE4:-NSlJmomDDVlD77uPGE5:b-4xo7fi) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6b2eb67019ea763f79074a377e10be64a1e0d1/pkg/sql/opt/invertedidx/json_array.go#L437)):*
> ```Go
> 		fetch = false
> 	default:
> 		return nil
> ```

nit: I think you should return `inverted.NonInvertedColExpression` here to match the comment for the function and the rest of the function.
___
*[`pkg/sql/opt/invertedidx/json_array.go` line 562 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101178#-NSlJUk896-Nd8T7d3bl:-NSlJUk896-Nd8T7d3bm:b-gssw5e) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6b2eb67019ea763f79074a377e10be64a1e0d1/pkg/sql/opt/invertedidx/json_array.go#L562)):*
> ```Go
> }
> 
> // extractJSONFetchValEqCondition extracts an InvertedExpression representing an
> ```

nit: incorrect function name
___
*[`pkg/sql/opt/invertedidx/json_array.go` line 582 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101178#-NSlLD9R4lc51r51EDXG:-NSlLD9R4lc51r51EDXH:b-fijozt) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6b2eb67019ea763f79074a377e10be64a1e0d1/pkg/sql/opt/invertedidx/json_array.go#L582)):*
> ```Go
> 	// For Equals expressions, we will generate the inverted expression for the
> 	// single object built from the keys and val.
> 	invertedExpr := getInvertedExprForJSONOrArrayIndexForContaining(ctx, evalCtx, val)
> ```

See my comment in the tests - I'm skeptical that we can use `getInvertedExprForJSONOrArrayIndexForContaining` in this case.
___
*[`pkg/sql/opt/xform/testdata/rules/select` line 2808 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101178#-NSlLNIb9xVNq_HXrwnc:-NSlLNIb9xVNq_HXrwnd:bxnt29y) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6b2eb67019ea763f79074a377e10be64a1e0d1/pkg/sql/opt/xform/testdata/rules/select#L2808)):*
> ```
>       │         │    └── spans
>       │         │         ├── ["7\x00\x01\x00", "7\x00\x01\x00"]
>       │         │         └── ["7\x00\x03\x00\x01\x00", "7\x00\x03\x00\x01\x00"]
> ```

We should only have a single span here, right? AFAIK there's only one possible JSON path for the JSON value `1`. I think it's because we generating spans with `getInvertedExprForJSONOrArrayIndexForContaining`. "Containment" is different than "equality", and I believe it generates two spans to handle the case when the JSON value is an array containing the value `1`.
___
*[`pkg/sql/opt/invertedidx/json_array_test.go` line 1089 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101178#-NSlM5I1E64BiONeqt-h:-NSlM5I1E64BiONeqt-i:b-vjf2l0) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6b2eb67019ea763f79074a377e10be64a1e0d1/pkg/sql/opt/invertedidx/json_array_test.go#L1089)):*
> ```Go
> 			ok:               true,
> 			tight:            false,
> 			unique:           false,
> ```

Ideally, this should be `unique=true`, correct? Is it possible for the generated spans to scan two entries with the same PK? I don't think it should be, but maybe it's due to the use of "containment" spans not "equality" spans (see my other comments).

**Review by Shivs11 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101178)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101178#-NSktJwW08WDCLbyIPG_):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Did you push your latest changes? The last sentence looks incomplete: "This has been completed here:"
</blockquote></details>

For some reason the PR numbers were not showing up on the log message. This has been fixed and the issue was about line wrapping the text to 72 columns.
___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101178#-NSlI_mf9IA4q-wQyDn1):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: Should "and" be "or" here?
</blockquote></details>

I believe "and". The current PR adds support in two separate cases.
___
*[`-- commits` line 13 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101178#-NSlIhKM8deQVzaKIkxl):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I don't understand this last sentence. Are you suggesting that keys from the LHS were useful in creating inverted spans previously, but no longer are useful? Or simply that there are not keys on the LHS?
</blockquote></details>

What I meant is the following: keys from the LHS were useful in creating inverted spans previously, but no longer are useful since there are none present this time around. Shall rephrase this, thank you.
___
*[`-- commits` line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101178#-NSlJ4qOEGYHwjK_EVOH):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

It's odd to write this with the negative perspective: "queries that do not use...". I think you can word it something like "for queries of this form..." to be less confusing.
</blockquote></details>

Sure. Changes have been made.
___
*[`pkg/sql/opt/invertedidx/json_array.go` line 437 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101178#-NSlJmomDDVlD77uPGE4:-NSlUMLF7R2ZFio4jtrS:bqw59g7) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6b2eb67019ea763f79074a377e10be64a1e0d1/pkg/sql/opt/invertedidx/json_array.go#L437)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: I think you should return `inverted.NonInvertedColExpression` here to match the comment for the function and the rest of the function.
</blockquote></details>

Hmm, okay. Changed.
___
*[`pkg/sql/opt/invertedidx/json_array.go` line 562 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101178#-NSlJUk896-Nd8T7d3bl:-NSlUO5n54xHp7awunZA:b-eapff3) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6b2eb67019ea763f79074a377e10be64a1e0d1/pkg/sql/opt/invertedidx/json_array.go#L562)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: incorrect function name
</blockquote></details>

Resolved.
___
*[`pkg/sql/opt/invertedidx/json_array.go` line 582 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101178#-NSlLD9R4lc51r51EDXG:-NSmG6QSAfgJkYcfPmwL:b-eapff3) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6b2eb67019ea763f79074a377e10be64a1e0d1/pkg/sql/opt/invertedidx/json_array.go#L582)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

See my comment in the tests - I'm skeptical that we can use `getInvertedExprForJSONOrArrayIndexForContaining` in this case.
</blockquote></details>

Resolved.
___
*[`pkg/sql/opt/xform/testdata/rules/select` line 2808 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101178#-NSlLNIb9xVNq_HXrwnc:-NSlVCpO6ZJiSTILiTY3:b-gxfnql) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6b2eb67019ea763f79074a377e10be64a1e0d1/pkg/sql/opt/xform/testdata/rules/select#L2808)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

We should only have a single span here, right? AFAIK there's only one possible JSON path for the JSON value `1`. I think it's because we generating spans with `getInvertedExprForJSONOrArrayIndexForContaining`. "Containment" is different than "equality", and I believe it generates two spans to handle the case when the JSON value is an array containing the value `1`.
</blockquote></details>

Was resolved offline. The decision, for now, is to use the function `getInvertedExprForJSONOrArrayIndexForContaining` even though it is not the most optimum solution.
___
*[`pkg/sql/opt/invertedidx/json_array_test.go` line 1089 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101178#-NSlM5I1E64BiONeqt-h:-NSlXC978iFPXf873p9D:b-xdgj1q) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6b2eb67019ea763f79074a377e10be64a1e0d1/pkg/sql/opt/invertedidx/json_array_test.go#L1089)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Ideally, this should be `unique=true`, correct? Is it possible for the generated spans to scan two entries with the same PK? I don't think it should be, but maybe it's due to the use of "containment" spans not "equality" spans (see my other comments).
</blockquote></details>

Resolved offline.

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101178)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 5 files at r1, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101178#-:-NSv6bLIAPQarc73GKIq:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @Shivs11)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101178#-NSktJwW08WDCLbyIPG_):*
<details><summary><i>Previously, Shivs11 (Shivam) wrote…</i></summary><blockquote>

For some reason the PR numbers were not showing up on the log message. This has been fixed and the issue was about line wrapping the text to 72 columns.
</blockquote></details>

I see. In a git commit message the `#` character at the beginning of a line denotes a comment, so you have to be careful with `#123` to issues and PRs.
___
*[`pkg/sql/opt/xform/testdata/rules/select` line 2808 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101178#-NSlLNIb9xVNq_HXrwnc:-NSv6Y011DrTqaC9u1vk:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/de6b2eb67019ea763f79074a377e10be64a1e0d1/pkg/sql/opt/xform/testdata/rules/select#L2808)):*
<details><summary><i>Previously, Shivs11 (Shivam) wrote…</i></summary><blockquote>

Was resolved offline. The decision, for now, is to use the function `getInvertedExprForJSONOrArrayIndexForContaining` even though it is not the most optimum solution.
</blockquote></details>

:+1: 
___
*[`pkg/sql/opt/xform/testdata/rules/select` line 2785 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/101178#-NSv6UNTCMC2wVYbX6-Z:-NSv6UNTCMC2wVYbX6-_:b-6mq056) ([raw file](https://github.com/cockroachdb/cockroach/blob/a09ddc85a617b6eb65642298fa7bb0526defa086/pkg/sql/opt/xform/testdata/rules/select#L2785)):*
> ```
> # applied again.
> ```

nit: remove extra new line

**Review by Shivs11 — COMMENTED** [review]
Thank you for your review! @mgartner 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101178#-:-NSwLMQU39EDn-_eU-Un:b-1bqmqp)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

**Pull request merged**
