### PR TITLE
roachtest: retire `bank` tests

### LINKED ISSUE #53871: roachtest: acceptance/bank/zerosum-restart failed [skipped]
[(roachtest).acceptance/bank/zerosum-restart failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2243461&tab=buildLog) on [master@b1244847e59bec9fe8cdb15f6b0830591c2b8030](https://github.com/cockroachdb/cockroach/commits/b1244847e59bec9fe8cdb15f6b0830591c2b8030):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: artifacts/acceptance/bank/zerosum-restart/run_1
	bank.go:354,bank.go:548,acceptance.go:91,test_runner.go:754: pq: cannot up-replicate to s3; missing gossiped StoreDescriptor

	test_runner.go:801: test timed out (10m0s)

```

<details><summary>More</summary><p>

Artifacts: [/acceptance/bank/zerosum-restart](https://teamcity.cockroachdb.com/viewLog.html?buildId=2243461&tab=artifacts#/acceptance/bank/zerosum-restart)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Aacceptance%2Fbank%2Fzerosum-restart.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #62749: roachtest: acceptance/bank/zerosum-splits failed [skipped]
Unclear why it's skipped; there's a tumultuous history for the test. Last failure I think was #53829 and the test was most recently skipped in #53833.

### PR DESCRIPTION
**Pull request by tbg**
The `bank` roachtests are a basic form of Jepsen test. We were hoping
that they could provide additional benefit due to being less complex
than a full Jepsen test. In my opinion, this calculus has not worked
out. We've spent many hours staring at this test deadlocked when it
wasn't CockroachDB's fault at all. Besides, it's not adding anything
meaningful on top of our Jepsen tests plus KVNemesis plus the TPCC
invariant checks, so we are removing the `bank` family of tests here.

Should we want to reintroduce these tests, we should do it at the level
of TestCluster, or at least augment the `bank` workload to incorporate
these invariant checks instead.

Closes #62754.
Closes #62749
Closes #53871.

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
Opened this when I ran into https://teamcity.cockroachdb.com/viewLog.html?buildId=2846442&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_Roachtest, which I think is fixed in #62754, but I really do think these tests are not worth salvaging in their current form.

**Review by andreimatei — COMMENTED** [review]
I agree with deleting these tests.
They have nothing to do with `workload run bank`, right? That workload seems used by other tests, and so it stays, right?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63073#-:-MXXuVci0Htvj-SHt5Ty:b-cecvqh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Comment by tbg** [comment]
Yep, these share a name but no code. workload/bank and the associated
roachtests remain.

**Comment by andreimatei** [comment]
:LGTM:

**Review by nvb — APPROVED** [review]
:lgtm: 

> Should we want to reintroduce these tests, we should do it at the level
> of TestCluster, or at least augment the `bank` workload to incorporate
> these invariant checks instead.

Do you think that we'll want to reintroduce these tests? If so, let's file an issue so they're not forgotten forever. Or we can just part ways here.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63073#-:-MXYWgbg2mHIRtGVQaT_:b-h3mqaq)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @tbg)

**Comment by tbg** [comment]
> Do you think that we'll want to reintroduce these tests? If so, let's file an issue so they're not forgotten forever. Or we can just part ways here.

I think it's parting ways. The issue would say "tests with invariants are good! We should test with invariants". That isn't actionable.

TFTR!

bors r=nvanbenschoten,andreimatei

**Comment by otan** [comment]
bors r-

i think this is causing
```

=== RUN   TestLint/TestStaticCheck
    lint_test.go:1665: 
        pkg/cmd/roachtest/cluster.go:2128:19: func (*cluster).Restart is unused (U1001)
    --- FAIL: TestLint/TestStaticCheck (553.45s)
```

**Comment by tbg** [comment]
Thanks Oliver!

bors r=nvanbenschoten,andreimatei

**Comment by tbg** [comment]
bors r=nvanbenschoten,andreimatei

**Comment by tbg** [comment]
bors r-

wait how did I screw it up again?

**Comment by tbg** [comment]
bors r=nvanbenschoten,andreimatei

**Comment by tbg** [comment]
bors single on

**Pull request merged**
