### PR TITLE
schemachanger: Enable ALTER PRIMARY KEY USING HASH

### LINKED ISSUE #96730: schemachanger: Support `ALTER PRIMARY KEY USING HASH`
Now that we supported adding/dropping constraints, we can support `ALTER PRIMARY KEY USING HASH`.
Its requirement will be similar to `CREATE INDEX USING HASH`.

Jira issue: CRDB-24678

### PR DESCRIPTION
**Pull request by Xiang-Gu**
We enable ALTER PRIMARY KEY USING HASH in the declarative schema changer. This commit also cleaned up some common logic to be re-used with CREATE INDEX ... USING HASH.

Note that we still fallback to legacy schema changer if the old primary key is on the implicit `rowid` column, because we don't support `ADD COLUMN, DROP COLUMN` in one statement yet (adding a shard column and dropping the `rowid` column).

Fixes: #96730
Epic: None

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
Can you make an end_to_end test for this case?

**Comment by Xiang-Gu** [comment]
@ajwerner I added an end_to_end test and made several other changes to pass CI. I think it's ready for another look!

**Review by ajwerner — APPROVED** [review]
LGTM

**Comment by Xiang-Gu** [comment]
TFTR

bors r+

**Comment by renatolabs** [comment]
bors r-

Test introduced here is failing the bors builds, please take a look.

**Comment by Xiang-Gu** [comment]
So I refactored how we quickly determine whether a statement is not supported, given mode and cluster version, before entering the builder, hoping to "fail fast" and thus avoid round-trips. All such check logic now live in the `checks` field of the stmt-support-map. The code is much cleaner now. 
It's ready for another look!

**Review by fqazi — APPROVED** [review]
:lgtm: 

One minor thing may be document the hoisting part at the top level function

> Reviewed 40 of 40 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97820#-:-NQRsgiaE3r9DupRZZHd:b1rxl9z)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Xiang-Gu)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go` line 88 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97820#-NQRryff4GrhE3MHDv59:-NQRryff4GrhE3MHDv5A:b-q398t9) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a202fbd95f847f6078e2c17ba9f48c5a86528c9/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go#L88)):*
> ```Go
> 	// For ALTER TABLE stmt, we will need to further check whether each
> 	// individual command is fully supported.
> 	n.HoistAddColumnConstraints(func() {
> ```

I think this is fine, though one side effect is that the tree will get modified. Might be worth highlighting the top-level function
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go` line 89 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97820#-NQRsHWXEf8cIgQ-T6gl:-NQRsHWXEf8cIgQ-T6gm:b-niuqv2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a202fbd95f847f6078e2c17ba9f48c5a86528c9/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go#L89)):*
> ```Go
> 	// individual command is fully supported.
> 	n.HoistAddColumnConstraints(func() {
> 		telemetry.Inc(sqltelemetry.SchemaChangeAlterCounterWithExtra("table", "add_column.references"))
> ```

Think this is an interesting side effect but fine, since it should only be the build phase.

**Review by Xiang-Gu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97820)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go` line 88 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97820#-NQRryff4GrhE3MHDv59:-NQS6lL7-D_krHMffL_M:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a202fbd95f847f6078e2c17ba9f48c5a86528c9/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go#L88)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

I think this is fine, though one side effect is that the tree will get modified. Might be worth highlighting the top-level function
</blockquote></details>

Done.



_Code quote:_
```Go
n.HoistAddColumnConstraints(func() {
```
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go` line 89 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97820#-NQRsHWXEf8cIgQ-T6gl:-NQS6ld5-NoRZR79CJ51:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a202fbd95f847f6078e2c17ba9f48c5a86528c9/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go#L89)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Think this is an interesting side effect but fine, since it should only be the build phase.
</blockquote></details>

Done.

**Comment by Xiang-Gu** [comment]
TFTR!

bors r+

**Pull request merged**
