### PR TITLE
kv: typo in TestApplyPaginatedCommittedEntries

### LINKED ISSUE #57213: kv: typo in TestApplyPaginatedCommittedEntries
**Describe the problem**
found a bug in pkg/kv/kvserver/replica_test  
line 9368
Please describe the issue you observed, and any steps we can take to reproduce it:
`ch, _, _, pErr = repl.evalAndPropose(ctx, &ba, allSpansGuard(), &exLease)`

To Fix:
replace 'ba' with 'ba2'
The Final code:
'ch, _, _, pErr = repl.evalAndPropose(ctx, &ba2, allSpansGuard(), &exLease)'

### PR DESCRIPTION
**Pull request by benlatern**
Fixes #57213.

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Looks good to me, thanks @benlatern!

The next step to get this merged is to [sign the CLA](https://github.com/cockroachdb/cockroach/pull/57284#issuecomment-736349080). Do you mind doing that and pinging this issue afterwards?

**Comment by benlatern** [comment]
Hi @nvanbenschoten,i have signed the CLA.

**Comment by nvanbenschoten** [comment]
Thanks! I'll queue this to be merged.

bors r+

**Comment by SWDevAngel** [comment]
@benlatern Thank you for contributing to CockroachDB this year. As a token of our appreciation we would like to send you a gift. Please DM me on our [community Slack](https://cockroa.ch/slack) `@lisa` so I can send you a link. (If you don’t want a gift, we also have a charitable contribution choice.) All orders need to be in by December 13, so please send this asap. :)

**Comment by SWDevAngel** [comment]
@benlatern LAST DAY TO ORDER!!! 
Thank you for contributing to CockroachDB this year. As a token of our appreciation we would like to send you a gift while supplies last. We tried to reach you via GitHub or on email, but if you didn’t see the message please DM me on our [community Slack](https://cockroa.ch/slack) `@lisa` so I can send you a link to order your gift. (If you don’t want a gift, we also have a charitable contribution choice.) All orders must be in by December 13 (that’s tomorrow!), so please send this asap. :)

**Comment by benlatern** [comment]
so how can I get the link?

**Pull request merged**
