### PR TITLE
tree: remove roachpb references

### PR DESCRIPTION
**Pull request by otan**
See individual commits for details.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, 2 of 2 files at r2, 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80684)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @msbutler, and @otan)

___
*[`pkg/sql/sem/tree/tenant.go` line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80684#-N0icnIQC2LOC08p9Brd:-N0icnIR1lckksPAMI6q:bpvi1qi) ([raw file](https://github.com/cockroachdb/cockroach/blob/43bead783ae3525229ebd3b3dbf90ec8e639648c/pkg/sql/sem/tree/tenant.go#L29)):*
> ```Go
> 	// TODO(knz): None of this complexity would be needed if the tenant
> 	// ID was specified using an Expr here. This can be removed once the
> 	// backup target syntax accepts expressions for tenant targets.
> ```

this comment is pretty stale now given we really actively rely on `Specified` and it's not "extra complexity"



_Code quote:_
```Go
	// Specified is set to true when the TENANT clause was specified in
	// the backup target input syntax. We need this, instead of relying
	// on TenantID.IsSet(), because we need a special marker for
	// the case when the value was anonymized. In other places, the
	// value used for anonymized integer literals is 0, but we can't use
	// 0 for TenantID as this is refused during parsing, nor can we use
	// any other value since all non-zero integers are valid tenant IDs.
	//
	// TODO(knz): None of this complexity would be needed if the tenant
	// ID was specified using an Expr here. This can be removed once the
	// backup target syntax accepts expressions for tenant targets.
```
___
*[`pkg/sql/sem/tree/tenant.go` line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80684#-N0icu-W47mvdLxcWQFX:-N0icu-W47mvdLxcWQFY:bk48zcx) ([raw file](https://github.com/cockroachdb/cockroach/blob/43bead783ae3525229ebd3b3dbf90ec8e639648c/pkg/sql/sem/tree/tenant.go#L37)):*
> ```Go
> // IsSet returns whether the TenantID is set.
> func (t *TenantID) IsSet() bool {
> 	return t.ID != 0
> ```

:/ See the above comment, I think we instead need to look at Specified in some cases?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80684)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @msbutler)

___
*[`pkg/sql/sem/tree/tenant.go` line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80684#-N0icnIQC2LOC08p9Brd:-N0ihymhCe7n6byKccLU:bwwjew3) ([raw file](https://github.com/cockroachdb/cockroach/blob/43bead783ae3525229ebd3b3dbf90ec8e639648c/pkg/sql/sem/tree/tenant.go#L29)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

this comment is pretty stale now given we really actively rely on `Specified` and it's not "extra complexity"
</blockquote></details>

i've removed the TODO
___
*[`pkg/sql/sem/tree/tenant.go` line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80684#-N0icu-W47mvdLxcWQFX:-N0ihq3--h5vVIHXPr5B:b88gblq) ([raw file](https://github.com/cockroachdb/cockroach/blob/43bead783ae3525229ebd3b3dbf90ec8e639648c/pkg/sql/sem/tree/tenant.go#L37)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

:/ See the above comment, I think we instead need to look at Specified in some cases?
</blockquote></details>

i was just basing this on old logic (it fell to roachpb.TenantID.IsSet). Happy to chuck in a `t.Specified` here as well.

**Comment by otan** [comment]
had to drop the last commit for now

```
$ bazel query 'somepath(//pkg/sql/sem/tree:tree, //pkg/roachpb:roachpb)'
//pkg/sql/sem/tree:tree
//pkg/security:security
//pkg/clusterversion:clusterversion
//pkg/roachpb:roachpb
```

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 11 files at r5, 2 of 2 files at r6, 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80684#-:-N0polFJ8xZH7f0FvRmH:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msbutler)

**Review by irfansharif — COMMENTED** [review]
Looks like the PR was able to break the dependency between pkg/sql/parser and pkg/roachpb; so we can remove this fellow: 

https://github.com/cockroachdb/cockroach/blob/e0ec89999bf13c00a4fe58acd59f0ebdf8e043f6/pkg/sql/parser/BUILD.bazel#L25

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80684#-:-N0pz1ZM-3ROiWkXWcIj:b-fyb4wv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msbutler)

**Comment by otan** [comment]
There is still a path to roachpb indirectly but Andrew is removing that.

**Comment by otan** [comment]
bors r=ajwerner

**Comment by otan** [comment]
bors r=ajwerner

**Pull request merged**
