### PR TITLE
workload: enable interleaves when necessary

### LINKED ISSUE #59338: roachtest: sqlsmith using deprecated interleaved tables
[(roachtest).sqlsmith/setup=rand-tables/setting=no-mutations failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2607609&tab=buildLog) on [master@7a5d3d0f9465c4d6a6f204ac6a672a027cf585a6](https://github.com/cockroachdb/cockroach/commits/7a5d3d0f9465c4d6a6f204ac6a672a027cf585a6):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/sqlsmith/setup=rand-tables/setting=no-mutations/run_1
	sqlsmith.go:105,sqlsmith.go:228,test_runner.go:767: pq: interleaved tables and interleaved indexes are disabled due to the sql.defaults.interleaved_tables.enabled cluster setting. Note that interleaved tables and interleaved indexes will be removed in a future release. For details, see https://www.cockroachlabs.com/docs/releases/v20.2.0#deprecations

```

<details><summary>More</summary><p>

Artifacts: [/sqlsmith/setup=rand-tables/setting=no-mutations](https://teamcity.cockroachdb.com/viewLog.html?buildId=2607609&tab=artifacts#/sqlsmith/setup=rand-tables/setting=no-mutations)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Asqlsmith%2Fsetup%3Drand-tables%2Fsetting%3Dno-mutations.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #59343: roachtest: interleavedpartitioned failed
[(roachtest).interleavedpartitioned failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2607609&tab=buildLog) on [master@7a5d3d0f9465c4d6a6f204ac6a672a027cf585a6](https://github.com/cockroachdb/cockroach/commits/7a5d3d0f9465c4d6a6f204ac6a672a027cf585a6):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/interleavedpartitioned/run_1
	cluster.go:2253,interleavedpartitioned.go:67,interleavedpartitioned.go:125,test_runner.go:767: output in run_095151.572_n5_workload_init_interleavedpartitioned: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-2607609-1611387508-37-n12cpu4-geo:5 -- ./workload init interleavedpartitioned --east-zone-name europe-west2-b --west-zone-name us-west1-b --central-zone-name us-east1-b --drop --locality east --init-sessions 1000 returned: exit status 20
		(1) attached stack trace
		  -- stack trace:
		  | main.(*cluster).RunE
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2331
		  | main.(*cluster).Run
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2251
		  | main.registerInterleaved.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/interleavedpartitioned.go:67
		  | main.registerInterleaved.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/interleavedpartitioned.go:125
		  | main.(*testRunner).runTest.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:767
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1374
		Wraps: (2) output in run_095151.572_n5_workload_init_interleavedpartitioned
		Wraps: (3) /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-2607609-1611387508-37-n12cpu4-geo:5 -- ./workload init interleavedpartitioned --east-zone-name europe-west2-b --west-zone-name us-west1-b --central-zone-name us-east1-b --drop --locality east --init-sessions 1000 returned
		  | stderr:
		  | Error: could not create table: customers: pq: interleaved tables and interleaved indexes are disabled due to the sql.defaults.interleaved_tables.enabled cluster setting. Note that interleaved tables and interleaved indexes will be removed in a future release. For details, see https://www.cockroachlabs.com/docs/releases/v20.2.0#deprecations
		  | Error: COMMAND_PROBLEM: exit status 1
		  | (1) COMMAND_PROBLEM
		  | Wraps: (2) Node 5. Command with error:
		  |   | ```
		  |   | ./workload init interleavedpartitioned --east-zone-name europe-west2-b --west-zone-name us-west1-b --central-zone-name us-east1-b --drop --locality east --init-sessions 1000
		  |   | ```
		  | Wraps: (3) exit status 1
		  | Error types: (1) errors.Cmd (2) *hintdetail.withDetail (3) *exec.ExitError
		  |
		  | stdout:
		Wraps: (4) exit status 20
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *main.withCommandDetails (4) *exec.ExitError

```

<details><summary>More</summary><p>

Artifacts: [/interleavedpartitioned](https://teamcity.cockroachdb.com/viewLog.html?buildId=2607609&tab=artifacts#/interleavedpartitioned)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Ainterleavedpartitioned.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #59348: roachtest: roachmart/partition=true failed
[(roachtest).roachmart/partition=true failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2607609&tab=buildLog) on [master@7a5d3d0f9465c4d6a6f204ac6a672a027cf585a6](https://github.com/cockroachdb/cockroach/commits/7a5d3d0f9465c4d6a6f204ac6a672a027cf585a6):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/roachmart/partition=true/run_1
	roachmart.go:43,roachmart.go:47,roachmart.go:71,test_runner.go:767: output in run_120747.027_n1_workload_init_roachmart: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-2607609-1611387508-63-n9cpu4-geo:1 -- ./workload init roachmart --local-zone=us-central1-b --local-percent=90 --users=10 --orders=100 --partition=true returned: exit status 20
		(1) attached stack trace
		  -- stack trace:
		  | main.(*cluster).RunE
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2331
		  | main.registerRoachmart.func1.1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/roachmart.go:42
		  | main.registerRoachmart.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/roachmart.go:47
		  | main.registerRoachmart.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/roachmart.go:71
		  | main.(*testRunner).runTest.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:767
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1374
		Wraps: (2) output in run_120747.027_n1_workload_init_roachmart
		Wraps: (3) /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-2607609-1611387508-63-n9cpu4-geo:1 -- ./workload init roachmart --local-zone=us-central1-b --local-percent=90 --users=10 --orders=100 --partition=true returned
		  | stderr:
		  | Error: could not create table: orders: pq: interleaved tables and interleaved indexes are disabled due to the sql.defaults.interleaved_tables.enabled cluster setting. Note that interleaved tables and interleaved indexes will be removed in a future release. For details, see https://www.cockroachlabs.com/docs/releases/v20.2.0#deprecations
		  | Error: COMMAND_PROBLEM: exit status 1
		  | (1) COMMAND_PROBLEM
		  | Wraps: (2) Node 1. Command with error:
		  |   | ```
		  |   | ./workload init roachmart --local-zone=us-central1-b --local-percent=90 --users=10 --orders=100 --partition=true
		  |   | ```
		  | Wraps: (3) exit status 1
		  | Error types: (1) errors.Cmd (2) *hintdetail.withDetail (3) *exec.ExitError
		  |
		  | stdout:
		Wraps: (4) exit status 20
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *main.withCommandDetails (4) *exec.ExitError

```

<details><summary>More</summary><p>

Artifacts: [/roachmart/partition=true](https://teamcity.cockroachdb.com/viewLog.html?buildId=2607609&tab=artifacts#/roachmart/partition=true)
Related:
- #51759 roachtest: roachmart/partition=true failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Aroachmart%2Fpartition%3Dtrue.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### LINKED ISSUE #59349: roachtest: roachmart/partition=false failed
[(roachtest).roachmart/partition=false failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2607609&tab=buildLog) on [master@7a5d3d0f9465c4d6a6f204ac6a672a027cf585a6](https://github.com/cockroachdb/cockroach/commits/7a5d3d0f9465c4d6a6f204ac6a672a027cf585a6):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/roachmart/partition=false/run_1
	roachmart.go:43,roachmart.go:47,roachmart.go:71,test_runner.go:767: output in run_120802.934_n1_workload_init_roachmart: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-2607609-1611387508-62-n9cpu4-geo:1 -- ./workload init roachmart --local-zone=us-central1-b --local-percent=90 --users=10 --orders=100 --partition=false returned: exit status 20
		(1) attached stack trace
		  -- stack trace:
		  | main.(*cluster).RunE
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2331
		  | main.registerRoachmart.func1.1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/roachmart.go:42
		  | main.registerRoachmart.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/roachmart.go:47
		  | main.registerRoachmart.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/roachmart.go:71
		  | main.(*testRunner).runTest.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:767
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1374
		Wraps: (2) output in run_120802.934_n1_workload_init_roachmart
		Wraps: (3) /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-2607609-1611387508-62-n9cpu4-geo:1 -- ./workload init roachmart --local-zone=us-central1-b --local-percent=90 --users=10 --orders=100 --partition=false returned
		  | stderr:
		  | Error: could not create table: orders: pq: interleaved tables and interleaved indexes are disabled due to the sql.defaults.interleaved_tables.enabled cluster setting. Note that interleaved tables and interleaved indexes will be removed in a future release. For details, see https://www.cockroachlabs.com/docs/releases/v20.2.0#deprecations
		  | Error: COMMAND_PROBLEM: exit status 1
		  | (1) COMMAND_PROBLEM
		  | Wraps: (2) Node 1. Command with error:
		  |   | ```
		  |   | ./workload init roachmart --local-zone=us-central1-b --local-percent=90 --users=10 --orders=100 --partition=false
		  |   | ```
		  | Wraps: (3) exit status 1
		  | Error types: (1) errors.Cmd (2) *hintdetail.withDetail (3) *exec.ExitError
		  |
		  | stdout:
		Wraps: (4) exit status 20
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *main.withCommandDetails (4) *exec.ExitError

```

<details><summary>More</summary><p>

Artifacts: [/roachmart/partition=false](https://teamcity.cockroachdb.com/viewLog.html?buildId=2607609&tab=artifacts#/roachmart/partition=false)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Aroachmart%2Fpartition%3Dfalse.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by jordanlewis**
Fixes #59338.
Fixes #59348.
Fixes #59349.
Fixes #59343.

Release note: None

### CODE REVIEW

**Review by asubiotto — COMMENTED** [review]
Are these tests versioned at all? If not, we might have to put these lines behind a version check.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59380#-:-MRuFE9N6_wIZ-XAo6UH:b-x3rsmt)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by jordanlewis** [comment]
I'm not sure how to check the version in a workload. So I just ignored the set cluster setting errors. I

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59380#-:-MRy6UQZ6WhtzjLXuElx:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by thoszhang — APPROVED** [review]
We do build `workload` from the respective branches, not from master, so I don't think you should expect an error. The only exception might be mixed-version tests, but it doesn't look like we have any with interleaved tables.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59380#-:-MS0AGiy2D-KjZO3f8rQ:bid58ev)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by thoszhang — CHANGES_REQUESTED** [review]
I meant to request changes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59380#-:-MS0B1Is0m96CxQ_uyW9:blmugms)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by jordanlewis** [comment]
Okay, reverted to the original patch.

TFTR

bors r+

**Pull request merged**
