### PR TITLE
storage/gc: create gc pkg, reverse iteration in rditer, paginate versions during GC

### LINKED ISSUE #42531: OOM occurred while running replica GC old version
**Describe the problem**

cockroach data node crash due to OOM when a replica running GC.

**To Reproduce**

What did you do? Describe in your own words.
I load data to a table(load like batch insert a large number of rows ) which has auto-increment, after 25hours later, the replica running GC old version for the table, but there are too many version, and when running GC we copy all version into memory. I known auto-increment is not recommended in cockroach, but I think it is a bug.

And I found another problem, when a key has to many version to GC(more than 256KB), it will Increase normal read and write request latency in  that key since the latch.

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster ...
2. Send SQL ... / CLI command ...
3. Look at UI / log file / client app ...

**Expected behavior**

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version [e.g. 2.0.x]
 - Server OS: [e.g. Linux/Distrib]
 - Client app [e.g. `cockroach sql`, JDBC, ...]

**Additional context**
What was the impact?

### PR DESCRIPTION
**Pull request by ajwerner**
This PR comes in 6 commits. See the commit messages for more details. The meat of the change is in: `storage: rework RunGC so it no longer buffers keys and values in memory`.

1) Fix the spanset Iterator such that SeekLT can seek to the end of the range.
2) Expose reverse iteration in rditer.ReplicaDataIterator.
3) Rearrange some code in gc_queue.go to put the RunGC() helpers below that function.
4) Remove lockableGCInfo because there was no need for it.
5) Move RunGC into a `gc` subpackage.
5) Rework RunGC to paginate versions of keys with reverse iteration.

Fixes #42531.

### CODE REVIEW

**Comment by ajwerner** [comment]
The last commit needs more testing and probably a benchmark but I wanted to put it up early because I suspect it's going to be at least a little bit controversial. On the whole I feel that it makes the code easier to read but I'd like some confirmation of that feeling.

**Comment by ajwerner** [comment]
Hey @tbg I hear you're coming back soon. This PR is certainly not ready to merge but I'd appreciate if you could give the 5th commit a look to judge the basic approach. I want to make sure the structure is reasonable before I invest in the testing and benchmarking to get this over the finish line.

**Review by tbg — COMMENTED** [review]
Glad to have you in this area of the code! The changes look very good. I'm not too worried that things will have slowed down due to the reverse iteration, but others will have more informed opinions on that.
The comments I left are mostly smaller suggestions to clarify the code. I have held off on reviewing some core pieces of logic pending your next round of changes.

> Reviewed 4 of 4 files at r1, 7 of 7 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 4 of 4 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43862#-:-LyTiFFR4M7aBbFHAUEm:btvv3ol)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/storage/batch_spanset_test.go, line 193 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43862#-LyTVCIm90yv037oZEDt:-LyTVCIm90yv037oZEDu:b2q9pmq) ([raw file](https://github.com/cockroachdb/cockroach/blob/778e1820ccb4b3bbcd5606290fc138c66b937d28/pkg/storage/batch_spanset_test.go#L193)):*
> ```Go
> 		t.Fatalf("expected valid iterator, err=%v", err)
> 	}
> 	// SeekLT the upper bound is invalid.
> ```

Lower bound, right? Span set has `[c,g)`, and `insideKey==c`.
___
*[pkg/storage/gc_iterator.go, line 40 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/43862#-LyTeANN5pptDhYM7OJ4:-LyTeANN5pptDhYM7OJ5:b-h0n6iu) ([raw file](https://github.com/cockroachdb/cockroach/blob/39f39a2886ef280fcdf29b0d598e789fc93ff34c/pkg/storage/gc_iterator.go#L40)):*
> ```Go
> // this case, next is the value of an intent.
> func (it *gcIterator) state() (
> 	cur, next *engine.MVCCKeyValue,
> ```

This is dangerously close to warranting a struct that is being returned. You're often returning mostly zero values, so it would actually help readability quite a bit if you introduced

```go
type gcIterState struct {
  cur, next *engine.MVCCKeyValue
  isNewest, isIntent, ok bool
  err error
```

It would also give you a more convenient place for comments.
Is `ok` really needed? A comment explaining what it does would help.

I'll assume this method does the right thing for now, will revisit in post your next round of changes.
___
*[pkg/storage/engine/gc.go, line 36 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/43862#-LyTgcVxAzlvzaUGbG2Y:-LyTgcVxAzlvzaUGbG2Z:b-8f0f9x) ([raw file](https://github.com/cockroachdb/cockroach/blob/39f39a2886ef280fcdf29b0d598e789fc93ff34c/pkg/storage/engine/gc.go#L36)):*
> ```Go
> }
> 
> // IsGarbage makes a determination whether a key (cur) is garbage. Next, if
> ```

Write `'next'` here to make this easier to parse.
___
*[pkg/storage/engine/gc.go, line 37 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/43862#-LyTghFw6AnCJJSnNUeV:-LyTghFw6AnCJJSnNUeW:b-ef7ogw) ([raw file](https://github.com/cockroachdb/cockroach/blob/39f39a2886ef280fcdf29b0d598e789fc93ff34c/pkg/storage/engine/gc.go#L37)):*
> non-nil,

s/next/newer/
___
*[pkg/storage/engine/gc.go, line 40 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/43862#-LyThWYN10VCCP-CcvAG:-LyThWYN10VCCP-CcvAH:b-b8lbun) ([raw file](https://github.com/cockroachdb/cockroach/blob/39f39a2886ef280fcdf29b0d598e789fc93ff34c/pkg/storage/engine/gc.go#L40)):*
> ```Go
> // metadata KV if cur is an intent). If isNewest is false, next must be non-nil.
> // isNewest implies that this is the highest timestamp committed version for
> // this key. If isNewest is true and next is non-nil, it is an intent.
> ```

Explain that there being an intent doesn't matter in the impl below. Conservatively we have to assume that the intent will get aborted, so we will be able to GC just the values that we could remove if there weren't an intent. Maybe this comment doesn't have to live in the method comment, but it would be helpful somewhere.
___
*[pkg/storage/engine/gc_test.go, line 13 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/43862#-LyThtNO6eMHH0NNCOE7:-LyThtNO6eMHH0NNCOE8:b-we42vb) ([raw file](https://github.com/cockroachdb/cockroach/blob/07ebd0230cea54110f249420fd215adc1d2d5ecf/pkg/storage/engine/gc_test.go#L13)):*
> ```Go
> package engine
> 
> import (
> ```

Do these tests need to be replaced?
___
*[pkg/storage/spanset/spanset.go, line 185 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43862#-LyTWyqS6quUdwdF2Cx7:-LyTWyqS6quUdwdF2Cx8:b-z0v0oa) ([raw file](https://github.com/cockroachdb/cockroach/blob/778e1820ccb4b3bbcd5606290fc138c66b937d28/pkg/storage/spanset/spanset.go#L185)):*
Can you add a comment for `spanKeyExclusive`? Something like

> If spanKeyExclusive is set, the spans in `access` will be made open, i.e. `[a,b)` will be considered `(a,b)`.
___
*[pkg/storage/spanset/spanset.go, line 194 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43862#-LyTZH1m6AWEexD_HG_H:-LyTZH1m6AWEexD_HG_I:b-icve88) ([raw file](https://github.com/cockroachdb/cockroach/blob/778e1820ccb4b3bbcd5606290fc138c66b937d28/pkg/storage/spanset/spanset.go#L194)):*
> ```Go
> 		for _, cur := range s.spans[ac][scope] {
> 			if cur.Contains(span) &&
> 				(!spanKeyExclusive || cur.EndKey != nil && !cur.Key.Equal(span.Key)) ||
> ```

Is this EndKey check in the right place? I think this should be

```!spanKeyExclusive || !cur.Key.Equal(span.Key) || (cur.EndKey != nil && cur.Key.Equal(span.EndKey))```
___
*[pkg/storage/spanset/spanset.go, line 195 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43862#-LyTWiaw80t-AsfFoZ8X:-LyTWiaw80t-AsfFoZ8Y:b-t4qczn) ([raw file](https://github.com/cockroachdb/cockroach/blob/778e1820ccb4b3bbcd5606290fc138c66b937d28/pkg/storage/spanset/spanset.go#L195)):*
> ```Go
> 			if cur.Contains(span) &&
> 				(!spanKeyExclusive || cur.EndKey != nil && !cur.Key.Equal(span.Key)) ||
> 				spanKeyExclusive && cur.EndKey.Equal(span.Key) {
> ```

Isn't `spanKeyExclusive` always true if this expr is evaluated?

Having read the tests I think what's happening here is that `cur = [k1, k2)` is treated like `(k1, k2]`. I find the bool is not named intuitively for that behavior. Could "reverse" (along with a comment) be a better name?
___
*[pkg/storage/spanset/spanset.go, line 225 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43862#-LyTZKYc-bm79yUQvZMy:-LyTZKYc-bm79yUQvZMz:b-wq9lr2) ([raw file](https://github.com/cockroachdb/cockroach/blob/778e1820ccb4b3bbcd5606290fc138c66b937d28/pkg/storage/spanset/spanset.go#L225)):*
> ```Go
> 		for _, cur := range s.spans[ac][scope] {
> 			if (cur.Contains(span) &&
> 				(!spanKeyExclusive || (cur.EndKey != nil && !cur.Key.Equal(span.Key)))) ||
> ```

Similarly confused here
___
*[pkg/storage/spanset/spanset_test.go, line 224 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43862#-LyTZQSy3VrTNQJbIr6b:-LyTZQSy3VrTNQJbIr6c:b85bi7o) ([raw file](https://github.com/cockroachdb/cockroach/blob/778e1820ccb4b3bbcd5606290fc138c66b937d28/pkg/storage/spanset/spanset_test.go#L224)):*
> ```Go
> 	defer leaktest.AfterTest(t)()
> 
> 	var ss SpanSet
> ```

random idea: call this `bdGkq` to make it self-describing and to make these tests easier to read (this test is small anyway, but maybe this works in general).
___
*[pkg/storage/spanset/spanset_test.go, line 235 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43862#-LyTZrI39Z9XeEcWzLax:-LyTZrI39Z9XeEcWzLay:bq7aqiu) ([raw file](https://github.com/cockroachdb/cockroach/blob/778e1820ccb4b3bbcd5606290fc138c66b937d28/pkg/storage/spanset/spanset_test.go#L235)):*
> ```Go
> 	}
> 	for _, span := range allowed {
> 		if err := ss.checkAllowed(SpanReadOnly, span, true /* spanKeyExclusive */); err != nil {
> ```

Ok this explains why I'm confused. `spanKeyExclusive` makes the end key inclusive? I see how that's the right thing for the `SeekLT` usage but the naming is confusing.

**Review by petermattis — COMMENTED** [review]
> Glad to have you in this area of the code! The changes look very good. I'm not too worried that things will have slowed down due to the reverse iteration, but others will have more informed opinions on that.

Reverse iteration is definitely slower than forward iteration (25-50% depending on what/where you're measuring). But this can be well worth it if we are scanning less data due to using reverse iteration. Is that the case here? I haven't grok'd what is going on in this PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43862#-:-LyUAOkjAeHCWIlsXhXG:b-6bvnie)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

**Review by tbg — COMMENTED** [review]
No, I think we're scanning the exact same data and it's basically "all of the data". Where previously we'd iterate through all of the kv pairs in a range in forward order, we're now doing the reverse. There is an opportunity to "optimize" by seeking to the previous user key the moment current one's versions are no longer GC'able. Seek internally steps the iter a few times before resorting to the actual seek (as you well know). In this PR as written, we will manually step the iterator through every kv pair (the old code did that too, but not in reverse). Whenever we have lots of keys with >>10 non-gcable versions the actual Seek should be the better choice (and should be equivalent otherwise, due to the internal stepping optimization).
My intuition is that the slowdown of reverse iteration will not be felt much because GC is not a foreground operation and because it hasn't been performance optimized, so there will be other bottlenecks. But it seems like we should check.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43862#-:-LyUBqLP0mjZ8460A53D:b93umbq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by ajwerner** [comment]
Thanks for giving it a look. I’ll move forward with writing benchmarks and testing.

**Review by ajwerner — COMMENTED** [review]
Alright, I wrote some benchmarks and some tests. I also took this chance to carve off a new package.

The test coverage is no worse than it used to be because I left all of the old tests in place. I also wrote a test that generates a random dataset and compares the output of the old implementation to the new one. Perhaps a few more unit tests are in order and perhaps more coverage of the unchanged code related to abort spans and the local key range. 

After some minor memory optimizations the benchmarks show a modest win and a dramatic reduction in memory usage. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43862#-:-Lyh8WDz2zX86VqWcpYU:b-a0ju0c)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @tbg)

___
*[pkg/storage/batch_spanset_test.go, line 193 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43862#-LyTVCIm90yv037oZEDt:-Lyh6V781xni5bP0ys4n:bidrs83) ([raw file](https://github.com/cockroachdb/cockroach/blob/778e1820ccb4b3bbcd5606290fc138c66b937d28/pkg/storage/batch_spanset_test.go#L193)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Lower bound, right? Span set has `[c,g)`, and `insideKey==c`.
</blockquote></details>

Right. Fixed.
___
*[pkg/storage/gc_iterator.go, line 40 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/43862#-LyTeANN5pptDhYM7OJ4:-Lyh49_m-liRjW-7NaoF:bv6jo27) ([raw file](https://github.com/cockroachdb/cockroach/blob/39f39a2886ef280fcdf29b0d598e789fc93ff34c/pkg/storage/gc_iterator.go#L40)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This is dangerously close to warranting a struct that is being returned. You're often returning mostly zero values, so it would actually help readability quite a bit if you introduced

```go
type gcIterState struct {
  cur, next *engine.MVCCKeyValue
  isNewest, isIntent, ok bool
  err error
```

It would also give you a more convenient place for comments.
Is `ok` really needed? A comment explaining what it does would help.

I'll assume this method does the right thing for now, will revisit in post your next round of changes.
</blockquote></details>

I did indeed create a struct. I also simplified the logic. 
___
*[pkg/storage/spanset/spanset.go, line 185 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43862#-LyTWyqS6quUdwdF2Cx7:-Lyh59a594-6_-EPNRYA:batzh3e) ([raw file](https://github.com/cockroachdb/cockroach/blob/778e1820ccb4b3bbcd5606290fc138c66b937d28/pkg/storage/spanset/spanset.go#L185)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Can you add a comment for `spanKeyExclusive`? Something like

> If spanKeyExclusive is set, the spans in `access` will be made open, i.e. `[a,b)` will be considered `(a,b)`.
</blockquote></details>

spans in access will be open at the start and closed at the end, i.e. `[a,b)` will be considered `(a,b]`
___
*[pkg/storage/spanset/spanset.go, line 195 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43862#-LyTWiaw80t-AsfFoZ8X:-Lyh7KKC6h5qNiVTm_8N:bxde61b) ([raw file](https://github.com/cockroachdb/cockroach/blob/778e1820ccb4b3bbcd5606290fc138c66b937d28/pkg/storage/spanset/spanset.go#L195)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Isn't `spanKeyExclusive` always true if this expr is evaluated?

Having read the tests I think what's happening here is that `cur = [k1, k2)` is treated like `(k1, k2]`. I find the bool is not named intuitively for that behavior. Could "reverse" (along with a comment) be a better name?
</blockquote></details>

I've renamed the variable and added commentary.
___
*[pkg/storage/spanset/spanset_test.go, line 224 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43862#-LyTZQSy3VrTNQJbIr6b:-Lyh7zpT0hwoOtEz9ZSf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/778e1820ccb4b3bbcd5606290fc138c66b937d28/pkg/storage/spanset/spanset_test.go#L224)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

random idea: call this `bdGkq` to make it self-describing and to make these tests easier to read (this test is small anyway, but maybe this works in general).
</blockquote></details>

Done.
___
*[pkg/storage/spanset/spanset_test.go, line 235 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43862#-LyTZrI39Z9XeEcWzLax:-Lyh8-nx3FKJ7XJY-3hQ:b-tvm9hv) ([raw file](https://github.com/cockroachdb/cockroach/blob/778e1820ccb4b3bbcd5606290fc138c66b937d28/pkg/storage/spanset/spanset_test.go#L235)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Ok this explains why I'm confused. `spanKeyExclusive` makes the end key inclusive? I see how that's the right thing for the `SeekLT` usage but the naming is confusing.
</blockquote></details>

Hopefully it's less confusing now.
___
*[pkg/storage/engine/gc.go, line 36 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/43862#-LyTgcVxAzlvzaUGbG2Y:-Lyh4jBy7o6P7Su955zO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/39f39a2886ef280fcdf29b0d598e789fc93ff34c/pkg/storage/engine/gc.go#L36)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Write `'next'` here to make this easier to parse.
</blockquote></details>

Done.
___
*[pkg/storage/engine/gc.go, line 37 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/43862#-LyTghFw6AnCJJSnNUeV:-Lyh4isKDvc_y8paQ08l:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/39f39a2886ef280fcdf29b0d598e789fc93ff34c/pkg/storage/engine/gc.go#L37)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

> non-nil,

s/next/newer/
</blockquote></details>

Done.
___
*[pkg/storage/engine/gc.go, line 40 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/43862#-LyThWYN10VCCP-CcvAG:-Lyh4zvw4Pfr2oW8CQ6A:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/39f39a2886ef280fcdf29b0d598e789fc93ff34c/pkg/storage/engine/gc.go#L40)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Explain that there being an intent doesn't matter in the impl below. Conservatively we have to assume that the intent will get aborted, so we will be able to GC just the values that we could remove if there weren't an intent. Maybe this comment doesn't have to live in the method comment, but it would be helpful somewhere.
</blockquote></details>

Done.
___
*[pkg/storage/engine/gc_test.go, line 13 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/43862#-LyThtNO6eMHH0NNCOE7:-LyUXgpkAiooW2oCcirN:bx3b3si) ([raw file](https://github.com/cockroachdb/cockroach/blob/07ebd0230cea54110f249420fd215adc1d2d5ecf/pkg/storage/engine/gc_test.go#L13)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Do these tests need to be replaced?
</blockquote></details>

definitely. I retained them in the testing file which now contains all of this old code and exists to support the old implementation.

**Review by ajwerner — COMMENTED** [review]
@tbg friendly ping

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43862#-:-Lz7Fz6I8ZHY17kypKQe:b-huo8gr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @tbg)

**Review by tbg — APPROVED** [review]
Looks great! :lgtm: and thanks for all of the cleanup work. I might've missed some of the changes since my last review (Reviewable and/or I got a little confused with all the revisions), so if there's something in particular that I should give a closer look please let me know.

> Reviewed 13 of 13 files at r7, 7 of 7 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, 7 of 7 files at r11, 12 of 12 files at r12.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43862#-:-Lz7SQLlB-Z7nDALx2J1:bz4ivqy)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/storage/gc/gc_iterator_test.go, line 27 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/43862#-Lz7Re3TEVr6Fl2uQy2f:-Lz7Re3UCqGI_SwiigIu:bt4cgiu) ([raw file](https://github.com/cockroachdb/cockroach/blob/55b4936360e897405a4816bd08f9009f115f5841/pkg/storage/gc/gc_iterator_test.go#L27)):*
> ```Go
> )
> 
> func TestGCIterator(t *testing.T) {
> ```

Bit of commentary as this test proceeds would be nice.
___
*[pkg/storage/gc/gc_old_test.go, line 32 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/43862#-Lz7RkYw9s1FoiAnCQuM:-Lz7RkYw9s1FoiAnCQuN:b-tbgf3g) ([raw file](https://github.com/cockroachdb/cockroach/blob/55b4936360e897405a4816bd08f9009f115f5841/pkg/storage/gc/gc_old_test.go#L32)):*
> ```Go
> )
> 
> // RunGCOld is an older implementation of Run. It is used for benchmarking and
> ```

Not that it matters much, but does it need to be exported?
___
*[pkg/storage/gc/gc.go, line 477 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/43862#-Lz7RQdh6d2-iVPuRNGC:-Lz7RQdh6d2-iVPuRNGD:b-k420az) ([raw file](https://github.com/cockroachdb/cockroach/blob/55b4936360e897405a4816bd08f9009f115f5841/pkg/storage/gc/gc.go#L477)):*
> ```Go
> // multiple of the heartbeat timeout used by the coordinator.
> //
> // TODO(tschottdorf): this could be done in Replica.GC itself, but it's
> ```

This TODO can be removed (not worth a CI run though)

**Review by tbg — COMMENTED** [review]
(and sorry for letting this sit - I've changed my GH workflow a bit and am still working out the kinks).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43862#-:-Lz7Sf-r8HggLdFL2bLA:b-hzoesz)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Review by ajwerner — COMMENTED** [review]
TFTR!

bors r=tbg

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43862#-:-Lz7nJmq7OmX3koIe_P_:b-kg5fnc)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @tbg)

___
*[pkg/storage/gc/gc.go, line 477 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/43862#-Lz7RQdh6d2-iVPuRNGC:-Lz7laEoDD4fa-b7BgES:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/55b4936360e897405a4816bd08f9009f115f5841/pkg/storage/gc/gc.go#L477)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This TODO can be removed (not worth a CI run though)
</blockquote></details>

Done.
___
*[pkg/storage/gc/gc_iterator_test.go, line 27 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/43862#-Lz7Re3TEVr6Fl2uQy2f:-Lz7mz2UCOCsavWLBUVm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/55b4936360e897405a4816bd08f9009f115f5841/pkg/storage/gc/gc_iterator_test.go#L27)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Bit of commentary as this test proceeds would be nice.
</blockquote></details>

Done.
___
*[pkg/storage/gc/gc_old_test.go, line 32 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/43862#-Lz7RkYw9s1FoiAnCQuM:-Lz7aaKn1oRaVUBapv9y:bc704ki) ([raw file](https://github.com/cockroachdb/cockroach/blob/55b4936360e897405a4816bd08f9009f115f5841/pkg/storage/gc/gc_old_test.go#L32)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Not that it matters much, but does it need to be exported?
</blockquote></details>

When I first wrote it I made the benchmarks a `package gc_test` file, I ended up reverting that because symbol sharing with other testing infrastructure got annoying. Unexported.

**Pull request merged**
