### PR TITLE
internal/sqlsmith: improvements for JSON

### PR DESCRIPTION
**Pull request by madelynnblue**

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42628)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mjibson)

___
*[pkg/internal/sqlsmith/alter.go, line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42628#-LuAExP0DJj7CKUGksby:-LuAExP0DJj7CKUGksbz:b-jo7tfr) ([raw file](https://github.com/cockroachdb/cockroach/blob/7178a0dcf1e33cf40c2cdb017aa28637be81291c/pkg/internal/sqlsmith/alter.go#L206)):*
> ```Go
> 		seen[col.Name] = true
> 		// If this is the first column and it's invertable (i.e., JSONB), make an inverted index.
> 		if len(cols) == 0 && sqlbase.ColumnTypeIsInvertedIndexable(col.Type) {
> ```

Do we want to create non-inverted index sometimes?
___
*[pkg/internal/sqlsmith/alter.go, line 200 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42628#-LuAGQOaBVt1jGUyPjou:-LuAGQOaBVt1jGUyPjov:b-w382ld) ([raw file](https://github.com/cockroachdb/cockroach/blob/1af6348db830c4ee0f06cf7fbe7a5b2e7a4f3e52/pkg/internal/sqlsmith/alter.go#L200)):*
> ```Go
> 	}
> 	col.Computed.Computed = true
> 	col.Computed.Expr = tree.NewTypedBinaryExpr(tree.JSONFetchText, ref.typedExpr(), sqlbase.RandDatumSimple(s.rnd, types.String), types.String)
> ```

I'm not sure about this, but can other types of JSON expressions (other than `JSONFetchText`) be used here?

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42628)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/internal/sqlsmith/alter.go, line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42628#-LuAExP0DJj7CKUGksby:-LuBF0tmBrGqLwndLHyv:b-dstluh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7178a0dcf1e33cf40c2cdb017aa28637be81291c/pkg/internal/sqlsmith/alter.go#L206)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Do we want to create non-inverted index sometimes?
</blockquote></details>

Nope, you can't make a non-inverted JSON index.
___
*[pkg/internal/sqlsmith/alter.go, line 200 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42628#-LuAGQOaBVt1jGUyPjou:-LuBF3JN67C5-IwGJgR7:b-or5ny) ([raw file](https://github.com/cockroachdb/cockroach/blob/1af6348db830c4ee0f06cf7fbe7a5b2e7a4f3e52/pkg/internal/sqlsmith/alter.go#L200)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I'm not sure about this, but can other types of JSON expressions (other than `JSONFetchText`) be used here?
</blockquote></details>

JSONFetchText is the operator used in the document describing this feature (https://www.cockroachlabs.com/docs/v19.2/inverted-indexes.html#comparisons). For now it meets the needs (test more JSON indexing) without worrying too much about theoretical possibilities.

**Review by yuzefovich — APPROVED** [review]
:lgtm: Thanks for the answers!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42628#-:-LuBUqWy33xr3vUHrSjl:b-by42qu)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by awoods187** [comment]
>Nope, you can't make a non-inverted JSON index.
I haven't read the pr but @mjibson we also need to test computed columns with indexes as an alternative to gin indexes

**Comment by mjibson** [comment]
@awoods187 That's the 3rd commit in this PR: https://github.com/cockroachdb/cockroach/pull/42628/commits/1af6348db830c4ee0f06cf7fbe7a5b2e7a4f3e52

**Pull request merged**
