### PR TITLE
[wip] sql: introduce new foreign key helper and batch foreign key checking (redux) 

### PR DESCRIPTION
**Pull request by emsal0**
This is (PR) #26957 but with some extra work and several rebases ahead; I tried turning the branch on the other PR into this one but I ran into several messy complications.

(Perhaps PR #26957 should be closed)

### CODE REVIEW

**Comment by BramGruneir** [comment]
Might as well close the old PR.

**Comment by knz** [comment]
when do you want me (us) to review this / provide feedback?

**Comment by emsal1863** [comment]
@knz this will be ready for review as soon as I finish the batching of all the cascader operations. Hopefully that will be soon. Should I close the PR in the meantime?

**Comment by knz** [comment]
it's fine.

**Pull request closed without merging**
