### PR TITLE
sql: do not wait for setup of remote flows on the gateway

### LINKED ISSUE #87669: distsql: consider not blocking on SetupFlow RPCs before starting the flow on the gateway
Currently, during the physical planning of a distributed query we will perform `SetupFlow` RPCs in parallel (subject to the available distsql runners) while setting up the flow on the gateway, but we won't start the execution of that gateway flow until all RPCs come back. In multi-region clusters that wait will be on the order of 100ms. If the gateway flow is such that all remote flows depend on data coming from the gateway, this blocking behavior introduces the "stall" in the execution pipeline across the whole plan which can significantly increase the latency of the query. Furthermore, this latency increase is non-deterministic (depends on the placement of ranges for the TableReaders) making it harder to investigate the performance.

This blocking is performed in order to make sure that remote nodes can execute their part of the plan. I believe originally it was envisioned that if the `SetupFlow` RPC fails for any reason, then the gateway would take over that part of the plan - but this was never implemented. Additionally, it seems far more likely that those RPCs are successful (we only consider nodes that are "healthy" and distsql-version-compatible for physical planning), so this blocking doesn't seem to be that useful. Also, we will soon remove the queueing of the remote flows due to `max_running_flows` limit which will increase the likelihood of the success of RPCs even further.

This all suggests that it would beneficial to remove this blocking and, instead, opportunistically proceed with the execution on the gateway while spinning up an async task that would make sure to cancel the execution if an RPC comes back with an error.

Jira issue: CRDB-19465

### PR DESCRIPTION
**Pull request by yuzefovich**
Previously, when setting up the flows for a distributed plan we would
issue all SetupFlow RPCs to the remote nodes and wait for all of them to
come back before proceeding with the execution of the local flow. This
can introduce an execution stall, especially in multi-region setups, if
remote flows depend on the local flow for some of the data. This was
suboptimal, and this PR makes it so that we no longer wait for the
RPCs to come back and start executing the local flow right away. We now
spin up a separate goroutine that waits for the RPCs to come back, and
if an error is encountered (which shouldn't happen often), then that
goroutine sets the error on the DistSQLReceiver and cancels the local
flow. Setting the error on the receiver, in turn, will make it so that
all remote flows will be canceled via CancelDeadFlows RPC (which might
be faster than via the distributed query shutdown triggered when the
local flow is canceled).

See individual commits for more details.

Fixes: #87669.

Epic: CRDB-20535

Release note (performance improvement): The setup of the distributed
query execution is now fully parallelized which should reduce the query
latencies, especially in multi-region setups.

### CODE REVIEW

**Review by msirek — COMMENTED** [review]
This looks great! Is it possible to add a test? Maybe a simple distributed query with a mode which randomly injects remote errors, then tests that everything was cleaned up properly. Or is that too difficult?

> Reviewed 6 of 6 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89649#-:-NGX_CBY4FF3xJhtQdg8:b2wup5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @yuzefovich)

___
*[`pkg/sql/distsql_running.go` line 102 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89649#-NGTxeiCCX22Daozt17B:-NGTxeiCCX22Daozt17C:b8oz6hj) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd511eee147aa992cd732d3fd786ec112da4c5f6/pkg/sql/distsql_running.go#L102)):*
> ```Go
> 
> // run executes the request. An error if encountered is both sent on the
> // result channel and returned.
> ```

nit: Please either add commas around 'if encountered' or re-word this.
___
*[`pkg/sql/distsql_running.go` line 452 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89649#-NGXLtyfBmFwP3TGaVPY:-NGXLtyg1dn0pJJMFir2:b-8qfpr5) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd511eee147aa992cd732d3fd786ec112da4c5f6/pkg/sql/distsql_running.go#L452)):*
> ```Go
> 		err = planCtx.saveFlows(flows, opChains)
> 	}
> 	if len(flows) == 1 || err != nil {
> ```

Is it safe to assume there is always a local `FlowSpec` in `flows`?
___
*[`pkg/sql/distsql_running.go` line 523 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89649#-NGXIqEx6UecoLN3iaLd:-NGXIqEx6UecoLN3iaLe:b-3lfe9l) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd511eee147aa992cd732d3fd786ec112da4c5f6/pkg/sql/distsql_running.go#L523)):*
> ```Go
> 	})
> 	_ = dsp.stopper.RunAsyncTask(origCtx, "distsql-remote-flows-setup-listener", func(ctx context.Context) {
> 		for i := 0; i < len(flows)-1; i++ {
> ```

This line makes the assumption that there is a local `FlowSpec` in `flows`. Is this always true?  Could it ever contain zero local `FlowSpec`s?
Should we make it explicit and iterate through all flows and then ignore any local flows?

Also, looking at `GenerateFlowSpecs()`, it seems like each `SQLInstanceID` entry in the `flow` map could have multiple flows. If the goal is to execute this loop once for each remote flow, it seems like it should also iterate over all `Processors` in each remote `FlowSpec`.
___
*[`pkg/sql/distsql_running.go` line 706 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89649#-NGXVC0M3-_zo4ZsjAVi:-NGXVC0M3-_zo4ZsjAVj:b-4gnu7a) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd511eee147aa992cd732d3fd786ec112da4c5f6/pkg/sql/distsql_running.go#L706)):*
> ```Go
> 	} else {
> 		defer func() {
> 			if recv.getError() != nil {
> ```

Should the `recv.resultWriterMu.batch` interface also be extended with `SetError` and `Err` methods so this `getError()` check could also eagerly cancel flows when there's a batch error?



_Code quote:_
```Go
recv
```
___
*[`pkg/sql/distsql_running.go` line 1111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89649#-NGXYiOBAdmkAUpfVn3l:-NGXYiOBAdmkAUpfVn3m:b-5ehp4e) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd511eee147aa992cd732d3fd786ec112da4c5f6/pkg/sql/distsql_running.go#L1111)):*
> ```Go
> 				// SQL node, which has left the handling up to the root
> 				// transaction.
> 				err = r.txn.UpdateStateOnRemoteRetryableErr(r.ctx, &retryErr.PErr)
> ```

If `r.txn` is `RootTxn`, this sets a new assertion error and loses the original error.  
Should `UpdateStateOnRemoteRetryableErr` wrap the assertion error inside the original error to get more useful error reporting?
___
*[`pkg/sql/flowinfra/flow.go` line 526 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89649#-NGXTULk5nJaI_Rbc26g:-NGXTULk5nJaI_Rbc26h:b4ot6d1) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd511eee147aa992cd732d3fd786ec112da4c5f6/pkg/sql/flowinfra/flow.go#L526)):*
> ```Go
> 		f.onFlowCleanup = func() {
> 			fn()
> 			oldOnFlowCleanup()
> ```

Should this add `fn()` after `oldOnFlowCleanup()` to make sure any cleanup operations in `oldOnFlowCleanup()` are done before `fn()` marks the cleanup as done?

**Review by yuzefovich — COMMENTED** [review]
Thanks for the review! I did briefly consider writing a test for this but decided not to since it seemed rather difficult and probably prone to flakes - but with your nudge I'll actually spend some time and see what I can come up with.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89649#-:-NGY0ARr5CtShlch4wrN:bayu7e1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @msirek)

___
*[`pkg/sql/distsql_running.go` line 452 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89649#-NGXLtyfBmFwP3TGaVPY:-NGXxmFX1yxfpvSw4dWo:b1u5v2d) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd511eee147aa992cd732d3fd786ec112da4c5f6/pkg/sql/distsql_running.go#L452)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Is it safe to assume there is always a local `FlowSpec` in `flows`?
</blockquote></details>

Yes - we have an assertion that there is a gateway flow at the very beginning of this (`setupFlows`) function.
___
*[`pkg/sql/distsql_running.go` line 523 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89649#-NGXIqEx6UecoLN3iaLd:-NGXxxnuDE5yaCV4z2eP:b8mruqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd511eee147aa992cd732d3fd786ec112da4c5f6/pkg/sql/distsql_running.go#L523)):*
I think it's a pretty safe code given there is always the gateway flow and this code (iterating `len(flows)-1` times to receive from `resultChan`) is not changing in this commit.

> Also, looking at GenerateFlowSpecs(), it seems like each SQLInstanceID entry in the flow map could have multiple flows.

Hm, why does it seem like this? `flows` is a map from `SQLInstanceID` to a `FlowSpec` which implies that we have at most a single `FlowSpec` for any given `SQLInstanceID`. The iteration in `GenerateFlowSpecs` is about handling all processors - i.e. each node can have many processors planned - but there will be at most one flow per node.

We did discuss the idea of having more parallelism in our execution a couple of times, and one approach there would be to have multiple flows for a single node, but we haven't really done any work in that direction.

> If the goal is to execute this loop once for each remote flow, it seems like it should also iterate over all Processors in each remote FlowSpec.

The goal of `GenerateFlowSpecs` is to iterate over all processors that are part of the `PhysicalPlan`, then divide all of them up according to the nodes on which they are planned, and each separate "division" (i.e. subset) of processors form a single `FlowSpec`.
___
*[`pkg/sql/distsql_running.go` line 706 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89649#-NGXVC0M3-_zo4ZsjAVi:-NGXzTdd7z-AfcMGFR9i:b-1ou5t8) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd511eee147aa992cd732d3fd786ec112da4c5f6/pkg/sql/distsql_running.go#L706)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Should the `recv.resultWriterMu.batch` interface also be extended with `SetError` and `Err` methods so this `getError()` check could also eagerly cancel flows when there's a batch error?
</blockquote></details>

It's not obvious, but `recv.resultWriterMu.row` and `recv.resultWriterMu.batch` (when the latter is non-nil) actually point to exactly the same object, so "implicitly" we do set the error on the correct object (most likely it'll be `commandResult`) in case of a batch error.
___
*[`pkg/sql/distsql_running.go` line 1111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89649#-NGXYiOBAdmkAUpfVn3l:-NGXzzZn1EXDsiHGD2aQ:bo1verf) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd511eee147aa992cd732d3fd786ec112da4c5f6/pkg/sql/distsql_running.go#L1111)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

If `r.txn` is `RootTxn`, this sets a new assertion error and loses the original error.  
Should `UpdateStateOnRemoteRetryableErr` wrap the assertion error inside the original error to get more useful error reporting?
</blockquote></details>

I'm guessing no, but this code is not modified in this commit at all - it is only extracted into the helper, so I'm afraid to change anything here :)
___
*[`pkg/sql/flowinfra/flow.go` line 526 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89649#-NGXTULk5nJaI_Rbc26g:-NGY-dvKCYeTWV05Yrhe:bjhtecr) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd511eee147aa992cd732d3fd786ec112da4c5f6/pkg/sql/flowinfra/flow.go#L526)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Should this add `fn()` after `oldOnFlowCleanup()` to make sure any cleanup operations in `oldOnFlowCleanup()` are done before `fn()` marks the cleanup as done?
</blockquote></details>

I think that we want the "stack" behavior here. My rationale is that we currently have a single `onFlowCleanup` function instantiated in `distsql.ServerImpl.setupFlow`, and I think that function should be executed last when we add new callbacks - this way the "parent" operation is cleaned up after the "child" one. I expanded the comment on the `Flow` interface.

**Comment by yuzefovich** [comment]
The test is actually uncovering some (relatively minor) issues that I want to address first, so hold off on reviewing further - I'll ping once it is ready for another look.

**Review by msirek — COMMENTED** [review]
OK

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89649#-:-NGb-RqZCOWemVGsWNQf:b32w0x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @yuzefovich)

___
*[`pkg/sql/distsql_running.go` line 452 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89649#-NGXLtyfBmFwP3TGaVPY:-NGayrSbBf72gSjTKLwK:brujztc) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd511eee147aa992cd732d3fd786ec112da4c5f6/pkg/sql/distsql_running.go#L452)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Yes - we have an assertion that there is a gateway flow at the very beginning of this (`setupFlows`) function.
</blockquote></details>

OK, thanks.
___
*[`pkg/sql/distsql_running.go` line 523 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89649#-NGXIqEx6UecoLN3iaLd:-NGayxdmE_aPGPcWa3dV:blpwy7p) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd511eee147aa992cd732d3fd786ec112da4c5f6/pkg/sql/distsql_running.go#L523)):*
> Hm, why does it seem like this?

I think this is misunderstanding of the code on my part.  Thanks for the clarification.

> We did discuss the idea of having more parallelism in our execution a couple of times, and one approach there would be to have multiple flows for a single node, but we haven't really done any work in that direction.

,,,

> The goal of GenerateFlowSpecs is to iterate over all processors that are part of the PhysicalPlan, then divide all of them up according to the nodes on which they are planned, and each separate "division" (i.e. subset) of processors form a single FlowSpec.

TIL
Thanks
___
*[`pkg/sql/distsql_running.go` line 706 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89649#-NGXVC0M3-_zo4ZsjAVi:-NGb-DAa7f32J7EYPEG8:b32w0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd511eee147aa992cd732d3fd786ec112da4c5f6/pkg/sql/distsql_running.go#L706)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

It's not obvious, but `recv.resultWriterMu.row` and `recv.resultWriterMu.batch` (when the latter is non-nil) actually point to exactly the same object, so "implicitly" we do set the error on the correct object (most likely it'll be `commandResult`) in case of a batch error.
</blockquote></details>

OK
___
*[`pkg/sql/distsql_running.go` line 1111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89649#-NGXYiOBAdmkAUpfVn3l:-NGb-GJB4ZI3AaHgkBGH:brujztc) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd511eee147aa992cd732d3fd786ec112da4c5f6/pkg/sql/distsql_running.go#L1111)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I'm guessing no, but this code is not modified in this commit at all - it is only extracted into the helper, so I'm afraid to change anything here :)
</blockquote></details>

OK, thanks.
___
*[`pkg/sql/flowinfra/flow.go` line 526 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89649#-NGXTULk5nJaI_Rbc26g:-NGb-NPc3U_Fqx_HH0H6:b32w0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd511eee147aa992cd732d3fd786ec112da4c5f6/pkg/sql/flowinfra/flow.go#L526)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I think that we want the "stack" behavior here. My rationale is that we currently have a single `onFlowCleanup` function instantiated in `distsql.ServerImpl.setupFlow`, and I think that function should be executed last when we add new callbacks - this way the "parent" operation is cleaned up after the "child" one. I expanded the comment on the `Flow` interface.
</blockquote></details>

OK

**Review by yuzefovich — COMMENTED** [review]
Alright, I think it is RFAL.

I added a test like Mark suggested which shook out some issues:
- in a newly-added second commit we now make the cancellation of `SetupFlow` RPC on the server-side (remote node) more eager. The test (when run with "succeeds within 5s") could have a remote flow on `n2` running even after the gateway flow on `n1` exited with an error injected on `n3` - this would depend on the scheduling of the RPC goroutines for `n2`. Unfortunately, in a rare edge case (like once in several thousands of runs under stress) it is expected that such a remote flow would exit after 10s timeout, so the test cannot use short 5s duration that I used when working on it for fleshing out things.
- using the "origCtx" for the RPCs could lead to reuse of the tracing span that was `Finish`ed if the RPC actually runs after the gateway flow exits. This is fixed by adjusting the last commit.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89649#-:-NGc8WlHDNViBml_NHQv:bpa24fe)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @msirek)

___
*[`pkg/sql/distsql_running.go` line 452 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89649#-NGXLtyfBmFwP3TGaVPY:-NGcAEg33BT-GkZ3wWLu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd511eee147aa992cd732d3fd786ec112da4c5f6/pkg/sql/distsql_running.go#L452)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

OK, thanks.
</blockquote></details>

Done.
___
*[`pkg/sql/distsql_running.go` line 523 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89649#-NGXIqEx6UecoLN3iaLd:-NGcAFfq7JFG-SBiJaCZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd511eee147aa992cd732d3fd786ec112da4c5f6/pkg/sql/distsql_running.go#L523)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

> Hm, why does it seem like this?

I think this is misunderstanding of the code on my part.  Thanks for the clarification.

> We did discuss the idea of having more parallelism in our execution a couple of times, and one approach there would be to have multiple flows for a single node, but we haven't really done any work in that direction.

,,,

> The goal of GenerateFlowSpecs is to iterate over all processors that are part of the PhysicalPlan, then divide all of them up according to the nodes on which they are planned, and each separate "division" (i.e. subset) of processors form a single FlowSpec.

TIL
Thanks
</blockquote></details>

Done.
___
*[`pkg/sql/distsql_running.go` line 706 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89649#-NGXVC0M3-_zo4ZsjAVi:-NGcAGgz9B5NHWk6_o-u:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd511eee147aa992cd732d3fd786ec112da4c5f6/pkg/sql/distsql_running.go#L706)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

OK
</blockquote></details>

Done.
___
*[`pkg/sql/distsql_running.go` line 1111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89649#-NGXYiOBAdmkAUpfVn3l:-NGcAH4x1GX-jqW6wRHL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd511eee147aa992cd732d3fd786ec112da4c5f6/pkg/sql/distsql_running.go#L1111)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

OK, thanks.
</blockquote></details>

Done.
___
*[`pkg/sql/flowinfra/flow.go` line 526 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89649#-NGXTULk5nJaI_Rbc26g:-NGcALpK28MSoMiJTOQc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd511eee147aa992cd732d3fd786ec112da4c5f6/pkg/sql/flowinfra/flow.go#L526)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

OK
</blockquote></details>

Done.

**Review by msirek — APPROVED** [review]
:lgtm: 

> Reviewed 7 of 7 files at r5, 1 of 1 files at r6, 8 of 9 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89649#-:-NGdAgRn3woR0PL4O5lk:b593w57)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
