### PR TITLE
server,cli: separate storage-level and application-level metrics

### PR DESCRIPTION
**Pull request by knz**
Prerequisite to #102378. 
Informs #108929.
Epic:  CRDB-26691.

Context: we have various projects that want to know which metrics
belong to the application layer (and thus are instantiated and
collected anew in every tenant); and which belong to the storage/KV
layer (and thus exist only once per node in the storage layer).

Prior to this patch, it was hard to distinguish between them.

This patch enhances the situation as follows:

- It introduces the concept of "server layering" for metrics, a
  concept which we had already introduced earlier in the
  `TestServerInterface`:

  - "storage" designates the storage layer, and only contains
    metrics relevant to the storage/kv layer.

  - "application" designates the application layer, and only
    contains metrics relevant to the application layer.

  - "server" is a special (pseudo) layer which contains metrics
    defined process-wide, and are thus reported both in combined
    sql/kv nodes and sql-only servers.

- It also uses *separate metric registries* to collect the metrics
  at each layer during server initialization.

  This is the main component that we were missing for later projects.

- It also enhances the `ChartCatalog` API endpoint and introduces
  a new `cockroach gen metric-list` command to use it and
  auto-generate a list of metrics with their layer information.

Release note (cli change): A new `cockroach gen metric-list` is now
available that can generate metadata that describes the various
metrics collected by an (idle) server. Note that the list does
not include dynamic metric names whose names are generated
based on workload.

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
Thanks for taking this on!

> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 16 of 16 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109042#-:-NcOFfEB3SGYuc8CAYEP:b-dt2ft9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @knz)

___
*[`-- commits` line 9 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109042#-NcO5Xk_8PrjNRQYpOs3):*
nit: should we add a unit test case for this in `TestRenderHTML`?
___
*[`pkg/cli/gen.go` line 350 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109042#-NcO6Y8m0Mvogl0FBKVa:-NcO6Y8m0Mvogl0FBKVb:bgxdl6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f6a524f8743c118ab259e1f25cd84e480446fe9/pkg/cli/gen.go#L350)):*
> ```Go
> 		})
> 
> 		// Start the server
> ```

nit: missing period.
___
*[`pkg/server/server.go` line 561 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109042#-NcOAGyJA5jFoOaa5tEf:-NcOAGyJA5jFoOaa5tEg:bluxrtb) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f6a524f8743c118ab259e1f25cd84e480446fe9/pkg/server/server.go#L561)):*
> ```Go
> 
> 	storesForFlowControl := kvserver.MakeStoresForFlowControl(stores)
> 	kvflowTokenDispatch := kvflowdispatch.New(appRegistry, storesForFlowControl, nodeIDContainer)
> ```

IIUC KV flow controller is on the KV server side, so I'd expect it to be in `nodeRegistry`.
___
*[`pkg/server/server.go` line 1806 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109042#-NcOCzc58erC8D3_Ue7r:-NcOCzc58erC8D3_Ue7s:b48zoga) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f6a524f8743c118ab259e1f25cd84e480446fe9/pkg/server/server.go#L1806)):*
> ```Go
> 	// Start measuring the Go scheduler latency.
> 	if err := schedulerlatency.StartSampler(
> 		workersCtx, s.st, s.stopper, s.appRegistry, base.DefaultMetricsSampleInterval,
> ```

I'm wondering whether the app registry is the right one for Go scheduler latency, seems closer to server registry, no?
___
*[`pkg/server/tenant.go` line 663 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109042#-NcODmEI2ZrFGE4Wz9TX:-NcODmEI2ZrFGE4Wz9TY:b4ei0mb) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f6a524f8743c118ab259e1f25cd84e480446fe9/pkg/server/tenant.go#L663)):*
> ```Go
> 	}
> 
> 	// We can now add the node registry.
> ```

nit: this comment now seems out of date.
___
*[`pkg/server/status/recorder.go` line 222 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109042#-NcOEYUlByma37zvf0Os:-NcOEYUlByma37zvf0Ot:bx8tztc) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f6a524f8743c118ab259e1f25cd84e480446fe9/pkg/server/status/recorder.go#L222)):*
> ```Go
> 
> // AddNode adds the Registry from an initialized node, along with its descriptor
> // and start time. It also adds the logging registry.
> ```

nit: the comment is now outdated.
___
*[`pkg/server/status/recorder.go` line 440 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109042#-NcOEf6aE20LgdtfyuhO:-NcOEf6aE20LgdtfyuhP:b-xpwzbf) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f6a524f8743c118ab259e1f25cd84e480446fe9/pkg/server/status/recorder.go#L440)):*
> ```Go
> //
> // If the argument is true, both node-level and app-level metrics are
> // combined in the firt return value.
> ```

nit: `s/firt/first/`.
___
*[`pkg/server/status/recorder.go` line 560 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109042#-NcOF0me0i211gayYgY8:-NcOF0me0i211gayYgY9:bjq7lc5) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f6a524f8743c118ab259e1f25cd84e480446fe9/pkg/server/status/recorder.go#L560)):*
> ```Go
> 		nodeStat.Metrics[name] = val
> 	})
> 	eachRecordableValue(mr.mu.logRegistry, func(name string, val float64) {
> ```

Should we also do the same for `sysRegistry`?

**Review by abarganier — COMMENTED** [review]
Thanks for this work! It's nice to see a step in the right direction.

In the context of https://github.com/cockroachdb/cockroach/issues/102378, how do we envision TSDB query clients being able to take advantage of this segmentation/classification of different metrics? Would we encode some additional piece of data into the TSDB key? Or use the registries to, given a metric name, determine its classification/type? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109042#-:-NcOSjiv26NwM1RUMt2W:b-r70z7u)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/cli/gen.go` line 321 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109042#-NcODtVzCUzlN_v2uDm0:-NcODtVzCUzlN_v2uDm1:b45veln) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f6a524f8743c118ab259e1f25cd84e480446fe9/pkg/cli/gen.go#L321)):*
> ```Go
> 
> var genMetricListCmd = &cobra.Command{
> 	Use:   "metric-list",
> ```

I was trying to imagine a scenario where a command like this would have been useful.

A few months ago I know @a-entin had some struggles finding a good "source of truth" for CRDB metrics and their descriptions. 

I think this command would have provided it, had it existed at the time!
___
*[`pkg/cli/gen.go` line 359 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109042#-NcOFvSa2Omgh-J3gAMW:-NcOFvSa2Omgh-J3gAMX:b-1939ub) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f6a524f8743c118ab259e1f25cd84e480446fe9/pkg/cli/gen.go#L359)):*
> ```Go
> 		case <-readyCh:
> 		case <-time.After(5 * time.Second):
> 			return errors.Newf("could not initialize server in time")
> ```

nit: is there any sort of remediation/advice we can provide the user in this error message? I feel like if the test server initialization timed out, there's a good chance that if we retried the command, it'd work the 2nd time, no?
___
*[`pkg/server/server.go` line 252 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109042#-NcOOxoLB6v3FlqEiKYq:-NcOOxoLB6v3FlqEiKYr:bv2u51o) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f6a524f8743c118ab259e1f25cd84e480446fe9/pkg/server/server.go#L252)):*
> ```Go
> 	// Do not use this for metrics that could possibly be reported by secondary
> 	// tenants, i.e. those also registered in tenant.go.
> 	nodeRegistry := metric.NewRegistry()
> ```

nit: Is there maybe a more descriptive name than "node" registry? I feel like the scope of "node" is not immediately clear. Is there a term closer to "kv" or "storage" that'd be clearer for naming? 
___
*[`pkg/server/server.go` line 661 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109042#-NcOQ0a5BZU2V27Vn4P1:-NcOQ0a5BZU2V27Vn4P2:bnd1irw) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f6a524f8743c118ab259e1f25cd84e480446fe9/pkg/server/server.go#L661)):*
> ```Go
> 		return nil, err
> 	}
> 	appRegistry.AddMetricStruct(protectedtsProvider.Metrics())
> ```

Just wanted to confirm - this belongs in the appRegistry? I'm not familiar with the ptprovider package, but I noticed it lives under `pkg/kv`, so just wanted to double check this doesn't belong in `nodeRegistry`.
___
*[`pkg/server/tenant.go` line 665 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109042#-NcOQvYq4pmp3NZoMplU:-NcOQvYq4pmp3NZoMplV:b4nk76y) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f6a524f8743c118ab259e1f25cd84e480446fe9/pkg/server/tenant.go#L665)):*
> ```Go
> 	// We can now add the node registry.
> 	s.recorder.AddNode(
> 		metric.NewRegistry(), // node registry -- unused here
> ```

Have we double-checked if this breaks any of the existing app-tenant-available metrics charts in DB Console? I think it's okay if it does for now, as long as we know which ones are affected.
___
*[`pkg/server/status/recorder.go` line 143 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109042#-NcOQato1x1smFTylYRE:-NcOQato1x1smFTylYRF:b-lsard4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f6a524f8743c118ab259e1f25cd84e480446fe9/pkg/server/status/recorder.go#L143)):*
> ```Go
> 		// its own separate registry to avoid things such as colliding labels.
> 		logRegistry *metric.Registry
> 		// sysRegistry contains the system-wide metrics.
> ```

nit: Can we elaborate a bit more on what we mean by "system-wide"? Maybe provide an example of what is/is not considered "system-wide"?
___
*[`pkg/server/status/recorder.go` line 395 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109042#-NcOSFP0-GedqiLAXCIR:-NcOSFP1BUiy1PWd4JoM:b-yifpbq) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f6a524f8743c118ab259e1f25cd84e480446fe9/pkg/server/status/recorder.go#L395)):*
> ```Go
> 	recorder.record(&data)
> 
> 	// Record time series from node-level registries for secondary tenants.
> ```

nit: do these tenant-level registries still count as "node-level"? Or would they now be more "app-level"?
___
*[`pkg/server/status/recorder.go` line 418 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109042#-NcOSbkH-tcBJI_yorUx:-NcOSbkH-tcBJI_yorUy:biwdxi6) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f6a524f8743c118ab259e1f25cd84e480446fe9/pkg/server/status/recorder.go#L418)):*
> ```Go
> 
> 		// Now record secondary tenant store metrics, if any exist in the process.
> 		for tenantID := range mr.mu.tenantRegistries {
> ```

Even though these are storage-related, does the fact that they're recorded at the tenant level make them "app-level"?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109042)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @a-entin, @abarganier, and @yuzefovich)

___
*[`-- commits` line 9 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109042#-NcO5Xk_8PrjNRQYpOs3):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: should we add a unit test case for this in `TestRenderHTML`?
</blockquote></details>

If my reading is right, it's already in there (2nd test case).
___
*[`pkg/cli/gen.go` line 321 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109042#-NcODtVzCUzlN_v2uDm0:-NcS019e2V9cq686qZli:b-pbdqz3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f6a524f8743c118ab259e1f25cd84e480446fe9/pkg/cli/gen.go#L321)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

I was trying to imagine a scenario where a command like this would have been useful.

A few months ago I know @a-entin had some struggles finding a good "source of truth" for CRDB metrics and their descriptions. 

I think this command would have provided it, had it existed at the time!
</blockquote></details>

Agreed.
___
*[`pkg/cli/gen.go` line 350 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109042#-NcO6Y8m0Mvogl0FBKVa:-NcRxvUtDsEeqUSy1_ca:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f6a524f8743c118ab259e1f25cd84e480446fe9/pkg/cli/gen.go#L350)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: missing period.
</blockquote></details>

Done.
___
*[`pkg/cli/gen.go` line 359 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109042#-NcOFvSa2Omgh-J3gAMW:-NcS047N73S9OD5qFkVB:bbtuzss) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f6a524f8743c118ab259e1f25cd84e480446fe9/pkg/cli/gen.go#L359)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: is there any sort of remediation/advice we can provide the user in this error message? I feel like if the test server initialization timed out, there's a good chance that if we retried the command, it'd work the 2nd time, no?
</blockquote></details>

it's an assertion failure - we're not expecting a failure here. If there's one they should contact support.
___
*[`pkg/server/server.go` line 252 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109042#-NcOOxoLB6v3FlqEiKYq:-NcS1VQy3uUvx4I-9F3J:b-c52rlc) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f6a524f8743c118ab259e1f25cd84e480446fe9/pkg/server/server.go#L252)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: Is there maybe a more descriptive name than "node" registry? I feel like the scope of "node" is not immediately clear. Is there a term closer to "kv" or "storage" that'd be clearer for naming?
</blockquote></details>

Feel free to make a suggestion?
___
*[`pkg/server/server.go` line 561 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109042#-NcOAGyJA5jFoOaa5tEf:-NcRy5MD9zCjesyWRo8f:boj1qgt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f6a524f8743c118ab259e1f25cd84e480446fe9/pkg/server/server.go#L561)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

IIUC KV flow controller is on the KV server side, so I'd expect it to be in `nodeRegistry`.
</blockquote></details>

Good catch. Done.
___
*[`pkg/server/server.go` line 661 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109042#-NcOQ0a5BZU2V27Vn4P1:-NcS0cjtCxw1o0Xr2EIb:b54czb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f6a524f8743c118ab259e1f25cd84e480446fe9/pkg/server/server.go#L661)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

Just wanted to confirm - this belongs in the appRegistry? I'm not familiar with the ptprovider package, but I noticed it lives under `pkg/kv`, so just wanted to double check this doesn't belong in `nodeRegistry`.
</blockquote></details>

Given that this is also done in tenant.go, then yes nearly by definition it goes to appRegistry.
___
*[`pkg/server/server.go` line 1806 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109042#-NcOCzc58erC8D3_Ue7r:-NcRy83V9z0rOUqrel9b:b-p5puhz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f6a524f8743c118ab259e1f25cd84e480446fe9/pkg/server/server.go#L1806)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I'm wondering whether the app registry is the right one for Go scheduler latency, seems closer to server registry, no?
</blockquote></details>

Indeed. Done.
Although the fact this is called unconditionally is also a bug - filed #109225.
___
*[`pkg/server/tenant.go` line 663 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109042#-NcODmEI2ZrFGE4Wz9TX:-NcRzYjg7XdccrfF2pl3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f6a524f8743c118ab259e1f25cd84e480446fe9/pkg/server/tenant.go#L663)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: this comment now seems out of date.
</blockquote></details>

Done.
___
*[`pkg/server/tenant.go` line 665 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109042#-NcOQvYq4pmp3NZoMplU:-NcRzZlWE7nVTwRpGZJQ:b-ozzl2m) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f6a524f8743c118ab259e1f25cd84e480446fe9/pkg/server/tenant.go#L665)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

Have we double-checked if this breaks any of the existing app-tenant-available metrics charts in DB Console? I think it's okay if it does for now, as long as we know which ones are affected.
</blockquote></details>

I believe this PR is feature-neutral: its only visible purpose is to add a field in the ChartCatalog response, that the new CLI command can use.

It's when about we go from here to fixing #102378 that we will need to be careful.
___
*[`pkg/server/status/recorder.go` line 143 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109042#-NcOQato1x1smFTylYRE:-NcS14IR5pDTLAOjVqgz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f6a524f8743c118ab259e1f25cd84e480446fe9/pkg/server/status/recorder.go#L143)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: Can we elaborate a bit more on what we mean by "system-wide"? Maybe provide an example of what is/is not considered "system-wide"?
</blockquote></details>

Done.
___
*[`pkg/server/status/recorder.go` line 222 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109042#-NcOEYUlByma37zvf0Os:-NcS-Nzn4fSvEWbr_7aJ:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f6a524f8743c118ab259e1f25cd84e480446fe9/pkg/server/status/recorder.go#L222)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: the comment is now outdated.
</blockquote></details>

Fixed.
___
*[`pkg/server/status/recorder.go` line 395 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109042#-NcOSFP0-GedqiLAXCIR:-NcS1ENC5MVmQfQTo82r:b8cg197) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f6a524f8743c118ab259e1f25cd84e480446fe9/pkg/server/status/recorder.go#L395)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: do these tenant-level registries still count as "node-level"? Or would they now be more "app-level"?
</blockquote></details>

Good call. Indeed.
___
*[`pkg/server/status/recorder.go` line 418 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109042#-NcOSbkH-tcBJI_yorUx:-NcS1K1X6o2WL9IcC7tT:b-9wdi06) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f6a524f8743c118ab259e1f25cd84e480446fe9/pkg/server/status/recorder.go#L418)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

Even though these are storage-related, does the fact that they're recorded at the tenant level make them "app-level"?
</blockquote></details>

Yes, correct.
___
*[`pkg/server/status/recorder.go` line 440 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109042#-NcOEf6aE20LgdtfyuhO:-NcS-jS32g7zYXSpwGts:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f6a524f8743c118ab259e1f25cd84e480446fe9/pkg/server/status/recorder.go#L440)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: `s/firt/first/`.
</blockquote></details>

Done.
___
*[`pkg/server/status/recorder.go` line 560 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109042#-NcOF0me0i211gayYgY8:-NcS-kUB6Z9hdEMKbDQe:boj1qgt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f6a524f8743c118ab259e1f25cd84e480446fe9/pkg/server/status/recorder.go#L560)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Should we also do the same for `sysRegistry`?
</blockquote></details>

Good catch. Done.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 18 of 18 files at r4, 4 of 4 files at r5, 17 of 17 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109042#-:-NcT7tkIDldSG0-61SMA:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @a-entin, @abarganier, and @knz)

___
*[`-- commits` line 9 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109042#-NcO5Xk_8PrjNRQYpOs3):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

If my reading is right, it's already in there (2nd test case).
</blockquote></details>

Indeed, I missed it.
___
*[`pkg/server/tenant.go` line 106 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/109042#-NcT5Q5i7GMg1G89qGTT:-NcT5Q5j5l98EXlmIS-n:b-ec8hqs) ([raw file](https://github.com/cockroachdb/cockroach/blob/de51b7620ff06e5fa1afc22a8a9b5f8b1fd2fcac/pkg/server/tenant.go#L106)):*
> ```Go
> 
> 	// Metric registries.
> 	// See the explanatory comments in server.go and status/recorder.g o
> ```

nit: `s/recorder.g o/recorder.go/`.
___
*[`pkg/server/status/recorder.go` line 311 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/109042#-NcT7Lpv16La6ezTioz2:-NcT7Lpv16La6ezTioz3:bsenz9t) ([raw file](https://github.com/cockroachdb/cockroach/blob/de51b7620ff06e5fa1afc22a8a9b5f8b1fd2fcac/pkg/server/status/recorder.go#L311)):*
> ```Go
> 	}
> 	topLevel := map[string]interface{}{
> 		fmt.Sprintf("node.%d", mr.mu.desc.NodeID):     mr.mu.nodeRegistry,
> ```

nit: should we add app and sys registries here too? It looks like `MarshalJSON` is only used in tests, but it might be good to adjust it for completeness sake.

**Comment by abarganier** [comment]
Issues like https://github.com/cockroachdb/cockroach/issues/108929, and then https://github.com/cockroachdb/cockroach/issues/109225, raise a couple questions about what we want to do for in-process app tenants for these different registries.

In https://github.com/cockroachdb/cockroach/issues/108929 we had all the app-tenant metrics in the same registry, and those were added to the "parent recorder" (this is the one that TSDB actually scrapes) as a tenant-level registry. This was done as part of the SQL server pre-start: https://github.com/cockroachdb/cockroach/blob/9d6e4b0fe4f69c1628521e082b934c7ff13483d1/pkg/server/tenant.go#L677

Prior to this PR we're discussing, this tenant registry contained just about everything for the tenant, including metrics from the RuntimeStatsSampler. This is what caused issues like https://github.com/cockroachdb/cockroach/issues/108929 - CPU metrics were being recorded for both the app-tenant and system-tenant. This is shown in my [comment here](https://github.com/cockroachdb/cockroach/issues/108929#issuecomment-1682986684) where I perform a `tsdump`. 

If we query those metrics and say "give me them for all tenants", TSDB would sum them together across tenants, leading to incorrect multiples of the actual value (actualVal * numTenants). As a result, incorrect values are reported in DB Console metrics pages when you select "All" from the tenant dropdown, so long as the metric's recorded for sys & app tenant. (NB: for some metrics, like `sql_insert_count`, sum would actually be the correct aggregation to use). 

As of this PR, these metrics from the RuntimeStatsSampler are added to the tenant's `sysRegistry`, which isn't provided to the parent recorder for the tenant. This means that https://github.com/cockroachdb/cockroach/issues/108929 would no longer occur, because these CPU metrics would only exist in TSDB for the system tenant. The value would be correct, because it was only recorded once into TSDB.

I think there's a bit of a requirements discussion to be had here. 

Do we *want* secondary app tenants to have access to things like hardware metrics? The spirit of https://github.com/cockroachdb/cockroach/issues/102378 makes me think that we don't. If an app tenant wants to see hardware metrics (and other "system" metrics), then they need to enable a tenant capability that allows them to query metrics for the system tenant. It's worth noting though that this would give them access to **all** system tenant metrics. Once the data's in TSDB, we lose the concept of "server layering"/metric classification.

If we take this approach, it should get rid of problems similar to what's happening in https://github.com/cockroachdb/cockroach/issues/108929 by only recording certain metrics for the system tenant. There will still be metrics however that exist across *all* tenants. In this case, we would still need to ensure that TSDB queries used for things like DB Console charts use the correct aggregation. It's not guaranteed that `sum` is always the right choice. Without knowing much about the DB Console code, I'd guess `sum` might be a default. If so, there's probably some work involved to define the proper aggregation for each chart (or maybe I'm wrong and this is done already).

LMK your thoughts.

**Comment by knz** [comment]
>  It's worth noting though that this would give them access to all system tenant metrics.

Not quite - we could filter the query to restrict it to only those metrics that are allowed. This is not too unpleasant to do because they share a common name prefix.

**Comment by knz** [comment]
So Alex and I just talked about this.

Alex was primarily interested in this conversation from the perspective of a *future* way to consume metrics, where we'll want potentially to merge metrics from different tenants together.

In that context, we will to be extra careful when there are "system metrics" (like CPU) that are different per tenant. For example, if we use separate-process deployments (in serverless), we have one set of system metrics per tenant, and the question arises: what do we record, how do we show it?

What we settled on in this conversation:

- the present PR is making incremental progress on the topics of 1) not recording system metrics multiple times in the same process 2) separation in the source code of the metric (names) that belong to storage vs app, for the later work in #102378.

- we're still concerned (for the later work in #102378) about whether or not to display system metris from the secondary tenant's view of metrics (e.g. via DB Console), in the case of shared-process deployments. Do we want them to be visible without a capability or not?  We will discuss this later during the work on #102378.

- to the question of whether and how to aggregate tenant metrics across tenants, we propose to punt this question until we make progress on the obs platform roadmap. There's a chance that we will not need to answer this question in the context of tsdb+dbconsole because we'd be working in a different environment.

**Comment by knz** [comment]
NB: @abarganier will investigate #109727 to see how it needs to be altered in light of the present PR.

**Comment by knz** [comment]
TFYRs!

bors r=yuzefovich

**Pull request merged**
