### PR TITLE
sql: unify span generation code in `sql` via introduction of `SpanBuilder`

### LINKED ISSUE #42517: sql: unify span generation code
We currently have a zoo of code for generating spans, each with its own quirks:
 - `spansFromConstraint` (used by `execFactory.ConstructScan`)
 - `sqlbase.MakeSpanFromEncDatums` (used by `execinfra.joinReader`) 
 - `sqlbase.EncodePartialIndexKey / EncodePartialIndexSpan`

The scan and the join reader have their own separate logic for when we can split a span into column families (and these are bound to rot/diverge given the work we are doing with families in secondary indexes):
https://github.com/cockroachdb/cockroach/blob/845bd7639fe144017e81eed59cd20f449239018c/pkg/sql/execinfra/indexjoiner.go#L223
https://github.com/cockroachdb/cockroach/blob/845bd7639fe144017e81eed59cd20f449239018c/pkg/sql/execinfra/joinreader.go#L352
https://github.com/cockroachdb/cockroach/blob/7bfa8f807c4960da6daf2ea31fd3ba70a7156354/pkg/sql/opt_index_selection.go#L164

We need to come up with a single consistent well-documented interface that is used everywhere. It's ok if we have a bunch of variants (e.g. for `Datums` vs `EncDatums`) as long as they all implement the same semantics.

I think there should be a `SpanBuilder` that you initialize with the index descriptor, optionally call something like `SetNeededFamilies` (which enables splitting into families) and which you can then use repeatedly to generate spans. This would hide the logic related to reusing the key interstices. There could even be a `SpanBuilder` cache to reuse stuff across queries.

### PR DESCRIPTION
**Pull request by rohany**
There is a wide variety of different span generation code in
the `sql` and child packages that all implement similar logic.
In addition, these different functions all implement similar
column family related optimizations. A single place for span
generation and related optimizations will avoid these different
codepaths from diverging in the future.

Fixes #42517.

Release note: None

### CODE REVIEW

**Comment by rohany** [comment]
This is a first pass at feeling out what the interface for this `SpanBuilder` should look like, so I wanted to get some thoughts comments. Some of the functions are a bit strange interface wise due to some requirements of the different ways spans were generated in the other parts of the code.

I'll look into updating the way that constraints are turned into spans either in this or a follow up PR to remove the need to allocate the nested list of interstices.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42688)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @RaduBerinde, and @rohany)

___
*[pkg/sql/execinfra/span_builder.go, line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42688#-LuIILV0904Q5REeG47f:-LuIILV0904Q5REeG47g:bkf68hb) ([raw file](https://github.com/cockroachdb/cockroach/blob/f39de273179fbb7d5a8dc0b06b1abea71d2aa6a2/pkg/sql/execinfra/span_builder.go#L13)):*
> ```Go
> package execinfra
> 
> // TODO (rohany): I want to put this in sqlbase, but it seems like i can't get the constraints package there.
> ```

maybe it belongs in `sql/row` ?
___
*[pkg/sql/execinfra/span_builder.go, line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42688#-LuIIX_S8XUIkJUVMnIf:-LuIIX_S8XUIkJUVMnIg:b5q7dca) ([raw file](https://github.com/cockroachdb/cockroach/blob/f39de273179fbb7d5a8dc0b06b1abea71d2aa6a2/pkg/sql/execinfra/span_builder.go#L56)):*
> ```Go
> 
> 	// TODO (rohany): does this need to be with mutations here?
> 	colIdxMap := table.ColumnIdxMap()
> ```

We are allocating this stuff just to figure out the types of the columns, it's probably better to just search for them in the descriptor.
___
*[pkg/sql/execinfra/span_builder.go, line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42688#-LuIJNuuB6iUQLl0avOP:-LuIJNuvD4vUIQqsCRRk:b-mu86hn) ([raw file](https://github.com/cockroachdb/cockroach/blob/f39de273179fbb7d5a8dc0b06b1abea71d2aa6a2/pkg/sql/execinfra/span_builder.go#L92)):*
> ```Go
> 
> // SpansFromConstraint generates spans from an optimizer constraint.
> // TODO (rohany): see if this can be changed to a more general interface?
> ```

We should consider an interface `SpanValueGetter` used to get the value of the `i`-th index column and provide a few implementations (using `Datums`, `EncDatums` with or without col maps, constraint.Span).

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42688)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @RaduBerinde)

___
*[pkg/sql/execinfra/span_builder.go, line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42688#-LuIILV0904Q5REeG47f:-LuIfl5K1zttXsNVjJwh:b-3fdf5w) ([raw file](https://github.com/cockroachdb/cockroach/blob/f39de273179fbb7d5a8dc0b06b1abea71d2aa6a2/pkg/sql/execinfra/span_builder.go#L13)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

maybe it belongs in `sql/row` ?
</blockquote></details>

ok, let me see if i can get out of a dependency cycle there.
___
*[pkg/sql/execinfra/span_builder.go, line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42688#-LuIIX_S8XUIkJUVMnIf:-LuIfrHzCvN2ydYysJNY:b2ni9bh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f39de273179fbb7d5a8dc0b06b1abea71d2aa6a2/pkg/sql/execinfra/span_builder.go#L56)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We are allocating this stuff just to figure out the types of the columns, it's probably better to just search for them in the descriptor.
</blockquote></details>

ok.
___
*[pkg/sql/execinfra/span_builder.go, line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42688#-LuIJNuuB6iUQLl0avOP:-LuIfw85844GWu7vijrL:bbrihr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/f39de273179fbb7d5a8dc0b06b1abea71d2aa6a2/pkg/sql/execinfra/span_builder.go#L92)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We should consider an interface `SpanValueGetter` used to get the value of the `i`-th index column and provide a few implementations (using `Datums`, `EncDatums` with or without col maps, constraint.Span).
</blockquote></details>

That sounds good -- would we want that for enc datums (because we'd have to decode them on every get). But i guess this code has to decode the datums to encode them anyway?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42688)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rohany)

___
*[pkg/sql/execinfra/span_builder.go, line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42688#-LuIJNuuB6iUQLl0avOP:-LuImSWl8znEpMO6qWXc:b-31wy8i) ([raw file](https://github.com/cockroachdb/cockroach/blob/f39de273179fbb7d5a8dc0b06b1abea71d2aa6a2/pkg/sql/execinfra/span_builder.go#L92)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

That sounds good -- would we want that for enc datums (because we'd have to decode them on every get). But i guess this code has to decode the datums to encode them anyway?
</blockquote></details>

I see. Then maybe an interface like `AppendSpanValue` which appends the encoded value of the `i`th column to a key.

**Comment by rohany** [comment]
I might move this idea of a `SpanGetter` interface into a new PR/issue, as it seems to be diving into the different methods of key generation (and all their idiosyncrasies). Additionally, it appears to be a decently large refactor to get this interface on all the types we want (given the different locations of `Datums`, `Constraint` and `EncDatums`.

**Comment by rohany** [comment]
PTAL -- i'm tracking unifying the key generation code itself in #42738.

**Comment by rohany** [comment]
Adding this into the span builder would be nice -- https://github.com/cockroachdb/cockroach/pull/38086

**Comment by rohany** [comment]
Pinging @RaduBerinde, can you take a look at this again?

**Review by RaduBerinde — APPROVED** [review]
:lgtm: (but @jordanlewis should take a look too)

Can you also modify the span code in row/fk_spans.go to use the builder? https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/row/fk_spans.go#L35

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42688#-:-LvCpwgw3lxPKfLjE4qv:b-hey7v)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @RaduBerinde, and @rohany)

___
*[pkg/sql/row/span_builder.go, line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42688#-LvCp1RdE_yFofXGBB2x:-LvCp1RdE_yFofXGBB2y:b-xc9vtp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea9bd41fc7da403bafcae26208cc4860eaaa209c/pkg/sql/row/span_builder.go#L40)):*
> ```Go
> 	interstices [][]byte
> 
> 	neededFamilies []sqlbase.FamilyID
> ```

maybe this should be a FastIntSet
___
*[pkg/sql/row/span_builder.go, line 44 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42688#-LvCpfnWD8Yc1LWLmywp:-LvCpfnX8Bj5YBBrvlbD:brwv6vf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea9bd41fc7da403bafcae26208cc4860eaaa209c/pkg/sql/row/span_builder.go#L44)):*
> ```Go
> 
> // Use some functions that aren't needed right now to make the linter happy.
> var _ = (*SpanBuilder)(nil).UnsetNeededColumns
> ```

[nit] can just be `var _ = (*SpanBuilder).UnsetNeededColumns`

**Review by rohany — COMMENTED** [review]
Done -- some logictests had to change. The spanbuilder right now won't split the lookup into a lookup on the first column family if the table only has 1 column family to begin with.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42688#-:-LvG_n_b8VzWhmbcbadw:brsj28w)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @RaduBerinde, and @rohany)

___
*[pkg/sql/row/span_builder.go, line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42688#-LvCp1RdE_yFofXGBB2x:-LvG_ocO9g2v8fq25j0E:bekx59k) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea9bd41fc7da403bafcae26208cc4860eaaa209c/pkg/sql/row/span_builder.go#L40)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

maybe this should be a FastIntSet
</blockquote></details>

I'll have to change some other unrelated code -- I'll can change that in a followup PR.
___
*[pkg/sql/row/span_builder.go, line 44 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42688#-LvCpfnWD8Yc1LWLmywp:-LvG_t5JDojfLrtKykfd:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea9bd41fc7da403bafcae26208cc4860eaaa209c/pkg/sql/row/span_builder.go#L44)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] can just be `var _ = (*SpanBuilder).UnsetNeededColumns`
</blockquote></details>

done

**Review by RaduBerinde — COMMENTED** [review]
Heh, yeah, this is how it was initially in #42572. :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42688#-:-LvGi5516XKltV_9F-dQ:b8t5w7i)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @RaduBerinde, and @rohany)

___
*[pkg/sql/row/fk_spans.go, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42688#-LvGiXCk19TyOuiyH54m:-LvGiXCk19TyOuiyH54n:b-6b8s75) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce9632be30b433a72dee403f04edaf4778ffbaf2/pkg/sql/row/fk_spans.go#L31)):*
> ```Go
> 	// We can always return the first element in the resulting span list -- if we can't split the span, then it
> 	// will be the original span. If we split the span, we only requested one family, so the slice has length 1 anyway.
> 	return f.spanBuilder.MaybeSplitSpanIntoSeparateFamilies(span, f.prefixLen)[0], nil
> ```

It's kind of annoying that we allocate spans and keys for all the families and the slice, just to get the first one. I don't have any data showing that this would make a big difference. But it might be worth adding a simpler API to get just the first family span.

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42688)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @RaduBerinde, and @rohany)

___
*[pkg/sql/row/fk_spans.go, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42688#-LvGiXCk19TyOuiyH54m:-LvGmO3_D0fw8WYGMxU0:bewxm2p) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce9632be30b433a72dee403f04edaf4778ffbaf2/pkg/sql/row/fk_spans.go#L31)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It's kind of annoying that we allocate spans and keys for all the families and the slice, just to get the first one. I don't have any data showing that this would make a big difference. But it might be worth adding a simpler API to get just the first family span.
</blockquote></details>

Let me think about it -- however we only requested the first family, so only a single allocation is made.

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/row/fk_spans.go, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42688#-LvGiXCk19TyOuiyH54m:-LvGnWg95tXpHa-ZFAE9:bgawrok) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce9632be30b433a72dee403f04edaf4778ffbaf2/pkg/sql/row/fk_spans.go#L31)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Let me think about it -- however we only requested the first family, so only a single allocation is made.
</blockquote></details>

Oh, I missed that, never mind!

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42688)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @RaduBerinde, and @rohany)

___
*[pkg/sql/row/fk_spans.go, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42688#-LvGiXCk19TyOuiyH54m:-LvGoKS29XzMBfErJSgv:b-hlyxu9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce9632be30b433a72dee403f04edaf4778ffbaf2/pkg/sql/row/fk_spans.go#L31)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Oh, I missed that, never mind!
</blockquote></details>

no, this is still a valid point -- we allocate an extra end key and still have to allocate a roachpb.Spans for no reason.

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42688)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @RaduBerinde, and @rohany)

___
*[pkg/sql/row/fk_spans.go, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42688#-LvGiXCk19TyOuiyH54m:-LvGpFoUETz4dwwlExBw:b5g6ih4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce9632be30b433a72dee403f04edaf4778ffbaf2/pkg/sql/row/fk_spans.go#L31)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

no, this is still a valid point -- we allocate an extra end key and still have to allocate a roachpb.Spans for no reason.
</blockquote></details>

Alright, this should look better.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42688)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @RaduBerinde, and @rohany)

___
*[pkg/sql/row/fk_spans.go, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42688#-LvGiXCk19TyOuiyH54m:-LvGpfxtDbCvGHjO9jdU:bcuiqp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce9632be30b433a72dee403f04edaf4778ffbaf2/pkg/sql/row/fk_spans.go#L31)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

Alright, this should look better.
</blockquote></details>

Now we're allocating the `FamilyID` slice :)  Well, not sure it gets allocated on the heap or stack. But we should just pass the family count to `CanSplitSpanIntoSeparateFamilies` since that's the only thing that is used.

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42688)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis, @RaduBerinde, and @rohany)

___
*[pkg/sql/row/fk_spans.go, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42688#-LvGiXCk19TyOuiyH54m:-LvGrRk3AVhOfBIvIWZe:bxab1gn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce9632be30b433a72dee403f04edaf4778ffbaf2/pkg/sql/row/fk_spans.go#L31)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Now we're allocating the `FamilyID` slice :)  Well, not sure it gets allocated on the heap or stack. But we should just pass the family count to `CanSplitSpanIntoSeparateFamilies` since that's the only thing that is used.
</blockquote></details>

I think it would get stack allocated. Either way the allocation is unnecessary.

Thanks for the patience going back and forth on this!

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42688)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @rohany)

___
*[pkg/sql/row/fk_spans.go, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42688#-LvGiXCk19TyOuiyH54m:-LvGsQWP6E1bCdxV2Ob0:b-iz06sa) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce9632be30b433a72dee403f04edaf4778ffbaf2/pkg/sql/row/fk_spans.go#L31)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

I think it would get stack allocated. Either way the allocation is unnecessary.

Thanks for the patience going back and forth on this!
</blockquote></details>

Awesome, looks great! Thank you!

**Review by jordanlewis — APPROVED** [review]
This looks great! Really sorry about the long turnaround. I had one packaging suggestion but I'm happy to see this go in either way.

I do think that this would be a great place to add unit tests...

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42688#-:-Lw_OfqT47L0fT2nS6k2:b-86wwx8)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @rohany)

___
*[pkg/sql/row/span_builder.go, line 27 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42688#-Lw_NgsWCEnVLGk0GqEX:-Lw_NgsX8evuzq9NIEe3:b95txz0) ([raw file](https://github.com/cockroachdb/cockroach/blob/10cd146f34a1c0588139890cbbbd7bac0e8b07be/pkg/sql/row/span_builder.go#L27)):*
> ```Go
> 
> // SpanBuilder is a single struct for generating key spans from Constraints, Datums and encDatums.
> type SpanBuilder struct {
> ```

I think you should put this into a new package, `pkg/sql/span`, so you can call it `span.Builder`, and let people who don't depend on `row` depend on this.

**Comment by rohany** [comment]
TFTRs! Repackaged and added a test. The remaining methods are mostly passthrough and are tested via their use in other parts of the code -- though I plan on adding more tests once I get to adding some secondary index + column family related optimizations though, where things get more tricky.

bors r+

**Pull request merged**
