### PR TITLE
lease: add a gauge for outstanding leases

### LINKED ISSUE #57456: sql: metric for outstanding leases
We should have a gauge metric that tracks the number of outstanding leases per node. We're concerned that the lease manager's limit on refreshing leases causes problems, and this metric could be a good way to detect such problems.

### PR DESCRIPTION
**Pull request by jordanlewis**
sql.leases.active is a gauge of the outstanding leases in the cluster.

Fixes #57456.

image

Release note (ui change): the sql.leases.active gauge is now available
to track the outstanding descriptor leases in the cluster.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
You'll need to add this to the chart catalog.

A test also might be nice. Maybe as simple as creating a table and database or something and then using them and watching the gauge go up by 2. Fancier if you tweak the settings so that leases get dropped and then watch it go down when the lease manager releases them. 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57561#-:-MNiKY87EOcyz1VIxFpU:b-3xewwo)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by jordanlewis** [comment]
I've added to the chart catalog and added a test. The test might be flaky - I think if it's going to be flaky, it's probably easier to just delete it than deflake :/

**Review by ajwerner — COMMENTED** [review]
sort of a nit but honestly I'd rather have a metrics struct with one metric in the Manager than a free floating metric 

> Reviewed 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57561#-:-MRv-XcD2cKk3r0INlVr:b8pwf6r)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/catalog/lease/lease.go, line 2157 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57561#-MRv-5s8-XsPPkT2_yfW:-MRv-5s8-XsPPkT2_yfX:b-f3n4ka) ([raw file](https://github.com/cockroachdb/cockroach/blob/a99f645fb4e9e880d899c109e11ff0812d9b4e6b/pkg/sql/catalog/lease/lease.go#L2157)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> // MetricsStruct returns a struct containing all of this Manager's metrics.
> func (m *Manager) MetricsStruct() Metrics {
> 	return Metrics{
> 		OutstandingLeases: m.storage.outstandingLeases,
> 	}
> }
> ```
</details>


I feel like generally just store the metric struct on the manager and return it. Then you wouldn't need the testing method to access the one gauge.

**Comment by jordanlewis** [comment]
> I feel like generally just store the metric struct on the manager and return it. Then you wouldn't need the testing method to access the one gauge.

The reason I didn't do this is that the `storage` struct is the thing that has the method that actually needs to touch the gauge. So I could restructure things to fix that but it seemed like maybe it wasn't a big deal to just do this.

**Review by ajwerner — COMMENTED** [review]
fair enough, `storage` is embedded in `Manager` so you could do what I said but just stick in it storage but no biggie either way. 

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57561#-:-MSEndu_2fkH8MFPC5rr:b-ec2ppo)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @jordanlewis)

**Review by ajwerner — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57561#-:-MSEnpN45tJyoqDKWa7t:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @jordanlewis)

**Comment by jordanlewis** [comment]
Thanks!

bors r+

**Pull request merged**
