### PR TITLE
sql: cleanup making copies of the eval context

### PR DESCRIPTION
**Pull request by yuzefovich**
This PR audits all processors to avoid now-redundant (as of #125715) copies of the `eval.Context` as well as performs some miscellaneous cleanup along the way.

Some microbenchmarks:
```
name                   old time/op    new time/op    delta
LastWriteWinsInsert-8    1.37ms ±13%    1.41ms ±16%    ~     (p=0.265 n=20+20)

name                   old alloc/op   new alloc/op   delta
LastWriteWinsInsert-8     253kB ± 2%     247kB ± 2%  -2.65%  (p=0.000 n=19+20)

name                   old allocs/op  new allocs/op  delta
LastWriteWinsInsert-8     1.67k ± 0%     1.67k ± 0%  -0.18%  (p=0.033 n=18+19)
```
```
FlowSetup/vectorize=true/distribute=true-8       144µs ± 3%     142µs ± 3%   -1.25%  (p=0.005 n=25+25)
FlowSetup/vectorize=true/distribute=false-8      139µs ± 6%     138µs ± 3%     ~     (p=0.260 n=24+22)
FlowSetup/vectorize=false/distribute=true-8      137µs ± 2%     138µs ± 4%     ~     (p=0.158 n=22+25)
FlowSetup/vectorize=false/distribute=false-8     132µs ± 2%     133µs ± 3%   +1.21%  (p=0.001 n=24+25)

name                                          old alloc/op   new alloc/op   delta
FlowSetup/vectorize=true/distribute=true-8      22.9kB ± 9%    18.9kB ± 5%  -17.18%  (p=0.000 n=24+21)
FlowSetup/vectorize=true/distribute=false-8     21.3kB ±10%    17.7kB ±12%  -17.04%  (p=0.000 n=22+22)
FlowSetup/vectorize=false/distribute=true-8     27.1kB ± 0%    25.3kB ± 0%   -6.62%  (p=0.000 n=20+20)
FlowSetup/vectorize=false/distribute=false-8    25.6kB ± 0%    23.8kB ± 0%   -6.99%  (p=0.000 n=20+20)

name                                          old allocs/op  new allocs/op  delta
FlowSetup/vectorize=true/distribute=true-8         234 ± 2%       231 ± 1%   -1.01%  (p=0.000 n=20+21)
FlowSetup/vectorize=true/distribute=false-8        219 ± 8%       217 ± 7%   -0.93%  (p=0.016 n=22+22)
FlowSetup/vectorize=false/distribute=true-8        229 ± 0%       228 ± 0%   -0.44%  (p=0.000 n=21+21)
FlowSetup/vectorize=false/distribute=false-8       212 ± 0%       211 ± 0%   -0.47%  (p=0.000 n=20+20)
```

Epic: CRDB-39063.

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r1, 20 of 20 files at r2, 3 of 3 files at r3, 29 of 29 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126036#-:-O0B0Hvi-_I8fzAN48z0:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @yuzefovich)

___
*[`pkg/sql/execinfra/flow_context.go` line 49 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126036#-O0Azd9uEYqFUn2EaWBI:-O0Azd9uEYqFUn2EaWBJ:bucihsv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c67bd53a5c44109f3cfe8e52c9fc8c429782ffbb/pkg/sql/execinfra/flow_context.go#L49)):*
> ```Go
> 	// expressions with this EvalCtx should get a copy with NewEvalCtx instead
> 	// of using this field.
> 	EvalCtx *eval.Context
> ```

Would making this un-exported be helpful in limiting its usage?
___
*[`pkg/sql/execinfra/processorsbase.go` line 750 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126036#-O0Azo5qAAyj6IWYoRMf:-O0Azo5qAAyj6IWYoRMg:bya23ik) ([raw file](https://github.com/cockroachdb/cockroach/blob/c67bd53a5c44109f3cfe8e52c9fc8c429782ffbb/pkg/sql/execinfra/processorsbase.go#L750)):*
> ```Go
> // execinfrapb.ProcessorSpec for more details).
> //
> // NB: it is assumed that the caller will not modify the eval context.
> ```

In the long-term it'd be nice to follow the example of mutable and immutable descriptors so that we can lean on the type system to enforce this. The API would make it impossible for an ImmutableEvalCtx to be mutated (outside of a small part of trusted code).
___
*[`pkg/sql/execinfra/processorsbase.go` line 794 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126036#-O0B-dFL8oNuCC-lDnDI:-O0B-dFL8oNuCC-lDnDJ:b-ye7y3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/c67bd53a5c44109f3cfe8e52c9fc8c429782ffbb/pkg/sql/execinfra/processorsbase.go#L794)):*
> ```Go
> 		// If we haven't created a copy of the eval context, and we have some
> 		// renders, then we'll need to create a copy ourselves since we're going
> 		// to use the ExprHelper which might mutate the eval context.
> ```

`ExprHelper` mutates `evalCtx` only temporarily by pushing then popping an ivar container. Is that not safe? Or is there another mutation happening than I'm missing?

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r1, 20 of 20 files at r2, 3 of 3 files at r3, 29 of 29 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126036#-:-O0BCSPE-CMX2yGtRSOc:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`pkg/sql/execinfra/processorsbase.go` line 135 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126036#-O0BBYYaEjv1fUAR2kW9:-O0BBYYbB-1aJyNHTk_O:brjg7ru) ([raw file](https://github.com/cockroachdb/cockroach/blob/c67bd53a5c44109f3cfe8e52c9fc8c429782ffbb/pkg/sql/execinfra/processorsbase.go#L135)):*
> ```Go
> 	coreOutputTypes []*types.T,
> 	semaCtx *tree.SemaContext,
> 	evalCtx *eval.Context,
> ```

[nit] Why not make it the responsibility of `ProcOutputHelper` to copy the `evalCtx`? It has the `PostProcessSpec`, so should be able to check for render expressions, right?

**Review by yuzefovich — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126036#-:-O0BiW_99bC65ZW9zksE:b-tlx7ko)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/execinfra/flow_context.go` line 49 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126036#-O0Azd9uEYqFUn2EaWBI:-O0BacC13DO8Q50h_5-g:b8zi4cc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c67bd53a5c44109f3cfe8e52c9fc8c429782ffbb/pkg/sql/execinfra/flow_context.go#L49)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Would making this un-exported be helpful in limiting its usage?
</blockquote></details>

I don't think that we want to be limiting usage of this field per se - it exposes a lot of things that are needed by many processors.

I think the right way forward - philosophically speaking - is breaking down `eval.Context` into smaller pieces and moving some of them directly into `FlowCtx` object. Raphael did an audit of the fields in the `eval.Context` [a while ago](https://github.com/cockroachdb/cockroach/issues/41992#issuecomment-559928078), but it'll be a lot of effort to actually achieve it. So for now treating `FlowCtx.EvalCtx` as a read-only field seems acceptable (vast majority of processors use it in this way).
___
*[`pkg/sql/execinfra/processorsbase.go` line 135 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126036#-O0BBYYaEjv1fUAR2kW9:-O0Bd9II6yeT_drcl99V:bhpm9k) ([raw file](https://github.com/cockroachdb/cockroach/blob/c67bd53a5c44109f3cfe8e52c9fc8c429782ffbb/pkg/sql/execinfra/processorsbase.go#L135)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Why not make it the responsibility of `ProcOutputHelper` to copy the `evalCtx`? It has the `PostProcessSpec`, so should be able to check for render expressions, right?
</blockquote></details>

Yep, good point, done.
___
*[`pkg/sql/execinfra/processorsbase.go` line 750 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126036#-O0Azo5qAAyj6IWYoRMf:-O0Be7yI-s8HLGJKiNdv:b-umnia8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c67bd53a5c44109f3cfe8e52c9fc8c429782ffbb/pkg/sql/execinfra/processorsbase.go#L750)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

In the long-term it'd be nice to follow the example of mutable and immutable descriptors so that we can lean on the type system to enforce this. The API would make it impossible for an ImmutableEvalCtx to be mutated (outside of a small part of trusted code).
</blockquote></details>

Yeah, it's one way to improve things. Another is to break down the `eval.Context` altogether.
___
*[`pkg/sql/execinfra/processorsbase.go` line 794 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126036#-O0B-dFL8oNuCC-lDnDI:-O0Bdbon39rNy0bVTJL0:b-fl7h0m) ([raw file](https://github.com/cockroachdb/cockroach/blob/c67bd53a5c44109f3cfe8e52c9fc8c429782ffbb/pkg/sql/execinfra/processorsbase.go#L794)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

`ExprHelper` mutates `evalCtx` only temporarily by pushing then popping an ivar container. Is that not safe? Or is there another mutation happening than I'm missing?
</blockquote></details>

Yeah, that's the only mutation AFAIK. The problem is that we might have concurrency between processors running on the same node, so if two processors were to use the same `eval.Context` via the ExprHelper, we could have corruption / data races.

**Comment by mgartner** [comment]
*[`pkg/sql/execinfra/processorsbase.go` line 794 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126036#-O0B-dFL8oNuCC-lDnDI:-O0FG_r57pQkRfKOAySI:bow9cs6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c67bd53a5c44109f3cfe8e52c9fc8c429782ffbb/pkg/sql/execinfra/processorsbase.go#L794)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Yeah, that's the only mutation AFAIK. The problem is that we might have concurrency between processors running on the same node, so if two processors were to use the same `eval.Context` via the ExprHelper, we could have corruption / data races.
</blockquote></details>

Ahh makes sense. Thanks for explaining.

**Pull request merged**
