### PR TITLE
kvserver/gc: make TestEndToEndGC work with secondary tenants

### PR DESCRIPTION
**Pull request by knz**
Informs #76378 
Epic: CRDB-18499

Release note: None

### CODE REVIEW

**Comment by erikgrinaker** [comment]
I'll let @aliher1911 pick this up.

**Review by aliher1911 — APPROVED** [review]
LGTM.

Do we have some TLDR on how should tests be written to work with our future vision?

**Comment by knz** [comment]
We are working on improving the test APIs and will get this documented when it feels ready for use.

**Comment by knz** [comment]
TFYR!

bors r=aliher1911

**Pull request merged**
