### PR TITLE
opt: pull join commutation logic into join_order_builder.go

### PR DESCRIPTION
**Pull request by DrewKimball**
Previously, inner joins and full joins were commuted by the
CommuteJoin rule. This PR brings commutation into the addJoin
function of JoinOrderBuilder, so that joins can be commuted at
the same time as they are reordered.

Note that CommuteLeftJoin remains because commuting a left join
requires a change in the type of join operator.

Also note that setting ReorderJoinsLimit to 0 now disallows
commutation, while setting ReorderJoinsLimit to 1 allows
commutation, but no other reordering.

Release note: None

### CODE REVIEW

**Review by andy-kimball — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52755#-:-MEdx3Ct03tSs9AFB8aR:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[pkg/sql/opt/memo/testdata/logprops/join, line 2473 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52755#-MEdup4H5cKXWVlyyvL3:-MEdup4H5cKXWVlyyvL4:bfeluui) ([raw file](https://github.com/cockroachdb/cockroach/blob/046847e7d02eb657a1a876f465e8ca0ba7af9bdd/pkg/sql/opt/memo/testdata/logprops/join#L2473)):*
> ```
>  │    ├── prune: (11)
>  │    ├── interesting orderings: (+6) (+8) (+10) (+14)
>  │    ├── scan trade
> ```

How come this got commuted? Shouldn't this change result in same plans as before?

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52755)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball)

___
*[pkg/sql/opt/memo/testdata/logprops/join, line 2473 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52755#-MEdup4H5cKXWVlyyvL3:-MEdxwsu0NSHULB52zrh:b-x6rugm) ([raw file](https://github.com/cockroachdb/cockroach/blob/046847e7d02eb657a1a876f465e8ca0ba7af9bdd/pkg/sql/opt/memo/testdata/logprops/join#L2473)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

How come this got commuted? Shouldn't this change result in same plans as before?
</blockquote></details>

The order in which expressions are added to the tree is different, so different plans with the same cost might be chosen (see TPC-H Q20).

**Review by RaduBerinde — APPROVED** [review]
:lgtm: Cool!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52755#-:-MEevVWn6iHEMsKcEbJJ:b-8mhwdz)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball)

**Comment by DrewKimball** [comment]
TFTRs!

**Pull request merged**
