### PR TITLE
sql: escape like operator properly

### LINKED ISSUE #44123: sql: Incorrect result for LIKE query
Consider the following test case:

```sql
CREATE TABLE t0(c0 STRING UNIQUE);
INSERT INTO t0 (c0) VALUES ('\a');
SELECT * FROM t0 WHERE c0 LIKE '\a'; -- unexpected: row is fetched
```

Unexpectedly, the query fetches a row. When removing the `UNIQUE` constraint, no row is fetched. That the predicate should evaluate to `FALSE` is also demonstrated by the following query:

```sql
SELECT c0 LIKE '\a' FROM t0; -- FALSE
```
I built CockroachDB from source (commit `55c0e012b9539a327640e42ceaaf556b7a0e7b10`) on Ubuntu 19.04.

### PR DESCRIPTION
**Pull request by cucaroach**
Fixes #44123

This is rough first take needs a test obviously but wanted feedback on general approach.

Release note: none

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
I don't understand the approach. If we just unescape the pattern, we have lost the context of whether e.g. a `%` was escaped or not. What if the pattern is `Hundred\%`? We will treat it as `Hundred%` and incorrectly convert it to a tight [`/Hundred - /Hundred`] span.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66472#-:-McpZPQfDZBskYuPRrHo:b-ko3qy3)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by cucaroach — COMMENTED** [review]
So basically the approach I took was to look at how we implemented: LIKE <pattern> ESCAPE '\\' which is to generate a call to the "like_escape" function which I studied lightly ;-).    Sounds like I should put my pencil down and study this some more, I did spend a little looking at how postgresql implements this, I'll run some more tests in PG to make sure I understand the full semantics. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66472#-:-McpcRrvAmlkZ3MPeHG-:brroz3p)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by RaduBerinde — COMMENTED** [review]
I don't see the relation between what this PR is doing and what `like_escape` is doing. `like_escape` calls `MatchLikeEscape` which uses the pattern in concert with the escape character.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66472#-:-Mcpm5sS1uYXLD_xV8RA:byztusl)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by cucaroach** [comment]
Right basically what my PR does is do what LIKE <pattern> ESCAPE '\\' does in the degenerate case where there's no "_%" characters at play (I think).   What's the source of truth for stuff like this?   Postgres docs or SQL standard?

**Comment by RaduBerinde** [comment]
I'd go by the Postgres docs.

**Pull request closed without merging**
