### PR TITLE
storage: use BlockPropertyCollector for fine-grained time bound itera…

### PR DESCRIPTION
**Pull request by sumeerbhola**
…tion

Adds an implementation of sstable.DataBlockIntervalCollector and
uses that to populate fine-grained per-block time intervals when
the cluster version is at PebbleFormatBlockPropertyCollector.

The original sstable-level pebbleTimeBoundPropCollector is still
in place, and will be useful for files that were written prior to
this use of BlockPropertyCollectors.

Benchmark results: For MVCCIncrementalIterator the ts=480 case is
one where 95% of the versions are irrelevant: new versions are
uniformly written for all keys, and each key on average should
have ~2 blocks. The ts=5 case is where all versions are relevant.

```
name                                            old time/op    new time/op    delta
MVCCIncrementalIterator/useTBI=true/ts=5-16       10.5ms ± 8%    10.7ms ± 7%     ~     (p=0.278 n=9+10)
MVCCIncrementalIterator/useTBI=true/ts=480-16     1.68ms ± 2%    0.38ms ± 2%  -77.44%  (p=0.000 n=9+9)
MVCCIncrementalIterator/useTBI=false/ts=5-16      7.83ms ±11%    8.58ms ± 6%   +9.62%  (p=0.000 n=10+10)
MVCCIncrementalIterator/useTBI=false/ts=480-16     952µs ± 1%     954µs ± 1%     ~     (p=0.549 n=10+9)

name                                            old alloc/op   new alloc/op   delta
MVCCIncrementalIterator/useTBI=true/ts=5-16       24.0kB ± 3%    24.2kB ± 2%     ~     (p=0.370 n=8+9)
MVCCIncrementalIterator/useTBI=true/ts=480-16     23.3kB ± 3%    21.0kB ± 2%  -10.10%  (p=0.000 n=10+9)
MVCCIncrementalIterator/useTBI=false/ts=5-16      11.3kB ±62%    14.0kB ± 3%     ~     (p=0.315 n=10+9)
MVCCIncrementalIterator/useTBI=false/ts=480-16    10.5kB ± 7%    10.5kB ± 7%     ~     (p=0.579 n=10+10)

name                                            old allocs/op  new allocs/op  delta
MVCCIncrementalIterator/useTBI=true/ts=5-16          224 ± 4%       251 ± 2%  +11.84%  (p=0.000 n=8+9)
MVCCIncrementalIterator/useTBI=true/ts=480-16        845 ± 3%       179 ± 1%  -78.87%  (p=0.000 n=10+8)
MVCCIncrementalIterator/useTBI=false/ts=5-16        15.2 ±54%      18.6 ± 3%     ~     (p=0.088 n=10+9)
MVCCIncrementalIterator/useTBI=false/ts=480-16       130 ± 7%       129 ± 7%     ~     (p=0.538 n=10+10)

name                                                               old time/op    new time/op    delta
CatchUpScan/linear-keys/useTBI=true/withDiff=false/perc=0.00-16       602ms ± 3%     600ms ± 5%     ~     (p=0.421 n=5+5)
CatchUpScan/linear-keys/useTBI=true/withDiff=false/perc=50.00-16      296ms ± 2%     290ms ± 2%   -2.05%  (p=0.032 n=5+5)
CatchUpScan/linear-keys/useTBI=true/withDiff=false/perc=75.00-16      145ms ± 3%     139ms ± 2%   -4.22%  (p=0.008 n=5+5)
CatchUpScan/linear-keys/useTBI=true/withDiff=false/perc=95.00-16     26.7ms ± 5%    26.4ms ± 2%     ~     (p=0.421 n=5+5)
CatchUpScan/linear-keys/useTBI=true/withDiff=false/perc=99.00-16     17.6ms ± 1%     5.3ms ± 1%  -70.07%  (p=0.008 n=5+5)
CatchUpScan/linear-keys/useTBI=false/withDiff=false/perc=0.00-16      382ms ± 3%     376ms ± 2%     ~     (p=0.310 n=5+5)
CatchUpScan/linear-keys/useTBI=false/withDiff=false/perc=50.00-16     283ms ± 2%     280ms ± 1%     ~     (p=0.056 n=5+5)
CatchUpScan/linear-keys/useTBI=false/withDiff=false/perc=75.00-16     233ms ± 0%     232ms ± 2%     ~     (p=0.556 n=4+5)
CatchUpScan/linear-keys/useTBI=false/withDiff=false/perc=95.00-16     196ms ± 5%     192ms ± 2%     ~     (p=0.310 n=5+5)
CatchUpScan/linear-keys/useTBI=false/withDiff=false/perc=99.00-16     186ms ± 4%     186ms ± 5%     ~     (p=1.000 n=5+5)
CatchUpScan/random-keys/useTBI=true/withDiff=false/perc=0.00-16       632ms ± 4%     624ms ± 0%     ~     (p=0.151 n=5+5)
CatchUpScan/random-keys/useTBI=true/withDiff=false/perc=50.00-16      518ms ± 1%     516ms ± 1%     ~     (p=0.690 n=5+5)
CatchUpScan/random-keys/useTBI=true/withDiff=false/perc=75.00-16      485ms ± 5%     479ms ± 3%     ~     (p=0.690 n=5+5)
CatchUpScan/random-keys/useTBI=true/withDiff=false/perc=95.00-16      418ms ± 2%     423ms ± 3%     ~     (p=0.548 n=5+5)
CatchUpScan/random-keys/useTBI=true/withDiff=false/perc=99.00-16      404ms ± 1%     400ms ± 2%     ~     (p=0.222 n=5+5)
CatchUpScan/random-keys/useTBI=false/withDiff=false/perc=0.00-16      392ms ± 1%     388ms ± 1%   -1.03%  (p=0.016 n=5+5)
CatchUpScan/random-keys/useTBI=false/withDiff=false/perc=50.00-16     304ms ± 2%     303ms ± 1%     ~     (p=1.000 n=5+5)
CatchUpScan/random-keys/useTBI=false/withDiff=false/perc=75.00-16     247ms ± 2%     247ms ± 2%     ~     (p=1.000 n=5+5)
CatchUpScan/random-keys/useTBI=false/withDiff=false/perc=95.00-16     223ms ±24%     207ms ± 1%     ~     (p=0.222 n=5+5)
CatchUpScan/random-keys/useTBI=false/withDiff=false/perc=99.00-16     198ms ± 2%     201ms ± 4%     ~     (p=0.310 n=5+5)
CatchUpScan/mixed-case/useTBI=true/withDiff=false/perc=0.00-16        620ms ± 1%     624ms ± 1%     ~     (p=0.548 n=5+5)
CatchUpScan/mixed-case/useTBI=true/withDiff=false/perc=50.00-16       519ms ± 2%     509ms ± 1%   -1.90%  (p=0.016 n=5+5)
CatchUpScan/mixed-case/useTBI=true/withDiff=false/perc=75.00-16       460ms ± 3%     452ms ± 1%     ~     (p=0.056 n=5+5)
CatchUpScan/mixed-case/useTBI=true/withDiff=false/perc=95.00-16       157ms ± 1%     156ms ± 1%   -1.15%  (p=0.032 n=5+5)
CatchUpScan/mixed-case/useTBI=true/withDiff=false/perc=99.00-16       145ms ± 1%     143ms ± 4%     ~     (p=0.310 n=5+5)
CatchUpScan/mixed-case/useTBI=false/withDiff=false/perc=0.00-16       387ms ± 3%     381ms ± 1%   -1.55%  (p=0.032 n=5+5)
CatchUpScan/mixed-case/useTBI=false/withDiff=false/perc=50.00-16      300ms ± 2%     297ms ± 1%   -1.17%  (p=0.032 n=5+5)
CatchUpScan/mixed-case/useTBI=false/withDiff=false/perc=75.00-16      247ms ± 1%     252ms ± 9%     ~     (p=1.000 n=5+5)
CatchUpScan/mixed-case/useTBI=false/withDiff=false/perc=95.00-16      202ms ± 3%     209ms ±10%     ~     (p=0.421 n=5+5)
CatchUpScan/mixed-case/useTBI=false/withDiff=false/perc=99.00-16      193ms ± 1%     192ms ± 1%     ~     (p=0.151 n=5+5)
```

Allocations are within [-0.10%,+0.10%] for CatchUpScan.

Release note: None

### CODE REVIEW

**Review by nicktrav — APPROVED** [review]
Neat. :lgtm:

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73143#-:-MpgjCaK7WQUlFOPBP6S:b-53gzg3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[pkg/storage/pebble.go, line 407 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73143#-MpggzSlCQ0s4SUpVF3Z:-MpggzSlCQ0s4SUpVF3_:b-tpm6ov) ([raw file](https://github.com/cockroachdb/cockroach/blob/889cbbc66b572e83b4fdb60e174f52231734ec15/pkg/storage/pebble.go#L407)):*
> ```Go
> 	// hlc.Timestamps in this block.
> 	lower = decodeWallTime(tc.min)
> 	tc.min = tc.min[:0]
> ```

Seems like these calls to zero out the min and max are significant? Worth documenting? Wondering what happens if you were to omit these?

**Comment by sumeerbhola** [comment]
TFTR!

@dt @stevendanna are there any roachtests that are sensitive to the TBI performance optimization that I can use to evaluate this change? For example, something that if tweaked to manually compact everything down to L6 would perform poorly.

**Comment by dt** [comment]
> @dt @stevendanna are there any roachtests that are sensitive to the TBI performance optimization that I can use to evaluate this change? For example, something that if tweaked to manually compact everything down to L6 would perform poorly.

Unfortunately I don't think we have a good test of the real-world efficacy of TBI right now -- almost all our automated tests start up on fresh data, run, and finish without really developing any significant spread in timestamps, waiting for the LSM to evolve over time and compactions, etc. In the past when I've wanted to measure TBI perf I've needed to standup a roachprod cluster and run tpcc for a few days to get a somewhat organic looking LSM to then test on. Perhaps we should at some point invest in a test fixture that is actual store snapshots that look more like data that is written/rewritten over time, vs our current tests that all start on freshly imported (all in l6) data.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73143)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal, @jbowens, and @nicktrav)

___
*[pkg/storage/pebble.go, line 407 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73143#-MpggzSlCQ0s4SUpVF3Z:-Mq19xExCRC3mD8vugWo:bi4jvne) ([raw file](https://github.com/cockroachdb/cockroach/blob/889cbbc66b572e83b4fdb60e174f52231734ec15/pkg/storage/pebble.go#L407)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

Seems like these calls to zero out the min and max are significant? Worth documenting? Wondering what happens if you were to omit these?
</blockquote></details>

I've added a comment. It is part of the contract when implementing `DataBlockIntervalCollector`, since the next `Add` call will be for a different data block.

**Review by stevendanna — APPROVED** [review]
LGTM, very cool.

> are there any roachtests that are sensitive to the TBI performance optimization that I can use to evaluate this change?

The `cdc/ledger` tests can be sensitive to TBI if you force them to run long enough such that a range split forces an expensive catchup-scan. Without TBI, the split should be rather disruptive to the end-to-end cdc latency without TBI in place (it is impactful even with TBI, but usually stays within the test bounds).  I haven't retested it since we moved to using the separated lock table for the rts scan though, which I believe was also a large portion of the problem.  To be useful you'll need to bump the test time and remove the hack we put in to avoid splits:

https://github.com/cockroachdb/cockroach/blob/5eb53d99ef5f8e91dbecbcb9008cf9a8c0d0a6f4/pkg/cmd/roachtest/tests/cdc.go#L777-L786

Another possibility is to run a workload with a changefeed for a while and then manually force splits.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73143#-:-Mq40lP2-BsH-luysuvH:b-gbgimd)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal, @jbowens, and @nicktrav)

**Comment by sumeerbhola** [comment]
@stevendanna do we see inadequate catchup performance even with TBI in this `cdc/ledger` test? I am trying to figure out a test that could show a difference between the file-level TBI and this new block-level filtering.

**Comment by miretskiy** [comment]
Is there a setting that needs to be turned on for this?

**Comment by sumeerbhola** [comment]
> Is there a setting that needs to be turned on for this?

No cluster setting. But the cluster version needs to be at `PebbleFormatBlockPropertyCollector`.

**Pull request merged**
