### PR TITLE
ui: add running status to admin UI jobs page

### LINKED ISSUE #30682: ui: add secondary status to jobs table
Certain schema changes like DROP TABLE, DROP INDEX when in the running state also publish a secondary status like, "waiting for GC interval" to the jobs table. This secondary status needs to show up in the admin UI jobs page.

### PR DESCRIPTION
**Pull request by eriktrinh**
The admin UI jobs page displays the running status above the progress
bar if the job has one.

screen shot 2018-10-08 at 4 33 48 pm

Fixes #30682.

Release note: None

### CODE REVIEW

**Review by couchand — APPROVED** [review]

**Comment by couchand** [comment]
cc @piyush-singh

**Review by vilterp — APPROVED** [review]

**Comment by vilterp** [comment]
@eriktrinh are we backporting this `running_status` stuff?

**Comment by eriktrinh** [comment]
No, all the changes which require `running_status` are for 2.2.

**Comment by vilterp** [comment]
bors r-

(bors r+ again when the test has been fixed)

**Comment by eriktrinh** [comment]
shouldn't be 500'ing anymore, PTAL.

**Review by vilterp — APPROVED** [review]
Change to handle nulls looks reasonable.

**Comment by vilterp** [comment]
bors r+

Bors was borked for a bit there; retrying

**Pull request merged**
