### PR TITLE
keys: use correct length of UUID

### PR DESCRIPTION
**Pull request by tbg**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5474)

### CODE REVIEW

**Comment by bdarnell** [comment]
LGTM

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[keys/printer.go, line 383 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5474#-KDUMkNgzGIwvU9phqig:-KDUMkNh9nJ5L-Y3tFke:790783871) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7c74044b43594ab4b818c93288241e1974173f7/keys/printer.go#L383)):*
> Had to find out the hard way that the wrapped uuid package never checks the string's length as long as it's long enough (and even that test is broken, I think - it checks for 32, not 36).

It checks for >= 32 because as the comment there says:
> // Following formats are supported:
// "6ba7b810-9dad-11d1-80b4-00c04fd430c8",
// "{6ba7b810-9dad-11d1-80b4-00c04fd430c8}",
// "urn:uuid:6ba7b810-9dad-11d1-80b4-00c04fd430c8"

Can you add a comment here that explains exactly what case you're guarding against?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5474)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[keys/printer.go, line 383 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5474#-KDUMkNgzGIwvU9phqig:-KDUO2zdPIlBCCGoQrR7:1903033507) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7c74044b43594ab4b818c93288241e1974173f7/keys/printer.go#L383)):*
The shortest of those is 36 chars. A comment would be good; a unit test would be better.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5474)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[keys/printer.go, line 383 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5474#-KDUMkNgzGIwvU9phqig:-KDUOdcaH4dZW3SUAdrN:884951339) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7c74044b43594ab4b818c93288241e1974173f7/keys/printer.go#L383)):*
Yeah, secretly the non-hyphenated `6ba7b8109dad11d180b4-00c04fd430c8` is also supported.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5474)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[keys/printer.go, line 383 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5474#-KDUMkNgzGIwvU9phqig:-KDUPd0pgkM7e79bvdVV:1891014639) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7c74044b43594ab4b818c93288241e1974173f7/keys/printer.go#L383)):*
I missed a hyper, but you get the point.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5474)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[keys/printer.go, line 383 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5474#-KDUMkNgzGIwvU9phqig:-KDUe14QjwK_oE1QStLn:1655470347) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7c74044b43594ab4b818c93288241e1974173f7/keys/printer.go#L383)):*
This is making sure you get an error if what you're reading in isn't actually a uuid (it would otherwise throw away the remainder of the string, presumably). I agree that this would deserve a unit test, but so does everything else here (the only testing coverage is `printer_test.go` which skips everything that comes back with a not-implemented-error), and (for now) the only reason for this code existing is as a way to peek into our on-disk data. Some day this code will have to be cleaned up (and, I would guess, completely rewritten). I'd like to punt on testing this stuff until some of the cluster issues are fixed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5474)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[keys/printer.go, line 383 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5474#-KDUMkNgzGIwvU9phqig:-KDUgyGFk9sV97ww-ctv:-692971983) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7c74044b43594ab4b818c93288241e1974173f7/keys/printer.go#L383)):*
OK, but can you at least add a comment that tells the story of how you "found out the hard way"?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5474)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[keys/printer.go, line 383 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5474#-KDUMkNgzGIwvU9phqig:-KDZ7K1DTB5thL3QHwwl:-827100998) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7c74044b43594ab4b818c93288241e1974173f7/keys/printer.go#L383)):*
I have no story, I just thought ahead. If that did happen, `UglyPrint` would find it (it pretty-prints everything it creates again and makes sure it didn't change the pretty key). If you have something that I should add, let me know what it is and I'll paste it in.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5474)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[keys/printer.go, line 383 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5474#-KDUMkNgzGIwvU9phqig:-KDZ9bc_McofXrZyIx-e:-598244969) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7c74044b43594ab4b818c93288241e1974173f7/keys/printer.go#L383)):*
I'd remove this altogether; I can't think of a real case where this does anything. I was going on your word of "I had to find out the hard way", but if there's no story then this seems like FUD.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5474)*

**Comment by tschottdorf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[keys/printer.go, line 383 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5474#-KDUMkNgzGIwvU9phqig:-KDobQi0f8s8W89pzmjc:1125207049) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7c74044b43594ab4b818c93288241e1974173f7/keys/printer.go#L383)):*
Need to leave it in for the tests (because the resulting key doesn't reproduce if there is more than the ID to the string).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5474)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[keys/printer.go, line 383 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5474#-KDUMkNgzGIwvU9phqig:-KDp1Fp2dEWBJubEgDS2:-1351819902) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7c74044b43594ab4b818c93288241e1974173f7/keys/printer.go#L383)):*
I don't follow, but OK.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5474#-:-KDp1OB8MT0JlVZ1LGdM:1417088721)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[keys/printer.go, line 383 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5474#-KDUMkNgzGIwvU9phqig:-KDp3_RCYBlJFg1Ki_qL:52460301) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7c74044b43594ab4b818c93288241e1974173f7/keys/printer.go#L383)):*
I'm "testing" this code in the key pretty printing test in the following way:

* uglify the pretty key
* if `&errUglifyUnsupported`, skip it.
* otherwise, check that it reproduces (in fact UglyPrint does that)

So if I don't catch it here, it'll drop the epoch and sequence number of a pretty key and it doesn't reproduce and the test fails.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5474)*

**Pull request merged**
