### PR TITLE
cli: improve usage text

### PR DESCRIPTION
**Pull request by petermattis**
Use different usage text for the --port and --host flags for different
commands.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4811)

### CODE REVIEW

**Comment by tamird** [comment]
LGTM cc @jseldess 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cli/flags.go, line 100 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4811#-KBwzbkJi39q720WOmqH:-KBwzbkJi39q720WOmqI:1457758593) ([raw file](https://github.com/cockroachdb/cockroach/blob/f636890de43b01787f13cd140051aded9543db50/cli/flags.go#L100)):*
should we rename this key to server_host? there's probably a port key somewhere that should be similarly renamed

---

*[cli/flags.go, line 101 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4811#-KBwzZVKS3Pe7UXmdr2G:-KBwzZVKS3Pe7UXmdr2H:-1082360556) ([raw file](https://github.com/cockroachdb/cockroach/blob/f636890de43b01787f13cd140051aded9543db50/cli/flags.go#L101)):*
this is also the listening hostname, right? let's include that in this text.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4811#-:-KBwzcwtzd-GcgnJ__Ho:-1879492792)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[cli/flags.go, line 100 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4811#-KBwzbkJi39q720WOmqH:-KBx-XSOhYqvnRCvI2yX:-59234789) ([raw file](https://github.com/cockroachdb/cockroach/blob/f636890de43b01787f13cd140051aded9543db50/cli/flags.go#L100)):*
I could. Doesn't seem to matter, but why not.

---

*[cli/flags.go, line 101 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4811#-KBwzZVKS3Pe7UXmdr2G:-KBx-_kq_AK_zbr8pFe6:2109517944) ([raw file](https://github.com/cockroachdb/cockroach/blob/f636890de43b01787f13cd140051aded9543db50/cli/flags.go#L101)):*
Yes. Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4811)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cli/flags.go, line 350 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4811#-KBxA00gwMtu6fgqCQRC:-KBxA00gwMtu6fgqCQRD:-1701652821) ([raw file](https://github.com/cockroachdb/cockroach/blob/f636890de43b01787f13cd140051aded9543db50/cli/flags.go#L350)):*
you didn't want to keep the shorthand?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4811)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cli/flags.go, line 350 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4811#-KBxA00gwMtu6fgqCQRC:-KBxAJ4wHrhJZW9rmy1c:-860445485) ([raw file](https://github.com/cockroachdb/cockroach/blob/f636890de43b01787f13cd140051aded9543db50/cli/flags.go#L350)):*
The builtin `--help` flag already uses the `-h` shorthand. pflag panics when this occurs. Looks like I could fix this by providing our own `--help` flag, but that feels confusing.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4811)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cli/flags.go, line 350 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4811#-KBxA00gwMtu6fgqCQRC:-KBxBw1Fer_2lnmEuOwR:-84421118) ([raw file](https://github.com/cockroachdb/cockroach/blob/f636890de43b01787f13cd140051aded9543db50/cli/flags.go#L350)):*
Ah, that's too bad.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4811)*

**Comment by petermattis** [comment]
Test failure is the same as https://github.com/cockroachdb/cockroach/issues/4753.

**Pull request merged**
