### PR TITLE
sql, config: make `voter_constraints` inherit from parent by default

### LINKED ISSUE #61316: sql, config: incorrect handling of pre-21.1 zone configs
https://github.com/cockroachdb/cockroach/pull/57184 introduced two new zone config attributes `num_voters` and `voter_constraints`. This was achieved by introducing the following new fields to the zone config proto:

```
optional int32 num_voters 

repeated ConstraintsConjunction voter_constraints

optional bool inherited_voter_constraints 
```

The `inherited_voter_constraints` field helps to disambiguate an empty (but not inherited) `voter_constraints` against an inherited `voter_constraints`. However, ZoneConfig protos persisted in 20.2 will not contain these new fields. When such protos are unmarshalled by a 21.1 node, `inherted_voter_constraints` will default to false.

To reproduce:
```
roachprod create $CLUSTER -n 5;
roachprod stage $CLUSTER release v20.2.7;
roachprod start $CLUSTER --racks=5;

#  set up a zone config hierarchy based on just the 20.2 fields
roachprod sql $CLUSTER:1 -- -e "create database db; use db; create table t ();"
roachprod sql $CLUSTER:1 -- -e "alter database db configure zone using num_replicas = 3, constraints = '{\"+rack=1\":1}';"
roachprod sql $CLUSTER:1 -- -e "use db; alter table t configure zone using constraints = '{\"+rack=1\":1}';"

# upgrade the cluster
roachprod stop $CLUSTER;
roachprod stage $CLUSTER cockroach
roachprod start $CLUSTER --racks=5;
roachprod sql $CLUSTER:1 -- -e "RESET CLUSTER SETTING cluster.preserve_downgrade_option;"
sleep 60;

# make the database level zone config use the new attributes 
roachprod sql $CLUSTER:1 -- -e "alter database db configure zone using num_replicas = 3, num_voters = 3, voter_constraints = '{\"+rack=1\":1}';"

# at this point, the table should be inheriting the database level voter_constraints, but it won't.
roachprod sql $CLUSTER:1 -- -e "use db; show zone configuration for table t;"
```

### PR DESCRIPTION
**Pull request by aayushshah15**
Resolves #61316

This commit inverts the definition of the flag used to keep track of
whether `voter_constraints` were empty or inherited. This allows legacy
(pre-21.1) zone configs to be correctly interpreted by 21.1 nodes.

Release note (backward-incompatible change): the internal representation
of the `voter_constraints` zone configuration attribute (new in 21.1)
has been altered in a way that's partially incompatible with the
representation used by previous 21.1 betas (and the alphas that include
this attribute). This means that Users who directly set the
`voter_constraints` attribute to an empty list _will lose_ those
constraints and will have to reset them.

### CODE REVIEW

**Comment by otan** [comment]
i think this is backwards incompatible with the betas, which according to @ajstorm is something we care about :\ 
would it be easier to write the migrations?

**Comment by ajstorm** [comment]
Nice to see this @aayushshah15.  Can you talk a bit more about how it's backwards incompatible?

**Comment by otan** [comment]
`inherited_voter_constraints` has been renamed and re-used as `explicitly_set_voter_constraints` in the protobuf. anyone who has used voter constraints in the past will have the meaning "swapped".

**Comment by aayushshah15** [comment]
>i think this is backwards incompatible with the betas, which according to @ajstorm is something we care about

Is there a source for this on our wiki / somewhere else? I can't find any doc claiming this, but I can find some old slack conversations about how [this is more of a best-effort thing](https://cockroachlabs.slack.com/archives/C0HM2DZ34/p1599502776068500?thread_ts=1598552701.118100&cid=C0HM2DZ34).

**Comment by otan** [comment]
if i understand correctly, would the migration be to set all InheritedVoterConstraints to true for every zone config that exists?
i sense some surprises if this is to be the case and the migration is not done, e.g. a user won't be able to migrate to MR if they set gc.ttlseconds on their table unless they discard the zone config (since we dont have CONFIGURE ZONE USING x = INHERIT FROM PARENT)

**Comment by aayushshah15** [comment]
>if i understand correctly, would the migration be to set all InheritedVoterConstraints to true for every zone config that exists?

Nope, this would essentially amount to wiping all `voter_constraints` on every zone. 

I haven't thought through this deeply but any migration would be quite tricky to get right here.

> user won't be able to migrate to MR if they set gc.ttlseconds on their table

I don't think I follow, why would `gc.ttlseconds` matter here?

**Comment by otan** [comment]
It initialises a new zone config but with the default values for voter constraints in v20.2. If a user migrates to v21.1, on the first multi-region add, we'll detect inherit voter constraints = false on the zone config which is not expected and would hence be blocked

**Comment by aayushshah15** [comment]
@otan I see what you mean. That's what this PR is fixing though, right? If all we're concerned about is the move from 20.2 to 21.1.0 (production) then this PR should be all we need.

Could you clarify what you're proposing, just so we're on the same page? What CRDB versions are we proposing to reconcile with a migration? 21.1 beta1 to beta3?

**Comment by aayushshah15** [comment]
Let me clarify what I'm thinking.

If we care about not breaking existing zone configs for existing 21.1 beta users in addition to not breaking `voter_constraints` inheritance for 20.2 users, a simple migration for just 20.2 -> 21.1 will not cut it anymore because we've shipped a couple 21.1 betas already.

So, if I'm reading you correctly, your proposal is two sets of migrations: one that deals with 20.2 users moving to "21.1beta3 and above", and another that deals with 21.1beta1 users to "21.1beta3 and above". The latter is the reason for the push-back against this PR, is that correct? Note that this is the migration case that's very tricky cause the users might have already created zone configs with explicitly _not inherited_ voter constraints.

**Comment by otan** [comment]
Hmm, sorry let's try again!

> I discussed with Nathan and Andrei just now and we felt that, in this particular case, not writing a migration doesn't lead to any issues severe enough (since it just amounts to users essentially losing their existing voter_constraints) to warrant the extra work. 

Somehow connected the wrong dots and thought you meant "we're cancelling this PR and doing nothing". My bad.

> The latter is the reason for the push-back against this PR, is that correct? 

Yep, that's my pushback on this PR. Anyone who's already in 21.1beta1 (or whatever is out there as of speaking) will have the behaviour surprisingly flip on them with this PR merged if they moved to say v21.1.0.

> If we care about not breaking existing zone configs for existing 21.1 beta users in addition to not breaking voter_constraints inheritance for 20.2 users, a simple migration for just 20.2 -> 21.1 will not cut it anymore because we've shipped a couple 21.1 betas already.

Ah yes, that's tricky.

I guess my question then is can we do something simple to check like 

```
if !zc.InheritParentZoneConfigs && len(voter_constraints) == 0 {
   zc.InheritParentZoneConfigs = true
}
```

(I would've thought if not inheriting then you must have some voter constraints, but I could be wrong).

Is there a way to check in a migration whether a cluster has ever been a certain version? I would've hope so, but realise I am asking for a lot more than is bargained for. Supporting compat between betas is really gross :\

----

In either case, both situations suck, but it seems like you have been weighing the options and I chimed in with insufficient context. I guess a release note summarising what could go wrong between betas would be nice to have.

**Comment by aayushshah15** [comment]
> "we're cancelling this PR and doing nothing"

yeah so just to confirm, my / our position was that we would go ahead with this PR since it's a very simple fix for the main issue that we care about, which is correct interpretation of 20.2 zone configs. Regarding the fact that we're mangling with zone configs from 21.1beta1, we would just call this out in a proper release note since it's not worth taking on all this complexity for a tiny set of non-production users (especially when the mitigation is to just discard some existing zone configs and re-add them -- the release note could call this out). 

> I guess my question then is can we do something simple to check like

I had wondered about this but it would be incorrect because the user could've just explicitly set `voter_constraints` to an empty list (a good reason to do that would be to _avoid_ inheriting from parent). I'm actually not sure there even is a correct migration we can write here. This kinda brings me to my point below.

> Supporting compat between betas is really gross :\

It's just that there's a ton of ways to get this whole ordeal wrong, all for the sake of a vague desire to maintain back-compat on _new features_ between betas (which we don't seem to promise anywhere externally) which seems questionable.

**Comment by otan** [comment]
I'm personally ok with going forwards with this PR, but also impartial to writing a migration that works only for 20.2->21.1 if we're going down this path :)

I guess it's not me the rules should be enforced by :D

**Comment by ajstorm** [comment]
The resolution from the team meeting today was:

1) We need a path for customers to migrate from previous betas to the beta
which contains this fix.  That migration doesn't need to be handled in the
code, but can be prescribed in a release note as a set of steps the
customer needs to run.  We should test this in-house to ensure that it
works, and that we don't get tripped up by any validation scenarios.
2) We need better clarity on what types of backward incompatible changes
are acceptable in betas.  I'll continue working to ensure that Isaac and
Nate define this for future releases.

**Comment by aayushshah15** [comment]
I've updated the release note with steps for current 21.1 beta users who upgrade to the next beta ([here's a script](https://gist.github.com/aayushshah15/7869881acebee364a3b50d8a5d9622c2) that encapsulates the validation of these steps on my end). PTAL when you get a chance.

**Review by ajstorm — COMMENTED** [review]
I'm probably missing something obvious, but I don't see the updated release notes.  @aayushshah15 can you point me to them.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63079#-:-MY5Xl_k4yz1pk2Y3tcF:b-fjtzzw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @otan)

**Comment by aayushshah15** [comment]
I had only updated the PR message, but now I updated the commit message as well.

**Review by otan — COMMENTED** [review]
Changes LGTM, letting a TL sign off for the beta incompatibility though.

> Reviewed 3 of 3 files at r2, 12 of 12 files at r3, 12 of 12 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63079#-:-MY7crX3Dhiuj-NzXhNh:b-aj40w0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Comment by aayushshah15** [comment]
@nvanbenschoten proposed an alternative approach today, which works out fantastically. The solution in the current revision does not break backwards compatibility with existing multi-region databases. It only breaks back-compat with 21.1 zone configs that _explicitly set_ `voter_constraints` to an empty list. Even then, the mitigation for that subset of users is very straightforward.

**Review by ajstorm — COMMENTED** [review]
:tada: it's great to see that ingenuity won out here.  Nice job team!

Nit: You might want to consider dropping the last two bullets of the release note.  I think if we describe who's impacted, we can leave out who's not impacted.  Also, you might want to change the first bullet to "Users who directly set the `voter_constraints` attribute (a new attribute in 21.1) to an empty list in one of the previous 21.1 betas or alphas _will lose_ those constraints and will have to reset them to an empty list".  Just a small tweak to clearly indicate that this only impacts previous beta/alpha users.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63079#-:-MYAEwu3B9VvdlDq8_M3:bpbkyrz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @otan)

**Comment by aayushshah15** [comment]
Thanks for the latest suggestions @ajstorm. Updated the note with them.

**Review by ajstorm — COMMENTED** [review]
LGTM.  Nit: Now that there's only one item in the list, you might want to remove the colon and just continue the paragraph.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63079#-:-MYBot9v2crN_tuyPWo5:b-bjun4u)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @otan)

**Review by nvb — APPROVED** [review]
:lgtm: thanks for diligently working through the complexity of this change. I think it ended up in a good spot.

> Reviewed 2 of 2 files at r1, 3 of 3 files at r2, 7 of 12 files at r3, 12 of 12 files at r4, 2 of 12 files at r5, 11 of 11 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63079#-:-MYDcwZB1quobpGObITq:b1qk94u)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15)

___
*[pkg/config/zonepb/zone.go, line 278 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/63079#-MYDb9jf-2pfWF-I2sDJ:-MYDb9jf-2pfWF-I2sDK:b-nshsih) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea5975fc02c4879ce2be2cee8ed33b37668568aa/pkg/config/zonepb/zone.go#L278)):*
> ```Go
> // explicitly set on this zone or if it is to be inherited from its parent.
> func (z *ZoneConfig) InheritedVoterConstraints() bool {
> 	if len(z.VoterConstraints) == 0 {
> ```

nit: this might be easier to read as `return len(z.VoterConstraints) == 0 && !z.NullVoterConstraintsIsEmpty`
___
*[pkg/config/zonepb/zone.go, line 554 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/63079#-MYDbPY66ZCYaAlBAgD-:-MYDbPY66ZCYaAlBAgD0:b-l7dijr) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea5975fc02c4879ce2be2cee8ed33b37668568aa/pkg/config/zonepb/zone.go#L554)):*
> ```Go
> 		if !parent.InheritedVoterConstraints() {
> 			z.VoterConstraints = parent.VoterConstraints
> 			z.NullVoterConstraintsIsEmpty = true
> ```

Should this be `z.NullVoterConstraintsIsEmpty = parent.NullVoterConstraintsIsEmpty`? I don't think it matters in practice, but it seems like we're copying everything from our parent, so why not this field?
___
*[pkg/config/zonepb/zone.proto, line 141 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/63079#-MYDc88ID6f9vKfs_DJ6:-MYDc88J5fwiGcgOc91J:b-nwy1fo) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea5975fc02c4879ce2be2cee8ed33b37668568aa/pkg/config/zonepb/zone.proto#L141)):*
> ```protobuf
>   // below) because the non-nullable nature of `constraints` and
>   // `voter_constraints` means that there is no other way to disambiguate
>   // between an unset `constraints` attribute and an empty one.
> ```

`voter_constraints`
___
*[pkg/config/zonepb/zone.proto, line 145 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/63079#-MYDbyH38dOZwug89NQC:-MYDbyH38dOZwug89NQD:b3szr3v) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea5975fc02c4879ce2be2cee8ed33b37668568aa/pkg/config/zonepb/zone.proto#L145)):*
> ```protobuf
> 
>   // NullVoterConstraintsIsEmpty specifies whether the VoterConstraints field
>   // was explicitly set to be empty or if it was inherited from its parent.
> ```

I'd say again here what you say right above. "This field is needed because the non-nullable nature of voter_constraints means that there is no other way to disambiguate between an unset `constraints` attribute and an empty one."
___
*[pkg/server/diagnostics/reporter.go, line 378 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/63079#-MYDcPEI-J50D_Dii3zd:-MYDcPEI-J50D_Dii3ze:b-vy59i5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea5975fc02c4879ce2be2cee8ed33b37668568aa/pkg/server/diagnostics/reporter.go#L378)):*
> ```Go
> 	}
> 	dst.VoterConstraints = make([]zonepb.ConstraintsConjunction, len(src.VoterConstraints))
> 	dst.NullVoterConstraintsIsEmpty = src.NullVoterConstraintsIsEmpty
> ```

Should we be doing the same thing for `InheritedConstraints` up above?

**Review by aayushshah15 — COMMENTED** [review]
Thanks for the reviews!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63079#-:-MYGu1ADD91S8nCWzqQI:bctxt4d)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten and @otan)

___
*[pkg/config/zonepb/zone.go, line 278 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/63079#-MYDb9jf-2pfWF-I2sDJ:-MYGStUF6QEHkxQsvKVv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea5975fc02c4879ce2be2cee8ed33b37668568aa/pkg/config/zonepb/zone.go#L278)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: this might be easier to read as `return len(z.VoterConstraints) == 0 && !z.NullVoterConstraintsIsEmpty`
</blockquote></details>

Done.
___
*[pkg/config/zonepb/zone.go, line 554 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/63079#-MYDbPY66ZCYaAlBAgD-:-MYGSsn04pCoNMh2cUmV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea5975fc02c4879ce2be2cee8ed33b37668568aa/pkg/config/zonepb/zone.go#L554)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should this be `z.NullVoterConstraintsIsEmpty = parent.NullVoterConstraintsIsEmpty`? I don't think it matters in practice, but it seems like we're copying everything from our parent, so why not this field?
</blockquote></details>

Done.
___
*[pkg/config/zonepb/zone.proto, line 141 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/63079#-MYDc88ID6f9vKfs_DJ6:-MYGSuEN6P9Nl2U-S8IE:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea5975fc02c4879ce2be2cee8ed33b37668568aa/pkg/config/zonepb/zone.proto#L141)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`voter_constraints`
</blockquote></details>

Fixed.
___
*[pkg/config/zonepb/zone.proto, line 145 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/63079#-MYDbyH38dOZwug89NQC:-MYGSvjoESftf5fdGoFI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea5975fc02c4879ce2be2cee8ed33b37668568aa/pkg/config/zonepb/zone.proto#L145)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'd say again here what you say right above. "This field is needed because the non-nullable nature of voter_constraints means that there is no other way to disambiguate between an unset `constraints` attribute and an empty one."
</blockquote></details>

Done.
___
*[pkg/server/diagnostics/reporter.go, line 378 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/63079#-MYDcPEI-J50D_Dii3zd:-MYGSwlh5OxxIkpFLGMl:b6ds509) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea5975fc02c4879ce2be2cee8ed33b37668568aa/pkg/server/diagnostics/reporter.go#L378)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we be doing the same thing for `InheritedConstraints` up above?
</blockquote></details>

It definitely seems like an oversight (though I think we're just dumping these anonymized configs somewhere for ~telemetry reasons), fixed for `InheritedConstraints` as well as `InheritedLeasePreferences`.

**Pull request merged**
