### PR TITLE
build,protobuf: stop building unnecessary protobuf

### PR DESCRIPTION
**Pull request by alan-mas**
Based on #56 we need to avoid protobuf compiler to run for Java, Obj-C and C# everytime we build as no one is using these languages anymore.

submodule c-deps/protobuf updated.

Release note: None

### CODE REVIEW

**Review by rickystewart — CHANGES_REQUESTED** [review]
The Bazel build needs to remain up-to-date.

**Review by rickystewart — CHANGES_REQUESTED** [review]
> The Bazel build needs to remain up-to-date.

**Comment by knz** [comment]
@rickystewart I think this PR is ok now?

**Review by rickystewart — CHANGES_REQUESTED** [review]
It looks like the submodule is at `9ebd07afe83a30b9bebce6ecb1340fe6d5382134` while the version pinned in `WORKSPACE` is `e809d75ecb5770fdc531081eef306b3e672bcdd2`. They should match.

**Review by rickystewart — APPROVED** [review]

**Pull request merged**
