### PR TITLE
sql: retry validation of unique constraint

### LINKED ISSUE #85711: roachtest: tpcc/multiregion/survive=region/chaos=true failed
roachtest.tpcc/multiregion/survive=region/chaos=true [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/5997534?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/5997534?buildTab=artifacts#/tpcc/multiregion/survive=region/chaos=true) on master @ [a7c91f06d8ee0fa2096bcd626f689009024947bb](https://github.com/cockroachdb/cockroach/commits/a7c91f06d8ee0fa2096bcd626f689009024947bb):

```
test artifacts and logs in: /artifacts/tpcc/multiregion/survive=region/chaos=true/run_1
	monitor.go:127,tpcc.go:257,tpcc.go:588,test_runner.go:896: monitor failure: monitor command failure: unexpected node event: 6: dead (exit status 7)
		(1) attached stack trace
		  -- stack trace:
		  | main.(*monitorImpl).WaitE
		  | 	main/pkg/cmd/roachtest/monitor.go:115
		  | main.(*monitorImpl).Wait
		  | 	main/pkg/cmd/roachtest/monitor.go:123
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.runTPCC
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/tpcc.go:257
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerTPCC.func9
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/tpcc.go:588
		  | [...repeated from below...]
		Wraps: (2) monitor failure
		Wraps: (3) attached stack trace
		  -- stack trace:
		  | main.(*monitorImpl).wait.func3
		  | 	main/pkg/cmd/roachtest/monitor.go:202
		  | runtime.goexit
		  | 	GOROOT/src/runtime/asm_amd64.s:1571
		Wraps: (4) monitor command failure
		Wraps: (5) unexpected node event: 6: dead (exit status 7)
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.withPrefix (5) *errors.errorString
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #78619 roachtest: tpcc/multiregion/survive=region/chaos=true failed [C-test-failure O-roachtest O-robot branch-release-22.1]
</p>
</details>
/cc @cockroachdb/multiregion
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*tpcc/multiregion/survive=region/chaos=true.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-18395

Epic CRDB-19172

### PR DESCRIPTION
**Pull request by yuzefovich**
Previously, when running the validation of unique constraint we would execute the query only once, and if that fails for any reason, we'd return an error. This was suboptimal because we might be performing the validation after having performed a lot of work (e.g. running an import), and the error could be a transient one (e.g. if a node that is used in the distributed validation query goes down). In order to improve the situation this commit adds a retry loop with 5 attempts with an allowlist of error that are swallowed.

Fixes: #85711.

Epic: CRDB-20535

Release note: None

### CODE REVIEW

**Review by irfansharif — APPROVED** [review]

**Comment by ajwerner** [comment]
I suppose this is fine. We already have logic in the legacy schema changer to retry transient errors:

https://github.com/cockroachdb/cockroach/blob/d106bd6525e547372cb96c9082a22b19ee966bde/pkg/sql/schema_changer.go#L2627-L2631

It seems that here we're in the importer, so I guess it makes sense. Does import not have checkpoints? What would happen if we just marked the failure as retryable using the below function and let the job registry deal with retrying? 
https://github.com/cockroachdb/cockroach/blob/1e322dc6b79633dd90a59e9880b9b224da52705d/pkg/jobs/errors.go#L31-L33

**Comment by ajwerner** [comment]
I prefer that, if it works, because the user will get visibility, there will be backoff, and we'll eventually succeed.

**Review by yuzefovich — COMMENTED** [review]
I think it would be worse that than what I'm proposing here. Imagine that we've just imported 1TB worth of data and encounter a transient error during this validation step. If we were to return a job-retryable error, then all imported data is discarded and import has to start from scratch, and it was all because of a temporary blip during the validation query at the very end. With this patch we will just transparently retry the validation query without having to start from scratch. I guess we might want to introduce some kind of backoff in this retry mechanism, done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88307#-:-NCb4Wp8Bot2dZfPiFiM:b-aw0x8s)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @rytaft)

**Review by yuzefovich — COMMENTED** [review]
Oh, I guess I missed your point about checkpoints - I don't know whether import has them.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88307#-:-NCb7He8AQKBDNdwHpBL:bkc1kq6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @rytaft)

**Comment by ajwerner** [comment]
@dt can you chime in here? I know sql teams own import or whatever, but let's be real, you know the answers and we don't. I do see progress checkpointing here: 
https://github.com/cockroachdb/cockroach/blob/b8eee78e455ad97f85f6a74c22732d3c5f3ee349/pkg/sql/importer/import_processor_planning.go#L158-L179

**Comment by yuzefovich** [comment]
I agree, it does look like the import is doing the check-pointing, but there are other users of `validateUniqueConstraint` which might not - e.g. it is used at the end of the backfill and during restore. Is it worth relying on the caller to retry? To me the answer seems no, but I'm not familiar with these callers to have a strong opinion about it. #85711 indicates that either the  import doesn't do a good job of retrying itself or the test harness doesn't.

**Review by ajwerner — APPROVED** [review]
Fair enough

LGTM

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

**Comment by yuzefovich** [comment]
blathers backport 22.2

**Pull request merged**
