### PR TITLE
opt: add geo functions to constant folding whitelist

### LINKED ISSUE #48213: opt: support constant folding of geospatial functions
As described in the [Geospatial RFC](https://github.com/cockroachdb/cockroach/pull/47762), one of the important tasks of the optimizer for geospatial support will be to detect geospatial functions with all constant inputs, and perform constant folding. Since we already support constant folding for functions, this should be as simple as adding the relevant function names to the `FoldFunctionWhitelist`.

### PR DESCRIPTION
**Pull request by madelynnblue**
Fixes #48213

Release notes: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: 

cc @otan Are there any functions in this list that we should not fold for any reason given constant inputs? Also, it would be good to make sure that new functions get added to this list. Should we add a comment somewhere in `geo_builtins.go`?

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48446#-:-M6aFX795T0OfGzy5wTt:bom1h1m)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48446)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by madelynnblue — COMMENTED** [review]
added that comment

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48446#-:-M6aslPv1J-S6b70cWYn:b-y8vsj9)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48446)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by otan** [comment]
Should we take a blacklist approach to this instead? Only ones we shouldn't fold are the DDL ones and maybe ST_IsValid

**Comment by otan** [comment]
)(not a merge blocker)

**Comment by mjibson** [comment]
There's a comment and issue (#26582) that would be the reasonable thing to do.

https://github.com/cockroachdb/cockroach/blob/85cd1182ffe4641a1f01e44a9b0a257d8073b100/pkg/sql/opt/norm/fold_constants.go#L356

**Pull request merged**
