### PR TITLE
bulkio: make backup, restore, and import more resilient to node failures

### PR DESCRIPTION
**Pull request by pbardea**
This PR extracts error helpers that were specific to the changefeedccl package, so that they can
be used by all other jobs that run long-running DistSQL flows. This allows all jobs to be resilient to
node failures.

This commit does not fix that less-than-ideal error handling used to detect RPC failures from
DistSQL flow, but does aim to centralize the checks so that they occur only in 1 place.

Informs https://github.com/cockroachdb/cockroach/issues/50732.

Please see individual commits.

Release-justification: high impact fix

### CODE REVIEW

**Comment by pbardea** [comment]
cc @miretskiy @adityamaru from our conversation this morning. I tried several approaches here, and wanted to minimize where we check the errors against the strings and landed on this. I would have liked to get it all in 1 place, but I couldn't find a way to get around checking for `changefeedccl`-specific errors, which I thought should stay in `changefeedccl` (first commit). Curious if you have any thoughts there/on this approach in general.

**Comment by pbardea** [comment]
This is still failing a test, but wanted to get some eyes on this while I was fixing any tests.

I think the best way to test this would be something like https://github.com/cockroachdb/cockroach/pull/57588 which I can dust off

**Comment by HonoreDB** [comment]
Makes sense to me.

**Review by HonoreDB — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, 3 of 3 files at r2, 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60947)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @pbardea)

___
*[pkg/ccl/utilccl/errors.go, line 93 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60947#-MUoGTw3BJ50PWXRoi1D:-MUoGTw4C4hNUOyLeS1G:b-meengs) ([raw file](https://github.com/cockroachdb/cockroach/blob/694dec8c0c818bda5d6f2387de7d3a8017a244a1/pkg/ccl/utilccl/errors.go#L93)):*
> ```Go
> 			isCustomRetryable = true
> 		}
> 		if retryable := isDistSQLRetryableError(err) || isCustomRetryable; !retryable {
> ```

nit: switching the order `isCustomRetryable || isDistSQLRetryableError(err) ` can potentially short-circuit and save a call, whereas here the custom function's already been called regardless.

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60947)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @HonoreDB, and @miretskiy)

___
*[pkg/ccl/utilccl/errors.go, line 93 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60947#-MUoGTw3BJ50PWXRoi1D:-MUoNYeZ9Cs6s2HT5_kv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/694dec8c0c818bda5d6f2387de7d3a8017a244a1/pkg/ccl/utilccl/errors.go#L93)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

nit: switching the order `isCustomRetryable || isDistSQLRetryableError(err) ` can potentially short-circuit and save a call, whereas here the custom function's already been called regardless.
</blockquote></details>

Done.

**Review by miretskiy — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60947)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @HonoreDB, and @pbardea)

___
*[pkg/ccl/utilccl/errors.go, line 59 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/60947#-MUoZyY04slOXSY-ppU_:-MUoZyY04slOXSY-ppUa:b1gojif) ([raw file](https://github.com/cockroachdb/cockroach/blob/586c574acedcf5484b73a24cc3c3d92680126e2f/pkg/ccl/utilccl/errors.go#L59)):*
> ```Go
> 	return false
> }
> ```

I'm all for refactoring retryable error stuff above.  However, I'm not convinced that
providing helper functions below (RetryDistSQLFlow and the other one) actually helps -- quite the opposite.

I find that it is better to see at the call site the fact that we retry...
True, you'd have to repeat retry options, etc... but that's good -- your retry options may different (and in general, they are).
So, we have less flexibility and with these helpers, and they kinda hid what's going on...
I'd much rather see, at the call sites:
 ```
   for r := retry.StartWithCtx(ctx, opts); r.Next(); {
      if err := doSomething(); err != nil && !isRetryable() {return}
   }
```

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60947)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @HonoreDB, and @miretskiy)

___
*[pkg/ccl/utilccl/errors.go, line 59 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/60947#-MUoZyY04slOXSY-ppU_:-MUovbuC6RP4Ij9totj4:b-i3dymv) ([raw file](https://github.com/cockroachdb/cockroach/blob/586c574acedcf5484b73a24cc3c3d92680126e2f/pkg/ccl/utilccl/errors.go#L59)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I'm all for refactoring retryable error stuff above.  However, I'm not convinced that
providing helper functions below (RetryDistSQLFlow and the other one) actually helps -- quite the opposite.

I find that it is better to see at the call site the fact that we retry...
True, you'd have to repeat retry options, etc... but that's good -- your retry options may different (and in general, they are).
So, we have less flexibility and with these helpers, and they kinda hid what's going on...
I'd much rather see, at the call sites:
 ```
   for r := retry.StartWithCtx(ctx, opts); r.Next(); {
      if err := doSomething(); err != nil && !isRetryable() {return}
   }
```

</blockquote></details>

Good point, I also think it makes sense to limit the retries for operations like backup, restore, and import. If you've retried X times and are still running into rpc errors it's probably worth failing the job for the user to check. Will update.

**Comment by pbardea** [comment]
I've cleaned up the roachtests here and simplified the code-change to just a fixed number of retries in the job. Since we don't always have a good sense of the error retrying on rpc failures should improve general resilience to node failures without retrying indefinitely on non-transient rpc failures.

RFAL

**Comment by pbardea** [comment]
I also want to eventually move node-failure testing to unit tests so that they are more easily run, but from what I've seen the test server today is not setup to be stopped forcefully (ie without waiting for the stopper, which will wait for the job to complete). So I added the testing as roachtests. That also gave me more confidence that the errors it detects are ones that you would see from an actual node failure (rather than something mocked by testservers).

**Review by miretskiy — APPROVED** [review]
> Reviewed 1 of 15 files at r5, 4 of 16 files at r6, 10 of 13 files at r8, 1 of 6 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60947)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @HonoreDB, and @miretskiy)

**Pull request merged**
