### PR TITLE
changefeedccl: unskip pulsar in changefeed tests

### PR DESCRIPTION
**Pull request by rharding6373**
Epic: CRDB-9180

Release note: None

### CODE REVIEW

**Comment by rharding6373** [comment]
I stress tested all the tests in changefeedccl with only pulsar enabled and all tests passed.

**Comment by wenyihu6** [comment]
Did we do any work after https://github.com/cockroachdb/cockroach/pull/123791 to deflake the test failures?

**Review by wenyihu6 — APPROVED** [review]
Ahh I see. [Reverted the synchronous ](https://github.com/cockroachdb/cockroach/pull/123791) did the trick and deflaked the failures.

**Comment by rharding6373** [comment]
TFTR!

bors r=wenyihu6

**Pull request merged**
