### PR TITLE
build: tweak the TC test runner to detect package fails

### PR DESCRIPTION
**Pull request by knz**
Workaround for the issue identified in #57516

(I'm including the "panic" logic test to exercise this, I'll remove it before merging if it works)

### CODE REVIEW

**Comment by tbg** [comment]
Nice, if this works I'm +1.

cc @rickystewart @jlinder

**Comment by jordanlewis** [comment]
Thank you kindly @knz!

cc @nkodali regarding an example of a "quality of life" improvement for test infra.

**Comment by knz** [comment]
Ok this seems to work, now we have in the overview:

image

("PackageLevel" is a synthetic test name, without which TC would not report anything)

And also the thing does a best effort at including the package-level test outputs (that don't fit "under a test") in the details:

image

Are we happy with this?

**Comment by knz** [comment]
Improved this further. Now in overview:

image

And when expanding, a helpful hint:

image

**Comment by knz** [comment]
Link to example CI run with failure (using a temporary always-failing `panic` logictest): https://teamcity.cockroachdb.com/viewLog.html?buildId=2497525&buildTypeId=Cockroach_UnitTests

I'll now amend the patch to remove the panic file

**Comment by knz** [comment]
@tbg ok to merge this?

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57557)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @tbg)

___
*[pkg/cmd/testfilter/main.go, line 208 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57557#-MO6uMV84lxQ2dShun7H:-MO6uMV9-SIh_1GIdmW4:b-vw2pl6) ([raw file](https://github.com/cockroachdb/cockroach/blob/258810f9d3dda7b3d14ae49d92e007f27a1ef375/pkg/cmd/testfilter/main.go#L208)):*
> ```Go
> 				// the test failures are reported before the package failure
> 				// in the final output.
> 				for key := range m {
> ```

Our old go-test-teamcity script had similar behavior and it sometimes led to hundreds of failing tests getting reported (think TestLogic). I would feel better if we capped that at <10 tests to avoid similar spill.

We also don't want issues posted for these bogus failures, but I think now we would post them? It might be better to report them as skipped.

Or we maybe shouldn't report them at all. I was hoping we wouldn't based on my previous experience with doing so. I understand the urge to make this as user-friendly as possible, but this seems to tilt a bit too far in the direction of code that only the author really understands without staring at it for an hour. (Plus, it's not exactly over-tested). I was most happy with just synthesizing a single bogus test failure that is the hallmark of a package failing, which seems closer to the sweet spot of utility vs. maintainability.

**Comment by knz** [comment]
> Our old go-test-teamcity script had similar behavior and it sometimes led to hundreds of failing tests getting reported (think TestLogic). I would feel better if we capped that at <10 tests to avoid similar spill.

have you seen the code? it explicitly skips sub-tests.

**Review by tbg — COMMENTED** [review]
Oh, sorry! I don't know how I missed that. In that case, aren't we still going to be posting issues for innocent tests?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57557#-:-MO7-FNd8CCL4zIDMYsL:b-9f0rgr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @tbg)

**Comment by knz** [comment]
So my reasoning for including the individual test names is that it gives a hint about where to look for the stray failure. Necessarily, *one of* the "open ended" remaining tests is the cause of the panic.

But I hadn't considered the issue auto-poster. I will modify this to mark the open-ended tests as "skipped" instead of "failed". Would that work?

**Comment by tbg** [comment]
I think that should be good! Skipped tests definitely don't get issues filed for them.

**Comment by tbg** [comment]
Though at the same time, TC also doesn't really show them prominently. It will make discoverability hard.

**Comment by knz** [comment]
I found a workable solution: don't report the open-ended tests as TC Tests

instead, list their name in the "Output" payload of the PackageLevel pseudo-test.

**Comment by knz** [comment]
Here's what it looks like now:

image

**Comment by knz** [comment]
Link to an example CI failure with this logic in place: https://teamcity.cockroachdb.com/viewLog.html?buildId=2510215&buildTypeId=Cockroach_UnitTests

**Review by tbg — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57557)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

**Comment by knz** [comment]
bors r=tbg

**Pull request merged**
