### PR TITLE
storage: Delay initial metrics until system config is ready

### LINKED ISSUE #13560: storage: Remove or fix "initial metrics computation"
As soon as gossip is connected, we attempt to compute the store metrics: https://github.com/cockroachdb/cockroach/blob/6e9c78f05fdd06bec380ab701a7f422cd0564a10/pkg/storage/store.go#L1250-L1262

This (nearly) always fails because gossip becomes connected before the system config is available. It logs a INFO message and then we discard the error. (This line appears in the logs of nearly all our tests, and is the only message in the logs for many tests). 

We should either wait for the system config to be available before computing metrics or remove the call completely since it's consistently failing.

### PR DESCRIPTION
**Pull request by bdarnell**
This was previously done too soon at startup and would clutter the
logs (mainly in tests) with "failed initial metrics computation".

Fixes #13560

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16354#-:-Kly1hEF2FOWjKelfPnw:bnfp4nl)*

**Comment by bdarnell** [comment]
This hit a data race which has been undetected for a long time: #16363.

**Comment by spencerkimball** [comment]
Nice, was wanting to do this myself.

**Comment by tschottdorf** [comment]
@bdarnell you wanna merge this?

**Comment by bdarnell** [comment]
Yes. Rebased.

**Pull request merged**
