### PR TITLE
workload/roachtest: Fix load-based rebalancing test flakes by splitting kv keyspace evenly

### LINKED ISSUE #29969: roachtest: rebalance-replicas-by-load failed on master
SHA: https://github.com/cockroachdb/cockroach/commits/f1efbfa583f9dc0003ec57d78ad0ea8c5e49859e

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stressrace instead of stress and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
make stress TESTS=rebalance-replicas-by-load PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-stderr=false -maxtime 20m -timeout 10m'
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=892462&tab=buildLog

```
	test.go:498,rebalance_load.go:108,rebalance_load.go:135: timed out before leases were evenly spread

```

### PR DESCRIPTION
**Pull request by a-robinson**
**workload/kv: Add option to split key space evenly**

The default splitting behavior randomly chooses split points, which can
lead to ranges that encompass drastically different amounts of the key
space (e.g. I saw a 9x size difference in the run I examined that
motivated this). Having drastically different range sizes is a pain for
any tests that expect roughly even qps across the ranges.

If you'd prefer I can just write this into the rebalancing roachtest,
but it seemed like something that may be useful more broadly as well.

**roachtest: Split kv ranges evenly in load-based rebalancing tests**

Fixes #29969. The rebalance-replicas-by-load roachtest sometimes failed
to properly rebalance one range leaseholder for the kv table to each
node because the ranges could receive drastically different qps (where
two smaller ranges don't even come close to the qps of one larger one).

--------------

Also, while I'm here, improve the output of the test a bit and send SQL load to all of the nodes, not just the first three.

### CODE REVIEW

**Review by nvb — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30255)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/rebalance_load.go, line 199 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30255#-LMV3qNI4CAHGD0FUsvO:-LMV3qNI4CAHGD0FUsvP:bxneu3k) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff36e3fe7471c41768f8a18c522fc39687a47c63/pkg/cmd/roachtest/rebalance_load.go#L199)):*
> ```Go
> 	for storeID := range counts {
> 		storeIDs = append(storeIDs, storeID)
> 	}
> ```

Did you mean to `sort.Ints(storeIDs)` here?
___
*[pkg/cmd/roachtest/rebalance_load.go, line 76 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30255#-LMV4DQ7CzfzextYinxM:-LMV4DQ7CzfzextYinxN:b-lkegtq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5413b72b0d9a5d0e36f8ef393d0be37a38e1c749/pkg/cmd/roachtest/rebalance_load.go#L76)):*
> ```Go
> 				"./workload run kv --read-percent=95 --splits=%d --split-evenly --tolerate-errors "+
> 					"--concurrency=%d --duration=%s {pgurl:1-%d}",
> 				splits, concurrency, duration.String(), len(roachNodes)))
> ```

nit: `fmt.Sprintf(`{pgurl%s}`, roachNodes) also works, which is pretty neat.
___
*[pkg/workload/kv/kv.go, line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30255#-LMV3XIu21B-ww7ldMPK:-LMV3XIv1QO9H4eQ2oXR:b-rb0lhh) ([raw file](https://github.com/cockroachdb/cockroach/blob/dac709ef2a0f7b380cdb1635c5ffe9c98927bfff/pkg/workload/kv/kv.go#L119)):*
> ```Go
> 			w.splits,
> 			func(splitIdx int) []interface{} {
> 				if w.splitEvenly {
> ```

Is there a reason why we shouldn't always do this?

**Review by a-robinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30255)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/rebalance_load.go, line 199 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30255#-LMV3qNI4CAHGD0FUsvO:-LMcBTzYEiifAVilM5Ka:b-nxnv38) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff36e3fe7471c41768f8a18c522fc39687a47c63/pkg/cmd/roachtest/rebalance_load.go#L199)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Did you mean to `sort.Ints(storeIDs)` here?
</blockquote></details>

🤦 thanks
___
*[pkg/cmd/roachtest/rebalance_load.go, line 76 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30255#-LMV4DQ7CzfzextYinxM:-LMcBHnSDnPXjJz0F0rt:b-lao53p) ([raw file](https://github.com/cockroachdb/cockroach/blob/5413b72b0d9a5d0e36f8ef393d0be37a38e1c749/pkg/cmd/roachtest/rebalance_load.go#L76)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: `fmt.Sprintf(`{pgurl%s}`, roachNodes) also works, which is pretty neat.
</blockquote></details>

Cute. I'll stick with this, though. It's clearer and used by more other tests.
___
*[pkg/workload/kv/kv.go, line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30255#-LMV3XIu21B-ww7ldMPK:-LMcBaq11aqgENr5qoCe:b-6cvuuk) ([raw file](https://github.com/cockroachdb/cockroach/blob/dac709ef2a0f7b380cdb1635c5ffe9c98927bfff/pkg/workload/kv/kv.go#L119)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is there a reason why we shouldn't always do this?
</blockquote></details>

I was hoping you'd ask that. Not a good one, as far as I can see. It will change what happens if you run `kv --splits` multiple times against the same cluster, but I doubt that anyone was relying on the old behavior. This certainly makes tests (including performance tests) more repeatable.

Should I just remove the old split logic entirely so that this is always used?

**Review by nvb — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30255)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/workload/kv/kv.go, line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30255#-LMV3XIu21B-ww7ldMPK:-LMccs8m2emA6vwFGLin:benlqis) ([raw file](https://github.com/cockroachdb/cockroach/blob/dac709ef2a0f7b380cdb1635c5ffe9c98927bfff/pkg/workload/kv/kv.go#L119)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

I was hoping you'd ask that. Not a good one, as far as I can see. It will change what happens if you run `kv --splits` multiple times against the same cluster, but I doubt that anyone was relying on the old behavior. This certainly makes tests (including performance tests) more repeatable.

Should I just remove the old split logic entirely so that this is always used?
</blockquote></details>

Yeah, let's do that. FWIW most workloads (tpcc, ledger, etc.) already have deterministic split points.

**Review by a-robinson — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30255#-:-LMciGdGAJKMIOjW_xOO:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/workload/kv/kv.go, line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30255#-LMV3XIu21B-ww7ldMPK:-LMciG2o2k44-qIIrYi0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dac709ef2a0f7b380cdb1635c5ffe9c98927bfff/pkg/workload/kv/kv.go#L119)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yeah, let's do that. FWIW most workloads (tpcc, ledger, etc.) already have deterministic split points.
</blockquote></details>

Done.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30255#-:-LMcmPhgD1acV51ELCIQ:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
