### PR TITLE
backupccl: deflake a test under stress

### LINKED ISSUE #109093: ccl/backupccl: TestFullClusterBackup failed
ccl/backupccl.TestFullClusterBackup [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/11400990?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/11400990?buildTab=artifacts#/) on master @ [31fe139c74640a383599c53719a39f0190a7065d](https://github.com/cockroachdb/cockroach/commits/31fe139c74640a383599c53719a39f0190a7065d):

```
=== RUN   TestFullClusterBackup
    test_log_scope.go:167: test logs captured to: /artifacts/tmp/_tmp/95e138e66d69292427dfb9528cf06d04/logTestFullClusterBackup2299892925
    test_log_scope.go:81: use -show-logs to present logs inline
```
<p>Parameters: <code>TAGS=bazel,gss</code>
, <code>stress=true</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestFullClusterBackup.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-30773

### PR DESCRIPTION
**Pull request by lidorcarmel**
Running locally, this test takes about 30 seconds when running once, 60 seconds when running 2 in parallel, and 15 minutes when running 8. Stress normally runs 1000 which times out.

With this change 8 run within a 90 seconds (the batching did the trick, dropping the ALTER is nice to have).

The second commit is applying a similar fix to another test in the same file, and also uses fewer users under race which allows us to unskip under race.

Epic: none

Fixes: #109093

Release note: None

### CODE REVIEW

**Review by stevendanna — COMMENTED** [review]
I think there is another test in this file that does something similar, can we fix that one up too while we are here?

**Review by stevendanna — APPROVED** [review]

**Comment by lidorcarmel** [comment]
indeed there is another one, fixing in a separate commit (also unskipping that test under race).
done, thanks!

**Comment by lidorcarmel** [comment]
TFTR!
bors r+

**Comment by adityamaru** [comment]
blathers backport 23.1

**Pull request merged**
