### PR TITLE
tsdump: add various HTTP upload mechanisms for timeseries data

### PR DESCRIPTION
**Pull request by dhartunian**
**tsdump: tsdump can write to http endpoint**

A new command line flag is available when using `--format openmetrics` with tsdump. Adding `--target-url` and adding a fully qualified HTTP endpoint that accepts a streaming openmetrics request body will push the openmetrics data to that endpoint instead of stdout.

This is meant for use with a tsdb which supports backfill of historical data in openmetrics format.

Part of CRDB-33038
Epic: CC-24457

Release note: None

----
**tsdump: add JSON upload format**

This change adds support for `--format json` which will send the
JSON payload of metrics to an HTTP target for every 10MiB buffer it
accumulates.

This is designed for use with the VictoriaMetrics JSON upload
endpoint which accepts arbitrary timestamps.

Part of: [CRDB-33038](https://cockroachlabs.atlassian.net/browse/CRDB-33038)
Epic: [CC-24457](https://cockroachlabs.atlassian.net/browse/CC-24457)

Release note: None

----
**tsdump: add ability to upload metrics to Datadog**

To upload metrics to datadog use the `--format datadog` flag with
`tsdump` on an existing raw dump file.

Metrics are upload with the `crdb.tsdump.` prefix.

In order to upload historical metrics that are more than a few hours
old, you will need to enable your custom metrics for historical
upload. To make this a bit easier, you can first upload using the
`--format datadoginit` flag which inserts zero metric values for
all metric names with the current timestamp. This will let you see
the metrics in DD UI and enable historical upload before uploading
everything.

Part of: [CRDB-33038](https://cockroachlabs.atlassian.net/browse/CRDB-33038)
Epic: [CC-24457](https://cockroachlabs.atlassian.net/browse/CC-24457)
Release note: None

----
**tsdump: add datadriven test for json and datadog outputs**

Extracted out some code for making HTTP requests to make the tsdump
code testable.

Epic: None
Release note: None

### CODE REVIEW

**Review by abarganier — COMMENTED** [review]
Code LGTM overall. Is there a way we could do a unit or integration test for this using a mock HTTP server? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119685#-:-NsJm8rCCRpXcV1grFUn:b-klp9td)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

**Comment by dhartunian** [comment]
@abarganier PTAL, I added tests

**Review by abarganier — COMMENTED** [review]
Nice job with the tests! Mostly LGTM, but I have a few minor comments. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119685#-:-NuUQ3eT6FK4uofJrgLV:bppnqhm)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @xinhaoz)

___
*[`pkg/cli/tsdump.go` line 292 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/119685#-NuUIzyU6C1geWAPI2MI:-NuUIzyVAujPYsA7z2bT:b-gp86vs) ([raw file](https://github.com/cockroachdb/cockroach/blob/c68d6d692526852fded629464f95394a8b79593c/pkg/cli/tsdump.go#L292)):*
> ```Go
> 	out.Metric["job"] = "cockroachdb"
> 	out.Metric["region"] = "local"
> 	// Zero values
> ```

nit: I just realized, the motivation for having all these zero value labels might be something that's lost over time. Can we expand this comment to note the reason we need all these zero value labels? 



_Code quote:_
```Go
	// Zero values
```
___
*[`pkg/cli/tsdump.go` line 305 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/119685#-NuUJqb1EBu4KIT-hJVy:-NuUJqb1EBu4KIT-hJVz:bvwkeyi) ([raw file](https://github.com/cockroachdb/cockroach/blob/c68d6d692526852fded629464f95394a8b79593c/pkg/cli/tsdump.go#L305)):*
> ```Go
> 		out.Metric["cluster"] = serverCfg.ClusterName
> 	} else {
> 		out.Metric["cluster"] = fmt.Sprintf("cluster-debug-%d", o.timestamp)
> ```

nit: should we log something indicating to the user what the `cluster` label value is being set to? My thinking is that this would make it easier to get an initial query down in VictoriaMetrics that's scoped to the cluster, instead of having to do some digging to figure out what the cluster label is. 



_Code quote:_
```Go
out.Metric["cluster"] = fmt.Sprintf("cluster-debug-%d", o.timestamp)
```
___
*[`pkg/cli/tsdump.go` line 479 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/119685#-NuUNHByDLVMdaKBu33x:-NuUNHByDLVMdaKBu33y:ba7ul17) ([raw file](https://github.com/cockroachdb/cockroach/blob/a65579ac98963ba6a6822b9fa3aaa1d533ca7d17/pkg/cli/tsdump.go#L479)):*
> ```Go
> 	//	}
> 	//}
> 	//return 0
> ```

nit: can we delete this commented code?



_Code quote:_
```Go
	return 1
	//for name, meta := range d.metricsMetadata {
	//	if strings.HasSuffix(data.Name, name) {
	//		switch meta.MetricType {
	//		case io_prometheus_client.MetricType_COUNTER:
	//			return 1
	//		case io_prometheus_client.MetricType_GAUGE:
	//			return 3
	//		default:
	//			return 0
	//		}
	//	}
	//}
	//return 0
```
___
*[`pkg/cli/tsdump.go` line 108 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/119685#-NuUPScH4yZliSzjqiWD:-NuUPScH4yZliSzjqiWE:b-alimw8) ([raw file](https://github.com/cockroachdb/cockroach/blob/211271d56f49d1a474ab94993c1be649efb8605d/pkg/cli/tsdump.go#L108)):*
> ```Go
> 				debugTimeSeriesDumpOpts.targetURL,
> 				debugTimeSeriesDumpOpts.httpToken,
> 				10_000_000,
> ```

nit: inline param name comments here and below for literal args.



_Code quote:_
```Go
				10_000_000,
```
___
*[`pkg/cli/tsdump.go` line 376 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/119685#-NuUPpOeDd3YVwHCgYps:-NuUPpOeDd3YVwHCgYpt:bx4wfwc) ([raw file](https://github.com/cockroachdb/cockroach/blob/211271d56f49d1a474ab94993c1be649efb8605d/pkg/cli/tsdump.go#L376)):*
> ```Go
> func (d *datadogWriter) Emit(data *tspb.TimeSeriesData) error {
> 	series := &DatadogSeries{
> 		// TODO(davidh): this is not correct. we should inspect metric metadata and set appropriately
> ```

nit: what's the impact of always setting the series type to 0? Does Datadog handle it well? 



_Code quote:_
```Go
		// TODO(davidh): this is not correct. we should inspect metric metadata and set appropriately
```

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119685)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @xinhaoz)

___
*[`pkg/cli/tsdump.go` line 292 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/119685#-NuUIzyU6C1geWAPI2MI:-NueJIXnEi4OBvdqTrh_:b-4jcp9o) ([raw file](https://github.com/cockroachdb/cockroach/blob/c68d6d692526852fded629464f95394a8b79593c/pkg/cli/tsdump.go#L292)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: I just realized, the motivation for having all these zero value labels might be something that's lost over time. Can we expand this comment to note the reason we need all these zero value labels?
</blockquote></details>

Honestly no clue why it's that way. I'll omit from my new code at least.
___
*[`pkg/cli/tsdump.go` line 305 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/119685#-NuUJqb1EBu4KIT-hJVy:-NueJM-340Qn8gCo6H0l:bdd4vz9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c68d6d692526852fded629464f95394a8b79593c/pkg/cli/tsdump.go#L305)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: should we log something indicating to the user what the `cluster` label value is being set to? My thinking is that this would make it easier to get an initial query down in VictoriaMetrics that's scoped to the cluster, instead of having to do some digging to figure out what the cluster label is.
</blockquote></details>

Good idea. done.
___
*[`pkg/cli/tsdump.go` line 479 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/119685#-NuUNHByDLVMdaKBu33x:-NueIj9W2xrwZRUAMppS:boa0nfp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a65579ac98963ba6a6822b9fa3aaa1d533ca7d17/pkg/cli/tsdump.go#L479)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: can we delete this commented code?
</blockquote></details>

It's deleted in the next commit
___
*[`pkg/cli/tsdump.go` line 108 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/119685#-NuUPScH4yZliSzjqiWD:-NueIWht3peZAP8VCVuT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/211271d56f49d1a474ab94993c1be649efb8605d/pkg/cli/tsdump.go#L108)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: inline param name comments here and below for literal args.
</blockquote></details>

Done.
___
*[`pkg/cli/tsdump.go` line 376 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/119685#-NuUPpOeDd3YVwHCgYps:-NueIXJu3yk0E3kxqidl:b-otcnja) ([raw file](https://github.com/cockroachdb/cockroach/blob/211271d56f49d1a474ab94993c1be649efb8605d/pkg/cli/tsdump.go#L376)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: what's the impact of always setting the series type to 0? Does Datadog handle it well?
</blockquote></details>

Yes, it just assumes gauge which is "fine". Added a note and clarified possible options into an enum.

**Review by abarganier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119685)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @xinhaoz)

___
*[`pkg/cli/tsdump.go` line 292 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/119685#-NuUIzyU6C1geWAPI2MI:-Nv2HdyQ-MkCMFIsejxW:bruyi07) ([raw file](https://github.com/cockroachdb/cockroach/blob/c68d6d692526852fded629464f95394a8b79593c/pkg/cli/tsdump.go#L292)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Honestly no clue why it's that way. I'll omit from my new code at least.
</blockquote></details>

IIRC, when Eric was first prototyping this for ingest into Mimir, many dashboards were built around an expectation that a certain label set would be present on all metrics. I think he added these zero values to make the ingested metrics play nicely with existing dashboards. 

Of course, if we can axe them, even better :slightly_smiling_face: 
___
*[`pkg/cli/tsdump.go` line 479 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/119685#-NuUNHByDLVMdaKBu33x:-Nv2IWjuBocnZaRVwluF:b-i7wwnl) ([raw file](https://github.com/cockroachdb/cockroach/blob/a65579ac98963ba6a6822b9fa3aaa1d533ca7d17/pkg/cli/tsdump.go#L479)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

It's deleted in the next commit
</blockquote></details>

Ack. Thanks.
___
*[`pkg/cli/tsdump.go` line 108 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/119685#-NuUPScH4yZliSzjqiWD:-Nv2HLdk4_C0IrwbW75z:b-77zxmq) ([raw file](https://github.com/cockroachdb/cockroach/blob/211271d56f49d1a474ab94993c1be649efb8605d/pkg/cli/tsdump.go#L108)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry to nit again, but I think we missed them for `tsDumpDatadogInit`, and the 3rd bool param for `makeDatadogWriter()`. 
___
*[`pkg/cli/tsdump.go` line 376 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/119685#-NuUPpOeDd3YVwHCgYps:-Nv2K1XM8SeIQKruRwha:b-anru0k) ([raw file](https://github.com/cockroachdb/cockroach/blob/211271d56f49d1a474ab94993c1be649efb8605d/pkg/cli/tsdump.go#L376)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Yes, it just assumes gauge which is "fine". Added a note and clarified possible options into an enum.
</blockquote></details>

Thanks for clarifying. 

Seems like we could get this metadata via `(*adminServer).AllMetricMetadata()`? I'm down to punt that, but maybe just note it in a comment. 

Does setting everything to Gauge limit which functions can be applied to the metric within Datadog?
___
*[`pkg/cli/tsdump.go` line 573 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/119685#-Nv2J33d6FVeVyAHkDiG:-Nv2J33eB8sWyyDbaQP9:b-sa9zfk) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fe24c94637fec05cbb244ef253c593f51445ecd/pkg/cli/tsdump.go#L573)):*
> ```Go
> 		out.Metric["cluster"] = fmt.Sprintf("cluster-debug-%d", o.timestamp)
> 	}
> 	fmt.Printf("Cluster label is set to: %s\n", out.Metric["cluster"])
> ```

Can we log this for the Datadog writer as well? Optionally, we could factor this cluster label determination logic into a shared helper and log there.



_Code quote:_
```Go
	fmt.Printf("Cluster label is set to: %s\n", out.Metric["cluster"])
```

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119685)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @xinhaoz)

___
*[`pkg/cli/tsdump.go` line 292 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/119685#-NuUIzyU6C1geWAPI2MI:-NvX9Qfq57VelG4F1lbA:b-bsjaa1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c68d6d692526852fded629464f95394a8b79593c/pkg/cli/tsdump.go#L292)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

IIRC, when Eric was first prototyping this for ingest into Mimir, many dashboards were built around an expectation that a certain label set would be present on all metrics. I think he added these zero values to make the ingested metrics play nicely with existing dashboards. 

Of course, if we can axe them, even better :slightly_smiling_face:
</blockquote></details>

Ah that's helpful context. I tested without the labels on centmon and the extra ones in the query just get ignored so I'll omit them.
___
*[`pkg/cli/tsdump.go` line 108 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/119685#-NuUPScH4yZliSzjqiWD:-NvX9Phb2b5xd77gIRZB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/211271d56f49d1a474ab94993c1be649efb8605d/pkg/cli/tsdump.go#L108)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

Sorry to nit again, but I think we missed them for `tsDumpDatadogInit`, and the 3rd bool param for `makeDatadogWriter()`.
</blockquote></details>

Done.
___
*[`pkg/cli/tsdump.go` line 376 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/119685#-NuUPpOeDd3YVwHCgYps:-Nvc8E9O1WCYEMY6JMNn:bbjqb5d) ([raw file](https://github.com/cockroachdb/cockroach/blob/211271d56f49d1a474ab94993c1be649efb8605d/pkg/cli/tsdump.go#L376)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

Thanks for clarifying. 

Seems like we could get this metadata via `(*adminServer).AllMetricMetadata()`? I'm down to punt that, but maybe just note it in a comment. 

Does setting everything to Gauge limit which functions can be applied to the metric within Datadog?
</blockquote></details>

Noted in comment. I'm going to leave the DD debugging to the next engineer.
___
*[`pkg/cli/tsdump.go` line 573 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/119685#-Nv2J33d6FVeVyAHkDiG:-Nvc8IRz3Yau_wwbz4Cj:b-7c1owh) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fe24c94637fec05cbb244ef253c593f51445ecd/pkg/cli/tsdump.go#L573)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

Can we log this for the Datadog writer as well? Optionally, we could factor this cluster label determination logic into a shared helper and log there.
</blockquote></details>

Hah I had actually removed this because it printed on every emit. put it back behind a sync.Once.

**Review by abarganier — APPROVED** [review]
:lgtm: - nice work on this! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119685#-:-NvhjSZU9GyNd3SPUIKp:bdgclps)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dhartunian and @xinhaoz)

___
*[`pkg/cli/tsdump.go` line 292 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/119685#-NuUIzyU6C1geWAPI2MI:-Nvhj9QRCa5mZeo9_39r:b-b4am7x) ([raw file](https://github.com/cockroachdb/cockroach/blob/c68d6d692526852fded629464f95394a8b79593c/pkg/cli/tsdump.go#L292)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Ah that's helpful context. I tested without the labels on centmon and the extra ones in the query just get ignored so I'll omit them.
</blockquote></details>

Nice, sgtm! Thanks.
___
*[`pkg/cli/tsdump.go` line 376 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/119685#-NuUPpOeDd3YVwHCgYps:-NvhjDxQ3dM7QNYzLGFb:b-jz85gr) ([raw file](https://github.com/cockroachdb/cockroach/blob/211271d56f49d1a474ab94993c1be649efb8605d/pkg/cli/tsdump.go#L376)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Noted in comment. I'm going to leave the DD debugging to the next engineer.
</blockquote></details>

:vulcan_salute: 
___
*[`pkg/cli/tsdump.go` line 573 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/119685#-Nv2J33d6FVeVyAHkDiG:-NvhjJ9K8L5pSijQmEfi:b9ldnbq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fe24c94637fec05cbb244ef253c593f51445ecd/pkg/cli/tsdump.go#L573)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Hah I had actually removed this because it printed on every emit. put it back behind a sync.Once.
</blockquote></details>

Cool, thanks!

**Comment by dhartunian** [comment]
TFTR!

bors r=abarganier

**Pull request merged**
