### PR TITLE
settings: introduce retired setting state

### PR DESCRIPTION
**Pull request by dt**
Addresses discussion in #21129: eagerly introducing a migration to delete a removed setting's value is risky, as older nodes are likely still using that value. We should delay any removal until after the cluster upgrade process is completed and no old nodes could be affected by the deletion. 

However, we can also just avoid accidental re-use of the name, and the log spam of an unknown value, by maintaining a list of retired settings, without needing to delete at all for now. 

In the future, if this list grows large, we can add version-protected migrations that flush this list,  cleaning up old values for all the previous version's retired settings at once, once the upgrade process ensures it is safe to do so, without adding that overhead on each individual setting removal.

Release note: none.

### CODE REVIEW

**Comment by dt** [comment]
if we like this approach to #21129, I think we should also move the two existing migrations over to be entries in this list.

**Comment by knz** [comment]
yeah I suppose this works. Thanks! :lgtm: 

---

Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23130#-:-L6MpqMp7iH832OVZQG9:b-udu9pi)*

**Comment by bdarnell** [comment]
:lgtm:

And yes, we should replace the existing migrations.

---

Review status: 1 of 3 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23130#-:-L6N6SjyD6TYc9YKsXh3:b77pdzf)*

**Comment by dt** [comment]
TFTRs, added retired entries and removed the workFn from those migrations, which, based on discussion with @benesch, is the preferred way to remove a migration. RFAL.

**Comment by knz** [comment]
Thanks :shipit: 

---

Reviewed 2 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23130#-:-L6NIqkS94rjJ-fU-FJx:bemy4r9)*

**Review by benesch — APPROVED** [review]
Migrations change LGTM. Thanks!

**Pull request merged**
