### PR TITLE
opt: Make several perf tweaks to speed up simple queries

### PR DESCRIPTION
**Pull request by andy-kimball**
Together, these changes improve the Optbuild scenarios from:
```
Phases/kv-read/OptBuild  21.4µs ± 2%
```
to:
```
Phases/kv-read/OptBuild  18.0µs ± 2%
```

NOTE: I changed my timing methodology so that I'm benchmarking on a single CPU (i.e. GC no longer allowed to run on another CPU). So the the 3us are not directly comparable to previous improvements in this scenario.

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28595#-:-LJuriAL-B3U9dmuu3oH:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by petermattis — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 14 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28595#-:-LJv9kdR1tFhGXc8Qmz-:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/memo/memo.go, line 109 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28595#-LJv9eW5-flWQ-qly3Ge:-LJv9eW5-flWQ-qly3Gf:btyhmcv) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f9cdaeb2eb97d6fd78c1af9af9655d56670d25a/pkg/sql/opt/memo/memo.go#L109)):*
> ```Go
> 	// metadata provides information about the columns and tables used in this
> 	// particular query.
> 	metadata *opt.Metadata
> ```

Is there a reason for this to be a pointer? It seems tied to the lifetime of the `Memo`.
___
*[pkg/sql/opt/memo/memo.go, line 145 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28595#-LJv99PO66xlrzoV0Lte:-LJv99PO66xlrzoV0Ltf:brwfkgv) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f9cdaeb2eb97d6fd78c1af9af9655d56670d25a/pkg/sql/opt/memo/memo.go#L145)):*
> ```Go
> 	m := &Memo{
> 		metadata: opt.NewMetadata(),
> 		exprMap:  make(map[Fingerprint]GroupID),
> ```

I wonder if we should specify an initial expected map size, both here and for `privatesMap`.

Another thought: for a small map, a linear search of the `groups` is faster and would avoid the `map` allocation. Perhaps we could lazily switch from such a search to using `exprMap`. That might be getting too far down optimizing the `kv-read` query.
___
*[pkg/sql/opt/memo/memo.go, line 146 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28595#-LJv8yl7E5Qta90yEUI4:-LJv8yl7E5Qta90yEUI5:b2mmgwb) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f9cdaeb2eb97d6fd78c1af9af9655d56670d25a/pkg/sql/opt/memo/memo.go#L146)):*
> ```Go
> 		metadata: opt.NewMetadata(),
> 		exprMap:  make(map[Fingerprint]GroupID),
> 		groups:   make([]group, 1, 8),
> ```

Heh, how did you arrive at `8`? I ask because I also noticed this and used `8` but I'm not sure why.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28595)* status: :shipit: complete! 2 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/memo.go, line 109 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28595#-LJv9eW5-flWQ-qly3Ge:-LJv_fbl7KbMmSSZEOW5:bv7tnyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f9cdaeb2eb97d6fd78c1af9af9655d56670d25a/pkg/sql/opt/memo/memo.go#L109)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is there a reason for this to be a pointer? It seems tied to the lifetime of the `Memo`.
</blockquote></details>

Yes, this can be inlined as well. I can do in a future PR (I'm just posting them as I go, and opening the next).
___
*[pkg/sql/opt/memo/memo.go, line 145 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28595#-LJv99PO66xlrzoV0Lte:-LJv_CIvATE3noB4phUB:brmjgjo) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f9cdaeb2eb97d6fd78c1af9af9655d56670d25a/pkg/sql/opt/memo/memo.go#L145)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I wonder if we should specify an initial expected map size, both here and for `privatesMap`.

Another thought: for a small map, a linear search of the `groups` is faster and would avoid the `map` allocation. Perhaps we could lazily switch from such a search to using `exprMap`. That might be getting too far down optimizing the `kv-read` query.
</blockquote></details>

Yeah, I've thought a bit about those possibilities. I'll play around in a future PR (or if you decide you want to take a crack, that's fine as well).
___
*[pkg/sql/opt/memo/memo.go, line 146 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28595#-LJv8yl7E5Qta90yEUI4:-LJvZd0oAOKUZO6hu9BJ:bt39ks0) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f9cdaeb2eb97d6fd78c1af9af9655d56670d25a/pkg/sql/opt/memo/memo.go#L146)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Heh, how did you arrive at `8`? I ask because I also noticed this and used `8` but I'm not sure why.
</blockquote></details>

1. Because powers of 2 are ... just better. Every 1 knows it.
2. Because 8 is enough not to need resizing in the simplest cases we're worried about.
3. Because 16 seems like it would waste too much memory in simple cases.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28595)* status: :shipit: complete! 2 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/memo.go, line 145 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28595#-LJv99PO66xlrzoV0Lte:-LJxcI586SRj1SoEsaJD:b-4pmn8w) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f9cdaeb2eb97d6fd78c1af9af9655d56670d25a/pkg/sql/opt/memo/memo.go#L145)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Yeah, I've thought a bit about those possibilities. I'll play around in a future PR (or if you decide you want to take a crack, that's fine as well).
</blockquote></details>

I doubt I'll have time, so consider this on your plate to play around with unless I ping you otherwise.

**Pull request merged**
