### PR TITLE
Add issue status and affected test suites to blacklist_test

### LINKED ISSUE #42548: unimplemented: linter to make sure that all linked issues are still open
We should make a new test in `blacklist_test.go` to query GitHub to ensure that all linked issues are actually still open.

### PR DESCRIPTION
**Pull request by apantel**
Fixes #42548

blacklist_test now includes in its output the status of each ticket,
and which blacklists each ticket appears in. The test fails if any
tickets are not open. This test is now skipped; we will only run it on
demand.

Release note: None

### CODE REVIEW

**Comment by apantel** [comment]
https://docs.google.com/spreadsheets/d/1sSwVqw-YFD8nvefxo7iU7DxqqD5op_L6VKAgccZ04JI/edit#gid=2020337687 for example of output

**Review by jordanlewis — COMMENTED** [review]
:lgtm: - I think the cache thing is nice since I do think it takes a little while to pull all the issue names, but I guess I don't feel that strongly about keeping it if you don't want to.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42830#-:-LvIV0l33GysMWZax9Vr:b5sa2si)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Review by apantel — COMMENTED** [review]
The cache doesn't save anything in this version since we're fetching all the open/closed statuses anyway.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42830#-:-LvL_FfK4IUHksJ25LhN:b-czz0k4)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by jordanlewis** [comment]
Great point, LGTM!

**Pull request merged**
