### PR TITLE
kvserver, kvclient: allow Rangefeeds to run over non-voting replicas

### LINKED ISSUE #59454: kvserver: allow rangefeeds over non-voting replicas
RangeFeeds currently only [work over voting replicas](https://github.com/cockroachdb/cockroach/blob/b44a0a0f184ad8437ee56b133dc6ecc7227e4393/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L233). This includes followers as well as the leaseholder. Now that we're adding [non-voting replicas](https://github.com/cockroachdb/cockroach/issues/51943), we should allow rangefeeds to run over these non-voting replicas as well.

### PR DESCRIPTION
**Pull request by aayushshah15**
Fixes #59454.

Release justification: low risk high benefit change to be able to fuel CDC streams using non-voting replicas

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59507)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15)

___
*[pkg/kv/kvserver/replica_rangefeed_test.go, line 121 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59507#-MS8lLDI83NVLp_YJEsc:-MS8lLDI83NVLp_YJEsd:bloxmq6) ([raw file](https://github.com/cockroachdb/cockroach/blob/64ba572b89282de042d04bce666c14bfb81acc87/pkg/kv/kvserver/replica_rangefeed_test.go#L121)):*
> ```Go
> 		tc.SplitRangeOrFatal(t, startKey)
> 
> 		if withNonVoters {
> ```

Instead of the RunTrueAndFalse, maybe we just add 2 voters and 2 non-voters and make sure that all 5 replicas can serve rangefeeds?
___
*[pkg/kv/kvserver/replica_rangefeed_test.go, line 161 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59507#-MS8l4vV8zEDRJANkxZv:-MS8l4vV8zEDRJANkxZw:bkwk8jt) ([raw file](https://github.com/cockroachdb/cockroach/blob/64ba572b89282de042d04bce666c14bfb81acc87/pkg/kv/kvserver/replica_rangefeed_test.go#L161)):*
> ```Go
> 					WithDiff: true,
> 				}
> 				pErr := store.RangeFeed(&req, stream)
> ```

Is this test testing the change you made in this PR? It's a good test case to add regardless, but it doesn't seem to be going through the DistSender. Does the test pass even if you revert the other half of this change?

**Comment by aayushshah15** [comment]
woops, I didn't realize this wasn't a draft PR. Was lazily prototyping & wanted CI to run on it.

**Comment by nvanbenschoten** [comment]
@amruss this is the PR you'll want to wait on before testing CDC + multi-region.

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59507)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_rangefeed_test.go, line 121 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59507#-MS8lLDI83NVLp_YJEsc:-MUlvmts7tfKg01eMKX_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/64ba572b89282de042d04bce666c14bfb81acc87/pkg/kv/kvserver/replica_rangefeed_test.go#L121)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Instead of the RunTrueAndFalse, maybe we just add 2 voters and 2 non-voters and make sure that all 5 replicas can serve rangefeeds?
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replica_rangefeed_test.go, line 161 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59507#-MS8l4vV8zEDRJANkxZv:-MUlvVY-ABKGRAejBUbY:bfd7yrc) ([raw file](https://github.com/cockroachdb/cockroach/blob/64ba572b89282de042d04bce666c14bfb81acc87/pkg/kv/kvserver/replica_rangefeed_test.go#L161)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this test testing the change you made in this PR? It's a good test case to add regardless, but it doesn't seem to be going through the DistSender. Does the test pass even if you revert the other half of this change?
</blockquote></details>

Added a new test.

**Review by nvb — APPROVED** [review]
:lgtm: though the test seems to be having issues:
```
=== RUN   TestRangefeedIsRoutedToNonVoter
    test_log_scope.go:73: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestRangefeedIsRoutedToNonVoter106363519
    test_log_scope.go:74: use -show-logs to present logs inline
panic: test timed out after 15m0s

goroutine 53 [chan receive, 14 minutes]:
github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestRangefeedIsRoutedToNonVoter(0xc000103500)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/client_rangefeed_test.go:231 +0x82e
testing.tRunner(0xc000103500, 0x4e19a48)
	/usr/local/go/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1168 +0x2b3
```

> Reviewed 19 of 19 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59507#-:-MUq8KwS693HiYplo6Ch:b4ar2zu)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by aayushshah15** [comment]
Fixed CI. 

TFTR!

bors r+

**Pull request merged**
