### PR TITLE
sql: unskip a logic test

### LINKED ISSUE #41283: sql: column family difference in fakedist with dates
The datetime sqllogic test fails under fakedist-metadata and fakedist-disk sometimes during column family randomization. May be the same as #41277.

### PR DESCRIPTION
**Pull request by jordanlewis**
Closes #41283

Release note: None

### CODE REVIEW

**Comment by rohany** [comment]
LGTM

**Comment by rohany** [comment]
can you rebase this

**Comment by rohany** [comment]
bump

**Comment by jordanlewis** [comment]
Random flake. Merging.

bors r+

**Review by jordanlewis — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47764#-:-M6VA9mTCrC9ARHj4Qdd:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany)

**Pull request merged**
