### PR TITLE
streamingccl: helper to cutover to latest high watermark

### PR DESCRIPTION
**Pull request by stevendanna**
This adds an overload to crdb_internal.complete_stream_ingestion_job
that sets the cutover time to whatever the most recent high watermark
is.

Release justification: Low-risk test feature for non-production feature.

Release note: None

### CODE REVIEW

**Review by gh-casper — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86029#-:-NA7VX6A98lKtSkGgaQR:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @gh-casper)

**Comment by stevendanna** [comment]
bors r=gh-casper

**Comment by stevendanna** [comment]
bors retry

**Comment by stevendanna** [comment]
bors retry

**Comment by stevendanna** [comment]
bors retry

**Comment by stevendanna** [comment]
We have all this and more now. Closing.

**Pull request closed without merging**
