### PR TITLE
sql/schemachanger: rework gcjob creation for descriptions

### PR DESCRIPTION
**Pull request by ajwerner**
This should also be a bit easier to extend in directions we'll need to go in
the future.

Part of dealing with #78030.

Release note: None

### CODE REVIEW

**Comment by postamar** [comment]
I like where this is going.

**Comment by ajwerner** [comment]
RFAL

**Review by postamar — APPROVED** [review]
:lgtm_strong: 

Very nice.

> Reviewed 26 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79024#-:-MzQBR7L5GsA7yi-Wqdx:b-5u1oo6)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/schemachanger/testdata/drop, line 6420 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79024#-MzQ7KzJ31eW8Irs6NLh:-MzQ7KzJ31eW8Irs6NLi:b-kupff8) ([raw file](https://github.com/cockroachdb/cockroach/blob/9674980d44e32f84ccb50273a7c5db67fa8a6521/pkg/sql/schemachanger/testdata/drop#L6420)):*
> ```
> delete scheduleId: <redacted>
> create job #2 (non-cancelable: true): "GC for DROP DATABASE db1 CASCADE"
>   descriptor IDs: [114 115 116 117 118 119 120 121 122 125]
> ```

nit: This is not directly related to this change but it's interesting that the database descriptor ID isn't featured in this list. Should it be? If not perhaps rename the prefix to `table descriptor IDs` or file an issue to that effect.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79024)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @postamar)

___
*[pkg/sql/schemachanger/testdata/drop, line 6420 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79024#-MzQ7KzJ31eW8Irs6NLh:-MzQWvjg78imF5xeOerI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9674980d44e32f84ccb50273a7c5db67fa8a6521/pkg/sql/schemachanger/testdata/drop#L6420)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

nit: This is not directly related to this change but it's interesting that the database descriptor ID isn't featured in this list. Should it be? If not perhaps rename the prefix to `table descriptor IDs` or file an issue to that effect.
</blockquote></details>

Done.

**Pull request merged**
