### PR TITLE
distsql: blacklist CURRENT_SCHEMA

### PR DESCRIPTION
**Pull request by RaduBerinde**
Blacklist builtins that use `EvalContext.Planner`.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Note: I don't think this deserves a release note because even though it was technically a bug, I don't see anybody using `CURRENT_SCHEMA(S)` inside a non-trivial query.

<a href="https://imgflip.com/i/2azt58"></a>

**Comment by jordanlewis** [comment]
LGTM!

**Comment by knz** [comment]
wait a second

you've changed both `current_schemas` and `current_schema`. I believe this is incorrect. Also only one has a logic test.

bors cancel

**Comment by RaduBerinde** [comment]
Both need to be blacklisted, I thought that was obvious.

**Pull request merged**
