### PR TITLE
sql: remove version gate in auth-session login

### PR DESCRIPTION
**Pull request by DarrylWong**
This was used to check if the user_id field added
in v23.1 is present. Since v23.1 is no longer supported, we can remove this check.

Epic: none
Fixes: none
Release note: none

### CODE REVIEW

**Comment by DarrylWong** [comment]
Tested by reenabling secure mode on the `rebalance/by-load/replicas/mixed-version` roachtest and setting the min version to `23.2`.

On master, auth will always fail on `23.2` because it doesn't query for `user_id`. On this branch it works fine.

**Review by rimadeodhar — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122468)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong)

___
*[`pkg/cli/auth.go` line 153 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122468#-NvciWgR-I7XW6SuQ3Ld:-NvciWgR-I7XW6SuQ3Le:btng8zb) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7ea773a6d0975a214b74b4333a5ab671155a167/pkg/cli/auth.go#L153)):*
> ```Go
> 
> 		var ok bool
> 		id, ok = row[0].(int64)
> ```

Nit: Could we remove the `var id int` and `var ok bool` declarations above and make this `id, ok := row[0].(int64)`?

**Comment by DarrylWong** [comment]
We need to return `id` and the assignment happens inside `ExecTxn`, so I think we need to keep the declaration outside of that? Let me know if I'm missing something though 😄

**Comment by rimadeodhar** [comment]
Aah, gotcha. Makes sense.

**Comment by DarrylWong** [comment]
TFTR!

bors r=rimadeodhar

**Pull request merged**
