### PR TITLE
util/queue: add generic queue implementation

### PR DESCRIPTION
**Pull request by jayshrivastava**
This change adds a queue implementation. This queue is implemented as a linked list.
This linked list uses chunking to amortize the overhead of linked list
elements.

This implementation is partially copied from `pkg/ccl/changefeedccl/kvevent/chunked_event_queue.go`.
A TODO is left to migrate that queue to use the generic implementation. Tests are copied
as well. The original implementation has been around for over 1 year and has been tested
at high scales (millions of elements, throughput of 100k items / sec, handling 100s of MBs
of data flowing through). The implementation is efficient in terms of memory and CPU usage.

The purpose of this change is to introduce a datastructure which scales and resizes
efficiently specifically for https://github.com/cockroachdb/cockroach/pull/109667. There is no existing implementation which does
so except for `chunked_event_queue.go`. Unfortunately, that queue does not support
generic types, so this change makes it generic.

Release note: None
Epic: None

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119643)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava and @rharding6373)

___
*[`pkg/util/queue/queue.go` line 19 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119643#-NrbvX06D-g-D_moRn__:-NrbvX06D-g-D_moRn_a:bvf7s0w) ([raw file](https://github.com/cockroachdb/cockroach/blob/519b4c1e50a2e27f4d091bd668f5b2d919053259/pkg/util/queue/queue.go#L19)):*
> ```Go
> 	head, tail *queueChunk[T]
> 
> 	pool *syncutil.Pool[*queueChunk[T]]
> ```

Drive by comment: making the `sync.Pool` a member of the struct is generally an anti-pattern as there is per-`sync.Pool` overhead in the implementation of pools. Are you sure you need a pool to recycle the chunks? Are you churning through the chunks that quickly? If this is necessary for performance, there should really be a benchmark that demonstrates the improvement. 
___
*[`pkg/util/queue/queue.go` line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119643#-Nrbw2Ej9skIi6vSKtij:-Nrbw2Ej9skIi6vSKtik:b-h6r8gl) ([raw file](https://github.com/cockroachdb/cockroach/blob/519b4c1e50a2e27f4d091bd668f5b2d919053259/pkg/util/queue/queue.go#L65)):*
> ```Go
> func (q *Queue[T]) Dequeue() (e T, ok bool) {
> 	if q.head == nil {
> 		return q.missing, false
> ```

You can `return e, false` here and then you don't need the `q.missing` field.

**Review by jayshrivastava — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119643)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @petermattis and @rharding6373)

___
*[`pkg/util/queue/queue.go` line 19 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119643#-NrbvX06D-g-D_moRn__:-Nret6TS0UlO1xvkrOat:b-quf07m) ([raw file](https://github.com/cockroachdb/cockroach/blob/519b4c1e50a2e27f4d091bd668f5b2d919053259/pkg/util/queue/queue.go#L19)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Drive by comment: making the `sync.Pool` a member of the struct is generally an anti-pattern as there is per-`sync.Pool` overhead in the implementation of pools. Are you sure you need a pool to recycle the chunks? Are you churning through the chunks that quickly? If this is necessary for performance, there should really be a benchmark that demonstrates the improvement.
</blockquote></details>

I agree that it's an anti pattern. If we want to use pools here, maybe getting the caller to pass in an allocator is better. 

The reason I included it is because we used one to buffer changefeed events, which is a similar use case to these rangefeed events. That being said, the initial design had a pool with no chunking, then we added chunking on afterwards. We never showed that the pool was necessary after chunking.

I think I'll drop the pool for now and revisit it when benchmark later. 
___
*[`pkg/util/queue/queue.go` line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119643#-Nrbw2Ej9skIi6vSKtij:-Nret51H-4Wl47rCRE84:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/519b4c1e50a2e27f4d091bd668f5b2d919053259/pkg/util/queue/queue.go#L65)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

You can `return e, false` here and then you don't need the `q.missing` field.
</blockquote></details>

Done.

**Review by rharding6373 — APPROVED** [review]
:lgtm: Nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119643#-:-Nrl-IpT5XCkwLlUw3HG:bcmw7ss)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @jayshrivastava and @petermattis)

___
*[`pkg/ccl/changefeedccl/kvevent/chunked_event_queue.go` line 16 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/119643#-Nrl-W0D0vv6jtJyCKyG:-Nrl-W0D0vv6jtJyCKyH:bzfn1ue) ([raw file](https://github.com/cockroachdb/cockroach/blob/e01f0138547cce5e72193924e5ce309e5282dedd/pkg/ccl/changefeedccl/kvevent/chunked_event_queue.go#L16)):*
> ```Go
> 
> // bufferEventChunkQueue is a queue implemented as a linked-list of bufferEntry.
> // TODO: This data structure should use `util/queue.Queue`.
> ```

nit: can you add an issue # here so this cleanup/refactoring can be tracked?
___
*[`pkg/util/queue/queue_test.go` line 24 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/119643#-Nrgb4hQ12cWU8tedo2P:-Nrgb4hQ12cWU8tedo2Q:b-z459xw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e01f0138547cce5e72193924e5ce309e5282dedd/pkg/util/queue/queue_test.go#L24)):*
> ```Go
> 
> func TestQueue(t *testing.T) {
> 	rand, _ := randutil.NewTestRand()
> ```

minor nit: rename `rand` to `rng` or something else to avoid name collision with the math/rand package -- nit because this avoids confusion reading the code, not because there's a collision in the technical sense.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119643)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @jayshrivastava and @rharding6373)

___
*[`pkg/util/queue/queue.go` line 47 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/119643#-Nrl7a9A16R3CmQdCgkn:-Nrl7a9A16R3CmQdCgko:b-3ad9fz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e01f0138547cce5e72193924e5ce309e5282dedd/pkg/util/queue/queue.go#L47)):*
> ```Go
> 	head, tail *queueChunk[T]
> 
> 	config *config
> ```

Do you need to hold configuration in a `config` structure? Doing so implies a memory allocation. There is only a single member here (`chunkSize`) which you could pull out into the `Queue[T]` struct. The overall size of the struct will be the same (8-bytes for the `*config` pointer or `8-bytes` for the `chunkSize` integer), but one less allocation.
___
*[`pkg/util/queue/queue.go` line 52 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/119643#-Nrl7TBmBA3M2wjZJ-mM:-Nrl7TBmBA3M2wjZJ-mN:b-h753ez) ([raw file](https://github.com/cockroachdb/cockroach/blob/e01f0138547cce5e72193924e5ce309e5282dedd/pkg/util/queue/queue.go#L52)):*
> ```Go
> // NewQueue returns a Queue of T.
> func NewQueue[T any](opts ...Option) (*Queue[T], error) {
> 	cfg := defaultConfig()
> ```

Nit: I can imagine a function named `defaultConfig()` as returning a singleton. Consider renaming to `newDefaultConfig`.
___
*[`pkg/util/queue/queue.go` line 59 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/119643#-Nrl7PuVCk3EOsXPYExN:-Nrl7PuVCk3EOsXPYExO:bgeojsw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e01f0138547cce5e72193924e5ce309e5282dedd/pkg/util/queue/queue.go#L59)):*
> ```Go
> 	}
> 	return &Queue[T]{
> 		config: defaultConfig(),
> ```

Shouldn't this be `config: cfg`? Given that no tests were failing here I suspect that you need an additional test as well.
___
*[`pkg/util/queue/queue.go` line 75 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/119643#-Nrl8bx2A5X60DGVey05:-Nrl8bx2A5X60DGVey06:b-bclkrf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e01f0138547cce5e72193924e5ce309e5282dedd/pkg/util/queue/queue.go#L75)):*
> ```Go
> 		chunk := newQueueChunk[T](q.config.chunkSize)
> 		q.tail.next = chunk
> 		q.tail = chunk
> ```

The linked list manipulation is complex enough that I'm not sure it is all correct. Not sure what can be done about that. 
___
*[`pkg/util/queue/queue.go` line 82 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/119643#-Nrl9Ih65rHyE17KeK-7:-Nrl9Ih73d2CaCfwJGhu:br0j0ap) ([raw file](https://github.com/cockroachdb/cockroach/blob/e01f0138547cce5e72193924e5ce309e5282dedd/pkg/util/queue/queue.go#L82)):*
> ```Go
> // Empty returns true IFF the Queue is empty.
> func (q *Queue[T]) Empty() bool {
> 	return q.head == nil || q.head.empty()
> ```

Is there ever a scenario where the head is empty, but a subsequent chunk is not? Feels like there is an invariant that can be enforced here and checked in tests. The way I often do that in data structures is to add a `checkInvariants` method that checks the invariants and panics if any are violated. You can then sprinkle `checkInvariants` calls in your test.
___
*[`pkg/util/queue/queue.go` line 100 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/119643#-Nrl8tji-jlJRXYXHje_:-Nrl8tji-jlJRXYXHjea:bm5la2z) ([raw file](https://github.com/cockroachdb/cockroach/blob/e01f0138547cce5e72193924e5ce309e5282dedd/pkg/util/queue/queue.go#L100)):*
> ```Go
> 		// NB: The previous value of q.head will be garbage collected.
> 		if !ok {
> 			return q.Dequeue()
> ```

Does Go support the tail call optimization? I would have structured this method as a loop which iterates until `q.head` is empty, returning as soon as it finds a value.

**Review by jayshrivastava — COMMENTED** [review]
TYFR Rachael!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119643#-:-NsiGXQi-am2NqIeL8nM:b2ma6jb)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @petermattis and @rharding6373)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/119643#-NsiH_yY6RX4hSmBwTVo:-NsiH_yY6RX4hSmBwTVp:b-u5zsuk) (no related file):*
Ty for reviewing @petermattis!

___
___
*[`pkg/util/queue/queue.go` line 47 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/119643#-Nrl7a9A16R3CmQdCgkn:-NsiHBpQ66ZNRPIIrW14:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e01f0138547cce5e72193924e5ce309e5282dedd/pkg/util/queue/queue.go#L47)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Do you need to hold configuration in a `config` structure? Doing so implies a memory allocation. There is only a single member here (`chunkSize`) which you could pull out into the `Queue[T]` struct. The overall size of the struct will be the same (8-bytes for the `*config` pointer or `8-bytes` for the `chunkSize` integer), but one less allocation.
</blockquote></details>

Done.
___
*[`pkg/util/queue/queue.go` line 59 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/119643#-Nrl7PuVCk3EOsXPYExN:-NsiHD7kAf44aQtif5Sm:b-7gclag) ([raw file](https://github.com/cockroachdb/cockroach/blob/e01f0138547cce5e72193924e5ce309e5282dedd/pkg/util/queue/queue.go#L59)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Shouldn't this be `config: cfg`? Given that no tests were failing here I suspect that you need an additional test as well.
</blockquote></details>

Added a test.
___
*[`pkg/util/queue/queue.go` line 82 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/119643#-Nrl9Ih65rHyE17KeK-7:-NsiHJRy9H6EU9i4I2s5:b-2phljq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e01f0138547cce5e72193924e5ce309e5282dedd/pkg/util/queue/queue.go#L82)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is there ever a scenario where the head is empty, but a subsequent chunk is not? Feels like there is an invariant that can be enforced here and checked in tests. The way I often do that in data structures is to add a `checkInvariants` method that checks the invariants and panics if any are violated. You can then sprinkle `checkInvariants` calls in your test.
</blockquote></details>

Good idea. I added invariant checking. 
___
*[`pkg/util/queue/queue.go` line 100 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/119643#-Nrl8tji-jlJRXYXHje_:-NsiHQVp1MM8eQmOGvjz:b2f0qgb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e01f0138547cce5e72193924e5ce309e5282dedd/pkg/util/queue/queue.go#L100)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Does Go support the tail call optimization? I would have structured this method as a loop which iterates until `q.head` is empty, returning as soon as it finds a value.
</blockquote></details>

It does not support tail optimization. However, we expect the subsequent chunk to either be nil or non-empty. I added this in the invariant check.

**Review by petermattis — APPROVED** [review]
:lgtm: modulo a minor comment in `queueChunk.pop()`. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119643#-:-Nss7tVzBbw9pOIaw8fB:b-g77gm1)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @jayshrivastava and @rharding6373)

___
*[`pkg/util/queue/queue.go` line 136 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/119643#-Nss766y0h1WmhEcjblq:-Nss766y0h1WmhEcjblr:b-nm8r54) ([raw file](https://github.com/cockroachdb/cockroach/blob/f16d5327bcf20f8384d4715f042512abb04cd076/pkg/util/queue/queue.go#L136)):*
> ```Go
> 
> func (c *queueChunk[T]) pop() (e T, ok bool, consumedAll bool) {
> 	if c.head == len(c.events) {
> ```

AFAICT, this should never be true as you remove a chunk in `Dequeue` whenever this condition occurs after successfully popping. I think you have an invariant that a chunk with `c.head == len(c.events)` never occurs in the list. (If this is true, `checkInvariants` should check for this). Am I missing something?
___
*[`pkg/util/queue/queue.go` line 146 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/119643#-Nss7UVd5DWT2P_J_5GR:-Nss7UVd5DWT2P_J_5GS:bb1mwjt) ([raw file](https://github.com/cockroachdb/cockroach/blob/f16d5327bcf20f8384d4715f042512abb04cd076/pkg/util/queue/queue.go#L146)):*
> ```Go
> 	e = c.events[c.head]
> 	c.head++
> 	return e, true, c.head == len(c.events)
> ```

I find the `consumedAll` return value a bit unusual from this function. I would have written `Dequeue` so that if it successfully pops an item we check to see if the chunk now how `c.head == len(c.events)` and remove it from the queue, encapsulating that check in a `queueChunk.finished()` method.

**Review by jayshrivastava — COMMENTED** [review]
Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119643#-:-NssCA3XCG9Leuv26H1k:b-ucfknh)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @petermattis and @rharding6373)

___
*[`pkg/util/queue/queue.go` line 136 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/119643#-Nss766y0h1WmhEcjblq:-NssApRNBnLkbYoyP-9h:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f16d5327bcf20f8384d4715f042512abb04cd076/pkg/util/queue/queue.go#L136)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

AFAICT, this should never be true as you remove a chunk in `Dequeue` whenever this condition occurs after successfully popping. I think you have an invariant that a chunk with `c.head == len(c.events)` never occurs in the list. (If this is true, `checkInvariants` should check for this). Am I missing something?
</blockquote></details>

Done.
___
*[`pkg/util/queue/queue.go` line 146 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/119643#-Nss7UVd5DWT2P_J_5GR:-NssAphr-s-khcBgzJux:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f16d5327bcf20f8384d4715f042512abb04cd076/pkg/util/queue/queue.go#L146)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I find the `consumedAll` return value a bit unusual from this function. I would have written `Dequeue` so that if it successfully pops an item we check to see if the chunk now how `c.head == len(c.events)` and remove it from the queue, encapsulating that check in a `queueChunk.finished()` method.
</blockquote></details>

Done.

**Review by rharding6373 — APPROVED** [review]
Thanks for all the hard work on this!

**Pull request merged**
