### PR TITLE
kvserver: exclude lease transfer targets with a send queue 

### LINKED ISSUE #128028: allocator: exclude lease transfer targets with a send queue
The allocator will transfer leases to replicas which are considered valid. A replica may be considered invalid if its store hasn't heart beated liveness recently enough, may require a snapshot or is otherwise unhealthy.

Extend the valid checks to also exclude replicas which currently have a send queue from transfer consideration.

See prototype commit adding this functionality https://github.com/cockroachdb/cockroach/pull/124484/commits/6b7b6f781fe5693cb2129b0e50235ec48d8673d7

Jira issue: CRDB-40761

Epic CRDB-37515

### PR DESCRIPTION
**Pull request by kvoli**
First commit from #131504.

---

Add a new method to the `RangeController`,
`SendStreamStatsRaftMuLocked()`, which returns a map of
replica IDs -> replica send stream stats:

```
// ReplicaSendStreamStats contains the stats for a replica send stream that may
// be used to inform placement decisions pertaining to the replica.
type ReplicaSendStreamStats struct {
	// Closed is true iff the send stream is closed.
	Closed bool
	// SendQueueSizeBytes is the size of the send queue entries in bytes. This
	// roughly represents the amount of data that is buffered in the send queue,
	// waiting for available tokens before being sent. A large value here may
	// indicate that the replica's store is not able to keep up with the rate of
	// incoming replication.
	SendQueueSizeBytes int64
}
```

This method can be used to determine appropriate lease transfer targets.

---

Previously, it was possible to transfer a lease to a replica which had a
raft send queue, likely unable to keep up once acquiring the lease.

As a result, the leaseholder would throttle incoming replication traffic
before evaluation because it waited in the store work queue, or for
elastic work, waited for available flow tokens.

Using the new `RangeController` method exposing information about
replicas' send queue, `SendStreamStats()`, exclude voter candidates as
lease transfer targets if:

```
HasSendQueue is true OR
IsStateReplicate is false
```

Resolves: https://github.com/cockroachdb/cockroach/issues/128028
Release note: None

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1, 1 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131457)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 140 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131457#-O7nrT4w2VNCJec8hSWo:-O7nrT4w2VNCJec8hSWp:b-cskxv1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3f95ca8619859a67ecead47afcb6883ed3b0f5d/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L140)):*
> ```Go
> // be used to inform placement decisions pertaining to the replica.
> type ReplicaSendStreamStats struct {
> 	// Closed is true iff the send stream is closed.
> ```

- I don't think we should transfer to replicas in StateProbe, i.e., we should exclude probeRecentlyNoSendQ too.
- Consider renaming this to something more semantically meaningful since "closed" is an implementation detail. For example, we could call it `InStateReplicate`.
- And we should also say that `SendQueueSizeBytes` is only populated when `InStateReplicate`.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 830 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131457#-O7nstpt0LAvKGdrk3nz:-O7nstpt0LAvKGdrk3o-:bntoypg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3f95ca8619859a67ecead47afcb6883ed3b0f5d/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L830)):*
> ```Go
> 
> func (rc *rangeController) SendStreamStatsRaftMuLocked() RangeSendStreamStats {
> 	stats := RangeSendStreamStats{}
> ```

How often will this be called? Can we afford to allocate a map each time, or should we have the caller pass in an in-out map parameter?
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 408 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131457#-O7ns1rc7jQJRjHuLvoH:-O7ns1rc7jQJRjHuLvoI:b6r9dco) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3f95ca8619859a67ecead47afcb6883ed3b0f5d/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L408)):*
> ```Go
> 	//
> 	// raftMu is held.
> 	SendStreamStatsRaftMuLocked() rac2.RangeSendStreamStats
> ```

Can we actually afford to acquire raftMu when calling this from the allocator? Blocking the allocator on IO doesn't seem right.

We already have the necessary state in `voterStateForWaiters.{isStateReplicate,hasSendQ}` which is protected by `rangeController.mu`. How about just grabbing it from there.

**Review by kvoli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131457)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 140 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131457#-O7nrT4w2VNCJec8hSWo:-O83y8JWB50gAmODNGCZ:b7bywhq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3f95ca8619859a67ecead47afcb6883ed3b0f5d/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L140)):*
> I don't think we should transfer to replicas in StateProbe, i.e., we should exclude probeRecentlyNoSendQ too.

We wouldn't transfer to them anyway, we exclude them earlier in the allocator.

> Consider renaming this to something more semantically meaningful since "closed" is an implementation detail. For example, we could call it `InStateReplicate`.

Updated to `InStateReplicate`.

> Consider renaming this to something more semantically meaningful since "closed" is an implementation detail. For example, we could call it `InStateReplicate`.

Done.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 830 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131457#-O7nstpt0LAvKGdrk3nz:-O83p0-TB5QjJnWny8fj:b2acct1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3f95ca8619859a67ecead47afcb6883ed3b0f5d/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L830)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

How often will this be called? Can we afford to allocate a map each time, or should we have the caller pass in an in-out map parameter?
</blockquote></details>

This will be called once per-range, about every 10 minutes in the normal case. If the range is hot, then more like once every minute.

Across all ranges though, worst case 10 times a second, per store.

I started on putting through an in-out map, then realized its not going to work very cleanly because we'd need to maintain it on the replica, or in the processor. There's no guarantees that we wouldn't have multiple calls to `SendStreamStats` in quick succession, where the map would be cleared while still in use -- there's some guarantees with https://github.com/cockroachdb/cockroach/pull/119410, but its not going to cover the cases where its an external command like `RELOCATE`.

I left as is. If we think the rates I mentioned above are problematic for GC, we could 

1. change the method to take in a replicaID and iter over the voter sets to find the replica and return the info, at the cost of more calls and mutex acquisitions OR
2. provide some form isolation on the map we are passing around, like refcounting and re-creating it if there's still a ref.


wdyt?
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go` line 408 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131457#-O7ns1rc7jQJRjHuLvoH:-O83yOQw0nsYmT60hmzW:b-7h295t) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3f95ca8619859a67ecead47afcb6883ed3b0f5d/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go#L408)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can we actually afford to acquire raftMu when calling this from the allocator? Blocking the allocator on IO doesn't seem right.

We already have the necessary state in `voterStateForWaiters.{isStateReplicate,hasSendQ}` which is protected by `rangeController.mu`. How about just grabbing it from there.
</blockquote></details>

We probably can but its not something we want. Updated to use the voter state for waiters and acquire `rangeController.mu` instead. This meant that `SendQueueBytes` changes to `HasSendQueue` instead here, which is a little unfortunate because it reduces the fidelity, but we aren't doing anything fancy here so there's no loss atm.

In the future, if we decide shedding is required, we will need to figure out a low cost way to get more information, like the `SendQueueBytes`.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 6 of 6 files at r4, 11 of 11 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131457#-:-O84LyPODdNMqv3SNCvb:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`-- commits` line 39 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/131457#-O84IOsb40AzCTeOj0Hb):*
nit: stale commit message
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 830 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131457#-O7nstpt0LAvKGdrk3nz:-O84J55KCFCNdCuaOKay:b-nmwa93) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3f95ca8619859a67ecead47afcb6883ed3b0f5d/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L830)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

This will be called once per-range, about every 10 minutes in the normal case. If the range is hot, then more like once every minute.

Across all ranges though, worst case 10 times a second, per store.

I started on putting through an in-out map, then realized its not going to work very cleanly because we'd need to maintain it on the replica, or in the processor. There's no guarantees that we wouldn't have multiple calls to `SendStreamStats` in quick succession, where the map would be cleared while still in use -- there's some guarantees with https://github.com/cockroachdb/cockroach/pull/119410, but its not going to cover the cases where its an external command like `RELOCATE`.

I left as is. If we think the rates I mentioned above are problematic for GC, we could 

1. change the method to take in a replicaID and iter over the voter sets to find the replica and return the info, at the cost of more calls and mutex acquisitions OR
2. provide some form isolation on the map we are passing around, like refcounting and re-creating it if there's still a ref.


wdyt?
</blockquote></details>

This is fine for now -- I was just curious. We can look into optimizations if it shows up in profiles.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 200 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/131457#-O84KKEn14any8qx08eB:-O84KKEn14any8qx08eC:b-ta3wkg) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c770aba3a7451dab499b0ea09677482edd6105a/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L200)):*
> ```Go
> 	// entries waiting on flow tokens to be sent.
> 	//
> 	// This is only populated when IsStateReplicate is true.
> ```

Given we are unconditionally setting it in `rangeController.SendStreamStats`, the "only populated" part isn't quite true. And in `voterSetForWaiters` we actually document `!isStateReplicate => hasSendQ`.

Consider rephrasing this to "Ignore this value unless IsStateReplicate is true".
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator_test.go` line 1958 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/131457#-O84LhRbB0kegqR_fUDE:-O84LhRbB0kegqR_fUDF:bd3mayd) ([raw file](https://github.com/cockroachdb/cockroach/blob/560ee92aca7102f64864c71a8ea7ee7b2947edbe/pkg/kv/kvserver/allocator/allocatorimpl/allocator_test.go#L1958)):*
> ```Go
> 			replStats.HasSendQueue = true
> 		}
> 		if _, ok := r.replsNotInStateReplicate[roachpb.ReplicaID(i)]; ok {
> ```

nit: do we need the else or could the if be
```
if _, ok ...; !ok {
  replStats.IsStateReplicate = true
}
```

**Review by kvoli — COMMENTED** [review]
TYFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131457#-:-O87NGIm17cOmbXA_Bs7:bzftgo7)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @kvoli and @sumeerbhola)

___
*[`-- commits` line 39 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/131457#-O84IOsb40AzCTeOj0Hb):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: stale commit message
</blockquote></details>

Updated.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 830 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131457#-O7nstpt0LAvKGdrk3nz:-O87MwUn5c22rhlFBfxH:bb7ohn6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3f95ca8619859a67ecead47afcb6883ed3b0f5d/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L830)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This is fine for now -- I was just curious. We can look into optimizations if it shows up in profiles.
</blockquote></details>

sgtm
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 200 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/131457#-O84KKEn14any8qx08eB:-O87MucD8R7lF6eFkq-r:b9lx5bh) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c770aba3a7451dab499b0ea09677482edd6105a/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L200)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Given we are unconditionally setting it in `rangeController.SendStreamStats`, the "only populated" part isn't quite true. And in `voterSetForWaiters` we actually document `!isStateReplicate => hasSendQ`.

Consider rephrasing this to "Ignore this value unless IsStateReplicate is true".
</blockquote></details>

Ah good idea, updated.
___
*[`pkg/kv/kvserver/allocator/allocatorimpl/allocator_test.go` line 1958 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/131457#-O84LhRbB0kegqR_fUDE:-O87NEXH1OskboGzPtge:b-6v0tjc) ([raw file](https://github.com/cockroachdb/cockroach/blob/560ee92aca7102f64864c71a8ea7ee7b2947edbe/pkg/kv/kvserver/allocator/allocatorimpl/allocator_test.go#L1958)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: do we need the else or could the if be
```
if _, ok ...; !ok {
  replStats.IsStateReplicate = true
}
```
</blockquote></details>

Can be simplified, done.

**Comment by kvoli** [comment]
Rebased to fix unrelated unit test failure.

**Comment by kvoli** [comment]
bors r=sumeerbhola

**Pull request merged**
