### PR TITLE
acceptance: add a regression test for migrations

### PR DESCRIPTION
**Pull request by andreimatei**
We used to have a bug where a 2.0-beta node couldn't come up in a 1.1
cluster if there were too many tables. This patch is a test for that.
The bug was #22370; it was a more general KV bug but migrations
triggered it.

Release note: None

### CODE REVIEW

**Comment by andreimatei** [comment]
This fails on the release-2.0 branch below the fix in https://github.com/cockroachdb/cockroach/issues/22370

**Comment by nvanbenschoten** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/acceptance/version_upgrade_test.go, line 285 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25196#-LBWuEI3CpyZSKOdHBML:-LBWuEI3CpyZSKOdHBMM:b5098t4) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7a3a81ebcf7846fd24c09d07a2c87240b464d4/pkg/acceptance/version_upgrade_test.go#L285)):*
> ```Go
> 	}
> 	for i := 0; i < 100; i++ {
> 		_, err := db.Exec(fmt.Sprintf("create table lotsatables.t%d (x int primary key)", i))
> ```

What's up with the `d` at the end of the table name?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25196#-:-LBWuJXGDwvazOIADc52:bnfp4nl)*

**Comment by andreimatei** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/acceptance/version_upgrade_test.go, line 285 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25196#-LBWuEI3CpyZSKOdHBML:-LBWucAC2FYZ3CroCf84:bs84j4j) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7a3a81ebcf7846fd24c09d07a2c87240b464d4/pkg/acceptance/version_upgrade_test.go#L285)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What's up with the `d` at the end of the table name?
</blockquote></details>

it's `Sprintf("%d", i)`

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25196)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/acceptance/version_upgrade_test.go, line 285 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25196#-LBWuEI3CpyZSKOdHBML:-LBWyuVu8LYbexGHv4gX:bplfi6m) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e7a3a81ebcf7846fd24c09d07a2c87240b464d4/pkg/acceptance/version_upgrade_test.go#L285)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

it's `Sprintf("%d", i)`
</blockquote></details>

Heh.. yeah you're right. Carry on.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25196)*

**Pull request merged**
