### PR TITLE
sql/json: support < and <= for JSON datums

### LINKED ISSUE #43123: sql: implement json compare
While working on sqlsmith, we discovered that the json type doesn't implement the < and <= (and > and >=) operators. There's a json.Compare method, so I went ahead and just added it to the list, assuming that it had been merely forgotten. I wrote a test to generate some json stuff and compare them, and ran it against postgres. The results differed, and should probably be fixed before we add this feature to postgres.

```
WITH
	t (c)
		AS (
			VALUES
				('1'::JSONB),
				('true'::JSONB),
				('[]'::JSONB),
				('{}'::JSONB)
		)
SELECT
	a.c, b.c, a.c < b.c, a.c <= b.c
FROM
	t AS a, t AS b
ORDER BY
	a.c, b.c;
```

cockroach:
```
   c   |  c   | ?column? | ?column?  
+------+------+----------+----------+
     1 |    1 |  false   |   true    
     1 | []   |   true   |   true    
     1 | true |   true   |   true    
     1 | {}   |   true   |   true    
  []   |    1 |  false   |  false    
  []   | []   |  false   |   true    
  []   | true |  false   |  false    
  []   | {}   |   true   |   true    
  true |    1 |  false   |  false    
  true | []   |   true   |   true    
  true | true |  false   |   true    
  true | {}   |   true   |   true    
  {}   |    1 |  false   |  false    
  {}   | []   |  false   |  false    
  {}   | true |  false   |  false    
  {}   | {}   |  false   |   true  
```

postgres:
```
  c   |  c   | ?column? | ?column? 
------+------+----------+----------
 []   | []   | f        | t
 []   | {}   | t        | t
 []   | 1    | t        | t
 []   | true | t        | t
 {}   | []   | f        | f
 {}   | {}   | f        | t
 {}   | 1    | f        | f
 {}   | true | f        | f
 1    | []   | f        | f
 1    | {}   | t        | t
 1    | 1    | f        | t
 1    | true | t        | t
 true | []   | f        | f
 true | {}   | t        | t
 true | 1    | f        | f
 true | true | f        | t
```

Although the orders differ here (which is weird?), the output also differs. Take the `1, []` case, where postgres says `false, false` and cockroach says `true, true`.

Jira issue: CRDB-5297

### PR DESCRIPTION
**Pull request by madelynnblue**
Improve Postgres compatibility by teaching JSON how to compare exactly
like Postgres. Two large changes happened to make this happen.

First, arrays were special cased during type comparison since empty
arrays in Postgres compare less than other things, even JSON null.

Second, JSON objects had their ordering changed to match Postgres. This
means that the object encoding ordering changed for some objects. The
DecodeJSON method was taught how to properly sort on-disk data to cope
with old encodings.

This commit does not change anything about disallowing JSON in ORDER
BY or its usability in indexes. However this is important progress to
support those use cases.

Fixes #43123

Release note (sql change): the JSON type now supports inequality
comparisons (<, <=, etc.)

### CODE REVIEW

**Comment by mjibson** [comment]
For whoever reviews this: what ways can this break? For example, I'm currently worried about a situation where a mixed-version cluster with this new code and some old version are running. Say a query gets issued with the new code as the gateway (and thus it supports JSON <). But let's say distsql schedules a processor on an old node that doesn't know about JSON <. Will that blow up the cluster?

Can this break if a new node gets a json object from disk (and thus sorts it with this new sort) and then serializes that object, sends it to an old node for distsql processing. The old node has some other json bytes (and thus sorted in a different manner), and compares them for equality, which fails since the exact ordering of fields doesn't match up, and the old (and new) json code assumes objects are correctly sorted.

Any other scenarios? Because of this I'm very hesitant to merge this until these questions are resolved.

**Comment by rohany** [comment]
I think that something will go wrong in that case -- I don't know if the old node will panic or just error at the unsupported comparison operation (should be relatively simple to test though). Your other concern seems pretty likely.

It feels to me that you need some sort of version gate on this, but I don't know where to put it. I'm also wondering how this has been done in the past with introduction of new types / updating operations on existing types.

**Comment by yuzefovich** [comment]
There is already `DistSQLVersion` in place (it's in `pkg/sql/execinfra/server_config.go:61`). Basically you'll bump it up (as well as `MinAcceptedVersion`), and everything should just work :)

**Review by otan — COMMENTED** [review]
> For whoever reviews this: what ways can this break?
> Can this break if a new node gets a json object from disk

So the only case I can think of this breaking that hasn't been touched is key encoding.
But I noticed it's not supported:
```
root@127.0.0.1:49698/defaultdb> create table a2 (j jsonb primary key);
ERROR: unimplemented: column j is of type jsonb and thus is not indexable
SQLSTATE: 0A000
HINT: You have attempted to use a feature that is not yet implemented.
See: https://github.com/cockroachdb/cockroach/issues/35730
```

So I think the only problem is in a mixed version cluster, the results read by different versioned nodes may present a different order as we `Decode` differently. Is that a problem?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43832#-:-LyBuL1S4OoCs-cTu2V2:b-1flnil)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mjibson and @otan)

___
*[pkg/sql/logictest/testdata/logic_test/json, line 723 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43832#-LyBtoCY7knmn-8xwrPw:-LyBtoCY7knmn-8xwrPx:bg9ico5) ([raw file](https://github.com/cockroachdb/cockroach/blob/094304cd914cc5d3f85d25a378c67c5072e053dc/pkg/sql/logictest/testdata/logic_test/json#L723)):*
> ```
> DROP TABLE json_family
> 
> # See #43123
> ```

maybe worth subtesting, e.g. `subtest regression_43123_json_sorting`?
___
*[pkg/util/json/json.go, line 400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43832#-LyBtZn8AyN7UD49CLxF:-LyBtZn8AyN7UD49CLxG:bi0g6fz) ([raw file](https://github.com/cockroachdb/cockroach/blob/094304cd914cc5d3f85d25a378c67c5072e053dc/pkg/util/json/json.go#L400)):*
> ```Go
> 
> 	// Zero-length arrays are special. They sort before everything, even
> 	// JSON null.
> ```

Can you point at the docs for this from postgres' side? If not documented, strange!

**Comment by otan** [comment]
___
*[pkg/sql/logictest/testdata/logic_test/json, line 746 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43832#-LyEsCB-CFzm0AgXYlaS:-LyEsCB-CFzm0AgXYlaT:b-jqehj5) ([raw file](https://github.com/cockroachdb/cockroach/blob/094304cd914cc5d3f85d25a378c67c5072e053dc/pkg/sql/logictest/testdata/logic_test/json#L746)):*
> ```
>                 ('{"b": 2}'::JSONB),
>                 ('{"bb": "dd"}'::JSONB),
>                 ('{"c": "e"}'::JSONB),
> ```

is there value in adding a more recursive json structure in here?

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43832)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/logictest/testdata/logic_test/json, line 723 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43832#-LyBtoCY7knmn-8xwrPw:-LyVEYQcD9gv3AOwur1i:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/094304cd914cc5d3f85d25a378c67c5072e053dc/pkg/sql/logictest/testdata/logic_test/json#L723)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

maybe worth subtesting, e.g. `subtest regression_43123_json_sorting`?
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/json, line 746 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43832#-LyEsCB-CFzm0AgXYlaS:-LyVXnQ21otxZb4frlAm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/094304cd914cc5d3f85d25a378c67c5072e053dc/pkg/sql/logictest/testdata/logic_test/json#L746)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

is there value in adding a more recursive json structure in here?
</blockquote></details>

Done.
___
*[pkg/util/json/json.go, line 400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43832#-LyBtZn8AyN7UD49CLxF:-LyWFwK9EP4ao2PaQQMF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/094304cd914cc5d3f85d25a378c67c5072e053dc/pkg/util/json/json.go#L400)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

Can you point at the docs for this from postgres' side? If not documented, strange!
</blockquote></details>

Done.

**Comment by mjibson** [comment]
Current status: I'm going to leave this PR unmerged until the following issues are fixed.

- It's not passing a json_build_object test. The test is correct (expected matches postgres), but the implementation is broken.
- Need to bump the distsql api version and set the new minimum to it. Make sure the distsql team is ok with bumping the minimum as it means in a mixed node cluster nodes of different versions will not be able to schedule work on the other nodes, which could be bad for customers load.

I'm fast approaching my paternity leave and have already spent more time on this than I've allotted myself and need to work on other things before I leave. I may or may not have time to return to this and fix things. I recommend ignoring this work until a PM decides we should start working on JSON again.

**Comment by knz** [comment]
Discussed offline: instead of changing the existing encoding for JSON, we could add a _separate_ encoding using a separate coltype in descriptors.

Then "old data" continues to use the old encoding (and cannot be indexed) and new data use the new type/encoding and can be indexed.

This way the behavior in mixed version is clear and users can control when they migrate from one column type to the next.

**Comment by otan** [comment]
I think where this doesn't work well is backup and restores. Namely if we change the type, we probably have to rename it on the backups too and makes it difficult to restore, especially on older versions.

**Comment by bobvawter** [comment]
[CLA assistant check](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=43832) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=43832) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.crdb.dev/check/cockroachdb/cockroach?pullRequest=43832) it.</sub>

**Pull request closed without merging**
