### PR TITLE
vendor: update pgx and pgconn for kerberos support

### PR DESCRIPTION
**Pull request by rafiss**
This doesn't use the krb5 support yet.

Release note: None

### CODE REVIEW

**Review by otan — COMMENTED** [review]
unfortunately i done goof'd and you'll need #110 as well, which isn't released yet AFAICT

**Comment by rafiss** [comment]
i have this pointing at the commit we want in go.mod: `github.com/jackc/pgconn v1.12.1-0.20220426135424-84e8238fa074`

**Review by otan — APPROVED** [review]
ah! well make sure you push the `vendor` repo too :')!

**Comment by rafiss** [comment]
tftr!

bors r=otan

**Pull request merged**
