### PR TITLE
sql: Add pg_type table to pg_catalog

### LINKED ISSUE #10072: sql: Implement pg_catalog.pg_type as a virtual table
See https://www.postgresql.org/docs/9.6/static/catalog-pg-type.html.

### PR DESCRIPTION
**Pull request by nvb**
Fixes #10072.

The `pg_type` table stores information about data types.

cc. @jordanlewis

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10209)

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Reassigning because @cuongdo is production monkey for the week.

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/pg_catalog.go, line 678 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10209#-KUxgubtEzEcBKnphdJs:-KUxeE7Lm-i7yuU89XEo:b-efs908) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cf72ffd974e4b548e455fcbeefbfde69b3914b2/pkg/sql/pg_catalog.go#L678)):*
> ```Go
> 
> var (
> 	oidToDatum = map[oid.Oid]parser.Type{
> ```

I would consider putting these two vars and their methods into their own file so they are decoupled from pg_catalog since they are also used in pgwire.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10209#-:-KUxhTxdznmsOhJcUlX6:bnfp4nl)*

**Comment by nvanbenschoten** [comment]
TFTR

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/pg_catalog.go, line 678 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10209#-KUxgubtEzEcBKnphdJs:-KV1PYT2j6z8B-aBHkw5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cf72ffd974e4b548e455fcbeefbfde69b3914b2/pkg/sql/pg_catalog.go#L678)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> I would consider putting these two vars and their methods into their own file so they are decoupled from pg_catalog since they are also used in pgwire.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10209#-:-KV1PYnZKTh2uCYX3JRb:bb73zsl)*

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10209#-:-KV1cYxD8Kq1J3vO8C7C:bnfp4nl)*

**Pull request merged**
