### PR TITLE
storage: avoid node liveness increment and heartbeat pile-ons

### PR DESCRIPTION
**Pull request by spencerkimball**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12352)

### CODE REVIEW

**Comment by tamird** [comment]
What's the motivation? Did this code simply not work before? Can it be tested?

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352#-:-KYzC5JIxtBFJTb6m7MB:b-gvfm9h)*

**Comment by petermattis** [comment]
Was this the cause of the periodic liveness failures?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352#-:-KYzP7IUwHGwh-UrHI5B:b-1ji1e6)*

**Comment by spencerkimball** [comment]
@tamird: this allows an original failure, if one exists, to be accessed on an ambiguous result error.
@petermattis: not sure what the periodic liveness failures you're referring to are. This fixes a bug I was seeing where an ambiguous result ends up not returning a condition failed error, which contains the actual value of the liveness record, and so we would just keep sending the incorrect one and failing.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352#-:-KYzPFNpZXjQX8X9T6sU:bjsduj0)*

**Comment by petermattis** [comment]
:lgtm:

Haven't we seen momentary spikes in the under-replicated range metric that you suspected were caused by blips in node liveness?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352#-:-KZ-Ac1u_X2Fj2GdLAGG:bmsiscf)*

**Comment by bdarnell** [comment]
Why would we repeatedly get AmbiguousResultError? Shouldn't we eventually get an unambiguous ConditionFailedError after retrying? 

I'm concerned about the proliferation of AmbiguousResultErrors; I think they're starting to intrude on application code. When we introduced this error type, the rationale was that some ambiguity was always going to be possible because your pgwire connection could fail mid-commit. But I think AmbiguousResultError has become quite a bit more common than that and we may need to think about ways to resolve some of these situations unambiguously (for example, an in-memory cache of recently committed transactions could allow a replayed EndTransaction to succeed in at least some cases). 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/kv/dist_sender.go, line 1194 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352#-KZ02xsdVT5xRK4W326P:-KZ02xsdVT5xRK4W326Q:b-io1c30) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a9e80fa0a492b89975172e688f4e214370b2bfc/pkg/kv/dist_sender.go#L1194)):*
> ```Go
> 					if haveCommit && (pending > 0 || ambiguousResult) {
> 						return nil, errors.Wrap(
> 							call.Reply.Error.GoError(), errMayHaveSucceededAtFailingReplica.Error(),
> ```

But now the returned error is not a `*roachpb.AmbiguousResultError` so type checks for it won't match. This may change retry behaviour in some places. 

AmbiguousResultError and ConditionFailedError are both roachpb.Errors and transmit correctly across the wire. The result of errors.Wrap is not, which may not matter in this instance but is a surprising departure from our usual error-handling. Does AmbiguousResultError need to carry an embedded roachpb.Error? 

---

*[pkg/storage/node_liveness.go, line 365 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352#-KZ071ahP6FbTMPbflUx:-KZ071ahP6FbTMPbflUy:biundxp) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a9e80fa0a492b89975172e688f4e214370b2bfc/pkg/storage/node_liveness.go#L365)):*
> ```Go
> 		return txn.Run(b)
> 	}); err != nil {
> 		if cErr, ok := errors.Cause(err).(*roachpb.ConditionFailedError); ok && handleCondFailed != nil {
> ```

Instead of relying on the right error type being returned (which will always be kind of fragile and is not something that user SQL code can rely on), maybe we should restructure this as a Get followed (maybe) by a Put. Then we'd have the old value no matter what. This isn't performance-critical so we don't need to pack it into a single CPut. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352#-:-KZ03TQunOyVj041PnM1:bqealp8)*

**Comment by spencerkimball** [comment]
We do eventually stop getting the `AmbiguousResultError`, but it seems as though the condition which causes it to be returned persists for long enough that the node liveness heartbeat is missed.

I am also concerned about these problems. I think it's a raw deal that we're doing this only to suit a fairly obscure, and IMO debatable, definition of consistency.

After more investigation, I've discovered the more fundamental problem behind this. Because every range will separately try to increment epochs for a node which appears to be down, as well as heartbeat the node's own liveness when it comes back online (while getting range leases), this will cause pile-ons in a busy system, and lots of unnecessary failures.

I've pushed a change which addresses this. PTAL

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/kv/dist_sender.go, line 1194 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352#-KZ02xsdVT5xRK4W326P:-KZ3Zg9gKEt31E_pDQiL:b-i1wa40) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a9e80fa0a492b89975172e688f4e214370b2bfc/pkg/kv/dist_sender.go#L1194)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

But now the returned error is not a `*roachpb.AmbiguousResultError` so type checks for it won't match. This may change retry behaviour in some places. 

AmbiguousResultError and ConditionFailedError are both roachpb.Errors and transmit correctly across the wire. The result of errors.Wrap is not, which may not matter in this instance but is a surprising departure from our usual error-handling. Does AmbiguousResultError need to carry an embedded roachpb.Error? 
</blockquote></details>

Yeah, I've grown to consider this a not-so-great solution to the problem, so I've reverted this part of the change.

---

*[pkg/storage/node_liveness.go, line 365 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352#-KZ071ahP6FbTMPbflUx:-KZ3_r60jJvTVWVYa1N6:b-hjycq9) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a9e80fa0a492b89975172e688f4e214370b2bfc/pkg/storage/node_liveness.go#L365)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Instead of relying on the right error type being returned (which will always be kind of fragile and is not something that user SQL code can rely on), maybe we should restructure this as a Get followed (maybe) by a Put. Then we'd have the old value no matter what. This isn't performance-critical so we don't need to pack it into a single CPut. 
</blockquote></details>

I'm no longer needing to do this with the change to avoid pile ons.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352#-:-KZ3YYwQMXaF2cETSoSc:b-pfppg5)*

**Comment by bdarnell** [comment]
LGTM. So does this address #12453 too?

I think the definition of consistency that prompted the introduction of AmbiguousResultErrors is valid - the application should be able to give us a non-idempotent command and have it execute zero or one times. But we were too quick to accept ambiguous responses because some level of ambiguity is inherent in the pgwire protocol. If we had a hypothetical alternative protocol in which clients could inspect transaction results after losing their TCP connection, then we'd have more pressure to make these outcomes unambiguous. 

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/storage/node_liveness.go, line 232 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352#-KZG3nXF0yzImqN3yoVK:-KZG3nXF0yzImqN3yoVL:b219oce) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd98f2ba998f68e928cce588036cb351d51bfc5e/pkg/storage/node_liveness.go#L232)):*
> ```Go
> 	if err := nl.updateLiveness(ctx, &newLiveness, liveness, func(actual Liveness) error {
> 		// Update liveness to actual value on mismatch.
> 		defer func() {
> ```

Why is this deferred instead of being executed immediately? None of the remaining code in this function changes `actual` or refers to `nl.mu.self` (in the previous code, there were references to `newLiveness` that needed to be preserved). I don't understand the motivation for the changes here other than the new mutexes.

---

*[pkg/storage/node_liveness.go, line 257 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352#-KZG31Z2Y9_D9ll4CZ8X:-KZG31Z3lldNk7R8HMsY:bxgcxwh) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd98f2ba998f68e928cce588036cb351d51bfc5e/pkg/storage/node_liveness.go#L257)):*
> ```Go
> 	nl.mu.Lock()
> 	defer nl.mu.Unlock()
> 	nl.mu.self = newLiveness
> ```

Doesn't this just clobber the assignment now made in the `defer` above? 

---

*[pkg/storage/node_liveness.go, line 319 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352#-KZG73FTtQeRpmDpQ6zQ:-KZG73FTtQeRpmDpQ6zR:bn9ttv3) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd98f2ba998f68e928cce588036cb351d51bfc5e/pkg/storage/node_liveness.go#L319)):*
> ```Go
> // gathered through gossip, an error is returned.
> func (nl *NodeLiveness) IncrementEpoch(ctx context.Context, liveness *Liveness) error {
> 	// Allow only one increment at a time.
> ```

One globally or one per node? Maybe the `incrementMu` should be on the `Liveness` (but I'm ok with the more-limited version here too)

---

*[pkg/storage/node_liveness.go, line 394 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352#-KZG8-VWLTH8OZeRrLyy:-KZG8-VWLTH8OZeRrLyz:b-wf3cx8) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd98f2ba998f68e928cce588036cb351d51bfc5e/pkg/storage/node_liveness.go#L394)):*
> ```Go
> 			b.CPut(key, newLiveness, nil)
> 		} else {
> 			b.CPut(key, newLiveness, oldLiveness)
> ```

You've fixed the per-range factor, but it's still possible for there to be a pile-up when a node dies and every live node tries to increment its epoch. As a CPut, each of those attempts will go into the (write) command queue and raft log. It would probably be better to rewrite this as a Get followed by a Put so that only one increment goes into the raft log. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352#-:-KZFvEygKfQsiTh83D6z:b-dibezl)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/kv/transport.go, line 199 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352#-KZMYFiXhFDVBY4Larl_:-KZMYFiXhFDVBY4Larla:b-1ziyah) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd98f2ba998f68e928cce588036cb351d51bfc5e/pkg/kv/transport.go#L199)):*
> ```Go
> 	go func() {
> 		gt.opts.metrics.SentCount.Inc(1)
> 		log.VEventf(ctx, 2, "sending request to %s", addr)
> ```

Logging an event for every RPC sent is likely going to have a performance hit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352)*

**Comment by spencerkimball** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/kv/transport.go, line 199 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352#-KZMYFiXhFDVBY4Larl_:-KZMZjYhaTDyWDXyhhgm:b17kj0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd98f2ba998f68e928cce588036cb351d51bfc5e/pkg/kv/transport.go#L199)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Logging an event for every RPC sent is likely going to have a performance hit.
</blockquote></details>

This will only be a trace event, right? Is that a perf hit?

---

*[pkg/storage/node_liveness.go, line 232 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352#-KZG3nXF0yzImqN3yoVK:-KZM_ElL7aEAhEVYjH8s:bcs9xwe) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd98f2ba998f68e928cce588036cb351d51bfc5e/pkg/storage/node_liveness.go#L232)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Why is this deferred instead of being executed immediately? None of the remaining code in this function changes `actual` or refers to `nl.mu.self` (in the previous code, there were references to `newLiveness` that needed to be preserved). I don't understand the motivation for the changes here other than the new mutexes.
</blockquote></details>

Removed deferral.

---

*[pkg/storage/node_liveness.go, line 257 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352#-KZG31Z2Y9_D9ll4CZ8X:-KZM_OpptoB1TGcLe7G1:bmagigx) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd98f2ba998f68e928cce588036cb351d51bfc5e/pkg/storage/node_liveness.go#L257)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Doesn't this just clobber the assignment now made in the `defer` above? 
</blockquote></details>

No because now we return in the `if err != nil {}` block above. This code is not executed if there was a condition failed error.

---

*[pkg/storage/node_liveness.go, line 319 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352#-KZG73FTtQeRpmDpQ6zQ:-KZM_bZUgvMXoeowmrh6:blxdcis) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd98f2ba998f68e928cce588036cb351d51bfc5e/pkg/storage/node_liveness.go#L319)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

One globally or one per node? Maybe the `incrementMu` should be on the `Liveness` (but I'm ok with the more-limited version here too)
</blockquote></details>

The limited version seems to work well in practice. This is simpler so will leave as is for the time being.

---

*[pkg/storage/node_liveness.go, line 394 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352#-KZG8-VWLTH8OZeRrLyy:-KZMa10ax576DYU-uPPG:b-popv0v) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd98f2ba998f68e928cce588036cb351d51bfc5e/pkg/storage/node_liveness.go#L394)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

You've fixed the per-range factor, but it's still possible for there to be a pile-up when a node dies and every live node tries to increment its epoch. As a CPut, each of those attempts will go into the (write) command queue and raft log. It would probably be better to rewrite this as a Get followed by a Put so that only one increment goes into the raft log. 
</blockquote></details>

I was trying to avoid two round trips here. It's obviously vital for nodes to keep their liveness up-to-date. I'm worried about two round trips for widely distributed clusters (e.g. EU <-> AU).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352)*

**Comment by tamird** [comment]
Reviewed 3 of 4 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/storage/node_liveness.go, line 97 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352#-KZMjBQzec3pFw2Xh0t-:-KZMjBQzec3pFw2Xh0t0:b-u8kii9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9d0a5d4e4704afb12c6c68c40d50faee43bbdf1/pkg/storage/node_liveness.go#L97)):*
> ```Go
> 	heartbeatInterval time.Duration
> 	pauseHeartbeat    atomic.Value // contains a bool
> 	incrementMu       syncutil.Mutex
> ```

can you make these two mutexes semaphores instead? semaphore channels compose better and would allow context cancellation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/kv/transport.go, line 199 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352#-KZMYFiXhFDVBY4Larl_:-KZMnGZvOGZaY2o6lKml:b7wau2n) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd98f2ba998f68e928cce588036cb351d51bfc5e/pkg/kv/transport.go#L199)):*
<details><summary><i>Previously, spencerkimball (Spencer Kimball) wrote…</i></summary><blockquote>

This will only be a trace event, right? Is that a perf hit?
</blockquote></details>

Yes, this is only a trace event. The impact is a bit hard to estimate. Certainly including `client.args` would have been problematic, but even without that I worry. But if you found this useful during debugging let's leave it in for now. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352)*

**Comment by spencerkimball** [comment]
Review status: 3 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/storage/node_liveness.go, line 97 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352#-KZMjBQzec3pFw2Xh0t-:-KZNdMa67QGUeHMmTKDu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9d0a5d4e4704afb12c6c68c40d50faee43bbdf1/pkg/storage/node_liveness.go#L97)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

can you make these two mutexes semaphores instead? semaphore channels compose better and would allow context cancellation.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks pending.

---

*[pkg/storage/node_liveness.go, line 214 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352#-KZNee998rQdPQTV0631:-KZNee9ArhCRq4UngWQo:b-qpx8ja) ([raw file](https://github.com/cockroachdb/cockroach/blob/d29156a25099b1bf0c870235c6861ffc16042377/pkg/storage/node_liveness.go#L214)):*
> ```Go
> // successful, stores the updated liveness record in the nodes map.
> func (nl *NodeLiveness) Heartbeat(ctx context.Context, liveness *Liveness) error {
> 	// Allow only one heartbeat at a time.
> ```

might make more sense to put this on the `make(chan struct{}, 1)` call

---

*[pkg/storage/node_liveness.go, line 242 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352#-KZNf6ct0xPdjR-ab70g:-KZNf6cuQtUridDPHuXz:bs7d32r) ([raw file](https://github.com/cockroachdb/cockroach/blob/17b99047a726d5c3c4d8bf595812a27abdaf16ff/pkg/storage/node_liveness.go#L242)):*
> ```Go
> 	nl.mu.Unlock()
> 	if err != nil {
> 		nl.metrics.HeartbeatFailures.Inc(1)
> ```

can you revert this bit if the answer to my above question is "no"?

---

*[pkg/storage/node_liveness.go, line 256 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352#-KZNf8FTiXshQCLAQyih:-KZNf8FTiXshQCLAQyii:box14aq) ([raw file](https://github.com/cockroachdb/cockroach/blob/d29156a25099b1bf0c870235c6861ffc16042377/pkg/storage/node_liveness.go#L256)):*
> ```Go
> 			return nil
> 		}
> 		nl.metrics.HeartbeatFailures.Inc(1)
> ```

you want this incremented even in the case of `errNodeAlreadyAlive`?

---

*[pkg/storage/node_liveness.go, line 265 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352#-KZNfIf84kqu_ZsFuBHA:-KZNfIf84kqu_ZsFuBHB:bzafaz2) ([raw file](https://github.com/cockroachdb/cockroach/blob/d29156a25099b1bf0c870235c6861ffc16042377/pkg/storage/node_liveness.go#L265)):*
> ```Go
> 	nl.mu.Unlock()
> 	nl.metrics.HeartbeatSuccesses.Inc(1)
> 	return nil
> ```

this should return err - bad conflict resolution?

---

*[pkg/storage/node_liveness.go, line 324 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352#-KZNemfMqping_5vB7OY:-KZNemfMqping_5vB7OZ:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/d29156a25099b1bf0c870235c6861ffc16042377/pkg/storage/node_liveness.go#L324)):*
> ```Go
> // gathered through gossip, an error is returned.
> func (nl *NodeLiveness) IncrementEpoch(ctx context.Context, liveness *Liveness) error {
> 	// Allow only one increment at a time.
> ```

ditto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352)*

**Comment by spencerkimball** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

*[pkg/storage/node_liveness.go, line 242 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352#-KZNf6ct0xPdjR-ab70g:-KZNjaDsCm5RNHPb2RAU:b-4obfha) ([raw file](https://github.com/cockroachdb/cockroach/blob/17b99047a726d5c3c4d8bf595812a27abdaf16ff/pkg/storage/node_liveness.go#L242)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

can you revert this bit if the answer to my above question is "no"?
</blockquote></details>

I think you're misreading the code.

---

*[pkg/storage/node_liveness.go, line 256 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352#-KZNf8FTiXshQCLAQyih:-KZNjNIg4bARCIQcn46Q:bl632dd) ([raw file](https://github.com/cockroachdb/cockroach/blob/d29156a25099b1bf0c870235c6861ffc16042377/pkg/storage/node_liveness.go#L256)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

you want this incremented even in the case of `errNodeAlreadyAlive`?
</blockquote></details>

No, that's why it's done after that condition is checked. Maybe I don't understand your comment. I don't want metrics incremented for success or failure if the node is already live.

---

*[pkg/storage/node_liveness.go, line 265 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352#-KZNfIf84kqu_ZsFuBHA:-KZNjfmVnM2EsjfiIp2g:b-oi8o3u) ([raw file](https://github.com/cockroachdb/cockroach/blob/d29156a25099b1bf0c870235c6861ffc16042377/pkg/storage/node_liveness.go#L265)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this should return err - bad conflict resolution?
</blockquote></details>

This comment doesn't make sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352)*

**Comment by tamird** [comment]
Yep, I was misreading. lgtm

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12352#-:-KZNkWecV73nB6HxEG5W:bojemak)*

**Pull request merged**
