### PR TITLE
storage/engine: MVCCReverseScan optimization

### PR DESCRIPTION
**Pull request by petermattis**
Avoid a call to `First` or `SeekToFirst` when reverse scanning reaches
the end of iteration. When a lower-bound is in effect, this call is
effectively doing a seek which is quite slow. The call is avoided by
enhancing `iterNext` to notice when the iterator is not pointed at a
valid entry and to call `First/SeekToFirst`. Avoiding this unnecessary
seek has a significant effect on short reverse scans:

```
name                                                          old time/op    new time/op     delta
MVCCReverseScan_Pebble/rows=1/versions=1/valueSize=8-16         6.35µs ± 4%     3.28µs ± 6%    -48.44%  (p=0.000 n=10+10)
MVCCReverseScan_Pebble/rows=1/versions=1/valueSize=64-16         145µs ± 4%        5µs ± 1%    -96.51%  (p=0.000 n=10+7)
MVCCReverseScan_Pebble/rows=1/versions=1/valueSize=512-16       7.24µs ± 7%     4.55µs ± 3%    -37.11%  (p=0.000 n=10+10)
MVCCReverseScan_Pebble/rows=10/versions=1/valueSize=8-16        8.78µs ± 3%     5.45µs ± 3%    -37.89%  (p=0.000 n=10+10)
MVCCReverseScan_Pebble/rows=10/versions=1/valueSize=64-16       84.4µs ± 4%      7.8µs ± 2%    -90.80%  (p=0.000 n=9+10)
MVCCReverseScan_Pebble/rows=10/versions=1/valueSize=512-16      13.0µs ± 1%      9.3µs ± 2%    -29.07%  (p=0.000 n=8+9)
MVCCReverseScan_Pebble/rows=100/versions=1/valueSize=8-16       26.5µs ± 2%     23.1µs ± 4%    -12.77%  (p=0.000 n=10+10)
MVCCReverseScan_Pebble/rows=100/versions=1/valueSize=64-16      36.1µs ± 3%     30.0µs ± 1%    -16.98%  (p=0.000 n=10+9)
MVCCReverseScan_Pebble/rows=100/versions=1/valueSize=512-16     50.4µs ± 3%     46.6µs ± 4%     -7.40%  (p=0.000 n=10+9)
MVCCReverseScan_RocksDB/rows=1/versions=1/valueSize=8-16        10.8µs ± 1%      7.7µs ± 1%    -29.36%  (p=0.000 n=10+9)
MVCCReverseScan_RocksDB/rows=1/versions=1/valueSize=64-16       15.9µs ± 1%     10.5µs ± 1%    -34.03%  (p=0.000 n=10+10)
MVCCReverseScan_RocksDB/rows=1/versions=1/valueSize=512-16      12.1µs ± 5%      8.4µs ± 3%    -30.85%  (p=0.000 n=10+10)
MVCCReverseScan_RocksDB/rows=10/versions=1/valueSize=8-16       14.8µs ± 1%     11.5µs ± 1%    -22.25%  (p=0.000 n=9+10)
MVCCReverseScan_RocksDB/rows=10/versions=1/valueSize=64-16      22.5µs ±21%     15.1µs ± 3%    -32.91%  (p=0.000 n=9+10)
MVCCReverseScan_RocksDB/rows=10/versions=1/valueSize=512-16     19.8µs ± 6%     15.0µs ± 1%    -24.42%  (p=0.000 n=10+9)
MVCCReverseScan_RocksDB/rows=100/versions=1/valueSize=8-16      42.3µs ± 1%     38.5µs ± 1%     -8.88%  (p=0.000 n=9+9)
MVCCReverseScan_RocksDB/rows=100/versions=1/valueSize=64-16     52.0µs ± 1%     46.2µs ± 2%    -11.06%  (p=0.000 n=10+9)
MVCCReverseScan_RocksDB/rows=100/versions=1/valueSize=512-16    74.1µs ± 1%     64.4µs ± 2%    -13.07%  (p=0.000 n=10+10)
```

Release note (performance improvement): Improved the low-level
performance of short range reverse scans.

### CODE REVIEW

**Review by ajkr — APPROVED** [review]
Nice find.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42092#-:-LsZkILp-UGXMH0CK3_A:bdkgtmf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @petermattis, and @sumeerbhola)

___
*[c-deps/libroach/mvcc.h, line 627 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42092#-LsZkTxV-t9zQ5KZNL-w:-LsZkTxV-t9zQ5KZNL-x:bajjx00) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb127fd74f574f0c0624fba9cc12c59528a4ce0b/c-deps/libroach/mvcc.h#L627)):*
> ```objc
>       iter_rep_->Prev();
>       if (!iter_rep_->Valid()) {
>         // Peeking at the previous key should never leave the iterator
> ```

This confused me for a while before. Glad to see it gone.

**Review by petermattis — COMMENTED** [review]
TFTR

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42092#-:-LsaxaIF6YiyLRUCYp2Z:b-4as1hm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @sumeerbhola)

___
*[c-deps/libroach/mvcc.h, line 627 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42092#-LsZkTxV-t9zQ5KZNL-w:-LsaxMUlAuPosuM-OVik:b-sgw4tf) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb127fd74f574f0c0624fba9cc12c59528a4ce0b/c-deps/libroach/mvcc.h#L627)):*
<details><summary><i>Previously, ajkr (Andrew Kryczka) wrote…</i></summary><blockquote>

This confused me for a while before. Glad to see it gone.
</blockquote></details>

It was a long-ago patch for a bug. Originally this fix wasn't so problematic for performance because we weren't specifying a lower-bound for iterators. When we switched to specifying lower-bound the performance of this code got dramatically worse.

**Comment by petermattis** [comment]
CI failed in testrace due to a C++ assertion. Yay!

```
[TestMVCCScanMaxNum/rocksdb] [Test Output]
engine.test: /go/src/github.com/cockroachdb/cockroach/c-deps/rocksdb/db/db_iter.cc:178: virtual rocksdb::Slice rocksdb::DBIter::key() const: Assertion `valid_' failed.
SIGABRT: abort
```

Unfortunately, I don't have the full stacktrace, but this shouldn't be too hard to track down.

**Comment by petermattis** [comment]
Hmm, this is proving more challenging to reproduce than I thought. I ran:

```
make stress ENABLE_LIBROACH_ASSERTIONS=true ENABLE_ROCKSDB_ASSERTIONS=true PKG=./storage/engine/ TESTS=TestMVCCScanMaxNum
```

No failures over 5m.

**Comment by petermattis** [comment]
Still can't reproduce, but I do see exactly one code path where `rocksdb::DBIter::key()` was being called without first checking `rocksdb::DBIter::Valid()`. That is now fixed.

**Comment by petermattis** [comment]
Ah, figured out why I couldn't reproduce. Specifying `ENABLE_{LIBROACH,ROCKSDB}_ASSERTIONS` on the make command line causes `{libroach,rocksdb}` to be rebuilt, but does not update `storage/engine/zcgo_flags_*.go`. The `zcgo_flags_*.go` file contains the `-L` directives telling the Go linker what to link against. So I was building `{libroach,rocksdb}` with assertions, but then linking against the version without assertions. Manually removing the `zcgo_flags_*.go` files allowed the assertion failure to be quickly reproduced and then I was able to verify that my fix also fixed the problem.

**Review by sumeerbhola — COMMENTED** [review]
Just some questions about the logic in this file

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42092#-:-Lsca85z9dIdkVLR0n3Q:b30g4uv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @petermattis)

___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 409 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42092#-LscTVtYEJSTkqcmR1mp:-LscTVtYEJSTkqcmR1mq:b-pky2e7) ([raw file](https://github.com/cockroachdb/cockroach/blob/971f41f7ed698f2e2d18c39653689646fa9001cb/pkg/storage/engine/pebble_mvcc_scanner.go#L409)):*
> ```Go
> 		}
> 		if !bytes.Equal(p.curKey, p.keyBuf) {
> 			p.incrementItersBeforeSeek()
> ```

I'm not quite understanding this adaptive `itersBeforeSeek` logic. If we successfully find the relevant key using iteration we increase our iteration budget and if we have to seek we decrease our iteration budget. What is the expected workload behavior that makes this work well?
___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 425 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42092#-LscZRQJ8svjVvdIfMGq:-LscZRQKAtL6OxaZxDRJ:b263mq0) ([raw file](https://github.com/cockroachdb/cockroach/blob/971f41f7ed698f2e2d18c39653689646fa9001cb/pkg/storage/engine/pebble_mvcc_scanner.go#L425)):*
> ```Go
> // specified key. The parameter i is used to maintain iteration count between
> // the loop here and the caller (usually prevKey). Returns false if the iterator
> // was exhausted.
> ```

Like `prevKey()` below, it isn't clear what the assumption is regarding the iterator position when this is called. I had to reread carefully to realize that (at least in one case) the iterator is immediately after `key`.
___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 449 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42092#-LscVlbL-139RRjxlcX2:-LscVlbL-139RRjxlcX3:b-ulg2g2) ([raw file](https://github.com/cockroachdb/cockroach/blob/971f41f7ed698f2e2d18c39653689646fa9001cb/pkg/storage/engine/pebble_mvcc_scanner.go#L449)):*
> ```Go
> }
> 
> // Advance to the newest iteration of the user key preceding the specified key.
> ```

Should "newest iteration" say "newest version"?

There must be an assumption that the iterator is currently positioned at `key`. Can that be added as a comment here?
___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 497 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42092#-LscUeTV56-xcd_RCgtT:-LscUeTV56-xcd_RCgtU:b-4co4ka) ([raw file](https://github.com/cockroachdb/cockroach/blob/971f41f7ed698f2e2d18c39653689646fa9001cb/pkg/storage/engine/pebble_mvcc_scanner.go#L497)):*
> ```Go
> 
> // advanceKeyAtNewKey advances to the key after the specified key, assuming we
> // have just reached the specified key.
> ```

I don't understand the body of this function based on this comment. Specifically why is `!p.reverse` case a noop -- I would expect it to do `p.nextKey()` which would make it the same as `advanceKey()`.

**Review by petermattis — COMMENTED** [review]
> Just some questions about the logic in this file

The logic in this file is not the prettiest. It is oriented around speed, not legibility, though I'm happy to add comments to make it more understandable.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42092#-:-LscdXt_Bqo5ukcSniGp:b-s1f3iu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @sumeerbhola)

___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 409 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42092#-LscTVtYEJSTkqcmR1mp:-LscbwK22zXHaeouirLl:b-2zesr2) ([raw file](https://github.com/cockroachdb/cockroach/blob/971f41f7ed698f2e2d18c39653689646fa9001cb/pkg/storage/engine/pebble_mvcc_scanner.go#L409)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I'm not quite understanding this adaptive `itersBeforeSeek` logic. If we successfully find the relevant key using iteration we increase our iteration budget and if we have to seek we decrease our iteration budget. What is the expected workload behavior that makes this work well?
</blockquote></details>

It is adapting to an unknown number of versions for each key, and working under the assumption that if we see N versions for a key, we're likely to see a similar number for adjacent keys. Usually, iteration is much faster, but if you have a sufficient number of versions seeking is faster. This optimization is useful, though we'd be better off if older versions were segregated at the storage layer as iterating in the presence of many versions is very slow.
___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 425 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42092#-LscZRQJ8svjVvdIfMGq:-LscclCv3u597cF2tLjE:bmptoo5) ([raw file](https://github.com/cockroachdb/cockroach/blob/971f41f7ed698f2e2d18c39653689646fa9001cb/pkg/storage/engine/pebble_mvcc_scanner.go#L425)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Like `prevKey()` below, it isn't clear what the assumption is regarding the iterator position when this is called. I had to reread carefully to realize that (at least in one case) the iterator is immediately after `key`.
</blockquote></details>

I believe the assumption is that the iterator is currently pointed at the oldest version of `key`. Comment added.
___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 449 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42092#-LscVlbL-139RRjxlcX2:-LsccWSh7va7-3NrejO-:bz64lxf) ([raw file](https://github.com/cockroachdb/cockroach/blob/971f41f7ed698f2e2d18c39653689646fa9001cb/pkg/storage/engine/pebble_mvcc_scanner.go#L449)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Should "newest iteration" say "newest version"?

There must be an assumption that the iterator is currently positioned at `key`. Can that be added as a comment here?
</blockquote></details>

Yes. Comment added.
___
*[pkg/storage/engine/pebble_mvcc_scanner.go, line 497 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42092#-LscUeTV56-xcd_RCgtT:-Lscd7KG9ZzctqFRQONf:b-hcp144) ([raw file](https://github.com/cockroachdb/cockroach/blob/971f41f7ed698f2e2d18c39653689646fa9001cb/pkg/storage/engine/pebble_mvcc_scanner.go#L497)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I don't understand the body of this function based on this comment. Specifically why is `!p.reverse` case a noop -- I would expect it to do `p.nextKey()` which would make it the same as `advanceKey()`.
</blockquote></details>

This is called from `seekVersion` in cases where we've already advanced to the next key. During forward iteration, when we've advanced to the next key there is nothing to do. In reverse iteration, we need to back up

**Pull request merged**
