### PR TITLE
util/parquet: add support for all types

### PR DESCRIPTION
**Pull request by jayshrivastava**
This change adds support for the following types families to the `util/parquet` library:
types.INetFamily, types.JsonFamily, types.FloatFamily, types.BytesFamily, types.BitFamily, types.EnumFamily, types.Box2DFamily, types.GeographyFamily, types.GeometryFamily, types.DateFamily, types.TimeFamily, types.TimeTZFamily, case types.IntervalFamily, types.TimestampTZFamily.

Release note: None

Informs: #99028
Epic: https://cockroachlabs.atlassian.net/browse/CRDB-15071

### CODE REVIEW

**Review by miretskiy — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101946)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava)

___
*[`pkg/sql/sem/tree/datum.go` line 1424 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101946#-NTViucW8RYza3ykMUf6:-NTViucW8RYza3ykMUf7:bw56dlq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebd58eaf14449ecbe53ef46b5f8b0a34f25835ba/pkg/sql/sem/tree/datum.go#L1424)):*
> ```Go
> }
> 
> // AsDCollatedString attempts to retrieve a DString from an Expr, returning a AsDCollatedString and
> ```

nit: comments wrap at 80?
___
*[`pkg/sql/sem/tree/datum.go` line 5083 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101946#-NTYgltj20MfHybm59q8:-NTYgltk2MtXfvIcSUeJ:b-2xznij) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebd58eaf14449ecbe53ef46b5f8b0a34f25835ba/pkg/sql/sem/tree/datum.go#L5083)):*
> ```Go
> // a flag signifying whether the assertion was successful. The function should
> // // be used instead of direct type assertions wherever a *DEnum wrapped by a
> // // *DOidWrapper is possible.
> ```

nit: extra '//'' in the comment above
___
*[`pkg/sql/sem/tree/datum.go` line 5092 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101946#-NTVjB6PAUrd2oyoUpK8:-NTVjB6PAUrd2oyoUpK9:b-afhgde) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebd58eaf14449ecbe53ef46b5f8b0a34f25835ba/pkg/sql/sem/tree/datum.go#L5092)):*
> ```Go
> 	}
> 	return nil, false
> }
> ```

I was hoping that we can get some template magic going... but maybe for another time.
___
*[`pkg/sql/sem/tree/format.go` line 670 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101946#-NTYdFsc04xHN9mv2gQ8:-NTYdFsc04xHN9mv2gQ9:bjl15j9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebd58eaf14449ecbe53ef46b5f8b0a34f25835ba/pkg/sql/sem/tree/format.go#L670)):*
> ```Go
> 
> // CloseAndGetBytes is the same as CloseAndGetString, except it returns bytes.
> // This avoids an allocation by not calling ctx.String().
> ```

Let's expand this comment to say that the return byte array is only valid until the next
call to fmtctx.
___
*[`pkg/sql/sem/tree/format.go` line 673 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101946#-NTYeYug0TRX9WzqwYwc:-NTYeYug0TRX9WzqwYwd:bvz8p0d) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebd58eaf14449ecbe53ef46b5f8b0a34f25835ba/pkg/sql/sem/tree/format.go#L673)):*
> ```Go
> func (ctx *FmtCtx) CloseAndGetBytes() []byte {
> 	s := ctx.Bytes()
> 	ctx.Close()
> ```

This is definitely not safe.  You cannot have CloseAndGetBytes method.  As a matter of fact, you should not have this method at all.
Unless i'm misreading the code, ctx.Close() resets the buffer (that's fine because you're still pointing to the "old" slice), but more important it returns it to the pool; and that means that that context can be reused, and the data in the underlying array will be overridden.
As I say above, just have a Writer level fmtCtx (which you close when you close the writer), and pass fmtCtx on every call;  You can then call ctx.Bytes() yourself, and that's safe because you complete encoding of the datum before you encode the next one.
___
*[`pkg/util/parquet/decoders.go` line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101946#-NTVkiCwCvnE4QEV4n4c:-NTVkiCwCvnE4QEV4n4d:bpxvk81) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebd58eaf14449ecbe53ef46b5f8b0a34f25835ba/pkg/util/parquet/decoders.go#L96)):*
> ```Go
> 	dtStr := string(v)
> 	d, dependsOnCtx, err := tree.ParseDTimestampTZ(nil, dtStr, time.Microsecond)
> 	if dependsOnCtx {
> ```

hmm... should we return an error hire?
Should we use default parse context?
Note: changefeed (queries at least) serialize this information in the proto buffer, so you probably have
access to it.  If it's a test only thing, i'd just use default context.
___
*[`pkg/util/parquet/schema.go` line 356 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101946#-NTYcSIQ1qIWhiPgv5EG:-NTYcSIQ1qIWhiPgv5EH:b-mq1f0) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebd58eaf14449ecbe53ef46b5f8b0a34f25835ba/pkg/util/parquet/schema.go#L356)):*
> ```Go
> 		result.decoder = collatedStringDecoder{}
> 		return result, nil
> 	case types.ArrayFamily:
> ```

Let's add a test that calls this function for all valid type families.
You can iterate over `types.Family_values` map and call this function for each one (I'm sure there will be some corner cases, like array, but I know you can figure out a way to make sure we don't miss any types, or any new types that can be added in the future)
___
*[`pkg/util/parquet/testutils.go` line 271 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101946#-NTYjJFq0CoW4OdlZ6jX:-NTYjJFq0CoW4OdlZ6jY:b1ug4ah) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebd58eaf14449ecbe53ef46b5f8b0a34f25835ba/pkg/util/parquet/testutils.go#L271)):*
> ```Go
> 			PhysicalRepresentations: [][]byte{
> 				{0x42, 0x1},
> 				{0x42},
> ```

there is no utility method out there to help you generate those 0x42, etc?
___
*[`pkg/util/parquet/write_functions.go` line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101946#-NTYdmzf0CR0JXW_4uL4:-NTYdmzf0CR0JXW_4uL5:b9drbzs) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebd58eaf14449ecbe53ef46b5f8b0a34f25835ba/pkg/util/parquet/write_functions.go#L179)):*
> ```Go
> 	fmtCtx := tree.NewFmtCtx(tree.FmtExport)
> 	d.Format(fmtCtx)
> 	a.byteArrayBatch[0] = fmtCtx.CloseAndGetBytes()
> ```

fmtCtx should be Closed() at some point; otherwise it is never returned to the pool.

You have a bit more work to do, but I think it would make sense to allocate a single fmtCtx in the Writer (top level parquet datum writer); close this fmtCtx in the close method of the writer, and pass
explicit FmtCtx argument to each write function.
___
*[`pkg/util/parquet/writer_test.go` line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101946#-NTYiwTF0t8_Jtx88zr5:-NTYiwTG1HiX5oNC_z5C:b-b63gt0) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebd58eaf14449ecbe53ef46b5f8b0a34f25835ba/pkg/util/parquet/writer_test.go#L63)):*
> ```Go
> 			// We will manually add array types which are supported below.
> 			// Excluding types.TupleFamily and types.ArrayFamily leaves us with only
> 			// scalar types so far.
> ```

so, we still have few more follow on PRs to handle the above (typles, array of arrays, tuples of array of tuples, etc; correct?

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101946)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava)

___
*[`pkg/util/parquet/write_functions.go` line 346 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101946#-NTYkWhbDYHWlYYdQLLu:-NTYkWhbDYHWlYYdQLLv:b95qiwt) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebd58eaf14449ecbe53ef46b5f8b0a34f25835ba/pkg/util/parquet/write_functions.go#L346)):*
> ```Go
> }
> 
> func writeJson(
> ```

nit: capitalize JSON?

**Review by jayshrivastava — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101946)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[`pkg/sql/sem/tree/datum.go` line 5092 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101946#-NTVjB6PAUrd2oyoUpK8:-NV-rSjo2Nfllb909SDn:b-ubyday) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebd58eaf14449ecbe53ef46b5f8b0a34f25835ba/pkg/sql/sem/tree/datum.go#L5092)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I was hoping that we can get some template magic going... but maybe for another time.
</blockquote></details>

Good idea :) 
___
*[`pkg/util/parquet/decoders.go` line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101946#-NTVkiCwCvnE4QEV4n4c:-NV-nbgq7HPwV8z6AxR2:b-byj140) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebd58eaf14449ecbe53ef46b5f8b0a34f25835ba/pkg/util/parquet/decoders.go#L96)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

hmm... should we return an error hire?
Should we use default parse context?
Note: changefeed (queries at least) serialize this information in the proto buffer, so you probably have
access to it.  If it's a test only thing, i'd just use default context.
</blockquote></details>

I think what I have is good. This is only used in testing. When we write parquet timestamps, we write the timestamp explicitly (we don't encode them as "NOW()" or anything like that). Thus we should assert in tests that the parse context is not required. If I'm reading the code correctly, the parse context is only needed for the current time or current timezone when those are not available. 

See 
- https://github.com/cockroachdb/cockroach/blob/048f8333c4f6f5ca1b5089bb51108c0d7c578541/pkg/util/timeutil/pgdate/field_extract.go#L167-L170
- https://github.com/cockroachdb/cockroach/blob/048f8333c4f6f5ca1b5089bb51108c0d7c578541/pkg/util/timeutil/pgdate/parsing.go#L246-L250
___
*[`pkg/util/parquet/schema.go` line 356 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101946#-NTYcSIQ1qIWhiPgv5EG:-NV0-V725BBYpsUWDb6Y:b-jpl8h3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebd58eaf14449ecbe53ef46b5f8b0a34f25835ba/pkg/util/parquet/schema.go#L356)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Let's add a test that calls this function for all valid type families.
You can iterate over `types.Family_values` map and call this function for each one (I'm sure there will be some corner cases, like array, but I know you can figure out a way to make sure we don't miss any types, or any new types that can be added in the future)
</blockquote></details>

I think the existing randomized test that uses `randgen.SeedTypes` gets the job done already, as it is made by iterating over all types - see below. The set of all types should cover all families. 

I could use something like `types.Family_name` to iterate over all the families and call this function in a test, but this function takes a `*types.T`. I would have to randomly generate a type from the family, which can get a bit messy. I feel like the existing randomized test is sufficient. 

https://github.com/cockroachdb/cockroach/blob/85b666ebd9c23814fee748ed82a4b0e1bac66ec1/pkg/sql/randgen/type.go#L41-L80
___
*[`pkg/util/parquet/testutils.go` line 271 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101946#-NTYjJFq0CoW4OdlZ6jX:-NUwyG20Ar33kekjFhLx:b-ftt8i2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebd58eaf14449ecbe53ef46b5f8b0a34f25835ba/pkg/util/parquet/testutils.go#L271)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

there is no utility method out there to help you generate those 0x42, etc?
</blockquote></details>

Yes there is. Done.
___
*[`pkg/util/parquet/write_functions.go` line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101946#-NTYdmzf0CR0JXW_4uL4:-NV-rYlX-aA0D06sz_5w:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebd58eaf14449ecbe53ef46b5f8b0a34f25835ba/pkg/util/parquet/write_functions.go#L179)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

fmtCtx should be Closed() at some point; otherwise it is never returned to the pool.

You have a bit more work to do, but I think it would make sense to allocate a single fmtCtx in the Writer (top level parquet datum writer); close this fmtCtx in the close method of the writer, and pass
explicit FmtCtx argument to each write function.

</blockquote></details>

Done.
___
*[`pkg/util/parquet/writer.go` line 123 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101946#-NV-t-UY2xYadaYNAAjn:-NV-t-UY2xYadaYNAAjo:bebafv4) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e07b02da7610353ee644d732df43f412f0ec627/pkg/util/parquet/writer.go#L123)):*
> ```Go
> 	}
> 	fmtCtx.Close()
> ```

I decided not to store one `fmtCtx` in the `Writer` and reuse it. I want to avoid this situation: Say we write a large JSON, so the `[]byte` in the `fmtCtx` grows and then we write small datums. The memory required to store the JSON is not released. To avoid the problem, I create a new `fmtCtx` when we call write and close it after writing. I assume that the underlying pool is smart enough to release large allocs in the pool - at least when memory is required elsewhere
___
*[`pkg/util/parquet/writer_test.go` line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101946#-NTYiwTF0t8_Jtx88zr5:-NUvrSgq7Y8inqB-Vv9N:bklmdy7) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebd58eaf14449ecbe53ef46b5f8b0a34f25835ba/pkg/util/parquet/writer_test.go#L63)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

so, we still have few more follow on PRs to handle the above (typles, array of arrays, tuples of array of tuples, etc; correct?
</blockquote></details>

Yes ofc... But I think we should integrate these with changefeeds and `EXPORT` first.
___
*[`pkg/sql/sem/tree/format.go` line 670 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101946#-NTYdFsc04xHN9mv2gQ8:-NV-rWX21d-78EKMz17z:b-6ya215) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebd58eaf14449ecbe53ef46b5f8b0a34f25835ba/pkg/sql/sem/tree/format.go#L670)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Let's expand this comment to say that the return byte array is only valid until the next
call to fmtctx.
</blockquote></details>

Deleted this method.
___
*[`pkg/sql/sem/tree/format.go` line 673 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101946#-NTYeYug0TRX9WzqwYwc:-NV-nBO81--HD6Yysb2Y:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebd58eaf14449ecbe53ef46b5f8b0a34f25835ba/pkg/sql/sem/tree/format.go#L673)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

This is definitely not safe.  You cannot have CloseAndGetBytes method.  As a matter of fact, you should not have this method at all.
Unless i'm misreading the code, ctx.Close() resets the buffer (that's fine because you're still pointing to the "old" slice), but more important it returns it to the pool; and that means that that context can be reused, and the data in the underlying array will be overridden.
As I say above, just have a Writer level fmtCtx (which you close when you close the writer), and pass fmtCtx on every call;  You can then call ctx.Bytes() yourself, and that's safe because you complete encoding of the datum before you encode the next one.
</blockquote></details>

Done.

**Review by miretskiy — APPROVED** [review]
> Reviewed 3 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101946)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava)

___
*[`pkg/util/parquet/schema.go` line 356 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101946#-NTYcSIQ1qIWhiPgv5EG:-NV026GF6btnWMeUsMD-:b22522u) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebd58eaf14449ecbe53ef46b5f8b0a34f25835ba/pkg/util/parquet/schema.go#L356)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

I think the existing randomized test that uses `randgen.SeedTypes` gets the job done already, as it is made by iterating over all types - see below. The set of all types should cover all families. 

I could use something like `types.Family_name` to iterate over all the families and call this function in a test, but this function takes a `*types.T`. I would have to randomly generate a type from the family, which can get a bit messy. I feel like the existing randomized test is sufficient. 

https://github.com/cockroachdb/cockroach/blob/85b666ebd9c23814fee748ed82a4b0e1bac66ec1/pkg/sql/randgen/type.go#L41-L80
</blockquote></details>

It's fine; it is sufficient in terms for coverage.
Explicitly iterating over all types could produce better error messages though.
Like "missing parser for newly added type Foo" type error.
Up to you.
___
*[`pkg/util/parquet/writer.go` line 122 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101946#-NV02zUm4480R1VioPPo:-NV02zUm4480R1VioPPp:bfikrcy) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e07b02da7610353ee644d732df43f412f0ec627/pkg/util/parquet/writer.go#L122)):*
> ```Go
> 		return err
> 	}
> 	fmtCtx.Close()
> ```

defer close right after you get NewFmtCtx since you may return an error above.

**Comment by jayshrivastava** [comment]
bors r=miretskiy

**Pull request merged**
