### PR TITLE
execbuilder: deflake TestExecBuild

### LINKED ISSUE #74933: sql/opt/exec/execbuilder: TestExecBuild failed
sql/opt/exec/execbuilder.TestExecBuild [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4140046&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4140046&tab=artifacts#/) on master @ [365b4da8bd02c06ee59d2130a56dec74ffc9ce21](https://github.com/cockroachdb/cockroach/commits/365b4da8bd02c06ee59d2130a56dec74ffc9ce21):

```
            • sort
            │ order: +k
            │
            └── • filter
                │ filter: st_intersects('01040000000200000001010000009A999999999901409A99999999990140010100000000000000000008400000000000000840', geom)
                │
                └── • index join
                    │ table: geo_table@geo_table_pkey
                    │
                    └── • inverted filter
                        │ inverted column: geom_inverted_key
                        │ num spans: 31
                        │
                        └── • scan
                              missing stats
                              table: geo_table@geom_index
                              spans: 31 spans
            ·
            Diagram: https://cockroachdb.github.io/distsqlplan/decode.html#eJyUlFFP2zwUhu-_X2GdG1p9prWdlA1fFUbYMpWWpZ02NFcoa85YRLEz2506of73KQ0DAmogvnB7jv2ck_e17Ftwv5YgIfp6PjqKx6RzEk9n00-jLplGo-jdjFyT02RyRq7QXPr0-xLJlw9REhHnL3Pt0TpceNfZO_s8msXnk3g863RETxDRE11KOkGPkaDHut09Kd9Hk7NollzQstZNl0ySkyghxxfkGihok-E4vUEH8htwoCBgTqGwZoHOGVumb7eb4mwNklHIdbHyZXpOYWEsgrwFn_slgoSx2TdFfwAUMvRpvtxu21AwK_8AOZ9eIciDDX1UmDcXnpUGJJhmaPusVh7u_RmW6i5zneEaKEyLVDtJ-gqOlVr_yJRac6bUmr00wX5bhisgqc5IwIjxP9E62KWZt9Ec699oPWan-dKjRdvndeH_1qN1YYnRZMglcaVq4nxqvdyqCN4MlGKCKcXYSxMQ1FlbrBT_RD2FycpLMuQ7fRBtfPhocn139GLX0Rc2v0ntn4fWdCh2dg_adL93P6j3rvLy6XVknIWsGuLulzNe_Tk8OrwfjIfP4oedtfE2fBbvyce3eii6r_A8bKN6aqxH2w_rmof8_53lB7XyL7wTCbrCaIeveijYZk4Bsyus3iJnVnaB59Ystm2qcLLltokMna9WD6og1tVS-YGPYd4Ii2ZYNMJBMxw0wmEzHDbCg2Z40AizJ_B889_fAAAA___nMRL3
            
        but found (query options: "") :
            distribution: local
            vectorized: true
            ·
            • sort
            │ order: +k
            │
            └── • filter
                │ filter: st_intersects('01040000000200000001010000009A999999999901409A99999999990140010100000000000000000008400000000000000840', geom)
                │
                └── • index join
                    │ table: geo_table@geo_table_pkey
                    │
                    └── • inverted filter
                        │ inverted column: geom_inverted_key
                        │ num spans: 31
                        │
                        └── • scan
                              missing stats
                              table: geo_table@geom_index
                              spans: 31 spans
            ·
            Diagram: https://cockroachdb.github.io/distsqlplan/decode.html#eJyUlFFP2zAQx9_3Kax7odW81naCNvxUGGHLVChLO21orlDW3FhEsTPbnTKhfvcpCQNa1ED84PbO_v3P_7OcW3C_lyAh-nY-PozPSO84ns6mn8d9Mo3G0fsZuSYnyeSUXKG59OmPJZKvH6MkIs5f5tqjdbjwrrd3-mU8i88n8dms1xMDQcRA9CnpBQNGggHr9_ek_BBNTqNZckErrZs-mSTHUUKOLsg1UNAmw7P0Bh3I78BhTqGwZoHOGVulbusNcVaCZBRyXax8lZ5TWBiLIG_B536JIGFWnTHBNEM7ZEAhQ5_my1r23sKoOsBlrjMsgcK0SLWTZKjgSKnyZ6ZUyZlSJXtugjddGa6ApDojASPG_0LrYL6mYFb-wY_z6RWC5Gv6cs-x_oPWY3aSLz1atEO-afz_elQWlhhNRlwSV7kmzqfWy9pF8HZfKSaYUow9NwFBnXXFKvNb7ilMVl6SEd_ZB9GlD59Mru-uXuy6-sLmN6n9-1CajsTO6kGX6vfdDzZrN3m5_WIYZyFrhrj75Yw3fw4OD-4H4-GT-GHnxngXPon35OOHNxL9F_Q87OJ6aqxHOww3PY_4653y-13kE3SF0Q435Hcps_WcAmZX2HwynFnZBZ5bs6jLNOGk5upEhs43q7wJYt0sVQd8DPNWWLTDohUO2uGgFQ7b4bAV3t-C5-tX_wIAAP__VL3gzA==
--- done: testdata/inverted_filter_geospatial_dist with config 5node: 13 tests, 1 failures
    logic.go:3370: 
        testdata/inverted_filter_geospatial_dist:206: error while processing
    logic.go:3370: testdata/inverted_filter_geospatial_dist:206: too many errors encountered, skipping the rest of the input
        --- FAIL: TestExecBuild/5node/inverted_filter_geospatial_dist (11.11s)
=== RUN   TestExecBuild/5node
    --- FAIL: TestExecBuild/5node (0.00s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
Parameters in this failure:

- GOFLAGS=-json
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestExecBuild.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by irfansharif**
Fixes #74933. This test asserts on physical plans of statements after
moving ranges around, i.e. whether distsql execution is "local" or
"distributed". This is determined by:
- where the distsql planner places processor cores,
- which in turn is a function of the span resolver,
- which delegates to the embedded distsender,
- which operates off of a range cache.

The range cache, like the name suggests, can hold stale data. This test
moved replicas of indexes around to induce distributed execution, but
was not accounting for the caches holding onto stale data. In my test
runs every so often I was seeing stale range descriptors from before the
relocate trip up the planner to generate a local execution, flaking the
test. Fortunately for us, all we need to do is slap on a retry. To
repro:

    # Took under a minute on my gceworker. Helped to trim down the test
    # file slightly.
    dev test pkg/sql/opt/exec/execbuilder \
      -f 'TestExecBuild/5node' -v --show-logs \
      --stress --stress-args '-p 4'

Release note: None

### CODE REVIEW

**Comment by irfansharif** [comment]
Haven't looked around to see if this pattern applies to other test files, I suspect it does and worth looking out for going forward. I'm not really sure why #73876 caused this to flake more reliably.

**Review by cucaroach — CHANGES_REQUESTED** [review]
Should we fix #75282 in this PR or handle it separately?   distsql_enum seemed to be flakey too, should the EXPLAN (VEC) test in there also have a retry?

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75304#-:-MuBSxKYCxjPvtZT-Isu:b-9y7k74)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif and @yuzefovich)

___
*[pkg/sql/opt/exec/execbuilder/testdata/inverted_filter_geospatial_dist, line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75304#-MuBSNIK1dsobhMza8Fp:-MuBSNIK1dsobhMza8Fq:b5fcl1c) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3ec41ea7574f68a79cee3f79f766e6e536ed1aa/pkg/sql/opt/exec/execbuilder/testdata/inverted_filter_geospatial_dist#L109)):*
> ```
> /1152921574000000000  NULL                  {2}       2
> 
> # Distributed. TODO(treilly): This claims to be distributed, but it isn't. What gives?
> ```

Good question!  I think we can handle the bogus comments in this test out of band, not sure if the comments just bitrotted or something deeper is going on.

**Review by irfansharif — COMMENTED** [review]
> Should we fix #75282 in this PR

Done, PTAL.

> distsql_enum seemed to be flakey too, should the EXPLAN (VEC)

Done, though I couldn't repro the original flake. The suggested fix looks right to me though, lets see if it works.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75304#-:-MuBvZy934Rb59l-kqG_:b-t1flxx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @yuzefovich)

___
*[pkg/sql/opt/exec/execbuilder/testdata/inverted_filter_geospatial_dist, line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75304#-MuBSNIK1dsobhMza8Fp:-MuBvlC-44-zeQ4c4Ssk:bmxsif1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3ec41ea7574f68a79cee3f79f766e6e536ed1aa/pkg/sql/opt/exec/execbuilder/testdata/inverted_filter_geospatial_dist#L109)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

Good question!  I think we can handle the bogus comments in this test out of band, not sure if the comments just bitrotted or something deeper is going on.
</blockquote></details>

I'll leave this TODO here for you/your team.

**Review by cucaroach — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75304#-:-MuCnePW51pCcTTCtieE:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @yuzefovich)

**Comment by irfansharif** [comment]
Thanks!

bors r+

**Pull request merged**
