### PR TITLE
Bump our version of glock to avoid race conditions when getting the repo

### LINKED ISSUE #8578: CONTRIBUTING.md instructions don't work on a fresh OS X install
I'm not sure whether it's an issue with the contributing instructions, our dependency management, or the Makefile, but something isn't right for someone that has just the bare minimum of things installed. If I try to run make, I get:

```shell
$ make build
Makefile:219: .bootstrap: No such file or directory
# cd /Users/alex/go/src/cloud.google.com/go; git rev-parse HEAD
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD
exit status 128
make: *** [.bootstrap] Error 1
```

My machine meets the stated prerequisites of the guide (C++ compiler > v6.0, go v1.6, git > v1.8, and bash) with the one exception that I have go 1.6.3 instead of 1.6.2. I believe my go environment is set up correctly:

```shell
$ echo $GOPATH
/Users/alex/go
$ pwd
/Users/alex/go/src/github.com/cockroachdb/cockroach
```

And I downloaded cockroach and its dependencies by running `go get -d github.com/cockroachdb/cockroach`, as instructed by the guide.

I'll see if I can figure out the problem and fix the guide.

### PR DESCRIPTION
**Pull request by a-robinson**
fixes #8578

@tamird

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8587)

### CODE REVIEW

**Comment by a-robinson** [comment]
Sorry about the CLA spam, I hadn't configured my git client yet. Re-pushed.

**Comment by RaduBerinde** [comment]
LGTM

**Comment by bdarnell** [comment]
LGTM. This should go to both branches, so either merge it to master and merge master into develop, or cherry-pick it into master once this is in develop.

**Comment by a-robinson** [comment]
Switched to merge into master first.

**Comment by RaduBerinde** [comment]
Make sure to rebase the commit onto `master` and push the branch again, or you'll pick up some changes from `develop`.

**Comment by tamird** [comment]
LGTM

**Comment by a-robinson** [comment]
Thanks, rebased onto master.

**Pull request merged**
