### PR TITLE
sql: expose number of KV pairs read in EXPLAIN ANALYZE

### LINKED ISSUE #103972: sql: `KV rows read` in EXPLAIN ANALYZE is misleading
Consider the example:

```sql
-- Create a parent table with 1000 rows, each ~4KB.
CREATE TABLE parent (
  id UUID PRIMARY KEY,
  s STRING
);

INSERT INTO parent
SELECT gen_random_uuid(), repeat('p', 4096)
FROM generate_series(1, 1000);

-- Create 1000 child rows for each parent row.
CREATE TABLE child (
  id UUID PRIMARY KEY,
  parent_id UUID REFERENCES parent(id)
);

INSERT INTO child
SELECT gen_random_uuid(), parent.id
FROM parent, generate_series(1, 100) g(i);

-- Collect table statistics.
ANALYZE parent;
ANALYZE child;

-- Fetch 5000 child/parent pairs.
EXPLAIN ANALYZE
SELECT * FROM child JOIN parent
  ON child.parent_id = parent.id
LIMIT 5000;
```

The output of the `EXPLAIN ANALYZE`:

```
                                                                     info                                                                                                                                                                            
----------------------------------------------------------------------------------------------------------------------------------------------
  planning time: 210µs
  execution time: 35ms
  distribution: full
  vectorized: true
  rows read from KV: 6,120 (4.5 MiB, 2 gRPC calls)
  cumulative time spent in KV: 33ms
  maximum memory usage: 18 MiB
  network usage: 0 B (0 messages)
  sql cpu time: 3ms
  regions: us-east1

  • limit
  │ count: 5000
  │
  └── • hash join
      │ nodes: n1
      │ regions: us-east1
      │ actual row count: 5,000
      │ estimated max memory allocated: 8.3 MiB
      │ estimated max sql temp disk usage: 0 B
      │ sql cpu time: 2ms
      │ estimated row count: 100,000
      │ equality: (parent_id) = (id)
      │ right cols are key
      │
      ├── • scan
      │     nodes: n1
      │     regions: us-east1
      │     actual row count: 5,120
      │     KV time: 31ms
      │     KV contention time: 0µs
      │     KV rows read: 5,120
      │     KV bytes read: 512 KiB
      │     KV gRPC calls: 1
      │     estimated max memory allocated: 6.0 MiB
      │     sql cpu time: 624µs
      │     estimated row count: 100,000 (100% of the table; stats collected 0 seconds ago)
      │     table: child@child_pkey  ----------------------  WARNING: the row count estimate is inaccurate, consider running 'ANALYZE child'
      │     spans: FULL SCAN
      │
      └── • scan
            nodes: n1
            regions: us-east1
            actual row count: 1,000
            KV time: 2ms
            KV contention time: 0µs
            KV rows read: 1,000
            KV bytes read: 4.0 MiB
            KV gRPC calls: 1
            estimated max memory allocated: 8.0 MiB
            sql cpu time: 481µs
            estimated row count: 1,000 (100% of the table; stats collected 1 second ago)
            table: parent@parent_pkey
            spans: FULL SCAN
```

Notice that the scan over table `child` has `KV rows read: 5,120`. This is misleading because (I believe) there were more rows read than 5,000 because a soft limit does not propagate into the scan.

Jira issue: CRDB-28281

### PR DESCRIPTION
**Pull request by yuzefovich**
**sql: expose number of KV pairs read in EXPLAIN ANALYZE**

This commit exposes the number of KV pairs read in the EXPLAIN ANALYZE
output. This information can be useful in cases when some KVs were
fetched but not decoded (e.g. because the LIMIT was satisfied, yet the
limit wasn't pushed down far enough in the plan). My guess is that
it'll be very common that the number of KVs equals the number of rows
read (which is likely to be true on tables with single column families),
so in those cases this new statistic is omitted (unless verbose output
is requested).

Release note (sql change): A new statistic `KV pairs read` is now
exposed on EXPLAIN ANALYZE output in some cases (when this number is
different from `KV rows read` statistic or when VERBOSE option is
requested). This new statistic is also added to the telemetry
sampled query events.

**sql: rename "KV rows read" to "KV rows decoded" in EXPLAIN ANALYZE**

This commit renames `KV rows read` to `KV rows decoded` in EXPLAIN
ANALYZE output to better reflect its meaning. In particular, this
statistic counts the number of SQL rows that were "formulated" (i.e.
formed by decoding some number of KVs), and it's possible that we
actually fetched more KVs that comprise more SQL rows but never decoded
them (e.g. because the LIMIT was satisfied).

Note that only user-visible EXPLAIN output has been changed, meaning the
code as well as code comments still use "rows read" (it didn't seem
worth it to make this change, and it might be more confusing than
helpful in the end).

Fixes: #103972.

Release note (sql change): `KV rows read` statistic of EXPLAIN ANALYZE
output has been renamed to `KV rows decoded` to better reflect its
meaning.

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 37 of 37 files at r1, 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104079#-:-NWrRyyU69TRIPkVS5vQ:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rharding6373 and @yuzefovich)

___
*[`pkg/sql/opt/exec/explain/emit.go` line 428 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104079#-NWrRY8l5Su31MYMXhNL:-NWrRY8l5Su31MYMXhNM:b-nrcz4q) ([raw file](https://github.com/cockroachdb/cockroach/blob/d20c08d6335f9795e59cb90a86ed4b125c3ae25c/pkg/sql/opt/exec/explain/emit.go#L428)):*
> ```Go
> 			if pairs != rows || e.ob.flags.Verbose {
> 				// Only show the number of KV pairs read when it's different
> 				// from the number of rows read or if verbose output is
> ```

nit: "number of rows decoded"?

**Review by rharding6373 — COMMENTED** [review]
Nice work! I have a few comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104079#-:-NWro-yeAAqne00j1g4g:byaw8n4)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104079#-NWrjWT29BAlNmvehVcF):*
Is it intended to always be present in the distsql diagram output even if it's the same value? Glanced through a couple and the new metric appears to be present even if they're the same and have been omitted from the plan output (e.g., in pkg/sql/opt/exec/execbuilder/testdata/explain_analyze_plans).
___
*[`pkg/sql/opt/exec/explain/emit.go` line 430 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104079#-NWrn_vSBla2Hmf7VwNk:-NWrn_vSBla2Hmf7VwNl:b-3v3r5f) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea8abfe55d5df3413957c8df97f20f03606ab41f/pkg/sql/opt/exec/explain/emit.go#L430)):*
> ```Go
> 				// from the number of rows read or if verbose output is
> 				// requested.
> 				e.ob.AddField("KV pairs read", string(humanizeutil.Count(s.KVPairsRead.Value())))
> ```

You mention in explain/output.go that pairs read could be flaky due to column families. Shouldn't that also apply here, and to the output in the distsql diagrams?
___
*[`pkg/sql/opt/exec/explain/output.go` line 328 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104079#-NWrmbhq3gQWy_6D5ts4:-NWrm-7WB2sXI0_41uu1:bz9leth) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea8abfe55d5df3413957c8df97f20f03606ab41f/pkg/sql/opt/exec/explain/output.go#L328)):*
> ```Go
> 		// KV pairs when deterministic EXPLAIN output is desired since the
> 		// column family randomization can change this number.
> 		kvs = fmt.Sprintf("%s KVs, ", humanizeutil.Count(uint64(kvPairs)))
> ```

Could you add an example in the tests where this is printed or point out one that already exists? I didn't notice one. Or will this never turn up in tests due to the deflake flag?
___
*[`pkg/util/log/eventpb/telemetry.proto` line 287 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104079#-NWrhaecDSB3XgWQXRiB:-NWrhaecDSB3XgWQXRiC:bb0mupd) ([raw file](https://github.com/cockroachdb/cockroach/blob/d20c08d6335f9795e59cb90a86ed4b125c3ae25c/pkg/util/log/eventpb/telemetry.proto#L287)):*
> ```proto
>   int64 mvcc_range_key_skipped_points = 74 [(gogoproto.jsontag) = ",omitempty"];
>   reserved 12;
> }
> ```

Could you add a comment along the lines of "Next available ID: 76"?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104079)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rharding6373)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104079#-NWrjWT29BAlNmvehVcF):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Is it intended to always be present in the distsql diagram output even if it's the same value? Glanced through a couple and the new metric appears to be present even if they're the same and have been omitted from the plan output (e.g., in pkg/sql/opt/exec/execbuilder/testdata/explain_analyze_plans).
</blockquote></details>

Yeah, I think it's intended - to a certain degree we're treating the diagram as always asking for verbose output (we include things like MVCC stats in there which are verbose-only, and I think I prefer it that way). My thinking is that the textual explain output is the main user-facing feature, so we need to be conscious about what we include there, but verbose or DistSQL diagram is for "power" users for debugging-like exploration where the more information, the better.
___
*[`pkg/sql/opt/exec/explain/emit.go` line 430 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104079#-NWrn_vSBla2Hmf7VwNk:-NWwdOLuDAo8kyAdtpZY:b-yl16b7) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea8abfe55d5df3413957c8df97f20f03606ab41f/pkg/sql/opt/exec/explain/emit.go#L430)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

You mention in explain/output.go that pairs read could be flaky due to column families. Shouldn't that also apply here, and to the output in the distsql diagrams?
</blockquote></details>

Good question. I thought a bit more about this, and I don't think it actually can be flaky because we always call `MakeDeterministic` in `execbuilder` tests and we don't have any EXPLAIN ANALYZE outputs in the regular logic tests. Thus, I believe it shouldn't be actually flaky.
___
*[`pkg/sql/opt/exec/explain/output.go` line 328 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104079#-NWrmbhq3gQWy_6D5ts4:-NWwcx6w9B9_L_hYFnoL:bcxuygk) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea8abfe55d5df3413957c8df97f20f03606ab41f/pkg/sql/opt/exec/explain/output.go#L328)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Could you add an example in the tests where this is printed or point out one that already exists? I didn't notice one. Or will this never turn up in tests due to the deflake flag?
</blockquote></details>

Indeed, this wasn't showing up in tests (we only have `execbuilder` ones) because of the deflake flag. Thinking about it more, the number of KV pairs won't be flaky there because we always call `MakeDeterministic`, so I removed the deflake flag from the conditional. I also modified `MakeDeterministic` so that the number of KV pairs is double of rows read, so it's now shown in the tests. Done.
___
*[`pkg/util/log/eventpb/telemetry.proto` line 287 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104079#-NWrhaecDSB3XgWQXRiB:-NWwZ5cr87Y2pQHK0DIn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d20c08d6335f9795e59cb90a86ed4b125c3ae25c/pkg/util/log/eventpb/telemetry.proto#L287)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Could you add a comment along the lines of "Next available ID: 76"?
</blockquote></details>

Done.

**Review by j82w — COMMENTED** [review]
> Reviewed 1 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104079)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @rharding6373, and @yuzefovich)

___
*[`-- commits` line 14 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/104079#-NWx0a1i6lAx3GhLCL4q):*
Can also add that it's exposed in the logs via the sampled query event?

**Review by rharding6373 — APPROVED** [review]
:lgtm: It's going to be nice to have this extra info.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104079#-:-NWxNoNeC-S_51aEZLb9:bb0v2y4)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @j82w, @mgartner, and @yuzefovich)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104079#-NWrjWT29BAlNmvehVcF):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Yeah, I think it's intended - to a certain degree we're treating the diagram as always asking for verbose output (we include things like MVCC stats in there which are verbose-only, and I think I prefer it that way). My thinking is that the textual explain output is the main user-facing feature, so we need to be conscious about what we include there, but verbose or DistSQL diagram is for "power" users for debugging-like exploration where the more information, the better.
</blockquote></details>

Ok, just checking. Thanks!
___
*[`pkg/sql/opt/exec/explain/emit.go` line 430 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104079#-NWrn_vSBla2Hmf7VwNk:-NWxKOgb97SJgGQyPdZ3:b-3ibkqz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea8abfe55d5df3413957c8df97f20f03606ab41f/pkg/sql/opt/exec/explain/emit.go#L430)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Good question. I thought a bit more about this, and I don't think it actually can be flaky because we always call `MakeDeterministic` in `execbuilder` tests and we don't have any EXPLAIN ANALYZE outputs in the regular logic tests. Thus, I believe it shouldn't be actually flaky.
</blockquote></details>

Ok, makes sense. Thanks.

**Review by yuzefovich — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104079#-:-NWxhX1Y7bONwIsm4rWq:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @j82w and @mgartner)

___
*[`-- commits` line 14 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/104079#-NWx0a1i6lAx3GhLCL4q):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Can also add that it's exposed in the logs via the sampled query event?
</blockquote></details>

Done.

**Pull request merged**
