### PR TITLE
storage: err on snapshot of large ranges

### PR DESCRIPTION
**Pull request by dt**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7788)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[storage/replica_raftstorage.go, line 260 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7788#-KMVxA7VToZs5OZK4CXa:-KMVxA7WfTLw9tYaHwOp:300956814) ([raw file](https://github.com/cockroachdb/cockroach/blob/20fa229c019e920bf16992edfb5e08f73a4efc79/storage/replica_raftstorage.go#L260)):*
> ```Go
> 	rangeID := r.RangeID
> 
> 	if r.needsSplitBySizeLocked() {
> ```

I was imagining we'd only do this if the snapshot size was excessive (i.e 3-4x the target range size), but perhaps it is always better to delay a snapshot if splitting needs to be done. @bdarnell?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7788)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[storage/replica_raftstorage.go, line 258 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7788#-KMVzqQWOLXqETRhbM_z:-KMVzqQWOLXqETRhbMa-:-341363121) ([raw file](https://github.com/cockroachdb/cockroach/blob/20fa229c019e920bf16992edfb5e08f73a4efc79/storage/replica_raftstorage.go#L258)):*
> ```Go
> // Snapshot requires that the replica lock is held.
> func (r *Replica) Snapshot() (raftpb.Snapshot, error) {
> 	rangeID := r.RangeID
> ```

can be below the size check

---

*[storage/replica_raftstorage_test.go, line 34 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7788#-KMW-HfWACGEtrdiPZKf:-KMW-HfXS_ltCF938zRW:-96912388) ([raw file](https://github.com/cockroachdb/cockroach/blob/20fa229c019e920bf16992edfb5e08f73a4efc79/storage/replica_raftstorage_test.go#L34)):*
> ```Go
> const valSize = 1 << 10 // 1 KiB
> 
> func fillTestRange(t testing.TB, rep *Replica, rangeID roachpb.RangeID, snapSize int) {
> ```

isn't `rangeID` always `rep`'s range ID? `snapSize` is also not a useful name in this "general" method

---

*[storage/replica_raftstorage_test.go, line 70 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7788#-KMW-TLdskVP-x3xyGhT:-KMW-TLdskVP-x3xyGhU:498980799) ([raw file](https://github.com/cockroachdb/cockroach/blob/20fa229c019e920bf16992edfb5e08f73a4efc79/storage/replica_raftstorage_test.go#L70)):*
> ```Go
> 	fillTestRange(t, rep, rangeID, snapSize*2)
> 
> 	if _, err := rep.Snapshot(); err == nil {
> ```

small nit: check that this is the right error, not just non-nil

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7788)*

**Comment by dt** [comment]
Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[storage/replica_raftstorage.go, line 258 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7788#-KMVzqQWOLXqETRhbM_z:-KMWD3THoleXPVLbn9N-:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/20fa229c019e920bf16992edfb5e08f73a4efc79/storage/replica_raftstorage.go#L258)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can be below the size check
</details>
Done.

---

*[storage/replica_raftstorage_test.go, line 34 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7788#-KMW-HfWACGEtrdiPZKf:-KMWCtJhVO1AHvXykuye:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/20fa229c019e920bf16992edfb5e08f73a4efc79/storage/replica_raftstorage_test.go#L34)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> isn't `rangeID` always `rep`'s range ID? `snapSize` is also not a useful name in this "general" method
</details>
Done.

---

*[storage/replica_raftstorage_test.go, line 70 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7788#-KMW-TLdskVP-x3xyGhT:-KMWCi1_4PV0nXCceqMC:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/20fa229c019e920bf16992edfb5e08f73a4efc79/storage/replica_raftstorage_test.go#L70)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> small nit: check that this is the right error, not just non-nil
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7788)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[storage/replica_raftstorage_test.go, line 73 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7788#-KMWEZfOpXrdihW9Xm6f:-KMWEZfPho91vqP-_CDN:588199593) ([raw file](https://github.com/cockroachdb/cockroach/blob/a428575fd30ea3d72c9dacc98b5e6ce4486d4d7c/storage/replica_raftstorage_test.go#L73)):*
> ```Go
> 
> 	if _, err := rep.Snapshot(); err != raft.ErrSnapshotTemporarilyUnavailable {
> 		t.Fatal("snapshot of a very large range should fail")
> ```

log the unexpected error

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7788)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[storage/replica_raftstorage_test.go, line 85 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7788#-KMWEdhx31mzRXW3yis1:-KMWEdhx31mzRXW3yis2:-1054325866) ([raw file](https://github.com/cockroachdb/cockroach/blob/a428575fd30ea3d72c9dacc98b5e6ce4486d4d7c/storage/replica_raftstorage_test.go#L85)):*
> ```Go
> 	defer stopper.Stop()
> 
> 	const snapSize = 1 << 25 // 32 MiB
> ```

remove?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7788)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 1 of 3 files at r2, 1 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[storage/replica_raftstorage.go, line 260 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7788#-KMVxA7VToZs5OZK4CXa:-KM_kiw8GbZs3YiLcW-q:605064563) ([raw file](https://github.com/cockroachdb/cockroach/blob/20fa229c019e920bf16992edfb5e08f73a4efc79/storage/replica_raftstorage.go#L260)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I was imagining we'd only do this if the snapshot size was excessive (i.e 3-4x the target range size), but perhaps it is always better to delay a snapshot if splitting needs to be done. @bdarnell?
</details>
We use the unmodified target size in `replicateQueue`; whatever we use should be consistent between the two. (this is just a fallback in case the range has grown between the decision to replicate and the time that the snapshot is actually sent)

I think it's better to be strict about this than to allow a multiple of the target size. Until we have streaming snapshots, we already have a 3-4x amplification factor in memory, and allowing 64MB * 4 * 4 = 1GB of memory to be consumed by a snapshot of a single range doesn't sound like a good idea.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7788#-:-KM_o-9sHInGMVnJN5sz:1417088721)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[storage/replica_raftstorage.go, line 260 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7788#-KMVxA7VToZs5OZK4CXa:-KM_oJmDdLmvtEXks7jz:-1868815981) ([raw file](https://github.com/cockroachdb/cockroach/blob/20fa229c019e920bf16992edfb5e08f73a4efc79/storage/replica_raftstorage.go#L260)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> We use the unmodified target size in `replicateQueue`; whatever we use should be consistent between the two. (this is just a fallback in case the range has grown between the decision to replicate and the time that the snapshot is actually sent)
> 
> I think it's better to be strict about this than to allow a multiple of the target size. Until we have streaming snapshots, we already have a 3-4x amplification factor in memory, and allowing 64MB * 4 * 4 = 1GB of memory to be consumed by a snapshot of a single range doesn't sound like a good idea.
</details>
True. My concern was that this limit will block raft from recovering an existing replica of a large range via a snapshot until that range has split. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7788)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[storage/replica_raftstorage.go, line 260 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7788#-KMVxA7VToZs5OZK4CXa:-KM_pkIMbw7UBldGoFl8:1620120422) ([raw file](https://github.com/cockroachdb/cockroach/blob/20fa229c019e920bf16992edfb5e08f73a4efc79/storage/replica_raftstorage.go#L260)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> True. My concern was that this limit will block raft from recovering an existing replica of a large range via a snapshot until that range has split. 
</details>
Hmm. Yeah, it might be worth using a higher limit here since we could be in a state where we can't split until we've recovered a lagging follower. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7788)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7788)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[storage/replica_raftstorage.go, line 260 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7788#-KMVxA7VToZs5OZK4CXa:-KMaok8UqD7WnMVpi70k:1144485651) ([raw file](https://github.com/cockroachdb/cockroach/blob/20fa229c019e920bf16992edfb5e08f73a4efc79/storage/replica_raftstorage.go#L260)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Hmm. Yeah, it might be worth using a higher limit here since we could be in a state where we can't split until we've recovered a lagging follower. 
</details>
How could we be in that situation? We'll only trim the raft log to the quorum commit index. If there is a lagging replica we're already in a danger zone. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7788)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[storage/replica_raftstorage.go, line 260 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7788#-KMVxA7VToZs5OZK4CXa:-KMbNfiKRuoR12Dx-1Pn:-84896729) ([raw file](https://github.com/cockroachdb/cockroach/blob/20fa229c019e920bf16992edfb5e08f73a4efc79/storage/replica_raftstorage.go#L260)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> How could we be in that situation? We'll only trim the raft log to the quorum commit index. If there is a lagging replica we're already in a danger zone. 
</details>
It's possible in edge cases when recovering from certain near-death experiences. For example, in a range on nodes A, B, and C, B dies, then some time later C dies (without any replica changes in between). B is revived, but C is unrecoverable. This range can recover if and only if A can send a snapshot to B. 

I can't come up with any situation in which this matters that doesn't involve multiple failures, so maybe it's not a situation we want to promise to handle, but there are cases where we could theoretically recover but this limit would prevent it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7788)*

**Comment by dt** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[storage/replica_raftstorage.go, line 260 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7788#-KMVxA7VToZs5OZK4CXa:-KMeniH78G0vHZ_yG_8E:672457041) ([raw file](https://github.com/cockroachdb/cockroach/blob/20fa229c019e920bf16992edfb5e08f73a4efc79/storage/replica_raftstorage.go#L260)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> It's possible in edge cases when recovering from certain near-death experiences. For example, in a range on nodes A, B, and C, B dies, then some time later C dies (without any replica changes in between). B is revived, but C is unrecoverable. This range can recover if and only if A can send a snapshot to B. 
> 
> I can't come up with any situation in which this matters that doesn't involve multiple failures, so maybe it's not a situation we want to promise to handle, but there are cases where we could theoretically recover but this limit would prevent it.
</details>
Just to be careful, I've bumped it up to 2x split size.

---

*[storage/replica_raftstorage_test.go, line 73 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7788#-KMWEZfOpXrdihW9Xm6f:-KMXzYZOlesrDCL8MY6B:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/a428575fd30ea3d72c9dacc98b5e6ce4486d4d7c/storage/replica_raftstorage_test.go#L73)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> log the unexpected error
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7788)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7788#-:-KMyfb3BnsfmK0GoC83g:1417088721)*

**Pull request merged**
