### PR TITLE
*: replace internal executor root user override with node

### LINKED ISSUE #108146: upgrades: audit whether we use node vs root user to spawn upgrade jobs
During a customer escalation, we noticed that the upgrade jobs were run by root. If they're spawned by the root user, by setting `version`, this might be appropriate, but certainly for background-spawned upgrades `node` would be the correct user.

Jira issue: CRDB-30329

Epic CRDB-34100

### LINKED ISSUE #108810: sql: investigate and replace RootUserSessionDataOverride usages
`RootUserSessionDataOverride` runs a query with elevated root user privileges which is a potential security risk as the user running the query may not have the correct privileges without the override.

These should be replaced with either
1. `NoSessionDataOverride` if the query is being triggered by a user action. This should be run with the user's session.
2. `NodeUserSessionDataOverride` if the query is being run on behalf of the node itself. In this case, the node user also has elevated privileges and should be able to run the query.

Slack conversation: https://cockroachlabs.slack.com/archives/C0168LW5THS/p1692030154565489

Jira issue: CRDB-30649

### PR DESCRIPTION
**Pull request by rafiss**
The root user is not the right user to use for internal operations, since an end-user could use root themselves. For internal operations, we should use the node user to make it clear that the operation originated internally within CRDB.

fixes #108146
Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118735)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi, @herkolategan, @maryliag, @mgartner, @msbutler, @rafiss, and @renatolabs)

___
*[`-- commits` line 10 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/118735#-Npumy6xAALV5P_FEi7n):*
Before I look closer, do I understand it correctly that the desired end state is the following:
- all queries issued via the IE on behalf of the user (for example, all delegated queries like `SHOW TABLES`, etc) use `NoSessionDataOverride`
  - What about the case when delegated queries are issued by internal operations?
- all queries issued via the IE but on behalf of CRDB (for example, all queries for operating the jobs system) use `NodeUserSessionDataOverride`.

What about several layers of nestedness? I.e. `CREATE STATISTICS` statement by the user creates a job record (which IIUC inserts a row in the jobs table) - should that insert be attributed to the user?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118735)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi, @herkolategan, @maryliag, @mgartner, @msbutler, @renatolabs, and @yuzefovich)

___
*[`-- commits` line 10 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/118735#-Npumy6xAALV5P_FEi7n):*
> all queries issued via the IE on behalf of the user (for example, all delegated queries like `SHOW TABLES`, etc) use `NoSessionDataOverride`

this is not necessarily the desired goal; or at least, i think that goal is separate from this PR.

i do think it might be valid in many cases for a query issued by the IE on behalf of the user to still execute as the `node` user. an example is how `ALTER ROLE my_role WITH password = 'abc'` requires the internal executor to run `UPDATE system.users SET "hashedPassword" = xyz WHERE username = 'my_user'`. that internal query does require elevated privileges, and we don't want the end-user to have privileges on the system table.

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 1 of 58 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118735)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi, @herkolategan, @maryliag, @mgartner, @msbutler, @rafiss, and @renatolabs)

___
*[`-- commits` line 10 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/118735#-Npumy6xAALV5P_FEi7n):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

> all queries issued via the IE on behalf of the user (for example, all delegated queries like `SHOW TABLES`, etc) use `NoSessionDataOverride`

this is not necessarily the desired goal; or at least, i think that goal is separate from this PR.

i do think it might be valid in many cases for a query issued by the IE on behalf of the user to still execute as the `node` user. an example is how `ALTER ROLE my_role WITH password = 'abc'` requires the internal executor to run `UPDATE system.users SET "hashedPassword" = xyz WHERE username = 'my_user'`. that internal query does require elevated privileges, and we don't want the end-user to privileges on the system table.
</blockquote></details>

I see, ok. So this PR is automatic replacement of all existing `RootUser` usages with `NodeUser`? Should then #108810 be kept open after this change? IIUC item 1. from that ticket to possibly use `NoSessionDataOverride` in more places would still be relevant, no?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118735)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi, @herkolategan, @maryliag, @mgartner, @msbutler, @renatolabs, and @yuzefovich)

___
*[`-- commits` line 10 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/118735#-Npumy6xAALV5P_FEi7n):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I see, ok. So this PR is automatic replacement of all existing `RootUser` usages with `NodeUser`? Should then #108810 be kept open after this change? IIUC item 1. from that ticket to possibly use `NoSessionDataOverride` in more places would still be relevant, no?
</blockquote></details>

yes this PR was a purely mechanical find/replace.

good point; i will unlink #108810 and comment there about the case i mentioned

**Review by yuzefovich — APPROVED** [review]
:lgtm: Perhaps someone from @cockroachdb/sql-foundations should sign off too.

> Reviewed 57 of 58 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118735#-:-Npuypa6CRQAwg8TPSId:bu01abu)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @fqazi, @herkolategan, @maryliag, @mgartner, @msbutler, and @renatolabs)

**Comment by rafiss** [comment]
> We also actually have many usages of sessiondata.InternalExecutorOverride{User: username.RootUserName()} which is effectively the same thing that we should probably replace as part of this PR.

nice catch; done

**Review by yuzefovich — COMMENTED** [review]
There are a few more places where we might want to switch from `root` to `node`:
- in calls to `sql.NewInternalPlanner`
- in `newInternalExecutorWithTxn`
- maybe also in `RunPermanentUpgrades`.

> Reviewed 24 of 24 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118735#-:-NpvC0Fh5I60_C6TUYkT:b-arymur)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @fqazi, @herkolategan, @maryliag, @mgartner, @msbutler, @rafiss, and @renatolabs)

___
*[`pkg/sql/internal.go` line 883 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118735#-NpvC3hHDbHoBTM7p0WS:-NpvC3hHDbHoBTM7p0WT:b8qrboi) ([raw file](https://github.com/cockroachdb/cockroach/blob/f491e9f3f2014deda123ed1f867cb4e0169d48a8/pkg/sql/internal.go#L883)):*
> ```Go
> 	sd := ie.sessionDataStack.Top()
> 	if sd.User().Undefined() {
> 		o.User = username.RootUserName()
> ```

We probably want this to be `node` too.
___
*[`pkg/upgrade/upgrades/permanent_create_auto_config_runner_job.go` line 57 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/118735#-NpvCD2O6SgOypebdfqN:-NpvCD2O6SgOypebdfqO:blh3dnh) ([raw file](https://github.com/cockroachdb/cockroach/blob/34a400a321407a7ba27d03fba2d51fb03f740a15/pkg/upgrade/upgrades/permanent_create_auto_config_runner_job.go#L57)):*
> ```Go
> 			Progress:      jobspb.AutoConfigRunnerProgress{},
> 			CreatedBy:     &jobs.CreatedByInfo{Name: username.RootUser, ID: username.RootUserID},
> 			Username:      username.RootUserName(),
> ```

Perhaps this one should be `node` too? As well as in `createJobsMetricsPollingJob`.

**Review by rafiss — COMMENTED** [review]
nice finds. done

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118735#-:-NpvH_onBDGhwtXMt2Uj:b-tlcxps)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @fqazi, @herkolategan, @maryliag, @mgartner, @msbutler, and @renatolabs)

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 21 of 21 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118735)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @fqazi, @herkolategan, @maryliag, @mgartner, @msbutler, @rafiss, and @renatolabs)

___
*[`-- commits` line 24 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/118735#-NpvITT6D3nQI0UcCpP0):*
nit: perhaps we should remove the user argument from `NewInternalPlanner` and `newInternalPlanner` altogether since it looks like we should always use the node user? For example, looks like `NewInternalPlanner` in `backfillQueryIntoTable` still uses the root.
___
*[`pkg/sql/internal.go` line 883 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118735#-NpvC3hHDbHoBTM7p0WS:-NpvI2SR8V49jjr45rrw:bw5tho3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f491e9f3f2014deda123ed1f867cb4e0169d48a8/pkg/sql/internal.go#L883)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

We probably want this to be `node` too.
</blockquote></details>

nit: what about this one, in `maybeNodeSessionDataOverride`?
___
*[`pkg/sql/temporary_schema.go` line 266 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/118735#-NpvIs3x429Ka6zmwqj7:-NpvIs3x429Ka6zmwqj8:b-s5z2v2) ([raw file](https://github.com/cockroachdb/cockroach/blob/915e14967a7670b50813ba7c5792703716eb8b3b/pkg/sql/temporary_schema.go#L266)):*
> ```Go
> 	})
> 
> 	searchPath := sessiondata.DefaultSearchPathForUser(username.RootUserName()).WithTemporarySchemaName(sc.GetName())
> ```

nit: perhaps this one should be `node` too?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118735)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @fqazi, @herkolategan, @maryliag, @mgartner, @msbutler, @renatolabs, and @yuzefovich)

___
*[`-- commits` line 24 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/118735#-NpvITT6D3nQI0UcCpP0):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: perhaps we should remove the user argument from `NewInternalPlanner` and `newInternalPlanner` altogether since it looks like we should always use the node user? For example, looks like `NewInternalPlanner` in `backfillQueryIntoTable` still uses the root.
</blockquote></details>

hm, it looks like there are also many places where the actual client username is passed as the argument, so i don't think the parameter should be removed. i will look at the usages more closely though.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118735)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @fqazi, @herkolategan, @maryliag, @mgartner, @msbutler, @renatolabs, and @yuzefovich)

___
*[`pkg/sql/internal.go` line 883 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118735#-NpvC3hHDbHoBTM7p0WS:-Npz9Iyf1E2z8VtBbuS_:b-7ql1td) ([raw file](https://github.com/cockroachdb/cockroach/blob/f491e9f3f2014deda123ed1f867cb4e0169d48a8/pkg/sql/internal.go#L883)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: what about this one, in `maybeNodeSessionDataOverride`?
</blockquote></details>

fixed
___
*[`pkg/sql/temporary_schema.go` line 266 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/118735#-NpvIs3x429Ka6zmwqj7:-Npz9JyA5JOofONPzwaB:b-7ql1td) ([raw file](https://github.com/cockroachdb/cockroach/blob/915e14967a7670b50813ba7c5792703716eb8b3b/pkg/sql/temporary_schema.go#L266)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: perhaps this one should be `node` too?
</blockquote></details>

fixed

**Review by stevendanna — APPROVED** [review]
Thanks for picking this up!

**Comment by rafiss** [comment]
TFTRs!

bors r+

**Pull request merged**
