### PR TITLE
storage: use AmbientContext in StoreConfig, queues

### PR DESCRIPTION
**Pull request by RaduBerinde**
Part of #9807.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10039)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

Consider the various "this has N callers" comments optional.

---

Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[pkg/server/node.go, line 308 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-KUN1iEAZXMdcYo9NEVa:-KUN1iEAZXMdcYo9NEVb:b8vx9ol) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3c69babfdd814813c0a5f380999e5077d68e4c3/pkg/server/node.go#L308)):*
> ```Go
> 	var err error
> 	if id == 0 {
> 		allocCtx, span := n.AnnotateCtxWithSpan(context.TODO(), "alloc-node-id")
> ```

why not

```
ctx, span := n.AnnotateCtxWithSpan(ctx, "alloc-node-id")
```

---

*[pkg/server/node.go, line 562 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-KUN1tGucsHQwNek-ZC-:-KUN1tGucsHQwNek-ZC0:b-g1s115) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3c69babfdd814813c0a5f380999e5077d68e4c3/pkg/server/node.go#L562)):*
> ```Go
> // node's address is gossiped with node ID as the gossip key.
> func (n *Node) connectGossip() {
> 	ctx := n.AnnotateCtx(context.Background())
> ```

one caller that has a context

---

*[pkg/server/node.go, line 671 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-KUN21f2QvKIcxBc1mfw:-KUN21f2QvKIcxBc1mfx:bu5d0mm) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3c69babfdd814813c0a5f380999e5077d68e4c3/pkg/server/node.go#L671)):*
> ```Go
> 	return n.stores.VisitStores(func(store *storage.Store) error {
> 		if err := store.ComputeMetrics(tick); err != nil {
> 			ctx := n.AnnotateCtx(context.TODO())
> ```

surely you could do this just once outside the closure.

---

*[pkg/storage/client_test.go, line 115 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-KUMzH2GkP9DJJU9r0Kh:-KUMzH2HDkotNa14a2d0:b-if7q2u) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3c69babfdd814813c0a5f380999e5077d68e4c3/pkg/storage/client_test.go#L115)):*
> ```Go
> 	stopper *stop.Stopper,
> ) *storage.Store {
> 	rpcContext := rpc.NewContext(log.AmbientContext{}, &base.Config{Insecure: true}, clock, stopper)
> ```

this function is very odd. we have a `log.AmbientContext` here, then another one below passed to `storage.NewStores`, and a third stashed inside `storeCfg`. Is this really the pattern we want to follow? Fixing this is maybe not for this PR, but the situation seems nuts.

---

*[pkg/storage/helpers_test.go, line 168 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-KUMzgk1L5hR-Ynyf6GE:-KUMzgk1L5hR-Ynyf6GF:boj2w95) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3c69babfdd814813c0a5f380999e5077d68e4c3/pkg/storage/helpers_test.go#L168)):*
> ```Go
> 		return fmt.Errorf("%s: system config not yet available", s)
> 	}
> 	ctx := s.AnnotateCtx(context.TODO())
> ```

This method has one caller - care to just plumb the context?

---

*[pkg/storage/queue.go, line 219 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-KUMzyysO2Km-P96hTnp:-KUMzyytfwZtcY4e7Q-0:bspkcoj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3c69babfdd814813c0a5f380999e5077d68e4c3/pkg/storage/queue.go#L219)):*
> ```Go
> 
> 	ambient := store.cfg.AmbientCtx
> 	// Prepend [name] to logs.
> ```

remove this comment - doesn't seem useful =/

---

*[pkg/storage/queue.go, line 241 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-KUN-89Zr27JsFGRmScd:-KUN-89Zr27JsFGRmSce:b-tshic2) ([raw file](https://github.com/cockroachdb/cockroach/blob/511ded9ae509bb42438021a2427e283f7a8b5d09/pkg/storage/queue.go#L241)):*
> ```Go
> 	bq.processMu = new(syncutil.Mutex)
> 
> 	bq.ctx = context.TODO()
> ```

lol wat

---

*[pkg/storage/queue.go, line 554 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-KUN-YXn5w65UI0cDyaX:-KUN-YXn5w65UI0cDyaY:b-skq9ln) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3c69babfdd814813c0a5f380999e5077d68e4c3/pkg/storage/queue.go#L554)):*
> ```Go
> 	bq.failures.Inc(1)
> 
> 	ctx := bq.AnnotateCtx(context.TODO())
> ```

this method has two callers, both in this file. plumb?

---

*[pkg/storage/queue.go, line 691 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-KUN-cRqGHDcYpS7oPI2:-KUN-cRqGHDcYpS7oPI3:b-u42d2u) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3c69babfdd814813c0a5f380999e5077d68e4c3/pkg/storage/queue.go#L691)):*
> ```Go
> 		if err := bq.processReplica(repl, clock); err != nil {
> 			bq.failures.Inc(1)
> 			ctx := bq.AnnotateCtx(context.TODO())
> ```

one caller

---

*[pkg/storage/raft_log_queue.go, line 183 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-KUN-oiEH7HBM9deCPiz:-KUN-oiF1l3ki1EFbtny:b-dcwmxz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3c69babfdd814813c0a5f380999e5077d68e4c3/pkg/storage/raft_log_queue.go#L183)):*
> ```Go
> 	now hlc.Timestamp, r *Replica, _ config.SystemConfig,
> ) (shouldQ bool, priority float64) {
> 	ctx := rlq.AnnotateCtx(context.TODO())
> ```

4 callers (for all impls, afaict)

---

*[pkg/storage/store.go, line 1190 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-KUN0mGAOwbVeETzEI4F:-KUN0mGAOwbVeETzEI4G:bx9th17) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3c69babfdd814813c0a5f380999e5077d68e4c3/pkg/storage/store.go#L1190)):*
> ```Go
> // Replica.maybeGossipSystemConfig and Replica.maybeGossipNodeLiveness.
> func (s *Store) maybeGossipSystemData() error {
> 	ctx := s.AnnotateCtx(context.Background())
> ```

TODO? nothing async here.

---

*[pkg/storage/store.go, line 1643 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-KUN0rjDytkxbUImuL_T:-KUN0rjDytkxbUImuL_U:b-80z19o) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3c69babfdd814813c0a5f380999e5077d68e4c3/pkg/storage/store.go#L1643)):*
> ```Go
> 		// equivalence with newRng. See Store.splitTriggerPostCommit()
> 		if exRng != newRng {
> 			ctx := s.AnnotateCtx(context.Background())
> ```

TODO?

---

*[pkg/storage/store.go, line 1777 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-KUN0uegx1nk2SnNfgWI:-KUN0uegx1nk2SnNfgWJ:b-q497ky) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3c69babfdd814813c0a5f380999e5077d68e4c3/pkg/storage/store.go#L1777)):*
> ```Go
> 		return true
> 	case nil:
> 		panic(fmt.Sprintf("range=%d: placeholder not found", rngID))
> ```

loss of fidelity here; I think you still want to log the store (so you should keep the Fatalf and make a context.

---

*[pkg/storage/store.go, line 2852 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-KUN1AbZcsmwlDdPGiaH:-KUN1AbZcsmwlDdPGiaI:b63u3kb) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3c69babfdd814813c0a5f380999e5077d68e4c3/pkg/storage/store.go#L2852)):*
> ```Go
> 				// might have closed.
> 				if log.V(1) {
> 					ctx := s.AnnotateCtx(context.Background())
> ```

feels like this should be passed in (so should be TODO)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-:-KUN2IwIIZ6zKi83Ad1T:b-28x3oq)*

**Comment by RaduBerinde** [comment]
TFTR (and thanks for checking the callers!)

---

Review status: 10 of 25 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[pkg/server/node.go, line 308 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-KUN1iEAZXMdcYo9NEVa:-KUNCgKwNyfLDFwDg5_n:b51oj0g) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3c69babfdd814813c0a5f380999e5077d68e4c3/pkg/server/node.go#L308)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> why not
> 
> ```
> ctx, span := n.AnnotateCtxWithSpan(ctx, "alloc-node-id")
> ```
</details>
Done (except I used a different var name, the linter complains).

---

*[pkg/server/node.go, line 562 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-KUN1tGucsHQwNek-ZC-:-KUNExyU1jX5A-3fDOR8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3c69babfdd814813c0a5f380999e5077d68e4c3/pkg/server/node.go#L562)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> one caller that has a context
</details>
Done.

---

*[pkg/server/node.go, line 671 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-KUN21f2QvKIcxBc1mfw:-KUN9qXNMDmd5L2ZOiAg:b-lb3qft) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3c69babfdd814813c0a5f380999e5077d68e4c3/pkg/server/node.go#L671)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> surely you could do this just once outside the closure.
</details>
This is an error path so it shouldn't happen normally, I figured it's better to avoid the allocation in the normal path.

---

*[pkg/storage/client_test.go, line 115 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-KUMzH2GkP9DJJU9r0Kh:-KUNACgzb-v5ZPXZrgWq:bfakaql) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3c69babfdd814813c0a5f380999e5077d68e4c3/pkg/storage/client_test.go#L115)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this function is very odd. we have a `log.AmbientContext` here, then another one below passed to `storage.NewStores`, and a third stashed inside `storeCfg`. Is this really the pattern we want to follow? Fixing this is maybe not for this PR, but the situation seems nuts.
</details>
They should all be passed the same ambient, just a result of the incremental change. Fixed.

---

*[pkg/storage/helpers_test.go, line 168 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-KUMzgk1L5hR-Ynyf6GE:-KUNFVNa4JUtps2fWmiz:b-ea24vz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3c69babfdd814813c0a5f380999e5077d68e4c3/pkg/storage/helpers_test.go#L168)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> This method has one caller - care to just plumb the context?
</details>
This is testing code, we haven't really spent energy plumbing contexts through test code until we have a good usecase. The caller just uses `context.TODO()`s anyway.

---

*[pkg/storage/queue.go, line 219 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-KUMzyysO2Km-P96hTnp:-KUNFtGtsJ1ScX6FCSxW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3c69babfdd814813c0a5f380999e5077d68e4c3/pkg/storage/queue.go#L219)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> remove this comment - doesn't seem useful =/
</details>
Done.

---

*[pkg/storage/queue.go, line 241 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-KUN-89Zr27JsFGRmScd:-KUNFubZZCBh67Ni_KX8:b9c8kcj) ([raw file](https://github.com/cockroachdb/cockroach/blob/511ded9ae509bb42438021a2427e283f7a8b5d09/pkg/storage/queue.go#L241)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> lol wat
</details>
yes, that was my thought too. I probably screwed this up in one of those big changes.

---

*[pkg/storage/queue.go, line 554 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-KUN-YXn5w65UI0cDyaX:-KUNK7HU0T2zhXGv8b_G:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3c69babfdd814813c0a5f380999e5077d68e4c3/pkg/storage/queue.go#L554)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this method has two callers, both in this file. plumb?
</details>
Done.

---

*[pkg/storage/queue.go, line 691 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-KUN-cRqGHDcYpS7oPI2:-KUNK8Om0Ncu01trakoe:bvthpl8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3c69babfdd814813c0a5f380999e5077d68e4c3/pkg/storage/queue.go#L691)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> one caller
</details>
Testing code.

---

*[pkg/storage/raft_log_queue.go, line 183 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-KUN-oiEH7HBM9deCPiz:-KUNLBVQSHbqLMCGGyqN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3c69babfdd814813c0a5f380999e5077d68e4c3/pkg/storage/raft_log_queue.go#L183)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> 4 callers (for all impls, afaict)
</details>
Done.

---

*[pkg/storage/store.go, line 1190 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-KUN0mGAOwbVeETzEI4F:-KUNLF0-NfYlXatJ7R7i:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3c69babfdd814813c0a5f380999e5077d68e4c3/pkg/storage/store.go#L1190)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> TODO? nothing async here.
</details>
Done.

---

*[pkg/storage/store.go, line 1643 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-KUN0rjDytkxbUImuL_T:-KUNLgFGVAdW0HMUQryd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3c69babfdd814813c0a5f380999e5077d68e4c3/pkg/storage/store.go#L1643)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> TODO?
</details>
Done.

---

*[pkg/storage/store.go, line 1777 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-KUN0uegx1nk2SnNfgWI:-KUNLgeSl1EhhvQjPe37:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3c69babfdd814813c0a5f380999e5077d68e4c3/pkg/storage/store.go#L1777)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> loss of fidelity here; I think you still want to log the store (so you should keep the Fatalf and make a context.
</details>
Done.

---

*[pkg/storage/store.go, line 2852 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-KUN1AbZcsmwlDdPGiaH:-KUNLl4qUN6_C_9_2xAl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3c69babfdd814813c0a5f380999e5077d68e4c3/pkg/storage/store.go#L2852)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> feels like this should be passed in (so should be TODO)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-:-KUNLmatsVnyD-LsRzp6:b-rcmhod)*

**Comment by tamird** [comment]
Reviewed 19 of 19 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/storage/client_test.go, line 115 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-KUMzH2GkP9DJJU9r0Kh:-KUOEARE3udzFrZKlj7Z:bljchsr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3c69babfdd814813c0a5f380999e5077d68e4c3/pkg/storage/client_test.go#L115)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> They should all be passed the same ambient, just a result of the incremental change. Fixed.
</details>
`storeCfg` still has a separate one, right?

---

*[pkg/storage/helpers_test.go, line 168 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-KUMzgk1L5hR-Ynyf6GE:-KUOEdoQQ3qSiKt0awED:bg0ej26) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3c69babfdd814813c0a5f380999e5077d68e4c3/pkg/storage/helpers_test.go#L168)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> This is testing code, we haven't really spent energy plumbing contexts through test code until we have a good usecase. The caller just uses `context.TODO()`s anyway.
</details>
I agree about the practical aspect of plumbing test code, but this is an easy one, so why not set a precedent?

---

*[pkg/storage/queue.go, line 691 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-KUN-cRqGHDcYpS7oPI2:-KUOEUXT0SdiA7FZW-Fm:bqkvf7h) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3c69babfdd814813c0a5f380999e5077d68e4c3/pkg/storage/queue.go#L691)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Testing code.
</details>
Well, if it's testing code, it should probably be in helpers_test.go - also, it still seems better to allow the test to pass the context, but i feel less strongly about that.

---

*[pkg/storage/queue.go, line 485 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-KUOEM5mMMy0RBO4XSTg:-KUOEM5mMMy0RBO4XSTh:bysldv4) ([raw file](https://github.com/cockroachdb/cockroach/blob/2eeb37970c4bcf7ae9c168561b2c9c7e18f72c05/pkg/storage/queue.go#L485)):*
> ```Go
> // while calling this method.
> func (bq *baseQueue) processReplica(
> 	queueCtx context.Context, repl *Replica, clock *hlc.Clock,
> ```

why not `ctx`?

---

*[pkg/util/log/ambient_context.go, line 103 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-KUODns-se6Q37C4FMiJ:-KUODns0yqoq40XjtDIG:b-7decu2) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b41f83d19ce5733475d71cdee8e669e7da46514/pkg/util/log/ambient_context.go#L103)):*
> ```Go
> func (ac *AmbientContext) FinishEventLog() {
> 	ac.eventLog.finish()
> 	ac.eventLog = nil
> ```

how come?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/storage/client_test.go, line 115 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-KUMzH2GkP9DJJU9r0Kh:-KUOGJS0Wl0in7dEkGnZ:b-886gsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3c69babfdd814813c0a5f380999e5077d68e4c3/pkg/storage/client_test.go#L115)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> `storeCfg` still has a separate one, right?
</details>
Fixed

---

*[pkg/storage/helpers_test.go, line 168 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-KUMzgk1L5hR-Ynyf6GE:-KUOGmSFAWFAKNqcTcMf:boczkrz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3c69babfdd814813c0a5f380999e5077d68e4c3/pkg/storage/helpers_test.go#L168)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I agree about the practical aspect of plumbing test code, but this is an easy one, so why not set a precedent?
</details>
There are 1000 of easy ones, I'm trying to spend my time where it's more important.

---

*[pkg/storage/queue.go, line 485 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-KUOEM5mMMy0RBO4XSTg:-KUOFwyf5G288hsQheOP:b-s36ch1) ([raw file](https://github.com/cockroachdb/cockroach/blob/2eeb37970c4bcf7ae9c168561b2c9c7e18f72c05/pkg/storage/queue.go#L485)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> why not `ctx`?
</details>
see ~10 lines below

---

*[pkg/util/log/ambient_context.go, line 103 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-KUODns-se6Q37C4FMiJ:-KUOHNtWbpal7e2Fr5Rx:b92000s) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b41f83d19ce5733475d71cdee8e669e7da46514/pkg/util/log/ambient_context.go#L103)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> how come?
</details>
it wasn't right, it's a race to change it (in direct contradiction of the function comment)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/storage/helpers_test.go, line 168 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-KUMzgk1L5hR-Ynyf6GE:-KUPvecdz4IIAH9EcsSA:b-rpfnzs) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3c69babfdd814813c0a5f380999e5077d68e4c3/pkg/storage/helpers_test.go#L168)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> There are 1000 of easy ones, I'm trying to spend my time where it's more important.
</details>
Sure. The point I was making is that you're already here, and setting a precedent for others (and yourself) may be worthwhile.

---

*[pkg/storage/queue.go, line 485 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039#-KUOEM5mMMy0RBO4XSTg:-KUPvyTf7pSC1u24RZJ6:b-1lsg2s) ([raw file](https://github.com/cockroachdb/cockroach/blob/2eeb37970c4bcf7ae9c168561b2c9c7e18f72c05/pkg/storage/queue.go#L485)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> see ~10 lines below
</details>
Oh, both are used. Weird!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10039)*

**Pull request merged**
