### PR TITLE
sql/parser: fix the numeric tenant_spec grammar

### PR DESCRIPTION
**Pull request by knz**
Informs #95908.
Epic: CRDB-23559
Release note: None

### CODE REVIEW

**Review by cucaroach — APPROVED** [review]
:lgtm:  Thanks for fixing!

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98977#-:-NQuITO95CDCjLwIDcX6:b-moa209)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @stevendanna)

**Comment by knz** [comment]
bors r=cucaroach

**Comment by stevendanna** [comment]
Thanks for fixing this. It leaves me wondering though, how many of these other users of `d_expr` are incorrect?  For instance, the following also doesn't work:

```
demo@127.0.0.1:26257/movr> create tenant 'bar'::string;                                                                                                                                                           
invalid syntax: statement ignored: at or near ":": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
create tenant 'bar'::string
                   ^
demo@127.0.0.1:26257/movr> create tenant ('bar'::string);                                                                                                                                                         
CREATE TENANT

Time: 14ms total (execution 14ms / network 0ms)


```

**Comment by knz** [comment]
> how many of these other users of d_expr are incorrect? For instance, the following also doesn't work:

That is on purpose! And was the point of using d_expr to start with. We can't use a_expr "naked" in a larger SQL statement with other keywords after the expression.

For your particular example you'd write `CREATE TENANT ('foo'::string)`

**Comment by knz** [comment]
bors r=cucaroach

**Pull request merged**
