### PR TITLE
sql: add commands to command all jobs of a given job type

### LINKED ISSUE #68126: cdc, jobs: PAUSE ALL CHANGEFEEDS command
**Is your feature request related to a problem? Please describe.**

Users may wish to quickly stop all changefeeds, perhaps as a way to to reduce load in certain situations.

**Describe the solution you'd like**

A `PAUSE ALL CHANGEFEEDS` command or similar.

**Describe alternatives you've considered**

Currently, this is done via [PAUSE JOB(S)](https://www.cockroachlabs.com/docs/stable/pause-job.html). This requires multiple steps, such as looking up the job ids.

A query like this is better: `PAUSE JOBS (SELECT job_id FROM [SHOW JOBS] WHERE job_type='CHANGEFEED' AND status IN ('running'))` (h/t @adityamaru)

`PAUSE ALL CHANGEFEEDS` _could_ be implemented as an alias/rewrite of the above, but that would be up to the implementer.

Epic CRDB-9106

### PR DESCRIPTION
**Pull request by samiskin**
Resolves https://github.com/cockroachdb/cockroach/issues/68126

Allow applying commands to all jobs of a given type

Users may wish to quickly stop all jobs of a given type such as changefeeds, perhaps as a way to to reduce load in certain situations.  This was previously already possible via something like 
```
PAUSE JOBS (SELECT job_id FROM [SHOW JOBS] WHERE job_type='CHANGEFEED' AND status IN ('running'))
```
however this is not ergonomic and we can add some smarts around which job statuses to run against and we can avoid `SHOW JOBS` with `pb_to_json`.

This change allows Pause, Resume, and Cancel commands to be applied to any Backup, Import, Restore, or Changefeed jobs via the SQL query `<Command> ALL <JobType> JOBS`.

Examples: `PAUSE ALL CHANGEFEED JOBS`, or `CANCEL ALL BACKUP JOBS`

Release justification: Low risk UX improvement to jobs management that
has been requested by customers, category 4

Release note (sql change):
There are now new job control statements allowing operator to manipulate
all jobs of specific type: `<Command> ALL <JobType> JOBS`.  Supports
CHANGEFEED, BACKUP, IMPORT and RESTORE jobs.  For example: `PAUSE ALL
CHANGEFEED JOBS`.

### CODE REVIEW

**Comment by samiskin** [comment]
@miretskiy Right now pause/resume/cancel with Changefeed jobs works using `pb_to_json`.

The remaining parts are:
1. I structured the `delegateJobControl` as it taking a `ControlJobsDelegate` struct where if you provide a `Schedule` value it uses that, otherwise if you put a `Type` value it uses that.  Ideally I'd like to structure this such that the type system to enforce that "you either put a command and schedule, or you put a command and type", but I'm uncertain as to the best way to do this.
2. This currently doesn't work with the other jobs since they end up just looping over:
```
I210825 15:25:32.533554 2149 jobs/adopt.go:247  [-] 449  job 687586450244141057: resuming execution
I210825 15:25:32.534218 2151 jobs/registry.go:1182  [n1] 452  IMPORT job 687586450212257793: stepping through state reverting with error: <nil>
E210825 15:25:32.535229 2048 jobs/adopt.go:410  [n1] 457  job 687586450244141057: adoption completed with error job 687586450244141057: has StatusFailed but no error was provided
```

Will likely need help debugging that, not sure if I'm missing some necessary parameters / need to mock out constructors in a different way in order to create a proper job of those types that will continue running

**Review by miretskiy — CHANGES_REQUESTED** [review]
This is very nice.  Mostly minor nits.  Some tests need to be updated.

> Reviewed 5 of 13 files at r1, 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69314#-:-MhzTVQREx5ohpTes-3R:b-pgka3h)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @samiskin)

___
*[-- commits, line 19 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69314#-MhzQFwE2LSUUrBaxFvr):*
Linter will complain about this description.

You need to add
"Release Justification:"
Something like:
```
Release Justification: Low danger, UX improvement to jobs management.
```

You also need to add Release Notes:

```
Release Notes: Adds new job control statements allowing operator to manipulate all
jobs of specific type: `<Command> EVERY <JobType> JOB`.  Supports CHANGEFEED, BACKUP, IMPORT
and RESTORE jobs.  For example: `PAUSE EVERY CHANGEFEED JOB`.
```
___
*[pkg/jobs/schedule_control_test.go, line 451 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69314#-MhzT4NH5KSnMyedNEJq:-MhzT4NH5KSnMyedNEJr:bc7m37g) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef3d30c5518a883cd6f2b2318f04e44697ce0769/pkg/jobs/schedule_control_test.go#L451)):*
> ```Go
> 		}
> 	}
> ```

nit: extra \n
___
*[pkg/jobs/jobstest/utils.go, line 25 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69314#-MhzS-UHB6e8Ni_IPku0:-MhzS-UHB6e8Ni_IPku1:b-d9iksq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef3d30c5518a883cd6f2b2318f04e44697ce0769/pkg/jobs/jobstest/utils.go#L25)):*
> ```Go
> // EnvTablesType tells JobSchedulerTestEnv whether to use the system tables,
> // or to use test tables.  System tables such as system.jobs may be affected
> // by the system, while test tables are isolated versions
> ```

nit: this is probably an unrelated change.  But I guess it's fine.
___
*[pkg/sql/delegate/job_control.go, line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69314#-MhzTIDh4IKtzg9Myj23:-MhzTIDh4IKtzg9Myj24:b-twtxtn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef3d30c5518a883cd6f2b2318f04e44697ce0769/pkg/sql/delegate/job_control.go#L27)):*
> ```Go
> type ControlJobsDelegate struct {
> 	Schedules *tree.Select
> 	Type      *tree.JobType
> ```

comment that only one of schedules/type should be non nil.
___
*[pkg/sql/delegate/job_control.go, line 85 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69314#-MhzSKdd3cPBymVbf-we:-MhzSKdd3cPBymVbf-wf:b-pjw1gw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef3d30c5518a883cd6f2b2318f04e44697ce0769/pkg/sql/delegate/job_control.go#L85)):*
> ```Go
> 	) SELECT id FROM decoded WHERE cf IS NOT null AND status IN (%s)
> )`
> 		log.Infof(context.Background(), "cmd=%q", fmt.Sprintf(queryStrFormat, tree.JobCommandToStatement[stmt.Command], protoNameForType[*stmt.Type], filterClause))
> ```

extra log statement.
___
*[pkg/sql/delegate/job_control.go, line 89 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69314#-MhzSQ3a7lOgQsvw20La:-MhzSQ3b5RaOLVujpwDB:b-fyrct5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef3d30c5518a883cd6f2b2318f04e44697ce0769/pkg/sql/delegate/job_control.go#L89)):*
> ```Go
> 	}
> 
> 	return parse(fmt.Sprintf(`%s JOBS SELECT id FROM system.jobs`, tree.JobCommandToStatement[stmt.Command]))
> ```

That's interesting.  Which cases was this general fallback supposed to catch?
___
*[pkg/sql/parser/sql.y, line 6192 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69314#-MhzRH7W0OvLGkyWirtK:-MhzRH7W0OvLGkyWirtL:bqsecf9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef3d30c5518a883cd6f2b2318f04e44697ce0769/pkg/sql/parser/sql.y#L6192)):*
> ```Yacc
>     $$.val = &tree.ControlJobsOfType{Type: $3.jobType(), Command: tree.PauseJob}
>   }
> | PAUSE EVERY error // SHOW HELP: PAUSE EVERY JOB
> ```

Very nice.  Usually, we modifying sql.y, you also need to update some of the SQL parse tests.
Currently, this is done w/ data driven tests.
See `pkg/sql/parser/testdata/control_job` and extend that file to support new control statements.
___
*[pkg/sql/sem/tree/run_control.go, line 144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69314#-MhtJqMYL7AuJ3AUn6pr-r1-144:-MhzRocCDXAymaf_GnFp:b-ujig40) ([raw file](https://github.com/cockroachdb/cockroach/blob/313975dc92791281e5881ba869bb17a87fdce6a3/pkg/sql/sem/tree/run_control.go#L144)):*
<details><summary><i>Previously, samiskin (Shiranka Miskin) wrote…</i></summary><blockquote>

Right now `ControlJobsOfType` is basically "Control jobs based on the job_type field as described in `SHOW JOBS`", and assuming that the `details` field of `jobs.proto` is what maps to this `job_type`, then schedule isn't a possibility there, and to me "JobsOfType" mapping to "job_type in [SHOW JOBS]" makes sense.

To me
```go
type ControlAllJobs struct {
	Type    JobType
	Command JobCommand
}
```
just looks strange since it isn't really all jobs if it requires a type parameter
</blockquote></details>

I'll buy that.

**Review by samiskin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69314)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @samiskin)

___
*[pkg/sql/delegate/job_control.go, line 89 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69314#-MhzSQ3a7lOgQsvw20La:-Mi1xWVYB7HHq9g2Pqy4:b-6dmxi7) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef3d30c5518a883cd6f2b2318f04e44697ce0769/pkg/sql/delegate/job_control.go#L89)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

That's interesting.  Which cases was this general fallback supposed to catch?
</blockquote></details>

I just put this in cause I didn't like the function not handling something that is possible to pass in.  It shouldn't ever happen.  I could also error or no-op, but I just went this way cause it seemed like an intuitive result, where Type and Schedule are like filters, so without them it just operates on all of them.

**Review by miretskiy — APPROVED** [review]
Let's also update PR description.  I know you updated your commit description; but once PR is created, that update is not reflected in PR description -- you have to do it manually.

Congrats on your first :lgtm:

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69314)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @miretskiy and @samiskin)

___
*[pkg/sql/delegate/job_control.go, line 81 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69314#-Mi2K_oJ8f8F6gCi6rRV:-Mi2K_oJ8f8F6gCi6rRW:bnsytdp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f8d5c12594857810f3a1c6fc95f1a47c3fb3c75/pkg/sql/delegate/job_control.go#L81)):*
> ```
> 	WITH DECODED AS (
> 		SELECT id, status, crdb_internal.pb_to_json('cockroach.sql.jobs.jobspb.Payload', payload)->'%s' AS cf FROM system.jobs
> 	) SELECT id FROM decoded WHERE cf IS NOT null AND status IN (%s)
> ```
my first nit was that `DECODED` shouldn't be capitalized by my follow-up nit is that this CTE doesn't feel justified. What about:
```sql
SELECT id
  FROM (
        SELECT id,
               status,
               (
                crdb_internal.pb_to_json(
                  'cockroach.sql.jobs.jobspb.Payload',
                  payload
                )->'%s'
               ) IS NOT NULL AS correct_type
          FROM system.jobs
         WHERE status IN (%s)
       )
 WHERE correct_type;
```
___
*[pkg/sql/parser/sql.y, line 6061 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69314#-Mi2JVPBB8ZDGoTlUSkU:-Mi2JVPBB8ZDGoTlUSkV:b-mj4cxq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f8d5c12594857810f3a1c6fc95f1a47c3fb3c75/pkg/sql/parser/sql.y#L6061)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>   CHANGEFEED { $$.val = tree.TypeChangefeed }
>   | IMPORT { $$.val = tree.TypeImport }
>   | BACKUP { $$.val = tree.TypeBackup }
>   | RESTORE { $$.val = tree.TypeRestore }
> ```
</details>

This feels heavy to me. Sure it lets you return an error at parse time, but I'm not convinced it's worth the weight. My preference is that we just make this a string in the AST and look up the type mapping from jobspb in the sql layer. Thoughts?

Advantages of doing it hear are that it might deal with capitalization things (though we should test that) and normalizing the statements.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69314)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @miretskiy, and @samiskin)

___
*[pkg/sql/parser/sql.y, line 6061 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69314#-Mi2JVPBB8ZDGoTlUSkU:-Mi2MKwyBY6fgWCLriV9:biptirh) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f8d5c12594857810f3a1c6fc95f1a47c3fb3c75/pkg/sql/parser/sql.y#L6061)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
>   CHANGEFEED { $$.val = tree.TypeChangefeed }
>   | IMPORT { $$.val = tree.TypeImport }
>   | BACKUP { $$.val = tree.TypeBackup }
>   | RESTORE { $$.val = tree.TypeRestore }
> ```
This feels heavy to me. Sure it lets you return an error at parse time, but I'm not convinced it's worth the weight. My preference is that we just make this a string in the AST and look up the type mapping from jobspb in the sql layer. Thoughts?

Advantages of doing it hear are that it might deal with capitalization things (though we should test that) and normalizing the statements. 
</blockquote></details>

There are advantages to using these... Like `??` completion on command line.
SQL also deal with capitalization.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69314)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @miretskiy, and @samiskin)

___
*[pkg/sql/parser/sql.y, line 6061 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69314#-Mi2JVPBB8ZDGoTlUSkU:-Mi2MdsE5y2utsZ6ywbq:b-o7q7sh) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f8d5c12594857810f3a1c6fc95f1a47c3fb3c75/pkg/sql/parser/sql.y#L6061)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

There are advantages to using these... Like `??` completion on command line.
SQL also deal with capitalization.
</blockquote></details>

Also, none of this introduces extra statements.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69314)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @miretskiy, and @samiskin)

___
*[pkg/sql/parser/sql.y, line 6061 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69314#-Mi2JVPBB8ZDGoTlUSkU:-Mi2NIY0E8QwwXGTdiYP:b-7wye95) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f8d5c12594857810f3a1c6fc95f1a47c3fb3c75/pkg/sql/parser/sql.y#L6061)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Also, none of this introduces extra statements.
</blockquote></details>

Looks like it doesn't complete "CHANGEFEED|}BACKUP", etc... I guess, @samiskin can play w/ help messages a bit..

**Review by ajwerner — COMMENTED** [review]
This change relates intimately to https://github.com/cockroachdb/cockroach/issues/68896. I wonder if we should pull the trigger on that change and get it into this release. If we did that, we could simply this PR and make it more efficient. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69314#-:-Mi2NXxx4bg1wgqXORZP:b-i515m3)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @miretskiy and @samiskin)

___
*[pkg/sql/parser/sql.y, line 6061 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69314#-Mi2JVPBB8ZDGoTlUSkU:-Mi2NHiL5N_ErZC8uppZ:b3gw1xj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f8d5c12594857810f3a1c6fc95f1a47c3fb3c75/pkg/sql/parser/sql.y#L6061)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Also, none of this introduces extra statements.
</blockquote></details>

I agree that none of it introduces extra statements.

**Review by miretskiy — APPROVED** [review]
> Reviewed 7 of 19 files at r7, 3 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69314)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @miretskiy and @samiskin)

___
*[pkg/sql/parser/testdata/control_job, line 607 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/69314#-Mj-liS_0OzfOUrpKMSh:-Mj-liS_0OzfOUrpKMSi:bolc304) ([raw file](https://github.com/cockroachdb/cockroach/blob/718925adea98b0dbd4de016e6ff86527b75de6c9/pkg/sql/parser/testdata/control_job#L607)):*
> ```
> PAUSE ALL JOBS
>               ^
> HINT: try \h PAUSE ALL JOBS
> ```

one more test for `PAUSE ALL blah JOBS`?

**Review by samiskin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69314)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @miretskiy)

___
*[-- commits, line 19 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69314#-MhzQFwE2LSUUrBaxFvr):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Linter will complain about this description.

You need to add
"Release Justification:"
Something like:
```
Release Justification: Low danger, UX improvement to jobs management.
```

You also need to add Release Notes:

```
Release Notes: Adds new job control statements allowing operator to manipulate all
jobs of specific type: `<Command> EVERY <JobType> JOB`.  Supports CHANGEFEED, BACKUP, IMPORT
and RESTORE jobs.  For example: `PAUSE EVERY CHANGEFEED JOB`.
```
</blockquote></details>

Done.
___
*[pkg/jobs/jobstest/utils.go, line 25 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69314#-MhzS-UHB6e8Ni_IPku0:-Mj-lKWt3NfAKMuXLVPu:bb77u1k) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef3d30c5518a883cd6f2b2318f04e44697ce0769/pkg/jobs/jobstest/utils.go#L25)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

nit: this is probably an unrelated change.  But I guess it's fine.
</blockquote></details>

Yeah
___
*[pkg/sql/delegate/job_control.go, line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69314#-MhzTIDh4IKtzg9Myj23:-Mj19lqe5BzuSB7-EyfT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef3d30c5518a883cd6f2b2318f04e44697ce0769/pkg/sql/delegate/job_control.go#L27)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

comment that only one of schedules/type should be non nil.
</blockquote></details>

Done.
___
*[pkg/sql/delegate/job_control.go, line 85 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69314#-MhzSKdd3cPBymVbf-we:-Mj1As-V1zGOQzX6-QiR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef3d30c5518a883cd6f2b2318f04e44697ce0769/pkg/sql/delegate/job_control.go#L85)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

extra log statement.
</blockquote></details>

Done.
___
*[pkg/sql/delegate/job_control.go, line 88 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69314#-MhtJqMYL7AuJ3AUn6pp-r4-88:-Mj1AtII1tXyCZjNv3Ow:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c32cb7c397bc506e05ab3edf550fbb61ce3abd65/pkg/sql/delegate/job_control.go#L88)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

If this branch "should not happen", then returning `nil, errors.AssertionFailedf("....")` is appropriate.
</blockquote></details>

Done.
___
*[pkg/sql/delegate/job_control.go, line 81 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69314#-Mi2K_oJ8f8F6gCi6rRV:-Mj19qN2BVM_CEJ4V4Zd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f8d5c12594857810f3a1c6fc95f1a47c3fb3c75/pkg/sql/delegate/job_control.go#L81)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	WITH DECODED AS (
> 		SELECT id, status, crdb_internal.pb_to_json('cockroach.sql.jobs.jobspb.Payload', payload)->'%s' AS cf FROM system.jobs
> 	) SELECT id FROM decoded WHERE cf IS NOT null AND status IN (%s)
> ```
my first nit was that `DECODED` shouldn't be capitalized by my follow-up nit is that this CTE doesn't feel justified. What about:
```sql
SELECT id
  FROM (
        SELECT id,
               status,
               (
                crdb_internal.pb_to_json(
                  'cockroach.sql.jobs.jobspb.Payload',
                  payload
                )->'%s'
               ) IS NOT NULL AS correct_type
          FROM system.jobs
         WHERE status IN (%s)
       )
 WHERE correct_type;
```

</blockquote></details>

Done.
___
*[pkg/sql/delegate/job_control.go, line 88 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69314#-MhtJqMYL7AuJ3AUn6pp-r5-88:-Mj1Au8l9OK5h0W9sqdT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f8d5c12594857810f3a1c6fc95f1a47c3fb3c75/pkg/sql/delegate/job_control.go#L88)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Let's use `errors.AssertionFailedf` -- this error "shouldn't" happen -- it's an assertion failure.
</blockquote></details>

Done.
___
*[pkg/sql/parser/sql.y, line 6192 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69314#-MhzRH7W0OvLGkyWirtK:-Mj1Ayns5CRKJwYTuibl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef3d30c5518a883cd6f2b2318f04e44697ce0769/pkg/sql/parser/sql.y#L6192)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Very nice.  Usually, we modifying sql.y, you also need to update some of the SQL parse tests.
Currently, this is done w/ data driven tests.
See `pkg/sql/parser/testdata/control_job` and extend that file to support new control statements.
</blockquote></details>

Done.
___
*[pkg/sql/parser/sql.y, line 6061 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69314#-Mi2JVPBB8ZDGoTlUSkU:-Mj1AxpT72pG3r6jO4BZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f8d5c12594857810f3a1c6fc95f1a47c3fb3c75/pkg/sql/parser/sql.y#L6061)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I agree that none of it introduces extra statements. 
</blockquote></details>

Done.
___
*[pkg/sql/parser/sql.y, line 773 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69314#-MhtJqMYL7AuJ3AUn6pq-r6-773:-Mj1Aw7BDsZgupKqRght:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a487aab6a0dac75f8d95df8604037e660700208a/pkg/sql/parser/sql.y#L773)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I think @samiskin will switch it to ALL.
</blockquote></details>

Done.
___
*[pkg/sql/parser/testdata/control_job, line 553 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69314#-Mi22WNFk6xCc_HweB_9-r5-553:-Mj1B0UP8OY34_CzIe6j:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f8d5c12594857810f3a1c6fc95f1a47c3fb3c75/pkg/sql/parser/testdata/control_job#L553)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Let's also add error test?
```
error
PAUSE EVERY unsupported JOB
---
```
</blockquote></details>

Done.
___
*[pkg/sql/parser/testdata/control_job, line 607 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/69314#-Mj-liS_0OzfOUrpKMSh:-Mj1B0mc8repn7gOtcqh:by2rd3t) ([raw file](https://github.com/cockroachdb/cockroach/blob/718925adea98b0dbd4de016e6ff86527b75de6c9/pkg/sql/parser/testdata/control_job#L607)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

one more test for `PAUSE ALL blah JOBS`?
</blockquote></details>

This isn't a parse error anymore since we don't have the types as part of sql.y anymore.  I added a test to `TestJobControlByType` to cover this instead.
___
*[pkg/sql/sem/tree/run_control.go, line 144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69314#-MhtJqMYL7AuJ3AUn6pr-r1-144:-Mj1BAo952zmlkca5psB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/313975dc92791281e5881ba869bb17a87fdce6a3/pkg/sql/sem/tree/run_control.go#L144)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I'll buy that.
</blockquote></details>

Done.
___
*[pkg/jobs/schedule_control_test.go, line 386 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69314#-MhtJqMYL7AuJ3AUn6pn-r1-386:-Mj1613t5kuK52jfMEYE:b-c3mq8x) ([raw file](https://github.com/cockroachdb/cockroach/blob/313975dc92791281e5881ba869bb17a87fdce6a3/pkg/jobs/schedule_control_test.go#L386)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

const ?
</blockquote></details>

Not sure what you were referring to here, it looks like I can't make `allJobTypes` a const since its an array.

**Comment by ajwerner** [comment]
See https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages for the issue/commit style guide.

**Pull request merged**
