### PR TITLE
kv: handle error from Stopper.RunAsyncTask

### PR DESCRIPTION
**Pull request by petermattis**
Follow-up to #18205

### CODE REVIEW

**Comment by benesch** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/kv/transport_race.go, line 111 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18213#-KtHlz8ClAgd7RnOp4Ji:-KtHlz8ClAgd7RnOp4Jj:bqxc02o) ([raw file](https://github.com/cockroachdb/cockroach/blob/6143cb0438873c6152ac6dcec58f31e6395da004/pkg/kv/transport_race.go#L111)):*
> ```Go
> 			}); err != nil {
> 			// Failed to start async task, reset our state.
> 			atomic.StoreInt32(&running, 0)
> ```

This doesn't need to return the error?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18213)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/kv/transport_race.go, line 111 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18213#-KtHlz8ClAgd7RnOp4Ji:-KtHrcLkcm72AtrVtn9j:b1omupo) ([raw file](https://github.com/cockroachdb/cockroach/blob/6143cb0438873c6152ac6dcec58f31e6395da004/pkg/kv/transport_race.go#L111)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

This doesn't need to return the error?
</blockquote></details>

Nope. The goroutine above is completely unnecessary for correctness and is trying to tickle rare data races.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18213)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18213#-:-KtHvE-6t6wCf-QRmYya:bnfp4nl)*

**Comment by benesch** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/kv/transport_race.go, line 111 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18213#-KtHlz8ClAgd7RnOp4Ji:-KtHux2FWK77cvs_EiwX:b5rn2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/6143cb0438873c6152ac6dcec58f31e6395da004/pkg/kv/transport_race.go#L111)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nope. The goroutine above is completely unnecessary for correctness and is trying to tickle rare data races.
</blockquote></details>

Ack. In general I worry that someone could break these CI-only code paths when the errors are swallowed without anyone noticing, but in this case if `stopper.RunAsyncTask` gets broken we'll notice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18213#-:-KtHucbTeh6j-MyOYWLA:bnfp4nl)*

**Comment by benesch** [comment]
(And thanks for fixing this!)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18213#-:-KtHvXRk4oyC6G66Ypt6:bu7571z)*

**Pull request merged**
