### PR TITLE
changefeedccl: add metric tracking tables watched

### LINKED ISSUE #118379: changefeedccl: add metric tables_watched
Add a metric changefeed_tables_watched, that takes the number of tables watched across all changefeeds and aggregates them together. We would expect this number to always be larges than num_changefeeds, since each changefeed watches at least one table. 

We may want to change the name if split column tables are counted as multiple "watched tables" even though they are logically one table.

This is important for the cloud 2.0 work and should be backported.

### PR DESCRIPTION
**Pull request by rharding6373**
This PR adds a new metric, changefeed.watched_targets, which tracks the number of unique tables watched by all changefeeds. If a table is tracked in multiple feeds, it is only counted once.

Epic: none
Fixes: #118379

Release note (enterprise change): Adds a new metric, changefeed.watched_targets, which tracks the number of unique tables watched by all changefeeds. Note that a table remains watched even if a changefeed is paused, and only becomes unwatched if the changefeed is altered to remove the table (the changefeed must be resumed), is canceled, or fails.

### CODE REVIEW

**Review by andyyang890 — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119391)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @amruss, @jayshrivastava, @rharding6373, and @wenyihu6)

___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NsMP_-J5ZJbm1_U7I4p):*
nit: maybe we should say "number of unique tables"
___
*[`pkg/ccl/changefeedccl/changefeed_stmt.go` line 313 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NsMQIAK7PT5UVYfQJ3a:-NsMQIAK7PT5UVYfQJ3b:bay9jhe) ([raw file](https://github.com/cockroachdb/cockroach/blob/23bd1be88b8440af72fd20773efd9305be388f73/pkg/ccl/changefeedccl/changefeed_stmt.go#L313)):*
> ```Go
> 
> 		logChangefeedCreateTelemetry(ctx, jr, changefeedStmt.Select != nil)
> 		err = func() error {
> ```

Maybe move this code into a named helper function? Especially given that it's more or less repeated verbatim below
___
*[`pkg/ccl/changefeedccl/changefeed_stmt.go` line 1497 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NsMRY_tBIpLqQw0KsJ_:-NsMRY_tBIpLqQw0KsJa:b-noiesz) ([raw file](https://github.com/cockroachdb/cockroach/blob/23bd1be88b8440af72fd20773efd9305be388f73/pkg/ccl/changefeedccl/changefeed_stmt.go#L1497)):*
> ```Go
> 	}
> 
> 	return func() error {
> ```

nit: maybe put this in an `if err := ...; err != nil { ... }` and still have the `return nil` at the end of the function, would make it a bit easier to insert things after this function (if needed) in the future
___
*[`pkg/ccl/changefeedccl/metrics.go` line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NsMO-Uo5INIm3MySTm0:-NsMLzStArrQFbvT-0DD:bjrlect) ([raw file](https://github.com/cockroachdb/cockroach/blob/23bd1be88b8440af72fd20773efd9305be388f73/pkg/ccl/changefeedccl/metrics.go#L165)):*
> ```Go
> 		resolved    map[int64]hlc.Timestamp
> 		checkpoint  map[int64]hlc.Timestamp
> 		targets     map[int]int64
> ```

Could you add comments documenting what these fields store?
___
*[`pkg/ccl/changefeedccl/metrics.go` line 229 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NsMNZc21lArFvWjV0Hz:-NsMNZc21lArFvWjV0I-:b-mfhjk0) ([raw file](https://github.com/cockroachdb/cockroach/blob/23bd1be88b8440af72fd20773efd9305be388f73/pkg/ccl/changefeedccl/metrics.go#L229)):*
> ```Go
> // WatchedTargets metrics if this is the first target with this id.
> // Requires m.mu to be locked.
> func (m *sliMetrics) incrTargetLocked(id int) {
> ```

nit: maybe rename to `incTargetLocked` to match the `Gauge` API
___
*[`pkg/ccl/changefeedccl/metrics.go` line 240 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NsMNc324yVE97BjMA8E:-NsMNc324yVE97BjMA8F:b-8vuhi4) ([raw file](https://github.com/cockroachdb/cockroach/blob/23bd1be88b8440af72fd20773efd9305be388f73/pkg/ccl/changefeedccl/metrics.go#L240)):*
> ```Go
> // WatchedTargets metric if this was the last target with this id.
> // Requires m.mu to be locked.
> func (m *sliMetrics) decrTargetLocked(id int) {
> ```

nit: maybe rename to `decTargetLocked` to match the `Gauge` API
___
*[`pkg/ccl/changefeedccl/metrics.go` line 886 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NsMPj_LAHLyRAc_2vm9:-NsMPj_LAHLyRAc_2vmA:b-o7psxj) ([raw file](https://github.com/cockroachdb/cockroach/blob/23bd1be88b8440af72fd20773efd9305be388f73/pkg/ccl/changefeedccl/metrics.go#L886)):*
> ```Go
> 	metaChangefeedWatchedTargets := metric.Metadata{
> 		Name:        "changefeed.watched_targets",
> 		Help:        "Targets watched by all feeds",
> ```

nit: maybe we should clarify that it's the number of "unique targets"
___
*[`pkg/ccl/changefeedccl/helpers_test.go` line 1379 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NsMPFoU-OV-kiL-M-fs:-NsMPFoU-OV-kiL-M-ft:b-i5gof4) ([raw file](https://github.com/cockroachdb/cockroach/blob/23bd1be88b8440af72fd20773efd9305be388f73/pkg/ccl/changefeedccl/helpers_test.go#L1379)):*
> ```Go
> }
> 
> func waitForChangefeedRunning(t *testing.T, sli *sliMetrics, targetCount int64) {
> ```

nit: maybe rename to something like `waitForChangefeedRunningCount`
___
*[`pkg/ccl/changefeedccl/metrics_test.go` line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NsMT5gL77OlgYIM5B46:-NsMT5gL77OlgYIM5B47:bpavl5m) ([raw file](https://github.com/cockroachdb/cockroach/blob/23bd1be88b8440af72fd20773efd9305be388f73/pkg/ccl/changefeedccl/metrics_test.go#L23)):*
> ```Go
> )
> 
> func TestRunningAndTables(t *testing.T) {
> ```

nit: maybe rename to `TestRunningCountAndWatchedTargets` since those are the only two metrics being tested?
___
*[`pkg/ccl/changefeedccl/metrics_test.go` line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NsMSyPuCx3Qfn62XVnj:-NsMSyPuCx3Qfn62XVnk:b-7mbbk8) ([raw file](https://github.com/cockroachdb/cockroach/blob/23bd1be88b8440af72fd20773efd9305be388f73/pkg/ccl/changefeedccl/metrics_test.go#L96)):*
> ```Go
> 		require.EqualValues(t, 2, sliMetric.WatchedTargets.Value())
> 
> 		// The running count should be decremented when the job is paused, but the
> ```

Should we maybe add an assertion for the running count being 0?

**Review by wenyihu6 — COMMENTED** [review]
Looks great! Thanks for adding these metrics! They will be really useful for escalations.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-:-NsOhh8J3IVxWBPWLUxv:bd7g0iy)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @amruss, @jayshrivastava, and @rharding6373)

___
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NsOaioy5lm7pHGAyNcY):*
nit: i think we only remove the watched targets if the job has failed or been canceled. Could you add a note here clarifying how they change and they won't be removed if they are paused?
___
*[`pkg/ccl/changefeedccl/changefeed_stmt.go` line 316 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NsOc5-PAj8ILSv82fWr:-NsOc5-PAj8ILSv82fWs:bt2vso) ([raw file](https://github.com/cockroachdb/cockroach/blob/23bd1be88b8440af72fd20773efd9305be388f73/pkg/ccl/changefeedccl/changefeed_stmt.go#L316)):*
> ```Go
> 			metrics := p.ExecCfg().JobRegistry.MetricsStruct().Changefeed.(*Metrics)
> 			pl := sj.Payload()
> 			cf := pl.GetDetails().(*jobspb.Payload_Changefeed).Changefeed
> ```

It seems there's a potential for `pl.GetDetails()` to return nil, which could lead to a nil pointer dereference when accessing Changefeed here. But I [notice](https://github.com/rharding6373/cockroach/blob/b45e639d5dfe141df152e3b0a3b9f6512cd1aa14/pkg/ccl/streamingccl/streamproducer/event_stream.go#L519)  that other parts of the code also directly access its fields, so maybe this is not possible. 
___
*[`pkg/ccl/changefeedccl/changefeed_stmt.go` line 317 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NsOeKW32eaI-mA1_tmY:-NsOeKW32eaI-mA1_tmZ:bb5otfh) ([raw file](https://github.com/cockroachdb/cockroach/blob/23bd1be88b8440af72fd20773efd9305be388f73/pkg/ccl/changefeedccl/changefeed_stmt.go#L317)):*
> ```Go
> 			pl := sj.Payload()
> 			cf := pl.GetDetails().(*jobspb.Payload_Changefeed).Changefeed
> 			scope := cf.Opts[changefeedbase.OptMetricsScope]
> ```

Do you know how this metrics would work if we add a metrics label for different changefeeds? Will `sli.WatchedTargets` still be correct?
___
*[`pkg/ccl/changefeedccl/changefeed_stmt.go` line 1156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NsOctuJ7JzSTg3PpKO4:-NsOctuJ7JzSTg3PpKO5:brrzfsq) ([raw file](https://github.com/cockroachdb/cockroach/blob/23bd1be88b8440af72fd20773efd9305be388f73/pkg/ccl/changefeedccl/changefeed_stmt.go#L1156)):*
> ```Go
> 		})
> 		sli.updateLastTargets(jobID, targetSet)
> 		return nil
> ```

nit: this part of code dealing with updating metrics for starting, resuming, and canceling jobs seems quite repetitive. Is there a straightforward way to modularize it?
___
*[`pkg/ccl/changefeedccl/metrics.go` line 197 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NsOdbgx974M1-j2wa_4:-NsOdbgx974M1-j2wa_5:b-h9kpxn) ([raw file](https://github.com/cockroachdb/cockroach/blob/23bd1be88b8440af72fd20773efd9305be388f73/pkg/ccl/changefeedccl/metrics.go#L197)):*
> ```Go
> }
> 
> func (m *sliMetrics) updateLastTargets(id jobspb.JobID, newTargets intsets.Fast) {
> ```

nit: could you add a comment for this function?
___
*[`pkg/ccl/changefeedccl/metrics.go` line 207 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NsOfbN-93kUeW_2F_Rp:-NsOfbN-93kUeW_2F_Rq:b-y63xa9) ([raw file](https://github.com/cockroachdb/cockroach/blob/23bd1be88b8440af72fd20773efd9305be388f73/pkg/ccl/changefeedccl/metrics.go#L207)):*
> ```Go
> 		}
> 		addedTargets = newTargets.Difference(oldTargets)
> 		removedTargets = oldTargets.Difference(newTargets)
> ```

For my education, what's the time efficiency to call Difference or Equals on intsets.Fast?
___
*[`pkg/ccl/changefeedccl/metrics_test.go` line 164 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NsOfS-W1RNHNQd7iLHo:-NsOfS-W1RNHNQd7iLHp:b10ca2m) ([raw file](https://github.com/cockroachdb/cockroach/blob/23bd1be88b8440af72fd20773efd9305be388f73/pkg/ccl/changefeedccl/metrics_test.go#L164)):*
> ```Go
> 		sqlDB.Exec(t, `CREATE TABLE bar (a INT PRIMARY KEY, b STRING)`)
> 		require.NoError(t, testfeed.Resume())
> 		require.EqualValues(t, 2, sliMetric.WatchedTargets.Value())
> ```

Nice tests!

**Review by rharding6373 — COMMENTED** [review]
I made a major change to move this metric from sliMetrics into the main Metrics, since we want to capture the # of unique tables across all changefeeds regardless of the metric label the changefeed uses. The result is a tiny bit simpler. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-:-NsRMceTC3jCQBOb5TCt:b-w3sl0u)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @amruss, @andyyang890, @jayshrivastava, and @wenyihu6)

___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NsMP_-J5ZJbm1_U7I4p):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

nit: maybe we should say "number of unique tables"
</blockquote></details>

Done
___
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NsOaioy5lm7pHGAyNcY):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

nit: i think we only remove the watched targets if the job has failed or been canceled. Could you add a note here clarifying how they change and they won't be removed if they are paused?
</blockquote></details>

Done
___
*[`pkg/ccl/changefeedccl/changefeed_stmt.go` line 313 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NsMQIAK7PT5UVYfQJ3a:-NsQFtb13hdqJAGx7Zkc:b-9fmn3c) ([raw file](https://github.com/cockroachdb/cockroach/blob/23bd1be88b8440af72fd20773efd9305be388f73/pkg/ccl/changefeedccl/changefeed_stmt.go#L313)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Maybe move this code into a named helper function? Especially given that it's more or less repeated verbatim below
</blockquote></details>

Good suggestion. Done.
___
*[`pkg/ccl/changefeedccl/changefeed_stmt.go` line 316 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NsOc5-PAj8ILSv82fWr:-NsQb0Eb6hj7fAbc-7Lz:b-1ty6s2) ([raw file](https://github.com/cockroachdb/cockroach/blob/23bd1be88b8440af72fd20773efd9305be388f73/pkg/ccl/changefeedccl/changefeed_stmt.go#L316)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

It seems there's a potential for `pl.GetDetails()` to return nil, which could lead to a nil pointer dereference when accessing Changefeed here. But I [notice](https://github.com/rharding6373/cockroach/blob/b45e639d5dfe141df152e3b0a3b9f6512cd1aa14/pkg/ccl/streamingccl/streamproducer/event_stream.go#L519)  that other parts of the code also directly access its fields, so maybe this is not possible.
</blockquote></details>

The payload is always set when the job is adopted. I don't think it can be nil.
___
*[`pkg/ccl/changefeedccl/changefeed_stmt.go` line 317 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NsOeKW32eaI-mA1_tmY:-NsPltC8-uD0fBwFOBSl:b-qvj9pq) ([raw file](https://github.com/cockroachdb/cockroach/blob/23bd1be88b8440af72fd20773efd9305be388f73/pkg/ccl/changefeedccl/changefeed_stmt.go#L317)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

Do you know how this metrics would work if we add a metrics label for different changefeeds? Will `sli.WatchedTargets` still be correct?
</blockquote></details>

This is a good point, and one thing I realized since writing this is that due to the way metrics labels work, we would double-count tables watched by changefeeds under different labels :grimacing:  I made a major change to fix this and added some test coverage. PTAL
___
*[`pkg/ccl/changefeedccl/changefeed_stmt.go` line 1156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NsOctuJ7JzSTg3PpKO4:-NsQbAxX8bEMzf5xpmzy:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/23bd1be88b8440af72fd20773efd9305be388f73/pkg/ccl/changefeedccl/changefeed_stmt.go#L1156)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

nit: this part of code dealing with updating metrics for starting, resuming, and canceling jobs seems quite repetitive. Is there a straightforward way to modularize it?
</blockquote></details>

Done
___
*[`pkg/ccl/changefeedccl/changefeed_stmt.go` line 1497 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NsMRY_tBIpLqQw0KsJ_:-NsQbF5EBtk_HpVGxf1R:b484b1l) ([raw file](https://github.com/cockroachdb/cockroach/blob/23bd1be88b8440af72fd20773efd9305be388f73/pkg/ccl/changefeedccl/changefeed_stmt.go#L1497)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

nit: maybe put this in an `if err := ...; err != nil { ... }` and still have the `return nil` at the end of the function, would make it a bit easier to insert things after this function (if needed) in the future
</blockquote></details>

With the new changes, this is no longer an issue.
___
*[`pkg/ccl/changefeedccl/metrics.go` line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NsMO-Uo5INIm3MySTm0:-NsQcxsY0mMxo9dQQ4e_:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/23bd1be88b8440af72fd20773efd9305be388f73/pkg/ccl/changefeedccl/metrics.go#L165)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Could you add comments documenting what these fields store?
</blockquote></details>

Done
___
*[`pkg/ccl/changefeedccl/metrics.go` line 197 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NsOdbgx974M1-j2wa_4:-NsRHU2K8rGlL8M19y7d:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/23bd1be88b8440af72fd20773efd9305be388f73/pkg/ccl/changefeedccl/metrics.go#L197)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

nit: could you add a comment for this function?
</blockquote></details>

Done
___
*[`pkg/ccl/changefeedccl/metrics.go` line 207 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NsOfbN-93kUeW_2F_Rp:-NsRHzT97gf9OcjFqXXu:bzf1xif) ([raw file](https://github.com/cockroachdb/cockroach/blob/23bd1be88b8440af72fd20773efd9305be388f73/pkg/ccl/changefeedccl/metrics.go#L207)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

For my education, what's the time efficiency to call Difference or Equals on intsets.Fast?
</blockquote></details>

Worst case implementation is a linked list of bitmaps, so Equals would be O(N). However, since table IDs are usually within a relatively small (100s) range, in practice I expect in most cases it would fit in a couple of bitmaps with only 1-3 linked list nodes.

Difference makes a copy of one of the sets first, but is also O(N).
___
*[`pkg/ccl/changefeedccl/metrics.go` line 229 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NsMNZc21lArFvWjV0Hz:-NsRKUgv-ON_DmoKojvx:b-ruv6hf) ([raw file](https://github.com/cockroachdb/cockroach/blob/23bd1be88b8440af72fd20773efd9305be388f73/pkg/ccl/changefeedccl/metrics.go#L229)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

nit: maybe rename to `incTargetLocked` to match the `Gauge` API
</blockquote></details>

I made the name more similar (while still using locked naming convention). What do you think?
___
*[`pkg/ccl/changefeedccl/metrics.go` line 240 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NsMNc324yVE97BjMA8E:-NsRKq0h-z0PTXo9ftvt:byr4ffv) ([raw file](https://github.com/cockroachdb/cockroach/blob/23bd1be88b8440af72fd20773efd9305be388f73/pkg/ccl/changefeedccl/metrics.go#L240)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

nit: maybe rename to `decTargetLocked` to match the `Gauge` API
</blockquote></details>

see above
___
*[`pkg/ccl/changefeedccl/metrics.go` line 886 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NsMPj_LAHLyRAc_2vm9:-NsRL-ap2LGBglGXsPDq:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/23bd1be88b8440af72fd20773efd9305be388f73/pkg/ccl/changefeedccl/metrics.go#L886)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

nit: maybe we should clarify that it's the number of "unique targets"
</blockquote></details>

Done
___
*[`pkg/ccl/changefeedccl/helpers_test.go` line 1379 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NsMPFoU-OV-kiL-M-fs:-NsRLEAhCJnkfjuqq0q5:bwks5fc) ([raw file](https://github.com/cockroachdb/cockroach/blob/23bd1be88b8440af72fd20773efd9305be388f73/pkg/ccl/changefeedccl/helpers_test.go#L1379)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

nit: maybe rename to something like `waitForChangefeedRunningCount`
</blockquote></details>

I did some refactoring here and made this more generic. Wdyt?
___
*[`pkg/ccl/changefeedccl/metrics_test.go` line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NsMT5gL77OlgYIM5B46:-NsRLZ_T6aZ4Yg90SF9X:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/23bd1be88b8440af72fd20773efd9305be388f73/pkg/ccl/changefeedccl/metrics_test.go#L23)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

nit: maybe rename to `TestRunningCountAndWatchedTargets` since those are the only two metrics being tested?
</blockquote></details>

Done
___
*[`pkg/ccl/changefeedccl/metrics_test.go` line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NsMSyPuCx3Qfn62XVnj:-NsRLlICDVgU7C8rxFCq:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/23bd1be88b8440af72fd20773efd9305be388f73/pkg/ccl/changefeedccl/metrics_test.go#L96)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Should we maybe add an assertion for the running count being 0?
</blockquote></details>

Good idea. Done.
___
*[`pkg/ccl/changefeedccl/metrics_test.go` line 164 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NsOfS-W1RNHNQd7iLHo:-NsRLotL3axUQLK6susM:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/23bd1be88b8440af72fd20773efd9305be388f73/pkg/ccl/changefeedccl/metrics_test.go#L164)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

Nice tests!
</blockquote></details>

Thanks!

**Review by jayshrivastava — APPROVED** [review]
This LGTM! Thanks for working on this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-:-NsjIkDuEbaDobE8QOuD:bahr3h8)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @amruss, @andyyang890, @rharding6373, and @wenyihu6)

___
*[`pkg/ccl/changefeedccl/metrics.go` line 1136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NsjIQvt7PRfSEyHIhvt:-NsjIQvt7PRfSEyHIhvu:b2sk71n) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c24224f0da9f7a912736d9069294dd3b12cc18/pkg/ccl/changefeedccl/metrics.go#L1136)):*
> ```Go
> // WatchedTargets metrics if this is the first target with this id.
> // Requires m.mu to be locked.
> func (m *Metrics) incLocked(id int) {
> ```

It's probably better to name these with a specific name ex. `incWatchedTargetsLocked`.
___
*[`pkg/ccl/changefeedccl/metrics.go` line 1136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NsjIcU74GCnLsKM3sGk:-NsjIcU74GCnLsKM3sGl:b-2y0e6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c24224f0da9f7a912736d9069294dd3b12cc18/pkg/ccl/changefeedccl/metrics.go#L1136)):*
> ```Go
> // WatchedTargets metrics if this is the first target with this id.
> // Requires m.mu to be locked.
> func (m *Metrics) incLocked(id int) {
> ```

nit: use `targetID` instead of `id`.

**Review by andyyang890 — APPROVED** [review]
Some small nits but otherwise :lgtm:

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-:-NskYWCN0eqgT6nxhLUF:b-6txhkz)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @amruss, @rharding6373, and @wenyihu6)

___
*[`pkg/ccl/changefeedccl/metrics.go` line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NsMO-Uo5INIm3MySTm0:-NskXcUo1GGU6mKbTMQi:b-6pqh2h) ([raw file](https://github.com/cockroachdb/cockroach/blob/23bd1be88b8440af72fd20773efd9305be388f73/pkg/ccl/changefeedccl/metrics.go#L165)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Thanks for adding comments!
___
*[`pkg/ccl/changefeedccl/metrics.go` line 1083 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NskWIP77QEB6wluF5wr:-NskWIP77QEB6wluF5ws:b-2zre4e) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c24224f0da9f7a912736d9069294dd3b12cc18/pkg/ccl/changefeedccl/metrics.go#L1083)):*
> ```Go
> 		// targets maps table IDs to the number of occurrences of the table ID in
> 		// changefeeds.
> 		targets map[int]int64
> ```

nit: do we maybe want to call this something more descriptive like`targetCounts`? if so, we can rename the functions below like `incTargetCountLocked` and `decTargetCountLocked`
___
*[`pkg/ccl/changefeedccl/metrics.go` line 1133 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NskVxM27qRXoFhTDC1N:-NskVxM27qRXoFhTDC1O:b-4e2iqd) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c24224f0da9f7a912736d9069294dd3b12cc18/pkg/ccl/changefeedccl/metrics.go#L1133)):*
> ```Go
> }
> 
> // incrTarget increments the count with the target ID and increments the
> ```

nit: function name in comment needs to be updated
___
*[`pkg/ccl/changefeedccl/metrics.go` line 1144 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NskW-j6Dm94V4t9TpaX:-NskW-j6Dm94V4t9TpaY:b-4e2iqd) ([raw file](https://github.com/cockroachdb/cockroach/blob/46c24224f0da9f7a912736d9069294dd3b12cc18/pkg/ccl/changefeedccl/metrics.go#L1144)):*
> ```Go
> }
> 
> // decrTarget decrements the count with the target ID and decrements the
> ```

nit: function name in comment needs to be updated
___
*[`pkg/ccl/changefeedccl/helpers_test.go` line 1379 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NsMPFoU-OV-kiL-M-fs:-NskXRQb4MbYIRV31kaz:b-83sjoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/23bd1be88b8440af72fd20773efd9305be388f73/pkg/ccl/changefeedccl/helpers_test.go#L1379)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

I did some refactoring here and made this more generic. Wdyt?
</blockquote></details>

Nice!

**Review by wenyihu6 — APPROVED** [review]
:lgtm: mod some nit comments others already made  

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-:-NsseP1I8wF2NzX7AorD:b-9vp7rg)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @amruss and @rharding6373)

___
*[`pkg/ccl/changefeedccl/metrics.go` line 207 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119391#-NsOfbN-93kUeW_2F_Rp:-Nss_lzrAhWb8Gr-dl_I:b-wsvasg) ([raw file](https://github.com/cockroachdb/cockroach/blob/23bd1be88b8440af72fd20773efd9305be388f73/pkg/ccl/changefeedccl/metrics.go#L207)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Worst case implementation is a linked list of bitmaps, so Equals would be O(N). However, since table IDs are usually within a relatively small (100s) range, in practice I expect in most cases it would fit in a couple of bitmaps with only 1-3 linked list nodes.

Difference makes a copy of one of the sets first, but is also O(N).
</blockquote></details>

Thanks for the explanation!

**Pull request closed without merging**
