### PR TITLE
crosscluster/logical: support external://

### PR DESCRIPTION
**Pull request by dt**
Release note: none.
Epic: none.

### CODE REVIEW

**Review by stevendanna — APPROVED** [review]

**Comment by stevendanna** [comment]
bors r=stevendanna

**Comment by stevendanna** [comment]
bors retry

**Comment by stevendanna** [comment]
Probably just needs a rebase against your other small cleanup PR.

```
pkg/ccl/crosscluster/logical/logical_replication_job_test.go:155:11: undefined: url
```

**Comment by dt** [comment]
TFTR!

bors r+

**Comment by stevendanna** [comment]
bors retry

**Comment by msbutler** [comment]
@dt cockroach is not compiling. i think you need to rebase.

**Pull request merged**
