### PR TITLE
release-21.2: revert "sql: add database ID to sampled query log"

### PR DESCRIPTION
**Pull request by THardy98**
Reverts: #84195
This reverts commit c633d130bf49a9a38b9e95e47fe1b60d00d1f338.

Removes the DatabaseID field from the
SampledQuery telemetry log due to the potential of indefinite blocking
in the case of a lease acquisition failure. Protobuf field not reserved as
no official build was released with these changes yet.

Release note (sql change): Removes the DatabaseID field from the
SampledQuery telemetry log due to the potential of indefinite blocking
in the case of a lease acquisition failure.

Release justification: Category 2: Bug fixes and low-risk updates to new functionality

### CODE REVIEW

**Review by maryliag — APPROVED** [review]
update your PR title to add `release-21.2:...` and use only lower case, unless is the name of a variable

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85022#-:-N7qoS8mCSOwMSKA9TOs:b-tqwjn)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by THardy98** [comment]
> update your PR title to add `release-21.2:...` and use only lower case, unless is the name of a variable
> 
> :lgtm:
> 
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85022#-:-N7qoS8mCSOwMSKA9TOs:b-tqwjn)_ status: :shipit: complete! 1 of 0 LGTMs obtained

Updated.

**Review by maryliag — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85022)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @maryliag and @THardy98)

___
*[`pkg/util/log/eventpb/telemetry.proto` line 60 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85022#-N7udbb376Ixp810Qvp2:-N7udbb376Ixp810Qvp3:b15hujf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0432dae2dbfee5a12cb6ba262cdee18f7336bb32/pkg/util/log/eventpb/telemetry.proto#L60)):*
> ```protobuf
> 
>   // Statement fingerprint ID of the query.
>   uint64 statement_fingerprint_id = 12 [(gogoproto.customname) = "StatementFingerprintID", (gogoproto.jsontag) = ',omitempty'];
> ```

to keep aligned with 22.1 and mater, go back to fingerprint 13 and add 12 as reserved

**Review by THardy98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85022)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @maryliag)

___
*[`pkg/util/log/eventpb/telemetry.proto` line 60 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85022#-N7udbb376Ixp810Qvp2:-N8-BG9I7L5lhxLLnskU:bit542n) ([raw file](https://github.com/cockroachdb/cockroach/blob/0432dae2dbfee5a12cb6ba262cdee18f7336bb32/pkg/util/log/eventpb/telemetry.proto#L60)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

to keep aligned with 22.1 and mater, go back to fingerprint 13 and add 12 as reserved
</blockquote></details>

Reserved 12 and reverted back to 13.
Small `gen.go` change to accomodate `reserved` fields in the proto.

**Review by maryliag — APPROVED** [review]
small nit, otherwise :lgtm: 

> Reviewed 3 of 6 files at r1, 1 of 1 files at r2, 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85022#-:-N8-k7dl6nWz3Zx14iHi:bwg40qh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag and @THardy98)

___
*[`pkg/util/log/eventpb/telemetry.proto` line 59 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85022#-N8-jzbB-zog3_7L3d7P:-N8-jzbC0HK0DjHsZpC7:b-amq9yk) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d4d147148647556fc4f4ad04dc75ded23d10e26/pkg/util/log/eventpb/telemetry.proto#L59)):*
> ```protobuf
>   string transaction_id = 11 [(gogoproto.customname) = "TransactionID", (gogoproto.jsontag) = ',omitempty', (gogoproto.moretags) = "redact:\"nonsensitive\""];
> 
>   reserved 12;
> ```

we usually put the list of reserved at the end, so people can just add items there

**Pull request merged**
