### PR TITLE
sql: add VOID type 

### LINKED ISSUE #45234: sql: add VOID type
Postgres has `void` type, and we don't. For example, `pg_sleep` and some of the `pg_advisory_...` builtins have it as the return type. We should add it to our type system for compatibility.

Epic: CRDB-11419

### PR DESCRIPTION
**Pull request by otan**
Resolves #45234

See individual commits for details.

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
lgtm with minor comments!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73488#-:-Mqp0lmrByRDa5QeDFZq:b-g6gy8h)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rafiss)

___
*[pkg/sql/logictest/testdata/logic_test/create_table, line 638 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/73488#-MqozyG63mfIhdRmb4rL:-MqozyG63mfIhdRmb4rM:b-5nfasm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e89328d92398a3e2d6487179845a51e7f1caa435/pkg/sql/logictest/testdata/logic_test/create_table#L638)):*
> ```
> CREATE TABLE serial_test4 (id SERIAL4, temp string)
> 
> statement ok
> ```

accidentally removed a test?
___
*[pkg/sql/logictest/testdata/logic_test/void, line 15 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73488#-Mqp-YD_3iqOE4hGtxXC:-Mqp-YD_3iqOE4hGtxXD:b-elxfhx) ([raw file](https://github.com/cockroachdb/cockroach/blob/500fa5df194112b5390b381ea4a6ff05e8ef901c/pkg/sql/logictest/testdata/logic_test/void#L15)):*
> ```
> 
> query T
> SELECT ('gone'::void)::text
> ```

maybe add a test for voids in tuples?

```
rafiss@127:postgres> select row (''::void, 2::int);
+--------+
| row    |
|--------|
| ("",2) |
+--------+
```
___
*[pkg/sql/pgwire/testdata/pgtest/void, line 4 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73488#-Mqp0aXD9hJae5QcUvgQ:-Mqp0aXD9hJae5QcUvgR:b-o4sowe) ([raw file](https://github.com/cockroachdb/cockroach/blob/b96a5357ecc1267469db2783854ea180e5b3bba5/pkg/sql/pgwire/testdata/pgtest/void#L4)):*
> ```
> # We can make these match in v22.2.
> 
> send noncrdb_only
> ```

nice call on adding this test
___
*[pkg/sql/sem/tree/datum.go, line 4360 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73488#-Mqp-yEg9YvxAGirY79U:-Mqp-yEh9HCvHbzmo8Cg:b5h0z3p) ([raw file](https://github.com/cockroachdb/cockroach/blob/500fa5df194112b5390b381ea4a6ff05e8ef901c/pkg/sql/sem/tree/datum.go#L4360)):*
> ```Go
> // NewDVoid returns a new Void Datum.
> func NewDVoid() *DVoid {
> 	return &DVoid{}
> ```

do we ever really need a new one? could we just used a const like how we do for DBoolTrue and DBoolFalse?
___
*[pkg/sql/sem/tree/datum.go, line 4374 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73488#-Mqp08iq91QbnzmakYft:-Mqp08ir2QLqD7SzJ40x:b-6g1jcr) ([raw file](https://github.com/cockroachdb/cockroach/blob/500fa5df194112b5390b381ea4a6ff05e8ef901c/pkg/sql/sem/tree/datum.go#L4374)):*
> ```Go
> 		return 1
> 	}
> 	return 0
> ```

should it assert that `other` is also a DVoid?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73488)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/logictest/testdata/logic_test/create_table, line 638 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/73488#-MqozyG63mfIhdRmb4rL:-MqpXhSk6vTlFKfOhpgS:bafaswv) ([raw file](https://github.com/cockroachdb/cockroach/blob/e89328d92398a3e2d6487179845a51e7f1caa435/pkg/sql/logictest/testdata/logic_test/create_table#L638)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

accidentally removed a test?
</blockquote></details>

urgh rebase problems. fixed.
___
*[pkg/sql/logictest/testdata/logic_test/void, line 15 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73488#-Mqp-YD_3iqOE4hGtxXC:-MqpXzM01NQZuhVCwPr5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/500fa5df194112b5390b381ea4a6ff05e8ef901c/pkg/sql/logictest/testdata/logic_test/void#L15)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

maybe add a test for voids in tuples?

```
rafiss@127:postgres> select row (''::void, 2::int);
+--------+
| row    |
|--------|
| ("",2) |
+--------+
```
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/testdata/pgtest/void, line 4 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73488#-Mqp0aXD9hJae5QcUvgQ:-MqpWISb1DczqpJQ5HS6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b96a5357ecc1267469db2783854ea180e5b3bba5/pkg/sql/pgwire/testdata/pgtest/void#L4)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nice call on adding this test
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/datum.go, line 4360 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73488#-Mqp-yEg9YvxAGirY79U:-MqpZRg0-5GX7nLHVrbD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/500fa5df194112b5390b381ea4a6ff05e8ef901c/pkg/sql/sem/tree/datum.go#L4360)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

do we ever really need a new one? could we just used a const like how we do for DBoolTrue and DBoolFalse?
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/datum.go, line 4374 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73488#-Mqp08iq91QbnzmakYft:-MqpZ57--3zRbAb4puYe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/500fa5df194112b5390b381ea4a6ff05e8ef901c/pkg/sql/sem/tree/datum.go#L4374)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

should it assert that `other` is also a DVoid?
</blockquote></details>

Done.

**Comment by rafiss** [comment]
still need to push the new changes? :P

**Comment by otan** [comment]
d'oh

**Review by rafiss — APPROVED** [review]
lgtm!

> Reviewed 9 of 12 files at r1, 1 of 23 files at r5, 15 of 16 files at r6, 4 of 4 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73488#-:-MqqwXD7AEnhbezZvKFk:b-7nbn20)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

**Comment by otan** [comment]
let's gooo

bors r=rafiss

**Pull request merged**
