### PR TITLE
server: add network diagnostics page

### PR DESCRIPTION
**Pull request by BramGruneir**
This adds network latencies to the node statuses that are saved in the cluster.
These node statuses are not gossiped, only the node descriptor is. Also, only a
single value is kept as they are always written with timestamp 0.

This network diagnositics page contains 4 sections:
1) a map of the current latencies between each node
2) a list of nodes that currently do not have a connection to another node
3) a list of the highest latency conncetions (exclusting self latencies)
4) a list of the lowest latency connections (exclusing self latencies)

### CODE REVIEW

**Comment by BramGruneir** [comment]
This is still a work in progress, but I wanted to get some feedback on it.  Here are some screenshots of the the page:

screen shot 2017-05-26 at 13 02 46
screen shot 2017-05-26 at 13 02 56
screen shot 2017-05-26 at 13 03 03

**Comment by BramGruneir** [comment]
Most of the work that I plan to do is in cleaning up how the latency chart is rendered and calculated.  

In a follow up PR, I'll add the ability to list the specific nodes by ids and only show those.

**Comment by petermattis** [comment]
Haven't looked at the actual code yet...

Mixing different units in the same table/matrix makes it difficult to read. For latencies, I'd suggest always using a `%.1fms` format. 

I wonder if the `No Connection`, `Worst Connections` and `Best Connections` tables are necessary. The `No Connection` table seems to be captured in the latencies matrix. And the worst/best connections could also be highlighted there.

Should we display the self latencies in the latencies matrix. Another option would be to leave those blank or use a `-`.

We discussed additional network diagnostics in the past. Are those coming in a future PR?

---

Review status: 0 of 15 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16174#-:-Kl5IqhxaNOCIgpytsrF:b-y0skko)*

**Comment by bdarnell** [comment]
I also haven't looked at the code yet.

I agree with Peter that as long as the big matrix is manageable, the best/worst lists are redundant and would be better highlighted in the table. Do they offer better insights in a cluster large enough that the big matrix is unusable? I'm skeptical: in a cluster with localities specified, the "best" connections will presumably be a list of intra-DC connections, and the "worst" will be a list of all of the connections on the slowest link. 

I think the list of nodes without connections is much more interesting than the latency stats (when there are any). Maybe it should get its own page. In addition to just listing nodes, we should try to collect as much information as we can: save the last error we logged for that connection, etc. 

---

Review status: 0 of 15 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16174#-:-KlLzP11T4C3z4M1EPlw:bzdn49b)*

**Comment by BramGruneir** [comment]
This is ready for a full review.

I've added a lot more here.  Including shading based on the mean latency with and +- standard deviations.

> Mixing different units in the same table/matrix makes it difficult to read. For latencies, I'd suggest always using a 
%.1fms format.
Done.  As always, you can hover over any value to get the full value.

> I wonder if the No Connection, Worst Connections and Best Connections tables are necessary. The No Connection table seems to be captured in the latencies matrix. And the worst/best connections could also be highlighted there.
I've tried to capture it all, but I think having a top 10 / worst 10 will be useful once the matrix gets huge.  

> Should we display the self latencies in the latencies matrix. Another option would be to leave those blank or use a -.
I've shaded them.  And they are not included in the matrix or statistic calculations.

> We discussed additional network diagnostics in the past. Are those coming in a future PR?
Yes.  More to come.

>I agree with Peter that as long as the big matrix is manageable, the best/worst lists are redundant and would be better highlighted in the table. Do they offer better insights in a cluster large enough that the big matrix is unusable?
I think they will.  But they're easy enough to remove later.

>I'm skeptical: in a cluster with localities specified, the "best" connections will presumably be a list of intra-DC connections, and the "worst" will be a list of all of the connections on the slowest link.
Agreed.  I've added the localities to all the node lists (you can see them in any nodeID tooltip as well.  

I'd like to add a localities matrix next.  Taking the average values between top level localities only, if any are specified.  Which should allow for a better understanding of network the topology.

>I think the list of nodes without connections is much more interesting than the latency stats (when there are any). Maybe it should get its own page. 
I like this idea.  And it would have to use a different metric than the latency one.  I've added it to the tracking issue #14671.  

>In addition to just listing nodes, we should try to collect as much information as we can: save the last error we logged for that connection, etc.
That will take some doing, but is entirely feasible.  I added this to the tracking issue as well.


Updated screens:



---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16174#-:-KlQ5VLcSHHld3PZ_Tpv:b-dbgik0)*

**Comment by petermattis** [comment]
:lgtm: though @a-robinson should weigh-in as well.

The matrix looks much better. The coloring is very nice. Is there a reason you left in the self-latencies along the diagonal? The values there aren't indicating anything about the network.

I'd still argue for leaving out the Worst/Best Connections lists. More isn't always better.

---

Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/server/status/status.proto, line 41 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16174#-KlQzjTU3UlmwGYdjavw:-KlQzjTU3UlmwGYdjavx:brymslh) ([raw file](https://github.com/cockroachdb/cockroach/blob/e38785938d03d1e6d337cc0f88e78086e5f5113c/pkg/server/status/status.proto#L41)):*
> ```protobuf
>   repeated string args = 7;
>   repeated string env = 8;
>   map<int64, int64> latencies = 9 [
> ```

The key and value for this map deserve a comment. What are the units here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16174#-:-KlQxjDmyK-FvfODF94y:b9njkm2)*

**Comment by BramGruneir** [comment]
I've removed the values in the self latencies and also the worst/best lists.  We can always add them back if needed.



---

Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/server/status/status.proto, line 41 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16174#-KlQzjTU3UlmwGYdjavw:-KlS0EWglyIq7mVXrLUS:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e38785938d03d1e6d337cc0f88e78086e5f5113c/pkg/server/status/status.proto#L41)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The key and value for this map deserve a comment. What are the units here?
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16174#-:-KlRzmeE3eAaIPmRSdF3:b-nkvt5y)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 11 of 14 files at r1, 4 of 4 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16174#-:-KlUQxIL-W2VCTyes5ZA:bnfp4nl)*

**Comment by a-robinson** [comment]
I actually liked the self-latencies because they provide a lower bound based on the cost of the rpc machinery, but I can live without them. Just a few comments.

---

Reviewed 11 of 14 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/rpc/clock_offset.go, line 114 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16174#-KlUT01Yti0Z63R1dxT3:-KlUT01Yti0Z63R1dxT4:bislqtn) ([raw file](https://github.com/cockroachdb/cockroach/blob/38a68bf1420ab2241644d9eddb02d356ec9c8834/pkg/rpc/clock_offset.go#L114)):*
> ```Go
> }
> 
> // AllLatencies resturns a map of all currently valid latency measurements.
> ```

s/resturns/returns

---

*[pkg/server/status/recorder.go, line 277 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16174#-KlUUtcIJxzujRHjTAtA:-KlUUtcIJxzujRHjTAtB:b-f6s17p) ([raw file](https://github.com/cockroachdb/cockroach/blob/38a68bf1420ab2241644d9eddb02d356ec9c8834/pkg/server/status/recorder.go#L277)):*
> ```Go
> // component stores.
> func (mr *MetricsRecorder) GetStatusSummary(ctx context.Context) *NodeStatus {
> 	latencies := make(map[roachpb.NodeID]int64)
> ```

It's a minor style point, but this would make sense as its own function

---

*[pkg/server/status/recorder.go, line 281 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16174#-KlUV8pg9BluQ4h78wqJ:-KlUV8pg9BluQ4h78wqK:b9g8b6e) ([raw file](https://github.com/cockroachdb/cockroach/blob/38a68bf1420ab2241644d9eddb02d356ec9c8834/pkg/server/status/recorder.go#L281)):*
> ```Go
> 		isLiveMap := mr.nodeLiveness.GetIsLiveMap()
> 		currentAverages := mr.remoteClockMonitor.AllLatencies()
> 		for nodeID := range isLiveMap {
> ```

If we're not using whether or not the node is live, do we really need to use the node liveness map at all? It seems as though we could just iterate over the `currentAverages` map and use a gossip method to get node ID by address.

---

*[pkg/server/status/status.proto, line 17 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16174#-KlUVt1dWW5UJgqui1p0:-KlUVt1dWW5UJgqui1p1:b8dm6g9) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bf5973c239ed35e63df9753f61957c39e5e0925/pkg/server/status/status.proto#L17)):*
> ```protobuf
> // Author: Bram Gruneir (bram+code@cockroachlabs.com)
> 
> syntax = "proto2";
> ```

Is this change backwards compatible? I realize the map type is useful, but it's a little scary given that I thought we store these on disk

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16174#-:-KlUO3q8A0AWFircfwNz:bchvl01)*

**Comment by BramGruneir** [comment]
Review status: 12 of 15 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/rpc/clock_offset.go, line 114 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16174#-KlUT01Yti0Z63R1dxT3:-KlUWwSPv-8Avu5iX14m:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/38a68bf1420ab2241644d9eddb02d356ec9c8834/pkg/rpc/clock_offset.go#L114)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

s/resturns/returns
</blockquote></details>

Done.

---

*[pkg/server/status/recorder.go, line 277 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16174#-KlUUtcIJxzujRHjTAtA:-KlUXJFLFZk66atqD390:b-8trm9w) ([raw file](https://github.com/cockroachdb/cockroach/blob/38a68bf1420ab2241644d9eddb02d356ec9c8834/pkg/server/status/recorder.go#L277)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

It's a minor style point, but this would make sense as its own function
</blockquote></details>

I agree.  Done.

---

*[pkg/server/status/recorder.go, line 281 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16174#-KlUV8pg9BluQ4h78wqJ:-KlUZ-lNO9cbkHG2vjvi:b-w167ee) ([raw file](https://github.com/cockroachdb/cockroach/blob/38a68bf1420ab2241644d9eddb02d356ec9c8834/pkg/server/status/recorder.go#L281)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

If we're not using whether or not the node is live, do we really need to use the node liveness map at all? It seems as though we could just iterate over the `currentAverages` map and use a gossip method to get node ID by address.
</blockquote></details>

Ah, that's a bug.  I wanted to only store values for nodes that are alive to minimize the amount of stored data.

---

*[pkg/server/status/status.proto, line 17 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16174#-KlUVt1dWW5UJgqui1p0:-KlUZtGBe6aTSow2w4fl:b-it77ii) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bf5973c239ed35e63df9753f61957c39e5e0925/pkg/server/status/status.proto#L17)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Is this change backwards compatible? I realize the map type is useful, but it's a little scary given that I thought we store these on disk
</blockquote></details>

I tested it and it seems to work perfectly fine.  All of the non-primatives were already set to nullable=false.  I've got a mixed version running right now locally and it just means that some of the nodes don't have latencies.  The admin ui (the primary/only consumer) seems perfectly fine. 



---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16174)*

**Comment by a-robinson** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r3.
Review status: 13 of 15 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/server/status/recorder.go, line 281 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16174#-KlUV8pg9BluQ4h78wqJ:-KlUi46NnQRgEwkJxt7v:bg2j5h2) ([raw file](https://github.com/cockroachdb/cockroach/blob/38a68bf1420ab2241644d9eddb02d356ec9c8834/pkg/server/status/recorder.go#L281)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Ah, that's a bug.  I wanted to only store values for nodes that are alive to minimize the amount of stored data.
</blockquote></details>

Makes sense, thanks!

---

*[pkg/server/status/status.proto, line 17 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16174#-KlUVt1dWW5UJgqui1p0:-KlUi9CutXEWBF6j2Y9g:b-wt1gmg) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bf5973c239ed35e63df9753f61957c39e5e0925/pkg/server/status/status.proto#L17)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

I tested it and it seems to work perfectly fine.  All of the non-primatives were already set to nullable=false.  I've got a mixed version running right now locally and it just means that some of the nodes don't have latencies.  The admin ui (the primary/only consumer) seems perfectly fine. 



</blockquote></details>

Ack, here's to hoping we didn't miss something.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16174#-:-KlUiJKG-iCg718HS_P6:bnfp4nl)*

**Comment by bdarnell** [comment]
Review status: 13 of 15 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/server/status/status.proto, line 17 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16174#-KlUVt1dWW5UJgqui1p0:-KlUk6ZS3BUKvfabu1T0:b-y7snnb) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bf5973c239ed35e63df9753f61957c39e5e0925/pkg/server/status/status.proto#L17)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Ack, here's to hoping we didn't miss something.
</blockquote></details>

Maps work in proto2 syntax too (there's already two in this file). 

This change looks compatible to me. The big issues in changing proto2 to proto3 is  losing the ability to distinguish absent from zero (which doesn't apply here because everything's already non-nullable) and the fact that the encoded form changes (which is only really important downstream of raft). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16174)*

**Comment by spencerkimball** [comment]
Awesome. We need this for the cluster viz.

**Pull request merged**
