### PR TITLE
storage: check for an empty intents slice

### LINKED ISSUE #20975: *log.safeError: stopper.go:179: runtime.errorString: runtime error: index out of range
https://sentry.io/cockroach-labs/cockroachdb/issues/421798485/

```
*log.safeError: stopper.go:179: runtime.errorString: runtime error: index out of range
  File "github.com/cockroachdb/cockroach/pkg/storage/intent_resolver.go", line 484, in cleanupFinishedTxnIntents
  File "github.com/cockroachdb/cockroach/pkg/storage/intent_resolver.go", line 461, in func1
  File "github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go", line 328, in func1
...
(1 additional frame(s) were not displayed)

stopper.go:179: runtime.errorString: runtime error: index out of range
```

### PR DESCRIPTION
**Pull request by spencerkimball**
Fixes #20975

Release note: None

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/storage/intent_resolver.go, line 410 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21008#-L0v16S97w5pQDfFxvQB:-L0v16S97w5pQDfFxvQC:b9elon3) ([raw file](https://github.com/cockroachdb/cockroach/blob/db182d3d3348b387ee3e6d4cc3b619625e032052/pkg/storage/intent_resolver.go#L410)):*
> ```Go
> 	ctx context.Context, txn *roachpb.Transaction, intents []roachpb.Intent, now hlc.Timestamp,
> ) error {
> 	return ir.store.Stopper().RunLimitedAsyncTask(
> ```

It's too bad that we'd need to launch this goroutine before noticing that the intents are empty. Can we do the check out here or is the other logic in the task (pushing pending transactions before resolving the intents) still important even without intents?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21008)*

**Comment by spencerkimball** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/storage/intent_resolver.go, line 410 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21008#-L0v16S97w5pQDfFxvQB:-L0v6TWeP-fArPSlqvId:b1h03t8) ([raw file](https://github.com/cockroachdb/cockroach/blob/db182d3d3348b387ee3e6d4cc3b619625e032052/pkg/storage/intent_resolver.go#L410)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It's too bad that we'd need to launch this goroutine before noticing that the intents are empty. Can we do the check out here or is the other logic in the task (pushing pending transactions before resolving the intents) still important even without intents?
</blockquote></details>

We still want to push the txn. But now I realize that we actually need to make sure we supply the transaction metadata separately from the intents so we can be sure we clean up the transaction record, even if there are no intents to resolve.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21008)*

**Comment by spencerkimball** [comment]
@tschottdorf ping

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21008#-:-L1OEPf5oLfmsiQvbh2g:bnfp4nl)*

**Pull request merged**
