### PR TITLE
opt: parser, test catalog, query support for virtual columns

### PR DESCRIPTION
**Pull request by RaduBerinde**
This set of changes add parser, testcat, and query support for virtual columns. I have come full circle and realized that even though user-defined virtual columns don't help with the optimizer-side work for expression-based indexes, they help with integrating with the existing sql code. In particular, we can carve out pieces of work and write more targeted tests related to virtual columns, without having to define them through an expression-based index.

Informs #57608.

#### sql: support virtual columns in parser

Support VIRTUAL keyword in the parser. We still error out if it is
ever used.

Release note: None

#### opt: clean up hack in test catalog

To ensure that PK columns are non-nullable, the test catalog
reinitializes them to override the nullable flag. We replace this
hacky mechanism with figuring out the PK columns beforehand and
marking them as non-nullable in the definition before creating the
table columns.

Release note: None

#### opt: test catalog support for virtual columns

Release note: None

#### opt: optbuilder support for scanning virtual columns

This change adds support for scanning tables with virtual columns. The
virtual columns are projected on top of the Scan.

Release note: None

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
Cool! :lgtm: 

> Reviewed 13 of 13 files at r1, 1 of 1 files at r2, 5 of 5 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57622#-:-MNyo2M36RLAm-9Unv_S:b-dp13x5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/opt/optbuilder/select.go, line 529 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/57622#-MNymbOt1zLwj9iKzxQw:-MNymbOuDs0G59W6XfIZ:b-ertrvq) ([raw file](https://github.com/cockroachdb/cockroach/blob/bee0662691c16223956156c2c75b1cfab9429271/pkg/sql/opt/optbuilder/select.go#L529)):*
> ```Go
> 
> 	b.addCheckConstraintsForTable(tabMeta)
> 	b.addComputedColsForTable(tabMeta)
> ```

`b.addComputedColsForTable` assumes that all ordinary columns are in `mb.outScope`. I think this is a safe assumption because `mb.outScope` has all ordinary columns except when building scans for foreign key checks and foreign keys on virtual columns will not be allowed. Does that sound right to you?

We were bit by this for partial indexes (see the long comment below) so I'm hyper-sensitive. Might be worth adding a comment here to explain why this is safe.
___
*[pkg/sql/opt/testutils/testcat/create_table.go, line 537 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57622#-MNyi0zBBQRnUtiJAHyi:-MNyi0zBBQRnUtiJAHyj:b-sl9uth) ([raw file](https://github.com/cockroachdb/cockroach/blob/094f595282a6c899606bd49f8b2e329b347f40b5/pkg/sql/opt/testutils/testcat/create_table.go#L537)):*
> ```Go
> 			false, /* hidden */
> 			defaultExpr,
> 			computedExpr,
> ```

[nit] make `InitNonVirtual` accept `string` arguments for `computedExpr` and `defaultExpr` rather than `*string` to make it consistent with `InitVirtualComputed`.
___
*[pkg/sql/opt/testutils/testcat/testdata/index, line 134 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57622#-MNyhSXU1iIaEhNF4_jG:-MNyhSXV4-aZFTLxk1cm:b6k9p6c) ([raw file](https://github.com/cockroachdb/cockroach/blob/094f595282a6c899606bd49f8b2e329b347f40b5/pkg/sql/opt/testutils/testcat/testdata/index#L134)):*
> ```
>  │    └── x int not null
>  ├── INDEX idx2
>  │    ├── idx_expr_1 string as (lower(z)) virtual [hidden] [virtual-computed]
> ```

Is it redundant to have `virtual` and `[virtual-computed]`?

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57622#-:-MNyrgy00U2eFs99UmtW:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/opt/optbuilder/select.go, line 529 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/57622#-MNymbOt1zLwj9iKzxQw:-MNyoNg9Bahg05NSWR1q:b-lhddud) ([raw file](https://github.com/cockroachdb/cockroach/blob/bee0662691c16223956156c2c75b1cfab9429271/pkg/sql/opt/optbuilder/select.go#L529)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

`b.addComputedColsForTable` assumes that all ordinary columns are in `mb.outScope`. I think this is a safe assumption because `mb.outScope` has all ordinary columns except when building scans for foreign key checks and foreign keys on virtual columns will not be allowed. Does that sound right to you?

We were bit by this for partial indexes (see the long comment below) so I'm hyper-sensitive. Might be worth adding a comment here to explain why this is safe.
</blockquote></details>

I think at first we won't allow computed/default/check expressions to refer to virtual columns (I have it on my checklist in #57608. to actually check for these).

I am not sure I understand the issue with addComputedColsForTable.. it looks like it creates its own scope that contains all ordinary columns? It doesn't even have access to `outScope`..
___
*[pkg/sql/opt/testutils/testcat/create_table.go, line 537 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57622#-MNyi0zBBQRnUtiJAHyi:-MNyqeTn4gTUrT9xQv2J:b-8nai1) ([raw file](https://github.com/cockroachdb/cockroach/blob/094f595282a6c899606bd49f8b2e329b347f40b5/pkg/sql/opt/testutils/testcat/create_table.go#L537)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] make `InitNonVirtual` accept `string` arguments for `computedExpr` and `defaultExpr` rather than `*string` to make it consistent with `InitVirtualComputed`.
</blockquote></details>

They are optional in the non-virtual case, but computedExpr is not optional for InitVirtualComputed.
___
*[pkg/sql/opt/testutils/testcat/testdata/index, line 134 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57622#-MNyhSXU1iIaEhNF4_jG:-MNyqotH-sRueuGBT1df:bzc1ryl) ([raw file](https://github.com/cockroachdb/cockroach/blob/094f595282a6c899606bd49f8b2e329b347f40b5/pkg/sql/opt/testutils/testcat/testdata/index#L134)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Is it redundant to have `virtual` and `[virtual-computed]`?
</blockquote></details>

Sure looks like it :) Fixed.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57622)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/optbuilder/select.go, line 529 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/57622#-MNymbOt1zLwj9iKzxQw:-MNysPhj5QrCYtpgRK8A:b-8f5dt4) ([raw file](https://github.com/cockroachdb/cockroach/blob/bee0662691c16223956156c2c75b1cfab9429271/pkg/sql/opt/optbuilder/select.go#L529)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I think at first we won't allow computed/default/check expressions to refer to virtual columns (I have it on my checklist in #57608. to actually check for these).

I am not sure I understand the issue with addComputedColsForTable.. it looks like it creates its own scope that contains all ordinary columns? It doesn't even have access to `outScope`..
</blockquote></details>

It will created its own scope with all ordinary columns, but the scan only output `tabColIDs` which are a subset of the table columns defined by the `ordinals` argument. So these expressions could have outer columns that can't be resolved.

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/opt/optbuilder/select.go, line 529 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/57622#-MNymbOt1zLwj9iKzxQw:-MNytAknCw6GxrBQ1S3-:byyrwc5) ([raw file](https://github.com/cockroachdb/cockroach/blob/bee0662691c16223956156c2c75b1cfab9429271/pkg/sql/opt/optbuilder/select.go#L529)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

It will created its own scope with all ordinary columns, but the scan only output `tabColIDs` which are a subset of the table columns defined by the `ordinals` argument. So these expressions could have outer columns that can't be resolved.
</blockquote></details>

Sure.. but this is not the concern of the code here. We are just building these expressions here "generically" to avoid building them in multiple places. They are a property of the table, not really of the scan. It's up to the code which uses them to make sure it uses them in a way that makes sense.

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/opt/optbuilder/select.go, line 529 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/57622#-MNymbOt1zLwj9iKzxQw:-MNyuHtF5EXERb_ycSJv:bwjh0hq) ([raw file](https://github.com/cockroachdb/cockroach/blob/bee0662691c16223956156c2c75b1cfab9429271/pkg/sql/opt/optbuilder/select.go#L529)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Sure.. but this is not the concern of the code here. We are just building these expressions here "generically" to avoid building them in multiple places. They are a property of the table, not really of the scan. It's up to the code which uses them to make sure it uses them in a way that makes sense.
</blockquote></details>

Perhaps if we don't scan all the ordinary columns, that is an indication that we won't / shouldn't need these and we shouldn't build them? But it's more error-prone than saying that every tabMeta should have them.

**Review by mgartner — COMMENTED** [review]
> Reviewed 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57622)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/optbuilder/select.go, line 529 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/57622#-MNymbOt1zLwj9iKzxQw:-MNyuwo0-Y_gSKjGpjSK:b-jr8c6u) ([raw file](https://github.com/cockroachdb/cockroach/blob/bee0662691c16223956156c2c75b1cfab9429271/pkg/sql/opt/optbuilder/select.go#L529)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Perhaps if we don't scan all the ordinary columns, that is an indication that we won't / shouldn't need these and we shouldn't build them? But it's more error-prone than saying that every tabMeta should have them.
</blockquote></details>

Hmm. Then maybe the fix for the similar issue with partial indexes is not the right fix? See https://github.com/cockroachdb/cockroach/pull/55702/commits/7ca00cc95fae2eb1a2b4b146f20e082ca92b50ee

I don't feel strongly how we do it, but we have to prevent projecting a virtual computed column expression that references columns that aren't output by the child Scan. Are you suggesting that it's the responsibility of the caller of buildScan not to pass bad `ordinals`?
___
*[pkg/sql/opt/testutils/testcat/create_table.go, line 537 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57622#-MNyi0zBBQRnUtiJAHyi:-MNytzvHDAXBwNEh1t32:b1o2vyg) ([raw file](https://github.com/cockroachdb/cockroach/blob/094f595282a6c899606bd49f8b2e329b347f40b5/pkg/sql/opt/testutils/testcat/create_table.go#L537)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

They are optional in the non-virtual case, but computedExpr is not optional for InitVirtualComputed.
</blockquote></details>

Oops. Nevermind then!

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57622)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[pkg/sql/opt/optbuilder/select.go, line 529 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/57622#-MNymbOt1zLwj9iKzxQw:-MNyx7om5xeq_Q6VWF6B:b-8grkoo) ([raw file](https://github.com/cockroachdb/cockroach/blob/bee0662691c16223956156c2c75b1cfab9429271/pkg/sql/opt/optbuilder/select.go#L529)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Hmm. Then maybe the fix for the similar issue with partial indexes is not the right fix? See https://github.com/cockroachdb/cockroach/pull/55702/commits/7ca00cc95fae2eb1a2b4b146f20e082ca92b50ee

I don't feel strongly how we do it, but we have to prevent projecting a virtual computed column expression that references columns that aren't output by the child Scan. Are you suggesting that it's the responsibility of the caller of buildScan not to pass bad `ordinals`?
</blockquote></details>

Hm I see.. But unlike `addComputedColsForTable`, `addPartialIndexPredicatesForTable` uses the `outScope` so the situation is different.

Now that I'm getting more reacquainted with this code, can't `addPartialIndexPredicatesForTable` also create its own scope with all the ordinary table columns? We may be relying on not adding them to tabMeta in certain cases, but if that's the case the check should happen where we would use them (by consulting the outer cols).

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57622)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[pkg/sql/opt/optbuilder/select.go, line 529 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/57622#-MNymbOt1zLwj9iKzxQw:-MNyy9D07rbx04vjTTX4:b-pjjtka) ([raw file](https://github.com/cockroachdb/cockroach/blob/bee0662691c16223956156c2c75b1cfab9429271/pkg/sql/opt/optbuilder/select.go#L529)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Hm I see.. But unlike `addComputedColsForTable`, `addPartialIndexPredicatesForTable` uses the `outScope` so the situation is different.

Now that I'm getting more reacquainted with this code, can't `addPartialIndexPredicatesForTable` also create its own scope with all the ordinary table columns? We may be relying on not adding them to tabMeta in certain cases, but if that's the case the check should happen where we would use them (by consulting the outer cols).
</blockquote></details>

Talking about it in terms of API, `ComputedCols` is a member of `TableMeta` defined as containing ScalarExprs for computed column expressions which refer to table columns using the table column IDs for this meta entry. The buildScan code just initializes it that way. After that, you do what you want with it. If you don't remap the column IDs or use it in a Project on top of an expression that doesn't produce all the necessary IDs, that's on you - it has nothing to do with the context of why the TableMeta was initialized in the first place.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57622)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/optbuilder/select.go, line 529 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/57622#-MNymbOt1zLwj9iKzxQw:-MNz0TKi2KIR58c_j3JJ:b-bw38ey) ([raw file](https://github.com/cockroachdb/cockroach/blob/bee0662691c16223956156c2c75b1cfab9429271/pkg/sql/opt/optbuilder/select.go#L529)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Talking about it in terms of API, `ComputedCols` is a member of `TableMeta` defined as containing ScalarExprs for computed column expressions which refer to table columns using the table column IDs for this meta entry. The buildScan code just initializes it that way. After that, you do what you want with it. If you don't remap the column IDs or use it in a Project on top of an expression that doesn't produce all the necessary IDs, that's on you - it has nothing to do with the context of why the TableMeta was initialized in the first place.
</blockquote></details>

Ahh I see. I like this definition. I'll work on making that change for `addPartialIndexPredicatesForTable` and checking the outer cols where it's used. I think the only place is in `scan_index_iter.go`. I think that will clean things up and be less error prone.

So nothing needs to change for `addComputedColsForTable`, but just below here `tabMeta.ComputedCols` is accessed, so I guess that's the place we'd check the outer cols, if it's necessary. And I don't think its necessary unless FKs can reference virtual columns, correct? I guess that's originally what I was trying to call out, but explained my thoughts poorly.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57622)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[pkg/sql/opt/optbuilder/select.go, line 529 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/57622#-MNymbOt1zLwj9iKzxQw:-MNz4VM77Mwcdu05a4TO:b-fw6sjw) ([raw file](https://github.com/cockroachdb/cockroach/blob/bee0662691c16223956156c2c75b1cfab9429271/pkg/sql/opt/optbuilder/select.go#L529)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Ahh I see. I like this definition. I'll work on making that change for `addPartialIndexPredicatesForTable` and checking the outer cols where it's used. I think the only place is in `scan_index_iter.go`. I think that will clean things up and be less error prone.

So nothing needs to change for `addComputedColsForTable`, but just below here `tabMeta.ComputedCols` is accessed, so I guess that's the place we'd check the outer cols, if it's necessary. And I don't think its necessary unless FKs can reference virtual columns, correct? I guess that's originally what I was trying to call out, but explained my thoughts poorly.
</blockquote></details>

Ohh, yeah, good point. I added a comment to the function and added an assertion (and constructed the ProjectionsItem properly while I'm at it).

I'll think about how to improve this API. I think maybe the cases where we scan specific ordinals should use a separate simplified path.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 13 of 13 files at r1, 1 of 1 files at r2, 2 of 5 files at r3, 5 of 5 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57622#-:-MNzHmG42gior33WAzCp:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/optbuilder/select.go, line 544 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/57622#-MNzFZiL-jGEr_UI2Leu:-MNzFZiM5h5ejUqYZ9SY:b-ak70vf) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c6d900d3293760cfbef5dd79b1f78c65a60d072/pkg/sql/opt/optbuilder/select.go#L544)):*
> ```Go
> 		virtualColIDs.ForEach(func(col opt.ColumnID) {
> 			item := b.factory.ConstructProjectionsItem(tabMeta.ComputedCols[col], col)
> 			if !item.ScalarProps().OuterCols.SubsetOf(tabColIDs) {
> ```

Is it not possible for one virtual column to depend on another? (Maybe you discussed this above, but wouldn't hurt to add an explicit comment or TODO)

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57622)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/optbuilder/select.go, line 544 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/57622#-MNzFZiL-jGEr_UI2Leu:-MNzOENU3eC5bpq3Uz2j:b9ent9c) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c6d900d3293760cfbef5dd79b1f78c65a60d072/pkg/sql/opt/optbuilder/select.go#L544)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Is it not possible for one virtual column to depend on another? (Maybe you discussed this above, but wouldn't hurt to add an explicit comment or TODO)
</blockquote></details>

Added a TODO. It will be an internal error for now. The checklist in #57608 tracks either supporting this case, or disallowing the creation of such columns in the first place.

**Pull request merged**
