### PR TITLE
storage: Reject preemptive snapshots for N seconds after raft snapshots

### PR DESCRIPTION
**Pull request by a-robinson**
This serves as a replacement for the broken estimatedCommitIndex
mechanism originally added by #13043, which is removed by the first commit.

Consider this an alternative to the other option discussed in #21261, which is just to block preemptive snapshots after restart for some amount of time.

### CODE REVIEW

**Comment by a-robinson** [comment]
If this approach looks good, I'll write a test. So far I've only tested it via allocsim.

**Comment by petermattis** [comment]
The approach looks good to me. Certainly a lot simpler than the estimated-behind mechanism. @bdarnell should chime in as well.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21386#-:-L2WjPFX5HSW2aKtLN8a:b-xfw0kl)*

**Comment by bdarnell** [comment]
LGTM, although I think that the more conservative change would be to block snapshots at startup (until idleReplicaElectionTime), since that's effectively all the estimatedCommitIndex check was doing. I'm concerned that an arbitrary 10s delay on rebalancing after a raft snapshot might impede recovery in chaos testing.  

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21386#-:-L2WlXfycxu9WjRoRUGy:b-1okdvp)*

**Comment by a-robinson** [comment]
> block snapshots at startup (until idleReplicaElectionTime), since that's effectively all the estimatedCommitIndex check was doing

Technically it blocked them for longer, since it blocked them until `idleReplicaElectionTime` plus however long it took for all raft groups to either quiesce or get a non-zero estimated commit index. I agree with your general sentiment though.

I'll write up a test.

**Comment by a-robinson** [comment]
...and then run some chaos testing, spinning blue back up if I can.

**Comment by a-robinson** [comment]
Unit test added, and I believe I have chaos running on the alex-chaos roachprod cluster (although there haven't been any events yet. We'll see whether the chaos I hacked together works properly and how the cluster does over the weekend.

**Comment by bdarnell** [comment]
> Technically it blocked them for longer, since it blocked them until idleReplicaElectionTime plus however long it took for all raft groups to either quiesce or get a non-zero estimated commit index.

Or it may have blocked them for less time, since if it was a single restarted node, the leader could send it a new MsgApp (and therefore a commit index) immediately. The idleReplicaElectionTime didn't act as a minimum unless all nodes restarted at once.

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21386#-:-L2bA_uLMGfDTb35JPUU:blgge7d)*

**Comment by a-robinson** [comment]
Fair point. I'm totally fine with just ripping out the old code and sticking with a time-based mechanism. I think you have to convince @petermattis, though, if that's what you believe is best.

So far things look good on my chaos cluster. It's taking one node down approximately every hour for a random duration between 1 and 20 minutes, the same as blue's chaos config. After a node comes back up, it rejects preemptive snapshots for around 10 seconds before it begins applying them.

**Comment by petermattis** [comment]
> Fair point. I'm totally fine with just ripping out the old code and sticking with a time-based mechanism. I think you have to convince @petermattis, though, if that's what you believe is best.
> 
> So far things look good on my chaos cluster. It's taking one node down approximately every hour for a random duration between 1 and 20 minutes, the same as blue's chaos config. After a node comes back up, it rejects preemptive snapshots for around 10 seconds before it begins applying them.

I'm fine with ripping out the old mechanism and using a purely time-based mechanism, but we'll need to test it. @a-robinson Note that chaos is "easier" when there is relatively little data on the cluster. Once the nodes fill up the recovery from chaos generally worsened.

**Comment by bdarnell** [comment]
I think testing here should start with reproducing a problem to be fixed by this mechanism. If you only have the first commit in this branch (removing estimatedCommitIndex with no replacement), do you see problems under chaos? Then we'll be able to tell whether blocking rebalancing snapshots at startup and/or after catch-up snapshots will improve things.

**Comment by a-robinson** [comment]
Will do.

Also, this commit had a few bad hiccups over the weekend (see below for an example), so I'll need to try a control group running at master as well if running at the first commit isn't much better. It's possible that we've regressed.

screen shot 2018-01-16 at 9 45 32 am

**Comment by a-robinson** [comment]
Running with just the first commit also caused a bad outage during chaos, one which I was able to observe while it was happening. It wasn't conclusive, but it looked as though the disk was being overloaded as the remaining nodes tried to up-replicate the dead node's data. I'm suspicious of the new compaction queue, since adding compactions during heavy rebalancing periods puts more load on the disk (and cpu, for what it's worth) when it's already busier than usual.

I'm now running without either of these commits to see how chaos affects things without any modifications. If it still has problems, I'll try running without the compaction queue.

**Comment by a-robinson** [comment]
I should note that the two changes here shouldn't make any difference - the problems are happening *while* a node is down, not after it comes back up.

**Comment by a-robinson** [comment]
Opened https://github.com/cockroachdb/cockroach/issues/21528 to track the problem of a node being down during chaos.

There have been no issues recovering after the downed nodes come back with any of the three approaches tested, so it doesn't provide any real data to work with here. I do think that having back-pressure on preemptive snapshots in the case of node slowness is valuable, and I do think that raft snapshots are a decent metric for that, but without any motivating scenarios it's hard to justify making changes. What do you want to do, @bdarnell?

**Comment by bdarnell** [comment]
I don't think we should introduce throttling based on raft snapshots without some better evidence that it solves a problem. 

The more interesting question is what we do about the EstimatedCommitIndex now that we know it's largely broken. Rip it out completely, try to fix it, replace it with a simpler version of the part of it that did work? I'm inclined to remove it completely since things seem to be working OK in that case (and we have a plausible explanation for the reason a once-necessary change no longer matters: deleting old replicas is now much more efficient)

**Comment by a-robinson** [comment]
Alright, I'll keep the throttling based on raft snapshots around in https://github.com/a-robinson/cockroach/tree/rejectsnapshots2 if we later find something that needs it, but have whittled this PR down to just removing the `estimatedCommitIndex` code.

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21386#-:-L3JTwxFc3IbbGi3-atI:bnfp4nl)*

**Pull request merged**
