### PR TITLE
roachtest/bank: don't start chaos until nodes are serving SQL

### PR DESCRIPTION
**Pull request by nvb**
Informs #30064.

Release note: None

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Please hold off on this. I thought it would fix the second class of failures we saw in #30064, but I just had a repro so it doesn't seem like it did.

**Review by tbg — COMMENTED** [review]
I'm surprised why you didn't change the `break` on l156 into a `return`.

**Comment by nvanbenschoten** [comment]
I still have this cleanup on my plate, including the l156 fix, but I'd like to actually get this test working without flakes first, which is turning out to be surprisingly tricky.

**Comment by nvanbenschoten** [comment]
Ok, this has been updated based on the discussion in #30064. PTAL.

Things changed a bit in https://github.com/cockroachdb/cockroach/pull/31011, so the first commit was replaced with a bit of cleanup around that change.

**Review by petermattis — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30989#-:-LOsRTws6JM3puTq9Vhf:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/bank.go, line 210 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30989#-LOsR0ox81S1lvwox6Nt:-LOsR0ox81S1lvwox6Nu:b-zeavw) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdb5c37d7dace3a8d9c96581c8ed8561cdbaa413/pkg/cmd/roachtest/bank.go#L210)):*
> ```Go
> 	consistentIdx int,
> ) {
> 	s.waitGroup.Add(1)
> ```

Is this kosher? You're calling `Add` from a goroutine and then calling `Wait` from the main routine. I think this would hit an internal assertion in `WaitGroup`, except that the `Wait` doesn't happen right away.
___
*[pkg/cmd/roachtest/bank.go, line 215 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30989#-LOsRKbb7ksZkf_MJNHg:-LOsRKbb7ksZkf_MJNHh:bnkuzx2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bd0decd3f5cf3e652b54e148c67c2ec6b823d11/pkg/cmd/roachtest/bank.go#L215)):*
> ```Go
> 	// Don't begin the chaos monkey until all nodes are serving SQL connections.
> 	// This ensures that we don't test cluster initialization under chaos.
> 	for i := 0; i < c.nodes; i++ {
> ```

Nit: `for i := 0; i <= c.nodes; i++`. Then in the body you can use `i` instead of `i+1`.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30989)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/bank.go, line 210 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30989#-LOsR0ox81S1lvwox6Nt:-LOsRoErC2eZo4-kw7va:be3nl2t) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdb5c37d7dace3a8d9c96581c8ed8561cdbaa413/pkg/cmd/roachtest/bank.go#L210)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is this kosher? You're calling `Add` from a goroutine and then calling `Wait` from the main routine. I think this would hit an internal assertion in `WaitGroup`, except that the `Wait` doesn't happen right away.
</blockquote></details>

Yeah, you're absolutely right.
___
*[pkg/cmd/roachtest/bank.go, line 215 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30989#-LOsRKbb7ksZkf_MJNHg:-LOsRrH4CCmPBKFbFvLM:b-ifz3e4) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bd0decd3f5cf3e652b54e148c67c2ec6b823d11/pkg/cmd/roachtest/bank.go#L215)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: `for i := 0; i <= c.nodes; i++`. Then in the body you can use `i` instead of `i+1`.
</blockquote></details>

Make it `for i := 1; i <= c.nodes; i++` and you've got a deal.

**Review by tbg — APPROVED** [review]
:lgtm: mod Peter's comments which it looks you're fixing up right now.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30989#-:-LOsV2qT2tBf6GZyM-dU:biglics)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30989)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/cmd/roachtest/bank.go, line 210 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30989#-LOsR0ox81S1lvwox6Nt:-LOsWdRl9N48MNWCyUBe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdb5c37d7dace3a8d9c96581c8ed8561cdbaa413/pkg/cmd/roachtest/bank.go#L210)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yeah, you're absolutely right.
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/bank.go, line 215 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30989#-LOsRKbb7ksZkf_MJNHg:-LOsWdiK8HX2K6A0x6iP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5bd0decd3f5cf3e652b54e148c67c2ec6b823d11/pkg/cmd/roachtest/bank.go#L215)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Make it `for i := 1; i <= c.nodes; i++` and you've got a deal.
</blockquote></details>

Done.

**Review by petermattis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30989)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Review by a-robinson — APPROVED** [review]
Having just read through the recent comments on #30064 I agree this is the right change to make. We should also reduce the migration lease duration, though. There's no need for it to be so long given that we renew it in the background while running migrations.

**Comment by nvanbenschoten** [comment]
TFTRs. 

> We should also reduce the migration lease duration, though.

I was hoping for a quick fix here, but it looks like this is tied to the `sql.LeaseManager`, which uses the same duration for all leases. This will have to wait on other improvements to the leasing system, like https://github.com/cockroachdb/cockroach/issues/24041.

bors r+

**Pull request merged**
