### PR TITLE
sql: helper to create pgbench-compatible schema and data

### PR DESCRIPTION
**Pull request by dt**
I split this into a lib and main since I expect to want to use the lib to setup benchmarks elsewhere,
but I also want a  to do manual runs of pgbench with various settings.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4573)

### CODE REVIEW

**Comment by bdarnell** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/pgbenchsetup/cmd/pgbenchsetup/main.go, line 67 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4573#-KB9WWFZNa0LHw5179EN:-KB9WWFZNa0LHw5179EO:-407774839) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4d7632e4245c59d272de0f97f7ef5ec9c52d1a/sql/pgbenchsetup/cmd/pgbenchsetup/main.go#L67)):*
Do we not support placeholders for drop/create database?

---

*[sql/pgbenchsetup/setup.go, line 28 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4573#-KB9W13nTwAWyRo5cKy6:-KB9W13nTwAWyRo5cKy7:1050921013) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4d7632e4245c59d272de0f97f7ef5ec9c52d1a/sql/pgbenchsetup/setup.go#L28)):*
We should avoid constructing queries with `Sprintf` (where possible - there's no good alternative for the bulk insert query you construct below). It's best to specify the database in the url (even if that means using a separate connection to create the database and throw it away).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4573)*

**Comment by petermattis** [comment]
Rather than `sql/pgbenchsetup`, perhaps the package should be `sql/pgbench` in anticipation of a go port of `pgbench` that is easier to run as part of our regular benchmark suite or use in acceptance tests.

---

Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[sql/pgbenchsetup/cmd/pgbenchsetup/main.go, line 29 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4573#-KB9TRa0MQfrhvPusCjj:-KB9TRa0MQfrhvPusCjk:867022391) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4d7632e4245c59d272de0f97f7ef5ec9c52d1a/sql/pgbenchsetup/cmd/pgbenchsetup/main.go#L29)):*
Probably better to use the stdlib `log` package here.

---

*[sql/pgbenchsetup/setup.go, line 24 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4573#-KB9TbD3cbl75tvBt4Il:-KB9TbD3cbl75tvBt4Im:1700997001) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4d7632e4245c59d272de0f97f7ef5ec9c52d1a/sql/pgbenchsetup/setup.go#L24)):*
Ditto.

---

*[sql/pgbenchsetup/setup.go, line 90 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4573#-KB9TkgxQHgyThB-w1-w:-KB9TkgxQHgyThB-w1-x:1540222201) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4d7632e4245c59d272de0f97f7ef5ec9c52d1a/sql/pgbenchsetup/setup.go#L90)):*
Where do these values come from? If copied from `pgbench` add a short comment indicating that.

---

*[sql/pgbenchsetup/setup.go, line 104 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4573#-KB9Tdmw3t-qDyIhIJ6-:-KB9Tdmw3t-qDyIhIJ60:712914405) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4d7632e4245c59d272de0f97f7ef5ec9c52d1a/sql/pgbenchsetup/setup.go#L104)):*
No need for the else. You've already returned in the other branches.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4573#-:-KB9WFRiQV8VWsncn8DW:-2080115776)*

**Comment by dt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[sql/pgbenchsetup/cmd/pgbenchsetup/main.go, line 29 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4573#-KB9TRa0MQfrhvPusCjj:-KB9xxPKrYkO4Ec2uQV0:1274829152) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4d7632e4245c59d272de0f97f7ef5ec9c52d1a/sql/pgbenchsetup/cmd/pgbenchsetup/main.go#L29)):*
I did initially but the linter complained. Is there a way to whitelist that I missed?

---

*[sql/pgbenchsetup/setup.go, line 28 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4573#-KB9W13nTwAWyRo5cKy6:-KBA2Y1sHPFDcimzj89j:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4d7632e4245c59d272de0f97f7ef5ec9c52d1a/sql/pgbenchsetup/setup.go#L28)):*
Done.

---

*[sql/pgbenchsetup/setup.go, line 90 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4573#-KB9TkgxQHgyThB-w1-w:-KB9yE4GeNQJvI9Cf2wS:1575871547) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4d7632e4245c59d272de0f97f7ef5ec9c52d1a/sql/pgbenchsetup/setup.go#L90)):*
Yeah, this basically a is a minimally edited `pg_dump` of a db created by `pgbench -i`. I mentioned that in the comment on the function, but will repeat that here, closer to the magic numbers.

---

*[sql/pgbenchsetup/setup.go, line 104 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4573#-KB9Tdmw3t-qDyIhIJ6-:-KB9xjsT6njoY5ofbuGn:-565254802) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4d7632e4245c59d272de0f97f7ef5ec9c52d1a/sql/pgbenchsetup/setup.go#L104)):*
Yeah, it was just to have x in scope, since there was a whole chain of dependent 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4573)*

**Comment by bdarnell** [comment]
LGTM

---

Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[sql/pgbenchsetup/cmd/pgbenchsetup/main.go, line 29 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4573#-KB9TRa0MQfrhvPusCjj:-KBA3huG4MJX-Glcl40p:-501777223) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4d7632e4245c59d272de0f97f7ef5ec9c52d1a/sql/pgbenchsetup/cmd/pgbenchsetup/main.go#L29)):*
Yeah, one of the `grep` lines in the `Makefile`. But I'd probably use `fmt.Printf` and `panic` (or return an error to a caller that will handle it) instead of either log package for a tool like this.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4573#-:-KBA4Z3t99kJALTWZp30:676834233)*

**Comment by dt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[sql/pgbenchsetup/cmd/pgbenchsetup/main.go, line 29 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4573#-KB9TRa0MQfrhvPusCjj:-KBA8qUcj_gVXpPazByx:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4d7632e4245c59d272de0f97f7ef5ec9c52d1a/sql/pgbenchsetup/cmd/pgbenchsetup/main.go#L29)):*
Done.

---

*[sql/pgbenchsetup/cmd/pgbenchsetup/main.go, line 67 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4573#-KB9WWFZNa0LHw5179EN:-KBAAo9EE7TGctcnAv9L:202463974) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4d7632e4245c59d272de0f97f7ef5ec9c52d1a/sql/pgbenchsetup/cmd/pgbenchsetup/main.go#L67)):*
I believe that is the case -- got a syntax error when I tried `$1`.

---

*[sql/pgbenchsetup/setup.go, line 24 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4573#-KB9TbD3cbl75tvBt4Il:-KBAAy_kITlyxqLtkVJ7:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4d7632e4245c59d272de0f97f7ef5ec9c52d1a/sql/pgbenchsetup/setup.go#L24)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4573)*

**Comment by petermattis** [comment]
LGTM

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/pgbenchsetup/cmd/pgbenchsetup/main.go, line 67 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4573#-KB9WWFZNa0LHw5179EN:-KBDe_V7RfI9WnJyxG76:1186329680) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4d7632e4245c59d272de0f97f7ef5ec9c52d1a/sql/pgbenchsetup/cmd/pgbenchsetup/main.go#L67)):*
We should file an issue to fix that. Shouldn't be difficult and it came up in another context recently.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4573#-:-KBDeoWFojtv9gP__b-m:676834233)*

**Comment by dt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/pgbench/cmd/pgbenchsetup/main.go, line 67 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4573#-KB9WWFZNa0LHw5179EN:-KBDpMbgssz2LAXwB1BE:-531436004) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b4d7632e4245c59d272de0f97f7ef5ec9c52d1a/sql/pgbench/cmd/pgbenchsetup/main.go#L67)):*
#4596

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4573)*

**Pull request merged**
