### PR TITLE
sql: Use SemanticType and Equivalent exclusively (patch 3/)

### PR DESCRIPTION
**Pull request by knz**
Split from #36598 cc @andy-kimball 

When comparing types.T, do not use == or FamilyEqual. Instead, use
Equivalent and a new SemanticType method that exposes the type codes
defined in types.proto. Remove the FamilyEqual method altogether,
and get rid of Family singletons in the types package.

These changes have the following advantages:

1. No more confusion over whether it's OK to use ==. It should never
   be used now, in favor of Equivalent or SemanticType. Comparing
   SemanticTypes gives almost the same behavior as using == to compare
   against singleton types, only it's more reliable and future-proofs
   for future commits where type instances are no longer guaranteed to
   be singletons (e.g. because of differing OIDs).

2. No more confusion over when to use FamilyEqual. It's now gone, in
   favor of using SemanticType.

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
@rytaft @RaduBerinde please review the `opt` part of this patch.

@BramGruneir @bobvawter please review the remainder of the changes in the `sql` packages.

Any or @danhhz please review the `ccl` changes.

**Review by RaduBerinde — COMMENTED** [review]
`opt` changes LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36700#-:-Lc6LGDW1eBTiAGD_pfd:b-g4acc7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter, @BramGruneir, @RaduBerinde, and @rytaft)

**Review by jordanlewis — COMMENTED** [review]
> Reviewed 67 of 67 files at r1, 127 of 127 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36700)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter, @BramGruneir, @knz, and @rytaft)

___
*[pkg/ccl/partitionccl/partition_test.go, line 853 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36700#-Lc9Yi7eA43WYt7Ao--s:-Lc9Yi7f9HLChnw6Oq9w:b-9eogiw) ([raw file](https://github.com/cockroachdb/cockroach/blob/36e8fd18c5c60155c23e727e5b84ed20ca686dd6/pkg/ccl/partitionccl/partition_test.go#L853)):*
> ```Go
> 		semType := types.SemanticType(semTypeID)
> 		switch semType {
> 		case types.ARRAY, types.TUPLE, types.JSONB, types.ANY:
> ```

I've noticed you adding ANY to these kinds of lists in a few places - does that make sense? Wouldn't types.UNKNOWN also belong there? Or maybe we don't have a types.UNKNOWN. Either way, I'm not sure why you're changing this in tests - is it important to do?
___
*[pkg/sql/exec_util.go, line 684 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36700#-Lc9ZjdE2k7xWls7o4_B:-Lc9ZjdE2k7xWls7o4_C:b-fw5nli) ([raw file](https://github.com/cockroachdb/cockroach/blob/36e8fd18c5c60155c23e727e5b84ed20ca686dd6/pkg/sql/exec_util.go#L684)):*
> ```Go
> func checkResultType(typ types.T) error {
> 	// Compare all types that can rely on == equality.
> 	switch typ.SemanticType() {
> ```

Why can you get rid of the UnwrapType here? Did you already get rid of oid wrapper in this patch? I'm surprised the tests would pass.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36700)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter, @BramGruneir, @jordanlewis, and @rytaft)

___
*[pkg/ccl/partitionccl/partition_test.go, line 853 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36700#-Lc9Yi7eA43WYt7Ao--s:-Lc9juR49H8MRtlgci4x:b9axrmw) ([raw file](https://github.com/cockroachdb/cockroach/blob/36e8fd18c5c60155c23e727e5b84ed20ca686dd6/pkg/ccl/partitionccl/partition_test.go#L853)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I've noticed you adding ANY to these kinds of lists in a few places - does that make sense? Wouldn't types.UNKNOWN also belong there? Or maybe we don't have a types.UNKNOWN. Either way, I'm not sure why you're changing this in tests - is it important to do?
</blockquote></details>

I added `ANY` to the `SemanticType` enumeration, so it now needed to be excluded in several places. I added it because the unified `types.T` will need to be able to represent types used during the analysis and type checking phase, which need support for `ANY`. Before, `ColumnType` was never used in those scenarios, so didn't need `ANY`. I added something to the release note about adding `ANY`.

As for `types.UNKNOWN` (still called `types.NULL` as of this patch), it was already present in the `SemanticType` enum, so I didn't need to add it to any lists. This code worked before with `types.NULL` present, so it must still work in the same way. I didn't try and understand every usage in cases where nothing material had changed, so I don't know why this code doesn't exclude `types.NULL`.
___
*[pkg/sql/exec_util.go, line 684 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36700#-Lc9ZjdE2k7xWls7o4_B:-Lc9jHwZDsn7U4zGrHuf:bb42ct3) ([raw file](https://github.com/cockroachdb/cockroach/blob/36e8fd18c5c60155c23e727e5b84ed20ca686dd6/pkg/sql/exec_util.go#L684)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Why can you get rid of the UnwrapType here? Did you already get rid of oid wrapper in this patch? I'm surprised the tests would pass.
</blockquote></details>

Because we're now checking type "family" using the `SemanticType` method rather than using == to check equality of type instances. This is a better way to do what `UnwrapType` + instance equality was trying to do.

**Comment by danhhz** [comment]
ccl changes LGTM

**Review by BramGruneir — APPROVED** [review]
:lgtm:  

Just one nit.

> Reviewed 67 of 67 files at r1, 127 of 127 files at r2, 19 of 19 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36700#-:-LcgCs-g3EAGeSzo_h49:bqxqziq)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bobvawter, @jordanlewis, @knz, and @rytaft)

___
*[pkg/sql/sqlbase/column_type_encoding.go, line 1115 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36700#-LcgCg_8-kN8JNu0nfWQ:-LcgCg_8-kN8JNu0nfWR:bne1ctn) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2acf5e792f86f266e5be322c21da5e12aaf5a00/pkg/sql/sqlbase/column_type_encoding.go#L1115)):*
> ```Go
> 
> func checkElementType(paramType types.T, columnType types.ColumnType) error {
> 	semanticType := paramType.SemanticType()
> ```

Any need to declare this variable?  It can just be in the if statement directly.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36700)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bobvawter, @BramGruneir, @jordanlewis, and @rytaft)

___
*[pkg/sql/sqlbase/column_type_encoding.go, line 1115 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36700#-LcgCg_8-kN8JNu0nfWQ:-LcpmdkC-QcYch-0eMaj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2acf5e792f86f266e5be322c21da5e12aaf5a00/pkg/sql/sqlbase/column_type_encoding.go#L1115)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Any need to declare this variable?  It can just be in the if statement directly.
</blockquote></details>

Done.

**Pull request closed without merging**
