### PR TITLE
storage/engine: add BenchmarkRocksDBDeleteRangeIterate

### PR DESCRIPTION
**Pull request by petermattis**
Demonstrate the performance problem with iterating through a range
tombstone.

```
name                                        time/op
RocksDBDeleteRangeIterate/entries=10-8      5.36µs ±10%
RocksDBDeleteRangeIterate/entries=1000-8    85.2µs ± 2%
RocksDBDeleteRangeIterate/entries=100000-8  7.93ms ± 3%
```

See #24029

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
@benesch Only 47 lines for the upstream fix: https://github.com/cockroachdb/rocksdb/compare/31fe461d05e943a40d6b28414806ab7e82a27e71...8beb3f8276028fb7e83ce0bdc997e16d4ba5435f

```
name                                        old time/op  new time/op  delta
RocksDBDeleteRangeIterate/entries=10-8      5.34µs ± 2%  3.39µs ± 3%  -36.50%  (p=0.000 n=9+10)
RocksDBDeleteRangeIterate/entries=1000-8    91.8µs ± 3%   3.4µs ± 3%  -96.30%  (p=0.000 n=10+10)
RocksDBDeleteRangeIterate/entries=100000-8  8.58ms ± 4%  0.00ms ± 4%  -99.96%  (p=0.000 n=10+10)
```

**Comment by benesch** [comment]
Holy cow. Those are some impressive numbers.

FYI plumbing an iterative upper bound is not quite as trivial as we hoped
thanks to some annoying string ownership issues.

**Comment by tschottdorf** [comment]
Not bad! Is that upstream code WIP or already polished? @benesch I assume you're going to take this for a spin?

**Comment by petermattis** [comment]
The upstream code is WIP. I don’t think it will help the clearange
roachtest until we get rid of the empty ranges in those fixtures. The gaps
from the empty ranges will foil this optimization. There is a more
complicated optimization that could help even with the gaps. We could have
lower level iterators seek to the end of a covering range deletion
tombstone. I’m going to investigate that as well.

**Comment by petermattis** [comment]
I've pushed the RocksDB code upstream (see https://github.com/facebook/rocksdb/pull/3969). I'm pretty sure the approach is copacetic.

**Comment by petermattis** [comment]
I've added a second optimization upstream in RocksDB that allows `LevelIterator` to skip over ranges of deleted keys. I think we should consider both of these RocksDB changes for back-porting to 2.0, though I want to add a lot more test coverage before doing so.

**Comment by petermattis** [comment]
@benesch This PR now contains everything I was testing with last night.

**Pull request closed without merging**
