### PR TITLE
builder: upgrade to go1.11

### LINKED ISSUE #29827: perf: upgrade from go1.10 to go1.11
`go1.11` was recently released: https://golang.org/doc/go1.11. I ran our standard benchmarks against it to get an idea of what kind of performance we can expect when we upgrade. This will may influence our decision of whether the upgrade before or after our 2.1 release.

All benchmarks were run on GCE `n1-standard-4` linux machines with the `nobarrier` SSD mount option. I ran 3 benchmarks, `kv0`, `kv95`, and `tpcc1-nowait`. Each benchmark was run on a single node cluster and on a three node cluster. Each configuration was run 5 times with `go1.10` and 5 times with `go1.11`. Each trial was run for 3 minutes, with a cluster wipe in-between.

```
name               old ops/sec  new ops/sec  delta
kv0-1node           5.78k ± 4%   6.41k ± 3%  +10.93%  (p=0.008 n=5+5)
kv0-3node           7.11k ± 2%   7.24k ± 1%   +1.81%  (p=0.056 n=5+5)
kv95-1node          9.63k ± 3%  10.58k ± 2%   +9.89%  (p=0.008 n=5+5)
kv95-3node          16.7k ± 1%   16.8k ± 4%   +0.52%  (p=0.151 n=5+5)
tpcc-nowait-1node    75.6 ± 4%    78.2 ± 3%   +3.49%  (p=0.056 n=5+5)
tpcc-nowait-3node    49.8 ± 2%    49.4 ± 5%     ~     (p=1.000 n=5+5)

name               old p50(ms)  new p50(ms)  delta
kv0-1node            10.5 ± 0%     9.4 ± 0%  -10.48%  (p=0.029 n=4+4)
kv0-3node            7.90 ± 0%    7.78 ± 2%     ~     (p=0.333 n=4+5)
kv95-1node           6.30 ± 0%    5.80 ± 0%   -7.94%  (p=0.079 n=4+5)
kv95-3node           3.44 ± 2%    3.40 ± 0%     ~     (p=0.444 n=5+5)
tpcc-nowait-1node    88.1 ± 5%    86.4 ± 3%     ~     (p=0.643 n=5+5)
tpcc-nowait-3node     176 ± 5%     178 ± 6%     ~     (p=0.881 n=5+5)

name               old p99(ms)  new p99(ms)  delta
kv0-1node            29.2 ± 4%    26.4 ± 5%   -9.33%  (p=0.008 n=5+5)
kv0-3node            28.3 ± 0%    28.3 ± 0%     ~     (all equal)
kv95-1node           19.9 ± 0%    17.8 ± 0%  -10.55%  (p=0.079 n=4+5)
kv95-3node           16.3 ± 0%    15.9 ± 2%   -2.21%  (p=0.095 n=4+5)
tpcc-nowait-1node     631 ± 6%     617 ± 3%     ~     (p=0.683 n=5+5)
tpcc-nowait-3node     772 ± 0%     765 ± 5%     ~     (p=0.968 n=4+5)
```

cc. @petermattis @a-robinson @benesch

### PR DESCRIPTION
**Pull request by benesch**
Go 1.11 brings us some nice performance improvements on single-node
clusters. See #29827 for benchmark results.

Fix #29827.

Release note: None

### CODE REVIEW

**Review by bdarnell — APPROVED** [review]

**Review by nvb — APPROVED** [review]

**Comment by couchand** [comment]
Friendly reminder that this needs widespread announcement before merging.

Also, shouldn't there be an update to `build/go-version-check.sh` as well?

**Comment by benesch** [comment]
> Friendly reminder that this needs widespread announcement before merging.

Yep, done.

> Also, shouldn't there be an update to build/go-version-check.sh as well?

Yeah, per our discussion in #engineering I'll be sure to add that. I'll also be reformatting everything to go1.11 style.

**Comment by benesch** [comment]
Ok, PTAL. I've reformatted all our Go files with Go 1.11 style and bumped the minimum required Go version.

**Review by RaduBerinde — APPROVED** [review]

**Review by nvb — APPROVED** [review]

**Comment by benesch** [comment]
bors r=bdarnell,raduberinde,nvanbenschoten

**Comment by benesch** [comment]
Flaky change feed test, it seems.

bors r=bdarnell,raduberinde,nvanbenschoten

**Comment by danhhz** [comment]
Flaky test is the same issue as #30258 I think

**Pull request merged**
