### PR TITLE
opt: fix lookup join bug, cross-check logical props in testrace

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: fix lookup join generating extra column

A separate change that cross-checks logical properties across
expressions in a group revealed that in some cases we have a lookup
join expression which generates more columns than in OutputCols.

The case is when we are using a non-covering secondary index, and not
all PK columns were output columns of the original join. For example:

```
CREATE TABLE abc (a INT PRIMARY KEY, b INT, c INT, INDEX (b));
CREATE TABLE x (x INT);
SELECT b, c, x FROM abc JOIN x ON x=b;
```

The plan here would be to do a lookup in the index on `b` and
index-join those results to get the corresponding values of `c`:

```
inner-join (lookup abc)
 ├── columns: b:2(int!null) c:3(int) x:4(int!null)
 ├── key columns: [1] = [1]
 ├── fd: (2)==(4), (4)==(2)
 ├── inner-join (lookup abc@secondary)
 │    ├── columns: a:1(int!null) b:2(int!null) x:4(int!null)
 │    ├── key columns: [4] = [2]
 │    ├── fd: (1)-->(2), (2)==(4), (4)==(2)
 │    ├── scan x
 │    │    └── columns: x:4(int)
 │    └── filters [type=bool, outer=(2,4), constraints=(/2: (/NULL - ]; /4: (/NULL - ]), fd=(2)==(4), (4)==(2)]
 │         └── x = b [type=bool, outer=(2,4), constraints=(/2: (/NULL - ]; /4: (/NULL - ])]
 └── true [type=bool]
```

The top lookup join would also produce column `a`, which is not an
`OutputCol` of the original join. Note that in practice I wasn't able
to observe a problem caused by this bug; the execbuilder seems to
tolerate extra columns just fine (though it's possible there are
cornercases where things could blow up).

Normally the fix for this problem would be to simply add a `ProjectOp`
on top of the lookup join. However, going down that path results in a
lot of problems related to statistics - the lookup join would use its
own derived statistics (since it would be in a separate group) and
that results in much larger costs. Trying to address that problem (by
taking into account that the equality columns form a key) opened up
other problems, affecting many plans.

This change fixes this issue by changing the `LookupJoin` semantics to
effectively include a projection. In the future, we can revert this
change once we address the stat issues.

Release note: None

#### opt: cross-check logical properties within memo groups

This change adds testrace-only code to cross-check logical properties
whenever we add a denormalized expression to a group (during
exploration).

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30320)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/props/logical.go, line 512 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30320#-LMd1uXa7-yiPhGrlDOd:-LMd1uXb78ZMiWS7Xlxk:brmarly) ([raw file](https://github.com/cockroachdb/cockroach/blob/6476651b504f7d92099423a4e16aa3c760be7c63/pkg/sql/opt/props/logical.go#L512)):*
> ```Go
> 		}
> 
> 		// XXX these checks might be overzealous - conceivably a subexpression with
> ```

Not sure if I should leave these checks in.

**Review by justinj — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30320#-:-LMdMIy16ShWCrvfrGcr:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/props/logical.go, line 509 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30320#-LMdMrdo29L171JKQVG-:-LMdMrdo29L171JKQVG0:bofejz3) ([raw file](https://github.com/cockroachdb/cockroach/blob/6476651b504f7d92099423a4e16aa3c760be7c63/pkg/sql/opt/props/logical.go#L509)):*
> ```Go
> 		if r1.Cardinality.Max < r2.Cardinality.Min ||
> 			r1.Cardinality.Min > r2.Cardinality.Max {
> 			panic(fmt.Sprintf("cardinality mismatch: %s vs %s", r1.Cardinality, r2.Cardinality))
> ```

are there any cases today where the cardinalities don't match exactly? shouldn't that imply that there are bounds to be improved somewhere?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30320)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/opt/props/logical.go, line 509 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30320#-LMdMrdo29L171JKQVG-:-LMdR0csCuT-zKjYVR16:bw2wavl) ([raw file](https://github.com/cockroachdb/cockroach/blob/6476651b504f7d92099423a4e16aa3c760be7c63/pkg/sql/opt/props/logical.go#L509)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

are there any cases today where the cardinalities don't match exactly? shouldn't that imply that there are bounds to be improved somewhere?
</blockquote></details>

It would, we don't assume that we always derive these perfectly "tight".

I also plan to use this to cross-check across different runs of `optsteps`, I could definitely see that missing some normalizations would affect how well we can establish these bounds (e.g. detecting a contradiction).

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30320#-:-LMh1wKu0-5i9ZwGaAAN:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/memo/logical_props_builder.go, line 528 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30320#-LMgyAnF87U6wMsheYpW:-LMgxwER6_ELuOkaZLOq:bo3ouoz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a85c3c6159e2f3faa56636969ecf2f09bd434026/pkg/sql/opt/memo/logical_props_builder.go#L528)):*
> ```Go
> 
> 	if h.lookupJoinDef != nil && !h.lookupJoinDef.Cols.Equals(relational.OutputCols) {
> 		if !h.lookupJoinDef.Cols.SubsetOf(relational.OutputCols) {
> ```

Can you add a comment here to explain what's going on? i.e. how `relational.OutputCols` came to have too many columns.
___
*[pkg/sql/opt/memo/private_defs.go, line 316 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30320#-LMgyzKq6oP0sPYll_h_:-LMgyzKq6oP0sPYll_ha:bydywh3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a85c3c6159e2f3faa56636969ecf2f09bd434026/pkg/sql/opt/memo/private_defs.go#L316)):*
> ```Go
> 	//
> 	// TODO(radu): this effectively allows an arbitrary projection; it should be
> 	// just a LookupJoin set indicating which columns we should add from the
> ```

what is a "LookupJoin set"?
___
*[pkg/sql/opt/props/logical.go, line 512 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30320#-LMd1uXa7-yiPhGrlDOd:-LMh0ZSh-moMWsMx30Gf:b5nst3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/6476651b504f7d92099423a4e16aa3c760be7c63/pkg/sql/opt/props/logical.go#L512)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Not sure if I should leave these checks in.
</blockquote></details>

Maybe change the "XXX" to a TODO?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30320)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/memo/logical_props_builder.go, line 528 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30320#-LMgyAnF87U6wMsheYpW:-LMh7Gi82fGgyJVEM09l:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a85c3c6159e2f3faa56636969ecf2f09bd434026/pkg/sql/opt/memo/logical_props_builder.go#L528)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Can you add a comment here to explain what's going on? i.e. how `relational.OutputCols` came to have too many columns.
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/private_defs.go, line 316 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30320#-LMgyzKq6oP0sPYll_h_:-LMh8yUv57jSJQq6VknV:bf6c7rb) ([raw file](https://github.com/cockroachdb/cockroach/blob/a85c3c6159e2f3faa56636969ecf2f09bd434026/pkg/sql/opt/memo/private_defs.go#L316)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

what is a "LookupJoin set"?
</blockquote></details>

Fixed, meant "LookupCols"

**Review by rytaft — CHANGES_REQUESTED** [review]
> Reviewed 3 of 8 files at r3, 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30320)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 360 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30320#-LMhK7XD16phtEV8wtKl:-LMhK7XD16phtEV8wtKm:b5qm0iv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a85c3c6159e2f3faa56636969ecf2f09bd434026/pkg/sql/opt/exec/execbuilder/relational_builder.go#L360)):*
> ```Go
> 		return execPlan{}, err
> 	}
> 	var outputCols opt.ColMap
> ```

you can move this declaration down now
___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 909 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30320#-LMhLRej4_sFS-dG2cU0:-LMhKhwGADEkCAbRqqXn:bfwlas0) ([raw file](https://github.com/cockroachdb/cockroach/blob/acf6333efd44e5ca9386306079f36dc7cccb1a3a/pkg/sql/opt/exec/execbuilder/relational_builder.go#L909)):*
> ```Go
> 
> 	// Apply a post-projection if necessary.
> 	if !def.Cols.Equals(inputProps.OutputCols.Union(lookupCols)) {
> ```

can't you just check if `!inputProps.OutputCols.SubsetOf(def.Cols)`?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30320)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 360 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30320#-LMhK7XD16phtEV8wtKl:-LMhQ5Lp1r-MOIGShiQr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a85c3c6159e2f3faa56636969ecf2f09bd434026/pkg/sql/opt/exec/execbuilder/relational_builder.go#L360)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

you can move this declaration down now
</blockquote></details>

Done.
___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 909 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/30320#-LMhLRej4_sFS-dG2cU0:-LMhQILX3RphRYeCGvuS:bv0jxid) ([raw file](https://github.com/cockroachdb/cockroach/blob/acf6333efd44e5ca9386306079f36dc7cccb1a3a/pkg/sql/opt/exec/execbuilder/relational_builder.go#L909)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

can't you just check if `!inputProps.OutputCols.SubsetOf(def.Cols)`?
</blockquote></details>

True, done.

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 6 files at r5, 5 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30320)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Review by andy-kimball — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30320#-:-LMhYmLh8rgIEb5WIcbe:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 3 stale)

**Pull request merged**
