### PR TITLE
roachtest: move to top-level package

### PR DESCRIPTION
**Pull request by tbg**
`roachtest` started as a non-library in `./pkg/cmd/roachtest`. It has
since grown to 36k LOC:

```
$ cat ./pkg/roachtest/*.go | grep -Ev '^//' | wc -l
36490
```

We want to look into cleaning it up. To that end, adopt the standard
pattern of moving the bulk of the code to a library (`./pkg/roachtest`)
and making `./pkg/cmd/roachtest` a thin wrapper around it. This was done
in this commit in the least intrusive way, i.e. without incurring *any*
code changes. We'd really want to keep the flags handling, etc, in the
`main` package and not the library, but that's better done as a
follow-up.

The move also required moving `issues` out of `./pkg/cmd/internal`,
which is fine (arguably all of our code is internal and we'll happily
break external dependencies, so the sporadic use of explicit packages
doesn't make a lot of sense unless applied to the code base as a whole).

Release note: None

### CODE REVIEW

**Review by erikgrinaker — COMMENTED** [review]
> The move also required moving `issues` out of `./pkg/cmd/internal`

I think we should consider moving this into e.g. `./pkg/util/issues`, for two reasons: `./pkg/cmd/issues` implies that there exists a command named `issues`, and it's odd for library code to be importing stuff from `./pkg/cmd` (this should arguably only be frontends for library code).

> Reviewed 185 of 185 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63717#-:-MYJfoKr4V7WW6AAkbhU:b1fqpq5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

**Review by knz — COMMENTED** [review]
Another thing that's important is to update our "forbidden packages" linter to ensure that none of the roachtest code nor its dependencies (including `issues` and its transitive dependencies on the github code) are embedded by mistake in a `cockroach` executable.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63717#-:-MYJiQeY99zHg0BSEOCa:b4bdsyw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

**Comment by tbg** [comment]
Sounds good. Given that I've caught conflicts here already (must've started with an older branch) I'll work these out in separate PRs first.

**Review by andreimatei — COMMENTED** [review]
I've read the commit msg, but can you tell me more about why this is a good idea? I think it'd be a good idea to break roachtest into multiple packages, but I think it'd be better for those packages to live under `pkg/cmd/roachtest/foo`; I think I'd prefer that to `pkg/roachtest`. `pkg/roachtest/main.go` seems dubious as hell.
I generally dislike file moves cause they make following the history on github hard. If we're actually getting some new packages then it can be worth it. But in this patch we're not really getting any new packages, so maybe wait until we do?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63717#-:-MYKwrI-94mL1voyCjyP:bcjkluz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

**Comment by tbg** [comment]
I'll defer any kind of movement. The proximate reason for embarking on this at all was that I was trying to unify the roachtest owners concept with CODEOWNERS/TEAMS.yaml and I realized that the simple approach I had tried to first hook them up couldn't work because you cannot reference symbols from a `main` package. But we can still do this the other way around & it's fine. So I'll hold off on any movement or refactors until there's actually bandwidth to follow through.

**Pull request closed without merging**
