### PR TITLE
tracing: improve interfaces around process boundaries

### PR DESCRIPTION
**Pull request by irfansharif**
We can rid ourselves of the opentracing cruft just a bit more, and add
some type-safety while doing so. While here, we'll also add some text
explaining how tracing data gets propagated across process boundaries.

Release note: None

---

First commit is from #59815, ignore here.

### CODE REVIEW

**Comment by irfansharif** [comment]
CI's failing due to something else:
```
panic: geos: error during GEOS init: geos: cannot load GEOS from dir "/go/src/github.com/cockroachdb/cockroach/lib": geos error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /go/src/github.com/cockroachdb/cockroach/lib/libgeos.so)
```

**Review by tbg — APPROVED** [review]
> Reviewed 22 of 22 files at r1, 14 of 14 files at r2, 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59876)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @angelapwen, @irfansharif, and @knz)

___
*[pkg/util/tracing/tracer.go, line 643 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59876#-MT-ctW-90nC-MQmUdiB:-MT-ctW-90nC-MQmUdiC:b-c2gjwo) ([raw file](https://github.com/cockroachdb/cockroach/blob/169efc975c890e7cd9fd04401dfa74cccf28b8f1/pkg/util/tracing/tracer.go#L643)):*
> ```Go
> //
> // A context wrapping the newly created span is returned, along with the span
> // itself. If non-nil, the caller is responsible to eventually Finish() it.
> ```

nit: for eventually finishing it
___
*[pkg/util/tracing/tracer.go, line 668 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59876#-MT-cz6MEkvrWfVprqCJ:-MT-cz6NAuOnCFkE2o5q:b-c2gjwo) ([raw file](https://github.com/cockroachdb/cockroach/blob/169efc975c890e7cd9fd04401dfa74cccf28b8f1/pkg/util/tracing/tracer.go#L668)):*
> ```Go
> //
> // A context wrapping the newly created span is returned, along with the span
> // itself. If non-nil, the caller is responsible to eventually Finish() it.
> ```

nit: for eventually finishing it

**Comment by irfansharif** [comment]
Re-ordered the commits to decouple it from #59815. TFTR!

bors r+

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59876)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @angelapwen, @irfansharif, @knz, and @tbg)

___
*[pkg/kv/kvserver/replica_proposal.go, line 854 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59876#-MT6OC0i1N9ftw_xL4Yn:-MT6OC0i1N9ftw_xL4Yo:bcvb3na) ([raw file](https://github.com/cockroachdb/cockroach/blob/9687953962d421e911b3571f18ad3f57f83098b2/pkg/kv/kvserver/replica_proposal.go#L854)):*
> ```Go
> 
> 	traceCarrier := tracing.MapCarrier{
> 		Map: make(map[string]string),
> ```

[nit] maybe put this into a `tracing.MakeMapCarrier`
___
*[pkg/util/tracing/tracer.go, line 637 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59876#-MT6NZHAEdXo5nsDo1YU:-MT6NZHAEdXo5nsDo1YV:b-dvcasz) ([raw file](https://github.com/cockroachdb/cockroach/blob/87d102d2f2330503c3f3c450eebef7f40408e0b1/pkg/util/tracing/tracer.go#L637)):*
> ```Go
> // details.
> //
> // The recordings from these spans will be automatically propagated to the
> ```

This deserves some more comment, given that the forked span can outlive the parent. There will be a "partial" recording in the parent, depending when it is retrieved, right?

[nit] s/these spans/the forked span

**Comment by RaduBerinde** [comment]
___
*[pkg/util/tracing/tracer.go, line 637 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/59876#-MT6NZHAEdXo5nsDo1YU:-MT6OTvg85DKNSCmGHxg:bwp1umx) ([raw file](https://github.com/cockroachdb/cockroach/blob/87d102d2f2330503c3f3c450eebef7f40408e0b1/pkg/util/tracing/tracer.go#L637)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This deserves some more comment, given that the forked span can outlive the parent. There will be a "partial" recording in the parent, depending when it is retrieved, right?

[nit] s/these spans/the forked span
</blockquote></details>

Ah, I see there's another PR proposing changes here, never mind

**Pull request merged**
