### PR TITLE
kvclient: add a DistSender bench test

### PR DESCRIPTION
**Pull request by andrewbaptist**
DistSender is in the critical path for most workloads. Having a test to
validate its performance is important as we refactor pieces of the code.

Results from testing (on my Macbook):
```
% ./dev bench pkg/kv/kvclient/kvcoord -f BenchmarkDistSenderSunnyDay -v --ignore-cache --bench-mem --bench-time 10s --timeout 500s
...
BenchmarkDistSenderSunnyDay/rf-3/count-1-conc-10         	 9154686	      1295 ns/op	    1687 B/op	      19 allocs/op
BenchmarkDistSenderSunnyDay/rf-3/count-1-10              	 6430297	      1885 ns/op	    1688 B/op	      19 allocs/op
BenchmarkDistSenderSunnyDay/rf-3/count-1000-conc-10      	 9099680	      1328 ns/op	    1687 B/op	      19 allocs/op
BenchmarkDistSenderSunnyDay/rf-3/count-1000-10           	 5766508	      2068 ns/op	    1688 B/op	      19 allocs/op
BenchmarkDistSenderSunnyDay/rf-3/count-100000-conc-10    	 8566322	      1418 ns/op	    1687 B/op	      19 allocs/op
BenchmarkDistSenderSunnyDay/rf-3/count-100000-10         	 5014044	      2387 ns/op	    1688 B/op	      19 allocs/op
BenchmarkDistSenderSunnyDay/rf-5/count-1-conc-10         	 9126138	      1326 ns/op	    1847 B/op	      19 allocs/op
BenchmarkDistSenderSunnyDay/rf-5/count-1-10              	 6132249	      1968 ns/op	    1848 B/op	      19 allocs/op
BenchmarkDistSenderSunnyDay/rf-5/count-1000-conc-10      	 8855670	      1343 ns/op	    1847 B/op	      19 allocs/op
BenchmarkDistSenderSunnyDay/rf-5/count-1000-10           	 5319618	      2243 ns/op	    1848 B/op	      19 allocs/op
BenchmarkDistSenderSunnyDay/rf-5/count-100000-conc-10    	 8354995	      1457 ns/op	    1847 B/op	      19 allocs/op
BenchmarkDistSenderSunnyDay/rf-5/count-100000-10         	 4643204	      2554 ns/op	    1848 B/op	      19 allocs/op
BenchmarkDistSenderSunnyDay/rf-11/count-1-conc-10        	 8586075	      1410 ns/op	    2328 B/op	      19 allocs/op
BenchmarkDistSenderSunnyDay/rf-11/count-1-10             	 4571427	      2648 ns/op	    2328 B/op	      19 allocs/op
BenchmarkDistSenderSunnyDay/rf-11/count-1000-conc-10     	 8426973	      1421 ns/op	    2328 B/op	      19 allocs/op
BenchmarkDistSenderSunnyDay/rf-11/count-1000-10          	 4166025	      2877 ns/op	    2328 B/op	      19 allocs/op
BenchmarkDistSenderSunnyDay/rf-11/count-100000-conc-10   	 8090950	      1515 ns/op	    2327 B/op	      19 allocs/op
BenchmarkDistSenderSunnyDay/rf-11/count-100000-10        	 3694186	      3208 ns/op	    2328 B/op	      19 allocs/op
```
Epic: none

Release note: None

### CODE REVIEW

**Comment by arulajmani** [comment]
@andrewbaptist is this PR still a draft or ready for review?

**Review by arulajmani — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117996)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117996#-NorgRZvAYM-oCMvlS7T):*
Let's run the benchmark and capture the results in the commit message as well.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_test.go` line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117996#-NorcbsC83nT6bN9vNxY:-NorcbsC83nT6bN9vNxZ:b-fqsjnr) ([raw file](https://github.com/cockroachdb/cockroach/blob/5853742a0e9f27d5cad46aaab6f28a32cc65d976/pkg/kv/kvclient/kvcoord/dist_sender_test.go#L17)):*
> ```Go
> 	"context"
> 	"fmt"
> 	t "log"
> ```

Is this intentional?
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_test.go` line 6257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117996#-Nord2ZC-hifFo1A9Z95:-Nord2ZC-hifFo1A9Z96:bxs4uiy) ([raw file](https://github.com/cockroachdb/cockroach/blob/5853742a0e9f27d5cad46aaab6f28a32cc65d976/pkg/kv/kvclient/kvcoord/dist_sender_test.go#L6257)):*
> ```Go
> 		nodes = append(nodes, &roachpb.NodeDescriptor{NodeID: roachpb.NodeID(i)})
> 	}
> 	replicas = replicas[1:]
> ```

Instead of this, let's either start the loop above from 1 or use `i+1` (instead of `i`) to set IDs. 
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_test.go` line 6259 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117996#-NorfzO44kKkWaNLT3AN:-NorfzO44kKkWaNLT3AO:b-dgrk3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/5853742a0e9f27d5cad46aaab6f28a32cc65d976/pkg/kv/kvclient/kvcoord/dist_sender_test.go#L6259)):*
> ```Go
> 	replicas = replicas[1:]
> 
> 	// Create a singleton range for each key.
> ```

s/singleton/single/g
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_test.go` line 6312 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117996#-Norg7cU9i9FUQFrCk4T:-Norg7cV80Jb1ekO0pxu:bmze63n) ([raw file](https://github.com/cockroachdb/cockroach/blob/5853742a0e9f27d5cad46aaab6f28a32cc65d976/pkg/kv/kvclient/kvcoord/dist_sender_test.go#L6312)):*
> ```Go
> 		},
> 		LatencyFunc: func(id roachpb.NodeID) (time.Duration, bool) {
> 			// Randomize the latency so there is some time spent sorting.
> ```

Is there a better way to do this than the magic constants below?
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_test.go` line 6347 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117996#-NorezXT621hNF1svDoK:-NorezXT621hNF1svDoL:b-gxocvi) ([raw file](https://github.com/cockroachdb/cockroach/blob/5853742a0e9f27d5cad46aaab6f28a32cc65d976/pkg/kv/kvclient/kvcoord/dist_sender_test.go#L6347)):*
> ```Go
> 				// synchronizes across threads.
> 				if _, pErr := kv.SendWrapped(ctx, ds, get); pErr != nil {
> 					t.Fatal(pErr)
> ```

This should be `b.Fatal`, right?

**Review by andrewbaptist — COMMENTED** [review]
TFTR - updated and should be good for another round now. Changes were slightly more extensive as I wanted to clean up the way we chose leaseholders and latencies but I think it is cleaner now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117996#-:-NortPkXACa6HbLBcu-K:bssn1q1)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117996#-NorgRZvAYM-oCMvlS7T):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Let's run the benchmark and capture the results in the commit message as well.
</blockquote></details>

Done
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_test.go` line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117996#-NorcbsC83nT6bN9vNxY:-NorjN1O2LFo2UyvddJ0:bs9apow) ([raw file](https://github.com/cockroachdb/cockroach/blob/5853742a0e9f27d5cad46aaab6f28a32cc65d976/pkg/kv/kvclient/kvcoord/dist_sender_test.go#L17)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Is this intentional?
</blockquote></details>

No. I didn't even notice that. It was caused by the use of `t.Fatal` rather than `b.Fatal` below. Fixed both.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_test.go` line 6257 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117996#-Nord2ZC-hifFo1A9Z95:-NorjyOtE7N7RZbxpeT6:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/5853742a0e9f27d5cad46aaab6f28a32cc65d976/pkg/kv/kvclient/kvcoord/dist_sender_test.go#L6257)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Instead of this, let's either start the loop above from 1 or use `i+1` (instead of `i`) to set IDs.
</blockquote></details>

Done
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_test.go` line 6259 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117996#-NorfzO44kKkWaNLT3AN:-Nork1Uk9ol9mTXYK655:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/5853742a0e9f27d5cad46aaab6f28a32cc65d976/pkg/kv/kvclient/kvcoord/dist_sender_test.go#L6259)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

s/singleton/single/g
</blockquote></details>

Done
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_test.go` line 6312 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117996#-Norg7cU9i9FUQFrCk4T:-Norssz85LM8ISLnu12J:bo5f9p6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5853742a0e9f27d5cad46aaab6f28a32cc65d976/pkg/kv/kvclient/kvcoord/dist_sender_test.go#L6312)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Is there a better way to do this than the magic constants below?
</blockquote></details>

I changed to presort the replicas. This makes it a little easier to follow and doesn't require this constant.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_test.go` line 6347 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117996#-NorezXT621hNF1svDoK:-Nort0hgE0f08_stDx0I:b-djmwpe) ([raw file](https://github.com/cockroachdb/cockroach/blob/5853742a0e9f27d5cad46aaab6f28a32cc65d976/pkg/kv/kvclient/kvcoord/dist_sender_test.go#L6347)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

This should be `b.Fatal`, right?
</blockquote></details>

Yep - fixed.

**Review by arulajmani — APPROVED** [review]
LGTM modulo comments.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117996#-:-NowGWM46gxmMoVpZwZU:b-z6u12h)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender_test.go` line 6267 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117996#-NowEUg_5Aa-c10Xru6-:-NowEUg_5Aa-c10Xru60:by6s445) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b18664eafcb5de4b5fd9f1fe252065ef52e6bbf/pkg/kv/kvclient/kvcoord/dist_sender_test.go#L6267)):*
> ```Go
> 	// We append the unused 0 node so the node offset matches its index.
> 	// We add an additional node for the "client" sending the request.
> 	for i := 0; i <= rf+1; i++ {
> ```

<= rf + 1?
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_test.go` line 6386 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117996#-NowFSDD1tuKB-Dq85Y4:-NowFSDD1tuKB-Dq85Y5:b-6vgh28) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b18664eafcb5de4b5fd9f1fe252065ef52e6bbf/pkg/kv/kvclient/kvcoord/dist_sender_test.go#L6386)):*
> ```Go
> 				// synchronizes across threads.
> 				if _, pErr := kv.SendWrapped(ctx, ds, get); pErr != nil {
> 					ch <- pErr.GoError()
> ```

Did we change to this pattern because we didn't want to call `Fatal` on a different goroutine? If so, a better way would be to keep the wait group around, but use `b.Error` instead -- that is allowed on a goroutine that isn't the main test goroutine.

**Comment by andrewbaptist** [comment]
bors+

**Comment by andrewbaptist** [comment]
bors r+

Appears like an agent died

**Comment by andrewbaptist** [comment]
bors r+

One more try - a timeout this time....

**Pull request merged**
