### PR TITLE
opt: inherit ordering for aggregations

### PR DESCRIPTION
**Pull request by justinj**
Certain aggregates are non-commutative, and thus their inputs can
require particular orderings.

This commit allows inputs which have an explicit ordering to have that
ordering be passed up to the group by.

This removed ColSet from any explicit expr, which means its struct is no
longer generated and there doesn't seem to be an easy way to keep around
its intern and associated tests. I figure we can always grab if out of
version control if we re-introduce it.

Release note: None

### CODE REVIEW

**Comment by justinj** [comment]
I think the conclusion of that discussion was to preserve the current behaviour of Cockroach (and "probably" Postgres) in this situation, since doing the per-agg ordering will require execution support. We can support it mostly today in the cases where the aggregate orderings are all a common prefix of some ordering, but that's a larger change that also requires AST and parser changes.

**Comment by knz** [comment]
I think that discussion should be captured in the commit message.

**Comment by knz** [comment]
So based on the discussion in #23620 I wonder if it's possible to restrict the preservation to _explicit_ orderings (the PR description suggests you;'re doing it for any implicit ordering).

**Comment by RaduBerinde** [comment]
It is just for explicit orderings:

> This commit allows inputs which have an explicit ordering to have that ordering be passed up to the group by.

**Comment by RaduBerinde** [comment]
@justinj any update on this? With enabling distsql, I'm finding I have to disable certain execbuilder testcases (like `SELECT CONCAT_AGG(s) FROM (SELECT s FROM kv ORDER BY k)`).

**Comment by justinj** [comment]
I had abandoned this for the time being since there didn't seem to be consensus on the behaviour, that seems to have changed, so I can attempt to revive it.

**Comment by RaduBerinde** [comment]
We have a bunch of logictests that depend on this behavior and we would like them to work with the optimizer too. I think this is a good interim solution until we can support `ORDER BY` in the agg arg (which won't happen in this opt milestone).

**Comment by knz** [comment]
I think the consensus was also that having an ORDER BY clause in the direct operand to FROM propagate as input order to the aggregations was the best (least surprise) UX for users, even though it's not specified by the SQL spec.

**Comment by justinj** [comment]
Ok, I've reworked this - PTAL

---

Review status: 0 of 28 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/memo/private_defs.go, line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/24815#-LD7G9lh5ipHuHf3csdU:-LDC0FZL6vitpF-7o3Hm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/30ddd98455dea28aa3deb14657c922f7dca54d1b/pkg/sql/opt/memo/private_defs.go#L142)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I think make this just `Ordering`, as that's what we call it elsewhere.
</blockquote></details>

Done.

---

*[pkg/sql/opt/memo/private_storage.go, line 175 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/24815#-LAEoAJUDR5sn9qhBGCe:-LDC0GSj2kMJiczyciCg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/30ddd98455dea28aa3deb14657c922f7dca54d1b/pkg/sql/opt/memo/private_storage.go#L175)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

internScanOpDef -> internGroupByDef
</blockquote></details>

Done.

---

*[pkg/sql/opt/memo/private_storage.go, line 181 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/24815#-LD7GZIy8Be7oxownpX1:-LDCJcEV3MDz-JrHyklm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/30ddd98455dea28aa3deb14657c922f7dca54d1b/pkg/sql/opt/memo/private_storage.go#L181)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Add a helper method on `keyBuffer` that serializes an `Ordering`.
</blockquote></details>

Done.

---

*[pkg/sql/opt/memo/private_storage.go, line 185 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/24815#-LD7GgsS7uQqmnhjSrKM:-LD7QTqY7cZJm5CLotYh:b-k05pox) ([raw file](https://github.com/cockroachdb/cockroach/blob/30ddd98455dea28aa3deb14657c922f7dca54d1b/pkg/sql/opt/memo/private_storage.go#L185)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

You need a delimiter between the ordering and grouping cols. Otherwise, you could have a `GroupBy` with 1 ordering col and 1 grouping col compare "equal" to a `GroupBy` with 2 grouping cols. See `internProjectionsOpDef` for an example.
</blockquote></details>

This still works since `InputOrdering` is prefixed with its length, but I'll match what's done elsewhere for consistency.

---

*[pkg/sql/opt/ops/relational.opt, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/24815#-LD7NCLA7jogBaqjGdtc:-LDCCNg9C40RYG6zQ4T_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/30ddd98455dea28aa3deb14657c922f7dca54d1b/pkg/sql/opt/ops/relational.opt#L171)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I think it'd be best to go through the existing rules, and update their matching to use `$def` rather than `$groupingCols`, to make it more clear that it's more than grouping cols now.
</blockquote></details>

Done.

---

*[pkg/sql/opt/optbuilder/distinct.go, line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/24815#-LAEpwej8Kpwb664tzOP:-LDCGoKLEmxfvEPziXht:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/30ddd98455dea28aa3deb14657c922f7dca54d1b/pkg/sql/opt/optbuilder/distinct.go#L62)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I don't think we need to include the ordering here since we know that there are no aggregates that take an ordering. The ordering is already copied to the output scope above, anyway.
</blockquote></details>

Done.

---

*[pkg/sql/opt/optbuilder/groupby.go, line 246 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/24815#-LAErJ3M7Zftewf9soj8:-LDrHQl8-9nM8k9nQ8Wf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/30ddd98455dea28aa3deb14657c922f7dca54d1b/pkg/sql/opt/optbuilder/groupby.go#L246)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Maybe don't bother with the ordering if `len(aggList) == 0` (similar to the DISTINCT case)
</blockquote></details>

Done.

---

*[pkg/sql/opt/optbuilder/testdata/distinct, line 140 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/24815#-LAEtqqIDq7nRDfboHdY:-LDCQx_eAPdKvj0ehkLy:b-a7jlwx) ([raw file](https://github.com/cockroachdb/cockroach/blob/30ddd98455dea28aa3deb14657c922f7dca54d1b/pkg/sql/opt/optbuilder/testdata/distinct#L140)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

The columns wouldn't have the ordering at this point since the sort doesn't happen until later. It seems like the ordering somehow isn't being forced below the group by.
</blockquote></details>

Seems to not be a problem now.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24815#-:-LDrHU-m8KQaXtsatGAQ:b-t6uem3)*

**Comment by andy-kimball** [comment]
:lgtm:
Just one small suggestion, looks very nice.

---

Review status: 0 of 28 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/norm/testdata/rules/decorrelate, line 619 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/24815#-LDrn_TeBOADZLhmqQ1j:-LDrn_TfDjmLQ31lKhs5:b-utauzs) ([raw file](https://github.com/cockroachdb/cockroach/blob/85999e7678ad96b3514ea31cd94f139fc319d52d/pkg/sql/opt/norm/testdata/rules/decorrelate#L619)):*
> ```
>       └── true [type=bool]
> 
> # Don't decorrelate when the group by input is ordered.
> ```

You should shift this test case slightly to use an `ARRAY_AGG`. Otherwise, it will cease to test what you want it to once we add a rule that discards the `ORDER BY` when it's not needed (like in this case).

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24815#-:-LDroLqN9K96CcjHieWB:boxby49)*

**Comment by justinj** [comment]
Review status: 0 of 28 files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/norm/testdata/rules/decorrelate, line 619 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/24815#-LDrn_TeBOADZLhmqQ1j:-LDs-iXPBjfkmk65Qwxe:b-f2vhmj) ([raw file](https://github.com/cockroachdb/cockroach/blob/85999e7678ad96b3514ea31cd94f139fc319d52d/pkg/sql/opt/norm/testdata/rules/decorrelate#L619)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

You should shift this test case slightly to use an `ARRAY_AGG`. Otherwise, it will cease to test what you want it to once we add a rule that discards the `ORDER BY` when it's not needed (like in this case).
</blockquote></details>

Unfortunately since `ARRAY_AGG` can't ignore nulls, it wouldn't get decorrelated here anyway. This is true of both `ARRAY_AGG`, `CONCAT_AGG` and `JSON_AGG`, which also happen to be the aggregates which care about ordering. I'm not sure if there's a way to actually correctly expose this extra condition, though I think it would be sketchy to not explicitly include it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24815)*

**Comment by rytaft** [comment]
*[pkg/sql/opt/norm/testdata/rules/decorrelate, line 619 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/24815#-LDrn_TeBOADZLhmqQ1j:-LDs7-0-6Xd5rQQID0nc:b-ecqo2d) ([raw file](https://github.com/cockroachdb/cockroach/blob/85999e7678ad96b3514ea31cd94f139fc319d52d/pkg/sql/opt/norm/testdata/rules/decorrelate#L619)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Unfortunately since `ARRAY_AGG` can't ignore nulls, it wouldn't get decorrelated here anyway. This is true of both `ARRAY_AGG`, `CONCAT_AGG` and `JSON_AGG`, which also happen to be the aggregates which care about ordering. I'm not sure if there's a way to actually correctly expose this extra condition, though I think it would be sketchy to not explicitly include it.
</blockquote></details>

What if you make all of the input columns non-null?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24815)*

**Comment by justinj** [comment]
Review status: 0 of 28 files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/norm/testdata/rules/decorrelate, line 619 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/24815#-LDrn_TeBOADZLhmqQ1j:-LDs8WL28wm_ZizAHuKf:b-t1fud1) ([raw file](https://github.com/cockroachdb/cockroach/blob/85999e7678ad96b3514ea31cd94f139fc319d52d/pkg/sql/opt/norm/testdata/rules/decorrelate#L619)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

What if you make all of the input columns non-null?
</blockquote></details>

I might misunderstand what you mean, but the problem is [this line](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/opt/norm/rules/decorrelate.opt#L192) which checks if all of the aggregations are allowed to ignore nulls, I think (but not sure, maybe Andy can clarify how this works) that this is important even if none of the initial inputs are null, because this gets decorrelated into a left outer join, which could introduce nulls where there weren't any before?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24815)*

**Comment by rytaft** [comment]
:lgtm_strong: 

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/norm/testdata/rules/decorrelate, line 619 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/24815#-LDrn_TeBOADZLhmqQ1j:-LDsCUJ154ABEz7EsrBj:bt2hk4r) ([raw file](https://github.com/cockroachdb/cockroach/blob/85999e7678ad96b3514ea31cd94f139fc319d52d/pkg/sql/opt/norm/testdata/rules/decorrelate#L619)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

I might misunderstand what you mean, but the problem is [this line](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/opt/norm/rules/decorrelate.opt#L192) which checks if all of the aggregations are allowed to ignore nulls, I think (but not sure, maybe Andy can clarify how this works) that this is important even if none of the initial inputs are null, because this gets decorrelated into a left outer join, which could introduce nulls where there weren't any before?
</blockquote></details>

Ah ok makes sense.

---

*[pkg/sql/opt/optbuilder/groupby.go, line 117 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/24815#-LDsAidGCjCt5M1CxfUp:-LDsAidGCjCt5M1CxfUq:bnv2hse) ([raw file](https://github.com/cockroachdb/cockroach/blob/85999e7678ad96b3514ea31cd94f139fc319d52d/pkg/sql/opt/optbuilder/groupby.go#L117)):*
> ```Go
> 
> func (b *Builder) constructGroupBy(
> 	input memo.GroupID, groupingColSet opt.ColSet, cols []scopeColumn, fromScope *scope,
> ```

I'd change `fromScope` to `inScope` to be consistent with convention

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24815#-:-LDsCa46DxSoaw23sbJ7:b-uwkowd)*

**Comment by andy-kimball** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/norm/testdata/rules/decorrelate, line 619 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/24815#-LDrn_TeBOADZLhmqQ1j:-LDsCa7I3BsubC7o0sBm:ba97uia) ([raw file](https://github.com/cockroachdb/cockroach/blob/85999e7678ad96b3514ea31cd94f139fc319d52d/pkg/sql/opt/norm/testdata/rules/decorrelate#L619)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Ah ok makes sense.
</blockquote></details>

You're correct, Justin. Even if the columns are non-null, the operators themselves still won't ignore nulls. We'd have to create variants of those operators that did ignore nulls for that to work (an interesting idea...).

I see what you're saying re: this test case. We'll just have to deal with this later if/when we add optimizations that discard ORDER BY.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24815)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/optbuilder/groupby.go, line 140 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/24815#-LDvEnQqAhRHSSim3bBE:-LDvEnQqAhRHSSim3bBF:bhi7uo7) ([raw file](https://github.com/cockroachdb/cockroach/blob/85999e7678ad96b3514ea31cd94f139fc319d52d/pkg/sql/opt/optbuilder/groupby.go#L140)):*
> ```Go
> 	var ordering props.Ordering
> 	if len(cols) > 0 {
> 		ordering = fromScope.physicalProps.Ordering
> ```

We cold do this only if we have aggregations that care about order.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24815#-:-LDvF28c3yPChjasS9Fs:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Can you also add the `distsql-opt` config to `logic_test/aggregate` as part of this change? (it should work now)

**Comment by andy-kimball** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24815#-:-LEA19EG-2QHesjSFS5O:bnfp4nl)*

**Comment by justinj** [comment]
I added a TODO for what you mentioned @RaduBerinde, and enabled that other test, TFTR!

bors r+

**Pull request merged**
