### PR TITLE
exec: change experimental_vectorize setting to an enum

### PR DESCRIPTION
**Pull request by asubiotto**
It was previously just a boolean. This enables the use of the `always`
mode, in which queries will fail with an error if they cannot use the
columnar execution engine. This is useful for testing.

Release note: None

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33384)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/plan_node_to_row_source.go, line 235 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33384#-LUq1y_z8iEJxNgGiy62:-LUq1ya02aAUMWa8za_c:bt80dt3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4833273a2093c7c604971d5118313f4746841dcd/pkg/sql/plan_node_to_row_source.go#L235)):*
> ```Go
> }
> 
> func (p *planNodeToRowSource) IsException() bool {
> ```

Add a comment explaining that it implements the interface
___
*[pkg/sql/distsqlrun/processors.go, line 1209 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33384#-LUq1bRbAt2D9Snnz19C:-LUq1bRc6vJcnMtvrsrp:b-u60utr) ([raw file](https://github.com/cockroachdb/cockroach/blob/4833273a2093c7c604971d5118313f4746841dcd/pkg/sql/distsqlrun/processors.go#L1209)):*
> ```Go
> // variable without getting an error.
> type VectorizeAlwaysException interface {
> 	// IsException returns whether this object should be an exception to the rule
> ```

Does this interface need to be exported?

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33384)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/plan_node_to_row_source.go, line 235 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33384#-LUq1y_z8iEJxNgGiy62:-LVD_FgSCKuymVYxdFqk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4833273a2093c7c604971d5118313f4746841dcd/pkg/sql/plan_node_to_row_source.go#L235)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Add a comment explaining that it implements the interface
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/processors.go, line 1209 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33384#-LUq1bRbAt2D9Snnz19C:-LVD_I0B68Nr9vjqxHGQ:by8ifwg) ([raw file](https://github.com/cockroachdb/cockroach/blob/4833273a2093c7c604971d5118313f4746841dcd/pkg/sql/distsqlrun/processors.go#L1209)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Does this interface need to be exported?
</blockquote></details>

Done. What do you think of the approach?

**Review by jordanlewis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33384)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/processors.go, line 1209 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33384#-LUq1bRbAt2D9Snnz19C:-LVElD_25CYAjj7S_w09:b-s0h93p) ([raw file](https://github.com/cockroachdb/cockroach/blob/4833273a2093c7c604971d5118313f4746841dcd/pkg/sql/distsqlrun/processors.go#L1209)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Done. What do you think of the approach?
</blockquote></details>

It seems fine. I do wonder whether you should just check for a `setVarNode` directly instead of introducing the interface but perhaps it's annoying because of the `planNodeToRowSource` wrapper.

**Comment by asubiotto** [comment]
The `planNodeToRowSource` lives in another package so I couldn't access the `node` member variable without making something public, and this made most sense.

bors r+

**Pull request merged**
