### PR TITLE
build: add script to generate go diff patch

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change adds a script that generates the `diff.patch` that is
applied to Go. It generates the patch using the
`github.com/cockroachdb/go` repository; specifically the diff between
the `go1.22.8` tag and the `cockroach-go1.22.8` branch. This branch
has been set up to contain the existing changes (see
https://github.com/cockroachdb/go/compare/go1.22.8...cockroachdb:go:cockroach-go1.22.8).

The procedure for making new changes is to first open a PR against
that branch, then the script can be used after the PR is merged.

Epic: none
Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
What is the procedure to experiment with changes to this patch (without affecting anyone else)?

**Comment by RaduBerinde** [comment]
> What is the procedure to experiment with changes to this patch (without affecting anyone else)?

I think I would need to kick off some builds (which ones? and would I even have permission to run them?) and then update the `go_download_sdk` section in `WORKSPACE`.

**Comment by rickystewart** [comment]
This does not make sense to me. Why would we not simply use `git` to checkout the fork?

**Comment by RaduBerinde** [comment]
> This does not make sense to me. Why would we not simply use git to checkout the fork?

In the builds themselves (e.g. `impl.sh`)? That makes sense - I would need some help - what are the builds exactly? Do I need special permissions to run them?

I wasn't sure if the `.tar.gz` archive is exactly the same with the repository, but I can check that.

**Comment by rickystewart** [comment]
> That makes sense - I would need some help - what are the builds exactly? Do I need special permissions to run them?

Hmm, for prototyping and testing I recommend running it locally. Is there a reason you cannot?

**Comment by rickystewart** [comment]
> I wasn't sure if the .tar.gz archive is exactly the same with the repository, but I can check that.

What `.tar.gz` are you talking about?

**Comment by RaduBerinde** [comment]
> Hmm, for prototyping and testing I recommend running it locally. Is there a reason you cannot?

I didn't try it but it looks like it assumes linux. Do you recommend trying it on a gceworker?

**Comment by RaduBerinde** [comment]
> What `.tar.gz` are you talking about?

https://go.dev/dl/go1.22.8.src.tar.gz which `impl.sh` downloads and patches.

**Comment by rickystewart** [comment]
> Do you recommend trying it on a gceworker?

You can, but really you should be using Docker either way. [The script](https://github.com/cockroachdb/cockroach/blob/master/build/teamcity/internal/release/build-and-publish-patched-go.sh) demonstrates how to do it.

> [go.dev/dl/go1.22.8.src.tar.gz](https://go.dev/dl/go1.22.8.src.tar.gz) which impl.sh downloads and patches.

Maybe I haven't made myself clear enough. 

Currently, we download the `.tar.gz` and apply the patch, as that is the only way we have to construct the version of the code we intend to build.

However, with the existence of the fork, there is no reason to go through this whole rigamarole. It's a waste of time. Instead you can simply use `git checkout` to checkout the code from our fork directly (or, equivalently, download a tarball from `github.com/cockroachdb/go/tarball/$COMMIT_ID`)

**Comment by rickystewart** [comment]
One additional note, the commit ID should be hard-coded instead of simply using `master` or a branch name so that the build works the same way regardless of how the branch on the fork is updated. It does mean that to roll out a change, you'll first have to merge it to github.com/cockroachlabs/go, then do a corresponding PR here.

**Comment by RaduBerinde** [comment]
Yes, understood, will do that. I wasn't sure whether https://go.dev/dl/go1.22.8.src.tar.gz is identical with what you would get with (e.g.) `github.com/cockroachdb/go/tarball/go1.22.8` but it must be.

**Comment by rickystewart** [comment]
You should be able to verify it pretty quickly. I believe those `src` archives from the Go project simply use `git archive`. I wouldn't worry about it, I see no reason they would differ.

**Comment by RaduBerinde** [comment]
Yeah, I verified it. There are some inconsequential things that are not in the official archive (.gitattributes, .github, .gitignore).

**Comment by RaduBerinde** [comment]
> One additional note, the commit ID should be hard-coded

Agreed.

**Comment by RaduBerinde** [comment]
How would you handle the FIPS build? I don't think we want to fork that and maintain a separate set of commits. We could check out the regular go build, generate a patch from that, then apply it, but that's not that much different than what we're doing here (and any bugs in that script would be much harder to debug).

This PR as-is is still a significant step forward in that we now have the Go patch nicely broken up into commits and any future changes are reviewable. IMO we should take this first step and backlog minor improvements to the process.

**Comment by rickystewart** [comment]
No, I think this is unnecessarily complicated. Feel free to close this and dev-inf will pick it up when we get a chance.

**Pull request closed without merging**
