### PR TITLE
Add lightweight telemetry reporting to roachprod

### PR DESCRIPTION
**Pull request by bobvawter**
Open questions for reviewers:
  * Should the protobuf live in the same `telemetry` package or is there a better spot for it?
  * Are there additional events we want to grab from `roachprod`?

The `telemetry-staging` service is live and end-to-end testing of this code works.  I'll send out a separate PR for that service once I get the updated vendor deps compiling.

Sample telemetry for a `roachprod destroy`:

```
bob@MSO-CLUSTER:26257/telemetry_staging> select * from telemetry_features;
   product  |             installation             |            timestamp             |                          feature                           |   uptime    | uses | version  
+-----------+--------------------------------------+----------------------------------+------------------------------------------------------------+-------------+------+---------+
  roachprod | 52fdfc07-2182-454f-963f-5f0f9a621d72 | 2019-05-10 17:04:23.915615+00:00 | command.destroy                                            | 97407184000 |    1 | NULL     
  roachprod | 52fdfc07-2182-454f-963f-5f0f9a621d72 | 2019-05-10 17:04:23.915615+00:00 | destroy.ok.bob-telemetry-0001.gce.us-east1-b.n1-standard-4 | 97407184000 |    1 | NULL     
  roachprod | 52fdfc07-2182-454f-963f-5f0f9a621d72 | 2019-05-10 17:04:23.915615+00:00 | destroy.ok.bob-telemetry-0002.gce.us-east1-b.n1-standard-4 | 97407184000 |    1 | NULL     
  roachprod | 52fdfc07-2182-454f-963f-5f0f9a621d72 | 2019-05-10 17:04:23.915615+00:00 | destroy.ok.bob-telemetry-0003.gce.us-east1-b.n1-standard-4 | 97407184000 |    1 | NULL     
  roachprod | 52fdfc07-2182-454f-963f-5f0f9a621d72 | 2019-05-10 17:04:23.915615+00:00 | destroy.ok.bob-telemetry-0004.gce.us-east1-b.n1-standard-4 | 97407184000 |    1 | NULL     
  roachprod | 52fdfc07-2182-454f-963f-5f0f9a621d72 | 2019-05-10 17:04:23.915615+00:00 | destroy.ok.lifetime.bob-telemetry-0001.612                 | 97407184000 |    1 | NULL     
  roachprod | 52fdfc07-2182-454f-963f-5f0f9a621d72 | 2019-05-10 17:04:23.915615+00:00 | destroy.ok.lifetime.bob-telemetry-0002.612                 | 97407184000 |    1 | NULL     
  roachprod | 52fdfc07-2182-454f-963f-5f0f9a621d72 | 2019-05-10 17:04:23.915615+00:00 | destroy.ok.lifetime.bob-telemetry-0003.611                 | 97407184000 |    1 | NULL     
  roachprod | 52fdfc07-2182-454f-963f-5f0f9a621d72 | 2019-05-10 17:04:23.915615+00:00 | destroy.ok.lifetime.bob-telemetry-0004.611                 | 97407184000 |    1 | NULL     
```

### CODE REVIEW

**Comment by dt** [comment]
I think I'd rather keep the devtool telemetry separate from the pkg/server/telemetry code that is in the shipped binaries in the interest of keeping the shipped binary's telemetry simple and easy for any concerned user to read/audit. For example, there's a cluster setting used to disable/enable that, but the dev-tool telemetry uses a separate env var, and small differences like this seems likely to be at the least confusing if they get mixed together.

**Comment by bobvawter** [comment]
`pkg/util/devtelem` ?  Open to suggestions on a name.

**Comment by dt** [comment]
This is way into bikeshed territory, but:
I wonder if we should make a dev-tools subtree prefix that we could then lint never gets linked in the main binary target. I'm thinking roachprod, including this new package, the pr-strees thing, maybe `backport` and `pr-master`, some of our custom `lint` code, etc is all devtool go code. I'm a  monorepo believer all day, but with the one main binary being the default assumption for where a given piece of code ends up in this repo, I wonder if just throwing things that don't go it it in `util` could get confusing?

That said, I don't feel strongly and don't want to let a bikeshed on some theoretical risks get in the way of actual work. 

`pkg/util/devtelemetry` is fine with me I guess.

**Comment by knz** [comment]
a heads up that @kannanlakshmi was asking about this recently

**Comment by petermattis** [comment]
@bobvawter Any intention to resuscitate this PR? Perhaps convert it to a draft in the meantime.

**Pull request closed without merging**
