### PR TITLE
kvserver: remove replicate queue pre-process check

### PR DESCRIPTION
**Pull request by kvoli**
Following c9cf06893bf827a1752213aa3aebee2aaea35f13, the `preProcessCheck` for the replicate queue is now
redundant. All callers of `processOneChange` will first call
`replicaCanBeProcessed`, which checks for a valid lease and that the
replica is not destroyed.

Epic: none
Release note: None

### CODE REVIEW

**Review by andrewbaptist — APPROVED** [review]
:lgtm:

nit: I was a little surprised that there is still code (adminScatter) that skips the checks. I wonder if we should track down those cases and prevent them. I worry that we will have unexpected behavior if all the checks are not consistently done.

**Comment by kvoli** [comment]
> :lgtm:
> 
> nit: I was a little surprised that there is still code (adminScatter) that skips the checks. I wonder if we should track down those cases and prevent them. I worry that we will have unexpected behavior if all the checks are not consistently done.

Turns out it actually doesn't, it does call `replicaCanBeProcessed(...)` before each process loop. I'll remove this extra check and update the PR.

**Comment by kvoli** [comment]
I've removed all of the `preProcessCheck` logic accordingly. Should be good for another review @andrewbaptist.

**Review by andrewbaptist — APPROVED** [review]
:lgtm:

**Comment by kvoli** [comment]
TYFTR

bors r=andrewbaptist

**Pull request merged**
