### PR TITLE
kv, sql: replace TestTraceFromErrorReplica

### PR DESCRIPTION
**Pull request by andreimatei**
That test was teminally confused and confusing. It was written to
prevent a regression from a time where the DistSender used to have a bug
causing it to not ingest snowball trace info for errors for which it
performed retries (e.g. NotLeaseHolderError). That bug was repaired by
pushing the ingesting logic from the DistSender down to the gRPC
transport. The test I wrote at the time was written at a very high level - using 
the SQL interface. If you look at it with generousity it might
have seemed like a good idea at the time, but particuarly with the
advent of DistSQL, the test became way confused.
It worked by using ManualReplication (which meant that, consciensiously
or not, the test was getting a single range). It then created a table
and controlled its leaseholder, and then traced a select from a node
that was not aware of this leaseholder, and asserted it was seeing a
NLHE in the trace.
The intent was from the error to come from a Scan. However, at least
since DistSQL happened, the error was coming from the planning process
(creating the physical plan), from a range resolving operation (because
the node doing the select became unaware of the leases for the meta
ranges too incidentally), not from a TableReader. Although arguably the
test was still proving what it wanted to prove, it was confusing af.

Also, the test is starting to hopelessly break with a different thing I
have in the works where clusters get more than one system range even
when used with ManualReplication.

The patch replaces the test with a unit test for the gRPC transport.

Release note: None

### CODE REVIEW

**Comment by andreimatei** [comment]
cc @nvanbenschoten

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32733#-:-LSXJNMd7E2SLoN4RnEz:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/kv/transport_test.go, line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32733#-LSXISnD7o-KezkAvR5w:-LSXISnD7o-KezkAvR5x:bra1lwj) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e0c3cbaa60af3f5559dac47d09c34f849310a22/pkg/kv/transport_test.go#L108)):*
> ```Go
> }
> 
> // TestSpanImport tests that the gRPC ingests trace information that came from
> ```

[nit] the gRPC transport?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32733)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/kv/transport_test.go, line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32733#-LSXISnD7o-KezkAvR5w:-LSpEhrn7_S-koVURDet:b-pb9bue) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e0c3cbaa60af3f5559dac47d09c34f849310a22/pkg/kv/transport_test.go#L108)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] the gRPC transport?
</blockquote></details>

indeed

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32733#-:-LSpEkY514MbqkGjcyA_:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
