### PR TITLE
sql: fix the collection of logical plan samples

### PR DESCRIPTION
**Pull request by knz**
As found by @couchand in https://github.com/cockroachdb/cockroach/pull/33020#discussion_r245752090

The logic was in the wrong place and did not properly account for the
optimizer mode and whether an execution error occured. This patch
fixes it.

To achieve this, the patch requires the ability to inspect the
planNode tree after the execution machinery finishes running the
query.

This is a new requirement and had to be careful about resource
deallocation:

1) it becomes important that a planNode does not get closed during
   execution. This was already mostly true, except for
   `unionNode`. This patch modifies `unionNode` to make it compliant
   with the new protocol, and clarifies the constraint in the
   interface documentation for `planNode.Close()`.

2) when a planNode tree is started (`startExec`), it allocates memory
   in memory accounts set up by the exec machinery.  At the end of
   execution, it is thus important to close the planNode tree before
   the exec machinery accounts are closed. In order to achieve this,
   the patch introduces an inversion of control over the deallocation
   of execution resources.

Before (simplified):

```
executor -> execWith() -> planNode.Next()
                       -> planNode.close()
                       -> execMon.close()
```

After (simplified):

```
executor -> cleanup := execWith() -> planNode.Next()
                                  -> return func() { execMon.close() }
         -> log(planNode)
         -> planNode.close()
         -> cleanup()
```

Release note: None

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
Seems like something didn't go quite right:

```
panic: name missing for type <nil>

goroutine 76 [running]:
github.com/cockroachdb/cockroach/pkg/sql.nodeName(0x0, 0x0, 0xc4204d2000, 0xbf053756e16d28f3)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:629 +0x2c6
```

@celiala can you take a look as well? Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33561#-:-LVjBwcH2IcEoq_oPOcX:b-w1p9jc)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by knz** [comment]
I think I found the problem, this looks like the logical plan was Close()d already at that point. Will look further.

**Comment by knz** [comment]
@vilterp @celiala @jordanlewis there's another issue I discovered while investigating. The code currently as-is will sample a query plan for every first instance of a given statement key. I think that's unreasonable -- this means incurring the overhead in the common case.

May I suggest to change this to the second instance? Or perhaps the 10th?

**Comment by jordanlewis** [comment]
I had a similar thought about the 1st instance before, but I ended up removing it because I don't think there is anything special about the 1st instance really. I don't think this will appreciably slow down interactive exploration of the database for example, so it's unlikely that users will notice.

I wouldn't object to moving it to a different number but I'm not sure it matters all that much in the end.

**Comment by knz** [comment]
Ok I did not change anything about the frequency of the collection. However I reworked the resource release code, to ensure that the distsqlrunner Run() method is not taking ownership of planNode.Close() any more. RFAL.

**Review by celiala — COMMENTED** [review]
Thanks for taking this on, Raphael!

In terms of the sampling frequency -- I can take on investigating this question further and adjust if needed (in future PR) .

I'll let others review the reworking of the resource release code; in terms of the sampling logic, this looks good to me.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33561#-:-LVs_xERDZs2kvmnoxGD:b-4kckly)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/conn_executor_exec.go, line 1072 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33561#-LVsRx-X7ReREMg4EKdi:-LVsRx-X7ReREMg4EKdj:bsui53n) ([raw file](https://github.com/cockroachdb/cockroach/blob/b22633a7d9251495570220ea34533378ee42bade/pkg/sql/conn_executor_exec.go#L1072)):*
> ```Go
> 	cleanupRunner := ex.server.cfg.DistSQLPlanner.PlanAndRun(
> 		ctx, evalCtx, planCtx, planner.txn, planner.curPlan.plan, recv)
> 	cleanupExec := func() {
> ```

The `func()...` param here is causing my local copy not to build?

**Review by celiala — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33561)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/testutils.go, line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33561#-LVsfUPrELaKOtVMmdt7:-LVsfUPs-7eIolH6c3Wy:b-vtg2if) ([raw file](https://github.com/cockroachdb/cockroach/blob/b22633a7d9251495570220ea34533378ee42bade/pkg/sql/testutils.go#L132)):*
> ```Go
> 	planCtx.stmtType = recv.stmtType
> 
> 	cleanup := dsp.PlanAndRun(ctx, evalCtx, planCtx, p.txn, p.curPlan.plan, recv, func() {})
> ```

The func()... param here is causing my local copy not to build?

**Comment by andreimatei** [comment]
Tackling the lifetimes of things is God's work. But this is the kind of patch where I'm bothered and I feel like something better should be possible but I don't know what exactly. The thing that bothers me is the cleanup function with an unclear contract that the patch is introducing from `DistSQLPlanner.Run()`. It'd be much nicer if all the resources used while that method is running were scoped to that method. I get that `flow.Cleanup() calls f.EvalCtx.ActiveMemAcc.Close(ctx)` and that there currently must be some unfortunate way in which that mem account is also used by planNodes and so that account can't be closed before the `plan.Close()`. But I think there's got to be a better way. Perhaps we can completely separate the accounts used by processors from the accounts used by planNodes, and have two completely separate words with different cleanup.

Relatedly, I think it was not bad that the plan was `.Close()d` when it's execution was done. It seems to me that there shouldn't be much resources that need to be kept alive after a plan is no longer executing. I understand that something about this plan needs to be sampled later; I'm not sure what the `log(plan)` from your diagram is so I can't verify what it needs exactly. But I think that maybe we can separate runtime resources from whatever that sampling needs, and scope things appropriately.
This is not to say that things are currently great: the stanza that this patch deletes that says "We need to close the planNode tree we translated into a DistSQL plan before flow.Cleanup, which closes memory accounts that expect to be emptied." already smelled very bad.

So... I dunno what to say. I'd be interested in discussing this to understand the issues better and have a more informed opinion.
But also I haven't been in this code for a while and so I don't need to have an opinion necessarily. If you've thought about things and are confident in what you're doing and want to get a review from someone else, I won't be offended.

**Comment by knz** [comment]
Thank you Andrei your comment was super helpful.
I agree that there are misdesigns and this needs to be addressed. Thankfully, we have a plan already!

I'd like to add a little context:

1. sampling the plan after a `planNode.Close()` is really a non-starter. Several of the planNodes these days (eg scanNode) are placed back in a `sync.Pool` during `Close()` and are erased in the process. So they truly are not reusable.
2. to do the "right" thing assuming we keep the planNode execution logic, would require moving the memory accounts away from the planNodes into the planner struct. **This would be a good change** and I could even volunteer to look at it. However...
3. the planNode execution logic (including memory monitoring etc) is going away bit by bit because of the migration to distsql. Half of it is already "gone" (dead code) unless `set distsql=2.0-off` is used, which will not be a thing any more in 2.2. Really the problems only show up in tests.

So really the bottom line is I don't want us (collectively) to spend time improving the planNode memory tracking to make things work in a way that's elegant, because we're going to kill it entirely.

So here is what I am going to do, probably Monday while y'all are on holiday:

A. I am going to attempt to split the sampling of the planNode tree into JSON (which can theoretically be done prior to execution), from the storing of that JSON (which must be done after execution, because it needs to know whether distsql was used and whether there was an error). This way I do not need to touch the plan deallocation logic and this discussion is moot.

B. If attempt A fails, I will actually go on and iterate to merge this PR as-is, with additional comments on the cleanup/close protocol to explain this is a temporary thing that should be removed / cleaned up when the planNode execution logic is removed.

Does this sound OK?

**Comment by knz** [comment]
RFAL:

Unfortunately path A above didn't work - *whether* the sampling should be performed can only be decided at the end of execution.

However I found an alternative plan C, where the `planTop.close()` method (called both by executor and distsql) becomes responsible to do this.

It's a kludge but much smaller in impact than my previous approach. Please re-read the commit message (2nd commit) to get the new explanation.

**Review by celiala — APPROVED** [review]
Thanks for taking this on, Raphael!

Some nits inline but otherwise LGTM and seems that all concerns have been addressed.

:lgtm:

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33561)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @celiala and @couchand)

___
*[pkg/sql/conn_executor_exec.go, line 831 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/33561#-LVgajpMKX9jJiNYby4H-r4-831:-LXJYv6I2339fESHUXs5:b5ajxg3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3d9f864575050be73615bad4bde8c91afa5ae32/pkg/sql/conn_executor_exec.go#L831)):*
<details><summary><i>Previously, celiala wrote…</i></summary><blockquote>

Reading the code, I _think_ this is the case, but can you confirm that we don't need to explicitly set `.maybeSavePlan` to nil if `sampleLogicalPlans` is false because curPlan gets reset/cleared?
</blockquote></details>

Yes; clarified with comment.
___
*[pkg/sql/conn_executor_prepare.go, line 245 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/33561#-LWv4vU6p8OhYq5BXL_K-r4-245:-LXJZQ3L9hGJ64YMGWiM:b-f8sf1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3d9f864575050be73615bad4bde8c91afa5ae32/pkg/sql/conn_executor_prepare.go#L245)):*
<details><summary><i>Previously, celiala wrote…</i></summary><blockquote>

nit: for the last paragraph in the commit message [about plumbing], can you also include this as a specific example? It took me a little bit to figure out that this was plumbing to correctly update optimizer counters.
</blockquote></details>

Added a comment.
___
*[pkg/sql/distsql_running.go, line 37 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/33561#-LVnMVcdDFy2ExnLIwHm-r4-37:-LXJZRYl8WUhYYo6l9cn:b-k7xnsw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3d9f864575050be73615bad4bde8c91afa5ae32/pkg/sql/distsql_running.go#L37)):*
<details><summary><i>Previously, celiala wrote…</i></summary><blockquote>

nit: `opentracing` doesn't seem to be related to below change? (maybe don't need this?)
</blockquote></details>

It's what radu explained.
___
*[pkg/sql/testutils.go, line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33561#-LVsfUPrELaKOtVMmdt7:-LXJZUpf-pJrMoaTWfdA:b-qssebl) ([raw file](https://github.com/cockroachdb/cockroach/blob/b22633a7d9251495570220ea34533378ee42bade/pkg/sql/testutils.go#L132)):*
<details><summary><i>Previously, celiala wrote…</i></summary><blockquote>

The func()... param here is causing my local copy not to build?
</blockquote></details>

fixed.

**Pull request merged**
