### PR TITLE
sqlccl: imporove incremental backup start/end timestamp matching

### PR DESCRIPTION
**Pull request by danhhz**
The previous ValidatePreviousBackups checks were a subset of what
makeImportRequests verifies, but we want to verify all the same things,
so reuse makeImportRequests.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13848)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/ccl/sqlccl/backup.go, line 73 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13848#-Ke5Ckb3r-0aKZtHJkJr:-Ke5Ckb3r-0aKZtHJkJs:b4txjvi) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f4a0dd7d980437edd87c18cda11d4093520f75e/pkg/ccl/sqlccl/backup.go#L73)):*
> ```Go
> 		return hlc.Timestamp{}, nil
> 	}
> 	var backups []BackupDescriptor
> ```

would this benefit from being pre-allocated?

---

*[pkg/ccl/sqlccl/backup.go, line 604 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13848#-Ke5DBwBgXcf7kIHMqKY:-Ke5DBwBgXcf7kIHMqKZ:b-opv42j) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f4a0dd7d980437edd87c18cda11d4093520f75e/pkg/ccl/sqlccl/backup.go#L604)):*
> ```Go
> 				if ts != ie.backup.StartTime {
> 					return nil, hlc.Timestamp{}, errors.Errorf(
> 						"no backup covers time %s to %s for range %s to %s",
> ```

`[%, %s)` notation for both time and span?

---

*[pkg/ccl/sqlccl/backup.go, line 621 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13848#-Ke5Dq3J8DCnF7d3IPkd:-Ke5Dq3J8DCnF7d3IPke:b-4n403s) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f4a0dd7d980437edd87c18cda11d4093520f75e/pkg/ccl/sqlccl/backup.go#L621)):*
> ```Go
> 		if ts != maxEndTime {
> 			return nil, hlc.Timestamp{}, errors.Errorf(
> 				"not all ranges have maximum end time %s", maxEndTime)
> ```

should this specifically call out the offending range and its end time?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13848)*

**Comment by danhhz** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/ccl/sqlccl/backup.go, line 73 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13848#-Ke5Ckb3r-0aKZtHJkJr:-Ke5Jpi8Kfj6ACGn-a15:bibcmk7) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f4a0dd7d980437edd87c18cda11d4093520f75e/pkg/ccl/sqlccl/backup.go#L73)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

would this benefit from being pre-allocated?
</blockquote></details>

Can't hurt

---

*[pkg/ccl/sqlccl/backup.go, line 604 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13848#-Ke5DBwBgXcf7kIHMqKY:-Ke5KO1DRkgbfSUNwbdB:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f4a0dd7d980437edd87c18cda11d4093520f75e/pkg/ccl/sqlccl/backup.go#L604)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

`[%, %s)` notation for both time and span?
</blockquote></details>

Done

---

*[pkg/ccl/sqlccl/backup.go, line 621 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13848#-Ke5Dq3J8DCnF7d3IPkd:-Ke5KhfBAc25iyWh-Xb7:bumy88j) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f4a0dd7d980437edd87c18cda11d4093520f75e/pkg/ccl/sqlccl/backup.go#L621)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

should this specifically call out the offending range and its end time?
</blockquote></details>

Good point. Made this match the other error

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13848)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13848)*

**Comment by benesch** [comment]
I'll give this a more thorough look tomorrow, but for now: commit message spells improve wrong.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13848#-:-Ke6tAnFv11eeN7IVumA:b-muf4ro)*

**Comment by benesch** [comment]
Is it required that intervals be listed in the correct order? 

```
root@:26257/> BACKUP DATABASE bench TO 'foo1';
+------+---------------+------------------------+----------+
|  to  |    startTs    |         endTs          | dataSize |
+------+---------------+------------------------+----------+
| foo1 | 0.000000000,0 | 1488692626.563997707,0 |     2831 |
+------+---------------+------------------------+----------+
(1 row)
root@:26257/> BACKUP DATABASE bench TO 'foo2' INCREMENTAL FROM foo1;
+------+------------------------+------------------------+----------+
|  to  |        startTs         |         endTs          | dataSize |
+------+------------------------+------------------------+----------+
| foo2 | 1488692626.563997707,0 | 1488692635.659729007,0 |        0 |
+------+------------------------+------------------------+----------+
(1 row)
root@:26257/> BACKUP DATABASE bench TO 'foo3' INCREMENTAL FROM foo2, foo1;
pq: no backup covers time [0.000000000,0,1488692626.563997707,0) for range [/Table/3/1,/Table/3/2)
root@:26257/> BACKUP DATABASE bench TO 'foo3' INCREMENTAL FROM foo1, foo2;
+------+------------------------+------------------------+----------+
|  to  |        startTs         |         endTs          | dataSize |
+------+------------------------+------------------------+----------+
| foo3 | 1488692635.659729007,0 | 1488692649.787192118,0 |        0 |
+------+------------------------+------------------------+----------+
(1 row)
root@:26257/>  
```

I would expect `BACKUP DATABASE bench TO 'foo3' INCREMENTAL FROM foo2, foo1;` to succeed because the error message claims "*no* backup covers time" and not "backups out of order." Plus my code reading suggests that the sort in `OverlapCoveringMerge` should make order irrelevant. But if I'm just mistaken and we intentionally don't support out-of-order incremental backups, then I'd advocate for an error message with a hint to check the order.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/sqlccl/backup_test.go, line 528 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13848#-KeRqU1nwt4lMqwvpcsq:-KeRqU1nwt4lMqwvpcsr:bmnw30k) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e950931e23dad3cc2262e8d962a09aef17b4fbc/pkg/ccl/sqlccl/backup_test.go#L528)):*
> ```Go
> 		filepath.Join(dir, "2"), // Incremental from 1.
> 		filepath.Join(dir, "3"), // Incremental from 0, but only one table.
> 	}
> ```

Are you opposed to giving each directory its own descriptively-named variable? It's hard for my little ape brain to follow the tests without constantly referring to this declaration.

---

*[pkg/ccl/sqlccl/backup_test.go, line 558 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13848#-KeRrsyh3CvSxu5fHGQx:-KeRrsyh3CvSxu5fHGQy:b-xipjg2) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e950931e23dad3cc2262e8d962a09aef17b4fbc/pkg/ccl/sqlccl/backup_test.go#L558)):*
> ```Go
> 		if !testutils.IsError(err, "no backup covers time") {
> 			t.Errorf("expected 'no backup covers time' error got: %+v", err)
> 		}
> ```

It'd be nice to have positive tests here (i.e., asserting that restoring incremental from `backupDirs[0]` and `backupDirs[1]` is not an error), but in the interest of code velocity perhaps that's better served by an higher-level test for incremental backups. (I couldn't find any code that tests a restore from an incremental backup. Is that planned as part of the nightly cluster backup-restore project?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13848#-:-KeRy89YkiwcBDZG8HAj:bo7ne5x)*

**Comment by danhhz** [comment]
Good call. I'm a little uncomfortable here with guessing what the user meant, so kept the stricter implementation but added to the error message. (OverlapCoveringMerge only sorts keyranges, it intentionally doesn't sort timeranges)

---

Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/ccl/sqlccl/backup_test.go, line 528 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13848#-KeRqU1nwt4lMqwvpcsq:-KedSPsL3NG0UnvqxnSu:b-1ctm1u) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e950931e23dad3cc2262e8d962a09aef17b4fbc/pkg/ccl/sqlccl/backup_test.go#L528)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Are you opposed to giving each directory its own descriptively-named variable? It's hard for my little ape brain to follow the tests without constantly referring to this declaration.
</blockquote></details>

Much better

---

*[pkg/ccl/sqlccl/backup_test.go, line 558 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13848#-KeRrsyh3CvSxu5fHGQx:-KedSRO5wSewJVeYhy3l:b7ywgiy) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e950931e23dad3cc2262e8d962a09aef17b4fbc/pkg/ccl/sqlccl/backup_test.go#L558)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

It'd be nice to have positive tests here (i.e., asserting that restoring incremental from `backupDirs[0]` and `backupDirs[1]` is not an error), but in the interest of code velocity perhaps that's better served by an higher-level test for incremental backups. (I couldn't find any code that tests a restore from an incremental backup. Is that planned as part of the nightly cluster backup-restore project?)
</blockquote></details>

TestBackupRestoreIncremental does this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13848#-:-KedSTTV8TjeClBgXAFW:ba0xk19)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13848)*

**Comment by benesch** [comment]
Thanks! :lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13848#-:-KedXr1lI_P3ghLdvkvA:b-ftzx47)*

**Comment by danhhz** [comment]
Thanks for the reviews!

**Pull request merged**
