### PR TITLE
rowexec: improve memory accounting in joinReader

### LINKED ISSUE #65904: row: joinreader has insufficient memory accounting
The joinReader, our index and lookup join processor, does not sufficiently account for much of the memory that it allocates and retains. When run in highly concurrent environments with memory pressure, this will cause the server to run out of memory due to the lack of backpressure.

For an easy example that can overwhelm a database in seconds, run TPCH query 4 with concurrency 1024. See #64906 for more background and other examples of this issue, including a sample setup that can reproduce this issue.

Here are some places where we do not account for memory sufficiently in joinReader.

1. All input rows are copied without memory accounting.
https://github.com/cockroachdb/cockroach/blob/ff28a1c72a8f2544e1b00c1cd55567fcd1fc0505/pkg/sql/rowexec/joinreader.go#L578
2. The spans generated by each input batch are not memory accounted. With some strategies like the index join strategy, there can be 10s of thousands of spans present in memory per join since the input batch is sized up to 4 megabytes of input data. And, the spans are sized in proportion to user data (since they are made of user-defined keys).
https://github.com/cockroachdb/cockroach/blob/bc465fb0005446b84624e24a3c2d712a4e613d7d/pkg/sql/rowexec/joinreader_span_generator.go#L123
3. The span generators store maps that are unaccounted for. These need to be memory accounted, as they are sized in proportion to user data.
https://github.com/cockroachdb/cockroach/blob/bc465fb0005446b84624e24a3c2d712a4e613d7d/pkg/sql/rowexec/joinreader_span_generator.go#L427
4. The `joinReaderOrderingStrategy` uses an unaccounted-for multimap. It's just integers, but it grows in proportion to the batch size in rows.
https://github.com/cockroachdb/cockroach/blob/bc465fb0005446b84624e24a3c2d712a4e613d7d/pkg/sql/rowexec/joinreader_strategies.go#L305

I think it's likely that there are more spots that are unaccounted for besides these, as well.

I took a cursory look at accounting for some of these issues. I found that it is difficult to do properly, because memory is not clearly owned by components of the processor. Memory is sometimes allocated by the joinReader itself, sometimes the joinReader's strategies, and sometimes the spanGenerators. The strategies and generators also retain pointers to some of the backing memory for reuse of the containers, but they don't have a clear spot at which they can zero the pointers inside of the containers to avoid retaining objects past their supposed lifetimes.

At a minimum, since the lifetimes are tricky, we need to over-account for all of this memory by ratcheting up a memory account as we see batches coming through and needing all of this scratch space.

Separately, I want to propose that we start rewriting the `joinReader` in the vectorized, starting with the simplest algorithm (index join). Doing this would immediately solve our memory accounting issues. It would also have ancillary benefits and I think would significantly improve performance. I will file a separate issue for that.

Epic: CRDB-8562

### PR DESCRIPTION
**Pull request by rytaft**
This commit improves memory accounting in joinReader by accounting
for the in-memory data structures used throughout execution.

Fixes #65904

Release note: None

### CODE REVIEW

**Comment by rytaft** [comment]
I need to add some tests, but I thought I'd at least put up a PR to see if there is any feedback on the approach.

**Review by jordanlewis — COMMENTED** [review]
Looks good overall! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67447#-:-MeCL4KZ3I3qbV8VY6SL:brszbq2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @rytaft)

___
*[pkg/sql/rowexec/joinreader.go, line 985 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67447#-MeCImH17T5S19N_Bov0:-MeCImH17T5S19N_Bov1:b-9g35rq) ([raw file](https://github.com/cockroachdb/cockroach/blob/1508acb81ee357b8b15507e7cc27fd0d8aa2576d/pkg/sql/rowexec/joinreader.go#L985)):*
> ```Go
> func (jr *joinReader) memUsage() int64 {
> 	// Account for scratchInputRows.
> 	size := int64(cap(jr.scratchInputRows)-len(jr.scratchInputRows)) * int64(unsafe.Sizeof(rowenc.EncDatumRow{}))
> ```

I think the .Size() method of `EncDatumRow` already includes the sizeof(EncDatumRow) overhead.
___
*[pkg/sql/rowexec/joinreader.go, line 987 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67447#-MeCI8fDBqTaVWHc7Srf:-MeCI8fDBqTaVWHc7Srg:b-p3bv47) ([raw file](https://github.com/cockroachdb/cockroach/blob/1508acb81ee357b8b15507e7cc27fd0d8aa2576d/pkg/sql/rowexec/joinreader.go#L987)):*
> ```Go
> 	size := int64(cap(jr.scratchInputRows)-len(jr.scratchInputRows)) * int64(unsafe.Sizeof(rowenc.EncDatumRow{}))
> 	for i := range jr.scratchInputRows {
> 		size += int64(jr.scratchInputRows[i].Size())
> ```

Doesn't this avoid counting up the size of rows that are past the Len() of the scratchInputRows slice?

I feel like maybe we could, at the start of this method, slice the `scratchInputRows` up to its cap and then account for the whole slice with this method.

Then we could restore the len afterwards.
___
*[pkg/sql/rowexec/joinreader_span_generator.go, line 168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67447#-MeCKaxd2fyuzL9Wuy48:-MeCKaxe5KBHPYTuIzON:b-ze51db) ([raw file](https://github.com/cockroachdb/cockroach/blob/1508acb81ee357b8b15507e7cc27fd0d8aa2576d/pkg/sql/rowexec/joinreader_span_generator.go#L168)):*
> ```Go
> 
> 	// Account for scratchSpans.
> 	size += int64(cap(g.scratchSpans)-len(g.scratchSpans)) * int64(unsafe.Sizeof(roachpb.Span{}))
> ```

Similar comment to above: I think we should be counting up the whole slice, including both the parts before and after the length cutoff in the slice.
___
*[pkg/sql/rowexec/joinreader_span_generator.go, line 170 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67447#-MeCKGhuDsrWR8GvrOWM:-MeCKGhuDsrWR8GvrOWN:b-228rov) ([raw file](https://github.com/cockroachdb/cockroach/blob/1508acb81ee357b8b15507e7cc27fd0d8aa2576d/pkg/sql/rowexec/joinreader_span_generator.go#L170)):*
> ```Go
> 	size += int64(cap(g.scratchSpans)-len(g.scratchSpans)) * int64(unsafe.Sizeof(roachpb.Span{}))
> 	for i := range g.scratchSpans {
> 		size += int64(g.scratchSpans[i].Size())
> ```

I think this .Size() method is actually going to report the size of the serialized protobuf, not the size of the in-memory object. It probably would be marginally better to report the size of the two keys, without the extra serialization bits that they add.
___
*[pkg/sql/rowexec/joinreader_span_generator.go, line 504 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67447#-MeCKlQ17taoi-ZxUEih:-MeCKlQ17taoi-ZxUEii:b-bebyud) ([raw file](https://github.com/cockroachdb/cockroach/blob/1508acb81ee357b8b15507e7cc27fd0d8aa2576d/pkg/sql/rowexec/joinreader_span_generator.go#L504)):*
> ```Go
> 
> 	// Account for scratchSpans.
> 	size += int64(cap(g.scratchSpans)-len(g.scratchSpans)) * int64(unsafe.Sizeof(roachpb.Span{}))
> ```

ditto comment above. Should we make a Spans.Size() method? or maybe a Spans.MemUsage() to distinguish from the protobuf-generated .Size method?
___
*[pkg/sql/rowexec/joinreader_strategies.go, line 648 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67447#-MeCL-aH5jWrk_3Dv0Jp:-MeCL-aH5jWrk_3Dv0Jq:b-j5tcbj) ([raw file](https://github.com/cockroachdb/cockroach/blob/1508acb81ee357b8b15507e7cc27fd0d8aa2576d/pkg/sql/rowexec/joinreader_strategies.go#L648)):*
> ```Go
> // mapSize returns the size of inputRowIdxToLookedUpRowIndices in bytes, to
> // be used for memory accounting.
> func (s *joinReaderOrderingStrategy) mapSize() int64 {
> ```

nit: maybe call this method memUsage to parallel the others.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67447)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @rytaft)

___
*[pkg/sql/rowexec/joinreader.go, line 640 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67447#-MeQHy2PAtu6LkEZyjdv:-MeQHy2PAtu6LkEZyjdw:b-8j0lb8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1508acb81ee357b8b15507e7cc27fd0d8aa2576d/pkg/sql/rowexec/joinreader.go#L640)):*
> ```Go
> 				jr.MoveToDraining(err)
> 				return jrStateUnknown, nil, meta
> 			}
> ```

Do we need to set `sizeBefore = sizeAfter` here so we have the correct `sizeBefore` in the `Resize` below?

**Review by rytaft — COMMENTED** [review]
TFTRs! Updated.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67447#-:-MelM3tx7wS095LOxgUP:b-u8hs9c)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @jordanlewis, and @mgartner)

___
*[pkg/sql/rowexec/joinreader.go, line 640 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67447#-MeQHy2PAtu6LkEZyjdv:-Meai81_19iVDWLc7DFX:b-xp0kj0) ([raw file](https://github.com/cockroachdb/cockroach/blob/1508acb81ee357b8b15507e7cc27fd0d8aa2576d/pkg/sql/rowexec/joinreader.go#L640)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Do we need to set `sizeBefore = sizeAfter` here so we have the correct `sizeBefore` in the `Resize` below?
</blockquote></details>

We're returning on the next line, so we won't ever get to that `Resize`. Or am I missing something?
___
*[pkg/sql/rowexec/joinreader.go, line 985 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67447#-MeCImH17T5S19N_Bov0:-MeeRwHsBkzQE86RExr_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1508acb81ee357b8b15507e7cc27fd0d8aa2576d/pkg/sql/rowexec/joinreader.go#L985)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think the .Size() method of `EncDatumRow` already includes the sizeof(EncDatumRow) overhead.
</blockquote></details>

Done.
___
*[pkg/sql/rowexec/joinreader.go, line 987 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67447#-MeCI8fDBqTaVWHc7Srf:-MeeRy9PAlZv6IuybgIZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1508acb81ee357b8b15507e7cc27fd0d8aa2576d/pkg/sql/rowexec/joinreader.go#L987)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Doesn't this avoid counting up the size of rows that are past the Len() of the scratchInputRows slice?

I feel like maybe we could, at the start of this method, slice the `scratchInputRows` up to its cap and then account for the whole slice with this method.

Then we could restore the len afterwards.
</blockquote></details>

Done.
___
*[pkg/sql/rowexec/joinreader_span_generator.go, line 168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67447#-MeCKaxd2fyuzL9Wuy48:-MeeQ6rU3rha2NSZ9VKy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1508acb81ee357b8b15507e7cc27fd0d8aa2576d/pkg/sql/rowexec/joinreader_span_generator.go#L168)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Similar comment to above: I think we should be counting up the whole slice, including both the parts before and after the length cutoff in the slice.
</blockquote></details>

Done.
___
*[pkg/sql/rowexec/joinreader_span_generator.go, line 170 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67447#-MeCKGhuDsrWR8GvrOWM:-MeeQ3Ji76o6rjmEY6NA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1508acb81ee357b8b15507e7cc27fd0d8aa2576d/pkg/sql/rowexec/joinreader_span_generator.go#L170)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think this .Size() method is actually going to report the size of the serialized protobuf, not the size of the in-memory object. It probably would be marginally better to report the size of the two keys, without the extra serialization bits that they add.
</blockquote></details>

Done.
___
*[pkg/sql/rowexec/joinreader_span_generator.go, line 504 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67447#-MeCKlQ17taoi-ZxUEih:-MeeS-o9ClTQZ8whrdhC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1508acb81ee357b8b15507e7cc27fd0d8aa2576d/pkg/sql/rowexec/joinreader_span_generator.go#L504)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

ditto comment above. Should we make a Spans.Size() method? or maybe a Spans.MemUsage() to distinguish from the protobuf-generated .Size method?
</blockquote></details>

Done.
___
*[pkg/sql/rowexec/joinreader_strategies.go, line 648 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67447#-MeCL-aH5jWrk_3Dv0Jp:-MeaimA-7JQjeZ-KGl_K:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1508acb81ee357b8b15507e7cc27fd0d8aa2576d/pkg/sql/rowexec/joinreader_strategies.go#L648)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

nit: maybe call this method memUsage to parallel the others.
</blockquote></details>

Done.

**Pull request closed without merging**
