### PR TITLE
opt: logical props and stats for merge join

### PR DESCRIPTION
**Pull request by RaduBerinde**
Wire up the code for logical props and stats to work with merge joins.
This is useful with exprgen.

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35074#-:-LZA_gsp9Lr4Kd5pxV31:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/opt/memo/logical_props_builder.go, line 1474 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35074#-LZAXvQ64mhpXz3lKuRW:-LZAXvQ64mhpXz3lKuRX:b-6uiwlw) ([raw file](https://github.com/cockroachdb/cockroach/blob/c61b6f38f05a0552d0e091f52d0fde54ae4de8d3/pkg/sql/opt/memo/logical_props_builder.go#L1474)):*
> ```Go
> 		}
> 
> 		// Lookup join has implicit equality conditions on the merge columns.
> ```

Lookup join -> Merge join
___
*[pkg/sql/opt/memo/testdata/stats/join, line 197 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35074#-LZAZdVY7RsfGaONAuRn:-LZAZdVY7RsfGaONAuRo:b-cay6p4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c61b6f38f05a0552d0e091f52d0fde54ae4de8d3/pkg/sql/opt/memo/testdata/stats/join#L197)):*
> ```
> SELECT * FROM xysd, b
> ----
> error: no data source matches prefix: "b"
> ```

These tests are broken now
___
*[pkg/sql/opt/norm/prune_cols.go, line 433 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35074#-LZA_Kvw9XJBOHXXOR8Q:-LZA_Kvw9XJBOHXXOR8R:b-uwjdnb) ([raw file](https://github.com/cockroachdb/cockroach/blob/c61b6f38f05a0552d0e091f52d0fde54ae4de8d3/pkg/sql/opt/norm/prune_cols.go#L433)):*
> ```Go
> 
> 	case opt.IndexJoinOp, opt.LookupJoinOp, opt.MergeJoinOp:
> 		// There is no need to prune columns projected by Index or Lookup joins,
> ```

or merge joins

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35074)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

___
*[pkg/sql/opt/memo/logical_props_builder.go, line 1474 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35074#-LZAXvQ64mhpXz3lKuRW:-LZAaV1C7mZU0A-CM8Wq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c61b6f38f05a0552d0e091f52d0fde54ae4de8d3/pkg/sql/opt/memo/logical_props_builder.go#L1474)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Lookup join -> Merge join
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/testdata/stats/join, line 197 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35074#-LZAZdVY7RsfGaONAuRn:-LZAadrq8O1SIx8OQtcF:b-gpnb6d) ([raw file](https://github.com/cockroachdb/cockroach/blob/c61b6f38f05a0552d0e091f52d0fde54ae4de8d3/pkg/sql/opt/memo/testdata/stats/join#L197)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

These tests are broken now
</blockquote></details>

Ugh, that was sloppy of me.. Fixed.
___
*[pkg/sql/opt/norm/prune_cols.go, line 433 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35074#-LZA_Kvw9XJBOHXXOR8Q:-LZAadik-eC_d2Rzpy3W:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c61b6f38f05a0552d0e091f52d0fde54ae4de8d3/pkg/sql/opt/norm/prune_cols.go#L433)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

or merge joins
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35074#-:-LZAkDik2wnEfHnw089r:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
