### PR TITLE
sql: support creating and dropping triggers

### LINKED ISSUE #126359: sql: add support for create/drop trigger
This issue tracks adding support for creating and dropping a trigger on a table. This work will require updating function descriptors for trigger functions so that the function cannot be dropped and create a dangling reference. See the Postgres docs here: https://www.postgresql.org/docs/16/sql-createtrigger.html and here: https://www.postgresql.org/docs/16/sql-droptrigger.html

Epic [CRDB-347](https://cockroachlabs.atlassian.net/browse/CRDB-347)

Jira issue: CRDB-39859

### PR DESCRIPTION
**Pull request by DrewKimball**
#### sql: add trigger descriptor

This commit adds a `Triggers` field to the table descriptor, which is
a list of `TriggerDescriptor` structs. `TriggerDescriptor` contains all
the information needed to build and execute a trigger, including the
timing, matched event type, and fully-resolved trigger function body.
This commit also adds the logic needed to track and update object
references and back-references within descriptors due to triggers.

Informs #126359

Release note: None

#### schemachanger: support CREATE TRIGGER in the declarative schema changer

This commit adds support for `CREATE TRIGGER` statements to the declarative
schema changer. The implementation assumes that most of the validation will
be carried out during planning, apart from checking for cross-database
references. Note that `CREATE TRIGGER` will not be implemented in the
legacy schema changer.

Informs #126359

Release note: None

#### schemachanger: support DROP TRIGGER in the declarative schema changer

This commit adds `DROP TRIGGER` support to the declarative schema changer.
Just as with `CREATE TRIGGER`, `DROP TRIGGER` will not be implemented in
the legacy schema changer.

Informs #126359

Release note (sql change): Implemented DROP TRIGGER statements. Note that
the CASCADE option for dropping a trigger is not supported.

#### opt: add support for CREATE TRIGGER in optimizer

This commit finalizes support for `CREATE TRIGGER` by adding support
for it in the optimizer. This includes validation for the statement,
dependency resolution, and logic tests.

Fixes #126359

Release note (sql change): Added support for CREATE TRIGGER. Note that
OR REPLACE syntax is not yet supported.

### CODE REVIEW

**Comment by DrewKimball** [comment]
The first commit is #126734. I'm happy to split this into multiple PRs if that will make reviewing easier - my thinking in keeping things the way they are is to keep all the changes in the same PR as the logic tests that test them.

**Review by fqazi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128540)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/schemachanger/scpb/elements.proto` line 462 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-O3m7SwT6-nnygmljk5u:-O3m7SwT6-nnygmljk5v:bwfkahz) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd7a90ecd857b5690dc57dae7b91bff5ad618bcc/pkg/sql/schemachanger/scpb/elements.proto#L462)):*
> ```proto
>   uint32 trigger_id = 2 [(gogoproto.customname) = "TriggerID", (gogoproto.casttype) = "github.com/cockroachdb/cockroach/pkg/sql/sem/catid.TriggerID"];
>   string name = 3;
>   bool enabled = 4;
> ```

I think to make life easier supporting the ALTER to toggle the trigger we probably should break this out into a separate element (could just an empty one called TriggerEnabled, containing the IDs). Otherwise, on the declarative schema changer side you'll get need to weird dance of swapping the entire trigger element to modify it.

**Review by mgartner — APPROVED** [review]
Optimizer changes :lgtm: Nice work!

Breaking this up might have been nice, but I understand your point about the tests.

> Reviewed 8 of 8 files at r1, 16 of 16 files at r2, 42 of 42 files at r3, 13 of 13 files at r4, 29 of 29 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-:-O5xU5BS7SEmjf46HXEc:bvi6hdu)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-O5xLOCgDLxVp0Ygwe8k):*
nit: lazily => lazy
___
*[`-- commits` line 69 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-O5xTwLW9W0KtuXsN3eZ):*
nit: note that the triggers can be created but they aren't executed yet
___
*[`pkg/sql/opt/optbuilder/create_trigger.go` line 266 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-O5xSe9C5KHKEdGujIhA:-O5xSe9C5KHKEdGujIhB:b-3l94mb) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd7a90ecd857b5690dc57dae7b91bff5ad618bcc/pkg/sql/opt/optbuilder/create_trigger.go#L266)):*
> ```Go
> 	newName, oldName := scopeColName(triggerColNew), scopeColName(triggerColOld)
> 	newCol := b.synthesizeColumn(whenScope, newName, tableTyp, nil /* expr */, tup)
> 	oldCol := b.synthesizeColumn(whenScope, oldName, tableTyp, nil /* expr */, tup)
> ```

Instead of checking the `colRefs` below, we could only add NEW and OLD columns to the scope when they are allowed to be referenced. But I suppose the error messages are more clear this way, so I think we should leave as-is.
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 143 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-O5xMGiYDN4v02sq22hI:-O5xMGiYDN4v02sq22hJ:baktv55) ([raw file](https://github.com/cockroachdb/cockroach/blob/1af9f9262e05fffcf34e763cb5c8bd27df0fed73/pkg/sql/opt/optbuilder/plpgsql.go#L143)):*
> ```Go
> // behavior is implemented by replacing SQL expressions with typed NULL values,
> // and SQL statements by a single-row VALUES operator with no columns. See also
> // the buildSQLExpr and buildSQLStatement methods.
> ```

nit: The reasoning for replacing the SQL expressions could be more explicit here, e.g., "In order to validate the PL/pgSQL during the creation of a trigger function, without analyzing SQL statements, we replace SQL expressions with typed NULL values, and SQL statements by a single-row VALUES operator with no columns."
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-O5xLlHIAFbhpnFsfoDY:-O5xLlHIAFbhpnFsfoDZ:b11u6oa) ([raw file](https://github.com/cockroachdb/cockroach/blob/1af9f9262e05fffcf34e763cb5c8bd27df0fed73/pkg/sql/opt/optbuilder/plpgsql.go#L191)):*
> ```Go
> 	routineName   string
> 	isProcedure   bool
> 	lazilyEvalSQL bool
> ```

nit: would "analyzeSQL" or "validateSQL" as the inverse of this bool be a more accurate name? The plpgsql compiler doesn't really have a concept of laziness here - it's either validating SQL expressions or not, but it's not doing anything lazily.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/triggers` line 1110 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-O5xQAUt6ArnEfHau9r7:-O5xQAUt6ArnEfHau9r8:b-nx5z29) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd7a90ecd857b5690dc57dae7b91bff5ad618bcc/pkg/ccl/logictestccl/testdata/logic_test/triggers#L1110)):*
> ```
> 
> statement ok
> CREATE FUNCTION get_triggers() RETURNS JSON LANGUAGE PLpgSQL AS $$
> ```

Nice tests!!!

I also like how we are dogfooding UDFs here in our triggers tests :)

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128540)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @fqazi and @mgartner)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-O5xLOCgDLxVp0Ygwe8k):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: lazily => lazy
</blockquote></details>

Done.
___
*[`pkg/sql/opt/optbuilder/create_trigger.go` line 266 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-O5xSe9C5KHKEdGujIhA:-O6-XaQa2JcvG4ZTBZ0s:bxxsen8) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd7a90ecd857b5690dc57dae7b91bff5ad618bcc/pkg/sql/opt/optbuilder/create_trigger.go#L266)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Instead of checking the `colRefs` below, we could only add NEW and OLD columns to the scope when they are allowed to be referenced. But I suppose the error messages are more clear this way, so I think we should leave as-is.
</blockquote></details>

Yeah, this way is nice because we can get the exact same error message as Postgres.
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 143 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-O5xMGiYDN4v02sq22hI:-O6-_3Mq21a3cLe7OPUJ:b3dzmjf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1af9f9262e05fffcf34e763cb5c8bd27df0fed73/pkg/sql/opt/optbuilder/plpgsql.go#L143)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: The reasoning for replacing the SQL expressions could be more explicit here, e.g., "In order to validate the PL/pgSQL during the creation of a trigger function, without analyzing SQL statements, we replace SQL expressions with typed NULL values, and SQL statements by a single-row VALUES operator with no columns."
</blockquote></details>

I've modified the comment; let me know what you think.
___
*[`pkg/sql/opt/optbuilder/plpgsql.go` line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-O5xLlHIAFbhpnFsfoDY:-O6-_BGU0VSKsUqqrZ4M:bw24x05) ([raw file](https://github.com/cockroachdb/cockroach/blob/1af9f9262e05fffcf34e763cb5c8bd27df0fed73/pkg/sql/opt/optbuilder/plpgsql.go#L191)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: would "analyzeSQL" or "validateSQL" as the inverse of this bool be a more accurate name? The plpgsql compiler doesn't really have a concept of laziness here - it's either validating SQL expressions or not, but it's not doing anything lazily.
</blockquote></details>

Sure, that makes sense. I went with `buildSQL`, since this applies to the execution path as well as function creation.
___
*[`pkg/sql/schemachanger/scpb/elements.proto` line 462 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-O3m7SwT6-nnygmljk5u:-O5MWBth-I-c40BX0fXN:b-z9vinz) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd7a90ecd857b5690dc57dae7b91bff5ad618bcc/pkg/sql/schemachanger/scpb/elements.proto#L462)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

I think to make life easier supporting the ALTER to toggle the trigger we probably should break this out into a separate element (could just an empty one called TriggerEnabled, containing the IDs). Otherwise, on the declarative schema changer side you'll get need to weird dance of swapping the entire trigger element to modify it.
</blockquote></details>

That makes sense to me, thanks. Done.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/triggers` line 1110 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-O5xQAUt6ArnEfHau9r7:-O6-_sag-MG5_nFzxf-n:b32vhw) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd7a90ecd857b5690dc57dae7b91bff5ad618bcc/pkg/ccl/logictestccl/testdata/logic_test/triggers#L1110)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Nice tests!!!

I also like how we are dogfooding UDFs here in our triggers tests :)
</blockquote></details>

:)

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128540)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @fqazi and @mgartner)

___
*[`-- commits` line 69 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-O5xTwLW9W0KtuXsN3eZ):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: note that the triggers can be created but they aren't executed yet
</blockquote></details>

Done.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128540)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @fqazi and @mgartner)

___
*[`pkg/sql/schemachanger/scpb/elements.proto` line 462 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-O3m7SwT6-nnygmljk5u:-O6-ix9_DZ4dNFmgHZ5Z:b-6eapt8) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd7a90ecd857b5690dc57dae7b91bff5ad618bcc/pkg/sql/schemachanger/scpb/elements.proto#L462)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

That makes sense to me, thanks. Done.
</blockquote></details>

Do you think it would be worth doing something similar for the name, for `ALTER TRIGGER ... RENAME TO ...`?

**Review by fqazi — APPROVED** [review]
Amazing work Drew! Just very minor comments

 :lgtm: 

> Reviewed 8 of 16 files at r7, 1 of 43 files at r8, 10 of 87 files at r13, 86 of 86 files at r17, 46 of 46 files at r18, 13 of 13 files at r19, 35 of 35 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-:-O8HmPIi2MDtH0-kP4UI:bgjjilr)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/catalog/rewrite/rewrite.go` line 94 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-O8HhpZgAjPJQQuxgc6Q:-O8HhpZgAjPJQQuxgc6R:bin3tkp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6817cd939b68345f3ac1a49f57a5bc864b0cbdd/pkg/sql/catalog/rewrite/rewrite.go#L94)):*
> ```Go
> 			func(expr *string, typ catalog.DescExprType) error {
> 				if typ != catalog.SQLExpr {
> 					// TODO(drewk): handle this case.
> ```

Do we at least want to give a not implemented error?
___
*[`pkg/sql/catalog/tabledesc/validate.go` line 1401 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-O8HiM_k0NPQxZZQKMya:-O8HiM_k0NPQxZZQKMyb:bbgxjk5) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6817cd939b68345f3ac1a49f57a5bc864b0cbdd/pkg/sql/catalog/tabledesc/validate.go#L1401)):*
> ```Go
> 		// and status of the referenced objects are checked in
> 		// ValidateForwardReferences for the table.
> 		for idx, depID := range trigger.DependsOn {
> ```

Nit: Might want to check for duplicates too, maybe just use an DescriptorIDSet for this check?
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go` line 72 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-O8HkPFDCxVVLVtHhZvx:-O8HkPFE2IgAWH_ZCZPD:b-mb8fm0) ([raw file](https://github.com/cockroachdb/cockroach/blob/360376ffd0b8ac6d03141e0add33f898874ee650/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go#L72)):*
> ```Go
> 	reflect.TypeOf((*tree.CreateDatabase)(nil)):      {fn: CreateDatabase, statementTags: []string{tree.CreateDatabaseTag}, on: true, checks: isV241Active},
> 	reflect.TypeOf((*tree.SetZoneConfig)(nil)):       {fn: SetZoneConfig, statementTags: []string{tree.ConfigureZoneTag}, on: true, checks: isV242Active},
> 	reflect.TypeOf((*tree.CreateTrigger)(nil)):       {fn: CreateTrigger, statementTags: []string{tree.CreateTriggerTag}, on: true, checks: nil /* isV243Active */},
> ```

Are you waiting for the version bump here?
___
*[`pkg/sql/schemachanger/scexec/scmutationexec/helpers.go` line 137 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-O8HkZc41hsdDtW6Vj2x:-O8HkZc41hsdDtW6Vj2y:bl7qll2) ([raw file](https://github.com/cockroachdb/cockroach/blob/360376ffd0b8ac6d03141e0add33f898874ee650/pkg/sql/schemachanger/scexec/scmutationexec/helpers.go#L137)):*
> ```Go
> 		return nil, err
> 	}
> 	for idx := range tbl.Triggers {
> ```

Nit: Could we use catalog.FindTriggerByID here

**Review by fqazi — COMMENTED** [review]
Also lets get coverage inside the end-to-end schema change tests as well, lets get CREATE / DROP trigger coverage inside:
pkg/sql/schemachanger/testdata/end_to_end. Might also be worth adding a DROP TABLE test with a trigger references for sanity.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-:-O8HmqZU1NHxH38dAjxH:byxfvhw)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @mgartner)

**Review by mgartner — COMMENTED** [review]
First 2 commits LGTM. Will review the last 2 shortly.

> Reviewed 8 of 16 files at r7, 1 of 43 files at r8, 10 of 87 files at r13, 3 of 38 files at r16, 86 of 86 files at r17, 46 of 46 files at r18.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-:-O8IXhAi83npVFzxdwNa:byktag7)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @fqazi)

___
*[`pkg/sql/catalog/descriptor.go` line 623 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-O8HcAgL2uzQzto8anel:-O8HcAgL2uzQzto8anem:b-3m9o0h) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6817cd939b68345f3ac1a49f57a5bc864b0cbdd/pkg/sql/catalog/descriptor.go#L623)):*
> ```Go
> 
> 	// GetAllReferencedTableIDs returns all relation IDs that this table
> 	// references.
> ```

nit: List the ways that a table can reference other tables.
___
*[`pkg/sql/catalog/descriptor.go` line 645 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-O8HcRcH6qPZlPQZSkuw:-O8HcRcH6qPZlPQZSkux:b-p6xtcq) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6817cd939b68345f3ac1a49f57a5bc864b0cbdd/pkg/sql/catalog/descriptor.go#L645)):*
> ```Go
> 	// GetAllReferencedFunctionIDsInTrigger returns descriptor IDs of all user
> 	// defined functions referenced in this trigger.
> 	GetAllReferencedFunctionIDsInTrigger(triggerID descpb.TriggerID) DescriptorIDSet
> ```

Can more than one function be referenced by a single trigger?
___
*[`pkg/sql/catalog/rewrite/rewrite.go` line 95 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-O8HdlNVDOnU_7j4rsyC:-O8HdlNVDOnU_7j4rsyD:b-qa74mk) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6817cd939b68345f3ac1a49f57a5bc864b0cbdd/pkg/sql/catalog/rewrite/rewrite.go#L95)):*
> ```Go
> 				if typ != catalog.SQLExpr {
> 					// TODO(drewk): handle this case.
> 					return nil
> ```

Should we return an unimplemented error here for now?
___
*[`pkg/sql/sem/tree/create_trigger.go` line 151 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-O8IXBkH0Kzy_le01sCG:-O8IXBkH0Kzy_le01sCH:b-bd0vwe) ([raw file](https://github.com/cockroachdb/cockroach/blob/360376ffd0b8ac6d03141e0add33f898874ee650/pkg/sql/sem/tree/create_trigger.go#L151)):*
> ```Go
> // TriggerEventTypeSet is a set of TriggerEventType values, used to conveniently
> // check for the presence of a given event type in a trigger definition.
> type TriggerEventTypeSet uint8
> ```

For extra future-proofing, you can add a compile-time check to ensure that `uint8` is big enough to hold all the trigger event types: https://go.dev/play/p/ePlTTU8VkCZ

**Review by mgartner — APPROVED** [review]
:lgtm: Great work!

> Reviewed 13 of 13 files at r19, 35 of 35 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-:-O8It7l019cHNqPXNI5A:bolbkdq)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @DrewKimball and @fqazi)

___
*[`pkg/sql/opt_exec_factory.go` line 1913 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-O8IrNeM3wCIpFARcmjg:-O8IrNeM3wCIpFARcmjh:b-2jn59y) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf828cee1ad57513f697fb966dcc4f0ffd74d565/pkg/sql/opt_exec_factory.go#L1913)):*
> ```Go
> 	if plan == nil {
> 		return nil, pgerror.New(pgcode.FeatureNotSupported,
> 			"CREATE TRIGGER is only implemented in the declarative schema changer")
> ```

I thought this error was produced elsewhere, no?
___
*[`pkg/sql/opt/cat/view.go` line 42 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-O8IrcS08rxggJywsjBh:-O8IrcS08rxggJywsjBi:bqbflxy) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf828cee1ad57513f697fb966dcc4f0ffd74d565/pkg/sql/opt/cat/view.go#L42)):*
> ```Go
> 	IsSystemView() bool
> 
> 	// TriggerCount returns the number of triggers present on the table.
> ```

nit: "table" => "view"

**Review by DrewKimball — COMMENTED** [review]
TFTRs!

>Also lets get coverage inside the end-to-end schema change tests as well, lets get CREATE / DROP trigger coverage inside:  
pkg/sql/schemachanger/testdata/end_to_end. Might also be worth adding a DROP TABLE test with a trigger references for sanity.

I've added some tests. LMK if it's what you were thinking.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-:-O8nqp_Q51XfXxxGh6rc:bg3suf8)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @fqazi and @mgartner)

___
*[`pkg/sql/opt_exec_factory.go` line 1913 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-O8IrNeM3wCIpFARcmjg:-O8o7o915s7qw9F-6gJ_:bvp9jmh) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf828cee1ad57513f697fb966dcc4f0ffd74d565/pkg/sql/opt_exec_factory.go#L1913)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I thought this error was produced elsewhere, no?
</blockquote></details>

We call into the declarative schema changer [here](https://github.com/cockroachdb/cockroach/blob/85e5cda4765056312074791c10bfa476bd9571a0/pkg/sql/opaque.go#L52), which eventually leads to this point.
___
*[`pkg/sql/catalog/descriptor.go` line 623 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-O8HcAgL2uzQzto8anel:-O8nqTSV19ZBVN20HgBO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6817cd939b68345f3ac1a49f57a5bc864b0cbdd/pkg/sql/catalog/descriptor.go#L623)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: List the ways that a table can reference other tables.
</blockquote></details>

Done.
___
*[`pkg/sql/catalog/descriptor.go` line 645 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-O8HcRcH6qPZlPQZSkuw:-O8nqeRf9afKUBld3kpD:b-phvftk) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6817cd939b68345f3ac1a49f57a5bc864b0cbdd/pkg/sql/catalog/descriptor.go#L645)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Can more than one function be referenced by a single trigger?
</blockquote></details>

Yes - the trigger function, and any functions it references. I've added that to the comment here.
___
*[`pkg/sql/catalog/rewrite/rewrite.go` line 94 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-O8HhpZgAjPJQQuxgc6Q:-O8nnNnh9r_IvLnJ0QFK:b-fitg1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6817cd939b68345f3ac1a49f57a5bc864b0cbdd/pkg/sql/catalog/rewrite/rewrite.go#L94)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Do we at least want to give a not implemented error?
</blockquote></details>

Sorry it's a bit confusing - I actually implemented this case here: https://github.com/cockroachdb/cockroach/pull/128555.
___
*[`pkg/sql/catalog/rewrite/rewrite.go` line 95 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-O8HdlNVDOnU_7j4rsyC:-O8nnSmD3DaNzupJdUcs:b-8v5tu7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6817cd939b68345f3ac1a49f57a5bc864b0cbdd/pkg/sql/catalog/rewrite/rewrite.go#L95)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Should we return an unimplemented error here for now?
</blockquote></details>

See above - it's implemented here: https://github.com/cockroachdb/cockroach/pull/128555.
___
*[`pkg/sql/catalog/tabledesc/validate.go` line 1401 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-O8HiM_k0NPQxZZQKMya:-O8noBKh-kMhxtOmId9r:b-1w2iw2) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6817cd939b68345f3ac1a49f57a5bc864b0cbdd/pkg/sql/catalog/tabledesc/validate.go#L1401)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Nit: Might want to check for duplicates too, maybe just use an DescriptorIDSet for this check?
</blockquote></details>

Sure, Done.
___
*[`pkg/sql/opt/cat/view.go` line 42 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-O8IrcS08rxggJywsjBh:-O8noI7W211tnZZBBomR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf828cee1ad57513f697fb966dcc4f0ffd74d565/pkg/sql/opt/cat/view.go#L42)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: "table" => "view"
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go` line 72 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-O8HkPFDCxVVLVtHhZvx:-O8noW9u8r-tu2nCdhLr:b-sg86bd) ([raw file](https://github.com/cockroachdb/cockroach/blob/360376ffd0b8ac6d03141e0add33f898874ee650/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go#L72)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Are you waiting for the version bump here?
</blockquote></details>

I was, yeah. I've updated it now to references 24.3.
___
*[`pkg/sql/schemachanger/scexec/scmutationexec/helpers.go` line 137 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-O8HkZc41hsdDtW6Vj2x:-O8nooL34wkF5ok_GUJZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/360376ffd0b8ac6d03141e0add33f898874ee650/pkg/sql/schemachanger/scexec/scmutationexec/helpers.go#L137)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Nit: Could we use catalog.FindTriggerByID here
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/scpb/elements.proto` line 462 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-O3m7SwT6-nnygmljk5u:-O8o88xXB4tlcHc0r7gt:b-h7k0cc) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd7a90ecd857b5690dc57dae7b91bff5ad618bcc/pkg/sql/schemachanger/scpb/elements.proto#L462)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Do you think it would be worth doing something similar for the name, for `ALTER TRIGGER ... RENAME TO ...`?
</blockquote></details>

I ended up doing this.
___
*[`pkg/sql/sem/tree/create_trigger.go` line 151 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-O8IXBkH0Kzy_le01sCG:-O8npP044p63ZLNJ_6O1:b-kdrxbz) ([raw file](https://github.com/cockroachdb/cockroach/blob/360376ffd0b8ac6d03141e0add33f898874ee650/pkg/sql/sem/tree/create_trigger.go#L151)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

For extra future-proofing, you can add a compile-time check to ensure that `uint8` is big enough to hold all the trigger event types: https://go.dev/play/p/ePlTTU8VkCZ
</blockquote></details>

That's a nice trick, done.

**Review by fqazi — APPROVED** [review]
This all looks great, nice work. Maybe not in this PR but a follow on one lets have rules added so that the we constrain which element can become public first. For examples look inside: pkg/sql/schemachanger/scplan/internal/rules/current. But I think you want the main trigger element to public first followed by dependents.

> Reviewed 98 of 98 files at r21, 46 of 46 files at r22, 13 of 13 files at r23, 48 of 48 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-:-O8oKA5Q-QUvU0pGo542:b-4meltq)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/schemachanger/scpb/elements.proto` line 462 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/128540#-O3m7SwT6-nnygmljk5u:-O8oIYrV7lhS04eD5VNI:buoh6ur) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd7a90ecd857b5690dc57dae7b91bff5ad618bcc/pkg/sql/schemachanger/scpb/elements.proto#L462)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

I ended up doing this.
</blockquote></details>

Yes, we should split the name off into a seperate element if we renaming needs to be supported.

**Comment by DrewKimball** [comment]
>This all looks great, nice work. Maybe not in this PR but a follow on one lets have rules added so that the we constrain which element can become public first. For examples look inside: pkg/sql/schemachanger/scplan/internal/rules/current. But I think you want the main trigger element to public first followed by dependents.

Oh nice, I wasn't aware we could do that. I'll post a follow-up after this merges.

**Pull request merged**
