### PR TITLE
tenantcostclient: improve token bucket client

### PR DESCRIPTION
**Pull request by andy-kimball**
This PR contains a series of improvements to the token bucket client
that make it behave better when using rate limiting. Each improvement
is encapsulated in a separate commit.

### CODE REVIEW

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113236)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @JeffSwenson)

___
*[`pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113236#gh-1376288788:-Ni1otSs4P44_XyCBSh3:b-q95op8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8e31abcf2dd27352890e42db306da2ccfc16537/pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go#L38)):*
<details><summary><i>Previously, JeffSwenson (Jeff Swenson) wrote…</i></summary><blockquote>

Have you tested the setting on a standalone sql server? I audited the code and think this will work, but settings tend to behave more consistently in the test server than they do during actual process start up.
</blockquote></details>

Yes, I've tested various scenarios with up to 3 standalone SQL processes coming up, going down, and shifting their RU/s rates.
___
*[`pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go` line 635 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/113236#gh-1376351401:-Ni1oKcw4Els56EAd2w8:bq5ob1t) ([raw file](https://github.com/cockroachdb/cockroach/blob/63d7a3057737805c47caf304e41320ed462c89a2/pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go#L635)):*
<details><summary><i>Previously, JeffSwenson (Jeff Swenson) wrote…</i></summary><blockquote>

Will the server return a partial RU grant with no trickle rate? I would expect an unfilled grant to indicate the server is in debt and the client was provided with an ru/s rate.

If there is no trickle duration or notify threshold, how does the client decide when to request more RUs?
</blockquote></details>

Yes, the server will do so in the case where it's out of RUs and there is no fill rate - it will not go into debt in that case, because there's no hope of it being paid back.

If there is no notify threshold, eventually the `onTick` will fire and will contact the server (i.e. the next regularly scheduled consumption reporting interval). If the RU consumption threshold has been reached, then this happens within 10 seconds. If not, then it happens within 40 seconds.

**Comment by andy-kimball** [comment]
*[`pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113236#gh-1376288788:-Ni1pqb95moIgg2Oe7BD:b8qez2s) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8e31abcf2dd27352890e42db306da2ccfc16537/pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go#L38)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Yes, I've tested various scenarios with up to 3 standalone SQL processes coming up, going down, and shifting their RU/s rates.
</blockquote></details>

I wonder if I should make this `SystemOnly`, given that I don't see any reason why tenants need to access it.

**Review by jeffswenson — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113236)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball)

___
*[`pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113236#gh-1376288788:-Ni6_b6rBh0uxJ8d3-Gu:b-fdetbt) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8e31abcf2dd27352890e42db306da2ccfc16537/pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go#L38)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I wonder if I should make this `SystemOnly`, given that I don't see any reason why tenants need to access it.
</blockquote></details>

I think `SystemVisible` is what you want here since tenant sql servers use this in `initRunState` to initialize their default fill rate.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113236)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @JeffSwenson)

___
*[`pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113236#gh-1376288788:-Ni6cksxBxB-AXUXc8JL:b-gq7kwr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8e31abcf2dd27352890e42db306da2ccfc16537/pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go#L38)):*
<details><summary><i>Previously, JeffSwenson (Jeff Swenson) wrote…</i></summary><blockquote>

I think `SystemVisible` is what you want here since tenant sql servers use this in `initRunState` to initialize their default fill rate.
</blockquote></details>

I see, so even our SQL process code can't access `SystemOnly` settings. I thought it was just that they wouldn't be exposed to the user via the `SHOW CLUSTER SETTING` command, but they're still accessible to our code.

**Review by jeffswenson — APPROVED** [review]
LGTM

**Pull request merged**
