### PR TITLE
sql: make SHOW TABLES able to inspect arbitrary schemas

### LINKED ISSUE #22964: sql: No easy way to view schemas
How to I see the different schema options? How do I know that the virtual schemas exist?

It would be nice to have a `SHOW SCHEMAS` command line option.

Found during QA for #22753

### LINKED ISSUE #22995: sql: SHOW TABLES not using database session variable
When the database session variable is set to `t`:
```
root@:26257/t> show tables from information_schema;
pq: database "information_schema" does not exist
root@:26257/t> show tables from t.information_schema;
+-----------------------------------+
|               Table               |
+-----------------------------------+
| administrable_role_authorizations |
| applicable_roles                  |
| column_privileges                 |
| columns                           |
| constraint_column_usage           |
| enabled_roles                     |
| key_column_usage                  |
| referential_constraints           |
| role_table_grants                 |
| schema_privileges                 |
| schemata                          |
| sequences                         |
| statistics                        |
| table_constraints                 |
| table_privileges                  |
| tables                            |
| user_privileges                   |
| views                             |
+-----------------------------------+
(18 rows)

Time: 2.48ms
```

Even though the database is set to `t`, the schema must be qualified with the database name for `SHOW TABLES` to work.

### PR DESCRIPTION
**Pull request by knz**
Fixes #22995.

With the introduction of compatibility with schema specifications,
SHOW TABLES was modified to recognize the following two forms:

     SHOW TABLES FROM <db>
     SHOW TABLES FROM <db> . <schema>

So one could, for example, issue `SHOW TABLES FROM system.pg_catalog`
to see all tables in `system`'s `pg_catalog`.

However this change broke a use case, as users were previously able to
use `SHOW TABLES` directly on virtual schemas, e.g. `SHOW TABLES FROM
crdb_internal`.

This patch restores this functionality, by making `SHOW TABLES`
resolve its parameter as if it was a star prefix in GRANT.  That is,
`SHOW TABLES FROM crdb_internal` will first try to find a database
called `crdb_internal`, and if that fails will try the current
database's schema called `crdb_internal`.

Release note (bug fix): `SHOW TABLES` is now again able to inspect
virtual schemas.

### CODE REVIEW

**Comment by rytaft** [comment]
Just checking: now that you've added `SHOW TABLES FROM <schema>`, does `SHOW TABLES FROM <db>` still work (both when the database session variable is set and unset)? How about `SHOW TABLES FROM public`, when there is a database named public?

---

Reviewed 7 of 11 files at r2, 5 of 7 files at r3, 11 of 11 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22994#-:-L626U43BkGMvaAwZ7vq:bxnenoi)*

**Comment by knz** [comment]
The commit message explains:

> That is, SHOW TABLES FROM crdb_internal will first try to find a database called crdb_internal, and if that fails will try the current database's schema called crdb_internal.

This is also explained in the name resolution RFC

**Comment by rytaft** [comment]
I saw that - just want to make sure the test cases cover it. If existing tests already cover that case then that's great - but as far as I can tell the new tests are only testing `SHOW TABLES` for virtual schemas.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22994#-:-L62FTkkZS0NBX7_r5pR:b21f896)*

**Comment by knz** [comment]
(In the future, if you want me to point you to a test, please ask me. If you merely give me a question mark, I will answer your question, not my code)

**Comment by rytaft** [comment]
Sorry I wasn't clear earlier!  The new tests look good.  Is there already a test for the specific case of `SHOW TABLES FROM <db>` when the database is set and unset?

---

Reviewed 18 of 18 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/logictest/testdata/logic_test/case_sensitive_names, line 11 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/22994#-L63a7IquS96-aRndQ_5:-L63a7IquS96-aRndQ_6:b-pckhrb) ([raw file](https://github.com/cockroachdb/cockroach/blob/38673ed5d8d0fa0432e429b6ce69af48bad2b868/pkg/sql/logictest/testdata/logic_test/case_sensitive_names#L11)):*
> ```
> SHOW TABLES FROM d
> 
> statement error pattern "D" did not match any valid database or schema
> ```

[nit] "pattern" is a bit of a technical word... I think it would be enough to say:
```
"D" does not match any valid database or schema
```

---

*[pkg/sql/logictest/testdata/logic_test/case_sensitive_names, line 17 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/22994#-L63aKDHsMasGIBSm3lC:-L63aKDHsMasGIBSm3lD:b-89a4l7) ([raw file](https://github.com/cockroachdb/cockroach/blob/38673ed5d8d0fa0432e429b6ce69af48bad2b868/pkg/sql/logictest/testdata/logic_test/case_sensitive_names#L17)):*
> ```
> CREATE DATABASE "E"
> 
> statement error pattern "e" did not match any valid database or schema
> ```

Ditto

---

*[pkg/sql/logictest/testdata/logic_test/set, line 44 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/22994#-L63ZiDVnAju96dAzJ0B:-L63ZiDVnAju96dAzJ0C:b-2xbtxr) ([raw file](https://github.com/cockroachdb/cockroach/blob/38673ed5d8d0fa0432e429b6ce69af48bad2b868/pkg/sql/logictest/testdata/logic_test/set#L44)):*
> ```
> ·
> 
> statement error pattern "public" did not match any valid database or schema
> ```

This error message is a bit odd since "public" was not specified in the statement

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22994#-:-L63aRAtZwdysPjb3mNv:b-6p90q2)*

**Comment by knz** [comment]
>  Is there already a test for the specific case of SHOW TABLES FROM <db> when the database is set and unset?

Added one to the `set` logic tests.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/logictest/testdata/logic_test/case_sensitive_names, line 11 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/22994#-L63a7IquS96-aRndQ_5:-L66Z4qZDY-u4tkhPtXc:b-g2sofm) ([raw file](https://github.com/cockroachdb/cockroach/blob/38673ed5d8d0fa0432e429b6ce69af48bad2b868/pkg/sql/logictest/testdata/logic_test/case_sensitive_names#L11)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] "pattern" is a bit of a technical word... I think it would be enough to say:
```
"D" does not match any valid database or schema
```
</blockquote></details>

will follow up in #23039

---

*[pkg/sql/logictest/testdata/logic_test/set, line 44 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/22994#-L63ZiDVnAju96dAzJ0B:-L66Z9tlvAMM3cVOMBYo:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/38673ed5d8d0fa0432e429b6ce69af48bad2b868/pkg/sql/logictest/testdata/logic_test/set#L44)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This error message is a bit odd since "public" was not specified in the statement
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22994#-:-L66aVdSgLN85B5JBjBI:bljk4ah)*

**Comment by rytaft** [comment]
:lgtm: Thanks!

---

Reviewed 4 of 4 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22994#-:-L66vdMXr1rMg7LSBYKn:b-g2a5fb)*

**Comment by knz** [comment]
thanks to you for the quality feedback :)

**Pull request merged**
