### PR TITLE
sql: return correct pgerror code for CHECK errors

### PR DESCRIPTION
**Pull request by xudongzheng**
Same issue as #16836 except for CHECK constraints.

### CODE REVIEW

**Review by jordanlewis — APPROVED** [review]
Thanks!

**Review by jordanlewis — CHANGES_REQUESTED** [review]
Actually, while this looks perfectly sound, it would be best if you could augment one of the existing tests to ensure that the error code is present. Look in `pkg/sql/logictest/testdata/logic_test/check_constraints` for the existing logic tests for check constraints. You can augment a logic test with an expected pg error code by adding `pgcode XXXX` after the `statement error` - see the `fk` logic tests for some examples.

**Comment by xudongzheng** [comment]
Thank you for your feedback. There were lots of tests with the CHECK constraint statement error and I think I changed most (if not all) of them. Please let me know if there is anything else I should amend.

**Review by jordanlewis — APPROVED** [review]

**Comment by jordanlewis** [comment]
Thanks for the contribution @xudongzheng!

**Pull request merged**
