### PR TITLE
sql: Add DistSQL metadata propagation testing framework

### PR DESCRIPTION
**Pull request by abhimadan**
Now that TxnMetas are being sent as metadata through DistSQL, it is
possible to create subtle correctness bugs in transactions by
incorrectly propgating all metadata. These bugs are difficult to
reproduce, track down, and fix. Therefore, it has become more
important to rigorously test metadata propagation.

This commit adds a new RowNum metadata type, which correponds to a row
sent from a processor, as well as a final message to count the number of
rows sent. These messages are created from metadataTestSender
processors, which act as no-op processors that send additional metadata.
Each of these messages must be sent exactly once to a
metadataTestReceiver processor, which checks that:
1) it receives the number of expected RowNum messages; and
2) it receives only one of each RowNum.

This way, the test can detect both dropped and repeated messages.

To ensure that this test is run frequently, a new
`-disable-metadata-test` flag has been added to the logic test binary,
to ensure that metadata propagation is opt-out and therefore tested by
default.

Release note: None

### CODE REVIEW

**Comment by abhimadan** [comment]
This PR also adds a new vendored dependency in https://github.com/cockroachdb/vendored/pull/17.

**Comment by petermattis** [comment]
Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/distsql_running.go, line 24 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23731#-L7QsV5YRvNVy9OWsawL:-L7QsV5YRvNVy9OWsawM:b-s9tu32) ([raw file](https://github.com/cockroachdb/cockroach/blob/4914e9977f661f2b560a7bd072b49b1029a26d57/pkg/sql/distsql_running.go#L24)):*
> ```Go
> 	opentracing "github.com/opentracing/opentracing-go"
> 	"github.com/pkg/errors"
> 	"github.com/willf/bitset"
> ```

I haven't looked at this package in depth, but on the surface it seems similar to `util.FastIntSet`. Is there a reason it is a better choice here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23731)*

**Comment by abhimadan** [comment]
Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/distsql_running.go, line 24 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/23731#-L7QsV5YRvNVy9OWsawL:-L7Qw1ktSKAHhsQq2Kb8:bl7zj46) ([raw file](https://github.com/cockroachdb/cockroach/blob/4914e9977f661f2b560a7bd072b49b1029a26d57/pkg/sql/distsql_running.go#L24)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I haven't looked at this package in depth, but on the surface it seems similar to `util.FastIntSet`. Is there a reason it is a better choice here?
</blockquote></details>

I think `FastIntSet` should work fine here. I initially added that other package because I didn't know about it, so thanks for pointing it out!

Reverted the submodule pointer update since it's not necessary anymore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23731)*

**Comment by abhimadan** [comment]
Looks like I forgot about `joinReader` and `interleavedReaderJoiner`. I'll need to add the `RowNum` plumbing to those processors as well.

**Comment by jordanlewis** [comment]
Very cool. Good job so far. I'm wondering whether we could cut down on the repeated code and effects on the normal codepath, though. As it stands, this patch adds a lot of boolean conditions to hot loops - which is not an ideal situation for what is supposed to be test only code.

Is there a way that we could write a single shim processor that gets planned after all of the source processors that does the accounting and sending of the source UUID, extra metadata and row counts etc? That way, we would only have to add one bit of code that cares about this and wouldn't repeat the same logic scattered across all of the sources. Also, I think it's less likely to rot - someone adding a new source processor would have to duplicate this whole dance.

---

Reviewed 2 of 4 files at r1, 1 of 14 files at r3, 12 of 12 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql_running.go, line 278 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/23731#-L7arTTaJ-lUwcLg2MWu:-L7arTTaJ-lUwcLg2MWv:b-encpnn) ([raw file](https://github.com/cockroachdb/cockroach/blob/2daa44a1baea952bd37a49156eeaef8b0899fbef/pkg/sql/distsql_running.go#L278)):*
> ```Go
> 	updateClock func(observedTs hlc.Timestamp)
> 
> 	rowCounts map[string]rowNumCounter
> ```

It would be better if this didn't have to go into every distSQLReceiver, even when the test mode is off.

---

*[pkg/sql/distsqlrun/data.proto, line 241 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/23731#-L7aqgmDxHQ39VhcOwuD:-L7aqgmDxHQ39VhcOwuE:b-700226) ([raw file](https://github.com/cockroachdb/cockroach/blob/2daa44a1baea952bd37a49156eeaef8b0899fbef/pkg/sql/distsqlrun/data.proto#L241)):*
> ```protobuf
>     repeated util.tracing.RecordedSpan collected_spans = 1 [(gogoproto.nullable) = false];
>   }
>   message RowNum {
> ```

These need comments.

---

*[pkg/sql/distsqlrun/tablereader.go, line 48 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/23731#-L7aoyxnN46XcH76vu0O:-L7aoyxnN46XcH76vu0P:b3t32u9) ([raw file](https://github.com/cockroachdb/cockroach/blob/2daa44a1baea952bd37a49156eeaef8b0899fbef/pkg/sql/distsqlrun/tablereader.go#L48)):*
> ```Go
> 	// status is not NeedMoreRows.
> 	trailingMetadata []ProducerMetadata
> ```

These should probably be in a sub struct to make it clear that they're just for testing.

---

*[pkg/sql/distsqlrun/values.go, line 35 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/23731#-L7ap9BV4KmRy0lxW4Y1:-L7ap9BV4KmRy0lxW4Y2:bej2ofb) ([raw file](https://github.com/cockroachdb/cockroach/blob/2daa44a1baea952bd37a49156eeaef8b0899fbef/pkg/sql/distsqlrun/values.go#L35)):*
> ```Go
> 	sd     StreamDecoder
> 	rowBuf sqlbase.EncDatumRow
> ```

These are the same fields as above. You should make a struct that contains them so this isn't duplicated.

---

*[pkg/sql/distsqlrun/values.go, line 173 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/23731#-L7apLOYzWn2oJgXEtud:-L7apLOYzWn2oJgXEtue:b-eyc0ij) ([raw file](https://github.com/cockroachdb/cockroach/blob/2daa44a1baea952bd37a49156eeaef8b0899fbef/pkg/sql/distsqlrun/values.go#L173)):*
> ```Go
> 			}
> 			if v.flowCtx.testingKnobs.MetadataTestingEnabled {
> 				v.sendRowNumMeta = true
> ```

This seems like the wrong place to do this. Can't this go in the processor initialization phase?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23731#-:-L7aqtJreyG1JK84ZTT5:b-ap084)*

**Comment by abhimadan** [comment]
I've made two new processors, `metadataTestSender` and `metadataTestReceiver`, to encapsulate the test logic better. This also caused some problems with generating the right `EXPLAIN` diagrams in logic tests, so there are now different metadata testing levels to have more control over this: the logic test default is `NoExplain`. I'm thinking of exposing the `On` level as a logic test mode (something like `explain-meta-distsql`), but I'm open to suggestions on that.

---

Review status: 3 of 16 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/sql/distsqlrun/data.proto, line 241 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/23731#-L7aqgmDxHQ39VhcOwuD:-L7k3tGudflvryFSlYuF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2daa44a1baea952bd37a49156eeaef8b0899fbef/pkg/sql/distsqlrun/data.proto#L241)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

These need comments.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23731#-:-L7k6uBHThVb-lbAeW0R:b6wan5r)*

**Comment by jordanlewis** [comment]
This is great! Generally LGTM, but I'd like @arjunravinarayan to take a look too.

---

Review status: 3 of 17 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23731#-:-L82YpynmZ7dnrmY6H6j:b-cx9f82)*

**Comment by arjunravinarayan** [comment]
:lgtm:
Does this have a performance impact when turned off?

---

Reviewed 3 of 12 files at r4, 22 of 22 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/metadata_test_sender.go, line 28 at r5](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23731#-L8DrCde9qaYi9YppvyW:-L8DrCde9qaYi9YppvyX:be9gg5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ae5a339972f10035ae240d2f49cf696d7440456/pkg/sql/distsqlrun/metadata_test_sender.go#L28)):*
> ```Go
> 	id    string
> 
> 	sendRowNumMeta bool
> ```

Needs a comment. "This is set ot true after sending a row from the underlying input, and set to false when the matching metadata is sent." or something like that.

---

*[pkg/sql/distsqlrun/metadata_test_sender.go, line 29 at r5](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23731#-L8DrEFW9-MG2lNxy8Jv:-L8DrEFW9-MG2lNxy8Jw:bjbv8ib) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ae5a339972f10035ae240d2f49cf696d7440456/pkg/sql/distsqlrun/metadata_test_sender.go#L29)):*
> ```Go
> 
> 	sendRowNumMeta bool
> 	sentLastMsg    bool
> ```

As does this one, although I'm not sure what it does.

---

*[pkg/sql/logictest/logic.go, line 332 at r5](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23731#-L8Cz2aJDwCcw-XI_zWA:-L8Cz2aJDwCcw-XI_zWB:beuovp5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ae5a339972f10035ae240d2f49cf696d7440456/pkg/sql/logictest/logic.go#L332)):*
> ```Go
> 		"do not fail when a test expects a column of a numeric type but the query provides another type",
> 	)
> 	disableMetadataTest = flag.Bool(
> ```

It's not great to have a flag named "disable" as then you're parsing a double negative to understand what it does. Rename it to "enable-metadata-test"

---

*[pkg/sql/distsqlrun/tablereader.go, line 48 at r4](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23731#-L7aoyxnN46XcH76vu0O:-L8CzOEk8tWFrRmmbzW2:b45o21n) ([raw file](https://github.com/cockroachdb/cockroach/blob/2daa44a1baea952bd37a49156eeaef8b0899fbef/pkg/sql/distsqlrun/tablereader.go#L48)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

These should probably be in a sub struct to make it clear that they're just for testing.
</blockquote></details>

Abhishek forgot to "Done" this, but did what you suggested, so "Done"ing it to resolve the discussion.

---

*[pkg/sql/distsqlrun/values.go, line 35 at r4](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23731#-L7ap9BV4KmRy0lxW4Y1:-L8CzTxD5V5jMAONWcfR:bbr7wrv) ([raw file](https://github.com/cockroachdb/cockroach/blob/2daa44a1baea952bd37a49156eeaef8b0899fbef/pkg/sql/distsqlrun/values.go#L35)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

These are the same fields as above. You should make a struct that contains them so this isn't duplicated.
</blockquote></details>

Abhishek forgot to "Done" this, but did what you suggested, so "Done"ing it.

---

*[pkg/sql/distsqlrun/values.go, line 173 at r4](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23731#-L7apLOYzWn2oJgXEtud:-L8CzWQP4FSB56rHNsaQ:bbr7wrv) ([raw file](https://github.com/cockroachdb/cockroach/blob/2daa44a1baea952bd37a49156eeaef8b0899fbef/pkg/sql/distsqlrun/values.go#L173)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This seems like the wrong place to do this. Can't this go in the processor initialization phase?
</blockquote></details>

Abhishek forgot to "Done" this, but did what you suggested, so "Done"ing it.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23731#-:-L8YrIlsCpa4EvElVyEG:b-ci5rjf)*

**Pull request merged**
