### PR TITLE
roachtest: enforce FIXTURE_VERSION is passed to generate-fixtures

### PR DESCRIPTION
**Pull request by renatolabs**
Previously, the process of generating fixtures for a release would rely on an overwritten build tag using the no longer existent `--build-tag` flag. This commit replicates that behavior by forcing the caller to pass a `FIXTURE_VERSION` environment variable indicating the released version (likely a beta) to be used to generate the fixtures for that version.

This commit also removes the functionality to auto-discover the binary version to use from the test. In practice, we want to be explicit about the version, so this is now the only supported way to invoke the `generate-fixtures` test.

Epic: none

Release note: None

### CODE REVIEW

**Comment by renatolabs** [comment]
Running `generate-fixtures` with `FIXTURE_VERSION=v23.1.0-alpha.9` on this branch leads to the expected error (`successfully created checkpoints; failing test on purpose`).

**Review by celiala — APPROVED** [review]
this makes sense to me a high-level. also a quick skim of the code also makes sense to me!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101464#-:-NSvvdxdEY8QeD8lhbqN:b-nvc6qp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @smg260)

**Comment by renatolabs** [comment]
TFTR!

bors r=celiala

**Comment by renatolabs** [comment]
bors retry

**Comment by celiala** [comment]
bors ping

**Comment by celiala** [comment]
bors retry

**Comment by celiala** [comment]
bors cancel

**Pull request merged**
