### PR TITLE
sql: fix EXPLAIN ANALYZE (DEBUG) for queries with LocalPlanNode

### LINKED ISSUE #62261: sql: crash for `explain analyze (debug)` - NPE in `generateMeta()`
Happens on both master and release-21.1. 
Some distribution of the query needs to be necessary.

```
./cockroach demo --nodes=9 --global
create table promos(id serial primary key, s string);
create table users(id uuid default gen_random_uuid() primary key, promo_id int references promos(id));
explain analyze (debug) insert into users (promo_id) values (642606224929619969);
```

```
* EXPLAIN ANALYZE (DEBUG) INSERT INTO users(promo_id) VALUES (642606224929619969)
*
*
* ERROR: [n1,client=127.0.0.1:38888,hostssl,user=demo] a panic has occurred!
* runtime error: invalid memory address or nil pointer dereference
* (1) attached stack trace
*   -- stack trace:
*   | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
*   |   /home/andrei/src/github.com/cockroachdb/cockroach-2/pkg/sql/conn_executor.go:480
*   | [...repeated from below...]
* Wraps: (2) while executing: EXPLAIN ANALYZE (DEBUG) INSERT INTO _(_) VALUES (_)
* Wraps: (3) attached stack trace
*   -- stack trace:
*   | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
*   |   /home/andrei/src/github.com/cockroachdb/cockroach-2/pkg/sql/conn_executor.go:480
*   | runtime.gopanic
*   |   /home/andrei/goroot/src/runtime/panic.go:969
*   | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
*   |   /home/andrei/src/github.com/cockroachdb/cockroach-2/pkg/sql/colexecerror/error.go:58
*   | runtime.gopanic
*   |   /home/andrei/goroot/src/runtime/panic.go:969
*   | runtime.panicmem
*   |   /home/andrei/goroot/src/runtime/panic.go:212
*   | runtime.sigpanic
*   |   /home/andrei/goroot/src/runtime/signal_unix.go:742
*   | github.com/cockroachdb/cockroach/pkg/kv.(*Txn).Type
*   |   /home/andrei/src/github.com/cockroachdb/cockroach-2/pkg/kv/txn.go:1224
*   | github.com/cockroachdb/cockroach/pkg/sql/execinfra.GetLeafTxnFinalState
*   |   /home/andrei/src/github.com/cockroachdb/cockroach-2/pkg/sql/execinfra/base.go:267
*   | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*joinReader).generateMeta
*   |   /home/andrei/src/github.com/cockroachdb/cockroach-2/pkg/sql/rowexec/joinreader.go:761
*   | github.com/cockroachdb/cockroach/pkg/sql/rowexec.newJoinReader.func1
*   |   /home/andrei/src/github.com/cockroachdb/cockroach-2/pkg/sql/rowexec/joinreader.go:287
*   | github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBase).moveToTrailingMeta
*   |   /home/andrei/src/github.com/cockroachdb/cockroach-2/pkg/sql/execinfra/processorsbase.go:727
*   | github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBase).DrainHelper
*   |   /home/andrei/src/github.com/cockroachdb/cockroach-2/pkg/sql/execinfra/processorsbase.go:646
*   | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*joinReader).Next
*   |   /home/andrei/src/github.com/cockroachdb/cockroach-2/pkg/sql/rowexec/joinreader.go:540
*   | github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBase).DrainHelper
*   |   /home/andrei/src/github.com/cockroachdb/cockroach-2/pkg/sql/execinfra/processorsbase.go:642
*   | github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Next
*   |   /home/andrei/src/github.com/cockroachdb/cockroach-2/pkg/sql/plan_node_to_row_source.go:183
*   | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Columnarizer).Next
*   |   /home/andrei/src/github.com/cockroachdb/cockroach-2/pkg/sql/colexec/columnarizer.go:199
*   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Next
*   |   /home/andrei/src/github.com/cockroachdb/cockroach-2/pkg/sql/colflow/stats.go:91
*   | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).next
*   |   /home/andrei/src/github.com/cockroachdb/cockroach-2/pkg/sql/colexec/materializer.go:273
*   | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).nextAdapter
*   |   /home/andrei/src/github.com/cockroachdb/cockroach-2/pkg/sql/colexec/materializer.go:298
*   | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
*   |   /home/andrei/src/github.com/cockroachdb/cockroach-2/pkg/sql/colexecerror/error.go:91
*   | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).Next
*   |   /home/andrei/src/github.com/cockroachdb/cockroach-2/pkg/sql/colexec/materializer.go:304
*   | github.com/cockroachdb/cockroach/pkg/sql/execinfra.Run
*   |   /home/andrei/src/github.com/cockroachdb/cockroach-2/pkg/sql/execinfra/base.go:171
*   | github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBase).Run
*   |   /home/andrei/src/github.com/cockroachdb/cockroach-2/pkg/sql/execinfra/processorsbase.go:774
*   | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run
*   |   /home/andrei/src/github.com/cockroachdb/cockroach-2/pkg/sql/flowinfra/flow.go:382
*   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
*   |   /home/andrei/src/github.com/cockroachdb/cockroach-2/pkg/sql/distsql_running.go:359
*   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).planAndRunPostquery
*   |   /home/andrei/src/github.com/cockroachdb/cockroach-2/pkg/sql/distsql_running.go:1156
*   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunCascadesAndChecks
*   |   /home/andrei/src/github.com/cockroachdb/cockroach-2/pkg/sql/distsql_running.go:1096
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
*   |   /home/andrei/src/github.com/cockroachdb/cockroach-2/pkg/sql/conn_executor_exec.go:1050
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
*   |   /home/andrei/src/github.com/cockroachdb/cockroach-2/pkg/sql/conn_executor_exec.go:912
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
*   |   /home/andrei/src/github.com/cockroachdb/cockroach-2/pkg/sql/conn_executor_exec.go:656
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
*   |   /home/andrei/src/github.com/cockroachdb/cockroach-2/pkg/sql/conn_executor_exec.go:120
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
*   |   /home/andrei/src/github.com/cockroachdb/cockroach-2/pkg/sql/conn_executor.go:1514
* Wraps: (4) runtime error: invalid memory address or nil pointer dereference
```

### PR DESCRIPTION
**Pull request by yuzefovich**
**sql: fix EXPLAIN ANALYZE (DEBUG) for queries with LocalPlanNode**

We recently added `EXPLAIN (VEC)` diagrams to the stmt bundle. However,
one edge case was overlooked (namely, a poor interaction between
planNode-to-processor and processor-to-operator adapters). Whenever we
encounter a `planNode` that isn't supported by DistSQL we break away
a part of the planNode tree and introduce two adapters:
1. `planNodeToRowSource` that is a DistSQL processor and is responsible
for draining the DistSQL input to the second adapter
2. `rowSourceToPlanNode` that is a planNode connecting the DistSQL input
to the unsupported planNode tree part.

The crucial observation is that the creation of these two adapters
happens during the physical planning stage whereas the addition of the
DistSQL input to be drained by `planNodeToRowSource` happens during the
flow setup (in `rowexec.NewProcessor`).

Now, `EXPLAIN (VEC)` works by taking in the physical plan, setting up
all of the flows and iterating over the resulting trees. When we added
`(VEC)` and `(VEC, VERBOSE)` flavors of EXPLAIN to the bundle, we added
two more code paths that would fully instantiate the flows, and we would
have 3 instantiations total (the first one is for the actual query
execution). Since `planNodeToRowSource` is created during the physical
planning, it would be modified every time to include the "new" DistSQL
input to be drained. This would lead to a nil pointer exception because
the second and the third "new" inputs are never started.

This commit fixes the issue by explicitly propagating the operator
chains from the flow setup to `saveFlows` function so that we could
avoid instantiation of the whole flow infrastructure for the second and
the third times. This is done only for LocalSyncFlows because all
physical plans containing `LocalPlanNode`s are fully local.

Fixes: #62261.

Release note: None (no stable release with this bug)

**sql: mechanical rename**

This commit renames `leaves` when talking about the vectorized operator
chains to `opChains` since the objects stored in the slice are actually
roots of the chains. It also introduces an alias for
`[]execinfrapb.OpNode`. Additionally, it switches the logic of handling
an error during the vectorized flow setup so that an error is checked
first (a common way to do so).

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
An alternative much less invasive but a lot more hacky fix is [here](https://github.com/yuzefovich/cockroach/commit/694cbe0e52b76133dcde72bd0462d8d48d49e752). I think we should proceed with this PR though and backport the first commit.

**Comment by yuzefovich** [comment]
Another option is reverting #62049 on `release-21.1`.

**Comment by RaduBerinde** [comment]
I am worried there may be other sharp edges.. I think we should revert from 21.1 or put it behind a cluster setting.

**Comment by yuzefovich** [comment]
Ok, I think let's revert the changes on 21.1 branch just to be safe.

**Comment by yuzefovich** [comment]
We reverted the introduction of `EXPLAIN (VEC)` diagrams on 21.1 branch, but not on master, so we still need to fix the issue. I think this PR is relatively clean way to do so. @RaduBerinde PTAL.

**Comment by yuzefovich** [comment]
@RaduBerinde friendly ping

**Review by RaduBerinde — COMMENTED** [review]
Very sorry, this fell through the cracks. Feel free to ping me more frequently in the future :)

:lgtm: 

Would it be possible / not too hard to add a test that reproduces #62261 without this fix?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62399#-:-MZEOA7w9GfRULO3sB1m:bje77dc)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colflow/explain_vec.go, line 92 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62399#-MZEOhoT5SCKxDDm7Dt_:-MZEOhoT5SCKxDDm7Dta:buopz5p) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccd8a506d9eb992257a650cc602c72864bc459f7/pkg/sql/colflow/explain_vec.go#L92)):*
> ```Go
> 	flows map[roachpb.NodeID]*execinfrapb.FlowSpec,
> 	localProcessors []execinfra.LocalProcessor,
> 	roots []execinfra.OpNode,
> ```

[nit] `roots` is pretty generic, maybe `opChainRoots`? Or better, define a `type OpChains []execinfra.OpNode` which explains in its doc that each entry is the root. Then we can just refer to it as `opChains`.
___
*[pkg/sql/colflow/vectorized_flow.go, line 225 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62399#-MZENzXE4W74v8Mtsk-c:-MZENzXE4W74v8Mtsk-d:b6zgoz2) ([raw file](https://github.com/cockroachdb/cockroach/blob/683e428cd6ba3e0fa9b510113a8323bf19774f14/pkg/sql/colflow/vectorized_flow.go#L225)):*
> ```Go
> 		return ctx, leaves, nil
> 	}
> 	// It is (theoretically) possible that some of the memory monitoring
> ```

[nit] we should move the error handling inside an `if err != nil` as usual, instead of the other way around.
___
*[pkg/sql/flowinfra/flow.go, line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62399#-MZENPcK-aR5FszXoqKI:-MZENPcL4kiOvHxbgpNr:b-ltw83q) ([raw file](https://github.com/cockroachdb/cockroach/blob/683e428cd6ba3e0fa9b510113a8323bf19774f14/pkg/sql/flowinfra/flow.go#L74)):*
> ```Go
> 	// The second return argument contains all operator chains planned on the
> 	// gateway node if the flow is vectorized and the physical plan is fully
> 	// local.
> ```

[nit] mention explicitly that in other cases it is empty

**Review by yuzefovich — COMMENTED** [review]
No worries, there were other higher priority items on our plates :)

I did add a regression test originally (in `explain_analyze` logic test), but also just added a regression unit test.

Looks like the CI is red only because of flakes, so I'll go ahead and bors it.

TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62399#-:-MZFyaRy4IuUm3bTmZo0:b6pts1k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

___
*[pkg/sql/colflow/explain_vec.go, line 92 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62399#-MZEOhoT5SCKxDDm7Dt_:-MZG1s-B5v8Z-h_HgNlK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccd8a506d9eb992257a650cc602c72864bc459f7/pkg/sql/colflow/explain_vec.go#L92)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] `roots` is pretty generic, maybe `opChainRoots`? Or better, define a `type OpChains []execinfra.OpNode` which explains in its doc that each entry is the root. Then we can just refer to it as `opChains`.
</blockquote></details>

Done.
___
*[pkg/sql/colflow/vectorized_flow.go, line 225 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62399#-MZENzXE4W74v8Mtsk-c:-MZG1sot6zMUEpObUh20:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/683e428cd6ba3e0fa9b510113a8323bf19774f14/pkg/sql/colflow/vectorized_flow.go#L225)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] we should move the error handling inside an `if err != nil` as usual, instead of the other way around.
</blockquote></details>

Done.

**Pull request merged**
