### PR TITLE
sql/catalog/typedesc: validate OID range before converting it to ID

### LINKED ISSUE #58414: typedesc: consider adding an error to typedesc.UserDefinedTypeOIDToID
**Describe the problem**

We have code to convert an OID to a `descpb.ID` that assumes that the OID is larger than a constant. When it isn't we wrap around and end up producing and bogus descriptor ID. This is bug prone. We should return an error. 

https://github.com/cockroachdb/cockroach/blob/448663cf3d8c2b839c51b9939368165a464f7ffe/pkg/sql/catalog/typedesc/type_desc.go#L148-L150

### PR DESCRIPTION
**Pull request by sajjadrizvi**
Previously the code to convert an OID to a `descpb.ID` assumed that the OID is
larger than a predefined constant. There were no checks to validate the given
OID during conversion. As a result, an out-of-range OID could be
converted to an invalid descriptor ID without an error.

The changes in this PR validate the range of given user-defined OID before
conversion, which encourages the user to check the conversion for
potential problems.

Release note: None

Fixes #58414

### CODE REVIEW

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65352)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @RichardJCai, and @sajjadrizvi)

___
*[pkg/ccl/backupccl/restore_planning.go, line 1045 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-M_w-WDCBAjoAqJ5vOVh:-M_w-WDD1GKOx6DIZDAV:bhyyo50) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbf7940c9c56dad5c29fb603957753928bf64775/pkg/ccl/backupccl/restore_planning.go#L1045)):*
> ```Go
> 		return
> 	}
> 	tid, _ := typedesc.GetTypeDescID(typ)
> ```

Why is it okay to not return an error if it's not valid in this case?
___
*[pkg/ccl/changefeedccl/schemafeed/schema_feed.go, line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-M_w-rgc0Lx3Rh2Gi_kb:-M_w-rgc0Lx3Rh2Gi_kc:b-pqf8u6) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbf7940c9c56dad5c29fb603957753928bf64775/pkg/ccl/changefeedccl/schemafeed/schema_feed.go#L183)):*
> ```Go
> func (t *typeDependencyTracker) purgeTable(tbl catalog.TableDescriptor) {
> 	for _, col := range tbl.UserDefinedTypeColumns() {
> 		// Not validating the type as the columns are supposed to have a valid id
> ```

If it's not valid that would be noteworthy, right? Perhaps it's at least worth logging or perhaps panicing in non-release builds? Adding cdc team for these changes.

**Review by sajjadrizvi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65352)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @pbardea, and @RichardJCai)

___
*[pkg/ccl/backupccl/restore_planning.go, line 1045 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-M_w-WDCBAjoAqJ5vOVh:-M_w7sx-Bi56McDNqs3f:b-12o43y) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbf7940c9c56dad5c29fb603957753928bf64775/pkg/ccl/backupccl/restore_planning.go#L1045)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Why is it okay to not return an error if it's not valid in this case?
</blockquote></details>

I thought the passed types are already validated in this case and they must be within the correct range. As the function does not returns an error, I will log an error message if the ID conversion is not OK.
___
*[pkg/ccl/changefeedccl/schemafeed/schema_feed.go, line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-M_w-rgc0Lx3Rh2Gi_kb:-M_w57RAEIsWEkecoI-K:b-n14qvn) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbf7940c9c56dad5c29fb603957753928bf64775/pkg/ccl/changefeedccl/schemafeed/schema_feed.go#L183)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

If it's not valid that would be noteworthy, right? Perhaps it's at least worth logging or perhaps panicing in non-release builds? Adding cdc team for these changes.
</blockquote></details>

Yeah, right. I should at least log an error.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65352)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @pbardea, and @RichardJCai)

___
*[pkg/ccl/backupccl/restore_planning.go, line 1045 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-M_w-WDCBAjoAqJ5vOVh:-M_w_U4w183ukIkMYwEb:b8858sl) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbf7940c9c56dad5c29fb603957753928bf64775/pkg/ccl/backupccl/restore_planning.go#L1045)):*
<details><summary><i>Previously, sajjadrizvi (Sajjad Rizvi) wrote…</i></summary><blockquote>

I thought the passed types are already validated in this case and they must be within the correct range. As the function does not returns an error, I will log an error message if the ID conversion is not OK.
</blockquote></details>

I'm uncomfortable seeing log fatal calls.  I think validation aside, "things" could happen.
For example, we know what type of data we store in the jobs table, but we still check
and return error if we failed to deserialize proto.  This feels very similar to me.
I think we should return an error.

**Review by fqazi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65352)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @pbardea, @RichardJCai, and @sajjadrizvi)

___
*[pkg/sql/type_change.go, line 820 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-Ma-98S73Fefvvg3IeyA:-Ma-98S73Fefvvg3IeyB:b-n7t635) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3534679267e6ff1d8da1e8a20fad3ab460b9bd3/pkg/sql/type_change.go#L820)):*
> ```Go
> 			}
> 
> 			id, _ := typedesc.GetTypeDescID(col.GetType())
> ```

Should we check if the conversion is okay?
___
*[pkg/sql/type_change.go, line 928 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-Ma-9F4_4_Df5Hu6uYKW:-Ma-9F4_4_Df5Hu6uYKX:bwplfsu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3534679267e6ff1d8da1e8a20fad3ab460b9bd3/pkg/sql/type_change.go#L928)):*
> ```Go
> 		firstClause := true
> 		for _, col := range desc.PublicColumns() {
> 			id, _ := typedesc.GetTypeDescID(col.GetType())
> ```

Similar any danger of not checking?
___
*[pkg/sql/catalog/typedesc/type_desc.go, line 119 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-Ma-AeTJ1vaQgKq09-jd:-Ma-AeTKDAEzoNFNZZUh:b-ywme5p) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3534679267e6ff1d8da1e8a20fad3ab460b9bd3/pkg/sql/catalog/typedesc/type_desc.go#L119)):*
> ```Go
> // descriptor ID. OID of a user-defined type must be greater than
> // CockraochPredefinedOIDMax.
> func MaybeUserDefinedTypeOIDToID(oid oid.Oid) (descpb.ID, bool) {
> ```

Minor: You don't have to do this, but would it be cleaner to just have a function that returns an error on failure to convert? Disregard, if that was something you discussed/considered.

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65352)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @pbardea, @RichardJCai, and @sajjadrizvi)

___
*[pkg/ccl/changefeedccl/schemafeed/schema_feed.go, line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-M_w-rgc0Lx3Rh2Gi_kb:-Ma2zi9sCC1hhOjwzifx:b5jce6z) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbf7940c9c56dad5c29fb603957753928bf64775/pkg/ccl/changefeedccl/schemafeed/schema_feed.go#L183)):*
<details><summary><i>Previously, sajjadrizvi (Sajjad Rizvi) wrote…</i></summary><blockquote>

Yeah, right. I should at least log an error.
</blockquote></details>

The only caller of this function is from a function that returns an error and has its own context.  Given that, I'd prefer that we return the error up the callstack both here and at the callsite in validateDescriptor and then log at the Error level rather than Fatal. An error from validateDescriptor will result in a failed changefeed job AFAIK and we'd like to limit the number of places where changefeeds can bring down the database. 

If this is the kind of error where we really don't want to continue once we've seen it, even inside changefeeds, perhaps a more descriptive error would be useful so that we know what table and column this happened on?

**Review by sajjadrizvi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65352)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @fqazi, @pbardea, and @RichardJCai)

___
*[pkg/ccl/backupccl/restore_planning.go, line 1045 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-M_w-WDCBAjoAqJ5vOVh:-Ma3oeVl-fKWpexc3qeI:bx8mi92) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbf7940c9c56dad5c29fb603957753928bf64775/pkg/ccl/backupccl/restore_planning.go#L1045)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I'm uncomfortable seeing log fatal calls.  I think validation aside, "things" could happen.
For example, we know what type of data we store in the jobs table, but we still check
and return error if we failed to deserialize proto.  This feels very similar to me.
I think we should return an error. 
</blockquote></details>

OK. I am modifying the code to return an error. It makes more sense to return an error.

I will avoid log fatal calls.
___
*[pkg/ccl/changefeedccl/schemafeed/schema_feed.go, line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-M_w-rgc0Lx3Rh2Gi_kb:-Ma3xv3w73jBf6eX8TuK:b-vxclio) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbf7940c9c56dad5c29fb603957753928bf64775/pkg/ccl/changefeedccl/schemafeed/schema_feed.go#L183)):*
> and then log at the Error level rather than Fatal.
Do you mean to log an error in the caller of validateDescriptor() instead of returning the error further up the callstack? The current caller of validateDescriptor(), which is ingestDescriptors(), eventually returns the error further up in the stack.

> perhaps a more descriptive error would be useful ...
Thanks, I will keep that in mind.
___
*[pkg/sql/type_change.go, line 820 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-Ma-98S73Fefvvg3IeyA:-Ma3pSolEVsQ_zYzDvle:b-dnnr1f) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3534679267e6ff1d8da1e8a20fad3ab460b9bd3/pkg/sql/type_change.go#L820)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Should we check if the conversion is okay?
</blockquote></details>

Yes, thanks for pointing out. I have modified it to check and return an error if the conversion fails.
___
*[pkg/sql/type_change.go, line 928 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-Ma-9F4_4_Df5Hu6uYKW:-Ma3pp_J9aXzwEM6tSxc:b-7an960) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3534679267e6ff1d8da1e8a20fad3ab460b9bd3/pkg/sql/type_change.go#L928)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Similar any danger of not checking?
</blockquote></details>

Yeah, fixed that as well. Thanks.
___
*[pkg/sql/catalog/typedesc/type_desc.go, line 119 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-Ma-AeTJ1vaQgKq09-jd:-Ma3pyqW4IAz_0CdBuVU:b1banaw) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3534679267e6ff1d8da1e8a20fad3ab460b9bd3/pkg/sql/catalog/typedesc/type_desc.go#L119)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Minor: You don't have to do this, but would it be cleaner to just have a function that returns an error on failure to convert? Disregard, if that was something you discussed/considered.
</blockquote></details>

I think it is cleaner to just return an error whenever we return false, we create an error message in the caller function and return an error. Essentially, we are just returning an error whenever conversion fails. I was planning to do it.

**Comment by sajjadrizvi** [comment]
This is a work-in-progress (WIP), not ready for the thorough review yet.

**Comment by sajjadrizvi** [comment]
This commit is now ready for another review (RFAR).

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65352)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @fqazi, @pbardea, @RichardJCai, and @sajjadrizvi)

___
*[pkg/ccl/backupccl/restore_planning.go, line 123 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-MaE6bNi5M2MjeMxTneD:-MaE6bNi5M2MjeMxTneE:bxt1a77) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f9cacfcb681323febc90c610ead5cc4487bef04/pkg/ccl/backupccl/restore_planning.go#L123)):*
> ```Go
> 	ctx.SetIndexedTypeFormat(func(ctx *tree.FmtCtx, ref *tree.OIDTypeReference) {
> 		newRef := ref
> 		id, err := typedesc.UserDefinedTypeOIDToID(ref.OID)
> ```

I don't think this will set the right `err`. This should define a new `err` scoped to this inner func and won't set the `err` that this function closes over. To do this, I think we need something like:
```
var id descpb.ID
id, err = typedesc.UserDefinedTypeOIDToID(ref.OID)
```

**Review by sajjadrizvi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65352)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @fqazi, @pbardea, and @RichardJCai)

___
*[pkg/ccl/backupccl/restore_planning.go, line 123 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-MaE6bNi5M2MjeMxTneD:-MaEJZk9DnZKtn-9UQR8:br45eiw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f9cacfcb681323febc90c610ead5cc4487bef04/pkg/ccl/backupccl/restore_planning.go#L123)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

I don't think this will set the right `err`. This should define a new `err` scoped to this inner func and won't set the `err` that this function closes over. To do this, I think we need something like:
```
var id descpb.ID
id, err = typedesc.UserDefinedTypeOIDToID(ref.OID)
```
</blockquote></details>

Good catch! I have now fixed it.

**Review by pbardea — APPROVED** [review]
Bulk IO changes LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-:-MaEZzrA5hbicz-batwv:b-oc1hz2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @fqazi, @pbardea, and @RichardJCai)

**Review by RichardJCai — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65352)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @fqazi, @pbardea, and @sajjadrizvi)

___
*[pkg/sql/type_change.go, line 663 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-MaEcJyzDEC0ayI-YDQ0:-MaEcJyzDEC0ayI-YDQ1:b40zbdw) ([raw file](https://github.com/cockroachdb/cockroach/blob/93362929db1371fec81332ce7196fde16ab477dd/pkg/sql/type_change.go#L663)):*
> ```Go
> 			id, err := typedesc.UserDefinedTypeOIDToID(typeOid.OID)
> 			if err != nil || id != typeID {
> 				return true, expr, nil
> ```

We should return the err if it's not nil
___
*[pkg/sql/type_change.go, line 687 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-MaEcOFX9p2qZvmTzDtR:-MaEcOFX9p2qZvmTzDtS:b-89a4l7) ([raw file](https://github.com/cockroachdb/cockroach/blob/93362929db1371fec81332ce7196fde16ab477dd/pkg/sql/type_change.go#L687)):*
> ```Go
> 			id = id - 1
> 			if err != nil || id != typeID {
> 				return true, expr, nil
> ```

Ditto
___
*[pkg/sql/type_change.go, line 732 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-MaEcQNf6irfy0A03IjS:-MaEcQNg8RyZRVy6VXaa:b-89a4l7) ([raw file](https://github.com/cockroachdb/cockroach/blob/93362929db1371fec81332ce7196fde16ab477dd/pkg/sql/type_change.go#L732)):*
> ```Go
> 		id, err := typedesc.UserDefinedTypeOIDToID(typeOid.OID)
> 		if err != nil || id != typeID {
> 			return true, expr, nil
> ```

Ditto
___
*[pkg/sql/catalog/tabledesc/validate.go, line 94 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-MaEf8Pr6BkO1vnekEj6:-MaEf8Pr6BkO1vnekEj7:b-z5yxrm) ([raw file](https://github.com/cockroachdb/cockroach/blob/93362929db1371fec81332ce7196fde16ab477dd/pkg/sql/catalog/tabledesc/validate.go#L94)):*
> ```Go
> 		id, err := typedesc.UserDefinedTypeOIDToID(oid)
> 		if err != nil {
> 			panic(err)
> ```

I think we should change this function to error as well instead of panicking, it looks like this is called by Validate 

Don't think we wanna panic while validating.

```// Validate returns a ValidationErrors interface which can provide the errors
// either as a slice or combined as one.```
```

___
*[pkg/sql/catalog/typedesc/type_desc.go, line 953 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-MaEcq8-BeiHV745zv79:-MaEcq8-BeiHV745zv7A:b1detml) ([raw file](https://github.com/cockroachdb/cockroach/blob/93362929db1371fec81332ce7196fde16ab477dd/pkg/sql/catalog/typedesc/type_desc.go#L953)):*
> ```Go
> 	id, err := GetUserDefinedTypeDescID(typ)
> 	if err != nil {
> 		panic(err)
> ```

I prefer returning an error here instead of panicking even if the only caller of this function will panic if theres an error.

If we add any more callers, they may not want a function it's calling to panic.

**Review by ajwerner — COMMENTED** [review]
This is getting very close. 

> Reviewed 1 of 14 files at r3, 2 of 8 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-:-MaiNeXJ7fxT8MM-BJKA:b-a4s0p7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @fqazi, @pbardea, and @sajjadrizvi)

___
*[pkg/sql/catalog/typedesc/type_desc_test.go, line 810 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-MaiMSpj7iOnsR3RqXfZ:-MaiMSpj7iOnsR3RqXf_:b-4a3ci9) ([raw file](https://github.com/cockroachdb/cockroach/blob/db3231e2098af01a40bd0de42c844a91b7594291/pkg/sql/catalog/typedesc/type_desc_test.go#L810)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> 
> 			t.Fatalf("%s test: expected error, but succeeded", test.name)
> 		} else if test.ok && err != nil {
> 			t.Fatalf("%s test: expected success, but got error: %s", test.name, err.Error())
> 		}
> ```
</details>

this is totally fine, however, I want to make sure you're aware of `require` 

I would write this:

```go
for _, test := range tests {
    t.Run(fmt.Sprint(test.oid), func(t *testing.T) {
        _, err := typedesc.UserDefinedTypeOIDToID(test.oid)
        if test.ok {
            require.NoError(t, err)
        } else {
            require.Regexp(t, "user-defined oid \d+.*", err) // could make a clearer regexp
        }
    })
}
```

It's the same size but it carries the metadata in a more structured way and generally for a lot of use cases can be a good bit more terse. `require` will fatal and its sister `assert` will just error. 
___
*[pkg/sql/opt/optbuilder/builder.go, line 429 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-MaiAwRC5b9XePSI8iHB:-MaiAwRC5b9XePSI8iHC:b-f0j8bm) ([raw file](https://github.com/cockroachdb/cockroach/blob/db3231e2098af01a40bd0de42c844a91b7594291/pkg/sql/opt/optbuilder/builder.go#L429)):*
> ```Go
> }
> 
> func (b *Builder) maybeTrackUserDefinedTypeDepsForViews(texpr tree.TypedExpr) error {
> ```

A caller to this needs to use this error, however, in this file, we panic errors because the builder always catches them. So, tl;dr, panic this error with confidence that it'll be caught.
___
*[pkg/sql/sem/tree/casts.go, line 1307 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-MaeHKKTEKAYt3yoHrsr:-MaeHKKTEKAYt3yoHrss:b-4i00hy) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d8d08e8e6ea27defc23061966aa3369eebce1ee/pkg/sql/sem/tree/casts.go#L1307)):*
> ```Go
> 		} else if typ, err := ctx.Planner.ResolveTypeByOID(ctx.Context, oid.Oid(v)); err == nil {
> 			ret.name = typ.PGName()
> 		} // It seems that the error above is not checked and returned intentionally.
> ```

How about:
```go
		} else if typedesc.IsOIDUserDefinedType(oid.Oid(v)) {
			typ, err := ctx.Planner.ResolveTypeByOID(ctx.Context, oid.Oid(v))
                        if err != nil {
                            return nil, err
                        }
                        ret.name = typ.PGName()
		}
```

**Review by ajwerner — APPROVED** [review]
:lgtm: mod the one nit and removing `WIP` from the title 

> Reviewed 1 of 8 files at r2, 3 of 14 files at r3, 2 of 6 files at r5, 2 of 8 files at r6, 4 of 6 files at r7, 1 of 3 files at r8, 4 of 4 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-:-Maiqn1w7TsgT0-O06Xg:b-try3gq)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @fqazi, @pbardea, and @sajjadrizvi)

___
*[pkg/sql/catalog/typedesc/type_desc.go, line 118 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-MaiqZRVEqzuBEYi2iTa:-MaiqZRVEqzuBEYi2iTb:b-ysbxn1) ([raw file](https://github.com/cockroachdb/cockroach/blob/840479318a679fe455e3b433fa0f952f8a1af185/pkg/sql/catalog/typedesc/type_desc.go#L118)):*
> ```Go
> // UserDefinedTypeOIDToID converts a user defined type OID into a
> // descriptor ID. OID of a user-defined type must be greater than
> // CockroachPredefinedOIDMax. The function throws an error if the
> ```

nit: returns rather than throws

**Review by sajjadrizvi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65352)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @fqazi, @pbardea, and @RichardJCai)

___
*[pkg/ccl/changefeedccl/schemafeed/schema_feed.go, line 183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-M_w-rgc0Lx3Rh2Gi_kb:-MaQtxX3Cm1cIXdSvPce:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbf7940c9c56dad5c29fb603957753928bf64775/pkg/ccl/changefeedccl/schemafeed/schema_feed.go#L183)):*
<details><summary><i>Previously, sajjadrizvi (Sajjad Rizvi) wrote…</i></summary><blockquote>

> and then log at the Error level rather than Fatal.
Do you mean to log an error in the caller of validateDescriptor() instead of returning the error further up the callstack? The current caller of validateDescriptor(), which is ingestDescriptors(), eventually returns the error further up in the stack.

> perhaps a more descriptive error would be useful ...
Thanks, I will keep that in mind.
</blockquote></details>

Done.
___
*[pkg/sql/type_change.go, line 820 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-Ma-98S73Fefvvg3IeyA:-MaQtzE6EprtmLAFOQ6c:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3534679267e6ff1d8da1e8a20fad3ab460b9bd3/pkg/sql/type_change.go#L820)):*
<details><summary><i>Previously, sajjadrizvi (Sajjad Rizvi) wrote…</i></summary><blockquote>

Yes, thanks for pointing out. I have modified it to check and return an error if the conversion fails.
</blockquote></details>

Done.
___
*[pkg/sql/type_change.go, line 928 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-Ma-9F4_4_Df5Hu6uYKW:-MaQtzik2U7picaLcHYH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3534679267e6ff1d8da1e8a20fad3ab460b9bd3/pkg/sql/type_change.go#L928)):*
<details><summary><i>Previously, sajjadrizvi (Sajjad Rizvi) wrote…</i></summary><blockquote>

Yeah, fixed that as well. Thanks.
</blockquote></details>

Done.
___
*[pkg/sql/type_change.go, line 663 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-MaEcJyzDEC0ayI-YDQ0:-MaQu1EQCyyN24oFv8fd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/93362929db1371fec81332ce7196fde16ab477dd/pkg/sql/type_change.go#L663)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

We should return the err if it's not nil
</blockquote></details>

Done.
___
*[pkg/sql/type_change.go, line 687 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-MaEcOFX9p2qZvmTzDtR:-MaQu1Yg9ao_yAcR0DnV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/93362929db1371fec81332ce7196fde16ab477dd/pkg/sql/type_change.go#L687)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[pkg/sql/type_change.go, line 732 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-MaEcQNf6irfy0A03IjS:-MaQu1pV9NtJenaYxxHJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/93362929db1371fec81332ce7196fde16ab477dd/pkg/sql/type_change.go#L732)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[pkg/sql/catalog/tabledesc/validate.go, line 94 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-MaEf8Pr6BkO1vnekEj6:-MaiD0ZCCLvTLpd-1yfL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/93362929db1371fec81332ce7196fde16ab477dd/pkg/sql/catalog/tabledesc/validate.go#L94)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I think we should change this function to error as well instead of panicking, it looks like this is called by Validate 

Don't think we wanna panic while validating.

```// Validate returns a ValidationErrors interface which can provide the errors
// either as a slice or combined as one.```
</blockquote></details>

Done.
___
*[pkg/sql/catalog/typedesc/type_desc.go, line 953 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-MaEcq8-BeiHV745zv79:-MaiD321CEM-_grtZRro:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/93362929db1371fec81332ce7196fde16ab477dd/pkg/sql/catalog/typedesc/type_desc.go#L953)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I prefer returning an error here instead of panicking even if the only caller of this function will panic if theres an error.

If we add any more callers, they may not want a function it's calling to panic.
</blockquote></details>

Done.
___
*[pkg/sql/catalog/typedesc/type_desc_test.go, line 810 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-MaiMSpj7iOnsR3RqXfZ:-MaivZy91D0B1zui39e6:br1bocw) ([raw file](https://github.com/cockroachdb/cockroach/blob/db3231e2098af01a40bd0de42c844a91b7594291/pkg/sql/catalog/typedesc/type_desc_test.go#L810)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 
> 			t.Fatalf("%s test: expected error, but succeeded", test.name)
> 		} else if test.ok && err != nil {
> 			t.Fatalf("%s test: expected success, but got error: %s", test.name, err.Error())
> 		}
> ```
this is totally fine, however, I want to make sure you're aware of `require` 

I would write this:

```go
for _, test := range tests {
    t.Run(fmt.Sprint(test.oid), func(t *testing.T) {
        _, err := typedesc.UserDefinedTypeOIDToID(test.oid)
        if test.ok {
            require.NoError(t, err)
        } else {
            require.Regexp(t, "user-defined oid \d+.*", err) // could make a clearer regexp
        }
    })
}
```

It's the same size but it carries the metadata in a more structured way and generally for a lot of use cases can be a good bit more terse. `require` will fatal and its sister `assert` will just error. 
</blockquote></details>

Done. Thanks for the pointer to the require package.
___
*[pkg/sql/opt/optbuilder/builder.go, line 429 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-MaiAwRC5b9XePSI8iHB:-MaiRxI88Szz1baReQq6:bkv88k2) ([raw file](https://github.com/cockroachdb/cockroach/blob/db3231e2098af01a40bd0de42c844a91b7594291/pkg/sql/opt/optbuilder/builder.go#L429)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

A caller to this needs to use this error, however, in this file, we panic errors because the builder always catches them. So, tl;dr, panic this error with confidence that it'll be caught.
</blockquote></details>

I called panic in the parent function. I have now changed it.
___
*[pkg/sql/sem/tree/casts.go, line 1307 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-MaeHKKTEKAYt3yoHrsr:-MaiUI_o-_9QCk9uJKMS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d8d08e8e6ea27defc23061966aa3369eebce1ee/pkg/sql/sem/tree/casts.go#L1307)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

How about:
```go
		} else if typedesc.IsOIDUserDefinedType(oid.Oid(v)) {
			typ, err := ctx.Planner.ResolveTypeByOID(ctx.Context, oid.Oid(v))
                        if err != nil {
                            return nil, err
                        }
                        ret.name = typ.PGName()
		}
```
</blockquote></details>

Done.

**Review by ajwerner — APPROVED** [review]
:lgtm: 

Super nit, don't to change anything, in the future I think the header I'd use is `sql/catalog/typedesc`. Commas are when the bulk of the change impacts multiple packages. 

Give it a `bors` when CI passes. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65352#-:-Maj1pLD6Jst34zrcwTy:b1jl57k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @fqazi, @pbardea, and @RichardJCai)

**Pull request merged**
