### PR TITLE
go.mod: bump Pebble to de41143371aa

### PR DESCRIPTION
**Pull request by RaduBerinde**
Changes:

 * [`de411433`](https://github.com/cockroachdb/pebble/commit/de411433) tool: fix up `wal dump`, add `wal dump-merged`
 * [`9b79e826`](https://github.com/cockroachdb/pebble/commit/9b79e826) vfs: make Unwrap part of FS, fix metamorphic restart op
 * [`f8a32c98`](https://github.com/cockroachdb/pebble/commit/f8a32c98) vfs: convert MemFS tests to datadriven
 * [`3d1f61aa`](https://github.com/cockroachdb/pebble/commit/3d1f61aa) sstable: convert RawWriter into an interface
 * [`583859f8`](https://github.com/cockroachdb/pebble/commit/583859f8) colblk: add index block writer, reader, iterator
 * [`de9087ca`](https://github.com/cockroachdb/pebble/commit/de9087ca) sstable: genericize iterators over index block iterator type
 * [`1b4021bc`](https://github.com/cockroachdb/pebble/commit/1b4021bc) colblk: store shared and bundle prefix length
 * [`99abcf76`](https://github.com/cockroachdb/pebble/commit/99abcf76) colblk: add UnsafeOffsets.At2 and improve UnsafeUints.At
 * [`55fcc6e9`](https://github.com/cockroachdb/pebble/commit/55fcc6e9) colblk: special case zero bitmaps
 * [`8ec212a4`](https://github.com/cockroachdb/pebble/commit/8ec212a4) colblk: use regular slice in PrefixBytesIter
 * [`94561af6`](https://github.com/cockroachdb/pebble/commit/94561af6) colblk: add some minor comments
 * [`d4348d08`](https://github.com/cockroachdb/pebble/commit/d4348d08) lint: remove golint
 * [`aa96305a`](https://github.com/cockroachdb/pebble/commit/aa96305a) sstable: fix nil pointer in twoLevelIterator.NextPrefix
 * [`9f97b7bf`](https://github.com/cockroachdb/pebble/commit/9f97b7bf) sstable: fix TestBlockProperties[BoundLimited] to use testkeys.Comparer
 * [`de53a981`](https://github.com/cockroachdb/pebble/commit/de53a981) rowblk: add IndexIter type
 * [`aa32f0b0`](https://github.com/cockroachdb/pebble/commit/aa32f0b0) db: fix WAL offset in replayWAL errors

Release note: none.
Epic: none.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
I had to change the two `RawWriter.Add` calls to `AddWithForceObsolete`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129644#-:-O5EIQ3i1kfon1QGt0zp:bwtc8ny)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @jbowens)

**Review by jbowens — APPROVED** [review]
lgtm

**Comment by RaduBerinde** [comment]
TFTR!

bors r+

**Comment by RaduBerinde** [comment]
> ERROR: The Build Event Protocol local file upload failed: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception

bors r+

**Pull request merged**
