### PR TITLE
tracing/collector: make cluster_inflight_traces work with tenants 

### PR DESCRIPTION
**Pull request by andreimatei**
Prior to this patch, crdb_internal.cluster_inflight_traces could not be
queried in a tenant. This patch makes it work by abstracting the trace
trace collector's dependency on node liveness for enumerating node IDs
and using instance IDs for tenants.

The patch also adds a test that queries this table; there didn't appear
to be any.

Release note: None
Epic: https://cockroachlabs.atlassian.net/browse/CRDB-14524

### CODE REVIEW

**Review by knz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92706#-:-NI831L6-ldY6c4lV9rd:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[`pkg/server/server_sql.go` line 810 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/92706#-NI82_haAlVFFQzrXcNq:-NI82_haAlVFFQzrXcNr:b-jk894r) ([raw file](https://github.com/cockroachdb/cockroach/blob/77c0e4ea02c6e8e0f130847da18909a7e3f70420/pkg/server/server_sql.go#L810)):*
> ```Go
> 	var getNodes func(ctx context.Context) ([]roachpb.NodeID, error)
> 	var nodeDialer *nodedialer.Dialer
> 	if !isSQLPod {
> ```

Can you file a followup issue "merge these two code paths together"
Then add a link to it here.
And assign the issue to label T-multitenant

thanks

**Review by abarganier — APPROVED** [review]
:lgtm:, nice work.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92706#-:-NI8MI7_0dZYd8v_Oiic:bgqev0f)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[`pkg/util/tracing/collector/collector_test.go` line 249 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/92706#-NI8M4eTBcm_uBOrHUje:-NI8M4eTBcm_uBOrHUjf:btrc1pl) ([raw file](https://github.com/cockroachdb/cockroach/blob/77c0e4ea02c6e8e0f130847da18909a7e3f70420/pkg/util/tracing/collector/collector_test.go#L249)):*
> ```Go
> 		}
> 
> 		localTraceID, _, cleanup := setupTraces(t0, t1)
> ```

nit: in the `tenant` case, should we setup traces for both the system and secondary tenant so we can assert that spans from one don't leak to the other? 



_Code quote:_
```Go
		localTraceID, _, cleanup := setupTraces(t0, t1)
```

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92706)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @abarganier and @knz)

___
*[`pkg/server/server_sql.go` line 810 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/92706#-NI82_haAlVFFQzrXcNq:-NI8blVNDPFk6quZCvBK:blshk81) ([raw file](https://github.com/cockroachdb/cockroach/blob/77c0e4ea02c6e8e0f130847da18909a7e3f70420/pkg/server/server_sql.go#L810)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Can you file a followup issue "merge these two code paths together"
Then add a link to it here.
And assign the issue to label T-multitenant

thanks
</blockquote></details>

I wouldn't know what to write in such an issue. As far as this code specifically is concerned, I think it's unified enough - or rather, for serverless, presumably at some level we'll always need to configure a different way of "listing all the nodes" than in other clusters. But this is all generally related to other stuff we've been discussing recently - like who gets an instance ID, for which we have different issues.
But if you know how to phrase an issue...
___
*[`pkg/util/tracing/collector/collector_test.go` line 249 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/92706#-NI8M4eTBcm_uBOrHUje:-NIItuVp0W8SasyJKXCM:bz66jas) ([raw file](https://github.com/cockroachdb/cockroach/blob/77c0e4ea02c6e8e0f130847da18909a7e3f70420/pkg/util/tracing/collector/collector_test.go#L249)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: in the `tenant` case, should we setup traces for both the system and secondary tenant so we can assert that spans from one don't leak to the other? 
</blockquote></details>

did something

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92706#-:-NIJR0qn3iOaeCV3epVw:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @abarganier and @knz)

**Pull request merged**
