### PR TITLE
cluster-ui: add tooltips to explain plan

### LINKED ISSUE #61764: sql/ui: add tooltips to explain plans in db console
@RaduBerinde outlined a proposal today to help others better understand EXPLAIN. EXPLAIN plans contain a lot of information. It can confusing to consume them directly. It would be great if we could provide tooltips in the DB Console for the various parts of explain and also in the SQL Shell (via verbose mode?). 

cc @Annebirzin

### PR DESCRIPTION
**Pull request by xinhaoz**
Resolves: #61764

This commit adds tooltips to explain plan operators and node
attributes, providing more information to explain plans.

Release justification: low-risk, high benefit changes to existing
functionality

Release note (ui change): On the explain plan tab in statement
details, Users will be able to hover over underlined explain
plan attributes to get tooltips with more information on the
attribute.

-----------------------------------------------------------------------
image

image

### CODE REVIEW

**Review by matthewtodd — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70568)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @matthewtodd and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planTooltips.tsx, line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70568#-MkD22pXDpmmMUgRBtGL:-MkD22pY8GZaG8NsmUxO:b-rfozna) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bffa55050298b3e07c96a9395f1204a9497e764/pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planTooltips.tsx#L17)):*
> ```XML
> } from "src/util/docs";
> 
> export type TooltipMap = Record<string, JSX.Element>;
> ```

Just curious, would it be helpful to make a type for these string keys?
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planTooltips.tsx, line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70568#-MkD2WdH9gkL4odbblFx:-MkD2WdIA64MozaPENod:b6t0xgy) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bffa55050298b3e07c96a9395f1204a9497e764/pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planTooltips.tsx#L17)):*
> ```XML
> } from "src/util/docs";
> 
> export type TooltipMap = Record<string, JSX.Element>;
> ```

And it looks like TooltipMap doesn't need to be exported, yes?
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx, line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70568#-MkD42QTBzznvLOIGgr5:-MkD42QTBzznvLOIGgr6:baydwcq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bffa55050298b3e07c96a9395f1204a9497e764/pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx#L148)):*
> ```XML
> 
> // standardizeKey converts str to camel case, removing labels like (anti).
> export function standardizeKey(str: string): string {
> ```

I see we already depend on [two](https://www.npmjs.com/package/camelcase) [separate](https://www.npmjs.com/package/camel-case) packages that do something like this, but I also see that we have extra behavior here, handling commas and removing `(anti)`. So I think you're right that, on balance, this separate function is warranted, especially since it's simple and well-tested below.
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx, line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70568#-MkD58d21fum-C3CDJiM:-MkD58d21fum-C3CDJiN:b-gkzavy) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bffa55050298b3e07c96a9395f1204a9497e764/pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx#L179)):*
> ```XML
> 
>   const tooltipContent = getAttributeTooltip(standardizeKey(attribute.key));
>   const attributeValTooltip = getAttributeValueTooltip(standardizeKey(values));
> ```

Just curious, is there ever a case where we want to put tooltips on each of the values separately?
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx, line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70568#-MkD5RnJE99asitWBa0s:-MkD5RnJE99asitWBa0t:b-ryigcb) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bffa55050298b3e07c96a9395f1204a9497e764/pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx#L179)):*
> ```XML
> 
>   const tooltipContent = getAttributeTooltip(standardizeKey(attribute.key));
>   const attributeValTooltip = getAttributeValueTooltip(standardizeKey(values));
> ```

Also, it looks like this would pass something like `"[one, two]"` into `standardizeKey`, producing `"[oneTwo]"`, with the square brackets. Maybe save the square bracket formatting for later?

**Review by xinhaoz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70568)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @matthewtodd and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planTooltips.tsx, line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70568#-MkD2WdH9gkL4odbblFx:-MkDACgM0vHXpQ5eY97r:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bffa55050298b3e07c96a9395f1204a9497e764/pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planTooltips.tsx#L17)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

And it looks like TooltipMap doesn't need to be exported, yes?
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx, line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70568#-MkD58d21fum-C3CDJiM:-MkDASeaAmaJnBy4ntIQ:bg8jcee) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bffa55050298b3e07c96a9395f1204a9497e764/pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx#L179)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Just curious, is there ever a case where we want to put tooltips on each of the values separately?
</blockquote></details>

Currently there is no case that I know of.
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx, line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70568#-MkD5RnJE99asitWBa0s:-MkDB1vL9pm3N_3-1sAm:bm8123y) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bffa55050298b3e07c96a9395f1204a9497e764/pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx#L179)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Also, it looks like this would pass something like `"[one, two]"` into `standardizeKey`, producing `"[oneTwo]"`, with the square brackets. Maybe save the square bracket formatting for later?
</blockquote></details>

Oh nice catch, didn't even realize the formatting of the values was adding the square brackets. Fixed!

**Comment by xinhaoz** [comment]
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planTooltips.tsx, line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70568#-MkD22pXDpmmMUgRBtGL:-MkDCGGy5wMrBEbHHr5W:b-ffi8l4) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bffa55050298b3e07c96a9395f1204a9497e764/pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planTooltips.tsx#L17)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Just curious, would it be helpful to make a type for these string keys?
</blockquote></details>

Hm, I'm not sure what value it would add in this specific case, since currently no matching key just means there is no tooltip for the value. Might be missing something though, please let me know!

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70568)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @matthewtodd, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx, line 152 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70568#-MkD8yVMAXri9tKSp7ai:-MkD8yVN0bAjmspEokHj:b-uv42ij) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bffa55050298b3e07c96a9395f1204a9497e764/pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx#L152)):*
> ```XML
>     .toLowerCase()
>     .split(/[ ,-]+/)
>     .filter(str => str !== "(anti)")
> ```

Is this special handling here trying to normalize `(anti) join` to just `join? 
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx, line 185 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70568#-MkDApJJDxUx7KuOHU9R:-MkDApJJDxUx7KuOHU9S:b72qa2u) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bffa55050298b3e07c96a9395f1204a9497e764/pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx#L185)):*
> ```XML
>       <span
>         className={cx(
>           "nodeAttributeKey",
> ```

hmm we are mixing camel case cx name here vs `*-*` names later for `node-attribute`, perhaps we can just pick one here?
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.spec.tsx, line 260 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70568#-MkDCl0u4vyz8TKIjS9y:-MkDCl0u4vyz8TKIjS9z:b-vnr996) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bffa55050298b3e07c96a9395f1204a9497e764/pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.spec.tsx#L260)):*
> ```XML
> 
>     it("should remove '(anti)' from the key", () => {
>       assert.equal(standardizeKey("lookup join (anti)"), "lookupJoin");
> ```

hmmm is `anti join` the only case where we would have special case like this?

**Review by matthewtodd — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70568)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @matthewtodd, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx, line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70568#-MkD58d21fum-C3CDJiM:-MkDDBuC8xQcIo4mP9GO:bpdb324) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bffa55050298b3e07c96a9395f1204a9497e764/pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx#L179)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Currently there is no case that I know of.
</blockquote></details>

Still thinking here, I wonder if it could make sense to do something like

```
const attributeValTooltip = 
  attribute.values.length > 1
    ? null
    : getAttributeValueTooltip(attribute.values[0]);
```
 
Then you could take the comma handling out of `standardizeKey` and maybe collapse this `if` with the square-bracket-formatting one for `values`?

I don't know, I think I'm looking to make the data flow here easier for me to reason about. WDYT?

**Review by xinhaoz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70568)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @matthewtodd, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx, line 152 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70568#-MkD8yVMAXri9tKSp7ai:-MkDEjkL1_z9Pe3WEdUB:bp8eu3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bffa55050298b3e07c96a9395f1204a9497e764/pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx#L152)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Is this special handling here trying to normalize `(anti) join` to just `join? 
</blockquote></details>

Yes, that's correct.
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx, line 185 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70568#-MkDApJJDxUx7KuOHU9R:-MkDEJ0X7sa2kaEClPvg:b-uhhi46) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bffa55050298b3e07c96a9395f1204a9497e764/pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx#L185)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

hmm we are mixing camel case cx name here vs `*-*` names later for `node-attribute`, perhaps we can just pick one here?
</blockquote></details>

I'd prefer not to use camel case for CSS class names since css class names aren't case sensitive afaik, but it seems like past class names are in camel case. Perhaps a quick win to turn it into snake case? Not sure if you'd rather I just address the ones in this file here in this ticket.
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.spec.tsx, line 260 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70568#-MkDCl0u4vyz8TKIjS9y:-MkDE6AY-6mVubETCH0n:b2abwn) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bffa55050298b3e07c96a9395f1204a9497e764/pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.spec.tsx#L260)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

hmmm is `anti join` the only case where we would have special case like this? 
</blockquote></details>

I believe for now the only cases I observed were from the join operators.

**Comment by xinhaoz** [comment]
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx, line 179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70568#-MkD58d21fum-C3CDJiM:-MkDia_NAA-wIpj1ubqq:bjzmk4w) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bffa55050298b3e07c96a9395f1204a9497e764/pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx#L179)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Still thinking here, I wonder if it could make sense to do something like

```
const attributeValTooltip = 
  attribute.values.length > 1
    ? null
    : getAttributeValueTooltip(attribute.values[0]);
```
 
Then you could take the comma handling out of `standardizeKey` and maybe collapse this `if` with the square-bracket-formatting one for `values`?

I don't know, I think I'm looking to make the data flow here easier for me to reason about. WDYT?
</blockquote></details>

Oh true, I highly doubt we'd need tooltips for any comma separated values, so sounds good to me! Updated.

**Review by matthewtodd — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70568)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Annebirzin, @Azhng, @kevin-v-ngo, @matthewtodd, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx, line 183 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70568#-MkDk7q9Av1Nhda9wvlj:-MkDk7q9Av1Nhda9wvlk:brsavwy) ([raw file](https://github.com/cockroachdb/cockroach/blob/e716b26f879be1b0e6ca3a09fa23eaee68578740/pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx#L183)):*
> ```XML
>     attribute.values.length > 1
>       ? null
>       : getAttributeValueTooltip(attribute.values[0]);
> ```

Oops, in my example code, I missed the `standardizeKey` call we still need here, right?

**Review by matthewtodd — APPROVED** [review]
Nice work! :lgtm: pending resolution on @azhng's questions.

> Reviewed 2 of 5 files at r1, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70568#-:-MkDldrWDnsT8pUXtpi3:bqd5l3l)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Annebirzin, @Azhng, @kevin-v-ngo, and @xinhaoz)

**Review by xinhaoz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70568)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Annebirzin, @Azhng, @kevin-v-ngo, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx, line 183 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/70568#-MkDk7q9Av1Nhda9wvlj:-MkDodG76aGGGwt0IxzL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e716b26f879be1b0e6ca3a09fa23eaee68578740/pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx#L183)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Oops, in my example code, I missed the `standardizeKey` call we still need here, right?
</blockquote></details>

Done.

**Review by maryliag — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70568)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Annebirzin, @Azhng, @kevin-v-ngo, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planTooltips.tsx, line 85 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70568#-MkDs1uv4yQ4eZYZyNk5:-MkDs1uwEoP_aMpFh0K6:b-xunn65) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec308d98505d3602df8e6d538a63ed9eeb8c929a/pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planTooltips.tsx#L85)):*
> ```XML
>       non-covering index where not all columns are present in the index to
>       satisfy the query. Index join requires columns to additionally be read
>       from the primary index.{" "}
> ```

nit:  you don't need this `{" "}` here
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planTooltips.tsx, line 124 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70568#-MkDsUUTDBskxZTZNR5c:-MkDsUUTDBskxZTZNR5d:b7z96mg) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec308d98505d3602df8e6d538a63ed9eeb8c929a/pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planTooltips.tsx#L124)):*
> ```XML
>     </span>
>   ),
>   update: <span>The update operator indicates an UPDATE statement.</span>,
> ```

nit: add `()` to get aligned with all other values

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70568)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Annebirzin, @kevin-v-ngo, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx, line 185 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70568#-MkDApJJDxUx7KuOHU9R:-MkEL24sD3jqrZyGF729:b-hmcamj) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bffa55050298b3e07c96a9395f1204a9497e764/pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx#L185)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

I'd prefer not to use camel case for CSS class names since css class names aren't case sensitive afaik, but it seems like past class names are in camel case. Perhaps a quick win to turn it into snake case? Not sure if you'd rather I just address the ones in this file here in this ticket.
</blockquote></details>

Hmm seems like a quick fix here. Let's just fix that in this PR then :stuck_out_tongue: 
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.spec.tsx, line 260 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70568#-MkDCl0u4vyz8TKIjS9y:-MkELC0f6LcyqirDAGaY:bb6mt9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bffa55050298b3e07c96a9395f1204a9497e764/pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.spec.tsx#L260)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

I believe for now the only cases I observed were from the join operators.
</blockquote></details>

:+1:

**Review by xinhaoz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70568)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Annebirzin, @Azhng, @kevin-v-ngo, @maryliag, @matthewtodd, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planTooltips.tsx, line 85 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70568#-MkDs1uv4yQ4eZYZyNk5:-MkI6KjL2Uzo5SzE53KX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec308d98505d3602df8e6d538a63ed9eeb8c929a/pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planTooltips.tsx#L85)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit:  you don't need this `{" "}` here
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planTooltips.tsx, line 124 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70568#-MkDsUUTDBskxZTZNR5c:-MkI6HGY34jjY440yBEr:b-6fubzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec308d98505d3602df8e6d538a63ed9eeb8c929a/pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planTooltips.tsx#L124)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: add `()` to get aligned with all other values
</blockquote></details>

Formatter reverted it, so going to leave this.
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx, line 185 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70568#-MkDApJJDxUx7KuOHU9R:-MkI6GcH0Gn7nV3SrMex:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3bffa55050298b3e07c96a9395f1204a9497e764/pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.tsx#L185)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm seems like a quick fix here. Let's just fix that in this PR then :stuck_out_tongue: 
</blockquote></details>

Done.

**Review by maryliag — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 5 files at r1, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70568#-:-MkI9zw37nTJ7ovKSzNR:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @Annebirzin, @Azhng, @kevin-v-ngo, and @xinhaoz)

**Review by Azhng — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70568#-:-MkIEJue2e_LCConOCI8:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (and 1 stale) (waiting on @Annebirzin, @kevin-v-ngo, and @xinhaoz)

**Comment by xinhaoz** [comment]
TFTR!!!
bors r=Azhng,maryliag,matthewtodd

**Review by kevin-v-ngo — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 1 of 2 files at r3, 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70568)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 3 stale) (waiting on @Annebirzin and @xinhaoz)

**Pull request merged**
