### PR TITLE
migration,startupmigrations: make AlterSystemWebSessionsCreateIndexes migration async

### LINKED ISSUE #65701: roachtest: acceptance/version-upgrade failed [ambiguous result]
roachtest.acceptance/version-upgrade [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3013935&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3013935&tab=artifacts#/acceptance/version-upgrade) on master @ [4192f1d5b58257bfe796bc33f774b11a33ae39a7](https://github.com/cockroachdb/cockroach/commits/4192f1d5b58257bfe796bc33f774b11a33ae39a7):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: artifacts/acceptance/version-upgrade/run_1
	versionupgrade.go:405,versionupgrade.go:200,versionupgrade.go:188,acceptance.go:47,acceptance.go:101,test_runner.go:792: pq: log-event: result is ambiguous (error=rpc error: code = Unavailable desc = transport is closing [exhausted])
```
<details><summary>Reproduce</summary>
<p>
<p>To reproduce, try:

```bash
# From https://go.crdb.dev/p/roachstress, perhaps edited lightly.
caffeinate ./roachstress.sh acceptance/version-upgrade
```
</p>
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*acceptance/version-upgrade.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #69145: migration,startupmigrations: move AlterSystemWebSessionsCreateIndexes migration to be async
**Describe the problem**

The migration associated with `AlterSystemWebSessionsCreateIndexes` which was added in https://github.com/cockroachdb/cockroach/pull/67547 should use `pkg/migration` as opposed to startupmigrations. It creates two indexes over tables which might be large. That's painful for a few reasons. One of which is that `IF NOT EXISTS` will return immediately even before the index has been made public. I think that's better than an error but it is hazardous. The other issue is that it may take a while.

**Suggested solution**

The solution is to use the `migration` package. We have similar migrations in this release which should make this straightforward. In particular, I'll point you at this helper function which I think you'll find useful:

https://github.com/cockroachdb/cockroach/blob/8d0f75eb31c16bddf9f8c5be2c4fc08a087f58d6/pkg/migration/migrations/retry_jobs_with_exponential_backoff.go#L93-L108

The idea is that you provide a sql statement and you provide a function to determine whether the table has been migrated appropriately. This will deal with all the concurrency issues for you.

This migration is registered here:
https://github.com/cockroachdb/cockroach/blob/8d0f75eb31c16bddf9f8c5be2c4fc08a087f58d6/pkg/migration/migrations/migrations.go#L113-L117

When it comes to adoption, you'll just want to version gate running the code that relies on the index on your added version. Unfortunately we do not have a callback for when a version changes. In the past, what we've done is just run a loop to poll the version and wait for it to become active.

### PR DESCRIPTION
**Pull request by cameronnunez**
Fixes [#69145](https://github.com/cockroachdb/cockroach/issues/69145).

`AlterSystemWebSessionsCreateIndexes` is a startup migration yet it creates 
indexes on potentially large tables. This might cause significant time delays and 
lead to other issues. This patch makes this migration long-running. 

Release note (bug fix): The `AlterSystemWebSessionsCreateIndexes` migration 
is now async in case there are large tables it creates indexes over. 

Release justification: bug fix

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69167)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez)

___
*[pkg/migration/migrations/migrations.go, line 138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69167#-MhUbPqq2oLlgYPOW4si:-MhUbPqq2oLlgYPOW4sj:bf2ui4t) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ca1032643286223028850fe7e375a3c808c0d91/pkg/migration/migrations/migrations.go#L138)):*
> ```Go
> 		interleavedTablesRemovedMigration,
> 		interleavedTablesRemovedMigration,
> 	),
> ```

I was expecting to the the new migration added here. 
___
*[pkg/migration/migrations/migrations.go, line 168 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69167#-MhUayku3Bfxjz8ZdRG1:-MhUayku3Bfxjz8ZdRG2:b-67i97c) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ca1032643286223028850fe7e375a3c808c0d91/pkg/migration/migrations/migrations.go#L168)):*
<details><summary><i alt="summary">Quoted 16 lines of code…</i></summary>

> ```
> // migrateTable is run during a migration to a new version and changes an existing
> // table's schema based on schemaChangeQuery. The schema-change is ignored if the
> // table already has the required changes.
> //
> // This function reads the existing table descriptor from storage and passes it
> // to schemaExists function to verify whether the schema-change already exists or
> // not. If the change is already done, the function does not perform the change
> // again, which makes migrateTable idempotent.
> //
> // schemaExists function should be customized based on the table being modified,
> // ignoring the fields in the descriptor that do not
> //
> // If multiple changes are done in the same query, e.g., if multiple columns are
> // added, the function should check all changes to exist or absent, returning
> // an error if changes exist partially.
> func migrateTable(
> ```
</details>

how about another file like `schema_changes.go`?
___
*[pkg/server/server.go, line 819 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69167#-MhUbTO51bHW3_QlsHJw:-MhUbTO51bHW3_QlsHJx:brc0ic) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ca1032643286223028850fe7e375a3c808c0d91/pkg/server/server.go#L819)):*
> ```Go
> 
> 	// Begin an async task to periodically purge old sessions in the system.web_sessions table.
> 	if lateBoundServer.cfg.Settings.Version.IsActive(ctx, clusterversion.AlterSystemWebSessionsCreateIndexes) {
> ```

I think this needs to be a bit more sophisticated. The version is going to become active later, so we need to start something. 
___
*[pkg/startupmigrations/migrations_test.go, line 768 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69167#-MhUbK-3CE6aKDVxOgGN:-MhUbK-3CE6aKDVxOgGO:b-fwr7uv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fb75ba1a3c6f11358886352f514b0efb603527/pkg/startupmigrations/migrations_test.go#L768)):*
> ```Go
> }
> 
> func TestAlterSystemWebSessionsTable(t *testing.T) {
> ```

please do port this test

**Review by cameronnunez — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69167)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @cameronnunez)

___
*[pkg/migration/migrations/migrations.go, line 138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69167#-MhUbPqq2oLlgYPOW4si:-MhnbUx3DcZ27PEyMggy:b-jhjqgv) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ca1032643286223028850fe7e375a3c808c0d91/pkg/migration/migrations/migrations.go#L138)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I was expecting to the the new migration added here. 
</blockquote></details>

:thumbsup: left it out while I was writing the `alterSystemWebSessionsCreateIndexes` function
___
*[pkg/migration/migrations/migrations.go, line 168 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69167#-MhUayku3Bfxjz8ZdRG1:-MhnbnEL88V-R1h4Jy1R:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ca1032643286223028850fe7e375a3c808c0d91/pkg/migration/migrations/migrations.go#L168)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> // migrateTable is run during a migration to a new version and changes an existing
> // table's schema based on schemaChangeQuery. The schema-change is ignored if the
> // table already has the required changes.
> //
> // This function reads the existing table descriptor from storage and passes it
> // to schemaExists function to verify whether the schema-change already exists or
> // not. If the change is already done, the function does not perform the change
> // again, which makes migrateTable idempotent.
> //
> // schemaExists function should be customized based on the table being modified,
> // ignoring the fields in the descriptor that do not
> //
> // If multiple changes are done in the same query, e.g., if multiple columns are
> // added, the function should check all changes to exist or absent, returning
> // an error if changes exist partially.
> func migrateTable(
> ```
how about another file like `schema_changes.go`?
</blockquote></details>

Done.
___
*[pkg/startupmigrations/migrations_test.go, line 768 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69167#-MhUbK-3CE6aKDVxOgGN:-MhnboAa7zdKy2VArp6H:b2nhqqh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3fb75ba1a3c6f11358886352f514b0efb603527/pkg/startupmigrations/migrations_test.go#L768)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

please do port this test
</blockquote></details>

WIP
___
*[pkg/server/server.go, line 819 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69167#-MhUbTO51bHW3_QlsHJw:-MhnbtEl24vFaSk2i806:bs6uxg) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ca1032643286223028850fe7e375a3c808c0d91/pkg/server/server.go#L819)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think this needs to be a bit more sophisticated. The version is going to become active later, so we need to start something. 
</blockquote></details>

how about having the version gate within the goroutine? just added this so you can take a look

**Comment by cameronnunez** [comment]
@sajjadrizvi generalized some of the helper functions for the migration you created and moved the functions around. PTAL if you have time!

**Review by sajjadrizvi — COMMENTED** [review]
The code related to migration looks good to me.

I am not sure if you need a test that fails migration after creating one index. `TestMigrationWithFailures` already covers migration failures and retries. So I guess it will be OK to not add another test for this specific migration.

Thanks for the refactoring and generalizing it further.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69167#-:-Mhxt8aE3ozBA5c9umqy:b52smug)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @cameronnunez)

___
*[pkg/migration/migrations/retry_jobs_with_exponential_backoff_external_test.go, line 667 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69167#-MhxsbD-5TEKkt-nbEsX:-MhxsbD-5TEKkt-nbEsY:b-dp8pqi) ([raw file](https://github.com/cockroachdb/cockroach/blob/8418f43ef958948f364610a264436934d52fd7ca/pkg/migration/migrations/retry_jobs_with_exponential_backoff_external_test.go#L667)):*
> ```Go
> 		},
> 		NextIndexID:    4,
> 		Privileges:     descpb.NewCustomSuperuserPrivilegeDescriptor(privilege.ReadWriteData, security.NodeUserName()),
> ```

Is this line removed on purpose? It seems OK, but asking to be sure about removing this line.
___
*[pkg/migration/migrations/schema_changes.go, line 56 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69167#-Mhxjfs2E8Ax98jmjc2A:-Mhxjfs2E8Ax98jmjc2B:biel53x) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d1f874ed95de559c74ff2cc1e92d38ccb78ce9a/pkg/migration/migrations/schema_changes.go#L56)):*
> ```Go
> //
> // schemaExists function should be customized based on the table being modified,
> // ignoring the fields in the descriptor that do not
> ```

`... ignoring the fields that do not matter while comparing with an existing descriptor.`

I think I didn't finish this line the comment. Please update it.

**Review by cameronnunez — COMMENTED** [review]
TFYR! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69167#-:-Mhyj9iwCk6mlDJxGDKc:bz5pfhr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @sajjadrizvi)

___
*[pkg/migration/migrations/retry_jobs_with_exponential_backoff_external_test.go, line 667 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69167#-MhxsbD-5TEKkt-nbEsX:-MhyjQFz6nZZP0QbO2kg:b-nfgsi) ([raw file](https://github.com/cockroachdb/cockroach/blob/8418f43ef958948f364610a264436934d52fd7ca/pkg/migration/migrations/retry_jobs_with_exponential_backoff_external_test.go#L667)):*
<details><summary><i>Previously, sajjadrizvi (Sajjad Rizvi) wrote…</i></summary><blockquote>

Is this line removed on purpose? It seems OK, but asking to be sure about removing this line.
</blockquote></details>

Added back. For some reason, I was given complaints about that line, so I removed it. Works fine now.
___
*[pkg/migration/migrations/schema_changes.go, line 56 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69167#-Mhxjfs2E8Ax98jmjc2A:-Mhyja7d0GR4KLeiK6rr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d1f874ed95de559c74ff2cc1e92d38ccb78ce9a/pkg/migration/migrations/schema_changes.go#L56)):*
<details><summary><i>Previously, sajjadrizvi (Sajjad Rizvi) wrote…</i></summary><blockquote>

`... ignoring the fields that do not matter while comparing with an existing descriptor.`

I think I didn't finish this line the comment. Please update it.
</blockquote></details>

Done.

**Review by ajwerner — COMMENTED** [review]
this is looking good, thanks for picking this up!

CI is saying you need a release justification. 

> Reviewed 1 of 4 files at r1, 2 of 11 files at r3, 1 of 6 files at r4, 3 of 6 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69167#-:-MhzXWrLCJ7bGpEFrZ2w:b-rgjtmi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @cameronnunez, and @sajjadrizvi)

___
*[pkg/migration/migrations/helpers_test.go, line 11 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69167#-MhzX1Iu5astacqSnoP8:-MhzX1Iu5astacqSnoP9:b-txz46t) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1e302bab84216b7d3334683adc52da95a0a15ff/pkg/migration/migrations/helpers_test.go#L11)):*
> ```
> package migrations
> ```
the reason for the `helper_test.go` file being in `package migrations` is that the symbols it exports won't be exported to other packages but will be available in `migrations_test`.
___
*[pkg/migration/migrations/schema_changes.go, line 191 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69167#-MhzWRssEbU50-SugPfr:-MhzWRssEbU50-SugPfs:b-c6s03e) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1e302bab84216b7d3334683adc52da95a0a15ff/pkg/migration/migrations/schema_changes.go#L191)):*
> ```Go
> // expectedTable descriptor. The comparison is not strict as several descriptor
> // fields are ignored.
> func HasColumn(storedTable, expectedTable catalog.TableDescriptor, colName string) (bool, error) {
> ```

nit: don't export this directly, instead, make a `helpers_test.go` file that does the following to make the symbols available in the `migrations_test` package

```go
package migrations

var (
    HasColumn = hasColumn
    HasIndex = hasIndex
)
```
___
*[pkg/migration/migrations/schema_changes.go, line 245 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69167#-MhzVkxV0MrFNdEuwyRs:-MhzVkxWASSuNIJUf3cU:b-iwfwv3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1e302bab84216b7d3334683adc52da95a0a15ff/pkg/migration/migrations/schema_changes.go#L245)):*
> ```
> 	storedCopy.CreatedExplicitly = false
> 	expectedCopy.CreatedExplicitly = false
> ```
how come we're saying this field does not matter?

**Review by cameronnunez — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69167)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @cameronnunez, and @sajjadrizvi)

___
*[pkg/migration/migrations/helpers_test.go, line 11 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69167#-MhzX1Iu5astacqSnoP8:-Mi2dW9DE48L9NfVJrs5:bpahgew) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1e302bab84216b7d3334683adc52da95a0a15ff/pkg/migration/migrations/helpers_test.go#L11)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> package migrations
> ```
the reason for the `helper_test.go` file being in `package migrations` is that the symbols it exports won't be exported to other packages but will be available in `migrations_test`.
</blockquote></details>

Ah that makes a lot of sense. Updated.
___
*[pkg/migration/migrations/schema_changes.go, line 245 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69167#-MhzVkxV0MrFNdEuwyRs:-Mi2dbDoB1Qa2HFzMQeI:b-h1wao6) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1e302bab84216b7d3334683adc52da95a0a15ff/pkg/migration/migrations/schema_changes.go#L245)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	storedCopy.CreatedExplicitly = false
> 	expectedCopy.CreatedExplicitly = false
> ```
how come we're saying this field does not matter?
</blockquote></details>

I think it is because `storedCopy.CreatedExplicitly` is set equal to true after the call to `migrations.Migrate()` in the unit test. However, `expectedCopy.CreatedExplicitly` will always be false since the schema is taken directly from `systemschema/system.go`. This results in  `hasIndex()` always returning false. Is this correct,  @sajjadrizvi?

**Review by sajjadrizvi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69167)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @cameronnunez, and @sajjadrizvi)

___
*[pkg/migration/migrations/schema_changes.go, line 245 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69167#-MhzVkxV0MrFNdEuwyRs:-Mi2wVk30fzzUf0BQDmg:b-7olb9h) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1e302bab84216b7d3334683adc52da95a0a15ff/pkg/migration/migrations/schema_changes.go#L245)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

I think it is because `storedCopy.CreatedExplicitly` is set equal to true after the call to `migrations.Migrate()` in the unit test. However, `expectedCopy.CreatedExplicitly` will always be false since the schema is taken directly from `systemschema/system.go`. This results in  `hasIndex()` always returning false. Is this correct,  @sajjadrizvi? 
</blockquote></details>

Yes, that's is the case. They should not be the same when an index is created successfully in the migration. So, I think it is safe to ignore these fields in the comparison.

**Comment by cameronnunez** [comment]
RFAL

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69167#-:-MiNsxz19KxgBPwCkE6_:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @cameronnunez, and @sajjadrizvi)

___
*[pkg/migration/migrations/schema_changes.go, line 245 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69167#-MhzVkxV0MrFNdEuwyRs:-MiNoZhv9kbIBQvvpNSw:bdb7fxq) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1e302bab84216b7d3334683adc52da95a0a15ff/pkg/migration/migrations/schema_changes.go#L245)):*
<details><summary><i>Previously, sajjadrizvi (Sajjad Rizvi) wrote…</i></summary><blockquote>

Yes, that's is the case. They should not be the same when an index is created successfully in the migration. So, I think it is safe to ignore these fields in the comparison.
</blockquote></details>

This ends up being due to bugs in where we set and use that field. See https://github.com/cockroachdb/cockroach/issues/65929. Can you put a comment explaining that the `CreatedExplicitly` field is ignored because of inconsistent behavior between `CREATE TABLE (... INDEX)` and `CREATE INDEX`? 
___
*[pkg/server/server.go, line 819 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69167#-MhUbTO51bHW3_QlsHJw:-MiNr1Wa8Smwe9Zpst9c:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/5ca1032643286223028850fe7e375a3c808c0d91/pkg/server/server.go#L819)):*
<details><summary><i>Previously, cameronnunez (Cameron Nunez) wrote…</i></summary><blockquote>

how about having the version gate within the goroutine? just added this so you can take a look
</blockquote></details>

:thumbsup:

**Review by cameronnunez — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69167)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @cameronnunez, and @sajjadrizvi)

___
*[pkg/migration/migrations/schema_changes.go, line 245 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69167#-MhzVkxV0MrFNdEuwyRs:-MiNxUhsDmcY8SZJcgh1:b1f9jin) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1e302bab84216b7d3334683adc52da95a0a15ff/pkg/migration/migrations/schema_changes.go#L245)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This ends up being due to bugs in where we set and use that field. See https://github.com/cockroachdb/cockroach/issues/65929. Can you put a comment explaining that the `CreatedExplicitly` field is ignored because of inconsistent behavior between `CREATE TABLE (... INDEX)` and `CREATE INDEX`? 
</blockquote></details>

Understood – done.

**Review by knz — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 1 of 11 files at r3, 1 of 6 files at r4, 1 of 7 files at r7, 6 of 7 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69167)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @cameronnunez, and @sajjadrizvi)

___
*[pkg/migration/migrations/schema_changes.go, line 37 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/69167#-MiRUdx8ARJWkZEmUnAV:-MiRUdx8ARJWkZEmUnAW:b-mjb33b) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b9784dcff06aef79955712e3828fc62be25654a/pkg/migration/migrations/schema_changes.go#L37)):*
> ```Go
> type operation struct {
> 	// Operation name.
> 	name string
> ```

you probably want to make `name` a `redact.RedactableString` or `redact.SafeString` to ensure it does not get elided in log messages.

**Review by cameronnunez — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69167)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @cameronnunez, @knz, and @sajjadrizvi)

___
*[pkg/migration/migrations/schema_changes.go, line 37 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/69167#-MiRUdx8ARJWkZEmUnAV:-MiS8CLv0NrbmNUW0ndc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b9784dcff06aef79955712e3828fc62be25654a/pkg/migration/migrations/schema_changes.go#L37)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

you probably want to make `name` a `redact.RedactableString` or `redact.SafeString` to ensure it does not get elided in log messages.
</blockquote></details>

Done.

**Comment by knz** [comment]
You need to rebase this, there is a merge conflict. Then you can merge it.

**Comment by cameronnunez** [comment]
thanks all!

bors r=ajwerner,knz

**Pull request merged**
