### PR TITLE
distsqlpb: whitelist node unavailability errors

### LINKED ISSUE #37215: sentry: (0) data.go:158: uncaught error: %+v | *roachpb.NodeUnavailableError
(see stack traces in additional data)
This issue was autofiled by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry link: https://sentry.io/organizations/cockroach-labs/issues/1005840789/?project=164528&referrer=webhooks_plugin

Panic message:

>(0) data.go:158: uncaught error: %+v | *roachpb.NodeUnavailableError
(see stack traces in additional data)

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

https://github.com/cockroachdb/cockroach/blob/13acf110dd353d4a9e86a9545bd5706b8bad9401/pkg/sql/distsqlpb/data.go#L157-L159 in pkg/sql/distsqlpb.NewError
https://github.com/cockroachdb/cockroach/blob/13acf110dd353d4a9e86a9545bd5706b8bad9401/pkg/sql/distsqlrun/server.go#L574-L576 in pkg/sql/distsqlrun.(*ServerImpl).SetupFlow
https://github.com/cockroachdb/cockroach/blob/13acf110dd353d4a9e86a9545bd5706b8bad9401/pkg/sql/distsqlpb/api.pb.go#L602-L604 in pkg/sql/distsqlpb._DistSQL_SetupFlow_Handler.func1
https://github.com/cockroachdb/cockroach/blob/13acf110dd353d4a9e86a9545bd5706b8bad9401/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go#L56-L58 in vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1
https://github.com/cockroachdb/cockroach/blob/13acf110dd353d4a9e86a9545bd5706b8bad9401/pkg/rpc/context.go#L221-L223 in pkg/rpc.NewServerWithInterceptor.func2
https://github.com/cockroachdb/cockroach/blob/13acf110dd353d4a9e86a9545bd5706b8bad9401/pkg/rpc/context.go#L251-L253 in pkg/rpc.NewServerWithInterceptor.func4
https://github.com/cockroachdb/cockroach/blob/13acf110dd353d4a9e86a9545bd5706b8bad9401/pkg/sql/distsqlpb/api.pb.go#L604-L606 in pkg/sql/distsqlpb._DistSQL_SetupFlow_Handler
https://github.com/cockroachdb/cockroach/blob/13acf110dd353d4a9e86a9545bd5706b8bad9401/vendor/google.golang.org/grpc/server.go#L1010-L1012 in vendor/google.golang.org/grpc.(*Server).processUnaryRPC
https://github.com/cockroachdb/cockroach/blob/13acf110dd353d4a9e86a9545bd5706b8bad9401/vendor/google.golang.org/grpc/server.go#L1248-L1250 in vendor/google.golang.org/grpc.(*Server).handleStream
https://github.com/cockroachdb/cockroach/blob/13acf110dd353d4a9e86a9545bd5706b8bad9401/vendor/google.golang.org/grpc/server.go#L679-L681 in vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1
</details>

```
pkg/sql/distsqlpb/data.go in pkg/sql/distsqlpb.NewError at line 158
pkg/sql/distsqlrun/server.go in pkg/sql/distsqlrun.(*ServerImpl).SetupFlow at line 575
pkg/sql/distsqlpb/api.pb.go in pkg/sql/distsqlpb._DistSQL_SetupFlow_Handler.func1 at line 603
vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go in vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1 at line 57
pkg/rpc/context.go in pkg/rpc.NewServerWithInterceptor.func2 at line 222
pkg/rpc/context.go in pkg/rpc.NewServerWithInterceptor.func4 at line 252
pkg/sql/distsqlpb/api.pb.go in pkg/sql/distsqlpb._DistSQL_SetupFlow_Handler at line 605
vendor/google.golang.org/grpc/server.go in vendor/google.golang.org/grpc.(*Server).processUnaryRPC at line 1011
vendor/google.golang.org/grpc/server.go in vendor/google.golang.org/grpc.(*Server).handleStream at line 1249
vendor/google.golang.org/grpc/server.go in vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1 at line 680
```

| Tag | Value |
|---|---|
| Cockroach Release | `v19.2.0-alpha.00000000-182-g13acf11` |
| Cockroach SHA: | 13acf110dd353d4a9e86a9545bd5706b8bad9401 |
| Platform | linux amd64 |
| Distribution | CCL |
| Environment | development |
| Command | server |
| Go Version | `go1.11.6`|
| # of CPUs |4 |
| # of Goroutines |374 |

### PR DESCRIPTION
**Pull request by knz**
Fixes #37215.

A node being down during distsql query processing is a legitimate (and
expected) error. It needs not be reported to telemetry.

### CODE REVIEW

**Comment by knz** [comment]
@RaduBerinde this is the change I was telling you about. I need a way to ensure that new distsql execution nodes (with this patch in) are not being used by old gateways (without this patch) so we don't get a crash upon non-decodable errors. What's the right combination of expected versions that will give me that guarantee?

**Comment by RaduBerinde** [comment]
Sounds like you need to bump both distsqlrun.Version and MinAcceptedVersion to 23.

Is this something you want to backport to 19.1.x? (bumping the version could be too disruptive for a point release)

**Comment by knz** [comment]
I wasn't directly considering a backport, but if we don't we'll want to decide what to do about #37215 in that version.

**Comment by knz** [comment]
@andreimatei do you have further thoughts?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37367)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/sql/distsqlpb/data.proto, line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37367#-LeSDfG48L0thVzJcOEe:-LeSDfG48L0thVzJcOEf:b-kzmqp8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d512889ba64580a35b94d0503962de9930d1f46/pkg/sql/distsqlpb/data.proto#L43)):*
> ```protobuf
>     pgerror.Error pg_error = 1 [(gogoproto.customname) = "PGError"];
>     roachpb.UnhandledRetryableError retryableTxnError = 2;
>     roachpb.NodeUnavailableError nodeUnavailableError = 3;
> ```

rather than starting to add random errors here, wouldn't it be better to turn `NodeUnavailableErr` into a pgerror? Even one with the internal error code. Nobody in DistSQL needs to recognize this error I believe.

**Review by knz — COMMENTED** [review]
Thanks Andrei for the simplification. This way no need for client/server restrictions. RFAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37367#-:-LfFmHwr8fCxOyZYFps6:bm410wq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/sql/distsqlpb/data.proto, line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37367#-LeSDfG48L0thVzJcOEe:-LfFjl50DkLCvFok3YT2:b77nk06) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d512889ba64580a35b94d0503962de9930d1f46/pkg/sql/distsqlpb/data.proto#L43)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

rather than starting to add random errors here, wouldn't it be better to turn `NodeUnavailableErr` into a pgerror? Even one with the internal error code. Nobody in DistSQL needs to recognize this error I believe.
</blockquote></details>

"internal error" is exactly what NewAssertionError (the current code) does and that triggers a sentry report. The issue #37215 was filed because we don't want a sentry report every time a node is down.

However I do like the idea to use a pgerror here, just because it doesn't raise version compatibility questions. Thanks for the hint.

**Review by andreimatei — APPROVED** [review]
:lgtm: 

but consider the comment about using a different code

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37367#-:-LfKtsRv62lP_oJWrRp4:brx97e3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @knz)

___
*[pkg/sql/distsqlpb/data.go, line 160 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37367#-LfKtHZm5LhwG3IG8v4N:-LfKtHZn8X6FX6WeDbA7:b-kfchz6) ([raw file](https://github.com/cockroachdb/cockroach/blob/64cda0956b279f52df0f1338af36ef2e56d32572/pkg/sql/distsqlpb/data.go#L160)):*
> ```Go
> 		return &Error{
> 			Detail: &Error_PGError{
> 				PGError: pgerror.Newf(pgerror.CodeConnectionExceptionError, "%v", e),
> ```

This error code doesn't seem right to me. I can't find any docs on it, but the other codes in its class refer to errors about a client connection, not something internal to the cluster.
I can't see another code that would apply, which is not surprising given that Postgres doesn't have such issues. I'd introduce another code akin to the one that we've already introduced for something similar (`CodeRangeUnavailable`), or just use that one.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37367)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei)

___
*[pkg/sql/distsqlpb/data.go, line 160 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/37367#-LfKtHZm5LhwG3IG8v4N:-LfdbV7Y8rfSXQbdSjlt:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/64cda0956b279f52df0f1338af36ef2e56d32572/pkg/sql/distsqlpb/data.go#L160)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

This error code doesn't seem right to me. I can't find any docs on it, but the other codes in its class refer to errors about a client connection, not something internal to the cluster.
I can't see another code that would apply, which is not surprising given that Postgres doesn't have such issues. I'd introduce another code akin to the one that we've already introduced for something similar (`CodeRangeUnavailable`), or just use that one.
</blockquote></details>

Good idea. Done.

**Comment by knz** [comment]
TFYR!

bors r+

**Comment by knz** [comment]
Build timeout. retrying

bors r+

**Pull request merged**
