### PR TITLE
geo: various geospatial built-in fixes

### PR DESCRIPTION
**Pull request by rharding6373**
geo: support null input for geohash builtins
    
    Allows and adds support for NULL inputs for the st_pointfromgeohash and
    st_geomfromgeohash built-ins.
    
    Epic: None
    Informs: #111157
    
    Release note (bug fix): Fixes null input handling for the geospatial
    built-ins st_pointfromgeohash and st_geomfromgeohash.
  

    geo: allow st_makeenvelope min/max bounds to be reversed
    
    Postgis allows xmin/ymin to be greater than xmax/ymax respectively in
    st_makeenvelope, but the geom library does not allow this when
    converting Bounds to Polygon. Instead, we build the polygon explicitly
    from the provided min/max coordinates.
    
    Epic: None
    Fixes: #111157
    
    Release note (bug fix): The geospatial st_makeenvelope built-in now
    correctly supports xmin or ymin to be greater than xmax or ymax,
    respectively.

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
:lgtm: Nice work!

> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113781#-:-NiMBaHp9d2LWMLbZAcp:bcmw7ss)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rharding6373)

___
*[`pkg/sql/sem/builtins/geo_builtins.go` line 1133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113781#-NiM9-ux3KuSKZLx__HK:-NiM9-ux3KuSKZLx__HL:b116h4z) ([raw file](https://github.com/cockroachdb/cockroach/blob/c61550f6ca5fafcf871f1bc2446e458e9155a7a9/pkg/sql/sem/builtins/geo_builtins.go#L1133)):*
> ```Go
> 			ReturnType: tree.FixedReturnType(types.Geometry),
> 			Fn: func(_ context.Context, evalCtx *eval.Context, args tree.Datums) (tree.Datum, error) {
> 				if tree.DNull.Compare(evalCtx, args[0]) == 0{
> ```

[nit] Elsewhere we just directly compare args with `tree.DNull` using `==`. Did you find a case where that doesn't work?

**Review by rharding6373 — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113781#-:-NiMaWlc8JYzsV1Mednq:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball)

___
*[`pkg/sql/sem/builtins/geo_builtins.go` line 1133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113781#-NiM9-ux3KuSKZLx__HK:-NiMa31CBZNmBI5tkNof:b-c2xiyj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c61550f6ca5fafcf871f1bc2446e458e9155a7a9/pkg/sql/sem/builtins/geo_builtins.go#L1133)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Elsewhere we just directly compare args with `tree.DNull` using `==`. Did you find a case where that doesn't work?
</blockquote></details>

That's just how I happened to write it out. Thanks for the suggestion!

**Comment by rharding6373** [comment]
I created a new issue for the test failure, which is an unrelated randomized CDC test: #113842

**Comment by rharding6373** [comment]
TFTR!

bors r+

**Pull request merged**
