### PR TITLE
raft: use a single raft transport everywhere

### PR DESCRIPTION
**Pull request by tamird**
The implementation here is mostly taken from the old localRPCContext, since that one has had the grpc issues addressed.

This code might be light on comments now, please call out specific areas if you think they'd benefit from comments.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4608)

### CODE REVIEW

**Comment by tamird** [comment]
Should fix #4419 and #4437.

**Comment by bdarnell** [comment]
Review status: 0 of 14 files reviewed at latest revision, 5 unresolved discussions.

---

*[server/node_test.go, line 100 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4608#-KBIZW9vyZbs5eCnhs5J:-KBIZW9vyZbs5eCnhs5K:988904320) ([raw file](https://github.com/cockroachdb/cockroach/blob/177bd0a621d4be2ce8711b0b188af8aeaa4189c0/server/node_test.go#L100)):*
I'd make a `storage.NewDummyRaftTransport()` function instead of repeating this comment everywhere. The comment on this line also has doubled `// //`.

---

*[storage/client_test.go, line 253 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4608#-KBIXY3qbRkBkn7wOW83:-KBIXY3qbRkBkn7wOW84:1078110332) ([raw file](https://github.com/cockroachdb/cockroach/blob/177bd0a621d4be2ce8711b0b188af8aeaa4189c0/storage/client_test.go#L253)):*
Why do we create a secure context here and an insecure one above? If this is intentional it needs comments, but I think it would be better to initialize `m.rpcContext` just once, before the `if m.gossip == nil` block.

---

*[storage/raft_transport.go, line 42 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4608#-KBIYz4tfJcjzru3zX86:-KBIYz4tfJcjzru3zX87:1681216202) ([raw file](https://github.com/cockroachdb/cockroach/blob/177bd0a621d4be2ce8711b0b188af8aeaa4189c0/storage/raft_transport.go#L42)):*
s/GossipPolymorphismShim/GossipAddressResolver/g

Or `NodeAddressResolver` could be defined in terms of `util.UnresolvedAddr` instead of `net.Addr` (and be an interface implemented by `Gossip` instead of a function type). If the production code sends everything through `UnresolvedAddr` then the test code might as well do the same.

---

*[storage/raft_transport.go, line 140 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4608#-KBIaRDEmUxF8zIC-dY-:-KBIaRDFCkbJmfove-VF:1581329283) ([raw file](https://github.com/cockroachdb/cockroach/blob/177bd0a621d4be2ce8711b0b188af8aeaa4189c0/storage/raft_transport.go#L140)):*
We need to check `t.mu.streams[nodeID]` again since we had to release the lock to upgrade from a read to write lock. The stream may have been created in between.

---

*[storage/raft_transport.go, line 155 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4608#-KBImftV9DCWcK6YQ_Bf:-KBImftV9DCWcK6YQ_Bg:1852398857) ([raw file](https://github.com/cockroachdb/cockroach/blob/177bd0a621d4be2ce8711b0b188af8aeaa4189c0/storage/raft_transport.go#L155)):*
I'm concerned about calling `GRPCDial` and `RaftMessage` while holding the write lock here. (`GRPCDial` may be fine now that we've removed `WithBlock` from the default options). We need to either make sure that we won't block on the network while holding the lock (because this would allow one bad network link to interfere with messages to other nodes), or re-introduce an intermediate channel like we had in server/raft_transport.go

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4608)*

**Comment by tschottdorf** [comment]
Reviewed 13 of 15 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[kv/local_test_cluster.go, line 121 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4608#-KBIslQoax6FiuqNRkDq:-KBIslQoax6FiuqNRkDr:-2079613304) ([raw file](https://github.com/cockroachdb/cockroach/blob/177bd0a621d4be2ce8711b0b188af8aeaa4189c0/kv/local_test_cluster.go#L121)):*
nit: something something don't capitalize no dot

---

*[server/server.go, line 173 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4608#-KBItBE8i5cAY8rpKhtc:-KBItBE8i5cAY8rpKhtd:-450663345) ([raw file](https://github.com/cockroachdb/cockroach/blob/177bd0a621d4be2ce8711b0b188af8aeaa4189c0/server/server.go#L173)):*
Looking forward to finding out what a GPS it is.

---

*[storage/client_test.go, line 541 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4608#-KBItSKKfsAKMCEFB1J_:-KBItSKKfsAKMCEFB1Ja:-989465452) ([raw file](https://github.com/cockroachdb/cockroach/blob/177bd0a621d4be2ce8711b0b188af8aeaa4189c0/storage/client_test.go#L541)):*
poisons the lock

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4608)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[kv/local_test_cluster.go, line 121 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4608#-KBIslQoax6FiuqNRkDq:-KBIxijsC-Pp_X3OmZn_:-1671707661) ([raw file](https://github.com/cockroachdb/cockroach/blob/177bd0a621d4be2ce8711b0b188af8aeaa4189c0/kv/local_test_cluster.go#L121)):*
yeah, removed in favour of NewDummyRaftTransport.

---

*[server/node_test.go, line 100 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4608#-KBIZW9vyZbs5eCnhs5J:-KBIt8nDtPLTnGGBgvD9:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/177bd0a621d4be2ce8711b0b188af8aeaa4189c0/server/node_test.go#L100)):*
Done.

---

*[server/server.go, line 173 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4608#-KBItBE8i5cAY8rpKhtc:-KBIxtzu-1DKvhjgxmGx:726469523) ([raw file](https://github.com/cockroachdb/cockroach/blob/177bd0a621d4be2ce8711b0b188af8aeaa4189c0/server/server.go#L173)):*
:clap: 

---

*[storage/client_test.go, line 253 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4608#-KBIXY3qbRkBkn7wOW83:-KBIojyCM8ANLTkhAYw6:1134297461) ([raw file](https://github.com/cockroachdb/cockroach/blob/177bd0a621d4be2ce8711b0b188af8aeaa4189c0/storage/client_test.go#L253)):*
Just an oversight. Done.

---

*[storage/client_test.go, line 541 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4608#-KBItSKKfsAKMCEFB1J_:-KBIyPvbOq3hw1gso3g4:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/177bd0a621d4be2ce8711b0b188af8aeaa4189c0/storage/client_test.go#L541)):*
Done.

---

*[storage/raft_transport.go, line 42 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4608#-KBIYz4tfJcjzru3zX86:-KBIoxEXNBUjYYDdOtel:-90277215) ([raw file](https://github.com/cockroachdb/cockroach/blob/177bd0a621d4be2ce8711b0b188af8aeaa4189c0/storage/raft_transport.go#L42)):*
I started with that, but didn't like the boilerplate of making a util.UnresolvedAddr from net.(Listener).Addr(). Renamed this as you suggested.

---

*[storage/raft_transport.go, line 140 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4608#-KBIaRDEmUxF8zIC-dY-:-KBIpnNws4A_3m0WaZDU:-1622819128) ([raw file](https://github.com/cockroachdb/cockroach/blob/177bd0a621d4be2ce8711b0b188af8aeaa4189c0/storage/raft_transport.go#L140)):*
Good point. Done.

---

*[storage/raft_transport.go, line 155 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4608#-KBImftV9DCWcK6YQ_Bf:-KBIxeQw7QrVWfr2bDhh:1092759002) ([raw file](https://github.com/cockroachdb/cockroach/blob/177bd0a621d4be2ce8711b0b188af8aeaa4189c0/storage/raft_transport.go#L155)):*
I've made this a bit more clever using sync.Once. PTAL.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4608)*

**Comment by tamird** [comment]
I've reverted this to using queues after all. PTAL

**Comment by bdarnell** [comment]
LGTM

---

Review status: 3 of 15 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4608#-:-KBKJyuJGOGc0Ng0_-4C:676834233)*

**Pull request merged**
