### PR TITLE
remove make check from make all

### LINKED ISSUE #7765: make check: remove TestSafeSQL
This is a test that takes forever to run and is hurting productivity. Is there a way we can run it on CI but not locally?

### PR DESCRIPTION
**Pull request by vivekmenezes**
"make" will run "make build test"

make check is too expensive

fixes #7765

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7769)

### CODE REVIEW

**Comment by petermattis** [comment]
Heh, that wasn't what I was suggesting in my comment to #7765. I think having `all` depend on `check` is the right default. Is there something forcing you to run `make all`?

**Comment by vivekmenezes** [comment]
I'm okay with not merging this, but is there a reason for including check with all? I know folks in the past have wanted make to just build the binary, but having it run the tests is valuable.

**Comment by petermattis** [comment]
I'm not clear what the usability problem is here. `make all` (or `make`) is just shorthand for `make build test check`. If you don't want `check`, then type `make build test`. If you don't want the binary, then `make test`. If this is too much to type, then create shell aliases. There is every intention that you only need to run the portion of the makefile needed for your particular edit-debug-cycle.

**Comment by bdarnell** [comment]
FWIW, I'm of the opinion that `make` (and `make all`) should be equivalent to `make build`, following the convention established by the vast majority of open source projects (at least in C). The Makefile defaults should be tuned for someone installing from source; developers should use non-default commands (although installing from source is much less common than it used to be, so maybe this is an out of date convention)

(Personally I never run `make` or `make build`; my pre-push incantation is `make test check testrace`)

**Comment by petermattis** [comment]
Why shouldn't developers installing from source run the tests? I agree that there is a convention in many C projects to not do so, yet I'm not sure that convention is worth following. As a counter-example in the Go world, building Go from source runs the tests.

There is an argument that we shouldn't include `check` in `all` because there is little reason to run `check` unless you're modifying the source. But I'm not sure this is worth changing.

**Pull request closed without merging**
