### PR TITLE
opt: limit UDF inlining

### LINKED ISSUE #100915: opt: do not duplicate column IDs when inlining UDF arguments that are subqueries
When the argument of a UDF is a subquery, and the argument is referenced multiple times in the UDF body, the optimizer uses the same column IDs when inlining the subquery for each reference. This can cause the optimizer to generate invalid plans. With the `crdb_test` build tag enabled, this causes the `check_expr.go` error: `internal error: left-join RelExpr children have intersecting columns`.

Some ideas for fixing:

1. Don't inline UDFs with subqueries are arguments.
2. Or, a more loose restriction: don't inline UDFs with a subquery argument referenced multiple times in the UDF body.
3. Or, no restriction: duplicate column IDs in entire subquery expressions when inlining a UDF.

Here's an example that triggers the problem:

```sql
CREATE FUNCTION f(i INT) RETURNS BOOL STABLE LANGUAGE SQL AS $$
  SELECT i = 0 OR i = 10
$$;

SELECT f((SELECT y FROM (VALUES (10), (20)) y(y) WHERE x=y)) FROM (VALUES (10), (20)) x(x)
```

They query plan shows the duplicate column `column1:2` used on both side of the higest `left-join`:

```
project
 ├── columns: f:5
 ├── cardinality: [1 - 8]
 ├── stats: [rows=2]
 ├── cost: 0.57
 ├── distribution: test
 ├── prune: (5)
 ├── ensure-distinct-on
 │    ├── columns: column1:2 rownum:6
 │    ├── grouping columns: rownum:6
 │    ├── error: "more than one row returned by a subquery used as an expression"
 │    ├── cardinality: [1 - 8]
 │    ├── stats: [rows=2]
 │    ├── cost: 0.52
 │    ├── key: (6)
 │    ├── fd: (6)-->(2)
 │    ├── distribution: test
 │    ├── left-join (hash)
 │    │    ├── columns: column1:1 column1:2 rownum:6
 │    │    ├── cardinality: [1 - 8]
 │    │    ├── stats: [rows=2]
 │    │    ├── cost: 0.42
 │    │    ├── fd: (6)-->(1)
 │    │    ├── distribution: test
 │    │    ├── ensure-distinct-on
 │    │    │    ├── columns: column1:1 column1:2 rownum:6
 │    │    │    ├── grouping columns: rownum:6
 │    │    │    ├── error: "more than one row returned by a subquery used as an expression"
 │    │    │    ├── cardinality: [1 - 4]
 │    │    │    ├── stats: [rows=2, distinct(1)=2, null(1)=0, distinct(2)=2, null(2)=0, distinct(6)=2, null(6)=0]
 │    │    │    ├── cost: 0.3
 │    │    │    ├── key: (6)
 │    │    │    ├── fd: (6)-->(1,2)
 │    │    │    ├── distribution: test
 │    │    │    ├── prune: (1,2)
 │    │    │    ├── left-join (hash)
 │    │    │    │    ├── columns: column1:1 column1:2 rownum:6
 │    │    │    │    ├── cardinality: [2 - 4]
 │    │    │    │    ├── stats: [rows=2, distinct(2)=2, null(2)=0, distinct(6)=2, null(6)=0]
 │    │    │    │    ├── cost: 0.18
 │    │    │    │    ├── fd: (6)-->(1)
 │    │    │    │    ├── distribution: test
 │    │    │    │    ├── ordinality
 │    │    │    │    │    ├── columns: column1:1 rownum:6
 │    │    │    │    │    ├── cardinality: [2 - 2]
 │    │    │    │    │    ├── stats: [rows=2, distinct(1)=2, null(1)=0, distinct(6)=2, null(6)=0]
 │    │    │    │    │    ├── cost: 0.06
 │    │    │    │    │    ├── key: (6)
 │    │    │    │    │    ├── fd: (6)-->(1)
 │    │    │    │    │    ├── distribution: test
 │    │    │    │    │    ├── prune: (1)
 │    │    │    │    │    └── values
 │    │    │    │    │         ├── columns: column1:1
 │    │    │    │    │         ├── cardinality: [2 - 2]
 │    │    │    │    │         ├── stats: [rows=2, distinct(1)=2, null(1)=0]
 │    │    │    │    │         ├── cost: 0.03
 │    │    │    │    │         ├── distribution: test
 │    │    │    │    │         ├── prune: (1)
 │    │    │    │    │         ├── (10,)
 │    │    │    │    │         └── (20,)
 │    │    │    │    ├── values
 │    │    │    │    │    ├── columns: column1:2
 │    │    │    │    │    ├── cardinality: [2 - 2]
 │    │    │    │    │    ├── stats: [rows=2, distinct(2)=2, null(2)=0]
 │    │    │    │    │    ├── cost: 0.03
 │    │    │    │    │    ├── distribution: test
 │    │    │    │    │    ├── prune: (2)
 │    │    │    │    │    ├── (10,)
 │    │    │    │    │    └── (20,)
 │    │    │    │    └── filters
 │    │    │    │         └── column1:1 = column1:2 [outer=(1,2), constraints=(/1: (/NULL - ]; /2: (/NULL - ]), fd=(1)==(2), (2)==(1)]
 │    │    │    └── aggregations
 │    │    │         ├── const-agg [as=column1:1, outer=(1)]
 │    │    │         │    └── column1:1
 │    │    │         └── const-agg [as=column1:2, outer=(2)]
 │    │    │              └── column1:2
 │    │    ├── values
 │    │    │    ├── columns: column1:2
 │    │    │    ├── cardinality: [2 - 2]
 │    │    │    ├── stats: [rows=2, distinct(2)=2, null(2)=0]
 │    │    │    ├── cost: 0.03
 │    │    │    ├── distribution: test
 │    │    │    ├── prune: (2)
 │    │    │    ├── (10,)
 │    │    │    └── (20,)
 │    │    └── filters
 │    │         └── column1:1 = column1:2 [outer=(1,2), constraints=(/1: (/NULL - ]; /2: (/NULL - ]), fd=(1)==(2), (2)==(1)]
 │    └── aggregations
 │         └── const-agg [as=column1:2, outer=(2)]
 │              └── column1:2
 └── projections
      └── (column1:2 = 0) OR (column1:2 = 10) [as=f:5, outer=(2)]
```

### PR DESCRIPTION
**Pull request by mgartner**
#### opt: improve error check_expr error message

The error message in `check_expr.go` for the error that occurs when the
children of a relational expression have intersecting column IDs now
includes the columns that intersect. This makes it easier to debug rules
that cause this error.

Release note: None

#### opt: limit UDF inlining

UDFs are now only inlined if their arguments are only either Variable or
Const expressions. This simplifies the logic to determine if a UDF can
be safely inlined. At the expense of being overly strict, we now can be
assured that we are not incorrectly inlining complex expressions like
subqueries. Inlining UDFs when the subquery arguments are referenced
more than once in the UDF's body can lead to errors and possibly
incorrect results (see #100915).

Fixes #100915

Release note (bug fix): A bug has been fixed that caused errors in test
builds and potentially incorrect results in release builds when invoking
a user-defined function with a subquery argument. This bug was only
present in alpha pre-release versions of 23.1.

### CODE REVIEW

**Comment by mgartner** [comment]
The first commit is from #101324.

**Review by DrewKimball — APPROVED** [review]
:lgtm: Nice fix!

> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101327#-:-NSqmXqxAQlNz2IwnfZx:b-46lt7k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[`pkg/sql/opt/norm/inline_funcs.go` line 432 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/101327#-NSqjOK3E6jguMGL5b31:-NSqjOK3E6jguMGL5b32:b-mb1gtn) ([raw file](https://github.com/cockroachdb/cockroach/blob/d045de79beea7168103800f949eee25e4ecefd0c/pkg/sql/opt/norm/inline_funcs.go#L432)):*
> ```Go
> // TODO(mgartner): We may be able to loosen (4), but there are several
> // difficulties to overcome. We must take care not to inline UDFs with volatile
> // arguments used more than once in the function body. We should also be sure
> ```

[nit] Is this part true? We're allowed to duplicate volatile expressions AFAIK.



_Code quote:_
```Go
// difficulties to overcome. We must take care not to inline UDFs with volatile
// arguments used more than once in the function body. We should also be sure
```
___
*[`pkg/sql/opt/norm/inline_funcs.go` line 443 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/101327#-NSqjwYb3MjhbUHKyUNl:-NSqjwYb3MjhbUHKyUNm:b-tlbssl) ([raw file](https://github.com/cockroachdb/cockroach/blob/d045de79beea7168103800f949eee25e4ecefd0c/pkg/sql/opt/norm/inline_funcs.go#L443)):*
> ```Go
> 	for i := range args {
> 		switch args[i].(type) {
> 		case *memo.VariableExpr, *memo.ConstExpr:
> ```

[nit] Should we allow placeholders as well? And tuples of constant/variable/placeholders? There are a few places where we make checks like this (for example, `IsConstantsAndPlaceholders`) - maybe we should unify the logic.
___
*[`pkg/sql/logictest/testdata/logic_test/udf` line 3443 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/101327#-NSqm4gP1LwBPn_i9_Ag:-NSqm4gP1LwBPn_i9_Ah:b-4q67aw) ([raw file](https://github.com/cockroachdb/cockroach/blob/d045de79beea7168103800f949eee25e4ecefd0c/pkg/sql/logictest/testdata/logic_test/udf#L3443)):*
> ```
> 
> query B
> SELECT f100915((SELECT y FROM (VALUES (10), (20)) y(y) WHERE x=y)) FROM (VALUES (10), (20)) x(x)
> ```

Could you add a case with an expression that has a subquery in it, in addition to this one that directly uses a subquery as argument?

**Review by rharding6373 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101327#-:-NSqzv91BtY7zFGAcQXX:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101327)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/opt/norm/inline_funcs.go` line 432 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/101327#-NSqjOK3E6jguMGL5b31:-NSup9FI4IL1voUisgvr:b7k9h2k) ([raw file](https://github.com/cockroachdb/cockroach/blob/d045de79beea7168103800f949eee25e4ecefd0c/pkg/sql/opt/norm/inline_funcs.go#L432)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Is this part true? We're allowed to duplicate volatile expressions AFAIK.
</blockquote></details>

If you duplicate a volatile argument while inlining, you change the semantics of the UDF. 

For example:

```sql
CREATE FUNCTION double(i INT) RETURNS INT IMMUTABLE LANGUAGE SQL AS $$
  SELECT i + i
$$;

SELECT double((random()*10)::INT);
```

If you inline this UDF and duplicate the volatile argument you'll get something equivalent to:

```sql
SELECT (random()*10)::INT) + (random()*10)::INT;
```

Which no longer has the same meaning. Instead of generating one random number and doubling it, you're generating two different random numbers and adding them together.

Of course, we can be more thoughtful and inline as something like this instead:

```sql
SELECT r + r FROM (SELECT random()) s(r)
```
___
*[`pkg/sql/opt/norm/inline_funcs.go` line 443 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/101327#-NSqjwYb3MjhbUHKyUNl:-NSuzFJFDu5EcZy5AyfC:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d045de79beea7168103800f949eee25e4ecefd0c/pkg/sql/opt/norm/inline_funcs.go#L443)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Should we allow placeholders as well? And tuples of constant/variable/placeholders? There are a few places where we make checks like this (for example, `IsConstantsAndPlaceholders`) - maybe we should unify the logic.
</blockquote></details>

Good idea. Done.
___
*[`pkg/sql/logictest/testdata/logic_test/udf` line 3443 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/101327#-NSqm4gP1LwBPn_i9_Ag:-NSutBIj4cbjsW-10sIF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d045de79beea7168103800f949eee25e4ecefd0c/pkg/sql/logictest/testdata/logic_test/udf#L3443)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Could you add a case with an expression that has a subquery in it, in addition to this one that directly uses a subquery as argument?
</blockquote></details>

Done.

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101327#-:-NSvm6wOCHq9ONsZBEji:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[`pkg/sql/opt/norm/inline_funcs.go` line 432 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/101327#-NSqjOK3E6jguMGL5b31:-NSvkHRb6pKCP2g9T2ef:b-g8mg16) ([raw file](https://github.com/cockroachdb/cockroach/blob/d045de79beea7168103800f949eee25e4ecefd0c/pkg/sql/opt/norm/inline_funcs.go#L432)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

If you duplicate a volatile argument while inlining, you change the semantics of the UDF. 

For example:

```sql
CREATE FUNCTION double(i INT) RETURNS INT IMMUTABLE LANGUAGE SQL AS $$
  SELECT i + i
$$;

SELECT double((random()*10)::INT);
```

If you inline this UDF and duplicate the volatile argument you'll get something equivalent to:

```sql
SELECT (random()*10)::INT) + (random()*10)::INT;
```

Which no longer has the same meaning. Instead of generating one random number and doubling it, you're generating two different random numbers and adding them together.

Of course, we can be more thoughtful and inline as something like this instead:

```sql
SELECT r + r FROM (SELECT random()) s(r)
```
</blockquote></details>

I don't think it should hold up this PR, but the comment in `props/volatility.go` seems to indicate this would be ok. This case seems similar to the one from the discussion [here](https://cockroachlabs.slack.com/archives/C04U1BTF8/p1672858411517479) to me.

**Review by mgartner — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101327#-:-NSw1-TRCi3kFZVDPY1M:b-tlx7ko)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball)

___
*[`pkg/sql/opt/norm/inline_funcs.go` line 432 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/101327#-NSqjOK3E6jguMGL5b31:-NSw-VsV2fUieIjkOPu9:b-78naao) ([raw file](https://github.com/cockroachdb/cockroach/blob/d045de79beea7168103800f949eee25e4ecefd0c/pkg/sql/opt/norm/inline_funcs.go#L432)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

I don't think it should hold up this PR, but the comment in `props/volatility.go` seems to indicate this would be ok. This case seems similar to the one from the discussion [here](https://cockroachlabs.slack.com/archives/C04U1BTF8/p1672858411517479) to me.
</blockquote></details>

I suppose it's a bit of a gray area, and I agree that the rules in `props/volatility.go` may need an an amendment if we want to solidify this guarantee.

But I'm very skeptical of not providing this guarantee. The presence of a function boundary seems like a critical detail. How can you write a robust, bug-free function `func myFunc(i int) { ... }` if the value of `i` can change during execution of the function, by something other than an assignment within the function itself (e.g. `i = 0`)? How can you even predict its behavior?

**Pull request merged**
