### PR TITLE
engine: refine mvcc logic around moving intent timestamps

### PR DESCRIPTION
**Pull request by nvb**
This commit cleans up comments and logic in mvccResolveWriteIntent.

Release note: None

### CODE REVIEW

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33468)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/engine/mvcc.go, line 2217 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33468#-LVdSr939jbKluec1AC0:-LVdSr939jbKluec1AC1:b-uwgxkh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3f1de88fd5e5ea445ded73a1bde2e68220888ba/pkg/storage/engine/mvcc.go#L2217)):*
> ```Go
> 	// after. We treat such intents as uncommitted.
> 	//
> 	// A commit with a newer timestamp than the intent means that our timestamp
> ```

This can't happen any more, right? We removed snapshot isolation and write at the provisional timestamp now, and we can't commit unless the provisional timestamp was the same for all writes. Assuming, of course, we're not in a migration where such things might still be carried out by other nodes.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33468)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/engine/mvcc.go, line 2217 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33468#-LVdSr939jbKluec1AC0:-LVeKo4CAhIWHqit3o3Y:bjz46kd) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3f1de88fd5e5ea445ded73a1bde2e68220888ba/pkg/storage/engine/mvcc.go#L2217)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This can't happen any more, right? We removed snapshot isolation and write at the provisional timestamp now, and we can't commit unless the provisional timestamp was the same for all writes. Assuming, of course, we're not in a migration where such things might still be carried out by other nodes.
</blockquote></details>

I think it can still happen if we successfully refresh a transaction to avoid restarting and laying down all intents again.

**Review by tbg — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33468#-:-LVhThAaCy3qctjJRJ9v:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/storage/engine/mvcc.go, line 2159 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33468#-LVhTBK93yNMHi382O0r:-LVhTBK93yNMHi382O0s:b8mlwnm) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3f1de88fd5e5ea445ded73a1bde2e68220888ba/pkg/storage/engine/mvcc.go#L2159)):*
> ```Go
> 		return false, err
> 	}
> 	// For cases where there's no value corresponding to the key we're
> ```

What do you think about

```go
nextKeyIter := iter
iter = nil // prevent accidental use
```

and use `nextKeyIter` below? Or any other way you can add confidence that we don't accidentally move `iter` in the future.
___
*[pkg/storage/engine/mvcc.go, line 2217 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33468#-LVdSr939jbKluec1AC0:-LVhPGOm-T0sum4vtWu1:bcrflhm) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3f1de88fd5e5ea445ded73a1bde2e68220888ba/pkg/storage/engine/mvcc.go#L2217)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think it can still happen if we successfully refresh a transaction to avoid restarting and laying down all intents again.
</blockquote></details>

Ah, of course. I forgot about refreshs. Worth adding to the comment that this is the only situation in which this happens nowadays.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33468)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @tbg)

___
*[pkg/storage/engine/mvcc.go, line 2159 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33468#-LVhTBK93yNMHi382O0r:-LXPJ0__-hLN14mbKanV:bknib28) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3f1de88fd5e5ea445ded73a1bde2e68220888ba/pkg/storage/engine/mvcc.go#L2159)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

What do you think about

```go
nextKeyIter := iter
iter = nil // prevent accidental use
```

and use `nextKeyIter` below? Or any other way you can add confidence that we don't accidentally move `iter` in the future.
</blockquote></details>

How's that? We were already doing it in one place below.

We could also take a `*Iterator` in `unsafeNextVersion` and nil it out in `unsafeNextVersion`, but that's kind of a strange contract.
___
*[pkg/storage/engine/mvcc.go, line 2217 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33468#-LVdSr939jbKluec1AC0:-LXPI48zBx9x4-XAoEhF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3f1de88fd5e5ea445ded73a1bde2e68220888ba/pkg/storage/engine/mvcc.go#L2217)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Ah, of course. I forgot about refreshs. Worth adding to the comment that this is the only situation in which this happens nowadays.
</blockquote></details>

Done.

**Review by tbg — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33468)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
