### PR TITLE
sql: add SET CLUSTER SETTING wrapper to alter system.settings

### PR DESCRIPTION
**Pull request by dt**
Currently a very thin wrapper around just upserting strings, just to get the various boilerplate and plumbing in place.

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1, 5 of 5 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/set.go, line 104 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14691#-KhNSCGrrb2gQ-_wXBLU:-KhNSCGrrb2gQ-_wXBLV:bas1wwg) ([raw file](https://github.com/cockroachdb/cockroach/blob/de841aff2444118913c6df91bcc7c4a125e46334/pkg/sql/set.go#L104)):*
> ```Go
> 			ctx, "update-setting", p.txn, "DELETE FROM system.settings WHERE name = $1", name,
> 		)
> 		return &emptyNode{}, err
> ```

nit: return here only if err is non-nil, and then return nil at the bottom?

---

*[pkg/sql/set.go, line 106 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14691#-KhNSLwN_wGxAq1_g6N3:-KhNSLwN_wGxAq1_g6N4:bol8dsw) ([raw file](https://github.com/cockroachdb/cockroach/blob/de841aff2444118913c6df91bcc7c4a125e46334/pkg/sql/set.go#L106)):*
> ```Go
> 		return &emptyNode{}, err
> 	case 1:
> 		// TODO(dt): validate and properly encode str according to type.
> ```

seems important enough to do now

---

*[pkg/sql/set.go, line 122 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14691#-KhNSSEqcCQ78la41i_2:-KhNSSEqcCQ78la41i_3:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/de841aff2444118913c6df91bcc7c4a125e46334/pkg/sql/set.go#L122)):*
> ```Go
> 
> func (p *planner) toSettingString(raw parser.Expr) (string, error) {
> 	// TODO(dt): typecheck and handle according to setting's desired type.
> ```

ditto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14691)*

**Comment by dt** [comment]
Review status: 1 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/set.go, line 104 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14691#-KhNSCGrrb2gQ-_wXBLU:-KhNUVvsXoR8o1k-YXrv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/de841aff2444118913c6df91bcc7c4a125e46334/pkg/sql/set.go#L104)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

nit: return here only if err is non-nil, and then return nil at the bottom?
</blockquote></details>

Done.

---

*[pkg/sql/set.go, line 106 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14691#-KhNSLwN_wGxAq1_g6N3:-KhNSnwLWWHjD_6bufA3:b-xlpdgn) ([raw file](https://github.com/cockroachdb/cockroach/blob/de841aff2444118913c6df91bcc7c4a125e46334/pkg/sql/set.go#L106)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

seems important enough to do now
</blockquote></details>

i've got it queued up locally for a fast follow, but obviously it depends on the registry in #14688, to lookup the types to do the validation, plus I wanted to keep individual changes a manageable size.

---

*[pkg/sql/set.go, line 122 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14691#-KhNSSEqcCQ78la41i_2:-KhNTKRyr88d_Og1bHe9:b-rqxvo7) ([raw file](https://github.com/cockroachdb/cockroach/blob/de841aff2444118913c6df91bcc7c4a125e46334/pkg/sql/set.go#L122)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14691)*

**Comment by tamird** [comment]
Reviewed 7 of 7 files at r4, 5 of 5 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/set.go, line 106 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14691#-KhNSLwN_wGxAq1_g6N3:-KhOUt3yszipHc87Mu7m:b-z8amb4) ([raw file](https://github.com/cockroachdb/cockroach/blob/de841aff2444118913c6df91bcc7c4a125e46334/pkg/sql/set.go#L106)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

i've got it queued up locally for a fast follow, but obviously it depends on the registry in #14688, to lookup the types to do the validation, plus I wanted to keep individual changes a manageable size.
</blockquote></details>

Understood, and yet I think it should go with this =/

---

*[pkg/sql/set.go, line 113 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/14691#-KhOUqnm06P8d3TxXZdA:-KhOUqnnYLq2cmkFEOJ7:b32vig) ([raw file](https://github.com/cockroachdb/cockroach/blob/324626a66e02e74ceb89c859e5b42e59e4372603/pkg/sql/set.go#L113)):*
> ```Go
> 		}
> 		upsertQ := "UPSERT INTO system.settings (name, value, lastUpdated, valueType) VALUES ($1, $2, NOW(), $3)"
> 		if _, err = ie.ExecuteStatementInTransaction(
> ```

:=

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14691)*

**Comment by dt** [comment]
Review status: 1 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/set.go, line 106 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14691#-KhNSLwN_wGxAq1_g6N3:-KhTtXNSg6DvJVGtsMuS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/de841aff2444118913c6df91bcc7c4a125e46334/pkg/sql/set.go#L106)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Understood, and yet I think it should go with this =/
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14691)*

**Comment by dt** [comment]
Review status: 1 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/set.go, line 113 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/14691#-KhOUqnm06P8d3TxXZdA:-KhTwZmN7EfP2ceSv1DI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/324626a66e02e74ceb89c859e5b42e59e4372603/pkg/sql/set.go#L113)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

:=
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14691)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r7, 5 of 5 files at r8, 2 of 2 files at r9, 3 of 3 files at r10.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/set.go, line 99 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/14691#-KhUpuRWlR1fqd3oExyU:-KhUpuRXEALYw936Se1-:b-i2lper) ([raw file](https://github.com/cockroachdb/cockroach/blob/2239d7a88153bd70184f141ea34bf335a7ab80af/pkg/sql/set.go#L99)):*
> ```Go
> 	typ, ok := settings.TypeOf(name)
> 	if !ok {
> 		return nil, errors.Errorf("unknown cluster settings %q", name)
> ```

setting

'%s'

---

*[pkg/sql/set.go, line 142 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/14691#-KhUqQ4kg0jQUm5y6h9y:-KhUqQ4kg0jQUm5y6h9z:b-fqwa11) ([raw file](https://github.com/cockroachdb/cockroach/blob/2239d7a88153bd70184f141ea34bf335a7ab80af/pkg/sql/set.go#L142)):*
> ```Go
> 			return "", err
> 		}
> 		encoded, err := f(d)
> ```

`return f(d)`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14691#-:-KhUq_Dk_YUYOmCyuTWH:bnfp4nl)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/set.go, line 99 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/14691#-KhUpuRWlR1fqd3oExyU:-KhUrtuvVKcswwg_4Vg9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2239d7a88153bd70184f141ea34bf335a7ab80af/pkg/sql/set.go#L99)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

setting

'%s'
</blockquote></details>

Done.

---

*[pkg/sql/set.go, line 142 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/14691#-KhUqQ4kg0jQUm5y6h9y:-KhUs8FAlvyF0pyRShvZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2239d7a88153bd70184f141ea34bf335a7ab80af/pkg/sql/set.go#L142)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

`return f(d)`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14691)*

**Comment by dt** [comment]
TFTR!

---

Review status: 8 of 9 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14691#-:-KhUsARb14Pp5TbOt2eN:b-814g8k)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14691)*

**Pull request merged**
