### PR TITLE
add log to enhance debug

### PR DESCRIPTION
**Pull request by xiaoyulei**
[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3263)

### CODE REVIEW

**Comment by bdarnell** [comment]
In general, we shouldn't both log an error and return it, because our caller will also do something with the error. These errors should be logged by the caller of `EndTransaction`, not `EndTransaction` itself.

**Comment by YuleiXiao** [comment]
But the caller also do not log the error.
And when I debug it, I found there are so many errors maybe returned in  ```EndTransaction```. If only caller log it, it is not easy to debug.

**Comment by bdarnell** [comment]
Hmm. Yeah, I guess this is kind of a special case. EndTransaction's error goes all the way back to the client, which will probably retry without logging anything because EndTransaction can fail for many "expected" reasons. But we never expect failures in the commit triggers so if they happen we should make sure they are visible. 

Move the log down to line 507 next to @tschottdorf 's comment about `ReplicaCorruptionError`.

**Comment by YuleiXiao** [comment]
@bdarnell I have move it. 
PTAL

**Comment by bdarnell** [comment]
LGTM

**Pull request merged**
