### PR TITLE
use opentracing-go instead of util/tracer

### PR DESCRIPTION
**Pull request by tbg**
Reduce util/tracer to a light wrapper around opentracing-go
(with `standardtracer` for now). This is mostly a brute-force
change which does a direct translation. In particular, most
invocations of `defer trace.Epoch("xxx")()` have simply been
replaced by `trace.LogEvent("xxx")`. This constitutes a loss
of fidelity, but a fidelity we haven't (recently) used and
which can be regained by introducing more LogEvent calls.

The hook-up to `net/trace` has also been removed. It could
be reinstated as well, but that would require more wrapping
than it's worth at this point. We can get this back if we want
it in the future (and we may well want to).
In tests, we still spit the trace info to stderr (though in a far
more trivial format). That should be enough to keep anyone
who uses it for debugging work happy for now. When not in
tests, traces are silently discarded for now.

This sets the stage for more of the "actual" work in #4067:
Work on performance goals, and actually do distributed tracing.

Review commit-by-commit is advised to skip lightly over the
more mechanical portions.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4079)

### CODE REVIEW

**Comment by vivekmenezes** [comment]
LGTM

**Comment by petermattis** [comment]
Reviewed 22 of 23 files at r1, 22 of 22 files at r2, 8 of 8 files at r3, 8 of 8 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[kv/dist_sender.go, line 231 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4079#-K9XphHI2DT4sgenN94H:-K9XphHI2DT4sgenN94I:1789205034) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bbc344d5b2951ebe7021d9a360ab7f9bff9420e/kv/dist_sender.go#L231)):*
Seems like `NilTrace` should be renamed `NilSpan`.

---

*[util/tracing/tracer.go, line 32 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4079#-K9XqCwjUTirlNElV012:-K9XqCwjUTirlNElV013:-1596612312) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d21a6d1917fea960451576b19b302ce3dd731e/util/tracing/tracer.go#L32)):*
So other comment about the receiver not needing to be a pointer.

---

*[util/tracing/tracer.go, line 84 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4079#-K9Xq3KzM9iXZNxeiI4H:-K9Xq3L-PrJqjBRcniTx:1044534841) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d21a6d1917fea960451576b19b302ce3dd731e/util/tracing/tracer.go#L84)):*
I'm not clear on why this isn't returning `dummySpan`. What is the purpose of going through `SpanFromContext` here?

---

*[util/tracer/tracer.go, line 33 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4079#-K9Xp4lbUzW7CoLtGDEu:-K9Xp4lbUzW7CoLtGDEv:-1991960975) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b1c9be8756f11bf43a3a6623d86882edf131f0f/util/tracer/tracer.go#L33)):*
`s/recorder/(*nilRecorder)(nil)/g`

Curious why the methods on`nilRecorder` and `nilSpan` take a pointer. I would think you could do:

```
func (nilRecorder) RecordSpan(...)
```

And then use `nilRecorder{}` as the implementation of the `opentracing.Recorder` interface.

---

*[util/tracer/tracer.go, line 55 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4079#-K9Xoy0KJC8jlUBbnvPS:-K9Xoy0LiwZtgZhUqcuh:1360978137) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b1c9be8756f11bf43a3a6623d86882edf131f0f/util/tracer/tracer.go#L55)):*
`s/span/(*nilSpan)(nil)/g`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4079)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[kv/dist_sender.go, line 231 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4079#-K9XphHI2DT4sgenN94H:-K9XxGGbpIrHkpf0pEkR:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bbc344d5b2951ebe7021d9a360ab7f9bff9420e/kv/dist_sender.go#L231)):*
Done.

---

*[util/tracing/tracer.go, line 33 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4079#-K9Xp4lbUzW7CoLtGDEu:-K9Y7XjTk_v3Bar206kz:-1092863953) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b1c9be8756f11bf43a3a6623d86882edf131f0f/util/tracing/tracer.go#L33)):*
no specific reason. I'm used to the pointer form in situations in which you want the nil object to no-op and a non-nil object to actually carry out actions. But there's no such distinction here. Made your suggested change.

---

*[util/tracing/tracer.go, line 55 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4079#-K9Xoy0KJC8jlUBbnvPS:-K9Xyi_wFu5CxFqy-1qS:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b1c9be8756f11bf43a3a6623d86882edf131f0f/util/tracing/tracer.go#L55)):*
Done.

---

*[util/tracing/tracer.go, line 84 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4079#-K9Xq3KzM9iXZNxeiI4H:-K9XynIQHIX5FYTbzm7i:1805958312) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6d21a6d1917fea960451576b19b302ce3dd731e/util/tracing/tracer.go#L84)):*
No purpose, just not updated in later iteration. Changed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4079)*

**Comment by petermattis** [comment]
LGTM

---

Review status: 26 of 32 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4079#-:-K9YaApQjshEcb1GLwcr:676834233)*

**Comment by bdarnell** [comment]
LGTM

---

Review status: 26 of 32 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4079#-:-K9YbbMAi30q0uQMDSKS:676834233)*

**Comment by petermattis** [comment]
LGTM

---

Review status: 23 of 36 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4079#-:-K9bLAOlbdBGj9ovqm1h:676834233)*

**Pull request merged**
