### PR TITLE
vendor: switch to pinning more deps

### PR DESCRIPTION
**Pull request by dt**
This switches to pinning many of our important / direct dependencies to make it easier to make more isolated dependency changes.

As discussed in #13138, this is because glide's re-resolution of all deps to latest in absence of a pin makes it otherwise hard to make smaller, isolated changes.

This also updates a few mostly uninteresting deps -- various docker libs, google cloud libs, and linters being the bulk of them.

Fixes a few new lint violations from unneeded capacity args to make.

https://github.com/GoogleCloudPlatform/google-cloud-go/compare/c96c4486...ce650573
https://github.com/Microsoft/go-winio/compare/24a3e3d3...fff283ad
https://github.com/Sirupsen/logrus/compare/9b48ece7...3f603f49
https://github.com/backtrace-labs/go-bcd/compare/389d108b...4ad9137a
https://github.com/docker/distribution/compare/7dba4276...b1993c95
https://github.com/docker/go-connections/compare/eb315e36...7da10c8c
https://github.com/docker/go-units/compare/e30f1e79...0dadbb03
https://github.com/dustin/go-humanize/compare/904a4949...7a41df00
https://github.com/elastic/gosigar/compare/171a3c9e...b49e01eb
https://github.com/golang/lint/compare/206c0f02...5295072e
https://github.com/google/go-github/compare/dcda0b96...27c7c32b
https://github.com/google/go-querystring/compare/9235644d...53e6ce11
https://github.com/mattn/go-runewidth/compare/737072b4...14207d28
https://github.com/mattn/goveralls/compare/61ac1a6b...8482d0eb
https://github.com/opencontainers/go-digest/compare/a6d0ee40...aa2ec055
https://github.com/opentracing/opentracing-go/compare/5e5abf83...6edb4867
https://github.com/spf13/pflag/compare/25f8b5b0...9ff6c692
https://github.com/golang/oauth2/compare/314dd2c0...4464e784
https://github.com/golang/sys/compare/d75a5265...7a6e5648
https://github.com/golang/text/compare/44f4f658...dafb3384
https://github.com/golang/tools/compare/354f9f8b...19c96be7
https://github.com/google/google-api-go-client/compare/025e50fd...3d017632
https://github.com/golang/appengine/compare/8758a385...2e4a801b
https://github.com/dominikh/go-tools/compare/287365bf...401755ce

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13471)

### CODE REVIEW

**Comment by tamird** [comment]
glide is so terrible

LGTM

we need some automation to deal with this new level of schleppery

**Comment by tamird** [comment]
> google/btree@316fb6d...925471a

appears to have gone backwards: https://github.com/google/btree/compare/925471ac...316fb6d3

same with crypto: https://github.com/golang/crypto/compare/1351f936...c3b1d0d6

**Comment by dt** [comment]
@tamird indeed (via etcd's preference)... do we care about using specific revision of either of those though?

**Comment by dt** [comment]
@tamird added those pins and added bump of glide version to pick up submodule handling correctness fix.

**Comment by tamird** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[glide.yaml, line 10 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13471#-KcUlCwcaN7WGYR5e9gp:-KcUlCwcaN7WGYR5e9gq:b-fwfd1c) ([raw file](https://github.com/cockroachdb/cockroach/blob/29dbb1a9dba9153cc6818c8cb8832427d1d34e1f/glide.yaml#L10)):*
> ```YAML
> - package: github.com/docker/docker
>   version: 7248742ae7127347a52ab9d215451c213b7b59da
> # Pins to prevent unintended version changes to libs we care about when adding/
> ```

is this comment the same as the one above?

---

*[build/checkdeps.sh, line 7 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13471#-KcUlT3Ak8r6ws26InHK:-KcUlT3Ak8r6ws26InHL:b-k7phlc) ([raw file](https://github.com/cockroachdb/cockroach/blob/29dbb1a9dba9153cc6818c8cb8832427d1d34e1f/build/checkdeps.sh#L7)):*
> ```Shell
> 
> echo "installing desired glide version"
> go get github.com/Masterminds/glide
> ```

why not `go get -u`? in particular, why does this differ from the readme?

---

*[pkg/ts/query_test.go, line 691 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13471#-KcUlb6LTqjwBwY8JnxC:-KcUlb6LTqjwBwY8JnxD:bpdilx1) ([raw file](https://github.com/cockroachdb/cockroach/blob/29dbb1a9dba9153cc6818c8cb8832427d1d34e1f/pkg/ts/query_test.go#L691)):*
> ```Go
> 	// Construct an expected result for comparison.
> 	var expectedDatapoints []tspb.TimeSeriesDatapoint
> 	expectedSources := make([]string, 0)
> ```

why isn't this `var expectedSources []string`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13471)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[glide.yaml, line 10 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13471#-KcUlCwcaN7WGYR5e9gp:-KcV-iQHpJWwa8lxgxsq:b2ni8op) ([raw file](https://github.com/cockroachdb/cockroach/blob/29dbb1a9dba9153cc6818c8cb8832427d1d34e1f/glide.yaml#L10)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

is this comment the same as the one above?
</blockquote></details>

no?

---

*[build/checkdeps.sh, line 7 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13471#-KcUlT3Ak8r6ws26InHK:-KcV-p9GXcS2jdoDB_m3:bc1u0lt) ([raw file](https://github.com/cockroachdb/cockroach/blob/29dbb1a9dba9153cc6818c8cb8832427d1d34e1f/build/checkdeps.sh#L7)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why not `go get -u`? in particular, why does this differ from the readme?
</blockquote></details>

Added `-u`.  IIRC currently README doesn't have any install advice (I can add a note since I already have a branch where i've been working on clarifying that section particularly w.r.t. submodules).

---

*[pkg/ts/query_test.go, line 691 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13471#-KcUlb6LTqjwBwY8JnxC:-KcV0yEdkuFDuwrQadwK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/29dbb1a9dba9153cc6818c8cb8832427d1d34e1f/pkg/ts/query_test.go#L691)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why isn't this `var expectedSources []string`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13471)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[glide.yaml, line 10 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13471#-KcUlCwcaN7WGYR5e9gp:-KcVLSTNNgsb6vtpXByU:bhngauc) ([raw file](https://github.com/cockroachdb/cockroach/blob/29dbb1a9dba9153cc6818c8cb8832427d1d34e1f/glide.yaml#L10)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

no?
</blockquote></details>

Oh, I see.

---

*[build/checkdeps.sh, line 8 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13471#-KcV3ssrwLj1B3Bx6R_8:-KcV3ssrwLj1B3Bx6R_9:bm6sums) ([raw file](https://github.com/cockroachdb/cockroach/blob/57f0c3dacb5e807400de5bcd88809eb9f4f9dc03/build/checkdeps.sh#L8)):*
> ```Shell
> echo "installing desired glide version"
> go get -u github.com/Masterminds/glide
> # ab0972eb merged our fix for correctly vendoring submodule contents.
> ```

you can remove this and the next line, I think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13471)*

**Comment by dt** [comment]
Review status: 13 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[build/checkdeps.sh, line 8 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13471#-KcV3ssrwLj1B3Bx6R_8:-KcW5FjAIsLG10MD3B3s:b-j2tss0) ([raw file](https://github.com/cockroachdb/cockroach/blob/57f0c3dacb5e807400de5bcd88809eb9f4f9dc03/build/checkdeps.sh#L8)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

you can remove this and the next line, I think.
</blockquote></details>

Eh, I'd rather pin it to a known version since upstream does break at times, unless you feel strongly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13471)*

**Comment by dt** [comment]
Review status: 13 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/ts/query_test.go, line 691 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13471#-KcW61JAIgUoxvGwt8gR:-KcW61JAIgUoxvGwt8gS:b4r8lem) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a3061628a3d0a069098688cf255b4b513d38053/pkg/ts/query_test.go#L691)):*
> ```Go
> 	// Construct an expected result for comparison.
> 	var expectedDatapoints []tspb.TimeSeriesDatapoint
> 	expectedSources := make([]string, 0)
> ```

Turns out it is to make `reflect.DeepEqual` happy https://play.golang.org/p/GUQ1A-SOEp

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13471)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[build/checkdeps.sh, line 8 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13471#-KcV3ssrwLj1B3Bx6R_8:-KcXVtgkdhnT8ofcewdK:beleewv) ([raw file](https://github.com/cockroachdb/cockroach/blob/57f0c3dacb5e807400de5bcd88809eb9f4f9dc03/build/checkdeps.sh#L8)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Eh, I'd rather pin it to a known version since upstream does break at times, unless you feel strongly.
</blockquote></details>

The instructions here should match what's in the readme, that's all I'm saying.

You should probably use `go get -d -u` here and in the readme.

---

*[pkg/ts/query_test.go, line 691 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13471#-KcW61JAIgUoxvGwt8gR:-KcXW44PUHuwzKPjLa3i:b2nhktp) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a3061628a3d0a069098688cf255b4b513d38053/pkg/ts/query_test.go#L691)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Turns out it is to make `reflect.DeepEqual` happy https://play.golang.org/p/GUQ1A-SOEp
</blockquote></details>

OK.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13471)*

**Comment by dt** [comment]
Review status: 12 of 14 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[build/checkdeps.sh, line 8 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13471#-KcV3ssrwLj1B3Bx6R_8:-KcYhrdbF2rBEKw24OgC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/57f0c3dacb5e807400de5bcd88809eb9f4f9dc03/build/checkdeps.sh#L8)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

The instructions here should match what's in the readme, that's all I'm saying.

You should probably use `go get -d -u` here and in the readme.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13471)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13471)*

**Pull request merged**
