### PR TITLE
sqlccl: support into_db in IMPORT

### LINKED ISSUE #18876: sqlccl: verify db exists when into_db is used with IMPORT CSV
https://github.com/cockroachdb/cockroach/blob/14c5215987e857d881c46749dbcf42f1a724ae1d/pkg/ccl/sqlccl/csv.go#L922

### PR DESCRIPTION
**Pull request by madelynnblue**
Fixes #18876

### CODE REVIEW

**Review by dt — APPROVED** [review]

**Comment by mjibson** [comment]
@bdarnell thoughts about cherry picking this into 1.1? I'm fine to leave it out, because it's easy enough to work around by setting your session database. (And, it's not that the syntax was allowed but ignored: it will still error in 1.1 if this option is present, so users won't be confused.)

**Comment by bdarnell** [comment]
This is about parity between IMPORT and RESTORE, right? Let's leave it out of 1.1 since the feature is still marked experimental anyway.

**Comment by mjibson** [comment]
Yes. Fine with me.

**Comment by dt** [comment]
@bdarnell @mjibson huh, I might be coming around to pro-cherrypick on this one: the error message if the session DB is empty says to supply the `into_db` option... which then fails, so it ends up looking kinda like we have a bug. We could just patch the error message, but given that it comes from a reused helper, cherrypicking this might be just as conservative.

**Pull request merged**
