### PR TITLE
roachtest: fix gorm bug in overriding tests_test.go

### PR DESCRIPTION
**Pull request by healthy-pod**
Previously, gorm called repeatRunE to override tests_test.go
content. The last two arguments in the variadic function repeatRunE
are `operation string` which describes what the command will do
and `args ...string` which is the command to run. This call to repeatRunE
omits `args` and only passes `operation` which results in an empty command,
which (in the roachprod world) means an interactive SSH session.

This didn't previously fail during build because `repeatRunE` is a
variadic function (i.e. len(args) can be 0). It also didn't previously fail
due to the interactive SSH session because we were calling roachprod using
the external binary, not the library. To start an interactive SSH session,
roachprod calls syscall.Exec which invokes the execve(2) system call.
This system call causes the program that is currently being run (i.e. roachtest)
to be replaced with a new program. Previously, "the program that is currently
being run" was the roachprod binary (`roachprod run`).

This patch fixes that by adding args to the call. It is also worth noting that
roachtest should never start an interactive SSH session, so in another change I
will add a check that errors out if `len(args) == 0`.

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
Wait, but the old code never did anything, right? Instead of fixing it, do you want to fix it & leave it out? It's clearly not necessary and maybe you want to avoid changing behavior. Perhaps @rafiss can stop by and let you know what to do. In any case, hilarious find.

**Review by otan — APPROVED** [review]
repeatRunE and RunE are very easy to mistakes on -- one requires the "description" arg and one does not!

I do wonder whether it makes sense to type the command arg so it's clear, e.g.

```
repeatRunE(ctx, t, c, node, newRunDescription("doing blah"), newCmd("a", "b"))
```

hurts writeability but means this class of bugs won't happen.

i do think the tests_test.go is important, however - if the test passed before it was by fluke.

**Comment by healthy-pod** [comment]
I agree and also roachtests shouldn't be allowed to pass empty args eitherways because that starts an interactive ssh session. I will change the variadic implementation to a typed implementation where args is just a `[]string` and propagate this change to the tests using repeatRunE.
TFTR!

**Review by rafiss — APPROVED** [review]
lgtm! i think this didn't fail before since gorm auto-skips some tests if it hasn't connected to the DB

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74086)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @healthy-pod, @RichardJCai, and @tbg)

___
*[pkg/cmd/roachtest/tests/gorm.go, line 124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74086#-MrQDFKT3sibq3lH6qDh:-MrQDFKT3sibq3lH6qDi:b-szz4sh) ([raw file](https://github.com/cockroachdb/cockroach/blob/97476a7532a1e7a9dc56b90965bd13645763c1d6/pkg/cmd/roachtest/tests/gorm.go#L124)):*
> ```Go
> 			ctx,
> 			node,
> 			fmt.Sprintf(`cd %s && GORM_DIALECT="postgres"
> ```

actually, i think we can remove the tests_test step entirely if we pass in 
```
GORM_DIALECT="postgres" GORM_DSN="user=root password= dbname=gorm host=localhost port=26257 sslmode=disable"
```

(and the `PG*` env vars can be removed)


if you aren't up for making this change though, no worries. we can do it later.

**Comment by healthy-pod** [comment]
> actually, i think we can remove the tests_test step entirely

Done

**Review by rafiss — APPROVED** [review]
lgtm!

**Comment by healthy-pod** [comment]
TFTR!

bors r=[rafiss,otan]

**Pull request merged**
