### PR TITLE
ui: Fix integration tests

### LINKED ISSUE #42365: webui: ui-test flaky
See for example https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=1585634&_focus=1458

```
38]
[Test web UI] HeadlessChrome 78.0.3904 (Linux 0.0.0): Executed 130 of 320 SUCCESS (0 secs / 3.06 secs)
[11:56:38]
[Test web UI]  [1A [2KHeadlessChrome 78.0.3904 (Linux 0.0.0) Query Management Saga integration tests AUTO_REFRESH/STOP_AUTO_REFRESH action sets inRunning flag on reducer when query is running. FAILED
[11:56:38]
[Test web UI] 	AssertionError: expected 2 to equal 1
[11:56:38]
[Test web UI] 	    at src/redux/queryManager/saga.spec.ts:20980:34
[11:56:38]
[Test web UI] HeadlessChrome 78.0.3904 (Linux 0.0.0): Executed 131 of 320 (1 FAILED) (0 secs / 3.079 secs)
[11:56:38]
[Test web UI]  [1A [2KWARN: '[WARNING]:', 'Saga exceeded async timeout of 250ms'
[11:56:38]
[Test web UI] HeadlessChrome 78.0.3904 (Linux 0.0.0): Executed 131 of 320 (1 FAILED) (0 secs / 3.079 secs)
[11:56:39]
[Test web UI]  [1A [2KWARN: '[WARNING]:', 'Saga exceeded async timeout of 250ms'
[11:56:39]
[Test web UI] HeadlessChrome 78.0.3904 (Linux 0.0.0): Executed 131 of 320 (1 FAILED) (0 secs / 3.079 secs)
```

### PR DESCRIPTION
**Pull request by koorosh**
Two integration tests failed in conjunction because of one test
did not execute at all (did not have return value) and it caused
some side effect on next test.

In addition used 'silentRun' to prevent unnecessary warnings in logs.

Resolves: #42365

Release note: None

### CODE REVIEW

**Review by nathanstilwell — APPROVED** [review]
LGTM. Nice catch

**Comment by nathanstilwell** [comment]
bors merge

**Comment by piyush-singh** [comment]
hmmm @nathanstilwell looks like this didn't merge and is stuck in the bors queue?

**Comment by jordanlewis** [comment]
"bors merge" doesnt do anything. You are looking for bors r+.

**Comment by nathanstilwell** [comment]
@jordanlewis Are we not using [this](https://bors.tech/documentation/)
> bors merge | Equivalent to bors r+

**Comment by jordanlewis** [comment]
Huh 🤔 maybe that's a newer version? My mistake, I didn't think `bors merge` worked (and I don't think it does in our repo) but it looks like you are right that it is documented!

**Pull request merged**
