### PR TITLE
vendor: bump Pebble to 59007c613a66

### PR DESCRIPTION
**Pull request by nicktrav**
```
59007c61 sstable: consolidate checksum types
17635b0a *: address staticcheck lints
11823273 *: address staticcheck lint check U1000
807abfe8 *: address staticcheck lint check S1039
d24dd342 all: remove some unused code
3bdca93a sstable: clarify comment on checksum input
926d23e9 pebble: remove comment related to batching from the table cache
0a6177ae db: tweak ErrClosed documentation
ecc685b2 db: expose facility for retrieving batch count
b2eb88a7 sstable: remove unused rawBlockIter err field
```

Release note: None.

### CODE REVIEW

**Review by jbowens — COMMENTED** [review]
> ecc685b2 db: expose facility for retrieving batch count

Heads up that I think this commit will require a code change in some (one?) places in pkg/storage. `pebble.NewBatchReader` now returns another return value.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71405#-:-MlkFKRb46qRSxEagtLK:b-raewjz)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by nicktrav — COMMENTED** [review]
Ah yep. Just caught it. Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71405#-:-MlkG_u7BXYj-gLM2Gte:be9rs95)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by nicktrav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71405)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/batch.go, line 127 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71405#-MlkJBun1tAnJeGG5TRF:-MlkJBun1tAnJeGG5TRG:bcuvix9) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bb62b29b5aa92f577d3e011c11d4ab2e75b65fd/pkg/storage/batch.go#L127)):*
> ```Go
> 	}
> 	r, c := pebble.ReadBatch(repr)
> 	if c > math.MaxInt32 {
> ```

@jbowens - looks like we were just casting before, so I added a check. Not sure if it's possible in practice to overflow, and can remove if obsolete.

**Review by jbowens — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71405#-:-MllRcswCia0wLW7YwAY:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by nicktrav** [comment]
bors r=jbowens

**Pull request merged**
