### PR TITLE
exec: reset the columnarizer's internal batch

### PR DESCRIPTION
**Pull request by yuzefovich**
The columnarizer "owns" a batch, but it is never reset (namely,
selection vector can remain unset).

Release note: None

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
:lgtm: nice catch, but how can we test this? Can you add a simple unit test? Is there something we can do more holistically?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40246#-:-LnJh5j3-EqbEoCSdxhg:b-yum1i5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Review by yuzefovich — COMMENTED** [review]
I added a unit test for this particular case. Also, I didn't just "notice" this, I think I ran into this problem (or noticed it) while debugging issues with bytes when types are randomized on testing operators against processors.

I think in the short term, I'll manually go over all calls to `NewMemBatch` and find all operators that own batches and make sure that all of them reset those.

But the general solution is maybe to have that batch allocator that we have talked about but actually make it responsible for both allocating and "giving out" the batches (i.e. it will be the only place that stores the batches internally). Then each operator will have an ID, and the allocator will actually allocate the batch on the first call from the operator, but on all consequent it will reset the already allocated batch and return it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40246#-:-LnKKR7cBzULUCQbWV8z:bn9jpiq)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by yuzefovich — COMMENTED** [review]
I think I found a few other places where the reset was missing (also, a few places where we might want to be on the safe side). PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40246#-:-LnKQVTE8NaSbt_GxtV-:b-nn78cq)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by jordanlewis — APPROVED** [review]
:lgtm:

I very much agree with your idea about the batch allocator, or some abstraction that manages this problem for us. Please keep thinking about it. Cleanups in this area seem like a good idea.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40246#-:-LnL3ZqG1Mzghvof8umu:b-e1klk2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/distsqlrun/columnarizer_test.go, line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40246#-LnL43jy9B36hj2gv2Ch:-LnL43jy9B36hj2gv2Ci:b-hosv1o) ([raw file](https://github.com/cockroachdb/cockroach/blob/39fddf8499327bf1f4d88b01b615859c88686e22/pkg/sql/distsqlrun/columnarizer_test.go#L28)):*
> ```Go
> 
> func TestColumnarizerResetsInternalBatch(t *testing.T) {
> 	defer leaktest.AfterTest(t)
> ```

Needs a trailing (), according to the linter

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40246#-:-LnNTS0kA3Ak8thyD0iT:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis)

___
*[pkg/sql/distsqlrun/columnarizer_test.go, line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40246#-LnL43jy9B36hj2gv2Ch:-LnNTQR855K3GwPubl0E:bo3vl6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/39fddf8499327bf1f4d88b01b615859c88686e22/pkg/sql/distsqlrun/columnarizer_test.go#L28)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Needs a trailing (), according to the linter
</blockquote></details>

Thanks, done.

**Pull request merged**
