### PR TITLE
schemachanger: add support for discarding subzones

### LINKED ISSUE #133158: schemachanger: support configure zone discard for subzone configs
This issue tracks our progress of supporting zone configs in declarative schema changer; in particular, this tracks support for `ALTER { INDEX | PARTITION } ... CONFIGURE ZONE DISCARD` in the declarative schema changer.

Jira issue: CRDB-43482

Epic CRDB-31473

### PR DESCRIPTION
**Pull request by annrpom**
### schemachanger: fix discards for explicit txns
Previously, discarding a zone config on an object in an
explicit transaction would only discard the latest (categorized by
highest seq num) element associated with it. This would mean for the
following scenario:
```
BEGIN;
ALTER TABLE t CONFIGURE ZONE USING num_replicas = 11;
ALTER TABLE t CONFIGURE ZONE USING num_replicas = 12;
ALTER TABLE t CONFIGURE ZONE DISCARD;
COMMIT;
```
The discard would only discard the element with a replication factor of 12,
leaving us with a table with a rep. factor of 11.

This patch ensures we clean up all references of an element when
discarding.

Epic: none
Release note: None

---
### schemachanger: add support for discarding subzones
This patch adds support for discarding a subzone config in the
DSC.

Fixes: https://github.com/cockroachdb/cockroach/issues/133158
Epic: none

Release note: None

### CODE REVIEW

**Review by fqazi — APPROVED** [review]
Great work @annrpom, I had some very minor comments.

:lgtm: 

> Reviewed 26 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134826#-:-OCErKyw1qt-9P2nV3bH:b-zhqvft)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @annrpom)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/database_zone_config.go` line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134826#-OCEqdEm5TaEYmidnH8S:-OCEqdEm5TaEYmidnH8T:bhics04) ([raw file](https://github.com/cockroachdb/cockroach/blob/739f490fdb0cdf8e6c4972c843fb1442a0acecf1/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/database_zone_config.go#L49)):*
> ```Go
> ) ([]scpb.Element, []scpb.Element) {
> 	var elems []scpb.Element
> 	if dzo.seqNum > 0 {
> ```

Maybe a comment for clarity, but I think this says that all past IDs are dropped. Could we just adjust the loop to do this for us...

```for i :=0; i < max(dzo.seqNum), 1), ;i++```
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/named_range_zone_config.go` line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134826#-OCEqrh8CRXD4ypm8-Hy:-OCEqrh8CRXD4ypm8-Hz:b-dv925x) ([raw file](https://github.com/cockroachdb/cockroach/blob/739f490fdb0cdf8e6c4972c843fb1442a0acecf1/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/named_range_zone_config.go#L47)):*
> ```Go
> 	_ BuildCtx,
> ) ([]scpb.Element, []scpb.Element) {
> 	var elems []scpb.Element
> ```

Similar comment here

**Review by annrpom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134826)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @fqazi)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/database_zone_config.go` line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134826#-OCEqdEm5TaEYmidnH8S:-OCJqDeCCJnGTw-QmDgM:bylwcvh) ([raw file](https://github.com/cockroachdb/cockroach/blob/739f490fdb0cdf8e6c4972c843fb1442a0acecf1/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/database_zone_config.go#L49)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Maybe a comment for clarity, but I think this says that all past IDs are dropped. Could we just adjust the loop to do this for us...

```for i :=0; i < max(dzo.seqNum), 1), ;i++```
</blockquote></details>

done -- i ended up using a `b.QueryByID(dzo.getTargetID()).FilterDatabaseZoneConfig().ForEach`
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/named_range_zone_config.go` line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134826#-OCEqrh8CRXD4ypm8-Hy:-OCJqQRw6iXPkhHDCLlI:b57ke2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/739f490fdb0cdf8e6c4972c843fb1442a0acecf1/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/named_range_zone_config.go#L47)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Similar comment here
</blockquote></details>

done -- similar to above

**Review by fqazi — APPROVED** [review]
Great work @annrpom 

> Reviewed 4 of 65 files at r3, 12 of 59 files at r5, 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134826#-:-OCYnXvE9iazhwRItKG4:b-l6kw50)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by annrpom** [comment]
tftr!

bors r+

**Pull request merged**
