### PR TITLE
cli: simplify output assertion in TestUnavailableZip

### LINKED ISSUE #106961: cli: TestUnavailableZip failed
cli.TestUnavailableZip [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/10948879?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/10948879?buildTab=artifacts#/) on master @ [9187485233337c7d73d0279e6a6f3fe8c53beec7](https://github.com/cockroachdb/cockroach/commits/9187485233337c7d73d0279e6a6f3fe8c53beec7):

```
=== RUN   TestUnavailableZip
    test_log_scope.go:167: test logs captured to: /artifacts/tmp/_tmp/28eeeeded7900e479eb7557c1bfd2784/logTestUnavailableZip4000005657
*
* ERROR: test tenant requested by configuration, but code organization prevents start!
* OSS binaries do not include enterprise features
*
*
* ERROR: test tenant requested by configuration, but code organization prevents start!
* OSS binaries do not include enterprise features
*
[debug --host=127.0.0.1:45437 --insecure=true zip --concurrency=1 --cpu-profile-duration=0 /dev/null --timeout=.5s]
    datadriven.go:143: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/12843/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/cli/cli_test_/cli_test.runfiles/com_github_cockroachdb_cockroach/pkg/cli/testdata/zip/unavailable:1:
         
        output didn't match expected:
        @@ -242,13 +242,13 @@
         [node 1] requesting heap file list: last request failed: ...
         [node 1] requesting heap file list: creating error output: debug/nodes/1/heapprof.err.txt... done
         [node 1] requesting goroutine dump list... received response...
         [node 1] requesting goroutine dump list: last request failed: ...
         [node 1] requesting goroutine dump list: creating error output: debug/nodes/1/goroutines.err.txt... done
        -[node 1] requesting log files list... received response... done
        -[node ?] ? log files found
        -[node 1] [log file: ...
        +[node 1] requesting log files list... received response...
        +[node 1] requesting log files list: last request failed: ...
        +[node 1] requesting log files list: creating error output: debug/nodes/1/logs.err.txt... done
         [node 1] requesting ranges... received response... done
         [node 1] writing ranges... writing JSON output: debug/nodes/1/ranges.json... done
         [cluster] pprof summary script... writing binary output: debug/pprof-summary.sh... done
         [cluster] hot range summary script... writing binary output: debug/hot-ranges.sh... done
         [cluster] tenant hot range summary script... writing binary output: debug/hot-ranges-tenant.sh... done
    panic.go:522: -- test log scope end --
--- FAIL: TestUnavailableZip (37.70s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #105800 cli: TestUnavailableZip failed [A-observability-inf C-test-failure O-robot T-observability-inf branch-release-23.1]
</p>
</details>
/cc @cockroachdb/obs-inf-prs @cockroachdb/server
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestUnavailableZip.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-29778

### PR DESCRIPTION
**Pull request by ericharmeling**
This commit removes the `datadriven.RunTest` call from `TestUnavailableZip`, as this unit test is meant to test the ability of debug zip to output while nodes are unavailable, and not meant to assert specific, non-deterministic output.

Fixes #106961.

Release note: None

### CODE REVIEW

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107199)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling and @Santamaura)

___
*[`-- commits` line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107199#-N_oFAgT8-f6XIP5scM2):*
nit: remove these lines
___
*[`pkg/cli/zip_test.go` line 365 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107199#-N_oFH6688KBJKZoBOqI:-N_oFH67-YWEvrWOVTae:b-yag48u) ([raw file](https://github.com/cockroachdb/cockroach/blob/55006ad597b30801ce0d85617e14f4fa3eddd93c/pkg/cli/zip_test.go#L365)):*
> ```Go
> 	}
> 
> 	assert.NotEmpty(t, out)
> ```

can we add something that asserts that both nodes were iterated over instead of just checking for non-empty output. I think that's what Raphael was alluding to: that one node's unavailability doesn't keep us from collecting over others.

**Review by ericharmeling — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107199)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @Santamaura)

___
*[`-- commits` line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107199#-N_oFAgT8-f6XIP5scM2):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: remove these lines
</blockquote></details>

Done.
___
*[`pkg/cli/zip_test.go` line 365 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107199#-N_oFH6688KBJKZoBOqI:-N_sfr5l9QogZP_-ASQ4:byaimku) ([raw file](https://github.com/cockroachdb/cockroach/blob/55006ad597b30801ce0d85617e14f4fa3eddd93c/pkg/cli/zip_test.go#L365)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

can we add something that asserts that both nodes were iterated over instead of just checking for non-empty output. I think that's what Raphael was alluding to: that one node's unavailability doesn't keep us from collecting over others.
</blockquote></details>

I don't see anything in the output to indicate that both nodes are iterated over in the current test setup.

Reproducing this test locally shows that, even when node 2 is unavailable (just `crl+c`ing the second node), we get some output for both nodes (the one from the second indicates that it's unavailable):

```
➜  cockroach git:(simplify-testunavailablezip) ✗ ./cockroach node status --insecure
  id |     address     |   sql_address   |           build            |              started_at              |              updated_at              | locality | is_available | is_live
-----+-----------------+-----------------+----------------------------+--------------------------------------+--------------------------------------+----------+--------------+----------
   1 | localhost:26257 | localhost:26257 | v23.2.0-alpha.00000000-dev | 2023-07-21 14:17:22.253221 +0000 UTC | 2023-07-21 14:20:19.34364 +0000 UTC  |          | true         | true
   2 | localhost:26258 | localhost:26258 | v23.2.0-alpha.00000000-dev | 2023-07-21 14:17:23.327202 +0000 UTC | 2023-07-21 14:20:12.750291 +0000 UTC |          | false        | false
(2 rows)
➜  cockroach git:(simplify-testunavailablezip) ✗ ./cockroach debug zip --insecure=true --concurrency=1 --cpu-profile-duration=0 /dev/null --timeout=.5s

...

[node 1] node status... writing JSON output: debug/nodes/1/status.json... done
[node 1] using SQL connection URL: postgresql://root@localhost:26257/system?application_name=%24+cockroach+zip&connect_timeout=15&sslmode=disable
[node 1] retrieving SQL data for crdb_internal.active_range_feeds... writing output: debug/nodes/1/crdb_internal.active_range_feeds.json... done

...

[node 2] node status... writing JSON output: debug/nodes/2/status.json... done
[node 2] using SQL connection URL: postgresql://root@localhost:26258/system?application_name=%24+cockroach+zip&connect_timeout=15&sslmode=disable
[node 2] retrieving SQL data for crdb_internal.active_range_feeds... writing output: debug/nodes/2/crdb_internal.active_range_feeds.json...
[node 2] retrieving SQL data for crdb_internal.active_range_feeds: last request failed: dial tcp [::1]:26258: connect: connection refused

...
```

@knz 

Is this expected? Or am I missing something?

**Review by ericharmeling — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107199)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @Santamaura)

___
*[`pkg/cli/zip_test.go` line 365 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107199#-N_oFH6688KBJKZoBOqI:-N_swKSL6Pb8jfwCYDVm:b5lfzj8) ([raw file](https://github.com/cockroachdb/cockroach/blob/55006ad597b30801ce0d85617e14f4fa3eddd93c/pkg/cli/zip_test.go#L365)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

I don't see anything in the output to indicate that both nodes are iterated over in the current test setup.

Reproducing this test locally shows that, even when node 2 is unavailable (just `crl+c`ing the second node), we get some output for both nodes (the one from the second indicates that it's unavailable):

```
➜  cockroach git:(simplify-testunavailablezip) ✗ ./cockroach node status --insecure
  id |     address     |   sql_address   |           build            |              started_at              |              updated_at              | locality | is_available | is_live
-----+-----------------+-----------------+----------------------------+--------------------------------------+--------------------------------------+----------+--------------+----------
   1 | localhost:26257 | localhost:26257 | v23.2.0-alpha.00000000-dev | 2023-07-21 14:17:22.253221 +0000 UTC | 2023-07-21 14:20:19.34364 +0000 UTC  |          | true         | true
   2 | localhost:26258 | localhost:26258 | v23.2.0-alpha.00000000-dev | 2023-07-21 14:17:23.327202 +0000 UTC | 2023-07-21 14:20:12.750291 +0000 UTC |          | false        | false
(2 rows)
➜  cockroach git:(simplify-testunavailablezip) ✗ ./cockroach debug zip --insecure=true --concurrency=1 --cpu-profile-duration=0 /dev/null --timeout=.5s

...

[node 1] node status... writing JSON output: debug/nodes/1/status.json... done
[node 1] using SQL connection URL: postgresql://root@localhost:26257/system?application_name=%24+cockroach+zip&connect_timeout=15&sslmode=disable
[node 1] retrieving SQL data for crdb_internal.active_range_feeds... writing output: debug/nodes/1/crdb_internal.active_range_feeds.json... done

...

[node 2] node status... writing JSON output: debug/nodes/2/status.json... done
[node 2] using SQL connection URL: postgresql://root@localhost:26258/system?application_name=%24+cockroach+zip&connect_timeout=15&sslmode=disable
[node 2] retrieving SQL data for crdb_internal.active_range_feeds... writing output: debug/nodes/2/crdb_internal.active_range_feeds.json...
[node 2] retrieving SQL data for crdb_internal.active_range_feeds: last request failed: dial tcp [::1]:26258: connect: connection refused

...
```

@knz 

Is this expected? Or am I missing something?
</blockquote></details>

(For reference: https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/testdata/zip/unavailable)

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107199)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @Santamaura)

___
*[`pkg/cli/zip_test.go` line 365 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107199#-N_oFH6688KBJKZoBOqI:-N_t9oQqAvPBWwezRSs5:b-8mrlju) ([raw file](https://github.com/cockroachdb/cockroach/blob/55006ad597b30801ce0d85617e14f4fa3eddd93c/pkg/cli/zip_test.go#L365)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

(For reference: https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/testdata/zip/unavailable)
</blockquote></details>

you're right, not sure why we don't we have any log lines for `node 2` in there :thinking:
I wonder if a 2-node cluster produces odd behavior.

**Review by knz — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107199)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @ericharmeling, and @Santamaura)

___
*[`pkg/cli/zip_test.go` line 365 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107199#-N_oFH6688KBJKZoBOqI:-N_tX2om5LTAf3PnpR5T:b-jk8osh) ([raw file](https://github.com/cockroachdb/cockroach/blob/55006ad597b30801ce0d85617e14f4fa3eddd93c/pkg/cli/zip_test.go#L365)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

you're right, not sure why we don't we have any log lines for `node 2` in there :thinking:
I wonder if a 2-node cluster produces odd behavior.
</blockquote></details>

All nodes in the cluster that can still be reached over the network will return _some_ data. Only some endpoints will be unavailable; others will work.

So with the kind of unavailability set up in this test we should assert:
- that at least some requests succeed on both nodes
- AND also that at least some requests fail on at least one node
___
*[`pkg/cli/zip_test.go` line 361 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107199#-N_tXAxE8TH6j829YrvK:-N_tXAxE8TH6j829YrvL:b-qv3wzt) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9375f7d8b949f92744c3fe653e82469a9060f30/pkg/cli/zip_test.go#L361)):*
> ```Go
> 	// Keep the timeout short so that the test doesn't take forever.
> 	out, err := c.RunWithCapture(
> 		"debug zip --concurrency=2 --cpu-profile-duration=0 " + os.DevNull + " --timeout=.5s")
> ```

Why concurrency 2?

**Review by ericharmeling — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107199)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @knz, and @Santamaura)

___
*[`pkg/cli/zip_test.go` line 365 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107199#-N_oFH6688KBJKZoBOqI:-N_t_TXBCq5P-wUqemmz:b1otoi2) ([raw file](https://github.com/cockroachdb/cockroach/blob/55006ad597b30801ce0d85617e14f4fa3eddd93c/pkg/cli/zip_test.go#L365)):*
> that at least some requests succeed on both nodes

The current output from this setup would fail this first assertion (as seen in `testdata/zip/unavailable`, there are only requests for node 1). 

I'm wondering if this is a problem with the setup itself or with `debug zip`, because I'm getting at least some requests go through on both nodes on a local 2-node cluster with one unavailable node.
___
*[`pkg/cli/zip_test.go` line 361 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107199#-N_tXAxE8TH6j829YrvK:-N_t_kEX6JFlebg0moKx:b-ff2zlx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9375f7d8b949f92744c3fe653e82469a9060f30/pkg/cli/zip_test.go#L361)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Why concurrency 2?
</blockquote></details>

Ah no reason - I was tweaking the parameters to see if the output would change :sweat_smile: .

Reverted.

**Comment by ericharmeling** [comment]
The [`TestingRequestFilter` knob](https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/zip_test.go#L320) (tbh, I don't fully understand how) is causing the `NodesList` and `NodesStatus` status endpoints to return `nil`, which results in the head node populating the `nodeList` over which the `debug zip` functions run with just the details of the first node: https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/zip_cluster_wide.go#L126-L143.

IIUC, `debug zip` output in the case where the `NodesList` and `NodesStatus` endpoints are unavailable will only contain information about a single node. This being the test case for `TestUnavailableZip`, the `pkg/cli/testdata/zip/unavailable` testdata should only ever contain `[node 1]` lines (and only ever has).

If this behavior isn't what we want to be testing, then we want to make the node "unavailable" through some other mechanism that doesn't block status endpoints. We could then assert that the debug zip output contains at least one line containing `[node x]` for all nodes in the cluster, as reported by `NodesList`. I've been exploring some options, but haven't yet found the right one (open to suggestions). 

If we want instead to just test that we are able to get the `debug zip` output for the local node when said endpoints are unavailable, then I think we should move forward with this PR and only assert node 1 output.

Thoughts?

**Comment by knz** [comment]
I believe I made mistakes when I originally implemented the test.

The test is _probably_ intending to create a 3-node cluster, not 2. (A comment refers to "making 2 of the nodes unavailable" but the test only makes 1 node unavailable). I don't think it's a big issue but at least that confusing comment should be removed.

Then the test makes the zip command contact node 1, while node 1 is also the one being made unavailable.
I believe the intent was to make node 2 unavailable, then have the zip command run from node 1.

Assuming we continue to make node 1 unavailable I think both tests are valuable:

- contact node 1, and validate that only in-RAM data from node 1 can be retrieved (because the descriptors for the other nodes cannot be loaded)
- contact node 2, and validate that some more data from node 2 can be retrieved + the same data from node 1.

One item of additional complexity is that what I wrote above may not work if the ranges are not replicated on both nodes. I'm not sure StartTestCluster guarantees that. Maybe we need to sprinkle some `.WaitForFullReplication()` in there.

There's also a separate question (probably KV-worthy) of whether `.Nodes()` should fall back to the gossip data when it fails to read the node descriptors from KV. This would get us access to more nodes. I would like us to explore that, but maybe not as part of code yellow. Could you file a follow-up issue for that?

**Comment by ericharmeling** [comment]
@knz 
Thanks for taking a closer look at this. 

What you are saying makes a lot of sense. But I am still having trouble recreating the test scenario that we want here.


> contact node 2, and validate that some more data from node 2 can be retrieved + the same data from node 1.


This is where I get a bit lost. Given the following test cluster:

```
	tc := testcluster.StartTestCluster(t, 2, base.TestClusterArgs{
		ServerArgsPerNode: map[int]base.TestServerArgs{
			0: {Insecure: true, Knobs: base.TestingKnobs{Store: knobs}},
			1: {Insecure: true},
		},
	})
```

We are only able to get data from the local node. If we create a `TestCLI` against node 1, we only get data from node 1. If we do so on node 2, we only get data from node 2. 

If I instead add the store testing knob to node 2 (to presumably make this node unavailable?): 

```
	tc := testcluster.StartTestCluster(t, 2, base.TestClusterArgs{
		ServerArgsPerNode: map[int]base.TestServerArgs{
			0: {Insecure: true},
			1: {Insecure: true, Knobs: base.TestingKnobs{Store: knobs}},
		},
	})
```

We get data from all nodes, regardless of the server we contact.

> One item of additional complexity is that what I wrote above may not work if the ranges are not replicated on both nodes. I'm not sure StartTestCluster guarantees that. Maybe we need to sprinkle some `.WaitForFullReplication()` in there.

`WaitForFullReplication` [returns without waiting when the number of nodes is less than 3](https://github.com/cockroachdb/cockroach/blob/master/pkg/testutils/testcluster/testcluster.go#L1431-L1434). For this reason, I increase the test cluster node count to 3. And then add in a `.WaitForFullReplication()` call ahead of clogging the channel. 

But the result is the same: we are only able to get data from the local node. If we create a `TestCLI` on node 1, we only get data from node 1. The same goes for nodes 2 and 3. And adding the knob to either node 2 or 3 results in us being able to get data from all nodes, regardless of the node we contact.

So I don't fully understand what this code does:

```
knobs := &kvserver.StoreTestingKnobs{
  TestingRequestFilter: func(ctx context.Context, _ *kvpb.BatchRequest) *kvpb.Error {
    select {
    case <-unavailableCh.Load().(chan struct{}):
    case <-ctx.Done():
    }
    return nil
  },
}

...

ch := make(chan struct{})
unavailableCh.Store(ch)
defer close(ch)
```

Are we are blocking replica requests from node 1 here? How does that affect the `debug zip` against node 2's fan-outs for data from node 1 and 3?

**Comment by knz** [comment]
Ah, yes now i see the problem.

- What the test currently does with 2 nodes is fine, and is getting the expected result (as you've found already)
- The test we are missing is when one of the nodes is _partially_ unavailable. That is, where we are able to read the node descriptors successfully (so we can contact all nodes) but some ranges are unavailable, whereby some of the data retrieval is blocked.

One way to do this is to extend the TestingRequestFilter to inspect the (start) key in the kv batch header. Say, if the key is less than TableMin, let the request through and block it otherwise. This should block SQL but let liveness/nodestatus through.

**Comment by ericharmeling** [comment]
> The test is probably intending to create a 3-node cluster, not 2. (A comment refers to "making 2 of the nodes unavailable" but the test only makes 1 node unavailable). I don't think it's a big issue but at least that confusing comment should be removed.

Updated that comment.

> What the test currently does with 2 nodes is fine, and is getting the expected result (as you've found already)

Okay - I've updated this test to include two subtests. Please see the comments and commit message for details.

> The test we are missing is when one of the nodes is partially unavailable. That is, where we are able to read the node descriptors successfully (so we can contact all nodes) but some ranges are unavailable, whereby some of the data retrieval is blocked.
> One way to do this is to extend the TestingRequestFilter to inspect the (start) key in the kv batch header. Say, if the key is less than TableMin, let the request through and block it otherwise. This should block SQL but let liveness/nodestatus through.

Excellent. Thank you! Done.

> There's also a separate question (probably KV-worthy) of whether .Nodes() should fall back to the gossip data when it fails to read the node descriptors from KV. This would get us access to more nodes. I would like us to explore that, but maybe not as part of code yellow. Could you file a follow-up issue for that?

Done. See https://github.com/cockroachdb/cockroach/issues/108310. (Please feel free to update the issue title/description as you see fit).

**Review by knz — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107199)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @ericharmeling, and @Santamaura)

___
*[`pkg/cli/zip_test.go` line 331 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/107199#-NbMLLT-DcwIAibisT9l:-NbMLLT-DcwIAibisT9m:b-5rzpac) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ac510478e75158184e1a4d435a6e2bdc869bba3/pkg/cli/zip_test.go#L331)):*
> ```Go
> 				// For node 1 connections, only block requests to table data ranges.
> 				if br.Requests[0].GetInner().Header().Key.Compare(keys.
> 					TableDataMin) != -1 {
> ```

Let's make that `>= 0` -- it's the more idiomatic way to say "greater than".
___
*[`pkg/cli/zip_test.go` line 382 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/107199#-NbML_e-ALdVNh6TfeMj:-NbML_e-ALdVNh6TfeMk:b-m0tvg2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ac510478e75158184e1a4d435a6e2bdc869bba3/pkg/cli/zip_test.go#L382)):*
> ```Go
> 	assert.NotEmpty(t, out)
> 	assert.Contains(t, out, "[cluster]")
> 	assert.Contains(t, out, "[node 1]")
> ```

I'd recommend checking a little more detailed stuff. As currently written, this here will allow the test to drift if/when we ever use the node prefix to announce, say, a connection error to that node.

**Review by ericharmeling — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107199)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @knz, and @Santamaura)

___
*[`pkg/cli/zip_test.go` line 331 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/107199#-NbMLLT-DcwIAibisT9l:-NbVfdHNAfWZH9BGqqpj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ac510478e75158184e1a4d435a6e2bdc869bba3/pkg/cli/zip_test.go#L331)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Let's make that `>= 0` -- it's the more idiomatic way to say "greater than".
</blockquote></details>

Done.
___
*[`pkg/cli/zip_test.go` line 382 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/107199#-NbML_e-ALdVNh6TfeMj:-NbVfeUC9T0cFY77thD8:bd0pvx9) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ac510478e75158184e1a4d435a6e2bdc869bba3/pkg/cli/zip_test.go#L382)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I'd recommend checking a little more detailed stuff. As currently written, this here will allow the test to drift if/when we ever use the node prefix to announce, say, a connection error to that node.
</blockquote></details>

Done.

Added a cluster check on nodes and liveness requests, and then a per-node check on several types of zip data requests.

**Review by knz — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107199)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @Santamaura)

**Comment by ericharmeling** [comment]
TFTR!

**Comment by ericharmeling** [comment]
blathers backport 23.1.9-rc

**Pull request merged**
