### PR TITLE
sql: add syntax for supporting security definer

### LINKED ISSUE #128844: sql: support syntax for SECURITY DEFINER
As a prelude for #121514, let's implement the syntax for defining a routine with SECURITY DEFINER. We should implement `[EXTERNAL] SECURITY {INVOKER | DEFINER}`. EXTERNAL is just there for SQL conformity (https://www.postgresql.org/docs/current/sql-createfunction.html).

Epic: CRDB-37477

### PR DESCRIPTION
**Pull request by annrpom**
This patch adds the syntax needed for supporting security
definer. Right now, if a routine is specified with
`[EXTERNAL] SECURITY {INVOKER | DEFINER}`, it is a no-op.
If the security mode is not specified, the default is
`SECURITY INVOKER`.

This also means that syntax for altering a function
supports the above options as well:
```
alter function f(int) external security definer;
```

Fixes: https://github.com/cockroachdb/cockroach/issues/128844
Epic: [CRDB-37477](https://cockroachlabs.atlassian.net/browse/CRDB-37477)

Release note: None

### CODE REVIEW

**Comment by annrpom** [comment]
Need to brush up and add tests

**Review by rafiss — CHANGES_REQUESTED** [review]
nice work!

this change was small enough, so it doesn't matter too much, but for future reference: the `pkg/sql/parser`, `pkg/sql/catalog`, and `pkg/sql/schemachanger` changes, could be broken up into 3 separate commits. for other syntax/feature additions, that makes it easier to review, since we can merge the parser changes first, and get to the lower level changes which mirror the syntax separately.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128413#-:-O46iVrd-bfUlj_PXauz:bmpmd2)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom, @michae2, and @msbutler)

___
*[`pkg/sql/catalog/catpb/function.proto` line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128413#-O46fdAl9w8V4r0Hj_gD:-O46fdAl9w8V4r0Hj_gE:b8c30bm) ([raw file](https://github.com/cockroachdb/cockroach/blob/70cfc7964ea644d1ad13c0279db43a51d35c0cd3/pkg/sql/catalog/catpb/function.proto#L81)):*
> ```proto
>   option (gogoproto.equal) = true;
>   optional Function.Security security = 1 [(gogoproto.nullable) = false];
>   optional bool external = 2 [(gogoproto.nullable) = false];
> ```

since the `external` keyword in the syntax actually does not have any functional effect, let's not include it in the proto

also, can we add a comment on `security` that says what the default behavior is if it's missing?
___
*[`pkg/sql/opt/optbuilder/routine.go` line 374 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128413#-O46gDP89cf8gW6SoUtm:-O46gDP89cf8gW6SoUtn:b-px3ub0) ([raw file](https://github.com/cockroachdb/cockroach/blob/70cfc7964ea644d1ad13c0279db43a51d35c0cd3/pkg/sql/opt/optbuilder/routine.go#L374)):*
> ```Go
> 			panic(err)
> 		}
> 		// hi
> ```

hello!
___
*[`pkg/sql/sem/tree/create_routine.go` line 344 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128413#-O46gntq59Y9q23PjDNY:-O46gntq59Y9q23PjDNZ:bpa5cce) ([raw file](https://github.com/cockroachdb/cockroach/blob/70cfc7964ea644d1ad13c0279db43a51d35c0cd3/pkg/sql/sem/tree/create_routine.go#L344)):*
> ```Go
> type RoutineSecurity struct {
> 	Security routineSecurityOptions
> 	External bool
> ```

since `external` doesn't do anything, we can just not include it in this struct, and always normalize when formatting the statement to not output it.

actually, if we don't have the `external` field, then we can avoid needing the struct at all. all we should need is the enum for invoker/definer.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/udf_params` line 227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128413#-O46hZzlAKgdm-pp23ju:-O46hZzlAKgdm-pp23jv:b-9d22c7) ([raw file](https://github.com/cockroachdb/cockroach/blob/70cfc7964ea644d1ad13c0279db43a51d35c0cd3/pkg/ccl/logictestccl/testdata/logic_test/udf_params#L227)):*
> ```
>   CALLED ON NULL INPUT
>   LANGUAGE plpgsql
>   SECURITY INVOKER
> ```

i missed the logic that says that `SECURITY INVOKER` should be the default if it wasn't specified. could you point me to that, just wanna make sure i understand.
___
*[`pkg/sql/parser/testdata/create_function` line 555 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128413#-O46hrVt0_cI7altrnho:-O46hrVt0_cI7altrnhp:b8e3817) ([raw file](https://github.com/cockroachdb/cockroach/blob/70cfc7964ea644d1ad13c0279db43a51d35c0cd3/pkg/sql/parser/testdata/create_function#L555)):*
> ```
> 
> parse
> CREATE OR REPLACE FUNCTION f(a int = 7) RETURNS INT SECURITY INVOKER AS 'SELECT 1' LANGUAGE SQL
> ```

can you add some tests to make sure we can't specify `security` twice?

**Review by mgartner — APPROVED** [review]
:lgtm: Nice work!

> Reviewed 65 of 65 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128413#-:-O46jUC1EhjPaZSfl39n:bcmw7ss)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @annrpom, @michae2, and @msbutler)

___
*[`pkg/sql/catalog/catpb/function.proto` line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128413#-O46ZWaS7yxXoVL4lAlD:-O46ZWaS7yxXoVL4lAlE:b-bh3o53) ([raw file](https://github.com/cockroachdb/cockroach/blob/70cfc7964ea644d1ad13c0279db43a51d35c0cd3/pkg/sql/catalog/catpb/function.proto#L81)):*
> ```proto
>   option (gogoproto.equal) = true;
>   optional Function.Security security = 1 [(gogoproto.nullable) = false];
>   optional bool external = 2 [(gogoproto.nullable) = false];
> ```

If `EXTERNAL` has no effect, do we need to retain its value, or can we simply ignore it after parsing? If we ignore it, then `SHOW CREATE FUNCTION ...` won't be able to display `EXTERNAL`, but I don't think that's a problem, is it?
___
*[`pkg/sql/opt/optbuilder/routine.go` line 374 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128413#-O46Zyz26Ljb39zTfBH_:-O46Zyz26Ljb39zTfBHa:bn2zade) ([raw file](https://github.com/cockroachdb/cockroach/blob/70cfc7964ea644d1ad13c0279db43a51d35c0cd3/pkg/sql/opt/optbuilder/routine.go#L374)):*
> ```Go
> 			panic(err)
> 		}
> 		// hi
> ```

hello :)
___
*[`pkg/sql/schemachanger/screl/scalars.go` line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128413#-O46iaGn7zQjWV9t6W_E:-O46iaGn7zQjWV9t6W_F:b-udng60) ([raw file](https://github.com/cockroachdb/cockroach/blob/70cfc7964ea644d1ad13c0279db43a51d35c0cd3/pkg/sql/schemachanger/screl/scalars.go#L130)):*
> ```Go
> 	case *scpb.TypeComment, *scpb.DatabaseZoneConfig:
> 		return version.IsActive(clusterversion.V24_2)
> 	// TODO(before merge): gate v24_3
> ```

nit: Don't forget this :)

**Review by annrpom — COMMENTED** [review]
> this change was small enough, so it doesn't matter too much, but for future reference: the `pkg/sql/parser`, `pkg/sql/catalog`, and `pkg/sql/schemachanger` changes, could be broken up into 3 separate commits. for other syntax/feature additions, that makes it easier to review, since we can merge the parser changes first, and get to the lower level changes which mirror the syntax separately

good point -- ty for the knowledge

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128413#-:-O4kDmfa5lZAArkn-m8e:b-kstj3n)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @michae2, @msbutler, and @rafiss)

___
*[`pkg/sql/catalog/catpb/function.proto` line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128413#-O46fdAl9w8V4r0Hj_gD:-O4kDtj937ujkC_ZN8xC:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/70cfc7964ea644d1ad13c0279db43a51d35c0cd3/pkg/sql/catalog/catpb/function.proto#L81)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

since the `external` keyword in the syntax actually does not have any functional effect, let's not include it in the proto

also, can we add a comment on `security` that says what the default behavior is if it's missing?
</blockquote></details>

done
___
*[`pkg/sql/catalog/catpb/function.proto` line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128413#-O46ZWaS7yxXoVL4lAlD:-O4kDvk2EYrl15mTu8eK:b199n5f) ([raw file](https://github.com/cockroachdb/cockroach/blob/70cfc7964ea644d1ad13c0279db43a51d35c0cd3/pkg/sql/catalog/catpb/function.proto#L81)):*
> but I don't think that's a problem, is it?

tis not -- done
___
*[`pkg/sql/opt/optbuilder/routine.go` line 374 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128413#-O46gDP89cf8gW6SoUtm:-O4kEhe_EPqRx7w8RQvz:b32wna) ([raw file](https://github.com/cockroachdb/cockroach/blob/70cfc7964ea644d1ad13c0279db43a51d35c0cd3/pkg/sql/opt/optbuilder/routine.go#L374)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hello!
</blockquote></details>

hi
___
*[`pkg/sql/opt/optbuilder/routine.go` line 374 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128413#-O46Zyz26Ljb39zTfBH_:-O4kEiGiCMYKvZMGwlhW:b32wna) ([raw file](https://github.com/cockroachdb/cockroach/blob/70cfc7964ea644d1ad13c0279db43a51d35c0cd3/pkg/sql/opt/optbuilder/routine.go#L374)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

hello :)
</blockquote></details>

hi
___
*[`pkg/sql/schemachanger/screl/scalars.go` line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128413#-O46iaGn7zQjWV9t6W_E:-O4kPqaLBciMBAwkMla5:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/70cfc7964ea644d1ad13c0279db43a51d35c0cd3/pkg/sql/schemachanger/screl/scalars.go#L130)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: Don't forget this :)
</blockquote></details>

done
___
*[`pkg/sql/sem/tree/create_routine.go` line 344 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128413#-O46gntq59Y9q23PjDNY:-O4kPrP8BXH1wSYmlFwh:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/70cfc7964ea644d1ad13c0279db43a51d35c0cd3/pkg/sql/sem/tree/create_routine.go#L344)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

since `external` doesn't do anything, we can just not include it in this struct, and always normalize when formatting the statement to not output it.

actually, if we don't have the `external` field, then we can avoid needing the struct at all. all we should need is the enum for invoker/definer.
</blockquote></details>

done
___
*[`pkg/ccl/logictestccl/testdata/logic_test/udf_params` line 227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128413#-O46hZzlAKgdm-pp23ju:-O4kQyhS6tbUZS8nS3dD:b-cu77tl) ([raw file](https://github.com/cockroachdb/cockroach/blob/70cfc7964ea644d1ad13c0279db43a51d35c0cd3/pkg/ccl/logictestccl/testdata/logic_test/udf_params#L227)):*
i left the suggested comment in function.proto from:

> also, can we add a comment on `security` that says what the default behavior is if it's missing?

i also added this in structured.proto & create_routine.go, 

unless you mean general "logic" and not in the code -- which would be this line in the postgres [docs](https://www.postgresql.org/docs/current/sql-createfunction.html):

> `SECURITY INVOKER` indicates that the function is to be executed with the privileges of the user that calls it. That is the default.

let me know if this doesn't address your comment properly, though
___
*[`pkg/sql/parser/testdata/create_function` line 555 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128413#-O46hrVt0_cI7altrnho:-O4kScGv9sqsrryulZvW:bcvqk3r) ([raw file](https://github.com/cockroachdb/cockroach/blob/70cfc7964ea644d1ad13c0279db43a51d35c0cd3/pkg/sql/parser/testdata/create_function#L555)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

can you add some tests to make sure we can't specify `security` twice?
</blockquote></details>

good point -- done! these are added in udf_options since we check this during `buildCreateFunction` https://github.com/cockroachdb/cockroach/blob/16cd5665feb68336dc547f275b6595be97a7c268/pkg/sql/opt/optbuilder/create_function.go#L78-L80

**Review by rafiss — APPROVED** [review]
great work! lgtm!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128413#-:-O4v5iSN6MZD2m2O8UD7:btf7s3p)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @annrpom, @mgartner, @michae2, and @msbutler)

___
*[`pkg/ccl/logictestccl/testdata/logic_test/udf_params` line 227 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128413#-O46hZzlAKgdm-pp23ju:-O4v5Lao7uZpra7NlrJR:bqdfgrc) ([raw file](https://github.com/cockroachdb/cockroach/blob/70cfc7964ea644d1ad13c0279db43a51d35c0cd3/pkg/ccl/logictestccl/testdata/logic_test/udf_params#L227)):*
<details><summary><i>Previously, annrpom (annie pompa) wrote…</i></summary><blockquote>

i left the suggested comment in function.proto from:

> also, can we add a comment on `security` that says what the default behavior is if it's missing?

i also added this in structured.proto & create_routine.go, 

unless you mean general "logic" and not in the code -- which would be this line in the postgres [docs](https://www.postgresql.org/docs/current/sql-createfunction.html):

> `SECURITY INVOKER` indicates that the function is to be executed with the privileges of the user that calls it. That is the default.

let me know if this doesn't address your comment properly, though
</blockquote></details>

thanks! i meant the code pointers; that was helpful.

**Comment by annrpom** [comment]
TFTRs! ('-')7

bors r=rafiss, mgartner

**Pull request merged**
