### PR TITLE
sqlccl: use Export command to implement Backup

### PR DESCRIPTION
**Pull request by danhhz**
```
name             old time/op    new time/op     delta
ClusterBackup-8    2.77µs ±26%     1.06µs ±10%   -61.85%  (p=0.008 n=5+5)

name             old speed      new speed       delta
ClusterBackup-8  42.3MB/s ±22%  109.2MB/s ±10%  +157.84%  (p=0.008 n=5+5)

name             old alloc/op   new alloc/op    delta
ClusterBackup-8    1.09kB ± 0%     0.14kB ± 6%   -87.54%  (p=0.016 n=4+5)

name             old allocs/op  new allocs/op   delta
ClusterBackup-8     0.00 ±NaN%       3.00 ± 0%     +Inf%  (p=0.008 n=5+5)
```

cc @bdarnell You mentioned in the original review that `client.SendWrappedWith` wasn't really intended for non-test use. Figured I'd double-check that you haven't changed your mind.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13556)

### CODE REVIEW

**Comment by bdarnell** [comment]
Reviewed 1 of 1 files at r1, 1 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/ccl/sqlccl/backup.go, line 220 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13556#-KcsnGgwEMPc7XzfitdG:-KcsnGgxXhiC7WgTdgag:b1namu3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f20bf06d5ec1eed363ad2bfb1c20c8cae47d5c91/pkg/ccl/sqlccl/backup.go#L220)):*
> ```Go
> 				StartTime: startTime,
> 			}
> 			res, pErr := client.SendWrappedWith(ctx, db.GetSender(), header, req)
> ```

I think this would be the first non-test use of SendWrappedWith, but I'm OK with that. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13556)*

**Comment by dt** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/storageccl/export.go, line 117 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13556#-KcsrC1KOyXUyxo-xTTq:-KcsrC1KOyXUyxo-xTTr:b-wd3ygh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f20bf06d5ec1eed363ad2bfb1c20c8cae47d5c91/pkg/ccl/storageccl/export.go#L117)):*
> ```Go
> 		// SSTables require at least one entry. It's silly to save an empty one,
> 		// anyway.
> 		sst = nil
> ```

nit: do we do this pattern elsewhere? it just looks a little funky. would it be cleaner just to make RocksDBSstFileWriter.Close handle nil? /shrug

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13556)*

**Comment by dt** [comment]
:lgtm:

---

Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13556#-:-KcsramUft5uHkI4MTcr:bnfp4nl)*

**Comment by mjibson** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/sqlccl/backup.go, line 222 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13556#-KcssBb5bD5z1cnu7vVV:-KcssBb5bD5z1cnu7vVW:b-jq9tkd) ([raw file](https://github.com/cockroachdb/cockroach/blob/f20bf06d5ec1eed363ad2bfb1c20c8cae47d5c91/pkg/ccl/sqlccl/backup.go#L222)):*
> ```Go
> 			res, pErr := client.SendWrappedWith(ctx, db.GetSender(), header, req)
> 			if pErr != nil {
> 				wg.Done(pErr.GoError())
> ```

Need return here.

---

*[pkg/ccl/sqlccl/backup.go, line 237 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13556#-KcssUUENtNOmN9TbCEf:-KcssUUENtNOmN9TbCEg:bsuiho8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f20bf06d5ec1eed363ad2bfb1c20c8cae47d5c91/pkg/ccl/sqlccl/backup.go#L237)):*
> ```Go
> 		}(spans[i])
> 	}
> 	if err := wg.Wait(); err != nil {
> ```

This could wait a real long time. Could we add some stuff to also listen for a context.Done?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13556)*

**Comment by mjibson** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/sqlccl/backup.go, line 237 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13556#-KcssUUENtNOmN9TbCEf:-KcssnCIbqhKVh9Tmal6:b99qzc4) ([raw file](https://github.com/cockroachdb/cockroach/blob/f20bf06d5ec1eed363ad2bfb1c20c8cae47d5c91/pkg/ccl/sqlccl/backup.go#L237)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

This could wait a real long time. Could we add some stuff to also listen for a context.Done?
</blockquote></details>

Or maybe because the ctx is passed down with client.SendWrappedWith, those will all get cancelled and return quickly, so no need to reimplement that logic here? Not sure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13556)*

**Comment by danhhz** [comment]
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/ccl/sqlccl/backup.go, line 222 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13556#-KcssBb5bD5z1cnu7vVV:-KcsvZMqMC9_RnHZ4_J1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f20bf06d5ec1eed363ad2bfb1c20c8cae47d5c91/pkg/ccl/sqlccl/backup.go#L222)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Need return here.
</blockquote></details>

Done.

---

*[pkg/ccl/sqlccl/backup.go, line 237 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13556#-KcssUUENtNOmN9TbCEf:-Kcsv_NMqjZS20V4-593:b437471) ([raw file](https://github.com/cockroachdb/cockroach/blob/f20bf06d5ec1eed363ad2bfb1c20c8cae47d5c91/pkg/ccl/sqlccl/backup.go#L237)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Or maybe because the ctx is passed down with client.SendWrappedWith, those will all get cancelled and return quickly, so no need to reimplement that logic here? Not sure.
</blockquote></details>

Yeah, the latter

---

*[pkg/ccl/storageccl/export.go, line 117 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13556#-KcsrC1KOyXUyxo-xTTq:-Kcsvh5JGbZoxxouhA__:b-higtgt) ([raw file](https://github.com/cockroachdb/cockroach/blob/f20bf06d5ec1eed363ad2bfb1c20c8cae47d5c91/pkg/ccl/storageccl/export.go#L117)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

nit: do we do this pattern elsewhere? it just looks a little funky. would it be cleaner just to make RocksDBSstFileWriter.Close handle nil? /shrug
</blockquote></details>

This is a little more subtle than that. I reworked the comment to hopefully make it more obvious what's going on

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13556)*

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13556#-:-KcsxQgGMyQv1uMn1ozr:bnfp4nl)*

**Comment by danhhz** [comment]
Thanks for the reviews!

**Pull request merged**
