### PR TITLE
cli/connect: fix typo in informational output

### LINKED ISSUE #61613: cli: typo in the output of `cockroach connect`
```
% ./cockroach connect --single-node
generating cert bundle for cluster
[...] Eample command:
```

Typo in "Eample"

cc @aaron-crl @itsbilal 

Related to  #60632

### PR DESCRIPTION
**Pull request by knz**
First commit from #62335. 
Fixes #61613.

### CODE REVIEW

**Review by stevendanna — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62336)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl and @itsbilal)

**Review by stevendanna — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62336)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl and @itsbilal)

**Comment by knz** [comment]
not merging this until #62335 is reviewed

**Comment by knz** [comment]
TFYR!

bors r=stevendanna

**Pull request merged**
