### PR TITLE
geo: fix panic when calling distance builtin with NaN coordinate

### LINKED ISSUE #90118: sql: st_distancespheroid with point with NaN coordinate causes panic
roachtest.sqlsmith/setup=seed/setting=no-mutations [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=6994303&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=6994303&tab=artifacts#/sqlsmith/setup=seed/setting=no-mutations) on release-21.2 @ [06fb4817f5ce494565674a1b4784d92ac6624fac](https://github.com/cockroachdb/cockroach/commits/06fb4817f5ce494565674a1b4784d92ac6624fac):

```
									),
									(
										'2':::STRING,
										(0.5890958543624928:::FLOAT8::FLOAT8 // (-0.40367659361358665):::FLOAT8::FLOAT8)::FLOAT8,
										'7':::STRING
									)
							)
								AS tab_13527 (col_32960, col_32961, col_32962)
				)
		SELECT
			'"':::STRING AS col_32963,
			cte_ref_1628.col_32956 AS col_32964,
			st_distancespheroid(st_snaptogrid('01050000C00400000001020000C0040000000A2B7937D2DDF341CAEF56D6CA94FEC168909A5A5308D5C1600863B65513F9C10E9D7B3828CFF3415D754B6EE344F4C154EB8B48DC37EEC14E5053131963FA41E4B8F8F90180E941B433052AC359E2C1B0F9BD706AE0CA41E47A00106D23E6C1140CDEFC2066E541DC041E43D7E0E541D71DA60DCF5800C2C03C19D64662A94101020000C00400000078A3F3FA171BECC14906026AC73000C2BF39C72B6DC0FCC13CFE89583CADE64120EBED23DDB5C1C1C072A4065C53DCC1B04A51E92098F441A063BD5F67B2E841CCB94727FC86DCC1B8276303051FD84114B61A426749FC417483A4C01A68E341F252B7B34B6EEDC19289514C865EF14148C84B584F87F24114436730C149E04101020000C003000000F8CB40BB7D74FD41407A6D511432D741B0CD41FE895DD4418672254A1EB8014208EACF19E83CD541746AD58CB9170242C0B19FB99AFED94148AE2EF95896FE4178B997637B6BD6C164ABA2111EA8FD410CFDE813927BD7C190265FCF876A014201020000C0060000001065DCD70770F7C10F612AD0CC33F4C111FFA41FB47802C2265299CFB19A01422F77456D88D7F2C1A2EAE8CB9F09F4C150167B5B5309EA415A5DDD2C45E9F1418C125198484AE64153D5D0ED755DFAC1EA0005C2D148F1C1EC3F313A1519E241E2779FD007B7F341CB5DDDC5D00CF0C1C24CC5C279C0FDC188BB78838C7BF341F0942DF0B3FBF041906304A7FFB4D5C1982570D0B8FCDB412059D469B946BF4160C6D4DBF074E841586F81D38E05E641A14870D6117800C23C248B430E0CF9C1':::GEOMETRY::GEOMETRY, cte_ref_1628.col_32957::FLOAT8)::GEOMETRY::GEOMETRY, '010500000002000000010200000003000000000000000000244000000000000024400000000000003440000000000000344000000000000024400000000000004440010200000004000000000000000000444000000000000044400000000000003E400000000000003E40000000000000444000000000000034400000000000003E400000000000002440':::GEOMETRY::GEOMETRY)::FLOAT8
				AS col_32965
		FROM
			with_5490 AS cte_ref_1628
		WHERE
			(false OR true)
		ORDER BY
			cte_ref_1628.col_32956 ASC;ping node 1: dial tcp 34.148.119.100:26257: connect: connection refused
		HINT: node likely crashed, check logs in artifacts > logs/1.unredacted

	cluster.go:1296,context.go:91,cluster.go:1284,test_runner.go:866: dead node detection: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod monitor teamcity-6994303-1666072367-12-n4cpu4 --oneshot --ignore-empty-nodes: exit status 1 3: 14601
		1: dead (exit status 134)
		4: 12463
		2: 12621
		Error: UNCLASSIFIED_PROBLEM: 1: dead (exit status 134)
		(1) UNCLASSIFIED_PROBLEM
		Wraps: (2) attached stack trace
		  -- stack trace:
		  | github.com/cockroachdb/cockroach/pkg/roachprod.Monitor
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/roachprod/roachprod.go:596
		  | main.glob..func14
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:569
		  | main.wrap.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:123
		  | github.com/spf13/cobra.(*Command).execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:856
		  | github.com/spf13/cobra.(*Command).ExecuteC
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:960
		  | github.com/spf13/cobra.(*Command).Execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:897
		  | main.main
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1170
		  | runtime.main
		  | 	/usr/local/go/src/runtime/proc.go:250
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1571
		Wraps: (3) 1: dead (exit status 134)
		Error types: (1) errors.Unclassified (2) *withstack.withStack (3) *errutil.leafError
```
<details><summary>Reproduce</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #89960 roachtest: sqlsmith/setup=seed/setting=no-mutations failed [C-test-failure O-roachtest O-robot T-sql-queries branch-master branch-release-22.2 branch-release-22.2.0 release-blocker]
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sqlsmith/setup=seed/setting=no-mutations.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-20594

### PR DESCRIPTION
**Pull request by rytaft**
This commit updates the distance builtin functions to return an error if one of the inputs contains a coordinate that is `NaN`. This avoids a panic in the s2 library that occurs when calling `SetFloat64` with `NaN`.

Fixes #90118

Release note (bug fix): Fixed a panic that could occur when calling `st_distancespheroid`, `st_distancesphere`, or `st_distance` with a spatial object containing an NaN coordinate. This now produces an error, "input is out of range".

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
Thanks for fixing this! Just one question but otherwise :lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90218#-:-NEht3uI15xh3UxZFmrn:b-8fyqxi)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan and @rytaft)

___
*[`pkg/geo/geogfn/distance.go` line 427 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90218#-NEhsnk_5MGdiYi1iY-7:-NEhsnk_5MGdiYi1iY-8:b1ys5e8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2ad88a364ef1d0b4e5cb50ca9419897af62305a/pkg/geo/geogfn/distance.go#L427)):*
> ```Go
> func regionHasNaN(r s2.Region) bool {
> 	switch r := r.(type) {
> 	case s2.Point:
> ```

How do we know these are the only types we have to worry about?

**Review by rytaft — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90218#-:-NEhxEhlCCMBkmWLWzTn:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan)

___
*[`pkg/geo/geogfn/distance.go` line 427 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90218#-NEhsnk_5MGdiYi1iY-7:-NEhwmWM6451NKBEk4Po:b-3usvmj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2ad88a364ef1d0b4e5cb50ca9419897af62305a/pkg/geo/geogfn/distance.go#L427)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

How do we know these are the only types we have to worry about?
</blockquote></details>

I think these are the only types that can be returned from `S2RegionsFromGeomT`, but maybe @otan can confirm.

**Comment by otan** [comment]
i think you can use `BoundingBoxHasNaNCoordinates` instead which avoids the O(n) lookup of every coordinate.

**Review by otan — CHANGES_REQUESTED** [review]
> i think you can re-use BoundingBoxHasNaNCoordinates instead which avoids the O(n) lookup of every coordinate. You'll need to copy the method and make it take in a Geography or make it take in an interface that takes BoundingBoxRef (geopb.Geometry should suffice?) and put it in `geo` probably.

requesting changes based on above comment - let me know if you have any questions!

**Comment by rytaft** [comment]
> > i think you can re-use BoundingBoxHasNaNCoordinates instead which avoids the O(n) lookup of every coordinate. You'll need to copy the method and make it take in a Geography or make it take in an interface that takes BoundingBoxRef (geopb.Geometry should suffice?) and put it in `geo` probably.
> 
> requesting changes based on above comment - let me know if you have any questions!

It seems like the bounding box is nil in this case. Is there something I should do to ensure that it's not nil?

**Comment by otan** [comment]
Hmm a nil bounding box should probably return DNull. What happens when you
run the same query against postgres? What happens if you
st_distancespheroid a POINT EMPTY? I'd check but not on computer

**Review by rytaft — COMMENTED** [review]
Sorry for the delay. Getting back to this now.

> What happens when you run the same query against postgres?

I get "No function matches the given name and argument types", since st_distancespheroid requires a third "spheroid" argument in Postgres. However, if change to st_distancesphere (which also panics on CRDB), I get "ERROR:  input is out of range".

> What happens if you st_distancespheroid a POINT EMPTY? I'd check but not on computer

On Postgres I get -1, on CRDB I get NULL. (If I use st_distancesphere, I get "ERROR:  input is out of range" on Postgres, and NULL on CRDB.)

What I've found is that the result of `st_snaptogrid` returns a geometry with a bounding box containing NaN coordinates. However, when `AsGeography` is called on the geometry, it returns a geography with a nil bounding box. Seems like perhaps we shouldn't be returning a nil bounding box in this case?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90218#-:-NFskHKL9zNawIe-YHSX:bdsucv8)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @otan)

**Comment by rytaft** [comment]
I think the main problem is that `s2.Rect.AddPoint(ll LatLng)` silently returns the original rectangle if the provided `LatLng` is not valid. In this case, we started with an empty rectangle, then added some NaN points, which just resulted in the original empty rectangle (and is the reason we get a nil bounding box). Perhaps callers of `s2.Rect.AddPoint` (`geogPointsBBox` and `geogLineBBox`) should check for validity of the point first, and return an error if the point is not valid?

**Review by rytaft — COMMENTED** [review]
I went ahead and made that change. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90218#-:-NFzGR1_7oGPo9nYPePu:bsge9vb)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @otan)

**Review by otan — APPROVED** [review]
sorry for being slow - lgtm!

**Review by rytaft — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90218#-:-NG24zh40Jzht93VZCUj:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @otan)

**Pull request merged**
