### PR TITLE
build: require go1.12

### PR DESCRIPTION
**Pull request by andreimatei**
Since the builder was upgraded a while ago and we already have code
needing 1.12.

Release note: The minimum compiler version for building CRDB is now go
1.12.

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]

**Comment by andreimatei** [comment]
Some more tweaks.

**Review by bdarnell — APPROVED** [review]
I have another go 1.12-related cleanup in #38384.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38379)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @petermattis)

___
*[build/teamcity-assert-clean.sh, line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38379#-LiAZihzD-h9QgjyX_zu:-LiAZihzD-h9QgjyX_zv:b-2hc467) ([raw file](https://github.com/cockroachdb/cockroach/blob/521a52d185712e73a99d5124ff8314e8c17c6352/build/teamcity-assert-clean.sh#L13)):*
> ```Shell
>   git diff -a >&2 || true
>   echo "Nuking build cruft. Please teach this build to clean up after itself." >&2
>   run docker run --volume="$root:/nuke" --workdir="/nuke" golang:stretch /bin/bash -c "git clean -ffdx ; git submodule foreach --recursive git clean -xffd" >&2
> ```

This will automatically use 1.13 when that's released, no? Is that desirable?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38379)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @petermattis and @RaduBerinde)

___
*[build/teamcity-assert-clean.sh, line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38379#-LiAZihzD-h9QgjyX_zu:-LiAd4ZD8Mp1MV1fCrfR:b88amcp) ([raw file](https://github.com/cockroachdb/cockroach/blob/521a52d185712e73a99d5124ff8314e8c17c6352/build/teamcity-assert-clean.sh#L13)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This will automatically use 1.13 when that's released, no? Is that desirable?
</blockquote></details>

I thought so... To be honest I don't understand what this docker invocation does; how does it use go?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38379)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @petermattis and @RaduBerinde)

___
*[build/teamcity-assert-clean.sh, line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38379#-LiAZihzD-h9QgjyX_zu:-LiAe7inACAJgGASoVcn:bt21887) ([raw file](https://github.com/cockroachdb/cockroach/blob/521a52d185712e73a99d5124ff8314e8c17c6352/build/teamcity-assert-clean.sh#L13)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I thought so... To be honest I don't understand what this docker invocation does; how does it use go?
</blockquote></details>

I guess it's just a random image that has git in it. Now the question is why does it use docker... Jordan says that maybe the system git is too old. :man_shrugging:

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38379)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @petermattis)

___
*[build/teamcity-assert-clean.sh, line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38379#-LiAZihzD-h9QgjyX_zu:-LiAeppv4lN1ra0L7gpc:b-us88bo) ([raw file](https://github.com/cockroachdb/cockroach/blob/521a52d185712e73a99d5124ff8314e8c17c6352/build/teamcity-assert-clean.sh#L13)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I guess it's just a random image that has git in it. Now the question is why does it use docker... Jordan says that maybe the system git is too old. :man_shrugging: 
</blockquote></details>

Oh.. I didn't notice it just runs git. Weird.

There is another invocation here: https://github.com/cockroachdb/cockroach/blob/51179af7e2aced39a155b33c7437939e3d893890/build/teamcity-verify-archive.sh#L29

For that one my question stands. I think we should fix that to 1.12 or things might break when 1.13 gets released.

**Review by andreimatei — COMMENTED** [review]
Took over #38384 here.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38379#-:-LiAkuNm7X7s7_IsEW7a:bjpoh2l)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @petermattis and @RaduBerinde)

___
*[build/teamcity-assert-clean.sh, line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38379#-LiAZihzD-h9QgjyX_zu:-LiAk_JC7zzkM9UamJ20:b9hjarb) ([raw file](https://github.com/cockroachdb/cockroach/blob/521a52d185712e73a99d5124ff8314e8c17c6352/build/teamcity-assert-clean.sh#L13)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Oh.. I didn't notice it just runs git. Weird.

There is another invocation here: https://github.com/cockroachdb/cockroach/blob/51179af7e2aced39a155b33c7437939e3d893890/build/teamcity-verify-archive.sh#L29

For that one my question stands. I think we should fix that to 1.12 or things might break when 1.13 gets released.
</blockquote></details>

yup, fixed that one. Thanks.

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38379#-:-LiEJm518CR_DqcLr6OW:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @petermattis and @RaduBerinde)

**Review by andreimatei — COMMENTED** [review]
bors please

bors+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38379#-:-LiKAWep6E7fXpg9WGjz:b-6h7xay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @petermattis and @RaduBerinde)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38379#-:-LiL-aUJ9CQtfL51zcVj:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @petermattis and @RaduBerinde)

**Pull request merged**
