### PR TITLE
backupccl: stop blocking backup/restore jobs on client disconnect

### PR DESCRIPTION
**Pull request by pbardea**
Previously, a backup/restore job whose client disconnect might have blocked on
sending its results to the resultCh (and thus block forever). This
commit allows these jobs to complete.

Release note (bug fix): Previously, a BACKUP/RESTORE jobs would
sometimes block once it finished executing the job. This is now fixed.

### CODE REVIEW

**Review by dt — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51999)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by dt** [comment]
do we need to do RESTORE too?

**Comment by pbardea** [comment]
Yep, was going to follow up in a separate PR - but I may as well as bundle it with this one. Will push the changes here.

**Comment by pbardea** [comment]
Updated with RESTORE, RFAL.

**Review by dt — APPROVED** [review]

**Comment by pbardea** [comment]
TFTR!
bors r+

**Pull request merged**
