### PR TITLE
*: muck with package dependencies

### PR DESCRIPTION
**Pull request by andreimatei**
See individual commits.

These are the preliminary commits from #39722. I had to revert that PR because the final commit caused mysterious test flakiness, but these preliminary commits are still good - in particular I need to use the TestServer from the kv package (enabled by the 2nd commit).

### CODE REVIEW

**Comment by knz** [comment]
I sincerely apologize for letting this slip under the radar. Can you rebase? I'll be looking at it quicker this time.

**Review by andreimatei — COMMENTED** [review]
No worries. Rebased.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42925#-:-LyVB9hD4SlO9PauBsjx:bmt86d)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

**Review by knz — COMMENTED** [review]
First commit LGTM
2nd commit LGTM with nits
I think the 3rd commit contains a bug (the CI says so) but I'm not sure where. I'll look if/when you find the fix (let me know if you need help).

> Reviewed 109 of 109 files at r1, 5 of 5 files at r2, 4 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42925#-:-LyYa8J7AtmHv5Nyt83_:b-u2rk61)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @knz)

___
*[pkg/server/testserver.go, line 854 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42925#-LyY_bBa8DU0iZGGr1aX:-LyY_bBa8DU0iZGGr1aY:b5yiqli) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b0df6e6db67f9098b1d6ed596bc5cfa10da23a4/pkg/server/testserver.go#L854)):*
> ```Go
>  SELECT tables.id FROM system.namespace tables
>    JOIN system.namespace dbs ON dbs.id = tables."parentID"
>    WHERE dbs.name = $1 AND tables.name = $2
> ```

You need to constrain on the schema ID too here.
___
*[pkg/server/testserver.go, line 861 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42925#-LyY_hN76q6hwn_nXyZp:-LyY_hN89ovdSJj1KmlU:b-597q2g) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b0df6e6db67f9098b1d6ed596bc5cfa10da23a4/pkg/server/testserver.go#L861)):*
> ```Go
> 		return err
> 	}
> 	if row == nil {
> ```

This is redundant with the next condition I think.

**Review by andreimatei — COMMENTED** [review]
> I think the 3rd commit contains a bu

fixed

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42925#-:-Ly_KyPUDxwfJ33IRY7j:b-u1k8do)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/server/testserver.go, line 854 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42925#-LyY_bBa8DU0iZGGr1aX:-Ly_JVR9EpE19rccWjfv:b-cshao8) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b0df6e6db67f9098b1d6ed596bc5cfa10da23a4/pkg/server/testserver.go#L854)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

You need to constrain on the schema ID too here.
</blockquote></details>

Well, this only copies the existing functionality from the old `testutils/sqlutils/gc.go`. I'd rather not make it fancier in this patch. Let this testing utility be ignorant of schemas and return an error if tables with the same name exist in multiple schemas. I've documented it as such.
___
*[pkg/server/testserver.go, line 861 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42925#-LyY_hN76q6hwn_nXyZp:-Ly_KjTR5itYm-iBzv-x:b-d4dj7r) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b0df6e6db67f9098b1d6ed596bc5cfa10da23a4/pkg/server/testserver.go#L861)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This is redundant with the next condition I think.
</blockquote></details>

don't think so. row and err are both nil if no row is found.

**Review by knz — APPROVED** [review]
:lgtm: with super minor nits

@solongordon there's a surprising technical item for user-defined schemas in this PR, see my comment below

> Reviewed 9 of 20 files at r4, 5 of 5 files at r5, 6 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42925#-:-Ly_Sibo-8jU2BuhbxrW:b-bl3ecs)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/server/testserver.go, line 861 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42925#-LyY_hN76q6hwn_nXyZp:-Ly_SOMG4I3Ng8qIkUhN:b-o3o23i) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b0df6e6db67f9098b1d6ed596bc5cfa10da23a4/pkg/server/testserver.go#L861)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

don't think so. row and err are both nil if no row is found.
</blockquote></details>

I mean `if row == nil` is redundant with `if len(row) != 1`
___
*[pkg/testutils/serverutils/test_server_shim.go, line 168 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42925#-Ly_Sa83EP2Rz_DEwcyY:-Ly_Sa84E1zqBrDC9MCk:b-suzea8) ([raw file](https://github.com/cockroachdb/cockroach/blob/81eaf51b9f6a92f2fc9f47ac0b342699c39664e1/pkg/testutils/serverutils/test_server_shim.go#L168)):*
> ```Go
> 	//
> 	// An error will be returned if the same table name exists in multiple schemas
> 	// inside the specified database.
> ```

(Maybe add a comment to suggest that this property should be lifted if/when crdb is extended to support user-defined schemas)

Also ping @solongordon who is currently exploring this space.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42925)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @solongordon)

___
*[pkg/server/testserver.go, line 861 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42925#-LyY_hN76q6hwn_nXyZp:-Ly_YZtBD-8AZRFEsWzX:bn30voc) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b0df6e6db67f9098b1d6ed596bc5cfa10da23a4/pkg/server/testserver.go#L861)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I mean `if row == nil` is redundant with `if len(row) != 1`
</blockquote></details>

`len(row) != 1` refers to the number of columns in the row
___
*[pkg/testutils/serverutils/test_server_shim.go, line 168 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42925#-Ly_Sa83EP2Rz_DEwcyY:-Ly_YecT7ilcrrtKXje_:b-lrsx1d) ([raw file](https://github.com/cockroachdb/cockroach/blob/81eaf51b9f6a92f2fc9f47ac0b342699c39664e1/pkg/testutils/serverutils/test_server_shim.go#L168)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

(Maybe add a comment to suggest that this property should be lifted if/when crdb is extended to support user-defined schemas)

Also ping @solongordon who is currently exploring this space.
</blockquote></details>

I've soured on adding such TODOs. If I knew we didn't have multiple schemas (except we have the one for temp tables, right), I wouldn't have even the comment that I did add :P

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42925)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @solongordon)

___
*[pkg/server/testserver.go, line 861 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42925#-LyY_hN76q6hwn_nXyZp:-Lya2ji-1_6In0Yj2-Kd:byui41z) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b0df6e6db67f9098b1d6ed596bc5cfa10da23a4/pkg/server/testserver.go#L861)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

`len(row) != 1` refers to the number of columns in the row
</blockquote></details>

My point remains that `len(row) == 0` if `row == nil` so the `len(row) != 1` condition is sufficient for both cases

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42925)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @solongordon)

___
*[pkg/server/testserver.go, line 861 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42925#-LyY_hN76q6hwn_nXyZp:-LyaF0n64TR5RAxfbUWe:b3kwlq5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b0df6e6db67f9098b1d6ed596bc5cfa10da23a4/pkg/server/testserver.go#L861)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

My point remains that `len(row) == 0` if `row == nil` so the `len(row) != 1` condition is sufficient for both cases
</blockquote></details>

Well but the errors are (very) different. What can I say, I like typing.

**Review by andreimatei — COMMENTED** [review]
TFTR

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42925#-:-LyaFM_F09NqegM2XVbm:b-4as1hm)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @solongordon)

**Comment by knz** [comment]
as I wrote above the nits were very minor. you're the captain on this ship

**Pull request merged**
