### PR TITLE
colexec: begin to implement flat decimal columns

### PR DESCRIPTION
**Pull request by jordanlewis**
This commit changes the representation of the Decimals column in the
colexec package to be a wrapped flat Bytes representation. Instead of
storing values of apd.Decimal in a slice (which contain heap pointers),
we now store a serialized form of apd.Decimal in a flat bytes slice,
without any heap pointers. Then, to access the apd.Decimals at runtime,
we "deserialize" them in a close to zero-copy fashion, inflating an
apd.Decimal by pointing its internal varlen Coeff field directly at the
serialized bytes.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
I fixed up most things since I was curious in the benchmark numbers, and here is what I got (note that I modified the benchmark to use the decimals):
```
name                                                                 old time/op    new time/op    delta
Aggregator/MIN/hash/decimal/groupSize=1/numInputRows=32-24             52.2µs ± 1%    50.9µs ± 3%   -2.48%  (p=0.003 n=10+10)
Aggregator/MIN/hash/decimal/groupSize=1/numInputRows=32768-24          16.2ms ± 4%    17.3ms ± 4%   +6.70%  (p=0.000 n=10+10)
Aggregator/MIN/hash/decimal/groupSize=1024/numInputRows=32768-24       2.98ms ± 1%    3.17ms ± 1%   +6.23%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=32-24          32.7µs ± 5%    31.4µs ± 7%   -3.91%  (p=0.035 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=32768-24       2.08ms ± 0%    3.03ms ± 1%  +45.60%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1024/numInputRows=32768-24    1.32ms ± 0%    2.02ms ± 0%  +52.93%  (p=0.000 n=9+10)

name                                                                 old speed      new speed      delta
Aggregator/MIN/hash/decimal/groupSize=1/numInputRows=32-24           4.91MB/s ± 1%  5.03MB/s ± 3%   +2.57%  (p=0.003 n=10+10)
Aggregator/MIN/hash/decimal/groupSize=1/numInputRows=32768-24        16.2MB/s ± 4%  15.2MB/s ± 4%   -6.25%  (p=0.000 n=10+10)
Aggregator/MIN/hash/decimal/groupSize=1024/numInputRows=32768-24     88.0MB/s ± 1%  82.8MB/s ± 1%   -5.86%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=32-24        7.83MB/s ± 5%  8.15MB/s ± 7%   +4.14%  (p=0.030 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=32768-24      126MB/s ± 0%    87MB/s ± 1%  -31.32%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1024/numInputRows=32768-24   198MB/s ± 0%   130MB/s ± 0%  -34.61%  (p=0.000 n=9+10)

name                                                                 old alloc/op   new alloc/op   delta
Aggregator/MIN/hash/decimal/groupSize=1/numInputRows=32-24              106kB ± 0%     124kB ± 0%  +17.63%  (p=0.000 n=10+10)
Aggregator/MIN/hash/decimal/groupSize=1/numInputRows=32768-24          14.6MB ± 0%    14.3MB ± 0%   -2.65%  (p=0.000 n=9+10)
Aggregator/MIN/hash/decimal/groupSize=1024/numInputRows=32768-24       1.12MB ± 0%    1.03MB ± 0%   -8.05%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=32-24          73.7kB ± 0%    96.1kB ± 0%  +30.38%  (p=0.000 n=9+10)
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=32768-24        293kB ± 0%     353kB ± 0%  +20.21%  (p=0.000 n=10+6)
Aggregator/MIN/ordered/decimal/groupSize=1024/numInputRows=32768-24     210kB ± 0%     274kB ± 0%  +30.70%  (p=0.000 n=9+8)

name                                                                 old allocs/op  new allocs/op  delta
Aggregator/MIN/hash/decimal/groupSize=1/numInputRows=32-24                197 ± 0%       148 ± 0%  -24.87%  (p=0.000 n=10+10)
Aggregator/MIN/hash/decimal/groupSize=1/numInputRows=32768-24           32.3k ± 0%     27.2k ± 0%  -15.70%  (p=0.000 n=9+10)
Aggregator/MIN/hash/decimal/groupSize=1024/numInputRows=32768-24        4.93k ± 0%     0.80k ± 0%  -83.75%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=32-24            78.0 ± 0%      48.0 ± 0%  -38.46%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=32768-24        3.50k ± 0%     0.37k ± 0%  -89.53%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1024/numInputRows=32768-24       398 ± 0%       370 ± 0%   -7.04%  (p=0.000 n=10+10)
```

**Comment by jordanlewis** [comment]
Can you push a patch with your benchmark change too?

**Comment by yuzefovich** [comment]
Sure, I switched one place from value to pointer, rerunning the benchmarks.

**Comment by yuzefovich** [comment]
That didn't help (benchmarks only of the switching commit):
```
name                                                                 old time/op    new time/op    delta
Aggregator/MIN/hash/decimal/groupSize=1/numInputRows=32-24             51.7µs ± 2%    53.8µs ± 2%  +3.97%  (p=0.000 n=10+10)
Aggregator/MIN/hash/decimal/groupSize=1/numInputRows=32768-24          16.9ms ± 1%    17.6ms ± 4%  +4.29%  (p=0.000 n=10+10)
Aggregator/MIN/hash/decimal/groupSize=1024/numInputRows=32768-24       3.17ms ± 0%    3.17ms ± 1%    ~     (p=0.796 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=32-24          30.0µs ± 3%    30.6µs ± 1%  +2.02%  (p=0.017 n=10+9)
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=32768-24       3.04ms ± 0%    2.83ms ± 0%  -6.99%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1024/numInputRows=32768-24    2.04ms ± 0%    2.04ms ± 0%    ~     (p=0.853 n=10+10)

name                                                                 old speed      new speed      delta
Aggregator/MIN/hash/decimal/groupSize=1/numInputRows=32-24           4.95MB/s ± 2%  4.76MB/s ± 2%  -3.82%  (p=0.000 n=10+10)
Aggregator/MIN/hash/decimal/groupSize=1/numInputRows=32768-24        15.5MB/s ± 1%  14.9MB/s ± 3%  -4.09%  (p=0.000 n=10+10)
Aggregator/MIN/hash/decimal/groupSize=1024/numInputRows=32768-24     82.7MB/s ± 0%  82.7MB/s ± 1%    ~     (p=0.839 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=32-24        8.53MB/s ± 3%  8.36MB/s ± 1%  -2.00%  (p=0.018 n=10+9)
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=32768-24     86.2MB/s ± 0%  92.7MB/s ± 0%  +7.52%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1024/numInputRows=32768-24   129MB/s ± 0%   129MB/s ± 0%    ~     (p=0.810 n=10+10)

name                                                                 old alloc/op   new alloc/op   delta
Aggregator/MIN/hash/decimal/groupSize=1/numInputRows=32-24              124kB ± 0%     124kB ± 0%  +0.13%  (p=0.000 n=10+10)
Aggregator/MIN/hash/decimal/groupSize=1/numInputRows=32768-24          14.1MB ± 0%    14.2MB ± 0%  +1.11%  (p=0.000 n=10+8)
Aggregator/MIN/hash/decimal/groupSize=1024/numInputRows=32768-24       1.03MB ± 0%    1.03MB ± 0%  -0.03%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=32-24          96.1kB ± 0%    96.1kB ± 0%    ~     (all equal)
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=32768-24        353kB ± 0%     353kB ± 0%  -0.00%  (p=0.002 n=9+10)
Aggregator/MIN/ordered/decimal/groupSize=1024/numInputRows=32768-24     274kB ± 0%     274kB ± 0%  +0.04%  (p=0.000 n=7+8)

name                                                                 old allocs/op  new allocs/op  delta
Aggregator/MIN/hash/decimal/groupSize=1/numInputRows=32-24                148 ± 0%       150 ± 0%  +1.35%  (p=0.000 n=10+10)
Aggregator/MIN/hash/decimal/groupSize=1/numInputRows=32768-24           27.2k ± 0%     27.2k ± 0%  +0.06%  (p=0.000 n=10+10)
Aggregator/MIN/hash/decimal/groupSize=1024/numInputRows=32768-24          788 ± 0%       778 ± 0%  -1.27%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=32-24            48.0 ± 0%      48.0 ± 0%    ~     (all equal)
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=32768-24          366 ± 0%       366 ± 0%    ~     (all equal)
Aggregator/MIN/ordered/decimal/groupSize=1024/numInputRows=32768-24       362 ± 0%       366 ± 0%  +1.10%  (p=0.000 n=10+10)
```

**Comment by jordanlewis** [comment]
This commit is a hybrid, where we store a slice of `[]apd.Decimal` but put all of the backing memory into an adjacent flat Bytes struct. Still doesn't do anything better, but at least the memory is contiguous? Hmm..

```
name                                                                 old time/op    new time/op    delta
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=32-12          20.8µs ± 1%    31.0µs ± 2%   +48.84%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=32768-12       1.40ms ± 1%    1.84ms ± 2%   +31.31%  (p=0.000 n=8+9)
Aggregator/MIN/ordered/decimal/groupSize=1024/numInputRows=32768-12     911µs ± 7%     919µs ± 1%      ~     (p=0.739 n=10+10)

name                                                                 old speed      new speed      delta
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=32-12        12.3MB/s ± 0%   8.3MB/s ± 2%   -32.79%  (p=0.000 n=8+10)
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=32768-12      187MB/s ± 1%   143MB/s ± 2%   -23.84%  (p=0.000 n=8+9)
Aggregator/MIN/ordered/decimal/groupSize=1024/numInputRows=32768-12   288MB/s ± 7%   285MB/s ± 1%      ~     (p=0.739 n=10+10)

name                                                                 old alloc/op   new alloc/op   delta
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=32-12          73.7kB ± 0%   148.5kB ± 0%  +101.60%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=32768-12        293kB ± 0%     552kB ± 0%   +88.20%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1024/numInputRows=32768-12     210kB ± 0%     424kB ± 0%  +102.51%  (p=0.000 n=8+8)

name                                                                 old allocs/op  new allocs/op  delta
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=32-12            78.0 ± 0%      50.0 ± 0%   -35.90%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=32768-12        3.50k ± 0%     0.37k ± 0%   -89.45%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1024/numInputRows=32768-12       394 ± 0%       376 ± 0%    -4.57%  (p=0.000 n=10+10)
```

**Comment by jordanlewis** [comment]
Latest commit with completely flat representation has the following benchmark results:

```
name                                                                   old time/op    new time/op    delta
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=1-24             35.9µs ± 5%    32.6µs ± 2%   -9.21%  (p=0.000 n=9+10)
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=32-24            41.0µs ± 2%    37.9µs ± 5%   -7.50%  (p=0.000 n=8+10)
Aggregator/MIN/ordered/decimal/groupSize=2/numInputRows=32-24            38.6µs ± 3%    37.4µs ± 2%   -2.94%  (p=0.001 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=32/numInputRows=32-24           39.3µs ± 3%    36.7µs ± 2%   -6.76%  (p=0.000 n=9+9)
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=1024-24           155µs ± 2%     149µs ± 1%   -3.83%  (p=0.000 n=8+9)
Aggregator/MIN/ordered/decimal/groupSize=2/numInputRows=1024-24           155µs ± 2%     146µs ± 2%   -5.94%  (p=0.000 n=8+10)
Aggregator/MIN/ordered/decimal/groupSize=32/numInputRows=1024-24          135µs ± 2%     126µs ± 3%   -6.27%  (p=0.000 n=8+10)
Aggregator/MIN/ordered/decimal/groupSize=128/numInputRows=1024-24         125µs ± 3%     122µs ± 6%   -2.38%  (p=0.043 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1024/numInputRows=1024-24        125µs ± 3%     120µs ±10%   -4.65%  (p=0.005 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=32768-24         2.12ms ± 0%    2.43ms ± 2%  +14.62%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=2/numInputRows=32768-24         2.02ms ± 1%    2.07ms ± 1%   +2.56%  (p=0.000 n=10+9)
Aggregator/MIN/ordered/decimal/groupSize=32/numInputRows=32768-24        1.54ms ± 1%    1.52ms ± 1%   -1.44%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=128/numInputRows=32768-24       1.41ms ± 1%    1.43ms ± 1%   +0.86%  (p=0.002 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1024/numInputRows=32768-24      1.36ms ± 1%    1.36ms ± 1%     ~     (p=0.247 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=1048576-24       63.9ms ± 1%    77.2ms ± 1%  +20.77%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=2/numInputRows=1048576-24       61.2ms ± 1%    64.3ms ± 1%   +4.96%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=32/numInputRows=1048576-24      49.0ms ± 1%    48.8ms ± 2%     ~     (p=0.280 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=128/numInputRows=1048576-24     44.9ms ± 1%    44.6ms ± 1%     ~     (p=0.075 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1024/numInputRows=1048576-24    43.1ms ± 1%    42.7ms ± 1%   -0.91%  (p=0.004 n=10+10)

name                                                                   old speed      new speed      delta
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=1-24            223kB/s ± 6%   246kB/s ± 2%  +10.15%  (p=0.000 n=9+10)
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=32-24          6.25MB/s ± 2%  6.76MB/s ± 4%   +8.17%  (p=0.000 n=8+10)
Aggregator/MIN/ordered/decimal/groupSize=2/numInputRows=32-24          6.64MB/s ± 3%  6.84MB/s ± 2%   +3.03%  (p=0.001 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=32/numInputRows=32-24         6.51MB/s ± 2%  6.98MB/s ± 2%   +7.23%  (p=0.000 n=9+9)
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=1024-24        52.9MB/s ± 2%  55.0MB/s ± 1%   +3.97%  (p=0.000 n=8+9)
Aggregator/MIN/ordered/decimal/groupSize=2/numInputRows=1024-24        52.9MB/s ± 2%  56.3MB/s ± 2%   +6.33%  (p=0.000 n=8+10)
Aggregator/MIN/ordered/decimal/groupSize=32/numInputRows=1024-24       60.9MB/s ± 2%  64.9MB/s ± 3%   +6.72%  (p=0.000 n=8+10)
Aggregator/MIN/ordered/decimal/groupSize=128/numInputRows=1024-24      65.7MB/s ± 3%  67.3MB/s ± 6%   +2.52%  (p=0.043 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1024/numInputRows=1024-24     65.3MB/s ± 3%  68.7MB/s ±10%   +5.16%  (p=0.005 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=32768-24        123MB/s ± 0%   108MB/s ± 2%  -12.75%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=2/numInputRows=32768-24        130MB/s ± 1%   127MB/s ± 1%   -2.50%  (p=0.000 n=10+9)
Aggregator/MIN/ordered/decimal/groupSize=32/numInputRows=32768-24       170MB/s ± 1%   172MB/s ± 1%   +1.45%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=128/numInputRows=32768-24      185MB/s ± 1%   184MB/s ± 1%   -0.85%  (p=0.002 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1024/numInputRows=32768-24     192MB/s ± 1%   193MB/s ± 1%     ~     (p=0.247 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=1048576-24      131MB/s ± 1%   109MB/s ± 1%  -17.20%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=2/numInputRows=1048576-24      137MB/s ± 1%   131MB/s ± 1%   -4.72%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=32/numInputRows=1048576-24     171MB/s ± 1%   172MB/s ± 2%     ~     (p=0.280 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=128/numInputRows=1048576-24    187MB/s ± 1%   188MB/s ± 1%     ~     (p=0.075 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1024/numInputRows=1048576-24   195MB/s ± 1%   196MB/s ± 1%   +0.92%  (p=0.004 n=10+10)

name                                                                   old alloc/op   new alloc/op   delta
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=1-24             70.0kB ± 0%    91.3kB ± 0%  +30.55%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=32-24            73.7kB ± 0%    96.1kB ± 0%  +30.38%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=2/numInputRows=32-24            73.6kB ± 0%    96.1kB ± 0%  +30.60%  (p=0.000 n=8+10)
Aggregator/MIN/ordered/decimal/groupSize=32/numInputRows=32-24           73.4kB ± 0%    96.1kB ± 0%  +30.82%  (p=0.000 n=9+10)
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=1024-24           194kB ± 0%     249kB ± 0%  +28.63%  (p=0.000 n=10+8)
Aggregator/MIN/ordered/decimal/groupSize=2/numInputRows=1024-24           189kB ± 0%     249kB ± 0%  +31.44%  (p=0.000 n=8+9)
Aggregator/MIN/ordered/decimal/groupSize=32/numInputRows=1024-24          186kB ± 0%     249kB ± 0%  +34.20%  (p=0.000 n=9+10)
Aggregator/MIN/ordered/decimal/groupSize=128/numInputRows=1024-24         185kB ± 0%     249kB ± 0%  +34.32%  (p=0.000 n=9+10)
Aggregator/MIN/ordered/decimal/groupSize=1024/numInputRows=1024-24        185kB ± 0%     249kB ± 0%  +34.30%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=32768-24          293kB ± 0%     353kB ± 0%  +20.21%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=2/numInputRows=32768-24          291kB ± 0%     355kB ± 0%  +22.27%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=32/numInputRows=32768-24         221kB ± 0%     277kB ± 0%  +25.23%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=128/numInputRows=32768-24        213kB ± 0%     276kB ± 0%  +29.70%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1024/numInputRows=32768-24       210kB ± 0%     274kB ± 0%  +30.73%  (p=0.000 n=9+9)
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=1048576-24       1.12MB ± 0%    1.15MB ± 0%   +2.46%  (p=0.000 n=9+9)
Aggregator/MIN/ordered/decimal/groupSize=2/numInputRows=1048576-24       1.15MB ± 0%    1.22MB ± 0%   +5.52%  (p=0.000 n=9+10)
Aggregator/MIN/ordered/decimal/groupSize=32/numInputRows=1048576-24      1.16MB ± 0%    1.26MB ± 0%   +8.37%  (p=0.000 n=7+8)
Aggregator/MIN/ordered/decimal/groupSize=128/numInputRows=1048576-24     1.12MB ± 0%    1.22MB ± 0%   +8.90%  (p=0.000 n=8+8)
Aggregator/MIN/ordered/decimal/groupSize=1024/numInputRows=1048576-24     992kB ± 0%    1081kB ± 0%   +8.98%  (p=0.000 n=9+10)

name                                                                   old allocs/op  new allocs/op  delta
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=1-24               47.0 ± 0%      48.0 ± 0%   +2.13%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=32-24              78.0 ± 0%      48.0 ± 0%  -38.46%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=2/numInputRows=32-24              62.0 ± 0%      48.0 ± 0%  -22.58%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=32/numInputRows=32-24             47.0 ± 0%      48.0 ± 0%   +2.13%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=1024-24           1.07k ± 0%     0.05k ± 0%  -95.51%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=2/numInputRows=1024-24             558 ± 0%        50 ± 0%  -91.04%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=32/numInputRows=1024-24           80.0 ± 0%      56.0 ± 0%  -30.00%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=128/numInputRows=1024-24          54.0 ± 0%      52.0 ± 0%   -3.70%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1024/numInputRows=1024-24         47.0 ± 0%      48.0 ± 0%   +2.13%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=32768-24          3.50k ± 0%     0.37k ± 0%  -89.53%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=2/numInputRows=32768-24          3.03k ± 0%     0.46k ± 0%  -84.96%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=32/numInputRows=32768-24         1.51k ± 0%     0.47k ± 0%  -69.05%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=128/numInputRows=32768-24          676 ± 0%       448 ± 0%  -33.73%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1024/numInputRows=32768-24         398 ± 0%       372 ± 0%   -6.53%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1/numInputRows=1048576-24        15.4k ± 0%     10.3k ± 0%  -33.21%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=2/numInputRows=1048576-24        16.4k ± 0%     12.8k ± 0%  -21.93%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=32/numInputRows=1048576-24       16.5k ± 0%     14.3k ± 0%  -13.38%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=128/numInputRows=1048576-24      15.0k ± 0%     12.9k ± 0%  -14.02%  (p=0.000 n=10+10)
Aggregator/MIN/ordered/decimal/groupSize=1024/numInputRows=1048576-24     11.7k ± 0%     10.8k ± 0%   -8.41%  (p=0.000 n=10+10)
```

**Comment by jordanlewis** [comment]
This is 1 year late but thanks for taking this over the finish line @nvanbenschoten!

**Pull request closed without merging**
