### PR TITLE
kvserver: detail the range ID and replica details upon lease error

### PR DESCRIPTION
**Pull request by knz**
This logging if it had been present, would have simplified the investigation on https://github.com/cockroachlabs/support/issues/482

Release note: None

### CODE REVIEW

**Review by irfansharif — APPROVED** [review]
LGTM.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50211#-:-M9u7PfL6s5AFpCPMyTD:b-85i63v)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif, @knz, and @tbg)

___
*[pkg/kv/kvserver/replica_range_lease.go, line 554 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50211#-M9u76JH2NLwOIz3bcx-:-M9u76JIDAxP1x0oDwgj:bfyeack) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd3aeb9b28b659cd5365681c8b5c2ad7bc7ceefd/pkg/kv/kvserver/replica_range_lease.go#L554)):*
> ```Go
> 			if err != nil {
> 				if leaseStatusLogLimiter.ShouldLog() {
> 					log.Warningf(context.TODO(), "%s: can't determine lease status of %s due to node liveness error: %+v",
> ```

[nit] Would using using `ctx := r.AnnotateCtx()` work? For `r` at least.

**Review by tbg — APPROVED** [review]

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50211)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif)

___
*[pkg/kv/kvserver/replica_range_lease.go, line 554 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50211#-M9u76JH2NLwOIz3bcx-:-MCBjzgb4MqRgB8s6E5N:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd3aeb9b28b659cd5365681c8b5c2ad7bc7ceefd/pkg/kv/kvserver/replica_range_lease.go#L554)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

[nit] Would using using `ctx := r.AnnotateCtx()` work? For `r` at least.
</blockquote></details>

Good idea. Done.

**Comment by knz** [comment]
bors r=irfansharif,tbg

**Comment by knz** [comment]
bors r=irfansharif,tbg

**Pull request merged**
