### PR TITLE
roachprod: add pprof command

### LINKED ISSUE #62309: roachprod: commands for pprof profiling
Clusters set up with `roachprod` have pprof enabled and available at the admin URL given by `roachprod adminurl` under the path `/debug/pprof`. It would be useful with a few `roachprod` commands that automatically collected pprof profiles, e.g.:

* `roachprod pprofurl`: outputs the pprof URL.
* `roachprod pprof-profile`: automatically takes a pprof CPU profile, dumps it to a local timestamped file, generates e.g. a PDF file, and opens the pprof `web` UI.
* `roachprod pprof-heap`: similar to `pprof-profile`, but for a heap profile.

### PR DESCRIPTION
**Pull request by stevendanna**
The new pprof command allows to user to collect CPU and heap profiles
from nodes in a roachprod cluster using pprof's HTTP endpoints.

Profiles are collected in parallel and stored in the current working
directory of the machine running pprof. The command can also
optionally open the profiles using `go tool pprof`.

Some usage examples:

    # Capture CPU profile for all nodes in the cluster
    roachprod pprof CLUSTERNAME
    # Capture CPU profile for the first node in the cluster for 60 seconds
    roachprod pprof CLUSTERNAME:1 --duration 60s
    # Capture a Heap profile for the first node in the cluster
    roachprod pprof CLUSTERNAME:1 --heap
    # Same as above
    roachprod pprof-heap CLUSTERNAME:1

Fixes #62309

Note that I've skipped the `pprofurl` command in the original issue. I noticed that the `adminurl` 
command has an option to append any string you'd like to the URL, which is probably most of what one
needs from that command in most cases. But, I can add it if others feel differently.

Release note: None

### CODE REVIEW

**Review by erikgrinaker — CHANGES_REQUESTED** [review]
This is awesome, thank you!

>Note that I've skipped the pprofurl command in the original issue.

Probably fine, we can add it later if anyone really needs it. I just had to dig around a bit to figure it out, but people are likely to just use the pprof command anyway.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62796#-:-MX2zREk5A5YYt60gQ2R:b-dcqwhx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stevendanna)

___
*[pkg/cmd/roachprod/main.go, line 1517 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62796#-MX2zfBkB0TGX-MUPl1X:-MX2zfBkB0TGX-MUPl1Y:bntwlzs) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff99b824b4c74b0179383c2d4191b9241ba69d72/pkg/cmd/roachprod/main.go#L1517)):*
> ```Go
> 	Use:     "pprof <cluster>",
> 	Args:    cobra.ExactArgs(1),
> 	Aliases: []string{"pprof-cpu", "pprof-profile", "pprof-heap"},
> ```

If we're using `--heap` for the heap profile then maybe that's sufficient instead of cluttering up the command namespace?
___
*[pkg/cmd/roachprod/main.go, line 1551 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62796#-MX2zsrWD67_uFwIxF1z:-MX2zsrWD67_uFwIxF2-:bml5mif) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff99b824b4c74b0179383c2d4191b9241ba69d72/pkg/cmd/roachprod/main.go#L1551)):*
> ```Go
> 		mu := &syncutil.Mutex{}
> 		pprofPath := fmt.Sprintf("debug/pprof/%s?seconds=%d", profType, int(pprofOptions.duration.Seconds()))
> 		httpClient := httputil.NewClientWithTimeout(5 * pprofOptions.duration)
> ```

5x seems a bit excessive, maybe just add on a fixed 10 seconds or something?
___
*[pkg/cmd/roachprod/main.go, line 1560 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62796#-MX3-7uG77_8TcbrGV5K:-MX3-7uG77_8TcbrGV5L:bsbxmce) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff99b824b4c74b0179383c2d4191b9241ba69d72/pkg/cmd/roachprod/main.go#L1560)):*
> ```Go
> 				scheme = "https"
> 			}
> 			outputFile := fmt.Sprintf("pprof-%s-%s-%04d-%d.out", profType, c.Name, i, timeutil.Now().Unix())
> ```

We should probably generate the timestamp once outside of the loop, to ensure we don't get files with different timestamps if they happen right as the clock ticks. Also, I'd probably use the time before the index in the filename so that all profiles for the same run are grouped together.
___
*[pkg/cmd/roachprod/main.go, line 1562 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62796#-MX3-yud1u8hBEx9wfy_:-MX3-yud1u8hBEx9wfya:bysy9n) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff99b824b4c74b0179383c2d4191b9241ba69d72/pkg/cmd/roachprod/main.go#L1562)):*
> ```Go
> 			outputFile := fmt.Sprintf("pprof-%s-%s-%04d-%d.out", profType, c.Name, i, timeutil.Now().Unix())
> 			outputDir := filepath.Dir(outputFile)
> 			file, err := ioutil.TempFile(outputDir, ".pprof")
> ```

I don't think we end up closing this file. Not that it matters that much since we'll just be exiting the process anyway, but it's the polite thing to do and the linter will probably yell at you for it anyway.
___
*[pkg/cmd/roachprod/main.go, line 1602 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62796#-MX31MtLD0W0Z06AfNQj:-MX31MtLD0W0Z06AfNQk:b-72r4hm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff99b824b4c74b0179383c2d4191b9241ba69d72/pkg/cmd/roachprod/main.go#L1602)):*
> ```Go
> 
> 		for _, s := range outputFiles {
> 			fmt.Printf("Created %s\n", s)
> ```

Maybe just move this into the function above, and output as the files are ready?
___
*[pkg/cmd/roachprod/main.go, line 1617 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62796#-MX30qnf8zQ632dafY00:-MX30qnf8zQ632dafY01:betsbpf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff99b824b4c74b0179383c2d4191b9241ba69d72/pkg/cmd/roachprod/main.go#L1617)):*
> ```Go
> 			for i, file := range outputFiles {
> 				port := pprofOptions.startingPort + i
> 				cmd := exec.Command("go", "tool", "pprof",
> ```

Will ending the main process (e.g. with ctrl-C) also reap the child processes? If not, we may have to do something along these lines:

```
cmd.SysProcAttr = &syscall.SysProcAttr{
    Pdeathsig: syscall.SIGKILL,
}
```

Just to make sure we don't get background processes hogging the ports.

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62796)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

___
*[pkg/cmd/roachprod/main.go, line 1517 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62796#-MX2zfBkB0TGX-MUPl1X:-MX3Au2o2Ye-Lx6_6dyD:b22rwx3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff99b824b4c74b0179383c2d4191b9241ba69d72/pkg/cmd/roachprod/main.go#L1517)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

If we're using `--heap` for the heap profile then maybe that's sufficient instead of cluttering up the command namespace?
</blockquote></details>

I removed `pprof-cpu` and `pprof-profile`, but I left `pprof-heap` just because it kinda amuses me to allow that.  Perhaps in the morning I'll remove it to, I'll think about it. :D
___
*[pkg/cmd/roachprod/main.go, line 1551 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62796#-MX2zsrWD67_uFwIxF1z:-MX39_M_0mXovInK-vs_:b-cwvwl6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff99b824b4c74b0179383c2d4191b9241ba69d72/pkg/cmd/roachprod/main.go#L1551)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

5x seems a bit excessive, maybe just add on a fixed 10 seconds or something?
</blockquote></details>

The worry I had with that is that I believe that timeout includes downloading the response, so if you've generated a very large profile, it might take a long time to download, especially if you have slower home internet.
___
*[pkg/cmd/roachprod/main.go, line 1560 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62796#-MX3-7uG77_8TcbrGV5K:-MX3AqecBXFOXqNVje6x:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff99b824b4c74b0179383c2d4191b9241ba69d72/pkg/cmd/roachprod/main.go#L1560)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

We should probably generate the timestamp once outside of the loop, to ensure we don't get files with different timestamps if they happen right as the clock ticks. Also, I'd probably use the time before the index in the filename so that all profiles for the same run are grouped together.
</blockquote></details>

Good idea. Done.
___
*[pkg/cmd/roachprod/main.go, line 1562 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62796#-MX3-yud1u8hBEx9wfy_:-MX34Zri03vpY7Wppc2f:b-wjr266) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff99b824b4c74b0179383c2d4191b9241ba69d72/pkg/cmd/roachprod/main.go#L1562)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

I don't think we end up closing this file. Not that it matters that much since we'll just be exiting the process anyway, but it's the polite thing to do and the linter will probably yell at you for it anyway.
</blockquote></details>

Good catch. Interestingly the linter doesn't seem to catch this.  Perhaps we should add a linter for this.  We now close in the defer and we also close before the rename in the happy path.
___
*[pkg/cmd/roachprod/main.go, line 1602 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62796#-MX31MtLD0W0Z06AfNQj:-MX34lVTDiEc5rUxV7s4:b2plr16) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff99b824b4c74b0179383c2d4191b9241ba69d72/pkg/cmd/roachprod/main.go#L1602)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Maybe just move this into the function above, and output as the files are ready?
</blockquote></details>

Unfortunately ParallelE write progress to the terminal by updating the same line repeatedly which means that if we write it while that is still progressing, we either need to write them to stderr despite them not being errors or we lose the output line in most cases.
___
*[pkg/cmd/roachprod/main.go, line 1617 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62796#-MX30qnf8zQ632dafY00:-MX36xht6sMAnqOAH9Tj:b307y0v) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff99b824b4c74b0179383c2d4191b9241ba69d72/pkg/cmd/roachprod/main.go#L1617)):*
> Will ending the main process (e.g. with ctrl-C) also reap the child processes?

Ending the main process in general will not reap the children, but ctrl-C at the terminal will work.  Control-C at the terminal sends SIGINT to all process in the foreground process group which will include all the `go pprof` processes.  Since this is an "interactive" type feature I thought this would probably be sufficient, but happy to go further and handle signals more gracefully in general. 

`Pdeathsig` doesn't work on macOS AFAIK.  So I think there our best option might be a signal handler for the common signals we expect to kill us.

**Review by erikgrinaker — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62796#-:-MX3Dor146cOQuMCiTX-:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @stevendanna)

___
*[pkg/cmd/roachprod/main.go, line 1551 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62796#-MX2zsrWD67_uFwIxF1z:-MX3Cj9w5TjHAYp9j6Rq:b-swosj3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff99b824b4c74b0179383c2d4191b9241ba69d72/pkg/cmd/roachprod/main.go#L1551)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

The worry I had with that is that I believe that timeout includes downloading the response, so if you've generated a very large profile, it might take a long time to download, especially if you have slower home internet.
</blockquote></details>

Right, makes sense. I suppose we'd really want to use a timeout until the first byte of the body or something, but let's not complicate it, this is fine.
___
*[pkg/cmd/roachprod/main.go, line 1562 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62796#-MX3-yud1u8hBEx9wfy_:-MX3DVca55vy9aOdgCcR:bs2s8sl) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff99b824b4c74b0179383c2d4191b9241ba69d72/pkg/cmd/roachprod/main.go#L1562)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Good catch. Interestingly the linter doesn't seem to catch this.  Perhaps we should add a linter for this.  We now close in the defer and we also close after the rename in the happy path.
</blockquote></details>

Huh, that's odd, would've expected it to pick up on that.
___
*[pkg/cmd/roachprod/main.go, line 1602 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62796#-MX31MtLD0W0Z06AfNQj:-MX3DMYm7G82_TQ-ur8P:b76tsc6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff99b824b4c74b0179383c2d4191b9241ba69d72/pkg/cmd/roachprod/main.go#L1602)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Unfortunately ParallelE write progress to the terminal by updating the same line repeatedly which means that if we write it while that is still progressing, we either need to write them to stderr despite them not being errors or we lose the output line in most cases.
</blockquote></details>

Ah right, make sense.
___
*[pkg/cmd/roachprod/main.go, line 1617 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62796#-MX30qnf8zQ632dafY00:-MX3DOjp4GUAJks1zPnt:b5rj5bb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff99b824b4c74b0179383c2d4191b9241ba69d72/pkg/cmd/roachprod/main.go#L1617)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

> Will ending the main process (e.g. with ctrl-C) also reap the child processes?

Ending the main process will not reap the children, but ctrl-C at the terminal will work.  Control-C at the terminal sends SIGINT to all process in the foreground process group which will include all the `go pprof` processes.  Since this is an "interactive" type feature I thought this would probably be sufficient, but happy to go further and handle signals more gracefully in general. 

Because `Pdeathsig` doesn't work on macOS AFAIK so I think there our best option might be a signal handler for the common signals we expect to kill us.
</blockquote></details>

As long as Control-C does the right thing that's good enough for me, thanks!

**Comment by stevendanna** [comment]
bors r=erikgrinaker

**Pull request merged**
