### PR TITLE
jobs: add WithCancelOnQuiesce to the registry

### LINKED ISSUE #99242: jobs: job resumers are not sensitive to stopper Quiesce signal by default
The context.Context handed off to job resumers does not cancel on server shutdown.

This is surprising, and it can cause a job to "hold" the server shutdown process and create a perception of instability (node restart/shutdown hanging).

We should make that ctx cancel on shutdown by defaultt, and let specific jobs opt out if/when needed. 

Jira issue: CRDB-25811

### PR DESCRIPTION
**Pull request by adityamaru**
This change adds missing WithCancelOnQuiesce calls to
various callsites in the jobs registry. Previously, we were
relying on the registry to receive a signal when the server
began quiescing that then led to all adopted jobs being cancelled.
Recently, we have seen an uptick in tests failing because
of a `slow quiesce` during shutdown. Some of these stacks are
stuck in `pkg/jobs`. This change wraps the context used in these
asnyc tasks so that they receive a ctx cancellation signal when
the server is quiescing.

Release note: None
Epic: CRDB-8964
Fixes #99242

## flowinfra: fix recently introduced bug with row-based flow shutdown

This commit fixes a bug that was introduced in https://github.com/cockroachdb/cockroach/commit/a71e11c3137a3242a6780c70ab6c2062a31f504a
that I believe to be the root cause of "slow quiesce" CI failures we've
seen on `fakedist-vec-off` logic test config. In particular, the bug is
as follows: that commit made it so that if the handshake with the remote
node (when connecting the inbound stream) fails, we now "cancel" the
stream by marking it as "canceled" and decrementing the wait group.
However, one important piece of the proper cancellation was missed - we
also need to push an error to the receiver. We do that when the inbound
stream timeout timer fires but that commit forgot to do so on the
handshake error, and this is now fixed.

The incorrect assumption in https://github.com/cockroachdb/cockroach/commit/a71e11c3137a3242a6780c70ab6c2062a31f504a was
that canceling the context of the flow is sufficient for the proper
shutdown, but this turns out to not be the case in the row-based flows.
We have some components (e.g. `execinfra.RowChannel`) that will block
until `ProducerDone` is not called, and with just cancelling the context
that could never happen. Now that we properly push the error it will.
The vectorized flows aren't affected by this because there we do listen
for context cancellation signals.

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
Nice :100:

**Review by knz — APPROVED** [review]
cheers

**Review by miretskiy — APPROVED** [review]

**Comment by adityamaru** [comment]
Will wait for https://github.com/cockroachdb/cockroach/pull/99711 to go in before merging

**Comment by ajwerner** [comment]
I still see slow quiece errors with https://github.com/cockroachdb/cockroach/pull/99711 in bors: 

https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/9292616?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

**Comment by knz** [comment]
that flake you see in https://github.com/cockroachdb/cockroach/pull/99711 is the one that this PR is meant to fix. It seems to me that the two PRs should go in together before we assess what remains to be done.

**Review by rytaft — COMMENTED** [review]
Did you mean to add the flowinfra commit to this PR?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99609#-:-NRcvaf47rLL-d_Gakb_:brfbaus)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by adityamaru** [comment]
> Did you mean to add the flowinfra commit to this PR?

Yup! The two PRs seem to be stumbling over each other so we wanted to see if CI is green if we check in both together. I will update the PR description to reflect this once we verify that. We're discussing this over here - https://cockroachlabs.slack.com/archives/C02HWA24541/p1680010242480119

**Comment by adityamaru** [comment]
We're going to go ahead and merge this since CI is failing on flakes not related to `slow quiescing`.

bors r+

**Review by yuzefovich — APPROVED** [review]
> Reviewed 5 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99609)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru)

**Comment by knz** [comment]
bors r=knz,miretskiy,yuzefovich

**Pull request merged**
