### PR TITLE
opt: Do not decorrelate CASE when there may be side effects

### PR DESCRIPTION
**Pull request by andy-kimball**
An expression can have a side effect if it might trigger a run-time error,
might modify outside state, or might not always return the same output
given the same input. For example:

  10 / col          -- division by zero error possible
  nextval(seq)      -- modifies sequence value
  col < random()    -- random() returns different value on each call

CASE decorrelation is sensitive to side effects, because a CASE branch
can only be executed when its condition is true. This prevents hoisting
correlated subqueries in the usual way, since that would trigger premature
evaluation.

Release note: None

### CODE REVIEW

**Review by rytaft — CHANGES_REQUESTED** [review]
:lgtm: 

> Reviewed 18 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28178#-:-LIzsc6_9rfrJt4wjM5t:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/memo/logical_props_builder.go, line 1088 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28178#-LIzoM9o14m1U6VONk-F:-LIzoM9o14m1U6VONk-G:b-iu72yk) ([raw file](https://github.com/cockroachdb/cockroach/blob/765604b21f01f22f5d0c6b79ad0af827b3f44be8/pkg/sql/opt/memo/logical_props_builder.go#L1088)):*
> ```Go
> 
> 	case opt.DivOp:
> 		// Division by zero error is possible.
> ```

Is it worth checking here if the divisor is a non-zero constant?
___
*[pkg/sql/opt/norm/decorrelate.go, line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28178#-LIzq5332Qx3HnkokyRF:-LIzq5332Qx3HnkokyRG:b-x0hfje) ([raw file](https://github.com/cockroachdb/cockroach/blob/765604b21f01f22f5d0c6b79ad0af827b3f44be8/pkg/sql/opt/norm/decorrelate.go#L56)):*
> ```Go
> 			scalar.Rule.HasHoistableSubquery = true
> 
> 			switch ev.Operator() {
> ```

It would help to add a comment here to remind us of the structure of a CASE operation
___
*[pkg/sql/opt/norm/testdata/rules/comp, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28178#-LIzqVc_4HRMB4zLRev9:-LIzqVc_4HRMB4zLRevA:b-1mxr7q) ([raw file](https://github.com/cockroachdb/cockroach/blob/765604b21f01f22f5d0c6b79ad0af827b3f44be8/pkg/sql/opt/norm/testdata/rules/comp#L57)):*
> ```
>       └── a.s <= 'foo' [type=bool, outer=(4), constraints=(/4: (/NULL - /'foo']; tight)]
> 
> # Impure function should not be considered constant.
> ```

But the inequality is still getting commuted... is that a problem?
___
*[pkg/sql/opt/norm/testdata/rules/decorrelate, line 517 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28178#-LIzqiSo-7SGxF3W9ZAh:-LIzqiSo-7SGxF3W9ZAi:b-o91efd) ([raw file](https://github.com/cockroachdb/cockroach/blob/765604b21f01f22f5d0c6b79ad0af827b3f44be8/pkg/sql/opt/norm/testdata/rules/decorrelate#L517)):*
> ```
>  │    │    │    │    └── ordering: +1
>  │    │    │    └── projections [outer=(1,2), side-effects]
>  │    │    │         └── (a.i * a.i) / 5 [type=decimal, outer=(2), side-effects]
> ```

Here's an example where we're being too conservative with labeling this as side-effects (there are several more examples below)

**Review by RaduBerinde — APPROVED** [review]
:lgtm: modulo Becca's comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28178#-:-LIzuAhBATJ4xwcuFGpj:bxqmfgp)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28178)* status: :shipit: complete! 2 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/logical_props_builder.go, line 1088 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28178#-LIzoM9o14m1U6VONk-F:-LJ-vMBRCt4h2r2FB9af:bpc3vkb) ([raw file](https://github.com/cockroachdb/cockroach/blob/765604b21f01f22f5d0c6b79ad0af827b3f44be8/pkg/sql/opt/memo/logical_props_builder.go#L1088)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Is it worth checking here if the divisor is a non-zero constant?
</blockquote></details>

I thought about it when I wrote the code, but decided it's not worth it. I'd need to look for a constant, test for zero in various data types, etc. It'd make testing harder in quite an edge case (since it currently only matters in CASE branches in correlated subqueries).
___
*[pkg/sql/opt/norm/decorrelate.go, line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28178#-LIzq5332Qx3HnkokyRF:-LJ-yCtRE2DUWlRg4AUB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/765604b21f01f22f5d0c6b79ad0af827b3f44be8/pkg/sql/opt/norm/decorrelate.go#L56)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

It would help to add a comment here to remind us of the structure of a CASE operation
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/testdata/rules/comp, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28178#-LIzqVc_4HRMB4zLRev9:-LJ-yjf148XPXTaBq8ox:b-2suaef) ([raw file](https://github.com/cockroachdb/cockroach/blob/765604b21f01f22f5d0c6b79ad0af827b3f44be8/pkg/sql/opt/norm/testdata/rules/comp#L57)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

But the inequality is still getting commuted... is that a problem?
</blockquote></details>

Ah, it's getting commuted by another rule (`CommuteVarInequality`). I changed the test case to avoid that.

**Review by rytaft — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28178)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/memo/logical_props_builder.go, line 1088 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28178#-LIzoM9o14m1U6VONk-F:-LJ0C-NM1mLbIHqMs1tF:b2ni9b4) ([raw file](https://github.com/cockroachdb/cockroach/blob/765604b21f01f22f5d0c6b79ad0af827b3f44be8/pkg/sql/opt/memo/logical_props_builder.go#L1088)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I thought about it when I wrote the code, but decided it's not worth it. I'd need to look for a constant, test for zero in various data types, etc. It'd make testing harder in quite an edge case (since it currently only matters in CASE branches in correlated subqueries).
</blockquote></details>

ok!

**Review by andy-kimball — COMMENTED** [review]
I fixed several issues in my latest push:

- Stopped treating side-effecting expressions like constants when adding to FD set for `Project` logical props
- Fixed several bugs caused by accidental reuse of `FastIntSet`
- Fixed several failing CI tests
- Clarified optimizer side-effect policy in comment

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28178#-:-LJ6IP6Q5Nx3lTwm7hL8:bvjru1x)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Review by rytaft — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28178)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/memo/testdata/logprops/scalar, line 208 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28178#-LJEeTD1A19A3khx4w13:-LJEeTD1A19A3khx4w14:b-q1391c) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1f5cd6b995e5455ff2eedcfab8aae97f4e83da2/pkg/sql/opt/memo/testdata/logprops/scalar#L208)):*
> ```
>  │         │    ├── stats: [rows=1000, distinct(3)=1000]
>  │         │    ├── key: (1)
>  │         │    ├── fd: (1)-->(2,3)
> ```

This seems wrong now. x does not uniquely determine x/y.
___
*[pkg/sql/opt/props/logical.go, line 501 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28178#-LJEfjZv40C1Y5WvQ0NJ:-LJEfjZw78MvyDSlTOid:b-85q378) ([raw file](https://github.com/cockroachdb/cockroach/blob/765604b21f01f22f5d0c6b79ad0af827b3f44be8/pkg/sql/opt/props/logical.go#L501)):*
> ```Go
> 	if !p.Relational.NotNullCols.SubsetOf(p.Relational.OutputCols) {
> 		panic(fmt.Sprintf("not null cols %s not a subset of output cols %s",
> 			p.Relational.NotNullCols, p.Relational.OutputCols))
> ```

Why did you get rid of this check?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28178)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/memo/testdata/logprops/scalar, line 208 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28178#-LJEeTD1A19A3khx4w13:-LJEh7aDEwYv7E8ijm00:b-f9ybuv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1f5cd6b995e5455ff2eedcfab8aae97f4e83da2/pkg/sql/opt/memo/testdata/logprops/scalar#L208)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This seems wrong now. x does not uniquely determine x/y.
</blockquote></details>

Why not? `x` is a key..
___
*[pkg/sql/opt/props/logical.go, line 501 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28178#-LJEfjZv40C1Y5WvQ0NJ:-LJEhDgq2soeTQkcd65X:b-86j6m5) ([raw file](https://github.com/cockroachdb/cockroach/blob/765604b21f01f22f5d0c6b79ad0af827b3f44be8/pkg/sql/opt/props/logical.go#L501)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why did you get rid of this check?
</blockquote></details>

The logical props are already verified by `checkExpr`

**Comment by rytaft** [comment]
___
*[pkg/sql/opt/memo/testdata/logprops/scalar, line 208 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28178#-LJEeTD1A19A3khx4w13:-LJEhYIi3FvXMEAgCWEx:b63rvs7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1f5cd6b995e5455ff2eedcfab8aae97f4e83da2/pkg/sql/opt/memo/testdata/logprops/scalar#L208)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Why not? `x` is a key..
</blockquote></details>

Ah good point- never mind!

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28178#-:-LJEi4W4AkaZcIpfFxdS:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/props/logical.go, line 501 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28178#-LJEfjZv40C1Y5WvQ0NJ:-LJEhzjwCt_P6sElAMHZ:bjtb84p) ([raw file](https://github.com/cockroachdb/cockroach/blob/765604b21f01f22f5d0c6b79ad0af827b3f44be8/pkg/sql/opt/props/logical.go#L501)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The logical props are already verified by `checkExpr`
</blockquote></details>

got it - thanks!

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> Reviewed 10 of 18 files at r1, 3 of 4 files at r2, 10 of 11 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28178#-:-LJEjq9f98QQJEXHOsfR:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Review by andy-kimball — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28178#-:-LJEq4lj8QkiZR-BiYvz:b-ydi9ay)* status: :shipit: complete! 2 of 0 LGTMs obtained

**Pull request merged**
