### PR TITLE
kvclient: fix merge skew

### PR DESCRIPTION
**Pull request by andreimatei**
Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53088#-:-MF7wnYI8LYxW9sWgEge:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by otan** [comment]
heads up

> 🕐 Waiting for PR status (Github check) to be set, probably by CI. Bors will automatically try to run when all required PR statuses are set.

doesn't work

**Comment by ajwerner** [comment]
Ack

**Comment by irfansharif** [comment]
Re-running CI.

**Comment by ajwerner** [comment]
Is that smart? This test was added in the skewed commit

**Comment by ajwerner** [comment]
actually, ignore me

**Comment by ajwerner** [comment]
Flaked on https://github.com/cockroachdb/cockroach/issues/52706

**Comment by irfansharif** [comment]
Yup, I'd checked (sorry - should've linked).

**Pull request merged**
