### PR TITLE
authors: add Chen Chen to authors

### PR DESCRIPTION
**Pull request by nerdroychan**
Release note: None

### CODE REVIEW

**Review by nicktrav — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81396#-:-N2IK-jYD8bA_dctVeB2:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nerdroychan)

**Comment by nerdroychan** [comment]
bors r=nicktrav

**Comment by nerdroychan** [comment]
It seems that the current master is fixed so I will try again.

bors r=nicktrav

**Pull request merged**
