### PR TITLE
sql: use a range feed for refreshing the table stats cache

### LINKED ISSUE #47925: stats: break Gossip dependency
Table stats uses gossip to notify the nodes about new statistics:

https://github.com/cockroachdb/cockroach/blob/f176a39446e5235c9985a07f2550583dc106c26c/pkg/sql/stats/stats_cache.go#L79

[Multi-tenancy Phase 2](https://github.com/cockroachdb/cockroach/blob/f176a39446e5235c9985a07f2550583dc106c26c/pkg/sql/stats/stats_cache.go#L79) won't have gossip available. On the plus side, there will only be a single SQL server running on behalf of a tenant (meaning the use of Gossip is not necessary, you just need to notify the running process).

Post phase 2, when we consider multiple SQL servers for a given tenant, we need to properly substitute the use of Gossip, but for now here the work is to use Gossip only when it's available, but to unconditionally notify the local server. This suggests that the statistics cache should not know about gossip but should operate on a suitable notifier abstraction.

Tentatively marking as a blocker since I think we'll want to avoid disabling stats, even for the small workloads we expect to support in the beginning.

### PR DESCRIPTION
**Pull request by RaduBerinde**
We currently use gossip to keep table stats caches updated when new
statistics become available. This mechanism is not available in
multi-tenant configurations (currently we only support single SQL
nodes in that configuration and we refresh the cache on the same node
out of band).

This commit changes this mechanism to use a range feed that listens
for updates to system.table_statistics. This is a cleaner mechanism as
it doesn't require any out-of-band coordination.

The range feed events are on a row-by-row basis; a statistics
collection typically inserts multiple rows. We handle this by
remembering the timestamp of the table_statistics row that triggered
the last update. In addition, we remember information about the last
event to avoid unnecessary overhead.

Note that we continue to send gossip updates when new statistics are
available, to keep things working for mixed-version clusters during
upgrade.

Fixes #47925.

Release note: None

### CODE REVIEW

**Comment by andy-kimball** [comment]
Is there some version of this that will be back-ported to 21.1? Or perhaps some reason why we don't need this for an initial release that supports multiple SQL nodes?

**Review by ajwerner — APPROVED** [review]
:lgtm:

Needs a `bazel-generate`

Filed https://github.com/cockroachdb/cockroach/issues/62567 as an optimization so we stop shipping the histograms to all the nodes. 

> Reviewed 12 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62563#-:-MWaq0d91GbCQrPpukEV:b-egfj2w)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/stats/stats_cache.go, line 372 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62563#-MWarb41ENJaPIgLbVTg:-MWarb41ENJaPIgLbVTh:b86dp66) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a96225c98d42d196b04b20ee1f6861e53511433/pkg/sql/stats/stats_cache.go#L372)):*
> ```Go
> 			log.VEventf(ctx, 1, "refreshing statistics for table %d", tableID)
> 			// TODO(radu): pass the timestamp and use AS OF SYSTEM TIME.
> 			stats, err = sc.getTableStatsFromDB(ctx, tableID)
> ```

alternatively and maybe better, grab the timestamp from the rows you read and use that as the timestamp here by using `crdb_internal_mvcc_timetamp`

**Review by RaduBerinde — COMMENTED** [review]
TFTRs!

> Is there some version of this that will be back-ported to 21.1? Or perhaps some reason why we don't need this for an initial release that supports multiple SQL nodes?

My plan is to have this working on master for a while, and backport later (when we need it). At that time, I'll consider keeping both implementations and only using this when gossip is not available.

> Filed #62567 as an optimization so we stop shipping the histograms to all the nodes.

Hm, yeah, good catch. Sending out all this information is unfortunate.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62563#-:-MWdW12vEWIzCWtV3Fbz:bsgyplc)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/stats/stats_cache.go, line 372 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62563#-MWarb41ENJaPIgLbVTg:-MWdWL-j8kiZivW1quC6:b-yg91dr) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a96225c98d42d196b04b20ee1f6861e53511433/pkg/sql/stats/stats_cache.go#L372)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

alternatively and maybe better, grab the timestamp from the rows you read and use that as the timestamp here by using `crdb_internal_mvcc_timetamp`
</blockquote></details>

I don't understand the suggestion, can you expand? `getTableStatsFromDB` is the only place where we read the rows. I was thinking that since I already have the timestamp from the range feed, I can use it with AS OF SYSTEM TIME when reading the rows, and it might make a difference if the system is overloaded.

**Review by ajwerner — COMMENTED** [review]
FWIW, rangefeeds can be driven from followers so maybe that makes the data broadcast story slightly better. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62563#-:-MWddNxMEn03WWwJb4pj:b-9rmao5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/stats/stats_cache.go, line 372 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62563#-MWarb41ENJaPIgLbVTg:-MWdXzQ_BZ9f0TIicBxn:b-nxa4eu) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a96225c98d42d196b04b20ee1f6861e53511433/pkg/sql/stats/stats_cache.go#L372)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I don't understand the suggestion, can you expand? `getTableStatsFromDB` is the only place where we read the rows. I was thinking that since I already have the timestamp from the range feed, I can use it with AS OF SYSTEM TIME when reading the rows, and it might make a difference if the system is overloaded.
</blockquote></details>

That's reasonable. I was thinking if there were newer writes you hadn't yet seen that you could coalesce the future update on the fact that you've already read a later value. The AOST idea is fine too but because it's going to be close to the present I doubt you're going to get follower reads.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62563)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/stats/stats_cache.go, line 372 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62563#-MWarb41ENJaPIgLbVTg:-MWdeBnAAqwhtqVNV776:b-efxpl9) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a96225c98d42d196b04b20ee1f6861e53511433/pkg/sql/stats/stats_cache.go#L372)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

That's reasonable. I was thinking if there were newer writes you hadn't yet seen that you could coalesce the future update on the fact that you've already read a later value. The AOST idea is fine too but because it's going to be close to the present I doubt you're going to get follower reads. 
</blockquote></details>

Yeah. I'm not worried about the same table being updated twice in a short period of time, that shouldn't happen in practice.

We could sleep for a bit before issuing the AOST query. I'll maybe file an issue with these ideas/discussions, it won't be in this PR.

**Review by rytaft — APPROVED** [review]
Nice! :lgtm: 

> Reviewed 13 of 13 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62563#-:-MWis--0-l08sMvkZlxE:bfd61qr)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

___
*[pkg/sql/stats/stats_cache_test.go, line 495 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62563#-MWih8e_EWSDi-sIRw-1:-MWih8e_EWSDi-sIRw-2:b-27mbeb) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb30fd5b2528fce8a82ec176a3e2c5d42abd113e/pkg/sql/stats/stats_cache_test.go#L495)):*
> ```Go
> 	}
> 
> 	if err := expectNStats(0); err != nil {
> ```

do you need to explicitly disable automatic stats collection to prevent this from flaking?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62563)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner and @rytaft)

___
*[pkg/sql/stats/stats_cache_test.go, line 495 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62563#-MWih8e_EWSDi-sIRw-1:-MWjzb9v3AbEK-_oaSCj:b-ht89wy) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb30fd5b2528fce8a82ec176a3e2c5d42abd113e/pkg/sql/stats/stats_cache_test.go#L495)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

do you need to explicitly disable automatic stats collection to prevent this from flaking?
</blockquote></details>

Very good catch, yes! I produced a failure if I insert a large enough Sleep before this call. Fixed.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62563#-:-MWk7s1gBQLmjkmvS4zV:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

**Pull request merged**
