### PR TITLE
backupccl: do not backup or restore stat forecasts

### LINKED ISSUE #86806: backupccl: write table stats in order in backup metadata sst
#86078 caused the BackupMetadataSST writer to write out of order kvs related to table stats, causing the pebble writer to error, as seen in #86289. One working theory for why this occurs:

Backup currently pulls the stats out of the stats cache and then constructs keys to write into the SST.  After #86078, the cache now returns stats per-column stats; however, the keys backup generates look like they are just based on the table id and the stats id.  Now, perhaps each key is no longer unique when you put the per-columns stat forecasts in the mix.

Jira issue: CRDB-18943

### PR DESCRIPTION
**Pull request by stevendanna**
Statistics forecasts are not persisted and are reconstructed on demand from the persisted statistics. As such, they don't need to be included in a backup or restored.

This has the additional effect of solving a bug in which we would fail to write statistics into our metadata SST if it included more than 1 forecast since the in-memory forecasts have a 0 statistic_id.

Fixes #86806

Epic: none

Release note: None

### CODE REVIEW

**Review by michae2 — CHANGES_REQUESTED** [review]
Thank you for fixing this! Hope this wasn't too much of an inconvenience!

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94992#-:-NLRcqcp4OZfo1lh4x_0:bbdysst)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @benbardin and @stevendanna)

___
*[`pkg/ccl/backupccl/backup_job.go` line 376 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94992#-NLRZoAL3Pv_NVRZPcG5:-NLRZoAL3Pv_NVRZPcG6:bj91wxk) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d457d9426ab0b1e2f21a375860bca2f6e4d8a6e/pkg/ccl/backupccl/backup_job.go#L376)):*
> ```Go
> 				// from the persisted stats and do not
> 				// need to be backed up.
> 				if stat.Name == jobspb.ForecastStatsName {
> ```

Additionally, in v23.1 we also want to skip merged partial statistics, which can be detected with `stat.Name == jobspb.MergedStatsName`.
___
*[`pkg/ccl/backupccl/restore_job.go` line 532 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94992#-NLRb30p3tudtitJkr6K:-NLRb30q469M7_O4P0S9:bzggntq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d457d9426ab0b1e2f21a375860bca2f6e4d8a6e/pkg/ccl/backupccl/restore_job.go#L532)):*
> ```Go
> 	tableHasStatsInBackup := make(map[descpb.ID]struct{})
> 	for _, stat := range tableStatistics {
> 		if stat.Name == jobspb.ForecastStatsName {
> ```

We should also skip merged partial statistics here (`stat.Name == jobspb.MergedStatsName`).
___
*[`pkg/ccl/backupccl/testdata/backup-restore/metadata` line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94992#-NLRcIf7BUwiKv_KTwu3:-NLRcIf88wQP57FG9YWT:b-fg3h2r) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d457d9426ab0b1e2f21a375860bca2f6e4d8a6e/pkg/ccl/backupccl/testdata/backup-restore/metadata#L34)):*
> ```
> 
> # The previous bug occurs when there are two or more forecasts since
> # forecasts do not hava a statistics ID.
> ```

Note that whenever #86358 is fixed, forecasted stats will have a statistics ID. (And same for merged partial stats, eventually.)

**Comment by stevendanna** [comment]
@michae2 Good call on the merged stats as those also pose a problem.  Fixing that up actually exposed another potential problem. It seems like we aren't backing up partial statistics because they aren't returned from `(*TableStatisticsCache).GetTableStats`.

How would you feel about a new method on the stats cache that was something like GetTableStatsForBackup?

**Comment by stevendanna** [comment]
Restoring partial statistics might require us to complicate the code for restoring statistics a bit since partial statistics reference full statistics and those references would need to be fixed up on restore.

This seems like something we could do in a follow-up issue.

**Comment by stevendanna** [comment]
I opened https://github.com/cockroachdb/cockroach/issues/95056 to track the other issue.

**Comment by michae2** [comment]
> @michae2 Good call on the merged stats as those also pose a problem. Fixing that up actually exposed another potential problem. It seems like we aren't backing up partial statistics because they aren't returned from `(*TableStatisticsCache).GetTableStats`.
> 
> How would you feel about a new method on the stats cache that was something like GetTableStatsForBackup?
>
> I opened #95056 to track the other issue.

Ah, good catch. I think we will eventually want the optimizer to see partial stats via `GetTableStats` anyway, so let me quickly fix that.

> Restoring partial statistics might require us to complicate the code for restoring statistics a bit since partial statistics reference full statistics and those references would need to be fixed up on restore.
> 
> This seems like something we could do in a follow-up issue.

Yes, this is a problem. Also a problem for `ALTER TABLE ... INJECT STATISTICS`. One idea is to change [InsertNewStat](https://github.com/cockroachdb/cockroach/blob/32ef463dcff22546906298d86085cedbab85e0f7/pkg/sql/stats/new_stat.go#L65) to also insert the StatisticID. I can open an issue about this.

**Review by michae2 — APPROVED** [review]
:lgtm: Thank you!

> Reviewed 3 of 3 files at r2, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94992#-:-NLX9x6U8RfodlzTwASt:b-ae66e1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @benbardin and @stevendanna)

___
*[`pkg/ccl/backupccl/backup_job.go` line 426 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/94992#-NLX92Gn5zoOxJxdMRcR:-NLX92Go9ploO_-UnTB6:bmfvtk0) ([raw file](https://github.com/cockroachdb/cockroach/blob/9059e80fb518c233d2c338933a62b1e697086b89/pkg/ccl/backupccl/backup_job.go#L426)):*
> ```Go
> 	// stats on demand and do not need to be backed up or
> 	// restored.
> 	if stat.Name == jobspb.ForecastStatsName || stat.Name == jobspb.MergedStatsName {
> ```

nit: This could be simplified to `return stat.Name != jobspb.ForecastStatsName && stat.Name != jobspb.MergedStatsName`.

**Comment by stevendanna** [comment]
bors r=michae2

**Pull request merged**
