### PR TITLE
sql: fix username parsing for CURRENT_USER/SESSION_USER 

### LINKED ISSUE #54696: sql: ALTER SCHEMA OWNED BY SESSION_USER/CURRENT_USER does not work
`CURRENT_USER`/`SESSION_USER` should be special keywords, but our current syntax treats them as normal strings:

```
root@127.0.0.1:61524/movr> alter schema sc OWNER TO CURRENT_USER;
ERROR: role/user "current_user" does not exist
SQLSTATE: 42704
root@127.0.0.1:61524/movr> alter schema sc OWNER TO SESSION_USER;
ERROR: role/user "session_user" does not exist
SQLSTATE: 42704
root@127.0.0.1:61524/movr> alter schema sc OWNER TO admin;
ALTER SCHEMA

Time: 0.029s total (exec 10.2% / net 88.2% / other 1.6%)
```

### PR DESCRIPTION
**Pull request by RichardJCai**
Release note (sql change): Fix bug where previously CURRENT_USER and
SESSION_USER were parsed incorrectly.

Fixes https://github.com/cockroachdb/cockroach/issues/54696

### CODE REVIEW

**Review by knz — COMMENTED** [review]
I reviewed the tree and parser changes only. Generally OK, but I think there's some unnecessary complexity related to the formatting code.

> Reviewed 23 of 38 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70439#-:-Mk8d3LbAPXeJ4crxBFY:b-hwu3z7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @rafiss, and @RichardJCai)

___
*[pkg/sql/sem/tree/alter_database.go, line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70439#-Mk8c3ir0BDkm9JjzZK6:-Mk8c3isAWg5mGvmUh0d:bsf7k7x) ([raw file](https://github.com/cockroachdb/cockroach/blob/937f0336438f7871ebb53d800653c6238ea9efb1/pkg/sql/sem/tree/alter_database.go#L16)):*
> ```Go
> type AlterDatabaseOwner struct {
> 	Name Name
> 	// TODO(solon): Adjust this, see
> ```

Here and elsewhere, remove the TODOs that refer to this specific issue.
___
*[pkg/sql/sem/tree/format.go, line 389 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70439#-Mk8cEUJ5ERDEiqV1mp3:-Mk8cEUK5POaolalUnFe:bufp9ie) ([raw file](https://github.com/cockroachdb/cockroach/blob/937f0336438f7871ebb53d800653c6238ea9efb1/pkg/sql/sem/tree/format.go#L389)):*
> ```Go
> 
> // FormatRoleSpec formats a role specification safely.
> func (ctx *FmtCtx) FormatRoleSpec(spec RoleSpec) {
> ```

I see you also have a `Format` method on type `RoleSpec`
Then you don't need this one. Instead, do `ctx.FormatNode(&n.RoleSpec)` on the other nodes, which will also be easier to read and less error-prone.

**Comment by dt** [comment]
how disruptive to your work would it be to wait on merging sweeping refactors like this, at least if they're also hitting bulk io's packages, until we have a 21.2 RC cut? some teams, mine included, are trying to minimize refactor churn until RC 1 is tagged, so that if we need to prepare an urgent fix for a release-blocking issue, we don't have as much risk of unclean backports delaying it further

**Comment by RichardJCai** [comment]
> how disruptive to your work would it be to wait on merging sweeping refactors like this, at least if they're also hitting bulk io's packages, until we have a 21.2 RC cut? some teams, mine included, are trying to minimize refactor churn until RC 1 is tagged, so that if we need to prepare an urgent fix for a release-blocking issue, we don't have as much risk of unclean backports delaying it further

This can definitely wait, I'm actually just picking this up and other smaller issues because I'm waiting on the 21.2 RC cut to merge my other huge PR.

**Review by rafiss — APPROVED** [review]
this is great! just had a nit, then feel free to merge after 21.2 RC

after this are there any other usages of name_list or name for usernames in sql.y?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70439#-:-MkICAw-Br_bnAlu4fvY:b-5ggzgi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @knz, and @RichardJCai)

___
*[pkg/sql/sem/tree/create.go, line 1577 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70439#-MkIBtX44t5miC7VrD18:-MkIBtX44t5miC7VrD19:b1g86dz) ([raw file](https://github.com/cockroachdb/cockroach/blob/2064b155927bddb664e61f06c45b4fb1347002a4/pkg/sql/sem/tree/create.go#L1577)):*
> ```Go
> 	// TODO(solon): Adjust this, see
> 	// https://github.com/cockroachdb/cockroach/issues/54696
> 	AuthRole RoleSpec
> ```

nit: remove the todo

**Review by knz — COMMENTED** [review]
> This should be ok to merge now right?

I don't have further comments, but there's still one unaddressed comment by rafi.

> Reviewed 1 of 38 files at r1, 8 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70439#-:-MlkEkeU59__nDcL02j2:b-s6mu29)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @knz, and @RichardJCai)

**Comment by RichardJCai** [comment]
bors r=rafiss

**Pull request merged**
