### PR TITLE
sql: add precision support for TIMESTAMP/TIMESTAMPTZ (v2)

### LINKED ISSUE #32098: sql: support optional TIMESTAMP precision
**Is your feature request related to a problem? Please describe.**

`CREATE TABLE t(x TIMESTAMP(6))` should work

See: https://www.postgresql.org/docs/11/static/datatype-datetime.html#DATATYPE-TIMEZONES

> time, timestamp, and interval accept an optional precision value p which specifies the number of fractional digits retained in the seconds field. By default, there is no explicit bound on precision. The allowed range of p is from 0 to 6.

**Describe the solution you'd like**

MVP: An optional precision of 6 should be recognized and ignored (this is the default in CockroachDB)

Optionally: support for other precisions than 6.

**Workaround**

If the desired precision is 6, then the precision can be omitted altogether to obtain equivalent behavior.

### PR DESCRIPTION
**Pull request by otan**
Refs #32098
Alternative to #42552

----

Add precision support for TIMESTAMP/TIMESTAMPTZ, supporting precisions
from 0 to 6 inclusive.

When storing this in the type proto, we introduce a `TimePrecisionIsSet`
variable, which is used to differentiate 0 (unset) or 0 (explicitly set)
for time related protos. This is abstracted away in the `Precision()`
function which returns the correct precision (unset => 6) for time. This
allows forwards and backwards compatibility.

Note Time will come later, as it involves a bit more plumbing to the
base library.

Release note (sql change): Introduces precision support for TIMESTAMP
and TIMESTAMPTZ, supporting precisions from 0 to 6 inclusive. Previous
versions of TIMESTAMP and TIMESTAMPTZ will default to 6 units of
precision. Note that if anyone downgrades whilst having precision set,
they will have full precision (6) again, but if they re-upgrade they
will find their precisions truncated again.

### CODE REVIEW

**Review by solongordon — CHANGES_REQUESTED** [review]
A few nits but generally looks great!

> Reviewed 19 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42580#-:-Lu9nn1G4mlSboODcRwW:b-5ws8os)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rohany)

___
*[pkg/sql/sem/tree/datum.go, line 2118 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42580#-Lu9eqfu1SeE7i7G_ftz:-Lu9eqfu1SeE7i7G_fu-:b-6wycqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/9834dca684b947b36f41ee8613405a0b5aabc601/pkg/sql/sem/tree/datum.go#L2118)):*
> ```Go
> }
> 
> // Round returns a new DTimestampTZ to the specified precision.
> ```

Nit: `DTimestamp`
___
*[pkg/sql/sem/tree/time_test.go, line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42580#-Lu9jkRa8-Q8NU0NVcvL:-Lu9jkRa8-Q8NU0NVcvM:bt4k4ub) ([raw file](https://github.com/cockroachdb/cockroach/blob/9834dca684b947b36f41ee8613405a0b5aabc601/pkg/sql/sem/tree/time_test.go#L21)):*
> ```Go
> )
> 
> func TestPrecisionToTruncDuration(t *testing.T) {
> ```

Nit: misnamed?
___
*[pkg/sql/types/types.go, line 701 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42580#-Lu9ktdX-ur_zJmn4-DY:-Lu9ktdX-ur_zJmn4-DZ:b-xacvi2) ([raw file](https://github.com/cockroachdb/cockroach/blob/9834dca684b947b36f41ee8613405a0b5aabc601/pkg/sql/types/types.go#L701)):*
> ```Go
> // the given number of fractional second digits.
> //
> // If precision is -1, it will return the default precision.
> ```

I may be missing something but what is the purpose of accepting -1? Seems like it is only passed by tests, which could just use `Timestamp` instead.
___
*[pkg/sql/types/types.go, line 720 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42580#-Lu9kzDu5dXsFAxNbKC6:-Lu9kzDu5dXsFAxNbKC7:bosql9o) ([raw file](https://github.com/cockroachdb/cockroach/blob/9834dca684b947b36f41ee8613405a0b5aabc601/pkg/sql/types/types.go#L720)):*
> ```Go
> // most the given number of fractional second digits.
> //
> // If precision is -1, it will return the default precision.
> ```

Same question about accepting -1.
___
*[pkg/sql/types/types.proto, line 408 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42580#-Lu9nN-FBrgQ8q3xRdqV:-Lu9nN-FBrgQ8q3xRdqW:bjeuk4j) ([raw file](https://github.com/cockroachdb/cockroach/blob/9834dca684b947b36f41ee8613405a0b5aabc601/pkg/sql/types/types.proto#L408)):*
> ```protobuf
>     //   * If Precision is 0, it will default to 6 if TimePrecisionIsSet is false
>     //    (for compatibility reasons).
>     //   * Otherwise, the precision is 6.
> ```

Did you mean 0?

**Comment by solongordon** [comment]
One more thought: when we discovered that the previous implementation of this was not backward compatible, @andy-kimball highlighted that we have `Marshal` and `Unmarshal` functions in `types.go` intended for managing backward compatibility between protobuf versions. I _think_ it's unnecessary to modify those here because your changes are already backward compatible, but perhaps worth a look to double-check.

**Review by otan — COMMENTED** [review]
Ah, that would've been useful as well, but I think with the way this is done we don't have to bother with doing that.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42580#-:-LuA440qBvYeeSSQQ1Qq:bl3vm9b)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany and @solongordon)

___
*[pkg/sql/types/types.go, line 701 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42580#-Lu9ktdX-ur_zJmn4-DY:-LuA32LCB0m-fu1HEm3S:b-oxrn78) ([raw file](https://github.com/cockroachdb/cockroach/blob/9834dca684b947b36f41ee8613405a0b5aabc601/pkg/sql/types/types.go#L701)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I may be missing something but what is the purpose of accepting -1? Seems like it is only passed by tests, which could just use `Timestamp` instead.
</blockquote></details>

Yeah I think that's cleaner. changing!
___
*[pkg/sql/types/types.go, line 720 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42580#-Lu9kzDu5dXsFAxNbKC6:-LuA347D7pmSgh1iCIXv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9834dca684b947b36f41ee8613405a0b5aabc601/pkg/sql/types/types.go#L720)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Same question about accepting -1.
</blockquote></details>

Done.
___
*[pkg/sql/types/types.proto, line 408 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42580#-Lu9nN-FBrgQ8q3xRdqV:-LuA3Iqc9I5xcJpvh5HX:bgwt34x) ([raw file](https://github.com/cockroachdb/cockroach/blob/9834dca684b947b36f41ee8613405a0b5aabc601/pkg/sql/types/types.proto#L408)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Did you mean 0?
</blockquote></details>

Yes. Fixed!

**Review by solongordon — APPROVED** [review]
Nit: Your commit message still references the `-1` business.

:lgtm: modulo a couple nits!

> Reviewed 2 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42580#-:-LuA5exQDWqICI2TYX_3:bvad01y)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan, @rohany, and @solongordon)

___
*[pkg/sql/types/types.go, line 711 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42580#-LuA56qCDlpbqlCkvbDR:-LuA56qD1LLhAeBffF_Y:b-qpxieu) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d8e3030d818d125063cd63759d8be212a40e8ad/pkg/sql/types/types.go#L711)):*
> ```Go
> // most the given number of fractional second digits.
> //
> // To use the default, use the `Timestamp` variable.
> ```

Nit: `TimestampTZ`

**Review by solongordon — COMMENTED** [review]
And I believe the intention is to backport this fix to the release-19.2 branch. (See https://github.com/benesch/backport to make this process easy.)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42580#-:-LuA6r5S3q5RMQgMw3hS:bdghmyf)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan, @rohany, and @solongordon)

**Review by otan — COMMENTED** [review]
Are we sure about backporting this? Seems like a strictly new feature instead of a bug fix?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42580#-:-LuA9BhKAHzs06fD4HHW:b-1xfw7p)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rohany and @solongordon)

**Comment by otan** [comment]
we can discuss the backporting afterwards - thanks for the review!

bors r+

**Pull request merged**
