### PR TITLE
kv: split LockConflictError, revive WriteIntentError over wire

### LINKED ISSUE #113271: [error while unmarshalling cockroach.kv.kvpb.LockConflictError] roachtest: backup-restore/mixed-version failed
roachtest.backup-restore/mixed-version [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12401722?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12401722?buildTab=artifacts#/backup-restore/mixed-version) on release-23.2 @ [6aa847e0e6f7eb6ab26dd9b150f165ccae9dd2c6](https://github.com/cockroachdb/cockroach/commits/6aa847e0e6f7eb6ab26dd9b150f165ccae9dd2c6):

```
(mixedversion.go:538).Run: mixed-version test failure while running step 20 (run "plan and run backups"): error waiting for job to finish: job 912597787176796161 failed with error: failed to run backup: exporting 837 ranges: exporting /Table/182/1/29{1-2}: conflicting locks on /Table/182/1/291/0 [reason=wait_policy]
test artifacts and logs in: /artifacts/backup-restore/mixed-version/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=true</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-12401722/backup-restore-mixed-version/1698570340569/1698573400305)

</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*backup-restore/mixed-version.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-32841

### PR DESCRIPTION
**Pull request by nvb**
Fixes #113271.

This commit resolves the backwards incompatibility introduced by 350dc60b when `WriteIntentError` was renamed to `LockConflictError`. This rename broke mixed-version compatibility, because error details in `kvpb.Error` are packaged into an `errorspb.EncodedError`, which internally uses a `protobuf/types.Any`. `protobuf/types.Any` encodes the error's name as a string, relying on the receiving node having a matching type in order to decode the error.

Without this, we saw the following logs on v23.1 nodes.
```
error while unmarshalling error: ‹any: message type "cockroach.kv.kvpb.LockConflictError" isn't linked
```
As a result, error handling for requests that used `WaitPolicy_Error` was broken.

This commit resolves the issue by re-introducing `WriteIntentError` over the wire, so that v23.1 and v23.2 nodes still use the same name to refer to the same error. It does so without reverting 350dc60b and losing the naming improvement in most of the code by splitting `LockConflictError` into its two distinct roles. `LockConflictError` remains in the kvserver to communicate locking conflicts between batch evaluation and concurrency handling. However, the smaller role of communicating locking conflicts to clients that use a `WaitPolicy_Error`, a lock timeout, or a maximum wait-queue length is split into a "new" error called `WriteIntentError`. Splitting these errors was a cleanup we wanted to do anyway, so this commit just does it now to fix the bug. The unfortunate naming of `WriteIntentError` is a battle that we can fight another day.

While this commit doesn't introduce any new tests, we have sufficient testing of the two uses of `WriteIntentError` for single-version clusters in the unit tests. For mixed-version clusters, we have the `backup-restore/mixed-version` roachtest, which caught the bug and exercises backup's use of `WriteIntentError`.

The remaining place where this broke mixed-version compatibility was `SELECT FOR UPDATE NOWAIT`. We should add mixed-version testing for all `SELECT FOR UPDATE` variants. In the meantime, I have manually verified that the following script works on a mixed-version cluster:
```
roachprod create nathan-113271 -n3
roachprod stage  nathan-113271 release v23.1.11
roachprod start  nathan-113271
roachprod stop   nathan-113271:2-3
roachprod put    nathan-113271:2-3 cockroach # with this commit
roachprod start  nathan-113271:2-3 --sequential=false

roachprod sql nathan-113271:1
roachprod sql nathan-113271:2

-- either shell
create table t(i int primary key);
insert into t values (1);
select lease_holder from [show ranges from table t with details];
alter table t scatter;

-- 23.2 shell
begin; select * from t for update;

-- 23.1 shell
begin; select * from t for update nowait;

-- if broken:
ERROR: conflicting locks on /Table/104/1/1/0 [reason=wait_policy]
-- if fixed:
ERROR: could not obtain lock on row (i)=(1) in t@t_pkey

-- same thing but in opposite direction, with 23.1 leaseholder and 23.2 gateway
```

Release note: None

### CODE REVIEW

**Review by arulajmani — COMMENTED** [review]
> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113646)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @dt, and @nvanbenschoten)

___
*[`pkg/kv/kvpb/errors.go` line 327 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113646#-NiFEy9ODrdUOUPsdxFu:-NiFEy9ODrdUOUPsdxFv:btx67u9) ([raw file](https://github.com/cockroachdb/cockroach/blob/f294b3649e14115fd16193634e57f3673828e50c/pkg/kv/kvpb/errors.go#L327)):*
> ```Go
> 	errors.RegisterTypeMigration(roachpbPath, "*roachpb.TransactionRetryError", &TransactionRetryError{})
> 	errors.RegisterTypeMigration(roachpbPath, "*roachpb.TransactionStatusError", &TransactionStatusError{})
> 	errors.RegisterTypeMigration(roachpbPath, "*roachpb.WriteIntentError", &WriteIntentError{})
> ```

Do we still need this?
___
*[`pkg/kv/kvpb/errors.proto` line 317 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113646#-NiFIBLY5Uie2cyk5h_j:-NiFIBLZ6Gm_Gg5wN-81:bjm0an2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f294b3649e14115fd16193634e57f3673828e50c/pkg/kv/kvpb/errors.proto#L317)):*
> ```proto
> //
> // Unlike WriteIntentError, LockConflictError is never returned from the
> // kvserver. Instead, it is only used internally by concurrency control.
> ```

nit: would it make sense to use a regular go error instead to prevent accidentally returning this across RPC boundaries? 
___
*[`pkg/kv/kvpb/errors.proto` line 357 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113646#-NiFGchd7OH6HcGRc8Vw:-NiFGchd7OH6HcGRc8Vx:b-u59ipq) ([raw file](https://github.com/cockroachdb/cockroach/blob/f294b3649e14115fd16193634e57f3673828e50c/pkg/kv/kvpb/errors.proto#L357)):*
> ```proto
> // returned for any conflicting lock, regardless of locking strength.
> // The naming is an artifact of a time when intents were the only form
> // of lock, and renames have proven difficult (see #113271). One day
> ```

We could teach the client on 23.2 to expect both `WriteIntentErrors` and `LockConflictErrors`[*]. Then, in 24.1, we could switch the server to start returning `LockConflictErrors` instead of `WriteIntentErrors`. 

[*] I see that the commit message says we wanted to add a split anyway, so maybe instead of re-using `LockConflictErrors` we would introduce a new, better named alternative to `WriteIntentError`.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113646)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @DrewKimball, and @dt)

___
*[`pkg/kv/kvpb/errors.go` line 327 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113646#-NiFEy9ODrdUOUPsdxFu:-NiLMjl82BvGFLgnPaSD:bomcec2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f294b3649e14115fd16193634e57f3673828e50c/pkg/kv/kvpb/errors.go#L327)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Do we still need this?
</blockquote></details>

I think we do still need the mapping from the `roachpb` to `kvpb` package.

`LockConflictError` was never released in the `roachpb` package though, so we don't need to register the type migration for that type.
___
*[`pkg/kv/kvpb/errors.proto` line 317 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113646#-NiFIBLY5Uie2cyk5h_j:-NiLN63rEGKTxKam1mDb:b1wd5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f294b3649e14115fd16193634e57f3673828e50c/pkg/kv/kvpb/errors.proto#L317)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: would it make sense to use a regular go error instead to prevent accidentally returning this across RPC boundaries?
</blockquote></details>

This is still packaged into a `kvpb.Error` and pulled out of the details in functions like `isConcurrencyRetryError`, so I'm ok with it remaining a proto error.
___
*[`pkg/kv/kvpb/errors.proto` line 357 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113646#-NiFGchd7OH6HcGRc8Vw:-NiLNg7U1Ahly1sAiTqm:bniqhqr) ([raw file](https://github.com/cockroachdb/cockroach/blob/f294b3649e14115fd16193634e57f3673828e50c/pkg/kv/kvpb/errors.proto#L357)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

We could teach the client on 23.2 to expect both `WriteIntentErrors` and `LockConflictErrors`[*]. Then, in 24.1, we could switch the server to start returning `LockConflictErrors` instead of `WriteIntentErrors`. 

[*] I see that the commit message says we wanted to add a split anyway, so maybe instead of re-using `LockConflictErrors` we would introduce a new, better named alternative to `WriteIntentError`.
</blockquote></details>

That's actually exactly what I was planning to do before I realized that we had wanted to introduce this split. I think it's a good idea, but I don't think the benefits (a rename) outweigh the risks (possible bugs) at this point in the release cycle.

**Review by arulajmani — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113646#-:-NiLUKhS5WWhYMOX42iS:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball, @dt, and @nvanbenschoten)

___
*[`pkg/kv/kvpb/errors.go` line 327 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113646#-NiFEy9ODrdUOUPsdxFu:-NiLU6_-C95QI5BW84YZ:b3nvpn1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f294b3649e14115fd16193634e57f3673828e50c/pkg/kv/kvpb/errors.go#L327)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think we do still need the mapping from the `roachpb` to `kvpb` package.

`LockConflictError` was never released in the `roachpb` package though, so we don't need to register the type migration for that type.
</blockquote></details>

I misunderstood what this was about. Nvm me. 
___
*[`pkg/kv/kvpb/errors.proto` line 357 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113646#-NiFGchd7OH6HcGRc8Vw:-NiLTxEMDQsixWDLXaeL:b-dw37up) ([raw file](https://github.com/cockroachdb/cockroach/blob/f294b3649e14115fd16193634e57f3673828e50c/pkg/kv/kvpb/errors.proto#L357)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

That's actually exactly what I was planning to do before I realized that we had wanted to introduce this split. I think it's a good idea, but I don't think the benefits (a rename) outweigh the risks (possible bugs) at this point in the release cycle.
</blockquote></details>

Yeah, makes sense on the risk reward analysis. Maybe something to keep in mind for the 24.1 cycle, if we're smart and motivated :rocket:

**Comment by nvanbenschoten** [comment]
TFTR!

bors r+

**Pull request merged**
