### PR TITLE
sql: remove transitioning regions from zone config validation

### PR DESCRIPTION
**Pull request by otan**
See individual commits for details.

Refs: #63462

### CODE REVIEW

**Review by ajstorm — APPROVED** [review]
:lgtm: 

What's your hope for backporting this change?  I'd suggest we hold off on backporting this until the `.1` release, as it's all just validation and refactoring.  

> Reviewed 5 of 5 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63502#-:-MYArq_d9o0tlvnO7Ygd:bb48d34)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani, @dt, and @otan)

___
*[pkg/sql/region_util.go, line 1429 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63502#-MYAmrOM7qHvsQuwX1so:-MYAmrOM7qHvsQuwX1sp:b-kaqadw) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e543621a81be7953bee980a6493beec952c693d/pkg/sql/region_util.go#L1429)):*
> ```Go
> 		return err
> 	}
> 	regionConfig, err := SynthesizeRegionConfig(ctx, p.txn, dbDesc.GetID(), p.Descriptors())
> ```

For my benefit, is this no longer needed because we've moved the zone config writing to finalize?
___
*[pkg/sql/region_util.go, line 1011 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63502#-MYArk495qdlor-Tj_O6:-MYArk495qdlor-Tj_O7:b-tsfkro) ([raw file](https://github.com/cockroachdb/cockroach/blob/874c2b5a9e2452d31c91533a34387ba2e0e530c6/pkg/sql/region_util.go#L1011)):*
> ```Go
> 		regionNames, err = regionEnum.RegionNames()
> 	}
> 	if err != nil {
> ```

Nit: should this be in the first commit?
___
*[pkg/sql/catalog/typedesc/type_desc.go, line 199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63502#-MYAjPbC0Qbgu2dGRnnT:-MYAjPbC0Qbgu2dGRnnU:bucvwch) ([raw file](https://github.com/cockroachdb/cockroach/blob/04982f4c75b4f761076ddc8653bf9e18ec7dc7be/pkg/sql/catalog/typedesc/type_desc.go#L199)):*
> ```Go
> }
> 
> // TransitioningRegionNames returns regions where are not `PUBLIC` and are in the
> ```

Nit: where -> which

**Review by arulajmani — COMMENTED** [review]
Can we add a test for the first commit which would have required the session variable to be set (us being too strict) but works now?

Also, :100: on the second commit here -- it cleans things up quite well! :smile: 

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63502#-:-MYBMDAeDSQGu_hy-1Fj:b-dnxkqk)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt and @otan)

___
*[pkg/sql/region_util.go, line 1044 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63502#-MYAgeMW5fxDcHorfM63:-MYAgeMW5fxDcHorfM64:buj3fh) ([raw file](https://github.com/cockroachdb/cockroach/blob/04982f4c75b4f761076ddc8653bf9e18ec7dc7be/pkg/sql/region_util.go#L1044)):*
> ```Go
> 		dbDesc.GetRegionConfig().SurvivalGoal,
> 		regionEnumID,
> 		multiregion.MakeRegionConfigOptionTransitioningRegions(transitioningRegionNames),
> ```

nit: rename this to something like `WithTransitioningRegions` for readability
___
*[pkg/sql/region_util.go, line 948 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63502#-MYBLVly1bSimMtxY6GO:-MYBLVly1bSimMtxY6GP:b-9ct3yc) ([raw file](https://github.com/cockroachdb/cockroach/blob/874c2b5a9e2452d31c91533a34387ba2e0e530c6/pkg/sql/region_util.go#L948)):*
> ```Go
> // SynthesizeRegionConfigOptionIncludeOffline includes offline descriptors for use
> // in RESTORE.
> var SynthesizeRegionConfigOptionIncludeOffline SynthesizeRegionConfigOption = func(o *synthesizeRegionConfigOptions) {
> ```

nit: s/SynthesizeRegionConfigOptionInlcudeOffline/InlcudeOffline/g
___
*[pkg/sql/region_util.go, line 955 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63502#-MYBLa69Ax7jmmmIZnFU:-MYBLa69Ax7jmmmIZnFV:b3yzjwo) ([raw file](https://github.com/cockroachdb/cockroach/blob/874c2b5a9e2452d31c91533a34387ba2e0e530c6/pkg/sql/region_util.go#L955)):*
> ```Go
> // as part of the regions field, allowing validation to account for regions in the
> // process of being dropped.
> var SynthesizeRegionConfigOptionForValidation SynthesizeRegionConfigOption = func(o *synthesizeRegionConfigOptions) {
> ```

nit: RegionConfigOptionForValidation/ForValidation/g
___
*[pkg/sql/catalog/multiregion/region_config.go, line 85 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63502#-MYBKhDv9M6N2cC9ZeFV:-MYBKhDv9M6N2cC9ZeFW:b-k85yex) ([raw file](https://github.com/cockroachdb/cockroach/blob/04982f4c75b4f761076ddc8653bf9e18ec7dc7be/pkg/sql/catalog/multiregion/region_config.go#L85)):*
> ```Go
> // MakeRegionConfigOptionTransitioningRegions is an option to include transitioning
> // regions into MakeRegionConfig.
> func MakeRegionConfigOptionTransitioningRegions(
> ```

nit: `WithTransitioningRegions` :sweat_smile: 
___
*[pkg/sql/catalog/typedesc/type_desc.go, line 200 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63502#-MYBKxW570Tg3NklGU0x:-MYBKxW570Tg3NklGU0y:boein6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/04982f4c75b4f761076ddc8653bf9e18ec7dc7be/pkg/sql/catalog/typedesc/type_desc.go#L200)):*
> ```Go
> 
> // TransitioningRegionNames returns regions where are not `PUBLIC` and are in the
> // process of transforming to or from being public.
> ```

nit: transitioning to `PUBLIC` or being removed entirely might be clearer here.

**Review by otan — COMMENTED** [review]
> Can we add a test for the first commit which would have required the session variable to be set (us being too strict) but works now?

this is basically what your tests will do (DROP REGION and REGIONAL BY ROW change concurrently). Since it'll just rebase conflict with you, I'm saving it

> What's your hope for backporting this change? I'd suggest we hold off on backporting this until the .1 release, as it's all just validation and refactoring.

It may need to be backported along with arul's changes to make all the testing work.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63502#-:-MYC2sqP7kXEyi8sw7vh:b-1pp744)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @dt)

___
*[pkg/sql/region_util.go, line 1429 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63502#-MYAmrOM7qHvsQuwX1so:-MYC26fLBye1eTfhHcOY:bt4slik) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e543621a81be7953bee980a6493beec952c693d/pkg/sql/region_util.go#L1429)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

For my benefit, is this no longer needed because we've moved the zone config writing to finalize?
</blockquote></details>

this was wrong in the first place -- it should have been "ForZoneConfigValidation"
___
*[pkg/sql/region_util.go, line 948 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63502#-MYBLVly1bSimMtxY6GO:-MYC0sFKEuwUV69ZXhHu:b-pxm34m) ([raw file](https://github.com/cockroachdb/cockroach/blob/874c2b5a9e2452d31c91533a34387ba2e0e530c6/pkg/sql/region_util.go#L948)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: s/SynthesizeRegionConfigOptionInlcudeOffline/InlcudeOffline/g
</blockquote></details>

i disagree with this one, it's too vague for the `sql` package.
i still heavily think prefixing is a good thing because it's clear to organise and know where it's coming from, and reduces the chance of conflicting options in future.
___
*[pkg/sql/region_util.go, line 955 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63502#-MYBLa69Ax7jmmmIZnFU:-MYC117Q8UWjoHqy8Nmm:bj8bld6) ([raw file](https://github.com/cockroachdb/cockroach/blob/874c2b5a9e2452d31c91533a34387ba2e0e530c6/pkg/sql/region_util.go#L955)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: RegionConfigOptionForValidation/ForValidation/g
</blockquote></details>

same as above.

**Review by ajstorm — COMMENTED** [review]
> It may need to be backported along with arul's changes to make all the testing work.

Let's chat if we determine that to be the case (once @arulajmani's stuff is done)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63502#-:-MYC5X9fCgeuCKmWyZ-Z:b-9eiftp)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajstorm, @arulajmani, @dt, and @otan)

___
*[pkg/sql/region_util.go, line 1429 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63502#-MYAmrOM7qHvsQuwX1so:-MYC8b7G5RRBGogY0YJg:b-59ot5w) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e543621a81be7953bee980a6493beec952c693d/pkg/sql/region_util.go#L1429)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

this was wrong in the first place -- it should have been "ForZoneConfigValidation"
</blockquote></details>

nm, I didn't catch the passing in of `SynthesizeRegionConfigOptionForValidation` at the end.

**Review by arulajmani — APPROVED** [review]
> this is basically what your tests will do (DROP REGION and REGIONAL BY ROW change concurrently). Since it'll just rebase conflict with you, I'm saving it

Just came back to this PR after realizing this :) Let me know when you get this in so I can rebase.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63502#-:-MYCRzvh2wD2JARAflzW:b-pzv9e7)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajstorm, @arulajmani, @dt, and @otan)

___
*[pkg/sql/region_util.go, line 948 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63502#-MYBLVly1bSimMtxY6GO:-MYCSAm--Kd_On2qed8q:b-4kbcii) ([raw file](https://github.com/cockroachdb/cockroach/blob/874c2b5a9e2452d31c91533a34387ba2e0e530c6/pkg/sql/region_util.go#L948)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i disagree with this one, it's too vague for the `sql` package.
i still heavily think prefixing is a good thing because it's clear to organise and know where it's coming from, and reduces the chance of conflicting options in future.
</blockquote></details>

IMO the prefix hinders readability, but maybe its just me. Regardless, not worth holding this PR over :)

**Comment by otan** [comment]
bors r=arulajmani,ajstorm

**Pull request merged**
