### PR TITLE
[WIP] cluster: implement version migration RFC

### PR DESCRIPTION
**Pull request by spencerkimball**
Introduce `Version` and `ClusterVersion` protobuf messages.

Add default `ServerVersion` and `MinimumSupportedVersion` to the base
package.

Add read/write methods to the `storage.Stores` object for persisting
the gossiped `ClusterVersion` setting to prevent too-old or too-new
binaries from starting on the data in a configured store.

**TODO**:
- Decide whether to build a callback facility for settings package.
- Check gossiped `ClusterVersion` against setting either on new
  settings callback or every time that the system config changes.
- Provide a hook when setting the cluster version setting to verify
  that existing nodes can accommodate the new value.

### CODE REVIEW

**Comment by tschottdorf** [comment]
Looks good so far! For the env var, maybe you can poach something from https://github.com/cockroachdb/cockroach/compare/master...tschottdorf:migration?expand=1#diff-4ec93c4ea7116a6504b783da77089a7aR26.

---

Reviewed 20 of 20 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/storage/stores.go, line 348 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17155#-KpXioj_dgfV3DWEyBR1:-KpXioj_dgfV3DWEyBR2:bwiye34) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f701a06c8fb960e0700a5239389e9d05a0c1bfc/pkg/storage/stores.go#L348)):*
> ```Go
> // ReadClusterVersion reads and returns the ClusterVersion protobuf
> // written to any of the configured stores which has the highest
> // minimum version. The returned value is also replicated to all
> ```

Mention what happens if that isn't unique. You could have same min version, but different use versions.

---

*[pkg/storage/stores_test.go, line 348 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17155#-KpXk6p1_-euFnRIn4cn:-KpXk6p1_-euFnRIn4co:bcgjvre) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f701a06c8fb960e0700a5239389e9d05a0c1bfc/pkg/storage/stores_test.go#L348)):*
> ```Go
> 	ls3.AddStore(stores[0])
> 	verifyBI.Reset()
> 	if err := ls3.ReadBootstrapInfo(&verifyBI); err != nil {
> ```

Why this change?

---

*[pkg/storage/stores_test.go, line 486 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17155#-KpXkiRnGNlbrEf-8qYh:-KpXkiRoWCe2p8QIaN5R:bgte2b3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f701a06c8fb960e0700a5239389e9d05a0c1bfc/pkg/storage/stores_test.go#L486)):*
> ```Go
> 	var err error
> 	if _, err = ls2.ReadClusterVersion(ctx); !testutils.IsError(err, "which is < minimum supported version") {
> 		t.Errorf("expected error reading version older than minimum supported")
> ```

Print the error, too.

---

*[pkg/storage/stores_test.go, line 512 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17155#-KpXklXvWA69-JByKoCb:-KpXklXvWA69-JByKoCc:bs4q9op) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f701a06c8fb960e0700a5239389e9d05a0c1bfc/pkg/storage/stores_test.go#L512)):*
> ```Go
> 	var err error
> 	if _, err = ls2.ReadClusterVersion(ctx); !testutils.IsError(err, "which is > supported version") {
> 		t.Errorf("expected error reading required version later than supported")
> ```

Ditto.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17155#-:-KpXl6xIsfeOAzux_23X:b-ltgprj)*

**Comment by spencerkimball** [comment]
As mentioned on Slack, I was hoping you could take this PR over. Looks like this code is going to be useful for the `SET CLUSTER SETTING` command. Are you planning to also make this settable via the CLI?

---

Review status: 19 of 20 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/storage/stores.go, line 348 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17155#-KpXioj_dgfV3DWEyBR1:-Kp_ffDDedvRJAu3cYte:b-cwftdq) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f701a06c8fb960e0700a5239389e9d05a0c1bfc/pkg/storage/stores.go#L348)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Mention what happens if that isn't unique. You could have same min version, but different use versions.
</blockquote></details>

Before updating this documentation, we should figure out what the most coherent policy is when the value of `UseVesion` is different between stores.

---

*[pkg/storage/stores_test.go, line 348 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17155#-KpXk6p1_-euFnRIn4cn:-Kp_f4ILCs9Ew0Ky5KtP:bcx2txm) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f701a06c8fb960e0700a5239389e9d05a0c1bfc/pkg/storage/stores_test.go#L348)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Why this change?
</blockquote></details>

There was a bug in the test; it wasn't testing what it was supposed to be testing...from a fresh `Stores` object.

---

*[pkg/storage/stores_test.go, line 486 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17155#-KpXkiRnGNlbrEf-8qYh:-Kp_fJWaQ13MiwP8sx_l:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f701a06c8fb960e0700a5239389e9d05a0c1bfc/pkg/storage/stores_test.go#L486)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Print the error, too.
</blockquote></details>

Done.

---

*[pkg/storage/stores_test.go, line 512 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17155#-KpXklXvWA69-JByKoCb:-Kp_fM8lFP10nKTpP9Dk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f701a06c8fb960e0700a5239389e9d05a0c1bfc/pkg/storage/stores_test.go#L512)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17155#-:-Kp_fNuqTB9yiA3a3VJV:b-pfnvtm)*

**Comment by RaduBerinde** [comment]
Just a note that cluster settings can already have change callbacks (`OnChange`).

**Comment by bdarnell** [comment]
Reviewed 19 of 20 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/storage/stores.go, line 348 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17155#-KpXioj_dgfV3DWEyBR1:-KppbWZLSyzx1uzrVuJW:b-uxrg2w) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f701a06c8fb960e0700a5239389e9d05a0c1bfc/pkg/storage/stores.go#L348)):*
<details><summary><i>Previously, spencerkimball (Spencer Kimball) wrote…</i></summary><blockquote>

Before updating this documentation, we should figure out what the most coherent policy is when the value of `UseVesion` is different between stores.
</blockquote></details>

I think there's going to be some gossiped value stored in the system config span that is the authoritative version of this. Whenever we get a gossip update we should update all our stores to match. If the stores disagree on `use_version` I don't think it matters much which one we use while waiting for our first gossip version, but I think I'd go with the smallest `use_version` value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17155)*

**Comment by tschottdorf** [comment]
Superseded by upcoming PR.

**Pull request closed without merging**
