### PR TITLE
opt: fix merge skew

### PR DESCRIPTION
**Pull request by RaduBerinde**
Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
Thanks for the quick fix!

**Comment by rytaft** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23408#-:-L6rqVUIAoci6OECR8Ye:bnfp4nl)*

**Comment by knz** [comment]
green

**Comment by RaduBerinde** [comment]
Sigh. I accidentally merged a different PR 23401 instead. That also fixes this problem though. I'll leave that in and open a new PR for any review comments.

**Pull request merged**
