### PR TITLE
storage: limit goroutine creation in intent resolution

### LINKED ISSUE #4925: stability: disconnect + crash under load
There is not clear and obvious culprit here, so I'll attempt to summarize as best I can.

build sha: e6793e1c8155dab88317a0948130d2eb64ed76c1

4-node cluster with the photos example running against it.
Things are fine for a few hours, until the following happens:

Crash timelines and full logs. All crashes are OOM

node4: 17:40:41
[node4.crash.txt](https://github.com/cockroachdb/cockroach/files/160594/node4.crash.txt)

node3: 18:04:32
[node3.crash.txt](https://github.com/cockroachdb/cockroach/files/160595/node3.crash.txt)

node2: 18:09:45
[node2.crash.txt](https://github.com/cockroachdb/cockroach/files/160596/node2.crash.txt)

node1: 21:15:49
[node1.crash.txt](https://github.com/cockroachdb/cockroach/files/160597/node1.crash.txt)

Now, looking for originating events is where it gets a bit tedious.
One of the first signs of badness if around 17:26 when we get:
```
17:26:54.224163 gossip/gossip.go:923  partition in gossip network; attempting new connection
```

This happens on nodes 1, 2, and 4 at that precise time, and 20 seconds lated on node 3.
Lease holders were the following, with 3 being the last one:
```
Node1:
I160306 17:24:47.189891 storage/replica_command.go:1255  range 1: new leader lease replica {1 1 10} 2016-03-06 17:24:43 +0000 UTC +1.820s
I160306 17:24:55.236673 storage/replica_command.go:1255  range 1: new leader lease replica {1 1 10} 2016-03-06 17:24:54 +0000 UTC +1.152s

Node2:
I160306 17:10:28.212065 storage/replica_command.go:1255  range 1: new leader lease replica {2 2 9} 2016-03-06 17:10:24 +0000 UTC +4.435s
I160306 17:10:38.194705 storage/replica_command.go:1255  range 1: new leader lease replica {2 2 9} 2016-03-06 17:10:34 +0000 UTC +4.438s

Node3:
I160306 17:24:47.324180 storage/replica_command.go:1255  range 1: new leader lease replica {3 3 11} 2016-03-06 17:24:46 +0000 UTC +1.391s
I160306 17:25:12.291490 storage/replica_command.go:1255  range 1: new leader lease replica {3 3 11} 2016-03-06 17:25:08 +0000 UTC +1.474s

Node4:
I160306 17:24:20.530929 storage/replica_command.go:1255  range 1: new leader lease replica {4 4 4} 2016-03-06 17:24:17 +0000 UTC +1.732s
I160306 17:24:24.417120 storage/replica_command.go:1255  range 1: new leader lease replica {4 4 4} 2016-03-06 17:24:23 +0000 UTC +1.003s
```

### PR DESCRIPTION
**Pull request by bdarnell**
The method formerly known as `Replica.handleSkippedIntents` will no longer try to push transactions for which a `PushTxn` call is already in flight. Additionally, there is now a hard limit on the number of async tasks that can be created in this area. 

Move methods related to intent resolution from `Store` and `Replica` to a new `intentResolver` type. Various cleanups, renamings, and refactorings to support these changes.

Fixes #4925

---

This change is [Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5219)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1, 5 of 5 files at r2, 3 of 3 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[storage/intent_resolver.go, line 43 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5219#-KCnQ0sRoM64g278PZ-e:-KCnQ0sRoM64g278PZ-f:1995616749) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1655b0b8fbf0ca32488ecd94e97668dbd011da4/storage/intent_resolver.go#L43)):*
these should be dereferenced on the way in - they are pointers in Transaction so that they can be nil before the transaction is initialized.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5219#-:-KCnQj-tQOLU5jgZEhwM:1417088721)*

**Comment by tschottdorf** [comment]
Can you add (relatively) prominent logging in the case that the rate limiting or the transaction cache are triggered, at least for now? Is it certified that #4925 is still the intent issue? I haven't had a chance to investigate it after I disarmed the timestamp cache (so in the case I had seen, there were a million synchronous pushes triggered by the GC queue).

:lgtm: 

---

Reviewed 3 of 3 files at r1, 5 of 5 files at r2, 3 of 3 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[storage/intent_resolver.go, line 59 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5219#-KCoux0jw6BOV9CXOYjm:-KCoux0jw6BOV9CXOYjn:-798546106) ([raw file](https://github.com/cockroachdb/cockroach/blob/e11948892bf6c27d93140c39c93ecdefdacc14a0/storage/intent_resolver.go#L59)):*
nit: there's something weird about the look of the `. (if ....)`.

---

*[storage/intent_resolver.go, line 162 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5219#-KCov71e_4CsqoWu4cX2:-KCov71e_4CsqoWu4cX3:355135680) ([raw file](https://github.com/cockroachdb/cockroach/blob/e11948892bf6c27d93140c39c93ecdefdacc14a0/storage/intent_resolver.go#L162)):*
s/own intents/own external intents/

---

*[storage/intent_resolver.go, line 192 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5219#-KCovacfzhvCKAhblvXy:-KCovacfzhvCKAhblvXz:-1159602200) ([raw file](https://github.com/cockroachdb/cockroach/blob/e11948892bf6c27d93140c39c93ecdefdacc14a0/storage/intent_resolver.go#L192)):*
why did this move below the call to `resolveIntents`?
I think `wiErr == nil` can be removed (as we decided to drop this case under the rug).

---

*[storage/intent_resolver.go, line 156 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5219#-KCoyb3ADli4i_q8LnRW:-KCoyb3ADli4i_q8LnRX:975051232) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1655b0b8fbf0ca32488ecd94e97668dbd011da4/storage/intent_resolver.go#L156)):*
If the other goroutine is pushing for timestamp but we need it aborted, that doesn't help us.

Some more comments here on the expected outcomes would be good (i.e. we assume the other guy's push goes through in time for us retrying the read/write).

---

*[storage/intent_resolver.go, line 237 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5219#-KCoz0A6vhrntfQiw1cB:-KCoz0A6vhrntfQiw1cC:1023920057) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1655b0b8fbf0ca32488ecd94e97668dbd011da4/storage/intent_resolver.go#L237)):*
why `true`? I thought it would make most sense to have `false` here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5219#-:-KCozxtMgjh6Cx9_vMlk:-192401872)*

**Comment by nvanbenschoten** [comment]
LGTM

---

Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[storage/intent_resolver.go, line 47 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5219#-KCpj_F-OBdR3xDxVzSF:-KCpj_F09RuYDnm8CpZp:1770227727) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e44cdc0a218ffddf751d540e528cc54136ef990/storage/intent_resolver.go#L47)):*
s/goroutines/goroutines./

---

*[storage/intent_resolver.go, line 155 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5219#-KCpkMHAx4A4uqIWHNEW:-KCpkMHAx4A4uqIWHNEX:1908747956) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e44cdc0a218ffddf751d540e528cc54136ef990/storage/intent_resolver.go#L155)):*
If there's a lot of contention for this lock, we may want to consider preallocating outside of the lock. We also can populate the `resolveIntents` slice outside of the lock if we're willing to do a second pass. Again, only needed if this becomes a bottleneck.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5219#-:-KCpoBt1MUReEr4Ad8RB:676834233)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[storage/intent_resolver.go, line 75 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5219#-KCqHXflh20Qsgo3sNi3:-KCqHXfmDMULUhAsinPE:1582892470) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e44cdc0a218ffddf751d540e528cc54136ef990/storage/intent_resolver.go#L75)):*
Holy mega-line-length!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5219)*

**Comment by bdarnell** [comment]
@tschottdorf The immediate problem in #4925 was goroutines created by `handleSkippedIntents`. There was a root cause that I don't think we've identified, but might have been the timestamp cache. I don't think there's enough info in #4925 to identify any culprit besides this one.

Added logging at V(1) for a push that is skipped because it is in flight (it would be pretty noisy otherwise - it shows up 250 times in a run of `make test PKG=./storage`) and stdlib log.Printf for tasks blocked by the semaphore (we can't use leveled logging from the stop package).

All other comments addressed.

---

Review status: 3 of 7 files reviewed at latest revision, 9 unresolved discussions.

---

*[storage/intent_resolver.go, line 192 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5219#-KCovacfzhvCKAhblvXy:-KCqh9QwYhO4Qi4cKOZU:-1366177098) ([raw file](https://github.com/cockroachdb/cockroach/blob/e11948892bf6c27d93140c39c93ecdefdacc14a0/storage/intent_resolver.go#L192)):*
Previously, `resolveWriteIntentError` could return a `WriteIntentError` *and* intents to resolve, so I changed it so that any intents that get returned should be resolved whether the push succeeded or not. I'm not sure whether it matters any more, though: I've removed the `WriteIntentError` quirks and I don't think it's possible for intents to make it to this point with the status of their transaction known in advance (and even if they did, we weren't returning them along with any errors but the `WriteIntentError`; see TODOs above)

---

*[storage/intent_resolver.go, line 43 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5219#-KCnQ0sRoM64g278PZ-e:-KCqjNtVAvOfU7DXqCTR:-2118021810) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1655b0b8fbf0ca32488ecd94e97668dbd011da4/storage/intent_resolver.go#L43)):*
Good catch; I guess this wasn't actually doing anything before since the pointers would never be the same. I can't figure out a good way to test this part, though (other than manually testing with logging, which I've now done). It's hard to test for the absence of something that, if it happened, would be asynchronous. 

---

*[storage/intent_resolver.go, line 156 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5219#-KCoyb3ADli4i_q8LnRW:-KCqeXzu5qEbm4BvhuwZ:1645509432) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1655b0b8fbf0ca32488ecd94e97668dbd011da4/storage/intent_resolver.go#L156)):*
Yes, that's why the only time we pass `skipInFlight` is for `PUSH_TOUCH` (that's the one case where we didn't have an effective means of backpressure before and goroutines could really get out of control). Pushes that are actually trying to modify the transaction are always allowed through. We could do a better job there of determining whether the push is fully covered by some in-flight operation, but then we'd also need to determine whether the intents are the same or whether it's a different intent from the same transaction, and if the latter to synchronize the resolution of that intent with the return from the push. I had originally envisioned reworking this file into an explicit hierarchy of dependencies between transactions to push, intents to resolve, and transactions to GC, but left that for another day. 

---

*[storage/intent_resolver.go, line 237 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5219#-KCoz0A6vhrntfQiw1cB:-KCqgB7IN3ZRRy6aoFlT:2029732340) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1655b0b8fbf0ca32488ecd94e97668dbd011da4/storage/intent_resolver.go#L237)):*
This is the only place where `skipInFlight` is true, because `PUSH_TOUCH` are the only types of pushes that are safe to drop. This is for intents that are skipped by an inconsistent read; there are no retries to worry about.

---

*[storage/intent_resolver.go, line 75 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5219#-KCqHXflh20Qsgo3sNi3:-KCqe2qXlmEEz-nOi06f:671270972) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e44cdc0a218ffddf751d540e528cc54136ef990/storage/intent_resolver.go#L75)):*
Did a pass over the entire diff to wrap at 100.

---

*[storage/intent_resolver.go, line 155 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5219#-KCpkMHAx4A4uqIWHNEW:-KCqeAJGniB2f36ad_QJ:-198131724) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e44cdc0a218ffddf751d540e528cc54136ef990/storage/intent_resolver.go#L155)):*
I doubt it'll be a problem. Allocation by itself is cheap; the main cost of an allocation is that each allocation implies eventual work for the GC.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5219#-:-KCqbsz5EhRgytFL_vLn:572307380)*

**Comment by tamird** [comment]
Reviewed 4 of 4 files at r9.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5219)*

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r9.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[storage/intent_resolver.go, line 156 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5219#-KCoyb3ADli4i_q8LnRW:-KCr0or7LAp_sz1Hob94:-858487095) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1655b0b8fbf0ca32488ecd94e97668dbd011da4/storage/intent_resolver.go#L156)):*
Oh, I misread the code. `skipInFlight` suggested to me that the in-flight map lookup is skipped, but really it's simply not pushing transactions for which a previous push is in flight. If that's likely to happen to someone else, maybe rename, but with the comment on the method it ought to be fine.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5219#-:-KCr24uUwv_xOD0Q-XNZ:1417088721)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[storage/intent_resolver.go, line 156 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5219#-KCoyb3ADli4i_q8LnRW:-KCr6SlAMw30j9OEGtwO:-651976722) ([raw file](https://github.com/cockroachdb/cockroach/blob/d1655b0b8fbf0ca32488ecd94e97668dbd011da4/storage/intent_resolver.go#L156)):*
Renamed to `skipIfInFlight`. I almost spelled it that way originally.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5219)*

**Comment by tschottdorf** [comment]
Reviewed 1 of 1 files at r10.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5219)*

**Pull request merged**
