### PR TITLE
storage: backpressure writes for large ranges until they split

### LINKED ISSUE #21357: storage: backpressure writes when ranges get too large
We've seen in privately tracked issues that under certain workloads the `splitQueue` is unable to keep up with the stream of incoming writes and ranges are able to grow without bound. In the referenced issue, 400 concurrent writers performing 80KB writes on a single range was enough to overwhelm the system to the point where ranges grew for past the 64MB split size, some reaching sizes of more than 3GB. We have issues open to better handle ranges of this size so that we don't lose availability in such cases (see https://github.com/cockroachdb/cockroach/issues/16954), but we should be more proactive about preventing these range sizes in the first place.

We should introduce a form of backpressure into the replica write path such that writes will synchronously block on pending splits once a range gets too large. This backpressure needs to come before the writes reach the `CommandQueue` to avoid creating contention or possible deadlocks, and we'll need to be careful to avoid throttling the split itself or any other requests that are needed to maintain replica health.

### PR DESCRIPTION
**Pull request by nvb**
Fixes https://github.com/cockroachdb/cockroach/issues/21357.

Testing has demonstrated that hotspot workloads which write large amounts
of data to a small range of keys can overload the `splitQueue` and create
excessively large ranges. Previous efforts to parallelize replica splits
have helped improve the queue's ability to keep up with these workloads,
but speeding up splits alone will never be able to fully prevent unbounded
range growth. Large ranges (those in the GB range) are problematic for
multiple reasons including that they slow down snapshots, consistency checks,
and other processes that scan over entire ranges and haven't been built with
these size ranges in mind. In the past we've attempted to prevent these
processes from running when ranges get too large, but this has created
other issues like #20589.

This change introduces a proactive backpressure mechanism to delay writes
once a range gets too large while we wait for its split to succeed. This
accomplishes the task of preventing ranges from getting to large because
it stops the range from growing and prevents new writes from getting in
the way of the split attempt. This has been shown to create an effective
soft limit on the maximum size of the range. By default, this limit is set
to twice the `range_max_bytes` setting, but this change also introduces an
environment variable for configuring the limit.

### Analysis

I did some testing similar to what was done [previously](https://github.com/cockroachdb/cockroach/pull/21562#issuecomment-359090789). Here, I spun up a four node
cluster and dropped the range size down to 4MB. I then ran 4 instances of the following
`kv --min-block-bytes=100000 --max-block-bytes=120000 --splits=0 --concurrency=20`
against the cluster with and without backpressure enabled. For each test, I
monitored the number of splits that were pending and that succeeded, the largest
range size in the cluster, and the number of writes that were backpressured. The
results are below:

#### Without backpressure

without-backpressure

#### With backpressure

with-backpressure

As the tests show, without backpressure the split queue was unable to keep up
with the hotspot workload and the maximum range size blew up to more than
750MB, 180 time the `range_max_bytes`. With backpressure, things were much
better. The max range size consistently stayed below 10MB and gradually dropped
below twice the `range_max_bytes`, the threshold at which we began backpressuring
writes. The third panel shows that backpressure wasn't even needed for very
long, as the ranges count quickly grew and the load spread out to the point where
the `splitQueue` could keep up on its own. This is exactly what we were hoping
to see and I attribute most of the difference we saw between this test and [this
one](https://github.com/cockroachdb/cockroach/pull/21562#issuecomment-359090789) to the fix to replica prioritization in the queues made by https://github.com/cockroachdb/cockroach/pull/21673.

### CODE REVIEW

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/storage/metrics.go, line 459 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21777#-L3jadRGrhax3Tu2Kox4:-L3jadRGrhax3Tu2Kox5:b-w9fu0w) ([raw file](https://github.com/cockroachdb/cockroach/blob/285d41f300344a20ffb0bc7bc5c75e801bdcb621/pkg/storage/metrics.go#L459)):*
> ```Go
> 	// Backpressure metrics.
> 	metaBackpressuredRequests = metric.Metadata{
> 		Name: "requests.backpressure",
> ```

Let's be more specific here (and maybe in the rest of the variable names): `requests.backpressure.split`. 

---

*[pkg/storage/metrics.go, line 460 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21777#-L3jaIfKKSDON5D6gjfE:-L3jaIfLQU8Ge2oo5EAx:bhqg7rp) ([raw file](https://github.com/cockroachdb/cockroach/blob/285d41f300344a20ffb0bc7bc5c75e801bdcb621/pkg/storage/metrics.go#L460)):*
> ```Go
> 	metaBackpressuredRequests = metric.Metadata{
> 		Name: "requests.backpressure",
> 		Help: "Number of backpressured writes waiting on a Range split"}
> ```

This description sounds like it refers to a gauge, not a counter. A gauge is probably what we want here, so we can see the backlog growing and then clearing. 

---

*[pkg/storage/queue.go, line 760 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21777#-L3jbaDoDugdX7VG1-Hp:-L3jbaDoDugdX7VG1-Hq:bpun35d) ([raw file](https://github.com/cockroachdb/cockroach/blob/285d41f300344a20ffb0bc7bc5c75e801bdcb621/pkg/storage/queue.go#L760)):*
> ```Go
> 
> 	// Call any registered callbacks.
> 	for _, cb := range item.callbacks {
> ```

Don't we need to clear the callbacks after this?

---

*[pkg/storage/replica_backpressure.go, line 34 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21777#-L3jcF5X0NXD9syIG3uO:-L3jcF5X0NXD9syIG3uP:b-59rj96) ([raw file](https://github.com/cockroachdb/cockroach/blob/285d41f300344a20ffb0bc7bc5c75e801bdcb621/pkg/storage/replica_backpressure.go#L34)):*
> ```Go
> // to 0 to disable backpressure altogether.
> var backpressureRangeSizeMultiplier = func() float64 {
> 	mult := envutil.EnvOrDefaultFloat64("COCKROACH_BACKPRESSURE_RANGE_SIZE_MULTIPLIER", 2)
> ```

I'd rather use a cluster setting than an env var for this. 

---

*[pkg/storage/replica_backpressure.go, line 62 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21777#-L3jcR87UEQzGXSpp_c3:-L3jcR87UEQzGXSpp_c4:b-vqq1rs) ([raw file](https://github.com/cockroachdb/cockroach/blob/285d41f300344a20ffb0bc7bc5c75e801bdcb621/pkg/storage/replica_backpressure.go#L62)):*
> ```Go
> 	// Don't backpressure splits themselves.
> 	//
> 	// TODO DURING REVIEW should we look at the txn name or should we
> ```

I'm OK with looking at the name. I'd rather do this based on the transaction than the keys (we could maybe add an explicit no-backpressure flag if the name feels too hacky). 

---

*[pkg/storage/replica_backpressure.go, line 82 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21777#-L3jcpnWPb5C-alKXxh3:-L3jcpnWPb5C-alKXxh4:b5sl5ch) ([raw file](https://github.com/cockroachdb/cockroach/blob/285d41f300344a20ffb0bc7bc5c75e801bdcb621/pkg/storage/replica_backpressure.go#L82)):*
> ```Go
> // subject to backpressure. This is based on the size of the range in relation
> // to the split size. If the range is more than backpressureRangeSizeMultiplier
> // times larger than
> ```

Finish this sentence.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21777#-:-L3jde6cQOWg0tmazl8K:bnfp4nl)*

**Comment by spencerkimball** [comment]
Super cool

**Comment by nvanbenschoten** [comment]
TFTR!

---

Review status: 0 of 11 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/storage/metrics.go, line 459 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21777#-L3jadRGrhax3Tu2Kox4:-L43Nxj7573_2ZLhxBen:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/285d41f300344a20ffb0bc7bc5c75e801bdcb621/pkg/storage/metrics.go#L459)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Let's be more specific here (and maybe in the rest of the variable names): `requests.backpressure.split`. 
</blockquote></details>

Done.

---

*[pkg/storage/metrics.go, line 460 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21777#-L3jaIfKKSDON5D6gjfE:-L43OFF9JXUWSeodqvUm:b-a2xn93) ([raw file](https://github.com/cockroachdb/cockroach/blob/285d41f300344a20ffb0bc7bc5c75e801bdcb621/pkg/storage/metrics.go#L460)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This description sounds like it refers to a gauge, not a counter. A gauge is probably what we want here, so we can see the backlog growing and then clearing. 
</blockquote></details>

Good point! Done.

Why does `Counter` have a `Dec` method on it in the first place? Seems like that breaks the contract from https://prometheus.io/docs/concepts/metric_types/#counter. I'll go through and see if anything can be done about that.

---

*[pkg/storage/queue.go, line 760 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21777#-L3jbaDoDugdX7VG1-Hp:-L43QH4gooeM9DQ9xjcy:b-c7n3j4) ([raw file](https://github.com/cockroachdb/cockroach/blob/285d41f300344a20ffb0bc7bc5c75e801bdcb621/pkg/storage/queue.go#L760)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Don't we need to clear the callbacks after this?
</blockquote></details>

No, the item is thrown away after this.

---

*[pkg/storage/replica_backpressure.go, line 34 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21777#-L3jcF5X0NXD9syIG3uO:-L43Yeat3JbrWK2HfMNn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/285d41f300344a20ffb0bc7bc5c75e801bdcb621/pkg/storage/replica_backpressure.go#L34)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I'd rather use a cluster setting than an env var for this. 
</blockquote></details>

Done.

---

*[pkg/storage/replica_backpressure.go, line 62 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21777#-L3jcR87UEQzGXSpp_c3:-L43QUbkPIsA4ewVWwWi:b-81nlyc) ([raw file](https://github.com/cockroachdb/cockroach/blob/285d41f300344a20ffb0bc7bc5c75e801bdcb621/pkg/storage/replica_backpressure.go#L62)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I'm OK with looking at the name. I'd rather do this based on the transaction than the keys (we could maybe add an explicit no-backpressure flag if the name feels too hacky). 
</blockquote></details>

SGTM.

---

*[pkg/storage/replica_backpressure.go, line 82 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21777#-L3jcpnWPb5C-alKXxh3:-L43QnYaG5rFqfE1nsAA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/285d41f300344a20ffb0bc7bc5c75e801bdcb621/pkg/storage/replica_backpressure.go#L82)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Finish this sentence.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21777#-:-L43uwEgqm98iCQ89QG4:b-814g8k)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 11 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/storage/metrics.go, line 460 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21777#-L3jaIfKKSDON5D6gjfE:-L43v0QvQuh5saSYLeLd:b-thoouw) ([raw file](https://github.com/cockroachdb/cockroach/blob/285d41f300344a20ffb0bc7bc5c75e801bdcb621/pkg/storage/metrics.go#L460)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Good point! Done.

Why does `Counter` have a `Dec` method on it in the first place? Seems like that breaks the contract from https://prometheus.io/docs/concepts/metric_types/#counter. I'll go through and see if anything can be done about that.
</blockquote></details>

Follow up: https://github.com/cockroachdb/cockroach/pull/21903

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21777)*

**Comment by a-robinson** [comment]
> Why does Counter have a Dec method on it in the first place? Seems like that breaks the contract from https://prometheus.io/docs/concepts/metric_types/#counter. I'll go through and see if anything can be done about that.

Because we aren't using the prometheus client library. The one we're using predates prometheus by quite a bit and has [different opinions on decrement methods](https://github.com/rcrowley/go-metrics/issues/193).

**Pull request merged**
