### PR TITLE
roachtest: add backward compat to replicate/wide

### PR DESCRIPTION
**Pull request by solongordon**
In 6c249306, I updated the way replication zones are named, which
affected the replicate/wide roachtest. However I neglected to add
backward compatibility for testing against previous releases. This
commit restores the old logic for that scenario.

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
Lgtm but please add a comment on both sections to indicate at which future version it can be removed.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by solongordon** [comment]
I think that is unknown because we haven't decided how long we will be running roachtest against earlier releases. But I'll make it clearer that the code can be removed once we're not testing against 19.1 and earlier.

**Comment by knz** [comment]
Sounds good!

**Comment by rohany** [comment]
lgtm

**Pull request merged**
