### PR TITLE
settings: support duration settings

### PR DESCRIPTION
**Pull request by knz**
This is needed to replace COCKROACH_TRACE_SQL. ( working on #13851 )

### CODE REVIEW

**Comment by knz** [comment]
rebased; PTAL

**Comment by dt** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/settings/cache_test.go, line 126 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15173#-Ki6pqXrnFzY7hMrHQxz:-Ki6pqXrnFzY7hMrHQy-:bck1exq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b0be432ef91a9cbe8dc17e873eb53658523ca18/pkg/settings/cache_test.go#L126)):*
> ```Go
> 			t.Fatalf("expected %v, got %v", expected, actual)
> 		}
> 		if expected, actual := time.Second, dAccessor(); expected != actual {
> ```

can you add write to this test as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15173#-:-Ki6pxF1iArxdGFoqVN7:bnfp4nl)*

**Comment by knz** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/settings/cache_test.go, line 126 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15173#-Ki6pqXrnFzY7hMrHQxz:-Ki6zsAk9I97C90i3-yA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b0be432ef91a9cbe8dc17e873eb53658523ca18/pkg/settings/cache_test.go#L126)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

can you add write to this test as well?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15173)*

**Comment by knz** [comment]
TFYR

**Pull request merged**
