### PR TITLE
Use `go test -json` instead of `go2xunit`

### LINKED ISSUE #26168: cmd/github-post: replace usage of go2xunit
`github-post` uses `go2xunit` to parse the output of `make stress`. Unfortunately, this parsing has bugs. For example, the title chosen for https://github.com/cockroachdb/cockroach/issues/26122 has a test name as the package name. Rather than trying to parse the textual output of `go test`, we should switch to using `go test -json`.

### PR DESCRIPTION
**Pull request by tamird**
Fixes #26168.

Release note: None

### CODE REVIEW

**Review by petermattis — CHANGES_REQUESTED** [review]
Thanks for tackling this irritant. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27287#-:-LH-Okon5HimSURPeIwD:b-kehfz9)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/github-post/main.go, line 60 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27287#-LH-Nm5O3FESOmNVr5OQ:-LH-Nm5O3FESOmNVr5OR:b-4dg2v8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5153935cdbc1c991945b593df6ff3387543cc6e/pkg/cmd/github-post/main.go#L60)):*
> ```Go
> 	input = io.TeeReader(input, &inputBuf)
> 
> 	// The `go test -json` output stream is a newline-separate sequence of
> ```

`s/separate/separated/g`
___
*[pkg/cmd/github-post/main.go, line 75 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27287#-LH-NygD5aBS6jKTEiQE:-LH-NygD5aBS6jKTEiQF:bf8rjdi) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5153935cdbc1c991945b593df6ff3387543cc6e/pkg/cmd/github-post/main.go#L75)):*
> ```Go
> 			break
> 		}
> 	}
> ```

This is neat, but also crazy. Is this always necessary to read the output of `go test -json`? That seems surprising.
___
*[pkg/cmd/github-post/main_test.go, line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27287#-LH-OSLOBIer-4uiQcYH:-LH-OSLOBIer-4uiQcYI:b-fdxo72) ([raw file](https://github.com/cockroachdb/cockroach/blob/3145b8995f2fd8f51db01c8d54af1e219738aed2/pkg/cmd/github-post/main_test.go#L55)):*
> ```Go
> 	}{
> 		{
> 			fileName:    "stress-failure",
> ```

Is there a reason that producing new test data is difficult? I would have added a deterministic failure to one of the tests.

**Review by tamird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27287)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/github-post/main.go, line 60 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27287#-LH-Nm5O3FESOmNVr5OQ:-LH-iJO_1QvOOUL1P45V:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5153935cdbc1c991945b593df6ff3387543cc6e/pkg/cmd/github-post/main.go#L60)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/separate/separated/g`
</blockquote></details>

Done.
___
*[pkg/cmd/github-post/main.go, line 75 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27287#-LH-NygD5aBS6jKTEiQE:-LH-iJqd2sSH537APdXJ:b-302ztd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5153935cdbc1c991945b593df6ff3387543cc6e/pkg/cmd/github-post/main.go#L75)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This is neat, but also crazy. Is this always necessary to read the output of `go test -json`? That seems surprising.
</blockquote></details>

It's not necessary to read the output of `go test -json`, but our `make` machinery that wraps `go test` makes it necessary. I've updated the comments, and the tests now exercise this.
___
*[pkg/cmd/github-post/main_test.go, line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27287#-LH-OSLOBIer-4uiQcYH:-LH-iRVjEPicYxOcNPdE:bswecad) ([raw file](https://github.com/cockroachdb/cockroach/blob/3145b8995f2fd8f51db01c8d54af1e219738aed2/pkg/cmd/github-post/main_test.go#L55)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is there a reason that producing new test data is difficult? I would have added a deterministic failure to one of the tests.
</blockquote></details>

Oh, duh. Done.

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27287#-:-LH-t67A0jBhkrnpNR_W:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/github-post/main.go, line 75 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27287#-LH-NygD5aBS6jKTEiQE:-LH-t4BP1eR8YLBzf16B:b-6276mv) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5153935cdbc1c991945b593df6ff3387543cc6e/pkg/cmd/github-post/main.go#L75)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

It's not necessary to read the output of `go test -json`, but our `make` machinery that wraps `go test` makes it necessary. I've updated the comments, and the tests now exercise this.
</blockquote></details>

Ah, that makes more sense.

**Comment by benesch** [comment]
bors r=petermattis

**Comment by mjibson** [comment]
This maybe broke the build? I can't see the vendor commit in the vendored repo. Did it not get pushed to a named branch?

**Comment by tschottdorf** [comment]
I was able to pull this change in, but just to make sure, I just did

```
$ git push -u origin remove-go2xunit
Counting objects: 3, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 295 bytes | 295.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To github.com:cockroachdb/vendored
 * [new branch]          remove-go2xunit -> remove-go2xunit
Branch 'remove-go2xunit' set up to track remote branch 'remove-go2xunit' from 'origin' by rebasing.
```

**Comment by mjibson** [comment]
Hopefully was just https://twitter.com/githubstatus/status/1016591060024418304 then?

**Comment by tamird** [comment]
I opened a PR in vendored; I don't have commit access there.

**Pull request merged**
