### PR TITLE
build: Update grpc to 1.9.1

### PR DESCRIPTION
**Pull request by bdarnell**
Updates #13722

Release note (general): CockroachDB now uses gRPC version 1.9.1

### CODE REVIEW

**Review by a-robinson — APPROVED** [review]
LGTM. Also updates #17370.

**Comment by mberhault** [comment]
LGTM. This should be fun.

**Comment by bdarnell** [comment]
GRPC deprecated some things, and our linter wasn't happy with that (it looks for "Deprecated" in doc comments. Wow!). I've shaved that yak now. There were non-trivial changes in the rpc package, especially rpc/snappy.go (which was rewritten and now follows the example of grpc's own gzip compressor)

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21398#-:-L2jzfpv2YIZz8oGb918:bnfp4nl)*

**Pull request merged**
