### PR TITLE
storage: eagerly replicate split ranges

### LINKED ISSUE #7022: storage: replication delay in new 3 node cluster
The delay in replicating the initial ranges feels too long in a local 3 node cluster. Reproduction steps:

1. Run `roachdemo`
2. Create 3 nodes
3. Visit the admin UI nodes page
4. Witness how long it takes for the nodes to all report 5 replicas

I would expect the replication to occur within seconds, but it seems to take closer to 30 seconds. I could have sworn this worked smoother in the past.

### PR DESCRIPTION
**Pull request by petermattis**
Eagerly add newly split ranges to the replicate queue. The replicate
queue only processes replicas that do not require splitting. This
reduces the time to replicate the initial ranges from ~30s to ~2s.

Fixes #7022.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7355)

### CODE REVIEW

**Comment by petermattis** [comment]
@tschottdorf, @bdarnell Any pointers on how to add a test for this? I suppose I could disable the replica scanner and still verify that the initial ranges are being replicated. Do we have any similar test?

cc @BramGruneir

**Comment by petermattis** [comment]
I've added a test which verifies that all of the initial ranges are in replicate queue purgatory after the initial splits occur and verified that this is not true if I disable the eager-replicate code path added in this PR.

**Comment by tamird** [comment]
LGTM

**Comment by BramGruneir** [comment]
This will work when up replicating a cluster at the start, but I don't think it will help in any way once a cluster is fully replicated and these calls won't do anything helpful but make splits take a little bit longer.

I think there's a better solution out there, perhaps a specialized initial range list in the replicate queue that are more aggressively looped.  Or just enqueue the initial range more than once during bootstrapping (or some other part of the startup sequence).  Or perhaps enqueue all ranges when a new node is gossiped (which will be helpful for rebalances).

**Comment by BramGruneir** [comment]
Or, maybe only enqueue after the split if the ranges are not fully replicated yet.  That would avoid spamming the replicate queue when it is not needed (and I think we have that info already).

**Comment by petermattis** [comment]
@BramGruneir The impact on split performance will be minimal. We already do a ton of work at split time, this is a few extra checks. I'm not sure I understand your other concern. Once a cluster is fully replicated, a split range won't require additional replication. The alternative you outline seems quite a bit more work and less robust. There are two items blocking the initial ranges from being replicated: another node to replicate to and for the required splits to be complete. With this change, we trigger replication when both events occur.

**Comment by petermattis** [comment]
@BramGruneir Is calling `replicateQueue.MaybeAdd` that expensive? When we have thousands of ranges on a node we'll be calling that method dozens of times per second just due to the replica scanner. I have trouble imagining that the additional calls after a split will be problematic. And if they are, we should make `replicateQueue.MaybeAdd` faster.

**Comment by cuongdo** [comment]
Yeah, just judging from past runs of the existing
`TestUpreplicate1To3Medium` acceptance test, we consume quite a bit of CPU
in the steady state (no replica movement between nodes). A good chunk of
that is because of the replica scanner. So, I believe that moving to an
event-based model should be a win.

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[storage/replica_command.go, line 2292 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7355#-KKnNZn8CumXy5HojHLI:-KKnNZn8CumXy5HojHLJ:-387885088) ([raw file](https://github.com/cockroachdb/cockroach/blob/b43b679141065c682fc570eee8fb24aa7fdceb91/storage/replica_command.go#L2292)):*
nit: was mildly confused by the second part. How about

>
// If the range was in not properly replicated before the split, the replicate queue
// may not have picked it up (due to the need for a split). Enqueue both new halves
// to speed up a potentially necessary replication. See #7022.

---

*[storage/replicate_test.go, line 42 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7355#-KKnQ2ZTngMiVY01UbLy:-KKnQ2ZTngMiVY01UbLz:67895450) ([raw file](https://github.com/cockroachdb/cockroach/blob/07e31ad5f3afb25a402b7f219aff43ea8dcd65aa/storage/replicate_test.go#L42)):*
> ```Go
> 	// should be present in replicate queue purgatory.
> 	expected := server.ExpectedInitialRangeCount()
> 	if n := store.ReplicateQueuePurgatoryLength(); expected != n {
> ```

I'm too unfamiliar with the code to figure out why the ranges end up in purgatory. Could you add a comment as to why that is?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7355#-:-KKnQTCW_WA7oHdrW7O0:1417088721)*

**Comment by BramGruneir** [comment]
@petermattis I was just kind of spitballing a few alternate ideas that I had last night.

I just don't think adding the call on both sides of a split during normal operation will be useful.  I can see us looking to speed up splits in the near future and adding unneeded checks won't help.

Is maybeAdd fast?  It should be relatively quick, but we are possibly iterating over all stores.  So it could be faster.  We haven't worried about its performance before.

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[storage/replica_command.go, line 2292 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7355#-KKnNZn8CumXy5HojHLI:-KKnU6gQDrHsmEC7LX75:1660675680) ([raw file](https://github.com/cockroachdb/cockroach/blob/b43b679141065c682fc570eee8fb24aa7fdceb91/storage/replica_command.go#L2292)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> nit: was mildly confused by the second part. How about
> 
> >
> // If the range was in not properly replicated before the split, the replicate queue
> // may not have picked it up (due to the need for a split). Enqueue both new halves
> // to speed up a potentially necessary replication. See #7022.
</details>
Sure. Done.

---

*[storage/replicate_test.go, line 42 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7355#-KKnQ2ZTngMiVY01UbLy:-KKnUEvA49Wr6kRwlzqj:1432358394) ([raw file](https://github.com/cockroachdb/cockroach/blob/07e31ad5f3afb25a402b7f219aff43ea8dcd65aa/storage/replicate_test.go#L42)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> I'm too unfamiliar with the code to figure out why the ranges end up in purgatory. Could you add a comment as to why that is?
</details>
Done. Added `(because we only have a single store in the test and thus replication cannot succeed)`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7355)*

**Comment by BramGruneir** [comment]
@petermattis Anyway, hard to argue with results, so this change works for me.  I'm describing a potential problem that we haven't encountered yet.  So let's go with this.

But also notice that this didn't solve the problem I'm investigating about the acceptance test failures, since 2 of them just failed.

I'll take a look at speeding up maybeAdd, I didn't know we were spending so much cpu when the cluster is idle.  That seems like a problem on its own too.

**Comment by petermattis** [comment]
@cuongdo How many ranges did you have when you saw the replica scanner consuming CPU while idle?

**Comment by cuongdo** [comment]
2,265 per node (so multiply by 3)

**Comment by cuongdo** [comment]
108 GiB of data per node.

**Comment by petermattis** [comment]
@cuongdo So we'd be scanning 3.7 replicas/second with the default scan time. Surprised that would show up as a CPU consumer, but perhaps the replica allocator has some low-hanging fruit. Let's file a separate issue about this.

**Comment by bdarnell** [comment]
:lgtm:

If we make enough changes like this to make things event-driven, we may be able to slow down the replica scanner without ill effect. We should aim to make `MaybeAdd` fast enough that we can call it whenever anything interesting happens on a range. In fact, a split affects most of the queues (all of the ones with `acceptsUnsplitRanges: false`, plus the split queue itself may be ready to split the range again if it is in a new zone config or if it had gotten very large), so maybe we just should add the new ranges to all the queues after a split?

---

Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7355#-:-KKnX-iNPnqxIIA0Nh5T:592601194)*

**Comment by petermattis** [comment]
Besides the `replicateQueue`, only `gcQueue` has `acceptUnsplitRanges: false` (unless I grep'd incorrectly).

---

Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7355#-:-KKnaLERkCVoCzchhRmD:1876666957)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7355#-:-KKntIf7HxRaokE8_BXn:1417088721)*

**Comment by petermattis** [comment]
@BramGruneir I pushed another commit which sets `defaultDeclinedReservationsTimeout` to `0s` as a temporary workaround to acceptance test flakiness. Before that change `TestSingleKey` was flaky about 1 out of every 5 runs. Afterwards, I've now seen 32 successful consecutive runs.

**Comment by tschottdorf** [comment]
👍

**Pull request merged**
