### PR TITLE
sqlproxyccl: sample script to run the proxy

### PR DESCRIPTION
**Pull request by spaskob**
This script is useful for local development and testing.
We probably would like to make it more configurable
at some point.

Release note: none.

### CODE REVIEW

**Review by imjching — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57562)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @darinpp, @dt, and @spaskob)

___
*[pkg/ccl/sqlproxyccl/run_proxy.sh, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57562#-MNiOX8-B9CmabMujzYo:-MNiOX8-B9CmabMujzYp:b-wgiox0) ([raw file](https://github.com/cockroachdb/cockroach/blob/396ab7f31fced3f43059139d34ac87ea6b034fb9/pkg/ccl/sqlproxyccl/run_proxy.sh#L41)):*
> ```Shell
> 
> # Spawn the proxy on :5432, forwarding to tenant SQL server (:36257)
> go run ./pkg/cmd/mtproxy/ -cert-file $CERTSDIR/node.crt -key-file $CERTSDIR/node.key -verify=false --target 127.0.0.1:36257 &
> ```

Is this still valid? I couldn't seem to find this package here. I think we can also use `cockroach mt start-proxy`: https://github.com/cockroachdb/cockroach/blob/a1759d1a6938b50fcd59f71258b97b6299c0960c/pkg/ccl/cliccl/mtproxy.go#L31

**Comment by spaskob** [comment]
Proxy start command fixed - also changed the port to the default and added ability to change cockroach and proxy executables.

**Comment by spaskob** [comment]
PTAL

**Review by imjching — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57562#-:-MNxJl9VBE2vMdjFnxFR:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @darinpp, @dt, and @spaskob)

___
*[pkg/ccl/sqlproxyccl/run_proxy.sh, line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57562#-MNxJgPq5r8PQFqKiv61:-MNxJgPq5r8PQFqKiv62:bk586em) ([raw file](https://github.com/cockroachdb/cockroach/blob/440548cddd88898e35b5d37b8c3af580d39b3f63/pkg/ccl/sqlproxyccl/run_proxy.sh#L21)):*
> ```Shell
> rm -rf ~/.cockroach-certs cockroach-data
> killall -9 cockroach || true
> killall -9 mtproxy || true
> ```

This can be removed now since everything ties to the cockroach process.

**Comment by spaskob** [comment]
TFTRs

**Pull request merged**
