### PR TITLE
util/cgroups: method to read file-backed memory on inactive LRU list

### PR DESCRIPTION
**Pull request by abarganier**
util/cgroups: method to read file-backed memory on inactive LRU list

Currently we have methods that allows us to read the cgroup memory
limit, as well as the current memory usage, for processes running in
unix containers. However, to more accurately determine the current
memory usage in the eyes of the container provider, we must subtract
the "cache usage" from the total memory usage, which is represented
by the inactive file-backed memory stat.

From the Docker documentation:

"On Linux, the Docker CLI reports memory usage by subtracting cache
usage from the total memory usage. The API does not perform such a
calculation but rather provides the total memory usage and the amount
from the cache so that clients can use the data as needed. The cache
usage is defined as the value of total_inactive_file field in the
memory.stat file on cgroup v1 hosts...On cgroup v2 hosts, the cache
usage is defined as the value of inactive_file field."

https://docs.docker.com/engine/reference/commandline/stats/#extended-description

In an effort to gain better observability into current memory usage in
the eyes of the container provider for purposes of identifying whether
or not a CRDB node is on its way to OOM, we add the ability to read
these values from the memory subsystem. This heuristic can then be
used in debug tools such as periodic query dumps and eventually,
more generalized crash dump platforms.

Informs https://github.com/cockroachdb/cockroach/pull/66901

### CODE REVIEW

**Comment by abarganier** [comment]
Please ignore 1st commit that adds current mem. usage when reviewing (can be reviewed separately @ https://github.com/cockroachdb/cockroach/pull/68204). Will rebase once merged.

**Review by rimadeodhar — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68310)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @itsbilal, and @knz)

___
*[pkg/util/cgroups/cgroups_test.go, line 118 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68310#-MgD4Ag2BBVhwtpy1ezl:-MgD4Ag2BBVhwtpy1ezm:bihbqx4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4577e27db37c914b347da9ba149c4d280327747a/pkg/util/cgroups/cgroups_test.go#L118)):*
> ```Go
> }
> 
> func TestCgroupsGetMemoryInactiveFileUsage(t *testing.T) {
> ```

Nit: Can you add a comment that elaborates on what this test checks?

**Review by knz — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68310)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @itsbilal)

___
*[pkg/util/cgroups/cgroups.go, line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68310#-MgLoln65UzOQ11fmkM9:-MgLoln71XtSlnCUMCU3:b4k5y7g) ([raw file](https://github.com/cockroachdb/cockroach/blob/4577e27db37c914b347da9ba149c4d280327747a/pkg/util/cgroups/cgroups.go#L63)):*
> ```Go
> // current process.
> //
> //lint:ignore U1001 TODO(abarganier): will use in querydumper once merged
> ```

nit: the idiomatic way would be to do

```go
// TODO(...): ...
var _ = GetMemoryUsage
```

in the file where you plan to use this later.
___
*[pkg/util/cgroups/cgroups.go, line 89 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68310#-MgLotvA08wlDPu70Qzs:-MgLotvA08wlDPu70Qzt:b-z45q9x) ([raw file](https://github.com/cockroachdb/cockroach/blob/4577e27db37c914b347da9ba149c4d280327747a/pkg/util/cgroups/cgroups.go#L89)):*
> ```Go
> 	}
> 
> 	// no memory controller detected
> ```

full sentences in comments.
___
*[pkg/util/cgroups/cgroups.go, line 111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68310#-MgLova29s8yCPsMRRee:-MgLova29s8yCPsMRRef:bol7h3x) ([raw file](https://github.com/cockroachdb/cockroach/blob/4577e27db37c914b347da9ba149c4d280327747a/pkg/util/cgroups/cgroups.go#L111)):*
> ```Go
> }
> 
> // `root` is set to "/" in production code and exists only for testing.
> ```

it's customary to start function comments by a sentence that describes the function "xxx does yyy." and then follow up with details.
___
*[pkg/util/cgroups/cgroups.go, line 120 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68310#-MgLpFHJAM3tvRObYQ0i:-MgLpFHJAM3tvRObYQ0j:b-n48swh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4577e27db37c914b347da9ba149c4d280327747a/pkg/util/cgroups/cgroups.go#L120)):*
> ```Go
> 	}
> 
> 	// no memory controller detected
> ```

full sentences in comments.
___
*[pkg/util/cgroups/cgroups.go, line 142 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68310#-MgLp0Kh0xRwuRWk17OY:-MgLp0Kh0xRwuRWk17OZ:b-rqxvp7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4577e27db37c914b347da9ba149c4d280327747a/pkg/util/cgroups/cgroups.go#L142)):*
> ```Go
> }
> 
> // `root` is set to "/" in production code and exists only for testing.
> ```

ditto
___
*[pkg/util/cgroups/cgroups.go, line 301 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68310#-MgLp1xbDv2k0AS1RX2T:-MgLp1xbDv2k0AS1RX2U:bmv3zih) ([raw file](https://github.com/cockroachdb/cockroach/blob/4577e27db37c914b347da9ba149c4d280327747a/pkg/util/cgroups/cgroups.go#L301)):*
> ```Go
> }
> 
> // Finds memory limit value for cgroup V1 via looking in
> ```

here and below, ditto. Function name first then what the function does.

This ensures that pop-ups in code editors do the right thing.
___
*[pkg/util/cgroups/cgroups.go, line 504 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68310#-MgLpAVSD1FhFLEJl4Y6:-MgLpAVSD1FhFLEJl4Y7:b-45mdn0) ([raw file](https://github.com/cockroachdb/cockroach/blob/4577e27db37c914b347da9ba149c4d280327747a/pkg/util/cgroups/cgroups.go#L504)):*
> ```Go
> 
> 	// Check for controller specifically in cgroup v1 (it is listed in super options field),
> 	// as the value can't be found if it is not enforced
> ```

missing period at end of sentence.

**Review by abarganier — COMMENTED** [review]
Thanks for the feedback, much appreciated! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68310#-:-MgS0Xp18bn3oxdDCuBb:brbu2fd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @knz, and @rimadeodhar)

___
*[pkg/util/cgroups/cgroups.go, line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68310#-MgLoln65UzOQ11fmkM9:-MgRsxsc1KeRSc_RzYL9:b7t9wmu) ([raw file](https://github.com/cockroachdb/cockroach/blob/4577e27db37c914b347da9ba149c4d280327747a/pkg/util/cgroups/cgroups.go#L63)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: the idiomatic way would be to do

```go
// TODO(...): ...
var _ = GetMemoryUsage
```

in the file where you plan to use this later.
</blockquote></details>

Ah yes, this is much better, thanks for the tip. Since the file I want to call this in hasn't been merged yet, would calling it at the top of this same file be preferred?
___
*[pkg/util/cgroups/cgroups.go, line 89 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68310#-MgLotvA08wlDPu70Qzs:-MgRvdhP9HP1BoTvxbU_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4577e27db37c914b347da9ba149c4d280327747a/pkg/util/cgroups/cgroups.go#L89)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

full sentences in comments.
</blockquote></details>

Done.
___
*[pkg/util/cgroups/cgroups.go, line 111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68310#-MgLova29s8yCPsMRRee:-MgRvi1ZB3u8HdPMuR6G:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4577e27db37c914b347da9ba149c4d280327747a/pkg/util/cgroups/cgroups.go#L111)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

it's customary to start function comments by a sentence that describes the function "xxx does yyy." and then follow up with details.
</blockquote></details>

Done.
___
*[pkg/util/cgroups/cgroups.go, line 120 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68310#-MgLpFHJAM3tvRObYQ0i:-MgRxS9YCgV_RWn_hHMh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4577e27db37c914b347da9ba149c4d280327747a/pkg/util/cgroups/cgroups.go#L120)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

full sentences in comments.
</blockquote></details>

Done.
___
*[pkg/util/cgroups/cgroups.go, line 142 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68310#-MgLp0Kh0xRwuRWk17OY:-MgRxSp32ILFS11ROfEH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4577e27db37c914b347da9ba149c4d280327747a/pkg/util/cgroups/cgroups.go#L142)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/util/cgroups/cgroups.go, line 301 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68310#-MgLp1xbDv2k0AS1RX2T:-MgRxrU51WndsW2nRiX9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4577e27db37c914b347da9ba149c4d280327747a/pkg/util/cgroups/cgroups.go#L301)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

here and below, ditto. Function name first then what the function does.

This ensures that pop-ups in code editors do the right thing.
</blockquote></details>

Done.
___
*[pkg/util/cgroups/cgroups.go, line 504 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68310#-MgLpAVSD1FhFLEJl4Y6:-MgRzPQg91aWaZ2KikpA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4577e27db37c914b347da9ba149c4d280327747a/pkg/util/cgroups/cgroups.go#L504)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

missing period at end of sentence.
</blockquote></details>

Done.
___
*[pkg/util/cgroups/cgroups_test.go, line 118 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68310#-MgD4Ag2BBVhwtpy1ezl:-MgS-IkY2s55Pf_f3xt0:bm7w0c9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4577e27db37c914b347da9ba149c4d280327747a/pkg/util/cgroups/cgroups_test.go#L118)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

Nit: Can you add a comment that elaborates on what this test checks?
</blockquote></details>

Done - I assume this is to call out the publicly exported function that this is testing, since we call the private delegate function here?

**Review by knz — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68310)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @itsbilal)

___
*[pkg/util/cgroups/cgroups.go, line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68310#-MgLoln65UzOQ11fmkM9:-MgkPK6OACWf_gHgLySH:b-us5s0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/4577e27db37c914b347da9ba149c4d280327747a/pkg/util/cgroups/cgroups.go#L63)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

Ah yes, this is much better, thanks for the tip. Since the file I want to call this in hasn't been merged yet, would calling it at the top of this same file be preferred?
</blockquote></details>

yes that would work too

**Review by abarganier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68310)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @knz)

___
*[pkg/util/cgroups/cgroups.go, line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68310#-MgLoln65UzOQ11fmkM9:-MgkgLovA8g_hdT69Alf:b3ge4oc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4577e27db37c914b347da9ba149c4d280327747a/pkg/util/cgroups/cgroups.go#L63)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

yes that would work too
</blockquote></details>

Thanks, sounds good/Done.

**Pull request merged**
