### PR TITLE
kv: prevent lease interval regression during expiration-to-epoch promotion

### LINKED ISSUE #121480: kv: node down with closed timestamp regression
Over the weekend, the `drt-large` cluster lost a node with:

```
I240331 15:40:23.115317 7909 1@kv/kvserver/replica_closedts.go:263 ⋮ [n14] 1067593  the server is terminating due to a fatal error (see the DEV channel for details)
F240331 15:40:23.116782 7909 kv/kvserver/replica_closedts.go:263 ⋮ [n14] 1067594  side-transport update saw closed timestamp regression on r15717: (lai=9, ts=1711899619.871648444,0) -> (lai=8, ts=1711899619.880149791,0)
```

A debug.zip exists on `drt-chaos-workload:1` (named `closed_timestamp_regression_debug.zip`), but as this cluster is on spot instances with local SSDs, if you need any additional information from the data on this node, I'd encourage you to act urgently, as the data could disappear at any time without notice.

Jira issue: CRDB-37283

Epic CRDB-37617

### LINKED ISSUE #122016: kv: closed timestamp regression on drt-large
Nodes 6 and 9 of the `drt-large` cluster went down last night with closed timestamp regressions

```
F240409 07:59:27.429493 109583 kv/kvserver/replica_closedts.go:263 ⋮ [T1,Vsystem,n6] 770841  side-transport update saw closed timestamp regression on r16472: (lai=2548, ts=1712649563.889408923,0) -> (lai=2547, ts=1712649564.426571698,0)
```

and

```
F240409 02:44:44.184257 8190663 kv/kvserver/replica_closedts.go:263 ⋮ [n23] 341041  side-transport update saw closed timestamp regression on r29677: (lai=287, ts=1712630678.676057292,0) -> (lai=286, ts=1712630680.929988206,0)
```

Logs are on the respective nodes.

Jira issue: CRDB-37665

### PR DESCRIPTION
**Pull request by nvb**
Fixes #121480.
Fixes #122016.

This commit resolves a bug in the expiration-based to epoch-based lease promotion transition, where the lease's effective expiration could be allowed to regress. To prevent this, we detect when such cases are about to occur and synchronously heartbeat the leaseholder's liveness record. This works because the liveness record interval and the expiration-based lease interval are the same, so a synchronous heartbeat ensures that the liveness record has a later expiration than the prior lease by the time the lease promotion goes into effect.

The code structure here leaves a lot to be desired, but since we're going to be cleaning up and/or removing a lot of this code soon anyway, I'm prioritizing backportability. This is therefore more targeted and less general than it could be.

The resolution here also leaves something to be desired. A nicer fix would be to introduce a minimum_lease_expiration field on epoch-based leases so that we can locally ensure that the expiration does not regress. This is what we plan to do for leader leases in the upcoming release. We don't make this change because it would be require a version gate to avoid replica divergence, so it would not be backportable.

Release note (bug fix): Fixed a rare bug where a lease transfer could lead to a `side-transport update saw closed timestamp regression` panic. The bug could occur when a node was overloaded and failing to heartbeat its node liveness record.

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
@sumeerbhola I'm assigning you as a reviewer for this, because you've been most recently in this code while working on the distributed multi-epoch leases prototype and because you and I recent hypothesized about this hazard, assuming it was handled. Turns out it wasn't (which you noticed in https://github.com/cockroachdb/cockroach/pull/121474#pullrequestreview-2006467978) and it turns out there's a good change it's the cause of the recent closed timestamp regressions we're seeing on the drt clusters when their local SSDs melt down. Let me know if you'd prefer that I find another reviewer.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123442)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/replica_range_lease.go` line 516 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123442#-NwtVPVI1YYgJihXWvsS:-NwtVPVI1YYgJihXWvsT:bqvsox4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2dca05d14624ccadc4f23224648e239322e14af/pkg/kv/kvserver/replica_range_lease.go#L516)):*
> ```Go
> 		var err error
> 		// If this replica is previous & next lease holder, manually heartbeat to become live.
> 		if status.OwnedBy(nextLeaseHolder.StoreID) && p.repl.store.StoreID() == nextLeaseHolder.StoreID {
> ```

This change seems odd, given that the previous lease has expired and if this store is not that leaseholder, why should it heartbeat itself if it already has a valid node liveness. It just seems to increase the work involved in getting a lease.

Is it a requirement that `Lease.Start` and `Lease.Epoch` be consistent in that the epoch must be successfully heartbeated at start? I am guessing not since in `cmd_lease_request.go` we forward the `Lease.Start` and don't validate whether we have gone past the end of the liveness. And in `leaseStatus` we are not making any assumptions about the validity of the lease at `Lease.Start`.

And in `InitOrJoinRequest` we do:
```
		l, ok := p.repl.store.cfg.NodeLiveness.GetLiveness(nextLeaseHolder.NodeID)
		if !ok || l.Epoch == 0 {
			llHandle.resolve(kvpb.NewError(&kvpb.LeaseRejectedError{
				Existing:  status.Lease,
				Requested: reqLease,
				Message:   fmt.Sprintf("couldn't request lease for %+v: %v", nextLeaseHolder, liveness.ErrRecordCacheMiss),
			}))
			return llHandle
		}
		reqLease.Epoch = l.Epoch

```
Is the concern that this code in `InitOrJoinRequest` has not ensured that the epoch liveness extends beyond `Lease.Start`. Does it matter?

Never mind, it looks like you effectively undid this change in the next commit by making the predicate be `extension`. Presumably this was an accidental change in this commit and can be undone?
___
*[`pkg/kv/kvserver/replica_range_lease.go` line 535 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123442#-Nwte_uU6yXA_TIX09kU:-Nwte_uU6yXA_TIX09kV:brrgtg6) ([raw file](https://github.com/cockroachdb/cockroach/blob/69cfffe091a90029c41d75659e4c5576db0bff0d/pkg/kv/kvserver/replica_range_lease.go#L535)):*
> ```Go
> 	// must make sure the expiration does not regress. We do this here because the
> 	// expiration is stored directly in the lease for expiration-based leases but
> 	// indirectly in liveness record for epoch-based leases. To ensure this, we
> ```

Can you expand the `To ensure this` to include that this is expected to work because "liveness record interval and the expiration-based lease interval are the same".
___
*[`pkg/kv/kvserver/replica_range_lease.go` line 536 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123442#-Nwtc_KC5-BVZhvdpTgC:-Nwtc_KC5-BVZhvdpTgD:b30th76) ([raw file](https://github.com/cockroachdb/cockroach/blob/69cfffe091a90029c41d75659e4c5576db0bff0d/pkg/kv/kvserver/replica_range_lease.go#L536)):*
> ```Go
> 	// expiration is stored directly in the lease for expiration-based leases but
> 	// indirectly in liveness record for epoch-based leases. To ensure this, we
> 	// manually heartbeat our liveness record if necessary.
> ```

Is there a reason to do this here instead of in `InitOrJoinRequest` where we already had the `Liveness` record and knew whether it was an extension?
The general smearing of correctness logic across many methods and files is what makes me the most nervous about leases. I realize we need to backport this, so if that is the motivation here, that is fine.

Also, the other part of my concern in https://github.com/cockroachdb/cockroach/pull/121474 was related to how we change the prev lease in `RequestLease`, which could defeat this fix.
```
but say L2 had applied at the leaseholder when RequestLease was called, which then uses EvalContext.GetLease to set the previous lease
```

How about adding something like the following to `RequestLease`
```
		if prevLease.Sequence != args.PrevLease.Sequence || *prevLease.ProposedTS != *args.PrevLease.ProposedTS {
			// The previous lease has changed.
			rErr.Message = fmt.Sprintf("expected previous lease %s, found %s", args.PrevLease, prevLease)
			return newFailedLeaseTrigger(false /* isTransfer */), rErr
		}
```
___
*[`pkg/kv/kvserver/replica_range_lease.go` line 546 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123442#-NwteOEXA3Lbmx7FRuRo:-NwteOEXA3Lbmx7FRuRp:b-ms11df) ([raw file](https://github.com/cockroachdb/cockroach/blob/69cfffe091a90029c41d75659e4c5576db0bff0d/pkg/kv/kvserver/replica_range_lease.go#L546)):*
> ```Go
> 			return kvpb.NewNotLeaseHolderError(roachpb.Lease{}, p.repl.store.StoreID(), p.repl.Desc(),
> 				fmt.Sprintf("failed to manipulate liveness record: %s", err))
> 		}
> ```

Can we call `GetLiveness` here (assuming it is cheap) and if the liveness expiration is still less than the lease expiration, panic?
___
*[`pkg/kv/kvserver/client_split_test.go` line 3243 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123442#-NwtfCuoB-9gzPSQuu7h:-NwtfCuoB-9gzPSQuu7i:b-hjgr1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/69cfffe091a90029c41d75659e4c5576db0bff0d/pkg/kv/kvserver/client_split_test.go#L3243)):*
> ```Go
> 					// times below and would like for leases to not expire. Configure a
> 					// longer lease duration to achieve this.
> 					RangeLeaseDuration: 10 * replicastats.MinStatsDuration,
> ```

was this working earlier because of (a) the bug, or because (b) something in this test infrastucture is lacking and does not allow us to exercise some of the new code paths?

**Review by nvb — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123442#-:-NwuZgl25eUa8mTAtFUd:b-814g8k)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/replica_range_lease.go` line 516 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123442#-NwtVPVI1YYgJihXWvsS:-NwuWnar9Yj1Y1tUqOZd:bgl8gon) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2dca05d14624ccadc4f23224648e239322e14af/pkg/kv/kvserver/replica_range_lease.go#L516)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This change seems odd, given that the previous lease has expired and if this store is not that leaseholder, why should it heartbeat itself if it already has a valid node liveness. It just seems to increase the work involved in getting a lease.

Is it a requirement that `Lease.Start` and `Lease.Epoch` be consistent in that the epoch must be successfully heartbeated at start? I am guessing not since in `cmd_lease_request.go` we forward the `Lease.Start` and don't validate whether we have gone past the end of the liveness. And in `leaseStatus` we are not making any assumptions about the validity of the lease at `Lease.Start`.

And in `InitOrJoinRequest` we do:
```
		l, ok := p.repl.store.cfg.NodeLiveness.GetLiveness(nextLeaseHolder.NodeID)
		if !ok || l.Epoch == 0 {
			llHandle.resolve(kvpb.NewError(&kvpb.LeaseRejectedError{
				Existing:  status.Lease,
				Requested: reqLease,
				Message:   fmt.Sprintf("couldn't request lease for %+v: %v", nextLeaseHolder, liveness.ErrRecordCacheMiss),
			}))
			return llHandle
		}
		reqLease.Epoch = l.Epoch

```
Is the concern that this code in `InitOrJoinRequest` has not ensured that the epoch liveness extends beyond `Lease.Start`. Does it matter?

Never mind, it looks like you effectively undid this change in the next commit by making the predicate be `extension`. Presumably this was an accidental change in this commit and can be undone?
</blockquote></details>

I think there's some confusion here. In the first commit, I'm adding an assertion a layer above that if `status.OwnedBy(nextLeaseHolder.StoreID)` is true (prev leaseholder == next leaseholder), then `p.repl.store.StoreID() == nextLeaseHolder.StoreID`. So there's no change in behavior, just an assertion which allows us to simplify this code. I'm doing that for the reason you mentioned — it doesn't make sense for a node to heartbeat itself if it's replacing a different leaseholder.

Then in the second commit, I just lifted `extension := status.OwnedBy(nextLeaseHolder.StoreID)` up a few lines.
___
*[`pkg/kv/kvserver/replica_range_lease.go` line 535 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123442#-Nwte_uU6yXA_TIX09kU:-NwtssOn2fja0k2Cu3_C:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/69cfffe091a90029c41d75659e4c5576db0bff0d/pkg/kv/kvserver/replica_range_lease.go#L535)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you expand the `To ensure this` to include that this is expected to work because "liveness record interval and the expiration-based lease interval are the same".
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/replica_range_lease.go` line 536 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123442#-Nwtc_KC5-BVZhvdpTgC:-NwtsvxVCm01ZJUPQVMY:b-spdooa) ([raw file](https://github.com/cockroachdb/cockroach/blob/69cfffe091a90029c41d75659e4c5576db0bff0d/pkg/kv/kvserver/replica_range_lease.go#L536)):*
> Is there a reason to do this here instead of in `InitOrJoinRequest` where we already had the `Liveness` record and knew whether it was an extension?

The reason to do it here is because we're in an async task and outside of a repl.mu critical section. A liveness heartbeat is a remote RPC, so we can't do this in `InitOrJoinRequest`. That's the same reason why the other manipulation of liveness below is in this function.

> I realize we need to backport this, so if that is the motivation here, that is fine.

Yes, this is the reason why I don't want to make any unnecessary refactors here.

Going forward, I would like for us to clean all of this up and consolidate the above-raft lease validation logic. I've opened https://github.com/cockroachdb/cockroach/issues/123498 to track this, and added it to the leases roadmap for v24.2.

> the other part of my concern in [ integration prototyping for distributed multi-epoch range leases - ta… #121474](https://reviewable.io/reviews/cockroachdb/cockroach/121474) was related to how we change the prev lease in `RequestLease`, which could defeat this fix.

Done. This is also something I'd like to clean up. I did a bit of digging into where this came from (see issue above) and it dates all the way back to before proposer-eval kv, circa 2015. There's not a good reason for it anymore, now that we use `(PrevSequence, PrevProposedTS)` as the compare-and-swap key through raft.
___
*[`pkg/kv/kvserver/replica_range_lease.go` line 546 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123442#-NwteOEXA3Lbmx7FRuRo:-NwtuFlS3hILcqZ7SLLZ:bqrgafn) ([raw file](https://github.com/cockroachdb/cockroach/blob/69cfffe091a90029c41d75659e4c5576db0bff0d/pkg/kv/kvserver/replica_range_lease.go#L546)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can we call `GetLiveness` here (assuming it is cheap) and if the liveness expiration is still less than the lease expiration, panic?
</blockquote></details>

I had been concerned about races that could cause false positives, but I no longer think that's a concern. Done.
___
*[`pkg/kv/kvserver/client_split_test.go` line 3243 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123442#-NwtfCuoB-9gzPSQuu7h:-NwtqVbU4rY_UHQF8Vd4:b5i6dke) ([raw file](https://github.com/cockroachdb/cockroach/blob/69cfffe091a90029c41d75659e4c5576db0bff0d/pkg/kv/kvserver/client_split_test.go#L3243)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

was this working earlier because of (a) the bug, or because (b) something in this test infrastucture is lacking and does not allow us to exercise some of the new code paths?
</blockquote></details>

I was actually dumber than that. The test is using a manual clock, defaults to a 6 second range lease, and bumps the manual clock by 5 seconds a few different times. Before this commit, the lease was expiring during the first 5 second jump, immediately before the "do a write to increase the qps above zero". As a result, the write re-acquired the lease, which then allowed it to survive the next 5 second jump. With the change, a heartbeat during an expiration-to-epoch promotion extended the lease just enough (6 seconds) that it survived the first 5 second jump. Since it didn't expire, it wasn't refreshed by the write, so it then expired during the second 5 second jump.

This config change avoids all of this confusion around lease expiration during these manual clock jumps.

**Review by sumeerbhola — APPROVED** [review]
:lgtm_strong: 

> Reviewed 3 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123442#-:-Nwuyz_fB-zKtN5ZSpk3:b-uwkowd)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Comment by nvanbenschoten** [comment]
TFTR!

bors r=sumeerbhola

**Comment by nvanbenschoten** [comment]
`acceptance/version-upgrade` failed due to an unrelated `workload run schemachange` error:
```
Error: ***UNEXPECTED ERROR; Received an unexpected execution error.: ERROR: unimplemented: default value (SQLSTATE 0A000)
```

bors r+

**Pull request merged**
