### PR TITLE
sql: support the `USAGE` privilege on schemas

### LINKED ISSUE #53342: sql: support the `USAGE` permission for schemas
Schemas in Postgres have the `USAGE` permission, which controls whether or not a user can even resolve objects within a schema.

### PR DESCRIPTION
**Pull request by rohany**
Fixes #53342.

This commit adds the `USAGE` privilege to schemas. The `USAGE` privilege
allows a user to resolve objects under a schema.

Release note (sql change): Support the `USAGE` privelege on schemas.

### CODE REVIEW

**Comment by rohany** [comment]
First commit is https://github.com/cockroachdb/cockroach/pull/53344

**Review by solongordon — APPROVED** [review]
> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53358)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @lucy-zhang, @rohany, and @solongordon)

___
*[pkg/sql/logictest/testdata/logic_test/schema, line 293 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53358#-MFWyEndCLv_62FOJzTp:-MFWyEne7bxYUrwgRPYp:b-jcup54) ([raw file](https://github.com/cockroachdb/cockroach/blob/d66d3934fce116b8cade503082c51187a013c833/pkg/sql/logictest/testdata/logic_test/schema#L293)):*
> ```
> statement ok
> CREATE TABLE privs.usage_tbl (x INT);
> CREATE TYPE privs.usage_typ AS ENUM ('usage');
> ```

Would it make this test stronger if you also granted SELECT on the table and USAGE on the type?

**Comment by rohany** [comment]
> Would it make this test stronger if you also granted SELECT on the table and USAGE on the type?

I don't think so, as Postgres(and we now) check the schema permissions first before the object permissions. I'm asserting that I get a schema permission error as well

**Comment by rohany** [comment]
> Would it make this test stronger if you also granted SELECT on the table and USAGE on the type?

I don't think so, as Postgres(and we now) check the schema permissions first before the object permissions. I'm asserting that I get a schema permission error as well, so we know that we're getting the right error

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53358#-:-MFXq8vLDrFlShYc8tzw:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lucy-zhang, @rohany, and @solongordon)

**Review by ajwerner — COMMENTED** [review]
speaking of @solongordon's question, do we properly deal with the `USAGE` privilege on enums? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53358#-:-MFXqYrO6vtKX-Kvx2t3:b-dhk2rv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lucy-zhang, @rohany, and @solongordon)

**Review by thoszhang — APPROVED** [review]
> Reviewed 14 of 16 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53358)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rohany)

___
*[pkg/sql/grant_revoke.go, line 231 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53358#-MFYBh7sBfuXMeVZ5_b5:-MFYB3OpElq_YK0Yetq-:bvdm4f0) ([raw file](https://github.com/cockroachdb/cockroach/blob/d66d3934fce116b8cade503082c51187a013c833/pkg/sql/grant_revoke.go#L231)):*
> ```Go
> 			}
> 		case *schemadesc.Mutable:
> 			if err := p.writeSchemaDescChange(
> ```

Don't have to change anything right now, but I think eventually we should be doing all these writes in the same batch.

**Comment by rohany** [comment]
> speaking of @solongordon's question, do we properly deal with the USAGE privilege on enums?

No, the usage privilege on enums is a bit different. `USAGE` on enums doesn't disallow just using the type in a `SELECT 'x'::mytype`. It only disallows you from using the type in a table or something that would cause a back reference.

**Comment by ajwerner** [comment]
> > speaking of @solongordon's question, do we properly deal with the USAGE privilege on enums?
> 
> No, the usage privilege on enums is a bit different. `USAGE` on enums doesn't disallow just using the type in a `SELECT 'x'::mytype`. It only disallows you from using the type in a table or something that would cause a back reference.

Just so we're clear, what you mean is if you have `USAGE` then you *can* create tables, right? Not having it disallows using it in tables. Nothing prevents selecting it IIUC so long as you can resolve it. That was my reading of

```
For types and domains, allows use of the type or domain in the creation of tables, functions, and other schema objects. (Note that this privilege does not control all “usage” of the type, such as values of the type appearing in queries. It only prevents objects from being created that depend on the type. The main purpose of this privilege is controlling which users can create dependencies on a type, which could prevent the owner from changing the type later.)
```

https://www.postgresql.org/docs/12/ddl-priv.html

**Comment by rohany** [comment]
Yes, thats what I meant. I was trying to say that having usage or not doesn't affect this particular test case.

**Comment by otan** [comment]
bors r-

looks like this is broken on CI

**Comment by rohany** [comment]
hmmmm

**Comment by otan** [comment]
hmm

:D

**Pull request merged**
