### PR TITLE
sql: add racewithbackfill case for hash sharded indexes

### PR DESCRIPTION
**Pull request by jordanlewis**
Release note: None

### CODE REVIEW

**Comment by postamar** [comment]
Oh wow.

**Comment by jordanlewis** [comment]
Wait, what's the wow? I sent this in just because, but I couldn't actually get it to fail :(

**Comment by postamar** [comment]
It totally did fail with the race detector, in CI. I thought that's why you created this PR.

**Comment by postamar** [comment]
I can repro the same behaviour locally: `make test` passes and `make testrace` hangs. I maintain and uphold my "Oh wow."

**Comment by postamar** [comment]
After having run the test a couple of dozen times, I noticed the test only hangs intermittently and in the runs where it hangs I get:
```
=== RUN   TestRaceWithBackfill
    test_log_scope.go:73: test logs captured to: /var/folders/53/0v5rqk_14lg0lvtzt8zm61rr0000gp/T/logTestRaceWithBackfill337694583
    test_log_scope.go:74: use -show-logs to present logs inline
    schema_changer_test.go:330: schema change ALTER TABLE t.test ADD COLUMN x DECIMAL DEFAULT (DECIMAL '1.4') CHECK (x >= 0) took 1.399793s
    schema_changer_test.go:330: schema change ALTER TABLE t.test DROP pi took 1.073828s
    schema_changer_test.go:330: schema change CREATE UNIQUE INDEX foo ON t.test (v) took 2.760541s
    schema_changer_test.go:330: schema change CREATE INDEX bar ON t.test(k) STORING (v) took 1.518181s
    schema_changer_test.go:328: pq: hash sharded indexes require the experimental_enable_hash_sharded_indexes session variable
    schema_changer_test.go:330: schema change CREATE INDEX zoop ON t.test(n ASC) USING HASH WITH BUCKET_COUNT = 32 took 14.934ms
```

During successful runs I don't see this complaint about an unset `experimental_enable_hash_sharded_indexes`, what's this doing here? Shouldn't it always be set at the point where the test is walking through the schema changes? 

The session var being somehow still unset would explain why this test fails. This, sadly, won't help us with our original problem, but we might have stumbled onto another unrelated bug.

**Comment by ajwerner** [comment]
>what's this doing here? Shouldn't it always be set at the point where the test is walking through the schema changes?

The code only sets it on one connection. You're using a `sql.DB`. There's no guarantee that that DB will give you the same connection. My guess is that there's a race involving putting the connection back in the pool. If you want to stop hitting this error, also set the cluster setting to default that to on. `SET CLUSTER SETTING sql.defaults.experimental_hash_sharded_indexes.enabled = true;`.

**Pull request closed without merging**
