### PR TITLE
Check Stopper when waiting for a Raft command to complete

### PR DESCRIPTION
**Pull request by kkaneda**
Some tests didn't finish when they were being torn down while `updateStoreStatus()` was still waiting for the response of `Put()`. This issue can be reproduced by setting ScanInterval to a short interval (e.g., 10ms) and making the scanner call updateStoreStatus() more frequently.

### CODE REVIEW

**Comment by spencerkimball** [comment]
Because updateStoreStatus() is called with an outstanding stopper task (see scanner.go:200), nothing should be getting torn down yet while updateStoreStatus() is still waiting for the response of `Put()`. What's the actual failure?

**Comment by kkaneda** [comment]
Ah, I see. Hmm, I'll take a look more. The actual error I got was that a test didn't finish after printing the following message:

```
L="ERROR" T="5/15 07:06:23.042" F="transport.go:202" Msg="sending rpc failed: read tcp 127.0.0.1:57829: use of closed network connection"
```

Stacktrace indicates that a gorountine was waiting for a message from `errChan` in `addWriteCmd`.

```
goroutine 2147 [chan receive]:
github.com/cockroachdb/cockroach/storage.func·017(0x0, 0x0)
	/Users/kaneda/Development/go/src/github.com/cockroachdb/cockroach/storage/range.go:678 +0xb1
github.com/cockroachdb/cockroach/storage.(*Range).addWriteCmd(0xc208185680, 0x52a4998, 0xc2082006f0, 0x52a52f8, 0xc208520780, 0x52a5350, 0xc2086082a0, 0xc208200601, 0x0, 0x0)
	/Users/kaneda/Development/go/src/github.com/cockroachdb/cockroach/storage/range.go:694 +0x8ea
github.com/cockroachdb/cockroach/storage.(*Range).AddCmd(0xc208185680, 0x52a4998, 0xc2082006f0, 0x52a52f8, 0xc208520780, 0x52a5350, 0xc2086082a0, 0x0, 0x0, 0x0, ...)
	/Users/kaneda/Development/go/src/github.com/cockroachdb/cockroach/storage/range.go:507 +0x4f6
github.com/cockroachdb/cockroach/storage.func·039(0xc208127a20, 0x0, 0x0)
	/Users/kaneda/Development/go/src/github.com/cockroachdb/cockroach/storage/store.go:1099 +0x3b0
github.com/cockroachdb/cockroach/util.RetryWithBackoff(0xc208127a20, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc2081f2f20, 0x0, ...)
	/Users/kaneda/Development/go/src/github.com/cockroachdb/cockroach/util/retry.go:81 +0x60
github.com/cockroachdb/cockroach/storage.(*Store).ExecuteCmd(0xc2081e61c0, 0x52a4958, 0xc20802cc88, 0x52a52f8, 0xc208520780, 0x52a5350, 0xc2086082a0, 0x0, 0x0, 0x0, ...)
	/Users/kaneda/Development/go/src/github.com/cockroachdb/cockroach/storage/store.go:1149 +0x762
github.com/cockroachdb/cockroach/kv.(*LocalSender).Send(0xc208637d40, 0x52a4958, 0xc20802cc88, 0x52a52f8, 0xc208520780, 0x52a5350, 0xc2086082a0, 0x0, 0x0, 0x0)
	/Users/kaneda/Development/go/src/github.com/cockroachdb/cockroach/kv/local_sender.go:150 +0x1cd
github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).sendOne(0xc20829de00, 0x52a52f8, 0xc208520780, 0x52a5350, 0xc2086082a0, 0x0, 0x0, 0x0)
	/Users/kaneda/Development/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:302 +0x26d
github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).Send(0xc20829de00, 0x52a4958, 0xc20802cc88, 0x52a52f8, 0xc208520780, 0x52a5350, 0xc2086082a0, 0x0, 0x0, 0x0)
	/Users/kaneda/Development/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:243 +0x51e
github.com/cockroachdb/cockroach/client.(*KV).Run(0xc20806f600, 0xc20850c400, 0x1, 0x1, 0x0, 0x0)
	/Users/kaneda/Development/go/src/github.com/cockroachdb/cockroach/client/kv.go:108 +0x3fa
github.com/cockroachdb/cockroach/client.(*DB).Run(0xc2084de7c8, 0xc2084fd000, 0x0, 0x0)
	/Users/kaneda/Development/go/src/github.com/cockroachdb/cockroach/client/db.go:300 +0x8e
github.com/cockroachdb/cockroach/client.runOne(0x52a6d70, 0xc2084de7c8, 0xc2084fd000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/kaneda/Development/go/src/github.com/cockroachdb/cockroach/client/db.go:894 +0x6b
github.com/cockroachdb/cockroach/client.(*DB).Put(0xc2084de7c8, 0x4a13c80, 0xc20812d340, 0x4a20780, 0xc208647880, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/kaneda/Development/go/src/github.com/cockroachdb/cockroach/client/db.go:201 +0xdb
github.com/cockroachdb/cockroach/storage.(*Store).updateStoreStatus(0xc2081e6380)
	/Users/kaneda/Development/go/src/github.com/cockroachdb/cockroach/storage/store.go:1442 +0x3a9
github.com/cockroachdb/cockroach/storage.*Store.(github.com/cockroachdb/cockroach/storage.updateStoreStatus)·fm()
	/Users/kaneda/Development/go/src/github.com/cockroachdb/cockroach/storage/store.go:314 +0x27
github.com/cockroachdb/cockroach/storage.func·029()
	/Users/kaneda/Development/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:200 +0x634
github.com/cockroachdb/cockroach/util.func·001()
	/Users/kaneda/Development/go/src/github.com/cockroachdb/cockroach/util/stopper.go:73 +0x51
created by github.com/cockroachdb/cockroach/util.(*Stopper).RunWorker
	/Users/kaneda/Development/go/src/github.com/cockroachdb/cockroach/util/stopper.go:74 +0xe3
```

And another goroutine was waiting at `s.drain.Wait()`.

```
goroutine 7364 [semacquire]:
sync.(*WaitGroup).Wait(0xc20807eb98)
	/usr/local/go/src/sync/waitgroup.go:132 +0x169
github.com/cockroachdb/cockroach/util.(*Stopper).Stop(0xc20807eb60)
	/Users/kaneda/Development/go/src/github.com/cockroachdb/cockroach/util/stopper.go:127 +0xaf
github.com/cockroachdb/cockroach/storage_test.(*multiTestContext).Stop(0xc208021380)
	/Users/kaneda/Development/go/src/github.com/cockroachdb/cockroag1ch/storage/client_test.go:161 +0x92
github.com/cockroachdb/cockroach/storage_test.TestStoreRangeReplicate(0xc208208000)
	/Users/kaneda/Development/go/src/github.com/cockroachdb/cockroach/storage/client_raft_test.go:524 +0x353
testing.tRunner(0xc208208000, 0x4e45130)
	/usr/local/go/src/testing/testing.go:447 +0xbf
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:555 +0xa8b
```

**Comment by kkaneda** [comment]
I could be wrong, but this might be the issue of drain ordering. Here are test logs with additional messages, and it shows that `multiraft.state.stop()` was called while the scanner is still canning `scanFn()`. 

```
L="ERROR" T="5/15 07:45:35.500" F="scanner.go:200" Msg="Calling scanFn()"
L="ERROR" T="5/15 07:45:35.503" F="multiraft.go:483" Msg="node 100000001: stopping"
L="ERROR" T="5/15 07:45:35.503" F="transport.go:202" Msg="sending rpc failed: read tcp 127.0.0.1:62723: use of closed network connection"
  ...
L="ERROR" T="5/15 07:45:35.503" F="transport.go:202" Msg="sending rpc failed: read tcp 127.0.0.1:62723: use of closed network connection"
L="ERROR" T="5/15 07:45:35.503" F="multiraft.go:483" Msg="node 200000002: stopping"
L="ERROR" T="5/15 07:45:35.503" F="transport.go:202" Msg="sending rpc failed: read tcp 127.0.0.1:51836: use of closed network connection"
 ...
L="ERROR" T="5/15 07:45:35.503" F="transport.go:202" Msg="sending rpc failed: read tcp 127.0.0.1:51836: use of closed network connection"
L="ERROR" T="5/15 07:45:35.503" F="multiraft.go:175" Msg="Stopping"
 ...
L="ERROR" T="5/15 07:45:35.503" F="multiraft.go:175" Msg="Stopping"
panic: test timed out after 20s
```

**Comment by spencerkimball** [comment]
I assume you added the log message for

L="ERROR" T="5/15 07:45:35.500" F="scanner.go:200" Msg="Calling scanFn()"

Did you have a similar message to indicate when the call to scanFn()
completed? While scanFn() is active, there should be no way for
stopper.ShouldStop() to signal and stop the multiraft nodes.

**Comment by bdarnell** [comment]
The tests in client_raft_test.go use multiple stores, each with their own stopper. Two stores have been shut down (that's why you see two "multiraft stopping" log lines), but the third is kept alive by its scanner (and the scanner can't exit until it has completed a write, which depends on the other stores being up).

Does this actually fix the problem? ShouldStop() shouldn't be true until after the "draining" phase is complete, and the hang here appears to occur while draining, not while stopping.

This is a tricky one. Sometimes we need to be able to stop and restart each store independently, but at the end of the test we need to shut them all down in unison. I think we need to modify Stopper.Quiesce to leave the stopper in the draining state (adding a new Unquiesce method to set draining back to 0), and then we can quiesce all the stoppers before stopping any of them in multiTestContext.Stop.

**Comment by kkaneda** [comment]
Thanks for the explanation, @spencerkimball , @bdarnell . Yes, I added the log message for the scan completion, and it didn't appear (assuming that the log was flushed). Sorry, it wasn't clear.

The test passed after the change, but it might just be a timing issue... Hmm, this looks tricker than I had thought. I'll take a look at what Ben suggested. (I wanted to fix test flakiness before modifying the scanner.)

**Pull request closed without merging**
