### PR TITLE
pgwire: add a metric for number of pipelined requests

### LINKED ISSUE #123912: sql: add a metric for number of statements queued in stmtBuf due to pipelining
**Is your feature request related to a problem? Please describe.**
If a client is using the query pipeline mode (https://www.postgresql.org/docs/current/libpq-pipeline-mode.html), then queries may arrive at CRDB faster than they can be processed. This will lead to a queue building up in the connExecutor `stmtBuf`: https://github.com/cockroachdb/cockroach/blob/bf28084f84af660ba3c65f9f39dea5e41957f9e9/pkg/sql/pgwire/conn.go#L386 

Right now, we cannot directly view any metrics to see how many queries are waiting in the stmtBuf.

**Describe the solution you'd like**
Add a gauge metric that is incremented in `stmtBuf.Push`: https://github.com/cockroachdb/cockroach/blob/e012d108896599dcb8d904a36bfce2c7a8d04117/pkg/sql/conn_io.go#L497-L501

It should be decremented in `LTrim`: https://github.com/cockroachdb/cockroach/blob/e012d108896599dcb8d904a36bfce2c7a8d04117/pkg/sql/conn_io.go#L563-L567

(open question: maybe we should decrement when `curPos` is modified, not `lastPos`?)

**Describe alternatives you've considered**
The closest way to approximate this is to compare the `sql.{update|insert|select|delete}.started.count` metric to the `sql.{update|insert|select|delete}.count` metric.

**Additional Context**
Follow up from a support escalation: https://cockroachdb.zendesk.com/agent/tickets/20683

Epic CRDB-38033

Jira issue: CRDB-38601

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/123912
Release note (ops change): Added the sql.pgwire.pipeline.count metric, which is a gauge that measures how many wire protocol commands have been received by the server, but have not yet begun processing. This metric will only grow if clients are using the "pipeline mode" of the Postgres wire protocol.

### CODE REVIEW

**Review by fqazi — APPROVED** [review]
Just one minor question :lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124231#-:-NxxpR6CCXcgo4q0zRi0:b-ei848e)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/pgwire/conn_test.go` line 300 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124231#-Nxxk64B5KS4-63-vb0h:-Nxxk64B5KS4-63-vb0i:b-tqtikc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a4a171b0819821b4b53caed18a4d23544978ebb/pkg/sql/pgwire/conn_test.go#L300)):*
> ```Go
> 	require.NoError(t, err)
> 
> 	testutils.SucceedsSoon(t, func() error {
> ```

Is this because we need to wait for the queries above to finish in the pipeline? Could we do GetResults?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124231)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/pgwire/conn_test.go` line 300 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124231#-Nxxk64B5KS4-63-vb0h:-Nxy6asXErRDoQaOFjKO:b1mujts) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a4a171b0819821b4b53caed18a4d23544978ebb/pkg/sql/pgwire/conn_test.go#L300)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Is this because we need to wait for the queries above to finish in the pipeline? Could we do GetResults?
</blockquote></details>

this is actually needed since we have to wait for the queries to reach the server and get into the pipeline.

GetResults wouldn't work here since the fake server in this test never actually sends results back to the client. and the reason we need a fake server is so that we can control exactly when the stmtBuf is read from.

i'll add some comments

**Review by rafiss — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124231#-:-Nxy7lKU70dc5VDQc_NR:b-ydi9ay)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @fqazi)

**Comment by rafiss** [comment]
tftr!

bors r+

**Pull request merged**
