### PR TITLE
opt: don't update computed columns unnecessarily

### LINKED ISSUE #42482: opt: don't recompute computed columns unnecessarily during updates
Example:

```
CREATE TABLE kv (
	k INT8 PRIMARY KEY, u INT8, v INT8, w INT8 AS (v + 1) STORED,
	FAMILY (u),
	FAMILY (v),
	FAMILY (w)
);

EXPLAIN (OPT, VERBOSE) UPDATE kv SET u = u + 1 WHERE k = 1;
                            text                            
+----------------------------------------------------------+
  update kv                                                 
   ├── columns: <none>                                      
   ├── fetch columns: k:5 u:6 w:8                           
   ├── update-mapping:                                      
   │    ├──  column9:9 => u:2                               
   │    └──  column10:10 => w:4                             
   ├── cardinality: [0 - 0]                                 
   ├── side-effects, mutations                              
   ├── stats: [rows=0]                                      
   ├── cost: 1.14                                           
   └── project                                              
        ├── columns: column10:10 column9:9 k:5 u:6 w:8      
        ├── cardinality: [0 - 1]                            
        ├── stats: [rows=1]                                 
        ├── cost: 1.13                                      
        ├── key: ()                                         
        ├── fd: ()-->(5,6,8-10)                             
        ├── prune: (5,6,8-10)                               
        ├── scan kv                                         
        │    ├── columns: k:5 u:6 v:7 w:8                   
        │    ├── constraint: /5: [/1 - /1]                  
        │    ├── cardinality: [0 - 1]                       
        │    ├── stats: [rows=1, distinct(5)=1, null(5)=0]  
        │    ├── cost: 1.09                                 
        │    ├── key: ()                                    
        │    └── fd: ()-->(5-8)                             
        └── projections                                     
             ├── v + 1 [outer=(7)]                          
             └── u + 1 [outer=(6)]                          
```

We shouldn't need to read `v` and recompute `w` just because we're changing `u`.

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### optbuilder: make addColumn a method on scope

Release note: None

#### optbuilder: projectionBuilder helper

Separating a small helper to make the `addSynthesizedCols` code more
readable.

Release note: None

#### optbuilder: split addSynthesizedCols

This code is always used to either build only non-computed columns, or
only computed columns. These two cases are logically different steps
in the process.

This commit splits it into two versions for the two purposes. This
removes the callbacks and will allow adding improvements that are
specific to a single step.

Release note: None

#### opt: don't update computed columns unnecessarily

We currently project the new value for all computed columns, even when
we are doing an UPDATE that doesn't affect a computed column. This can
lead to unnecessary index joins in some cases.

This change fixes this by checking whether any of the referenced
columns are being updated. If not, we do not update the target
columns (which lets existing normalization rules prune the
unnecessary projection).

Fixes #42482.

Release note (performance improvement): potentially improved
performance for UPDATE statements where the table has computed columns
that don't depend on updated columns.

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
:lgtm: Very cool! Thanks for packaging it up so beautifully into 4 commits. It made it very pleasant to review.

[nit] in commit message: "which lets existing normalization rules to prune the unnecessary projection" => "... rules prune ..."

> Reviewed 11 of 11 files at r1, 2 of 2 files at r2, 3 of 3 files at r3, 11 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58188#-:-MPBmJhv1nGtS8JrJuCE:b7thyvf)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 592 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58188#-MPBfNNj2QvP5L8QBPZO:-MPBfNNkDECd7LgdBtmN:b-ouzgds) ([raw file](https://github.com/cockroachdb/cockroach/blob/925c9e0c669bbdc148e04a566523efe831007fc6/pkg/sql/opt/optbuilder/mutation_builder.go#L592)):*
> ```Go
> 
> 		// Add synthesized column. It is important to use the real column name in
> 		// when this is a default column, which may latter be referred by a computed
> ```

[nit] "name in when" => "name when"
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 554 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58188#-MPBkc4q0H4xPyU_kXbT:-MPBkc4q0H4xPyU_kXbU:bytrktp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0681593a04fb39600ac22e5972eb1e0de3ecb9b/pkg/sql/opt/optbuilder/mutation_builder.go#L554)):*
> ```Go
> //      use a default value (0 for INT column, "" for STRING column, etc). Note
> //      that the existing "fetched" value returned by the scan cannot be used,
> //      since it may not have been initialized yet by the backfiller.
> ```

I'm surprised (3) is valid. How can we assume a value for a mutation column?
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 569 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58188#-MPBiqvU5xlBGtSdj_vp:-MPBiqvU5xlBGtSdj_vq:b-hfsdhm) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0681593a04fb39600ac22e5972eb1e0de3ecb9b/pkg/sql/opt/optbuilder/mutation_builder.go#L569)):*
> ```Go
> 	for i, n := 0, mb.tab.ColumnCount(); i < n; i++ {
> 		tabCol := mb.tab.Column(i)
> 		if kind := tabCol.Kind(); !(kind == cat.WriteOnly || (!onlyWriteOnly && kind == cat.Ordinary)) {
> ```

[nit] this conditional is quite the brain teaser. might be easier to grok if you make a variable for the opposite.

```
validKind := kind == cat.WriteOnly || (!onlyWriteOnly && kind == cat.Ordinary)
if !validKind {
    continue
}
```
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 576 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58188#-MPBlB163MRX7_7G8NS8:-MPBlB163MRX7_7G8NS9:b-f61qib) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0681593a04fb39600ac22e5972eb1e0de3ecb9b/pkg/sql/opt/optbuilder/mutation_builder.go#L576)):*
> ```Go
> 			continue
> 		}
> 		// Skip columns that are already specified.
> ```

[nit] Should this also have the note `(this is possible for upserts)`, like below?
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 585 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58188#-MPBlL340CqnrlDvYsU-:-MPBlL340CqnrlDvYsU0:b-ouzgds) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0681593a04fb39600ac22e5972eb1e0de3ecb9b/pkg/sql/opt/optbuilder/mutation_builder.go#L585)):*
> ```Go
> 
> 		// Add synthesized column. It is important to use the real column name in
> 		// when this is a default column, which may latter be referred by a computed
> ```

[nit] "name in when" => "name when"

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

Fixed commit message.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58188#-:-MPD6wId53iXk3MGbRz4:bw675o8)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 554 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58188#-MPBkc4q0H4xPyU_kXbT:-MPD20eM0D5dhLO4gpMl:b1pknp4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0681593a04fb39600ac22e5972eb1e0de3ecb9b/pkg/sql/opt/optbuilder/mutation_builder.go#L554)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I'm surprised (3) is valid. How can we assume a value for a mutation column?
</blockquote></details>

There is some context here: https://github.com/cockroachdb/cockroach/commit/d76e06a5c5462348206c88ac53d44ae7cf620a3b
and in the issue:
https://github.com/cockroachdb/cockroach/issues/42459#issuecomment-599088593

I think the cliff notes are that in these cases the value does not really matter (it will not be visible), as long as it doesn't cause a violation of the not-null constraint.
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 576 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58188#-MPBlB163MRX7_7G8NS8:-MPD5uww26-fDz0KUMU4:bd1gn8s) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0681593a04fb39600ac22e5972eb1e0de3ecb9b/pkg/sql/opt/optbuilder/mutation_builder.go#L576)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] Should this also have the note `(this is possible for upserts)`, like below?
</blockquote></details>

No, it's different below because that pertains to computed columns, for which you cannot provide a value (e.g. in an INSERT).

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 11 of 11 files at r1, 2 of 2 files at r2, 3 of 3 files at r3, 8 of 11 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58188#-:-MPEwoOfAAfWOvFtdfM4:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/norm/testdata/rules/prune_cols, line 1984 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/58188#-MPEuJpD4bj5UOGyiP-n:-MPEuG3068LcQ9wKpJoT:b-mxdlq0) ([raw file](https://github.com/cockroachdb/cockroach/blob/56ec1d789f584a980a046e65f5bf5db949182027/pkg/sql/opt/norm/testdata/rules/prune_cols#L1984)):*
> ```
> 
> # We should not be producing a value for the computed column d, which is not
> # being changed. We should, however produce a value for the write-only column x
> ```

[super nit] add a comma after "however"
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 592 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58188#-MPEp0dS6qxLkds5tfBf:-MPEp0dTBro2PqoDidwE:b-3dz19n) ([raw file](https://github.com/cockroachdb/cockroach/blob/925c9e0c669bbdc148e04a566523efe831007fc6/pkg/sql/opt/optbuilder/mutation_builder.go#L592)):*
> ```Go
> 
> 		// Add synthesized column. It is important to use the real column name in
> 		// when this is a default column, which may latter be referred by a computed
> ```

[nit] latter -> later
___
*[pkg/sql/opt/optbuilder/project.go, line 326 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58188#-MPEpT7XBuGzMZZdvK2w:-MPEpT7Y3FbtJ6fUUrBJ:b-3edqra) ([raw file](https://github.com/cockroachdb/cockroach/blob/925c9e0c669bbdc148e04a566523efe831007fc6/pkg/sql/opt/optbuilder/project.go#L326)):*
> ```Go
> }
> 
> // Add a projection.
> ```

[nit] explain what the return values are
___
*[pkg/sql/opt/optbuilder/scope.go, line 276 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58188#-MPEnqbDA-EDfJ4zU41M:-MPEnqbEB8RaB6WnGl3M:b-ta1cd9) ([raw file](https://github.com/cockroachdb/cockroach/blob/82c0f94703b81b1871b226c7d1cee1cd0c6d08ed/pkg/sql/opt/optbuilder/scope.go#L276)):*
> ```Go
> }
> 
> // addColumn adds a column to scope with the given alias, type, and
> ```

[nit] alias, type, and expression -> alias and typed expression

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58188#-:-MPF7EzMC-MCU6C5Db5I:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/norm/testdata/rules/prune_cols, line 1984 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/58188#-MPEuJpD4bj5UOGyiP-n:-MPF4UYX2tTICU5Vw79w:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/56ec1d789f584a980a046e65f5bf5db949182027/pkg/sql/opt/norm/testdata/rules/prune_cols#L1984)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[super nit] add a comma after "however"
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 592 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58188#-MPEp0dS6qxLkds5tfBf:-MPF4hB992T-f8NMD5Yo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/925c9e0c669bbdc148e04a566523efe831007fc6/pkg/sql/opt/optbuilder/mutation_builder.go#L592)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] latter -> later
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/project.go, line 326 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58188#-MPEpT7XBuGzMZZdvK2w:-MPF6Ln5DGqGDWvXdBn0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/925c9e0c669bbdc148e04a566523efe831007fc6/pkg/sql/opt/optbuilder/project.go#L326)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] explain what the return values are
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/scope.go, line 276 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/58188#-MPEnqbDA-EDfJ4zU41M:-MPF6ZE97cXOVeJPTJ1P:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/82c0f94703b81b1871b226c7d1cee1cd0c6d08ed/pkg/sql/opt/optbuilder/scope.go#L276)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] alias, type, and expression -> alias and typed expression
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 12 files at r6, 11 of 11 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58188)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner)

**Review by RaduBerinde — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58188#-:-MPFgoD1Ea6ShneN3YF7:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner)

**Comment by mgartner** [comment]
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 562 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/58188#-MPFvRWf7yFDLxTCKcxO:-MPFvRWf7yFDLxTCKcxP:boongkh) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9b4687afb4cafd531290f7128557872d4a42653/pkg/sql/opt/optbuilder/mutation_builder.go#L562)):*
> ```Go
> // are added to mb.outScope.
> func (mb *mutationBuilder) addSynthesizedDefaultCols(
> 	colIDs opt.OptionalColList, includeOrdinary bool,
> ```

:+1:  `onlyWriteOnly` was good while it lasted though... :laughing:

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 562 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/58188#-MPFvRWf7yFDLxTCKcxO:-MPGLE9-65RjewPBCnE1:bc52tdo) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9b4687afb4cafd531290f7128557872d4a42653/pkg/sql/opt/optbuilder/mutation_builder.go#L562)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

:+1:  `onlyWriteOnly` was good while it lasted though... :laughing: 
</blockquote></details>

:laughing:

**Pull request merged**
