### PR TITLE
kvserver: enable loosely coupled raft log truncation

### PR DESCRIPTION
**Pull request by sumeerbhola**
The const override that disabled loosely coupled truncation
is removed. There is additional testing of both the end-to-end
path and the truncator.

Informs #36262

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
The first two commits are from https://github.com/cockroachdb/cockroach/pull/76215 and https://github.com/cockroachdb/cockroach/pull/76793

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76902#-:-MwY-cvF0H2E_r5-WRuW:b-vxpxtu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @nvanbenschoten, and @tbg)

**Review by sumeerbhola — COMMENTED** [review]
Rebased. The non test changes are tiny.
Most of the test diffs are indentation changes due to running the kvserver server-side tests both with and without loosely-coupled truncation. The client-side kvserver tests are only run with whatever is the default truncation behavior.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76902#-:-Mwb5Nl8AjIsfoYs88yL:bzc07xi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @nvanbenschoten, and @tbg)

**Review by tbg — COMMENTED** [review]
Haven't reviewed the tests yet, have a suggestion on how to simplify the prod code. Will review tests first thing tomorrow.

> Reviewed 3 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76902#-:-MwbWuRp0ACzvujc9naJ:bqmziyk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/kv/kvserver/raft_log_truncator.go, line 394 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76902#-MwbUe3L3XXXi0ezd4Pq:-MwbUe3MAq2DSVY7n-pZ:b-1dmkch) ([raw file](https://github.com/cockroachdb/cockroach/blob/13456187352fca48914767f737a617a3b723682b/pkg/kv/kvserver/raft_log_truncator.go#L394)):*
> ```Go
> 	if runTruncation {
> 		if err := t.stopper.RunAsyncTask(
> 			t.ambientCtx, "raft-log-truncation", t.durabilityAdvanced); err != nil {
> ```

Consider pulling the `t.mu.runningTruncation = false` out. It is nice to have it all in one place.

Near the top of the method:

```
runTruncation := false
done := func() {}

t.mu.Lock()
[...]
  runTruncation = true
  t.mu.runningTruncation = true
  done := func() {
    t.mu.Lock()
    if !t.mu.runningTruncation { panic("...") }
    t.mu.runningTruncation = false
    t.mu.Unlock()
  }

[...]

for runTruncation {
  if err := t.stopper.RunAsyncTask(...., func(ctx context.Context) {
    defer done()
    for {
      t.durabilityAdvanced(ctx)
      t.mu.Lock()
      queued := t.mu.queuedDurabilityCB
      t.mu.queuedDurabilityCB = false
      t.mu.Unlock()
      if !queued { return }
    }
  }); err != nil {
    done()
    return
  }
  
}
```

That way `runningTruncation` is only accessed in this method.
___
*[pkg/kv/kvserver/raft_log_truncator.go, line 435 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76902#-MwbWX8A9QsVQ_KDVX1_:-MwbWX8A9QsVQ_KDVX1a:b-clc2mg) ([raw file](https://github.com/cockroachdb/cockroach/blob/13456187352fca48914767f737a617a3b723682b/pkg/kv/kvserver/raft_log_truncator.go#L435)):*
> ```Go
> 		t.tryEnactTruncations(ctx, rangeID, reader)
> 		select {
> 		case <-shouldQuiesce:
> ```

Why do you need this? Were you seeing hangs? `tryEnactTruncations` should also be sensitive to quiescence so this seems superfluous.
___
*[pkg/kv/kvserver/raft_log_truncator.go, line 443 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76902#-MwbWbPLC-9yxjWdhRnN:-MwbWbPLC-9yxjWdhRnO:bmgw6h7) ([raw file](https://github.com/cockroachdb/cockroach/blob/13456187352fca48914767f737a617a3b723682b/pkg/kv/kvserver/raft_log_truncator.go#L443)):*
> ```Go
> 		}
> 	}
> 	t.mu.Lock()
> ```

This part would go away with my other suggestion.

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76902#-:-MwbnqlZ9zzzt2KHydpp:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvserver/raft_log_truncator.go, line 394 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76902#-MwbUe3L3XXXi0ezd4Pq:-MwbmCTM4sPyNiZPo6X5:bi949pr) ([raw file](https://github.com/cockroachdb/cockroach/blob/13456187352fca48914767f737a617a3b723682b/pkg/kv/kvserver/raft_log_truncator.go#L394)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Consider pulling the `t.mu.runningTruncation = false` out. It is nice to have it all in one place.

Near the top of the method:

```
runTruncation := false
done := func() {}

t.mu.Lock()
[...]
  runTruncation = true
  t.mu.runningTruncation = true
  done := func() {
    t.mu.Lock()
    if !t.mu.runningTruncation { panic("...") }
    t.mu.runningTruncation = false
    t.mu.Unlock()
  }

[...]

for runTruncation {
  if err := t.stopper.RunAsyncTask(...., func(ctx context.Context) {
    defer done()
    for {
      t.durabilityAdvanced(ctx)
      t.mu.Lock()
      queued := t.mu.queuedDurabilityCB
      t.mu.queuedDurabilityCB = false
      t.mu.Unlock()
      if !queued { return }
    }
  }); err != nil {
    done()
    return
  }
  
}
```

That way `runningTruncation` is only accessed in this method.
</blockquote></details>

Much better! Done.
___
*[pkg/kv/kvserver/raft_log_truncator.go, line 435 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76902#-MwbWX8A9QsVQ_KDVX1_:-MwbmO_BAs0nLXio5LpD:b23lhls) ([raw file](https://github.com/cockroachdb/cockroach/blob/13456187352fca48914767f737a617a3b723682b/pkg/kv/kvserver/raft_log_truncator.go#L435)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Why do you need this? Were you seeing hangs? `tryEnactTruncations` should also be sensitive to quiescence so this seems superfluous.
</blockquote></details>

I saw a test fail with a `pebble.tableCacheShard` leak, which suggests the test shutdown without waiting for this goroutine that was holding open a `pebble.Iterator`. It seemed wise to not have stray goroutines that are not linked to a stopper, hence the stopper plumbing.

This particular change to check `shouldQuiesce` was just to play nice -- my reading of the stopper contract was that it waits for all such async tasks after closing this channel. So may as well check after processing each range.
___
*[pkg/kv/kvserver/raft_log_truncator.go, line 443 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76902#-MwbWbPLC-9yxjWdhRnN:-MwbnYG2DLAkVzEqgIm8:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/13456187352fca48914767f737a617a3b723682b/pkg/kv/kvserver/raft_log_truncator.go#L443)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This part would go away with my other suggestion.
</blockquote></details>

Done

**Review by tbg — APPROVED** [review]
> Reviewed 10 of 13 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76902)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/kv/kvserver/raft_log_truncator.go, line 435 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76902#-MwbWX8A9QsVQ_KDVX1_:-Mwf7hu_5w9oJqSgKDiU:b-cso4g3) ([raw file](https://github.com/cockroachdb/cockroach/blob/13456187352fca48914767f737a617a3b723682b/pkg/kv/kvserver/raft_log_truncator.go#L435)):*
> hence the stopper plumbing.

Sorry, that wasn't the question. Was just asking about checking quiescing here. It doesn't seem necessary, since this won't block shutdown. Mild preference for removal to keep the code clean.
___
*[pkg/kv/kvserver/testdata/raft_log_truncator, line 405 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76902#-Mwf83SDEXT_VFonK45z:-Mwf83SDEXT_VFonK46-:ba8mdf3) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0095c52a1fe86b1fda331cf557bb975c6057542/pkg/kv/kvserver/testdata/raft_log_truncator#L405)):*
> ```
> # Test case to ensure that truncator is reading only flushed engine state when
> # deciding to enact truncations.
> create-replica id=3 trunc-index=20 last-log-entry=30
> ```

It's odd to see `last-log-entry` but then the log ends at `29`. I think this should be `last-log-entry=29` (i.e. make it inclusive).
___
*[pkg/kv/kvserver/testdata/raft_log_truncator, line 438 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76902#-Mwf8qgBAT0emsjcZ_qg:-Mwf8qgC1L8oHv1eahRw:b-xrna98) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0095c52a1fe86b1fda331cf557bb975c6057542/pkg/kv/kvserver/testdata/raft_log_truncator#L438)):*
> ```
> # Move RaftAppliedState enough to allow first truncation, but don't flush that
> # change.
> write-raft-applied-index id=3 raft-applied-index=22 no-flush=true
> ```

What ensures that a flush doesn't accidentally happen?

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76902)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvserver/raft_log_truncator.go, line 435 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76902#-MwbWX8A9QsVQ_KDVX1_:-MwgBsjk7F4v2YDp776-:b8g7u3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/13456187352fca48914767f737a617a3b723682b/pkg/kv/kvserver/raft_log_truncator.go#L435)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

> hence the stopper plumbing.

Sorry, that wasn't the question. Was just asking about checking quiescing here. It doesn't seem necessary, since this won't block shutdown. Mild preference for removal to keep the code clean.
</blockquote></details>

I've left the code in place and added
```
		// Check if the stopper is quiescing. This isn't strictly necessary, but
		// if there are a huge number of ranges that need to be truncated, this
		// will cause us to stop faster.
```
___
*[pkg/kv/kvserver/testdata/raft_log_truncator, line 405 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76902#-Mwf83SDEXT_VFonK45z:-MwgCMGo19CkrzSaxwSc:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0095c52a1fe86b1fda331cf557bb975c6057542/pkg/kv/kvserver/testdata/raft_log_truncator#L405)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

It's odd to see `last-log-entry` but then the log ends at `29`. I think this should be `last-log-entry=29` (i.e. make it inclusive).
</blockquote></details>

Done
___
*[pkg/kv/kvserver/testdata/raft_log_truncator, line 438 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76902#-Mwf8qgBAT0emsjcZ_qg:-MwgCdT-CvF8rcJ29RvP:b-e8m5zm) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0095c52a1fe86b1fda331cf557bb975c6057542/pkg/kv/kvserver/testdata/raft_log_truncator#L438)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

What ensures that a flush doesn't accidentally happen?
</blockquote></details>

The initial memtable size is 256KB, and doubles for each new memtable. Even that initial size is much larger than anything we do in this test between explicit flushes.

I've added a comment to the test
```
				// The initial engine memtable size is 256KB, and doubles for each new
				// memtable. Even the initial size is much larger than anything we do
				// in this test between explicit flushes. Hence we can rely on the
				// fact that no-flush will actually be respected, and we won't
				// encounter an unexpected flush.
```

**Comment by sumeerbhola** [comment]
bors r=tbg

**Comment by sumeerbhola** [comment]
bors r=tbg

**Pull request merged**
