### PR TITLE
sqlsmith: add hint for ping failures and stop marking failures as release blockers

### PR DESCRIPTION
**Pull request by mgartner**
#### sqlsmith: add hint for ping failures

Release note: None

#### sqlsmith: failures are no longer release blockers

Release note: None

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm: Thanks!

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83297#-:-N5Gy8mlCq_qcrH6s_7U:b-g2a5fb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[`pkg/cmd/roachtest/tests/sqlsmith.go` line 285 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83297#-N5Gxq1z2ur8MRah5lCo:-N5Gxq1z2ur8MRah5lCp:b-7k9r0i) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7487e2183ebe48c97635a2502459b1b93ffe3ff/pkg/cmd/roachtest/tests/sqlsmith.go#L285)):*
> ```Go
> 					logStmt(stmt)
> 					nodeID := idx + 1
> 					errStr := fmt.Sprintf("ping node %d: %v\n", nodeID, err)
> ```

nit: do we want `\n` at the end of the line here and below given that we use `WriteString`? I'm guessing we will have an empty line, maybe that's ok though.

**Review by rharding6373 — APPROVED** [review]
:lgtm: This will be helpful.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83297#-:-N5H6azs62_plHoY5o25:b-3j3jsc)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by mgartner** [comment]
*[`pkg/cmd/roachtest/tests/sqlsmith.go` line 285 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83297#-N5Gxq1z2ur8MRah5lCo:-N5HC2165BK_8mytJDBo:b7sf6qq) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7487e2183ebe48c97635a2502459b1b93ffe3ff/pkg/cmd/roachtest/tests/sqlsmith.go#L285)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: do we want `\n` at the end of the line here and below given that we use `WriteString`? I'm guessing we will have an empty line, maybe that's ok though.
</blockquote></details>

I'm not sure I follow. WriteString doesn't add newlines afaik.

**Review by yuzefovich — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83297)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/cmd/roachtest/tests/sqlsmith.go` line 285 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83297#-N5Gxq1z2ur8MRah5lCo:-N5HDGBN7ICCwkG1ucAM:b6j2afh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7487e2183ebe48c97635a2502459b1b93ffe3ff/pkg/cmd/roachtest/tests/sqlsmith.go#L285)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I'm not sure I follow. WriteString doesn't add newlines afaik.
</blockquote></details>

Indeed, you're right - not sure why I assumed it did.

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
