### PR TITLE
roachtest: update sqlalchemy blacklist

### LINKED ISSUE #41797: roachtest: sqlalchemy failed
SHA: https://github.com/cockroachdb/cockroach/commits/724ed4fdf1ceb98fe5eb469480ce57cc2ba4d46c

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=sqlalchemy PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1551263&tab=artifacts#/sqlalchemy

```
The test failed on branch=release-19.1, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/20191022-1551263/sqlalchemy/run_1
	orm_helpers.go:174,orm_helpers.go:111,sqlalchemy.go:201,sqlalchemy.go:210,test_runner.go:689: 
		Tests run on Cockroach v19.1.5-40-g724ed4f
		Tests run against sqlalchemy rel_1_3_10
		207 Total Tests Run
		135 tests passed
		72 tests failed
		57 tests skipped
		1 test ignored
		3 tests passed unexpectedly
		0 tests failed unexpectedly
		0 tests expected failed but skipped
		0 tests expected failed but not run
		For a full summary look at the sqlalchemy artifacts 
		
		An updated blacklist (sqlAlchemyBlacklist) is available in the artifacts' sqlalchemy log

```

### PR DESCRIPTION
**Pull request by solongordon**
A few of the SQLAlchemy tests started passing due to a fix on the
cockroachdb-python side. I updated the blacklist to reflect this.

Fixes #41797

Release note: None

### CODE REVIEW

**Review by arulajmani — COMMENTED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41811#-:-LroP4sW91iKGO_o5K8n:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

**Review by rafiss — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41811)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
I'm also seeing this `3 tests passed unexpectedly` on `v19.2.0-rc.2`, so please backport this commit as well (and I will ask you to sign off on those unexpected successes).

**Comment by solongordon** [comment]
@yuzefovich I think a backport is unnecessary because roachtests always use master, even when running against older versions. This test doesn't even exist on the release-19.2 branch.

**Pull request merged**
