### PR TITLE
storage: Splits get write locks on the entire span

### LINKED ISSUE #14881: storage: TestUnsplittableRange failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/bc79f9e2bb0d3d99bb79b99d20aa02e0c33e38fe

Parameters:
```
COCKROACH_PROPOSER_EVALUATED_KV=true
TAGS=
GOFLAGS=
```

Stress build found a failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=219687&tab=buildLog

```
I170413 06:35:36.562832 39569 gossip/gossip.go:307  [n1] NodeDescriptor set to node_id:1 address:<network_field:"" address_field:"" > attrs:<> locality:<> 
I170413 06:35:36.563990 39569 storage/store.go:1256  [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
I170413 06:35:36.565041 39593 storage/split_queue.go:92  [split,s1,r1/1:/M{in-ax},@c420294300] splitting at key /System/""
I170413 06:35:36.565665 39593 storage/replica_command.go:2608  [split,s1,r1/1:/M{in-ax},@c420294300] initiating a split of this range at key /System/"" [r2]
I170413 06:35:36.569435 39569 storage/split_queue.go:92  [split,s1,r2/1:/{System/""-Max},@c420294600] splitting at key /System/tsd
I170413 06:35:36.569498 39569 storage/replica_command.go:2608  [split,s1,r2/1:/{System/""-Max},@c420294600] initiating a split of this range at key /System/tsd [r3]
W170413 06:35:36.571488 39569 storage/stores.go:218  range not contained in one range: [/Meta2/System/tsd,/System/tsd/NULL), but have [/Min,/System/"")
I170413 06:35:36.573452 39593 storage/split_queue.go:92  [split,s1,r3/1:/{System/tsd-Max},@c420c84c00] splitting at key /System/"tse"
I170413 06:35:36.573476 39593 storage/replica_command.go:2608  [split,s1,r3/1:/{System/tsd-Max},@c420c84c00] initiating a split of this range at key /System/"tse" [r4]
I170413 06:35:36.576925 39593 storage/split_queue.go:92  [split,s1,r4/1:/{System/"tse"-Max},@c4200a4f00] splitting at key /Table/0/0
I170413 06:35:36.576949 39593 storage/replica_command.go:2608  [split,s1,r4/1:/{System/"tse"-Max},@c4200a4f00] initiating a split of this range at key /Table/0 [r5]
I170413 06:35:36.579906 39593 storage/split_queue.go:92  [split,s1,r5/1:/{Table/0-Max},@c4201a4f00] splitting at key /Table/11/0
I170413 06:35:36.579932 39593 storage/replica_command.go:2608  [split,s1,r5/1:/{Table/0-Max},@c4201a4f00] initiating a split of this range at key /Table/11 [r6]
I170413 06:35:36.586923 39593 storage/split_queue.go:92  [split,s1,r6/1:/{Table/11-Max},@c420c0af00] splitting at key /Table/12/0
I170413 06:35:36.586950 39593 storage/replica_command.go:2608  [split,s1,r6/1:/{Table/11-Max},@c420c0af00] initiating a split of this range at key /Table/12 [r7]
I170413 06:35:36.591008 39593 storage/split_queue.go:92  [split,s1,r7/1:/{Table/12-Max},@c4200a5b00] splitting at key /Table/13/0
I170413 06:35:36.591032 39593 storage/replica_command.go:2608  [split,s1,r7/1:/{Table/12-Max},@c4200a5b00] initiating a split of this range at key /Table/13 [r8]
I170413 06:35:36.594101 39593 storage/split_queue.go:92  [split,s1,r8/1:/{Table/13-Max},@c420a8ac00] splitting at key /Table/14/0
I170413 06:35:36.594130 39593 storage/replica_command.go:2608  [split,s1,r8/1:/{Table/13-Max},@c420a8ac00] initiating a split of this range at key /Table/14 [r9]
	soon.go:43: storage/client_split_test.go:2005, condition failed to evaluate within 45s: expected max-bytes to be changed: 65536
```

### PR DESCRIPTION
**Pull request by bdarnell**
This was meant to go in as a part of #14833.
De-flakes TestUnsplittableRange.

Fixes #14881

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14992#-:-Khx8H598pVSBJ7AtQFK:bnfp4nl)*

**Comment by tamird** [comment]
Might be good to test more directly, though.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14992#-:-Khx8HjAukyHb4jivE17:baxc2t7)*

**Review by a-robinson — APPROVED** [review]
I can confirm that this removes the flake.

**Comment by bdarnell** [comment]
Added a unit test.

**Comment by tamird** [comment]
I was thinking we'd test it at a higher level, specifically inducing the troublesome race. I'm OK with this, too.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14992#-:-KhxIKcpmuvvivKFMdvw:b-nry7tp)*

**Comment by bdarnell** [comment]
A higher-level test for this would be tricky to write, because we don't have any hooks in place to detect when the Put has been blocked by the command queue.

**Comment by nvanbenschoten** [comment]
@bdarnell I was thinking about this in relation to https://github.com/cockroachdb/cockroach/issues/16075#issuecomment-303408116 and it's pretty unfortunate that splits need to declare write locks on their left and right-hand sides. Naively I would expect that a read lock would be sufficient to block all writes on the range that may concurrently mess with the stats, but I assume we're running into issues with https://github.com/cockroachdb/cockroach/pull/14342 (writes in the future affecting the stats). If that is, in fact, the issue, we might consider adjusting the perceived timestamp of the split in the eyes of the `CommandQueue` so that even a read lock will block all concurrent writes while still permitting concurrent reads.

**Comment by bdarnell** [comment]
You mean putting the split in the command queue as a read at the maximum possible timestamp, but still using its real timestamp for the timestamp cache when the operation completes? I think that would work, although it feels hacky. In that case then reads to the LHS would be uninterrupted, and reads to the RHS would be allowed except for the ones in flight as the split occurs (since they would no longer be addressed to the correct range).

**Comment by nvanbenschoten** [comment]
> I think that would work, although it feels hacky.

In one sense, I agree, but it also seems logically consistent to say that the operation on the LHS is a read that needs to depend on all writes and therefore operates at the maximum timestamp. Do we have any notion of this to deal with inline values?

I may also be blowing this out of proportion, but it seems like blocking all reads to a range during splits as serious enough to warrant some special logic.

> and reads to the RHS would be allowed except for the ones in flight as the split occurs (since they would no longer be addressed to the correct range)

How is that handled now? Are reads to the RHS which are waiting in the cmdQueue during the split all rejected with a `RangeKeyMismatchError` after the split finishes and they're allowed to execute? In that case, we'd probably need to keep the declared keys for the RHS as writes.

**Comment by bdarnell** [comment]
> In one sense, I agree, but it also seems logically consistent to say that the operation on the LHS is a read that needs to depend on all writes and therefore operates at the maximum timestamp.

Reads always depend on all writes in their past; it's weird for a read to depend on writes in its future. 

> Do we have any notion of this to deal with inline values?

Currently, we apply the command's timestamp to all of the keys it touches, even if they have inline values.

> How is that handled now? Are reads to the RHS which are waiting in the cmdQueue during the split all rejected with a RangeKeyMismatchError after the split finishes and they're allowed to execute? In that case, we'd probably need to keep the declared keys for the RHS as writes.

Yes, exactly. We *might* be able to allow the RHS reads through as long as everything is properly synchronized, so that there is a smaller window of disruption. I don't think that's safe today, though.

**Comment by nvanbenschoten** [comment]
@bdarnell In the process of reworking the CommandQueue, I noticed that the logic from https://github.com/cockroachdb/cockroach/pull/14342 is disabled when a command enters the CommandQueue with an empty timestamp. This means that we could simply pass an empty timestamp and avoid the "maximum possible timestamp" hack we were discussing above. Once we do that, we can declare a read span for the entire range and allow concurrent reads to go through (although the locking on the RHS might be tricky). Think it's worth pursuing this?

**Comment by bdarnell** [comment]
That sounds plausible. The question is just whether that behavior is something we want to commit to in the command queue - when, aside from this trick, would we ever have both timestamped and untimestamped access to the same keys?

**Comment by nvanbenschoten** [comment]
> The question is just whether that behavior is something we want to commit to in the command queue

It's actually something we're already committed to and I think it makes sense. We already do exactly this for locally-scoped keys. Providing an empty timestamp to the command queue is basically a way of saying "don't treat this as an MVCC operation".

> would we ever have both timestamped and untimestamped access to the same keys?

Currently, I don't believe so. It doesn't seem like a big leap to me though.

**Pull request merged**
