### PR TITLE
bazel: allow using locally-installed `node` on freebsd

### LINKED ISSUE #74208: bazel: yarn download error on freebsd upon `dev build cockroach`
**Describe the problem**

```
kena@kenax ....com/cockroachdb/cockroach %  ./dev build cockroach
TMPDIR set to /tmp/tmp.pt7YeG66
$ bazel build //pkg/cmd/cockroach:cockroach --config=with_ui
INFO: Build option --define has changed, discarding analysis cache.
INFO: Repository npm instantiated at:
  /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/WORKSPACE:177:13: in <toplevel>
  /data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/build_bazel_rules_nodejs/index.bzl:83:18: in yarn_install
Repository rule yarn_install defined at:
  /data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:917:31: in <toplevel>
ERROR: An error occurred during the fetch of repository 'npm':
   Traceback (most recent call last):
        File "/data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 813, column 36, in _yarn_install_impl
                is_windows_host = is_windows_os(repository_ctx)
        File "/data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/build_bazel_rules_nodejs/nodejs/private/os_name.bzl", line 65, column 19, in is_windows_os
                return os_name(rctx) == OS_NAMES[0]
        File "/data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/build_bazel_rules_nodejs/nodejs/private/os_name.bzl", line 62, column 9, in os_name
                fail("Unsupported operating system {} architecture {}".format(os_name, arch))
Error in fail: Unsupported operating system freebsd architecture amd64
```

**To Reproduce**

freebsd 13, run the command above

**Expected behavior**

Either:
- the thing works as-is, or
- there's some information in a README file about how to tell the tool to use a locally-installed yarn

(NB: `make build` works)

Epic CRDB-8036

Jira issue: CRDB-11971

### PR DESCRIPTION
**Pull request by rickystewart**
* Pull in a patch to [rules_nodejs](https://github.com/cockroachdb/rules_nodejs/commit/59a92ccbcd2f5c40cf2368bbb9f7b102491f537b) to support FreeBSD.
* Add a new `toolchain` pointing to the locally-installed `node` which
  is compatible with FreeBSD.

Closes #74208.

Release note: None

### CODE REVIEW

**Comment by rickystewart** [comment]
@knz Can you try this patch out (work through the new `dev doctor` checks and try `dev build` on FreeBSD)? I suspect it should work but wasn't able to try everything end-to-end.

**Comment by knz** [comment]
thanks for the heads up! 

here what I get now:

```
INFO: Build option --//pkg/ui:with_ui_flag has changed, discarding analysis cache.
INFO: Repository npm_db_console instantiated at:
  /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/WORKSPACE:256:13: in <toplevel>
  /data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/build_bazel_rules_nodejs/index.bzl:83:18: in yarn_install
Repository rule yarn_install defined at:
  /data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:977:31: in <toplevel>
ERROR: An error occurred during the fetch of repository 'npm_db_console':
   Traceback (most recent call last):
        File "/data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 827, column 36, in _yarn_install_impl
                is_windows_host = is_windows_os(repository_ctx)
        File "/data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/rules_nodejs/nodejs/private/os_name.bzl", line 65, column 19, in is_windows_os
                return os_name(rctx) == OS_NAMES[0]
        File "/data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/rules_nodejs/nodejs/private/os_name.bzl", line 62, column 9, in os_name
                fail("Unsupported operating system {} architecture {}".format(os_name, arch))
Error in fail: Unsupported operating system freebsd architecture amd64
ERROR: /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/WORKSPACE:256:13: fetching yarn_install rule //external:npm_db_console: Traceback (most recent call last):
        File "/data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 827, column 36, in _yarn_install_impl
                is_windows_host = is_windows_os(repository_ctx)
        File "/data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/rules_nodejs/nodejs/private/os_name.bzl", line 65, column 19, in is_windows_os
                return os_name(rctx) == OS_NAMES[0]
        File "/data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/rules_nodejs/nodejs/private/os_name.bzl", line 62, column 9, in os_name
                fail("Unsupported operating system {} architecture {}".format(os_name, arch))
Error in fail: Unsupported operating system freebsd architecture amd64
ERROR: /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/ui/distccl/BUILD.bazel:3:8: //pkg/ui/distccl:genassets depends on //pkg/ui/workspaces/db-console:db-console-ccl in repository @ which failed to fetch. no such package '@npm_db_console//typescript': Unsupported operating system freebsd architecture amd64
ERROR: Analysis of target '//pkg/cmd/cockroach:cockroach' failed; build aborted:
INFO: Elapsed time: 27.693s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (442 packages loaded, 22737 targets configured)
    currently loading: pkg/ui/workspaces/db-console
ERROR: exit status 1
```

So maybe it's able to pick up `node`, but we should teach it to pick up system-wide `yarn` as well.

**Comment by knz** [comment]
(as mentioned in issue #74208 we want all 3 of `node`, `yarn` and `npm` to be picked up from the system-wide install without download)

**Comment by rickystewart** [comment]
I made a small change, let me know if the build works with the latest version.

> (as mentioned in issue https://github.com/cockroachdb/cockroach/issues/74208 we want all 3 of node, yarn and npm to be picked up from the system-wide install without download)

This is not how this is implemented -- the globally installed `node` will be used, but `yarn` is not platform-specific and will be downloaded

**Review by knz — COMMENTED** [review]
there's progress now!

```
ERROR: An error occurred during the fetch of repository 'npm_db_console':
   Traceback (most recent call last):
        File "/data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 971, column 32, in _yarn_
install_impl
                _apply_post_install_patches(repository_ctx)
        File "/data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 377, column 19, in _apply
_post_install_patches
                _apply_patches(repository_ctx, working_directory, repository_ctx.attr.post_install_patches, marker_file)
        File "/data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 435, column 21, in _apply
_patches
                fail("Error applying patch %s in %s:\n%s%s" % (str(patch_file), working_directory, st.stderr, st.stdout))
Error in fail: Error applying patch //pkg/ui:patches/aria-query/remove-filenames-with-spaces.db-console.patch in /data/home/kena/src/go/src/github.com/cockroachdb/cockroach:
File to patch:
No file found--skip this patch? [y]
1 out of 1 hunks ignored--saving rejects to Oops.rej
...
No file found--skip this patch? [y]
1 out of 1 hunks ignored--saving rejects to Oops.rej
File to patch:
No file found--skip this patch? [y]
1 out of 1 hunks ignored--saving rejects to Oops.rej
ERROR: Analysis of target '//pkg/cmd/cockroach:cockroach' failed; build aborted:
```

FWIW, I symlinked `patch` as instructed and `patch --version` returns 2.7.6.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82762#-:-N4Th2usEFkoDT4J4xtY:b-mn9jig)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rickystewart)

**Comment by rickystewart** [comment]
@knz That error looks odd to me, can you run with the Bazel flag `'--toolchain_resolution_debug=.*'` and paste the full output?

**Comment by knz** [comment]
I get the following

```
% bazel build //pkg/cmd/cockroach:cockroach --config=with_ui  --toolchain_resolution_debug='.*'
INFO: Invocation ID: 7e371d82-6850-40a4-a7be-d5c8b079b08d
ERROR: /data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/npm_db_console/webpack-cli/bin/BUILD.bazel:9:14: While resolving toolchains for target @npm_db_console//webpack-cli/bin:webpack-cli: no matching toolchains found for types @rules_nodejs//nodejs:toolchain_type
ERROR: Analysis of target '//pkg/cmd/cockroach:cockroach' failed; build aborted:
INFO: Elapsed time: 4.878s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (3 packages loaded, 0 targets configured)
    currently loading: @npm_db_console//
```

**Review by knz — COMMENTED** [review]
With the latest change, there's progress!



> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82762#-:-N4Tlb8N0G0WcyiDzmcs:b-8rn6s5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rickystewart)

**Comment by knz** [comment]
okay but there's something not clean yet:

If I run `dev ui clean --all`, then `dev build`, I run into the `patch` error above again.

I have to run `dev build` and let it fail 2 times, first, 

then at the 3rd time it's able to make progress and finish the build.

**Comment by rickystewart** [comment]
@knz Not sure what's going on with that, I'll pull Sean into the discussion in Slack.

**Comment by knz** [comment]
I'm going to apply Sean's suggestion:

> wanna give that a try on your machine since patch is still borked for you?  Should be as easy as find $moduleDir -name '* *' -delete at the end of seed_yarn_cache.sh

**Comment by knz** [comment]
I did this:

- removed the two patch specs in the top level WORKSPACE
- added the `find ... -delete` in the shell script

as a result I observe **once**:

```
$ bazel build //pkg/cmd/cockroach:cockroach --config=with_ui
INFO: Invocation ID: 345544b4-928f-4b8a-9752-b2130c8914ba
INFO: Analyzed target //pkg/cmd/cockroach:cockroach (312 packages loaded, 10816 targets configured).
INFO: Found 1 target...
ERROR: /data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/npm_cluster_ui/BUILD.bazel:9021:10: Copying directory external/npm_cluster_ui/_/pkg/ui/workspaces/cluster-ui/node_modules/des.js failed: missing input file 'external/npm_cluster_ui/_/pkg/ui/workspaces/cluster-ui/node_modules/des.js', owner: '@npm_cluster_ui//:_/pkg/ui/workspaces/cluster-ui/node_modules/des.js'
ERROR: /data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/npm_cluster_ui/BUILD.bazel:20573:10: Copying directory external/npm_cluster_ui/_/pkg/ui/workspaces/cluster-ui/node_modules/sha.js failed: missing input file 'external/npm_cluster_ui/_/pkg/ui/workspaces/cluster-ui/node_modules/sha.js', owner: '@npm_cluster_ui//:_/pkg/ui/workspaces/cluster-ui/node_modules/sha.js'
ERROR: /data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/npm_cluster_ui/BUILD.bazel:15405:10: Copying directory external/npm_cluster_ui/_/pkg/ui/workspaces/cluster-ui/node_modules/md5.js failed: missing input file 'external/npm_cluster_ui/_/pkg/ui/workspaces/cluster-ui/node_modules/md5.js', owner: '@npm_cluster_ui//:_/pkg/ui/workspaces/cluster-ui/node_modules/md5.js'
ERROR: /data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/npm_cluster_ui/BUILD.bazel:6637:10: Copying directory external/npm_cluster_ui/_/pkg/ui/workspaces/cluster-ui/node_modules/big.js failed: missing input file 'external/npm_cluster_ui/_/pkg/ui/workspaces/cluster-ui/node_modules/big.js', owner: '@npm_cluster_ui//:_/pkg/ui/workspaces/cluster-ui/node_modules/big.js'
ERROR: /data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/npm_cluster_ui/BUILD.bazel:15405:10: Copying directory external/npm_cluster_ui/_/pkg/ui/workspaces/cluster-ui/node_modules/md5.js failed: 1 input file(s) do not exist
ERROR: /data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/npm_cluster_ui/BUILD.bazel:20573:10: Copying directory external/npm_cluster_ui/_/pkg/ui/workspaces/cluster-ui/node_modules/sha.js failed: 1 input file(s) do not exist
ERROR: /data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/npm_cluster_ui/BUILD.bazel:9021:10: Copying directory external/npm_cluster_ui/_/pkg/ui/workspaces/cluster-ui/node_modules/des.js failed: 1 input file(s) do not exist
ERROR: /data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/npm_cluster_ui/BUILD.bazel:6669:10: Copying directory external/npm_cluster_ui/_/pkg/ui/workspaces/cluster-ui/node_modules/bn.js failed: missing input file 'external/npm_cluster_ui/_/pkg/ui/workspaces/cluster-ui/node_modules/bn.js', owner: '@npm_cluster_ui//:_/pkg/ui/workspaces/cluster-ui/node_modules/bn.js'
ERROR: /data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/npm_cluster_ui/BUILD.bazel:6637:10: Copying directory external/npm_cluster_ui/_/pkg/ui/workspaces/cluster-ui/node_modules/big.js failed: 1 input file(s) do not exist
Target //pkg/cmd/cockroach:cockroach failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/npm_cluster_ui/BUILD.bazel:15405:10 Copying directory external/npm_cluster_ui/_/pkg/ui/workspaces/cluster-ui/node_modules/md5.js failed: 1 input file(s) do not exist
INFO: Elapsed time: 65.084s, Critical Path: 0.20s
INFO: 38 processes: 26 internal, 12 local.
FAILED: Build did NOT complete successfully
```

but then if I run `dev build` again it completes without error.

(For certainty, I have run `dev ui clean --all` then `dev build` again. Same thing: it fails once, then succeeds.)

**Comment by knz** [comment]
I have another idea. lemme try this too

**Review by knz — COMMENTED** [review]
I have used the following command in the script instead:

```
find $moduleDir/node_modules/aria-query -name '* *' -delete || true
```

This improves the situation, but not yet 100%. I then get the follwoing error (still, **only once** - the 2nd time there's no error and the command succeeds)

```
ERROR: /data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/npm_cluster_ui/BUILD.bazel:9789:10: Copying directory external/npm_cluster_ui/_/pkg/ui/workspaces/cluster-ui/node_modules/enquire.js failed: missing input file 'external/npm_cluster_ui/_/pkg/ui/workspaces/cluster-ui/node_modules/enquire.js', owner: '@npm_cluster_ui//:_/pkg/ui/workspaces/cluster-ui/node_modules/enquire.js'
ERROR: /data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/npm_cluster_ui/BUILD.bazel:9789:10: Copying directory external/npm_cluster_ui/_/pkg/ui/workspaces/cluster-ui/node_modules/enquire.js failed: 1 input file(s) do not exist
ERROR: /data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/npm_cluster_ui/BUILD.bazel:16765:10: Copying directory external/npm_cluster_ui/_/pkg/ui/workspaces/cluster-ui/node_modules/omit.js failed: missing input file 'external/npm_cluster_ui/_/pkg/ui/workspaces/cluster-ui/node_modules/omit.js', owner: '@npm_cluster_ui//:_/pkg/ui/workspaces/cluster-ui/node_modules/omit.js'
Target //pkg/cmd/cockroach:cockroach failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/npm_cluster_ui/BUILD.bazel:9789:10 Copying directory external/npm_cluster_ui/_/pkg/ui/workspaces/cluster-ui/node_modules/enquire.js failed: 1 input file(s) do not exist
INFO: Elapsed time: 59.211s, Critical Path: 0.07s
INFO: 110 processes: 30 internal, 80 local.
FAILED: Build did NOT complete successfully

```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82762#-:-N4Tq71TCCGXEDYeahhG:b-ubf3ow)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rickystewart)

**Review by knz — APPROVED** [review]
based on the convo with @sjbarag the remaining issue is not related to this fix. So the PR as is is very much acceptable as a solution to the original issue. Thanks!

:lgtm_strong:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82762#-:-N4TxO79CApNXagJIpR2:b17tq5h)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rickystewart)

**Comment by knz** [comment]
I'll gladly be using this piece of functionality today, so going ahead and merging this. Thanks again

bors r+

**Pull request merged**
