### PR TITLE
sql: categorize index in middle of being added error

### PR DESCRIPTION
**Pull request by otan**
Release note: None

### CODE REVIEW

**Comment by otan** [comment]
this will be backported on approval

**Review by thoszhang — APPROVED** [review]
Thanks!

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55299#-:-MJ3Ef7kBBRIXxabj2V6:b-ucfknh)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by otan** [comment]
bors r=lucy-zhang

**Comment by otan** [comment]
bors r=lucy-zhang

**Pull request merged**
