### PR TITLE
kvserver: avoid engine bypass in sideload storage

### LINKED ISSUE #58948: kvserver: diskSideloadedStorage.TruncateTo can cause spurious errors
**Describe the problem**

We [saw](https://cockroachlabs.slack.com/archives/C0KB9Q03D/p1610484229007200) the following errors in logs during `make bench`:

```
E210112 19:54:19.158760 38559 kv/kvserver/queue.go:1087  [n2,raftlog,s2,r56/2:/Table/54/{2/"dataâ€¦-3}] recomputing raft log size: while purging "auxiliary/sideloading/r0XXXX/r56": file already exists
E210112 19:54:19.292477 38653 kv/kvserver/queue.go:1087  [n2,raftlog,s2,r56/2:/Table/54/{2/"dataâ€¦-3}] recomputing raft log size: while purging "auxiliary/sideloading/r0XXXX/r56": file already exists
E210112 19:54:19.691621 6955 kv/kvserver/replica_application_result.go:282  [n2,s2,r42/2:/{Table/54/3-Max}] while removing sideloaded files during log truncation: while purging "auxiliary/sideloading/r0XXXX/r42": file already exists
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*diskSideloadStorage).TruncateTo
  | 	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_sideload_disk.go:241
[...]
```

This indicates an error from `eng.RemoveDir` here:

https://github.com/cockroachdb/cockroach/blob/19951d2ad7a8eb3c20c38c6e55e1414549d1850f/pkg/kv/kvserver/replica_sideload_disk.go#L236-L243

The error message is misleading due to a bug in pebble that was fixed today. The error is really that the directory is not empty.

The code attempts to invoke `RemoveDir` only if it believes that it has deleted all files (there is no concurrent access to the directory here since access always happens under `raftMu`). However, this isn't true: note how

https://github.com/cockroachdb/cockroach/blob/19951d2ad7a8eb3c20c38c6e55e1414549d1850f/pkg/kv/kvserver/replica_sideload_disk.go#L247-L270

globs for files matching a pattern. Perhaps we are writing files that do not match this pattern in some cases. In that case, we could erroneously see no files (the raft log size case above passes `firstIndex==0` and so would definitely not try to delete the directory if any sideloaded SST was present)

However, the only other write to these directories that I am aware of is here:

https://github.com/cockroachdb/cockroach/blob/ef645191867f2ba4d80083f1dae0b9ba1b805277/pkg/kv/kvserver/replica_proposal.go#L509-L516

and it looks like it should be handled correctly (exactly like the file without the .ingested suffix).

**To Reproduce**

Run `BenchmarkUserfileImport` (presumably). If the error is reproducible, we should dump a listing of the directory with the error to understand what the unexpected file is.

**Expected behavior**

The sideloaded storage should have the full authority over the directory. No other files should be placed in it, and so this (harmless) error should not occur.

**Additional data / screenshots**

**Environment:**

**Additional context**

### PR DESCRIPTION
**Pull request by tbg**
While investigating #59126, I realized we were still going through the
engine for listing the files. I rectified this and as a result,
completely removed the in-mem implementation of the sideloaded storage
that we had in place: instead of it, we simply use an in-mem engine,
which now works like a charm thanks to not bypassing the engine for
listing the file contents (`filepath.Glob` --> `eng.List`).

While I was here, I added some defense in depth: it was unreasonable
that `TruncateTo` was returning an error as a result of failing to
perform best-effort cleanup on its directory.

I am no longer seeing the spurious errors observed in #59126 with
this change.

Touches #59126.
Touches #31913.
Fixes #58948.

Release note: None

### CODE REVIEW

**Review by jbowens — APPROVED** [review]
:LGTM:

Thanks for fixing that! Looks like I missed the Glob in #49717!

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59134#-:-MRQ8305AE73E81HDOSp:bkiex25)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by tbg** [comment]
Thanks for the review!

bors r=jbowens

**Comment by tbg** [comment]
bors r=jbowens

**Comment by tbg** [comment]
Can't merge because

> [Prepare environment] curl: (22) The requested URL returned error: 503 Service Unavailable: Back-end server is at capacity

**Comment by tbg** [comment]
bors r=jbowens

**Pull request merged**
