### PR TITLE
sql: cleanup tests by using sqlbase.GetTableDescriptor()

### PR DESCRIPTION
**Pull request by vivekmenezes**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6995)

### CODE REVIEW

**Comment by vivekmenezes** [comment]
@andreimatei this is just a refactor change and I'd like to merge it before rebasing the other review I have pending with you. Thanks

**Comment by andreimatei** [comment]
this function already exists
https://github.com/cockroachdb/cockroach/blob/962b759c2085f8a82a86ec96ade35ea984095616/sql/sqlbase/testutils.go#L35

<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> @andreimatei this is just a refactor change and I'd like to merge it before rebasing the other review I have pending with you. Thanks
</details>


---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6995#-:-KJM8zMV7oL5YSVh4oRj:996054160)*

**Comment by vivekmenezes** [comment]
This is ready for another look. Thank for pointing out the existing function.

<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> this function already exists
> https://github.com/cockroachdb/cockroach/blob/962b759c2085f8a82a86ec96ade35ea984095616/sql/sqlbase/testutils.go#L35
</details>


---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6995#-:-KJa2RtjxnAY101kfFdp:804214376)*

**Comment by andreimatei** [comment]
:lgtm:

http://img.memecdn.com/clean-up_o_882443.jpg

<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> This is ready for another look. Thank for pointing out the existing function.
</details>


---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6995#-:-KJka0FOhSR5vxks_vT-:1254606201)*

**Pull request merged**
