### PR TITLE
sql: give LogicTest a chance to test more inputs before reporting an error

### PR DESCRIPTION
**Pull request by knz**
This gives us a chance to catch more failures between dev iterations.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6041)

### CODE REVIEW

**Comment by andreimatei** [comment]
How about we `Errorf` and then skip to the next file on first error in a file. Otherwise pretty much every line in a file will fail after the first.

**Comment by knz** [comment]
This is what this patch does, doesn't it?

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/logic_test.go, line 270 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6041#-KFFfwIJV9C2nkSMvORR:-KFFfwIJV9C2nkSMvORS:316186650) ([raw file](https://github.com/cockroachdb/cockroach/blob/6198b380a2509054e2635113a921a057dbff9320/sql/logic_test.go#L270)):*
why don't you make this function return an error? current approach seems fragile.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6041)*

**Comment by mjibson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/logic_test.go, line 270 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6041#-KFFfwIJV9C2nkSMvORR:-KFFgjigDhbdKpQJNOnx:-1683131809) ([raw file](https://github.com/cockroachdb/cockroach/blob/6198b380a2509054e2635113a921a057dbff9320/sql/logic_test.go#L270)):*
I agree. t was needed to call t.Fatal, but if that's going away an error may be enough.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6041)*

**Comment by knz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/logic_test.go, line 270 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6041#-KFFfwIJV9C2nkSMvORR:-KFFphAXoVQYJpSwjgXR:1333120123) ([raw file](https://github.com/cockroachdb/cockroach/blob/6198b380a2509054e2635113a921a057dbff9320/sql/logic_test.go#L270)):*
Thanks for the hint. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6041)*

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6041#-:-KFFwICKLNUvSOVkVzOQ:1417088721)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6041)*

**Pull request merged**
