### PR TITLE
sql: fix/enhance sql telemetry logging

### LINKED ISSUE #69653: sql: add effective sample rate field to the sampled query event
**Is your feature request related to a problem? Please describe.**
Currently, the sampled query event does not provide any means to determine its effective sample rate (i.e. it cannot be determined how often the event is emitted/sampled relative to how many queries are actually executed). Consequently, it is difficult to determine insight as to how the event is being represented in the log.

**Describe the solution you'd like**
A simple solution would be to add a counter to detect the number of events that have *not been emitted* since the *last emitted event*.
A value of 0 would indicate an effective sample rate of 1 (i.e. full representativity).
Values >0 would indicate an effective sample rate of: 1 / (number of not emitted events + 1)

**Additional context**
I have left `TODO(thardy98)` where code changes need to be made.

### PR DESCRIPTION
**Pull request by knz**
Fixes #69653.
This also fixes another problem that hadn't been filed as an issue.

Main changes:

- do not consider internal statements in sampling telemetry
- report the skipped query count in sampled query telemetry  (issue #69653)

### CODE REVIEW

**Comment by knz** [comment]
cc @thtruo: This will need a backport to 22.1 and a deployment to CC serverless. Do you want to expedite this? It will need the proper justification to the release team.

**Comment by thtruo** [comment]
Thank you @knz! 
> This will need a backport to 21.2 and a deployment to CC serverless. Do you want to expedite this? It will need the proper justification to the release team.
Yes please! We'd like to expedite this so it lands as soon as possible into the release branch that CC Serverless will test and ship with - sounds like your fix will result in much more useful logs when consuming downstream. We need that since the Serverless launch is happening in October!

**Review by maryliag — APPROVED** [review]
:lgtm: 
I can request an expedited approval for this today or I can request it on the release call Monday morning, what do you prefer?
If you want today I will need:
- Quick summary/impact:
-  Answer: Will this change prevent an upgrade from a beta build to the final release build? Will this change make the final release incompatible with beta releases? [Quick explanation if not covered by previous response]

From what I can see on the code, the answer to the second question is no, correct?

> Reviewed 1 of 3 files at r5, 6 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70346#-:-Mjo16B1A8HUxOvkhGUm:b-3ysciq)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

___
*[-- commits, line 1 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/70346#-Mjo2JfoAGzSVe_ijBgz):*
nit: can you squash this into a single commit?

**Review by knz — COMMENTED** [review]
> I can request an expedited approval for this today or I can request it on the release call Monday morning, what do you prefer?

It does not matter to me. You can hash this out with Tommy.

In the meantime, I'll issue the backport PR.

> Quick summary/impact: 

This change is necessary to get actionable telemetry on SQL query usage from the very first CC paid tier customers.

> Will this change prevent an upgrade from a beta build to the final release build? 

No.

> Will this change make the final release incompatible with beta releases?

No.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70346#-:-MjoAHjW7k_-nQylJoUp:b-h5fc0m)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag)

___
*[-- commits, line 1 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/70346#-Mjo2JfoAGzSVe_ijBgz):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: can you squash this into a single commit?
</blockquote></details>

I like the idea of 1 commit = 1 unit of reasoning.

**Comment by knz** [comment]
bors r=maryliag

**Comment by knz** [comment]
blathers backport 21.2

**Pull request merged**
