### PR TITLE
schemachanger: fix typos and style

### PR DESCRIPTION
**Pull request by postamar**
This commit makes only purely cosmetic changes in the schemachanger
package and its children.

Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm: :clap: 

> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72778#-:-Mo_6C_Y9QUt_tVpfV-c:bqao6p5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @postamar)

___
*[pkg/sql/schemachanger/rel/query_lang_expr.go, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72778#-Mo_69JoA83Hs7TjVw-T:-Mo_69Jp8xde1yJZ3Zqo:b-rhuq1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac36e9bfc70ea1e426df1079c3bc20d1bc06bf73/pkg/sql/schemachanger/rel/query_lang_expr.go#L24)):*
> ```Go
> // clauses and use variable names which are not part of the defined scope of
> // the rule, the new variableSlots which will be created will have a scope
> // prefix  to try to ensure that they are unique. Given that, don't put `:` in
> ```

nit: extra space

**Comment by postamar** [comment]
Thanks for the review! I removed the extra space.

bors r+

**Comment by postamar** [comment]
bors cancel

**Pull request merged**
