### PR TITLE
batcheval,bulk: move AddSSTable mvcc stats computation to caller

### PR DESCRIPTION
**Pull request by dt**
This allows a client to include the MVCCStats for the SST when sending
an AddSSTable request. If stats are included in a request, the receiving
store can use the stapled stats instead of computing them itself.

While this is still the same total amount of work, moving it to the
client can help when many clients are producing and sending SSTs to the
same range, which could then become a bottleneck.

Additioanlly, this paves the way to future optimization that could
actually reduce the total work done in some cases. While the server,
handed an arbitrary SST, has to assume that it can contain anything and
has to run the full recompute on it, in some cases, some clients may
potentially be able to make simplifying assumptions based on what they
are putting in their SST, and thus be able to compute or derive stats
more cheapy than running all of `ComputeStatsGo`. Giving the client the
option to pass its own stats provides this flexibility.

Release note: None.

### CODE REVIEW

**Review by nvb — APPROVED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36549)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/storage/batcheval/cmd_add_sstable.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36549#-LbeIyaB6V1zMLVKlN4S:-LbeIyaB6V1zMLVKlN4T:b4xaj2l) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe94913263aa1103c4e7c6f5567a61f06fc09cd3/pkg/storage/batcheval/cmd_add_sstable.go#L71)):*
> ```Go
> 	stats := args.MVCCStats
> 
> 	if stats.KeyCount == 0 {
> ```

I'm surprised you didn't make `args.MVCCStats` nullable and just base this decision off of that. Any reason for this approach?
___
*[pkg/storage/batcheval/cmd_add_sstable.go, line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36549#-LbeJhqRD8GYTQ1NMWjY:-LbeJhqRD8GYTQ1NMWjZ:bcn4d1y) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe94913263aa1103c4e7c6f5567a61f06fc09cd3/pkg/storage/batcheval/cmd_add_sstable.go#L86)):*
> ```Go
> 		return result.Result{}, err
> 	} else if ok {
> 		if unsafeKey := dataIter.UnsafeKey(); !unsafeKey.Less(mvccEndKey) {
> ```

Is `unsafeKey.Less(mvccEndKey)` possible after a `Seek`?

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36549)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @nvanbenschoten)

___
*[pkg/storage/batcheval/cmd_add_sstable.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36549#-LbeIyaB6V1zMLVKlN4S:-LbhtqZm4u1L5s8Xyvg6:bqgyc9f) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe94913263aa1103c4e7c6f5567a61f06fc09cd3/pkg/storage/batcheval/cmd_add_sstable.go#L71)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm surprised you didn't make `args.MVCCStats` nullable and just base this decision off of that. Any reason for this approach?
</blockquote></details>

Hm, not sure. For some reason I thought we just never liked nullable fields, even for optional message types? If that isn't true, I'd happily make this one nullable.

**Review by danhhz — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36549#-:-LbhuhBPD3Z9J3VPcl_5:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt and @nvanbenschoten)

___
*[pkg/storage/batcheval/cmd_add_sstable.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36549#-LbeIyaB6V1zMLVKlN4S:-Lbht0zuCNkLb9VkXPFD:bec3zto) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe94913263aa1103c4e7c6f5567a61f06fc09cd3/pkg/storage/batcheval/cmd_add_sstable.go#L71)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Hm, not sure. For some reason I thought we just never liked nullable fields, even for optional message types? If that isn't true, I'd happily make this one nullable. 
</blockquote></details>

I like nullable here. we usually care about them because of allocs
___
*[pkg/storage/batcheval/cmd_add_sstable.go, line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36549#-LbeJhqRD8GYTQ1NMWjY:-LbhuHS_4HvZXLj3LPxt:b-hjtjyf) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe94913263aa1103c4e7c6f5567a61f06fc09cd3/pkg/storage/batcheval/cmd_add_sstable.go#L86)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is `unsafeKey.Less(mvccEndKey)` possible after a `Seek`?
</blockquote></details>

Interesting point. mvccEndKey is constructed from args.EndKey, which should be greater than any key in the sstable. Does that mean the ok check is enough?

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36549)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz and @dt)

___
*[pkg/storage/batcheval/cmd_add_sstable.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36549#-LbeIyaB6V1zMLVKlN4S:-LbiCHd4AaEDetI9CKpf:b2ve8pr) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe94913263aa1103c4e7c6f5567a61f06fc09cd3/pkg/storage/batcheval/cmd_add_sstable.go#L71)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I like nullable here. we usually care about them because of allocs
</blockquote></details>

Yeah, it's usually because of allocations, but that's not really a concern here.
___
*[pkg/storage/batcheval/cmd_add_sstable.go, line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36549#-LbeJhqRD8GYTQ1NMWjY:-LbiCZwaETFqWPYzxMLn:b-4dy2tw) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe94913263aa1103c4e7c6f5567a61f06fc09cd3/pkg/storage/batcheval/cmd_add_sstable.go#L86)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Interesting point. mvccEndKey is constructed from args.EndKey, which should be greater than any key in the sstable. Does that mean the ok check is enough?
</blockquote></details>

That's what I'm thinking. `args.EndKey` is exclusive, so if Seek ever succeeds, we have an issue.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36549)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[pkg/storage/batcheval/cmd_add_sstable.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36549#-LbeIyaB6V1zMLVKlN4S:-Lbyll50EpsAPH2kueZD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe94913263aa1103c4e7c6f5567a61f06fc09cd3/pkg/storage/batcheval/cmd_add_sstable.go#L71)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yeah, it's usually because of allocations, but that's not really a concern here.
</blockquote></details>

Done.
___
*[pkg/storage/batcheval/cmd_add_sstable.go, line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36549#-LbeJhqRD8GYTQ1NMWjY:-Lbylm3o2zce8zAA0UtT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe94913263aa1103c4e7c6f5567a61f06fc09cd3/pkg/storage/batcheval/cmd_add_sstable.go#L86)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

That's what I'm thinking. `args.EndKey` is exclusive, so if Seek ever succeeds, we have an issue.
</blockquote></details>

Done.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36549#-:-LbzyIw58K-sQpxvSiGp:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Comment by dt** [comment]
so turns out that that `.Less()` check after the `.Seek` to the same key actually _was_ doing something. I haven't dug into it yet but that seems like it does not agree with the contract on Iterator.Seek, so I think we need to look at sst_iterator (unless I'm being super dense and totally misunderstanding `Seek` and `Less` usage?)

**Comment by dt** [comment]
I forgot to say that this is ready for another look (specifically the changes in the caller's computation on split retries are new)

**Comment by dt** [comment]
@nvanbenschoten this got lost a while back debugging broken `Seek` on `SSTIterator`, but with that resolved, I think this is ready for another look.

**Comment by nvanbenschoten** [comment]
Do you mind rebasing it before I do the final pass?

**Comment by dt** [comment]
Huh, I don't know why GitHub closed this. Initially it wouldn't let me re-open it either and had a tooltip saying `The repository may be missing relevant data. Please contact support for more information.`. I sent a ticket but it looks like maybe it has resolved itself? maybe it was so old it dropped out of some cache or something ¯\_(ツ)_/¯

**Comment by dt** [comment]
rebase needed one last round of `crl-fmt` but looks happy now

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 13 of 13 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36549#-:-LlJRNaU0CAO9x7GBTb9:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @dt)

___
*[pkg/roachpb/api.proto, line 1443 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36549#-LlJRLkNEwBXNVaIG0G6:-LlJRLkO4B06FMfTUwYZ:bnm0mh8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1167f247de96143857e12de8aa9a666351f6dd94/pkg/roachpb/api.proto#L1443)):*
> ```protobuf
>   // regardless of the timestamps.
>   bool disallow_shadowing = 3;
>   storage.engine.enginepb.MVCCStats mvcc_stats = 4 [(gogoproto.customname) = "MVCCStats"];
> ```

Give this field a comment.

**Review by dt — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36549#-:-LlP7P3JCRGZ1Q2zciZU:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @nvanbenschoten)

___
*[pkg/roachpb/api.proto, line 1443 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36549#-LlJRLkNEwBXNVaIG0G6:-LlP7KRO3rdY1Eswn9Ij:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1167f247de96143857e12de8aa9a666351f6dd94/pkg/roachpb/api.proto#L1443)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Give this field a comment.
</blockquote></details>

Done.

**Comment by dt** [comment]
huh, `TestDrainingProcessorSwallowsUncertaintyError` flake looks unrelated.

bors r+

**Pull request merged**
