### PR TITLE
roachtest: tpccbench: handle overload vm crash in last search iter

### LINKED ISSUE #64187: roachtest: tpccbench/nodes=6/cpu=16/multi-az failed
roachtest.tpccbench/nodes=6/cpu=16/multi-az [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2920165&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=2920165&tab=artifacts#/tpccbench/nodes=6/cpu=16/multi-az) on master @ [3cd29547884feb24b150b67ca2a88073798a35fd](https://github.com/cockroachdb/cockroach/commits/3cd29547884feb24b150b67ca2a88073798a35fd):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/tpccbench/nodes=6/cpu=16/multi-az/run_1
	cluster.go:1716,context.go:140,cluster.go:1705,test_runner.go:858: dead node detection: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod monitor teamcity-2920165-1619291008-63-n7cpu16-geo --oneshot --ignore-empty-nodes: exit status 1 7: skipped
		1: dead
		3: 1587
		2: 1572
		4: 1588
		6: 1605
		5: 1598
		Error: UNCLASSIFIED_PROBLEM: 1: dead
		(1) UNCLASSIFIED_PROBLEM
		Wraps: (2) attached stack trace
		  -- stack trace:
		  | main.glob..func14
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:1162
		  | main.wrap.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:284
		  | github.com/spf13/cobra.(*Command).execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:856
		  | github.com/spf13/cobra.(*Command).ExecuteC
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:960
		  | github.com/spf13/cobra.(*Command).Execute
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:897
		  | main.main
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachprod/main.go:2057
		  | runtime.main
		  | 	/usr/local/go/src/runtime/proc.go:204
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1374
		Wraps: (3) 1: dead
		Error types: (1) errors.Unclassified (2) *withstack.withStack (3) *errutil.leafError
```
<details><summary>Reproduce</summary>
<p>
<p>To reproduce, try:

```bash
# From https://go.crdb.dev/p/roachstress, perhaps edited lightly.
caffeinate ./roachstress.sh tpccbench/nodes=6/cpu=16/multi-az
```
</p>
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #62339 roachtest: tpccbench/nodes=6/cpu=16/multi-az failed [overload] [C-test-failure O-roachtest O-robot branch-release-21.1]
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*tpccbench/nodes=6/cpu=16/multi-az.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by tbg**
`tpccbench` is set up to "handle" (ignore) crashes during its line
search on the assumption that these are due to pushing CRDB into
overload territory, which at the time of writing it does not handle
gracefully.
There was a special case in which this was broken, namely that of
the line search terminating in a final step with a crash. In that
case, the cluster would be left running with one node down, which
roachtest checks and emits as an error.

Unconditionally restart the cluster after the line search (assuming
it found a passing warehouse count, i.e. didn't error out itself)
to make roachtest happy.

cc @cockroachdb/kv

Closes #64187.

Release note: None

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64205)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/cmd/roachtest/tpcc.go, line 844 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64205#-MZDDVeE7B3wxET4A6rU:-MZDDVeF4ILgrU00syoy:b-f7qvyf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d72b8559b69b8948de7a3c2792739c22beaa2882/pkg/cmd/roachtest/tpcc.go#L844)):*
> ```Go
> 		restart()
> 
> 		time.Sleep(restartWait)
> ```

Will we need to sleep after the final `restart()` call? If so, maybe consider moving this into `restart()`.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64205)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

___
*[pkg/cmd/roachtest/tpcc.go, line 844 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64205#-MZDDVeE7B3wxET4A6rU:-MZDEPvf203qYwST9bMO:bnf84x1) ([raw file](https://github.com/cockroachdb/cockroach/blob/d72b8559b69b8948de7a3c2792739c22beaa2882/pkg/cmd/roachtest/tpcc.go#L844)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Will we need to sleep after the final `restart()` call? If so, maybe consider moving this into `restart()`.
</blockquote></details>

No, there shouldn't be any reason to - we usually don't randomly sleep after starting the cluster. I guess there also shouldn't be any reason for this to be necessary here, but I don't want to ruffle any feathers :-)

**Review by erikgrinaker — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64205#-:-MZDT0Bd4l1O7Epd0nYn:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

**Comment by tbg** [comment]
bors r=erikgrinaker

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64205)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/cmd/roachtest/tpcc.go, line 812 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64205#-MZEBFKm-6Z39HXkeObn:-MZEBFKm-6Z39HXkeObo:b-8g19qh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d72b8559b69b8948de7a3c2792739c22beaa2882/pkg/cmd/roachtest/tpcc.go#L812)):*
> ```Go
> 			}
> 			shortCtx, cancel := context.WithTimeout(ctx, 2*time.Minute)
> 			if err := c.StopE(shortCtx, roachNodes); err != nil {
> ```

Tobi, what's the point of this `Stop` call after the previous `c.Reset()`? What's there to stop? Are we simply using it as a sanity check that we can talk to the machines?

**Comment by tbg** [comment]
@andreimatei yes pretty much. I hope all of this `Reset` business can go away when we've done something about https://github.com/cockroachdb/cockroach/pull/64177.

bors r=erikgrinaker

**Pull request merged**
