### PR TITLE
storage: move TestingKnobs to storagebase

### PR DESCRIPTION
**Pull request by jordanlewis**
... to permit users of TestingKnobs not to have to import all of
storage.

Also, delete an unused TestingKnob that accepted Replica as a parameter.

Updates #30001.

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
> Reviewed 47 of 47 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31317)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by jordanlewis** [comment]
TFTR!

bors r+

**Comment by andreimatei** [comment]
Can you please explain more about the motivation for this change?
The way I see it, different knobs are specific to different packages, and it's natural for them to live in their respective packages. It's also natural for the callback knobs to take in arguments of types that are not exported by the respective package.
What dependency exactly did you want to break here? I see this seems to be part of a larger plan to break the dependency of sql on storage; I don't really understand this desire, particularly if it comes at the cost of this kind of code moves (as opposed to introducing some interfaces). Presumably SQL was fiddling with some of these knobs; what is another implementation of the storage layer supposed to do with the knobs sql was setting?
So I guess my question here is - what have we gained?

**Comment by jordanlewis** [comment]
The original goal was to break the edge between sql and CGo libraries. That goal expanded into the only slightly more difficult goal of having sql not depend on storage. Why? The storage package is enormous and 99.5% of it is completely irrelevant to the sql package. Moving one TestingKnobs struct somewhere else to fully break that edge seems like a net win to me, just on the basis of package boundary cleanliness.

**Comment by andreimatei** [comment]
>  Moving one TestingKnobs struct somewhere else to fully break that edge seems like a net win to me, just on the basis of package boundary cleanliness.

But it's not, in my opinion. In fact, it's a step backwards. sql (as used in the cockroach binary, through the server) will always depend on storage, either statically or dynamically. And since it does, a static dependency is generally better than a dynamic one, unless you get some concrete benefit from making it dynamic. After a change like this, sql depends on both storage and storagebase.
In my opinion, if there actually were a benefit from removing the static dependency, we should extract a proper interface for storage. That interface would probably not contain the vast majority of these testing knobs, since they wouldn't make sense for another implementation. Whoever knows enough to set one of these knobs, knows enough to depend on `storage`.

What's wrong with sql depending on storage? I'm guessing somebody other than the crdb server started depending on sql and is unhappy with the firehose; if so, I think maybe a better effort might be to make sql more modular and have those other binaries only depend on small parts of sql.

**Comment by andreimatei** [comment]
We spent some time at the kitchen table and it looks like the storage TestingKnobs can go back into the storage package without sql caring much.

**Pull request merged**
