### PR TITLE
colmem: fix some issues with the memory limiting

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: some fixes of the external sort**

This commit fixes some of the relatively benign issues in the external
sort:
- previously we forgot to unset the partition info for all partitions
that are being merged as part of the repeated merging process (we would
only reset the first one because it is overwritten by the newly created
"merged" partition)
- we incorrectly estimated "min output batch size" for the repeated
merging (the calculation was as if all current partitions were being
merged rather than `n`)
- we incorrectly computed the memory size of the enqueued batch. It is
possible that the batch is a "window" or doesn't use the whole capacity,
and previously we were using the total memory footprint.  However, we
need to only include the "proportional" size according to the length of
the batch.

The issues are relatively benign since they would mostly make the verbose
logging incorrect as well as over-estimate the "max batch mem size"
(which would mean that we'd merge the partitions sooner or with
a smaller output batch size).

Release justification: low-risk bug fix.

Release note: None

**colmem: fix some issues with the memory limiting**

This commit fixes a couple of issues with how we do memory-limiting of
batches by the footprint. In particular, the allocator will now estimate
the memory footprint of a batch before allocating a new one and will
clamp the capacity so that the batch stays under the limit. Previously,
we could allocate a batch that would exceed the limit even when all
types are fixed length. This behavior has been present since long time
ago.

Additionally, this commit fixes a recent regression in how
`SetAccountingHelper` uses the capacity of the batch. Previously, if
a new batch is allocated (when variable-width types are present) and
exceeds the memory limit, then the first call to `AccountForSet` would
artificially clamp the used capacity at 1, so the batch might have a lot
of unused capacity. Now the helper will memorize the full capacity right
after the batch is allocated. This regression was introduced in a recent
refactor of the `SetAccountingHelper`. In particular, it could lead to
the external sort (which uses the ordered synchronizer internally which
uses the `SetAccountingHelper`) becoming excruciatingly slow with
"unlucky" low memory limits. The limit would be "unlucky" if it is such
that a batch with capacity `c` doesn't exceed it, but the batch with
capacity `2 * c` would exceed the limit by less than a factor of two. In
such a scenario previously we would allocate the batch of capacity
`2 * c` yet would always use only a single row (because in
`AccountForSet` we would set the max capacity at 1).

Addresses: #87510.

Release justification: bug fix.

Release note: None

### CODE REVIEW

**Review by DrewKimball — COMMENTED** [review]
In cases like the one you mentioned with the external sort, won't the capacity limit be exponentially decreased until it hits 1 anyway?

> Reviewed 1 of 1 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87563#-:-NBQa8tV7tg81aj2m3nH:b5251qd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[`pkg/sql/colmem/allocator.go` line 194 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87563#-NBQYhZu5jHlcigUTG8h:-NBQYhZu5jHlcigUTG8i:bgdfzhz) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbffa4fe710d0124c3276aa0d25096630f5fb92f/pkg/sql/colmem/allocator.go#L194)):*
> ```Go
> // still within the memory limit for the given type schema. The returned value
> // is at most minDesiredCapacity and at least 1.
> func checkDesiredCapacityMemoryLimit(
> ```

[nit] another possible name could be `truncateCapacityToMemoryLimit` or just `truncateToMemoryLimit` - up to you, though.
___
*[`pkg/sql/colmem/allocator.go` line 204 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87563#-NBQX6gbAX3NpERGOfKY:-NBQX6gcBrT4WNlxX0Qe:b-c9wbjg) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbffa4fe710d0124c3276aa0d25096630f5fb92f/pkg/sql/colmem/allocator.go#L204)):*
> ```Go
> 	// desired capacity, if not, reduce the ask.
> 	estimatedMemoryUsage := SelVectorSize(minDesiredCapacity) + EstimateBatchSizeBytes(typs, minDesiredCapacity)
> 	if estimatedMemoryUsage >= maxBatchMemSize {
> ```

[nit] I think we can do `>` instead, since the `=` case should be a no-op.
___
*[`pkg/sql/colmem/allocator.go` line 275 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87563#-NBQUlKa8v6TLICXH5zR:-NBQQCUq3PrsOjogA4e5:b5qj34t) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbffa4fe710d0124c3276aa0d25096630f5fb92f/pkg/sql/colmem/allocator.go#L275)):*
> ```Go
> 		if estimatedMaxCapacity := checkDesiredCapacityMemoryLimit(
> 			growCapacity(oldBatch, minDesiredCapacity), maxBatchMemSize, typs,
> 		); estimatedMaxCapacity < minDesiredCapacity {
> ```

I think this condition is equivalent to 
```checkDesiredCapacityMemoryLimit(minDesiredCapacity, maxBatchMemSize, typs) < minDesiredCapacity```, since `estimatedMaxCapacity` being less than `minDesiredCapacity` implies that `minDesiredCapacity` would also exceed the memory limit. So, we could simplify to:
```
minDesiredCapacity = checkDesiredCapacityMemoryLimit(minDesiredCapacity, maxBatchMemSize, typs)
if minDesiredCapacity < int(float64(oldBatch.Capacity())*1.1) {
    useOldBatch = true
}
```
I guess the first line could be moved up next to `reallocated = true`, since it is used in both branches.
___
*[`pkg/sql/colmem/allocator.go` line 309 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87563#-NBQY0dO-mpVDrJ4-lfA:-NBQY0dO-mpVDrJ4-lfB:bv25n09) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbffa4fe710d0124c3276aa0d25096630f5fb92f/pkg/sql/colmem/allocator.go#L309)):*
> ```Go
> 		} else {
> 			a.ReleaseMemory(oldBatchMemSize)
> 			newCapacity := growCapacity(oldBatch, minDesiredCapacity)
> ```

[nit] If you perform the above refactoring, you could inline `growCapacity` (e.g. keep the old code unchanged), since it's only used in one place now.

**Review by yuzefovich — COMMENTED** [review]
If we're "unlucky", then we will reuse the same batch that exceeded the limit (but not by too much to be discarded) from now on and only will ever set a single tuple. Setting that single tuple is the source of extreme slowdown. I updated the commit message to include this detail.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87563#-:-NBTCRCR2rvbbh-YcOd9:b-2s8hz6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @michae2, and @yuzefovich)

___
*[`pkg/sql/colmem/allocator.go` line 194 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87563#-NBQYhZu5jHlcigUTG8h:-NBSoH7zDQWaVKGSIgAj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbffa4fe710d0124c3276aa0d25096630f5fb92f/pkg/sql/colmem/allocator.go#L194)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] another possible name could be `truncateCapacityToMemoryLimit` or just `truncateToMemoryLimit` - up to you, though.
</blockquote></details>

Done.
___
*[`pkg/sql/colmem/allocator.go` line 204 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87563#-NBQX6gbAX3NpERGOfKY:-NBSoKjSDzk8IjoaDTA6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbffa4fe710d0124c3276aa0d25096630f5fb92f/pkg/sql/colmem/allocator.go#L204)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] I think we can do `>` instead, since the `=` case should be a no-op.
</blockquote></details>

Done.
___
*[`pkg/sql/colmem/allocator.go` line 275 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87563#-NBQUlKa8v6TLICXH5zR:-NBSmiAK0tpBu-spTuIR:b-cnivv7) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbffa4fe710d0124c3276aa0d25096630f5fb92f/pkg/sql/colmem/allocator.go#L275)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

I think this condition is equivalent to 
```checkDesiredCapacityMemoryLimit(minDesiredCapacity, maxBatchMemSize, typs) < minDesiredCapacity```, since `estimatedMaxCapacity` being less than `minDesiredCapacity` implies that `minDesiredCapacity` would also exceed the memory limit. So, we could simplify to:
```
minDesiredCapacity = checkDesiredCapacityMemoryLimit(minDesiredCapacity, maxBatchMemSize, typs)
if minDesiredCapacity < int(float64(oldBatch.Capacity())*1.1) {
    useOldBatch = true
}
```
I guess the first line could be moved up next to `reallocated = true`, since it is used in both branches.

</blockquote></details>

It's not exactly equivalent since we truncate the "grown" capacity, not the desired capacity. So if `minDesiredCapacity` is 10, `oldBatch.Capacity()` is 6, `growCapacity()` will return 12. If we only have enough limit for 8, then we update the desired capacity. At the same time if we have enough limit for 11 or more, we do not want to update the min desired cap. The reason for truncating the "grown" capacity is to see whether we should encourage the usage of the old batch when it is already pretty close to the limit.

Pulling out `minDesiredCapacity = checkDesiredCapacityMemoryLimit(minDesiredCapacity, maxBatchMemSize, typs)` next to `reallocated = true` seems correct but would be mostly a noop for the case when `oldBatch` is non-nil. (If we reuse the old batch - for whatever reason - then the desired capacity doesn't matter, it we don't reuse the old batch, then we want to truncate the "grown" capacity, not the original min desired cap.)

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87563)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @michae2, and @yuzefovich)

___
*[`pkg/sql/colmem/allocator.go` line 275 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87563#-NBQUlKa8v6TLICXH5zR:-NBTFkruAL7TasJOiYcM:biljrx1) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbffa4fe710d0124c3276aa0d25096630f5fb92f/pkg/sql/colmem/allocator.go#L275)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

It's not exactly equivalent since we truncate the "grown" capacity, not the desired capacity. So if `minDesiredCapacity` is 10, `oldBatch.Capacity()` is 6, `growCapacity()` will return 12. If we only have enough limit for 8, then we update the desired capacity. At the same time if we have enough limit for 11 or more, we do not want to update the min desired cap. The reason for truncating the "grown" capacity is to see whether we should encourage the usage of the old batch when it is already pretty close to the limit.

Pulling out `minDesiredCapacity = checkDesiredCapacityMemoryLimit(minDesiredCapacity, maxBatchMemSize, typs)` next to `reallocated = true` seems correct but would be mostly a noop for the case when `oldBatch` is non-nil. (If we reuse the old batch - for whatever reason - then the desired capacity doesn't matter, it we don't reuse the old batch, then we want to truncate the "grown" capacity, not the original min desired cap.)
</blockquote></details>

Hm, maybe I'm missing something here... here's my reasoning:
1. `checkDesiredCapacityMemoryLimit` returns a value `<=` the given capacity, which depends only on the memory limit in the `<` case.
2. We only want to change `minDesiredCapacity` if the adjusted `expectedMaxCapacity` is smaller than it
3. If (1) and (2) are true, truncating `minDesiredCapacity` directly should have the same affect

In the example you mentioned, if we have enough memory for 11 or more, `minDesiredCapacity` wouldn't be adjusted, right (because of (1))? And if we only had enough for 8, it would be updated to 8 as expected.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87563)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @michae2, and @yuzefovich)

___
*[`pkg/sql/colmem/allocator.go` line 275 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87563#-NBQUlKa8v6TLICXH5zR:-NBTX8lBBSOqzTuJurgR:b-84igmt) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbffa4fe710d0124c3276aa0d25096630f5fb92f/pkg/sql/colmem/allocator.go#L275)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Hm, maybe I'm missing something here... here's my reasoning:
1. `checkDesiredCapacityMemoryLimit` returns a value `<=` the given capacity, which depends only on the memory limit in the `<` case.
2. We only want to change `minDesiredCapacity` if the adjusted `expectedMaxCapacity` is smaller than it
3. If (1) and (2) are true, truncating `minDesiredCapacity` directly should have the same affect

In the example you mentioned, if we have enough memory for 11 or more, `minDesiredCapacity` wouldn't be adjusted, right (because of (1))? And if we only had enough for 8, it would be updated to 8 as expected.
</blockquote></details>

This sounds right, but I think you might be missing that in this line of code we don't call `truncateToMemoryLimit` with `minDesiredCapacity` but with the result of `growCapacity()`.

I agree that we can pull out `minDesiredCapacity = truncateToMemoryLimit(minDesiredCapacity, maxBatchMemSize, typs)` to where `reallocated = true` is, but it shouldn't change the behavior of the code in comparison to how it's currently written. There are three cases to consider:
1. old batch is nil. In this case we already perform the truncation.
2. old batch is non-nil and is reused. In this case the possibly updated min desired cap doesn't matter since we don't allocate a new batch.
3. old batch is non-nil and is not reused. In this case we want to try growing the capacity and make it subject to the memory limit. If we truncate the min desired capacity early on, we either need to memorize the fact that it was already truncated (so that we don't attempt to grow the capacity at all), or if it wasn't truncated early on, then we still want to try growing the capacity. So it seems to make only a somewhat meaningful change in the former case, but it is still eventually ends up with the same target capacity for the code as is.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87563)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @michae2, and @yuzefovich)

___
*[`pkg/sql/colmem/allocator.go` line 275 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87563#-NBQUlKa8v6TLICXH5zR:-NBTZpsk16CQXnNYJI4b:b-l79hb4) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbffa4fe710d0124c3276aa0d25096630f5fb92f/pkg/sql/colmem/allocator.go#L275)):*
The result of `growCapacity()` shouldn't ever be smaller than `minDesiredCapacity`, right? And we'd only adjust `minDesiredCapacity` if the result of truncating `growCapacity()` is smaller than `minDesiredCapacity`, in which case `minDesiredCapacity` must exceed the memory limit and would be adjusted in the same way by just truncating it directly.

>I agree that we can pull out minDesiredCapacity = truncateToMemoryLimit(minDesiredCapacity, maxBatchMemSize, typs) to where reallocated = true is, but it shouldn't change the behavior of the code in comparison to how it's currently written.

I should have added [nit] to that part - I just thought it would look a bit cleaner. I don't feel strongly about it.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87563)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @michae2, and @yuzefovich)

___
*[`pkg/sql/colmem/allocator.go` line 275 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87563#-NBQUlKa8v6TLICXH5zR:-NBTmTl408yLm8x3g2av:b-hn2dz4) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbffa4fe710d0124c3276aa0d25096630f5fb92f/pkg/sql/colmem/allocator.go#L275)):*
> The result of `growCapacity()` shouldn't ever be smaller than `minDesiredCapacity`, right? And we'd only adjust `minDesiredCapacity` if the result of truncating `growCapacity()` is smaller than `minDesiredCapacity`, in which case `minDesiredCapacity` must exceed the memory limit and would be adjusted in the same way by just truncating it directly.

I see, this all sounds right.

I think what's missing from the current discussion is that sometimes `minDesiredCapacity` is not sufficient (when the caller doesn't know how many tuples it'll set). So in a case when `desiredCapacitySufficient = false`, and let's say `oldCapacity = 2`, the caller will provide `minDesiredCapacity = 0` which is clamped to 1 at the very top of the method. So if we then do `minDesiredCapacity = truncateToMemoryLimit(minDesiredCapacity, maxBatchMemSize, typs)`, it'll stay at 1 and condition `if minDesiredCapacity < 1.1 * oldCapacity` will be true making so that the capacity will never grow. But this is not the intention of the caller.

If we pull out something like `minDesiredCapacity = truncateToMemoryLimit(growCapacity(...), ...)` to where `reallocated = true` is, then we might allocate a larger batch that the caller is asking for (when the old batch is nil and `desiredCapacitySufficient` is `true`). Does this sound right?

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87563#-:-NBU-f0y-SWG27jN6gia:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball, @michae2, and @yuzefovich)

___
*[`pkg/sql/colmem/allocator.go` line 275 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87563#-NBQUlKa8v6TLICXH5zR:-NBTsYhv24b5xtHw4PDp:bfaelx5) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbffa4fe710d0124c3276aa0d25096630f5fb92f/pkg/sql/colmem/allocator.go#L275)):*
> So if we then do minDesiredCapacity = truncateToMemoryLimit(minDesiredCapacity, maxBatchMemSize, typs), it'll stay at 1 and condition if minDesiredCapacity < 1.1 * oldCapacity will be true making so that the capacity will never grow. But this is not the intention of the caller.

I see, I was missing that case. Thanks for walking me through it all. I think there's probably room for simplification here, but it looks correct. I guess maybe it's best to keep the changes minimal here so that it can be backported, and then any refactoring can happen later.

>If we pull out something like minDesiredCapacity = truncateToMemoryLimit(growCapacity(...), ...) to where reallocated = true is, then we might allocate a larger batch that the caller is asking for (when the old batch is nil and desiredCapacitySufficient is true). Does this sound right?

That makes sense now with the other point you made, we should leave that as it is.

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87563#-:-NBUDF69BIqxchZkWuQp:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball, @michae2, and @yuzefovich)

___
*[`pkg/sql/colmem/allocator.go` line 275 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/87563#-NBQUlKa8v6TLICXH5zR:-NBUCzO46biuPvGfqn6e:b1c1lo6) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbffa4fe710d0124c3276aa0d25096630f5fb92f/pkg/sql/colmem/allocator.go#L275)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

> So if we then do minDesiredCapacity = truncateToMemoryLimit(minDesiredCapacity, maxBatchMemSize, typs), it'll stay at 1 and condition if minDesiredCapacity < 1.1 * oldCapacity will be true making so that the capacity will never grow. But this is not the intention of the caller.

I see, I was missing that case. Thanks for walking me through it all. I think there's probably room for simplification here, but it looks correct. I guess maybe it's best to keep the changes minimal here so that it can be backported, and then any refactoring can happen later.

>If we pull out something like minDesiredCapacity = truncateToMemoryLimit(growCapacity(...), ...) to where reallocated = true is, then we might allocate a larger batch that the caller is asking for (when the old batch is nil and desiredCapacitySufficient is true). Does this sound right?

That makes sense now with the other point you made, we should leave that as it is.
</blockquote></details>

I appreciate the attention to the details!

**Pull request merged**
