### PR TITLE
roachprod: configure logging in roachprod library

### LINKED ISSUE #73234: roachprod: logs for parallel roachtests make it to console
Before (the librarification of roachprod, I assume), logs from roachtest's invocation of `roachprod` would not make it to stdout if multiple tests were running in parallel. Now they seem to do, and it's messy.
When using `roachtest --parallelism=<n> ...`, most logs are redirected away from stdout. I can dig out the info on this if necessary. Invocations of external binaries (like `roachprod` used to be) were also redirected.

### PR DESCRIPTION
**Pull request by healthy-pod**
This patch moves `pkg/cmd/roachtest/logger` to `pkg/roachprod/logger`
to be used as a logger by the roachprod library. `roachtest` and the
roachprod binary are then configured to use/pass instances of `logger`
as needed by `pkg/roachprod`.

All calls to `fmt.Printf` and `fmt.Println` were removed from
`pkg/roachprod` except in few cases specific to the roachprod
binary. In the future, using `fmt.Printf` and `fmt.Println` in
the library (i.e. `pkg/roachprod`) should be discouraged.

Closes #73234.

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
> Reviewed 152 of 152 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74223)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @healthy-pod, and @RaduBerinde)

___
*[pkg/cmd/roachprod/main.go, line 891 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74223#-MraNw_w490pWR49tS_L:-MraNw_w490pWR49tS_M:b-xwuyno) ([raw file](https://github.com/cockroachdb/cockroach/blob/51e94c0feb3acb0a8995fdee330a8e6ec5dcaa4e/pkg/cmd/roachprod/main.go#L891)):*
> ```Go
> 	loggerCfg := logger.Config{Stdout: os.Stdout, Stderr: os.Stderr}
> 	var loggerError error
> 	roachprodLibraryLogger, loggerError = loggerCfg.NewLogger("/Users/ahmad/desktop/roachprod.log")
> ```

hello ahmad :-)

**Review by healthy-pod — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74223)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @RaduBerinde, and @tbg)

___
*[pkg/cmd/roachprod/main.go, line 891 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74223#-MraNw_w490pWR49tS_L:-Mrc58hPDvugW_4SQXOF:b31x5fd) ([raw file](https://github.com/cockroachdb/cockroach/blob/51e94c0feb3acb0a8995fdee330a8e6ec5dcaa4e/pkg/cmd/roachprod/main.go#L891)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

hello ahmad :-)
</blockquote></details>

Oops! I will remove it. TFTR

**Comment by rickystewart** [comment]
bors r=tbg

**Comment by rickystewart** [comment]
bors r=tbg

**Pull request merged**
