### PR TITLE
*: lint log and error formatters / constructors

### PR DESCRIPTION
**Pull request by knz**
This patch adds a new `fmtsafe` linter in the roachvet
tree and fixes a couple of bugs found by the litter.

The linter checks the following:

- that the format string in `log.Infof()`, `errors.Errorf()` and
  similar calls is a constant string.

  This check is essential for correctness because format strings
  are assumed to be PII-free and always safe for reporting in
  telemetry or PII-free logs.

- that the message strings in errors.New() and similar calls that
  construct error objects is a constant string.

  This check is provided to encourage hygiene: errors
  constructed using non-constant strings are better constructed using
  a formatting function instead, which makes the construction more
  readable and encourage the provision of PII-free reportable details.

New error or logging formatter should be subsequently added to the
file `functions.go` in that linter's directory.

It is possible for a call site to opt the format/message string out of
the linter using `/* nolint:fmtsafe */` after the format argument.
This can only be done in tests, where it can be assumed that no
formatted messages/errors will ever be reported to telemetry.

Example bugs that were found:

- `log.Warningf(ctx, msg)` with a non-constant `msg` that might
  contain `%` codes.
- calls to `errors.New(fmt.Sprintf(...))` instead of
  `errors.Newf(...)`.

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
@ajwerner can you review the code of the linter specifically (I borrowed some of your code in the return err check linter)

@irfansharif can you review all the PR

thanks

**Comment by knz** [comment]
(I intend to backport this to 20.1 and 19.2)

**Review by RaduBerinde — COMMENTED** [review]
Very cool!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48040#-:-M5sB7F74BZgSDPdd_WP:b-jdo7t9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @irfansharif, and @knz)

___
*[pkg/ccl/importccl/read_import_mysql.go, line 680 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48040#-M5s4Zdb8kekVdXyrAte:-M5s4Zdb8kekVdXyrAtf:b-mzu0j3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b5ee59716d243c42bdde7add795db3f7a1e15a0/pkg/ccl/importccl/read_import_mysql.go#L680)):*
> ```Go
> 	case mysqltypes.Set:
> 		return nil, errors.WithHint(unimplemented.NewWithIssue(32560,
> 			"cannot import SET columns at this time"),
> ```

[nit] indentation here (and below) doesn't match the syntactic depth, maybe put the entire `NewWithIssue` call on one line?
___
*[pkg/sql/rowexec/distinct.go, line 281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48040#-M5s5EXZAKafyH2Nyw1I:-M5s5EXZAKafyH2Nyw1J:bgjssec) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b5ee59716d243c42bdde7add795db3f7a1e15a0/pkg/sql/rowexec/distinct.go#L281)):*
> ```Go
> 				// an error.
> 				//
> 				// TODO(knz): errorOnDup could be passed via log.Safe() if
> ```

We should do this, the text string is something like "UPSERT or INSERT...ON CONFLICT command cannot affect row a second time"

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48040)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @irfansharif, and @RaduBerinde)

___
*[pkg/ccl/importccl/read_import_mysql.go, line 680 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48040#-M5s4Zdb8kekVdXyrAte:-M5v3W-148fqCo7Nr3C-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b5ee59716d243c42bdde7add795db3f7a1e15a0/pkg/ccl/importccl/read_import_mysql.go#L680)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] indentation here (and below) doesn't match the syntactic depth, maybe put the entire `NewWithIssue` call on one line?
</blockquote></details>

Done.
___
*[pkg/sql/rowexec/distinct.go, line 281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48040#-M5s5EXZAKafyH2Nyw1I:-M5v3X5m0hk4i8ZAmDeR:b-xdt6ta) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b5ee59716d243c42bdde7add795db3f7a1e15a0/pkg/sql/rowexec/distinct.go#L281)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We should do this, the text string is something like "UPSERT or INSERT...ON CONFLICT command cannot affect row a second time"
</blockquote></details>

I believe you but I don't trust the code.
If what you say is true, why is this string literal not used here instead of a struct field?

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/rowexec/distinct.go, line 281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48040#-M5s5EXZAKafyH2Nyw1I:-M5vjco00OENuGbTEX65:b-72wy35) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b5ee59716d243c42bdde7add795db3f7a1e15a0/pkg/sql/rowexec/distinct.go#L281)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I believe you but I don't trust the code.
If what you say is true, why is this string literal not used here instead of a struct field?
</blockquote></details>

We want the error message to "live" in the optimizer and think it's used for two different cases (with string literals in both cases).

What are the consequences of this change exactly? In what contexts will we stop seeing the error?

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/rowexec/distinct.go, line 281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48040#-M5s5EXZAKafyH2Nyw1I:-M5vk_Ig378pjuFfooDQ:bwg2y1u) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b5ee59716d243c42bdde7add795db3f7a1e15a0/pkg/sql/rowexec/distinct.go#L281)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We want the error message to "live" in the optimizer and think it's used for two different cases (with string literals in both cases).

What are the consequences of this change exactly? In what contexts will we stop seeing the error?
</blockquote></details>

Maybe we should define a type "noPIIErrorMessage" and use that instead of the string?

I also have no problem wirh changing the string to a func() error that is implemented in the optimizer. But we'd still have the same problem inside the optimizer (so the separate type would still help).

**Review by ajwerner — COMMENTED** [review]
Just looked at the linter which :lgtm: 

> Reviewed 3 of 54 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48040#-:-M5voizr1pKNdr9zpq9W:b-r2d99y)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @irfansharif, and @knz)

___
*[pkg/testutils/lint/passes/fmtsafe/fmtsafe.go, line 149 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48040#-M5voL5ADV_vG1KTymkA:-M5voL5ADV_vG1KTymkB:b-cj09e6) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bae3cc1668835528d9a78a1676f08e424ae36eb/pkg/testutils/lint/passes/fmtsafe/fmtsafe.go#L149)):*
> ```Go
> 	nparams := params.Len()
> 
> 	// Is second last param 'format string'?
> ```

nits: `second to last` but also in the case of the constant message, it's the last param. Maybe `Is the message or format param a string?`

**Review by irfansharif — APPROVED** [review]
:lgtm:, thanks for submitting this!

s/litter/linter in the commit message

> Reviewed 53 of 54 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48040#-:-M60LA9e46npNqCNaaLL:b3xia6n)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/ccl/importccl/read_import_mysql.go, line 686 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48040#-M60MDEt55cRIeMiW39l:-M60MDEt55cRIeMiW39m:bqvaa1v) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bae3cc1668835528d9a78a1676f08e424ae36eb/pkg/ccl/importccl/read_import_mysql.go#L686)):*
> ```Go
> 	case mysqltypes.Bit:
> 		return nil, errors.WithHint(
> 			unimplemented.NewWithIssue(32561, "cannot improt BIT columns at this time"),
> ```

[nit,unrelated to this diff]: s/improt/import
___
*[pkg/cmd/roachprod-stress/main.go, line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48040#-M60MaF25nPPDxwXPqUG:-M60MaF25nPPDxwXPqUH:b7p9sp7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bae3cc1668835528d9a78a1676f08e424ae36eb/pkg/cmd/roachprod-stress/main.go#L65)):*
> ```Go
> 		flags.SetOutput(&b)
> 		flags.Usage()
> 		return errors.Newf("%s", b.String())
> ```

I can see myself running against this sort of linter error, and being confused as to what to do, if I didn't catch this PR fly by. Perhaps this usage pattern (and what's motivating it) should be captured in the errors pkg. I also just learned about this log.Safe machinery so maybe it's not a widespread concern.

Edit: I see this is part of the linter doc, how does that surface to an engineer introducing code failing this lint test?
___
*[pkg/internal/rsg/yacc/parse.go, line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48040#-M60NEnc8Bks7q4wMquA:-M60NEnc8Bks7q4wMquB:b-frj90p) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bae3cc1668835528d9a78a1676f08e424ae36eb/pkg/internal/rsg/yacc/parse.go#L27)):*
> ```Go
> 	"runtime"
> 
> 	"github.com/pkg/errors"
> ```

Noob question: why pkg/errors here instead of cockroachdb/errors? (Also, why pkg/errors anywhere within crdb really?)
___
*[pkg/kv/kvserver/raft_log_queue.go, line 615 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48040#-M60O7t7-vk4CFnaB-vX:-M60O7t7-vk4CFnaB-vY:bou0dsy) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bae3cc1668835528d9a78a1676f08e424ae36eb/pkg/kv/kvserver/raft_log_queue.go#L615)):*
> ```Go
> 		r.store.metrics.RaftLogTruncated.Inc(int64(decision.NumTruncatableIndexes()))
> 	} else {
> 		// TODO(knz,tbg): check how much of this can be included in log.Safe().
> ```

All of it is safe at the time of writing, we're only emitting log indexes and log size.
___
*[pkg/server/admin.go, line 1507 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48040#-M60P89w1lYKOCtH8qFX:-M60P89w1lYKOCtH8qFY:b37h7z) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bae3cc1668835528d9a78a1676f08e424ae36eb/pkg/server/admin.go#L1507)):*
> ```Go
> 	}
> 
> 	// The following query swaps the user identity to `root` because
> ```

This seems unrelated to the rest of the PR?
___
*[pkg/sql/sem/builtins/builtins.go, line 2901 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48040#-M60RM670hF7eE0otYaP:-M60RM670hF7eE0otYaQ:bje9ins) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bae3cc1668835528d9a78a1676f08e424ae36eb/pkg/sql/sem/builtins/builtins.go#L2901)):*
> ```Go
> 				errCode := string(*args[0].(*tree.DString))
> 				msg := string(*args[1].(*tree.DString))
> 				// We construct the errors below via %s as the
> ```

Is there a better place for this kind of comment? Perhaps in the `errors` pkg doc itself?

Edit: I see the fmtsafe doc now.
___
*[pkg/testutils/lint/passes/fmtsafe/fmtsafe.go, line 54 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48040#-M60U0BAD6FuabenqJNS:-M60U0BAD6FuabenqJNT:b32vbm) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bae3cc1668835528d9a78a1676f08e424ae36eb/pkg/testutils/lint/passes/fmtsafe/fmtsafe.go#L54)):*
> ```Go
> // Analyzer defines this pass.
> var Analyzer = &analysis.Analyzer{
> 	Name:     "fmtsafe2",
> ```

2?
___
*[pkg/testutils/lint/passes/fmtsafe/fmtsafe.go, line 109 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48040#-M60W1SB8KmblH6JF4QW:-M60W1SB8KmblH6JF4QX:b-k4mwwa) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bae3cc1668835528d9a78a1676f08e424ae36eb/pkg/testutils/lint/passes/fmtsafe/fmtsafe.go#L109)):*
> ```Go
> }
> 
> func maybeGetCstStr(pass *analysis.Pass, fd *ast.FuncDecl) (res *types.Var) {
> ```

[nit] s/Cst/Const
___
*[pkg/testutils/lint/passes/fmtsafe/fmtsafe.go, line 178 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48040#-M60Uof9DG-pamZIHckc:-M60Uof9DG-pamZIHckd:by46tzm) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bae3cc1668835528d9a78a1676f08e424ae36eb/pkg/testutils/lint/passes/fmtsafe/fmtsafe.go#L178)):*
> ```Go
> 	fnName := fn.FullName()
> 
> 	// pass.Reportf(call.Lparen, "in %s", fnName)
> ```

Leftover code?

**Review by knz — COMMENTED** [review]
> s/litter/linter in the commit message

Done

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48040#-:-M65qE-k78Hqeb9FPXjt:b4ub3xq)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner, @irfansharif, and @RaduBerinde)

___
*[pkg/ccl/importccl/read_import_mysql.go, line 686 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48040#-M60MDEt55cRIeMiW39l:-M65OWEO5G3ncxAP9Z1g:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bae3cc1668835528d9a78a1676f08e424ae36eb/pkg/ccl/importccl/read_import_mysql.go#L686)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

[nit,unrelated to this diff]: s/improt/import
</blockquote></details>

Done.
___
*[pkg/cmd/roachprod-stress/main.go, line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48040#-M60MaF25nPPDxwXPqUG:-M65QMJa5kvChhGuGZd7:b-2zvoy2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bae3cc1668835528d9a78a1676f08e424ae36eb/pkg/cmd/roachprod-stress/main.go#L65)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

I can see myself running against this sort of linter error, and being confused as to what to do, if I didn't catch this PR fly by. Perhaps this usage pattern (and what's motivating it) should be captured in the errors pkg. I also just learned about this log.Safe machinery so maybe it's not a widespread concern.

Edit: I see this is part of the linter doc, how does that surface to an engineer introducing code failing this lint test?
</blockquote></details>

It shows up like this in the error message:

```
    TestLint/TestRoachVet: lint_test.go:78:
        pkg/util/errorutil/tenant.go:33:19: message argument is not a constant expression
    TestLint/TestRoachVet: lint_test.go:78:
        Tip: use YourFuncf("%s", ...) or list new formatting wrappers in pkg/testutils/lint/passes/fmtsafe/functions.go.
```
___
*[pkg/internal/rsg/yacc/parse.go, line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48040#-M60NEnc8Bks7q4wMquA:-M65OtQFBJnrR6zDWKgy:b-x5057e) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bae3cc1668835528d9a78a1676f08e424ae36eb/pkg/internal/rsg/yacc/parse.go#L27)):*
>  why pkg/errors here instead of cockroachdb/errors

mistake (auto-import)

> why pkg/errors anywhere within crdb really?

we haven't linted it out yet (although we probably should - filed #48157 to track).
___
*[pkg/kv/kvserver/raft_log_queue.go, line 615 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48040#-M60O7t7-vk4CFnaB-vX:-M65ReMp-UfZrZYprNf-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bae3cc1668835528d9a78a1676f08e424ae36eb/pkg/kv/kvserver/raft_log_queue.go#L615)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

All of it is safe at the time of writing, we're only emitting log indexes and log size.
</blockquote></details>

Done.
___
*[pkg/server/admin.go, line 1507 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48040#-M60P89w1lYKOCtH8qFX:-M65Ri2U7rZbsMmre9YU:bucqylw) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bae3cc1668835528d9a78a1676f08e424ae36eb/pkg/server/admin.go#L1507)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

This seems unrelated to the rest of the PR?
</blockquote></details>

oops yes that is indeed unrelated. Reverted.
___
*[pkg/sql/rowexec/distinct.go, line 281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48040#-M5s5EXZAKafyH2Nyw1I:-M65S05Z6PfQA5a29FXY:b-uwuj99) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b5ee59716d243c42bdde7add795db3f7a1e15a0/pkg/sql/rowexec/distinct.go#L281)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Maybe we should define a type "noPIIErrorMessage" and use that instead of the string?

I also have no problem wirh changing the string to a func() error that is implemented in the optimizer. But we'd still have the same problem inside the optimizer (so the separate type would still help).
</blockquote></details>

What about this: make two exported constants in the opt package.
Then let the code here choose which one to use based on a bool (or an int). Would this work?
___
*[pkg/sql/sem/builtins/builtins.go, line 2901 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48040#-M60RM670hF7eE0otYaP:-M65S82OEv9vR3tDySet:bwqaqbe) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bae3cc1668835528d9a78a1676f08e424ae36eb/pkg/sql/sem/builtins/builtins.go#L2901)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Is there a better place for this kind of comment? Perhaps in the `errors` pkg doc itself?

Edit: I see the fmtsafe doc now.
</blockquote></details>

This comment is also for the future maintainer of builtins.go. My experience is that we get the least experienced folk work on this file first, so they need more handholding in comments.
___
*[pkg/testutils/lint/passes/fmtsafe/fmtsafe.go, line 54 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48040#-M60U0BAD6FuabenqJNS:-M65SIsy7f8gYTvIVDnr:bopsrp2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bae3cc1668835528d9a78a1676f08e424ae36eb/pkg/testutils/lint/passes/fmtsafe/fmtsafe.go#L54)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

2?
</blockquote></details>

:facepalm:  - left over from testing
___
*[pkg/testutils/lint/passes/fmtsafe/fmtsafe.go, line 109 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48040#-M60W1SB8KmblH6JF4QW:-M65p_n36aMkZgujgOsi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bae3cc1668835528d9a78a1676f08e424ae36eb/pkg/testutils/lint/passes/fmtsafe/fmtsafe.go#L109)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

[nit] s/Cst/Const
</blockquote></details>

Done.
___
*[pkg/testutils/lint/passes/fmtsafe/fmtsafe.go, line 149 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48040#-M5voL5ADV_vG1KTymkA:-M65pmJfCpj0smtcvq4B:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bae3cc1668835528d9a78a1676f08e424ae36eb/pkg/testutils/lint/passes/fmtsafe/fmtsafe.go#L149)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nits: `second to last` but also in the case of the constant message, it's the last param. Maybe `Is the message or format param a string?`
</blockquote></details>

Good idea. Done.
___
*[pkg/testutils/lint/passes/fmtsafe/fmtsafe.go, line 178 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48040#-M60Uof9DG-pamZIHckc:-M65pndF2H2C_lDyEQye:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bae3cc1668835528d9a78a1676f08e424ae36eb/pkg/testutils/lint/passes/fmtsafe/fmtsafe.go#L178)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Leftover code?
</blockquote></details>

Removed.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48040)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner, @irfansharif, and @RaduBerinde)

___
*[pkg/sql/rowexec/distinct.go, line 281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48040#-M5s5EXZAKafyH2Nyw1I:-M65rfFjBTbGfTD5Cnwv:b-pmshcg) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b5ee59716d243c42bdde7add795db3f7a1e15a0/pkg/sql/rowexec/distinct.go#L281)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

What about this: make two exported constants in the opt package.
Then let the code here choose which one to use based on a bool (or an int). Would this work?
</blockquote></details>

I'll file a separate issue to track this. It's a bit more hairy than it seems.

**Comment by knz** [comment]
> I'll file a separate issue to track this. It's a bit more hairy than it seems.

Filed as #48166

**Comment by knz** [comment]
bors r=irfansharif,ajwerner,RaduBerinde

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/rowexec/distinct.go, line 281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48040#-M5s5EXZAKafyH2Nyw1I:-M66IMjf30Cp5vD_qatx:b4uf48h) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b5ee59716d243c42bdde7add795db3f7a1e15a0/pkg/sql/rowexec/distinct.go#L281)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I'll file a separate issue to track this. It's a bit more hairy than it seems.
</blockquote></details>

Yes, sounds good, please assign to me. It will need to be plumbed through the optimizer, but I think it's a good change everywhere.

**Pull request merged**
