### PR TITLE
roachtest: skip expensive checks on alterpk-tpcc-500

### LINKED ISSUE #47887: roachtest: alterpk-tpcc-500 failed
[(roachtest).alterpk-tpcc-500 failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=1891353&tab=buildLog) on [master@056e32e84831f13b286fceb7681dd0cd2b00b4b4](https://github.com/cockroachdb/cockroach/commits/056e32e84831f13b286fceb7681dd0cd2b00b4b4):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/alterpk-tpcc-500/run_1
	cluster.go:2012,alterpk.go:159,alterpk.go:190,test_runner.go:753: output in run_082113.782_n4_workload_check_tpcc: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-1891353-1587540974-18-n4cpu16:4 -- ./workload check tpcc --warehouses 500 --expensive-checks {pgurl:1} returned: exit status 30
		(1) attached stack trace
		  | main.(*cluster).RunE
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2087
		  | main.(*cluster).Run
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2010
		  | main.registerAlterPK.func3
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/alterpk.go:159
		  | main.registerAlterPK.func5
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/alterpk.go:190
		  | main.(*testRunner).runTest.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:753
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
		Wraps: (2) 2 safe details enclosed
		Wraps: (3) output in run_082113.782_n4_workload_check_tpcc
		Wraps: (4) /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-1891353-1587540974-18-n4cpu16:4 -- ./workload check tpcc --warehouses 500 --expensive-checks {pgurl:1} returned
		  | stderr:
		  | I200422 08:21:15.431180 1 workload/tpcc/tpcc.go:372  check 3.3.2.1 took 64.437759ms
		  | I200422 08:21:23.024262 1 workload/tpcc/tpcc.go:372  check 3.3.2.2 took 7.592963715s
		  | I200422 08:21:25.554962 1 workload/tpcc/tpcc.go:372  check 3.3.2.3 took 2.530642228s
		  | I200422 08:22:29.803721 1 workload/tpcc/tpcc.go:372  check 3.3.2.4 took 1m4.248592717s
		  | I200422 08:24:29.445017 1 workload/tpcc/tpcc.go:372  check 3.3.2.5 took 1m59.641132712s
		  | I200422 08:32:11.372779 1 workload/tpcc/tpcc.go:372  check 3.3.2.6 took 7m41.927456866s
		  | Error: check failed: 3.3.2.6: pq: root: memory budget exceeded: 10240 bytes requested, 3781234688 currently allocated, 3781235712 bytes in budget
		  | Error: DEAD_ROACH_PROBLEM: exit status 1
		  | (1) DEAD_ROACH_PROBLEM
		  | Wraps: (2) Node 4. Command with error:
		  |   | ```
		  |   | ./workload check tpcc --warehouses 500 --expensive-checks {pgurl:1}
		  |   | ```
		  | Wraps: (3) exit status 1
		  | Error types: (1) errors.Cockroach (2) *hintdetail.withDetail (3) *exec.ExitError
		  |
		  | stdout:
		Wraps: (5) exit status 30
		Error types: (1) *withstack.withStack (2) *safedetails.withSafeDetails (3) *errutil.withMessage (4) *main.withCommandDetails (5) *exec.ExitError

```

<details><summary>More</summary><p>

Artifacts: [/alterpk-tpcc-500](https://teamcity.cockroachdb.com/viewLog.html?buildId=1891353&tab=artifacts#/alterpk-tpcc-500)
Related:
- #47877 roachtest: alterpk-tpcc-500 failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-provisional_202004210018_v20.1.0](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-provisional_202004210018_v20.1.0) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Aalterpk-tpcc-500.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by yuzefovich**
The data set is just too big for the 3 node cluster we're using, so
we're either hitting memory budget errors (usually) or fatal OOMs due to
problems with memory accounting - likely below SQL level - (rarely).

Fixes: #47887.

Release note: None

### CODE REVIEW

**Comment by rohany** [comment]
Is it possible to still run alterpk-tpcc 500 but don't run the expensive checks?

**Review by yuzefovich — COMMENTED** [review]
Good point, done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48067#-:-M5wglYD3qsPCkOnqIQY:bfbq99i)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rohany)

**Review by rohany — APPROVED** [review]
lgtm thanks!

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
