### PR TITLE
.git: improve the hooks

### PR DESCRIPTION
**Pull request by knz**
2nd commit motivated by 50b6aed77c0f324b31051eba651ec53cb2a631e1.

schermafdruk_2018-01-17_12-38-19

### CODE REVIEW

**Comment by benesch** [comment]
First commit LGTM! I'll defer to @jordanlewis on the second.

**Comment by dt** [comment]
Counterpoint: hard-wrapping the text manually, rather than letting the client do it at rendering, harms accessibility and the client’s ability to present best according to its constraints. For example, hard-wrapped text is much harder to read on a mobile device (either you reflow it and have every other line truncated, or you have to scroll to read each line.
example

**Comment by knz** [comment]
This change adds a linter that merely prints out a "warning" message. Our commit message linters are currently not prescriptive.

Also, consider the following. Suppose you two continue to not-wrap and let's suppose everyone is fine with that. Meanwhile, everyone else does wrap. For someone who is used to wrap, having a warning pop up when the editor messed up or something is actually a good thing. The overall utility of this linter is thus positive, regardless of whether we'd like to promote wrapping or not.

**Review by benesch — APPROVED** [review]
:shipit:

**Comment by knz** [comment]
thanks!

**Comment by BramGruneir** [comment]
I'd like to voice my opinion that I am still not a fan of 72 as our wrapping length and I don't think this went through enough of a vetting process.

You are free to implement your own warning on your own system and even share that with others.  By adding a warning to the repo, you are de facto making it the standard.

**Comment by knz** [comment]
The script says hi in a friendly fashion at 80 columns.

**Comment by BramGruneir** [comment]
Better than 72, but I still think it's prescriptive.

**Comment by knz** [comment]
I have performed some analytics on our repo and it is clear that most folk do not follow the "Release note" format recommended by the linter -- that's a very clear sign that the prescriptiveness of our commit message linter has very little influence on the team's behavior.

**Comment by BramGruneir** [comment]
That's sad.  It is quite easy to follow and extremely helpful.

**Pull request merged**
