### PR TITLE
lint: add Wrapf to the list of printf-like functions

### PR DESCRIPTION
**Pull request by RaduBerinde**

### CODE REVIEW

**Review by dt — APPROVED** [review]

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18090#-:-KstQdDdR7E0PSnziPY4:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Hm, I found the occurrence noticed in #18079, not sure why vet doesn't detect it

`ccl/sqlccl/csv.go:340:			return 0, errors.Wrapf(err, dataFile)`

**Comment by RaduBerinde** [comment]
I guess it doesn't warn about non-literal formats. Anyway, fixed that other one too.

**Review by dt — APPROVED** [review]
Thanks!

**Pull request merged**
