### PR TITLE
vendor: upgrade lib/pq to v1.10.6

### PR DESCRIPTION
**Pull request by catj-cockroach**
Previously lib/pq blocked the use of certificates/private keys if their
permissions made them readable to the owning group (0640 or u=rw,g=r).
This is required for the use of key material in Kubernetes when running
as a non-root user, as all secrets are mounted as being owned by root.

Release note: None

### CODE REVIEW

**Comment by catj-cockroach** [comment]
This PR may make more sense as a backport if #81943 is merged first

**Comment by rafiss** [comment]
I think this might be missing a `./dev generate bazel --mirror`

**Review by rafiss — CHANGES_REQUESTED** [review]
I think this might be missing a ./dev generate bazel --mirror

also, should we add a test that verifies that the behavior you desire is in effect? otherwise, the behavior might regress

**Review by rail — APPROVED** [review]
LGTM, :shipit:

**Review by rafiss — APPROVED** [review]

**Comment by catj-cockroach** [comment]
bors +r

**Comment by catj-cockroach** [comment]
blathers backport 22.1 21.2 21.1

**Comment by rafiss** [comment]
Just a heads up: there are no more planned 21.1 releases, so you probably don't need to do that backport.

**Pull request merged**
