### PR TITLE
colexecbase: extend support of casts

### PR DESCRIPTION
**Pull request by yuzefovich**
Addresses: #48135

See individual commits for details. After this PR we only need to add
more casts between natively supported types.

### CODE REVIEW

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67733)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/colexecbase/cast_tmpl.go, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67733#-Mf9YLo347IYcmLoH9G5:-Mf9X6p2--_2Pm7UYV8O:b-fxlvkk) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec33dc1dd17929ccf9b6665b3d863232d158b280/pkg/sql/colexec/colexecbase/cast_tmpl.go#L94)):*
> ```Go
> 		return true
> 	}
> 	if fromType.Family() == types.UuidFamily && toType.Family() == types.BytesFamily {
> ```

nit/question: Why is this not the case for `UUID` -> 'String`? Can `String` have a width?
___
*[pkg/sql/colexec/colexecbase/cast_tmpl.go, line 351 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67733#-Mf9XIIMDpYvjaX1rDea:-Mf9XIIMDpYvjaX1rDeb:b23gn2r) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec33dc1dd17929ccf9b6665b3d863232d158b280/pkg/sql/colexec/colexecbase/cast_tmpl.go#L351)):*
> ```Go
> 			c.da.AllocSize = n
> 		}
> 		if cap(c.scratch) < maxIdx {
> ```

I think `c.scratch` needs to be resliced when the capacity is sufficient, right?
___
*[pkg/sql/colexec/colexecbase/cast_tmpl.go, line 400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67733#-Mf9j3zB46aIxY3dcdk-:-Mf9j3zB46aIxY3dcdk0:b1rxuj3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec33dc1dd17929ccf9b6665b3d863232d158b280/pkg/sql/colexec/colexecbase/cast_tmpl.go#L400)):*
> ```Go
> 	}
> 	converted := scratch[idx]
> 	if hasNulls {
> ```

[nit] could fold these conditions
___
*[pkg/sql/colexec/execgen/cmd/execgen/cast_gen.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67733#-Mf9hCe5B4h5NoDh00Zx:-Mf9hCe5B4h5NoDh00Zy:bgqgcub) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec33dc1dd17929ccf9b6665b3d863232d158b280/pkg/sql/colexec/execgen/cmd/execgen/cast_gen.go#L36)):*
> ```Go
> 
> 	setValues := makeFunctionRegex("_CAST_TUPLES", 2)
> 	// We have to be a bit tricky with this replacement because we want to
> ```

[nit] We might be able to avoid this sort of thing by using execgen. Though, feel free to disregard this if you don't think it's worth it; the code that generates the code isn't too important.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67733)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[pkg/sql/colexec/colexecbase/cast_tmpl.go, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67733#-Mf9YLo347IYcmLoH9G5:-MfAMpmx1cdj-OxZNytl:b-6pgnxp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec33dc1dd17929ccf9b6665b3d863232d158b280/pkg/sql/colexec/colexecbase/cast_tmpl.go#L94)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

nit/question: Why is this not the case for `UUID` -> 'String`? Can `String` have a width?
</blockquote></details>

`types.String` implicitly also represents weird string-like special types (like `char` and `"char"`, etc) which do require some truncation. At the moment our "resolution" is based on type families (and widths for IntFamily), so all special string-like types are handled by the same operator. In the future we might lift up the resolution to be based on Oids (which will speed up the casts), but it doesn't seem worth it at the moment.

Also, even if there weren't such complications, `UUID`s are represented differently when they have been cast to strings. UUIDs are essentially `[16]byte`, but when we cast them to string, we get `xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx` which is longer and also encoded. Thus, we do need to first convert `[16]byte` to a `UUID` and then stringify it.
___
*[pkg/sql/colexec/colexecbase/cast_tmpl.go, line 351 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67733#-Mf9XIIMDpYvjaX1rDea:-MfAOTliEhHaH-IT4HV-:b8gj3mz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec33dc1dd17929ccf9b6665b3d863232d158b280/pkg/sql/colexec/colexecbase/cast_tmpl.go#L351)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

I think `c.scratch` needs to be resliced when the capacity is sufficient, right?
</blockquote></details>

Good catch, fixed.
___
*[pkg/sql/colexec/colexecbase/cast_tmpl.go, line 400 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67733#-Mf9j3zB46aIxY3dcdk-:-MfAOeWT7Dj30hCsvXuG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec33dc1dd17929ccf9b6665b3d863232d158b280/pkg/sql/colexec/colexecbase/cast_tmpl.go#L400)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] could fold these conditions
</blockquote></details>

Done.
___
*[pkg/sql/colexec/execgen/cmd/execgen/cast_gen.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67733#-Mf9hCe5B4h5NoDh00Zx:-MfAOluuCPzzlqeEaj0_:b-pxwu9e) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec33dc1dd17929ccf9b6665b3d863232d158b280/pkg/sql/colexec/execgen/cmd/execgen/cast_gen.go#L36)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] We might be able to avoid this sort of thing by using execgen. Though, feel free to disregard this if you don't think it's worth it; the code that generates the code isn't too important.
</blockquote></details>

Hm, I don't see how the execgen would help us here - `_CAST_TUPLES` does rely heavily on the text/template stuff. In particular, `$fromInfo` is a template variable that we want to propagate into the template invocation. It also propagates the overload via `.Global`. I think that the execgen isn't currently capable of these things (at least without an involved refactor).

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67733)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @yuzefovich)

___
*[pkg/sql/colexec/colexecbase/cast_tmpl.go, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67733#-Mf9YLo347IYcmLoH9G5:-MfAXktmCgNgMQZfq1Bk:bcr5s31) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec33dc1dd17929ccf9b6665b3d863232d158b280/pkg/sql/colexec/colexecbase/cast_tmpl.go#L94)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

`types.String` implicitly also represents weird string-like special types (like `char` and `"char"`, etc) which do require some truncation. At the moment our "resolution" is based on type families (and widths for IntFamily), so all special string-like types are handled by the same operator. In the future we might lift up the resolution to be based on Oids (which will speed up the casts), but it doesn't seem worth it at the moment.

Also, even if there weren't such complications, `UUID`s are represented differently when they have been cast to strings. UUIDs are essentially `[16]byte`, but when we cast them to string, we get `xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx` which is longer and also encoded. Thus, we do need to first convert `[16]byte` to a `UUID` and then stringify it.
</blockquote></details>

Got it, thanks.
___
*[pkg/sql/colexec/colexecbase/cast_tmpl.go, line 325 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67733#-MfAYXQw75jxdenLSH14:-MfAYXQw75jxdenLSH15:b-o5ynve) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8aa0ab4687827475b32eb986b3d25e9f7382864/pkg/sql/colexec/colexecbase/cast_tmpl.go#L325)):*
> ```Go
> 
> 	scratch []tree.Datum
> 	da      rowenc.DatumAlloc
> ```

Should we be accounting for these somewhere? (maybe we are, and I'm just not seeing it)
___
*[pkg/sql/colexec/colexecbase/cast_tmpl.go, line 358 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67733#-MfAZKEiBV_1Ew6-W8Qe:-MfAZKEiBV_1Ew6-W8Qf:b-kg3j7w) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8aa0ab4687827475b32eb986b3d25e9f7382864/pkg/sql/colexec/colexecbase/cast_tmpl.go#L358)):*
> ```Go
> 		scratch := c.scratch
> 		colconv.ColVecToDatum(scratch, inputVec, n, sel, &c.da)
> 		if sel != nil {
> ```

Shouldn't we always ignore the selection?
___
*[pkg/sql/colexec/execgen/cmd/execgen/cast_gen.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67733#-Mf9hCe5B4h5NoDh00Zx:-MfAWt6f78GyCu2TPoKt:be6tvtu) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec33dc1dd17929ccf9b6665b3d863232d158b280/pkg/sql/colexec/execgen/cmd/execgen/cast_gen.go#L36)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Hm, I don't see how the execgen would help us here - `_CAST_TUPLES` does rely heavily on the text/template stuff. In particular, `$fromInfo` is a template variable that we want to propagate into the template invocation. It also propagates the overload via `.Global`. I think that the execgen isn't currently capable of these things (at least without an involved refactor).
</blockquote></details>

I thin you should be able to leave the `$fromInfo` templating and whatever else - execgen inlining should preserve those comments. But, again, it doesn't really matter.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67733)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[pkg/sql/colexec/colexecbase/cast_tmpl.go, line 325 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67733#-MfAYXQw75jxdenLSH14:-MfAbNt4DM5BLN74PsIy:b-u3ncdq) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8aa0ab4687827475b32eb986b3d25e9f7382864/pkg/sql/colexec/colexecbase/cast_tmpl.go#L325)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Should we be accounting for these somewhere? (maybe we are, and I'm just not seeing it)
</blockquote></details>

No, we typically don't account for objects within `DatumAlloc`s. We could (and probably should) be accounting for the temporary converted datums stored in `c.scratch`, but so far we haven't done so. I filed #67889 to not forget about this shortcoming, but I don't think it's too important to address it in this PR.
___
*[pkg/sql/colexec/colexecbase/cast_tmpl.go, line 358 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67733#-MfAZKEiBV_1Ew6-W8Qe:-MfA_Ir93vjNb6NmfgQ8:b-tu0p4o) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8aa0ab4687827475b32eb986b3d25e9f7382864/pkg/sql/colexec/colexecbase/cast_tmpl.go#L358)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Shouldn't we always ignore the selection?
</blockquote></details>

No, we're consciously using `sel` here. `colconv.ColVecToDatum` performs the conversion without deselection (we have another version for that), all slots in `scratch` that are not in `sel` are left unchanged, and the same goes for all slots in `outputCol`. I left it this way because all other cast operators work in this manner (I don't remember but I might have run into test issues before my PTO if the deselection is performed).

Hm, now that I've typed it out I think we can perform the conversion with deselection but then put the datums from the scratch into the corresponding slots, without performing deselection on the output vector (because that would require copying over all other vectors too).
___
*[pkg/sql/colexec/execgen/cmd/execgen/cast_gen.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67733#-Mf9hCe5B4h5NoDh00Zx:-MfAeP3rDMM7OrVCQ2W8:b-3kxy3l) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec33dc1dd17929ccf9b6665b3d863232d158b280/pkg/sql/colexec/execgen/cmd/execgen/cast_gen.go#L36)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

I thin you should be able to leave the `$fromInfo` templating and whatever else - execgen inlining should preserve those comments. But, again, it doesn't really matter.
</blockquote></details>

Indeed, good point, added another commit to refactor the template.

**Review by DrewKimball — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67733#-:-MfAulbf1ngXVZHYvqW8:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

**Comment by yuzefovich** [comment]
I rebased on top of master and squashed the last three commits into one.

TFTR!

bors r+

**Pull request merged**
