### PR TITLE
release-24.1: kvserver: split snapshot SSTables for mvcc keys into multiple SSTs

### PR DESCRIPTION
**Pull request by itsbilal**
Backport 1/1 commits from #127997.

/cc @cockroachdb/release

Release justification: Performance improvement that has baked in master for a while, that was originally identified in a support escalation.

---

Previously, we'd only create one sstable for all mvcc keys in a range when ingesting a rebalance/recovery snapshot into Pebble. This increased write-amp in Pebble as more sstables would have to be compacted into it (or the sstable then split into smaller ones in Pebble), and had other consequences such as massive filter blocks in the large singular sstable.

This change adds a new cluster setting,
kv.snapshot_rebalance.max_sst_size, that sets the max size of the sstables containing user/mvcc keys in a range. If an sstable exceeds this size in multiSSTWriter, we roll over that sstable and create a new one.

Epic: CRDB-8471
Fixes: #67284

Release note (performance improvement): Reduce the write-amplification impact of rebalances by splitting snapshot sstable files into smaller ones before ingesting them into Pebble.

### CODE REVIEW

**Comment by itsbilal** [comment]
This wouldn't compile until the Fragmenter and MakeInternalKeyTrailer are exported from Pebble, which I'll do momentarily.

**Comment by jbowens** [comment]
Noting that we'll need the eventual fix to #129026 before merging any backport. I think regardless, we'll want it to bake on master for a while.

**Comment by itsbilal** [comment]
Backported #129088. This should be ready for another look.

**Review by jbowens — APPROVED** [review]

**Comment by itsbilal** [comment]
TFTR!

**Pull request merged**
