### PR TITLE
sql: better distribute distinct processors

### PR DESCRIPTION
**Pull request by yuzefovich**
**sql: better distribute distinct processors**

The distinct processors are planned in two stages - first, a "local"
stage is planned on the same nodes as the previous stage, then,
a "global" stage is added. Previously, the global stage would be planned
on the gateway, and this commit changes that to make it distributed - by
planning "global" distinct processors on the same nodes as the "local"
ones and connecting them via a hash router hashing the distinct columns.

Release note: None

**sql: implement ConstructDistinct in the new factory**

Addresses: #47473.

Release note: None

### CODE REVIEW

**Review by asubiotto — APPROVED** [review]
It's unclear to me whether hashing the output of the first stage is necessarily an improvement with higher inter-node latencies. This is probably a decision that should be left up to the optimizer. I'm not opposed to merging this though if it makes it easier for the new spec planning work to implement distinct construction.

:lgtm: 

> Reviewed 4 of 6 files at r1, 2 of 2 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52098#-:-MDougVhCKNYCDc2_x_A:bwa25q9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/distsql_physical_planner.go, line 2914 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52098#-MDouEqD0gLw4Il6EL2T:-MDouEqD0gLw4Il6EL2U:b-k7lskx) ([raw file](https://github.com/cockroachdb/cockroach/blob/48dc83e3f902f29202ee9858335d17e5151750de/pkg/sql/distsql_physical_planner.go#L2914)):*
> ```Go
> 
> 	// Add distinct processors local to each existing current result processor.
> 	// TODO(arjun): This is potentially memory inefficient if we don't have any
> ```

`s/arjun/yuzefovich` :smile:?
___
*[pkg/sql/physicalplan/physical_plan.go, line 1171 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52098#-MDtBJ54-5RbL_Kd9zT7:-MDtBJ54-5RbL_Kd9zT8:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7fa59305910a07ffcf1fe83f587c6a44996caa2/pkg/sql/physicalplan/physical_plan.go#L1171)):*
> ```Go
> // INTERSECT and EXCEPT plans.
> //
> // TODO(abhimadan): If there's a strong key on the left or right side, we
> ```

ditto

**Review by yuzefovich — COMMENTED** [review]
The first commit is not necessary for the new factory, but I disagree that it is not improvement. The thing is that in the old factory if one stage is local, then all consequent stages will also be local, and those later stages might contain joins or aggregations.

For example, for this query we can now run distributed sort and use ordered synchronizer to merge the streams (before https://cockroachdb.github.io/distsqlplan/decode.html#eJy8lVGL2kAUhd_7Ky73ySUjcSZx1YFC2jVLA1a3UWjLkocxGbaBbGInI7SI_73EFHeVOsmi9fHOzJnv3JPLZIPlzww5zv2Jf7eAtcrgPpx9hkf_28PkQzCFzjiYL-ZfJjfw90hVB9O7BQgCy_pwIrSAr5_80IdOR4AFyxuwIOY8mC6GN_Ae2ABm4dgP4eN3WBIQERLMi0ROxbMskT8iRYIMCTpI0EWCfYwIrlQRy7IsVHVksxMEyS_kPYJpvlrrajkiGBdKIt-gTnUmkeNCLDMZSpFIZfeQYCK1SLMdpjLqrVT6LNRvJDhfibzk0LUpiDwBCoX-IRUSvE8zLRWHTsejYIHHqn4853VDvC6Q4GytOXiUeAyjLcFirV-8lVo8SeR0S9r7H6elTvNY2_1D8zWC4EwlUsmkiclOMl9QRX3VMcciHrMw2prM0d5Z7py3JDIvlJbKpvQIySziUeskwz1g0PZTQ9tMjU27Nrvq3DR0sP80txecG9Y-NdYqNda1naum1tDBPrXBBVNz2qfmtErN6druVVNr6GCf2vCCqbntU3NbpeZ27f5VU2voYJ_a6D-97P9ghrJcFXkpD4inbu5VT75MnmT9myiLtYrlgyriHaYuZzvdbiGRpa53aV0Eeb1VGXwtpkYxOxDTYzEzih0z2THbZma1a1T3zeL-OU3fGsUDM3lwDnloFI_M5NE5ZNowY01D9rYpi7bv_gQAAP__AKVrVw==,
after https://cockroachdb.github.io/distsqlplan/decode.html#eJy8ltFr4koUxt_vX3E4TxZH4kxitYELube1rNDVrgq7S_FhNEMrWONORthS_N8Xzao16pykhjxG882c830_PvKO8a8Z-jhoP7Rvh7DUM7jv977CU_vH48N_nS5U7jqD4eDbwxX8fWX93OneDkEyGCcvh9JI-P6l3W9DpSKhCuMrqMLE9zvdYesK_gXRhF7_rt2H_3_CmIEcIcN5FKqufFUx-k_IkaFAhi4y9JBhA0cMFzqaqDiO9PqV942gE_5Gv85wOl8szfrnEcNJpBX672imZqbQx6Ecz1RfyVBpp44MQ2XkdLa5Zj1osNDTV6nfkOFgIeexDzWHg5yHwCEyL0ojw_vpzCjtQ6UScKhCINb7BO7HhfzkARn2lsaHgLNA4GjFMFqa_Wyxkc8Kfb5i2ee_m8ZmOp8Yp3E4fHIFw54OlVbh6Tv3x4zf4EXGL6fOGK32o4mzo-2PipIb00dVWSCqyWFnd-D1Tyyxn87NY9wg0kZph6d9E1UW8OrZO7xPO7A7-MQw3agWLRxxuP65ERoHI_DsfPMsfDu85ohSCSc22NFxXT7hvHDCeYGEE8ZtCU_7lotwkR0vkQkvUXPcUvEiNthF0ywfL1E4XqJAvAjjtnilfcuFl5sdLzcTXm7N8UrFi9hgF02rfLzcwvFyC8SLMG6LV9q3XHh52fHyMuHl1ZxGqXgRG-yiuSkfL69wvLwC8SKM2-KV9u3Tn38n7uireBHNY5Xpq66-tkaFzyqxM46WeqIedTTZXJM89ja6zQ-hik3yL08eOvPkr_WAH8U8LeYfxeJAzPOJm5eIOb9I3bhIfWNXC6vhrt1w1yr27Dd7VrEgsm5Y1dd28fUloNjFBCh2MQUKoSZAIdQEKE2r4S274a1LQLmxd0KdKIWjSsnVCnY1VQt2NdkLhJwqBkJOBM6PiuXQd0H4bm8WInNurxbuEZcflUuu0O1qKnS7mgydkFOhE3IqdHuvcqJY-VHH5Ard3jGcKBl-1DK5QrerqdDtajJ0Qk6FTsip0O0NK4iGFfaPtnToo9U_fwIAAP__UdBziQ==).

I agree that in some cases the first commit might not be beneficial, but I think in most cases it is.

TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52098#-:-MDu36ah-mzaPn6_4Ztc:b-b1aogj)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

___
*[pkg/sql/distsql_physical_planner.go, line 2914 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52098#-MDouEqD0gLw4Il6EL2T:-MDu2Y9h-STI50hLQ3RH:bmdi56c) ([raw file](https://github.com/cockroachdb/cockroach/blob/48dc83e3f902f29202ee9858335d17e5151750de/pkg/sql/distsql_physical_planner.go#L2914)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

`s/arjun/yuzefovich` :smile:?
</blockquote></details>

:)

I think this particular TODO doesn't make sense, removed.
___
*[pkg/sql/physicalplan/physical_plan.go, line 1171 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52098#-MDtBJ54-5RbL_Kd9zT7:-MDu35gd413jk9aVO3HE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7fa59305910a07ffcf1fe83f587c6a44996caa2/pkg/sql/physicalplan/physical_plan.go#L1171)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Comment by yuzefovich** [comment]
Merge skew.

bors r-

**Comment by yuzefovich** [comment]
It's not a merge skew and rather a bug in the new factory.

Hey @RaduBerinde, there is a bug with this block that got exposed in this PR:
https://github.com/cockroachdb/cockroach/blob/1d12a54a77971781775aa11697159d2914b05cd9/pkg/sql/distsql_spec_exec_factory.go#L360-L366

Here is the expected [plan](https://cockroachdb.github.io/distsqlplan/decode.html#eJzUWlFv4kYQfu-vWO1ToprYu7ZJsHRS0gtVOaVwhTz0euLBgW2wcGxqL8lFUf57ZThEjLkdGx-ezVsIXvPNfrPffDP2C03_C6lHR92b7sdbskxC8vtw8Cf52v37881Vr0-u-lc3X_7pkpPr3uh29NfNKfl-afa51_94S07mT2dPp-tl80fyadDrk_kTGfTJ_PFsTj6Q7HsyGF53h-S3L6tPY2rQKJ6Kvv8gUup9pYwalFOD2tSgDjWoS8cGXSTxRKRpnGSXvKwW9KbfqGcZNIgWS5n9e2zQSZwI6r1QGchQUI_e-nehGAp_KhLTogadCukH4epn5o-XiyR48JNnatDRwo9Sj7TM7IcHS-mRywzGnS8nM5GSeCkX2T-zW8jlInzzr-yyVIRiIoPHQD57xDqzsstS6YchkcGD8IiV0vGrQddL1gFsAN49k5mfzvLQLhkdv45X97gX1GOvxmERt3cifipGbLK3MXNtYuY_jHl7n2UUJ1ORiGnuTuNsJXTJno37w09nn-IgEonJdlIlFP_Kk0t2-iEJ7merv37WjolvYrKUQRz9aNe2O2JXyYLrIJVBNJEmcwvbfFzA1Wh2atCsCptbDYe9DcmtwtMoTqRITF5g6dfG8LZLULCPgBXIvSz041a8MO0dCkpE49aP5jwXDSuvlQyuDiZvmbb29aFCzOcl6kMuZl3rA2u4PjDt6wOQBdv60H5H9aEazcr6wDSpDwBPm_pQYAmrPvDy6sJLKKrdMh3tFbVCzBclFDUXs66KyhtWVK69ogJZsFXU83ekqNVoVioq10RRAZ42ilpgCUtR7fLqYpdQVKdlutoraoWYOyUUNRezropqN6yotvaKCmTBVlEv3pGiVqNZqai2JooK8LRR1AJLWIrqlFcXp4Siui3t9bRCxC6spy2TET-aEkZiOROJ9srqNKysjvbKCuTDVlk770hZq9GsVFZHE2UFeNooa4ElHabDe_AORbqIo1Tsnri9d7YyisT0Xqz5TONlMhGfk3iy-pn1x8Fq3WpKMhWpXH_L1x960earVPqy7IjZKi1OVSB19IPE3DqYymt4JeaYfvvEzzEwsQoZznWA1NEP0k6GV8R0aIYDzDH99mknwxvCxHcxWW8x2TlI1u5iWxmQg6FsakgMRdkATCjKpsbEbQ0xoVRvR3k-XPX5cJWL2_l4dhe31Sczn8lWM7txrp_jU0NCyRk1pHqO70jMoegigKmWLh5aPy70c3xqSCiOTw2pnuM7DiYcxwdgquX4Ds3wjrKuMEtd0pi6Tavl-Q721UCLXUvcDm5AAFA4_SzQZKPYPggUSg1nhWYtf0w4cEzUfVUbJSMBf42yzWpMONQD_RqKf4PIw9E4ABSOxhVaNnwLB2DCmdqpMeGYOIi8Wi7u4DQHQKEM7ph6uMDaQIEqjBc08HFqTDjDOwgUSpcKgELycQAonGJeGDLkj8kFcEwKHZwGPq7QwWng49SYalF_pH1C8nEAeTgaB4BC8XG8yusFTT0tq_J-QUPuBMCE4-Mg8lCmcRAonAew6kEDBwYNvDBowPdxACYcHweBwtE4Nah6Pu5gQQFAofg4Xhg15I-JAxwT9XNcFB_HCx3cz_NxR8KEQ70aE46Pg8jD0TgAFI7GAW0himdSY0KZxwGYkHwcQB6OjwNA4fg49aCBA4MGrn5UjOPjgMf8OBoHgMLROOBBP8o8DgKFMpTh6tcPbOD1A7vQwiH4uPHrL_8HAAD__7oqa9U=) and the actual [plan](https://cockroachdb.github.io/distsqlplan/decode.html#eJzMmF1vo0YUhu_7K0bnKlFxYPiIs0grJd24qlepvbVz0e2KCwLTGJkAZYZ4o8j_vQLvagPOMoyJmbkzH2d4ztE75_WcZ6D_xeDCcnIz-XCLijxGvy_mf6Ivk78_3VxNZ-hqdnXz-Z8JOrmeLm-Xf92com-vltfT2YdbdLLenG1Od2HrR_RxPp2h9QbNZ2j9eLZG71H5HM0X15MF-u1zdeWBBkkakpn_QCi4XwCDBiZoYIEGNmjggKdBlqcBoTTNy1eeq4Bp-BVcQ4MoyQpW3vY0CNKcgPsMLGIxARdu_buYLIgfklw3QIOQMD-Kq8-sHy-zPHrw8yfQYJn5CXXRSC8_PC-Yiy5LjDufBStCUVqwrLxZLsGKLH5xq3yNkpgELHqM2JOLjDOjfI0yP44Rix6IiwwK3laDXcguge-Ad09o5dNVHe0Sg7f1qjXuCbh4qx2W8Xkj481-xjp-mbOpTM7mT3P-sU6RpHlIchLWVvLKSN4rrxTuD5-uPqZRQnIdN6QSk3_ZySU-fZ9H96vq11tVjHwlQcGiNPlZ1X5UxOpRkVfSnaWjNNOxU8-0QypO_1RsEUFfR5RFScB0fL6nmE61fwNgRwR4measFNG4ifvrYLznNV7cvWNgfo_UzZFuKd8lBXIed-iStZxV7ZJ44C6Jle-SZncVmB2Ub410W3nlC-R80UH5tZxVVb45sPJN5ZVvdVeB1UH59kh3lFe-QM7vOii_lrOqyrcGVr6lvPLt7iqwOyjfGSmve4GMHb7uRzpGfhIijFK2IrnyO8AeeAfYyu8AzvlkQWiWJpQ0K_PqykZZDhLek115aVrkAfmUp0H1md3lvIqr_n-GhLLdU3N3MU2-P6LMZ13PmEZnEYkgXaiHhHEfpu57TYjJVrBOYxlMWEDhpgpIF-ohNRQuyHSowjlMtoJ1GstgMptMxksmq77pmsFWa3C9xkYz2G4NdtqDndZgXN8GxjClPFfPDtuRpNhhO1I_OzwSkxQ75DD1ssNDm-pYPTtsR5Jih-1I_ezwSExS7JDD1MsOD1X4hYgdDoP0Tj1baUeSYivtSHJshcPUy1aOoyZJpyyRQcJQ_9VFJglqMMlxFh5UL2s5-PQnNEwYqlJ75z_55oL3zn_y3YXD1MtejlQnOf7Cg5JybuFByXGYvUmFAg7TztTLYQ6WeTuTJIfhQMmZ5XGg5DhM-0xNjsPsjerezmGOxCTlAMNhkuQwHCg5DsOBkuMwItPfobq5yPh3qBYlNP9VBEqOwwhNgIeC2hvaSXAYb_vL_wEAAP__t6mY5Q==). Because we have a projection on top of the hash joiner which has `reqOrdering=nil`, we merge all streams. This breaks our assumption that `nil` `reqOrdering` is a sign that we have a top-level projection. Do you have an idea of how to fix this?

**Comment by RaduBerinde** [comment]
Hm. Yes, I hate that hack. I tried moving the top-level projection in `ConstructPlan` but I ran into some issues. I will add a separate new exec.Factory primitive, it will be a good example for when the optimizer will make more distribution-related decision. Let me work on that today.

**Comment by yuzefovich** [comment]
Thanks! I would say fixing this is not super urgent since we've decided to temporarily postpone the work on the new factory until the feature cut off time (for a milestone or so) in order to get some vectorized features in (because we won't be able to finish distsql spec work before the cut off anyway), but I appreciate your willingness to jump in.

**Comment by yuzefovich** [comment]
Radu fixed the bug, and now the build should be green.

bors r+

**Pull request merged**
