### PR TITLE
roachpb: delete NoopRequest and NoopResponse

### PR DESCRIPTION
**Pull request by nvb**
This change removes the `NoopRequest` type and it's corresponding
`NoopResponse` type. This helps to eliminate a number of special
cases scattered throughout our code. The request type has gone
unused since July 2017, so 2.1 clusters will never need to worry
about encountering an instance of one.

### CODE REVIEW

**Review by bdarnell — APPROVED** [review]
> Reviewed 17 of 17 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27352)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by nvanbenschoten** [comment]
TFTR!

bors r+

**Comment by minglinlu** [comment]
This issue is also good for knowing how to create a new request.
After comparison, I summary that we need to modify 3 files:
`api.proto`
`api.go`
`method.go`
And run `make generate`, there would be some other files auto generated.
And the, you could use your own XxxRequest struct.

**Comment by minglinlu** [comment]
This issue is also good for knowing how to create a new request.
After comparison, I summary that we need to modify 3 files:
`api.proto`
`api.go`
`method.go`
And run `make generate`, there would be some other files auto generated.
And the, you could use your own XxxRequest struct.

**Pull request merged**
