### PR TITLE
geoviz: add a visualization tool for geospatial data

### PR DESCRIPTION
**Pull request by otan**
This PR adds a visualization tool for looking at geography and S2 data.
It's pretty rudimentary right now, but will help immensely with
visualizing and explaining concepts especially for the RFC.

Release note: None

image

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
This is nice! I've made a first pass, and have some preliminary questions.

> Reviewed 1 of 2 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47502#-:-M5JJnnd4ZwBGfhvn2hz:b-vs33vb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/cmd/geoviz/main.go, line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47502#-M5JI3Cc5Fa7kWjQvKhQ:-M5JI3Cc5Fa7kWjQvKhR:b9h9dy1) ([raw file](https://github.com/cockroachdb/cockroach/blob/efa268d59bab63c9b97bb74b38d44e6bf3de18af/pkg/cmd/geoviz/main.go#L78)):*
> ```Go
> func main() {
> 	http.HandleFunc("/", handleIndex)
> 	http.HandleFunc("/load", handleLoad)
> ```

`handleLoad` seems to be handling the form mentioned in `index.tmpl.html`. It is not clear to me what `handleIndex` is for.
___
*[pkg/cmd/geoviz/templates/index.tmpl.html, line 91 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47502#-M5JFcyQ95EN05wfZFHv:-M5JFcyQ95EN05wfZFHw:b1ht6qk) ([raw file](https://github.com/cockroachdb/cockroach/blob/efa268d59bab63c9b97bb74b38d44e6bf3de18af/pkg/cmd/geoviz/templates/index.tmpl.html#L91)):*
> ```HTML
>           zoom: 2
>         });
>         $("#form-geoviz-input").submit();
> ```

my javascript is poor -- what is the `$("#form-geoviz-input")` referencing?

can you add a comment for each code block in this file?
___
*[pkg/geo/geo.go, line 213 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47502#-M5JDRGq9F525Zkx0ltf:-M5JDRGq9F525Zkx0ltg:b1yyaz7) ([raw file](https://github.com/cockroachdb/cockroach/blob/efa268d59bab63c9b97bb74b38d44e6bf3de18af/pkg/geo/geo.go#L213)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 	crossProduct := a.X()*b.Y() - a.Y()*b.X() +
> 		a.Y()*c.X() - a.X()*c.Y() +
> 		b.X()*c.Y() - c.X()*b.Y()
> 	return crossProduct > 0
> ```
</details>


is this the vector ab x vector bc, and if so can you add a code comment.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47502)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/cmd/geoviz/main.go, line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47502#-M5JI3Cc5Fa7kWjQvKhQ:-M5N5HSdCAwCp5lKDMn2:b51kggp) ([raw file](https://github.com/cockroachdb/cockroach/blob/efa268d59bab63c9b97bb74b38d44e6bf3de18af/pkg/cmd/geoviz/main.go#L78)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

`handleLoad` seems to be handling the form mentioned in `index.tmpl.html`. It is not clear to me what `handleIndex` is for.
</blockquote></details>

added comments
___
*[pkg/cmd/geoviz/templates/index.tmpl.html, line 91 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47502#-M5JFcyQ95EN05wfZFHv:-M5N5v8FDG6RAfgO2M_g:b-376pbp) ([raw file](https://github.com/cockroachdb/cockroach/blob/efa268d59bab63c9b97bb74b38d44e6bf3de18af/pkg/cmd/geoviz/templates/index.tmpl.html#L91)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

my javascript is poor -- what is the `$("#form-geoviz-input")` referencing?

can you add a comment for each code block in this file?
</blockquote></details>

this is jquery -- "#form-geoviz-input" means "match anything with "id=form-geoviz-input"
___
*[pkg/geo/geo.go, line 213 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47502#-M5JDRGq9F525Zkx0ltf:-M5N6-st1lWav90sVdur:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/efa268d59bab63c9b97bb74b38d44e6bf3de18af/pkg/geo/geo.go#L213)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> ```
> 	crossProduct := a.X()*b.Y() - a.Y()*b.X() +
> 		a.Y()*c.X() - a.X()*c.Y() +
> 		b.X()*c.Y() - c.X()*b.Y()
> 	return crossProduct > 0
> ```

is this the vector ab x vector bc, and if so can you add a code comment.

</blockquote></details>

Done.

**Comment by otan** [comment]
abandoning this for now.

**Comment by otan** [comment]
actually nah ill suck up the rebase

**Review by sumeerbhola — APPROVED** [review]
sorry about the long delay
:lgtm: 

> Reviewed 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47502#-:-M8pdp2n4tk-ofYRmLbA:b-3nyw8d)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Comment by otan** [comment]
all geezy!

bors r=sumeerbhola

**Pull request merged**
