### PR TITLE
storage: make load-based replica rebalancing decisions at the store level

### PR DESCRIPTION
**Pull request by a-robinson**
Built on top of https://github.com/cockroachdb/cockroach/pull/28340, which is where the first 3 commits are from. This is still somewhat incomplete, in that it's missing unit tests and I'm only just now running tpc-c 10k on it. Sending out now to start the discussion of whether to include it in 2.1, since we're obviously very late in the intended development cycle.

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm: but mostly just :man_scientist: :dog: on the `StoreRebalancer` changes. @BramGruneir do you mind taking a look at that?

> Reviewed 6 of 6 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28852#-:-LKvuiUK4tXiNgblbqw5:bb0h9af)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/allocator.go, line 383 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28852#-LKvgd5SBkMf3KNzLbvB:-LKvgd5T585RaXO-COJI:b-mt7980) ([raw file](https://github.com/cockroachdb/cockroach/blob/861f228c4a6a96d5777015998bb58cda8ee68b0b/pkg/storage/allocator.go#L383)):*
> ```Go
> 		existingReplicas: len(existing),
> 		aliveStores:      aliveStoreCount,
> 		throttledStores:  throttledStoreCount,
> ```

nit: always 0, right?

**Review by a-robinson — COMMENTED** [review]
Thanks @nvanbenschoten. Waiting on @BramGruneir isn't ideal since he's out this week, but I'll at least wait until I have metrics/debugging hooked up before merging, and will definitely wait for his review before cherrypicking.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28852#-:-LKwzpgkDx35DYxOUseo:b-1t3c06)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/storage/allocator.go, line 383 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28852#-LKvgd5SBkMf3KNzLbvB:-LKwzgZSBeXrJ4Z6qkhq:b-ro5tmj) ([raw file](https://github.com/cockroachdb/cockroach/blob/861f228c4a6a96d5777015998bb58cda8ee68b0b/pkg/storage/allocator.go#L383)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: always 0, right?
</blockquote></details>

True, although I'd prefer to leave as is rather than assume it's always 0 in case the condition above ever gets removed.

**Comment by a-robinson** [comment]
Plans for improving `RelocateRange` outlined in https://github.com/cockroachdb/cockroach/issues/29130

**Review by BramGruneir — APPROVED** [review]
Gave this another full read through. 

LGTM

> Reviewed 3 of 3 files at r1, 9 of 9 files at r2, 3 of 3 files at r3, 1 of 6 files at r4, 13 of 13 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28852#-:-LLjsfWFE22t9SshjpQ6:b-yiv9ln)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by a-robinson** [comment]
TFTR!

bors r+

**Pull request merged**
