### PR TITLE
pgwire: reduce allocations when writing CHAR(N) datums

### PR DESCRIPTION
**Pull request by mgartner**
`ResolveBlankPaddedCharBytes` has been replaced with a more efficient
method of padding `CHAR(N)` datums with trailing spaces.

Epic: None

Release note: None

### CODE REVIEW

**Review by DrewKimball — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132338)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/pgwire/types.go` line 529 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132338#-O8u2KimEFas9A1-J9e6:-O8u2KimEFas9A1-J9e7:b-zdjnq8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1cd184ff15c354e68a04dc17aaf85436f57e3414/pkg/sql/pgwire/types.go#L529)):*
> ```Go
> 		v = []byte{0}
> 	}
> 	b.putInt32(int32(len(v)))
> ```

Will this length be wrong now that the padding happens after it's written?

**Review by rafiss — COMMENTED** [review]
could we see results of the improvement if we used `benchstat` on `pgwire.BenchmarkEncodings`? `pgwire.BenchmarkWriteTextString` also looks like it could be duplicated and modified slightly so that it tests `CHAR` instead of `TEXT`.

**Review by mgartner — COMMENTED** [review]
I opted for your latter suggestion, since `BenchmarkEncodings` does not currently test encoding from a columnar vector.

`BenchmarkWriteBinaryColumnarChar` shows the improvement:

```
name                     old time/op    new time/op    delta
WriteBinaryColumnarChar    52.1µs ± 0%    22.4µs ± 1%   -57.03%  (p=0.008 n=5+5)

name                     old alloc/op   new alloc/op   delta
WriteBinaryColumnarChar    8.19kB ± 0%    0.00kB       -100.00%  (p=0.008 n=5+5)

name                     old allocs/op  new allocs/op  delta
WriteBinaryColumnarChar     1.02k ± 0%     0.00k       -100.00%  (p=0.008 n=5+5)
```

And, as expected, no change in `BenchmarkWriteTextColumnarChar` since that code path is unchanged (I added the benchmark for parity with other benchmarks):

```
name                   old time/op    new time/op    delta
WriteTextColumnarChar     178µs ± 1%     178µs ± 0%   ~     (p=1.000 n=5+5)

name                   old alloc/op   new alloc/op   delta
WriteTextColumnarChar    34.5kB ± 0%    34.5kB ± 0%   ~     (p=1.000 n=5+5)

name                   old allocs/op  new allocs/op  delta
WriteTextColumnarChar     2.05k ± 0%     2.05k ± 0%   ~     (all equal)
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132338#-:-O8wkW_O5dhSDsJ4P72k:bfzt1ph)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/pgwire/types.go` line 529 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132338#-O8u2KimEFas9A1-J9e6:-O8wQNMYCxGb1XW-u8rq:bq2d837) ([raw file](https://github.com/cockroachdb/cockroach/blob/1cd184ff15c354e68a04dc17aaf85436f57e3414/pkg/sql/pgwire/types.go#L529)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Will this length be wrong now that the padding happens after it's written?
</blockquote></details>

Ooops, the tests caught this too. Fixed.

**Review by DrewKimball — APPROVED** [review]
:lgtm: Nice work!

> Reviewed 3 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132338#-:-O8yvlWXACcgo4qcfXso:bcmw7ss)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Pull request merged**
