### PR TITLE
sql: move AsOfSystemTime to EvalContext

### PR DESCRIPTION
**Pull request by otan**
Previously, AsOfSystemTime was on the SemaCtx. With the bounded
staleness work needing this in the EvalContext, and all other contexts
accessing this variable have access to EvalContext, move
AsOfSystemTime from SemaContext to EvalContext.

Release note: None

### CODE REVIEW

**Comment by rytaft** [comment]
I think this was a good idea! I canceled bors-ing my other PR so feel free to re-open this.

**Comment by otan** [comment]
feel free to bors this if you accept @rytaft :D im off to bed!

**Review by rytaft — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68219)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/conn_executor.go, line 2408 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68219#-Mfmky2Q1lO_6QkSRtqo:-Mfmky2Q1lO_6QkSRtqp:b-lnwql6) ([raw file](https://github.com/cockroachdb/cockroach/blob/131db990b54f5fd526e1194ce1a4d6138bd04698/pkg/sql/conn_executor.go#L2408)):*
> ```Go
> 	p.semaCtx.SearchPath = ex.sessionData.SearchPath
> 	p.semaCtx.IntervalStyleEnabled = ex.sessionData.IntervalStyleEnabled
> 	p.semaCtx.AsOfSystemTime = nil
> ```

if you're not going to reset it here, seems like you should actually remove it from the `SemaContext`, no? I think there are still some references to this field. For example: https://github.com/cockroachdb/cockroach/blob/2eb16353c8a388459414964fc94962cba59b585e/pkg/sql/create_stats.go#L516

**Review by otan — COMMENTED** [review]
revert also included

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68219#-:-Mfo6Ui64G83ccc20mWD:b-7iv2de)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/conn_executor.go, line 2408 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68219#-Mfmky2Q1lO_6QkSRtqo:-Mfo5jRV4HjSAEpvil5c:b-283v3m) ([raw file](https://github.com/cockroachdb/cockroach/blob/131db990b54f5fd526e1194ce1a4d6138bd04698/pkg/sql/conn_executor.go#L2408)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

if you're not going to reset it here, seems like you should actually remove it from the `SemaContext`, no? I think there are still some references to this field. For example: https://github.com/cockroachdb/cockroach/blob/2eb16353c8a388459414964fc94962cba59b585e/pkg/sql/create_stats.go#L516
</blockquote></details>

urgh, knew it was too good to be true to pass first go
removed!

**Review by rytaft — APPROVED** [review]
:lgtm: Thanks!!

> Reviewed 5 of 5 files at r3, 10 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68219#-:-MfosoYR0TU5UG-VTux7:b-qyabs)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan)

**Comment by otan** [comment]
bors r=rytaft

cheers

**Pull request merged**
