### PR TITLE
sql: update comment about row keys

### PR DESCRIPTION
**Pull request by andreimatei**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7761)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7761#-:-KMRXbsZuVZia54mFQrF:1417088721)*

**Comment by tamird** [comment]
Commend -> comment

**Comment by paperstreet** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[keys/keys.go, line 546 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7761#-KMUSWi4Hlw-Cnh-wWpB:-KMUSWi4Hlw-Cnh-wWpC:449440817) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc961ac8143eb10452295e708f664a8e4cb213c8/keys/keys.go#L546)):*
> ```Go
> 	}
> 
> 	// Strip off the family ID / column ID suffix from the buf. The last byte of the buf
> ```

You could also replace "column ID" with "family ID" and it would be more correct

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7761#-:-KMUSkbAfnbgldMm1SBj:1417088721)*

**Comment by andreimatei** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[keys/keys.go, line 546 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7761#-KMUSWi4Hlw-Cnh-wWpB:-KMUbQllvVN4gGazMiio:-1264812538) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc961ac8143eb10452295e708f664a8e4cb213c8/keys/keys.go#L546)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> You could also replace "column ID" with "family ID" and it would be more correct
</details>
would it? My understanding is that is could be both (i.e. if there's no families, this is a col id), right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7761)*

**Comment by paperstreet** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[keys/keys.go, line 546 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7761#-KMUSWi4Hlw-Cnh-wWpB:-KMUctikNgSJepg5hGlK:-340370688) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc961ac8143eb10452295e708f664a8e4cb213c8/keys/keys.go#L546)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> would it? My understanding is that is could be both (i.e. if there's no families, this is a col id), right?
</details>
There's always families, we just sometimes construct them such that the family has one column and the family id is the same as the one column's id.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7761)*

**Comment by andreimatei** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[keys/keys.go, line 546 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7761#-KMUSWi4Hlw-Cnh-wWpB:-KM_HEmimW-JHD55bU1D:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/7076537f67010013b6895c293e91a2e93b503eac/keys/keys.go#L546)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> There's always families, we just sometimes construct them such that the family has one column and the family id is the same as the one column's id.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7761)*

**Pull request merged**
