### PR TITLE
tracing: wrap structured recordings with time at which they were recorded

### PR DESCRIPTION
**Pull request by adityamaru**
This change wrap the existing Structured record in a proto that
has a `time` field, indicating what time the record was recorded.

This is similar to how we wrap free form logs in LogRecord and will
help interleaving child recordings between parent recordings, at
the time when they occurred rather than at the span start time.

This change was motivated by the fact that jobs are going to be using
structured recordings to indicate which phase of execution they are
currently in. When consuming this information, it is more intuitive to
see interleaved events, rather than all events for the parent span followed by
all events for the child span.

Currently, we see:
```
ProcSentExportRequest <- processor level
ProcReceivedExportResponse
ExportRequestEvalStarted <- export.go level
ExportRequestEvalFinished
```

We would like to see:
```
ProcSentExportRequest <- processor level
ExportRequestEvalStarted <- export.go level
ExportRequestEvalFinished
ProcReceivedExportResponse
```

Informs: #64992

### CODE REVIEW

**Comment by adityamaru** [comment]
@tbg curious what you think about a change like this?

**Comment by tbg** [comment]
I'm not opposed to this per se but as is this breaks mixed-version clusters and so in particular the statements contention stuff will not work in that state. We'd need to migrate properly. As for whether we want to go forward with something like this, or mandate that any payload that wants timestamps to wrap them itself, I'd like to leave that decision to the obs-inf team. To me it seems reasonable to provide them by default for all payloads.

**Comment by abarganier** [comment]
Overall looking good, this seems like it will provide a much clearer picture of the overall trace timeline and its associated payloads.

I think it's best to provide timestamps for all payloads by default - I can't think of a scenario where including timestamps wouldn't be helpful. Should opting to not include a timestamp alongside a payload even be an option?

re: migrations/backwards compatibility, is there a way we can structure this to allow for backwards compatibility more easily w.r.t. the protobufs? What if an additional field is added to the `RecordedSpan` proto containing an equivalent sized array of timestamps, existing alongside `internal_structured`, where `internal_structured[i]`'s timestamp is `structured_timestamps[i]`? Then we don't require a new proto message and out-of-date nodes/clients/etc will be able to continue treating the payloads as if they don't have timestamps. Under the hood, we can use a ring buffer for the timestamps like we do for `sizeLimitedBuffer`, evicting timestamps as we evict paylods when the buffer limit is reached. Would that work/not be too inconvenient to work with?

**Review by abarganier — COMMENTED** [review]
Overall looking good, this seems like it will provide a much clearer picture of the overall trace timeline and its associated payloads.

I think it's best to provide timestamps for all payloads by default - I can't think of a scenario where including timestamps wouldn't be helpful. Should opting to not include a timestamp alongside a payload even be an option?

re: migrations/backwards compatibility, is there a way we can structure this to allow for backwards compatibility more easily w.r.t. the protobufs? What if an additional field is added to the `RecordedSpan` proto containing an equivalent sized array of timestamps, existing alongside `internal_structured`, where `internal_structured[i]`'s timestamp is `structured_timestamps[i]`? Then we don't require a new proto message and out-of-date nodes/clients/etc will be able to continue treating the payloads as if they don't have timestamps. Under the hood, we can use a ring buffer for the timestamps like we do for `sizeLimitedBuffer`, evicting timestamps as we evict payloads when the buffer limit is reached. Would that work/not be too inconvenient to work with?

**Comment by adityamaru** [comment]
Noting down an offline conversation I had with @abarganier re: the migration path of the above change.

There are a few scenarios to be considered in a mixed version cluster:

1. A 21.1 node reads a `RecordedSpan` via `Structured` from the `InternalStructured` slice, that was recorded by a 21.2 node.

In this case, the recording from the 21.2 node would be a `StructuredRecord` and would break in the 21.1 `Structured` method since it does not do the correct unwrapping. The solution here would be to:
a) Rename `InternalStructured` to `DeprecatedInternalStructured`
b) Introduce a new slice `StructuredRecordings` that would be of `type []*types.Any`
c) Insert a `Structured` entry into `DeprecatedInternalStructured` and a `StructuredRecord` into `StructuredRecordings`.i.e two insertions for one recording

21.1 nodes would continue to read from `DeprecatedInternalStructured`.

2. A 21.2 node needs to check the RecordedSpan for the existence of `StructuredRecordings`. If it is non-nil, read from it, otherwise read from `InternalStructured` as the span could have come from an older node.

Note: writing to two slices instead of one, means duplicating the recordings and increasing memory usage. I wonder how much of an impact this will have? @tbg sorry to rope you in again, but just wanted to run this migration plan by you.

**Comment by tbg** [comment]
No worries! The migration sounds good, this is also how we've done it in the past. Since payloads are currently lightly used, I think this should be acceptable, though I've been wrong about the perf implications of tracing in the past. The kv95 nightlies on roachperf should be helpful to pin down top-line regressions from this if they occur. We could also elide the population of the old slice once a cluster version is active (if we added one for this purpose). Note that however that I think I remember that the `.IsActive` check is not performance efficent, i.e we'd need to work around the need to re-check it frequently. For that reason I would consider that only if we need to.

**Comment by adityamaru** [comment]
This is RFAL!

**Review by abarganier — APPROVED** [review]
Nice, proto changes :lgtm:, with an optional nit & question. 

People analyzing traces on a v21.2 node that receives structured recordings from some older node will get an inconsistent experience, right? 21.2 structured recordings will be able to be laid out on a timeline properly, while structured recordings from older nodes will have their timestamps set to the owning span's start timestamp. Just wanted to pose the question - is this an acceptable UX for the operator? My opinion is yes, I think the pros outweigh the cons, but I wanted to spark a small discussion regardless for posterity. Regardless we should probably have this documented somewhere. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66147#-:-McKZrO96YvaTtlIMSBv:b-llbugi)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru)

___
*[pkg/sql/sem/builtins/generator_builtins.go, line 1572 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66147#-McKZg4p3iHAGQcDJSSB:-McKZg4qAky4SVfdlfyu:b7spokw) ([raw file](https://github.com/cockroachdb/cockroach/blob/95d43fd5908ec3de72577378334742d455128bb0/pkg/sql/sem/builtins/generator_builtins.go#L1572)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 	payloadJSON, err := payload.FetchValKey("payload")
> 	if err != nil {
> 		return nil, err
> 	}
> ```
</details>

Just curious - why is it okay to remove this now? 
___
*[pkg/util/tracing/tracingpb/recorded_span.proto, line 90 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66147#-McKXwSW9UZu78rBYVWi:-McKXwSX-ok_hbWDIxa4:bcrdxmt) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7a45ddd208f02699ac65edd0c0fa15cf47075db/pkg/util/tracing/tracingpb/recorded_span.proto#L90)):*
> ```
> // StructuredRecords contains StructuredRecord events recorded in the span.
> ```
nit: Until we finish deprecating the other field, would it be useful to note the difference between the two here?

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66147)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier)

___
*[pkg/sql/sem/builtins/generator_builtins.go, line 1572 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66147#-McKZg4p3iHAGQcDJSSB:-McUt2Pm7oLDwFKQwGQL:b-5m1do6) ([raw file](https://github.com/cockroachdb/cockroach/blob/95d43fd5908ec3de72577378334742d455128bb0/pkg/sql/sem/builtins/generator_builtins.go#L1572)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

> ```
> 	payloadJSON, err := payload.FetchValKey("payload")
> 	if err != nil {
> 		return nil, err
> 	}
> ```
Just curious - why is it okay to remove this now? 
</blockquote></details>

I changed the`Structured()` method we use in Next()  to unwrap the inner "Payload" and return that instead of the wrapped `StructuredRecord` (https://github.com/cockroachdb/cockroach/pull/66147/files#diff-9dc236117104be8ff39df1ffc4e4854355bc061569009782634e3970b8259f02R49). So when we convert it to JSON we don't need this additional layer of indexing. fwiw this was how it was before this PR. 
I think in a follow up when we do decide to expose this new "recordedAt" time, it'll be more useful to add it as a separate column in this generator builtin, rather than wrapped in JSON.
___
*[pkg/util/tracing/tracingpb/recorded_span.proto, line 90 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66147#-McKXwSW9UZu78rBYVWi:-McUuBCa-_AXSM4usZDu:bl7tnra) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7a45ddd208f02699ac65edd0c0fa15cf47075db/pkg/util/tracing/tracingpb/recorded_span.proto#L90)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

> ```
> // StructuredRecords contains StructuredRecord events recorded in the span.
> ```
nit: Until we finish deprecating the other field, would it be useful to note the difference between the two here?
</blockquote></details>

good point, done.

**Comment by adityamaru** [comment]
TFTR!

bors r=abarganier

**Pull request merged**
