### PR TITLE
ui: add graph for RocksDB read amplification

### PR DESCRIPTION
**Pull request by cuongdo**
Partly addresses #7552 but doesn't include the nice visualization that's
been requested.

screenshot 2016-07-05 13 00 35

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7620)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[storage/store.go, line 2453 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7620#-KLw2StnOxKQH_aJFeP8:-KLw2StnOxKQH_aJFeP9:-899505872) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f75ea0b9b808cc79c64504cb8a30f445cbcfa69/storage/store.go#L2453)):*
> ```Go
> 	if rocksdb, ok := s.engine.(*engine.RocksDB); ok {
> 		sstables := rocksdb.GetSSTables()
> 		log.Infof("store %d sstables\n%s", s.StoreID(), sstables)
> ```

Perhaps we should log the read amplification here for easy grep'ability. Something like: `store %d sstables (read-amplification=%d)\n%s`.

---

*[storage/engine/rocksdb.go, line 159 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7620#-KLw3152956iQADOLlKp:-KLw3152956iQADOLlKq:-299713769) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f75ea0b9b808cc79c64504cb8a30f445cbcfa69/storage/engine/rocksdb.go#L159)):*
> ```Go
> func (s SSTableInfos) ReadAmplification() int {
> 	var readAmp int
> 	seenLevel := make(map[int]bool)
> ```

`GetSSTables` returns the tables sorted by level, though perhaps it is better to not rely on that.

Would be good to add a simple test of this method. See `TestSSTableInfosString`.

---

*[ui/app/containers/nodeGraphs.tsx, line 208 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7620#-KLw3HprleDNmnNY5qlx:-KLw3HprleDNmnNY5qly:-1319419010) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f75ea0b9b808cc79c64504cb8a30f445cbcfa69/ui/app/containers/nodeGraphs.tsx#L208)):*
> ```XML
>             <LineGraph title="Read Amplification" sources={sources}>
>               <Axis format={ d3.format(".1") }>
>                 <Metric name="cr.store.rocksdb.read-amplification" title="Read Amplification" />
> ```

I wonder if this should be placed on the same graph as flushes and compactions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7620#-:-KLw3P0dEmd1BQ-zZQXz:1417088721)*

**Comment by tamird** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[storage/engine/rocksdb.go, line 154 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7620#-KLw420BUTHmMZC7f1Rz:-KLw420BUTHmMZC7f1S-:1764711032) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f75ea0b9b808cc79c64504cb8a30f445cbcfa69/storage/engine/rocksdb.go#L154)):*
> ```Go
> }
> 
> // ReadAmplification returns RocksDB's read amplification, which is the number
> ```

where does this definition of read amplification come from? Rather than a statement of fact, could you put a brief explanation in this comment (or a citation)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7620)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[storage/engine/rocksdb.go, line 154 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7620#-KLw420BUTHmMZC7f1Rz:-KLw5XWiHYt468B5Kaql:1393317806) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f75ea0b9b808cc79c64504cb8a30f445cbcfa69/storage/engine/rocksdb.go#L154)):*
Not sure what more there is to say here. This comes from https://github.com/facebook/rocksdb/wiki/RocksDB-Tuning-Guide:

> so the read amplification is `number_of_level0_files + number_of_non_empty_levels`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7620)*

**Comment by tamird** [comment]
Just a link to that guide would be good.

**Comment by cuongdo** [comment]
@petermattis: I tried combining read amplification with flushes & compactions. Because the read amplification may tend to be higher than the flushes & compaction rate, combining these graphs makes flushes and compactions less visible. What do you think? 

screenshot 2016-07-06 12 07 14

**Comment by petermattis** [comment]
@cuongdo Yeah, that's not so good. Perhaps you could have a separate y-axis for the read amp, but let's just use a separate graph for now.

**Comment by cuongdo** [comment]
Review status: 1 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[storage/store.go, line 2453 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7620#-KLw2StnOxKQH_aJFeP8:-KM-yhfv4jwkRAmnUdxE:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f75ea0b9b808cc79c64504cb8a30f445cbcfa69/storage/store.go#L2453)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Perhaps we should log the read amplification here for easy grep'ability. Something like: `store %d sstables (read-amplification=%d)\n%s`.
</details>
Done.

---

*[storage/engine/rocksdb.go, line 154 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7620#-KLw420BUTHmMZC7f1Rz:-KM-z4JyBH2IhKmoqp7T:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f75ea0b9b808cc79c64504cb8a30f445cbcfa69/storage/engine/rocksdb.go#L154)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Not sure what more there is to say here. This comes from https://github.com/facebook/rocksdb/wiki/RocksDB-Tuning-Guide:
> 
> > so the read amplification is `number_of_level0_files + number_of_non_empty_levels`
</details>
Done.

---

*[storage/engine/rocksdb.go, line 159 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7620#-KLw3152956iQADOLlKp:-KM-z5OYTPkPSkPdtvTN:335878796) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f75ea0b9b808cc79c64504cb8a30f445cbcfa69/storage/engine/rocksdb.go#L159)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `GetSSTables` returns the tables sorted by level, though perhaps it is better to not rely on that.
> 
> Would be good to add a simple test of this method. See `TestSSTableInfosString`.
</details>
Test added. I prefer not to rely on the tables being sorted by level. I don't think it'll be a performance issue, but we can optimize if it is.

---

*[ui/app/containers/nodeGraphs.tsx, line 208 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7620#-KLw3HprleDNmnNY5qlx:-KM0a-vCGFLpDeKIeXO3:2139738161) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f75ea0b9b808cc79c64504cb8a30f445cbcfa69/ui/app/containers/nodeGraphs.tsx#L208)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I wonder if this should be placed on the same graph as flushes and compactions.
</details>
For the reason mentioned in the main comment thread, I'm leaving this as a separate graph.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7620)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[storage/store.go, line 2459 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7620#-KM0dSIbVU3og2C8dxNF:-KM0dSIbVU3og2C8dxNG:-505972397) ([raw file](https://github.com/cockroachdb/cockroach/blob/43caaec0112aefabc4fc160048ce74fddd91aa32/storage/store.go#L2459)):*
> ```Go
> 		sstables := rocksdb.GetSSTables()
> 		readAmp := sstables.ReadAmplification()
> 		log.Infof("store %d sstables (read amplification = %d)\n%s", s.StoreID(), readAmp, sstables)
> ```

colon before the newline? not sure if that looks better in practice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7620#-:-KM0dWH6xICF4fITjG5n:1417088721)*

**Comment by cuongdo** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/store.go, line 2459 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7620#-KM0dSIbVU3og2C8dxNF:-KM0rt6J3nxb_8R2NC8S:-941496614) ([raw file](https://github.com/cockroachdb/cockroach/blob/43caaec0112aefabc4fc160048ce74fddd91aa32/storage/store.go#L2459)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> colon before the newline? not sure if that looks better in practice.
</details>
colon added

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7620)*

**Pull request merged**
