### PR TITLE
release-23.2: settings: add a Sensitive option and use it for some settings

### PR DESCRIPTION
**Pull request by rafiss**
Backport 5/5 commits from #115851.

/cc @cockroachdb/release

Release justification: high priority feature request, with low risk

---

This new option causes the value of a string setting to be redacted in all outputs that are shown to the user. Users who have the MODIFYCLUSTERSETTING privilege can view the unredacted setting.

Virtual cluster setting overrides don't have their privilege checks changed for the write path. The only change is that when using SHOW commands, the values of sensitive settings will be redacted if the user does not have MODIFYCLUSTERSETTING.

See individual commits for details to make it easier to review.

fixes https://github.com/cockroachdb/cockroach/issues/115356

Release note (security update): Introduced the `server.redact_sensitive_settings.enabled` cluster
setting, which is false by default. If set to true, then the values of the following settings will be redacted
when accessed through SHOW commands or other introspection interfaces:
- server.oidc_authentication.client_id
- server.oidc_authentication.client_secret

In the future, any other sensitive cluster settings that are added will be redacted as well.
Users who have the MODIFYCLUSTERSETTING privilege can view the unredacted
settings.

Release note (cluster virtualization): If the `server.redact_sensitive_settings.enabled` cluster setting
is set to true, then the MANAGEVIRTUALCLUSTER privilege is required to view the values of the
per-virtual-cluster overrides for sensitive cluster settings.

### CODE REVIEW

**Comment by dhartunian** [comment]
Thanks for opening a [backport](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/900005932/Backporting+a+change+to+a+release+branch).

Please check the backport criteria before merging:

- [ ] Backports should only be created for [serious
  issues](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/1043235321/Database+Backport+Patch+Policy#Backport-only-for-serious-issues) or test-only changes.
- [ ] Backports should not break backwards-compatibility.
- [ ] Backports should change as little code as possible.
- [ ] Backports should not change on-disk formats or node communication protocols.
- [ ] Backports should not add new functionality (except as defined
  [here](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/1043235321/Database+Backport+Patch+Policy#Backporting-new-functionality-(including-modifications-to-persisted-state-%26-cross-node-RPCs))).
- [ ] Backports **must not** add, edit, or otherwise modify cluster versions; or add version gates.
- [ ] All backports must be reviewed by the owning areas TL _and_ one additional
  TL. For more information as to how that review should be conducted, please consult the [backport
policy](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/1043235321/Database+Backport+Patch+Policy#Getting-your-backport-reviewed).


<details>
  <summary>If your backport adds new functionality, please ensure that the
following additional criteria are satisfied:</summary>

- [ ] There is a high priority need for the functionality that cannot wait until the next release and is difficult to address in another way.
- [ ] The new functionality is additive-only and only runs for clusters which have specifically “opted in” to it (e.g. by a cluster setting).
- [ ] New code is protected by a conditional check that is trivial to verify and ensures that it only runs for opt-in clusters. State changes must be further protected such that nodes running old binaries will not be negatively impacted by the new state (with a mixed version test added).
- [ ] The PM and TL on the team that owns the changed code have signed off that the change obeys the above rules.
- [ ] Your backport must be accompanied by a post to the appropriate Slack
  channel (#db-backports-point-releases or #db-backports-XX-X-release) for awareness and discussion.
</details>

Also, please add a brief release justification to the body of your PR to justify this
backport.

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117729)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @dt, @fqazi, and @rafiss)

___
*[`pkg/settings/masked.go` line 48 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/117729#-NnzIHnk9Lo4rRtwct6N:-NnzIHnk9Lo4rRtwct6O:bp22kkf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b29bb64ea50c211ed76992e70c663fc199f3154a/pkg/settings/masked.go#L48)):*
> ```Go
> 	// Non-reportable settings are always redacted. Sensitive settings are
> 	// redacted if the redaction cluster setting is enabled.
> 	if !isSensitive || sensitiveRedactionEnabled {
> ```

I'm having a bit of trouble parsing this `if` clause. Why do we return `<redacted>` when `isSensitive` is true?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117729)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @dhartunian, @dt, and @fqazi)

___
*[`pkg/settings/masked.go` line 48 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/117729#-NnzIHnk9Lo4rRtwct6N:-NnzIcjC5SDNnFCxRw08:blehg3b) ([raw file](https://github.com/cockroachdb/cockroach/blob/b29bb64ea50c211ed76992e70c663fc199f3154a/pkg/settings/masked.go#L48)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

I'm having a bit of trouble parsing this `if` clause. Why do we return `<redacted>` when `isSensitive` is true?
</blockquote></details>

MaskedSetting is used for "sensitive" and "non-reportable" settings (and maybe other setting classifications we make up in the future).

non-reportable settings always get redacted.
sensitive settings are only redacted if the `sensitiveRedactionEnabled` cluster setting is on.

**Review by fqazi — APPROVED** [review]
One minor comment, this all looks good. :lgtm: 

> Reviewed 3 of 3 files at r1, 12 of 12 files at r2, 7 of 7 files at r3, 2 of 2 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117729#-:-NnzYv7Q4j8ZSBSB9CYN:b-628e7)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @abarganier, @dhartunian, @dt, and @rafiss)

___
*[`pkg/kv/kvserver/queue_concurrency_test.go` line 70 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/117729#-NnzXMQqE4gW5LYqME9z:-NnzXMQqE4gW5LYqMEA-:b-h5z4yt) ([raw file](https://github.com/cockroachdb/cockroach/blob/b29bb64ea50c211ed76992e70c663fc199f3154a/pkg/kv/kvserver/queue_concurrency_test.go#L70)):*
> ```Go
> 		processingNanos: metric.NewCounter(metric.Metadata{Name: "processingnanos"}),
> 		purgatory:       metric.NewGauge(metric.Metadata{Name: "purgatory"}),
> 		disabledConfig:  testQueueEnabled,
> ```

I guess this is only needed because of a test case? Would it make sense to just initialize the settings at the start of the tests

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117729)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @abarganier, @dhartunian, @dt, and @fqazi)

___
*[`pkg/kv/kvserver/queue_concurrency_test.go` line 70 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/117729#-NnzXMQqE4gW5LYqME9z:-No3bGXcAv6c75Ei13ue:bcuesjs) ([raw file](https://github.com/cockroachdb/cockroach/blob/b29bb64ea50c211ed76992e70c663fc199f3154a/pkg/kv/kvserver/queue_concurrency_test.go#L70)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

I guess this is only needed because of a test case? Would it make sense to just initialize the settings at the start of the tests
</blockquote></details>

in this case, the test is testing a "base queue." this queue data structure is used in a few different places, and each one has a different cluster setting that configures it (e.g. `kvserverbase.ConsistencyQueueEnabled). in this test, there is no such cluster setting to use, so we just use a dummy one instead.

**Review by dhartunian — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117729)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @abarganier, @dt, and @fqazi)

**Review by dhartunian — CHANGES_REQUESTED** [review]
Had a second thought here regarding two functions that changed implementation. Can we gate the new/old impl on the cluster setting value?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117729#-:-NoJQeQYA0RW8r3Wmr63:bw370kb)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @abarganier, @dt, @fqazi, and @rafiss)

___
*[`pkg/settings/masked.go` line 36 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/117729#-NoJ9Qvh1PZgpOCoyOnO:-NoJ9Qvh1PZgpOCoyOnP:b-ji6kdz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b29bb64ea50c211ed76992e70c663fc199f3154a/pkg/settings/masked.go#L36)):*
> ```Go
> // String hides the underlying value.
> func (s *MaskedSetting) String(sv *Values) string {
> 	// Special case for non-reportable/sensitive strings: we still want
> ```

Can this function impl switch on `redactSensitiveSettingsEnabled.Get(sv)` at the top and keep the existing codepath when the setting is off?
___
*[`pkg/sql/show_cluster_setting.go` line 163 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/117729#-NoJ9hzMCSLmaQQOvzcv:-NoJ9hzNDxZYvi2FicXs:b-ji6kdz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b29bb64ea50c211ed76992e70c663fc199f3154a/pkg/sql/show_cluster_setting.go#L163)):*
> ```Go
> 	ctx context.Context, n *tree.ShowClusterSetting,
> ) (planNode, error) {
> 	name := settings.SettingName(strings.ToLower(n.Name))
> ```

Can this function impl switch on `redactSensitiveSettingsEnabled.Get(sv)` at the top and keep the existing codepath when the setting is off?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117729)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @abarganier, @dhartunian, @dt, and @fqazi)

___
*[`pkg/settings/masked.go` line 36 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/117729#-NoJ9Qvh1PZgpOCoyOnO:-NoNhx-957JLJqPEacai:bh46wxl) ([raw file](https://github.com/cockroachdb/cockroach/blob/b29bb64ea50c211ed76992e70c663fc199f3154a/pkg/settings/masked.go#L36)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Can this function impl switch on `redactSensitiveSettingsEnabled.Get(sv)` at the top and keep the existing codepath when the setting is off?
</blockquote></details>

hm, actually for this function, it would not be correct to preserve the old code path when the setting is off. it would lead to all "masked settings" getting redacted, which means that a user who previously could view the OIDC settings would no longer be able to, even when the setting is off.
___
*[`pkg/sql/show_cluster_setting.go` line 163 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/117729#-NoJ9hzMCSLmaQQOvzcv:-NoNZJyVE6bemhm2bEMI:b-55vsjj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b29bb64ea50c211ed76992e70c663fc199f3154a/pkg/sql/show_cluster_setting.go#L163)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Can this function impl switch on `redactSensitiveSettingsEnabled.Get(sv)` at the top and keep the existing codepath when the setting is off?
</blockquote></details>

i initially did not do this so that `redactSensitiveSettingsEnabled` could remain private to the `settings` package. would you still vote for making it public?

the code change in this function also is partially a bugfix IMO, it was always incorrect to use `LookupForLocalAccess` here, since this lookup is ultimately used to show the value to the user.

**Review by dhartunian — APPROVED** [review]
:lgtm: take 2. @rafiss resolved my concerns, it seems like the existing implementation code changes are necessary as they are since they are either bugs or would result in incorrect behavior with the new feature.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117729#-:-NoNkCl-9xqqCNx3efdZ:b-wqvieb)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @abarganier, @dt, @fqazi, and @rafiss)

___
*[`pkg/settings/masked.go` line 36 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/117729#-NoJ9Qvh1PZgpOCoyOnO:-NoNjc8CCEhO9o1l4SD4:bxdkk1i) ([raw file](https://github.com/cockroachdb/cockroach/blob/b29bb64ea50c211ed76992e70c663fc199f3154a/pkg/settings/masked.go#L36)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hm, actually for this function, it would not be correct to preserve the old code path when the setting is off. it would lead to all "masked settings" getting redacted, which means that a user who previously could view the OIDC settings would no longer be able to, even when the setting is off.
</blockquote></details>

ack. Thanks for clarifying.
___
*[`pkg/sql/show_cluster_setting.go` line 163 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/117729#-NoJ9hzMCSLmaQQOvzcv:-NoNkB338Ow4FkT7TIqz:b-nwv2m1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b29bb64ea50c211ed76992e70c663fc199f3154a/pkg/sql/show_cluster_setting.go#L163)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i initially did not do this so that `redactSensitiveSettingsEnabled` could remain private to the `settings` package. would you still vote for making it public?

the code change in this function also is partially a bugfix IMO, it was always incorrect to use `LookupForLocalAccess` here, since this lookup is ultimately used to show the value to the user.
</blockquote></details>

Gotcha. Thanks for clarifying.

**Review by dt — APPROVED** [review]

**Pull request merged**
