### PR TITLE
colcontainer: move DiskQueue to a new package and clean up testing code

### PR DESCRIPTION
**Pull request by asubiotto**
**colserde: reintroduce flags to BenchmarkQueue**
These flags were removed in the original PR for simplicity. However, it is
useful to keep them around to easily run benchmarks with differing values from
the command line.

A new default value has also been chosen for the buffer size in this commit.
There were changes since the last time the benchmark was run for the RFC and
the current version of the code was submitted as a PR.

Release note: None (benchmark code changes).

**colcontainer: move DiskQueue to colcontainer package from colserde**
It felt slightly awkward to have DiskQueue in colserde. This commit is only
code movement moving the DiskQueue to a new colcontainer package, similar to
the rowcontainer package.

This additionally moves assertEqualBatches to coldata/testutils.go and
copyBatch to colexec/utils.go. These seem like better homes for these
functions.

Release note: None (code movement)

**colcontainer: add DiskQueueCfg creation testing helper**
These will be used by other tests in other packages using the DiskQueue. The
helper extracts directory creation in both the in-mem and on-disk cases and
returns a cleanup function as well as the DiskQueueCfg to use.

The names of the test and benchmark have also been adjusted to refer to a
DiskQueue.

Release note: None (testing code changes)

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 7 of 7 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44487#-:-LzmI01u9-3fcT5JaSmW:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colcontainer/testutils.go, line 22 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44487#-LzmHvUSBJGUdcwNv3UD:-LzmHvUSBJGUdcwNv3UE:b-z9fs7u) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd66c9a42f1e727f2c82d767e684d5e85125f93c/pkg/sql/colcontainer/testutils.go#L22)):*
> ```Go
> const inMemDirName = "testing"
> 
> // NewTestingDiskQueueCfg returns a DiskQueueCfg and a cleanup function.
> ```

[nit]: I'd mention that `cleanup` is non-nil.
___
*[pkg/sql/colexec/utils.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44487#-LzmHC-s56bQ2OhLFPXv:-LzmHC-s56bQ2OhLFPXw:b-jdi3c3) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b7fb23b5696bef3a2f05491a00dc550f121caaf/pkg/sql/colexec/utils.go#L35)):*
> ```Go
> // CopyBatch copies the original batch and returns that copy. However, note that
> // the underlying capacity might be different (a new batch is created only with
> // capacity original.Length().
> ```

[nit]: missing closing parenthesis.

**Review by asubiotto — COMMENTED** [review]
bors r=yuzefovich

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44487#-:-LzmJzqx7JJYz0MogCaa:b-ewwdc)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

___
*[pkg/sql/colcontainer/testutils.go, line 22 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44487#-LzmHvUSBJGUdcwNv3UD:-LzmJz5sATdVU5pTo_ay:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd66c9a42f1e727f2c82d767e684d5e85125f93c/pkg/sql/colcontainer/testutils.go#L22)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: I'd mention that `cleanup` is non-nil.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/utils.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44487#-LzmHC-s56bQ2OhLFPXv:-LzmJzP2EloOE9DJ3-8-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b7fb23b5696bef3a2f05491a00dc550f121caaf/pkg/sql/colexec/utils.go#L35)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: missing closing parenthesis.
</blockquote></details>

Done.

**Review by yuzefovich — COMMENTED** [review]
I saw that the build was red because a linter complained. You should double check that.

bors r-

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44487#-:-LzmKK6n1aqL1j4PqHS0:b-sgoivv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

**Comment by asubiotto** [comment]
Thanks, should be good now.

bors r=yuzefovich

**Comment by asubiotto** [comment]
Build failed due to importing `testing` for `AssertEquivalentBatches`. Using a private interface that mirrors the required methods for now, we'll probably want to change that to return a diff string instead of operating on `testing.TB` in the future.

**Comment by asubiotto** [comment]
bors r=yuzefovich

**Comment by asubiotto** [comment]
bors r-

There seems to be an unrelated Examples ORMs failure

**Comment by asubiotto** [comment]
Examples-ORMs should be fixed now

bors r=yuzefovich

**Comment by asubiotto** [comment]
Flake

bors r=yuzefovich

**Pull request merged**
