### PR TITLE
sql/parser: allow collated strings in COPY and IMPORT

### LINKED ISSUE #21858: sql: collated string not supported in COPY or IMPORT
These both call into https://github.com/cockroachdb/cockroach/blob/6fadcd50dd42272a9579fb950e37aa7e408bc2f2/pkg/sql/parser/parse.go#L152 which doesn't support them.

### PR DESCRIPTION
**Pull request by madelynnblue**
Release note (sql change): allow collated strings in COPY
Release note (enterprise change): allow collated strings in IMPORT

Fixes #21858

### CODE REVIEW

**Review by knz — APPROVED** [review]
Thanks!

**Comment by andreimatei** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/copy.go, line 75 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21859#-L41omcqXRMCUllTvLRs:-L41omcqXRMCUllTvLRt:b-39meot) ([raw file](https://github.com/cockroachdb/cockroach/blob/df21ebbbd7678dc4ed345b7e280d81e72c6b528f/pkg/sql/copy.go#L75)):*
> ```Go
> 	// other things that statements more generally need.
> 	parsingEvalCtx *tree.EvalContext
> 	collationEnv   *tree.CollationEnvironment
> ```

is this ever initialized? If not, why is it a member?

Also, a comment on the definition of CollationEnv suggesting that a non-initialized one can be used would be nice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21859)*

**Comment by andreimatei** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/parser/parse.go, line 153 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21859#-L41pld9Pw1E521NkN22:-L41pld9Pw1E521NkN23:b-mq5w1m) ([raw file](https://github.com/cockroachdb/cockroach/blob/df21ebbbd7678dc4ed345b7e280d81e72c6b528f/pkg/sql/parser/parse.go#L153)):*
> ```Go
> // ParseStringAs parses s as type t.
> func ParseStringAs(
> 	t types.T, s string, evalCtx *tree.EvalContext, env *tree.CollationEnvironment,
> ```

pass env by value and say that an empty one will do?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21859)*

**Comment by mjibson** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/copy.go, line 75 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21859#-L41omcqXRMCUllTvLRs:-L42H-3OdBPUuAKdNnxL:b-pjn8x7) ([raw file](https://github.com/cockroachdb/cockroach/blob/df21ebbbd7678dc4ed345b7e280d81e72c6b528f/pkg/sql/copy.go#L75)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

is this ever initialized? If not, why is it a member?

Also, a comment on the definition of CollationEnv suggesting that a non-initialized one can be used would be nice.
</blockquote></details>

Yes, it is initialized to its zero value, which is useful. During collated string parsing an expensive factory is initialized, so this code should allow that to only happen once per COPY statement instead of once per string.

I don't think it's safe to leave this as nil because that would create a NPE later down. But I've added a comment trying to explain what this is for.

---

*[pkg/sql/parser/parse.go, line 153 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21859#-L41pld9Pw1E521NkN22:-L42HaLNsiI0CjME7G8s:bpi37ws) ([raw file](https://github.com/cockroachdb/cockroach/blob/df21ebbbd7678dc4ed345b7e280d81e72c6b528f/pkg/sql/parser/parse.go#L153)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

pass env by value and say that an empty one will do?
</blockquote></details>

The whole point of the CollationEnvironment is to not initialize it multiple times, so passing an empty one is actively discouraged.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21859)*

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/copy.go, line 75 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21859#-L41omcqXRMCUllTvLRs:-L42KjNcbMHuRLsfeghe:b-jaj1vw) ([raw file](https://github.com/cockroachdb/cockroach/blob/df21ebbbd7678dc4ed345b7e280d81e72c6b528f/pkg/sql/copy.go#L75)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Yes, it is initialized to its zero value, which is useful. During collated string parsing an expensive factory is initialized, so this code should allow that to only happen once per COPY statement instead of once per string.

I don't think it's safe to leave this as nil because that would create a NPE later down. But I've added a comment trying to explain what this is for.
</blockquote></details>

I see. But there's no reason to make it a pointer, is there?

The CE would be a lot easier to understand if it had a ctor such that afterwards its members (the pointers) would never change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21859#-:-L42MACnY43c9WGxuJSN:bnfp4nl)*

**Comment by mjibson** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/copy.go, line 75 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21859#-L41omcqXRMCUllTvLRs:-L42OX3y-TWCF8liJ9iJ:b-cd57w) ([raw file](https://github.com/cockroachdb/cockroach/blob/df21ebbbd7678dc4ed345b7e280d81e72c6b528f/pkg/sql/copy.go#L75)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I see. But there's no reason to make it a pointer, is there?

The CE would be a lot easier to understand if it had a ctor such that afterwards its members (the pointers) would never change.
</blockquote></details>

Yeah. Maybe the next time someone is working on these it'll improve. For now it's fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21859)*

**Comment by andreimatei** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/copy.go, line 75 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21859#-L41omcqXRMCUllTvLRs:-L42PMfyGfOdlsdqk8I5:bcc7siu) ([raw file](https://github.com/cockroachdb/cockroach/blob/df21ebbbd7678dc4ed345b7e280d81e72c6b528f/pkg/sql/copy.go#L75)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Yeah. Maybe the next time someone is working on these it'll improve. For now it's fine.
</blockquote></details>

But why did you leave it a pointer here? The `copyMachine` owns it, doesn't it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21859)*

**Comment by mjibson** [comment]
Oh yeah I misunderstood. Opened #21886.

**Pull request merged**
