### PR TITLE
migration: provide a hook to implement preconditions

### PR DESCRIPTION
**Pull request by ajwerner**
This change augments the migration infrastructure with an optional
hook for tenant migrations to express preconditions that will prevent
any attempt to push the cluster version to a version which requires
this migration to run.

This will be helpful to prevent scenarios where user migrations are doomed
to fail based on current state in the database but that would only be
determined after the cluster had locked out the older version.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68242#-:-MfngvW65b-pi3TV2ek_:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @knz)

___
*[pkg/migration/tenant_migration.go, line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68242#-MfngLVm9FVF7zhzcAMx:-MfngLVm9FVF7zhzcAMy:b-ab5jh5) ([raw file](https://github.com/cockroachdb/cockroach/blob/8af77c24ad8255887975e5defedf0f9877b69a0f/pkg/migration/tenant_migration.go#L103)):*
> ```Go
> 	ctx context.Context, cv clusterversion.ClusterVersion, d TenantDeps,
> ) error {
> 	if m.precondition == nil {
> ```

[nit] I think it would be good to require a non-nil `precondition` function, to force whoever is adding a migration to consider this aspect. We can define a `NoPreconditionFn` to use when it's not needed.

**Review by ajwerner — COMMENTED** [review]
Added testing and made the precondition required. PTAL. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68242#-:-MglJB5R2T0aeWwZQR0x:bm28u9q)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz)

___
*[pkg/migration/tenant_migration.go, line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68242#-MfngLVm9FVF7zhzcAMx:-MglJ9Wx3bFw-4dIY3eG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8af77c24ad8255887975e5defedf0f9877b69a0f/pkg/migration/tenant_migration.go#L103)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] I think it would be good to require a non-nil `precondition` function, to force whoever is adding a migration to consider this aspect. We can define a `NoPreconditionFn` to use when it's not needed.
</blockquote></details>

Done.

**Review by fqazi — APPROVED** [review]
> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68242)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz)

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Pull request merged**
