### PR TITLE
c-deps: revert RocksDB bump to 5.9 (back to 5.5.1)

### PR DESCRIPTION
**Pull request by tbg**
This dependency upgrade has likely introduced consistency failures
which remain to be investigated.

See https://github.com/cockroachdb/cockroach/issues/19947.

### CODE REVIEW

**Review by benesch — APPROVED** [review]

**Comment by danhhz** [comment]
lgtm

**Comment by tschottdorf** [comment]
Had to revert f6f227d616b18486ee504137917811188b29cfe9 as well to get it to compile.

**Comment by tschottdorf** [comment]
Here we go 🤞

**Comment by cuongdo** [comment]
The nightlies are passing again.

**Pull request merged**
