### PR TITLE
sql: fix assignment casts of arrays

### LINKED ISSUE #102412: Unexpected results might be related to `BIT` and `INDEX`
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

Consider the following program:
```
CREATE DATABASE database1;
USE database1;
SET CLUSTER SETTING diagnostics.reporting.enabled    = false;
SET CLUSTER SETTING diagnostics.reporting.send_crash_reports = false;
SET CLUSTER SETTING sql.metrics.statement_details.plan_collection.enabled = 'off';
SET CLUSTER SETTING sql.stats.automatic_collection.enabled = 'off';
SET CLUSTER SETTING timeseries.storage.enabled = 'off';
set experimental_enable_hash_sharded_indexes='on';

CREATE TABLE t0 (c0 VARBIT(55)[] AS (ARRAY[B'1111111111111111111111111111111111110010101010100100111000111001', B'1']) STORED);

CREATE UNIQUE INDEX ON t0(rowid DESC, c0 DESC);

INSERT INTO t0 (rowid) VALUES (1488128305);
 
SELECT t0.rowid FROM t0 WHERE (((NOT ((t0.c0) NOT BETWEEN (t0.c0) AND t0.c0)))AND((t0.rowid) IN ((VALUES (1488128305)))));

SELECT t0.rowid FROM t0 WHERE (((NOT ((t0.c0) NOT BETWEEN (t0.c0) AND t0.c0)))AND((t0.rowid) IN (SELECT t0.rowid FROM t0 )));
```

There is only one value in `t0.c0`, so this two `SELECT` queries should be equivalent and have the same results. As `((NOT ((t0.c0) NOT BETWEEN (t0.c0) AND t0.c0)))` always return `TRUE`, so the results of these two queries should be `1488128305`.

But I get the following results:
```
> SELECT t0.rowid FROM t0 WHERE (((NOT ((t0.c0) NOT BETWEEN (t0.c0) AND t0.c0)))AND((t0.rowid) IN ((VALUES (1488128305)))));
  rowid
---------
(0 rows)

Time: 1ms

> SELECT t0.rowid FROM t0 WHERE (((NOT ((t0.c0) NOT BETWEEN (t0.c0) AND t0.c0)))AND((t0.rowid) IN (SELECT t0.rowid FROM t0 )));
    rowid
--------------
  1488128305
(1 row)

Time: 1ms
```
The first query returns an empty result, which is unexpected.

I tried three methods that can avoid this bug. The first is to remove the `INDEX`, then this bug can not reproduce. The second is to modify the value `1111111111111111111111111111111111110010101010100100111000111001` to a smaller one, or modify the type of `t0.c0` to `INT`. The third is remove `((NOT ((t0.c0) NOT BETWEEN (t0.c0) AND t0.c0)))`.

**To Reproduce**

I build CockroachDB from the latest commit version https://github.com/cockroachdb/cockroach/commit/5b44c4fd6d97dc3a75e786fed24f47ad8bcf9039, and run it in a single machine. I run this program in CLI.

**Expected behavior**
The first query has correct result.

**Environment:**
 - CockroachDB version https://github.com/cockroachdb/cockroach/commit/5b44c4fd6d97dc3a75e786fed24f47ad8bcf9039
 - Server OS: [Ubuntu 22.04]
 - Client app [CLI, JDBC]

Jira issue: CRDB-27431

### PR DESCRIPTION
**Pull request by mgartner**
#### eval: add psql -X flag to cast CSV generators

The `-X` flag has been added to `psql` commands in
`assignment_casts_gen.sh` and `explicit_casts_gen.sh`. This flag makes
`psql` ignore a user's `.psqlrc` file, which prevents custom
configurations from affecting the scripts' output, such as the
`/timing` setting which prints query latencies.

Release note: None

#### eval: fix error line number in cast tests

Release note: None

#### eval: add more types to cast comparison tests

Release note: None

#### sql: fix assignment casts of arrays

This commit fixes a bug that caused incorrect results for assignment
casts of array types. Previously, the array's elements were casted as an
explicit cast, not an assignment cast. This allowed values to be
inserted into an array column that did not conform to the type.

Fixes #102412

Release note (bug fix): A bug has been fixed that allowed values to be
inserted into an `ARRAY`-type column that did not conform to the
inner-type of the array. For example, it was possible to insert
`ARRAY['foo']` into a column of type `CHAR(1)[]`. This could cause
incorrect results when querying the table. The insert now errors, which
is expected. This bug was present since v21.1.

#### eval: add more types to cast comparison tests

Array types have been added to the cast comparison tests.

Release note: None

#### eval: remove extraneous info from PG version in cast CSVs

Release note: None

### CODE REVIEW

**Review by michae2 — APPROVED** [review]
:lgtm: Nice fix! Sorry I didn't add array types originally!

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 5 of 5 files at r3, 2 of 2 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102491#-:-NU3bzyACJ92DrgigrlH:bslpg30)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/sem/eval/cast_test/cast_test.go` line 219 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/102491#-NU3ZufmEgOA9Jufw-Oj:-NU3ZufmEgOA9Jufw-Ok:b6zrrk4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9634da71ba0477ce7efd29ade3d88eb61dd5ac9/pkg/sql/sem/eval/cast_test/cast_test.go#L219)):*
> ```Go
> 	// Start lineno at 9 to account for the comment lines at the beginning of
> 	// the CSV files.
> 	for lineno := 9; ; lineno++ {
> ```

Good catch!

**Review by michae2 — APPROVED** [review]
Stairway thought (just a suggestion, can ignore): it might be nice to also add the empty array and the empty string to `literals.txt`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102491#-:-NU3vteLDh03HTIzakWD:bxffn35)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by mgartner** [comment]
> Stairway thought (just a suggestion, can ignore): it might be nice to also add the empty array and the empty string to literals.txt.

Good idea. Done!

**Comment by mgartner** [comment]
TFTR!

bors r+

**Pull request merged**
