### PR TITLE
release-23.2: catalog: add descriptor repair to remove missing roles

### PR DESCRIPTION
**Pull request by fqazi**
Backport 1/1 commits from #122557.

/cc @cockroachdb/release

---

Previously, we had a bug that could lead to descriptors having privileages to roles that no longer exist. This could lead to certain commands like SHOW GRANTS breaking. To address this, this patch will add descirptor repair logic to automatically clean up oprhaned privileges.

Fixes: #122552

Release note (bug fix): Add automated clean up / validation for dropped roles inside descriptors.
Release justification: low risk fix that prevents corrupt descriptors from impacting SHOW GRANTS

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
i think this should account for node also. maybe we should backport some of the changes i'm adding in https://github.com/cockroachdb/cockroach/pull/124772

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124665#-:-Nz-yjVqEm1Uewlvs-Rm:b824ecs)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @fqazi)

___
*[`pkg/sql/crdb_internal.go` line 6155 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124665#-Nz-wAEw4l1Xi9V_3t0C:-Nz-wAEw4l1Xi9V_3t0D:b-e6xxuk) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f2f15b107de5a82331f7509596818a53434dacc/pkg/sql/crdb_internal.go#L6155)):*
> ```Go
> 			}
> 			doError(catalog.ValidateRolesInDescriptor(descriptor, func(username username.SQLUsername) (bool, error) {
> 				if username.IsRootUser() ||
> ```

does this also need to exclude the `node` user? otherwise, it will report errors on internal objects that are owned by `node`. i created https://github.com/cockroachdb/cockroach/pull/124772
___
*[`pkg/sql/crdb_internal.go` line 6620 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124665#-Nz-xdP83tTTLt26SGFK:-Nz-xdP83tTTLt26SGFL:b-ayzo15) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f2f15b107de5a82331f7509596818a53434dacc/pkg/sql/crdb_internal.go#L6620)):*
> ```Go
> 							(SELECT username
> 							FROM system.users UNION
> 							SELECT 'public' as username)
> ```

what about `node`?
___
*[`pkg/sql/sem/builtins/builtins.go` line 5426 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124665#-Nz-yIhc8OVeBY40OaMa:-Nz-yIhc8OVeBY40OaMb:brwmjfh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f2f15b107de5a82331f7509596818a53434dacc/pkg/sql/sem/builtins/builtins.go#L5426)):*
> ```Go
> 							(SELECT username
> 							FROM system.users UNION
> 							SELECT 'public' as username)
> ```

should `node` go here too?

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124665)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @rafiss)

___
*[`pkg/sql/crdb_internal.go` line 6155 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124665#-Nz-wAEw4l1Xi9V_3t0C:-Nz0GrgyCIpkEkUYOhBn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f2f15b107de5a82331f7509596818a53434dacc/pkg/sql/crdb_internal.go#L6155)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

does this also need to exclude the `node` user? otherwise, it will report errors on internal objects that are owned by `node`. i created https://github.com/cockroachdb/cockroach/pull/124772
</blockquote></details>

Done.
___
*[`pkg/sql/crdb_internal.go` line 6620 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124665#-Nz-xdP83tTTLt26SGFK:-Nz0GtxE4Xkerb0tfiZ5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f2f15b107de5a82331f7509596818a53434dacc/pkg/sql/crdb_internal.go#L6620)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

what about `node`?
</blockquote></details>

Done.
___
*[`pkg/sql/sem/builtins/builtins.go` line 5426 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124665#-Nz-yIhc8OVeBY40OaMa:-Nz0GsE-0be8_bSq889J:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f2f15b107de5a82331f7509596818a53434dacc/pkg/sql/sem/builtins/builtins.go#L5426)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

should `node` go here too?
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
lgtm!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124665#-:-Nz3nMQ7-wKPOO1zJjYz:b-7nbn20)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

**Review by dhartunian — APPROVED** [review]

**Comment by fqazi** [comment]
@rafiss @dhartunian TFTR!

**Pull request merged**
