### PR TITLE
storage: implement `RangeKeyChanged()` for `MVCCIncrementalIterator`

### LINKED ISSUE #86105: storage: implement `RangeKeyChanged` for `MVCCIncrementalIterator`
The `RangeKeyChanged()` iterator method can allow for significant performance improvements when iterating across spans and detecting MVCC range keys. However, this hasn't been implemented for `MVCCIncrementalIterator`, because of two complications:

1. The iterator can hide range keys, so even though the range key may change in the underlying iterator, it may not in the incremental iterator (because the range keys were never exposed).

2. `NextIgnoringTime()` and `NextKeyIgnoringTime()` may cause the exposed range keys to change -- both by revealing a previously hidden range key span, and by revealing additional versions for currently exposed range keys. These should most likely cause `RangeKeyChanged()` to trigger, as should the reversal to regular time-bound iteration.

Jira issue: CRDB-18576

Epic CRDB-2624

### PR DESCRIPTION
**Pull request by erikgrinaker**
**storage: use `RangeKeyChanged()` in `MVCCIncrementalIterator`**

This patch uses `RangeKeyChanged()` to detect changes to range keys in
`MVCCIncrementalIterator`. There are no functional changes.

Some quick benchmarks, using catchup scans:

```
name                                                                 old time/op  new time/op  delta
CatchUpScan/mixed-case/withDiff=true/perc=0.00/numRangeKeys=0-24      538ms ± 1%   535ms ± 1%     ~     (p=0.211 n=10+9)
CatchUpScan/mixed-case/withDiff=true/perc=0.00/numRangeKeys=1-24      690ms ± 0%   590ms ± 1%  -14.56%  (p=0.000 n=9+10)
CatchUpScan/mixed-case/withDiff=true/perc=0.00/numRangeKeys=100-24    743ms ± 1%   646ms ± 1%  -13.13%  (p=0.000 n=9+9)
CatchUpScan/mixed-case/withDiff=false/perc=0.00/numRangeKeys=0-24     794ms ± 1%   794ms ± 0%     ~     (p=0.579 n=10+10)
CatchUpScan/mixed-case/withDiff=false/perc=0.00/numRangeKeys=1-24     966ms ± 0%   911ms ± 1%   -5.72%  (p=0.000 n=10+10)
CatchUpScan/mixed-case/withDiff=false/perc=0.00/numRangeKeys=100-24   974ms ± 0%   920ms ± 0%   -5.51%  (p=0.000 n=10+10)
```

Release justification: bug fixes and low-risk updates to new functionality.

Release note: None

**storage: implement `RangeKeyChanged()` for `MVCCIncrementalIterator`**

This patch implements `RangeKeyChanged()` for `MVCCIncrementalIterator`.
It only fires if the time bound range keys change, not if a
`Next(Key)IgnoringTime()` operation reveals additional range keys.

Resolves #86105.

Release justification: bug fixes and low-risk updates to new functionality

Release note: None
  
**storage: add `MVCCIncrementalIterator.RangeKeysIgnoringTime()`**

This patch changes `MVCCIncrementalIterator` range key behavior
following a `Next(Key)IgnoringTime()` call. Previously, range key
methods would then expose unfiltered range keys. Now, the standard range
key methods only apply to filtered range keys, and an additional
`RangeKeysIgnoringTime()` method provides access to unfiltered range
keys.

This implies that if such a call steps onto a range key that's entirely
outside of the time bounds then:

* `HasPointAndRange()` will return `false`,`false` if on a bare range
  key.

* `RangeKeyChanged()` will not fire, unless stepping off of a range key
  within the time bounds.

* `RangeBounds()` and `RangeKeys()` will return empty results.

This is done to avoid conditional range key handling following these
calls, except for the exact sites where the caller is interested in
the unfiltered range keys.

Release justification: bug fixes and low-risk updates to new functionality

Release note: None

### CODE REVIEW

**Review by tbg — COMMENTED** [review]
First pass, still need to get a little more confident with the code, if you put a silly bug in there on purpose I probably would've missed it. Haven't looked at the test output yet. I will work a bit on https://github.com/cockroachdb/cockroach/issues/86122 to get more comfortable with the harness.

> Reviewed 2 of 2 files at r2, 2 of 2 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86259#-:-N9fZr-U715panJetJVx:b-58twit)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @jbowens)

___
*[`-- commits` line 51 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86259#-N9fWXwt3Zy1VThj2f-x):*
This 
___
*[`pkg/storage/mvcc_history_test.go` line 1611 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86259#-N9fYP_7Bq1LPyPW9vtq:-N9fYP_7Bq1LPyPW9vtr:b-32poc8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f56dcfb41d39fdf692ea1300f1e327409d15a8df/pkg/storage/mvcc_history_test.go#L1611)):*
> ```Go
> 		if e.iterRangeKeys.IsEmpty() {
> 			e.iterRangeKeys = MVCCRangeKeyStack{
> 				Bounds:   roachpb.Span{Key: keys.MinKey.Next().Clone(), EndKey: keys.MaxKey.Clone()},
> ```

Why the clone? Do we need to update `keys.MinKey` etc so that its cap equals its len?
___
*[`pkg/storage/mvcc_incremental_iterator.go` line 336 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86259#-N9fRM268vnKjPpjEmd8:-N9fRM268vnKjPpjEmd9:b-peuurs) ([raw file](https://github.com/cockroachdb/cockroach/blob/a86462e32ab9cd81a87341884bfcc3c789096ebb/pkg/storage/mvcc_incremental_iterator.go#L336)):*
> ```Go
> 						return false
> 					}
> 					tbiKey = i.timeBoundIter.UnsafeKey().Key
> ```

Could `i.timeBoundIter` still be positioned with (`hasRange && !hasPoint`) at this point, i.e. can we access `UnsafeKey()` unconditionally here?
___
*[`pkg/storage/mvcc_incremental_iterator.go` line 434 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86259#-N9fRxyK6U7yucLUcy_Q:-N9fRxyK6U7yucLUcy_R:b-pp6kwu) ([raw file](https://github.com/cockroachdb/cockroach/blob/a86462e32ab9cd81a87341884bfcc3c789096ebb/pkg/storage/mvcc_incremental_iterator.go#L434)):*
> ```Go
> 		}
> 		if skipped {
> 			// The skip may landed in the middle of a bare range key, in which case we
> ```

may have landed
___
*[`pkg/storage/mvcc_incremental_iterator.go` line 435 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86259#-N9fSICc4ToahtDN8xew:-N9fSICc4ToahtDN8xex:b6x8qxw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a86462e32ab9cd81a87341884bfcc3c789096ebb/pkg/storage/mvcc_incremental_iterator.go#L435)):*
> ```Go
> 		if skipped {
> 			// The skip may landed in the middle of a bare range key, in which case we
> 			// should move on to the next key.
> ```

Why is this done here and not in `maybeSkipKeys`?
___
*[`pkg/storage/mvcc_incremental_iterator.go` line 96 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/86259#-N9fT_CC38vvaHFgDZoB:-N9fT_CC38vvaHFgDZoC:b-mh69lb) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f22b47c490ee5a7804e7e7fb71cc0d0379da054/pkg/storage/mvcc_incremental_iterator.go#L96)):*
> ```Go
> 	// underlying iterator returns true as well. This can be used to hide point or
> 	// range keys where one key kind satisfies the time predicate but the other
> 	// one doesn't. Ignored following IgnoringTime() calls.
> ```

Ignored for how long? Consider expanding the comment by referencing `i.ignoringTime` and expanding its comment a bit to point out when the flag is reset (I guess that's when we're done with the IgnoringTime call). The code isn't so clear; we actually reset `ignoringTime` at the top of `advance`, I think someplace should explain how this works and on the field is as good a place as any. Maybe `advance` should also be renamed to reflect that it doesn't ignore time? `advanceObservingTime`? You could similarly rename `hasPoint` and `hasRange` with an `ObservingTime` suffix.
___
*[`pkg/storage/mvcc_incremental_iterator.go` line 247 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/86259#-N9fSc9IBimpOuHIE5Ng:-N9fSc9IBimpOuHIE5Nh:b1w95w6) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f22b47c490ee5a7804e7e7fb71cc0d0379da054/pkg/storage/mvcc_incremental_iterator.go#L247)):*
> ```Go
> 	}
> 	i.iter.SeekGE(startKey)
> 	i.advance(true /* seek */)
> ```

Should the parameter be called `seeked`, since it reflects what the caller did before? As is, this sounds like imperative mood which doesn't seem right.

edit: with the comment on `advance` this seems clear enough, still going to submit this for your consideration.
___
*[`pkg/storage/mvcc_incremental_iterator.go` line 480 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/86259#-N9fUwdb-IU-FmfwYOQF:-N9fUwdb-IU-FmfwYOQG:bgfbgai) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f22b47c490ee5a7804e7e7fb71cc0d0379da054/pkg/storage/mvcc_incremental_iterator.go#L480)):*
> ```Go
> 			// isn't visible either, then we keep going.
> 			if !i.hasPoint {
> 				if !i.hasRange {
> ```

Not new code, but I thought one of (hasPoint,hasRange) them has to be true for a valid iterator. This isn't true here because these values come from `updateRangeKeys` which filters them by time, so we could have both false. Mind pointing this out.
___
*[`pkg/storage/mvcc_incremental_iterator.go` line 486 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86259#-N9fXaXO7r5nnfMN00zb:-N9fXaXO7r5nnfMN00zc:bs4yt0h) ([raw file](https://github.com/cockroachdb/cockroach/blob/f56dcfb41d39fdf692ea1300f1e327409d15a8df/pkg/storage/mvcc_incremental_iterator.go#L486)):*
> ```Go
> 			newRangeKey = i.hasRange
> 			if !hadRange && !i.hasRange {
> 				i.rangeKeyChanged = false
> ```

It's false already, so you don't need this?
___
*[`pkg/storage/mvcc_incremental_iterator.go` line 679 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86259#-N9fWmY6AAkN8zTeTSqZ:-N9fWmY6AAkN8zTeTSq_:b-yaoam4) ([raw file](https://github.com/cockroachdb/cockroach/blob/f56dcfb41d39fdf692ea1300f1e327409d15a8df/pkg/storage/mvcc_incremental_iterator.go#L679)):*
> ```Go
> // However, RangeKeyChanged() will only fire if this moves onto an entirely new
> // MVCC range key, not if it reveals additional range keys at the current
> // position.
> ```

Are you confident that these are the right semantics? Is it what `CatchUpScan` wants? It feels like this might require awkward code at each caller that also uses `*IgnoringTime`. Could it be better to trigger an event in this case?

If the current semantics are desirable, maybe a way to phrase them as less of a one-off is that RangeKeyChanged triggers whenever we traverse (i.e. cross or step onto) the start key of a range deletion. This is not the case if we call `NextIgnoringTime` while already positioned on a hidden range key, so there is no surprise that RangeKeyChanged won't fire.

I am still suspicious that current semantics are the right choice. Callers may use `RangeKeyChanged` to cache state that depends on the range key. Seems to invite bugs if the range key may change without the corresponding notification firing.
___
*[`pkg/storage/testdata/mvcc_histories/range_key_iter_incremental` line 129 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86259#-N9fXKJN5tM5zb2NWREN:-N9fXKJN5tM5zb2NWREO:blm2cx) ([raw file](https://github.com/cockroachdb/cockroach/blob/f56dcfb41d39fdf692ea1300f1e327409d15a8df/pkg/storage/testdata/mvcc_histories/range_key_iter_incremental#L129)):*
> ```
> iter_scan: "a"/4.000000000,0=/<empty> {a-b}/[1.000000000,0=/<empty>]
> iter_scan: "a"/2.000000000,0=/BYTES/a2 {a-b}/[1.000000000,0=/<empty>]
> iter_scan: {b-c}/[3.000000000,0=/<empty> 1.000000000,0=/<empty>] !
> ```

I don't see code in this diff that produces the exclamation mark.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86259)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @jbowens, and @tbg)

___
*[`pkg/storage/mvcc_history_test.go` line 1611 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86259#-N9fYP_7Bq1LPyPW9vtq:-N9flcQh3sCiNPD3aJBW:b9ztxm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/f56dcfb41d39fdf692ea1300f1e327409d15a8df/pkg/storage/mvcc_history_test.go#L1611)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Why the clone? Do we need to update `keys.MinKey` etc so that its cap equals its len?
</blockquote></details>

Otherwise, when we call `CloneInto()` later which reuses the byte slices, we're trampling `keys.MinKey` and `keys.MaxKey`, which is really bad. I'll add a comment.
___
*[`pkg/storage/mvcc_incremental_iterator.go` line 435 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86259#-N9fSICc4ToahtDN8xew:-N9flxP_9NQyDQGttlG2:b-575cy6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a86462e32ab9cd81a87341884bfcc3c789096ebb/pkg/storage/mvcc_incremental_iterator.go#L435)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Why is this done here and not in `maybeSkipKeys`?
</blockquote></details>

We need to record and propagate the `RangeKeyChanged` state during the steps. By doing this here, `maybeSkipKeys` only ever takes one step, so we can keep all of the `RangeKeyChanged` logic in one spot. Initially tried returning a value for it instead, but don't think it ended up being as clear -- either works though, no strong opinion.
___
*[`pkg/storage/mvcc_incremental_iterator.go` line 96 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/86259#-N9fT_CC38vvaHFgDZoB:-N9fll0f5HI6c6paEr61:b-cmhsdx) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f22b47c490ee5a7804e7e7fb71cc0d0379da054/pkg/storage/mvcc_incremental_iterator.go#L96)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Ignored for how long? Consider expanding the comment by referencing `i.ignoringTime` and expanding its comment a bit to point out when the flag is reset (I guess that's when we're done with the IgnoringTime call). The code isn't so clear; we actually reset `ignoringTime` at the top of `advance`, I think someplace should explain how this works and on the field is as good a place as any. Maybe `advance` should also be renamed to reflect that it doesn't ignore time? `advanceObservingTime`? You could similarly rename `hasPoint` and `hasRange` with an `ObservingTime` suffix.
</blockquote></details>

Until the next positioning operation, which may or may not be another IgnoringTime operation. Will expand.
___
*[`pkg/storage/mvcc_incremental_iterator.go` line 679 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86259#-N9fWmY6AAkN8zTeTSqZ:-N9fmEZc-s7OFG1V1pOP:b-96jkj1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f56dcfb41d39fdf692ea1300f1e327409d15a8df/pkg/storage/mvcc_incremental_iterator.go#L679)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Are you confident that these are the right semantics? Is it what `CatchUpScan` wants? It feels like this might require awkward code at each caller that also uses `*IgnoringTime`. Could it be better to trigger an event in this case?

If the current semantics are desirable, maybe a way to phrase them as less of a one-off is that RangeKeyChanged triggers whenever we traverse (i.e. cross or step onto) the start key of a range deletion. This is not the case if we call `NextIgnoringTime` while already positioned on a hidden range key, so there is no surprise that RangeKeyChanged won't fire.

I am still suspicious that current semantics are the right choice. Callers may use `RangeKeyChanged` to cache state that depends on the range key. Seems to invite bugs if the range key may change without the corresponding notification firing.
</blockquote></details>

I've been going back and forth on this.

The main reason I landed on this is that if the caller is doing any caching, then triggering `RangeKeyChanged´ when `NextIgnoringTime` reveals additional versions is going to ruin that caching anyway -- in the worst case, it's going to flip back and forth for every `Next()`/`NextIgnoringTime()` cycle, effectively making the caching worse than not caching at all.

Because `MVCCIncrementalIterator` already has to decode and process the range keys (for filtering), we can cheaply cache both of them in here, and so I think the recommended way to use this would be for the caller to not do any caching at all, but simply call `RangeKeys()` at the spot they need it and process as needed -- for example, this simplifies the `WithDiff` processing in catchupscan, which just needs to know if there's a range key between two points regardless of time filtering.

Another option I've been considering has been to always expose filtered range keys in `RangeKeys()`, and have a separate `RangeKeysIgnoringTime()` to expose unfiltered range keys. However, in that case it isn't clear what the semantics of `RangeKeyChanged` should be when `RangeKeysIgnoringTime()` changes but `RangeKeys()`doesn't.

Happy to talk through this on a call or something.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86259)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @jbowens, and @tbg)

___
*[`pkg/storage/mvcc_incremental_iterator.go` line 679 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86259#-N9fWmY6AAkN8zTeTSqZ:-N9hRhiy1jpYfUpqvOWW:bkjc9px) ([raw file](https://github.com/cockroachdb/cockroach/blob/f56dcfb41d39fdf692ea1300f1e327409d15a8df/pkg/storage/mvcc_incremental_iterator.go#L679)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

I've been going back and forth on this.

The main reason I landed on this is that if the caller is doing any caching, then triggering `RangeKeyChanged´ when `NextIgnoringTime` reveals additional versions is going to ruin that caching anyway -- in the worst case, it's going to flip back and forth for every `Next()`/`NextIgnoringTime()` cycle, effectively making the caching worse than not caching at all.

Because `MVCCIncrementalIterator` already has to decode and process the range keys (for filtering), we can cheaply cache both of them in here, and so I think the recommended way to use this would be for the caller to not do any caching at all, but simply call `RangeKeys()` at the spot they need it and process as needed -- for example, this simplifies the `WithDiff` processing in catchupscan, which just needs to know if there's a range key between two points regardless of time filtering.

Another option I've been considering has been to always expose filtered range keys in `RangeKeys()`, and have a separate `RangeKeysIgnoringTime()` to expose unfiltered range keys. However, in that case it isn't clear what the semantics of `RangeKeyChanged` should be when `RangeKeysIgnoringTime()` changes but `RangeKeys()`doesn't.

Happy to talk through this on a call or something. 
</blockquote></details>

How about

- `RangeKeyChanged()` only triggers on filtered range keys, even if `XIgnoringTime` exposes an unseen, out-of-bounds range key.
- `XIgnoringTime() (rangeKeyChanged bool)` returns whether there's now an exclusively ignored rangekey, which can be retrieved via:
- `RangeKeyIgnoringTime() MVCCRangeKeyStack`

This seems good because:

- caching based on `RangeKey` when all you care about is filtered ones "just works"
- don't randomly expose `RangeKey`s that are out of time bounds after a call to `XIgnoringKey`...
- ... but if those are relevant, the event tracking and access to them is there, and
- it's nicely contained in the three methods related to ignoring time bounds.

This is also operating under the assumption that access to out-of-bounds range keys will be somewhat rare. The uses I've seen revolve around discovering a version matching an intent, finding a previous version for withDiff, etc.
Would be interesting to litmus test this with `MVCCPredicateDeleteRange` and/or `MVCCClearRange` since both probably do want to see out-of-bound range dels.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86259)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens and @tbg)

___
*[`pkg/storage/mvcc_incremental_iterator.go` line 336 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86259#-N9fRM268vnKjPpjEmd8:-N9u_bL-6cO35RtsdGdb:boa2bnv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a86462e32ab9cd81a87341884bfcc3c789096ebb/pkg/storage/mvcc_incremental_iterator.go#L336)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Could `i.timeBoundIter` still be positioned with (`hasRange && !hasPoint`) at this point, i.e. can we access `UnsafeKey()` unconditionally here?
</blockquote></details>

Yes, `UnsafeKey()` is also valid along a range key.
___
*[`pkg/storage/mvcc_incremental_iterator.go` line 435 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86259#-N9fSICc4ToahtDN8xew:-N9uckKo48d1X_zI6l00:b-sx0bd3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a86462e32ab9cd81a87341884bfcc3c789096ebb/pkg/storage/mvcc_incremental_iterator.go#L435)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

We need to record and propagate the `RangeKeyChanged` state during the steps. By doing this here, `maybeSkipKeys` only ever takes one step, so we can keep all of the `RangeKeyChanged` logic in one spot. Initially tried returning a value for it instead, but don't think it ended up being as clear -- either works though, no strong opinion.
</blockquote></details>

Ended up moving this back into `maybeSkipKeys`, it's cleaner.
___
*[`pkg/storage/mvcc_incremental_iterator.go` line 247 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/86259#-N9fSc9IBimpOuHIE5Ng:-N9u_YCN1z6r3tdLbNvT:b-1eh3wi) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f22b47c490ee5a7804e7e7fb71cc0d0379da054/pkg/storage/mvcc_incremental_iterator.go#L247)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Should the parameter be called `seeked`, since it reflects what the caller did before? As is, this sounds like imperative mood which doesn't seem right.

edit: with the comment on `advance` this seems clear enough, still going to submit this for your consideration.
</blockquote></details>

Sure, done.
___
*[`pkg/storage/mvcc_incremental_iterator.go` line 486 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86259#-N9fXaXO7r5nnfMN00zb:-N9u_sUx2HbyiDQGNA65:b-84vinf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f56dcfb41d39fdf692ea1300f1e327409d15a8df/pkg/storage/mvcc_incremental_iterator.go#L486)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

It's false already, so you don't need this?
</blockquote></details>

We need this in the case where we weren't on a range key, then stepped onto a new range key, but it got filtered out. This shouldn't trigger `RangeKeyChanged()` to the caller, since we're going from empty to empty.
___
*[`pkg/storage/mvcc_incremental_iterator.go` line 679 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86259#-N9fWmY6AAkN8zTeTSqZ:-N9ubyuq5heQZUilGMQ6:bvetndg) ([raw file](https://github.com/cockroachdb/cockroach/blob/f56dcfb41d39fdf692ea1300f1e327409d15a8df/pkg/storage/mvcc_incremental_iterator.go#L679)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

How about

- `RangeKeyChanged()` only triggers on filtered range keys, even if `XIgnoringTime` exposes an unseen, out-of-bounds range key.
- `XIgnoringTime() (rangeKeyChanged bool)` returns whether there's now an exclusively ignored rangekey, which can be retrieved via:
- `RangeKeyIgnoringTime() MVCCRangeKeyStack`

This seems good because:

- caching based on `RangeKey` when all you care about is filtered ones "just works"
- don't randomly expose `RangeKey`s that are out of time bounds after a call to `XIgnoringKey`...
- ... but if those are relevant, the event tracking and access to them is there, and
- it's nicely contained in the three methods related to ignoring time bounds.

This is also operating under the assumption that access to out-of-bounds range keys will be somewhat rare. The uses I've seen revolve around discovering a version matching an intent, finding a previous version for withDiff, etc.
Would be interesting to litmus test this with `MVCCPredicateDeleteRange` and/or `MVCCClearRange` since both probably do want to see out-of-bound range dels.
</blockquote></details>

Yeah, let me do another pass over this. Seems reasonable to stick to filtered range keys by default. We may not even need `XIgnoringTime() (rangeKeyChanged bool)` at all -- since `RangeKeyIgnoringTime()` is ~free, the caller can just call it unconditionally when needed.
___
*[`pkg/storage/testdata/mvcc_histories/range_key_iter_incremental` line 129 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86259#-N9fXKJN5tM5zb2NWREN:-N9ubmv4E2d_KZT9gU6L:b-l5wp8r) ([raw file](https://github.com/cockroachdb/cockroach/blob/f56dcfb41d39fdf692ea1300f1e327409d15a8df/pkg/storage/testdata/mvcc_histories/range_key_iter_incremental#L129)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I don't see code in this diff that produces the exclamation mark.
</blockquote></details>

It was added back in #86056, but `MVCCIncrementalIterator` was explicitly omitted because it didn't implement `RangeKeyChanged()`. See changes in `mvcc_history_test.go` which remove those exclusions.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86259)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens and @tbg)

___
*[`pkg/storage/mvcc_incremental_iterator.go` line 679 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86259#-N9fWmY6AAkN8zTeTSqZ:-N9vNuYZ5bFQkPOj19Dy:bhj7vcg) ([raw file](https://github.com/cockroachdb/cockroach/blob/f56dcfb41d39fdf692ea1300f1e327409d15a8df/pkg/storage/mvcc_incremental_iterator.go#L679)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Yeah, let me do another pass over this. Seems reasonable to stick to filtered range keys by default. We may not even need `XIgnoringTime() (rangeKeyChanged bool)` at all -- since `RangeKeyIgnoringTime()` is ~free, the caller can just call it unconditionally when needed.
</blockquote></details>

Done. All standard range key methods now only apply to filtered range keys. Unfiltered range keys are available via `RangeKeysIgnoringTime()`.

The only wart here is that it's now possible for `HasPointAndRange()` to return `false,false` if `NextIgnoringTime` steps onto a bare range key that's outside the time bounds, in violation of the `SimpleMVCCIterator` contract. This isn't really an issue for the current callers, but it is a bit of a footgun so one has to be careful -- then again, one does have to be careful with the `IgnoringTime` methods in general.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86259)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens and @tbg)

___
*[`pkg/storage/mvcc_incremental_iterator.go` line 679 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86259#-N9fWmY6AAkN8zTeTSqZ:-N9vhgMgEe7gTU3Zkb1H:bbi12k7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f56dcfb41d39fdf692ea1300f1e327409d15a8df/pkg/storage/mvcc_incremental_iterator.go#L679)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Done. All standard range key methods now only apply to filtered range keys. Unfiltered range keys are available via `RangeKeysIgnoringTime()`.

The only wart here is that it's now possible for `HasPointAndRange()` to return `false,false` if `NextIgnoringTime` steps onto a bare range key that's outside the time bounds, in violation of the `SimpleMVCCIterator` contract. This isn't really an issue for the current callers, but it is a bit of a footgun so one has to be careful -- then again, one does have to be careful with the `IgnoringTime` methods in general.
</blockquote></details>

Meh, had to add in `RangeKeyChangedIgnoringTime()` too, since it's otherwise possible to land on one of these bare, invisible range keys without detecting it.

See #86512 for the catchup scan "port".

**Review by tbg — COMMENTED** [review]
> Reviewed 3 of 3 files at r5, 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86259)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens and @tbg)

___
*[`pkg/storage/mvcc_incremental_iterator.go` line 679 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86259#-N9fWmY6AAkN8zTeTSqZ:-NA4HvDnCs6MOmp5QU6-:b-8gq745) ([raw file](https://github.com/cockroachdb/cockroach/blob/f56dcfb41d39fdf692ea1300f1e327409d15a8df/pkg/storage/mvcc_incremental_iterator.go#L679)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Meh, had to add in `RangeKeyChangedIgnoringTime()` too, since it's otherwise possible to land on one of these bare, invisible range keys without detecting it.

See #86512 for the catchup scan "port".
</blockquote></details>

Think it's worth removing that last wart, too?

`HasPointAndRange() (hasPoint, hasRange, hasRangeIgnoringTime bool)`?

It seems valuable to have the contract that for a valid iter, `HasPointAndRange()` returns at least one `true`. Most callers could assign while ignoring the third param, if they're pretty sure they didn't call `XIgnoringTime`.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86259)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens and @tbg)

___
*[`pkg/storage/mvcc_incremental_iterator.go` line 679 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86259#-N9fWmY6AAkN8zTeTSqZ:-NA4Jeja71kn0o9ot5Ae:bxkjq6b) ([raw file](https://github.com/cockroachdb/cockroach/blob/f56dcfb41d39fdf692ea1300f1e327409d15a8df/pkg/storage/mvcc_incremental_iterator.go#L679)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Think it's worth removing that last wart, too?

`HasPointAndRange() (hasPoint, hasRange, hasRangeIgnoringTime bool)`?

It seems valuable to have the contract that for a valid iter, `HasPointAndRange()` returns at least one `true`. Most callers could assign while ignoring the third param, if they're pretty sure they didn't call `XIgnoringTime`.
</blockquote></details>

But that method is part of the `SimpleMVCCIterator` interface, so we can't add on a return value.

It seems ok to say that if `Valid()` returns `true` but `HasPointAndRange()` returns `false,false` then we must be on a hidden MVCC range tombstone.

**Review by tbg — APPROVED** [review]
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86259)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens)

**Comment by erikgrinaker** [comment]
TFTR!

bors r=tbg

**Pull request merged**
