### PR TITLE
backupccl: include all tenants in full cluster backup

### PR DESCRIPTION
**Pull request by tbg**
As of this commit, `BACKUP TO x` includes all tenants, and `RESTORE FROM
x` restores them. `WITH REVISION HISTORY` is not yet supported; an error
will result if such a combination is attempted.

Release note: None

### CODE REVIEW

**Comment by dt** [comment]
Heh, I have pretty much exactly this diff stashed locally too. The reason I stashed it and didn't include it in the initial PR was mentioned on that PR though: that `SELECT id, active, info FROM system.tenants` is only run at the end time -- it doesn't capture changes to tenants or tenants that that were added and removed in the backup revision window.  I have a sort-of working changed tenant finder but haven't had a chance to write a test yet.

**Comment by dt** [comment]
changed tenant finding is actually easier than _relevant_ change descriptor finding since tenants are relevant iff the backup is of everything or they're explicitly listed -- we don't need to do any parent ID chasing the way we do for thing like descriptors to build the changed record closure.

**Comment by tbg** [comment]
Thanks for taking a look! I am beginning to understand what you're saying about the changed tenants, but I'm not sure I'm grokking it yet. Are the following examples right:

- t=00: full backup
- t-10: tenant created
- t=20: incremental backup
- later: restore either of the backups

This would work fine, the current code includes tenant 10 in the backup, and since it incrementals `[00,20]` it grabs all of the data.

- t=00: full backup
- t=10: tenant created
- t=15: tenant destroyed
- t=20: incremental backup

Wouldn't this also work fine? We wouldn't see the tenant in either restore, but that's ok (or isn't it? The history for `system.tenants` will be inconsistent with the data in the tenant spans, but it will be anyway - we are intending to ClearRange removed tenants, so you couldn't recover a tenant via time travel anyway, though maybe it's better if works analogously to dropping tables, i.e. we apply the GC TTL?). Is the problem with `WITH REVISION HISTORY` if we tried to restore to some timestamp `10 <= t < 15`? In that case it seems that we would need to include spans for all of the tenants that existed at any timestamp between `startTime` and `endTime`.

Also, somewhat independently, don't we want a bool on the manifest that tells us that all tenants were included (rather than just having an ad-hoc list that semantically wouldn't really have to have all tenants)? For example, I could do a full cluster backup that also includes tenants 2,3,4 (but not 5 which also exists), and then I do an incremental that is supposed to include all tenants on top of it; there doesn't seem to be a good way for the incremental backup to fail (as it should since it's lacking history for tenant 5).

**Comment by dt** [comment]
> WITH REVISION HISTORY if we tried to restore to some timestamp 10 <= t < 15

Exactly -- if you say BACKUP this cluster from time x to time y with revision history, the implied promise if we say "okay, done" is that we can restore the cluster to any time between `x` and `y`, including tenants. I think we could still merge a change that handles non-revision backups, but we'd need to explicitly reject revision backups if the cluster contains tenants until we add changed-tenant finding. That is what I started working on when I tried this, and put it on ice for a few weeks to unblock some other stuff, but the nice thing is it is easier than changed-table finding since tenants don't have parents or any other sort of set-containment we'd need to expand.


> Also, somewhat independently, don't we want a bool on the manifest that tells us that all tenants were included ... rather than just having an ad-hoc list.

We already have this in fact: `DescriptorCoverage` is either `AllDescriptors` (full-cluster) or `RequestedDescriptors` (individual tables/db/tenants).

This should mostly all just work, but in case you're curious:

Adding tables to a set that is being backed up incrementally is where a lot of the complexity in incremental comes, doubly so with revision_history. Typically asking to backup something incrementally that wasn't in the prior backup is an error -- if your prior backup contained `x.a` and `x.b`, you can't make an incremental backup on top of it and ask to include `x.a`, `x.b` **and `x.c`** since prior backup didn't capture `x.c` so what would we be incrementally capturing _from_?. But if your prior backup was of `database x` and you ran `create table x.c` between backups, it'd be really annoying if we told you "waoh, prior backup does not contain c". We did at one point, but then started tracking which dbs were "fully-expanded" by a given backup, and then if we say a new thing in one of those, we'd allow it to be missing. But we still can't _incrementally_ back it up -- what if you _moved_ a table into a DB? it has rows prior to the last backup, but capturing just the ones written after the move -- i.e. what a simple incremental export would do -- would be wrong since it'd be missing those prior rows. So we track things we "fully-expanded" in the CompleteDBs field and allow new things if their parent is in there. But then we have to actually export newly "Introduced" spans _non_ incrementally (and then note that in the key/time 2d covering for RESTORE).

Anyway, I think _most_ of this will just work for tenants: the introduced span stuff is all just on spans, so it will just work. The harder part is revision_history: we need to find _changed_ tenants between start and end time even if they don't exist at end-time. SQL can't do this for us, and indeed even ScanRequest can't, so we need to roll our own, the same way we do changed schema: do an _incremental SSTable export of the tenant table, basically a little mini in-memory backup, and then decode it manually to find the IDs that changed. This is what `getRelevantDescChanges` does for schema, but with a lot of extra code to as mentioned to handle the fact we need to set-expand DBs as well.

**Comment by dt** [comment]
Oh, actually, `getAllDescChanges` is closer to what we want and has none of the annoying parent db stuff that its wrapper has.

**Comment by tbg** [comment]
Ok, the non-revision history version now works. Before I get started on adding revision history support, I think there's enough here to merge this PR? A few questions that popped up were:

1. I ran into an annoyance around the system config trigger. Basically, when RESTORE creates and activates tenants, it touches the system table, and if we're not calling `txn.SetSystemConfigTrigger` in advance (i.e. at the beginning of the txn) it will error out. I wonder if that's acceptable (also cc @nvanbenschoten). We do rely on the tenant table being gossiped (right?) so the behavior seems roughly right, but I wanted to check.
2. I made it an error to try to take a backup that has tenants and revision history on. I think that's sane and I'd like to lift that restriction in a separate PR. (This intermediate step de-risks free tier, since we can work with that status quo just fine)
3. Do we want a separate option to opt into including tenants in the backup? Morally speaking I think that `BACKUP TO` should simply include all tenants, since for a multi-tenancy deployment they pretty much *are* most of the cluster, but it's worth pausing to see what the overall UX here will be. Is there a desire to, down the road, take a full cluster backup with only a select list of tenants? I assume not, though perhaps we'd want to be able to exclude a list of tenants? Not sure, but it also doesn't seem hard to add that with an additional option.
4. Assuming the answer in 3 is "no, always include them" I think I'll need to add the migration that backfills the `system.tenants` table on all existing clusters. Otherwise, we need to awkwardly look at the bootstrap version of the cluster in each `BACKUP` to determine whether the table exists.
5. Do we at all care about how a backup that has tenants in it is handled on old CRDB versions? I'm pretty sure we don't internally, but I wanted to bring it up. At first approximation, I think it would either fail (not sure what checks we have against extra fields in the manifest we don't recognize) or simply skip the tenants, both of which sound reasonable enough (silently skipping sounds weird, but if you're running CRDB that doesn't support tenants, not sure what you expected).

**Comment by tbg** [comment]
This is ready for review now.

**Review by dt — APPROVED** [review]
:lgtm_strong: 

> Reviewed 1 of 1 files at r1, 4 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52096#-:-ME4-9qN3eIGfo8nmIJq:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/ccl/backupccl/restore_job.go, line 863 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52096#-ME3z_zx9h9WBEyhK-XP:-ME3z_zx9h9WBEyhK-XQ:bbbrv5a) ([raw file](https://github.com/cockroachdb/cockroach/blob/477df8f281ff0fdf3e7b74ef0bddf22cfcf96b32/pkg/ccl/backupccl/restore_job.go#L863)):*
> ```Go
> 		err := p.ExecCfg().DB.Txn(ctx, func(ctx context.Context, txn *kv.Txn) error {
> 			if len(details.Tenants) > 0 {
> 				// TODO(during review): if the txn already has txn.Key set, we get an
> ```

Huh, I admit I'm surprised we need this, and don't fully grasp why.
___
*[pkg/ccl/backupccl/restore_job.go, line 1216 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52096#-ME3yo9g8meegYUTUnxD:-ME3yo9g8meegYUTUnxE:b-tnrqs3) ([raw file](https://github.com/cockroachdb/cockroach/blob/477df8f281ff0fdf3e7b74ef0bddf22cfcf96b32/pkg/ccl/backupccl/restore_job.go#L1216)):*
> ```Go
> 			// TODO(dt): this is a noop since the tenant is already active=false but
> 			// that should be fixed in DestroyTenant.
> 			// TODO(during review): why is r.execCfg nil and what's the difference
> ```

eh, better not to use fields on `r` anyway -- they shouldn't be there in the first place, since they're not set by the contructor but rather brittle side-effects of prior functions. We should eliminate them entirely. 

Anyway, all that is to say, this is good as is, no using `r`.

**Comment by dt** [comment]
> Ok, the non-revision history version now works. Before I get started on adding revision history support, I think there's enough here to merge this PR? A few questions that popped up were:
> 
> 1. I ran into an annoyance around the system config trigger. Basically, when RESTORE creates and activates tenants, it touches the system table, and if we're not calling `txn.SetSystemConfigTrigger` in advance (i.e. at the beginning of the txn) it will error out. I wonder if that's acceptable (also cc @nvanbenschoten). We do rely on the tenant table being gossiped (right?) so the behavior seems roughly right, but I wanted to check.

What I don't get is aren't the descriptors we're touching _also_ a gossiped system table? Why doesn't writing to it set the trigger?

> 2. I made it an error to try to take a backup that has tenants and revision history on. I think that's sane and I'd like to lift that restriction in a separate PR. (This intermediate step de-risks free tier, since we can work with that status quo just fine)
👍 

> 3. Do we want a separate option to opt into including tenants in the backup? Morally speaking I think that `BACKUP TO` should simply include all tenants, since for a multi-tenancy deployment they pretty much _are_ most of the cluster, but it's worth pausing to see what the overall UX here will be. Is there a desire to, down the road, take a full cluster backup with only a select list of tenants? I assume not, though perhaps we'd want to be able to exclude a list of tenants? Not sure, but it also doesn't seem hard to add that with an additional option.

full-cluster means full-cluster, and if there are tenants in the cluster, we should include them. We have explicit db or table backups if you want some tables but not the tenants. I think this is good as-is.

> 4. Assuming the answer in 3 is "no, always include them" I think I'll need to add the migration that backfills the `system.tenants` table on all existing clusters. Otherwise, we need to awkwardly look at the bootstrap version of the cluster in each `BACKUP` to determine whether the table exists.

Good catch.

> 5. Do we at all care about how a backup that has tenants in it is handled on old CRDB versions? I'm pretty sure we don't internally, but I wanted to bring it up. At first approximation, I think it would either fail (not sure what checks we have against extra fields in the manifest we don't recognize) or simply skip the tenants, both of which sound reasonable enough (silently skipping sounds weird, but if you're running CRDB that doesn't support tenants, not sure what you expected).

No, the contract is that backups are only readable/restorable by equal of newer versions, so don't need to worry about how old versions handle it.

**Comment by tbg** [comment]
> What I don't get is aren't the descriptors we're touching _also_ a gossiped system table? Why doesn't writing to it set the trigger?

Improving the error shows:

> backup_test.go:5254: error executing 'RESTORE FROM 'nodelocal://1/clusterwide'': pq: activating tenant: activate-tenant: transaction anchor key already set to /Table/3/1/55/2/1, can't set to /Table/SystemConfigSpan/Start

I'm still confused as to why this is happening. We make a new txn in `publishDescriptors` (which is the one I'm looking at now) and by logging a backtrace whenever we set the anchor key I found out that it gets populated here:

https://github.com/cockroachdb/cockroach/blob/f10a6be2459ad68d375daf69085baed895dd9636/pkg/ccl/backupccl/restore_job.go#L1151-L1177

I added TODOs in your name describing that - I'm not sure this is something that's desired. Were we not setting the system config trigger before? That sounds vaguely bad.

**Comment by dt** [comment]
Oh, interesting -- since we make the job before the desc, the txn isn't anchored to config range? huh. I wonder why this ever worked?

**Comment by tbg** [comment]
bors r=dt

> Oh, interesting -- since we make the job before the desc, the txn isn't anchored to config range? huh. I wonder why this ever worked?

Yeah - I sure don't know.

**Pull request merged**
