### PR TITLE
*: add jobID to ctx tags in bulk distsql processors

### PR DESCRIPTION
**Pull request by dt**
It is in the tags in the job's initial context which is what plans and runs these flows, but those tags get lost on the way to  the *remote* processors, so only the one processor that happens to be on the gateway logs with its ID. Instead, these changes now put it explicitly in the processor specs so that we can explicitly add it to the local ctx tags in each processor's initialization.

Release note: none.

Release justification: logging only change.

### CODE REVIEW

**Comment by adityamaru** [comment]
cc: @stevendanna since we briefly chatted about how we wished we had this when grepping for logs

**Review by knz — APPROVED** [review]

**Comment by dt** [comment]
TFTR!

CI failure looks like a flake; race-timeout in TestGCDropIndexSpanExpansion.

bors r+

**Comment by dt** [comment]
Still `TestGCDropIndexSpanExpansion`. 

bors r+

**Comment by adityamaru** [comment]
blathers backport 21.2

**Pull request merged**
