### PR TITLE
sql: miscellaneous cleanup around OUT parameters

### LINKED ISSUE #100405: sql:  support OUT, INOUT argmode in UDF
**Is your feature request related to a problem? Please describe.**
In crdb 21.3 users cannot define UDFs with OUT, INOUT param.
For an example:
```
CREATE FUNCTION add_em (IN x int, IN y int, OUT sum int)
AS 'SELECT x + y'
LANGUAGE SQL;
```
resulted in 
`invalid syntax: statement ignored: at or near "out": syntax error: unimplemented: this syntax`.

**Describe the solution you'd like**
would like crdb to support UDFs creation with `OUT `and `INOUT ` arg mode.
example behavior in postgresSql
```
postgres=# CREATE FUNCTION add_em (IN x int, IN y int, OUT sum int)
AS 'SELECT x + y'
LANGUAGE SQL;
CREATE FUNCTION
```

**Additional context**
[postgres docs](https://www.postgresql.org/docs/current/sql-createfunction.html)

Epic: CRDB-30611
Jira issue: CRDB-26414

### LINKED ISSUE #120932: roachtest: pg_regress failed
roachtest.pg_regress [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyBazel/14521703?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyBazel/14521703?buildTab=artifacts#/pg_regress) on master @ [4a9385cacb82e7a8d6d37e5d9a26a6b7c845aab6](https://github.com/cockroachdb/cockroach/commits/4a9385cacb82e7a8d6d37e5d9a26a6b7c845aab6):

```
    RAISE EXCEPTION 'rewrites not allowed';
  END;
  $$;
@@ -276381,7 +276405,7 @@
  alter table rewriteme add column baz int default 0;
  -- test with more than one reason to rewrite a single table
  CREATE OR REPLACE FUNCTION test_evtrig_no_rewrite() RETURNS event_trigger
-@@ -511,18 +723,36 @@
+@@ -511,18 +719,36 @@
                 pg_event_trigger_table_rewrite_reason();
  END;
  $$;
@@ -276420,7 +276444,7 @@
  begin;
  set timezone to 'UTC';
  alter table rewriteme alter column bar type timestamp;
-@@ -530,7 +760,6 @@
+@@ -530,7 +756,6 @@
  alter table rewriteme alter column bar type timestamptz;
  set timezone to 'Europe/London';
  alter table rewriteme alter column bar type timestamp; -- does rewrite
@@ -276428,7 +276452,7 @@
  rollback;
  -- typed tables are rewritten when their type changes.  Don't emit table
  -- name, because firing order is not stable.
-@@ -541,21 +770,52 @@
+@@ -541,21 +766,52 @@
                 pg_event_trigger_table_rewrite_reason();
  END;
  $$;
@@ -276484,7 +276508,7 @@
  CREATE TABLE event_trigger_test (a integer, b text);
  CREATE OR REPLACE FUNCTION start_command()
  RETURNS event_trigger AS $$
-@@ -563,37 +823,66 @@
+@@ -563,37 +819,66 @@
  RAISE NOTICE '% - ddl_command_start', tg_tag;
  END;
  $$ LANGUAGE plpgsql;
@@ -276560,7 +276584,7 @@
  -- Check the object addresses of all the event triggers.
  SELECT
      e.evtname,
-@@ -604,13 +893,22 @@
+@@ -604,13 +889,22 @@
      LATERAL pg_identify_object_as_address('pg_event_trigger'::regclass, e.oid, 0) as b,
      LATERAL pg_get_object_address(b.type, b.object_names, b.object_args) as a
    ORDER BY e.evtname;
If the diff is expected, copy regression.diffs from the test artifacts to pkg/cmd/roachtest/testdata/regression.diffs
test artifacts and logs in: /artifacts/pg_regress/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-14521703/pg-regress/1711178283273/1711178963549)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*pg_regress.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-36954

### LINKED ISSUE #120989: sql/tests: TestRandomSyntaxGeneration failed [CALL statement causes "expected FuncExpr"]
sql/tests.TestRandomSyntaxGeneration [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RandomSyntaxTestsBazel/14549406?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RandomSyntaxTestsBazel/14549406?buildTab=artifacts#/) on master @ [c994982a8be5af89f594e115e897dd6d62cf99d8](https://github.com/cockroachdb/cockroach/commits/c994982a8be5af89f594e115e897dd6d62cf99d8):

Random syntax error:

```
    rsg_test.go:909: Crash detected: server panic: pq: internal error: expected FuncExpr
```
Query:

```
        CALL [ FUNCTION 165 ] ( * );
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRandomSyntaxGeneration.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-36991

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit adjusts the code slightly so that in case a user attempts to CALL not a procedure (but a special function like an aggregate, a window function, or our custom SQL function) we return the same error as postgres (previously we would return an internal error in some cases).

Additionally, it disables calling procedures with output parameters from SQL UDFs and SPs - this feature is currently unsupported in postgres. Note that calling procedures with output parameters from PLpgSQL is supported by PG but not yet supported by us (this commit includes some commented out unit tests for that).

Furthermore, this commit updates sqlsmith to generate all supported parameter types as well as adjusts a few TODOs to reference a different issue number (where we currently hit an internal error) in order to remove remaining references of the OUT parameter issue.

Fixes: #100405.
Fixes: #120932.
Fixes: #120989.

Release note: None

### CODE REVIEW

**Review by DrewKimball — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120945)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

___
*[`-- commits` line 14 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120945#-Ntii8qx4OZUZR8RbbnN):*
Huh, TIL.
___
*[`pkg/sql/routine.go` line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120945#-Ntinohb-KetKsZrzBNY:-Ntinohb-KetKsZrzBNZ:b5u9k6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d927a517f56c64956679016f9cbbfd3dbfade33/pkg/sql/routine.go#L56)):*
> ```Go
> 	if res == tree.DNull {
> 		// No rows were produced by the last statement.
> 		return nil
> ```

In this case, shouldn't there be a NULL for each column? We should probably directly use `routineGenerator` instead of calling `eval.Expr`, but maybe for now it would be fine to just look at the return type.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120945)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/routine.go` line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120945#-Ntinohb-KetKsZrzBNY:-Ntm11YU1T4j5dY_nheP:bur2q00) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d927a517f56c64956679016f9cbbfd3dbfade33/pkg/sql/routine.go#L56)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

In this case, shouldn't there be a NULL for each column? We should probably directly use `routineGenerator` instead of calling `eval.Expr`, but maybe for now it would be fine to just look at the return type.
</blockquote></details>

Hm, you're asking an interesting question. I applied the following diff:
```
--- a/pkg/sql/routine.go
+++ b/pkg/sql/routine.go
@@ -51,10 +51,6 @@ func (d *callNode) startExec(params runParams) error {
                }
                return nil
        }
-       if res == tree.DNull {
-               // No rows were produced by the last statement.
-               return nil
-       }
        tuple, ok := tree.AsDTuple(res)
        if !ok {
                return errors.AssertionFailedf("expected a tuple, got %T", res)
@@ -157,6 +153,11 @@ func (p *planner) EvalRoutineExpr(
                }
                res = row[0]
        }
+       if rt := expr.ResolvedType(); expr.Procedure && rt.Family() == types.TupleFamily {
+               if _, ok := tree.AsDTuple(res); !ok {
+                       res = tree.NewDTuple(rt, res)
+               }
+       }
        if len(args) == 0 && !expr.EnableStepping {
                // Cache the result if there are zero arguments and stepping is
                // disabled.
```
and now `CALL p(17)` from the newly-added test produces two rows in the result
```
NULL
17
```
Here is the test:
```sql
CREATE TABLE temp (k INT PRIMARY KEY);

CREATE PROCEDURE p(INOUT param INT) AS $$
BEGIN
  INSERT INTO temp VALUES(param);
  COMMIT;
END; $$ LANGUAGE PLpgSQL;

CALL p(17);
```
It seems like what happens is that we first evaluate `CALL p` statement with `isFinalPlan = true` (which produces the NULL row) and then we evaluate two stmts within the procedure (which produces the 17 row due to INOUT parameter).

I'm confused about the interaction with different "continuations" when building this procedure - do you mind taking a closer look? Like it seems that we have `isFinalPlan == true` for two different plans for a single procedure which seems wrong.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120945)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/routine.go` line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120945#-Ntinohb-KetKsZrzBNY:-NtmANKH5CmbQaU8rBcl:bsari3) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d927a517f56c64956679016f9cbbfd3dbfade33/pkg/sql/routine.go#L56)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Hm, you're asking an interesting question. I applied the following diff:
```
--- a/pkg/sql/routine.go
+++ b/pkg/sql/routine.go
@@ -51,10 +51,6 @@ func (d *callNode) startExec(params runParams) error {
                }
                return nil
        }
-       if res == tree.DNull {
-               // No rows were produced by the last statement.
-               return nil
-       }
        tuple, ok := tree.AsDTuple(res)
        if !ok {
                return errors.AssertionFailedf("expected a tuple, got %T", res)
@@ -157,6 +153,11 @@ func (p *planner) EvalRoutineExpr(
                }
                res = row[0]
        }
+       if rt := expr.ResolvedType(); expr.Procedure && rt.Family() == types.TupleFamily {
+               if _, ok := tree.AsDTuple(res); !ok {
+                       res = tree.NewDTuple(rt, res)
+               }
+       }
        if len(args) == 0 && !expr.EnableStepping {
                // Cache the result if there are zero arguments and stepping is
                // disabled.
```
and now `CALL p(17)` from the newly-added test produces two rows in the result
```
NULL
17
```
Here is the test:
```sql
CREATE TABLE temp (k INT PRIMARY KEY);

CREATE PROCEDURE p(INOUT param INT) AS $$
BEGIN
  INSERT INTO temp VALUES(param);
  COMMIT;
END; $$ LANGUAGE PLpgSQL;

CALL p(17);
```
It seems like what happens is that we first evaluate `CALL p` statement with `isFinalPlan = true` (which produces the NULL row) and then we evaluate two stmts within the procedure (which produces the 17 row due to INOUT parameter).

I'm confused about the interaction with different "continuations" when building this procedure - do you mind taking a closer look? Like it seems that we have `isFinalPlan == true` for two different plans for a single procedure which seems wrong.
</blockquote></details>

I think part of my confusion was due to tail call optimization. Once I disable it, the control flow makes a bit more sense to me. I see that when we're handling `ast.TransactionControl` for the COMMIT stmt, at the end of `callContinuationWithTxnOp` we have the following expression tree: `returnScope.expr = ProjectExpr -> BarrierExpr -> ValuesExpr`, that ValuesExpr has 1 row of 0 columns, and this is what's converted into `unaryNode` during the execution and eventually emits a single NULL row. So to me it looks like something is off when handling `ast.TransactionControl`. Perhaps the fact that we have INOUT parameter that is passed through to the continuation somehow messes things up.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120945)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

___
*[`pkg/sql/routine.go` line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120945#-Ntinohb-KetKsZrzBNY:-NtnVS2NE9bd2inShcf3:b-ysii3e) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d927a517f56c64956679016f9cbbfd3dbfade33/pkg/sql/routine.go#L56)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I think part of my confusion was due to tail call optimization. Once I disable it, the control flow makes a bit more sense to me. I see that when we're handling `ast.TransactionControl` for the COMMIT stmt, at the end of `callContinuationWithTxnOp` we have the following expression tree: `returnScope.expr = ProjectExpr -> BarrierExpr -> ValuesExpr`, that ValuesExpr has 1 row of 0 columns, and this is what's converted into `unaryNode` during the execution and eventually emits a single NULL row. So to me it looks like something is off when handling `ast.TransactionControl`. Perhaps the fact that we have INOUT parameter that is passed through to the continuation somehow messes things up.
</blockquote></details>

Ah, that's interesting. So, what should be happening is the first result is discarded by the connExecutor, and then the second one (resulting from [this](https://github.com/cockroachdb/cockroach/blob/c994982a8be5af89f594e115e897dd6d62cf99d8/pkg/sql/plan_opt.go#L536-L542) code path) is the final result. That might require some additional changes now that we have OUT parameters - we don't want results to be flushed to the client until we know it's the final iteration, and we don't know that until the final iteration has executed.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120945)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

___
*[`pkg/sql/routine.go` line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120945#-Ntinohb-KetKsZrzBNY:-NtnXuMyBH7lwEpaXfPA:b-simssr) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d927a517f56c64956679016f9cbbfd3dbfade33/pkg/sql/routine.go#L56)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Ah, that's interesting. So, what should be happening is the first result is discarded by the connExecutor, and then the second one (resulting from [this](https://github.com/cockroachdb/cockroach/blob/c994982a8be5af89f594e115e897dd6d62cf99d8/pkg/sql/plan_opt.go#L536-L542) code path) is the final result. That might require some additional changes now that we have OUT parameters - we don't want results to be flushed to the client until we know it's the final iteration, and we don't know that until the final iteration has executed.
</blockquote></details>

I think this might be the right thing to do:
```
diff --git a/pkg/sql/routine.go b/pkg/sql/routine.go
index cc1be441562..7d12daf8282 100644
--- a/pkg/sql/routine.go
+++ b/pkg/sql/routine.go
@@ -43,6 +43,12 @@ func (d *callNode) startExec(params runParams) error {
        if err != nil {
                return err
        }
+       if params.p.storedProcTxnState.getResumeProc() != nil {
+               // The current iteration of this stored procedure is requesting to COMMIT
+               // or ROLLBACK the current transaction, and resume execution in a new one.
+               // The current result should be discarded.
+               return nil
+       }
        if d.proc.Typ.Family() == types.VoidFamily {
                // With VOID return type we expect no rows to be pr
```

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120945)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/routine.go` line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120945#-Ntinohb-KetKsZrzBNY:-NtqZSWv9HL76zxsrvfg:b-xryuy9) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d927a517f56c64956679016f9cbbfd3dbfade33/pkg/sql/routine.go#L56)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

I think this might be the right thing to do:
```
diff --git a/pkg/sql/routine.go b/pkg/sql/routine.go
index cc1be441562..7d12daf8282 100644
--- a/pkg/sql/routine.go
+++ b/pkg/sql/routine.go
@@ -43,6 +43,12 @@ func (d *callNode) startExec(params runParams) error {
        if err != nil {
                return err
        }
+       if params.p.storedProcTxnState.getResumeProc() != nil {
+               // The current iteration of this stored procedure is requesting to COMMIT
+               // or ROLLBACK the current transaction, and resume execution in a new one.
+               // The current result should be discarded.
+               return nil
+       }
        if d.proc.Typ.Family() == types.VoidFamily {
                // With VOID return type we expect no rows to be pr
```
</blockquote></details>

I see. Unfortunately, this diff didn't just work because when we're executing the second (and final) `callNode`, `resumeProc` is still non-nil. It is used to create the plan for that second `callNode`, and we only reset `resumeProc` when control flow goes back to the connExecutor, after having executed the second `callNode`.

Perhaps, when we have non-nil `resumeProc`, we need to use an intermediate buffer for results that we will flush at the same time as when we're resetting `resumeProc` in the connExecutor if the execution was successful. For now, I pulled out this change - this issue was exposed in the pgjdbc roachtest and is tracked in #119937.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120945)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/opt/optbuilder/routine.go` line 134 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/120945#-NtqkmyZ7mt9E3pkfetq:-Ntr7eoLCjEFgEfocnm6:b-ycw1zc) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3b0b10afdf49e3ae01cb4803c626ea2c250b3bc/pkg/sql/opt/optbuilder/routine.go#L134)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I think the solution here needs to be expanded. The `scope.VisitPre` function can replace window functions with a variety of `tree.Expr`s, including `tree.DNull`, a `scopeColumn` for window functions. I'm thinking that this should always be a user error "xxx() is not a procedure" if `typedExpr` is not a `tree.FuncExpr`.
</blockquote></details>

Done (although I'm not sure whether we can come up with type names for the arguments, so I reduced the error message a bit).

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120945)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

___
*[`pkg/sql/routine.go` line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120945#-Ntinohb-KetKsZrzBNY:-NtrdRbBAY_indQ4mtLc:b1eu0fb) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d927a517f56c64956679016f9cbbfd3dbfade33/pkg/sql/routine.go#L56)):*
>For now, I pulled out this change

SGTM. For what it's worth, it'll be easy to set `resumeProc` to nil immediately after we retrieve it - the only reason I didn't do it before is that it was nice to only reset it in a single location on the connExecutor.

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120945#-:-Ntre0Kp9nb13_siwReN:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

**Comment by yuzefovich** [comment]
It'll conflict with #120733.

bors r-

**Comment by DrewKimball** [comment]
(https://github.com/cockroachdb/cockroach/pull/120733 just merged)

**Pull request merged**
