### PR TITLE
kv,changefeedccl: Mark timeout when nudging a range as retryable

### PR DESCRIPTION
**Pull request by HonoreDB**
Fixing a possible cause for #67973 -- an attempt to establish a
rangefeed that encounters no lease and times out trying to create
one seems like it may be bubbling up to cdc under chaos, when it's
likely to succeed if it retries.

I haven't been able to find a path in testing that actually hits
this, since the async nudging effectively retries forever anyway
so this only matters if somehow the rangefeed creation happens right
as we're getting into a bad state.

Release note: None

### CODE REVIEW

**Review by miretskiy — COMMENTED** [review]
> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68347)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, and @HonoreDB)

___
*[pkg/kv/kvserver/replica_rangefeed.go, line 155 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68347#-Mg7qol6D0-E5Q5Ckppp:-Mg7qol6D0-E5Q5Ckppq:b-btcsva) ([raw file](https://github.com/cockroachdb/cockroach/blob/10abac9fa26b52cb8f8231396702ecc09b1f995e/pkg/kv/kvserver/replica_rangefeed.go#L155)):*
> ```Go
> 
> 	if err := r.ensureClosedTimestampStarted(ctx); err != nil {
> 		if errors.HasType(err.GoError(), (*contextutil.TimeoutError)(nil)) {
> ```

Would it make sense to check that the error is TimeoutError right at the call site (in `ensureClosedTimestampStarted`) and return correct RangeFeedError from there instead?
___
*[pkg/util/contextutil/timeout_error.go, line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68347#-Mg7qXiz7j9RRCaC01us:-Mg7qXiz7j9RRCaC01ut:b-gy33le) ([raw file](https://github.com/cockroachdb/cockroach/blob/10abac9fa26b52cb8f8231396702ecc09b1f995e/pkg/util/contextutil/timeout_error.go#L68)):*
> ```Go
> 
> // Build a fake timeout error for tests
> func MockTimeoutError() *TimeoutError {
> ```

do we need this here? Why not inline this in the test?

**Review by ajwerner — COMMENTED** [review]
I think your test is somewhat missing what we're trying to exercise. The most important thing to exercise is that when we *start* a new rangefeed while there is no valid lease that the error that comes back does not make it to the client but rather gets retried at the distsender. I'd feel good if you wrote a test that first gets an error upon the initial `RangeFeed` call because there is no lease and we inject the lease failure and then make the change as made in this PR and see that it now retries internally instead of propagating that error. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68347#-:-Mg83YnPCdkdCJ8SLKD8:boseael)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @HonoreDB)

**Review by HonoreDB — COMMENTED** [review]
I agree, the test definitely isn't exercising the actual fix, just verifying that it doesn't regress. I'm still working on getting the test you describe to work. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68347#-:-Mg8Ps-1EpZ_PflyGHS_:boea5ek)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @miretskiy)

___
*[pkg/kv/kvserver/replica_rangefeed.go, line 155 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68347#-Mg7qol6D0-E5Q5Ckppp:-Mg8OttD4kIYW4C7dVUx:bd7jkzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/10abac9fa26b52cb8f8231396702ecc09b1f995e/pkg/kv/kvserver/replica_rangefeed.go#L155)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Would it make sense to check that the error is TimeoutError right at the call site (in `ensureClosedTimestampStarted`) and return correct RangeFeedError from there instead?
</blockquote></details>

That's how I had it before, Andrew suggested moving it here because I guess this is the only place we already have access to the `stream`
___
*[pkg/util/contextutil/timeout_error.go, line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68347#-Mg7qXiz7j9RRCaC01us:-Mg8PDh_1rDoWFF39GFH:b6x9wlx) ([raw file](https://github.com/cockroachdb/cockroach/blob/10abac9fa26b52cb8f8231396702ecc09b1f995e/pkg/util/contextutil/timeout_error.go#L68)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

do we need this here? Why not inline this in the test?
</blockquote></details>

I think there's no public constructor (`TimeoutError{}` creates an infinite loop when being handled), and I need the type to match, so I think I'm stuck?

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68347)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @HonoreDB)

___
*[pkg/kv/kvserver/replica_rangefeed.go, line 155 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68347#-Mg7qol6D0-E5Q5Ckppp:-MgB5q0BEb6M6AyNqwfZ:bqvewyg) ([raw file](https://github.com/cockroachdb/cockroach/blob/10abac9fa26b52cb8f8231396702ecc09b1f995e/pkg/kv/kvserver/replica_rangefeed.go#L155)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

That's how I had it before, Andrew suggested moving it here because I guess this is the only place we already have access to the `stream`
</blockquote></details>

Sure; but seeing TimeoutError here is strange -- while seeing it immediately after the call to WithDeadline is a lot less strange and more readable in my opinion.   I could be wrong though.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68347)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @miretskiy)

___
*[pkg/kv/kvserver/replica_rangefeed.go, line 155 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68347#-Mg7qol6D0-E5Q5Ckppp:-MgBffULCyucbUQwQnLi:b-62glby) ([raw file](https://github.com/cockroachdb/cockroach/blob/10abac9fa26b52cb8f8231396702ecc09b1f995e/pkg/kv/kvserver/replica_rangefeed.go#L155)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Sure; but seeing TimeoutError here is strange -- while seeing it immediately after the call to WithDeadline is a lot less strange and more readable in my opinion.   I could be wrong though.
</blockquote></details>

Seems fine to convert it at the lower level. Sorry for the confusion. This level just needs to send it rather than return it (I think).

**Review by HonoreDB — COMMENTED** [review]
Okay, actual test added that fails on master and passes here.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68347#-:-MgCJHAY71Ap8DqbNf4G:b-98jd9e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @miretskiy)

___
*[pkg/kv/kvserver/replica_rangefeed.go, line 155 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68347#-Mg7qol6D0-E5Q5Ckppp:-MgCJAHO8ftAQv0fUbMP:b-b7zlvk) ([raw file](https://github.com/cockroachdb/cockroach/blob/10abac9fa26b52cb8f8231396702ecc09b1f995e/pkg/kv/kvserver/replica_rangefeed.go#L155)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Seems fine to convert it at the lower level. Sorry for the confusion. This level just needs to send it rather than return it (I think). 
</blockquote></details>

Ah, that makes sense. Done.

**Review by ajwerner — APPROVED** [review]
:lgtm: mod nits

> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68347#-:-MgCpUHEDREtsG2-QuF1:b-tkmfg9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @HonoreDB, and @miretskiy)

___
*[pkg/kv/kvserver/replica_rangefeed_test.go, line 1179 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68347#-MgCp9BVEp1MnS1GW7nm:-MgCp9BWDmeN4z4EnB8l:byafkie) ([raw file](https://github.com/cockroachdb/cockroach/blob/716da9446b17811081eca86794cc4636d6525244/pkg/kv/kvserver/replica_rangefeed_test.go#L1179)):*
> ```Go
> 	var rejectExtraneousRequests int64 // accessed atomically
> 
> 	var timeoutSimulated int64
> ```

given you're not using atomics on this thing, should it just be a `bool`?
___
*[pkg/kv/kvserver/replica_rangefeed_test.go, line 1299 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68347#-MgCpHNM3roLRuMV28G5:-MgCnCia-acEJcCLP7Op:b-850tir) ([raw file](https://github.com/cockroachdb/cockroach/blob/716da9446b17811081eca86794cc4636d6525244/pkg/kv/kvserver/replica_rangefeed_test.go#L1299)):*
> ```
> 	resumeHeartbeats()
> 	go startRangefeed()
> ```

Is there any way to confirm you've hit the error before you resume the heartbeats? Like can we wait until nudge has been seen before resuming the heartbeats?
___
*[pkg/roachpb/errors.proto, line 494 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68347#-MgCpc065IlT1DBI53Ha:-MgCpc065IlT1DBI53Hb:b-8so11) ([raw file](https://github.com/cockroachdb/cockroach/blob/716da9446b17811081eca86794cc4636d6525244/pkg/roachpb/errors.proto#L494)):*
> ```protobuf
>     // events.
>     REASON_SLOW_CONSUMER = 5;
>     // No leaseholder exists or could be created, so closed timestamps won't be emitted
> ```

nit: period
___
*[pkg/util/contextutil/timeout_error.go, line 71 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68347#-MgCoAZj3YuGx1ufQr5c:-MgCoAZj3YuGx1ufQr5d:b4a093z) ([raw file](https://github.com/cockroachdb/cockroach/blob/716da9446b17811081eca86794cc4636d6525244/pkg/util/contextutil/timeout_error.go#L71)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> // MockTimeoutError builds a fake timeout error for tests
> func MockTimeoutError() *TimeoutError {
> 	t := &TimeoutError{operation: "op", duration: time.Second * 0, cause: errors.New("cause")}
> 	return t
> }
> ```
</details>

Maybe upsetting but you could use the following instead of adding this:

```
	timeoutErr := contextutil.RunWithTimeout(ctx, "test", 0,
		func(ctx context.Context) error { <-ctx.Done(); return ctx.Err() })
```

**Review by HonoreDB — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68347)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andreimatei, and @miretskiy)

___
*[pkg/kv/kvserver/replica_rangefeed.go, line 155 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68347#-Mg7qol6D0-E5Q5Ckppp:-MgCsmWe6EpNXP4ZVdfb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/10abac9fa26b52cb8f8231396702ecc09b1f995e/pkg/kv/kvserver/replica_rangefeed.go#L155)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Ah, that makes sense. Done.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replica_rangefeed_test.go, line 1179 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68347#-MgCp9BVEp1MnS1GW7nm:-MgCsnl1-y31huRy8YFY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/716da9446b17811081eca86794cc4636d6525244/pkg/kv/kvserver/replica_rangefeed_test.go#L1179)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

given you're not using atomics on this thing, should it just be a `bool`?
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replica_rangefeed_test.go, line 1299 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68347#-MgCpHNM3roLRuMV28G5:-MgCt0N-E-cK6BFbDQbU:bvbph1x) ([raw file](https://github.com/cockroachdb/cockroach/blob/716da9446b17811081eca86794cc4636d6525244/pkg/kv/kvserver/replica_rangefeed_test.go#L1299)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	resumeHeartbeats()
> 	go startRangefeed()
> ```

Is there any way to confirm you've hit the error before you resume the heartbeats? Like can we wait until nudge has been seen before resuming the heartbeats?
</blockquote></details>

I don't think I do need to hit the error before resuming the heartbeats--the pause is to cause the lease to expire, as I understand it. The error is getting hit when I start the rangefeed.
___
*[pkg/roachpb/errors.proto, line 494 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68347#-MgCpc065IlT1DBI53Ha:-MgCsqBq89Qf4NFQi25X:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/716da9446b17811081eca86794cc4636d6525244/pkg/roachpb/errors.proto#L494)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: period
</blockquote></details>

Done.
___
*[pkg/util/contextutil/timeout_error.go, line 71 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68347#-MgCoAZj3YuGx1ufQr5c:-MgCsrAc3tGBgQ3COTy5:b-1upkpr) ([raw file](https://github.com/cockroachdb/cockroach/blob/716da9446b17811081eca86794cc4636d6525244/pkg/util/contextutil/timeout_error.go#L71)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> // MockTimeoutError builds a fake timeout error for tests
> func MockTimeoutError() *TimeoutError {
> 	t := &TimeoutError{operation: "op", duration: time.Second * 0, cause: errors.New("cause")}
> 	return t
> }
> ```
Maybe upsetting but you could use the following instead of adding this:

```
	timeoutErr := contextutil.RunWithTimeout(ctx, "test", 0,
		func(ctx context.Context) error { <-ctx.Done(); return ctx.Err() })
```
</blockquote></details>

That's horrifying, I love it. Done.

**Comment by HonoreDB** [comment]
TFTR!

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68347)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @andreimatei, @HonoreDB, and @miretskiy)

___
*[pkg/kv/kvserver/replica_rangefeed_test.go, line 1299 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/68347#-MgCpHNM3roLRuMV28G5:-MgD8oLE-8phLlxYO2qM:b6yf1lz) ([raw file](https://github.com/cockroachdb/cockroach/blob/716da9446b17811081eca86794cc4636d6525244/pkg/kv/kvserver/replica_rangefeed_test.go#L1299)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

I don't think I do need to hit the error before resuming the heartbeats--the pause is to cause the lease to expire, as I understand it. The error is getting hit when I start the rangefeed.
</blockquote></details>

Right but in the meantime it seems possible for the lease to get reestablished before you start the rangefeed if, say, a queue runs. I’m interested in shaking out flakes.

**Comment by HonoreDB** [comment]
bors r+
I'd like to merge this tonight to potentially unblock the release or at least see how this does under the full chaos suite. I think it prevents flakes as-is by blocking extraneous requests, but we'll see.

**Pull request merged**
