### PR TITLE
server: define all RPCs in terms of grpc-gateway

### PR DESCRIPTION
**Pull request by tamird**
Finally removes httprouter and fixes ##8569.

cc @maxlang

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8576)

### CODE REVIEW

**Comment by cuongdo** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8576#-:-KPJ0xx4uEpCPTcZw8Hm:bnfp4nl)*

**Comment by BramGruneir** [comment]
:lgtm:

---

Reviewed 10 of 11 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[server/status.go, line 56 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8576#-KPJ-WgBeq2J7AfYfDfE:-KPJ-WgBeq2J7AfYfDfF:b-1zvtf5) ([raw file](https://github.com/cockroachdb/cockroach/blob/750f5d01f06ea79dde964fb5d87c2f933569ba29/server/status.go#L56)):*
> ```Go
> const (
> 	/*
> 	   Note that :node_id can always be replaced by the value "local" to see
> ```

Might be worth keeping some of this comment around, as it has instructions as it describes all the different endpoints.

---

*[server/status.go, line 100 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8576#-KPJ-lPlBH6UErL_3nAC:-KPJ-lPlBH6UErL_3nAD:b7fvfp7) ([raw file](https://github.com/cockroachdb/cockroach/blob/73d2a4e3338c57008fb356280b7e2f53cbd85b95/server/status.go#L100)):*
> ```Go
> 	}
> 
> 	// TODO(tschottdorf): significant overlap with /debug/pprof/goroutine,
> ```

Is this comment still appropriate?  Perhaps move it somewhere else.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8576#-:-KPJ28MaW-EOFssR_w4H:bnfp4nl)*

**Comment by bdarnell** [comment]
This looks like it should go in `develop` instead of `master`.

**Comment by maxlang** [comment]
:lgtm: 

Ran a cursory check on the branch and data is being pulled correctly into the UI.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8576#-:-KPJFFwBBvHKS8EIFQui:bc6toqc)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[server/status.go, line 56 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8576#-KPJ-WgBeq2J7AfYfDfE:-KPJKA6PHWq3nJnRvcOz:b-fezc5r) ([raw file](https://github.com/cockroachdb/cockroach/blob/750f5d01f06ea79dde964fb5d87c2f933569ba29/server/status.go#L56)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary>
> Might be worth keeping some of this comment around, as it has instructions as it describes all the different endpoints.
</details>
It's just begging to rot, though. Just look at the proto.

---

*[server/status.go, line 100 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8576#-KPJ-lPlBH6UErL_3nAC:-KPJKQ2OQF7D83Prr_ZY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/73d2a4e3338c57008fb356280b7e2f53cbd85b95/server/status.go#L100)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary>
> Is this comment still appropriate?  Perhaps move it somewhere else.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8576)*

**Comment by BramGruneir** [comment]
Reviewed 1 of 11 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[server/status.go, line 56 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8576#-KPJ-WgBeq2J7AfYfDfE:-KPJKrjhG11jMrBlr9ZS:b-9u9ogp) ([raw file](https://github.com/cockroachdb/cockroach/blob/750f5d01f06ea79dde964fb5d87c2f933569ba29/server/status.go#L56)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> It's just begging to rot, though. Just look at the proto.
</details>
Could you move the comments to before each service call in the proto then?  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8576)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/status.go, line 56 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8576#-KPJ-WgBeq2J7AfYfDfE:-KPJTbIi3RkP7ngNdEuT:b-fpjhoc) ([raw file](https://github.com/cockroachdb/cockroach/blob/750f5d01f06ea79dde964fb5d87c2f933569ba29/server/status.go#L56)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary>
> Could you move the comments to before each service call in the proto then?  
</details>
What exactly are you trying to salvage? The routes are already listed in the proto.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8576)*

**Comment by BramGruneir** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/status.go, line 56 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8576#-KPJ-WgBeq2J7AfYfDfE:-KPJTufgRmrody7MNyY9:bfj3d1) ([raw file](https://github.com/cockroachdb/cockroach/blob/750f5d01f06ea79dde964fb5d87c2f933569ba29/server/status.go#L56)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> What exactly are you trying to salvage? The routes are already listed in the proto.
</details>
The explanation on what the routes actual do.  And the fact that you can use local in place of :node_id.

This was a nice succinct listing of all status endpoints, with an explanation of what they do.  That's lost now as you have to jump between both the proto and the status code to understand what's going on.  Most are clear based on the name of the function, but it's still nice to see for someone who hasn't touched the code before (or hasn't touched it in a while).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8576)*

**Comment by tamird** [comment]
Review status: 4 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[server/status.go, line 56 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8576#-KPJ-WgBeq2J7AfYfDfE:-KPJZQyA_dTOzm3tcnxk:bfv59ah) ([raw file](https://github.com/cockroachdb/cockroach/blob/750f5d01f06ea79dde964fb5d87c2f933569ba29/server/status.go#L56)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary>
> The explanation on what the routes actual do.  And the fact that you can use local in place of :node_id.
> 
> This was a nice succinct listing of all status endpoints, with an explanation of what they do.  That's lost now as you have to jump between both the proto and the status code to understand what's going on.  Most are clear based on the name of the function, but it's still nice to see for someone who hasn't touched the code before (or hasn't touched it in a while).
</details>
Added comments in the proto.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8576)*

**Comment by BramGruneir** [comment]
Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8576)*

**Pull request merged**
