### PR TITLE
client: CommitBy takes Timestamp by value

### PR DESCRIPTION
**Pull request by tamird**
@petermattis this addresses your review comments, though in a different way than you suggested.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3043)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[client/txn.go, line 346 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3043#-K2YaQrxBBqmFmcUDV4-)** ([raw file](https://github.com/cockroachdb/cockroach/blob/c633c5b1460760e9bdfd52768d7ea0443cb341a7/client/txn.go#L346)):</sup>
This (very likely) causes an allocation.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3043)

**Comment by tamird** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[client/txn.go, line 346 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3043#-K2YaQrxBBqmFmcUDV4-)** ([raw file](https://github.com/cockroachdb/cockroach/blob/c633c5b1460760e9bdfd52768d7ea0443cb341a7/client/txn.go#L346)):</sup>
I'm not sure it will, since it doesn't escape, but even if it does, I think the semantics of CommitBy always taking a non-nil Timestamp are more important for now.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3043)

**Comment by petermattis** [comment]
LGTM


---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[client/txn.go, line 346 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3043#-K2YaQrxBBqmFmcUDV4-)** ([raw file](https://github.com/cockroachdb/cockroach/blob/c633c5b1460760e9bdfd52768d7ea0443cb341a7/client/txn.go#L346)):</sup>
The compiler's escape analysis never crosses function boundaries. So it only won't escape if `txn.commit` is inlined which seems unlikely. Regardless, I think this is ok for now, just want to make sure you realize that passing by value and then converting to a pointer usually causes an allocation. 


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3043)

**Comment by tamird** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

<sup>**[client/txn.go, line 346 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3043#-K2YaQrxBBqmFmcUDV4-)** ([raw file](https://github.com/cockroachdb/cockroach/blob/c633c5b1460760e9bdfd52768d7ea0443cb341a7/client/txn.go#L346)):</sup>
> The compiler's escape analysis never crosses function boundaries.

Thanks, I didn't know that.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3043)

**Pull request merged**
