### PR TITLE
sql: fix over parallelization of sqllite tests and revert a scapel left in patient

### LINKED ISSUE #78690: sql: logictest leaks memory
```
make test 'TESTFLAGS=-memprofile=mem.out vv -bigtest -flex-types' TESTTIMEOUT=24h PKG=./pkg/sql/logictest 'TESTS=^TestSqlLiteLogic/local/slt_good_0.test' TAGS=crdb_test_off
```

```
❯ go tool pprof mem.out
File: logictest.test
Build ID: f25562c981de7971c6ec0341c073a16fcd6f0ac0
Type: alloc_space
Time: Mar 28, 2022 at 5:21pm (UTC)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 522.93GB, 45.48% of 1149.78GB total
Dropped 6760 nodes (cum <= 5.75GB)
Showing top 10 nodes out of 485
      flat  flat%   sum%        cum   cum%
  185.38GB 16.12% 16.12%   221.53GB 19.27%  github.com/cockroachdb/cockroach/pkg/util/pretty.(*beExec).iDoc
  116.63GB 10.14% 26.27%   357.03GB 31.05%  github.com/cockroachdb/cockroach/pkg/util/pretty.(*beExec).be
   52.52GB  4.57% 30.84%    52.52GB  4.57%  github.com/cockroachdb/pebble/vfs.(*memFile).Write
   36.15GB  3.14% 33.98%    36.15GB  3.14%  github.com/cockroachdb/cockroach/pkg/util/pretty.(*beExec).newiDoc (inline)
   28.64GB  2.49% 36.47%    28.64GB  2.49%  github.com/cockroachdb/cockroach/pkg/storage.(*pebbleResults).put
   23.43GB  2.04% 38.51%    23.43GB  2.04%  reflect.unsafe_NewArray
   21.25GB  1.85% 40.36%    21.25GB  1.85%  github.com/cockroachdb/cockroach/pkg/util/pretty.(*beExec).newDocBest (inline)
   20.15GB  1.75% 42.11%    25.46GB  2.21%  github.com/cockroachdb/cockroach/pkg/sql/parser.(*Parser).scanOneStmt
   19.44GB  1.69% 43.80%    19.44GB  1.69%  reflect.New
   19.33GB  1.68% 45.48%    19.33GB  1.68%  github.com/cockroachdb/cockroach/pkg/sql/opt/constraint.SingleSpanConstraint
```
profile001

Jira issue: CRDB-14218

### PR DESCRIPTION
**Pull request by cucaroach**
sql: remove a scapel left in the patient
    
Commit 1472c10b2b7df4b85051d5d2855df5dcfcfd6733 inadvertently set
GOMAXPROCS to 16 for all TestLogic tests.
    
Release note: None

sql: limit sqllite tests to 4 parallel when run from teamcity

Running with a full GOMAXPROCS can cause upwards of 16GB of memory
to be used when we parallelize 5 node clusters with 512MB split
between block-cache and max-sql-memory.  With a limit of 4 we should
stay in the 2-3GB range.

Not sure how this will affect performance, we'll have to watch it
going forward.

Fixes: #78690

Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
LGTM and sorry

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79476#-:-MzxFOSu21NGfb-tIEjL:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach)

**Comment by mgartner** [comment]
@cucaroach @yuzefovich should we backport the `GOMAXPROCS` fix to release-22.1? Or is it fine to leave as-is?

**Comment by cucaroach** [comment]
Good call, I forgot to check 22.1, its just test code but good to clean up I think.

**Comment by cucaroach** [comment]
blathers backport 22.1

**Pull request merged**
