### PR TITLE
roachtest: retry copyfrom test on serializable error

### LINKED ISSUE #112369: roachtest: copyfrom/crdb-atomic/sf=1/nodes=1 failed
roachtest.copyfrom/crdb-atomic/sf=1/nodes=1 [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12176599?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12176599?buildTab=artifacts#/copyfrom/crdb-atomic/sf=1/nodes=1) on master @ [f2bfa2a140fa302e79c9d31b84b944a6ac5e98ce](https://github.com/cockroachdb/cockroach/commits/f2bfa2a140fa302e79c9d31b84b944a6ac5e98ce):

```
(copyfrom.go:81).runTest: COMMAND_PROBLEM: exit status 1
(monitor.go:153).Wait: monitor failure: monitor user task failed: t.Fatal() was called
test artifacts and logs in: /artifacts/copyfrom/crdb-atomic/sf=1/nodes=1/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-12176599/copyfrom-crdb-atomic-sf-1-nodes-1/1697274476381/1697274729540)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*copyfrom/crdb-atomic/sf=1/nodes=1.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-32375

### PR DESCRIPTION
**Pull request by DrewKimball**
It is fairly common for the copyfrom roachtest to run in an overloaded environment, which can lead to client visible retryable (40001) errors. This patch adds a retry loop for these errors, which should reduce flakes.

Fixes #112369

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113099)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @herkolategan, and @srosenberg)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113099#-NhczlQB6Lyaz43Pxc09):*
Why is the environment overloaded? Is the test itself pushes the single node too hard?
___
*[`pkg/cmd/roachtest/tests/copyfrom.go` line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113099#-Nhd-PXlDgFUzuDQOjg2:-Nhd-PXlDgFUzuDQOjg3:b-b92cr3) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bb475c958449e3afbd0b360e959256ab7009b12/pkg/cmd/roachtest/tests/copyfrom.go#L89)):*
> ```Go
> 	rOpts.MaxBackoff = 10 * time.Second
> 	r := retry.StartWithCtx(ctx, rOpts)
> 	for r.Next() {
> ```

It seems possible that for all retries to fail with serializable error, yet the test would pass and would log meaningless copy rate. Should we handle it somehow? Like have a boolean `success` set to `true` whenever we break out of the retry loop, and we'd still fail the test on `!success`.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113099)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @srosenberg, and @yuzefovich)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113099#-NhczlQB6Lyaz43Pxc09):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Why is the environment overloaded? Is the test itself pushes the single node too hard?
</blockquote></details>

I'm not sure, but nothing else is touching that table and the `40001` errors that have failed this test can be triggered by overload, so it seemed the most likely explanation. Especially since we often observe symptoms of overload in such tests.
___
*[`pkg/cmd/roachtest/tests/copyfrom.go` line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113099#-Nhd-PXlDgFUzuDQOjg2:-NhkPVIg6cqmbaEKTgeH:b-4c5ezp) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bb475c958449e3afbd0b360e959256ab7009b12/pkg/cmd/roachtest/tests/copyfrom.go#L89)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

It seems possible that for all retries to fail with serializable error, yet the test would pass and would log meaningless copy rate. Should we handle it somehow? Like have a boolean `success` set to `true` whenever we break out of the retry loop, and we'd still fail the test on `!success`.
</blockquote></details>

Good catch, done.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113099#-:-NhmgvsZ0ja6bVV9tJWw:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan and @srosenberg)

**Comment by DrewKimball** [comment]
TFTR

bors r+

**Comment by DrewKimball** [comment]
blathers backport 23.2

**Pull request merged**
