### PR TITLE
storage/compactor: update the bytes queued metric more frequently

### PR DESCRIPTION
**Pull request by petermattis**
Update the bytes queued metric after processing each compaction and
periodically (every 10s while we're processing suggestions) refresh the
metric using the persisted suggestions so that it captures newly added
suggestions. Changed processCompaction() to delete processed suggestions
as soon as they are performed instead of in bulk at the end of
processing suggestions. The delay in deleting processed suggestions was
affecting our ability to query the persisted state and it was a
premature optimization as compactions take seconds while deleted the
processed suggestions takes milliseconds.

See #24029

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
Noticed this while debugging #24029.

**Comment by benesch** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/storage/compactor/compactor.go, line 266 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26365#-LEAxOQd5uQHZ2RANOuG:-LEAxOQd5uQHZ2RANOuH:bp0yg27) ([raw file](https://github.com/cockroachdb/cockroach/blob/97b352a23ead91aa917505a711cb79e1a1334283/pkg/storage/compactor/compactor.go#L266)):*
> ```Go
> 			totalBytes = bytes
> 		}
> 		c.Metrics.BytesQueued.Update(totalBytes)
> ```

`examineQueue` calls `c.Metrics.BytesQueued.Update` so this line perhaps belongs in an `else`. I suppose it doesn't much matter. Just something I noticed.

---

*[pkg/storage/compactor/compactor.go, line 351 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26365#-LEAxxyD7hF-K5cgSYFN:-LEAxxyD7hF-K5cgSYFO:b-8pde8t) ([raw file](https://github.com/cockroachdb/cockroach/blob/97b352a23ead91aa917505a711cb79e1a1334283/pkg/storage/compactor/compactor.go#L351)):*
> ```Go
> 		}
> 		delBatch.Close()
> 	}()
> ```

I think this would be clearer if you moved the `delBatch.Commit` to after the loop below instead of deferring it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26365#-:-LEAyOtp9RZ9PmRyhJ0S:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/compactor/compactor.go, line 266 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26365#-LEAxOQd5uQHZ2RANOuG:-LEBDIZ34xRIOlFL0al4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/97b352a23ead91aa917505a711cb79e1a1334283/pkg/storage/compactor/compactor.go#L266)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

`examineQueue` calls `c.Metrics.BytesQueued.Update` so this line perhaps belongs in an `else`. I suppose it doesn't much matter. Just something I noticed.
</blockquote></details>

Done.

---

*[pkg/storage/compactor/compactor.go, line 351 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26365#-LEAxxyD7hF-K5cgSYFN:-LEBDJdnB5MFgmtVCsJu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/97b352a23ead91aa917505a711cb79e1a1334283/pkg/storage/compactor/compactor.go#L351)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I think this would be clearer if you moved the `delBatch.Commit` to after the loop below instead of deferring it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26365)*

**Comment by petermattis** [comment]
bors r=benesch

**Pull request merged**
