### PR TITLE
sqlbase: introduce RowFetcher.Reset()

### PR DESCRIPTION
**Pull request by jordanlewis**
In preparation for pooling tableReader objects and reusing internal
allocated memory.

Broken out from #30556.

Release note: None

### CODE REVIEW

**Review by asubiotto — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30608)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sqlbase/rowfetcher.go, line 238 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30608#-LNGJp_k2BfGItlPPlyQ:-LNGJp_k2BfGItlPPlyR:by1h8fa) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2d932e3a3afa154a05642bf5fe366b4bc2fb8e6/pkg/sql/sqlbase/rowfetcher.go#L238)):*
> ```Go
> }
> 
> // Reset restets this RowFetcher, preserving the memory capacity that was used
> ```

`s/restets/resets`
___
*[pkg/sql/sqlbase/rowfetcher.go, line 244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30608#-LNGJCDwBn2zSViIGQUF:-LNGJCDwBn2zSViIGQUG:brc98pu) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2d932e3a3afa154a05642bf5fe366b4bc2fb8e6/pkg/sql/sqlbase/rowfetcher.go#L244)):*
> ```Go
> func (rf *RowFetcher) Reset() {
> 	*rf = RowFetcher{
> 		tables: rf.tables[:0],
> ```

I wonder if there's a test we can add or if we can modify existing tests to verify correctness while reusing a single `RowFetcher`. I'm just worried about adding more fields that need to be reset and forgetting to reset them in `Reset`. Not sure if this is a valid concern or if just resetting the `tables` slice is always enough.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30608)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sqlbase/rowfetcher.go, line 238 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30608#-LNGJp_k2BfGItlPPlyQ:-LNLts2s47DKlDv3D8wY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2d932e3a3afa154a05642bf5fe366b4bc2fb8e6/pkg/sql/sqlbase/rowfetcher.go#L238)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

`s/restets/resets`
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/rowfetcher.go, line 244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30608#-LNGJCDwBn2zSViIGQUF:-LNJ-41c0ly36iqJGRJ3:b-uk911n) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2d932e3a3afa154a05642bf5fe366b4bc2fb8e6/pkg/sql/sqlbase/rowfetcher.go#L244)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I wonder if there's a test we can add or if we can modify existing tests to verify correctness while reusing a single `RowFetcher`. I'm just worried about adding more fields that need to be reset and forgetting to reset them in `Reset`. Not sure if this is a valid concern or if just resetting the `tables` slice is always enough.
</blockquote></details>

We don't have to worry about not remembering to reset fields, because this resets everything *but* the `tables` field. So you only have to add stuff you *don't* want to reset to this declaration.

I added a simple test though.

**Review by asubiotto — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30608)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by rjnn — CHANGES_REQUESTED** [review]
The intent of the code changes are great, but some of the variable renaming and rewriting are done in an unintuitive fashion, so I'd like to see that cleaned up. In particular, you are consistently allocating a new object, and grafting over the most expensive-to-allocate components, but your variable naming seems to indicate that you are keeping the outer object and resetting the innards. This is the source of much of the confusion here.

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30608#-:-LNR7Hxx3eXAX1XE4E5H:bbt947r)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sqlbase/rowfetcher.go, line 244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30608#-LNGJCDwBn2zSViIGQUF:-LNR7Vgb2eV7elKr9DDF:b2nopgb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2d932e3a3afa154a05642bf5fe366b4bc2fb8e6/pkg/sql/sqlbase/rowfetcher.go#L244)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

We don't have to worry about not remembering to reset fields, because this resets everything *but* the `tables` field. So you only have to add stuff you *don't* want to reset to this declaration.

I added a simple test though.
</blockquote></details>

Alfonso's confusion is a good pointer that the pattern you're using is *very* unintuitive, and so you should make this clear in the top comment. You are resetting the pointer to the receiver, which requires drawing the reader's attention.
___
*[pkg/sql/sqlbase/rowfetcher.go, line 280 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30608#-LNR4mUoDBGCyYYlx6Mo:-LNR4mUoDBGCyYYlx6Mp:b-hjjofb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a44aad803daf2005b21bb4a93d3998a5bdeabf6/pkg/sql/sqlbase/rowfetcher.go#L280)):*
> ```Go
> 	for tableIdx, tableArgs := range tables {
> 		table := rf.tables[tableIdx]
> 		table = tableInfo{
> ```

you assign to `table` in the line above, and then reassign to it here. I get you're reusing, but its weird to read. At least call it `oldTable` or something else.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30608)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sqlbase/rowfetcher.go, line 244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30608#-LNGJCDwBn2zSViIGQUF:-LNR9GZyEdorpCjpcBgM:b-2buoz3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2d932e3a3afa154a05642bf5fe366b4bc2fb8e6/pkg/sql/sqlbase/rowfetcher.go#L244)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

Alfonso's confusion is a good pointer that the pattern you're using is *very* unintuitive, and so you should make this clear in the top comment. You are resetting the pointer to the receiver, which requires drawing the reader's attention.
</blockquote></details>

Hmm, IIUC this does not reset the pointer to the receiver. In Go, saying

```
var foo *SomeStruct = ...

*foo = SomeStruct{fields...}
```

copies the contents of the second declaration into the memory pointed to by `foo`.

Also, does the comment above this method not sufficiently draw your attention? I tried to spell out what is going on.
___
*[pkg/sql/sqlbase/rowfetcher.go, line 280 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30608#-LNR4mUoDBGCyYYlx6Mo:-LNR9qM340qOmDnovQRY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a44aad803daf2005b21bb4a93d3998a5bdeabf6/pkg/sql/sqlbase/rowfetcher.go#L280)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

you assign to `table` in the line above, and then reassign to it here. I get you're reusing, but its weird to read. At least call it `oldTable` or something else. 
</blockquote></details>

Done.

**Review by rjnn — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30608#-:-LNRDk3N8Ru7j1XBNPOK:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/sqlbase/rowfetcher.go, line 244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30608#-LNGJCDwBn2zSViIGQUF:-LNRDTIq7YHJjQbnjj5R:b-4tuc8d) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2d932e3a3afa154a05642bf5fe366b4bc2fb8e6/pkg/sql/sqlbase/rowfetcher.go#L244)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Hmm, IIUC this does not reset the pointer to the receiver. In Go, saying

```
var foo *SomeStruct = ...

*foo = SomeStruct{fields...}
```

copies the contents of the second declaration into the memory pointed to by `foo`.

Also, does the comment above this method not sufficiently draw your attention? I tried to spell out what is going on.
</blockquote></details>

Got it. I guess 'resets the foo' reads to me like you're setting all the internal variables to their zero values. But you're actually replacing the struct, and only carrying over a single value. I'd like a better comment still, but seeing as I'm unable to precisely phrase it, I won't hold you to a bar that I'm unable to meet myself :)

**Review by jordanlewis — COMMENTED** [review]
Thanks for the reviews!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30608#-:-LNRFt6MCk7p5siz3-cc:bctxt4d)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/sqlbase/rowfetcher.go, line 244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30608#-LNGJCDwBn2zSViIGQUF:-LNRFW2T15sJnt04E6CC:b8yjecu) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2d932e3a3afa154a05642bf5fe366b4bc2fb8e6/pkg/sql/sqlbase/rowfetcher.go#L244)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

Got it. I guess 'resets the foo' reads to me like you're setting all the internal variables to their zero values. But you're actually replacing the struct, and only carrying over a single value. I'd like a better comment still, but seeing as I'm unable to precisely phrase it, I won't hold you to a bar that I'm unable to meet myself :)
</blockquote></details>

Yeah, agreed that it's kind of weird, but it's *almost* the zero value - in many ways a 0 length slice is indistinguishable from a nil slice. In this case, it just happens to have capacity. That may or may not be filled with structs that have slices that recursively have that property. I dunno, it's kind of gross, but I'm not seeing a better way to do this kind of preservation of memory in Go. We definitely don't want to have to reallocate this stuff every time if we don't have to.

**Pull request merged**
