### PR TITLE
oidcccl: generate JWT auth token for cluster SSO

### PR DESCRIPTION
**Pull request by matthewtodd**
Epic: CC-24814

A new branch is added to the OIDC login flow that, instead of logging the user in, renders a JWT from the resulting credentials in a new web UI, suitable for use with cluster SSO.

This feature is configured by a few new cluster settings, all in the `server.oidc_authentication.generate_cluster_sso_token` namespace:
- `.enabled` enables the feature.
- `.use_token` selects whether to use the `id_token` or the `access_token` from the credentials.
- `.sql_host` and `.sql_port` are used to render the resulting full connection string. (These are necessary because the cluster may be behind a load balancer.)

For configuring cluster SSO and DB Console SSO, see:
- https://www.cockroachlabs.com/docs/stable/sso-sql.html
- https://www.cockroachlabs.com/docs/stable/sso-db-console.html

Release note (enterprise change): New cluster settings in the `server.oidc_authentication.generate_cluster_sso_token` namespace support using OIDC to generate a JWT auth token for cluster SSO.

Release justification: Customer commitment.

### CODE REVIEW

**Review by kpatron-cockroachlabs — COMMENTED** [review]
Seems like you could use a couple more tests and some cleanup but the flow looks good to me. Not sure where we are on the urgency to merge and fix it later vs ensure code quality before any release spectrum.

> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105553#-:-NYtMGZUAk8rXopq-hON:b-6nttmw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @matthewtodd)

___
*[`pkg/ccl/oidcccl/authentication_oidc.go` line 281 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105553#-NYtIl2WCeKXip_p_uEK:-NYtIl2WCeKXip_p_uEL:b-hws2sr) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6cd11a82363d2e5143c5d91cce173e9e33814dc/pkg/ccl/oidcccl/authentication_oidc.go#L281)):*
> ```Go
> // This flow consists of an initial login request that triggers
> // an HTTP redirect to the auth provider, and a callback endpoint
> // that the auth provider redirects the user back to with
> ```

Nit: maybe expand on this comment?
___
*[`pkg/ccl/oidcccl/authentication_oidc.go` line 342 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105553#-NYtIa8f6sGfFO1OMAk3:-NYtIa8f6sGfFO1OMAk4:bvcoldi) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6cd11a82363d2e5143c5d91cce173e9e33814dc/pkg/ccl/oidcccl/authentication_oidc.go#L342)):*
> ```Go
> 			return
> 		}
> 		if mode == serverpb.OIDCState_MODE_GENERATE_JWT_AUTH_TOKEN {
> ```

Nit: maybe drop a comment here explaining this split and vaguely what the difference is
___
*[`pkg/ccl/oidcccl/authentication_oidc.go` line 423 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105553#-NYtLgfyApoAIlROvEU0:-NYtLgfyApoAIlROvEU1:blxtbgq) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6cd11a82363d2e5143c5d91cce173e9e33814dc/pkg/ccl/oidcccl/authentication_oidc.go#L423)):*
> ```Go
> 	}))
> 
> 	handleHTTP(oidcJWTPath, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
> ```

Is there a more CRDB native way to do this by registering it like a real API instead of this special handler?
___
*[`pkg/ccl/oidcccl/authentication_oidc.go` line 446 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105553#-NYtJJhs65kkTafFmyjS:-NYtJJhs65kkTafFmyjT:bk46ass) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6cd11a82363d2e5143c5d91cce173e9e33814dc/pkg/ccl/oidcccl/authentication_oidc.go#L446)):*
> ```Go
> 		// We trigger telemetry on this endpoint only when we pass through the enabled gate to maintain
> 		// a useful signal.
> 		telemetry.Inc(beginCallbackUseCounter)
> ```

Should this be a different counter?
___
*[`pkg/ccl/oidcccl/authentication_oidc.go` line 513 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105553#-NYtJpw8EWT0a7P3NEA0:-NYtJpw8EWT0a7P3NEA1:b-iqdtl) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6cd11a82363d2e5143c5d91cce173e9e33814dc/pkg/ccl/oidcccl/authentication_oidc.go#L513)):*
> ```Go
> 				"attempting to extract SQL username from the payload using the claim key %s and regex %s",
> 				oidcAuthentication.conf.claimJSONKey,
> 				oidcAuthentication.conf.principalRegex,
> ```

I think this log is wrong. We aren't using the principal regex here. We are using the identity map.
___
*[`pkg/ccl/oidcccl/authentication_oidc.go` line 525 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105553#-NYtKsWi3aqUi86NaIzP:-NYtKsWi3aqUi86NaIzQ:b-9mtal1) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6cd11a82363d2e5143c5d91cce173e9e33814dc/pkg/ccl/oidcccl/authentication_oidc.go#L525)):*
> ```Go
> 		// There is also similar code in ValidateJWTLogin, though it's
> 		// working with a jwt.Token instead of an *oidc.IDToken.
> 		// Apart from the types, is there a meaningful difference, though?
> ```

I would be surprised if there was a meaningful difference.
___
*[`pkg/ccl/oidcccl/authentication_oidc.go` line 561 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105553#-NYtKSVx6tDB4LPrSZGg:-NYtKSVyDOmj48YcCuLV:b-uuji4y) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6cd11a82363d2e5143c5d91cce173e9e33814dc/pkg/ccl/oidcccl/authentication_oidc.go#L561)):*
> ```Go
> 			}
> 
> 			if len(tokenPrincipals) == 0 {
> ```

Any reason not to just have the subject case set tokenPrincipals = {token.Subject} and same with the string unmarshalling? It feels like that might be a bit more intuitive to read.
___
*[`pkg/ccl/oidcccl/authentication_oidc.go` line 569 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105553#-NYtKpYpAB5Rw7B3D1PP:-NYtKpYpAB5Rw7B3D1PQ:b-ik2276) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6cd11a82363d2e5143c5d91cce173e9e33814dc/pkg/ccl/oidcccl/authentication_oidc.go#L569)):*
> ```Go
> 		var idMap *identmap.Conf
> 		{
> 			// TODO(todd): Get the identity map from someplace that's already caching it.
> ```

I agree with this TODO
___
*[`pkg/ccl/oidcccl/authentication_oidc.go` line 583 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105553#-NYtLFZX3b0_q02_XejD:-NYtLFZX3b0_q02_XejE:bl2m091) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6cd11a82363d2e5143c5d91cce173e9e33814dc/pkg/ccl/oidcccl/authentication_oidc.go#L583)):*
> ```Go
> 			for _, tokenPrincipal := range tokenPrincipals {
> 				// Note that ill-mapped usernames don't stop us from proceeding; some principal may still be usable.
> 				if usernames, mapFound, _ := idMap.Map(token.Issuer, tokenPrincipal); mapFound {
> ```

Do you think it's worth adding a log line if there is an error?
___
*[`pkg/ccl/oidcccl/authentication_oidc.go` line 588 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105553#-NYtL7LzA_L5Z9x4B4LM:-NYtL7LzA_L5Z9x4B4LN:bpsxjdo) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6cd11a82363d2e5143c5d91cce173e9e33814dc/pkg/ccl/oidcccl/authentication_oidc.go#L588)):*
> ```Go
> 					}
> 				} else {
> 					if username, err := username.MakeSQLUsernameFromUserInput(tokenPrincipal, username.PurposeValidation); err != nil {
> ```

Do you think it's worth adding a log line for the else case?
___
*[`pkg/ccl/oidcccl/authentication_oidc.go` line 595 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105553#-NYtLPnU4Ngbqng5hqvC:-NYtLPnU4Ngbqng5hqvD:b-avwsum) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6cd11a82363d2e5143c5d91cce173e9e33814dc/pkg/ccl/oidcccl/authentication_oidc.go#L595)):*
> ```Go
> 		}
> 
> 		body, err := json.MarshalIndent(struct {
> ```

Is there a more CRDB native way to do this? My understanding is most of the GRPC APIs will also serve JSON depending on what you feed them. A place for future work to standardize.
___
*[`pkg/ccl/oidcccl/settings.go` line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105553#-NYtLuOG-FXp3akooYb1:-NYtLuOG-FXp3akooYb2:b-b6x74s) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6cd11a82363d2e5143c5d91cce173e9e33814dc/pkg/ccl/oidcccl/settings.go#L37)):*
> ```Go
> 	OIDCAutoLoginSettingName      = baseOIDCSettingName + "autologin"
> 
> 	OIDCGenerateJWTAuthTokenEnabledSettingName  = baseOIDCSettingName + "generate_jwt_auth_token.enabled"
> ```

nit: I wonder if there's there's a clearer name for `generate_jwt_auth_token`

**Review by matthewtodd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105553)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kpatron-cockroachlabs)

___
*[`pkg/ccl/oidcccl/authentication_oidc.go` line 342 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105553#-NYtIa8f6sGfFO1OMAk3:-NYx5YvuDqn3_Z707VY9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6cd11a82363d2e5143c5d91cce173e9e33814dc/pkg/ccl/oidcccl/authentication_oidc.go#L342)):*
<details><summary><i>Previously, kpatron-cockroachlabs (Kyle) wrote…</i></summary><blockquote>

Nit: maybe drop a comment here explaining this split and vaguely what the difference is
</blockquote></details>

Done.
___
*[`pkg/ccl/oidcccl/authentication_oidc.go` line 423 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105553#-NYtLgfyApoAIlROvEU0:-NYx5dbnDQWwpu-h0KGK:bdu9sr8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6cd11a82363d2e5143c5d91cce173e9e33814dc/pkg/ccl/oidcccl/authentication_oidc.go#L423)):*
<details><summary><i>Previously, kpatron-cockroachlabs (Kyle) wrote…</i></summary><blockquote>

Is there a more CRDB native way to do this by registering it like a real API instead of this special handler?
</blockquote></details>

I found this weird, too. It's how the other two `/oidc/v1` handlers are registered here, so probably makes sense to keep as is for this PR. (Will also add to my list of notes to investigate & spin out some tickets.)
___
*[`pkg/ccl/oidcccl/authentication_oidc.go` line 446 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105553#-NYtJJhs65kkTafFmyjS:-NYx6L672HAocLk12FB8:brpdchi) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6cd11a82363d2e5143c5d91cce173e9e33814dc/pkg/ccl/oidcccl/authentication_oidc.go#L446)):*
<details><summary><i>Previously, kpatron-cockroachlabs (Kyle) wrote…</i></summary><blockquote>

Should this be a different counter?
</blockquote></details>

Good catch! Changed.
___
*[`pkg/ccl/oidcccl/authentication_oidc.go` line 513 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105553#-NYtJpw8EWT0a7P3NEA0:-NYx8L2b4oMhTG899FC9:bsye2h2) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6cd11a82363d2e5143c5d91cce173e9e33814dc/pkg/ccl/oidcccl/authentication_oidc.go#L513)):*
<details><summary><i>Previously, kpatron-cockroachlabs (Kyle) wrote…</i></summary><blockquote>

I think this log is wrong. We aren't using the principal regex here. We are using the identity map.
</blockquote></details>

:man_facepalming: Thanks.
___
*[`pkg/ccl/oidcccl/authentication_oidc.go` line 561 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105553#-NYtKSVx6tDB4LPrSZGg:-NYx9LMa6DzmsGQQviZE:b-9wgxos) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6cd11a82363d2e5143c5d91cce173e9e33814dc/pkg/ccl/oidcccl/authentication_oidc.go#L561)):*
<details><summary><i>Previously, kpatron-cockroachlabs (Kyle) wrote…</i></summary><blockquote>

Any reason not to just have the subject case set tokenPrincipals = {token.Subject} and same with the string unmarshalling? It feels like that might be a bit more intuitive to read.
</blockquote></details>

Good question, yeah, this smelled weird to me, too. I lifted this directly from our other implementation in [ValidateJWTLogin](https://github.com/cockroachdb/cockroach/blob/63082e0bf808644bd54ad9fa2cf1228ccc7fdb34/pkg/ccl/jwtauthccl/authentication_jwt.go#L123) and suggest we keep them the same until figuring out how to address the duplication. (Also, since we don't yet have automated test coverage over these callbacks -- we'll want to stand up a fake IdP at test time -- I'm feeling pretty conservative here.)
___
*[`pkg/ccl/oidcccl/authentication_oidc.go` line 583 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105553#-NYtLFZX3b0_q02_XejD:-NYxDaHX1Kuf6u0GLJqM:bvfcc31) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6cd11a82363d2e5143c5d91cce173e9e33814dc/pkg/ccl/oidcccl/authentication_oidc.go#L583)):*
<details><summary><i>Previously, kpatron-cockroachlabs (Kyle) wrote…</i></summary><blockquote>

Do you think it's worth adding a log line if there is an error?
</blockquote></details>

Added for future-proofness. It turns out that currently the error will always be `nil` because only [this line](https://github.com/cockroachdb/cockroach/blob/fd9548f95a9cf2d4857b3615b73502c4ebaf1e00/pkg/sql/pgwire/identmap/ident_map.go#L155) could produce an error, but`MakeSQLUsernameFromUserInput` [doesn't return errors](https://github.com/cockroachdb/cockroach/blob/ff3606bd46812cc2fb5cf3c476869520e6c55156/pkg/security/username/username.go#L173) on validation.
___
*[`pkg/ccl/oidcccl/authentication_oidc.go` line 588 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105553#-NYtL7LzA_L5Z9x4B4LM:-NYxGkbDAv3ZH6qeiXIK:b-21pn6i) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6cd11a82363d2e5143c5d91cce173e9e33814dc/pkg/ccl/oidcccl/authentication_oidc.go#L588)):*
<details><summary><i>Previously, kpatron-cockroachlabs (Kyle) wrote…</i></summary><blockquote>

Do you think it's worth adding a log line for the else case?
</blockquote></details>

SGTM, done.
___
*[`pkg/ccl/oidcccl/authentication_oidc.go` line 595 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105553#-NYtLPnU4Ngbqng5hqvC:-NYxGxB_-D9XTk_KA3Kd:brbr63x) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6cd11a82363d2e5143c5d91cce173e9e33814dc/pkg/ccl/oidcccl/authentication_oidc.go#L595)):*
<details><summary><i>Previously, kpatron-cockroachlabs (Kyle) wrote…</i></summary><blockquote>

Is there a more CRDB native way to do this? My understanding is most of the GRPC APIs will also serve JSON depending on what you feed them. A place for future work to standardize.
</blockquote></details>

Good q, agreed. Have documented in the code and captured on my list for now.

**Review by cameronnunez — COMMENTED** [review]
Nice! The flow pretty much looks good to me but as Kyle already mentioned, may want to consider more testing 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105553#-:-NYxRJp-5SUfzDJRFZmc:b-pv7u0w)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kpatron-cockroachlabs and @matthewtodd)

___
*[`pkg/ccl/oidcccl/authentication_oidc.go` line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105553#-NYxJvdb8g33ByNz26N4:-NYxJvdb8g33ByNz26N5:b-35tj7q) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6cd11a82363d2e5143c5d91cce173e9e33814dc/pkg/ccl/oidcccl/authentication_oidc.go#L48)):*
> ```Go
> 	oidcLoginPath            = "/oidc/v1/login"
> 	oidcCallbackPath         = "/oidc/v1/callback"
> 	oidcJWTPath              = "/oidc/v1/jwt"
> ```

nit: similar to the mode name discussion, might want to consider adding clarity with a different path name. maybe something that includes "cluster SSO". your call though 
___
*[`pkg/ccl/oidcccl/authentication_oidc.go` line 342 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105553#-NYtIa8f6sGfFO1OMAk3:-NYxJIWgADtCCPuxZehJ:b-oqjqgd) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6cd11a82363d2e5143c5d91cce173e9e33814dc/pkg/ccl/oidcccl/authentication_oidc.go#L342)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: maybe we should also log if the redirection happens
___
*[`pkg/ccl/oidcccl/settings.go` line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105553#-NYtLuOG-FXp3akooYb1:-NYxEbDcDDlnUvpdbVEK:b-lsf6v5) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6cd11a82363d2e5143c5d91cce173e9e33814dc/pkg/ccl/oidcccl/settings.go#L37)):*
<details><summary><i>Previously, kpatron-cockroachlabs (Kyle) wrote…</i></summary><blockquote>

nit: I wonder if there's there's a clearer name for `generate_jwt_auth_token`
</blockquote></details>

nit: +1, one consideration could be including "cluster SSO" in the name and the mode name to help better inform what the token is being used for and how this mode is different than the login mode, since some steps between the two modes in this area are pretty much the same (e.g. oauth2 exchange), it's just that the OIDC tokens get used differently depending on the mode

**Review by kpatron-cockroachlabs — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105553)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @matthewtodd)

___
*[`pkg/ccl/oidcccl/authentication_oidc.go` line 423 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105553#-NYtLgfyApoAIlROvEU0:-NYxRrdZ4ieS3zBmBBSI:bymcr25) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6cd11a82363d2e5143c5d91cce173e9e33814dc/pkg/ccl/oidcccl/authentication_oidc.go#L423)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

I found this weird, too. It's how the other two `/oidc/v1` handlers are registered here, so probably makes sense to keep as is for this PR. (Will also add to my list of notes to investigate & spin out some tickets.)
</blockquote></details>

Hmm okay.
___
*[`pkg/ccl/oidcccl/authentication_oidc.go` line 561 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105553#-NYtKSVx6tDB4LPrSZGg:-NYxS2dz1Ud1jsgZfVww:b-bk5ip0) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6cd11a82363d2e5143c5d91cce173e9e33814dc/pkg/ccl/oidcccl/authentication_oidc.go#L561)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Good question, yeah, this smelled weird to me, too. I lifted this directly from our other implementation in [ValidateJWTLogin](https://github.com/cockroachdb/cockroach/blob/63082e0bf808644bd54ad9fa2cf1228ccc7fdb34/pkg/ccl/jwtauthccl/authentication_jwt.go#L123) and suggest we keep them the same until figuring out how to address the duplication. (Also, since we don't yet have automated test coverage over these callbacks -- we'll want to stand up a fake IdP at test time -- I'm feeling pretty conservative here.)
</blockquote></details>

Works for me.

**Review by matthewtodd — COMMENTED** [review]
Thank you both! I appreciate all your good suggestions. I've renamed the cluster settings to live in the `server.oidc_authentication.generate_cluster_sso_token` namespace. In the interest of making tonight's SHA pick, I'll get that much merged for now and follow on with further improvements for the next release. (I like the idea of changing the paths, @cameronnunez, will fast follow.)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105553#-:-NYxbIXT0AyBxRkzYIZ7:b-87b2j6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kpatron-cockroachlabs)

**Pull request merged**
