### PR TITLE
sql: replace IVarHelper in SemaContext/EvalContext with IVarContainer

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### sql: replace IndexedVarHelper in SemaContext with IndexedVarContainer

The `SemaContext.IVarHelper` felt strange to me (why would we want a
helper in a semantic context?) so I looked at how it is used. Turns
out we only use it for its container (which makes sense). This leads
to situations where we create `IndexedVarHelper`s just to populate
this field.

We change the field to be an `IndexedVarContainer`.

Release note: None

#### sql: replace IndexedVarHelper in EvalContext with IndexedVarContainer

`EvalContext.IndexedVarHelper` is only used for its container. In many
contexts we create a helper just to populate this field.

Changing the field to `IndexedVarContainer`.

Release note: None

### CODE REVIEW

**Comment by jordanlewis** [comment]
:lgtm: this is cleaner for sure

---

Reviewed 14 of 14 files at r1.
Review status: 10 of 25 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22784#-:-L5Vb7ky14vzOKxScQNt:b-n3yn53)*

**Comment by jordanlewis** [comment]
Reviewed 15 of 15 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/sem/tree/eval.go, line 2292 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22784#-L5VbK5CxKDxlci8zYX3:-L5VbK5CxKDxlci8zYX4:blyrngj) ([raw file](https://github.com/cockroachdb/cockroach/blob/63eb09057e6c45ce2df8d03623878041d7312e56/pkg/sql/sem/tree/eval.go#L2292)):*
> ```Go
> 	// IVarContainer is used to evaluate IndexedVars.
> 	IVarContainer IndexedVarContainer
> 	// iVarHelperStack is used when we swap out IVarHelpers in order to evaluate
> ```

nit: this should be iVarContainerStack now, and s/IVarHelper/IVarContainer/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22784)*

**Comment by knz** [comment]
Good simplification. I like it!
:lgtm: 

---

Reviewed 13 of 14 files at r1, 15 of 15 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22784#-:-L5Vehs7Qi1GU2cC1lTb:b-v552xj)*

**Comment by RaduBerinde** [comment]
TFTRs!

Another idea I had (not for this PR) was to create a sub-interface of `IVarContainer` that has just the get-type method. We have a few containers that only implement that, and we would only need this restricted container in SemaContext. Not sure it's worth it.

---

Review status: 9 of 25 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/sem/tree/eval.go, line 2292 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22784#-L5VbK5CxKDxlci8zYX3:-L5W8ydsymFCMkCMTqNI:bb769dr) ([raw file](https://github.com/cockroachdb/cockroach/blob/63eb09057e6c45ce2df8d03623878041d7312e56/pkg/sql/sem/tree/eval.go#L2292)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

nit: this should be iVarContainerStack now, and s/IVarHelper/IVarContainer/
</blockquote></details>

Done. Grepped and fixed a couple others.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22784#-:-L5W920_xqfDiavR3NWr:b-1l37o1)*

**Pull request merged**
