### PR TITLE
workload/schemachanger: Stabilize UDFs calling UDFs within the workload

### LINKED ISSUE #121407: pkg/ccl/testccl/workload/schemachange/schemachange_test: TestWorkload failed
pkg/ccl/testccl/workload/schemachange/schemachange_test.TestWorkload [failed](https://tanzanite.cluster.engflow.com/invocations/default/02f80160-ff5c-406c-9667-df5f29d47106?testReportRun=29&testReportShard=1&testReportAttempt=1#targets-Ly9wa2cvY2NsL3Rlc3RjY2wvd29ya2xvYWQvc2NoZW1hY2hhbmdlOnNjaGVtYWNoYW5nZV90ZXN0) on master @ [2a5e231716c436781f12452d800651f51c6383b7](https://github.com/cockroachdb/cockroach/commits/2a5e231716c436781f12452d800651f51c6383b7):

```
     "schema_w0_22"
    ],
    "result": []
   }
  ],
  "previousStatements": [
   "ALTER TABLE IF EXISTS \"NonExistentTable\" ALTER PRIMARY KEY USING COLUMNS (\"IrrelevantColumn\")",
   "ALTER FUNCTION schema_w0_6.udf_w1_20() SET SCHEMA schema_w0_22",
   "COMMENT ON SCHEMA schema_w1_48 IS ''",
   "DROP SCHEMA \"schema_w0_22\" CASCADE"
  ]
 }
}
    schema_change_external_test.go:132: 
        	Error Trace:	pkg/ccl/testccl/workload/schemachange/schemachange_test_test/pkg/ccl/testccl/workload/schemachange/schema_change_external_test.go:132
        	Error:      	Received unexpected error:
        	            	***UNEXPECTED ERROR; Received an unexpected execution error.: ERROR: cannot drop function "udf_w1_20" because other object ([schemachange.schema_w0_6.udf_w1_55]) still depend on it (SQLSTATE 2BP01)
        	            	(1) forced error mark
        	            	  | "fatal error when running txn"
        	            	  | github.com/cockroachdb/errors/withstack/*withstack.withStack::
        	            	Wraps: (2)
        	            	Wraps: (3) attached stack trace
        	            	  -- stack trace:
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*opStmt).executeStmt
        	            	  | 	github.com/cockroachdb/cockroach/pkg/workload/schemachange/operation_generator.go:3120
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*schemaChangeWorker).runInTxn
        	            	  | 	github.com/cockroachdb/cockroach/pkg/workload/schemachange/schemachange.go:504
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*schemaChangeWorker).run
        	            	  | 	github.com/cockroachdb/cockroach/pkg/workload/schemachange/schemachange.go:586
        	            	  | pkg/ccl/testccl/workload/schemachange/schemachange_test_test.TestWorkload.TestWorkload.func4.func6
        	            	  | 	pkg/ccl/testccl/workload/schemachange/schemachange_test_test/pkg/ccl/testccl/workload/schemachange/schema_change_external_test.go:121
        	            	  | golang.org/x/sync/errgroup.(*Group).Go.func1
        	            	  | 	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:78
        	            	  | runtime.goexit
        	            	  | 	src/runtime/asm_amd64.s:1695
        	            	Wraps: (4) ***UNEXPECTED ERROR; Received an unexpected execution error.
        	            	Wraps: (5) ERROR: cannot drop function "udf_w1_20" because other object ([schemachange.schema_w0_6.udf_w1_55]) still depend on it (SQLSTATE 2BP01)
        	            	Error types: (1) *markers.withMark (2) *schemachange.ErrorState (3) *withstack.withStack (4) *errutil.withPrefix (5) *pgconn.PgError
        	Test:       	TestWorkload
Schema Workload Stats
Total Schema Statements Executed = 139
Total Schema Statements Succeeded = 139
Total Schema Statement Expected Failures = 0
Total Transactions Committed = 72
Total Transactions Rolled Back = 93
Total Transactions Executed = 165
    schema_change_external_test.go:98: backup, tracing data, and system table dumps in /var/lib/engflow/worker/work/2/exec/bazel-out/k8-fastbuild/testlogs/pkg/ccl/testccl/workload/schemachange/schemachange_test/run_29_of_30/test.outputs/logTestWorkload842769376
    panic.go:626: -- test log scope end --
test logs left over in: outputs.zip/logTestWorkload842769376
--- FAIL: TestWorkload (26.21s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=29</code>
 - <code>shard=1</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestWorkload.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

### LINKED ISSUE #121425: pkg/ccl/testccl/workload/schemachange/schemachange_test: TestWorkload failed
pkg/ccl/testccl/workload/schemachange/schemachange_test.TestWorkload [failed](https://tanzanite.cluster.engflow.com/invocations/default/b8827329-ddca-46a9-9b31-a41b550a4bfb?testReportRun=27&testReportShard=1&testReportAttempt=1#targets-Ly9wa2cvY2NsL3Rlc3RjY2wvd29ya2xvYWQvc2NoZW1hY2hhbmdlOnNjaGVtYWNoYW5nZV90ZXN0) on release-24.1 @ [5d952f80b3e1efe2e9aaed73f1fd68433880fcb7](https://github.com/cockroachdb/cockroach/commits/5d952f80b3e1efe2e9aaed73f1fd68433880fcb7):

```
    "query": "SELECT EXISTS (SELECT proname FROM pg_proc WHERE (proname = $1) AND (pg_get_function_identity_arguments(oid) ILIKE $2))",
    "queryArgs": [
     "udf_w1_65",
     ""
    ],
    "result": false
   }
  ],
  "previousStatements": [
   "CREATE FUNCTION schema_w1_43.udf_w1_65()\n\tRETURNS public.enum_w1_1\n\tLANGUAGE SQL\n\tAS $$ SELECT NULL WHERE ('ff'::public.enum_w1_1 IS NULL) AND ('saaadd'::public.enum_w1_1 IS NULL) AND ('a'::public.enum_w1_1 IS NULL) AND (SELECT public.udf_w0_18(NULL,NULL) IS NOT NULL) AND (SELECT schema_w0_17.udf_w0_26(NULL,NULL) IS NOT NULL) $$"
  ]
 }
}
    schema_change_external_test.go:132: 
        	Error Trace:	pkg/ccl/testccl/workload/schemachange/schemachange_test_test/pkg/ccl/testccl/workload/schemachange/schema_change_external_test.go:132
        	Error:      	Received unexpected error:
        	            	***UNEXPECTED ERROR; Received an unexpected execution error.: ERROR: unknown function: public.udf_w0_11() (SQLSTATE 42883)
        	            	(1) forced error mark
        	            	  | "fatal error when running txn"
        	            	  | github.com/cockroachdb/errors/withstack/*withstack.withStack::
        	            	Wraps: (2)
        	            	Wraps: (3) attached stack trace
        	            	  -- stack trace:
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*opStmt).executeStmt
        	            	  | 	github.com/cockroachdb/cockroach/pkg/workload/schemachange/operation_generator.go:3120
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*schemaChangeWorker).runInTxn
        	            	  | 	github.com/cockroachdb/cockroach/pkg/workload/schemachange/schemachange.go:504
        	            	  | github.com/cockroachdb/cockroach/pkg/workload/schemachange.(*schemaChangeWorker).run
        	            	  | 	github.com/cockroachdb/cockroach/pkg/workload/schemachange/schemachange.go:586
        	            	  | pkg/ccl/testccl/workload/schemachange/schemachange_test_test.TestWorkload.TestWorkload.func4.func6
        	            	  | 	pkg/ccl/testccl/workload/schemachange/schemachange_test_test/pkg/ccl/testccl/workload/schemachange/schema_change_external_test.go:121
        	            	  | golang.org/x/sync/errgroup.(*Group).Go.func1
        	            	  | 	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:78
        	            	  | runtime.goexit
        	            	  | 	src/runtime/asm_amd64.s:1695
        	            	Wraps: (4) ***UNEXPECTED ERROR; Received an unexpected execution error.
        	            	Wraps: (5) ERROR: unknown function: public.udf_w0_11() (SQLSTATE 42883)
        	            	Error types: (1) *markers.withMark (2) *schemachange.ErrorState (3) *withstack.withStack (4) *errutil.withPrefix (5) *pgconn.PgError
        	Test:       	TestWorkload
Schema Workload Stats
Total Schema Statements Executed = 108
Total Schema Statements Succeeded = 108
Total Schema Statement Expected Failures = 0
Total Transactions Committed = 64
Total Transactions Rolled Back = 71
Total Transactions Executed = 135
    schema_change_external_test.go:98: backup, tracing data, and system table dumps in /var/lib/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/testlogs/pkg/ccl/testccl/workload/schemachange/schemachange_test/run_27_of_30/test.outputs/logTestWorkload3675729792
    panic.go:626: -- test log scope end --
test logs left over in: outputs.zip/logTestWorkload3675729792
--- FAIL: TestWorkload (21.08s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=27</code>
 - <code>shard=1</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #121407 pkg/ccl/testccl/workload/schemachange/schemachange_test: TestWorkload failed [C-test-failure O-robot T-sql-foundations branch-master release-blocker]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestWorkload.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-37244

### LINKED ISSUE #121436: roachtest: schemachange/random-load failed [UDF-UDF dependency tracking]
roachtest.schemachange/random-load [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/14635191?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/14635191?buildTab=artifacts#/schemachange/random-load) on release-24.1 @ [5d952f80b3e1efe2e9aaed73f1fd68433880fcb7](https://github.com/cockroachdb/cockroach/commits/5d952f80b3e1efe2e9aaed73f1fd68433880fcb7):

```
(schemachange_random_load.go:123).runSchemaChangeRandomLoad: full command output in run_183938.274554066_n1_workload-run-schemac.log: COMMAND_PROBLEM: exit status 1
test artifacts and logs in: /artifacts/schemachange/random-load/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=true</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-14635191/schemachange-random-load/1711910340644/1711911169764)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #120771 roachtest: schemachange/random-load failed [C-test-failure O-roachtest O-robot P-2 T-sql-foundations branch-master]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*schemachange/random-load.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-37256

### LINKED ISSUE #121595: roachtest: schemachange/mixed-versions failed [unknown function when defining UDF]
roachtest.schemachange/mixed-versions [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/14675255?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/14675255?buildTab=artifacts#/schemachange/mixed-versions) on master @ [7166724ff02b9b7f0d5787f74d919487ca347bd0](https://github.com/cockroachdb/cockroach/commits/7166724ff02b9b7f0d5787f74d919487ca347bd0):

```
(mixedversion.go:592).Run: mixed-version test failure while running step 8 (run "run schemachange workload and validation in mixed version"): full command output in run_060623.949982078_n4_COCKROACHRANDOMSEED2.log: COMMAND_PROBLEM: exit status 1
test artifacts and logs in: /artifacts/schemachange/mixed-versions/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-14675255/schemachange-mixed-versions/1712124293349/1712124536312)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #121411 roachtest: schemachange/mixed-versions failed [C-test-failure O-roachtest O-robot P-2 T-sql-foundations branch-release-24.1]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*schemachange/mixed-versions.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-37360

### PR DESCRIPTION
**Pull request by fqazi**
This patch addresses the following issues with our UDFs invoking other UDFs support:

1. Previously the randomized CREATE FUNCTION could incorrectly select UDFs that were marked as dropped, these are now properly skipped
2. When DROP SCHEMA was invoked we would check if the schema contained any UDF invoked by any other UDF in a different schema. This should block the DROP SCHEMA operation in the legacy schema changer. Unfortunately, the check using for checking dependencies had bugs and never worked properly.
3. ALTER FUNCTION ... SET SCHEMA should have a block to prevent setting schema if any UDF references exist. Both a unit test and checking inside the randomize workload are added.

Fixes: #121407

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121492)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi, @herkolategan, and @renatolabs)

___
*[`pkg/sql/alter_function.go` line 403 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/121492#-NuVK_yq31ccGyd6zuKf:-NuVK_yq31ccGyd6zuKg:b-u0a85y) ([raw file](https://github.com/cockroachdb/cockroach/blob/a315c54600891956cd6b461499206cc73007efda/pkg/sql/alter_function.go#L403)):*
> ```Go
> 		return errors.UnimplementedErrorf(
> 			errors.IssueLink{
> 				IssueURL: "https://github.com/cockroachdb/cockroach/issues/83233",
> ```

nit: use `build.MakeIssueURL`

(also, see: https://github.com/cockroachdb/cockroach/pull/120719)
___
*[`pkg/sql/alter_function.go` line 404 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/121492#-NuVKX8A-EM7H3pHbcRu:-NuVKX8A-EM7H3pHbcRv:bq7wlij) ([raw file](https://github.com/cockroachdb/cockroach/blob/a315c54600891956cd6b461499206cc73007efda/pkg/sql/alter_function.go#L404)):*
> ```Go
> 			errors.IssueLink{
> 				IssueURL: "https://github.com/cockroachdb/cockroach/issues/83233",
> 				Detail:   "renames are disallowed because references are by name",
> ```

nit: this detail message should be updated
___
*[`pkg/workload/schemachange/operation_generator.go` line 3943 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121492#-NuVIlcX-iWXxbAIFV8F:-NuVIlcX-iWXxbAIFV8G:bv91ugo) ([raw file](https://github.com/cockroachdb/cockroach/blob/05d72919950d1abbfa145c7a53bae98c38f31b33/pkg/workload/schemachange/operation_generator.go#L3943)):*
> ```Go
> 	functions
> 	INNER JOIN pg_catalog.pg_proc ON oid = (id + 100000)
> 	WHERE (descriptor->'state')::STRING <> 'DROPPED'::STRING;`)
> ```

should this just look for PUBLIC?

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121492)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @rafiss, and @renatolabs)

___
*[`pkg/workload/schemachange/operation_generator.go` line 3943 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121492#-NuVIlcX-iWXxbAIFV8F:-NuX-mO03Yxvt4rWq8J5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/05d72919950d1abbfa145c7a53bae98c38f31b33/pkg/workload/schemachange/operation_generator.go#L3943)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

should this just look for PUBLIC?
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
lgtm!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121492#-:-NuZuUas-8K02T5o4cia:b-7nbn20)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @renatolabs)

**Comment by fqazi** [comment]
@rafiss TFTR!

bors r+

**Comment by rafiss** [comment]
blathers backport 24.1

**Pull request merged**
