### PR TITLE
move kv/local_sender to storage/stores

### PR DESCRIPTION
**Pull request by vivekmenezes**
[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3202)

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM with minor comments. Looks like the second commit should be squashed into the first.

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[kv/dist_sender.go, line 34 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3202#-K3p4-ON4AXWy4Vv2SNu:-K3p4-ON4AXWy4Vv2SNv:1405093977) ([raw file](https://github.com/cockroachdb/cockroach/blob/03833cf7fadeae3aac6829f59b7831eac12f1725/kv/dist_sender.go#L34)):_
can you get rid of that dependency? Breaking `kv -> storage` would be right in the spirit of this change.

---

_[kv/dist_sender.go, line 145 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3202#-K3p4EfjBtPZNPYEV9aw:-K3p4EfjBtPZNPYEV9ax:2110863076) ([raw file](https://github.com/cockroachdb/cockroach/blob/03833cf7fadeae3aac6829f59b7831eac12f1725/kv/dist_sender.go#L145)):_
this interface doesn't need to be in `storage`.

---

_[kv/dist_sender.go, line 498 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3202#-K3p4H_DDt6AeJ9Df6ea:-K3p4H_DDt6AeJ9Df6eb:-1965179840) ([raw file](https://github.com/cockroachdb/cockroach/blob/03833cf7fadeae3aac6829f59b7831eac12f1725/kv/dist_sender.go#L498)):_
`LookupOptions` can also move out of `storage` into a common place.

---

_[kv/local_test_cluster.go, line 48 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3202#-K3p4dA3-eCEVnqdStzh:-K3p4dA3-eCEVnqdStzi:1365847642) ([raw file](https://github.com/cockroachdb/cockroach/blob/03833cf7fadeae3aac6829f59b7831eac12f1725/kv/local_test_cluster.go#L48)):_
could you update this comment? It uses a `DistSender` (but still no RPC traffic).

---

_[kv/local_test_cluster.go, line 57 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3202#-K3p4lFVFw9DiH2ynZUd:-K3p4lFVFw9DiH2ynZUe:-850525529) ([raw file](https://github.com/cockroachdb/cockroach/blob/03833cf7fadeae3aac6829f59b7831eac12f1725/kv/local_test_cluster.go#L57)):_
ok, hard to avoid `storage` here (and this is package-public). But `LocalTestCluster` is only used in `kv` and `ts`, so still makes sense to avoid `storage` everything but here with the outlook of having `ts` use the other `TestServer` in the future.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3202#-:-K3p5tXFgyARWIv84Rl1:-1555131712)_

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[kv/dist_sender.go, line 145 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3202#-K3p4EfjBtPZNPYEV9aw:-K3p6mAG2xmUC1sMHKTF:-411778829) ([raw file](https://github.com/cockroachdb/cockroach/blob/03833cf7fadeae3aac6829f59b7831eac12f1725/kv/dist_sender.go#L145)):_
It needs to be where LookupOptions is, and we can't use LookupOptions from storage if it stays in kv. We need to either move LookupOptions to somewhere lower in the dependency graph or maybe just remove it from the RangeDescriptorDB interface completely (and pass two bools to RangeLookup instead of a LookupOptions struct). I think I'd rather do that than move LookupOptions to storage.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3202)_

**Comment by vivekmenezes** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[kv/dist_sender.go, line 145 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3202#-K3p4EfjBtPZNPYEV9aw:-K3p88kiuLAW5VYYUwH0:-212821844) ([raw file](https://github.com/cockroachdb/cockroach/blob/03833cf7fadeae3aac6829f59b7831eac12f1725/kv/dist_sender.go#L145)):_
I'll make the change to pass in two booleans. We do state that Stores implements the RangeDescriptorDB interface, how do I do that without moving it to storage or elsewhere. Any thoughts on where I should move it?

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3202)_

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[kv/dist_sender.go, line 145 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3202#-K3p4EfjBtPZNPYEV9aw:-K3pAD7fiecSBs98650h:1365758854) ([raw file](https://github.com/cockroachdb/cockroach/blob/03833cf7fadeae3aac6829f59b7831eac12f1725/kv/dist_sender.go#L145)):_
We don't necessarily need the interface assertion: the compiler will enforce this for us when we pass Stores as a RangeDescriptorDB in client_test.go. If you want to keep the assertion you could put it in `storage/client_test.go`; since it is in package `storage_test` it can import from both `storage` and `kv`.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3202)_

**Comment by vivekmenezes** [comment]
Review status: 6 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

_[kv/dist_sender.go, line 34 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3202#-K3p4-ON4AXWy4Vv2SNu:-K3pXQcbAqREHl2vyicc:-467915377) ([raw file](https://github.com/cockroachdb/cockroach/blob/03833cf7fadeae3aac6829f59b7831eac12f1725/kv/dist_sender.go#L34)):_
fixed

---

_[kv/dist_sender.go, line 145 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3202#-K3p4EfjBtPZNPYEV9aw:-K3pXSLzk9jWt4N1atsp:-477015672) ([raw file](https://github.com/cockroachdb/cockroach/blob/03833cf7fadeae3aac6829f59b7831eac12f1725/kv/dist_sender.go#L145)):_
Fixed. Added the interface assert in client_test.go

---

_[kv/local_test_cluster.go, line 48 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3202#-K3p4dA3-eCEVnqdStzh:-K3pX90yZccyEbX1o2pj:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/03833cf7fadeae3aac6829f59b7831eac12f1725/kv/local_test_cluster.go#L48)):_
done

---

_[kv/local_test_cluster.go, line 57 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3202#-K3p4lFVFw9DiH2ynZUd:-K3pXJM6mSa_PE7yVVRb:452881291) ([raw file](https://github.com/cockroachdb/cockroach/blob/03833cf7fadeae3aac6829f59b7831eac12f1725/kv/local_test_cluster.go#L57)):_
I interpret this as: do nothing.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3202)_

**Comment by tschottdorf** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3202)_

**Comment by vivekmenezes** [comment]
The first commit is just the mv of the files, the second commit is readjusting everything else.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3202#-:-K3paILxE648NAK9hNXD:-1356006374)_

**Comment by bdarnell** [comment]
LGTM

**Comment by tschottdorf** [comment]
Your first commit doesn't compile, though.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3202#-:-K3paoTnbmdgCdwczJ5c:-1534284165)_

**Comment by vivekmenezes** [comment]
True,  to aid in reviewing I split it into two commits. I've just rebased and now will merge it in as one. Thanks

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3202#-:-K3pbEFG3iQI3fmkPVy4:-353318582)_

**Pull request merged**
