### PR TITLE
sql: Generate family specific spans in zigzagjoiner.

### PR DESCRIPTION
**Pull request by rohany**
For point lookups in the zigzagjoiner, generate spans that are specific to the needed columns families, rather than requesting an entire row.

Addresses second half of #38280.

Release note: None

### CODE REVIEW

**Review by solongordon — COMMENTED** [review]
Thinking about this more, I'm doubting whether this optimization actually applies here. The fetches that the zigzagjoiner does are not point lookups. They are scans looking for the next rows greater than or equal to the specified start key. I think this precludes doing family-specific lookups.

@jordanlewis does that sound right to you?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38875#-:-LjvJW4413BbNvmnZIt4:b-k27yk3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

**Comment by jordanlewis** [comment]
I think that conceivably zigzag join could be planned such that all columns would be known after getting information from one of the sides, right? I think it depends on planning. I asked @justinj about this and he wasn't sure whether this was a possible scenario. I wonder if we could come up with some scenarios here to try to produce the behavior that would trigger the optimization.

**Comment by rohany** [comment]
I was having a tough time coming up with logic tests to verify the behavior -- i think we can put this aside for now though to focus on other things though.

**Comment by rohany** [comment]
Closing this, it doesn't seem like this optimization is really applicable here.

**Pull request closed without merging**
