### PR TITLE
pgwire: unexport ServerMetrics, rename to tenantSpecificMetrics

### PR DESCRIPTION
**Pull request by knz**
Parent PRs:
- [x] https://github.com/cockroachdb/cockroach/pull/84608
- [x] https://github.com/cockroachdb/cockroach/pull/91739
- [x] https://github.com/cockroachdb/cockroach/pull/91744

Epic: CRDB-14537

### CODE REVIEW

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92574)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/sql/pgwire/server.go` line 215 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92574#-NHz58IG4Kz_TTJmjGIf:-NHz58IG4Kz_TTJmjGIg:b-3d5ifc) ([raw file](https://github.com/cockroachdb/cockroach/blob/735d7c112834e31cecd60ca797d1025819845db7/pkg/sql/pgwire/server.go#L215)):*
> ```Go
> 
> // Server implements the server side of the PostgreSQL wire protocol for one
> // specific tenant (i.e. its configuration is specific to one tenant).
> ```

i don't follow why the "tenant specific" name is helpful here. it already seemed clear that this is a "per-connection object" which definitionally is finer-scoped than "tenant specific."

to take this PR's logic further, why not rename `Server` to `TenantSpecificServer`? (i don't think we should, just asking rhetorically)

**Comment by knz** [comment]
> it already seemed clear that this is a "per-connection object" which definitionally is finer-scoped than "tenant specific."

Nope, that is not how I want to frame it.
Connections _start_ in a tenant-agnostic state, then get _assigned_ to a specific tenant.

> to take this PR's logic further, why not rename Server to TenantSpecificServer? (i don't think we should, just asking rhetorically)

Yes, once this PR and its subsequent PRs, up to and including #92579 are merged, this would make (rhetorically) sense.

**Review by stevendanna — APPROVED** [review]
LGTM

**Comment by knz** [comment]
rafi, I will be willing to rename the various concepts in this code any time, for example in a followup PR.

bors r=stevendanna

**Comment by knz** [comment]
unrelated flake

bors r=stevendanna

**Comment by knz** [comment]
bors r=stevendanna

**Review by rafiss — APPROVED** [review]

**Pull request merged**
