### PR TITLE
distsql: API for streams

### PR DESCRIPTION
**Pull request by RaduBerinde**
Adding API for streams - an outgoing mailbox will call this API to set up a
stream to an incoming mailbox on a different host. The first message of the
stream identifies the mailbox (as flow uuid + stream id).

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7514)

### CODE REVIEW

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[sql/distsql/api.proto, line 46 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7514#-KLXR86o9dc2H-s8X0St:-KLXR86o9dc2H-s8X0Su:-171151881) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca6ace3129ac65b002d4212eee80a2320eef9c55/sql/distsql/api.proto#L46)):*
> ```protobuf
>   // SetupFlows instantiates a set of flows (subgraphs of a distributed SQL
>   // computation) on the receiving node.
>   rpc SetupFlows(SetupFlowsRequest) returns (SimpleResponse) {}
> ```

what does `;' vs `{}` mean?

---

*[sql/distsql/data.proto, line 132 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7514#-KLXSLmLvADnO2mNJUb4:-KLXSLmMOXN3J_MCUGQ6:1144569540) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca6ace3129ac65b002d4212eee80a2320eef9c55/sql/distsql/data.proto#L132)):*
> ```protobuf
> 
>   optional int32 stream_id = 2 [(gogoproto.nullable) = false,
>            (gogoproto.customname) = "StreamID"];
> ```

nit: alignment is different than above

---

*[sql/distsql/flow.go, line 27 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7514#-KLXSvWcovjHA8aNkPaJ:-KLXSvWcovjHA8aNkPaK:1308567393) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7e9966a9136baac4ffd6da894a9de4b629a7eb0/sql/distsql/flow.go#L27)):*
> ```Go
> )
> 
> // StreamID identifies a stream that crosses machine boundaries. The identifier
> ```

do these need to be public?

---

*[sql/distsql/processors.proto, line 115 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7514#-KLXScEs0-KCpdHRHPJ6:-KLXScEs0-KCpdHRHPJ7:-606875032) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7e9966a9136baac4ffd6da894a9de4b629a7eb0/sql/distsql/processors.proto#L115)):*
> ```protobuf
>       (gogoproto.customtype) = "github.com/cockroachdb/cockroach/util/uuid.UUID"];
> 
>   repeated ProcessorSpec processors = 2 [(gogoproto.nullable) = false];
> ```

pray nobody sees this edit

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7514#-:-KLXZYclbQARbcBAV8_M:1417088721)*

**Comment by RaduBerinde** [comment]
TFTR, updated.

---

Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[sql/distsql/api.proto, line 46 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7514#-KLXR86o9dc2H-s8X0St:-KLXheUuCpIJiACgd3TP:-78065101) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca6ace3129ac65b002d4212eee80a2320eef9c55/sql/distsql/api.proto#L46)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> what does `;' vs `{}` mean?
</details>
No difference (I hope).  I didn't realize it but the docs and all other instances we have use `{}` so I switched to that

---

*[sql/distsql/flow.go, line 27 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7514#-KLXSvWcovjHA8aNkPaJ:-KLXiDHwTW4w9wu3XAE3:-1605098810) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7e9966a9136baac4ffd6da894a9de4b629a7eb0/sql/distsql/flow.go#L27)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> do these need to be public?
</details>
guess not, fixing

---

*[sql/distsql/processors.proto, line 115 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7514#-KLXScEs0-KCpdHRHPJ6:-KLXlaV0Lck7gh6edRnw:632473060) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7e9966a9136baac4ffd6da894a9de4b629a7eb0/sql/distsql/processors.proto#L115)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> pray nobody sees this edit
</details>
If a protobuf member gets its id changed but no one is around to hear it scream..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7514#-:-KLXm-k64bkJJJJuQ4rp:556295420)*

**Comment by tschottdorf** [comment]
Reviewed 7 of 7 files at r1, 3 of 3 files at r2.
Review status: 5 of 8 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[sql/distsql/flow.go, line 27 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7514#-KLXSvWcovjHA8aNkPaJ:-KLXodV3bRZJd1H0mwTh:-1253495953) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7e9966a9136baac4ffd6da894a9de4b629a7eb0/sql/distsql/flow.go#L27)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> guess not, fixing
</details>
Sure about this? The protos are exported, and it's awkward if you can't populate this proto from somewhere else because there's a package-local type used as a castkey. Disregard if you're not using these as cast keys any more.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7514)*

**Comment by RaduBerinde** [comment]
Review status: 5 of 8 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[sql/distsql/flow.go, line 27 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7514#-KLXSvWcovjHA8aNkPaJ:-KLXqkg7OuJv3_UMG9Le:2113119823) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7e9966a9136baac4ffd6da894a9de4b629a7eb0/sql/distsql/flow.go#L27)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Sure about this? The protos are exported, and it's awkward if you can't populate this proto from somewhere else because there's a package-local type used as a castkey. Disregard if you're not using these as cast keys any more.
</details>
Hm, that's a good point. I started with them exported because that seemed to be always the case with protos but I didn't know a good reason for it. This is a good enough reason to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7514)*

**Pull request merged**
