### PR TITLE
sql: get rid of DescriptorMissingError error detail

### PR DESCRIPTION
**Pull request by andreimatei**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6549)

### CODE REVIEW

**Comment by dt** [comment]
Reviewed 6 of 8 files at r1.
Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[roachpb/errors.proto, line 232 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6549#-KH24EoiksNyj6fry05G:-KH24EoiksNyj6fry05H:-1662991322) ([raw file](https://github.com/cockroachdb/cockroach/blob/50663aaf4947c122382fae559797f4981ace8ce2/roachpb/errors.proto#L232)):*
woah, deleting fields?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6549)*

**Comment by andreimatei** [comment]
Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[roachpb/errors.proto, line 232 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6549#-KH24EoiksNyj6fry05G:-KH25h7ERprrKUGP1qRE:194113370) ([raw file](https://github.com/cockroachdb/cockroach/blob/50663aaf4947c122382fae559797f4981ace8ce2/roachpb/errors.proto#L232)):*
heh, I said in another PR that I'm asking for an exemption :) Protos with these fields set were never sent over the network.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6549)*

**Comment by tamird** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/table.go, line 88 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6549#-KH2YcURyCQsKJimPbVQ:-KH2YcURyCQsKJimPbVR:-1633809435) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b014e126b03a67e8bb3be45bc86c8b5ad06f250/sql/table.go#L88)):*
does this error ever leak out to the user?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6549)*

**Comment by andreimatei** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/table.go, line 88 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6549#-KH2YcURyCQsKJimPbVQ:-KH60FAG9eFwJevZtiXR:-1135145651) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b014e126b03a67e8bb3be45bc86c8b5ad06f250/sql/table.go#L88)):*
no, it shouldn't

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6549)*

**Comment by tamird** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6549#-:-KH60ZxfMratajTBDuP3:1417088721)*

**Pull request merged**
