### PR TITLE
opt: prefer to scan smaller indexes

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change tweaks the cost of scan so that it depends on the number
of columns in the index. The goal is to prefer an index with fewer
columns when possible.

For this to work properly, the RowCount and DisinctCount in stats were
changed to floats to allow them to be smaller than 1. An example of
why: we have no stats and are choosing between an index with `a=1`
constraint and an index with `(a,b)=(1,2)` constraint. Because of the
way we calculate selectivity, the estimate for the first index is ~1
row.  The estimate for the second index is much smaller, but to the
old code they were both 1. We do want the second index here because in
reality there could be many rows for a specific value of `a`.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
This turned out to be a bit of a rabbit hole. I'm open to suggestions about the cost formulas.

**Comment by RaduBerinde** [comment]
*[pkg/sql/opt/xform/coster.go, line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26714#-LEy79W1-02WaRjxTww9:-LEy79W1-02WaRjxTwwA:b-v0fa0h) ([raw file](https://github.com/cockroachdb/cockroach/blob/26b518de559c231bf85f8e95645b9863eeafadce/pkg/sql/opt/xform/coster.go#L122)):*
> ```Go
> 	// sort with a temp RocksDB store. Add an IO cost, proportional to the number
> 	// of columns we are sorting.
> 	cost += memo.Cost(rowCount * float64(logical.Relational.OutputCols.Len()) * seqIOCostFactor)
> ```

This change might cause us to push more complicated subtrees inside index-join which we can't execute.. If we run into trouble, I might need to revert this to only depend on `RowCount` so that higher-level sorts are preferred (along with the epsilon change in #26597).

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26714)*

**Comment by RaduBerinde** [comment]
I updated the PR: I scaled the number of columns using the cpu cost factor, and left the sort cost as-is. This fixed a bunch of cases where we switched to index join on just an inequality.

**Comment by andy-kimball** [comment]
:lgtm:

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/opt/exec/execbuilder/testdata/orderby, line 311 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26714#-LEzUsHP9tGb_spF445H:-LEzUsHQ0Lc0sYlmghbr:b4rustd) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cee8f815a5474fbd9a7358d4c15615b180ec3ba/pkg/sql/opt/exec/execbuilder/testdata/orderby#L311)):*
> ```
> ·          spans  ALL
> 
> query TTT
> ```

We still need a TODO that the sort needs to be eliminated.

---

*[pkg/sql/opt/xform/testdata/external/tpcc, line 711 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26714#-LEziGgPE9LHNWMLSFXE:-LEziGgPE9LHNWMLSFXF:b-d3ikjp) ([raw file](https://github.com/cockroachdb/cockroach/blob/47948e64a7885618a5ca6a8cb18e943fbafda70b/pkg/sql/opt/xform/testdata/external/tpcc#L711)):*
> ```
>                 ├── columns: customer.c_id:1(int!null) customer.c_d_id:2(int!null) customer.c_w_id:3(int!null) customer.c_first:4(string) customer.c_last:6(string)
>                 ├── constraint: /3/2/6/4/1: [/10/100/'Smith' - /10/100/'Smith']
>                 ├── stats: [rows=0, distinct(2)=0, distinct(3)=0, distinct(6)=0]
> ```

How come rows/cost are 0 here? Are we rounding down for display?

---

*[pkg/sql/opt/xform/testdata/external/tpcc, line 748 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26714#-LEzipFGCi33rb0P9YTI:-LEzipFH-o9ht2PogOI5:b-6xka2f) ([raw file](https://github.com/cockroachdb/cockroach/blob/47948e64a7885618a5ca6a8cb18e943fbafda70b/pkg/sql/opt/xform/testdata/external/tpcc#L748)):*
> ```
>       │         ├── columns: "order".o_id:1(int!null) "order".o_d_id:2(int!null) "order".o_w_id:3(int!null) "order".o_c_id:4(int!null) "order".o_entry_d:5(timestamp) "order".o_carrier_id:6(int)
>       │         ├── key columns: [3 2 1]
>       │         ├── stats: [rows=0, distinct(2)=0, distinct(3)=0, distinct(4)=0]
> ```

This should be estimating 1000 rows since we have the following stat:
```
  {
    "columns": ["o_w_id", "o_d_id", "o_carrier_id"],
    "created_at": "2018-01-01 1:00:00.00000+00:00",
    "row_count": 300000,
    "distinct_count": 1000
  },
```
However, maybe we don't have complete support yet. But 0 seems wrong. Maybe +@rytaft could do a deeper dive on some of these stats issues with TPCC.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26714#-:-LEzjV96DQxjR8f5nV3e:bnfp4nl)*

**Comment by andy-kimball** [comment]
*[pkg/sql/opt/xform/testdata/external/tpcc, line 748 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26714#-LEzipFGCi33rb0P9YTI:-LEzmpAWB87Lb4xucKAS:b-d2xzdk) ([raw file](https://github.com/cockroachdb/cockroach/blob/47948e64a7885618a5ca6a8cb18e943fbafda70b/pkg/sql/opt/xform/testdata/external/tpcc#L748)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

This should be estimating 1000 rows since we have the following stat:
```
  {
    "columns": ["o_w_id", "o_d_id", "o_carrier_id"],
    "created_at": "2018-01-01 1:00:00.00000+00:00",
    "row_count": 300000,
    "distinct_count": 1000
  },
```
However, maybe we don't have complete support yet. But 0 seems wrong. Maybe +@rytaft could do a deeper dive on some of these stats issues with TPCC.
</blockquote></details>

Actually, should be 300 rows estimated, not 1000...

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26714)*

**Comment by RaduBerinde** [comment]
Review status: :shipit: complete! 1 of 0 LGTMs obtained

---

*[pkg/sql/opt/exec/execbuilder/testdata/orderby, line 311 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26714#-LEzUsHP9tGb_spF445H:-LEzutX438-ZWxQKcaEE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cee8f815a5474fbd9a7358d4c15615b180ec3ba/pkg/sql/opt/exec/execbuilder/testdata/orderby#L311)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

We still need a TODO that the sort needs to be eliminated.
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/testdata/external/tpcc, line 711 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26714#-LEziGgPE9LHNWMLSFXE:-LEzvRVUCnzYbCBciFUd:b-sy53ew) ([raw file](https://github.com/cockroachdb/cockroach/blob/47948e64a7885618a5ca6a8cb18e943fbafda70b/pkg/sql/opt/xform/testdata/external/tpcc#L711)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

How come rows/cost are 0 here? Are we rounding down for display?
</blockquote></details>

Yeah we only display 2 decimals

---

*[pkg/sql/opt/xform/testdata/external/tpcc, line 748 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26714#-LEzipFGCi33rb0P9YTI:-LEzwaim-WtY5lgAd55o:b-lj17wj) ([raw file](https://github.com/cockroachdb/cockroach/blob/47948e64a7885618a5ca6a8cb18e943fbafda70b/pkg/sql/opt/xform/testdata/external/tpcc#L748)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Actually, should be 300 rows estimated, not 1000...
</blockquote></details>

Yeah, it looks like the relevant stats code doesn't look at multi-column stats.
BTW we can't even generate multi-column stats yet (there are some TODOs in the stats code).

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26714)*

**Comment by RaduBerinde** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/opt/exec/execbuilder/testdata/select_index, line 470 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26714#-LF-phsk69ZeU7Nvo9bc:-LF-phsk69ZeU7Nvo9bd:b-xoe1t7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8066d672e276e8bc6751827ecfbdb858b355b2a9/pkg/sql/opt/exec/execbuilder/testdata/select_index#L470)):*
> ```
> ·          spans     /1/4-/1/5  ·       ·
> 
> # TODO(radu): this should use the abcd index. Both scans are estimate to return
> ```

This is another strange case. I looked at optsteps and both indexes get the same estimated number of rows (2.86):


```
  +      └── scan abcd@abcd
              ├── columns: a:1(int!null) b:2(int)
  +           ├── constraint: /1/2/3/4/5: [/1/4 - /1/4] [/2/9 - /2/9]
              ├── stats: [rows=2.86, distinct(1)=2]
  -           ├── cost: 3.06
  -           ├── scan abcd@adb
  -           │    ├── columns: a:1(int) b:2(int)
  -           │    ├── constraint: /1/4/2/5: [/1 - /2]
  -           │    ├── stats: [rows=2.86, distinct(1)=2]
  -           │    └── cost: 3.03
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26714)*

**Comment by andy-kimball** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/opt/exec/execbuilder/testdata/select_index, line 470 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26714#-LF-phsk69ZeU7Nvo9bc:-LF0-bX58711uwZZ1a4b:b3n0s05) ([raw file](https://github.com/cockroachdb/cockroach/blob/8066d672e276e8bc6751827ecfbdb858b355b2a9/pkg/sql/opt/exec/execbuilder/testdata/select_index#L470)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is another strange case. I looked at optsteps and both indexes get the same estimated number of rows (2.86):


```
  +      └── scan abcd@abcd
              ├── columns: a:1(int!null) b:2(int)
  +           ├── constraint: /1/2/3/4/5: [/1/4 - /1/4] [/2/9 - /2/9]
              ├── stats: [rows=2.86, distinct(1)=2]
  -           ├── cost: 3.06
  -           ├── scan abcd@adb
  -           │    ├── columns: a:1(int) b:2(int)
  -           │    ├── constraint: /1/4/2/5: [/1 - /2]
  -           │    ├── stats: [rows=2.86, distinct(1)=2]
  -           │    └── cost: 3.03
```
</blockquote></details>

Yeah, that's really concerning, since it's causing us to pick a less constrained index.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26714)*

**Comment by rytaft** [comment]
*[pkg/sql/opt/xform/testdata/external/tpcc, line 748 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26714#-LEzipFGCi33rb0P9YTI:-LFOe8280pO0U_8lIjvW:b-8pnk58) ([raw file](https://github.com/cockroachdb/cockroach/blob/47948e64a7885618a5ca6a8cb18e943fbafda70b/pkg/sql/opt/xform/testdata/external/tpcc#L748)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Yeah, it looks like the relevant stats code doesn't look at multi-column stats.
BTW we can't even generate multi-column stats yet (there are some TODOs in the stats code).
</blockquote></details>

This is actually working as intended. If I just run `build` instead of `opt`, I can see that for the full table scan of `customer` it estimates `rows: 300000, distinct(c_d_id): 210000, distinct(d_w_id): 10, distinct(c_last): 210000`. The selectivity of the predicate is calculated as: `(1/210000)*(1/10)*(1/210000)`, which is about `2.3e-12`. Therefore, the row count after the filter is estimated to be `2.3e-12 * 300000 = 6.8e-7`. Since this is less than 0.0001, it's printed as 0.

Once the FD code is merged, I can update the selectivity calculation to take the FDs into account and get a more accurate estimate.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26714)*

**Pull request merged**
