### PR TITLE
sqlccl: distributed import progress tracking

### PR DESCRIPTION
**Pull request by madelynnblue**
This PR hits a bunch of different systems. I think if the three of you review just the stuff you're familiar with it should cover it all.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
distsqlrun part LGTM

---

Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/distsqlrun/processors.proto, line 465 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20976#-L0uiGp-SwSLkOELovVv:-L0uiGp-SwSLkOELovVw:bx5atw4) ([raw file](https://github.com/cockroachdb/cockroach/blob/909135c100aea5b8e5c1345166fdf1dc7ead4cdc/pkg/sql/distsqlrun/processors.proto#L465)):*
> ```protobuf
> }
> 
> message JobProgress {
> ```

[nit] This could use a comment to say that it identifies the job to report progress on (which happens out-of-band, i.e. not through distsql).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20976#-:-L0uiqMd-dIz4iBEpMxS:b-ufttrr)*

**Comment by dt** [comment]
Reviewed 2 of 6 files at r1, 11 of 11 files at r4, 5 of 5 files at r5, 3 of 8 files at r6.
Review status: 8 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/sqlccl/progress.go, line 68 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/20976#-L1TdauImyiNYDuuti34:-L1TdauJrucZnkwRUJHM:b-pvv2ir) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd6600682d35c22234e9afcf012257b9bdc2a259/pkg/ccl/sqlccl/progress.go#L68)):*
> ```Go
> 	jpl.lastReportedFraction = fraction
> 	return jpl.job.Progressed(ctx, func(ctx context.Context, details interface{}) float32 {
> 		jpl.progressedFn(ctx, details)
> ```

the ci failure suggests this either wants the nil check that used to be in job.Progressed or we need to be more diligent about all the creators of jobProgressLoggers initializing progressedFn?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20976)*

**Comment by mjibson** [comment]
Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/ccl/sqlccl/progress.go, line 68 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/20976#-L1TdauImyiNYDuuti34:-L24IjCRf5qnhwlbD6RN:b-7xzgr) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd6600682d35c22234e9afcf012257b9bdc2a259/pkg/ccl/sqlccl/progress.go#L68)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

the ci failure suggests this either wants the nil check that used to be in job.Progressed or we need to be more diligent about all the creators of jobProgressLoggers initializing progressedFn?
</blockquote></details>

nil check is enough i think

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20976)*

**Comment by mjibson** [comment]
Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/distsqlrun/processors.proto, line 465 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20976#-L0uiGp-SwSLkOELovVv:-L24InCebnVd7XnKB7jE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/909135c100aea5b8e5c1345166fdf1dc7ead4cdc/pkg/sql/distsqlrun/processors.proto#L465)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] This could use a comment to say that it identifies the job to report progress on (which happens out-of-band, i.e. not through distsql).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20976)*

**Comment by mjibson** [comment]
@benesch can you review the jobs stuff here?

**Comment by benesch** [comment]
Approach looks great! Got some naming/commenting nits though.

---

Reviewed 13 of 13 files at r7, 5 of 5 files at r8.
Review status: 5 of 13 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/sqlccl/progress.go, line 36 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/20976#-L2QeE3dHkbtVWYmX_u8:-L2Qdbt1Dw2q640J1nrr:b6dt4xz) ([raw file](https://github.com/cockroachdb/cockroach/blob/25b9f7a5503bce5776ad5b2162404623695d84f4/pkg/ccl/sqlccl/progress.go#L36)):*
> ```Go
> 	startFraction float32
> 	totalChunks   int
> 	progressedFn  func(context.Context, interface{})
> ```

Jordan added a marker interface for this that we should use: `jobs.Details`. Just to make the code a bit more self-documenting.

---

*[pkg/ccl/sqlccl/progress.go, line 66 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/20976#-L2QeMHUFslJvcwG3FnB:-L2QeMHUFslJvcwG3FnC:b-8brjlp) ([raw file](https://github.com/cockroachdb/cockroach/blob/25b9f7a5503bce5776ad5b2162404623695d84f4/pkg/ccl/sqlccl/progress.go#L66)):*
> ```Go
> 	jpl.lastReportedAt = timeutil.Now()
> 	jpl.lastReportedFraction = fraction
> 	return jpl.job.Progressed(ctx, func(ctx context.Context, details interface{}) float32 {
> ```

`jobs.Details` here, too.

---

*[pkg/sql/jobs/jobs.go, line 156 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/20976#-L2QeXVSrEy72idlY4FW:-L2QeXVSrEy72idlY4FX:b-j64gjt) ([raw file](https://github.com/cockroachdb/cockroach/blob/25b9f7a5503bce5776ad5b2162404623695d84f4/pkg/sql/jobs/jobs.go#L156)):*
> ```Go
> 
> // ProgressedFn is a callback that allows arbitrary modifications to a job's
> // details when updating its progress.
> ```

"ProgressedFn is a callback that computes a job's completion fraction given its details. It is safe to modify details in the callback; those modifications will be automatically persisted to the database record."

---

*[pkg/sql/jobs/jobs.go, line 160 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/20976#-L2QfcPlEE-GkNf10g_y:-L2QfcPlEE-GkNf10g_z:b-ym7y2r) ([raw file](https://github.com/cockroachdb/cockroach/blob/25b9f7a5503bce5776ad5b2162404623695d84f4/pkg/sql/jobs/jobs.go#L160)):*
> ```Go
> 
> // Noop returns a ProgressedFn that returns its argument.
> func Noop(f float32) ProgressedFn {
> ```

Eek, this confused me. `Noop` seems like the wrong name now. I'll throw out `FractionUpdater`, which seems to read pretty well:

```
jobs.Progressed(ctx, jobs.FractionUpdater(0.7))
```

---

*[pkg/sql/jobs/jobs.go, line 171 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/20976#-L2Qf5Fmq9SbpDn1Erij:-L2Qf5Fmq9SbpDn1Erik:b-effjaz) ([raw file](https://github.com/cockroachdb/cockroach/blob/25b9f7a5503bce5776ad5b2162404623695d84f4/pkg/sql/jobs/jobs.go#L171)):*
> ```Go
> // a pointer to the job's details to allow for modifications to the details
> // before the job is saved. If no such modifications are required, pass Noop
> // instead of nil for readability.
> ```

"Progressed updates the progress of the tracked job. It sets the job's FractionCompleted field to the value returned by progressedFn and persists progressedFn's modifications to the job's details, if any.

Jobs for which progress computations do not depend on their details can use the FractionUpdater helper to construct a ProgressedFn."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20976#-:-L2QnrUEWWWmkUQu8zbL:b7tge7i)*

**Comment by mjibson** [comment]
Review status: 0 of 14 files reviewed at latest revision, 7 unresolved discussions.

---

*[pkg/ccl/sqlccl/progress.go, line 36 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/20976#-L2QeE3dHkbtVWYmX_u8:-L2RbrzBED3hI0Ki0RTt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/25b9f7a5503bce5776ad5b2162404623695d84f4/pkg/ccl/sqlccl/progress.go#L36)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Jordan added a marker interface for this that we should use: `jobs.Details`. Just to make the code a bit more self-documenting.
</blockquote></details>

Done.

---

*[pkg/ccl/sqlccl/progress.go, line 66 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/20976#-L2QeMHUFslJvcwG3FnB:-L2RbslvOLBV9X9DLt-z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/25b9f7a5503bce5776ad5b2162404623695d84f4/pkg/ccl/sqlccl/progress.go#L66)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

`jobs.Details` here, too.
</blockquote></details>

Done.

---

*[pkg/sql/jobs/jobs.go, line 160 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/20976#-L2QfcPlEE-GkNf10g_y:-L2Rc1ZtMf_qgfPQKR3L:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/25b9f7a5503bce5776ad5b2162404623695d84f4/pkg/sql/jobs/jobs.go#L160)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Eek, this confused me. `Noop` seems like the wrong name now. I'll throw out `FractionUpdater`, which seems to read pretty well:

```
jobs.Progressed(ctx, jobs.FractionUpdater(0.7))
```
</blockquote></details>

Done.

---

*[pkg/sql/jobs/jobs.go, line 171 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/20976#-L2Qf5Fmq9SbpDn1Erij:-L2RcDHUE06_zz9gaXe2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/25b9f7a5503bce5776ad5b2162404623695d84f4/pkg/sql/jobs/jobs.go#L171)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

"Progressed updates the progress of the tracked job. It sets the job's FractionCompleted field to the value returned by progressedFn and persists progressedFn's modifications to the job's details, if any.

Jobs for which progress computations do not depend on their details can use the FractionUpdater helper to construct a ProgressedFn."
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20976)*

**Comment by benesch** [comment]
Job stuff :lgtm: 

---

Reviewed 11 of 11 files at r9, 5 of 5 files at r10, 8 of 8 files at r11.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20976#-:-L2RkYNNCtafgUxbxmvF:bpmivy8)*

**Comment by dt** [comment]
:lgtm:

---

Review status: 2 of 14 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20976#-:-L2WOjzfnzvNYw_Qq2Bg:bnfp4nl)*

**Pull request merged**
