### PR TITLE
parser: focus on LOCALITY syntax + add PRIMARY REGION syntax

### PR DESCRIPTION
**Pull request by otan**
* Changed the code to focus on SET LOCALITY ... as the primary setting.
* Added `PRIMARY REGION` syntax for configuration.

Release note (sql change): Added `LOCALITY REGIONAL BY TABLE IN
PRIMARY REGION` syntax for configuring table locality.

### CODE REVIEW

**Review by ajstorm — CHANGES_REQUESTED** [review]
These changes look good, but I checked with @awoods187 and we still want to be able to test the AFFINITY syntax with users.  It's a bit premature to pull it all out now, but you can certainly continue with the internal rename (though not sure it's worth it right now).  

Also, a few minors about REGIONAL BY TABLE without the IN clause.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57275#-:-MNUoxs1-2dAxbnLJGmZ:bdlozyb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[docs/generated/sql/bnf/stmt_block.bnf, line 2130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57275#-MNUoXF_4manAkLUJUaG:-MNUoXF_4manAkLUJUaH:b-wxckkk) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d81f3bb9eec6918483f5124521895308b414e76/docs/generated/sql/bnf/stmt_block.bnf#L2130)):*
> ```
> locality ::=
> 	'LOCALITY' 'GLOBAL'
> 	| 'LOCALITY' 'REGIONAL' 'BY' 'TABLE' 'IN' region_name
> ```

Do we need a REGIONAL BY TABLE without the IN here?
___
*[pkg/sql/parser/parse_test.go, line 1396 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57275#-MNUocz28Ill5q8N4Axo:-MNUocz28Ill5q8N4Axp:b-zbuuz5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d81f3bb9eec6918483f5124521895308b414e76/pkg/sql/parser/parse_test.go#L1396)):*
> ```Go
> 		{`ALTER TABLE a RENAME CONSTRAINT c TO d, RENAME COLUMN e TO f`},
> 		{`ALTER TABLE a SET LOCALITY GLOBAL`},
> 		{`ALTER TABLE a SET LOCALITY REGIONAL BY TABLE IN region_name`},
> ```

Same comment as above.  REGIONAL BY TABLE without the IN
___
*[pkg/sql/sem/tree/region.go, line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57275#-MNUoB2_CoqwQ4kLg5zJ:-MNUoB2_CoqwQ4kLg5zK:b-dhjycz) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d81f3bb9eec6918483f5124521895308b414e76/pkg/sql/sem/tree/region.go#L43)):*
> ```Go
> 		ctx.WriteString("GLOBAL")
> 	case LocalityLevelTable:
> 		ctx.WriteString("REGIONAL BY TABLE IN ")
> ```

Will this show the IN even in cases where the user doesn't specify a region (i.e. the table is to reside in the primary region)?

**Review by otan — COMMENTED** [review]
Ok, I'll re-add the AFFINITY syntax just in case. I still want the renames (and now PRIMARY REGION) logic to go through.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57275#-:-MNUxqCN3nCvFPTCm6I2:bgd5d00)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[docs/generated/sql/bnf/stmt_block.bnf, line 2130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57275#-MNUoXF_4manAkLUJUaG:-MNUxYcLBZoMxE9jiFJj:b-limh8v) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d81f3bb9eec6918483f5124521895308b414e76/docs/generated/sql/bnf/stmt_block.bnf#L2130)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Do we need a REGIONAL BY TABLE without the IN here?
</blockquote></details>

The spec requires the IN, I think `LOCALITY REGIONAL BY TABLE "us-west-1"` looks a bit awkies.
___
*[pkg/sql/parser/parse_test.go, line 1396 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57275#-MNUocz28Ill5q8N4Axo:-MNUxnLEEhYplD8V72CC:bwa2mq6) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d81f3bb9eec6918483f5124521895308b414e76/pkg/sql/parser/parse_test.go#L1396)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Same comment as above.  REGIONAL BY TABLE without the IN
</blockquote></details>

huh, forgot to do PRIMARY REGION. Let me do that.

**Review by ajstorm — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57275)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[docs/generated/sql/bnf/stmt_block.bnf, line 2130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57275#-MNUoXF_4manAkLUJUaG:-MNVIjQnELRja6IL4hrX:b-e8f3pb) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d81f3bb9eec6918483f5124521895308b414e76/docs/generated/sql/bnf/stmt_block.bnf#L2130)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

The spec requires the IN, I think `LOCALITY REGIONAL BY TABLE "us-west-1"` looks a bit awkies.
</blockquote></details>

Sorry, I might not have been clear.  I agree we want it for that case, but I'm worried about the case where the user wants to have the table in the PRIMARY REGION.  In that case, can't we allow LOCALITY REGIONAL BY TABLE with no IN PRIMARY REGION clause, and default to the PRIMARY REGION?

**Comment by otan** [comment]
___
*[docs/generated/sql/bnf/stmt_block.bnf, line 2130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57275#-MNUoXF_4manAkLUJUaG:-MNVdHP9EDGX18REaaas:b-jx1r1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d81f3bb9eec6918483f5124521895308b414e76/docs/generated/sql/bnf/stmt_block.bnf#L2130)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Sorry, I might not have been clear.  I agree we want it for that case, but I'm worried about the case where the user wants to have the table in the PRIMARY REGION.  In that case, can't we allow LOCALITY REGIONAL BY TABLE with no IN PRIMARY REGION clause, and default to the PRIMARY REGION?
</blockquote></details>

ah, is that part of the spec? i read it as requiring `IN PRIMARY REGION`

**Comment by otan** [comment]
___
*[docs/generated/sql/bnf/stmt_block.bnf, line 2130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57275#-MNUoXF_4manAkLUJUaG:-MNVdoiLD-HdUq9bJ65C:bj6sbwj) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d81f3bb9eec6918483f5124521895308b414e76/docs/generated/sql/bnf/stmt_block.bnf#L2130)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

ah, is that part of the spec? i read it as requiring `IN PRIMARY REGION`
</blockquote></details>

(i'm not a big fan of `REGIONAL BY TABLE` inferring PRIMARY REGION as it is not explicit)

**Review by ajstorm — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57275)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[docs/generated/sql/bnf/stmt_block.bnf, line 2130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57275#-MNUoXF_4manAkLUJUaG:-MNVtHmZ91XuWBI4tqtK:b2hflza) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d81f3bb9eec6918483f5124521895308b414e76/docs/generated/sql/bnf/stmt_block.bnf#L2130)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

(i'm not a big fan of `REGIONAL BY TABLE` inferring PRIMARY REGION as it is not explicit)
</blockquote></details>

I think it might make sense for a few reasons:

1) REGIONAL BY TABLE IN PRIMARY REGION is the default table pattern
2) If you specify nothing (i.e. CREATE TABLE t (c1 int)) you get REGIONAL BY TABLE IN PRIMARY REGION so long as the database is a multi-region database
3) REGIONAL BY TABLE IN PRIMARY REGION is wordy

2) is probably the strongest argument.  We're doing a lot of inferring, so it seems reasonable to me to infer a bit more to make the syntax a bit cleaner in the case where the user wants the table in the PRIMARY REGION.

You are right that this might not be in the spec right now.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57275)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[docs/generated/sql/bnf/stmt_block.bnf, line 2130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57275#-MNUoXF_4manAkLUJUaG:-MNWUPaY7iPE81HEK0e6:bao9jb3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d81f3bb9eec6918483f5124521895308b414e76/docs/generated/sql/bnf/stmt_block.bnf#L2130)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

I think it might make sense for a few reasons:

1) REGIONAL BY TABLE IN PRIMARY REGION is the default table pattern
2) If you specify nothing (i.e. CREATE TABLE t (c1 int)) you get REGIONAL BY TABLE IN PRIMARY REGION so long as the database is a multi-region database
3) REGIONAL BY TABLE IN PRIMARY REGION is wordy

2) is probably the strongest argument.  We're doing a lot of inferring, so it seems reasonable to me to infer a bit more to make the syntax a bit cleaner in the case where the user wants the table in the PRIMARY REGION.

You are right that this might not be in the spec right now.
</blockquote></details>

ok, i've added it in.
it doesn't really work well for the other syntaxes so the LOCALITY REGIONAL BY TABLE is what i've done.

**Review by ajstorm — APPROVED** [review]
Changes look good.  :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57275#-:-MNZ5LIX8pOWweyMeNJl:b-53btjy)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[docs/generated/sql/bnf/stmt_block.bnf, line 2130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57275#-MNUoXF_4manAkLUJUaG:-MNZ4vW9DSo1dhuK7bHe:b-2h5px) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d81f3bb9eec6918483f5124521895308b414e76/docs/generated/sql/bnf/stmt_block.bnf#L2130)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

ok, i've added it in.
it doesn't really work well for the other syntaxes so the LOCALITY REGIONAL BY TABLE is what i've done.
</blockquote></details>

Awesome.  I agree that it doesn't work for the others.

**Comment by otan** [comment]
bors r=ajstorm

**Comment by otan** [comment]
bors r-

this cries when rebasing onto master o_o

**Comment by otan** [comment]
had to remove `TABLE LEVEL REGIONAL AFFINITY TO PRIMARY REGION` as it causes a super index build error in goyacc.
```

[17:01:24][run] panic: runtime error: index out of range [120000] with length 120000
[17:01:24][run] 
[17:01:24][run] goroutine 1 [running]:
[17:01:24][run] main.stin(0x93b)
[17:01:24][run] 	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/tools/cmd/goyacc/yacc.go:2765 +0x63b
[17:01:24][run] main.callopt()
[17:01:24][run] 	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/tools/cmd/goyacc/yacc.go:2655 +0x3e5
[17:01:24][run] main.main()
[17:01:24][run] 	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/tools/cmd/goyacc/yacc.go:365 +0x12a
[17:01:24][run] Makefile:1428: recipe for target 'pkg/sql/parser/gen/sql.go.tmp' failed
[17:01:24][run] make: *** [pkg/sql/parser/gen/sql.go.tmp] Error 2
```

we'll come back to it later

**Comment by otan** [comment]
bors r=ajstorm

**Pull request merged**
