### PR TITLE
*: upgrade etcd/raft to master

### PR DESCRIPTION
**Pull request by tbg**
We were using a custom fork that we picked up during our vgo transition,
but in the meantime upstream has turned `raft` into a small module which
has very few deps, and which we can switch back to.

Helpfully, this module already pins gogoproto v1.3+, which simplifies
PR #56147.

I did review the commits we're picking up here in etcd/raft and they look good. The ones worth pointing out are:

https://github.com/etcd-io/etcd/pull/12137
https://github.com/etcd-io/etcd/pull/12134
https://github.com/etcd-io/etcd/pull/12163

These all seem to fix real bugs.

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
I did review the commits we're picking up here in etcd/raft and they look good. The ones worth pointing out are:

https://github.com/etcd-io/etcd/pull/12137
https://github.com/etcd-io/etcd/pull/12134
https://github.com/etcd-io/etcd/pull/12163

These all seem to fix real bugs.

**Review by knz — APPROVED** [review]
Code change here LGTM, but: there are some linter errors now (I don't understand where they come from)

> Reviewed 88 of 88 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56233#-:-MLmDbvD1E-sW6BkxUIG:bqae00t)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by knz — COMMENTED** [review]
oh it's because you're also bumping staticcheck in the same vendor bump. Why did you do so?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56233#-:-MLmEPS4AzC8F842qAGD:br2v615)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by tbg** [comment]
This honnef.co dependency likes to bump itself for reasons I don't understand. And when it does, it bumps itself to a version that has bugs (shows tons of stuff as unused), which I know has happened to a few people in the past, so I thought I would bump us all the way to a version that does not have that bug (I think the linter complaints are all legit).

I should split that out though. Do you a) understand why that dep would always bump despite being pinned and b) think we should upgrade it to the version I have here (which is essentially the latest release)?

**Comment by knz** [comment]
>  Do you a) understand why that dep would always bump despite being pinned

it would if the dependency you're updating depends on a newer version of it

> and b) think we should upgrade it to the version I have here (which is essentially the latest release)?

I don't mind

**Comment by tbg** [comment]
Scheduling a bors attempt provided CI goes green (which it ought to this time around)

bors r=knz

**Comment by tbg** [comment]
bors single on
bors r=knz

Managed to fix the dep diff finally, I had some .go files in ./artifacts/go-build-xxxx that confused go mod tidy.

**Pull request merged**
