### PR TITLE
sql: fixing "copy from stdin" issues

### PR DESCRIPTION
**Pull request by andreimatei**
See individual commits.

### CODE REVIEW

**Comment by knz** [comment]
Thanks for these much-awaited patches.
The code is OK I think, but I have two major nits:

- there's a space between "Release note" and the open parenthesis, in the commit message.

- I'd recommend adding memory monitoring with that buffer meant to grow unbounded over time.

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/acceptance/testdata/psql/test-psql.sh, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26345#-LE8_MhFCiw5CdgrGP6r:-LE8_MhH8uIU4AxENbt1:b-uuedli) ([raw file](https://github.com/cockroachdb/cockroach/blob/686c08985f5e0e600078aa4920fdd037cde4f14e/pkg/acceptance/testdata/psql/test-psql.sh#L71)):*
> ```Shell
> 
> # Test that a row larger than 8192 bytes is handled OK. That's when psql splits
> # it into multiple packages.
> ```

s/packages/packets

---

*[pkg/sql/copy.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26345#-LE8_bdb6kwftCEZoesN:-LE8_bdc8O5XvwI5QIxx:b-6vdhm1) ([raw file](https://github.com/cockroachdb/cockroach/blob/686c08985f5e0e600078aa4920fdd037cde4f14e/pkg/sql/copy.go#L57)):*
> ```Go
> 	buf bytes.Buffer
> 	// rows accumulates a batch of rows to be eventually inserted.
> 	rows []*tree.Tuple
> ```

Add memory accounting while you're here. Otherwise a client can DoS a server with this copy junk.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26345#-:-LE8_qYd94U_NeaiLTTP:b-vaan4w)*

**Comment by andreimatei** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/acceptance/testdata/psql/test-psql.sh, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26345#-LE8_MhFCiw5CdgrGP6r:-LEAuhKA-InRGJl2-C-S:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/686c08985f5e0e600078aa4920fdd037cde4f14e/pkg/acceptance/testdata/psql/test-psql.sh#L71)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

s/packages/packets
</blockquote></details>

Done.

---

*[pkg/sql/copy.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26345#-LE8_bdb6kwftCEZoesN:-LEAuciVCUDxDmt8vti7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/686c08985f5e0e600078aa4920fdd037cde4f14e/pkg/sql/copy.go#L57)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Add memory accounting while you're here. Otherwise a client can DoS a server with this copy junk.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26345)*

**Comment by knz** [comment]
thanks for the update, just one detail remaining

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[pkg/sql/copy.go, line 219 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26345#-LEB0pDz0JMLlk7rz2Y-:-LEB0pE-6SwCtvhBDocK:b-63kpeq) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa00a03cae27b35da861b1c5286d8cdcca630ad4/pkg/sql/copy.go#L219)):*
> ```Go
> 	ctx context.Context, data string, evalCtx *tree.EvalContext, final bool,
> ) (retErr error) {
> 	// At the end, adjust the mem accounting to reflect what's left in the buffer.
> ```

that's not how accounts work: you need to call `Resize()`  _before_ actually asking Go's heap. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26345#-:-LEB0z5SCN6QOemBQwjp:b-otmkm8)*

**Comment by andreimatei** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/copy.go, line 219 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26345#-LEB0pDz0JMLlk7rz2Y-:-LEB2PBT7s5w_B480ke1:b-xqva41) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa00a03cae27b35da861b1c5286d8cdcca630ad4/pkg/sql/copy.go#L219)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

that's not how accounts work: you need to call `Resize()`  _before_ actually asking Go's heap. 
</blockquote></details>

I understand how it works.
But we've already "asked Go's heap" - `data` has been already allocated (without accounting) when we read it off the network.  And since one copy of data is unaccounted, I think we might as well have two unaccounted copies. So the mantra is that we're accounting for memory used in between packets and we consider the scratch space needed for processing one packet as noise. I think that's more honest than putting more accounting before we copy into the buffer.
What do you think?

I've moved to using the buffer's capacity versus the buffer's length in the accounting we do have, however. It seems slightly better...

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26345)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/copy.go, line 219 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26345#-LEB0pDz0JMLlk7rz2Y-:-LEBAtl-8syXi-TGduVq:b3vhxs9) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa00a03cae27b35da861b1c5286d8cdcca630ad4/pkg/sql/copy.go#L219)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I understand how it works.
But we've already "asked Go's heap" - `data` has been already allocated (without accounting) when we read it off the network.  And since one copy of data is unaccounted, I think we might as well have two unaccounted copies. So the mantra is that we're accounting for memory used in between packets and we consider the scratch space needed for processing one packet as noise. I think that's more honest than putting more accounting before we copy into the buffer.
What do you think?

I've moved to using the buffer's capacity versus the buffer's length in the accounting we do have, however. It seems slightly better...
</blockquote></details>

Your explanation merely tells me that we're missing accounting of the `data` buffer in pgwire. This is another problem (which we also need to solve).

Yes the capacity is better but I still think that if we make 2 copies of the data we need to account for both before they are actually allocated.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26345)*

**Comment by andreimatei** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/copy.go, line 219 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26345#-LEB0pDz0JMLlk7rz2Y-:-LEBJTeeE5YLA7MDFf9x:b-6o8uub) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa00a03cae27b35da861b1c5286d8cdcca630ad4/pkg/sql/copy.go#L219)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Your explanation merely tells me that we're missing accounting of the `data` buffer in pgwire. This is another problem (which we also need to solve).

Yes the capacity is better but I still think that if we make 2 copies of the data we need to account for both before they are actually allocated.


</blockquote></details>

well yeah but I'm not sure what needs to be refactored for that to happen exactly...
My vote is we merge this as is and improve elsewhere (cause to be honest I'm not personally particularly interested in doing it). As the code stands now, nothing is more unaccounted then it was before the PR. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26345)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/copy.go, line 219 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26345#-LEB0pDz0JMLlk7rz2Y-:-LEDicc66A90jfnl9fiy:b-vj6q7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa00a03cae27b35da861b1c5286d8cdcca630ad4/pkg/sql/copy.go#L219)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

well yeah but I'm not sure what needs to be refactored for that to happen exactly...
My vote is we merge this as is and improve elsewhere (cause to be honest I'm not personally particularly interested in doing it). As the code stands now, nothing is more unaccounted then it was before the PR. 
</blockquote></details>

Then:

- file an issue and cc me and vivek on it
- add a TODO here
- add a TODO next to the `data` allocations

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26345)*

**Comment by andreimatei** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/copy.go, line 219 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26345#-LEB0pDz0JMLlk7rz2Y-:-LEGUigSBGH_9CMQJUMu:b-w2l2dk) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa00a03cae27b35da861b1c5286d8cdcca630ad4/pkg/sql/copy.go#L219)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Then:

- file an issue and cc me and vivek on it
- add a TODO here
- add a TODO next to the `data` allocations

</blockquote></details>

Filed #26439

Did some changes here to account for the buffer's copy of data - PTAL.
No todos...

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26345)*

**Comment by knz** [comment]
:lgtm: thank you! :sparkling_heart: 

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26345#-:-LEGyGs7Ebo-DhJ1lZQf:bk4s3pb)*

**Pull request merged**
