### PR TITLE
sql: set `plan_cache_mode` default to `auto`

### PR DESCRIPTION
**Pull request by mgartner**
#### ccl: remove CCL check for generic query plans

Release note: None

#### sql: move generic query plan tests out of `pkg/ccl`

Release note: None

#### opt: remove `generic` test option

Now that generic query plans are not gated behind the CCL license check,
opt tests can use the `set` option to alter the `plan_cache_mode`
session setting, rather than the `generic` option. The `generic` option
is no longer supported.

Release note: None

#### sql: set `plan_cache_mode` default to `auto`

Epic: None

Release note (performance improvement): The session setting
`plan_cache_mode` now defaults to `auto`, enabling generic query plans
for some queries.

### CODE REVIEW

**Comment by mgartner** [comment]
No need to review quite yet—I'm expecting the last commit to require a lot of test rewrite which I haven't done yet. We'll see what shakes out in CI.

**Review by yuzefovich — APPROVED** [review]
:tada: :lgtm:

> Reviewed 5 of 11 files at r1, 8 of 8 files at r4, 3 of 3 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135668#-:-OC_FGit8kMQJS9zTzvr:b-kqvd1r)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Review by michae2 — APPROVED** [review]
:lgtm: Nice!

> Reviewed 5 of 11 files at r1, 8 of 8 files at r4, 3 of 3 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135668#-:-OC_ZW9o3NDjt_de_pTy:b-8gk8uj)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
