### PR TITLE
roachtest: make ruby-pg test work on Ubuntu 22.04

### LINKED ISSUE #112109: roachtest: update ruby-pg test for ubunutu 22.04
Ubuntu images for roachtests were upgraded to 22.04 in [#111517](https://github.com/cockroachdb/cockroach/pull/111517). Ruby-pg had new failures when trying to run on 22.04.  Currently, the test is still using the previous Ubuntu image of 20.04 (Focal Fossa) through a cluster.spec override. https://github.com/cockroachdb/cockroach/blob/1f86b1e9c6ef4c5d8cb6656cc432a56a5282124a/pkg/cmd/roachtest/tests/ruby_pg.go#L236

The following issue is preventing us from running this test on Ubuntu 22.04. We need to fix this and remove the above override.

[Ubuntu 22.04 uses OpenSSL 3.0](https://discourse.ubuntu.com/t/jammy-jellyfish-release-notes/24668). The current roachtest version of [ruby-pg v1.3.5, does not support OpenSSL 3.0](https://github.com/ged/ruby-pg/blob/master/History.md#v135-2022-03-31-lars-kanis-larsgreiz-reinsdorfde). This can easily be fixed by upgrading to [ruby-pg v1.4.6 or higher](https://github.com/ged/ruby-pg/blob/master/History.md#v146-2023-02-26-lars-kanis-larsgreiz-reinsdorfde) when the Windows fat binary gem was updated to include OpenSSL 3.0.

However, doing so introduces 100+ new tests, many of which fail. Additionally, test servers are expected to be [instanceable](https://github.com/ged/ruby-pg/commit/816d9c32cbbd22d09a9e2234a91775b34618356c), completely breaking the current ruby-pg-helper.rb file. This helper file needs to be updated, and the failing tests need to be fixed or blocklisted.

Jira issue: CRDB-32238

### PR DESCRIPTION
**Pull request by rafiss**
This required updating the version under test, which led to a few new test failures that we track now.

fixes https://github.com/cockroachdb/cockroach/issues/112109
Release note: None

### CODE REVIEW

**Review by DarrylWong — COMMENTED** [review]
I see that you updated the blocklist but I'm still getting failures when I run this test.

It might be a red herring but `RuntimeError during test setup: Command failed: [/home/ubuntu/cockroach start-single-node --insecure --store=/mnt/data1/ruby-pg/tmp_test_read-only/data --advertise-addr=localhost --sql-addr=localhost:26258]` seems suspicious to me. It shouldn't be trying to create a node at that port since that's the http port created by the `c.Start()` call.

**Comment by rafiss** [comment]
kicked off a run here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13739314?hideProblemsFromDependencies=false&hideTestsFromDependencies=false

**Comment by rafiss** [comment]
That was a red herring; this is ready for another look

**Review by DarrylWong — APPROVED** [review]
LGTM 🥳

**Comment by rafiss** [comment]
tftr

bors r+

**Pull request merged**
