### PR TITLE
bazel: mark metamorphic_test as working in bazel

### LINKED ISSUE #61920: storage: broken tests in Bazel
We are making a lot of progress in the migration from make to Bazel. Before we can complete our migration, we need to make sure that all tests in-tree continue to pass when run inside of the Bazel sandbox. The following tests are broken when run in the Bazel sandbox:

    pkg/storage/metamorphic:metamorphic_test

Please help us by doing the following:

* Reproduce the failure locally; for example, with `bazel test pkg/storage/metamorphic:metamorphic_test`, and consult the test logs to see what went wrong
* Identify the root cause of the failure
* If you are able, repair the failure such that the test passes, and submit a PR removing the `broken_in_bazel` tag from the test (see the linked documentation below)
* If not, take your findings to #bazel in Slack, and we’ll work with you to figure out how we can get the tests working

Helpful documentation:
* [How to ensure your tests can run in the Bazel sandbox (consider starting here!)](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/1553172016/How+to+ensure+your+tests+can+run+in+the+Bazel+sandbox)
* [How to ensure your code builds with Bazel](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/1380090083/How+to+ensure+your+code+builds+with+Bazel)
* [A user's guide to Bazel](https://docs.bazel.build/versions/4.0.0/guide.html)

### PR DESCRIPTION
**Pull request by rickystewart**
Resolves #61920.

Release note: None

### CODE REVIEW

**Comment by rickystewart** [comment]
Bilal -- one clarifying question here. What I'm seeing is that when I run this test on my Macbook, the test passes, but it takes a very long time (~500s). Running the same test in a Docker container succeeds far faster (~15s). Is this expected, or has something gone wrong?

**Comment by itsbilal** [comment]
I'll have to look into this as the magnitude is pretty large, but anything that stresses the disk is significantly slower on macs for all sorts of OS-related reasons so this is expected. Some of it is likely just the different SyncingFile implementation.

**Review by itsbilal — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62747#-:-MX2fRuYCUtfvCKjg2ui:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rickystewart)

**Pull request merged**
