### PR TITLE
roachtest: more multi-region TPC-C fine tuning

### LINKED ISSUE #67777: roachtest: tpcc/multiregion/survive=region/chaos=true failed
roachtest.tpcc/multiregion/survive=region/chaos=true [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3194875&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3194875&tab=artifacts#/tpcc/multiregion/survive=region/chaos=true) on master @ [efb4fd2b406cd47b505b4f1a1d5700fc79841469](https://github.com/cockroachdb/cockroach/commits/efb4fd2b406cd47b505b4f1a1d5700fc79841469):

```
		  |   | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.(*tpccChaosEventProcessor).checkUptime
		  |   | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/drt.go:56
		  |   | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.(*tpccChaosEventProcessor).listen.func1
		  |   | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/drt.go:282
		  |   | runtime.goexit
		  |   | 	/usr/local/go/src/runtime/asm_amd64.s:1371
		  | Wraps: (4) expected <=10 errors, found from 0.000000, to 20.000000
		  | Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.leafError
		Wraps: (4) secondary error attachment
		  | error at from 2021-07-19T20:21:34Z, to 2021-07-19T20:26:14Z on metric workload_tpcc_newOrder_error_total{instance="34.139.117.73:2112"}: expected <=10 errors, found from 0.000000, to 16.000000
		  | (1) attached stack trace
		  |   -- stack trace:
		  |   | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.(*tpccChaosEventProcessor).checkMetrics
		  |   | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/drt.go:207
		  |   | [...repeated from below...]
		  | Wraps: (2) error at from 2021-07-19T20:21:34Z, to 2021-07-19T20:26:14Z on metric workload_tpcc_newOrder_error_total{instance="34.139.117.73:2112"}
		  | Wraps: (3) attached stack trace
		  |   -- stack trace:
		  |   | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.(*tpccChaosEventProcessor).checkUptime.func2
		  |   | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/drt.go:78
		  |   | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.(*tpccChaosEventProcessor).checkMetrics
		  |   | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/drt.go:206
		  |   | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.(*tpccChaosEventProcessor).checkUptime
		  |   | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/drt.go:56
		  |   | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.(*tpccChaosEventProcessor).listen.func1
		  |   | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/drt.go:282
		  |   | runtime.goexit
		  |   | 	/usr/local/go/src/runtime/asm_amd64.s:1371
		  | Wraps: (4) expected <=10 errors, found from 0.000000, to 16.000000
		  | Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.leafError
		Wraps: (5) attached stack trace
		  -- stack trace:
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.(*tpccChaosEventProcessor).checkMetrics
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/drt.go:207
		  | [...repeated from below...]
		Wraps: (6) error at from 2021-07-19T20:21:34Z, to 2021-07-19T20:26:14Z on metric workload_tpcc_newOrder_error_total{instance="34.139.117.73:2121"}
		Wraps: (7) attached stack trace
		  -- stack trace:
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.(*tpccChaosEventProcessor).checkUptime.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/drt.go:78
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.(*tpccChaosEventProcessor).checkMetrics
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/drt.go:206
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.(*tpccChaosEventProcessor).checkUptime
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/drt.go:56
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.(*tpccChaosEventProcessor).listen.func1
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/drt.go:282
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1371
		Wraps: (8) expected <=10 errors, found from 0.000000, to 14.000000
		Error types: (1) *secondary.withSecondaryError (2) *secondary.withSecondaryError (3) *secondary.withSecondaryError (4) *secondary.withSecondaryError (5) *withstack.withStack (6) *errutil.withPrefix (7) *withstack.withStack (8) *errutil.leafError
```
<details><summary>Reproduce</summary>
<p>
<p>To reproduce, try:

```bash
# From https://go.crdb.dev/p/roachstress, perhaps edited lightly.
caffeinate ./roachstress.sh tpcc/multiregion/survive=region/chaos=true
```
</p>
</p>
</details>
/cc @cockroachdb/multiregion
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*tpcc/multiregion/survive=region/chaos=true.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by otan**
Resolves #67777

See individual commits for details.

### CODE REVIEW

**Review by ajstorm — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67835)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/cmd/roachtest/tests/tpcc.go, line 504 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67835#-Mf5c1Bb6AxgpPh6rHNs:-Mf5c1Bb6AxgpPh6rHNt:b-f2kb4g) ([raw file](https://github.com/cockroachdb/cockroach/blob/2073adcd1b17347021d2b2cff75888f82e459082/pkg/cmd/roachtest/tests/tpcc.go#L504)):*
> ```Go
> 			// We see a slow trickle of errors after a server has been force shutdown due
> 			// to queries before the shutdown not fully completing.
> 			// This is of the form: `ERROR: inbox communication error: rpc error: code = Canceled desc = context canceled (SQLSTATE 58C01)`
> ```

Nit: Long line.
___
*[pkg/cmd/roachtest/tests/tpcc.go, line 506 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67835#-Mf5cAHxCOzk0V5L6LXa:-Mf5cAHxCOzk0V5L6LXb:b7y2k29) ([raw file](https://github.com/cockroachdb/cockroach/blob/2073adcd1b17347021d2b2cff75888f82e459082/pkg/cmd/roachtest/tests/tpcc.go#L506)):*
> ```Go
> 			// This is of the form: `ERROR: inbox communication error: rpc error: code = Canceled desc = context canceled (SQLSTATE 58C01)`
> 			// Setting this allows some errors to occur.
> 			maxErrorsDuringUptime int
> ```

This seems like a big hammer.  Are we able to either limit this to errors detected after a server has been shutdown (i.e. ensure that it's 0 at the time of the shutdown)?  Or look for the precise error we're expecting?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67835)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/cmd/roachtest/tests/tpcc.go, line 506 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67835#-Mf5cAHxCOzk0V5L6LXa:-Mf68Eac9GT7Rv2YF7bF:b-mwa1r) ([raw file](https://github.com/cockroachdb/cockroach/blob/2073adcd1b17347021d2b2cff75888f82e459082/pkg/cmd/roachtest/tests/tpcc.go#L506)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

This seems like a big hammer.  Are we able to either limit this to errors detected after a server has been shutdown (i.e. ensure that it's 0 at the time of the shutdown)?  Or look for the precise error we're expecting?
</blockquote></details>

not easily - also worth noting that this can also be a genuine error during *success* which i would argue is very bad (we have 0 slack on errors during success right now). i've manually had to audit each error and check it is one that is valid - this one is the majority atm.

i don't have a great solution for this at the moment. unfortunately most DRTs i've usually run are quite manual, and the automated ones usually have tolerances (e.g. 99.7% available even after downtime).

**Review by ajstorm — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67835)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/cmd/roachtest/tests/tpcc.go, line 506 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67835#-Mf5cAHxCOzk0V5L6LXa:-Mf80Z1K9uWdaqiTmLZw:bz1rj2g) ([raw file](https://github.com/cockroachdb/cockroach/blob/2073adcd1b17347021d2b2cff75888f82e459082/pkg/cmd/roachtest/tests/tpcc.go#L506)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

not easily - also worth noting that this can also be a genuine error during *success* which i would argue is very bad (we have 0 slack on errors during success right now). i've manually had to audit each error and check it is one that is valid - this one is the majority atm.

i don't have a great solution for this at the moment. unfortunately most DRTs i've usually run are quite manual, and the automated ones usually have tolerances (e.g. 99.7% available even after downtime). 
</blockquote></details>

I could see how this would be painful.  Doesn't need to be in this PR, but I'd imagine this code would benefit from some "allowable errors" list, which we check errors against.  Cancelled context seems acceptable, data corruption, less so.

Does it make sense to open an issue to track this?

**Comment by otan** [comment]
issue filed (#67908)

bors r=ajstorm

**Pull request merged**
