### PR TITLE
storage: implement iterator to interleave separated intents

### PR DESCRIPTION
**Pull request by sumeerbhola**
intentInterleavingIter allows for both physically separate
and physically interleaved intents, and makes both look
like interleaved intents. It uses two underlying iterators,
a MVCCIterator and an EngineIterator, that are kept
synchronized.

Informs #41720

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
The test will fail until pebble is bumped in https://github.com/cockroachdb/cockroach/pull/56534

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56535#-:-MLoqxG594F8NtkfkcOw:bvaualj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @nvanbenschoten, and @petermattis)

**Review by petermattis — COMMENTED** [review]
Mostly just skimmed this as I'm expecting @nvanbenschoten to scrutinize the logic. Are you planning to add microbenchmarks to compare the performance of iterating over separated vs interleaved intents? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56535#-:-MLrkVGq5VuHTw4xNt4V:bjb7wy3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @nvanbenschoten, @petermattis, and @sumeerbhola)

___
*[pkg/storage/intent_interleaving_iter.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56535#-MLrhOhY3cSlIU9pOMAM:-MLrhOhZ3xhzqPdpgppB:b2bbwah) ([raw file](https://github.com/cockroachdb/cockroach/blob/f56915cd4029e94c1be8d92df5538bf57b6e4e17/pkg/storage/intent_interleaving_iter.go#L25)):*
> ```Go
> // intentInterleavingIter makes separated intents appear as interleaved. It
> // assumes that there can also be intents that are physically interleaved.
> // However, for a particular roachpb.Key there will be at most intent, either
> ```

Nit: Something is off with the grammar of `at most intent`. Perhaps `at most one intent`.

**Review by sumeerbhola — COMMENTED** [review]
> Are you planning to add microbenchmarks to compare the performance of iterating over separated vs interleaved intents?

I've added a TODO for microbenchmarks. Both the randomized test and microbenchmarks will happen in follow-up PRs, but before I integrate this with existing code.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56535#-:-MLsGQgU80Apd5plaYKi:bku3wqt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @nvanbenschoten)

___
*[pkg/storage/intent_interleaving_iter.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56535#-MLrhOhY3cSlIU9pOMAM:-MLsHO6C0uxReH3jJ55J:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f56915cd4029e94c1be8d92df5538bf57b6e4e17/pkg/storage/intent_interleaving_iter.go#L25)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: Something is off with the grammar of `at most intent`. Perhaps `at most one intent`.
</blockquote></details>

Done

**Review by nvb — COMMENTED** [review]
> Reviewed 6 of 8 files at r1, 3 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56535)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @sumeerbhola)

___
*[pkg/keys/keys.go, line 401 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56535#-MLs96m-1VVcQQWKVUYn:-MLs96m-1VVcQQWKVUYo:b-dcrk3q) ([raw file](https://github.com/cockroachdb/cockroach/blob/f56915cd4029e94c1be8d92df5538bf57b6e4e17/pkg/keys/keys.go#L401)):*
> ```Go
> // For a scan [start, end) the corresponding lock table scan is
> // [LTSK(start), LTSK(end)).
> func LockTableSingleKey(key roachpb.Key, buf []byte) (roachpb.Key, []byte) {
> ```

We should note somewhere in the function's comment that `buf` is replaced and not appended to.
___
*[pkg/storage/intent_interleaving_iter.go, line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56535#-MLstwCb6pYirD6qDU9u:-MLstwCb6pYirD6qDU9v:bm2eikt) ([raw file](https://github.com/cockroachdb/cockroach/blob/9748ba19f3b18045b7ecf00a2642c8be1ea41b07/pkg/storage/intent_interleaving_iter.go#L30)):*
> ```Go
> // Additionally, the implementation assumes that the only single key locks
> // in the lock table key space are intents.
> type intentInterleavingIter struct {
> ```

What is the plan for this type once all intents have been moved into the lockTable? It seems like we will still need it for limited scans that do not scan the lockTable ahead of time (https://github.com/cockroachdb/cockroach/issues/49973), but will other operations that have already scanned the lockTable still use it? Also, do we plan to simplify the implementation once all intents are segregated?
___
*[pkg/storage/intent_interleaving_iter.go, line 44 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56535#-MLt5qekDZPCAuGx3wrG:-MLt5qekDZPCAuGx3wrH:bsejdkr) ([raw file](https://github.com/cockroachdb/cockroach/blob/9748ba19f3b18045b7ecf00a2642c8be1ea41b07/pkg/storage/intent_interleaving_iter.go#L44)):*
> ```Go
> 	// state of the intentKey overrides that state.
> 	intentKey roachpb.Key
> 	// - cmp output of (intentKey, current iter key) when both are non-nil.
> ```

Could you expand this out a bit more to discuss whether this is taking timestamps into account or not? For instance, what should this be if the intentIter is positioned on an intent and the iter is positioned on the same key but at a committed version instead of the provisional version? I _think_ it will be `0` after reading some of this file. Or is that not possible because we'll move `intentIter` forward first?

EDIT: I was able to resolve these questions after reading the rest of the code in depth, but it could be made easier to understand.

Maybe this brings up a more general point about being more clear about how the `MVCCIterator` and the `EngineIterator` interleave. It might be helpful to think of this as an interleaving between two `MVCCIterator`s, where the first is `iter` and the second is a transformation of `intentIter` that a) maps the EngineKey to another EngineKey using `DecodeLockTableSingleKey` and b) maps the EngineKey to an MVCCKey by giving it a timestamp of 0. If we didn't care about performance, I bet you could even define this type a little more abstractly like that:
```
 intentInterleavingIter = iter_merge(iter, intentIter.map(|k| DecodeLockTableSingleKey(k)).map(|k| MVCCKey{Key: k, Timestamp: 0}))
```
___
*[pkg/storage/intent_interleaving_iter.go, line 71 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56535#-MLsz2oU8gjO7nTOmx_0:-MLsz2oU8gjO7nTOmx_1:bjcz9ic) ([raw file](https://github.com/cockroachdb/cockroach/blob/9748ba19f3b18045b7ecf00a2642c8be1ea41b07/pkg/storage/intent_interleaving_iter.go#L71)):*
> ```Go
> 	var intentKeyBuf []byte
> 	if opts.LowerBound != nil {
> 		intentOpts.LowerBound, intentKeyBuf = keys.LockTableSingleKey(opts.LowerBound, nil)
> ```

Isn't this going to alias `intentKeyBuf` and `intentOpts.LowerBound` to the same memory? Is that not unsafe? Can the buffers passed in an `IterOptions` be reused after a call to `NewEngineIterator`?
___
*[pkg/storage/intent_interleaving_iter.go, line 105 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56535#-MLszfKJ75mAGzvVJ6P_:-MLszfKJ75mAGzvVJ6Pa:bfvp4x6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9748ba19f3b18045b7ecf00a2642c8be1ea41b07/pkg/storage/intent_interleaving_iter.go#L105)):*
> ```Go
> 		// or using SetUpperBound.
> 		if !i.hasUpperBound && keys.IsLocal(key.Key) && !keys.IsLocalStoreKey(key.Key) {
> 			i.iter.SetUpperBound(keys.LocalRangeLockTablePrefix)
> ```

Should we set `i.hasUpperBound = true` after this? Or should we be calling `i.SetUpperBound`?
___
*[pkg/storage/intent_interleaving_iter.go, line 109 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56535#-MLt1MzZ4zTvqaNsdYji:-MLt1MzZ4zTvqaNsdYjj:bgtc0us) ([raw file](https://github.com/cockroachdb/cockroach/blob/9748ba19f3b18045b7ecf00a2642c8be1ea41b07/pkg/storage/intent_interleaving_iter.go#L109)):*
> ```Go
> 	}
> 	var intentSeekKey roachpb.Key
> 	if key.Timestamp == (hlc.Timestamp{}) {
> ```

`.IsEmpty()`. We just got rid of all of these in https://github.com/cockroachdb/cockroach/pull/56373/commits/4fa8a38298e110f1849ea9e315e74d53a7da5c5a.
___
*[pkg/storage/intent_interleaving_iter.go, line 118 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56535#-MLt28LW-xkABzNoifxw:-MLt28LW-xkABzNoifxx:b-54gg0t) ([raw file](https://github.com/cockroachdb/cockroach/blob/9748ba19f3b18045b7ecf00a2642c8be1ea41b07/pkg/storage/intent_interleaving_iter.go#L118)):*
> ```Go
> 		// Else seeking to a particular version and using prefix iteration,
> 		// so don't expect to ever see the intent.
> 		i.intentKey = nil
> ```

nit: consider adding `intentSeekKey = nil`. I know it's not needed, but it makes the intention and the interaction with the next block more clear.
___
*[pkg/storage/intent_interleaving_iter.go, line 155 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56535#-MLt2rEXD6oEVWaV4Jlt:-MLt2rEXD6oEVWaV4Jlu:b-z825dq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9748ba19f3b18045b7ecf00a2642c8be1ea41b07/pkg/storage/intent_interleaving_iter.go#L155)):*
> ```Go
> func (i *intentInterleavingIter) tryDecodeLockKey(valid bool) error {
> 	if !valid {
> 		i.intentKey = nil
> ```

Consider mentioning why this doesn't set `i.valid = false` in a comment. It took me a second to understand how this interacts with `computePos`.
___
*[pkg/storage/intent_interleaving_iter.go, line 206 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56535#-MLt4zKH1eD5XSgxI4Pt:-MLt4zKH1eD5XSgxI4Pu:ba52o11) ([raw file](https://github.com/cockroachdb/cockroach/blob/9748ba19f3b18045b7ecf00a2642c8be1ea41b07/pkg/storage/intent_interleaving_iter.go#L206)):*
> ```Go
> 			// preceding key or exhausted. So step it forward. It will now point to
> 			// a key that is the same as the intent key since an intent always has a
> 			// corresponding provisional value.
> ```

" and provisional values must have a higher timestamp than any committed value on a key". We've actually had bugs with this in the past, so it's worth considering where we're making assumptions about this. We should be able to assume it, but it's probably best to call the assumption out explicitly.
___
*[pkg/storage/intent_interleaving_iter.go, line 337 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56535#-MLt9Sul1_uMxzTsbdin:-MLt9Sul1_uMxzTsbdio:b-253e2m) ([raw file](https://github.com/cockroachdb/cockroach/blob/9748ba19f3b18045b7ecf00a2642c8be1ea41b07/pkg/storage/intent_interleaving_iter.go#L337)):*
> ```Go
> 
> func (i *intentInterleavingIter) isCurAtIntentIter() bool {
> 	return (i.dir > 0 && i.intentCmp <= 0) || (i.dir < 0 && i.intentCmp > 0)
> ```

This might be a good place for a comment and maybe even a diagram demonstrating how the two iterators move and why this is the case. If you're feeling inspired.
___
*[pkg/storage/intent_interleaving_iter.go, line 360 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56535#-MLt9sM36Z51nxzVleVg:-MLt9sM4CEL5rnMpPK1C:b-23o7rz) ([raw file](https://github.com/cockroachdb/cockroach/blob/9748ba19f3b18045b7ecf00a2642c8be1ea41b07/pkg/storage/intent_interleaving_iter.go#L360)):*
> ```Go
> func (i *intentInterleavingIter) Key() MVCCKey {
> 	unsafeKey := i.UnsafeKey()
> 	return MVCCKey{Key: append(roachpb.Key(nil), unsafeKey.Key...), Timestamp: unsafeKey.Timestamp}
> ```

nit: `append(roachpb.Key(nil), unsafeKey.Key...` isn't quite the same as `keyCopy := make([]byte, len(key.Key)); copy(keyCopy, key.Key)`. One reason is that the `append` method leaves some capacity on the slice. In the past, I believe we measured it to be a bit slower. I'd lean towards doing exactly what we do in `pebbleIterator.Key`.

Also, do we think there might be cases where an Iterator implementation provides a more efficient `Key` impl? In other words, would it be worth deferring to the underlying MVCCIterator implementation when `!i.isCurAtIntentIter()`.
___
*[pkg/storage/intent_interleaving_iter.go, line 392 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56535#-MLtB-xx3t2qQSK27Q5t:-MLtB-xyEo10JbuQ33Po:b-uqkfzc) ([raw file](https://github.com/cockroachdb/cockroach/blob/9748ba19f3b18045b7ecf00a2642c8be1ea41b07/pkg/storage/intent_interleaving_iter.go#L392)):*
> ```Go
> 			return
> 		} else {
> 			intentSeekKey, i.intentKeyBuf = keys.LockTableSingleKey(key.Key.Next(), i.intentKeyBuf)
> ```

Could you give this a small comment that calls out why `Next` is required. It took me a minute to figure that out.
___
*[pkg/storage/testdata/ii_iter, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56535#-MLuFAnc70nEsNz4bH8h:-MLuFAnc70nEsNz4bH8i:bds3i29) ([raw file](https://github.com/cockroachdb/cockroach/blob/9748ba19f3b18045b7ecf00a2642c8be1ea41b07/pkg/storage/testdata/ii_iter#L1)):*
> ```
> # Both separated and interleaved intents, and one inline meta.
> ```

Nice test!
___
*[pkg/storage/testdata/ii_iter, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56535#-MLuF05CCT_f9AQO9_mo:-MLuF05CCT_f9AQO9_mp:bvsa5sd) ([raw file](https://github.com/cockroachdb/cockroach/blob/9748ba19f3b18045b7ecf00a2642c8be1ea41b07/pkg/storage/testdata/ii_iter#L47)):*
> ```
> next
> ----
> cmd: seek-ge meta k=a ts=20 txn=1
> ```

nit: this would be a little easier to follow if it more clearly separated the cmd from the output, and if it included the arguments to cmds that take them, like `seek-ge` and `seek-lt`.
___
*[pkg/storage/testdata/ii_iter, line 123 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56535#-MLuFdJkDizfOXK5IhjE:-MLuFdJkDizfOXK5IhjF:b8re19l) ([raw file](https://github.com/cockroachdb/cockroach/blob/9748ba19f3b18045b7ecf00a2642c8be1ea41b07/pkg/storage/testdata/ii_iter#L123)):*
> ```
> cmd: next .
> 
> # Prefix iteration and NextKey. There is no guarantee on what we will
> ```

Does this combination make sense to support? Does the "no guarantee" part mean that its behavior is undefined?
___
*[pkg/storage/testdata/ii_iter, line 149 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56535#-MLuFzcX7g2E3tMlpZE3:-MLuFzcY0Qd6CL6JzWsM:b-5zy9o4) ([raw file](https://github.com/cockroachdb/cockroach/blob/9748ba19f3b18045b7ecf00a2642c8be1ea41b07/pkg/storage/testdata/ii_iter#L149)):*
> ```
> seek-ge k=a ts=25
> next
> next
> ```

Should this also include a case like `seek-ge k=a ts=5` where we immediately seek to the next key?

**Review by sumeerbhola — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56535#-:-MLyhQhCAxLXCD5d9Vmp:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @nvanbenschoten, and @sumeerbhola)

___
*[pkg/keys/keys.go, line 401 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56535#-MLs96m-1VVcQQWKVUYn:-MLwlOmFE_wPTNIlcm8y:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f56915cd4029e94c1be8d92df5538bf57b6e4e17/pkg/keys/keys.go#L401)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We should note somewhere in the function's comment that `buf` is replaced and not appended to.
</blockquote></details>

Done
___
*[pkg/storage/intent_interleaving_iter.go, line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56535#-MLstwCb6pYirD6qDU9u:-MLwlTYV1ZgG51YSznjf:b-rn9xnz) ([raw file](https://github.com/cockroachdb/cockroach/blob/9748ba19f3b18045b7ecf00a2642c8be1ea41b07/pkg/storage/intent_interleaving_iter.go#L30)):*
> What is the plan for this type once all intents have been moved into the lockTable? It seems like we will still need it for limited scans that do not scan the lockTable ahead of time (#49973), but will other operations that have already scanned the lockTable still use it?

Yes, that is correct -- it will continue to exist for use in limited scans only.

> Also, do we plan to simplify the implementation once all intents are segregated?

Yes, I think there will be (minor) simplifications.
___
*[pkg/storage/intent_interleaving_iter.go, line 44 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56535#-MLt5qekDZPCAuGx3wrG:-MLx3KgYEY0-vc_FMq7w:bmnnmj0) ([raw file](https://github.com/cockroachdb/cockroach/blob/9748ba19f3b18045b7ecf00a2642c8be1ea41b07/pkg/storage/intent_interleaving_iter.go#L44)):*
> EDIT: I was able to resolve these questions after reading the rest of the code in depth, but it could be made easier to understand.

I've added a struct-level long comment and another comment here.

> It might be helpful to think of this as an interleaving between two MVCCIterators, where the first is iter and the second is a transformation of intentIter that a) maps the EngineKey to another EngineKey using DecodeLockTableSingleKey and b) maps the EngineKey to an MVCCKey by giving it a timestamp of 0. If we didn't care about performance, ...

This is now included in the struct-level comment.
___
*[pkg/storage/intent_interleaving_iter.go, line 71 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56535#-MLsz2oU8gjO7nTOmx_0:-MLx5dk7EpPxkpFX5qod:b-p04caw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9748ba19f3b18045b7ecf00a2642c8be1ea41b07/pkg/storage/intent_interleaving_iter.go#L71)):*
> Isn't this going to alias intentKeyBuf and intentOpts.LowerBound to the same memory? Is that not unsafe? Can the buffers passed in an IterOptions be reused after a call to NewEngineIterator?

Yes to aliasing. No to it being unsafe. Yes, we don't document the copying behavior in `pebbleIterator` -- I have now added comments in `engine.go` to this effect.
I will probably need to further optimize this when integrating, since (a) iterator reuse should include reusing already allocated memory for `intentInterleavingIter`, (b) this intentKeyBuf reuse is quite half-hearted -- I am inclined towards having 2 bufs.
___
*[pkg/storage/intent_interleaving_iter.go, line 105 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56535#-MLszfKJ75mAGzvVJ6P_:-MLx7b608LrOL6Q0IKL7:b2gjnj2) ([raw file](https://github.com/cockroachdb/cockroach/blob/9748ba19f3b18045b7ecf00a2642c8be1ea41b07/pkg/storage/intent_interleaving_iter.go#L105)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we set `i.hasUpperBound = true` after this? Or should we be calling `i.SetUpperBound`?
</blockquote></details>

I added a comment. This is not a user-specified upper-bound, so we want to keep changing it on every call to `SeekGE`, which is why we don't set `hasUpperBound=true`.

I've also added some test cases with local keys, to exercise this code.
___
*[pkg/storage/intent_interleaving_iter.go, line 109 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56535#-MLt1MzZ4zTvqaNsdYji:-MLx7sNwAckpZS-ay3XY:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/9748ba19f3b18045b7ecf00a2642c8be1ea41b07/pkg/storage/intent_interleaving_iter.go#L109)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`.IsEmpty()`. We just got rid of all of these in https://github.com/cockroachdb/cockroach/pull/56373/commits/4fa8a38298e110f1849ea9e315e74d53a7da5c5a.
</blockquote></details>

Done
___
*[pkg/storage/intent_interleaving_iter.go, line 118 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56535#-MLt28LW-xkABzNoifxw:-MLxI3w55NZumcgcc2sm:b-cv2i0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/9748ba19f3b18045b7ecf00a2642c8be1ea41b07/pkg/storage/intent_interleaving_iter.go#L118)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: consider adding `intentSeekKey = nil`. I know it's not needed, but it makes the intention and the interaction with the next block more clear.
</blockquote></details>

I added a comment instead -- I prefer a code style where we don't set things to their existing value, and instead assert an invariant. Since this invariant is very local (`intentSeekKey` was declared a few lines before) I figured it wasn't worth asserting. Let me know if you think otherwise.
___
*[pkg/storage/intent_interleaving_iter.go, line 155 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56535#-MLt2rEXD6oEVWaV4Jlt:-MLxK2Fm3YJZiGMwGz0S:b-pujzqq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9748ba19f3b18045b7ecf00a2642c8be1ea41b07/pkg/storage/intent_interleaving_iter.go#L155)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Consider mentioning why this doesn't set `i.valid = false` in a comment. It took me a second to understand how this interacts with `computePos`.
</blockquote></details>

Done. I didn't mention `computePos` here since the caller sometimes uses `computePos` and sometimes does something more specialized (by relying on an invariant that avoids a key comparison).
___
*[pkg/storage/intent_interleaving_iter.go, line 206 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56535#-MLt4zKH1eD5XSgxI4Pt:-MLxKxJ4EP66TunnV-ue:bs9d3p8) ([raw file](https://github.com/cockroachdb/cockroach/blob/9748ba19f3b18045b7ecf00a2642c8be1ea41b07/pkg/storage/intent_interleaving_iter.go#L206)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

" and provisional values must have a higher timestamp than any committed value on a key". We've actually had bugs with this in the past, so it's worth considering where we're making assumptions about this. We should be able to assume it, but it's probably best to call the assumption out explicitly.
</blockquote></details>

I've added a longer comment, which mentions that we don't actually rely on it pointing to the provisional value. But we do rely on it pointing to some version of the same key.
And I audited all the other places in the code that rely on some invariant outside the scope of this iterator and added comments for them. 
___
*[pkg/storage/intent_interleaving_iter.go, line 337 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56535#-MLt9Sul1_uMxzTsbdin:-MLyQtq-5jLLkznibIxE:bld4y2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/9748ba19f3b18045b7ecf00a2642c8be1ea41b07/pkg/storage/intent_interleaving_iter.go#L337)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This might be a good place for a comment and maybe even a diagram demonstrating how the two iterators move and why this is the case. If you're feeling inspired.
</blockquote></details>

I've added a long comment. It also resulted in a couple of code changes elsewhere.
___
*[pkg/storage/intent_interleaving_iter.go, line 360 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56535#-MLt9sM36Z51nxzVleVg:-MLyRnS61zFBdCqf6_g5:b-264e4y) ([raw file](https://github.com/cockroachdb/cockroach/blob/9748ba19f3b18045b7ecf00a2642c8be1ea41b07/pkg/storage/intent_interleaving_iter.go#L360)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: `append(roachpb.Key(nil), unsafeKey.Key...` isn't quite the same as `keyCopy := make([]byte, len(key.Key)); copy(keyCopy, key.Key)`. One reason is that the `append` method leaves some capacity on the slice. In the past, I believe we measured it to be a bit slower. I'd lean towards doing exactly what we do in `pebbleIterator.Key`.

Also, do we think there might be cases where an Iterator implementation provides a more efficient `Key` impl? In other words, would it be worth deferring to the underlying MVCCIterator implementation when `!i.isCurAtIntentIter()`.
</blockquote></details>

Good point. I've duplicated the logic from `pebbleIterator.Key`.
___
*[pkg/storage/intent_interleaving_iter.go, line 392 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56535#-MLtB-xx3t2qQSK27Q5t:-MLySSgiB-5fxfc16kdx:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/9748ba19f3b18045b7ecf00a2642c8be1ea41b07/pkg/storage/intent_interleaving_iter.go#L392)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Could you give this a small comment that calls out why `Next` is required. It took me a minute to figure that out.
</blockquote></details>

Done
___
*[pkg/storage/testdata/ii_iter, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56535#-MLuF05CCT_f9AQO9_mo:-MLyUyTB4-4cY8-8lvx2:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/9748ba19f3b18045b7ecf00a2642c8be1ea41b07/pkg/storage/testdata/ii_iter#L47)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: this would be a little easier to follow if it more clearly separated the cmd from the output, and if it included the arguments to cmds that take them, like `seek-ge` and `seek-lt`.
</blockquote></details>

Fixed.
___
*[pkg/storage/testdata/ii_iter, line 123 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56535#-MLuFdJkDizfOXK5IhjE:-MLyVLVd0DiTFVaRhF4A:bvfdbuc) ([raw file](https://github.com/cockroachdb/cockroach/blob/9748ba19f3b18045b7ecf00a2642c8be1ea41b07/pkg/storage/testdata/ii_iter#L123)):*
> Does this combination make sense to support? Does the "no guarantee" part mean that its behavior is undefined?

Yes, it is undefined on what happens after we are done with the key that `SeekGE` was called with. I've adjusted the comment. We don't "support" it, but we don't prevent the user from continuing to iterate either.
___
*[pkg/storage/testdata/ii_iter, line 149 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56535#-MLuFzcX7g2E3tMlpZE3:-MLyXIAaEB5CnTzab5vL:b-qw199g) ([raw file](https://github.com/cockroachdb/cockroach/blob/9748ba19f3b18045b7ecf00a2642c8be1ea41b07/pkg/storage/testdata/ii_iter#L149)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should this also include a case like `seek-ge k=a ts=5` where we immediately seek to the next key?
</blockquote></details>

Good point. Added

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56535#-:-MLyolSn-YOAQAhLE2N5:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal)

**Comment by sumeerbhola** [comment]
TFTR!
I've moved one error test case out into separate `testdata` files for race off and on, since the error is caught at different points of the iteration.

**Pull request merged**
