### PR TITLE
server: Emit telemetry counter matching engine type

### LINKED ISSUE #42223: storage/engine: add telemetry about which storage engine is being used
Title says it all. We need to add telemetry about which storage engine (`pebble` or `rocksdb`) a node is using so that we can track adoption.

### PR DESCRIPTION
**Pull request by itsbilal**
This change increments a telemetry counter upon startup that
denotes engine type (pebble, rocksdb), and whether this is an
initial-boot or a node restart with an initialized store directory.

Fixes #42223.

Release note: None.

### CODE REVIEW

**Comment by itsbilal** [comment]
Was relatively unsure about who to tag for review on this - feel free to review if you're not marked as a reviewer (and don't be pressured to if you are but don't want to review).

**Review by petermattis — COMMENTED** [review]
Glad to see this done, though I'm unsure on the telemetry stuff. Another possible reviewer is @dt. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42700#-:-LuJ58-i274-3C1fDPDb:bmtftdl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @knz, and @petermattis)

___
*[pkg/server/server.go, line 1696 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42700#-LuJ4pJG6rv_kYn0qkzY:-LuJ4pJG6rv_kYn0qkzZ:by4we6d) ([raw file](https://github.com/cockroachdb/cockroach/blob/e74b3a87a35f095a490bba5a246cb4464db682a7/pkg/server/server.go#L1696)):*
> ```Go
> 	} else {
> 		nodeStartCounter += "restart"
> 	}
> ```

I'm not familiar with the naming conventions on telemetry. I'll leave it to @knz to review that.

Do we need to distinguish initial-boot from restart here? Won't other parts of telemetry be able to determine when a node was created vs restarted? Perhaps this is another question for @knz.

**Review by itsbilal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42700)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/server/server.go, line 1696 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42700#-LuJ4pJG6rv_kYn0qkzY:-LuJSLsi2FM2ngPrKF1m:b-xo38vc) ([raw file](https://github.com/cockroachdb/cockroach/blob/e74b3a87a35f095a490bba5a246cb4464db682a7/pkg/server/server.go#L1696)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm not familiar with the naming conventions on telemetry. I'll leave it to @knz to review that.

Do we need to distinguish initial-boot from restart here? Won't other parts of telemetry be able to determine when a node was created vs restarted? Perhaps this is another question for @knz.
</blockquote></details>

My rationale behind this was to be able to filter out the noise from repeated restarts somehow. If there's no point in separating the two, I can remove that suffix.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42700)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @knz)

___
*[pkg/server/server.go, line 1696 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42700#-LuJ4pJG6rv_kYn0qkzY:-LuJXHuaACLYQYsOdMvu:b-85ihhp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e74b3a87a35f095a490bba5a246cb4464db682a7/pkg/server/server.go#L1696)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

My rationale behind this was to be able to filter out the noise from repeated restarts somehow. If there's no point in separating the two, I can remove that suffix.
</blockquote></details>

Ack. I'm just not sure if it is necessary. There is likely already an ability to only count a metric like this once per instance or once per cluster. @knz or @dt will have to chime in.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42700)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/server/server.go, line 1696 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42700#-LuJ4pJG6rv_kYn0qkzY:-LuJXrgD7dxoJ1qt5u5G:bylx7e2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e74b3a87a35f095a490bba5a246cb4464db682a7/pkg/server/server.go#L1696)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Ack. I'm just not sure if it is necessary. There is likely already an ability to only count a metric like this once per instance or once per cluster. @knz or @dt will have to chime in.
</blockquote></details>

There's nothing persisted in telemetry, so I think the approach here makes sense.

I initially asked that all telemetry keys be literal string constants, ideally passed directly to `telemetry.Count()` -- partly so that we could easily enumerate the set of telemetry keys, but more importantly to make it trivial to prove they were safe w.r.t leaking user data. 

For example, you may currently know that `StorageEngine.String()` can currently only return one of two constants, but a) that isn't always _obvious_ or b) if someone else working on config stuff later opted to do something like embed a path in or other option in that string, this could silently start leaking stuff we really don't want to collect. 

My personal preference is to have a conditional or switch/case with string literals in each branch that may overlap / be repetitive, rather than programmatically constructing a string, but this rule hasn't really been followed -- even by me! -- and I'm not going to start insisting on following it now if you prefer this approach.

**Comment by itsbilal** [comment]
Addressed the point on `StorageEngine.String()`  anyway - even if it's not a commonly followed convention. PTAL!

**Review by dt — APPROVED** [review]

**Comment by itsbilal** [comment]
TFTR!

bors r+

**Pull request merged**
