### PR TITLE
roachtest: pass missing parameter

### LINKED ISSUE #29665: roachtest: drop/tpcc/w=100,nodes=9 failed on master
SHA: https://github.com/cockroachdb/cockroach/commits/acc8f8337524c7654259f0540780e7237503001d

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stressrace instead of stress and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
make stress TESTS=drop/tpcc/w=100,nodes=9 PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-stderr=false -maxtime 20m -timeout 10m'
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=888557&tab=buildLog

```
	test.go:498,drop.go:72,drop.go:105,cluster.go:1206,errgroup.go:58: pq: no value provided for placeholder: $1
	test.go:498,cluster.go:1227,drop.go:159,drop.go:184: Goexit() was called

```

### PR DESCRIPTION
**Pull request by tbg**
Fixes #29665.

Release note: None

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm:

Huh. I thought we had already fixed this, but I guess not.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30373#-:-LMh_OWdBaS0ZeFNJyFh:b-p3isk3)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by knz** [comment]
that's not sufficient. I'll push the rest of the fix to your branch

**Comment by knz** [comment]
done

LGTM

**Comment by tschottdorf** [comment]
Thanks @knz!

bors r=petermattis,knz

**Pull request merged**
