### PR TITLE
[WIP] util/log,diagnostics: new TELEMETRY channel, send reports to logging

### PR DESCRIPTION
**Pull request by knz**
Informs #63815.

See discussion in #63815: we would like to leverage the logging
subsystem, in particular network logging, as a new way
to channel diagnostic reports.

This work will operate in multiple phases. This commit is only
about the first phase:

- creating a new logging channel TELEMETRY
- ensuring the channel is not redirected to files by default.
- copies the diagnostic report to the TELEMETRY channel,
  *in addition* of sending it to `register.cockroachdb.com`
  as previously.

Later work will aim to further this project by subsuming
the HTTP reporting to `register.cockroachdb.com` entirely
under logging, e.g. via a HTTP sink (see issue #63980).

Release note (cli change): CockroachDB now also sends
telemetry diagnostics to the new logging channel TELEMETRY.
By default, this channel is not connected to file output,
so there is no observable difference in behavior
for default deployments. To redirect the diagnostic
output, one can define a new sink that captures
this channel.

For example, to see diagnostics reports on the standard
error, one can use: `--log='sinks: {stderr: {channels: TELEMETRY, filter: INFO}}'`

### CODE REVIEW

**Review by logston — COMMENTED** [review]
I don't have the CRDB context give this a thumbs up or not but I like what I see! Thanks for this work @knz. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64218#-:-MZEmmev4rTVxOeOaCL8:b-nc15mp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @thtruo and @vilamurugu)

**Comment by thtruo** [comment]
cc @JuanLeon1

**Review by thtruo — COMMENTED** [review]
This looks good to me, Raphael! I like the inclusion of having diagnostic usage reports being sent as distinct logs through the TELEMETRY channel. 

> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64218#-:-MaifhkC35bTeeStF5Kf:b-evwsqj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @vilamurugu)

**Comment by thtruo** [comment]
@knz One question came up in a conversation with @logston around the Serverless case. Will diagnostic usage reports be sent per tenant or per node? 
If they are per tenant, we may want to consider doing some sampling to reduce the volume of data (and cost) going through telemetry into the storage bucket

**Comment by knz** [comment]
> Will diagnostic usage reports be sent per tenant or per node?

We want both, for different purposes:

- To analyze our customer's behavior PM wants data from SQL tenants, not the KV nodes underneath. So the most data we'll collect will be per tenant.
- Separately, I think we want KV nodes to also telemetry that reflects CRDB usage *by the CC control plane*, because we'll want to utilize this telemetry in crdb engineering to optimize CC's performance overall (especially in the KV team)

> If they are per tenant, we may want to consider doing some sampling to reduce the volume of data (and cost) going through telemetry into the storage bucket

You're preaching to the choir. That's exactly why we absolutely must use sampling for query logging.

The other events of interest (feature counters, time to first query etc) are infrequent enough.

**Comment by thtruo** [comment]
cc @andy-kimball for awareness as this is one of the prerequisite pieces towards enabling the logging telemetry pipeline to support product analytics for CC Serverless

**Comment by knz** [comment]
superseded by #66427

**Pull request closed without merging**
