### PR TITLE
cloud/azure: Fix azure schemes

### PR DESCRIPTION
**Pull request by benbardin**
Part of: https://cockroachlabs.atlassian.net/browse/CRDB-31120

Release note (bug fix): Fixes azure schemes in storage, kms and external conns.

### CODE REVIEW

**Comment by adityamaru** [comment]
The change LGTM but I think we should add a few tests so that if this breaks in the future we have something that fails?

**Review by adityamaru — APPROVED** [review]
Thanks for picking this up, as discussed offline it'd be useful to either add a few lines to the integration tests or just smoke test e2e since CDC also registers `azure` schemes but with their own custom validator.

**Comment by benbardin** [comment]
Done, how's this look?

**Review by adityamaru — APPROVED** [review]
🚀

**Comment by adityamaru** [comment]
@benbardin apologies I should've pointed this out earlier. @mdlinville indicated that it would help to flesh out the release note so that the appropriate changes can be made in the docs across releases.

**Comment by mdlinville** [comment]
> @benbardin apologies I should've pointed this out earlier. @mdlinville indicated that it would help to flesh out the release note so that the appropriate changes can be made in the docs across releases.

We synced offline and came up with a good release note. :)

**Comment by benbardin** [comment]
Yes, thanks Matt! I also added appropriate variants of the notes to the backported versions.

**Pull request merged**
