### PR TITLE
cli/zip: include all system tables by default

### LINKED ISSUE #81303: cli/zip: system.migrations is not included in zip
**Describe the problem**

The system table `system.migrations` is not included.
Arguably, we probably want all tables from database `system` except for a few special tables. For example `system.users` should be excluded.

**To Reproduce**

`debug zip`

**Expected behavior**

moar `system` tables included

### PR DESCRIPTION
**Pull request by knz**
Fixes #81303.

This makes the code use a deny-list (opt out) instead of an allow-list.

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81306)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @knz)

___
*[`pkg/cli/testdata/zip/partial1` line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81306#-N2CwMwC6gzjkNL_pf-a:-N2CwMwC6gzjkNL_pf-b:b-pccxo0) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dea40d07d3b1f853b41575640b52e835909059f/pkg/cli/testdata/zip/partial1#L61)):*
> ```
> [cluster] retrieving SQL data for system.sql_instances... writing output: debug/system.sql_instances.txt... done
> [cluster] retrieving SQL data for system.sqlliveness... writing output: debug/system.sqlliveness.txt... done
> [cluster] retrieving SQL data for system.statement_bundle_chunks... writing output: debug/system.statement_bundle_chunks.txt... done
> ```

should we skip this one? It can be big and it's a pain to use without tooling that we don't have.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81306)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[`pkg/cli/testdata/zip/partial1` line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81306#-N2CwMwC6gzjkNL_pf-a:-N2CxiwTAp6gqHsSiSd7:bb7ohn6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dea40d07d3b1f853b41575640b52e835909059f/pkg/cli/testdata/zip/partial1#L61)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

should we skip this one? It can be big and it's a pain to use without tooling that we don't have.
</blockquote></details>

sgtm

**Review by ajwerner — COMMENTED** [review]
One more round of exclusions then :lgtm: 

I am sort of worried that new observability tables are going to be added and we won't notice that they get huge in the field. I know we can exclude them, but it'll hurt. Another approach might be to enumerate all of them explicitly and have them either included or excluded with a reason, and then, in a test, read the set of tables and make sure all of the tables are either included or excluded. 

> Reviewed 2 of 9 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81306#-:-N2D1XC49PSpWhKw7YoE:bmx3fai)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/cli/testdata/zip/testzip_tenant` line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81306#-N2D1sL94DHSJsEkxGjB:-N2D1sL94DHSJsEkxGjC:bf4mhqq) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4052f7f4ac3148b09c7b0d3757a7e2831a1598d/pkg/cli/testdata/zip/testzip_tenant#L78)):*
> ```
> [cluster] retrieving SQL data for system.statement_diagnostics... writing output: debug/system.statement_diagnostics.txt... done
> [cluster] retrieving SQL data for system.statement_diagnostics_requests... writing output: debug/system.statement_diagnostics_requests.txt... done
> [cluster] retrieving SQL data for system.statement_statistics... writing output: debug/system.statement_statistics.txt... done
> ```

this one can be gigantic
___
*[`pkg/cli/testdata/zip/testzip_tenant` line 80 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81306#-N2D1uhB38OxvmrS4vEC:-N2D1uhB38OxvmrS4vED:bk6y9l3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4052f7f4ac3148b09c7b0d3757a7e2831a1598d/pkg/cli/testdata/zip/testzip_tenant#L80)):*
> ```
> [cluster] retrieving SQL data for system.statement_statistics... writing output: debug/system.statement_statistics.txt... done
> [cluster] retrieving SQL data for system.table_statistics... writing output: debug/system.table_statistics.txt... done
> [cluster] retrieving SQL data for system.transaction_statistics... writing output: debug/system.transaction_statistics.txt... done
> ```

this one also can be gigantic
___
*[`pkg/cli/testdata/zip/testzip_tenant` line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81306#-N2D1xx79nu9VqyxzfTE:-N2D1xx79nu9VqyxzfTF:b5db6bj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4052f7f4ac3148b09c7b0d3757a7e2831a1598d/pkg/cli/testdata/zip/testzip_tenant#L81)):*
> ```
> [cluster] retrieving SQL data for system.table_statistics... writing output: debug/system.table_statistics.txt... done
> [cluster] retrieving SQL data for system.transaction_statistics... writing output: debug/system.transaction_statistics.txt... done
> [cluster] retrieving SQL data for system.zones... writing output: debug/system.zones.txt... done
> ```

this one we already have in a generally easier to read format.

**Review by knz — COMMENTED** [review]
> Another approach might be to enumerate all of them explicitly and have them either included or excluded with a reason, and then, in a test, read the set of tables and make sure all of the tables are either included or excluded.

This will not help with "tables are going to be added and we won't notice that they get huge in the field".
The mechanism we have for this will be `--timeout`.

Meanwhile, I'm not keen on explicit lists of any kind: I'd like a `zip` tool to start automatically capturing tables when run against a server in version N+1.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81306#-:-N2DZvla83CtNX9Zc1EU:b-wpg1s7)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[`pkg/cli/testdata/zip/testzip_tenant` line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81306#-N2D1sL94DHSJsEkxGjB:-N2D_8D_5vtP8Xq3ULi7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4052f7f4ac3148b09c7b0d3757a7e2831a1598d/pkg/cli/testdata/zip/testzip_tenant#L78)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

this one can be gigantic
</blockquote></details>

Done.
___
*[`pkg/cli/testdata/zip/testzip_tenant` line 80 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81306#-N2D1uhB38OxvmrS4vEC:-N2D_8eN9OZBLMMobD3R:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4052f7f4ac3148b09c7b0d3757a7e2831a1598d/pkg/cli/testdata/zip/testzip_tenant#L80)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

this one also can be gigantic
</blockquote></details>

Done.
___
*[`pkg/cli/testdata/zip/testzip_tenant` line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81306#-N2D1xx79nu9VqyxzfTE:-N2D_9nX40NZ3kYpr3Ps:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f4052f7f4ac3148b09c7b0d3757a7e2831a1598d/pkg/cli/testdata/zip/testzip_tenant#L81)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

this one we already have in a generally easier to read format. 
</blockquote></details>

Done.

**Review by rimadeodhar — APPROVED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81306)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)

**Comment by knz** [comment]
TFYR!

bors r=rimadeodhar,ajwerner

**Comment by knz** [comment]
@rimadeodhar can i let you investigate the backport error

**Comment by knz** [comment]
okay, so @rimadeodhar you're off the hook for this one. I'll investigate how important this backport is.

**Comment by Santamaura** [comment]
@knz was this important enough to be backported to 21.2?

**Pull request merged**
