### PR TITLE
release-19.1: storage: fix possible raft log panic after fsync error

### PR DESCRIPTION
**Pull request by ajkr**
Backport 1/1 commits from #37102.

/cc @cockroachdb/release

---

Detected with #36989 applied by running
`./bin/roachtest run --local '^system-crash/sync-errors=true$'`.
With some slight modification to that test's constants it could repro
errors like this within a minute:

```
panic: tocommit(375) is out of range [lastIndex(374)]. Was the raft log corrupted, truncated, or lost?
```

Debugging showed `DBSyncWAL` can be called even after a sync failure.
I guess if it returns success any time after it fails it will ack
writes that aren't recoverable in WAL. They aren't recoverable because
RocksDB stops recovery upon hitting the offset corresponding to the
lost write (typically there should be a corruption there). Meanwhile,
there are still successfully synced writes at later offsets in the
file.

The fix is simple. If `DBSyncWAL` returns an error once, keep track of
that error and return it for all future writes.

Release note (bug fix): Fixed possible panic while recovering from a WAL
on which a sync operation failed.

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
Per @tbg's comment on #37102, please add a release note. I should have noticed that omission. 

@tbg re a unit test: it seems like a test of this change would need to be very targeted. I was thinking that #36989 is a more holistic test for problems in this area. Not sure if you are aware of that. I should have mentioned that during the review of #37102. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37109#-:-LdJhT0A7y8MfzEFtRRx:byssjvx)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by tbg** [comment]
Ack, thanks for clarifying.

**Review by bdarnell — APPROVED** [review]
LGTM, although I'd hold this back for 19.1.1 instead of getting it in to this week's release.

**Comment by tbg** [comment]
@bdarnell good to merge now right?

**Comment by bdarnell** [comment]
Yes, go ahead.

**Pull request merged**
