### PR TITLE
storage: skip TestWedgedReplicaDetection on test short

### PR DESCRIPTION
**Pull request by andreimatei**
Takes 10s. I've opened #33654 asking for an investigation.

Release note: None

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
Peter can I merge this?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33655#-:-LY3DidG7wN0HHjX4SLU:b-hys3d3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @petermattis)

**Comment by petermattis** [comment]
@andreimatei I seem to have dropped the ball here. Do we still need this PR?

**Comment by andreimatei** [comment]
Still ten seconds, so give a stamp to a brother.

**Review by petermattis — APPROVED** [review]
LGTM

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33655#-:-LrQsClo1O_imZcl8995:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Pull request merged**
