### PR TITLE
tenant: use single connManager instance on tenant start

### PR DESCRIPTION
**Pull request by dhartunian**
Previously, two different connManager instances were created via
`netutil.MakeServer` in the tenant startup process. This change unifies
the two to match the way dedicated/kv nodes use the `connManager`
instance and moves the initialization out of the `RunAsyncTask` that
starts the HTTP server. Additionally, the initialization of the HTTP mux
has also been lifted out of the async job since it's required for the
`connManager` instance.

Additionally, the use of the `workersCtx` is cleaned up and we now
initialize a single context that's used for all the async jobs that are
triggered in the tenant cluster startup.

Release note: None

### CODE REVIEW

**Review by knz — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70276)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

**Comment by dhartunian** [comment]
@knz this PR was sitting around so I just updated against your changes. I am now using your recently added `background` context for the async tasks instead of `workerCtx`.

**Review by knz — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70276)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

**Comment by dhartunian** [comment]
TFTR!

bors r=knz

**Pull request merged**
