### PR TITLE
sql: fix a data race in TestInternalExecAppNameInitialization

### LINKED ISSUE #33268: tests: race in TestInternalExecAppNameInitialization
Found in https://teamcity.cockroachdb.com/viewLog.html?buildId=1063526&buildTypeId=Cockroach_UnitTests

```
[14:29:12]
[Maybe stressrace pull request] === RUN   TestInternalExecAppNameInitialization/root_internal_exec
[14:29:12]
[Maybe stressrace pull request] ==================
[14:29:12]
[Maybe stressrace pull request] WARNING: DATA RACE
[14:29:12]
[Maybe stressrace pull request] Write at 0x00c421486cb0 by goroutine 129:
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*ResolvableFunctionReference).Resolve()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/function_name.go:59 +0x328
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*scope).VisitPre()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scope.go:791 +0xacf
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql/sem/tree.WalkExpr()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/walk.go:680 +0x5c
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*scope).walkExprTree()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scope.go:253 +0x7c
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*scope).resolveType()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scope.go:287 +0x56
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).analyzeSelectList()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/project.go:146 +0x3b0
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).analyzeProjectionList()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/project.go:80 +0x2c2
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelectClause()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:581 +0x2dc
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelect()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:527 +0x49e
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmt()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:197 +0x1e3
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:148 +0x1b2
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql.(*planner).makeOptimizerPlan()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:483 +0xd7c
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql.(*planner).optionallyUseOptimizer()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/planner.go:552 +0xde
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:783 +0x22d
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:417 +0x106c
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:98 +0x463
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1141 +0x343d
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql.(*internalExecutorImpl).initConnEx.func1()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:203 +0x7d
[14:29:12]
[Maybe stressrace pull request] 
[14:29:12]
[Maybe stressrace pull request] Previous read at 0x00c421486cb0 by goroutine 248:
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*ResolvableFunctionReference).Format()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/function_name.go:42 +0x3c
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FmtCtx).formatNodeOrHideConstants()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/hide_constants.go:47 +0x75
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FmtCtx).FormatNode()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/format.go:275 +0xb2
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FuncExpr).Format()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/expr.go:1329 +0x1f3
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FmtCtx).formatNodeOrHideConstants()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/hide_constants.go:47 +0x75
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FmtCtx).FormatNode()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/format.go:275 +0xb2
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*SelectExpr).Format()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/select.go:170 +0x84
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FmtCtx).formatNodeOrHideConstants()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/hide_constants.go:47 +0x75
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FmtCtx).FormatNode()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/format.go:275 +0xb2
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*SelectExprs).Format()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/select.go:137 +0x74
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FmtCtx).formatNodeOrHideConstants()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/hide_constants.go:47 +0x75
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FmtCtx).FormatNode()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/format.go:275 +0xb2
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*SelectClause).Format()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/select.go:104 +0x1b1
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FmtCtx).formatNodeOrHideConstants()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/hide_constants.go:47 +0x75
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FmtCtx).FormatNode()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/format.go:275 +0xb2
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*Select).Format()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/select.go:53 +0xbe
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FmtCtx).formatNodeOrHideConstants()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/hide_constants.go:47 +0x75
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FmtCtx).FormatNode()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/format.go:275 +0xb2
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql/sem/tree.AsStringWithFlags()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/format.go:305 +0x65
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql/sem/tree.AsString()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/format.go:311 +0x4b
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*Select).String()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/stmt.go:855 +0x44
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).serialize()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2042 +0x373
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql.(*SessionRegistry).SerializeAll()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/exec_util.go:905 +0x263
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/server.(*statusServer).ListLocalSessions()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/server/status.go:1359 +0x1a7
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql.glob..func39()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/crdb_internal.go:740 +0x10f
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql.virtualDefEntry.getPlanInfo.func1()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:258 +0x6bc
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql.(*execFactory).ConstructVirtualScan.func1()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt_exec_factory.go:129 +0xac
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql.(*delayedNode).startExec()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/delayed.go:62 +0xa7
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql.startExec.func2()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:720 +0xd3
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal.func1()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:134 +0x99
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:578 +0x583
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:101 +0xfb
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql.walkPlan()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:65 +0x1c1
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql.startExec()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:725 +0x152
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Start()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:140 +0x198
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:803 +0x8a
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Run()
[14:29:12]
[Maybe stressrace pull request]       <autogenerated>:1 +0x61
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).StartSync()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:618 +0x329
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:261 +0xb4a
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:805 +0x297
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1005 +0x4aa
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:847 +0xee8
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:417 +0x106c
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:98 +0x463
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1141 +0x343d
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql.(*internalExecutorImpl).initConnEx.func1()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:203 +0x7d
[14:29:12]
[Maybe stressrace pull request] 
[14:29:12]
[Maybe stressrace pull request] Goroutine 129 (running) created at:
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql.(*internalExecutorImpl).initConnEx()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:202 +0x56d
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql.(*internalExecutorImpl).execInternal()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:489 +0x766
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql.(*internalExecutorImpl).queryInternal()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:239 +0x141
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).Query()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:223 +0x10e
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql_test.testInternalExecutorAppNameInitialization.func1()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/internal_test.go:208 +0xe3
[14:29:12]
[Maybe stressrace pull request] 
[14:29:12]
[Maybe stressrace pull request] Goroutine 248 (running) created at:
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql.(*internalExecutorImpl).initConnEx()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:202 +0x56d
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql.(*internalExecutorImpl).execInternal()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:489 +0x766
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql.(*internalExecutorImpl).queryInternal()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:239 +0x141
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).Query()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:223 +0x10e
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql_test.testInternalExecutorAppNameInitialization()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/internal_test.go:253 +0x402
[14:29:12]
[Maybe stressrace pull request]   github.com/cockroachdb/cockroach/pkg/sql_test.TestInternalExecAppNameInitialization.func1()
[14:29:12]
[Maybe stressrace pull request]       /go/src/github.com/cockroachdb/cockroach/pkg/sql/internal_test.go:156 +0x97
[14:29:12]
[Maybe stressrace pull request]   testing.tRunner()
[14:29:12]
[Maybe stressrace pull request]       /usr/local/go/src/testing/testing.go:777 +0x16d
[14:29:12]
[Maybe stressrace pull request] ==================
[14:29:12]
[Maybe stressrace pull request] 
[14:29:12]
[Maybe stressrace pull request] 
[14:29:12]
[Maybe stressrace pull request] ERROR: exit status 66

```

### PR DESCRIPTION
**Pull request by knz**
Fixes #33268.

Release note: None

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
:lgtm: whoops!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33392#-:-LUpk0Sr9vCK56n_dwBB:bnj9jy)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by knz** [comment]
aw man data races are hard :sweat_smile:

**Pull request merged**
