### PR TITLE
backupccl: only restore system tables included in backup

### PR DESCRIPTION
**Pull request by pbardea**
Before this commit, we would assume that all of the system tables that
we wanted to restore were present in the backup. However, this is not
necessarily true since system tables can be added between releases.

Release note (bug fix): Previously cluster backups taken from before
20.2 could not be restored in 20.2 clusters, with an error message about
failing to restore a system table. This is now fixed.

### CODE REVIEW

**Comment by pbardea** [comment]
This is an initial stab at it, but wanted to solicit any feedback early on. Adding x-version testing now for cluster restore.

**Review by miretskiy — APPROVED** [review]
Looks reasonable to me on the first pass.  Let's see the tests. :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55685#-:-MK0bbnW0G8VSiL1ipju:bufheyv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @pbardea)

___
*[pkg/ccl/backupccl/restore_old_versions_test.go, line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55685#-MK0bQN365nbQXCdOMEA:-MK0bQN365nbQXCdOMEB:b-dxlu97) ([raw file](https://github.com/cockroachdb/cockroach/blob/d93370f74744c36028200e62a61067d7be4900d2/pkg/ccl/backupccl/restore_old_versions_test.go#L107)):*
> ```Go
> 		)
> 
> 		//
> ```

extra comment?

**Comment by pbardea** [comment]
Update: pushed the test, but now it looks like DROP DATABASE jobs are hanging as soon as we restore any system table data from the test backup. Investigating.

**Review by dt — APPROVED** [review]

**Comment by pbardea** [comment]
TFTRs!
bors r=dt

**Pull request merged**
