### PR TITLE
Miscellaneous logging improvements

### PR DESCRIPTION
**Pull request by knz**
The main visible changes here are:

- (most important) `make acceptance` now capture all generated temp files, including temp files and thus non-redirected log files, in the artifact directory.
- `--log-dir=""` can now disable output to files as advertised 
- TestLogic puts non-essential log events to files.
- Acceptance tests put non-essential log events to files.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12662)

### CODE REVIEW

**Comment by jordanlewis** [comment]
:lgtm_strong:

---

Reviewed 1 of 2 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 3 of 3 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 3 of 3 files at r8, 25 of 25 files at r9, 3 of 3 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12662#-:-K_a9LM7wQcvhVUc4i41:b-jbsf8z)*

**Comment by tamird** [comment]
Reviewed 1 of 2 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 3 of 3 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 3 of 3 files at r8.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/cli/start.go, line 279 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12662#-K_aBG1CeZckNzR0te4W:-K_aBG1CeZckNzR0te4X:b-zae6y5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebcd2f7d3268c135457a8d5e2e4b369c46ee795d/pkg/cli/start.go#L279)):*
> ```Go
> 	pf := cockroachCmd.PersistentFlags()
> 	f := pf.Lookup(logflags.LogDirName)
> 	if !log.DirSet() && !f.Changed {
> ```

what if `f.Changed` but the value is non-empty?

---

*[pkg/sql/logic_test.go, line 370 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/12662#-K_aC83QlRtis9TvTIpm:-K_aC83RrwrCMInF4spH:b-6186qt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7460eb1428d90831f1b660a317dcced5f9ee2743/pkg/sql/logic_test.go#L370)):*
> ```Go
> 
> 	// logScope binds the lifetime of the log files to this test.
> 	logScope log.TestLogScope
> ```

ah I see, this is why you exported LogScope. I think you should combine those two commits, but also extract TestLogScope into its own package that both log_test and sql_test can depend on - then you won't need `tShim`.

---

*[pkg/sql/logic_test.go, line 397 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/12662#-K_aCOFc1LMXXYBpVDEh:-K_aCOFc1LMXXYBpVDEi:b-tjsyvn) ([raw file](https://github.com/cockroachdb/cockroach/blob/7460eb1428d90831f1b660a317dcced5f9ee2743/pkg/sql/logic_test.go#L397)):*
> ```Go
> // out emits a message both on stdout and the log files if
> // verbose is set.
> func (t *logicTest) out(format string, args ...interface{}) {
> ```

`outf`

---

*[pkg/util/log/test_log_scope.go, line 34 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/12662#-K_aBX6BsGZNv_bSB1tb:-K_aBX6BsGZNv_bSB1tc:b1ggtt4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a880218f31035515c6e24f892f55898ccdee43f/pkg/util/log/test_log_scope.go#L34)):*
> ```Go
> type TestLogScope string
> 
> // tShim is the part of testing.T used by TestLogScope.
> ```

This commit doesn't include any rationale - why did you need to export this stuff?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12662)*

**Comment by knz** [comment]
Hopefully fixes #12654.

**Comment by knz** [comment]
Review status: 0 of 37 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/cli/start.go, line 279 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12662#-K_aBG1CeZckNzR0te4W:-K_amcn9qjcACbMfBGxG:blsydi1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebcd2f7d3268c135457a8d5e2e4b369c46ee795d/pkg/cli/start.go#L279)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

what if `f.Changed` but the value is non-empty?
</blockquote></details>

If the value is non-empty then log.DirSet() returns true.

---

*[pkg/sql/logic_test.go, line 370 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/12662#-K_aC83QlRtis9TvTIpm:-K_amiacieIGu0zNX5LH:bonycdy) ([raw file](https://github.com/cockroachdb/cockroach/blob/7460eb1428d90831f1b660a317dcced5f9ee2743/pkg/sql/logic_test.go#L370)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

ah I see, this is why you exported LogScope. I think you should combine those two commits, but also extract TestLogScope into its own package that both log_test and sql_test can depend on - then you won't need `tShim`.
</blockquote></details>

There is no `log_test` package currently. The tests in `clog_test.go` which would use the new package `logscope` would need to be extracted in their own package as well to avoid circular dependencies. I have tried doing that, and a large portion of the internal interface of the `log` package need to be exported to support these tests! (the diff has grown larger than 500 changed lines and 15 structs/functions exported before I threw the towel). I think that this loss of encapsulation is not worth the refactoring. You are free to follow-up in a separate PR :smile_cat: 

I did combine the two subsequent commits though as you suggested.

---

*[pkg/sql/logic_test.go, line 397 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/12662#-K_aCOFc1LMXXYBpVDEh:-K_cqxEQkN0aowLkfJZW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7460eb1428d90831f1b660a317dcced5f9ee2743/pkg/sql/logic_test.go#L397)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

`outf`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12662)*

**Comment by tamird** [comment]
Reviewed 1 of 3 files at r5, 37 of 38 files at r11, 2 of 2 files at r13, 2 of 2 files at r14, 1 of 1 files at r15, 1 of 1 files at r16, 4 of 4 files at r17, 1 of 5 files at r19.
Review status: 10 of 40 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/logic_test.go, line 370 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/12662#-K_aC83QlRtis9TvTIpm:-K_dP6Y5-HNpq977OZyx:bir1qng) ([raw file](https://github.com/cockroachdb/cockroach/blob/7460eb1428d90831f1b660a317dcced5f9ee2743/pkg/sql/logic_test.go#L370)):*
> The tests in clog_test.go which would use the new package logscope would need to be extracted in their own package as well to avoid circular dependencies.

Not true - if you can make them `package log_test` (without moving them) then you don't have a circular dependency.

Ah, I guess that's what you tried.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12662)*

**Comment by RaduBerinde** [comment]
Just noticed this: `test_log_scope.go:81: test log files left over in: /tmp/TestLogic028915605`
Nice!! :+1:

**Comment by andreimatei** [comment]
Review status: 0 of 43 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/util/log/trace_test.go, line 95 at r26](https://reviewable.io:443/reviews/cockroachdb/cockroach/12662#-Kmi37uFDqXyeqdHugDs:-Kmi37uGkRaQbFoU6y26:b-88na16) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2951555820d29dcbc5ad962915ed1168ab3ab85/pkg/util/log/trace_test.go#L95)):*
> ```Go
> 	// The test below merely cares about observing events in traces.
> 	// Do not pollute the test's stderr with them.
> 	logging.stderrThreshold = Severity_FATAL
> ```

I believe this is funky. First of all, this is an atomic, and it has a setter. Second, I think it should be restored when the test is done. Third, I think modifying that global is generally horrible because... it's a global (think parallel tests).

I'm curious what motivated this change exactly. What did we want to keep out of stderr? If I run with `TESTFLAGS=-v`, I want all logs in stderr, right? And if I run without that, no logs go to stderr regardless of their level and this threshold, right?
And also it's unclear to me what log statements in this test are affected by this statement. As far as I can see, there's only one logging statement (as opposed to tracing events): `VEvent(ctxWithSpan, logging.verbosity.get()+1, "test2")`. Is that the target? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12662)*

**Comment by knz** [comment]
Review status: 0 of 43 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/util/log/trace_test.go, line 95 at r26](https://reviewable.io:443/reviews/cockroachdb/cockroach/12662#-Kmi37uFDqXyeqdHugDs:-Kmi6UmrH3KKEReWEkCg:b-movhqj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2951555820d29dcbc5ad962915ed1168ab3ab85/pkg/util/log/trace_test.go#L95)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I believe this is funky. First of all, this is an atomic, and it has a setter. Second, I think it should be restored when the test is done. Third, I think modifying that global is generally horrible because... it's a global (think parallel tests).

I'm curious what motivated this change exactly. What did we want to keep out of stderr? If I run with `TESTFLAGS=-v`, I want all logs in stderr, right? And if I run without that, no logs go to stderr regardless of their level and this threshold, right?
And also it's unclear to me what log statements in this test are affected by this statement. As far as I can see, there's only one logging statement (as opposed to tracing events): `VEvent(ctxWithSpan, logging.verbosity.get()+1, "test2")`. Is that the target? 
</blockquote></details>

Thank you for taking the time to review this, albeit late.

Since the PR is already merged it makes it hard(er) to have a discussion and iterate on code. Mind copy-pasting your concern into a new issue and assign it to me? (I would rather you do that in general in the future if you want to comment on closed PRs.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12662)*

**Comment by andreimatei** [comment]
Review status: 0 of 43 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/util/log/trace_test.go, line 95 at r26](https://reviewable.io:443/reviews/cockroachdb/cockroach/12662#-Kmi37uFDqXyeqdHugDs:-Kmi9iYOoa_HsPTHvwco:b-uln1y2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2951555820d29dcbc5ad962915ed1168ab3ab85/pkg/util/log/trace_test.go#L95)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Thank you for taking the time to review this, albeit late.

Since the PR is already merged it makes it hard(er) to have a discussion and iterate on code. Mind copy-pasting your concern into a new issue and assign it to me? (I would rather you do that in general in the future if you want to comment on closed PRs.)
</blockquote></details>

Filed #16551

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12662)*

**Pull request merged**
