### PR TITLE
acceptance: terrafarm cleanups

### PR DESCRIPTION
**Pull request by cuongdo**
**acceptance/terraform: sync with beta cluster cfg**
This brings the terrafarm clusters to  the beta cluster config for both
CockroachDB (notably 2 GiB cache size) and block_writer / photos
parameters.

**acceptance: clean up allocator vs. terrafarm flags**
Originally, the allocator tests were using a different Terraform config
than the other remote acceptance tests. This required unnaturally
putting certain flags (e.g. the one that lets you pass in a custom
`cockroach` binary) as allocator test flags.

This change allows any remote test using a `terrafarm.Farmer` to 
use these useful flags -- particularly our continuous load tests.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8472)

### CODE REVIEW

**Comment by cuongdo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[acceptance/terraform/supervisor.conf.tpl, line 39 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8472#-KOu_mX7A5y2eOHpsDkP:-KOuaBD76qYm3enSQhpD:b-2b0455) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccf4cedd1e6dcd55666579d61193dff9f2fd0fa4/acceptance/terraform/supervisor.conf.tpl#L39)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> `--benchmark-name`?
</details>
It's a way to pass in the name that should be used in the benchmark output upon the exit of `photos` and `block_writer`. For example, if `benchmark_name` is `BenchmarkBlockWriter6h`, the benchmark output could look like this:

```
BenchmarkBlockWriter6h      104320      191734.5 ns/op
```

This name will be used to collate results of the daily runs to visualize performance over time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8472)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[acceptance/terraform/supervisor.conf.tpl, line 39 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8472#-KOu_mX7A5y2eOHpsDkP:-KOub14CKxJIV513NKvI:b-p0t4g0) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccf4cedd1e6dcd55666579d61193dff9f2fd0fa4/acceptance/terraform/supervisor.conf.tpl#L39)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary>
> It's a way to pass in the name that should be used in the benchmark output upon the exit of `photos` and `block_writer`. For example, if `benchmark_name` is `BenchmarkBlockWriter6h`, the benchmark output could look like this:
> 
> ```
> BenchmarkBlockWriter6h      104320      191734.5 ns/op
> ```
> 
> This name will be used to collate results of the daily runs to visualize performance over time.
</details>
I should have been more verbose. You changed some flags here from a single dash to a double dash, and I was asking if you intended to change this one as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8472)*

**Comment by cuongdo** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[acceptance/terraform/supervisor.conf.tpl, line 39 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8472#-KOu_mX7A5y2eOHpsDkP:-KOucQiuTASMZkynN954:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccf4cedd1e6dcd55666579d61193dff9f2fd0fa4/acceptance/terraform/supervisor.conf.tpl#L39)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I should have been more verbose. You changed some flags here from a single dash to a double dash, and I was asking if you intended to change this one as well.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8472)*

**Comment by tamird** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[acceptance/terraform/supervisor.conf.tpl, line 39 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8472#-KOu_mX7A5y2eOHpsDkP:-KOuch1XWYAw8XF_EeB-:bzdqwz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccf4cedd1e6dcd55666579d61193dff9f2fd0fa4/acceptance/terraform/supervisor.conf.tpl#L39)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary>
> Done.
</details>
Thanks. Note that the commit you amended was not the one that contained the other single-dash-to-double-dash changes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8472)*

**Pull request merged**
