### PR TITLE
sql/parser: fix TestParseDatadriven/create_function

### PR DESCRIPTION
**Pull request by renatolabs**
After we tagged master as 23.1 (post #91010), we need to update this file to include the new release number.

Epic: None
Release note: None

### CODE REVIEW

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91287#-:-NG2GOqYCK0d1uk1gzDA:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @renatolabs)

**Review by herkolategan — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91287#-:-NG2GVqVA1LoDoBzfqcP:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @renatolabs)

**Comment by ajwerner** [comment]
The test in question passed CI in the current run. This PR doesn't touch anything else. For the sake of other changes:

bors r+

**Comment by ajwerner** [comment]
Thanks for doing it!

**Comment by ajwerner** [comment]
> `(test_impl.go:291).Fatal: 1: expected version 1000022.2-4, got 1000022.1-34`

**Pull request closed without merging**
