### PR TITLE
Log reference 6

### PR DESCRIPTION
**Pull request by taroface**
Fixes DOC-2957.

Removed a docs `_include` note that was not being properly rendered by the auto-generated doc. 

I think the "experimental" status is already implicit from the `ALTER TABLE ... EXPERIMENTAL_AUDIT SET` command.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78255)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cameronnunez and @taroface)

___
*[pkg/util/log/logconfig/config.go, line 194 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78255#-MzLWp7p1ucO2gxP3nLk:-MzLWp7p1ucO2gxP3nLl:br38ojh) ([raw file](https://github.com/cockroachdb/cockroach/blob/714c95a51f9fe7407fd90b57119a1b9565b1841d/pkg/util/log/logconfig/config.go#L194)):*
> ```Go
> // is `stderr`. Example configuration:
> //
> //		 ~~~
> ```

the spacing seems off here and below (alignment with `sinks`)

**Comment by taroface** [comment]
> 
> the spacing seems off here and below (alignment with sinks)
> ```

A mistake on my part - I had accidentally merged some unwanted commit on my fork. I just reverted this.

**Comment by taroface** [comment]
@knz Let me know if this otherwise looks ok. I'm not sure why the build is failing, however.

**Review by knz — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78255)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @taroface)

___
*[docs/generated/eventlog.md, line 335 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78255#-Mzzlhob2-Wau7_yjgvL:-Mzzlhob2-Wau7_yjgvM:b-u77430) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c62e913b23044f5c4e4501cd1bbd0eb70a9cda3/docs/generated/eventlog.md#L335)):*
> ```Markdown
> marked as audited via `ALTER TABLE ... EXPERIMENTAL_AUDIT SET`.
> 
> {% include {{ page.version.version }}/misc/experimental-warning.md %}
> ```

This is a generated file. You shouldn't be modifying this without also updating the place where this comes from: `pkg/util/log/eventpb/sql_audit_events.proto`

**Comment by taroface** [comment]
> > Reviewed 1 of 1 files at r4, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78255)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @taroface)
> 
> _[docs/generated/eventlog.md, line 335 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/78255#-Mzzlhob2-Wau7_yjgvL:-Mzzlhob2-Wau7_yjgvM:b-u77430) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c62e913b23044f5c4e4501cd1bbd0eb70a9cda3/docs/generated/eventlog.md#L335)):_
> 
> > ```gfm
> > marked as audited via `ALTER TABLE ... EXPERIMENTAL_AUDIT SET`.
> > 
> > {% include {{ page.version.version }}/misc/experimental-warning.md %}
> > ```
> 
> This is a generated file. You shouldn't be modifying this without also updating the place where this comes from: `pkg/util/log/eventpb/sql_audit_events.proto`

Ah thanks for the reminder. Fixed there as well.

**Review by knz — APPROVED** [review]

**Comment by taroface** [comment]
bors r=knz

**Pull request merged**
