### PR TITLE
Add support for pg's SET SESSION CHARACTERISTICS AS TRANSACTION

### LINKED ISSUE #4524: sql: JDBC wants "set session parameters as ..."
Using the same test: https://github.com/cockroachdb/cockroach/issues/3819#issuecomment-171589559

Now fails with:
```
ERROR in (a-test) (QueryExecutorImpl.java:2182)
Uncaught exception, not in assertion.
expected: nil
  actual: org.postgresql.util.PSQLException: ERROR: syntax error at or near "AS"
SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL SERIALIZABLE
                            ^

 at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse (QueryExecutorImpl.java:2182)
    org.postgresql.core.v3.QueryExecutorImpl.processResults (QueryExecutorImpl.java:1911)
    org.postgresql.core.v3.QueryExecutorImpl.execute (QueryExecutorImpl.java:173)
    org.postgresql.jdbc2.AbstractJdbc2Statement.execute (AbstractJdbc2Statement.java:616)
    org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags (AbstractJdbc2Statement.java:452)
    org.postgresql.jdbc2.AbstractJdbc2Connection.execSQLUpdate (AbstractJdbc2Connection.java:399)
    org.postgresql.jdbc2.AbstractJdbc2Connection.setTransactionIsolation (AbstractJdbc2Connection.java:976)
    clojure.java.jdbc$db_transaction_STAR_.doInvoke (jdbc.clj:582)
    clojure.lang.RestFn.invoke (RestFn.java:464)
    jdbc_test.core_test/fn (core_test.clj:16)
```

### PR DESCRIPTION
**Pull request by knz**
This is needed for Clojure JDBC.

Fixes #4524.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4537)

### CODE REVIEW

**Comment by petermattis** [comment]
You should add some test cases to `sql/parser/parser_test.go`.

---

Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/parser/sql.y, line 970 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4537#-KB4LSXOi-4WAeBBqzu-:-KB4LSXOi-4WAeBBqzu0:-1164773245) ([raw file](https://github.com/cockroachdb/cockroach/blob/17c04b929a4249478e376b0e927a418c23a6b1ab/sql/parser/sql.y#L970)):*
I wonder if we need a separate node or if we should just treat this as syntactic sugar for `&Set{Name: "DEFAULT_TRANSACTION_ISOLATION", Values: $6}`. Well, the actual initialization won't be that easy, but the idea will be the same. If you don't do this work now let's file an issue so it doesn't get forgotten.

---

*[sql/parser/stmt.go, line 214 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4537#-KB4K7PMzZYSi-qFxebs:-KB4K7PNfOatYP8XZ2If:1008076433) ([raw file](https://github.com/cockroachdb/cockroach/blob/17c04b929a4249478e376b0e927a418c23a6b1ab/sql/parser/stmt.go#L214)):*
Is that the correct tag to return? (i.e. did you check the postgres sources?)

---

*[sql/set.go, line 92 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4537#-KB4KuFLx-aX0pZhAQOe:-KB4KuFMwQsOEWyLLj1t:-146859069) ([raw file](https://github.com/cockroachdb/cockroach/blob/17c04b929a4249478e376b0e927a418c23a6b1ab/sql/set.go#L92)):*
Actually storing a session level default isolation level is fairly easy. You need to add a field to `Session` (in `session.proto`) and then set it here. When we create transactions in `executor.go` you then have to set the isolation level via a call to `planner.setIsolationLevel`. Should be straightforward. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4537#-:-KB4KO-fiTzTJHWOJWcF:-1765253983)*

**Comment by tamird** [comment]
Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[sql/testdata/txn, line 368 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4537#-KB4ObIiGVIjJhDpLXXp:-KB4ObIiGVIjJhDpLXXq:-113006217) ([raw file](https://github.com/cockroachdb/cockroach/blob/17c04b929a4249478e376b0e927a418c23a6b1ab/sql/testdata/txn#L368)):*
spurious newline

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4537)*

**Comment by knz** [comment]
Done.

---

Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[sql/parser/sql.y, line 970 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4537#-KB4LSXOi-4WAeBBqzu-:-KB5MhOJrJqyldALdyvD:-1847593111) ([raw file](https://github.com/cockroachdb/cockroach/blob/17c04b929a4249478e376b0e927a418c23a6b1ab/sql/parser/sql.y#L970)):*
Filed #4542.

---

*[sql/parser/stmt.go, line 214 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4537#-KB4K7PMzZYSi-qFxebs:-KB5DdUCPdFAKbppPe_z:-1918282032) ([raw file](https://github.com/cockroachdb/cockroach/blob/17c04b929a4249478e376b0e927a418c23a6b1ab/sql/parser/stmt.go#L214)):*
Actually the correct tag is SET, just checked.

---

*[sql/set.go, line 92 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4537#-KB4KuFLx-aX0pZhAQOe:-KB5LTnsxjXpnLQ5winI:-1780408995) ([raw file](https://github.com/cockroachdb/cockroach/blob/17c04b929a4249478e376b0e927a418c23a6b1ab/sql/set.go#L92)):*
Thanks for pointing me to it. I just made a first attempt, please have a look. I am not entirely sure where newly created transactions are initialized however. 

---

*[sql/testdata/txn, line 368 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4537#-KB4ObIiGVIjJhDpLXXp:-KB5L4vLoKL6wg8ZmhyH:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/17c04b929a4249478e376b0e927a418c23a6b1ab/sql/testdata/txn#L368)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4537#-:-KB5CuZZvrv0g7tHivWk:-499146009)*

**Comment by knz** [comment]
So can you suggest where transactions are first populated in a session? I get that BEGIN will set the isolation level if specified in the syntax, and the executor will create transactions on the fly if not yet defined, but I fail to see one single point there planner.session.txn  is being  populated.

**Comment by petermattis** [comment]
Review status: 0 of 11 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/set.go, line 92 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4537#-KB4KuFLx-aX0pZhAQOe:-KB5X2X8DaZer2qIWSLc:1286098366) ([raw file](https://github.com/cockroachdb/cockroach/blob/17c04b929a4249478e376b0e927a418c23a6b1ab/sql/set.go#L92)):*
I don't believe there is a single initialization point for newly created transactions right now. This seems like a good time to add it. Transactions are all created in `executor.go`. Search for `NewTxn` and `db.Txn`. After the transaction is created, I think we want to call `planner.setIsolationLevel` or some new `initTxn` method which does that. 

---

*[sql/testdata/txn, line 370 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4537#-KB5XY71ITgbDTbz03Xa:-KB5XY71ITgbDTbz03Xb:1660128495) ([raw file](https://github.com/cockroachdb/cockroach/blob/53c31959a30a2f07b0851996b4ff501cba5576e1/sql/testdata/txn#L370)):*
You should test that `SHOW DEFAULT_ISOLATION_LEVEL` and `SHOW TRANSACTION ISOLATION LEVEL` both reflect this value. The `SHOW DEFAULT_ISOLATION_LEVEL` will need to be fixed as it is harcoded to `"SERIALIZABLE"` right now.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4537)*

**Comment by knz** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/set.go, line 92 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4537#-KB4KuFLx-aX0pZhAQOe:-KB70Mzh6wtuGYbQAWP8:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/17c04b929a4249478e376b0e927a418c23a6b1ab/sql/set.go#L92)):*
Done.

---

*[sql/testdata/txn, line 370 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4537#-KB5XY71ITgbDTbz03Xa:-KB70QfAILzpn9Xz_ZjY:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/53c31959a30a2f07b0851996b4ff501cba5576e1/sql/testdata/txn#L370)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4537)*

**Comment by knz** [comment]
Also the CI test fails with `sql/parser/keywords.go:35: undefined: CHARACTERISTICS`. I did add the keyword though, `make test` works locally. Why is CI not picking it up?

**Comment by tamird** [comment]
Reviewed 4 of 7 files at r1, 6 of 7 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/session.proto, line 47 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4537#-KB7IZ-M2eMLG4sE7Uuq:-KB7IZ-NT0njcBblM3Du:1232453140) ([raw file](https://github.com/cockroachdb/cockroach/blob/844a0c04f3463de6a29360a2a87524ed071c2f0a/sql/session.proto#L47)):*
i dont think this comment is helpful - it seems likely to rot and duplicates the definition of `roachpb.IsolationType`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4537)*

**Comment by petermattis** [comment]
Not sure about the CI failure. Did you edit `keywords.go` manually, or did you run `make` in `sql/parser`? 

---

Review status: 12 of 14 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[sql/set.go, line 92 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4537#-KB4KuFLx-aX0pZhAQOe:-KB8I51TWS28bzMTEfe4:-1276957098) ([raw file](https://github.com/cockroachdb/cockroach/blob/17c04b929a4249478e376b0e927a418c23a6b1ab/sql/set.go#L92)):*
You missed the call to `db.Txn` which is actually the most important one to address as it is used to create the auto-commit transactions when no explicit transaction is requested by the user.

---

*[sql/show.go, line 48 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4537#-KB8HZO1j2PpRdCc0tQn:-KB8HZO1j2PpRdCc0tQo:-437827937) ([raw file](https://github.com/cockroachdb/cockroach/blob/68250f0f60bae884a0fa95ae33cedae5bae2e9be/sql/show.go#L48)):*
I think this can be: `level := p.session.DefaultIsolationLevel.String()`.

---

*[sql/testdata/txn, line 391 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4537#-KB8IFAUS18RYgMlqqEa:-KB8IFAVga3OANsGCG-P:-805579595) ([raw file](https://github.com/cockroachdb/cockroach/blob/68250f0f60bae884a0fa95ae33cedae5bae2e9be/sql/testdata/txn#L391)):*
You should also test this statement outside of an explicit transaction. I believe the code right now doesn't work correctly (see my other comment about the call to `db.Txn`). 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4537#-:-KB8GrDdfhn6p2QIMmfy:-445737704)*

**Comment by knz** [comment]
I had forgotten tot commit the change to SQL.go, because it was marked as binary... Fixed

---

Review status: 12 of 14 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[sql/testdata/txn, line 391 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4537#-KB8IFAUS18RYgMlqqEa:-KB8Ks8UuyABiLqM1i5C:-2130895749) ([raw file](https://github.com/cockroachdb/cockroach/blob/68250f0f60bae884a0fa95ae33cedae5bae2e9be/sql/testdata/txn#L391)):*
Hum how do you suggest to check for implicit transactions? Does one get created if I enter SHOW TRANSACTION outside of one?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4537#-:-KB8KPkweVLgbVgqVT8-:-805561376)*

**Comment by petermattis** [comment]
Review status: 12 of 14 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/testdata/txn, line 391 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4537#-KB8IFAUS18RYgMlqqEa:-KB8MTDn2Rywlhw9xTPM:1822934234) ([raw file](https://github.com/cockroachdb/cockroach/blob/68250f0f60bae884a0fa95ae33cedae5bae2e9be/sql/testdata/txn#L391)):*
Yes. Any statement that is not inside an explicit transaction is performed inside an implicit one.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4537)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4537)*

**Comment by knz** [comment]
Review status: 10 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/show.go, line 48 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4537#-KB8HZO1j2PpRdCc0tQn:-KB8w93NWZpHQRdD16XL:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/68250f0f60bae884a0fa95ae33cedae5bae2e9be/sql/show.go#L48)):*
Done.

---

*[sql/testdata/txn, line 391 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4537#-KB8IFAUS18RYgMlqqEa:-KB8w7x1n440DV45OCtd:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/68250f0f60bae884a0fa95ae33cedae5bae2e9be/sql/testdata/txn#L391)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4537)*

**Comment by tamird** [comment]
LGTM. I think you can take the "preliminary" out of the commit and PR messages :)

---

Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4537#-:-KB8wyogjqpLV2pxVeHR:-41313622)*

**Comment by knz** [comment]
@tamird @petermattis please help me by telling me precisely what I need to do to make this circleci error go away. Thanks

**Pull request merged**
