### PR TITLE
sql: include stopped monitors into node_memory_monitors

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit changes how we traverse the tree of monitors to not skip any stopped monitors that are reachable from the root. An additional column is included into the vtable which should help us understand monitors leaks if present.

Note that because this vtable only offers single node view (i.e. we don't have `cluster_node_monitors`), debug.zip just works in the mixed version cluster (each node populates its state according to the node's binary, not the binary used as the "gateway" for `debug zip` command).

Epic: None

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
@cockroachdb/obs-prs could someone double check me please on the following: in the mixed version cluster, when taking a debug.zip, if contents for a single `crdb_internal` virtual table cannot be retrieved (due to a query execution error - on newer nodes we have a new column, on older we don't), the debug.zip as a whole won't be impacted, right?

**Review by DrewKimball — APPROVED** [review]
:lgtm: assuming the case of a mixed-version state doesn't cause issues.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122069#-:-Nv9djD53tl7fHVO1n1k:bbwhhgn)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by yuzefovich** [comment]
I just manually verified the mixed version state, and actually things worked in all scenarios. I think this is because we only have single-node view of the memory monitoring state, so each node is responsible for populating the file that corresponds to it, not the `cockroach` binary acting as the gateway for `debug zip` operation.

TFTR!

bors

**Pull request merged**
