### PR TITLE
binfetcher: extract binary downloader

### PR DESCRIPTION
**Pull request by tbg**
This is helpful for upcoming infrastructure improvements. I want to put this
into its own repository with nightly CI (as opposed to the CI here on every
build, which is overkill and annoys offline developers) and vendor it where
needed.

I am holding off on that initially because I anticipate some amount of
bikeshedding.

Release note: None

### CODE REVIEW

**Comment by tschottdorf** [comment]
@benesch, could you review the first commit? Ignore the second one for now.

**Comment by benesch** [comment]
Ugh, sorry for the delay. Taking a look shortly.

**Review by benesch — APPROVED** [review]
LGTM!

But! If we're planning to use this in a bunch of places, I would prefer that it be written in (don't kill me) bash. Otherwise it's difficult to use in, say, the ORM repositories which don't have a Go pipeline set up.

**Comment by tschottdorf** [comment]
TFTR! I'll do the bash version in a second PR.

**Pull request merged**
