### PR TITLE
*: Don't build RocksDB when calling "make buildshort" 

### PR DESCRIPTION
**Pull request by itsbilal**
As in title.

Adds a RocksDB engine stub that panics on all methods,
and that stub is substituted in when the `short` flag
is set. Some common, non-rocksdb related methods/variables
in rocksdb.go had to be moved to other files.

This change, plus the changes in the previous commits,
allows us to also get away without building libroach.

First two commits are #53978.

Release justification: Will land in 21.1.
Release note: None.

### CODE REVIEW

**Comment by itsbilal** [comment]
A bit of a WIP as I'm not sure how to remove rocksdb/libroach from `zcgo_flags_*.go` files. This isn't entirely necessary; the linker just throws a warning that it can't find the directories specified in there, but it never errors out as we don't rely on any of the symbols in those libraries (and we don't explicitly request `-lroach` or `-lrocksdb` anywhere).

**Review by petermattis — COMMENTED** [review]
Exciting!

> Reviewed 1 of 1 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53979#-:-MGQQCEjEx2ZsFJKNwcS:b-pxyq17)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @jbowens, and @petermattis)

___
*[Makefile, line 523 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53979#-MGQOoRC8oKChBFy_Rs7:-MGQOoRC8oKChBFy_Rs8:b-rpgznl) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a9542674238038ef75651e0cc3b7ca8ac07a411/Makefile#L523)):*
> ```Makefile
> 	$(if $(target-is-windows),,$(LIBEDIT)) \
> 	$(LIBPROTOBUF) $(LIBSNAPPY) $(LIBPROJ) $(LIBGEOS)
> C_LIBS_SHORT = $(C_LIBS_COMMON) $(LIBCRYPTOPP)
> ```

Do we need `LIBCRYPTOPP` here? I thought it was only used for RocksDB encryption-at-rest. 
___
*[pkg/storage/merge.go, line 11 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53979#-MGQPAvH0ESrBt-x2y2E:-MGQPAvH0ESrBt-x2y2F:bvh9laq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a9542674238038ef75651e0cc3b7ca8ac07a411/pkg/storage/merge.go#L11)):*
> ```Go
> // licenses/APL.txt.
> //
> // +build !short
> ```

Perhaps rename this file to `rocksdb_merge.go`.
___
*[pkg/storage/merge.go, line 64 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53979#-MGQPW5G9oNGZ6kIlP5v:-MGQPW5G9oNGZ6kIlP5w:by3bttv) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a9542674238038ef75651e0cc3b7ca8ac07a411/pkg/storage/merge.go#L64)):*
> ```Go
> // can combine with mergeIntoNil: the initial state is either 'nil' or the first
> // operand.
> func MergeInternalTimeSeriesData(
> ```

Isn't this used by `ts/timeseries_test.go`? Can we move this function to `pebble_merge.go` and rewrite it to use the Pebble merge operator?
___
*[pkg/storage/rocksdb_short.go, line 73 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53979#-MGQQ-OJ-oPBJ0AacX6l:-MGQQ-OJ-oPBJ0AacX6m:bq9745u) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a9542674238038ef75651e0cc3b7ca8ac07a411/pkg/storage/rocksdb_short.go#L73)):*
> ```Go
> // NewRocksDB allocates and returns a new RocksDB stub object.
> func NewRocksDB(cfg RocksDBConfig, cache RocksDBCache) (*RocksDB, error) {
> 	r := &RocksDB{}
> ```

I'm curious why you had to fully define the `RocksDB` type. I would think it sufficient to define a placeholder type and `panic` here.

**Review by itsbilal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53979)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens and @petermattis)

___
*[Makefile, line 523 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53979#-MGQOoRC8oKChBFy_Rs7:-MHHBiJlBAJl0FxytTn7:baepipx) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a9542674238038ef75651e0cc3b7ca8ac07a411/Makefile#L523)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Do we need `LIBCRYPTOPP` here? I thought it was only used for RocksDB encryption-at-rest. 
</blockquote></details>

Done. Good catch; we don't need it.
___
*[pkg/storage/rocksdb_short.go, line 73 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53979#-MGQQ-OJ-oPBJ0AacX6l:-MGyurZe4XGI4vVQKMKn:bxswi0r) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a9542674238038ef75651e0cc3b7ca8ac07a411/pkg/storage/rocksdb_short.go#L73)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm curious why you had to fully define the `RocksDB` type. I would think it sufficient to define a placeholder type and `panic` here.
</blockquote></details>

Good point. I had to do this because the function signature here can't be changed, and the return struct type had to adhere to the `Engine` interface, regardless of whether we return a stub here or panic rightaway.
___
*[pkg/storage/merge.go, line 11 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53979#-MGQPAvH0ESrBt-x2y2E:-MGyup-M2u24a3gVu6MK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a9542674238038ef75651e0cc3b7ca8ac07a411/pkg/storage/merge.go#L11)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Perhaps rename this file to `rocksdb_merge.go`.
</blockquote></details>

Done.
___
*[pkg/storage/merge.go, line 64 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53979#-MGQPW5G9oNGZ6kIlP5v:-MHHCc2IDLCDO7CPx5-t:bj1tn0z) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a9542674238038ef75651e0cc3b7ca8ac07a411/pkg/storage/merge.go#L64)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Isn't this used by `ts/timeseries_test.go`? Can we move this function to `pebble_merge.go` and rewrite it to use the Pebble merge operator?
</blockquote></details>

We should do that rewrite, yes. It's not necessary for this change, but either way I'll probably get to that later this week.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53979)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @jbowens)

___
*[Makefile, line 523 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53979#-MGQOoRC8oKChBFy_Rs7:-MHIdyko9ohATgCFANwN:b-bivba) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a9542674238038ef75651e0cc3b7ca8ac07a411/Makefile#L523)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Done. Good catch; we don't need it.
</blockquote></details>

Do we need `LIBPROTOBUF`? Do we need `LIBSNAPPY`? I think the answer is no to both.
___
*[pkg/storage/rocksdb_short.go, line 73 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53979#-MGQQ-OJ-oPBJ0AacX6l:-MHIeZzfBqeoeahqqrIP:b47xdn) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a9542674238038ef75651e0cc3b7ca8ac07a411/pkg/storage/rocksdb_short.go#L73)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Good point. I had to do this because the function signature here can't be changed, and the return struct type had to adhere to the `Engine` interface, regardless of whether we return a stub here or panic rightaway.
</blockquote></details>

I wonder if you could do a hack by using a type alias.

```
type RocksDB = Pebble
```

And then leave the panic here. Nobody will be able to use RocksDB.

**Review by itsbilal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53979)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens and @petermattis)

___
*[Makefile, line 523 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53979#-MGQOoRC8oKChBFy_Rs7:-MHXdz9YBFAE6mFWEhhf:bv8pfgd) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a9542674238038ef75651e0cc3b7ca8ac07a411/Makefile#L523)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Do we need `LIBPROTOBUF`? Do we need `LIBSNAPPY`? I think the answer is no to both.
</blockquote></details>

Yep, the answer is no to both. Removed.
___
*[pkg/storage/rocksdb_short.go, line 73 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53979#-MGQQ-OJ-oPBJ0AacX6l:-MHXe0V479yX2IBjLac0:b-90ewdr) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a9542674238038ef75651e0cc3b7ca8ac07a411/pkg/storage/rocksdb_short.go#L73)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I wonder if you could do a hack by using a type alias.

```
type RocksDB = Pebble
```

And then leave the panic here. Nobody will be able to use RocksDB.
</blockquote></details>

Done. That worked. Had to hack on a `GetTickersAndHistograms` though.

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53979#-:-MHkkSFa2qp2BDswTZHM:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens and @petermattis)

**Comment by itsbilal** [comment]
TFTR!

I tried making the `MergeInternalTimeSeriesData` change, but I'm having a harder time figuring out what `mergeWithNil = true` is supposed to mean from an MVCC standpoint, and how I should implement it with the new merger. Turns out, merging with a zero-value `InternalTimeSeriesData` doesn't produce the same result, but that's what the C++ code seems to be doing?

Anyway, the rest of this PR is complete. If you're fine with me deferring that change for a future PR, I can merge this as-is and remove the WIP marker.

**Review by petermattis — APPROVED** [review]
I'm fine with merging as-is.

> Turns out, merging with a zero-value InternalTimeSeriesData doesn't produce the same result, but that's what the C++ code seems to be doing?

Feels like something to look into. The C++ and Go merge code should have identical behavior.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53979#-:-MHlbb8L7qn9twfpkm1a:b-t43bxv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens and @petermattis)

**Comment by itsbilal** [comment]
Will look into it. Thanks!

bors r+

**Pull request merged**
