### PR TITLE
bazel: refactor dev roachprod-bench-wrapper command to dev test-binaries

### PR DESCRIPTION
**Pull request by herkolategan**
This intends to decouple generating test binaries and running the roachprod microbenchmarks command. Rather than having a strong coupling this command will now just build and archive the portable test binaries that can then be used by any other commands in the future.

The command also no longer builds the libraries or the roachprod microbenchmarks binary (formerly roachprod-bench). After this change `dev test-binaries` will only generate an archive of portable test binaries. This archive can then be used with the roachprod microbenchmarks command, possibly amongst other things, to run microbenchmarks.

See also: #90958

Release note: None

### CODE REVIEW

**Review by srosenberg — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95353#-:-NPwWH9m10hZ4Ro-n1kP:b593vm9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lateg)

___
*[`pkg/cmd/dev/test_binaries.go` line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95353#-NPwUp9LBnDplvQmP8sG:-NPwUp9LBnDplvQmP8sH:b9haefv) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d9236c7532d0602e10db7b19f5a9559a5fbaf34/pkg/cmd/dev/test_binaries.go#L55)):*
> ```Go
> const stageOutputTemplateScript = `
> mkdir -p #{.StageDir#}
> ln -s #{.BazelOutputDir#}/#{.RunfilesDirName#} #{.StageDir#}/#{.RunfilesDirName#}
> ```

Curious why the change from `cp`? Both source and destination are on the same filesystem, right?
___
*[`pkg/cmd/dev/test_binaries.go` line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95353#-NPwVQ1S4maAG8cTb9mM:-NPwVQ1S4maAG8cTb9mN:b-pzh5oz) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d9236c7532d0602e10db7b19f5a9559a5fbaf34/pkg/cmd/dev/test_binaries.go#L70)):*
> ```Go
> 
> rm -rf pkg
> bazel clean
> ```

No `--expunge`?
___
*[`pkg/cmd/dev/test_binaries.go` line 356 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95353#-NPwVyJk7GwdUXR7jzJk:-NPwVyJk7GwdUXR7jzJl:bbtbm4f) ([raw file](https://github.com/cockroachdb/cockroach/blob/a90a9e96575e190eacb447eac99c06534b118afd/pkg/cmd/dev/test_binaries.go#L356)):*
> ```Go
> }
> 
> func (d *dev) buildGeos(ctx context.Context, volume string) error {
> ```

Does this mean that tests/benchmarks which depend on libgeos would fail to execute?

**Review by herkolategan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95353)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @srosenberg)

___
*[`pkg/cmd/dev/test_binaries.go` line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95353#-NPwUp9LBnDplvQmP8sG:-NPxF6QTBnFqmkQt7YOs:b-223xl8) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d9236c7532d0602e10db7b19f5a9559a5fbaf34/pkg/cmd/dev/test_binaries.go#L55)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Curious why the change from `cp`? Both source and destination are on the same filesystem, right?
</blockquote></details>

Yes, I had an issue where it would run out of disk space, so with the soft links it saved some space.
___
*[`pkg/cmd/dev/test_binaries.go` line 70 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95353#-NPwVQ1S4maAG8cTb9mM:-NPxFFIZACPd7MM_ePgS:bbmnhr4) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d9236c7532d0602e10db7b19f5a9559a5fbaf34/pkg/cmd/dev/test_binaries.go#L70)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

No `--expunge`?
</blockquote></details>

Clean here is again to free up some space in the interim, but expunge might be a good idea.
___
*[`pkg/cmd/dev/test_binaries.go` line 356 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95353#-NPwVyJk7GwdUXR7jzJk:-NPxFcYZ209z4VGRQzjA:bkz0ed5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a90a9e96575e190eacb447eac99c06534b118afd/pkg/cmd/dev/test_binaries.go#L356)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Does this mean that tests/benchmarks which depend on libgeos would fail to execute?
</blockquote></details>

Interestingly enough I haven't ever seen that happen. The microbenchmarks util will copy over `libgeos` and complain if it is not present.

**Review by srosenberg — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95353)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by herkolategan** [comment]
TFTR!
bors r=srosenberg

**Pull request merged**
