### PR TITLE
sql: print comments in SHOW CREATE TABLE

### LINKED ISSUE #42875: cli/dump: COMMENT ON missing
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:
If a column has a comment (via `COMMENT ON`), the comment will be missing in the `cockroach dumo --dump-mode schema` output.

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Create a schema with a comment ([the example in the docs](https://www.cockroachlabs.com/docs/v19.2/comment-on.html) will do)
2. Issue `cockroach dump --dump-mode schema <database>` | grep COMMENT
4. Observe the lack of output, which implies no comment was dumped with the schema.

**Expected behavior**
The schema is dumped with all comments.

**Environment:**
 - CockroachDB version v19.2.0
 - Server OS: Linux/archlinux
 - Client app cockroach dump

**Additional context**
What was the impact?

It silently swallowed my comments, which specified preliminary enum mappings for int2 columns. Thankfully it wasn't much.

### PR DESCRIPTION
**Pull request by hueypark**
Fixes #42875

Release note (sql change): SHOW CREATE TABLE now prints comments.

### CODE REVIEW

**Comment by namibj** [comment]
Will this get into v.19.2.3? I'd quite like to deploy this, so that I can start writing comments without them getting lost.

**Comment by hueypark** [comment]
@jordanlewis Would you review this?

**Review by knz — COMMENTED** [review]
@namibj no this will not get in 19.2.x. We do not add or changes features in release branches unless they are security-critical. The earliest this will be released will be v20.1.

@hueypark Jordan is away and he asked me to review.

As usual, your work here is very good. I have just one  suggestion to improve the interface and some stylistics edits on code comments.

A request on the commit message: can you expand the release note to explain what is happening, for example:

> Release note (sql change): SHOW CREATE TABLE now also emits the COMMENT statements sufficient to populate the table's user-defined comments, if any, alongside the CREATE statement proper.

Finally, could you please file an issue for supporting COMMENT ON VIEW and COMMENT ON SEQUENCE for completeness, and mention in the issue description that the code for SHOW CREATE must be adapted accordingly. Thank you.

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43152#-:-Lz2Dp1I-GgqOH1aomu_:b3nbsls)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @hueypark)

___
*[pkg/sql/show_create.go, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43152#-Lz2Ecct7RiRwtjVfvKG:-Lz2Ecct7RiRwtjVfvKH:b-1kw60j) ([raw file](https://github.com/cockroachdb/cockroach/blob/828853371c6e3b6ec88510dbb99499202516aeba/pkg/sql/show_create.go#L48)):*
> ```Go
> // the prefix when the given table references other tables in the
> // current database.
> func ShowCreateTable(
> ```

I would make this function a method on `*planner`, then add its in terface to the `PlanHookState` interface.
___
*[pkg/sql/show_create_clauses.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43152#-Lz2EoYYCJ1fG34PlYdm:-Lz2EoYYCJ1fG34PlYdn:b-uwx570) ([raw file](https://github.com/cockroachdb/cockroach/blob/828853371c6e3b6ec88510dbb99499202516aeba/pkg/sql/show_create_clauses.go#L26)):*
> ```Go
> )
> 
> // tableComment has comment data for table.
> ```

1) `tableConmment` -> `tableComments`

2) `// tableComments stores the comment data for a table.`
___
*[pkg/sql/show_create_clauses.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43152#-Lz2EnLUBvA0ca-RE0dq:-Lz2EnLV3VqS8gnuEYhE:b-e1wiev) ([raw file](https://github.com/cockroachdb/cockroach/blob/828853371c6e3b6ec88510dbb99499202516aeba/pkg/sql/show_create_clauses.go#L38)):*
> ```Go
> }
> 
> // selectComment returns table comment.
> ```

Detail what is being done here:

```go
// selectComment retrieves all the comments pertaining to a table (comments on the table
// itself but also column and index comments.)
```
___
*[pkg/sql/show_create_clauses.go, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43152#-Lz2F5l52B2h0y8oWkXI:-Lz2F5l52B2h0y8oWkXJ:b-o6b0wc) ([raw file](https://github.com/cockroachdb/cockroach/blob/828853371c6e3b6ec88510dbb99499202516aeba/pkg/sql/show_create_clauses.go#L94)):*
> ```Go
> }
> 
> // showComment writes a valid SQL representation of a COMMENT clause.
> ```

1) `showComment` -> `showComments`

2) `// showComments prints out the COMMENT statement sufficient to populate a table's comments, including its index and column comments.`

**Comment by knz** [comment]
sorry regarding my last comment of course the word should be plural:

```
// showComments prints out the COMMENT statements sufficient to populate a 
// table's comments, including its index and column comments.
```

**Review by hueypark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43152)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/sql/show_create.go, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43152#-Lz2Ecct7RiRwtjVfvKG:-Lz2JyBV6Zi1lHbeNgrT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/828853371c6e3b6ec88510dbb99499202516aeba/pkg/sql/show_create.go#L48)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I would make this function a method on `*planner`, then add its in terface to the `PlanHookState` interface.
</blockquote></details>

Done.
___
*[pkg/sql/show_create_clauses.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43152#-Lz2EoYYCJ1fG34PlYdm:-Lz2IODqBSdiSvMHGrjm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/828853371c6e3b6ec88510dbb99499202516aeba/pkg/sql/show_create_clauses.go#L26)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

1) `tableConmment` -> `tableComments`

2) `// tableComments stores the comment data for a table.`
</blockquote></details>

Done.
___
*[pkg/sql/show_create_clauses.go, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43152#-Lz2EnLUBvA0ca-RE0dq:-Lz2IWJt5tAn_ubZF-Q5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/828853371c6e3b6ec88510dbb99499202516aeba/pkg/sql/show_create_clauses.go#L38)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Detail what is being done here:

```go
// selectComment retrieves all the comments pertaining to a table (comments on the table
// itself but also column and index comments.)
```
</blockquote></details>

Done.
___
*[pkg/sql/show_create_clauses.go, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43152#-Lz2F5l52B2h0y8oWkXI:-Lz2InQFCfcMREvXz-Sx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/828853371c6e3b6ec88510dbb99499202516aeba/pkg/sql/show_create_clauses.go#L94)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

1) `showComment` -> `showComments`

2) `// showComments prints out the COMMENT statement sufficient to populate a table's comments, including its index and column comments.`
</blockquote></details>

Done.

**Review by knz — APPROVED** [review]
Very nice. Thank you!

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43152#-:-Lz2OgTu09OQWTaH0IDt:b-qp9fv8)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by hueypark — COMMENTED** [review]
I added an issue for VIEW and SEQUENCE(https://github.com/cockroachdb/cockroach/issues/44135).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43152#-:-Lz2PaQH2KsyAg7X4wso:bjtm7yj)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by hueypark** [comment]
Thank you for the review!

**Pull request merged**
