### PR TITLE
sql: refactor `FunctionOverload`

### PR DESCRIPTION
**Pull request by mgartner**
The `FunctionOverload` protobuf message has been renamed to
`FunctionSignature`. This addresses some confusion the previous name
caused, because the `FunctionOverload` message could not be converted
into a full `tree.Overload`. The new name reflects that it contains only
partial information about the function.

Epic: None

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
This seems good

**Review by benbardin — APPROVED** [review]
Approved for backupccl

**Review by chengxiong-ruan — APPROVED** [review]
Thanks a lot.

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Comment by mgartner** [comment]
I removed the first commit, because we actually do need the `ReturnSet` field for signatures.

**Pull request merged**
