### PR TITLE
backupccl,backupbase: change backupbase to backupresolved

### PR DESCRIPTION
**Pull request by pbardea**
Backupbase was a bit too generic and had quite of a bit of backup
specific info that didn't need to be shared outside of backupccl. It was
only this way due to some unfortunate dependencies. This commit cleans
up those dependencies, and backuptargets is a better suited name to
describe it's functionality.

Release justification: low risk (just code-movement) change, which no
expected impact. Merging in this release will make future backports
easier.
Release note: None

### CODE REVIEW

**Comment by pbardea** [comment]
My original intention for this change was just to get the backup configuration stuff back into backupccl so it doesn't need to bee exported anymore. After I did that though, all that was left was the backup target resolution stuff so I thought that renaming the package might make it clearer which parts are shared with changefeeds. WDYT?

**Review by miretskiy — APPROVED** [review]
> Reviewed 5 of 16 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61581)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea)

___
*[pkg/ccl/backupccl/system_schema.go, line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61581#-MVT_8CvDFL4sRAtvAMa:-MVT_8CvDFL4sRAtvAMb:bavybx1) ([raw file](https://github.com/cockroachdb/cockroach/blob/48c6fcae09c9dd329d64e9b83076f6d128925444/pkg/ccl/backupccl/system_schema.go#L50)):*
> ```Go
> //    cluster so there is no need to rewrite system table data.
> type systemBackupConfiguration struct {
> 	shouldIncludInClusterBackup clusterBackupInclusion
> ```

typo? missing `e` in `Includ`

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61581)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[pkg/ccl/backupccl/system_schema.go, line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61581#-MVT_8CvDFL4sRAtvAMa:-MVXhg53DkmAWUJQbaSa:bdr63nv) ([raw file](https://github.com/cockroachdb/cockroach/blob/48c6fcae09c9dd329d64e9b83076f6d128925444/pkg/ccl/backupccl/system_schema.go#L50)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

typo? missing `e` in `Includ`
</blockquote></details>

Yep -- thanks for catching!

**Comment by pbardea** [comment]
TFTR!
bors r+

**Pull request merged**
