### PR TITLE
sql/coltypes: remove the field `Name` in TArray

### PR DESCRIPTION
**Pull request by knz**
First commits from #28955 and priors.
Forked from #28690.

It was not needed. This simplifies.

Release note: None

### CODE REVIEW

**Review by BramGruneir — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, 18 of 18 files at r3, 2 of 2 files at r4, 7 of 7 files at r5, 3 of 3 files at r6, 13 of 13 files at r7, 31 of 31 files at r8, 23 of 23 files at r9, 16 of 16 files at r10, 2 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28959#-:-LKYUvXH2fy4rlaANexH:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/coltypes/arrays.go, line 43 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/28959#-LKYUZJB0_KOX5yp7F5P:-LKYUZJH5p3uHdNh3ulK:b-p29c2y) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98e93a917a052cf061065c75cae0934be30d706/pkg/sql/coltypes/arrays.go#L43)):*
> ```Go
> 	} else {
> 		node.ParamType.Format(buf, f)
> 		buf.WriteString("[]")
> ```

Is there a reason why this isn't:

```go
node.ParamType.Format(buf, f)
buf.WriteString("[]")
if collation, ok := node.ParamType.(*TCollatedString); ok {
  buf.WriteString(" COLLATE ")
  lex.EncodeUnrestrictedSQLIdent(buf, collation.Locale, f)
}
```

**Review by BramGruneir — COMMENTED** [review]
But I did have one question.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28959#-:-LKYUyV998Ae_d_W3BrZ:b-kpgsjy)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28959)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/coltypes/arrays.go, line 43 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/28959#-LKYUZJB0_KOX5yp7F5P:-LKabI9x9oO5cTR9YFV5:bbgzql9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d98e93a917a052cf061065c75cae0934be30d706/pkg/sql/coltypes/arrays.go#L43)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Is there a reason why this isn't:

```go
node.ParamType.Format(buf, f)
buf.WriteString("[]")
if collation, ok := node.ParamType.(*TCollatedString); ok {
  buf.WriteString(" COLLATE ")
  lex.EncodeUnrestrictedSQLIdent(buf, collation.Locale, f)
}
```
</blockquote></details>

This was my first idea, but unfortunately it is incorrect: if the element type is a collated string, `ParamType.Format()` would include the COLLATE keyword. However, the keyword must appear after the square brackets. 
I did however reuse the ParamType.Format instead of TypeName inside the if case, which is nicer to read.
Also added a comment to clarify.

Also added some tests.

**Comment by knz** [comment]
TFYR!

bors r+

**Comment by knz** [comment]
temporary doc site failure

bors r-

**Pull request merged**
