### PR TITLE
sql: skip flaky TestCaptureIndexUsageStats

### PR DESCRIPTION
**Pull request by gtr**
Informs: #102732

Release note: None

### CODE REVIEW

**Review by maryliag — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103295#-:-NVUmkML8DxJGLVLjdhQ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
This needs `./dev gen bazel`.

bors r-

**Comment by rafiss** [comment]
bors r-

```
  ERROR: /go/src/github.com/cockroachdb/cockroach/pkg/sql/scheduledlogging/BUILD.bazel:27:8: GoCompilePkg pkg/sql/scheduledlogging/scheduledlogging_test.internal.recompileinternal.a failed: (Exit 1): builder failed: error executing command bazel-out/k8-opt-exec-2B5CBBC6/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -tags bazel,gss,bazel,gss -src ... (remaining 75 arguments skipped)
  Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
  compilepkg: missing strict dependencies:
    /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/3004/execroot/com_github_cockroachdb_cockroach/pkg/sql/scheduledlogging/captured_index_usage_stats_test.go: import of "github.com/cockroachdb/cockroach/pkg/testutils/skip"
```

**Comment by gtr** [comment]
Forgot to update the BUILD file 😅 thanks!

**Pull request merged**
