### PR TITLE
cli/sql: fix very long pastes

### LINKED ISSUE #102083: cli/sql: bad behavior upon very long pastes
**Describe the problem**

Found by @fabiog1901 

When pasting a very large file, the line editor in the SQL interactive shell misbehaves.

**To Reproduce**

Try pasting a file that's >2kb in size or >100 lines long.

Jira issue: CRDB-27268

### PR DESCRIPTION
**Pull request by knz**
Fixes #102083.
Epic: CRDB-28893

Prior to this commit, a paste longer than 99 lines or longer than 1-2KB would be broken up with later pieces not parsed properly.

This imports the proper patch from upstream for it.

Release note: None

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
thanks!

**Comment by knz** [comment]
@rafiss given the small impact, would you be ok backporting this to 23.1.0?

bors r=rafiss

**Comment by rafiss** [comment]
yes, i think it's fine to backport to 23.1.0

**Comment by knz** [comment]
blathers backport 23.1.0

**Pull request merged**
