### PR TITLE
sql: export (and rename) resolver's requiredType

### PR DESCRIPTION
**Pull request by dt**
Release note: none.

### CODE REVIEW

**Comment by dt** [comment]
[bump]

**Review by jordanlewis — COMMENTED** [review]
:lgtm:, but why'd you need to export out of curiosity?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37431#-:-LeoL9PuAH3czb9arU-_:bvdfg04)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @knz)

**Comment by dt** [comment]
I need to do name resolution in ccl code for the name of an existing table for incremental import.

**Pull request merged**
