### PR TITLE
sql: optionally enable vectorized planning with experimental_vectorize

### PR DESCRIPTION
**Pull request by jordanlewis**
This commit adds optional, best-effort flow setup time planning of
columnar operators. When experimental_vectorize is set, flow setup will
attempt to convert DistSQL Processors into their columnar Operator
equivalents, if such equivalents exist.

Release note (sql change): the experimental_vectorize session setting,
when enabled, causes columnar operators to be planned instead of
row-by-row processors, when possible.

Release note: None

### CODE REVIEW

**Comment by jordanlewis** [comment]
This is ready for a look. It's currently got a merge from #31940 to permit scanning TPCH data, that will go away once that PR is merged.

**Comment by solongordon** [comment]
Rebased to pick up the date/decimal commits.

**Review by solongordon — CHANGES_REQUESTED** [review]
Great work! In CFetcher I pointed out unused code where I noticed it, though in some cases maybe you'll prefer to leave it there to maintain parity with RowFetcher.

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 4 of 4 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-:-LQA-XUE5LVjjvIza-_0:b-48n025)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/colbatch_scan.go, line 44 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-LQ9uCUG2J6p5sjm67da:-LQ9uCUG2J6p5sjm67db:btv13ld) ([raw file](https://github.com/cockroachdb/cockroach/blob/894c33185bb1a7ad2b6f1a138d7fec8eb03c6397/pkg/sql/distsqlrun/colbatch_scan.go#L44)):*
> ```Go
> 	s.ctx = context.Background()
> 	if err := s.rf.StartScan(
> 		context.Background(), s.flowCtx.txn, s.spans,
> ```

Doesn't really matter at this point but did you mean to pass `s.ctx` here?
___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 30 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-LQ9xHvd0NtC63cirdwz:-LQ9xHvd0NtC63cirdx-:buzc58k) ([raw file](https://github.com/cockroachdb/cockroach/blob/13a575fc8736ec707064d6fb5f200e9b567f110a/pkg/sql/distsqlrun/column_exec_setup.go#L30)):*
> ```Go
> )
> 
> func (f *Flow) makeColOperator(
> ```

unused?
___
*[pkg/sql/row/cfetcher.go, line 59 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-LQ9lhoo3SVnY7CIdygc:-LQ9lhoo3SVnY7CIdygd:bgjr3gf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9a5872afba25252892e1e4863636ba0c6b09b0f/pkg/sql/row/cfetcher.go#L59)):*
> ```Go
> 	// pair. It allows us to check if an index key belongs to a given
> 	// table-index.
> 	equivSignature []byte
> ```

Doesn't seem to ever be read (though the same is true in the rowfetcher).
___
*[pkg/sql/row/cfetcher.go, line 82 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-LQ9o_ILEm_88B4MzBkd:-LQ9o_ILEm_88B4MzBke:b2n8k8q) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9a5872afba25252892e1e4863636ba0c6b09b0f/pkg/sql/row/cfetcher.go#L82)):*
> ```Go
> 	// One value per column that is part of the key; each value is a column
> 	// index (into cols); -1 if we don't need the value for that column.
> 	indexColIdx []int
> ```

Nit: `indexColIndices` would be clearer. (Or perhaps `indexColOrdinals` to avoid mixing the two meanings of "index".)
___
*[pkg/sql/row/cfetcher.go, line 86 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-LQ9oeoE-ZXegJxaMD_k:-LQ9oeoE-ZXegJxaMD_l:b7au1ui) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9a5872afba25252892e1e4863636ba0c6b09b0f/pkg/sql/row/cfetcher.go#L86)):*
> ```Go
> 	// One value per column that is part of the key; each value is a column
> 	// index (into cols); -1 if we don't need the value for that column.
> 	extraValColIdx []int
> ```

Nit: `extraValColIndices` would be clearer`
___
*[pkg/sql/row/cfetcher.go, line 99 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-LQ9luOv7D2lm2aZdFqt:-LQ9luOv7D2lm2aZdFqu:b-yrumkl) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9a5872afba25252892e1e4863636ba0c6b09b0f/pkg/sql/row/cfetcher.go#L99)):*
> ```Go
> 
> 	// hasLast indicates whether there was a previously scanned k/v.
> 	hasLast bool
> ```

Unused
___
*[pkg/sql/row/cfetcher.go, line 104 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-LQ9lwHm24u3WJM4hBmx:-LQ9lwHm24u3WJM4hBmy:b-p4cg5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9a5872afba25252892e1e4863636ba0c6b09b0f/pkg/sql/row/cfetcher.go#L104)):*
> ```Go
> 	// It is required because Fetcher.kv is overwritten before NextRow
> 	// returns.
> 	lastKV roachpb.KeyValue
> ```

Written but never read
___
*[pkg/sql/row/cfetcher.go, line 108 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-LQ9lxI4-YTFhu2yZpuE:-LQ9lxI4-YTFhu2yZpuF:b-yrumkl) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9a5872afba25252892e1e4863636ba0c6b09b0f/pkg/sql/row/cfetcher.go#L108)):*
> ```Go
> 	// only present when doing a physical check in order to verify
> 	// ordering.
> 	lastDatums tree.Datums
> ```

Unused
___
*[pkg/sql/row/cfetcher.go, line 114 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-LQ9n9lE66VQo8N7VqaA:-LQ9n9lE66VQo8N7VqaB:b-9x51p3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9a5872afba25252892e1e4863636ba0c6b09b0f/pkg/sql/row/cfetcher.go#L114)):*
> ```Go
> // arbitrary number of tables.
> // Usage:
> //   var rf Fetcher
> ```

CFetcher
___
*[pkg/sql/row/cfetcher.go, line 185 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-LQ9nOcc3JK1R_8Wu2Tx:-LQ9nOcc3JK1R_8Wu2Ty:b-yrumkl) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9a5872afba25252892e1e4863636ba0c6b09b0f/pkg/sql/row/cfetcher.go#L185)):*
> ```Go
> 	rowReadyTable *cTableInfo // the table for which a row was fully decoded and ready for output
> 	currentTable  *cTableInfo // the most recent table for which a key was decoded
> 	keySigBuf     []byte      // buffer for the index key's signature
> ```

Unused
___
*[pkg/sql/row/cfetcher.go, line 186 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-LQ9nPHQ2bnKBH-Rt_uD:-LQ9nPHQ2bnKBH-Rt_uE:b-yrumkl) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9a5872afba25252892e1e4863636ba0c6b09b0f/pkg/sql/row/cfetcher.go#L186)):*
> ```Go
> 	currentTable  *cTableInfo // the most recent table for which a key was decoded
> 	keySigBuf     []byte      // buffer for the index key's signature
> 	keyRestBuf    []byte      // buffer for the rest of the index key that is not part of the signature
> ```

Unused
___
*[pkg/sql/row/cfetcher.go, line 207 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-LQ9maOa4x-IJogmCHI0:-LQ9maOa4x-IJogmCHI1:b-yrumkl) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9a5872afba25252892e1e4863636ba0c6b09b0f/pkg/sql/row/cfetcher.go#L207)):*
> ```Go
> // within tables. This permits reuse of this objects without forcing total
> // reallocation of all of those slice fields.
> func (rf *CFetcher) Reset() {
> ```

Unused
___
*[pkg/sql/row/cfetcher.go, line 270 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-LQ9ny_d5jdLnZeFjzY7:-LQ9ny_d5jdLnZeFjzY8:b-zaw5nj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9a5872afba25252892e1e4863636ba0c6b09b0f/pkg/sql/row/cfetcher.go#L270)):*
> ```Go
> 		var err error
> 		if multipleTables {
> 			panic("Can't do this yet")
> ```

Maybe add a bit more descriptive TODO and remove the dead code below
___
*[pkg/sql/row/cfetcher.go, line 628 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-LQ9mjA8DjzYTwjSLP7L:-LQ9mjA8DjzYTwjSLP7M:b-yrumkl) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9a5872afba25252892e1e4863636ba0c6b09b0f/pkg/sql/row/cfetcher.go#L628)):*
> ```Go
> // It returns whether or not the key is for any of the tables initialized
> // in Fetcher, and the remaining part of the key if it is.
> func (rf *CFetcher) ReadIndexKey(key roachpb.Key) (remaining []byte, ok bool, err error) {
> ```

Unused
___
*[pkg/sql/row/cfetcher.go, line 650 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-LQ9qKU4CZonC4Q1Ah4H:-LQ9qKU4CZonC4Q1Ah4I:baif7hp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9a5872afba25252892e1e4863636ba0c6b09b0f/pkg/sql/row/cfetcher.go#L650)):*
> ```Go
> 			table.desc.Name,
> 			table.index.Name,
> 			//rf.prettyEncDatums(table.keyValTypes, table.keyVals),
> ```

Handle this or add a todo?
___
*[pkg/sql/row/cfetcher.go, line 667 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-LQ9q2FK1vSKee5AfCWP:-LQ9q2FK1vSKee5AfCWQ:b-xbuldp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9a5872afba25252892e1e4863636ba0c6b09b0f/pkg/sql/row/cfetcher.go#L667)):*
> ```Go
> 		for idx, ok := table.neededValueColsByIdx.Next(0); ok; idx, ok = table.neededValueColsByIdx.Next(idx + 1) {
> 			// TODO(jordan) null out batch.
> 			//table.row[idx].UnsetDatum()
> ```

Do we need this now?
___
*[pkg/sql/row/cfetcher.go, line 668 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-LQ9rRb02IlhlkF8oCUR:-LQ9rRb02IlhlkF8oCUS:b-psx5yq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9a5872afba25252892e1e4863636ba0c6b09b0f/pkg/sql/row/cfetcher.go#L668)):*
> ```Go
> 			// TODO(jordan) null out batch.
> 			//table.row[idx].UnsetDatum()
> 		}
> ```

In the rowfetcher there is some logic at this point for filling in column values that are part of the index key. Do we need that?
___
*[pkg/sql/row/cfetcher.go, line 766 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-LQ9sNnYDSWQHitvwF8t:-LQ9sNnYDSWQHitvwF8u:b-8pvelq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9a5872afba25252892e1e4863636ba0c6b09b0f/pkg/sql/row/cfetcher.go#L766)):*
> ```Go
> 	prettyKeyPrefix string,
> ) (prettyKey string, prettyValue string, err error) {
> 	panic("Can't do this yet")
> ```

Add a TODO and remove dead code?
___
*[pkg/sql/row/cfetcher.go, line 891 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-LQ9sgxx2_7XgZn8-ZyX:-LQ9sgxx2_7XgZn8-ZyY:bkwx3h3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9a5872afba25252892e1e4863636ba0c6b09b0f/pkg/sql/row/cfetcher.go#L891)):*
> ```Go
> }
> 
> // NextRow processes keys until we complete one row, which is returned as an
> ```

Update docstring
___
*[pkg/sql/row/cfetcher.go, line 990 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-LQ9mzpG2gU5Fvgqls1B:-LQ9mzpG2gU5Fvgqls1C:b-yrumkl) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9a5872afba25252892e1e4863636ba0c6b09b0f/pkg/sql/row/cfetcher.go#L990)):*
> ```Go
> // GetRangeInfo returns information about the ranges where the rows came from.
> // The RangeInfo's are deduped and not ordered.
> func (rf *CFetcher) GetRangeInfo() []roachpb.RangeInfo {
> ```

Unused

**Comment by solongordon** [comment]
FYI this logic test panics on the SELECT. Maybe it is specific to `fakedist` though?
```
# LogicTest: fakedist

statement ok
create table t (x int)

statement ok
insert into t values (1), (2), (3)

statement ok
set experimental_vectorize=true

query I rowsort
select * from t
----
1
2
3
```

**Review by jordanlewis — COMMENTED** [review]
I think it's specific to `fakedist`. I haven't done any testing with that yet. What's the panic?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-:-LQB62X60NHshGOMzIZp:bqwl7gd)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/colbatch_scan.go, line 44 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-LQ9uCUG2J6p5sjm67da:-LQAfVQa1DgYM3YWGA3Y:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/894c33185bb1a7ad2b6f1a138d7fec8eb03c6397/pkg/sql/distsqlrun/colbatch_scan.go#L44)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Doesn't really matter at this point but did you mean to pass `s.ctx` here?
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 30 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-LQ9xHvd0NtC63cirdwz:-LQAfeiF29uVJF-OXCht:b-qp3bzl) ([raw file](https://github.com/cockroachdb/cockroach/blob/13a575fc8736ec707064d6fb5f200e9b567f110a/pkg/sql/distsqlrun/column_exec_setup.go#L30)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

unused?
</blockquote></details>

Oops, yeah, guess that was abandoned WIP... thanks for noticing and sorry for making you read that whole thing hah
___
*[pkg/sql/row/cfetcher.go, line 59 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-LQ9lhoo3SVnY7CIdygc:-LQAfoYZD7PzLqUMdTaO:bcr04rw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9a5872afba25252892e1e4863636ba0c6b09b0f/pkg/sql/row/cfetcher.go#L59)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Doesn't seem to ever be read (though the same is true in the rowfetcher).
</blockquote></details>

Going to leave this alone for now to minimize diff... we do panic above here if we're invoked with more than one table so this is all dead code anyway. 
___
*[pkg/sql/row/cfetcher.go, line 82 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-LQ9o_ILEm_88B4MzBkd:-LQAfvoEBOQv4lyuToe6:b-6ajlzx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9a5872afba25252892e1e4863636ba0c6b09b0f/pkg/sql/row/cfetcher.go#L82)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Nit: `indexColIndices` would be clearer. (Or perhaps `indexColOrdinals` to avoid mixing the two meanings of "index".)
</blockquote></details>

Ooh, good idea. Ordinals. Done.
___
*[pkg/sql/row/cfetcher.go, line 86 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-LQ9oeoE-ZXegJxaMD_k:-LQAg441A-_G37JHENkb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9a5872afba25252892e1e4863636ba0c6b09b0f/pkg/sql/row/cfetcher.go#L86)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Nit: `extraValColIndices` would be clearer`
</blockquote></details>

Done.
___
*[pkg/sql/row/cfetcher.go, line 99 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-LQ9luOv7D2lm2aZdFqt:-LQAg5wa7bF61HmAgQos:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9a5872afba25252892e1e4863636ba0c6b09b0f/pkg/sql/row/cfetcher.go#L99)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Unused
</blockquote></details>

Done.
___
*[pkg/sql/row/cfetcher.go, line 108 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-LQ9lxI4-YTFhu2yZpuE:-LQAg9JY5PJc6tbH48Ad:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9a5872afba25252892e1e4863636ba0c6b09b0f/pkg/sql/row/cfetcher.go#L108)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Unused
</blockquote></details>

Done.
___
*[pkg/sql/row/cfetcher.go, line 114 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-LQ9n9lE66VQo8N7VqaA:-LQAgAlW4Hid_J4LBJfh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9a5872afba25252892e1e4863636ba0c6b09b0f/pkg/sql/row/cfetcher.go#L114)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

CFetcher
</blockquote></details>

Done.
___
*[pkg/sql/row/cfetcher.go, line 185 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-LQ9nOcc3JK1R_8Wu2Tx:-LQAgDLQEG7jXku8tsYI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9a5872afba25252892e1e4863636ba0c6b09b0f/pkg/sql/row/cfetcher.go#L185)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Unused
</blockquote></details>

Done.
___
*[pkg/sql/row/cfetcher.go, line 186 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-LQ9nPHQ2bnKBH-Rt_uD:-LQAgDfl5G87yAo-7Hmp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9a5872afba25252892e1e4863636ba0c6b09b0f/pkg/sql/row/cfetcher.go#L186)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Unused
</blockquote></details>

Done.
___
*[pkg/sql/row/cfetcher.go, line 207 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-LQ9maOa4x-IJogmCHI0:-LQAgFjK3iX5Qul-MMOq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9a5872afba25252892e1e4863636ba0c6b09b0f/pkg/sql/row/cfetcher.go#L207)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Unused
</blockquote></details>

Done.
___
*[pkg/sql/row/cfetcher.go, line 270 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-LQ9ny_d5jdLnZeFjzY7:-LQAgMGP6NV0qmB1VH7_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9a5872afba25252892e1e4863636ba0c6b09b0f/pkg/sql/row/cfetcher.go#L270)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Maybe add a bit more descriptive TODO and remove the dead code below
</blockquote></details>

Done.
___
*[pkg/sql/row/cfetcher.go, line 628 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-LQ9mjA8DjzYTwjSLP7L:-LQAgcf26lOQB-xU0VmG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9a5872afba25252892e1e4863636ba0c6b09b0f/pkg/sql/row/cfetcher.go#L628)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Unused
</blockquote></details>

Done.
___
*[pkg/sql/row/cfetcher.go, line 650 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-LQ9qKU4CZonC4Q1Ah4H:-LQAhzAJ3UWRCzMSDyZM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9a5872afba25252892e1e4863636ba0c6b09b0f/pkg/sql/row/cfetcher.go#L650)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Handle this or add a todo?
</blockquote></details>

Done.
___
*[pkg/sql/row/cfetcher.go, line 667 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-LQ9q2FK1vSKee5AfCWP:-LQAi09_67J-UWJCU7a-:bgmvm9u) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9a5872afba25252892e1e4863636ba0c6b09b0f/pkg/sql/row/cfetcher.go#L667)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Do we need this now?
</blockquote></details>

We don't need it if we can't handle nulls, which we currently can't. We'll add this when we add null support. Added a TODO.
___
*[pkg/sql/row/cfetcher.go, line 668 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-LQ9rRb02IlhlkF8oCUR:-LQB-0Yc86pYTf6HgiAg:bbhfmyg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9a5872afba25252892e1e4863636ba0c6b09b0f/pkg/sql/row/cfetcher.go#L668)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

In the rowfetcher there is some logic at this point for filling in column values that are part of the index key. Do we need that?
</blockquote></details>

Yes, but this now occurs directly when we decode keyVals, since we're decoding right into the column vectors. So it's not present here.
___
*[pkg/sql/row/cfetcher.go, line 766 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-LQ9sNnYDSWQHitvwF8t:-LQB-5mSE0b983cLTX7s:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9a5872afba25252892e1e4863636ba0c6b09b0f/pkg/sql/row/cfetcher.go#L766)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Add a TODO and remove dead code?
</blockquote></details>

Done.
___
*[pkg/sql/row/cfetcher.go, line 891 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-LQ9sgxx2_7XgZn8-ZyX:-LQB-UqV8MG05BYdvVOh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9a5872afba25252892e1e4863636ba0c6b09b0f/pkg/sql/row/cfetcher.go#L891)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Update docstring
</blockquote></details>

Done.
___
*[pkg/sql/row/cfetcher.go, line 990 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-LQ9mzpG2gU5Fvgqls1B:-LQB-VBACYZAe-tnC_VI:brbdlbf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9a5872afba25252892e1e4863636ba0c6b09b0f/pkg/sql/row/cfetcher.go#L990)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Unused
</blockquote></details>

Going to leave this one for now as we'll need it eventually.

**Review by jordanlewis — COMMENTED** [review]
Thanks for your review - I know this was a ton of (messy) code, I appreciate your willingness to dive in

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-:-LQB68lO6TldaA14sMll:bajbfa5)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by jordanlewis — COMMENTED** [review]
Yeah `fakedist` just will completely not work at all, since the planner I wrote completely ignores all of the distsql infrastructure (multiple streams, routers, etc etc). I'll add a new switch that refuses to vectorize if the flow isn't fully local.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-:-LQBGsc5-2qGCuwBQLlZ:b-he10jx)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by solongordon — APPROVED** [review]
:lgtm_strong:, mod the new switch you mentioned.

> Reviewed 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-:-LQESaglDMwzNR7zLaL_:b-buv6vw)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by jordanlewis — COMMENTED** [review]
Done - turns out I was missing a case in the big stream setup loop, which was why it wasn't failing at that step. Now we return an error if a stream is anything but a local one. I verified your test case works. I'm not sure what the testing strategy should be for this yet. Probably we should introduce YALTC, but I'll leave that for later I think.

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31354#-:-LQEfAF89wPQ0V-LLwt0:b-5z9d9h)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
