### PR TITLE
storage: adopt util/quotapool

### PR DESCRIPTION
**Pull request by ajwerner**
Release note: None

### CODE REVIEW

**Comment by ajwerner** [comment]
@andreimatei hold off on reviewing this guy. Nathan has more context and we just talked about another change we want to make here.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39119)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/storage/replica.go, line 295 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39119#-Llboa1d-YhHmv-qUrwU:-Llboa1d-YhHmv-qUrwV:b-330gxl) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e65960e5861b30b85d8970b1a7088195a184517/pkg/storage/replica.go#L295)):*
> ```Go
> 		//
> 		// The *ProposalData in the map are "owned" by it. Elements from the
> 		// map must only be referenced while the Replica.raftMu is held, except
> ```

@nvanbenschoten and I spoke offline about this. It intended to say the Replica.mu but we added further synchronization on the `ctx` field in https://github.com/cockroachdb/cockroach/pull/38343. I added some more comments but I'm not sure they're super clear. I'm going to work on moving the proposals map down below the raftMu instead.

**Comment by ajwerner** [comment]
This is RFAL

**Review by nvb — APPROVED** [review]
:lgtm: very nice!

> Reviewed 3 of 12 files at r1, 10 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39119#-:-Lm6qgfv3opqTBLpNZLm:bhnhlex)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @andreimatei)

___
*[pkg/storage/replica_destroy.go, line 157 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39119#-Lm6ou1H4Z2O3E9d3vpT:-Lm6ou1H4Z2O3E9d3vpU:b1mlo9a) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e7bb11fd2b416c2c07c63c77fcdb73dd3bffbe4/pkg/storage/replica_destroy.go#L157)):*
> ```Go
> // It requires that both mu and raftMu are held.
> func (r *Replica) cancelPendingCommandsLocked() {
> 	r.raftMu.AssertHeld()
> ```

nit: assert in the same order that you do above.
___
*[pkg/storage/replica_proposal_quota.go, line 244 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39119#-Lm6pcW-102sBhslPOq0:-Lm6pcW-102sBhslPOq1:bu9f9gj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e7bb11fd2b416c2c07c63c77fcdb73dd3bffbe4/pkg/storage/replica_proposal_quota.go#L244)):*
> ```Go
> 		var toRelease *quotapool.IntAlloc
> 		for _, rel := range r.mu.quotaReleaseQueue[:numReleases] {
> 			if rel == nil || !rel.From(r.mu.proposalQuota) {
> ```

Add a comment about when `!rel.From(r.mu.proposalQuota)` would evaluate to true.
___
*[pkg/storage/replica_proposal_quota.go, line 250 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39119#-Lm6pkrs7oGMmxUIDzz6:-Lm6pkrs7oGMmxUIDzz7:b-tg6ubl) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e7bb11fd2b416c2c07c63c77fcdb73dd3bffbe4/pkg/storage/replica_proposal_quota.go#L250)):*
> ```Go
> 				toRelease = rel
> 			} else {
> 				toRelease.Merge(rel)
> ```

Is this more efficient than releasing each `IntAlloc` one-by-one?

**Review by ajwerner — COMMENTED** [review]
TFTR! I reworked the release logic into the quotapool package. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39119#-:-Lm7N_yc1KXHxhZlOXhb:bk1hz7d)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/storage/replica_destroy.go, line 157 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39119#-Lm6ou1H4Z2O3E9d3vpT:-Lm7MdKb0W24puab5IaG:bb0lvin) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e7bb11fd2b416c2c07c63c77fcdb73dd3bffbe4/pkg/storage/replica_destroy.go#L157)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: assert in the same order that you do above.
</blockquote></details>

Switched the other one.
___
*[pkg/storage/replica_proposal_quota.go, line 244 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39119#-Lm6pcW-102sBhslPOq0:-Lm75H_f4SuUf6ilxKVG:b-27tvlh) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e7bb11fd2b416c2c07c63c77fcdb73dd3bffbe4/pkg/storage/replica_proposal_quota.go#L244)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Add a comment about when `!rel.From(r.mu.proposalQuota)` would evaluate to true.
</blockquote></details>

Added an `NB` but also moved this logic into the quotapool package as a separate commit. 
___
*[pkg/storage/replica_proposal_quota.go, line 250 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39119#-Lm6pkrs7oGMmxUIDzz6:-Lm71jmsDjcUDBmOSB_F:b8olbec) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e7bb11fd2b416c2c07c63c77fcdb73dd3bffbe4/pkg/storage/replica_proposal_quota.go#L250)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this more efficient than releasing each `IntAlloc` one-by-one?
</blockquote></details>

Yes. Merge updates the value in toRelease and puts rel back into the underlying sync.Pool without any synchronization. Release needs to synchronize on the `Pool` to check if somebody needs to get notified. 
___
*[pkg/storage/replica_proposal_quota.go, line 141 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39119#-Lm7Nn0t7a5uy3WNjmae:-Lm7Nn0uEf0Vp2VIByej:b6tln3g) ([raw file](https://github.com/cockroachdb/cockroach/blob/af42a40f168f76e20c42bc8a43d7898efaa9481e/pkg/storage/replica_proposal_quota.go#L141)):*
> ```Go
> 			// (if any) and release the quotaReleaseQueue so its allocs are pooled.
> 			r.mu.proposalQuota.Close("leader change")
> 			r.mu.proposalQuota.Release(r.mu.quotaReleaseQueue...)
> ```

I had forgotten to release this before.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 13 files at r4, 12 of 12 files at r6, 11 of 11 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39119#-:-LmAOwEiDbZ9IkTadT_f:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @andreimatei)

___
*[pkg/storage/replica_proposal_quota.go, line 250 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39119#-Lm6pkrs7oGMmxUIDzz6:-LmAOot07s38j8uHysSA:bah5wn7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e7bb11fd2b416c2c07c63c77fcdb73dd3bffbe4/pkg/storage/replica_proposal_quota.go#L250)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Yes. Merge updates the value in toRelease and puts rel back into the underlying sync.Pool without any synchronization. Release needs to synchronize on the `Pool` to check if somebody needs to get notified. 
</blockquote></details>

:thumbsup: thanks for encapsulating this concern.
___
*[pkg/storage/replica_proposal_quota.go, line 141 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39119#-Lm7Nn0t7a5uy3WNjmae:-LmAOfX_9vVDtO0Y8Lg3:bjex4b7) ([raw file](https://github.com/cockroachdb/cockroach/blob/af42a40f168f76e20c42bc8a43d7898efaa9481e/pkg/storage/replica_proposal_quota.go#L141)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I had forgotten to release this before. 
</blockquote></details>

Good catch. Did you hit an assertion or anything?
___
*[pkg/util/quotapool/intpool_test.go, line 473 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39119#-LmANoZ_2CqB3D79ZwAX:-LmANoZ_2CqB3D79ZwAY:bscl6fm) ([raw file](https://github.com/cockroachdb/cockroach/blob/11b6d5c6474bf35c91dfdabd0c75f9884a136d92/pkg/util/quotapool/intpool_test.go#L473)):*
> ```Go
> }
> 
> // TestIntpoolRelease tests the Release method of intpool to ensure that it releases
> ```

Is there more to this or is it just missing a period?
___
*[pkg/util/quotapool/intpool_test.go, line 507 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39119#-LmAOABJ7SopaGrUHEWi:-LmAOABK07dGOozlSSN-:b76gr09) ([raw file](https://github.com/cockroachdb/cockroach/blob/11b6d5c6474bf35c91dfdabd0c75f9884a136d92/pkg/util/quotapool/intpool_test.go#L507)):*
> ```Go
> 			pools := makePools()
> 			allocs := make([]*quotapool.IntAlloc, len(c.toAcquire))
> 			for i, acq := range c.toAcquire {
> ```

Let's require that the fields in `acq` are within their `numPools` and `capacity` limits.

**Review by ajwerner — COMMENTED** [review]
TFTR

bors r=nvanbenschoten

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39119#-:-LmARGHp2rITlhmiVgfM:bxx76ig)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/storage/replica_proposal_quota.go, line 141 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39119#-Lm7Nn0t7a5uy3WNjmae:-LmAPVC_49XE82-mV1Oi:b-62b92c) ([raw file](https://github.com/cockroachdb/cockroach/blob/af42a40f168f76e20c42bc8a43d7898efaa9481e/pkg/storage/replica_proposal_quota.go#L141)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Good catch. Did you hit an assertion or anything?
</blockquote></details>

No. It wasn't a correctness issue, just weren't pooling. 
___
*[pkg/util/quotapool/intpool_test.go, line 473 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39119#-LmANoZ_2CqB3D79ZwAX:-LmAQRkeBnvJNitP8Kof:booj1bn) ([raw file](https://github.com/cockroachdb/cockroach/blob/11b6d5c6474bf35c91dfdabd0c75f9884a136d92/pkg/util/quotapool/intpool_test.go#L473)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is there more to this or is it just missing a period?
</blockquote></details>

Finished the sentence.
___
*[pkg/util/quotapool/intpool_test.go, line 507 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/39119#-LmAOABJ7SopaGrUHEWi:-LmAPwSaBe8gVgZHHXS2:bfd59ik) ([raw file](https://github.com/cockroachdb/cockroach/blob/11b6d5c6474bf35c91dfdabd0c75f9884a136d92/pkg/util/quotapool/intpool_test.go#L507)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's require that the fields in `acq` are within their `numPools` and `capacity` limits.
</blockquote></details>

It will panic if it's outside of `numPools`. Requests above `capacity` are truncated so it's not technically a problem but added an assertion anyway.

**Review by nvb — APPROVED** [review]
> Reviewed 1 of 12 files at r8, 11 of 11 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39119)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei)

**Pull request merged**
