### PR TITLE
colexec: speed up ordered sync

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: refactor ordered sync to use assign instead of append**

Ordered synchronizer sets the output one row at a time. Previously, we
were calling Append on the output vectors, but it is faster to use Sets
in such scenario.

Release note: None

**colexec: speed up ordered sync**

This commit speeds up the ordered synchronizer with two modifications:
1. instead of updating the allocator after we copy a single whole row,
we will now update the allocator after we copy a full batch of rows
2. to reduce the number of interface conversions we will "strip" output
vectors to get to the underlying slices and will use those directly when
copying the data.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Here is the benchmark with the default three inputs:
```
name                    old time/op    new time/op    delta
OrderedSynchronizer-16     139µs ± 1%      55µs ± 1%   -60.54%  (p=0.000 n=9+10)

name                    old speed      new speed      delta
OrderedSynchronizer-16   177MB/s ± 1%   449MB/s ± 1%  +153.45%  (p=0.000 n=9+10)

name                    old alloc/op   new alloc/op   delta
OrderedSynchronizer-16    32.8kB ± 0%     0.0kB       -100.00%  (p=0.000 n=10+10)

name                    old allocs/op  new allocs/op  delta
OrderedSynchronizer-16     1.02k ± 0%     0.00k       -100.00%  (p=0.000 n=10+10)
```

**Comment by yuzefovich** [comment]
There is currently a bug with Setting values on Bytes type, I'll fix it tomorrow.

**Comment by yuzefovich** [comment]
Actually, I was wrong - there is no bug in this PR, so it is RFAL.

(Yesterday I thought that when we're setting NULL value on a `Bytes` vector, we would need to set an empty byte slice in the corresponding position as well, but this is not necessary because before returning the output batch, we're setting a length on it, and that method will enforce the invariant on `Bytes`.)

**Review by solongordon — APPROVED** [review]
Nice speed-up!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43834#-:-LyA_EdbApEFvRrs39y-:bj9s536)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

**Comment by yuzefovich** [comment]
I think the most of the performance improvement comes from reducing the number of calls on allocator, and I was the one who put them in place :)

TFTR!

bors r+

**Review by solongordon — COMMENTED** [review]
Well the use of `Append` to copy single rows into the output is a wart that was there from the beginning so you get full credit for fixing that.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43834#-:-LyAb89h1n1AmtoLUarr:bct4le2)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Pull request merged**
