### PR TITLE
sql: delete distsql modes 2.0-off and 2.0-auto

### LINKED ISSUE #34162: sql: delete 2.0-off and 2.0-auto settings for 2.2
The logic tests themselves also need to be changed to no longer use 2.0-off for `local` mode.

Deleting these settings will further pave the way to deleting the implementations of planNodes that have distsql equivalents.

### PR DESCRIPTION
**Pull request by jordanlewis**
This removes user ability to query using the local engine.

Closes #34162.

Release note (sql change): remove the 2.0-off and 2.0-auto distsql
modes. All queries are now run via the newer, distsql engine; queries
are still only distributed if appropriate.

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

Awesome!  Hopefully we will be able to get rid of the `local/local-opt` testsuites altogether.

What are the cases that are left where we still run the planNode code for nodes which would otherwise have a distsql equivalent? (you mentioned `deleteNode`, is there anything else?) Because we will have a gap in our testing until then.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34163#-:-LWq0ylo5dc1FFxzL_ID:b-6nuan)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @RaduBerinde)

**Comment by jordanlewis** [comment]
As far as I can tell it's just delete. I have a separate branch where I changed all of the local implementations to panic unconditionally - this revealed crashes in the logic tests with deletes. It's possible that there are more, but hopefully not. I'm suspicious that there's still a lurking issue with explains, which generally do weird stuff - will find out soon.

**Comment by jordanlewis** [comment]
bors r+

Hopefully good now - was fighting slightly incorrect trace output.

**Comment by RaduBerinde** [comment]
🎉 You impressed the gods today.

**Pull request merged**
