### PR TITLE
cherrypick-2.0: log: misc logging fixes

### PR DESCRIPTION
**Pull request by knz**
Picks #23221.
Picks #23230.

cc @cockroachdb/release

### CODE REVIEW

**Review by bdarnell — APPROVED** [review]

**Comment by BramGruneir** [comment]
*[pkg/util/log/clog.go, line 1106 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23231#-L6SvticvYYqIHbyloCI:-L6SvticvYYqIHbyloCJ:b-1svpch) ([raw file](https://github.com/cockroachdb/cockroach/blob/312d930e96ff9fef29623372476cdd40e0118d62/pkg/util/log/clog.go#L1106)):*
> ```Go
> 		for _, l := range secondaryLogRegistry.mu.loggers {
> 			l.logger.mu.Lock()
> 			if !l.logger.disableDaemons {
> ```

is disableDaemons locked via mu?
If not, why not check this outside of the lock and not lock if they are disabled?  Or should disableDaemons be put under the lock?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23231)*

**Comment by BramGruneir** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23231)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/util/log/clog.go, line 1106 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23231#-L6SvticvYYqIHbyloCI:-L6SxAvYeT_j-rzVD-lB:byc8jvc) ([raw file](https://github.com/cockroachdb/cockroach/blob/312d930e96ff9fef29623372476cdd40e0118d62/pkg/util/log/clog.go#L1106)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

is disableDaemons locked via mu?
If not, why not check this outside of the lock and not lock if they are disabled?  Or should disableDaemons be put under the lock?
</blockquote></details>

Good call. Will look into it. As this is a cherry-pick I will not edit this commit but if there's an improvement to be made on `master` I'll have a look.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23231)*

**Comment by knz** [comment]
TFYRs

**Pull request merged**
