### PR TITLE
sql, storage: misc spelling fixes

### PR DESCRIPTION
**Pull request by BramGruneir**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8980)

### CODE REVIEW

**Comment by petermattis** [comment]
LGTM, though merge this to master.

**Comment by BramGruneir** [comment]
I'll close and open another PR to merge to master.

**Comment by tamird** [comment]
There's no need to close and reopen.

**Comment by BramGruneir** [comment]
ok, cherry-picked this onto master, sadly, github won't let me reopen the PR.  I'll post a new one.

**Pull request closed without merging**
