### PR TITLE
sqlsmith: add support for computed columns

### PR DESCRIPTION
**Pull request by RaduBerinde**
This changes the random table generator to also create computed
columns (either STORED or VIRTUAL). Some example of definitions:
 - `col1_14 STRING NOT NULL AS (lower(CAST(col1_8 AS STRING))) VIRTUAL`
 - `col2_6 DECIMAL NOT NULL AS (col2_2 + 1:::DECIMAL) STORED`
 - `col1_13 INT4 AS (col1_0 + col1_10) STORED`

Release justification: non-production code change.

Release note: None

Informs #57608.

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61491#-:-MUyb7Fv4WAW3CcZ2RPd:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @RaduBerinde)

___
*[pkg/sql/rowenc/testutils.go, line 1245 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61491#-MUyan5x8X1HzNsoFNv_:-MUyan5x8X1HzNsoFNva:b-1dyetq) ([raw file](https://github.com/cockroachdb/cockroach/blob/47bb01c295c705bdf476ce6b4d0abf90423da299/pkg/sql/rowenc/testutils.go#L1245)):*
> ```Go
> 		// Make defs for computed columns.
> 		normalColDefs := columnDefs
> 		for i := nNormalColumns; i < nColumns; i++ {
> ```

[nit] `i` is not used in the block, so `for i := 0; i < nComputedColumns; i++ {` might be easier to understand.
___
*[pkg/sql/rowenc/testutils.go, line 1536 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61491#-MUya2mZ7ZF6fr4J1aJm:-MUya2m_6MZnypYk8UjB:b-q9oqvv) ([raw file](https://github.com/cockroachdb/cockroach/blob/47bb01c295c705bdf476ce6b4d0abf90423da299/pkg/sql/rowenc/testutils.go#L1536)):*
> ```Go
> 	if rng.Intn(2) == 0 {
> 		// Try to find a set of numeric columns with the same type so we can add
> 		// them together as the computed expression.
> ```

[nit] expand this explanation similar to the single-column explanation below. An example might be nice.
___
*[pkg/sql/rowenc/testutils.go, line 1594 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61491#-MUyZphmBkCqeSzaV6Hu:-MUyZphmBkCqeSzaV6Hv:b-e77vy5) ([raw file](https://github.com/cockroachdb/cockroach/blob/47bb01c295c705bdf476ce6b4d0abf90423da299/pkg/sql/rowenc/testutils.go#L1594)):*
> ```Go
> 		case types.DecimalFamily:
> 			var err error
> 			right, err = tree.ParseDDecimal("1")
> ```

[nit] I think you could use `RandDatum` to get a random "special" datum for `right`, rather than hard-coding to `1`.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61491)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @RaduBerinde)

___
*[pkg/sql/rowenc/testutils.go, line 1245 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61491#-MUyan5x8X1HzNsoFNv_:-MUybKtf5yg_e--vp1Ng:b-uq4tx3) ([raw file](https://github.com/cockroachdb/cockroach/blob/47bb01c295c705bdf476ce6b4d0abf90423da299/pkg/sql/rowenc/testutils.go#L1245)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] `i` is not used in the block, so `for i := 0; i < nComputedColumns; i++ {` might be easier to understand.
</blockquote></details>

nvm, `i` is used. disregard.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61491)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @mgartner)

___
*[pkg/sql/rowenc/testutils.go, line 1594 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61491#-MUyZphmBkCqeSzaV6Hu:-MUycEztEgG9-RdYISgC:bpvgdf4) ([raw file](https://github.com/cockroachdb/cockroach/blob/47bb01c295c705bdf476ce6b4d0abf90423da299/pkg/sql/rowenc/testutils.go#L1594)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] I think you could use `RandDatum` to get a random "special" datum for `right`, rather than hard-coding to `1`.
</blockquote></details>

Good idea, that also made the code simpler.

**Comment by RaduBerinde** [comment]
Had to make a few fixes: don't create FKs from computed columns or to virtual columns (which we don't support); and use `FmtParsable` in `TestCreateRandomSchema`.

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61491#-:-MUzuhHd-I5IAi9U0ZDy:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @RaduBerinde)

___
*[pkg/sql/rowenc/testutils.go, line 1621 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61491#-MUzuM5ZBmZJqyVsPqQt:-MUzuM5ZBmZJqyVsPqQu:b-ujuguf) ([raw file](https://github.com/cockroachdb/cockroach/blob/258ba546b6fb581267a26dee67a6f4c154044da0/pkg/sql/rowenc/testutils.go#L1621)):*
> ```Go
> 				},
> 				True: tree.NewStrVal("foo"),
> 				Else: tree.NewStrVal("bar"),
> ```

[nit] you could use RandDatum here too

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61491#-:-MV-IHSR4XlLjIwlM86s:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @mgartner)

___
*[pkg/sql/rowenc/testutils.go, line 1621 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61491#-MUzuM5ZBmZJqyVsPqQt:-MV-IGAxAXibawL9Xui6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/258ba546b6fb581267a26dee67a6f4c154044da0/pkg/sql/rowenc/testutils.go#L1621)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] you could use RandDatum here too
</blockquote></details>

Done.

**Review by mgartner — APPROVED** [review]
> Reviewed 2 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61491)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis)

**Pull request merged**
