### PR TITLE
sql/catalog/lease: handle ambiguous errors

### LINKED ISSUE #73719: roachtest: acceptance/version-upgrade failed
roachtest.acceptance/version-upgrade [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3893901&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3893901&tab=artifacts#/acceptance/version-upgrade) on master @ [22df0a6658a927e7b65dafbdfc9d790500791993](https://github.com/cockroachdb/cockroach/commits/22df0a6658a927e7b65dafbdfc9d790500791993):

```
The test failed on branch=master, cloud=local:
test artifacts and logs in: artifacts/acceptance/version-upgrade/run_1
	versionupgrade.go:473,versionupgrade.go:207,versionupgrade.go:195,acceptance.go:54,acceptance.go:104,test_runner.go:779: 1: expected version 21.2-26, got 21.2
```
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*acceptance/version-upgrade.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-11706

### PR DESCRIPTION
**Pull request by ajwerner**
Before this patch, ambiguous errors from kv during lease acquisitions would
both make their way to the client and would result in a leaked lease. This
leaked lease caused a flakey versionupgrade test.

Along the way I needed to make `kv.AutoCommitError` behave correctly in terms
of error wrapping.

Fixes #73719.

Release note (bug fix): Fixed a bug whereby certain catalog interactions which
occurred concurrently with node failures were not internally retried.

### CODE REVIEW

**Review by postamar — APPROVED** [review]
I'll approve this with the understanding that I only have superficial understanding of what's going on here. I'm not sure what an ambiguous error is, for instance. That being said, I do get the gist of it, and I'm satisfied that merging this patch at least won't worsen things.

> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78529#-:-MzFly2DANyTFUYwmx_i:b1462v3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/sql/catalog/lease/storage.go, line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78529#-MzFk2643s2onT55j1On:-MzFk2643s2onT55j1Oo:b-xp2s1t) ([raw file](https://github.com/cockroachdb/cockroach/blob/99be2cf03f252b421f469b0fb13b21bfa212e2b6/pkg/sql/catalog/lease/storage.go#L109)):*
> ```Go
> 		// desc and expiration is non-empty. In this case, we may have successfully
> 		// written a value to the database, which we'd leak if we did not delete it.
> 		// Note that the expiration is part of the primary key in the table, so we
> ```

Now that is a counterintuitive design choice. For my information, are you aware of any reason why the expiration timestamp would be part of the PK?
___
*[pkg/sql/catalog/lease/storage.go, line 118 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78529#-MzFktDe3RE9SWWr0mLe:-MzFktDe3RE9SWWr0mLf:b-gzdtzb) ([raw file](https://github.com/cockroachdb/cockroach/blob/99be2cf03f252b421f469b0fb13b21bfa212e2b6/pkg/sql/catalog/lease/storage.go#L118)):*
> ```Go
> 			)
> 			if _, err := s.internalExecutor.Exec(
> 				ctx, "lease-insert", txn, deleteLease,
> ```

nit: perhaps replace `lease-insert` with something more descriptive? also would we want to pepper a `log.VEventf` call here as well, to complement the `storage acquired lease` log message below?
___
*[pkg/sql/catalog/lease/storage.go, line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78529#-MzFlcZfAFCnXx1MQqGj:-MzFlcZfAFCnXx1MQqGk:bk53o0u) ([raw file](https://github.com/cockroachdb/cockroach/blob/99be2cf03f252b421f469b0fb13b21bfa212e2b6/pkg/sql/catalog/lease/storage.go#L142)):*
> ```Go
> 			return err
> 		}
> 		log.VEventf(ctx, 2, "storage acquired lease %v@%v", desc, expiration)
> ```

nit: should this be hoisted into the retry loop instead?

**Review by chengxiong-ruan — APPROVED** [review]
@postamar I only saw very few ambiguous error before and never tried to fully understand it myself. but I was able to find something match my superficial understanding before: http://github.com/cockroachdb/cockroach/blob/master/pkg/kv/kvserver/replica_write.go#L327-L327

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78529#-:-MzFxkFc-VsLGz-CVKaG:b-fg8yg0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

**Comment by ajwerner** [comment]
May also fix [#74599](https://github.com/cockroachdb/cockroach/issues/74599).

**Review by ajwerner — COMMENTED** [review]
TFTR!

The ambiguous errors happen after the transaction has send an `EndTransaction` request and then fails to hear a response. At that point, it might have been aborted or it might have been committed and have had its intents resolved. It's ambiguous. We could probably write more kvclient code to recover more gracefully. 

There's a bunch of issues related to this topic:

https://github.com/cockroachdb/cockroach/issues/35170
https://github.com/cockroachdb/cockroach/issues/54867

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78529#-:-MzHx7kO9KHtgRMRbUZ4:b454ywy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)

___
*[pkg/sql/catalog/lease/storage.go, line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78529#-MzFk2643s2onT55j1On:-MzHvrZC0fKQH-PYrNnl:b-22qris) ([raw file](https://github.com/cockroachdb/cockroach/blob/99be2cf03f252b421f469b0fb13b21bfa212e2b6/pkg/sql/catalog/lease/storage.go#L109)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Now that is a counterintuitive design choice. For my information, are you aware of any reason why the expiration timestamp would be part of the PK?
</blockquote></details>

Nope, I have no clue. it's in the original RFC, but it's not explained in the doc or the original feedback: https://github.com/cockroachdb/cockroach/pull/2810

https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20151009_table_descriptor_lease.md
___
*[pkg/sql/catalog/lease/storage.go, line 118 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78529#-MzFktDe3RE9SWWr0mLe:-MzHvqmBB2iJr0qzSTJ5:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/99be2cf03f252b421f469b0fb13b21bfa212e2b6/pkg/sql/catalog/lease/storage.go#L118)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

nit: perhaps replace `lease-insert` with something more descriptive? also would we want to pepper a `log.VEventf` call here as well, to complement the `storage acquired lease` log message below?
</blockquote></details>

done.
___
*[pkg/sql/catalog/lease/storage.go, line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/78529#-MzFlcZfAFCnXx1MQqGj:-MzHwzxb7rE3-qVBLzOB:b-yhrxj9) ([raw file](https://github.com/cockroachdb/cockroach/blob/99be2cf03f252b421f469b0fb13b21bfa212e2b6/pkg/sql/catalog/lease/storage.go#L142)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

nit: should this be hoisted into the retry loop instead?
</blockquote></details>

changed the language of this and added a log line when we finish. These `VEventf` calls should be thought of as free, more or less.

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Pull request merged**
