### PR TITLE
roachtest: uninstall `snapd` for `dmsetup` disk stall tests

### LINKED ISSUE #113283: roachtest: failover/chaos/read-only/lease=expiration failed
roachtest.failover/chaos/read-only/lease=expiration [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12412122?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12412122?buildTab=artifacts#/failover/chaos/read-only/lease=expiration) on release-23.2 @ [1e5be546f219b64b171cb1f39985706b5809d79b](https://github.com/cockroachdb/cockroach/commits/1e5be546f219b64b171cb1f39985706b5809d79b):

```
(disk_stall.go:314).Setup: full command output in run_135422.940103846_n1-10_echo-0-sudo-blockdev.log: COMMAND_PROBLEM: exit status 1
(cluster.go:2176).Run: context canceled
(cluster.go:2176).Run: context canceled
(cluster.go:2176).Run: context canceled
test artifacts and logs in: /artifacts/failover/chaos/read-only/lease=expiration/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=2</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-12412122/failover-chaos-read-only-lease-expiration/1698674061733/1698674223851)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*failover/chaos/read-only/lease=expiration.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-32849

### PR DESCRIPTION
**Pull request by erikgrinaker**
This runs a udev trigger on dmsetup device creation, which may interfere with a dmsetup reload, causing test flakes.

Resolves #113283 🤞.
Epic: none
Release note: None

### CODE REVIEW

**Review by andrewbaptist — COMMENTED** [review]
This is a pretty annoying bug but I'm not sure this is the right place to put this change. 

I think it is a bad idea to leave the state of the cluster different than when the test starts, and by uninstalling here it will do that. I don't think we have any uses for snap right now, but if we do in the future it would be painful to figure out that it only fails "after running any test that uses diskstaller". Also, it's confusing since the install for GCE, Azure, and AWS are all different. I'm not sure they even use the exact same base OS (see https://github.com/cockroachdb/cockroach/commit/3a2153c7ba4138c839906ca75d055967bcf13584). So I can't tell for sure if snapd is installed on all 3. 

Two solutions:
1) Reinstall snapd as part of the `Cleanup` phase of this test so we don't modify the system.
2) Uninstall snapd as part of the "OS install" in roachtest. 

Option 1 would probably be OK, but is a bit of a pain.
Option 2 seems better, but is a little tricky because we have a different mechanism for installing on each platform.

A different option would be to remove the `66-snapd-autoimport.rules` file as that should prevent it from running. That seems a little safer from a forward compatibility perspective.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113311#-:-Ni1RQAY6OojUemel04d:b-221h3c)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @renatolabs and @srosenberg)

**Comment by erikgrinaker** [comment]
>I think it is a bad idea to leave the state of the cluster different than when the test starts

Good point, added a reinstall during `Cleanup`. It's not even clear that this is the problem, so let's not spend too much effort on this.

**Review by andrewbaptist — APPROVED** [review]
:lgtm:

Hopefully this fixes it!

**Pull request merged**
