### PR TITLE
Replace stagnant sigar dependency with a fork that's active.

### PR DESCRIPTION
**Pull request by BramGruneir**
[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4887)

### CODE REVIEW

**Comment by bdarnell** [comment]
LGTM

**Comment by tamird** [comment]
In the commit message, can you include some rationale? does this fork contain some specific bug fixes?

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/context.go, line 37 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4887#-KC7PrpUrC3qYAG2_h5B:-KC7PrpUrC3qYAG2_h5C:1071406401) ([raw file](https://github.com/cockroachdb/cockroach/blob/29a01f20378c33db4773b2176f2c9ed85e783676/server/context.go#L37)):*
can you move these back to where they were?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4887#-:-KC7PvKwfOBpmH_Ix3wS:1026868237)*

**Comment by BramGruneir** [comment]
Sure, done.

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/context.go, line 37 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4887#-KC7PrpUrC3qYAG2_h5B:-KC7rTZFBcRhPuCgORSp:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/29a01f20378c33db4773b2176f2c9ed85e783676/server/context.go#L37)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4887#-:-KC7rW1sB5GeQm1Tb0eY:-84779010)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4887#-:-KC7ugxZ-QiH3er-n9jD:1417088721)*

**Pull request merged**
