### PR TITLE
sql/parser: add timestamptz alias for timestamp data type

### LINKED ISSUE #5865: sql: support `timestamptz` type as alias for `timestamp`?

### PR DESCRIPTION
**Pull request by dt**
Our current 'timestamp' datatype has the same behavior as postgres' timestamptz type:
it accepts strings containing an offset and includes that offset when calculating a utc timestamp, and when returned to the client has an offset (usually 0).

Fixes #5865.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5893)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/parser/sql.y, line 2722 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5893#-KEgXvfqyY0PXmFhGJuR:-KEgXvfqyY0PXmFhGJuS:1293706100) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b8762c130785b6f80258585ae8b08689023d2db/sql/parser/sql.y#L2722)):*
Some of the other `*Type` structures contain a `Name` field so that we can perfectly round-trip the SQL. See `FloatType` and `StringType` for examples. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5893#-:-KEgY54qOGji95jW1JWE:1417088721)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5893#-:-KEgYI01ltZjKpmfFU2X:1417088721)*

**Comment by dt** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/parser/sql.y, line 2722 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5893#-KEgXvfqyY0PXmFhGJuR:-KEgYFeD2oirfW26xu_m:-1891399452) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b8762c130785b6f80258585ae8b08689023d2db/sql/parser/sql.y#L2722)):*
hm, do we need this to roundtrip? As indicated in the test, I was thinking we'd just normalize it to `TIMESTAMP` all the time, at least as long as it is just an alias (in the future we might find a client actually wants a timestamp with no offset returned and it'll actually be different behavior)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5893)*

**Comment by petermattis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/parser/sql.y, line 2722 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5893#-KEgXvfqyY0PXmFhGJuR:-KEgZNvmcc6wX_9p9Rej:1819994396) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b8762c130785b6f80258585ae8b08689023d2db/sql/parser/sql.y#L2722)):*
I don't have a specific use case for needing the round-tripping, yet I think we should err on the side of doing so when it isn't difficult. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5893)*

**Comment by dt** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/parser/sql.y, line 2722 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5893#-KEgXvfqyY0PXmFhGJuR:-KEgaSTI30ecY0qsQMKE:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b8762c130785b6f80258585ae8b08689023d2db/sql/parser/sql.y#L2722)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5893)*

**Comment by petermattis** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/parser/sql.y, line 2722 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5893#-KEgXvfqyY0PXmFhGJuR:-KEgaxW0BpIlmVkkmAa6:402804248) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b8762c130785b6f80258585ae8b08689023d2db/sql/parser/sql.y#L2722)):*
I was imagining `TimestampType{Name: "TIMESTAMPTZ"}`, but this works too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5893)*

**Pull request merged**
