### PR TITLE
sql: adjust physical planning heuristics around scans, sorts, and aggregations

### LINKED ISSUE #61450: sql: consider changing the physical planning heuristics for scans with no limits
In [this comment](https://github.com/cockroachlabs/support/issues/850#issuecomment-786091902) Radu raised a question whether we should recommend the distribution of scans with no limits (this would change the meaning of `distsql=auto` to be more like `distsql=on`, possibly making the former redundant). We quickly discussed it in our team meeting, and Jordan suggested checking the performance of point lookups. That [showed](https://github.com/cockroachlabs/support/issues/850#issuecomment-790268566) noticeable perf hit, so we don't want to just take up the idea, and we might want to be more sophisticated (like introducing a threshold for which we start recommending the distribution that would take the estimated row count into account).

Jira issue: CRDB-3016

### LINKED ISSUE #75178: sql: should distribute large constrained scans
We currently don't recommend distributing constrained scans, even if they are very large:
https://github.com/cockroachdb/cockroach/blob/d990758125a1e323ff28cb8ea661f8d1a97ea2e7/pkg/sql/distsql_physical_planner.go#L536

I think we should distribute anything that has to scan a large amount of data. A sample case is in https://github.com/cockroachdb/cockroach/issues/74736#issuecomment-1016073783 (although the large number of spans in the constraint is problematic there).

CC @yuzefovich

Jira issue: CRDB-12497

### LINKED ISSUE #135898: sql: turning off DistSQL gives 7.5% qps boost on oltp_read_only (1.7% qps on oltp_read_write)
In an ad-hoc experiment, changing `sql.defaults.distsql` to `off` resulted in a 7.5% improvement in qps, from around 40k to around 43k.[^1]

DistSQL is likely used for the sysbench "range" queries, which scan 100 consecutive keys. It likely makes no sense to use DistSQL here, as the overhead does not get amortized. There are no unbounded scans here either.

Epic: CRDB-42584

[^1]: https://cockroachlabs.slack.com/archives/C07P0CNLP51/p1732192681032459?thread_ts=1732092976.359539&cid=C07P0CNLP51

Jira issue: CRDB-44780

### PR DESCRIPTION
**Pull request by yuzefovich**
This PR adjusts the physical planning heuristics for scans, sorts, and aggregations so that the plan distribution is forced if a large set of rows (at least 10k or 1k, depending on the context, adjustable via session variables) is processed. We now:
- will **stop** distributing _small_ full scans, sorts, and aggregations
- will **start** distributing _large_ constrained scans and top K sorts.

See each commit for details.

Fixes: #61450.
Fixes: #75178.
Fixes: #135898.

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
:lgtm: Nice improvements!

> Reviewed 21 of 21 files at r1, 7 of 7 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137072#-:-ODnBZXt2zZVVjavJ4Hn:bdyovjk)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[`pkg/sql/opt/exec/execbuilder/testdata/distsql_auto_mode` line 92 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/137072#-ODnBTWqCOqDJalEGT99:-ODnBTWqCOqDJalEGT9A:bhttcxi) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd9f721626ae4cfbedcb9492e8dc5ef1b5276aa2/pkg/sql/opt/exec/execbuilder/testdata/distsql_auto_mode#L92)):*
> ```
> distribution: local
> 
> # Soft limit in a large scan - don't distribute.
> ```

[nit] The comment says `don't distribute`, but the query is distributed.
___
*[`pkg/sql/exec_util.go` line 1937 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137072#-ODn1sJe9VyC711BSBz-:-ODn1sJe9VyC711BSBz0:b-72r09r) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b3a38163155227b78110811d9e0974882d9ff04/pkg/sql/exec_util.go#L1937)):*
> ```Go
> 	plan planMaybePhysical,
> 	distSQLVisitor *distSQLExprCheckVisitor,
> 	sd *sessiondata.SessionData,
> ```

[nit] `distSQLMode` lives on the `SessionData`, so can be removed as an parameter.
___
*[`pkg/sql/distsql_spec_exec_factory.go` line 834 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/137072#-ODn8oUDERigcO5sL8XL:-ODn8oUDERigcO5sL8XM:b-u275l5) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdbe952a7ad5b386191965b91ee6cba5aa38e306/pkg/sql/distsql_spec_exec_factory.go#L834)):*
> ```Go
> 	ordering exec.OutputOrdering,
> 	alreadyOrderedPrefix int,
> 	estimatedInputRowCount uint64,
> ```

Do we make the decision about whether to distribute before this point? Is that why the row count estimate isn't needed?

**Review by yuzefovich — COMMENTED** [review]
I did 5 runs of sysbench before and after this change (with `distsql=auto`). Here are the numbers (I lost the 2nd "before" run):
- before: 21997, ?, 20865, 20940, 20901. Average: **21176**
- after: 21742, 21902, 22524, 22450, 22487. Average: **22221** which is **4.93% better** than above.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137072#-:-ODnj1WbBv1u4WFokqdO:b-qry15i)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @michae2)

___
*[`pkg/sql/distsql_spec_exec_factory.go` line 834 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/137072#-ODn8oUDERigcO5sL8XL:-ODnaMQdCLiPNUpJ-SSZ:bs3wwl2) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdbe952a7ad5b386191965b91ee6cba5aa38e306/pkg/sql/distsql_spec_exec_factory.go#L834)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Do we make the decision about whether to distribute before this point? Is that why the row count estimate isn't needed?
</blockquote></details>

No, I think we currently completely ignore this information in the distsql spec factory for sort and top K. In the current state, this factory doesn't consider the plan as a whole to decide whether it's worth distributing it or not; instead, it makes a "local" decision for each logical operator based on the previous physical plan stage and the operator info. In case of sorts, that "local decision" is to not change the distribution of the plan (i.e. we keep it the same as of the previous stage). I left a couple of TODOs.
___
*[`pkg/sql/exec_util.go` line 1937 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137072#-ODn1sJe9VyC711BSBz-:-ODndM2r2ucGyN6hY0EX:b-hzn0vv) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b3a38163155227b78110811d9e0974882d9ff04/pkg/sql/exec_util.go#L1937)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] `distSQLMode` lives on the `SessionData`, so can be removed as an parameter.
</blockquote></details>

I just added another commit to do this - there was a minor difficulty that with pausable portals we might use distsql=off even if the session allows it.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/distsql_auto_mode` line 92 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/137072#-ODnBTWqCOqDJalEGT99:-ODni2Fx3GnCz_-tRzQv:b-q5bsbs) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd9f721626ae4cfbedcb9492e8dc5ef1b5276aa2/pkg/sql/opt/exec/execbuilder/testdata/distsql_auto_mode#L92)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] The comment says `don't distribute`, but the query is distributed.
</blockquote></details>

The comment was describing the desired state and was confusing. Removed it and updated the TODO.

**Review by DrewKimball — APPROVED** [review]
> Reviewed 1 of 22 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137072)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2)

**Review by mgartner — APPROVED** [review]
:lgtm: Thanks for addressing this!

> Reviewed 22 of 22 files at r4, 15 of 15 files at r5, 7 of 7 files at r6, 9 of 9 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137072#-:-ODql76aAKRHfX4NJCMx:btkgntc)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @michae2, and @yuzefovich)

___
*[`pkg/sql/opt/exec/execbuilder/testdata/distsql_auto_mode` line 52 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/137072#-ODqkx6yC8kNGSo-8BEO:-ODqkx6yC8kNGSo-8BEP:bpz8kaq) ([raw file](https://github.com/cockroachdb/cockroach/blob/04945677e8a62a6bb5606c1406c65eb20e7731cb/pkg/sql/opt/exec/execbuilder/testdata/distsql_auto_mode#L52)):*
> ```
> distribution: local
> 
> # Force full table scan of a small table to be distributed.
> ```

nit: Do we need a case for a full table scan of a large table? I guess it's the same code path as "full table scan with no stats" which is tested above?
___
*[`pkg/sql/conn_executor_exec.go` line 1910 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/137072#-ODqhyyO24AYUidSloch:-ODqhyyO24AYUidSloci:b-gpx1ca) ([raw file](https://github.com/cockroachdb/cockroach/blob/9037e545da4f7f601138fd2a0894312e59052988/pkg/sql/conn_executor_exec.go#L1910)):*
> ```Go
> 			len(planner.curPlan.checkPlans) == 0 &&
> 			len(planner.curPlan.triggers) == 0 {
> 			// We only allow non-distributed plan for pausable portals.
> ```

nit: This comment reads as if non-distributed plans are not allowed when there is no pausable portal. "We don't allow a distributed plan for pausable portals." would be more clear.

**Review by yuzefovich — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137072#-:-ODrNAGQAzY9ChXlhoE6:b-tlx7ko)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball, @mgartner, and @michae2)

___
*[`pkg/sql/opt/exec/execbuilder/testdata/distsql_auto_mode` line 52 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/137072#-ODqkx6yC8kNGSo-8BEO:-ODrMH_t8aP-yDWwvpm_:b-s6krr3) ([raw file](https://github.com/cockroachdb/cockroach/blob/04945677e8a62a6bb5606c1406c65eb20e7731cb/pkg/sql/opt/exec/execbuilder/testdata/distsql_auto_mode#L52)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: Do we need a case for a full table scan of a large table? I guess it's the same code path as "full table scan with no stats" which is tested above?
</blockquote></details>

Kinda yes, but I added another test case for this.

**Pull request merged**
