### PR TITLE
sql: support geospatial index for index recommendation indexrec

### LINKED ISSUE #80934: opt: add geospatial inverted index recommendations
There should be geospatial inverted index recommendations for queries that use index accelerated geospatial functions:

https://github.com/cockroachdb/cockroach/blob/6f85a0b6586dd59eca12468de40ec694cbf3ab71/pkg/geo/geoindex/geoindex.go#L36-L51

For example, the query below has no recommendation:

```
defaultdb> CREATE TABLE t (k INT PRIMARY KEY, g GEOMETRY);

defaultdb> EXPLAIN SELECT k FROM t WHERE st_covers(g, 'POINT(0 0 0 0)');
                                                  info
--------------------------------------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • filter
  │ filter: st_covers(g, '01010000C00000000000000000000000000000000000000000000000000000000000000000')
  │
  └── • scan
        missing stats
        table: t@t_pkey
        spans: FULL SCAN
(10 rows)
```

But if an index is added, a query plan using it is chosen because it is more efficient:

```
defaultdb> CREATE INVERTED INDEX ON t(g);
CREATE INDEX

defaultdb> EXPLAIN SELECT k FROM t WHERE st_covers(g, 'POINT(0 0 0 0)');
                                                  info
--------------------------------------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • filter
  │ filter: st_covers(g, '01010000C00000000000000000000000000000000000000000000000000000000000000000')
  │
  └── • index join
      │ table: t@t_pkey
      │
      └── • inverted filter
          │ inverted column: g_inverted_key
          │ num spans: 31
          │
          └── • scan
                missing stats
                table: t@t_g_idx
                spans: 31 spans
(17 rows)
```

Jira issue: CRDB-15446

Epic: CRDB-14532

### PR DESCRIPTION
**Pull request by wenyihu6**
Previously, we did not consider geospatial inverted index or box2d index for
index recommendation. But for queries that use index-accelerated geospatial
functions or box2d operations, the spatial index should be recommended. This PR
added spatial index to index candidates.

Fixes: https://github.com/cockroachdb/cockroach/issues/80934

Release note (sql change): index recommendations are now supported for spatial indexes

### CODE REVIEW

**Review by michae2 — CHANGES_REQUESTED** [review]
Nice job! This is looking great! I love all the testcases! :100: :rocket:

When we're getting close to done with this PR, I'll ask you to squash all of the commits into a single git commit. (You can do that now or later, your choice.)

> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82293#-:-N3VExGs6ga87sCr3JZV:b-ks0wom)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @wenyihu6)

___
*[`pkg/sql/opt/indexrec/index_candidate_set.go` line 384 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/82293#-N3VFQ0h7xtdeK-jMqNW:-N3VFQ0h7xtdeK-jMqNX:b325ok) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3f00b37fbd51d3da74b2c29331691fad19c8ba9/pkg/sql/opt/indexrec/index_candidate_set.go#L384)):*
> ```Go
> 	}
> 
> 	// Note: Indexes on spatial columns are now added for index recommendation.
> ```

nit: I think you can remove this comment. (But I'm glad it is true! :slightly_smiling_face:)
___
*[`pkg/sql/opt/indexrec/index_candidate_set.go` line 410 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/82293#-N3VEMcI8WIdNLQNb8YD:-N3VEMcJBuhroGz6KLYs:bk4wkcd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3f00b37fbd51d3da74b2c29331691fad19c8ba9/pkg/sql/opt/indexrec/index_candidate_set.go#L410)):*
> ```Go
> func (ics *indexCandidateSet) addGeoSpatialIndexes(expr opt.Expr, indexCandidates map[cat.Table][][]cat.IndexColumn) {
> 	switch expr := expr.(type) {
> 	case *memo.FunctionExpr:
> ```

From looking at `GetGeoIndexRelationship` in `pkg/sql/opt/invertedidx/geo.go:49` it looks like there are two other expression types that can also be index-accelerated by a geospatial inverted index: `*memo.BBoxCoversExpr` and `*memo.BBoxIntersectsExpr`. Let's add those expression types to this function as well as `categorizeIndexCandidates`. (Sorry I didn't notice this sooner!)

**Review by rytaft — COMMENTED** [review]
Awesome! I agree that the test cases are great! Just a few nits below in addition to @michae2's comments

> Reviewed 2 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82293#-:-N3aLDM0D0P5cJIUfYWz:b-pjh3de)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, and @wenyihu6)

___
*[`-- commits` line 8 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/82293#-N3aLJu66NXJ278Esp0W):*
nit: change the commit message to look more like the PR message

nit: add a release note, e.g., Release note (sql change): index recommendations are now supported for spatial inverted indexes.
___
*[`pkg/sql/opt/indexrec/index_candidate_set.go` line 415 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/82293#-N3aLuMw7Ha7qUpDK9yK:-N3aLuMw7Ha7qUpDK9yL:b-t6mcqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/d65fccf4423934eee886bedead31f9f7628f73d3/pkg/sql/opt/indexrec/index_candidate_set.go#L415)):*
> ```Go
> 
> // AddGeoSpatialIndexes is used to add single-column GIN indexes to inverted candidates for
> // spatial functions that can be index-accelerated.
> ```

nit: comments should be <= 80 columns wide

nit: we tend to use the word "inverted" instead of "GIN" throughout the codebase. GIN is only supported for compatibility with Postgres.

nit: this function isn't specifically adding to `invertedCandidates` -- it adds to whatever indexCandidates map was passed in.
___
*[`pkg/sql/opt/indexrec/index_candidate_set.go` line 423 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/82293#-N3aO6vrDN1_Rq4abD52:-N3aO4jv27K3mhyJojsY:bko65zh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d65fccf4423934eee886bedead31f9f7628f73d3/pkg/sql/opt/indexrec/index_candidate_set.go#L423)):*
> ```Go
> 		if ok {
> 			// Add arguments of the spatial function to inverted indexes
> 			for i := range expr.Args {
> ```

nit: since you're using the `Child` method below, I think it would be better to also use `ChildCount` here. For example:
`for i, n := 0, expr.Args.ChildCount(); i < n; i++ {`
___
*[`pkg/sql/opt/indexrec/index_candidate_set.go` line 417 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/82293#-N3aPeiPBKvYymC8Mxyh:-N3aPeiPBKvYymC8Mxyi:buqahex) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b07bb4bb298607dc51452c15c300eb367dae244/pkg/sql/opt/indexrec/index_candidate_set.go#L417)):*
> ```Go
> 	switch expr := expr.(type) {
> 	case *memo.FunctionExpr:
> 		// Ensure that the function is a spatial function AND can be index-accelerated
> ```

nit: end comments with a period. (here and in other comments below)

**Review by rytaft — APPROVED** [review]
:lgtm: once you address @michae2's feedback and update the commit message. Nice work!

> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82293#-:-N3aagafE7XNGPI-wuJI:b-9zgqpj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner, @michae2, and @wenyihu6)

___
*[`-- commits` line 4 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/82293#-N3a_dKKBJ3ZXgxORiSk):*
You can just make the commit message match the PR message exactly. I think the docs team also relies on having the release note included in the commit message

**Review by michae2 — COMMENTED** [review]
This is looking great.

I tried playing with it a bit, and couldn't get any of the examples from the test to actually show a recommendation. If you add a few `index-recommendations` testcases to match the `index-candidates` testcases, do any of them show recommendations? :thinking:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82293#-:-N3asIbXCRxYnA27nim1:b-e3wa9s)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @wenyihu6)

___
*[`-- commits` line 11 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/82293#-N3atI1u7njL6S7MXU1G):*
nit: I think you can leave off "and box2d indexes".
___
*[`pkg/sql/opt/indexrec/index_candidate_set.go` line 413 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/82293#-N3apZAEBhkkZnOjwIbR:-N3apZAEBhkkZnOjwIbS:b-7aptha) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4b3ba0e8c5df3ff5af4c0e7f2828df90752d819/pkg/sql/opt/indexrec/index_candidate_set.go#L413)):*
> ```Go
> // AddGeoSpatialIndexes is used to add single-column indexes to indexCandidates
> // for spatial functions that can be index-accelerated.
> func (ics *indexCandidateSet) addGeoSpatialIndexes(expr opt.Expr, indexCandidates map[cat.Table][][]cat.IndexColumn) {
> ```

Looks like a linter wants you to wrap this function signature. Here's the output from TeamCity:

```
------- Stdout: -------
=== RUN   TestLint/TestCrlfmt
=== PAUSE TestLint/TestCrlfmt
=== CONT  TestLint/TestCrlfmt
=== CONT  TestLint/TestCrlfmt
    lint_test.go:1372:
        diff -u old/sql/opt/indexrec/index_candidate_set.go new/sql/opt/indexrec/index_candidate_set.go
        --- old/sql/opt/indexrec/index_candidate_set.go  2022-06-02 23:22:26.562030586 +0000
        +++ new/sql/opt/indexrec/index_candidate_set.go  2022-06-02 23:22:26.562030586 +0000
        @@ -410,7 +410,9 @@
         // AddGeoSpatialIndexes is used to add single-column indexes to indexCandidates
         // for spatial functions that can be index-accelerated.
        -func (ics *indexCandidateSet) addGeoSpatialIndexes(expr opt.Expr, indexCandidates map[cat.Table][][]cat.IndexColumn) {
        +func (ics *indexCandidateSet) addGeoSpatialIndexes(
        +  expr opt.Expr, indexCandidates map[cat.Table][][]cat.IndexColumn,
        +) {
           switch expr := expr.(type) {
           case *memo.FunctionExpr:
             // Ensure that the function is a spatial function AND can be index-accelerated.
    lint_test.go:1387: run the following to fix your formatting:
        bin/crlfmt "-fast" "-ignore" "\\.(pb(\\.gw)?)|(\\.[eo]g)\\.go|/testdata/|^sql/parser/sql\\.go$|_generated(_test)?\\.go$" "-tab" "2" "-w" "/go/src/github.com/cockroachdb/cockroach/pkg"
        Don't forget to add amend the result to the correct commits.
    --- FAIL: TestLint/TestCrlfmt (6.48s)
```

**Review by michae2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82293)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @wenyihu6)

___
*[`pkg/sql/opt/indexrec/hypothetical_index.go` line 209 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/82293#-N3wcxhG-kBp6m6GHYfM:-N3wcxhG-kBp6m6GHYfN:boa8gxd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e29997c210686faa7d7433e5b3455ef2a7b53b23/pkg/sql/opt/indexrec/hypothetical_index.go#L209)):*
> ```Go
> 
> // GeoConfig is part of the cat.Index interface.
> // TODO(nehageorge): Add support for spatial index recommendations.
> ```

Nice catch!

nit: You can remove this `TODO` comment. :slightly_smiling_face:
___
*[`pkg/sql/opt/indexrec/hypothetical_table.go` line 181 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/82293#-N3wal9c1DM4CIxOfFH6:-N3wal9c1DM4CIxOfFH7:b86tchk) ([raw file](https://github.com/cockroachdb/cockroach/blob/e29997c210686faa7d7433e5b3455ef2a7b53b23/pkg/sql/opt/indexrec/hypothetical_table.go#L181)):*
> ```Go
> 		ht.ColumnCount(),
> 		tree.Name(string(invertedSourceCol.ColName())+"_inverted_key"),
> 		invertedSourceCol.DatumType(),
> ```

From looking at `InvertedColumnKeyType` in `pkg/sql/catalog/descpb/index.go` it seems like this should be `types.EncodedKey` rather than `types.Bytes`.

**Review by mgartner — APPROVED** [review]
:lgtm: Great job!

> Reviewed 1 of 2 files at r12, 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82293#-:-N3yYdOD8dXfOhP3CnNS:bgtqnie)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @michae2 and @wenyihu6)

___
*[`-- commits` line 11 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/82293#-N3atI1u7njL6S7MXU1G):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: I think you can leave off "and box2d indexes".
</blockquote></details>

Also, we aim to wrap git commit messages at 72 characters: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages#GitCommitMessages-Commitdescription
___
*[`-- commits` line 15 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/82293#-N3yUnM0EQeTaA-XvkV2):*
nit: remove these extra titles from the commit message - they aren't necessary.
___
*[`pkg/sql/opt/indexrec/index_candidate_set.go` line 413 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/82293#-N3yYDHj2fGkN0Cj3oTW:-N3yYDHk47XXCHX0DOXh:b-txj2ho) ([raw file](https://github.com/cockroachdb/cockroach/blob/98d8a9048a4f7fcb574e62c27d98a016ad360f2f/pkg/sql/opt/indexrec/index_candidate_set.go#L413)):*
> ```Go
> // AddGeoSpatialIndexes is used to add single-column indexes to indexCandidates
> // for spatial functions that can be index-accelerated.
> func (ics *indexCandidateSet) addGeoSpatialIndexes(expr opt.Expr, indexCandidates map[cat.Table][][]cat.IndexColumn) {
> ```

The caller of this function has already asserted the type of the expr as `*memo.FunctionExpr`, so you can change the type of `expr` in the function signature to `*memo.FunctionExpr`. Then you can remove the switch statement inside this function.
___
*[`pkg/sql/opt/indexrec/testdata/geospatial-index-candidates-recommendations` line 804 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/82293#-N3yWSs93E2ACCCM1EKu:-N3yWACg6GTr73cjzLrR:b5dp0b7) ([raw file](https://github.com/cockroachdb/cockroach/blob/98d8a9048a4f7fcb574e62c27d98a016ad360f2f/pkg/sql/opt/indexrec/testdata/geospatial-index-candidates-recommendations#L804)):*
> ```
> index recommendations: 1
> 1. type: index creation
>    SQL command: CREATE INDEX ON t2 (bbox1) STORING (k, i, s, geom1, geog1, bbox2, geom2, geog2, inet1);
> ```

Maybe you should add a comment above this test to explain that the recommendation is a non-inverted index because an inverted index on `geom1` cannot be used because the left-hand side of the `~` operator is not a constant?
___
*[`pkg/sql/opt/indexrec/testdata/geospatial-index-candidates-recommendations` line 961 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/82293#-N3yWkEr-Dkamr3_-6P2:-N3yWkEr-Dkamr3_-6P3:b-j08jfn) ([raw file](https://github.com/cockroachdb/cockroach/blob/98d8a9048a4f7fcb574e62c27d98a016ad360f2f/pkg/sql/opt/indexrec/testdata/geospatial-index-candidates-recommendations#L961)):*
> ```
>       └── inet1:10 && inet1:10 [outer=(10), immutable]
> 
> # Part 3: For spatial functions that do not use index accelerated geospatial functions, do not recommend geospatial index.
> ```

nit: wrap comments to 80 characters
___
*[`pkg/sql/opt/indexrec/testdata/geospatial-index-candidates-recommendations` line 1081 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/82293#-N3yX8iR1KnSxZJfky8y:-N3yX8iR1KnSxZJfky8z:bx91l9u) ([raw file](https://github.com/cockroachdb/cockroach/blob/98d8a9048a4f7fcb574e62c27d98a016ad360f2f/pkg/sql/opt/indexrec/testdata/geospatial-index-candidates-recommendations#L1081)):*
> ```
> 
> index-recommendations
> SELECT * FROM t2 WHERE st_overlaps(geom1, geom2) AND k = 2
> ```

If you use a constant for one argument of `st_overlaps` you should get a more interesting recommendation like, `CREATE INVERTED INDEX ON t2 (k, geom1) ...`, which I think is what you are trying to test here and in the test casts below.

**Review by michae2 — APPROVED** [review]
:lgtm_strong: Nice work! :tada:

I have one question below, but it doesn't need to block merging. This looks good!

> Reviewed 2 of 3 files at r13, 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82293#-:-N3zWN7I8xRAmGi0VH6Q:b3njlbf)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @wenyihu6)

___
*[`pkg/sql/opt/indexrec/hypothetical_table.go` line 181 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/82293#-N3wal9c1DM4CIxOfFH6:-N3zTnJlCVBH1dlIDfws:by1pi1h) ([raw file](https://github.com/cockroachdb/cockroach/blob/e29997c210686faa7d7433e5b3455ef2a7b53b23/pkg/sql/opt/indexrec/hypothetical_table.go#L181)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

From looking at `InvertedColumnKeyType` in `pkg/sql/catalog/descpb/index.go` it seems like this should be `types.EncodedKey` rather than `types.Bytes`.
</blockquote></details>

@wenyihu6 I'm a little confused, could you explain why this change was necessary? It looks like [in the test catalog we use the column type](https://github.com/cockroachdb/cockroach/blob/abc8afd8a244f2c6e85cdfe50119ef18f72602e2/pkg/sql/opt/testutils/testcat/create_table.go#L1038) but [in the real catalog we always use `types.EncodedKey`](https://github.com/cockroachdb/cockroach/blob/abc8afd8a244f2c6e85cdfe50119ef18f72602e2/pkg/sql/opt_catalog.go#L891). Without knowing more, I'd be inclined to use `types.EncodedKey`. But maybe I just don't understand what is going on here.

**Comment by mgartner** [comment]
*[`pkg/sql/opt/indexrec/hypothetical_table.go` line 181 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/82293#-N3wal9c1DM4CIxOfFH6:-N3zk1Ag7kzu6KJ4WKMi:brgwexp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e29997c210686faa7d7433e5b3455ef2a7b53b23/pkg/sql/opt/indexrec/hypothetical_table.go#L181)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

@wenyihu6 I'm a little confused, could you explain why this change was necessary? It looks like [in the test catalog we use the column type](https://github.com/cockroachdb/cockroach/blob/abc8afd8a244f2c6e85cdfe50119ef18f72602e2/pkg/sql/opt/testutils/testcat/create_table.go#L1038) but [in the real catalog we always use `types.EncodedKey`](https://github.com/cockroachdb/cockroach/blob/abc8afd8a244f2c6e85cdfe50119ef18f72602e2/pkg/sql/opt_catalog.go#L891). Without knowing more, I'd be inclined to use `types.EncodedKey`. But maybe I just don't understand what is going on here.
</blockquote></details>

I think the test catalog is wrong, though I'm curious why that hasn't caused issues. 

`type.EncodedKey` is a recent addition to better describe the type of inverted columns. We previously used `type.Bytes`, but that was less than ideal. There's some more context here: https://github.com/cockroachdb/cockroach/pull/77501

I _think_ in this case we should use `types.EncodedKey`.

**Review by wenyihu6 — COMMENTED** [review]
> :lgtm_strong: Nice work! 🎉
> 
> I have one question below, but it doesn't need to block merging. This looks good!
> 
> > Reviewed 2 of 3 files at r13, 2 of 2 files at r15, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82293#-:-N3zWN7I8xRAmGi0VH6Q:b3njlbf)_ status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @wenyihu6)
> 
> _[`pkg/sql/opt/indexrec/hypothetical_table.go` line 181 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/82293#-N3wal9c1DM4CIxOfFH6:-N3zTnJlCVBH1dlIDfws:by1pi1h) ([raw file](https://github.com/cockroachdb/cockroach/blob/e29997c210686faa7d7433e5b3455ef2a7b53b23/pkg/sql/opt/indexrec/hypothetical_table.go#L181)):_
> 
> Previously, michae2 (Michael Erickson) wrote…
> @wenyihu6 I'm a little confused, could you explain why this change was necessary? It looks like [in the test catalog we use the column type](https://github.com/cockroachdb/cockroach/blob/abc8afd8a244f2c6e85cdfe50119ef18f72602e2/pkg/sql/opt/testutils/testcat/create_table.go#L1038) but [in the real catalog we always use `types.EncodedKey`](https://github.com/cockroachdb/cockroach/blob/abc8afd8a244f2c6e85cdfe50119ef18f72602e2/pkg/sql/opt_catalog.go#L891). Without knowing more, I'd be inclined to use `types.EncodedKey`. But maybe I just don't understand what is going on here.

I was reading the code in [`pkg/sql/opt/testutils/testcat/create_table.go`](https://github.com/cockroachdb/cockroach/blob/abc8afd8a244f2c6e85cdfe50119ef18f72602e2/pkg/sql/opt/testutils/testcat/create_table.go#L1039), and it was using the data type of the inverted column instead. If inverted column should be `types.EncodedKey`, I will also need to add another statement in [`GeoConfig`](https://github.com/wenyihu6/cockroach/blob/5c2da11ea73b45bd19ddff18d1b8f19324b483e9/pkg/sql/opt/indexrec/hypothetical_index.go#L211) to find the type of the table column referenced by the inverted index.

**Comment by mgartner** [comment]
*[`pkg/sql/opt/indexrec/hypothetical_table.go` line 181 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/82293#-N3wal9c1DM4CIxOfFH6:-N3zqQvnCFxKqyP3fe2o:b-m6gdeg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e29997c210686faa7d7433e5b3455ef2a7b53b23/pkg/sql/opt/indexrec/hypothetical_table.go#L181)):*
In the opt catalog (the _real_ catalog), we set the inverted column type in an index to `type.EncodedKey`:

https://github.com/cockroachdb/cockroach/blob/32622e1b18030bd52529841ec1bb280a5683d5cb/pkg/sql/opt_catalog.go#L902

https://github.com/cockroachdb/cockroach/blob/49b6ca8bf75f8d30302f16f1e84f8fc5b212bb0e/pkg/sql/catalog/table_elements.go#L181-L186

So that confirms that it should be `EncodedKey` here.

> I will need to add another statement in GeoConfig to find the type of the column on the table referenced by the inverted index.

To get the type of the inverted column's source column, you can do something like this:

```go
	srcCol := hi.tab.Column(hi.InvertedColumn().InvertedSourceColumnOrdinal())
	srcCol.DatumType()
```

**Comment by mgartner** [comment]
*[`pkg/sql/opt/indexrec/hypothetical_table.go` line 181 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/82293#-N3wal9c1DM4CIxOfFH6:-N3zvq9h7ObxGJno7Fri:bl7jfuk) ([raw file](https://github.com/cockroachdb/cockroach/blob/e29997c210686faa7d7433e5b3455ef2a7b53b23/pkg/sql/opt/indexrec/hypothetical_table.go#L181)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

In the opt catalog (the _real_ catalog), we set the inverted column type in an index to `type.EncodedKey`:

https://github.com/cockroachdb/cockroach/blob/32622e1b18030bd52529841ec1bb280a5683d5cb/pkg/sql/opt_catalog.go#L902

https://github.com/cockroachdb/cockroach/blob/49b6ca8bf75f8d30302f16f1e84f8fc5b212bb0e/pkg/sql/catalog/table_elements.go#L181-L186

So that confirms that it should be `EncodedKey` here.

> I will need to add another statement in GeoConfig to find the type of the column on the table referenced by the inverted index.

To get the type of the inverted column's source column, you can do something like this:

```go
	srcCol := hi.tab.Column(hi.InvertedColumn().InvertedSourceColumnOrdinal())
	srcCol.DatumType()
```


</blockquote></details>

FYI I fixed the problem in the test catalog in a separate PR: https://github.com/cockroachdb/cockroach/pull/82547

**Review by mgartner — APPROVED** [review]
> Reviewed 2 of 2 files at r15, 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82293)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @michae2 and @wenyihu6)

___
*[`pkg/sql/opt/indexrec/testdata/geospatial-index-candidates-recommendations` line 236 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/82293#-N3zxDrG1YeRdtPP0WBg:-N3zxDrG1YeRdtPP0WBh:byo53io) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ce9c32e715040eaa20bb54cfc988fcaf19265ee/pkg/sql/opt/indexrec/testdata/geospatial-index-candidates-recommendations#L236)):*
> ```
>  (geom2)
> 
> # Note: geom1 or geom2 is not chosen for the query plan. When both arguments of
> ```

nit: **An index on** geom1 or geom2...
___
*[`pkg/sql/opt/indexrec/testdata/geospatial-index-candidates-recommendations` line 802 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/82293#-N3zxJ3O0GEMODGHXiCd:-N3zxJ3O0GEMODGHXiCe:b-xtwm6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ce9c32e715040eaa20bb54cfc988fcaf19265ee/pkg/sql/opt/indexrec/testdata/geospatial-index-candidates-recommendations#L802)):*
> ```
> # Part 2: Geospatial indexes should be added for Box2d operators and functions.
> 
> # Note: geom1 is not chosen for the query plan. When both arguments of functions
> ```

nit: **An index on** geom1...
___
*[`pkg/sql/opt/indexrec/testdata/geospatial-index-candidates-recommendations` line 832 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/82293#-N3zxOjn3a7qSRZUSRqi:-N3zxOjn3a7qSRZUSRqj:b-xtwm6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ce9c32e715040eaa20bb54cfc988fcaf19265ee/pkg/sql/opt/indexrec/testdata/geospatial-index-candidates-recommendations#L832)):*
> ```
>       └── bbox1:6 ~ geom1:4 [outer=(4,6), immutable, constraints=(/4: (/NULL - ]; /6: (/NULL - ])]
> 
> # Note: geom1 is chosen for the query plan here. If one of the arguments is a
> ```

nit: **An index on** geom1...

**Review by mgartner — APPROVED** [review]
> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82293)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @michae2 and @wenyihu6)

**Pull request merged**
