### PR TITLE
sql: Replace IntVal and NumVal with ConstVal

### PR DESCRIPTION
**Pull request by nvb**
This change uses the `go/constant` package to parse, operate on, and
evaluate all constant numeric values in our parser.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6280)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 12 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[sql/values_test.go, line 46 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6280#-KGCzOXqiwJD6cz5PHU5:-KGCzOXqiwJD6cz5PHU6:554389827) ([raw file](https://github.com/cockroachdb/cockroach/blob/544d737dd00f525d36820e2f86a6c8e09631ab77/sql/values_test.go#L46)):*
Perhaps add `parser.MakeConstIntVal()` and `parser.MakeConstFloatVal()`.

---

*[sql/parser/expr.go, line 280 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6280#-KGDPue7xPBHGnlyq5ZX:-KGDPue8WSPN7V0KZeaJ:-868480704) ([raw file](https://github.com/cockroachdb/cockroach/blob/544d737dd00f525d36820e2f86a6c8e09631ab77/sql/parser/expr.go#L280)):*
This comment doesn't make a lot of sense. Can you change it so it describes what `ResolvedType` actually is?

---

*[sql/parser/normalize.go, line 325 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6280#-KGDQze3_X-AjAc6EHcl:-KGDQze3_X-AjAc6EHcm:526855915) ([raw file](https://github.com/cockroachdb/cockroach/blob/544d737dd00f525d36820e2f86a6c8e09631ab77/sql/parser/normalize.go#L325)):*
Now that we're using arbitrary precision math for constants, can't we address this `TODO`? In fact, can't we get rid of this special case below completely?

---

*[sql/parser/scan.go, line 558 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6280#-KGDVu0j4hVCF45L8Oyx:-KGDVu0j4hVCF45L8Oyy:1887674721) ([raw file](https://github.com/cockroachdb/cockroach/blob/544d737dd00f525d36820e2f86a6c8e09631ab77/sql/parser/scan.go#L558)):*
I don't see tests for this error or the one above about `constant float`.

`s/literal string/literal/g` as the literal isn't actually a string in the input. 

---

*[sql/parser/scan_test.go, line 274 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6280#-KGDW9Lm2vPT-MY1gKY6:-KGDW9Lm2vPT-MY1gKY7:1862435988) ([raw file](https://github.com/cockroachdb/cockroach/blob/544d737dd00f525d36820e2f86a6c8e09631ab77/sql/parser/scan_test.go#L274)):*
`s/no error/success/g`

---

*[sql/testdata/builtin_function, line 622 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6280#-KGDWO5AYRuPofK8blJD:-KGDWO5AYRuPofK8blJE:1664629724) ([raw file](https://github.com/cockroachdb/cockroach/blob/544d737dd00f525d36820e2f86a6c8e09631ab77/sql/testdata/builtin_function#L622)):*
What's this change caused by?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6280#-:-KGDWf5ziFenorh7UokM:1417088721)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 12 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[sql/values_test.go, line 46 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6280#-KGCzOXqiwJD6cz5PHU5:-KGDau9_dzUJ3MpQnm-a:1102881377) ([raw file](https://github.com/cockroachdb/cockroach/blob/544d737dd00f525d36820e2f86a6c8e09631ab77/sql/values_test.go#L46)):*
I think this is the only place that we use those other than one use in the SQL syntax. Unless that changes, I'd rather keep it as an implementation detail instead of encouraging its use by promoting it to a documented part of the `sql/parser`'s public API.

---

*[sql/parser/expr.go, line 280 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6280#-KGDPue7xPBHGnlyq5ZX:-KGDaBCftSgZPmWntMFL:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/544d737dd00f525d36820e2f86a6c8e09631ab77/sql/parser/expr.go#L280)):*
Done.

---

*[sql/parser/normalize.go, line 325 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6280#-KGDQze3_X-AjAc6EHcl:-KGDaC8787vh8KkjoFh3:-907374197) ([raw file](https://github.com/cockroachdb/cockroach/blob/544d737dd00f525d36820e2f86a6c8e09631ab77/sql/parser/normalize.go#L325)):*
Yep, this method is able to be removed completely in a later commit.

---

*[sql/parser/scan.go, line 558 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6280#-KGDVu0j4hVCF45L8Oyx:-KGDaS35AH9oE_ptfpMH:-1404893406) ([raw file](https://github.com/cockroachdb/cockroach/blob/544d737dd00f525d36820e2f86a6c8e09631ab77/sql/parser/scan.go#L558)):*
They shouldn't happen in practice. I'll panic instead.

---

*[sql/parser/scan_test.go, line 274 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6280#-KGDW9Lm2vPT-MY1gKY6:-KGDajLaaIbgDmtY0Lrq:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/544d737dd00f525d36820e2f86a6c8e09631ab77/sql/parser/scan_test.go#L274)):*
Done.

---

*[sql/testdata/builtin_function, line 622 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6280#-KGDWO5AYRuPofK8blJD:-KGDcmd5y87SSQ9_0mUq:-1319547653) ([raw file](https://github.com/cockroachdb/cockroach/blob/544d737dd00f525d36820e2f86a6c8e09631ab77/sql/testdata/builtin_function#L622)):*
The `go/constant` package doesnt [support](https://play.golang.org/p/4Ecm-qy0xM) `-0`. I don't think this is a problem because it isn't an expected value in any SQL data types and it is not even consistently supported across our data types (currently only available in FLOAT).

Still, this is a limitation, so if you think it should be documented somewhere, I'll add in a note.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6280)*

**Comment by petermattis** [comment]
Review status: 0 of 12 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[sql/values_test.go, line 46 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6280#-KGCzOXqiwJD6cz5PHU5:-KGDvBy87pOM6FVbhgby:2068912651) ([raw file](https://github.com/cockroachdb/cockroach/blob/544d737dd00f525d36820e2f86a6c8e09631ab77/sql/values_test.go#L46)):*
No, this doesn't matter too much, though you do something similar in `parser/parse_test.go`.

---

*[sql/parser/normalize.go, line 325 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6280#-KGDQze3_X-AjAc6EHcl:-KGDvQy75ZM8EBrjGkCf:634455588) ([raw file](https://github.com/cockroachdb/cockroach/blob/544d737dd00f525d36820e2f86a6c8e09631ab77/sql/parser/normalize.go#L325)):*
Curious why it can't be removed here, but ok if it is being removed later.

---

*[sql/testdata/builtin_function, line 622 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6280#-KGDWO5AYRuPofK8blJD:-KGDvgjORu-MhFcP_BSH:2146779649) ([raw file](https://github.com/cockroachdb/cockroach/blob/544d737dd00f525d36820e2f86a6c8e09631ab77/sql/testdata/builtin_function#L622)):*
I was more curious than anything. This is fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6280)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 12 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/parser/normalize.go, line 325 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6280#-KGDQze3_X-AjAc6EHcl:-KGDxDVc8WOCJEuCMlwP:1411261456) ([raw file](https://github.com/cockroachdb/cockroach/blob/544d737dd00f525d36820e2f86a6c8e09631ab77/sql/parser/normalize.go#L325)):*
I think it's because we're not yet folding constants.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6280)*

**Pull request merged**
