### PR TITLE
ts: Return timestamps at start of sample periods

### PR DESCRIPTION
**Pull request by mrtracy**
Changes time series queries to return timestamps at the beginning of a
downsampled period, rather than the middle. This brings us in line with
the behavior of all other time series systems which perform
downsampling/time grouping.

This has a minor effect on tests, and will have a (positive) UI impact
by creating more recognizable time stamps for data points on graphs.

Release note (admin UI): Time series charts now display data points at
more consistent timestamps.

screen shot 2018-04-16 at 4 43 21 pm

### CODE REVIEW

**Comment by couchand** [comment]
LGTM, thanks!  I can confirm that the timestamps make a little more sense now.  For instance,

old:
screen shot 2018-04-17 at 9 53 04 am

new:
screen shot 2018-04-17 at 9 53 57 am

**Comment by bdarnell** [comment]
:lgtm:

Why the beginning instead of the end? 

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24856#-:-LAJWhzo6V9lG-_QUJyn:b-o58flv)*

**Comment by mrtracy** [comment]
@bdarnell After talking with @couchand (and reviewing the behavior of other time series databases), I believe that is the most natural way to identify a grouped time period.  For example, when we downsample at a full-hour resolution, we end up with a point that represents all data from 8:00:00 - 8:59:59.  It seems better to label that point as 8:00 rather than 9:00.

**Pull request merged**
