### PR TITLE
sql: refactor sessionDataMutator as sessionDataMutatorIterator

### PR DESCRIPTION
**Pull request by otan**
Part of a body of work for SET LOCAL (refs #32562)

See individual commits for details.

Release justification: high pri work

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69394)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @otan)

___
*[pkg/sql/conn_executor.go, line 1480 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69394#-Mi-Vkkt7tX588bonHm5:-Mi-Vkkt7tX588bonHm6:b4qvfet) ([raw file](https://github.com/cockroachdb/cockroach/blob/6057acb19fff08dbeccd4f1277bfca209fc3d7f9/pkg/sql/conn_executor.go#L1480)):*
> ```Go
> }
> 
> // sessionData returns the top SessionData in the executor's sessionDataStack.
> ```

it's worth mentioning in this comment that the purpose of doing this is so that each transacation can track a separate sessiondata, and so we can get txn-scoped session variable changes.
___
*[pkg/sql/exec_util.go, line 2428 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69394#-Mi-iUK97ksHQXN1doq-:-Mi-iUK97ksHQXN1doq0:b4xpxm8) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe9857073d0eb79755b1bb8b41ddaa205dd3e62d/pkg/sql/exec_util.go#L2428)):*
> ```Go
> // a transaction where there may be two or more SessionData elements in
> // the stack)
> type sessionDataMutatorTopOnlyBase struct {
> ```

heh i can see why this is the name, but at the same time i feel like there could be a better name

something like `sessionDataMutatorTopCallbacks` or even just `sessionDataMutatorCallbacks`?
___
*[pkg/sql/exec_util.go, line 2453 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69394#-Mi-h5NPCV8mYY4BaEO5:-Mi-h5NPCV8mYY4BaEO6:b7iih2l) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe9857073d0eb79755b1bb8b41ddaa205dd3e62d/pkg/sql/exec_util.go#L2453)):*
> ```Go
> 		sessionDataMutatorBase: f.sessionDataMutatorBase,
> 	}
> 	// Change the sessionDataMutatorTopOnlyBase if our SessionData element is not
> ```

hmm could you explain a bit more about why we need this? i get that we're going to be creating a mutator for each element in the stack, but then why change this? is this the step that prevents us from sending out multiple param status updates?

also, what is sessionDataMutatorTopOnlyBase going to be if we don't change it? it looks like it would just be nil?

(i'm just asking since i couldn't piece it together on my own. but maybe this info would be useful to put in this comment.)
___
*[pkg/sql/exec_util.go, line 2455 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69394#-Mi-huYTDqm-tlwAv1v9:-Mi-huYTDqm-tlwAv1vA:b-thcxiv) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe9857073d0eb79755b1bb8b41ddaa205dd3e62d/pkg/sql/exec_util.go#L2455)):*
> ```Go
> 	// Change the sessionDataMutatorTopOnlyBase if our SessionData element is not
> 	// the top.
> 	if sd != f.sds.Top() {
> ```

comparing the pointers seems a bit fragile to me.. but maybe my instincts are wrong on this. what would you feel about making each sessiondata keep track of its nesting level, and comparing those instead?
___
*[pkg/sql/exec_util.go, line 2486 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69394#-Mi-aFho2XuNra3ritXx:-Mi-aFho2XuNra3ritXy:b-yb201f) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe9857073d0eb79755b1bb8b41ddaa205dd3e62d/pkg/sql/exec_util.go#L2486)):*
> ```Go
> ) error {
> 	for _, sd := range f.sds.Elems() {
> 		if err := applyFunc(f.mutator(sd)); err != nil {
> ```

could we end up in a bad state if we error out of this loop early? it would mean that some of the sessiondatas had the function applied and some did not. e.g. in the case of RESET ALL, some levels of the txn nesting would get reset while others would not

the ideal would be that if we encounter an error, we undo all the changes that were done so far. idk if it's feasible to do so -- maybe we could copy each sessiondata before calling applyFunc on it, and revert the stack elements to those copies?
___
*[pkg/sql/exec_util.go, line 2493 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69394#-Mi-kXmc7hvLEMim3y5e:-Mi-kXmc7hvLEMim3y5f:b6s4b6m) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe9857073d0eb79755b1bb8b41ddaa205dd3e62d/pkg/sql/exec_util.go#L2493)):*
> ```Go
> }
> 
> // sessionDataMutator is the object used by sessionVars to change the session
> ```

should sessionVars still be using this? why don't they need to use the `sessionDataMutatorIterator`?

actually, why do we need this struct at all? can't we get rid of this `sessionDataMutator` and rename `sessionDataMutatorIterator` to `sessionDataMutator`?
___
*[pkg/sql/sessiondata/session_data.go, line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69394#-Mi-W4cEC4OpExQyKOqH:-Mi-W4cF0gUBq-yO0l_W:boo107d) ([raw file](https://github.com/cockroachdb/cockroach/blob/6057acb19fff08dbeccd4f1277bfca209fc3d7f9/pkg/sql/sessiondata/session_data.go#L206)):*
> ```Go
> func (s *Stack) Top() *SessionData {
> 	if len(s.stack) == 0 {
> 		return nil
> ```

another followup from the last PR:

should this function return an AssertionError here if the stack is empty?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69394)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @rafiss)

___
*[pkg/sql/conn_executor.go, line 1480 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69394#-Mi-Vkkt7tX588bonHm5:-Mi-oY3e6YLkzvQrJWlf:bb77ucv) ([raw file](https://github.com/cockroachdb/cockroach/blob/6057acb19fff08dbeccd4f1277bfca209fc3d7f9/pkg/sql/conn_executor.go#L1480)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

it's worth mentioning in this comment that the purpose of doing this is so that each transacation can track a separate sessiondata, and so we can get txn-scoped session variable changes.
</blockquote></details>

Yep.
___
*[pkg/sql/exec_util.go, line 2428 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69394#-Mi-iUK97ksHQXN1doq-:-Mi-r1zQ3FVn9B39nzO0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe9857073d0eb79755b1bb8b41ddaa205dd3e62d/pkg/sql/exec_util.go#L2428)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

heh i can see why this is the name, but at the same time i feel like there could be a better name

something like `sessionDataMutatorTopCallbacks` or even just `sessionDataMutatorCallbacks`?
</blockquote></details>

Done.
___
*[pkg/sql/exec_util.go, line 2453 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69394#-Mi-h5NPCV8mYY4BaEO5:-Mi-r2lZ0Sbw1zqctNTG:bqvw2s3) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe9857073d0eb79755b1bb8b41ddaa205dd3e62d/pkg/sql/exec_util.go#L2453)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hmm could you explain a bit more about why we need this? i get that we're going to be creating a mutator for each element in the stack, but then why change this? is this the step that prevents us from sending out multiple param status updates?

also, what is sessionDataMutatorTopOnlyBase going to be if we don't change it? it looks like it would just be nil?

(i'm just asking since i couldn't piece it together on my own. but maybe this info would be useful to put in this comment.)
</blockquote></details>

it prevents us from sending multiple paramstatusupdates for a `SET x` inside a transaction. otherwise, it would create paramstatusupdate for each level of nesting in the txn!
___
*[pkg/sql/exec_util.go, line 2455 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69394#-Mi-huYTDqm-tlwAv1v9:-Mi-reWH1oCLSGlotHuf:b-7rl0jq) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe9857073d0eb79755b1bb8b41ddaa205dd3e62d/pkg/sql/exec_util.go#L2455)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

comparing the pointers seems a bit fragile to me.. but maybe my instincts are wrong on this. what would you feel about making each sessiondata keep track of its nesting level, and comparing those instead?
</blockquote></details>

done!
___
*[pkg/sql/exec_util.go, line 2486 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69394#-Mi-aFho2XuNra3ritXx:-Mi-rft07f9_Kv_noLdi:bvh45vg) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe9857073d0eb79755b1bb8b41ddaa205dd3e62d/pkg/sql/exec_util.go#L2486)):*
> could we end up in a bad state if we error out of this loop early? 

potentially, but I'm not sure it's worth doing much more than that until we do https://github.com/cockroachdb/cockroach/issues/69391. in theory, if something errors here, we're in bigger trouble.

seems like the savepointStack has a similar issue if we're paranoid, but I'm ok with things as is.
___
*[pkg/sql/exec_util.go, line 2493 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69394#-Mi-kXmc7hvLEMim3y5e:-Mi-s9fj88P0_UgChYQc:bnsh2wy) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe9857073d0eb79755b1bb8b41ddaa205dd3e62d/pkg/sql/exec_util.go#L2493)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

should sessionVars still be using this? why don't they need to use the `sessionDataMutatorIterator`?

actually, why do we need this struct at all? can't we get rid of this `sessionDataMutator` and rename `sessionDataMutatorIterator` to `sessionDataMutator`?
</blockquote></details>

because the `set_vars.go` will be responsible for delegating to either the top mutator, or all mutators.
the iterator makes it easy to transform mutator objects based on whether or not it's the top. without the separation also, we'd have to take in a `islocal` argument to all the `varGen` variables which is hairier imo.
___
*[pkg/sql/sessiondata/session_data.go, line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69394#-Mi-W4cEC4OpExQyKOqH:-Mi-p22nB78VP5w354vV:b-5bp3s4) ([raw file](https://github.com/cockroachdb/cockroach/blob/6057acb19fff08dbeccd4f1277bfca209fc3d7f9/pkg/sql/sessiondata/session_data.go#L206)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

another followup from the last PR:

should this function return an AssertionError here if the stack is empty?
</blockquote></details>

Not everything errors here; we can panic if you want. I'm ok with the other assertions we already made in the pop functions.

**Review by rafiss — APPROVED** [review]
looks good! just some optional comments if you'd like

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69394#-:-Mi04yB10-IVy_tbM8H9:b-q6xhv7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @otan)

___
*[pkg/sql/exec_util.go, line 2453 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69394#-Mi-h5NPCV8mYY4BaEO5:-Mi01QTs0fY1_-ySU2hq:bkj8ec1) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe9857073d0eb79755b1bb8b41ddaa205dd3e62d/pkg/sql/exec_util.go#L2453)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

it prevents us from sending multiple paramstatusupdates for a `SET x` inside a transaction. otherwise, it would create paramstatusupdate for each level of nesting in the txn!
</blockquote></details>

it's more clear to me now thanks!
___
*[pkg/sql/exec_util.go, line 2486 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69394#-Mi-aFho2XuNra3ritXx:-Mi00bEXER67PoEBtA_6:bnq95dc) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe9857073d0eb79755b1bb8b41ddaa205dd3e62d/pkg/sql/exec_util.go#L2486)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

Actually we always reset to the first stack entry after a txn so if it's corrupt it's inside an already broken txn. So I think re ok
</blockquote></details>

excellent!
___
*[pkg/sql/exec_util.go, line 2493 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69394#-Mi-kXmc7hvLEMim3y5e:-Mi01_2a99pEYDpmLm78:b-93vx1n) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe9857073d0eb79755b1bb8b41ddaa205dd3e62d/pkg/sql/exec_util.go#L2493)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

because the `set_vars.go` will be responsible for delegating to either the top mutator, or all mutators.
the iterator makes it easy to transform mutator objects based on whether or not it's the top. without the separation also, we'd have to take in a `islocal` argument to all the `varGen` variables which is hairier imo.
</blockquote></details>

ohh i see, i missed the change where `applyFunc` was added to `func (n *setVarNode) startExec()`. yes that definitely seems nicer than having to pass in `isLocal` to everything
___
*[pkg/sql/exec_util.go, line 2403 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69394#-Mi03CZxBpYisG33K3wh:-Mi03CZxBpYisG33K3wi:b-osdp8b) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2bd77f55467be146ea92243bcc25fe66b57fdbd/pkg/sql/exec_util.go#L2403)):*
> ```Go
> 	defaults SessionDefaults
> 	settings *cluster.Settings
> 	sessionDataMutatorCallbacks
> ```

if we embedded `sessionDataMutatorCallbacks` inside of `sessionDataMutatorIterator` and `sessionDataMutator` instead of embedding it here, would it make things cleaner? then we could avoid the logic of having to unset it inside of `mutator()` right?
___
*[pkg/sql/exec_util.go, line 2475 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69394#-Mi04_k34vuA6BG9Kbdx:-Mi04_k34vuA6BG9Kbdy:b-od2d8x) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2bd77f55467be146ea92243bcc25fe66b57fdbd/pkg/sql/exec_util.go#L2475)):*
> ```Go
> 	elems := f.sds.Elems()
> 	for i, sd := range elems {
> 		applyFunc(f.mutator(i == len(elems)-1, sd))
> ```

we just as well could change this to `i == 0` -- that way the param status notifications are sent as soon as the value is updated in the top-level, outside of any txn. and if any of the per-txn data mutators fail, the param status will still have been sent out. (ditto for `forEachMutatorError`)

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69394)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @otan, and @rafiss)

___
*[pkg/sql/exec_util.go, line 2493 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69394#-Mi-kXmc7hvLEMim3y5e:-Mi0KZU4DYvjtHAPJrm6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe9857073d0eb79755b1bb8b41ddaa205dd3e62d/pkg/sql/exec_util.go#L2493)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

ohh i see, i missed the change where `applyFunc` was added to `func (n *setVarNode) startExec()`. yes that definitely seems nicer than having to pass in `isLocal` to everything
</blockquote></details>

Done.
___
*[pkg/sql/exec_util.go, line 2403 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69394#-Mi03CZxBpYisG33K3wh:-Mi0LHuTDVcFXsDwUmhb:b-21w2q2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2bd77f55467be146ea92243bcc25fe66b57fdbd/pkg/sql/exec_util.go#L2403)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

if we embedded `sessionDataMutatorCallbacks` inside of `sessionDataMutatorIterator` and `sessionDataMutator` instead of embedding it here, would it make things cleaner? then we could avoid the logic of having to unset it inside of `mutator()` right?
</blockquote></details>

good idea, done!
___
*[pkg/sql/exec_util.go, line 2475 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69394#-Mi04_k34vuA6BG9Kbdx:-Mi0K_1Q5eP1TpkP7lXe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2bd77f55467be146ea92243bcc25fe66b57fdbd/pkg/sql/exec_util.go#L2475)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

we just as well could change this to `i == 0` -- that way the param status notifications are sent as soon as the value is updated in the top-level, outside of any txn. and if any of the per-txn data mutators fail, the param status will still have been sent out. (ditto for `forEachMutatorError`)
</blockquote></details>

Done.

**Pull request merged**
