### PR TITLE
add anchors to each setting's name

### PR DESCRIPTION
**Pull request by arberiii**
Changes done for issue https://github.com/cockroachdb/cockroach/issues/36733

### CODE REVIEW

**Comment by knz** [comment]
@arberiii thank you for your contribution.
As you can see CI fails, that's because you have not actually ran `make` to update the generated files with your change.

Please do that and complete the commit with all the derived changes. Then this should be fine. 

@jseldess do you know who on the doc side can validate this?

**Comment by jseldess** [comment]
@rmloveland, can you help verify that this works in the doc?

**Comment by rmloveland** [comment]
> can you help verify that this works in the doc?

It definitely works.  I just tested it for the duplicate PR of this change in https://github.com/cockroachdb/cockroach/pull/38923

@arberiii can you please choose which of these PRs (this or #38923) we should work with you on, and close the other?  They appear to be duplicates.

**Comment by arberiii** [comment]
@rmloveland  Great! I will close this one as the other one is tested.

**Pull request closed without merging**
