### PR TITLE
*: centralize cross-platform signal handling

### PR DESCRIPTION
**Pull request by benesch**
Go's story around cross-platform signal handling is weak. The syscall
package sometimes defines compatibility shims, but not always. For
example, on Windows, neither SIGTERM nor SIGUSR1 exists, yet Go provides
syscall.SIGTERM and not syscall.SIGUSR1. Our Windows build was recently
broken because of an unchecked usage of syscall.SIGUSR1 (2b91e0f).

Introduce a sysutil package to serve as a compatibility layer. sysutil
provides consistent cross-platform shims for all signals we care about.

sysutil also allows us to lint against usage of the syscall package
elsewhere in the codebase. Direct usage of syscall usually indicates
code that will fail to compile on Windows. The few syscall symbols that
are known to work cross-platform, or at least to fail gracefully on
unsupported platforms, are re-exported in the sysutil package. (A
similar lint rule used to exist, but was inadvertently dropped by
254457c.)

Unix-specific code is still allowed to import golang.org/x/sys/unix, but
hopefully the import path makes it a obvious that such code needs to be
protected with a "!windows" build tag. Ideally we'd lint for this, too,
but writing such a lint rule is challenging.

Release note: None

/cc @bdarnell you might want to have a look too.

### CODE REVIEW

**Comment by bdarnell** [comment]
I missed the original change here, but I don't know if we want to use both SIGUSR1 and SIGUSR2 for this purpose. I think that flushing the logs could easily fit under our existing SIGHUP handler (which currently reloads certificates, and could generally be used for all non-disruptive changes). Then we'd only need one new signal for log rotation and could keep SIGUSR2 free for other use (for example, when external log rotation is used, you want a signal that can say "external rotation has occurred, you need to reopen your logs"). 

Is a signal for forcing internal log rotation even desirable? I don't know of any other process that works this way. Using a CLI command instead of a signal would allow us to do the rotation synchronously, so that by the time the command has returned you know that the old log is no longer being written and could safely be archived. An async signal to trigger this rotation is less useful and AFAIK unconventional. 

I think I'd rather just revert this signal change (except maybe to flush on SIGHUP) and leave the rest for a future batch of changes focused on working better with external log rotation. 

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23801#-:-L7Vqfr436l3wB34DYtA:bj9jylp)*

**Comment by benesch** [comment]
Okay, I opened the revert PR: https://github.com/cockroachdb/cockroach/pull/23801#issuecomment-372792834

Regarding this PR, I still think it's useful to ban usage of "syscall" and force everyone through a compatibility shim. @bdarnell would you prefer if I held off on this until later in the release cycle, or are you entirely opposed to something like this going in?

**Comment by bdarnell** [comment]
I'm OK with introducing and requiring a `sysutil` abstraction layer, but I think it should have higher-level abstractions. It shouldn't just paper over compilation errors by providing dummy symbols with the same names, but instead abstract over the concepts of draining and reloading signals, etc. 

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/cli/start.go, line 398 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23801#-L7VvZJeZK--fA5Xst41:-L7VvZJfqv1GD-E5PrQr:b-zhi23e) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d83e034bd773bac04957d3c14fefb2456fcd153/pkg/cli/start.go#L398)):*
> ```Go
> 	// signals later, some startup logging might be lost.
> 	signalCh := make(chan os.Signal, 1)
> 	signal.Notify(signalCh, os.Interrupt, sysutil.MaybeSIGTERM, sysutil.MaybeSIGQUIT)
> ```

Adding the dummy `MaybeSIGX` values here is a little ugly. What if `sysutil` contained a list `var DrainSignals = []Signal{SIGINT, SIGTERM, SIGQUIT}` whose contents varied by platform?

---

*[pkg/cli/start.go, line 792 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23801#-L7VvyewhyD2uSwoiA0h:-L7VvyewhyD2uSwoiA0i:b8m3iv9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d83e034bd773bac04957d3c14fefb2456fcd153/pkg/cli/start.go#L792)):*
> ```Go
> 	// this, it's easier if the information appears in the log file.
> 	log.Infof(ctx, "process identity: uid %d euid %d gid %d egid %d",
> 		sysutil.MaybeGetuid(), sysutil.MaybeGeteuid(), sysutil.MaybeGetgid(), sysutil.MaybeGetegid())
> ```

If we're going to introduce this abstraction then we should only log the process identity fields that we can actually retrieve. 

---

*[pkg/security/certs_rotation_test.go, line 28 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23801#-L7VwLhbqSbebI9e8GRD:-L7VwLhbqSbebI9e8GRE:b-33wl6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d83e034bd773bac04957d3c14fefb2456fcd153/pkg/security/certs_rotation_test.go#L28)):*
> ```Go
> 
> 	"github.com/pkg/errors"
> 	"golang.org/x/sys/unix"
> ```

If we're going to require that all access to `syscall` go through `sysutil`, we should probably do the same for `sys/unix`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23801#-:-L7Vwgh7wpIeAje1JHNQ:bczgs82)*

**Comment by benesch** [comment]
> I'm OK with introducing and requiring a sysutil abstraction layer, but I think it should have higher-level abstractions. It shouldn't just paper over compilation errors by providing dummy symbols with the same names, but instead abstract over the concepts of draining and reloading signals, etc.I'm OK with introducing and requiring a sysutil abstraction layer, but I think it should have higher-level abstractions. It shouldn't just paper over compilation errors by providing dummy symbols with the same names, but instead abstract over the concepts of draining and reloading signals, etc.

Very fair. sysutil is now basically three high-level APIs instead of a thin shim over `syscall`. PTAL.

---

Review status: 0 of 17 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/cli/start.go, line 398 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23801#-L7VvZJeZK--fA5Xst41:-L7XfW-AWE9q4RY8oQI7:b-5c5mq8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d83e034bd773bac04957d3c14fefb2456fcd153/pkg/cli/start.go#L398)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Adding the dummy `MaybeSIGX` values here is a little ugly. What if `sysutil` contained a list `var DrainSignals = []Signal{SIGINT, SIGTERM, SIGQUIT}` whose contents varied by platform?
</blockquote></details>

Good point, done. I felt like the concept of "drain signals" belonged in `pkg/cli`, though, so I put the conditional compilation here, in `start_unix` and `start_windows`.

---

*[pkg/cli/start.go, line 792 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23801#-L7VvyewhyD2uSwoiA0h:-L7Xe6c7ZBIGA4vWozHG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d83e034bd773bac04957d3c14fefb2456fcd153/pkg/cli/start.go#L792)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

If we're going to introduce this abstraction then we should only log the process identity fields that we can actually retrieve. 
</blockquote></details>

Done.

---

*[pkg/security/certs_rotation_test.go, line 28 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23801#-L7VwLhbqSbebI9e8GRD:-L7Xfl3hJeSLnGpbkfIc:b-bogzn3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d83e034bd773bac04957d3c14fefb2456fcd153/pkg/security/certs_rotation_test.go#L28)):*
The reason I want to ban syscall in particular is because of this warning label:

> NOTE: This package is locked down. Code outside the standard Go repository should be migrated to use the corresponding package in the golang.org/x/sys repository. That is also where updates required by new systems or versions should be applied. Signal, Errno and SysProcAttr are not yet available in golang.org/x/sys and must still be referenced from the syscall package. See https://golang.org/s/go1.4-syscall for more information.

I've found that we're much better about putting use of `golang.org/x/sys/unix` behind a build tag. I also think it's nice to be able to just slap a test behind a `!windows` build tag and use `golang.org/x/sys/unix` freely without building an abstraction layer first, like in crash_reporting_unix_test.go.

WDYT?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23801#-:-L7XgmPwhWT7j0HVjV_d:b-i6ss38)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 17 of 17 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/security/certs_rotation_test.go, line 28 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23801#-L7VwLhbqSbebI9e8GRD:-L7_9PiKjcFV_KlKwRKh:bvu0fup) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d83e034bd773bac04957d3c14fefb2456fcd153/pkg/security/certs_rotation_test.go#L28)):*
> I've found that we're much better about putting use of golang.org/x/sys/unix behind a build tag.

Except in this file, where you're introducing a new use of sys/unix without a build tag. The old version would at least build on windows. I'm OK with allowing sys/unix in build-tagged files. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23801#-:-L7_LP7YYH-Ni3M7saG8:bnfp4nl)*

**Comment by benesch** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/security/certs_rotation_test.go, line 28 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23801#-L7VwLhbqSbebI9e8GRD:-L7_Lci-tzZGu3lOLSC2:bs4jz2w) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d83e034bd773bac04957d3c14fefb2456fcd153/pkg/security/certs_rotation_test.go#L28)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

> I've found that we're much better about putting use of golang.org/x/sys/unix behind a build tag.

Except in this file, where you're introducing a new use of sys/unix without a build tag. The old version would at least build on windows. I'm OK with allowing sys/unix in build-tagged files. 
</blockquote></details>

This file has a `// build !windows` tag already, no?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23801)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/security/certs_rotation_test.go, line 28 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23801#-L7VwLhbqSbebI9e8GRD:-L7_LyJ5LY9IYGok5E-T:b-ylujqb) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d83e034bd773bac04957d3c14fefb2456fcd153/pkg/security/certs_rotation_test.go#L28)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

This file has a `// build !windows` tag already, no?
</blockquote></details>

D'oh. Nevermind. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23801)*

**Review by knz — APPROVED** [review]
thanks

**Comment by knz** [comment]
I might suggest a cherry-pick to ensure the 2.0 maintainers will use the same code as master.

**Comment by bdarnell** [comment]
-1 on cherrypicking. We should only cherrypick to fix bugs, not to make future hypothetical changes easier. (If we end up making changes here during the 2.0.x patch cycle, we could consider cherry-picking this then)

**Comment by benesch** [comment]
Perfectly happy not cherry-picking!

@BramGruneir, would you mind to test this out on Windows before I merge? Specifically, can you verify that `./cockroach start --insecure` followed by `Ctrl-c` returns a zero exit status and `./cockroach start --insecure` followed by two `Ctrl-c`s in quick succession returns a non-zero exit status? I've attached what I hope is a valid Windows binary below.

[cockroach-windows.zip](https://github.com/cockroachdb/cockroach/files/1813399/cockroach-windows.zip)

**Comment by BramGruneir** [comment]
On shutdown after a single `Ctrl-c`:
- `$?` = False -- this means there was an error
- `$lastexitcode` = 1
- `$error[0]` = was empty

And the console showed this:
```
Note: a second interrupt will skip graceful shutdown and terminate forcefully
initiating graceful shutdown of server
server drained and shutdown completed
*
* INFO: interrupted
*
Failed running "start"
```

On shutdown after two `Ctrl-c`s:
- `$?` = False -- this means there was an error
- `$lastexitcode` = 1
- `$error[0]` was empty

And the console showed this:
```
Note: a second interrupt will skip graceful shutdown and terminate forcefully
initiating graceful shutdown of server
*
* ERROR: received signal 'interrupt' during shutdown, initiating hard shutdown - node may take longer to restart & clients may need to wait for leases to expire
*
```

Also, after every shutdown, even if graceful, the temp file had to be deleted:
```
* ERROR: could not cleanup temporary directories from record file: remove C:\cockroach\cockroach-data\cockroach-temp093610803\TEMP_DIR.LOCK: The process cannot access the file because it is being used by another process.
```
But the error variables still remained the exact same as the other two.

**Comment by benesch** [comment]
Ok, I just got around to testing v2.0 on Windows, and it exhibits the exact same behavior as it does with this patch, including that unfortunate "could not clean up temporary directories" message. Merging since this patch doesn't make things any worse! TFTRs.

**Comment by knz** [comment]
bors no happy

**Comment by benesch** [comment]
Well, I give up. Thanks for the ping.

**Pull request merged**
