### PR TITLE
sql: allow atomic name swaps

### LINKED ISSUE #54562: sql: can't atomically swap names for catalog entries
These operations are allowed in postgres, but not in cockroach, where you'll get a `relation ... already exists` error:

```
lucy=# create table foo();
CREATE TABLE
lucy=# begin;
BEGIN
lucy=# alter table foo rename to bar;
ALTER TABLE
lucy=# create table foo();
CREATE TABLE
lucy=# commit;
COMMIT
```

```
lucy=# create table foo();
CREATE TABLE
lucy=# create table bar();
CREATE TABLE
lucy=# begin;
BEGIN
lucy=# drop table foo;
DROP TABLE
lucy=# alter table bar rename to foo;
ALTER TABLE
lucy=# commit;
COMMIT
```

```
lucy=# create table foo();
CREATE TABLE
lucy=# create table bar();
CREATE TABLE
lucy=# begin;
BEGIN
lucy=# alter table foo rename to temp;
ALTER TABLE
lucy=# alter table bar rename to foo;
ALTER TABLE
lucy=# alter table temp rename to bar;
ALTER TABLE
lucy=# commit;
COMMIT
```

https://github.com/cockroachdb/cockroach/issues/12123 is a special case of the same issue. Of course, this also applies to other things in the catalog (databases, schemas, types).

The problem is that we prohibit multiple names from referring to the same descriptor at the same time, and this is enforced through the draining names system. Can we lift this restriction?

----

Epic CRDB-10483

### PR DESCRIPTION
**Pull request by postamar**
This PR deprecates and disables usage of the draining names mechanism on catalog descriptors. When renaming or dropping a table/database/schema/type, the namespace entry is now modified in-transaction. This makes it possible to swap names in-transaction. On the other hand, names may be inconsistently resolved to either the old or the new target in specific circumstances.  

Fixes #54562.

### CODE REVIEW

**Comment by postamar** [comment]
This PR is best reviewed commit-by-commit. We might want more tests but I'm not quite sure what to add. I'm all ears.

**Review by ajwerner — COMMENTED** [review]
I'd very much like to see logic tests that exercise these atomic name changes in various ways. I don't see any new logic tests. 

----

Some more snippets that I think should get some updated commentary or, at least, consideration:

https://github.com/cockroachdb/cockroach/blob/9dde19c5380c4d21d873cc5db6d768262646bb52/pkg/sql/catalog/descs/kv_descriptors.go#L192-L197

 https://github.com/cockroachdb/cockroach/blob/9dde19c5380c4d21d873cc5db6d768262646bb52/pkg/sql/catalog/descs/uncommitted_descriptors.go#L94-L100

After very brief reflection, I think the second piece could still be relevant. 

> Reviewed 6 of 25 files at r1, 11 of 15 files at r2, 33 of 37 files at r3, 12 of 12 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70334#-:-MnWvaXO5Ps5pzzhiBL6:br385se)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)

**Review by postamar — COMMENTED** [review]
Thanks for taking a look!

I've added a new logic test suite to exercise these changes. Did I cover enough cases? I'm honestly bad at coming up with these.

I've added TODOs for each of these snippets. Mixed-version clusters mean that we can't do what we _really_ want to do in the descs collection until 22.1 comes out anyway.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70334#-:-MnYD6M9ALlTFKVnlJny:bfi8g3t)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

**Review by ajwerner — COMMENTED** [review]
>I've added TODOs for each of these snippets. Mixed-version clusters mean that we can't do what we really want to do in the descs collection until 22.1 comes out anyway.

Ah yeah, makes sense. I'm a bit sad I wasn't in the mixed-version mindset in the first read through. 

----

abstract thought: are there any hazards with drop cascades and then failures to resolve fully qualified names?

----

On the whole, :lgtm:. Let me stew on some concerning thoughts until tomorrow but I'm pretty pleased with this. 

> Reviewed 1 of 52 files at r5, 4 of 37 files at r6, 9 of 15 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70334#-:-MnYjOEz-LgFvSZjrfAG:b-cajdey)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/migration/migrations/ensure_no_draining_names.go, line 44 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70334#-MnYhNti-2lUXhMZrzBs:-MnYhNti-2lUXhMZrzBt:bvbqxzy) ([raw file](https://github.com/cockroachdb/cockroach/blob/91f0cc6e85993b5b68c332b29be3ef55cb9f7665/pkg/migration/migrations/ensure_no_draining_names.go#L44)):*
> ```Go
> 	cte2
> WHERE
> 	COALESCE(json_array_length(d->'drainingNames'), 0) > 0;
> ```

add a `LIMIT 1` then consider just using the `Buffered` version of the internal executor for some simpler processing?
___
*[pkg/sql/logictest/testdata/logic_test/rename_atomic, line 4 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70334#-MnYj1hwEkl_mJpPKtte:-MnYj1hwEkl_mJpPKttf:b-m1f5ax) ([raw file](https://github.com/cockroachdb/cockroach/blob/91f0cc6e85993b5b68c332b29be3ef55cb9f7665/pkg/sql/logictest/testdata/logic_test/rename_atomic#L4)):*
> ```
> CREATE DATABASE db;
> CREATE DATABASE db_new;
> ```

what I'd like to see added here is the usage of the renamed objects in the transaction after the renaming statements to demonstrate that they are indeed usable. 
___
*[pkg/sql/logictest/testdata/logic_test/table, line 859 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70334#-MnYkE3B3IZ9yfwUtFwu:-MnYkE3B3IZ9yfwUtFwv:b-gsejym) ([raw file](https://github.com/cockroachdb/cockroach/blob/084f8a08f309af545be0369dd846c5cdd024dbb5/pkg/sql/logictest/testdata/logic_test/table#L859)):*
> ```
> 
> user root
> ```

it feels like you could preserve a version of this test without the errors
___
*[pkg/sql/logictest/testdata/logic_test/views, line 848 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70334#-MnYjpjQ8ivPpRvQlYsU:-MnYjpjQ8ivPpRvQlYsV:bxdmmr6) ([raw file](https://github.com/cockroachdb/cockroach/blob/084f8a08f309af545be0369dd846c5cdd024dbb5/pkg/sql/logictest/testdata/logic_test/views#L848)):*
> ```
> CREATE VIEW db2.v2 AS SELECT a+b+c+d FROM cd, db1.public.ab
> 
> # Unit test for #60737
> ```

it feels like you can rework this test to be a working test if you remove the errors and the rollbacks.

**Review by postamar — COMMENTED** [review]
> abstract thought: are there any hazards with drop cascades and then failures to resolve fully qualified names?

I honestly couldn't tell you at this point, could you elaborate please? It's been a while. Do you have in mind the following: adding a unit test which drop-cascades a bunch of stuff, blocks the schema change job via a testing knob, and concurrently tries to resolve fully-qualified names? Basically testing that the job does the "right thing" with names now that it no longer drains the names at the very end of its execution?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70334#-:-MnbVg_-CKCNhDmsA3lr:b-gq1up1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/migration/migrations/ensure_no_draining_names.go, line 44 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70334#-MnYhNti-2lUXhMZrzBs:-MnbUqtK36-nie0hh4eX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/91f0cc6e85993b5b68c332b29be3ef55cb9f7665/pkg/migration/migrations/ensure_no_draining_names.go#L44)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

add a `LIMIT 1` then consider just using the `Buffered` version of the internal executor for some simpler processing?
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/rename_atomic, line 4 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70334#-MnYj1hwEkl_mJpPKtte:-MnbUsDd-Tcp6FLhoevv:b-gk5vqq) ([raw file](https://github.com/cockroachdb/cockroach/blob/91f0cc6e85993b5b68c332b29be3ef55cb9f7665/pkg/sql/logictest/testdata/logic_test/rename_atomic#L4)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

what I'd like to see added here is the usage of the renamed objects in the transaction after the renaming statements to demonstrate that they are indeed usable. 
</blockquote></details>

Done, I think.
___
*[pkg/sql/logictest/testdata/logic_test/table, line 859 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70334#-MnYkE3B3IZ9yfwUtFwu:-MnbV7gf91uBqlU2sZEc:by7rp5e) ([raw file](https://github.com/cockroachdb/cockroach/blob/084f8a08f309af545be0369dd846c5cdd024dbb5/pkg/sql/logictest/testdata/logic_test/table#L859)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

it feels like you could preserve a version of this test without the errors
</blockquote></details>

That's true, but what are we testing in that case? It feels like the purpose of this deleted test is to exercise the error messages. Would you like me to extend the `rename_atomic `suite with cases involving different object types: tables, types, views etc?
___
*[pkg/sql/logictest/testdata/logic_test/views, line 848 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70334#-MnYjpjQ8ivPpRvQlYsU:-MnbVbjWE_7UU-DUjs5i:b73102r) ([raw file](https://github.com/cockroachdb/cockroach/blob/084f8a08f309af545be0369dd846c5cdd024dbb5/pkg/sql/logictest/testdata/logic_test/views#L848)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

it feels like you can rework this test to be a working test if you remove the errors and the rollbacks. 
</blockquote></details>

Same comment as above regarding what this test exercises.

**Review by ajwerner — APPROVED** [review]
LGTM

**Comment by postamar** [comment]
Thanks for the review!

**Review by ajwerner — COMMENTED** [review]
:lgtm: mod the one comment

> Reviewed 2 of 53 files at r9, 6 of 37 files at r10, 9 of 15 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70334#-:-MnfhAAABT5TsqdHbY_4:bmz9vux)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/migration/migrations/ensure_no_draining_names.go, line 75 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/70334#-MnfgaUU4q6foit7IoPp:-MnfgaUV6nGfYwqstoQ9:b-q8g4q7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3daa0db33793131c509b64d5b600637196b3e595/pkg/migration/migrations/ensure_no_draining_names.go#L75)):*
> ```Go
> 		log.Infof(ctx, "descriptor with ID %d and name %q still has draining names", id, name)
> 	}
> 	panic("unreachable")
> ```

how is this unreachable? If the context gets canceled, won't you be here?
___
*[pkg/sql/logictest/testdata/logic_test/table, line 859 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70334#-MnYkE3B3IZ9yfwUtFwu:-Mnfh6eUCsO1930C8FWG:b-bg3w9o) ([raw file](https://github.com/cockroachdb/cockroach/blob/084f8a08f309af545be0369dd846c5cdd024dbb5/pkg/sql/logictest/testdata/logic_test/table#L859)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

That's true, but what are we testing in that case? It feels like the purpose of this deleted test is to exercise the error messages. Would you like me to extend the `rename_atomic `suite with cases involving different object types: tables, types, views etc?
</blockquote></details>

It's okay, I think it's fine.

**Comment by postamar** [comment]
> how is this unreachable? If the context gets canceled, won't you be here?

Gaah I keep forgetting about that. Thanks, good catch! Returning `ctx.Err()` instead, on your advice (thank you for that too).

**Pull request merged**
