### PR TITLE
sql: Support more forms of CREATE TABLE AS

### LINKED ISSUE #9222: sql: Can't use literal VALUES expressions with CREATE TABLE AS
In Postgres:

```
alex=# create table test9 as values (1, 'one'), (2, 'two');
SELECT 2
alex=# select * from test9;
 column1 | column2
---------+---------
       1 | one
       2 | two
(2 rows)
```

In CockroachDB:

```
root@:26257> create table test9 as values (1, 'one'), (2, 'two');
pq: Invalid Select type.
```

The functionality is reasonably well-documented:
https://www.postgresql.org/docs/9.1/static/sql-createtableas.html
https://www.postgresql.org/docs/9.1/static/sql-values.html

For what it's worth, MySQL doesn't support this, and I'm honestly not sure whether we want to. @knz, is the lack of support for this intentional? If so, should we also not support it in views?

### PR DESCRIPTION
**Pull request by a-robinson**
Includes selecting a VALUES list, a UNION, and renaming columns.

Modified the logic and parser tests accordingly to cover the new functionality. The new syntax error type is duplicated from my initial view support PR (#9212), but I assume this will get in first.

Fixes #9222 

cc @knz @dt

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9278)

### CODE REVIEW

**Comment by dt** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/create.go, line 278 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9278#-KRRQVJcDQdbv-dIAYf0:-KRRQVJcDQdbv-dIAYf1:b-idfoc5) ([raw file](https://github.com/cockroachdb/cockroach/blob/de2f81b37f76c30f928e2450019751e46de3cd66/sql/create.go#L278)):*
> ```Go
> 			return nil, err
> 		}
> 		if len(n.ToCols) > len(selectPlan.Columns()) {
> ```

I don't have postgres handy right now... should this be` !=` (with an `|| len(n.ToCols) == 0` to) ?

---

*[sql/create.go, line 861 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9278#-KRRQeXxWpUn_lDGP7z2:-KRRQeXxWpUn_lDGP7z3:br6no1t) ([raw file](https://github.com/cockroachdb/cockroach/blob/de2f81b37f76c30f928e2450019751e46de3cd66/sql/create.go#L861)):*
> ```Go
> 		colType, _ := parser.DatumTypeToColumnType(colRes.Typ)
> 		columnTableDef := parser.ColumnTableDef{Name: parser.Name(colRes.Name), Type: colType}
> 		if len(p.ToCols) > i {
> ```

ditto above, if so, I'd just use `len != 0` (and maybe recheck len(p.ToCols) vs len(resultCols) above the loop) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9278)*

**Comment by knz** [comment]
So I did a double take on the same thing as @dt but have a different reaction to it. Sure pg does something similar, but I'd argue this is hardly *desirable* behavior. I think that if the user says `CREATE TABLE foo(x) AS SELECT ...` there is a definite expectation that the final table only has one column. pg's behavior here is at best confusing, at worst allowing users to shoot themselves in the foot by causing their derived tables to contain much more data than they need.

I'd recommend just erroring out when the number of columns doesn't match, with a comment that this is different from what pg does. Then wait to see if users complain. Then I'd argue that if users want to disable error checking it should be with a separate syntax, such as (I'm pulling this out of my hat now) `CREATE TABLE foo(x, *) AS SELECT ...`.

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[sql/create.go, line 278 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9278#-KRRQVJcDQdbv-dIAYf0:-KRS2UriblS65tGQs592:bnbm835) ([raw file](https://github.com/cockroachdb/cockroach/blob/de2f81b37f76c30f928e2450019751e46de3cd66/sql/create.go#L278)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> I don't have postgres handy right now... should this be` !=` (with an `|| len(n.ToCols) == 0` to) ?
</details>
This is fine. The names listed in the CREATE TABLE AS are used to rename the source columns, not to constrain the number of columns. If there are more columns in the source than specified in CREATE TABLE, they will be silently added without being renamed.

---

*[sql/create.go, line 861 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9278#-KRRQeXxWpUn_lDGP7z2:-KRS36AgdQ1cGa9GndyN:br0cj4v) ([raw file](https://github.com/cockroachdb/cockroach/blob/de2f81b37f76c30f928e2450019751e46de3cd66/sql/create.go#L861)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> ditto above, if so, I'd just use `len != 0` (and maybe recheck len(p.ToCols) vs len(resultCols) above the loop) 
</details>
I think this code is correct.

---

*[sql/parser/create.go, line 561 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9278#-KRS3ByLn2YNKIpgdTlG:-KRS3ByM2LiCg78dYP3l:b-p03a0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/de2f81b37f76c30f928e2450019751e46de3cd66/sql/parser/create.go#L561)):*
> ```Go
> 	Defs        TableDefs
> 	AsSource    *Select
> 	ToCols      NameList // Only to be used in conjunction with AsSource
> ```

nit: I'd use 
```
As struct {
   Source      *Select
   ColumnNames NameList
}
```

---

*[sql/sqlbase/errors.go, line 59 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9278#-KRS3mi4KfRVCenefIFO:-KRS3mi5v5mv1Me6o01a:b-cdwnzf) ([raw file](https://github.com/cockroachdb/cockroach/blob/de2f81b37f76c30f928e2450019751e46de3cd66/sql/sqlbase/errors.go#L59)):*
> ```Go
> var _ ErrorWithPGCode = &ErrUndefinedTable{}
> var _ ErrorWithPGCode = &ErrRetry{}
> var _ ErrorWithPGCode = &ErrSyntax{}
> ```

I think it would be best to move the changes to this file to a separate commit (though perhaps OK to keep it in the same PR). Also in that commit the use of it in Create() and perhaps you could have a quick scan at the other error cases in the other planNode constructors and see if we should use the new error there as well. And if you don't want to do this right now, at least file a follow-up issue to do this work.

---

*[sql/testdata/create_as, line 13 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9278#-KRS4H76Xg7eQDZJ13lm:-KRS4H786JdnAsKtjLZm:b2ggjya) ([raw file](https://github.com/cockroachdb/cockroach/blob/de2f81b37f76c30f928e2450019751e46de3cd66/sql/testdata/create_as#L13)):*
> ```
> 
> statement ok
> CREATE TABLE itemColors (color) AS VALUES ('blue'), ('red'), ('green')
> ```

So if you want to keep the feature where you can have fewer columns named in CREATE than there are in the source, at least test this here and show the result of a subsequent query. We're talking about:
```
query II colnames
CREATE TABLE foo(x INT, y INT); CREATE TABLE bar(w) AS SELECT * FROM foo; SELECT * FROM bar
w y
----
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9278#-:-KRS4nSmPmzWe2WpTb2D:b-61emgt)*

**Comment by a-robinson** [comment]
Yeah, I agree on the fact that it's probably not desirable behavior. Switched over to only allowing named columns when the correct number are specified.

---

Review status: 1 of 7 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[sql/create.go, line 278 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9278#-KRRQVJcDQdbv-dIAYf0:-KRT_LHVfok0lOtCrkZq:bvuzedm) ([raw file](https://github.com/cockroachdb/cockroach/blob/de2f81b37f76c30f928e2450019751e46de3cd66/sql/create.go#L278)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> This is fine. The names listed in the CREATE TABLE AS are used to rename the source columns, not to constrain the number of columns. If there are more columns in the source than specified in CREATE TABLE, they will be silently added without being renamed.
</details>
Yeah, that's the behavior in postgres, but as suggested by knz above, we're going to restrict it for now.

---

*[sql/create.go, line 861 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9278#-KRRQeXxWpUn_lDGP7z2:-KRTb32zQKkaQoMJU7Fj:bxenl3x) ([raw file](https://github.com/cockroachdb/cockroach/blob/de2f81b37f76c30f928e2450019751e46de3cd66/sql/create.go#L861)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> I think this code is correct.
</details>
I could redo the check, I suppose, but this code works as intended if the earlier checks are performed as intended, and operates reasonably without panicking if they aren't. Let me know if you'd still like me to change it.

---

*[sql/parser/create.go, line 561 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9278#-KRS3ByLn2YNKIpgdTlG:-KRTa4xCRO5GPnH0kpdy:b-syn2ph) ([raw file](https://github.com/cockroachdb/cockroach/blob/de2f81b37f76c30f928e2450019751e46de3cd66/sql/parser/create.go#L561)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> nit: I'd use 
> ```
> As struct {
>    Source      *Select
>    ColumnNames NameList
> }
> ```
</details>
That required defining the `As` strict on its own at the package scope rather than anonymously within the CreateTable struct, since nested structs can't be cleanly initialized from our yacc. Defining a separate struct seemed less clear to me (e.g. is it used anywhere else?), so I just switched the second name to AsColumnNames. Good enough?

---

*[sql/sqlbase/errors.go, line 59 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9278#-KRS3mi4KfRVCenefIFO:-KRTg4_TAttMU0XQHS2e:b-otzyj2) ([raw file](https://github.com/cockroachdb/cockroach/blob/de2f81b37f76c30f928e2450019751e46de3cd66/sql/sqlbase/errors.go#L59)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> I think it would be best to move the changes to this file to a separate commit (though perhaps OK to keep it in the same PR). Also in that commit the use of it in Create() and perhaps you could have a quick scan at the other error cases in the other planNode constructors and see if we should use the new error there as well. And if you don't want to do this right now, at least file a follow-up issue to do this work.
</details>
Done: https://github.com/cockroachdb/cockroach/issues/9290

---

*[sql/testdata/create_as, line 13 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9278#-KRS4H76Xg7eQDZJ13lm:-KRTa7vFzhcWnWNX6pws:btnz17y) ([raw file](https://github.com/cockroachdb/cockroach/blob/de2f81b37f76c30f928e2450019751e46de3cd66/sql/testdata/create_as#L13)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> So if you want to keep the feature where you can have fewer columns named in CREATE than there are in the source, at least test this here and show the result of a subsequent query. We're talking about:
> ```
> query II colnames
> CREATE TABLE foo(x INT, y INT); CREATE TABLE bar(w) AS SELECT * FROM foo; SELECT * FROM bar
> w y
> ----
> ```
</details>
Removed the functionality, added a test for the failure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9278#-:-KRT_56D4T7AvXBP1l27:b992raj)*

**Comment by knz** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[sql/create.go, line 861 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9278#-KRRQeXxWpUn_lDGP7z2:-KRTuKO3ZNh385W69eFp:b-5h53so) ([raw file](https://github.com/cockroachdb/cockroach/blob/de2f81b37f76c30f928e2450019751e46de3cd66/sql/create.go#L861)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary>
> I could redo the check, I suppose, but this code works as intended if the earlier checks are performed as intended, and operates reasonably without panicking if they aren't. Let me know if you'd still like me to change it.
</details>
This is fine given the new check above.

---

*[sql/create.go, line 237 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9278#-KRTuBtX407ocQJAY09t:-KRTuBtX407ocQJAY09u:byj9qa8) ([raw file](https://github.com/cockroachdb/cockroach/blob/958c9b2c1571c7f256d0b7b70027b9730a85475f/sql/create.go#L237)):*
> ```Go
> 	dbDesc     *sqlbase.DatabaseDescriptor
> 	insertPlan planNode
> 	selectPlan planNode
> ```

nit: now you're supporting more sources than just selects, you could rename this attribute to `sourcePlan` instead of `selectPlan`.

---

*[sql/create.go, line 280 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9278#-KRTtZmeC884hqT8J6jX:-KRTtZmeC884hqT8J6jY:bftyo65) ([raw file](https://github.com/cockroachdb/cockroach/blob/958c9b2c1571c7f256d0b7b70027b9730a85475f/sql/create.go#L280)):*
> ```Go
> 		numColNames := len(n.AsColumnNames)
> 		if numColNames != 0 {
> 			if numColNames > len(selectPlan.Columns()) {
> ```

We're not that far in our SQL UX story that we really need two error messages here. You can simplify this to `fmt.Sprintf("CREATE TABLE AS specifies %d columns, data source has %d", numColNames, len(selectPlan.Columns())`

---

*[sql/parser/create.go, line 561 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9278#-KRS3ByLn2YNKIpgdTlG:-KRTuP829YO3PJbsP4mx:bb6mt9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/de2f81b37f76c30f928e2450019751e46de3cd66/sql/parser/create.go#L561)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary>
> That required defining the `As` strict on its own at the package scope rather than anonymously within the CreateTable struct, since nested structs can't be cleanly initialized from our yacc. Defining a separate struct seemed less clear to me (e.g. is it used anywhere else?), so I just switched the second name to AsColumnNames. Good enough?
</details>
:+1:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9278#-:-KRTv-nVBQKav4gtYydu:bnfp4nl)*

**Comment by a-robinson** [comment]
Review status: 5 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[sql/create.go, line 237 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9278#-KRTuBtX407ocQJAY09t:-KRU2PuhscOYmA9dciWf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/958c9b2c1571c7f256d0b7b70027b9730a85475f/sql/create.go#L237)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> nit: now you're supporting more sources than just selects, you could rename this attribute to `sourcePlan` instead of `selectPlan`.
</details>
Done.

---

*[sql/create.go, line 280 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/9278#-KRTtZmeC884hqT8J6jX:-KRU3wmr8cdor3w1CJnj:bwq4b5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/958c9b2c1571c7f256d0b7b70027b9730a85475f/sql/create.go#L280)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> We're not that far in our SQL UX story that we really need two error messages here. You can simplify this to `fmt.Sprintf("CREATE TABLE AS specifies %d columns, data source has %d", numColNames, len(selectPlan.Columns())`
</details>
Done, although now there's an awkward pluralization issue in the error message.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9278)*

**Comment by knz** [comment]
`utils.Pluralize()`

**Comment by a-robinson** [comment]
Beautiful, thanks :)

---

Review status: 5 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9278#-:-KRU5BFIFDAyb2AZLfuL:b-qk3st6)*

**Pull request merged**
