### PR TITLE
roachtest: update pgjdbc blacklist after test fixes

### PR DESCRIPTION
**Pull request by rafiss**
There was a bug in the test runner script, and it's fixed now, so there
a lot more passing tests.

#40666

Release justification: This only changes testing code.

Release note: None

### CODE REVIEW

**Comment by jordanlewis** [comment]
LGTM

**Comment by nvanbenschoten** [comment]
Thanks @rafiss. Can we mark this as closing #40666?

**Comment by rafiss** [comment]
It should close it -- but I just want to verify that I got the 2.1 blacklist right first, so I'll let one more 2.1 nightly run happen (it was hard for me to get 2.1 built locally to verify this).

**Pull request merged**
