### PR TITLE
opt: map and push down equality conditions

### LINKED ISSUE #36226: opt: AssociateJoin should push down transitive equalities
Consider this schema+query:

```
exec-ddl
CREATE TABLE parent1 (pid1 INT PRIMARY KEY, pa1 INT)
----

exec-ddl
CREATE TABLE child1 (
  pid1 INT,
  cid1 INT,
  ca1 INT,
  PRIMARY KEY(pid1, cid1)
)
INTERLEAVE IN PARENT parent1 (pid1)
----

exec-ddl
CREATE TABLE grandchild1 (
  pid1 INT,
  cid1 INT,
  gcid1 INT,
  gca1 INT,
  PRIMARY KEY(pid1, cid1, gcid1)
)
INTERLEAVE IN PARENT child1 (pid1, cid1)
----

memo join-limit=4
SELECT * FROM grandchild1
JOIN child1 USING (pid1, cid1)
JOIN parent1 USING (pid1)
ORDER BY pid1
----
```

There's a transitive equality which in theory should get pushed down, but since the rule that generates those is a norm rule, it doesn't get applied to the expression generated by AssociateJoin, and we end up with a cross join where we shouldn't.

### LINKED ISSUE #38716: opt: Synthesize equality conditions during AssociateJoin rule
When 3 or more tables are joined, it is not uncommon for 3 or more columns to be equivalent. For example:
```
SELECT * FROM a, b, c WHERE a.x=b.y AND b.y=c.z
```
The optimizer will consider these join orders:
```
1. (a join b) join c
2. a join (b join c)
```
But it will not consider `(a join c) join b`, because there is no explicit join condition between `a` and `c`. This could cause it to miss the best plan (in fact, it does miss the best plan for TPC-H Q9 for this reason).

The optimizer knows that columns (x, y, z) are all equivalent to one another. It can synthesize any missing equality conditions during the `AssociateJoin` rule, thus opening up new ordering possibilities.

For TPC-H Q9, adding the missing equality condition reduces execution time from ~120s to ~20s.

### PR DESCRIPTION
**Pull request by rytaft**
This commit adds a new normalization rule to enable pushing variable
equality conditions such as `a.x=b.x` through joins.

For example, consider this query:

  `SELECT * FROM a, b, c WHERE a.x=b.x AND a.x=c.x`

Given join ordering `(a join (b join c))`, it should be possible to infer the
filter `b.x=c.x` and push it down from the top level onto the join `(b join c)`.
This commit enables that mapping and pushdown to happen.

In addition, this commit updates the `AssociateJoin` rule to map as many
equality conditions as possible to use the output columns of the new inner-most
join, allowing those conditions to be pushed onto that join.

For example, consider this query:

  `SELECT * FROM a, b, c WHERE a.x=b.x AND b.x=c.x`

If the AssociateJoin rule creates a new join ordering `(b join (a join c))`,
it should be possible to map `a.x=b.x` to `a.x=c.x` and add it onto the new
inner-most join `(a join c)`. This commit enables that mapping to happen.

Fixes #38716
Fixes #36226

Release note (performance improvement): Improved performance for some join
queries due to improved filter inference during planning.
Release justification: This commit will not be merged before the release
branch is cut.

### CODE REVIEW

**Review by justinj — COMMENTED** [review]
Nice! :lgtm:, this was a bit tricky to wrap my head around but once I understood it it's very nice and clean!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41250#-:-LqCXG6u7RuFCKssrV0b:b-rszm3y)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/norm/join.go, line 181 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41250#-LqCTr144SVKppjPEtvj:-LqCTr15EdNV4yaRShXh:be5tcf7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d613e451e93969c080f7939a203670feff73d8da/pkg/sql/opt/norm/join.go#L181)):*
> ```Go
> 	for i := range filters {
> 		fd := &filters[i].ScalarProps(c.mem).FuncDeps
> 		filterEqCols := fd.ComputeEquivClosure(fd.EquivReps())
> ```

Is there a case today in which this does not correspond to just a pair of columns being equated? 
___
*[pkg/sql/opt/norm/join.go, line 278 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41250#-LqCUNLp1wtlnuzEiNBA:-LqCUNLq1inb-esjAK-G:b-nkjbxn) ([raw file](https://github.com/cockroachdb/cockroach/blob/d613e451e93969c080f7939a203670feff73d8da/pkg/sql/opt/norm/join.go#L278)):*
> ```Go
> 	filters memo.FiltersExpr, src *memo.FiltersItem, dst memo.RelExpr,
> ) opt.ScalarExpr {
> 	// Fast path if src is already bound by dst.
> ```

can this be easily unified with `CanMapJoinOpEquality`?
___
*[pkg/sql/opt/norm/join.go, line 366 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41250#-LqCWQt16mAoW3wIzPfa:-LqCWQt16mAoW3wIzPfb:byc11ug) ([raw file](https://github.com/cockroachdb/cockroach/blob/d613e451e93969c080f7939a203670feff73d8da/pkg/sql/opt/norm/join.go#L366)):*
> ```Go
> 		if !scalarProps.OuterCols.Contains(col) {
> 			// Filter does not contain col.
> 			eqCols = scalarProps.FuncDeps.ComputeEquivClosure(eqCols)
> ```

Can't this still miss some, if we have a case like:
```
col: x
filter: x = y AND w = z AND y = w
```
?
(assuming I understood the problem that prompted this change correctly)

**Review by justinj — COMMENTED** [review]
oops, only looked at first commit

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41250#-:-LqCXzIl4dBXFhIYT2Xr:b-bqzuza)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, and @rytaft)

**Review by justinj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41250)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/norm/join.go, line 331 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41250#-LqCbQOV-EWwBgr0hpDC:-LqCbQOV-EWwBgr0hpDD:bx172sg) ([raw file](https://github.com/cockroachdb/cockroach/blob/713906ed6df67419e1dc0276d2052a47f860f846/pkg/sql/opt/norm/join.go#L331)):*
> ```Go
> 			(newFilters == nil && c.CanMapJoinOpEquality(filters, filter, dst)) {
> 			if newFilters == nil {
> 				// All right, it was necessary to allocate the filters after all.
> ```

lol, I like the resigned tone of this comment
___
*[pkg/sql/opt/norm/join.go, line 336 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41250#-LqCdsZEEWgp7o_ZIAA3:-LqCdsZEEWgp7o_ZIAA4:b87cx01) ([raw file](https://github.com/cockroachdb/cockroach/blob/713906ed6df67419e1dc0276d2052a47f860f846/pkg/sql/opt/norm/join.go#L336)):*
> ```Go
> 			}
> 
> 			newFilters[i] = memo.FiltersItem{
> ```

Maybe I'm missing some important thing here, is it not possible for the replacement of the filter like this to cause us to lose some information? Like, I get if we were just appending this newly mapped filter we'd be fine, but couldn't *replacing* like this result in making the replacement no longer valid (since we use the filters themselves to justify the mapping)?

Like if we had something like:
```
a = b AND b = c AND c = d AND d = e AND e = f AND f = a
```
(a 6-cycle)
and then we replaced `b = c` => `b = f` and `e = f` => `e = c`, we no longer have an equivalent set of filters, we have two equivalence groups (`{a,b,f}` and `{c,d,e}`) rather than one (`{a,b,c,d,e,f}`).

**Review by rytaft — COMMENTED** [review]
TFTR! Very thoughtful comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41250#-:-LqDSQH648AwDDF3iZYx:b-gi1qi4)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/norm/join.go, line 181 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41250#-LqCTr144SVKppjPEtvj:-LqD9LDR64L6PrRvzZnI:b-rqqelq) ([raw file](https://github.com/cockroachdb/cockroach/blob/d613e451e93969c080f7939a203670feff73d8da/pkg/sql/opt/norm/join.go#L181)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Is there a case today in which this does not correspond to just a pair of columns being equated? 
</blockquote></details>

I don't think so -- in `logical_props_builder.go` we only add equivalencies for filters that are variable equalities. 

I did it this way since it seemed like the easiest way to extract the equivalent columns and remove them from `eqCols`.
___
*[pkg/sql/opt/norm/join.go, line 278 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41250#-LqCUNLp1wtlnuzEiNBA:-LqCvHcE4G2pHcGEBgI2:bmr6q5g) ([raw file](https://github.com/cockroachdb/cockroach/blob/d613e451e93969c080f7939a203670feff73d8da/pkg/sql/opt/norm/join.go#L278)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

can this be easily unified with `CanMapJoinOpEquality`?
</blockquote></details>

Not sure if I understand the question, but are you asking whether we can get rid of the fast path here by returning false from `CanMapJoinOpEquality`?

The problem is that we need `CanMapJoinOpEquality` to return true for this fast path so that the rule `PushEqualityIntoJoinLeftAndRight` will fire when appropriate. For example, suppose we have the following query: `SELECT * from a, b WHERE a.x = a.y AND a.x = b.x AND a.y = b.y;`. `PushEqualityIntoJoinLeftAndRight` has to fire to prevent `MapEqualityIntoJoinLeft` and `MapEqualityIntoJoinRight` from cycling with each other. They will infinitely loop mapping `a.x=a.y` to `b.x=b.y` and vice-versa. 

I added a note above `PushEqualityIntoJoinLeftAndRight` to emphasize that it has to be first (this is the same pattern we used for the existing filter push down rules).
___
*[pkg/sql/opt/norm/join.go, line 366 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41250#-LqCWQt16mAoW3wIzPfa:-LqDEScu6zu-2vhgHU7Y:b1p1nd7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d613e451e93969c080f7939a203670feff73d8da/pkg/sql/opt/norm/join.go#L366)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Can't this still miss some, if we have a case like:
```
col: x
filter: x = y AND w = z AND y = w
```
?
(assuming I understood the problem that prompted this change correctly)
</blockquote></details>

Good point! Fixed.
___
*[pkg/sql/opt/norm/join.go, line 336 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41250#-LqCdsZEEWgp7o_ZIAA3:-LqD1KE0B_9aTSCuuNIZ:b-cnnp42) ([raw file](https://github.com/cockroachdb/cockroach/blob/713906ed6df67419e1dc0276d2052a47f860f846/pkg/sql/opt/norm/join.go#L336)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Maybe I'm missing some important thing here, is it not possible for the replacement of the filter like this to cause us to lose some information? Like, I get if we were just appending this newly mapped filter we'd be fine, but couldn't *replacing* like this result in making the replacement no longer valid (since we use the filters themselves to justify the mapping)?

Like if we had something like:
```
a = b AND b = c AND c = d AND d = e AND e = f AND f = a
```
(a 6-cycle)
and then we replaced `b = c` => `b = f` and `e = f` => `e = c`, we no longer have an equivalent set of filters, we have two equivalence groups (`{a,b,f}` and `{c,d,e}`) rather than one (`{a,b,c,d,e,f}`).
</blockquote></details>

This situation is not possible because of the blocks in `CanMapJoinOpEquality` and `MapJoinOpEquality` that have the following comment:
```
// Remove from consideration equality columns that already have an equality
// condition bound by dst.
```
So in the example you gave, suppose that the columns in `dst` are `{a,b,f}`, and we want to try to map `b=c` to use `{a,b,f}`. Since `a=b` and `f=a` are filters already bound by `dst`, all three columns (a, b and f) will be removed from consideration for the new equality condition. Therefore, it won't be possible to map to `b=f`.

That being said, I agree there's something about this that feels slightly weird. Another way to think about this problem is that if every column in the equivalence group is a node in a graph, we want to find the minimum spanning tree for the graph, where edges between nodes in `dst` have lower weight. I'm not sure if formulating it in this way makes it easier/cleaner to solve, but I'll spend some time thinking about it.

One thing I do like about this solution, though, is that it reuses the code from the normalization rules, and the normalization rules follow the same pattern we already used for filter push down.

Anyway, let me know if you have an idea about how to make this better!

**Review by justinj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41250)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/norm/join.go, line 181 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41250#-LqCTr144SVKppjPEtvj:-LqHVTgm-p7yH6VqiDsQ:b-bbtpz6) ([raw file](https://github.com/cockroachdb/cockroach/blob/d613e451e93969c080f7939a203670feff73d8da/pkg/sql/opt/norm/join.go#L181)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I don't think so -- in `logical_props_builder.go` we only add equivalencies for filters that are variable equalities. 

I did it this way since it seemed like the easiest way to extract the equivalent columns and remove them from `eqCols`.
</blockquote></details>

Makes sense! Just wanted to make sure I was understanding right
___
*[pkg/sql/opt/norm/join.go, line 278 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41250#-LqCUNLp1wtlnuzEiNBA:-LqHV_NeDTpyBJXqwkDz:bbtxrtq) ([raw file](https://github.com/cockroachdb/cockroach/blob/d613e451e93969c080f7939a203670feff73d8da/pkg/sql/opt/norm/join.go#L278)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Not sure if I understand the question, but are you asking whether we can get rid of the fast path here by returning false from `CanMapJoinOpEquality`?

The problem is that we need `CanMapJoinOpEquality` to return true for this fast path so that the rule `PushEqualityIntoJoinLeftAndRight` will fire when appropriate. For example, suppose we have the following query: `SELECT * from a, b WHERE a.x = a.y AND a.x = b.x AND a.y = b.y;`. `PushEqualityIntoJoinLeftAndRight` has to fire to prevent `MapEqualityIntoJoinLeft` and `MapEqualityIntoJoinRight` from cycling with each other. They will infinitely loop mapping `a.x=a.y` to `b.x=b.y` and vice-versa. 

I added a note above `PushEqualityIntoJoinLeftAndRight` to emphasize that it has to be first (this is the same pattern we used for the existing filter push down rules).
</blockquote></details>

Sorry, was a little too terse, I meant these couple blocks of code seem very similar to the blocks in `CanMapJoinOpEquality` and it feels like maybe there's an extraction possible. If not that's fine!
___
*[pkg/sql/opt/norm/join.go, line 336 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41250#-LqCdsZEEWgp7o_ZIAA3:-LqGoiFH3EHm2KQbfygP:beff1xg) ([raw file](https://github.com/cockroachdb/cockroach/blob/713906ed6df67419e1dc0276d2052a47f860f846/pkg/sql/opt/norm/join.go#L336)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This situation is not possible because of the blocks in `CanMapJoinOpEquality` and `MapJoinOpEquality` that have the following comment:
```
// Remove from consideration equality columns that already have an equality
// condition bound by dst.
```
So in the example you gave, suppose that the columns in `dst` are `{a,b,f}`, and we want to try to map `b=c` to use `{a,b,f}`. Since `a=b` and `f=a` are filters already bound by `dst`, all three columns (a, b and f) will be removed from consideration for the new equality condition. Therefore, it won't be possible to map to `b=f`.

That being said, I agree there's something about this that feels slightly weird. Another way to think about this problem is that if every column in the equivalence group is a node in a graph, we want to find the minimum spanning tree for the graph, where edges between nodes in `dst` have lower weight. I'm not sure if formulating it in this way makes it easier/cleaner to solve, but I'll spend some time thinking about it.

One thing I do like about this solution, though, is that it reuses the code from the normalization rules, and the normalization rules follow the same pattern we already used for filter push down.

Anyway, let me know if you have an idea about how to make this better!
</blockquote></details>

Talked about this offline

**Review by rytaft — COMMENTED** [review]
I've completely changed this to use a minimum-spanning tree approach as Justin and I discussed offline. PTAL!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41250#-:-LqJ5pnO660QAh6yJHc-:b-h6fnmj)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @rytaft)

**Review by RaduBerinde — COMMENTED** [review]
Very cool! Some minor comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41250#-:-LqM2kcN5qbAsZHswkKQ:bwzc0g)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/norm/join.go, line 122 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41250#-LqLzZAMEximcLTS6cph:-LqLzZAMEximcLTS6cpi:btctoj2) ([raw file](https://github.com/cockroachdb/cockroach/blob/21f4b3cede438cbfcbf9fdd39323412269c04b55/pkg/sql/opt/norm/join.go#L122)):*
> ```Go
> //
> // If src has a correlated subquery, CanMapJoinOpFilter returns false.
> func (c *CustomFuncs) CanMapJoinOpFilter(
> ```

we should move this so it stays close to `MapJoinOpFilter`
___
*[pkg/sql/opt/norm/join.go, line 171 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41250#-LqLz6Nd5ZQocpZUo05G:-LqLz6Nd5ZQocpZUo05H:bgdll6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/21f4b3cede438cbfcbf9fdd39323412269c04b55/pkg/sql/opt/norm/join.go#L171)):*
> ```Go
> 	// If more than one equality condition connecting columns in the equivalence
> 	// group spans both sides of the join, these conditions can be remapped.
> 	found := false
> ```

[nit] would be more suggestive if we used `found := 0` and then `found++; if found > 1 { return true }`
___
*[pkg/sql/opt/norm/join.go, line 195 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41250#-LqM-LEA0Za7MnH4JwjR:-LqM-LEA0Za7MnH4JwjS:bkhwe91) ([raw file](https://github.com/cockroachdb/cockroach/blob/21f4b3cede438cbfcbf9fdd39323412269c04b55/pkg/sql/opt/norm/join.go#L195)):*
> ```Go
> // containing col that forms an equivalence group in filters. Then it
> // (conceptually) constructs a graph in which the nodes represent columns and
> // the edges represent equality conditions between the columns. The goal is to
> ```

This is a bit confusing. There is the graph that represents the given equality conditions (the first diagram below), and then there's the conceptual complete graph where there's an edge between any pair of columns in the equivalency group. We are talking about a spanning tree of the latter, not the former. The former graph isn't important really, I don't think we should draw it.

What does "minimum" spanning tree mean here? Sounds like we're looking for *any* spanning tree with a single "crossing" edge. I get that the "restriction" can be thought of as a per-edge cost but we should use either one definition or the other.

We may be complicating things unnecessarily by talking about graphs and spanning trees. We could just say that we have a set of columns that are all equivalent, some on the left side and some on the right side. We construct a new set of equalities that implies the same equivalency group, with the property that there is a single condition with one left column and one right column.
___
*[pkg/sql/opt/norm/join.go, line 246 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41250#-LqM1aeOCM4QqieW3c8e:-LqM1aeOCM4QqieW3c8f:bulze7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/21f4b3cede438cbfcbf9fdd39323412269c04b55/pkg/sql/opt/norm/join.go#L246)):*
> ```Go
> 		))
> 	}
> 	for col, ok := leftEqCols.Next(prevCol + 1); ok; col, ok = leftEqCols.Next(col + 1) {
> ```

Is it important here how we "connect" them? It would be more intuitive (and easier to descripbe) to just pick an arbitrary column on each side and make everything on that side equal to that column. Eg if we have `l1, l2, l3` and `r1, r2, r3`, we could pick `l1` and `r2` and generate `l1 = r2` plus `l1 = l2`, `l1 = l3` plus `r1 = r2`, `r1 = r3`.
___
*[pkg/sql/opt/norm/join.go, line 252 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41250#-LqM2XKi-hoAu9yTW6bf:-LqM2XKi-hoAu9yTW6bg:b8c1ngh) ([raw file](https://github.com/cockroachdb/cockroach/blob/21f4b3cede438cbfcbf9fdd39323412269c04b55/pkg/sql/opt/norm/join.go#L252)):*
> ```Go
> 		prevCol = col
> 	}
> 	for col, ok := rightEqCols.Next(0); ok; col, ok = rightEqCols.Next(col + 1) {
> ```

It's subtle that the "crossing" condition happens here implicitly, should add a comment.

**Review by rytaft — COMMENTED** [review]
TFTR! Updated.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41250#-:-Lqb6qxy5i31ALfQVsJG:b-p0fj95)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj and @rytaft)

___
*[pkg/sql/opt/norm/join.go, line 278 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41250#-LqCUNLp1wtlnuzEiNBA:-Lqb2Qbj5Ksks7LMA1Nd:b-ft37oh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d613e451e93969c080f7939a203670feff73d8da/pkg/sql/opt/norm/join.go#L278)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Sorry, was a little too terse, I meant these couple blocks of code seem very similar to the blocks in `CanMapJoinOpEquality` and it feels like maybe there's an extraction possible. If not that's fine!
</blockquote></details>

This code is different now.
___
*[pkg/sql/opt/norm/join.go, line 122 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41250#-LqLzZAMEximcLTS6cph:-Lqazfhx4rBjtymCauAT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/21f4b3cede438cbfcbf9fdd39323412269c04b55/pkg/sql/opt/norm/join.go#L122)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

we should move this so it stays close to `MapJoinOpFilter`
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/join.go, line 171 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41250#-LqLz6Nd5ZQocpZUo05G:-LqazyAdCCoTOZwQkwKY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/21f4b3cede438cbfcbf9fdd39323412269c04b55/pkg/sql/opt/norm/join.go#L171)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] would be more suggestive if we used `found := 0` and then `found++; if found > 1 { return true }`
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/join.go, line 195 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41250#-LqM-LEA0Za7MnH4JwjR:-Lqb0oS313Y3sZgpEscP:bs7wumb) ([raw file](https://github.com/cockroachdb/cockroach/blob/21f4b3cede438cbfcbf9fdd39323412269c04b55/pkg/sql/opt/norm/join.go#L195)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is a bit confusing. There is the graph that represents the given equality conditions (the first diagram below), and then there's the conceptual complete graph where there's an edge between any pair of columns in the equivalency group. We are talking about a spanning tree of the latter, not the former. The former graph isn't important really, I don't think we should draw it.

What does "minimum" spanning tree mean here? Sounds like we're looking for *any* spanning tree with a single "crossing" edge. I get that the "restriction" can be thought of as a per-edge cost but we should use either one definition or the other.

We may be complicating things unnecessarily by talking about graphs and spanning trees. We could just say that we have a set of columns that are all equivalent, some on the left side and some on the right side. We construct a new set of equalities that implies the same equivalency group, with the property that there is a single condition with one left column and one right column.
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/join.go, line 246 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41250#-LqM1aeOCM4QqieW3c8e:-Lqb2Ho5AEw63TrU0Ilq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/21f4b3cede438cbfcbf9fdd39323412269c04b55/pkg/sql/opt/norm/join.go#L246)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Is it important here how we "connect" them? It would be more intuitive (and easier to descripbe) to just pick an arbitrary column on each side and make everything on that side equal to that column. Eg if we have `l1, l2, l3` and `r1, r2, r3`, we could pick `l1` and `r2` and generate `l1 = r2` plus `l1 = l2`, `l1 = l3` plus `r1 = r2`, `r1 = r3`.
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/join.go, line 252 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41250#-LqM2XKi-hoAu9yTW6bf:-Lqb2J5hCALli2oqJZNT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/21f4b3cede438cbfcbf9fdd39323412269c04b55/pkg/sql/opt/norm/join.go#L252)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It's subtle that the "crossing" condition happens here implicitly, should add a comment.
</blockquote></details>

Done.

**Review by justinj — COMMENTED** [review]
:lgtm_strong: :

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41250#-:-LqbEI25-v26Hdx6Bm_Z:b-yncq55)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj and @rytaft)

___
*[pkg/sql/opt/norm/join.go, line 163 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41250#-Lqb8druDuQIB5aWPmIx:-Lqb8druDuQIB5aWPmIy:bxkw8ck) ([raw file](https://github.com/cockroachdb/cockroach/blob/774e7828dc31340fbf09e5e5eefb79b1fddc4d22/pkg/sql/opt/norm/join.go#L163)):*
> ```Go
> //   SELECT * FROM a, b WHERE a.x = a.y AND b.x = b.y AND a.x = b.x
> //
> func (c *CustomFuncs) MapJoinOpEqualities(
> ```

Nice, this function is super clear now :thumbsup:

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41250)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj and @rytaft)

___
*[pkg/sql/opt/norm/rules/join.opt, line 179 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41250#-LqbV0Bu8k_2DwAX66XW:-LqbV0Bv3O2JaQ0Xk4x3:b-qo1g7a) ([raw file](https://github.com/cockroachdb/cockroach/blob/774e7828dc31340fbf09e5e5eefb79b1fddc4d22/pkg/sql/opt/norm/rules/join.opt#L179)):*
> ```
>         ...
>         $item:(FiltersItem (Eq (Variable $col:*) (Variable))) &
>             (CanMapJoinOpEqualities $on $col $leftCols:(OutputCols $left) $rightCols:(OutputCols $right))
> ```

If we have a lot of equalities, and we can't Map them, we will recompute this function for each item no? Could we just check it once on the entire `$on`? (I'd think the common case is to have at least one equality)

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41250)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/norm/rules/join.opt, line 179 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41250#-LqbV0Bu8k_2DwAX66XW:-Lqfedej9DKmEiNy5KDX:b-bb6i1u) ([raw file](https://github.com/cockroachdb/cockroach/blob/774e7828dc31340fbf09e5e5eefb79b1fddc4d22/pkg/sql/opt/norm/rules/join.opt#L179)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

If we have a lot of equalities, and we can't Map them, we will recompute this function for each item no? Could we just check it once on the entire `$on`? (I'd think the common case is to have at least one equality)
</blockquote></details>

Good point -- updated so now it just checks once per equivalence group rather than once per equality condition.

**Review by rytaft — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41250#-:-LqgapTI4mtmefgkWzQ9:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, and @rytaft)

**Pull request merged**
