### PR TITLE
sql: deflake TestCopyFromRandom 

### LINKED ISSUE #122330: pkg/sql/copy/copy_test: TestCopyFromRandom failed
pkg/sql/copy/copy_test.TestCopyFromRandom [failed](https://tanzanite.cluster.engflow.com/invocations/default/7ca50a36-034a-4cda-9f5d-92c165c7ccee?testReportRun=1&testReportShard=2&testReportAttempt=1#targets-Ly9wa2cvc3FsL2NvcHk6Y29weV90ZXN0) on master @ [900f8b66a50ca600527856b9bf83ccbbcbef932a](https://github.com/cockroachdb/cockroach/commits/900f8b66a50ca600527856b9bf83ccbbcbef932a):

```
=== RUN   TestCopyFromRandom
    test_log_scope.go:170: test logs captured to: outputs.zip/logTestCopyFromRandom3385764067
    test_log_scope.go:81: use -show-logs to present logs inline
    test_server_shim.go:157: automatically injected an external process virtual cluster under test; see comment at top of test_server_shim.go for details.
I240412 09:42:50.762640 1 (gostd) rand.go:250  [-] 1  random seed: 5058866758784072023
    copy_in_test.go:256: pq: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_ASYNC_WRITE_FAILURE - missing intent on: /Tenant/10/Table/106/1/164/0): "sql txn" meta={id=9f9d04f7 key=/Tenant/10/Table/106/1/0/0 iso=Serializable pri=0.04074592 epo=0 ts=1712914983.020712413,2 min=1712914981.334040366,0 seq=1001} lock=true stat=PENDING rts=1712914983.020712413,2 wto=false gul=1712914981.834040366,0
    panic.go:626: -- test log scope end --
test logs left over in: outputs.zip/logTestCopyFromRandom3385764067
--- FAIL: TestCopyFromRandom (16.05s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>race=true</code>
 - <code>run=1</code>
 - <code>shard=2</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestCopyFromRandom.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-37804

### PR DESCRIPTION
**Pull request by arulajmani**
This test runs COPY using an explicit transaction, which doesn't retry
retriable errors automatically. Write pipelines are one form of such
errors that this test would occasionally run into and flake on. Turn off
write pipelining for this test.

Closes https://github.com/cockroachdb/cockroach/issues/122330

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm:

Do we have any ideas about why this test seemed to suddenly get flaky around 2 months ago?

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125596#-:-O-DTsOKAqySnX-ekkjP:b-7unk3w)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125596#-:-O-DVIng-TNlC3K_UDpK:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/sql/copy_from.go` line 1154 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125596#-O-DV-aT8EeFV7ARfNGo:-O-DV-aT8EeFV7ARfNGp:b-f4piic) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdbe4ef3f12f04aaea6b61f59a935fb674086ebe/pkg/sql/copy_from.go#L1154)):*
> ```Go
> 				// consumes directly from the read buffer, and the data would no
> 				// longer be available during the retry.
> 				if c.implicitTxn && !c.p.SessionData().CopyFromAtomicEnabled && c.p.SessionData().CopyFromRetriesEnabled && errIsRetriable(err) {
> ```

nit: `errIsRetriable` in this condition is now redundant.
___
*[`pkg/sql/copy_from.go` line 1163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125596#-O-DV5kN-heyDpva-mtI:-O-DV5kN-heyDpva-mtJ:b68gkjm) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdbe4ef3f12f04aaea6b61f59a935fb674086ebe/pkg/sql/copy_from.go#L1163)):*
> ```Go
> 					continue
> 				} else {
> 					log.SqlExec.Infof(ctx, "%s is not retrying", c.copyFromAST.String())
> ```

nit: perhaps extend the message with information about txn being implicit or explicit and value of `copy_from_atomic_enabled` session variable.

**Review by arulajmani — COMMENTED** [review]
> Do we have any ideas about why this test seemed to suddenly get flaky around 2 months ago?

I'm not sure -- I tried repro-ing this earlier (admittedly, not very hard), with no luck. All the failures are under race and on engflow, so that might be related. 

TFTRs!

bors r=nvanbenschoten,yuzefovich

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125596#-:-O-DgYH84jCxnFNx51kF:bybxb4q)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @nvanbenschoten and @yuzefovich)

___
*[`pkg/sql/copy_from.go` line 1154 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125596#-O-DV-aT8EeFV7ARfNGo:-O-DgP0X-AysK0kdw-BI:b-t8fyss) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdbe4ef3f12f04aaea6b61f59a935fb674086ebe/pkg/sql/copy_from.go#L1154)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: `errIsRetriable` in this condition is now redundant.
</blockquote></details>

Oops. Fixed.
___
*[`pkg/sql/copy_from.go` line 1163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125596#-O-DV5kN-heyDpva-mtI:-O-DgMOI-w3i1Co0pMOx:b2tqktn) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdbe4ef3f12f04aaea6b61f59a935fb674086ebe/pkg/sql/copy_from.go#L1163)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: perhaps extend the message with information about txn being implicit or explicit and value of `copy_from_atomic_enabled` session variable.
</blockquote></details>

Good call; done.

**Comment by yuzefovich** [comment]
Flake is #125565.

bors r=nvanbenschoten,yuzefovich

**Comment by yuzefovich** [comment]
blathers backport release-24.1

**Pull request merged**
