### PR TITLE
sql: Support `GENERATED ... AS IDENTITY` syntax under `CREATE TABLE`

### PR DESCRIPTION
**Pull request by ZhouXing19**
Touches [#48532](https://github.com/cockroachdb/cockroach/issues/48532)

Note that we didn't implement the corresponding `OVERRIDING SYSTEM VALUE` syntax under `INSERT | UPSERT | UPDATE` statement, nor do we support a customized `sequence_options` for `GENERATED .. AS IDENTITY` yet.

This matches the PostgreSQL syntax: https://www.postgresql.org/docs/current/sql-createtable.html

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
just reviewed commit 1 -- more reviews incoming!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67956#-:-Mg7Qjry9p87dRtFE--I:blydjsd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai and @ZhouXing19)

___
*[pkg/sql/serial.go, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67956#-Mg7Oj9v1X647rIhWVKX:-Mg7Oj9v1X647rIhWVKY:bc0i05v) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8256ed3223ccc6d4f7d73a2b031bc9368ad8700/pkg/sql/serial.go#L58)):*
> ```Go
> // This is a helper function for generateSerialInColumnDef.
> 
> func getNewColDef(
> ```

since this function is so short and it's only used in one place, i think this function should be removed and the logic can be done inline in `generateSerialInColumnDef`
___
*[pkg/sql/serial.go, line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67956#-Mg7OH307_68U9eowCTb:-Mg7OH307_68U9eowCTc:b-sqzl4k) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8256ed3223ccc6d4f7d73a2b031bc9368ad8700/pkg/sql/serial.go#L129)):*
> ```Go
> 	}
> 
> 	seqType := ""
> ```

it looks like seqType is always `""`. i think it should be removed from the return values
___
*[pkg/sql/serial.go, line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67956#-Mg7PuYFAHXROba5BFDk:-Mg7PuYFAHXROba5BFDl:b-2iff3r) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8256ed3223ccc6d4f7d73a2b031bc9368ad8700/pkg/sql/serial.go#L130)):*
> ```Go
> 
> 	seqType := ""
> 	seqOpts := realSequenceOpts
> ```

similar, seqOpts is always the same (and the return value is immediately modified)

so let's remove seqOpts from the return values
___
*[pkg/sql/serial.go, line 141 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67956#-Mg7P4yr3s91KlECfRBz:-Mg7P4yr3s91KlECfRC-:bwuglre) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8256ed3223ccc6d4f7d73a2b031bc9368ad8700/pkg/sql/serial.go#L141)):*
> ```Go
> 	d *tree.ColumnTableDef,
> 	tableName *tree.TableName,
> 	serialNormalizationModePtr *sessiondata.SerialNormalizationMode,
> ```

nit: `serialNormalizationMode` should just be passed as `sessiondata.SerialNormalizationMode`, not as a pointer

the argument is never nil, so it should simplify logic below
___
*[pkg/sql/serial.go, line 236 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67956#-Mg7FpfPCZaCoHnj2GKh:-Mg7FpfPCZaCoHnj2GKi:bq817vv) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8256ed3223ccc6d4f7d73a2b031bc9368ad8700/pkg/sql/serial.go#L236)):*
> ```Go
> 	// To generate a general sequence is the same as generate a serial
> 	// with serial_normalization being 'sql_sequence'
> 	curSerialNormalizationMode := sessiondata.SerialUsesSQLSequences
> ```

hmm i sort of wonder if we should just use `UsesCachedSQLSequences` by default here

maybe we can see what others on the team feel. @ajwerner might want to weigh in as well.


either way, can you create a new github issue for adding support for `sequence_options` when defining a `GENERATED ... AS IDENTITY` column, then add a TODO comment here referencing that?
___
*[pkg/sql/serial.go, line 303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67956#-Mg7Qdi98p9nk2Q26z8y:-Mg7Qdi98p9nk2Q26z8z:bngnz9p) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8256ed3223ccc6d4f7d73a2b031bc9368ad8700/pkg/sql/serial.go#L303)):*
> ```Go
> 		}
> 	} else {
> 		return d, nil, nil, nil, nil
> ```

i think this case should return an assertion error, since this should never happen

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67956)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai and @ZhouXing19)

___
*[pkg/sql/parser/sql.y, line 6718 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67956#-Mg7R0jZ4sYrkmSqt61y:-Mg7R0jZ4sYrkmSqt61z:bnnfuwp) ([raw file](https://github.com/cockroachdb/cockroach/blob/80901e3fde69686a2cbc3f9e90c8618cb09dbc68/pkg/sql/parser/sql.y#L6718)):*
> ```Yacc
>     return 1
>  }
> | generated_always_as IDENTITY
> ```

it might make the rules a little messier, but i think we should match postgres by only allowing `GENERATED ALWAYS AS IDENTITY` or `GENERATED BY DEFAULT AS IDENTITY`. we should not allow `GENERATED AS IDENTITY`

you can achieve this by splitting the previous `generated_as` into two rules:

```
generated_as:
  AS {}
| generated_always_as

generated_always_as:
  GENERATED_ALWAYS ALWAYS AS {}
```

then use the `generated_as` rule for all of the existing rules, but for the new IDENTITY syntax, use `generated_always_as`
___
*[pkg/sql/sem/tree/create.go, line 422 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67956#-Mg7S0Zw6WP_HTApbk9W:-Mg7S0Zx8CQRXfwmFtDI:b19cu23) ([raw file](https://github.com/cockroachdb/cockroach/blob/80901e3fde69686a2cbc3f9e90c8618cb09dbc68/pkg/sql/sem/tree/create.go#L422)):*
> ```Go
> 	Type      ResolvableTypeReference
> 	IsSerial  bool
> 	Generated struct {
> ```

nit: can you name it `GeneratedIdentity`

that way it's not confused with the computed column alternative syntax
___
*[pkg/sql/sem/tree/create.go, line 425 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67956#-Mg7SQHs6z1bqPoULM1i:-Mg7SQHs6z1bqPoULM1j:b-hdypxc) ([raw file](https://github.com/cockroachdb/cockroach/blob/80901e3fde69686a2cbc3f9e90c8618cb09dbc68/pkg/sql/sem/tree/create.go#L425)):*
> ```Go
> 		IsGenerated    bool
> 		GeneratedType  Generatedtype
> 		ConstraintName Name
> ```

what is `ConstraintName` in this context?
___
*[pkg/sql/sem/tree/create.go, line 464 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67956#-Mg7RncDCZv40s94xWYf:-Mg7RncDCZv40s94xWYg:bjs12s6) ([raw file](https://github.com/cockroachdb/cockroach/blob/80901e3fde69686a2cbc3f9e90c8618cb09dbc68/pkg/sql/sem/tree/create.go#L464)):*
> ```Go
> 		IfNotExists bool
> 	}
> 	DisallowExplicitWrite bool
> ```

this DisallowExplicitWrite bool is only true if and only if `GeneratedType == GeneratedAlways`. so i don't think we need `DisallowExplicitWrite` as a separate field
___
*[pkg/sql/sem/tree/create.go, line 688 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67956#-Mg7ZTKN7PJaF-sZmn9k:-Mg7ZTKN7PJaF-sZmn9l:b6cc28v) ([raw file](https://github.com/cockroachdb/cockroach/blob/80901e3fde69686a2cbc3f9e90c8618cb09dbc68/pkg/sql/sem/tree/create.go#L688)):*
> ```Go
> 		ctx.FormatNode(node.DefaultExpr.Expr)
> 	}
> 	if node.Generated.IsGenerated {
> ```

can you add tests to `pkg/sql/parser/testdata/create_table` and `alter_table` for the new syntax?

you can add example statements in this format (with the 4 dashes):

```
CREATE TABLE etc etc
----
```

then run `make test PKG=./pkg/sql/parser TESTS='TestParseDatadriven/$create_table' TESTFLAGS='-rewrite'` to regenerate the file. make sure the syntax parsing works as you expect.
___
*[pkg/sql/sem/tree/pretty.go, line 1839 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67956#-Mg7ZNId269prlj5eN_k:-Mg7ZNId269prlj5eN_l:b-fj4t9d) ([raw file](https://github.com/cockroachdb/cockroach/blob/80901e3fde69686a2cbc3f9e90c8618cb09dbc68/pkg/sql/sem/tree/pretty.go#L1839)):*
> ```Go
> 	//   [[CREATE [IF NOT EXISTS]] FAMILY [name]]
> 	//   [[CONSTRAINT name] DEFAULT expr]
> 	//   [[CONSTRAINT name] GENERATED ALWAYS|BY DEFAULT AS IDENTITY]
> ```

i don't think we want "generated identity" to show up as a constraint. i think this should be removed

**Review by rafiss — CHANGES_REQUESTED** [review]
and one comment on the release note:

```
Release Node (sql): `GENERATED AS IDENTITY` syntax support
```

should be 
```
Release note (sql change): Added support for `GENERATED {ALWAYS | BY DEFAULT} AS IDENTITY`
syntax in a column definition. This will automatically create a sequence for the given column.
This matches PostgreSQL syntax and functionality.
See https://www.postgresql.org/docs/current/sql-createtable.html
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67956#-:-Mg7drju4WAQPMtUl3s3:b-8msm77)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai and @ZhouXing19)

___
*[pkg/sql/logictest/testdata/logic_test/create_table, line 481 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67956#-Mg7d_JM622xZWewA8C3:-Mg7d_JM622xZWewA8C4:bxk1ehi) ([raw file](https://github.com/cockroachdb/cockroach/blob/4604c5b6e3f3455d6daa58c1d8b30981f4489f67/pkg/sql/logictest/testdata/logic_test/create_table#L481)):*
> ```
> subtest generated_as_identity
> statement ok
> CREATE TABLE hello_t (x INT, y INT);
> ```

nit: remove the `hello_t` table
___
*[pkg/sql/logictest/testdata/logic_test/create_table, line 511 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67956#-Mg7dgV-2p3t572o8Pjk:-Mg7dgV-2p3t572o8Pjl:b-yflpwc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4604c5b6e3f3455d6daa58c1d8b30981f4489f67/pkg/sql/logictest/testdata/logic_test/create_table#L511)):*
> ```
> 
> statement ok
> CREATE TABLE generated_by_default_t (a INT UNIQUE, b INT GENERATED BY DEFAULT AS IDENTITY);
> ```

can you also add a test to show the output of `SHOW CREATE TABLE generated_always_t` and `SHOW CREATE TABLE generated_by_default_t`?

**Comment by ZhouXing19** [comment]
___
*[pkg/sql/sem/tree/pretty.go, line 1839 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67956#-Mg7ZNId269prlj5eN_k:-Mg7jKrx2IguwbmE-4EM:by9czia) ([raw file](https://github.com/cockroachdb/cockroach/blob/80901e3fde69686a2cbc3f9e90c8618cb09dbc68/pkg/sql/sem/tree/pretty.go#L1839)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i don't think we want "generated identity" to show up as a constraint. i think this should be removed
</blockquote></details>

It seems that it won't pass `VerifyStatementPrettyRoundtrip` without adding `GENERATED AS IDENTITY` in this part. (check https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/logic.go#L2620)

**Comment by ZhouXing19** [comment]
___
*[pkg/sql/serial.go, line 303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67956#-Mg7Qdi98p9nk2Q26z8y:-MgClXyz07bD6XQMUcIK:bm6x3ir) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8256ed3223ccc6d4f7d73a2b031bc9368ad8700/pkg/sql/serial.go#L303)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think this case should return an assertion error, since this should never happen
</blockquote></details>

I think we should keep what it is, since we expect it to return the original `tree.ColumnTableDef` if it's not a serial-like column. Check the caller of the original `generateSerialInColumnDef` [here](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/add_column.go#L52).

**Review by ZhouXing19 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67956)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss, @RichardJCai, and @ZhouXing19)

___
*[pkg/sql/serial.go, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67956#-Mg7Oj9v1X647rIhWVKX:-MgDFVYWBe0Tj1kMCoAU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8256ed3223ccc6d4f7d73a2b031bc9368ad8700/pkg/sql/serial.go#L58)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

since this function is so short and it's only used in one place, i think this function should be removed and the logic can be done inline in `generateSerialInColumnDef`
</blockquote></details>

Done.
___
*[pkg/sql/serial.go, line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67956#-Mg7OH307_68U9eowCTb:-MgDFadoDpKI9Aogm6uE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8256ed3223ccc6d4f7d73a2b031bc9368ad8700/pkg/sql/serial.go#L129)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

it looks like seqType is always `""`. i think it should be removed from the return values
</blockquote></details>

Done.
___
*[pkg/sql/serial.go, line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67956#-Mg7PuYFAHXROba5BFDk:-MgDFdFc-L01npATJ-Ia:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8256ed3223ccc6d4f7d73a2b031bc9368ad8700/pkg/sql/serial.go#L130)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

similar, seqOpts is always the same (and the return value is immediately modified)

so let's remove seqOpts from the return values
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/create_table, line 511 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67956#-Mg7dgV-2p3t572o8Pjk:-MgDFj1qEwGB5ghnz0HS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4604c5b6e3f3455d6daa58c1d8b30981f4489f67/pkg/sql/logictest/testdata/logic_test/create_table#L511)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

can you also add a test to show the output of `SHOW CREATE TABLE generated_always_t` and `SHOW CREATE TABLE generated_by_default_t`?
</blockquote></details>

Done.
___
*[pkg/sql/parser/sql.y, line 6718 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67956#-Mg7R0jZ4sYrkmSqt61y:-MgDFl4I734Y7Rtx9ayd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/80901e3fde69686a2cbc3f9e90c8618cb09dbc68/pkg/sql/parser/sql.y#L6718)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

it might make the rules a little messier, but i think we should match postgres by only allowing `GENERATED ALWAYS AS IDENTITY` or `GENERATED BY DEFAULT AS IDENTITY`. we should not allow `GENERATED AS IDENTITY`

you can achieve this by splitting the previous `generated_as` into two rules:

```
generated_as:
  AS {}
| generated_always_as

generated_always_as:
  GENERATED_ALWAYS ALWAYS AS {}
```

then use the `generated_as` rule for all of the existing rules, but for the new IDENTITY syntax, use `generated_always_as`
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/create.go, line 464 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67956#-Mg7RncDCZv40s94xWYf:-MgDFoK48mO61hMdHWKw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/80901e3fde69686a2cbc3f9e90c8618cb09dbc68/pkg/sql/sem/tree/create.go#L464)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this DisallowExplicitWrite bool is only true if and only if `GeneratedType == GeneratedAlways`. so i don't think we need `DisallowExplicitWrite` as a separate field
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/create.go, line 688 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67956#-Mg7ZTKN7PJaF-sZmn9k:-MgDFp6jCb03bTLB7j98:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/80901e3fde69686a2cbc3f9e90c8618cb09dbc68/pkg/sql/sem/tree/create.go#L688)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

can you add tests to `pkg/sql/parser/testdata/create_table` and `alter_table` for the new syntax?

you can add example statements in this format (with the 4 dashes):

```
CREATE TABLE etc etc
----
```

then run `make test PKG=./pkg/sql/parser TESTS='TestParseDatadriven/$create_table' TESTFLAGS='-rewrite'` to regenerate the file. make sure the syntax parsing works as you expect.
</blockquote></details>

Done.

**Review by mgartner — COMMENTED** [review]
Do we need to make sure 21.2 is finalized before allowing users to create `GENERATED ALWAYS AS IDENTITY` columns? We do this for expression indexes here: https://github.com/cockroachdb/cockroach/blob/a5414f2e4c64f37b383bd1ac00c7f7d940a0a5d6/pkg/sql/create_index.go#L389-L393

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67956#-:-MgGj2wLAXSVpzxJqOBX:b-cxkmcu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss, @RichardJCai, and @ZhouXing19)

**Comment by rafiss** [comment]
> Do we need to make sure 21.2 is finalized before allowing users to create GENERATED ALWAYS AS IDENTITY columns? We do this for expression indexes here: 

+1 to adding a version gate

**Pull request closed without merging**
