### PR TITLE
raft: pass logSlice from maybeAppend to append

### PR DESCRIPTION
**Pull request by pav-kv**
This PR propagates the appended `logSlice` down the stack from `maybeAppend` to `append`. All appends should use this type for readability and safety. Ultimately, the `logSlice` will be passed from the append method to `unstable.truncateAndAppend` which will implement a few more safety checks and use the `logSlice.term` to track the "last accepted term".

This change helped fixing a bunch of bugs in tests that initialized `RawNode` or `raftLog` incorrectly.

Part of #124440

### CODE REVIEW

**Comment by pav-kv** [comment]
@nvanbenschoten PTAL. Only the last 2 commits are contentful. The commits before it are preparatory clean-up/no-ops in tests (each commit does one thing at a time for easier review), so that it's obvious how the last 2 commits affect the tests (particularly some tests were incorrect).

This PR is a stepping stone. Next up: propagate the `logSlice` to `unstable.truncateAndAppend`, and make `unstable` to be a `logSlice` itself. The `logSlice.term` carries the "leader term" / "accepted term" which will then replace the [accTerm](https://github.com/cockroachdb/cockroach/blob/d13253527955eaa2da09394b8a2729627ab25c48/pkg/raft/raft.go#L362-L363) and be used for a safe log write/ack protocol.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, 2 of 2 files at r9, 1 of 1 files at r10, 1 of 1 files at r11, 5 of 5 files at r12, 6 of 6 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126474#-:-O0qRcLXD2cSzdwo0fPa:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pav-kv)

___
*[`pkg/raft/log.go` line 107 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/126474#-O0qPiVmDiYdPcGHwQOg:-O0qPiVmDiYdPcGHwQOh:bnm13vk) ([raw file](https://github.com/cockroachdb/cockroach/blob/be28ce6e9af77ee17555c007662bb758a7701f1b/pkg/raft/log.go#L107)):*
> if any entry is overwritten

Is overwritten the right term for the condition here? That's the effect, not the cause, right? Can we rephrase to make this clearer?
___
*[`pkg/raft/log_test.go` line 982 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126474#-O0qIeON2DFLnr3LiDfj:-O0qIeON2DFLnr3LiDfk:b-dtvj18) ([raw file](https://github.com/cockroachdb/cockroach/blob/a21f3da8f8cc8f0d9cc5e5ed91aca2a53b9f542e/pkg/raft/log_test.go#L982)):*
> ```Go
> }
> 
> // append generates a valid logSlice of entries appended after the given entry
> ```

Should we perform a similar rename for `index.terms` and `index.termRange`?
___
*[`pkg/raft/log_test.go` line 81 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/126474#-O0qJapG36Rpge6PzA1C:-O0qJapG36Rpge6PzA1D:bi02ktp) ([raw file](https://github.com/cockroachdb/cockroach/blob/79cc920b4fd3576aca1cb865347686e5d6fe0dfe/pkg/raft/log_test.go#L81)):*
> ```Go
> 	}{
> 		// Log starts from index 1.
> 		{sl: entryID{}.append(2, 2, 5, 5, 5), index: 100, term: 2, want: 100}, // ErrUnavailable
> ```

Consider pulling out a `noSnap` variable (or something along those lines, `empty`?) so that you can name the `entryID{}` case, like you did with `snap10`.
___
*[`pkg/raft/log_test.go` line 186 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/126474#-O0qLIiJDRlAH33QF4qQ:-O0qLIiJDRlAH33QF4qR:b-hrbogz) ([raw file](https://github.com/cockroachdb/cockroach/blob/332788de7881db8d0f0ab2f4a18c4ba5ae1c9973/pkg/raft/log_test.go#L186)):*
> ```Go
> 			require.NoError(t, storage.Append(init.entries))
> 			raftLog := newLog(storage, discardLogger)
> 			raftLog.committed = commit
> ```

`raftLog.commitTo(commit)`?
___
*[`pkg/raft/log_test.go` line 270 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/126474#-O0qM3jtEVycReY91vGO:-O0qM3jtEVycReY91vGP:b-58k375) ([raw file](https://github.com/cockroachdb/cockroach/blob/4de26055e66ddb74b981f2a9c8494f74b1125c95/pkg/raft/log_test.go#L270)):*
> ```Go
> func TestCompactionSideEffects(t *testing.T) {
> 	// Populate the log with 1000 entries; 750 in stable storage and 250 in unstable.
> 	stable := entryID{}.append(intRange[uint64](1, 751)...)
> ```

Type inference couldn't figure this one out?

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126474)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pav-kv)

___
*[`pkg/raft/log.go` line 107 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/126474#-O0qPiVmDiYdPcGHwQOg:-O0q_b_H6iexi17TagtV:b-8558o9) ([raw file](https://github.com/cockroachdb/cockroach/blob/be28ce6e9af77ee17555c007662bb758a7701f1b/pkg/raft/log.go#L107)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> if any entry is overwritten

Is overwritten the right term for the condition here? That's the effect, not the cause, right? Can we rephrase to make this clearer?
</blockquote></details>

Reworded/elaborated the comment.

That's the issue with the current implementation (will be improved in the next PRs): it's both the cause and the effect. The code does not clearly distinguish the case when the truncation is permitted (the accepted term goes up), or not (the write is made under the same accepted term). It detects the former case when it observes at least one overwritten entry.
___
*[`pkg/raft/log_test.go` line 982 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/126474#-O0qIeON2DFLnr3LiDfj:-O0qkT3UBbWqjnQt78wC:b3hy0qc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a21f3da8f8cc8f0d9cc5e5ed91aca2a53b9f542e/pkg/raft/log_test.go#L982)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we perform a similar rename for `index.terms` and `index.termRange`?
</blockquote></details>

Punting for now. Will be clearer after more work on this code, but these helpers are possibly not needed, at least the `termRange(from, to)` can be replaced with `terms(intRange(from, to)...)`.

With `index.term`, it could be something like `after(index).append(terms...)`, but will leave this possibility for future PRs.
___
*[`pkg/raft/log_test.go` line 81 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/126474#-O0qJapG36Rpge6PzA1C:-O0qXc5a3qoUJ93i_4E2:bnvxw6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/79cc920b4fd3576aca1cb865347686e5d6fe0dfe/pkg/raft/log_test.go#L81)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Consider pulling out a `noSnap` variable (or something along those lines, `empty`?) so that you can name the `entryID{}` case, like you did with `snap10`.
</blockquote></details>

Good idea, added a `noSnap` variable.
___
*[`pkg/raft/log_test.go` line 186 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/126474#-O0qLIiJDRlAH33QF4qQ:-O0qlqjF7JyVrRBo0aaA:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/332788de7881db8d0f0ab2f4a18c4ba5ae1c9973/pkg/raft/log_test.go#L186)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`raftLog.commitTo(commit)`?
</blockquote></details>

Done
___
*[`pkg/raft/log_test.go` line 270 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/126474#-O0qM3jtEVycReY91vGO:-O0qWGNt69bkZGS2q_I-:b-qi94d4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4de26055e66ddb74b981f2a9c8494f74b1125c95/pkg/raft/log_test.go#L270)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Type inference couldn't figure this one out?
</blockquote></details>

No. Just tried removing `[uint64]`, doesn't work.

**Comment by pav-kv** [comment]
TFTR!

r=nvanbenschoten

**Review by nvb — APPROVED** [review]
> Reviewed 1 of 2 files at r18, 6 of 6 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126474)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @pav-kv)

**Pull request merged**
