### PR TITLE
SQL: Skip scan of unfiltered spans during delete if possible. 

### PR DESCRIPTION
**Pull request by dt**
```
name                   old time/op  new time/op  delta
Delete1_Cockroach-8     703µs ± 5%   532µs ± 9%  -24.34%  (p=0.000 n=39+29)
Delete10_Cockroach-8   1.63ms ± 3%  1.20ms ± 5%  -26.68%  (p=0.000 n=40+29)
Delete100_Cockroach-8  9.55ms ± 5%  7.10ms ± 6%  -25.69%  (p=0.000 n=40+28)
```

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4444)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/delete.go, line 105 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KAkiOcYEIBF-aGWnrFj:-KAkiOcYEIBF-aGWnrFk:-636763025) ([raw file](https://github.com/cockroachdb/cockroach/blob/db0113c8a5cc21ae11f14d4dbc505c9a5847af52/sql/delete.go#L105)):*
@RaduBerinde, @andreimatei PTAL. I'll let you guys decide whether to merge this or not. I was primarily interested in seeing what performance improvement we would see by skipping the scan when possible. We should see a similar perf win from creating a `ScanFilterDelete` range-level operation.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444)*

**Comment by petermattis** [comment]
That's a very nice win, though I was guessing it would be higher. 

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-:-KAkiupgwL6bAZJ2lc3I:520277872)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[client/batch.go, line 160 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KAkwSBCbUiTlINp9gCb:-KAkwSBDuGmb2QRKoG7F:903729805) ([raw file](https://github.com/cockroachdb/cockroach/blob/db0113c8a5cc21ae11f14d4dbc505c9a5847af52/client/batch.go#L160)):*
This kind of name leads to a lot of confusion. It is not the number of rows (which KV doesn't even know), it is the number of *keys*. We use the same for scans and we should fix that as well.

---

*[sql/delete.go, line 173 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KAkx8ZPbRKE36kVfJHp:-KAkx8ZPbRKE36kVfJHq:1800117684) ([raw file](https://github.com/cockroachdb/cockroach/blob/db0113c8a5cc21ae11f14d4dbc505c9a5847af52/sql/delete.go#L173)):*
This is not correct. We actually don't know the number of rows, this is the number of deleted keys.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444)*

**Comment by dt** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/delete.go, line 173 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KAkx8ZPbRKE36kVfJHp:-KAl-nDFf5nOewlLphP9:1384825931) ([raw file](https://github.com/cockroachdb/cockroach/blob/db0113c8a5cc21ae11f14d4dbc505c9a5847af52/sql/delete.go#L173)):*
yeah, see discussion in gitter

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444)*

**Comment by tamird** [comment]
Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[client/batch.go, line 160 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KAkwSBCbUiTlINp9gCb:-KAl4RdQE5tvSJGjaYcT:1632628790) ([raw file](https://github.com/cockroachdb/cockroach/blob/db0113c8a5cc21ae11f14d4dbc505c9a5847af52/client/batch.go#L160)):*
On the other hand, it's consistent with the naming in client/db.go.

I'd just file an issue and do it separately.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444)*

**Comment by dt** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[client/batch.go, line 160 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KAkwSBCbUiTlINp9gCb:-KAl4lXAC_bupzFE2-_U:-1833759466) ([raw file](https://github.com/cockroachdb/cockroach/blob/db0113c8a5cc21ae11f14d4dbc505c9a5847af52/client/batch.go#L160)):*
It's going to have to go away anyway and will instead be the deleted keys -- if we decide we want to merge something like this at all.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444)*

**Comment by dt** [comment]
Okay, little refactor to send back deleted keys for DeleteRange requests and then look at them to count rows deleted seems to work, and, it even looks like the speedup is still there. I still want to try a couple more complicated benchmarks before I'm sold though.

---

Review status: 1 of 16 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-:-KAn-HZ5BOSvmoVwOYe8:-1598455035)*

**Comment by tamird** [comment]
Reviewed 15 of 15 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[server/server_test.go, line 363 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KAoFUgGgsuDt7eeeY9b:-KAoFUgGgsuDt7eeeY9c:1067656611) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c0a344065767932c08806c31570747deac3510c/server/server_test.go#L363)):*
rather than asserting on lengths, can't you assert on the values here?

---

*[sql/delete.go, line 71 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KAoGQ1mobs9oPUhzMvh:-KAoGQ1mobs9oPUhzMvi:58454317) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c0a344065767932c08806c31570747deac3510c/sql/delete.go#L71)):*
nit: s/additional/secondary/

---

*[sql/delete.go, line 87 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KAoGeIpZfWbA5ZW3rBj:-KAoGeIpZfWbA5ZW3rBk:-1173781638) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c0a344065767932c08806c31570747deac3510c/sql/delete.go#L87)):*
i believe we hide most of this output under V(2). I know this is provisional, just sayin'. Also no periods in log messages.

---

*[sql/scan.go, line 335 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KAoG7kzp-68CLddkF8O:-KAoG7l-vem9l6iGmtlh:1722324036) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c0a344065767932c08806c31570747deac3510c/sql/scan.go#L335)):*
this is a nice refactor, but deserves its own commit

---

*[storage/engine/mvcc.go, line 1071 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KAoFkePtTVjRKM37Tgn:-KAoFkePtTVjRKM37Tgo:-1920683664) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c0a344065767932c08806c31570747deac3510c/storage/engine/mvcc.go#L1071)):*
nit: probably possible to share code between these variants using a closure that is called with (key, err) for each key

---

*[storage/engine/mvcc_test.go, line 1258 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KAoFJ9x6rrLWPvd1vs7:-KAoFJ9x6rrLWPvd1vs8:-839128644) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c0a344065767932c08806c31570747deac3510c/storage/engine/mvcc_test.go#L1258)):*
while you're fixing this fallout, do you think it's worth asserting on the value, rather than just the length?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[storage/engine/mvcc.go, line 1071 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KAoFkePtTVjRKM37Tgn:-KAobOMstI0pclbNhPas:1076406708) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c0a344065767932c08806c31570747deac3510c/storage/engine/mvcc.go#L1071)):*
Related, we should probably be using `MVCCIterate` instead of `MVCCScan` here. Even better would be to delete the keys as they are encountered using the same iterator as the scan instead of creating one iterator for the scan and another for the deletion. Let's file an issue to experiment with that change.

---

*[storage/replica_command.go, line 243 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KAobsVQNw-0y5hi8Y1Z:-KAobsVQNw-0y5hi8Y1_:2105444897) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c0a344065767932c08806c31570747deac3510c/storage/replica_command.go#L243)):*
This is going to pessimize truncating/dropping a table which also uses `DeleteRange` but doesn't care about the returned keys. I thought there was a suggestion to add a flag to the `DeleteRange` RPC indicating whether the keys should be returned.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[sql/delete.go, line 178 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KAp1aF7-rbeFQnxK3sf:-KAp1aF8C6sOHtZQAmmZ:962304357) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c0a344065767932c08806c31570747deac3510c/sql/delete.go#L178)):*
I wonder it this loop and the normal scan loop could be unified. Instead of having a new `Keys` field in the result, you could populate `Result.Rows` with the keys and empty values. That might be sufficient to use a `scanNode` for iterating over the key/value pairs instead of this separate loop. Or it might not. I haven't looked at the details of this thoroughly.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444)*

**Comment by dt** [comment]
Review status: 2 of 21 files reviewed at latest revision, 11 unresolved discussions.

---

*[server/server_test.go, line 363 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KAoFUgGgsuDt7eeeY9b:-KAvjjA9TMShA2h27-De:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c0a344065767932c08806c31570747deac3510c/server/server_test.go#L363)):*
Done.

---

*[sql/delete.go, line 173 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KAkx8ZPbRKE36kVfJHp:-KAvjFpNiXD9eDmMHgyc:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/db0113c8a5cc21ae11f14d4dbc505c9a5847af52/sql/delete.go#L173)):*
Done.

---

*[sql/delete.go, line 71 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KAoGQ1mobs9oPUhzMvh:-KAvklzLfONRVJESwFVo:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c0a344065767932c08806c31570747deac3510c/sql/delete.go#L71)):*
Done.

---

*[sql/delete.go, line 87 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KAoGeIpZfWbA5ZW3rBj:-KAvkmI1CadAo32YiCcz:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c0a344065767932c08806c31570747deac3510c/sql/delete.go#L87)):*
Done.

---

*[sql/scan.go, line 335 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KAoG7kzp-68CLddkF8O:-KAvjEtqUf0E28xVuKZw:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c0a344065767932c08806c31570747deac3510c/sql/scan.go#L335)):*
Done.

---

*[storage/engine/mvcc.go, line 1071 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KAoFkePtTVjRKM37Tgn:-KAvjDWBz5ZvkDK4fx-s:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c0a344065767932c08806c31570747deac3510c/storage/engine/mvcc.go#L1071)):*
Done.

---

*[storage/engine/mvcc_test.go, line 1258 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KAoFJ9x6rrLWPvd1vs7:-KAvjCiNhixXWIWdx8v-:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c0a344065767932c08806c31570747deac3510c/storage/engine/mvcc_test.go#L1258)):*
Done.

---

*[storage/replica_command.go, line 243 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KAobsVQNw-0y5hi8Y1Z:-KAvjBwsYdfjAova8nUn:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c0a344065767932c08806c31570747deac3510c/storage/replica_command.go#L243)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444)*

**Comment by dt** [comment]
Plumbed key-returning through the delete range request path, so I'm pretty sure this is no longer known-incorrect.

This might be easier to review if I closed this PR and opened a fresh one, since I pulled some refactors out that have since landed?

---

Review status: 2 of 21 files reviewed at latest revision, 10 unresolved discussions.

---

*[client/batch.go, line 160 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KAkwSBCbUiTlINp9gCb:-KAvnloXPZseFrCOT8cU:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/db0113c8a5cc21ae11f14d4dbc505c9a5847af52/client/batch.go#L160)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-:-KAvlYH6oCy2ehlfaXm1:-1632099440)*

**Comment by petermattis** [comment]
LGTM. I'd still like @RaduBerinde and @andreimatei to take a look at this as it makes the `Delete` code a bit hairier. 

---

Reviewed 4 of 4 files at r1, 15 of 15 files at r2.
Review status: 2 of 21 files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-:-KAvnHKrT6Ff2NaOU55t:1281416235)*

**Comment by tamird** [comment]
Reviewed 19 of 19 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[server/server_test.go, line 363 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KAoFUgGgsuDt7eeeY9b:-KAvtpLe2wuLQzykSFfU:-790671668) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c0a344065767932c08806c31570747deac3510c/server/server_test.go#L363)):*
Was there a reason not to use `reflect.DeepEqual` here?

---

*[sql/scan.go, line 335 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KAvuNyU2UU0ECfub-9V:-KAvuNyU2UU0ECfub-9W:-561020566) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f0e341a80934a414f9c24d3e6775f6bf8b09f80/sql/scan.go#L335)):*
s/performs/perform/

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444)*

**Comment by andreimatei** [comment]
The numbers definitely look attractive. On the other hand I'm pretty convinced we'll figure out a proper way to do "remote side deletes" soonish, that'll work with filters, (secondary) indexes and returning the row count (and by "pretty convinced", I mean we have to :) ).
So I dunno... I guess I'm not opposed to landing this code for now.

---

Review status: 18 of 21 files reviewed at latest revision, 11 unresolved discussions.

---

*[sql/delete.go, line 83 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KB9C3yHLOlnPBPNliTP:-KB9C3yHLOlnPBPNliTQ:126755971) ([raw file](https://github.com/cockroachdb/cockroach/blob/32e3f6ccb661cf06e83a912325c15449693cf14d/sql/delete.go#L83)):*
this variable deserves a comment, also explaining the rationale for the whole next block

---

*[sql/delete.go, line 111 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KB9GLY9ZfNIx0wGrcHT:-KB9GLY9ZfNIx0wGrcHU:-677625981) ([raw file](https://github.com/cockroachdb/cockroach/blob/32e3f6ccb661cf06e83a912325c15449693cf14d/sql/delete.go#L111)):*
how about putting the final `if scanSkipped` block from this method here, maybe called via a defer to run it after the txn run? Or just split deletion-via-scanSkipped into its separate function, and duplicate the code that commits the batch.

---

*[sql/delete.go, line 115 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KB9FG7MLsggVZDxisOa:-KB9FG7MLsggVZDxisOb:1656203850) ([raw file](https://github.com/cockroachdb/cockroach/blob/32e3f6ccb661cf06e83a912325c15449693cf14d/sql/delete.go#L115)):*
make this a separate function? `createDeleteBatch()`

---

*[sql/delete.go, line 174 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KB9DmEKtDJsrpPCOp8Q:-KB9DmELBHVf_sHC_911:-1848262598) ([raw file](https://github.com/cockroachdb/cockroach/blob/32e3f6ccb661cf06e83a912325c15449693cf14d/sql/delete.go#L174)):*
please add a comment for this block, explaining that it's a perf optimization applicable under some circumstances. Better yet, make this a separate function, `countDeletedRows(b.Results)`?
Unless Peter's suggestion below is actionable somehow (I don't see how exactly).

---

*[sql/delete.go, line 192 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KB9EsQV02UIdS3HUulp:-KB9EsQV02UIdS3HUulq:-479393447) ([raw file](https://github.com/cockroachdb/cockroach/blob/32e3f6ccb661cf06e83a912325c15449693cf14d/sql/delete.go#L192)):*
don't we need to accumulate all row counts into one result?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-:-KB9FNNLMQtLiNpT-dsQ:-1575253642)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444)*

**Comment by dt** [comment]
Review status: 15 of 21 files reviewed at latest revision, 9 unresolved discussions.

---

*[server/server_test.go, line 363 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KAoFUgGgsuDt7eeeY9b:-KAw8C6aur1MUeUL50_Q:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c0a344065767932c08806c31570747deac3510c/server/server_test.go#L363)):*
Done.

---

*[sql/delete.go, line 111 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KB9GLY9ZfNIx0wGrcHT:-KBEZSDdqC4ApqbR4bu3:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/32e3f6ccb661cf06e83a912325c15449693cf14d/sql/delete.go#L111)):*
Done.

---

*[sql/delete.go, line 115 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KB9FG7MLsggVZDxisOa:-KBDyaUNYfI5dOj_vtMW:-400887164) ([raw file](https://github.com/cockroachdb/cockroach/blob/32e3f6ccb661cf06e83a912325c15449693cf14d/sql/delete.go#L115)):*
Hm, would need to pass it almost everything that is in scope so I'm not sure if it is worth it, particularly with the other stuff now pulled out.

---

*[sql/delete.go, line 174 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KB9DmEKtDJsrpPCOp8Q:-KBE04hlylro78MZ2tfU:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/32e3f6ccb661cf06e83a912325c15449693cf14d/sql/delete.go#L174)):*
Done.

---

*[sql/delete.go, line 192 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KB9EsQV02UIdS3HUulp:-KBDz5TJlzClFDpv-m4t:1634778281) ([raw file](https://github.com/cockroachdb/cockroach/blob/32e3f6ccb661cf06e83a912325c15449693cf14d/sql/delete.go#L192)):*
what do you mean? for every new key in every batch of results, it's appending a row to `result.rows`, right?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444)*

**Comment by tamird** [comment]
Reviewed 6 of 6 files at r5.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444)*

**Comment by andreimatei** [comment]
LGTM thanks

---

Review status: 20 of 22 files reviewed at latest revision, 10 unresolved discussions.

---

*[sql/delete.go, line 210 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KBKGbmnZx6ODRLFf6_w:-KBKGbmnZx6ODRLFf6_x:1536089260) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b72e0220d00269205e29513840f5f875baf00b1/sql/delete.go#L210)):*
as discussed, consider doing readIndexKey() only when the prefix changes

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-:-KBKGu4P_1bOfEkDE7wh:-82034416)*

**Comment by dt** [comment]
Review status: 15 of 22 files reviewed at latest revision, 10 unresolved discussions.

---

*[sql/delete.go, line 105 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KAkiOcYEIBF-aGWnrFj:-KBKP5c2Xx22gSg52zHB:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/db0113c8a5cc21ae11f14d4dbc505c9a5847af52/sql/delete.go#L105)):*
Done.

---

*[sql/delete.go, line 178 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KAp1aF7-rbeFQnxK3sf:-KBKPLRMqdVcYwM9CYba:-1571658195) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c0a344065767932c08806c31570747deac3510c/sql/delete.go#L178)):*
With the addition of the fast bail-out andre suggested below, this would be kinda messy to unify.

---

*[sql/delete.go, line 83 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KB9C3yHLOlnPBPNliTP:-KBKPlKZvjM90bQzSbYN:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/32e3f6ccb661cf06e83a912325c15449693cf14d/sql/delete.go#L83)):*
Done.

---

*[sql/delete.go, line 210 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444#-KBKGbmnZx6ODRLFf6_w:-KBKNo02W2hYSpZQlWR6:-2272763) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b72e0220d00269205e29513840f5f875baf00b1/sql/delete.go#L210)):*
```
name                   old time/op    new time/op    delta
Delete1_Cockroach-8       554µs ± 2%     561µs ± 5%    ~      (p=0.661 n=9+10)
Delete10_Cockroach-8     1.71ms ± 2%    1.73ms ± 3%    ~     (p=0.436 n=10+10)
Delete100_Cockroach-8    12.6ms ± 4%    12.9ms ± 6%    ~      (p=0.133 n=9+10)

name                   old alloc/op   new alloc/op   delta
Delete1_Cockroach-8      28.3kB ± 0%    28.3kB ± 0%    ~      (p=0.523 n=7+10)
Delete10_Cockroach-8     83.8kB ± 0%    83.6kB ± 0%  -0.25%   (p=0.001 n=9+10)
Delete100_Cockroach-8     642kB ± 0%     639kB ± 0%  -0.36%    (p=0.000 n=9+7)

name                   old allocs/op  new allocs/op  delta
Delete1_Cockroach-8         442 ± 0%       439 ± 0%  -0.68%    (p=0.000 n=9+8)
Delete10_Cockroach-8      1.20k ± 0%     1.17k ± 0%  -2.52%   (p=0.000 n=10+7)
Delete100_Cockroach-8     8.45k ± 0%     8.15k ± 0%  -3.55%    (p=0.000 n=9+9)
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4444)*

**Pull request merged**
