### PR TITLE
sql,backupccl: add more tests for user ID migrations

### PR DESCRIPTION
**Pull request by andyyang890**
**sql: add mixed version test for system.privileges user ID migration**

This patch adds a mixed version logic test that ensures granting of
system privileges continues to work properly in a cluster that has
both 22.2 and 23.1 nodes. The relevant version gate being tested here
is V23_1SystemPrivilegesTableHasUserIDColumn.

Release note: None

---

**sql: add mixed version test for system.database_role_settings user IDs**

This patch adds a mixed version logic test that ensures setting default
session variables continues to work properly in a cluster that has
both 22.2 and 23.1 nodes. The relevant version gate being tested here
is V23_1DatabaseRoleSettingsHasRoleIDColumn.

Release note: None

---

**backupccl: update TestRestoreOldVersions subtest for system.privileges**

This patch updates the TestRestoreOldVersions subtest for the
system.privileges table to also test that a row for the public
role is correctly restored.

Release note: None

---

Part of #87079 
Part of #92342

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
lgtm!

**Comment by andyyang890** [comment]
bors r=rafiss

**Comment by andyyang890** [comment]
seems like bors is stuck

bors r-

**Comment by andyyang890** [comment]
bors r=rafiss

**Pull request merged**
