### PR TITLE
kvserver: don't fail a split because of failed stats recomputation

### LINKED ISSUE #121262: kv/kvnemesis: TestKVNemesisSingleNode failed
kv/kvnemesis.TestKVNemesisSingleNode [failed](https://tanzanite.cluster.engflow.com/invocations/default/da29002a-1e41-4562-9347-1324956473a8?testReportRun=7&testReportShard=1&testReportAttempt=1#targets-Ly9wa2cva3Yva3ZuZW1lc2lzOmt2bmVtZXNpc190ZXN0) on master @ [460707194644edbf4c6258d09b46d9877c8eefa6](https://github.com/cockroachdb/cockroach/commits/460707194644edbf4c6258d09b46d9877c8eefa6):

```
=== RUN   TestKVNemesisSingleNode
    test_log_scope.go:170: test logs captured to: outputs.zip/logTestKVNemesisSingleNode3458089655
    test_log_scope.go:81: use -show-logs to present logs inline
    kvnemesis_test.go:328: seed: 6297214651202231189
    kvnemesis_test.go:235: kvnemesis logging to /var/lib/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/testlogs/pkg/kv/kvnemesis/kvnemesis_test/run_7_of_30/test.outputs/kvnemesis3065144168
    kvnemesis.go:178: error applying x.AdminSplit(ctx, tk(17558946769533644915), hlc.MaxTimestamp) // failed to re-compute MVCCStats pre split: descriptor mismatch; range likely merged: failed to re-compute MVCCStats pre split: descriptor mismatch; range likely merged
    kvnemesis.go:213: failures(verbose): /var/lib/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/testlogs/pkg/kv/kvnemesis/kvnemesis_test/run_7_of_30/test.outputs/kvnemesis3065144168/failures
        repro steps: /var/lib/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/testlogs/pkg/kv/kvnemesis/kvnemesis_test/run_7_of_30/test.outputs/kvnemesis3065144168/repro.go
        rangefeed KVs: /var/lib/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/testlogs/pkg/kv/kvnemesis/kvnemesis_test/run_7_of_30/test.outputs/kvnemesis3065144168/kvs-rangefeed.txt
        scan KVs: /var/lib/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/testlogs/pkg/kv/kvnemesis/kvnemesis_test/run_7_of_30/test.outputs/kvnemesis3065144168/kvs-scan.txt
    kvnemesis_test.go:356: [0] proposed: 815
    kvnemesis_test.go:358: [0] reproposed unchanged: 66
    kvnemesis_test.go:360: [0] reproposed with new LAI: 7
    kvnemesis_test.go:365: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/kv/kvnemesis/pkg/kv/kvnemesis/kvnemesis_test.go:365
        	            				github.com/cockroachdb/cockroach/pkg/kv/kvnemesis/pkg/kv/kvnemesis/kvnemesis_test.go:275
        	Error:      	Should be zero, but was 1
        	Test:       	TestKVNemesisSingleNode
        	Messages:   	kvnemesis detected failures
    panic.go:626: -- test log scope end --
test logs left over in: outputs.zip/logTestKVNemesisSingleNode3458089655
--- FAIL: TestKVNemesisSingleNode (6.97s)
```

Parameters:
 - <code>attempt=1</code>
 - <code>run=7</code>
 - <code>shard=1</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestKVNemesisSingleNode.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-37160

### PR DESCRIPTION
**Pull request by miraradeva**
It is possible that the pre-split stats recomputation fails because the range descriptor changed. Splits already handle range descriptor changes by returning a bening error, which will later be retried with the new descriptor.

This patch logs a warning if the pre-split stats recomputation failed, and lets the descriptor-changed error be handled later on by the split.

Fixes: #121262

Release note: None

### CODE REVIEW

**Comment by miraradeva** [comment]
Looking for feedback on some alternatives:
1. Check that the re-computation error is specifically `descriptor mismatch`; for all other errors actually fail the split.
2. Do something similar with the [user stats computation](https://github.com/cockroachdb/cockroach/blob/2e448b5d40710be64602b0e670b0b264a424914c/pkg/kv/kvserver/replica_command.go#L535) as well, though I don't have specific cases in mind where that would fail.
3. For any re-computation failure, fall back to accurate-stats computation.

**Review by kvoli — COMMENTED** [review]
> 1. Check that the re-computation error is specifically `descriptor mismatch`; for all other errors actually fail the split.

This seems like a nice to have, I'm in favor of including this as part of the change and adding a test which exercises this codepath.

> 2.  Do something similar with the [user stats computation](https://github.com/cockroachdb/cockroach/blob/2e448b5d40710be64602b0e670b0b264a424914c/pkg/kv/kvserver/replica_command.go#L535) as well, though I don't have specific cases in mind where that would fail.

That doesn't seem necessary since we won't run into any error which could be considered benign and later retried.

> 3. For any re-computation failure, fall back to accurate-stats computation.

In cases where the recomputation fails, it seems likely that accurate stats computation would also fail -- only increasing the amount of work to get to a failure. If that is accurate, then this option doesn't seem like a good choice.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121277#-:-Nu4h-mf5DpIxhciWj-7:b-auiht3)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @miraradeva and @nvanbenschoten)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121277#-Nu4gEDd98Qjn2RsGEub):*
nit: benign

**Comment by miraradeva** [comment]
Thanks for the feedback! I did option 1.

**Review by kvoli — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121277#-:-NuU2JBA2-xp03E5bGQi:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @miraradeva and @nvanbenschoten)

___
*[`pkg/kv/kvserver/batcheval/cmd_recompute_stats.go` line 64 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/121277#-NuU1wJ66Z_aKZ_7Gzv1:-NuU1wJ66Z_aKZ_7Gzv2:b-lwsmor) ([raw file](https://github.com/cockroachdb/cockroach/blob/a05c7fa02d67f814f080451f166f01c7b7d1c6bc/pkg/kv/kvserver/batcheval/cmd_recompute_stats.go#L64)):*
> ```Go
> }
> 
> var RecomputeStatsMismatchError = errors.New("descriptor mismatch; range likely merged")
> ```

nit: comment the exported err var.

**Comment by miraradeva** [comment]
bors r=kvoli

**Pull request merged**
