### PR TITLE
sql: add precision and duration field support for INTERVAL type

### LINKED ISSUE #32564: sql: support optional INTERVAL precision
**Is your feature request related to a problem? Please describe.**

`CREATE TABLE t(x INTERVAL(6))` should work

See: https://www.postgresql.org/docs/11/static/datatype-datetime.html#DATATYPE-TIMEZONES

> time, timestamp, and interval accept an optional precision value p which specifies the number of fractional digits retained in the seconds field. By default, there is no explicit bound on precision. The allowed range of p is from 0 to 6.

**Describe the solution you'd like**

MVP: An optional precision of 6 should be recognized and ignored

Optionally: support for other precisions than 6, for example 9 as is currently done in CockroachDB.

**Workaround**

If the desired precision is 9, then the precision can be omitted altogether to obtain equivalent behavior.

### PR DESCRIPTION
**Pull request by otan**
Resolves #32564.

This PR adds support for precision for intervals, e.g. INTERVAL(5) and
SECOND(5). It further adds support of storing the duration field types
(e.g. SECOND, MINUTE, HOUR, DAY TO HOUR, etc.) into the database.

This mainly involves a change to the `type` package, adding a nilable
`IntervalFieldDuration` to the `type` proto to support the duration
field types. Precision-based support is an extension of the previous
precision support done for the time classes. These are backwards
compatible with pre 20.1 versions of the data type.

Changes to sql package are mostly addition of parsing and eval support
for these new types.

Tried copying postgres tests for interval logictests, but found some
bugs that already existed before this branch, and requires this branch
in order to fix them. These have been annotated in the tests.

Release note (sql change): We previously did not support interval types
with precision (e.g. INTERVAL(5), INTERVAL SECOND(5)), nor did we
support storing intervals with duration fields (e.g. INTERVAL x TO y).
This PR adds support for these features.

### CODE REVIEW

**Review by solongordon — APPROVED** [review]
:lgtm: I won't claim to have read every line, but I looked it over and messed around with it a bit, and everything looked good. Thanks for this work!

> Reviewed 2 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43130#-:-LwKZXWMAF5RZc8T0RkI:b-9x4i2n)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @solongordon)

**Comment by otan** [comment]
bors r=solongordon

thanks for reviewing :)

**Comment by otan** [comment]
bors r=solongordon

rebasing turned up some fun errors

**Comment by otan** [comment]
bors r=solongordon

**Pull request merged**
