### PR TITLE
wip: use one request to fetch databases tables data

### LINKED ISSUE #22941: ui: databases page makes too many requests to fetch data
The databases page makes a ton of requests for fine-grained data: one to get a list of all the databases, _one per database_, then **two per table**, all of them spammed out at once on page load.  This isn't really getting a lot of data, and we always want to load all of it.  The overhead of individual requests is pretty significant in this case.

We should introduce an endpoint that just returns the info for all databases and their tables in one shot.

Jira issue: CRDB-5833

### PR DESCRIPTION
**Pull request by celiala**
The databases page currently makes a ton of requests to render the tables
view: one to get a list of all the databases, one per database, then two per
table.

This PR will eventually create a new endpoint to make a single request to
return all of this data.

Pushing up work-so-far to get early feedback on new `DatabaseTableStats`
protobuf objects/interface.

Still todo [to call this complete]:
 - hook into frontend
 - wire up real data from the backend
 - test on large datasets, e.g. is rendering too slow if many databases/tables? if so, maybe make two calls: one to get databases list (can use existing endpoint), then wait on this new endpoint to fill in table details (can still use this endpoint).

Fixes #22941

Release note (admin ui change): Databases page now makes single request to
fetch data for tables view. Was previously making several requests and
fetching some data that wasn't being rendered.

### CODE REVIEW

**Comment by celiala** [comment]
Hi @couchand @vilterp - looking to get early feedback on new DatabaseTableStats
protobuf objects/interface. (e.g. still need to hook into frontend, and wire up real data from the backend). Thanks!

**Comment by vilterp** [comment]
Your proto changes look reasonable. The most important thing now is to understand whether performance of this on large clusters is a problem, so I'd say move forward with this protos and get a quick and dirty implementation we can test on a large cluster with `roachprod` and `roachtest`.

**Comment by celiala** [comment]
Great, I'll move forward with this and get a working implementation to test how this performs for large clusters. Thanks!

**Comment by jordanlewis** [comment]
@dhartunian is this related to what we were talking about at the meeting today, with regards to having to fetch so much data from the UI?

**Comment by dhartunian** [comment]
@jordanlewis yes this is what I was talking about. I glanced at this earlier in the year and found that the implementation was not "easy" :)

**Comment by jordanlewis** [comment]
Yeah, I think you're right. I apologize for dismissing your concern on the call!

I wish we could have the frontend communicate with the backend via SQL commands. I feel that that could be a more flexible approach. But I'm sure there's problems with that, and maybe security issues. Do you have thoughts?

**Comment by dhartunian** [comment]
There does seem to be demand for being able to access Admin UI data via SQL so it seems reasonable to explore!

I can't believe I'm saying this but I wonder if GraphQL is a reasonable solution here...

Is the info I'm looking for currently available via SQL? Would I write a query that asks for the tables in a db and then do a `GROUP BY`...`SUM` etc.?

**Comment by jordanlewis** [comment]
It looks like we want range count and approximate size per table per database, right? As well as columns and index count. I investigated this and came up with this query:

```
SELECT
	tables.database_name,
	table_name,
	sum(range_size) AS approx_table_size,
	count(DISTINCT ti.index_id) AS index_count,
	count(DISTINCT column_id) AS column_count
FROM
	crdb_internal.ranges
	JOIN crdb_internal.tables ON
			ranges.table_name = tables.name
	JOIN crdb_internal.table_indexes AS ti ON
			ti.descriptor_id = tables.table_id
	JOIN crdb_internal.table_columns AS tc ON
			tc.descriptor_id = ti.descriptor_id
GROUP BY
	tables.database_name, table_name;
```

Here's an example on movr:

```
root@127.0.0.1:49670/movr> select tables.database_name, table_name, sum(range_size) approx_table_size, count(distinct ti.index_id) index_count, count(distinct column_id) column_count from crdb_internal.ranges join crdb_internal.tables on ranges.table_name=tables.name join crdb_internal.table_indexes ti on ti.descriptor_id=tables.table_id join crdb_internal.table_columns tc on tc.descriptor_id=ti.descriptor_id group by tables.database_name, table_name;
  database_name |         table_name         | approx_table_size | index_count | column_count
----------------+----------------------------+-------------------+-------------+---------------
  movr          | vehicle_location_histories |            434590 |           1 |            5
  movr          | promo_codes                |           1164865 |           1 |            5
  movr          | user_promo_codes           |                 0 |           1 |            5
  movr          | users                      |             27805 |           1 |            5
  movr          | vehicles                   |             57152 |           2 |            8
  movr          | rides                      |           5276610 |           3 |           10
(6 rows)
```

**Comment by celiala** [comment]
Closing (no intention to continue working on this)

**Pull request closed without merging**
