### PR TITLE
tracing,testutils: detect span leaks

### PR DESCRIPTION
**Pull request by irfansharif**
With always-on tracing, we're maintaining in-memory registry of active
spans (#58490). Spans are added and removed from this registry when
they're Start()-ed and Finish()-ed. Spans that not explicitly finished
(typically using `defer sp.Finish()`) are now a resource-leak, as they
take up room in the registry. We'll want to find instances of this leak
as soon as they crop up.

To that end we add a check in our TestCluster.Stop codepaths that
asserts against the registry being empty. This should give us wide
coverage given it's usage throughout. We expect this change to capture
the cases described in #58721.

---

This check is currently failing, given we're actually leaking spans in
`txnState.resetForNewSQLTxn`. Fixing that doesn't look simple, it ties
into questions around draining SQL and rolling back open txns.

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58902)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif and @knz)

___
*[pkg/sql/txn_state.go, line 161 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58902#-MQvcdh0EYKBN70qX6Dl:-MQvcdh138_bX1jK4bE8:bbqjwh8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c59889139cf638c15988cf45d65d21613e5cfc08/pkg/sql/txn_state.go#L161)):*
> ```Go
> 	//
> 	// XXX: We'll need do address the above with always-on tracing; we're
> 	// leaking spans.
> ```

One thing we could do is finish all the spans registered with the tracer on server shutdown. But... that's exactly destroying any way to check that we're not leaking them.

@asubiotto can you chime in here and suggest/make a change? We need reliable semantics about span finishing in all places, or the registry for long-running operations won't be very useful. My naive assumption is that a txnState only exists in the context of a conn executor, so if that had a close method that is called reliably (which should be possible) that would take care of the issue.

@irfansharif to get this PR merged, you could introduce a (temporary) `tracing.WithBypassRegistry()` option to `StartSpan{,Ctx}` that would simply avoid putting the `Span` in the registry, and use it here. Then we can file an issue against SQL and move on.

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58902)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif and @knz)

___
*[pkg/sql/txn_state.go, line 161 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/58902#-MQvcdh0EYKBN70qX6Dl:-MQvkPy5-WvIyS8QVAOS:b-1ih7rq) ([raw file](https://github.com/cockroachdb/cockroach/blob/c59889139cf638c15988cf45d65d21613e5cfc08/pkg/sql/txn_state.go#L161)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

One thing we could do is finish all the spans registered with the tracer on server shutdown. But... that's exactly destroying any way to check that we're not leaking them.

@asubiotto can you chime in here and suggest/make a change? We need reliable semantics about span finishing in all places, or the registry for long-running operations won't be very useful. My naive assumption is that a txnState only exists in the context of a conn executor, so if that had a close method that is called reliably (which should be possible) that would take care of the issue.

@irfansharif to get this PR merged, you could introduce a (temporary) `tracing.WithBypassRegistry()` option to `StartSpan{,Ctx}` that would simply avoid putting the `Span` in the registry, and use it here. Then we can file an issue against SQL and move on.
</blockquote></details>

I agree with adding a temporary way to bypass adding spans to the registry (maybe with a more explicit you-shouldn't-do-this indicator in the name) to get this PR merged.

With respect to the specific problem of leaking spans on server shutdown I'm assuming this is specifically about txns that don't respond to a cancellation request, otherwise I would expect `finishSQLTxn` to be called. If not, we'd probably need to do something in the `connExecutor`'s close method, although I'm not sure it gets called in these cases. It's been a while since I took a look at the code, but I think the best thing is to add this bypass and create an issue with a reproduction so that we can tackle it on the SQL exec team.

**Comment by irfansharif** [comment]
I'll wait for the discussion on #58897 before landing this. I added the `tracing.WithBypassRegistry()` option, so should be ready to go.

**Comment by irfansharif** [comment]
Given how difficult CI has been recently, I'm just going to pile on and optimistically bors it. The second commit is from #58897. So either that fails and this goes through, or vice versa, or the commits get de-duped away.

bors r+

**Pull request merged**
