### PR TITLE
sql: support OUT / INOUT parameters in UDFs

### PR DESCRIPTION
**Pull request by yuzefovich**
See individual commits for details.

Addresses: #100405.
Epic: CRDB-30611

Release note (sql change): OUT and INOUT parameter classes are now supported in User-Defined Functions.

### CODE REVIEW

**Comment by yuzefovich** [comment]
This is RFAL. I tried to document all interesting behaviors that Rachael and I found (both in the commit messages and in the logic tests) - if you know of some other quirks, I'm all ears 😃

**Review by mgartner — APPROVED** [review]
:lgtm: Very nice and thorough! 

> Reviewed 7 of 7 files at r1, 12 of 12 files at r2, 6 of 6 files at r3, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118610#-:-NqTxi354xwFq99WhEaA:b-9qlt3m)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @yuzefovich)

___
*[`pkg/sql/opt/testutils/testcat/function.go` line 87 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/118610#-NqTxQzpCuA8JGq_gb2f:-NqTxQzpCuA8JGq_gb2g:byxwvq8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7cb0b8f34a62469dca54bad566e6a566326f696/pkg/sql/opt/testutils/testcat/function.go#L87)):*
> ```Go
> 	paramTypes := make(tree.ParamTypes, len(c.Params))
> 	var outParamTypes []*types.T
> 	var firstOutParamName string
> ```

nit: Do you want to add an optbuilder test so that the changes here are used?
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go` line 389 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/118610#-NqTriV6Dh2mvP_OnLVR:-NqTriV6Dh2mvP_OnLVS:bwvph0g) ([raw file](https://github.com/cockroachdb/cockroach/blob/579d4188adb7048889094512263d5bd075af7d20/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go#L389)):*
> ```Go
> 	ResolveIndex(relationID catid.DescID, indexName tree.Name, p ResolveParams) ElementResultSet
> 
> 	// ResolveRoutine retrieves a user defined function and returns its elements.
> ```

nit: Should "user defined function" also be changed? Or is this only used for UDFs and not for resolving SPs?
___
*[`pkg/sql/logictest/testdata/logic_test/udf_params` line 218 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/118610#-NqTwoJp3e8eQE-s3zSu:-NqTwoJp3e8eQE-s3zSv:bjohvh6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7cb0b8f34a62469dca54bad566e6a566326f696/pkg/sql/logictest/testdata/logic_test/udf_params#L218)):*
> ```
> 
> statement ok
> CREATE FUNCTION f_inout_int(INOUT param INT) RETURNS INT AS $$ SELECT 1; $$ LANGUAGE SQL;
> ```

nit: Might be a little more interesting to have `param` used in the UDF body.

**Review by DrewKimball — APPROVED** [review]
:lgtm: Nice work!

> Reviewed 7 of 7 files at r1, 12 of 12 files at r2, 6 of 6 files at r3, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118610#-:-Nq_1-yQE_0-VcRnEJkv:bcmw7ss)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`pkg/sql/sem/tree/create_routine.go` line 399 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/118610#-NqGZMTr2GxsG-wluYao:-NqGZMTr2GxsG-wluYap:b-suq2o0) ([raw file](https://github.com/cockroachdb/cockroach/blob/579d4188adb7048889094512263d5bd075af7d20/pkg/sql/sem/tree/create_routine.go#L399)):*
> ```Go
> )
> 
> func IsInParamClass(class RoutineParamClass) bool {
> ```

[nit] This function (and below) could use comments, in particular to mention that it returns true for both IN and INOUT parameters.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_params` line 548 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/118610#-Nq_0Jcv4xYggvrAwHyT:-Nq_0Jcv4xYggvrAwHyU:b-a2urzx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7cb0b8f34a62469dca54bad566e6a566326f696/pkg/sql/logictest/testdata/logic_test/udf_params#L548)):*
> ```
> # But then the IN parameter name cannot be changed anymore.
> statement error cannot change name of input parameter "in_param"
> CREATE OR REPLACE FUNCTION f_default_names(OUT INT, OUT param2 INT, IN in_param_new INT, OUT INT) RETURNS RECORD AS $$ SELECT (1, 2, 3); $$ LANGUAGE SQL;
> ```

Could we have a test like this?
```
CREATE TYPE typ AS (a INT, b INT);
CREATE FUNCTION f() RETURNS typ LANGUAGE SQL AS $$ SELECT 1 AS x, 2 AS y; $$;
SELECT * FROM f();
```
I suspect there may be some problems with the use of `types.IsRecordType()` returning true for UDTs.

**Review by yuzefovich — COMMENTED** [review]
Thanks for the reviews!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118610#-:-Nq_BsBd2Sl4ElTH5z_T:b-hlc8bm)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/opt/testutils/testcat/function.go` line 87 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/118610#-NqTxQzpCuA8JGq_gb2f:-Nq_7Dvj3vvlsO-LRvC5:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7cb0b8f34a62469dca54bad566e6a566326f696/pkg/sql/opt/testutils/testcat/function.go#L87)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: Do you want to add an optbuilder test so that the changes here are used?
</blockquote></details>

Good point, done.
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_function.go` line 74 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/118610#-Nq_BuK-2mALs1NQaI_y:-Nq_BuK-2mALs1NQaI_z:bmcnbbf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a07ac0500b9a0defe0c6978cd2ce4e8db010e11/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_function.go#L74)):*
> ```Go
> 			// If the function returns a RECORD type, then we need to check
> 			// whether its OUT parameters specify labels for the return type.
> 			// TODO(yuzefovich): why do we need to do this? Why doing this in
> ```

Does someone know the answer to this question? To me it seemed that the new schema changer reparsed the whole function - is that true?
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go` line 389 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/118610#-NqTriV6Dh2mvP_OnLVR:-Nq_2F6z18YjTsXOxou5:b-7e3ba7) ([raw file](https://github.com/cockroachdb/cockroach/blob/579d4188adb7048889094512263d5bd075af7d20/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go#L389)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: Should "user defined function" also be changed? Or is this only used for UDFs and not for resolving SPs?
</blockquote></details>

I think it's for both, done.
___
*[`pkg/sql/sem/tree/create_routine.go` line 399 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/118610#-NqGZMTr2GxsG-wluYao:-Nq_2YHB8McM89JP59UJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/579d4188adb7048889094512263d5bd075af7d20/pkg/sql/sem/tree/create_routine.go#L399)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] This function (and below) could use comments, in particular to mention that it returns true for both IN and INOUT parameters.
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_params` line 218 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/118610#-NqTwoJp3e8eQE-s3zSu:-Nq_5pYU997qfd1ZnBbs:b-un23wb) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7cb0b8f34a62469dca54bad566e6a566326f696/pkg/sql/logictest/testdata/logic_test/udf_params#L218)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: Might be a little more interesting to have `param` used in the UDF body.
</blockquote></details>

Good point, done. This actually exposed an issue that I left a few TODOs for.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_params` line 548 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/118610#-Nq_0Jcv4xYggvrAwHyT:-Nq_BU2j1ZgGbGucdW3c:bjtyt6e) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7cb0b8f34a62469dca54bad566e6a566326f696/pkg/sql/logictest/testdata/logic_test/udf_params#L548)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Could we have a test like this?
```
CREATE TYPE typ AS (a INT, b INT);
CREATE FUNCTION f() RETURNS typ LANGUAGE SQL AS $$ SELECT 1 AS x, 2 AS y; $$;
SELECT * FROM f();
```
I suspect there may be some problems with the use of `types.IsRecordType()` returning true for UDTs.
</blockquote></details>

Thanks, added a test - looks like everything works as expected.

**Review by DrewKimball — COMMENTED** [review]
> Reviewed 3 of 19 files at r5, 1 of 10 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118610)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @yuzefovich)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_function.go` line 74 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/118610#-Nq_BuK-2mALs1NQaI_y:-Nq_KB88CFJYMkUypLJu:b-8e2env) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a07ac0500b9a0defe0c6978cd2ce4e8db010e11/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_function.go#L74)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Does someone know the answer to this question? To me it seemed that the new schema changer reparsed the whole function - is that true?
</blockquote></details>

Yeah, the statement gets formatted and re-parsed. See here:
https://github.com/cockroachdb/cockroach/blob/ab9cc950f809cd93b1e078212aad754df9563e0f/pkg/sql/schemachanger/scbuild/build.go#L77
and here:
https://github.com/cockroachdb/cockroach/blob/ab9cc950f809cd93b1e078212aad754df9563e0f/pkg/sql/schemachanger/scbuild/ast_annotator.go#L30-L34

So, the AST no longer reflects any changes that were made in the optbuilder at this point.

**Review by yuzefovich — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118610#-:-Nq_VkLx5rh-SQsjKJ8j:b-ydi9ay)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_function.go` line 74 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/118610#-Nq_BuK-2mALs1NQaI_y:-Nq_VhZe5y64fwlSsiEL:b8mp2yb) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a07ac0500b9a0defe0c6978cd2ce4e8db010e11/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_function.go#L74)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Yeah, the statement gets formatted and re-parsed. See here:
https://github.com/cockroachdb/cockroach/blob/ab9cc950f809cd93b1e078212aad754df9563e0f/pkg/sql/schemachanger/scbuild/build.go#L77
and here:
https://github.com/cockroachdb/cockroach/blob/ab9cc950f809cd93b1e078212aad754df9563e0f/pkg/sql/schemachanger/scbuild/ast_annotator.go#L30-L34

So, the AST no longer reflects any changes that were made in the optbuilder at this point.
</blockquote></details>

Ack, thanks for the pointers.

**Pull request merged**
