### PR TITLE
go.mod: bump github.com/aws/aws-sdk-go to v1.38.69

### PR DESCRIPTION
**Pull request by adityamaru**
Release notes: https://github.com/aws/aws-sdk-go/releases

Release note: None

### CODE REVIEW

**Comment by adityamaru** [comment]
Going to look into all the CI failures so you can hold off on this review!

**Comment by adityamaru** [comment]
Should be RFAL, fixed the vendor badness.

**Review by pbardea — APPROVED** [review]

**Review by pbardea — APPROVED** [review]

**Comment by adityamaru** [comment]
TFTR!

bors r=pbardea

**Pull request merged**
