### PR TITLE
server, ui: login: template logged in user into index.html

### LINKED ISSUE #25171: ui: login: remember that user has a session
If a user has logged in and opens another page, they should not be prompted to enter their username and password again; the page should somehow remember that they have a session.

Do this either by:
- Storing it browser-side in `localStorage`
- Templating `index.html` server-side with a variable such as `window.loggedInUser = 'vilterp'`.

### PR DESCRIPTION
**Pull request by vilterp**
...instead of serving a static index.html generated at build time via a webpack plugin. This allows the UI to decide whether it needs to show a login UI (and show the logged in username if there is one) without making an additional request to the backend.

Fixes #25171 

TODO:
- [x] make sure this doesn't break `make buildshort`
- [x] favicon not showing up
- tests
    - [x] insecure: can get assets, index.html doesn't have user
    - secure
        - [x] logged out: can get assets, index.html doesn't have user
        - [x] logged in: can get assets, index.html has user
- [x] fix race condition where health check endpoint crashes server before it's fully started up

Release note: None

### CODE REVIEW

**Comment by couchand** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/server/authentication.go, line 309 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25195#-LBRTU8L3UKxpDQYHfAe:-LBRTU8L3UKxpDQYHfAf:bcjwdo8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4099f7d37caea552b06cd7cbba10e1ac56cb44c6/pkg/server/authentication.go#L309)):*
> ```Go
> 	inner  http.Handler
> 
> 	rejectIfUnauthenticated bool
> ```

suggest reversing the logic so the zero value is the safe one... `allowAnonymous` maybe?

---

*[pkg/server/authentication.go, line 313 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25195#-LBRTX6y6aOz9_ci85Y2:-LBRTX6y6aOz9_ci85Y3:b-2363dk) ([raw file](https://github.com/cockroachdb/cockroach/blob/4099f7d37caea552b06cd7cbba10e1ac56cb44c6/pkg/server/authentication.go#L313)):*
> ```Go
> 
> func newAuthenticationMux(
> 	s *authenticationServer, inner http.Handler, rejectIfUnauthenticated bool,
> ```

suggest exposing two different constructors rather than passing in the bool

---

*[pkg/server/authentication.go, line 327 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25195#-LBRV4pq3bDc1v1BjcEc:-LBRV4pq3bDc1v1BjcEd:b9gze8m) ([raw file](https://github.com/cockroachdb/cockroach/blob/4099f7d37caea552b06cd7cbba10e1ac56cb44c6/pkg/server/authentication.go#L327)):*
> ```Go
> 	username, httpCode, err := am.getSession(w, req)
> 	if am.rejectIfUnauthenticated && err != nil {
> 		http.Error(w, err.Error(), httpCode)
> ```

i think i made this comment on the original pr... i don't think we should be returning the error.  we should log it, but the actor attempting to log in shouldn't be able to see details beyond the status code.

---

*[pkg/server/authentication.go, line 332 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25195#-LBRYWK3AfBQXCkmN0_f:-LBRYWK3AfBQXCkmN0_g:b-k2jzm1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4099f7d37caea552b06cd7cbba10e1ac56cb44c6/pkg/server/authentication.go#L332)):*
> ```Go
> 
> 	newCtx := context.WithValue(req.Context(), loggedInUserKey{}, username)
> 	newReq := req.WithContext(newCtx)
> ```

probably worth updating tests to reflect this

---

*[pkg/server/server.go, line 1450 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25195#-LBRYrxNAZGDdP_ernA8:-LBRYrxNAZGDdP_ernA9:bu5ou3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/4099f7d37caea552b06cd7cbba10e1ac56cb44c6/pkg/server/server.go#L1450)):*
> ```Go
> 	log.Event(ctx, "added http endpoints")
> 
> 	// Also throw the landing page in there. It won't work well, but it's better than a 404.
> ```

are you sure you want to move this all the way down here?  if so, the comment isn't really relevant anymore...

---

*[pkg/server/server.go, line 1459 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25195#-LBRXiU7CPwz_HjzCaLx:-LBRXiU7CPwz_HjzCaLy:bbhcw16) ([raw file](https://github.com/cockroachdb/cockroach/blob/4099f7d37caea552b06cd7cbba10e1ac56cb44c6/pkg/server/server.go#L1459)):*
> ```Go
> 	})
> 
> 	assetsHandler := func(writer http.ResponseWriter, request *http.Request) {
> ```

suggest moving this to a new file and adding tests for the various cases.

---

*[pkg/server/server.go, line 1478 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25195#-LBRZf7k70r-tOe7R9vK:-LBRZf7k70r-tOe7R9vL:b-6i8t9g) ([raw file](https://github.com/cockroachdb/cockroach/blob/4099f7d37caea552b06cd7cbba10e1ac56cb44c6/pkg/server/server.go#L1478)):*
> ```Go
> 			wrappedErr := errors.Wrap(err, "templating index.html")
> 			log.Error(ctx, wrappedErr)
> 			writer.WriteHeader(500)
> ```

`http.Error`?

---

*[pkg/ui/ui.go, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25195#-LBRaKViCO3ssK6xBK2-:-LBRaKViCO3ssK6xBK20:b-l83vp8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4099f7d37caea552b06cd7cbba10e1ac56cb44c6/pkg/ui/ui.go#L101)):*
> ```Go
> 		</script>
> 
> 		<script src="protos.dll.js" type="text/javascript"></script>
> ```

if we can get these to be build-time rather than code-time, that would be ideal, but if that's too complicated hard-coding isn't that bad.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25195)*

**Comment by mrtracy** [comment]
It's my opinion that, rather than having index.html be generated with "loggedInUser" set, we should have the authenticationMux set a second, non-httponly cookie on the outgoing response which contains the logged in user name. I think that the index.html generation here is a bit heavy-handed for this particular enhancement.

---

Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/server/authentication.go, line 313 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25195#-LBRTX6y6aOz9_ci85Y2:-LBRdfYd3UVNxJqw4_Ya:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/4099f7d37caea552b06cd7cbba10e1ac56cb44c6/pkg/server/authentication.go#L313)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

suggest exposing two different constructors rather than passing in the bool
</blockquote></details>

+1

---

*[pkg/server/authentication.go, line 327 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25195#-LBRV4pq3bDc1v1BjcEc:-LBRdhmu0DWgyTb439Du:b-489le3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4099f7d37caea552b06cd7cbba10e1ac56cb44c6/pkg/server/authentication.go#L327)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

i think i made this comment on the original pr... i don't think we should be returning the error.  we should log it, but the actor attempting to log in shouldn't be able to see details beyond the status code.
</blockquote></details>

Agreed, this could unintentionally leak details to an unauthenticated client.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25195#-:-LBRdvNAA5eZDGP4z5gw:bpsg9r8)*

**Comment by couchand** [comment]
>  set a second, non-httponly cookie on the outgoing response ... the index.html generation here is a bit heavy-handed for this particular enhancement

a reasonable perspective, however, this also seems like a good strategy for addressing #19024

**Comment by vilterp** [comment]
Update: after some debugging with Andrei, looks like the crash should be fixed by #24945. The problem was that in `server.Start` the healthcheck endpoint is exposed before the SQL executor is initialized. This was never a problem until authorization was turned on (with the env var), which causes it to run SQL to check the session. Once we exempt it from auth, it won't run SQL, as before.

**Comment by couchand** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/server/authentication.go, line 313 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25195#-LBRTX6y6aOz9_ci85Y2:-LC_TR-X401iAjoySD0s:b-qj3eu5) ([raw file](https://github.com/cockroachdb/cockroach/blob/4099f7d37caea552b06cd7cbba10e1ac56cb44c6/pkg/server/authentication.go#L313)):*
<details><summary><i>Previously, vilterp (Pete Vilter) wrote…</i></summary><blockquote>

Done, although the names are clunky. Lmk if you have better ideas.
</blockquote></details>

I just removed "DisallowAnonymous" since that's considered the default.

---

*[pkg/server/authentication.go, line 327 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25195#-LBRV4pq3bDc1v1BjcEc:-LC_TaOP8TbIizC3iOZ9:b-vdbqo9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4099f7d37caea552b06cd7cbba10e1ac56cb44c6/pkg/server/authentication.go#L327)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

Agreed, this could unintentionally leak details to an unauthenticated client.
</blockquote></details>

Updated to log the real error and then respond with a generic error.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25195)*

**Comment by couchand** [comment]
@mrtracy would you please take one more look at this when you get a chance?

**Comment by mrtracy** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/server/authentication.go, line 327 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25195#-LBRV4pq3bDc1v1BjcEc:-LC_nrrUDizsM4r_2SJ_:b-6rm5kr) ([raw file](https://github.com/cockroachdb/cockroach/blob/4099f7d37caea552b06cd7cbba10e1ac56cb44c6/pkg/server/authentication.go#L327)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

Updated to log the real error and then respond with a generic error.
</blockquote></details>

Isn't this going to log "Web Session Error" when you load up index.html the first time, without yet having logged in?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25195)*

**Comment by mrtracy** [comment]
Had a comment on the log message for unauthenticated requests, otherwise this is :lgtm:

---

Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25195#-:-LC_qr-N6mnXG1oXVDoi:b415j3k)*

**Comment by couchand** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/server/authentication.go, line 327 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25195#-LBRV4pq3bDc1v1BjcEc:-LC_tWBQ73NT4HyHMPYh:b-kyo06x) ([raw file](https://github.com/cockroachdb/cockroach/blob/4099f7d37caea552b06cd7cbba10e1ac56cb44c6/pkg/server/authentication.go#L327)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

Isn't this going to log "Web Session Error" when you load up index.html the first time, without yet having logged in?
</blockquote></details>

Indeed.  I think we still want to log if it hits any but the first conditional in `getSession`, or maybe this should just be moved into the `if !am.allowAnonymous` block?

Actually, I think `getSession` should just take into account `am.allowAnonymous`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25195)*

**Comment by couchand** [comment]
Reviewed 4 of 8 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/server/authentication.go, line 327 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25195#-LBRV4pq3bDc1v1BjcEc:-LCe0rngA-W9L20oFX-S:b-cqotzd) ([raw file](https://github.com/cockroachdb/cockroach/blob/4099f7d37caea552b06cd7cbba10e1ac56cb44c6/pkg/server/authentication.go#L327)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

Indeed.  I think we still want to log if it hits any but the first conditional in `getSession`, or maybe this should just be moved into the `if !am.allowAnonymous` block?

Actually, I think `getSession` should just take into account `am.allowAnonymous`.
</blockquote></details>

Nevermind on that last point, it's too much work for too little benefit.  I just pushed it inside the `if !am.allowAnonymous` block.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25195)*

**Pull request merged**
