### PR TITLE
opt: proper handling of IndexedVars in the exec builder

### PR DESCRIPTION
**Pull request by RaduBerinde**
`IndexedVar`s are relative to a specific execution node; we need to
allow arbitrary mappings of `ColumnIndex`es to `IndexedVar`s when
building scalars. This change adds a scalar build context containing
the indexed var helper and a column map.

We are able to get away with not having an indexed var container by
using `IndexedVarWithType`.

Release note: None

### CODE REVIEW

**Comment by andy-kimball** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22458#-:-L4kmuCg9a3cSS2KyOnO:bnfp4nl)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22458#-:-L4krlJnCnnVMvlj3g6T:bnfp4nl)*

**Comment by RaduBerinde** [comment]
I added a commit to quiet down a linter check and did a bit of minor cleanup in `Metadata`.

**Comment by rytaft** [comment]
The new changes look good

---

Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22458#-:-L4lOB3ku7rkEIEH0gyz:bjndekt)*

**Pull request merged**
