### PR TITLE
*: remove more author tags

### PR DESCRIPTION
**Pull request by tamird**

### CODE REVIEW

**Comment by tschottdorf** [comment]
Haven't checked the diff, but LGTM assuming no changes other than removed tags. Think you can update the lint?

**Comment by tschottdorf** [comment]
Haven't checked the diff, but LGTM assuming no changes other than removed tags. Think you can update the lint?

**Comment by tschottdorf** [comment]
Sorry, saw that you already did :)

**Comment by tamird** [comment]
Minor change to IR stringing code which was producing trailing whitespace. Will merge on green.

**Review by benesch — APPROVED** [review]
Nice!

**Pull request merged**
