### PR TITLE
opt: improve partial index implication with virtual columns

### LINKED ISSUE #122352: sql/opt: prove partial index implication with in-exact atoms containing virtual computed columns
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

```
--! The following works as expected
CREATE TABLE test_index_stored (
    a int primary key,
    b jsonb
);

ALTER TABLE test_index_stored ADD COLUMN c STRING AS (b->>'c') STORED;
ALTER TABLE test_index_stored ADD COLUMN d STRING AS (b->>'d') STORED;
ALTER TABLE test_index_stored ADD COLUMN e INT AS ((b->>'e')::INT) STORED;
CREATE INDEX ON test_index_stored(c, e) WHERE c IS NOT NULL AND e IS NOT NULL;

INSERT INTO test_index_stored VALUES (1, '{"c": "foo", "d": "bar", "e": 5}');

SELECT c, e FROM test_index_stored@test_index_stored_c_e_idx WHERE c = 'foo' AND e > 4;  --! works

```
```
--! The following fails:
CREATE TABLE test_index_virtual (
    a int primary key,
    b jsonb
);

ALTER TABLE test_index_virtual ADD COLUMN c STRING AS (b->>'c') VIRTUAL;
ALTER TABLE test_index_virtual ADD COLUMN d STRING AS (b->>'d') VIRTUAL;
ALTER TABLE test_index_virtual ADD COLUMN e INT AS ((b->>'e')::INT) VIRTUAL;
CREATE INDEX ON test_index_virtual(c, e) WHERE c IS NOT NULL AND e IS NOT NULL;

INSERT INTO test_index_virtual VALUES (1, '{"c": "foo", "d": "bar", "e": 5}');

SELECT c, e FROM test_index_virtual@test_index_virtual_c_e_idx WHERE c = 'foo' AND e > 4; --! fails
SELECT c, e FROM test_index_virtual@test_index_virtual_c_e_idx WHERE c is not null and e is not null; --! works
SELECT c, e FROM test_index_virtual@test_index_virtual_c_e_idx WHERE c is not null and e is not null and c = 'foo' and e > 4; --! fails
```

Spent quite some time investigating the problem, even tried to force the index scan.  The exception was thrown here: https://github.com/cockroachdb/cockroach/blob/67547d7724f8a52646e2e8ecb3ca48b923957d90/pkg/sql/opt/exec/execbuilder/relational.go#L598, when the index that is actually needed mismatches the index in the flag. 

Changed the code to force the scan the flags.index, the query worked, but empty result was returned, likely due to predicate matching.
It seemed to me that the predict added here can be further pruned: https://github.com/cockroachdb/cockroach/blob/67547d7724f8a52646e2e8ecb3ca48b923957d90/pkg/sql/opt/optbuilder/select.go#L643
and it might also have something to do with virtual columns, because they are always applied a projection

**Expected behavior**
The query should not fail.

**Environment:**
 - CockroachDB version 24.1 alpha, also have tested on 23.1.17 and 23.2.3
 - Server OS: [e.g. Linux/Distrib]
 - Client app [e.g. `cockroach sql`]

Jira issue: CRDB-37825

### PR DESCRIPTION
**Pull request by mgartner**
#### opt: add Implicator benchmarks with virtual columns

Release note: None

#### opt: improve partial index implication with virtual columns

The partial index implicator is now aware of computed columns and their
expressions. This allows implication to be proven in more cases. For
example, consider the table and query:

    CREATE TABLE (
      j JSONB,
      i INT AS ((j->>'x')::INT) VIRTUAL,
      INDEX (i) WHERE i IS NOT NULL
    );

    SELECT * FROM t WHERE i = 10;

Prior to this commit, the optimizer would not plan a constrained scan
over the partial index because the implicator could not prove that the
query filters, pushed into the projection as `(j->>'x')::INT = 10`,
imply the partial index predicate, built as
`(j->>'x')::INT IS NOT NULL`. To prove implication cases like this where
the expressions are not exact matches, the implicator must build
constraints to check if the predicate contains the filter. Constraints
cannot be built from these expressions, so verifying containment was
impossible.

Now that the implicator is aware of computed columns and their
expressions, it converts the filter and predicate into expressions
referencing virtual computed columns: `i = 10` and `i IS NOT NULL`.
Constraints can be built from expressions in this forms, containment can
be checked, and implication can be proven.

Fixes #122352

Release note (sql change): The optimizer can now plan constrained scans
over partial indexes in more cases, particularly on partial indexes with
predicates referencing virtual computed columns.

#### opt: add session setting for virtual computed column implication

The `optimizer_prove_implication_with_virtual_computed_columns` has been
added which, when enabled, indicates that virtual computed columns
should be considered during partial index implication to try to prove
that a filter implies a predicate.

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
Benchmarks:

```
name                                                old time/op    new time/op    delta
Implicator/single-exact-match-10                      51.4ns ±11%    50.1ns ± 4%       ~     (p=0.421 n=5+5)
Implicator/single-inexact-match-10                     223ns ± 5%     221ns ± 0%       ~     (p=0.730 n=5+4)
Implicator/range-inexact-match-10                      517ns ± 1%     533ns ± 7%     +2.99%  (p=0.032 n=5+5)
Implicator/two-var-comparison-10                       155ns ± 1%     159ns ± 0%     +2.79%  (p=0.008 n=5+5)
Implicator/single-exact-match-extra-filters-10         177ns ± 2%     175ns ± 0%     -1.63%  (p=0.008 n=5+5)
Implicator/single-inexact-match-extra-filters-10       386ns ± 8%     383ns ± 0%       ~     (p=0.635 n=5+5)
Implicator/multi-column-and-exact-match-10            53.7ns ± 0%    53.4ns ± 0%     -0.44%  (p=0.008 n=5+5)
Implicator/multi-column-and-inexact-match-10           451ns ± 0%     465ns ± 1%     +3.19%  (p=0.008 n=5+5)
Implicator/multi-column-and-two-var-comparisons-10     301ns ± 1%     327ns ±11%     +8.95%  (p=0.008 n=5+5)
Implicator/multi-column-or-exact-match-10             49.3ns ± 0%    49.4ns ± 0%       ~     (p=0.500 n=5+5)
Implicator/multi-column-or-exact-match-reverse-10      290ns ± 5%     288ns ± 0%       ~     (p=0.690 n=5+5)
Implicator/multi-column-or-inexact-match-10            626ns ± 5%     644ns ± 5%       ~     (p=0.095 n=5+5)
Implicator/in-implies-or-10                            680ns ± 0%     699ns ± 1%     +2.81%  (p=0.016 n=4+5)
Implicator/and-filters-do-not-imply-pred-10           2.29µs ± 1%    2.26µs ± 0%     -1.04%  (p=0.008 n=5+5)
Implicator/or-filters-do-not-imply-pred-10             361ns ± 1%     365ns ± 0%       ~     (p=0.190 n=5+4)
Implicator/single-exact-match-virtual-10              50.0ns ± 2%    49.8ns ± 1%       ~     (p=0.651 n=5+5)
Implicator/single-inexact-match-virtual-10             124ns ± 5%     705ns ± 0%   +467.81%  (p=0.008 n=5+5)
Implicator/single-no-match-virtual-10                  125ns ± 5%     734ns ± 0%   +489.54%  (p=0.008 n=5+5)
Implicator/and-filters-virtual-10                      292ns ± 9%    3251ns ± 0%  +1015.19%  (p=0.016 n=5+4)
Implicator/or-filters-virtual-10                       309ns ± 0%    2108ns ± 0%   +583.30%  (p=0.008 n=5+5)
Implicator/many-columns-exact-match10-10               161ns ± 0%     161ns ± 5%       ~     (p=0.651 n=5+5)
Implicator/many-columns-inexact-match10-10            3.93µs ± 0%    4.29µs ± 0%     +9.23%  (p=0.008 n=5+5)
Implicator/many-columns-exact-match100-10             12.1µs ± 0%    11.9µs ± 0%     -1.26%  (p=0.008 n=5+5)
Implicator/many-columns-inexact-match100-10            259µs ± 0%     272µs ± 0%     +4.93%  (p=0.008 n=5+5)

name                                                old alloc/op   new alloc/op   delta
Implicator/single-exact-match-10                       48.0B ± 0%     48.0B ± 0%       ~     (all equal)
Implicator/single-inexact-match-10                     81.0B ± 0%     81.0B ± 0%       ~     (all equal)
Implicator/range-inexact-match-10                       160B ± 0%      160B ± 0%       ~     (all equal)
Implicator/two-var-comparison-10                       81.0B ± 0%     81.0B ± 0%       ~     (all equal)
Implicator/single-exact-match-extra-filters-10          560B ± 0%      560B ± 0%       ~     (all equal)
Implicator/single-inexact-match-extra-filters-10       81.0B ± 0%     81.0B ± 0%       ~     (all equal)
Implicator/multi-column-and-exact-match-10             48.0B ± 0%     48.0B ± 0%       ~     (all equal)
Implicator/multi-column-and-inexact-match-10           81.0B ± 0%     81.0B ± 0%       ~     (all equal)
Implicator/multi-column-and-two-var-comparisons-10     81.0B ± 0%     81.0B ± 0%       ~     (all equal)
Implicator/multi-column-or-exact-match-10              48.0B ± 0%     48.0B ± 0%       ~     (all equal)
Implicator/multi-column-or-exact-match-reverse-10       120B ± 0%      120B ± 0%       ~     (all equal)
Implicator/multi-column-or-inexact-match-10             181B ± 0%      181B ± 0%       ~     (all equal)
Implicator/in-implies-or-10                             371B ± 0%      371B ± 0%       ~     (all equal)
Implicator/and-filters-do-not-imply-pred-10           2.15kB ± 0%    2.15kB ± 0%       ~     (all equal)
Implicator/or-filters-do-not-imply-pred-10              140B ± 0%      140B ± 0%       ~     (all equal)
Implicator/single-exact-match-virtual-10               48.0B ± 0%     48.0B ± 0%       ~     (all equal)
Implicator/single-inexact-match-virtual-10             81.0B ± 0%    265.0B ± 0%   +227.16%  (p=0.008 n=5+5)
Implicator/single-no-match-virtual-10                  81.0B ± 0%     81.0B ± 0%       ~     (all equal)
Implicator/and-filters-virtual-10                      81.0B ± 0%    722.0B ± 0%   +791.36%  (p=0.008 n=5+5)
Implicator/or-filters-virtual-10                        100B ± 0%      572B ± 0%   +472.00%  (p=0.008 n=5+5)
Implicator/many-columns-exact-match10-10               48.0B ± 0%     48.0B ± 0%       ~     (all equal)
Implicator/many-columns-inexact-match10-10              266B ± 0%      266B ± 0%       ~     (all equal)
Implicator/many-columns-exact-match100-10              48.0B ± 0%     48.0B ± 0%       ~     (all equal)
Implicator/many-columns-inexact-match100-10           2.16kB ± 0%    2.16kB ± 0%       ~     (p=0.897 n=5+5)

name                                                old allocs/op  new allocs/op  delta
Implicator/single-exact-match-10                        2.00 ± 0%      2.00 ± 0%       ~     (all equal)
Implicator/single-inexact-match-10                      2.00 ± 0%      2.00 ± 0%       ~     (all equal)
Implicator/range-inexact-match-10                       2.00 ± 0%      2.00 ± 0%       ~     (all equal)
Implicator/two-var-comparison-10                        2.00 ± 0%      2.00 ± 0%       ~     (all equal)
Implicator/single-exact-match-extra-filters-10          3.00 ± 0%      3.00 ± 0%       ~     (all equal)
Implicator/single-inexact-match-extra-filters-10        2.00 ± 0%      2.00 ± 0%       ~     (all equal)
Implicator/multi-column-and-exact-match-10              2.00 ± 0%      2.00 ± 0%       ~     (all equal)
Implicator/multi-column-and-inexact-match-10            2.00 ± 0%      2.00 ± 0%       ~     (all equal)
Implicator/multi-column-and-two-var-comparisons-10      2.00 ± 0%      2.00 ± 0%       ~     (all equal)
Implicator/multi-column-or-exact-match-10               2.00 ± 0%      2.00 ± 0%       ~     (all equal)
Implicator/multi-column-or-exact-match-reverse-10       2.00 ± 0%      2.00 ± 0%       ~     (all equal)
Implicator/multi-column-or-inexact-match-10             2.00 ± 0%      2.00 ± 0%       ~     (all equal)
Implicator/in-implies-or-10                             4.00 ± 0%      4.00 ± 0%       ~     (all equal)
Implicator/and-filters-do-not-imply-pred-10             14.0 ± 0%      14.0 ± 0%       ~     (all equal)
Implicator/or-filters-do-not-imply-pred-10              2.00 ± 0%      2.00 ± 0%       ~     (all equal)
Implicator/single-exact-match-virtual-10                2.00 ± 0%      2.00 ± 0%       ~     (all equal)
Implicator/single-inexact-match-virtual-10              2.00 ± 0%      6.00 ± 0%   +200.00%  (p=0.008 n=5+5)
Implicator/single-no-match-virtual-10                   2.00 ± 0%      2.00 ± 0%       ~     (all equal)
Implicator/and-filters-virtual-10                       2.00 ± 0%     16.00 ± 0%   +700.00%  (p=0.008 n=5+5)
Implicator/or-filters-virtual-10                        2.00 ± 0%     14.00 ± 0%   +600.00%  (p=0.008 n=5+5)
Implicator/many-columns-exact-match10-10                2.00 ± 0%      2.00 ± 0%       ~     (all equal)
Implicator/many-columns-inexact-match10-10              2.00 ± 0%      2.00 ± 0%       ~     (all equal)
Implicator/many-columns-exact-match100-10               2.00 ± 0%      2.00 ± 0%       ~     (all equal)
Implicator/many-columns-inexact-match100-10             3.00 ± 0%      3.00 ± 0%       ~     (all equal)
```

**Comment by mgartner** [comment]
I don't love that this might slow down implication for tables containing computed columns by 10x:

```
Implicator/and-filters-virtual-10                      292ns ± 9%    3251ns ± 0%  +1015.19%  (p=0.016 n=5+4)
```

It's likely not a major bottleneck of optimization, but I'll think about ways to reduce this overhead.

**Comment by cty123** [comment]
This was what I used to reproduce the issue, as a user, I expect these 2 types of queries to have the exact same effect,

```sql
--! Good
CREATE TABLE test_index_stored (
    a int primary key,
    b jsonb
);

ALTER TABLE test_index_stored ADD COLUMN c STRING AS (b->>'c') STORED;
ALTER TABLE test_index_stored ADD COLUMN d STRING AS (b->>'d') STORED;
ALTER TABLE test_index_stored ADD COLUMN e INT AS ((b->>'e')::INT) STORED;
CREATE INDEX ON test_index_stored(c, e) WHERE c IS NOT NULL AND e IS NOT NULL;

INSERT INTO test_index_stored VALUES (1, '{"c": "foo", "d": "bar", "e": 5}');

SELECT c, e FROM test_index_stored@test_index_stored_c_e_idx WHERE c = 'foo' AND e > 4;  --! works
```

```sql
--! Bad
CREATE TABLE test_index_virtual (
    a int primary key,
    b jsonb
);

ALTER TABLE test_index_virtual ADD COLUMN c STRING AS (b->>'c') VIRTUAL;
ALTER TABLE test_index_virtual ADD COLUMN d STRING AS (b->>'d') VIRTUAL;
ALTER TABLE test_index_virtual ADD COLUMN e INT AS ((b->>'e')::INT) VIRTUAL;
CREATE INDEX ON test_index_virtual(c, e) WHERE c IS NOT NULL AND e IS NOT NULL;

INSERT INTO test_index_virtual VALUES (1, '{"c": "foo", "d": "bar", "e": 5}');

SELECT c, e FROM test_index_virtual@test_index_virtual_c_e_idx WHERE c = 'foo' AND e > 4; --! fails
SELECT c, e FROM test_index_virtual@test_index_virtual_c_e_idx WHERE c is not null and e is not null; --! works
SELECT c, e FROM test_index_virtual@test_index_virtual_c_e_idx WHERE c is not null and e is not null and c = 'foo' and e > 4; --! fails
```

**Comment by cty123** [comment]
Result wise, I can tell they are the same

```sql
root@127.0.0.1:26257/defaultdb> select c,e,a from test_index_stored where c = 'foo' and e > 2;                                      
   c  | e | a
------+---+----
  foo | 4 | 1
(1 row)

Time: 1ms total (execution 1ms / network 0ms)

-----------------------------------------------------------------------------------------------------------------

root@127.0.0.1:26257/defaultdb> select c,e,a from test_index_virtual where c = 'foo' and e > 2;                                     
   c  | e | a
------+---+----
  foo | 4 | 1
(1 row)

Time: 2ms total (execution 2ms / network 0ms)
```

but plan wise, they are not exactly the same,

```sql
root@127.0.0.1:26257/defaultdb> explain select c,e,a from test_index_stored where c = 'foo' and e > 2;                              
                                                             info
-------------------------------------------------------------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • scan
    estimated row count: 1 (100% of the table; stats collected 20 minutes ago; using stats forecast for 4 days in the future)
    table: test_index_stored@test_index_stored_c_e_idx (partial index)
    spans: [/'foo'/3 - /'foo']
(7 rows)

Time: 1ms total (execution 1ms / network 0ms)



============================================================================



root@127.0.0.1:26257/defaultdb> explain select c,e,a from test_index_virtual where c = 'foo' and e > 2;                             
                                                                 info
---------------------------------------------------------------------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • render
  │
  └── • index join
      │ estimated row count: 1
      │ table: test_index_virtual@test_index_virtual_pkey
      │
      └── • scan
            estimated row count: 1 (100% of the table; stats collected 20 minutes ago; using stats forecast for 4 days in the future)
            table: test_index_virtual@test_index_virtual_c_e_idx (partial index)
            spans: [/'foo'/3 - /'foo']
(13 rows)

Time: 1ms total (execution 1ms / network 0ms)
```

My finding is that, the execution time of the `virtual` is always slower than the execution time of `stored`,  and the query plan of virtual always needs to do the join with the primary key index, even when the selected fields can be fully covered by the index.

My guess is that the during the planning, the virtual fields got replaced with `b->>xxx`, so that the field `b` was included in the output columns.

**Review by DrewKimball — APPROVED** [review]
:lgtm: Great work!

> Reviewed 1 of 1 files at r1, 7 of 7 files at r2, 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123163#-:-NwkVoeU6n2J_YHFaV2K:bolbkdq)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner, @michae2, and @rytaft)

___
*[`pkg/sql/opt/partialidx/testdata/implicator/virtual` line 9 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123163#-NwkTD6X0pfHS9H8D7PZ:-NwkTD6X0pfHS9H8D7P_:b42yme5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7d64121c635331df604d7df6df9fe3be3fdd7b0/pkg/sql/opt/partialidx/testdata/implicator/virtual#L9)):*
> ```
> # virtual computed columns are rewritten with the computed expression so that
> # they can be pushed into Projects and filter directly above a Scans. Similarly,
> # predicates referencing virtual computed columns
> ```

[nit] looks like this comment got cut off.

**Comment by mgartner** [comment]
@cty123 The index-join is the result of another limitation. I've explained it in further detail in #123320.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123163)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball, @michae2, and @rytaft)

___
*[`pkg/sql/opt/partialidx/testdata/implicator/virtual` line 9 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123163#-NwkTD6X0pfHS9H8D7PZ:-NwkYIvx1hc8C5MFPFNS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7d64121c635331df604d7df6df9fe3be3fdd7b0/pkg/sql/opt/partialidx/testdata/implicator/virtual#L9)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] looks like this comment got cut off.
</blockquote></details>

Done.

**Comment by mgartner** [comment]
TFTR!

bors r+

**Pull request merged**
