### PR TITLE
physicalplan: do not simply project out render expressions

### LINKED ISSUE #108901: roachtest: unoptimized-query-oracle: unexpectedly different number of columns are output: expected [], actual [float]
roachtest.unoptimized-query-oracle/disable-rules=half/seed-multi-region [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11354773?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/11354773?buildTab=artifacts#/unoptimized-query-oracle/disable-rules=half/seed-multi-region) on release-23.1 @ [e0e71af3fc0d357968e5dc46ca95d881bc8937e4](https://github.com/cockroachdb/cockroach/commits/e0e71af3fc0d357968e5dc46ca95d881bc8937e4):

```
(query_comparison_util.go:252).runOneRoundQueryComparison: internal error while running optimized statement. 1501 statements run: pq: internal error: unable to vectorize execution plan: unexpectedly different number of columns are output: expected [], actual [float]
test artifacts and logs in: /artifacts/unoptimized-query-oracle/disable-rules=half/seed-multi-region/run_1
```
<p>Parameters: <code>ROACHTEST_arch=amd64</code>
, <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/p/roachfana/teamcity-11354773-1692250972-56-n9cpu4-geo/1692277114986/1692277878220)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #108527 roachtest: unoptimized-query-oracle/disable-rules=half/seed-multi-region failed [C-test-failure O-roachtest O-robot T-sql-queries branch-master release-blocker]
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*unoptimized-query-oracle/disable-rules=half/seed-multi-region.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-30697

### PR DESCRIPTION
**Pull request by yuzefovich**
Previously, whenever we were applying a projection on top of render expressions, we would simply re-order the render expressions accordingly. However, I believe this might be incorrect in some edge cases when the render expressions result in errors. This shouldn't happen often since these cases are usually determined by the optimizer before getting to the physical planning, but we just saw one case where disabling some optimizer rules created such a plan that would either incorrectly return a result (if executed locally) or hit an internal error (if executed in distributed fasthion) whereas it should return "out of range" error.

This commit fixes this problem by allowing the projection to simply reorder the render expressions only if all render expressions are projected at least once, otherwise we add a new noop processor. This might result in a minor performance hit but it should be negligible.

Fixes: #108901.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Interestingly, no error occurs when running the reproduction query locally, and it's tracked by #108962.

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108952#-:-Nc9Dj9R5PYc8fwnaCAB:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by michae2** [comment]
Do we also want to backport this to release-23.1.9-rc?

**Comment by yuzefovich** [comment]
I don't think so - this code is extremely old, so we'd be taking bigger risk when backporting then when not doing that. I'm still on the fence about 23.1 backport, but I definitely want to have some baking time on master first.

**Pull request merged**
