### PR TITLE
coldata: change Batch interface to operate with int length

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit changes Batch interface to operate with `int` length
because it unifies the way we store batches - now we will have a single
implementation `MemBatch` (with an exception for `coldata.ZeroBatch`). This
allows us to remove `bufferedBatch`.

Release note: None

### CODE REVIEW

**Comment by asubiotto** [comment]
Is this RFAL?

**Comment by yuzefovich** [comment]
RFAL.

**Comment by yuzefovich** [comment]
Ran some benchmarks, and it seems like `int` is less performant (with more variance) than `uint64`.

This [doc](https://gist.github.com/yuzefovich/56c1db4ac009bbedd41979c2f7758f06) are the benchmarks of master vs only the first commit in this PR.

This [doc](https://gist.github.com/yuzefovich/afb740fb4ae34e81b7b8ecc98c70dc4f) are the benchmarks of master vs both commits in this PR (the motivation was that it seemed like nulls cases became slower, I did change the arguments from `uint64` to `int` and added an assertion, so I wanted to see that that wasn't the issue).

**Comment by yuzefovich** [comment]
Ran some more benchmarks.

Rerunning on gceworker [uint16 vs uint64](https://gist.github.com/yuzefovich/588272284b96ba7079073d9acc4c1345).

And actually comparing the two choices to each other [uint64 vs int (without nulls assertion)](https://gist.github.com/yuzefovich/5883e020e6ae643674593088c9f21467). Seems like `uint64` is slightly more performant on average here as well.

**Comment by asubiotto** [comment]
I think part of the problem with nulls is that we simplified the `NullAt` code when we had uint64's and do a division by 8. In the case of the uint64 this gets optimized to bit operations while in the int case it doesn't. I wonder what happens if you do the division using bit operations in the int case.

**Comment by yuzefovich** [comment]
I think you're right about nulls. I switched division by 8 and modulo by 8 to explicit bit operations. I also removed some of the unnecessary `int()` conversions from `_tmpl` files (apparently, they are not checked by the linter).

Here are the new benchmarks:
- [uint64 vs int](https://gist.github.com/yuzefovich/3082837263625b2310dc4ad645703357)
- [uint16 (master) vs int](https://gist.github.com/yuzefovich/fcb161ff88f6995fac0647f80e169c12)

Seems like we can proceed with `int`, there only worrisome benchmark is of the hash joiner, but I think that can be addressed separately. We might want to switch `hashTable` to operate on `int`s as well, that might be the issue.

**Comment by yuzefovich** [comment]
One of the nice things about using `int`s for the selection vector is that we might be able to remove some of the templated `if` statements which we needed to convert previous `uint16` to `int` - now we can iterate over the loop with `for _, idx := range sel[:n]` and `for idx := 0; idx < n; idx++` and `idx` will be of the same `int` type. I actually made such simplification in one of the templates.

**Comment by yuzefovich** [comment]
By accident, when updating `uint64` branch to use `int`s instead, I replaced `OpStr` of hash overloads in `overloads.go`. This caused the hash operations to have `uint64(int(...))` conversions which showed up in the benchmarks. I updated the hash joiner benchmark with this change reverted, and now they look reasonable, so I don't see any worrisome regressions. RFAL.

**Comment by asubiotto** [comment]
Awesome, will take a look today.

**Review by asubiotto — APPROVED** [review]
:lgtm: just to double check, you disabled batch size randomization in the benchmarks, right?

> Reviewed 5 of 120 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45534#-:-M1QmYHT4Wnaarvt2N9_:b-cx7zsb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/col/coldata/nulls_test.go, line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45534#-M1QmtXE2oSjg2N5hsat:-M1QmtXE2oSjg2N5hsau:b-5kjgyf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a42708b3a825c80a9fca1cba0814aa77d24838c/pkg/col/coldata/nulls_test.go#L162)):*
> ```Go
> 		for _, i := range swapPos {
> 			for _, j := range swapPos {
> 				n.swap(uint64(i), uint64(j))
> ```

Can we change swap to take in `int` arguments as well?

**Review by yuzefovich — COMMENTED** [review]
Yes, batch size randomization was disabled on both gceworker and MBP.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45534#-:-M1RBbHa6-WiHyF-eHC-:b-i3zsqq)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

___
*[pkg/col/coldata/nulls_test.go, line 162 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45534#-M1QmtXE2oSjg2N5hsat:-M1RBaJB1M6swk2jlZpP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a42708b3a825c80a9fca1cba0814aa77d24838c/pkg/col/coldata/nulls_test.go#L162)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Can we change swap to take in `int` arguments as well?
</blockquote></details>

Done.

**Comment by asubiotto** [comment]
:shipit:

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
