### PR TITLE
kv: don't use LegacyTimestamp in Liveness records

### PR DESCRIPTION
**Pull request by nvb**
Completes migration started in 9c0dce9.

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56190#-:-MLJeIHa8V9gfecu5R5y:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

**Comment by nvanbenschoten** [comment]
This appears to be running into issues with the `acceptance/version-upgrade` test. I think this is because master still reports a `v20.2.0` build tag, so we still start with a v20.1 cluster in that test. I'll need to fix that first before merging the rest of this.

**Comment by andreimatei** [comment]
maybe #55520 helps

**Comment by nvanbenschoten** [comment]
It does! Thanks for the pointer.

**Comment by lucy-zhang** [comment]
I just pushed a `v21.1.0-alpha.00000000` tag on a recent commit on the master branch, so if you rebase, the roachtest should work.

**Comment by nvanbenschoten** [comment]
Thanks @lucy-zhang! Your change worked. Unfortunately, it revealed that the node liveness code wasn't as ready as it thought it was for variable proto encoding. So we're going to have to land https://github.com/cockroachdb/cockroach/pull/56477 in v21.1 and hold off on this PR until v21.2. That's a shame, but nothing depends on this change so we can just wait it out.

**Pull request closed without merging**
