### PR TITLE
go.mod: upgrade etcd-io/raft to 515b1428

### PR DESCRIPTION
**Pull request by pav-kv**
This includes https://github.com/etcd-io/raft/pull/32 which fixes an out-of-memory scenario during election with large unapplied Raft logs.

Part of #104402
Epic: none
Release note (bug fix): Fixed a bug in upstream etcd-io/raft which could result in pulling unlimited amount of log into memory, and lead to out-of-memory situations. With the fix, the log scan has a limited memory footprint.

### CODE REVIEW

**Review by tbg — APPROVED** [review]

**Comment by pavelkalinnikov** [comment]
bor r=tbg

**Comment by pavelkalinnikov** [comment]
bors retry

**Comment by pavelkalinnikov** [comment]
bors r=tbg

**Comment by pavelkalinnikov** [comment]
bors retry

**Pull request merged**
