### PR TITLE
sql: move RowContainer and row comparison to sqlbase

### PR DESCRIPTION
**Pull request by RaduBerinde**
`RowContainer` will be used by `distsqlrun`.

### CODE REVIEW

**Comment by knz** [comment]
Moving `ResultColumns` to `sqlbase` is a better way to fit the peg to the hole than allocating multiple additional slices per query without any computational benefit! 

---

Reviewed 4 of 4 files at r1, 9 of 9 files at r2, 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/executor.go, line 1001 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15310#-KiZX7Om9XWFFljnJVTb:-KiZX7Om9XWFFljnJVTc:bgkq2pv) ([raw file](https://github.com/cockroachdb/cockroach/blob/69e0ada7f7189fc284e2c1e27fa5fde3551d66fb/pkg/sql/executor.go#L1001)):*
> ```Go
> 	result.Type = (*parser.Show)(nil).StatementType()
> 	result.Columns = ResultColumns{{Name: "TRANSACTION STATUS", Typ: parser.TypeString}}
> 	result.Rows = sqlbase.NewRowContainer(session.makeBoundAccount(), result.Columns.Types(), 0)
> ```

Argh we're allocating a slice extra now for every row container... We can do better: what about moving ResultColumn/ResultColumns to sqlbase instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15310#-:-KiZXt3TWaShMiUKDRSk:ba2fn1o)*

**Comment by RaduBerinde** [comment]
I hesitate because it feels like the wrong interface. Distsql doesn't use ResultColumns, it will have to make up one just to call this function.
We could also provide a callback to get the i-th type instead, not sure if that also always involves an allocation though.

**Comment by knz** [comment]
An alternative would be to have ResultColumn hold separate slices for the types and the names.

**Comment by RaduBerinde** [comment]
But then aren't we just moving the allocation to wherever ResultColumns are created (which is in most nodes, more per query than RowContainers)?

If I move ResultColumns, I could provide two interfaces for convenience - one with ResultColumns, one which takes []ColumnType. Perhaps that's the best way.

**Comment by knz** [comment]
Yes my proposal was not very good wrt allocations, at least not until we make ResultColumn allocate sub-slices from a pool. Your alternative sounds good.

**Comment by RaduBerinde** [comment]
Moved `ResultColumns` to `sqlbase`.

**Comment by knz** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1, 53 of 54 files at r5, 1 of 1 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15310#-:-Ki_9k02LocsJybKASdV:bnfp4nl)*

**Pull request merged**
