### PR TITLE
importccl: enabling saving of bad csv rows to a side file

### PR DESCRIPTION
**Pull request by spaskob**
importccl: enabling saving of bad csv rows to a side file

When importing from large csv files it's common to have a few offending rows.
Currently `IMPORT` will abort at the first error which makes for a tedious
task of manually fixing ech problem and re-running. Instead users can specify
new option `WITH experimental_save_rejected` which will not stop on bad rows
but save them in a side file called `<original_csv_file>.rejected` and
continue. The user then can re-run the import command using `IMPORT INTO` using
the rejected file after fixing the problems in it.

Touches #40374.

Release note (sql change): enable skipping of faulty rows in IMPORT.

### CODE REVIEW

**Review by dt — COMMENTED** [review]
> Reviewed 8 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41430)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @spaskob)

___
*[pkg/ccl/importccl/import_stmt.go, line 292 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41430#-LqgnuKM0MrIGyyYET2C:-LqgnuKM0MrIGyyYET2D:b-u1wocp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9003d10b89bf33cdd2a982f560bc29e0c2e31a2/pkg/ccl/importccl/import_stmt.go#L292)):*
> ```Go
> 			// is passed in all import formats not just DELIMITED..
> 			if _, ok := opts[importOptionSaveRejected]; ok {
> 				format.MysqlOut.SaveRejected = true
> ```

this doesn't feel like a per-format option to me? I guess the level at which we can reject depends on the format, and support will arrive in formats one-by-one, but the option feels more general to me and should be either at the job level or at least at the top level in format options.
___
*[pkg/ccl/importccl/import_stmt_test.go, line 240 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41430#-Lqlj0p34MSguuHSBHfq:-Lqlj0p34MSguuHSBHfr:bd4jmsg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9003d10b89bf33cdd2a982f560bc29e0c2e31a2/pkg/ccl/importccl/import_stmt_test.go#L240)):*
> ```Go
> 		// MySQL OUTFILE
> 		// If err field is non-empty, the query filed specifies what expect
> 		// to get from the rows that are parsed correctly (see option experimental_save_rejected).
> ```

I think we should also have a field that is there content of the rejected row file?
___
*[pkg/ccl/importccl/read_import_base.go, line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41430#-LqgpkKlBh9h1vL-WYe2:-LqgpkKlBh9h1vL-WYe3:bqk6e6e) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9003d10b89bf33cdd2a982f560bc29e0c2e31a2/pkg/ccl/importccl/read_import_base.go#L133)):*
> ```Go
> 				rejected = make(chan string)
> 			}
> 			grp := ctxgroup.WithContext(ctx)
> ```

tiny nit, but I might move the `if rejected != nil` out here and only spin up the group / use the the group to call fileFunc in the non-nil branch, keeping the direct call to `fileFunc` in normal, non-rejecting execution, just to avoid the extra goroutine(s) unless we need them.
___
*[pkg/ccl/importccl/read_import_base.go, line 140 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41430#-LqgqnswCUyR03sYh4Ge:-Lqgqnsx-2rOwkwB3xnh:b-taaaqb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9003d10b89bf33cdd2a982f560bc29e0c2e31a2/pkg/ccl/importccl/read_import_base.go#L140)):*
> ```Go
> 				suffix := ".rejected"
> 				if es.Conf().Provider == roachpb.ExportStorageProvider_Http {
> 					suffix = "/rejected"
> ```

Why is this case different?
___
*[pkg/ccl/importccl/read_import_base.go, line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41430#-LqgqWsm8aDF4DrMEUXD:-LqgqWsm8aDF4DrMEUXE:bjxyfhx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9003d10b89bf33cdd2a982f560bc29e0c2e31a2/pkg/ccl/importccl/read_import_base.go#L142)):*
> ```Go
> 					suffix = "/rejected"
> 				}
> 				conf, err := storageccl.ExportStorageConfFromURI(dataFile + suffix)
> ```

I don't think you can blindly append to the _string URI_ since almost all of them use query parameters to pass options, like keys or settings. 

I think you need to do `net/url.Parse()`, append to the `url.Path` field, and then serialize the result to a string and pass _that_ to makeStorage, so that trailing parameters are correctly preserved.
___
*[pkg/ccl/importccl/read_import_base.go, line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41430#-LqgrXpO0vUf65u6oVYG:-LqgrXpO0vUf65u6oVYH:b-tv5po0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9003d10b89bf33cdd2a982f560bc29e0c2e31a2/pkg/ccl/importccl/read_import_base.go#L146)):*
> ```Go
> 					return err
> 				}
> 				rejectedStorage, err := storageccl.MakeExportStorage(ctx, conf, settings)
> ```

I think we should wait to open this file until the first rejected row shows up in the loop below, so that we don't open (and create) it at all if all the rows process without rejection.
___
*[pkg/roachpb/io-formats.proto, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41430#-LqgoCLI9sTN6tiV4peX:-LqgoCLI9sTN6tiV4peY:bbmdfe5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9003d10b89bf33cdd2a982f560bc29e0c2e31a2/pkg/roachpb/io-formats.proto#L77)):*
> ```protobuf
>   optional int32 escape = 6 [(gogoproto.nullable) = false];
>   // If true, don't abort on failures but instead save the offending row and keep on.
>   optional bool save_rejected = 7 [(gogoproto.nullable) = false];
> ```

ditto comment above.

**Review by spaskob — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41430)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/ccl/importccl/import_stmt.go, line 292 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41430#-LqgnuKM0MrIGyyYET2C:-LqlpT49A2LySRAoqLYt:bdjkh5s) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9003d10b89bf33cdd2a982f560bc29e0c2e31a2/pkg/ccl/importccl/import_stmt.go#L292)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

this doesn't feel like a per-format option to me? I guess the level at which we can reject depends on the format, and support will arrive in formats one-by-one, but the option feels more general to me and should be either at the job level or at least at the top level in format options.
</blockquote></details>

agreed, notice the TODO just above that addresses this. Since this will be fairly big refactor are you ok with keeping it in DELIMITED at first and once we nail DELIMITED I will refactor it out and start implementing for other modes.
___
*[pkg/ccl/importccl/import_stmt_test.go, line 240 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41430#-Lqlj0p34MSguuHSBHfq:-LqlpqMaEIK-Bxocb4rm:bj3nlcr) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9003d10b89bf33cdd2a982f560bc29e0c2e31a2/pkg/ccl/importccl/import_stmt_test.go#L240)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I think we should also have a field that is there content of the rejected row file?
</blockquote></details>

yes, this is tbd until i figure out the threading through the http test server
___
*[pkg/ccl/importccl/read_import_base.go, line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41430#-LqgpkKlBh9h1vL-WYe2:-LqlstIQ9aMbQTIcAc32:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9003d10b89bf33cdd2a982f560bc29e0c2e31a2/pkg/ccl/importccl/read_import_base.go#L133)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

tiny nit, but I might move the `if rejected != nil` out here and only spin up the group / use the the group to call fileFunc in the non-nil branch, keeping the direct call to `fileFunc` in normal, non-rejecting execution, just to avoid the extra goroutine(s) unless we need them.
</blockquote></details>

done
___
*[pkg/ccl/importccl/read_import_base.go, line 140 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41430#-LqgqnswCUyR03sYh4Ge:-LqlqCP3Bfp-VHHLzq6d:b42wfhl) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9003d10b89bf33cdd2a982f560bc29e0c2e31a2/pkg/ccl/importccl/read_import_base.go#L140)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Why is this case different?
</blockquote></details>

http uri is 192.0.0.1:<port#> and you append .rejected to it becomes invalid http request
this is still WIP, hacking it like this for now to have unit tests working
___
*[pkg/ccl/importccl/read_import_base.go, line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41430#-LqgqWsm8aDF4DrMEUXD:-LqlqZfT6_MrCgPVbw7l:b9gzp78) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9003d10b89bf33cdd2a982f560bc29e0c2e31a2/pkg/ccl/importccl/read_import_base.go#L142)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I don't think you can blindly append to the _string URI_ since almost all of them use query parameters to pass options, like keys or settings. 

I think you need to do `net/url.Parse()`, append to the `url.Path` field, and then serialize the result to a string and pass _that_ to makeStorage, so that trailing parameters are correctly preserved.
</blockquote></details>

thanks, TBD
___
*[pkg/ccl/importccl/read_import_base.go, line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41430#-LqgrXpO0vUf65u6oVYG:-Lqlt-bH1EuFyF5XB2Qj:b59m4dk) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9003d10b89bf33cdd2a982f560bc29e0c2e31a2/pkg/ccl/importccl/read_import_base.go#L146)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I think we should wait to open this file until the first rejected row shows up in the loop below, so that we don't open (and create) it at all if all the rows process without rejection.
</blockquote></details>

good point, done
___
*[pkg/roachpb/io-formats.proto, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41430#-LqgoCLI9sTN6tiV4peX:-Lqlqhgb7PGK97C-PHLc:b2nhysk) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9003d10b89bf33cdd2a982f560bc29e0c2e31a2/pkg/roachpb/io-formats.proto#L77)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

ditto comment above.
</blockquote></details>

ack

**Review by spaskob — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41430)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/ccl/importccl/import_stmt_test.go, line 240 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41430#-Lqlj0p34MSguuHSBHfq:-LqzvwZlA_B0d6QxDnJ3:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9003d10b89bf33cdd2a982f560bc29e0c2e31a2/pkg/ccl/importccl/import_stmt_test.go#L240)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

yes, this is tbd until i figure out the threading through the http test server
</blockquote></details>

done
___
*[pkg/ccl/importccl/read_import_base.go, line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41430#-LqgrXpO0vUf65u6oVYG:-Lqzw6hp9Dn1LCcECFTG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e9003d10b89bf33cdd2a982f560bc29e0c2e31a2/pkg/ccl/importccl/read_import_base.go#L146)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

good point, done
</blockquote></details>

Done.

**Comment by spaskob** [comment]
PTAL

**Review by dt — APPROVED** [review]
> Reviewed 7 of 11 files at r2, 1 of 3 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41430)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @spaskob)

___
*[pkg/ccl/importccl/read_import_base.go, line 115 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41430#-Lr9Ns4j6-7s0IWIADCY:-Lr9Ns4j6-7s0IWIADCZ:bg5z0mc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0773066e551937130a4b55f12bf669590f38185/pkg/ccl/importccl/read_import_base.go#L115)):*
> ```Go
> 						atFirstLine = false
> 					}
> 					if atFirstLine {
> ```

nit: I think we could just use `len(buf) > 0`

**Review by spaskob — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41430)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/ccl/importccl/read_import_base.go, line 115 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41430#-Lr9Ns4j6-7s0IWIADCY:-LrA16gNAX7arDBh7Gu7:b-kr0v6d) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0773066e551937130a4b55f12bf669590f38185/pkg/ccl/importccl/read_import_base.go#L115)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

nit: I think we could just use `len(buf) > 0`
</blockquote></details>

you are right, I initially thought that buf can be empty but that there's still an error but in that case it still does not make sense to write the reject file anyway.

**Pull request merged**
