### PR TITLE
sql: handle tuples with nulls for IN operator 

### PR DESCRIPTION
**Pull request by rafiss**
A previous change had allowed any query of the form <left> IN <subquery>
to typecheck as long as <left> is NULL or a tuple containing any NULLS.

This erroneously allowed something like `('s', NULL) IN (1, 2)` to
typecheck. Now, this is fixed, by making sure all the non-null tuple
elements have the same type.

A release note is omitted as this fixes a bug that is only present in
non-published versions of CockroachDB.

See #49723 and https://github.com/cockroachdb/cockroach/pull/49767#pullrequestreview-422136291

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49814)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @RaduBerinde, and @rafiss)

___
*[pkg/sql/types/types.go, line 1743 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49814#-M9L7Uqz948ck0EsdCAr:-M9L7Ur-8_OxgwgOpJfP:bnzg5vv) ([raw file](https://github.com/cockroachdb/cockroach/blob/91658bf6588af86e8390ab975acc6ca177142396/pkg/sql/types/types.go#L1743)):*
> ```Go
> 			}
> 		}
> ```

I think we should be checking if `other` is also TupleFamily. Looks like we would return true if `t` is an empty tuple and `other` is not a tuple, e.g. `SELECT () IN (1,2)` (i'd add a test like that)

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49814)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @RaduBerinde)

___
*[pkg/sql/types/types.go, line 1743 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49814#-M9L7Uqz948ck0EsdCAr:-M9Lqir7Ek6WKPARbM2p:b-tcglzy) ([raw file](https://github.com/cockroachdb/cockroach/blob/91658bf6588af86e8390ab975acc6ca177142396/pkg/sql/types/types.go#L1743)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I think we should be checking if `other` is also TupleFamily. Looks like we would return true if `t` is an empty tuple and `other` is not a tuple, e.g. `SELECT () IN (1,2)` (i'd add a test like that)
</blockquote></details>

good call -- that example is currently correct, but something like `SELECT NULL IN (SELECT * FROM (VALUES (1, 1)) AS t(a, b));` is not handled right now. adding a test and fixing.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49814)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @RaduBerinde)

___
*[pkg/sql/types/types.go, line 1743 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49814#-M9L7Uqz948ck0EsdCAr:-M9M6UYf522BwRS2HAGw:b8405hc) ([raw file](https://github.com/cockroachdb/cockroach/blob/91658bf6588af86e8390ab975acc6ca177142396/pkg/sql/types/types.go#L1743)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

good call -- that example is currently correct, but something like `SELECT NULL IN (SELECT * FROM (VALUES (1, 1)) AS t(a, b));` is not handled right now. adding a test and fixing.
</blockquote></details>

ah, got it now: `SELECT () IN (SELECT * FROM (VALUES (1)) AS t(a))` tests the case that you pointed out.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49814)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @RaduBerinde, and @rafiss)

___
*[pkg/sql/logictest/testdata/logic_test/select, line 487 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49814#-M9MOEa38HLwFHivygxH:-M9MOEa38HLwFHivygxI:b-6i3e7y) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0f00cf1c49c997fb7ff463f6beaaab6e13cbf10/pkg/sql/logictest/testdata/logic_test/select#L487)):*
> ```
> NULL
> 
> query error unsupported comparison operator: <unknown> IN <tuple{tuple{int AS a, int AS b}}>
> ```

Why can't NULL pass as a tuple? `SELECT NULL IN (ROW (1,1), ROW(2,2));` works in postgres.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49814)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @RaduBerinde)

___
*[pkg/sql/logictest/testdata/logic_test/select, line 487 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49814#-M9MOEa38HLwFHivygxH:-M9Q2Ne19eW2KKjZv85V:b4b2wl8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0f00cf1c49c997fb7ff463f6beaaab6e13cbf10/pkg/sql/logictest/testdata/logic_test/select#L487)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Why can't NULL pass as a tuple? `SELECT NULL IN (ROW (1,1), ROW(2,2));` works in postgres.
</blockquote></details>

i believe that is tested on line 395, i left a comment there.

for whatever reason, in postgres, these queries work:
```
SELECT NULL IN (ROW (1,1), ROW(2,2));
SELECT NULL IN ((1, 1))
SELECT NULL IN (SELECT * FROM (VALUES (1)) AS t(a))
```

but this one doesn't:
```
SELECT NULL IN (SELECT * FROM (VALUES (1, 1)) AS t(a, b))
```

so i've made this logic test assert that behavior as well.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49814#-:-M9Q6TxH1Lq0W2IfRp0N:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/logictest/testdata/logic_test/select, line 487 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49814#-M9MOEa38HLwFHivygxH:-M9Q6b3sE4fUsv9sz8dU:bsb8eu2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0f00cf1c49c997fb7ff463f6beaaab6e13cbf10/pkg/sql/logictest/testdata/logic_test/select#L487)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i believe that is tested on line 395, i left a comment there.

for whatever reason, in postgres, these queries work:
```
SELECT NULL IN (ROW (1,1), ROW(2,2));
SELECT NULL IN ((1, 1))
SELECT NULL IN (SELECT * FROM (VALUES (1)) AS t(a))
```

but this one doesn't:
```
SELECT NULL IN (SELECT * FROM (VALUES (1, 1)) AS t(a, b))
```

so i've made this logic test assert that behavior as well.
</blockquote></details>

Ah, I see. How does our code distinguish between these two? Isn't it the same operator `<unknown> IN <tuple{tuple{int AS a, int AS b}}>` in both cases?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49814)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/logictest/testdata/logic_test/select, line 487 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49814#-M9MOEa38HLwFHivygxH:-M9TlQZo3DCtTcFTmm2X:bzgntlv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0f00cf1c49c997fb7ff463f6beaaab6e13cbf10/pkg/sql/logictest/testdata/logic_test/select#L487)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Ah, I see. How does our code distinguish between these two? Isn't it the same operator `<unknown> IN <tuple{tuple{int AS a, int AS b}}>` in both cases?
</blockquote></details>

the `typeCheckComparisonOp` function differentiates these cases:

https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/tree/type_check.go#L1887-L1897

in the tuple case, it calls `TypeCheckSameTypedExprs`, which allows NULLs.

also, there's an optimizer rule for this that must come into play as well (`FoldNullInNonEmpty`):

https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/opt/norm/rules/fold_constants.opt#L39-L61

**Pull request merged**
