### PR TITLE
storage: Add tests for a new node using the same address as an old one

### LINKED ISSUE #10266: storage: restarting node without its data causes other nodes to get stuck
What I did:
1. Created a 3-node insecure cluster on build beta-20161013-297-g33c94fa
2. Opened up a SQL shell on the first node and ran `SHOW DATABASES;` and `CREATE DATABASE foo;`
3. Killed the first node
4. Created a new node with the same hostname as the original first node ("cockroachdb-0.cockroachdb.default.svc.cluster.local", this was on kubernetes) but with an empty/new data directory
5. Open up a SQL shell against any of the 3 nodes and run `SHOW DATABASES;`

This returns the error `pq: store 1 not found` on all of the cockroachdb nodes. This error sticks around for more than 5 minutes after taking down the old node and bringing up the new one. In fact, it didn't go away for a solid 10 minutes, so it seems as though it may be permanent.

I decided to restart the new node. Shutting it down immediately caused the other 2 nodes to start working again, and the new node worked fine as well when it came back up. I've attached the logs for the new node both times that it came up as well as one of the other nodes.

It looks like this error has been seen before in #5056/#5166, but those have both been long closed.

[node0-attempt1.txt](https://github.com/cockroachdb/cockroach/files/556367/node0-attempt1.txt)
[node0-attempt2.txt](https://github.com/cockroachdb/cockroach/files/556366/node0-attempt2.txt)
[node1.txt](https://github.com/cockroachdb/cockroach/files/556368/node1.txt)

### LINKED ISSUE #10613: storage: consistency checker diff calculation uses a cancelled context
Discovered while investigating #10602.

When `Replica.ConsistencyChecker` discovers an inconsistency, it spawns a new goroutine using `Stopper.RunAsyncTask` and recursively calls itself pass `withDiff = true`. But the new goroutine is passed the original context and when `Replica.ConsistencyChecker` returns the context is cancelled fairly soon. The result is that we never perform the diff check and never exist on consistency failures.

### PR DESCRIPTION
**Pull request by a-robinson**
Includes a system-y test that uses a TestCluster (and a corresponding fix for using/handling the `StoreNotFoundError` in the `dist_sender` path for local TestCluster requests) and a unit test that more directly verifies the raft transport's behavior.

These are the follow-up tests I owed on #10544, which fixed #10266.

@tamird

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10699)

### CODE REVIEW

**Comment by tamird** [comment]
What's the relationship between the first commit and the last? Do they need to be squashed together?

---

Reviewed 3 of 3 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[pkg/kv/dist_sender.go, line 1200 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10699#-KWcY5rUI8rO4zb0oMUh:-KWcY5rUI8rO4zb0oMUi:bchala0) ([raw file](https://github.com/cockroachdb/cockroach/blob/4972de775940ee1ccf351dcde35c0ae2a9f7f93f/pkg/kv/dist_sender.go#L1200)):*
> ```Go
> 		return true
> 	case *roachpb.StoreNotFoundError:
> 		return true
> ```

if you omit this change, what fails?

---

*[pkg/storage/gossip_test.go, line 144 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10699#-KWcZ1mslwdetGVqjkcg:-KWcZ1mslwdetGVqjkch:b-4mw38x) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb735a48ce463d3e4b4a2616c6e4db92243ebe64/pkg/storage/gossip_test.go#L144)):*
> ```Go
> 
> 	newServerArgs := base.TestServerArgs{
> 		Addr:          tc.Servers[0].ServingAddr(),
> ```

consider a comment and/or extracting this `0` into a named binding so it's obvious that you're constructing a serverArgs to replace the existing server. You could also give this thing a more descriptive name to help with that.

---

*[pkg/storage/gossip_test.go, line 147 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10699#-KWcYWC-Bm5tP_KUmH8S:-KWcYWC-Bm5tP_KUmH8T:bhexmzd) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb735a48ce463d3e4b4a2616c6e4db92243ebe64/pkg/storage/gossip_test.go#L147)):*
> ```Go
> 		PartOfCluster: true,
> 		JoinAddr:      tc.Servers[1].ServingAddr(),
> 		Stopper:       stop.NewStopper(),
> ```

this stopper is never stopped, is it? why not use `tc.Stopper()` here?

---

*[pkg/storage/gossip_test.go, line 156 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10699#-KWcYmuZRz3R8OxO4BCK:-KWcYmuZRz3R8OxO4BCL:b-h01qwh) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb735a48ce463d3e4b4a2616c6e4db92243ebe64/pkg/storage/gossip_test.go#L156)):*
> ```Go
> 	// node, they can get stuck here.
> 	for i := 1; i < 4; i++ {
> 		t.Run(fmt.Sprintf("node %d", i), func(t *testing.T) {
> ```

not sure this is an appropriate use of a sub-test. i can't conceive of a case where one of these would fail consistently but the others would not.

---

*[pkg/storage/raft_transport_test.go, line 88 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10699#-KWcZL2pTu3ycfFa_wHG:-KWcZL2pTu3ycfFa_wHH:b-cjiq9e) ([raw file](https://github.com/cockroachdb/cockroach/blob/5975950d36365062af3aabc737d2a380da81ad7a/pkg/storage/raft_transport_test.go#L88)):*
> ```Go
> 		}
> 	}
> 	log.Fatalf(ctx, "unexpected raft response: %s", resp)
> ```

well now that you're returning something from here, you may as well ditch this panic and return an error.

---

*[pkg/storage/raft_transport_test.go, line 516 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10699#-KWcZwFPQV2k-Qu7mmN2:-KWcZwFPQV2k-Qu7mmN3:bu5g6ut) ([raw file](https://github.com/cockroachdb/cockroach/blob/5975950d36365062af3aabc737d2a380da81ad7a/pkg/storage/raft_transport_test.go#L516)):*
> ```Go
> 	rttcStopper := rttc.stopper
> 	serverStopper := stop.NewStopper()
> 	rttc.stopper = serverStopper
> ```

this stopper dance is pretty sketchy. I don't have a suggestion (because i'm not spelunking through the RaftTransportTestContext code right now) but it may be worth doing a bit of extra work to avoid stopper juggling. If someone adds any method calls on the stopper in newRaftTransportTestContext this will break in very hard to debug ways.

---

*[pkg/storage/raft_transport_test.go, line 524 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10699#-KWcZnvzNwOYkC4hbdqh:-KWcZnvzNwOYkC4hbdqi:b-ca6fhl) ([raw file](https://github.com/cockroachdb/cockroach/blob/5975950d36365062af3aabc737d2a380da81ad7a/pkg/storage/raft_transport_test.go#L524)):*
> ```Go
> 	serverTransport, serverAddr := rttc.AddNodeWithoutGossip(serverReplica.NodeID, util.TestAddr)
> 	rttc.GossipNode(serverReplica.NodeID, serverAddr)
> 	_ = rttc.ListenStore(serverReplica.NodeID, serverReplica.StoreID)
> ```

why the `_ = `? this looks like an ignored error, just remove it. ditto below

---

*[pkg/storage/raft_transport_test.go, line 548 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10699#-KWc_m9kp33QTYRkaV4L:-KWc_m9kp33QTYRkaV4M:b-dxqdsa) ([raw file](https://github.com/cockroachdb/cockroach/blob/5975950d36365062af3aabc737d2a380da81ad7a/pkg/storage/raft_transport_test.go#L548)):*
> ```Go
> 	// Try sending a message to the old server's store (at the address its
> 	// replacement is now running at) before its replacement has been gossiped.
> 	// We just want to ensure that doing so doesn't halt the client transport.
> ```

"halt" meaning deadlock? throughout.

---

*[pkg/storage/raft_transport_test.go, line 586 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10699#-KWc_ykbyNfcTKsi3ueZ:-KWc_ykbyNfcTKsi3ue_:bigcn5y) ([raw file](https://github.com/cockroachdb/cockroach/blob/5975950d36365062af3aabc737d2a380da81ad7a/pkg/storage/raft_transport_test.go#L586)):*
> ```Go
> 		default:
> 		}
> 		return errors.Errorf("expected message commit=2")
> ```

don't want to log the actual message that was instead received?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10699#-:-KWca3F3VgUbNIJ8zPbS:blylzqn)*

**Comment by a-robinson** [comment]
The first commit was needed to make the tests in the third commit pass. The fourth commit is unrelated.

I've just now noticed that this breaks kv's TestRequestToUninitializedRange. Looking into that during/after the SQL core meeting.

---

Review status: 6 of 8 files reviewed at latest revision, 9 unresolved discussions.

---

*[pkg/kv/dist_sender.go, line 1200 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10699#-KWcY5rUI8rO4zb0oMUh:-KWd74jLTXSIxqMb9buz:b-iz52mj) ([raw file](https://github.com/cockroachdb/cockroach/blob/4972de775940ee1ccf351dcde35c0ae2a9f7f93f/pkg/kv/dist_sender.go#L1200)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> if you omit this change, what fails?
</details>
TestGossipHandlesReplacedNode fails because the replacement node is unable to get an ID allocated while starting up, triggering the log.Fatal at https://github.com/cockroachdb/cockroach/blob/master/pkg/server/node.go#L310

---

*[pkg/storage/gossip_test.go, line 144 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10699#-KWcZ1mslwdetGVqjkcg:-KWd87hEfmWFE0V2NUKd:bbdychk) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb735a48ce463d3e4b4a2616c6e4db92243ebe64/pkg/storage/gossip_test.go#L144)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> consider a comment and/or extracting this `0` into a named binding so it's obvious that you're constructing a serverArgs to replace the existing server. You could also give this thing a more descriptive name to help with that.
</details>
Thanks for calling this out, the test deserves a comment and to be made more clear. I should have done that up front given the annoyance I've occasionally experienced trying to figure out precisely what other tests throughout the code are trying to test.

---

*[pkg/storage/gossip_test.go, line 147 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10699#-KWcYWC-Bm5tP_KUmH8S:-KWd92sOjQwIUc16IcZX:b-u6gug) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb735a48ce463d3e4b4a2616c6e4db92243ebe64/pkg/storage/gossip_test.go#L147)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this stopper is never stopped, is it? why not use `tc.Stopper()` here?
</details>
Each server is allocated its own stopper, which is added to the testcluster's stopper when the server is added to the testcluster:
https://github.com/cockroachdb/cockroach/blob/master/pkg/testutils/testcluster/testcluster.go#L164
https://github.com/cockroachdb/cockroach/blob/master/pkg/testutils/testcluster/testcluster.go#L172

---

*[pkg/storage/gossip_test.go, line 156 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10699#-KWcYmuZRz3R8OxO4BCK:-KWd94f6eKwbnkdsCFzD:b-dbzvpb) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb735a48ce463d3e4b4a2616c6e4db92243ebe64/pkg/storage/gossip_test.go#L156)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> not sure this is an appropriate use of a sub-test. i can't conceive of a case where one of these would fail consistently but the others would not.
</details>
There are definitely cases where one of them would fail but not the others, but you're right that's it not deterministic. I only used subtests for the sake of trivially including the node index in the error output (since the error returned from Put doesn't include the key being put to), so I've reverted to not using them.

---

*[pkg/storage/raft_transport_test.go, line 88 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10699#-KWcZL2pTu3ycfFa_wHG:-KWdCVsO5rSxUTdiqv-H:bz0jfcx) ([raw file](https://github.com/cockroachdb/cockroach/blob/5975950d36365062af3aabc737d2a380da81ad7a/pkg/storage/raft_transport_test.go#L88)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> well now that you're returning something from here, you may as well ditch this panic and return an error.
</details>
We never expect this to be called except in the newly added test, so it seems nice to maintain the behavior of failing fast if our expectation is broken rather than passing an error into the innards of theRaftTransport where it may be handled in some other way.

---

*[pkg/storage/raft_transport_test.go, line 516 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10699#-KWcZwFPQV2k-Qu7mmN2:-KWdDn1AC9A_0_XAUUVc:b-7qxbkw) ([raw file](https://github.com/cockroachdb/cockroach/blob/5975950d36365062af3aabc737d2a380da81ad7a/pkg/storage/raft_transport_test.go#L516)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this stopper dance is pretty sketchy. I don't have a suggestion (because i'm not spelunking through the RaftTransportTestContext code right now) but it may be worth doing a bit of extra work to avoid stopper juggling. If someone adds any method calls on the stopper in newRaftTransportTestContext this will break in very hard to debug ways.
</details>
Good point. I had done it this away to avoid adding extra parameters to AddNodeWithoutGossip, but passing in the stopper to it certainly makes this test less convoluted. Done.

---

*[pkg/storage/raft_transport_test.go, line 524 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10699#-KWcZnvzNwOYkC4hbdqh:-KWdBpnfO5fatLHzo882:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5975950d36365062af3aabc737d2a380da81ad7a/pkg/storage/raft_transport_test.go#L524)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> why the `_ = `? this looks like an ignored error, just remove it. ditto below
</details>
Done.

---

*[pkg/storage/raft_transport_test.go, line 548 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10699#-KWc_m9kp33QTYRkaV4L:-KWdBtuam_j2nIs88t0w:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5975950d36365062af3aabc737d2a380da81ad7a/pkg/storage/raft_transport_test.go#L548)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> "halt" meaning deadlock? throughout.
</details>
Done.

---

*[pkg/storage/raft_transport_test.go, line 586 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10699#-KWc_ykbyNfcTKsi3ueZ:-KWdCHKp6mLwGL_gQBkz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5975950d36365062af3aabc737d2a380da81ad7a/pkg/storage/raft_transport_test.go#L586)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> don't want to log the actual message that was instead received?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10699#-:-KWd6srGOf5_MHf7axHI:bgokxip)*

**Comment by a-robinson** [comment]
Hmm, now that StoreNotFound errors are considered to be per-replica, I'm not sure of an error that we can reasonably use in its place in TestRequestToUninitializedRange. Have any suggestions?

---

Review status: 6 of 8 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10699#-:-KWdPEzfjWt0tLMpyihz:b-24ztct)*

**Comment by tamird** [comment]
Can you give a bit more detail about what the test is doing, how it fails in this PR, etc?

---

Reviewed 2 of 2 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/kv/dist_sender.go, line 1200 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10699#-KWcY5rUI8rO4zb0oMUh:-KWdUGaOaooyVgEK39rv:bc5lgdm) ([raw file](https://github.com/cockroachdb/cockroach/blob/4972de775940ee1ccf351dcde35c0ae2a9f7f93f/pkg/kv/dist_sender.go#L1200)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary>
> TestGossipHandlesReplacedNode fails because the replacement node is unable to get an ID allocated while starting up, triggering the log.Fatal at https://github.com/cockroachdb/cockroach/blob/master/pkg/server/node.go#L310
</details>
I see. However, it seems that `TestGossipHandlesReplacedNode` is added in the 3rd commit, while this is done in the first?

---

*[pkg/testutils/testcluster/testcluster.go, line 164 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/10699#-KWdUn0-w9TaVPX2YUpT:-KWdUn0-w9TaVPX2YUpU:b-gbpxn) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b57a0f08d3c65aebdadd9da1d62a4820f2435ea/pkg/testutils/testcluster/testcluster.go#L164)):*
> ```Go
> 		}
> 		serverArgs.PartOfCluster = true
> 		serverArgs.Stopper = stop.NewStopper()
> ```

would it make sense to put this in `AddServer`? that would remove the odd `stop.NewStopper()` I previously commented on.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10699#-:-KWdVmWhk1oytlWs4feD:blmb9em)*

**Comment by a-robinson** [comment]
The comments in the test can probably explain it better than me: https://github.com/cockroachdb/cockroach/blob/master/pkg/kv/dist_sender_server_test.go#L1222

It's trying to reproduce a panic that was fixed a while back (#6027). It does so by creating an uninitialized range on one store, then sending requests to that bogus range in an attempt to cause a panic. For some reason this requires also having a second store in play but then removing that store as a way to generate non-retryable errors. @bdarnell could probably explain better, since he added this test (along with a disclaimer that it may not be worth maintaining).

---

Review status: 2 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/kv/dist_sender.go, line 1200 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10699#-KWcY5rUI8rO4zb0oMUh:-KWdY-gV7u4stsgabEIZ:b8rrk6i) ([raw file](https://github.com/cockroachdb/cockroach/blob/4972de775940ee1ccf351dcde35c0ae2a9f7f93f/pkg/kv/dist_sender.go#L1200)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I see. However, it seems that `TestGossipHandlesReplacedNode` is added in the 3rd commit, while this is done in the first?
</details>
I was keeping the actual behavior change in a separate commit from the test because the test wasn't added to test this behavior change and thought that keeping them separate made the commit history easier to understand. I apparently was wrong about that :)

---

*[pkg/testutils/testcluster/testcluster.go, line 164 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/10699#-KWdUn0-w9TaVPX2YUpT:-KWdYq2DI7IzBcwtYWVR:b-sc43n3) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b57a0f08d3c65aebdadd9da1d62a4820f2435ea/pkg/testutils/testcluster/testcluster.go#L164)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> would it make sense to put this in `AddServer`? that would remove the odd `stop.NewStopper()` I previously commented on.
</details>
Yeah, that'd be cleaner. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10699#-:-KWdWr47O6gZT4e_qH1v:b-391opb)*

**Comment by bdarnell** [comment]
:lgtm:

I'd just remove TestRequestToUninitializedRange. There may be some way to salvage it (a new testing knob is the most direct solution), but it's unclear whether all the machinations are even reproducing a plausible regression any more.

---

Reviewed 2 of 2 files at r2, 5 of 5 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10699#-:-KWfXrwV_3RSkEkgcn_S:b-xqe050)*

**Comment by tamird** [comment]
Reviewed 5 of 5 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10699)*

**Comment by a-robinson** [comment]
Done, thanks!

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10699#-:-KWhg8ucO10IQx29crsd:b-dtkds3)*

**Comment by tamird** [comment]
Reviewed 1 of 8 files at r10, 2 of 2 files at r11, 4 of 4 files at r12, 1 of 1 files at r13.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10699)*

**Comment by a-robinson** [comment]
It turns out there's still a race in allocating a node ID that pops up in 1 out of every 100-150 runs of TestGossipHandlesReplacedNode that I'm looking further into now. Kudos to @tamird for stressing new tests in the PR builder 👏

**Comment by tamird** [comment]
Awesome! I think this might be the first one caught :)

**Comment by a-robinson** [comment]
Fixed, PTAL. I've had to make another testcluster method public. The issue was a race during the test's shutdown. The test could pass and start shutting down before allocateStoreIDs actually returned, causing its context to timeout while doing things like logging the node join event, which would then lead to the log.Fatal in bootstrapStores getting hit during shutdown.

**Comment by a-robinson** [comment]
...And it found another, even less frequent race in the other test I added. This one appears a little trickier -- something is causing the circuit breaker in raft_transport not to work properly. Back to investigating.

**Comment by tamird** [comment]
Reviewed 2 of 3 files at r14, 1 of 1 files at r15.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10699)*

**Comment by a-robinson** [comment]
Well this is an awkward one. The [circuit breaker package we use](https://github.com/rubyist/circuitbreaker) only tracks its `lastFailure` timestamps with second-level precision, even though it then makes backoff decisions with nanosecond precision. Due to the moderately awkward situation where we [call breaker.Success() when we establish a connection](https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/raft_transport.go#L439) and [breaker.Fail() when a connection fails](https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/raft_transport.go#L445), the fact that a success reduces the backoff time somewhat makes it possible to get into a situation where the time since the last failure is repeatedly greater than the backoff time.

The best solution is to update the upstream circuitbreaker library to store higher precision `lastFailure` timestamps (since this issue affects real code as well), so I'll try to do that. In the meantime we could probably also just subscribe to the circuitbreaker's event feed in this test, but I'll see how quickly we can get upstream fixed.

**Comment by tamird** [comment]
Incredible find. I've said it before and I'll say it again: everything is
garbage.

**Comment by a-robinson** [comment]
Rebased on top of #10746 and now everything is happy. Thanks for the reviews!

**Pull request merged**
