### PR TITLE
kvstreamer: fix some bugs (indefinite hang, request corruption)

### LINKED ISSUE #74853: roachtest: tpchvec/disk failed
roachtest.tpchvec/disk [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4115910&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4115910&tab=artifacts#/tpchvec/disk) on master @ [d6b99e92bf55b6f4a0d79800d67924e04d0b2a6d](https://github.com/cockroachdb/cockroach/commits/d6b99e92bf55b6f4a0d79800d67924e04d0b2a6d):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/tpchvec/disk/run_1
	tpchvec.go:480,tpchvec.go:564,tpchvec.go:587,test_runner.go:780: Non-zero exit code: 1
```
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*tpchvec/disk.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #74898: kv/kvclient/kvstreamer: TestStreamerBudgetErrorInEnqueue failed
kv/kvclient/kvstreamer.TestStreamerBudgetErrorInEnqueue [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4132347&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4132347&tab=artifacts#/) on master @ [5ad21e3896ee809e9c3ebc28bb22166f1275acca](https://github.com/cockroachdb/cockroach/commits/5ad21e3896ee809e9c3ebc28bb22166f1275acca):

Fatal error:

```
panic: root: no bytes in account to release, current 10, free 1048627 [recovered]
	panic: root: no bytes in account to release, current 10, free 1048627

```
Stack: 

```
goroutine 2080 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc0015303f0, {0x4e6b130, 0xc0014076a0})
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:251 +0x94
panic({0x3acbfe0, 0xc000d0ad38})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/cockroachdb/cockroach/pkg/util/log/logcrash.ReportOrPanic({0x4e6b130, 0xc0014076a0}, 0xc0005d4000, {0x3e35ec2, 0x40}, {0xc0021f3a18, 0x7fbdc8ed1108, 0x50})
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/logcrash/crash_reporting.go:376 +0x1af
github.com/cockroachdb/cockroach/pkg/util/mon.(*BoundAccount).Shrink(0xc000d0a4f8, {0x4e6b130, 0xc0014076a0}, 0x100033)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:636 +0x127
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvstreamer.(*budget).release(0xc001d1cc80, {0x4e6b130, 0xc0014076a0}, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvstreamer/budget.go:117 +0xa9
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvstreamer.(*workerCoordinator).performRequestAsync.func1({0x4e6b130, 0xc0014076a0})
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvstreamer/streamer.go:1025 +0x3af
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:488 +0x12a
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:478 +0x445
```
<details><summary>Log preceding fatal error</summary>
<p>

```
=== RUN   TestStreamerBudgetErrorInEnqueue/single_key_exceeds_root_pool_size
```
</p>
</details>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
Parameters in this failure:

- GOFLAGS=-parallel=4
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestStreamerBudgetErrorInEnqueue.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #75256: kvstreamer: streamer can get into more debt than necessary
As the code written currently, `Streamer` is allowed to put its budget into debt when the head-of-the-line request is being executed. At the moment, the "head-of-the-line" means the first request among a batch of requests to be issued. However, that doesn't take into account any already created `Result`s that haven't been `Release`d by the consumer yet.

Consider a scenario when 100 requests can be responded to and the consumer is slow to process already produced results. We might end up in a scenario where the `Streamer` issues and receives the response one request at a time. The results are accumulated, but every request - since there are no other requests in flight - is treated as head-of-the-line, so it is allowed to put the budget into more debt.

I think we should be thinking of a particular request as "head-of-the-line" IFF there are no other requests in flight AND there are no un`Release`d already created results.

UPDATE: this scenario wasn't actually possible because the worker coordinator would not issue more requests since it doesn't have enough budget, and it would block on `waitCh` which only gets notified when the budget gets out of debt. However, there is an issue with an indefinite hang in rare cases.

### PR DESCRIPTION
**Pull request by yuzefovich**
**kvstreamer: fix rare race condition**

This commit refactors the locking logic in an error case in `Enqueue`
where previously we had a rare race condition. We divided the locking
state across two things (the mutex and a boolean indicating whether the
mutex is locked) which together were not accessed atomically. This
commit removes the boolean by forcing that the mutex is held when
`Enqueue` returns.

Release note: None

**kvstreamer: fix the case when root pool is exhausted**

Each request processed asynchronously assumes that the memory footprint
of the spans in the request has already been accounted for. This
assumption was broken in case `Enqueue` encountered an error when
consuming from the budget due to root pool being exhausted.

The sequence of steps to get into a problematic state was as follows:
- spin up the worker coordinator, it blocks until there are any requests
to serve
- populate requests to serve
- `s.mu` is unlocked to perform the memory accounting
- the worker coordinator wakes up and picks up some work
- memory reservation is denied in `Enqueue`, an error is returned; thus,
we have a drift in the memory accounting
- concurrent request is responded to, and when it attempts to reconcile
the memory accounting, a crash (in test builds) occurs because the
memory reservation in `Enqueue` was denied.

This is now fixed by not telling the worker coordinator about the
requests to serve until after the memory accounting is performed.

Fixes: #74898.

Release note: None

**kvstreamer: fix rare cases of worker coordinator being stuck forever**

Previously, it was possible for the worker coordinator to be stuck
indefinitely because we were using a separate mutex for its condition
variable waiting for more work. Namely, the following sequence of events
was possible:
1. `Enqueue` unlocks the `Streamer`'s mutex to make the memory
reservation. Then the goroutine is preempted.
2. the worker coordinator wakes up, checks that there are no requests to
serve, and before it blocks on the condition variable, it is preempted.
3. `Enqueue` goroutine wakes up, adds some requests to serve, and
signals the condition variable. But because no goroutine is currently
waiting on it, no goroutine is woken up.
4. the worker coordinator wakes up and goes into waiting on the
condition variable forever.

This problem is now fixed by using the same `Streamer`'s mutex for the
condition variable used for waiting for work.

Another scenario when the worker coordinator could get stuck was due to
the fact that we were unlocking the `Streamer`'s mutex after retrieving
no requests to proceed and before waiting on the condition variable. Thus,
previously it was possible for a new request to be added and the
condition variable to be signaled before the coordinator started waiting
(which would be forever). This is now fixed by more precise locking of
the mutex.

Release note: None

**kvstreamer: fix the streamer's behavior with a slow consumer**

This commit fixes a case when the worker coordinator could get stuck
indefinitely waiting for budget in some degenerate cases. The way
that would happen was the following:
1. the coordinator checks that there is at least one request in flight.
Its goroutine is then preempted.
2. those concurrent requests in flight finish, decrement the number of
requests in flight to zero, but don't notify the budget's `waitCh`
because the budget didn't get out of debt.
3. the coordinator wakes up, checks that the budget is in debt, and
because it earlier checked that there were some requests in flight (but
not anymore), it starts waiting for some `release` calls, but none
would ever occur.

This is now fixed by always holding the budget's mutex when checking
whether to wait for the next `release` call or until the budget gets out
of debt. The corresponding channel has been refactored to a condition
variable. The condition variable is now additionally signaled when the
last request in flight completes so that the worker coordinator doesn't
wait forever for budget to get out of debt in a degenerate case when it
never will.

Now, due to such signaling, the streamer could get in more debt than
necessary because "head-of-the-line" requests are allowed to put the
budget in more debt than it already is in. Consider a scenario when
many requests need to be responded to and the consumer is slow to
process already produced results. We might end up in a scenario where
the `Streamer` issues and receives the response one request at a time.
The results are accumulated, but every request - since there are no
other requests in flight - is treated as the "head-of-the-line", so
it is allowed to put the budget into more debt.

To improve the behavior in this scenario we introduce the notion of
requests "in progress" which include both requests that are currently
in flight in addition to already created results that haven't been
released yet. Now, the "head-of-the-line" request is such that there are
no other requests in progress.

Fixes: #75256.

Release note: None

**kvstreamer: fix the bug with corrupting request when it is put back**

When the `Streamer` realizes that its budget doesn't allow for
accounting for the received response for not head-of-the-line request,
it puts the original request back to be processed from scratch.
Previously, due to the way the code was structured, it was possible that
the request would get corrupted. Namely, this was the case because we
were updating the original request in-place to include any `ResumeSpan`s
and nilling it out too while we're calculating the total memory
footprint. Then, we'd reconcile the budget, and if the allocation is
denied, then we put the original request back to be processed; however,
at this point the request was already corrupted.

As it turns out, modifying of the original requests is not allowed by
the KV layer, so this commit fixes that as well as the corruption issue
by splitting the iteration over the results into two loops:
- in the first loop, we calculate the memory footprint only as well as
the number of new requests to be created;
- then, we reconcile the budget, and if necessary, put the original
unmodified request back to be served;
- in the second loop, when the budget is successfully reconciled, we're
allocating new requests and updating them with the `ResumeSpan`s.

Additionally, this commit adjusts the calculation of the size of the
responses to be similar to how the responses are accounted for by the KV
layer for the purposes of `TargetBytes`. This is needed because `Size`
methods generated for the protobuf messages automatically include
additional overhead, and we don't want that.

Fixes: #74853.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Hold off on reviewing this PR for a bit, there is a failure I want to investigate first.

**Comment by yuzefovich** [comment]
Alright, I think this is finally ready for a look. @rharding6373 @rytaft

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75127)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373 and @rytaft)

___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 1324 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/75127#-MuDueRw0Hpq6b9YlkG7:-MuDueRw0Hpq6b9YlkG8:b-8upqnp) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7a3524edfe3a7d4eb48902eda57ae42b784227e/pkg/kv/kvclient/kvstreamer/streamer.go#L1324)):*
> ```Go
> // getResponseSize calculates the size of the GetResponse similar to how it is
> // accounted for TargetBytes parameter by the KV layer.
> // TODO(yuzefovich): check with Erik that this is, indeed, similar.
> ```

@erikgrinaker could you please take a look at a couple of new functions here? I want to make sure that we're accounting for the results' memory footprint in the same manner as we're counting them against `TargetBytes` limit.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75127)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373, @rytaft, and @yuzefovich)

___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 1324 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/75127#-MuDueRw0Hpq6b9YlkG7:-MuFb5HlACdxUk81jINp:bfrw06w) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7a3524edfe3a7d4eb48902eda57ae42b784227e/pkg/kv/kvclient/kvstreamer/streamer.go#L1324)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

@erikgrinaker could you please take a look at a couple of new functions here? I want to make sure that we're accounting for the results' memory footprint in the same manner as we're counting them against `TargetBytes` limit.
</blockquote></details>

I don't think `scanResponseSize()` is accurate in the `Rows` case. The server appears to retain the original size calculation from the binary representation before decoding the KVs into the response:

https://github.com/cockroachdb/cockroach/blob/6a7678c19d142b8ed6a7ba3c222d3e18aab66c78/pkg/storage/mvcc.go#L2394

https://github.com/cockroachdb/cockroach/blob/6a7678c19d142b8ed6a7ba3c222d3e18aab66c78/pkg/storage/mvcc.go#L2421-L2438

I believe the correct calculation is `8 + len(row.Key) + len(row.Value.RawBytes)`:

https://github.com/cockroachdb/cockroach/blob/6a7678c19d142b8ed6a7ba3c222d3e18aab66c78/pkg/storage/pebble_mvcc_scanner.go#L142

However, why not simply use the `NumBytes` field of the response, which already contains the correct size as calculated by the server? I think doing the calculation on the client side seems a bit brittle and too tightly coupled with server-side implementation details.

**Review by rytaft — COMMENTED** [review]
Nice fixes!

> Reviewed 5 of 5 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, 3 of 3 files at r10, 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75127#-:-MuGq-iK45vmOXN5ZF5e:b-5k0d9g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373 and @yuzefovich)

___
*[-- commits, line 46 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/75127#-MuGeU8B4okkz431TFDd):*
nit: preemptied -> preempted (here and below)
___
*[-- commits, line 75 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/75127#-MuGgy-KD2PU8ZdDJjgO):*
nit: preemptied -> preempted
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 539 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/75127#-MuGdENR5I-zMcWpBNKv:-MuGdENR5I-zMcWpBNKw:bsb5qtf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d758761363b38b43e14e70baed0a12671e3b152a/pkg/kv/kvclient/kvstreamer/streamer.go#L539)):*
> ```Go
> 
> 	// Memory reservation was approved, so the requests are good to go.
> 	s.mu.requestsToServe = requestsToServe
> ```

is it possible that you're overwriting existing requests here? Should this be appended instead?
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 261 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/75127#-MuGevjS-CiL401S9bZO:-MuGevjS-CiL401S9bZP:b-8ozs9a) ([raw file](https://github.com/cockroachdb/cockroach/blob/af18398497d87b1ee15c62ad4d113e0cd1d18908/pkg/kv/kvclient/kvstreamer/streamer.go#L261)):*
> ```Go
> 		// been returned by GetResults() yet.
> 		results []Result
> 		// err is set once the Streamer cannot make progress any more and will
> ```

nit: add a blank line to be consistent
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 709 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/75127#-MuGgEuX7TfrgL3Bo97D:-MuGgEuX7TfrgL3Bo97E:brrbt7z) ([raw file](https://github.com/cockroachdb/cockroach/blob/af18398497d87b1ee15c62ad4d113e0cd1d18908/pkg/kv/kvclient/kvstreamer/streamer.go#L709)):*
> ```Go
> 		// not releasing it in order to not miss the signal on hasWork condition
> 		// variable.
> 		w.s.mu.Lock()
> ```

consider putting this whole locked section into a subroutine so you can use `defer w.s.mu.Unlock()`
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 730 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/75127#-MuGfw7F3gZWHdf-JXFK:-MuGfw7GAxuJIvnbW9lz:b8bcjxb) ([raw file](https://github.com/cockroachdb/cockroach/blob/af18398497d87b1ee15c62ad4d113e0cd1d18908/pkg/kv/kvclient/kvstreamer/streamer.go#L730)):*
> ```Go
> 			}
> 			continue
> 		} else {
> ```

nit: you shouldn't need the else
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 1011 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/75127#-MuGnt0OB2pvuUd1P-q2:-MuGnt0OB2pvuUd1P-q3:b5iyd64) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23044a4cb8d8c8cdfc7124e035e34427976b74a/pkg/kv/kvclient/kvstreamer/streamer.go#L1011)):*
> ```Go
> 			}
> 
> 			// First, we have to reconcile the memory budget. We do it
> ```

Consider creating separate functions for each of these things to make the code easier to follow
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 1063 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/75127#-MuGmqf25mSUBpfXtIjR:-MuGmqf25mSUBpfXtIjS:b-6djuwt) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23044a4cb8d8c8cdfc7124e035e34427976b74a/pkg/kv/kvclient/kvstreamer/streamer.go#L1063)):*
> ```Go
> 			}
> 			numIncompleteRequests := numIncompleteGets + numIncompleteScans
> 			if resumeReqsMemUsage > 0 {
> ```

you shouldn't really need to check this, right? `numIncompleteRequests` will be 0 anyway.
___
*[pkg/sql/mem_limit_test.go, line 173 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/75127#-MuGkmWV1m5X_n6Njcpz:-MuGkmWV1m5X_n6Njcq-:b-me5dgc) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e5e06a45adafd953f06b47683f17baa4b8a7068/pkg/sql/mem_limit_test.go#L173)):*
> ```Go
> 	require.NoError(t, err)
> 
> 	// Set the workmem limit to a low value such it will allow the Streamer to
> ```

nit: such it -> such that it

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75127)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @rharding6373, and @rytaft)

___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 1324 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/75127#-MuDueRw0Hpq6b9YlkG7:-MuIAsti1yx1-S4FMXEn:b-hx5cce) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7a3524edfe3a7d4eb48902eda57ae42b784227e/pkg/kv/kvclient/kvstreamer/streamer.go#L1324)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

I don't think `scanResponseSize()` is accurate in the `Rows` case. The server appears to retain the original size calculation from the binary representation before decoding the KVs into the response:

https://github.com/cockroachdb/cockroach/blob/6a7678c19d142b8ed6a7ba3c222d3e18aab66c78/pkg/storage/mvcc.go#L2394

https://github.com/cockroachdb/cockroach/blob/6a7678c19d142b8ed6a7ba3c222d3e18aab66c78/pkg/storage/mvcc.go#L2421-L2438

I believe the correct calculation is `8 + len(row.Key) + len(row.Value.RawBytes)`:

https://github.com/cockroachdb/cockroach/blob/6a7678c19d142b8ed6a7ba3c222d3e18aab66c78/pkg/storage/pebble_mvcc_scanner.go#L142

However, why not simply use the `NumBytes` field of the response, which already contains the correct size as calculated by the server? I think doing the calculation on the client side seems a bit brittle and too tightly coupled with server-side implementation details.
</blockquote></details>

Nice, I didn't know about `NumBytes`.
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 539 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/75127#-MuGdENR5I-zMcWpBNKv:-MuI1uEZ3ybyVX_5SYWy:b-d2we6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/d758761363b38b43e14e70baed0a12671e3b152a/pkg/kv/kvclient/kvstreamer/streamer.go#L539)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

is it possible that you're overwriting existing requests here? Should this be appended instead?
</blockquote></details>

No, that's currently not possible - we check above that all previous requests have already been responded to, and if that's not the case, we return an assertion failed error.
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 709 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/75127#-MuGgEuX7TfrgL3Bo97D:-MuI4cgQ1oHKVYIQ03Xq:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/af18398497d87b1ee15c62ad4d113e0cd1d18908/pkg/kv/kvclient/kvstreamer/streamer.go#L709)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

consider putting this whole locked section into a subroutine so you can use `defer w.s.mu.Unlock()`
</blockquote></details>

Good point, done.
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 730 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/75127#-MuGfw7F3gZWHdf-JXFK:-MuI4Tcr05r7VoVqGX9C:b-u3h61u) ([raw file](https://github.com/cockroachdb/cockroach/blob/af18398497d87b1ee15c62ad4d113e0cd1d18908/pkg/kv/kvclient/kvstreamer/streamer.go#L730)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: you shouldn't need the else
</blockquote></details>

The code has been refactored.



_Code quote:_
```Go
// getRequestsLocked returns all currently enqueued requests to be served. It
// assumes that the Streamer's mutex is being held.
//
// A boolean that indicates whether the coordinator should exit is returned.
func (w *workerCoordinator) getRequestsLocked() (
	requestsToServe []singleRangeBatch,
	avgResponseSize int64,
	shouldExit bool,
) {
	w.s.mu.AssertHeld()

	requestsToServe = w.s.mu.requestsToServe
	avgResponseSize = w.s.mu.avgResponseEstimator.getAvgResponseSize()
	shouldExit = w.s.mu.err != nil || w.s.mu.done
	return requestsToServe, avgResponseSize, shouldExit
}
```
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 1011 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/75127#-MuGnt0OB2pvuUd1P-q2:-MuIAQ3CD1Sgh-eOEsd1:b7h7zw5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23044a4cb8d8c8cdfc7124e035e34427976b74a/pkg/kv/kvclient/kvstreamer/streamer.go#L1011)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Consider creating separate functions for each of these things to make the code easier to follow
</blockquote></details>

Extracted into separate functions.
___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 1063 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/75127#-MuGmqf25mSUBpfXtIjR:-MuI5i_bCMLIKrXC9kmr:bcs71sx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a23044a4cb8d8c8cdfc7124e035e34427976b74a/pkg/kv/kvclient/kvstreamer/streamer.go#L1063)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

you shouldn't really need to check this, right? `numIncompleteRequests` will be 0 anyway.
</blockquote></details>

Yes, good point. This was a remnant of the code where we were reusing `reqs.req` slice.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r12, 1 of 3 files at r15, 4 of 4 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75127#-:-MuNGNr3ERihD4_UpY0B:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @erikgrinaker, @rharding6373, and @yuzefovich)

___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 1193 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/75127#-MuNFSkEAbjwSEQqCOBS:-MuNFSkEAbjwSEQqCOBT:bp8e1cc) ([raw file](https://github.com/cockroachdb/cockroach/blob/36da734bf7d86b7c16348728b785f12f1b5f932e/pkg/kv/kvclient/kvstreamer/streamer.go#L1193)):*
> ```Go
> // It also assumes that the budget has already been reconciled with the
> // reservations for Results that will be created. The calculation of the memory
> // footprint must be the same as in calculateFootprint.
> ```

Can you expand on this last sentence a bit? There seem to be some differences and it's not totally obvious to me what's going on with the memory footprint calculation. (e.g., `memoryFootprintBytes` is an input param here, whereas it's an output param above).

**Review by yuzefovich — COMMENTED** [review]
TFTR!

@rytaft do I also have your approval on the first two commits (that are from #75078)? I think there I addressed the comments from Rachael and Raphael, but don't have an LGTM yet.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75127#-:-MuNO7eM0dHHDwvi3o7v:b41q6sh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @erikgrinaker, @rharding6373, and @rytaft)

___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 1193 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/75127#-MuNFSkEAbjwSEQqCOBS:-MuNOP_E17gubwZl1xDk:b5vdakv) ([raw file](https://github.com/cockroachdb/cockroach/blob/36da734bf7d86b7c16348728b785f12f1b5f932e/pkg/kv/kvclient/kvstreamer/streamer.go#L1193)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Can you expand on this last sentence a bit? There seem to be some differences and it's not totally obvious to me what's going on with the memory footprint calculation. (e.g., `memoryFootprintBytes` is an input param here, whereas it's an output param above).
</blockquote></details>

I added some more words, please let me know if it's better.

Think of it this way:
- in `calculateFootprint` we estimate the memory footprint
- but then in `processSingleRangeResults` we need to make sure to create `memoryTok`s such that all of them together add up to the same footprint as estimated in `calculateFootprint`. If two quantities don't match, then we'll have a drift in the memory budget, so we have to use the same approach for calculating the footprint in both methods.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75127)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @erikgrinaker, @rharding6373, and @rytaft)

___
*[pkg/kv/kvclient/kvstreamer/streamer.go, line 1193 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/75127#-MuNFSkEAbjwSEQqCOBS:-MuNRWyI-0M9ojHFhzyZ:ber84k4) ([raw file](https://github.com/cockroachdb/cockroach/blob/36da734bf7d86b7c16348728b785f12f1b5f932e/pkg/kv/kvclient/kvstreamer/streamer.go#L1193)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I added some more words, please let me know if it's better.

Think of it this way:
- in `calculateFootprint` we estimate the memory footprint
- but then in `processSingleRangeResults` we need to make sure to create `memoryTok`s such that all of them together add up to the same footprint as estimated in `calculateFootprint`. If two quantities don't match, then we'll have a drift in the memory budget, so we have to use the same approach for calculating the footprint in both methods.
</blockquote></details>

I decided to remove the commentary and, instead, added the explicit calculation in the second loop and an assertion that both quantities match.

**Review by rytaft — APPROVED** [review]
Yea, I reviewed the whole thing

> Reviewed 1 of 5 files at r17, 1 of 3 files at r20, 4 of 4 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75127#-:-MuNSav53XJnlGm8NZwr:b-wu2al4)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @erikgrinaker and @rharding6373)

**Review by yuzefovich — COMMENTED** [review]
Thanks!

Force-pushed to appease the CLA check.

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75127#-:-MuNTswgBl7lkOqC2I1-:b-n9jldi)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rharding6373)

**Pull request merged**
