### PR TITLE
sql: create a couple of new packages

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit creates two new packages sql/distsql and sql/execplan.
All the code used by both distsqlrun and newly created execplan is
extracted from distsqlrun into distsql. execplan contains most of
the logic needed to plan the vectorized flow.

Notable changes:
- several things that are moved into distsql needed to be made public
  so that distsqlrun and execplan could access them
- RowBuffer that was intended to be used only in tests, now lives in
  a test file so is only accessible from the tests
- a few of the processors that live in the newly created packages are
  now made public
- in some cases, tests live in a different package from the respective
  logic
- distsqlrun/stats have been split up into two files because of the
  couple processors that now live in distsql.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
I know this is a huge PR that will require significant time to review, but I believe we should merge it for 19.2, and the sooner I'll get feedback, the less painful will be rebasing on top the recent changes since this PR touches so many files, so this is a friendly ping :)

Possibly, I should provide more background why do this change at all. The main driver (from my perspective) is that it should enable us write unit tests for the vectorized engine that relies on the code that lives in sql/distsqlrun. Additionally, it seems like a good idea to attempt to separate the vectorized stuff in sql/distsqlrun from the DistSQL stuff.

**Comment by jordanlewis** [comment]
I think this is a good initiative and I'd like to bias toward merging something like it without bikeshedding too hard. I agree that the dependencies here have been making it hard to test things - important to resolve that problem.

The pattern that the optimizer established was to make a `builder` package within the package that is being "built", not side by side. I think we should follow this pattern. That means I think you should move `execplanner` inside of `exec`.

I like `distsql`. Maybe `distsqlrun` is really more like `distsql/processors/` or something but we don't have to do that now.

@RaduBerinde can you give a high level opinion?

**Comment by RaduBerinde** [comment]
What is the benefit of merging this in 19.2 (rather than putting it on master after the fork)? Do we plan to write the unit tests it enables in the 19.2 timeframe?

It is pretty hard to get the gist of things from the PR. Could you show a simple diagram of the dependencies between the relevant packages? I think `distsqlpb`, `distsqlrun` and `distsqlplan` should be moved inside `distsql`, but we don't have to do that at the same time.

**Comment by jordanlewis** [comment]
> What is the benefit of merging this in 19.2 (rather than putting it on master after the fork)? Do we plan to write the unit tests it enables in the 19.2 timeframe?

Since this isn't a destabilizing change as a pure refactor, the benefit is simply that backports will be made easier.

**Comment by RaduBerinde** [comment]
In that case if we agree other things should be moved/renamed as well (moving packages inside `distsql`) we should try to do them at the same time.

**Comment by yuzefovich** [comment]
Here is the current state of things in this PR:
```
sql/
    distsql/ {some distsql infra, several processors that are planned by both Row and Vec execution}
    distsqlplan/ {this hasn't changed much, some things used only by Row planning}
    distsqlrun/ {most of distsql infra, almost all of the processors, the final step of Vec planning}
    exec/ {all of the Vec execution logic}
    execplan/ {most of the Vec planning}
```
I can't say that I love this setup. To arrive into this state, I wanted to extract `execplan` out of `distsqlrun`, and then just did whatever was needed for build to succeed.

I think I like Alfonso's suggestion, what do you guys @jordanlewis @RaduBerinde think about that? I imagine the setup would be as:
```
sql/
    colexec/ {all of the Vec execution logic (simply renaming of exec package)}
    colplan/ {all of the Vec planning (what I have in execplan at the moment plus the final step of Vec planning that is in distsqlrun right now}
    execinfra/ {all distsql infra, several processors that are planned by both Row and Vec execution (what I have in distsql as well as the infra in distsqlrun)}
    rowplan/ {things used only by Row planning (simply renaming of distsqlplan package)}
    rowexec/ {almost all of the processors (whatever is left of distsqlrun, ideally should not be processors that are used only by Row execution)}
```

**Comment by RaduBerinde** [comment]
I like the `row / col` renaming. We will still have `distsqlpb` though, would that become `execinfrapb` or `execinfra/execinfrapb`?

**Comment by yuzefovich** [comment]
Hm, I guess we could do either. I'd lean towards moving it inside, so `sql/distsqlpb` -> `sql/execinfra/execinfrapb` if that'll work (or maybe just `sql/execinfra/pb`).

**Comment by RaduBerinde** [comment]
`sql/execinfra/execinfrapb` works. `sql/execinfra/pb` not so much because it's too generic in code (`pb.X`).

**Comment by yuzefovich** [comment]
Sounds good, so I'll proceed with the following scheme then:
```
sql/
    colexec/ {all of the Vec execution logic (simply renaming of exec package)}
    colplan/ {all of the Vec planning (what I have in execplan at the moment plus the final step of Vec planning that is in distsqlrun right now}
    execinfra/ {all distsql infra, several processors that are planned by both Row and Vec execution (what I have in distsql as well as the infra in distsqlrun)}
    execinfra/execinfrapb {simply renaming of distsqlpb package}
    rowexec/ {almost all of the processors (whatever is left of distsqlrun, ideally should not be processors that are used only by Row execution)}
    rowplan/ {things used only by Row planning (simply renaming of distsqlplan package)}
```

**Comment by jordanlewis** [comment]
Great! Once this gets merged please plan to send out an email explaining the package migration to eng@.

**Comment by yuzefovich** [comment]
For the moment, this PR will be WIP. Please ignore the changes for now.

**Pull request closed without merging**
