### PR TITLE
sql: SHOW CREATE now uses two-part names for composite types

### LINKED ISSUE #125934: `SHOW CREATE` doesn't properly identify composite types
**Describe the problem**

When you use `SHOW CREATE` to see DDL statements, it doesn't properly identify the composite type. It only displays the composite type by its name, leaving out the schema name. If the same composite type name is defined in another schema, the DDL that is generated isn't valid.

**To Reproduce**

```
demo@127.0.0.1:26257/demoapp/movr> create schema s1;
CREATE SCHEMA

Time: 17ms total (execution 12ms / network 5ms)

demo@127.0.0.1:26257/demoapp/movr> create schema s2;
CREATE SCHEMA

Time: 19ms total (execution 12ms / network 6ms)

demo@127.0.0.1:26257/demoapp/movr> create type s1.comp1 as (c1 bigint);
CREATE TYPE

Time: 7ms total (execution 7ms / network 0ms)

demo@127.0.0.1:26257/demoapp/movr> create type s2.comp2 as (c1 string);
CREATE TYPE

Time: 6ms total (execution 5ms / network 0ms)

demo@127.0.0.1:26257/demoapp/movr> create table public.use_comps(c1 s1.comp1, c2 s2.comp2);
CREATE TABLE

Time: 50ms total (execution 47ms / network 2ms)

demo@127.0.0.1:26257/demoapp/movr> show create table use_comps;
  table_name |                      create_statement
-------------+--------------------------------------------------------------
  use_comps  | CREATE TABLE public.use_comps (
             |     c1 COMP1 NULL,
             |     c2 COMP2 NULL,
             |     rowid INT8 NOT VISIBLE NOT NULL DEFAULT unique_rowid(),
             |     CONSTRAINT use_comps_pkey PRIMARY KEY (rowid ASC)
             | )
(1 row)

Time: 14ms total (execution 14ms / network 0ms)
```

Notice that in the `SHOW CREATE` output, c1 and c2 both refer to the same type in the wrong schema.

**Expected behavior**
The output for the `SHOW CREATE` command should include the schema name in the composite types. This would be similar to the postgres behaviour through `pg_dump`.

For example, it should look like:
```
demo@127.0.0.1:26257/demoapp/movr> show create table use_comps;
  table_name |                      create_statement
-------------+--------------------------------------------------------------
  use_comps  | CREATE TABLE public.use_comps (
             |     c1 s1.COMP1 NULL,
             |     c2 s2.COMP2 NULL,
             |     rowid INT8 NOT VISIBLE NOT NULL DEFAULT unique_rowid(),
             |     CONSTRAINT use_comps_pkey PRIMARY KEY (rowid ASC)
             | )
(1 row)
```

**Environment:**
 - CockroachDB version: CockroachDB CCL v24.2.0-alpha.00000000-dev (darwin arm64, built , go1.22.3 X:nocoverageredesign
 - Server OS: macOS
 - Client app `cockroach sql`

Jira issue: CRDB-39672

### PR DESCRIPTION
**Pull request by spilchen**
This change formats composite types as two- or three-part names, depending on the context, in places that output the name, such as SHOW CREATE TABLES. Previously, composite types were only displayed with a one-part name, which could cause ambiguity, especially if a table had two types with the same name but in different schemas. The new rules for formatting composite types are the same as those implemented for enum types.

Closes: #125934
Release note (bug fix): Fixed a bug related to displaying the names of composite types in the SHOW CREATE TABLES command. The names are now shown as two-part names, which disambiguates the output and makes it more portable to other databases.

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
nice fix! i'll add the 24.2 backport label, since we are still in alphas for 24.2

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127158#-:-O1rID-e3H2Qt-1EdoMx:bb5qmml)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @spilchen)

**Review by Dedej-Bergin — APPROVED** [review]
:lgtm:

Thanks Matt!

I added some notes/comments as a recap of the question/answers from our review call to keep other observers in the loop.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/127158#-:-O1rLQu39F5Z69VpojSv:b-1k1ncd)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @spilchen)

___
*[`pkg/sql/types/types.go` line 2029 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127158#-O1rK6rGBAiW6uRMjjuy:-O1rK6rGBAiW6uRMjjuz:b-poa80a) ([raw file](https://github.com/cockroachdb/cockroach/blob/8649ed9ab6434f72e63401b0181f0861037d8ee5/pkg/sql/types/types.go#L2029)):*
> ```Go
> 		return t.TypeMeta.Name.FQName(false /* explicitCatalog */)
> 	case TupleFamily:
> 		if t.UserDefined() {
> ```

Recap from our review call to keep other observers in the loop.

I asked about the TupleFamily, was informed that it was pre-existing in t.Family() and this case catches all composite types. 

We have the if statement for the user defined types, where it returns the name similar to case EnumFamily, where as non-user defined composite type should just be turned to upper through the same String.ToUpper that we had before.  
   
___
*[`pkg/sql/logictest/testdata/logic_test/show_create` line 220 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127158#-O1rJSrAEWXjIue1CqYV:-O1rJSrAEWXjIue1CqYW:b-3l1635) ([raw file](https://github.com/cockroachdb/cockroach/blob/8649ed9ab6434f72e63401b0181f0861037d8ee5/pkg/sql/logictest/testdata/logic_test/show_create#L220)):*
> ```
> 
> query T
> SELECT create_statement FROM [SHOW CREATE TABLE T_WITH_COMPS];
> ```

Recap from our review call to keep other observers in the loop.

I asked how this test worked and was informed that before we would see sc1 comp1 NULL, sc2 comp1 NULL which is incorrect.
___
*[`pkg/sql/logictest/testdata/logic_test/tuple` line 1005 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/127158#-O1rL2mj58FkoO7LvM4u:-O1rL2mj58FkoO7LvM4v:b-tkn1ql) ([raw file](https://github.com/cockroachdb/cockroach/blob/8649ed9ab6434f72e63401b0181f0861037d8ee5/pkg/sql/logictest/testdata/logic_test/tuple#L1005)):*
> ```
> 
> # Adding a cast here should still work too.
> statement error incompatible COALESCE expressions: expected \(SELECT \(1,\)\)::t to be of type tuple, found type tuple{int AS x}
> ```

Recap from our review call to keep other observers in the loop.

I asked about the lower casing, and was informed that we’re not doing the string.ToUpper anymore.

**Comment by spilchen** [comment]
tftr!

bors r+

**Comment by spilchen** [comment]
bors retry

**Comment by spilchen** [comment]
blathers backport 24.2

**Pull request merged**
