### PR TITLE
github-pull-request-make: avoid confusion when pkgs are moved

### PR DESCRIPTION
**Pull request by tbg**
The CI stress runner would get confused when packages were renamed or
removed in a PR and would try to run tests on nonexistent packages,
which would then fail. This was because it was using the "Patch" format, which
gives the patch for each individual push. By switching to the "diff"
format, we get a single diff for the whole PR, which still can trip
but at least is immune to such churn within a PR.

Also added a helper that makes it easier to generate new test cases.

Release note: None

### CODE REVIEW

**Review by benesch — CHANGES_REQUESTED** [review]
Thanks for taking this on! To be honest I'm not sure how much the test case adds considering the test-case generator uses a different code path than the thing it's testing, but ¯\_(ツ)_/¯ .

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27879#-:-LIBhLFO5jYoPas9h06_:b7ryocn)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/github-pull-request-make/main.go, line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27879#-LIBhICxE7ZlgSZSasud:-LIBhICxE7ZlgSZSasue:bgvxoqf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e1351da94445f8403308dff2c5425b10774152e/pkg/cmd/github-pull-request-make/main.go#L202)):*
> ```Go
> 		repo,
> 		*currentPull.Number,
> 		github.RawOptions{Type: github.Patch},
> ```

I think you forgot to change this. :grinning:

**Review by tbg — COMMENTED** [review]
Ha, definitely pushed this way too hastily, thanks for catching that! Updated now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27879#-:-LIFw_sN3AjztjCm461C:b-5iocvf)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/github-pull-request-make/main.go, line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27879#-LIBhICxE7ZlgSZSasud:-LIFwWQ809BKqRF2XHMs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e1351da94445f8403308dff2c5425b10774152e/pkg/cmd/github-pull-request-make/main.go#L202)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I think you forgot to change this. :grinning: 
</blockquote></details>

Done.

**Comment by tschottdorf** [comment]
@tamird, do you have opinions on this change?

**Review by tamird — DISMISSED** [review]
Looks good to me.

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27879#-:-LIG7iH-D7WdrFYBoBeD:b9j9n43)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/github-pull-request-make/main.go, line 165 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27879#-LIG6rjoA7GU3gzALaI0:-LIG6rjoA7GU3gzALaI1:b-f9bn3q) ([raw file](https://github.com/cockroachdb/cockroach/blob/304eed5dc3be35d04a9c9bab8f0cc6191daeecf7/pkg/cmd/github-pull-request-make/main.go#L165)):*
> ```Go
> 		log.Printf("GitHub API token environment variable %s is not set", githubAPITokenEnv)
> 	}
> 	client := github.NewClient(httpClient)
> ```

Directly return?
___
*[pkg/cmd/github-pull-request-make/main_test.go, line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27879#-LIG7X9_1d_zX9ngE9nc:-LIG7X9_1d_zX9ngE9nd:b-x2evwj) ([raw file](https://github.com/cockroachdb/cockroach/blob/86d0a7fa5611af12592f1340345db34034830375/pkg/cmd/github-pull-request-make/main_test.go#L27)):*
> ```Go
> 	for filename, expPkgs := range map[string]map[string]pkg{
> 		"testdata/10305.diff": {
> 			filepath.Join("pkg", "roachpb"): {tests: []string{"TestLeaseVerify"}},
> ```

Not your doing, but using `filepath` here is wrong :(

**Comment by tschottdorf** [comment]
@benesch no rush, but ball is in your court.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27879)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/github-pull-request-make/main.go, line 165 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27879#-LIG6rjoA7GU3gzALaI0:-LIHv1u402hMLPMc17yf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/304eed5dc3be35d04a9c9bab8f0cc6191daeecf7/pkg/cmd/github-pull-request-make/main.go#L165)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Directly return?
</blockquote></details>

Done.
___
*[pkg/cmd/github-pull-request-make/main_test.go, line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27879#-LIG7X9_1d_zX9ngE9nc:-LIHv2TW0zDBPpvvB4Vs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/86d0a7fa5611af12592f1340345db34034830375/pkg/cmd/github-pull-request-make/main_test.go#L27)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Not your doing, but using `filepath` here is wrong :(
</blockquote></details>

Done.

**Review by benesch — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27879#-:-LIHx-Dy-PEYjMBfeXIy:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by tschottdorf** [comment]
bors r=benesch,tamird

**Comment by benesch** [comment]
bors r=benesch,tamird

**Review by tamird — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27879#-:-LII80I7EHphTAanV7wq:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
