### PR TITLE
raft: do not grant {,Pre}Vote when supporting fortified leader

### LINKED ISSUE #125351: raft: respect leader fortification during elections
**Describe the problem**

Part of https://github.com/cockroachdb/cockroach/issues/123847

Followers that have promised fortification support to a leader should not call elections until the promised support has expired.

Jira issue: CRDB-39402

Epic CRDB-37522

### PR DESCRIPTION
**Pull request by arulajmani**
Raft peers that have promised fortification support to the leader and still support the leader in StoreLiveness should not grant votes or pre-votes to peers calling elections.

Closes https://github.com/cockroachdb/cockroach/issues/125351

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129697)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/raft/raft.go` line 1178 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129697#-O5JE_OQC8dJm76yd8Fk:-O5JE_OQC8dJm76yd8Fl:b2uj1lt) ([raw file](https://github.com/cockroachdb/cockroach/blob/834fbe347f4d758b704b0509c542b27f5b9bb8d9/pkg/raft/raft.go#L1178)):*
> ```Go
> 		if m.Type == pb.MsgVote || m.Type == pb.MsgPreVote {
> 			force := bytes.Equal(m.Context, []byte(campaignTransfer))
> 			inLease := r.checkQuorum && r.lead != None && r.electionElapsed < r.electionTimeout
> ```

At some point, we're going to want to get rid of the `checkQuorum` option, because leader fortification assumes that it's set to true.
___
*[`pkg/raft/raft.go` line 1178 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129697#-O5JFAnBEoXVBbx1QmpH:-O5JFAnBEoXVBbx1QmpI:bf87c0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/834fbe347f4d758b704b0509c542b27f5b9bb8d9/pkg/raft/raft.go#L1178)):*
> ```Go
> 		if m.Type == pb.MsgVote || m.Type == pb.MsgPreVote {
> 			force := bytes.Equal(m.Context, []byte(campaignTransfer))
> 			inLease := r.checkQuorum && r.lead != None && r.electionElapsed < r.electionTimeout
> ```

Should we name this something like `inHeartbeatLease` to contrast it with `inFortifyLease`?
___
*[`pkg/raft/raft.go` line 1179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129697#-O5JELJU25SXVrzm3IQe:-O5JELJU25SXVrzm3IQf:bizu3nr) ([raw file](https://github.com/cockroachdb/cockroach/blob/834fbe347f4d758b704b0509c542b27f5b9bb8d9/pkg/raft/raft.go#L1179)):*
> ```Go
> 			force := bytes.Equal(m.Context, []byte(campaignTransfer))
> 			inLease := r.checkQuorum && r.lead != None && r.electionElapsed < r.electionTimeout
> 			inFortifyLease := r.supportingFortifiedLeader()
> ```

We do want to allow the vote if it comes from the currently supported leader. Otherwise, a leader would get stuck if it ever decided that it needed to advance its term.

That should probably also apply to the previous condition, but it's less serious there, because once the leader steps down, it will stop heartbeating at the raft level, but it will continue heartbeating at the store liveness level.
___
*[`pkg/raft/raft.go` line 1189 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129697#-O5JFCIoBqrNIVqjoZMQ:-O5JFCIoBqrNIVqjoZMR:b-tft3m8) ([raw file](https://github.com/cockroachdb/cockroach/blob/834fbe347f4d758b704b0509c542b27f5b9bb8d9/pkg/raft/raft.go#L1189)):*
> ```Go
> 					// Log why we're ignoring the Request{,Pre}Vote.
> 					var inFortifyLeaseMsg string
> 					var inLeaseMsg string
> ```

nit: pull this up above `var inFortifyLeaseMsg string`, since it's first everywhere else.
___
*[`pkg/raft/raft.go` line 1192 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129697#-O5JFhA9BHnTuLINdcDQ:-O5JFhA9BHnTuLINdcDR:b-aio1v0) ([raw file](https://github.com/cockroachdb/cockroach/blob/834fbe347f4d758b704b0509c542b27f5b9bb8d9/pkg/raft/raft.go#L1192)):*
> ```Go
> 					var sep string
> 					if inLease {
> 						inLeaseMsg = fmt.Sprintf("lease is not expired (remaining ticks: %d)", r.electionTimeout-r.electionElapsed)
> ```

Feel free to change this message to something like "recently received heartbeat messages (remaining ticks: %d)" (maybe in an initial commit). The concept of a "lease" never really existed at this level, despite etcd/raft mentioning it in this one place.
___
*[`pkg/raft/raft.go` line 1206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129697#-O5JFao4-kLNir6aGIhL:-O5JFao57iaaSbXXoTXY:bct5wj9) ([raw file](https://github.com/cockroachdb/cockroach/blob/834fbe347f4d758b704b0509c542b27f5b9bb8d9/pkg/raft/raft.go#L1206)):*
> ```Go
> 						r.id, last.term, last.index, r.Vote, m.Type, m.From, m.LogTerm, m.Index, r.Term, inLeaseMsg, sep, inFortifyLeaseMsg)
> 				}
> 				return nil // don't update term/grant vote; early return
> ```

Thanks for this comment. I've missed the early return on multiple occasions and gotten confused about how this works.
___
*[`pkg/raft/testdata/fortification_followers_dont_vote_prevote.txt` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129697#-O5JGjHt-hPEtZzwE0p8:-O5JGjHt-hPEtZzwE0p9:b-oa273) ([raw file](https://github.com/cockroachdb/cockroach/blob/834fbe347f4d758b704b0509c542b27f5b9bb8d9/pkg/raft/testdata/fortification_followers_dont_vote_prevote.txt#L1)):*
> ```help
> # Test to ensure that a follower will not vote for another peer
> ```

nit: should we just call this `fortification_followers_dont_prevote.txt`?

**Review by arulajmani — COMMENTED** [review]
TFTR, RFAL!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129697#-:-O5KlL-h4AFQbWFxSvjz:b-qrbqp3)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/raft/raft.go` line 1178 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129697#-O5JE_OQC8dJm76yd8Fk:-O5KMXE9CNDzpkKxMeLu:bwxpfwx) ([raw file](https://github.com/cockroachdb/cockroach/blob/834fbe347f4d758b704b0509c542b27f5b9bb8d9/pkg/raft/raft.go#L1178)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

At some point, we're going to want to get rid of the `checkQuorum` option, because leader fortification assumes that it's set to true.
</blockquote></details>

Agreed. I had the same thought here as well. I'll file an issue.
___
*[`pkg/raft/raft.go` line 1178 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129697#-O5JFAnBEoXVBbx1QmpH:-O5KMvvW5wzFg2vjR6ra:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/834fbe347f4d758b704b0509c542b27f5b9bb8d9/pkg/raft/raft.go#L1178)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we name this something like `inHeartbeatLease` to contrast it with `inFortifyLease`?
</blockquote></details>

Done.
___
*[`pkg/raft/raft.go` line 1179 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129697#-O5JELJU25SXVrzm3IQe:-O5KjNMm6VrRLVCpQV5_:bb6uoju) ([raw file](https://github.com/cockroachdb/cockroach/blob/834fbe347f4d758b704b0509c542b27f5b9bb8d9/pkg/raft/raft.go#L1179)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We do want to allow the vote if it comes from the currently supported leader. Otherwise, a leader would get stuck if it ever decided that it needed to advance its term.

That should probably also apply to the previous condition, but it's less serious there, because once the leader steps down, it will stop heartbeating at the raft level, but it will continue heartbeating at the store liveness level.
</blockquote></details>

Good point. We didn't have this in the prototype, but I remember we spoke about this a few weeks ago. I made the change (and a few other changes needed to make sure the leader is able to bump its term after stepping down). 

There's a test case too to demonstrate this now.
___
*[`pkg/raft/raft.go` line 1192 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129697#-O5JFhA9BHnTuLINdcDQ:-O5KlJvv6TAWapiVpGcD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/834fbe347f4d758b704b0509c542b27f5b9bb8d9/pkg/raft/raft.go#L1192)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Feel free to change this message to something like "recently received heartbeat messages (remaining ticks: %d)" (maybe in an initial commit). The concept of a "lease" never really existed at this level, despite etcd/raft mentioning it in this one place.
</blockquote></details>

Done.
___
*[`pkg/raft/raft.go` line 1206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129697#-O5JFao4-kLNir6aGIhL:-O5KbDUA2qmdXFOl9JdU:bmi8ppe) ([raw file](https://github.com/cockroachdb/cockroach/blob/834fbe347f4d758b704b0509c542b27f5b9bb8d9/pkg/raft/raft.go#L1206)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Thanks for this comment. I've missed the early return on multiple occasions and gotten confused about how this works.
</blockquote></details>

:100: 
___
*[`pkg/raft/testdata/fortification_followers_dont_vote_prevote.txt` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129697#-O5JGjHt-hPEtZzwE0p8:-O5Kjb-A4xwsO8ynTXUG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/834fbe347f4d758b704b0509c542b27f5b9bb8d9/pkg/raft/testdata/fortification_followers_dont_vote_prevote.txt#L1)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: should we just call this `fortification_followers_dont_prevote.txt`?
</blockquote></details>

Done.

**Review by nvb — APPROVED** [review]
:lgtm: nice testing throughout!

> Reviewed 10 of 10 files at r2, 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129697#-:-O5LvSKB8koCYmA1R_r7:b5foxdg)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/raft/raft.go` line 983 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129697#-O5LukBRBeA_td-x-pWP:-O5LukBS3fCJxQwjL_rj:b-989o5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b8ae315ae3a10c6add47ee4f44142609fb08c5f/pkg/raft/raft.go#L983)):*
> ```Go
> 	}
> 	assertTrue(!r.supportingFortifiedLeader() || r.lead == r.id,
> 		"shouldn't be supporting a fortified leader when becoming pre-candidate; leader exempted",
> ```

nit: we're using "should not" above, so maybe just keep that here as well.

**Review by arulajmani — COMMENTED** [review]
Thanks! (also for the quick review iterations)

bors r=nvanbenschoten

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129697#-:-O5ONCEI2MjUxc8bBUkZ:b-ovxqz9)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[`pkg/raft/raft.go` line 983 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129697#-O5LukBRBeA_td-x-pWP:-O5OMylUClOhnnXwc0aS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b8ae315ae3a10c6add47ee4f44142609fb08c5f/pkg/raft/raft.go#L983)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: we're using "should not" above, so maybe just keep that here as well.
</blockquote></details>

Done.

**Pull request merged**
