### PR TITLE
sql: fix apply joins when inner plans have subqueries

### LINKED ISSUE #39433: sql: internal error: invalid index
```
CREATE TABLE IF NOT EXISTS tab_orig AS
	SELECT
		g % 2 = 0 AS _bool
	FROM
		generate_series(0, 0) AS g;

SELECT
	(
		SELECT
			NULL
		FROM
			tab_orig
			LEFT JOIN tab_orig AS tab_57077
				RIGHT JOIN tab_orig AS tab_57078
					FULL JOIN tab_orig AS tab_57079 ON
							true ON tab_57069._bool
				CROSS JOIN tab_orig AS tab_57080
				INNER JOIN tab_orig AS tab_57081 ON true ON
					EXISTS(
						SELECT
							NULL
						FROM
							tab_orig AS tab_57082
							LEFT JOIN tab_orig ON
									EXISTS(
										SELECT
											NULL
										FROM
											tab_orig
											
									)
					)
	)
FROM
	tab_orig AS tab_57069;
```

```
pq: internal error: invalid index 3 for "EXISTS (SELECT NULL FROM tab_orig)"
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/sql/subquery.go:46: EvalSubquery()
github.com/cockroachdb/cockroach/pkg/sql/distsqlplan/expression.go:119: VisitPre()
github.com/cockroachdb/cockroach/pkg/sql/sem/tree/walk.go:667: WalkExpr()
github.com/cockroachdb/cockroach/pkg/sql/distsqlplan/expression.go:86: MakeExpression()
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:894: initTableReaderSpec()
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:1070: createTableReaders()
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2312: createPlanForNode()
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2197: createPlanForJoin()
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2324: createPlanForNode()
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2365: createPlanForNode()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:826: planAndRunSubquery()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:764: PlanAndRunSubqueries()
github.com/cockroachdb/cockroach/pkg/sql/apply_join.go:303: runRightSidePlan()
github.com/cockroachdb/cockroach/pkg/sql/apply_join.go:273: Next()
github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:171: Next()
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:171: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:793: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:581: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:333: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:942: PlanAndRun()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:910: execWithDistSQLEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:734: dispatchToExecutionEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:417: execStmtInOpenState()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:99: execStmt()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1211: execCmd()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1140: run()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:442: ServeConn()
github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:584: func1()
```

### PR DESCRIPTION
**Pull request by yuzefovich**
Previously, whenever the inner plan of an apply join was executed, it
would try to refer to the results of the subqueries of the outer plan
because the way we "connect" the subqueries with their results is a bit
fragile - by having an index into subquery plans slice that lives on the
`planner`. This could be incorrect when the "inner" plan has its own
subqueries.

In case when the "inner" plan is referring to the "inner" subqueries,
there are two bug-scenarios:
- if the "outer" plan also contains the subqueries, then the "inner"
plan could use the incorrect result, and the whole query silently would
return an incorrect result too;
- if the "outer" plan has no subqueries, then a panic (converted to an
internal error by the vectorized engine) would occur.

This commit partially mitigates the problem by detecting the scenario
when both "inner" and "outer" plans have subqueries (and returning an
unsupported error) and by updating the planner to point to the "inner"
subqueries when there are no "outer" subqueries.

Fixes: #39433.

Release note (bug fix): Correlated subqueries that couldn't be
decorrelated and that have their own subqueries are now executed
correctly when supported. Note that it is an edge case of an edge case,
so it's unlikely the users have hit this bug (it was found by the
randomized testing).

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66442)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/apply_join.go, line 272 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66442#-McAikZs5HazNrMxxgoe:-McAikZs5HazNrMxxgof:b-az8bml) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec913749c038d67b051a0c105512efee9d0e8896/pkg/sql/apply_join.go#L272)):*
> ```Go
> 	// plan, but it is possible that subqueries or the main query of the "inner"
> 	// plan refer to the results of subqueries from the "inner" plan. We have to
> 	// replace the subqueries manually in such scenario and restore the original
> ```

@raduberinde do you think it is possible for the "inner" plan to refer to the subqueries of the "outer" plan?

**Comment by yuzefovich** [comment]
At least it looks like the CI is green, so this commit doesn't seem to break known things.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66442)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/apply_join.go, line 272 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66442#-McAikZs5HazNrMxxgoe:-McAnuLx9z2yM3CJ3jdY:b-cjwrmn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec913749c038d67b051a0c105512efee9d0e8896/pkg/sql/apply_join.go#L272)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

@raduberinde do you think it is possible for the "inner" plan to refer to the subqueries of the "outer" plan?
</blockquote></details>

Yeah, I believe it can.. Feels like this change moves the problem around (and I'm not sure which version is "better", though given that not many users hit this issue it would be safer to leave it as is).

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66442)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/apply_join.go, line 272 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66442#-McAikZs5HazNrMxxgoe:-McAodWqAhCyHAH-Jjz_:b3zwz66) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec913749c038d67b051a0c105512efee9d0e8896/pkg/sql/apply_join.go#L272)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Yeah, I believe it can.. Feels like this change moves the problem around (and I'm not sure which version is "better", though given that not many users hit this issue it would be safer to leave it as is).
</blockquote></details>

It would be reasonable to handle the case where only one of the two "contexts" has subqueries. If they both do, we can error out with a more reasonable "unsupported" error since we're possibly going to mess up during execution (and it could in principle be a silent incorrect value, I think).

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66442)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/apply_join.go, line 272 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66442#-McAikZs5HazNrMxxgoe:-McApOpYCkFZfMHcu8Ne:b9py204) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec913749c038d67b051a0c105512efee9d0e8896/pkg/sql/apply_join.go#L272)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It would be reasonable to handle the case where only one of the two "contexts" has subqueries. If they both do, we can error out with a more reasonable "unsupported" error since we're possibly going to mess up during execution (and it could in principle be a silent incorrect value, I think).
</blockquote></details>

Yeah, I'm also concerned about currently using the result of the "outer" subquery when we're actually referring to the "inner" one. I like your suggestion of allowing only one of the contexts to have subqueries, I'll update the PR.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66442)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/apply_join.go, line 272 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66442#-McAikZs5HazNrMxxgoe:-McAsVrIAzsuKrSEAaVJ:b-rr168b) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec913749c038d67b051a0c105512efee9d0e8896/pkg/sql/apply_join.go#L272)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Yeah, I'm also concerned about currently using the result of the "outer" subquery when we're actually referring to the "inner" one. I like your suggestion of allowing only one of the contexts to have subqueries, I'll update the PR.
</blockquote></details>

Updated, PTAL.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66442#-:-McAwQLdAp59vG_nIDnP:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/apply_join.go, line 274 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66442#-McAwC2m8MSPXU30hU-O:-McAwC2m8MSPXU30hU-P:b-dyxrgn) ([raw file](https://github.com/cockroachdb/cockroach/blob/60ba09dd9e1c4a27f1fcf2cad13fe6cf06133420/pkg/sql/apply_join.go#L274)):*
> ```Go
> 		// propagating the results of the subqueries.
> 		if len(params.p.curPlan.subqueryPlans) != 0 {
> 			return errors.New(`apply joins with subqueries in the "inner" and "outer" contexts are not supported`)
> ```

[nit] Maybe `unimplemented.NewWithIssue`?

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66442#-:-McB0USN8zmjevMahRHb:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @yuzefovich)

___
*[pkg/sql/apply_join.go, line 274 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66442#-McAwC2m8MSPXU30hU-O:-McB-9LQCPjlM9ZMeqsG:b-kz1wm) ([raw file](https://github.com/cockroachdb/cockroach/blob/60ba09dd9e1c4a27f1fcf2cad13fe6cf06133420/pkg/sql/apply_join.go#L274)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] Maybe `unimplemented.NewWithIssue`?
</blockquote></details>

Good point, filed #66447 to track.

**Comment by rytaft** [comment]
Should this be backported?

**Comment by RaduBerinde** [comment]
I would backport, but I'd wait for a couple of days to see if sqlsmith finds some unexpected consequence.

**Pull request merged**
