### PR TITLE
sql/delegate: refactoring/cleaning up show_grants.go

### PR DESCRIPTION
**Pull request by Dedej-Bergin**
Mainly doing this as a golang and codebase learning exercise. I split up the 400 lines of code delegateShowGrants method into smaller methods that make it more readable.

Fixes:#123422
Release note (general change): made the delegateShowGrants method more readable by splitting it up into smaller methods, there is no change to functionality.

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
this looks cleaner to read, nice work! i had suggestions on how to organize it 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123428#-:-NxPAaYZ8vdodknbnF27:bnl1n28)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Dedej-Bergin and @fqazi)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123428#-NxP75n0As9afSk5Im5z):*
release notes are intended for our users to read, so they should only describe behavioral changes they would notice. see here for more information: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/186548364/Release+notes

in this case, it should be `Release note: None`

the information you wrote here would be useful to include in the commit message, since it's helpful for CockroachDB developers to read, but just not in the release note.
___
*[`pkg/sql/delegate/show_grants.go` line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123428#-NxP7YBw1SSE_jdRgFQ_:-NxP7YBx2ssP7KDDckXJ:b124whh) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd604a05619685e31796d7f05a2b31af5d041155/pkg/sql/delegate/show_grants.go#L146)):*
> ```Go
> `, oidext.CockroachPredefinedOIDMax)
> 
> type querySpecifics struct {
> ```

nit: can you add a comment above `querySpecifics` to describe what it is and where it's used? also, i think a name like `showGrantsSpecifics` would be more descriptive than `querySpecifics`
___
*[`pkg/sql/delegate/show_grants.go` line 149 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123428#-NxP9-6OCGOVhm46UfQL:-NxP9-6OCGOVhm46UfQM:bo2vvhy) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd604a05619685e31796d7f05a2b31af5d041155/pkg/sql/delegate/show_grants.go#L149)):*
> ```Go
> 	params   []string
> 	source   bytes.Buffer
> 	cond     bytes.Buffer
> ```

it would be easier to read if `source` and `cond` were also strings. the `bytes.Buffer` is only needed while building `source` and `cond`, but the way it's factored now, they are fully built by the time `querySpecifics` is returned by each function. see my comment at the end of `delegateShowGrantsDatabase` for how you could do this.
___
*[`pkg/sql/delegate/show_grants.go` line 164 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123428#-NxP7pQCEOUrRmwKfT35:-NxP7pQCEOUrRmwKfT36:b-udiurf) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd604a05619685e31796d7f05a2b31af5d041155/pkg/sql/delegate/show_grants.go#L164)):*
> ```Go
> 
> 	if n.Targets == nil {
> 		specifics = d.delegateShowGrantsAll(specifics)
> ```

nit: there's no need to have `specifics` be a parameter for any of these functions. in fact, it's probably more confusing to have it as a parameter, since `specifics` is the _output_ of each of the functions, and is not used for any part of the input. (just initialize the `querySpecifics` inside of these functions, rather than passing in a newly initialized value.)
___
*[`pkg/sql/delegate/show_grants.go` line 186 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123428#-NxPAQH187LeNU0C_8Ys:-NxPAQH187LeNU0C_8Yt:b-3dw9ha) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd604a05619685e31796d7f05a2b31af5d041155/pkg/sql/delegate/show_grants.go#L186)):*
> ```Go
> 	}
> 
> 	return d.addWithClause(n, specifics)
> ```

for this function, it actually does make sense to keep `specifics` as a parameter, since the function uses it as input. so no need to change this one
___
*[`pkg/sql/delegate/show_grants.go` line 228 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123428#-NxP9cQtEzFRmY9u6dlc:-NxP9cQtEzFRmY9u6dld:b-7bjpt8) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd604a05619685e31796d7f05a2b31af5d041155/pkg/sql/delegate/show_grants.go#L228)):*
> ```Go
> 	specifics.cond = cond
> 
> 	return specifics, nil
> ```

given both of the above suggestions, this part could instead be

```
return querySpecifics{
  params: params,
  source: source.String(),
  cond: cond.String(),
  nameCols: "database_name,"
}, nil
```

at the beginning of the function, you can initialize the values like this:
```
var source bytes.Buffer
var cond bytes.Buffer
var params []string
```

this same pattern can be used in the below functions

**Review by Dedej-Bergin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123428)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @rafiss)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123428#-NxP75n0As9afSk5Im5z):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

release notes are intended for our users to read, so they should only describe behavioral changes they would notice. see here for more information: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/186548364/Release+notes

in this case, it should be `Release note: None`

the information you wrote here would be useful to include in the commit message, since it's helpful for CockroachDB developers to read, but just not in the release note.
</blockquote></details>

Thanks, just this change
___
*[`pkg/sql/delegate/show_grants.go` line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123428#-NxP7YBw1SSE_jdRgFQ_:-NxSvj1j6jc1SEok4M8N:b-rfmdk4) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd604a05619685e31796d7f05a2b31af5d041155/pkg/sql/delegate/show_grants.go#L146)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: can you add a comment above `querySpecifics` to describe what it is and where it's used? also, i think a name like `showGrantsSpecifics` would be more descriptive than `querySpecifics`
</blockquote></details>

Added it, thanks Rafi!
___
*[`pkg/sql/delegate/show_grants.go` line 149 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123428#-NxP9-6OCGOVhm46UfQL:-NxTQtD_4YpAq6Oo7TcK:b-4gcff0) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd604a05619685e31796d7f05a2b31af5d041155/pkg/sql/delegate/show_grants.go#L149)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

it would be easier to read if `source` and `cond` were also strings. the `bytes.Buffer` is only needed while building `source` and `cond`, but the way it's factored now, they are fully built by the time `querySpecifics` is returned by each function. see my comment at the end of `delegateShowGrantsDatabase` for how you could do this.
</blockquote></details>

Thanks for the tip, I went ahead and made this change!
___
*[`pkg/sql/delegate/show_grants.go` line 164 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123428#-NxP7pQCEOUrRmwKfT35:-NxSvVQl3YOMbIDE56Pc:b-iiv2n5) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd604a05619685e31796d7f05a2b31af5d041155/pkg/sql/delegate/show_grants.go#L164)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: there's no need to have `specifics` be a parameter for any of these functions. in fact, it's probably more confusing to have it as a parameter, since `specifics` is the _output_ of each of the functions, and is not used for any part of the input. (just initialize the `querySpecifics` inside of these functions, rather than passing in a newly initialized value.)
</blockquote></details>

Yes definitely better this way, I went ahead and made the change thanks Rafi!
___
*[`pkg/sql/delegate/show_grants.go` line 186 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123428#-NxPAQH187LeNU0C_8Ys:-NxSvPuu4jSAAmDXyeEf:bq0ncok) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd604a05619685e31796d7f05a2b31af5d041155/pkg/sql/delegate/show_grants.go#L186)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

for this function, it actually does make sense to keep `specifics` as a parameter, since the function uses it as input. so no need to change this one
</blockquote></details>

sounds good
___
*[`pkg/sql/delegate/show_grants.go` line 228 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/123428#-NxP9cQtEzFRmY9u6dlc:-NxT-8n020dznfB0VvN1:bik09uy) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd604a05619685e31796d7f05a2b31af5d041155/pkg/sql/delegate/show_grants.go#L228)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

given both of the above suggestions, this part could instead be

```
return querySpecifics{
  params: params,
  source: source.String(),
  cond: cond.String(),
  nameCols: "database_name,"
}, nil
```

at the beginning of the function, you can initialize the values like this:
```
var source bytes.Buffer
var cond bytes.Buffer
var params []string
```

this same pattern can be used in the below functions
</blockquote></details>

this looks a lot nicer, thanks Rafi!

**Review by rafiss — APPROVED** [review]
nice work, this looks great now! i left a minor comment that i don't feel strongly about

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123428#-:-NxnalzQ43ubDnELYi68:b-4m0ian)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Dedej-Bergin and @fqazi)

___
*[`pkg/sql/delegate/show_grants.go` line 161 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123428#-NxnaXkoE9q0hXpx54xN:-NxnaXkoE9q0hXpx54xO:bk8a3p8) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d98e66354782ab6da36f76087094f9bf6c76a3c/pkg/sql/delegate/show_grants.go#L161)):*
> ```Go
> //	       mysql only returns the user's privileges.
> func (d *delegator) delegateShowGrants(n *tree.ShowGrants) (tree.Statement, error) {
> 	var specifics showGrantsSpecifics
> ```

super nit: it might be more readable to delete the `var specifics showGrantsSpecifics` declaration from all the functions. this `specifics` value is not really used anywhere.

(instead, in all the error cases, you would need something like `return showGrantsSpecifics{}, err`)

**Review by Dedej-Bergin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/123428)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @rafiss)

___
*[`pkg/sql/delegate/show_grants.go` line 161 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/123428#-NxnaXkoE9q0hXpx54xN:-NxsQxkDEFZi1YzuXq0T:b-oang0q) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d98e66354782ab6da36f76087094f9bf6c76a3c/pkg/sql/delegate/show_grants.go#L161)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

super nit: it might be more readable to delete the `var specifics showGrantsSpecifics` declaration from all the functions. this `specifics` value is not really used anywhere.

(instead, in all the error cases, you would need something like `return showGrantsSpecifics{}, err`)
</blockquote></details>

Thanks Rafi! Just made this change, definitely better this way

**Pull request merged**
