### PR TITLE
sql: migration to remove orphaned primary index comments

### LINKED ISSUE #73409: sql: write a migration to remove orphaned primary index comments
When a primary key change occurs, we were not cleaning up the comments that were on the old primary key.

Consider the following (this problem affects at least v21.1 plus):
```
root@:26257/defaultdb> create table t (a int, b int, constraint pkey primary key (a,b));
CREATE TABLE

root@:26257/defaultdb> comment on index pkey is 'idx';
COMMENT ON INDEX

root@:26257/defaultdb> alter table t alter primary key using columns (a);
ALTER TABLE

root@:26257/defaultdb> show create table t;
ERROR: index in GC mutations list
```

The problem is that the comment on `pkey` became orphaned. The `show create table` command sees the comment, but then cannot match it to a live index in the table descriptor.

https://github.com/cockroachdb/cockroach/pull/73408 takes care of the problem going forwards, but we still need to cleanup any comments out there that are orphaned.

### PR DESCRIPTION
**Pull request by fqazi**
Fixes: #73409

Previously, on older Cockroach versions it was possible
to drop indexes and not have comments for them cleaned up.
This was inadequate because entries would be left in
system.comments table for indexes that were dropped.
This patch, will introduce a new migration to clean up
index comments for any indexes that no longer exist.

Release note: None

### CODE REVIEW

**Review by postamar — COMMENTED** [review]
I suggested an improvement for the actual deletion, otherwise this looks good. I look forward to approving this.

> Reviewed 8 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75842#-:-MuvKvt35rdE8vm2WBQd:b-37jz2l)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

___
*[pkg/migration/migrations/comment_on_index_migration.go, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75842#-MuvHMhm8TjHesHMJPHx:-MuvHMhm8TjHesHMJPHy:b-p86q5j) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4cfd084c99eff848d6bd1bc84a43c75621d13d8/pkg/migration/migrations/comment_on_index_migration.go#L24)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/sql/sem/tree"
> 	"github.com/cockroachdb/cockroach/pkg/sql/sessiondata"
> 	"github.com/cockroachdb/cockroach/pkg/testutils/lint/passes/errwrap/testdata/src/github.com/cockroachdb/errors"
> ```

You imported the wrong errors package here. 
___
*[pkg/migration/migrations/comment_on_index_migration.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75842#-MuvHkEtDGxn8XuIQamg:-MuvHkEtDGxn8XuIQamh:bkdhrq1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4cfd084c99eff848d6bd1bc84a43c75621d13d8/pkg/migration/migrations/comment_on_index_migration.go#L47)):*
> ```Go
> 				  FROM crdb_internal.table_indexes
> 				 WHERE descriptor_id = comment.object_id
> 			);`,
> ```

I suspect you have this separate from the DELETE because CRDB doesn't support `DELETE FROM ... JOIN ...` but you can use tuples here to clean the comments table in a single statement:
```
DELETE FROM system.comments 
WHERE type = $1
  AND (object_id, sub_id) NOT IN (
    SELECT (descriptor_id, index_id) FROM crdb_internal.table_indexes
  );
```
with $1 bound to `keys.IndexCommentType`.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75842)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/migration/migrations/comment_on_index_migration.go, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75842#-MuvHMhm8TjHesHMJPHx:-MuvP74O5Mxa4HsV6aCe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4cfd084c99eff848d6bd1bc84a43c75621d13d8/pkg/migration/migrations/comment_on_index_migration.go#L24)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

You imported the wrong errors package here. 
</blockquote></details>

Done.
___
*[pkg/migration/migrations/comment_on_index_migration.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75842#-MuvHkEtDGxn8XuIQamg:-MuvP7bz8RyNySR-QI-b:bvpl0wy) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4cfd084c99eff848d6bd1bc84a43c75621d13d8/pkg/migration/migrations/comment_on_index_migration.go#L47)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

I suspect you have this separate from the DELETE because CRDB doesn't support `DELETE FROM ... JOIN ...` but you can use tuples here to clean the comments table in a single statement:
```
DELETE FROM system.comments 
WHERE type = $1
  AND (object_id, sub_id) NOT IN (
    SELECT (descriptor_id, index_id) FROM crdb_internal.table_indexes
  );
```
with $1 bound to `keys.IndexCommentType`. 
</blockquote></details>

Done.

Nice, I didn't realize that was allowed syntax-wise. I was trying to do the JOIN approach, but the syntax wasn't there.

**Review by postamar — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75842#-:-MuvZvfxAGliV-L0mVgD:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by fqazi** [comment]
@postamar TFTR!

**Pull request merged**
