### PR TITLE
sql/logictest: A re-write of the subtest command.

### LINKED ISSUE #21077: logictest: fix subtests
Pasting some comments from #20615 so we don't lose track of this.

It seems that the many occurrences of
```go
  subtestError = errors.Errorf(...)
  subtestT.Error(subtestError)
  return
```
could be just
```go
  subtestT.Fatalf(...)
```

Either way, when one of these happens, we will keep running the statements that follow in a new subtest with the same name (?!)  
```
            --- PASS: TestLogic/5node-distsql/distsql_stats/base (0.00s)
            --- FAIL: TestLogic/5node-distsql/distsql_stats/lol (0.00s)
            	logic_test.go:1042: testdata/logic_test/distsql_stats:5 invalid repeat line: strconv.Atoi: parsing "lol": invalid syntax
            --- FAIL: TestLogic/5node-distsql/distsql_stats/lol#01 (0.00s)
            	logic_test.go:1042: testdata/logic_test/distsql_stats:6 invalid repeat line: strconv.Atoi: parsing "lol": invalid syntax
```

We probably want to stop the entire file (call Fatalf on `t.t` not `subtestT`?).

By the way, the new code is very hard to understand when you get into the details (sorry for not thinking about the details carefully when reviewing). There are many subtleties as to how subtests keep working even when previous subtests aren't run (in fact I was convinced it's broken a bunch of times, and had to "reverse debug" some tests to see how it works).

In particular, we are abusing `Run()` - if we have a `subtest a` that isn't run, we actually keep calling `Run("a")` for each statement until the next subtest (generating a ton of subtests `a#01, a#02` etc). This is pretty sketchy, and it can leak out, e.g.

```
$ make test PKG=./pkg/sql/logictest TESTS='Logic/default/cascade/0' TESTFLAGS=-v
        --- PASS: TestLogic/default/cascade (2.88s)
            --- PASS: TestLogic/default/cascade/base#01 (0.00s)
            --- PASS: TestLogic/default/cascade/DeleteCascade_Basic#01 (0.29s)
            --- PASS: TestLogic/default/cascade/DeleteCascade_PrimaryKeys#01 (0.31s)
            --- PASS: TestLogic/default/cascade/DeleteCascade_CompositeFKs#01 (0.30s)
            --- PASS: TestLogic/default/cascade/DeleteCascade_Restrict#01 (0.38s)
            --- PASS: TestLogic/default/cascade/DeleteCascade_Interleaved#01 (0.43s)
            --- PASS: TestLogic/default/cascade/DeleteCascade_InterleavedRestrict#01 (0.40s)
            --- PASS: TestLogic/default/cascade/DeleteCascade_SelfReference#01 (0.03s)
            --- PASS: TestLogic/default/cascade/DeleteCascade_SelfReferenceCycle#01 (0.03s)
            --- PASS: TestLogic/default/cascade/DeleteCascade_TwoTableLoop#01 (0.12s)
            --- PASS: TestLogic/default/cascade/DeleteCascade_TwoTableLoopCycle#01 (0.12s)
            --- PASS: TestLogic/default/cascade/DeleteCascade_DoubleSelfReference#01 (0.39s)
```

We can even get a bogus error:
```
$ make test PKG=./pkg/sql/logictest TESTS='Logic/default/cascade/5' TESTFLAGS=-v
    --- FAIL: TestLogic/default (0.01s)
        --- FAIL: TestLogic/default/cascade (2.20s)
            --- PASS: TestLogic/default/cascade/DeleteCascade_Basic#05 (0.27s)
            --- PASS: TestLogic/default/cascade/DeleteCascade_PrimaryKeys#05 (0.31s)
            --- PASS: TestLogic/default/cascade/DeleteCascade_CompositeFKs#05 (0.30s)
            --- PASS: TestLogic/default/cascade/DeleteCascade_Restrict#05 (0.37s)
            --- PASS: TestLogic/default/cascade/DeleteCascade_Interleaved#05 (0.45s)
            --- PASS: TestLogic/default/cascade/DeleteCascade_InterleavedRestrict#05 (0.42s)
            --- FAIL: TestLogic/default/cascade/DeleteCascade_SelfReference#05 (0.00s)
            	logic_test.go:1406: testdata/logic_test/cascade:564: unknown command: id
        	logic_test.go:2063: 
        		testdata/logic_test/cascade:574: 
        		expected success, but found
        		pq: relation "self" does not exist
            --- FAIL: TestLogic/default/cascade/DeleteCascade_SelfReference#15 (0.00s)
            	logic_test.go:1088: 
            		testdata/logic_test/cascade:574: error in statement, skipping to next file
            --- FAIL: TestLogic/default/cascade/DeleteCascade_SelfReference#25 (0.00s)
            	logic_test.go:1000: testdata/logic_test/cascade:586: too many errors encountered, skipping the rest of the input
```

It might be cleaner to just read in the whole file into a `[]string` and then break that up into subtests beforehand.

We could also require that if a file uses `subtest`, it should start with that. Then we can avoid having the "base" subtest everywhere.

### PR DESCRIPTION
**Pull request by BramGruneir**
The current subtest command works, but the code was hard to read and when they failed, it was in strange ways. This is a re-write of that functionality that simplifies the code and should fail in the expected ways. See #21077 for more details.

Closes #21077

Release note: None

### CODE REVIEW

**Comment by BramGruneir** [comment]
@RaduBerinde Sorry for the delay getting this together, whole family's been sick.

Let me know what you think.  I think this covers all the error cases and is a lot easier to understand.

**Comment by RaduBerinde** [comment]
:lgtm_strong: 

The new code is fantastic, thank you!  Hope you all fell better and have a happy new year!

---

Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/sql/logictest/logic.go, line 269 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21142#-L1iOM9bDJxYnZoCg2Sl:-L1iOM9bDJxYnZoCg2Sm:b-wa7t75) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbc343b4697261f1f1c7920bcac1ce1040fe1412/pkg/sql/logictest/logic.go#L269)):*
> ```Go
> //                different numeric type than the one expected by the
> //                test. This enables reusing tests designed for
> //                database with slightly different typing semantics.
> ```

[nit] since you're here, "databases"

---

*[pkg/sql/logictest/logic.go, line 986 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21142#-L1iNKmA4L38CHfDULUN:-L1iNKmA4L38CHfDULUO:b-orpn2q) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbc343b4697261f1f1c7920bcac1ce1040fe1412/pkg/sql/logictest/logic.go#L986)):*
> ```Go
> type subtestDetails struct {
> 	name          string
> 	buffer        bytes.Buffer
> ```

[nit] could use a comment saying it stores a portion of the test file

---

*[pkg/sql/logictest/logic.go, line 1005 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21142#-L1iMx3jMVpYkFv56hL5:-L1iMx3jMVpYkFv56hL6:b-83sjoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbc343b4697261f1f1c7920bcac1ce1040fe1412/pkg/sql/logictest/logic.go#L1005)):*
> ```Go
> 			break
> 		}
> 		// If subtest has no name, than it is not a subtest, so just run the lines
> ```

Nice!

---

*[pkg/sql/logictest/logic.go, line 1005 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21142#-L1iMyO8VYwc3ymZFckV:-L1iMyO8VYwc3ymZFckW:btoqc6b) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbc343b4697261f1f1c7920bcac1ce1040fe1412/pkg/sql/logictest/logic.go#L1005)):*
> ```Go
> 			break
> 		}
> 		// If subtest has no name, than it is not a subtest, so just run the lines
> ```

[nit] then

---

*[pkg/sql/logictest/logic.go, line 1042 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21142#-L1iN85bPLUj1sB38bNE:-L1iN85bPLUj1sB38bNF:b-hnyhvm) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbc343b4697261f1f1c7920bcac1ce1040fe1412/pkg/sql/logictest/logic.go#L1042)):*
> ```Go
> }
> 
> func fetchSubtests(path string, config testClusterConfig) ([]subtestDetails, error) {
> ```

[nit] this could use a comment. Also, is config actually used?

---

*[pkg/sql/logictest/logic.go, line 1057 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21142#-L1iO0Pzoeu8DTZNx--1:-L1iO0Pzoeu8DTZNx--2:b5zrb7k) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbc343b4697261f1f1c7920bcac1ce1040fe1412/pkg/sql/logictest/logic.go#L1057)):*
> ```Go
> 		line := s.Text()
> 		fields := strings.Fields(line)
> 		if len(fields) > 0 && fields[0] == "subtest" {
> ```

[nit] this is a bit pedantic, but this could be tricked into looking at the wrong line if some query result happens to start with "subtest". I don't think this is worth fixing, but I'd leave a comment just in the off-chance that someone runs into this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21142#-:-L1iOxtxG9TKNG5dfFQF:b5977nr)*

**Comment by BramGruneir** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/sql/logictest/logic.go, line 269 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21142#-L1iOM9bDJxYnZoCg2Sl:-L1iksNekERZzJfGNTAt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbc343b4697261f1f1c7920bcac1ce1040fe1412/pkg/sql/logictest/logic.go#L269)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] since you're here, "databases"
</blockquote></details>

Done.

---

*[pkg/sql/logictest/logic.go, line 986 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21142#-L1iNKmA4L38CHfDULUN:-L1im0bQrzyzXA6caSHW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbc343b4697261f1f1c7920bcac1ce1040fe1412/pkg/sql/logictest/logic.go#L986)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] could use a comment saying it stores a portion of the test file
</blockquote></details>

Done.

---

*[pkg/sql/logictest/logic.go, line 1005 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21142#-L1iMyO8VYwc3ymZFckV:-L1im5aT9tjDmAc_eYMU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbc343b4697261f1f1c7920bcac1ce1040fe1412/pkg/sql/logictest/logic.go#L1005)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] then
</blockquote></details>

Done.

---

*[pkg/sql/logictest/logic.go, line 1042 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21142#-L1iN85bPLUj1sB38bNE:-L1in3L-h1Je_FzpEiMp:bg9v4wl) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbc343b4697261f1f1c7920bcac1ce1040fe1412/pkg/sql/logictest/logic.go#L1042)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] this could use a comment. Also, is config actually used?
</blockquote></details>

It wasn't, so I removed it.  And added a comment.

---

*[pkg/sql/logictest/logic.go, line 1057 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21142#-L1iO0Pzoeu8DTZNx--1:-L1inYgX9vVS-3WcJHSO:b3lf2md) ([raw file](https://github.com/cockroachdb/cockroach/blob/fbc343b4697261f1f1c7920bcac1ce1040fe1412/pkg/sql/logictest/logic.go#L1057)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] this is a bit pedantic, but this could be tricked into looking at the wrong line if some query result happens to start with "subtest". I don't think this is worth fixing, but I'd leave a comment just in the off-chance that someone runs into this.
</blockquote></details>

Agreed.  I added a comment to the error, which I think should cover it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21142)*

**Comment by RaduBerinde** [comment]
:lgtm_strong: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21142#-:-L1ix6TbFi0DXT-8ajMJ:b-uwkowd)*

**Comment by BramGruneir** [comment]
So... I thought I merged this 2 days ago via the octodroid app for android... clearly it didn't.  :(

**Pull request merged**
