### PR TITLE
tpccbench: various improvements to chaos and non-partitioned tests

### LINKED ISSUE #31156: TPCCbench failed under chaos
**Describe the problem**

TPCC bench failed under chaos 
`andy-1539099254-tpccbench-nodes-7-cpu-16-chaos: getting (scp) logs artifacts/tpccbench/nodes=7/cpu=16/chaos/logs
.
   1: done
   2: done
   3: done
   4: done
   5: done
   6: done
   7: done
   8: ~ scp -r -C -i /Users/andrewwoods/.ssh/google_compute_engine -o StrictHostKeyChecking=no andrewwoods@104.196.59.43:logs artifacts/tpccbench/nodes=7/cpu=16/chaos/8.logs
scp: logs: No such file or directory
: exit status 1
: exit status 1skipping cluster wipe
--- FAIL: tpccbench/nodes=7/cpu=16/chaos (10308.30s)
	test.go:570,cluster.go:1318,tpcc.go:663,tpcc.go:333: error running tpcc load generator:
		
		Error: EOF
		Error:  exit status 1
		
		: /Users/andrewwoods/go/bin/roachprod run andy-1539099254-tpccbench-nodes-7-cpu-16-chaos:8 -- ulimit -n 32768; ./workload run tpcc --warehouses=5000 --active-warehouses=2000 --tolerate-errors --ramp=5m0s --duration=10m0s {pgurl:8}: exit status 1
FAIL`

**To Reproduce**

Ran tpcc-bench with chaos on 7 nodes 

**Environment:**
 - CockroachDB version [e.g. 2.1 Beta 09/17]

[cockroach.log](https://github.com/cockroachdb/cockroach/files/2461885/cockroach.log)

### LINKED ISSUE #31234: Snapshot failed, mismatch incrementing epoch, and other errors when running tpcc with 30 nodes without partitioning
**Describe the problem**
image

**To Reproduce**
Changed ramp duration to 8h

`@@ -414,7 +414,7 @@ func loadTPCCBench(
        // generation doesn't actually run.
        cmd = fmt.Sprintf("ulimit -n 32768; "+
                "./workload run tpcc --warehouses=%d --split --scatter %s "+
               "--duration=3m --tolerate-errors {pgurl:1}", b.LoadWarehouses, partArgs)
               "--duration=8h --tolerate-errors {pgurl:1}", b.LoadWarehouses, partArgs)
        if out, err := c.RunWithBuffer(ctx, c.l, loadNode, cmd); err != nil {
                return errors.Wrapf(err, "failed with output %q", string(out))
        }`

Ran `bin/roachtest bench '^tpccbench/nodes=30/cpu=16$$' --wipe=false --user=andy`

**Expected behavior**

**Additional data / screenshots**

2018-10-10 22:54:26 | ERROR | [n1,raftsnapshot,s1,r190/1:/Table/59/1/{692/5/…-1181/3…}] snapshot failed: (n3,s4):4: remote couldn't accept Raft snapshot 5a04dfcf at applied index 13 with error: [n3,s4],r190: cannot apply snapshot: snapshot intersects existing range [n3,s4,r75/4:/{Table/59/1/6…-Max}]

2018-10-10 22:54:26 | ERROR | [n1,replicate,s1,r305/1:/Table/59/1/3619/10/-1503…] change replicas of r305 failed: descriptor changed: [expected] r305:/{Table/59/1/3619/10/-1503-Max} [(n1,s1):1, (n28,s24):2, (n2,s2):3, (n3,s4):4, next=5, gen=0] != [actual] r305:/Table/59/1/3619/10/-1503{-/0} [(n1,s1):1, (n28,s24):2, (n2,s2):3, (n3,s4):4, next=5, gen=1]: unexpected value: raw_bytes:"\001\270\340\017\003\010\261\002\022\t\303\211\367\016#\222\206\372!\032\n\303\211\367\016#\222\206\372!\210\"\006\010\001\020\001\030\001\"\006\010\034\020\030\030\002\"\006\010\002\020\002\030\003\"\006\010\003\020\004\030\004(\0050\001" timestamp:<wall_time:1539212066497189048 >

E181011 00:39:55.229855 14221444 storage/replica_range_lease.go:301  [n1,s1,r40208/1:/Table/61/1/5023/65647{-/0}] mismatch incrementing epoch for {NodeID:27 Epoch:1 Expiration:1539218351.983387584,0 Draining:false Decommissioning:false}; actual is {NodeID:27 Epoch:1 Expiration:1539218369.983334357,0 Draining:false Decommissioning:false}

E181011 00:43:46.696866 15483502 storage/replica_range_lease.go:301  [n1,s1,r41307/1:/Table/61/1/503{3/126…-4/5220}] context canceled

E181010 22:54:16.124941 68 sqlmigrations/migrations.go:370  [n8] failed attempt to acquire migration lease: lease /System/"system-version/lease" is not available until at least 1539212116.073461816,0`

**Environment:**
CockroachDB version 2.1.0 beta 1008

[cockroach.log](https://github.com/cockroachdb/cockroach/files/2466947/cockroach.log)

[cockroach.log](https://github.com/cockroachdb/cockroach/files/2466948/cockroach.log)

### PR DESCRIPTION
**Pull request by nvb**
Closes #31234.
Closes #31156.

cc. @awoods187

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
@awoods187 I'm running `tpccbench/nodes=7/cpu=16/chaos` and `tpccbench/nodes=3/cpu=16` now on `cockroach-v2.1.0-beta.20181008`. I'll let you know what the results are.

**Review by m-schneider — DISMISSED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31275)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/tpcc.go, line 204 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/31275#-LOZQPqAADq3z8KO2Z0d:-LOZQPqAADq3z8KO2Z0e:b-vmxbbu) ([raw file](https://github.com/cockroachdb/cockroach/blob/37e74f10ceb1c06457c7a69682897c986fc72490/pkg/cmd/roachtest/tpcc.go#L204)):*
> ```Go
> 	switch d {
> 	case singleZone:
> 		return []string{"us-central1-a"}
> ```

I usually ran tests in 1-b, when I was tracking down variability, can't really comment on 1-a performance.
___
*[pkg/cmd/roachtest/tpcc.go, line 701 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/31275#-LOZRD9M3hjUSXBvorPQ:-LOZRD9M3hjUSXBvorPR:bo591yg) ([raw file](https://github.com/cockroachdb/cockroach/blob/37e74f10ceb1c06457c7a69682897c986fc72490/pkg/cmd/roachtest/tpcc.go#L701)):*
> ```Go
> 
> 			LoadWarehouses: 2000,
> 			EstimatedMax:   1000,
> ```

Did you set it about 300 below on purpose so that it runs a bit longer?

**Review by a-robinson — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31275)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/tpcc.go, line 495 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31275#-LOZSguJ85T_U0EkU2Ow:-LOZSguJ85T_U0EkU2Ox:b-md6vqh) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4a6c5753f754e5d4de2355bd1459fb8bd6ce863/pkg/cmd/roachtest/tpcc.go#L495)):*
> ```Go
> 		c.Install(ctx, loadNodes, "haproxy")
> 		c.Put(ctx, cockroach, "./cockroach", loadNodes)
> 		c.Run(ctx, loadNodes, fmt.Sprintf("./cockroach gen haproxy --insecure --host %s",
> ```

So was this just failing previously?
___
*[pkg/cmd/roachtest/tpcc.go, line 537 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31275#-LOZSsJP-Gp8adY4cYIz:-LOZSsJP-Gp8adY4cYJ-:bbnfefd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4a6c5753f754e5d4de2355bd1459fb8bd6ce863/pkg/cmd/roachtest/tpcc.go#L537)):*
> ```Go
> 					Target:       roachNodes.randNode,
> 					Stopper:      loadDone,
> 					DrainAndQuit: true,
> ```

Is the thought just that there's a bug in the test logic that implements `DrainAndQuit`?
___
*[pkg/cmd/roachtest/tpcc.go, line 419 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31275#-LOZVqND2BClIRpOaEAI:-LOZVqNEAhmRitNL3rJl:bplddim) ([raw file](https://github.com/cockroachdb/cockroach/blob/4eae1b158f52bec4c9f73c25b950a1c905df135e/pkg/cmd/roachtest/tpcc.go#L419)):*
> ```
> 	// Run 1/10th of the expected load in the
> 	// desired distribution by dropping the worker count. This should allow
> 	// for load-based rebalancing to help distribute load.
> ```

We may want to just run `--ramp=<rebalanceWait> --duration=1s` instead of dropping the worker count so much. Load-based rebalancing ignores differences of less than 100qps per store, and for low warehouse counts will we even see differences that large if we do this?
___
*[pkg/cmd/roachtest/tpcc.go, line 426 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31275#-LOZVZ7gDynA1IQCVlCv:-LOZVZ7gDynA1IQCVlCw:b-4ryv5w) ([raw file](https://github.com/cockroachdb/cockroach/blob/4eae1b158f52bec4c9f73c25b950a1c905df135e/pkg/cmd/roachtest/tpcc.go#L426)):*
> ```Go
> 		"./workload run tpcc --warehouses=%d --workers=%d --split --scatter "+
> 		"--duration=%d --tolerate-errors %s {pgurl%s}",
> 		b.LoadWarehouses, b.LoadWarehouses, rebalanceWait, partArgs, roachNodes)
> ```

I'm not sure `rebalanceWait` is really going to be long enough, but I guess we'll find out.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31275)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/tpcc.go, line 495 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31275#-LOZSguJ85T_U0EkU2Ow:-LOsdPjF634mKCsUpI5m:bdma56v) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4a6c5753f754e5d4de2355bd1459fb8bd6ce863/pkg/cmd/roachtest/tpcc.go#L495)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

So was this just failing previously?
</blockquote></details>

Yes. I added a new `tpccbench/nodes=12/cpu=4/chaos/partition` test that will run nightly.
___
*[pkg/cmd/roachtest/tpcc.go, line 537 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31275#-LOZSsJP-Gp8adY4cYIz:-LOse5YW1-gzrlVnVEZ1:b-6n44jc) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4a6c5753f754e5d4de2355bd1459fb8bd6ce863/pkg/cmd/roachtest/tpcc.go#L537)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Is the thought just that there's a bug in the test logic that implements `DrainAndQuit`?
</blockquote></details>

I didn't track down exactly what was going wrong, but I don't think this ever really worked. We can explore this more when we revist chaos. For now, this is reverting to the approach that we did most of our testing with.
___
*[pkg/cmd/roachtest/tpcc.go, line 419 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31275#-LOZVqND2BClIRpOaEAI:-LOsrRpl0WgX26193FeR:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/4eae1b158f52bec4c9f73c25b950a1c905df135e/pkg/cmd/roachtest/tpcc.go#L419)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

> ```
> 	// Run 1/10th of the expected load in the
> 	// desired distribution by dropping the worker count. This should allow
> 	// for load-based rebalancing to help distribute load.
> ```

We may want to just run `--ramp=<rebalanceWait> --duration=1s` instead of dropping the worker count so much. Load-based rebalancing ignores differences of less than 100qps per store, and for low warehouse counts will we even see differences that large if we do this?
</blockquote></details>

Good idea. Done.
___
*[pkg/cmd/roachtest/tpcc.go, line 426 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31275#-LOZVZ7gDynA1IQCVlCv:-LOsrL0D1SECABAp_aU4:bfjny7g) ([raw file](https://github.com/cockroachdb/cockroach/blob/4eae1b158f52bec4c9f73c25b950a1c905df135e/pkg/cmd/roachtest/tpcc.go#L426)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

I'm not sure `rebalanceWait` is really going to be long enough, but I guess we'll find out.
</blockquote></details>

Bumped it by 50%. Even with the old wait period, we were able to hit TPC-C 10k without partitioning.
___
*[pkg/cmd/roachtest/tpcc.go, line 204 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/31275#-LOZQPqAADq3z8KO2Z0d:-LOsdJKFCuBLlxFeJG4f:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/37e74f10ceb1c06457c7a69682897c986fc72490/pkg/cmd/roachtest/tpcc.go#L204)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

I usually ran tests in 1-b, when I was tracking down variability, can't really comment on 1-a performance.
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/tpcc.go, line 701 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/31275#-LOZRD9M3hjUSXBvorPQ:-LOseOB62sg87A3g-pqT:bb81has) ([raw file](https://github.com/cockroachdb/cockroach/blob/37e74f10ceb1c06457c7a69682897c986fc72490/pkg/cmd/roachtest/tpcc.go#L701)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

Did you set it about 300 below on purpose so that it runs a bit longer?
</blockquote></details>

No, it just never got updated.

**Review by a-robinson — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31275#-:-LOt3UMSB1rb1OATlnsv:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/tpcc.go, line 426 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31275#-LOZVZ7gDynA1IQCVlCv:-LOt36rd7olCu3ZJ3yLO:b-rorkes) ([raw file](https://github.com/cockroachdb/cockroach/blob/4eae1b158f52bec4c9f73c25b950a1c905df135e/pkg/cmd/roachtest/tpcc.go#L426)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Bumped it by 50%. Even with the old wait period, we were able to hit TPC-C 10k without partitioning.
</blockquote></details>

🎉🎉🎉
___
*[pkg/cmd/roachtest/tpcc.go, line 184 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/31275#-LOt3Puh5TJ5P-cGgjPB:-LOt3Puh5TJ5P-cGgjPC:b-ce6qai) ([raw file](https://github.com/cockroachdb/cockroach/blob/cca2d0faf80a4174bb50e5aa79bed20d5c9cffba/pkg/cmd/roachtest/tpcc.go#L184)):*
> ```Go
> 	})
> 	registerTPCCBenchSpec(r, tpccBenchSpec{
> 		Nodes:      9,
> ```

You know better than me, but isn't 9 nodes a lot for CI?

**Review by nvb — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31275#-:-LOxCJkS94Wqv1pH-2Uf:b-tlx7ko)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/tpcc.go, line 701 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/31275#-LOZRD9M3hjUSXBvorPQ:-LOxCLrT4DU-TUasKEMu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/37e74f10ceb1c06457c7a69682897c986fc72490/pkg/cmd/roachtest/tpcc.go#L701)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

No, it just never got updated.
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/tpcc.go, line 184 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/31275#-LOt3Puh5TJ5P-cGgjPB:-LOxCApe4e1Ugfd6ksRe:b-nwpzrr) ([raw file](https://github.com/cockroachdb/cockroach/blob/cca2d0faf80a4174bb50e5aa79bed20d5c9cffba/pkg/cmd/roachtest/tpcc.go#L184)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

You know better than me, but isn't 9 nodes a lot for CI?
</blockquote></details>

Not if they're 4-core machines. This should be fine.

**Pull request merged**
