### PR TITLE
sqlstats: skip TestSQLStatsFlush under race

### LINKED ISSUE #116003: persistedsqlstats: TestSQLStatsFlush is flaky
```
No pass/skip/fail event found for test
=== RUN   TestSQLStatsFlush
    test_log_scope.go:170: test logs captured to: /artifacts/tmp/_tmp/9a30d5271a65be6b3f2aa1433be9011f/logTestSQLStatsFlush3569017073
    test_log_scope.go:81: use -show-logs to present logs inline
panic: test timed out after 5m24s
running tests:
```

https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelExtendedCi/13055735?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

Jira issue: CRDB-34371

### PR DESCRIPTION
**Pull request by dhartunian**
Resolves: #116003
Epic: None

Release note: None

### CODE REVIEW

**Review by maryliag — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116073#-:-NlOmItR2vkLnZpzTyr0:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @abarganier)

**Comment by dhartunian** [comment]
bors r=mayliag

**Comment by dhartunian** [comment]
bors r=maryliag

**Comment by rickystewart** [comment]
bors r=maryliag

**Comment by michae2** [comment]
blathers backport release-23.2

**Comment by michae2** [comment]
blathers backport release-23.2.0

**Comment by michae2** [comment]
blathers backport release-23.2.0-rc

**Pull request merged**
