### PR TITLE
sql/sqlbase: avoid various allocations during column family span splitting

### PR DESCRIPTION
**Pull request by nvb**
This PR contains two improvements to column family splitting that avoid unnecessary memory allocations and copies.

The first commit avoids intermediate slices during column family span splitting. It does so by reworking the `SplitSpanIntoSeparateFamilies` class of functions to accept slices as arguments and append directly to these slices. This avoids the need for intermediate slice allocation when calling these functions, as they now append directly to the destination slice.

The second commit avoids a useless key copy in `SplitSpanIntoSeparateFamilies `. It does so by making a copy of the provided `roachpb.Key` before using it to construct a family key in `SplitSpanIntoSeparateFamilies `. This was unnecessary because `MakeFamilyKey` is already going to re-alloc when it appends. It looks like we were trying to avoid mutations to extra capacity in `span.Key`, but there's an easier way to do that - just limit its capacity before calling `MakeFamilyKey`.

This is a bit of cleanup work before addressing https://github.com/cockroachdb/cockroach/pull/44178#issuecomment-577347011.

### CODE REVIEW

**Review by rohany — APPROVED** [review]
Code looks good! Thanks for the cleanup nathan

> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44224#-:-LzDw7I3EMi6s4nqO1Ug:b-kcsvvt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten, @rohany, and @solongordon)

___
*[pkg/sql/span/span_builder.go, line 158 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44224#-LzDvZaHDQCw4hYxUw9a:-LzDvZaHDQCw4hYxUw9b:b-ctg98d) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6494e346c7fde136bff61459d750065b6669b32/pkg/sql/span/span_builder.go#L158)):*
> ```Go
> //
> // The function accepts a slice of spans to append to.
> func (s *Builder) MaybeAppendSpansAfterSpanSplitIntoSeparateFamilies(
> ```

this function's name is such a mouthful, but I don't have any suggestions.
___
*[pkg/sql/sqlbase/index_encoding.go, line 281 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44224#-LzDw4av5Iwkeduwl97T:-LzDw4av5Iwkeduwl97U:bnj7hl0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6494e346c7fde136bff61459d750065b6669b32/pkg/sql/sqlbase/index_encoding.go#L281)):*
> ```Go
> //
> // The function accepts a slice of spans to append to.
> func AppendSpansAfterSpanSplitIntoSeparateFamilies(
> ```

same as above

**Review by nvb — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44224#-:-LzDyhzU345Y3Knyl9n9:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany and @solongordon)

___
*[pkg/sql/span/span_builder.go, line 158 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44224#-LzDvZaHDQCw4hYxUw9a:-LzDySdn6jwrQ-LA2rVf:b23uuxl) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6494e346c7fde136bff61459d750065b6669b32/pkg/sql/span/span_builder.go#L158)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

this function's name is such a mouthful, but I don't have any suggestions.
</blockquote></details>

Yeah... I tried to make this shorter but wasn't able to find anything that didn't leave things ambiguous at the caller. I'll wait to see if Solon has any suggestions. If not, I guess I'll just keep this.

**Review by solongordon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44224)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany and @solongordon)

___
*[pkg/sql/span/span_builder.go, line 158 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44224#-LzDvZaHDQCw4hYxUw9a:-LzE-VfM58V5i5IdjLuY:b-1fxdxa) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6494e346c7fde136bff61459d750065b6669b32/pkg/sql/span/span_builder.go#L158)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yeah... I tried to make this shorter but wasn't able to find anything that didn't leave things ambiguous at the caller. I'll wait to see if Solon has any suggestions. If not, I guess I'll just keep this.
</blockquote></details>

I'd vote for keeping the function names as they were. The signatures and docstrings already make the behavior clear enough.

**Review by nvb — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44224#-:-LzEil621ADI8MDWeCNk:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany)

___
*[pkg/sql/span/span_builder.go, line 158 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44224#-LzDvZaHDQCw4hYxUw9a:-LzEikbBCruXNbXgISUV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6494e346c7fde136bff61459d750065b6669b32/pkg/sql/span/span_builder.go#L158)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I'd vote for keeping the function names as they were. The signatures and docstrings already make the behavior clear enough.
</blockquote></details>

Done.

**Pull request merged**
