### PR TITLE
sql: convert SQL audit and execution log to a structured format

### LINKED ISSUE #58999: sql: append database name to audit log line for executed query
Currently in the SQL audit logs:
```
I201211 17:20:30.880671 2096606 sql/exec_log.go:207 ⋮ [n15,client=‹1.2.3.4:12345›,hostssl,user=‹test›] 45 ‹exec› ‹"PostgreSQL JDBC Driver"› ‹{"tablename"[118]:READ}› ‹"SELECT column1 FROM tablename AS my_table WHERE ((column1 IS NOT NULL)"› ‹{}› 4.492 0 ‹OK› 0
```
This log line shows the `tablename` table and `test` user that executed the query, but not the database name where `tablename` is located. This makes it difficult to parse the logs using tooling to quickly find what query impacted what set of data, especially in the event where `tablename` may exist on multiple databases in the cluster. Enabling this database name to appended to the log, or to have a flag to enable this feature would be beneficial.

### LINKED ISSUE #59105: logging,sql: make structured events for SQL query log and audit logging
Requested by customer, via @thtruo 

Today the entries in `cockroach-sql-slow.log`, `cockroach-sql-audit.log` and `cockroach-sql-exec.log` are not structured. This is a problem because the customers would like to integrate these events with external log monitoring.

Additionally, certain queries fail with an error. This fact is indicated with a copy of the error message in the log event. Unfortunately, the error message may contain sensitive information. We wish to include the presence of an error with  the SQLSTATE  and the error message in a separate field, so that the latter can be eliminated reliably with a log filter.

### PR DESCRIPTION
**Pull request by knz**
First commit from #59108.
Fixes #59105. 
Fixes #58999. 

Example new format for the query log:
```
I210118 17:20:32.675052 2009 10@util/log/event_log.go:32  [n1,client=127.0.0.1:11362,hostssl,user=demo] Structured entry:
{"Timestamp":1610990432674339786,
 "EventType":"slow_query",
 "Statement":"SELECT * FROM \"\".\"\".t WHERE x = 10",
 "User":"demo",
 "ApplicationName":"$ cockroach demo",
 "ExecMode":"exec",
 "Age":0.790742,
 "FullTableScan":true}
 ```

Example new format, for audit events:
```
I210122 16:33:01.297735 2012 8@util/log/event_log.go:32 [n1,client=127.0.0.1:59820,hostssl,user=demo] Structured entry:
{"Timestamp":1611333181296915618,
 "EventType":"sensitive_table_access",
 "Statement":"INSERT INTO \"\".\"\".helloworld(abc) VALUES (1)",
 "User":"demo",
 "DescriptorID":53,
 "ApplicationName":"$ cockroach demo",
 "ExecMode":"exec",
 "NumRows":1,
 "Age":0.895012,
 "TableName":"t.public.helloworld",
 "AccessMode":"rw"}
```

(Audit events have more fields, specifically `DescriptorID`,
`TableName` and `AccessMode`, because they pertain to specific
objects for which audit logging has been triggered.)

Release note (sql change): CockroachDB now uses
a structured logging format for the SQL audit, execution and
query logs. See the reference documentation for details.

Of note, audit and execution logs now also include information
about whether a query plan contain full index scans. Previously,
this information was only included in theslow query log.

Release note (backward-incompatible change): The logging format for
SQL audit, execution and query logs has changed, from a crude
space-delimited format to JSON. To opt out of this new behavior and
restore the pre-v21.1 logging format, you can set the cluster setting
`sql.log.unstructured_entries.enabled` to true.

### CODE REVIEW

**Comment by knz** [comment]
@jordanlewis I took #58999 on board as requested. The db name is only included in the new structured format though.

**Comment by knz** [comment]
Note that the table names are not automatically qualified in the reported queries/statements. They were not before either. This is tracked as separate issue #59303 .

**Review by jordanlewis — APPROVED** [review]
Very nice work. This should be announced pretty loudly via docs, I think.

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59110#-:-MRgWRgzECCwpc3fANYh:buf04w1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @jordanlewis, and @knz)

___
*[docs/generated/eventlog.md, line 1597 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59110#-MRgV73v2wUa959wUyi5:-MRgV73v2wUa959wUyi6:b9bw1ck) ([raw file](https://github.com/cockroachdb/cockroach/blob/898e5945ef56a83f987a62b659937b1b94b04f3f/docs/generated/eventlog.md#L1597)):*
> ```Markdown
> | `DescriptorID` | The primary object descriptor affected by the operation. Set to zero for operations that don't affect descriptors. | no |
> | `ApplicationName` | The application name for the session where the event was emitted. This is included in the event to ease filtering of logging output by application. | yes |
> | `PlaceholderValues` | The mapping of SQL placeholders to their values, for prepared statements. | yes |
> ```

should we mark this file as binary to avoid the diffs?
___
*[pkg/sql/exec_log.go, line 259 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59110#-MRgWA530n0rquCsLxF8:-MRgWA530n0rquCsLxF9:bqcchkf) ([raw file](https://github.com/cockroachdb/cockroach/blob/73bdc73a0b699637ebc306c08634a51eee13ca0e/pkg/sql/exec_log.go#L259)):*
> ```Go
> 
> 	if auditEventsDetected {
> 		// TODO(knz): re-add the placeholders and age into the logging event.
> ```

Didn't you add this in the frst commit? I must be missing something.
___
*[pkg/util/log/eventpb/sql_audit_events.proto, line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59110#-MRgWJ9Z4dkjN2sNkZ4a:-MRgWJ9Z4dkjN2sNkZ4b:be4l6wz) ([raw file](https://github.com/cockroachdb/cockroach/blob/73bdc73a0b699637ebc306c08634a51eee13ca0e/pkg/util/log/eventpb/sql_audit_events.proto#L28)):*
> ```protobuf
>   string exec_mode = 1 [(gogoproto.jsontag) = ",omitempty", (gogoproto.moretags) = "redact:\"nonsensitive\""];
>   // Number of rows returned.
>   uint64 num_rows = 2 [(gogoproto.jsontag) = ",omitempty"];
> ```

What does this do for inserts? Worth mentioning.

**Review by knz — COMMENTED** [review]
> This should be announced pretty loudly via docs, I think.

There's a humongous docs project for logging already underway. This will be part of it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59110#-:-MRirAKf2xD_nFSpsemn:bwogyv8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @jordanlewis)

___
*[docs/generated/eventlog.md, line 1597 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59110#-MRgV73v2wUa959wUyi5:-MRirJalDqnZ66g3UAfa:b7p94bg) ([raw file](https://github.com/cockroachdb/cockroach/blob/898e5945ef56a83f987a62b659937b1b94b04f3f/docs/generated/eventlog.md#L1597)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

should we mark this file as binary to avoid the diffs?
</blockquote></details>

I don't believe so: 

1) the generated doc file is much easier to review as a whole than the comments in the source files. It's easier to spot a mistake here and then find the source comment that caused it.

2) as we involve doc writers more and more to review user-facing changes, these  generated doc files will be the "interface" to facilitate their review
___
*[pkg/sql/exec_log.go, line 259 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59110#-MRgWA530n0rquCsLxF8:-MRirmIy41H81VSRa2aP:bobclp9) ([raw file](https://github.com/cockroachdb/cockroach/blob/73bdc73a0b699637ebc306c08634a51eee13ca0e/pkg/sql/exec_log.go#L259)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Didn't you add this in the frst commit? I must be missing something.
</blockquote></details>

Good catch. Removed.
___
*[pkg/util/log/eventpb/sql_audit_events.proto, line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59110#-MRgWJ9Z4dkjN2sNkZ4a:-MRivyGr7qotXDpMXBxj:b-szf42y) ([raw file](https://github.com/cockroachdb/cockroach/blob/73bdc73a0b699637ebc306c08634a51eee13ca0e/pkg/util/log/eventpb/sql_audit_events.proto#L28)):*
Then it's "rows affected".

> Worth mentioning.

Yes! Very good idea. Done.

**Comment by knz** [comment]
TFYR!

bors r=jordanlewis

**Pull request merged**
