### PR TITLE
kvserver: teach allocator to prescribe non-voter addition/removal

### PR DESCRIPTION
**Pull request by aayushshah15**
This PR adds basic logic in the allocator to spit out actions that
prescribe upreplication or downreplication of non-voting replicas based
on zone configs.

Note that this commit *does not* enable the `replicateQueue` or the
`StoreRebalancer` to actually act on these newly added
`AllocatorAction`s, not does it make the allocator smart enough to
prescribe _rebalancing_ non-voting replicas. This commit also does not
teach the allocator to rank non-voting replicas for addition or removal.

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59389)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @andreimatei)

___
*[pkg/kv/kvserver/allocator.go, line 52 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59389#-MS5kRN17ILQ7o3XWgDY:-MS5kRN17ILQ7o3XWgDZ:b-v3zvoo) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ba4f15626b7bf06b62e5cdaa517896986aa3dde/pkg/kv/kvserver/allocator.go#L52)):*
> ```Go
> 
> 	// Priorities for various repair operations.
> 	// TODO DURING REVIEW: Do these priorities look sane? Note that these
> ```

This comment was helpful. I never knew that this was the only use of these priorities. Could you add to the comment to indicate this.

Now that I know that, I'm left wondering whether the magnitude of these priorities matter, or whether only their relative order matters. For instance, is it meaningful that `addDecommissioningReplacementVoterPriority` has 5x the priority of `removeDeadVoterPriority`? Would `addDecommissioningReplacementVoterPriority float64 = 1001` have the exact same behavior?
___
*[pkg/kv/kvserver/allocator.go, line 52 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59389#-MS5l2KWB6c9DLYfd9ma:-MS5l2KWB6c9DLYfd9mb:bwgqx6) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ba4f15626b7bf06b62e5cdaa517896986aa3dde/pkg/kv/kvserver/allocator.go#L52)):*
> ```Go
> 
> 	// Priorities for various repair operations.
> 	// TODO DURING REVIEW: Do these priorities look sane? Note that these
> ```

Yes, these priorities make sense to me.
___
*[pkg/kv/kvserver/allocator.go, line 159 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59389#-MS5lRgJ4NTPnfBZIF5K:-MS5lRgJ4NTPnfBZIF5L:b-arx2k0) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ba4f15626b7bf06b62e5cdaa517896986aa3dde/pkg/kv/kvserver/allocator.go#L159)):*
> ```Go
> type allocatorError struct {
> 	constraints []zonepb.ConstraintsConjunction
> 	// TODO(aayush): !!! This might need to be augmented.
> ```

What did you decide here?
___
*[pkg/kv/kvserver/allocator.go, line 317 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59389#-MS5m4yP-5Y7t6PAOduq:-MS5m4yP-5Y7t6PAOdur:bxbsvcf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ba4f15626b7bf06b62e5cdaa517896986aa3dde/pkg/kv/kvserver/allocator.go#L317)):*
> ```Go
> // available for up-replication.
> //
> // If `num_voters` aren't explicitly configured in the zone config, all replicas
> ```

"all `num_replicas` replicas"
___
*[pkg/kv/kvserver/allocator.go, line 323 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59389#-MS5lf4p6NwP_pYSeRmq:-MS5lf4p6NwP_pYSeRmr:b-jiytlv) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ba4f15626b7bf06b62e5cdaa517896986aa3dde/pkg/kv/kvserver/allocator.go#L323)):*
> ```Go
> // this method should only be consulted after voting replicas have been
> // upreplicated / rebalanced off of dead/decommissioning nodes.
> func GetNeededNonVoters(numVoters, zoneConfigNumNonVoters, clusterNodes int) int {
> ```

nit: we have `zoneConfigVoterCount` above and `zoneConfigNumNonVoters` here. Let's be uniform.
___
*[pkg/kv/kvserver/allocator.go, line 411 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59389#-MS5mUIh6TE0qSLkXFP7:-MS5mUIh6TE0qSLkXFP8:b-bslxxo) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ba4f15626b7bf06b62e5cdaa517896986aa3dde/pkg/kv/kvserver/allocator.go#L411)):*
> ```Go
> 	quorum := computeQuorum(haveVoters)
> 
> 	// TODO(aayush): When haveVoters < neededVoters but we don't have quorum to
> ```

Any idea why we don't already do this? The code structure makes me wonder if it's intentional.
___
*[pkg/kv/kvserver/allocator.go, line 425 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59389#-MS5nUKwEzZf7kmjRU_Y:-MS5nUKwEzZf7kmjRU_Z:b-3dur72) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ba4f15626b7bf06b62e5cdaa517896986aa3dde/pkg/kv/kvserver/allocator.go#L425)):*
> ```Go
> 	}
> 
> 	liveVoterReplicas, deadVoterReplicas := a.storePool.liveAndDeadReplicas(voterReplicas)
> ```

nit: should we rename this to `liveVoters` and `deadVoters` to fit the rest of the variable naming in this function?
___
*[pkg/kv/kvserver/allocator.go, line 460 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59389#-MS5nMKY4igSPwyQ3b07:-MS5nMKZ4EeW0zL1T3Ea:bwa5lfk) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ba4f15626b7bf06b62e5cdaa517896986aa3dde/pkg/kv/kvserver/allocator.go#L460)):*
> ```Go
> 
> 	// Non-voting replica addition.
> 	//liveNonVoters, deadNonVoters := a.storePool.liveAndDeadReplicas(nonVoterReplicas)
> ```

Do we need to handle the `if haveNonVoters == neededNonVoters && len(deadNonVoters) > 0 {` case? In fact, do we need a `AllocatorReplaceDeadNonVoter` action? Does that fall into your future change to rebalance non-voting replicas?
___
*[pkg/kv/kvserver/allocator.go, line 465 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59389#-MS5n4Dw1e83-cdDvscu:-MS5n4Dw1e83-cdDvscv:bk6urm5) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ba4f15626b7bf06b62e5cdaa517896986aa3dde/pkg/kv/kvserver/allocator.go#L465)):*
> ```Go
> 	if haveNonVoters < neededNonVoters {
> 		priority := addMissingNonVoterPriority
> 		action := AllocatorAddNonVoter
> ```

Isn't this supposed to be a lower priority than `AllocatorRemoveDeadVoter`? Will that work if we have this check before the `if len(deadVoterReplicas) > 0 {` check?

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59389)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @andreimatei, and @nvanbenschoten)

___
*[pkg/kv/kvserver/allocator.go, line 52 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59389#-MS5kRN17ILQ7o3XWgDY:-MS5sWNU2-s_ODQ_7HR_:buwp31g) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ba4f15626b7bf06b62e5cdaa517896986aa3dde/pkg/kv/kvserver/allocator.go#L52)):*
> I'm left wondering whether the magnitude of these priorities matter

The difference between `addMissingVoterPriority` and `addDecommissioningReplacementVoterPriority` makes sense to me because we modulate the priority of adding missing voters based on how far we are from our expected voter count. But for the rest I don't think the magnitude matters.
___
*[pkg/kv/kvserver/allocator.go, line 159 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59389#-MS5lRgJ4NTPnfBZIF5K:-MSQ7FQrE9ZTYWAkFrEG:bbikyd7) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ba4f15626b7bf06b62e5cdaa517896986aa3dde/pkg/kv/kvserver/allocator.go#L159)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What did you decide here?
</blockquote></details>

Sorry, this should be addressed inside #59403. Removed from here.
___
*[pkg/kv/kvserver/allocator.go, line 317 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59389#-MS5m4yP-5Y7t6PAOduq:-MSMMg3y83qVnsjzAAtG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ba4f15626b7bf06b62e5cdaa517896986aa3dde/pkg/kv/kvserver/allocator.go#L317)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"all `num_replicas` replicas"
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/allocator.go, line 323 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59389#-MS5lf4p6NwP_pYSeRmq:-MSMMlx0D9wsAziZE2EG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ba4f15626b7bf06b62e5cdaa517896986aa3dde/pkg/kv/kvserver/allocator.go#L323)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: we have `zoneConfigVoterCount` above and `zoneConfigNumNonVoters` here. Let's be uniform.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/allocator.go, line 411 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59389#-MS5mUIh6TE0qSLkXFP7:-MS5tFql4bayIKVfXrop:b-oxhked) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ba4f15626b7bf06b62e5cdaa517896986aa3dde/pkg/kv/kvserver/allocator.go#L411)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Any idea why we don't already do this? The code structure makes me wonder if it's intentional.
</blockquote></details>

Yeah it does seem intentional, but I don't really see how. It makes sense that it's never really come up before because the symptoms would be hard to discern.
___
*[pkg/kv/kvserver/allocator.go, line 425 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59389#-MS5nUKwEzZf7kmjRU_Y:-MSQ3KBa8AOluFg9QIl-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ba4f15626b7bf06b62e5cdaa517896986aa3dde/pkg/kv/kvserver/allocator.go#L425)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: should we rename this to `liveVoters` and `deadVoters` to fit the rest of the variable naming in this function?
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/allocator.go, line 460 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59389#-MS5nMKY4igSPwyQ3b07:-MSQ3Mkr1dWrmE8XK_j5:b-hjc2ka) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ba4f15626b7bf06b62e5cdaa517896986aa3dde/pkg/kv/kvserver/allocator.go#L460)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we need to handle the `if haveNonVoters == neededNonVoters && len(deadNonVoters) > 0 {` case? In fact, do we need a `AllocatorReplaceDeadNonVoter` action? Does that fall into your future change to rebalance non-voting replicas?
</blockquote></details>

Yup, replacement/rebalancing is coming after. I did not mean to leave that thing commented in here though. Fixed.
___
*[pkg/kv/kvserver/allocator.go, line 465 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59389#-MS5n4Dw1e83-cdDvscu:-MSQ3WZG5mG-5CXCpCVk:b-fkaemv) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ba4f15626b7bf06b62e5cdaa517896986aa3dde/pkg/kv/kvserver/allocator.go#L465)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Isn't this supposed to be a lower priority than `AllocatorRemoveDeadVoter`? Will that work if we have this check before the `if len(deadVoterReplicas) > 0 {` check?
</blockquote></details>

Woops, yes. The whole thing should to be structured in exactly the order of the priorities. I added a comment to this effect, both inside `computeAction` and above the definition of those priorities.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59389#-:-MSTokXODTsbyGQ6DyXh:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15 and @andreimatei)

___
*[pkg/kv/kvserver/allocator.go, line 465 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59389#-MS5n4Dw1e83-cdDvscu:-MSTodY9-XMBiGPA3qGU:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ba4f15626b7bf06b62e5cdaa517896986aa3dde/pkg/kv/kvserver/allocator.go#L465)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Woops, yes. The whole thing should to be structured in exactly the order of the priorities. I added a comment to this effect, both inside `computeAction` and above the definition of those priorities. 
</blockquote></details>

:thumbsup:

**Comment by aayushshah15** [comment]
TFTR!

I'm in no rush to merge this, I'll hold off until @andreimatei takes a took.

**Comment by aayushshah15** [comment]
Friendly bump.

**Review by andreimatei — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59389#-:-MT24Vc_3jEBA0B0fedh:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15 and @nvanbenschoten)

___
*[pkg/kv/kvserver/allocator.go, line 319 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/59389#-MT23n8b16QqfIs5wbZx:-MT23n8b16QqfIs5wbZy:b-o2bc8w) ([raw file](https://github.com/cockroachdb/cockroach/blob/026e90d1ff4a6d294d1972ba309a460859595b09/pkg/kv/kvserver/allocator.go#L319)):*
> ```Go
> // available for up-replication.
> //
> // If `num_voters` aren't explicitly configured in the zone config, all
> ```

it's unclear to me how this comment relates to this function. Is this essentially saying that if `zoneConfigNonVoterCount` is zero, then this method returns 0? Consider removing it.
___
*[pkg/kv/kvserver/allocator.go, line 427 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/59389#-MT22loq08quv_CaXnLy:-MT22loq08quv_CaXnLz:bwt8j1q) ([raw file](https://github.com/cockroachdb/cockroach/blob/026e90d1ff4a6d294d1972ba309a460859595b09/pkg/kv/kvserver/allocator.go#L427)):*
> ```Go
> 	// TODO(aayush): When haveVoters < neededVoters but we don't have quorum to
> 	// actually execute the addition of a new replica, we should be returning a
> 	// ALlocatorRangeUnavailable.
> ```

ALl/All

**Review by aayushshah15 — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59389#-:-MT3tDLrCX7_7g17141o:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15, @andreimatei, and @nvanbenschoten)

___
*[pkg/kv/kvserver/allocator.go, line 319 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/59389#-MT23n8b16QqfIs5wbZx:-MT3s0OCD4rlPw2tVi7K:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/026e90d1ff4a6d294d1972ba309a460859595b09/pkg/kv/kvserver/allocator.go#L319)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

it's unclear to me how this comment relates to this function. Is this essentially saying that if `zoneConfigNonVoterCount` is zero, then this method returns 0? Consider removing it.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/allocator.go, line 427 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/59389#-MT22loq08quv_CaXnLy:-MT3s2HSARj8xUrCw-qF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/026e90d1ff4a6d294d1972ba309a460859595b09/pkg/kv/kvserver/allocator.go#L427)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

ALl/All
</blockquote></details>

Done.

**Pull request merged**
