### PR TITLE
release-22.2: storage: introduce test-build assertion iterator

### PR DESCRIPTION
**Pull request by jbowens**
Backport #90859, #96685 and #97222 to mangle the buffers returned by Pebble
iterators to ensure MVCC and Cockroach code respects the Pebble iterator memory
lifetimes.

The RangeBounds() and RangeKeys() validity assertions are omitted, since 22.2
allowed these methods to be invoked on an invalid iterator or an iterator
positioned at a point key.

Epic: None
Release note: None
Release justification: Non-production code changes and fix to high-severity MVCC iterator bug.

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]
Thanks for catching this, `pointSynthesizingIter` changes LGTM. Mind running a quick `MVCCGet` benchmark to see the impact?

> Reviewed 19 of 19 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97572#-:-NP-YUBR85qEgfKMH0vF:b-2tfkdn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens and @RaduBerinde)

___
*[`pkg/storage/sst.go` line 615 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97572#-NP-Y0eUAAwSd6P9svNB:-NP-Y0eUAAwSd6P9svNC:b-4ay5vg) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfb711f507a891b116813e39604e65b7c08fc3cd/pkg/storage/sst.go#L615)):*
> ```Go
> 				// Re-retrieve the buffers.
> 				if extHasRange {
> 					extRangeKeys = extIter.RangeKeys()
> ```

Consider pulling this out to a separate commit for visibility.
___
*[`pkg/storage/pebbleiter/crdb_test_off.go` line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97572#-NP-Y5UAA2l3SNRcKvhz:-NP-Y5UAA2l3SNRcKvi-:b-8bxe4i) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfb711f507a891b116813e39604e65b7c08fc3cd/pkg/storage/pebbleiter/crdb_test_off.go#L19)):*
> ```Go
> 
> // Iterator redefines *pebble.Iterator.
> type Iterator = *pebble.Iterator
> ```

Nice trick to avoid dynamic dispatch here.

**Review by jbowens — COMMENTED** [review]
TFTR!

>  Mind running a quick MVCCGet benchmark to see the impact?

For sure. running them on my gceworker now

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97572#-:-NP3M53KAjQ2B47jZklv:bq2jqrm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @RaduBerinde)

___
*[`pkg/storage/sst.go` line 615 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97572#-NP-Y0eUAAwSd6P9svNB:-NP3Fp1hB4h5FjrGkQt_:b-48vilg) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfb711f507a891b116813e39604e65b7c08fc3cd/pkg/storage/sst.go#L615)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Consider pulling this out to a separate commit for visibility.
</blockquote></details>

Good call, done.

**Review by jbowens — COMMENTED** [review]
Impact looks not horrible:

```
name                                                                     old time/op    new time/op    delta
MVCCGet_Pebble/batch=false/versions=1/valueSize=8/numRangeKeys=0-24        6.29µs ± 1%    6.32µs ± 1%    ~     (p=0.310 n=5+5)
MVCCGet_Pebble/batch=false/versions=1/valueSize=8/numRangeKeys=1-24        11.5µs ± 1%    11.7µs ± 1%    ~     (p=0.056 n=5+5)
MVCCGet_Pebble/batch=false/versions=1/valueSize=8/numRangeKeys=100-24       133µs ± 1%     129µs ± 1%  -3.01%  (p=0.008 n=5+5)
MVCCGet_Pebble/batch=false/versions=10/valueSize=8/numRangeKeys=0-24       25.8µs ± 0%    25.7µs ± 1%    ~     (p=0.421 n=5+5)
MVCCGet_Pebble/batch=false/versions=10/valueSize=8/numRangeKeys=1-24       33.5µs ± 2%    34.0µs ± 2%  +1.38%  (p=0.032 n=5+5)
MVCCGet_Pebble/batch=false/versions=10/valueSize=8/numRangeKeys=100-24      115µs ± 1%     115µs ± 1%    ~     (p=0.690 n=5+5)
MVCCGet_Pebble/batch=false/versions=100/valueSize=8/numRangeKeys=0-24       107µs ± 2%     107µs ± 1%    ~     (p=0.421 n=5+5)
MVCCGet_Pebble/batch=false/versions=100/valueSize=8/numRangeKeys=1-24       117µs ± 1%     118µs ± 1%    ~     (p=0.222 n=5+5)
MVCCGet_Pebble/batch=false/versions=100/valueSize=8/numRangeKeys=100-24     209µs ± 4%     208µs ± 1%    ~     (p=1.000 n=5+5)
MVCCGet_Pebble/batch=true/versions=1/valueSize=8/numRangeKeys=0-24         3.82µs ± 1%    3.81µs ± 1%    ~     (p=0.571 n=5+5)
MVCCGet_Pebble/batch=true/versions=1/valueSize=8/numRangeKeys=1-24         6.19µs ± 1%    6.14µs ± 1%    ~     (p=0.310 n=5+5)
MVCCGet_Pebble/batch=true/versions=1/valueSize=8/numRangeKeys=100-24       69.2µs ± 0%    69.6µs ± 1%  +0.70%  (p=0.032 n=5+5)
MVCCGet_Pebble/batch=true/versions=10/valueSize=8/numRangeKeys=0-24        22.1µs ± 1%    22.0µs ± 2%    ~     (p=0.310 n=5+5)
MVCCGet_Pebble/batch=true/versions=10/valueSize=8/numRangeKeys=1-24        27.6µs ± 1%    27.8µs ± 1%    ~     (p=0.222 n=5+5)
MVCCGet_Pebble/batch=true/versions=10/valueSize=8/numRangeKeys=100-24      94.2µs ± 1%    95.7µs ± 1%  +1.57%  (p=0.032 n=5+5)
MVCCGet_Pebble/batch=true/versions=100/valueSize=8/numRangeKeys=0-24        105µs ± 1%     105µs ± 1%    ~     (p=0.841 n=5+5)
MVCCGet_Pebble/batch=true/versions=100/valueSize=8/numRangeKeys=1-24        114µs ± 1%     114µs ± 2%    ~     (p=0.841 n=5+5)
MVCCGet_Pebble/batch=true/versions=100/valueSize=8/numRangeKeys=100-24      188µs ± 3%     190µs ± 1%    ~     (p=0.310 n=5+5)
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97572#-:-NP3XK6KBTQ5U-uQ0HDM:b-5knrof)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @RaduBerinde)

**Comment by jbowens** [comment]
TFTR!

**Pull request merged**
