### PR TITLE
distsqlrun: outer distributed hash joins can use ON filter expressions correctly

### PR DESCRIPTION
**Pull request by jordanlewis**
This PR fixes a few bugs in distributed hash join and provides support for filter expressions in `OUTER JOIN`.

@knz I did not add memory accounting in the same place as before because I didn't see a nearby memory account in the code. There's probably something that I'm missing about that - please let me know what it is!

cc @irfansharif 

Updates #12550.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12558)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Thanks for fixing this! LGTM

Yeah, we don't yet have memory accounting plumbed through in distsql. I plan to work on that in the near future.

In r3: I think it will be confusing if we refer to the "on" condition as a filter (we should reserve that for WHERE conditions). In fact I think that confusion is exactly why the existing code does what it does :)  Could we change the comments and var names to say "on" (e.g. `failedOnCond`)?

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/distsqlrun/joinerbase.go, line 80 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12558#-KZdOnTgsjsYuozN2PDp:-KZdOnTgsjsYuozN2PDq:b-g7r5pb) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e12d8eacea1e3114b1e722b2e495dc24beddbc6/pkg/sql/distsqlrun/joinerbase.go#L80)):*
> ```Go
> // inner join and one of the given rows is nil).
> func (jb *joinerBase) render(lrow, rrow sqlbase.EncDatumRow) (sqlbase.EncDatumRow, error) {
> 	lnil := lrow == nil
> ```

[nit] this whole switch could be replaced with
```
if lrow == nil {
  if jb.joinType == innerJoin || jb.joinType == leftOuter { return nil, nil }
  lrow = jb.emptyLeft
}
if rrow == nil {
  if jb.joinType == innerJoin || jb.joinType == rightOuter { return nil, nil }
  rrow = jb.emptyRight
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12558#-:-KZdPvumFZzFLco_Enta:b5vzfy1)*

**Comment by jordanlewis** [comment]
TFTR! I replaced the "filter" wording with "onCond" everywhere it seemed appropriate.

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/distsqlrun/joinerbase.go, line 80 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12558#-KZdOnTgsjsYuozN2PDp:-KZe1UIhFW9HEjDU6kyh:b-wmhd8j) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e12d8eacea1e3114b1e722b2e495dc24beddbc6/pkg/sql/distsqlrun/joinerbase.go#L80)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] this whole switch could be replaced with
```
if lrow == nil {
  if jb.joinType == innerJoin || jb.joinType == leftOuter { return nil, nil }
  lrow = jb.emptyLeft
}
if rrow == nil {
  if jb.joinType == innerJoin || jb.joinType == rightOuter { return nil, nil }
  rrow = jb.emptyRight
}
```
</blockquote></details>

Nice -done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12558#-:-KZe4vR8QEjjdosRS-rr:b-rbj93c)*

**Comment by RaduBerinde** [comment]
:lgtm: Thanks!

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12558#-:-KZfqWEDCFbZ0DC3hlBD:b-g2a5fb)*

**Comment by knz** [comment]
:lgtm:
The remark about  "filter" not being appropriately named applies to joinNode too. If you could file a follow-up issue about this that would be swell.

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 4 of 4 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12558#-:-KZg3rPCxoywK7ht4MPs:bu2fj6s)*

**Pull request merged**
