### PR TITLE
kv: finish and enable parallel commits

### PR DESCRIPTION
**Pull request by nvb**
The majority of this PR is addressing the final work item for parallel commits - splitting pre-commit QueryIntents from parallel committing EndTransaction requests.

If a batch is performing a parallel commit and the transaction has previously pipelined writes that have yet to be proven successful then the EndTransaction request will be preceded by a series of QueryIntent requests (see txn_pipeliner.go). Before evaluating, each of these QueryIntent requests will grab latches and wait for their corresponding write to finish. This is how the QueryIntent requests synchronize with the write they are trying to verify.

If these QueryIntents remained in the same batch as the EndTransaction request then they would force the EndTransaction request to wait for the previous write before evaluating itself. This "pipeline stall" would effectively negate the benefit of the parallel commit. To avoid this, we make sure that these "pre-commit" QueryIntent requests are split from and issued concurrently with the rest of the parallel commit batch.

With this complete, parallel commits is then able to be enabled.

### Benchmarks

The original benchmarking for parallel commits was presented in https://github.com/cockroachdb/cockroach/pull/35165#issue-255582656.

One of my recent experiments was to run the `indexes` benchmark at varying numbers of secondary indexes on a 3-node geo-distributed cluster. Below are plots with and without parallel commits enabled. We can see that without parallel commits, the introduction of the first secondary index doubles p50 latency and reduces throughput (at a fixed concurrency) by 56%. With parallel commits, the introduction of the secondary index has almost no noticeable effect on p50 latency and reduces throughput by only 29%.

Secondary Indexes Throughput With Parallel Commits (1)

Secondary Indexes p50 Latency With Parallel Commits (1)

I expect I'll polish off more comparison benchmarks over the next few weeks to further demonstrate the effect of parallel commits.

### CODE REVIEW

**Review by tbg — APPROVED** [review]
:lgtm:

Can you run the tests a few times to weed out any obvious flakes?

> Reviewed 3 of 3 files at r1, 9 of 9 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37719#-:-LfUgVpL668vnQv8HwYE:b-jphbxu)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/dist_sender.go, line 809 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37719#-LfU3hrh-z-S-cL9qaKY:-LfU3hriDdzw4A3cLKmr:b-j4le1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/04ef179dfc95d9cbf74e455384dac5e90c66ea18/pkg/kv/dist_sender.go#L809)):*
> ```Go
> // issued concurrently with the rest of the parallel commit batch.
> func (ds *DistSender) divideAndSendParallelCommit(
> 	ctx context.Context, ba roachpb.BatchRequest, rs roachpb.RSpan, batchIdx int,
> ```

Explain `batchIdx`.
___
*[pkg/kv/dist_sender.go, line 838 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37719#-LfU3LeF0BuwpBSNZbN5:-LfU365n-zlZwd63lP6G:b9m5fw1) ([raw file](https://github.com/cockroachdb/cockroach/blob/04ef179dfc95d9cbf74e455384dac5e90c66ea18/pkg/kv/dist_sender.go#L838)):*
Isn't it more specifically

> this method if they end up in the same range as the EndTransaction (or if the batch rewrites previously written keys)
___
*[pkg/kv/dist_sender.go, line 861 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37719#-LfU4A1k9ub-NmGOwmpv:-LfU4A1k9ub-NmGOwmpw:b-joxw2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/04ef179dfc95d9cbf74e455384dac5e90c66ea18/pkg/kv/dist_sender.go#L861)):*
> ```Go
> 		positions := make([]int, len(qiBa.Requests))
> 		for i := swapIdx; i < lastIdx; i++ {
> 			positions[i-swapIdx] = i
> ```

Mind adding a comment (with a small example) here?
___
*[pkg/kv/dist_sender.go, line 863 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37719#-LfU4MtdA-Igx3LB5n8a:-LfU4Mte0s_SrfFCJk_t:b-7o8qky) ([raw file](https://github.com/cockroachdb/cockroach/blob/04ef179dfc95d9cbf74e455384dac5e90c66ea18/pkg/kv/dist_sender.go#L863)):*
> // Send the batch with withCommit=true since it will be inflight concurrently with the EndTransaction batch below.
___
*[pkg/kv/dist_sender.go, line 901 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37719#-LfU54Bo0svtiXbAbMER:-LfU54Bo0svtiXbAbMES:b-qdyqiv) ([raw file](https://github.com/cockroachdb/cockroach/blob/04ef179dfc95d9cbf74e455384dac5e90c66ea18/pkg/kv/dist_sender.go#L901)):*
> ```Go
> 		qiPErr.UpdateTxn(ba.Txn)
> 		maybeSwapErrorIndex(qiPErr, swapIdx, lastIdx)
> 		pErr := roachpb.NewError(&roachpb.MixedSuccessError{Wrapped: qiPErr})
> ```

I thought we wanted to get rid of `MixedSuccessError`. Still the plan and how will the error be handled today (after this PR)?
___
*[pkg/kv/dist_sender_server_test.go, line 2481 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37719#-LfUf7vV-zetx5HFMUZj:-LfUf7vW-WFmCiVXia7H:b-237qob) ([raw file](https://github.com/cockroachdb/cockroach/blob/04ef179dfc95d9cbf74e455384dac5e90c66ea18/pkg/kv/dist_sender_server_test.go#L2481)):*
> a mixed
___
*[pkg/kv/dist_sender_test.go, line 2100 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37719#-LfUflUV4CVZbg9ECFvy:-LfUflUV4CVZbg9ECFvz:b-eqjzcq) ([raw file](https://github.com/cockroachdb/cockroach/blob/04ef179dfc95d9cbf74e455384dac5e90c66ea18/pkg/kv/dist_sender_test.go#L2100)):*
> ```Go
> 			et:        roachpb.Key("b"),
> 			parCommit: true,
> 			exp:       [][]roachpb.Method{{roachpb.Put, roachpb.Put}, {roachpb.EndTransaction}},
> ```

Can you tell from this that it was sent in parallel? I can't. Shouldn't I be able to tell?
___
*[pkg/kv/dist_sender_test.go, line 2140 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37719#-LfUg0hN3q6XAPmNXAfv:-LfUg0hN3q6XAPmNXAfw:bktmeow) ([raw file](https://github.com/cockroachdb/cockroach/blob/04ef179dfc95d9cbf74e455384dac5e90c66ea18/pkg/kv/dist_sender_test.go#L2140)):*
> ```Go
> 			et:        roachpb.Key("a1"),
> 			parCommit: true,
> 			exp:       [][]roachpb.Method{{roachpb.EndTransaction}, {roachpb.Put, roachpb.Put}},
> ```

ditto. Maybe this is ok?
___
*[pkg/kv/txn_interceptor_committer.go, line 159 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37719#-LfU2Xxu6m16ejHvTVYu:-LfU2Xxu6m16ejHvTVYv:b5ftt79) ([raw file](https://github.com/cockroachdb/cockroach/blob/7009f8750d5c3af32d5c43011869048ea7a311ae/pkg/kv/txn_interceptor_committer.go#L159)):*
> ```Go
> 		// flag based on whether any of previously declared in-flight writes
> 		// in this batch overlap with each other. This will have (rare) false
> 		// negatives when the in-flight writes overlap with existing intent
> ```

I know this is just a revert, but if someone went and disabled parallel commits via the cluster setting, don't they need this removed code?

**Review by nvb — COMMENTED** [review]
TFTR!

> Can you run the tests a few times to weed out any obvious flakes?

I stressed both of them. They look stable.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37719#-:-LfVIBCF8Yos2QSaHn1B:b-bwogxf)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @tbg)

___
*[pkg/kv/dist_sender.go, line 809 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37719#-LfU3hrh-z-S-cL9qaKY:-LfVDeAu140a3MP29SC5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/04ef179dfc95d9cbf74e455384dac5e90c66ea18/pkg/kv/dist_sender.go#L809)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Explain `batchIdx`.
</blockquote></details>

Done.
___
*[pkg/kv/dist_sender.go, line 838 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37719#-LfU3LeF0BuwpBSNZbN5:-LfVDmPe8PCQ_cOS8Lmn:b-66hl91) ([raw file](https://github.com/cockroachdb/cockroach/blob/04ef179dfc95d9cbf74e455384dac5e90c66ea18/pkg/kv/dist_sender.go#L838)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Isn't it more specifically

> this method if they end up in the same range as the EndTransaction (or if the batch rewrites previously written keys)
</blockquote></details>

Well these are only ever present if the batch is rewriting previously written keys, which is why they are rare. Them ending on the same range as the EndTransaction doesn't really matter - either way, some write is being slowed down.

I added a note that points to `txnPipeliner.chainToInFlightWrites`.
___
*[pkg/kv/dist_sender.go, line 861 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37719#-LfU4A1k9ub-NmGOwmpv:-LfVGCuq87xY29_7POy3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/04ef179dfc95d9cbf74e455384dac5e90c66ea18/pkg/kv/dist_sender.go#L861)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Mind adding a comment (with a small example) here?
</blockquote></details>

Done.
___
*[pkg/kv/dist_sender.go, line 863 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37719#-LfU4MtdA-Igx3LB5n8a:-LfVGKJx-k7Aq_djASzf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/04ef179dfc95d9cbf74e455384dac5e90c66ea18/pkg/kv/dist_sender.go#L863)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

> // Send the batch with withCommit=true since it will be inflight concurrently with the EndTransaction batch below.
</blockquote></details>

Done.
___
*[pkg/kv/dist_sender.go, line 901 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37719#-LfU54Bo0svtiXbAbMER:-LfVGKiICl66-a4yLaMo:b-bpxygy) ([raw file](https://github.com/cockroachdb/cockroach/blob/04ef179dfc95d9cbf74e455384dac5e90c66ea18/pkg/kv/dist_sender.go#L901)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I thought we wanted to get rid of `MixedSuccessError`. Still the plan and how will the error be handled today (after this PR)?
</blockquote></details>

Yes, that's still the plan and nothing we did with parallel commits should cause issues (e.g. staging a transaction record is idempotent). For now, though, we can't get rid of it. This `MixedSuccessError` will be handled exactly like any other after this PR.
___
*[pkg/kv/dist_sender_server_test.go, line 2481 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37719#-LfUf7vV-zetx5HFMUZj:-LfVGlzIDA1TaHciHBUS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/04ef179dfc95d9cbf74e455384dac5e90c66ea18/pkg/kv/dist_sender_server_test.go#L2481)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

> a mixed
</blockquote></details>

Done.
___
*[pkg/kv/dist_sender_test.go, line 2100 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37719#-LfUflUV4CVZbg9ECFvy:-LfVH7sqBaWi89Sg2U1A:b-ggb3aa) ([raw file](https://github.com/cockroachdb/cockroach/blob/04ef179dfc95d9cbf74e455384dac5e90c66ea18/pkg/kv/dist_sender_test.go#L2100)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Can you tell from this that it was sent in parallel? I can't. Shouldn't I be able to tell?
</blockquote></details>

No, the goal wasn't to be able to tell here. Added a comment.
___
*[pkg/kv/dist_sender_test.go, line 2140 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37719#-LfUg0hN3q6XAPmNXAfv:-LfVHBC_3Q_k87lmUd9R:br4lgw4) ([raw file](https://github.com/cockroachdb/cockroach/blob/04ef179dfc95d9cbf74e455384dac5e90c66ea18/pkg/kv/dist_sender_test.go#L2140)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

ditto. Maybe this is ok?
</blockquote></details>

In this case, we can actually tell. Added a comment.
___
*[pkg/kv/txn_interceptor_committer.go, line 159 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37719#-LfU2Xxu6m16ejHvTVYu:-LfVDCaF-4F7IQDJiwg9:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/7009f8750d5c3af32d5c43011869048ea7a311ae/pkg/kv/txn_interceptor_committer.go#L159)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I know this is just a revert, but if someone went and disabled parallel commits via the cluster setting, don't they need this removed code?
</blockquote></details>

Good point, done.

**Review by tbg — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r4, 9 of 9 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37719#-:-LfVQubp5Ois0UvENgef:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by nvanbenschoten** [comment]
Bors failed because of https://github.com/cockroachdb/cockroach/issues/36812.

bors r+

**Pull request merged**
