### PR TITLE
optgen: add multi-variable bind expression

### PR DESCRIPTION
**Pull request by mgartner**
This commit adds a new optgen expression syntax for binding multiple
variables to the return values of a custom function. See the updated
documentation in this commit for more details.

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
This was a little Flex Friday project I did, mostly to learn more about Optgen. I'm not convinced we'll benefit all that much from this new syntax, but I thought I'd put up the PR incase others think it'll come in handy. The second commit shows how the new syntax can be used in an existing rule.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62683)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @mgartner, and @rytaft)

___
*[pkg/sql/opt/xform/rules/select.opt, line 122 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62683#-MWlCCDiBr4C5Mx-oxcn:-MWlCCDiBr4C5Mx-oxco:bkjxtvt) ([raw file](https://github.com/cockroachdb/cockroach/blob/963f428179853e99373f64cdffb313b0f89f5b21/pkg/sql/opt/xform/rules/select.opt#L122)):*
> ```
>     $filters:* &
>         $(
>             leftFilter
> ```

Would be really cool to have something like this, but this particular syntax is too "magic". It hides the "ok" return value and it's hard to understand what's going on. Maybe @andy-kimball has other ideas for this kind of syntax?

Maybe a new "with" keyword:
```
& with $ok, $leftFilter, $rightFilter, $itemToReplace:(SplitDisjunction ..) $ok
```

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62683)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @rytaft)

___
*[pkg/sql/opt/xform/rules/select.opt, line 122 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62683#-MWlCCDiBr4C5Mx-oxcn:-MWligjl6aLWl55IhinI:bcbaiqm) ([raw file](https://github.com/cockroachdb/cockroach/blob/963f428179853e99373f64cdffb313b0f89f5b21/pkg/sql/opt/xform/rules/select.opt#L122)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Would be really cool to have something like this, but this particular syntax is too "magic". It hides the "ok" return value and it's hard to understand what's going on. Maybe @andy-kimball has other ideas for this kind of syntax?

Maybe a new "with" keyword:
```
& with $ok, $leftFilter, $rightFilter, $itemToReplace:(SplitDisjunction ..) $ok
```
</blockquote></details>

I'm totally open to syntax suggestions - didn't put a whole lot of thought into that yet, was just experimenting.

`let` is a common keyword in s-expression languages for variable binding, so we could use something like that? E.g., `& (let $leftFilter $rightFilter $itemToReplace $ok; $ok)`.

Utilizing `{` and `}` is another option, given that these don't currently have uses AFAIK.

**Review by rytaft — COMMENTED** [review]
Cool!

> Reviewed 13 of 13 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62683#-:-MWzv6yg2GlGboV1w1LY:b-89q77x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @mgartner)

___
*[pkg/sql/opt/optgen/lang/compiler.go, line 520 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62683#-MWzs06JEC8rNibbHABI:-MWzs06JEC8rNibbHABJ:b21bso7) ([raw file](https://github.com/cockroachdb/cockroach/blob/feeeabe5e82daece8cdf69c714625fb1aed6a441/pkg/sql/opt/optgen/lang/compiler.go#L520)):*
> ```Go
> 	// Ensure that binding labels are unique.
> 	for _, label := range bind.Labels {
> 		// label := l.(*StringExpr)
> ```

Is this dead code?
___
*[pkg/sql/opt/xform/rules/select.opt, line 122 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62683#-MWlCCDiBr4C5Mx-oxcn:-MWztYhb4ueJUX7C2k_D:bo5iqkw) ([raw file](https://github.com/cockroachdb/cockroach/blob/963f428179853e99373f64cdffb313b0f89f5b21/pkg/sql/opt/xform/rules/select.opt#L122)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I'm totally open to syntax suggestions - didn't put a whole lot of thought into that yet, was just experimenting.

`let` is a common keyword in s-expression languages for variable binding, so we could use something like that? E.g., `& (let $leftFilter $rightFilter $itemToReplace $ok; $ok)`.

Utilizing `{` and `}` is another option, given that these don't currently have uses AFAIK.
</blockquote></details>

Agree that we shouldn't hide the `$ok` value. It seems like this might also be useful in contexts where we don't want to always return `$ok`, and it's unfortunate that this forces the function to return an extra value. Either of the `with` or `let` ideas sound good to me...

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62683)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @mgartner)

___
*[pkg/sql/opt/xform/rules/select.opt, line 122 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62683#-MWlCCDiBr4C5Mx-oxcn:-MX-MjAI6NfMf_Jp91bQ:b4behp4) ([raw file](https://github.com/cockroachdb/cockroach/blob/963f428179853e99373f64cdffb313b0f89f5b21/pkg/sql/opt/xform/rules/select.opt#L122)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Agree that we shouldn't hide the `$ok` value. It seems like this might also be useful in contexts where we don't want to always return `$ok`, and it's unfortunate that this forces the function to return an extra value. Either of the `with` or `let` ideas sound good to me...
</blockquote></details>

Initially I though that this type of binding would only be allowed as a child in a boolean-AND `&` expression, so the binding expression itself would have to evaluate to a boolean.

But I guess it doesn't have to be that way. As an example, something like this might be possible (I'm using `{}` as this special syntax, but it could be `(With ...)` or `(Let ...)` or something else entirely):


```
(Select
    $input:*
    $filters:*
    {$filtersA $filtersB $ok}:(SplitFilters $filters) &
        $ok
)
=>
...
```

This would allow omitting `$ok` if the situation called for it:

```
(Select
    $input:*
    $filters:*
    {$filtersA $filtersB}:(SplitFilters $filters) &
        (NotEmpty $filtersA) &
        (NotEmpty $filtersB)
)
=>
...
```

But what about short-circuiting before executing the multi-variable binding. For the examples above, how would you perform `(SomeCondition $filters)` before executing `SplitFilters`? Something like this might work:

```
(Select
    $input:*
    $filters:* & (SomeCondition $filters)
    {$filtersA $filtersB}:(SplitFilters $filters) & 
         (NotEmpty $filtersA) &
         (NotEmpty $filtersB)
)
=>
...
````

**Review by andy-kimball — COMMENTED** [review]
I'm glad you're developing some expertise in `optgen`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62683#-:-MX5RGsd9oxZDNHDjCIC:b-976dsd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/xform/rules/select.opt, line 122 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62683#-MWlCCDiBr4C5Mx-oxcn:-MX5PqVs1O3vffej6YOW:b-kbmn55) ([raw file](https://github.com/cockroachdb/cockroach/blob/963f428179853e99373f64cdffb313b0f89f5b21/pkg/sql/opt/xform/rules/select.opt#L122)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Initially I though that this type of binding would only be allowed as a child in a boolean-AND `&` expression, so the binding expression itself would have to evaluate to a boolean.

But I guess it doesn't have to be that way. As an example, something like this might be possible (I'm using `{}` as this special syntax, but it could be `(With ...)` or `(Let ...)` or something else entirely):


```
(Select
    $input:*
    $filters:*
    {$filtersA $filtersB $ok}:(SplitFilters $filters) &
        $ok
)
=>
...
```

This would allow omitting `$ok` if the situation called for it:

```
(Select
    $input:*
    $filters:*
    {$filtersA $filtersB}:(SplitFilters $filters) &
        (NotEmpty $filtersA) &
        (NotEmpty $filtersB)
)
=>
...
```

But what about short-circuiting before executing the multi-variable binding. For the examples above, how would you perform `(SomeCondition $filters)` before executing `SplitFilters`? Something like this might work:

```
(Select
    $input:*
    $filters:* & (SomeCondition $filters)
    {$filtersA $filtersB}:(SplitFilters $filters) & 
         (NotEmpty $filtersA) &
         (NotEmpty $filtersB)
)
=>
...
````
</blockquote></details>

I think syntax-wise, I'd probably vote for `($var1 $var2)`, since when the formatter breaks across lines, it'd be nice to see the $ for each variable:
```
    $filters:* &
        (
            $leftFilter
            $rightFilter
            $itemToReplace
        ):(SplitDisjunction $scanPrivate $filters)
```

**Comment by mgartner** [comment]
I made some more progress today, and I think it's looking much better. I went with naming these expressions `Let` expressions because it's fairly common in s-expression languages and it won't be confused with a `memo.WithExpr`.

I've used `{` and `}` to wrap Let expressions, e.g. `{Let [$a $b $c $ok (SplitFilters $input $filters)] $ok}`, but I think it'd be cleaner if it was just parens, e.g. `(Let [$a $b $c $ok (SplitFilters $input $filters)] $ok)`. The parsing will be a bit more tricky to handle this, but it should be possible.

**Comment by RaduBerinde** [comment]
I looked around and LISP has a "multiple-value-bind" operator: http://clhs.lisp.se/Body/m_multip.htm
I like the more explicit "MultipleValueBind", it's more evident what is happening.

For us it would look like:
`(MultipleValueBind ($a $b $ok) (SomeFunc ..) $ok)`

I think this syntax would be pretty good if we could make it happen.

**Comment by rytaft** [comment]
I don't have a strong opinion between `Let` v. `MultipleValueBind` -- both seem fine to me, although I'm not convinced that they are needed (see my suggestion below). I don't love the fact that `(Let [$a $b $c $ok (SplitFilters $input $filters)] $ok)` makes it look like `(SplitFilters $input $filters)` is just one element in a slice.

I'm also not sure about having the return value `$ok` look like just another argument to `Let` or `MultipleValueBind`.

What about using something like the go syntax for `if ...; ok {`? Are we already using the semi colon for anything?

I liked the original idea of having the colon separate the list of return values from the function, similar to single value bind. So would something like this work: `... & ($a $b $ok):(SomeFunc ...); $ok & ...` or `... & {$a $b $ok}:(SomeFunc ...); $ok & ...`?

**Comment by mgartner** [comment]
Thanks for the feedback @RaduBerinde and @rytaft. I took it all into account and came up with this new iteration:

```
(Op
    $input:* &
        ($foo $bar $ok:(CustomFunc $input); $ok)
)
```

Here's some of the reasons I like this:

1. I liked the `MultipleValueBind` Lisp expression, but it's a bit verbose and I agree with @rytaft that it might be confusing because the variable reference at the end looks like an input to the expression, not the output.
2. Including `;` makes the expression's result more clear, especially so for people familiar with Go.
3. The surrounding `(` and `)` make it clear that its an encapsulated expression. The suggestions without some wrapping brackets, like `($a $b $ok):(SomeFunc ...); $ok` could be hard to read in complex expressions. Also, implementing sane optfmt behavior seems easier with surround parens.
4. I like that this syntax is pretty clear and concise, and doesn't require a special keyword in the language, like `Let`.

All that being said, I don't feel super strongly, so let me know if you have any qualms about this syntax and I'll give it another shot.

**Review by RaduBerinde — COMMENTED** [review]
It is beautiful!

The only suggestion I have is to use a comma between the variables: `($foo,$bar,$ok:(CustomFunc $input); $ok)`. Otherwise you can read `$ok:(CustomFunc $input)` as a separate thing which is confusing.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62683#-:-MXjKABABBsykUNYXqdn:b-hpq9t7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @RaduBerinde, and @rytaft)

**Review by mgartner — COMMENTED** [review]
> The only suggestion I have is to use a comma between the variables: ($foo,$bar,$ok:(CustomFunc $input); $ok). Otherwise you can read $ok:(CustomFunc $input) as a separate thing which is confusing.

Done. Do we like the `,` without a space? Is it too crowded?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62683#-:-MXmWUATCu82SnksF3ul:b-6vvf35)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @RaduBerinde, and @rytaft)

**Comment by mgartner** [comment]
I also added back in that original second commit that uses this new syntax for `SplitDisjunction`.

**Review by RaduBerinde — COMMENTED** [review]
:lgtm: 

> Done. Do we like the , without a space? Is it too crowded?

I don't feel strongly either way. Adding a space would be more consistent with the rest of the syntax, but may be less suggestive to the fact that we're dealing with them as a group.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62683#-:-MXmZaxBEYZNc-zPcArI:brduhs7)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner, @RaduBerinde, and @rytaft)

**Review by mgartner — COMMENTED** [review]
> I don't feel strongly either way. Adding a space would be more consistent with the rest of the syntax, but may be less suggestive to the fact that we're dealing with them as a group.

Unless @rytaft is in favor of a space, let's leave as-is for now. If we ever change our minds it'd just require an `optfmt` change - the optgen parser accepts either format.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62683#-:-MXn0_MKDnAU7szocxOr:b-b8rrt2)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

___
*[pkg/sql/opt/optgen/lang/compiler.go, line 520 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62683#-MWzs06JEC8rNibbHABI:-MXn0VG75nvC2w5SjcHO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/feeeabe5e82daece8cdf69c714625fb1aed6a441/pkg/sql/opt/optgen/lang/compiler.go#L520)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Is this dead code?
</blockquote></details>

Done.

**Comment by mgartner** [comment]
Ahh a last minute dissenter... Who do you think you are @andy-kimball, the creator of this language? 😆 

I originally preferred a more s-expr style syntax, hence my earlier suggestions. But the Go-like suggestion from @rytaft has some merits which I described above, and it has grown on me. I like both for various reasons...

It sounds like we all have strong, but loosely held opinions. I can be the tie-breaker on this, in which case I'll probably leave as-is, but I'll give you all another day or so to convince me one way or another.

**Review by rytaft — APPROVED** [review]
Lol 😂 

I do like that @andy-kimball's suggestion seems a bit more consistent with existing optgen syntax. But I'd also be content with the current iteration. I think it's your call, @mgartner 🙂

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62683#-:-MXnziVd-GLpCrVDg-s1:bz29dva)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

**Comment by mgartner** [comment]
Ok, `(Let ($foo $bar $ok):(MyCustomFunc $input) $ok)` it is. **_Let_**'s stick to the s-expr style as much as possible.

**Comment by RaduBerinde** [comment]
`(Let 's do this)`!!

**Review by rytaft — APPROVED** [review]
🎉

> Reviewed 1 of 16 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62683#-:-MYBzGRa-cgGtHXBn7Zm:b44uc2)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/optgen/lang/doc.go, line 176 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/62683#-MYBygrcCI3P70XPLad9:-MYBygrcCI3P70XPLadA:b-9aukje) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd21115a346c3b6fe24770809f05cf7e84c2459c/pkg/sql/opt/optgen/lang/doc.go#L176)):*
> ```Go
> custom function with multiple return values. This expression consists of two
> elements, a binding and a result. The binding includes a list of variables to
> bind followed by a custom function to produce the bind values. The result is as
> ```

nit: as -> a

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62683)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

___
*[pkg/sql/opt/optgen/lang/doc.go, line 176 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/62683#-MYBygrcCI3P70XPLad9:-MYC5Dg68mrI5UdNenG3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd21115a346c3b6fe24770809f05cf7e84c2459c/pkg/sql/opt/optgen/lang/doc.go#L176)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: as -> a
</blockquote></details>

Done.

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
