### PR TITLE
sql: allow VIEW and SEQUENCEs for multi-region databases

### PR DESCRIPTION
**Pull request by otan**
Refs #61382 -- missing materialized views.

Release note (bug fix): Allow VIEWs and SEQUENCEs in multi-region
databases. They will have REGIONAL BY TABLE set.

### CODE REVIEW

**Review by ajstorm — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62050)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/catalog/tabledesc/validate.go, line 1223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62050#-MVupZ9uEPhGkRM16DJe:-MVupZ9v5HR0tt2XxUth:b-hzkos9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4cf4399cb00ebf48566b4a8eab574ab47e98152/pkg/sql/catalog/tabledesc/validate.go#L1223)):*
> ```Go
> 	}
> 
> 	s := tree.NewFmtCtx(tree.FmtSimple)
> ```

Nit: Why do this outside of the `!db.IsMultiRegion() ` block?  Will we ever need this in the non-MR case?

**Review by arulajmani — COMMENTED** [review]
Is it correct for sequences to not have locality set? Wouldn't they behave like "regional tables homed in the primary region", by virtue of the database zone configs, so shouldn't there be a locality config reflecting as such?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62050#-:-MVwKaUsB1NIcBiS7wud:bvhegt8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

**Comment by otan** [comment]
> Is it correct for sequences to not have locality set? Wouldn't they behave like "regional tables homed in the primary region", by virtue of the database zone configs, so shouldn't there be a locality config reflecting as such?

I think it works either way. Actually, I may be a fan of setting the locality so I'll switch it around.

**Comment by otan** [comment]
probably worth for another look @ajstorm !

**Review by ajstorm — APPROVED** [review]
A few cleanup comments.  I'm not in love with passing the flag around everywhere, so if we can fix that, more 🍌🍌🍌🍌🍌🍌🍌

> Reviewed 14 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62050#-:-MW-dAyz04LkOcvbVm6O:b-2j4hay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @otan)

___
*[pkg/sql/create_sequence.go, line 98 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62050#-MW-bu6Q-gjqc-0TzBTJ:-MW-bu6Q-gjqc-0TzBTK:btabe4i) ([raw file](https://github.com/cockroachdb/cockroach/blob/f70d705f58fc3d631e13be4bbfe34c5545cc0e52/pkg/sql/create_sequence.go#L98)):*
> ```Go
> 	opts tree.SequenceOptions,
> 	jobDesc string,
> 	isMultiRegion bool,
> ```

We have the dbDesc here.  Can't we key off of that for the MR check?
___
*[pkg/sql/create_sequence.go, line 187 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62050#-MW-cK04CwGObEsPGNJz:-MW-cK04CwGObEsPGNK-:bavmd54) ([raw file](https://github.com/cockroachdb/cockroach/blob/f70d705f58fc3d631e13be4bbfe34c5545cc0e52/pkg/sql/create_sequence.go#L187)):*
> ```Go
> 	persistence tree.Persistence,
> 	params *runParams,
> 	isMultiRegion bool,
> ```

With the parentID, can we not pull the database descriptor here and use that to determine if the sequence should be made MR?  Saves having to pass this flag everywhere.
___
*[pkg/sql/create_view.go, line 303 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62050#-MW-cdue-66uyitkZRXM:-MW-cdue-66uyitkZRXN:blu5jd6) ([raw file](https://github.com/cockroachdb/cockroach/blob/f70d705f58fc3d631e13be4bbfe34c5545cc0e52/pkg/sql/create_view.go#L303)):*
> ```Go
> 	evalCtx *tree.EvalContext,
> 	persistence tree.Persistence,
> 	isMultiRegion bool,
> ```

Same comment about pulling the db descriptor down here.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62050)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @ajstorm)

___
*[pkg/sql/create_sequence.go, line 187 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62050#-MW-cK04CwGObEsPGNJz:-MW0anzg8rfcBUeLW36b:bgcsyih) ([raw file](https://github.com/cockroachdb/cockroach/blob/f70d705f58fc3d631e13be4bbfe34c5545cc0e52/pkg/sql/create_sequence.go#L187)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

With the parentID, can we not pull the database descriptor here and use that to determine if the sequence should be made MR?  Saves having to pass this flag everywhere.
</blockquote></details>

we don't have a transaction, and e.g. restore doesn't give you one.
___
*[pkg/sql/create_view.go, line 303 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62050#-MW-cdue-66uyitkZRXM:-MW0auKh6UybVPSns0gY:bj8bld6) ([raw file](https://github.com/cockroachdb/cockroach/blob/f70d705f58fc3d631e13be4bbfe34c5545cc0e52/pkg/sql/create_view.go#L303)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Same comment about pulling the db descriptor down here.
</blockquote></details>

same as above.
___
*[pkg/sql/catalog/tabledesc/validate.go, line 1223 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62050#-MVupZ9uEPhGkRM16DJe:-MVwOiCx9TAvI2EYmJhr:b-onofff) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4cf4399cb00ebf48566b4a8eab574ab47e98152/pkg/sql/catalog/tabledesc/validate.go#L1223)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: Why do this outside of the `!db.IsMultiRegion() ` block?  Will we ever need this in the non-MR case?
</blockquote></details>

no, but this already early exits in the if statement above if it is not multi-region.

**Comment by otan** [comment]
bors r=ajstorm

**Pull request merged**
