### PR TITLE
sql: row fetcher optimizations

### PR DESCRIPTION
**Pull request by RaduBerinde**
### sql: optimize the rowfetcher per-column overhead for unneeded columns

In a profile of a TPC-H `COUNT(*)` (single node), 7-9% was the map lookup of
column IDs. This lookup happens even for columns that are not needed.

Optimizing this by implementing a `FastIntSet` primitive which uses bits for
small IDs. We now store the needed column IDs in a `FastIntSet` which we can
consult first.

This shaved a couple of seconds from the query (21-22s to 18-19s).

### sql: remove row fetcher overhead due to log.V

In the profile of a large `COUNT(*)` query, the `log.V` calls in `RowFetcher`
add up to about 4%. Changing these to depend on a constant flag so they are left
out of normal builds.

### CODE REVIEW

**Comment by irfansharif** [comment]
nice PR!

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/util/fast_int_set.go, line 88 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16446#-KmPjZ3RaQUg1hiSiTr4:-KmPjZ3RaQUg1hiSiTr5:ba5ja3i) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a2fbb1f2d99513a502be6c84ca57e5c24e3cdff/pkg/util/fast_int_set.go#L88)):*
> ```Go
> }
> 
> func (s *FastIntSet) String() string {
> ```

This will return `")"` for empty sets, we can do `buf.WriteByte('(')` outside the loop and not have to re-assign `delim` inside (we can make do with `delim` altogether too).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16446#-:-KmPlbJzkj9Tna2tSvcy:b-xsrjrz)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/util/fast_int_set.go, line 88 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16446#-KmPjZ3RaQUg1hiSiTr4:-KmRS165dXioheSbcgDk:b8gj3mz) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a2fbb1f2d99513a502be6c84ca57e5c24e3cdff/pkg/util/fast_int_set.go#L88)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

This will return `")"` for empty sets, we can do `buf.WriteByte('(')` outside the loop and not have to re-assign `delim` inside (we can make do with `delim` altogether too).
</blockquote></details>

Good catch, fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16446)*

**Comment by arjunravinarayan** [comment]
:lgtm:

Do you have a copy of the TPC-H profile? It would be good to triage it for more low hanging fruit. This is excellent!

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16446#-:-KmRxJRw4f6V4J-64NdQ:b-dxmkmu)*

**Comment by RaduBerinde** [comment]
TFTR!  I'm attaching a profile with the fastint change but not the log.V one. I have more optimizations in the pipeline though (e.g. removing the 3.7% makemap under ProcessKV).

[profile tpch fastintset.pdf](https://github.com/cockroachdb/cockroach/files/1068714/profile.tpch.fastintset.pdf)

**Comment by danhhz** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/sqlbase/rowfetcher.go, line 102 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16446#-KmRzSgD2Nb21VylccVa:-KmRzSgD2Nb21VylccVb:bpw8zlp) ([raw file](https://github.com/cockroachdb/cockroach/blob/0641e14bbc77bc19b9a3717d6ad15b0f366fbdac/pkg/sql/sqlbase/rowfetcher.go#L102)):*
> ```Go
> }
> 
> const debugRowFetch = false
> ```

Comment on why we do this instead of log.V, plz

---

*[pkg/util/fast_int_set.go, line 25 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16446#-KmRyjjwnK7GoSmd5nWa:-KmRyjjx9JORvJwj1_8y:bfs5shs) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a2fbb1f2d99513a502be6c84ca57e5c24e3cdff/pkg/util/fast_int_set.go#L25)):*
> ```Go
> 
> // FastIntSet keeps track of a set of integers. It is very fast when the values
> // are small.
> ```

Mention that this isn't threadsafe, plz

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16446#-:-KmRzX8uICmh1R11evup:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/sqlbase/rowfetcher.go, line 102 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16446#-KmRzSgD2Nb21VylccVa:-KmS-H3ZD3t5rP-UEkTL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0641e14bbc77bc19b9a3717d6ad15b0f366fbdac/pkg/sql/sqlbase/rowfetcher.go#L102)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Comment on why we do this instead of log.V, plz
</blockquote></details>

Done.

---

*[pkg/util/fast_int_set.go, line 25 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16446#-KmRyjjwnK7GoSmd5nWa:-KmS-F04ImOQSsK7a768:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a2fbb1f2d99513a502be6c84ca57e5c24e3cdff/pkg/util/fast_int_set.go#L25)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Mention that this isn't threadsafe, plz
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16446)*

**Pull request merged**
