### PR TITLE
release-21.2: rangefeed,storage: use time-bound iterator for with-diff catchup scan

### LINKED ISSUE #78974: storage: expand TBI support to include with diff
TBI has been a huge help for changefeed users, as it significantly improves the performance of scans. This is especially important during times of instability or at a high scale of data. For example: When resuming a changefeed after 20 hrs of interrupted service, turning off `with diff` and using TBI caused catch up scan [to go from](https://cockroachlabs.slack.com/archives/C9TGBJB44/p1646785059137259) 10 hours to 3 seconds for one workload. This was incredibly important to restore service quickly and ensure system stability during catch up. TBI support is one of the reasons we recommend anyone using changefeeds in production upgrade to 21.2 ([example](https://cockroachlabs.slack.com/archives/C01MUGJFWTE/p1631047921006500)).

Unfortunately, changefeed users who use the `WITH diff` option do not benefit from this performance improvement. This came up recently with a prospect, who needs `WITH diff` but was looking for similar performance improvements.

---------

From MVCCIncrementalIterator:  
// TODO(ssd): The withDiff option requires us to iterate over
// values arbitrarily in the past so that we can populate the
// previous value of a key. This is possible since the
// IncrementalIterator has a non-timebound iterator
// internally, but it is not yet implemented.

Crude implementation started here: https://github.com/cockroachdb/cockroach/pull/69191

Jira issue: CRDB-14469

### PR DESCRIPTION
**Pull request by jayshrivastava**
Backport of https://github.com/cockroachdb/cockroach/pull/80591

/cc https://github.com/orgs/cockroachdb/teams/release

Release note: None
Epic: None

### CODE REVIEW

**Comment by jayshrivastava** [comment]
cc @shermanCRL

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
looks good

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90565#-:-NFTj9FS3NGPyH-rUsMl:b-47fafm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava)

___
*[`pkg/kv/kvserver/rangefeed/catchup_scan.go` line 178 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90565#-NFTiaBw9Z3NiSUMOPwi:-NFTiaBx4jTBDOckMNBI:b-luuq09) ([raw file](https://github.com/cockroachdb/cockroach/blob/4128b60da65da74474598acbf80bc30139797075/pkg/kv/kvserver/rangefeed/catchup_scan.go#L178)):*
> ```Go
> 					return errors.Wrap(err, "iterating to provisional value for intent")
> 				} else if !ok {
> 					return errors.Errorf("expected provisional value for intent")
> ```

Looks like this is where we have picked up some additional changes. Does the `CatchUpIterator.CatchUpScan` method now exactly match in terms of code the method after https://github.com/cockroachdb/cockroach/pull/80591 was merged? I'd like to scrutinize it more carefully if it does not.
___
*[`pkg/storage/mvcc_incremental_iterator_test.go` line 731 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90565#-NFThWHz3ncOvVE4tIKm:-NFThWHz3ncOvVE4tIKn:bkkzg5m) ([raw file](https://github.com/cockroachdb/cockroach/blob/4128b60da65da74474598acbf80bc30139797075/pkg/storage/mvcc_incremental_iterator_test.go#L731)):*
> ```Go
> 					nextFunc()
> 					expectKeyValue(t, iter, kv2_1_1)
> 					//>>>>>>> 5a2c3e90c7 (rangefeed,storage: use time-bound iterator for with-diff catchup scan)
> ```

stray merge conflict comment?

**Review by jayshrivastava — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90565)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/rangefeed/catchup_scan.go` line 178 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90565#-NFTiaBw9Z3NiSUMOPwi:-NFUESpe-y0gVGQzGwCm:b-hhg089) ([raw file](https://github.com/cockroachdb/cockroach/blob/4128b60da65da74474598acbf80bc30139797075/pkg/kv/kvserver/rangefeed/catchup_scan.go#L178)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Looks like this is where we have picked up some additional changes. Does the `CatchUpIterator.CatchUpScan` method now exactly match in terms of code the method after https://github.com/cockroachdb/cockroach/pull/80591 was merged? I'd like to scrutinize it more carefully if it does not.
</blockquote></details>

It matches `CatchUpIterator.CatchUpScan` in your `with_diff` branch exactly, but it differs from `master`.
___
*[`pkg/storage/mvcc_incremental_iterator_test.go` line 731 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90565#-NFThWHz3ncOvVE4tIKm:-NFUERcF83aZUHbOKrKL:bss4a1y) ([raw file](https://github.com/cockroachdb/cockroach/blob/4128b60da65da74474598acbf80bc30139797075/pkg/storage/mvcc_incremental_iterator_test.go#L731)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

stray merge conflict comment?
</blockquote></details>

Removed!

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90565#-:-NFUOqYrAXbjFWtUPesd:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jayshrivastava)

**Comment by jayshrivastava** [comment]
TYFR!

**Comment by rickystewart** [comment]
bors r-

No need to use `bors` for backports.

**Comment by shermanCRL** [comment]
Ready to merge here?

**Comment by jayshrivastava** [comment]
@shermanCRL There's a discussion going on in https://github.com/cockroachdb/cockroach/pull/80591 about the results. I don't know if that means we should void this backport. @ajwerner do you think this fine to backport?

**Comment by ajwerner** [comment]
I have no concerns

**Pull request merged**
