### PR TITLE
opt: improve the partial index label in EXPLAIN

### PR DESCRIPTION
**Pull request by RaduBerinde**
This commit moves the "partial index" mention next to the name of the
index.

Release note: None

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
:lgtm: Nice!

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51839#-:-MCwUSax3bj5V63F-q_v:b-8gk8uj)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by RaduBerinde** [comment]
This has got to be a record low for the ratio `<time making the code change> / <time wasted trying to merge>`.

bors r-

**Pull request merged**
