### PR TITLE
server: add COCKROACH_SLOW_DRAIN env variable

### PR DESCRIPTION
**Pull request by asubiotto**
This variable enables a 10s wait for a draining node's liveness record
to propagate to the rest of the cluster. Operators should use this to
lower the probability of the occurence of unavailability scenarios where
another node in the cluster unknowingly transfers a lease to a draining
node after the node has attempted to transfer away its leases.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14419)

### CODE REVIEW

**Comment by tamird** [comment]
What's the idea here? Operators would start the entire cluster with this variable?

This looks like something that should either be in a settings table (see RFC) or enabled globally.

**Comment by bdarnell** [comment]
Yeah, this shouldn't be an env var except as a temporary experiment. I think that if the rolling upgrade workflow includes an explicit drain RPC, the draining time would be an argument to that RPC. If we want to stick with a signal-based protocol (because it's easier to integrate with kubernetes or whatever), can we use two different signals? E.g. `SIGTERM` is a fast shutdown but `SIGUSR1` is a slow drain. 

I also think it would be reasonable to just always do the wait. Impatient people can `kill -9` or `C-c` twice.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/server/server.go, line 850 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14419#-KgKmpgS7Ti74xgTumWs:-KgKmpgS7Ti74xgTumWt:bi4igb3) ([raw file](https://github.com/cockroachdb/cockroach/blob/420ea77dbec9567e13315e881710452e69448397/pkg/server/server.go#L850)):*
> ```Go
> 			s.nodeLiveness.SetDraining(context.TODO(), setTo)
> 			if setTo && slowDrain {
> 				time.Sleep(10 * time.Second)
> ```

Why 10s? Is this tied to the lease duration? If so it should refer to some constant so it can keep up to date if we change it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14419#-:-KgKk_CwPsNjPcodkChB:b-8bukm2)*

**Comment by tamird** [comment]
> I also think it would be reasonable to just always do the wait. Impatient people can kill -9 or C-c twice.
:+1:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/server/server.go, line 850 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14419#-KgKmpgS7Ti74xgTumWs:-KgKoeNDb1xwtb-Scy_W:brygpm) ([raw file](https://github.com/cockroachdb/cockroach/blob/420ea77dbec9567e13315e881710452e69448397/pkg/server/server.go#L850)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Why 10s? Is this tied to the lease duration? If so it should refer to some constant so it can keep up to date if we change it.
</blockquote></details>

Also if it's possible to observe from this node that its liveness record has expired rather than relying on a hardcoded duration, that'd be preferable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14419#-:-KgKo_-q0Q5ch3smD5hS:b-d41w5z)*

**Comment by tamird** [comment]
@asubiotto have you decided against this?

**Comment by asubiotto** [comment]
Yeah, I think it's not worth keeping this PR open. Thanks!

**Pull request closed without merging**
