### PR TITLE
server: skip TestUpgradeHappensAfterMigrations

### PR DESCRIPTION
**Pull request by knz**
informs https://github.com/cockroachdb/cockroach/issues/100276
Release note: None
Epic: None

### CODE REVIEW

**Review by adityamaru — APPROVED** [review]

**Comment by knz** [comment]
TFYR

bors r=adityamaru p=99

**Comment by knz** [comment]
bors r=adityamaru p=99

**Comment by knz** [comment]
bors r=adityamaru

**Comment by rafiss** [comment]
this should fix the test: https://github.com/cockroachdb/cockroach/pull/100490

it no longer failed under stress

**Comment by knz** [comment]
thanks i'll remove this commit then

bors r-

**Comment by knz** [comment]
closing in favor of  #100483.

**Pull request closed without merging**
