### PR TITLE
sql: add TODO for different conn close test

### PR DESCRIPTION
**Pull request by andreimatei**
Release note: None

### CODE REVIEW

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26533#-:-LEaxgKt1YDr2o1M_qM4:bnfp4nl)*

**Comment by andreimatei** [comment]
bors r+

---

Review status: :shipit: complete! 1 of 0 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26533#-:-LEjYgBq1U-547BSodjO:b-ydi9ay)*

**Pull request merged**
