### PR TITLE
sql: initial support for virtual columns

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change adds very basic support for virtual columns to the
non-test descriptors and catalog. This is gated behind an experimental
session setting.

Informs #57608.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57803)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @mgartner, and @rytaft)

___
*[pkg/sql/opt/exec/execbuilder/testdata/virtual_columns, line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57803#-MOD_eHG8N6mC1gPjSxK:-MOD_eHG8N6mC1gPjSxL:b1lj9md) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cec2bbeb93099157c4a168cab41b8a84188a141/pkg/sql/opt/exec/execbuilder/testdata/virtual_columns#L18)):*
> ```
>  ├── tableoid oid [hidden] [system]
>  ├── FAMILY fam_0_b (b)
>  ├── FAMILY fam_1_a_v (a, v)
> ```

Hm, I think virtual column should not be part of any column family. I'll fix that.

**Comment by RaduBerinde** [comment]
Added logic to disallow virtual columns from being part of column families; and added validation logic for the Virtual field.

**Review by ajwerner — COMMENTED** [review]
This was straightforward. Is there anything that needs to be done to use these in indexes, constraints, etc? If they would work, might be nice to add some testing, otherwise, might be nice to put up some gating. 

:lgtm: 

> Reviewed 9 of 13 files at r1, 8 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57803#-:-MOFJnlm3uPyFSqlaX_r:boeuigc)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @mgartner, and @rytaft)

**Comment by RaduBerinde** [comment]
Yeah, quite a bit needs to be done, especially for indexes. I'm keeping a checklist in #57608. For now, we just have this one big gate. We'll consider gating more specific things when we get further along.

**Comment by RaduBerinde** [comment]
Fixed and added some ValidateTableDescriptor tests.

**Pull request merged**
