### PR TITLE
sql: avoid unnecessary singleflight requests for role membership cache

### LINKED ISSUE #135931: sql: role membership cache refresh logic can cause a thundering herd of queries to `system.role_members`
**Describe the problem**

When the role membership cache is invalidated, each node will need to rebuild the cache. Currently, each user whose membership is being looked up will cause a query on the `system.role_members` table. This can be seen by looking at the requestKey of the `singleflight` operation here: https://github.com/cockroachdb/cockroach/blob/89dae000e93ca462d99b251df47b1e162058b56c/pkg/sql/authorization.go#L641

This is wasteful. Each of those queries is already scanning all the data from `system.role_members`, so we should change this so that the cache only gets populated once per node. This will change the number of internal queries needed to repopulate the cache to be `O(node count)` rather than `O((node count) * (active user count))`.

**To Reproduce**
The cache is invalidated by `CREATE ROLE`, `DROP ROLE`, and `GRANT role` statements, so this problem is easy to reproduce.

See the escalation https://github.com/cockroachlabs/support/issues/3128 for an example.

**Expected behavior**
Don't have such a big latency hit.

**Additional data / screenshots**
See the linked ticket.

**Environment:**
This was reported on CockroachDB version v24.1.6, but all supported versions are affected.

Jira issue: CRDB-44792

Epic CRDB-43310

### PR DESCRIPTION
**Pull request by rafiss**
See individual commits for refactors that make the enhancement easier.

---

Since we use a query that scans the whole role_members table to
populate the membership cache, it is wasteful to launch multiple
singleflight requests for different users. This patch changes
the cache refresh logic of the singleflight so that it always populates
the entire cache, which means there will only ever be one in-flight
query per each node.

```
$ benchdiff --old 98b0521cb18 --new 26daef27780 . -r BenchmarkUseManyRoles

pkg=1/1 iter=10/10 cockroachdb/cockroach/pkg/bench/rttanalysis \

name                          old time/op     new time/op     delta
UseManyRoles/use_50_roles-10      225ms ± 6%      114ms ± 2%  -49.43%  (p=0.000 n=10+10)
UseManyRoles/use_2_roles-10      10.7ms ± 4%      7.4ms ± 3%  -30.74%  (p=0.000 n=10+8)

name                          old roundtrips  new roundtrips  delta
UseManyRoles/use_2_roles-10        9.00 ± 0%       5.00 ± 0%  -44.44%  (p=0.000 n=10+10)
UseManyRoles/use_50_roles-10       3.00 ± 0%       3.00 ± 0%     ~     (all equal)

name                          old alloc/op    new alloc/op    delta
UseManyRoles/use_50_roles-10      438MB ± 0%      377MB ± 1%  -13.88%  (p=0.000 n=9+10)
UseManyRoles/use_2_roles-10      20.7MB ± 2%     19.1MB ± 1%   -7.46%  (p=0.000 n=10+10)

name                          old allocs/op   new allocs/op   delta
UseManyRoles/use_50_roles-10       881k ± 0%       398k ± 4%  -54.81%  (p=0.000 n=8+10)
UseManyRoles/use_2_roles-10       54.4k ± 8%      36.0k ± 5%  -33.85%  (p=0.000 n=10+10)
```

fixes https://github.com/cockroachdb/cockroach/issues/135931
Release note (performance improvement): Improved the internal caching
logic for role membership information. This reduces the latency impact
of commands such as `DROP ROLE`, `CREATE ROLE`, and `GRANT role TO user`,
which cause the role membership cache to be invalidated.

### CODE REVIEW

**Comment by rafiss** [comment]
I created a simple read-only workload that runs concurrent queries with a thousand different users, and ran it on a 3 node cluster.

Before this PR, CREATE ROLE and DROP ROLE caused a spike on the 99.9th percentile latency and also the rate of internal queries.
```
root@localhost:26257/defaultdb> select timestamp, "eventType" from system.eventlog where timestamp > '2024-11-22 23:07'::timestamptz and timestamp < '2024-11-22 23:11'::timestamptz
                             -> order by timestamp asc;
          timestamp          |  eventType
-----------------------------+--------------
  2024-11-22 23:08:57.942819 | create_role
  2024-11-22 23:09:27.021219 | drop_role
```
image
image


With this PR, there was no noticeable impact.
```
root@localhost:26257/defaultdb> select timestamp, "eventType" from system.eventlog where timestamp > '2024-11-22 23:53'::timestamptz and timestamp < '2024-11-22 23:57'::timestamptz
                             -> order by timestamp asc;
          timestamp          |  eventType
-----------------------------+--------------
  2024-11-22 23:54:47.286715 | create_role
  2024-11-22 23:55:29.026177 | drop_role
```
image
image


<details>
<summary>Click to see the workload script</summary>
```
package main

import (
	"context"
	"fmt"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"golang.org/x/sync/errgroup"
	"math/rand"
	"strconv"
	"strings"
)

func main() {
	u := "<node 1 connection string redacted>"
	ctx := context.Background()
	conn, err := pgx.Connect(ctx, u)
	if err != nil {
		panic(err)
	}

	fmt.Println("Creating table ...")

	_, err = conn.Exec(ctx, "DROP TABLE IF EXISTS tab")
	if err != nil {
		panic(err)
	}
	_, err = conn.Exec(ctx, "CREATE TABLE IF NOT EXISTS tab (a INT PRIMARY KEY)")
	if err != nil {
		panic(err)
	}
	_, err = conn.Exec(ctx, "INSERT INTO tab VALUES (1)")
	if err != nil {
		panic(err)
	}

	fmt.Println("Creating roles ...")

	_, err = conn.Exec(ctx, "CREATE ROLE IF NOT EXISTS parent_role")
	if err != nil {
		panic(err)
	}

	_, err = conn.Exec(ctx, "GRANT ALL ON TABLE tab TO parent_role")
	if err != nil {
		panic(err)
	}

	roles := make([]string, 0, 1000)
	for i := 0; i < 1000; i++ {
		roleName := "role" + strconv.Itoa(i)
		_, err = conn.Exec(ctx, "CREATE ROLE IF NOT EXISTS "+roleName)
		if err != nil {
			panic(err)
		}
		roles = append(roles, roleName)

		if i%50 == 0 {
			fmt.Println("Created role", i)
		}
	}

	_, err = conn.Exec(ctx, "GRANT parent_role TO "+strings.Join(roles, ", "))
	if err != nil {
		panic(err)
	}

	urls := []string{
		"<node 1 connection string redacted>",
		"<node 2 connection string redacted>",
		"<node 3 connection string redacted>",
	}
	pools := make([]*pgxpool.Pool, len(urls))

	fmt.Println("Creating pools ...")
	for i, u := range urls {
		cfg, err := pgxpool.ParseConfig(u)
		if err != nil {
			panic(err)
		}
		cfg.MaxConns = 500
		pool, err := pgxpool.NewWithConfig(ctx, cfg)
		if err != nil {
			panic(err)
		}
		pools[i] = pool
	}

	g, _ := errgroup.WithContext(ctx)
	g.SetLimit(1000)

	fmt.Println("Sending load ...")

	i := 0
	for {
		pool := pools[rand.Intn(len(pools))]
		roleID := i % 1000
		g.Go(func() error {
			conn, err := pool.Acquire(ctx)
			if err != nil {
				return err
			}
			defer conn.Release()

			_, err = conn.Exec(ctx, "SET ROLE role"+strconv.Itoa(roleID))
			if err != nil {
				return err
			}
			var res int
			err = conn.QueryRow(ctx, "SELECT * FROM tab LIMIT 1", pgx.QueryExecModeSimpleProtocol).Scan(&res)
			if err != nil {
				return err
			}

			return nil
		})
		if i%100 == 0 {
			fmt.Println("Sent load", i)
		}
		i++
	}
}

```
</details>

With larger node counts and greater numbers of concurrent active SQL users, the impact would be greater.

**Review by fqazi — APPROVED** [review]
Amazing work @rafiss :lgtm_strong:  . I only had one minor comment

Do we want to eventually consider back porting this or is the risk too high?

> Reviewed 2 of 2 files at r2, 12 of 12 files at r9, 11 of 11 files at r10, 7 of 7 files at r11, 7 of 7 files at r12, 7 of 7 files at r13, 7 of 7 files at r14, 8 of 8 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135852#-:-OCYmwgi0XvlNEcFxnux:bwbmunp)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @rafiss)

___
*[`pkg/sql/authorization.go` line 873 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/135852#-OCYiQV9EpO_wQ7qjFZR:-OCYiQV9EpO_wQ7qjFZS:b-rf3z0r) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac967184b77fe288f60fd41e4b6ffc67e8a6998f/pkg/sql/authorization.go#L873)):*
> ```Go
> 
> 	var ok bool
> 	for ok, err = it.Next(ctx); ok; ok, err = it.Next(ctx) {
> ```

Are we missing error checking after the loop?
___
*[`pkg/sql/authorization.go` line 622 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/135852#-OCYlcmlC-Z0py5PkQ9c:-OCYlcmlC-Z0py5PkQ9d:b9tk12a) ([raw file](https://github.com/cockroachdb/cockroach/blob/26daef27780cd9fac4029dbaf9a3e9183ae9b5f5/pkg/sql/authorization.go#L622)):*
> ```Go
> 			return userMapping, nil
> 		} else {
> 			return nil, sqlerrors.NewUndefinedUserError(member)
> ```

I think this fine, though its a behaviour change. I think previously we would do avoid the cache to confirm a user didn't exist. In case there was any funny case where the lease manager didn't know of the new version because of range feed lag. However, the old behaviour seems less correct since the user commit may not have completed (waiting for one version).

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135852)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @fqazi and @michae2)

___
*[`pkg/sql/authorization.go` line 873 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/135852#-OCYiQV9EpO_wQ7qjFZR:-OCYxytw0i4G3-fZJECk:b-8xmr3h) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac967184b77fe288f60fd41e4b6ffc67e8a6998f/pkg/sql/authorization.go#L873)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Are we missing error checking after the loop?
</blockquote></details>

i don't believe so; there's a `return err` right after the loop. i can make it an explicit `if err != nil` check though.
___
*[`pkg/sql/authorization.go` line 622 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/135852#-OCYlcmlC-Z0py5PkQ9c:-OCYwmHoAzQrPkv_wwoQ:b-rv1zqu) ([raw file](https://github.com/cockroachdb/cockroach/blob/26daef27780cd9fac4029dbaf9a3e9183ae9b5f5/pkg/sql/authorization.go#L622)):*
> I think this fine, though its a behaviour change. I think previously we would do avoid the cache to confirm a user didn't exist.

i don't think it's a behavior change. previously, we would never cache non-existence of a role. so if you tried to look up a role that didn't exist, it would be a cache miss that caused `resolveMemberOfWithAdminOption` to be called, and that would do the `RoleExists` check.

now, we don't need to do that, since we know that if the cache has any entries, it has entries for all existing users. this is because ac967184b77fe288f60fd41e4b6ffc67e8a6998f changed the query that populates the cache.

so it's an optimization, but not a functional behavior change. perhaps that's already what you meant with your comment?

**Review by rafiss — COMMENTED** [review]
> Do we want to eventually consider back porting this or is the risk too high?

I do want to try a backport for this if it doesn't have many conflicts, since I think we should try to help with the linked escalation

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135852#-:-OCZ-tor155UC2wXBNsG:bacb7nf)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @fqazi and @michae2)

___
*[`pkg/sql/authorization.go` line 622 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/135852#-OCYlcmlC-Z0py5PkQ9c:-OCZ-cA4DOybh5u2_U3k:bt03251) ([raw file](https://github.com/cockroachdb/cockroach/blob/26daef27780cd9fac4029dbaf9a3e9183ae9b5f5/pkg/sql/authorization.go#L622)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

> I think this fine, though its a behaviour change. I think previously we would do avoid the cache to confirm a user didn't exist.

i don't think it's a behavior change. previously, we would never cache non-existence of a role. so if you tried to look up a role that didn't exist, it would be a cache miss that caused `resolveMemberOfWithAdminOption` to be called, and that would do the `RoleExists` check.

now, we don't need to do that, since we know that if the cache has any entries, it has entries for all existing users. this is because ac967184b77fe288f60fd41e4b6ffc67e8a6998f changed the query that populates the cache.

so it's an optimization, but not a functional behavior change. perhaps that's already what you meant with your comment?
</blockquote></details>

Hm, maybe you are right though. this test ([link](https://mesolite.cluster.engflow.com/invocations/default/dc6d7853-826c-4935-97ed-c10818c27ef8)) failed with a user not found error (for a user that should have existed). so you are saying that the cache invalidation may not happen in time for this to work correctly?

```
        /var/lib/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/ccl/backupccl/backupccl_test_/backupccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/backupccl/testdata/backup-restore/descriptor-conflicts:67:
         SELECT count(1) FROM [SHOW TABLES FROM system] WHERE table_name LIKE 'crdb_internal_copy_%';
        expected:
        4
        
        found:
        pq: role/user "hamburger" does not exist
```

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135852)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @rafiss)

___
*[`pkg/sql/authorization.go` line 873 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/135852#-OCYiQV9EpO_wQ7qjFZR:-OCZ4uVmCcr9U-7psuzL:baf5utw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac967184b77fe288f60fd41e4b6ffc67e8a6998f/pkg/sql/authorization.go#L873)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i don't believe so; there's a `return err` right after the loop. i can make it an explicit `if err != nil` check though.
</blockquote></details>

oh I was wondering about the case where it.Next returns an error.
___
*[`pkg/sql/authorization.go` line 622 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/135852#-OCYlcmlC-Z0py5PkQ9c:-OCZ4j3o4jnV53_k87DC:bofcusg) ([raw file](https://github.com/cockroachdb/cockroach/blob/26daef27780cd9fac4029dbaf9a3e9183ae9b5f5/pkg/sql/authorization.go#L622)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

Hm, maybe you are right though. this test failed with a user not found error (for a user that should have existed). so you are saying that the cache invalidation may not happen in time for this to work correctly?

```
        /var/lib/engflow/worker/work/0/exec/bazel-out/k8-fastbuild/bin/pkg/ccl/backupccl/backupccl_test_/backupccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/backupccl/testdata/backup-restore/descriptor-conflicts:67:
         SELECT count(1) FROM [SHOW TABLES FROM system] WHERE table_name LIKE 'crdb_internal_copy_%';
        expected:
        4
        
        found:
        pq: role/user "hamburger" does not exist
```
</blockquote></details>

I wonder if we just need a WaitForOneVersion in there :thinking:

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135852)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @fqazi and @michae2)

___
*[`pkg/sql/authorization.go` line 873 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/135852#-OCYiQV9EpO_wQ7qjFZR:-OCZ5ngM8ktGL-OBa7qm:b-gblko4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac967184b77fe288f60fd41e4b6ffc67e8a6998f/pkg/sql/authorization.go#L873)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

oh I was wondering about the case where it.Next returns an error.
</blockquote></details>

yeah, if `it.Next` returns an error, the loop will exit, and the line right after the loop ends says `return err`.
___
*[`pkg/sql/authorization.go` line 622 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/135852#-OCYlcmlC-Z0py5PkQ9c:-OCZ677b7MPjN451Y7V8:b4364vq) ([raw file](https://github.com/cockroachdb/cockroach/blob/26daef27780cd9fac4029dbaf9a3e9183ae9b5f5/pkg/sql/authorization.go#L622)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

I wonder if we just need a WaitForOneVersion in there :thinking:
</blockquote></details>

where are you referring to? we already have a `WaitForOneVersion` which is called after running create/drop/grant/revoke statements, here: https://github.com/cockroachdb/cockroach/blob/2b30f8e6e0202c63e5222ff16ba5bbdfcc8e5d7c/pkg/sql/conn_executor.go#L4037

i think the issue in this case might just be that the restore code inserts directly into system.users, which will skip the table version bump logic. let me verify this.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135852)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @rafiss)

___
*[`pkg/sql/authorization.go` line 622 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/135852#-OCYlcmlC-Z0py5PkQ9c:-OCZ75QIE73XU8F5XB19:b-ykzr8e) ([raw file](https://github.com/cockroachdb/cockroach/blob/26daef27780cd9fac4029dbaf9a3e9183ae9b5f5/pkg/sql/authorization.go#L622)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

where are you referring to? we already have a `WaitForOneVersion` which is called after running create/drop/grant/revoke statements, here: https://github.com/cockroachdb/cockroach/blob/2b30f8e6e0202c63e5222ff16ba5bbdfcc8e5d7c/pkg/sql/conn_executor.go#L4037

i think the issue in this case might just be that the restore code inserts directly into system.users, which will skip the table version bump logic. let me verify this.
</blockquote></details>

Yeah, I was wondering about the restore code, we might just need to add the wait for one version in it.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135852)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @fqazi, @kev-cao, and @michae2)

___
*[`pkg/sql/authorization.go` line 622 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/135852#-OCYlcmlC-Z0py5PkQ9c:-OCZgKH-E4_-vJMsDf5h:bentziq) ([raw file](https://github.com/cockroachdb/cockroach/blob/26daef27780cd9fac4029dbaf9a3e9183ae9b5f5/pkg/sql/authorization.go#L622)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Yeah, I was wondering about the restore code, we might just need to add the wait for one version in it.
</blockquote></details>

i have added the version bump in the restore code

**Review by fqazi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135852#-:-OCZh7aF1L4A9lCLvZb-:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kev-cao and @michae2)

**Comment by rafiss** [comment]
tftr!

bors r+

**Pull request merged**
