### PR TITLE
workload/schemachange: add backups and ndjson logging

### LINKED ISSUE #57471: workload/schemachange: add logging and backups
Currently, errors that occur in the workload are hard to investigate because of a lack of observability. Logs need to be improved and a backup should be created on failure:
- [ ] Implement backup functionality when an error terminates the workload. Save the backup in the artifacts directory.
- [ ] Improve transaction logging to be serialized and show worker ids. When a transaction fails, log concurrent, in-progress transactions.
- [ ] Improve logging format - using json would make it easier to inspect programatically

### PR DESCRIPTION
**Pull request by jayshrivastava**
### roachtest: save database backup on schemachange random load failure 

Previously, there was no way to inspect the state of the database
when the schemachange random load workload failed. This change
updates roachtest to save a backup in the artifacts directory
so that the database state can be recovered for debugging or
investigation.

See #56118 

Release note: None

### roachtest: add transaction log to schemachange/random-load 
Release note: None

### workload/schemachange: add json logging infrastructure 

This change adds mechanisms for writing json transaction logs
to a file while the workload is running.

Workers now use atomicLog structs to write transactions atomically
to log files or stdout. Also, each worker stores log entries
inside its internal state to make coordinating log writes easier.

A preErrorHook function is introduced and implemented
to ensure that partially completed transactions can be written
to a log when the workload terminates due to an error. All log
entries are protected by mutexes so this hook can halt
other workers while it flushes their transaction logs. This
hook can only be called once per workload and is protected
by a sync.Once struct. If "tolerate-errors" is true, then
the worker will restart and release the locks it has on other
workers.

Release note: None

### workload/schemachange: refactor logging to use new infrastructure 

Closes: https://github.com/cockroachdb/cockroach/issues/57471
Release note: None

### workload/schemachange: implement addForeignKeyConstraint op

addForeignKeyConstraint adds a single, non-composite, foreign key relation
between two random columns.

Release note: None

### workload/schemachange: implement addUniqueConstraint op

The addUniqueConstraint op adds a unique constraint on a single
column.

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
A bit nit-picky but this feels like it should be 2 different PRs. 

Only reviewed the logging and backup part in detail. Consider splitting the fk and unique constraint commits off to a new PR. 

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 1 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57181#-:-MObQXRo7V1JO07ox701:b3las5j)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @jayshrivastava)

___
*[pkg/cmd/roachtest/schemachange_random_load.go, line 180 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57181#-MObJcTN0yCXT4vY2kk0:-MObJcTN0yCXT4vY2kk1:b8g4pur) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a945f0e742e0dcf9a3f9843ff7ea330a1bbf97a/pkg/cmd/roachtest/schemachange_random_load.go#L180)):*
> ```Go
> 
> 	// Copy the backup from the store directory to the artifacts directory.
> 	err = c.Get(ctx, c.l, filepath.Join(storeDirectory, "extern", "schemachange"), filepath.Join(c.t.ArtifactsDir(), "backup"), c.Node(1))
> ```

total nit: assign the paths to variables or wrap this. 
___
*[pkg/workload/schemachange/schemachange.go, line 252 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57181#-MObPeQ2B77wOegNi5vb:-MObPeQ2B77wOegNi5vc:b3fiicy) ([raw file](https://github.com/cockroachdb/cockroach/blob/63330a0599ffb3a0ba8c6c2c9d156c0336a3d423/pkg/workload/schemachange/schemachange.go#L252)):*
<details><summary><i alt="summary">Quoted 10 lines of code…</i></summary>

> ```
> 
> 	currentLogEntry     *struct {
> 		mu struct {
> 			syncutil.Mutex
> 			entry *LogEntry
> 		}
> 	}
> 	stdoutLog    *atomicLog
> 	artifactsLog *atomicLog
> }
> ```
</details>

my sense is that you should encapsulate this logic better. The boundaries here are pretty fuzzy. 
___
*[pkg/workload/schemachange/schemachange.go, line 265 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57181#-MObQ5uL0r91FQYEn4Yx:-MObQ5uL0r91FQYEn4Yy:b-toajml) ([raw file](https://github.com/cockroachdb/cockroach/blob/63330a0599ffb3a0ba8c6c2c9d156c0336a3d423/pkg/workload/schemachange/schemachange.go#L265)):*
> ```Go
> type LogEntry struct {
> 	WorkerID int
> 	Ops      []string
> ```

my sense is that we would benefit from making this more structured. For example, a timestamp would likely be good. Might also be nice to attach the new error codes that this statement expects. 
___
*[pkg/workload/schemachange/schemachange.go, line 273 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57181#-MObNpsBC_Y3Dw3QF_Fs:-MObNpsBC_Y3Dw3QF_Ft:b-boqwox) ([raw file](https://github.com/cockroachdb/cockroach/blob/63330a0599ffb3a0ba8c6c2c9d156c0336a3d423/pkg/workload/schemachange/schemachange.go#L273)):*
> ```Go
> 	//	TxStatusRollbackFailure = -2
> 	//	TxStatusInFailure       = -3
> 	//	TxStatusCommitSuccess   = 1
> ```

nit: indentation is weird here. Maybe define a new type for yourself and `stringer` it so this prints nicely. 

also, consider using struct tags to make the json prettier. 
___
*[pkg/workload/schemachange/schemachange.go, line 616 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57181#-MObPFoSE_YcHVdWHFAF:-MObPFoSE_YcHVdWHFAG:bdtepj0) ([raw file](https://github.com/cockroachdb/cockroach/blob/63330a0599ffb3a0ba8c6c2c9d156c0336a3d423/pkg/workload/schemachange/schemachange.go#L616)):*
> ```Go
> 		return err
> 	}
> 	_, _ = f.WriteString("[\n")
> ```

does it really need to be an array? My sense is that just newline-delimited json would be better
___
*[pkg/workload/schemachange/schemachange.go, line 627 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57181#-MObPCfnAo3ahDXgr4bK:-MObPCfnAo3ahDXgr4bL:bb7r2f0) ([raw file](https://github.com/cockroachdb/cockroach/blob/63330a0599ffb3a0ba8c6c2c9d156c0336a3d423/pkg/workload/schemachange/schemachange.go#L627)):*
> ```Go
> 	}
> 
> 	_, _ = s.logFile.WriteString("{}\n")
> ```

why?

**Review by jayshrivastava — COMMENTED** [review]
I dropped the last two commits. I'll PR them after this gets in.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57181#-:-MOcPoDO7LQB00xWm-S1:b2teo8n)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/workload/schemachange/schemachange.go, line 252 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57181#-MObPeQ2B77wOegNi5vb:-MOcQ059BTk1B9B2BZzE:b-qhbvy1) ([raw file](https://github.com/cockroachdb/cockroach/blob/63330a0599ffb3a0ba8c6c2c9d156c0336a3d423/pkg/workload/schemachange/schemachange.go#L252)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 
> 	currentLogEntry     *struct {
> 		mu struct {
> 			syncutil.Mutex
> 			entry *LogEntry
> 		}
> 	}
> 	stdoutLog    *atomicLog
> 	artifactsLog *atomicLog
> }
> ```
my sense is that you should encapsulate this logic better. The boundaries here are pretty fuzzy. 
</blockquote></details>

I like this idea. I moved logging stuff into a new logger struct. 
___
*[pkg/workload/schemachange/schemachange.go, line 265 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57181#-MObQ5uL0r91FQYEn4Yx:-MOcQ8HR2SxkUefI3UXv:bigtimd) ([raw file](https://github.com/cockroachdb/cockroach/blob/63330a0599ffb3a0ba8c6c2c9d156c0336a3d423/pkg/workload/schemachange/schemachange.go#L265)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

my sense is that we would benefit from making this more structured. For example, a timestamp would likely be good. Might also be nice to attach the new error codes that this statement expects. 
</blockquote></details>

Agreed. Attaching the expected errors makes writing error messages and passing them around much easier. Also solves some linting problems I was having. 
___
*[pkg/workload/schemachange/schemachange.go, line 616 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57181#-MObPFoSE_YcHVdWHFAF:-MOcPT-SEsXg40Dbv_v6:brw2ksf) ([raw file](https://github.com/cockroachdb/cockroach/blob/63330a0599ffb3a0ba8c6c2c9d156c0336a3d423/pkg/workload/schemachange/schemachange.go#L616)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

does it really need to be an array? My sense is that just newline-delimited json would be better
</blockquote></details>

I agree. It makes formatting easier and makes the logfile smaller. 
___
*[pkg/workload/schemachange/schemachange.go, line 627 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57181#-MObPCfnAo3ahDXgr4bK:-MOcPJcn0kebwCQ4YLyd:b-4djkr9) ([raw file](https://github.com/cockroachdb/cockroach/blob/63330a0599ffb3a0ba8c6c2c9d156c0336a3d423/pkg/workload/schemachange/schemachange.go#L627)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

why?
</blockquote></details>

I dropped this since I converted the log output to be newline-delimited json.

**Review by ajwerner — COMMENTED** [review]
just minor suggestions, otherwise :lgtm: 

> Reviewed 1 of 5 files at r6, 1 of 2 files at r12, 2 of 3 files at r14, 1 of 1 files at r15.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57181#-:-MOir3ugCJ4A7siNUcxu:bl8yuf3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @jayshrivastava)

___
*[pkg/cmd/roachtest/schemachange_random_load.go, line 182 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/57181#-MOip9tsEJbLd94Ro7U2:-MOip9tsEJbLd94Ro7U3:b-1582a6) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eddc07689780653af3c16ea8b6ecb5905211439/pkg/cmd/roachtest/schemachange_random_load.go#L182)):*
> ```Go
> 	remoteBackupFilePath := filepath.Join(storeDirectory, "extern", "schemachange")
> 	localBackupFilePath := filepath.Join(c.t.ArtifactsDir(), "backup")
> 	remoteTransactionsFilePath := filepath.Join(storeDirectory, "transactions.jsonl")
> ```

is the `l` because it's newline delimited? I usually see that as `ndjson` http://ndjson.org/
___
*[pkg/workload/schemachange/schemachange.go, line 281 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/57181#-MOipYvb-oTqnHCM-aZM:-MOipYvb-oTqnHCM-aZN:b-p5ciqq) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eddc07689780653af3c16ea8b6ecb5905211439/pkg/workload/schemachange/schemachange.go#L281)):*
<details><summary><i alt="summary">Quoted 14 lines of code…</i></summary>

> ```
> // TxStatus mirrors pgx.TxStatus, and is only valid
> // for the values -3,-2,-1,0,1,2,3. It is redefined here
> // for nicer printing.
> type TxStatus int
> func (s TxStatus) String() string {
> 	return [...]string{
> 		"TxStatusInFailure",
> 		"TxStatusRollbackFailure",
> 		"TxStatusCommitFailure",
> 		"TxStatusInProgress",
> 		"TxStatusCommitSuccess",
> 		"TxStatusRollbackSuccess"}[s+3]
> }
> // MarshalJSON encodes a TxStatus to a string.
> ```
</details>



I'd do this as:

```
// TxStatus mirrors pgx.TxStatus for printing.
type TxStatus int

//go:generate stringer -type TxStatus

const (
    TxStatusInProgress TxStatus = pgx.TxStatusInProgress
    // ...
)
```
___
*[pkg/workload/schemachange/schemachange.go, line 287 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/57181#-MOiqZQh4Zkgw36RSOeH:-MOiqZQh4Zkgw36RSOeI:b1u82rc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eddc07689780653af3c16ea8b6ecb5905211439/pkg/workload/schemachange/schemachange.go#L287)):*
> ```Go
> 	buffer := bytes.NewBufferString(`"`)
> 	buffer.WriteString(s.String())
> 	buffer.WriteString(`"`)
> ```

nit: how about
```
var buf bytes.Buffer
_, _ = fmt.Fprintf(&buf, "%q", s)
return buf.Bytes(), nil
```

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r16.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57181#-:-MP50Sy3-56IYA9xSqDm:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by jayshrivastava** [comment]
bors r=ajwerner

**Pull request merged**
