### PR TITLE
sqlsmith: add DELETE FROM ... USING and UPDATE ... FROM support

### LINKED ISSUE #98910: sqlsmith: generate statements of the form DELETE FROM ... USING and UPDATE ... FROM
As title. I think we're currently not generating statements of neither form even though there were introduced in #88974 and #39202, respectively.

Jira issue: CRDB-25584

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit makes it so that the sqlsmith can now generate statements of the form `DELETE FROM ... USING` and `UPDATE ... FROM`. We toss a coin every time before deciding to add another table (meaning in 50% cases these forms are not used, in 25% we have 1 extra table, etc). It also adjusts the generation of the RETURNING clause for DELETE and UPDATE to be able to pick from any of the table sources.

Fixes: #98910.

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
I used `cmd/smith` to see how the new statements look (thanks Michael for that addition!), and they looked reasonable. Should I also actually run something (a command or a unit test) so that generated queries are executed against some DB, or is it ok to just let the nightly tests do that for us?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98914#-:-NQmStDWBvYIiUASJsHJ:bjuha0p)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @michae2)

**Review by michae2 — APPROVED** [review]
:lgtm:

If you really want to run against a DB you could do something like:

```
# first shell
cockroach demo movr

# second shell
smith -url 'postgresql://demo:demo60607@127.0.0.1:26257/movr?options=...'
```

But it's fine with me if we want to let the nightly tests try this out.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98914#-:-NR5-aT97kRKormC1ZCp:b-iizy8h)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Review by mgartner — APPROVED** [review]
Thanks for doing this! :lgtm: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98914#-:-NR55WLq43lvppLPkcl3:bkqkww5)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by yuzefovich** [comment]
TFTRs!

I'll let nightly run tell us if anything is wrong (and will also backport to 23.1 but after a few days of baking on master).

bors r+

**Comment by yuzefovich** [comment]
This seems to have found one bug on master, but otherwise didn't destabilize the tests, so I think it's worth backporting to 23.1.

**Comment by yuzefovich** [comment]
blathers backport 23.1

**Pull request merged**
