### PR TITLE
opt: shorten column labels

### PR DESCRIPTION
**Pull request by RaduBerinde**
Shorten qualified column labels in opt test output (unless it can
cause ambiguity).

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Review status: 0 of 66 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/opt/props/logical.go, line 250 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25580#-LCdd9hC6cJpHpTLqVU2:-LCdf8bF-3XcX75udiYE:b-jgbio5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a45ee8d9c7e36586cc9cc99764b4bce0907a9313/pkg/sql/opt/props/logical.go#L250)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Isn't this the same as `suffix := label[idx]`?
</blockquote></details>

Ha, good point. Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25580)*

**Comment by andy-kimball** [comment]
:lgtm:

---

Review status: 0 of 77 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/opt/props/logical.go, line 252 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25580#-LCeDwX7BCC-VsHuhzYI:-LCeDwX7BCC-VsHuhzYJ:b-je6qh9) ([raw file](https://github.com/cockroachdb/cockroach/blob/20333f938db994f50557337d7dbe6820c6f9d5ce/pkg/sql/opt/props/logical.go#L252)):*
> ```Go
> 			for col := opt.ColumnID(1); int(col) <= md.NumColumns(); col++ {
> 				if col != id {
> 					if l := md.ColumnLabel(col); l == short || strings.HasSuffix(l, label[idx:]) {
> ```

In what case would `l == short`? If the label starts with "."? Seems like an extra logic complication for a case that i doubt will ever happen...

---

*[pkg/sql/opt/props/logical.go, line 259 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25580#-LCdy3UQD8QlUxsnIEEu:-LCeDRgf31vHjTdmZzxR:b-avmyph) ([raw file](https://github.com/cockroachdb/cockroach/blob/20333f938db994f50557337d7dbe6820c6f9d5ce/pkg/sql/opt/props/logical.go#L259)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I don't think it matters, this is effectively testing code.
</blockquote></details>

I think just run all the tests before and after this change, and make sure that the total elapsed times are similar.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25580#-:-LCeE9YdCgI3Ob1TBiNI:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 77 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/props/logical.go, line 252 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25580#-LCeDwX7BCC-VsHuhzYI:-LCeEiBz6P4EaXWhHsL8:b-4rza8x) ([raw file](https://github.com/cockroachdb/cockroach/blob/20333f938db994f50557337d7dbe6820c6f9d5ce/pkg/sql/opt/props/logical.go#L252)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

In what case would `l == short`? If the label starts with "."? Seems like an extra logic complication for a case that i doubt will ever happen...
</blockquote></details>

`short` doesn't include the `.`  Eg we're shortening `t.x` and there's some other column that's just `x`

---

*[pkg/sql/opt/props/logical.go, line 259 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25580#-LCdy3UQD8QlUxsnIEEu:-LCeFQQNE_knZBNpIJPN:b2qql9w) ([raw file](https://github.com/cockroachdb/cockroach/blob/20333f938db994f50557337d7dbe6820c6f9d5ce/pkg/sql/opt/props/logical.go#L259)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I think just run all the tests before and after this change, and make sure that the total elapsed times are similar.
</blockquote></details>

Just did that, they look the same (within variation).

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25580)*

**Comment by rytaft** [comment]
Reviewed 11 of 77 files at r6, 29 of 65 files at r7, 1 of 66 files at r8, 65 of 65 files at r9.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/opt/format.go, line 71 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/25580#-LCeEeu2AJvz9-EFoOC1:-LCeEeu2AJvz9-EFoOC2:b-yjnynv) ([raw file](https://github.com/cockroachdb/cockroach/blob/88744055e7fea16ca8da079fec43f3113026aaa0/pkg/sql/opt/format.go#L71)):*
> ```Go
> }
> 
> func (f *ExprFmtCtx) Metadata() *Metadata {
> ```

I think the linter will yell at you for not having comments on all these exported functions

---

*[pkg/sql/opt/props/logical.go, line 252 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/25580#-LCdtGLPBws-o6fsG2VY:-LCeHCPZ6upvB8_52poV:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/20333f938db994f50557337d7dbe6820c6f9d5ce/pkg/sql/opt/props/logical.go#L252)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

`label[idx:]` includes the `.`. I made it a variable with a comment
</blockquote></details>

Thanks!

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25580)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/format.go, line 71 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/25580#-LCeEeu2AJvz9-EFoOC1:-LCeNfG9-k_jsOpQfkS5:bfetdhp) ([raw file](https://github.com/cockroachdb/cockroach/blob/88744055e7fea16ca8da079fec43f3113026aaa0/pkg/sql/opt/format.go#L71)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I think the linter will yell at you for not having comments on all these exported functions
</blockquote></details>

Done. I meant to do that but then got trigger-happy when I got things working :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25580)*

**Comment by rytaft** [comment]
Reviewed 1 of 66 files at r10.
Review status: 12 of 77 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25580)*

**Pull request merged**
