### PR TITLE
sql: Properly mock out notion of namespaces in pg_catalog

### LINKED ISSUE #10522: sql: mock out notion of namespaces in pg_catalog
Currently `pg_namespace` returns databases present in CockroachDB. However, Postgres returns namespaces in this table, a notion that CockroachDB does not have. To support this use case, we need to mock out the existence of these namespaces in pg_catalog. This can be accomplished by hoisting `pg_catalog` and `information_schema` to their own namespaces, and putting all other databases under the `public` namespace.

### PR DESCRIPTION
**Pull request by nvb**
Fixes #10522.

CockroachDB does not have a notion of namespaces, but some clients rely on
a relationship between databases and namespaces existing in pg_catalog. To
accommodate this use case, we mock out the existence of namespaces, splitting
databases into one of four namespaces. These namespaces mirror Postgres, with
the addition of a "system" namespace so that only user-created objects exist
in the "public" namespace.

The namespaces included in this change are:
- pg_catalog
- information_schema
- system
- public

The second commit is split from the first to allow the first to be reviewed more easily.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/11603)

### CODE REVIEW

**Comment by knz** [comment]
:lgtm:

Although please enumerate the four namespaces in the commit message, instead of merely stating that there are four of them.

---

Reviewed 3 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11603#-:-KXR4M0a0FihOi25lUnh:b-fbonvh)*

**Comment by nvanbenschoten** [comment]
TFTR! Done.

**Comment by jordanlewis** [comment]
:lgtm: as well - I think this is important for some other pg_catalog things as well, so I'm glad you added it.

---

Review status: 1 of 3 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11603#-:-KXfXPjgKTJplJZCyip5:b-pxtcfx)*

**Comment by jordanlewis** [comment]
This also relates to an issue with our `pg_class` compatibility. Without merging this PR we have the ability to join entries in `pg_class` with their owner databases via `pg_namespace`. When this is merged, it will be impossible to determine the database of an entry in `pg_class`. I don't think we need to block this PR because of this problem, but I'd just like to note it down.

Postgres doesn't need this disambiguation because it returns only those entries in `pg_class` that are owned by the current database. We can't do that because we support cross-database joins and view.

**Comment by nvanbenschoten** [comment]
TFTRs!

@jordanlewis's concern was discussed offline. We decided to adopt the behavior of Postgres and return only entries in `pg_class` that are owned by the current database. Another option would have been to extend `pg_class` with a `reldat` field that points at `pg_database.oid`. We are not currently going to pursue this option, but that decision may be revisited in the future.

**Pull request merged**
