### PR TITLE
release-23.2: roachtest: allow tests to specify a cockroach binary to use 

### PR DESCRIPTION
**Pull request by DarrylWong**
Backport 3/3 commits from #113301.

/cc @cockroachdb/release

Release Justification: test-only change

---

Currently, roachtests must manually upload their own cockroach binary if needed through the Put API.
However, almost all roachtests upload the standard t.Cockroach() binary to ./cockroach on all nodes,
resulting in the same Put code being duplicated at the start of most tests. Additionally, to collect artifacts
we still need a cockroach binary at a discoverable path, leading to the same binary being copied twice in many
cases, see: https://github.com/cockroachdb/cockroach/pull/97814

This change adds a TestSpec option which lets tests specify a cockroach binary to use. If one is not specified,
we now upload the t.Cockroach() binary to ./cockroach. This lets us remove cockroach-default logic for artifacts,
and removes the need to manually upload binaries at the start of each test.

Release note: None
Fixes: https://github.com/cockroachdb/cockroach/issues/104729

### CODE REVIEW

**Comment by yuzefovich** [comment]
This needs to include #114212.

**Comment by DarrylWong** [comment]
Thanks, added 👍 

RFAL @renatolabs 

A little old but heres a [ low prob test run](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/12576712?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildTestsSection=true) I did

**Comment by renatolabs** [comment]
I don't see #114212; did you forget to push?

**Comment by DarrylWong** [comment]
Ahh, i just added the changes to my own commit. In hindsight for book keeping I see why just adding the commit would be better. Should i revert the changes and do that?

**Comment by renatolabs** [comment]
Oh, I see! Yes, cherry-picking the commits individually would be better, it is quite confusing to have the "same" commit doing different things across branches.

**Comment by DarrylWong** [comment]
Done.

Good to know that!

**Review by renatolabs — APPROVED** [review]

**Comment by DarrylWong** [comment]
TFTR!

bors r=renatolabs

**Comment by renatolabs** [comment]
Ops 🙂 This is a backport (i.e., no bors).

**Comment by DarrylWong** [comment]
🤦

**Pull request merged**
