### PR TITLE
streamingccl: move to wrapped event by default

### PR DESCRIPTION
**Pull request by dt**
Previously we had one event type that was just roachpb.KeyValues and a separate event type that was a wrapped KeyValue with additional previous value if diffs were requested. This, however, made a lot of code need to to handle one or the other. In the future we also expect to need to add more optional metadata to KVs, such as MVCC value headers, which would also require the use of a wrapper.

This change switches to use the wrapper by default all the time, even if a specific piece of added data like diffs isn't requested, and deprecates the old unwrapped field.

Release note: none.
Epic: none.

### CODE REVIEW

**Review by stevendanna — APPROVED** [review]
Very nice improvement.

**Comment by dt** [comment]
So one downside is this roughly doubles the memory usage of PCR's buffers for small valueless keys like indexes. Maybe we should follow up here and switch to a side-by-side slices configuration where we carry a slice of []kv and then, if any of those kvs have "extended attributes" or something a second slice, of the same len, where `kv[I]`'s extended attrs are in `attrs[I]` and if they're all zero value, we can elide the whole slice.

**Comment by dt** [comment]
TFTR!
bors r+

**Comment by stevendanna** [comment]
> Maybe we should follow up here and switch to a side-by-side slices configuration where we carry a slice of []kv and then, if any of those kvs have "extended attributes" or something a second slice, of the same len, where kv[I]'s extended attrs are in attrs[I] and if they're all zero value, we can elide the whole slice.

This seems like a good idea.

**Pull request merged**
