### PR TITLE
build: switch to go1.10

### PR DESCRIPTION
**Pull request by petermattis**

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[build/builder.sh, line 6 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22849#-L5oau5_w6wOq4Mvxssn:-L5oau5_w6wOq4Mvxsso:b-c41yys) ([raw file](https://github.com/cockroachdb/cockroach/blob/91782ee5ac2569989dc67d93b71356307b38c346/build/builder.sh#L6)):*
> ```Shell
> 
> image=cockroachdb/builder
> version=latest
> ```

I know I need to specify the right tag here, just haven't done so yet. I won't merge this until this is fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22849)*

**Comment by benesch** [comment]
If you're up for it, Ben suggested that we stop building Go from source and just download the binary tarball directly. LGTM though!

**Comment by benesch** [comment]
Took over your PR and took myself up on my suggestion. PTAL.

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22849#-:-L5ol9QlBdOd3tSYQesS:bnfp4nl)*

**Comment by benesch** [comment]
Welp, now I remember why we build Go from source. The binary releases default `$(go env CC)` to `gcc` when we want to use `clang`. Reverted to building from source because I don't want to deal with whatever fallout will inevitably ensue if I set `CC=clang` in the builder's env.

**Comment by petermattis** [comment]
Just noticed that we never cherry-picked this into the 2.0 branch. @bdarnell I wanted to confirm that we should cherry-pick. Would have been nice to build the first beta with go1.10, but at least master has been running with this for a few weeks.

**Comment by bdarnell** [comment]
I thought that was deliberate, and we were going to ship 2.0 with go 1.9. I don't feel strongly about it either way, though.

**Pull request merged**
