### PR TITLE
roachtest: small misc

### PR DESCRIPTION
**Pull request by andreimatei**
See individual commits.

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52083)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by ajwerner — APPROVED** [review]
:lgtm: mod build fixes

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52083#-:-MDRSyyGEoUpNkp6Iy5-:bqd5bs4)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/ts/timespan.go, line 100 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52083#-MDRT6ey2UucTRNQz-Ry:-MDRT6ey2UucTRNQz-Rz:b-gjhz2o) ([raw file](https://github.com/cockroachdb/cockroach/blob/caf506b3ffd71e6713c69b2df5a85fd1cb275780/pkg/ts/timespan.go#L100)):*
> ```Go
> 		return fmt.Errorf(
> 			"cannot query time series in the future (start time %d was greater than "+
> 				"cutoff for current sample period %d); current time: %s; sample duration: %s",
> ```

you need a `%d` or `%v`

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52083)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)

___
*[pkg/ts/timespan.go, line 100 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52083#-MDRT6ey2UucTRNQz-Ry:-MDvBmb95iLTpDZATWUl:bez7cmr) ([raw file](https://github.com/cockroachdb/cockroach/blob/caf506b3ffd71e6713c69b2df5a85fd1cb275780/pkg/ts/timespan.go#L100)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

you need a `%d` or `%v`
</blockquote></details>

switched to proper times

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52083#-:-MDvCt16DNE5JQ7VSLmM:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52083#-:-MDzPehL5W8rXzhBcZPP:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)

**Pull request merged**
