### PR TITLE
config/storage: per-replica constraints, improved locality handling

### LINKED ISSUE #19985: storage: zone configs lack expressivity
The zone configuration format makes certain configurations difficult and/or brittle. This is an umbrella issue to collect them.

1. two datacenters A and B, want two replicas in A and a third in B. I think this can be achieved by giving the nodes in A `--locality dc=a,hash=<random thing>` and the nodes in `B` `--locality=b`. It also seems that it would break if `B` got anything added to their locality.
2. 4 datacenters A B C D, want exactly one replica in A B C, none in D. This could use a negative constraint on `D`. Again this seems brittle since adding a new DC would wipe things out. Or similarly to the previous example, can give A-C longer distinct locality prefixes and trust that D's doesn't ever grow to the same length.

### PR DESCRIPTION
**Pull request by a-robinson**
This creates a new allowable format for zone config constraints, which
lets the user apply different sets of constraints to different numbers
of replicas within a zone. See the included test for what the new format
looks like.

Fixes #19985

Release note (cli change): Replication zone constraints can now be
specified on a per-replica basis, meaning you can configure some
replicas in a zone's ranges to follow one set of constraints and other
replicas to follow other constraints.

--------------------

Everything except the last commit is just #22412, so please ignore all the others.

This is really just a prototype of what it takes to make the YAML parsing backwards-compatible while supporting something along the lines of what @petermattis proposed for the new format in #19985. I'm looking for feedback on the format as well as on whether I'm over-complicating the parsing. Suggestions on other formats would be great -- I'm not at all attached to this.

Once we agree on the format/parsing, this still needs validation of the new constraints (e.g. to ensure that all the `Constraints.NumReplicas` sum to `ZoneConfig.NumReplicas`, that either all `Constraints` specify `NumReplicas` or there's only 0 or 1 `Constraints`, and that only positive constraints are included if `Constraints.NumReplicas` is set because that's the limited scope we settled on -- allowing more may make for some weird edge cases and doesn't seem necessary). It also will need a version gate to not allow `Constraints.NumReplicas` to be used unless the cluster's min version is 2.0, since old nodes would fail to parse the new configs.

### CODE REVIEW

**Comment by a-robinson** [comment]
Review status: 0 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/config/zone_yaml.go, line 23 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819#-L5k-U_Idq7MOIosaO-9:-L5ocBSOHqDCeY8NpP5J:b-1eh3wi) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f6aba1f8b7f0a49dbd6e17b70a5663043272596/pkg/config/zone_yaml.go#L23)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This is somewhat confusing. It isn't clear that `:numReplicas` applies to all of the constraints. Can we enclose the constraints in parentheses and make this `(c1,c2,c3):numReplicas`?
</blockquote></details>

Sure, done.

---

*[pkg/config/zone_yaml.go, line 132 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819#-L5k0RfBB77whCI8kKSE:-L5oJINrFXpChwfJYKDk:b-g3vhuz) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f6aba1f8b7f0a49dbd6e17b70a5663043272596/pkg/config/zone_yaml.go#L132)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Can we add a check of some sort that `marshalableZoneConfig` contains all of the fields of `ZoneConfig`? I assume you can cast a `ZoneConfig` to a `marshalableZoneConfig` because of the constraints field. Can we instead set a custom type in the `ZoneConfig` proto for `ZoneConfig.Constraints`? 
</blockquote></details>

You're right, we can't cast directly between `ZoneConfig` and `marshalableZoneConfig`.

I can't get `customtype` (or `casttype`) to replace `[]TYPE` with whatever custom/cast type I provide -- I can only replace `TYPE`. In this case, it produces something useless like `[]ConstraintList` as the generated type of the field.

I could, though, write a test that fills all fields of the struct (using reflection to avoid missing any new fields) and then round-trips it through yaml (or through utility conversion functions).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819)*

**Comment by petermattis** [comment]
:lgtm: though it would be worthwhile to get some feedback from other folks about the syntax. 

---

Review status: 0 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/config/zone_yaml.go, line 23 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819#-L5k-U_Idq7MOIosaO-9:-L5ofQPC2Jc8X0Y-FNIT:be6odnp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f6aba1f8b7f0a49dbd6e17b70a5663043272596/pkg/config/zone_yaml.go#L23)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Sure, done.
</blockquote></details>

You need to update this comment. 

---

*[pkg/config/zone_yaml.go, line 132 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819#-L5k0RfBB77whCI8kKSE:-L5of9blleZW4fDUcR3M:b84fs5u) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f6aba1f8b7f0a49dbd6e17b70a5663043272596/pkg/config/zone_yaml.go#L132)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

You're right, we can't cast directly between `ZoneConfig` and `marshalableZoneConfig`.

I can't get `customtype` (or `casttype`) to replace `[]TYPE` with whatever custom/cast type I provide -- I can only replace `TYPE`. In this case, it produces something useless like `[]ConstraintList` as the generated type of the field.

I could, though, write a test that fills all fields of the struct (using reflection to avoid missing any new fields) and then round-trips it through yaml (or through utility conversion functions).
</blockquote></details>

Ok. Rather than manually filling the protobuf, there is a `gogoproto.populate` option that will generate a function to automatically fill a proto with random data.

---

*[pkg/config/zone_yaml.go, line 34 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819#-L5ofXkeTmiX97xgge7K:-L5ofXkeTmiX97xgge7L:b-pt3mul) ([raw file](https://github.com/cockroachdb/cockroach/blob/9921d30f29d1a5b982cf01abd4aa5373c3b4c4ea/pkg/config/zone_yaml.go#L34)):*
> ```Go
> //    [c1, c2, c3]
> // 2. A per-replica format when NumReplicas is non-zero:
> //	  (c1,c2,c3):numReplicas
> ```

This line is misindented.

---

*[pkg/config/zone_yaml.go, line 68 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819#-L5ofhXZ7Q73ROv_HeQD:-L5ofhX_3VEJG3lKQcIR:bchzyqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/9921d30f29d1a5b982cf01abd4aa5373c3b4c4ea/pkg/config/zone_yaml.go#L68)):*
> ```Go
> 
> 	if !strings.HasPrefix(splitStr[0], "(") || !strings.HasSuffix(splitStr[0], ")") {
> 		return fmt.Errorf("constraints before separator must be wrapped in parentheses; got %q", str)
> ```

You should add some test cases that trigger these various error conditions. For example, more than one `:`, missing parentheses, missing open or close parenthesis, etc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819#-:-L5ofrqRwhx8w11a4REj:bw1wjxa)*

**Comment by a-robinson** [comment]
Review status: 0 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/config/zone_yaml.go, line 23 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819#-L5k-U_Idq7MOIosaO-9:-L5oiQh2UuB-KNxgUm2V:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f6aba1f8b7f0a49dbd6e17b70a5663043272596/pkg/config/zone_yaml.go#L23)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

You need to update this comment. 
</blockquote></details>

Done.

---

*[pkg/config/zone_yaml.go, line 132 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819#-L5k0RfBB77whCI8kKSE:-L5ojbA1J0pvZmaS7Fkf:btfjdtq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f6aba1f8b7f0a49dbd6e17b70a5663043272596/pkg/config/zone_yaml.go#L132)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Ok. Rather than manually filling the protobuf, there is a `gogoproto.populate` option that will generate a function to automatically fill a proto with random data.
</blockquote></details>

Perfect, thanks for the pointer. Done.

---

*[pkg/config/zone_yaml.go, line 34 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819#-L5ofXkeTmiX97xgge7K:-L5oiJEJpo9Guy-nc4Sb:b-bylmku) ([raw file](https://github.com/cockroachdb/cockroach/blob/9921d30f29d1a5b982cf01abd4aa5373c3b4c4ea/pkg/config/zone_yaml.go#L34)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This line is misindented.
</blockquote></details>

Clearly you have different reviewable settings than me, since it doesn't show up as off for me. Done.

---

*[pkg/config/zone_yaml.go, line 68 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819#-L5ofhXZ7Q73ROv_HeQD:-L5p5PtIH3OCovRVAYSJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9921d30f29d1a5b982cf01abd4aa5373c3b4c4ea/pkg/config/zone_yaml.go#L68)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

You should add some test cases that trigger these various error conditions. For example, more than one `:`, missing parentheses, missing open or close parenthesis, etc.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819)*

**Comment by petermattis** [comment]
Looks good to go modulo bike shedding of the syntax.

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819#-:-L5p67UTxk7RZWD6S9z7:b38791j)*

**Comment by a-robinson** [comment]
TFTR. I've also added the validation code/tests here, since they make the most sense in context.

---

Review status: 0 of 17 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819#-:-L5q8W2-uC6AdPglGK2i:b4skues)*

**Comment by a-robinson** [comment]
There is a slight problem here, though, which is that v1.1 does `ZoneConfig` parsing, validation, and protobuf serialization client-side and then inserts the serialized protobufs directly into the `system.zones` table, meaning that there's no way to protect people from trying to configure the new format but ending up with old style constraints that just won't match anything (because things like "(+a=1):2" will be interpreted as a node/store `Attribute`).

---

Review status: 0 of 17 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819#-:-L5qAS3q0h56BphOVgtX:bj627wf)*

**Comment by petermattis** [comment]
I'm not sure what to do about that problem. Could we detect it server side somehow? That seems irritating. It also seems rare enough that we could just ignore it. 

---

Review status: 0 of 17 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819#-:-L5qG54ZacRoPviBIfwW:b-jgw5j0)*

**Comment by a-robinson** [comment]
We can't prevent it without mucking with the generic SQL `UPSERT` code path, which is clearly a bad idea. We could detect it after it's happened with some safety checks in a code path that access the zone configs, but even if we do that the user won't get feedback that what they did was wrong unless they look at the logs.

I'd certainly like to prevent it because it's an understandable mistake to make, but we can't. Detecting it after the fact and spitting out some log messages isn't particularly helpful. I don't like it, but we may just have to live with makng the documentation extra clear about the need to use at least a v2.0 client.

---

Review status: 0 of 17 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819#-:-L5stj_hSfb-ILcsVcxt:beeqaut)*

**Comment by a-robinson** [comment]
Updated with the new map-based format suggested by @benesch in https://github.com/cockroachdb/cockroach/issues/19985#issuecomment-367122731

---

Review status: 0 of 22 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819#-:-L5tJtcHjCMCa_sBCVRL:b1xfowk)*

**Comment by a-robinson** [comment]
I'll leave this open until the end of the day, then squash all the commits from #22412 into the first commit of this PR and merge it. If there are any comments left, please get them in this afternoon.

I could try to re-jigger the changes into more reasonable commits if someone feels strongly about it, but it'd take quite a lot of re-jiggering at this point.

**Comment by a-robinson** [comment]
Squashed into one giant commit to rule them all. Will merge once green.

---

Review status: 0 of 22 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819#-:-L5uFPGNDaOZ_0WNQsxh:bh1mb5f)*

**Comment by petermattis** [comment]
The new format looks good to me.

---

Review status: 0 of 22 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819#-:-L5uTQyp1kckMUdC90kV:b1vn1sj)*

**Comment by couchand** [comment]
Apologies for the after-merge comments, I meant to get to this last night but didn't have a chance.  Only looked at the parsing/syntax stuff, didn't dive into the allocator business.

The one thing I don't see here or in the discussion is user-level examples that describe significant real world usage (beyond trivial, context-free a-b-c examples).  We also don't do a great job currently of documenting the zone config format from this perspective (which is part of why I came here looking for this sort of detail).

What I'm talking about is a handful of different scenarios that cover the main config points.  For each, an overview of the cluster topology, a description of what they're trying to do, and the start locality and attribute flags and zone configs you would use to achieve it.  Ideally these would be encoded in tests of some sort, but at least written up somewhere.

Specifically in the context of this PR, it would be useful to have examples of the sort that wouldn't have been possible before, and (in the future if further changes are made here) using those examples to guide the syntax could be helpful.

Also, do you want to perhaps update `docs/RFCS/20160706_expressive_zone_config.md` as obsolete now?

---

Review status: 0 of 22 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/config/zone.go, line 346 at r24](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819#-L5vUaQSVg8dme7Iq817:-L5vUaQSVg8dme7Iq818:bhaup4a) ([raw file](https://github.com/cockroachdb/cockroach/blob/73466fd3eff5e42667c0ca9bfc0f98bdbcb0ec96/pkg/config/zone.go#L346)):*
> ```Go
> 			numConstrainedRepls += int64(constraints.NumReplicas)
> 			for _, constraint := range constraints.Constraints {
> 				if constraint.Type != Constraint_REQUIRED && constraints.NumReplicas != z.NumReplicas {
> ```

It doesn't look like there are any tests that exercise the `Validate` method with prohibited constraints (making it hard for me to answer my own question below on 356).

---

*[pkg/config/zone.go, line 350 at r24](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819#-L5vX-X0BIzDqHxHFrnf:-L5vX-X1mBtpQ32AOAC5:b-q3ifa3) ([raw file](https://github.com/cockroachdb/cockroach/blob/73466fd3eff5e42667c0ca9bfc0f98bdbcb0ec96/pkg/config/zone.go#L350)):*
> ```Go
> 						"only required constraints (prefixed with a '+') can be applied to a subset of replicas")
> 				}
> 				if strings.Contains(constraint.Key, ":") || strings.Contains(constraint.Value, ":") {
> ```

Should there be a corresponding validation of the localities & attributes?

---

*[pkg/config/zone.go, line 356 at r24](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819#-L5vUsjs_K8MYDLMEvMO:-L5vUsjs_K8MYDLMEvMP:b7ht4p2) ([raw file](https://github.com/cockroachdb/cockroach/blob/73466fd3eff5e42667c0ca9bfc0f98bdbcb0ec96/pkg/config/zone.go#L356)):*
> ```Go
> 		}
> 		// TODO(a-robinson): Relax this constraint, as discussed on #22412.
> 		if numConstrainedRepls != int64(z.NumReplicas) {
> ```

It seems like this check and the one on line 346 combine to disallow prohibited constraints alongside required ones.  I think that's implied by the discussion on #22412, but I don't see it mentioned anywhere, so I'm not sure if that's a factor that's already been considered.  This seems like it would be sufficiently limiting to make prohibited constraints unuseful, but perhaps you're planning on addressing this soon?

---

*[pkg/config/zone_test.go, line 419 at r24](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819#-L5vXw_jRZZAusyB-fFY:-L5vXw_jRZZAusyB-fFZ:b-4dhmv1) ([raw file](https://github.com/cockroachdb/cockroach/blob/73466fd3eff5e42667c0ca9bfc0f98bdbcb0ec96/pkg/config/zone_test.go#L419)):*
> ```Go
> 		{input: "{+a: 1, '+a=1,+b,+c=d': 2}"},
> 		{input: "{'+a: 1'}"},  // unfortunately this parses just fine because yaml autoconverts it to a list...
> 		{input: "{+a,+b: 1}"}, // this also parses fine but will fail ZoneConfig.Validate()
> ```

Is there another natural character to use as a delimiter instead of comma, one that yaml doesn't already put significance on?  This case in particular seems likely to trip people up, and the error message will not necessarily make it clear what went wrong.

OTOH, the comma is also used on the locality side, and it's nice to have them be the same, so perhaps if it's changed here it should be changed there, too.

Looking over at that side, it looks like localities use `=` as the separator and attributes use `:`, so perhaps there's already an opportunity to push all of this to be more cohesive in a future pass.

---

*[pkg/config/zone_yaml.go, line 159 at r24](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819#-L5vAkDYVekfNQQicbpv:-L5vAkDZ0Biz15D8zAJh:b-23uqin) ([raw file](https://github.com/cockroachdb/cockroach/blob/73466fd3eff5e42667c0ca9bfc0f98bdbcb0ec96/pkg/config/zone_yaml.go#L159)):*
> ```Go
> }
> 
> // marshalableZoneConfig should be kept up-to-date with the real,
> ```

Can this be generated or linted?  If that's not feasible, perhaps at least a corresponding comment in the proto def?

---

*[pkg/roachpb/metadata.go, line 63 at r24](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819#-L5uz7K6AOPMwDEopDRC:-L5uz7K7im0ecpSA8uPG:bab08yc) ([raw file](https://github.com/cockroachdb/cockroach/blob/73466fd3eff5e42667c0ca9bfc0f98bdbcb0ec96/pkg/roachpb/metadata.go#L63)):*
> ```Go
> 
> // Equals returns whether the Attributes lists are equivalent. Attributes lists
> // are treated as sets, meaaning that ordering and duplicates are ignored.
> ```

s/meaaning/meaning/

---

*[pkg/settings/cluster/cockroach_versions.go, line 175 at r24](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819#-L5uzKcJM68MMgfRCTIC:-L5uzKcJM68MMgfRCTID:bec4xz0) ([raw file](https://github.com/cockroachdb/cockroach/blob/73466fd3eff5e42667c0ca9bfc0f98bdbcb0ec96/pkg/settings/cluster/cockroach_versions.go#L175)):*
> ```Go
> 	},
> 	{
> 		// VersionReadUncommittedRangeLookups is https://github.com/cockroachdb/cockroach/pull/21276.
> ```

copy-pasta

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819#-:-L5vec8lGI6igTNk_Kwh:b-7d3lhi)*

**Comment by a-robinson** [comment]
Thanks for the extra feedback, @couchand!

Regarding user scenarios, I'm sorry we didn't write any up in detail on Github. They were primarily discussed offline. This had its priority bumped way up during the 2.0 development cycle by partitioning use cases that @awoods187 came across when talking to customers. We certainly should include realistic scenarios in the documentation for this.

A lot of the motivating uses are wanting to have at least one replica in a location for latency reasons, but not have all of them there for fault tolerance reasons. As an example, just yesterday afternoon we were talking through a case where a customer is considering running with two datacenters on the west coast and two on the east coast, where they've partitioned their data into west coast and east coast users. They want to pin 2 replicas of the west coast user data to the west coast, and vice versa on the east coast for fast read and write latency. But they don't want to squeeze all the replicas in the two datacenters on the close coast because running with just 2 DCs means a single DC outage can take down your app. And they don't want to run a third DC on each coast due to the complexity of managing more DCs.

It's good feedback that they should be encoded in tests. The unit tests in this change go far beyond testing the more basic scenarios that customers have expressed interest in, because they're testing all the ways the mechanism *could* be used, not just the more limited subset of ways that we know people have asked to use it. That doesn't mean there shouldn't be one or two simpler tests, though.

> Also, do you want to perhaps update docs/RFCS/20160706_expressive_zone_config.md as obsolete now?

Sure, although it's only partially obsolete. I've opened https://github.com/cockroachdb/cockroach/pull/23014 to address your comments below, and will mark that separately.

---

Review status: 0 of 22 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/config/zone.go, line 346 at r24](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819#-L5vUaQSVg8dme7Iq817:-L62hVCbzzIh-hGRz1om:b-orumjy) ([raw file](https://github.com/cockroachdb/cockroach/blob/73466fd3eff5e42667c0ca9bfc0f98bdbcb0ec96/pkg/config/zone.go#L346)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

It doesn't look like there are any tests that exercise the `Validate` method with prohibited constraints (making it hard for me to answer my own question below on 356).
</blockquote></details>

Good point

---

*[pkg/config/zone.go, line 350 at r24](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819#-L5vX-X0BIzDqHxHFrnf:-L62hl0c_esjxdZqJY24:b-lo1k36) ([raw file](https://github.com/cockroachdb/cockroach/blob/73466fd3eff5e42667c0ca9bfc0f98bdbcb0ec96/pkg/config/zone.go#L350)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

Should there be a corresponding validation of the localities & attributes?
</blockquote></details>

Actually, this shouldn't have been left in. This is a remnant of my list-based implementation before using YAML maps were suggested. There isn't a strong reason to need to restrict these anymore.

If this were a clean-room implementation, there are all sorts of special characters I'd like to restrict, but given that we allow pretty much everything in v1.0 and v1.1, I'm not eager to add a bunch of restrictions that we don't need.

---

*[pkg/config/zone.go, line 356 at r24](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819#-L5vUsjs_K8MYDLMEvMO:-L62ioACCzoURFrvPmte:b-5ws3ro) ([raw file](https://github.com/cockroachdb/cockroach/blob/73466fd3eff5e42667c0ca9bfc0f98bdbcb0ec96/pkg/config/zone.go#L356)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

It seems like this check and the one on line 346 combine to disallow prohibited constraints alongside required ones.  I think that's implied by the discussion on #22412, but I don't see it mentioned anywhere, so I'm not sure if that's a factor that's already been considered.  This seems like it would be sufficiently limiting to make prohibited constraints unuseful, but perhaps you're planning on addressing this soon?
</blockquote></details>

Prohibited constraints can still be used (including alongside required constraints) when using constraints that apply to the entire range instead of these per-replica constraints. I've added a couple test cases to show this.

As for addressing this limitation, I plan to let you run with `numConstraintedRepls < z.NumReplicas` as discussed on #22412. Allowing prohibited constraints could probably be done as well, I'd just have to think through it in more detail and write a bunch more tests. I'm worried about the potentially bad combinations of constraints that users could come up with that'll get their cluster into a nasty state; limiting the available options was a good way to keep the initial scope smaller.

---

*[pkg/config/zone_test.go, line 419 at r24](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819#-L5vXw_jRZZAusyB-fFY:-L62flC48-0i2RTDBRSg:bfq6kfq) ([raw file](https://github.com/cockroachdb/cockroach/blob/73466fd3eff5e42667c0ca9bfc0f98bdbcb0ec96/pkg/config/zone_test.go#L419)):*
> Is there another natural character to use as a delimiter instead of comma, one that yaml doesn't already put significance on? This case in particular seems likely to trip people up, and the error message will not necessarily make it clear what went wrong.

There's nothing as natural as a comma, and we use commas everywhere else in our system that the user can specify lists of things (other than store attributes, as you mention, but those are a pretty ugly special case, and yaml puts just as much significance on them).g

---

*[pkg/config/zone_yaml.go, line 159 at r24](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819#-L5vAkDYVekfNQQicbpv:-L62gPI6mchgWALulVrZ:bpdazw0) ([raw file](https://github.com/cockroachdb/cockroach/blob/73466fd3eff5e42667c0ca9bfc0f98bdbcb0ec96/pkg/config/zone_yaml.go#L159)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

Can this be generated or linted?  If that's not feasible, perhaps at least a corresponding comment in the proto def?
</blockquote></details>

`TestMarshalableZoneConfigRoundTrip` is the effective Lint - if we neglect to include or change a field here when we add/change a `ZoneConfig` field, that test will fail.

---

*[pkg/roachpb/metadata.go, line 63 at r24](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819#-L5uz7K6AOPMwDEopDRC:-L62gZAxEqqEzBUORwRz:b-zcjvte) ([raw file](https://github.com/cockroachdb/cockroach/blob/73466fd3eff5e42667c0ca9bfc0f98bdbcb0ec96/pkg/roachpb/metadata.go#L63)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

s/meaaning/meaning/
</blockquote></details>

Thanks

---

*[pkg/settings/cluster/cockroach_versions.go, line 175 at r24](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819#-L5uzKcJM68MMgfRCTIC:-L62gsZWdcQKeayeIG5s:b-zcjvte) ([raw file](https://github.com/cockroachdb/cockroach/blob/73466fd3eff5e42667c0ca9bfc0f98bdbcb0ec96/pkg/settings/cluster/cockroach_versions.go#L175)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

copy-pasta
</blockquote></details>

Thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819#-:-L62WfCuiG4FNEiJA1Ai:blm1bnc)*

**Comment by couchand** [comment]
Review status: 0 of 22 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/config/zone.go, line 356 at r24](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819#-L5vUsjs_K8MYDLMEvMO:-L63Nat7Wy2HPRO49aoH:bgv8gc1) ([raw file](https://github.com/cockroachdb/cockroach/blob/73466fd3eff5e42667c0ca9bfc0f98bdbcb0ec96/pkg/config/zone.go#L356)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Prohibited constraints can still be used (including alongside required constraints) when using constraints that apply to the entire range instead of these per-replica constraints. I've added a couple test cases to show this.

As for addressing this limitation, I plan to let you run with `numConstraintedRepls < z.NumReplicas` as discussed on #22412. Allowing prohibited constraints could probably be done as well, I'd just have to think through it in more detail and write a bunch more tests. I'm worried about the potentially bad combinations of constraints that users could come up with that'll get their cluster into a nasty state; limiting the available options was a good way to keep the initial scope smaller.
</blockquote></details>

Yes, I had missed that possibility.

I also am concerned about the too-much-rope question here, in the future we should do more to make the ramifications of this configuration more obvious.

---

*[pkg/config/zone_yaml.go, line 159 at r24](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819#-L5vAkDYVekfNQQicbpv:-L63NzEuMgh3e0_MPLVn:b-myxumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/73466fd3eff5e42667c0ca9bfc0f98bdbcb0ec96/pkg/config/zone_yaml.go#L159)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

`TestMarshalableZoneConfigRoundTrip` is the effective Lint - if we neglect to include or change a field here when we add/change a `ZoneConfig` field, that test will fail.
</blockquote></details>

Ah, yes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22819)*

**Pull request merged**
