### PR TITLE
release-19.1: changefeed schema change nemeses and fixes

### PR DESCRIPTION
**Pull request by danhhz**
Backport:
  * 1/1 commits from "changefeedccl: add schema change events to nemeses" (#41842)
  * 1/1 commits from "changefeedccl: add scan boundaries based on change in set of columns" (#42053)

Please see individual PRs for details.

/cc @cockroachdb/release

### CODE REVIEW

**Comment by danhhz** [comment]
Here's the last one! Tests fail without the other PRs so those have to merge first. This didn't flake in an hour of Nemeses/cloudstorage testing on roachprod-stress.

**Comment by danhhz** [comment]
Hey @ajwerner looks like the 19.1 release is out. Mind taking a look at this so I can page it out?

**Review by ajwerner — CHANGES_REQUESTED** [review]
Seems like you added some `eg.go` files by accident. 

> Reviewed 4 of 5 files at r1, 6 of 7 files at r2, 2 of 35 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43037#-:-LwK8xE614cBHCetYwk9:bisdutb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @ajwerner, and @danhhz)

___
*[pkg/ccl/changefeedccl/cdctest/nemeses.go, line 531 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43037#-LwK7JeU2RH6-Y581QMP:-LwK7JeU2RH6-Y581QMQ:b2xenx3) ([raw file](https://github.com/cockroachdb/cockroach/blob/316a514c5cdc4c5ade01a428aa98f969eb2237e1/pkg/ccl/changefeedccl/cdctest/nemeses.go#L531)):*
> ```Go
> 	}
> 
> 	txn, err := ns.db.Begin()
> ```

Would it make you sad to also backport https://github.com/cockroachdb/cockroach/pull/43215? If so we can do that separately
___
*[pkg/col/coldata/vec.eg.go, line 2 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/43037#-LwK8sPN-5s23iETvZP-:-LwK8sPN-5s23iETvZP0:b-69evn9) ([raw file](https://github.com/cockroachdb/cockroach/blob/265a2b7e0883726fee39fd308ff3c8d6b5765f75/pkg/col/coldata/vec.eg.go#L2)):*
> ```Go
> // Code generated by execgen; DO NOT EDIT.
> // Copyright 2018 The Cockroach Authors.
> ```

This shouldn't be here right?

**Review by danhhz — COMMENTED** [review]
Fixed the eg.go files.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43037#-:-LwK9oCl-Rh02vM8YWor:b-wbavml)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @danhhz)

___
*[pkg/ccl/changefeedccl/cdctest/nemeses.go, line 531 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43037#-LwK7JeU2RH6-Y581QMP:-LwK9qK3CBWbAY5hjCvk:bk4dcry) ([raw file](https://github.com/cockroachdb/cockroach/blob/316a514c5cdc4c5ade01a428aa98f969eb2237e1/pkg/ccl/changefeedccl/cdctest/nemeses.go#L531)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Would it make you sad to also backport https://github.com/cockroachdb/cockroach/pull/43215? If so we can do that separately
</blockquote></details>

Definitely separately

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 2 of 35 files at r3, 31 of 32 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43037#-:-LwKDF4HDphpMONfMvWD:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15 and @danhhz)

**Comment by danhhz** [comment]
TFTR!

**Pull request merged**
