### PR TITLE
storage: deflake TestEagerReplication

### LINKED ISSUE #36663: teamcity: failed test: TestEagerReplication
The following tests appear to have failed on master (test): TestEagerReplication

You may want to check [for open issues](https://github.com/cockroachdb/cockroach/issues?q=is%3Aissue+is%3Aopen+TestEagerReplication).

[#1230907](https://teamcity.cockroachdb.com/viewLog.html?buildId=1230907):

```
TestEagerReplication
...I190409 13:37:09.004516 740264 storage/replicate_test.go:60  SucceedsSoon: expected 21 replicas in purgatory, but found 20
I190409 13:37:10.004928 740264 storage/replicate_test.go:60  SucceedsSoon: expected 21 replicas in purgatory, but found 20
I190409 13:37:11.005399 740264 storage/replicate_test.go:60  SucceedsSoon: expected 21 replicas in purgatory, but found 20
I190409 13:37:12.005918 740264 storage/replicate_test.go:60  SucceedsSoon: expected 21 replicas in purgatory, but found 20
I190409 13:37:13.006353 740264 storage/replicate_test.go:60  SucceedsSoon: expected 21 replicas in purgatory, but found 20
I190409 13:37:14.006866 740264 storage/replicate_test.go:60  SucceedsSoon: expected 21 replicas in purgatory, but found 20
I190409 13:37:15.007387 740264 storage/replicate_test.go:60  SucceedsSoon: expected 21 replicas in purgatory, but found 20
I190409 13:37:16.007847 740264 storage/replicate_test.go:60  SucceedsSoon: expected 21 replicas in purgatory, but found 20
I190409 13:37:17.008451 740264 storage/replicate_test.go:60  SucceedsSoon: expected 21 replicas in purgatory, but found 20
I190409 13:37:18.008894 740264 storage/replicate_test.go:60  SucceedsSoon: expected 21 replicas in purgatory, but found 20
I190409 13:37:19.009410 740264 storage/replicate_test.go:60  SucceedsSoon: expected 21 replicas in purgatory, but found 20
I190409 13:37:20.009915 740264 storage/replicate_test.go:60  SucceedsSoon: expected 21 replicas in purgatory, but found 20
I190409 13:37:21.010390 740264 storage/replicate_test.go:60  SucceedsSoon: expected 21 replicas in purgatory, but found 20
I190409 13:37:22.010863 740264 storage/replicate_test.go:60  SucceedsSoon: expected 21 replicas in purgatory, but found 20
I190409 13:37:23.011233 740264 storage/replicate_test.go:60  SucceedsSoon: expected 21 replicas in purgatory, but found 20
I190409 13:37:24.011678 740264 storage/replicate_test.go:60  SucceedsSoon: expected 21 replicas in purgatory, but found 20
I190409 13:37:25.012105 740264 storage/replicate_test.go:60  SucceedsSoon: expected 21 replicas in purgatory, but found 20
I190409 13:37:26.012498 740264 storage/replicate_test.go:60  SucceedsSoon: expected 21 replicas in purgatory, but found 20
I190409 13:37:27.012926 740264 storage/replicate_test.go:60  SucceedsSoon: expected 21 replicas in purgatory, but found 20
I190409 13:37:28.013287 740264 storage/replicate_test.go:60  SucceedsSoon: expected 21 replicas in purgatory, but found 20
I190409 13:37:29.013741 740264 storage/replicate_test.go:60  SucceedsSoon: expected 21 replicas in purgatory, but found 20
I190409 13:37:30.014160 740264 storage/replicate_test.go:60  SucceedsSoon: expected 21 replicas in purgatory, but found 20
I190409 13:37:31.014562 740264 storage/replicate_test.go:60  SucceedsSoon: expected 21 replicas in purgatory, but found 20
I190409 13:37:32.015080 740264 storage/replicate_test.go:60  SucceedsSoon: expected 21 replicas in purgatory, but found 20
I190409 13:37:33.015571 740264 util/stop/stopper.go:546  quiescing; tasks left:
1      [async] intent_resolver_ir_batcher
1      [async] intent_resolver_gc_batcher
    replicate_test.go:60: condition failed to evaluate within 45s: expected 21 replicas in purgatory, but found 20
        goroutine 740264 [running]:
        runtime/debug.Stack(0xa7a358200, 0xc00e72e210, 0x348ffe0)
        	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
        github.com/cockroachdb/cockroach/pkg/testutils.SucceedsSoon(0x34f74c0, 0xc000899500, 0xc001168760)
        	/go/src/github.com/cockroachdb/cockroach/pkg/testutils/soon.go:49 +0x103
        github.com/cockroachdb/cockroach/pkg/storage_test.TestEagerReplication(0xc000899500)
        	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replicate_test.go:60 +0x315
        testing.tRunner(0xc000899500, 0x2ea22e0)
        	/usr/local/go/src/testing/testing.go:827 +0xbf
        created by testing.(*T).Run
        	/usr/local/go/src/testing/testing.go:878 +0x35c



TestEagerReplication
...I190409 13:37:22.010863 740264 storage/replicate_test.go:60  SucceedsSoon: expected 21 replicas in purgatory, but found 20
I190409 13:37:23.011233 740264 storage/replicate_test.go:60  SucceedsSoon: expected 21 replicas in purgatory, but found 20
I190409 13:37:24.011678 740264 storage/replicate_test.go:60  SucceedsSoon: expected 21 replicas in purgatory, but found 20
I190409 13:37:25.012105 740264 storage/replicate_test.go:60  SucceedsSoon: expected 21 replicas in purgatory, but found 20
I190409 13:37:26.012498 740264 storage/replicate_test.go:60  SucceedsSoon: expected 21 replicas in purgatory, but found 20
I190409 13:37:27.012926 740264 storage/replicate_test.go:60  SucceedsSoon: expected 21 replicas in purgatory, but found 20
I190409 13:37:28.013287 740264 storage/replicate_test.go:60  SucceedsSoon: expected 21 replicas in purgatory, but found 20
I190409 13:37:29.013741 740264 storage/replicate_test.go:60  SucceedsSoon: expected 21 replicas in purgatory, but found 20
I190409 13:37:30.014160 740264 storage/replicate_test.go:60  SucceedsSoon: expected 21 replicas in purgatory, but found 20
I190409 13:37:31.014562 740264 storage/replicate_test.go:60  SucceedsSoon: expected 21 replicas in purgatory, but found 20
I190409 13:37:32.015080 740264 storage/replicate_test.go:60  SucceedsSoon: expected 21 replicas in purgatory, but found 20
I190409 13:37:33.015571 740264 util/stop/stopper.go:546  quiescing; tasks left:
1      [async] intent_resolver_ir_batcher
1      [async] intent_resolver_gc_batcher
    replicate_test.go:60: condition failed to evaluate within 45s: expected 21 replicas in purgatory, but found 20
        goroutine 740264 [running]:
        runtime/debug.Stack(0xa7a358200, 0xc00e72e210, 0x348ffe0)
        	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
        github.com/cockroachdb/cockroach/pkg/testutils.SucceedsSoon(0x34f74c0, 0xc000899500, 0xc001168760)
        	/go/src/github.com/cockroachdb/cockroach/pkg/testutils/soon.go:49 +0x103
        github.com/cockroachdb/cockroach/pkg/storage_test.TestEagerReplication(0xc000899500)
        	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replicate_test.go:60 +0x315
        testing.tRunner(0xc000899500, 0x2ea22e0)
        	/usr/local/go/src/testing/testing.go:827 +0xbf
        created by testing.(*T).Run
        	/usr/local/go/src/testing/testing.go:878 +0x35c
------- Stdout: -------
I190409 13:55:17.528162 772905 gossip/gossip.go:392  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"invalid.invalid:26257" > attrs:<> locality:<> ServerVersion:<major_val:0 minor_val:0 patch:0 unstable:0 > build_tag:"" started_at:0 
I190409 13:55:17.629642 773128 storage/queue.go:435  [s1,r2/1:/System/NodeLiveness{-Max}] rate limited in maybeadd-merge: throttled on async limiting semaphore
I190409 13:55:17.652334 773192 storage/queue.go:435  [s1] rate limited in maybeadd-split: throttled on async limiting semaphore
I190409 13:55:17.919711 772905 storage/replica_command.go:246  [s1,r5/1:/{Systemtse-Table/System…}] initiating a split of this range at key "a" [r21] (manual)
I190409 13:55:17.958233 773170 storage/queue.go:435  [s1,r5/1:{/Systemtse-a},txn=8f89db11] rate limited in maybeadd-replicate: throttled on async limiting semaphore
I190409 13:55:17.966039 772905 util/stop/stopper.go:546  quiescing; tasks left:
1      storage.IntentResolver: processing intents
1      [async] intent_resolver_ir_batcher
1      [async] intent_resolver_gc_batcher
I190409 13:55:17.966606 772905 util/stop/stopper.go:546  quiescing; tasks left:
1      storage.IntentResolver: processing intents
1      [async] intent_resolver_ir_batcher
I190409 13:55:17.967019 772905 util/stop/stopper.go:546  quiescing; tasks left:
1      storage.IntentResolver: processing intents
W190409 13:55:17.967251 773310 storage/intentresolver/intent_resolver.go:611  failed to cleanup transaction intents: failed to resolve intents: node unavailable; try another peer




```

Please assign, take a look and update the issue accordingly.

### LINKED ISSUE #36821: storage: TestStoreRangeSystemSplits failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/c53084cbd4b2be90789652ffb74b3d0c02930f7c

Parameters:
```
TAGS=
GOFLAGS=-parallel=4
```

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=TestStoreRangeSystemSplits PKG=github.com/cockroachdb/cockroach/pkg/storage TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1239993&tab=buildLog

```
but found:
[/Meta2/System/NodeLiveness /Meta2/System/NodeLivenessMax /Meta2/System/tsd /Meta2/System/"tse" /Meta2/Table/SystemConfigSpan/Start /Meta2/Table/11 /Meta2/Table/12 /Meta2/Table/13 /Meta2/Table/14 /Meta2/Table/15 /Meta2/Table/16 /Meta2/Table/17 /Meta2/Table/18 /Meta2/Table/19 /Meta2/Table/20 /Meta2/Table/21 /Meta2/Table/22 /Meta2/Table/23 /Meta2/Table/24 /Meta2/Table/50 /Meta2/Table/51 /Meta2/Table/52 /Meta2/Table/53 /Meta2/Table/54 /Meta2/Max]
I190413 07:21:11.458383 568978 storage/replica_command.go:252  [split,s1,r25/1:/{Table/54-Max}] initiating a split of this range at key /Table/57 [r26] (zone config)
I190413 07:21:11.459806 568428 storage/queue.go:435  [split,s1,r25/1:/{Table/54-Max},txn=628aa133] rate limited in maybeadd-merge: throttled on async limiting semaphore
E190413 07:21:11.460401 569219 storage/consistency_queue.go:137  [consistencyChecker,s1,r25/1:/{Table/54-Max}] computing own checksum: could not dial node ID 1: no node dialer configured
E190413 07:21:11.460434 569219 storage/queue.go:866  [consistencyChecker,s1,r25/1:/{Table/54-Max}] computing own checksum: could not dial node ID 1: no node dialer configured
I190413 07:21:11.462768 568413 storage/queue.go:435  [split,s1,r25/1:/Table/5{4-7},txn=628aa133] rate limited in maybeadd-replicate: throttled on async limiting semaphore
I190413 07:21:11.648281 567901 util/stop/stopper.go:546  quiescing; tasks left:
1      [async] storage.IntentResolver: cleanup txn records
1      [async] intent_resolver_ir_batcher
1      [async] intent_resolver_gc_batcher
I190413 07:21:11.648324 567901 util/stop/stopper.go:546  quiescing; tasks left:
1      [async] storage.IntentResolver: cleanup txn records
W190413 07:21:11.648348 569240 storage/intentresolver/intent_resolver.go:820  failed to gc transaction record: could not GC completed transaction anchored at /Local/Range/Table/54/RangeDescriptor: node unavailable; try another peer
--- FAIL: TestStoreRangeSystemSplits (45.22s)
    client_split_test.go:1367: condition failed to evaluate within 45s: expected split keys:
        [/Meta2/System/NodeLiveness /Meta2/System/NodeLivenessMax /Meta2/System/tsd /Meta2/System/"tse" /Meta2/Table/SystemConfigSpan/Start /Meta2/Table/11 /Meta2/Table/12 /Meta2/Table/13 /Meta2/Table/14 /Meta2/Table/15 /Meta2/Table/16 /Meta2/Table/17 /Meta2/Table/18 /Meta2/Table/19 /Meta2/Table/20 /Meta2/Table/21 /Meta2/Table/22 /Meta2/Table/23 /Meta2/Table/24 /Meta2/Table/50 /Meta2/Table/51 /Meta2/Table/52 /Meta2/Table/53 /Meta2/Table/54 /Meta2/Table/57 /Meta2/Max]
        but found:
        [/Meta2/System/NodeLiveness /Meta2/System/NodeLivenessMax /Meta2/System/tsd /Meta2/System/"tse" /Meta2/Table/SystemConfigSpan/Start /Meta2/Table/11 /Meta2/Table/12 /Meta2/Table/13 /Meta2/Table/14 /Meta2/Table/15 /Meta2/Table/16 /Meta2/Table/17 /Meta2/Table/18 /Meta2/Table/19 /Meta2/Table/20 /Meta2/Table/21 /Meta2/Table/22 /Meta2/Table/23 /Meta2/Table/24 /Meta2/Table/50 /Meta2/Table/51 /Meta2/Table/52 /Meta2/Table/53 /Meta2/Table/54 /Meta2/Max]
        goroutine 567901 [running]:
        runtime/debug.Stack(0xa7a358200, 0xc0016a4ff0, 0x34d8a00)
        	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
        github.com/cockroachdb/cockroach/pkg/testutils.SucceedsSoon(0x353ffa0, 0xc001330000, 0xc0016a4fc0)
        	/go/src/github.com/cockroachdb/cockroach/pkg/testutils/soon.go:49 +0x103
        github.com/cockroachdb/cockroach/pkg/storage_test.TestStoreRangeSystemSplits.func2()
        	/go/src/github.com/cockroachdb/cockroach/pkg/storage/client_split_test.go:1334 +0xb12
        github.com/cockroachdb/cockroach/pkg/storage_test.TestStoreRangeSystemSplits(0xc001330000)
        	/go/src/github.com/cockroachdb/cockroach/pkg/storage/client_split_test.go:1367 +0x55d
        testing.tRunner(0xc001330000, 0x2ee4cd8)
        	/usr/local/go/src/testing/testing.go:827 +0xbf
        created by testing.(*T).Run
        	/usr/local/go/src/testing/testing.go:878 +0x35c

```

### PR DESCRIPTION
**Pull request by tbg**
This wasn't actually the test's fault but another brain fart on my end,
namely using the wrong parameter for the semaphores used for MaybeAdd
and Add. We wanted size 500 and 100 respectively, but ended up using 1.

Fixes #36663.
Fixes #36821.

Release note: None

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm:

This looks like something you'll want to backport, right?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36755#-:-LcBDJjv-q9H7UZIrAx5:b-ku4que)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @petermattis)

**Comment by tbg** [comment]
No, the change that introduced this wasn't backported, neither: https://github.com/cockroachdb/cockroach/pull/36564

**Comment by tbg** [comment]
Ugh. CI failed with a timeout, it turns out that under race we spawn *loads* of these goroutines (likely because of the tight scanner interval, hitting the semaphore limit of 500) and just quiescing takes ages. One test took almost 36 minutes (of the 45 available) all by itself and a sizeable chunk of that just quiescing. No great option presents itself other than significantly clamping down on the goroutine count here, but then we get test flakes back when it was relied upon by a test that things will be fine. Opinions welcome.

```
I190411 11:42:44.218591 7611014 util/stop/stopper.go:546  quiescing; tasks left:
2      maybeadd-replicate
1      maybeadd-gc
I190411 11:42:44.220471 7611017 util/stop/stopper.go:546  quiescing; tasks left:
1      maybeadd-gc
I190411 11:42:44.222299 7611014 util/stop/stopper.go:546  quiescing; tasks left:
1      maybeadd-replicate
W190411 11:42:44.371836 487566 storage/store.go:1511  [n4,s4,r1/2:/{Min-System/NodeLâ€¦}] could not gossip first range descriptor: node unavailable; try another peer
--- PASS: TestReplicateQueueRebalance (2191.02s)
```

**Comment by tbg** [comment]
@petermattis can I get another review?

**Review by petermattis — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36755)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @petermattis and @tbg)

___
*[pkg/storage/replica_proposal.go, line 536 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36755#-LcbhrdR-s8BMp3QKj-x:-LcbhrdR-s8BMp3QKj-y:b49tq4m) ([raw file](https://github.com/cockroachdb/cockroach/blob/20fa0cd751d7c6cdade20aebfaacd2e50e551f5a/pkg/storage/replica_proposal.go#L536)):*
> ```Go
> 	// NB: the bootstrap store has a nil split queue.
> 	// TODO(tbg): the above is probably a lie now.
> 	if r.store.splitQueue != nil && needsSplitBySize && r.splitQueueThrottle.ShouldProcess(timeutil.Now()) {
> ```

This is a clever use of `log.EveryN`, but also seems to be an abuse of `log.EveryN`. Is it worthwhile to separate out that utility to make it clear that the usage here is not about logging?

Also, the switch to asynchronously enqueueing replicas in queues is causing some fallout.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36755)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @petermattis)

___
*[pkg/storage/replica_proposal.go, line 536 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36755#-LcbhrdR-s8BMp3QKj-x:-Lcbrng7AVP5wBnjI7t9:b-mviya4) ([raw file](https://github.com/cockroachdb/cockroach/blob/20fa0cd751d7c6cdade20aebfaacd2e50e551f5a/pkg/storage/replica_proposal.go#L536)):*
> Also, the switch to asynchronously enqueueing replicas in queues is causing some fallout.

That's what caused 99% of the work I did here -- what specifically are you referring to? CI is green. I'm going to hold off on the merge until you clarify.

> This is a clever use of log.EveryN, but also seems to be an abuse of log.EveryN. Is it worthwhile to separate out that utility to make it clear that the usage here is not about logging?

It's not actually an abuse, except that I wanted `util.EveryN`.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36755)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @petermattis and @tbg)

___
*[pkg/storage/replica_proposal.go, line 536 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36755#-LcbhrdR-s8BMp3QKj-x:-LcbxkKrBNtLyk82hohR:b9oz0cw) ([raw file](https://github.com/cockroachdb/cockroach/blob/20fa0cd751d7c6cdade20aebfaacd2e50e551f5a/pkg/storage/replica_proposal.go#L536)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

> Also, the switch to asynchronously enqueueing replicas in queues is causing some fallout.

That's what caused 99% of the work I did here -- what specifically are you referring to? CI is green. I'm going to hold off on the merge until you clarify.

> This is a clever use of log.EveryN, but also seems to be an abuse of log.EveryN. Is it worthwhile to separate out that utility to make it clear that the usage here is not about logging?

It's not actually an abuse, except that I wanted `util.EveryN`.
</blockquote></details>

Ack on the usage of `util.EveryN`.

There are uses of `MaybeAddAsync`. Are there any concerns and need to throttle those uses?

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36755)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @petermattis)

___
*[pkg/storage/replica_proposal.go, line 536 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36755#-LcbhrdR-s8BMp3QKj-x:-Lcc-5yyEK4m0mUx-2eq:b8lfpsf) ([raw file](https://github.com/cockroachdb/cockroach/blob/20fa0cd751d7c6cdade20aebfaacd2e50e551f5a/pkg/storage/replica_proposal.go#L536)):*
> Are there any concerns and need to throttle those uses?

`MaybeAddAsync` is throttled -- it goes through `Async` with `wait==false`, so whatever doesn't fit the semaphore is simply dropped. I'm a bit confused still by your comments, you must be seeing something I'm not seeing. Or you're looking at an older diff?

**Comment by tbg** [comment]
@petermattis I'm going to run with your earlier LGTM but please let me know if there's anything you're concerned about here.

bors r=petermattis

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36755)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @petermattis and @tbg)

___
*[pkg/storage/replica_proposal.go, line 536 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36755#-LcbhrdR-s8BMp3QKj-x:-LcfI05HCOn_N7bHBB6z:b-fabozm) ([raw file](https://github.com/cockroachdb/cockroach/blob/20fa0cd751d7c6cdade20aebfaacd2e50e551f5a/pkg/storage/replica_proposal.go#L536)):*
> MaybeAddAsync is throttled -- it goes through Async with wait==false, so whatever doesn't fit the semaphore is simply dropped. I'm a bit confused still by your comments, you must be seeing something I'm not seeing. Or you're looking at an older diff?

It is possible I'm confused. My understanding is that the throttling here (using `util.EveryN`) is to prevent the semaphore from being clogged up with async operations to add the same replica to the queue. Is that correct?

We call `raftLogQueue.MaybeAddAsync` and `splitQueue.MaybeAddAsync` elsewhere in this file without `util.EveryN` throttling. In `store.go` we call `{merge,split}Queue.MaybeAddAsync` on every replica on the store which surely isn't a useful thing to be doing as we'll very quickly hit the async limit. It is possible I'm completely misunderstanding how this is supposed to work as I haven't been reviewing all of the PRs involved.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36755)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @petermattis)

___
*[pkg/storage/replica_proposal.go, line 536 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36755#-LcbhrdR-s8BMp3QKj-x:-LcfPCUxEs0pTWWbfom0:bvgt0hn) ([raw file](https://github.com/cockroachdb/cockroach/blob/20fa0cd751d7c6cdade20aebfaacd2e50e551f5a/pkg/storage/replica_proposal.go#L536)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

> MaybeAddAsync is throttled -- it goes through Async with wait==false, so whatever doesn't fit the semaphore is simply dropped. I'm a bit confused still by your comments, you must be seeing something I'm not seeing. Or you're looking at an older diff?

It is possible I'm confused. My understanding is that the throttling here (using `util.EveryN`) is to prevent the semaphore from being clogged up with async operations to add the same replica to the queue. Is that correct?

We call `raftLogQueue.MaybeAddAsync` and `splitQueue.MaybeAddAsync` elsewhere in this file without `util.EveryN` throttling. In `store.go` we call `{merge,split}Queue.MaybeAddAsync` on every replica on the store which surely isn't a useful thing to be doing as we'll very quickly hit the async limit. It is possible I'm completely misunderstanding how this is supposed to work as I haven't been reviewing all of the PRs involved. 
</blockquote></details>

raft log is already throttled: https://github.com/cockroachdb/cockroach/blob/2d25bf0f85f5c70f6cd508f7c8047c3e8635b8ca/pkg/storage/replica_proposal.go#L633-L642
There are four callers of `*.MaybeAddAsync` and they're from split triggers, so that's fine. BTW, the throttling added in this commit is really just a workaround against this code firing all the time. I didn't see any problems without the semaphore, but now that we're firing off goroutines I'd want to avoid doing that once for each Raft request processed. It seems nontrivial to achieve that, hence the workaround and TODO. There isn't a problem for the queues per se if we call `MaybeAddAsync` all the time, that's exactly what the semaphore protects against. But this one below really showed up a lot.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36755)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @petermattis and @tbg)

___
*[pkg/storage/replica_proposal.go, line 536 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36755#-LcbhrdR-s8BMp3QKj-x:-LcfUlVxC3C4br0Jhd2B:b408soh) ([raw file](https://github.com/cockroachdb/cockroach/blob/20fa0cd751d7c6cdade20aebfaacd2e50e551f5a/pkg/storage/replica_proposal.go#L536)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

raft log is already throttled: https://github.com/cockroachdb/cockroach/blob/2d25bf0f85f5c70f6cd508f7c8047c3e8635b8ca/pkg/storage/replica_proposal.go#L633-L642
There are four callers of `*.MaybeAddAsync` and they're from split triggers, so that's fine. BTW, the throttling added in this commit is really just a workaround against this code firing all the time. I didn't see any problems without the semaphore, but now that we're firing off goroutines I'd want to avoid doing that once for each Raft request processed. It seems nontrivial to achieve that, hence the workaround and TODO. There isn't a problem for the queues per se if we call `MaybeAddAsync` all the time, that's exactly what the semaphore protects against. But this one below really showed up a lot.
</blockquote></details>

What about the usage of `MaybeAddAsync` in `Store.systemGossipUpdate`?

Rather that using a semaphore to limit the goroutines, did you consider using a `chan *Replica` that is read from by a single queue goroutine? Apologies for re-litigating the design at this point. I'm likely missing context here too, so thank you for your patience.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36755)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @petermattis)

___
*[pkg/storage/replica_proposal.go, line 536 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36755#-LcbhrdR-s8BMp3QKj-x:-LcfX4PG0muBnVZMG7xl:b-wz4fi4) ([raw file](https://github.com/cockroachdb/cockroach/blob/20fa0cd751d7c6cdade20aebfaacd2e50e551f5a/pkg/storage/replica_proposal.go#L536)):*
> What about the usage of MaybeAddAsync in Store.systemGossipUpdate?

That was the reason I started pulling on this thread. Note how the code there blocks when the semaphore is not available. It may crowd out other replicas while it's doing that, but it's adding all replicas, so that's fine. Originally I had set things up so that this goroutine would basically occupy a single semaphore entry to do all of its work, but this got awkward too quickly.

> Rather that using a semaphore to limit the goroutines, did you consider using a chan *Replica that is read from by a single queue goroutine?

That's another option, though it's not clear to me why that would be preferable. I'd like to think that the external API (MaybeAddAsync etc) would look the same, but that it would end up dropping more frequently. To be honest, I added this async stuff to avoid the chance of deadlocks, and was dismayed to find out that we were spraying calls to `MaybeAddAsync` at high frequency - I didn't expect the specific rate limiting to matter. That's the real problem here - we don't want to expect to drop additions to the queues (for example, we wouldn't want a replica that is queued to downreplicate sit around for 10 minutes, waiting for the scanner). We were previously backpressuring that to the caller goroutine directly (with all the chances at deadlock) but this also isn't great since that goroutine is often the raft goroutine.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36755)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @petermattis and @tbg)

___
*[pkg/storage/replica_proposal.go, line 536 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36755#-LcbhrdR-s8BMp3QKj-x:-Lcfak9pCeqVZvc02kIJ:bn13kuo) ([raw file](https://github.com/cockroachdb/cockroach/blob/20fa0cd751d7c6cdade20aebfaacd2e50e551f5a/pkg/storage/replica_proposal.go#L536)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

> What about the usage of MaybeAddAsync in Store.systemGossipUpdate?

That was the reason I started pulling on this thread. Note how the code there blocks when the semaphore is not available. It may crowd out other replicas while it's doing that, but it's adding all replicas, so that's fine. Originally I had set things up so that this goroutine would basically occupy a single semaphore entry to do all of its work, but this got awkward too quickly.

> Rather that using a semaphore to limit the goroutines, did you consider using a chan *Replica that is read from by a single queue goroutine?

That's another option, though it's not clear to me why that would be preferable. I'd like to think that the external API (MaybeAddAsync etc) would look the same, but that it would end up dropping more frequently. To be honest, I added this async stuff to avoid the chance of deadlocks, and was dismayed to find out that we were spraying calls to `MaybeAddAsync` at high frequency - I didn't expect the specific rate limiting to matter. That's the real problem here - we don't want to expect to drop additions to the queues (for example, we wouldn't want a replica that is queued to downreplicate sit around for 10 minutes, waiting for the scanner). We were previously backpressuring that to the caller goroutine directly (with all the chances at deadlock) but this also isn't great since that goroutine is often the raft goroutine.
</blockquote></details>

Ah, I was missing part of this change, which explains why I was so confused. See my comment in `systemGossipUpdate`.
___
*[pkg/storage/store.go, line 1701 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36755#-LcfaX0D2z0vYDHESNwa:-LcfaX0D2z0vYDHESNwb:b-cj2uxc) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d25bf0f85f5c70f6cd508f7c8047c3e8635b8ca/pkg/storage/store.go#L1701)):*
> ```Go
> 		}
> 		repl.SetZoneConfig(zone)
> 		s.splitQueue.Async(ctx, "gossip update", true /* wait */, func(ctx context.Context, h queueHelper) {
> ```

Can't you call `MaybeAdd` directly here? I don't think any locks are being held.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36755)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @petermattis and @tbg)

___
*[pkg/storage/store.go, line 1701 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36755#-LcfaX0D2z0vYDHESNwa:-LcgUdTZ8Rn5CXu4I0_R:b-xuergm) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d25bf0f85f5c70f6cd508f7c8047c3e8635b8ca/pkg/storage/store.go#L1701)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Can't you call `MaybeAdd` directly here? I don't think any locks are being held.
</blockquote></details>

Yes, but there's no `MaybeAdd` (outside of testing) -- I don't want to have anyone try to be clever about what locks they hold or don't. You always call `{Maybe,}AddAsync`.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36755)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @petermattis and @tbg)

___
*[pkg/storage/store.go, line 1701 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36755#-LcfaX0D2z0vYDHESNwa:-LchEt4A5IooiNmquTTI:b4o4t18) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d25bf0f85f5c70f6cd508f7c8047c3e8635b8ca/pkg/storage/store.go#L1701)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Yes, but there's no `MaybeAdd` (outside of testing) -- I don't want to have anyone try to be clever about what locks they hold or don't. You always call `{Maybe,}AddAsync`.
</blockquote></details>

Ack. Ok.

**Pull request merged**
