### PR TITLE
cli: don't pull liveness twice

### LINKED ISSUE #49520: zip: liveness is retrieved twice
A while ago I added a patch to `cockroach debug zip` to ignore decommissioned nodes. For this the command needed to retrieve the liveness data.

I did not see that liveness is already being retrieved earlier in the code.

The result is that `zip` currently retrieves liveness twice, and also populates the liveness JSON twice in the output zip file.

(This is relatively innocuous but wasteful)

The fix is to remove the first retrieval and only keep the second one.

### PR DESCRIPTION
**Pull request by tbg**
Fixes #49520

Noticed this since on OSX `unzip` asks me whether to overwrite `liveness.json`
This seems harmless other than that though.

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
thanks there was an issue #49520 but I was waiting for the contributor to say something...

LGTM!

**Comment by knz** [comment]
I think you can merge this now

**Comment by knz** [comment]
ping

**Comment by tbg** [comment]
bors r=knz

**Pull request merged**
