### PR TITLE
sql/pgwire: implicitly destroy portal on txn finish 

### LINKED ISSUE #42912: Portal not being implicitly destroyed on transaction finish
**Describe the problem**
Using to run a query in Java: when the query is inside a transaction with fetch size set, a cursor/portal is created on the server.
Upon committing the transaction without closing the ResultSet, the follwing error occurs:
```
org.postgresql.util.PSQLException: ERROR: unimplemented: multiple active portals not supported
  Hint: You have attempted to use a feature that is not yet implemented.
See: https://github.com/cockroachdb/cockroach/issues/40195
```

**To Reproduce**
Run [CockroachTest](https://github.com/feedzai/pdb/blob/cockroach-fetchsize-test/src/test/java/cockroach/test/CockroachTest.java) 
(the test is "standalone" and needs to have a CockroachDB or PostgreSQL container running; the commands used to start the containers are shown in the test comments)

**Expected behavior**
The test has 4 cases: a `SELECT *` query is ran using fetch size 0 or 2 (which is less than the size of the ResultSet); in addition, the query may run with or without a transaction.

When running without transaction, the fetch size is ignored and no problems occur (I suppose this is due to the limitations that also apply to PostgreSQL, using "fetch size" needs server cursors which only live for the duration of a transaction).

When running fetch size 0, the feature is disabled and no problems occur.

When running fetch size 2:
- CockroachDB 19.1.X fails due to #4035 when running the query (feature not supported, was implemented only in 19.2.X).
- CockroachDB 19.2.X is able to run the query and return results, but fails on commit due to #40195; however, if the ResultSet is closed before transaction commit, then no problem occurs.
- PostgreSQL 9.6.X passes the test without any problems.

Even though it is a good practice to close the ResultSets (as well as other Closeable objects), the patch in #33423 leads me to believe that the behavior to expect is the same as PostgreSQL: the cursors/portals should be implicitly closed when the transaction is done.

**Environment:**
CockroachDB 19.1.X, 19.2.X or PostgreSQL 9.6.X (or newer)

### PR DESCRIPTION
**Pull request by rafiss**
fixes #42912
touches #40195 

This also includes a commit to fix an error message hint that seems to be
accidentally using `WithSafeDetails`, which is meant for sentry reporting.
(Originally added in #40197.)

Release note (sql change): Previously, committing a transaction when a
portal was suspended would cause a "multiple active portals not
supported" error. Now, the portal is automatically destroyed.

### CODE REVIEW

**Review by jordanlewis — APPROVED** [review]
:lgtm_strong: 

I feel like we would do well to add a pgjdbc test for this as well to exercise the cases that we've gotten in the issues. Unless this will unlock some test cases in their test suite?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63677#-:-MYHZiTqCJuFRZ3P_jjk:bvrene9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/pgwire/command_result.go, line 499 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63677#-MYHXyY01VU7q1ms1cjQ:-MYHXyY01VU7q1ms1cjR:b2aj2el) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc8e06465834900051ea4aecb22b44aa3aafe6e1/pkg/sql/pgwire/command_result.go#L499)):*
> ```Go
> 			telemetry.Inc(sqltelemetry.InterleavedPortalRequestCounter)
> 			return errors.WithDetail(sql.ErrLimitedResultNotSupported,
> 				fmt.Sprintf("cannot perform operation %T while a different portal is open", c))
> ```

If you get rid of the errors.Safe thing, doesn't the type get redacted from logs?

**Review by rafiss — COMMENTED** [review]
will add a pgjdbc test good call!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63677#-:-MYIhmfb7xDCRW4re1EW:bwxhgtj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/pgwire/command_result.go, line 499 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63677#-MYHXyY01VU7q1ms1cjQ:-MYIhFqv6MXox2ZNjKzb:bz3xi1) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc8e06465834900051ea4aecb22b44aa3aafe6e1/pkg/sql/pgwire/command_result.go#L499)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

If you get rid of the errors.Safe thing, doesn't the type get redacted from logs?
</blockquote></details>

in this case no, because `WithDetail` is just meant for the _hint_ that is returned to the end user, and also it's just a naked string (that's why i changed to fmt.Sprintf).

`WithSafeDetails` on the other hand, is meant for sentry/reporting, and does require format args and need to specify when an argument is safe for reporting.

**Review by rafiss — COMMENTED** [review]
well, turns out pgjdbc always sends a COMMIT using the extended protocol. so it does in fact rely on multiple active portals, and supporting that will require fully implementing #40195 

 but the flow that i added to pgtest is the one used by the rust driver, so this change still seems useful

bors r=jordanlewis

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63677#-:-MYLg71_2sIQBF3GRZf5:b-xyqilt)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Comment by rafiss** [comment]
need to fix one of the tests

bors r-

**Comment by jordanlewis** [comment]
So, this does not in fact fix #42912 after all? I'm confused 🤔

**Comment by rafiss** [comment]
Yes, it does fix https://github.com/cockroachdb/cockroach/issues/42912. Previously, the following commands would fail at the `COMMIT` command.

```
send
Query {"String": "BEGIN"}
----

until
ReadyForQuery
----
{"Type":"CommandComplete","CommandTag":"BEGIN"}
{"Type":"ReadyForQuery","TxStatus":"T"}

# 83 = ASCII 'S' for Statement
# 49 = ASCII '1'
# ParameterFormatCodes = [0] for text format
send
Parse {"Name": "s4", "Query": "select n::int4 from generate_series(0,$1::int8) n", "ParameterOIDs": [20]}
Describe {"ObjectType": 83, "Name": "s4"}
Bind {"PreparedStatement": "s4", "ParameterFormatCodes": [0], "ResultFormatCodes": [0], "Parameters": [[49]]}
Execute {"MaxRows": 1}
Sync
----

until
ReadyForQuery
----
{"Type":"ParseComplete"}
{"Type":"ParameterDescription","ParameterOIDs":[20]}
{"Type":"RowDescription","Fields":[{"Name":"n","TableOID":0,"TableAttributeNumber":0,"DataTypeOID":23,"DataTypeSize":4,"TypeModifier":-1,"Format":0}]}
{"Type":"BindComplete"}
{"Type":"DataRow","Values":[{"text":"0"}]}
{"Type":"PortalSuspended"}
{"Type":"ReadyForQuery","TxStatus":"T"}


send
Query {"String": "COMMIT"}
----

until
ReadyForQuery
----
{"Type":"CommandComplete","CommandTag":"COMMIT"}
{"Type":"ReadyForQuery","TxStatus":"I"}
```

This is what the Rust sqlx driver does, according to this user-provided pcap: https://github.com/cockroachdb/cockroach/issues/40195#issuecomment-752611175

This works now after this change.

We can't test this with PGJDBC, because PGJDBC always executes COMMIT using the extended protocol. In other words, instead of sending a COMMIT like this:

```
send
Query {"String": "COMMIT"}
----
```

PGJDBC sends a COMMIT like this:
```
send
Parse {"Name": "commit_stmt", "Query": "COMMIT"}
Bind {"PreparedStatement": "commit_stmt"}
Execute
Sync
----
```

**Comment by rafiss** [comment]
@jordanlewis thanks for the nudge -- turns out we actually can handle a "prepared commit" also. Added that, and a PGJDBC test.

**Comment by rafiss** [comment]
@jordanlewis this is ready for another look

**Review by jordanlewis — APPROVED** [review]
:lgtm_strong: woo hoo!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63677#-:-MZ0tptWD1A9fKrc-gOP:bv0f645)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/pgwire/command_result.go, line 497 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63677#-MZ0s_i5CBbgJ_xov_I5:-MZ0s_i6BZj0NLfp5Cdr:b-xnnf0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/1168599b2524990e5416196e842fa2c75b8dee27/pkg/sql/pgwire/command_result.go#L497)):*
> ```Go
> // Parse/Bind/Execute sequence for a COMMIT query.
> func (r *limitedCommandResult) isCommit() (bool, error) {
> 	cmd, _, err := r.conn.stmtBuf.CurCmd()
> ```

nit: I think a comment before each "major case" would be useful, to explain what the things are being checked. like, up top:

// Case 1: the statement is a COMMIT in simple protocol

then down below

// Case 2: the statement is a Parse/Bind/Execute sequence

otherwise it is a little hard to discern "the point" of what is going on with all of the case checking.

**Comment by rafiss** [comment]
thanks for the review! i've added comments at each case

bors r=jordanlewis

**Comment by rafiss** [comment]
bors r=jordanlewis

**Comment by rafiss** [comment]
bors r=jordanlewis

**Pull request merged**
