### PR TITLE
util,lint: bump 'crlfmt', move 'color' to own repo

### PR DESCRIPTION
**Pull request by knz**
This patch moves 'color' to a separate repository so that 'crlfmt'
can use it, vendors the new package 'ttycolor' and bumps 'crlfmt'.

Release note: None

### CODE REVIEW

**Review by benesch — APPROVED** [review]
LGTM, thanks! But looks like something went wrong with your dep bump.

**Comment by knz** [comment]
> But looks like something went wrong with your dep bump.

Yep, fixed.

bors r+

**Comment by knz** [comment]
I forgot to include the generated sql.go from the lint test.

bors r+

**Comment by knz** [comment]
I am botching this commit and I don't understand why. Will iterate a little bit with local testing.

bors r-

**Comment by knz** [comment]
D'oh I was editing the wrong branch... PEBCAK

bors r+

**Pull request merged**
