### PR TITLE
systemschema: support rbr system.sql_instances

### PR DESCRIPTION
**Pull request by jeffswenson**
## instancestorage: clean up codec interface
Refactor the codec interface. The new codec interface will be used to
support the legacy index format and the RBR compatible index format.

Part of https://github.com/cockroachdb/cockroach/issues/85736

## systemschema: support rbr system.sql_instances
The sql_instances table now supports an index format compatible with
regional by row tables. This is building on the work from https://github.com/cockroachdb/cockroach/pull/90408.

```
$ COCKROACH_MR_SYSTEM_DATABASE=true ./cockroach-short demo
demo@127.0.0.1:26257/movr> SELECT * FROM system.sql_instances LIMIT 2;
  id |      addr       |                session_id                |             locality              | crdb_region
-----+-----------------+------------------------------------------+-----------------------------------+--------------
   1 | 127.0.0.1:26257 | \x0101800c678f05d4114b3aa17bcd61d336308a | {"Tiers": "region=us-east1,az=b"} | \x80
   2 |                 | NULL                                     | NULL                              | \x80
(2 rows)

$ COCKROACH_MR_SYSTEM_DATABASE=false ./cockroach-short demo
demo@127.0.0.1:26257/movr> SELECT * FROM system.sql_instances LIMIT 2;
  id |      addr       |                session_id                |             locality
-----+-----------------+------------------------------------------+------------------------------------
   1 | 127.0.0.1:26257 | \x010180fb9227b38ca9445ba27ac8b1f5a2204d | {"Tiers": "region=us-east1,az=b"}
   2 |                 | NULL                                     | NULL
(2 rows)
```

Part of https://github.com/cockroachdb/cockroach/issues/85736

### CODE REVIEW

**Comment by JeffSwenson** [comment]
The first 3 commits are from https://github.com/cockroachdb/cockroach/pull/91970.

**Review by ajwerner — COMMENTED** [review]
These migrations are going to be good times.

> Reviewed 1 of 4 files at r4, 19 of 20 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92010#-:-NH2jJ-37jKY1IF3KgKx:b-qvfxbs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jaylim-crl, @JeffSwenson, and @msbutler)

___
*[`pkg/sql/catalog/systemschema/system.go` line 667 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92010#-NH2gGyS6OWF0z1U_TXX:-NH2gGyS6OWF0z1U_TXY:b-bgzvl3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0b49001a752317e4e9100c0466497220c13d022/pkg/sql/catalog/systemschema/system.go#L667)):*
> ```Go
>     session_id   BYTES,
>     locality     JSONB,
> 	crdb_region  BYTES NOT NULL,
> ```

should we mark this as `NOT VISIBLE`?
___
*[`pkg/sql/sqlinstance/instancestorage/instancestorage.go` line 233 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92010#-NH2i7Z0-4zSvCyxlswQ:-NH2i7Z0-4zSvCyxlswR:biafdgr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0b49001a752317e4e9100c0466497220c13d022/pkg/sql/sqlinstance/instancestorage/instancestorage.go#L233)):*
> ```Go
> 	ctx context.Context, region []byte, db dbScan,
> ) (base.SQLInstanceID, error) {
> 	rows, err := s.getInstanceRows(ctx, region, db)
> ```

This is in the tail, but we might want for the initial grabbing of an ID to do a SKIP LOCKED scan in case there's an ongoing task to re-allocate IDs between regions. Honestly, I feel like the reallocation code could use another pass. 
___
*[`pkg/sql/sqlinstance/instancestorage/instancestorage.go` line 257 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92010#-NH2hOza29Vmx7bM1TSV:-NH2hOzbCVLxEAq7hXPz:b-top7a3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0b49001a752317e4e9100c0466497220c13d022/pkg/sql/sqlinstance/instancestorage/instancestorage.go#L257)):*
> ```Go
> }
> 
> // reclaimRegion will reclaim instances belong to expired sessions and delete
> ```

nit: belonging.
___
*[`pkg/sql/sqlinstance/instancestorage/instancestorage.go` line 259 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92010#-NH2gwn8-pFeS9dz6K6q:-NH2gwn8-pFeS9dz6K6r:b-xo2oz0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0b49001a752317e4e9100c0466497220c13d022/pkg/sql/sqlinstance/instancestorage/instancestorage.go#L259)):*
> ```Go
> // reclaimRegion will reclaim instances belong to expired sessions and delete
> // surplus sessions.
> func (s *Storage) reclaimRegion(ctx context.Context, region []byte) error {
> ```

If we were using the cached reader we wouldn't need to worry about blocking when checking for liveness. There's a real with the cached reader that it won't be up-to-date, but that only really matters if everything is in a crash loop using up sessions which are indeed dead. If there's literally nothing to grab, perhaps the right thing to do is find a way to ask the cache when its in-flight queries are done or something before trying again. Exponential backoff in the retry if there's literally nothing available is probably just as good. 



_Code quote:_
```Go
// reclaimRegion will reclaim instances belong to expired sessions and delete
// surplus sessions.
func (s *Storage) reclaimRegion(ctx context.Context, region []byte) error {
	// In a seperate transaction, read all rows that exist in the region. This
```
___
*[`pkg/sql/sqlinstance/instancestorage/row_codec.go` line 167 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92010#-NH2fcEd0pqaxBWU2a7H:-NH2fcEeEuk-k_c2Ng4R:bn98lmh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0b49001a752317e4e9100c0466497220c13d022/pkg/sql/sqlinstance/instancestorage/row_codec.go#L167)):*
> ```Go
> 		instanceID: instanceID,
> 	}
> 	if value == nil || !value.IsPresent() {
> ```

`value.IsPresent` has a nil check in it already
___
*[`pkg/ccl/multiregionccl/multiregion_system_table_test.go` line 144 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92010#-NH2fyW4AKCll2D6msi5:-NH2fyW51KJ8OVcNiLHg:b-qu7r6c) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0b49001a752317e4e9100c0466497220c13d022/pkg/ccl/multiregionccl/multiregion_system_table_test.go#L144)):*
> ```Go
> 	tDB := sqlutils.MakeSQLRunner(tenantSQL)
> 
> 	tDB.Exec(t, `SET descriptor_validation = off`)
> ```

don't need this anymore

**Review by jeffswenson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92010)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jaylim-crl, and @msbutler)

___
*[`pkg/sql/catalog/systemschema/system.go` line 667 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92010#-NH2gGyS6OWF0z1U_TXX:-NH56X2mBGB6_XFPE9Oc:b-8wme12) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0b49001a752317e4e9100c0466497220c13d022/pkg/sql/catalog/systemschema/system.go#L667)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

should we mark this as `NOT VISIBLE`?
</blockquote></details>

I would prefer to keep the table visible. Since this is an internal system state, I think we should optimize for showing the actual state of the system. 
___
*[`pkg/sql/sqlinstance/instancestorage/instancestorage.go` line 233 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92010#-NH2i7Z0-4zSvCyxlswQ:-NH6-hfH4gfTcK-js-Wa:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0b49001a752317e4e9100c0466497220c13d022/pkg/sql/sqlinstance/instancestorage/instancestorage.go#L233)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This is in the tail, but we might want for the initial grabbing of an ID to do a SKIP LOCKED scan in case there's an ongoing task to re-allocate IDs between regions. Honestly, I feel like the reallocation code could use another pass. 
</blockquote></details>

Done
___
*[`pkg/sql/sqlinstance/instancestorage/instancestorage.go` line 259 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92010#-NH2gwn8-pFeS9dz6K6q:-NH56w9Q1cGiWIh1HGMY:b-9cwfh4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0b49001a752317e4e9100c0466497220c13d022/pkg/sql/sqlinstance/instancestorage/instancestorage.go#L259)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

If we were using the cached reader we wouldn't need to worry about blocking when checking for liveness. There's a real with the cached reader that it won't be up-to-date, but that only really matters if everything is in a crash loop using up sessions which are indeed dead. If there's literally nothing to grab, perhaps the right thing to do is find a way to ask the cache when its in-flight queries are done or something before trying again. Exponential backoff in the retry if there's literally nothing available is probably just as good. 
</blockquote></details>

We were actually using the cached reader. I updated the PR to remove the cache wrapper, since my changes allow us to use the blocking API instead.

reclaimRegion is only called by the background routine, so blocking on an IsAlive call to clean things up is fine (and preferable). reclaimRegion is only writing to a single region, so it will use the 1PC path and avoid locking.

Allocating on start up will only attempt to reclaim local rows. The only reason getAvailableInstanceIDForRegion reclaims unused IDs is it is cheaper to reclaim a local expired row than it is to perform the global allocation operation. It also improves availability as it can reclaim local rows even if a region is unavailable.
___
*[`pkg/sql/sqlinstance/instancestorage/row_codec.go` line 167 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92010#-NH2fcEd0pqaxBWU2a7H:-NH5APTQ1_TMvaJUmolo:bboit3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0b49001a752317e4e9100c0466497220c13d022/pkg/sql/sqlinstance/instancestorage/row_codec.go#L167)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

`value.IsPresent` has a nil check in it already
</blockquote></details>

That is surprising and useful.
___
*[`pkg/ccl/multiregionccl/multiregion_system_table_test.go` line 144 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92010#-NH2fyW4AKCll2D6msi5:-NH5AYGzBse1BsLAJIVc:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0b49001a752317e4e9100c0466497220c13d022/pkg/ccl/multiregionccl/multiregion_system_table_test.go#L144)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

don't need this anymore 
</blockquote></details>

Done

**Review by ajwerner — APPROVED** [review]
Fix the tests and :lgtm: 

> Reviewed 1 of 1 files at r1, 2 of 5 files at r2, 2 of 2 files at r3, 1 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92010#-:-NH6igx49EPRRppOcVa8:b-9uydbn)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jaylim-crl, @JeffSwenson, and @msbutler)

___
*[`pkg/sql/catalog/systemschema/system.go` line 667 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/92010#-NH2gGyS6OWF0z1U_TXX:-NH6_xWn8_qvT9dN70mr:b-aoougd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b0b49001a752317e4e9100c0466497220c13d022/pkg/sql/catalog/systemschema/system.go#L667)):*
<details><summary><i>Previously, JeffSwenson (Jeff Swenson) wrote…</i></summary><blockquote>

I would prefer to keep the table visible. Since this is an internal system state, I think we should optimize for showing the actual state of the system. 
</blockquote></details>

Fair enough. In general with REGIONAL BY ROW, this is `NOT VISIBLE`.

**Review by jaylim-crl — COMMENTED** [review]
> Reviewed 27 of 28 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92010)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @JeffSwenson, and @msbutler)

___
*[`pkg/sql/sqlinstance/instancestorage/instancestorage.go` line 220 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/92010#-NHAf_QF3FAIeoJOwVng:-NHAf_QGE411i7xEAgRm:bth54zq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea3a2997f7a4c44e54bc96bc5c16a7531687eb3f/pkg/sql/sqlinstance/instancestorage/instancestorage.go#L220)):*
> ```Go
> 		// trigger reclaiming, and retry. This blocks until the reclaim process
> 		// completes.
> 		if err := s.generateAvailableInstanceRows(ctx, [][]byte{region}, sessionExpiration); err != nil {
> ```

nit: can we add a comment about only needing our own region here to reduce cold start latency?
___
*[`pkg/sql/sqlinstance/instancestorage/instancestorage.go` line 266 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/92010#-NHAgHdK1ryGWUkoQkL3:-NHAgHdK1ryGWUkoQkL4:b1eattj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea3a2997f7a4c44e54bc96bc5c16a7531687eb3f/pkg/sql/sqlinstance/instancestorage/instancestorage.go#L266)):*
> ```Go
> // reclaimRegion will reclaim instances belonging to expired sessions and
> // delete surplus sessions. reclaimRegion should only be called by the back
> // ground clean up and allocation job.
> ```

nit: background?
___
*[`pkg/sql/sqlinstance/instancestorage/instancestorage.go` line 268 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/92010#-NHAgCaN-UBRSb71R_1u:-NHAgCaN-UBRSb71R_1v:b-opwpnv) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea3a2997f7a4c44e54bc96bc5c16a7531687eb3f/pkg/sql/sqlinstance/instancestorage/instancestorage.go#L268)):*
> ```Go
> // ground clean up and allocation job.
> func (s *Storage) reclaimRegion(ctx context.Context, region []byte) error {
> 	// In a seperate transaction, read all rows that exist in the region. This
> ```

nit: s/seperate/separate
___
*[`pkg/sql/sqlinstance/instancestorage/instancestorage.go` line 338 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/92010#-NHAkWlN5Ta0aAo8QxIo:-NHAkWlN5Ta0aAo8QxIp:bu854o9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea3a2997f7a4c44e54bc96bc5c16a7531687eb3f/pkg/sql/sqlinstance/instancestorage/instancestorage.go#L338)):*
> ```Go
> 	batch := txn.NewBatch()
> 	if waitPolicy == lock.WaitPolicy_SkipLocked {
> 		batch.Header.WaitPolicy = waitPolicy
> ```

How come we only set the wait policy here if it is SkipLocked? If Block isn't required, I think we should make it take a bool instead (e.g. `skipRowIfLocked bool`)
___
*[`pkg/sql/sqlinstance/instancestorage/instancestorage.go` line 439 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/92010#-NHAoeiT2h8Q-RQijbLO:-NHAoeiT2h8Q-RQijbLP:b-2gpknv) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea3a2997f7a4c44e54bc96bc5c16a7531687eb3f/pkg/sql/sqlinstance/instancestorage/instancestorage.go#L439)):*
> ```Go
> // regions.
> func (s *Storage) generateAvailableInstanceRows(
> 	ctx context.Context, regions [][]byte, sessionExpiration hlc.Timestamp,
> ```

One thing to note about taking in an additional `[][]byte` here means that the reclaimGroup may not do what it does. e.g. If the caller calls generateAvailableInstanceRows(...,[]byte{region1}, ...), and generateAvailableInstanceRows(..., []byte{region2}, ...) at the same time, only one of them will run, given that the key is the same. If we include the region in the key, then that avoids the initial purpose.

Does it matter if the retry loop in CreateInstance only handles its own instance? (e.g. we talked about how round trip doesn't matter much in that case if we had to allocate).
___
*[`pkg/sql/sqlinstance/instancestorage/instancestorage.go` line 447 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/92010#-NHAqAFw52ibgLsw27u8:-NHAqAFw52ibgLsw27u9:b-m35lj5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea3a2997f7a4c44e54bc96bc5c16a7531687eb3f/pkg/sql/sqlinstance/instancestorage/instancestorage.go#L447)):*
> ```Go
> 	_, _, err := s.reclaimGroup.Do("allocate-instance-ids", func() (interface{}, error) {
> 		err := s.db.Txn(ctx, func(ctx context.Context, txn *kv.Txn) error {
> 			instances, err := s.getInstanceRows(ctx /*global*/, nil, txn, lock.WaitPolicy_Block)
> ```

nit: I think you meant to put global for `nil`?
___
*[`pkg/sql/sqlinstance/instancestorage/instancestorage.go` line 448 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/92010#-NHAlf7v2GGK_4qnMy3s:-NHAlf7v2GGK_4qnMy3t:b8rvfdo) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b802d3c6d50a2f00cb06561e7dde810520d8f2c/pkg/sql/sqlinstance/instancestorage/instancestorage.go#L448)):*
> ```Go
> 	_, _, err := s.reclaimGroup.Do("reclaim-instance-ids", func() (interface{}, error) {
> 		err := s.db.Txn(ctx, func(ctx context.Context, txn *kv.Txn) error {
> 			// Set the transaction deadline to the session expiration to ensure
> ```

Why don't we continue setting the transaction deadline here?
___
*[`pkg/sql/sqlinstance/instancestorage/instancestorage.go` line 496 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/92010#-NHAlprv21Wj7uUYJmyr:-NHAlprv21Wj7uUYJmys:bewq60m) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea3a2997f7a4c44e54bc96bc5c16a7531687eb3f/pkg/sql/sqlinstance/instancestorage/instancestorage.go#L496)):*
> ```Go
> 	target int, regions [][]byte, instances []instancerow,
> ) (toAllocate []instancerow) {
> 	// available per region
> ```

nit: unnecessary comment I think

**Review by jeffswenson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92010)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @jaylim-crl, and @msbutler)

___
*[`pkg/sql/sqlinstance/instancestorage/instancestorage.go` line 220 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/92010#-NHAf_QF3FAIeoJOwVng:-NHB1qR-6FQDgcbTb9pK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea3a2997f7a4c44e54bc96bc5c16a7531687eb3f/pkg/sql/sqlinstance/instancestorage/instancestorage.go#L220)):*
<details><summary><i>Previously, jaylim-crl (Jay Lim) wrote…</i></summary><blockquote>

nit: can we add a comment about only needing our own region here to reduce cold start latency?
</blockquote></details>

Done.
___
*[`pkg/sql/sqlinstance/instancestorage/instancestorage.go` line 338 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/92010#-NHAkWlN5Ta0aAo8QxIo:-NHAyjV60W6oq4qnkM0d:b7vc7za) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea3a2997f7a4c44e54bc96bc5c16a7531687eb3f/pkg/sql/sqlinstance/instancestorage/instancestorage.go#L338)):*
<details><summary><i>Previously, jaylim-crl (Jay Lim) wrote…</i></summary><blockquote>

How come we only set the wait policy here if it is SkipLocked? If Block isn't required, I think we should make it take a bool instead (e.g. `skipRowIfLocked bool`)
</blockquote></details>

Thanks! I removed the if block. The if block was intended as a temporary test.
___
*[`pkg/sql/sqlinstance/instancestorage/instancestorage.go` line 439 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/92010#-NHAoeiT2h8Q-RQijbLO:-NHAzgz44sOXMIGcVRmF:bqnz1dt) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea3a2997f7a4c44e54bc96bc5c16a7531687eb3f/pkg/sql/sqlinstance/instancestorage/instancestorage.go#L439)):*
<details><summary><i>Previously, jaylim-crl (Jay Lim) wrote…</i></summary><blockquote>

One thing to note about taking in an additional `[][]byte` here means that the reclaimGroup may not do what it does. e.g. If the caller calls generateAvailableInstanceRows(...,[]byte{region1}, ...), and generateAvailableInstanceRows(..., []byte{region2}, ...) at the same time, only one of them will run, given that the key is the same. If we include the region in the key, then that avoids the initial purpose.

Does it matter if the retry loop in CreateInstance only handles its own instance? (e.g. we talked about how round trip doesn't matter much in that case if we had to allocate).
</blockquote></details>

That is a good point.  I decided to remove the single flight. It is okay for the transactions to run in parallel, so the single flight is an optimization to reduce contention. Since one is run at start up and the other is run 10 minutes after start up, it is unlikely the transactions will run at the same time. 
___
*[`pkg/sql/sqlinstance/instancestorage/instancestorage.go` line 447 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/92010#-NHAqAFw52ibgLsw27u8:-NHAzExs0gyniHHCTpnj:b-mmjcqo) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea3a2997f7a4c44e54bc96bc5c16a7531687eb3f/pkg/sql/sqlinstance/instancestorage/instancestorage.go#L447)):*
<details><summary><i>Previously, jaylim-crl (Jay Lim) wrote…</i></summary><blockquote>

nit: I think you meant to put global for `nil`?
</blockquote></details>

Thanks! I fixed it. This is an annoying quirk of the go format tool. It reformats `func(arg1, /*comment*/ arg2)` into  `func(arg1 /*comment*/, arg2)`
___
*[`pkg/sql/sqlinstance/instancestorage/instancestorage.go` line 448 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/92010#-NHAlf7v2GGK_4qnMy3s:-NHAz1EU4LOD0aBecfRn:bvxez2s) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b802d3c6d50a2f00cb06561e7dde810520d8f2c/pkg/sql/sqlinstance/instancestorage/instancestorage.go#L448)):*
<details><summary><i>Previously, jaylim-crl (Jay Lim) wrote…</i></summary><blockquote>

Why don't we continue setting the transaction deadline here?
</blockquote></details>

We don't need to set a transaction deadline. I have a PR that I will send for review that removes the expiration argument and transaction deadline from CreateInstance. It's valid to create an instance owned by an expired session. The session expiration only needs to be checked when using the instance id.

**Review by jaylim-crl — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92010#-:-NHOXTUUDdke0X4V-YPe:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @JeffSwenson, and @msbutler)

**Comment by JeffSwenson** [comment]
I commented out the `ALTER TABLE ... SET LOCALITY REGIONAL BY ROW' commands in TestMrSystemDatabase. They caused a difficult to debug test flake. alterTableLocalityToRegionalByRow is defensive. It will generate a new primary key index even though the existing primary key is compatible with regional by row. Generating the new index deletes the existing sqlliveness index, which causes the session heart beat loop to terminate.

**Pull request merged**
