### PR TITLE
types: supress T type generation by proto

### PR DESCRIPTION
**Pull request by rohany**
Related to #48300.

This PR removes the type declaration generation from the types.T
proto in order to define non serialized fields on the types proto.

Release note: None

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
Oh, this is a nice workaround. :lgtm: but I'd like for Andy to take a look as well (or maybe @raduberinde)

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48350#-:-M6VVVf85L4gxvH57AWA:bt6lxyq)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball)

**Comment by RaduBerinde** [comment]
Interesting, what fields are we looking to add?

**Comment by rohany** [comment]
I'm planning on adding pointers to cached information about enums here (like a mapping from the logical to physical representation). Adding this information to the type itself seems much more feasible than plumbing `EvalContext` down to a huge number of places.

**Comment by RaduBerinde** [comment]
Cool, so something that's nil/zero for regular types but that gets populated for enum types? That makes sense (as long as we watch for thread safety issues).

**Comment by rohany** [comment]
Exactly. Yeah, I'm trying to keep those things in mind. I'm planning for the data to be read only during evaluation.

**Comment by rohany** [comment]
Do I have a stamp to merge this?

**Review by RaduBerinde — APPROVED** [review]

**Comment by rohany** [comment]
TFTRs!

bors r+

**Comment by andy-kimball** [comment]
Yeah, this is nice, glad you realized this was possible.

**Pull request merged**
