### PR TITLE
sql: Add Oid support to types.ColumnType (patch 4/)\

### PR DESCRIPTION
**Pull request by knz**
Split from #36598 cc @andy-kimball 

1. Add a new Oid field to ColumnType so that it can represent all the
base PG types. This largely replaces the need for the VisibleType field
(except for case of QCHAR).

2. types.proto now generates InternalColumnType which is wrapped by an
outer ColumnType. ColumnType overrides the marshal and unmarshal methods
in order to set up the fields correctly (e.g. setting the new OID field)
and to preserve backwards compatibility.

3. Represent NAME/OIDVECTOR/INT2VECTOR using the new OID field and remove
them as semantic types.

4. Rename JSONB to JSON, since the JSON semantic type represents all
JSON types, regardless of how they're stored.

4. Add Identical method that compares every ColumnType field for exact
equality.

Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Please extend the commit message:

- regarding point 1, please explain why qchar needs extra treatment
- regarding point 2, please explain what happens when using a mixed version cluster, say 19.1/19.2, and a 19.2 node creates a new table. Will the 19.1 node understand it? How does that work?
- regarding the 2nd point 4:
   - please rename to "point 5"
   - explain what Identical is used for - why is it useful and whether/how it could replace Equivalent.

Thank you

> Reviewed 71 of 71 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36701#-:-Lc5gxgDBezOwysBz4jC:bcet3uw)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sem/types/types.go, line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36701#-Lc5fyYG7Z2Dd7Dnvt3U:-Lc5fyYG7Z2Dd7Dnvt3V:b604gzg) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d515a8bc83a77567d71f706841cb92805b0a488/pkg/sql/sem/types/types.go#L129)):*
> ```Go
> // Identical returns true if every field in this ColumnType is exactly the same
> // as every corresponding field in the given ColumnType. Identical performs a
> // deep comparison, traversing any Tuple or Array contents.
> ```

Out of curiosity, why are you not delegating to `reflect.DeepEqual` here?
___
*[pkg/sql/sqlbase/encoded_datum_test.go, line 218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36701#-Lc5gjGs6wFjn0a0t3MA:-Lc5gjGs6wFjn0a0t3MB:b3t7wgf) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d515a8bc83a77567d71f706841cb92805b0a488/pkg/sql/sqlbase/encoded_datum_test.go#L218)):*
> ```Go
> 	for kind := range types.SemanticType_name {
> 		kind := types.SemanticType(kind)
> 		if kind == types.ANY || kind == types.NULL || kind == types.ARRAY ||
> ```

(Note to self: check null renamed to unknown in later commit)

**Review by knz — COMMENTED** [review]
This also needs a release note, to explain the improved type introspection in `information_schema.columns.data_type`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36701#-:-Lc5hS5L2hn0DA-8MbT8:b-j3gsk2)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by knz** [comment]
There are also a couple CI failures:

- there's an apparent in the IMPORT PGDUMP tests, which you can fix by adjusting the reference (expected) output.
- I invite you to clear linter failures in this commit already, so that further CI failures in later patches become easier to interpret.

**Review by andy-kimball — COMMENTED** [review]
I updated the commit message:
* For point 1, it's an out-of-date commit message. I originally thought QCHAR needed special treatment, before I understood that T_char = QCHAR and T_bpchar = CHAR, which confused me for some time. Once I got that sorted out, I forgot to update the commit message.
* For point 2, I think that's too much detail for a commit message. I have detail in patch #14, in the comment for `T`. Can you take a look at that and see if it's enough detail for you? I also added hopefully complete upgrade/downgrade tests in patch #14. I waited until nearly the end to test/comment, because so much was changing patch to patch.
* For 2nd point 4, I updated the message, inviting the reader to read the comment for `Identical`, which I beefed up to explain how it differs from `Equivalent`.

I updated the release note as well.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36701#-:-Lc9UZISBqrpCtOA90fu:b-ui6h7p)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/sql/sem/types/types.go, line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36701#-Lc5fyYG7Z2Dd7Dnvt3U:-Lc9TuHs5bZN1NvBlqPQ:bp8jsyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d515a8bc83a77567d71f706841cb92805b0a488/pkg/sql/sem/types/types.go#L129)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Out of curiosity, why are you not delegating to `reflect.DeepEqual` here?
</blockquote></details>

For performance reasons, since that uses reflection, which is way slower than custom code like I have here. I took the `Equal` code generated by the gogo protobuf library and tweaked it to skip over unused fields and handle Oid values (which do not have an Equal method, and so are not compatible with gogo protobuf assumptions).

**Review by knz — COMMENTED** [review]
Thank you!

The only things that remain to be adjusted in this commit are the NodeJS, Sequelize and IMPORT PGDUMP tests (see CI failure). It's good to go after that.

> Reviewed 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36701#-:-Lc9xZKN9-9FgBPc1EQu:b-dj57az)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sem/types/types.go, line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36701#-Lc5fyYG7Z2Dd7Dnvt3U:-Lc9xEYE3pGUUGSFmvCR:b-ucfkn4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d515a8bc83a77567d71f706841cb92805b0a488/pkg/sql/sem/types/types.go#L129)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

For performance reasons, since that uses reflection, which is way slower than custom code like I have here. I took the `Equal` code generated by the gogo protobuf library and tweaked it to skip over unused fields and handle Oid values (which do not have an Equal method, and so are not compatible with gogo protobuf assumptions).
</blockquote></details>

Thanks.

**Review by knz — COMMENTED** [review]
:lgtm: Out of curiosity, what was causing the CI failure? I don't recognize any significant change that would explain why the pgdump import test was failing.

> Reviewed 14 of 14 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36701#-:-LcG56W_5J3tMy1Chq8w:b-ev481h)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by andy-kimball** [comment]
pgdump import was failing due to using the `XXX_` prefix on some of the `ColumnType` fields. When I switched to `ZZZ_` it fixed these failures. The trouble is that `XXX_` is treated as special by gogo protobuf. It was not working correctly with our marshal/unmarshal Fuzz code.

All I wanted from the prefix was something to indicate these fields should not be used, rather than have them behave differently. In a later patch, when I create the `InternalType` struct, I get rid of the prefix anyway.

**Pull request closed without merging**
