### PR TITLE
build: add script for automated diagram generation

### PR DESCRIPTION
**Pull request by RichardJCai**
Added script to automatically generate grammar diagrams to be
uploaded to the cockroachdb/generated-diagrams repo.

Release note: None

### CODE REVIEW

**Comment by rickystewart** [comment]
I'll look closer at this tomorrow :) 

One question we're going to have to engage with is how this plays with Bazelfication. Ideally we should be using Bazel to generate this stuff. It doesn't have to happen immediately, and that won't block this PR, but we should have our sights set on how to make that switchover in the near future.

**Review by jlinder — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64780)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[build/teamcity-diagram-generation.sh, line 3 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64780#-M_3Vr1JCoA3X7AV09lX:-M_3Vr1JCoA3X7AV09lY:baph3wu) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e6fc693ef24cc09e3ac40b11c74071d320ba2f6/build/teamcity-diagram-generation.sh#L3)):*
> ```Shell
> #!/usr/bin/env bash
> 
> source "$(dirname "${0}")/teamcity-common-support.sh"
> ```

I'd recommend sourcing `build/teamcity-support.sh` here. It has some other important and helpful things in it. Examples:

- A TRAP function call that automatically always calls `common_support_remove_files_on_exit` when the script ends (whether through success or failure somewhere in the middle) so the ssh key files are assured to be removed. This also means the last line of this file won't be necessary.
- The `tc_start_block` and `tc_end_block` functions. They can be used to group log output in the TC build logs so you can expand specific sections of logs. Check the other `teamcity-*.sh` files for examples of how to use them.
___
*[build/teamcity-diagram-generation.sh, line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64780#-M_3VltpBp8B6bwajzFU:-M_3VltpBp8B6bwajzFV:b-9u5n9w) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e6fc693ef24cc09e3ac40b11c74071d320ba2f6/build/teamcity-diagram-generation.sh#L5)):*
> ```Shell
> source "$(dirname "${0}")/teamcity-common-support.sh"
> 
> # Grab the Railroad jar for SVG diagram generation.
> ```

Something that may be helpful for the log files. In 
___
*[build/teamcity-diagram-generation.sh, line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64780#-M_3Y7DiBVcsvyluKPn9:-M_3Y7DiBVcsvyluKPnA:b-3fyro4) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e6fc693ef24cc09e3ac40b11c74071d320ba2f6/build/teamcity-diagram-generation.sh#L11)):*
> ```
> ref
> ```
Maybe name this `cockroach_ref` to make it clear it's from the cockroach repo when it's used later in file?
___
*[build/release/teamcity-make-and-publish-build.sh, line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64780#-M_3TCRL3ykZP-CzgYTS:-M_3TCRL3ykZP-CzgYTT:blhffsi) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e6fc693ef24cc09e3ac40b11c74071d320ba2f6/build/release/teamcity-make-and-publish-build.sh#L6)):*
> ```Shell
> 
> source "$(dirname "${0}")/teamcity-support.sh"
> source "$(dirname "${0}")/../teamcity-common-support.sh"
> ```

This line isn't necessary here. The `build/release/teamcity-support.sh` file already sources the `build/teamcity-common-support.sh` script so it doesn't need to be sourced here.

Same for the other `build/release/teamcity-*.sh` files.
___
*[build/release/teamcity-support.sh, line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64780#-M_3TJgUCzsr81xCnoJ4:-M_3TJgUCzsr81xCnoJ5:byaebu5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e6fc693ef24cc09e3ac40b11c74071d320ba2f6/build/release/teamcity-support.sh#L8)):*
> ```Shell
> 
> remove_files_on_exit() {
>   rm -f .cockroach-teamcity-key
> ```

This line can also be removed since it's been added to the `common_support_remove_files_on_exit()` function in `build/teamcity-common-support.sh`.

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64780)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jlinder)

___
*[build/teamcity-diagram-generation.sh, line 3 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64780#-M_3Vr1JCoA3X7AV09lX:-M_6s65j8aqPL6P6X1C_:b7wzc4f) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e6fc693ef24cc09e3ac40b11c74071d320ba2f6/build/teamcity-diagram-generation.sh#L3)):*
> A TRAP function call that automatically always calls common_support_remove_files_on_exit when the script ends (whether through success or failure somewhere in the middle) so the ssh key files are assured to be removed. This also means the last line of this file won't be necessary.

Thanks for the tip, done
___
*[build/teamcity-diagram-generation.sh, line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64780#-M_3VltpBp8B6bwajzFU:-M_6s87p9mbsziMTAdkk:b9a6yxq) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e6fc693ef24cc09e3ac40b11c74071d320ba2f6/build/teamcity-diagram-generation.sh#L5)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

Something that may be helpful for the log files. In 
</blockquote></details>

Did this comment end early?
___
*[build/teamcity-diagram-generation.sh, line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64780#-M_3Y7DiBVcsvyluKPn9:-M_6sACy3kC4eBB95JiV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e6fc693ef24cc09e3ac40b11c74071d320ba2f6/build/teamcity-diagram-generation.sh#L11)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

> ```
> ref
> ```
Maybe name this `cockroach_ref` to make it clear it's from the cockroach repo when it's used later in file?
</blockquote></details>

Done.
___
*[build/release/teamcity-make-and-publish-build.sh, line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64780#-M_3TCRL3ykZP-CzgYTS:-M_6sGIPC19Vb8SrUAKz:b2tdgd) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e6fc693ef24cc09e3ac40b11c74071d320ba2f6/build/release/teamcity-make-and-publish-build.sh#L6)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

This line isn't necessary here. The `build/release/teamcity-support.sh` file already sources the `build/teamcity-common-support.sh` script so it doesn't need to be sourced here.

Same for the other `build/release/teamcity-*.sh` files.
</blockquote></details>

Oops didn't see that, thanks
___
*[build/release/teamcity-support.sh, line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64780#-M_3TJgUCzsr81xCnoJ4:-M_6sI7o2CO9xt4SssvX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e6fc693ef24cc09e3ac40b11c74071d320ba2f6/build/release/teamcity-support.sh#L8)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

This line can also be removed since it's been added to the `common_support_remove_files_on_exit()` function in `build/teamcity-common-support.sh`.
</blockquote></details>

Done.

**Review by jlinder — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64780)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[build/teamcity-diagram-generation.sh, line 3 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64780#-M_3Vr1JCoA3X7AV09lX:-M_T8E2Y9HUVFQj690bZ:b12fgqf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e6fc693ef24cc09e3ac40b11c74071d320ba2f6/build/teamcity-diagram-generation.sh#L3)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

> A TRAP function call that automatically always calls common_support_remove_files_on_exit when the script ends (whether through success or failure somewhere in the middle) so the ssh key files are assured to be removed. This also means the last line of this file won't be necessary.

Thanks for the tip, done
</blockquote></details>

Gladly!

One thing I wasn't clear on in the first comment is that the `source "$(dirname "${0}")/teamcity-common-support.sh"` line isn't necessary because that file is sourced by the `teamcity-support.sh` script.
___
*[build/teamcity-diagram-generation.sh, line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64780#-M_3VltpBp8B6bwajzFU:-M_T8X00BBeKpRger30N:bbzkygj) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e6fc693ef24cc09e3ac40b11c74071d320ba2f6/build/teamcity-diagram-generation.sh#L5)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Did this comment end early?
</blockquote></details>

Ah!  I forgot to remove it. It was the start of the comment above. :-p
___
*[build/teamcity-support.sh, line 9 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64780#-M_TBVEr-eVfi_cFz5p2:-M_TBVEr-eVfi_cFz5p3:b-clfkkw) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b84142d71bbb20b1ee38bebd1250ba7d41375d5/build/teamcity-support.sh#L9)):*
> ```Shell
> 
> remove_files_on_exit() {
>   rm -f ~/.ssh/id_rsa{,.pub}
> ```

This line still needs to be here. It corresponds to the `generate_ssh_key()` function at the bottom of this file.
___
*[build/release/teamcity-support.sh, line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64780#-M_3TJgUCzsr81xCnoJ4:-M_TCBUiEBCv1yLK6aMl:b-y9seaf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e6fc693ef24cc09e3ac40b11c74071d320ba2f6/build/release/teamcity-support.sh#L8)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Oh, it looks like you removed a similar line from `build/teamcity-support.sh` instead of this file (`build/release/teamcity-support.sh`).

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64780)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jlinder and @RichardJCai)

___
*[build/teamcity-diagram-generation.sh, line 3 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64780#-M_3Vr1JCoA3X7AV09lX:-M_Vz9EY8tn-UgKTxLkK:b-b28re8) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e6fc693ef24cc09e3ac40b11c74071d320ba2f6/build/teamcity-diagram-generation.sh#L3)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

Gladly!

One thing I wasn't clear on in the first comment is that the `source "$(dirname "${0}")/teamcity-common-support.sh"` line isn't necessary because that file is sourced by the `teamcity-support.sh` script.
</blockquote></details>

Ah yeah didn't notice that `teamcity-support.sh` already sources it
___
*[build/teamcity-support.sh, line 9 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64780#-M_TBVEr-eVfi_cFz5p2:-M_Vz7OuE8YMOH9TCi1Y:b-paxwgh) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b84142d71bbb20b1ee38bebd1250ba7d41375d5/build/teamcity-support.sh#L9)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

This line still needs to be here. It corresponds to the `generate_ssh_key()` function at the bottom of this file.
</blockquote></details>

Oops added back.
___
*[build/release/teamcity-support.sh, line 8 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64780#-M_3TJgUCzsr81xCnoJ4:-M_VzR8IA28ArvUqM4KX:b2pdpdl) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e6fc693ef24cc09e3ac40b11c74071d320ba2f6/build/release/teamcity-support.sh#L8)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

Oh, it looks like you removed a similar line from `build/teamcity-support.sh` instead of this file (`build/release/teamcity-support.sh`).
</blockquote></details>

Yep my mistake, fixed.

**Review by jlinder — CHANGES_REQUESTED** [review]
I noticed one last thing I missed in the last review. 

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64780#-:-M_W9o5b22FvvQzMZFkx:b-ly5o3e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[build/release/teamcity-mark-build.sh, line 4 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64780#-M_W9NFD4AlFXo00KlVO:-M_W9NFE83jskDFMb_bX:bc2cyw4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d126bf97cdd7fe956ffe3e80fd369b6faa919acc/build/release/teamcity-mark-build.sh#L4)):*
> ```Shell
> 
> source "$(dirname "${0}")/teamcity-support.sh"
> source "$(dirname "${0}")/../teamcity-support.sh"
> ```

This line is not necessary (given that `teamcity-support.sh` sources it already).

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64780)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jlinder)

___
*[build/release/teamcity-mark-build.sh, line 4 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64780#-M_W9NFD4AlFXo00KlVO:-M_WC8UZ0wGSiTxI7yGv:ba3dfob) ([raw file](https://github.com/cockroachdb/cockroach/blob/d126bf97cdd7fe956ffe3e80fd369b6faa919acc/build/release/teamcity-mark-build.sh#L4)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

This line is not necessary (given that `teamcity-support.sh` sources it already). 
</blockquote></details>

Removed

**Review by jlinder — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64780#-:-M_WCvkZ1gPWnYiJW2BX:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jlinder)

**Comment by RichardJCai** [comment]
Thanks for the review!

bors r=jlinder

**Pull request merged**
