### PR TITLE
stats: use inconsistent scans

### LINKED ISSUE #35432: stats: handle the case where auto stats take longer than the TTL
The minimum TTL we recommend in the docs is 10 minutes. With throttling, we have seen automatic statistic jobs take 2+ hours. We need to have sane behavior in a case like this. I am not sure what the current behavior is, I assume the table scanners would start getting errors and we would keep restarting the job forever.

CC @rytaft @awoods187

### PR DESCRIPTION
**Pull request by RaduBerinde**
Automated statistics run with throttling (to reduce impact on running
workloads) and can take a long time. When this time exceeds the TTL,
scans start receiving errors.

This change makes `CREATE STATISTICS ... AS OF SYSTEM TIME` use a
"moving" timestamp that keeps up with the current time. When the
timestamp is more than 5 minutes in the past, we move it up by the
amount of time that passed since the scan (so that the new timestamp
is as much in the past as the original timestamp was). The comments in
`TableReaderSpec` describe this in more detail.

Fixes #35432.

Release note (bug fix): Automated table statistics no longer encounter
"batch timestamp must be after replica GC threshold" errors on
configurations with low TTL.

I am hesitant to add even more nuance to the fetcher code but I could see no way around it. I plan on looking at creating a roachtest that reproduces #35432 and run it with and without this change.

### CODE REVIEW

**Review by andreimatei — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36500#-:-LbZk28-1Jdp_G4nrQKd:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @jordanlewis, @RaduBerinde, and @rytaft)

___
*[pkg/sql/distsqlrun/tablereader.go, line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36500#-LbZfb7zA3F2EfSBoL0K:-LbZfUEh7FoTzrhaVezM:b-8h9en1) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c345d70cb7006c3020d18d47dad651cb27ed77/pkg/sql/distsqlrun/tablereader.go#L93)):*
> ```Go
> 	tr.limitHint = limitHint(spec.LimitHint, post)
> 	tr.maxResults = spec.MaxResults
> 	tr.inconsistentScanInterval = time.Duration(spec.InconsistentScanNanos) * time.Nanosecond
> ```

nit: `time.Nanosecond` is 1, so scratch it
___
*[pkg/sql/row/fetcher.go, line 496 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36500#-LbZh9wdEtjxmCNwSGE5:-LbZh9wdEtjxmCNwSGE6:b-3khkjv) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c345d70cb7006c3020d18d47dad651cb27ed77/pkg/sql/row/fetcher.go#L496)):*
> ```Go
> 		if now.Sub(txnTime) > 2*relativeAsOfTime {
> 			// Timestamp is too old; advance it.
> 			// We could in principle recalculate the timestamp on each batch but this
> ```

nit: I'd move this comment to the proto or the spec or wherever this all starts. I thought about it for a second when I was reading the commit message to come to the same conclusion.
___
*[pkg/sql/row/fetcher.go, line 501 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36500#-LbZhcaO6bk81VHMU6Pv:-LbZhcaO6bk81VHMU6Pw:b-4g7vun) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c345d70cb7006c3020d18d47dad651cb27ed77/pkg/sql/row/fetcher.go#L501)):*
> ```Go
> 		}
> 		ts := hlc.Timestamp{WallTime: txnTime.UnixNano()}
> 		err := db.Txn(ctx, func(ctx context.Context, txn *client.Txn) error {
> ```

for symmetry  with the consistent case, I'd create a txn and call `txn.Send`, instead of calling `db.Txn()`. The difference is how retriable errors are handled, but that shouldn't matter here.
And actually, it might be worth it to reuse the same txn. I think you've asked me and I've told you to just create new transactions every time, but I didn't think we're talking about such a significant use case.

Or even better, it might be worth using non-transactional requests. Because there is a bunch of overhead to allocating transactions.
I think you can do something like 
```
b := client.Batch{Timestamp: ...}
b.Scan(...)
return db.Run(b)
```
___
*[pkg/sql/row/kv_batch_fetcher.go, line 154 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36500#-LbZgmi7AMUoRbe3bfkD:-LbZgmi7AMUoRbe3bfkE:bgi1fzn) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c345d70cb7006c3020d18d47dad651cb27ed77/pkg/sql/row/kv_batch_fetcher.go#L154)):*
> ```Go
> ) (txnKVFetcher, error) {
> 	sendFn := func(ctx context.Context, ba roachpb.BatchRequest) (*roachpb.BatchResponse, error) {
> 		res, err := txn.Send(ctx, ba)
> ```

you'll be happy know that I'm trying to make `txn.Send` return error, not pErr
___
*[pkg/sql/row/kv_batch_fetcher.go, line 161 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36500#-LbZh03d7yfuoNMIQFE7:-LbZh03d7yfuoNMIQFE8:beerabj) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c345d70cb7006c3020d18d47dad651cb27ed77/pkg/sql/row/kv_batch_fetcher.go#L161)):*
> ```Go
> 	}
> 	return makeKVBatchFetcherWithSendFunc(
> 		sendFunc(sendFn), spans, reverse, useBatchLimit, firstBatchLimit, returnRangeInfo,
> ```

do you need the cast to `sendFunc`?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36500)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @RaduBerinde, and @rytaft)

___
*[pkg/sql/row/fetcher.go, line 501 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36500#-LbZhcaO6bk81VHMU6Pv:-LbZqXiHCU4J1IEKucYJ:buq7osr) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c345d70cb7006c3020d18d47dad651cb27ed77/pkg/sql/row/fetcher.go#L501)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

for symmetry  with the consistent case, I'd create a txn and call `txn.Send`, instead of calling `db.Txn()`. The difference is how retriable errors are handled, but that shouldn't matter here.
And actually, it might be worth it to reuse the same txn. I think you've asked me and I've told you to just create new transactions every time, but I didn't think we're talking about such a significant use case.

Or even better, it might be worth using non-transactional requests. Because there is a bunch of overhead to allocating transactions.
I think you can do something like 
```
b := client.Batch{Timestamp: ...}
b.Scan(...)
return db.Run(b)
```

</blockquote></details>

actually, let's get more opinions here. Cause cross-range non-transactional requests were something that we've considered restricting in the past. Although I think that was more about the difficulties in ensuring atomicity of such batches, but that doesn't matter for reads. (the implementation will wrap the batch into a transaction transparently when it's crossing ranges, and that's pretty gross).
@bdarnell what do you think?

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36500#-:-LbZs43Q-vqm9sLkR1fv:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @jordanlewis and @RaduBerinde)

___
*[pkg/sql/distsql_plan_stats.go, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36500#-LbZqIqa9kDixbscHXYa:-LbZqIqa9kDixbscHXYb:b5wmlfe) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c345d70cb7006c3020d18d47dad651cb27ed77/pkg/sql/distsql_plan_stats.go#L89)):*
> ```Go
> 			// It is checked elsewhere that the AS OF time is in the past; this guard
> 			// is just in case.
> 			deltaNanos = 1
> ```

You check later that this should be at least 1 microsecond. Should this be 1000?

**Review by bdarnell — COMMENTED** [review]
Why is this a user-visible option in the grammar? How would a user decide when to use INCONSISTENT or not? If auto stats use INCONSISTENT mode shouldn't the explicit statement default to inconsistent too (so the new keyword would be CONSISTENT)? The consistent case will be extremely rare; is it worth even having the option?

Maybe we could make this automatic based on TTL: pick a timestamp and use it until we either finish a cycle or that timestamp's age is halfway to the TTL. That would be fully consistent in most practical configurations while falling back to inconsistent mode for short TTLs. 

> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36500#-:-LbZvoYh17IIJ0L8MYB7:bh8dg3s)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @andreimatei, @jordanlewis, and @RaduBerinde)

___
*[pkg/sql/row/fetcher.go, line 501 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36500#-LbZhcaO6bk81VHMU6Pv:-LbZv2K47_G-Bh2HL1Fa:b-mdysu5) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c345d70cb7006c3020d18d47dad651cb27ed77/pkg/sql/row/fetcher.go#L501)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

actually, let's get more opinions here. Cause cross-range non-transactional requests were something that we've considered restricting in the past. Although I think that was more about the difficulties in ensuring atomicity of such batches, but that doesn't matter for reads. (the implementation will wrap the batch into a transaction transparently when it's crossing ranges, and that's pretty gross).
@bdarnell what do you think?
</blockquote></details>

I think I'd rather go through a transaction here for consistency with the regular use of AOST. (but one transaction and reuse it until we have to reset the timestamp instead of one per batch, if we're concerned about the allocation cost).

**Comment by RaduBerinde** [comment]
It is in the grammar because the automatic stats code issues the command as a SQL statement. I wasn't planning on documenting the option (or the throttling option) for users.

When a user issues a `CREATE STATISTICS` manually they probably expect it to use a consistent snapshot of the table. At least this was the case until now. I don't see a problem with providing that. Also, `INCONSISTENT` requires `AS OF SYSTEM TIME` so it would feel strange if by default the statement cannot be issued without AOST. Using an implicit AOST by default would be problematic, in cases where users call it right after a schema change or similar.

Finally, there may be testing scenarios where we want consistent scans so I'd be hesitant to remove that possibility altogether.

**Comment by RaduBerinde** [comment]
> Maybe we could make this automatic based on TTL: pick a timestamp and use it until we either finish a cycle or that timestamp's age is halfway to the TTL. That would be fully consistent in most practical configurations while falling back to inconsistent mode for short TTLs.

I can look into something like this. The TTL could be changed during the operation though so there would be some difficulty there (not sure how to plumb that to the distsql processor).

**Comment by bdarnell** [comment]
> When a user issues a CREATE STATISTICS manually they probably expect it to use a consistent snapshot of the table. 

I doubt that users would have expectations that are that detailed. (and if so, I think we should probably tamp down those expectations - we should give ourselves permission to make the stats as approximate as we want as long as it's useful to the optimizer. If you want consistent information, write your own query that computes the stats you want)

> Using an implicit AOST by default would be problematic, in cases where users call it right after a schema change or similar.

We could solve that the same way we do for the auto stats job itself: sleep for enough time that our default AOST delay is in the past.

**Review by jordanlewis — APPROVED** [review]
:lgtm: regarding the changes to the fetcher

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36500#-:-Lb_EeFo1wGdF0MyH4JH:b-s4j9f9)* status: :shipit: complete! 3 of 0 LGTMs obtained (waiting on @andreimatei, @jordanlewis, and @RaduBerinde)

**Review by RaduBerinde — COMMENTED** [review]
I let this sit until the release and only now got back to working on it. Sorry for letting this much time pass.

I updated the change: I removed the special syntax; we use the new mechanism whenever AS OF SYSTEM TIME is used. I also updated the mechanism, we now use a timestamp until it becomes 5 minutes old, at which point we move it up.

I plan to work on a roach test with a large table in a low TTL scenario but it will be a separate PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36500#-:-LeqbnD52DJoBi0EHlsm:b-gmneae)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 3 stale) (waiting on @andreimatei, @bdarnell, and @rytaft)

___
*[pkg/sql/distsql_plan_stats.go, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36500#-LbZqIqa9kDixbscHXYa:-LeqdMazE-GfLYqksMLb:bwi3m9z) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c345d70cb7006c3020d18d47dad651cb27ed77/pkg/sql/distsql_plan_stats.go#L89)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

You check later that this should be at least 1 microsecond. Should this be 1000?
</blockquote></details>

Changed this code altogether.
___
*[pkg/sql/row/fetcher.go, line 496 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36500#-LbZh9wdEtjxmCNwSGE5:-LeqdSpJ8QLmJw6pUZeP:b-f0q6r) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c345d70cb7006c3020d18d47dad651cb27ed77/pkg/sql/row/fetcher.go#L496)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: I'd move this comment to the proto or the spec or wherever this all starts. I thought about it for a second when I was reading the commit message to come to the same conclusion.
</blockquote></details>

The TableReaderSpec now describes exactly how the ts gets advanced.
___
*[pkg/sql/row/fetcher.go, line 501 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36500#-LbZhcaO6bk81VHMU6Pv:-Leqcm527Af2F6wOaUX9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c345d70cb7006c3020d18d47dad651cb27ed77/pkg/sql/row/fetcher.go#L501)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I think I'd rather go through a transaction here for consistency with the regular use of AOST. (but one transaction and reuse it until we have to reset the timestamp instead of one per batch, if we're concerned about the allocation cost). 
</blockquote></details>

Done.
___
*[pkg/sql/row/kv_batch_fetcher.go, line 161 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36500#-LbZh03d7yfuoNMIQFE7:-LeqcyfVD543ed6wupm2:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/51c345d70cb7006c3020d18d47dad651cb27ed77/pkg/sql/row/kv_batch_fetcher.go#L161)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

do you need the cast to `sendFunc`?
</blockquote></details>

Removed.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 19 of 19 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36500#-:-Lesy8RC1jFcMmnCGRiN:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @andreimatei and @RaduBerinde)

___
*[pkg/sql/distsqlrun/tablereader.go, line 54 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36500#-Lesvz4J6qA3m_V_Om9b:-Lesvz4J6qA3m_V_Om9c:b-62vzwz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2513a95fdf095a1028c6b1ce4e1ff0a163d3f21/pkg/sql/distsqlrun/tablereader.go#L54)):*
> ```Go
> 	maxResults uint64
> 
> 	// See TableReaderSpec.InconsistentScanNanos.
> ```

Update comment

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36500)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 3 stale) (waiting on @andreimatei and @rytaft)

___
*[pkg/sql/distsqlrun/tablereader.go, line 54 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36500#-Lesvz4J6qA3m_V_Om9b:-Ley1pj40qHQAGRaXDuQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2513a95fdf095a1028c6b1ce4e1ff0a163d3f21/pkg/sql/distsqlrun/tablereader.go#L54)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Update comment
</blockquote></details>

Done.

**Review by andreimatei — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36500#-:-Lf-kRrqAkHKIQRB7DRH:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @andreimatei and @rytaft)

**Comment by RaduBerinde** [comment]
Added a test. Thanks to @andreimatei and @tbg for helping me write it!

**Review by rytaft — APPROVED** [review]
Nice test! :lgtm:

> Reviewed 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36500#-:-Lf2-kCN1yK4qeBfy068:ba34cbf)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @andreimatei)

**Comment by RaduBerinde** [comment]
Disabled the test under race (the initial data insertion can take very long in race mode).

**Pull request merged**
