### PR TITLE
storage: fix a nasty merge deadlock

### PR DESCRIPTION
**Pull request by benesch**
Fix a nasty edge case which could cause a concurrent merge and split to
deadlock. See the comment on TestStoreRangeMergeConcurrentSplit for
details.

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29324#-:-LL8oxJF-2SoZzJcAuuu:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/client_merge_test.go, line 1000 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29324#-LL8l45QD_VzyZNARvwE:-LL8l45QD_VzyZNARvwF:b-mb0p73) ([raw file](https://github.com/cockroachdb/cockroach/blob/574b40292345b49a2945593716134c94e51c4503/pkg/storage/client_merge_test.go#L1000)):*
> ```Go
> // meta2 to be resolved. Unfortunately, in this case, the range lookup would see
> // the merge's intent, but rather than resolving the intent directly, it would
> // notice that the split was already atte50mpting to resolve the intent, and so it
> ```

50mpting
___
*[pkg/storage/client_merge_test.go, line 1006 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29324#-LL8mGfJ3ESvgHDUih2G:-LL8mGfJ3ESvgHDUih2H:b-91exmp) ([raw file](https://github.com/cockroachdb/cockroach/blob/574b40292345b49a2945593716134c94e51c4503/pkg/storage/client_merge_test.go#L1006)):*
> ```Go
> //
> // Now, the watcher goroutine sends a PushTransaction directly to the merge
> // transaction to avoid deadlock.
> ```

Still a little unclear about some of the parts. So we have the split txn waiting for the merge intent on meta2 to disappear, right? And the split is actually aborted but doesn't know it (for Q is locked, and that's where that info lives).

In the contention queue, I imagine that the split is at the head of the queue but is actually stuck querying its own transaction record on Q? Feels that that operation should have a timeout; if a txn can't update its own status within (say) a heartbeat interval, sound like it should do something to let someone else try.
___
*[pkg/storage/replica.go, line 2848 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29324#-LL8ooZD0eXwtk4tCT7U:-LL8ooZD0eXwtk4tCT7V:b-ll9eip) ([raw file](https://github.com/cockroachdb/cockroach/blob/574b40292345b49a2945593716134c94e51c4503/pkg/storage/replica.go#L2848)):*
> ```Go
> 				case <-r.store.stopper.ShouldQuiesce():
> 					// The server is shutting down. The error while fetching the range
> 					// descriptor was probably caused by the shutdown, so ignore it.
> ```

Can't this cause shutdown to stall? Hmm, don't see a better way to handle this.
___
*[pkg/storage/replica.go, line 2865 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29324#-LL8obZ2CbZqsK1UacdD:-LL8obZ2CbZqsK1UacdE:b4ukhoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/574b40292345b49a2945593716134c94e51c4503/pkg/storage/replica.go#L2865)):*
> ```Go
> 			r.mu.Unlock()
> 			return
> 		}
> ```

log.Fatal(ctx, "unreachable")

**Review by benesch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29324)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/client_merge_test.go, line 1000 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29324#-LL8l45QD_VzyZNARvwE:-LLC2v0y4x2eZMVIHUtP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/574b40292345b49a2945593716134c94e51c4503/pkg/storage/client_merge_test.go#L1000)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

50mpting
</blockquote></details>

Done.
___
*[pkg/storage/client_merge_test.go, line 1006 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29324#-LL8mGfJ3ESvgHDUih2G:-LLBrwP6EgIX1AcHa9tI:bfqxprl) ([raw file](https://github.com/cockroachdb/cockroach/blob/574b40292345b49a2945593716134c94e51c4503/pkg/storage/client_merge_test.go#L1006)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Still a little unclear about some of the parts. So we have the split txn waiting for the merge intent on meta2 to disappear, right? And the split is actually aborted but doesn't know it (for Q is locked, and that's where that info lives).

In the contention queue, I imagine that the split is at the head of the queue but is actually stuck querying its own transaction record on Q? Feels that that operation should have a timeout; if a txn can't update its own status within (say) a heartbeat interval, sound like it should do something to let someone else try.
</blockquote></details>

I captured a log that explains the situation better than I can:

https://gist.githubusercontent.com/benesch/b1f7cc0c15335a139b12eb9f9ca9a409/raw/154078c9bce67ee79fb260316037cf152e8c8172/merge%2520deadlock%2520log.txt

You were right that my understanding was subtly wrong. I've updated the comment text accordingly.
___
*[pkg/storage/replica.go, line 2848 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29324#-LL8ooZD0eXwtk4tCT7U:-LLC2wfMD5fs-7grF5vH:b-r9xkj1) ([raw file](https://github.com/cockroachdb/cockroach/blob/574b40292345b49a2945593716134c94e51c4503/pkg/storage/replica.go#L2848)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Can't this cause shutdown to stall? Hmm, don't see a better way to handle this.
</blockquote></details>

Ack. It's no worse than it was before, I think.
___
*[pkg/storage/replica.go, line 2865 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29324#-LL8obZ2CbZqsK1UacdD:-LLC2vUi6Rk01BeoSg4-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/574b40292345b49a2945593716134c94e51c4503/pkg/storage/replica.go#L2865)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

log.Fatal(ctx, "unreachable")
</blockquote></details>

Done.

**Review by nvb — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29324)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/client_merge_test.go, line 991 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29324#-LLCmeZs0TpuFcVIS9GR:-LLCmeZs0TpuFcVIS9GS:b-exjnb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6fe326ad39119933beed1c02e60a8a6a7a18c34/pkg/storage/client_merge_test.go#L991)):*
> ```Go
> // range descriptor, then tries to update Q's meta2 range descriptor, but runs
> // into the merge's intent and attempts to push the merge. Since the split has
> // the same priority as the merge, this amounts to waiting for the merge to
> ```

Priorities aren't really used now, so this is a bit misleading. The split would only not wait for the merge if the split had max priority or the merge had min priority. Up to you whether it's worth clarifying the comment.
___
*[pkg/storage/client_merge_test.go, line 995 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29324#-LLCngYU7OlMclS-kGWU:-LLCngYU7OlMclS-kGWV:bk425e5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6fe326ad39119933beed1c02e60a8a6a7a18c34/pkg/storage/client_merge_test.go#L995)):*
> ```Go
> // into the split's intent. While pushing the split, the merge realizes that
> // waiting for the split to complete would cause deadlock, so it aborts the
> // split instead.
> ```

We talked about this a bit in person, but this deadlock and corresponding fallout still sounds primarily to me like a failure to order writes consistently between the split txn and the merge txn. The fix here is probably a good one regardless, but would all of this go away if both split and merge txns agreed upon an ordering for writing to the local and meta range descriptors? 

Is there a reason why they need to be opposite each other? Does it have to do with where we need the transaction records to end up?

**Comment by benesch** [comment]
Yeah, I think we need to make this change no matter what because relying on
the ordering of keys touched to avoid deadlock is always going to be subtle
and finicky. At some point we’re going to speed up split txns by sending
basically everything in parallel, and then we can’t guarantee an ordering
at all.

And merges already have this problem! They send the meta2 and local update
in the same batch, which gets split and parallelized arbitrarily by
DistSender. Serializing that to avoid deadlock seems like a shame. This
case will be pretty rare in practice since the split and merge queues won’t
operate on the same range. It requires an automatic merge to occur
concurrently with a manual split to the RHS.

I’ll fix that thing about priorities.

**Review by benesch — COMMENTED** [review]
Ok, going to merge on Tobi's LGTM so I can hopefully get merges re-enabled before the weekend is up. @nvanbenschoten let me know if you have any post-merge feedback.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29324#-:-LLLqz4y2w6gekkakZro:bm9sb0q)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/client_merge_test.go, line 991 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29324#-LLCmeZs0TpuFcVIS9GR:-LLLq_VPA36KDrGvi4TE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6fe326ad39119933beed1c02e60a8a6a7a18c34/pkg/storage/client_merge_test.go#L991)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Priorities aren't really used now, so this is a bit misleading. The split would only not wait for the merge if the split had max priority or the merge had min priority. Up to you whether it's worth clarifying the comment.
</blockquote></details>

Done.
___
*[pkg/storage/client_merge_test.go, line 995 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29324#-LLCngYU7OlMclS-kGWU:-LLLqnFx9uUnrc9JpF2B:b6dkjw5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6fe326ad39119933beed1c02e60a8a6a7a18c34/pkg/storage/client_merge_test.go#L995)):*
Copying and pasting from the GitHub comment so that it's inline with the Reviewable discussion:

> Yeah, I think we need to make this change no matter what because relying on
> the ordering of keys touched to avoid deadlock is always going to be subtle
> and finicky. At some point we’re going to speed up split txns by sending
> basically everything in parallel, and then we can’t guarantee an ordering
> at all.
> 
> And merges already have this problem! They send the meta2 and local update
> in the same batch, which gets split and parallelized arbitrarily by
> DistSender. Serializing that to avoid deadlock seems like a shame. This
> case will be pretty rare in practice since the split and merge queues won’t
> operate on the same range. It requires an automatic merge to occur
> concurrently with a manual split to the RHS.

**Review by nvb — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29324#-:-LLLroXZ81Yo81XNbIjy:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/storage/client_merge_test.go, line 995 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29324#-LLCngYU7OlMclS-kGWU:-LLLrgNI0ip884DhQayD:bnoczzl) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6fe326ad39119933beed1c02e60a8a6a7a18c34/pkg/storage/client_merge_test.go#L995)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Copying and pasting from the GitHub comment so that it's inline with the Reviewable discussion:

> Yeah, I think we need to make this change no matter what because relying on
> the ordering of keys touched to avoid deadlock is always going to be subtle
> and finicky. At some point we’re going to speed up split txns by sending
> basically everything in parallel, and then we can’t guarantee an ordering
> at all.
> 
> And merges already have this problem! They send the meta2 and local update
> in the same batch, which gets split and parallelized arbitrarily by
> DistSender. Serializing that to avoid deadlock seems like a shame. This
> case will be pretty rare in practice since the split and merge queues won’t
> operate on the same range. It requires an automatic merge to occur
> concurrently with a manual split to the RHS.
</blockquote></details>

Ok, that makes sense. Thanks for the explanation.

**Comment by benesch** [comment]
👍 👍 👍 

bors r=tschottdorf,nvanbenschoten

**Pull request merged**
