### PR TITLE
*: use go-deadlock in race builds

### LINKED ISSUE #7972: Potential deadlock between Gossip.SetStorage and Node.gossipStores (inconsistent lock order)
It seems that Gossip.SetStorage and  Node.gossipStores grab mutexes in different order.

My understanding is: 

* Gossip.SetStorage grabs gossip lock, calls ReadBootstrapInfo which grabs stores rlock.
* Node.gossipStores calls VisitStores, which grabs stores rlock, in the closure: Gossip.AddInfoProto->AddInfo, which grabs gossip lock.

Steps to reporoduce (@5151da6461852f57785db18511efd8ccf918b39c), using [go-deadlock](https://github.com/sasha-s/go-deadlock/):

```sh
go get github.com/sasha-s/go-deadlock/...
cd src/github.com/cockroachdb
find . -name "*.go" | xargs -n 1 sed -i '' 's/sync.RWMutex/deadlock.RWMutex/'
find . -name "*.go" | xargs -n 1 sed -i '' 's/sync.Mutex/deadlock.Mutex/'
goimports -w .
cd cockroach
make acceptance TESTS='' TESTFLAGS='-v -d 1200s -l .' TESTTIMEOUT=1210s
```
look into acceptance/TestDockerC/roach*/stderr.*

Stack traces from go-deadlock:
```
POTENTIAL DEADLOCK: Inconsistent locking. saw this ordering in one goroutine:
happened before
src/github.com/cockroachdb/cockroach/gossip/gossip.go:261 gossip.(*Gossip).SetStorage { g.mu.Lock() } <<<<<
src/github.com/cockroachdb/cockroach/server/node.go:437 server.(*Node).initStores { if err := n.ctx.Gossip.SetStorage(n.stores); err != nil { }
src/github.com/cockroachdb/cockroach/server/node.go:332 server.(*Node).start { if err := n.initStores(engines, n.stopper); err != nil { }
src/github.com/cockroachdb/cockroach/server/server.go:402 server.(*Server).Start { if err := s.node.start(unresolvedAddr, s.ctx.Engines, s.ctx.NodeAttributes); err != nil { }
src/github.com/cockroachdb/cockroach/cli/start.go:341 cli.runStart { if err := s.Start(); err != nil { }
src/github.com/spf13/cobra/command.go:600 cobra.(*Command).execute ???
src/github.com/spf13/cobra/command.go:690 cobra.(*Command).ExecuteC ???
src/github.com/spf13/cobra/command.go:649 cobra.(*Command).Execute ???
src/github.com/cockroachdb/cockroach/cli/cli.go:95 cli.Run { return cockroachCmd.Execute() }
src/github.com/cockroachdb/cockroach/main.go:37 main.main { if err := cli.Run(os.Args[1:]); err != nil { }
/usr/local/go/src/runtime/proc.go:188 runtime.main { main_main() }

happened after
src/github.com/cockroachdb/cockroach/storage/stores.go:279 storage.(*Stores).ReadBootstrapInfo { ls.mu.RLock() } <<<<<
src/github.com/cockroachdb/cockroach/gossip/gossip.go:267 gossip.(*Gossip).SetStorage { err := storage.ReadBootstrapInfo(&storedBI) }
src/github.com/cockroachdb/cockroach/server/node.go:437 server.(*Node).initStores { if err := n.ctx.Gossip.SetStorage(n.stores); err != nil { }
src/github.com/cockroachdb/cockroach/server/node.go:332 server.(*Node).start { if err := n.initStores(engines, n.stopper); err != nil { }
src/github.com/cockroachdb/cockroach/server/server.go:402 server.(*Server).Start { if err := s.node.start(unresolvedAddr, s.ctx.Engines, s.ctx.NodeAttributes); err != nil { }
src/github.com/cockroachdb/cockroach/cli/start.go:341 cli.runStart { if err := s.Start(); err != nil { }
src/github.com/spf13/cobra/command.go:600 cobra.(*Command).execute ???
src/github.com/spf13/cobra/command.go:690 cobra.(*Command).ExecuteC ???
src/github.com/spf13/cobra/command.go:649 cobra.(*Command).Execute ???
src/github.com/cockroachdb/cockroach/cli/cli.go:95 cli.Run { return cockroachCmd.Execute() }
src/github.com/cockroachdb/cockroach/main.go:37 main.main { if err := cli.Run(os.Args[1:]); err != nil { }
/usr/local/go/src/runtime/proc.go:188 runtime.main { main_main() }

in another goroutine: happened before
src/github.com/cockroachdb/cockroach/storage/stores.go:118 storage.(*Stores).VisitStores { ls.mu.RLock() } <<<<<
src/github.com/cockroachdb/cockroach/server/node.go:588 server.(*Node).gossipStores { if err := n.stores.VisitStores(func(s *storage.Store) error { }
src/github.com/cockroachdb/cockroach/server/node.go:568 server.(*Node).startGossip.func1 { n.gossipStores() // one-off run before going to sleep }
src/github.com/cockroachdb/cockroach/util/stop/stopper.go:180 stop.(*Stopper).RunWorker.func1 { f() }

happend after
src/github.com/cockroachdb/cockroach/gossip/gossip.go:545 gossip.(*Gossip).AddInfo { g.mu.Lock() } <<<<<
src/github.com/cockroachdb/cockroach/gossip/gossip.go:561 gossip.(*Gossip).AddInfoProto { return g.AddInfo(key, bytes, ttl) }
src/github.com/cockroachdb/cockroach/storage/store.go:1341 storage.(*Store).GossipStore { if err := s.ctx.Gossip.AddInfoProto(gossipStoreKey, storeDesc, ttlStoreGossip); err != nil { }
src/github.com/cockroachdb/cockroach/server/node.go:589 server.(*Node).gossipStores.func1 { s.GossipStore() }
src/github.com/cockroachdb/cockroach/storage/stores.go:121 storage.(*Stores).VisitStores { if err := visitor(s); err != nil { }
src/github.com/cockroachdb/cockroach/server/node.go:588 server.(*Node).gossipStores { if err := n.stores.VisitStores(func(s *storage.Store) error { }
src/github.com/cockroachdb/cockroach/server/node.go:568 server.(*Node).startGossip.func1 { n.gossipStores() // one-off run before going to sleep }
src/github.com/cockroachdb/cockroach/util/stop/stopper.go:180 stop.(*Stopper).RunWorker.func1 { f() }
```

### PR DESCRIPTION
**Pull request by tamird**
Fixes #7972.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8011)

### CODE REVIEW

**Comment by sasha-s** [comment]
Review status: 0 of 67 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[util/syncutil/mutex_deadlock.go, line 21 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8011#-KNYr1ZyNa38Eb0W2jtU:-KNYr1ZyNa38Eb0W2jtV:-367178224) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a21c7f620781112026b56f9b3f6030097b429d1/util/syncutil/mutex_deadlock.go#L21)):*
> ```Go
> package syncutil
> 
> import deadlock "github.com/sasha-s/go-deadlock"
> ```

Deadlock is doing os.Exit(2) by default when it sees a potential deadlock.
If that's not what you need, you might want to change deadlock.Opts.OnPotentialDeadlock in init.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8011)*

**Comment by tamird** [comment]
Review status: 0 of 67 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[util/syncutil/mutex_deadlock.go, line 21 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8011#-KNYr1ZyNa38Eb0W2jtU:-KNYrq0FfOj_wlgW4MmQ:1204254941) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a21c7f620781112026b56f9b3f6030097b429d1/util/syncutil/mutex_deadlock.go#L21)):*
<details><summary><i>Previously, sasha-s wrote…</i></summary>
> Deadlock is doing os.Exit(2) by default when it sees a potential deadlock.
> If that's not what you need, you might want to change deadlock.Opts.OnPotentialDeadlock in init.
</details>
Yeah, I saw. @mberhault any opinions on this? Will affect rho.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8011)*

**Comment by bdarnell** [comment]
Can you put the substantive changes (e.g. gossip.go, and maybe others I haven't found) in a separate commit from the one that does `s/sync.Mutex/syncutil.Mutex/g`?

---

Review status: 0 of 67 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8011#-:-KNYv8LRHqM4ohc3_vYB:-291743458)*

**Comment by tamird** [comment]
@bdarnell done.

---

Review status: 0 of 67 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8011#-:-KNYwSH77jY4uqGJKUc3:-2027757103)*

**Comment by bdarnell** [comment]
LGTM.

Since CI is failing in non-trivial ways and updating this PR is going to be painful, you may want to merge the renaming to use syncutil everywhere without making syncutil use go-deadlock. 

---

Review status: 0 of 67 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[build/check-style.sh, line 39 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8011#-KNYz_VKE5DO9K9d7moV:-KNYz_VKE5DO9K9d7moW:-1247436004) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aa9ba217995bf14e2e6a8933bc2b58480af39f4/build/check-style.sh#L39)):*
> ```Shell
> TestSyncMutex() {
>   echo "checking for sync.Mutex usage (use syncutil.Mutex instead)"
>   ! git grep -nE 'sync\.Mutex' -- '*.go' | grep -vE '^util/syncutil/mutex_sync\.go\b'
> ```

`sync\.(RW)?Mutex`

---

*[util/syncutil/mutex_deadlock.go, line 21 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8011#-KNYr1ZyNa38Eb0W2jtU:-KNYy2AqNV73-pWZNOfr:1666618519) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a21c7f620781112026b56f9b3f6030097b429d1/util/syncutil/mutex_deadlock.go#L21)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Yeah, I saw. @mberhault any opinions on this? Will affect rho.
</details>
I think ideally I'd like this to work like the race detector: log it (and in tests report the test as failed), but don't kill the process. But if that's a pain (and integrating it with the test reporting might be trouble), I'm ok with just killing the process (even on rho).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8011#-:-KNZ-5AaUnLToBY_S7BS:-233576834)*

**Comment by tamird** [comment]
Review status: 0 of 67 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[build/check-style.sh, line 39 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8011#-KNYz_VKE5DO9K9d7moV:-KNZ04CFAS4bKi0ZQ6xw:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/4aa9ba217995bf14e2e6a8933bc2b58480af39f4/build/check-style.sh#L39)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> `sync\.(RW)?Mutex`
</details>
Done.

---

*[util/syncutil/mutex_deadlock.go, line 21 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8011#-KNYr1ZyNa38Eb0W2jtU:-KNZ06lvjmfE2FjHeKl3:-480130792) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a21c7f620781112026b56f9b3f6030097b429d1/util/syncutil/mutex_deadlock.go#L21)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> I think ideally I'd like this to work like the race detector: log it (and in tests report the test as failed), but don't kill the process. But if that's a pain (and integrating it with the test reporting might be trouble), I'm ok with just killing the process (even on rho).
</details>
We could piggyback on leaktest in order to get a handle to the `testing.T`, perhaps?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8011)*

**Comment by mberhault** [comment]
Review status: 0 of 67 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[util/syncutil/mutex_deadlock.go, line 21 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8011#-KNYr1ZyNa38Eb0W2jtU:-KNZ2bpUAR5djNdptF98:1409195833) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a21c7f620781112026b56f9b3f6030097b429d1/util/syncutil/mutex_deadlock.go#L21)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> We could piggyback on leaktest in order to get a handle to the `testing.T`, perhaps?
</details>
I prefer having the option of dying of not (the race detector has that option), but as long as we don't get false positives, I don't mind exits too much.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8011)*

**Comment by bdarnell** [comment]
Review status: 0 of 67 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[util/syncutil/mutex_deadlock.go, line 21 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8011#-KNYr1ZyNa38Eb0W2jtU:-KNZ2dBQW8J5r2R-dTd0:2137008776) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a21c7f620781112026b56f9b3f6030097b429d1/util/syncutil/mutex_deadlock.go#L21)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary>
> I prefer having the option of dying of not (the race detector has that option), but as long as we don't get false positives, I don't mind exits too much.
</details>
You mean have `leaktest` put the `testing.T` in a public global?  Eww. What I had in mind with integrating it with test reporting was to parse it out of the logs like go2xunit does for races: https://bitbucket.org/tebeka/go2xunit/src/bca3a606b7abccfdfcab96b2a532becba46dceeb/parsers.go?fileviewer=file-view-default#parsers.go-47

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8011)*

**Comment by tamird** [comment]
Review status: 0 of 67 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[util/syncutil/mutex_deadlock.go, line 21 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8011#-KNYr1ZyNa38Eb0W2jtU:-KNZ3J_XOu58hM5zhy1p:-688009735) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a21c7f620781112026b56f9b3f6030097b429d1/util/syncutil/mutex_deadlock.go#L21)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> You mean have `leaktest` put the `testing.T` in a public global?  Eww. What I had in mind with integrating it with test reporting was to parse it out of the logs like go2xunit does for races: https://bitbucket.org/tebeka/go2xunit/src/bca3a606b7abccfdfcab96b2a532becba46dceeb/parsers.go?fileviewer=file-view-default#parsers.go-47
</details>
Ew indeed.

Well, I guess I'll leave it as-is for now, especially since we're not going to use go-deadlock for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8011)*

**Pull request merged**
