### PR TITLE
*: stop embedding mocks in libraries

### PR DESCRIPTION
**Pull request by ajwerner**
We were doing something bad before this PR, we were embedding mock implementations of abstractions into the library packages which defined those interfaces. That meant that the `cockroach` binary was depending on `gomock` which it should not. It also meant that we could not avoid re-generating those mock sources whenever any of their deps changed. This led to a pretty bad cascade of dependencies which slowed the build down. 

In most cases, we only ever imported the mocks in the package itself. In those cases, move the mocks to an `_test.go` file. In some cases, we were importing them into other package's tests. In those cases, move the mocks to subpackages.

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]
Thanks for cleaning this up, can't have been fun. A test or linter to avoid importing this into builds seems important, that wasn't in my mind at all last time I was wrangling with mocks. 

Also rather satisfying to get rid of the Bazel acrobatics for building these. Does this still work properly with Gazelle generation?

I haven't reviewed this in detail, but the overall direction seems reasonable.

**Comment by ajwerner** [comment]
> Does this still work properly with Gazelle generation?

Yes, I'm reasonably certain I didn't break anything regarding gazelle. 

>  A test or linter to avoid importing this into builds seems important, that wasn't in my mind at all last time I was wrangling with mocks.

+1

**Comment by ajwerner** [comment]
The bazel CI failure is a flake fixed by https://github.com/cockroachdb/cockroach/pull/76125

**Comment by ajwerner** [comment]
I'm taking @erikgrinaker's approval

bors r+

**Pull request merged**
