### PR TITLE
sql: deflake TestSavepoints

### LINKED ISSUE #70220: sql: TestSavepoints failed
sql.TestSavepoints [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3443717&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3443717&tab=artifacts#/) on master @ [a79a08268cbaad620d2e2dc0c3e19dd670795a1a](https://github.com/cockroachdb/cockroach/commits/a79a08268cbaad620d2e2dc0c3e19dd670795a1a):

```
=== RUN   TestSavepoints
    test_log_scope.go:76: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestSavepoints887684322
    test_log_scope.go:77: use -show-logs to present logs inline
=== CONT  TestSavepoints
    panic.go:613: -- test log scope end --
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestSavepoints887684322
--- FAIL: TestSavepoints (1.14s)
=== RUN   TestSavepoints/rollback_after_lock_timeout
    conn_executor_savepoints_test.go:107: 7: reading progress: pq: canceling statement due to lock timeout on row (conn,n)=('default',3) in progress@primary
    datadriven.go:243: 
        testdata/savepoints:265: SET lock_timeout = '1ms'
        BEGIN
        SAVEPOINT foo
        SELECT * FROM t WHERE x = 1 FOR UPDATE
        ROLLBACK TO SAVEPOINT foo
        SELECT * FROM t WHERE x = 2 FOR UPDATE
        COMMIT
        SET lock_timeout = 0
        output didn't match expected:
        @@ -9,9 +9,9 @@
         5: ROLLBACK TO SAVEPOINT foo -- 0 rows
         -- Aborted     -> Open        ###.....  foo
         6: SELECT * FROM t WHERE x = 2 FOR UPDATE -- 0 rows
         -- Open        -> Open        ###..#..  foo
         7: COMMIT -- 0 rows
        --- Open        -> NoTxn       ###..##.  (none)
        +-- Open        -> NoTxn       ........  (none)
         8: SET lock_timeout = 0 -- 0 rows
         -- NoTxn       -> NoTxn       ###..###  (none)
         
    --- FAIL: TestSavepoints/rollback_after_lock_timeout (0.10s)
```
<details><summary>Reproduce</summary>
<p>
To reproduce, try:

```bash
make stressrace TESTS=TestSavepoints PKG=./pkg/sql TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```
Parameters in this failure:

- GOFLAGS=-json
</p>
</details>
/cc @cockroachdb/sql-queries andreimatei
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestSavepoints.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #72911: sql: TestSavepoints failed
sql.TestSavepoints [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3755382&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3755382&tab=artifacts#/) on release-21.2 @ [de3aa0be93809feccd8040bf55cdbb8bea8cb1e9](https://github.com/cockroachdb/cockroach/commits/de3aa0be93809feccd8040bf55cdbb8bea8cb1e9):

```
=== RUN   TestSavepoints
    test_log_scope.go:79: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestSavepoints595601019
    test_log_scope.go:80: use -show-logs to present logs inline
=== CONT  TestSavepoints
    panic.go:613: -- test log scope end --
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestSavepoints595601019
--- FAIL: TestSavepoints (1.42s)
=== RUN   TestSavepoints/rollback_after_lock_timeout
    conn_executor_savepoints_test.go:107: 7: reading progress: pq: canceling statement due to lock timeout on row (conn,n)=('default',3) in progress@primary
    datadriven.go:243: 
        testdata/savepoints:265: SET lock_timeout = '1ms'
        BEGIN
        SAVEPOINT foo
        SELECT * FROM t WHERE x = 1 FOR UPDATE
        ROLLBACK TO SAVEPOINT foo
        SELECT * FROM t WHERE x = 2 FOR UPDATE
        COMMIT
        SET lock_timeout = 0
        output didn't match expected:
        @@ -9,9 +9,9 @@
         5: ROLLBACK TO SAVEPOINT foo -- 0 rows
         -- Aborted     -> Open        ###.....  foo
         6: SELECT * FROM t WHERE x = 2 FOR UPDATE -- 0 rows
         -- Open        -> Open        ###..#..  foo
         7: COMMIT -- 0 rows
        --- Open        -> NoTxn       ###..##.  (none)
        +-- Open        -> NoTxn       ........  (none)
         8: SET lock_timeout = 0 -- 0 rows
         -- NoTxn       -> NoTxn       ###..###  (none)
         
    --- FAIL: TestSavepoints/rollback_after_lock_timeout (0.08s)
```
<details><summary>Reproduce</summary>
<p>
To reproduce, try:

```bash
make stressrace TESTS=TestSavepoints PKG=./pkg/sql TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```
Parameters in this failure:

- GOFLAGS=-json
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #70220 sql: TestSavepoints failed [C-test-failure O-robot T-kv T-sql-queries branch-master]
</p>
</details>
/cc @cockroachdb/sql-queries andreimatei
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestSavepoints.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by nvb**
Fixes #70220.
Fixes #72911.

This commit deflakes `TestSavepoints` by running the manipulation of the
`progress` table in a separate SQL connection. This connection is not
subject to the lock_timeout or any other session settings that may be
configured on the other SQL connections in the test.

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73388)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @rytaft)

___
*[pkg/sql/conn_executor_savepoints_test.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73388#-MpwGJzg8h-LunrflT0g:-MpwGJzg8h-LunrflT0h:b-9tor0d) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8145c944393e3737f4700e6d92c1bef5851f3fb/pkg/sql/conn_executor_savepoints_test.go#L50)):*
> ```Go
> 				return conn
> 			}
> 			conn = serverutils.OpenDBConn(
> ```

this is too heavy weight I think. You're creating a new connection pool when all you want is one connection. There's `DB.Conn()` instead, isn't there?

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73388)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @rytaft)

___
*[pkg/sql/conn_executor_savepoints_test.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73388#-MpwGJzg8h-LunrflT0g:-MpwI843EUnQur1pG82V:blbsas3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8145c944393e3737f4700e6d92c1bef5851f3fb/pkg/sql/conn_executor_savepoints_test.go#L50)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

this is too heavy weight I think. You're creating a new connection pool when all you want is one connection. There's `DB.Conn()` instead, isn't there?
</blockquote></details>

Is this creating a new connection pool? This is the same code that's in `serverutils.StartServer` (where `origConn` came from). And I don't see a `DB.Conn()`.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73388)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @rytaft)

___
*[pkg/sql/conn_executor_savepoints_test.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73388#-MpwGJzg8h-LunrflT0g:-MpwJ53v-W70BrD4-65J:bxojok8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8145c944393e3737f4700e6d92c1bef5851f3fb/pkg/sql/conn_executor_savepoints_test.go#L50)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this creating a new connection pool? This is the same code that's in `serverutils.StartServer` (where `origConn` came from). And I don't see a `DB.Conn()`.
</blockquote></details>

`origConn` is a conn pool (a `sql.DB`).
Here's the `Conn`.
https://pkg.go.dev/database/sql#DB.Conn

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73388#-:-MpwUm3y2n_Pipoqehtn:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73388)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/sql/conn_executor_savepoints_test.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73388#-MpwGJzg8h-LunrflT0g:-Mpwa42lEDUV1HkqofDt:b20dqzz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8145c944393e3737f4700e6d92c1bef5851f3fb/pkg/sql/conn_executor_savepoints_test.go#L50)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

`origConn` is a conn pool (a `sql.DB`).
Here's the `Conn`.
https://pkg.go.dev/database/sql#DB.Conn
</blockquote></details>

Oh I see, you're completely right. Thanks for calling this out. Done.

**Review by andreimatei — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73388#-:-Mpwf5o78pZ4YwDdphn6:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @rytaft)

**Comment by nvanbenschoten** [comment]
TFTRs!

bors r+

**Pull request merged**
