### PR TITLE
storage: advance pebble minimum suported format version

### PR DESCRIPTION
**Pull request by RaduBerinde**
Also add a test that it matches the one for `MinSupported`.

Epic: none
Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115370)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens)

___
*[`pkg/storage/pebble.go` line 2361 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115370#-NkXDzvV4uKRMz6WSPou:-NkXDzvV4uKRMz6WSPov:b-9y7y4i) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab038710de9c27e5a8b091995775572a6c96787a/pkg/storage/pebble.go#L2361)):*
> ```Go
> 	clusterversion.V23_1:                                    pebble.FormatFlushableIngest,
> 	clusterversion.V23_2_PebbleFormatVirtualSSTables:        pebble.FormatVirtualSSTables,
> 	clusterversion.V23_2_PebbleFormatDeleteSizedAndObsolete: pebble.FormatDeleteSizedAndObsolete,
> ```

Do we plan to switch 24.1 to `FormatVirtualSSTables`?

**Review by itsbilal — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115370#-:-NkzuELB5-quvI11oNHp:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens, @RaduBerinde, and @sumeerbhola)

___
*[`pkg/storage/pebble.go` line 2361 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115370#-NkXDzvV4uKRMz6WSPou:-Nkztmi-0T_qxkSHKqys:b-fkax0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab038710de9c27e5a8b091995775572a6c96787a/pkg/storage/pebble.go#L2361)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Do we plan to switch 24.1 to `FormatVirtualSSTables`?
</blockquote></details>

As in that'll be the min expected version for all 24.1 crdb cluster versions? Yeah that makes sense to me.

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115370#-:-Nl-6-RP55lSSvva9MLO:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[`pkg/storage/pebble.go` line 2361 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115370#-NkXDzvV4uKRMz6WSPou:-Nl-4T0y1YPXf6GXD-SE:bj6oy4n) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab038710de9c27e5a8b091995775572a6c96787a/pkg/storage/pebble.go#L2361)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

As in that'll be the min expected version for all 24.1 crdb cluster versions? Yeah that makes sense to me.
</blockquote></details>

I didn't read the list correctly, it looked like the default format for a new store on master was FormatDeleteSizedAndObsolete but the list isn't sorted as I expected - V23_2_PebbleFormatVirtualSSTables is the latest one so that would continue to apply to 24.1. I fixed the ordering.

**Pull request merged**
