### PR TITLE
sql: add contended tables, indexes, and keys views

### LINKED ISSUE #61507: sql: Add contended tables, indexes, and keys views
We now have rich contention information on contention, but we require developers to find it and address it themselves. Instead, we could make predetermined views that would ease observability. 

Contended tables:
```SQL
CREATE VIEW crdb_internal.contended_tables (database_name, schema_name, name, num_contention_events)
AS SELECT DISTINCT database_name, schema_name, name, num_contention_events
FROM crdb_internal.cluster_contention_events
JOIN crdb_internal.tables
ON crdb_internal.cluster_contention_events.table_id = crdb_internal.tables.table_id
ORDER BY num_contention_events desc;
```
With sample TPC-C results:
```SQL
select * from contended_tables;
  database_name | schema_name |       name       | num_contention_events
----------------+-------------+------------------+------------------------
  tpcc          | public      | warehouse        |                   496
  system        | public      | jobs             |                   178
  tpcc          | public      | district         |                    71
  system        | public      | sqlliveness      |                    51
  NULL          | pg_catalog  | pg_extension     |                    33
  system        | public      | jobs             |                    33
  tpcc          | public      | stock            |                     9
  NULL          | pg_catalog  | pg_event_trigger |                     9
  NULL          | pg_catalog  | pg_event_trigger |                     6
  NULL          | pg_catalog  | pg_event_trigger |                     4
  NULL          | pg_catalog  | pg_event_trigger |                     3
  NULL          | pg_catalog  | pg_event_trigger |                     2
  NULL          | pg_catalog  | pg_event_trigger |                     1
```

We should also add views for contended indexes and contended keys.
```SQL
CREATE VIEW tpcc.contended_indexes (database_name, schema_name, name, index_name, num_contention_events)
AS SELECT DISTINCT database_name, schema_name, name, index_name, num_contention_events
FROM crdb_internal.cluster_contention_events, crdb_internal.tables, crdb_internal.table_indexes
WHERE crdb_internal.cluster_contention_events.index_id = crdb_internal.table_indexes.index_id
AND crdb_internal.cluster_contention_events.table_id = crdb_internal.tables.table_id
ORDER BY num_contention_events desc limit 5;
 SELECT * from contended_indexes;
  database_name | schema_name |    name     | index_name | num_contention_events
----------------+-------------+-------------+------------+------------------------
  tpcc          | public      | warehouse   | primary    |                   812
  system        | public      | jobs        | primary    |                   182
  tpcc          | public      | district    | primary    |                   142
  system        | public      | sqlliveness | primary    |                    55
  system        | public      | jobs        | order_idx  |                    34
(5 rows)
```

### PR DESCRIPTION
**Pull request by matthewtodd**
These support developers in interpreting the existing contention information in cluster_contention_events.

Resolves: #61507

See also: #57114, #61625

Release note (sql change): Three new views were added to the crdb_internal schema to support developers investigating contention events, cluster_contended_{tables, indexes, keys}.

```
> SELECT * FROM crdb_internal.cluster_contended_tables
  database_name | schema_name | table_name | num_contention_events
----------------+-------------+------------+------------------------
  ycsb          | public      | usertable  |                    76
(1 row)
```

```
> SELECT * FROM crdb_internal.cluster_contended_indexes
  database_name | schema_name | table_name | index_name | num_contention_events
----------------+-------------+------------+------------+------------------------
  ycsb          | public      | usertable  | primary    |                    76
(1 row)
```

```
> SELECT * FROM crdb_internal.cluster_contended_keys
  database_name | schema_name | table_name | index_name |                  key                  | num_contention_events
----------------+-------------+------------+------------+---------------------------------------+------------------------
  ycsb          | public      | usertable  | primary    | /53/1/"user12161962213042174405"/1/1  |                     3
  ycsb          | public      | usertable  | primary    | /53/1/"user12161962213042174405"/2/1  |                     2
  ycsb          | public      | usertable  | primary    | /53/1/"user12161962213042174405"/3/1  |                     4
  ycsb          | public      | usertable  | primary    | /53/1/"user12161962213042174405"/4/1  |                     8
  ycsb          | public      | usertable  | primary    | /53/1/"user12161962213042174405"/5/1  |                     7
  ycsb          | public      | usertable  | primary    | /53/1/"user12161962213042174405"/6/1  |                     7
  ycsb          | public      | usertable  | primary    | /53/1/"user12161962213042174405"/7/1  |                     7
  ycsb          | public      | usertable  | primary    | /53/1/"user12161962213042174405"/8/1  |                     7
  ycsb          | public      | usertable  | primary    | /53/1/"user12161962213042174405"/9/1  |                     2
  ycsb          | public      | usertable  | primary    | /53/1/"user12161962213042174405"/10/1 |                     1
  ycsb          | public      | usertable  | primary    | /53/1/"user14856124470027295614"/1/1  |                     1
  ycsb          | public      | usertable  | primary    | /53/1/"user14856124470027295614"/10/1 |                     1
  ycsb          | public      | usertable  | primary    | /53/1/"user16390143479181108970"/1/1  |                     2
  ycsb          | public      | usertable  | primary    | /53/1/"user16390143479181108970"/2/1  |                     1
  ycsb          | public      | usertable  | primary    | /53/1/"user16390143479181108970"/4/1  |                     1
  ycsb          | public      | usertable  | primary    | /53/1/"user16390143479181108970"/5/1  |                     1
  ycsb          | public      | usertable  | primary    | /53/1/"user16390143479181108970"/6/1  |                     4
  ycsb          | public      | usertable  | primary    | /53/1/"user16390143479181108970"/7/1  |                     3
  ycsb          | public      | usertable  | primary    | /53/1/"user16390143479181108970"/9/1  |                     2
  ycsb          | public      | usertable  | primary    | /53/1/"user2171580671610491919"/1/1   |                     2
  ycsb          | public      | usertable  | primary    | /53/1/"user2171580671610491919"/3/1   |                     1
  ycsb          | public      | usertable  | primary    | /53/1/"user2171580671610491919"/4/1   |                     2
  ycsb          | public      | usertable  | primary    | /53/1/"user2171580671610491919"/7/1   |                     1
  ycsb          | public      | usertable  | primary    | /53/1/"user2171580671610491919"/9/1   |                     1
  ycsb          | public      | usertable  | primary    | /53/1/"user4838870532157485734"/4/1   |                     1
  ycsb          | public      | usertable  | primary    | /53/1/"user4865742928595613128"/7/1   |                     1
  ycsb          | public      | usertable  | primary    | /53/1/"user6399761937749426484"/3/1   |                     1
  ycsb          | public      | usertable  | primary    | /53/1/"user6399761937749426484"/6/1   |                     1
  ycsb          | public      | usertable  | primary    | /53/1/"user6399761937749426484"/8/1   |                     1
(29 rows)
```

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
Excellent work!

I'm, at a high level, wondering about 2 things (both product level):

1. Internal table architecture-wise, do we prefer our join keys to be by-name (in which case any joins must be accomplished by including all 3 of the names in a join) or by-id (in which case joins can be accomplished by just the table id, which are cluster-wide unique?)
2. Do we need to redact the contention keys? The answer to this question might depend on the level of access that we provide to this table. It seems like a data leak waiting to happen unless we also test the querying user's `SELECT` capability on the tables.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66370#-:-Mc9gplcDChzxoZVKYz1:b23de8x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @matthewtodd)

___
*[pkg/sql/crdb_internal.go, line 1753 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66370#-Mc9gzcO2pxW4M1BrCMs:-Mc9gzcO2pxW4M1BrCMt:b1pev3l) ([raw file](https://github.com/cockroachdb/cockroach/blob/691b2101cc7e1773f5b7448086c5bad8272f8fdd/pkg/sql/crdb_internal.go#L1753)):*
> ```Go
>     database_name, schema_name, name, sum(num_contention_events)
>   FROM
>     [
> ```

Interesting use of the cockroachdb-specific [] syntax! I'm curious, how did you come across this? In general we prefer the SQL-standard () subquery syntax, which is going to be better supported optimization-wise,  unless you found a reason not to use it here?

**Review by maryliag — COMMENTED** [review]
2. I agree we should have redaction depending on the user's level of access to the table. Also, should we have some explanation or more details about what the value means? I don't think the user will necessarily knows what each value of the key means and even if you look for documentation I could only find https://www.cockroachlabs.com/docs/stable/functions-and-operators.html that simply states "This function is used only by CockroachDB’s developers for testing purposes."

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66370#-:-Mc9o4uhB86d-mtB5sR1:b-hgzhkn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @matthewtodd)

**Review by matthewtodd — COMMENTED** [review]
Thank you both for the review!

For 1., I could use a little more context. I've asked in our #sql-observability-team to see more of what you mean, @jordanlewis.

For 2., AFAICT this change doesn't expose anything that isn't already available in `crdb_internal.cluster_contention_events`, which is already [gated on a VIEWACTIVITY permission][1]. And I assume a view doesn't work if the user can't select from its underlying tables, yes?

Alternatively, I've gone looking for column-specific permissions but not yet found anything. If those exist, could you point me in the right direction?

Prettifying keys was per @kevin-v-ngo's request, acknowledging that it's [not yet an ideal answer][2]. LMK if you think we should just revert to binary keys here for now, and I can do that easily.

[1]: https://github.com/matthewtodd/cockroach/blob/38dbeae2cfe36c66ce3662d0898d4e959667a8e4/pkg/server/status.go#L2199-L2202
[2]: https://github.com/cockroachdb/cockroach/issues/61625

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66370#-:-McAProO2aXQdaM8KRi1:bhzz614)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/crdb_internal.go, line 1753 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66370#-Mc9gzcO2pxW4M1BrCMs:-McAODY5-QK8j25qjjvt:baz4so0) ([raw file](https://github.com/cockroachdb/cockroach/blob/691b2101cc7e1773f5b7448086c5bad8272f8fdd/pkg/sql/crdb_internal.go#L1753)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Interesting use of the cockroachdb-specific [] syntax! I'm curious, how did you come across this? In general we prefer the SQL-standard () subquery syntax, which is going to be better supported optimization-wise,  unless you found a reason not to use it here? 
</blockquote></details>

Oops! Not sure where I saw this, will fix. Good catch!

**Review by matthewtodd — COMMENTED** [review]
I think we're all set to merge this now! I've fixed my unintentional usage of cockroach-specific syntax, @kevin-v-ngo is following up on the key redaction issue, and @jordanlewis mentioned in our 1:1 this morning that his comments about the shape of these tables/views were more intended to raise our team's overall awareness (leading to [Kevin's draft doc](https://docs.google.com/document/d/1QCj0cw_mMvz6nFuuKwCUa8IMxr8G9zuX_PofRcsO2zE/edit), awesome, Kevin!) than to block landing these changes as they are. Could I get an LGTM?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66370#-:-McKaqQB3V0H_EQFlGai:b-u3mxjq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/crdb_internal.go, line 1753 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66370#-Mc9gzcO2pxW4M1BrCMs:-McKae3t48Ke6I_5fbq7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/691b2101cc7e1773f5b7448086c5bad8272f8fdd/pkg/sql/crdb_internal.go#L1753)):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Oops! Not sure where I saw this, will fix. Good catch!
</blockquote></details>

Done.

**Review by maryliag — APPROVED** [review]
Great work on this!
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66370#-:-McL6v8YEvj12FO9If_0:bmnv6lf)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Pull request merged**
