### PR TITLE
sql: read minimal set of columns for backfilling index

### PR DESCRIPTION
**Pull request by vivekmenezes**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14271)

### CODE REVIEW

**Comment by jordanlewis** [comment]
The logic :lgtm: mod comments. While you're amending this commit, I'd suggest adding a brief note in the commit message body explaining what was here before, e.g. "Previously, we did XYZ. Now we did ABC."

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/indexbackfiller.go, line 100 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14271#-KfgD2_AU6ALA9KdTwuZ:-KfgD2_B4eOHxsh6ggf9:bryks0a) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e3ca81af62ebd80aa2be895c49aff4aa8476b64/pkg/sql/distsqlrun/indexbackfiller.go#L100)):*
> ```Go
> 			}
> 			for _, id := range idx.ColumnIDs {
> 				valNeeded(id)
> ```

I don't think the auxiliary function adds too much here - I think it'd be clearer if you just inlined the map set statement.

---

*[pkg/sql/distsqlrun/indexbackfiller.go, line 148 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14271#-KfgDZUnNGjlaVPJdv6a:-KfgDZUnNGjlaVPJdv6b:b-drgvt5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0edcd258e1734fcca300905f74b783100029ab3/pkg/sql/distsqlrun/indexbackfiller.go#L148)):*
> ```Go
> 			// It would not only avoid allocations, but also decode-encode cycles in some
> 			// cases (e.g. anything that is part of the PK). Similar to how the joinreader
> 			// uses MakeKeyFromEncDatums.
> ```

Is this TODO no longer needed? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14271#-:-KfgDj4K4QBM9oHbADcJ:b-45kc9q)*

**Comment by vivekmenezes** [comment]
I've added another test for UNIQUE indexes with STORING columns

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/distsqlrun/indexbackfiller.go, line 100 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14271#-KfgD2_AU6ALA9KdTwuZ:-KfgHwW4nQ4VKL_IjeX4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e3ca81af62ebd80aa2be895c49aff4aa8476b64/pkg/sql/distsqlrun/indexbackfiller.go#L100)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I don't think the auxiliary function adds too much here - I think it'd be clearer if you just inlined the map set statement.
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/indexbackfiller.go, line 148 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14271#-KfgDZUnNGjlaVPJdv6a:-KfgHxFJ81aLZo6LPCYl:bjbx9s9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a0edcd258e1734fcca300905f74b783100029ab3/pkg/sql/distsqlrun/indexbackfiller.go#L148)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Is this TODO no longer needed? 
</blockquote></details>

Yeah, the TODO asks us to pass in encoded columns so that they can be lazily decoded later when creating the indexes. This changes reads only the minimal set of columns so it is okay to decode all of them here, and we don't need to defer decoding them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14271#-:-KfgcIz-8HkMmyVw_YgZ:b-8nw9yi)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/distsqlrun/indexbackfiller.go, line 100 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14271#-KfgD2_AU6ALA9KdTwuZ:-KfgciYMNOFWPDWkIsXW:bj9b3bp) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e3ca81af62ebd80aa2be895c49aff4aa8476b64/pkg/sql/distsqlrun/indexbackfiller.go#L100)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I've made this safer by switching it to use ContainsColumnID()

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14271)*

**Comment by jordanlewis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/distsqlrun/indexbackfiller.go, line 100 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14271#-KfgD2_AU6ALA9KdTwuZ:-KfglmWtAzWkCvPnERi6:b8qizwx) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e3ca81af62ebd80aa2be895c49aff4aa8476b64/pkg/sql/distsqlrun/indexbackfiller.go#L100)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

I've made this safer by switching it to use ContainsColumnID()
</blockquote></details>

Hmm I'm not sure I understand what's going on here. When would valNeededForCol[i] ever be true during this first pass? doesn't valNeededForCol start out uninitialized and therefore all false?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14271)*

**Comment by tamird** [comment]
Reviewed 1 of 2 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/distsqlrun/indexbackfiller.go, line 100 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14271#-KfgD2_AU6ALA9KdTwuZ:-KfgmmE529e7tiyVQZ6s:b-q1mglh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e3ca81af62ebd80aa2be895c49aff4aa8476b64/pkg/sql/distsqlrun/indexbackfiller.go#L100)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Hmm I'm not sure I understand what's going on here. When would valNeededForCol[i] ever be true during this first pass? doesn't valNeededForCol start out uninitialized and therefore all false?
</blockquote></details>

This iteration happens more than once, though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14271)*

**Comment by jordanlewis** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/distsqlrun/indexbackfiller.go, line 100 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14271#-KfgD2_AU6ALA9KdTwuZ:-KfgmwYe8ccJa8H2Qx9H:bnx7ivy) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e3ca81af62ebd80aa2be895c49aff4aa8476b64/pkg/sql/distsqlrun/indexbackfiller.go#L100)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

This iteration happens more than once, though.
</blockquote></details>

Yeah somehow my eyes passed over the outer loop. whoops.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14271#-:-Kfgn9f_ucZFGzfgZbAy:bnfp4nl)*

**Pull request merged**
