### PR TITLE
gossip: use a better signal for multi-node vs single-node cluster

### PR DESCRIPTION
**Pull request by petermattis**
Use `bootstrapInfo.Addresses` rather than the `nodeDescs` map to
determine whether a cluster is multi-node or single-node. The former is
persistent while the latter is ephemeral.

Release note: None

### CODE REVIEW

**Review by bdarnell — APPROVED** [review]

**Review by a-robinson — APPROVED** [review]

**Comment by petermattis** [comment]
Sort of interesting that this breaks `TestGossipOrphanedStallDetection` because each of the gossip nodes only has the bootstrap address for the other node, not itself. This indicates that using `bootstrapInfo.Addresses` is actually a bit more fragile than `nodeDescs` because the latter will always contain our own node, but the former may or may not. Thoughts?

**Comment by bdarnell** [comment]
You also need to change the comparison to `> 0`. The bootstrap addresses may contain the local node if it is passed in `--join`, but shouldn't otherwise (and the presence of the `-join` flag indicates the intention to use a multi-node cluster)

**Comment by petermattis** [comment]
If I change the comparison to `> 0`, it fixes the test but then the log spam is back if a `--join` flag is specified. The original issue was about gossip log spam when `--join` was specified so we'd be back to where we started.

**Comment by a-robinson** [comment]
> The bootstrap addresses may contain the local node if it is passed in `--join`, but shouldn't otherwise (and the presence of the `-join` flag indicates the intention to use a multi-node cluster)

I don't believe `bootstrapInfo.Addresses` will ever contain the local node. It also won't contain a node in the join list that it hasn't been able to connect to yet. `bootstrapInfo.Addresses` only contains nodes that have been successfully connected to at some point in the past, and it can remove addresses that it later thinks have been removed from the cluster. This is a good thing, because it means that adding extra join flags to a single node cluster won't cause log spam (as in the original Helm example that found the issue in the first place).

So yeah, changing the comparison to `> 0` sounds correct.

**Comment by a-robinson** [comment]
> it fixes the test but then the log spam is back if a `--join` flag is specified

Is that true? I did a local test and addresses in the `--join` flag that haven't ever been successfully connected to don't show up in `g.bootstrapInfo.Addresses` here.

**Comment by bdarnell** [comment]
> The original issue was about gossip log spam when --join was specified so we'd be back to where we started.

Oh, I thought we were talking about the more typical single-node-without-join case. A single-node cluster with a join flag is an unusual configuration (although one that i have been pushing). I guess the condition we want is whether the join flag contains any nodes other than the local one.

> It also won't contain a node in the join list that it hasn't been able to connect to yet.

Hmm. That might be an issue. I suggested bootstrapInfo.Addresses because I thought it was the closest thing we had to a copy of the join flag at this level. I might be pointing to the wrong field.

**Comment by petermattis** [comment]
> Is that true? I did a local test and addresses in the --join flag that haven't ever been successfully connected to don't show up in g.bootstrapInfo.Addresses here.

Well I tested it so I thought it was true. But I just re-tested it and I see that it isn't true. Not sure what I did wrong before. I also added extra instrumentation and in the single-node case with a `--join` address I can see that the node's own address is never added to `bootstrapInfo.Addresses`. This is accomplished by `Gossip.updateAddress` specifically ignoring the node's own address. 

Updated this PR. I think it is good to go now.

**Review by a-robinson — APPROVED** [review]
> Hmm. That might be an issue. I suggested bootstrapInfo.Addresses because I thought it was the closest thing we had to a copy of the join flag at this level. I might be pointing to the wrong field.

It doesn't include the join flag's addresses before they've been connected to, but it does include addresses that were persisted to disk previous times the node ran, which is great. The only time it should really be empty is if the node has never been part of a multi-node cluster.

LGTM

**Comment by petermattis** [comment]
bors r=bdarnell,a-robinson

**Pull request merged**
