### PR TITLE
sql: propagate default int size to remote nodes

### PR DESCRIPTION
**Pull request by yuzefovich**
A while ago we added support of `DEFAULT_INT_SIZE` which can be set
either to 8 (default) or 4 bytes. So far that setting has been used to
influence how we parse the "naked" INT in the query from the client.
However, there is one other place where we're performing the parsing:
during expression deserialization on the remote nodes. Previously, the
setting hasn't been propagated to remote nodes, so we might have
interpreted it incorrectly. This commit addresses that.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Together with @jordanlewis we found this when looked into some test failures while I was working on #49891. However, now I believe that this propagation is actually unnecessary - my current understanding is that we see "naked" `INT` type only when it's coming from the client, and we parse it into either `INT8` or `INT4`. From that point on forward we don't have `INT`s anywhere, including the serialized representation. Is my understanding correct? If so, I think this PR attempts to fix a problem that doesn't exist and I'll close it.

**Comment by knz** [comment]
I think that it's useful for consistency, so that there's no discrepancy between local and remote execution.

Also we have a pg builtin function that retrieves session variables, we may want to keep the option to eventually run them on any node not just the gateway?
-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by yuzefovich** [comment]
> I think that it's useful for consistency, so that there's no discrepancy between local and remote execution.

Hm, did you mean that we should propagate an update to `default_int_size` setting throughout the whole cluster (which I don't think we currently do)? Or that DistSQL execution should propagate it as part of the eval context proto (which is what this PR does)?

**Comment by knz** [comment]
I mean what this PR does. I was surprised it doesn't already actually; I thought the entire SessionData struct was propagated as-is. 

Maybe it could be an idea to make SessionData a protobuf and have the same struct used directly by the executor and serialized with the distsql plans. This way it'd always be up to date.

**Comment by yuzefovich** [comment]
> Maybe it could be an idea to make SessionData a protobuf and have the same struct used directly by the executor and serialized with the distsql plans. This way it'd always be up to date.

It's an interesting idea. I think there might be a possible downside to it: it seems that many packages import `sessiondata` package which currently has just a couple of dependencies, but if we make `SessionData` struct a protobuf, then we might be bringing in more dependencies in other packages, possibly making build times slower in some scenarios. Does this sound plausible? I'm not very familiar with build process in general, so maybe I'm making stuff up.

Anyway, I'll bring this idea up during our weekly meeting tomorrow.

**Comment by asubiotto** [comment]
@yuzefovich to create an issue

**Comment by knz** [comment]
I think this is still relevant, especially in light of the recent realization that we get internal executors spawned on distsql proecssors. Casts executed remotely need to know about the int size!!

**Comment by yuzefovich** [comment]
#55569 does more than this PR, so closing.

**Pull request closed without merging**
