### PR TITLE
flowinfra: refactor locking around FlowRegistry

### LINKED ISSUE #72964: sql/flowinfra: don't send ConsumerSignal during FlowRegistry registration while holding lock
The largest source of mutex contention in TPC-E is in a location I haven't seen before. During a test, we see over **25%** of time spent blocking on mutexes process-wide in `FlowRegistry.ConnectInboundStream`, which is responsible for registering an incoming stream with the flow registry:

Screen Shot 2021-11-18 at 10 18 17 PM

Looking at the code, it's not hard to see why. [`FlowRegistry.ConnectInboundStream`](https://github.com/cockroachdb/cockroach/blob/28bb1ea049da5bfb6e15a7003cd7b678cbc4b67f/pkg/sql/flowinfra/flow_registry.go#L480) grabs a registry-wide (i.e. process-wide) exclusive lock and proceeds to register the flow with the registry. So far, this seems reasonable.

However, it then constructs and sends [at least one](https://github.com/cockroachdb/cockroach/blob/28bb1ea049da5bfb6e15a7003cd7b678cbc4b67f/pkg/sql/flowinfra/flow_registry.go#L534) (and [sometimes two](https://github.com/cockroachdb/cockroach/blob/28bb1ea049da5bfb6e15a7003cd7b678cbc4b67f/pkg/sql/flowinfra/flow_registry.go#L489)) `*ConsumerSignal` messages on a gRPC stream. So under a process-wide exclusive lock, we're interacting with gRPC. Granted this is a gRPC stream so it is usually non-blocking, but it's still expensive.

We should try to restructure this code to pull any interactions with gRPC outside of the locking. Ideally, the locking would surround just the portion of the code that requires mutual exclusion and nothing else. I believe this is just the interactions with the `FlowRegistry.flows` map and the corresponding `flowEntry`.

cc. @yuzefovich do you have ideas about how we can improve the structure of this function?

### PR DESCRIPTION
**Pull request by yuzefovich**
**flowinfra: refactor locking around FlowRegistry**

This commit refactors the locking done in `FlowRegistry`. Previously,
the `FlowRegistry`'s mutex (global process-wide) was protecting three
pieces of information:
- `flows` map that stores which flows have already been scheduled on the
node
- `flowEntry` objects (information about each scheduled flow)
- `InboundStreamInfo` objects (information about endpoints to serve
`FlowStream` RPCs).

This commit refactors the `InboundStreamInfo` objects so that each has
its own mutex. This cleans up the things a bit and allows us more
cleanly refactor the code in `ConnectInboundStream` so that we don't
perform any gRPC calls (which might be blocking, rarely) while holding
the `FlowRegistry`'s mutex.

Fixes: #72964.

Release note: None

**flowinfra: remove the reference to waitGroup from InboundStreamInfo**

This limits the coupling of `InboundStreamInfo` and `FlowBase`.

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
Thanks for looking into this!

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72998#-:-Mp9_fPz4FaVHJDe7Ke5:b-1q0apj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/flowinfra/flow_registry.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72998#-Mp9VDxaEY8bdAxzgm8S:-Mp9VDxaEY8bdAxzgm8T:b466qnd) ([raw file](https://github.com/cockroachdb/cockroach/blob/33fab06086d26a26dd87ea7c5f752c55323fb786/pkg/sql/flowinfra/flow_registry.go#L77)):*
> ```Go
> 	receiver InboundStreamHandler
> 	// waitGroup to signal on when finished.
> 	waitGroup *sync.WaitGroup
> ```

Drive-by comment on old code: it's a little strange to see an object hold on to a reference to a `WaitGroup`. At a minimum, that's coupling the `InboundStreamInfo` implementation with the orchestration layer above it. It also allows the `InboundStreamInfo` to call `Add` or `Wait` on the `waitGroup`, which would be an issue.

Consider replacing the concrete type with an `interface { Done() }`.
___
*[pkg/sql/flowinfra/flow_registry.go, line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72998#-Mp9XPfk1c8UAXoDMt7I:-Mp9XPfk1c8UAXoDMt7J:b-qyir29) ([raw file](https://github.com/cockroachdb/cockroach/blob/33fab06086d26a26dd87ea7c5f752c55323fb786/pkg/sql/flowinfra/flow_registry.go#L108)):*
> ```Go
> 	// inboundStreams are streams that receive data from other hosts, through
> 	// the FlowStream API. Each InboundStreamInfo has its own mutex, separate
> 	// from the FlowRegistry mutex. This map is set in Flow.Setup(), so it is
> ```

Could we talk about lock ordering here? Do the mutexes ever need to be held at the same time? If not, let's say that. If yes, then let's talk about which order they should the acquired in.
___
*[pkg/sql/flowinfra/flow_registry.go, line 515 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72998#-Mp9ZH2eDvwB2zTYZuI-:-Mp9ZH2eDvwB2zTYZuI0:btl5qhx) ([raw file](https://github.com/cockroachdb/cockroach/blob/33fab06086d26a26dd87ea7c5f752c55323fb786/pkg/sql/flowinfra/flow_registry.go#L515)):*
> ```Go
> 			return nil, nil, nil, err
> 		}
> 		fr.Lock()
> ```

Should we push this locking into `waitForFlow`? And I guess the same question applies to up above — should we push `FlowRegistry` locking into a `getEntry` method?
___
*[pkg/sql/flowinfra/flow_registry.go, line 534 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72998#-Mp9_-Ym-HxrS1KHNY9t:-Mp9_-Ym-HxrS1KHNY9u:bg882rk) ([raw file](https://github.com/cockroachdb/cockroach/blob/33fab06086d26a26dd87ea7c5f752c55323fb786/pkg/sql/flowinfra/flow_registry.go#L534)):*
> ```Go
> 		return nil, nil, nil, errors.Errorf("flow %s: no inbound stream %d", flowID, streamID)
> 	}
> 	s.mu.Lock()
> ```

Consider pulling some of these checked critical sections into methods on the `InboundStreamInfo`. For instance, this looks like a `func (*InboundStreamInfo) connect() error` method.
___
*[pkg/sql/flowinfra/flow_registry.go, line 548 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72998#-Mp9_Ti50Jqq62r32upD:-Mp9_Ti50Jqq62r32upE:bkn4ntj) ([raw file](https://github.com/cockroachdb/cockroach/blob/33fab06086d26a26dd87ea7c5f752c55323fb786/pkg/sql/flowinfra/flow_registry.go#L548)):*
> ```Go
> 	s.mu.connected = true
> 	s.mu.Unlock()
> 	defer func() {
> ```

nit: this may be cleaner to just put in the single `err` path down below.
___
*[pkg/sql/flowinfra/flow_registry.go, line 575 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72998#-Mp9Y8il9aQamm932Ga7:-Mp9Y8il9aQamm932Ga8:bxlhfcy) ([raw file](https://github.com/cockroachdb/cockroach/blob/33fab06086d26a26dd87ea7c5f752c55323fb786/pkg/sql/flowinfra/flow_registry.go#L575)):*
> ```Go
> 
> // The mutex of the streamEntry must be held when calling this method.
> func (fr *FlowRegistry) finishInboundStreamLocked(streamEntry *InboundStreamInfo) {
> ```

We're now mixing some "locked" methods on `FlowRegistry` that refer to the `FlowRegistry`'s mutex and some that refer to the `InboundStreamInfo`'s mutex. Consider changing the name here to make that more clear.

But also, does this even need to be a method on `FlowRegistry`? Can't it just be a `finishLocked` method on `InboundStreamInfo`? And then maybe add a `finish` method alongside it that acquires the lock. Then the `cleanup` closure becomes `cleanup := s.finish`.

**Review by yuzefovich — COMMENTED** [review]
Thanks for the review!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72998#-:-Mp9xWUSCF9Fj-mInkFh:b-9qdoz3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @nvanbenschoten, and @RaduBerinde)

___
*[pkg/sql/flowinfra/flow_registry.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72998#-Mp9VDxaEY8bdAxzgm8S:-Mp9vYYd5LMtnV1JK37u:b-vfzss4) ([raw file](https://github.com/cockroachdb/cockroach/blob/33fab06086d26a26dd87ea7c5f752c55323fb786/pkg/sql/flowinfra/flow_registry.go#L77)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Drive-by comment on old code: it's a little strange to see an object hold on to a reference to a `WaitGroup`. At a minimum, that's coupling the `InboundStreamInfo` implementation with the orchestration layer above it. It also allows the `InboundStreamInfo` to call `Add` or `Wait` on the `waitGroup`, which would be an issue.

Consider replacing the concrete type with an `interface { Done() }`.
</blockquote></details>

Hm, I think the comments are pretty tightly coupled with the idea of using the wait group here. I do see your point though, so I implemented your suggestion and updated the comments. Let me know what you think.
___
*[pkg/sql/flowinfra/flow_registry.go, line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72998#-Mp9XPfk1c8UAXoDMt7I:-Mp9tOKk-GoBhPqLEjMT:b-9uw06v) ([raw file](https://github.com/cockroachdb/cockroach/blob/33fab06086d26a26dd87ea7c5f752c55323fb786/pkg/sql/flowinfra/flow_registry.go#L108)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Could we talk about lock ordering here? Do the mutexes ever need to be held at the same time? If not, let's say that. If yes, then let's talk about which order they should the acquired in.
</blockquote></details>

Good point, updated the comment.
___
*[pkg/sql/flowinfra/flow_registry.go, line 515 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72998#-Mp9ZH2eDvwB2zTYZuI-:-Mp9nwQ0DfIsn94_3_fC:blhq5xt) ([raw file](https://github.com/cockroachdb/cockroach/blob/33fab06086d26a26dd87ea7c5f752c55323fb786/pkg/sql/flowinfra/flow_registry.go#L515)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we push this locking into `waitForFlow`? And I guess the same question applies to up above — should we push `FlowRegistry` locking into a `getEntry` method?
</blockquote></details>

I have gone back and forth on pushing locking into `waitForFlow`, and I think with my original version it was getting more complicated. Now it seems to be much cleaner, so done.

However, I think we should keep `getEntryLocked` unchanged because the `FlowRegistry`'s mutex protects `flowEntry` objects (e.g. `flow` field), and in several callsites of `getEntryLocked` we are holding the lock for other reasons anyway.
___
*[pkg/sql/flowinfra/flow_registry.go, line 575 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72998#-Mp9Y8il9aQamm932Ga7:-Mp9tR59AyuwvgCgAdN_:b-t57ec5) ([raw file](https://github.com/cockroachdb/cockroach/blob/33fab06086d26a26dd87ea7c5f752c55323fb786/pkg/sql/flowinfra/flow_registry.go#L575)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We're now mixing some "locked" methods on `FlowRegistry` that refer to the `FlowRegistry`'s mutex and some that refer to the `InboundStreamInfo`'s mutex. Consider changing the name here to make that more clear.

But also, does this even need to be a method on `FlowRegistry`? Can't it just be a `finishLocked` method on `InboundStreamInfo`? And then maybe add a `finish` method alongside it that acquires the lock. Then the `cleanup` closure becomes `cleanup := s.finish`.
</blockquote></details>

Your second paragraph is spot on - it definitely makes sense to make this method on `InboundStreamInfo`, and things become much cleaner. I didn't change the naming since now with different receivers in place it should be clear which mutex should be help.

**Review by nvb — APPROVED** [review]
:lgtm_strong:, though this should probably also get a look from someone more familiar with this code.

> Reviewed 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72998#-:-MpoYHQX3Bq32zhtUTse:b-rhk2zy)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @RaduBerinde)

___
*[pkg/sql/flowinfra/flow_registry.go, line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72998#-Mp9XPfk1c8UAXoDMt7I:-MpoXka26eN-gpU2cYhS:byojdjx) ([raw file](https://github.com/cockroachdb/cockroach/blob/33fab06086d26a26dd87ea7c5f752c55323fb786/pkg/sql/flowinfra/flow_registry.go#L108)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Good point, updated the comment.
</blockquote></details>

Aren't the two locks held at the same time in `cancelPendingStreamsLocked`?

**Review by rytaft — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72998)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/flowinfra/flow_registry.go, line 355 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72998#-MpqK1UcDe2flo-0DgLL:-MpqK1UcDe2flo-0DgLM:b-ash8t4) ([raw file](https://github.com/cockroachdb/cockroach/blob/442b3405792abce5abc59a2fe6c2436a2b1b95bf/pkg/sql/flowinfra/flow_registry.go#L355)):*
> ```Go
> 			is.cancelLocked()
> 		}
> 		is.mu.Unlock()
> ```

should we use `defer` for this and move it up, in case `cancelLocked` panics?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72998)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @nvanbenschoten, @RaduBerinde, and @rytaft)

___
*[pkg/sql/flowinfra/flow_registry.go, line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72998#-Mp9XPfk1c8UAXoDMt7I:-MprTLSmDINMgJBv2BKJ:b-j7g22x) ([raw file](https://github.com/cockroachdb/cockroach/blob/33fab06086d26a26dd87ea7c5f752c55323fb786/pkg/sql/flowinfra/flow_registry.go#L108)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Aren't the two locks held at the same time in `cancelPendingStreamsLocked`?
</blockquote></details>

Indeed, nice catch! I refactored the code there to not hold the FlowRegistry's lock. This actually simplified the code a bit, PTAL.
___
*[pkg/sql/flowinfra/flow_registry.go, line 355 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/72998#-MpqK1UcDe2flo-0DgLL:-MprTKoL7D5DK6hITHg3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/442b3405792abce5abc59a2fe6c2436a2b1b95bf/pkg/sql/flowinfra/flow_registry.go#L355)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

should we use `defer` for this and move it up, in case `cancelLocked` panics?
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
:lgtm: (although I'm also not familiar with this code)

> Reviewed 3 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72998#-:-MprhyIi0SXbwtrHKUUc:b-fwlfo3)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @jordanlewis and @RaduBerinde)

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72998#-:-Mps52mu9bvbPdCbN-a_:bnfp4nl)* status: :shipit: complete! 3 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/sql/flowinfra/flow_registry.go, line 161 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72998#-Mps5rzl6ySRF2j1eDTn:-Mps5rzl6ySRF2j1eDTo:b7cxbuv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1bc7cf7aab07f26dbeb4a4cb573d24a3b2975c3/pkg/sql/flowinfra/flow_registry.go#L161)):*
> ```Go
> 	// inboundStreams are streams that receive data from other hosts, through
> 	// the FlowStream API. This map is set in Flow.Setup(), so it is safe to
> 	// lookup into concurrently later.
> ```

I think we need a similar comment in `FlowBase.inboundStreams` and maybe`AddRemoteStream`.
___
*[pkg/sql/flowinfra/flow_registry.go, line 346 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72998#-Mps3Huo3ZRDVTtf5JuD:-Mps3Huo3ZRDVTtf5JuE:b4a5e9x) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1bc7cf7aab07f26dbeb4a4cb573d24a3b2975c3/pkg/sql/flowinfra/flow_registry.go#L346)):*
> ```Go
> 	fr.Unlock()
> 	if inboundStreams == nil {
> 		return numTimedOutReceivers
> ```

`return 0`
___
*[pkg/sql/flowinfra/flow_registry.go, line 354 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72998#-Mps4Uhk2A6pDmsytnDs:-Mps4Uhk2A6pDmsytnDt:b-ffplvq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1bc7cf7aab07f26dbeb4a4cb573d24a3b2975c3/pkg/sql/flowinfra/flow_registry.go#L354)):*
> ```Go
> 		var pendingReceiver InboundStreamHandler
> 		is.mu.Lock()
> 		defer is.mu.Unlock()
> ```

Strange to lock all of them, then unlock all of them. I'd just do `us.mu.Unlock()` at the end of the block.

**Review by yuzefovich — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72998#-:-MpsAo0kEuGpfQxJkX8c:b-tlx7ko)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @jordanlewis, @RaduBerinde, and @rytaft)

___
*[pkg/sql/flowinfra/flow_registry.go, line 354 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72998#-Mps4Uhk2A6pDmsytnDs:-Mps8o4-2MDoRO7Dkr37:b-fdzpdl) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1bc7cf7aab07f26dbeb4a4cb573d24a3b2975c3/pkg/sql/flowinfra/flow_registry.go#L354)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Strange to lock all of them, then unlock all of them. I'd just do `us.mu.Unlock()` at the end of the block.
</blockquote></details>

`finishLocked` (called by `cancelLocked` below) might panic, so Becca suggested to defer the unlocking. I've refactored the code to add a function scope for this defer.

**Pull request merged**
