### PR TITLE
kvserver: add timeout for lease acquisitions 

### LINKED ISSUE #81788: kvserver: add timeout for lease acquisitions
Lease acquisitions should have a timeout. It should be set to twice the Raft election timeout (6 seconds total), since it may need to hold a Raft election and repropose the lease acquisition command, each of which may take up to one election timeout.

Without this timeout, it's possible for a lease acquisition to stall indefinitely (e.g. in the case of a stalled disk). This prevents a
NotLeaseHolderError from being returned to the client DistSender, which in turn prevents it from trying other replicas that could acquire the lease instead. This can cause a lease to remain invalid forever.

### PR DESCRIPTION
**Pull request by erikgrinaker**
**kvserver: deflake `TestLeasePreferencesDuringOutage`**

This patch deflakes `TestLeasePreferencesDuringOutage` by allowing nodes
to acquire a lease even when they are not the Raft leader.

Release note: None

**kvserver: add timeout for lease acquisitions**

This patch adds a timeout for lease acquisitions. It is set to
twice the Raft election timeout (6 seconds total), since it may need to
hold a Raft election and repropose the lease acquisition command, each
of which may take up to one election timeout.

Without this timeout, it's possible for a lease acquisition to stall
indefinitely (e.g. in the case of a stalled disk). This prevents a
`NotLeaseHolderError` from being returned to the client DistSender,
which in turn prevents it from trying other replicas that could acquire
the lease instead. This can cause a lease to remain invalid forever.

Touches #81100.

Release note (bug fix): Fixed a bug where an unresponsive node (e.g.
with a stalled disk) could prevent other nodes from acquiring its
leases, effectively stalling these ranges until the node was shut down
or recovered.

### CODE REVIEW

**Review by tbg — COMMENTED** [review]
Second commit LGTM, first commit I am concerned that we're making the API worse and not better by adding this, since we don't have a way to return a descriptive cancellation error.

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81136#-:-N1kpjt2-NdS92G6f6-r:bah6907)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

___
*[`pkg/kv/kvserver/replica_range_lease.go` line 362 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81136#-N1kpKK57F7c8fdwF5R0:-N1kpKK57F7c8fdwF5R1:b-z6clbe) ([raw file](https://github.com/cockroachdb/cockroach/blob/c78e37ef439356f06e4f3e674e61b026b2b36f59/pkg/kv/kvserver/replica_range_lease.go#L362)):*
> ```Go
> 			// regular heartbeat. We must eventually return a NotLeaseHolderError,
> 			// otherwise we could prevent anyone else from acquiring the lease.
> 			Timeout: nlRenewal,
> ```

Let's say a range is unavailable, but the circuit breaker hasn't tripped (there isn't a lease). A request comes in and requests the lease. We will do so with a 4.5s timeout. I was worried that we wouldn't ever trip the breaker. But I think I'm wrong - the caller (this code) will abandon the lease proposal, but the proposal will stick around. So we will still tickle the breaker.

(Just rationalizing this for myself.)
___
*[`pkg/util/stop/stopper.go` line 503 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81136#-N1kottCEKp-YGSfaU6T:-N1kottCEKp-YGSfaU6U:b-urbxb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fadf35c65554ee1541674f87a3f802a4ffe11a4/pkg/util/stop/stopper.go#L503)):*
> ```Go
> 		// infallible.
> 		if opt.Timeout > 0 {
> 			_ = contextutil.RunWithTimeout(ctx, opt.TaskName, opt.Timeout,
> ```

This seems to defeat the purpose of using `RunWithTimeout` in the first place. If you specify a timeout, you want to pass a fallible closure. The nesting option that you alluded to would be better since it will actually surface the error massaged by `RunWithTimeout`.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81136)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[`pkg/kv/kvserver/replica_range_lease.go` line 362 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/81136#-N1kpKK57F7c8fdwF5R0:-N1m8mW30aXNgmhDcbQX:b-k6wtav) ([raw file](https://github.com/cockroachdb/cockroach/blob/c78e37ef439356f06e4f3e674e61b026b2b36f59/pkg/kv/kvserver/replica_range_lease.go#L362)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Let's say a range is unavailable, but the circuit breaker hasn't tripped (there isn't a lease). A request comes in and requests the lease. We will do so with a 4.5s timeout. I was worried that we wouldn't ever trip the breaker. But I think I'm wrong - the caller (this code) will abandon the lease proposal, but the proposal will stick around. So we will still tickle the breaker.

(Just rationalizing this for myself.)
</blockquote></details>

Yeah, thanks for verifying. It seems unfortunate that all of these mechanisms (lease acquisitions, circuit breakers, etc) are driven by client requests.
___
*[`pkg/util/stop/stopper.go` line 503 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81136#-N1kottCEKp-YGSfaU6T:-N1m8zty-gTiSuH7OYwe:b-vpq96f) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fadf35c65554ee1541674f87a3f802a4ffe11a4/pkg/util/stop/stopper.go#L503)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This seems to defeat the purpose of using `RunWithTimeout` in the first place. If you specify a timeout, you want to pass a fallible closure. The nesting option that you alluded to would be better since it will actually surface the error massaged by `RunWithTimeout`.
</blockquote></details>

If we do the call manually we're still in the same situation: we're in an infallible goroutine and have to handle the error from `RunWithTimeout`. The same is true if the caller simply passes in a cancellable context to `RunAsyncTask`: the context error must be handled inside the infallible goroutine. These errors must either be logged or passed to a different goroutine regardless of this option.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81136)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[`pkg/util/stop/stopper.go` line 503 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81136#-N1kottCEKp-YGSfaU6T:-N1mBTJE9eWGzzqYDUr5:bh149ks) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fadf35c65554ee1541674f87a3f802a4ffe11a4/pkg/util/stop/stopper.go#L503)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

If we do the call manually we're still in the same situation: we're in an infallible goroutine and have to handle the error from `RunWithTimeout`. The same is true if the caller simply passes in a cancellable context to `RunAsyncTask`: the context error must be handled inside the infallible goroutine. These errors must either be logged or passed to a different goroutine regardless of this option.
</blockquote></details>

Oh wait, yeah I see what you're saying. I'll drop it.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81136)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[`pkg/util/stop/stopper.go` line 503 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81136#-N1kottCEKp-YGSfaU6T:-N1s_KGsCRsXoUHk54PF:bevftus) ([raw file](https://github.com/cockroachdb/cockroach/blob/7fadf35c65554ee1541674f87a3f802a4ffe11a4/pkg/util/stop/stopper.go#L503)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Oh wait, yeah I see what you're saying. I'll drop it.
</blockquote></details>

Done, PTAL.

**Review by erikgrinaker — COMMENTED** [review]
> Second commit LGTM, first commit I am concerned that we're making the API worse and not better by adding this, since we don't have a way to return a descriptive cancellation error.

I think Reviewable ate the other comment thread, since I can't find it anywhere in the UI anymore now that it's resolved. Anyway, the new error handling requires a decode/encode roundtrip for `roachpb.Error` -- I'm a bit worried that those can be lossy, but let's see what CI says.

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81136#-:-N1scTE00QuIdLYJ2_O4:b-x30ksp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

**Review by tbg — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81136)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

**Comment by erikgrinaker** [comment]
I'm seeing two CI failures here:

* `TestReplicaDrainLease` under race, which is likely #81511.
* `TestLeasePreferencesDuringOutage`, which seems inherently racy (see also #73980), but is tickled more frequently with this change.

Going to resolve these somehow before merging.

**Review by tbg — APPROVED** [review]
> Reviewed 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81136)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

**Comment by erikgrinaker** [comment]
TFTR!

bors r=tbg

**Pull request merged**
