### PR TITLE
sql/parser: support nullable arguments in builtin functions

### PR DESCRIPTION
**Pull request by justinj**
Was a mostly mechanical rebase of #13031. Healthy amounts of 🔬🐶 here.

Also simplified `checkReturn` a little to return the `typedExprs` instead of `s`.

### CODE REVIEW

**Comment by justinj** [comment]
Hold off on reviewing this for now, actually, I have some stuff to figure out.

**Comment by justinj** [comment]
OK, after sleeping on this a bit and discussing it with Jordan, I have a better understanding and I've updated it a bit, please take a look when you get a chance.

**Comment by jordanlewis** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/parser/overload.go, line 541 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17264#-Kq94vDNyI_PXyK4Ek_l:-Kq94vDNyI_PXyK4Ek_m:bueuwp6) ([raw file](https://github.com/cockroachdb/cockroach/blob/787ef9b0b7baadd80f0fd922c795ca04ae71e411/pkg/sql/parser/overload.go#L541)):*
> ```Go
> func checkReturn(
> 	ctx *SemaContext, s typeCheckOverloadState,
> ) ([]TypedExpr, []overloadImpl, bool, error) {
> ```

Hmm I'm surprised this works. Although this function doesn't mutate `s`, `defaultTypeCheck` does - and since we don't return the resultant `s`, I think the caller of this function will lose the modifications potentially made to it by `defaultTypeCheck` if you don't either return `s` or change everything to pass it as a pointer. It's suspicious that there's no tests that notice this behavior so maybe I'm wrong.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17264)*

**Comment by knz** [comment]
LGTM modulo resolution of the open question

---

Reviewed 8 of 8 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/parser/overload.go, line 541 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17264#-Kq94vDNyI_PXyK4Ek_l:-Kq97jQKCvly7ZuVTnzB:bnsf14l) ([raw file](https://github.com/cockroachdb/cockroach/blob/787ef9b0b7baadd80f0fd922c795ca04ae71e411/pkg/sql/parser/overload.go#L541)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Hmm I'm surprised this works. Although this function doesn't mutate `s`, `defaultTypeCheck` does - and since we don't return the resultant `s`, I think the caller of this function will lose the modifications potentially made to it by `defaultTypeCheck` if you don't either return `s` or change everything to pass it as a pointer. It's suspicious that there's no tests that notice this behavior so maybe I'm wrong.
</blockquote></details>

same question here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17264#-:-Kq97g_JwKPrED7_z6rI:bz61hjp)*

**Comment by justinj** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/parser/overload.go, line 541 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17264#-Kq94vDNyI_PXyK4Ek_l:-Kq9a0Vsq1lFzWj1HkU0:bbcm3bv) ([raw file](https://github.com/cockroachdb/cockroach/blob/787ef9b0b7baadd80f0fd922c795ca04ae71e411/pkg/sql/parser/overload.go#L541)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

same question here
</blockquote></details>

Any time `checkReturn` returns true (which it does in both paths where `s` is mutated) it's a signal to `typeCheckOverloadedExprs` to return immediately (which it does, and so `s` is discarded). So while this is correct, it's certainly a bit confusing. I'm not sure how to improve it without a larger scale refactoring, since `checkReturn` uses a lot of info from `s`. I could add a comment but I'm not sure that that would improve the clarity unless you're comparing this to the previous revision (but I might be blinded by having spent a couple days in this code).

One option might be to do the switch outside the calls to this function and then it can be clearer in which cases it's causing a return and in which cases it's not, but this would make the calling function a bit noisy. I don't want to revert this to pass `s` around, because I think that just obscures what's going on here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17264)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/parser/overload.go, line 541 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17264#-Kq94vDNyI_PXyK4Ek_l:-KqFFqvwjzUj4bSEipt4:b-czqcrx) ([raw file](https://github.com/cockroachdb/cockroach/blob/787ef9b0b7baadd80f0fd922c795ca04ae71e411/pkg/sql/parser/overload.go#L541)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Any time `checkReturn` returns true (which it does in both paths where `s` is mutated) it's a signal to `typeCheckOverloadedExprs` to return immediately (which it does, and so `s` is discarded). So while this is correct, it's certainly a bit confusing. I'm not sure how to improve it without a larger scale refactoring, since `checkReturn` uses a lot of info from `s`. I could add a comment but I'm not sure that that would improve the clarity unless you're comparing this to the previous revision (but I might be blinded by having spent a couple days in this code).

One option might be to do the switch outside the calls to this function and then it can be clearer in which cases it's causing a return and in which cases it's not, but this would make the calling function a bit noisy. I don't want to revert this to pass `s` around, because I think that just obscures what's going on here.
</blockquote></details>

Can you extend the comment of this function with your explanation, then we're probably good to go.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17264)*

**Comment by justinj** [comment]
Review status: 5 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/parser/overload.go, line 541 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17264#-Kq94vDNyI_PXyK4Ek_l:-KqJcxcvYD4uwSjJbRqo:b-s1k01c) ([raw file](https://github.com/cockroachdb/cockroach/blob/787ef9b0b7baadd80f0fd922c795ca04ae71e411/pkg/sql/parser/overload.go#L541)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Can you extend the comment of this function with your explanation, then we're probably good to go.
</blockquote></details>

Ok, done. I spent some time yesterday trying to figure out a more holistic change, but I think this will do for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17264)*

**Comment by jordanlewis** [comment]
:lgtm:

---

Reviewed 5 of 8 files at r1, 3 of 3 files at r5, 1 of 1 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17264#-:-KqNoC9pWnI7qOdPxtdP:bnfp4nl)*

**Comment by justinj** [comment]
Thanks for the reviews!

**Pull request merged**
