### PR TITLE
scplan: Fix deprules for dropping computed columns

### LINKED ISSUE #111608: schema: drop column cascade used by expression index DML injection failure
Setup
```
CREATE TABLE tbl (
	insert_phase_ordinal TEXT NOT NULL, 
	operation_phase_ordinal TEXT NOT NULL,
	operation TEXT NOT NULL,
	val INT,
	PRIMARY KEY (insert_phase_ordinal, operation_phase_ordinal, operation)
);
ALTER TABLE tbl ADD COLUMN i INT NOT NULL DEFAULT 1;
CREATE INDEX idx ON tbl ((i + 1));
```

Schema change
```
ALTER TABLE tbl DROP COLUMN i CASCADE;
```

Schema change DML injection failure
```
dml_injection_test.go:357: [phaseOrdinal=PostCommitPhase:1] error executing query="DELETE FROM tbl WHERE insert_phase_ordinal = $1 AND operation_phase_ordinal = $2 AND operation = $3" args=["StatementPhase:1" "PostCommitPhase:1" "delete"]: pq: column "crdb_internal_column_5_name_placeholder" does not exist
```

Same underlying bug as https://github.com/cockroachdb/cockroach/issues/111619

Jira issue: CRDB-31986

Epic CRDB-37763

### LINKED ISSUE #111619: schema: drop column with index using hash cascade DML injection failure
Setup
```
CREATE TABLE tbl (
	insert_phase_ordinal TEXT NOT NULL, 
	operation_phase_ordinal TEXT NOT NULL,
	operation TEXT NOT NULL,
	val INT,
	PRIMARY KEY (insert_phase_ordinal, operation_phase_ordinal, operation)
);
ALTER TABLE tbl ADD COLUMN i INT NOT NULL DEFAULT 1;
CREATE INDEX idx ON tbl (i) USING HASH;
```

Schema change
```
ALTER TABLE tbl DROP COLUMN i CASCADE;
```

Schema change DML injection failure
```
dml_injection_test.go:442: [phaseOrdinal=PostCommitPhase:1] error executing query="DELETE FROM tbl WHERE insert_phase_ordinal = $1 AND operation_phase_ordinal = $2 AND operation = $3" args=["StatementPhase:1" "PostCommitPhase:1" "delete"]: pq: column "crdb_internal_column_5_name_placeholder" does not exist
does not exist
```

Same underlying bug as https://github.com/cockroachdb/cockroach/issues/111608

Jira issue: CRDB-31989

Epic CRDB-37763

### PR DESCRIPTION
**Pull request by rimadeodhar**
This PR fixes the new schema changer deprules for
dropping virtual computed columns which are also
used for hash and expression indexes.
Currently, the optimizer allows for virtual, computed
columns to be evaluated even when under mutation.
However, this causes concurrent DML issues when the
schemachanger job is running as the column that the
virtual computed column depends on moves into WRITE_ONLY
stage prior to the computed column being dropped.
As a result, the optimizer is unable to access the column
for evaluating the compute expression.
This PR updates the dep rules to ensure the virtual,
computed column is dropped before the dependent column
moves to WRITE_ONLY ensuring that the compute expression
can be enforced correctly for concurrent DML during all
stages of the schema change.

Epic: none
Fixes: https://github.com/cockroachdb/cockroach/issues/111608
Fixes: https://github.com/cockroachdb/cockroach/issues/111619
Release note: None

------------------------------------------------------------------
**Note for reviewers:** This PR is stacked on top of https://github.com/cockroachdb/cockroach/pull/120792.

### CODE REVIEW

**Review by fqazi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120794)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rimadeodhar)

___
*[`pkg/sql/schemachanger/scplan/testdata/alter_table_drop_column` line 1353 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120794#-NtTigsD9rbZ5WsrR1Ju:-NtTigsD9rbZ5WsrR1Jv:bgscv4o) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e9ea4279a2f490ea0e0af1734ffacd87b016711/pkg/sql/schemachanger/scplan/testdata/alter_table_drop_column#L1353)):*
> ```
> StatementPhase stage 1 of 1 with 42 MutationType ops
>   transitions:
>     [[Column:{DescID: 107, ColumnID: 3}, ABSENT], PUBLIC] -> WRITE_ONLY
> ```

Just thinking about this if we have a transaction what makes v2 invisible in this scenario? I think we are waiting this post commit non-revertible phase in this scenario?

```
i.e
BEGIN
ALTER TABLE defaultdb.foo DROP COLUMN v2 CASCADE;
SELECT * FROM defaultdb.foo;
...
```

**Review by rimadeodhar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120794)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/schemachanger/scplan/testdata/alter_table_drop_column` line 1353 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120794#-NtTigsD9rbZ5WsrR1Ju:-NtXjwbR3L10Rx8ZOjoc:b-7m829o) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e9ea4279a2f490ea0e0af1734ffacd87b016711/pkg/sql/schemachanger/scplan/testdata/alter_table_drop_column#L1353)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Just thinking about this if we have a transaction what makes v2 invisible in this scenario? I think we are waiting this post commit non-revertible phase in this scenario?

```
i.e
BEGIN
ALTER TABLE defaultdb.foo DROP COLUMN v2 CASCADE;
SELECT * FROM defaultdb.foo;
...
```
</blockquote></details>

Yeah, good point. I think for transactions we would need to introduce an additional stage where the columns being dropped move to inaccessible in the statement phase. I'll file a tracking issue for it. We would still need the changes contained within this PR as without them we will continue to get errors once the column moves to WRITE_ONLY.

**Review by rimadeodhar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120794)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/schemachanger/scplan/testdata/alter_table_drop_column` line 1353 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120794#-NtTigsD9rbZ5WsrR1Ju:-NtY8ach7A6KHhF0B9wf:bskfh2w) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e9ea4279a2f490ea0e0af1734ffacd87b016711/pkg/sql/schemachanger/scplan/testdata/alter_table_drop_column#L1353)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

Yeah, good point. I think for transactions we would need to introduce an additional stage where the columns being dropped move to inaccessible in the statement phase. I'll file a tracking issue for it. We would still need the changes contained within this PR as without them we will continue to get errors once the column moves to WRITE_ONLY.
</blockquote></details>

Created https://github.com/cockroachdb/cockroach/issues/120863

**Comment by michae2** [comment]
Looks like you'll need to do `./dev testlogic base --config=5node --files=distsql_stats --ignore-cache --rewrite` and then you should get this change:

```
diff --git a/pkg/sql/logictest/testdata/logic_test/distsql_stats b/pkg/sql/logictest/testdata/logic_test/distsql_stats
index e218e65a693..76ce58b7c6c 100644
--- a/pkg/sql/logictest/testdata/logic_test/distsql_stats
+++ b/pkg/sql/logictest/testdata/logic_test/distsql_stats
@@ -2699,8 +2699,10 @@ SELECT statistics_name, column_names, row_count, histogram_id IS NOT NULL AS has
 FROM [SHOW STATISTICS FOR TABLE t118537]
 ORDER BY statistics_name, column_names::STRING
 ----
-statistics_name  column_names  row_count  has_histogram
-mutation         {a}           10         true
+statistics_name  column_names                 row_count  has_histogram
+mutation         {a,crdb_internal_a_shard_3}  10         false
+mutation         {a}                          10         true
+mutation         {crdb_internal_a_shard_3}    10         true

 statement ok
 SET CLUSTER SETTING jobs.debug.pausepoints = ''
```

(I was literally just trying to figure out why I get this diff on 23.1 but not 23.2 or master, so congratulations on the fix! 😆)

**Review by fqazi — CHANGES_REQUESTED** [review]
Great work, just a couple of comments to improve performance on the rule evaluation side

> Reviewed 19 of 23 files at r1, 18 of 19 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120794#-:-Ntqg8XY5FLoF_A_7vUg:bc9tjg7)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rimadeodhar)

___
*[`pkg/sql/schemachanger/scplan/internal/rules/helpers.go` line 307 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120794#-Ntqf2F_CIETFljGdH0u:-Ntqf2Fa12VI6ORVi_Xq:b2q1lqb) ([raw file](https://github.com/cockroachdb/cockroach/blob/28d9cb78a788b59bef0fa1a97a21042f124bc44e/pkg/sql/schemachanger/scplan/internal/rules/helpers.go#L307)):*
> ```Go
> 			return rel.Clauses{
> 				indexColumn.Type((*scpb.IndexColumn)(nil)),
> 				indexColumn.AttrEqVar(screl.DescID, rel.Blank),
> ```

This should be tableID?
___
*[`pkg/sql/schemachanger/scplan/internal/rules/current/dep_drop_column.go` line 151 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120794#-NtqfXOg0sgz7aTH7O6q:-NtqfXOg0sgz7aTH7O6r:bad0i9j) ([raw file](https://github.com/cockroachdb/cockroach/blob/28d9cb78a788b59bef0fa1a97a21042f124bc44e/pkg/sql/schemachanger/scplan/internal/rules/current/dep_drop_column.go#L151)):*
> ```Go
> 						}
> 						for _, refColumns := range colType.ComputeExpr.ReferencedColumnIDs {
> 							if refColumns == column.ColumnID {
> ```

We can use: ReferencedColumnIDsContains and do it before the filter

**Review by rimadeodhar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120794)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/schemachanger/scplan/internal/rules/helpers.go` line 307 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120794#-Ntqf2F_CIETFljGdH0u:-NwQf7xwA069zvnnXvei:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/28d9cb78a788b59bef0fa1a97a21042f124bc44e/pkg/sql/schemachanger/scplan/internal/rules/helpers.go#L307)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

This should be tableID?
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/scplan/internal/rules/current/dep_drop_column.go` line 151 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120794#-NtqfXOg0sgz7aTH7O6q:-NwQfAyhCJT-y3mIDn56:b-wi2s9q) ([raw file](https://github.com/cockroachdb/cockroach/blob/28d9cb78a788b59bef0fa1a97a21042f124bc44e/pkg/sql/schemachanger/scplan/internal/rules/current/dep_drop_column.go#L151)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

We can use: ReferencedColumnIDsContains and do it before the filter
</blockquote></details>

The referencedColumnIDs field is contained within the expression field in the ColumnType element, so I can't use this helper. Any other recommendations?

**Review by fqazi — APPROVED** [review]
All of this looks good. I do have one comment below, not sure if we want to add some other safety or something else as a follow on, since it seems like a potential pitfall if users aren't careful.

> Reviewed 34 of 85 files at r3, 79 of 79 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120794#-:-NwuKOFBBsdbP9lgPnJl:b-y9wzzi)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rimadeodhar)

___
*[`pkg/sql/schemachanger/scplan/internal/rules/current/dep_drop_column.go` line 151 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120794#-NtqfXOg0sgz7aTH7O6q:-NwuHveCDUEiLKH2x_9r:b-reemll) ([raw file](https://github.com/cockroachdb/cockroach/blob/28d9cb78a788b59bef0fa1a97a21042f124bc44e/pkg/sql/schemachanger/scplan/internal/rules/current/dep_drop_column.go#L151)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

The referencedColumnIDs field is contained within the expression field in the ColumnType element, so I can't use this helper. Any other recommendations?
</blockquote></details>

Ugh, no other options here then. Though its not too terrible since its limited to the columns on the table.
___
*[`pkg/sql/schemachanger/testdata/end_to_end/drop_column_with_null_constraint/drop_column_with_null_constraint.definition` line 9 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/120794#-NwuJb9J9nSZKLDCQSF5:-NwuJb9KELckUdK33nAO:b-1dp3un) ([raw file](https://github.com/cockroachdb/cockroach/blob/6be59a93e0ab892c339864ebfacde4053a2e3903/pkg/sql/schemachanger/testdata/end_to_end/drop_column_with_null_constraint/drop_column_with_null_constraint.definition#L9)):*
> ```
> # for j
> stage-exec phase=PostCommitPhase stage=:
> INSERT INTO t (i) VALUES($stageKey);
> ```

I think logically and correctness wise all of this makes sense, since we need to be able to rollback consistently. I think the only worry I have is someone accidentally doing a DROP COLUMN and not realizing that inserts will be blocked until the table is backfilled. 

Not sure if we want a safety net of some sort :thinking: . Not sure what your thoughts are on that scenario.

**Review by rimadeodhar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120794)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/schemachanger/testdata/end_to_end/drop_column_with_null_constraint/drop_column_with_null_constraint.definition` line 9 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/120794#-NwuJb9J9nSZKLDCQSF5:-NwuQVK03R-RbE6dxOPh:b-lcy339) ([raw file](https://github.com/cockroachdb/cockroach/blob/6be59a93e0ab892c339864ebfacde4053a2e3903/pkg/sql/schemachanger/testdata/end_to_end/drop_column_with_null_constraint/drop_column_with_null_constraint.definition#L9)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

I think logically and correctness wise all of this makes sense, since we need to be able to rollback consistently. I think the only worry I have is someone accidentally doing a DROP COLUMN and not realizing that inserts will be blocked until the table is backfilled. 

Not sure if we want a safety net of some sort :thinking: . Not sure what your thoughts are on that scenario.
</blockquote></details>

Do you mean a scenario where someone drops a column accidentally, cancels the job and then the table is inaccessible for inserts until backfill part of the rollback is completed?

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120794)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rimadeodhar)

___
*[`pkg/sql/schemachanger/testdata/end_to_end/drop_column_with_null_constraint/drop_column_with_null_constraint.definition` line 9 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/120794#-NwuJb9J9nSZKLDCQSF5:-NwuUT2-DTR7pdakPC_I:b-c11fmt) ([raw file](https://github.com/cockroachdb/cockroach/blob/6be59a93e0ab892c339864ebfacde4053a2e3903/pkg/sql/schemachanger/testdata/end_to_end/drop_column_with_null_constraint/drop_column_with_null_constraint.definition#L9)):*
<details><summary><i>Previously, rimadeodhar (Rima Deodhar) wrote…</i></summary><blockquote>

Do you mean a scenario where someone drops a column accidentally, cancels the job and then the table is inaccessible for inserts until backfill part of the rollback is completed?
</blockquote></details>

Wait, I misread the plan this is a non-issue. Plus the rollback won't have any backfill only validation, which should be quick so it should be a small blip

**Comment by rimadeodhar** [comment]
TFTR!

bors r+

**Comment by rimadeodhar** [comment]
blathers backport 24.1

**Pull request merged**
