### PR TITLE
pgcrypto: add helper functions for PKCS padding

### PR DESCRIPTION
**Pull request by andyyang890**
This patch adds helper functions for PKCS padding/unpadding, which is
needed for pgcrypto's raw encryption functions.

Informs #21001 

Release note: None

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104058)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890 and @ecwall)

___
*[`pkg/sql/sem/builtins/pgcrypto/padding.go` line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104058#-NWnPY8TCW90XSfsGXbc:-NWnPY8TCW90XSfsGXbd:b4pgyt2) ([raw file](https://github.com/cockroachdb/cockroach/blob/101520c38dc0789d63e02ed389fc014396dbee3a/pkg/sql/sem/builtins/pgcrypto/padding.go#L33)):*
> ```Go
> 
> // PKCSUnpad removes the padding added by PKCSPad.
> func PKCSUnpad(data []byte, blockSize int) ([]byte, error) {
> ```

i want to make sure i understand: why do we need the blockSize here? it wasn't mentioned in that RFC, and it seems like this other library doesn't need it https://github.com/zenazn/pkcs7pad/blob/master/pkcs7pad.go
___
*[`pkg/sql/sem/builtins/pgcrypto/padding.go` line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104058#-NWnR9yC0_RdW72wnxb6:-NWnR9yC0_RdW72wnxb7:box16jl) ([raw file](https://github.com/cockroachdb/cockroach/blob/101520c38dc0789d63e02ed389fc014396dbee3a/pkg/sql/sem/builtins/pgcrypto/padding.go#L45)):*
> ```Go
> 
> 	paddingLen := data[len(data)-1]
> 	if paddingLen == 0 || int(paddingLen) > blockSize {
> ```

i think we should also add a check to make sure `paddingLen <= len(data)`. otherwise i think the loop could hit an index-out-of-bounds error. and we should be able to add a test for that
___
*[`pkg/sql/sem/builtins/pgcrypto/padding_test.go` line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104058#-NWnRdpl6qRqo-Ght5pc:-NWnRdpl6qRqo-Ght5pd:b8e3r8) ([raw file](https://github.com/cockroachdb/cockroach/blob/101520c38dc0789d63e02ed389fc014396dbee3a/pkg/sql/sem/builtins/pgcrypto/padding_test.go#L122)):*
> ```Go
> 		},
> 		"non-empty data with partial-block padding": {
> 			data:      []byte{'a', 'b', 2, 2},
> ```

continuing my last comment: how about a test case like `[]byte{'a', 'b', 20, 20},`

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104058)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall and @rafiss)

___
*[`pkg/sql/sem/builtins/pgcrypto/padding.go` line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104058#-NWnPY8TCW90XSfsGXbc:-NWnTPTU5J12XuAnGJRh:b-8tq68r) ([raw file](https://github.com/cockroachdb/cockroach/blob/101520c38dc0789d63e02ed389fc014396dbee3a/pkg/sql/sem/builtins/pgcrypto/padding.go#L33)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i want to make sure i understand: why do we need the blockSize here? it wasn't mentioned in that RFC, and it seems like this other library doesn't need it https://github.com/zenazn/pkcs7pad/blob/master/pkcs7pad.go
</blockquote></details>

I guess it's not strictly necessary but I thought it might be nice to have an extra check to make sure that the data is a multiple of the block size. (Otherwise, it was either padded incorrectly or the function is being called with the wrong block size.)

It also solves the problem you mentioned below of checking `paddingLen <= len(data)`. If`len(data)%blockSize==0` and`paddingLen <= blockSize`, then we necessarily have that `paddingLen <= len(data)`.

In any case, I've removed it and will move this check into the function that calls `PKCSUnpad`.
___
*[`pkg/sql/sem/builtins/pgcrypto/padding.go` line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104058#-NWnR9yC0_RdW72wnxb6:-NWn_QXa75wIvhpGdhVw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/101520c38dc0789d63e02ed389fc014396dbee3a/pkg/sql/sem/builtins/pgcrypto/padding.go#L45)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think we should also add a check to make sure `paddingLen <= len(data)`. otherwise i think the loop could hit an index-out-of-bounds error. and we should be able to add a test for that
</blockquote></details>

Done.
___
*[`pkg/sql/sem/builtins/pgcrypto/padding_test.go` line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104058#-NWnRdpl6qRqo-Ght5pc:-NWn_Tkp09eWelkUER75:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/101520c38dc0789d63e02ed389fc014396dbee3a/pkg/sql/sem/builtins/pgcrypto/padding_test.go#L122)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

continuing my last comment: how about a test case like `[]byte{'a', 'b', 20, 20},`
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
lgtm!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104058#-:-NXB5Z0C3EKfUiFId5PL:b-7nbn20)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall)

**Comment by andyyang890** [comment]
TFTR!

bors r=rafiss

**Pull request merged**
