### PR TITLE
exec: add sorter

### PR DESCRIPTION
**Pull request by rjnn**
Add a templated sort operator.

Release note: None

### CODE REVIEW

**Review by changangela — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32394)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/execgen/cmd/execgen/colvec_gen.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32394#-LRO63bO5SqaVXyA5ll2:-LRO63bP2bXoVvNo15jl:blrtdeg) ([raw file](https://github.com/cockroachdb/cockroach/blob/f426193935d87a81ca7ccb85e3be8288d9f1a43b/pkg/sql/exec/execgen/cmd/execgen/colvec_gen.go#L111)):*
> ```Go
> }
> 
> func (m *memColumn) Len(colType types.T) int {
> ```

Any reason we are using this instead of`ColBatch.Length()` as the argument to `Append` and `AppendWithSel`?

**Review by changangela — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32394)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/sort_test.go, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32394#-LRO6zYr5AnARqwxow1R:-LRO6zYs4mtKC0r2_c5g:b3t8o8i) ([raw file](https://github.com/cockroachdb/cockroach/blob/f426193935d87a81ca7ccb85e3be8288d9f1a43b/pkg/sql/exec/sort_test.go#L24)):*
> ```Go
> )
> 
> func TestSort(t *testing.T) {
> ```

I'm curious what would happen if the output of the HashJoiner operator is used as input, since it would stream in variable sized batches.

**Comment by arjunravinarayan** [comment]
___
*[pkg/sql/exec/sort_test.go, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32394#-LRO6zYr5AnARqwxow1R:-LROA3wa4dOXiDPMsP5h:b6xama9) ([raw file](https://github.com/cockroachdb/cockroach/blob/f426193935d87a81ca7ccb85e3be8288d9f1a43b/pkg/sql/exec/sort_test.go#L24)):*
<details><summary><i>Previously, changangela (Angela Chang) wrote…</i></summary><blockquote>

I'm curious what would happen if the output of the HashJoiner operator is used as input, since it would stream in variable sized batches.
</blockquote></details>

This is a good thought. Do you have an idea as to an easy way to test this? Do you think we should augment the test harness to send variable sized batches?

**Review by changangela — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32394)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/sort_test.go, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32394#-LRO6zYr5AnARqwxow1R:-LROE2Ff8MgF6gwsRpzO:b-mckhhu) ([raw file](https://github.com/cockroachdb/cockroach/blob/f426193935d87a81ca7ccb85e3be8288d9f1a43b/pkg/sql/exec/sort_test.go#L24)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

This is a good thought. Do you have an idea as to an easy way to test this? Do you think we should augment the test harness to send variable sized batches?
</blockquote></details>

Hmm it would be a bit of a hassle to add it to the sort tests, but maybe we can add it to the hash join tests? Something like 
```
			sortSpec := sortSpec{
				sortCol:    0,
				direction:  ascending,
				inputTypes: outTypes,
			}

			sort := NewSortOp(hj, sortSpec)

			out := newOpTestOutput(sort, cols, tc.expectedTuples)`
```
This would only work on the test cases where the leftOutCols and rightOutCols include every single index of the tables.

**Review by asubiotto — CHANGES_REQUESTED** [review]
First pass review, hopefully what I'm saying makes sense but let me know if it doesn't.

> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32394#-:-LROEYlqDJG268151JV5:b-wya5qo)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/colvec.go, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32394#-LRO3i-c0hYeZbdZvJd9:-LRO3i-c0hYeZbdZvJdA:bjc8tpa) ([raw file](https://github.com/cockroachdb/cockroach/blob/f426193935d87a81ca7ccb85e3be8288d9f1a43b/pkg/sql/exec/colvec.go#L58)):*
> ```Go
> 
> 	// Len returns the length of this ColVec when it is treated as a colType.
> 	Len(colType types.T) int
> ```

I'm not sure I like the idea of adding Len to the interface. In general, if you need to call it multiple times, you might as well get the underlying slice and call `len` on that. If not, it would cost the same to do an `{{.ExecType}}` conversion and call `len()` on that, however hiding this behind an interface call might lead the caller to believe this call is cheap.
___
*[pkg/sql/exec/sort.go, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32394#-LROCCeIENahlju-nDHw:-LROCCeIENahlju-nDHx:b-5yo70o) ([raw file](https://github.com/cockroachdb/cockroach/blob/f426193935d87a81ca7ccb85e3be8288d9f1a43b/pkg/sql/exec/sort.go#L30)):*
> ```Go
> )
> 
> type sortSpec struct {
> ```

Please add a comment describing the algorithm
___
*[pkg/sql/exec/execgen/cmd/execgen/sort_gen.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32394#-LRO8ZcV8STEZw5-KAk1:-LRO8ZcW3Z40zKNzkTp3:be8buax) ([raw file](https://github.com/cockroachdb/cockroach/blob/f426193935d87a81ca7ccb85e3be8288d9f1a43b/pkg/sql/exec/execgen/cmd/execgen/sort_gen.go#L37)):*
> ```Go
> func (s *sorter) Less(i, j int) bool {
>   switch s.spec.inputTypes[s.spec.sortCol] {
>   {{range .}}
> ```

I think that doing a switch on each comparison will be a performance hit. What I think we would really want to do is to have `n` `sort_TYPE` implementations for each type that implements comparison.
___
*[pkg/sql/exec/execgen/cmd/execgen/sort_gen.go, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32394#-LRO99naA4VDknDp2VLM:-LRO99naA4VDknDp2VLN:br9ddop) ([raw file](https://github.com/cockroachdb/cockroach/blob/f426193935d87a81ca7ccb85e3be8288d9f1a43b/pkg/sql/exec/execgen/cmd/execgen/sort_gen.go#L40)):*
> ```Go
>     case types.{{.ExecType}}:
>       {{if eq .ExecType "Bool"}}
>         return (s.values[s.spec.sortCol].{{.ExecType}}()[i] == false) &&
> ```

Instead of having these comparisons spelled out, I think you could reuse similar logic to `_ASSIGN_NE` in distinct, just using `_ASSIGN_LT`. I was kind of frustrated by the fact that there was no need to assign, but sticking it into godbolt showed that the compiler elided that step. Hopefully that's true here too.
___
*[pkg/sql/exec/execgen/cmd/execgen/sort_gen.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32394#-LROAEPi5ykOD0iWUtTM:-LROAEPi5ykOD0iWUtTN:bx1ds8a) ([raw file](https://github.com/cockroachdb/cockroach/blob/f426193935d87a81ca7ccb85e3be8288d9f1a43b/pkg/sql/exec/execgen/cmd/execgen/sort_gen.go#L66)):*
> ```Go
>     case types.{{.ExecType}}:
> 	s.order[i], s.order[j] = s.order[j], s.order[i]
> 	s.values[s.spec.sortCol].{{.ExecType}}()[i],
> ```

If you template a sorter for each specific type, you can keep around a slice of that specific type and you will be able to use a simple slice swap with no templating here. (and avoid a call to {{.ExecType}})

**Review by changangela — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32394)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/colvec.go, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32394#-LRO3i-c0hYeZbdZvJd9:-LROJph42_ZKC4C-TCkl:b-bow0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/f426193935d87a81ca7ccb85e3be8288d9f1a43b/pkg/sql/exec/colvec.go#L58)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I'm not sure I like the idea of adding Len to the interface. In general, if you need to call it multiple times, you might as well get the underlying slice and call `len` on that. If not, it would cost the same to do an `{{.ExecType}}` conversion and call `len()` on that, however hiding this behind an interface call might lead the caller to believe this call is cheap.
</blockquote></details>

Another idea is to keep a variable that stores the updated size of `s.values` on the side.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32394)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec/colvec.go, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32394#-LRO3i-c0hYeZbdZvJd9:-LROu8Jq6yAYhwBsnF8H:byv0cgz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f426193935d87a81ca7ccb85e3be8288d9f1a43b/pkg/sql/exec/colvec.go#L58)):*
<details><summary><i>Previously, changangela (Angela Chang) wrote…</i></summary><blockquote>

Another idea is to keep a variable that stores the updated size of `s.values` on the side.
</blockquote></details>

+1 to Angela's point. This doesn't seem necessary.
___
*[pkg/sql/exec/sort.go, line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32394#-LROTgdDBNClmu_P_K-5:-LROTgdDBNClmu_P_K-6:b-umg7r3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b183bbb9941ecf314149b419e15bafc5363700/pkg/sql/exec/sort.go#L65)):*
> ```Go
> 	s.input.Init()
> 
> 	batch := s.input.Next()
> ```

Interesting idea to do this up-front work in Init. None of the other operators do that. I don't think there's anything preventing this from working right now, but I think having Init call Next is not a good pattern to follow. It's the same with DistSQL - the Start method doesn't actually begin execution with .Next on its parent.

Point taken from the meeting that this should be documented, though.
___
*[pkg/sql/exec/sort.go, line 94 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32394#-LROXgF98HlqgAdH0VHx:-LROXgF98HlqgAdH0VHy:bzh8h5t) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b183bbb9941ecf314149b419e15bafc5363700/pkg/sql/exec/sort.go#L94)):*
> ```Go
> 	}
> 
> 	s.order = make([]int, s.values[0].Len(s.spec.inputTypes[0]))
> ```

Isn't this Len() call going to give us the same number as `s.size`? If so, I think using `s.size` would be more clear.
___
*[pkg/sql/exec/sort.go, line 105 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32394#-LROYV0d-9G9DY0zgxXY:-LROYV0d-9G9DY0zgxXZ:btkf2la) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b183bbb9941ecf314149b419e15bafc5363700/pkg/sql/exec/sort.go#L105)):*
> ```Go
> 
> func (s *sorter) Next() ColBatch {
> 	limit := s.emitted + ColBatchSize
> ```

I'm confused about what's happening here. What does `limit` represent? I think it's the "end index" into the colbatch that you're going to ultimately emit, right? I'd suggest renaming this variable to something else, or at least adding a comment explaining what it means.
___
*[pkg/sql/exec/execgen/cmd/execgen/sort_gen.go, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32394#-LRO8ZcV8STEZw5-KAk1:-LROZ9845HF4vVIm7cvY:b-mjndnr) ([raw file](https://github.com/cockroachdb/cockroach/blob/f426193935d87a81ca7ccb85e3be8288d9f1a43b/pkg/sql/exec/execgen/cmd/execgen/sort_gen.go#L37)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think that doing a switch on each comparison will be a performance hit. What I think we would really want to do is to have `n` `sort_TYPE` implementations for each type that implements comparison.
</blockquote></details>

Agreed. Alfonso hit the nail on the head. It's definitely necessary to have more than one `sorter` implementation - you need one per type, just like the other operators. It might be a good idea to check out one of the generated .eg.go files to see what it looks like - that way you'll see the pattern to follow in a different light.
___
*[pkg/sql/exec/execgen/cmd/execgen/sort_gen.go, line 66 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32394#-LROAEPi5ykOD0iWUtTM:-LRP3PdaDq0SHRUhSkWJ:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/f426193935d87a81ca7ccb85e3be8288d9f1a43b/pkg/sql/exec/execgen/cmd/execgen/sort_gen.go#L66)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

If you template a sorter for each specific type, you can keep around a slice of that specific type and you will be able to use a simple slice swap with no templating here. (and avoid a call to {{.ExecType}})
</blockquote></details>

:thumbsup: 
___
*[pkg/sql/exec/execgen/cmd/execgen/sort_gen.go, line 24 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32394#-LRP3-IV3oCmscEUxhCz:-LRP3-IV3oCmscEUxhD-:bdivknl) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b183bbb9941ecf314149b419e15bafc5363700/pkg/sql/exec/execgen/cmd/execgen/sort_gen.go#L24)):*
> ```Go
> )
> 
> const sorterTemplate = `
> ```

You might want to consider moving this into a `sort_tmpl.go` file, to avoid having to keep everything in a big string like you were talking about. For example, see how the distinct and aggregate operators work - `sum_agg_tmpl.go` or `distinct_tmpl.go`.
___
*[pkg/sql/exec/execgen/cmd/execgen/sort_gen.go, line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32394#-LROsGVv2HX0DAJf_4I-:-LROsGVwE1OqL8LmQ3sj:bqgyyv6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b183bbb9941ecf314149b419e15bafc5363700/pkg/sql/exec/execgen/cmd/execgen/sort_gen.go#L81)):*
> ```Go
>   switch s.spec.inputTypes[s.spec.sortCol] {
>   {{range .}}
>   case types.{{.ExecType}}:
> ```

ditto here regarding removal of this switch/case.

**Comment by jordanlewis** [comment]
Not sure why the @CLAassistant piped up on this, but I'm going to close this PR.

**Pull request closed without merging**
