### PR TITLE
storage/engine: warn on long batch commits

### PR DESCRIPTION
**Pull request by petermattis**
See #9663.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9666)

### CODE REVIEW

**Comment by petermattis** [comment]
Cc @cockroachdb/stability

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/engine/rocksdb.go, line 1018 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9666#-KT66_JOwccstA5jbA7H:-KT66_JOwccstA5jbA7I:b-qodrxb) ([raw file](https://github.com/cockroachdb/cockroach/blob/56353277816c9928cea630afca36e59bd144895c/storage/engine/rocksdb.go#L1018)):*
> ```Go
> 	const batchCommitWarnThreshold = 500 * time.Millisecond
> 	if elapsed := timeutil.Since(start); elapsed >= batchCommitWarnThreshold {
> 		log.Warningf(context.TODO(), "batch [%d/%d/%d] commit took %s (>%s):\n%s",
> ```

@raduberinde There isn't a convenient context to use here. Should I be using `context.TODO` or `context.Background`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9666)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/engine/rocksdb.go, line 1018 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9666#-KT66_JOwccstA5jbA7H:-KT6HUCHdSm-k3fSawpk:blzbpfw) ([raw file](https://github.com/cockroachdb/cockroach/blob/56353277816c9928cea630afca36e59bd144895c/storage/engine/rocksdb.go#L1018)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> @raduberinde There isn't a convenient context to use here. Should I be using `context.TODO` or `context.Background`?
</details>
`TODO`. It's fixable, we should probably pass a context to `NewBatch` and store it in the `rocksDBBatch`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9666)*

**Comment by petermattis** [comment]
@tschottdorf ping

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[storage/engine/rocksdb.go, line 994 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9666#-KT9pYWbjJ2X-j9EjhLA:-KT9pYWbjJ2X-j9EjhLB:brbe4ce) ([raw file](https://github.com/cockroachdb/cockroach/blob/56353277816c9928cea630afca36e59bd144895c/storage/engine/rocksdb.go#L994)):*
> ```Go
> 
> 	start := timeutil.Now()
> 	var count int
> ```

[nit] count, size

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9666#-:-KT9pbQwcvB9X2_vGgRD:bnfp4nl)*

**Comment by tschottdorf** [comment]
LGTM. Mind waiting until #9672 merges (hopefully momentarily)?

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[storage/engine/rocksdb.go, line 994 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9666#-KT9pYWbjJ2X-j9EjhLA:-KT9yy3zNmX57Z0Mt9gK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/56353277816c9928cea630afca36e59bd144895c/storage/engine/rocksdb.go#L994)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> [nit] count, size
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9666)*

**Comment by tschottdorf** [comment]
PR is merged.

**Pull request merged**
