### PR TITLE
WIP: Replay protection through enforced commit index

### PR DESCRIPTION
**Pull request by tbg**
See #6287. The last commit is the meat; some refactoring was necessary before
that.

Augment `processRaftCommand` to check for the newly introduced `MustIndex`
field. On a mismatch, the command is "refurbished" (named to distinguish it
from a mere reproposal), i.e. an identical command proposed, at a new index.

The difference between refurbishing and reproposing is important: The goal
here is to do away with Raft-related replays. A reproposal is issued when
we're not sure that the proposal made it into Raft in the first place, i.e.
we want to guarantee that the client eventually receives a response, and we
err on the side of caution in doing so by reproposing fairly liberally, however
without updating the index to which the command is tied (so that it really
will commit only once).

A refurbished command must only be issued when we are certain that the original
command cannot commit at its chosen index any more - for instance because we
observe its application at a different  index, or because we observe the committed
or applied index having surpassed its chosen index. In this case, we propose
a new command which can commit at a new, higher, index, and route its response
to the waiting client.

A consequence of this replay protection mechanism is that proposing commands
on a non-leader is inherently racy: we will guess the next index based on
the Replica's last index, but that index lags behind the leader. Thus, without
further mechanisms, we might find ourselves reproposing such a command over
and over, but never getting to the leader in time.

The open parts in this change are
- prevent getting stuck in a refurbishing loop due to the above race
- optimize reproposals which can be refurbishments
- an audit (and removal) of previous, MVCC-based, replay protection mechanisms.
- see about adding the Term to MustIndex if it is necessary for anything.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6722)

### CODE REVIEW

**Comment by tamird** [comment]
there's some weird entanglement between commits here. the first one adds a (unused) field, the second moves code around but also adds a use of that field.

can you make the first commit _just_ code movement and put everything else in the second?

<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> #### WIP: Replay protection through enforced commit index
> 
> See #6287. The last commit is the meat; some refactoring was necessary before
> 
> that.
> 
> 
> 
> Augment `processRaftCommand` to check for the newly introduced `MustIndex`
> 
> field. On a mismatch, the command is "refurbished" (named to distinguish it
> 
> from a mere reproposal), i.e. an identical command proposed, at a new index.
> 
> 
> 
> The difference between refurbishing and reproposing is important: The goal
> 
> here is to do away with Raft-related replays. A reproposal is issued when
> 
> we're not sure that the proposal made it into Raft in the first place, i.e.
> 
> we want to guarantee that the client eventually receives a response, and we
> 
> err on the side of caution in doing so by reproposing fairly liberally, however
> 
> without updating the index to which the command is tied (so that it really
> 
> will commit only once).
> 
> 
> 
> A refurbished command must only be issued when we are certain that the original
> 
> command cannot commit at its chosen index any more - for instance because we
> 
> observe its application at a different  index, or because we observe the committed
> 
> or applied index having surpassed its chosen index. In this case, we propose
> 
> a new command which can commit at a new, higher, index, and route its response
> 
> to the waiting client.
> 
> 
> 
> A consequence of this replay protection mechanism is that proposing commands
> 
> on a non-leader is inherently racy: we will guess the next index based on
> 
> the Replica's last index, but that index lags behind the leader. Thus, without
> 
> further mechanisms, we might find ourselves reproposing such a command over
> 
> and over, but never getting to the leader in time.
> 
> 
> 
> The open parts in this change are
> 
> 
> 
> * prevent getting stuck in a refurbishing loop due to the above race
> 
> * optimize reproposals which can be refurbishments
> 
> * an audit (and removal) of previous, MVCC-based, replay protection mechanisms.
> 
> * see about adding the Term to MustIndex if it is necessary for anything.
> 
> 
> </details>


---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6722#-:-KHvHYoF_8oJprxwUzwn:593312010)*

**Comment by tschottdorf** [comment]
I removed reference to `MustIndex` from the refactoring commit (and moved its introduction to the one following it). The refactoring commit is pretty small. I don't think that splitting it up further is worth it/useful.

<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> there's some weird entanglement between commits here. the first one adds a (unused) field, the second moves code around but also adds a use of that field.
> 
> can you make the first commit _just_ code movement and put everything else in the second?</details>


---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6722#-:-KHvMTTA1sMthBDCAT-j:1037629347)*

**Comment by bdarnell** [comment]
I'm not too concerned about the race - only leader lease proposals should be coming from nodes that don't already have the lease, so there shouldn't be too much disruption. 

I don't believe adding the Term to MustIndex is necessary - we rely on the lease being held continuously between proposal and application, but we don't really care about raft leadership.

<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> I removed reference to `MustIndex` from the refactoring commit (and moved its introduction to the one following it). The refactoring commit is pretty small. I don't think that splitting it up further is worth it/useful.</details>


---

Reviewed 2 of 4 files at r8.
Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[roachpb/api.proto, line 795 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6722#-KHwr_OlaDPQ4MzZx_kF:-KHwr_OlaDPQ4MzZx_kG:-1043070075) ([raw file](https://github.com/cockroachdb/cockroach/blob/3df10b4debfff3f7ab50d69ff2aa64e752f28604/roachpb/api.proto#L795)):*
> ```protobuf
>   // When the command is applied, its result is an error unless the log position
>   // at which it applies is equal to must_index.
>   optional uint64 must_index = 4 [(gogoproto.nullable) = false];
> ```

"Must" should be followed by a verb. `required_index`? `expected_index`?  Or `required_raft_index` for a little more context.

---

*[storage/replica.go, line 1548 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6722#-KHwvRSgsuWPXKjv-2sz:-KHwvRSgsuWPXKjv-2t-:1559559705) ([raw file](https://github.com/cockroachdb/cockroach/blob/3df10b4debfff3f7ab50d69ff2aa64e752f28604/storage/replica.go#L1548)):*
> ```Go
> 	// TODO(tschottdorf): each of these pending commands has a log index at
> 	// which it must commit (or it will catch an error and be refurbished).
> 	// We shouldn't repropose commands here whose log index is already taken.
> ```

`pendingCmds` is a map, which means that if it has more than one element we're probably breaking the underlying order. We should change it from a map to a slice. Even then, I think in a large fraction of cases when reproposals are required, the order will have already been broken, so I think we may be better off going straight to refurbishment (which would also mean we don't need a separate name and don't need "refurbish"). 

---

*[storage/replica.go, line 1669 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6722#-KHwxEXrFleeuBEjZG81:-KHwxEXrFleeuBEjZG82:1929331201) ([raw file](https://github.com/cockroachdb/cockroach/blob/3df10b4debfff3f7ab50d69ff2aa64e752f28604/storage/replica.go#L1669)):*
> ```Go
> 			// leader is very busy, it's possible that we'll never get the
> 			// command in the right slot. We may have to make the reproposal
> 			// conditional, for example allowing only LeaderLeaseRequest when
> ```

Isn't this already the case? We shouldn't propose any command except LeaderLease unless we already hold the lease.

---

*[storage/replica.go, line 1752 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6722#-KHwsOTxnHRjP4IzkEWn:-KHwsOTxnHRjP4IzkEWo:605948960) ([raw file](https://github.com/cockroachdb/cockroach/blob/3df10b4debfff3f7ab50d69ff2aa64e752f28604/storage/replica.go#L1752)):*
> ```Go
> 		batch = r.store.Engine().NewBatch()
> 		br, rErr = nil, forcedError
> 	} else if mayApply {
> ```

Instead of setting `mayApply` to false, can we set `forcedError = roachpb.NewError(roachpb.NewRangeFrozenError)` instead so we only have one error code path here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6722#-:-KHwy8E2vBt_gFQxHUBb:1155929731)*

**Comment by tschottdorf** [comment]
I also don't think the race will be frequent, but I'm fairly sure that it will eventually happen (especially on clusters which aren't doing very well) and there's nothing that would terminate it, so there should be a safeguard there.

<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> I'm not too concerned about the race - only leader lease proposals should be coming from nodes that don't already have the lease, so there shouldn't be too much disruption. 
> 
> I don't believe adding the Term to MustIndex is necessary - we rely on the lease being held continuously between proposal and application, but we don't really care about raft leadership.</details>


---

Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[storage/replica.go, line 1548 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6722#-KHwvRSgsuWPXKjv-2sz:-KI-DDs_lWsP9wBP2Ejl:-1748330152) ([raw file](https://github.com/cockroachdb/cockroach/blob/3df10b4debfff3f7ab50d69ff2aa64e752f28604/storage/replica.go#L1548)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> `pendingCmds` is a map, which means that if it has more than one element we're probably breaking the underlying order. We should change it from a map to a slice. Even then, I think in a large fraction of cases when reproposals are required, the order will have already been broken, so I think we may be better off going straight to refurbishment (which would also mean we don't need a separate name and don't need "refurbish"). </details>
We can't refurbish a command unless we know it can't commit at its original log position. If you propose 10 commands rapidly and then the last five get lost, you need to repropose them as they were (and, as you mention, that should happen in order), or wait until enough other Raft commands have committed (not a great idea).
So I think we'll have to keep repropose around, though I also think that in practice we should be able to refurbish most of it directly.

---

*[storage/replica.go, line 1669 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6722#-KHwxEXrFleeuBEjZG81:-KI-Dqb34n3NXeeGD6mk:-1942217529) ([raw file](https://github.com/cockroachdb/cockroach/blob/3df10b4debfff3f7ab50d69ff2aa64e752f28604/storage/replica.go#L1669)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Isn't this already the case? We shouldn't propose any command except LeaderLease unless we already hold the lease.</details>
It's generally the case but there's no guarantee. We check the leader lease at some point before the proposal. If enough time passes until `proposeRaftCommand` for whatever reason, another node may hold the lease when we get here. And once that has happened to a command, with a busy leader I think its chances of not getting through for a long time are very high.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6722#-:-KI-EXRHXtdA5LZP6D18:-219660871)*

**Comment by tschottdorf** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[roachpb/api.proto, line 795 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6722#-KHwr_OlaDPQ4MzZx_kF:-KI8ixlsnooGnH7P3Frt:-800328726) ([raw file](https://github.com/cockroachdb/cockroach/blob/3df10b4debfff3f7ab50d69ff2aa64e752f28604/roachpb/api.proto#L795)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> "Must" should be followed by a verb. `required_index`? `expected_index`?  Or `required_raft_index` for a little more context.
</details>
Renamed to `RequiredIndex`. It's inside of `RaftCommand`, so I don't think the extra `_raft_` is going to be helpful.

---

*[storage/replica.go, line 1752 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6722#-KHwsOTxnHRjP4IzkEWn:-KI8nVVdeeNizrofhYoR:-262272805) ([raw file](https://github.com/cockroachdb/cockroach/blob/3df10b4debfff3f7ab50d69ff2aa64e752f28604/storage/replica.go#L1752)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Instead of setting `mayApply` to false, can we set `forcedError = roachpb.NewError(roachpb.NewRangeFrozenError)` instead so we only have one error code path here?
</details>
Good catch, done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6722)*

**Comment by tschottdorf** [comment]
This is a fairly subtle change, much hairier than I'd hoped for. The TL;DR is
that while it probably works reasonably well in the happy case, I have some
trouble imagining how quickly this would recover when it goes off the rails.

In the case in which the Raft leader isn't colocated with the lease holder, the
lease holder essentially has to guess the last index of the Raft leader
(presumably under the assumption that everything that's inflight makes it
there). Even worse, this premonition must allow for the occasional request to
be proposed directly at the Raft leader (or even another Replica):

Assume that everyone's log position is 10 (completely applied), and the lease
holder starts proposing commands. It needs to propose these commands at 11, ...
and the only information it has is its own last index. Firing off the first few
proposals, its last index will only increase when the appends from the Raft
leader come in, so we definitely need to keep a counter of in-flight proposals
(or rather, for simplicity, it keeps the last index it thinks it has proposed
at, i.e. the last RequiredIndex).
Now some appends come back; they increase the last index, but we'll keep using
our counter (as long as the last index trails it). So far, so good.

Now, for some reason, the Raft leader proposes a command of its own. That means
that all of the lease holder's outstanding commands which haven't made it there
yet will be offset, i.e. they will not commit in the right place. When the
first such command gets processed, we know we're going to have to do something
about our counter.

The only new information we get is the delta from our intended log position
diff := (ActualIndex - RequiredIndex), which for now we assume to be positive
(corresponding to the above case). To take this into account, we refurbish the
command at its assigned_index+diff (updating our internal counter accordingly).

What if a leadership change discards part of the log? We may find that a command we
had hoped would commit at, say, index 20 now committed at index 10. We can't
refurbish this command because reproposals could have picked it up, and one of
these reproposals may actually sit at the (correct) index 20. So all we can do
here is repropose stupidly until the index has advanced to 20, busy looping if
necessary.

The interplay between reproposals and refurbishments is pretty tricky in
general:

* If `index<RequiredIndex`, it must not refurbish itself. This is the case above -
  there could be reproposals of this command out there which hit the correct
  index, so refurbishing could lead to a replay. The only option is reproposing
  the command again. If many reproposals do that, there's a blow up (but at
  least it limits itself; can only roughly happen
  `RequiredIndex-firstAppliedIndex` times (mod overshooting).
* If `index > RequiredIndex`, it must not refurbish itself unconditionally.
  This is because we could have an (earlier) incarnation already processed,
  and this would a) either have had the correct log position, or b) will have
  refurbished itself already, so we can't do it again. Hence, there needs to be
  a mechanism for a command to find out whether an earlier incarnation of
  itself already dealt with the problem.
  That mechanism is the following: when observing the command at an incorrect
  index, we have two pieces of information: the pending command and the
  command popping out of Raft, and both of them have a RequiredIndex set.
  Assuming (and making sure that) a refurbishment always strictly increases
  RequiredIndex, we can check whether the pending command's RequiredIndex has
  increased from the Raft command's. If that is the case, an earlier
  refurbishment is already on the way and the command errors out (as if there
  were no pending command, but leaving it in the map).
* This leaves the case in which we want to refurbish (`index > RequiredIndex`),
  but the index we would require is less than or equal to our current,
  incorrect, one. In the absence of a better idea, we can just repropose - we
  think that that will put the command at a too-low index, but then that's what
  it's going to be (and maybe it can refurbish then). In the common case, we
  expect the next RequiredIndex to be larger than the current (since the index
  is already larger than the RequiredIndex of this command), so this situation
  should not occur outside of singular events such as a log truncation.

While that makes sure things are "correct", it doesn't at all guarantee making
progress. Especially the case in which we get "ahead" of the log is awkward
(`RequiredIndex > index`) because we essentially spam reproposals until we
catch up.

I'm in the middle of writing the code and tests for all the above, but I wanted to
give a summary of where it's headed - I don't want this to become a future source
of complications, and it's one of those things that will perform poorly mostly in
production situations in which a cluster as a whole performs poorly (so it's not
that easy to test completely).

**Comment by tschottdorf** [comment]
superseded by #6961.

**Pull request closed without merging**
