### PR TITLE
spanconfig: visualize differences with gossiped SystemConfigSpan

### PR DESCRIPTION
**Pull request by irfansharif**
**spanconfig: visualize differences with gossiped SystemConfigSpan**

We introduce a test-only package that compares the span configs
infrastructure against the gossiped SystemConfigSpan it was designed to
replace. The datadriven test spits out a visual "diff" of the two
subsystems, indicating exactly where they differ (or not!) in terms of
implied range boundaries and the configurations to apply. It does so by
having both systems run side-by-side and scanning their contents. These
range boundaries and configurations have second-order effects (various
actions are executed on behalf of ranges by internal queues), but we
don't bother with any of that in the test.

Of particular note is the behavior of each system in the presence of
secondary tenants that create arbitrary schemas and zone configs. This
after all is what motivated the new infrastructure. Here's an example,
as a diff, that shows how the system config span is unable to split
within an active tenant's boundary unlike the new thing:

```diff
configs version=current offset=37 limit=5
----
...
/Tenant/10                                 range default
/Tenant/11/Table/3                         range default
/Tenant/11/Table/4                         range default
/Tenant/11/Table/5                         range default
/Tenant/11/Table/6                         range default
...

configs version=legacy offset=43
----
...
/Tenant/10                                 range default
/Tenant/11                                 range default

diff offset=31 limit=8
----
--- gossiped system config span (legacy)
+++ span config infrastructure (current)
...
@@ -43,4 +37,37 @@
 /Table/47                                  range system
 /Tenant/10                                 range default
-/Tenant/11                                 range default
+/Tenant/11/Table/3                         range default
+/Tenant/11/Table/4                         range default
+/Tenant/11/Table/5                         range default
+/Tenant/11/Table/6                         range default
...
```
This commit also gets rid of the ShadowReader. We were using it
previously to manually diagnose differences between the two subsystems.
With the improved testing, we can get rid of the painter's tape.

---

**spanconfig: rm benign differences with SystemConfigSpan**

In the previous commit we demonstrated visually the differences between
the gossip-backed system config span and the new infrastructure. This
commit gets rid of the benign differences. We could also just not do
anything here, but it's only a minor change.

Release note: None

---

Only the last two commits are of interest here, the earlier ones are from #71994.

### CODE REVIEW

**Comment by irfansharif** [comment]
(Gentle bump here as well, it's a test only change + plus an entirely optional commit I'm happy to drop. It led to the realization in #73749 which we'll try and get to pre-22.1.)

**Review by ajwerner — COMMENTED** [review]
Can you rebase this now that  #71994 has merged? I think it :lgtm: but it'll be easy to take a last pass after the PR stands alone. 

> Reviewed 5 of 28 files at r1, 1 of 8 files at r2, 11 of 19 files at r5, 7 of 8 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73746#-:-MqzluOrAy9fxpgG6WRk:b-g9kcje)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, @irfansharif, and @nvanbenschoten)

___
*[pkg/ccl/spanconfigccl/spanconfigcomparedccl/datadriven_test.go, line 168 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73746#-MqzlRL5-w1GuKMz7KTD:-MqzlRL5-w1GuKMz7KTE:btwfkad) ([raw file](https://github.com/cockroachdb/cockroach/blob/6929ad7b15bb0b907db8ad2961b7054b32fadb69/pkg/ccl/spanconfigccl/spanconfigcomparedccl/datadriven_test.go#L168)):*
<details><summary><i alt="summary">Quoted 15 lines of code…</i></summary>

> ```
> 					// Now that all tenants have reconciled their SQL changes,
> 					// read the current time and wait for the kvsubscriber to
> 					// advance past it. This lets us observe the effects of all:
> 					// (i)  reconciliation processes;
> 					// (ii) tenant initializations (where seed span configs are
> 					//      installed).
> 					now := systemTenant.Clock().Now()
> 					testutils.SucceedsSoon(t, func() error {
> 						lastUpdated := kvSubscriber.LastUpdated()
> 						if lastUpdated.Less(now) {
> 							return errors.Newf("kvsubscriber last updated timestamp (%s) lagging barrier timestamp (%s)",
> 								lastUpdated.GoTime(), now.GoTime())
> 						}
> 						return nil
> 					})
> ```
</details>

does this `SuceedsSoon` need to be nested in the other one?

**Review by irfansharif — COMMENTED** [review]
Rebased.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73746#-:-MqzoF3B4awmimI7ay9g:bncvegj)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @arulajmani, and @nvanbenschoten)

___
*[pkg/ccl/spanconfigccl/spanconfigcomparedccl/datadriven_test.go, line 168 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/73746#-MqzlRL5-w1GuKMz7KTD:-MqzoRqK3IW7JcjvkXDM:bnzzq6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/6929ad7b15bb0b907db8ad2961b7054b32fadb69/pkg/ccl/spanconfigccl/spanconfigcomparedccl/datadriven_test.go#L168)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 					// Now that all tenants have reconciled their SQL changes,
> 					// read the current time and wait for the kvsubscriber to
> 					// advance past it. This lets us observe the effects of all:
> 					// (i)  reconciliation processes;
> 					// (ii) tenant initializations (where seed span configs are
> 					//      installed).
> 					now := systemTenant.Clock().Now()
> 					testutils.SucceedsSoon(t, func() error {
> 						lastUpdated := kvSubscriber.LastUpdated()
> 						if lastUpdated.Less(now) {
> 							return errors.Newf("kvsubscriber last updated timestamp (%s) lagging barrier timestamp (%s)",
> 								lastUpdated.GoTime(), now.GoTime())
> 						}
> 						return nil
> 					})
> ```
does this `SuceedsSoon` need to be nested in the other one?
</blockquote></details>

It doesn't, un-nested.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 5 of 19 files at r5, 5 of 59 files at r7, 8 of 54 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73746#-:-Mr0gmHtDIOOsF1DE6xT:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, and @nvanbenschoten)

**Review by ajwerner — APPROVED** [review]
> Reviewed 5 of 19 files at r5, 5 of 59 files at r7, 8 of 54 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73746)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, and @nvanbenschoten)

**Pull request merged**
