### PR TITLE
sql: turn on the optimizer for PREPARE statements

### LINKED ISSUE #26958: sql: use the same determination for optimizations during prepare as exec
Logical plans in CockroachDB are created on 3 different paths:

- the regular "simply query" execution path in `(connExecutor) dispatchToExecutionEngine()`
- PREPARE statements in SQL and pgwire prepare messages,  via `(connExecutor) prepare()`
- DO NOTHING mutations (parallel statements)

The optimizer cluster setting currently only works with the 1st code path. 

Arguably we are not supporting the 3rd because the optimizer doesn't deal with mutations yet.

However the 2nd is a problem since most applications use prepared queries: queries using correlation appear currently broken with the prepare protocol despite the setting "optimizer is enabled".

The solution is to factor the choice of planning engine across `(connExecutor) dispatchToExecutionEngine()` and `(connExecutor) prepare()`.

cc @justinj

### PR DESCRIPTION
**Pull request by BramGruneir**
The optimizer, when enabled, was not used for prepare statements. This patch
fixes that.

It should be noted that PREPARE has a limited subset of statements it can be
run with. Postgres only allows SELECT, INSERT, UPDATE, DELETE and VALUES
statements to be prepared.
See: https://www.postgresql.org/docs/current/static/sql-prepare.html

However, we allow a large number of additional statements.
As of right now, the optimizer only works on SELECT statements and will fallback
for all others, so this change should be safe for the foreseeable future.

Closes #26958.

Release note (sql change): When the cost based optimizer is enabled, it will
also affect prepared queries.

### CODE REVIEW

**Comment by justinj** [comment]
Is there a way we can do this without duplicating the optimizer mode logic? I haven't tried but I think we could have a function that returns a plan appropriately that gets called from both places?

**Comment by BramGruneir** [comment]
I'll try to DRI it up.

**Comment by BramGruneir** [comment]
Done, PTAL.

**Comment by benesch** [comment]
Bors got stuck. Trying again.

bors r+

**Pull request merged**
