### PR TITLE
server/status: read current process's cgroup to determine available memory

### PR DESCRIPTION
**Pull request by ajwerner**
Prior to this commit we would consult the system memory and the root cgroup
to determine the available memory. This is problematic because almost always
when systems use cgroups they use a hierarchy to create limits for specific
sets of processes. After this change we'll now determine the deepest child
hierarchy which contains this process and examine all of the relevant
limits to determine the memory limit.

Release note (bug fix): On linux machines we now respect the available memory
limit as dictated by the cgroup limits which apply to the cockroach process.

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
to save future headaches, is it possible to support reading both cgroup v1 file or v2 file?

in Kubernetes, we are starting to work toward cgroup v2 enablement so adding support for memory.max in addition to what is checked here would help prevent future revisions.

**Comment by ajwerner** [comment]
@bdarnell I didn't know about #32067 when I typed this. Do we prefer that patch? It adds a dependency on runc just to read the `/proc/<pid>/cgroup` file though that dependency makes for cleaner code. I think that patch still has a problem with regards to limits in a parent of the hierarchy being smaller than the limit in the child. 

Relates to #31750.

**Comment by ajwerner** [comment]
@bdarnell I didn't know about #32067 when I typed this. Do we prefer that patch? It adds a dependency on runc just to read the `/proc/<pid>/cgroup` file though that dependency makes for cleaner code. I think that patch still has a problem with regards to limits in a parent of the hierarchy being smaller than the limit in the child. 

Relates to #31750.

**Comment by ajwerner** [comment]
>  But given the "TODO: support v2" comments, it seems useful to take on a dependency and get (hopefully) more complete and future-proof support for it.

I buy that. I went fishing around for a better library than the one in `runc` and didn't come up with too much. https://github.com/containerd/cgroups seems like it could be okay though on first glance the API seems pretty heavy weight. The logic required to support `v2` is rather small. It's just detecting that there's a v2 hierarchy when parsing the `/proc/<pid>/cgroup` file which would be a row with a `0::$PATH` line and then reading the `memory.max` file instead of the `memory.limit_in_bytes` file. The bigger win from adopting the dependency is that it parses the mount points to find out where the cgroups are mounted (also a TODO). 

If I read your comment correctly, I should take a stab at adopting a dependency to achieve the goals and only if I have a bad time should we revisit this more manual approach.

**Comment by bdarnell** [comment]
Yeah, I'd try with the dependency first.

**Comment by ajwerner** [comment]
> Yeah, I'd try with the dependency first.

I ran in to trouble with the dependencies. I decided to just support v2. I wrote tests and tried it out in a variety of settings on VMs. It seems to work. 

@vladdy would you be willing to give this a review?

**Comment by ajwerner** [comment]
I suspect the code needs more of a gate on the OS, perhaps by consulting runtime.GOOS at runtime or by using compilation directives. Otherwise it is RFAL.

**Review by vladdy — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43137)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by ajwerner** [comment]
TFTR!

bors r=vladdy

**Pull request merged**
