### PR TITLE
ui: temporary fix so that redux devtools will work

### PR DESCRIPTION
**Pull request by maxlang**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8454)

### CODE REVIEW

**Comment by mrtracy** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[ui/app/containers/banner/outdatedBanner.tsx, line 109 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8454#-KOqP_gYTfb1ZU455zCq:-KOqP_gYTfb1ZU455zCr:b-jvlm1e) ([raw file](https://github.com/cockroachdb/cockroach/blob/1585cb99595142f515091edc4fd1ae2864d5c48c/ui/app/containers/banner/outdatedBanner.tsx#L109)):*
> ```XML
> let versions = createSelector(
>   nodeStatuses,
>   (statuses: NodeStatus[]): string[] => statuses && _.uniq(_.map(statuses, (s: NodeStatus) => s.build_info && s.build_info.tag))
> ```

Is this a necessary change?

---

*[ui/app/redux/state.ts, line 38 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8454#-KOqOt3_F6q4xdggHH9h:-KOqOt3auWyCn0OdnZ33:bpmz3va) ([raw file](https://github.com/cockroachdb/cockroach/blob/1585cb99595142f515091edc4fd1ae2864d5c48c/ui/app/redux/state.ts#L38)):*
> ```XML
>     // https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd
>     (window as any).devToolsExtension ? (window as any).devToolsExtension({
>       // The nodes state had a circular reference in it which was breaking redux devtools
> ```

Please add some more explanation to this comment; this is a really brutal thing. I understand that it only effects a development tool, but we need to call that out a bit more.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8454)*

**Comment by tamird** [comment]
Ditto regarding the commit message. Is it necessary to deviate from the
convention?

**Comment by maxlang** [comment]
What's the commit message convention?

**Comment by maxlang** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[ui/app/containers/banner/outdatedBanner.tsx, line 109 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8454#-KOqP_gYTfb1ZU455zCq:-KOq_mTUAyNl72aNOl3j:br5chl) ([raw file](https://github.com/cockroachdb/cockroach/blob/1585cb99595142f515091edc4fd1ae2864d5c48c/ui/app/containers/banner/outdatedBanner.tsx#L109)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> Is this a necessary change?
</details>
For some reason it was giving me infinite null pointer exceptions without this null-check. Not sure why it never came up before.

---

*[ui/app/redux/state.ts, line 38 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8454#-KOqOt3_F6q4xdggHH9h:-KOqdzVzLsTzUmAhWqLJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1585cb99595142f515091edc4fd1ae2864d5c48c/ui/app/redux/state.ts#L38)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> Please add some more explanation to this comment; this is a really brutal thing. I understand that it only effects a development tool, but we need to call that out a bit more.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8454)*

**Comment by mrtracy** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8454#-:-KOqk8In78-E1qZsMTxp:bnfp4nl)*

**Pull request merged**
