### PR TITLE
roachtest: use correct database in backup test

### PR DESCRIPTION
**Pull request by benesch**
Some day, someone will have to explain to me why workload uses a
different database name every time I look at it.

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23962#-:-L7k84BgL4PJte_Nf99Z:bnfp4nl)*

**Comment by benesch** [comment]
Stuffed another commit in here. PTAL.

**Comment by petermattis** [comment]
Still :lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23962#-:-L7k9FBx3vfpowb54-Kf:b-2pygyf)*

**Comment by benesch** [comment]
Store dumps download quietly in 12m now. I'm feeling good about this.

```
[   1] backup2TB: downloading store dumps (59s)
[   2] backup2TB: downloading store dumps (1m59s)
[   3] backup2TB: downloading store dumps (2m59s)
[   4] backup2TB: downloading store dumps (3m59s)
[   5] backup2TB: downloading store dumps (4m59s)
[   6] backup2TB: downloading store dumps (5m59s)
[   7] backup2TB: downloading store dumps (6m59s)
[   8] backup2TB: downloading store dumps (7m59s)
[   9] backup2TB: downloading store dumps (8m59s)
[  10] backup2TB: downloading store dumps (9m59s)
[  11] backup2TB: downloading store dumps (10m59s)
[  12] backup2TB: downloading store dumps (11m59s)
```

**Pull request merged**
