### PR TITLE
stats: don't issue query for the same stats in parallel

### LINKED ISSUE #36284: stats: excessive SELECTs against the system.table_statistics
On a cluster running TPCC, we are seeing a huge number of queries against the table_statistics cache:

image

Note that the latency of the query is huge (3s). I suspect that it's caused by the following: when we have a new statistic, we get a signal through gossip to invalidate that entry in the stats cache. At that point, every query that comes in will try to update the statistics by running the same SELECT query. This in turn makes this query really slow (it's hitting a single range very hard), which increases the window of time where we don't have a table statistic.

The fix is for just the first query to update the stats and have everyone else wait for that info to come in.

### PR DESCRIPTION
**Pull request by RaduBerinde**
In the time window between when a stat is invalidated and when the new
stat is populated, every query that needs this stat results in an
internal query for retrieving the same stats. This is a positive
feedback loop because the more queries we issue, the larger this
window gets.

The fix is to make everyone wait for the first internal query to come
back, and reuse those results. We achieve this by putting an entry in
the cache while we are retrieving stats; other callers find this entry
and wait on it.

Fixes #36284.

Release note (bug fix): Fixed excessive number of internal queries for
table statistics.

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: Thanks for the quick fix!

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36300#-:-Lb528U56aa2gFEhT91M:b-yq9ynn)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @justinj)

**Comment by RaduBerinde** [comment]
Updated with some changes suggested by Andy: replaced the channel with a condition and cleaned up the code a bit.

**Review by andy-kimball — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36300#-:-Lb94gky2LlOsZ_-exbP:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @justinj, and @rytaft)

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36300)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/stats/stats_cache.go, line 153 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36300#-Lb94jx27Yb1DwBZgx9G:-Lb94jx27Yb1DwBZgx9H:b42uikf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a79ac443a8ca3236639a2de1debc6e78adea4745/pkg/sql/stats/stats_cache.go#L153)):*
> ```Go
> // Assumes that the caller holds sc.mu. Note that the mutex can be unlocked and
> // locked again if we need to wait (this can only happen when found=true).
> func (sc *TableStatisticsCache) lookupStatsLocked(
> ```

NIT: Would be nice to group the exported methods at the top of the file to make it easier to see the API. Helper methods like this are less important and could be grouped further down.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36300)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @andy-kimball, @justinj, and @rytaft)

___
*[pkg/sql/stats/stats_cache.go, line 153 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36300#-Lb94jx27Yb1DwBZgx9G:-Lb95m6sBYY16cJfqOvT:b-4ck85f) ([raw file](https://github.com/cockroachdb/cockroach/blob/a79ac443a8ca3236639a2de1debc6e78adea4745/pkg/sql/stats/stats_cache.go#L153)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: Would be nice to group the exported methods at the top of the file to make it easier to see the API. Helper methods like this are less important and could be grouped further down.
</blockquote></details>

I'm not crazy about moving the functions far away from their single use. I guess it's a tradeoff between discovering the API and reading the code. Moved the new ones below the exported function.

**Comment by rytaft** [comment]
I was thinking about this some more, and I think there is a way we can improve it (not for 19.1, but perhaps for 19.1.1). It's a bit unfortunate that whenever the stats cache is invalidated for a heavily used table, potentially every query on that node must block and wait for the new stats to be fetched. Obviously this is much better than what we had before where all queries were trying to fetch the stats at once. But I think we can still improve this by allowing concurrent queries to use the old stats instead of blocking. It would work like this:
- Instead of deleting the cache entry when InvalidateTableStats is called, we can update it with a status "invalid"
- When the first thread encounters a cache entry with status "invalid", it updates the status to "fetch in progress" and issues a query to the DB to fetch the new stats.
- In the mean time, when other threads see the status "fetch in progress", they can continue planning and execution by using the old stats
- Once the stats query completes, the fetching thread updates the cache entry with the new statistics and changes the status back to "valid"

Thoughts?

**Comment by RaduBerinde** [comment]
@rytaft Yeah I've been thinking of something similar. I don't like a transaction having to wait for another transaction and the impact that has on latencies (especially p99). I was thinking that invalidation itself would start the process of refreshing the stats (otherwise, the first query(s) that need stats would get the old ones, even if the update happened a while back).

**Comment by RaduBerinde** [comment]
Filed #36365. Agree on targeting 19.1.1.

**Comment by rytaft** [comment]
Sounds great - thanks! Good idea to start the fetch during the invalidation.

**Pull request merged**
