### PR TITLE
sql: modify tests to have deterministic results

### PR DESCRIPTION
**Pull request by yuzefovich**
I missed a few in #27635. Hopefully, now all
tests are deterministic.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
I am not crazy about the `window_local` fork.  Logic tests should try to verify that results match the semantics we advertise, regardless of execution paths.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27700#-:-LHhmZIp74-eQ8xwcndP:b68gh5x)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
I do not have strong opinion about keeping `window_local`, so unless @nvanbenschoten objects, I'll remove that test suite.

**Comment by nvanbenschoten** [comment]
No objections from me.

**Comment by yuzefovich** [comment]
Thanks for quick replies!

**Pull request merged**
