### PR TITLE
opt: Convert exec code to use new opt expressions.

### PR DESCRIPTION
**Pull request by andy-kimball**
The exec.go file converts SQL AST nodes into the old opt expressions.
This PR converts that code to use the new opt expressions. As part
of this, I created a new `exec` package. That package will live in
the `opt` directory for now. But eventually, it will move to the
`sql` directory, and we will move other execution-related packages
into the `sql/exec` directory as well. Until then, it's better to
keep it here so that developers are not confused as to why we have a
top-level `exec` directory that doesn't actually contain the main
body of execution code.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
The commit includes the `optgen` binary. LGTM otherwise

---

Review status: 0 of 34 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/executor_opt_interface.go, line 75 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22423#-L4gUaisb8JWuLPl1kDY:-L4gUaitgRIxxrhXHEU2:brn2ly3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a590b37d656fb46834de67f1fe80bf1a06a734e/pkg/sql/executor_opt_interface.go#L75)):*
> ```Go
> 		return nil, err
> 	}
> 	return exec.Node(scan), nil
> ```

Just curious, is the `exec.Node(..)` there just so things are more explicit? Is it a typical practice to do this?

---

*[pkg/sql/opt/exec/engine.go, line 33 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22423#-L4gbWrCBqLU22AuvGbf:-L4gbWrDT3qVpugCZlV9:bjdblca) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a590b37d656fb46834de67f1fe80bf1a06a734e/pkg/sql/opt/exec/engine.go#L33)):*
> ```Go
> 	// nodes, or they take other nodes previously constructed by this same
> 	// factory as children.
> 	Factory() Factory
> ```

[nit] Should there be some guidance here as to whether a Factory can/should be reused across queries?

---

*[pkg/sql/opt/xform/testdata/typing, line 204 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22423#-L4gbl-gu36bpI60136t:-L4gbl-gu36bpI60136u:b-dkjqqz) ([raw file](https://github.com/cockroachdb/cockroach/blob/71e439618f95bef5f83242a914d023e3b605f367/pkg/sql/opt/xform/testdata/typing#L204)):*
> ```
>            └── const: NULL [type=NULL]
> 
> # Any, Some, All
> ```

Is this related to the rest of the change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22423#-:-L4gbEFbsQNQkSWxgKG7:b-pm1vmf)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 38 of 38 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/build/builder.go, line 52 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22423#-L4gVVDraU2fu_oaya8E:-L4gVVDraU2fu_oaya8F:bo1731r) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a590b37d656fb46834de67f1fe80bf1a06a734e/pkg/sql/opt/build/builder.go#L52)):*
> ```Go
> 	tree.IsDistinctFrom:    (opt.Factory).ConstructIsNot,
> 	tree.IsNotDistinctFrom: (opt.Factory).ConstructIs,
> 	tree.Contains:          nil,
> ```

Can you add a TODO here as well to explain why these are nil?

---

*[pkg/sql/opt/exec/build/main_test.go, line 35 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22423#-L4gcqWxwGlUw3wpi6dm:-L4gcqWy7xxBSzbQmNds:btr9ax5) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a590b37d656fb46834de67f1fe80bf1a06a734e/pkg/sql/opt/exec/build/main_test.go#L35)):*
> ```Go
> // create and run an execution plan. The implementation is in sql so this is an
> // opaque function that is initialized in TestMain.
> var NewExecEngine func(s serverutils.TestServerInterface) exec.Engine
> ```

Why did you delete this stuff? This is a useful way to prevent depending on sql. You probably just need to change the package name for this file to build_test

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22423#-:-L4gdBe5vK6bJrxM8z_5:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/exec/build/builder_test.go, line 39 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22423#-L4geeepAUXvdbUgcmEF:-L4geeepAUXvdbUgcmEG:b-sgdgmo) ([raw file](https://github.com/cockroachdb/cockroach/blob/80568d090594b4a9116491f28f2987a784d48014/pkg/sql/opt/exec/build/builder_test.go#L39)):*
> ```Go
> )
> 
> func TestLogicalProps(t *testing.T) {
> ```

copy paste-o?

---

*[pkg/sql/opt/exec/build/builder_test.go, line 76 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22423#-L4gehniGZZrvpA_oIYi:-L4gehniGZZrvpA_oIYj:btjnsw2) ([raw file](https://github.com/cockroachdb/cockroach/blob/80568d090594b4a9116491f28f2987a784d48014/pkg/sql/opt/exec/build/builder_test.go#L76)):*
> ```Go
> 
> 			// Build the execution node tree.
> 			eng := s.Executor().(*sql.Executor).NewExecEngine()
> ```

Are we positive that this won't lead to a circular dependency at some point? I feel uneasy about this package depending on sql.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22423)*

**Comment by andy-kimball** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/sql/executor_opt_interface.go, line 75 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22423#-L4gUaisb8JWuLPl1kDY:-L4gyYKUEppcPck05OcU:b-7ozhnq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a590b37d656fb46834de67f1fe80bf1a06a734e/pkg/sql/executor_opt_interface.go#L75)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Just curious, is the `exec.Node(..)` there just so things are more explicit? Is it a typical practice to do this?
</blockquote></details>

That was a vestige from an earlier design that I forgot to remove. I removed it now.

---

*[pkg/sql/opt/build/builder.go, line 52 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22423#-L4gVVDraU2fu_oaya8E:-L4gzbS6Az1NXWBhaVyR:b-i8gu81) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a590b37d656fb46834de67f1fe80bf1a06a734e/pkg/sql/opt/build/builder.go#L52)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Can you add a TODO here as well to explain why these are nil?
</blockquote></details>

nil triggers an NYI error whereas their absence triggers an index out-of-range error. I removed the existing ConstructAny/Some/All methods because I think we need to handle them differently, and I didn't want to worry about them in the exec builder. I added a comment.

---

*[pkg/sql/opt/exec/engine.go, line 33 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22423#-L4gbWrCBqLU22AuvGbf:-L4h560x75NfufDEu2b3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a590b37d656fb46834de67f1fe80bf1a06a734e/pkg/sql/opt/exec/engine.go#L33)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] Should there be some guidance here as to whether a Factory can/should be reused across queries?
</blockquote></details>

Done.

---

*[pkg/sql/opt/exec/build/builder_test.go, line 39 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22423#-L4geeepAUXvdbUgcmEF:-L4h59P8XhY7yZdxdiwh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/80568d090594b4a9116491f28f2987a784d48014/pkg/sql/opt/exec/build/builder_test.go#L39)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

copy paste-o?
</blockquote></details>

Done.

---

*[pkg/sql/opt/exec/build/builder_test.go, line 76 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22423#-L4gehniGZZrvpA_oIYi:-L4h5I2u4XVkPotxnyhL:b-pguedb) ([raw file](https://github.com/cockroachdb/cockroach/blob/80568d090594b4a9116491f28f2987a784d48014/pkg/sql/opt/exec/build/builder_test.go#L76)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Are we positive that this won't lead to a circular dependency at some point? I feel uneasy about this package depending on sql.
</blockquote></details>

I fixed this per our offline convo.

---

*[pkg/sql/opt/exec/build/main_test.go, line 35 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22423#-L4gcqWxwGlUw3wpi6dm:-L4h5KuU7wOLTMM8qYM5:bo46xem) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a590b37d656fb46834de67f1fe80bf1a06a734e/pkg/sql/opt/exec/build/main_test.go#L35)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why did you delete this stuff? This is a useful way to prevent depending on sql. You probably just need to change the package name for this file to build_test
</blockquote></details>

Yep, I got this fixed.

---

*[pkg/sql/opt/xform/testdata/typing, line 204 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22423#-L4gbl-gu36bpI60136t:-L4h5PbSkUiZD1WAVugr:b-qvcw9g) ([raw file](https://github.com/cockroachdb/cockroach/blob/71e439618f95bef5f83242a914d023e3b605f367/pkg/sql/opt/xform/testdata/typing#L204)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Is this related to the rest of the change?
</blockquote></details>

These ops appear to be just syntactic sugar that can get mapped to our Exists op. I didn't want to think about how to handle them in the exec builder, so I just deleted them. : )

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22423)*

**Comment by rytaft** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22423)*

**Pull request merged**
