### PR TITLE
UI: Add tooltips to the visualization wrapper

### PR DESCRIPTION
**Pull request by maxlang**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6006)

### CODE REVIEW

**Comment by maxlang** [comment]
cc @mrtracy Ready for review, but working on the actual tooltip text with @jseldess

**Comment by maxlang** [comment]
Currently only includes 3 tooltips, and doesn't include a separate warning state. The info icon only appears if the visualization has a tooltip, but the warning icon always appears in the error/warning state.

screen shot 2016-04-13 at 2 05 32 pm
screen shot 2016-04-13 at 2 05 37 pm
screen shot 2016-04-13 at 2 05 56 pm

**Comment by mrtracy** [comment]
Reviewed 5 of 9 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[ui/styl/modules/palette.styl, line 62 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6006#-KFG20LdAPUJcszvVd19:-KFG20LdAPUJcszvVd1A:1371220135) ([raw file](https://github.com/cockroachdb/cockroach/blob/722a3a8f3ac5ca9fabc814051a897bb7080f1fab/ui/styl/modules/palette.styl#L62)):*
Any rease

---

*[ui/styl/partials/layout.styl, line 579 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6006#-KFG6FLnwlDV1_cIJKct:-KFG6FLnwlDV1_cIJKcu:-1488303199) ([raw file](https://github.com/cockroachdb/cockroach/blob/722a3a8f3ac5ca9fabc814051a897bb7080f1fab/ui/styl/partials/layout.styl#L579)):*
I don't think you're using .left anywhere.

---

*[ui/styl/partials/layout.styl, line 610 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6006#-KFG60u9B1uzvtrc93Uj:-KFG60uA_wWGYQgZlf64:-2082519553) ([raw file](https://github.com/cockroachdb/cockroach/blob/722a3a8f3ac5ca9fabc814051a897bb7080f1fab/ui/styl/partials/layout.styl#L610)):*
What's the point of the .left/.right classes if you're applying values based on hierarchy like this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6006)*

**Comment by mrtracy** [comment]
:lgtm:, suggestions provided on how to clean up the CSS a bit.  

I would like for the tooltips to eventually position themselves more intelligently (for example, based on mouse cursor position); explicitly specifying '.left/.right' or doing it based on hierarchy is fine for now, though (although I would suggest picking one approach or the other, if possible).

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6006#-:-KFG74zoKz1qPlLSD_hF:-686233971)*

**Comment by maxlang** [comment]
Cleaned up the CSS to just use the hierarchy as suggested. I'll hold off on doing something more intelligent until I see if there's a react component that can handle the various issues involved with this instead (eg detecting if a tooltip would go off the page and repositioning it.)

---

Review status: 7 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[ui/styl/modules/palette.styl, line 62 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6006#-KFG20LdAPUJcszvVd19:-KFG7TEjG1LYQwKlZrlx:166874) ([raw file](https://github.com/cockroachdb/cockroach/blob/722a3a8f3ac5ca9fabc814051a897bb7080f1fab/ui/styl/modules/palette.styl#L62)):*
?

---

*[ui/styl/partials/layout.styl, line 579 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6006#-KFG6FLnwlDV1_cIJKct:-KFGAHkcny0KNO4H6YO6:610327451) ([raw file](https://github.com/cockroachdb/cockroach/blob/722a3a8f3ac5ca9fabc814051a897bb7080f1fab/ui/styl/partials/layout.styl#L579)):*
Removed

---

*[ui/styl/partials/layout.styl, line 610 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6006#-KFG60u9B1uzvtrc93Uj:-KFGAGwCnJ8QCGinR2i6:610327451) ([raw file](https://github.com/cockroachdb/cockroach/blob/722a3a8f3ac5ca9fabc814051a897bb7080f1fab/ui/styl/partials/layout.styl#L610)):*
Removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6006#-:-KFGAPYTzEwAAqGq42dV:1061755818)*

**Comment by jseldess** [comment]
Review status: 7 of 9 files reviewed at latest revision, 11 unresolved discussions.

---

*[ui/ts/pages/cluster.ts, line 100 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6006#-KFGWc0yoo3U72uhJciK:-KFGWc0yoo3U72uhJciL:1139696367) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b45fbb54eed0cf42275591a8c6baafc65f1d383/ui/ts/pages/cluster.ts#L100)):*
I'd go with "The total number of nodes in the cluster." 

---

*[ui/ts/pages/cluster.ts, line 103 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6006#-KFGWthRLMk5EtzGiJPb:-KFGWthRLMk5EtzGiJPc:-320719794) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b45fbb54eed0cf42275591a8c6baafc65f1d383/ui/ts/pages/cluster.ts#L103)):*
Can we make this tootltip dynamic? If so, I'd suggest:

"You are using ~3GB of ~80GB storage capacity across all nodes."

If it needs to be static, we could try:

"The estimated percentage of total storage capacity currently in use."

---

*[ui/ts/pages/cluster.ts, line 129 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6006#-KFGXsnay5YwLS5FxAu6:-KFGXsnay5YwLS5FxAu7:-262437634) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b45fbb54eed0cf42275591a8c6baafc65f1d383/ui/ts/pages/cluster.ts#L129)):*
For Query Time, we could try this:

"The estimated time between query request and response, in milliseconds."

Not sure how to explain the percentiles here. Need to work with someone on that.

---

*[ui/ts/pages/cluster.ts, line 142 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6006#-KFGYGSSik8b29mpFSQb:-KFGYGSSik8b29mpFSQc:-1735266942) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b45fbb54eed0cf42275591a8c6baafc65f1d383/ui/ts/pages/cluster.ts#L142)):*
Maybe: "The percentage of CPU used by CockroachDB (User %) and system-level operations (Sys %) across all nodes."

---

*[ui/ts/pages/cluster.ts, line 151 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6006#-KFGYgadXI0cYnYE4QqA:-KFGYgadXI0cYnYE4QqB:775014403) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b45fbb54eed0cf42275591a8c6baafc65f1d383/ui/ts/pages/cluster.ts#L151)):*
I'd suggest: "The average memory in use across all nodes."

---

*[ui/ts/pages/cluster.ts, line 158 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6006#-KFGYriQRG8huxdxAnUG:-KFGYriRRPG7vLuwARZX:-1311199335) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b45fbb54eed0cf42275591a8c6baafc65f1d383/ui/ts/pages/cluster.ts#L158)):*
Suggested tooltip: "The total number of active SQL connections to the cluster."

---

*[ui/ts/pages/cluster.ts, line 170 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6006#-KFGZ9-XCLFxioq7Ynvq:-KFGZ9-XCLFxioq7Ynvr:-1929824576) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b45fbb54eed0cf42275591a8c6baafc65f1d383/ui/ts/pages/cluster.ts#L170)):*
Suggested tooltip: "The amount on network traffic sent to and from the SQL system, in bytes."

---

*[ui/ts/pages/cluster.ts, line 178 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6006#-KFGZJ5Ztk3msMpPP96E:-KFGZJ5Ztk3msMpPP96F:-1916909966) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b45fbb54eed0cf42275591a8c6baafc65f1d383/ui/ts/pages/cluster.ts#L178)):*
Suggested tooltip: "The number of SELECT statements, averaged over a 10 second period."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6006)*

**Comment by jseldess** [comment]
*[ui/ts/pages/cluster.ts, line 170 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6006#-KFGZ9-XCLFxioq7Ynvq:-KFG_6ltNQxcLaLfTwS7:1528752168) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b45fbb54eed0cf42275591a8c6baafc65f1d383/ui/ts/pages/cluster.ts#L170)):*
Spelling mistake in there. Meant: "The amount of network traffic sent to and from the SQL system, in bytes."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6006)*

**Comment by maxlang** [comment]
@jseldess Here are all the current tooltips.

screen shot 2016-04-14 at 1 27 48 pm
screen shot 2016-04-14 at 1 27 42 pm
screen shot 2016-04-14 at 1 27 36 pm
screen shot 2016-04-14 at 1 27 29 pm
screen shot 2016-04-14 at 1 27 22 pm
screen shot 2016-04-14 at 1 27 17 pm
screen shot 2016-04-14 at 1 27 11 pm
screen shot 2016-04-14 at 1 27 06 pm
screen shot 2016-04-14 at 1 26 57 pm

**Comment by jseldess** [comment]
LGTM, @maxlang. Should we add tooltips for other tabs in this PR, or would you rather do that in a separate PR?

**Comment by maxlang** [comment]
@jseldess yeah let's do it in a separate PR. Let's see if we can go through the rest of the graphs with @cuongdo and @mrtracy

**Pull request merged**
