### PR TITLE
Move ts.keyDataPrefix to keys.TimeseriesPrefix.

### PR DESCRIPTION
**Pull request by petermattis**
Simplify rangeAddressing.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4186)

### CODE REVIEW

**Comment by tschottdorf** [comment]
unrelated-ish, but `RangeMetaKey` has logic based off of `Meta{1,2}Prefix[0]` - that means we should have a test somewhere verifying that these prefixes are single-character.

LGTM

---

Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4186#-:-K9uaAJdMrjoMnazef_8:1639144029)*

**Comment by petermattis** [comment]
If the `Meta{1,2}Prefix` constants change to be larger than 1 byte, lots of tests break. I'm not sure if any additional specific testing is worthwhile there. 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4186#-:-K9wMAy1-HGjj9AiA0vs:-1627021162)*

**Comment by tschottdorf** [comment]
Ok, I'll take your word for it. Hypothetical concern anyway.

**Comment by petermattis** [comment]
FYI, I tried changing `Meta1Prefix` to `\x02\x01` and ran the tests. Boom. Lots of failures.

**Pull request merged**
