### PR TITLE
storage: avoid unnecessary abort cache check on 1PC writes

### LINKED ISSUE #13359: storage: remove unnecessary abort cache checks
We currently check the abort-cache to see if a transaction has been aborted on transactional reads and writes. This check involves a RocksDB read which is mildly expensive. For 1PC transactions this is unnecessary as there is no possibility of an abort-cache record. 

I'm not sure if there is a good signal whether a transactional read operation is the sole operation in a transaction. The existing `isOnePhaseCommit` method used on writes checks for a begin and end transaction request in the batch. But for a read-only transaction we never send a begin transaction. We might have to plumb down an additional signal in the `BatchRequest`, but that shouldn't be difficult.

Cc @bdarnell, @spencerkimball

### PR DESCRIPTION
**Pull request by petermattis**
Fixes #13359

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13386)

### CODE REVIEW

**Comment by bdarnell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/replica.go, line 4029 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13386#-Kc4OewOW4Pj6BsKAqpG:-Kc4OewOW4Pj6BsKAqpH:b-el32em) ([raw file](https://github.com/cockroachdb/cockroach/blob/20e16f41f4b7608ee1474154c7cfa934b8724e42/pkg/storage/replica.go#L4029)):*
> ```Go
> 	// hindered by this). Note that we don't do this check for 1PC transactions
> 	// that never write a transaction record.
> 	if ba.Txn != nil && ba.IsTransactionWrite() {
> ```

I think we can move this down another level into `executeBatch` to avoid the duplication. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13386)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/replica.go, line 4029 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13386#-Kc4OewOW4Pj6BsKAqpG:-Kc4l0bKSkH_nwgHcr5_:b-vs1dmy) ([raw file](https://github.com/cockroachdb/cockroach/blob/20e16f41f4b7608ee1474154c7cfa934b8724e42/pkg/storage/replica.go#L4029)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I think we can move this down another level into `executeBatch` to avoid the duplication. 
</blockquote></details>

True, though I'd need a way to signal that we should return a `nil` batch here. I made a stab at this and it didn't look much better. Take a look at the early return in `applyRaftCommandInBatch` when this method returns a `nil` batch. I'm open to suggestions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13386)*

**Comment by bdarnell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/replica.go, line 4029 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13386#-Kc4OewOW4Pj6BsKAqpG:-Kc54MmsJNIRseDvYMcb:b-nvbyym) ([raw file](https://github.com/cockroachdb/cockroach/blob/20e16f41f4b7608ee1474154c7cfa934b8724e42/pkg/storage/replica.go#L4029)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

True, though I'd need a way to signal that we should return a `nil` batch here. I made a stab at this and it didn't look much better. Take a look at the early return in `applyRaftCommandInBatch` when this method returns a `nil` batch. I'm open to suggestions.
</blockquote></details>

But why does it need to be a nil batch? Can't you just return a real (empty) batch and let it be closed through the error path in `applyRaftCommandInBatch`? That's a slight behavior change from the previous version, but I think it's better to get this onto the same error path as anything else. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13386)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/storage/replica.go, line 4029 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13386#-Kc4OewOW4Pj6BsKAqpG:-Kc5ofLDNr7Otm1hiE0Y:bp6ldjn) ([raw file](https://github.com/cockroachdb/cockroach/blob/20e16f41f4b7608ee1474154c7cfa934b8724e42/pkg/storage/replica.go#L4029)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

But why does it need to be a nil batch? Can't you just return a real (empty) batch and let it be closed through the error path in `applyRaftCommandInBatch`? That's a slight behavior change from the previous version, but I think it's better to get this onto the same error path as anything else. 
</blockquote></details>

I took another approach to remove the duplication. PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13386)*

**Comment by bdarnell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/replica.go, line 4015 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13386#-Kc9U-6AuoxI1Dk6Lnxp:-Kc9U-6AuoxI1Dk6Lnxq:bqicl6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/76c00798aba23cbab8f51b8dbb1cc7cb65f34f4b/pkg/storage/replica.go#L4015)):*
> ```Go
> 	// hindered by this). Note that we don't do this check for 1PC transactions
> 	// that never write a transaction record.
> 	if ba.Txn != nil && ba.IsTransactionWrite() {
> ```

I think we need to do this for `ba.Txn != nil && (ba.IsTransactionWrite() || ba.Txn.Writing)` to handle the #2231 case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13386)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/replica.go, line 4015 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13386#-Kc9U-6AuoxI1Dk6Lnxp:-Kc9VDqJhxjSaEcsSWiq:b-rx2egm) ([raw file](https://github.com/cockroachdb/cockroach/blob/76c00798aba23cbab8f51b8dbb1cc7cb65f34f4b/pkg/storage/replica.go#L4015)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I think we need to do this for `ba.Txn != nil && (ba.IsTransactionWrite() || ba.Txn.Writing)` to handle the #2231 case.
</blockquote></details>

This was the condition we were using previously. I'm not following why `|| ba.Txn.Writing` would be necessary now. Or perhaps it was necessary before and we were just doing this wrong.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13386)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/replica.go, line 4015 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13386#-Kc9U-6AuoxI1Dk6Lnxp:-Kc9XOEwZZn3llyPvJiT:b-7ahw18) ([raw file](https://github.com/cockroachdb/cockroach/blob/76c00798aba23cbab8f51b8dbb1cc7cb65f34f4b/pkg/storage/replica.go#L4015)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This was the condition we were using previously. I'm not following why `|| ba.Txn.Writing` would be necessary now. Or perhaps it was necessary before and we were just doing this wrong.
</blockquote></details>

Never mind, I was getting this mixed up with #13367. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13386#-:-Kc9XS4jH8JgSDyMhubn:bnfp4nl)*

**Pull request merged**
