### PR TITLE
sql: improve the handling of CREATE TABLE ... AS ...

### LINKED ISSUE #20227: sql: createTableAs should implement `planNodeFastPath`
the `createTableNode` has a `rowsAffected` field (currently called `count`) like `createUser`, but its handling uses a weird special case in the executor. I think it can be simplified to use the `planNodeFastPath` interface instead.

### PR DESCRIPTION
**Pull request by knz**
Fixes #20227.

cc @vivekmenezes for the first commit.

cc @mjibson for the last commit -- once again the `pq` driver is being annoying. Do you think I should file an issue upstream?

### CODE REVIEW

**Comment by vivekmenezes** [comment]
first commit LGTM

**Comment by mjibson** [comment]
Yes, it'd be nice to have an issue upstream for this. I wasn't aware of that behavior.

**Comment by knz** [comment]
Filed upstream as https://github.com/lib/pq/issues/682.

**Comment by jordanlewis** [comment]
Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 6 of 6 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/sem/tree/stmt.go, line 90 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20268#-L-3j7HzGD_rAMDgVuGG:-L-3j7HzGD_rAMDgVuGH:bch94jm) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf12dab930c0348d22641fc540b2080977dc2707/pkg/sql/sem/tree/stmt.go#L90)):*
> ```Go
> // the database schema but may have StatementType() != DDL.
> // See CanModifySchema() below.
> type canModifySchema interface {
> ```

Raphael! What is the deal? I thought you were adamantly against emulating type switches with Golang interface implementations.

I think we really need to sit down and make a more coherent strategy around this kind of thing. You often push back on people doing this.

Your previous argument was that we should put functionality in a single file near where it's used. Now it's spread near the data. I personally *like* this style - I'm just bewildered trying to understand why you've chosen to do it this way when you also push back against this strategy in other PRs (and in fact our codebase's status quo).

---

*[pkg/sql/sem/tree/stmt.go, line 218 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20268#-L-3lbW4PpRpCBiDohza:-L-3lbW4PpRpCBiDohzb:b-fyv1ns) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd114c06ca9ca35e39d5a1346633c2432492e725/pkg/sql/sem/tree/stmt.go#L218)):*
> ```Go
> 	if n.As() {
> 		return RowsAffected
> 	}
> ```

Seems like we need a higher level test for this - you said we can see it in psql right? Can you test it with the psql acceptance test?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20268)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/sem/tree/stmt.go, line 90 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20268#-L-3j7HzGD_rAMDgVuGG:-L-3nneUcwprdHJa6aMp:b-hxmpli) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf12dab930c0348d22641fc540b2080977dc2707/pkg/sql/sem/tree/stmt.go#L90)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Raphael! What is the deal? I thought you were adamantly against emulating type switches with Golang interface implementations.

I think we really need to sit down and make a more coherent strategy around this kind of thing. You often push back on people doing this.

Your previous argument was that we should put functionality in a single file near where it's used. Now it's spread near the data. I personally *like* this style - I'm just bewildered trying to understand why you've chosen to do it this way when you also push back against this strategy in other PRs (and in fact our codebase's status quo).
</blockquote></details>

So yes I generally push back against this kind of thing, but for now in this file we have a pattern going, and I needed to fix the bug without starting a big refactor.
If I were to do this differently for this property, it wouldn't be homogeneous with the other properties encoded here. Hence my choice (I don't fully like it, but I respect existing patterns while bug fixing).

---

*[pkg/sql/sem/tree/stmt.go, line 218 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20268#-L-3lbW4PpRpCBiDohza:-L-3o4gfaazh5BUhj-cs:bp32udq) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd114c06ca9ca35e39d5a1346633c2432492e725/pkg/sql/sem/tree/stmt.go#L218)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Seems like we need a higher level test for this - you said we can see it in psql right? Can you test it with the psql acceptance test?
</blockquote></details>

This is tested in the new test `TestCreateStatementType` in `create_test.go`. I made a Go test with our internal driver because I couldn't use `pq`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20268)*

**Comment by jordanlewis** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/sem/tree/stmt.go, line 90 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20268#-L-3j7HzGD_rAMDgVuGG:-L-86PQmRLiNhyu_-FHn:b32w1t) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf12dab930c0348d22641fc540b2080977dc2707/pkg/sql/sem/tree/stmt.go#L90)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

So yes I generally push back against this kind of thing, but for now in this file we have a pattern going, and I needed to fix the bug without starting a big refactor.
If I were to do this differently for this property, it wouldn't be homogeneous with the other properties encoded here. Hence my choice (I don't fully like it, but I respect existing patterns while bug fixing).
</blockquote></details>

Ok

---

*[pkg/sql/sem/tree/stmt.go, line 218 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20268#-L-3lbW4PpRpCBiDohza:-L-86G3CNKZpAdp2PZQF:bdqq5rr) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd114c06ca9ca35e39d5a1346633c2432492e725/pkg/sql/sem/tree/stmt.go#L218)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This is tested in the new test `TestCreateStatementType` in `create_test.go`. I made a Go test with our internal driver because I couldn't use `pq`. 
</blockquote></details>

Can you please add a psql test as well? There are often small discrepancies that are picked up in a test against psql that we don't see in other places.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20268#-:-L-86Qe3i_TwR55y6kK-:bnfp4nl)*

**Comment by knz** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/sem/tree/stmt.go, line 218 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20268#-L-3lbW4PpRpCBiDohza:-L-IFquQkug2BVatBKvk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd114c06ca9ca35e39d5a1346633c2432492e725/pkg/sql/sem/tree/stmt.go#L218)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Can you please add a psql test as well? There are often small discrepancies that are picked up in a test against psql that we don't see in other places.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20268)*

**Comment by knz** [comment]
TFYR!

**Pull request merged**
