### PR TITLE
changefeedccl: fix memory leak in rowFetcherCache

### PR DESCRIPTION
**Pull request by ajwerner**
The rowFetcherCache used by the changefeed to decode KVs into datums
keys the row.Fetcher for a table by using an `*ImmutableTableDescriptor`.
Unfortunately, over time, as the `LeaseManager` renews leases, the table
descriptor used to perform the lookup will change. This leads to a slow
leak of a single `row.Fetcher` every couple of minutes. This ends up
being pretty bad when backfilling a large table as each row.Fetcher ends
up holding onto a whole `ScanResponse`.

Release note (bug fix): Fix memory leak which can affect CHANGEFEEDs
performing scans of large tables.

### CODE REVIEW

**Comment by ajwerner** [comment]
I'm all ears for good testing techniques on this one.

**Review by pbardea — APPROVED** [review]
Approach looks good to me. Just wanted to note that `lease.go` defines a similar struct,`IDVersion`, that we could reuse here.

**Comment by ajwerner** [comment]
I’m aware but didn’t like it because 1) the fields aren’t public and 2) it has the name. Didn’t feel worth adapting something so simple.

**Comment by pbardea** [comment]
Ah, I see - makes sense. LGTM.

**Comment by ajwerner** [comment]
TFTR

bors r=pbardea

**Comment by dt** [comment]
typical bors.

bors r=pbardea

**Pull request merged**
