### PR TITLE
ui: add KeyedCachedDataReducer selector factory util, refactor jobs page props to use RequestState

### PR DESCRIPTION
**Pull request by xinhaoz**
See individual commits.

Release note: None

Epic: CRDB-25476

### CODE REVIEW

**Review by maryliag — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101481)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/store/jobs/jobs.reducer.ts` line 14 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101481#-NTKj28kAKrPaBYEqfLV:-NTKj28kAKrPaBYEqfLW:b-w3pkeb) ([raw file](https://github.com/cockroachdb/cockroach/blob/606b5a094358f89ae06fea3a58180e433aa9d2fc/pkg/ui/workspaces/cluster-ui/src/store/jobs/jobs.reducer.ts#L14)):*
> ```XML
> import { JobsRequest, JobsResponse } from "src/api/jobsApi";
> import { DOMAIN_NAME } from "../utils";
> import moment from "moment-timezone";
> ```

I think it needs to be imported from moment-timezone, related to the work of adding timezone to console pages

**Review by xinhaoz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101481)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/store/jobs/jobs.reducer.ts` line 14 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101481#-NTKj28kAKrPaBYEqfLV:-NTKr37Y-r5lLGYCCwAx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/606b5a094358f89ae06fea3a58180e433aa9d2fc/pkg/ui/workspaces/cluster-ui/src/store/jobs/jobs.reducer.ts#L14)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

I think it needs to be imported from moment-timezone, related to the work of adding timezone to console pages
</blockquote></details>

Done.

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101481#-:-NTKtE-J3_KZgxD0nEAv:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @xinhaoz)

**Comment by xinhaoz** [comment]
TFTR!
bors r+

**Pull request merged**
