### PR TITLE
sql/parser: fix NOT VISIBLE test case

### PR DESCRIPTION
**Pull request by mgartner**
Epic: None

Release note: None

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122565#-:-NvmNS9x1WcaasMHWPlm:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122565#-:-NvqjsLd7xIwrcLvrd3z:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/parser/testdata/create_table` line 2488 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122565#-NvqjfAK0RWkWHPuhhjo:-NvqjfAK0RWkWHPuhhjp:btom8k4) ([raw file](https://github.com/cockroachdb/cockroach/blob/937e995438f011f5c375147a13c10da7c1ab6a8c/pkg/sql/parser/testdata/create_table#L2488)):*
> ```
> ----
> 
> # The following test cases make sure that creating an invisible primary index is
> ```

nit: now there's just one test case, so make this comment singular

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/122565)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/parser/testdata/create_table` line 2488 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/122565#-NvqjfAK0RWkWHPuhhjo:-NwBpXPEC7QUpC8cWz_a:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/937e995438f011f5c375147a13c10da7c1ab6a8c/pkg/sql/parser/testdata/create_table#L2488)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: now there's just one test case, so make this comment singular
</blockquote></details>

Done.

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
