### PR TITLE
schemachanger: Prep work for ALTER DATABASE ... CONFIGURE ZONE

### PR DESCRIPTION
**Pull request by Xiang-Gu**
This PR contains three preparation commits for supporting zone configs in DSC. They should be rather uncontroversial and easy to review. See commit message for details.

Informs: #117574
Epic: CRDB-31473

### CODE REVIEW

**Review by fqazi — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, 4 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118575#-:-NpeZ31cArHAtmgW0_Xt:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @Xiang-Gu)

___
*[`-- commits` line 40 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118575#-NpeYtzG4L-sQgkkLZhv):*
If we are deprecating the old syntax then we probably should call it out in a release note in the future. Before actually removing it along with throwing notices (That's a separate PR problem).

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118575)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @Xiang-Gu)

___
*[`pkg/sql/sqlerrors/errors.go` line 371 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118575#-Npea3OO14By0G9u31_S:-Npea3OO14By0G9u31_T:b-5mjl4i) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f40f913c9d466ad26e2077707c56abea598f47c/pkg/sql/sqlerrors/errors.go#L371)):*
> ```Go
> // the descriptor.
> func NewInsufficientPrivilegeOnDescriptorError(
> 	user string, orPrivs []privilege.Kind, descType string, descName string,
> ```

nit: the user should be a `username.SQLUsername`, not a string.

**Review by Xiang-Gu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118575)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @fqazi)

___
*[`-- commits` line 40 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118575#-NpeYtzG4L-sQgkkLZhv):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

If we are deprecating the old syntax then we probably should call it out in a release note in the future. Before actually removing it along with throwing notices (That's a separate PR problem).
</blockquote></details>

ack, in the future, when we are ready to support `CONFIGURE ZONE` in DSC (which does not support the YAML syntax) we can put a release note there.
___
*[`pkg/sql/sqlerrors/errors.go` line 371 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118575#-Npea3OO14By0G9u31_S:-Npu71Yv2rWROb2TKZXE:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f40f913c9d466ad26e2077707c56abea598f47c/pkg/sql/sqlerrors/errors.go#L371)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: the user should be a `username.SQLUsername`, not a string.
</blockquote></details>

done

**Review by rafiss — APPROVED** [review]

**Comment by Xiang-Gu** [comment]
TFTR!

bors r+

**Pull request merged**
