### PR TITLE
sql: run show cluster setting in a restartable txn

### LINKED ISSUE #30225: teamcity: failed test: version-upgrade
The following tests appear to have failed:

[#903870](https://teamcity.cockroachdb.com/viewLog.html?buildId=903870):

```
--- FAIL: roachtest/acceptance/version-upgrade (188.491s)
	test.go:503,upgrade.go:415,retry.go:188,upgrade.go:409,upgrade.go:571,upgrade.go:576,acceptance.go:59: 1: pq: value differs between gossip (2.0-13) and KV (2.0); try again later (<nil> after 1m59.06830204s)

--- FAIL: roachtest/acceptance/version-upgrade (188.491s)
	test.go:503,upgrade.go:415,retry.go:188,upgrade.go:409,upgrade.go:571,upgrade.go:576,acceptance.go:59: 1: pq: value differs between gossip (2.0-13) and KV (2.0); try again later (<nil> after 1m59.06830204s)


```

Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by jordanlewis**
Previously, SHOW CLUSTER SETTING would run in the parent txn. This was
troublesome because if it misses a KV update once (due to an older txn
timestamp), it'll miss it in perpetuity.

Now, we make a fresh transaction for the kv read, and allow it to
restart.

Closes #30225.

Release note: None

### CODE REVIEW

**Comment by jordanlewis** [comment]
This is extremely science dog, but in principle I don't see any reason why it's not ok to make a new transaction here. The analogous SET CLUSTER SETTING code does it, for example.

**Review by tbg — APPROVED** [review]
LGTM, but equally :woman_scientist: :dog2: as well, so let's get someone who would know... @andreimatei?

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30721#-:-LNQim752LZ6ou5ITQFB:bmqcvyf)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
well so this patch introduces non-repeatable reads for transactions that call this `showStateMachineSetting()`. I'm not sure if it's a good idea (but I haven't checked how this function is used).
Why would we do this , exactly? Skimming through #30225, I understand that the problem is with a `set` statement. Can't we have that guy create new transactions for every iteration of its polling? (and also probably make that particular `set` statement illegal inside transactions?)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30721#-:-LNQkb100RMYYwBnKg8d:b-hepzqp)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by jordanlewis** [comment]
Andrei, I think the problem is only in SHOW, not in SET.

**Comment by andreimatei** [comment]
The can you describe the problem, please? :)

**Comment by jordanlewis** [comment]
Gossip can win against KV. If the two disagree, you need to restart your txn and check KV again. I think. Honestly, I'm not sure how these components interact exactly.

**Comment by andreimatei** [comment]
OK, so this is about `show cluster setting version`. I think you want to make this statement non-transactional (i.e. make it error out if it's ran inside an explicit txn). In fact, I think we should make all `show cluster setting` statements non-transactional. Then this change looks fine to me (modulo the fact that I think it's missing the retries).

**Comment by jordanlewis** [comment]
What do you mean you think it's missing the retries?

**Review by andreimatei — CHANGES_REQUESTED** [review]
See my comment below
> we used to retry on this, now we don't. Shouldn't we?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30721#-:-LNRfgmeEoVzAu9xTuCQ:b-yn9wuo)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/show_cluster_setting.go, line 86 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30721#-LNQqK7c6_hqCTUrFUf3:-LNQqK7d3Zztr0GOfwXc:b-zfsgz1) ([raw file](https://github.com/cockroachdb/cockroach/blob/40ba6a03f0895be882ec3dc5e802f9375599b50c/pkg/sql/show_cluster_setting.go#L86)):*
> ```Go
> 		}
> 		if !bytes.Equal(gossipRawVal, kvRawVal) {
> 			return errors.Errorf("value differs between gossip (%v) and KV (%v); try again later (%v after %s)", gossipObj, kvObj, retryCtx.Err(), timeutil.Since(tBegin))
> ```

we used to retry on this, now we don't. Shouldn't we?

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30721)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/show_cluster_setting.go, line 86 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30721#-LNQqK7c6_hqCTUrFUf3:-LNturiJ3a0_i2nQBpUw:b-glwtq5) ([raw file](https://github.com/cockroachdb/cockroach/blob/40ba6a03f0895be882ec3dc5e802f9375599b50c/pkg/sql/show_cluster_setting.go#L86)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

we used to retry on this, now we don't. Shouldn't we?
</blockquote></details>

Yes I suppose we should. Is the right way to do that to keep the outer Retry that I deleted and embed this Txn call within?  Also, I don't understand what the last WithMaxAttempts was for - it seems to have been set to MaxInt32 retries.

**Comment by jordanlewis** [comment]
PTAL @andreimatei

**Review by andreimatei — APPROVED** [review]
LGTM

But what did you think about disallowing `show cluster setting` in a txn?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30721#-:-LOYdUt07fuA2Rhhhn2t:b-vdu96g)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/show_cluster_setting.go, line 23 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30721#-LOYdO-dC5T8hjMkH7fq:-LOYdO-dC5T8hjMkH7fr:b-c59hrr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6930582e3c86724a9a4ff8785e66c374985588f/pkg/sql/show_cluster_setting.go#L23)):*
> ```Go
> 	"strings"
> 	"time"
> ```

extra line

**Comment by jordanlewis** [comment]
> But what did you think about disallowing show cluster setting in a txn?

What's the point? I guess to just prevent people from being confused? If we're doing this, I think we should do them all at once - and if that's the case, not in this PR.

**Comment by jordanlewis** [comment]
TFTR!

**Comment by andreimatei** [comment]
Schema changes are special beasts indeed, but I don't quite see the analogy. The atomicity of schema changes is questionable, leading to write-skew type anomalies, but that's different (even schema changes outside of txns would have that problem).

**Comment by knz** [comment]
this needs a backport if you claim it fixes #28879.

**Pull request merged**
