### PR TITLE
docs: update keys section

### PR DESCRIPTION
**Pull request by petermattis**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9670)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[docs/design.md, line 144 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9670#-KT9pm5d_K7N2BYD-KvS:-KT9pm5d_K7N2BYD-KvT:bcsfq3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/a135204f1e763a37ccbb316624f0831cdd83acc7/docs/design.md#L144)):*
> ```Markdown
> System keys come in several subtypes:
> 
> - **Global** keys are used by the "meta1" and "meta2" tables as well
> ```

do we really want to call these tables?

---

*[docs/design.md, line 152 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9670#-KT9pyTgwyUa-O0XYQL2:-KT9pyTh-0URxcn72Ree:b-fzrw85) ([raw file](https://github.com/cockroachdb/cockroach/blob/a135204f1e763a37ccbb316624f0831cdd83acc7/docs/design.md#L152)):*
> ```Markdown
>     data they hold is tied to the lifetime of the store they are
>     present on.
> - **Range local** keys store range metadata that is associated with a
> ```

"associated with a global key"?

---

*[docs/design.md, line 163 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9670#-KT9qUzIgghOExPaizVf:-KT9qUzIgghOExPaizVg:b1ljzap) ([raw file](https://github.com/cockroachdb/cockroach/blob/a135204f1e763a37ccbb316624f0831cdd83acc7/docs/design.md#L163)):*
> ```Markdown
> 
> Table data keys are used to store all SQL data. Table data keys have
> structure as described in the section on [mapping data between the SQL
> ```

"have structure" is awkward

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9670#-:-KT9qY1me3kSsoPno1NY:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[docs/design.md, line 144 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9670#-KT9pm5d_K7N2BYD-KvS:-KTA-ZSvVGV1cS8-7rZp:b-7chdat) ([raw file](https://github.com/cockroachdb/cockroach/blob/a135204f1e763a37ccbb316624f0831cdd83acc7/docs/design.md#L144)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> do we really want to call these tables?
</details>
We seem to be moving away from that terminology. Changed.

---

*[docs/design.md, line 152 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9670#-KT9pyTgwyUa-O0XYQL2:-KTA-rK72dfqyWD_2T8a:bhpfhmo) ([raw file](https://github.com/cockroachdb/cockroach/blob/a135204f1e763a37ccbb316624f0831cdd83acc7/docs/design.md#L152)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> "associated with a global key"?
</details>
Yeah, I'm not sure of a better way to express that. Range local keys have a special prefix followed by a global key and then a special suffix. For example, transaction record keys look like: `\x01k<global-key>txn-<txnID>`.

---

*[docs/design.md, line 163 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9670#-KT9qUzIgghOExPaizVf:-KTA0W9CJRx2iBQ1vWiB:b-qj92pf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a135204f1e763a37ccbb316624f0831cdd83acc7/docs/design.md#L163)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> "have structure" is awkward
</details>
Reworded.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9670)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[docs/design.md, line 152 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9670#-KT9pyTgwyUa-O0XYQL2:-KTA0swTXNAHA5DaztEP:blp1zdx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a135204f1e763a37ccbb316624f0831cdd83acc7/docs/design.md#L152)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Yeah, I'm not sure of a better way to express that. Range local keys have a special prefix followed by a global key and then a special suffix. For example, transaction record keys look like: `\x01k<global-key>txn-<txnID>`.
</details>
Perhaps just include that more verbose explanation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9670)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/design.md, line 152 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9670#-KT9pyTgwyUa-O0XYQL2:-KTA1bkPBPRIqjHB6LX1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a135204f1e763a37ccbb316624f0831cdd83acc7/docs/design.md#L152)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Perhaps just include that more verbose explanation.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9670)*

**Pull request merged**
