### PR TITLE
sql: add version gating for multi-region and implicit column partitioning

### LINKED ISSUE #59226: sql: add version gating for multiregion or implicit column partitioning features

### PR DESCRIPTION
**Pull request by otan**
See commits for details.

Resolves #59226

### CODE REVIEW

**Review by ajstorm — APPROVED** [review]
Irresponsibly? I think you're ready to become a parent.

> Reviewed 4 of 4 files at r1, 15 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60605#-:-MTpEh3k2deo0zWO2sBU:brhi635)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @otan)

___
*[pkg/ccl/partitionccl/partition.go, line 377 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60605#-MTpPHyD2DlOxEyUeE0k:-MTpPHyD2DlOxEyUeE0l:bm3j5pt) ([raw file](https://github.com/cockroachdb/cockroach/blob/6699a5c11b28f5931fb449630e139038672a55e0/pkg/ccl/partitionccl/partition.go#L377)):*
> ```Go
> 			return indexDesc, pgerror.Newf(
> 				pgcode.ObjectNotInPrerequisiteState,
> 				`cannot use implicit column partitioning whilst the cluster is upgrading`,
> ```

Nit: whilst->while
___
*[pkg/sql/alter_database.go, line 278 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60605#-MTpQ1_WAfzqY-elhBN1:-MTpQ1_WAfzqY-elhBN2:b-sog5lz) ([raw file](https://github.com/cockroachdb/cockroach/blob/6699a5c11b28f5931fb449630e139038672a55e0/pkg/sql/alter_database.go#L278)):*
> ```Go
> 	}
> 
> 	if err := checkMultiRegionEnabled(p.EvalContext()); err != nil {
> ```

Nit: Does it make sense to make this an assertion here?  How could we get into the situation where we're dropping. a region on a mixed-level cluster?  Same comment for AlterAdd, and AlterSurvive.
___
*[pkg/sql/alter_table_locality.go, line 54 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60605#-MTpQZUdC3ww_8nVbCzc:-MTpQZUdC3ww_8nVbCzd:b-atejh1) ([raw file](https://github.com/cockroachdb/cockroach/blob/6699a5c11b28f5931fb449630e139038672a55e0/pkg/sql/alter_table_locality.go#L54)):*
> ```Go
> 	}
> 
> 	if err := checkMultiRegionEnabled(p.EvalContext()); err != nil {
> ```

Nit: Does it make sense to make this an assert after the Multi-region check below?  Same comment for CREATE.
___
*[pkg/sql/create_table.go, line 1645 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60605#-MTpReJAE0zTbWuLkwBS:-MTpReJAE0zTbWuLkwBT:bm3j5pt) ([raw file](https://github.com/cockroachdb/cockroach/blob/6699a5c11b28f5931fb449630e139038672a55e0/pkg/sql/create_table.go#L1645)):*
> ```Go
> 				return nil, pgerror.Newf(
> 					pgcode.ObjectNotInPrerequisiteState,
> 					`cannot use PARTITION ALL BY whilst the cluster is upgrading`,
> ```

Nit: whilst->while
___
*[pkg/sql/create_table.go, line 2739 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60605#-MTpRNM00NThOCeZoEkH:-MTpRNM00NThOCeZoEkI:b-k4sp7k) ([raw file](https://github.com/cockroachdb/cockroach/blob/6699a5c11b28f5931fb449630e139038672a55e0/pkg/sql/create_table.go#L2739)):*
> ```Go
> }
> 
> func checkMultiRegionEnabled(evalCtx *tree.EvalContext) error {
> ```

Nit: Does it make sense to add a checkImplicitPartitioningEnabled?  I'd think this would make the code a bit more readable.
___
*[pkg/sql/create_table.go, line 2743 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60605#-MTpRXMXCLCGxfqPS0rp:-MTpRXMXCLCGxfqPS0rq:b-p9mmhv) ([raw file](https://github.com/cockroachdb/cockroach/blob/6699a5c11b28f5931fb449630e139038672a55e0/pkg/sql/create_table.go#L2743)):*
> ```Go
> 		return pgerror.Newf(
> 			pgcode.ObjectNotInPrerequisiteState,
> 			`cannot use multi-region features whilst the cluster is upgrading`,
> ```

Nit: whilst->while.
___
*[pkg/sql/descriptor.go, line 321 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60605#-MTpRkiL4z_i5TMXQxhR:-MTpRkiL4z_i5TMXQxhS:bnq36sz) ([raw file](https://github.com/cockroachdb/cockroach/blob/6699a5c11b28f5931fb449630e139038672a55e0/pkg/sql/descriptor.go#L321)):*
> ```Go
> 		return nil, nil
> 	}
> 	if err := checkMultiRegionEnabled(p.EvalContext()); err != nil {
> ```

Nit: Or does it make sense for this to the principal blocking location? 
___
*[pkg/sql/logictest/logic.go, line 503 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60605#-MTpEupHA8RhTOBftU6A:-MTpEupHA8RhTOBftU6B:b-366p36) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf533486a44c2b4cb1b7ffa5508b07d3bc7415c8/pkg/sql/logictest/logic.go#L503)):*
> ```Go
> 	},
> 	{
> 		name:                "local-mixed-20.2-20.1",
> ```

Do we only ever test one level down for mixed versions?

**Review by arulajmani — APPROVED** [review]
nit: In all the error messages, can we put the exact version finalization required? I quite like how ALTER COLUMN TYPE does this `"version %v must be finalized to run this alter column type"`

Other than that, :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60605#-:-MTpc5eCE_2RC3ecMiMc:b-k801y8)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan)

**Review by otan — COMMENTED** [review]
> must be finalized to run this alter column type

this displays as `version MultiRegionFeatures must be finalized to use multi-region features` which i think is even less clear.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60605#-:-MTr9AECAPU-lU3xLyj5:bkn838x)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/sql/logictest/logic.go, line 503 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60605#-MTpEupHA8RhTOBftU6A:-MTr9bcn34orITzouECX:b-7xt4rz) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf533486a44c2b4cb1b7ffa5508b07d3bc7415c8/pkg/sql/logictest/logic.go#L503)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Do we only ever test one level down for mixed versions?
</blockquote></details>

Yep.

**Comment by otan** [comment]
bors r=arulajmani,ajstorm

**Comment by otan** [comment]
bors r=arulajmani,ajstorm

**Pull request merged**
