### PR TITLE
sql: detect integer overflow in +, -, *

### LINKED ISSUE #10408: sql: expression normalization does not check for overflows
Run
```
cockroach sql <<EOF
drop database if exists foo;
create database	foo;
create table foo.bar ( i int primary key );
insert into foo.bar values (1),	(2), (3);
select i from foo.bar where i < 9223372036854775807;
select i from foo.bar where i - 1 < 9223372036854775807;
EOF
```
and get
```
DROP DATABASE
CREATE DATABASE
CREATE TABLE
INSERT 3
3 rows
i
1
2
3
0 rows
i
```
Since `i - 1 < i`, the second `select` should produce at least as many rows.

### LINKED ISSUE #14780: sql: integer overflow is not detected
postgres:

```
postgres=# select 9223372036854775807::bigint;
        int8         
---------------------
 9223372036854775807
(1 row)

postgres=# select 9223372036854775807::bigint + 1;
ERROR:  bigint out of range
```

cockroach:

```
root@:26257/> SELECT 1 + 9223372036854775807:::int;
+-------------------------------+
| 1 + 9223372036854775807:::INT |
+-------------------------------+
|          -9223372036854775808 |
+-------------------------------+
(1 row)
```

Postgres detects the integer overflow instead of wrapping. We should perhaps do the same.

### PR DESCRIPTION
**Pull request by madelynnblue**
Fixes #14780
Fixes #10408

### CODE REVIEW

**Comment by knz** [comment]
Consider extending the unary negation as well.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/parser/eval.go, line 544 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14782#-KhR885jWNWwBPdyBRhK:-KhR885jWNWwBPdyBRhL:b1lq2a8) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ae506ed37f7225f90a2498d7e73c2d374579011/pkg/sql/parser/eval.go#L544)):*
> ```Go
> 			ReturnType: TypeInt,
> 			fn: func(_ *EvalContext, left Datum, right Datum) (Datum, error) {
> 				const mostPositive = 1<<63 - 1
> ```

Please provide your source for this code (I suspect you found it here http://grokbase.com/t/gg/golang-nuts/148wdq497d/go-nuts-test-for-an-integer-overflow but nevertheless it needs to be properly cited.)

Also
1. explain why `(mostPositive + 1)` doesn't overflow
2. explain why you're not using `MaxInt64` here
3. explain why the test "a == mostNegative || b == mostNegative" is necessary and why "c/b != a" is not sufficient
4. This code is obscure. Here and above, consider replacing by the (somewhat simpler) tests from pg:
https://git.postgresql.org/gitweb/?p=postgresql.git;a=blob;f=src/backend/utils/adt/int.c;h=bd4422e08a1650696fc7022b443f3af13728c981;hb=HEAD#l597 and below

---

*[pkg/sql/parser/normalize.go, line 345 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14782#-KhR7ghfOrsJEIuBHV5D:-KhR7ghgwIeC8bNfvWq9:b-9rj4wc) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ae506ed37f7225f90a2498d7e73c2d374579011/pkg/sql/parser/normalize.go#L345)):*
> ```Go
> 				newRightExpr, err := newBinExpr.Eval(v.ctx)
> 				if err != nil {
> 					// An error occurred, give up.
> ```

 This does not seem to belong?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14782#-:-KhR9rvcWIAjW0iTaNPv:bm5s1n7)*

**Comment by eisenstatdavid** [comment]
And `INT_MIN / -1`.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/parser/eval.go, line 544 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14782#-KhR885jWNWwBPdyBRhK:-KhSISNrCF2k_ZT1pgwk:b2o2kfr) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ae506ed37f7225f90a2498d7e73c2d374579011/pkg/sql/parser/eval.go#L544)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please provide your source for this code (I suspect you found it here http://grokbase.com/t/gg/golang-nuts/148wdq497d/go-nuts-test-for-an-integer-overflow but nevertheless it needs to be properly cited.)

Also
1. explain why `(mostPositive + 1)` doesn't overflow
2. explain why you're not using `MaxInt64` here
3. explain why the test "a == mostNegative || b == mostNegative" is necessary and why "c/b != a" is not sufficient
4. This code is obscure. Here and above, consider replacing by the (somewhat simpler) tests from pg:
https://git.postgresql.org/gitweb/?p=postgresql.git;a=blob;f=src/backend/utils/adt/int.c;h=bd4422e08a1650696fc7022b443f3af13728c981;hb=HEAD#l597 and below
</blockquote></details>

In case these are not rhetorical questions: (1) Golang constants have infinite precision (2) (and `MinInt64` too) (3) because `MinInt64 * -1` overflows (but `MinInt64 * 1` doesn't). I have no problem with the plus/minus checks; the way to read them is by mentally adding or subtracting `b` from both sides of the inequality. I'm not in love with either this multiply check or the Postgres one -- think it's just a messy problem.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14782#-:-KhSHlpwsh2innt0YLCq:b5szelv)*

**Comment by mjibson** [comment]
I've added unary negation. `INT_MIN / -1` is broken for another reason, and is being tracked in #14817.

---

Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/parser/eval.go, line 544 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14782#-KhR885jWNWwBPdyBRhK:-KhTWomQ6NyhMMm6v6Uk:bbnznrn) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ae506ed37f7225f90a2498d7e73c2d374579011/pkg/sql/parser/eval.go#L544)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

In case these are not rhetorical questions: (1) Golang constants have infinite precision (2) (and `MinInt64` too) (3) because `MinInt64 * -1` overflows (but `MinInt64 * 1` doesn't). I have no problem with the plus/minus checks; the way to read them is by mentally adding or subtracting `b` from both sides of the inequality. I'm not in love with either this multiply check or the Postgres one -- think it's just a messy problem.
</blockquote></details>

I've replaced mostPositive and mostNegative with their corresponding math constants, which the linked code predated (they are identical) (that should take care of 1 and 2). I've added a comment and test case showing the need for 3. I can't understand at all what the linked postgres code is doing, and I find it fairly straightforward what the Go code is doing, so I don't agree with 4.

---

*[pkg/sql/parser/normalize.go, line 345 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14782#-KhR7ghfOrsJEIuBHV5D:-KhTXLIBviemJYw6eajP:b-useg52) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ae506ed37f7225f90a2498d7e73c2d374579011/pkg/sql/parser/normalize.go#L345)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

 This does not seem to belong?
</blockquote></details>

I've added some more detail here. I think it needs a comment because previously we failed the entire normalization instead of just not normalizing. Clarifying why we do it this way now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14782#-:-KhTkBPuJMkpn1jzMek4:bnkfg4h)*

**Comment by eisenstatdavid** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14782#-:-KhTlhnNlrG6lUVIRZ4p:bnfp4nl)*

**Comment by knz** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/eval.go, line 544 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14782#-KhR885jWNWwBPdyBRhK:-KhWHM7e7nC-U-Pn8wbF:b-9t0ji3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ae506ed37f7225f90a2498d7e73c2d374579011/pkg/sql/parser/eval.go#L544)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

I've replaced mostPositive and mostNegative with their corresponding math constants, which the linked code predated (they are identical) (that should take care of 1 and 2). I've added a comment and test case showing the need for 3. I can't understand at all what the linked postgres code is doing, and I find it fairly straightforward what the Go code is doing, so I don't agree with 4.
</blockquote></details>

OK I can live with this for now.

---

*[pkg/sql/parser/normalize.go, line 345 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14782#-KhR7ghfOrsJEIuBHV5D:-KhWHTjN_Z_GvG_KLGlN:b-ucfkn4) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ae506ed37f7225f90a2498d7e73c2d374579011/pkg/sql/parser/normalize.go#L345)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

I've added some more detail here. I think it needs a comment because previously we failed the entire normalization instead of just not normalizing. Clarifying why we do it this way now.
</blockquote></details>

Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14782#-:-KhWHYJiaMocnY2nupR2:bnfp4nl)*

**Pull request merged**
