### PR TITLE
tracing: rework local Batch logic+ some bug fixes

### LINKED ISSUE #17175: tracing: tags should be remembered even if we're not recording
In order to provide the `GetSpanTag` functionality, we need to set tags in all cases, not just if we are recording. `GetSpanTag` is used to avoid creating a `Batch` span if the gRPC interceptor already created one for us.

### PR DESCRIPTION
**Pull request by RaduBerinde**
### tracing: env vars for default value for lightstep and zipkin

Adding env vars to allow use of Lightstep or Zipkin with `make test` without
modifying code.

### tracing: don't combine CollectedSpans twice

As of #12142, we accidentally append CollectedSpans twice when combining BatchResponses. This leads to duplicate spans with snowball tracing.

### tracing: set StartSpan tags after setting up the spa

We were setting the StartSpan tags too early: the span wasn't yet set up so the tags weren't being recorded.

### tracing: rework local Batch logic

To determine if a Batch is local or comes from gRPC, we check for a special tag set by the gRPC interceptor in the current span. This is not currently working in all cases - if we are not recording, we don't actually remember the tag.

Fortunately, we have a more reliable mechanism (which I wasn't aware of before) to determine if a batch is local (`IsLocalRequest`). This change switches the logic to use `IsLocalRequest` and removes `tracing.GetSpanTag`.

A remaining issue is that `TestTrace` was passing even though snowball tracing was broken. This is because we see the gRPC client-side Batch span and that's good enough as far as the test is concerned. This problem will go away when we remove the gRPC client-side span (requires an upstream change to the interceptors).

Fixes #17175.

### CODE REVIEW

**Comment by tschottdorf** [comment]
:lgtm:, thanks!

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17176#-:-Kpl_tZYA_Rnpl1PC-vI:bpqxd5f)*

**Comment by RaduBerinde** [comment]
So this fails TestTrace tests with duplicate spans. Something very weird is going on here: without this check working properly, we never set the recording in `CollectedSpans`. And yet, snowball tracing was somehow working. Now that the check is fixed, we get a duplicate remote span.

I also noticed we have a more reliable way of determining if the batch is local (`grpcutil.IsLocalRequestContext`) so once I figure out the problem above I will switch to that.

**Comment by RaduBerinde** [comment]
I have reworked this change. See the updated description.

**Comment by andreimatei** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 1 of 2 files at r3, 1 of 2 files at r5.
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/roachpb/batch.go, line 254 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17176#-Kpp5ZFcstu8N4UNaHuo:-Kpp5ZFcstu8N4UNaHup:b-hxdjss) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d8143913556b7a43656f387c7fb996fa0812323/pkg/roachpb/batch.go#L254)):*
> ```Go
> 	}
> 	br.Txn.Update(otherBatch.Txn)
> 	br.CollectedSpans = append(br.CollectedSpans, otherBatch.CollectedSpans...)
> ```

curious - where's the duplicate?

---

*[pkg/util/tracing/tracer.go, line 282 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17176#-Kpp61YJomuygP4KnnVH:-Kpp61YJomuygP4KnnVI:bpm4k92) ([raw file](https://github.com/cockroachdb/cockroach/blob/996671a2e4cc6bf29778a64c89a2249320f8567f/pkg/util/tracing/tracer.go#L282)):*
> ```Go
> 	}
> 
> 	// Copy baggage items to tags so they show up in the shadow tracer UI,
> ```

Did you remove the `if netTrace || shadowTr != nil {` for any particular reason? Not that I know of any particular reason why it was there in the first place :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17176#-:-Kpp7Qgy3gBCiUwsWJG9:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/roachpb/batch.go, line 254 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17176#-Kpp5ZFcstu8N4UNaHuo:-Kpp8VSM4Qi0H4tnL3cP:beid65i) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d8143913556b7a43656f387c7fb996fa0812323/pkg/roachpb/batch.go#L254)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

curious - where's the duplicate?
</blockquote></details>

Inside `br.BatchResponse_Header.combine` (called above)

---

*[pkg/util/tracing/tracer.go, line 282 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17176#-Kpp61YJomuygP4KnnVH:-Kpp84novQML93Gr0DtJ:btlz6j8) ([raw file](https://github.com/cockroachdb/cockroach/blob/996671a2e4cc6bf29778a64c89a2249320f8567f/pkg/util/tracing/tracer.go#L282)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Did you remove the `if netTrace || shadowTr != nil {` for any particular reason? Not that I know of any particular reason why it was there in the first place :)
</blockquote></details>

Yeah, so they still show up during recording. Otherwise the recording differs depending on whether lightstep/nettrace was enabled.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17176)*

**Pull request merged**
