### PR TITLE
sql: added PopFirst functionality to RowContainer

### PR DESCRIPTION
**Pull request by irfansharif**
We now additionally maintain a deleted rows count, indicating the number
of rows deleted from the fron. Whenever this reaches the number of
rows per chunk we delete the first chunk and reset count.

supplementary to #10534, part of #10618.

cc @RaduBerinde

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10623)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[pkg/sql/row_container.go, line 59 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10623#-KWFhh9HBh4LCfHvuVGV:-KWFhh9HBh4LCfHvuVGW:b-dewgm8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d62bd7a2d51a89074c1708ceebf841fe08422be/pkg/sql/row_container.go#L59)):*
> ```Go
> 
> 	// deletedRows is the number of rows that have been deleted from the front
> 	// of container. When this number reaches rowsPerChunk we delete that chunk
> ```

of the container.

---

*[pkg/sql/row_container.go, line 60 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10623#-KWFhfmWd4dC_DOfwP_B:-KWFhfmWd4dC_DOfwP_C:b-7k26c6) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d62bd7a2d51a89074c1708ceebf841fe08422be/pkg/sql/row_container.go#L60)):*
> ```Go
> 	// deletedRows is the number of rows that have been deleted from the front
> 	// of container. When this number reaches rowsPerChunk we delete that chunk
> 	// and rest this back to zero.
> ```

reset

---

*[pkg/sql/row_container.go, line 232 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10623#-KWFicHrT9OuCLcS-WJI:-KWFicHrT9OuCLcS-WJJ:b8643vs) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d62bd7a2d51a89074c1708ceebf841fe08422be/pkg/sql/row_container.go#L232)):*
> ```Go
> 
> // Pop 'deletes' the the first rows added to the RowContainer.
> func (c *RowContainer) Pop() {
> ```

Use `PopFirst()`, there are other `Pop()`s which pop from the back (e.g. in heap interface)

---

*[pkg/sql/row_container.go, line 233 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10623#-KWFisLzHLyxDrjgOj9C:-KWFisLzHLyxDrjgOj9D:b-r7v144) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d62bd7a2d51a89074c1708ceebf841fe08422be/pkg/sql/row_container.go#L233)):*
> ```Go
> // Pop 'deletes' the the first rows added to the RowContainer.
> func (c *RowContainer) Pop() {
> 	c.deletedRows++
> ```

check and panic if there are no rows

---

*[pkg/sql/row_container.go, line 234 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10623#-KWFhz01XO1_2kaygYXq:-KWFhz01XO1_2kaygYXr:b3t8xgr) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d62bd7a2d51a89074c1708ceebf841fe08422be/pkg/sql/row_container.go#L234)):*
> ```Go
> func (c *RowContainer) Pop() {
> 	c.deletedRows++
> 	if c.deletedRows < c.rowsPerChunk {
> ```

aren't we supposed to `numRows--` ? Please add a check for `Len()` in the test

---

*[pkg/sql/row_container.go, line 235 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10623#-KWFkM-BWmNJ1-Ul4jD0:-KWFkM-BWmNJ1-Ul4jD1:b5tr23h) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d62bd7a2d51a89074c1708ceebf841fe08422be/pkg/sql/row_container.go#L235)):*
> ```Go
> 	c.deletedRows++
> 	if c.deletedRows < c.rowsPerChunk {
> 		return
> ```

this return is odd when this is the "common" path and we only have two lines, i'd reverse the condition

---

*[pkg/sql/row_container_test.go, line 51 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10623#-KWFjB-_VG0bPE_uxAPU:-KWFjB-_VG0bPE_uxAPV:b99lhuh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d62bd7a2d51a89074c1708ceebf841fe08422be/pkg/sql/row_container_test.go#L51)):*
> ```Go
> 			}
> 
> 			rc.Pop()
> ```

this probably doesn't test the code that actually removes the chunk. Maybe run more cases , e.g. `for _, numPops := range []int{0, 1, 2, numRows/3, numRows/2}`

---

*[pkg/sql/row_container_test.go, line 54 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10623#-KWFj64KpiNFAyQ6EopI:-KWFj64KpiNFAyQ6EopJ:bb7p4x8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d62bd7a2d51a89074c1708ceebf841fe08422be/pkg/sql/row_container_test.go#L54)):*
> ```Go
> 			rc.Pop()
> 
> 			// Given we just deleted two rows, we have numRows - 2 rows to
> ```

that

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10623)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[pkg/sql/row_container.go, line 231 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10623#-KWFlepUZoUwcttwCYXo:-KWFlepUZoUwcttwCYXp:b-rnrngj) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d62bd7a2d51a89074c1708ceebf841fe08422be/pkg/sql/row_container.go#L231)):*
> ```Go
> }
> 
> // Pop 'deletes' the the first rows added to the RowContainer.
> ```

perhaps "discards" would allow you to avoid air quotes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10623)*

**Comment by irfansharif** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[pkg/sql/row_container.go, line 59 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10623#-KWFhh9HBh4LCfHvuVGV:-KWFlWTWRldHrwsUzIlN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d62bd7a2d51a89074c1708ceebf841fe08422be/pkg/sql/row_container.go#L59)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> of the container.
</details>
Done.

---

*[pkg/sql/row_container.go, line 60 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10623#-KWFhfmWd4dC_DOfwP_B:-KWFlWjwDfQS_McTz6DV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d62bd7a2d51a89074c1708ceebf841fe08422be/pkg/sql/row_container.go#L60)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> reset
</details>
Done.

---

*[pkg/sql/row_container.go, line 231 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10623#-KWFlepUZoUwcttwCYXo:-KWFmkv4M8m__Kk3FEtB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d62bd7a2d51a89074c1708ceebf841fe08422be/pkg/sql/row_container.go#L231)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> perhaps "discards" would allow you to avoid air quotes.
</details>
Done.

---

*[pkg/sql/row_container.go, line 232 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10623#-KWFicHrT9OuCLcS-WJI:-KWFla_gNbF4yntRBQTQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d62bd7a2d51a89074c1708ceebf841fe08422be/pkg/sql/row_container.go#L232)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Use `PopFirst()`, there are other `Pop()`s which pop from the back (e.g. in heap interface)
</details>
Done.

---

*[pkg/sql/row_container.go, line 233 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10623#-KWFisLzHLyxDrjgOj9C:-KWFm2hE1NxEIuAAwc0q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d62bd7a2d51a89074c1708ceebf841fe08422be/pkg/sql/row_container.go#L233)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> check and panic if there are no rows
</details>
Done.

---

*[pkg/sql/row_container.go, line 234 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10623#-KWFhz01XO1_2kaygYXq:-KWFmdxzZhmhaCY_c5Hc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d62bd7a2d51a89074c1708ceebf841fe08422be/pkg/sql/row_container.go#L234)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> aren't we supposed to `numRows--` ? Please add a check for `Len()` in the test
</details>
Done.

---

*[pkg/sql/row_container.go, line 235 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10623#-KWFkM-BWmNJ1-Ul4jD0:-KWFm3DE4yEFcMqRDBYF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d62bd7a2d51a89074c1708ceebf841fe08422be/pkg/sql/row_container.go#L235)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> this return is odd when this is the "common" path and we only have two lines, i'd reverse the condition
</details>
Done.

---

*[pkg/sql/row_container_test.go, line 51 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10623#-KWFjB-_VG0bPE_uxAPU:-KWFpF7zhEADNsK9Bh95:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d62bd7a2d51a89074c1708ceebf841fe08422be/pkg/sql/row_container_test.go#L51)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> this probably doesn't test the code that actually removes the chunk. Maybe run more cases , e.g. `for _, numPops := range []int{0, 1, 2, numRows/3, numRows/2}`
</details>
Done.

---

*[pkg/sql/row_container_test.go, line 54 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10623#-KWFj64KpiNFAyQ6EopI:-KWFm6pyVuBNNjpwDAqi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d62bd7a2d51a89074c1708ceebf841fe08422be/pkg/sql/row_container_test.go#L54)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> that
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10623)*

**Comment by tamird** [comment]
For posterity, from slack discussion:

PR description currently includes "Fixes #10618" which will cause merging this to close #10618 - that's probably not what you want.

Also, you should keep in mind that preemptive API changes like this (i.e. adding an API in one PR with the intention of using it in the next) is generally a bad idea because it limits the reviewer's ability to help you avoid bad API designs.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10623#-:-KWFwAiYBbJBNzw9tCNA:b-f6z960)*

**Comment by irfansharif** [comment]
ack, TFTRs!

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10623#-:-KWFwz9hIM8Xhi79-100:b-qrofxm)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10623#-:-KWG77S2FxkESfKvYuIG:bnfp4nl)*

**Pull request merged**
