### PR TITLE
cli: fix flakiness in TestConnRecover

### LINKED ISSUE #33004: cli: TestConnRecover is flaky
Fails in 1 or 2 runs under stress. Fails in 50 runs with `STRESSFLAGS="-p 1"`.

```
> make stress PKG='./pkg/cli' TESTS=TestConnRecover

sql_util_test.go:71: conn.Exec(): expected bad conn, got read tcp 127.0.0.1:61059->127.0.0.1:61057: read: connection reset by peer
```

### PR DESCRIPTION
**Pull request by knz**
Fixes #33004.

The test was expecting that a server restart be immediately detected
by the SQL driver. In practice, another error (eg TCP reset) may be
encountered first. The test must account for that.

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33455)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by knz** [comment]
TFYR

bors r+

**Pull request merged**
