### PR TITLE
sql: add some more debug info to TestRaceWithbackfill

### PR DESCRIPTION
**Pull request by vivekmenezes**
#10021

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10137)

### CODE REVIEW

**Comment by tamird** [comment]
How come this needs to merge? In other words, are you able to reproduce the mentioned issue locally or in GCE?

**Comment by vivekmenezes** [comment]
I'm unable to reproduce this issue. It has happened once, and I'm concerned with it being a rare error being ignored bug in either INSERT/UPDATE/DELETE. This will hopefully narrow it down to one of the three.

**Comment by tamird** [comment]
In GCE, this reproduces after about 4 minutes:

```
$ make stress PKG=./pkg/sql TESTS=TestRaceWithBackfill STRESSFLAGS='-stderr -maxfails 1 -p 100'
go list -tags '' -f \
'go test -v  -tags '\'''\'' -ldflags '\'''\'' -i -c {{.ImportPath}} -o {{.Dir}}/stress.test && (cd {{.Dir}} && if [ -f stress.test ]; then stress -stderr -maxfails 1 -p 100 ./stress.test -test.run TestRaceWithBackfill -test.timeout 2m ; fi)' ./pkg/sql | \
/bin/bash
github.com/cockroachdb/cockroach/pkg/sql
github.com/cockroachdb/cockroach/pkg/sql_test
testmain
0 runs so far, 0 failures, over 5s
0 runs so far, 0 failures, over 10s
0 runs so far, 0 failures, over 15s
0 runs so far, 0 failures, over 20s
84 runs so far, 0 failures, over 25s
100 runs so far, 0 failures, over 30s
100 runs so far, 0 failures, over 35s
186 runs so far, 0 failures, over 40s
200 runs so far, 0 failures, over 45s
201 runs so far, 0 failures, over 50s
279 runs so far, 0 failures, over 55s
299 runs so far, 0 failures, over 1m0s
301 runs so far, 0 failures, over 1m5s
378 runs so far, 0 failures, over 1m10s
398 runs so far, 0 failures, over 1m15s
400 runs so far, 0 failures, over 1m20s
476 runs so far, 0 failures, over 1m25s
497 runs so far, 0 failures, over 1m30s
499 runs so far, 0 failures, over 1m35s
580 runs so far, 0 failures, over 1m40s
596 runs so far, 0 failures, over 1m45s
601 runs so far, 0 failures, over 1m50s
681 runs so far, 0 failures, over 1m55s
695 runs so far, 0 failures, over 2m0s
707 runs so far, 0 failures, over 2m5s
783 runs so far, 0 failures, over 2m10s
795 runs so far, 0 failures, over 2m15s
817 runs so far, 0 failures, over 2m20s
884 runs so far, 0 failures, over 2m25s
895 runs so far, 0 failures, over 2m30s
917 runs so far, 0 failures, over 2m35s
983 runs so far, 0 failures, over 2m40s
995 runs so far, 0 failures, over 2m45s
1019 runs so far, 0 failures, over 2m50s
1084 runs so far, 0 failures, over 2m55s
1097 runs so far, 0 failures, over 3m0s
1131 runs so far, 0 failures, over 3m5s
1185 runs so far, 0 failures, over 3m10s
1201 runs so far, 0 failures, over 3m15s
1247 runs so far, 0 failures, over 3m20s
1287 runs so far, 0 failures, over 3m25s
1304 runs so far, 0 failures, over 3m30s
1348 runs so far, 0 failures, over 3m35s
1389 runs so far, 0 failures, over 3m40s
1409 runs so far, 0 failures, over 3m45s
1459 runs so far, 0 failures, over 3m50s
1489 runs so far, 0 failures, over 3m55s
1516 runs so far, 0 failures, over 4m0s
1570 runs so far, 0 failures, over 4m5s
1589 runs so far, 0 failures, over 4m10s

I161021 20:43:19.947131 1 rand.go:76  Random seed: -8603381568575260631
I161021 20:43:19.979694 8 storage/engine/rocksdb.go:349  opening in memory rocksdb instance
I161021 20:43:19.984348 8 gossip/gossip.go:234  [n?] initial resolvers: []
W161021 20:43:19.984385 8 gossip/gossip.go:1045  [n?] no resolvers found; use --join to specify a connected node
W161021 20:43:19.986535 8 server/status/runtime.go:116  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I161021 20:43:19.987483 8 server/node.go:417  [n?] store [n0,s0] not bootstrapped
I161021 20:43:19.991296 87 storage/replica_proposal.go:278  [s1,r1/1:/M{in-ax},r1/1:/M{in-ax}] new range lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 410300h43m28.98980783s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0s [physicalTime=2016-10-21 20:43:19.991194549 +0000 UTC]
I161021 20:43:20.001754 8 util/stop/stopper.go:353  stop has been called, stopping or quiescing all running tasks
I161021 20:43:20.029087 8 server/node.go:349  [n?] **** cluster {e5d7f45b-df8f-49aa-b8f6-e247e1238c83} has been created
I161021 20:43:20.029139 8 server/node.go:350  [n?] **** add additional nodes by specifying --join=127.0.0.1:36374
I161021 20:43:20.030178 8 gossip/gossip.go:268  [n?] NodeID set to 1
I161021 20:43:20.032092 10 storage/split_queue.go:103  [split,n?,s1,r1/1:/M{in-ax}] splitting at keys [/Table/11/0 /Table/12/0 /Table/13/0 /Table/14/0]
I161021 20:43:20.035191 8 storage/store.go:1079  [n?] [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
I161021 20:43:20.035247 8 server/node.go:430  [n?] initialized store [n1,s1]: {Capacity:536870912 Available:536870912 RangeCount:0}
I161021 20:43:20.035290 8 server/node.go:318  [n?] node ID 1 initialized
I161021 20:43:20.035431 8 gossip/gossip.go:282  [n?] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:36374" > attrs:<> locality:<>
I161021 20:43:20.035527 8 storage/stores.go:292  [n?] read 0 node addresses from persistent storage
I161021 20:43:20.035648 8 server/node.go:560  [n?] connecting to gossip network to verify cluster ID...
I161021 20:43:20.035692 8 server/node.go:581  [n?] node connected via gossip and verified as part of cluster {"e5d7f45b-df8f-49aa-b8f6-e247e1238c83"}
I161021 20:43:20.035766 8 server/node.go:368  [n?] node=1: started with [[]=] engine(s) and attributes []
I161021 20:43:20.035813 8 server/server.go:553  [n1] starting https server at 127.0.0.1:35559
I161021 20:43:20.035838 8 server/server.go:554  [n1] starting grpc/postgres server at 127.0.0.1:36374
I161021 20:43:20.035866 8 server/server.go:555  [n1] advertising CockroachDB node at 127.0.0.1:36374
I161021 20:43:20.123603 158 sql/event_log.go:94  [n1] Event: "node_join", target: 1, info: {Descriptor:{NodeID:1 Address:{NetworkField:tcp AddressField:127.0.0.1:36374} Attrs: Locality:} ClusterID:{UUID:e5d7f45b-df8f-49aa-b8f6-e247e1238c83} StartedAt:1477082600035704446}
I161021 20:43:20.243476 10 storage/replica_command.go:2354  [split,n1,s1,r1/1:/M{in-ax},r1/1:/M{in-ax}] initiating a split of this range at key /Table/11 [r2]
I161021 20:43:20.266556 10 storage/replica_command.go:2354  [split,n1,s1,r1/1:/{Min-Table/11},r2/1:/{Table/11-Max}] initiating a split of this range at key /Table/12 [r3]
I161021 20:43:20.370035 10 storage/replica_command.go:2354  [split,n1,s1,r1/1:/{Min-Table/11},r3/1:/{Table/12-Max}] initiating a split of this range at key /Table/13 [r4]
I161021 20:43:20.541866 10 storage/replica_command.go:2354  [split,n1,s1,r1/1:/{Min-Table/11},r4/1:/{Table/13-Max}] initiating a split of this range at key /Table/14 [r5]
I161021 20:43:20.618832 355 sql/event_log.go:94  [n1,client=127.0.0.1:45012] Event: "create_database", target: 50, info: {DatabaseName:t Statement:CREATE DATABASE t User:root}
I161021 20:43:20.659730 355 sql/event_log.go:94  [n1,client=127.0.0.1:45012] Event: "create_table", target: 51, info: {TableName:t.test Statement:CREATE TABLE t.test (k INT PRIMARY KEY, v INT, pi DECIMAL DEFAULT (DECIMAL '3.14')) User:root}
I161021 20:43:20.665403 355 sql/event_log.go:94  [n1,client=127.0.0.1:45012] Event: "create_index", target: 51, info: {TableName:test IndexName:vidx Statement:CREATE UNIQUE INDEX vidx ON t.test (v) User:root MutationID:1}
I161021 20:43:20.672330 10 storage/split_queue.go:103  [split,n1,s1,r5/1:/{Table/14-Max}] splitting at keys [/Table/50/0]
I161021 20:43:20.674594 10 storage/replica_command.go:2354  [split,n1,s1,r5/1:/{Table/14-Max},r5/1:/{Table/14-Max}] initiating a split of this range at key /Table/50 [r6]
I161021 20:43:20.728918 10 storage/split_queue.go:103  [split,n1,s1,r6/1:/{Table/50-Max}] splitting at keys [/Table/51/0]
I161021 20:43:20.729421 10 storage/replica_command.go:2354  [split,n1,s1,r6/1:/{Table/50-Max},r6/1:/{Table/50-Max}] initiating a split of this range at key /Table/51 [r7]
I161021 20:43:20.748372 355 sql/event_log.go:94  Event: "finish_schema_change", target: 51, info: {MutationID:1}
I161021 20:43:21.468619 355 sql/mon/mem_usage.go:86  [n1,client=127.0.0.1:45012] memory usage increases to 16 KiB (+48)
I161021 20:43:21.475537 355 sql/mon/mem_usage.go:86  [n1,client=127.0.0.1:45012] memory usage increases to 32 KiB (+48)
I161021 20:43:21.476316 355 sql/mon/mem_usage.go:86  [n1,client=127.0.0.1:45012] memory usage increases to 64 KiB (+48)
I161021 20:43:21.477679 355 sql/mon/mem_usage.go:86  [n1,client=127.0.0.1:45012] memory usage increases to 128 KiB (+48)
W161021 20:43:23.712666 167 storage/replica.go:513  [n1,s1,r7/1:/{Table/51-Max}] raftMu: mutex held by github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady for 752.463047ms (>500ms):
goroutine 167 [running]:
runtime/debug.Stack(0x1d3fe00, 0x1d3fe40, 0x47)
	/home/tamird/go/src/runtime/debug/stack.go:24 +0x79
github.com/cockroachdb/cockroach/pkg/util/syncutil.ThresholdLogger.func1(0x2cd9acc7)
	/home/tamird/src/github.com/cockroachdb/cockroach/pkg/util/syncutil/timedmutex.go:63 +0xe1
github.com/cockroachdb/cockroach/pkg/util/syncutil.(*TimedMutex).Unlock(0xc4208198e8)
	/home/tamird/src/github.com/cockroachdb/cockroach/pkg/util/syncutil/timedmutex.go:90 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady(0xc420819880, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/tamird/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1817 +0xee
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processReady(0xc42063c000, 0x7)
	/home/tamird/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2848 +0x13b
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42063e000, 0xc4200fc000)
	/home/tamird/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:223 +0x257
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/home/tamird/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:180 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4200fc000, 0xc420604c20)
	/home/tamird/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:191 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/home/tamird/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:192 +0x66
I161021 20:43:23.960251 355 sql/event_log.go:94  [n1,client=127.0.0.1:45012] Event: "alter_table", target: 51, info: {TableName:test Statement:ALTER TABLE t.test ADD COLUMN x DECIMAL DEFAULT (DECIMAL '1.4') User:root MutationID:2}
I161021 20:43:23.985946 355 sql/lease.go:267  publish (count leases): descID=51 name=test version=5 count=1
I161021 20:43:25.503498 355 sql/event_log.go:94  Event: "finish_schema_change", target: 51, info: {MutationID:2}
I161021 20:43:25.514503 355 sql/lease.go:267  publish (count leases): descID=51 name=test version=6 count=1
I161021 20:43:25.751069 8 util/stop/stopper.go:353  stop has been called, stopping or quiescing all running tasks
I161021 20:43:25.751916 248 http2_server.go:276  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:36374->127.0.0.1:45000: use of closed network connection
--- FAIL: TestRaceWithBackfill (5.81s)
	schema_changer_test.go:457: schema change ALTER TABLE t.test ADD COLUMN x DECIMAL DEFAULT (DECIMAL '1.4') took 1.595294781s
	schema_changer_test.go:524: expected 16044 key value pairs, but got 16043
FAIL


ERROR: exit status 1

1595 runs completed, 1 failures, over 4m11s
FAIL
Makefile:128: recipe for target 'stress' failed
make: *** [stress] Error 1
```

**Comment by vivekmenezes** [comment]
How do I go about running it on GCE?

**Comment by vivekmenezes** [comment]
I remember Tobi sent out some instructions for that.

**Comment by tamird** [comment]
`scripts/gce_worker.sh create`
then
`scripts/gce_worker.sh ssh`
the worker will automatically shut down after 10 minutes of no user
sessions. to bring it back in the future, use
`scripts/gce_worker.sh start`

**Comment by vivekmenezes** [comment]
Good to know the `start` command. Thanks!

**Pull request closed without merging**
