### PR TITLE
execstats: calculate maximum temp disk usage

### LINKED ISSUE #56606: execstats: calculate maximum flow temporary disk usage
This issue tracks adding the maximum flow temporary disk usage calculation to the TraceAnalyzer. This should follow the same design as #54340, by asking for the high watermark disk usage from a parent disk monitor.

### PR DESCRIPTION
**Pull request by asubiotto**
Depends on #60787 

Closes #56606

Release justification: low risk high benefit change to existing functionality.

Release note: None (internal change to be displayed on DB Console)

Putting this out for an initial review (last two commits only). I'm about to board a flight so will polish later.

### CODE REVIEW

**Comment by asubiotto** [comment]
Still need to finish writing `execstats` test and add the field to `ExecStats` in `component_stats`. @yuzefovich was hoping I could get your opinion on the commit to add a disk monitor to the flow ctx, that commit is pretty much final.

**Review by yuzefovich — COMMENTED** [review]
Third commit LGTM, I just have one suggestion.

> Reviewed 35 of 35 files at r3, 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60791#-:-MTwM-LB1BfyZd6LrptV:bd4994y)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @asubiotto)

___
*[pkg/sql/distsql/server.go, line 378 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/60791#-MTwLAny2b69wZyF0dWY:-MTwLAny2b69wZyF0dWZ:b-abj44j) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2bb7d8b16110335a77030969ba92415e8462c4d/pkg/sql/distsql/server.go#L378)):*
> ```Go
> // NewFlowContext creates a new FlowCtx that can be used during execution of
> // a flow.
> func (ds *ServerImpl) NewFlowContext(
> ```

nit: I see that this method is only used in the same file, so we should unexport it so that we could guarantee that the disk monitor is always closed (because `Cleanup()` must be called after `setupFlow` call which is the only user of this method).

**Comment by asubiotto** [comment]
Changed `NewFlowContext` to be private. This PR is now no longer a WIP so can be reviewed in its entirety (minus the first two commits).

**Comment by asubiotto** [comment]
cc @yuzefovich do you know why we would get non-deterministic output for the expected max memory usage of a vectorized flow when setting `ForceDiskSpill`?:
```
    --- FAIL: TestTraceAnalyzer/ColExec (0.00s)
        traceanalyzer_test.go:180:
            	Error Trace:	traceanalyzer_test.go:180
            	Error:      	Not equal:
            	            	expected: 133120
            	            	actual  : 61440 **THIS FIELD CHANGES ON EACH TEST RUN**
            	Test:       	TestTraceAnalyzer/ColExec
    traceanalyzer_test.go:193: -- test log scope end --
```

Does it have to do with metamorphic builds? Change the check to be greater than 0 in the meantime.

**Comment by asubiotto** [comment]
This PR has been rebased and is now RFAL btw.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 10 of 21 files at r5, 16 of 16 files at r8, 9 of 9 files at r9, 7 of 7 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60791#-:-MUGwbso8CeqQRjrpLPH:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru and @asubiotto)

___
*[pkg/sql/execstats/traceanalyzer_test.go, line 177 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/60791#-MUGvlJu0fTiAWm-ugJc:-MUGvlJvDujRidfp5uYM:b5ylo0b) ([raw file](https://github.com/cockroachdb/cockroach/blob/daa10befc5d3dcc53aec375d28651ac80ab3f4ee/pkg/sql/execstats/traceanalyzer_test.go#L177)):*
> do you know why we would get non-deterministic output for the expected max memory usage of a vectorized flow when setting `ForceDiskSpill`?

Yeah, I think it has to do with `crdb_test` build tag which forces the randomization of `coldata.BatchSize()`. We have 30 rows in the table, and we're performing an external sort. Memory usage of that will vary depending on how large batches are.

I think the current way is reasonable, we simply want to make sure that the stat is set, and it might be a bit annoying to try to get an expected range for that value because whenever we change something about the memory accounting in the external sort, we might need to readjust the range here.
___
*[pkg/sql/flowinfra/flow.go, line 445 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/60791#-MUGuPTt8MLE2PbooHtb:-MUGuPTt8MLE2PbooHtc:bdg8v1v) ([raw file](https://github.com/cockroachdb/cockroach/blob/af28e1ce054dc15bf6df10b475ff34c9c392d357/pkg/sql/flowinfra/flow.go#L445)):*
> ```Go
> 	}
> 
> 	// This closes the disk monitor opened in NewFlowCtx.
> ```

nit: `s/NewFlowCtx/newFlowCtx/g`.
___
*[pkg/ui/src/util/appStats.ts, line 125 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/60791#-MUGwVU1AIvJPIma3xJ0:-MUGwVU1AIvJPIma3xJ1:b-j4i9n5) ([raw file](https://github.com/cockroachdb/cockroach/blob/c138017ec40db5cad2aa6febea4f39a0a8f5ca90/pkg/ui/src/util/appStats.ts#L125)):*
> ```XML
>       countB,
>     ),
>     max_disk_usage: addMaybeUnsetNumericStat(
> ```

nit: not sure if it matters for the UI, but it might be nice to put disk usage next to mem usage.

**Review by asubiotto — COMMENTED** [review]
TFTR

bors r=yuzefovich

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60791#-:-MUJCyp5DePcdpvqdpj7:bsvne40)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @asubiotto, and @yuzefovich)

___
*[pkg/ui/src/util/appStats.ts, line 125 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/60791#-MUGwVU1AIvJPIma3xJ0:-MUJBnQF916XxA62y7GY:b-jpbe03) ([raw file](https://github.com/cockroachdb/cockroach/blob/c138017ec40db5cad2aa6febea4f39a0a8f5ca90/pkg/ui/src/util/appStats.ts#L125)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: not sure if it matters for the UI, but it might be nice to put disk usage next to mem usage.
</blockquote></details>

This doesn't matter to the UI (display is done elsewhere in the order designed by Anne). I prefer to keep this order since it's the same as the protobuf definition.

**Comment by asubiotto** [comment]
bors r=yuzefovich

**Comment by asubiotto** [comment]
release justification missing

bors r=yuzefovich

**Comment by asubiotto** [comment]
Unrelated flakes.

bors r=yuzefovich

**Comment by otan** [comment]
good samaritan retries

bors r=yuzefovich

**Pull request merged**
