### PR TITLE
storage: remove `(*Store).context`

### PR DESCRIPTION
**Pull request by tamird**
It was already replaced with `(*Store).logContext`.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9137)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/store.go, line 1016 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9137#-KR-dXOAgPar5uVjEUFi:-KR-dXOBaUViuWwQ5Iie:b-44x7k6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b443676ecf24662e65e26eaf10356d9abb2b2a82/storage/store.go#L1016)):*
> ```Go
> // to gossip accordingly.
> func (s *Store) startGossip() {
> 	gossipFns := map[func() error]string{
> ```

Might want to split this cleanup in a separate config

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9137#-:-KR-dNdLckWNELd9L__L:bnfp4nl)*

**Comment by RaduBerinde** [comment]
*[storage/store.go, line 1016 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9137#-KR-dXOAgPar5uVjEUFi:-KR-diuKeBLHIpybZK4X:b-mb0s0r) ([raw file](https://github.com/cockroachdb/cockroach/blob/b443676ecf24662e65e26eaf10356d9abb2b2a82/storage/store.go#L1016)):*
> config
Lol, *commit

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9137)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[storage/store.go, line 1025 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9137#-KR-luY7ApWk0llyu2M7:-KR-luY7ApWk0llyu2M8:b-lfv3j8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b443676ecf24662e65e26eaf10356d9abb2b2a82/storage/store.go#L1025)):*
> ```Go
> 	s.initComplete.Add(len(gossipFns))
> 	for fn, description := range gossipFns {
> 		fn, description := fn, description // per-iteration copy
> ```

Is this line really necessary?

Anyway, seems like this doesn't build, maybe easier to just use a `[]struct` instead of a map

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9137)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[storage/store.go, line 1025 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9137#-KR-luY7ApWk0llyu2M7:-KR-neGYqZWfNgL9nB7o:bg152u2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b443676ecf24662e65e26eaf10356d9abb2b2a82/storage/store.go#L1025)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Is this line really necessary?
> 
> Anyway, seems like this doesn't build, maybe easier to just use a `[]struct` instead of a map
</details>
Ah I see why, for some reason I thought that in `for a, b := range` the `a, b` variables have the lifetime of an iteration not the entire loop

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9137)*

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/store.go, line 1016 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/9137#-KR-dXOAgPar5uVjEUFi:-KR-wB2MfDZ17a0bHbqJ:bwsyy1o) ([raw file](https://github.com/cockroachdb/cockroach/blob/b443676ecf24662e65e26eaf10356d9abb2b2a82/storage/store.go#L1016)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> > config
> Lol, *commit
</details>
Pulled it out, will send a separate PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9137)*

**Pull request merged**
