### PR TITLE
sql,upgrade: pre-create an application tenant

### PR DESCRIPTION
**Pull request by knz**
Needed for #84608.
Epic: CRDB-14537

This commit introduces a predefined "app" tenant. This tenant is identified by name: its ID is allocated dynamically to be different from any pre-existing tenant.

Some of the tests here are found to not-work with a predefined app tenant. This will be handled separately in #91122.

### CODE REVIEW

**Comment by knz** [comment]
I wonder if it wouldn't make sense to make the app tenant ID for new clusters a metamorphic variable.

**Review by ajwerner — COMMENTED** [review]
This seems reasonable

**Comment by knz** [comment]
thank you

**Comment by knz** [comment]
I think this is good for (a first round of) review now.

**Review by postamar — COMMENTED** [review]
This seems close to me. I don't feel I have the required expertise when it comes to splits so perhaps someone else should check to make sure. 

Perhaps also add an assertion in the tenant upgrade step to check that the 'app' tenant has been created?

> Reviewed 5 of 6 files at r1, 26 of 27 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91058#-:-NGSkmEvBOdxsQGs7o3r:bla7h3s)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif, @knz, @renatolabs, @rhu713, and @smg260)

___
*[`pkg/server/testing_knobs.go` line 50 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91058#-NGSkEcD8eijuYQkxdoT:-NGSkEcD8eijuYQkxdoU:b-18jen6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cd2e97b08bfd71fe098b0036b31eed5a1d9efe7/pkg/server/testing_knobs.go#L50)):*
> ```Go
> 	// DisableAppTenantAutoCreation disables the auto-creation of an app tenant
> 	// in fresh clusters.
> 	DisableAppTenantAutoCreation bool
> ```

Shouldn't this be made incompatible with `BinaryVersionOverride` somehow? Otherwise you can set this to `true` and still have the tenant creation upgrade step run.
___
*[`pkg/sql/catalog/bootstrap/metadata.go` line 70 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91058#-NGSdQb2-z_2vmN7HfpO:-NGSdQb2-z_2vmN7HfpP:b-nftadn) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cd2e97b08bfd71fe098b0036b31eed5a1d9efe7/pkg/sql/catalog/bootstrap/metadata.go#L70)):*
> ```Go
> 	predefineSecondaryTenant bool,
> ) MetadataSchema {
> 	ms := MakeMetadataSchema(keys.SystemSQLCodec, defaultZoneConfig, defaultSystemZoneConfig)
> ```

nit: at this point, should `MakeInitialKeyspace` (and perhaps also `MakeMetadataSchema`) adopt the `...Option` pattern instead? 

https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/181371303/Go+Golang+coding+guidelines#Functional-Options
___
*[`pkg/sql/catalog/bootstrap/metadata.go` line 641 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91058#-NGSf5Go0iJdK562zN4Y:-NGSf5Go0iJdK562zN4Z:bg95713) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cd2e97b08bfd71fe098b0036b31eed5a1d9efe7/pkg/sql/catalog/bootstrap/metadata.go#L641)):*
> ```Go
> 
> 	// Ensure that the secondary tenant starts at a split point.
> 	// ms.otherSplits = append(ms.otherSplits, roachpb.RKey(codec2.TenantPrefix()))
> ```

Shouldn't this line be either removed or uncommented? Note that I haven't checked whether that split on the tenant prefix was added or not.
___
*[`pkg/upgrade/upgrades/tenant_table_migration.go` line 110 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91058#-NGSiwGtBTBktpY58luE:-NGSiwGtBTBktpY58luF:b-g88d7f) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cd2e97b08bfd71fe098b0036b31eed5a1d9efe7/pkg/upgrade/upgrades/tenant_table_migration.go#L110)):*
> ```Go
>      AND NOT EXISTS (SELECT 1 FROM system.tenants t WHERE t.name=$1)
>    LIMIT 1
> ) SELECT "".crdb_internal.create_tenant(newid, $1) FROM tid
> ```

Wouldn't `SELECT "".crdb_internal.create_tenant(max(id)+1, $1) FROM system.tenants HAVING max(name=$1)` be equivalent? I'm probably missing something subtle here. In any case I'm struggling to understand this query, FWIW.
___
*[`pkg/upgrade/upgrades/tenant_table_migration.go` line 121 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91058#-NGSjXUZ1C55JwO1EfVI:-NGSjXUZ1C55JwO1EfVJ:b-rx574l) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cd2e97b08bfd71fe098b0036b31eed5a1d9efe7/pkg/upgrade/upgrades/tenant_table_migration.go#L121)):*
> ```Go
> 	}
> 
> 	_, err = d.InternalExecutor.ExecEx(ctx, "add-app-entry", nil,
> ```

nit: `s,nil,nil /* txn */,`

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/91058)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif, @postamar, @renatolabs, @rhu713, and @smg260)

___
*[`pkg/upgrade/upgrades/tenant_table_migration.go` line 110 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/91058#-NGSiwGtBTBktpY58luE:-NGakOdM1Ix7DY8iXJYA:b-mss2u0) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cd2e97b08bfd71fe098b0036b31eed5a1d9efe7/pkg/upgrade/upgrades/tenant_table_migration.go#L110)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Wouldn't `SELECT "".crdb_internal.create_tenant(max(id)+1, $1) FROM system.tenants HAVING max(name=$1)` be equivalent? I'm probably missing something subtle here. In any case I'm struggling to understand this query, FWIW.
</blockquote></details>

The query as written re-uses holes generated by deletion.

In fact I do not understand your HAVING clause :)

**Comment by postamar** [comment]
> The query as written re-uses holes generated by deletion.

Ah, that's what I was missing. Is this desirable, though? Do we expect to exhaust the tenant ID space if we don't re-use them? My naive opinion is that this seems unlikely and re-using IDs is more trouble than it's worth.

> In fact I do not understand your HAVING clause :)

Well, my query is incorrect anyway, sorry for that. The `max` was a bad way to express `bool_or`. Never mind, I was feeling cleverer than I really was!

**Comment by knz** [comment]
subsumed by #98466

**Pull request closed without merging**
