### PR TITLE
rangefeed: fix sendMetadata deadlock

### LINKED ISSUE #123355: ccl/streamingccl/streamingest: TestTenantStreamingJobRetryReset failed
ccl/streamingccl/streamingest.TestTenantStreamingJobRetryReset [failed](https://tanzanite.cluster.engflow.com/invocations/default/d5f31ffa-c249-41a8-ae5e-54197f8167ce?testReportRun=9&testReportShard=5&testReportAttempt=1#targets-Ly9wa2cvY2NsL3N0cmVhbWluZ2NjbC9zdHJlYW1pbmdlc3Q6c3RyZWFtaW5nZXN0X3Rlc3Q=) on master @ [af3173a899e16af30d2ca9489d8c2c926c410121](https://github.com/cockroachdb/cockroach/commits/af3173a899e16af30d2ca9489d8c2c926c410121):

Fatal error:

```
panic: test timed out after 14m57s
running tests:
	TestTenantStreamingJobRetryReset (14m46s)

```
Stack: 

```
goroutine 361679 [running]:
testing.(*M).startAlarm.func1()
	GOROOT/src/testing/testing.go:2366 +0x385
created by time.goFunc
	GOROOT/src/time/sleep.go:177 +0x2d
```
<details><summary>Log preceding fatal error</summary>
<p>

```
* runtime/pprof.Do({0x7f3a4a8?, 0xc352800?}, {{0xc000e0b1a0?, 0x7f3a7f8?, 0xc00ce09ce0?}}, 0xc0020007c0)
* 	GOROOT/src/runtime/pprof/runtime.go:51 +0x9d
* github.com/cockroachdb/pebble.openCleanupManager.func1()
* 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/obsolete_files.go:97 +0x56
* created by github.com/cockroachdb/pebble.openCleanupManager in goroutine 14136
* 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/obsolete_files.go:96 +0x265
* 
* goroutine 14196 [select]:
* github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs.func1()
* 	github.com/cockroachdb/cockroach/pkg/util/admission/work_queue.go:500 +0x14d
* created by github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs in goroutine 14136
* 	github.com/cockroachdb/cockroach/pkg/util/admission/work_queue.go:471 +0x4f
* 
* goroutine 14140 [chan receive, 4 minutes]:
* github.com/cockroachdb/pebble.(*cleanupManager).mainLoop(0xc0086c3040)
* 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/obsolete_files.go:163 +0xe5
* github.com/cockroachdb/pebble.openCleanupManager.func1.1({0x7f3a7f8?, 0xc00cd5a510?})
* 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/obsolete_files.go:98 +0x17
* runtime/pprof.Do({0x7f3a4a8?, 0xc352800?}, {{0xc000e0b1a0?, 0xc00114ffd0?, 0x4a77bd?}}, 0xc00114ffc0)
* 	GOROOT/src/runtime/pprof/runtime.go:51 +0x9d
* github.com/cockroachdb/pebble.openCleanupManager.func1()
* 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/obsolete_files.go:97 +0x56
* created by github.com/cockroachdb/pebble.openCleanupManager in goroutine 14136
* 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/obsolete_files.go:96 +0x265
* 
* goroutine 14173 [select]:
* github.com/cockroachdb/cockroach/pkg/util/admission.initWorkQueue.func2()
* 	github.com/cockroachdb/cockroach/pkg/util/admission/work_queue.go:423 +0x85
* created by github.com/cockroachdb/cockroach/pkg/util/admission.initWorkQueue in goroutine 14136
* 	github.com/cockroachdb/cockroach/pkg/util/admission/work_queue.go:420 +0x3be
* 
* goroutine 14194 [select]:
* github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs.func1()
* 	github.com/cockroachdb/cockroach/pkg/util/admission/work_queue.go:500 +0x14d
* created by github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs in goroutine 14136
* 	github.com/cockroachdb/cockroach/pkg/util/admission/work_queue.go:471 +0x4f
* 
* goroutine 14177 [select]:
* github.com/cockroachdb/cockroach/pkg/util/admission.initWorkQueue.func2()
* 	github.com/cockroachdb/cockroach/pkg/util/admission/work_queue.go:423 +0x85
* created by github.com/cockroachdb/cockroach/pkg/util/admission.initWorkQueue in goroutine 14136
* 	github.com/cockroachdb/cockroach/pkg/util/admission/work_queue.go:420 +0x3be
* 
* goroutine 14172 [select]:
* github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs.func1()
* 	github.com/cockroachdb/cockroach/pkg/util/admission/work_queue.go:500 +0x14d
* created by github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs in goroutine 14136
* 	github.com/cockroachdb/cockroach/pkg/util/admission/work_queue.go:471 +0x4f
* 
*
```
</p>
</details>

Parameters:
 - <code>attempt=1</code>
 - <code>run=9</code>
 - <code>shard=5</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestTenantStreamingJobRetryReset.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-38316

### LINKED ISSUE #123397: ccl/streamingccl/streamingest: TestTenantStreamingMultipleNodes failed
ccl/streamingccl/streamingest.TestTenantStreamingMultipleNodes [failed](https://mesolite.cluster.engflow.com/invocations/default/7e0940ef-305f-4456-b227-0d6a24f50706?testReportRun=1&testReportShard=15&testReportAttempt=1#targets-Ly9wa2cvY2NsL3N0cmVhbWluZ2NjbC9zdHJlYW1pbmdlc3Q6c3RyZWFtaW5nZXN0X3Rlc3Q=) on master @ [6eeddf14e5420000793f2c5334ca1ac26f0ca12d](https://github.com/cockroachdb/cockroach/commits/6eeddf14e5420000793f2c5334ca1ac26f0ca12d):

Fatal error:

```
panic: test timed out after 14m57s
running tests:
	TestTenantStreamingMultipleNodes (14m57s)
	TestTenantStreamingMultipleNodes/fromSystem=true (14m31s)

```
Stack: 

```
goroutine 105307 [running]:
testing.(*M).startAlarm.func1()
	GOROOT/src/testing/testing.go:2366 +0x385
created by time.goFunc
	GOROOT/src/time/sleep.go:177 +0x2d
```
<details><summary>Log preceding fatal error</summary>
<p>

```
* sync.(*Cond).Wait(0x30?)
* 	GOROOT/src/sync/cond.go:70 +0x85
* github.com/cockroachdb/pebble/record.(*flusherCond).Wait(...)
* 	github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go:369
* github.com/cockroachdb/pebble/record.(*LogWriter).flushLoop(0xc006bde000, {0x5c8c520?, 0xc353840?})
* 	github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go:643 +0x6fd
* runtime/pprof.Do({0x7f3b1a8?, 0xc353840?}, {{0xc000e20bc0?, 0xc001c6cc80?, 0x7ef19a0?}}, 0xc001acb7c0)
* 	GOROOT/src/runtime/pprof/runtime.go:51 +0x9d
* github.com/cockroachdb/pebble/record.NewLogWriter.func2()
* 	github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go:562 +0x56
* created by github.com/cockroachdb/pebble/record.NewLogWriter in goroutine 42215
* 	github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go:561 +0x4b8
* 
* goroutine 42245 [select]:
* github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs.func1()
* 	github.com/cockroachdb/cockroach/pkg/util/admission/work_queue.go:500 +0x14d
* created by github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs in goroutine 42215
* 	github.com/cockroachdb/cockroach/pkg/util/admission/work_queue.go:471 +0x4f
* 
* goroutine 42240 [select]:
* github.com/cockroachdb/cockroach/pkg/util/admission.initWorkQueue.func2()
* 	github.com/cockroachdb/cockroach/pkg/util/admission/work_queue.go:423 +0x85
* created by github.com/cockroachdb/cockroach/pkg/util/admission.initWorkQueue in goroutine 42215
* 	github.com/cockroachdb/cockroach/pkg/util/admission/work_queue.go:420 +0x3be
* 
* goroutine 42234 [select]:
* github.com/cockroachdb/cockroach/pkg/util/admission.initWorkQueue.func2()
* 	github.com/cockroachdb/cockroach/pkg/util/admission/work_queue.go:423 +0x85
* created by github.com/cockroachdb/cockroach/pkg/util/admission.initWorkQueue in goroutine 42215
* 	github.com/cockroachdb/cockroach/pkg/util/admission/work_queue.go:420 +0x3be
* 
* goroutine 42235 [select]:
* github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs.func1()
* 	github.com/cockroachdb/cockroach/pkg/util/admission/work_queue.go:500 +0x14d
* created by github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs in goroutine 42215
* 	github.com/cockroachdb/cockroach/pkg/util/admission/work_queue.go:471 +0x4f
* 
* goroutine 42239 [select]:
* github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs.func1()
* 	github.com/cockroachdb/cockroach/pkg/util/admission/work_queue.go:500 +0x14d
* created by github.com/cockroachdb/cockroach/pkg/util/admission.(*WorkQueue).startClosingEpochs in goroutine 42215
* 	github.com/cockroachdb/cockroach/pkg/util/admission/work_queue.go:471 +0x4f
* 
* goroutine 42236 [select]:
* github.com/cockroachdb/cockroach/pkg/util/admission.initWorkQueue.func2()
* 	github.com/cockroachdb/cockroach/pkg/util/admission/work_queue.go:423 +0x85
* created by github.com/cockroachdb/cockroach/pkg/util/admission.initWorkQueue in goroutine 42215
* 	github.com/cockroachdb/cockroach/pkg/util/admission/work_queue.go:420 +0x3be
* 
*
```
</p>
</details>

Parameters:
 - <code>attempt=1</code>
 - <code>run=1</code>
 - <code>shard=15</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/disaster-recovery
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestTenantStreamingMultipleNodes.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-38343

### PR DESCRIPTION
**Pull request by msbutler**
If the rangefeed client's context is cancelled before a metadata event is sent
on the event channel, the rangefeed could hang forever. This bug was introduced
in #123001.

Fixes #123355
Fixes #123397

Release note: none

### CODE REVIEW

**Comment by celiala** [comment]
FYI that I'm removing the backport to v24.1.0-rc, as the rc candidate is building now. thanks!
(and it looks like the blockers are against `master` branch).

**Review by dt — APPROVED** [review]

**Comment by dt** [comment]
The issue affects 24.1 and 24.1.0 as well, but I think we can live with it in 24.1.0

**Comment by msbutler** [comment]
TFTR!

bors r=dt

**Comment by msbutler** [comment]
unrelated unit test flake

bors r+

**Comment by msbutler** [comment]
blathers backport release-24.1.0-rc

**Pull request merged**
