### PR TITLE
storage: reenable TestStoreRangeRebalance

### PR DESCRIPTION
**Pull request by petermattis**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8444)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[gossip/client.go, line 75 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8444#-KOpLk_87YVneVE6Ownv:-KOpLk_87YVneVE6Ownw:b-7u7cw5) ([raw file](https://github.com/cockroachdb/cockroach/blob/83cce47296dca39644e07e9c9b4f58c26f7c8120/gossip/client.go#L75)):*
> ```Go
> func (c *client) start(g *Gossip, disconnected chan *client, rpcCtx *rpc.Context, stopper *stop.Stopper) {
> 	ctx := context.TODO()
> 	nodeID := g.is.NodeID
> ```

this local is slightly inconsistent since you just inlined everywhere else. optional nit.

---

*[storage/balancer.go, line 156 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8444#-KOpKQGMwmGBCzWtMqNm:-KOpKQGNWOexy4a0r1by:b-bz8eik) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c56b6fef3207015b99217c2bbfd28bf129649c4/storage/balancer.go#L156)):*
> ```Go
> 	// node becomes fuller than maxFractionUsedThreshold we will always select it
> 	// for rebalancing. This is currently utilized by tests.
> 	res := store.Capacity.FractionUsed() <= maxFractionUsedThreshold &&
> ```

can you give `res` a more descriptive name? perhaps `rebalanceNotNeeded`?

---

*[storage/client_test.go, line 572 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8444#-KOpLNCx8jnAxHm8q0cL:-KOpLNCx8jnAxHm8q0cM:b-3h85l3) ([raw file](https://github.com/cockroachdb/cockroach/blob/43dee23105707b9b7fa286ba7e36619b34ca756e/storage/client_test.go#L572)):*
> ```Go
> 		m.mu.Lock()
> 		defer m.mu.Unlock()
> 		addr := m.nodeIDtoAddr[1]
> ```

isn't the first store `[0]`?

---

*[storage/store_pool.go, line 256 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8444#-KOpKzo75eagbFYMRWQY:-KOpKzo8yfE7ekzDbqj9:bps0x8p) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c56b6fef3207015b99217c2bbfd28bf129649c4/storage/store_pool.go#L256)):*
> ```Go
> 
> 	var buf bytes.Buffer
> 	now := time.Now()
> ```

probably has to be timeutil.

---

*[storage/store_pool.go, line 447 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8444#-KOpKoBasjUzYL6ySayp:-KOpKoBbVDDxDZB2sCUh:bp206is) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c56b6fef3207015b99217c2bbfd28bf129649c4/storage/store_pool.go#L447)):*
> ```Go
> func (sl StoreList) String() string {
> 	var buf bytes.Buffer
> 	fmt.Fprintf(&buf, "  candidate-count: mean=%v\n", sl.candidateCount.mean)
> ```

why the indents?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8444#-:-KOpM9X4ScW9UOyiykC8:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: 2 of 10 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[gossip/client.go, line 75 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8444#-KOpLk_87YVneVE6Ownv:-KOpRYU4zqSrcD1i-Hq1:bfbk7nf) ([raw file](https://github.com/cockroachdb/cockroach/blob/83cce47296dca39644e07e9c9b4f58c26f7c8120/gossip/client.go#L75)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this local is slightly inconsistent since you just inlined everywhere else. optional nit.
</details>
Yeah, it's inconsistent, but some of the uses are done where we're not holding `g.mu.Lock()` which would make accessing `g.is.NodeID` unsafe.

---

*[storage/balancer.go, line 156 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8444#-KOpKQGMwmGBCzWtMqNm:-KOpRhGDy9Ka4RD_jUd6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c56b6fef3207015b99217c2bbfd28bf129649c4/storage/balancer.go#L156)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can you give `res` a more descriptive name? perhaps `rebalanceNotNeeded`?
</details>
Done.

---

*[storage/client_test.go, line 572 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8444#-KOpLNCx8jnAxHm8q0cL:-KOpRrkMYGuAtdoWYPqD:bqwe1wm) ([raw file](https://github.com/cockroachdb/cockroach/blob/43dee23105707b9b7fa286ba7e36619b34ca756e/storage/client_test.go#L572)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> isn't the first store `[0]`?
</details>
The `nodeIDtoAddr` map is indexed by node ID, not node index. The first node ID is 1. See about a dozen lines down in this method.

---

*[storage/store_pool.go, line 256 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8444#-KOpKzo75eagbFYMRWQY:-KOpS4hKqYP176T-KCk-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c56b6fef3207015b99217c2bbfd28bf129649c4/storage/store_pool.go#L256)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> probably has to be timeutil.
</details>
Done.

---

*[storage/store_pool.go, line 447 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8444#-KOpKoBasjUzYL6ySayp:-KOpS5OSCIkcMR9-AO1S:b63m0eu) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c56b6fef3207015b99217c2bbfd28bf129649c4/storage/store_pool.go#L447)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> why the indents?
</details>
The usage of this output by `allocator.go` makes this info easier to consume.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8444)*

**Comment by tamird** [comment]
Reviewed 3 of 8 files at r5, 1 of 1 files at r6, 3 of 3 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[gossip/client.go, line 75 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8444#-KOpLk_87YVneVE6Ownv:-KOpZO2qu7n_U07_nJdK:bwqgkel) ([raw file](https://github.com/cockroachdb/cockroach/blob/83cce47296dca39644e07e9c9b4f58c26f7c8120/gossip/client.go#L75)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Yeah, it's inconsistent, but some of the uses are done where we're not holding `g.mu.Lock()` which would make accessing `g.is.NodeID` unsafe.
</details>
Ah, I see that now.

---

*[storage/store_pool.go, line 447 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8444#-KOpKoBasjUzYL6ySayp:-KOpZhTJQzSCrJ89e1xl:b-rrpgad) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c56b6fef3207015b99217c2bbfd28bf129649c4/storage/store_pool.go#L447)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> The usage of this output by `allocator.go` makes this info easier to consume.
</details>
I'd feel slightly better if this was achieved using a tabwriter. Optional.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8444)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/store_pool.go, line 447 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8444#-KOpKoBasjUzYL6ySayp:-KOpa9Nux6_e3UOI9n1v:b9xjw5b) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c56b6fef3207015b99217c2bbfd28bf129649c4/storage/store_pool.go#L447)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I'd feel slightly better if this was achieved using a tabwriter. Optional.
</details>
No need for a tabwriter here as the spacing is known. Tabwriter is nice when you need variable width tabs. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8444)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[storage/client_test.go, line 567 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8444#-KOpkjI0xfSvVjnXF4ni:-KOpkjI0xfSvVjnXF4nj:bn7wsx0) ([raw file](https://github.com/cockroachdb/cockroach/blob/751d7b5931d1943ae11c133c8a603af4f8c16aba/storage/client_test.go#L567)):*
> ```Go
> 
> 	// Give this store the first store as a resolver. We don't provide all of the
> 	// previous stores as resolvers as doing so can cause delays in bringing the
> ```

Why is there a delay if we give it multiple resolvers? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8444)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[storage/client_test.go, line 567 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8444#-KOpkjI0xfSvVjnXF4ni:-KOpo7pGZflDXoTGEfOi:b-ry2hl4) ([raw file](https://github.com/cockroachdb/cockroach/blob/751d7b5931d1943ae11c133c8a603af4f8c16aba/storage/client_test.go#L567)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Why is there a delay if we give it multiple resolvers? 
</details>
In at least one run, I saw nodes connecting to the non-bootstrap node and then having to wait for reconnections. This part of the PR might not have been completely necessary after bumping the succeeds soon timeout. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8444)*

**Pull request merged**
