### PR TITLE
jwtauthccl: Rename and hide `server.jwt_authentication.issuer_custom_ca`

### LINKED ISSUE #126935: jwtauthccl: Rename and hide `server.jwt_authentication.issuer_custom_ca`
**Describe the problem**
https://github.com/cockroachdb/cockroach/pull/126062 introduced the `server.jwt_authentication.issuer_custom_ca` cluster setting which has the following problems:
1. It has been made public prematurely in comparison to the other JWT cluster settings.
2. The cluster setting name should be renamed to `server.jwt_authentication.issuers.custom_ca` for consistency (e.g. `server.ldap_authentication.domain.custom_ca`)

**Expected behavior**
All the JWT cluster settings could be made public at once as part of https://github.com/cockroachdb/cockroach/issues/126540.

**Additional context**
This may need to be backported to 24.2

Jira issue: CRDB-40195

Epic CRDB-39964

### PR DESCRIPTION
**Pull request by pritesh-lahoti**
https://github.com/cockroachdb/cockroach/pull/126062 introduced the `server.jwt_authentication.issuer_custom_ca` cluster setting which has the following problems:
1. It has been made public prematurely in comparison to the other JWT cluster settings.
2. The cluster setting name should be renamed to `server.jwt_authentication.issuers.custom_ca` for consistency (e.g. `server.ldap_authentication.domain.custom_ca`)

All the JWT cluster settings will be made public at once as part of https://github.com/cockroachdb/cockroach/issues/126540.

Fixes: #126935
Epic: CRDB-40195

Release note: None

### CODE REVIEW

**Review by souravcrl — APPROVED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126939)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pritesh-lahoti)

___
*[`docs/generated/settings/settings-for-tenants.txt` line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126939#-O1boJYCBogb1xaH-skf:-O1boJYCBogb1xaH-skg:brv8wm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/551dcfbaf516139ab8c6f5d30269a00b0bdce032/docs/generated/settings/settings-for-tenants.txt#L92)):*
> ```help
> server.http.base_path	string	/	path to redirect the user to upon succcessful login	application
> server.identity_map.configuration	string		system-identity to database-username mappings	application
> server.jwt_authentication.issuer_custom_ca	string		sets the custom root CA for verifying certificates while fetching JWKS from the JWT issuer	application
> ```

Should we update the setting description to say `sets the custom root CA for verifying certificates while fetching  JWKS url(from open-id configuration) and JWKS from the JWT issuer. Multiple domains CA certs can be concatenated to be added to root CA` ?

**Review by pritesh-lahoti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126939)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @souravcrl)

___
*[`docs/generated/settings/settings-for-tenants.txt` line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126939#-O1boJYCBogb1xaH-skf:-O1c-BNH4OswqewmF24W:b4zek0t) ([raw file](https://github.com/cockroachdb/cockroach/blob/551dcfbaf516139ab8c6f5d30269a00b0bdce032/docs/generated/settings/settings-for-tenants.txt#L92)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

Should we update the setting description to say `sets the custom root CA for verifying certificates while fetching  JWKS url(from open-id configuration) and JWKS from the JWT issuer. Multiple domains CA certs can be concatenated to be added to root CA` ?
</blockquote></details>

Reworded to address your point. Tried to keep it short and crisp.
PEM - denotes that certs could be concatenated; removed the `from JWT issuer` part.

**Comment by souravcrl** [comment]
https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/186548364/Release+notes#High-level-rules
`Although the cluster setting has been renamed, it has also been hidden.` this should be before the release note as release note should be the last line of the commit and reserved interfaces should not be in the release note.

**Review by pritesh-lahoti — COMMENTED** [review]
Addressed. Thank you!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126939#-:-O1pJ9hw1oqznxgktkKT:baepupk)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @souravcrl)

**Comment by pritesh-lahoti** [comment]
blathers backport 24.2

**Pull request merged**
