### PR TITLE
storage,roachpb: protected timestamp plumbing into storage

### PR DESCRIPTION
**Pull request by ajwerner**
This PR comes as two commits.

1) Plumb the interfaces into the `storage.Replica` and GC process
2) Introduce the AdminVerifyProtectedTimestamp to the roachpb API

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, 12 of 12 files at r3, 11 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42890)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/roachpb/api.proto, line 1472 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-Lw0wy2j6pu_JCiPozBx:-Lw0wy2j6pu_JCiPozBy:b-o1222w) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a02eef10f946a445d1e7d72e181858eac2b05b4/pkg/roachpb/api.proto#L1472)):*
> ```protobuf
>   RequestHeader header = 1 [(gogoproto.nullable) = false, (gogoproto.embed) = true];
> 
>   util.hlc.Timestamp protected = 2 [(gogoproto.nullable) = false];
> ```

Let's give these fields comments. Their roles aren't obvious.
___
*[pkg/roachpb/api_test.go, line 110 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-Lw0xGLh2IDtUd8Z-6KH:-Lw0xGLh2IDtUd8Z-6KI:btj0f0y) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a02eef10f946a445d1e7d72e181858eac2b05b4/pkg/roachpb/api_test.go#L110)):*
> ```Go
> 
> 		if _, ok := interface{}(v1).(combinable); !ok {
> 			t.Fatal("AdminVerifyProtectedTimestampResponse does not implement combinable")
> ```

nit: reword to something that doesn't say the exact opposite of what we're trying to test. This confused me for a second. Maybe:

```
t.Fatal("AdminVerifyProtectedTimestampResponse unexpectedly does not implement combinable")
```
___
*[pkg/storage/replica.go, line 1399 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-Lw0xk360jsImWFfKOeU:-Lw0xk360jsImWFfKOeV:b47mmfl) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a02eef10f946a445d1e7d72e181858eac2b05b4/pkg/storage/replica.go#L1399)):*
> ```Go
> 
> 	// Admin commands always require the range lease.
> 	_, pErr := r.redirectOnOrAcquireLease(ctx)
> ```

Are we checking the lease twice?
___
*[pkg/storage/replica_protected_timestamp.go, line 90 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-Lw0s_GH1EwygicvtHZm:-Lw0s_GH1EwygicvtHZn:btyhosr) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f421f10df7364ca8ceb9182fe5a39258c0a71f7/pkg/storage/replica_protected_timestamp.go#L90)):*
> ```Go
> // checkProtectedTimestampsForGC determines whether the Replica can run GC.
> // If the Replica can run GC, this method returns the latest timestamp which
> // can be used to determine a valid new GCThreshold.
> ```

The method seems to have other side-effects as well. Could you spell those out?
___
*[pkg/storage/replica_protected_timestamp.go, line 106 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-Lw0sUlG7i24aewnXEn5:-Lw0sUlG7i24aewnXEn6:bk5rfpm) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f421f10df7364ca8ceb9182fe5a39258c0a71f7/pkg/storage/replica_protected_timestamp.go#L106)):*
> ```Go
> 
> 		r.protectedTimestampMu.Lock()
> 		delete(r.protectedTimestampMu.promisedIDs, rec.ID)
> ```

Could you give this a comment? It's not obvious what it's doing.
___
*[pkg/storage/replica_protected_timestamp.go, line 139 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-Lw0t332DBTEr9jPLG8X:-Lw0t332DBTEr9jPLG8Y:b6cw719) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f421f10df7364ca8ceb9182fe5a39258c0a71f7/pkg/storage/replica_protected_timestamp.go#L139)):*
The need for both of these checks indicates that there's some duplication of responsibility here. Both the protected timestamp system and the promises are trying to serve similar roles. I wonder whether some of this redundancy could be removed. Please correct me if any of this is incorrect?

- We couldn't only have promises because they don't persist across a lease transfer.
- We couldn't only have protected timestamps because a given replica could have an arbitrarily stale view of this system and there would be no way for a request to ensure that it's timestamp will be respected.

This makes me wonder whether protected timestamp validation should be tied in a little tighter to the protected timestamp system. Instead of maintaining a set of promises and checking them here, could we instead have the process of acquiring a "promise" wait until the protected timestamp system has caught up before returning? I think this would avoid the parallel bookkeeping and make the roles of these components more clear.

Another way to look at this is that  in `gcQueue.process`, we say:
> process first determines whether the replica can run GC given its view of the protected timestamp subsystem and its current state.

The fact that this determination is a function of both its protected timestamp subsystem _and its current state_ seems undesirable. What would it take to make this determination only based on the protected timestamp subsystem?
___
*[pkg/storage/store.go, line 698 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-Lw0wdPOBh3SmgCG9p4p:-Lw0wdPOBh3SmgCG9p4q:bm9dq9l) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f421f10df7364ca8ceb9182fe5a39258c0a71f7/pkg/storage/store.go#L698)):*
> ```Go
> 	ExternalStorageFromURI cloud.ExternalStorageFromURIFactory
> 
> 	ProtectedTimestampTracker protectedts.Tracker
> ```

Might as well give this a comment since everything else here has one.

**Review by ajwerner — COMMENTED** [review]
This is RFAL. It's gotten simpler since your last pass but I could see another iteration on the `pendingGC` state. Curious to hear what you think. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-:-LxbScMI0GDLLoGleZ8B:b-epwoya)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/roachpb/api.proto, line 1472 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-Lw0wy2j6pu_JCiPozBx:-LxbRPom6OflWDl162xi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a02eef10f946a445d1e7d72e181858eac2b05b4/pkg/roachpb/api.proto#L1472)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's give these fields comments. Their roles aren't obvious.
</blockquote></details>

Done.
___
*[pkg/roachpb/api_test.go, line 110 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-Lw0xGLh2IDtUd8Z-6KH:-LxbRYPC8vKyxtd6U26o:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a02eef10f946a445d1e7d72e181858eac2b05b4/pkg/roachpb/api_test.go#L110)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: reword to something that doesn't say the exact opposite of what we're trying to test. This confused me for a second. Maybe:

```
t.Fatal("AdminVerifyProtectedTimestampResponse unexpectedly does not implement combinable")
```
</blockquote></details>

Done.
___
*[pkg/storage/replica.go, line 1399 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-Lw0xk360jsImWFfKOeU:-LxbRjQw3AlrxPM3Ixsl:b-9jvu3h) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a02eef10f946a445d1e7d72e181858eac2b05b4/pkg/storage/replica.go#L1399)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Are we checking the lease twice?
</blockquote></details>

We were and we still are in the new code, once when first checking the status and once after refreshing the cache state. It's a bit more explicit now. 
___
*[pkg/storage/replica_protected_timestamp.go, line 99 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-LvHJt5k-QK42pEDn5jU:-LvHJt5k-QK42pEDn5jV:b-5bstim) ([raw file](https://github.com/cockroachdb/cockroach/blob/e58d205ecb7e2cbce4ef7a2e55a63c09da0f95e3/pkg/storage/replica_protected_timestamp.go#L99)):*
> ```Go
> 	lease := *r.mu.state.Lease
> 	r.mu.RUnlock()
> 	var overlapping []*ptpb.Record
> ```

One thing I've considered is storing this slice on the replica object under the `protectedTimestampMu` to avoid allocations here in the common case. 
___
*[pkg/storage/replica_protected_timestamp.go, line 90 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-Lw0s_GH1EwygicvtHZm:-LxbS1cx8XBjuA944YEe:bm6clv0) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f421f10df7364ca8ceb9182fe5a39258c0a71f7/pkg/storage/replica_protected_timestamp.go#L90)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The method seems to have other side-effects as well. Could you spell those out?
</blockquote></details>

It no longer has those side effects. 
___
*[pkg/storage/replica_protected_timestamp.go, line 106 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-Lw0sUlG7i24aewnXEn5:-LxbSMwr290Cvlm4UfeW:bnlvq0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f421f10df7364ca8ceb9182fe5a39258c0a71f7/pkg/storage/replica_protected_timestamp.go#L106)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Could you give this a comment? It's not obvious what it's doing.
</blockquote></details>

the less obvious logic has been removed.
___
*[pkg/storage/replica_protected_timestamp.go, line 139 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-Lw0t332DBTEr9jPLG8X:-LxbS9PQAiEmqdkCGYpI:b2wcb1q) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f421f10df7364ca8ceb9182fe5a39258c0a71f7/pkg/storage/replica_protected_timestamp.go#L139)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The need for both of these checks indicates that there's some duplication of responsibility here. Both the protected timestamp system and the promises are trying to serve similar roles. I wonder whether some of this redundancy could be removed. Please correct me if any of this is incorrect?

- We couldn't only have promises because they don't persist across a lease transfer.
- We couldn't only have protected timestamps because a given replica could have an arbitrarily stale view of this system and there would be no way for a request to ensure that it's timestamp will be respected.

This makes me wonder whether protected timestamp validation should be tied in a little tighter to the protected timestamp system. Instead of maintaining a set of promises and checking them here, could we instead have the process of acquiring a "promise" wait until the protected timestamp system has caught up before returning? I think this would avoid the parallel bookkeeping and make the roles of these components more clear.

Another way to look at this is that  in `gcQueue.process`, we say:
> process first determines whether the replica can run GC given its view of the protected timestamp subsystem and its current state.

The fact that this determination is a function of both its protected timestamp subsystem _and its current state_ seems undesirable. What would it take to make this determination only based on the protected timestamp subsystem?
</blockquote></details>

this is mostly fixed. There's still the pending GC state. 
___
*[pkg/storage/store.go, line 698 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-Lw0wdPOBh3SmgCG9p4p:-LxbTWL_8BIczM4OcGF7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f421f10df7364ca8ceb9182fe5a39258c0a71f7/pkg/storage/store.go#L698)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Might as well give this a comment since everything else here has one.
</blockquote></details>

Done.

**Review by nvb — COMMENTED** [review]
This is looking a lot nicer with the simplification. My big remaining question is whether that allows us to remove a lot of the remaining leaseholder interactions entirely.

> Reviewed 16 of 16 files at r5, 11 of 11 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-:-Lxbbppr-PsHcNc1F2om:b-teu5db)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/roachpb/api.proto, line 1478 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-LxbbKpu7TvO_YWSPXKm:-LxbbKpu7TvO_YWSPXKn:b-rq9r4y) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e66726b3cf146e53113761533bf63c67be2cf7b/pkg/roachpb/api.proto#L1478)):*
> observing the timestamp at which the read occurred

By this do you mean "observing the timestamp of the record's KV pair" or "using the timestamp at which the read occurred"? The word "observing" is kind of throwing me off.
___
*[pkg/storage/replica_protected_timestamp.go, line 99 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-LvHJt5k-QK42pEDn5jU:-LxbaE080t5HGSzqLHQV:b-5c2x07) ([raw file](https://github.com/cockroachdb/cockroach/blob/e58d205ecb7e2cbce4ef7a2e55a63c09da0f95e3/pkg/storage/replica_protected_timestamp.go#L99)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

One thing I've considered is storing this slice on the replica object under the `protectedTimestampMu` to avoid allocations here in the common case. 
</blockquote></details>

Maybe just leave a TODO.
___
*[pkg/storage/replica_protected_timestamp.go, line 30 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-LxbZxe-EohVWRnB4GB-:-LxbZxe0669FjTS6S7TO:b-f4wf9y) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3513de84218c43d26474899dee6c3df180b97c8/pkg/storage/replica_protected_timestamp.go#L30)):*
> ```Go
> // is refreshed and then the check is performed again.
> func (r *Replica) protectedTimestampRecordApplies(
> 	ctx context.Context, protected, recordAliveAt hlc.Timestamp, id uuid.UUID,
> ```

nit: I'd rename this to `createdAt` so that it lines up more closely with the comment. Or reword the comment like you did with `protectedTimestampRecordCurrentlyApplies`.
___
*[pkg/storage/replica_protected_timestamp.go, line 66 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-Lxb_KcO4X5yCCsB0bwi:-Lxb_KcO4X5yCCsB0bwj:b-pc19zb) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3513de84218c43d26474899dee6c3df180b97c8/pkg/storage/replica_protected_timestamp.go#L66)):*
> ```Go
> 	ctx context.Context, protected, recordAliveAt hlc.Timestamp, id uuid.UUID,
> ) (willApply, cacheTooOld bool, _ error) {
> 	// We first need to check that we're the current leaseholder.
> ```

Now that we're no longer making promises and holding on to state on the leaseholder, do we need to check for the lease at all? Getting rid of that requirement would be a very nice simplification throughout all of this.
___
*[pkg/storage/replica_protected_timestamp.go, line 119 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-Lxb_zgn9C-jJCxaXZ6v:-Lxb_zgn9C-jJCxaXZ6w:be736y6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3513de84218c43d26474899dee6c3df180b97c8/pkg/storage/replica_protected_timestamp.go#L119)):*
> ```Go
> 		})
> 	if seen {
> 		r.protectedTimestampMu.minStateReadTimestamp = readAt
> ```

Why do we only set this on this path? And we no longer need to forward it?
___
*[pkg/storage/replica_protected_timestamp.go, line 149 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-LxbaLf21O6aqs2eEQWk:-LxbaLf21O6aqs2eEQWl:b4o3mxr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3513de84218c43d26474899dee6c3df180b97c8/pkg/storage/replica_protected_timestamp.go#L149)):*
> ```Go
> 			// replica state here to determine whether the record indeed has been
> 			// applied.
> 			if !rec.Timestamp.Less(gcThreshold) {
> ```

Is this easier to read with `LessEq`?
___
*[pkg/storage/replica_protected_timestamp_test.go, line 207 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-Lxbb3e1EXEE1Kaprtxy:-Lxbb3e20g9mh32LvKgW:b10ca2z) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3513de84218c43d26474899dee6c3df180b97c8/pkg/storage/replica_protected_timestamp_test.go#L207)):*
> ```Go
> 			},
> 		},
> 		// Ensure NLE after performing a refresh propagates.
> ```

Nice tests.

**Review by ajwerner — COMMENTED** [review]
Thanks for the quick turnaround. I think we still need the leaseholder interactions.

The synchronization around markPendingGC does feel a bit clunky but I don't have a clear vision on how to make it all that much better. One option would be to hold the protectedTimestampMu during the entirety of consulting the cache and computing the new GC threshold in `gcQueue.process`

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-:-Lxbndf6D0iji0z2-tdL:b-7ocav3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/roachpb/api.proto, line 1478 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-LxbbKpu7TvO_YWSPXKm:-Lxbm4Ye9C499jaBOy2m:bhuoegn) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e66726b3cf146e53113761533bf63c67be2cf7b/pkg/roachpb/api.proto#L1478)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> observing the timestamp at which the read occurred

By this do you mean "observing the timestamp of the record's KV pair" or "using the timestamp at which the read occurred"? The word "observing" is kind of throwing me off.
</blockquote></details>

I mean "using the timestamp at which the read occurred". I've `s/observing/using/`'d the comment.
___
*[pkg/storage/replica_protected_timestamp.go, line 99 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-LvHJt5k-QK42pEDn5jU:-Lxbl7wtBJ6stuJINsuW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e58d205ecb7e2cbce4ef7a2e55a63c09da0f95e3/pkg/storage/replica_protected_timestamp.go#L99)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Maybe just leave a TODO.
</blockquote></details>

Done.
___
*[pkg/storage/replica_protected_timestamp.go, line 30 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-LxbZxe-EohVWRnB4GB-:-LxbegHo-o_INxibLS5a:b-u1i96f) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3513de84218c43d26474899dee6c3df180b97c8/pkg/storage/replica_protected_timestamp.go#L30)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: I'd rename this to `createdAt` so that it lines up more closely with the comment. Or reword the comment like you did with `protectedTimestampRecordCurrentlyApplies`.
</blockquote></details>

Stale comment. It's not when the record was created any longer. 
___
*[pkg/storage/replica_protected_timestamp.go, line 66 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-Lxb_KcO4X5yCCsB0bwi:-Lxbeojh7OdnXdtaJQNk:bdotfwq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3513de84218c43d26474899dee6c3df180b97c8/pkg/storage/replica_protected_timestamp.go#L66)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Now that we're no longer making promises and holding on to state on the leaseholder, do we need to check for the lease at all? Getting rid of that requirement would be a very nice simplification throughout all of this.
</blockquote></details>

We do indeed need to ensure that we're the leaseholder and we do store some state on the leaseholder. We cannot just check any replica as that replica 1) may have a stale view of the GC Threshold or 2) may have an up-to-date view of the GC threshold but may occur concurrently with an attempt to change the GC threshold. Note the `r.protectedTimestampMu.minStateReadTimestamp`.
___
*[pkg/storage/replica_protected_timestamp.go, line 119 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-Lxb_zgn9C-jJCxaXZ6v:-Lxbfg2O8Dz6DnocN6Wp:b-gzpg3s) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3513de84218c43d26474899dee6c3df180b97c8/pkg/storage/replica_protected_timestamp.go#L119)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why do we only set this on this path? And we no longer need to forward it?
</blockquote></details>

Added commentary here and on the `Replica` struct.
___
*[pkg/storage/replica_protected_timestamp.go, line 149 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-LxbaLf21O6aqs2eEQWk:-LxbkmohA9BT2MzCniDw:b-rq2q7k) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3513de84218c43d26474899dee6c3df180b97c8/pkg/storage/replica_protected_timestamp.go#L149)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this easier to read with `LessEq`?
</blockquote></details>

Done. Didn't know about  `LessEq`.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 4 of 15 files at r7, 11 of 11 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-:-Lxc-wFr0wZrC5lI5z9z:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/storage/replica_protected_timestamp.go, line 66 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-Lxb_KcO4X5yCCsB0bwi:-LxbzGha9LltW4dUep0y:b-lg05o9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3513de84218c43d26474899dee6c3df180b97c8/pkg/storage/replica_protected_timestamp.go#L66)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

We do indeed need to ensure that we're the leaseholder and we do store some state on the leaseholder. We cannot just check any replica as that replica 1) may have a stale view of the GC Threshold or 2) may have an up-to-date view of the GC threshold but may occur concurrently with an attempt to change the GC threshold. Note the `r.protectedTimestampMu.minStateReadTimestamp`.
</blockquote></details>

I see, thanks for the explanation.
___
*[pkg/storage/replica_protected_timestamp.go, line 92 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-LxbzvKk4_7EAVG7wtyd:-LxbzvKk4_7EAVG7wtye:b-10312u) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb791feac7613d0d42c6dc49f8e4195bd461c824/pkg/storage/replica_protected_timestamp.go#L92)):*
> ```Go
> 	defer r.mu.RUnlock()
> 
> 	if !r.mu.state.GCThreshold.Less(protected) {
> ```

`LessEq` here too.
___
*[pkg/storage/replica_protected_timestamp.go, line 120 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-LxbzNwF5R9-FYnr4diR:-LxbzNwF5R9-FYnr4diS:bj8jyax) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb791feac7613d0d42c6dc49f8e4195bd461c824/pkg/storage/replica_protected_timestamp.go#L120)):*
> ```Go
> 	// If we observed the record in question then we know that all future attempts
> 	// to run GC will observe the Record if it still exists. The one hazard we
> 	// need to avoid is a race whereby and attempt to run GC first checks the
> ```

s/and/an/
___
*[pkg/storage/replica_protected_timestamp.go, line 139 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-Lxc-gHyBFVbGYaPNNGQ:-Lxc-gHyBFVbGYaPNNGR:b-k1bwev) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb791feac7613d0d42c6dc49f8e4195bd461c824/pkg/storage/replica_protected_timestamp.go#L139)):*
> ```Go
> // If the Replica can run GC, this method returns the latest timestamp which
> // can be used to determine a valid new GCThreshold.
> func (r *Replica) checkProtectedTimestampsForGC(
> ```

What's going on here with `now` and `gcThreshold`? Why do we take `now` as a param if we're just going to ignore it?

**Review by ajwerner — COMMENTED** [review]
TFTR!

bors r=nvanbenschoten

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-:-LxcHNM8-1JqpgzB1j74:b-l0r5kv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[pkg/storage/replica_protected_timestamp.go, line 92 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-LxbzvKk4_7EAVG7wtyd:-Lxc4aZg46Y8srYM9Egu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb791feac7613d0d42c6dc49f8e4195bd461c824/pkg/storage/replica_protected_timestamp.go#L92)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`LessEq` here too.
</blockquote></details>

Done.
___
*[pkg/storage/replica_protected_timestamp.go, line 120 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-LxbzNwF5R9-FYnr4diR:-Lxc4v1D0Xe4PwMog4i5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb791feac7613d0d42c6dc49f8e4195bd461c824/pkg/storage/replica_protected_timestamp.go#L120)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

s/and/an/
</blockquote></details>

Done.
___
*[pkg/storage/replica_protected_timestamp.go, line 139 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-Lxc-gHyBFVbGYaPNNGQ:-Lxc3XeY4INwBZEnD5AC:b-fq78zx) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb791feac7613d0d42c6dc49f8e4195bd461c824/pkg/storage/replica_protected_timestamp.go#L139)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What's going on here with `now` and `gcThreshold`? Why do we take `now` as a param if we're just going to ignore it?
</blockquote></details>

Good point. In a previous iteration it was used. Removed.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42890)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[pkg/storage/replica_protected_timestamp.go, line 139 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-Lxc-gHyBFVbGYaPNNGQ:-LxcJ9Tb1Ey4fxCJy4Lp:bll1wpf) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb791feac7613d0d42c6dc49f8e4195bd461c824/pkg/storage/replica_protected_timestamp.go#L139)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Good point. In a previous iteration it was used. Removed.
</blockquote></details>

I'm still confused. Why are we consulting `r.mu.state.GCThreshold` at all? Isn't this supposed to be picking a new gc theshold, before the replica state has been updated to reflect it?

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42890)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[pkg/storage/replica_protected_timestamp.go, line 139 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/42890#-Lxc-gHyBFVbGYaPNNGQ:-LxcN_n82SAotn5Quzev:b-a29is6) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb791feac7613d0d42c6dc49f8e4195bd461c824/pkg/storage/replica_protected_timestamp.go#L139)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm still confused. Why are we consulting `r.mu.state.GCThreshold` at all? Isn't this supposed to be picking a new gc theshold, before the replica state has been updated to reflect it?
</blockquote></details>

We consult the current `GCThreshold` to determine whether there are existing records which should be ignored. If a record already does not apply given the current `GCThreshold` then we don't want it to prevent increasing the `GCThreshold` further. See the use of `gcThreshold` in the call to `Iterate`.

**Pull request merged**
