### PR TITLE
storage: avoid timer deadlock in quotaPool + add lint check

### LINKED ISSUE #17524: user cluster has three wedged timeseries ranges
Forked from https://github.com/cockroachdb/cockroach/issues/17478#issuecomment-321046079.

We have access to this cluster via a Cisco WebEx session (you'll need a chrome plugin) at a meeting link that can be activated by Gitter user @HeikoOnnebrink (he'll supervise while you are connected).

It's a 9node cluster running inside of Docker on CoreOS. I've only looked more closely at r104 (see Archive.zip below), which stopped working on 7/31 and then saw some more activity on 8/3: The problematic member here is node1. In grepping the logs, I saw that node1 briefly got the lease on 7/31. The next activity is on 8/3, when it receives 3-4 snapshots including almost no log entries.

There are two other ranges that are perhaps not comparable. In particular, one of the two has a 120mb raft log.

I have no bandwidth to investigate this further. It's fairly tedious due to the remote connection and the fact that this is a 9node cluster. Still, we should follow through and gather what we can. I tried to enable lower-level raft logging via access to /debug/vmodule/raft=8 but somehow it didn't work. That plus grep for `r104/` should turn up *something*.

Inlined my initial investigation comment below:
> 
> > I should also mention that the reason node 5 is unwilling to become raft leader is because it doesn't have an entry for itself in its own progress map (prs map[uint64]*Progress), which make it un-"promotable". This seems pretty surprising, but I'm not familiar with the expectations for it.
>
> I thought the `Progress` is only populated *on* the Raft leader. Which piece of code are you talking about?
>
> I'm currently looking at a user's cluster who also lost his timeseries ranges. Data attached.
>
> There's definitely a problem with the quota pool on that cluster. @irfansharif, any thoughts on the below? It might be an artifact of the ranges being horked, which the attached range pages can hopefully illustrate.
[Archive.zip](https://github.com/cockroachdb/cockroach/files/1209223/Archive.zip)

```
goroutine 35976949 [chan receive, 6999 minutes]:
github.com/cockroachdb/cockroach/pkg/util/timeutil.(*Timer).Reset(0xc422777740, 0xdf8475800)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/timeutil/timer.go:89 +0x9f
github.com/cockroachdb/cockroach/pkg/storage.(*quotaPool).acquire(0xc420e88c30, 0x7fbd9cbebff8, 0xc420e5c3f0, 0x23b, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/quota_pool.go:198 +0x69a
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).maybeAcquireProposalQuota(0xc420441180, 0x7fbd9cbebff8, 0xc420e5c3f0, 0x23b, 0x8, 0x14d7740974383c7f)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:899 +0xd9
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).propose(0xc420441180, 0x7fbd9cbebff8, 0xc420e5c3f0, 0x14d76b9159239640, 0x0, 0x0, 0x0, 0x700000007, 0xc, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2817 +0x69c
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).tryExecuteWriteBatch(0xc4204
```

### PR DESCRIPTION
**Pull request by nvb**
Maybe fixes #17524.

When a `timeutil.Timer` is read from, it needs to set `timer.Read = true`
before calling `timer.Reset` or it risks deadlocking itself. A deadlock
in the `quotaPool` was possible because it missed this step. Once the
`quotaPool` deadlocked, it would block the `CommandQueue` and wreak havoc
on a cluster.

To prevent against this happening again, this change adds a new lint check that
assures that `timeutil.Timer` is used correctly.

> checkSetTimeutilTimerRead assures that timeutil.Timer objects are used
> correctly, to avoid race conditions and deadlocks. These timers require
> callers to set their Read field to true when their channel has been received
> on. If this field is not set and the timer's Reset method is called, we will
> deadlock. This lint assures that the Read field is set in the most common
> case where Reset is used, within a for-loop where each iteration blocks
> on a select statement. The timers are usually used as timeouts on these
> select statements, and need to be reset after each iteration.
>
> ```
> for {
>   timer.Reset(...)
>   select {
>     case <-timer.C:
>       timer.Read = true   <--  lint verifies that this line is present
>     case ...:
>   }
> }
> ```

Note that the lint is triggered even if `Reset` is not present in each iteration.
Even though this case will not deadlock without the `timer.Read = true`, I
think it's safer to mandate that all select cases set the `Read` flag anyway.
This prevents against issues calling `Reset` sometime after the `for` loop, which
could still deadlock.

@tschottdorf for the first commit, @tamird for the second.

### CODE REVIEW

**Comment by tschottdorf** [comment]
Wow, nice lint! LGTM, but @tamird should probably take a look at your AST craziness as well. Either way, hope we can merge this tomorrow.

---

Reviewed 1 of 1 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/cmd/metacheck/main.go, line 160 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17796#-Ks6TwRHnJz_qgWGFo5y:-Ks6TwRHnJz_qgWGFo5z:b-fypw96) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee4b01b7df26664c400edd2425e9208b616828e7/pkg/cmd/metacheck/main.go#L160)):*
> ```Go
> 	selectorIsTimer := func(s *ast.SelectorExpr) bool {
> 		typ := j.Program.Info.TypeOf(s.X).String()
> 		return strings.HasSuffix(typ, "pkg/util/timeutil.Timer")
> ```

This is silly, but if we renamed that package, your lint would silently fail, right? Can we somehow import that package to make sure we explode if we move it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17796#-:-Ks6UNFrDaNujj5Z3GKI:boq4hcx)*

**Comment by petermattis** [comment]
:lgtm: Nice catch. I didn't look at the lint check, but even trying to add one is going above and beyond.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/storage/quota_pool.go, line 147 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17796#-Ks6V8gydqy0ilM-D4ho:-Ks6V8gydqy0ilM-D4hp:bu7hu99) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee4b01b7df26664c400edd2425e9208b616828e7/pkg/storage/quota_pool.go#L147)):*
> ```Go
> 
> 	for {
> 		slowTimer.Reset(base.SlowRequestThreshold)
> ```

Is there a reason you moved this `Reset` inside the loop? Ditto for the one below. That will make the loop warning multiple times which I don't think is desirable. Or maybe it is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17796#-:-Ks6VLmLqcVo43eCdIZi:bg0z89h)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/quota_pool.go, line 147 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17796#-Ks6V8gydqy0ilM-D4ho:-Ks6YB-5lSDz9K9fYcuq:b-9ioobv) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee4b01b7df26664c400edd2425e9208b616828e7/pkg/storage/quota_pool.go#L147)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is there a reason you moved this `Reset` inside the loop? Ditto for the one below. That will make the loop warning multiple times which I don't think is desirable. Or maybe it is.
</blockquote></details>

I think it is desirable. We were staring at logs today that had zero activity and we had to grep through the history to figure out if there was ever a message. Starting to repetitively log loads of messages here has its own problems, but we should work really hard to never get into that state. Since each of these repetitive messages would be bound to a client's context, I think we should try this out.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17796)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/quota_pool.go, line 147 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17796#-Ks6V8gydqy0ilM-D4ho:-Ks6ZBbiHjBGVN6O7Svy:b-6v6nzf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee4b01b7df26664c400edd2425e9208b616828e7/pkg/storage/quota_pool.go#L147)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

I think it is desirable. We were staring at logs today that had zero activity and we had to grep through the history to figure out if there was ever a message. Starting to repetitively log loads of messages here has its own problems, but we should work really hard to never get into that state. Since each of these repetitive messages would be bound to a client's context, I think we should try this out.
</blockquote></details>

Ok, maybe we should change the other `slowTimers` for consistency.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17796)*

**Comment by nvanbenschoten** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/cmd/metacheck/main.go, line 160 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17796#-Ks6TwRHnJz_qgWGFo5y:-Ks7H7AR58zvbp1EyDPL:b-bhg5v2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee4b01b7df26664c400edd2425e9208b616828e7/pkg/cmd/metacheck/main.go#L160)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

This is silly, but if we renamed that package, your lint would silently fail, right? Can we somehow import that package to make sure we explode if we move it?
</blockquote></details>

Good point. @tamird, is there a standard way we've addressed this in the past?

---

*[pkg/storage/quota_pool.go, line 147 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17796#-Ks6V8gydqy0ilM-D4ho:-Ks7GmzZMFdK03w_KU-l:bdelzr0) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee4b01b7df26664c400edd2425e9208b616828e7/pkg/storage/quota_pool.go#L147)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Ok, maybe we should change the other `slowTimers` for consistency.
</blockquote></details>

It was already inside the loop, just in the `<-slowTimer.C` case body instead of directly in the for loop, so this shouldn't change behavior. Moving it up just makes it consistent with other places where we want multiple warnings.

The other three instances of slow timers are in:
- `DistSender.sendToReplicas`
- `Replica.redirectOnOrAcquireLease`
- `Replica.tryExecuteWriteBatch`

As you point out, none of these warn multiple times. These should probably be consistent with `quotaPool.acquire`, but I'm wary of introducing log spam that could clutter the logs even further. That said, the timers should only go off once a minute. You two have probably spent the most time debugging issues by looking at logs, so I'll defer to your judgment.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17796)*

**Comment by tamird** [comment]
:lgtm: nice job!

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/cmd/metacheck/main.go, line 160 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17796#-Ks6TwRHnJz_qgWGFo5y:-Ks8bQf_xNRipt8kIfq5:buvbu27) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee4b01b7df26664c400edd2425e9208b616828e7/pkg/cmd/metacheck/main.go#L160)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Good point. @tamird, is there a standard way we've addressed this in the past?
</blockquote></details>

Yep, `go/build.Import` is the standard way to address this; see for instance https://github.com/cockroachdb/cockroach/eebbd7a/master/pkg/cmd/benchmark/main.go#L55

---

*[pkg/cmd/metacheck/main.go, line 195 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17796#-Ks8cxlBhux5xAWmuFOm:-Ks8cxlBhux5xAWmuFOn:by3mnf7) ([raw file](https://github.com/cockroachdb/cockroach/blob/631aa799750a32f0ade65fc8e5d86933bb25d61a/pkg/cmd/metacheck/main.go#L195)):*
> ```Go
> 				}
> 				selectorName := fmt.Sprint(selector.X)
> 				if selector.Sel.String() != "C" {
> ```

this will also silently break if the name of this field changes. probably fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17796#-:-Ks8bcnPJ-WGVcjLxfRU:bxpgx20)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/cmd/metacheck/main.go, line 160 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17796#-Ks6TwRHnJz_qgWGFo5y:-Ks8dShXTSXvEXq-BHZD:b-mi2wfi) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee4b01b7df26664c400edd2425e9208b616828e7/pkg/cmd/metacheck/main.go#L160)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Yep, `go/build.Import` is the standard way to address this; see for instance https://github.com/cockroachdb/cockroach/eebbd7a/master/pkg/cmd/benchmark/main.go#L55
</blockquote></details>

Oh, and I imagine you can use reflection to confirm the type name (and the field name, "C", below).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17796)*

**Comment by nvanbenschoten** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/cmd/metacheck/main.go, line 160 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17796#-Ks6TwRHnJz_qgWGFo5y:-KsABqI9kn_rhcngfmlm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee4b01b7df26664c400edd2425e9208b616828e7/pkg/cmd/metacheck/main.go#L160)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Oh, and I imagine you can use reflection to confirm the type name (and the field name, "C", below).
</blockquote></details>

Done.

---

*[pkg/cmd/metacheck/main.go, line 195 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17796#-Ks8cxlBhux5xAWmuFOm:-KsABqnRfGBQzVK0VmYz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/631aa799750a32f0ade65fc8e5d86933bb25d61a/pkg/cmd/metacheck/main.go#L195)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this will also silently break if the name of this field changes. probably fine.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17796)*

**Comment by tamird** [comment]
Reviewed 2 of 3 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17796)*

**Pull request merged**
