### PR TITLE
release-21.1: roachprod: backport changes from 21.2

### PR DESCRIPTION
**Pull request by RaduBerinde**
This PR attempts to backport all roachprod commits from 21.2 onto 21.1.  This will allow larger changes from master to be backported all the way to 21.1.

Some of the commits were modifying things outside of roachprod; those were "trimmed" to just the roachprod part.

The biggest manual change was avoiding the use of `go:embed` which is not available in the go version used by 21.1.

### CODE REVIEW

**Comment by tbg** [comment]
What kind of review would you like here? I've scanned the list of commits and it looks fine; reviewing them in any detail is likely not what we need here. The build is currently red:

```
pkg/server/status.go:1811:21: not enough arguments in call to rep.State
	have ()
	want (context.Context)
```

(and perhaps others). From my POV, this is good to go if you can get it to pass CI plus a real-cluster roachtest of your choosing.

**Review by tbg — APPROVED** [review]
A bit of rationale would also be nice. 21.1 is not really seeing much activity. I assume your interest here has something to do with serverless upgrade path testing.

**Comment by RaduBerinde** [comment]
@jlinder can say more about the rationale. My understanding is that we are making significant changes in roachprod and roachtest on master, and if we don't backport those, it will be hard to backport any important future roachtest fix/improvement. Maybe this trade-off is not worth it, at least for 21.1?

**Comment by rail** [comment]
This is very scary! :D I scrolled the diff and it contains sooooooo many changes that can affect other parts of the system... Changes to `/pkg/server` make me especially nervous. :) If those are ok to backport, we just need to fix the CI builds.

**Comment by RaduBerinde** [comment]
Yes I agree on the `server` changes, those shouldn't have been backported. I fixed that backport to only include the small change to roachprod. I still need to review all changes more carefully and run some tests.

I don't like backporting all this stuff either and starting to believe it's not worth it just so any potential roachtest fixes can be backported without reworking. I defer to @jlinder though.

**Comment by jlinder** [comment]
> @jlinder can say more about the rationale. My understanding is that we are making significant changes in roachprod and roachtest on master, and if we don't backport those, it will be hard to backport any important future roachtest fix/improvement. Maybe this trade-off is not worth it, at least for 21.1?

That is correct that we are making significant changes to roachprod and roachtest. Specifically, the new roachprod library is being integrated into roachtest which will introduce a lot of changes related to interactions with roachprod.

Some data. Between 21.1.0 and 21.1.11, there were 70 commits containing changes to `pkg/cmd/roachtest`. Backporting of roachtest changes has certainly slowed down in the last couple months (the last changes were 4, 5, and 6 weeks ago). There's 6 months left in that release series. 

Given the backport rate slows down over time, maybe there will be 5-20 commits backported in that time frame? (We certainly won't have 70.) And maybe half of them would need some reworking (given )? So maybe 10 at most commits would need some tweaking and maybe two would need a lot?

That's a low number of possible affected commits. Lower than I thought they'd be. I'm OK if we don't follow through on getting this PR merged for 21.1. (Though I do think 21.2 should be updated since a lot more backports would likely be affected.)

**Comment by RaduBerinde** [comment]
Ok, I am closing this. I agree on keeping 21.2 updated (that is much more straightforward though).

**Pull request closed without merging**
