### PR TITLE
sql: support max/min aggregates on collated strings

### LINKED ISSUE #45846: sql: max/min aggregates don't work with collated strings
Repro:
```
root@:26257/defaultdb> SELECT max(x) FROM (VALUES ('foo' COLLATE en), ('bar' COLLATE en)) t(x);
ERROR: unknown signature: max(collatedstring{en})
```
EXPECTED: This should work; it does in PG.

### LINKED ISSUE #46685: sql: Unexpected error while using min/max for collated string.
Unexpected error while using min/max for the collated string.
```
root@localhost:26257/defaultdb> CREATE TABLE de_names (name STRING COLLATE de PRIMARY KEY);
CREATE TABLE
Time: 21.184268ms
root@localhost:26257/defaultdb> INSERT INTO de_names VALUES ('Backhaus' COLLATE de), ('Bär' COLLATE de), ('Baz' COLLATE de);
INSERT 3
Time: 16.182031ms
root@localhost:26257/defaultdb> SELECT max(name) FROM de_names;
  max
-------
  Baz
(1 row)
Time: 1.684005ms
root@localhost:26257/defaultdb> SELECT max(name), min(name) FROM de_names;
ERROR: internal error: error decoding 5 bytes: failed to parse locale "": language: tag is not well-formed
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/sql/sem/tree/datum.go:1213: getCacheEntry()
github.com/cockroachdb/cockroach/pkg/sql/sem/tree/datum.go:1228: NewDCollatedString()
github.com/cockroachdb/cockroach/pkg/sql/sqlbase/column_type_encoding.go:466: decodeUntaggedDatum()
github.com/cockroachdb/cockroach/pkg/sql/sqlbase/column_type_encoding.go:436: DecodeTableValue()
github.com/cockroachdb/cockroach/pkg/sql/sqlbase/encoded_datum.go:226: EnsureDecoded()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:730: Push()
github.com/cockroachdb/cockroach/pkg/sql/rowflow/row_based_flow.go:429: Push()
github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:173: Run()
github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:749: Run()
github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:370: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:405: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1019: PlanAndRun()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:878: execWithDistSQLEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:771: dispatchToExecutionEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:476: execStmtInOpenState()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:95: execStmt()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1368: execCmd()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1297: run()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:476: ServeConn()
github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:594: func1()
/snap/go/5569/src/runtime/asm_amd64.s:1373: goexit()
HINT: You have encountered an unexpected error.
Please check the public issue tracker to check whether this problem is
already tracked. If you cannot find it there, please report the error
with details by creating a new issue.
If you would rather not post publicly, please contact us directly
using the support form.
We appreciate your feedback.
```
hard to reproduce this error directly.

But can be generated by adding test cases,
as in `pkg/sql/logictest/testdata/logic_test/aggregate`
added folling testcase:
```
subtest testing

statement ok
CREATE TABLE de_names (name STRING COLLATE de PRIMARY KEY)

statement ok
INSERT INTO de_names VALUES ('Backhaus' COLLATE de), ('Bär' COLLATE de), ('Baz' COLLATE de)

query TT
SELECT max(name), min(name) FROM de_names
----
Baz Backhaus

statement ok
DROP TABLE de_names
```

for `make test PKG=./pkg/sql/logictest  TESTS=TestLogic/local/aggregate/testing  TESTFLAGS="-v -show-logs"` all the test case passed.
but for `make test PKG=./pkg/sql/logictest  TESTS=TestLogic/.*/aggregate/testing TESTFLAGS="-v -show-logs"` I was able to reproduce the same error.

### PR DESCRIPTION
**Pull request by rohany**
Fixes #45846.
Fixes #46685.

This PR allows for performing the max/min aggregations on collated
strings. Currently, our aggregates would not support container types
like `AnyCollatedString`. This PR extends the aggregates infrastructure
in DistSQL that caused the limitation to allow for container types,
which unblocks #48370.

Release note (sql change): Support the max/min aggregations on collated
strings.

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49530#-:-M8GrVsg-rGRztkixBNg:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @rohany)

___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 239 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49530#-M8Gqvlz-2JsQfzUWxuP:-M8Gqvm-AeDQ6rYM9bc3:b-oklqh3) ([raw file](https://github.com/cockroachdb/cockroach/blob/9afee91db96611569ad6dd0c36b6452983074320/pkg/sql/sem/builtins/aggregate_builtins.go#L239)):*
> ```Go
> 				)
> 			}
> 			return makeAggOverload([]*types.T{t}, t, newMinAggregate, info, tree.VolatilityImmutable)
> ```

nit: `s/tree.VolatilityImmutable/vol/g`.

**Comment by rohany** [comment]
tftr!

bors r=yuzefovich

**Pull request merged**
