### PR TITLE
sql: fix inconsistent lock ordering

### PR DESCRIPTION
**Pull request by tamird**
Spotted in https://circleci.com/gh/tamird/cockroach/304.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8019)

### CODE REVIEW

**Comment by tschottdorf** [comment]
The diff :lgtm: with a question.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/lease.go, line 861 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8019#-KNc2d27R1ihoZR0jSY_:-KNc2d27R1ihoZR0jSYa:658697333) ([raw file](https://github.com/cockroachdb/cockroach/blob/93af0cec87948b793b8d5237dd1004c8f9681bd4/sql/lease.go#L861)):*
> ```Go
> 		return nil
> 	}
> 	lease.mu.Lock()
> ```

I don't know this part of the code very well, but is it problematic that now both `c` and the lease are unlocked for a short moment just above?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8019#-:-KNc2tS5Ah1fBOdA8Uc-:2043034396)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/lease.go, line 861 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8019#-KNc2d27R1ihoZR0jSY_:-KNc7OEmmfnlmnr3N4FQ:-1142644016) ([raw file](https://github.com/cockroachdb/cockroach/blob/93af0cec87948b793b8d5237dd1004c8f9681bd4/sql/lease.go#L861)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> I don't know this part of the code very well, but is it problematic that now both `c` and the lease are unlocked for a short moment just above?
</details>
TBH, I don't know either. I don't think so, but doesn't hurt to ask @andreimatei.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8019)*

**Comment by vivekmenezes** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/lease.go, line 856 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8019#-KNcL5Ekxa92luNX-SyE:-KNcL5Ekxa92luNX-SyF:1172265811) ([raw file](https://github.com/cockroachdb/cockroach/blob/93af0cec87948b793b8d5237dd1004c8f9681bd4/sql/lease.go#L856)):*
> ```Go
> ) *LeaseState {
> 	c.mu.Lock()
> 	lease, ok := c.tables[makeTableNameCacheKey(dbID, tableName)]
> ```

call makeTableNameCahceKey() outside the lock

---

*[sql/lease.go, line 861 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8019#-KNc2d27R1ihoZR0jSY_:-KNcK_ywFlnNjsnypgdC:-222652066) ([raw file](https://github.com/cockroachdb/cockroach/blob/93af0cec87948b793b8d5237dd1004c8f9681bd4/sql/lease.go#L861)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> TBH, I don't know either. I don't think so, but doesn't hurt to ask @andreimatei.
</details>
You do not need to pull the lock up here and can leave it where it is where it protects released and the refcount. This is a safe change because after holding the lock you do check if the lease has been released before incrementing the ref count, so you never hand out a bad lease. nice one!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8019#-:-KNcL2zOj1HMBqEzGmWE:1417088721)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/lease.go, line 856 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8019#-KNcL5Ekxa92luNX-SyE:-KNcOCq-yG3anHazMB0W:1480516046) ([raw file](https://github.com/cockroachdb/cockroach/blob/93af0cec87948b793b8d5237dd1004c8f9681bd4/sql/lease.go#L856)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> call makeTableNameCahceKey() outside the lock
</details>
doesn't seem worth it.

---

*[sql/lease.go, line 861 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8019#-KNc2d27R1ihoZR0jSY_:-KNcO9_MAOe2Bh-TJonC:-1499398692) ([raw file](https://github.com/cockroachdb/cockroach/blob/93af0cec87948b793b8d5237dd1004c8f9681bd4/sql/lease.go#L861)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> You do not need to pull the lock up here and can leave it where it is where it protects released and the refcount. This is a safe change because after holding the lock you do check if the lease has been released before incrementing the ref count, so you never hand out a bad lease. nice one!
</details>
Any harm in moving it up here? gonna assume no and merge.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8019)*

**Pull request merged**
