### PR TITLE
jobs, server: add mutable 'execution status' to registered jobs

### PR DESCRIPTION
**Pull request by dt**
This extends the state tracked in the jobs registry to include a mutable 'execution status' field,
in addition to the current cancel function it tracks for each job it is running.

This execution status is a map of proccessors that are doing work on behalf of
this job, with each processor having one or more tasks that can each updaate
their own status. This structure is intended to make it easier to tracck the
status of the many components of job distributed across remtoe processoors,
though a job that simply runs one task in its resume function could choose
to simply set the status of a e.g. 'main' task in processor 0.

Actually reporting status in individual tasks and collecting that information
from remote processors is still the responsibility of an individual job
implementation -- what this change does is give that job somewhere to put
that collection status information that is then surfaced in a debugging
endpoint in the status server.

Release note: none.

### CODE REVIEW

**Review by pbardea — APPROVED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50983)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/jobs/jobs.go, line 141 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50983#-MBWOvt-2eEeoO7Qn6r0:-MBWOvt-2eEeoO7Qn6r1:bu3f85g) ([raw file](https://github.com/cockroachdb/cockroach/blob/c10221f4878f9e8a60897985b7ed2118db015e39/pkg/jobs/jobs.go#L141)):*
> ```Go
> }
> 
> // Processor gets or creates the mutable stutus tracker for a processor in this
> ```

stutus -> status
___
*[pkg/jobs/jobs.go, line 157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50983#-MBWUOONCj9azwzd07RS:-MBWUOONCj9azwzd07RT:b-ap1gtc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c10221f4878f9e8a60897985b7ed2118db015e39/pkg/jobs/jobs.go#L157)):*
> ```Go
> 	Status            string
> 	LastUpdatedMicros int64
> 	Details           interface{}
> ```

How are these details going to be exposed/used? Would it be useful if instead of interface they implemented some interface that provided a description of their details that could be reported back to the endpoint.
___
*[pkg/server/status.go, line 2117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50983#-MBWQVGjBCtWtwzZLJm5:-MBWQVGjBCtWtwzZLJm6:b-7bcvh2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c10221f4878f9e8a60897985b7ed2118db015e39/pkg/server/status.go#L2117)):*
> ```Go
> 					})
> 				}
> ```

nit: extra newline

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50983)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @pbardea)

___
*[pkg/jobs/jobs.go, line 157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50983#-MBWUOONCj9azwzd07RS:-MBZCJzBEO3JBg6u9qUn:b4ii7r) ([raw file](https://github.com/cockroachdb/cockroach/blob/c10221f4878f9e8a60897985b7ed2118db015e39/pkg/jobs/jobs.go#L157)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

How are these details going to be exposed/used? Would it be useful if instead of interface they implemented some interface that provided a description of their details that could be reported back to the endpoint.
</blockquote></details>

Hmm, good point. I have a usage follow-up but it only sets the string above. 

I was imagining this field would be a task-specific proto in many cases, but in that case maybe a proto.message or something would be more appropriate than interface{}?

Could also just remove this until the actual structured status follow-up adds it instead of trying to do something speculative.

**Review by miretskiy — COMMENTED** [review]
nit: Few typos in the description (tracck, remtoe, etc)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50983#-:-MBZQcjJ8s4RENrADFp2:b-wvy0wu)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @pbardea)

___
*[pkg/jobs/jobs.go, line 156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50983#-MBZRHgiAyG29jLM78_p:-MBZRHgiAyG29jLM78_q:byfmgpn) ([raw file](https://github.com/cockroachdb/cockroach/blob/c10221f4878f9e8a60897985b7ed2118db015e39/pkg/jobs/jobs.go#L156)):*
> ```Go
> type ProcessorTaskStatus struct {
> 	Status            string
> 	LastUpdatedMicros int64
> ```

why not time.Time?
___
*[pkg/server/status.go, line 2141 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50983#-MBZSPtzA9cVC4aoTmb8:-MBZSPtzA9cVC4aoTmb9:bu7h2eb) ([raw file](https://github.com/cockroachdb/cockroach/blob/c10221f4878f9e8a60897985b7ed2118db015e39/pkg/server/status.go#L2141)):*
> ```Go
> 		resp.RunningJobs = append(resp.RunningJobs, &job)
> 	}
> 	sort.Slice(resp.RunningJobs, func(i, j int) bool { return resp.RunningJobs[i].Id < resp.RunningJobs[j].Id })
> ```

nit: wrap long line?

**Review by pbardea — APPROVED** [review]

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50983)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @pbardea)

___
*[pkg/jobs/jobs.go, line 141 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50983#-MBWOvt-2eEeoO7Qn6r0:-MBg1PhrBSc5778-D7UB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c10221f4878f9e8a60897985b7ed2118db015e39/pkg/jobs/jobs.go#L141)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

stutus -> status
</blockquote></details>

Done.
___
*[pkg/jobs/jobs.go, line 156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50983#-MBZRHgiAyG29jLM78_p:-MBg3o2s3oqnvxkM_D7S:b-g6bxan) ([raw file](https://github.com/cockroachdb/cockroach/blob/c10221f4878f9e8a60897985b7ed2118db015e39/pkg/jobs/jobs.go#L156)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

why not time.Time?
</blockquote></details>

we use `fooMicros` pretty extensively already, including for similar fields in the `jobs` package.  This is usually because it is easy to (de)serialize in proto messages as a single int64. Furthermore, microsecond is level of precision supported by default in postgres' timestamp types, so when we surface times in SQL, any additional precision is pointless (and often even harmful when it breaks equality).

**Review by tbg — COMMENTED** [review]
I wonder if down the road this approach could use tracing. Instead of a `map[int32]*ProcessorStatus`, you'd have a span per processor (I guess you wouldn't even need to hold on to the spans here, all you'd need to discover the children is the trace's ID). Processors could use https://github.com/cockroachdb/cockroach/issues/60997 to attach ephemeral information and payloads to the trace which could be surfaced via https://github.com/cockroachdb/cockroach/issues/60999.

When https://github.com/cockroachdb/cockroach/issues/59188 is addressed, long-running spans (when used discreetly, one per job should be fine!) should not be an issue, allowing this possible use case.

cc @andreimatei who's also an observability stan

**Pull request closed without merging**
