### PR TITLE
opt: Add various constant folding normalization patterns

### PR DESCRIPTION
**Pull request by andy-kimball**
This PR adds a number of scalar constant folding patterns:

- Null folding
- Arithmetic 0 and 1 folding
- Coalesce simplification

In order to do correct null folding, it was necessary to add a typed Null
operator. All patterns are required to preserve the data type of the input
expression, and this was not possible when replacing with a Null that
always had the unknown type. The null operator keeps its static type as
a private so that type inference after pattern replacement yields the same
type.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Looks like there's an `interface conversion: types.tUnknown is not tree.TypedExpr` crash in `execbuilder.(*Builder).buildTypedExpr`.

BTW I usually run `make test PKG=./pkg/sql/opt/...` on every opt change.

---

Review status: 0 of 33 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/sql/opt/ops/scalar.opt, line 32 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23337#-L6fs1Om7Qrh5HQXYhfJ:-L6fs1OnClJ_lSsaKHwF:b12ceku) ([raw file](https://github.com/cockroachdb/cockroach/blob/79919611a9270a15c8890799b57ba2d6232dd9a5/pkg/sql/opt/ops/scalar.opt#L32)):*
> ```
> # Null is the constant SQL null value that has "unknown value" semantics. If
> # the Typ field is not types.Unknown, then the value is known to be in the
> # domain of that type. This is important for preesrving correct types in
> ```

preserving

---

*[pkg/sql/opt/ops/scalar.opt, line 39 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23337#-L6fs6r_-Rx7916bXvyM:-L6fs6r_-Rx7916bXvyN:b-fhccmz) ([raw file](https://github.com/cockroachdb/cockroach/blob/79919611a9270a15c8890799b57ba2d6232dd9a5/pkg/sql/opt/ops/scalar.opt#L39)):*
> ```
> # constant folded to (Null), then its type must remain as Int. Any other type
> # violates logical equivalence of the expression, breaking type inference and
> # possibly changing the results of execution. The solution is to use tag the
> ```

"to use tag the null"

---

*[pkg/sql/opt/xform/factory.go, line 197 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23337#-L6fuB_aE4IfdoktgxhR:-L6fuB_aE4IfdoktgxhS:biuz6dd) ([raw file](https://github.com/cockroachdb/cockroach/blob/79919611a9270a15c8890799b57ba2d6232dd9a5/pkg/sql/opt/xform/factory.go#L197)):*
> ```Go
> 
> // simplifyAnd removes True operands from an And operator, and eliminates the
> // And operator altogether if any operands is False. If, after simplification,
> ```

any operand or any of the operands

---

*[pkg/sql/opt/xform/factory.go, line 222 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23337#-L6fuEiQ6DxbrqTfKxNM:-L6fuEiQ6DxbrqTfKxNN:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/79919611a9270a15c8890799b57ba2d6232dd9a5/pkg/sql/opt/xform/factory.go#L222)):*
> ```Go
> 
> // simplifyOr removes False operands from an Or operator, and eliminates the
> // Or operator altogether if any operands is True. If, after simplification,
> ```

ditto

---

*[pkg/sql/opt/xform/rules/bool.opt, line 6 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23337#-L6fucRc-1yoKSS5spi1:-L6fucRc-1yoKSS5spi2:b-lg8uwf) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd6ac32d5656ff8d7110028fdcf20841107c4d1f/pkg/sql/opt/xform/rules/bool.opt#L6)):*
> ```
> 
> 
> # EliminateAnd discards the And operator if any of its operands is false.
> ```

These rules are now implemented by SimplifyOr/And right? Should we also implement EliminateSingletonAnd/Or in that same function? (actually, we don't have EliminateSingletonAnd yet)

---

*[pkg/sql/opt/xform/rules/bool.opt, line 29 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23337#-L6fuLNIAPZzg8wOuxob:-L6fuLNIAPZzg8wOuxoc:b-c7sk5z) ([raw file](https://github.com/cockroachdb/cockroach/blob/79919611a9270a15c8890799b57ba2d6232dd9a5/pkg/sql/opt/xform/rules/bool.opt#L29)):*
> ```
> 
> # SimplifyAnd removes True children of an And. If all children are True,
> # replaces the And node with True.
> ```

If any child is False, replaces the And node with False.

---

*[pkg/sql/opt/xform/rules/bool.opt, line 39 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23337#-L6fuO3gE_8ZtNgjiIW1:-L6fuO3gE_8ZtNgjiIW2:b-hxm3nv) ([raw file](https://github.com/cockroachdb/cockroach/blob/79919611a9270a15c8890799b57ba2d6232dd9a5/pkg/sql/opt/xform/rules/bool.opt#L39)):*
> ```
> 
> # SimplifyOr removes False children of an Or. If all children are False,
> # replaces the Or node with False.
> ```

If any child is True, replaces the Or node with True.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23337#-:-L6ftcwO6bNC-XaeB9p9:bsi5wi1)*

**Comment by andy-kimball** [comment]
Yeah, I usually do as well, but forgot this time.

---

Review status: 0 of 33 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/ops/scalar.opt, line 32 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23337#-L6fs1Om7Qrh5HQXYhfJ:-L6g-SHM7uTD53jdHH6I:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/79919611a9270a15c8890799b57ba2d6232dd9a5/pkg/sql/opt/ops/scalar.opt#L32)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

preserving
</blockquote></details>

Done.

---

*[pkg/sql/opt/ops/scalar.opt, line 39 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23337#-L6fs6r_-Rx7916bXvyM:-L6g-WjA-M1o6xmKaik3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/79919611a9270a15c8890799b57ba2d6232dd9a5/pkg/sql/opt/ops/scalar.opt#L39)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

"to use tag the null"
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/factory.go, line 197 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23337#-L6fuB_aE4IfdoktgxhR:-L6g-igHEthE0hnsPuyH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/79919611a9270a15c8890799b57ba2d6232dd9a5/pkg/sql/opt/xform/factory.go#L197)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

any operand or any of the operands
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/factory.go, line 222 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23337#-L6fuEiQ6DxbrqTfKxNM:-L6g-jIR739NaQ44nMqB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/79919611a9270a15c8890799b57ba2d6232dd9a5/pkg/sql/opt/xform/factory.go#L222)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/rules/bool.opt, line 6 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23337#-L6fucRc-1yoKSS5spi1:-L6g-lgQ7KyV9X_WGd_2:b-qtoa3h) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd6ac32d5656ff8d7110028fdcf20841107c4d1f/pkg/sql/opt/xform/rules/bool.opt#L6)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

These rules are now implemented by SimplifyOr/And right? Should we also implement EliminateSingletonAnd/Or in that same function? (actually, we don't have EliminateSingletonAnd yet)
</blockquote></details>

The reason I put `EliminateAnd` into `SimplifyAnd` is that is that the patterns were almost the same (`True` vs. `False`), and I could save an iteration over the children while still retaining a clean-looking pattern by using `True | False`. But `EliminateSingletonAnd` is a different case, since it doesn't require iteration (can just check `ListID.Length`), and it doesn't syntactically combine well with this other pattern.

---

*[pkg/sql/opt/xform/rules/bool.opt, line 29 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23337#-L6fuLNIAPZzg8wOuxob:-L6g1bP47yUFB9CVGFaw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/79919611a9270a15c8890799b57ba2d6232dd9a5/pkg/sql/opt/xform/rules/bool.opt#L29)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

If any child is False, replaces the And node with False.
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/rules/bool.opt, line 39 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23337#-L6fuO3gE_8ZtNgjiIW1:-L6g1boI7HeWJLFVdlhB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/79919611a9270a15c8890799b57ba2d6232dd9a5/pkg/sql/opt/xform/rules/bool.opt#L39)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

If any child is True, replaces the Or node with True.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23337#-:-L6g1ehx7pYaDClNMH4c:beaz9se)*

**Comment by RaduBerinde** [comment]
:lgtm:  Very nice!

---

Review status: 0 of 34 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/sql/opt/xform/testdata/rules/scalar, line 122 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23337#-L6hBZIQ3gw1WCzJPzJM:-L6hBZIQ3gw1WCzJPzJN:b-tcnkom) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e437bb1291a1cd2a57fe0c6d8193dc9b1e8ce4d/pkg/sql/opt/xform/testdata/rules/scalar#L122)):*
> ```
>     i::decimal || null, null || i::float
> FROM a
> ```

[nit] extra line

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23337#-:-L6hBwQ-0OGfd-kMJVFC:b-8ymd1x)*

**Comment by andy-kimball** [comment]
Review status: 0 of 34 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/opt/xform/testdata/rules/scalar, line 122 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23337#-L6hBZIQ3gw1WCzJPzJM:-L6hNYikDurDByQ4DIex:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e437bb1291a1cd2a57fe0c6d8193dc9b1e8ce4d/pkg/sql/opt/xform/testdata/rules/scalar#L122)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] extra line
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23337)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 22 of 33 files at r1, 11 of 12 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/xform/rules/comp.opt, line 32 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23337#-L6qZDt7UZStHlq6uFvJ:-L6qZDt7UZStHlq6uFvK:b13p7ib) ([raw file](https://github.com/cockroachdb/cockroach/blob/17b880d28ae1bdbcf61778b20f9c267ab74bfbd9/pkg/sql/opt/xform/rules/comp.opt#L32)):*
> ```
> [FoldNullComparisonLeft, Normalize]
> (Eq | Ne | Ge | Gt | Le | Lt | Like | NotLike | ILike | NotILike | SimilarTo |
>     NotSimilarTo | RegMatch | NotRegMatch | RegIMatch | NotRegIMatch
> ```

Why not use a Comparison tag?
Also, don't you need a * for the right operand?

---

*[pkg/sql/opt/xform/testdata/rules/bool, line 86 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23337#-L6q_oGtasZoRb7BiPOD:-L6q_oGtasZoRb7BiPOE:bi7xzpg) ([raw file](https://github.com/cockroachdb/cockroach/blob/17b880d28ae1bdbcf61778b20f9c267ab74bfbd9/pkg/sql/opt/xform/testdata/rules/bool#L86)):*
> ```
> 
> # --------------------------------------------------
> # SimplifyAnd
> ```

Should this be SimplifyAnd + EliminateSingletonAnd to be consistent with the comment for Or below?

---

*[pkg/sql/opt/xform/testdata/rules/scalar, line 120 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23337#-L6qbK9jT_oqsQNk0LTP:-L6qbK9jT_oqsQNk0LTQ:bhu5c8t) ([raw file](https://github.com/cockroachdb/cockroach/blob/17b880d28ae1bdbcf61778b20f9c267ab74bfbd9/pkg/sql/opt/xform/testdata/rules/scalar#L120)):*
> ```
>     -- These shouldn't be folded because AllowNullArgs is true for concat with arrays.
>     arr::decimal[] || null, null || arr::string[],
>     i::decimal || null, null || i::float
> ```

What about these? They are not arrays...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23337#-:-L6qbjOCj1umP4mAsS3N:bnfp4nl)*

**Comment by andy-kimball** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/xform/rules/comp.opt, line 32 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23337#-L6qZDt7UZStHlq6uFvJ:-L6qf_YUTyxovogsPwMq:buve52) ([raw file](https://github.com/cockroachdb/cockroach/blob/17b880d28ae1bdbcf61778b20f9c267ab74bfbd9/pkg/sql/opt/xform/rules/comp.opt#L32)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why not use a Comparison tag?
Also, don't you need a * for the right operand?
</blockquote></details>

I can't use Comparison, because this is only a subset of the comparison operators. For example, `Is` and `IsNot` are not part of this list, because their null-handling rules are different.

In terms of matching, you can match the first N arguments if you like, but don't have to match all the way to the end of the argument list. This is what allows (Null) to work, since it has 1 argument (Type), but usually we don't need to match it. That said, I think it would help the clarity of this pattern to add the *, so I made that change.

---

*[pkg/sql/opt/xform/testdata/rules/bool, line 86 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23337#-L6q_oGtasZoRb7BiPOD:-L6qlFFaHbp6dAGaCOa0:b35rpx8) ([raw file](https://github.com/cockroachdb/cockroach/blob/17b880d28ae1bdbcf61778b20f9c267ab74bfbd9/pkg/sql/opt/xform/testdata/rules/bool#L86)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Should this be SimplifyAnd + EliminateSingletonAnd to be consistent with the comment for Or below?
</blockquote></details>

We don't have an `EliminateSingletonAnd` pattern yet.

---

*[pkg/sql/opt/xform/testdata/rules/scalar, line 120 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/23337#-L6qbK9jT_oqsQNk0LTP:-L6qlc6EjVRp650YTI8u:b-n7opeu) ([raw file](https://github.com/cockroachdb/cockroach/blob/17b880d28ae1bdbcf61778b20f9c267ab74bfbd9/pkg/sql/opt/xform/testdata/rules/scalar#L120)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

What about these? They are not arrays...
</blockquote></details>

Concatenating these scalar types with null will match array concat overloads. The only overloads available for decimal concatenation is one in which the decimal is concatenated with an array. I added comment to clarify.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23337)*

**Pull request merged**
