### PR TITLE
roachtest: disable auto table stats on kv/gracefuldraining

### PR DESCRIPTION
**Pull request by aliher1911**
Automatic stats collection can cause workload QPS to change significantly during failover as stats jobs are being preempted. This commit excludes stats and backups from the test to reduce flakiness.

Touches: #106490

Release note: None

### CODE REVIEW

**Review by andrewbaptist — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106596)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @herkolategan, and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/kv.go` line 514 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106596#-N_FMcnm8u5O5LIM3Jqa:-N_FMcnm8u5O5LIM3Jqb:bcd9nfw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea9a4cb014056c5fdd85d193d6ea67f65cb38018/pkg/cmd/roachtest/tests/kv.go#L514)):*
> ```Go
> 		Owner:   registry.OwnerKV,
> 		Cluster: r.MakeClusterSpec(4),
> 		Leases:  registry.EpochLeases,
> ```

Drive-by review. Why did you change back to EpochLeases?

**Review by aliher1911 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106596)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @herkolategan, and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/kv.go` line 514 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106596#-N_FMcnm8u5O5LIM3Jqa:-N_FgZG4BIW0wOv8eGXR:b-a80eq9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea9a4cb014056c5fdd85d193d6ea67f65cb38018/pkg/cmd/roachtest/tests/kv.go#L514)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

Drive-by review. Why did you change back to EpochLeases? 
</blockquote></details>

That is fair point! I was actually following another deflaking PR https://github.com/cockroachdb/cockroach/pull/106379 which is testing similar thing during quiescence. But I will try to rerun tests with expiration leases and see if QPS is noisy or flat.

**Review by aliher1911 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106596)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @herkolategan, and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/kv.go` line 514 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106596#-N_FMcnm8u5O5LIM3Jqa:-N_FmtfG5ZjrmpoglxlI:b-5q8c4t) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea9a4cb014056c5fdd85d193d6ea67f65cb38018/pkg/cmd/roachtest/tests/kv.go#L514)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

That is fair point! I was actually following another deflaking PR https://github.com/cockroachdb/cockroach/pull/106379 which is testing similar thing during quiescence. But I will try to rerun tests with expiration leases and see if QPS is noisy or flat.
</blockquote></details>

So I tried running with expiration based leases and it fails 100% times.

**Comment by andrewbaptist** [comment]
> Previously, aliher1911 (Oleg) wrote…
> So I tried running with expiration based leases and it fails 100% times.

That's not good. For test that do quiescence it makes sense (since we can't quiesce expiration leases), but for a test like this, I don't understand why it would be failing. How does it fail?

**Review by aliher1911 — COMMENTED** [review]
We measure QPS of kv workload and expect it to be above 900 (out of 1000). So with epoch leases and no stats you get consistent 990+. With expiration leases I just got
```
19:42:50 = 996.00
19:43:00 = 993.70
19:43:10 = 991.90
19:43:20 = 994.60
19:43:30 = 994.00
19:43:40 = 995.20
19:43:50 = 992.90
19:44:00 = 992.00
19:44:10 = 996.10
19:44:20 = 994.20
19:44:30 = 940.10
19:44:40 = 776.10
19:44:50 = 999.40
19:45:00 = 996.30
19:45:10 = 993.50
19:45:20 = 994.90
19:45:30 = 993.20
19:45:40 = 994.70
19:45:50 = 992.70
19:46:00 = 992.10
```
which fails at 19:44:40 mark. Not 100% failure rate, but quite frequent.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106596#-:-N_Fpmd99fAFXfscg4nx:b1odjl5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist, @herkolategan, and @renatolabs)

**Comment by andrewbaptist** [comment]
I don't think this PR is needed anymore now that #106490 is merged.

**Pull request closed without merging**
