### PR TITLE
Misc fixes from multi-cpu branch

### PR DESCRIPTION
**Pull request by tamird**
[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3073)

### CODE REVIEW

**Comment by tschottdorf** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[gossip/infostore.go, line 200 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3073#-K2jJLwNMU0AKeU42uog)** ([raw file](https://github.com/cockroachdb/cockroach/blob/5dd3cb022aa71fdea6dd603bdad31ce98b70ecfc/gossip/infostore.go#L200)):</sup>
update the comment to explain what the returned closure does.


---

<sup>**[kv/txn_coord_sender.go, line 644 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3073#-K2jJe6vs0gIlBuyKeSH)** ([raw file](https://github.com/cockroachdb/cockroach/blob/da5fa7d04ed14de149341df4f328c2f73591e7c8/kv/txn_coord_sender.go#L644)):</sup>
TODO(tamird)


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3073)

**Comment by tschottdorf** [comment]
LGTM

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[gossip/infostore.go, line 200 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3073#-K2jJLwNMU0AKeU42uog)** ([raw file](https://github.com/cockroachdb/cockroach/blob/5dd3cb022aa71fdea6dd603bdad31ce98b70ecfc/gossip/infostore.go#L200)):</sup>
Done.


---

<sup>**[kv/txn_coord_sender.go, line 644 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3073#-K2jJe6vs0gIlBuyKeSH)** ([raw file](https://github.com/cockroachdb/cockroach/blob/da5fa7d04ed14de149341df4f328c2f73591e7c8/kv/txn_coord_sender.go#L644)):</sup>
Nooo, I don't want to own this TODO. Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3073)

**Comment by bdarnell** [comment]
Review status: 5 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

<sup>**[gossip/infostore.go, line 219 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3073#-K2jNjr9GtgAzlxJx-zy)** ([raw file](https://github.com/cockroachdb/cockroach/blob/5b3749f03ebd3d824841fdd6d85fda99b0ee5b37/gossip/infostore.go#L219)):</sup>
Comment that we want to preserve order (and that removing callbacks is uncommon, assuming it is), so we don't try to optimize this in the future by swapping the element to be removed to the end and truncating the slice.


---

<sup>**[kv/txn_coord_sender.go, line 644 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3073#-K2jJe6vs0gIlBuyKeSH)** ([raw file](https://github.com/cockroachdb/cockroach/blob/da5fa7d04ed14de149341df4f328c2f73591e7c8/kv/txn_coord_sender.go#L644)):</sup>
Why do we now need a clone when we used to think that the `errStr` part of the callback was sufficient?


---

<sup>**[storage/client_raft_test.go, line 1409 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3073#-K2jOfpGNBIXYbCSc3Mw)** ([raw file](https://github.com/cockroachdb/cockroach/blob/5b3749f03ebd3d824841fdd6d85fda99b0ee5b37/storage/client_raft_test.go#L1409)):</sup>
2 minutes is a long time.  If it takes anywhere near that long we've got a problem on our hands and we should fix that instead of raising the timeout that much. What's the slowest successful execution you've seen? Does it still need more time after #3070?


---

<sup>**[storage/client_split_test.go, line 751 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3073#-K2jPRQ953srZBIBal5A)** ([raw file](https://github.com/cockroachdb/cockroach/blob/5b3749f03ebd3d824841fdd6d85fda99b0ee5b37/storage/client_split_test.go#L751)):</sup>
If we need this here, we're going to need it in a lot of tests that start/stop stores. Where exactly are we hitting the error here? Is there anything we can wait for in `restartStore` to make it deterministic?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3073)

**Comment by tamird** [comment]
Review status: 5 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

<sup>**[gossip/infostore.go, line 219 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3073#-K2jNjr9GtgAzlxJx-zy)** ([raw file](https://github.com/cockroachdb/cockroach/blob/5b3749f03ebd3d824841fdd6d85fda99b0ee5b37/gossip/infostore.go#L219)):</sup>
Actually, I'm just going to make this implementation optimal - I don't think we need to preserve order through removals.


---

<sup>**[kv/txn_coord_sender.go, line 644 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3073#-K2jJe6vs0gIlBuyKeSH)** ([raw file](https://github.com/cockroachdb/cockroach/blob/da5fa7d04ed14de149341df4f328c2f73591e7c8/kv/txn_coord_sender.go#L644)):</sup>
There was a race on an error's transaction pointer: https://circleci.com/gh/cockroachdb/cockroach/8992


---

<sup>**[storage/client_raft_test.go, line 1409 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3073#-K2jOfpGNBIXYbCSc3Mw)** ([raw file](https://github.com/cockroachdb/cockroach/blob/5b3749f03ebd3d824841fdd6d85fda99b0ee5b37/storage/client_raft_test.go#L1409)):</sup>
2 minutes is chosen so that the test timeout fires and we get a stack trace. I don't think I've tried this after #3070.


---

<sup>**[storage/client_split_test.go, line 751 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3073#-K2jPRQ953srZBIBal5A)** ([raw file](https://github.com/cockroachdb/cockroach/blob/5b3749f03ebd3d824841fdd6d85fda99b0ee5b37/storage/client_split_test.go#L751)):</sup>
Here's one: https://circleci.com/gh/cockroachdb/cockroach/8994

I'm not sure if there is, I didn't dig into this very deeply, though I expected that `restartStore` wouldn't return until the store was ready.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3073)

**Comment by bdarnell** [comment]
Review status: 5 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

<sup>**[storage/client_raft_test.go, line 1409 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3073#-K2jOfpGNBIXYbCSc3Mw)** ([raw file](https://github.com/cockroachdb/cockroach/blob/5b3749f03ebd3d824841fdd6d85fda99b0ee5b37/storage/client_raft_test.go#L1409)):</sup>
OK. Let's leave this one out until we see if the problem recurs after #3070.


---

<sup>**[storage/client_split_test.go, line 751 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3073#-K2jPRQ953srZBIBal5A)** ([raw file](https://github.com/cockroachdb/cockroach/blob/5b3749f03ebd3d824841fdd6d85fda99b0ee5b37/storage/client_split_test.go#L751)):</sup>
I think `restartStore` does wait long enough but the `distSender` is using a stale cached range descriptor (and not retrying because we call `NewSendError(..., false)`). I think making the "store is stopped" send error in `client_test.go` retryable would fix this.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3073)

**Comment by tamird** [comment]
Review status: 5 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

<sup>**[storage/client_raft_test.go, line 1409 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3073#-K2jOfpGNBIXYbCSc3Mw)** ([raw file](https://github.com/cockroachdb/cockroach/blob/5b3749f03ebd3d824841fdd6d85fda99b0ee5b37/storage/client_raft_test.go#L1409)):</sup>
Done.


---

<sup>**[storage/client_split_test.go, line 751 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3073#-K2jPRQ953srZBIBal5A)** ([raw file](https://github.com/cockroachdb/cockroach/blob/5b3749f03ebd3d824841fdd6d85fda99b0ee5b37/storage/client_split_test.go#L751)):</sup>
OK, I'll leave it out for now and see about making that retryable in a future backport.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3073)

**Comment by bdarnell** [comment]
LGTM

**Pull request merged**
