### PR TITLE
changefeedccl: better validation check for sarama config

### PR DESCRIPTION
**Pull request by wenyihu6**
Previously, we implement our own validation check for sarama config which may
have missed certain cases. This patch changes an additional check by adding
sarama's own exported validation function.

Release note: none
Epic: none

### CODE REVIEW

**Comment by wenyihu6** [comment]
*[`pkg/ccl/changefeedccl/sink_kafka.go` line 211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118890#-Nq3IkSU-I_3ZdMwmoa4:-Nq3IkSU-I_3ZdMwmoa5:blz7gh3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ff9177754547423854093d1fa19f3100c9b75c7/pkg/ccl/changefeedccl/sink_kafka.go#L211)):*
> ```Go
> 	// where our call to Flush() would block forever.
> 	if (c.Flush.Bytes > 0 || c.Flush.Messages > 1) && c.Flush.Frequency == 0 {
> 		return errors.New("Flush.Frequency must be > 0 when Flush.Bytes > 0 or Flush.Messages > 1")
> ```

Sarama does the check for this here - it checks for c.Flush.Messages > 0 rather than c.Flush.Messages > 1 which I thought makes more sense. 

https://github.com/IBM/sarama/blob/25c9c1a880e385781e1a39b49f8e7239e3d5e729/config.go#L593-L595

**Review by rharding6373 — APPROVED** [review]
:lgtm: The sarama config validator is a nice find!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118890#-:-Nq3bNZm5PNP5SqZKqh0:b-fwrtdt)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @wenyihu6)

___
*[`pkg/ccl/changefeedccl/sink_kafka.go` line 211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118890#-Nq3IkSU-I_3ZdMwmoa4:-Nq3b9q8--ncvbi_Mq2W:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ff9177754547423854093d1fa19f3100c9b75c7/pkg/ccl/changefeedccl/sink_kafka.go#L211)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

Sarama does the check for this here - it checks for c.Flush.Messages > 0 rather than c.Flush.Messages > 1 which I thought makes more sense. 

https://github.com/IBM/sarama/blob/25c9c1a880e385781e1a39b49f8e7239e3d5e729/config.go#L593-L595
</blockquote></details>

:thumbsup:

**Comment by wenyihu6** [comment]
*[`pkg/ccl/changefeedccl/sink_kafka.go` line 211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118890#-Nq3IkSU-I_3ZdMwmoa4:-Nq8u_4r0qDQCo086mkm:b-70cm7y) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ff9177754547423854093d1fa19f3100c9b75c7/pkg/ccl/changefeedccl/sink_kafka.go#L211)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

:thumbsup:
</blockquote></details>

I just realized that sarama doesn't return an error in this case but just outputs a warning https://github.com/IBM/sarama/blob/25c9c1a880e385781e1a39b49f8e7239e3d5e729/config.go#L594. I will the validation back. It does return error for improper client id though. I will add a test for this in the other PR.

**Review by rharding6373 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118890#-:-Nq8xavy7vffNnAWc3TH:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @wenyihu6)

___
*[`pkg/ccl/changefeedccl/sink_kafka.go` line 211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118890#-Nq3IkSU-I_3ZdMwmoa4:-Nq8xco0DT-u-4eq5EsL:b3qe8nd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ff9177754547423854093d1fa19f3100c9b75c7/pkg/ccl/changefeedccl/sink_kafka.go#L211)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

I just realized that sarama doesn't return an error in this case but just outputs a warning https://github.com/IBM/sarama/blob/25c9c1a880e385781e1a39b49f8e7239e3d5e729/config.go#L594. I will the validation back. It does return error for improper client id though. I will add a test for this in the other PR.
</blockquote></details>

Could you add a note in the comment to the effect of "Note that the sarama config validator only logs an error in this case, so we check explicitly."

**Comment by wenyihu6** [comment]
*[`pkg/ccl/changefeedccl/sink_kafka.go` line 211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118890#-Nq3IkSU-I_3ZdMwmoa4:-Nq9eqJPA8VyWZrc0BWn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ff9177754547423854093d1fa19f3100c9b75c7/pkg/ccl/changefeedccl/sink_kafka.go#L211)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Could you add a note in the comment to the effect of "Note that the sarama config validator only logs an error in this case, so we check explicitly."
</blockquote></details>

Done.

**Comment by wenyihu6** [comment]
TFTRs!!

bors r=rharding6373

**Pull request merged**
