### PR TITLE
sql, stats: use the jobs framework for CREATE STATISTICS

### PR DESCRIPTION
**Pull request by rytaft**
Prior to this commit, `CREATE STATISTICS` was a regular SQL statement
and followed the standard logic of AST -> `planNode` -> DistSQL physical
plan -> execution. This commit changes `CREATE STATISTICS` to use the
jobs framework, and as a result the `createStatsNode` has been
changed to execute a function which starts a `CreateStats` job. The job
is then responsible for performing DistSQL planning and execution.

There are several advantages to using the jobs framework:
- Now `CREATE STATISTICS` jobs can easily be cancelled, paused and resumed,
  and viewed from the Admin UI.
- Nodes can adopt the job if the original gateway node fails.
- We will be able to use the JobID to lock creation of automatic
  statistics, so that only one automatic statistics job can run at
  a time. Job adoption will ensure that a dead node never prevents progress
  by holding a lock on stats creation (implementation of locking will be
  saved for the next PR).

Release note (sql change): CREATE STATISTICS now runs as a job instead
of as a regular SQL statement.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
Cool! It will take some time to unpack this, it involves a lot of infrastructure I'm not familiar with.

The plan node hook stuff is to allow the implementation to live in CCL packages (which is not the case here). Are you sure that part is needed?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34279#-:-LXGiIjm8UbEXOeiU5Na:b7stolw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @danhhz, @dt, @mjibson, @RaduBerinde, and @rytaft)

___
*[pkg/jobs/jobspb/jobs.proto, line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34279#-LXGjU5AB0J0mVYC4Gsj:-LXGjU5AB0J0mVYC4Gsk:b-cq640) ([raw file](https://github.com/cockroachdb/cockroach/blob/22a3b4810b8bf543767f522531a4f5ba34cf9b80/pkg/jobs/jobspb/jobs.proto#L206)):*
> ```protobuf
>   ];
>   sqlbase.TableDescriptor table = 2 [(gogoproto.nullable) = false];
>   repeated Columns columns = 3 [(gogoproto.nullable) = false];
> ```

This should be a list of lists. Even though there's no syntax, a single CreateStats can in principle create stats for multiple sets of columns. In fact, that's what it does now when no columns are specified (in the future, we may want to populate this with those auto-determined columns).

**Review by rytaft — COMMENTED** [review]
Thanks!

> The plan node hook stuff is to allow the implementation to live in CCL packages (which is not the case here). Are you sure that part is needed?

I'm not sure, but the reason I did it this way was because we don't want the normal AST -> `planNode` -> DistSQL plan -> execution pipeline. The `planNode` returned by `planner.newPlan` should just create a new job and stop. `hookFnNode` is a convenient way to do that since it just executes the function registered with `AddPlanHook`.  I could put the `createStats` planNode back, but I think it would effectively do the same thing as `hookFnNode`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34279#-:-LXK2xSY7rJceXkE7Wje:b-8y24i8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @danhhz, @dt, @mjibson, and @RaduBerinde)

___
*[pkg/jobs/jobspb/jobs.proto, line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34279#-LXGjU5AB0J0mVYC4Gsj:-LXK59bNDDR22edQ9oeI:b-q3xdlk) ([raw file](https://github.com/cockroachdb/cockroach/blob/22a3b4810b8bf543767f522531a4f5ba34cf9b80/pkg/jobs/jobspb/jobs.proto#L206)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This should be a list of lists. Even though there's no syntax, a single CreateStats can in principle create stats for multiple sets of columns. In fact, that's what it does now when no columns are specified (in the future, we may want to populate this with those auto-determined columns).
</blockquote></details>

This is actually a list of lists -- it's a repeated element which itself contains a repeated element (I don't know of another way to represent that with protobufs). But I agree the naming doesn't make that obvious... I've changed the names to hopefully make it more clear.

**Review by RaduBerinde — COMMENTED** [review]
Oh, I see, thanks, that makes sense!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34279#-:-LXK8_Lc-a0r7U2SfIlL:bq54y7g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @danhhz, @dt, @mjibson, and @rytaft)

___
*[pkg/jobs/jobspb/jobs.proto, line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34279#-LXGjU5AB0J0mVYC4Gsj:-LXK8d-y48pvCaLaejmT:b-co0n74) ([raw file](https://github.com/cockroachdb/cockroach/blob/22a3b4810b8bf543767f522531a4f5ba34cf9b80/pkg/jobs/jobspb/jobs.proto#L206)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This is actually a list of lists -- it's a repeated element which itself contains a repeated element (I don't know of another way to represent that with protobufs). But I agree the naming doesn't make that obvious... I've changed the names to hopefully make it more clear. 
</blockquote></details>

Sorry, my bad, missed the inner "repeated". I like the new name though, thanks!

**Review by danhhz — COMMENTED** [review]
All the pieces here look good! I didn't do a detailed review, but I can if you need an additional pair of eyes.

From a high level, my two large concerns with any new job are 1) overloading the jobs row with progress updates, 2)  zombie jobs and 3) the user UX of the jobs entries.

1) It's really easy to gum things up with txn contention updating the job progress. Changefeeds, for example, funnel progress info to a singleton distsql processor, which then rate limits and does the updates. I don't think it's worth the complexity in your case of a processor just for that, but given that the number of updates here scales with the number of processors, it's worth a few preventative measures to mitigate the risk.

First, you could rate limit the progress updates based on time. No need to update more than every second or so.

Even easier here, if your TODO is going to stick around for a while, since you're not actually updating the progress, you're just checking whether the job is still live, is to use a read-only txn. I don't recall offhand if the jobs framework already has an accessor to grab the state, but if it doesn't, feel free to add one. This would be used instead of the progress update in your worker loop. If it also surfaced the error, you could also use it the error handling bit in your planner code.

2) Dunno the details of the lock you describe, but important to know that you can end up with zombie jobs. The framework does its best to let only one copy of each job run at a time, but there are various conditions around failures where we can end up with two copies of the job running at once: the blessed one and a zombie one. I think you'll be fine, since the worst thing that happens here is probably some wasted work (as opposed to restore/changefeeds/etc where we have correctness issues to worry about), but important to keep in mind.

3) How often do we make these jobs? What does that look like in the jobs admin ui page? I've only been following the statistics stuff at a high level, but the number of these we run scales with traffic right? Maybe with num tables, too? Unless something has changed since I last looked, we don't garbage collect old jobs, so these could clutter things up. On the other hand, that page already has a dropdown for job type, so maybe that's sufficient. I just want to make sure this is considered.

> I could put the createStats planNode back, but I think it would effectively do the same thing as hookFnNode.

This is likely what I'd recommend, make the planNode submit the job and then either return the jobID (so the client can poll progress) or have it wait until the job finishes. Most (all?) existing jobs do the former. We tend to avoid planHook when we can (which is any non-ccl code).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34279#-:-LXK8IAUDeDviQY6aHcE:bw0ott)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @danhhz, @dt, @mjibson, and @rytaft)

**Review by RaduBerinde — COMMENTED** [review]
@danhhz How does changefeed funnel progress info? Is it through a special ProducerMetadata?  We already have a single "final" processor (SampleAggregator), we should be able to use the same mechanism.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34279#-:-LXKGE_b9ZQB6afEIAPM:b-6jb6x8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @dt, @mjibson, and @rytaft)

**Comment by danhhz** [comment]
Changefeed progress is both used for some user facing stuff and super complicated and as a result, ended up needing stronger ordering guarantees than distsql metadata provides.

For this job, you have two "progress" concerns. One is stopping the workers when the job is paused or fails. This can be done with the read only txn I mentioned or (now that I think about it) handled with ctx cancellation. The latter is what changefeeds do. The second concern is actually updating the progress. Distsql metadata and doing it on SampleAggregator sgtm

**Review by rytaft — COMMENTED** [review]
Thanks, @danhhz!

1. Regarding the read-only txn: In my first attempt I actually took this approach and stored the transaction info in the `CreateStatsDetails`.  Not sure I understand the suggestion to create an accessor for the jobs framework, but that sounds like it might be better -- can you explain a bit more? Alternatively, ctx cancellation also sounds like a good option. Is there a reason to prefer one over the other?

2. Good to know about the possibility of zombie jobs, but I think you're right that the only consequence would be some wasted work and perhaps temporarily degraded performance. The purpose of the lock is for performance reasons -- there is no correctness issue with running multiple `CREATE STATISTICS` jobs at once.

3. You're right that there could be a lot of `CREATE STATISTICS` jobs cluttering the admin UI. The TYPE dropdown does help, though (speaking of which, looks like I need to add `CREATE STATISTICS` to the dropdown....). Should I create an issue to garbage collect old jobs (at least `CreateStats` jobs)?

4. Good to know about avoiding planHook -- I'll put the `createStats` node back.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34279#-:-LXKJ8KEBon2QrPurgTX:b-axfqgr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @dt, and @mjibson)

**Review by rytaft — COMMENTED** [review]
@danhhz -- It seems like the context is not getting cancelled automatically. I could add a function to cancel the job's context and call it from `OnFailOrCancel`, but that wouldn't work for `PAUSE JOB`. Perhaps I should do both of your suggestions: add a function to get the status and add a function to cancel the context? Does that seem reasonable?

> Jobs is unstaffed at this point, so if this needs to be done as a result of making stats a job, then you might have to pick this one off yourself : - ).

No problem! I'll create an issue and assign to myself. Doesn't seem urgent (the UI seems to work fine, especially given the TYPE dropdown), but I'll try to get it done before the release...

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34279#-:-LXL6fca5ARqfv7PLlLL:b-4gwpdl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @dt, and @mjibson)

**Comment by danhhz** [comment]
The context cancellation does work, changefeeds rely on it. What test are you running that cause you to say it doesn't?

Usually, the tricky bit is getting the distsql error handling right, but it's worth the effort to investigate what's going on. Basically, if the job is paused or cancelled, the ctx your `Resume` function gets will be cancelled. If the job coordinator node is killed, then your SampleAggregator should get an error back from `job.FractionProgressed` and it should use that error to tear down the processor, which will cause distsql to propagate the ctx cancellation to the rest of your flow.

**Comment by rytaft** [comment]
As we discussed offline, context cancellation works for liveness issues or other errors, but not for paused or cancelled jobs. I've instead moved the progress reporting to the `SampleAggregator` so it can be rate-limited.  I've also added periodic metadata pushes from the `Sampler` to detect when the consumer is closed.

I've also put the `createStatsNode` back, but now it's a local-only node similar to `hookFnNode`.

PTAL - thanks!

**Comment by rytaft** [comment]
Fixed a bug and updated the tests to catch it. 

I've also confirmed that this plays nicely with automatic stats by enabling automatic stats during a TPC-C run. I could see the jobs in the Admin UI and successfully canceled and paused/resumed a handful.

**Review by danhhz — COMMENTED** [review]
jobs stuff lgtm modulo a few last comments. great work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34279#-:-LXRRlr_Bu0w5smHiF_Q:b5w26n7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @dt, @mjibson, and @rytaft)

___
*[pkg/sql/distsqlrun/sample_aggregator.go, line 19 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34279#-LXRPTcJD0Ge_PlbI-8x:-LXRPTcJD0Ge_PlbI-8y:bb9rtlt) ([raw file](https://github.com/cockroachdb/cockroach/blob/66427264c97ec1a8836442af2e1424413cad1f99/pkg/sql/distsqlrun/sample_aggregator.go#L19)):*
> ```Go
> import (
> 	"context"
> 	time "time"
> ```

nit: this is odd
___
*[pkg/sql/distsqlrun/sample_aggregator.go, line 145 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34279#-LXRPcYY-c547M7I8iu1:-LXRPcYY-c547M7I8iu2:b-5ewgfu) ([raw file](https://github.com/cockroachdb/cockroach/blob/66427264c97ec1a8836442af2e1424413cad1f99/pkg/sql/distsqlrun/sample_aggregator.go#L145)):*
> ```Go
> 	var job *jobs.Job
> 	jobID := s.spec.JobID
> 	if jobID != 0 {
> ```

are there times that you won't have a job id? maybe stick a comment here with when that happens
___
*[pkg/sql/distsqlrun/sample_aggregator.go, line 173 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34279#-LXRQye70GY1PVPmiK3g:-LXRQye70GY1PVPmiK3h:b-odi2oa) ([raw file](https://github.com/cockroachdb/cockroach/blob/66427264c97ec1a8836442af2e1424413cad1f99/pkg/sql/distsqlrun/sample_aggregator.go#L173)):*
> ```Go
> 			// rows have been processed. The purpose of this function call is to
> 			// periodically check that the job has not been paused or canceled.
> 			if err := progFn(0); err != nil {
> ```

I was imagining doing this in response to getting distsql metadata with progress info filled in (rate limited with a `util.Every(sampleAggregatorProgressInterval)`). This works too, but my suggestion would save you the goroutine (and what you have here leaks the timer).
___
*[pkg/sql/distsqlrun/sample_aggregator.go, line 246 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34279#-LXRQVjk3E4RZsmDYmui:-LXRQMue7n6yahQ95YGp:b-ff7vad) ([raw file](https://github.com/cockroachdb/cockroach/blob/66427264c97ec1a8836442af2e1424413cad1f99/pkg/sql/distsqlrun/sample_aggregator.go#L246)):*
> ```Go
> 	// Report progress one last time so we don't write results if the job was
> 	// canceled.
> 	if err = progFn(1.0); err != nil {
> ```

Sorry if i've missed it, but do you have a job.Succeeded somewhere? You want to call it when the job finishes successfully to put the job into the terminal "succeeded" status

**Review by rytaft — COMMENTED** [review]
Thanks! Updated.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34279#-:-LXUT5frAe7UvX-w0iBN:b-wb3jnk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @danhhz, @dt, and @mjibson)

___
*[pkg/sql/distsqlrun/sample_aggregator.go, line 19 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34279#-LXRPTcJD0Ge_PlbI-8x:-LXUBtHbBqS6aGD9Hgun:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/66427264c97ec1a8836442af2e1424413cad1f99/pkg/sql/distsqlrun/sample_aggregator.go#L19)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

nit: this is odd
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/sample_aggregator.go, line 145 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34279#-LXRPcYY-c547M7I8iu1:-LXUCEgE5WbjTpKS6HEF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/66427264c97ec1a8836442af2e1424413cad1f99/pkg/sql/distsqlrun/sample_aggregator.go#L145)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

are there times that you won't have a job id? maybe stick a comment here with when that happens
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/sample_aggregator.go, line 173 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34279#-LXRQye70GY1PVPmiK3g:-LXUL3NT5MG0E7iiUoDt:b-j5eoda) ([raw file](https://github.com/cockroachdb/cockroach/blob/66427264c97ec1a8836442af2e1424413cad1f99/pkg/sql/distsqlrun/sample_aggregator.go#L173)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I was imagining doing this in response to getting distsql metadata with progress info filled in (rate limited with a `util.Every(sampleAggregatorProgressInterval)`). This works too, but my suggestion would save you the goroutine (and what you have here leaks the timer).
</blockquote></details>

Oh nice! Didn't know that function existed. Done.
___
*[pkg/sql/distsqlrun/sample_aggregator.go, line 246 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34279#-LXRQVjk3E4RZsmDYmui:-LXUL84Z-QLo1NBMeGqy:b5p4yjv) ([raw file](https://github.com/cockroachdb/cockroach/blob/66427264c97ec1a8836442af2e1424413cad1f99/pkg/sql/distsqlrun/sample_aggregator.go#L246)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Sorry if i've missed it, but do you have a job.Succeeded somewhere? You want to call it when the job finishes successfully to put the job into the terminal "succeeded" status
</blockquote></details>

Seems like that's getting called inside `Registry.resume` (in `jobs/registry.go`) once `createStatsResumer.Resume` finishes successfully.

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34279)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @danhhz, @dt, @mjibson, and @rytaft)

___
*[pkg/sql/distsqlrun/sample_aggregator.go, line 246 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34279#-LXRQVjk3E4RZsmDYmui:-LXUWsPd6-zJw-zreaol:brsycg3) ([raw file](https://github.com/cockroachdb/cockroach/blob/66427264c97ec1a8836442af2e1424413cad1f99/pkg/sql/distsqlrun/sample_aggregator.go#L246)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Seems like that's getting called inside `Registry.resume` (in `jobs/registry.go`) once `createStatsResumer.Resume` finishes successfully.
</blockquote></details>

:man_facepalming: carry on

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34279)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball, @danhhz, @dt, and @mjibson)

___
*[pkg/sql/distsqlrun/sample_aggregator.go, line 246 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34279#-LXRQVjk3E4RZsmDYmui:-LXUXdZRDJTA6DTAW9jd:btqx8we) ([raw file](https://github.com/cockroachdb/cockroach/blob/66427264c97ec1a8836442af2e1424413cad1f99/pkg/sql/distsqlrun/sample_aggregator.go#L246)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

:man_facepalming: carry on
</blockquote></details>

:thumbsup: No worries!

**Review by RaduBerinde — APPROVED** [review]
:lgtm: Nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34279#-:-LXVJWvg2pl4Ftby90Ms:bcmw7ss)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @danhhz, @dt, @mjibson, and @rytaft)

___
*[pkg/jobs/jobspb/jobs.proto, line 195 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34279#-LXV3hbV5XlqmJ_38MC9:-LXV3hbV5XlqmJ_38MCA:b10pfp2) ([raw file](https://github.com/cockroachdb/cockroach/blob/adb8afd63985e29afc53a73813090fc81c622bf5/pkg/jobs/jobspb/jobs.proto#L195)):*
> ```protobuf
> }
> 
> message CreateStatsDetails {
> ```

[nit] could use a comment mentioning this is related to table stats and CREATE STATS statement.
___
*[pkg/sql/create_stats.go, line 80 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34279#-LXV4fpY5-3Aqaees-RS:-LXV4fpY5-3Aqaees-RT:bqdfzh7) ([raw file](https://github.com/cockroachdb/cockroach/blob/adb8afd63985e29afc53a73813090fc81c622bf5/pkg/sql/create_stats.go#L80)):*
> ```Go
> 
> func (p *planner) CreateStatistics(ctx context.Context, n *tree.CreateStats) (planNode, error) {
> 	fn := func(ctx context.Context, resultsCh chan<- tree.Datums) error {
> ```

Do we need to store this as a function? Can't it just be a separate method?
___
*[pkg/sql/create_stats.go, line 221 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34279#-LXVA2hi-7Y8Xvd-OKh9:-LXVA2hi-7Y8Xvd-OKhA:b-uxf9lc) ([raw file](https://github.com/cockroachdb/cockroach/blob/adb8afd63985e29afc53a73813090fc81c622bf5/pkg/sql/create_stats.go#L221)):*
> ```Go
> }
> 
> type createStatsResumer struct {
> ```

I would add a description here and explain how the object is used. Especially that an instance of this is associated with a single job (because the methods in the interface suggest otherwise)
___
*[pkg/sql/create_stats.go, line 249 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34279#-LXV5BDG4XNlPu--b95F:-LXV5BDG4XNlPu--b95G:b-zab3op) ([raw file](https://github.com/cockroachdb/cockroach/blob/adb8afd63985e29afc53a73813090fc81c622bf5/pkg/sql/create_stats.go#L249)):*
> ```Go
> 
> 	dsp := p.DistSQLPlanner()
> 	err := r.evalCtx.ExecCfg.DB.Txn(ctx, func(ctx context.Context, txn *client.Txn) error {
> ```

[nit] can just `return` so we don't have yet another `err` instance
___
*[pkg/sql/create_stats.go, line 276 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34279#-LXV5Fmm2n1_--YGexkK:-LXV5Fmn-PA-NNhDF1n3:bpr12r7) ([raw file](https://github.com/cockroachdb/cockroach/blob/adb8afd63985e29afc53a73813090fc81c622bf5/pkg/sql/create_stats.go#L276)):*
> ```Go
> 				return err
> 			}
> 			return err
> ```

We have two different `err`s here which makes this kind of confusing, I'd give the inner one a different name (eg `jobErr`)
___
*[pkg/sql/create_stats.go, line 293 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34279#-LXV5WS45pWAPvxD5KEB:-LXV5WS45pWAPvxD5KEC:b2h243e) ([raw file](https://github.com/cockroachdb/cockroach/blob/adb8afd63985e29afc53a73813090fc81c622bf5/pkg/sql/create_stats.go#L293)):*
> ```Go
> 
> // OnSuccess is part of the jobs.Resumer interface.
> func (r *createStatsResumer) OnSuccess(ctx context.Context, txn *client.Txn, job *jobs.Job) error {
> ```

nit: maybe use `_` instead of `txn` here to make it clear we're not using that
___
*[pkg/sql/create_stats.go, line 323 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34279#-LXV6BEO0N2_sZ-EIpCn:-LXV6BEO0N2_sZ-EIpCo:bfzrdmr) ([raw file](https://github.com/cockroachdb/cockroach/blob/adb8afd63985e29afc53a73813090fc81c622bf5/pkg/sql/create_stats.go#L323)):*
> ```Go
> }
> 
> func createStatsResumeHook(typ jobspb.Type, settings *cluster.Settings) jobs.Resumer {
> ```

[nit] maybe add a comment, or if not I'd just declare this directly in the `AddResumeHook` call.

**Review by rytaft — COMMENTED** [review]
TFTR! Updated.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34279#-:-LXVVYw38bKLmv66TH54:b-p0fj95)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @dt, and @mjibson)

___
*[pkg/jobs/jobspb/jobs.proto, line 195 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34279#-LXV3hbV5XlqmJ_38MC9:-LXVNDNf5oPmYt0WWqQj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/adb8afd63985e29afc53a73813090fc81c622bf5/pkg/jobs/jobspb/jobs.proto#L195)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] could use a comment mentioning this is related to table stats and CREATE STATS statement.
</blockquote></details>

Done.
___
*[pkg/sql/create_stats.go, line 80 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34279#-LXV4fpY5-3Aqaees-RS:-LXVOlsB2aEQFepy3e7G:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/adb8afd63985e29afc53a73813090fc81c622bf5/pkg/sql/create_stats.go#L80)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Do we need to store this as a function? Can't it just be a separate method?
</blockquote></details>

Done.
___
*[pkg/sql/create_stats.go, line 221 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34279#-LXVA2hi-7Y8Xvd-OKh9:-LXVVm_76hY_dsgJ_D04:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/adb8afd63985e29afc53a73813090fc81c622bf5/pkg/sql/create_stats.go#L221)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I would add a description here and explain how the object is used. Especially that an instance of this is associated with a single job (because the methods in the interface suggest otherwise)
</blockquote></details>

Done.
___
*[pkg/sql/create_stats.go, line 249 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34279#-LXV5BDG4XNlPu--b95F:-LXVVbS07rYbeMbm_ldr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/adb8afd63985e29afc53a73813090fc81c622bf5/pkg/sql/create_stats.go#L249)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] can just `return` so we don't have yet another `err` instance
</blockquote></details>

Done.
___
*[pkg/sql/create_stats.go, line 276 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34279#-LXV5Fmm2n1_--YGexkK:-LXVVdhM2xOHFr7CBPG_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/adb8afd63985e29afc53a73813090fc81c622bf5/pkg/sql/create_stats.go#L276)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We have two different `err`s here which makes this kind of confusing, I'd give the inner one a different name (eg `jobErr`)
</blockquote></details>

Done.
___
*[pkg/sql/create_stats.go, line 293 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34279#-LXV5WS45pWAPvxD5KEB:-LXVVh2XCbsd8OsrvkU_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/adb8afd63985e29afc53a73813090fc81c622bf5/pkg/sql/create_stats.go#L293)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

nit: maybe use `_` instead of `txn` here to make it clear we're not using that
</blockquote></details>

Done.
___
*[pkg/sql/create_stats.go, line 323 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34279#-LXV6BEO0N2_sZ-EIpCn:-LXVViym81RPzvciobtP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/adb8afd63985e29afc53a73813090fc81c622bf5/pkg/sql/create_stats.go#L323)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] maybe add a comment, or if not I'd just declare this directly in the `AddResumeHook` call.
</blockquote></details>

Done.

**Pull request merged**
