### PR TITLE
distsql: add XOR aggregate function

### PR DESCRIPTION
**Pull request by danhhz**
XOR is commutative and associative, so it can be aggregated locally on
each node into a single value and once finally on the gateway.

This is motivated by a desire to fingerprint large amounts of data
(entire tables) via distsql. Good hash functions are not commutative or
associative and so do not lend themselves to distributed computation.
Assuming you start with a good checksum for each row and don't care
about row order, XOR is a decent way to combine them.

I'm a little out of my depth here, so if there's some better way to do what I want than xor, I'm all ears.

@knz Any thoughts on the name? Our docs say the non-aggregation xor is `#`, should I use that?

### CODE REVIEW

**Comment by RaduBerinde** [comment]
I don't have context on what the use case is, but to really fingerprint a large table, I would use a Merkle Tree. Each leaf is a row fingerprint.  The next level fingerprints each X consecutive rows into a single fingerprint. and so on.

We can compute fingerprints for ranges in parallel. For each range, we compute as much of the tree as we can. If you think of this big tree and a range of rows (aka leaves), say we paint each tree node with blue if all the rows inside that node's subtree are inside this range. Now among the blue nodes, paint with black those whose parent is not blue. The black nodes are what we emit for this range. There are `O(log RowsPerRange)` black nodes (because on any level the black nodes are contiguous, and we can't have all black siblings under a parent node).

Then we process these `O(NumRanges * log RowsPerRange)` results sequentially. If needed this step can also be parallelized with the same scheme (split into blocks of consecutive ranges).

This could work well within distsql. The first stage can be a processor that generates the black nodes and the second stage is a processor that takes streams of black nodes and merges them. The streams can be ordered "left to right" as you look at the tree so this merging can be done on the go, without storing a lot in memory (just the right-most incomplete branches of the processed tree).


Regarding this PR, I don't see the harm in adding this function, it's definitely a simple way to aggregate fingerprints and it could have other applications.

**Comment by dt** [comment]
Merkle trees are really cool, but I am mostly only familiar with their use in p2p networks (where ability to staple partial hashes with a chunk allows verifying chunks belong to the root has as they're received) -- what's their benefit here over the xor?

**Comment by RaduBerinde** [comment]
Yes, the problems with XOR are ordering and duplicate rows canceling each other out. But if we always fingerprint the entire row (including the distinct and ordered PK), these aren't concerns anymore; in this case I think it would work pretty well.

If we are looking for something cryptographically secure (i.e. that gives you similar guarantees to hashing the entire table), I believe Merkle trees achieve that; I don't know if XORing row fingerprints (with PKs) achieves that - my hunch is that it should be easier to forge a duplicate result (off the top of my head: I can generate a bunch of test row fingerprints, and then I am free to choose *any subset* of those; so with X hash calculations I can generate 2^X possible values iusing just XORs which are a couple of orders of magnitude faster than secure hashes).

**Comment by knz** [comment]
Associative/commutative hash functions:

https://en.wikipedia.org/wiki/MD6

https://en.wikipedia.org/wiki/Rolling_hash#Rabin-Karp_rolling_hash

**Comment by RaduBerinde** [comment]
The distsql part looks great! The rest LGTM too but I would get another review.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15831#-:-KjmYEG9Tcf3ItnUZFS8:b-bkcoz0)*

**Comment by knz** [comment]
- I suggest naming the aggregate version `xor_agg`, for consistency with `concat_agg` (the aggregate version of the `||` operator)

- you can call the operator (non-aggregate) variant `#` indeed and make it a new overload next to the integer version, unless you specifically want it to be variadic like coalesce (but that would be slightly more complex). The name `xor` is fine btw.

**Comment by danhhz** [comment]
Thanks for the comments everyone!

@knz I renamed the agg function to `xor_agg`. I don't need the non-agg version, so in the spirit of keeping our exposed surface low, I'll leave that out unless you feel strongly. RFAL

> Associative/commutative hash functions:
> https://en.wikipedia.org/wiki/MD6
> https://en.wikipedia.org/wiki/Rolling_hash#Rabin-Karp_rolling_hash

Great suggestion! I couldn't find go impls of either of those, tho

@RaduBerinde merkel trees are really interesting. The backstory here is that we'd like to do a BACKUP as of some system time, restore it somewhere else, and do a SELECT on each (reusing the same as of system time) to make sure the restored data has the same fingerprint. I took me a while to wrap my head around how the coloring makes this independent of the row->range mapping, but I think it makes sense now. Happy to leave it for a followup though : - )

Relatedly, @dt had [a cool idea over lunch on using them _during_ a restore](https://github.com/cockroachdb/cockroach/issues/15850) which could let us retry ranges that fail, so I had him write it up.

**Comment by arjunravinarayan** [comment]
:lgtm:
I think this is fine. In the long term we'll want something better than XOR and @knz's suggestions seem great, but this works well now. The aggregator_spec changes in particular look great.

---

Reviewed 7 of 7 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15831#-:-Kjn_cNDJXU6LkkSU1hy:b1xq9o9)*

**Comment by RaduBerinde** [comment]
For checking a restore this is great (as long as each row has something distinct, which should always be the case).

**Comment by danhhz** [comment]
Thanks for the reviews y'all!

**Pull request merged**
