### PR TITLE
sql: simplify MergeOrdering logic

### LINKED ISSUE #64784: sql: mismatched type schema on the arms of UNION
The following logic test (extracted from a SQLLite test):
```
hash-threshold 8

statement ok
CREATE TABLE tab3(pk INTEGER PRIMARY KEY, col0 INTEGER, col1 FLOAT, col2 TEXT, col3 INTEGER, col4 FLOAT, col5 TEXT, FAMILY (col1, col0, col2), FAMILY (col4), FAMILY (pk, col3), FAMILY (col5));
CREATE UNIQUE INDEX idx_tab3_0 ON tab3 (col4,col1);
CREATE UNIQUE INDEX idx_tab3_1 ON tab3 (col1 DESC,col3);
CREATE UNIQUE INDEX idx_tab3_2 ON tab3 (col0);
INSERT INTO tab3 VALUES(0,212,202.62,'nshdy',212,208.79,'wsxfc');
INSERT INTO tab3 VALUES(1,213,203.64,'xwfuo',213,209.26,'lyswz');
INSERT INTO tab3 VALUES(2,214,204.82,'jnued',216,210.48,'qczzf');
INSERT INTO tab3 VALUES(3,215,205.40,'jtijf',217,211.96,'dpugl');
INSERT INTO tab3 VALUES(4,216,206.3,'dpdzk',219,212.43,'xfirg');
INSERT INTO tab3 VALUES(5,218,207.43,'qpwyw',220,213.50,'fmgky');
INSERT INTO tab3 VALUES(6,219,208.3,'uooxb',221,215.30,'xpmdy');
INSERT INTO tab3 VALUES(7,220,209.54,'ndtbb',225,218.8,'ivqyw');
INSERT INTO tab3 VALUES(8,221,210.65,'zjpts',226,219.82,'sezsm');
INSERT INTO tab3 VALUES(9,222,211.57,'slaxq',227,220.91,'bdqyb');

query II nosort label-6010-2-desc
SELECT pk, col0 FROM tab3 WHERE (col0 IN (SELECT col3 FROM tab3 WHERE col3 IS NULL OR (col1 < 22.54) OR col4 > 85.74) OR ((col4 IS NULL)) AND col3 < 8 OR (col4 > 82.93 AND (col0 <= 61) AND col0 > 94 AND col0 > 15)) ORDER BY 2 DESC
----
12 values hashing to 283dc7e5427055f6b3790e695ea8b0fc
```
fails for `fakedist*` configs with
```
        testdata/logic_test/wip:27: SELECT pk, col0 FROM tab3 WHERE (col0 IN (SELECT col3 FROM tab3 WHERE col3 IS NULL OR (col1 < 22.54) OR col4 > 85.74) OR ((col4 IS NULL)) AND col3 < 8 OR (col4 > 82.93 AND (col0 <= 61) AND col0 > 94 AND col0 > 15)) ORDER BY 2 DESC
        expected success, but found
        (XXUUU) ResultTypes length mismatch: 5 and 4
        distsql_plan_set_op.go:27: in mergeResultTypesForSetOp()
	-- FAIL
```

### PR DESCRIPTION
**Pull request by yuzefovich**
Remove the physical plan intelligence around plumbing columns for
merge ordering. The optimizer takes care of this now. The complications
around the existing logic represented themselves as a mismatch in the
type schema around the set operations when the ordering needs to be
maintained.

Fixes: #64784.

Release note: None (no stable release with this bug)

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64954)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/distsql_plan_set_op.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64954#-M_MYvwg1G6hWo46_lwZ:-M_MYvwg1G6hWo46_lw_:bi7v7ln) ([raw file](https://github.com/cockroachdb/cockroach/blob/42323fd273f24b549d45b0ceb4a35d01bb983f45/pkg/sql/distsql_plan_set_op.go#L28)):*
> ```Go
> 	// plan removing all columns that are propagated for the sole purpose of
> 	// maintaining the ordering during stream merges.
> 	getTypesIgnoreMergeOrdering := func(plan *PhysicalPlan) []*types.T {
> ```

TBH I'm not very fond of this fix but couldn't come up with anything cleaner. I might try to get rid off `MergeOrdering` altogether, but it'll probably take me a while, so IMO it's worth fixing the problem in the meantime.

**Comment by RaduBerinde** [comment]
> we need to propagate some columns for the sole purpose of merging the physical streams into one.

This should not happen anymore, except maybe at the very root of the query.

I believe there may be some other problem that we'd be papering over. Can you walk us through an example which shows how this problem is happening? If you can simplify the query in the issue, that would be great :)

**Comment by yuzefovich** [comment]
I tried reducing the query but didn't succeed - even the removal of an unused column no longer reproduces the problem (probably because the cost of the primary index scan vs secondary index scan + index join changes). Here is the relevant part of the `opt` plan:
```
  project
   ├── columns: pk:1 col0:2
   ├── stats: [rows=333.333333]
   ├── cost: 2540.78284
   ├── key: (1)
   ├── fd: (1)-->(2), (2)~~>(1)
   ├── ordering: -2
   ├── prune: (1,2)
   ├── interesting orderings: (+1) (+2,+1)
   └── distinct-on
        ├── columns: pk:1 col0:2 col3:5 col4:6
        ├── grouping columns: pk:1
        ├── stats: [rows=333.333333]
        ├── cost: 2537.4395
        ├── key: (1)
        ├── fd: (1)-->(2,5,6), (2)~~>(1,5,6)
        ├── ordering: -2
        ├── interesting orderings: (+1) (+6) (+2,+1)
        ├── union-all
        │    ├── columns: pk:1 col0:2 col3:5 col4:6
        │    ├── left columns: pk:56 col0:57 col3:60 col4:61
        │    ├── right columns: pk:65 col0:66 col3:69 col4:70
        │    ├── stats: [rows=108.491605]
        │    ├── cost: 2528.66159
        │    ├── ordering: -2
        │    ├── interesting orderings: (+1) (+6,+2,+1) (+2,+1)
        │    ├── project
        │    │    ├── columns: pk:56 col0:57 col3:60 col4:61
        │    │    ├── stats: [rows=99.1582715, distinct(57)=98.265847, null(57)=0.991582715]
        │    │    ├── cost: 2448.29849
        │    │    ├── key: (56)
        │    │    ├── fd: (56)-->(57,60,61), (57)~~>(56,60,61)
        │    │    ├── ordering: -57
        │    │    ├── interesting orderings: (+56) (+61) (+57,+56)
        │    │    └── inner-join (lookup tab3)
        │    │         ├── columns: col3:14 pk:56 col0:57 col3:60 col4:61
        │    │         ├── key columns: [56] = [56]
        │    │         ├── lookup columns are key
        │    │         ├── stats: [rows=97.1676978, distinct(14)=97.1676978, null(14)=0, distinct(57)=97.1676978, null(57)=0]
        │    │         ├── cost: 2447.29691
        │    │         ├── key: (56)
        │    │         ├── fd: (56)-->(57,60,61), (57)-->(56,60,61), (14)==(57), (57)==(14)
        │    │         ├── ordering: -(14|57) [actual: -14]
        │    │         ├── interesting orderings: (+56) (+61) (+57,+56)
        │    │         ├── inner-join (lookup tab3@idx_tab3_2)
        │    │         │    ├── columns: col3:14 pk:56 col0:57
        │    │         │    ├── key columns: [14] = [57]
        │    │         │    ├── lookup columns are key
        │    │         │    ├── stats: [rows=97.1676978, distinct(14)=97.1676978, null(14)=0, distinct(57)=97.1676978, null(57)=0]
        │    │         │    ├── cost: 1845.81886
        │    │         │    ├── key: (56)
        │    │         │    ├── fd: (56)-->(57), (57)-->(56), (14)==(57), (57)==(14)
        │    │         │    ├── ordering: -(14|57) [actual: -14]
        │    │         │    ├── sort
        │    │         │    │    ├── columns: col3:14
        │    │         │    │    ├── stats: [rows=98.265847, distinct(14)=98.265847, null(14)=1]
        │    │         │    │    ├── cost: 1249.66498
        │    │         │    │    ├── key: (14)
        │    │         │    │    ├── ordering: -14
        │    │         │    │    └── distinct-on
        │    │         │    │         ├── columns: col3:14
        │    │         │    │         ├── grouping columns: col3:14
        │    │         │    │         ├── stats: [rows=98.265847, distinct(14)=98.265847, null(14)=1]
        │    │         │    │         ├── cost: 1233.69933
        │    │         │    │         ├── key: (14)
        │    │         │    │         └── select
        │    │         │    │              ├── columns: col1:12 col3:14 col4:15
        │    │         │    │              ├── stats: [rows=333.333333, distinct(14)=98.265847, null(14)=3.33333333]
        │    │         │    │              ├── cost: 1226.03
        │    │         │    │              ├── lax-key: (12,14,15)
        │    │         │    │              ├── fd: (12,15)~~>(14), (12,14)~~>(15)
        │    │         │    │              ├── interesting orderings: (+15,+12) (-12,+14)
        │    │         │    │              ├── scan tab3
        │    │         │    │              │    ├── columns: col1:12 col3:14 col4:15
        │    │         │    │              │    ├── stats: [rows=1000, distinct(14)=100, null(14)=10]
        │    │         │    │              │    ├── cost: 1216.01
        │    │         │    │              │    ├── lax-key: (12,14,15)
        │    │         │    │              │    ├── fd: (12,15)~~>(14), (12,14)~~>(15)
        │    │         │    │              │    ├── prune: (12,14,15)
        │    │         │    │              │    └── interesting orderings: (+15,+12) (-12,+14)
        │    │         │    │              └── filters
        │    │         │    │                   └── ((col3:14 IS NULL) OR (col1:12 < 22.54)) OR (col4:15 > 85.74) [outer=(12,14,15)]
        │    │         │    └── filters (true)
        │    │         └── filters (true)
...
```
Note how the bottom lookup join has this `ordering: -(14|57) [actual: -14]` - the project two levels up requires `-57` ordering which causes us to keep track of `col3:14` as `MergeOrdering` during the physical planning. Another weird thing is that we have `col3` twice. I think that Radu is correct in that the current fix is tampering over something else.

**Comment by RaduBerinde** [comment]
In general, we should remove all the code in distsql physical planner that adds columns because of orderings.

**Comment by yuzefovich** [comment]
I added a slightly different fix and didn't update the logic about adding new columns into the projection if they are only a part of `MergeOrdering`. The difficulty there was that `AddProjection` does the same thing and is called by `AddRendering` in some cases, so we'll need to evaluate more carefully whether the removal of this ordering-projecting business is sound.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64954)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft and @yuzefovich)

___
*[pkg/sql/distsql_physical_planner.go, line 1405 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64954#-M_OQuoO-XkU-xK1fxpK:-M_OQuoO-XkU-xK1fxpL:b14ozs7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c584c68703ecac0f9f846a03d917660ce5f7a025/pkg/sql/distsql_physical_planner.go#L1405)):*
> ```Go
> 	// Update the merge ordering according to the required ordering of
> 	// renderNode.
> 	p.SetMergeOrdering(dsp.convertOrdering(planReqOrdering(n), p.PlanToStreamColMap))
> ```

Hm, this doesn't make sense to me. The req ordering refers to columns that are output by the projection. I would instead clear the MergeOrdering before calling AddRendering, and set if afterwards (with the new map).

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64954)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/distsql_physical_planner.go, line 1405 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64954#-M_OQuoO-XkU-xK1fxpK:-M_OT9JC4aHuAJT-byOo:biiji9d) ([raw file](https://github.com/cockroachdb/cockroach/blob/c584c68703ecac0f9f846a03d917660ce5f7a025/pkg/sql/distsql_physical_planner.go#L1405)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Hm, this doesn't make sense to me. The req ordering refers to columns that are output by the projection. I would instead clear the MergeOrdering before calling AddRendering, and set if afterwards (with the new map).
</blockquote></details>

This was my initial idea for the rewrite, but I realized it could be wrong (see this [build](https://teamcity.cockroachdb.com/viewLog.html?buildId=2966540&buildTypeId=Cockroach_UnitTests) for failures). I was concerned because we could be modifying the post-processing spec of the last stage of processors in the physical plan before we are able to add the input synchronizers that enforce the necessary inter-stream ordering. This problem is quite hairy :/

Is it possible that if a `renderNode` is the root of the plan that it doesn't have `reqOrdering` set?

**Comment by yuzefovich** [comment]
I also started thinking that it would be nice to get rid of `PlanToStreamColMap` and `MergeOrdering` entirely, it would be such a nice cleanup and simplification. Do you think it is now feasible? Like I'm imagining that during the exec-building, all columns that currently can be in `MergeOrdering` would be explicitly required, and at the very root of the plan (or possibly earlier) we project them away. IIUC currently `PlanToStreamColMap` is only needed to handle the case when a column is not needed for the end result but is needed for `MergeOrdering`, so if we can get rid of the latter, we might be able to remove the former too.

I guess it might be easier to do once we finish the DistSQL spec factory.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64954)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft and @yuzefovich)

___
*[pkg/sql/distsql_physical_planner.go, line 1405 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64954#-M_OQuoO-XkU-xK1fxpK:-M_OWIXw4n2yfeGwfHX4:b-mfd6aj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c584c68703ecac0f9f846a03d917660ce5f7a025/pkg/sql/distsql_physical_planner.go#L1405)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

This was my initial idea for the rewrite, but I realized it could be wrong (see this [build](https://teamcity.cockroachdb.com/viewLog.html?buildId=2966540&buildTypeId=Cockroach_UnitTests) for failures). I was concerned because we could be modifying the post-processing spec of the last stage of processors in the physical plan before we are able to add the input synchronizers that enforce the necessary intra-stream ordering. This problem is quite hairy :/

Is it possible that if a `renderNode` is the root of the plan that it doesn't have `reqOrdering` set?
</blockquote></details>

Oh, right, it is possible at the root. I added a separate ConstructSerializingProject execution operator but we aren't treating it specially in the normal factory. I think we should set a flag for this in renderNode and use EnsureSingleStream when it's set. Then we won't need to rely on the MergeOrdering logic.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64954)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/distsql_physical_planner.go, line 1405 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64954#-M_OQuoO-XkU-xK1fxpK:-M_OoYVXAN-q4AmueiDd:bf0p6yt) ([raw file](https://github.com/cockroachdb/cockroach/blob/c584c68703ecac0f9f846a03d917660ce5f7a025/pkg/sql/distsql_physical_planner.go#L1405)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Oh, right, it is possible at the root. I added a separate ConstructSerializingProject execution operator but we aren't treating it specially in the normal factory. I think we should set a flag for this in renderNode and use EnsureSingleStream when it's set. Then we won't need to rely on the MergeOrdering logic.
</blockquote></details>

Hm, this sounds like a problem, but I don't think that's what's happening here - in the plan I posted above the relevant `renderNode` is not the root of the tree, so it isn't created by `ConstructSerializingProject`. Something else is off.

**Review by yuzefovich — COMMENTED** [review]
Simplifying the plan from above
```
  project
   └── distinct-on
        ├── ordering: -2
        ├── union-all
        │    ├── columns: pk:1 col0:2 col3:5 col4:6
        │    ├── left columns: pk:56 col0:57 col3:60 col4:61
        │    ├── right columns: pk:65 col0:66 col3:69 col4:70
        │    ├── ordering: -2
        │    ├── project
        │    │    ├── columns: pk:56 col0:57 col3:60 col4:61
        │    │    ├── ordering: -57
        │    │    └── inner-join (lookup tab3)
        │    │         ├── columns: col3:14 pk:56 col0:57 col3:60 col4:61
        │    │         ├── ordering: -(14|57) [actual: -14]
        │    │         ├── inner-join (lookup tab3@idx_tab3_2)
        │    │         │    ├── columns: col3:14 pk:56 col0:57
        │    │         │    ├── key columns: [14] = [57]
        │    │         │    ├── lookup columns are key
        │    │         │    ├── ordering: -(14|57) [actual: -14]
        │    │         │    ├── sort
        │    │         │    │    ├── columns: col3:14
        │    │         │    │    ├── ordering: -14
        │    │         │    │    └── distinct-on
        │    │         │    │         ├── columns: col3:14
...
```
what we have currently is that during the physical planning, the left arm of UNION ALL thinks that it returns 4 columns `pk:56 col0:57 col3:60 col4:61`, but `MergeOrdering` on the arm is set to include `col3:14` (`col0:57` equals to that column based on the lookup). Because of this, the physical planning includes `col3:14` as the fifth column to be projected by the left arm which trips up the logic to merge two arms.

I'm wondering whether the optimizer is incorrect in choosing the column over which ordering is kept here `ordering: -(14|57) [actual: -14]` since up the tree we don't care about `col3:14` anymore, starting from the top lookup join. I imagine it would fix the issue in this plan, but I'm not certain whether no other similar issues remain.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64954#-:-M_Or3SyCZrAZF2NMrOb:bbyiy4w)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

**Review by RaduBerinde — COMMENTED** [review]
What the optimizer produces is correct. The optimizer is essentially telling us: if you need to merge streams before the project, merge them by column 14; if you need to merge streams after the project, merge them by column 57. This is correct because they are equal.

The problem is that the legacy code is trying to hold on to that column 14. This should be addressed by clearing MergeOdering before AddRendering.

> I also started thinking that it would be nice to get rid of PlanToStreamColMap and MergeOrdering entirely

I think we could in principle. There may be some difficulties - for example, there are some "paired" lookup joins for geospatial which I believe use an extra column that isn't reflected in the logical operator. Also I we would still need to remember the merge ordering for whenever we decide to merge streams (but the logic around it would be very simple).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64954#-:-M_OtjtUCgzLYaJSpkHM:bn40d4k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

**Review by RaduBerinde — COMMENTED** [review]
This change is pretty much what I have in mind: 
https://github.com/RaduBerinde/cockroach/commit/8ce4ba6a0e7889c1ada8ce0e52b33928e74fbf4c

It passes the fakedist and 5node logic tests (modulo some minor distsql plan changes) and there is no more code that adds columns because of orderings.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64954#-:-M_PBELeAD8JDC55XoSX:b-guviz4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

**Review by yuzefovich — COMMENTED** [review]
Thanks! Your commit makes sense, I modified a few things noted below.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64954#-:-M_SC1KW50zYMKf_N5M6:b-y1h2kj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/distsql_physical_planner.go, line 2036 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64954#-M_SC9xE6FHgaiXY8i97:-M_SC9xE6FHgaiXY8i98:b-5xbfjz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec81305983696eb2fbe1ef1b9305fcffb62c7d4f/pkg/sql/distsql_physical_planner.go#L2036)):*
> ```Go
> 	// Calculate the new merge ordering based on the projection.
> 	oldMergeOrdering := plan.MergeOrdering
> 	newMergeOrdering := execinfrapb.Ordering{Columns: make([]execinfrapb.Ordering_Column, len(plan.MergeOrdering.Columns))}
> ```

In your patch we used an empty ordering here, but I believe this might be incorrect, so I added this remapping logic. Am I missing something? Could we just ignore the merge ordering on the plan here?
___
*[pkg/sql/opt_exec_factory.go, line 314 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64954#-M_SCSnH8uRJ1dCp7ZCv:-M_SCSnH8uRJ1dCp7ZCw:b-vvb5o6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec81305983696eb2fbe1ef1b9305fcffb62c7d4f/pkg/sql/opt_exec_factory.go#L314)):*
> ```Go
> 		return nil, err
> 	}
> 	// If we pulled up a spoolNode, we don't need to materialize the ordering
> ```

I also made minor changes here. But I'm still wondering why is it ok to not materialize things if `res` is not a `renderNode` - this would contradict the comment on `ConstructSerializingProject`. I took a guess about `spoolNode` being ok but curious what is the reasoning in general.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64954)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft and @yuzefovich)

___
*[pkg/sql/distsql_physical_planner.go, line 2036 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64954#-M_SC9xE6FHgaiXY8i97:-M_SDiCG--1YPrbB2Xj1:b-odt2jf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec81305983696eb2fbe1ef1b9305fcffb62c7d4f/pkg/sql/distsql_physical_planner.go#L2036)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

In your patch we used an empty ordering here, but I believe this might be incorrect, so I added this remapping logic. Am I missing something? Could we just ignore the merge ordering on the plan here?
</blockquote></details>

I should have left a comment. The merge ordering only does something if we join streams. Here we know for sure that we won't join anything before the next stage (AddNoGroupingStage or AddSingleGroupStage if there is a single stream). We do set the correct output ordering with `AddNoGroupingStage`.
___
*[pkg/sql/opt_exec_factory.go, line 314 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64954#-M_SCSnH8uRJ1dCp7ZCv:-M_SFFUV1ibf1hvERzsj:b2ys20s) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec81305983696eb2fbe1ef1b9305fcffb62c7d4f/pkg/sql/opt_exec_factory.go#L314)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I also made minor changes here. But I'm still wondering why is it ok to not materialize things if `res` is not a `renderNode` - this would contradict the comment on `ConstructSerializingProject`. I took a guess about `spoolNode` being ok but curious what is the reasoning in general.
</blockquote></details>

Yeah spoolNode means things are not distributed anyway. I don't think there are other possibilities here, we could change to a `switch res.(type)`.

We can also leave a TODO to not push renderings through spoolNode (I doubt we need it, it's there since the heuristic planner).

I don't remember the overall reasoning and logic around spoolNode - it might be trying to fix things that we already fixed since, maybe we can remove it altogether now.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64954)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/distsql_physical_planner.go, line 2036 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64954#-M_SC9xE6FHgaiXY8i97:-M_SQbSiADXjZrAAOWtX:b-nevox1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec81305983696eb2fbe1ef1b9305fcffb62c7d4f/pkg/sql/distsql_physical_planner.go#L2036)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I should have left a comment. The merge ordering only does something if we join streams. Here we know for sure that we won't join anything before the next stage (AddNoGroupingStage or AddSingleGroupStage if there is a single stream). We do set the correct output ordering with `AddNoGroupingStage`.
</blockquote></details>

Ack, makes sense. Added a comment.
___
*[pkg/sql/opt_exec_factory.go, line 314 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64954#-M_SCSnH8uRJ1dCp7ZCv:-M_SVEjW6PboML-057ll:b-g1hs46) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec81305983696eb2fbe1ef1b9305fcffb62c7d4f/pkg/sql/opt_exec_factory.go#L314)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Yeah spoolNode means things are not distributed anyway. I don't think there are other possibilities here, we could change to a `switch res.(type)`.

We can also leave a TODO to not push renderings through spoolNode (I doubt we need it, it's there since the heuristic planner).

I don't remember the overall reasoning and logic around spoolNode - it might be trying to fix things that we already fixed since, maybe we can remove it altogether now.
</blockquote></details>

Makes sense, done.
___
*[pkg/sql/opt_exec_factory.go, line 298 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64954#-M_SVJjq-03M9-YYeMVB:-M_SVJjr8Y_P9So0_S1_:b75d5pd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c8f1928089b2e0a4a5dd5ab0167aecedf07ac4/pkg/sql/opt_exec_factory.go#L298)):*
> ```Go
> 				inputCols[i].Name = colNames[i]
> 			}
> 			if r, ok := n.(*renderNode); ok {
> ```

I'm still concerned about this case a bit though - IIUC we can have any type of node here, if we're simply renaming the columns, so we might be breaking the contract of the serializing project.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64954)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde, @rytaft, and @yuzefovich)

___
*[pkg/sql/opt_exec_factory.go, line 298 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64954#-M_SVJjq-03M9-YYeMVB:-M_Sg9XECtOUcnmfj4LS:b-2qimvh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c8f1928089b2e0a4a5dd5ab0167aecedf07ac4/pkg/sql/opt_exec_factory.go#L298)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I'm still concerned about this case a bit though - IIUC we can have any type of node here, if we're simply renaming the columns, so we might be breaking the contract of the serializing project.
</blockquote></details>

Yeah.. This only happens at the top of the query, where we are about to serialize everything anyway. You can leave a TODO to clean this up. I hesitate to add a renderNode in all cases, given that this is always used at the root.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64954)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/opt_exec_factory.go, line 298 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/64954#-M_SVJjq-03M9-YYeMVB:-M_SrHa2EnZv_hWZqASY:b5j9xfp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4c8f1928089b2e0a4a5dd5ab0167aecedf07ac4/pkg/sql/opt_exec_factory.go#L298)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Yeah.. This only happens at the top of the query, where we are about to serialize everything anyway. You can leave a TODO to clean this up. I hesitate to add a renderNode in all cases, given that this is always used at the root.
</blockquote></details>

Ok, left a TODO.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64954#-:-M_TlK5H5m_9c9i0I63t:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft and @yuzefovich)

___
*[pkg/sql/distsql_physical_planner.go, line 1401 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/64954#-M_TlkGXC2DOl-fnj2ig:-M_TlkGXC2DOl-fnj2ih:b-bu6qfx) ([raw file](https://github.com/cockroachdb/cockroach/blob/1450fa0fcd482d3c1c2ff31c9b63499bbd2f2367/pkg/sql/distsql_physical_planner.go#L1401)):*
> ```Go
> 		return err
> 	}
> 	if n.serialize {
> ```

If we want to avoid many of the distsql plan changes (which are mildly negative), we could be smarter here and call `EnsureSingleStreamOnGateway()` after the projection if `n.MergeOrdering` is empty. That way we would still project away columns before moving data between nodes in common cases.

I will think about how to clean this up. I think I should do separate factory methods for the "serializing" thing and column renaming/projection.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64954)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/distsql_physical_planner.go, line 1401 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/64954#-M_TlkGXC2DOl-fnj2ig:-M_To_ouCttKGauaBlNY:b-b2ktmp) ([raw file](https://github.com/cockroachdb/cockroach/blob/1450fa0fcd482d3c1c2ff31c9b63499bbd2f2367/pkg/sql/distsql_physical_planner.go#L1401)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

If we want to avoid many of the distsql plan changes (which are mildly negative), we could be smarter here and call `EnsureSingleStreamOnGateway()` after the projection if `n.MergeOrdering` is empty. That way we would still project away columns before moving data between nodes in common cases.

I will think about how to clean this up. I think I should do separate factory methods for the "serializing" thing and column renaming/projection.
</blockquote></details>

That's a good point about mildly negative changes - I also thought about that but realized that with the current solution in general we have to accept the cost.

I like your suggestion about deferring the serialization if the merge ordering is empty, implemented.

**Review by RaduBerinde — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64954#-:-M_U4Pig2K2wz2_fgetV:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft and @yuzefovich)

___
*[pkg/sql/distsql_physical_planner.go, line 2036 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/64954#-M_TmSK25NUHdkYlOg6y:-M_TmSK25NUHdkYlOg6z:bce78c3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1450fa0fcd482d3c1c2ff31c9b63499bbd2f2367/pkg/sql/distsql_physical_planner.go#L2036)):*
> ```Go
> 	// Note that we're using an empty merge ordering because we know for sure
> 	// that we won't join streams before the next stage (below, we call either
> 	// AddNoGroupingStage or AddSingleGroupStage, and neither function joins the
> ```

[nit] AddSingleGroupStage does merge streams, but we only call it when there is a single stream.

**Comment by yuzefovich** [comment]
Thanks a lot for working on this thorny issue with me!

bors r+

**Comment by yuzefovich** [comment]
bors r-

Didn't realize there was another nit.

**Review by yuzefovich — COMMENTED** [review]
Addressed the nit.

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64954#-:-M_U6Dca87jv66rmlsXH:br45id1)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

**Pull request merged**
