### PR TITLE
sql: add cluster setting to gate PLACEMENT operations

### LINKED ISSUE #68598: sql: add cluster setting for PLACEMENT operations
In #68433, syntax is being added to remove non-voting replicas from a database zone configuration. This should not be exposed to users by default; we want to this to be a last-resort option for users who can't wait for domiciling functionality. Therefore, we should put it behind an experimental cluster setting.

### PR DESCRIPTION
**Pull request by pawalt**
Previously, PLACEMENT operations were allowed by default. We want to
hide these unless the user explicitly enables them, however, so this PR
adds the `sql.defaults.experimental_domiciling` cluster setting to gate
them.

Release note: None

Resolves #68598

### CODE REVIEW

**Review by arulajmani — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69005)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @pawalt)

___
*[pkg/sql/create_database.go, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69005#-MhFLeP439TMwR1kE7jH:-MhFLeP439TMwR1kE7jI:boz4y1r) ([raw file](https://github.com/cockroachdb/cockroach/blob/4be32a0f80ba46d7e0e0ae598fa1aa12f037c15e/pkg/sql/create_database.go#L100)):*
> ```Go
> 		if !p.EvalContext().SessionData.PlacementEnabled {
> 			return nil, pgerror.New(
> 				pgcode.InvalidDatabaseDefinition,
> ```

Feature not supported instead, maybe?
___
*[pkg/sql/create_database.go, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69005#-MhFL-v46smWoQAxA58A:-MhFL-v46smWoQAxA58B:b-ldm0yy) ([raw file](https://github.com/cockroachdb/cockroach/blob/4be32a0f80ba46d7e0e0ae598fa1aa12f037c15e/pkg/sql/create_database.go#L101)):*
> ```Go
> 			return nil, pgerror.New(
> 				pgcode.InvalidDatabaseDefinition,
> ```

extra line?
___
*[pkg/sql/create_database.go, line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69005#-MhFL5zi0O4tUyS5RnzL:-MhFL5zi0O4tUyS5RnzM:bvicrm9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4be32a0f80ba46d7e0e0ae598fa1aa12f037c15e/pkg/sql/create_database.go#L102)):*
> ```Go
> 				pgcode.InvalidDatabaseDefinition,
> 
> 				"PLACEMENT requires that the cluster setting sql.defaults.experimental_placement "+
> ```

Should we be referencing the session setting here instead as the cluster setting only serves as a default?

Also, let's put the exact session setting that the user might need to change in the HINT message. It's nice to have these things copy-paste-able. 
___
*[pkg/sql/exec_util.go, line 236 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69005#-MhFK8aaB6uTetG-lz2T:-MhFK8abCmKWDYO2d-8v:bz0nebc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4be32a0f80ba46d7e0e0ae598fa1aa12f037c15e/pkg/sql/exec_util.go#L236)):*
> ```Go
> 
> var placementEnabledClusterMode = settings.RegisterBoolSetting(
> 	"sql.defaults.experimental_placement.enabled",
> ```

Let's call this `sql.defaults.multiregion_placement_policy.enabled`? 

Last I heard we were moving away from "experimental" in cluster settings/syntax etc.
___
*[pkg/sql/vars.go, line 1258 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69005#-MhFKbQK-zEIMV4Q_9Ar:-MhFKbQK-zEIMV4Q_9As:b-oekyrk) ([raw file](https://github.com/cockroachdb/cockroach/blob/4be32a0f80ba46d7e0e0ae598fa1aa12f037c15e/pkg/sql/vars.go#L1258)):*
> ```Go
> 
> 	// CockroachDB extension.
> 	`experimental_enable_placement`: {
> ```

Same as above, instead of `experimental_enable_placement`, let's call this `enable_multiregion_placement_policy` instead. 
___
*[pkg/sql/sessiondatapb/local_only_session_data.proto, line 170 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69005#-MhFKvPY5aL7Tf1RmnAX:-MhFKvPY5aL7Tf1RmnAY:be8a23z) ([raw file](https://github.com/cockroachdb/cockroach/blob/4be32a0f80ba46d7e0e0ae598fa1aa12f037c15e/pkg/sql/sessiondatapb/local_only_session_data.proto#L170)):*
> ```protobuf
> 
>   // PlacementEnabled indicates whether PLACEMENT can be used or not.
>   bool placement_enabled = 44;
> ```

Why do we need this?

**Review by pawalt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69005)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @otan)

___
*[pkg/sql/create_database.go, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69005#-MhFLeP439TMwR1kE7jH:-MhK6SFh-cWUpcXUVix-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4be32a0f80ba46d7e0e0ae598fa1aa12f037c15e/pkg/sql/create_database.go#L100)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Feature not supported instead, maybe?
</blockquote></details>

Done.
___
*[pkg/sql/create_database.go, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69005#-MhFL-v46smWoQAxA58A:-MhK6SSB-hMK3werXy-s:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4be32a0f80ba46d7e0e0ae598fa1aa12f037c15e/pkg/sql/create_database.go#L101)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

extra line?
</blockquote></details>

Done.
___
*[pkg/sql/create_database.go, line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69005#-MhFL5zi0O4tUyS5RnzL:-MhK7oZk9rs7OIB_7845:b-6s2crs) ([raw file](https://github.com/cockroachdb/cockroach/blob/4be32a0f80ba46d7e0e0ae598fa1aa12f037c15e/pkg/sql/create_database.go#L102)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Should we be referencing the session setting here instead as the cluster setting only serves as a default?

Also, let's put the exact session setting that the user might need to change in the HINT message. It's nice to have these things copy-paste-able. 
</blockquote></details>

I'll put the session setting in the main error and cluster setting in the hint so they know where to go for long-term changes.
___
*[pkg/sql/exec_util.go, line 236 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69005#-MhFK8aaB6uTetG-lz2T:-MhKB57gBS7yMiyjdfv7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4be32a0f80ba46d7e0e0ae598fa1aa12f037c15e/pkg/sql/exec_util.go#L236)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Let's call this `sql.defaults.multiregion_placement_policy.enabled`? 

Last I heard we were moving away from "experimental" in cluster settings/syntax etc.


</blockquote></details>

Done.
___
*[pkg/sql/vars.go, line 1258 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69005#-MhFKbQK-zEIMV4Q_9Ar:-MhKB5PqAjHaWetrsVHT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4be32a0f80ba46d7e0e0ae598fa1aa12f037c15e/pkg/sql/vars.go#L1258)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Same as above, instead of `experimental_enable_placement`, let's call this `enable_multiregion_placement_policy` instead. 
</blockquote></details>

Done.
___
*[pkg/sql/sessiondatapb/local_only_session_data.proto, line 170 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69005#-MhFKvPY5aL7Tf1RmnAX:-MhK6rNb7sRnoeEnDcYs:bx9f54j) ([raw file](https://github.com/cockroachdb/cockroach/blob/4be32a0f80ba46d7e0e0ae598fa1aa12f037c15e/pkg/sql/sessiondatapb/local_only_session_data.proto#L170)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Why do we need this? 
</blockquote></details>

@otan moved our session setting from an enum to proto, so we've gotta add this here.

**Review by arulajmani — APPROVED** [review]
:lgtm: once the commit message is updated 

> Reviewed 1 of 13 files at r1, 1 of 1 files at r2, 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69005#-:-MhLznFi03JhUl474eUW:b-rm183s)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan and @pawalt)

___
*[-- commits, line 6 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69005#-MhLyLfe13s_NA2Y-mHm:-MhLyLfe13s_NA2Y-mHn:b-vkh5ej) ([raw file](https://github.com/cockroachdb/cockroach/blob/77c6806264161af6dddd888948e3239d82748e82/-- commits#L6)):*
I think your commit message needs an update with the new session/cluster settings in. 

Also, add a nod to the fact that you're intentionally skipping on the release note here and why. 
___
*[pkg/sql/create_database.go, line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69005#-MhFL5zi0O4tUyS5RnzL:-MhLz9FWDUrRPNB96t0B:bsq01e9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4be32a0f80ba46d7e0e0ae598fa1aa12f037c15e/pkg/sql/create_database.go#L102)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

I'll put the session setting in the main error and cluster setting in the hint so they know where to go for long-term changes.
</blockquote></details>

Maybe I'm lazy, but I really like when I can just copy paste the exact session setting I need to change instead of deciphering a hint message. Maybe something like "you can enable multi-region placement policy by running `SET enable_multiregion_placement_policy = true` in the hint. 

Your call! 
___
*[pkg/sql/sessiondatapb/local_only_session_data.proto, line 170 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69005#-MhFKvPY5aL7Tf1RmnAX:-MhLyILnC8m4aCqTFnHr:b-812qdr) ([raw file](https://github.com/cockroachdb/cockroach/blob/4be32a0f80ba46d7e0e0ae598fa1aa12f037c15e/pkg/sql/sessiondatapb/local_only_session_data.proto#L170)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

@otan moved our session setting from an enum to proto, so we've gotta add this here.
</blockquote></details>

TIL!

**Review by pawalt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69005)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani and @otan)

___
*[-- commits, line 6 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69005#-MhLyLfe13s_NA2Y-mHm:-MhOmWjhCo_D0cgCLKh_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/77c6806264161af6dddd888948e3239d82748e82/-- commits#L6)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I think your commit message needs an update with the new session/cluster settings in. 

Also, add a nod to the fact that you're intentionally skipping on the release note here and why. 
</blockquote></details>

Done.
___
*[pkg/sql/create_database.go, line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69005#-MhFL5zi0O4tUyS5RnzL:-MhOlvrjCLqgwVFBqikN:b-dxcbu5) ([raw file](https://github.com/cockroachdb/cockroach/blob/4be32a0f80ba46d7e0e0ae598fa1aa12f037c15e/pkg/sql/create_database.go#L102)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Maybe I'm lazy, but I really like when I can just copy paste the exact session setting I need to change instead of deciphering a hint message. Maybe something like "you can enable multi-region placement policy by running `SET enable_multiregion_placement_policy = true` in the hint. 

Your call! 
</blockquote></details>

Makes sense!

**Comment by arulajmani** [comment]
I think one of your tests is failing because you need to now turn on this cluster setting for it. That, and this needs a rebase. Should be good to go in after!

**Comment by pawalt** [comment]
bors r=arulajmani

**Pull request merged**
