### PR TITLE
roachtest: import-cancellation: run with and without range tombstones

### PR DESCRIPTION
**Pull request by nicktrav**
Currently, the `import-cancellation` roachtest is intended to exercise range tombstone functionality via the repeated cancellation of imports. This test has caught a number of issues unrelated to range tombstones / range keys themselves.

Add a second variant of the test that runs both with and without range tombstones enabled.

Touches #90948.
Epic: CRDB-20465.

Release note: None.

### CODE REVIEW

**Comment by nicktrav** [comment]
Doing a few manual runs [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=7301814&tab=buildLog#_state=5412) and [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=7302930&buildTypeId=Cockroach_Nightlies_RoachtestStress&tab=buildLog).

**Review by msbutler — APPROVED** [review]

**Review by jbowens — APPROVED** [review]
:lgtm:

**Review by erikgrinaker — APPROVED** [review]

**Comment by nicktrav** [comment]
TFTRs!

bors r+

**Comment by nicktrav** [comment]
bors retry

**Pull request merged**
