### PR TITLE
sql: clean up code for pg_description

### PR DESCRIPTION
**Pull request by rafiss**
By including builtin function comments in
crdb_internal.kv_catalog_comments, we can remove a lot of corner case handling in the pg_description table generation code.

informs #103106
Release note: None

### CODE REVIEW

**Review by fqazi — APPROVED** [review]
:lgtm: Nice work and this clean this up a bit.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103257#-:-NVUenzy-IUo7eTnXUBY:b5axllk)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/crdb_internal.go` line 5439 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103257#-NVUefjk29eSVk7Hp346:-NVUefjk29eSVk7Hp347:bcimn6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/13fc256de36ba7c04c3ebcba1b242d07943b5fce/pkg/sql/crdb_internal.go#L5439)):*
> ```Go
> 		}
> 		// Loop over all builtin function comments.
> 		for _, name := range builtins.AllBuiltinNames() {
> ```

Maybe a TODO to push this all down into the collections?

**Comment by rafiss** [comment]
tftr!

bors r=fqazi

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103257)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @fqazi)

___
*[`pkg/sql/crdb_internal.go` line 5439 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103257#-NVUefjk29eSVk7Hp346:-NVUsdRG3LXn1knGK0sC:b2gbf6k) ([raw file](https://github.com/cockroachdb/cockroach/blob/13fc256de36ba7c04c3ebcba1b242d07943b5fce/pkg/sql/crdb_internal.go#L5439)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Maybe a TODO to push this all down into the collections?
</blockquote></details>

good idea; done

**Comment by rafiss** [comment]
blathers backport 23.1

**Pull request merged**
