### PR TITLE
bazel: use pre-built archives of the c-deps

### LINKED ISSUE #77135: bazel: archive prebuilt versions of `krb5`, `geos`
In CI, when the build is cold (it usually is), tests are often bottlenecked on building these two libraries. The logic tests can't start without them and they take a very long time to run, so we can work around the problem by avoiding the build altogether and just downloading prebuilt versions.

`krb5` only needs a Linux build. `geos` needs a Linux build to get the CI advantages but we might just expose it for all OS's so everyone can download a prebuilt version.

Epic CRDB-8306

Jira issue: CRDB-13427

### PR DESCRIPTION
**Pull request by rickystewart**
Up until this point we've required building all of the `c-deps` via
`rules_foreign_cc`. This has a couple downsides: the build is not
parallelized (https://github.com/cockroachdb/cockroach/issues/77207), and while in principle developers should be able
to build it once and then reuse the cached version forever, in practice
this is not really the case (https://github.com/cockroachdb/cockroach/issues/76851). To this point we pre-build these
libraries and add the requisite glue so that Bazel can download and link
them in.

1. Rename all the `c-deps:libX` targets to `c-deps:libX_foreign`.
2. `libproj`, `libjemalloc`, and `libkrb5` are updated to compile w/
   `-fPIC` unless `force_build_cdeps` is set.
3. Add a script `c-deps/buildcdeps.sh` that builds all the
   `libX_foreign` libraries in the various cross-configurations.
4. Add a script `build-and-publish-cdeps.sh` that can be invoked from
   TeamCity to build all the `c-deps` and push them to GCS.
5. Add `c-deps/archived.bzl` to wrap all the pre-compiled libraries
   from above.
6. Now `libgeos` is no longer (necessarily) found in
   `bazel-bin/c-deps/libgeos`, so we need to update a few places so it
   can continue to be found: `bazci`, `publish-artifacts`, and
   `publish-provisional-artifacts`, and `pkg/geos`.

You can still force building the `c-deps` from scratch with
`--force_build_cdeps`. Doing so will compile the `c-deps` WITHOUT
`-fPIC`; the release pipeline is updated to use this to avoid any
performance regression. You still must compile the `c-deps` from scratch
on unsupported operating systems (OS's other than Linux, macOS, and
Windows).

Closes https://github.com/cockroachdb/cockroach/issues/77135.

### CODE REVIEW

**Review by mari-crl — APPROVED** [review]
Rad!! Sorry for the delay here! :lgtm:

> Reviewed 1 of 1 files at r1, 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79808#-:-N02EyJz13BOEZLORbIk:bxx0ett)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rickystewart)

**Comment by rickystewart** [comment]
TFTR! 

bors=mari-crl

**Comment by rickystewart** [comment]
bors r=mari-crl

**Comment by otan** [comment]
is this causing roachtests to fail?

https://teamcity.cockroachdb.com/viewLog.html?buildId=4962200&tab=buildResultsDiv&buildTypeId=Cockroach_Nightlies_RoachtestNightlyGceBazel

```
[05:18:14]++ cp /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-opt/bin/c-deps/libgeos/lib/libgeos.so lib.docker_amd64
[05:18:14]cp: cannot stat '/home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-opt/bin/c-deps/libgeos/lib/libgeos.so': No such file or directory
[05:18:14]+ remove_files_on_exit
[05:18:14]+ rm -f /home/roach/.ssh/id_rsa /home/roach/.ssh/id_rsa.pub
```

**Pull request merged**
