### PR TITLE
libroach: clean up includes

### PR DESCRIPTION
**Pull request by tbg**
The stringprintf import has the unappealing side effect that it confuses
VSCode's IntelliSense into believing that va_args is defined in

`c-deps/protobuf/src/google/protobuf/stubs/stringprintf.cc`

```
// Define va_copy for MSVC. This is a hack, assuming va_list is simply a
// pointer into the stack and is safe to copy.
```

(which is not reasonable seeing that this definition is sufficiently
guarded).

Since it's not needed in `db.cc`, remove it.

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[c-deps/libroach/db.cc, line 15 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21582#-L3EJpXLUuhsrrseCmaW:-L3EJpXLUuhsrrseCmaX:bhxd7h7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ba95069304a131b4825a6a9c635f2c6de359756/c-deps/libroach/db.cc#L15)):*
> ```cpp
> // permissions and limitations under the License.
> 
> #include <stdarg.h>
> ```

Did you run this through `clang-format`? I thought it placed `db.h` first.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21582#-:-L3EJoTyMLKZnGsOJrQ8:bnfp4nl)*

**Review by benesch — APPROVED** [review]

**Comment by tschottdorf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[c-deps/libroach/db.cc, line 15 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21582#-L3EJpXLUuhsrrseCmaW:-L3EKwgzZrvwIjR3tYoL:b-1nyef3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ba95069304a131b4825a6a9c635f2c6de359756/c-deps/libroach/db.cc#L15)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Did you run this through `clang-format`? I thought it placed `db.h` first.
</blockquote></details>

Nope, it leaves it alone. (via `make c-deps-fmt`).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21582)*

**Comment by tschottdorf** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[c-deps/libroach/db.cc, line 15 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21582#-L3EJpXLUuhsrrseCmaW:-L3ELWexrqwAxc1W2TJC:bi2e83z) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ba95069304a131b4825a6a9c635f2c6de359756/c-deps/libroach/db.cc#L15)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Nope, it leaves it alone. (via `make c-deps-fmt`).
</blockquote></details>

Actually it did move it. Updated the PR. (I thought it would exit nonzero if it did anything).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21582)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21582#-:-L3EZ_N14xCvnJEq-HWO:bnfp4nl)*

**Comment by tschottdorf** [comment]
TFTRs!

**Pull request merged**
