### PR TITLE
kvserver: don't call Processor.AdmitRaftMuLocked while holding Replic…

### LINKED ISSUE #132637: kv/kvserver: TestFlowControlBasicV2 failed
kv/kvserver.TestFlowControlBasicV2 [failed](https://tanzanite.cluster.engflow.com/invocations/default/d1526788-0651-4582-b52a-0c0c23d50dd2?testReportRun=1&testReportShard=11&testReportAttempt=1#targets-Ly9wa2cva3Yva3ZzZXJ2ZXI6a3ZzZXJ2ZXJfdGVzdA==) on master @ [a1b013e763abd1454603985996a45663b6e6bcad](https://github.com/cockroachdb/cockroach/commits/a1b013e763abd1454603985996a45663b6e6bcad):

```
github.com/cockroachdb/cockroach/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go:2117 rac2.(*replicaState).handleReadyEntries ??? <<<<<
github.com/cockroachdb/cockroach/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go:2116 rac2.(*replicaState).handleReadyEntries ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go:1080 rac2.(*rangeController).HandleRaftEventRaftMuLocked ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go:775 replica_rac2.(*processorImpl).HandleRaftReadyRaftMuLocked ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:977 kvserver.(*Replica).handleRaftReadyRaftMuLocked ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:809 kvserver.(*Replica).handleRaftReady ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:681 kvserver.(*Store).processReady ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:420 kvserver.(*raftSchedulerShard).worker ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:319 kvserver.(*raftScheduler).Start.func2 ???
github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:498 stop.(*Stopper).RunAsyncTaskEx.func2 ???

happened after
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/flow_control_replica_integration.go:477 kvserver.(*replicaForRACv2).MuLock ??? <<<<<
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica.go:181 kvserver.(*ReplicaMutex).Lock ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/flow_control_replica_integration.go:476 kvserver.(*replicaForRACv2).MuLock ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/kvflowcontrol/replica_rac2/raft_node.go:71 replica_rac2.raftNodeForRACv2.SendMsgAppRaftMuLocked ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go:2458 rac2.(*replicaSendStream).handleReadyEntriesLocked ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go:2121 rac2.(*replicaState).handleReadyEntries ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go:1080 rac2.(*rangeController).HandleRaftEventRaftMuLocked ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go:775 replica_rac2.(*processorImpl).HandleRaftReadyRaftMuLocked ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:977 kvserver.(*Replica).handleRaftReadyRaftMuLocked ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:809 kvserver.(*Replica).handleRaftReady ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:681 kvserver.(*Store).processReady ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:420 kvserver.(*raftSchedulerShard).worker ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:319 kvserver.(*raftScheduler).Start.func2 ???
github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:498 stop.(*Stopper).RunAsyncTaskEx.func2 ???

Other goroutines holding locks:
goroutine 7218973 lock 0xc003295be8
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:808 kvserver.(*Replica).handleRaftReady ??? <<<<<
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:807 kvserver.(*Replica).handleRaftReady ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:681 kvserver.(*Store).processReady ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:420 kvserver.(*raftSchedulerShard).worker ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:319 kvserver.(*raftScheduler).Start.func2 ???
github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:498 stop.(*Stopper).RunAsyncTaskEx.func2 ???

goroutine 7218973 lock 0xc01796b888
github.com/cockroachdb/cockroach/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go:2117 rac2.(*replicaState).handleReadyEntries ??? <<<<<
github.com/cockroachdb/cockroach/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go:2116 rac2.(*replicaState).handleReadyEntries ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go:1080 rac2.(*rangeController).HandleRaftEventRaftMuLocked ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go:775 replica_rac2.(*processorImpl).HandleRaftReadyRaftMuLocked ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:977 kvserver.(*Replica).handleRaftReadyRaftMuLocked ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:809 kvserver.(*Replica).handleRaftReady ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:681 kvserver.(*Store).processReady ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:420 kvserver.(*raftSchedulerShard).worker ???
github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:319 kvserver.(*raftScheduler).Start.func2 ???
github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:498 stop.(*Stopper).RunAsyncTaskEx.func2 ???



```

Parameters:
 - <code>attempt=1</code>
 - <code>deadlock=true</code>
 - <code>run=1</code>
 - <code>shard=11</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestFlowControlBasicV2.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-43193

### PR DESCRIPTION
**Pull request by sumeerbhola**
…a.mu

This method will eventually acquire replicaSendStream.mu, which needs to be ordered before Replica.mu.

Fixes #132637 #132638 #132639 #132640 #132641 #132642 #132643 #132644 #132645 #132646 #132647 #132648 #132649

Epic: CRDB-37515

Release note: None

### CODE REVIEW

**Review by kvoli — APPROVED** [review]

**Review by pav-kv — APPROVED** [review]

**Review by sumeerbhola — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132676#-:-O9GDLmuBziw2i2kUTT7:bz5mair)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @pav-kv)

___
*[`pkg/kv/kvserver/replica_raft.go` line 720 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132676#gh-1801602612:-O9GDGjh7CeQXuR8amr4:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f9568df8019bd975fdba84c23265828aa877d0fb/pkg/kv/kvserver/replica_raft.go#L720)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Could follow the pattern above, and only check `Term != 0`.
</blockquote></details>

Done

**Comment by sumeerbhola** [comment]
bors r=kvoli,pav-kv

**Comment by michae2** [comment]
I just got [this failure](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelExtendedCi/17413258?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true) on release-24.3. Does this need to be backported?

**Comment by sumeerbhola** [comment]
This preceded the branch cut. And the failure in `TestFlowControlRaftMembershipV2/v2_enabled_when_leader_level=2/kvadmission.flow_control.mode=apply_to_elastic` seems to be one of those non-deterministic test failures that @kvoli is looking at.

**Pull request merged**
