### PR TITLE
storage: Give Store.pendingRaftGroups its own mutex

### LINKED ISSUE #4881: stability: OOM from too many goroutines
build sha: 6188995f5f0868ee57378a0e7e507dea80e3cd38

Full log for that node (run through panic parse): 
[node1.crash.parsed.txt](https://github.com/cockroachdb/cockroach/files/159873/node1.crash.parsed.txt)

Biggest stack traces by # of goroutines:
```
1188930: semacquire [0~2 minutes] [Created by storage.(*Store).enqueueRaftUpdateCheck @ store.go:1736]
    sync       sema.go:47              runtime_Semacquire(#1013)
    sync       mutex.go:83             (*Mutex).Lock(#1012)
    storage    store.go:1729           (*Store).enqueueRaftUpdateCheck.func1(#2, 0x1)
137637: semacquire [1~463 minutes] [Created by rpc.syncAdapter.exec @ server.go:51]
    sync       sema.go:47              runtime_Semacquire(*)
    sync       waitgroup.go:127        (*WaitGroup).Wait(*)
    storage    replica.go:732          (*Replica).beginCmds(#3, *, 0xd)
    storage    replica.go:901          (*Replica).addWriteCmd(#3, #1390983, *, *, 0, #37, 0xa, 0x1, 0, 0, ...)
    storage    replica.go:658          (*Replica).Send(#3, #1390983, *, *, 0, #37, 0xa, 0x1, 0, 0, ...)
    storage    store.go:1450           (*Store).Send(#2, #1390983, *, *, 0, #37, 0xa, 0x1, 0, 0, ...)
    storage    stores.go:186           (*Stores).Send(#950, #1390983, *, 0, 0, #37, 0xa, 0x1, 0, 0, ...)
    server     node.go:607             (*Node).executeCmd.func2()
    stop       stopper.go:125          (*Stopper).RunTask(#1, *, 0)
    server     node.go:619             (*Node).executeCmd(#986, #1390956, *, 0, 0, 0, 0)
    server     node.go:326             executeCmd)-fm(#1390956, *, 0, 0, 0, 0)
    rpc        server.go:50            syncAdapter.exec.func1(*, #657, #1390956, *)
19967: select [0~2 minutes] [Created by stop.(*Stopper).RunAsyncTask @ stopper.go:141]
    kv         send.go:157             send(0, #39, #38, #1390992, *, *, 0x4, 0x4, 0, 0, ...)
    kv         dist_sender.go:345      (*DistSender).sendRPC(#887, #1390992, *, 0x1, *, 0x4, 0x4, 0, 0, 0, ...)
    kv         dist_sender.go:425      (*DistSender).sendSingleRange(#887, #1390992, *, 0, 0, 0, 0, 0, 0, 0, ...)
    kv         dist_sender.go:618      (*DistSender).sendChunk.func1(*, *, *, #887, #1390992, *, 0x20, *)
    kv         dist_sender.go:619      (*DistSender).sendChunk(#887, #1390983, *, 0, 0, 0, 0, 0, 0, 0, ...)
    kv         dist_sender.go:490      (*DistSender).Send(#887, #1390983, *, 0, 0, 0, 0, 0, 0, 0, ...)
    kv         txn_coord_sender.go:424 (*TxnCoordSender).Send(#981, #1390983, *, 0, 0, 0, 0, 0, 0, 0, ...)
    client     db.go:488               (*DB).send(#913, *, 0x1, 0x1, 0, *)
    client     db.go:453               send)-fm(*, 0x1, 0x1, 0x1, 0)
    client     db.go:418               sendAndFill(*, *, *, *)
    client     db.go:453               (*DB).RunWithResponse(#913, *, 0x1, 0x1)
    storage    store.go:1615           (*Store).resolveWriteIntentError(#2, #1390978, *, *, #3, 0, 0, *, 0, 0, ...)
    storage    replica.go:1745         (*Replica).handleSkippedIntents.func1()
    stop       stopper.go:140          (*Stopper).RunAsyncTask.func1(#1, #22, 0x12, 0x706, *)
```

### PR DESCRIPTION
**Pull request by bdarnell**
This lets us give it its own place in the lock order and access it
without spawning an unbounded number of additional goroutines to avoid
deadlocks.

Fixes #4881

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4886)

### CODE REVIEW

**Comment by tamird** [comment]
LGTM with or without my comment addressed.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[storage/store.go, line 1789 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4886#-KC7SfNs-5BCqvLowb6O:-KC7ST1z0W_C_N5Yh-7j:1708662928) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ef1269574f8064fb7d5a0b737e2b489ab00dda2/storage/store.go#L1789)):*
sorry for the drive-by: this length check looks like it's here to avoid the allocation below the `for-range`, but we can avoid that allocation altogether by `delete`ing during iteration.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4886#-:-KC7TACfm97dHjsuDFtf:680173678)*

**Comment by tschottdorf** [comment]
LGTM, but does this really close #4881, or explain why it happened?

`137637: semacquire [1~463 minutes] [Created by rpc.syncAdapter.exec @ server.go:51]`

**Comment by bdarnell** [comment]
It may not solve all of #4881, but it gets most of it. Almost 90% of the goroutines there were created by `enqueueRaftUpdateCheck`. 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[storage/store.go, line 1789 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4886#-KC7SfNs-5BCqvLowb6O:-KC7WA-Kli7_Ry1JJR1K:-1006546810) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ef1269574f8064fb7d5a0b737e2b489ab00dda2/storage/store.go#L1789)):*
Yes, but then you're doing N map deletions instead of one allocation. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4886#-:-KC7Wi_UzoxK7M2oeJ1k:-1141223134)*

**Comment by tschottdorf** [comment]
Ok, but does it explain why #4881 happened? If so, appreciate a short explanation.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4886#-:-KC7ZZy1utcKV-WAIkxO:-2103292718)*

**Comment by bdarnell** [comment]
Analysis posted in #4881

**Comment by bdarnell** [comment]
I'm going to merge this and leave #4881 open until my next PR, which will add some backpressure to intent resolution.

**Comment by tschottdorf** [comment]
Thanks for the analysis. In addition to backpressure on intent resolution,
resolving intents asynchronously can also massively profit from batching up
those intents which are local.

**Comment by BramGruneir** [comment]
LGTM

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[storage/store.go, line 529 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4886#-KC89_p9rTU7H4OiAeSf:-KC89_pA-1MsnNq9e7Jq:-2015854058) ([raw file](https://github.com/cockroachdb/cockroach/blob/b74efd2600b54f55f98d94c6df731476060123a7/storage/store.go#L529)):*
I know it's in the constructor and not required, but I don't think it would hurt to lock and unlock around this line.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4886#-:-KC8AE0HWC85z2R0rofd:676834233)*

**Pull request merged**
