### PR TITLE
sql: implement IFERROR and ISERROR

### LINKED ISSUE #9760: sql: add a SQL "function to transform eval errors to NULL
Please follow the steps below to help us help you.

1. Please supply the header (i.e. the first few lines) of your most recent
   log file **for each node in your cluster**. On most unix-based systems
   running with defaults, this boils down to the output of

     grep -F '[config]' cockroach-data/logs/cockroach.INFO

   When log files are not available, supply the output of `cockroach version`
   and all flags/environment variables passed to `cockroach start` instead.

2. Please describe the issue you observed:

- What did you do?

- What did you expect to see?

- What did you see instead?

### PR DESCRIPTION
**Pull request by knz**
Fixes #9760.

The SQL scalar operators `IFERROR` and `ISERROR` are inspired from the
MSSQL feature of the same name. In their simple form:

- `ISERROR(Expr)` returns false if `Expr` evaluates
  without error; true otherwise.
- `IFERROR(Expr, Val)` returns the value of `Expr` if `Expr` evaluates
  without error, otherwise it evaluates and returns `Val`.

In order to avoid catching too many errors, they exist also in an
"advanced" mode:

- `ISERROR(Expr, Code)` returns false if `Expr` evaluates without
  error; otherwise, it evaluates `Code`, and if `Code` evaluates
  without error it checks whether the error produced for `Expr` has pg
  error code that matches `Code`. If `Code` is NULL or the pg error
  code matches, `ISERROR` returns true, otherwise `ISERROR` returns
  `Expr`'s evaluation error. For example, `ISERROR(1/x, '22012')
  returns true iff Expr evaluates with a "divide by zero" error.

- `IFERROR(Expr, Val, Code)` evaluates `Expr` and returns its value if
  no error. If there is an error, it evaluates `Code` and checks the
  `Expr` eval error with `Code` as for `ISERROR` above. If the error
  code matches, it evaluates and returns `Val`.

Note: this only covers the evaluation of scalar expressions that
do not require access to data in the underlying KV store.

- If ISERROR/IFERROR is applied to a subquery and the subquery errors
  out, the entire query fails and ISERROR/IFERROR are ineffective.
- In general if the scalar expression causes a KV operation and the KV
  operation fails (e.g. `nextval()` on a sequence), again the entire
  query fails.
- Some very specific uses of KV may be caught (e.g. ::REGCLASS casts)
  but this is neither tested nor guaranteed.

Release note (sql change): the two experimental scalar operators
`IFERROR()` and `ISERROR()` have been introduced. They may be
documented for public use in the future.

### CODE REVIEW

**Comment by knz** [comment]
cc @andreimatei

**Comment by knz** [comment]
Note: I made a mistake in the definition of iserror -- my explanation about "either/or code" is wrong.

**Comment by knz** [comment]
Fixed, PTAL

**Comment by nvanbenschoten** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/sql/sem/tree/expr.go, line 542 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25304#-LBgyj1M2DAU0eCicekL:-LBgyj1M2DAU0eCicekM:b-wqb9s2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7900fbdf5d137f37de7b560d6c750c66b05fa11/pkg/sql/sem/tree/expr.go#L542)):*
> ```Go
> }
> 
> // IfErrExpr represents an IFERR expression.
> ```

`s/IFERR/IFERROR/`

---

*[pkg/sql/sem/tree/expr.go, line 546 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25304#-LBgy7EHBlswUEC56Elz:-LBgy7EHBlswUEC56Em-:bkmtpzz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7900fbdf5d137f37de7b560d6c750c66b05fa11/pkg/sql/sem/tree/expr.go#L546)):*
> ```Go
> 	Cond    Expr
> 	Else    Expr
> 	ErrCond Expr
> ```

I would rename `ErrCond` to `ErrCode` everywhere. It's a little confusing having multiple "condition" expressions within the same parent Expr.

---

*[pkg/sql/sem/tree/expr.go, line 579 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25304#-LBgylZG8u6941eiknTM:-LBgylZG8u6941eiknTN:b-d6rdv3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7900fbdf5d137f37de7b560d6c750c66b05fa11/pkg/sql/sem/tree/expr.go#L579)):*
> ```Go
> }
> 
> // IsErrExpr represents an IFERR expression.
> ```

`s/IFERR/ISERROR/`

---

*[pkg/sql/sem/tree/expr.go, line 580 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25304#-LBgyNHOCJp5-xhH9VbG:-LBgyNHOCJp5-xhH9VbH:b-qhuhil) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7900fbdf5d137f37de7b560d6c750c66b05fa11/pkg/sql/sem/tree/expr.go#L580)):*
> ```Go
> 
> // IsErrExpr represents an IFERR expression.
> type IsErrExpr struct {
> ```

Do you think it's worth folding this into `IfErrExpr` with a `nil` `Else` expression? Should be pretty easy to make that work.

---

*[pkg/sql/sem/tree/type_check.go, line 621 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25304#-LBgzB3_CW8vTt_QHfQW:-LBgzB3_CW8vTt_QHfQX:bxxxiic) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7900fbdf5d137f37de7b560d6c750c66b05fa11/pkg/sql/sem/tree/type_check.go#L621)):*
> ```Go
> 	var typedErrCond TypedExpr
> 	if expr.ErrCond != nil {
> 		typedErrCond, err = typeCheckAndRequire(ctx, expr.ErrCond, types.String, "IFERROR")
> ```

`s/IFERROR/ISERROR/`

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25304)*

**Comment by nvanbenschoten** [comment]
Review status: 4 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/sem/tree/expr.go, line 580 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25304#-LBgyNHOCJp5-xhH9VbG:-LBh8rpyDplkQnORNoih:b23a831) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7900fbdf5d137f37de7b560d6c750c66b05fa11/pkg/sql/sem/tree/expr.go#L580)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

do you mean that `iferror(a)` should type as boolean whereas `iferror(a,b)` should type as the type of a and b? That looks fishy. I think we've been pretty disciplined at having 1 expr type === 1 typing rule.
</blockquote></details>

No sorry, I just meant folding these two expression types into a single AST node.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25304)*

**Comment by knz** [comment]
Review status: 4 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/sem/tree/expr.go, line 580 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25304#-LBgyNHOCJp5-xhH9VbG:-LC5DZu2E9XFuboIc1By:b-nrz0nc) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7900fbdf5d137f37de7b560d6c750c66b05fa11/pkg/sql/sem/tree/expr.go#L580)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

No sorry, I just meant folding these two expression types into a single AST node.
</blockquote></details>

Done. RFAL

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25304)*

**Comment by nvanbenschoten** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25304#-:-LCdEBzEA75y97JroBUV:bnfp4nl)*

**Comment by knz** [comment]
Thanks!

bors r+

**Pull request merged**
