### PR TITLE
ui: apply Typescript strict mode for Cluster UI and Db Console

### PR DESCRIPTION
**Pull request by koorosh**
This change enables "strict" mode for both Cluster UI and Db Console workspaces to avoid
issues due to type mismatches that cannot be caught during development. 
"strictNullChecks" rule remains disabled as it causes thousands of problems all around the
project that cannot be easily fixed. Most of the time is caused by usage of types from Protobuf
messages that by default are nullable and optional, but in code it could be used as required
fields.
Some of the typing issues are ignored as it requires more refactoring and significant changes.
At the same time, some places were refactored with low risk to break something.

Epic: https://cockroachlabs.atlassian.net/browse/CC-26102

Release note: None

### CODE REVIEW

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125551)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @laurenbarker)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/databaseDetailsApi.ts` line 460 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125551#-O-CKxV1C8_eC3vKvOPT:-O-CKxV1C8_eC3vKvOPU:b68hq59) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d2586c38fb8cc41dd165e392106c449e8c35c7c/pkg/ui/workspaces/cluster-ui/src/api/databaseDetailsApi.ts#L460)):*
> ```XML
> 
> const databaseDetailQueries: DatabaseDetailsQuery<DatabaseDetailsRow>[] = [
>   // eslint-disable-next-line @typescript-eslint/ban-ts-comment
> ```

Defined generic type `DatabaseDetailsQuery<DatabaseDetailsRow>` is incorrect because Typescript is strict to
generics with union types:
`Type<A | B | C>` is not the same as `Type<A> | Type<B> | Type<C>`
___
*[`pkg/ui/workspaces/cluster-ui/src/api/schemaInsightsApi.ts` line 254 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125551#-O-CLsd04hDbxkXEl_id:-O-CLsd04hDbxkXEl_ie:b-8qeve9) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d2586c38fb8cc41dd165e392106c449e8c35c7c/pkg/ui/workspaces/cluster-ui/src/api/schemaInsightsApi.ts#L254)):*
> ```XML
>     // @ts-ignore
>     const insightQuery: SchemaInsightQuery<SchemaInsightResponse> =
>       schemaInsightQueries[txnResult.statement - 1];
> ```

For some reason, here's `schemaInsightQueries` array contains two values of different types and only one type is valid for us.
I don't know how accessing by index `[txnResult.statement - 1]` works so decided to ignore it.
___
*[`pkg/ui/workspaces/cluster-ui/src/api/tableDetailsApi.ts` line 552 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125551#-O-CQN0S5oVkaCmluBEw:-O-CQN0S5oVkaCmluBEx:b-xuord1) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d2586c38fb8cc41dd165e392106c449e8c35c7c/pkg/ui/workspaces/cluster-ui/src/api/tableDetailsApi.ts#L552)):*
> ```XML
>   // eslint-disable-next-line @typescript-eslint/ban-ts-comment
>   // @ts-ignore
>   getTableId,
> ```

The same a before, generic union type incorrectly used in many places.
___
*[`pkg/ui/workspaces/cluster-ui/src/columnsSelector/columnsSelector.tsx` line 153 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125551#-O-CR1e2C_RV7bVEcIxC:-O-CR1e2C_RV7bVEcIxD:b-uhe5fk) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d2586c38fb8cc41dd165e392106c449e8c35c7c/pkg/ui/workspaces/cluster-ui/src/columnsSelector/columnsSelector.tsx#L153)):*
> ```XML
>   ): void => {
>     const { action } = actionMeta;
>     if (action !== "select-option" && action !== "deselect-option") {
> ```

`<Select>` component calls `handleChange` callback on many actions (not only select and deselect as it was handled before).
This change in code logic assumes that all possible action types can trigger this callback, but we filter out all except `select` and `deselect` so the logic preserves the same.
___
*[`pkg/ui/workspaces/cluster-ui/src/sessions/sessionsTable.tsx` line 268 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125551#-O-CRbH74WK7t9Aix_W2:-O-CRbH74WK7t9Aix_W3:bow0icm) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d2586c38fb8cc41dd165e392106c449e8c35c7c/pkg/ui/workspaces/cluster-ui/src/sessions/sessionsTable.tsx#L268)):*
> ```XML
>       titleAlign: "right",
>       cell: ({ session }) => {
>         const menuItems: DropdownItem<"cancelStatement" | "cancelSession">[] = [
> ```

TypeScript distinguishes string literals and `String` type now.
___
*[`pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx` line 513 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125551#-O-CS2156_iNZQ-6eFsC:-O-CS2156_iNZQ-6eFsD:b-2gsoja) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d2586c38fb8cc41dd165e392106c449e8c35c7c/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx#L513)):*
> ```XML
>     let found = false;
>     Object.values(SqlStatsSortOptions).forEach(option => {
>       const optionString = isString(option) ? option : getSortColumn(option);
> ```

`option` argument can be either `String` or `SqlStatsSortType`.
___
*[`pkg/ui/workspaces/cluster-ui/src/store/clusterLocks/clusterLocks.saga.ts` line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125551#-O-CSCs03RuO8oJVY-yt:-O-CSCs03RuO8oJVY-yu:btbmrw7) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d2586c38fb8cc41dd165e392106c449e8c35c7c/pkg/ui/workspaces/cluster-ui/src/store/clusterLocks/clusterLocks.saga.ts#L29)):*
> ```XML
>     yield put(actions.received(result));
>   } catch (e) {
>     yield put(actions.failed(e as Error));
> ```

`catch (e)` defines `e` as `unknown` type and it doesn't allow to write like this `catch (e: Error)`. Thats why it is explicitly casted in  catch clause.
___
*[`pkg/ui/workspaces/db-console/tsconfig.json` line 10 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125551#-O-CU9Ex6h7bmvi1SthZ:-O-CU9Ex6h7bmvi1Sth_:b-q6nkt3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f00f1cc3716f1c8dcb62d620efa0a5edf215a121/pkg/ui/workspaces/db-console/tsconfig.json#L10)):*
> ```jsonc
>     "lib": ["esnext", "dom"],
>     "moduleResolution": "node",
>     "noFallthroughCasesInSwitch": true,
> ```

This rules are redundant as they're applied with `strict` rule.

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125551)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @laurenbarker)

___
*[`pkg/ui/workspaces/db-console/ccl/src/views/shared/containers/licenseSwap/index.tsx` line 49 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125551#-O-CUjwq8BqSH5H-5FVM:-O-CUjwq8BqSH5H-5FVN:b-deyjvh) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d2586c38fb8cc41dd165e392106c449e8c35c7c/pkg/ui/workspaces/db-console/ccl/src/views/shared/containers/licenseSwap/index.tsx#L49)):*
> ```XML
>  * on the current license status.
>  */
> export default function swapByLicense<OSSProps, CCLProps, TProps = OSSProps | CCLProps>(
> ```

Split prop types for OSS and CCL components as they are supposed to have different set of properties.
___
*[`pkg/ui/workspaces/db-console/src/test-utils/renderWithProviders.tsx` line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125551#-O-CV4Y_4eSuk4BTyjza:-O-CV4Y_4eSuk4BTyjzb:b-11ccti) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d2586c38fb8cc41dd165e392106c449e8c35c7c/pkg/ui/workspaces/db-console/src/test-utils/renderWithProviders.tsx#L47)):*
> ```XML
>       // eslint-disable-next-line @typescript-eslint/ban-ts-comment
>       // @ts-ignore
>       queryManager: queryManagerReducer,
> ```

For some reason specific Action types of `queryManagerReducer` is not compatible with expected `AnyAction` type.
___
*[`pkg/ui/workspaces/db-console/src/util/api.ts` line 447 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125551#-O-CVVej37CrWDLfYlZ9:-O-CVVej37CrWDLfYlZA:b-30g0qu) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d2586c38fb8cc41dd165e392106c449e8c35c7c/pkg/ui/workspaces/db-console/src/util/api.ts#L447)):*
> ```XML
>     // eslint-disable-next-line @typescript-eslint/ban-ts-comment
>     // @ts-ignore
>     (response: JobsResponseMessage) => response,
> ```

Don't know how to properly define expected type. Ignored for now.
___
*[`pkg/ui/workspaces/db-console/src/views/keyVisualizer/index.tsx` line 167 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125551#-O-CWCB6CzYZgfx7r-gz:-O-CWCB6CzYZgfx7r-h-:b-ytn4yp) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d2586c38fb8cc41dd165e392106c449e8c35c7c/pkg/ui/workspaces/db-console/src/views/keyVisualizer/index.tsx#L167)):*
> ```XML
> 
>   // Hex encode bucket UUIDs.
>   const keySamples: KeyVisSample[] = samples.map(sample => ({
> ```

Refactored to produce a new array with proper type 
___
*[`pkg/ui/workspaces/db-console/src/views/shared/components/dropdown/index.tsx` line 163 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/125551#-O-CWrCa9LjC42JkRBhc:-O-CWrCa9LjC42JkRBhd:bnnzxnv) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d2586c38fb8cc41dd165e392106c449e8c35c7c/pkg/ui/workspaces/db-console/src/views/shared/components/dropdown/index.tsx#L163)):*
> ```XML
>           content
>         ) : (
>           // @ts-ignore
> ```

`onChange` callback function expects incorrect argument type but it correctly works with it. Changing code to provide correct value to `onChange` args breaks the code.

**Review by laurenbarker — APPROVED** [review]
Thank you @koorosh! I think this is a HUGE improvement, so I'd say LGTM. The one thing I'd want to see is the errors not cast to Error without checking that `message` exists on the error object. However, that can be done in a follow-up.

I'd also want to see if @xinhaoz or @dhartunian want to review this prior to merge. 

> Reviewed 57 of 57 files at r1, 44 of 44 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125551#-:-O-HLdnyBwqS1ruUv7Ej:btn03l6)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @koorosh)

___
*[`pkg/ui/workspaces/cluster-ui/src/store/uiConfig/uiConfig.sagas.ts` line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125551#-O-HIZvS2QqbCukGlSPI:-O-HIZvS2QqbCukGlSPJ:b-c37a6m) ([raw file](https://github.com/cockroachdb/cockroach/blob/30eefddd7bf0575dfd2c71bed64f10fa2842bb36/pkg/ui/workspaces/cluster-ui/src/store/uiConfig/uiConfig.sagas.ts#L32)):*
> ```XML
>   } catch (e) {
>     getLogger().warn(
>       (e as Error).message,
> ```

We have a couple of error helpers in the managed-service repo that look like they would be helpful in the cockroach repo as well. That way we aren't casting types when we don' t actually know what the type will be.

```ts
// console/assets/js/util/errors.ts

/**
 * Determines if a value is an object with a string-valued `.message` property (though it _can_ be empty!)
 * @param val the value to check
 * @returns `true` if `val` is an object with a `.message` property of type string, otherwise `false`
 */
function hasMessage(val: unknown): val is { message: string } {
  return (
    typeof val === "object" &&
    val != null &&
    "message" in val &&
    typeof (val as Record<string, unknown>).message === "string"
  );
}

/**
 * Extracts a non-empty string from a possibly Error-like object, defaulting to the provided message
 * if no message exists.
 *
 * In development builds only (where `DEV_MODE === true`), when no message is found a JSON representation
 * of `maybeError` is appended to `fallbackMsg` to aid with debugging.
 *
 * @param maybeError the JS `Error`, `GrpcError`, or similar object to extract a `.message` from
 * @param fallbackMsg the message to use if `maybeError` doesn't contain a suitable `.message`
 * @returns `maybeError.message` if it exists and is non-empty, otherwise `fallbackMsg`
 */
export function getErrorMessageOrElse(
  maybeError: unknown,
  fallbackMsg: string,
): string {
  if (hasMessage(maybeError) && maybeError.message) {
    return (maybeError as { message: string }).message;
  }

  if (DEV_MODE) {
    return (
      fallbackMsg + ` (DEV_MODE) original error: ${JSON.stringify(maybeError)}`
    );
  }

  return fallbackMsg;
}
```
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodesOverview/tableSection.tsx` line 110 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/125551#-O-HKKSG5OBasqcwOGIK:-O-HKKSG5OBasqcwOGIL:bdhx97t) ([raw file](https://github.com/cockroachdb/cockroach/blob/89f838ef49933bf4ddf5b4404781df27bf6972b5/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodesOverview/tableSection.tsx#L110)):*
> ```XML
>         <div className={contentClass}>
>           {children}
>           {this.props.footer && <div className="table-section__footer">{this.props.footer}</div>}
> ```

Why was the footer prop removed from the destructured props and accessed directly?

**Review by xinhaoz — APPROVED** [review]
LGTM, thanks @koorosh!

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125551)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @laurenbarker)

___
*[`pkg/ui/workspaces/cluster-ui/src/store/uiConfig/uiConfig.sagas.ts` line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125551#-O-HIZvS2QqbCukGlSPI:-O-LnLlp3cxF_g3IF22a:b-h1d08g) ([raw file](https://github.com/cockroachdb/cockroach/blob/30eefddd7bf0575dfd2c71bed64f10fa2842bb36/pkg/ui/workspaces/cluster-ui/src/store/uiConfig/uiConfig.sagas.ts#L32)):*
<details><summary><i>Previously, laurenbarker (Lauren Barker) wrote…</i></summary><blockquote>

We have a couple of error helpers in the managed-service repo that look like they would be helpful in the cockroach repo as well. That way we aren't casting types when we don' t actually know what the type will be.

```ts
// console/assets/js/util/errors.ts

/**
 * Determines if a value is an object with a string-valued `.message` property (though it _can_ be empty!)
 * @param val the value to check
 * @returns `true` if `val` is an object with a `.message` property of type string, otherwise `false`
 */
function hasMessage(val: unknown): val is { message: string } {
  return (
    typeof val === "object" &&
    val != null &&
    "message" in val &&
    typeof (val as Record<string, unknown>).message === "string"
  );
}

/**
 * Extracts a non-empty string from a possibly Error-like object, defaulting to the provided message
 * if no message exists.
 *
 * In development builds only (where `DEV_MODE === true`), when no message is found a JSON representation
 * of `maybeError` is appended to `fallbackMsg` to aid with debugging.
 *
 * @param maybeError the JS `Error`, `GrpcError`, or similar object to extract a `.message` from
 * @param fallbackMsg the message to use if `maybeError` doesn't contain a suitable `.message`
 * @returns `maybeError.message` if it exists and is non-empty, otherwise `fallbackMsg`
 */
export function getErrorMessageOrElse(
  maybeError: unknown,
  fallbackMsg: string,
): string {
  if (hasMessage(maybeError) && maybeError.message) {
    return (maybeError as { message: string }).message;
  }

  if (DEV_MODE) {
    return (
      fallbackMsg + ` (DEV_MODE) original error: ${JSON.stringify(maybeError)}`
    );
  }

  return fallbackMsg;
}
```
</blockquote></details>

Makes sense, I'd propose to use `isError` from lodash package, WDYT?
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodesOverview/tableSection.tsx` line 110 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/125551#-O-HKKSG5OBasqcwOGIK:-O-LnqQnDuqR7x9zDuwL:b-b561yd) ([raw file](https://github.com/cockroachdb/cockroach/blob/89f838ef49933bf4ddf5b4404781df27bf6972b5/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodesOverview/tableSection.tsx#L110)):*
<details><summary><i>Previously, laurenbarker (Lauren Barker) wrote…</i></summary><blockquote>

Why was the footer prop removed from the destructured props and accessed directly?
</blockquote></details>

It was done because `footer` is an optional prop and destructing prop which is not defined causes TS error.
Accessing directly allows to evaluate if it's defined and then use it.

**Review by laurenbarker — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125551)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @koorosh)

___
*[`pkg/ui/workspaces/cluster-ui/src/store/uiConfig/uiConfig.sagas.ts` line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125551#-O-HIZvS2QqbCukGlSPI:-O-MHjlg6Gjb7Yq0J5X6:bo3987r) ([raw file](https://github.com/cockroachdb/cockroach/blob/30eefddd7bf0575dfd2c71bed64f10fa2842bb36/pkg/ui/workspaces/cluster-ui/src/store/uiConfig/uiConfig.sagas.ts#L32)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Makes sense, I'd propose to use `isError` from lodash package, WDYT?
</blockquote></details>

Sure that works. It'd still be nice to enforce a fallback message with a helper though. That way we never end up in a situation where no error is logged. We can merge and then follow-up with the error change though.
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodesOverview/tableSection.tsx` line 110 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/125551#-O-HKKSG5OBasqcwOGIK:-O-MIPd29ap8i1fIyWyI:bj7d1i) ([raw file](https://github.com/cockroachdb/cockroach/blob/89f838ef49933bf4ddf5b4404781df27bf6972b5/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodesOverview/tableSection.tsx#L110)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

It was done because `footer` is an optional prop and destructing prop which is not defined causes TS error.
Accessing directly allows to evaluate if it's defined and then use it.
</blockquote></details>

Hm, so this causes an error? This isn't blocking, I'm just surprised that would cause an issue.
```ts
const { footer } = this.props;

{footer && <div className="table-section__footer">{footer}</div>}
```

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125551)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @laurenbarker)

___
*[`pkg/ui/workspaces/cluster-ui/src/store/uiConfig/uiConfig.sagas.ts` line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125551#-O-HIZvS2QqbCukGlSPI:-O-_0PNd1CNV45nPpf2z:b-jonms3) ([raw file](https://github.com/cockroachdb/cockroach/blob/30eefddd7bf0575dfd2c71bed64f10fa2842bb36/pkg/ui/workspaces/cluster-ui/src/store/uiConfig/uiConfig.sagas.ts#L32)):*
<details><summary><i>Previously, laurenbarker (Lauren Barker) wrote…</i></summary><blockquote>

Sure that works. It'd still be nice to enforce a fallback message with a helper though. That way we never end up in a situation where no error is logged. We can merge and then follow-up with the error change though.
</blockquote></details>

Done, added validation on Error, possible string value or fallback to error with predefined message.
___
*[`pkg/ui/workspaces/db-console/src/views/cluster/containers/nodesOverview/tableSection.tsx` line 110 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/125551#-O-HKKSG5OBasqcwOGIK:-O-_0C4-DgmUE-mScNkX:b-iltyyf) ([raw file](https://github.com/cockroachdb/cockroach/blob/89f838ef49933bf4ddf5b4404781df27bf6972b5/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodesOverview/tableSection.tsx#L110)):*
<details><summary><i>Previously, laurenbarker (Lauren Barker) wrote…</i></summary><blockquote>

Hm, so this causes an error? This isn't blocking, I'm just surprised that would cause an issue.
```ts
const { footer } = this.props;

{footer && <div className="table-section__footer">{footer}</div>}
```
</blockquote></details>

Correct! Props might not have such field at all.

**Pull request merged**
