### PR TITLE
kvstreamer: extend a test to assert that the streamer is used

### LINKED ISSUE #82646: kvstreamer: add tests to verify that the streamer is used when we expect it to be
Currently, the fact whether the streamer is used is rather opaque. We should have some simple regressions tests to ensure that it is in fact used when we expect it to be.

Jira issue: CRDB-16637

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit extends an existing test which examines the trace of
different queries to assert that the streamer is used in all cases when
we expect. It also simplifies some of the queries as well as adjusts the
workmem limit which got out of sync with the index join memory limiting
behavior which was changed recently.

Fixes: #82646.

Release note: None

### CODE REVIEW

**Review by rharding6373 — APPROVED** [review]
Great, thank you! :lgtm: 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82671#-:-N48IL2f-BPY-YTEZqoO:b1th0zs)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by yuzefovich** [comment]
Looks like the test might be flaky.

bors r-

**Comment by yuzefovich** [comment]
The adjusted test started being flaky in rare circumstances due to join reader not behaving under memory pressure for the lookup join with ordering test case. Opened up #82693 to fix that and will merge this PR once that PR goes in.

**Comment by yuzefovich** [comment]
Should be good now.

bors r+

**Pull request merged**
