### PR TITLE
exec: Add vectorized support for IN

### PR DESCRIPTION
**Pull request by rohany**
Added vectorized support for the IN operator, as detailed in #38502 

This is my first pass at the vectorized stuff, reviews are welcome! I'm probably doing things wierdly / not in the best way.

### CODE REVIEW

**Review by solongordon — CHANGES_REQUESTED** [review]
I know this is already out of date but I added some initial thoughts.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38546#-:-Lii3rLv7re4yQsUlWzh:b-ykpkb2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany and @solongordon)

___
*[Makefile, line 798 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38546#-LihlYgw57OCQ3p_y9TY:-LihlYgx5EyC7TRjVihg:bdkbyy4) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f856e90cedb7ff4012a3c2190f2aa6e85f36cad/Makefile#L798)):*
> ```Makefile
>   pkg/sql/exec/rowstovec.eg.go \
>   pkg/sql/exec/selection_ops.eg.go \
> 	pkg/sql/exec/select_in.eg.go \
> ```

tabs/spaces inconsistency
___
*[pkg/sql/exec/select_in_test.go, line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38546#-LihyouvCcXRaoxeaXMv:-LihyouvCcXRaoxeaXMw:bhddnim) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f856e90cedb7ff4012a3c2190f2aa6e85f36cad/pkg/sql/exec/select_in_test.go#L21)):*
> ```Go
> )
> 
> func TestSelectInInt64(t *testing.T) {
> ```

Nit: It would be nice to make the below tests a single unit test with a list of test cases.
___
*[pkg/sql/exec/select_in_tmpl.go, line 98 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38546#-Lihtxy6-B6PrK0x0-Na:-Lihtxy6-B6PrK0x0-Nb:b-2swy7h) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f856e90cedb7ff4012a3c2190f2aa6e85f36cad/pkg/sql/exec/select_in_tmpl.go#L98)):*
> ```Go
> }
> 
> func fillDatumRow_TYPE(ct *semtypes.T, row tree.Datum) ([]_GOTYPE, []bool, bool, error) {
> ```

I would suggest making this function accept a `DTuple` rather than a `Datum`. Then the planner can be responsible for checking if it's a tuple or not.
___
*[pkg/sql/exec/select_in_tmpl.go, line 121 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38546#-LihtZkY-AG97jSCl7UI:-LihtZkY-AG97jSCl7UJ:brgj7q8) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f856e90cedb7ff4012a3c2190f2aa6e85f36cad/pkg/sql/exec/select_in_tmpl.go#L121)):*
> ```Go
> 		}
> 		result = append(result, converted)
> 		resultNulls = append(resultNulls, isNull)
> ```

Is `resultNulls` really necessary? Could you just skip adding the value to `result`? It seems like we just care about whether at least one null value is present or not (i.e. `hasNulls`).
___
*[pkg/sql/exec/select_in_tmpl.go, line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38546#-LihsSoO1Lx-YzXmRdEV:-LihsSoO1Lx-YzXmRdEW:b-a1bx8c) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f856e90cedb7ff4012a3c2190f2aa6e85f36cad/pkg/sql/exec/select_in_tmpl.go#L127)):*
> ```Go
> 
> func (si *selectInOp_TYPE) isIn_TYPE(col []_GOTYPE, sel []uint16, nulls *coldata.Nulls, i uint16, idx *uint16) {
> 	// if our row element is not in filter row
> ```

Minor: Please try to make your comments properly capitalized, in complete sentences, and wrapped at 80 chars. That's the general Cockroach standard.
___
*[pkg/sql/exec/select_in_tmpl.go, line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38546#-LihsEvW5cTjiPkXzDrP:-LihsEvW5cTjiPkXzDrQ:b-ydwpoo) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f856e90cedb7ff4012a3c2190f2aa6e85f36cad/pkg/sql/exec/select_in_tmpl.go#L132)):*
> ```Go
> 	keep := false
> 	for fi, val := range si.filterRow {
> 		// if we have a null row, we keep it immediately
> ```

What about `NULL IN ()`?
___
*[pkg/sql/exec/select_in_tmpl.go, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38546#-LihvcoaAPc2lxfqLBAX:-LihvcoaAPc2lxfqLBAY:b-ov40t2) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f856e90cedb7ff4012a3c2190f2aa6e85f36cad/pkg/sql/exec/select_in_tmpl.go#L150)):*
> ```Go
> 		nulls.SetNull(i)
> 		sel[*idx] = i
> 		*idx++
> ```

I'd recommend against passing around int pointers like this if possible. It makes it much harder to understand the code which calls this function.

Might be best for this function to return the result of the IN evaluation (true, false, or null) and leave it up to the caller to modify `sel` and `idx`.
___
*[pkg/sql/exec/select_in_tmpl.go, line 157 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38546#-LihyMbF8I6UYlhhUaGx:-LihyMbF8I6UYlhhUaGy:b-e2ximc) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f856e90cedb7ff4012a3c2190f2aa6e85f36cad/pkg/sql/exec/select_in_tmpl.go#L157)):*
> ```Go
> }
> 
> func (si *selectInOp_TYPE) isNotIn_TYPE(col []_GOTYPE, sel []uint16, nulls *coldata.Nulls, i uint16, idx *uint16) {
> ```

Seems like you should be able to just negate the result of `isIn` rather than duplicating most of the code.

**Review by solongordon — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38546)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany and @solongordon)

___
*[pkg/sql/exec/select_in_test.go, line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38546#-Lii45zlBpCiK8FHf8Vc:-Lii45zlBpCiK8FHf8Vd:bgggjxq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f856e90cedb7ff4012a3c2190f2aa6e85f36cad/pkg/sql/exec/select_in_test.go#L129)):*
> ```Go
> 	batch := coldata.NewMemBatch([]types.T{types.Int64, types.Int64})
> 	col1 := batch.ColVec(0).Int64()
> 	col2 := batch.ColVec(1).Int64()
> ```

I think you only need one column here. Having two just doubles your throughput numbers. :)

**Review by solongordon — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38546)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany)

___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 568 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38546#-LiiRy1K8A1yCq-Nv45G:-LiiRy1K8A1yCq-Nv45H:b-y3crmu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c49097f35ff1136830e87806f719dfeb35861541/pkg/sql/distsqlrun/column_exec_setup.go#L568)):*
> ```Go
> 				datumTuple, ok := tree.AsDTuple(constArg)
> 				if !ok {
> 					err = errors.Errorf("in operator used on not a tuple")
> ```

Maybe clearer: `"IN is only supported for constant expressions"`
___
*[pkg/sql/exec/select_in_test.go, line 82 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38546#-Lii_HcGCywrVtI3BGUw:-Lii_HcGCywrVtI3BGUx:b-iw6mpv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c49097f35ff1136830e87806f719dfeb35861541/pkg/sql/exec/select_in_test.go#L82)):*
> ```Go
> }
> 
> // TODO: include sels and nulls
> ```

This would definitely be nice, especially the nulls.
___
*[pkg/sql/exec/select_in_test.go, line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38546#-Lii_Q-G-1LLPONg_Faa:-Lii_Q-G-1LLPONg_Fab:b-7vnuhv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c49097f35ff1136830e87806f719dfeb35861541/pkg/sql/exec/select_in_test.go#L83)):*
> ```Go
> 
> // TODO: include sels and nulls
> func benchmarkSelectInInt64(b *testing.B) {
> ```

Just out of curiosity I tried running your benchmark with a single element `filterRow`, since this is vaguely comparable to our existing selection operators. It's quite a bit slower.
```
BenchmarkSelectInInt64/selectInInt64-4                     500000  3403 ns/op  2406.67 MB/s
BenchmarkSelLTInt64Int64Op/useSel=false,hasNulls=false-4  3000000   568 ns/op  28841.75 MB/s
```
I would certainly expect the IN implementation to be slower but I wonder if it should be such a wide margin. It would be interesting to try and pin down where the slowness is creeping in.
___
*[pkg/sql/exec/select_in_tmpl.go, line 123 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38546#-Liib2SCDUZvd6Vnio7f:-Liib2SDEbm4K-8ROEKl:b5vt609) ([raw file](https://github.com/cockroachdb/cockroach/blob/c49097f35ff1136830e87806f719dfeb35861541/pkg/sql/exec/select_in_tmpl.go#L123)):*
> ```Go
> // requires that the input is not NULL
> func (si *selectInOp_TYPE) cmpIn_TYPE(target _GOTYPE) comparisonResult {
> 	for _, val := range si.filterRow {
> ```

I believe it's best to avoid `for _, val` here because this will make a copy of each element in `filterRow`. Better to do `for i := range si.filterRow` and use `si.filterRow[i]` in place of `val` in your comparison.
___
*[pkg/sql/exec/select_in_tmpl.go, line 157 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38546#-LiiXjuk8maTIJOx89hs:-LiiXjuk8maTIJOx89ht:b-299wk9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c49097f35ff1136830e87806f719dfeb35861541/pkg/sql/exec/select_in_tmpl.go#L157)):*
> ```Go
> 			if sel := batch.Selection(); sel != nil {
> 				sel = sel[:n]
> 				if si.negate {
> ```

To reduce code duplication, you could set the "expected" comparison result to `siFalse` or `siTrue` depending on the value of `negate`. (Worth checking if this affects your benchmark.)
___
*[pkg/sql/exec/execgen/cmd/execgen/select_in_gen.go, line 36 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38546#-Lii_3GyAZs1If6tavjc:-Lii_3GyAZs1If6tavjd:bgeq1oe) ([raw file](https://github.com/cockroachdb/cockroach/blob/c49097f35ff1136830e87806f719dfeb35861541/pkg/sql/exec/execgen/cmd/execgen/select_in_gen.go#L36)):*
> ```Go
> 	s = strings.Replace(s, "_TemplateType", "{{.LTyp}}", -1)
> 
> 	tmpl, err := template.New("select_in").Funcs(template.FuncMap{"buildDict": buildDict}).Parse(s)
> ```

Minor: You probably don't need the `Funcs` argument anymore.

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38546)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 568 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38546#-LiiRy1K8A1yCq-Nv45G:-LiikkgA27hXF1-6OYI-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c49097f35ff1136830e87806f719dfeb35861541/pkg/sql/distsqlrun/column_exec_setup.go#L568)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Maybe clearer: `"IN is only supported for constant expressions"`
</blockquote></details>

Done.
___
*[pkg/sql/exec/select_in_test.go, line 82 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38546#-Lii_HcGCywrVtI3BGUw:-Liio22f2W05MUtGAuTv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c49097f35ff1136830e87806f719dfeb35861541/pkg/sql/exec/select_in_test.go#L82)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

This would definitely be nice, especially the nulls.
</blockquote></details>

Done.
___
*[pkg/sql/exec/select_in_test.go, line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38546#-Lii_Q-G-1LLPONg_Faa:-LiikmWM7qIMu9DpZHLy:bexgpfc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c49097f35ff1136830e87806f719dfeb35861541/pkg/sql/exec/select_in_test.go#L83)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Just out of curiosity I tried running your benchmark with a single element `filterRow`, since this is vaguely comparable to our existing selection operators. It's quite a bit slower.
```
BenchmarkSelectInInt64/selectInInt64-4                     500000  3403 ns/op  2406.67 MB/s
BenchmarkSelLTInt64Int64Op/useSel=false,hasNulls=false-4  3000000   568 ns/op  28841.75 MB/s
```
I would certainly expect the IN implementation to be slower but I wonder if it should be such a wide margin. It would be interesting to try and pin down where the slowness is creeping in.
</blockquote></details>

it seems most of the overhead comes from just having the for loop in the comparison function. It is unclear how to avoid this.
___
*[pkg/sql/exec/select_in_tmpl.go, line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38546#-LihsEvW5cTjiPkXzDrP:-Liikv2K2ADet2bYWBzH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f856e90cedb7ff4012a3c2190f2aa6e85f36cad/pkg/sql/exec/select_in_tmpl.go#L132)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

What about `NULL IN ()`?
</blockquote></details>

Done.
___
*[pkg/sql/exec/select_in_tmpl.go, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38546#-LihvcoaAPc2lxfqLBAX:-Liikw05A1J10gtwFKwU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f856e90cedb7ff4012a3c2190f2aa6e85f36cad/pkg/sql/exec/select_in_tmpl.go#L150)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I'd recommend against passing around int pointers like this if possible. It makes it much harder to understand the code which calls this function.

Might be best for this function to return the result of the IN evaluation (true, false, or null) and leave it up to the caller to modify `sel` and `idx`.
</blockquote></details>

Done.
___
*[pkg/sql/exec/select_in_tmpl.go, line 123 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38546#-Liib2SCDUZvd6Vnio7f:-LiikxoxAX3AzXjyGvyN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c49097f35ff1136830e87806f719dfeb35861541/pkg/sql/exec/select_in_tmpl.go#L123)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I believe it's best to avoid `for _, val` here because this will make a copy of each element in `filterRow`. Better to do `for i := range si.filterRow` and use `si.filterRow[i]` in place of `val` in your comparison.
</blockquote></details>

Done.
___
*[pkg/sql/exec/select_in_tmpl.go, line 157 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38546#-LiiXjuk8maTIJOx89hs:-LiikyZw7dAqGl6V3uJz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c49097f35ff1136830e87806f719dfeb35861541/pkg/sql/exec/select_in_tmpl.go#L157)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

To reduce code duplication, you could set the "expected" comparison result to `siFalse` or `siTrue` depending on the value of `negate`. (Worth checking if this affects your benchmark.)
</blockquote></details>

Done.

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38546)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany and @solongordon)

___
*[pkg/sql/exec/select_in_test.go, line 33 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38546#-LiiyZQK1hyS3pb1jLAq:-LiiyZQK1hyS3pb1jLAr:bplquwv) ([raw file](https://github.com/cockroachdb/cockroach/blob/146ea5ed84a0988e50546c8bf9d810aa2669ad97/pkg/sql/exec/select_in_test.go#L33)):*
> ```Go
> 	}{
> 		{
> 			desc:         "Simple in test",
> ```

nit: consider making these part of the subtest name. For example, this would be `SimpleIn`/`NotInWithNulls` then you would `t.Run(t.desc func(t *testing.T)` before `runTests` so if any of these tests fail, you know which case failed.

**Comment by rohany** [comment]
Thanks for the review alfonso! I updated the tests.

**Review by solongordon — APPROVED** [review]
Looking good!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38546#-:-Lin2zbT7SiyuhaVbgdL:br2sbr6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany)

___
*[pkg/sql/exec/select_in_test.go, line 122 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38546#-Lin2YdA1_PEYNkrJvNw:-Lin2YdA1_PEYNkrJvNx:b9fyoka) ([raw file](https://github.com/cockroachdb/cockroach/blob/eae0d30bc4ecd6c0ddd819f4a741db2016b4d1b1/pkg/sql/exec/select_in_test.go#L122)):*
> ```Go
> 		input:     source,
> 		colIdx:    0,
> 		filterRow: []int64{1},
> ```

Probably more realistic to have more than one value in `filterRow`, even though the single value is interesting for comparing to other selection operators.

**Pull request merged**
