### PR TITLE
CLI: Update Stores Flag

### PR DESCRIPTION
**Pull request by BramGruneir**
This updates the --stores flag to be --store
See #4577 for all the details on the new format.

Merging this will break cockroach-prod, so I'll create an issue there and link it back to this PR.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4671)

### CODE REVIEW

**Comment by BramGruneir** [comment]
@jseldess Can you take a look at the language in flags.go?  I'm sure it could use some polish.

**Comment by tamird** [comment]
Can you elaborate (in the commit message) on the change being made here? I know this references #4577, but it is useful to dereference such things into commit messages.

I'll have to finish this review tomorrow.

---

Reviewed 12 of 14 files at r1.
Review status: 12 of 14 files reviewed at latest revision, 12 unresolved discussions.

---

*[acceptance/cluster/localcluster.go, line 380 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBPR871yuERX4CXnwFc:-KBPR871yuERX4CXnwFd:686484258) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/acceptance/cluster/localcluster.go#L380)):*
what;s this?

---

*[cli/start.go, line 106 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBPSNGnVjaESO9H9t21:-KBPSNGnVjaESO9H9t22:-1840105363) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/cli/start.go#L106)):*
nit: use append

---

*[cloud/aws/variables.tf, line 9 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBPSfnBlMellrHzDyBs:-KBPSfnBlMellrHzDyBt:270092546) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/cloud/aws/variables.tf#L9)):*
"cp ..." is no longer accurate.

---

*[server/context.go, line 187 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBPT8CPQL_2KGc-XOoA:-KBPT8CPQL_2KGc-XOoB:-2058811475) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/server/context.go#L187)):*
s/a slice of engine.Engine objects/ctx.Engines/

---

*[server/context.go, line 203 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBPTQUkb8GqNUGuAUwu:-KBPTQUkb8GqNUGuAUwv:-1552642712) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/server/context.go#L203)):*
seems odd to use humanize.Ftoa here, just use a float format string

---

*[server/context.go, line 217 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBPY_lL0x2FB5ghgI12:-KBPY_lL0x2FB5ghgI13:-469765787) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/server/context.go#L217)):*
ditto

---

*[server/context.go, line 225 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBPbermeKA6_eZy_VHd:-KBPbermeKA6_eZy_VHe:-1389636956) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/server/context.go#L225)):*
s/specified/initialized/?

---

*[server/context_test.go, line 32 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBPbmYeZ4ZWyDAaiG3B:-KBPbmYeZ4ZWyDAaiG3C:-2127930671) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/server/context_test.go#L32)):*
nit: i think append might be more concise. your call.

---

*[server/store_spec_test.go, line 116 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBPcRtgP_hYRyDdjW62:-KBPcRtgP_hYRyDdjW63:1699091293) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/server/store_spec_test.go#L116)):*
can you strengthen this by asserting on the particular error?

---

*[server/store_spec_test.go, line 123 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBPcaR-HrjGnzTBSJuP:-KBPcaR-HrjGnzTBSJuQ:159003647) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/server/store_spec_test.go#L123)):*
throughout: i think the string being parsed is more useful in identifying the test case than the test case's array index.

---

*[server/store_spec_test.go, line 127 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBPcnG2vEMHShz3BpXo:-KBPcnG2vEMHShz3BpXp:2024657749) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/server/store_spec_test.go#L127)):*
throughout: no need for the trailing newline

---

*[server/store_spec_test.go, line 131 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBPcuP465lmIHC5_tXB:-KBPcuP465lmIHC5_tXC:-1706558256) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/server/store_spec_test.go#L131)):*
s/the//

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-:-KBPRruc5tKjvOVAE8cF:-429399656)*

**Comment by bdarnell** [comment]
LGTM

---

Review status: 12 of 14 files reviewed at latest revision, 15 unresolved discussions.

---

*[acceptance/cluster/localcluster.go, line 426 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBQ7qRWMjEvlUlErYhp:-KBQ7qRWMjEvlUlErYhq:1903269838) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/acceptance/cluster/localcluster.go#L426)):*
Attrs are no longer required so this could use the simpler `--store=%s` or `store=path=%s`. (I think in general we should remove `attr=ssd` from our examples since store-level attributes are an advanced use case)

---

*[cli/start.go, line 106 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBPSNGnVjaESO9H9t21:-KBQ8LTXJix6gBrUGUkP:677194780) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/cli/start.go#L106)):*
Why?

---

*[server/context.go, line 196 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBQ8sVed9pH1nCSL5Db:-KBQ8sVed9pH1nCSL5Dc:813318163) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/server/context.go#L196)):*
Whenever we get physical memory we should cap it by our container's allocation; see `server/context.go#getDefaultCacheSize`

---

*[server/store_spec.go, line 78 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBQACRXrZIXQ9Qvp2Nw:-KBQACRXrZIXQ9Qvp2Nx:508040198) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/server/store_spec.go#L78)):*
s/attributes/fields/, since we use `attr` below. Do we need to consider the ability to escape `,` to include it in a field value or are commas simply forbidden?

---

*[server/store_spec_test.go, line 123 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBPcaR-HrjGnzTBSJuP:-KBQAZvgqYnerVCVuGVi:5172523) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/server/store_spec_test.go#L123)):*
+1

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-:-KBQAtmHBoEgTrQYLkuf:676834233)*

**Comment by tamird** [comment]
Review status: 12 of 14 files reviewed at latest revision, 14 unresolved discussions.

---

*[cli/start.go, line 106 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBPSNGnVjaESO9H9t21:-KBQBQYEOx2wwdi64AIh:798169789) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/cli/start.go#L106)):*
another comment i left gave the reason: i think it'll be more concise. as stated in that comment, i leave the decision up to @BramGruneir.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671)*

**Comment by petermattis** [comment]
LGTM

---

Review status: 12 of 14 files reviewed at latest revision, 20 unresolved discussions.

---

*[cloud/aws/README.md, line 77 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBQCYoTdTC9uG91vQow:-KBQCYoTdTC9uG91vQox:69297764) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/cloud/aws/README.md#L77)):*
Per Ben's comment elsewhere, I think we should remove the `attr=ssd` stuff until we're heavily pushing attributes.

---

*[cloud/aws/variables.tf, line 12 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBQCgUGaB0wA7XTaj4k:-KBQCgUH9-sl0LKAvgFF:-582564748) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/cloud/aws/variables.tf#L12)):*
`s/attr=ssd,path=//g`

---

*[server/store_spec.go, line 207 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBQDAxjKs3L_i8Xo-cT:-KBQDAxk4TIem79IBaMe:1632311796) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/server/store_spec.go#L207)):*
The name makes me think this is a singular value. Perhaps `s/StoreSpecValue/StoreSpecList/g`.

---

*[server/store_spec.go, line 216 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBQDc7YuU7heQQnCaFC:-KBQDc7Zb32kEzau-L9C:1048543387) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/server/store_spec.go#L216)):*
My pattern for adding a delimiter is something like this:

```
sep := ""
for _, ss := range ssv {
  fmt.Fprintf(&buffer, "%s--store=%s", sep, ss))
  sep = " "
}
```

Note that you should definitely be using `fmt.Fprintf(&buffer` instead of `buffer.WriteString(fmt.Sprintf(`.

---

*[server/store_spec.go, line 227 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBQDv2-di1POhalz9BN:-KBQDv2-di1POhalz9BO:-1644959977) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/server/store_spec.go#L227)):*
Do you know what this is used for? The existing values I've seen are all lowercase strings. So this might better be `"store"`. But I also don't know where it is used.

---

*[server/store_spec_test.go, line 111 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBQEJ8lEQfp_OSsmCkh:-KBQEJ8m725OvCTkPT30:61039102) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/server/store_spec_test.go#L111)):*
Nice tests!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-:-KBQEMoAIxv3LzIjWug8:676834233)*

**Comment by BramGruneir** [comment]
Review status: 7 of 14 files reviewed at latest revision, 21 unresolved discussions.

---

*[acceptance/cluster/localcluster.go, line 380 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBPR871yuERX4CXnwFc:-KBR2VSMGcJ5TvNCwMp_:-986892472) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/acceptance/cluster/localcluster.go#L380)):*
I found it very useful for debugging purposes to output the the command line used to start cockroach in the docker containers.  I can remove it if you prefer, but it seems like something we should see.  I moved it into the other info that shows the ui and tracing info.

---

*[acceptance/cluster/localcluster.go, line 426 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBQ7qRWMjEvlUlErYhp:-KBR48Xhe4VnDgCt1BfK:1683531236) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/acceptance/cluster/localcluster.go#L426)):*
Done.  As far as removing the examples with it, I don't think we should.  But we can reword the documentation accordingly.

---

*[cli/start.go, line 106 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBPSNGnVjaESO9H9t21:-KBREnteAq94HBF65Y4W:-406251133) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/cli/start.go#L106)):*
I prefer keeping it this way.

---

*[cloud/aws/README.md, line 77 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBQCYoTdTC9uG91vQow:-KBR7mNY5KlG-a-2TQzU:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/cloud/aws/README.md#L77)):*
Done.

---

*[cloud/aws/variables.tf, line 9 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBPSfnBlMellrHzDyBs:-KBR7kZ7_9TEldenmErU:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/cloud/aws/variables.tf#L9)):*
Done.

---

*[cloud/aws/variables.tf, line 12 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBQCgUGaB0wA7XTaj4k:-KBR7qLUqZUpSV2Q3TIP:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/cloud/aws/variables.tf#L12)):*
Done.

---

*[server/context.go, line 187 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBPT8CPQL_2KGc-XOoA:-KBR8MVa-51cJ5jBbl_Q:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/server/context.go#L187)):*
Done.

---

*[server/context.go, line 196 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBQ8sVed9pH1nCSL5Db:-KBREDT3GCm71uEqQTFq:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/server/context.go#L196)):*
Done.

---

*[server/context.go, line 203 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBPTQUkb8GqNUGuAUwu:-KBR99n3xzwZ21YS_ecJ:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/server/context.go#L203)):*
Done.

---

*[server/context.go, line 217 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBPY_lL0x2FB5ghgI12:-KBR9AdTMP8etQjF5sxs:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/server/context.go#L217)):*
Done.

---

*[server/context.go, line 225 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBPbermeKA6_eZy_VHd:-KBREZqAbSRc2yvs05t3:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/server/context.go#L225)):*
Done.

---

*[server/context_test.go, line 32 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBPbmYeZ4ZWyDAaiG3B:-KBREc6pUGdB7a8HMX5M:1055075514) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/server/context_test.go#L32)):*
I prefer the direct initialization.

---

*[server/store_spec.go, line 78 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBQACRXrZIXQ9Qvp2Nw:-KBREyI2CD2uGxvCkugc:-1107182146) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/server/store_spec.go#L78)):*
Good idea.  And commas are just forbidden from field values, including paths and attributes.

---

*[server/store_spec.go, line 207 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBQDAxjKs3L_i8Xo-cT:-KBRHBUEeqhWqktqeiT-:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/server/store_spec.go#L207)):*
Done.

---

*[server/store_spec.go, line 216 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBQDc7YuU7heQQnCaFC:-KBRHIR1YNf7CjZPDPTH:-1207184020) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/server/store_spec.go#L216)):*
I've made the change to use fmt.Fprint.  I kept my pattern in this case because it was used above in StoreSpecString  (where it isn't in a loop).  I'm might try to benchmark these methods.

---

*[server/store_spec.go, line 227 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBQDv2-di1POhalz9BN:-KBRI_xL-WDQz__zyxhk:-1743867591) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/server/store_spec.go#L227)):*
I really have no idea.  I know it's a requirement for the interface.

---

*[server/store_spec_test.go, line 116 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBPcRtgP_hYRyDdjW62:-KBYPlovbwiMb3ztHkfQ:-16419975) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/server/store_spec_test.go#L116)):*
That seems like overkill, but done.

---

*[server/store_spec_test.go, line 123 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBPcaR-HrjGnzTBSJuP:-KBYmrG5dCsy7NeL6kvF:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/server/store_spec_test.go#L123)):*
Done.

---

*[server/store_spec_test.go, line 127 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBPcnG2vEMHShz3BpXo:-KBYn-w0ywiZ_hAOJ2vQ:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/server/store_spec_test.go#L127)):*
Done.

---

*[server/store_spec_test.go, line 131 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBPcuP465lmIHC5_tXB:-KBYn49kpNnZznEGzjWX:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/server/store_spec_test.go#L131)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671)*

**Comment by BramGruneir** [comment]
I added more into the commit message and addressed all the feedback.  Feel free to give it another pass when you have a chance.

---

Review status: 7 of 14 files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-:-KBYrlERhxfeGo4rKr4y:-1477433050)*

**Comment by BramGruneir** [comment]
Review status: 7 of 14 files reviewed at latest revision, 11 unresolved discussions.

---

*[server/store_spec.go, line 227 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBQDv2-di1POhalz9BN:-KBYt6R46qSYWJRQ12hT:1001272719) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/server/store_spec.go#L227)):*
It seems to be used to check to see if it's a "string" in a few places, but otherwise is just for error messages.  And their own implementation seems to match the underlying struct name (which is not normally exported, so non-capitol first leter).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671)*

**Comment by petermattis** [comment]
LGTM

---

Review status: 7 of 14 files reviewed at latest revision, 10 unresolved discussions.

---

*[cloud/aws/README.md, line 77 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBQCYoTdTC9uG91vQow:-KBZE9LA2N-I51is1lmX:1399619974) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/cloud/aws/README.md#L77)):*
The `path=` isn't necessary, is it?

---

*[cloud/aws/variables.tf, line 12 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBQCgUGaB0wA7XTaj4k:-KBZED1lPxUW87O9FMdu:1191299511) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/cloud/aws/variables.tf#L12)):*
Ditto. 

---

*[server/store_spec.go, line 216 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBQDc7YuU7heQQnCaFC:-KBZEGylU7FhLLOWHxQv:-1993298957) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/server/store_spec.go#L216)):*
This isn't performance critical. I suggested the pattern I usually use because it is somewhat more concise.

---

*[server/store_spec_test.go, line 39 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBZEe3Ve9DGCYB6geeN:-KBZEe3Ve9DGCYB6geeO:1288373485) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8fa9ac8b34c29d4952047e11eb9f8a4d7eadc3/server/store_spec_test.go#L39)):*
All of the `Attrs: []string(nil)` settings can be removed. They are setting the `Attrs` field to `nil` which is the default. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-:-KBZEwT32LGjWobKCVEk:676834233)*

**Comment by bdarnell** [comment]
Review status: 7 of 14 files reviewed at latest revision, 9 unresolved discussions.

---

*[acceptance/cluster/localcluster.go, line 426 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBQ7qRWMjEvlUlErYhp:-KBZwAiJa4g5uhlAwHjs:-608418153) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/acceptance/cluster/localcluster.go#L426)):*
We should have a few examples with attributes but I think most examples shouldn't have them.

---

*[cli/start.go, line 106 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBPSNGnVjaESO9H9t21:-KBZwLmeVSNSx_tU-zPW:-817983553) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/cli/start.go#L106)):*
I'm missing something; what's the more concise version? `append()` does less type inferencing than composite literals so I can't come up with anything shorter.

---

*[cloud/aws/README.md, line 77 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBQCYoTdTC9uG91vQow:-KBZzuNdGjrJbZm8yv-9:1690352070) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/cloud/aws/README.md#L77)):*
It lets you include `=` in your path and makes it slightly more transparent that other options exist, but I would get rid of it in most examples. 

---

*[server/context.go, line 131 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KB_-FmZ0nDjek6Ef0Kt:-KB_-FmZ0nDjek6Ef0Ku:-1906406934) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8fa9ac8b34c29d4952047e11eb9f8a4d7eadc3/server/context.go#L131)):*
This sentence is unclear. But more importantly, I don't think we want to return two different values. For all practical purposes the cgroup memory should be treated as the physical memory so this function should be responsible for choosing the appropriate value to use.

---

*[server/store_spec.go, line 78 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBQACRXrZIXQ9Qvp2Nw:-KB_0G1uqr6vVMkVBM8b:-955889651) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/server/store_spec.go#L78)):*
Mention in this comment that commas are forbidden.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671)*

**Comment by BramGruneir** [comment]
Review status: 6 of 14 files reviewed at latest revision, 9 unresolved discussions.

---

*[acceptance/cluster/localcluster.go, line 426 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBQ7qRWMjEvlUlErYhp:-KBfhPY6MdeZUcLrT9dq:-1898182018) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/acceptance/cluster/localcluster.go#L426)):*
Removed the path= even.
I'm going to go over the documentation with Jesse tomorrow.

---

*[cloud/aws/README.md, line 77 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBQCYoTdTC9uG91vQow:-KBfbK7rPEYG9vYGGZp8:-151101272) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/cloud/aws/README.md#L77)):*
Removed path= from the readme.

---

*[cloud/aws/variables.tf, line 12 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBQCgUGaB0wA7XTaj4k:-KBfbs7R0Thg-HMrn077:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/cloud/aws/variables.tf#L12)):*
Done.

---

*[server/context.go, line 131 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KB_-FmZ0nDjek6Ef0Kt:-KBfdlNH40lP9yZyaANj:1758359711) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8fa9ac8b34c29d4952047e11eb9f8a4d7eadc3/server/context.go#L131)):*
Fixed.

---

*[server/store_spec.go, line 78 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBQACRXrZIXQ9Qvp2Nw:-KBfe5u8bVn2njY2FLK6:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/server/store_spec.go#L78)):*
Done.

---

*[server/store_spec.go, line 216 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBQDc7YuU7heQQnCaFC:-KBfeB7SGZXQMl8UkQnk:-1707092419) ([raw file](https://github.com/cockroachdb/cockroach/blob/4416496cb0ca483d716958aaeeb038d9f240c2fa/server/store_spec.go#L216)):*
Oh I know.  I just thought it would be a fun exercise to see which method is fastest.  This is a case where a ternary operator would be wonderful.  

---

*[server/store_spec_test.go, line 39 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-KBZEe3Ve9DGCYB6geeN:-KBfhL1pnUCUqjZflovw:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee8fa9ac8b34c29d4952047e11eb9f8a4d7eadc3/server/store_spec_test.go#L39)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671)*

**Comment by bdarnell** [comment]
LGTM

---

Review status: 6 of 14 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4671#-:-KBhYD9TNFrh9zlpABSJ:676834233)*

**Comment by BramGruneir** [comment]
Chatted with @jseldess, we're going to go over the CLI language in a follow up PR.

**Pull request merged**
