### PR TITLE
sqlsmith, tests, tree: add prepared queries to tlp

### PR DESCRIPTION
**Pull request by nehageorge**
Previously, we did not have statements with placeholders in TLP queries.
This could have caught a correctness bug (#71002).
In this PR, support for prepared queries is added.

Fixes #71216.

Release note: None

### CODE REVIEW

**Review by mgartner — CHANGES_REQUESTED** [review]
Nice! It might be fun to comment out [this line](https://github.com/cockroachdb/cockroach/blob/bb4100ed7f1eeaa6304f3b474d28746c98d1397c/pkg/sql/opt/norm/factory.go#L242-L241) and see if TLP rediscovers #71002.

> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71323#-:-MlWIXjq56OMUbe6tBEs:bcpvtxl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @nehageorge)

___
*[pkg/cmd/roachtest/tests/tlp.go, line 160 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71323#-MlWHPrr8QQIWgqjUNLJ:-MlWHPrr8QQIWgqjUNLK:b-9hmgjm) ([raw file](https://github.com/cockroachdb/cockroach/blob/39ad0e12802fb44c1cd6b2e89d57c6761742d490/pkg/cmd/roachtest/tests/tlp.go#L160)):*
> ```Go
> // runTLPQuery runs two queries to perform TLP. One is partitioned and one is
> // unpartitioned. If the results of the queries are not equal, an error is
> // returned. Generate TLP also returns any placeholder arguments needed for the
> ```

nit: remove space between `Generate` and `TLP`
___
*[pkg/cmd/roachtest/tests/tlp.go, line 187 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71323#-MlWI1aA66gDf8FAaYT_:-MlWI1aA66gDf8FAaYTa:b-y0dzf5) ([raw file](https://github.com/cockroachdb/cockroach/blob/39ad0e12802fb44c1cd6b2e89d57c6761742d490/pkg/cmd/roachtest/tests/tlp.go#L187)):*
> ```Go
> 			return nil
> 		}
> 		rows2, err := conn.Query(partitioned, args...)
> ```

I guess `conn.Query` will automatically call `.String()` or `SQLString()` on each arg? I wonder if it'd be more clear for the visitor to just collect args as `string`s from the get-go?
___
*[pkg/internal/sqlsmith/scalar.go, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71323#-MlWFwkq2Jed-MXR6P2w:-MlWFwkr9y7U4Gin4n3e:bvcy9uo) ([raw file](https://github.com/cockroachdb/cockroach/blob/39ad0e12802fb44c1cd6b2e89d57c6761742d490/pkg/internal/sqlsmith/scalar.go#L76)):*
> ```Go
> }
> 
> func makeBoolExprPlaceholder(s *Smither, refs colRefs) (tree.Expr, []interface{}) {
> ```

nit: maybe `makeBoolExprWithPlaceholders`?
___
*[pkg/internal/sqlsmith/tlp.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71323#-MlWGHRM4R1nMUiyjljZ:-MlWGHRM4R1nMUiyjlj_:bedketr) ([raw file](https://github.com/cockroachdb/cockroach/blob/39ad0e12802fb44c1cd6b2e89d57c6761742d490/pkg/internal/sqlsmith/tlp.go#L36)):*
> ```Go
> // have all been implemented in SQLancer. See:
> // https://github.com/sqlancer/sqlancer/tree/1.1.0/src/sqlancer/cockroachdb/oracle/tlp.
> func (s *Smither) GenerateTLP() (unpartitioned, partitioned string, args []interface{}) {
> ```

nit: explain what `args` is in the function comment
___
*[pkg/internal/sqlsmith/tlp.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71323#-MlWGP7M0cOMdGVd4b9T:-MlWGP7M0cOMdGVd4b9U:b-9vjtui) ([raw file](https://github.com/cockroachdb/cockroach/blob/39ad0e12802fb44c1cd6b2e89d57c6761742d490/pkg/internal/sqlsmith/tlp.go#L59)):*
> ```Go
> }
> 
> func (s *Smither) generatePrepareTLP() (unpartitioned, partitioned string, args []interface{}) {
> ```

nit: a quick explanation of what types of queries this function generates might be helpful
___
*[pkg/internal/sqlsmith/tlp.go, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71323#-MlWHef16cfuFUVNgCSb:-MlWHef16cfuFUVNgCSc:b-9wg8ht) ([raw file](https://github.com/cockroachdb/cockroach/blob/39ad0e12802fb44c1cd6b2e89d57c6761742d490/pkg/internal/sqlsmith/tlp.go#L81)):*
> ```Go
> 	partitioned = fmt.Sprintf("(%s) UNION ALL (%s) UNION ALL (%s)", part1, part2, part3)
> 
> 	return unpartitioned, partitioned, args
> ```

This function looks very similar to generateWhereTLP. Maybe it's worth combining them, and rollling the dice within the function to call either `makeBoolExpr` or `makeBoolExprWithPlaceholders`.
___
*[pkg/sql/sem/tree/placeholders.go, line 218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71323#-MlWGgkR212CqJnyeyTz:-MlWGgkR212CqJnyeyU-:bnduoum) ([raw file](https://github.com/cockroachdb/cockroach/blob/39ad0e12802fb44c1cd6b2e89d57c6761742d490/pkg/sql/sem/tree/placeholders.go#L218)):*
> ```Go
> // expressions with placeholders, and updates Args with the corresponding Datum
> // values. This is used to prepare and execute a statement with placeholders.
> type ReplaceDatumPlaceholderVisitor struct{
> ```

You should be able to move this to `sqlsmith/scalar.go` since it is only used there. It can be unexported then too.
___
*[pkg/sql/sem/tree/placeholders.go, line 219 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71323#-MlWH9KtAuug7SAOGyQ1:-MlWH9KtAuug7SAOGyQ2:brvlkmw) ([raw file](https://github.com/cockroachdb/cockroach/blob/39ad0e12802fb44c1cd6b2e89d57c6761742d490/pkg/sql/sem/tree/placeholders.go#L219)):*
> ```Go
> // values. This is used to prepare and execute a statement with placeholders.
> type ReplaceDatumPlaceholderVisitor struct{
> 	Args []interface{}
> ```

I think you can narrow down this type to `[]Expr`.

**Review by nehageorge — COMMENTED** [review]
Tried it three times so far and no luck yet :( ... I think we may have to run it many many times since `getBoolExprContext` most often returns `true`, `false`, or `NULL`, and we can't add placeholders to those expressions.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71323#-:-MlWXqyJCfILr7O_z8Bg:byyoa0m)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/cmd/roachtest/tests/tlp.go, line 160 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71323#-MlWHPrr8QQIWgqjUNLJ:-MlWVTz4EXPjMFNglf-W:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/39ad0e12802fb44c1cd6b2e89d57c6761742d490/pkg/cmd/roachtest/tests/tlp.go#L160)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: remove space between `Generate` and `TLP`
</blockquote></details>

Done
___
*[pkg/cmd/roachtest/tests/tlp.go, line 187 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71323#-MlWI1aA66gDf8FAaYT_:-MlWU60z2cAbnOnC2W0Z:bmvho4f) ([raw file](https://github.com/cockroachdb/cockroach/blob/39ad0e12802fb44c1cd6b2e89d57c6761742d490/pkg/cmd/roachtest/tests/tlp.go#L187)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I guess `conn.Query` will automatically call `.String()` or `SQLString()` on each arg? I wonder if it'd be more clear for the visitor to just collect args as `string`s from the get-go?
</blockquote></details>

I think so. It actually doesn't accept `[]string` or `[]tree.Expr` types as input (only `[]interface{}`) so that's why it's set up like this. But I do agree that `[]string` would be clearer.
___
*[pkg/internal/sqlsmith/scalar.go, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71323#-MlWFwkq2Jed-MXR6P2w:-MlWVVN62vt-nCcQocgF:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/39ad0e12802fb44c1cd6b2e89d57c6761742d490/pkg/internal/sqlsmith/scalar.go#L76)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: maybe `makeBoolExprWithPlaceholders`?
</blockquote></details>

Done
___
*[pkg/internal/sqlsmith/tlp.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71323#-MlWGHRM4R1nMUiyjljZ:-MlWVWSc6GSGPV0Tekm_:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/39ad0e12802fb44c1cd6b2e89d57c6761742d490/pkg/internal/sqlsmith/tlp.go#L36)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: explain what `args` is in the function comment
</blockquote></details>

Done
___
*[pkg/internal/sqlsmith/tlp.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71323#-MlWGP7M0cOMdGVd4b9T:-MlWVXTU4_h60Bqyh4mQ:bmze3wi) ([raw file](https://github.com/cockroachdb/cockroach/blob/39ad0e12802fb44c1cd6b2e89d57c6761742d490/pkg/internal/sqlsmith/tlp.go#L59)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: a quick explanation of what types of queries this function generates might be helpful
</blockquote></details>

I merged this function with `generateWhereTLP`, done.
___
*[pkg/internal/sqlsmith/tlp.go, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71323#-MlWHef16cfuFUVNgCSb:-MlWVdqg212QPcdEss6f:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/39ad0e12802fb44c1cd6b2e89d57c6761742d490/pkg/internal/sqlsmith/tlp.go#L81)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This function looks very similar to generateWhereTLP. Maybe it's worth combining them, and rollling the dice within the function to call either `makeBoolExpr` or `makeBoolExprWithPlaceholders`.
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/placeholders.go, line 218 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71323#-MlWGgkR212CqJnyeyTz:-MlWVezL1m_a1WSjiigb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/39ad0e12802fb44c1cd6b2e89d57c6761742d490/pkg/sql/sem/tree/placeholders.go#L218)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

You should be able to move this to `sqlsmith/scalar.go` since it is only used there. It can be unexported then too.
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/placeholders.go, line 219 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71323#-MlWH9KtAuug7SAOGyQ1:-MlWUW_NB8y5w0MiC2J-:bc6p0b6) ([raw file](https://github.com/cockroachdb/cockroach/blob/39ad0e12802fb44c1cd6b2e89d57c6761742d490/pkg/sql/sem/tree/placeholders.go#L219)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I think you can narrow down this type to `[]Expr`.
</blockquote></details>

See my above comment. `conn.Query` doesn't accept this type.

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71323#-:-MluTLa_9r9D77V0xzZM:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @nehageorge)

___
*[pkg/cmd/roachtest/tests/tlp.go, line 187 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71323#-MlWI1aA66gDf8FAaYT_:-MluSmY-9Qerj-TjL7Yr:be9l9jh) ([raw file](https://github.com/cockroachdb/cockroach/blob/39ad0e12802fb44c1cd6b2e89d57c6761742d490/pkg/cmd/roachtest/tests/tlp.go#L187)):*
<details><summary><i>Previously, nehageorge wrote…</i></summary><blockquote>

I think so. It actually doesn't accept `[]string` or `[]tree.Expr` types as input (only `[]interface{}`) so that's why it's set up like this. But I do agree that `[]string` would be clearer.
</blockquote></details>

A function that accepts `[]interface{}` should be able to accept a slice of any type, unless I'm mistaken. This seems to work: `_, _ = conn.Query("SELECT $1", []string{"1"})`.

**Review by nehageorge — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71323)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/cmd/roachtest/tests/tlp.go, line 187 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71323#-MlWI1aA66gDf8FAaYT_:-MluV_Gy8sqPVJk9qnwh:b7fnjsw) ([raw file](https://github.com/cockroachdb/cockroach/blob/39ad0e12802fb44c1cd6b2e89d57c6761742d490/pkg/cmd/roachtest/tests/tlp.go#L187)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

A function that accepts `[]interface{}` should be able to accept a slice of any type, unless I'm mistaken. This seems to work: `_, _ = conn.Query("SELECT $1", []string{"1"})`.
</blockquote></details>

I believe that passes the `args` as a single argument. When it's run with variadic input as desired, it gives me this error: `Cannot use '[]string{"1"}' (type []string) as the type []interface{}`

**Pull request merged**
