### PR TITLE
 roachprod: create terraform-based API resource management for AWS

### PR DESCRIPTION
**Pull request by ajwerner**
In order to run a roachprod cluster in AWS one needs to configure vms with
resources which exist on a per-region or per-availability zone basis.

Each region requires a VPC with security groups, AMIs and subnets which defines
the availability zone within the region. Furthermore, each region's VPC must be
configured with peering to each other VPC.

Currently this is set up just for 3 regions (us-east-2, us-west-2, eu-west-2).
Using additional regions requires setting up the required resources manually
and then connecting them through a variety of less than ergonomic flags.

In gcloud we have a different story; users can just specify a list of
availability zones in which to place the instances. This could yet be made
better by providing an easy way to distribute nodes within regions over
availability zones (see #36400).

This PR creates the machinery to set up AWS for convenient use with arbitrary
regions.

The basic architecture is that there's a collection of terraform files under
`cmd/roachprod/vm/aws/terraform` which defines resources and modules to manage
the above described required AWS resources.

The `main.tf` for the terraform project is generated by a go program
`terraformgen` which allows users to specify the account number, resource name
prefix and the set of regions. The templating is especially important because
of the need for pair-wise peerings between each region. The terraform project
is set up to output the relevant IDs which, with the combination of the the
`--json` flag will be used to produce an artifact which roachprod will consume.

The second commit adopts this information from the first by setting up `go:generate` directives to:

  1. Generate the terraform `main.tf` which is used to generate `config.json`.
  2. Generate the `embedded.go` bindata file to contain the default json value.

The commit then defines the `awsConfig` struct to usefully expose the
information produced by terraform to create instances. Users can override the
embedded default configuration by providing similarly formatted json in a file
passed by path to the '--aws-config` flag.

### CODE REVIEW

**Review by DuskEagle — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 7 of 7 files at r4, 8 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36418)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/36418#-LbUSY-lCfLbrimAHKSy:-LbUSY-lCfLbrimAHKSz:b-nm5os1) (no related file):*
Code looks good to me; just some small feedback on the comments.

---
___
*[pkg/cmd/roachprod/vm/aws/config.go, line 25 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/36418#-LbUQF59DUwd_UOj6Zw-:-LbUQF59DUwd_UOj6Zw0:bfmh5rg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a97e0951db1b14a925a525a8eadee62ed8bb419f/pkg/cmd/roachprod/vm/aws/config.go#L25)):*
> ```Go
> 
> // The below directives create two files, the first is a terraform main file
> // that lives in the terraform subdirectory. The second file is produces the
> ```

nit: "is produces the" -> "it produces is the"
___
*[pkg/cmd/roachprod/vm/aws/terraformgen/terraformgen.go, line 42 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/36418#-LbUOJGxECjvqfGvOT3w:-LbUOJGyDSheyRwiFul8:b-hjqbjk) ([raw file](https://github.com/cockroachdb/cockroach/blob/0afe1cc909f0436ab79b6d75330640dcde7eb15d/pkg/cmd/roachprod/vm/aws/terraformgen/terraformgen.go#L42)):*
> ```Go
>     key            = "terraform/{{ .ResourcePrefix }}"
> 
>     # Fixed fields, DO NOT MODIFY.
> ```

I think this comment is intended mainly for the managed service, where all Terraform states are stored in one bucket, and only the key changes for each different cluster. It's unnecessary here, where the bucket will change depending on the ResourcePrefix.
___
*[pkg/cmd/roachprod/vm/aws/terraformgen/terraformgen.go, line 52 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/36418#-LbUOzLFB9LSPX88CPhe:-LbUOzLFB9LSPX88CPhf:b4wtjnc) ([raw file](https://github.com/cockroachdb/cockroach/blob/0afe1cc909f0436ab79b6d75330640dcde7eb15d/pkg/cmd/roachprod/vm/aws/terraformgen/terraformgen.go#L52)):*
> ```Go
> # ---------------------------------------------------------------------------------------------------------------------
> locals {
>   # Cockroach-Labs Shared
> ```

This comment might be misleading if the account number changes.
___
*[pkg/cmd/roachprod/vm/aws/terraformgen/terraformgen.go, line 195 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/36418#-LbUPNEJBKmzj-ZdfAU2:-LbUPNEK-BIJNPIB_pGw:b8wqerz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0afe1cc909f0436ab79b6d75330640dcde7eb15d/pkg/cmd/roachprod/vm/aws/terraformgen/terraformgen.go#L195)):*
> ```Go
> 		"list of regions to operate in")
> 	rootCmd.Flags().StringVar(&data.AccountNumber, "account-number", data.AccountNumber,
> 		"list of regions to operate in")
> ```

"AWS account to operate in"
___
*[pkg/cmd/roachprod/vm/aws/terraformgen/terraformgen.go, line 178 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/36418#-LbURqgi20Gsr-Gg4W_N:-LbURqgi20Gsr-Gg4W_O:b9c5iyo) ([raw file](https://github.com/cockroachdb/cockroach/blob/a97e0951db1b14a925a525a8eadee62ed8bb419f/pkg/cmd/roachprod/vm/aws/terraformgen/terraformgen.go#L178)):*
> ```Go
> 		Long: `
> terraformgen sets up VPCs and security groups for each of specified regions for
> the provided account number. The generated file then has an output which is
> ```

This comment sort of suggests running terraformgen will be sufficient to set up the VPC peering and security groups for the provided account. It might be worth noting that you have to run `terraform apply` in the directory of the generated output afterward.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36418)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DuskEagle)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/36418#-LbUSY-lCfLbrimAHKSy:-LbUnkZN8kh6ehk74_lt:b-ncgzc2) (no related file):*
<details><summary><i>Previously, DuskEagle (Joel Kenny) wrote…</i></summary><blockquote>

Code looks good to me; just some small feedback on the comments.
</blockquote></details>

Thanks for the quick review!

---
___
*[pkg/cmd/roachprod/vm/aws/terraformgen/terraformgen.go, line 42 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/36418#-LbUOJGxECjvqfGvOT3w:-LbUn0qX8qq4nFImwJjj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0afe1cc909f0436ab79b6d75330640dcde7eb15d/pkg/cmd/roachprod/vm/aws/terraformgen/terraformgen.go#L42)):*
<details><summary><i>Previously, DuskEagle (Joel Kenny) wrote…</i></summary><blockquote>

I think this comment is intended mainly for the managed service, where all Terraform states are stored in one bucket, and only the key changes for each different cluster. It's unnecessary here, where the bucket will change depending on the ResourcePrefix.
</blockquote></details>

Done.
___
*[pkg/cmd/roachprod/vm/aws/terraformgen/terraformgen.go, line 52 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/36418#-LbUOzLFB9LSPX88CPhe:-LbUn1W1CHILpHKdD832:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0afe1cc909f0436ab79b6d75330640dcde7eb15d/pkg/cmd/roachprod/vm/aws/terraformgen/terraformgen.go#L52)):*
<details><summary><i>Previously, DuskEagle (Joel Kenny) wrote…</i></summary><blockquote>

This comment might be misleading if the account number changes.
</blockquote></details>

Done.
___
*[pkg/cmd/roachprod/vm/aws/terraformgen/terraformgen.go, line 195 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/36418#-LbUPNEJBKmzj-ZdfAU2:-LbUnjcU2nyIDCzawcG3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0afe1cc909f0436ab79b6d75330640dcde7eb15d/pkg/cmd/roachprod/vm/aws/terraformgen/terraformgen.go#L195)):*
<details><summary><i>Previously, DuskEagle (Joel Kenny) wrote…</i></summary><blockquote>

"AWS account to operate in"
</blockquote></details>

Done.
___
*[pkg/cmd/roachprod/vm/aws/terraformgen/terraformgen.go, line 178 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/36418#-LbURqgi20Gsr-Gg4W_N:-LbUnj4c3VUtLr9g55Of:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a97e0951db1b14a925a525a8eadee62ed8bb419f/pkg/cmd/roachprod/vm/aws/terraformgen/terraformgen.go#L178)):*
<details><summary><i>Previously, DuskEagle (Joel Kenny) wrote…</i></summary><blockquote>

This comment sort of suggests running terraformgen will be sufficient to set up the VPC peering and security groups for the provided account. It might be worth noting that you have to run `terraform apply` in the directory of the generated output afterward.
</blockquote></details>

Done.

**Pull request merged**
