### PR TITLE
engine: fix divergent MVCCStats updates

### PR DESCRIPTION
**Pull request by tbg**
Found while investigating #20554 (though this does not at all fix the issue
discovered there; that will be a separate PR).

We were incorrectly updating GCBytesAge when moving an intent.

This change raises the question of what to do about the divergent stats
that exist in real-world clusters. As part of addressing #20554, we'll need
a mechanism to correct the stats anyway, and so I will defer its
introduction.

You'll want to view this diff with `?w=1` (insensitive to whitespace
changes).

Release note: None.

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, 3 of 3 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[pkg/storage/engine/mvcc.go, line 1847 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20996#-L10E2OUGz1meuHWn6lH:-L10E2OUGz1meuHWn6lI:b-irmds4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1b76018d2c6362b983c2d51afd363ecc6af3e44/pkg/storage/engine/mvcc.go#L1847)):*
> ```Go
> }
> 
> // unsafePeekNextVersion positions the iterator at the successor to latestKey. If this value
> ```

I'm not sure I like the term `"peek"` here. That usually implies that the iterator is not moved by the function (for instance, that's the case for `sql/parser.Scanner`), which is not true in this case. `unsafeNextVersion` is probably a better name.

---

*[pkg/storage/engine/mvcc.go, line 1859 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20996#-L10D3WaoNJhAs7VsBMq:-L10D3WaoNJhAs7VsBMr:bzyw3g) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1b76018d2c6362b983c2d51afd363ecc6af3e44/pkg/storage/engine/mvcc.go#L1859)):*
> ```Go
> 	}
> 	unsafeKey := iter.UnsafeKey()
> 	if !unsafeKey.IsValue() {
> ```

Is this case actually possible or is it just a sanity check? We already verified that the next value had the same key.

---

*[pkg/storage/engine/mvcc.go, line 326 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/20996#-L10L9DmXM5vvBz99LPK:-L10L9DmXM5vvBz99LPL:bsh5xl8) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a5bf742553583fb2ab6cdb7631777b5156e5757/pkg/storage/engine/mvcc.go#L326)):*
> ```Go
> 
> 	if sys {
> 		ms.SysBytes += metaKeySize + metaValSize - origMetaValSize - origMetaKeySize
> ```

minor nit here and below: `(metaKeySize + metaValSize) - (origMetaValSize + origMetaKeySize)` is a bit easier to read.

---

*[pkg/storage/engine/mvcc.go, line 333 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/20996#-L10RyrNx9RRwSWJvr9v:-L10RyrNx9RRwSWJvr9w:b-zgh6ra) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a5bf742553583fb2ab6cdb7631777b5156e5757/pkg/storage/engine/mvcc.go#L333)):*
> ```Go
> 		}
> 		// At orig.Timestamp, the original meta key disappears.
> 		ms.KeyBytes -= origMetaKeySize + orig.KeyBytes
> ```

Were we missing the `orig.KeyBytes` and `meta.KeyBytes` handling before? That wasn't the fundamental problem here, right?

---

*[pkg/storage/engine/mvcc.go, line 342 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/20996#-L10RkPGW3coeFid2c16:-L10RkPGW3coeFid2c17:bquygox) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a5bf742553583fb2ab6cdb7631777b5156e5757/pkg/storage/engine/mvcc.go#L342)):*
> ```Go
> 		}
> 
> 		ms.AgeTo(meta.Timestamp.WallTime)
> ```

I think I understand what's going on here after staring at this for 10 minutes, but since this always takes so long to page back in, do you mind expanding the commit message to explain what the "divergent MVCCStats update" was? Maybe also add a comment about why this `ms.AgeTo` needs to be above the `KeyBytes` and `ValBytes` change below.

---

*[pkg/storage/engine/mvcc_stats_test.go, line 1 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/20996#-L10HHHMNKvs2ET1DaAB:-L10HHHMNKvs2ET1DaAC:b-oq96do) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f4af813c4a90c9b9558401344950a5943364ea/pkg/storage/engine/mvcc_stats_test.go#L1)):*
> ```Go
> // Copyright 2014 The Cockroach Authors.
> ```

There were no changes in this code movement, right?

---

*[pkg/storage/engine/mvcc_test.go, line 3414 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20996#-L10EmjyO0Q3AeNKVeQl:-L10EmjyO0Q3AeNKVeQm:b-b2kjeh) ([raw file](https://github.com/cockroachdb/cockroach/blob/77b601199a81211bf15d03f489e39a98cdd30180/pkg/storage/engine/mvcc_test.go#L3414)):*
> ```Go
> }
> 
> func verifyStats(debug string, ms, expMS *enginepb.MVCCStats, t *testing.T) {
> ```

nit: consider moving `t *testing.T` to be the first argument.

---

*[pkg/storage/engine/mvcc_test.go, line 3416 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20996#-L10EvQQO8LQ6aGnmF1w:-L10EvQQO8LQ6aGnmF1x:bwwh0c1) ([raw file](https://github.com/cockroachdb/cockroach/blob/77b601199a81211bf15d03f489e39a98cdd30180/pkg/storage/engine/mvcc_test.go#L3416)):*
> ```Go
> func verifyStats(debug string, ms, expMS *enginepb.MVCCStats, t *testing.T) {
> 	t.Helper()
> 	if !ms.Equal(expMS) {
> ```

Huh, why weren't we just doing this before?

---

*[pkg/storage/engine/mvcc_test.go, line 3436 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20996#-L10GXf8Q_tlLEot22OB:-L10GXf8Q_tlLEot22OC:b-v5d1na) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bf2c174fb589e33ccf3b17d087bcf047375f1d1/pkg/storage/engine/mvcc_test.go#L3436)):*
> ```Go
> 		verifyStats(debug, ms, expMS, t)
> 
> 		it := engine.NewIterator(false)
> ```

Think it makes sense to put this all in `verifyStats` so that we make the assertion everywhere?

---

*[pkg/storage/engine/mvcc_test.go, line 3452 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20996#-L10Gh0Q6U4wYe3g_iQu:-L10Gh0Q6U4wYe3g_iQv:b-iukzzr) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bf2c174fb589e33ccf3b17d087bcf047375f1d1/pkg/storage/engine/mvcc_test.go#L3452)):*
> ```Go
> 		}
> 
> 		if t.Failed() {
> ```

What's this about?

---

*[pkg/storage/engine/mvcc_test.go, line 3491 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20996#-L10G92YL115mxfhzioT:-L10G92YL115mxfhzioU:b-t7xsus) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bf2c174fb589e33ccf3b17d087bcf047375f1d1/pkg/storage/engine/mvcc_test.go#L3491)):*
> ```Go
> 
> 	// Delete the value using a transaction.
> 	// TODO(tschottdorf): this case is interesting: we write at ts2, bt the timestamp is ts1.
> ```

`s/bt/but/`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20996)*

**Comment by tschottdorf** [comment]
@nvanbenschoten I'll get to your comments, but in the meantime, I dumped an additional number of commits that finds and addresses a boatload of bugs.

**Comment by tschottdorf** [comment]
Review status: 0 of 13 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[pkg/storage/engine/mvcc.go, line 1847 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20996#-L10E2OUGz1meuHWn6lH:-L15lrn5AAUFCnZJFDlc:b-ti493h) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1b76018d2c6362b983c2d51afd363ecc6af3e44/pkg/storage/engine/mvcc.go#L1847)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm not sure I like the term `"peek"` here. That usually implies that the iterator is not moved by the function (for instance, that's the case for `sql/parser.Scanner`), which is not true in this case. `unsafeNextVersion` is probably a better name.
</blockquote></details>

Done. I moved this to https://github.com/cockroachdb/cockroach/pull/21036 because this PR is becoming large and I assume it won't land for a while.

---

*[pkg/storage/engine/mvcc.go, line 1859 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20996#-L10D3WaoNJhAs7VsBMq:-L15m1GnBmqB2remi_LU:bakw78h) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1b76018d2c6362b983c2d51afd363ecc6af3e44/pkg/storage/engine/mvcc.go#L1859)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this case actually possible or is it just a sanity check? We already verified that the next value had the same key.
</blockquote></details>

Sanity check. This is also the previous code.
I moved this to https://github.com/cockroachdb/cockroach/pull/21036 because this PR is becoming large and I assume it won't land for a while.

---

*[pkg/storage/engine/mvcc_stats_test.go, line 1 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/20996#-L10HHHMNKvs2ET1DaAB:-L15mEhCv95EOTkf0v3p:btqqu5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f4af813c4a90c9b9558401344950a5943364ea/pkg/storage/engine/mvcc_stats_test.go#L1)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

There were no changes in this code movement, right?
</blockquote></details>

Correct.

---

*[pkg/storage/engine/mvcc_test.go, line 3416 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20996#-L10EvQQO8LQ6aGnmF1w:-L15leA4JC0dVfHTC1u-:b-sebpxf) ([raw file](https://github.com/cockroachdb/cockroach/blob/77b601199a81211bf15d03f489e39a98cdd30180/pkg/storage/engine/mvcc_test.go#L3416)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Huh, why weren't we just doing this before?
</blockquote></details>

I think this code predated `pretty.Diff`.

---

*[pkg/storage/engine/mvcc_test.go, line 3452 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20996#-L10Gh0Q6U4wYe3g_iQu:-L15lKI_5ExonaQIMnZD:bn3jmmh) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bf2c174fb589e33ccf3b17d087bcf047375f1d1/pkg/storage/engine/mvcc_test.go#L3452)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What's this about?
</blockquote></details>

You want to see the numbers from all the computations above (once they are upgraded to `Errorf`), but then bail.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20996)*

**Comment by tschottdorf** [comment]
Review status: 0 of 13 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[pkg/storage/engine/mvcc.go, line 326 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/20996#-L10L9DmXM5vvBz99LPK:-L15oYeIOgB1pFp-h5oq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a5bf742553583fb2ab6cdb7631777b5156e5757/pkg/storage/engine/mvcc.go#L326)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

minor nit here and below: `(metaKeySize + metaValSize) - (origMetaValSize + origMetaKeySize)` is a bit easier to read.
</blockquote></details>

Done.

---

*[pkg/storage/engine/mvcc.go, line 333 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/20996#-L10RyrNx9RRwSWJvr9v:-L15oZG2lDx3RWe5PwPh:bdmykx0) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a5bf742553583fb2ab6cdb7631777b5156e5757/pkg/storage/engine/mvcc.go#L333)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Were we missing the `orig.KeyBytes` and `meta.KeyBytes` handling before? That wasn't the fundamental problem here, right?
</blockquote></details>

Yep. I added to the commit message.

---

*[pkg/storage/engine/mvcc.go, line 342 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/20996#-L10RkPGW3coeFid2c16:-L15pc06I8KaqF56igvm:b-aze04i) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a5bf742553583fb2ab6cdb7631777b5156e5757/pkg/storage/engine/mvcc.go#L342)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think I understand what's going on here after staring at this for 10 minutes, but since this always takes so long to page back in, do you mind expanding the commit message to explain what the "divergent MVCCStats update" was? Maybe also add a comment about why this `ms.AgeTo` needs to be above the `KeyBytes` and `ValBytes` change below.
</blockquote></details>

Yep. I added to the commit message. By the way, testing gets a lot better in later commits, with more descriptive and smaller tests.

---

*[pkg/storage/engine/mvcc_test.go, line 3414 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20996#-L10EmjyO0Q3AeNKVeQl:-L15mp_dpwqrd1qt-ygy:b-tokev) ([raw file](https://github.com/cockroachdb/cockroach/blob/77b601199a81211bf15d03f489e39a98cdd30180/pkg/storage/engine/mvcc_test.go#L3414)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: consider moving `t *testing.T` to be the first argument.
</blockquote></details>

Good point, but with the code movement and the fact that it's cleaned up in later commits, I'd like to leave it as is in this one.

---

*[pkg/storage/engine/mvcc_test.go, line 3436 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20996#-L10GXf8Q_tlLEot22OB:-L15mWSKVfzPpP7BSdf0:b-80iabn) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bf2c174fb589e33ccf3b17d087bcf047375f1d1/pkg/storage/engine/mvcc_test.go#L3436)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Think it makes sense to put this all in `verifyStats` so that we make the assertion everywhere?
</blockquote></details>

This 

---

*[pkg/storage/engine/mvcc_test.go, line 3491 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20996#-L10G92YL115mxfhzioT:-L15n85_qjw4B3XfaBe4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9bf2c174fb589e33ccf3b17d087bcf047375f1d1/pkg/storage/engine/mvcc_test.go#L3491)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`s/bt/but/`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20996)*

**Comment by tschottdorf** [comment]
Actually I just nuked these extra commits again. I'll open a separate PR with them when this one is in. Sorry about the diff noise.

---

Review status: 1 of 4 files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20996#-:-L15rrc0nWuvcjQHtgwG:b-wf3ix4)*

**Comment by nvanbenschoten** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r8, 2 of 2 files at r9, 3 of 3 files at r10, 1 of 1 files at r11.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20996#-:-L1O1Zv1bxKWIRlM6xDI:bnfp4nl)*

**Comment by tschottdorf** [comment]
TFTR @nvanbenschoten!

**Pull request merged**
