### PR TITLE
backupccl: RESTORE TENANT x .. WITH tenant = y

### LINKED ISSUE #73609: restore: support restoring data into a different tenant
Currently tenant-run RESTOREs of tables and databases support restoring even if the tenant running the restore is different than the one that backed up, because we remove the tenant prefix, if any, from the backed up data and prepend the new tenant prefix. However _cluster_ restores are not supported in this case, because the jobs may contain spans the that have tenant prefixed, and more broadly we don't support restoring tables or databases or clusters backed up by a tenant into system tenant or restoring a backup of a tenant into a different tenant ID wholesale. That is, any host-cluster run restore of guest-tenant data always restores it to the same tenant. 

Instead, we should be able to restore data into any tenant ID and from any tenant ID. For simple table and database restores in the system tenant from a backup from a non-system tenant, this should be as easy as removing the tenant prefix, but we'd need to communicate this to the rekeyer as distinct from tenant restore, where keys are left as-is. For restore of one tenant into a different tenant id, or for "cluster" restores that restore jobs from one tenant id to another (including into or out of system tenants) we also need to change all jobs to store only the suffix of their spans, not encoded spans, in their progress checkpoints.

Epic: CRDB-8817

### PR DESCRIPTION
**Pull request by dt**
This adds support for restoring a tenant with a new tenant ID, allowing restoring
into a cluster that already has an existing tenant (perhaps the same one) at the
ID of the backed up tenant.

Release note: none.

### CODE REVIEW

**Comment by dt** [comment]
still needs a e2e test but it seems to work in demo.

**Review by adityamaru — APPROVED** [review]

**Comment by dt** [comment]
TFTR!

bors r+

**Comment by dt** [comment]
Failure in alter logic test seems unrelated.

bors r+

**Comment by dt** [comment]
`TestRemoveDeadReplicas` looks unrelated too.

bors r+

**Pull request merged**
