### PR TITLE
hlc,sql: expose structured error for untrustworthy clocks, make it retriable in schema changes

### LINKED ISSUE #63636: schema: `remote wall time is too far ahead` error considered permanent
I saw this on a roachprod cluster, which have been having trouble with clocks over the past few months. A large `ALTER TABLE ADD COLUMN` schema change hit a clock sync error:
```
job 649711962939129857: cannot be reverted, manual cleanup may be required: remote wall time is too far ahead (998.616155ms) to be trustworthy
```
This error can be bubbled up if hit [here](https://github.com/cockroachdb/cockroach/blob/46401472ab79dbe6c103a54886d71dc21ecf7835/pkg/kv/kvserver/store_send.go#L90). It is currently non-structured and is created [here](https://github.com/cockroachdb/cockroach/blob/87ed071f5a23295b34fd4d56d4539f0d0207f937/pkg/util/hlc/hlc.go#L422).

The schema then seemed to get stuck in this state. Future attempts to re-run the schema change hit:
```
ERROR: duplicate: column "crdb_region" in the middle of being added, not yet public
```
We should make sure that there is some way to recover from this error.

### PR DESCRIPTION
**Pull request by ajwerner**
Two commits:

* Structure the error.
* Detect it in the schema changer.

Fixes #63636.
    
Release note (bug fix): Fixed a bug whereby transient clock synchronization
errors could result in permanent schema change failures.

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm: thanks!

> Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63671#-:-MYHVypz6gKF3tAhULhE:brfqlux)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/util/hlc/hlc.go, line 413 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63671#-MYHUpn_DN5vO8q8Dgpv:-MYHUpn_DN5vO8q8Dgpw:b-7fnje7) ([raw file](https://github.com/cockroachdb/cockroach/blob/17b5d230575884566cbd5256c516bd6ae40a4cd5/pkg/util/hlc/hlc.go#L413)):*
> ```Go
> }
> 
> type untrustworthyRemoveWallTimeError struct {
> ```

Can you remind me what will happen if this gets jammed into a `roachpb.Error` and then passed over the network?
___
*[pkg/util/hlc/hlc.go, line 423 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63671#-MYHUgEJ56C2EwozatNO:-MYHUgEKCW-lKfPrVSUE:b870dbe) ([raw file](https://github.com/cockroachdb/cockroach/blob/17b5d230575884566cbd5256c516bd6ae40a4cd5/pkg/util/hlc/hlc.go#L423)):*
> ```Go
> }
> 
> // IsUntrustworthyRemoteWallTimeError returns
> ```

What does it return?

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63671)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[pkg/util/hlc/hlc.go, line 413 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63671#-MYHUpn_DN5vO8q8Dgpv:-MYIfHnJ98MgEjBZGqYW:bjanaa) ([raw file](https://github.com/cockroachdb/cockroach/blob/17b5d230575884566cbd5256c516bd6ae40a4cd5/pkg/util/hlc/hlc.go#L413)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can you remind me what will happen if this gets jammed into a `roachpb.Error` and then passed over the network?
</blockquote></details>

Good catch. Added some code and a test. 
___
*[pkg/util/hlc/hlc.go, line 423 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63671#-MYHUgEJ56C2EwozatNO:-MYIfKx67npyJfB_Sapp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/17b5d230575884566cbd5256c516bd6ae40a4cd5/pkg/util/hlc/hlc.go#L423)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What does it return?
</blockquote></details>

Done.

**Comment by ajwerner** [comment]
Simplified the on-the-wire error stuff

**Review by nvb — APPROVED** [review]
:lgtm_strong: 

> Reviewed 3 of 5 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63671#-:-MYMILoaCpoJCJv8xCsv:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by ajwerner** [comment]
TFTR!

bors r=nvanbenschoten

**Pull request merged**
