### PR TITLE
[Prototype] metrics: Add indicator information for CRDB metrics

### PR DESCRIPTION
**Pull request by rimadeodhar**
In this commit, I put in a prototype framework for adding and exposing indicator information for metrics. This commit only puts in a skeleton framework to outline the rough idea. This framework along with the initial feedback on it will power the RFC that I will share more broadly.

Related issue: #66004

### CODE REVIEW

**Comment by knz** [comment]
I looked at the change and the API looks reasonable to me.

Can you outline how this would work, by providing an example IndicatorInfo instance for a few metrics we already support?

**Review by rimadeodhar — COMMENTED** [review]
Thanks @knz  for the quick review. Let me find some examples and add them here. Will make sure I do the same when I put out the RFC.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67626#-:-MeajNI348mNoJfBTvBz:b-upkceb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @joshimhoff, @knz, and @tbg)

**Review by joshimhoff — COMMENTED** [review]
LGTM. Looking forward to the RFC. I have asked some Qs that are prob a better fit for the RFC. Plz feel free to push them off if that is true.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67626#-:-MeeSuRvEEM0arSm9zIc:b-3r2nuc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @rimadeodhar, and @tbg)

___
*[pkg/util/metric/metric.proto, line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67626#-MeeQy2H3rZj3CIi8MEK:-MeeQy2I5WP5ypLE4nqX:b-2bwobh) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c02de10b2bcdc22e2f8cb62589d12c540847bdb/pkg/util/metric/metric.proto#L61)):*
> ```protobuf
> }
> 
> // IndicatorInfo holds information on how to derive an indicator
> ```

WARNING naming bikeshed: What do we get by creating this term "indicator" for the result of applying an aggregation to a metric / some metrics? The API changes here are useful at a documentation level (and possibly programs can consume the data as per my below comment) but as aggregation doesn't happen within the CRDB codebase, why should the CRDB codebase create a term for it that isn't used in industry (as far as I know)?
___
*[pkg/util/metric/metric.proto, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67626#-MeeQCp3DZyvSO3wuo8W:-MeeQCp3DZyvSO3wuo8X:b-bllotu) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c02de10b2bcdc22e2f8cb62589d12c540847bdb/pkg/util/metric/metric.proto#L64)):*
> ```protobuf
> // for a metric. It is embedded within the metadata field for a
> // metric.
> message IndicatorInfo {
> ```

All this additional documentation seems useful to me and may also have the side effect of raising our quality bar around documentation of metrics, which would be a good thing.

But I have a Q: Is that how we are thinking about this stuff? Documentation? Or do we imagine programmatic consumption of this data? Do we have anything along those lines in mind that is somewhat concrete?

**Review by tbg — COMMENTED** [review]
Thanks Rima for getting the discussion started!

The scaffolding here looks fine. I just read the indicators doc again and it suggests starting with free-form text, but I'd like to suggest using prometheus aggregation rules syntax right off the bat (as strings), since that's ultimately the direction we're taking anyway and for which the approach must work (right?). This immediately gives us something we can do with them, which is deploy them to prometheus in some roachtests where we know they shouldn't fire. (This doesn't cover the more basic level of having some kind of unit testing that all defined indicators are even valid prometheus rules, for which we shouldn't rely on a roachtest, but this is just something to solve and not something to nudge us back to the free-text route).

+1 to Raphael's suggestion to provide a few examples. It would be useful to source something that our SREs actually use in prod, i.e. from https://github.com/cockroachlabs/managed-service/blob/master/pkg/kube/kubecreate/monitoring/assets/prometheus/common/alerts.cockroach.yml.

Something I'm noticing is that there are rules in there that involve more than one metric, for example here:

https://github.com/cockroachlabs/managed-service/blob/8b10e2a02195231f887db4015f3c20c485eda8a2/pkg/kube/kubecreate/monitoring/assets/prometheus/common/alerts.cockroach.yml#L84-L85

We'll need to decide if these are out of scope or in scope for now. If they're in scope, do we even want to attach aggregation rules directly to a metric, or do we perhaps want to define them separately but somehow stipulate that every metric should be considered for inclusion into an aggregation (by means of an opt-out pattern instead of opt-in)? This all tugs at the simple definition of "indicator := metric + aggregation rule" but if that simple world doesn't fit most of the time it's better to leave it early and say that an indicator is an aggregation rule over at least one, but possibly more than one metric, indicating something about the health of the system. I think I'd rather build for the general case right away, but it's a discussion that should be had.

How exactly should this information we're adding be used? The doc was somewhat vague about this. One goal that's top-of-mind for me is to ultimately (not necessarily to be reached right now) to be able to auto-generate not only decent prod-ready Grafana dashboards (i.e. automate https://github.com/cockroachdb/cockroach/pull/65964), but also basic alerting rules (which is where the "indicators" come in). This tightens the bond between what our SREs, our customers, and we internally care about and test and while everyone will certainly make some adjustments or add rules that don't apply elsewhere, it's a shared foundation. A prerequisite for that is that development work concerns itself more with feeding useful information to these outlets, i.e. this needs to be incentivized and made easy.

Another concept worth keeping in mind is multi-tenancy. We have some metrics families that are keyed on a tenantID (the mvccstats and rate limiter metrics, I think) so it's worth thinking about what our indicators guidance for such metrics would be (the default is likely just summing up over the tenant dimension). I don't know how many more of these we're going to pick up, but a quick sanity check that whatever we do can be made work with the existing tenant-aware metrics we do have is worth it.

And, for another thing to just keep in mind, even though we don't use them yet, [exemplars](https://vbehar.medium.com/using-prometheus-exemplars-to-jump-from-metrics-to-traces-in-grafana-249e721d4192) exist and are very interesting, and it might make sense, at least at some point in the future, to prompt our developers to think about whether they want to use exemplars to be for a new metric they're creating. The default use case for exemplars (see the previous link) is to allow navigation between metrics and traces that caused certain datapoints, which could be something we might want to do if we get always-on tracing to truly work. But we also will have some operations that are always-traced soon, namely bulk jobs. And we could also link metrics with statement fingerprints instead of traces. There is something here, and while the RFC at hand may not be the right place to do into great detail about these, it might be a good time to start thinking long-term about possible use cases of exemplars.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67626#-:-Mee7k7oD7wNVPUws0xE:b-wiib01)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @joshimhoff, @knz, and @rimadeodhar)

**Comment by joshimhoff** [comment]
Now I head further into RFC level convos... :)

> Something I'm noticing is that there are rules in there that involve more than one metric.

Yes. Also quite common, as an error rate is the rate of two cumulative metrics divided by each other.

> do we perhaps want to define them separately but somehow stipulate that every metric should be considered for inclusion into an aggregation (by means of an opt-out pattern instead of opt-in)?

We could express this in promQL as "aggregations". See https://github.com/cockroachlabs/managed-service/blob/master/pkg/kube/kubecreate/monitoring/assets/prometheus/common/aggregation.rules.yml. What do we gain by building our own format for expressing this, which we then would need to translate into promQL? This is def an RFC level Q :)

> One goal that's top-of-mind for me is to ultimately (not necessarily to be reached right now) to be able to auto-generate not only decent prod-ready Grafana dashboards (i.e. automate #65964), but also basic alerting rules (which is where the "indicators" come in). This tightens the bond between what our SREs, our customers, and we internally care about and test and while everyone will certainly make some adjustments or add rules that don't apply elsewhere, it's a shared foundation.

I like this goal. There are interesting ownership Qs to consider:

1. System owners such as SRE in CC case & customers in on-prem case ultimately own the alerting config and at least co-own the dashboarding. 
2. Devs have significant insight into what makes a good alert & dashboard.

Additionally the only good way I know to tune alerts is based on data from prod. So we need a fast feedback loop where devs or SREs can propose alerts, vetting em against prod data, then write the new definition to the shared source of truth.

> We have some metrics families that are keyed on a tenantID (the mvccstats and rate limiter metrics, I think) so it's worth thinking about what our indicators guidance for such metrics would be (the default is likely just summing up over the tenant dimension).

+1 that default seems sensible to me. Two cents: Tenant-specific alerting a problem for a year from now, if not more.

> The default use case for exemplars (see the previous link) is to allow navigation between metrics and traces that caused certain datapoints, which could be something we might want to do if we get always-on tracing to truly work.

Very cool.

**Review by rimadeodhar — COMMENTED** [review]
Thanks everyone! I think I have some really good pointers to keep in mind as I go about drafting the RFC which was the main goal of this prototype PR. I'm giving some high level responses to some of the things @tbg mentioned above, but would prefer to keep the more in depth discussions on the RFC PR. So please don't feel that you need to respond to this here as all these points will be covered in more detail in the RFC. But I'm adding it here for completeness of the discussion on this PR. 

> I just read the indicators doc again and it suggests starting with free-form text, but I'd like to suggest using prometheus aggregation rules syntax right off the bat (as strings), since that's ultimately the direction we're taking anyway and for which the approach must work

I think that seems fair. I was in favor of keeping it more free-form so that we don't begin by creating a structure that hampers flexibility going forward. But I think having *some* structure is probably important from the get go and prometheus aggregator rules syntax might be good way to have that.

> It would be useful to source something that our SREs actually use in prod, i.e. from https://github.com/cockroachlabs/managed-service/blob/master/pkg/kube/kubecreate/monitoring/assets/prometheus/common/alerts.cockroach.yml.

Nice! I will use these to drive my examples. My original intention was to add some examples here but I think it would be best to add them to the RFC and have further discussions there so that all in-depth context is retained in a single place.

> Something I'm noticing is that there are rules in there that involve more than one metric

This is a good callout and something I haven't fully thought through yet. But my initial inclination is to support a generic way to provide aggregation information including for metrics that make sense to be aggregated together. By that I mean, separate aggregation information from indicator info. As you mentioned, this will allow us to have the more flexible meaning for the term indicator as a meaningful aggregation over one or more metric that gives an insight into the health of the system. I like the idea of keeping the indicator info flexible from the get-go to make it more usable and extensible.

> How exactly should this information we're adding be used?

I think programmatic consumption is the eventual goal but the first step in that direction will be defining a framework to provide additional information (metadata) for the metric which will provide data on how to construct an indicator from the metric and exposing that information through an endpoint. What do we accomplish by this first step? To begin with, just basic documentation on individual metrics and how they should be used. The second goal is to create a culture where engineers truly have to think through how their metric will be used. It kind of forces an engineer adding a metric to really think what does this metric expose regarding the health of the system, how can I describe that as an indicator? If there is no good answer for that, then maybe the metric should be reconsidered or redefined. Or then explicitly be marked as a metric for temporary usage (such as , say, during the rollout of some feature) which will be deprecated soon enough.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67626#-:-MefFnscAZFnq4m6r2Lt:b-dkqqin)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @joshimhoff, @knz, and @tbg)

___
*[pkg/util/metric/metric.proto, line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67626#-MeeQy2H3rZj3CIi8MEK:-MefKcxTD0Gj7U6clr7P:b-lnfvep) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c02de10b2bcdc22e2f8cb62589d12c540847bdb/pkg/util/metric/metric.proto#L61)):*
<details><summary><i>Previously, joshimhoff (Josh Imhoff) wrote…</i></summary><blockquote>

WARNING naming bikeshed: What do we get by creating this term "indicator" for the result of applying an aggregation to a metric / some metrics? The API changes here are useful at a documentation level (and possibly programs can consume the data as per my below comment) but as aggregation doesn't happen within the CRDB codebase, why should the CRDB codebase create a term for it that isn't used in industry (as far as I know)?
</blockquote></details>

Good callout and a nice discussion to have on the RFC for sure. I would like to get more opinions on this as well. I'm going to copy this comment over to the RFC PR when I open it and get the discussion started there. I hope that seems reasonable.
___
*[pkg/util/metric/metric.proto, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67626#-MeeQCp3DZyvSO3wuo8W:-MefKvGr62slnisMH8kH:btshqq7) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c02de10b2bcdc22e2f8cb62589d12c540847bdb/pkg/util/metric/metric.proto#L64)):*
<details><summary><i>Previously, joshimhoff (Josh Imhoff) wrote…</i></summary><blockquote>

All this additional documentation seems useful to me and may also have the side effect of raising our quality bar around documentation of metrics, which would be a good thing.

But I have a Q: Is that how we are thinking about this stuff? Documentation? Or do we imagine programmatic consumption of this data? Do we have anything along those lines in mind that is somewhat concrete?
</blockquote></details>

I have alluded to this in my response to @tbg but the tl;dr; is that the initial goal is documentation but eventually we will want to extend it to support programmatic consumption either to drive dashboards or automated alerting. I don't have anything concrete to specify just yet but that would be a good exercise to have.

**Comment by joshimhoff** [comment]
Thanks, @rimadeodhar!

**Comment by tbg** [comment]
Thanks Rima! +1 to keeping the discussions on the upcoming RFC but I just
wanted to say that I agree with everything you said in your response, so I
think we're very much on the same page.
I talked to David (H) earlier today and we arrived at the conclusion that
the dashboard generation and the indicators project are fairly disjoint at
this point, but that they have a future "touchpoint" in the sense that we
might ultimately want to not only create a prometheus dashboard, but also
associated alerting rules (from the indicators). I think that's what you're
saying, too.

**Review by rimadeodhar — COMMENTED** [review]
Thanks @tbg for the response :). And I agree with your statement on indicators project being fairly disjoint atm but having future scope related to dashboards and alerting.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67626#-:-MegM7YG57hjb9Ey9EfC:b-qcl18a)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @joshimhoff, @knz, and @tbg)

**Comment by rimadeodhar** [comment]
The RFC PR is up https://github.com/cockroachdb/cockroach/pull/68082. Closing out this prototype PR. Once again, thanks everyone for the quick review and feedback on this.

**Pull request closed without merging**
