### PR TITLE
sql: final assault on planner.session

### PR DESCRIPTION
**Pull request by andreimatei**
See individual commits.

release note: none

### CODE REVIEW

**Comment by andreimatei** [comment]
Everything up to and including "sql,pgwire: rework the implementation of the Copy-in pgwire subprotocol" is another PR.

**Comment by knz** [comment]
Ok this is very nice work, but I'll need to review it in phases.
I think the first commit has already been merged, you can kill it from this PR.
The 2nd commit LGTM.

---

Reviewed 6 of 6 files at r1, 17 of 17 files at r2.
Review status: 15 of 49 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21486#-:-L303X-iQQFsjt5mnUKb:b-hls2ia)*

**Comment by knz** [comment]
3rd commit (COPY improvement) LGTM, with some nits. I do notice a significant trend upwards in the quality of your code comments. Thank you very very much for this.

Given the complete approach change I'd like to see a succeeding CI acceptance run for this 3rd commit though (currently red).

---

Reviewed 18 of 18 files at r3.
Review status: 29 of 49 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/copy.go, line 114 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21486#-L30BW5MJyy_0Se_E3_-:-L30BW5MJyy_0Se_E3_0:b-vpn2ry) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0ffc7041fa49d612d2c2b2c9abbaae38d40f97e/pkg/sql/copy.go#L114)):*
> ```Go
> }
> 
> //copyTxnOpt contains information about the transaction in which the copying
> ```

Spaces after `//`

---

*[pkg/sql/copy.go, line 150 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21486#-L30BfH52lIAR1PCsSDh:-L30BfH646EaDaBw3d4A:bjm3701) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0ffc7041fa49d612d2c2b2c9abbaae38d40f97e/pkg/sql/copy.go#L150)):*
> ```Go
> 			defer func() {
> 				if err := cleanup(); err != nil {
> 					if retErr == nil {
> ```

Don't drop `err` on the floor if `retErr != nil`. At least log it, and perhaps do something clever with `errors.Wrapf`.

---

*[pkg/sql/copy.go, line 178 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21486#-L30Bq8j2R1Y-vDHpYUj:-L30Bq8kD5L1PEAmjzB2:bn25zp3) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0ffc7041fa49d612d2c2b2c9abbaae38d40f97e/pkg/sql/copy.go#L178)):*
> ```Go
> 				return false, nil
> 			case pgwirebase.ClientMsgCopyFail:
> 				return false, fmt.Errorf("client canceled COPY")
> ```

pgerrors.NewErrorf. Also I think I recall a pgerror code for this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21486#-:-L30CMp1r9zPo3cp9kov:b-k0ggi2)*

**Comment by knz** [comment]
r4 LGTM
r5 LGTM, but there's a typo in the commit message: structer -> struct. Did you measure?

In general I'd like to see a before/after benchmark comparison on the entire PR.

---

Reviewed 2 of 2 files at r4, 3 of 3 files at r5.
Review status: 32 of 49 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21486#-:-L30Cu4f0TArAjULL1kl:b-4a3jvp)*

**Comment by knz** [comment]
r6 LGTM
r7 conceptually and quality LGTM, but it makes me wonder even more about benchmarking. There's a bit much indirection in there.

---

Reviewed 1 of 1 files at r6, 7 of 7 files at r7.
Review status: 35 of 49 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21486#-:-L30DOCihJ5YRrBp4w7v:b-9t212e)*

**Comment by knz** [comment]
r8 code LGTM, but I don't understand the commit message. Please reword.

---

Reviewed 2 of 2 files at r8.
Review status: 36 of 49 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21486#-:-L30DfFlLGZZFv8eb8Iw:b4fg50w)*

**Comment by knz** [comment]
Last commit LGTM, modulo resolution of the open issue in opt_interface.go. 
I love the new interface, very good choice.

All in all this is a very neat patch set. I hope we get it to merge soon.

---

Reviewed 13 of 13 files at r9.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/executor_opt_interface.go, line 30 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/21486#-L30E6TRk-zrIpopSP34:-L30E6TRk-zrIpopSP35:b8e8z4d) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c2782cda872d13dbcd820d68fb11e3dc8bc2675/pkg/sql/executor_opt_interface.go#L30)):*
> ```Go
> func (e *Executor) NewExecFactory() opt.ExecFactory {
> 	txn := client.NewTxn(e.cfg.DB, e.cfg.NodeID.Get())
> 	// TODO(andrei): figure out when to do the cleanup. #21482.
> ```

I do not understand this TODO, it looks like a FIXME before this last commit can merge. Can you figure this out together with @RaduBerinde?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21486#-:-L30ELSMwJAvUY4GHq4D:b-uycnmc)*

**Comment by knz** [comment]
Also I'd like to have a cursory look at the PR again after you rebase.

**Comment by andreimatei** [comment]
Fixed the commit messages and reworded r8, although it's pretty much the same. Not sure what's not clear :)

no change in benchmarks

```
name                                             old time/op    new time/op    delta
SQL/Cockroach/Delete/count=1-8                      353µs ± 2%     368µs ± 1%   ~     (p=0.100 n=3+3)
SQL/Cockroach/Delete/count=10-8                     642µs ± 1%     622µs ± 0%   ~     (p=0.100 n=3+3)
SQL/Cockroach/Delete/count=100-8                   2.76ms ± 2%    2.74ms ± 1%   ~     (p=0.700 n=3+3)
SQL/Cockroach/Delete/count=1000-8                  31.9ms ± 4%    30.8ms ± 1%   ~     (p=0.100 n=3+3)
SQL/Cockroach/Insert/count=1-8                      624µs ±11%     634µs ± 7%   ~     (p=1.000 n=3+3)
SQL/Cockroach/Insert/count=10-8                    1.44ms ±30%    1.41ms ±21%   ~     (p=1.000 n=3+3)
SQL/Cockroach/Insert/count=100-8                   5.14ms ±10%    5.44ms ±14%   ~     (p=0.700 n=3+3)
SQL/Cockroach/Insert/count=1000-8                  64.9ms ± 4%    60.8ms ± 6%   ~     (p=0.400 n=3+3)
SQL/Cockroach/InsertDistinct/count=1-8             3.79ms ± 3%    3.66ms ± 3%   ~     (p=0.200 n=3+3)
SQL/Cockroach/InsertDistinct/count=10-8            1.58ms ± 9%    1.40ms ± 6%   ~     (p=0.200 n=3+3)
SQL/Cockroach/InsertDistinct/count=100-8           2.27ms ± 6%    2.14ms ± 5%   ~     (p=0.400 n=3+3)
SQL/Cockroach/InsertFK/count=1/nFks=1-8             480µs ±13%     466µs ± 9%   ~     (p=1.000 n=3+3)
SQL/Cockroach/InsertFK/count=1/nFks=5-8             732µs ± 3%     723µs ± 2%   ~     (p=0.700 n=3+3)
SQL/Cockroach/InsertFK/count=1/nFks=10-8           1.24ms ± 4%    1.09ms ± 3%   ~     (p=0.100 n=3+3)
SQL/Cockroach/InsertFK/count=10/nFks=1-8           1.62ms ± 3%    1.46ms ± 6%   ~     (p=0.100 n=3+3)
SQL/Cockroach/InsertFK/count=10/nFks=5-8           4.85ms ± 3%    4.78ms ± 8%   ~     (p=1.000 n=3+3)
SQL/Cockroach/InsertFK/count=10/nFks=10-8          7.52ms ± 5%    7.27ms ± 3%   ~     (p=0.400 n=3+3)
SQL/Cockroach/InsertFK/count=100/nFks=1-8          12.0ms ± 5%    12.2ms ± 8%   ~     (p=1.000 n=3+3)
SQL/Cockroach/InsertFK/count=100/nFks=5-8          42.1ms ± 8%    42.3ms ± 7%   ~     (p=1.000 n=3+3)
SQL/Cockroach/InsertFK/count=100/nFks=10-8         74.4ms ±24%    64.9ms ± 6%   ~     (p=0.400 n=3+3)
SQL/Cockroach/InsertFK/count=1000/nFks=1-8          113ms ±10%     124ms ± 6%   ~     (p=0.200 n=3+3)
SQL/Cockroach/InsertFK/count=1000/nFks=5-8          443ms ±16%     410ms ±11%   ~     (p=0.700 n=3+3)
SQL/Cockroach/InsertFK/count=1000/nFks=10-8         726ms ± 5%     711ms ± 5%   ~     (p=0.700 n=3+3)
SQL/Cockroach/InsertSecondaryIndex/count=1-8        628µs ± 2%     638µs ± 3%   ~     (p=0.400 n=3+3)
SQL/Cockroach/InsertSecondaryIndex/count=10-8      5.00ms ± 6%    4.76ms ±10%   ~     (p=0.400 n=3+3)
SQL/Cockroach/InsertSecondaryIndex/count=100-8     47.2ms ± 9%    45.9ms ± 6%   ~     (p=1.000 n=3+3)
SQL/Cockroach/InsertSecondaryIndex/count=1000-8     470ms ± 4%     470ms ± 1%   ~     (p=1.000 n=3+3)
SQL/Cockroach/InterleavedSelect/count=1-8           287µs ± 1%     283µs ± 1%   ~     (p=0.200 n=3+3)
SQL/Cockroach/InterleavedSelect/count=10-8          299µs ± 1%     299µs ± 0%   ~     (p=1.000 n=3+3)
SQL/Cockroach/InterleavedSelect/count=100-8         422µs ± 1%     428µs ± 3%   ~     (p=0.700 n=3+3)
SQL/Cockroach/InterleavedSelect/count=1000-8       1.62ms ± 7%    1.56ms ± 1%   ~     (p=0.400 n=3+3)
SQL/Cockroach/TrackChoices/count=1-8                401µs ± 5%     374µs ± 4%   ~     (p=0.200 n=3+3)
SQL/Cockroach/TrackChoices/count=10-8               163µs ± 7%     164µs ±16%   ~     (p=1.000 n=3+3)
SQL/Cockroach/TrackChoices/count=100-8              156µs ± 1%     158µs ± 1%   ~     (p=0.200 n=3+3)
SQL/Cockroach/TrackChoices/count=1000-8             147µs ± 2%     142µs ± 2%   ~     (p=0.200 n=3+3)
SQL/Cockroach/Update/count=1-8                      396µs ± 4%     384µs ± 2%   ~     (p=0.200 n=3+3)
SQL/Cockroach/Update/count=10-8                     921µs ±56%     659µs ± 6%   ~     (p=0.700 n=3+3)
SQL/Cockroach/Update/count=100-8                   2.66ms ± 2%    2.63ms ± 3%   ~     (p=1.000 n=3+3)
SQL/Cockroach/Update/count=1000-8                  22.0ms ± 6%    21.6ms ± 2%   ~     (p=1.000 n=3+3)
SQL/Cockroach/Upsert/count=1-8                     1.31ms ±10%    1.22ms ±13%   ~     (p=0.400 n=3+3)
SQL/Cockroach/Upsert/count=10-8                    2.80ms ± 2%    2.78ms ± 2%   ~     (p=1.000 n=3+3)
SQL/Cockroach/Upsert/count=100-8                  8.40ms ±128%   18.28ms ± 1%   ~     (p=0.700 n=3+3)
SQL/Cockroach/Upsert/count=1000-8                  21.1ms ± 1%    22.4ms ± 2%   ~     (p=0.100 n=3+3)

name                                             old alloc/op   new alloc/op   delta
SQL/Cockroach/Delete/count=1-8                     50.8kB ± 0%    51.0kB ± 0%   ~     (p=0.100 n=3+3)
SQL/Cockroach/Delete/count=10-8                     113kB ± 0%     113kB ± 0%   ~     (p=1.000 n=3+3)
SQL/Cockroach/Delete/count=100-8                    715kB ± 0%     715kB ± 1%   ~     (p=1.000 n=3+3)
SQL/Cockroach/Delete/count=1000-8                  6.52MB ± 1%    6.50MB ± 1%   ~     (p=1.000 n=3+3)
SQL/Cockroach/Insert/count=1-8                     38.7kB ± 4%    38.5kB ± 3%   ~     (p=1.000 n=3+3)
SQL/Cockroach/Insert/count=10-8                    89.3kB ± 2%    90.6kB ± 3%   ~     (p=0.700 n=3+3)
SQL/Cockroach/Insert/count=100-8                    591kB ± 2%     579kB ± 0%   ~     (p=0.100 n=3+3)
SQL/Cockroach/Insert/count=1000-8                  5.26MB ± 0%    5.38MB ± 5%   ~     (p=1.000 n=3+3)
SQL/Cockroach/InsertDistinct/count=1-8              362kB ± 1%     360kB ± 0%   ~     (p=0.700 n=3+3)
SQL/Cockroach/InsertDistinct/count=10-8             373kB ± 0%     374kB ± 1%   ~     (p=1.000 n=3+3)
SQL/Cockroach/InsertDistinct/count=100-8            425kB ± 1%     423kB ± 1%   ~     (p=1.000 n=3+3)
SQL/Cockroach/InsertFK/count=1/nFks=1-8            51.6kB ± 1%    52.5kB ± 3%   ~     (p=0.400 n=3+3)
SQL/Cockroach/InsertFK/count=1/nFks=5-8             119kB ± 4%     120kB ± 2%   ~     (p=0.700 n=3+3)
SQL/Cockroach/InsertFK/count=1/nFks=10-8            215kB ± 8%     223kB ±10%   ~     (p=0.700 n=3+3)
SQL/Cockroach/InsertFK/count=10/nFks=1-8            261kB ±25%     233kB ±12%   ~     (p=0.700 n=3+3)
SQL/Cockroach/InsertFK/count=10/nFks=5-8            800kB ± 6%     763kB ±11%   ~     (p=0.400 n=3+3)
SQL/Cockroach/InsertFK/count=10/nFks=10-8          1.67MB ±22%    1.53MB ±12%   ~     (p=1.000 n=3+3)
SQL/Cockroach/InsertFK/count=100/nFks=1-8          1.93MB ±14%    2.09MB ±28%   ~     (p=1.000 n=3+3)
SQL/Cockroach/InsertFK/count=100/nFks=5-8          7.45MB ±12%    8.96MB ±21%   ~     (p=0.200 n=3+3)
SQL/Cockroach/InsertFK/count=100/nFks=10-8         19.9MB ± 3%    15.3MB ±13%   ~     (p=0.100 n=3+3)
SQL/Cockroach/InsertFK/count=1000/nFks=1-8         20.9MB ±14%    19.3MB ±14%   ~     (p=0.400 n=3+3)
SQL/Cockroach/InsertFK/count=1000/nFks=5-8         85.9MB ±11%    76.5MB ± 0%   ~     (p=0.700 n=3+3)
SQL/Cockroach/InsertFK/count=1000/nFks=10-8         156MB ±10%     154MB ± 0%   ~     (p=0.700 n=3+3)
SQL/Cockroach/InsertSecondaryIndex/count=1-8        102kB ± 1%     126kB ±19%   ~     (p=0.200 n=3+3)
SQL/Cockroach/InsertSecondaryIndex/count=10-8       607kB ± 4%     594kB ± 1%   ~     (p=0.700 n=3+3)
SQL/Cockroach/InsertSecondaryIndex/count=100-8     6.34MB ± 3%    6.35MB ± 2%   ~     (p=1.000 n=3+3)
SQL/Cockroach/InsertSecondaryIndex/count=1000-8    71.0MB ± 3%    70.6MB ± 1%   ~     (p=1.000 n=3+3)
SQL/Cockroach/InterleavedSelect/count=1-8          48.2kB ± 0%    48.7kB ± 1%   ~     (p=0.200 n=3+3)
SQL/Cockroach/InterleavedSelect/count=10-8         52.5kB ± 4%    53.4kB ± 4%   ~     (p=0.400 n=3+3)
SQL/Cockroach/InterleavedSelect/count=100-8        89.0kB ± 7%    87.2kB ± 2%   ~     (p=1.000 n=3+3)
SQL/Cockroach/InterleavedSelect/count=1000-8        426kB ± 3%     417kB ± 7%   ~     (p=0.700 n=3+3)
SQL/Cockroach/TrackChoices/count=1-8               64.3kB ±22%    63.8kB ±15%   ~     (p=1.000 n=3+3)
SQL/Cockroach/TrackChoices/count=10-8              19.3kB ± 5%    23.8kB ±26%   ~     (p=0.400 n=3+3)
SQL/Cockroach/TrackChoices/count=100-8             19.2kB ±13%    18.7kB ± 6%   ~     (p=1.000 n=3+3)
SQL/Cockroach/TrackChoices/count=1000-8            19.2kB ± 0%    19.3kB ± 1%   ~     (p=0.200 n=3+3)
SQL/Cockroach/Update/count=1-8                     55.3kB ± 1%    56.3kB ± 2%   ~     (p=0.100 n=3+3)
SQL/Cockroach/Update/count=10-8                     123kB ± 2%     122kB ± 0%   ~     (p=1.000 n=3+3)
SQL/Cockroach/Update/count=100-8                    766kB ± 0%     771kB ± 2%   ~     (p=0.700 n=3+3)
SQL/Cockroach/Update/count=1000-8                  6.61MB ± 1%    6.59MB ± 0%   ~     (p=1.000 n=3+3)
SQL/Cockroach/Upsert/count=1-8                      120kB ± 6%     121kB ± 5%   ~     (p=0.700 n=3+3)
SQL/Cockroach/Upsert/count=10-8                     168kB ± 1%     169kB ± 2%   ~     (p=0.700 n=3+3)
SQL/Cockroach/Upsert/count=100-8                    778kB ± 4%     805kB ± 1%   ~     (p=0.400 n=3+3)
SQL/Cockroach/Upsert/count=1000-8                  6.76MB ± 2%    6.66MB ± 1%   ~     (p=0.100 n=3+3)

name                                             old allocs/op  new allocs/op  delta
SQL/Cockroach/Delete/count=1-8                        452 ± 1%       453 ± 1%   ~     (p=0.600 n=3+3)
SQL/Cockroach/Delete/count=10-8                       781 ± 7%       764 ± 2%   ~     (p=1.000 n=3+3)
SQL/Cockroach/Delete/count=100-8                    3.70k ± 7%     3.81k ±10%   ~     (p=0.700 n=3+3)
SQL/Cockroach/Delete/count=1000-8                   37.1k ±16%     34.6k ±17%   ~     (p=1.000 n=3+3)
SQL/Cockroach/Insert/count=1-8                        370 ±40%       400 ±30%   ~     (p=0.700 n=3+3)
SQL/Cockroach/Insert/count=10-8                       578 ±21%       696 ±38%   ~     (p=0.400 n=3+3)
SQL/Cockroach/Insert/count=100-8                    3.06k ±30%     2.49k ± 1%   ~     (p=0.100 n=3+3)
SQL/Cockroach/Insert/count=1000-8                   23.3k ± 1%     25.9k ±21%   ~     (p=1.000 n=3+3)
SQL/Cockroach/InsertDistinct/count=1-8              2.46k ±12%     2.27k ± 4%   ~     (p=0.700 n=3+3)
SQL/Cockroach/InsertDistinct/count=10-8             2.40k ± 4%     2.39k ± 4%   ~     (p=1.000 n=3+3)
SQL/Cockroach/InsertDistinct/count=100-8            2.96k ± 7%     2.85k ± 8%   ~     (p=1.000 n=3+3)
SQL/Cockroach/InsertFK/count=1/nFks=1-8               424 ± 3%       470 ±19%   ~     (p=0.400 n=3+3)
SQL/Cockroach/InsertFK/count=1/nFks=5-8               906 ± 8%       964 ± 5%   ~     (p=0.400 n=3+3)
SQL/Cockroach/InsertFK/count=1/nFks=10-8            1.68k ±12%     1.82k ±27%   ~     (p=1.000 n=3+3)
SQL/Cockroach/InsertFK/count=10/nFks=1-8            2.19k ±35%     1.85k ±18%   ~     (p=0.700 n=3+3)
SQL/Cockroach/InsertFK/count=10/nFks=5-8            6.40k ±12%     5.86k ±16%   ~     (p=0.400 n=3+3)
SQL/Cockroach/InsertFK/count=10/nFks=10-8           13.4k ±34%     11.5k ±18%   ~     (p=0.700 n=3+3)
SQL/Cockroach/InsertFK/count=100/nFks=1-8           14.1k ±23%     16.1k ±43%   ~     (p=0.700 n=3+3)
SQL/Cockroach/InsertFK/count=100/nFks=5-8           53.4k ±20%     70.1k ±32%   ~     (p=0.700 n=3+3)
SQL/Cockroach/InsertFK/count=100/nFks=10-8           167k ± 4%      112k ±21%   ~     (p=0.100 n=3+3)
SQL/Cockroach/InsertFK/count=1000/nFks=1-8           158k ±21%      140k ±23%   ~     (p=0.400 n=3+3)
SQL/Cockroach/InsertFK/count=1000/nFks=5-8           612k ±20%      494k ± 2%   ~     (p=0.400 n=3+3)
SQL/Cockroach/InsertFK/count=1000/nFks=10-8         1.06M ±21%     1.03M ± 3%   ~     (p=0.700 n=3+3)
SQL/Cockroach/InsertSecondaryIndex/count=1-8          511 ± 3%       786 ±36%   ~     (p=0.200 n=3+3)
SQL/Cockroach/InsertSecondaryIndex/count=10-8       2.48k ±16%     2.35k ± 8%   ~     (p=1.000 n=3+3)
SQL/Cockroach/InsertSecondaryIndex/count=100-8      20.5k ± 5%     24.1k ±12%   ~     (p=0.200 n=3+3)
SQL/Cockroach/InsertSecondaryIndex/count=1000-8      210k ± 5%      236k ±13%   ~     (p=0.200 n=3+3)
SQL/Cockroach/InterleavedSelect/count=1-8             535 ± 1%       535 ± 1%   ~     (p=1.000 n=3+3)
SQL/Cockroach/InterleavedSelect/count=10-8            606 ± 5%       603 ± 3%   ~     (p=1.000 n=3+3)
SQL/Cockroach/InterleavedSelect/count=100-8         1.08k ± 7%     1.09k ± 5%   ~     (p=1.000 n=3+3)
SQL/Cockroach/InterleavedSelect/count=1000-8        5.86k ± 3%     5.73k ± 6%   ~     (p=0.700 n=3+3)
SQL/Cockroach/TrackChoices/count=1-8                  527 ±27%       507 ±21%   ~     (p=1.000 n=3+3)
SQL/Cockroach/TrackChoices/count=10-8                 119 ±11%       173 ±46%   ~     (p=0.400 n=3+3)
SQL/Cockroach/TrackChoices/count=100-8               97.0 ±30%      92.0 ±14%   ~     (p=0.800 n=3+3)
SQL/Cockroach/TrackChoices/count=1000-8              82.3 ± 8%      84.7 ± 7%   ~     (p=0.700 n=3+3)
SQL/Cockroach/Update/count=1-8                        545 ± 3%       546 ± 3%   ~     (p=1.000 n=3+3)
SQL/Cockroach/Update/count=10-8                       912 ± 3%       889 ± 0%   ~     (p=0.600 n=3+3)
SQL/Cockroach/Update/count=100-8                    4.20k ± 2%     4.28k ± 3%   ~     (p=0.700 n=3+3)
SQL/Cockroach/Update/count=1000-8                   35.5k ± 1%     36.2k ± 4%   ~     (p=0.400 n=3+3)
SQL/Cockroach/Upsert/count=1-8                      1.07k ±11%     1.09k ± 7%   ~     (p=0.600 n=3+3)
SQL/Cockroach/Upsert/count=10-8                     1.62k ±10%     1.71k ±11%   ~     (p=0.400 n=3+3)
SQL/Cockroach/Upsert/count=100-8                    6.87k ± 4%     7.15k ± 0%   ~     (p=0.400 n=3+3)
SQL/Cockroach/Upsert/count=1000-8                   59.0k ± 2%     56.9k ± 2%   ~     (p=0.200 n=3+3)
```

---

Review status: 14 of 50 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/sql/copy.go, line 114 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21486#-L30BW5MJyy_0Se_E3_-:-L34fipuKNvngeUPed5g:bzbnmst) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0ffc7041fa49d612d2c2b2c9abbaae38d40f97e/pkg/sql/copy.go#L114)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Spaces after `//`
</blockquote></details>

done.

Please comment on #21408 for this commit

---

*[pkg/sql/copy.go, line 150 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21486#-L30BfH52lIAR1PCsSDh:-L34fzy-V8tlFEKkT2D4:biuxgja) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0ffc7041fa49d612d2c2b2c9abbaae38d40f97e/pkg/sql/copy.go#L150)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Don't drop `err` on the floor if `retErr != nil`. At least log it, and perhaps do something clever with `errors.Wrapf`.
</blockquote></details>

this doesn't apply any more

---

*[pkg/sql/copy.go, line 178 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21486#-L30Bq8j2R1Y-vDHpYUj:-L34g8218ehCKYyJkO9F:b-6axyt6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0ffc7041fa49d612d2c2b2c9abbaae38d40f97e/pkg/sql/copy.go#L178)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

pgerrors.NewErrorf. Also I think I recall a pgerror code for this.
</blockquote></details>

well what code should I use? This is keeping the previous code.

---

*[pkg/sql/executor_opt_interface.go, line 30 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/21486#-L30E6TRk-zrIpopSP34:-L34i0arnsgZF2lksRA_:begpik5) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c2782cda872d13dbcd820d68fb11e3dc8bc2675/pkg/sql/executor_opt_interface.go#L30)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I do not understand this TODO, it looks like a FIXME before this last commit can merge. Can you figure this out together with @RaduBerinde?
</blockquote></details>

well I wasn't making anything worse than it was.
But I've fixed it now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21486#-:-L34tFpIp1ycWaFyPxC6:bkpga9k)*

**Comment by andreimatei** [comment]
Rafa, good to go?

---

Review status: 0 of 22 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21486#-:-L3C-h9mpFmAJeYGJBHL:b-vg6x66)*

**Comment by knz** [comment]
All good. Thanks, and nice work.

---

Reviewed 1 of 23 files at r10, 2 of 3 files at r11, 1 of 1 files at r12, 2 of 7 files at r13, 1 of 2 files at r14, 15 of 15 files at r15.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/copy.go, line 178 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21486#-L30Bq8j2R1Y-vDHpYUj:-L3Dxg4N1W-D4m3a4CY9:brqava5) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0ffc7041fa49d612d2c2b2c9abbaae38d40f97e/pkg/sql/copy.go#L178)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

well what code should I use? This is keeping the previous code.
</blockquote></details>

We'll have a later run of replacements then. For now this will do.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21486#-:-L3Dxzl0AWLdV8NPc8ee:bk26eyb)*

**Pull request merged**
