### PR TITLE
sql: increase the syntax compatibility of CREATE DATABASE with pg.

### LINKED ISSUE #10734: sql: support the pg extended syntax for CREATE DATABASE
Reported in #5582:
```
ERROR:  syntax error at or near "TEMPLATE"
CREATE DATABASE postgrex_test TEMPLATE=template0 ENCODING='UTF8' LC_COLLATE='en_US.UTF-8' LC_CTYPE='en_US.UTF-8';
```

1) Although we do not support the TEMPLATE parameter, in the particular case where the argument is `template0` we can ignore it, as it simply indicates to create a "blank" database. (`template0` is pg's empty database, clients typically use it explicitly because pg also allows configuration to override the default used when no template is specified)

2) ENCODING, LC_COLLATE and LC_CTYPE can be checked for correctness (assert that their values are compatible with the current CockroachDB code, which is the case here) an then safely ignored.

So to address this issue we can simply accept the extended syntax, do some sanity check on it and then process it as a regular `CREATE DATABASE`.

### PR DESCRIPTION
**Pull request by knz**
This patch introduce preliminary support for additional parameters to
CREATE DATABASE: TEMPLATE, LC_COLLATE and LC_CTYPE. The parameters
are now accepted and their value is checked to be compatible with
CockroachDB's behavior.

Currently the implementation supports them in the specific order they
are documented by pg: TEMPLATE then ENCODING then LC_COLLATE then
LC_CTYPE. A subsequent implementation, should this be required by
clients, could accept them in any order.

Fixes #10734.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10775)

### CODE REVIEW

**Comment by knz** [comment]
cc @tlvenn

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/testdata/database, line 60 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10775#-KWok-lF_CghOrA7vWhR:-KWok-lGISOfouY4ScGb:b-ql4uj9) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ec76f9bd63195dbce8bda9a3090ec3e5f3f8eb2/pkg/sql/testdata/database#L60)):*
> ```
> 
> statement ok
> CREATE DATABASE b5 TEMPLATE=template0 ENCODING='UTF8' LC_COLLATE='en_US.UTF-8' LC_CTYPE='en_US.UTF-8'
> ```

Maybe add `WITH` to this one so that path gets tested too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10775#-:-KWol4KW82Xn01mj_320:bnfp4nl)*

**Comment by bdarnell** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/create.go, line 80 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10775#-KWpt7IwBYq3iqaHfGBj:-KWpt7IwBYq3iqaHfGBk:b-xvm9ao) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ec76f9bd63195dbce8bda9a3090ec3e5f3f8eb2/pkg/sql/create.go#L80)):*
> ```Go
> 		collateStr := string(*collate.(*parser.DString))
> 		// We only support C and en_US.UTF-8.
> 		if collateStr != "C" && collateStr != "en_US.UTF-8" {
> ```

Per my comment on #10734, `C` and `en_US` are different (at least when used as a collation; I don't know what effect it has in LC_CTYPE)  and we only support `C` (and `C.UTF-8`) at this time. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10775)*

**Comment by knz** [comment]
TFYRs

---

Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/create.go, line 80 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10775#-KWpt7IwBYq3iqaHfGBj:-KWqExPyrYzu8SkAAH_h:b-x52gbo) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ec76f9bd63195dbce8bda9a3090ec3e5f3f8eb2/pkg/sql/create.go#L80)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Per my comment on #10734, `C` and `en_US` are different (at least when used as a collation; I don't know what effect it has in LC_CTYPE)  and we only support `C` (and `C.UTF-8`) at this time. 
</details>
Thanks, fixed.

---

*[pkg/sql/testdata/database, line 60 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10775#-KWok-lF_CghOrA7vWhR:-KWqEzhnex1oKfcBel_L:blw1b5h) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ec76f9bd63195dbce8bda9a3090ec3e5f3f8eb2/pkg/sql/testdata/database#L60)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> Maybe add `WITH` to this one so that path gets tested too.
</details>
Done. (as parser test)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10775#-:-KWqF3Dq9NHkfuSXu993:b-814cgt)*

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10775#-:-KWseZRPhMgu0aTHDKYa:bnfp4nl)*

**Pull request merged**
