### PR TITLE
distsql: move protos to distsqlpb from distsqlrun

### PR DESCRIPTION
**Pull request by jordanlewis**
This creates a new package, distsqlpb, that contains the distsql API
protobufs, generated files, and support methods.

The new package permits other packages to depend on distsql protobufs
without having to depend on the distsql runtime.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Ha, what timing, I was just updating the proto deps which required various changes :)

LGTM other than the test failures

This change was all mechanic, correct? Can you put the fixes you make in a separate commit for easy review? Thanks!

**Comment by jordanlewis** [comment]
Yes, all mechanical. The test failures were all missing find-and-replace issues, no real fixes were necessary - I had forgotten to move a test file to the new package, had forgotten to rename a string used in a trace test that contains the proto namespace, and had forgotten to add a comment to a newly exported function.

**Comment by jordanlewis** [comment]
Now TestVet is failing due to "unkeyed composite structs" - I guess this check is disabled for structs that live in the same package? This seems like a huge waste of time, but I guess I'll go in and add the field names everywhere. It's too bad that TestVet doesn't give a diff.

**Review by RaduBerinde — APPROVED** [review]
Nice! Regarding the lint failures - not sure why they suddenly showed up here, but I had to fix these when updating proto deps. That change is not done yet but maybe you can use the diffs to save on some work: https://github.com/RaduBerinde/cockroach/tree/update-proto

**Comment by jordanlewis** [comment]
All set now. TFTR!

bors r+

**Pull request merged**
