### PR TITLE
sql: validate check constraints with the schema changer

### PR DESCRIPTION
**Pull request by thoszhang**
Currently, constraints are added in the `Unvalidated` state, and are not
validated for existing rows until ALTER TABLE ... VALIDATE CONSTRAINT is run.
With this change, check constraints will be validated asynchronously after they
are added by default (and similar changes to FKs are to follow). This addresses
the problematic long-running transactions caused by the current implementation
of VALIDATE CONSTRAINT. This PR is a rework of #32504 and has the same tests.

With this change, check constraints will be added to the table descriptor in
the new `Validating` state, visible to CRUD operations, and a mutation is
queued indicating that the constraint is to be validated. During the backfill
step, the constraint is validated for existing rows. If validation succeeds,
then the constraint moves to the `Validated` state; otherwise, it is dropped.

The behavior when dropping constraints (either via DROP CONSTRAINT or
indirectly when a column is dropped) is unchanged: no mutation is enqueued.

As part of this change, check constraints can be added to non-public columns in
the process of being added, including columns that were created earlier in the
same transaction.

The main difference between this PR and #32504 is that #32504 does not add the
constraint to the table descriptor until it has been validated.

See #34238 for more context.

Release note (sql change): Check constraint adds by default will validate table
data with the added constraint asynchronously after the transaction commits.

### CODE REVIEW

**Review by vivekmenezes — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @lucy-zhang, and @vivekmenezes)

___
*[pkg/sql/alter_table.go, line 217 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34301#-LXPTs1i5yLtOdpXy9hg:-LXPTs1i5yLtOdpXy9hh:b-x0ppws) ([raw file](https://github.com/cockroachdb/cockroach/blob/938fb995ecd46e99a6795252abea4ae7d469f998/pkg/sql/alter_table.go#L217)):*
> ```Go
> 				// A previous command could have added a column which the new constraint uses,
> 				// allocate IDs now.
> 				if err != n.tableDesc.AllocateIDs() {
> ```

This seems out of place. Does something break without it?
___
*[pkg/sql/backfill.go, line 601 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34301#-LXPVRtY7drzzjsyf4xc:-LXPVRtY7drzzjsyf4xd:b-x7bvwc) ([raw file](https://github.com/cockroachdb/cockroach/blob/938fb995ecd46e99a6795252abea4ae7d469f998/pkg/sql/backfill.go#L601)):*
> ```Go
> 					return err
> 				}
> 				doneCheckValidation = true
> ```

What if there are two columns with two check constraints?
___
*[pkg/sql/backfill.go, line 624 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34301#-LXPVazZACGafUXp2Jq7:-LXPVazZACGafUXp2Jq8:b-f4y3xz) ([raw file](https://github.com/cockroachdb/cockroach/blob/938fb995ecd46e99a6795252abea4ae7d469f998/pkg/sql/backfill.go#L624)):*
> ```Go
> 
> 			case *sqlbase.DescriptorMutation_Constraint:
> 				return errors.Errorf("constraint validation mutation cannot be in the DROP state within the same transaction: %+v", m)
> ```

How about BEGIN; ALTER ADD COLUMN a INT CHECK a < 1; ALTER DROP COLUMN a; COMMIT ?
___
*[pkg/sql/create_table.go, line 1488 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34301#-LXPWFnz8OPv3jqkyHWm:-LXPWFnz8OPv3jqkyHWn:bof5wou) ([raw file](https://github.com/cockroachdb/cockroach/blob/938fb995ecd46e99a6795252abea4ae7d469f998/pkg/sql/create_table.go#L1488)):*
> ```Go
> 
> 		col, dropped, err := desc.FindColumnByName(c.ColumnName)
> 		if err != nil || dropped {
> ```

Why do you need this change?
___
*[pkg/sql/schema_changer.go, line 1160 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34301#-LXPWo699YOmD1Gwx05r:-LXPWo699YOmD1Gwx05s:b-ctivrp) ([raw file](https://github.com/cockroachdb/cockroach/blob/938fb995ecd46e99a6795252abea4ae7d469f998/pkg/sql/schema_changer.go#L1160)):*
> ```Go
> 					}
> 				}
> 			}
> ```

Do you think you can add this logic to sc.deleteIndexMutationsWithReversedColumns() and rename that to sc.DeleteDependentMutationsWithReversedColumns() ?
___
*[pkg/sql/schema_changer.go, line 1838 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34301#-LXPX7l76WHsNKV9i_Mi:-LXPX7l76WHsNKV9i_Mj:b-234bed) ([raw file](https://github.com/cockroachdb/cockroach/blob/938fb995ecd46e99a6795252abea4ae7d469f998/pkg/sql/schema_changer.go#L1838)):*
> ```Go
> 			Location: dummyLocation,
> 		},
> 		User: security.NodeUser,
> ```

I don't believe you need this because you are using the backfiller and not the internal executor
___
*[pkg/sql/backfill/backfill.go, line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34301#-LXPXoq_30IYVvJGME9h:-LXPXoq_30IYVvJGME9i:b-3q3cir) ([raw file](https://github.com/cockroachdb/cockroach/blob/938fb995ecd46e99a6795252abea4ae7d469f998/pkg/sql/backfill/backfill.go#L84)):*
> ```Go
> 	cb.evalCtx = evalCtx
> 	numCols := len(desc.Columns)
> 	cb.cols = desc.Columns
> ```

Does desc.WritableColumns() work here?
___
*[pkg/sql/distsqlrun/checkbackfiller.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34301#-LXPYbj58dhMZbzJqKUS:-LXPYbj58dhMZbzJqKUT:bnmy55m) ([raw file](https://github.com/cockroachdb/cockroach/blob/938fb995ecd46e99a6795252abea4ae7d469f998/pkg/sql/distsqlrun/checkbackfiller.go#L28)):*
> ```Go
> )
> 
> // indexBackfiller is a processor that backfills new indexes.
> ```

checkBackfiller
___
*[pkg/sql/sqlbase/structured.go, line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34301#-LXP_9NH0m88a0-KUjtd:-LXP_9NH0m88a0-KUjte:bg5g68f) ([raw file](https://github.com/cockroachdb/cockroach/blob/938fb995ecd46e99a6795252abea4ae7d469f998/pkg/sql/sqlbase/structured.go#L252)):*
> ```Go
> 	}
> 
> 	checks := make([]TableDescriptor_CheckConstraint, len(tbl.Checks))
> ```

desc.allChecks = 
___
*[pkg/sql/sqlbase/structured.go, line 2075 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34301#-LXPZcOt2fZw0HxqQXMe:-LXPZcOt2fZw0HxqQXMf:b-zccspg) ([raw file](https://github.com/cockroachdb/cockroach/blob/938fb995ecd46e99a6795252abea4ae7d469f998/pkg/sql/sqlbase/structured.go#L2075)):*
> ```Go
> 		}
> 	}
> 	return nil, fmt.Errorf("index %q does not exist", name)
> ```

check %q does not exist. 
___
*[pkg/sql/sqlbase/structured.proto, line 194 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34301#-LXPSDwYDzNuO-B9F2mL:-LXPSDwYDzNuO-B9F2mM:bwswx4v) ([raw file](https://github.com/cockroachdb/cockroach/blob/938fb995ecd46e99a6795252abea4ae7d469f998/pkg/sql/sqlbase/structured.proto#L194)):*
> ```protobuf
> 
> enum ConstraintValidity {
>   Validated = 0;
> ```

Can you add a comment for Validated as well:

// The constraint is valid across all rows.
___
*[pkg/sql/sqlbase/structured.proto, line 196 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34301#-LXPSNnm5BWhFveX-wAA:-LXPSNnm5BWhFveX-wAB:bm28c2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/938fb995ecd46e99a6795252abea4ae7d469f998/pkg/sql/sqlbase/structured.proto#L196)):*
> ```protobuf
>   Validated = 0;
>   Unvalidated = 1;
>   // The state for a constraint that was just added, but whose validation
> ```

Perhaps add: // The constraint has yet to be checked across all rows.
___
*[pkg/sql/sqlbase/structured.proto, line 501 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34301#-LXPSdSmERnOyuB1jIxR:-LXPSdSn-99XbHMYdkaK:b5oqt3s) ([raw file](https://github.com/cockroachdb/cockroach/blob/938fb995ecd46e99a6795252abea4ae7d469f998/pkg/sql/sqlbase/structured.proto#L501)):*
> ```protobuf
> // containing each column/index descriptor being added or dropped.
> message DescriptorMutation {
>   message ConstraintToValidate {
> ```

let's place this message outside of DescriptorMutation like the other messages.

**Review by thoszhang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @vivekmenezes)

___
*[pkg/sql/alter_table.go, line 217 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34301#-LXPTs1i5yLtOdpXy9hg:-LXVBPEW3IbU4VjkuXeI:b-mn49jt) ([raw file](https://github.com/cockroachdb/cockroach/blob/938fb995ecd46e99a6795252abea4ae7d469f998/pkg/sql/alter_table.go#L217)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

This seems out of place. Does something break without it?
</blockquote></details>

Yeah, if you add a check constraint on a column that's being added, the check will contain a column ID of 0 in its `ColumnIDs` field which will never get updated later. The test that fails is `TestSchemaChangeAfterCreateInTxn`, at the SCRUB check.

To make sure it wasn't just a SCRUB false positive, I added an UPDATE statement to it, which returns an error when it can't find column 0. (For some reason, INSERT still works even with the invalid column id.)
___
*[pkg/sql/backfill.go, line 601 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34301#-LXPVRtY7drzzjsyf4xc:-LXVOHmkAXNUM5Riqs_N:bolwr5h) ([raw file](https://github.com/cockroachdb/cockroach/blob/938fb995ecd46e99a6795252abea4ae7d469f998/pkg/sql/backfill.go#L601)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

What if there are two columns with two check constraints?
</blockquote></details>

The backfiller validates every check constraint at once. I updated the comment to make this more clear.
___
*[pkg/sql/backfill.go, line 624 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34301#-LXPVazZACGafUXp2Jq7:-LXVEdaX7uAVDJuq_Gnq:bud0s0s) ([raw file](https://github.com/cockroachdb/cockroach/blob/938fb995ecd46e99a6795252abea4ae7d469f998/pkg/sql/backfill.go#L624)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

How about BEGIN; ALTER ADD COLUMN a INT CHECK a < 1; ALTER DROP COLUMN a; COMMIT ?
</blockquote></details>

If you do that, you'll get the `constraint "a" in the middle of being added` error.

This method only gets called when there's a schema change for a new table added earlier in the same transaction. We never add a DROP mutation when dropping a check, we just remove it from the list of checks. So the only time any check validation mutation can be in the DROP state is if it's getting rolled back because of an error, which is a different situation from what this method covers.
___
*[pkg/sql/create_table.go, line 1488 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34301#-LXPWFnz8OPv3jqkyHWm:-LXVTkDx07yi-lzPJ1lM:b-zacql9) ([raw file](https://github.com/cockroachdb/cockroach/blob/938fb995ecd46e99a6795252abea4ae7d469f998/pkg/sql/create_table.go#L1488)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Why do you need this change?
</blockquote></details>

The method gets called by `MakeCheckConstraint`. This change is to deal with non-public columns currently being added.
___
*[pkg/sql/schema_changer.go, line 1160 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34301#-LXPWo699YOmD1Gwx05r:-LXVXV9W50D8bs2PSjhG:b-a5kqyi) ([raw file](https://github.com/cockroachdb/cockroach/blob/938fb995ecd46e99a6795252abea4ae7d469f998/pkg/sql/schema_changer.go#L1160)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Do you think you can add this logic to sc.deleteIndexMutationsWithReversedColumns() and rename that to sc.DeleteDependentMutationsWithReversedColumns() ?
</blockquote></details>

I'm not sure about adding it to that function or any existing function, since this is a new kind of behavior (we're removing something from the table descriptor itself, not just the mutations). I split this out into a new function. 
___
*[pkg/sql/schema_changer.go, line 1838 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34301#-LXPX7l76WHsNKV9i_Mi:-LXVY2ak7jzcQCqESDOs:b26ccv) ([raw file](https://github.com/cockroachdb/cockroach/blob/938fb995ecd46e99a6795252abea4ae7d469f998/pkg/sql/schema_changer.go#L1838)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

I don't believe you need this because you are using the backfiller and not the internal executor
</blockquote></details>

You're right (I forgot to remove this when I added the backfiller)
___
*[pkg/sql/backfill/backfill.go, line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34301#-LXPXoq_30IYVvJGME9h:-LXVZSEY3GL6p2UmdLGa:b-vxw2mu) ([raw file](https://github.com/cockroachdb/cockroach/blob/938fb995ecd46e99a6795252abea4ae7d469f998/pkg/sql/backfill/backfill.go#L84)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Does desc.WritableColumns() work here?
</blockquote></details>

I don't think so, since we also want to exclude columns being dropped
___
*[pkg/sql/distsqlrun/checkbackfiller.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34301#-LXPYbj58dhMZbzJqKUS:-LXVZy1I5KerZApcuMYW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/938fb995ecd46e99a6795252abea4ae7d469f998/pkg/sql/distsqlrun/checkbackfiller.go#L28)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

checkBackfiller
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/structured.go, line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34301#-LXP_9NH0m88a0-KUjtd:-LXV_mrV6tx6a1P9a6W9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/938fb995ecd46e99a6795252abea4ae7d469f998/pkg/sql/sqlbase/structured.go#L252)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

desc.allChecks = 
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/structured.go, line 2075 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34301#-LXPZcOt2fZw0HxqQXMe:-LXV_vDDAFMOf_h57rmT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/938fb995ecd46e99a6795252abea4ae7d469f998/pkg/sql/sqlbase/structured.go#L2075)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

check %q does not exist. 
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/structured.proto, line 194 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34301#-LXPSDwYDzNuO-B9F2mL:-LXVb9j8DGNc-8Cg40xV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/938fb995ecd46e99a6795252abea4ae7d469f998/pkg/sql/sqlbase/structured.proto#L194)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Can you add a comment for Validated as well:

// The constraint is valid across all rows.
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/structured.proto, line 196 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34301#-LXPSNnm5BWhFveX-wAA:-LXVb9yZ7gYFaWuRUpvB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/938fb995ecd46e99a6795252abea4ae7d469f998/pkg/sql/sqlbase/structured.proto#L196)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Perhaps add: // The constraint has yet to be checked across all rows.
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/structured.proto, line 501 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34301#-LXPSdSmERnOyuB1jIxR:-LXVc86G6x8VUu9vGa3r:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/938fb995ecd46e99a6795252abea4ae7d469f998/pkg/sql/sqlbase/structured.proto#L501)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

let's place this message outside of DescriptorMutation like the other messages.
</blockquote></details>

Done.

**Review by thoszhang — COMMENTED** [review]
Ready for another look.

I also added a few tests to the `schema_change_in_txn` logic test for the errors that are returned when trying to drop or validate a check constraint that's being added.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34301#-:-LXVjHjg1-KyWPUZf1Xd:b-ywh5eh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @vivekmenezes)

**Review by vivekmenezes — COMMENTED** [review]
Thanks for updating the PR. I think this PR should wait on https://github.com/cockroachdb/cockroach/pull/34263 to merge so you can remove the backfill functionality in this PR. Thanks

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34301#-:-LXZTUzV1oDhiT0_3LSY:bcbmz06)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @vivekmenezes)

**Review by thoszhang — COMMENTED** [review]
This is ready for another look. I replaced the backfiller with the InternalExecutor SQL query, and added some more tests, mostly for when a table is created and schema changes are made in the same transaction, since that case currently has very little coverage.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34301#-:-LYU_O6S2QIO1no-I_YE:b-tzp5h1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @vivekmenezes)

**Review by vivekmenezes — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34301)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @lucy-zhang)

___
*[pkg/sql/backfill.go, line 284 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34301#-LYUhucR2UGO0nnHAZlW:-LYUhucR2UGO0nnHAZlX:b-q53qiv) ([raw file](https://github.com/cockroachdb/cockroach/blob/cea639ae578a85e6a35b68c38fc8931f082265cc/pkg/sql/backfill.go#L284)):*
> ```Go
> 				}
> 
> 				return validateCheckExpr(ctx, check.Expr, desc.TableDesc(), ie, txn)
> ```

All the code above is a copy of the code in ValidateCheckInTxn() . Make the recommended change to ValidateCheckInTxn and call it from here too.
___
*[pkg/sql/backfill.go, line 898 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34301#-LYUhXfY5Jhgcbx1jpzj:-LYUhXfY5Jhgcbx1jpzk:b4rboxe) ([raw file](https://github.com/cockroachdb/cockroach/blob/cea639ae578a85e6a35b68c38fc8931f082265cc/pkg/sql/backfill.go#L898)):*
> ```Go
> 	tableDesc *MutableTableDescriptor,
> 	txn *client.Txn,
> 	checks []sqlbase.ConstraintToValidate,
> ```

You can iterate on the checks outside this function and then you will be able to use ValidateCheckInTxn() both here and in the normal case above. See my other comment.
___
*[pkg/sql/check.go, line 54 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34301#-LYUiDG9EvnZ7xDZznWI:-LYUiDG9EvnZ7xDZznWJ:bpi6nui) ([raw file](https://github.com/cockroachdb/cockroach/blob/cea639ae578a85e6a35b68c38fc8931f082265cc/pkg/sql/check.go#L54)):*
> ```Go
> 
> 	queryStr := tree.AsStringWithFlags(stmt, tree.FmtParsable)
> 	log.Infof(ctx, "Validating check constraint %q with query %q", expr.String(), queryStr)
> ```

take out
___
*[pkg/sql/sqlbase/structured.go, line 2291 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34301#-LYUj_BX3U1ATxqqgZg6:-LYUj_BX3U1ATxqqgZg7:bd30ifx) ([raw file](https://github.com/cockroachdb/cockroach/blob/cea639ae578a85e6a35b68c38fc8931f082265cc/pkg/sql/sqlbase/structured.go#L2291)):*
> ```Go
> 		i++
> 	}
> 	table.Mutations = table.Mutations[i:]
> ```

good catch

**Comment by vivekmenezes** [comment]
Nice work!

**Review by thoszhang — COMMENTED** [review]
TFTR, just 1 minor question

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34301#-:-LYXsexy7Gh7i9Z-axZY:b-guqmmt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @lucy-zhang, and @vivekmenezes)

___
*[pkg/sql/backfill.go, line 284 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34301#-LYUhucR2UGO0nnHAZlW:-LYXsKM37fugnWuq5uMZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cea639ae578a85e6a35b68c38fc8931f082265cc/pkg/sql/backfill.go#L284)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

All the code above is a copy of the code in ValidateCheckInTxn() . Make the recommended change to ValidateCheckInTxn and call it from here too.
</blockquote></details>

Done.
___
*[pkg/sql/backfill.go, line 898 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34301#-LYUhXfY5Jhgcbx1jpzj:-LYXsL1-63dV0tBK9wHj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cea639ae578a85e6a35b68c38fc8931f082265cc/pkg/sql/backfill.go#L898)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

You can iterate on the checks outside this function and then you will be able to use ValidateCheckInTxn() both here and in the normal case above. See my other comment.
</blockquote></details>

Done.
___
*[pkg/sql/check.go, line 54 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34301#-LYUiDG9EvnZ7xDZznWI:-LYXsNYnAB7ZVJVv1o6O:bygi3f7) ([raw file](https://github.com/cockroachdb/cockroach/blob/cea639ae578a85e6a35b68c38fc8931f082265cc/pkg/sql/check.go#L54)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

take out
</blockquote></details>

I added this to match the logging for the FK validation queries (elsewhere in this file). Should the logging be removed?

**Review by vivekmenezes — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34301#-:-LYXtxV9-JkUd4ObJOPu:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt and @lucy-zhang)

**Comment by lucy-zhang** [comment]
I'm getting `No space left on device` on the build agent. I'm going to recreate the agent and try again.

**Pull request merged**
