### PR TITLE
ui: get smarter about pinning protobufjs's dependency set

### PR DESCRIPTION
**Pull request by benesch**
ProtobufJS's CLI attempts to install its own dependencies by invoking
NPM. This breaks our dependency pinning and vendoring, so we pre-install
its dependencies ourselves. Unfortunately, the CLI maintains two
different dependency lists: the cliDependencies field in package.json,
and the dependencies field in cli/package.standalone.json.  We were
looking at the latter when pre-installing the CLI's dependencies, but
only the former is maintained.

This patch adds a script to extract a package.json that encodes
up-to-date dependency information. The Makefile then invokes `yarn
install` on this synthesized package. This guarantees that the
ProtobufJS CLI will see that the correct versions of its dependencies
are pre-installed and will not invoke NPM.

The resulting diff in pkg/ui/yarn.protobuf-cli.lock reveals that
ProtobufJS was installing newer versions of its dependencies without us
realizing it. Note that it is now safe to use new versions of jsdoc; the
issue mentioned in the Makefile was fixed in jsdoc 3.5.4
(jsdoc3/jsdoc#1408).

To prevent accidents in the future, a forthcoming commit will remove NPM
from the builder image so that CI will fail if ProtobufJS attempts to
invoke NPM behind our back. See #27163.

Release note: None

### CODE REVIEW

**Comment by benesch** [comment]
And yes, this is insanity. I would really like to move away from ProtobufJS.

**Comment by knz** [comment]
LGTM!

Thank you for the lightning fast turnaround.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by benesch** [comment]
Thanks for finding the problem and reviewing the fix!

bors r=knz

**Comment by vilterp** [comment]
Wow. Yeah the CLI invoking NPM is pretty nuts.

**Pull request merged**
