### PR TITLE
upgrades: make stmt diag upgrade idempotent

### PR DESCRIPTION
**Pull request by yuzefovich**
All upgrades are expected to be idempotent, but the stmt diag upgrade (needed for plan-gist batched matching) wasn't - we needed to add `IF EXISTS` clause to the `DROP INDEX` stmt (which doesn't have a meaningful `schemaExistsFn`). Additionally, we can combine two stmts that add a single column into one that adds two.

Epic: None

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
In terms of testing, I added a simple implementation of Radu's idea in #112462.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112470#-:-NguXvhrBAUq0ZEDZWnM:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

___
*[`pkg/upgrade/upgrades/plan_gist_stmt_diagnostics_requests.go` line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112470#-NguWrg20XD_JlNGzaKY:-NguWrg20XD_JlNGzaKZ:b-91rgc5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a87af63db8849632d6e8ec301899885731d8b28a/pkg/upgrade/upgrades/plan_gist_stmt_diagnostics_requests.go#L28)):*
> ```Go
> 	addPlanGistColsToStmtDiagReqs = `
> ALTER TABLE system.statement_diagnostics_requests
>   ADD COLUMN IF NOT EXISTS plan_gist STRING NULL FAMILY "primary",
> ```

I assume we guarantee that these two mutations are performed atomically? Otherwise we'd get a "partial schema" error when we check `schemaExistsFn`.
___
*[`pkg/upgrade/upgrades/plan_gist_stmt_diagnostics_requests.go` line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112470#-NguXGx74zOZGPTtP-Zh:-NguXGx74zOZGPTtP-Zi:bg12vm3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a87af63db8849632d6e8ec301899885731d8b28a/pkg/upgrade/upgrades/plan_gist_stmt_diagnostics_requests.go#L29)):*
> ```Go
> ALTER TABLE system.statement_diagnostics_requests
>   ADD COLUMN IF NOT EXISTS plan_gist STRING NULL FAMILY "primary",
>   ADD COLUMN IF NOT EXISTS anti_plan_gist BOOL NULL FAMILY "primary"`
> ```

[nit] IF NOT EXISTS is not necessary here because of the `schemaExistsFn`.
___
*[`pkg/upgrade/upgrades/plan_gist_stmt_diagnostics_requests.go` line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112470#-NguXYJH3l1ptnvcWzIw:-NguXYJH3l1ptnvcWzIx:be3kma8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a87af63db8849632d6e8ec301899885731d8b28a/pkg/upgrade/upgrades/plan_gist_stmt_diagnostics_requests.go#L35)):*
> ```Go
>   STORING (statement_fingerprint, min_execution_latency, expires_at, sampling_probability, plan_gist, anti_plan_gist)`
> 
> 	dropCompletedIdx = `DROP INDEX IF EXISTS system.statement_diagnostics_requests@completed_idx`
> ```

An alternative would be to have a proper `schemaExistsFn` for this step, one which just flips the result of `hasIndex()`. It might result in better log messages ("skipping operation" vs "performing operation")

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112470)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @RaduBerinde)

___
*[`pkg/upgrade/upgrades/plan_gist_stmt_diagnostics_requests.go` line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112470#-NguWrg20XD_JlNGzaKY:-Ngue7zh8YJLBUoexj9S:b-2xxhjq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a87af63db8849632d6e8ec301899885731d8b28a/pkg/upgrade/upgrades/plan_gist_stmt_diagnostics_requests.go#L28)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I assume we guarantee that these two mutations are performed atomically? Otherwise we'd get a "partial schema" error when we check `schemaExistsFn`.
</blockquote></details>

I think so, but I'll double check with Foundations.
___
*[`pkg/upgrade/upgrades/plan_gist_stmt_diagnostics_requests.go` line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112470#-NguXYJH3l1ptnvcWzIw:-NgueENI7E_wWo_EHnr_:bb75br1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a87af63db8849632d6e8ec301899885731d8b28a/pkg/upgrade/upgrades/plan_gist_stmt_diagnostics_requests.go#L35)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

An alternative would be to have a proper `schemaExistsFn` for this step, one which just flips the result of `hasIndex()`. It might result in better log messages ("skipping operation" vs "performing operation")
</blockquote></details>

I considered it, but it seems safer to not come up with a custom `schemaExistsFn` in this case - we currently don't have any other places for a similar "skip drop if already dropped" scenario.

**Review by RaduBerinde — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112470)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

**Review by yuzefovich — COMMENTED** [review]
TFTR and for the find!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112470#-:-NgyTzHb8PcgwVEibdGZ:bpqv5dp)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[`pkg/upgrade/upgrades/plan_gist_stmt_diagnostics_requests.go` line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112470#-NguWrg20XD_JlNGzaKY:-NgyTpoQ68OZnuAIglvE:b-m4milm) ([raw file](https://github.com/cockroachdb/cockroach/blob/a87af63db8849632d6e8ec301899885731d8b28a/pkg/upgrade/upgrades/plan_gist_stmt_diagnostics_requests.go#L28)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I think so, but I'll double check with Foundations.
</blockquote></details>

Xiang confirmed that it's atomic.

**Pull request merged**
