### PR TITLE
acceptance,server: move TestDebugRemote to an acceptance test

### LINKED ISSUE #14714: server: TestDebugRemote fails
```
--- FAIL: TestDebugRemote (3.04s)
	debug_test.go:70: Get http://viveks-MacBook-Pro.local:64048/debug/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

/etc/hosts 

```
127.0.0.1	localhost
255.255.255.255	broadcasthost
```

### PR DESCRIPTION
**Pull request by petermattis**
Change COCKROACH_REMOTE_DEBUG to server.debug.remote cluster setting.

Fixes #14714

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/acceptance/debug_remote_test.go, line 50 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15280#-KiVKeRNb6HVDBhiEiXQ:-KiVKeRNb6HVDBhiEiXR:b-eorovj) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcddb867edd2f74845aa223295552943b62fbb10/pkg/acceptance/debug_remote_test.go#L50)):*
> ```Go
> 	}
> 	defer func() {
> 		_ = db.Close()
> ```

may as well check the error.

---

*[pkg/acceptance/debug_remote_test.go, line 65 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15280#-KiVKkdxZuxc8TlB41hb:-KiVKkdxZuxc8TlB41hc:b-5hku7b) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcddb867edd2f74845aa223295552943b62fbb10/pkg/acceptance/debug_remote_test.go#L65)):*
> ```Go
> 		{"unrecognized", http.StatusUnauthorized},
> 	}
> 	for i, c := range testCases {
> ```

subtests?

---

*[pkg/acceptance/debug_remote_test.go, line 66 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15280#-KiVKhKKvTT34_O_Zrsc:-KiVKhKKvTT34_O_Zrsd:b-1rbmsu) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcddb867edd2f74845aa223295552943b62fbb10/pkg/acceptance/debug_remote_test.go#L66)):*
> ```Go
> 	}
> 	for i, c := range testCases {
> 		setStmt := fmt.Sprintf("SET CLUSTER SETTING server.debug.remote = '%s'", c.remoteDebug)
> ```

do these statements not support placeholders? urgh. cc @dt 

---

*[pkg/server/debug.go, line 47 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15280#-KiVKT4O8qHMg13LXYFA:-KiVKT4P4SweddpOIEvl:b8wo0ym) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcddb867edd2f74845aa223295552943b62fbb10/pkg/server/debug.go#L47)):*
> ```Go
> 	"server.debug.remote",
> 	"set to enable remote debugging, localhost-only or disable (all, local, false)",
> 	"local")
> ```

nit: comma on this line and close paren on the next line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15280#-:-KiVKpoVgYOge_Lzi9UD:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/acceptance/debug_remote_test.go, line 50 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15280#-KiVKeRNb6HVDBhiEiXQ:-KiVNfq1VLlgul_jAAzx:b5kvkx9) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcddb867edd2f74845aa223295552943b62fbb10/pkg/acceptance/debug_remote_test.go#L50)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

may as well check the error.
</blockquote></details>

I cribbed that from somewhere else. The common pattern is `defer db.Close()`.

---

*[pkg/acceptance/debug_remote_test.go, line 65 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15280#-KiVKkdxZuxc8TlB41hb:-KiVNbsxTlMCf_B_ukca:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcddb867edd2f74845aa223295552943b62fbb10/pkg/acceptance/debug_remote_test.go#L65)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

subtests?
</blockquote></details>

Done.

---

*[pkg/acceptance/debug_remote_test.go, line 66 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15280#-KiVKhKKvTT34_O_Zrsc:-KiVN_bqZdmJjFk_VyvE:bkrqwwd) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcddb867edd2f74845aa223295552943b62fbb10/pkg/acceptance/debug_remote_test.go#L66)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

do these statements not support placeholders? urgh. cc @dt 
</blockquote></details>

Not as far as I can tell.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15280)*

**Comment by tamird** [comment]
Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/acceptance/debug_remote_test.go, line 64 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15280#-KiVSdIUXsLwMkcWYca8:-KiVSdIUXsLwMkcWYca9:butzok3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7d31cd97cd4a0e9673fba44589c1efbf72cc1c6/pkg/acceptance/debug_remote_test.go#L64)):*
> ```Go
> 	}
> 	for _, c := range testCases {
> 		t.Run("", func(t *testing.T) {
> ```

c.remoteDebug instead of empty string?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15280)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/acceptance/debug_remote_test.go, line 66 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15280#-KiVKhKKvTT34_O_Zrsc:-KiVS-g-zuYpPuDm-Vw9:bh94exk) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcddb867edd2f74845aa223295552943b62fbb10/pkg/acceptance/debug_remote_test.go#L66)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Not as far as I can tell.
</blockquote></details>

The `SET` grammar doesn't AFAIK -- I haven't looked closely, but I think switching the RHS to an expr would be nice -- @knz has thought about it more than I have though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15280)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/acceptance/debug_remote_test.go, line 64 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15280#-KiVSdIUXsLwMkcWYca8:-KiVSywXo3uWriJE99bb:b-it0x4k) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7d31cd97cd4a0e9673fba44589c1efbf72cc1c6/pkg/acceptance/debug_remote_test.go#L64)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

c.remoteDebug instead of empty string?
</blockquote></details>

Does it matter? I'll change it if I have to go through another round of CI.

---

*[pkg/server/debug.go, line 47 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15280#-KiVKT4O8qHMg13LXYFA:-KiVSt-dEH1jhXn3mtXv:bebp48v) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcddb867edd2f74845aa223295552943b62fbb10/pkg/server/debug.go#L47)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

nit: comma on this line and close paren on the next line
</blockquote></details>

Oops, didn't mean to ignore this, except I did because I'm not a believer in that style. :smile: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15280)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/acceptance/debug_remote_test.go, line 64 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15280#-KiVSdIUXsLwMkcWYca8:-KiVTUBAJQ0IxrEete80:bl3q5iz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7d31cd97cd4a0e9673fba44589c1efbf72cc1c6/pkg/acceptance/debug_remote_test.go#L64)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Does it matter? I'll change it if I have to go through another round of CI.
</blockquote></details>

I mean, I think it matters to have helpful errors, but I guess I won't insist. Btw, the cost of changing this isn't another round of CI, since the current one only just started.

---

*[pkg/server/debug.go, line 47 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15280#-KiVKT4O8qHMg13LXYFA:-KiVTfMMzB6bbxHPkKoG:bb7km6z) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcddb867edd2f74845aa223295552943b62fbb10/pkg/server/debug.go#L47)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Oops, didn't mean to ignore this, except I did because I'm not a believer in that style. :smile: 
</blockquote></details>

merp

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15280)*

**Pull request merged**
