### PR TITLE
ui: add column selector to transation page

### LINKED ISSUE #70148: add column selector on transactions page
add the column selector component to transactions page to align with statements page

### PR DESCRIPTION
**Pull request by maryliag**
Add column selector to Transaction Page

Fixes #70148

Screen Shot 2021-09-15 at 11 28 56 AM

Release justification: Category 4
Release note (ui change): Add column selector to transaction page

### CODE REVIEW

**Review by matthewtodd — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70262#-:-MjeMk8L7g2o4KUPV6HL:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag)

**Review by Azhng — COMMENTED** [review]
> Reviewed 2 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70262)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/statsTableUtil/statsTableUtil.tsx, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70262#-MjeNQrI9hR7eZ6c3iOa:-MjeNQrJ7-SrSjJbHg87:bg8apqn) ([raw file](https://github.com/cockroachdb/cockroach/blob/926ef9cfa5416fcca98e846ac70ce8f49a169c81/pkg/ui/workspaces/cluster-ui/src/statsTableUtil/statsTableUtil.tsx#L41)):*
> ```XML
>   rowsRead: "Rows Read",
>   statements: "Statements",
>   statementsCount: "Statements",
> ```

`statements` and `statementsCount` have the same column label ?
___
*[pkg/ui/workspaces/cluster-ui/src/statsTableUtil/statsTableUtil.tsx, line 588 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70262#-MjeNgtT6pIN9A_86lG3:-MjeNgtT6pIN9A_86lG4:b-kstsgr) ([raw file](https://github.com/cockroachdb/cockroach/blob/926ef9cfa5416fcca98e846ac70ce8f49a169c81/pkg/ui/workspaces/cluster-ui/src/statsTableUtil/statsTableUtil.tsx#L588)):*
> ```XML
>     );
>   },
>   statementsCount: (statType: StatisticType) => {
> ```

Do we also want to annotate the return types here like we did for other places in this PR ?

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70262)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/ui/workspaces/cluster-ui/src/statsTableUtil/statsTableUtil.tsx, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70262#-MjeNQrI9hR7eZ6c3iOa:-MjeTnt10AJ5uM1U-teK:bgr47y9) ([raw file](https://github.com/cockroachdb/cockroach/blob/926ef9cfa5416fcca98e846ac70ce8f49a169c81/pkg/ui/workspaces/cluster-ui/src/statsTableUtil/statsTableUtil.tsx#L41)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

`statements` and `statementsCount` have the same column label ?
</blockquote></details>

same column label, different tooltip. That's why they need to be different keys here
___
*[pkg/ui/workspaces/cluster-ui/src/statsTableUtil/statsTableUtil.tsx, line 588 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70262#-MjeNgtT6pIN9A_86lG3:-MjeTwvy2oWGcmdy4_Ui:b-7i3b32) ([raw file](https://github.com/cockroachdb/cockroach/blob/926ef9cfa5416fcca98e846ac70ce8f49a169c81/pkg/ui/workspaces/cluster-ui/src/statsTableUtil/statsTableUtil.tsx#L588)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Do we also want to annotate the return types here like we did for other places in this PR ? 
</blockquote></details>

the return type here is a little trickier, we're returning as Element, but is we add return type Element it requires several other parameters, so I made the decision of leaving those one as is

**Review by Azhng — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70262#-:-Mjeag7J9Ngw832fTsos:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @maryliag)

**Pull request merged**
