### PR TITLE
ui: clusterviz: liveness status counts for nodes & localities

### PR DESCRIPTION
**Pull request by vilterp**
## Localities

All live:
screen shot 2018-02-14 at 4 39 40 pm

Some dead and suspect:
screen shot 2018-02-14 at 4 39 15 pm

Just one suspect:
screen shot 2018-02-14 at 4 45 28 pm

Just one dead:
screen shot 2018-02-14 at 4 45 42 pm

Decommissioning nodes are counted as suspect, until we change `sumNodeStats` at some point in the future…

## Individual Nodes

| Live                                                                                                                                      | Suspect                                                                                                                                      | Dead                                                                                                                                   |
|-------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------|
| screen shot 2018-02-14 at 5 26 29 pm | screen shot 2018-02-14 at 5 26 43 pm | screen shot 2018-02-14 at 5 26 56 pm |

Release note: None

### CODE REVIEW

**Comment by couchand** [comment]
> Decommission(ing|ed) are ignored from these counts.

Unfortunately, that's not true:

https://github.com/cockroachdb/cockroach/blob/814a7ee11e5b32c494579265bdf449897b2a1bc8/pkg/ui/src/redux/nodes.ts#L151

**Comment by vilterp** [comment]
Edited

**Comment by couchand** [comment]
Talked about this in meatspace, it's consistent, so it's probably fine.  If we want to change the classification of decommissioning nodes so they don't show up as suspect in the future, it will affect both places since they're both using the same source data.

**Comment by couchand** [comment]
sure hope nobody has double-digits of suspect or dead nodes

:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/ui/ccl/src/views/clusterviz/containers/map/localityView.tsx, line 38 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22708#-L5LRzVdPczlO1gK1fpZ:-L5LRzVdPczlO1gK1fp_:b2nif2d) ([raw file](https://github.com/cockroachdb/cockroach/blob/3252c48d2cfa4b496c7f460ba0ecb99929ed3442/pkg/ui/ccl/src/views/clusterviz/containers/map/localityView.tsx#L38)):*
> ```XML
> const LIVENESS_TOTAL_WIDTH = LIVENESS_ICON_RADIUS * 2 + LIVENESS_ICON_SPACING;
> 
> // function StatusIcon
> ```

wat

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22708#-:-L5LSqwZ6fhBdLW8JsqP:b-7ov2z5)*

**Comment by vilterp** [comment]
Good point. Yeah, not gonna worry about that one. That would be a helluva dependent type, btw — "this text always fits inside this circle"…

**Pull request merged**
