### PR TITLE
sql: support output parameters in procedures

### PR DESCRIPTION
**Pull request by yuzefovich**
See each commit for details.

Addresses: #100405.
Epic: CRDB-30611

### CODE REVIEW

**Comment by yuzefovich** [comment]
This is RFAL. First and third commit are exactly as from one approved revision of #120029 (so they deserve little scrutiny) - I extracted all the new changes into the second commit (that I will squash into first one before merging).

I also have some further changes to match the behavior of Postgres on DROP PROCEDURE, but it'll be in a separate PR.

**Review by DrewKimball — APPROVED** [review]
:lgtm: Great work!

> Reviewed 21 of 21 files at r1, 24 of 24 files at r4, 19 of 19 files at r5, 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120851#-:-Nt_P86-6UkhHK5RVXk1:bolbkdq)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

___
*[`pkg/sql/opt/optbuilder/routine.go` line 146 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/120851#-Nt_9AfhEiA1fKw1q0AS:-Nt_9AfhEiA1fKw1q0AT:b-73m6vw) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0a4c078fde40f71feb6bce54f5c76df5cf9cf30/pkg/sql/opt/optbuilder/routine.go#L146)):*
> ```Go
> 			pgerror.Newf(
> 				pgcode.WrongObjectType,
> 				"%s(%s) is not a procedure", def.Name, strings.Join(typeNames, ", "),
> ```

Nice catch!
___
*[`pkg/sql/sem/tree/type_check.go` line 1228 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/120851#-Nt_MXt_0WhoOL0GGgl4:-Nt_MXt_0WhoOL0GGgl5:b-hvuajz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0a4c078fde40f71feb6bce54f5c76df5cf9cf30/pkg/sql/sem/tree/type_check.go#L1228)):*
> ```Go
> 				} else {
> 					s2.release()
> 				}
> ```

[nit] Since this is going to error anyway, could we simplify the `release` situation if we threw the `_ is not a procedure` error here? (or `unknown signature` if no UDF was found).
___
*[`pkg/sql/sem/tree/type_check.go` line 3475 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/120851#-Nt_N8uC2lCKk4CB7Qhd:-Nt_N8uC2lCKk4CB7Qhe:b-2qocql) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0a4c078fde40f71feb6bce54f5c76df5cf9cf30/pkg/sql/sem/tree/type_check.go#L3475)):*
> ```Go
> ) (QualifiedOverload, error) {
> 	ambiguousError := func() error {
> 		if ambiguousErrorOverride != nil {
> ```

[nit] can we just check `expr.InCall` here and throw the correct error?

**Review by yuzefovich — COMMENTED** [review]
TFTR!

Will wait for green CI, then squash 2nd commit into 1st and will merge.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120851#-:-NtbBe_sE2uox0GlT3dF:b4jfp0p)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/sem/tree/type_check.go` line 1228 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/120851#-Nt_MXt_0WhoOL0GGgl4:-NtbBV_M5FJm2F519EYw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0a4c078fde40f71feb6bce54f5c76df5cf9cf30/pkg/sql/sem/tree/type_check.go#L1228)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Since this is going to error anyway, could we simplify the `release` situation if we threw the `_ is not a procedure` error here? (or `unknown signature` if no UDF was found).
</blockquote></details>

Done.
___
*[`pkg/sql/sem/tree/type_check.go` line 3475 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/120851#-Nt_N8uC2lCKk4CB7Qhd:-Ntb6G0Y6InKsU9Uv0eS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0a4c078fde40f71feb6bce54f5c76df5cf9cf30/pkg/sql/sem/tree/type_check.go#L3475)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] can we just check `expr.InCall` here and throw the correct error?
</blockquote></details>

Done.

**Review by mgartner — APPROVED** [review]
What a doozy! Thanks for being so thorough! And thanks to Drew for a thorough review of this.

> Reviewed 21 of 21 files at r1, 24 of 24 files at r4, 14 of 19 files at r5, 10 of 10 files at r7, 8 of 8 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120851#-:-NtbpxiCBWuzqjcdW-GP:b-pi4lpu)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @yuzefovich)

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

**Pull request merged**
