### PR TITLE
sql: add old zone config in zone config logs

### LINKED ISSUE #127176: sql: zone configuration changes logging enhancement
**Is your feature request related to a problem? Please describe.**
CRDB needs to log the **original** and final zone configuration changes when such are made. Currently there is no way to tell what was the original/previous zone configuration if it was changed. Only the final config is logged. 
This is a problem mostly when the replication factor changes (e.g. from 3 to 5) and the console starts reporting under replicated ranges. 

**Describe the solution you'd like**
CRDB needs to write both the original and the final zone configuration in the events log or audit log or somewhere else.

**Describe alternatives you've considered**
Currently the only alternative is to run something like this and go back in time (**if the GC hasn't ran yet**):

```
SELECT id, crdb_internal.pb_to_json('cockroach.config.zonepb.ZoneConfig', config) FROM system.zones AS OF SYSTEM TIME '<insert some time>;
```

**Additional context**
Without this it is harder to troubleshoot under replicated ranges when replication factor has been increased. 

Jira issue: CRDB-40305

Epic CRDB-31473

### PR DESCRIPTION
**Pull request by annrpom**
### sql: add old zone config in zone config logs
This patch adds another field in `eventpb.SetZoneConfig`.
This field, `ResolvedOldConfig`, will aid in logging the zone configuration
that we have changed.

We use the `completeZone/completeSubzone` here because we want to
be more useful in our zone config logging. The benefit of using the
complete* is that we can explicitly see what fields are changing,
even if they are actually modeled as a zone config that just inherits
from its parent. The disadvantage of this is that we are not able
to easily tell the inheritence of the old zone config, but knowing
the actual diff between the old vs new config seems more relevant
for debugging.

Fixes: https://github.com/cockroachdb/cockroach/issues/127176

Release note: None

---

### schemachanger: log index, partition
This patch enables logging for index and partition
zone configs in the DSC.

Release note: None

---

### schemachanger: add old zone config in zone config logs in DSC
This patch fills the `ResolvedOldConfig` field in
`eventpb.SetZoneConfig` to log the old zone configuration
in the declarative schema changer.

Informs: https://github.com/cockroachdb/cockroach/issues/127176

Release note: None

### CODE REVIEW

**Comment by annrpom** [comment]
Tests are failing because I need to update some side effects files from our end to end testing; I'll update before merge

**Review by rafiss — APPROVED** [review]
nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132677#-:-O9LgVFJ8HWU8ZKD6MBJ:b-j4xmku)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aa-joshi, @angles-n-daemons, @annrpom, and @arjunmahishi)

___
*[`pkg/ccl/logictestccl/testdata/logic_test/event_log` line 0 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132677#-O9Lf6nP5MjAQv9cFRMz:-O9Lf6nQ9MJREdL_JHT1:b-wbvs2s) ([raw file](https://github.com/cockroachdb/cockroach/blob/0779301281f90823b5c85b909363770ebc5249c0/pkg/ccl/logictestccl/testdata/logic_test/event_log#L0)):*
do you know why this had to be in the `ccl` package?

**Review by annrpom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132677)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aa-joshi, @angles-n-daemons, @arjunmahishi, and @rafiss)

___
*[`pkg/ccl/logictestccl/testdata/logic_test/event_log` line  at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132677#-O9Lf6nP5MjAQv9cFRMz:-O9MRpR17Xxi4ZAQz6HU:b-89flgk) ([raw file](https://github.com/cockroachdb/cockroach/blob/0779301281f90823b5c85b909363770ebc5249c0/pkg/ccl/logictestccl/testdata/logic_test/event_log#L)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

do you know why this had to be in the `ccl` package?
</blockquote></details>

relevant pr: https://github.com/cockroachdb/cockroach/pull/132788
i'll make this a stacked PR on top of ^; it doesn't have to be in the ccl package after the above

**Comment by annrpom** [comment]
TFTR! ('-')7

bors r=rafiss

**Pull request merged**
