### PR TITLE
pkg/ui: Make tracez v2 page node-aware

### PR DESCRIPTION
**Pull request by benbardin**
Release note: None

Demo video below. Note that it starts on the v1 trace page, and I navigate to the new one by typing in the address bar.

https://user-images.githubusercontent.com/261508/196736069-952dadde-dcb7-4060-8563-e98727b48a48.mov

Part of https://github.com/cockroachdb/cockroach/issues/83679

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
Thanks for working on this!

> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90244#-:-NFAEF5y4Vnd4QJXofc_:b-4v1jpi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @benbardin, @dhartunian, and @sjbarag)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90244#-NFA7ZKl82wLx8f7b0o0):*
Please put more in this commit message.
Please explain how the interaction with the cookie works. The cookie in question is the one used for routing, right? I'm surprised our page needs understand anything about it.

Am I right to assume that if there's no node ID in the URL and no cookie, I get the data from the node serving the page? I think that'd be a good default. We'll probably need to find a way to resolve the node ID of the local node. If that's too much work, and also in cases where the local node does not yet have a node id, I think showing it as "local" in the nodes dropdown would be fine.
Another thing I want to make sure is that the page works against the current node even if the current node can't talk to anybody else and even if the `/nodes` endpoint returns an error. Reliably getting data from the local node is important for a lower-level tool like this page.

Related to all this, I also want to make sure that we're not making it hard for this page to work for tenant sql servers. I don't know if it works currently, but it'll need to work soon. Even if we don't figure out how to list all of the tenant's pods, I want at least it shouldn't get harder to make getting data from the server serving the page.
___
*[`pkg/ui/workspaces/cluster-ui/src/tracez/snapshot/snapshotPage.tsx` line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90244#-NFA6gts91Qno93nJnKA:-NFA6gts91Qno93nJnKB:b-ujtdee) ([raw file](https://github.com/cockroachdb/cockroach/blob/004f4445fd509b2fe28f93aa626af56421e9fc56/pkg/ui/workspaces/cluster-ui/src/tracez/snapshot/snapshotPage.tsx#L88)):*
> ```XML
>   const nodeIDStr = getMatchParamByName(match, "nodeID");
> 
>   // Load iniital data.
> ```

iniitial
___
*[`pkg/ui/workspaces/cluster-ui/src/tracez/snapshot/snapshotPage.tsx` line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90244#-NFA6wl42XOVD3gEj5WS:-NFA6wl42XOVD3gEj5WT:bedhqu7) ([raw file](https://github.com/cockroachdb/cockroach/blob/004f4445fd509b2fe28f93aa626af56421e9fc56/pkg/ui/workspaces/cluster-ui/src/tracez/snapshot/snapshotPage.tsx#L97)):*
> ```XML
>       return;
>     }
>     refreshSnapshots(parseInt(nodeIDStr));
> ```

if we can lift the `parseInt`s out of these functions, I think that'd be good.
___
*[`pkg/ui/workspaces/db-console/src/app.spec.tsx` line 502 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90244#-NFA6CXXCSGa4TWZPd6y:-NFA6CXYAPsAAKtDkIEk:b3o3ujf) ([raw file](https://github.com/cockroachdb/cockroach/blob/004f4445fd509b2fe28f93aa626af56421e9fc56/pkg/ui/workspaces/db-console/src/app.spec.tsx#L502)):*
> ```XML
> 
>   describe("'/debug/tracez_v2/snapshot/:id' path", () => {
>     test("routes to <ScheduleDetails> component", () => {
> ```

is this "ScheduleDetails" right?

**Review by benbardin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90244)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @andreimatei, @dhartunian, and @sjbarag)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90244#-NFA7ZKl82wLx8f7b0o0):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Please put more in this commit message.
Please explain how the interaction with the cookie works. The cookie in question is the one used for routing, right? I'm surprised our page needs understand anything about it.

Am I right to assume that if there's no node ID in the URL and no cookie, I get the data from the node serving the page? I think that'd be a good default. We'll probably need to find a way to resolve the node ID of the local node. If that's too much work, and also in cases where the local node does not yet have a node id, I think showing it as "local" in the nodes dropdown would be fine.
Another thing I want to make sure is that the page works against the current node even if the current node can't talk to anybody else and even if the `/nodes` endpoint returns an error. Reliably getting data from the local node is important for a lower-level tool like this page.

Related to all this, I also want to make sure that we're not making it hard for this page to work for tenant sql servers. I don't know if it works currently, but it'll need to work soon. Even if we don't figure out how to list all of the tenant's pods, I want at least it shouldn't get harder to make getting data from the server serving the page.
</blockquote></details>

Discussed offline - we agreed to ignore the cookie entirely, and use the local node if none is supplied. We'll attempt to look up the local node's ID, but won't block on that in case it isn't available for some reason.
___
*[`pkg/ui/workspaces/cluster-ui/src/tracez/snapshot/snapshotPage.tsx` line 88 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90244#-NFA6gts91Qno93nJnKA:-NFG1hkdBVLblAZEcAk7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/004f4445fd509b2fe28f93aa626af56421e9fc56/pkg/ui/workspaces/cluster-ui/src/tracez/snapshot/snapshotPage.tsx#L88)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

iniitial
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/tracez/snapshot/snapshotPage.tsx` line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90244#-NFA6wl42XOVD3gEj5WS:-NFG1iXq7GcKvC4xW6sa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/004f4445fd509b2fe28f93aa626af56421e9fc56/pkg/ui/workspaces/cluster-ui/src/tracez/snapshot/snapshotPage.tsx#L97)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

if we can lift the `parseInt`s out of these functions, I think that'd be good.
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/db-console/src/app.spec.tsx` line 502 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90244#-NFA6CXXCSGa4TWZPd6y:-NFG1jnF9fzrVUCa7IKl:bisnvsl) ([raw file](https://github.com/cockroachdb/cockroach/blob/004f4445fd509b2fe28f93aa626af56421e9fc56/pkg/ui/workspaces/db-console/src/app.spec.tsx#L502)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

is this "ScheduleDetails" right?
</blockquote></details>

nope! fixed :)

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90244)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @benbardin, @dhartunian, and @sjbarag)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/statusApi.ts` line 13 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90244#-NFKQBEg6HtRPZlwhRoq:-NFKQBEg6HtRPZlwhRor:brbpitw) ([raw file](https://github.com/cockroachdb/cockroach/blob/81ff6c9ef373ff5b10cf9ddcbb060099136af52a/pkg/ui/workspaces/cluster-ui/src/api/statusApi.ts#L13)):*
> ```XML
> import { cockroach } from "@cockroachlabs/crdb-protobuf-client";
> import { fetchData } from "src/api";
> import NodeRequestMessage = cockroach.server.serverpb.NodeRequest;
> ```

is suffixing such imports with `Message` a usual thing to do?
___
*[`pkg/ui/workspaces/cluster-ui/src/api/statusApi.ts` line 19 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90244#-NFKQuPY3PJFBFy3ZAD6:-NFKQuPY3PJFBFy3ZAD7:b-69hbwn) ([raw file](https://github.com/cockroachdb/cockroach/blob/81ff6c9ef373ff5b10cf9ddcbb060099136af52a/pkg/ui/workspaces/cluster-ui/src/api/statusApi.ts#L19)):*
> ```XML
> 
> export function getNodeUI(
>   nodeID: string, // String to support `local`
> ```

we always pass "local" for this param. Let's get rid of it. Also see below.
___
*[`pkg/ui/workspaces/cluster-ui/src/api/statusApi.ts` line 26 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90244#-NFKUdiZ1pDWhkjx9aJ_:-NFKUdiZ1pDWhkjx9aJa:bq22167) ([raw file](https://github.com/cockroachdb/cockroach/blob/81ff6c9ef373ff5b10cf9ddcbb060099136af52a/pkg/ui/workspaces/cluster-ui/src/api/statusApi.ts#L26)):*
> ```XML
>   return fetchData(
>     NodeResponseMessage,
>     `${STATUS_PREFIX}/nodes_ui/${nodeID}`,
> ```

Instead of this `nodes_ui` endpoint, can we use [this thing](https://github.com/cockroachdb/cockroach/blob/ca31896ec6e3e6a1e88a38b669d9c310acc54c76/pkg/ui/workspaces/db-console/src/views/reports/containers/debug/index.tsx#L247)? Seems much lighter weight; I believe it doesn't involve any RPCs (i.e. the ID of the node that served the page is embedded into the page source somehow).

In fact, I think the way to go is to reuse the [`NodeIDSelector`](https://github.com/cockroachdb/cockroach/blob/ca31896ec6e3e6a1e88a38b669d9c310acc54c76/pkg/ui/workspaces/db-console/src/views/reports/containers/debug/index.tsx#L114) component that we already have (and `NodeIDSelectorConnected` also?). We don't want the selector setting any cookies, like it does on the Advanced Debug page, but I think that part is already factored out.
The concerns about the page working when the list of nodes cannot be retrieved still apply - hopefully that component doesn't behave badly or we can make it not behave badly.
FWIW, I've asked @dhartunian about reusing that component, and he seems to support it. Let's get him on the review too.
___
*[`pkg/ui/workspaces/cluster-ui/src/api/tracezApi.ts` line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90244#-NFKXTW4Anm3yKWfK6Vi:-NFKXTW4Anm3yKWfK6Vj:b-g1hpkp) ([raw file](https://github.com/cockroachdb/cockroach/blob/81ff6c9ef373ff5b10cf9ddcbb060099136af52a/pkg/ui/workspaces/cluster-ui/src/api/tracezApi.ts#L43)):*
> ```XML
>     // "local," it still queries gossip while doing it. We'd like to avoid a hard dependency
>     // on that to support malfunctioning clusters or nodes.
>     return path;
> ```

I'm curious to see what this gossip reference is about. I've very superficially traced what I think is the relevant code to [here](https://github.com/cockroachdb/cockroach/blob/0bbe280a83ef2b20f5b17a2df76c5f208ee126d5/pkg/server/status.go#L619), and it looks to me like, gossip or no gossip, a `"local"` value for the nodeID turns into a `true` return from that function, which I'd hope makes everything just work.
___
*[`pkg/ui/workspaces/cluster-ui/src/api/tracezApi.ts` line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90244#-NFKnTZbAL_mOUxTJzKg:-NFKnTZbAL_mOUxTJzKh:b-6ulid4) ([raw file](https://github.com/cockroachdb/cockroach/blob/81ff6c9ef373ff5b10cf9ddcbb060099136af52a/pkg/ui/workspaces/cluster-ui/src/api/tracezApi.ts#L45)):*
> ```XML
>     return path;
>   }
>   return path + `?remote_node_id=${nodeID}`;
> ```

Clever use of `?remote_node_id`.
___
*[`pkg/ui/workspaces/cluster-ui/src/api/tracezApi.ts` line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90244#-NFKn10GDceZrS8PCzAw:-NFKn10GDceZrS8PCzAx:by27em7) ([raw file](https://github.com/cockroachdb/cockroach/blob/81ff6c9ef373ff5b10cf9ddcbb060099136af52a/pkg/ui/workspaces/cluster-ui/src/api/tracezApi.ts#L53)):*
> ```XML
>   return fetchData(
>     cockroach.server.serverpb.ListTracingSnapshotsResponse,
>     proxyNonLocalNode(`${API_PREFIX}/trace_snapshots`, nodeID),
> ```

instead of munging all the URLs yourself, I'd vote we push the ability to add the magic arg inside `fetchData`.

**Review by benbardin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90244)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @andreimatei, @dhartunian, and @sjbarag)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/statusApi.ts` line 13 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90244#-NFKQBEg6HtRPZlwhRoq:-NFPEPK5AXdnWSDRY9NZ:b-utryu2) ([raw file](https://github.com/cockroachdb/cockroach/blob/81ff6c9ef373ff5b10cf9ddcbb060099136af52a/pkg/ui/workspaces/cluster-ui/src/api/statusApi.ts#L13)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

is suffixing such imports with `Message` a usual thing to do?
</blockquote></details>

no, turns out! We do it in tracezApi, perhaps it's more common in db-console. But I'll remove that there too.
___
*[`pkg/ui/workspaces/cluster-ui/src/api/statusApi.ts` line 19 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90244#-NFKQuPY3PJFBFy3ZAD6:-NFPwBIL0sXNaL4nF_Ag:b-x2lx9g) ([raw file](https://github.com/cockroachdb/cockroach/blob/81ff6c9ef373ff5b10cf9ddcbb060099136af52a/pkg/ui/workspaces/cluster-ui/src/api/statusApi.ts#L19)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

we always pass "local" for this param. Let's get rid of it. Also see below.
</blockquote></details>

removing the file!
___
*[`pkg/ui/workspaces/cluster-ui/src/api/statusApi.ts` line 26 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90244#-NFKUdiZ1pDWhkjx9aJ_:-NFPvNFbB0h_UJ__Q2io:bmhyih0) ([raw file](https://github.com/cockroachdb/cockroach/blob/81ff6c9ef373ff5b10cf9ddcbb060099136af52a/pkg/ui/workspaces/cluster-ui/src/api/statusApi.ts#L26)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Instead of this `nodes_ui` endpoint, can we use [this thing](https://github.com/cockroachdb/cockroach/blob/ca31896ec6e3e6a1e88a38b669d9c310acc54c76/pkg/ui/workspaces/db-console/src/views/reports/containers/debug/index.tsx#L247)? Seems much lighter weight; I believe it doesn't involve any RPCs (i.e. the ID of the node that served the page is embedded into the page source somehow).

In fact, I think the way to go is to reuse the [`NodeIDSelector`](https://github.com/cockroachdb/cockroach/blob/ca31896ec6e3e6a1e88a38b669d9c310acc54c76/pkg/ui/workspaces/db-console/src/views/reports/containers/debug/index.tsx#L114) component that we already have (and `NodeIDSelectorConnected` also?). We don't want the selector setting any cookies, like it does on the Advanced Debug page, but I think that part is already factored out.
The concerns about the page working when the list of nodes cannot be retrieved still apply - hopefully that component doesn't behave badly or we can make it not behave badly.
FWIW, I've asked @dhartunian about reusing that component, and he seems to support it. Let's get him on the review too.
</blockquote></details>

Oh, dataFromServer is perfect here, thanks!

Using NodeIDSelector doesn't sit quite right with me - it's in db-console, not cluster-ui, so I'd have to move it; the current dropdown using the appropriate design language off the bat; and I'm not sure we'll actually be using this very often (maybe if we expand /debug functionality a ton it'd make sense? but we're not there yet.) Curious to hear what David thinks, I'll ping him!
___
*[`pkg/ui/workspaces/cluster-ui/src/api/tracezApi.ts` line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90244#-NFKXTW4Anm3yKWfK6Vi:-NFPw3D8E-ej9P3Bnovd:b-ukndf0) ([raw file](https://github.com/cockroachdb/cockroach/blob/81ff6c9ef373ff5b10cf9ddcbb060099136af52a/pkg/ui/workspaces/cluster-ui/src/api/tracezApi.ts#L43)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'm curious to see what this gossip reference is about. I've very superficially traced what I think is the relevant code to [here](https://github.com/cockroachdb/cockroach/blob/0bbe280a83ef2b20f5b17a2df76c5f208ee126d5/pkg/server/status.go#L619), and it looks to me like, gossip or no gossip, a `"local"` value for the nodeID turns into a `true` return from that function, which I'd hope makes everything just work.
</blockquote></details>

Yup, you're right! I saw Gossip.Get and assumed it did something RPC-like, but it's just wrapping a value with proto.
___
*[`pkg/ui/workspaces/cluster-ui/src/api/tracezApi.ts` line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90244#-NFKnTZbAL_mOUxTJzKg:-NFPw8ns55KxhF8r1nTS:b-9755fn) ([raw file](https://github.com/cockroachdb/cockroach/blob/81ff6c9ef373ff5b10cf9ddcbb060099136af52a/pkg/ui/workspaces/cluster-ui/src/api/tracezApi.ts#L45)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Clever use of `?remote_node_id`.
</blockquote></details>

Thank you!
___
*[`pkg/ui/workspaces/cluster-ui/src/api/tracezApi.ts` line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90244#-NFKn10GDceZrS8PCzAw:-NFUT5Ng0N47N3jflEKa:biqx5ch) ([raw file](https://github.com/cockroachdb/cockroach/blob/81ff6c9ef373ff5b10cf9ddcbb060099136af52a/pkg/ui/workspaces/cluster-ui/src/api/tracezApi.ts#L53)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

instead of munging all the URLs yourself, I'd vote we push the ability to add the magic arg inside `fetchData`.
</blockquote></details>

Yeah, I see what you mean, but I'm not sure I see how to do that smoothly. The challenge I'm not sure how to handle, is that `fetchData()` already takes a bunch of arguments:

```
export const fetchData = <P extends ProtoBuilder<P>, T extends ProtoBuilder<T>>(
  RespBuilder: T,
  path: string,
  ReqBuilder?: P,
  reqPayload?: FirstConstructorParameter<P>,
  timeout?: string,
): Promise<InstanceType<T>>
```

This leads to some silly-looking calls like 
```
src/api/statementsApi.ts
40:  return fetchData(
41-    cockroach.server.serverpb.StatementsResponse,
42-    `${STATEMENTS_PATH}?${queryStr}`,
43-    null,
44-    null,
45-    "30M",
```

By the numbers, `fetchData()` has 20 uses. Of those 20, 13 have no query params. Of the 7 that do, 4 are in this new tracezApi, and 3 are elsewhere (in `statementsApi.ts` and `jobsApi.ts`).

The usability hit from requiring a _third_ null for `fetchData()` calls 65% of the time, seems more important to me than the usability gain from supporting query params 35% of the time. But reasonable people can disagree, or perhaps you just see something I've missed? What do you think?

**Review by andreimatei — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90244#-:-NFj6MJq1Wvjs0zrY9Zb:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @benbardin, @dhartunian, and @sjbarag)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/tracezApi.ts` line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90244#-NFKXTW4Anm3yKWfK6Vi:-NFiwTp2-V2BRPqnJvZG:b5126do) ([raw file](https://github.com/cockroachdb/cockroach/blob/81ff6c9ef373ff5b10cf9ddcbb060099136af52a/pkg/ui/workspaces/cluster-ui/src/api/tracezApi.ts#L43)):*
<details><summary><i>Previously, benbardin (Ben Bardin) wrote…</i></summary><blockquote>

Yup, you're right! I saw Gossip.Get and assumed it did something RPC-like, but it's just wrapping a value with proto.
</blockquote></details>

then this comment needs adjustment, right?
___
*[`pkg/ui/workspaces/cluster-ui/src/api/tracezApi.ts` line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90244#-NFKn10GDceZrS8PCzAw:-NFiweDN8CXdAxZnvHqF:b18103q) ([raw file](https://github.com/cockroachdb/cockroach/blob/81ff6c9ef373ff5b10cf9ddcbb060099136af52a/pkg/ui/workspaces/cluster-ui/src/api/tracezApi.ts#L53)):*
<details><summary><i>Previously, benbardin (Ben Bardin) wrote…</i></summary><blockquote>

Yeah, I see what you mean, but I'm not sure I see how to do that smoothly. The challenge I'm not sure how to handle, is that `fetchData()` already takes a bunch of arguments:

```
export const fetchData = <P extends ProtoBuilder<P>, T extends ProtoBuilder<T>>(
  RespBuilder: T,
  path: string,
  ReqBuilder?: P,
  reqPayload?: FirstConstructorParameter<P>,
  timeout?: string,
): Promise<InstanceType<T>>
```

This leads to some silly-looking calls like 
```
src/api/statementsApi.ts
40:  return fetchData(
41-    cockroach.server.serverpb.StatementsResponse,
42-    `${STATEMENTS_PATH}?${queryStr}`,
43-    null,
44-    null,
45-    "30M",
```

By the numbers, `fetchData()` has 20 uses. Of those 20, 13 have no query params. Of the 7 that do, 4 are in this new tracezApi, and 3 are elsewhere (in `statementsApi.ts` and `jobsApi.ts`).

The usability hit from requiring a _third_ null for `fetchData()` calls 65% of the time, seems more important to me than the usability gain from supporting query params 35% of the time. But reasonable people can disagree, or perhaps you just see something I've missed? What do you think?
</blockquote></details>

I'd introduce a `fetchDataEx()` that groups all the optional args in a struct. 
___
*[`pkg/ui/workspaces/cluster-ui/src/tracez/snapshot/snapshotPage.tsx` line 87 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90244#-NFixyWI8yTURmG5Uvf3:-NFixyWI8yTURmG5Uvf4:bf6hzsa) ([raw file](https://github.com/cockroachdb/cockroach/blob/4be86670e9850c021991e6471889c010bdd01f3d/pkg/ui/workspaces/cluster-ui/src/tracez/snapshot/snapshotPage.tsx#L87)):*
> ```XML
>   const columnTitle = match.params.columnTitle || "";
> 
>   const snapshotIDStr = getMatchParamByName(match, "snapshotID");
> ```

do we need this variable? If possible, I think it'd be nicer if we dealt only with `snapshotID` in int form.
___
*[`pkg/ui/workspaces/cluster-ui/src/tracez/snapshot/snapshotPage.tsx` line 118 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90244#-NFj6-FT6QZFkMTKTyVv:-NFj6-FT6QZFkMTKTyVw:b-dkeibb) ([raw file](https://github.com/cockroachdb/cockroach/blob/4be86670e9850c021991e6471889c010bdd01f3d/pkg/ui/workspaces/cluster-ui/src/tracez/snapshot/snapshotPage.tsx#L118)):*
> ```XML
> 
>   // If no node was provided, navigate to the default if provided, or the first.
>   useEffect(() => {
> ```

any change we can combine this and the next effect into one?
___
*[`pkg/ui/workspaces/cluster-ui/src/tracez/snapshot/snapshotPage.tsx` line 126 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90244#-NFiydslEWednX007Jin:-NFiydslEWednX007Jio:b-lc1quz) ([raw file](https://github.com/cockroachdb/cockroach/blob/4be86670e9850c021991e6471889c010bdd01f3d/pkg/ui/workspaces/cluster-ui/src/tracez/snapshot/snapshotPage.tsx#L126)):*
> ```XML
>       targetNodeID = "local";
>     }
>     console.log(targetNodeID);
> ```

get rid of this

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90244)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @andreimatei, @benbardin, and @sjbarag)

___
*[`pkg/ui/workspaces/cluster-ui/src/tracez/snapshot/snapshotPage.tsx` line 139 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90244#-NFj-y8U9TFcG48gnFRF:-NFj-y8V0Sfoo5pI8wft:b-j4ujma) ([raw file](https://github.com/cockroachdb/cockroach/blob/4be86670e9850c021991e6471889c010bdd01f3d/pkg/ui/workspaces/cluster-ui/src/tracez/snapshot/snapshotPage.tsx#L139)):*
> ```XML
>     history.location.pathname =
>       "/debug/tracez_v2/node/" + nodeID + "/snapshot/" + lastSnapshotID;
>     history.replace(history.location);
> ```

can we merge the two `useEffect` calls that modify the `pathname`? I'd be worried about a double refresh or either of them clobbering each others work.
___
*[`pkg/ui/workspaces/cluster-ui/src/tracez/snapshot/snapshotPage.tsx` line 177 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90244#-NFjOnvbEyNo-JH9pOFk:-NFjOnvbEyNo-JH9pOFl:b-myjkeq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4be86670e9850c021991e6471889c010bdd01f3d/pkg/ui/workspaces/cluster-ui/src/tracez/snapshot/snapshotPage.tsx#L177)):*
> ```XML
>       // Load the new snapshot.
>       history.location.pathname =
>         "/debug/tracez_v2/node/" +
> ```

can the base path you're using everywhere be derived from the router props? then maybe the page is resilient to base URL changes.

**Review by benbardin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90244)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @andreimatei, @dhartunian, and @sjbarag)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/tracezApi.ts` line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90244#-NFKXTW4Anm3yKWfK6Vi:-NGNqvIB2QRYu5MAT1Cl:b6ns588) ([raw file](https://github.com/cockroachdb/cockroach/blob/81ff6c9ef373ff5b10cf9ddcbb060099136af52a/pkg/ui/workspaces/cluster-ui/src/api/tracezApi.ts#L43)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

then this comment needs adjustment, right?
</blockquote></details>

Yes, and better, the whole thing can go away!
___
*[`pkg/ui/workspaces/cluster-ui/src/api/tracezApi.ts` line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90244#-NFKn10GDceZrS8PCzAw:-NGSCLwF5xgUudQR2-pO:b-9vov1x) ([raw file](https://github.com/cockroachdb/cockroach/blob/81ff6c9ef373ff5b10cf9ddcbb060099136af52a/pkg/ui/workspaces/cluster-ui/src/api/tracezApi.ts#L53)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'd introduce a `fetchDataEx()` that groups all the optional args in a struct. 
</blockquote></details>

Ah, gotcha. With the updated proxying arg I think that's _probably_ not worth it right now, but if I keep running into it I can make that upgrade.
___
*[`pkg/ui/workspaces/cluster-ui/src/tracez/snapshot/snapshotPage.tsx` line 87 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90244#-NFixyWI8yTURmG5Uvf3:-NGNKFAEEk-P1MuGzQbM:b-pnzgk6) ([raw file](https://github.com/cockroachdb/cockroach/blob/4be86670e9850c021991e6471889c010bdd01f3d/pkg/ui/workspaces/cluster-ui/src/tracez/snapshot/snapshotPage.tsx#L87)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

do we need this variable? If possible, I think it'd be nicer if we dealt only with `snapshotID` in int form.
</blockquote></details>

Yup, good idea!
___
*[`pkg/ui/workspaces/cluster-ui/src/tracez/snapshot/snapshotPage.tsx` line 118 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90244#-NFj6-FT6QZFkMTKTyVv:-NGNOV_o1IOwuLTzO1_W:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4be86670e9850c021991e6471889c010bdd01f3d/pkg/ui/workspaces/cluster-ui/src/tracez/snapshot/snapshotPage.tsx#L118)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

any change we can combine this and the next effect into one?
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/tracez/snapshot/snapshotPage.tsx` line 126 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90244#-NFiydslEWednX007Jin:-NGNN3pKBf2tSm3MU3Q3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4be86670e9850c021991e6471889c010bdd01f3d/pkg/ui/workspaces/cluster-ui/src/tracez/snapshot/snapshotPage.tsx#L126)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

get rid of this
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/tracez/snapshot/snapshotPage.tsx` line 139 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90244#-NFj-y8U9TFcG48gnFRF:-NGNOUxo63IeLsbF7IW4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4be86670e9850c021991e6471889c010bdd01f3d/pkg/ui/workspaces/cluster-ui/src/tracez/snapshot/snapshotPage.tsx#L139)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

can we merge the two `useEffect` calls that modify the `pathname`? I'd be worried about a double refresh or either of them clobbering each others work.
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/tracez/snapshot/snapshotPage.tsx` line 177 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/90244#-NFjOnvbEyNo-JH9pOFk:-NGNql8W7iTa8tUH5DAi:b-bczox2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4be86670e9850c021991e6471889c010bdd01f3d/pkg/ui/workspaces/cluster-ui/src/tracez/snapshot/snapshotPage.tsx#L177)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

can the base path you're using everywhere be derived from the router props? then maybe the page is resilient to base URL changes.
</blockquote></details>

discussed offline - yes, but we'd have to move the route structure into this component. We don't use that pattern elsewhere (though we probably should!) so considered out of scope for now.

**Review by dhartunian — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90244#-:-NGqxcH_DW7ZCHV8D_gL:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @andreimatei, and @sjbarag)

**Comment by benbardin** [comment]
bors cancel

**Comment by rail** [comment]
bors ping

**Pull request merged**
