### PR TITLE
sql: point spans should never include interleaves

### LINKED ISSUE #33326: sql: foreign key lookup spans are too wide, including child interleaves
Foreign key checks emit a scan request on the foreign table to check whether or not the foreign key prefix is present.

Today, the span emitted for the scan request is too wide. It includes child interleaves. This is inefficient: more data will be fetched than necessary, and a larger span will be added to the latch manager, resulting in more transaction retries than necessary.

This should be fixed by teaching the foreign key span emitted to only emit a span that's precise, without including the child interleave.

Additionally, the foreign key checker should be enhanced to include kv tracing to make debugging stuff like this easier in the future.

### LINKED ISSUE #33330: sql: upsert lookup spans are too wide, including child interleaves
Similar to #33326, UPSERT produces lookup spans that include child interleaves by accident.

```
root@127.0.0.1:62359/defaultdb> create table a (a int primary key);
CREATE TABLE

Time: 6.245ms

root@127.0.0.1:62359/defaultdb> create table b (a int, b int, primary key(a,b)) interleave in parent a(a);
CREATE TABLE

Time: 15.043ms

root@127.0.0.1:62359/defaultdb> \set auto_trace=on,kv

root@127.0.0.1:62359/defaultdb> upsert into a values(2) returning *;
  a
+---+
(0 rows)

Time: 1.434ms

             timestamp             |       age       |                message                 |                        tag                         | location |    operation     | span
+----------------------------------+-----------------+----------------------------------------+----------------------------------------------------+----------+------------------+------+
  2018-12-21 19:43:25.319905+00:00 | 00:00:00.000828 | Scan /Table/52/1/{2-3}                 | [n1,client=127.0.0.1:62361,user=root]              |          | flow             |    3
  2018-12-21 19:43:25.319953+00:00 | 00:00:00.000876 | querying next range at /Table/52/1/2   | [n1,client=127.0.0.1:62361,user=root,txn=ef5e9b68] |          | dist sender send |    5
  2018-12-21 19:43:25.319996+00:00 | 00:00:00.000919 | r21: sending batch 1 Scan to (n1,s1):1 | [n1,client=127.0.0.1:62361,user=root,txn=ef5e9b68] |          | dist sender send |    5
  2018-12-21 19:43:25.320327+00:00 | 00:00:00.00125  | fetched: /a/primary/2 -> NULL          | [n1,client=127.0.0.1:62361,user=root]              |          | flow             |    3
  2018-12-21 19:43:25.320371+00:00 | 00:00:00.001294 | rows affected: 0                       | [n1,client=127.0.0.1:62361,user=root]              |          | sql txn          |    1
```

### LINKED ISSUE #33347: sql: index and lookup join spans are too wide, including interleave children
```
root@127.0.0.1:58662/defaultdb> create table a (a int primary key, b int, c int, index(b));
CREATE TABLE

Time: 6.676ms

root@127.0.0.1:58662/defaultdb> insert into a values(1,2,3);                                                                                                                                                INSERT 1

Time: 7.574ms

root@127.0.0.1:58662/defaultdb> \set auto_trace=on,kv
root@127.0.0.1:58662/defaultdb> select * from a where b=2;                                                                                                                                                    a | b | c
+---+---+---+
  1 | 2 | 3
(1 row)

Time: 1.504ms

             timestamp             |       age       |                message                 |                        tag                         | location |    operation     | span
+----------------------------------+-----------------+----------------------------------------+----------------------------------------------------+----------+------------------+------+
  2018-12-24 15:59:00.121441+00:00 | 00:00:00.000671 | Scan /Table/53/2/{2-3}                 | [n1,client=127.0.0.1:58664,user=root]              |          | table reader     |    4
  2018-12-24 15:59:00.121489+00:00 | 00:00:00.000719 | querying next range at /Table/53/2/2   | [n1,client=127.0.0.1:58664,user=root,txn=ffa8ce30] |          | dist sender send |    6
  2018-12-24 15:59:00.121525+00:00 | 00:00:00.000755 | r22: sending batch 1 Scan to (n1,s1):1 | [n1,client=127.0.0.1:58664,user=root,txn=ffa8ce30] |          | dist sender send |    6
  2018-12-24 15:59:00.121756+00:00 | 00:00:00.000986 | fetched: /a/a_b_idx/2/1 -> NULL        | [n1,client=127.0.0.1:58664,user=root]              |          | table reader     |    4
  2018-12-24 15:59:00.121852+00:00 | 00:00:00.001082 | Scan /Table/53/1/{1-2}                 | [n1,client=127.0.0.1:58664,user=root]              |          | index joiner     |    8
  2018-12-24 15:59:00.121883+00:00 | 00:00:00.001113 | querying next range at /Table/53/1/1   | [n1,client=127.0.0.1:58664,user=root,txn=ffa8ce30] |          | dist sender send |   10
  2018-12-24 15:59:00.121907+00:00 | 00:00:00.001137 | r22: sending batch 1 Scan to (n1,s1):1 | [n1,client=127.0.0.1:58664,user=root,txn=ffa8ce30] |          | dist sender send |   10
  2018-12-24 15:59:00.122061+00:00 | 00:00:00.001291 | fetched: /a/primary/1/b/c -> /2/3      | [n1,client=127.0.0.1:58664,user=root]              |          | flow             |    3
  2018-12-24 15:59:00.122147+00:00 | 00:00:00.001377 | rows affected: 1                       | [n1,client=127.0.0.1:58664,user=root]              |          | sql txn          |    1
(9 rows)
```

### PR DESCRIPTION
**Pull request by jordanlewis**
Closes #33347.
Closes #33326.
Closes #33330.

Previously, many sql processors that needed to generate spans for key
lookups unconditionally used the PrefixEnd method on the key to look up
to get the end of the keyspan. While correct, this generated span is
wide enough to contain all child interleaves of a table on that key, if
they exist. This is very bad for performance, causing "point scans" to
accidentally need to scan through an entire interleaves if it exists.

Now, code is adjusted to use spans that are bounded on the right by the
interleave marker appended to the start key, if the index to look up in
is unique and fully specified. Note that the condition chosen is broader
than strictly necessary - we only insert interleaves today into primary
indexes, and we could tighten the condition to only emit an interleave
marker if the index does in fact have interleaves - but keeping the
condition simple makes things easier to test and provides a modicum of
assurance that this hairy code won't have to change again if we decide
to permit interleaving tables or indexes into other unique, non primary
indexes later.

New helper methods were introduced that permit retrieval of the key span
for a set of key values, and not just the key itself, in the hopes that
future code won't commit the same sins.

```
name                                      old time/op    new time/op    delta
SQL/Cockroach/InterleavedFK/count=1-8        790µs ± 9%     515µs ± 8%  -34.77%  (p=0.000 n=10+10)
SQL/Cockroach/InterleavedFK/count=10-8      6.53ms ± 7%    1.32ms ± 5%  -79.79%  (p=0.000 n=10+10)
SQL/Cockroach/InterleavedFK/count=100-8     65.1ms ±10%     9.7ms ±14%  -85.16%  (p=0.000 n=10+10)
SQL/Cockroach/InterleavedFK/count=1000-8     565ms ± 8%     102ms ±11%  -81.99%  (p=0.000 n=10+10)

name                                      old alloc/op   new alloc/op   delta
SQL/Cockroach/InterleavedFK/count=1-8        158kB ± 2%      54kB ± 6%  -65.89%  (p=0.000 n=10+10)
SQL/Cockroach/InterleavedFK/count=10-8      2.72MB ± 1%    0.14MB ± 1%  -94.88%  (p=0.000 n=10+9)
SQL/Cockroach/InterleavedFK/count=100-8     26.8MB ± 1%     1.0MB ± 7%  -96.17%  (p=0.000 n=10+8)
SQL/Cockroach/InterleavedFK/count=1000-8     222MB ± 1%      11MB ± 6%  -94.95%  (p=0.000 n=10+9)

name                                      old allocs/op  new allocs/op  delta
SQL/Cockroach/InterleavedFK/count=1-8          515 ± 2%       508 ± 3%     ~     (p=0.195 n=10+10)
SQL/Cockroach/InterleavedFK/count=10-8       1.64k ±20%     1.33k ± 1%  -18.59%  (p=0.000 n=10+9)
SQL/Cockroach/InterleavedFK/count=100-8      14.2k ±12%     10.0k ±15%  -29.25%  (p=0.000 n=10+9)
SQL/Cockroach/InterleavedFK/count=1000-8      129k ±16%      102k ± 7%  -21.07%  (p=0.000 n=10+9)
```

Release note (performance improvement): index joins, lookup joins,
foreign key checks, cascade scans, zig zag joins, and upserts no longer
needlessly scan over child interleaved tables when searching for keys.

### CODE REVIEW

**Comment by knz** [comment]
The gist of this LGTM, but it's a bit out of my league. You'll need to talk me through this before I can review in detail.

However already one comment: the release note should highlight that this optimization only applies to unique indexes (incl PKs) and that non-unique indices, if interleaved, will still see the worse performance.

Also I would recommend adding a benchmark that shows both cases: the before/after speedup on unique indexes, and the unique/non-unique comparison (of a scan over interleave parent) after this PR.

**Comment by jordanlewis** [comment]
> You'll need to talk me through this before I can review in detail.

Here's the gist: before interleaved indexes, it was totally valid to construct a key span for a particular key in an index (say `/foo/1`) by taking the `PrefixEnd` (which just increments the key as it would an integer) of the key and using that as the end key of the span. So you'd get a span`foo/1 -> foo/2`. In the code, it was supposed for a long time that this transformation would be sufficient to get the "minimal keyspan" for a key - a span that contains as few keys as possible including the one being searched for.

But in a world with interleaves, this is no longer the case, because there can be tables (and keys) that begin with the input key that aren't even in the part of the same table. So if there was an interleaved table below our example key, it might have keys:

```
/foo/1/
/foo/1/#/80/1/bar
/foo/1/#/80/1/baz
```

and so on. And our original key span `/foo/1/ -> /foo/2/` would now include all of those other keys!

Some codepaths were changed after interleaves were introduced to not have this problem. Direct SQL index lookups for example do the correct thing. But not all code paths! Foreign key lookups, cascade lookups, index join lookups, lookup join lookups, zig zag join lookups, and upsert lookups for existing keys all were using the `PrefixEnd` method of calculating their span's end key. So each of these lookups would be very slow if performed on a parent interleave with interleaved rows.

> However already one comment: the release note should highlight that this optimization only applies to unique indexes (incl PKs) and that non-unique indices, if interleaved, will still see the worse performance.

You can't interleave tables or indexes into anything except for primary indexes. In the future, you may be able to interleave into secondary, unique indexes. But there's no conceptual mapping for interleaving into a non-unique index.

> Also I would recommend adding a benchmark that shows both cases: the before/after speedup on unique indexes, and the unique/non-unique comparison (of a scan over interleave parent) after this PR.

Ehh... this changes the number of keys scanned from O(n) to linear, so you can make the benchmark look like however you want.

**Review by knz — COMMENTED** [review]
Thank you for your explanation.

>> However already one comment: the release note should highlight that this optimization only applies to unique indexes (incl PKs) and that non-unique indices, if interleaved, will still see the worse performance.
 
> You can't interleave tables or indexes into anything except for primary indexes. In the future, you may be able to interleave into secondary, unique indexes. But there's no conceptual mapping for interleaving into a non-unique index.

My test says this is incorrect:
```
root@127.0.0.1:63436/defaultdb> create table t(x int);
CREATE TABLE

Time: 2.563248ms

root@127.0.0.1:63436/defaultdb> create table u(x int primary key);
CREATE TABLE

Time: 3.136705ms

root@127.0.0.1:63436/defaultdb> create index on t(x) interleave in parent u(x);
CREATE INDEX

Time: 76.346498ms

root@127.0.0.1:63436/defaultdb> show create t;
  table_name |                   create_statement
+------------+-------------------------------------------------------+
  t          | CREATE TABLE t (
             |     x INT8 NULL,
             |     INDEX t_x_idx (x ASC) INTERLEAVE IN PARENT u (x),
             |     FAMILY "primary" (x, rowid)
             | )
(1 row)

Time: 2.802364ms
```


> > Also I would recommend adding a benchmark that shows both cases: the before/after speedup on unique indexes, and the unique/non-unique comparison (of a scan over interleave parent) after this PR.

> Ehh... this changes the number of keys scanned from O(n) to linear, so you can make the benchmark look like however you want.

The proper phrasing reveals what I mean: "this changes the number of keys scanned from O(n) to O(1) where n is the number of interleaved children". I am interested in the behavior when n=0 and n=1. What is the change in the constant? 

1) in the case when n=0 your patch may cause a small slowdown, I am not sure. I want to check that.
2) in the case when n=1 there is a speedup in that case thanks to your change. A benchmark would demonstrate that.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33350#-:-LVDKt041j31RJg1txY-:b-nuxmd3)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by knz — COMMENTED** [review]
> You can't interleave tables or indexes into anything except for primary indexes. In the future, you may be able to interleave into secondary, unique indexes. But there's no conceptual mapping for interleaving into a non-unique index.

Coming back to this: I misunderstood. The parent has to be a PK; the child can be table or index. I stand corrected. However a comment needs adjusting, see below.

> Reviewed 3 of 3 files at r1, 13 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33350#-:-LVDMpTh9h4M8Fh7n4PT:bo89he9)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sqlbase/index_encoding.go, line 227 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33350#-LVDMwkv31kI4Nf51aB_:-LVDMwkv31kI4Nf51aBa:b-ue7itw) ([raw file](https://github.com/cockroachdb/cockroach/blob/7742f491b5e12563e285cd98089498285aa2a0d2/pkg/sql/sqlbase/index_encoding.go#L227)):*
> ```Go
> 		// any child interleaves of the input key.
> 		//
> 		// Note that currently only primary indexes can contain interleaved tables,
> ```

interleaved tables or indexes.
___
*[pkg/sql/sqlbase/index_encoding.go, line 229 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33350#-LVDMyxU8gO1nCNoUhSQ:-LVDMyxU8gO1nCNoUhSR:b-svt4i4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7742f491b5e12563e285cd98089498285aa2a0d2/pkg/sql/sqlbase/index_encoding.go#L229)):*
> ```Go
> 		// Note that currently only primary indexes can contain interleaved tables,
> 		// so this condition is broader than necessary in case one day we permit
> 		// interleaving into unique indexes. Note also that we could precisely only
> ```

into arbitrary unique indexes.

**Comment by knz** [comment]
Also you can perhaps rebase this on top of #33320 to catch the strict upserter fix in there.

**Review by jordanlewis — COMMENTED** [review]
```
name                                      old time/op    new time/op    delta
SQL/Cockroach/InterleavedFK/count=1-8        790µs ± 9%     515µs ± 8%  -34.77%  (p=0.000 n=10+10)
SQL/Cockroach/InterleavedFK/count=10-8      6.53ms ± 7%    1.32ms ± 5%  -79.79%  (p=0.000 n=10+10)
SQL/Cockroach/InterleavedFK/count=100-8     65.1ms ±10%     9.7ms ±14%  -85.16%  (p=0.000 n=10+10)
SQL/Cockroach/InterleavedFK/count=1000-8     565ms ± 8%     102ms ±11%  -81.99%  (p=0.000 n=10+10)

name                                      old alloc/op   new alloc/op   delta
SQL/Cockroach/InterleavedFK/count=1-8        158kB ± 2%      54kB ± 6%  -65.89%  (p=0.000 n=10+10)
SQL/Cockroach/InterleavedFK/count=10-8      2.72MB ± 1%    0.14MB ± 1%  -94.88%  (p=0.000 n=10+9)
SQL/Cockroach/InterleavedFK/count=100-8     26.8MB ± 1%     1.0MB ± 7%  -96.17%  (p=0.000 n=10+8)
SQL/Cockroach/InterleavedFK/count=1000-8     222MB ± 1%      11MB ± 6%  -94.95%  (p=0.000 n=10+9)

name                                      old allocs/op  new allocs/op  delta
SQL/Cockroach/InterleavedFK/count=1-8          515 ± 2%       508 ± 3%     ~     (p=0.195 n=10+10)
SQL/Cockroach/InterleavedFK/count=10-8       1.64k ±20%     1.33k ± 1%  -18.59%  (p=0.000 n=10+9)
SQL/Cockroach/InterleavedFK/count=100-8      14.2k ±12%     10.0k ±15%  -29.25%  (p=0.000 n=10+9)
SQL/Cockroach/InterleavedFK/count=1000-8      129k ±16%      102k ± 7%  -21.07%  (p=0.000 n=10+9)
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33350#-:-LVFbeh4-qsmUAxYwAgk:b-f7e9rh)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sqlbase/index_encoding.go, line 227 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33350#-LVDMwkv31kI4Nf51aB_:-LVF5ajY8TN-udapnmSQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7742f491b5e12563e285cd98089498285aa2a0d2/pkg/sql/sqlbase/index_encoding.go#L227)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

interleaved tables or indexes.
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/index_encoding.go, line 229 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33350#-LVDMyxU8gO1nCNoUhSQ:-LVF5b5m7gb44yQFM8Nm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7742f491b5e12563e285cd98089498285aa2a0d2/pkg/sql/sqlbase/index_encoding.go#L229)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

into arbitrary unique indexes.
</blockquote></details>

Done.

**Review by knz — COMMENTED** [review]
I don't see the source code for BenchmarkInterleavedFK. Where is it?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33350#-:-LVFf9So6CRITFJ99kEt:b-uvklax)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by jordanlewis — COMMENTED** [review]
I forgot to upload it. Check again.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33350#-:-LVFbkq55f6L4IvXLKjz:b-6dshk2)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by knz — COMMENTED** [review]
> 1. in the case when n=0 your patch may cause a small slowdown, I am not sure. I want to check that.
> 2. in the case when n=1 there is a speedup in that case thanks to your change. A benchmark would demonstrate that.

Excellent benchmark for point 2. How have you verified what changed for point 1?

> Reviewed 1 of 1 files at r4, 13 of 13 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33350#-:-LVFgZWt-6Xa1f9562aI:b-487hap)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by jordanlewis — COMMENTED** [review]
> Excellent benchmark for point 2. How have you verified what changed for point 1?

No, and I will, but OOC are you just asking to be thorough or based on something you saw in the code? What overhead are you talking about? This changes some code to append a byte to a slice instead of incrementing the byte at the end of the slice. Are you suggesting that adding one append might produce a noticable slowdown?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33350#-:-LVFhMHa7q0mP0npH5CB:bdxthxi)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by knz** [comment]
> This changes some code to append a byte to a slice instead of incrementing the byte at the end of the slice. Are you suggesting that adding one append might produce a noticable slowdown?

Yes because it is possible that this changes the alloc profile.

If the evidence shows that indeed this happens, we can subsequently fix that by over-allocating the byte slices by 1 upfront.

**Review by jordanlewis — COMMENTED** [review]
```
name                                        old time/op    new time/op    delta
SQL/Cockroach/InsertFK/count=1/nFks=1-8        535µs ±11%     590µs ±18%    ~     (p=0.243 n=9+10)
SQL/Cockroach/InsertFK/count=10/nFks=1-8      1.74ms ±12%    1.77ms ± 8%    ~     (p=0.780 n=10+9)
SQL/Cockroach/InsertFK/count=100/nFks=1-8     14.1ms ± 4%    13.8ms ± 6%    ~     (p=0.278 n=9+10)
SQL/Cockroach/InsertFK/count=1000/nFks=1-8     142ms ± 6%     142ms ± 3%    ~     (p=0.156 n=9+10)

name                                        old alloc/op   new alloc/op   delta
SQL/Cockroach/InsertFK/count=1/nFks=1-8       50.8kB ± 0%    50.9kB ± 1%    ~     (p=0.423 n=9+8)
SQL/Cockroach/InsertFK/count=10/nFks=1-8       149kB ± 0%     149kB ± 0%    ~     (p=0.541 n=8+9)
SQL/Cockroach/InsertFK/count=100/nFks=1-8     1.09MB ± 1%    1.09MB ± 1%    ~     (p=0.574 n=8+8)
SQL/Cockroach/InsertFK/count=1000/nFks=1-8    12.2MB ± 1%    12.3MB ± 1%    ~     (p=0.606 n=8+9)

name                                        old allocs/op  new allocs/op  delta
SQL/Cockroach/InsertFK/count=1/nFks=1-8          472 ± 1%       475 ± 1%  +0.49%  (p=0.012 n=10+10)
SQL/Cockroach/InsertFK/count=10/nFks=1-8       1.30k ± 0%     1.32k ± 0%  +1.55%  (p=0.000 n=8+9)
SQL/Cockroach/InsertFK/count=100/nFks=1-8      9.32k ± 0%     9.52k ± 0%  +2.13%  (p=0.000 n=8+8)
SQL/Cockroach/InsertFK/count=1000/nFks=1-8     89.7k ± 1%     91.5k ± 1%  +2.02%  (p=0.000 n=9+9)
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33350#-:-LVFkdgb8jbyiQ2zuGg6:bd6lv5i)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by knz** [comment]
well then +2% allocs, what do we do about that? (I don't have opinions either way - but maybe @nvanbenschoten has thoughts)

**Comment by jordanlewis** [comment]
I could introduce a key size estimate integer to prevent repeat allocations. Currently we don't do anything of the kind - we just double the key prefix, which is completely arbitrary and more than likely usually gives us back a number between 4 and 8 bytes, which is likely insufficient for most applications...

**Comment by jordanlewis** [comment]
Even still, I'd argue the performance failure that this PR corrects is tens of times more egregious than 2% extra allocations, but idk

**Comment by jordanlewis** [comment]
I made the estimation mildly more clever/correct, which seems to have good results:

```
SQL/Cockroach/InsertFK/count=1/nFks=1-8        505µs ±11%     498µs ± 7%    ~     (p=0.353 n=10+10)
SQL/Cockroach/InsertFK/count=10/nFks=1-8      1.71ms ±12%    1.72ms ±10%    ~     (p=0.912 n=10+10)
SQL/Cockroach/InsertFK/count=100/nFks=1-8     13.8ms ± 7%    14.3ms ±12%    ~     (p=0.447 n=9+10)
SQL/Cockroach/InsertFK/count=1000/nFks=1-8     139ms ± 4%     146ms ±12%    ~     (p=0.280 n=10+10)

name                                        old alloc/op   new alloc/op   delta
SQL/Cockroach/InsertFK/count=1/nFks=1-8       50.9kB ± 1%    50.9kB ± 1%    ~     (p=1.000 n=10+10)
SQL/Cockroach/InsertFK/count=10/nFks=1-8       149kB ± 0%     151kB ± 3%    ~     (p=0.203 n=8+10)
SQL/Cockroach/InsertFK/count=100/nFks=1-8     1.09MB ± 1%    1.09MB ± 1%    ~     (p=0.258 n=9+9)
SQL/Cockroach/InsertFK/count=1000/nFks=1-8    12.2MB ± 1%    12.3MB ± 0%    ~     (p=0.400 n=9+10)

name                                        old allocs/op  new allocs/op  delta
SQL/Cockroach/InsertFK/count=1/nFks=1-8          472 ± 0%       471 ± 1%    ~     (p=0.793 n=10+10)
SQL/Cockroach/InsertFK/count=10/nFks=1-8       1.30k ± 0%     1.31k ± 1%    ~     (p=0.071 n=8+10)
SQL/Cockroach/InsertFK/count=100/nFks=1-8      9.31k ± 0%     9.32k ± 0%    ~     (p=0.196 n=9+9)
SQL/Cockroach/InsertFK/count=1000/nFks=1-8     89.6k ± 1%     90.0k ± 0%  +0.42%  (p=0.043 n=10+10)
```

**Review by knz — APPROVED** [review]
yay! :100:

**Review by jordanlewis — COMMENTED** [review]
Woo! TFTR.

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33350#-:-LVG-xYHCXH0H_VNa4aE:b-y8bbb6)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Pull request merged**
