### PR TITLE
roachtest: collect failure artifacts when restore fails

### PR DESCRIPTION
**Pull request by renatolabs**
This commit updates the `backup-restore/mixed-version` roachtest to
collect artifacts (cockroach logs and a debug.zip) when a restore
fails in the last step of the test (when all backups taken are
restored). In that step, we do not immediately fail the test when a
restore fails but instead attempt to restore every backup and return a
list of errors found when the process is done. However, restoring
cluster backups involves wiping the cluster which also deletes
existing cockroach logs up to that point. This makes debugging a
restore failure that happened prior to a cluster restore impossible.

After this commit, a restore failure in that test will cause a
`restore_failure_N` directory to be created in the artifacts
directory, including the cockroach logs collected right after the
failure, as well as a debug.zip created at the same time.

This will make issues such as #104604 more actionable.

Epic: none

Release note: None

### CODE REVIEW

**Review by srosenberg — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104868)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @renatolabs)

___
*[`pkg/cmd/roachtest/cluster.go` line 1476 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104868#-NXubDNz9nRGd-u264n_:-NXubDNz9nRGd-u264na:b-2jdtqc) ([raw file](https://github.com/cockroachdb/cockroach/blob/584fe30e5ba530b38b803a9492f6ac7b042a7b1e/pkg/cmd/roachtest/cluster.go#L1476)):*
> ```Go
> 
> // FetchDebugZip downloads the debug zip from the cluster using `roachprod ssh`.
> // The logs will be placed `dest`, relative to the test's artifacts dir.
> ```

Nit: ...placed at `dest`
___
*[`pkg/cmd/roachtest/tests/mixed_version_backup.go` line 2030 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104868#-NXucI7BE9Nto0LLdNvq:-NXucI7BE9Nto0LLdNvr:bczmcne) ([raw file](https://github.com/cockroachdb/cockroach/blob/584fe30e5ba530b38b803a9492f6ac7b042a7b1e/pkg/cmd/roachtest/tests/mixed_version_backup.go#L2030)):*
> ```Go
> 				// restore failure; if we can't, log the error encountered and
> 				// move on.
> 				restoreErr, collectionErr := mvb.collectFailureArtifacts(ctx, l, err, len(restoreErrors)+1)
> ```

Last param. is `errID`, but it seems hardly unique–what if it's invoked twice with the same number of `restoreErrors`?
___
*[`pkg/cmd/roachtest/tests/mixed_version_backup.go` line 2050 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104868#-NXubsb62IMCzHTC2D9p:-NXubsb62IMCzHTC2D9q:b-jszq74) ([raw file](https://github.com/cockroachdb/cockroach/blob/584fe30e5ba530b38b803a9492f6ac7b042a7b1e/pkg/cmd/roachtest/tests/mixed_version_backup.go#L2050)):*
> ```Go
> 		msgs := make([]string, 0, len(restoreErrors))
> 		for j, err := range restoreErrors {
> 			msgs = append(msgs, fmt.Sprintf("%d: %s", j+1, err.Error()))
> ```

Curious why the switch to 1-based accounting?

**Review by renatolabs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104868)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @srosenberg)

___
*[`pkg/cmd/roachtest/cluster.go` line 1476 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104868#-NXubDNz9nRGd-u264n_:-NXuguRHA9SR4_v8h8S0:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/584fe30e5ba530b38b803a9492f6ac7b042a7b1e/pkg/cmd/roachtest/cluster.go#L1476)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Nit: ...placed at `dest`
</blockquote></details>

Fixed.
___
*[`pkg/cmd/roachtest/tests/mixed_version_backup.go` line 2030 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104868#-NXucI7BE9Nto0LLdNvq:-NXugvRn7YSdfklhqcLr:b-8q1ldb) ([raw file](https://github.com/cockroachdb/cockroach/blob/584fe30e5ba530b38b803a9492f6ac7b042a7b1e/pkg/cmd/roachtest/tests/mixed_version_backup.go#L2030)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Last param. is `errID`, but it seems hardly unique–what if it's invoked twice with the same number of `restoreErrors`?
</blockquote></details>

It's unique "by construction" in this case? There's a 1:1 relationship between `collectFailureArtifacts` and `append(restoreErrors)` calls. The "ID" passed is such that it matches the index reported in the aggregated error message.
___
*[`pkg/cmd/roachtest/tests/mixed_version_backup.go` line 2050 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104868#-NXubsb62IMCzHTC2D9p:-NXuhJ1i3DbWSteQGk5_:b-k4c3ok) ([raw file](https://github.com/cockroachdb/cockroach/blob/584fe30e5ba530b38b803a9492f6ac7b042a7b1e/pkg/cmd/roachtest/tests/mixed_version_backup.go#L2050)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Curious why the switch to 1-based accounting?
</blockquote></details>

Just personal preference, doesn't matter either way. Humans start counting at 1, and the error is for human consumption :shrug:

**Review by srosenberg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104868)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/mixed_version_backup.go` line 2030 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104868#-NXucI7BE9Nto0LLdNvq:-NXujIGr7-uN4Qtjopdz:b-zibrwh) ([raw file](https://github.com/cockroachdb/cockroach/blob/584fe30e5ba530b38b803a9492f6ac7b042a7b1e/pkg/cmd/roachtest/tests/mixed_version_backup.go#L2030)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

It's unique "by construction" in this case? There's a 1:1 relationship between `collectFailureArtifacts` and `append(restoreErrors)` calls. The "ID" passed is such that it matches the index reported in the aggregated error message.
</blockquote></details>

Got it,  thanks. I was initially thinking this might get invoked multiple times during the lifecycle of the test, but that's not the case.
___
*[`pkg/cmd/roachtest/tests/mixed_version_backup.go` line 2050 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104868#-NXubsb62IMCzHTC2D9p:-NXujTtl4d4vu0nhuTN3:bzrdjo) ([raw file](https://github.com/cockroachdb/cockroach/blob/584fe30e5ba530b38b803a9492f6ac7b042a7b1e/pkg/cmd/roachtest/tests/mixed_version_backup.go#L2050)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Just personal preference, doesn't matter either way. Humans start counting at 1, and the error is for human consumption :shrug: 
</blockquote></details>

Fair enough, although the humans who will be reading these logs are already forced to switch between 0-based and 1-based thinking :)

**Comment by renatolabs** [comment]
@srosenberg pushed another commit after taking another look at #104604 -- that failure is actually a test timeout, and it's hard to diagnose. Let me know if you have comments.

**Review by srosenberg — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104868)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/mixed_version_backup.go` line 2045 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/104868#-NXurumq5mk17oFHUD3d:-NXurumr3p6J-jTszYKL:b96dicm) ([raw file](https://github.com/cockroachdb/cockroach/blob/c6403ffd5738cbb73fc08931f75cbe246bca26e3/pkg/cmd/roachtest/tests/mixed_version_backup.go#L2045)):*
> ```Go
> 	verify(clusterupgrade.MainVersion)
> 
> 	// If the context was canceled (most likely due to a test timeout),
> ```

Timeouts are partial (unclean) runs, so it makes sense to bail out here.

**Pull request merged**
