### PR TITLE
storage: issue swaps on AllocatorConsiderRebalance

### PR DESCRIPTION
**Pull request by tbg**
Change the rebalancing code so that it not only looks up a new replica to
add, but also picks one to remove. Both actions are then given to a
ChangeReplicas invocation which will carry it out atomically as long as
that feature is enabled.

Release note (bug fix): Replicas can now be moved between stores without
entering an intermediate configuration that violates the zone constraints.
Violations may still occur during zone config changes, decommissioning, and
in the presence of dead nodes (NB: the remainder be addressed in a future
change, so merge the corresponding release note)

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40284)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/storage/allocator.go, line 402 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40284#-LnNfa8O4tGC18-OOV3Z:-LnNfa8O4tGC18-OOV3_:b-waq6i0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b203d1d523af2adef042edaea66c4a97ea7467/pkg/storage/allocator.go#L402)):*
> ```Go
> 		// The dead replica(s) will be down-replicated later.
> 		priority := addDeadReplacementPriority
> 		log.VEventf(ctx, 3, "AllocatorAdd - replacement for %d dead replicas priority=%.2f",
> ```

`AllocatorReplaceDead`
___
*[pkg/storage/allocator.go, line 410 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40284#-LnNfbe61bpiEZnTE9PK:-LnNfbe61bpiEZnTE9PL:bqxkbbi) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b203d1d523af2adef042edaea66c4a97ea7467/pkg/storage/allocator.go#L410)):*
> ```Go
> 		// Range has decommissioning replica(s), which should be replaced.
> 		priority := addDecommissioningReplacementPriority
> 		log.VEventf(ctx, 3, "AllocatorAdd - replacement for %d decommissioning replicas priority=%.2f",
> ```

`AllocatorReplaceDecommissioning`
___
*[pkg/storage/allocator_test.go, line 5023 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40284#-LnNj2Pq4yoK28qblzO-:-LnNj2Pq4yoK28qblzO0:b-h6fnpe) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b203d1d523af2adef042edaea66c4a97ea7467/pkg/storage/allocator_test.go#L5023)):*
> ```Go
> 
> 				action, _ := a.ComputeAction(ctx, zone, &desc)
> 				require.Equal(t, c.expectedAction.String(), action.String())
> ```

Why do we need the `.String()`?
___
*[pkg/storage/replicate_queue.go, line 344 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40284#-LnNjAuf5utbzUkYwXsS:-LnNjAuf5utbzUkYwXsT:boga9ru) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b203d1d523af2adef042edaea66c4a97ea7467/pkg/storage/replicate_queue.go#L344)):*
> ```Go
> 		existingReplicas := liveVoterReplicas
> 		// WIP(tbg): pass a slice of replicas that can be replaced in.
> 		// In ReplaceDead, the it's the dead replicas, in ReplaceDecommissioning
> ```

`s/the it's/it's/`
___
*[pkg/storage/replicate_queue.go, line 423 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/40284#-LnNkdYe06CbdnZxnRyI:-LnNkdYe06CbdnZxnRyJ:b-7l1kxa) ([raw file](https://github.com/cockroachdb/cockroach/blob/405874b57e8ba22c06dbc3520ab4903a57d39d0c/pkg/storage/replicate_queue.go#L423)):*
> ```Go
> 		ctx,
> 		repl,
> 		[]roachpb.ReplicationChange{{Target: newReplica, ChangeType: roachpb.ADD_REPLICA}},
> ```

Can we not use `roachpb.MakeReplicationChanges` here and below?
___
*[pkg/storage/replicate_queue.go, line 717 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/40284#-LnNliw51GEutaf8fcvh:-LnNliw51GEutaf8fcvi:bykv1n2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6d5c9c5d0de2a004d99b5217f83509151144443/pkg/storage/replicate_queue.go#L717)):*
> ```
> not taking into account the replica we're going to remove
> ```

I must be missing how we're ensuring this. `findRemoveTarget` doesn't mutate `existingReplicas`, does it?
___
*[pkg/storage/replicate_queue_test.go, line 140 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/40284#-LnNmMSK2kAmbYRzOq43:-LnNmMSK2kAmbYRzOq44:bjgod3v) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6d5c9c5d0de2a004d99b5217f83509151144443/pkg/storage/replicate_queue_test.go#L140)):*
> ```Go
> 
> 	// Query the range log to see if anything unexpected happened. Concretely,
> 	// we'll make sure that our tracked ranges never had >=3 replicas.
> ```

`> 3 replicas`

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40284)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/storage/allocator_test.go, line 5023 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40284#-LnNj2Pq4yoK28qblzO-:-LnNosiRAofZPFUj_gTW:b67fl6p) ([raw file](https://github.com/cockroachdb/cockroach/blob/b7b203d1d523af2adef042edaea66c4a97ea7467/pkg/storage/allocator_test.go#L5023)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why do we need the `.String()`?
</blockquote></details>

It was printed as `%d` for some reason.
___
*[pkg/storage/replicate_queue.go, line 717 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/40284#-LnNliw51GEutaf8fcvh:-LnNpqvM7-dhrLKVREXQ:b-daheht) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6d5c9c5d0de2a004d99b5217f83509151144443/pkg/storage/replicate_queue.go#L717)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> ```
> not taking into account the replica we're going to remove
> ```

I must be missing how we're ensuring this. `findRemoveTarget` doesn't mutate `existingReplicas`, does it?
</blockquote></details>

We're removing one from `existingReplicas` and are adding one that is not in `existingReplicas`, hence they're not the same, so I think the comment is true-- but looking into this I saw that I'm reinventing the wheel:

https://github.com/cockroachdb/cockroach/blob/8d8e8ffd3b9918f9caa0f078fd1753c0922ba450/pkg/storage/allocator.go#L708-L715

I should return both the removal and addition target from `RebalanceTarget.

**Review by nvb — COMMENTED** [review]
> Reviewed 5 of 5 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, 4 of 4 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40284)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/storage/replicate_queue.go, line 717 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/40284#-LnNliw51GEutaf8fcvh:-LnNuAxG3lgLUIlQ16mg:b-xlhkhe) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6d5c9c5d0de2a004d99b5217f83509151144443/pkg/storage/replicate_queue.go#L717)):*
> We're removing one from existingReplicas and are adding one that is not in existingReplicas

Yeah, but where are we doing that?

Oh, unless the point is that `existingReplicas` still contains `removeReplica` when passed to `RebalanceTarget`, in which case the "not taking into account the replica we're going to remove" is easy to misinterpret as the opposite of what it's intending to say.

> I should return both the removal and addition target from `RebalanceTarget.

You're doing that now?

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40284)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/storage/replicate_queue.go, line 717 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/40284#-LnNliw51GEutaf8fcvh:-LnO3DnvCYnRwohjUiVU:bs214fz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6d5c9c5d0de2a004d99b5217f83509151144443/pkg/storage/replicate_queue.go#L717)):*
> You're doing that now?

Yep, done

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40284)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @tbg)

___
*[pkg/storage/allocator_test.go, line 609 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/40284#-LnO7fsS9bLY0XrBSt6X:-LnO7fsS9bLY0XrBSt6Y:bth8xkc) ([raw file](https://github.com/cockroachdb/cockroach/blob/60edff0b46b4dc969a7999c3598d29ce690d4801/pkg/storage/allocator_test.go#L609)):*
> ```Go
> 		{
> 			var rangeUsageInfo RangeUsageInfo
> 			target, details, _, ok := a.RebalanceTarget(
> ```

Is `details` in the wrong position?
___
*[pkg/storage/allocator_test.go, line 855 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/40284#-LnO7krj0qr4xHvZwV-7:-LnO7krj0qr4xHvZwV-8:bzcaofn) ([raw file](https://github.com/cockroachdb/cockroach/blob/60edff0b46b4dc969a7999c3598d29ce690d4801/pkg/storage/allocator_test.go#L855)):*
> ```Go
> 	sg.GossipStores(stores, t)
> 	for i := 0; i < 10; i++ {
> 		target, details, _, ok := a.RebalanceTarget(
> ```

Same question.
___
*[pkg/storage/allocator_test.go, line 873 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/40284#-LnO7nY12vmyWSp3AakB:-LnO7nY12vmyWSp3AakC:b2hm91l) ([raw file](https://github.com/cockroachdb/cockroach/blob/60edff0b46b4dc969a7999c3598d29ce690d4801/pkg/storage/allocator_test.go#L873)):*
> ```Go
> 	sg.GossipStores(stores, t)
> 	for i := 0; i < 10; i++ {
> 		target, details, _, ok := a.RebalanceTarget(
> ```

Mind checking all of these?
___
*[pkg/storage/replicate_queue.go, line 717 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/40284#-LnNliw51GEutaf8fcvh:-LnO85fU3xGVSjxr2TZE:b-rloua) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6d5c9c5d0de2a004d99b5217f83509151144443/pkg/storage/replicate_queue.go#L717)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

> You're doing that now?

Yep, done
</blockquote></details>

We don't need to transfer the lease away from `removeTarget`?
___
*[pkg/storage/replicate_queue.go, line 697 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/40284#-LnO8Epi6hc6uXUZIEVO:-LnO8Epi6hc6uXUZIEVP:b-ild09n) ([raw file](https://github.com/cockroachdb/cockroach/blob/60edff0b46b4dc969a7999c3598d29ce690d4801/pkg/storage/replicate_queue.go#L697)):*
> ```Go
> 	// rebalance. Attempt to find a rebalancing target.
> 	if !rq.store.TestingKnobs().DisableReplicaRebalancing {
> 		// Then, not taking into account the replica we're going to remove, see
> ```

This comment is strange now, since this is the only step.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40284)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/storage/replicate_queue.go, line 717 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/40284#-LnNliw51GEutaf8fcvh:-LnOToGn9vtaWMyYJfg7:b9jsebw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6d5c9c5d0de2a004d99b5217f83509151144443/pkg/storage/replicate_queue.go#L717)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We don't need to transfer the lease away from `removeTarget`?
</blockquote></details>

Good catch, we do. Added.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r13.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40284#-:-LnOlYFw06EgbijYNUFc:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/storage/replicate_queue.go, line 705 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/40284#-LnOkk1f0wSOozHAZZRe:-LnOkk1f0wSOozHAZZRf:b-6bcqlc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c66ec750a7d48a0040b41a1a10a27e54e7411a8/pkg/storage/replicate_queue.go#L705)):*
> ```Go
> 		} else if done, err := rq.maybeTransferLeaseAway(ctx, repl, removeTarget.StoreID, dryRun); err != nil {
> 			log.VEventf(ctx, 1, "want to remove self, but failed to transfer lease away: %s", err)
> 		} else if !done {
> ```

nit: I'd do this like:

```
if !ok {
    ...
} else if done, err := rq.maybeTransferLeaseAway(ctx, repl, removeTarget.StoreID, dryRun); err != nil {
    ...
} else if done {
    // Lease is now elsewhere, so we're not in charge any more.
    return false, nil
} else {
    ...
}
```

This gives you a place to add a comment.

**Review by tbg — COMMENTED** [review]
TFTR!

bors r=nvanbenschoten

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40284#-:-LnOqOhGCfVGKBfFF0yJ:b-l0r5kv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

**Pull request merged**
