### PR TITLE
sql: marshall the sequences session state to distsql execution

### LINKED ISSUE #23808: sql: panic in lastval
Found by `sqlsmith`.

```
SELECT CAST(NULLIF(ref_0.s_order_cnt, ref_0.s_i_id) AS INT8) AS c0 FROM public.stock AS ref_0 WHERE pg_catalog.set_masklen(CAST(pg_catalog.inet_client_addr() AS INET), CAST(pg_catalog.lastval() AS INT8)) > pg_catalog.inet_server_addr() LIMIT 65
```

```
I180313 19:10:14.144817 439 sql/conn_executor.go:1805  [n1,client=127.0.0.1:55225,user=root] [Open pos:105657] executing Sync
I180313 19:10:14.145112 439 sql/conn_executor.go:1805  [n1,client=127.0.0.1:55225,user=root] [Open pos:105658] executing ExecStmt: SELECT CAST(NULLIF(ref_0.s_order_cnt, ref_0.s_i_id) AS INT8) AS c0 FROM public.stock AS ref_0 WHERE pg_catalog.set_masklen(CAST(pg_catalog.inet_client_addr() AS INET), CAST(pg_catalog.lastval() AS INT8)) > pg_catalog.inet_server_addr() LIMIT 65
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x480a637]

goroutine 23714 [running]:
github.com/cockroachdb/cockroach/pkg/sql/sessiondata.(*SequenceState).GetLastValue(0x0, 0x0, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/sessiondata/sequence_state.go:63 +0x37
github.com/cockroachdb/cockroach/pkg/sql/sem/builtins.glob..func76(0xc433617600, 0x7265ed0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc435424154)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/sem/builtins/builtins.go:1087 +0x36
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FuncExpr).Eval(0xc429425b60, 0xc433617600, 0xc429425b60, 0x60c3060, 0xc429425b60, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go:3307 +0x314
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FuncExpr).Eval(0xc429425bc0, 0xc433617600, 0xc429425bc0, 0x60c3060, 0xc429425bc0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go:3297 +0x13a
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*ComparisonExpr).Eval(0xc425c02120, 0xc433617600, 0x0, 0x0, 0xc426195350, 0x4c705e5)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go:3256 +0x7d
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.RunFilter(0x60c2880, 0xc425c02120, 0xc433617600, 0x0, 0x1, 0xc426195350)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/expr_filter.go:26 +0x48
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*exprHelper).evalFilter(0xc42a388e00, 0xc433977c00, 0x11, 0x11, 0xabbd, 0xc435424160, 0x142)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/expr.go:153 +0x10c
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcOutputHelper).ProcessRow(0xc42758f500, 0x60b6ca0, 0xc42c1dec00, 0xc433977c00, 0x11, 0x11, 0xc42758f8d0, 0xc42758f940, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:304 +0x8a7
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*tableReader).Next(0xc42758f500, 0xc42080a790, 0x47735c6, 0x60b6be0, 0xc4270828c0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/tablereader.go:207 +0x2fc
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.Run(0x60b6be0, 0xc425d0ce80, 0x60b7b20, 0xc42758f500, 0x609d1a0, 0xc429711680)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:135 +0x35
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*tableReader).Run(0xc42758f500, 0xc425269df8)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/tablereader.go:132 +0x6b
created by github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Start
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:466 +0x38b
```

### PR DESCRIPTION
**Pull request by andreimatei**
Before this patch, using some of the sequence functions in a distql
query would results in a panic.

Fixes #23808

Release note: None

### CODE REVIEW

**Comment by vilterp** [comment]
This PR does solve the panic, so maybe we should just get it in for 2.0. But my gut reaction is that sequence state should stay on the gateway node, and we should fix this panic by disabling distsql for queries that use the functions powered by sequence state (`lastval` and `currval`). I don't know if choosing local sql for a statement based on what functions are being used is easy to do though.

The sequence state-using functions are most likely to be used in a transaction that's doing writes (i.e. insert some rows that increment a sequence, use `currval` or `lastval` to get the new value of the sequence and insert some other rows used to it) — they're unlikely to be used for the big distributed selects that distsql is built for. Thus the code, cpu and network bandwidth needed to marshal and send them over the network seems not worth it.

I am finishing up UI work today but can look at the "disable distsql" tomorrow or early next week.

**Comment by justinj** [comment]
> I don't know if choosing local sql for a statement based on what functions are being used is easy to do though.

it's easy, see `DistsqlBlacklist`: https://github.com/justinj/cockroach/blob/894d955ec0725224ddf8989af3a252edb03c09e2/pkg/sql/sem/builtins/builtins.go#L541

**Comment by vilterp** [comment]
Oh perfect. I will try that.

**Comment by andreimatei** [comment]
I don't really see reason to not support it; we should be chipping away at things that force us to use one engine or another because there will be a day where we have a single engine. When that  day comes, distsql will probably have a gateway-only mode, but still.
I don't buy the network bandwidth and cpu stuff too much. Most transactions will not have any sequence data, and if they do and we think the query needs distsql, then that shouldn't prevent us from using it. And the code... it's not so bad. Having a black-list would be the code I'd like to avoid (not only the blacklist itself, but the complications to the session state and the EvalCtx that come with it - like the `dummySequenceOperators`; see #24130).

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24131#-:-L8EfDXXGTnrAqHYVvK3:b-r1kf8t)*

**Review by vilterp — APPROVED** [review]
Ok, I buy the argument that this helps unblock removing local SQL.

**Comment by RaduBerinde** [comment]
Do we need to blacklist `nextval` though? I assume it does a write as part of the enclosing txn?

---

Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/api.proto, line 61 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24131#-L8FftnawJtSBE7GWiC1:-L8FftnawJtSBE7GWiC2:b-729wo5) ([raw file](https://github.com/cockroachdb/cockroach/blob/687d96ca9aeb28e8f1271e0b4a767cc3f5e73e21/pkg/sql/distsqlrun/api.proto#L61)):*
> ```protobuf
> }
> 
> // SequenceState is used to marshall the sessiondata.SequenceState struct.
> ```

Do we need to bump the distsql version?

---

*[pkg/sql/distsqlrun/api.proto, line 74 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24131#-L8Ffvh6h01hsieSp1LC:-L8Ffvh6h01hsieSp1LD:b-tcnkom) ([raw file](https://github.com/cockroachdb/cockroach/blob/687d96ca9aeb28e8f1271e0b4a767cc3f5e73e21/pkg/sql/distsqlrun/api.proto#L74)):*
> ```protobuf
>   optional uint32 last_seq_incremented = 2;
> }
> ```

[nit] extra line

---

*[pkg/sql/logictest/testdata/logic_test/sequences_distsql, line 40 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/24131#-L8FfyAqQDIf0FmpUzG9:-L8FfyAqQDIf0FmpUzGA:bub2c1t) ([raw file](https://github.com/cockroachdb/cockroach/blob/687d96ca9aeb28e8f1271e0b4a767cc3f5e73e21/pkg/sql/logictest/testdata/logic_test/sequences_distsql#L40)):*
> ```
> # 1, 1
> ```

[nit] trailing lines

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24131#-:-L8FgZFiNuGx_SVH6kUM:b-w22ktf)*

**Comment by vilterp** [comment]
Nextval does a write in its own transaction.

**Comment by RaduBerinde** [comment]
:lgtm:  then

---

Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24131#-:-L8FiRUOdTfgNcsebvDH:b-95nniq)*

**Comment by andreimatei** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/distsqlrun/api.proto, line 61 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24131#-L8FftnawJtSBE7GWiC1:-L8ZqJCl5TRn8l51rwUV:b547wwe) ([raw file](https://github.com/cockroachdb/cockroach/blob/687d96ca9aeb28e8f1271e0b4a767cc3f5e73e21/pkg/sql/distsqlrun/api.proto#L61)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Do we need to bump the distsql version?
</blockquote></details>

I don't think so. There's no incompatibility that's being introduced here. Old code would just crash on some queries :P

---

*[pkg/sql/distsqlrun/api.proto, line 74 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24131#-L8Ffvh6h01hsieSp1LC:-L8Zq_fd9DFPdVEwD0UM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/687d96ca9aeb28e8f1271e0b4a767cc3f5e73e21/pkg/sql/distsqlrun/api.proto#L74)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] extra line
</blockquote></details>

Done.

---

*[pkg/sql/logictest/testdata/logic_test/sequences_distsql, line 40 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24131#-L8FfyAqQDIf0FmpUzG9:-L8Zqewq8RdCWweFvUF5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/687d96ca9aeb28e8f1271e0b4a767cc3f5e73e21/pkg/sql/logictest/testdata/logic_test/sequences_distsql#L40)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] trailing lines
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24131)*

**Pull request merged**
