### PR TITLE
backport-2.1: server: add a configuration to enable GC of system.rangelog

### LINKED ISSUE #21260: storage: GC `system.rangelog`
We currently allow the `system.rangelog` table to grow without bound, on the assumption that its rate of growth will be negligible, but this isn't true. On long-lived clusters of many nodes, the rangelog table can grow to a significant fraction of the total database size. We need some sort of garbage collection here (and we should also take the opportunity to evaluate the usefulness of this log and whether we could be writing less data to it).

### PR DESCRIPTION
**Pull request by tbg**
Backport 1/1 commits from #30913.

This doesn't *have* to be in 2.1, and it hasn't baked particularly long, so I'm open to not backporting this (though I think it's a useful feature and due to the kill switch it can be disarmed)

Maybe we should backport this with a TTLs of zero (disabled)?

/cc @cockroachdb/release

---

system.rangelog table currently grows unboundedly. The rate of
growth is slow (as long as there is no replica rebalancing
thrashing), but it can still become a problem in long running
clusters.

This commit adds cluster settings to specify interval and TTL
for rows in system.rangelog.
By default, TTL of system.rangelog is set to 30 days.

Fixes #21260

Release note: Add configuration to enable GC of system.rangelog

### CODE REVIEW

**Comment by bdarnell** [comment]
I don't think we should have this on by default in 2.1. Either leave it for 2.2 or backport it with the default changed to 0.

**Comment by tschottdorf** [comment]
Updated, PTAL.

**Comment by bdarnell** [comment]
LGTM, but now that RC1 has been cut I don't feel comfortable adding this at this point. Maybe in a patch release, but I think I'd prefer waiting for 2.2.

**Comment by tschottdorf** [comment]
Ack.

**Pull request closed without merging**
