### PR TITLE
RFC: suggestions on adding new SQL syntax

### PR DESCRIPTION
**Pull request by knz**
Suggested to be put in RFC form by @danhhz

### CODE REVIEW

**Comment by couchand** [comment]
:lgtm: A variety of nits, but looks good on the whole.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[docs/RFCS/adding_sql_syntax.md, line 36 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17569#-KrBr3ROA_R64z83JbpL:-KrBr3RPhFKBTWWTs018:bte70js) ([raw file](https://github.com/cockroachdb/cockroach/blob/49ce8819c49109423f1bc5fa9f04b5c73ce9ed40/docs/RFCS/adding_sql_syntax.md#L36)):*
> ```Markdown
> The main motivation for that approach was to ensure that a later PR
> introducing said functionality would contain fewer commits / changes
> to review, to eas the review process.
> ```

s/eas/ease/

---

*[docs/RFCS/adding_sql_syntax.md, line 43 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17569#-KrBr9JG4DCStQ9skACl:-KrBr9JG4DCStQ9skACm:bcvwupa) ([raw file](https://github.com/cockroachdb/cockroach/blob/49ce8819c49109423f1bc5fa9f04b5c73ce9ed40/docs/RFCS/adding_sql_syntax.md#L43)):*
> ```Markdown
> - "Things happen" with the grammar over time - cleanups, refactorings,
>   optimizations, renames, etc. This is routine work for the SQL team,
>   but it's also work that needs to have ownership of the SQL
> ```

the grammar of this sentence is a little odd... the work doesn't have ownership.

---

*[docs/RFCS/adding_sql_syntax.md, line 55 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17569#-KrBraoJhQG6tTqo_gog:-KrBraoJhQG6tTqo_goh:bg3yc6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/49ce8819c49109423f1bc5fa9f04b5c73ce9ed40/docs/RFCS/adding_sql_syntax.md#L55)):*
> ```Markdown
>   1) that the UI is consistent
>   2) that it's orthogonal
>   3) that it is extendable at low cost
> ```

s/extendable/extensible

---

*[docs/RFCS/adding_sql_syntax.md, line 58 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17569#-KrBrQv3rEr6OztpZrnA:-KrBrQv3rEr6OztpZrnB:bmkwzcq) ([raw file](https://github.com/cockroachdb/cockroach/blob/49ce8819c49109423f1bc5fa9f04b5c73ce9ed40/docs/RFCS/adding_sql_syntax.md#L58)):*
> ```Markdown
>   4) that it's well-documented and, most important for us
>   5) that we don't run the risk of defining something that will
> 	 conflict with some industry standard later (such as a standard
> ```

%s/^\t/    /

---

*[docs/RFCS/adding_sql_syntax.md, line 60 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17569#-KrBs2cORwlowJXWJydt:-KrBs2cORwlowJXWJydu:b-pwh9mj) ([raw file](https://github.com/cockroachdb/cockroach/blob/49ce8819c49109423f1bc5fa9f04b5c73ce9ed40/docs/RFCS/adding_sql_syntax.md#L60)):*
> ```Markdown
> 	 conflict with some industry standard later (such as a standard
> 	 SQL feature *we* may not have heard of yet but our customers will
> 	 want us to look at).
> ```

to this end, I suggest that the one accepted and documented exception to this policy be to reserve syntax that is specified in the SQL syntax but currently unsupported.  this provides us a convinient way to ensure we don't introduce conflicting syntax while also giving us a natural mechanism to inform the user that, yes, we know that's a reasonable thing to ask, go look at this GH issue to see why we don't support it

---

*[docs/RFCS/adding_sql_syntax.md, line 63 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17569#-KrBrfkX_bk-ETm8H9Sq:-KrBrfkX_bk-ETm8H9Sr:bivkksj) ([raw file](https://github.com/cockroachdb/cockroach/blob/49ce8819c49109423f1bc5fa9f04b5c73ce9ed40/docs/RFCS/adding_sql_syntax.md#L63)):*
> ```Markdown
> 
>   Granted, SQL is not really "pleasant" to look at but it has some
>   internal structure and general patterns wrt extensibility that have
> ```

s/wrt/regarding/

---

*[docs/RFCS/adding_sql_syntax.md, line 94 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17569#-KrBsakl_yA35j5AsqNE:-KrBsakl_yA35j5AsqNF:b-ul506p) ([raw file](https://github.com/cockroachdb/cockroach/blob/49ce8819c49109423f1bc5fa9f04b5c73ce9ed40/docs/RFCS/adding_sql_syntax.md#L94)):*
> ```Markdown
> 
> **As a matter of good engineering, it is always useful to discuss and
> define the mechanisms separately from the design of the interfaces.**
> ```

and prior to.

---

*[docs/RFCS/adding_sql_syntax.md, line 158 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17569#-KrBtEML4nfDBFpCJ_Ia:-KrBtEMMLXVw14i4IM-H:b-armbok) ([raw file](https://github.com/cockroachdb/cockroach/blob/49ce8819c49109423f1bc5fa9f04b5c73ce9ed40/docs/RFCS/adding_sql_syntax.md#L158)):*
> ```Markdown
>   - does the functionality need to input data from a relation/query?
>     - consider FROM
> 	
> ```

trailing w/s

---

*[docs/RFCS/adding_sql_syntax.md, line 161 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17569#-KrBtMZRfgYzbcgwrQoO:-KrBtMZRfgYzbcgwrQoP:bpgu2ql) ([raw file](https://github.com/cockroachdb/cockroach/blob/49ce8819c49109423f1bc5fa9f04b5c73ce9ed40/docs/RFCS/adding_sql_syntax.md#L161)):*
> ```Markdown
> In general: if a *part* of another SQL statement corresponds more or
> less to what your new envisioned syntax requires, consider reusing the
> same syntactic structure. This is moreso true if there are two or more
> ```

or keywords?

---

*[docs/RFCS/adding_sql_syntax.md, line 223 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17569#-KrBtr63yFa6gJBTj1Hn:-KrBtr63yFa6gJBTj1Ho:bcu6mod) ([raw file](https://github.com/cockroachdb/cockroach/blob/49ce8819c49109423f1bc5fa9f04b5c73ce9ed40/docs/RFCS/adding_sql_syntax.md#L223)):*
> ```Markdown
> - If your feature is adding a new SQL statement type:
>   - what should its PG tag be in the pgwire protocol? Are clients going to notice/care?
>   - be mindful about the difference between DDL and non-DDL statements
> ```

Alternatives?  Unresolved questions?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17569#-:-KrBu2oV8qR1dPrmrJFb:b75fs2o)*

**Comment by knz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 10 unresolved discussions.

---

*[docs/RFCS/adding_sql_syntax.md, line 36 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17569#-KrBr3ROA_R64z83JbpL:-KrG4DQPZTpljkwogHki:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/49ce8819c49109423f1bc5fa9f04b5c73ce9ed40/docs/RFCS/adding_sql_syntax.md#L36)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

s/eas/ease/
</blockquote></details>

Done.

---

*[docs/RFCS/adding_sql_syntax.md, line 43 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17569#-KrBr9JG4DCStQ9skACl:-KrG4IGNYlM_W_aoyBrq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/49ce8819c49109423f1bc5fa9f04b5c73ce9ed40/docs/RFCS/adding_sql_syntax.md#L43)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

the grammar of this sentence is a little odd... the work doesn't have ownership.
</blockquote></details>

Done.

---

*[docs/RFCS/adding_sql_syntax.md, line 55 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17569#-KrBraoJhQG6tTqo_gog:-KrG4KUy5D5RML6RzItN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/49ce8819c49109423f1bc5fa9f04b5c73ce9ed40/docs/RFCS/adding_sql_syntax.md#L55)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

s/extendable/extensible
</blockquote></details>

Done.

---

*[docs/RFCS/adding_sql_syntax.md, line 58 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17569#-KrBrQv3rEr6OztpZrnA:-KrG4L8eRcwfXw-y12XL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/49ce8819c49109423f1bc5fa9f04b5c73ce9ed40/docs/RFCS/adding_sql_syntax.md#L58)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

%s/^\t/    /
</blockquote></details>

Done.

---

*[docs/RFCS/adding_sql_syntax.md, line 60 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17569#-KrBs2cORwlowJXWJydt:-KrG50uU0qHawwkXWxTd:bo3u2zm) ([raw file](https://github.com/cockroachdb/cockroach/blob/49ce8819c49109423f1bc5fa9f04b5c73ce9ed40/docs/RFCS/adding_sql_syntax.md#L60)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

to this end, I suggest that the one accepted and documented exception to this policy be to reserve syntax that is specified in the SQL syntax but currently unsupported.  this provides us a convinient way to ensure we don't introduce conflicting syntax while also giving us a natural mechanism to inform the user that, yes, we know that's a reasonable thing to ask, go look at this GH issue to see why we don't support it
</blockquote></details>

Done. (new section below)

---

*[docs/RFCS/adding_sql_syntax.md, line 63 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17569#-KrBrfkX_bk-ETm8H9Sq:-KrG54bLaSwY2iINv5r0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/49ce8819c49109423f1bc5fa9f04b5c73ce9ed40/docs/RFCS/adding_sql_syntax.md#L63)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

s/wrt/regarding/
</blockquote></details>

Done.

---

*[docs/RFCS/adding_sql_syntax.md, line 94 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17569#-KrBsakl_yA35j5AsqNE:-KrG55FohsJ1ffOKnhn7:b-6pv2rb) ([raw file](https://github.com/cockroachdb/cockroach/blob/49ce8819c49109423f1bc5fa9f04b5c73ce9ed40/docs/RFCS/adding_sql_syntax.md#L94)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

and prior to.
</blockquote></details>

Huh why? I think they should be done concurrently, albeit separately.

---

*[docs/RFCS/adding_sql_syntax.md, line 158 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17569#-KrBtEML4nfDBFpCJ_Ia:-KrG58t8_oLYIl99jXMr:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/49ce8819c49109423f1bc5fa9f04b5c73ce9ed40/docs/RFCS/adding_sql_syntax.md#L158)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

trailing w/s
</blockquote></details>

Fixed.

---

*[docs/RFCS/adding_sql_syntax.md, line 161 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17569#-KrBtMZRfgYzbcgwrQoO:-KrG59da74RU8JLbs8nH:b7c9gwp) ([raw file](https://github.com/cockroachdb/cockroach/blob/49ce8819c49109423f1bc5fa9f04b5c73ce9ed40/docs/RFCS/adding_sql_syntax.md#L161)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

or keywords?
</blockquote></details>

Please explain?

---

*[docs/RFCS/adding_sql_syntax.md, line 223 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17569#-KrBtr63yFa6gJBTj1Hn:-KrG5eN66NxqlfEX-Esn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/49ce8819c49109423f1bc5fa9f04b5c73ce9ed40/docs/RFCS/adding_sql_syntax.md#L223)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

Alternatives?  Unresolved questions?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17569)*

**Comment by knz** [comment]
final comment period

**Comment by knz** [comment]
final comment period extended due to incoming comments - will be processed soon

**Comment by knz** [comment]
FCP canceled - there needs some revision in here.
Notes from a discussion with @danhhz: this RFC should mention solutions as to how to set up unit testing for an ongoing project before the features are complete.

**Comment by vivekmenezes** [comment]
@knz very nice writeup! Thanks for doing it. I'm okay with merging it as is as a first version. It's kind of odd that it's an RFC since it's really a policy doc so perhaps merging it elsewhere makes more sense.

I'd suggest adding a couple of examples to the doc to connect it to the ground reality. Perhaps using the testing addition that you had in mind suggested by dan can help.

**Comment by couchand** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/adding_sql_syntax.md, line 94 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17569#-KrBsakl_yA35j5AsqNE:-KuKcCah9WfZXEmSF6Y5:b3nud5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/49ce8819c49109423f1bc5fa9f04b5c73ce9ed40/docs/RFCS/adding_sql_syntax.md#L94)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Huh why? I think they should be done concurrently, albeit separately.
</blockquote></details>

I guess what I was getting at is that it's a good idea to have a solid understanding of what we're trying to do before we dive into coming up with a SQL interface for it.  But I think you're right, they can reasonably be developed concurrently.  Perhaps the ordering constraint is actually "mechanisms no later than interface".

---

*[docs/RFCS/adding_sql_syntax.md, line 161 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17569#-KrBtMZRfgYzbcgwrQoO:-KuKcaMwd9YkosX6MHka:b-fr4f7o) ([raw file](https://github.com/cockroachdb/cockroach/blob/49ce8819c49109423f1bc5fa9f04b5c73ce9ed40/docs/RFCS/adding_sql_syntax.md#L161)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please explain?
</blockquote></details>

If possible reuse existing keywords rather than defining new keywords, particularly if the new keyword would have to be reserved.  Maybe that's already clear from what you wrote, but I thought it was worth mentioning.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17569)*

**Comment by knz** [comment]
@danhhz I have added a section to reflect what we talked about. PTAL.

(cc @benesch since you're effectively applying this in #19140 )

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[docs/RFCS/adding_sql_syntax.md, line 94 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17569#-KrBsakl_yA35j5AsqNE:-Kw4siZjzbFEIycQE591:b-3d8t2u) ([raw file](https://github.com/cockroachdb/cockroach/blob/49ce8819c49109423f1bc5fa9f04b5c73ce9ed40/docs/RFCS/adding_sql_syntax.md#L94)):*
> mechanisms no later than interface
Added.

---

*[docs/RFCS/adding_sql_syntax.md, line 161 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17569#-KrBtMZRfgYzbcgwrQoO:-Kw4sYUmpZIdgAG5euZr:b-g1y7iv) ([raw file](https://github.com/cockroachdb/cockroach/blob/49ce8819c49109423f1bc5fa9f04b5c73ce9ed40/docs/RFCS/adding_sql_syntax.md#L161)):*
> If possible reuse existing keywords rather than defining new keywords, particularly if the new keyword would have to be reserved.
Added this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17569#-:-Kw4szY6yoKF0i_YwxAJ:b-nfe8nb)*

**Comment by danhhz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/adding_sql_syntax.md, line 145 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17569#-Kw6AYJ8wqPgOqUi-iYW:-Kw6AYJ8wqPgOqUi-iYX:b-9azbad) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cde142a2332533500ead16165edde751e7acb66/docs/RFCS/adding_sql_syntax.md#L145)):*
> ```Markdown
> permissions or a planner flag.
> 
> ## Multi-person or multi-stage projects
> ```

excellent! this section looks very good overall

---

*[docs/RFCS/adding_sql_syntax.md, line 149 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17569#-Kw6Ac7lCyKLno-b7DTF:-Kw6Ac7lCyKLno-b7DTG:baamb8f) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cde142a2332533500ead16165edde751e7acb66/docs/RFCS/adding_sql_syntax.md#L149)):*
> ```Markdown
> We can reserve syntax also when all the following conditions hold:
> 
> - a new mechanism RFC in demand of dedicated syntax has been discussed
> ```

my one concern is that we're moving toward a world where we get more and more buy-in from external customers before closing fcp and merging an rfc. which takes a lot of time and we may not want to wait to start the implementation.

partitioning, for example, is still being shopped to the interested customers, but we're getting ready to optimistically assume it will work out how we've presented it and start implementing it. which means we need _some_ syntax. it's possible that what we have presented in the rfc right now might change, but we'd obviously update the implementation in response.

which leads me to my concrete proposal: we should have a more precise definition of an "accepted" rfc here. (first lgtm? enter fcp? merged?)

instead of enter fcp/merged, i'd like to suggest that if necessary, an lgtm on just the proposed syntax from someone on sql-language-prs is enough

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17569)*

**Comment by knz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/adding_sql_syntax.md, line 149 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17569#-Kw6Ac7lCyKLno-b7DTF:-KwAJMXuVXTWkdLHVGMI:bqi79lv) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cde142a2332533500ead16165edde751e7acb66/docs/RFCS/adding_sql_syntax.md#L149)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

my one concern is that we're moving toward a world where we get more and more buy-in from external customers before closing fcp and merging an rfc. which takes a lot of time and we may not want to wait to start the implementation.

partitioning, for example, is still being shopped to the interested customers, but we're getting ready to optimistically assume it will work out how we've presented it and start implementing it. which means we need _some_ syntax. it's possible that what we have presented in the rfc right now might change, but we'd obviously update the implementation in response.

which leads me to my concrete proposal: we should have a more precise definition of an "accepted" rfc here. (first lgtm? enter fcp? merged?)

instead of enter fcp/merged, i'd like to suggest that if necessary, an lgtm on just the proposed syntax from someone on sql-language-prs is enough
</blockquote></details>

Reworded to add the flexibility you suggested.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17569)*

**Pull request merged**
