### PR TITLE
server, ui: add sort and limit to sql activity pages, switch sql activity pages to read only from system table

### PR DESCRIPTION
**Pull request by xinhaoz**
See individual commits.

DB-Console: https://www.loom.com/share/73248244baa54cdf80389d0eec788447
DB-Console Details pages: https://www.loom.com/share/2d74c6cf082f4dcfb5e7f690166c2baf

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
nit: You should update your PR title, since it has a lot more than that
Can you add looms showing the new behaviour working on all SQL Activity pages on both DB and CC?

> Reviewed 3 of 3 files at r1, 21 of 21 files at r2, 3 of 3 files at r3, 5 of 5 files at r4, 18 of 18 files at r5, 12 of 12 files at r6, 24 of 24 files at r7, 34 of 34 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98815#-:-NQze2V508SBwEPbKY0q:boxpauh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`-- commits` line 79 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/98815#-NQzi5dl9tFmdUOo3zUN):*
you should add a release note here, because documentation will need to be updated to show users they might not see data that was just executed
___
*[`pkg/server/combined_statement_stats.go` line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98815#-NQzeYRf7k3cxRAq-_Z-:-NQzeYRf7k3cxRAq-_Z0:b-xqc1vo) ([raw file](https://github.com/cockroachdb/cockroach/blob/672cb2bd6c38a8ca3f8cbb7d2f7a097ebc5a3d7a/pkg/server/combined_statement_stats.go#L80)):*
> ```Go
> 	var err error
> 
> 	if req.FetchMode == nil || req.FetchMode.StatsType != serverpb.CombinedStatementsStatsRequest_StmtStatsOnly {
> ```

nit: can you use StatsType == TxnStatsOnly to make more clear? Is a little confusing this way
___
*[`pkg/server/combined_statement_stats.go` line 256 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/98815#-NQzhQVC2ONK_PtjR7AB:-NQzhQVC2ONK_PtjR7AC:b-uwnj42) ([raw file](https://github.com/cockroachdb/cockroach/blob/3860273002cfae7a66f3bd8d5fe3e65e2923aa24/pkg/server/combined_statement_stats.go#L256)):*
> ```Go
> 	aostClause := testingKnobs.GetAOSTClause()
> 	query := fmt.Sprintf(`
> SELECT * FROM (
> ```

why you need this "wrapper" select?
___
*[`pkg/server/combined_statement_stats.go` line 264 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/98815#-NQziJ7K-GnrxZ8b5rp8:-NQziJ7K-GnrxZ8b5rp9:b-vgjx6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fb4a9acba7b0486f16552f40fd94d8690ab29ed/pkg/server/combined_statement_stats.go#L264)):*
> ```Go
>     metadata,
>     crdb_internal.merge_statement_stats(array_agg(statistics)) AS statistics
> FROM crdb_internal.statement_statistics_persisted %s
> ```

there are other places on this file that should also be updated to the new tables, e.g. all the calls on the details. Basically all usages should be replaced with the new views, since there is also performance issues on details endpoints
___
*[`pkg/ui/workspaces/cluster-ui/src/api/statementsApi.ts` line 54 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/98815#-NQzjMBS3j5ZGy48YBOj:-NQzjMBS3j5ZGy48YBOk:b-qen11l) ([raw file](https://github.com/cockroachdb/cockroach/blob/b20bd821ab3ab870abbecf9ecc51df85f6639fca/pkg/ui/workspaces/cluster-ui/src/api/statementsApi.ts#L54)):*
> ```XML
> };
> 
> // THhe required fields to create a stmts request.
> ```

nit: The
___
*[`pkg/ui/workspaces/cluster-ui/src/searchCriteria/searchCriteria.tsx` line 1 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/98815#-NQzlvO11pQ_AoxeTY0F:-NQzlvO11pQ_AoxeTY0G:bxqvv2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9aa01a4c8641a9cfc67e35f955f325e33f7e165/pkg/ui/workspaces/cluster-ui/src/searchCriteria/searchCriteria.tsx#L1)):*
> ```XML
> // Copyright 2021 The Cockroach Authors.
> ```

nit: 2023
___
*[`pkg/ui/workspaces/cluster-ui/src/store/transactionStats/index.ts` line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98815#-NQzfj7x9icWBMPDJxWM:-NQzfj7x9icWBMPDJxWN:bxqvv2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/41355f2ea12af60fdcdf85482a0028a7a590ae24/pkg/ui/workspaces/cluster-ui/src/store/transactionStats/index.ts#L1)):*
> ```XML
> // Copyright 2021 The Cockroach Authors.
> ```

nit: 2023
___
*[`pkg/ui/workspaces/cluster-ui/src/store/transactionStats/txnStats.reducer.ts` line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98815#-NQzfhpx3tcbRONqq4MA:-NQzfhpx3tcbRONqq4MB:bxqvv2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/41355f2ea12af60fdcdf85482a0028a7a590ae24/pkg/ui/workspaces/cluster-ui/src/store/transactionStats/txnStats.reducer.ts#L1)):*
> ```XML
> // Copyright 2021 The Cockroach Authors.
> ```

nit: 2023
___
*[`pkg/ui/workspaces/cluster-ui/src/store/transactionStats/txnStats.reducer.ts` line 41 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98815#-NQzfSWV-GsPuJZdUk8S:-NQzfSWV-GsPuJZdUk8T:b3pc589) ([raw file](https://github.com/cockroachdb/cockroach/blob/41355f2ea12af60fdcdf85482a0028a7a590ae24/pkg/ui/workspaces/cluster-ui/src/store/transactionStats/txnStats.reducer.ts#L41)):*
> ```XML
> };
> 
> // This is actually statements only, despite the SQLStatsState name.
> ```

this comment is not valid here
___
*[`pkg/ui/workspaces/cluster-ui/src/store/transactionStats/txnStats.reducer.ts` line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98815#-NQzfXrm5v1Xpyz5-ABB:-NQzfXrnA8xbJmsXxw0i:b-nr9o3t) ([raw file](https://github.com/cockroachdb/cockroach/blob/41355f2ea12af60fdcdf85482a0028a7a590ae24/pkg/ui/workspaces/cluster-ui/src/store/transactionStats/txnStats.reducer.ts#L47)):*
> ```XML
>   initialState,
>   reducers: {
>     received: (state, action: PayloadAction<StatementsResponse>) => {
> ```

maybe you want to add a comment that is indeed StatementResponse for Transaction, might be confusing for someone looking into this in the future and asking why they don't match
___
*[`pkg/ui/workspaces/cluster-ui/src/store/transactionStats/txnStats.sagas.ts` line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98815#-NQzfm4gBmO9gcThFEae:-NQzfm4gBmO9gcThFEaf:bxqvv2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/41355f2ea12af60fdcdf85482a0028a7a590ae24/pkg/ui/workspaces/cluster-ui/src/store/transactionStats/txnStats.sagas.ts#L1)):*
> ```XML
> // Copyright 2021 The Cockroach Authors.
> ```

nit: 2023
___
*[`pkg/ui/workspaces/cluster-ui/src/store/transactionStats/txnStats.selector.ts` line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98815#-NQzfp254EOaswXt70qf:-NQzfp254EOaswXt70qg:bxqvv2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/41355f2ea12af60fdcdf85482a0028a7a590ae24/pkg/ui/workspaces/cluster-ui/src/store/transactionStats/txnStats.selector.ts#L1)):*
> ```XML
> // Copyright 2021 The Cockroach Authors.
> ```

nit: 2023
___
*[`pkg/ui/workspaces/db-console/src/util/api.ts` line 748 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/98815#-NQzjwFPC-_diyff_zt2:-NQzjwFPC-_diyff_zt3:bnr61up) ([raw file](https://github.com/cockroachdb/cockroach/blob/1cf75095871a9df935c036c674783dca73a02134/pkg/ui/workspaces/db-console/src/util/api.ts#L748)):*
> ```XML
> 
> // getCombinedStatements returns statements the cluster has recently executed, and some stats about them.
> export function getCombinedStatements(
> ```

curious of why this is no longer needed
___
*[`pkg/ui/workspaces/db-console/src/views/transactions/transactionDetails.tsx` line 39 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/98815#-NQzk88yAKadL0TQzEiD:-NQzk88yAKadL0TQzEiE:blg6cm5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b20bd821ab3ab870abbecf9ecc51df85f6639fca/pkg/ui/workspaces/db-console/src/views/transactions/transactionDetails.tsx#L39)):*
> ```XML
> import { selectTxnInsightsByFingerprint } from "src/views/insights/insightsSelectors";
> import { selectHasAdminRole } from "src/redux/user";
> import { limitSetting } from "./transactionsPage";
> ```

can you combine this with the import above with the other stuff coming from this file?
___
*[`pkg/ccl/serverccl/statusccl/tenant_status_test.go` line 440 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/98815#-NQziiTe4eJ89AOefl4s:-NQziiTe4eJ89AOefl4t:b94rg27) ([raw file](https://github.com/cockroachdb/cockroach/blob/1cf75095871a9df935c036c674783dca73a02134/pkg/ccl/serverccl/statusccl/tenant_status_test.go#L440)):*
> ```Go
> 		}
> 
> 		for _, tenantStmt := range tenantCombinedStats.Statements {
> ```

why those tests were removed?
___
*[`pkg/ccl/serverccl/statusccl/tenant_status_test.go` line 447 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/98815#-NQziulcE6UatP_RUeOw:-NQziulcE6UatP_RUeOx:blksh1e) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fb4a9acba7b0486f16552f40fd94d8690ab29ed/pkg/ccl/serverccl/statusccl/tenant_status_test.go#L447)):*
> ```Go
> 	// ensure tests are deterministic.
> 	testCluster.TenantConn(0 /* idx */).
> 		Exec(t, "SET CLUSTER SETTING sql.stats.flush.interval = '24h'")
> ```

why can you just shut off the flush like it was done previously?
___
*[`pkg/ui/workspaces/cluster-ui/src/store/transactionStats/txnStats.sagas.spec.ts` line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98815#-NQzg9mK4eV2p9tvLWy8:-NQzg9mK4eV2p9tvLWy9:bxqvv2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/41355f2ea12af60fdcdf85482a0028a7a590ae24/pkg/ui/workspaces/cluster-ui/src/store/transactionStats/txnStats.sagas.spec.ts#L1)):*
> ```XML
> // Copyright 2021 The Cockroach Authors.
> ```

nit: 2023

**Review by xinhaoz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98815)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/server/combined_statement_stats.go` line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98815#-NQzeYRf7k3cxRAq-_Z-:-NQzx9sf8-jh4uESMn0q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/672cb2bd6c38a8ca3f8cbb7d2f7a097ebc5a3d7a/pkg/server/combined_statement_stats.go#L80)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: can you use StatsType == TxnStatsOnly to make more clear? Is a little confusing this way
</blockquote></details>

Done.
___
*[`pkg/server/combined_statement_stats.go` line 256 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/98815#-NQzhQVC2ONK_PtjR7AB:-NQzxGKXBrLk2eh5NXrl:bn0vrbd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3860273002cfae7a66f3bd8d5fe3e65e2923aa24/pkg/server/combined_statement_stats.go#L256)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

why you need this "wrapper" select?
</blockquote></details>

It's so that we can use the statistics column in the sort. Since `merge_statement_statistics` isn't recognized as an aggregate function, we can't use it in the `ORDER BY`.
___
*[`pkg/server/combined_statement_stats.go` line 264 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/98815#-NQziJ7K-GnrxZ8b5rp8:-NR-0LDeE6iuC9a6hQ9I:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fb4a9acba7b0486f16552f40fd94d8690ab29ed/pkg/server/combined_statement_stats.go#L264)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

there are other places on this file that should also be updated to the new tables, e.g. all the calls on the details. Basically all usages should be replaced with the new views, since there is also performance issues on details endpoints
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/store/transactionStats/txnStats.reducer.ts` line 41 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98815#-NQzfSWV-GsPuJZdUk8S:-NQzxSii27QIj4QkObVt:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/41355f2ea12af60fdcdf85482a0028a7a590ae24/pkg/ui/workspaces/cluster-ui/src/store/transactionStats/txnStats.reducer.ts#L41)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

this comment is not valid here
</blockquote></details>

Removed.
___
*[`pkg/ui/workspaces/cluster-ui/src/store/transactionStats/txnStats.reducer.ts` line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/98815#-NQzfXrm5v1Xpyz5-ABB:-NQzyW9fB87siPS7k_57:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/41355f2ea12af60fdcdf85482a0028a7a590ae24/pkg/ui/workspaces/cluster-ui/src/store/transactionStats/txnStats.reducer.ts#L47)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

maybe you want to add a comment that is indeed StatementResponse for Transaction, might be confusing for someone looking into this in the future and asking why they don't match
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/db-console/src/util/api.ts` line 748 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/98815#-NQzjwFPC-_diyff_zt2:-NQzzZjl5r8OM31KHGlA:b-7vny53) ([raw file](https://github.com/cockroachdb/cockroach/blob/1cf75095871a9df935c036c674783dca73a02134/pkg/ui/workspaces/db-console/src/util/api.ts#L748)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

curious of why this is no longer needed
</blockquote></details>

We can use the one exported from cluster-ui -- no need to duplicate it here.
___
*[`pkg/ccl/serverccl/statusccl/tenant_status_test.go` line 440 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/98815#-NQziiTe4eJ89AOefl4s:-NQzzkt13qbp3GZqFUBk:b-t6mu8t) ([raw file](https://github.com/cockroachdb/cockroach/blob/1cf75095871a9df935c036c674783dca73a02134/pkg/ccl/serverccl/statusccl/tenant_status_test.go#L440)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

why those tests were removed?
</blockquote></details>

We're just reading from a system table now instead of in-memory. I thought we got segregated tables for tenants for free so this test isn't necessary anymore IIUC.
___
*[`pkg/ccl/serverccl/statusccl/tenant_status_test.go` line 447 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/98815#-NQziulcE6UatP_RUeOw:-NR--9hz-tVDtuNGbOby:b-d4reeh) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fb4a9acba7b0486f16552f40fd94d8690ab29ed/pkg/ccl/serverccl/statusccl/tenant_status_test.go#L447)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

why can you just shut off the flush like it was done previously?
</blockquote></details>

Well I checked the code and it in the code for Flush, if this is disabled, we do not flush.  So this test actually was just testing in-memory both times before.

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98815)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`pkg/server/combined_statement_stats.go` line 697 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/98815#-NR-9PLbD7hWsGd80S9m:-NR-9PLbD7hWsGd80S9n:b-p9tod9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8025085f326e821c1a36676cbe34846113dbc73/pkg/server/combined_statement_stats.go#L697)):*
> ```Go
> 		FROM crdb_internal.statement_statistics_persisted %s
> 		GROUP BY
> 				agg_interval,
> ```

We don't use the aggregation interval anywhere, it can be removed here too
___
*[`pkg/server/combined_statement_stats.go` line 774 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/98815#-NR-9fys1myepPgse5J_:-NR-9fys1myepPgse5Ja:b-p9tod9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8025085f326e821c1a36676cbe34846113dbc73/pkg/server/combined_statement_stats.go#L774)):*
> ```Go
> 				crdb_internal.merge_stats_metadata(array_agg(metadata)) AS metadata,
> 				crdb_internal.merge_statement_stats(array_agg(statistics)) AS statistics,
> 				agg_interval
> ```

We don't use the aggregation interval anywhere, it can be removed here too
___
*[`pkg/server/combined_statement_stats.go` line 921 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/98815#-NR-9hRd4GlvHBoACqX4:-NR-9hRd4GlvHBoACqX5:b-p9tod9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8025085f326e821c1a36676cbe34846113dbc73/pkg/server/combined_statement_stats.go#L921)):*
> ```Go
> 				crdb_internal.merge_stats_metadata(array_agg(metadata)) AS metadata,
> 				crdb_internal.merge_statement_stats(array_agg(statistics)) AS statistics,
> 				agg_interval,
> ```

We don't use the aggregation interval anywhere, it can be removed here too

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98815)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`pkg/ccl/serverccl/statusccl/tenant_status_test.go` line 371 at r21](https://reviewable.io/reviews/cockroachdb/cockroach/98815#-NR-F5k8Do_fwHrWQN2B:-NR-F5k8Do_fwHrWQN2C:b-q70r2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd4f05e3c95b8ae10459fd13eb95bc113936f5fc/pkg/ccl/serverccl/statusccl/tenant_status_test.go#L371)):*
> ```Go
> 	require.NoError(t, err)
> 
> 	require.NoError(t, err)
> ```

this line is no longer necessary, since you don't have any new errors

**Review by xinhaoz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98815)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`-- commits` line 79 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/98815#-NQzi5dl9tFmdUOo3zUN):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

you should add a release note here, because documentation will need to be updated to show users they might not see data that was just executed
</blockquote></details>

Done.
___
*[`pkg/server/combined_statement_stats.go` line 697 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/98815#-NR-9PLbD7hWsGd80S9m:-NR-Fk1K1NEHw8IIzeSN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c8025085f326e821c1a36676cbe34846113dbc73/pkg/server/combined_statement_stats.go#L697)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

We don't use the aggregation interval anywhere, it can be removed here too
</blockquote></details>

Done.
___
*[`pkg/ccl/serverccl/statusccl/tenant_status_test.go` line 371 at r21](https://reviewable.io/reviews/cockroachdb/cockroach/98815#-NR-F5k8Do_fwHrWQN2B:-NR-FlfE7k2jdabNNUc6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd4f05e3c95b8ae10459fd13eb95bc113936f5fc/pkg/ccl/serverccl/statusccl/tenant_status_test.go#L371)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

this line is no longer necessary, since you don't have any new errors
</blockquote></details>

Done.

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98815)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`pkg/ccl/serverccl/statusccl/tenant_status_test.go` line 447 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/98815#-NQziulcE6UatP_RUeOw:-NR-QHji4AmC5bh1UnrQ:b-wqbsvu) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fb4a9acba7b0486f16552f40fd94d8690ab29ed/pkg/ccl/serverccl/statusccl/tenant_status_test.go#L447)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Well I checked the code and it in the code for Flush, if this is disabled, we do not flush.  So this test actually was just testing in-memory both times before.
</blockquote></details>

Ah got it! thanks!

**Review by maryliag — APPROVED** [review]
Amazing work on this! :rocket: 
Just one change on the limit options, otherwise

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98815#-:-NR-grxFEhHJWaJlGgZ6:bwf3trg)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`pkg/server/combined_statement_stats.go` line 256 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/98815#-NQzhQVC2ONK_PtjR7AB:-NR-fZ-v5o8i1EYoDQDv:b-yzlh8v) ([raw file](https://github.com/cockroachdb/cockroach/blob/3860273002cfae7a66f3bd8d5fe3e65e2923aa24/pkg/server/combined_statement_stats.go#L256)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

It's so that we can use the statistics column in the sort. Since `merge_statement_statistics` isn't recognized as an aggregate function, we can't use it in the `ORDER BY`.
</blockquote></details>

ah make sense!
___
*[`pkg/ui/workspaces/cluster-ui/src/util/sqlActivityConstants.ts` line 16 at r23](https://reviewable.io/reviews/cockroachdb/cockroach/98815#-NR-hD6v1DBZDGrfXDSx:-NR-hD6v1DBZDGrfXDSy:b-3hwbn2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e2420435b7d7cc252646a751644b82113cba098/pkg/ui/workspaces/cluster-ui/src/util/sqlActivityConstants.ts#L16)):*
> ```XML
> 
> export const limitOptions = [
>   { value: 100, label: "100" },
> ```

From the feedback we decided on 25, 50, 100, 500.

**Review by maryliag — COMMENTED** [review]
> Reviewed 1 of 12 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98815)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/util/sqlActivityConstants.ts` line 34 at r25](https://reviewable.io/reviews/cockroachdb/cockroach/98815#-NR-kqcL1F1Im7qXRjC-:-NR-kqcL1F1Im7qXRjC0:b-irwh8b) ([raw file](https://github.com/cockroachdb/cockroach/blob/af634650ccd5dea233a10a44d6288fd0331a7297/pkg/ui/workspaces/cluster-ui/src/util/sqlActivityConstants.ts#L34)):*
> ```XML
>       return "Contention Time";
>     case SqlStatsSortOptions.PCT_RUNTIME:
>       return "% All Run Time";
> ```

nit: % of All Runtime

**Comment by xinhaoz** [comment]
bors r=maryliag

**Pull request merged**
