### PR TITLE
docs: update sql function codelab

### PR DESCRIPTION
**Pull request by thoszhang**
Update codelab to reflect changes in filepaths and variable names.

Release note: None

### CODE REVIEW

**Review by benesch — APPROVED** [review]
Thanks!

**Review by dt — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32063#-:-LQApCtk8XSNoAQgxkYD:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by benesch** [comment]
While we're sorting out Bors permissions, this'll at least allow you to r+ this one PR:

bors delegate

**Comment by dt** [comment]
I think it should work now.

**Pull request merged**
