### PR TITLE
sql: some fixes around Annotations handling

### LINKED ISSUE #112821: sql: v23.1.11: "no Annotations provided" when cleaning up paused portal info
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4563466675/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4563466675/?referrer=webhooks_plugin)

Panic Message:

```
crash_reporting.go:390: session: no bytes in account to release, current 0, free 8
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/util/log/logcrash.ReportOrPanic
  | 	github.com/cockroachdb/cockroach/pkg/util/log/logcrash/crash_reporting.go:390
  | github.com/cockroachdb/cockroach/pkg/util/mon.(*BoundAccount).Shrink
  | 	github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:915
  | github.com/cockroachdb/cockroach/pkg/sql.(*PreparedPortal).close
  | 	github.com/cockroachdb/cockroach/pkg/sql/prepared_stmt.go:242
  | github.com/cockroachdb/cockroach/pkg/sql.(*prepStmtNamespace).closeAllPortals
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1816
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).close
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1183
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1158
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:900
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.NewFmtCtx
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/format.go:349
  | github.com/cockroachdb/cockroach/pkg/sql.formatStmtKeyAsRedactableString
  | 	github.com/cockroachdb/cockroach/pkg/sql/exec_util.go:3634
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).getCommonSQLEventDetails
  | 	github.com/cockroachdb/cockroach/pkg/sql/event_log.go:190
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).logEventsWithOptions
  | 	github.com/cockroachdb/cockroach/pkg/sql/event_log.go:221
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).logOperationalEventsOnlyExternally
  | 	github.com/cockroachdb/cockroach/pkg/sql/exec_log.go:427
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).maybeLogStatementInternal
  | 	github.com/cockroachdb/cockroach/pkg/sql/exec_log.go:403
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).maybeLogStatement
  | 	github.com/cockroachdb/cockroach/pkg/sql/exec_log.go:134
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine.func4.1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1561
  | github.com/cockroachdb/cockroach/pkg/sql.(*cleanupFuncStack).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/prepared_stmt.go:272
  | github.com/cockroachdb/cockroach/pkg/sql.(*portalPauseInfo).cleanupAll
  | 	github.com/cockroachdb/cockroach/pkg/sql/prepared_stmt.go:395
  | github.com/cockroachdb/cockroach/pkg/sql.(*PreparedPortal).close
  | 	github.com/cockroachdb/cockroach/pkg/sql/prepared_stmt.go:245
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).deletePortal
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:577
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execBind
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:385
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2321
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2105
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:902
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:310
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (2) session: no bytes in account to release, current 0, free 8
Error types: (1) *withstack.withStack (2) *errutil.leafError
-- report composition:
*errutil.leafError: session: no bytes in account to release, current 0, free 8
crash_reporting.go:390: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/pgwire/conn.go#L309-L311](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/pgwire/conn.go#L309-L311)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L901-L903](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L901-L903)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L2104-L2106](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L2104-L2106)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L2320-L2322](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L2320-L2322)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor_prepare.go#L384-L386](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor_prepare.go#L384-L386)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor_prepare.go#L576-L578](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor_prepare.go#L576-L578)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/prepared_stmt.go#L244-L246](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/prepared_stmt.go#L244-L246)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/prepared_stmt.go#L394-L396](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/prepared_stmt.go#L394-L396)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/prepared_stmt.go#L271-L273](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/prepared_stmt.go#L271-L273)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor_exec.go#L1560-L1562](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor_exec.go#L1560-L1562)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/exec_log.go#L133-L135](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/exec_log.go#L133-L135)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/exec_log.go#L402-L404](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/exec_log.go#L402-L404)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/exec_log.go#L426-L428](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/exec_log.go#L426-L428)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/event_log.go#L220-L222](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/event_log.go#L220-L222)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/event_log.go#L189-L191](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/event_log.go#L189-L191)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/exec_util.go#L3633-L3635](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/exec_util.go#L3633-L3635)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/sem/tree/format.go#L348-L350](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/sem/tree/format.go#L348-L350)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L899-L901](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L899-L901)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L1157-L1159](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L1157-L1159)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L1182-L1184](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L1182-L1184)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L1815-L1817](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L1815-L1817)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/prepared_stmt.go#L241-L243](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/prepared_stmt.go#L241-L243)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/util/mon/bytes_usage.go#L914-L916](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/util/mon/bytes_usage.go#L914-L916)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/util/log/logcrash/crash_reporting.go#L389-L391](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/util/log/logcrash/crash_reporting.go#L389-L391)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 310
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 902
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2105
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2321
pkg/sql/conn_executor_prepare.go in pkg/sql.(*connExecutor).execBind at line 385
pkg/sql/conn_executor_prepare.go in pkg/sql.(*connExecutor).deletePortal at line 577
pkg/sql/prepared_stmt.go in pkg/sql.(*PreparedPortal).close at line 245
pkg/sql/prepared_stmt.go in pkg/sql.(*portalPauseInfo).cleanupAll at line 395
pkg/sql/prepared_stmt.go in pkg/sql.(*cleanupFuncStack).run at line 272
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine.func4.1 at line 1561
pkg/sql/exec_log.go in pkg/sql.(*planner).maybeLogStatement at line 134
pkg/sql/exec_log.go in pkg/sql.(*planner).maybeLogStatementInternal at line 403
pkg/sql/exec_log.go in pkg/sql.(*planner).logOperationalEventsOnlyExternally at line 427
pkg/sql/event_log.go in pkg/sql.(*planner).logEventsWithOptions at line 221
pkg/sql/event_log.go in pkg/sql.(*planner).getCommonSQLEventDetails at line 190
pkg/sql/exec_util.go in pkg/sql.formatStmtKeyAsRedactableString at line 3634
pkg/sql/sem/tree/format.go in pkg/sql/sem/tree.NewFmtCtx at line 349
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn.func1 at line 900
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).closeWrapper at line 1158
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).close at line 1183
pkg/sql/conn_executor.go in pkg/sql.(*prepStmtNamespace).closeAllPortals at line 1816
pkg/sql/prepared_stmt.go in pkg/sql.(*PreparedPortal).close at line 242
pkg/util/mon/bytes_usage.go in pkg/util/mon.(*BoundAccount).Shrink at line 915
pkg/util/log/logcrash/crash_reporting.go in pkg/util/log/logcrash.ReportOrPanic at line 390
```

### Tags

| Tag | Value |
| --- | --- |
| Command | mt start-sql |
| Environment | v23.1.11 |
| Go Version | go1.19.10 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.11 |
| Cockroach SHA | 62ad175cbc0e9041d993ea1cc911e07d279671f5 |
| # of CPUs | 32 |
| # of Goroutines | 357 |

Jira issue: CRDB-32616

### PR DESCRIPTION
**Pull request by yuzefovich**
**sql: update Annotations of EvalCtx to refer to new ones in prepare**

It looks like in most places where we override `SemaCtx.Annotations` we
also make the corresponding update to `EvalCtx.Annotations` too, but we
were missing such an update in the `prepare` code path. This commit
fixes that.

Release note: None

**sql: prevent nil pointer panic with pausable portals and logging**

Formatting a stmt for logging purposes requires non-nil `Annotations` to
be set on the eval ctx of the planner. However, in some code paths we
set those to `nil`, and usually it's not a problem (because we'll update
it afterwards), but with pausable portal cleanup it seems possible for
`Annotations` to remain `nil` (e.g. because we hit an error before we
could update the planner). This commit prevents this type of a panic
from occurring.

Fixes: #112821.

Release note: None

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114760#-:-NjimUZ42v3Znyc3V02i:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss and @rharding6373)

**Comment by mgartner** [comment]
*[`pkg/sql/conn_executor_exec.go` line 1736 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114760#-NjimY3rDDJuzshaLw4C:-NjimY3rDDJuzshaLw4D:b-rhrn47) ([raw file](https://github.com/cockroachdb/cockroach/blob/a28ddb45980d413d6dfc31255a82fd9075d255e4/pkg/sql/conn_executor_exec.go#L1736)):*
> ```Go
> 						// executed, but then we never set the annotations on
> 						// the planner. Formatting the stmt for logging requires
> 						// non-nil annotations.
> ```

You don't have a reproduction for this, do you?

**Review by rharding6373 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114760#-:-Njn0eWZDk3iqTpS68R_:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @rafiss and @yuzefovich)

**Review by yuzefovich — COMMENTED** [review]
TFTRs!

bors

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114760#-:-NjnZjMpA9oSh7WxhdEh:b-axxl2n)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner and @rafiss)

___
*[`pkg/sql/conn_executor_exec.go` line 1736 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114760#-NjimY3rDDJuzshaLw4C:-NjnZOdt3nqODJFOvPxm:bwpg3xk) ([raw file](https://github.com/cockroachdb/cockroach/blob/a28ddb45980d413d6dfc31255a82fd9075d255e4/pkg/sql/conn_executor_exec.go#L1736)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

You don't have a reproduction for this, do you?
</blockquote></details>

No, this is just a hypothetical explanation I came up with. Probably if I were to spend like half an hour, I could trigger the problem (perhaps with using some testing knobs), but it doesn't seem worth it given that multiple active portals are disabled by default (which is why I'm also leaning towards not backporting this change).

**Pull request merged**
