### PR TITLE
sql: add is_sharded to crdb_internal.table_indexes

### LINKED ISSUE #73057: Add details about hash-sharded attributes to crdb_internal.table_indexes table
**Is your feature request related to a problem? Please describe.**
I want to be able to find out which indexes in a database are hash-sharded and how many buckets the index is using.

**Describe the solution you'd like**
I'd like to be able to query the table_indexes table in crdb_internal to get details about the hash-sharded attributes.
Currently, I get this set of fields:
```
root@localhost:26257/prod> select * from crdb_internal.table_indexes limit 1;
  descriptor_id | descriptor_name | index_id |    index_name     | index_type | is_unique | is_inverted
----------------+-----------------+----------+-------------------+------------+-----------+--------------
           2301 | table1000000    |        2 | table1000000_idx  | primary    |   true    |    false
```

**Describe alternatives you've considered**
I think I could query the `create table` statement and do some fancy pattern matching.  I also tried doing `show indexes from table_name` but it doesn't have any HSI info either.

**Additional context**
I'm doing my testing on 21.1.9.  If this feature has been added in later versions, I haven't checked.

Epic CRDB-7363

### PR DESCRIPTION
**Pull request by chengxiong-ruan**
fixes #73057

Release note (bug fix): crdb_internal.table_indexes now shows if an
index is sharded or not.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> Release note (bug fix): crdb_interl.table_indexes now shows if an
> index is sharded or not.

Can you fix up this release note too? I don't remember which gets used but I think it's the PR description. 

> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73380#-:-MpvrPNu8TKZ_Em2P_6M:b-e5633s)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan and @postamar)

___
*[pkg/sql/crdb_internal.go, line 2558 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73380#-MpvrVPd6qliK9yuFMlF:-MpvrVPd6qliK9yuFMlG:b-9qitoc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cee82916ee442a3729c826cbe1a6898a11ca0aa/pkg/sql/crdb_internal.go#L2558)):*
> ```
>   is_inverted      BOOL NOT NULL,
> 	is_sharded       BOOL NOT NULL
> ```
nit: tabs v. spaces
___
*[pkg/sql/logictest/testdata/logic_test/dependencies, line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73380#-Mpvr_N32m94QWWS4XL-:-Mpvr_N32m94QWWS4XL0:b3tq2eh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d33d9ac3eac7c907f1d4d92c56bb0ec08818863f/pkg/sql/logictest/testdata/logic_test/dependencies#L45)):*
> ```
> 
> query ITITTBBB colnames
> SELECT * FROM crdb_internal.table_indexes WHERE descriptor_name LIKE 'test_%' ORDER BY descriptor_id, index_id
> ```

it'd be good to see a test where the value is true.

**Review by chengxiong-ruan — COMMENTED** [review]
fixed

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73380#-:-Mpw-d3H886Mbmyxn9hT:b-7ql1td)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/sql/crdb_internal.go, line 2558 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73380#-MpvrVPd6qliK9yuFMlF:-Mpw-iOl56MF-_1dkSnl:bd4j4ip) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cee82916ee442a3729c826cbe1a6898a11ca0aa/pkg/sql/crdb_internal.go#L2558)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
>   is_inverted      BOOL NOT NULL,
> 	is_sharded       BOOL NOT NULL
> ```
nit: tabs v. spaces
</blockquote></details>

good eyes!
___
*[pkg/sql/logictest/testdata/logic_test/dependencies, line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73380#-Mpvr_N32m94QWWS4XL-:-Mpw-U305ZoW64XKG8JX:b-kqd5q8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d33d9ac3eac7c907f1d4d92c56bb0ec08818863f/pkg/sql/logictest/testdata/logic_test/dependencies#L45)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

it'd be good to see a test where the value is true. 
</blockquote></details>

added a subtest to `hash_sharded_index` logic test

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73380#-:-Mpw4ww64GW1ZnFULIqm:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @postamar)

___
*[pkg/sql/logictest/testdata/logic_test/hash_sharded_index, line 672 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73380#-Mpw52EC8uzAwZZ-nxQR:-Mpw52EC8uzAwZZ-nxQS:bim25xg) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b715f745390f6c5b267cec68325ccbd9b70daf8/pkg/sql/logictest/testdata/logic_test/hash_sharded_index#L672)):*
> `poor_t`

cute :)

**Comment by chengxiong-ruan** [comment]
TFTR!

bors r+

**Pull request merged**
