### PR TITLE
sql/schemachanger: version gate element creation

### PR DESCRIPTION
**Pull request by ajwerner**
Commit 1: fix minSupportedVersion of `ADD COLUMN` in new schema changer
from v22.1 to v22.2
Commit 2: We cannot create elements the old version of the code does not know about.

Release justification: fixed mixed version incompatibility
Release note: None

### CODE REVIEW

**Review by fqazi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86774)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[`pkg/sql/schemachanger/scbuild/build.go` line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86774#-NAf7wQb9q0R8TZM-toV:-NAf7wQb9q0R8TZM-toW:btbwvkw) ([raw file](https://github.com/cockroachdb/cockroach/blob/39764bfaca953e1ff31eb64737b4976cca11ac3b/pkg/sql/schemachanger/scbuild/build.go#L101)):*
> ```Go
> 		// Exclude targets which are not yet usable in the currently active
> 		// cluster version.
> 		if !version.IsActive(screl.MinVersion(e.element)) {
> ```

Are there any concerns about funny side effects because of missing elements and transactions? We tend to stack states together when multiple statements are used.

**Comment by ajwerner** [comment]
> Are there any concerns about funny side effects because of missing elements and transactions? We tend to stack states together when multiple statements are used.

We don't really support using the declarative schema changer in explicit transactions officially, and we don't support any statements where that is interesting in the mixed version state, so I'm not worried about it.

**Review by fqazi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86774)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by ajwerner** [comment]
Will fix #86659

**Comment by Xiang-Gu** [comment]
Once #87459 is merged into master, I will rid it (commit 1) from this PR. After that we should be able to bors it.

**Pull request merged**
