### PR TITLE
sql/parser: use RoleSpec for ALTER ROLE

### PR DESCRIPTION
**Pull request by rafiss**
Release note (sql change): CURRENT_USER and SESSION_USER can now be used
as the role identifier in ALTER ROLE statements.

Release note (backward-incompatible change): Placeholder values (e.g. `$1`)
can no longer be used for role names in ALTER ROLE statements.

Release note (backward-incompatible change): Placeholders (e.g. `$1`)
can no longer be used for role names in CREATE/DROP ROLE statements.

### CODE REVIEW

**Review by RichardJCai — APPROVED** [review]
LGTM with minor nit

**Review by RichardJCai — APPROVED** [review]
> Reviewed 5 of 11 files at r1, 17 of 23 files at r2, 20 of 22 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71498)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/alter_role.go, line 543 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71498#-MlzZnJZ-hkU-m1TO6ti:-MlzZnJZ-hkU-m1TO6tj:b-nlqbat) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c8ef7cc324ee99cb16f02ed0c4715f2cafc42a6/pkg/sql/alter_role.go#L543)):*
> ```Go
> 		return true, security.MakeSQLUsernameFromPreNormalizedString(""), nil
> 	}
> 	if n.roleName.Normalized() == "" {
> ```

Can use `IsUndefined()`

**Review by rafiss — COMMENTED** [review]
tftr!

bors r=RichardJCai

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71498#-:-MlzdmPeDR3X3uPMqYL3:b-23iapl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[pkg/sql/alter_role.go, line 151 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71498#-MlqkVlzQvVfcg2di627-r4-151:-MlzdlBaC_yHpvfVSvI0:b-7ql1td) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c8ef7cc324ee99cb16f02ed0c4715f2cafc42a6/pkg/sql/alter_role.go#L151)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Sorry my reviewable comment didn't go through for some reason. My nit is that you can use `IsUndefined()` here I think.
</blockquote></details>

fixed

**Comment by andy-kimball** [comment]
@rafiss, what was the reason to break backwards-compatibility here? This broke CC and will probably break some customers as well. I assume there was some really compelling reason why we had to do this?

**Comment by rafiss** [comment]
Huh, it's a bit surprising that CC is using a pre-alpha version of CockroachDB. I heard about the CC issue -- but in a normal upgrade this change would be evident in backward-incompatible change release notes.

This change was done to support the `CURRENT_USER` and `SESSION_USER` aliases in the CREATE/ALTER ROLE commands. They are special syntax keywords which are handled within the parser. It matches the [Postgres syntax](https://www.postgresql.org/docs/current/sql-alterrole.html) so we made this change to get some improved compatibility with tooling and to support a useful feature.

Theoretically we could still support placeholders for this with a bit of extra work, but here was my rationale for not doing so:
- It aligns more closely with how every other identifier in SQL works. For example, you can't use a placeholder for a table name.
- The way our parser handles usernames is a bit of a mess in versions 21.2 and earlier. It inconsistently would treat usernames as string constants, or as identifiers, or as generic expressions. Given that placeholders were already not allowed for usernames in many other contexts, I thought this would be OK.
- We never documented that we do accept placeholders for the username.
- Allowing placeholders here is a CRDB-specific invention, as far as I can tell.

With all of the above, I was almost getting to the point where I thought it was an accident that we ever did allow placeholders here. I'd honestly be pretty surprised if many customers were relying on this. There is somewhat compelling evidence for this not being widely used in our telemetry data -- let me know if you'd like me to share that with you separately.

Additionally, I'm working on a little bit of guidance for when backwards-incompatible changes are OK. There are quite a few other SQL bugfixes we'd like to do, but the fix itself would have incompatibility implications. @jordanlewis and I have been thinking of multi-dimensional criteria including "ease of discovering the change," "ease of fixing the incompatibility," and "severity of not accounting for the change."

This change was made before we discussed this kind of guidance, but to apply that framework:
- this change is easy to discover, since the error message tells you what part of the statement isn't working;
- it's easy to fix, since you just need to stop using placeholders;
- and the severity seems medium, since it's unlikely to break any business logic (more likely would affect tests and operator-initiated setup).

---

All that being said, if these arguments are not swaying you, let me know, and I can spend a bit of time trying to re-add placeholder support here.

**Comment by andy-kimball** [comment]
Thanks for the detailed justification. It sounds like your team has thought this through carefully, which was the main thing I wanted to verify. I'm content to let your team own the decision.

**Pull request merged**
