### PR TITLE
 roachprod: add DNS entries for roachprod hosts

### PR DESCRIPTION
**Pull request by dt**
This adds support for maintaining a Google Cloud DNS zone with entries for hosts in roachprod clusters.
Whenever we re-sync the on-disk cluster listing, if we are configured with default (i.e. cockroach labs) Google Cloud settings, then we also update the google cloud DNS zone.

These aliases can then be used in 'adminurl' to make it easiler to keep track of which nodes you're interacting with while monitoring/debugging.

Release note: none.

Also:

roachprod: sync after gc’ing / destroying clusters
After destroying a cluster (explicitly or via sync), this updates the in-memory clusters to remove it. It then rewrites the on-disk synced cluster listing from that updated in-memory state.

### CODE REVIEW

**Comment by dt** [comment]
@ajwerner if you like roachprod productivity hacks, here's another one for you

**Review by ajwerner — APPROVED** [review]
:lgtm:

Neat

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35295#-:-L_DMMtz4lCG0iQr-li2:b-jxf52d)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt and @mberhault)

___
*[pkg/cmd/roachprod/vm/gce/utils.go, line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35295#-L_DLs5nA1C45X7fbBXI:-L_DLs5o9jOMsstkwgxs:b5wotkk) ([raw file](https://github.com/cockroachdb/cockroach/blob/f310e0afe6f994fcdab69569070d336a71dbb301/pkg/cmd/roachprod/vm/gce/utils.go#L137)):*
> ```Go
> 	defer f.Close()
> 	for _, vm := range names {
> 		fmt.Fprintf(f, "%s 60 IN A %s\n", vm.Name, vm.PublicIP)
> ```


More for conversation than feedback, if you're feeling busy or uninterested by the questions please ignore

Just curious how you decided on 60 seconds. Do you have any concerns about stale records and/or propagation time? Not that this relates to propagation time.

**Comment by dt** [comment]
Google Cloud DNS has some non-trivial propagation time, i.e. > 3s, which is why I didn't simply replace the public IP string with the hostname -- if you have an annoying negative caching resolver grab on to that NXDOMAIN, I don't want it to prevent actual cluster admin actions, so those are all still done by IP. 

The dns name is purely for humans using the UI, so you can keep track of which cluster/node a given tab belongs to, e.g. if you're comparing lots of profiles or whatever.

The short TTL is because clusters are pretty dynamic and I don't want to be sitting around for a long time waiting on some DNS caching. Given that this is only for humans opening the UI, I don't think the extra couple ms once a minute is a big deal.

**Comment by mberhault** [comment]
LGTM.

**Comment by dt** [comment]
switched subdomain to `roachprod.crdb.io` and added a check to `adminurl` to confirm that DNS actually works and automatically fallback to the current IPs if it doesn't.

**Comment by mberhault** [comment]
LGTM. I assume you're the only one who ran this? The `clusters` zone will need to be deleted.

**Review by petermattis — CHANGES_REQUESTED** [review]
The idea looks good, but I have a question about how this works if multiple people run `roachprod create` simultaneously.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35295#-:-L_DwVixCDOuqJMXIksV:b7ghm41)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @dt, and @mberhault)

___
*[pkg/cmd/roachprod/main.go, line 712 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35295#-L_Dw4Je6PYKz4tXDK1C:-L_Dw4Je6PYKz4tXDK1D:bc35rv2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dce746c718029810f86a389aa729712d3e2d2a4/pkg/cmd/roachprod/main.go#L712)):*
> ```Go
> 		vms = append(vms, c.VMs...)
> 	}
> 	if err := gce.SyncDNS(vms); err != nil {
> ```

`syncAll` is called every time a cluster is created or `list` or `sync` are run. I worry that we'll be updating the DNS very frequently and that we're doing so in a non-synchronized manner. Can my call to `SyncDNS` remove a DNS entry for the cluster you just created?

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35295)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @dt, @mberhault, and @petermattis)

___
*[pkg/cmd/roachprod/main.go, line 712 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35295#-L_Dw4Je6PYKz4tXDK1C:-L_E0One3Zprv1H_pc2b:bqdwt6m) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dce746c718029810f86a389aa729712d3e2d2a4/pkg/cmd/roachprod/main.go#L712)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`syncAll` is called every time a cluster is created or `list` or `sync` are run. I worry that we'll be updating the DNS very frequently and that we're doing so in a non-synchronized manner. Can my call to `SyncDNS` remove a DNS entry for the cluster you just created?
</blockquote></details>

I think we `listCloud` before `syncAll`ing, including after node creation in `create`, so I think two racing updates should usually both be derived from the same cloud data, not local state. 

In the worst case, if somehow we do mess it up, a) just running `sync` should fix it b) `adminurl` will fallback to to printing IPs if it can't resolve and will suggest the re-sync.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35295)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @dt, and @mberhault)

___
*[pkg/cmd/roachprod/main.go, line 712 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35295#-L_Dw4Je6PYKz4tXDK1C:-L_ElMRx910YktTM6Y5l:b-fe0j5c) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dce746c718029810f86a389aa729712d3e2d2a4/pkg/cmd/roachprod/main.go#L712)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I think we `listCloud` before `syncAll`ing, including after node creation in `create`, so I think two racing updates should usually both be derived from the same cloud data, not local state. 

In the worst case, if somehow we do mess it up, a) just running `sync` should fix it b) `adminurl` will fallback to to printing IPs if it can't resolve and will suggest the re-sync.
</blockquote></details>

Ack. Ok. 

Is updating the DNS fast? Mostly just curious as some other GCE operations are surprisingly slow.

**Comment by dt** [comment]
when I was playing with it on cli `dns record-set` calls seemed to complete in under a second (though their effects often take 5s to become visible on the actual edge name servers). 

The delay is part of why I didn't try to replace the IPs with hostnames internally, and instead just use them as a nice-to-have in `adminurl` -- by that time they're usually resolvable, and if they aren't, falling back to the IP is no worse than it is today.

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35295#-:-L_Esgpg5WjAa9Y752QG:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @dt, and @mberhault)

**Comment by dt** [comment]
huh, that's strange: it just prints the error to stdout, but it doesn't bail out on failure, so it _should't_ break anything. Looking.

**Comment by dt** [comment]
I'll bet it isn't the DNS stuff at all, but the added `syncAll` I put after destroying a cluster: https://github.com/cockroachdb/cockroach/pull/35295/commits/25579972b85fb0a43e113af18e7c1b583d4f782b#diff-5db51b6a4a95bc32c7a70c98bacbdb3d

**Comment by petermattis** [comment]
> I'll bet it isn't the DNS stuff at all, but the added syncAll I put after destroying a cluster: 2557997#diff-5db51b6a4a95bc32c7a70c98bacbdb3d

I'm not seeing why that would cause a problem. What scenario are you imagining?

Regardless, we might want to revert this PR for now.

**Pull request merged**
