### PR TITLE
sql: create general logging job to capture index usage stats

### LINKED ISSUE #72486: Capture index usage metrics in telemetry logging channel
This issue tracks capturing index usage metrics for all customer workloads. This will help us determine how many customers are suffering from unused indexes and measure our progress in helping developers design and tune their indexing strategy. We should take at least 8 hour periodic snapshots of this information

We should capture the envelope including the following event payload: 

 CREATE TABLE telemetry_logs_index_usage_statistics_raw (
                                       database_name NOT NULL STRING,
                                       database_id INT8 NOT NULL,
                                       table_name NOT NULL STRING,
                                       table_id INT8 NOT NULL,
                                       ti.index_name INT8 NOT NULL,
                                       index_id INT8 NOT NULL,
                                       index_type NOT NULL STRING,
                                       total_reads INT8 NOT NULL,
                                       is_unique BOOL NOT NULL,
                                       is_inverted BOOL NOT NULL,
                                       last_read TIMESTAMPTZ NULL
)

crdb_internal tables that contain this information:

- crdb_internal.index_usage_statistics
- crdb_internal.table_indexes
- crdb_internal.databases

Sample user query:

  ```
  SELECT
  current_database() as database_name,
   ti.descriptor_name as table_name,
   ti.descriptor_id as table_id,
   ti.index_name,
   ti.index_id,
   ti.index_type,
   ti.is_unique,
   ti.is_inverted,
   total_reads,
   last_read
  FROM crdb_internal.index_usage_statistics AS us
  JOIN crdb_internal.table_indexes ti
  ON us.index_id = ti.index_id
   AND us.table_id = ti.descriptor_id
  ORDER BY total_reads ASC;
  ```

Epic: CRDB-10495

Jira issue: CRDB-11177

### PR DESCRIPTION
**Pull request by THardy98**
Resolves: https://github.com/cockroachdb/cockroach/issues/72486

Previously, we did not capture index usage metrics to our telemetry logging
channel. The intention of this change is to introduce a scheduler for jobs that
emit logging events.

Currently, we want to capture index usage statistics to the telemetry logging
channel on a time interval, but being able to emit scheduled logs for different
statistics/events would be useful telemetry going forward, which motivates the
creation of a scheduler that supports different logging jobs.

This change introduces the `scheduledloggingjobs` package.
`CreateScheduledLoggingJob` in `scheduledloggingjobs`, allows you to create a
scheduler with parameters for:
- label
- schedule interval
- executor type
- schedule details
- execution arguments

The Resumer and Executor logic for the scheduled jobs resides in
`sql/scheduled_logging_jobs.go`. The Resumer receives a callback function that
returns the logging events it wants to emit. The Executor receives the job
details/progress (used to create the job record when the job is executed) and
job type (to check that a job of the same type isn't already running when we
try to create the job).

The `scheduledloggingjobs` package also contains a `Controller` whose purpose
is to `Start` all the scheduled logging jobs in its interface. The
`Controller`'s `Start` method is hooked into the startup of the `sql.Server`.

Assuming its `jobs.proto` definitions and `wrap.go` cases are covered, a new
logging job can be added to this by:
- defining its resume callback function
- registering its log resumer and executor with
  `RegisterLogResumerAndScheduleExecutor`
- defining its arguments (label, schedule interval, executor type, schedule
  details, execution arguments) and calling `CreateScheduledLoggingJob`
- adding it to the `Controller` interface, and `Start` method (if you want to
  create the scheduled job on server startup)

This change was made for internal use in mind, I didn't consider a SQL
interface to create these schedules.

Release note (sql change): Initial implementation of a general logging job,
used to create a job that captures index usage statistics to the telemetry
logging channel.

### CODE REVIEW

**Review by miretskiy — COMMENTED** [review]
> Reviewed 3 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76752)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @Azhng, and @THardy98)

___
*[-- commits, line 11 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76752#-Mw8LpLf76hbuv1k2nme):*

Is there an epic/doc/issue you can point me to that describes what this is supposed to accomplish?
Is there an SQL interface for creating such schedules?  What's the intended usage and use case?  Basically, any information
that can help me review the code better.

**Review by miretskiy — COMMENTED** [review]
> Reviewed 1 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76752)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @Azhng, and @THardy98)

___
*[pkg/sql/scheduledloggingjobs/scheduled_logging_job.go, line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76752#-Mw8RRv398tXhClpEHIF:-Mw8RRv398tXhClpEHIG:b-phwpvc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6fdb20a98b1a733c7b2249b556ff32e71cac0d9/pkg/sql/scheduledloggingjobs/scheduled_logging_job.go#L31)):*
> ```Go
> //////////////////////////////////////
> //////// SCHEDULED JOB LOGIC	////////
> //////////////////////////////////////
> ```

nit: we don't really have this comment style in our codebase...
___
*[pkg/sql/scheduledloggingjobs/scheduled_logging_job.go, line 150 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76752#-Mw8RtINBpgeR4Gb4yOz:-Mw8RtIOEMrwwSrRWjSV:b-ubba8s) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6fdb20a98b1a733c7b2249b556ff32e71cac0d9/pkg/sql/scheduledloggingjobs/scheduled_logging_job.go#L150)):*
> ```Go
> // If an existing logging job of the same type is found, an error is returned,
> // preventing a duplicate job from being created.
> func checkExistingLoggingJob(
> ```

normally, this should be needed -- scheduled job system, by default, ensures only 1 instance of job run at a time...

**Review by THardy98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76752)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @Azhng, @miretskiy, and @THardy98)

___
*[-- commits, line 11 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76752#-Mw8LpLf76hbuv1k2nme):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>


Is there an epic/doc/issue you can point me to that describes what this is supposed to accomplish?
Is there an SQL interface for creating such schedules?  What's the intended usage and use case?  Basically, any information
that can help me review the code better.
</blockquote></details>

Linked the issue this is intended to resolve, and a quick note about the idea behind this change.

**Review by THardy98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76752)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @Azhng, and @miretskiy)

___
*[pkg/sql/scheduledloggingjobs/scheduled_logging_job.go, line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76752#-Mw8RRv398tXhClpEHIF:-Mw8ciN66xTB2J5G1-Gx:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6fdb20a98b1a733c7b2249b556ff32e71cac0d9/pkg/sql/scheduledloggingjobs/scheduled_logging_job.go#L31)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

nit: we don't really have this comment style in our codebase...
</blockquote></details>

Removed.
___
*[pkg/sql/scheduledloggingjobs/scheduled_logging_job.go, line 150 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76752#-Mw8RtINBpgeR4Gb4yOz:-Mw8cjAf9yXbtFxzn98j:bqacea5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6fdb20a98b1a733c7b2249b556ff32e71cac0d9/pkg/sql/scheduledloggingjobs/scheduled_logging_job.go#L150)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

normally, this should be needed -- scheduled job system, by default, ensures only 1 instance of job run at a time...
</blockquote></details>

Oh I didn't know that. How does it check whether an instance is of a job is already running?

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76752)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @miretskiy, and @THardy98)

___
*[pkg/sql/conn_executor.go, line 488 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76752#-Mw8w3Cm4x7VlfuPJIRC:-Mw8w3Cm4x7VlfuPJIRD:bz02vbq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5db48598f297a0c6a2f7339c4d86619f484837c/pkg/sql/conn_executor.go#L488)):*
> ```Go
> 	s.txnIDCache.Start(ctx, stopper)
> 
> 	s.scheduledLoggingJobsController.Start(ctx)
> ```

`.Start(ctx)` function here usually implies that there are one or more long-running background goroutines that need start using the `stopper` here. In CRDB we don't directly start a goroutine using the `go` keyword. Using the stopper here allows us to stop all the background goroutines when gracefully shutting down a server.

Looking at the `scheduledLoggingJobsController`, it seems like the `Start()` method simply starts a transaction and create the scheduled job record. This logic can live within the constructor of the object. Alternatively, if you want to follow the automatic job pattern, then you can kick off a background goroutine here that periodically wake up to check if there exists a schedule job record for your scheduled job. 
___
*[pkg/sql/scheduled_logging_job.go, line 32 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76752#-Mw8xBfm39OqmBfjaTps:-Mw8xBfm39OqmBfjaTpt:b-p3pw4c) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5db48598f297a0c6a2f7339c4d86619f484837c/pkg/sql/scheduled_logging_job.go#L32)):*
> ```Go
> 
> func init() {
> 	RegisterLogResumerAndScheduleExecutor(
> ```

Since you can only register jobs within the sql package, perhaps there's no need exporting this function ? 
___
*[pkg/sql/scheduledloggingjobs/captured_index_usage_stats.go, line 39 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76752#-Mw8ykzRB37-aPRljoHR:-Mw8ykzRB37-aPRljoHS:b-683ves) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5db48598f297a0c6a2f7339c4d86619f484837c/pkg/sql/scheduledloggingjobs/captured_index_usage_stats.go#L39)):*
> ```Go
> 	"sql.capture_index_usage_stats.telemetry.interval",
> 	"cron-tab interval to capture index usage statistics to the telemetry logging channel",
> 	"0 */8 * * *", /* defaultValue */
> ```

Hmm, what does this cronexpr mean in english :thinking: ?
___
*[pkg/sql/scheduledloggingjobs/captured_index_usage_stats.go, line 92 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76752#-Mw8yHub6TPSQXLG5Rvp:-Mw8yHub6TPSQXLG5Rvq:bq1vyb0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5db48598f297a0c6a2f7339c4d86619f484837c/pkg/sql/scheduledloggingjobs/captured_index_usage_stats.go#L92)):*
> ```Go
> 	expectedNumDatums = 10
> 	var allEvents []eventpb.EventPayload
> 	for _, databaseName := range allDatabaseNames {
> ```

What happen if the jobs is paused or cancelled while this loop is still running? 
___
*[pkg/sql/scheduledloggingjobs/scheduled_logging_job_controller.go, line 64 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76752#-Mw8yv_ADkt-cvbWYaaY:-Mw8yv_ADkt-cvbWYaaZ:bpyoot0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5db48598f297a0c6a2f7339c4d86619f484837c/pkg/sql/scheduledloggingjobs/scheduled_logging_job_controller.go#L64)):*
> ```Go
> // createCaptureIndexUsageStatsScheduledJob creates all scheduled logging jobs.
> // createCaptureIndexUsageStatsScheduledJob implements the sql.Controller interface.
> func (c *LoggingJobsController) createCaptureIndexUsageStatsScheduledJob(
> ```

During cluster startup, every single node will go and attempt to create this scheduled job (and since this schedule already exist, all will fail). This code is synchronous, which means this will block the cluster startup due to contention.

**Review by miretskiy — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76752)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @miretskiy, and @THardy98)

___
*[pkg/sql/scheduledloggingjobs/scheduled_logging_job.go, line 150 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/76752#-Mw8RtINBpgeR4Gb4yOz:-MwCrDG73QhlTI3cvzzh:bhya3ns) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6fdb20a98b1a733c7b2249b556ff32e71cac0d9/pkg/sql/scheduledloggingjobs/scheduled_logging_job.go#L150)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

Oh I didn't know that. How does it check whether an instance is of a job is already running?
</blockquote></details>

When you specify CreatedBy field when creating new job, that links the job with the schedule; and the scheduler will (by default) wait for the previous job completion
before starting the new one.

**Comment by miretskiy** [comment]
I'm curious: why is this whole thing implemented as a job?  Jobs are long running processes, that must survive
restarts.  Critically, jobs infrastructure provides ability for a long running job to checkpoint its progress.
As far as I can tell -- nothing here says job ... Just that you want to have a task that runs once every 8 hours, and does something.  Sounds like a daemon go routine that sleeps for 8 hours and wakes up periodically to do its thing?

**Review by THardy98 — COMMENTED** [review]
There were two reasons:
- the job system offered an existing way to create a long running scheduled background process
- with the idea to support different log-emitting jobs in the future, some of those jobs may make use other features of the job system like checkpointing (although this job doesn't)

That being said, maybe it's overkill and unlikely that background logging would make use of the job's system effectively.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76752#-:-MwDtJeS5XeX9eEwOPlR:bxnrlyj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @miretskiy, and @THardy98)

**Review by miretskiy — COMMENTED** [review]
I think we should err on the side of simplicity.  If this particular use case doesn't need jobs, then, let's not add another job type and schedule.  If feature uses prove the need to have that, then (as can be seen by this PR), unifying the code to use new schedule/job type is fairly straight forward.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76752#-:-MwE2is6DQOb8IOY3Qc4:b-ejt9y5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @miretskiy, and @THardy98)

**Review by THardy98 — COMMENTED** [review]
Sounds good, I'll close this PR. I've created PR #76886 in its place. Feel free to take a look at that if you like, although it doesn't use the jobs system.

TYFR @miretskiy and @Azhng 👍 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76752#-:-MwWjWGE19daJ9y0YNXt:bcsw34)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @miretskiy, and @THardy98)

**Pull request closed without merging**
