### PR TITLE
storage/reports: misc fixes

### PR DESCRIPTION
**Pull request by andreimatei**
See individual commits.

Release justification: see individual commits

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
friendly ping

cc @knz if Darin is too busy. We should have someone else in this party too.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40710#-:-Low18ZD38LMri0Fki37:b-36zhy2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @darinpp)

**Review by darinpp — APPROVED** [review]
lgtm

**Review by knz — APPROVED** [review]
LGTM with nits. The comment on "its" only needs a tweak if you intend to keep the commits separate, or you can squish them to only remain the final form. Your call.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40710#-:-Loz026T-Bh4OCz2nxrk:b-kik70e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/storage/reports/range_report.go, line 355 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40710#-Loz-aQk-6sNRYEi23eH:-Loz-aQk-6sNRYEi23eI:b-6b5qdm) ([raw file](https://github.com/cockroachdb/cockroach/blob/addff3d8253f9fe94bbbcf2b6fb7f1b19351accd/pkg/storage/reports/range_report.go#L355)):*
> ```Go
> 
> // zoneHasReport determines whether a given zone deserves a replication report.
> // A zone deserves a report if it's config overrides replication-related
> ```

..if its config...
___
*[pkg/storage/reports/reporter_test.go, line 936 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/40710#-Loz-wjoDGGyMoYxamMb:-Loz-wjp-HDXRFbd_5rp:b-ekka72) ([raw file](https://github.com/cockroachdb/cockroach/blob/77cdcae9e06d2783e2f6194968844c1b23f06bcd/pkg/storage/reports/reporter_test.go#L936)):*
> ```Go
> 	}
> 	require.True(t, len(systemZoneIDs) > 0, "expected some system zones, got none")
> 	// Remove the entries in systemZoneIDs that don't get critical localities reports.
> ```

either "locality reports" or "reports on localities". IIRC the genitive does not get pluralized in English.

**Review by andreimatei — COMMENTED** [review]
TFTRs

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40710#-:-Lozq_ar0J2o9FyBaXLm:b-6rbzir)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/storage/reports/range_report.go, line 355 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40710#-Loz-aQk-6sNRYEi23eH:-Lozq2js0xq6zozdG3Py:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/addff3d8253f9fe94bbbcf2b6fb7f1b19351accd/pkg/storage/reports/range_report.go#L355)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

..if its config...
</blockquote></details>

Done.
___
*[pkg/storage/reports/reporter_test.go, line 936 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/40710#-Loz-wjoDGGyMoYxamMb:-LozqSsX11F81M5yonS6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/77cdcae9e06d2783e2f6194968844c1b23f06bcd/pkg/storage/reports/reporter_test.go#L936)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

either "locality reports" or "reports on localities". IIRC the genitive does not get pluralized in English.
</blockquote></details>

Done.

**Review by andreimatei — COMMENTED** [review]
I had messed up something in the ranges report (r6); a zone with `Constraints` set but `NumReplicas` unset was causing an NPE.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40710#-:-LpEiL969dDa-5xeVl2F:b-g9g0ke)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40710#-:-LpEtJN_CZpzYypgTgcL:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

**Pull request merged**
