### PR TITLE
tests: new roachtest for job backward compatibility in new schema changer

### LINKED ISSUE #79840: sql/schemachanger/scbuild: ensure proper version gating for mixed-version state
**Is your feature request related to a problem? Please describe.**

We ought to produce the same elements in the mixed version state as we do in the old version. That's how we'll ensure compatibility. We need to both do that and to validate that we do that.

**Describe the solution you'd like**

We need to find a way to ensure that the same statement and initial state result in the same exact state protobufs between the previous version and the current version. We could do this in a variety of ways, including writing "golden" protos on a per-release basis or finding a way to link old code directly. 

**Describe alternatives you've considered**
There might be some way to do this as an integration test. I don't know that that would be better.

Jira issue: CRDB-15895

### PR DESCRIPTION
**Pull request by Xiang-Gu**
Commit 1: Moved a few functions so that we can reuse them in the next commit.
Commit 2: We added a roachtest that tests job backward compatibility in the
declarartive schema changer in a mixed-version cluster. Namely, we test that
DDL stmts supported in v22.1 can be planed in nodes running in v22.2 and the
jobs created can be adopted and finished by nodes running in v22.1.

Fixes: #79840

Release justification: test only changes.

Release note: None

### CODE REVIEW

**Comment by Xiang-Gu** [comment]
I think it's RFAL :)

**Review by fqazi — APPROVED** [review]
:lgtm: Only minor nitty comments.

> Reviewed 1 of 1 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86950#-:-NCL9m3xCGqbN3hV4ErA:b-bwdwuw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @fqazi and @Xiang-Gu)

___
*[`pkg/cmd/roachtest/tests/mixed_version_job_backward_compatibility_in_declarative_schema_changer.go` line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86950#-NCL9ben5QHGmnNjMxCL:-NCL9ben5QHGmnNjMxCM:b-z6m96c) ([raw file](https://github.com/cockroachdb/cockroach/blob/986fb92d8e1ed71462816a27f4dab766298f5e67/pkg/cmd/roachtest/tests/mixed_version_job_backward_compatibility_in_declarative_schema_changer.go#L29)):*
> ```Go
> 		db := c.Conn(ctx, t.L(), 1)
> 		setUpQuery := `
> SET use_declarative_schema_changer = off;
> ```

Don't think we need to force the legacy one here?
___
*[`pkg/cmd/roachtest/tests/mixed_version_job_backward_compatibility_in_declarative_schema_changer.go` line 116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86950#-NCL854B5zWWJDVfxkkr:-NCL854B5zWWJDVfxkks:b45p3f2) ([raw file](https://github.com/cockroachdb/cockroach/blob/986fb92d8e1ed71462816a27f4dab766298f5e67/pkg/cmd/roachtest/tests/mixed_version_job_backward_compatibility_in_declarative_schema_changer.go#L116)):*
> ```Go
> 
> 				// Run schema change stmts, chosen from those supported in `predV` version.
> 				planAndRunSchemaChange(c, upgradedNodes.RandNode(), `DROP SEQUENCE testdb.testsc.s`),
> ```

Longer term do we want these tests to be datadriven somehow? Think this is more of a future thing.

**Review by Xiang-Gu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86950)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/cmd/roachtest/tests/mixed_version_job_backward_compatibility_in_declarative_schema_changer.go` line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86950#-NCL9ben5QHGmnNjMxCL:-NCRBlsQ7d1ANftviSVY:b-a7cie6) ([raw file](https://github.com/cockroachdb/cockroach/blob/986fb92d8e1ed71462816a27f4dab766298f5e67/pkg/cmd/roachtest/tests/mixed_version_job_backward_compatibility_in_declarative_schema_changer.go#L29)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Don't think we need to force the legacy one here?
</blockquote></details>

We don't necessarily; I think I was just being paranoid when I wrote tests about declarative schema changer -- I want all the setup stmts to run in legacy schema changer and all to-be-tested stmst to run in declarative schema changer.

I don't really think this is reasonable or convincing at all -- I've removed it
___
*[`pkg/cmd/roachtest/tests/mixed_version_job_backward_compatibility_in_declarative_schema_changer.go` line 116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86950#-NCL854B5zWWJDVfxkkr:-NCRESFK8-tEtxS6VXUe:b-yoq298) ([raw file](https://github.com/cockroachdb/cockroach/blob/986fb92d8e1ed71462816a27f4dab766298f5e67/pkg/cmd/roachtest/tests/mixed_version_job_backward_compatibility_in_declarative_schema_changer.go#L116)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Longer term do we want these tests to be datadriven somehow? Think this is more of a future thing.
</blockquote></details>

yes, I thought about it and don't know the answer -- Indeed, such a roachtest will need to be modified for each (future) release because what's tested in all supported stmts in release v_N-1 (in this case, it's only all the `DROP`s).  I don't like that. What you suggested, a datadriven test, sounds like a way. Let's discuss this during our next 1:1 so I can gain more clarity about what to do.

For this release, let's keep it as is.

**Comment by Xiang-Gu** [comment]
TFTR!

bors r+

**Pull request merged**
