### PR TITLE
sql: implement the logic for ALTER TENANT SET CLUSTER SETTING

### PR DESCRIPTION
**Pull request by knz**
Informs #77471

Release justification: low risk, high benefit changes to existing functionality

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
Thanks for working on this!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77740#-:-My9H3lz80PU8LlUruwV:b-4v1jpi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @RaduBerinde)

___
*[pkg/sql/set_cluster_setting.go, line 379 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77740#-My9GJPD9YuE05YY-4QG:-My9GJPD9YuE05YY-4QH:b-66ket7) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fb7819c1420508a9c98e5b4a4a59e85c170b0fe/pkg/sql/set_cluster_setting.go#L379)):*
> ```Go
> 	}
> 
> 	if knobs := execCfg.TenantTestingKnobs; knobs != nil && knobs.ClusterSettingsUpdater != nil {
> ```

I don't think this block makes sense to run when we are setting a tenant override.
___
*[pkg/sql/set_cluster_setting.go, line 660 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77740#-My9FV5T1APHMi0A3IzN:-My9FV5T1APHMi0A3IzO:bp1n5lt) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fb7819c1420508a9c98e5b4a4a59e85c170b0fe/pkg/sql/set_cluster_setting.go#L660)):*
> ```Go
> // settingWriter is an interface that abstracts the setting change logic
> // over local and remote changes.
> type settingWriter interface {
> ```

I am skeptical about the value of having this interface. The two code paths are very different and pretty well separated in the code; we're only saving the duplication of a few lines as far as I can tell, while making following the overall logic much harder.

At the very least, `versionUpgradeHook` should not be part of this interface (the caller, `runMigrationsAndUpgradeVersion`, only runs for the existing case).
___
*[pkg/sql/tenant_settings.go, line 49 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77740#-My9F61JAvfJx8YN51aa:-My9F61JAvfJx8YN51ab:b-f9ugcj) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fb7819c1420508a9c98e5b4a4a59e85c170b0fe/pkg/sql/tenant_settings.go#L49)):*
> ```Go
> 	ctx context.Context, n *tree.AlterTenantSetClusterSetting,
> ) (planNode, error) {
> 	// Changing cluster settings for other tenants is a more
> ```

This statement should only be allowed if we are the system tenant.
___
*[pkg/sql/tenant_settings.go, line 74 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77740#-My9FCWg4BFvSALZEKpF:-My9FCWg4BFvSALZEKpG:b5uh3z6) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fb7819c1420508a9c98e5b4a4a59e85c170b0fe/pkg/sql/tenant_settings.go#L74)):*
> ```Go
> 
> 	st := p.EvalContext().Settings
> 	v, ok := settings.Lookup(name, settings.LookupForLocalAccess, p.ExecCfg().Codec.ForSystemTenant())
> ```

Here we only want to allow tenant-visible settings, so we should always pass `false` for the last argument, or check that it is not a system setting if we want a better error message (and please add a test for this case).
___
*[pkg/util/log/eventpb/misc_sql_events.proto, line 44 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77740#-My9GpzA1A_tlXM7etiw:-My9GpzA1A_tlXM7etix:b-5emg3l) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fb7819c1420508a9c98e5b4a4a59e85c170b0fe/pkg/util/log/eventpb/misc_sql_events.proto#L44)):*
> ```protobuf
> 
> // SetTenantClusterSetting is recorded when a cluster setting override
> // is changed for another tenant.
> ```

[nit] is changed (either for a particular tenant, or for all tenants).

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77740)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/set_cluster_setting.go, line 379 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77740#-My9GJPD9YuE05YY-4QG:-MyEmBZK5vFSF9EvGNRn:b-i0zk3t) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fb7819c1420508a9c98e5b4a4a59e85c170b0fe/pkg/sql/set_cluster_setting.go#L379)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I don't think this block makes sense to run when we are setting a tenant override.
</blockquote></details>

Good point. Updated.
___
*[pkg/sql/set_cluster_setting.go, line 660 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77740#-My9FV5T1APHMi0A3IzN:-MyEmJgPEY2Kq0sRcRVz:bc5srsc) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fb7819c1420508a9c98e5b4a4a59e85c170b0fe/pkg/sql/set_cluster_setting.go#L660)):*
> The two code paths are very different

In which way are they different?

> and pretty well separated in the code

Where's the separation?

> we're only saving the duplication of a few lines as far as I can tell

I tried otherwise and the change resulted in a large file with more than a hundred lines. I think the risk to get divergence in the common path if we duplicate the logic is high.

> while making following the overall logic much harder.

Maybe we can help that with documentation.

> At the very least, versionUpgradeHook should not be part of this interface (the caller, runMigrationsAndUpgradeVersion, only runs for the existing case).

What do you mean? versionUpgradeHook is called every time the version setting is updated. Secondary tenant have a version setting too! 

Even though, as explained in #77733, we're not implementing version setting changes in the current PR, the purpose of the interface I'm introducing here is to make that feature possible later, so that the separate implementation of the interface can provide the new way to run the SQL migrations when changing the version settings for another tenant.

In the next commit, this method interface is 
___
*[pkg/sql/tenant_settings.go, line 49 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77740#-My9F61JAvfJx8YN51aa:-MyEklSXBRqGbxVxLek4:b-1ggm3e) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fb7819c1420508a9c98e5b4a4a59e85c170b0fe/pkg/sql/tenant_settings.go#L49)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This statement should only be allowed if we are the system tenant.
</blockquote></details>

This is already checked below (and in unit tests).
```go
  if ¬p.execCfg.Codec.ForSystemTenant() {
    return ∅, pgerror.Newf(pgcode.InsufficientPrivilege,
      "ALTER TENANT can only be called by system operators")
  }
```

do you mean I should move this check up in the function?
___
*[pkg/sql/tenant_settings.go, line 74 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77740#-My9FCWg4BFvSALZEKpF:-MyEkx0F9hU5G8j2D2aO:b10yva4) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fb7819c1420508a9c98e5b4a4a59e85c170b0fe/pkg/sql/tenant_settings.go#L74)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Here we only want to allow tenant-visible settings, so we should always pass `false` for the last argument, or check that it is not a system setting if we want a better error message (and please add a test for this case).
</blockquote></details>

There's a test just below:
```go
  if setting.Class() ≡ settings.SystemOnly {
    return ∅, pgerror.Newf(pgcode.InsufficientPrivilege,
      "%s is a system-only setting and must be set in the admin tenant using SET CLUSTER SETTING", name)
  }
```
and it's also already exercised in tests.

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/set_cluster_setting.go, line 660 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77740#-My9FV5T1APHMi0A3IzN:-MyF-C-H3JrejpWK3F5Y:b-ohx998) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fb7819c1420508a9c98e5b4a4a59e85c170b0fe/pkg/sql/set_cluster_setting.go#L660)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

> The two code paths are very different

In which way are they different?

> and pretty well separated in the code

Where's the separation?

> we're only saving the duplication of a few lines as far as I can tell

I tried otherwise and the change resulted in a large file with more than a hundred lines. I think the risk to get divergence in the common path if we duplicate the logic is high.

> while making following the overall logic much harder.

Maybe we can help that with documentation.

> At the very least, versionUpgradeHook should not be part of this interface (the caller, runMigrationsAndUpgradeVersion, only runs for the existing case).

What do you mean? versionUpgradeHook is called every time the version setting is updated. Secondary tenant have a version setting too! 

Even though, as explained in #77733, we're not implementing version setting changes in the current PR, the purpose of the interface I'm introducing here is to make that feature possible later, so that the separate implementation of the interface can provide the new way to run the SQL migrations when changing the version settings for another tenant.

In the next commit, this method interface is 
</blockquote></details>

We are not implementing tenant settings here (they are already implemented). We are implementing tenant setting *overrides*. Version is not something that makes sense to override.

Maybe @ajwerner can chime in here too.

**Comment by knz** [comment]
> We are not implementing tenant settings here

Hm that's right.

What's the logic envisioned to change a tenant's own local customization "remotely"?

**Review by RaduBerinde — COMMENTED** [review]
> What's the logic envisioned to change a tenant's own local customization "remotely"?

I might be misunderstanding your question. Are you asking how the overrides work on the tenant side? It's implemented as described in the RFC (#73349): the tenant KV connector monitors the overrides (via an InternalServer streaming API) and the settings watcher on the tenant side integrates with the tenant connector (via the `setingswatcher.OverridesMonitor` interface).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77740#-:-MyFVNA_1wPNtIGLj5zI:bdfx4gk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @knz, and @RaduBerinde)

___
*[pkg/sql/set_cluster_setting.go, line 660 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77740#-My9FV5T1APHMi0A3IzN:-MyFWNH57NAM2U5fhtKO:b3ak6lu) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fb7819c1420508a9c98e5b4a4a59e85c170b0fe/pkg/sql/set_cluster_setting.go#L660)):*
> In which way are they different?

ALTER TENANT just has to write to the tenant_settings table. Not much else from the `SET CLUSTER SETTINGS` code applies: no special version handling, no waiting until the setting becomes "in effect". The only common thing is the encoding of the setting value into something that can be written to the table (which can be easily separated into a common routine).
 
> Where's the separation?

I just mean that the AlterTenant node is separate, it's not like there's some common entry point which has to at some point "branch out" into the two possibilities. 
___
*[pkg/sql/tenant_settings.go, line 49 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77740#-My9F61JAvfJx8YN51aa:-MyFV7KVBeZzqm1TIKiy:bk1zlp9) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fb7819c1420508a9c98e5b4a4a59e85c170b0fe/pkg/sql/tenant_settings.go#L49)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This is already checked below (and in unit tests).
```go
  if ¬p.execCfg.Codec.ForSystemTenant() {
    return ∅, pgerror.Newf(pgcode.InsufficientPrivilege,
      "ALTER TENANT can only be called by system operators")
  }
```

do you mean I should move this check up in the function?
</blockquote></details>

Ah, right, let's just move it up so it's next to this check, and it's as early as possible. And the rest of the code should not look at `ForSystemTenant()` again, as it can only be `true`.
___
*[pkg/sql/tenant_settings.go, line 74 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77740#-My9FCWg4BFvSALZEKpF:-MyFVHkHBSx48lS5HpFj:biatylq) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fb7819c1420508a9c98e5b4a4a59e85c170b0fe/pkg/sql/tenant_settings.go#L74)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

There's a test just below:
```go
  if setting.Class() ≡ settings.SystemOnly {
    return ∅, pgerror.Newf(pgcode.InsufficientPrivilege,
      "%s is a system-only setting and must be set in the admin tenant using SET CLUSTER SETTING", name)
  }
```
and it's also already exercised in tests.

</blockquote></details>

Ah, great, sorry for missing it.

**Review by knz — COMMENTED** [review]
Ok I am just discovering that we're missing out on an important use case, let's resume this conversation in #77935. 

I will simplify the current PR accordingly and we can do a separate PR when we tackle the new issue.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77740#-:-MyHjPu9DD2SEggI-MeG:b-oevlqq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @RaduBerinde)

___
*[pkg/sql/set_cluster_setting.go, line 660 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77740#-My9FV5T1APHMi0A3IzN:-MyHkoLF1iraL8i7IfMT:b-v90syh) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fb7819c1420508a9c98e5b4a4a59e85c170b0fe/pkg/sql/set_cluster_setting.go#L660)):*
> The only common thing is the encoding of the setting value into something that can be written to the table (which can be easily separated into a common routine).

But that's the change I have implemented here. The common code is now reusable in both places. What is missing?
___
*[pkg/sql/tenant_settings.go, line 49 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77740#-My9F61JAvfJx8YN51aa:-MyHkM-g7-9YthozcUAy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fb7819c1420508a9c98e5b4a4a59e85c170b0fe/pkg/sql/tenant_settings.go#L49)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Ah, right, let's just move it up so it's next to this check, and it's as early as possible. And the rest of the code should not look at `ForSystemTenant()` again, as it can only be `true`.
</blockquote></details>

Done.
___
*[pkg/sql/tenant_settings.go, line 74 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77740#-My9FCWg4BFvSALZEKpF:-MyHkXXaEHx8heI-7DF_:b-a2ykd0) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fb7819c1420508a9c98e5b4a4a59e85c170b0fe/pkg/sql/tenant_settings.go#L74)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Ah, great, sorry for missing it.
</blockquote></details>

Moved up higher.

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/set_cluster_setting.go, line 660 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77740#-My9FV5T1APHMi0A3IzN:-MyI6tNu-NbR87wlj_af:b-dc2pxk) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fb7819c1420508a9c98e5b4a4a59e85c170b0fe/pkg/sql/set_cluster_setting.go#L660)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

> The only common thing is the encoding of the setting value into something that can be written to the table (which can be easily separated into a common routine).

But that's the change I have implemented here. The common code is now reusable in both places. What is missing?


</blockquote></details>

Right, but the way you did it was to extract the non-common code behind an interface. The alternative I'm proposing is that the common code would be extracted into a few helper routines and the two codepaths would be otherwise unrelated. It's possible I'm missing some details that would make this harder than it seems, so it's up to you.

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/set_cluster_setting.go, line 660 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77740#-My9FV5T1APHMi0A3IzN:-MyI8n_G2s6gKxX17iz7:bwzm168) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fb7819c1420508a9c98e5b4a4a59e85c170b0fe/pkg/sql/set_cluster_setting.go#L660)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Right, but the way you did it was to extract the non-common code behind an interface. The alternative I'm proposing is that the common code would be extracted into a few helper routines and the two codepaths would be otherwise unrelated. It's possible I'm missing some details that would make this harder than it seems, so it's up to you.
</blockquote></details>

Looking at it another way - we're implementing a statement which upserts or deletes a row in a table, and that's all it does. Does that justify shuffling around (and complicating) hundreds of lines of existing code?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77740)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @RaduBerinde)

___
*[pkg/sql/set_cluster_setting.go, line 660 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77740#-My9FV5T1APHMi0A3IzN:-MyIKILp4gYgAxQaKzN3:b7y785u) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fb7819c1420508a9c98e5b4a4a59e85c170b0fe/pkg/sql/set_cluster_setting.go#L660)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Looking at it another way - we're implementing a statement which upserts or deletes a row in a table, and that's all it does. Does that justify shuffling around (and complicating) hundreds of lines of existing code?
</blockquote></details>

So to start with, the first commit in this PR is generally beneficial because it transforms nearly a thousand lines of code into many smaller functions, each with a clearer purpose.

With that infrastructure in place, the common path between SET CLUSTER SETTING and its ALTER TENANT variant is this:

- `writeSettingInternal()`
- `writeDefaultSettingValue()`
- half of `writeNonDefaultSettingValue()`
- `toSettingString()`

1) This is not a full hundred lines, but it's close to it. I do not feel comfortable copy-pasting that near hundred lines for the benefit of ALTER TENANT SET CLUSTER SETTING, because some of that logic could then diverge.

2) I stand by my point that we will likely want to solve #77935 / #77733 at some point. If/when that happens, then 100% of `writeNonDefaultSettingValue()` can be reused on both paths.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77740)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @RaduBerinde)

___
*[pkg/sql/set_cluster_setting.go, line 660 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77740#-My9FV5T1APHMi0A3IzN:-MyJEqel0ipZCdOg4Wvj:b-rv47fd) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fb7819c1420508a9c98e5b4a4a59e85c170b0fe/pkg/sql/set_cluster_setting.go#L660)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

So to start with, the first commit in this PR is generally beneficial because it transforms nearly a thousand lines of code into many smaller functions, each with a clearer purpose.

With that infrastructure in place, the common path between SET CLUSTER SETTING and its ALTER TENANT variant is this:

- `writeSettingInternal()`
- `writeDefaultSettingValue()`
- half of `writeNonDefaultSettingValue()`
- `toSettingString()`

1) This is not a full hundred lines, but it's close to it. I do not feel comfortable copy-pasting that near hundred lines for the benefit of ALTER TENANT SET CLUSTER SETTING, because some of that logic could then diverge.

2) I stand by my point that we will likely want to solve #77935 / #77733 at some point. If/when that happens, then 100% of `writeNonDefaultSettingValue()` can be reused on both paths.
</blockquote></details>

Separating into functions is good, but moving some functions behind an interface is a non-trivial complication (I don't mean a technical complication, it's pretty easy to achieve in the code; I mean a conceptual complication - it leads to pieces of the code that are "generic" w.r.t the interface, so to understand them you need to have a concept of what the interface is and does in the back of your head).

What your analysis above is missing is that in the ALTER TENANT case, most of those common routines reduce to little else on top of calling the interface. Here, I gave what I propose a shot: https://github.com/RaduBerinde/cockroach/commit/aa79281d49beec3a8b4b12a257a0a41a397fbd40

This is how little code we actually need, and it's mostly new code. The only thing I copy-pasted is the block of code below, which could be easily separated into a common routine:
```go
		reportedValue = tree.AsStringWithFlags(n.value, tree.FmtBareStrings)
		value, err := n.value.Eval(params.p.EvalContext())
		if err != nil {
			return err
		}
		encoded, err := toSettingString(params.ctx, n.st, n.name, n.setting, value)
```

**Review by knz — COMMENTED** [review]
RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77740#-:-MyiEmntC56vdPr05eAq:bb72pd0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/set_cluster_setting.go, line 660 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/77740#-My9FV5T1APHMi0A3IzN:-MyiEkld1LBuLzsByrdd:b-upz1ww) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fb7819c1420508a9c98e5b4a4a59e85c170b0fe/pkg/sql/set_cluster_setting.go#L660)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Separating into functions is good, but moving some functions behind an interface is a non-trivial complication (I don't mean a technical complication, it's pretty easy to achieve in the code; I mean a conceptual complication - it leads to pieces of the code that are "generic" w.r.t the interface, so to understand them you need to have a concept of what the interface is and does in the back of your head).

What your analysis above is missing is that in the ALTER TENANT case, most of those common routines reduce to little else on top of calling the interface. Here, I gave what I propose a shot: https://github.com/RaduBerinde/cockroach/commit/aa79281d49beec3a8b4b12a257a0a41a397fbd40

This is how little code we actually need, and it's mostly new code. The only thing I copy-pasted is the block of code below, which could be easily separated into a common routine:
```go
		reportedValue = tree.AsStringWithFlags(n.value, tree.FmtBareStrings)
		value, err := n.value.Eval(params.p.EvalContext())
		if err != nil {
			return err
		}
		encoded, err := toSettingString(params.ctx, n.st, n.name, n.setting, value)
```
</blockquote></details>

ok, that works.

**Review by RaduBerinde — APPROVED** [review]
:lgtm: Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77740#-:-MyoLirE4Y4crefcRIBU:b-g2a5fb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Comment by knz** [comment]
bors r=RaduBerinde

**Pull request merged**
