### PR TITLE
storage: avoid deadlock during merges

### LINKED ISSUE #27442: storage: merges can deadlock
Consider the following sequence of events:

1. LHS initiates merge with RHS.
2. RHS loses its lease.
3. RHS reacquires its lease, notices merge is in progress, and installs a mergeCompleteCh.
4. User sends a request to RHS. Let's call it a Get. The request blocks on mergeCompleteCh.
5. LHS sends GetSnapshotForMerge to RHS. GetSnapshotForMerge gets stuck in the command queue waiting for the Get to succeed.
6. Deadlock!

@bdarnell has suggested the following solution. Instead of blocking on the mergeCompleteCh in the replica, return a MergeInProgressError. Handle this error in the store by reaching into the replica for its mergeCompleteCh, and block there. Once the channel closes, retry the request. This neatly avoids deadlock by allowing blocked commands to exit the command queue without requiring the caller to retry them.

### PR DESCRIPTION
**Pull request by benesch**
Merges could deadlock if the lease on the right-hand range was
transferred or renewed during the merge transaction and the new
leaseholder received any request before the GetSnapshotForMerge request.
See #27442 and the comments within for details. Avoid the deadlock by
moving the responsibility for waiting for a merge to complete from the
replica to the store.

Add a unit test that runs several get requests concurrently with several
merges to reliably test for regressions. The problem previously only
presented when stressing TestStoreRangeMergeWithData.

Fix #27442.
Fix #27454.

Release note: None

### CODE REVIEW

**Review by bdarnell — APPROVED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27454)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/roachpb/errors.proto, line 397 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27454#-LHUKt8l5RNL8lMrQ_Pz:-LHUKt8l5RNL8lMrQ_Q-:bg6mqan) ([raw file](https://github.com/cockroachdb/cockroach/blob/10dfd6e9b97e4793f309b61a08995de92d6198d9/pkg/roachpb/errors.proto#L397)):*
> ```protobuf
> // A MergeInProgressError indicates that the request could not be completed
> // because the replica is being merged into its left-hand neighbor. The request
> // should be resubmitted after the merge completes.
> ```

Comment that this error is handled by the Store and should not escape to higher levels.

**Review by benesch — COMMENTED** [review]
Thanks for the review!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27454#-:-LHVPj9d1FTHeCcxI4mC:b-9qdoz3)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/roachpb/errors.proto, line 397 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27454#-LHUKt8l5RNL8lMrQ_Pz:-LHVPiJP5NkcnstRLm7e:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/10dfd6e9b97e4793f309b61a08995de92d6198d9/pkg/roachpb/errors.proto#L397)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Comment that this error is handled by the Store and should not escape to higher levels. 
</blockquote></details>

Done.

**Comment by benesch** [comment]
bors r=bdarnell

**Comment by benesch** [comment]
bors r=bdarnell

**Pull request merged**
