### PR TITLE
server: split the tenant server creation into 3 stages

### PR DESCRIPTION
**Pull request by knz**
Needed as prerequisite to #90176, towards fixing #89974.
First two commits from #90523.

The original motivation (and ultimate goal) for this PR is to
split the tenant server initialization into three phases: `New()`,
`PreStart()`, `AcceptClients()`, so as to reuse a common process startup
logic in a separate PR (https://github.com/cockroachdb/cockroach/pull/90176).

To achieve this goal, this PR re-orders the initialization steps
in `server.NewTenantServer` (previously known as
`server.StartTenant`), and extracts many of them into a new method
`(*SQLServerWrapper).PreStart()`.

The specific order of the code in `NewTenantServer()` and
`(*SQLServerWrapper).PreStart()` was chosen to mirror the order of
things in `NewServer()` and `(*Server).PreStart()`.

Reason for using the same order:

- it makes the review of this change easier: the reviewer can pull
  `server.go` and `tenant.go` and read them side-by-side, to satisfy
  themselves that the two implementations of
  `NewServer`/`NewTenantServer` and `PreStart` are equivalent.

- it will make it easier for future maintainers to keep them in sync.

- it helps us discover the fact that both sides share a lot of code.
  This opens an opportunity to merge them to a common implementation
  at a later stage.

While doing this work, care was also taken to discover which steps of
`(*Server).PreStart()` were *missing* from the tenant server
initialization. We found the following:

- the Sentry context enhancement (to report cluster ID, etc)
  was missing. This commit fixes that.

- several log entries that report the server configuration
  to the OPS channel were not emitted. This commit fixes that.

- the Graphite metric reporting was never enabled, even when
  configured. This commit fixes that.

- the Obs Service testing knobs (TestingKnobs.EventExporter) were
  not configured on the ObsServer instance. This commit fixes that.

- the `go.scheduler_latency` metric was not being measured.
  This commit fixes that.

Additionally, two followup issues were filed for the following
missing steps:

- missing support for the special file that blocks background jobs. (https://github.com/cockroachdb/cockroach/issues/90524)
- missing support for the system.eventlog cleanup loop. (https://github.com/cockroachdb/cockroach/issues/90521)

Epic: CRDB-14537

### CODE REVIEW

**Comment by knz** [comment]
@JeffSwenson @dhartunian I'd like to invite you both to review this, with different focus:

- @JeffSwenson to satisfy yourself that the changes here are feature-neutral, despite the relative large code movement. (Hint: look at the suggestion in the PR description to place the source files side-by-side to make review easier.)
- @dhartunian because we have discussed this area further, and I know you have an interest in keeping your understanding of this area up-to-date.

cc @andreimatei.

**Review by dhartunian — APPROVED** [review]
:lgtm: thanks for the review notes.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 6 of 13 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90384#-:-NFJiVVrEYAuaHsIPUSs:be3v0h3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @JeffSwenson, @knz, and @smg260)

___
*[`pkg/server/tenant.go` line 197 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/90384#-NFJidQqCSNTy5HhGBPp:-NFJidQqCSNTy5HhGBPq:biw9vvx) ([raw file](https://github.com/cockroachdb/cockroach/blob/fea8222608f02b28ef6332d02d9790ff55a7e314/pkg/server/tenant.go#L197)):*
> ```Go
> 			waitQuiesce(background)
> 			return nil, nil, nil, "", "", err
> 		}
> ```

was this block redundant with the code in `startListenRPCAndSQL`?



_Code quote:_
```Go
		waitQuiesce := func(ctx context.Context) {
			<-args.stopper.ShouldQuiesce()
			// NB: we can't do this as a Closer because (*Server).ServeWith is
			// running in a worker and usually sits on accept(pgL) which unblocks
			// only when pgL closes. In other words, pgL needs to close when
			// quiescing starts to allow that worker to shut down.
			_ = pgL.Close()
		}
		if err := args.stopper.RunAsyncTask(background, "wait-quiesce-pgl", waitQuiesce); err != nil {
			waitQuiesce(background)
			return nil, nil, nil, "", "", err
		}
```

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90384)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian, @herkolategan, @JeffSwenson, and @smg260)

___
*[`pkg/server/tenant.go` line 197 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/90384#-NFJidQqCSNTy5HhGBPp:-NFJw-oy-qfEkid1ozkP:bdv1kfg) ([raw file](https://github.com/cockroachdb/cockroach/blob/fea8222608f02b28ef6332d02d9790ff55a7e314/pkg/server/tenant.go#L197)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

was this block redundant with the code in `startListenRPCAndSQL`?
</blockquote></details>

Yep it was!

**Comment by knz** [comment]
TFYR

bors r=dhartunian

**Pull request merged**
