### PR TITLE
sql: use vectorize=on when not explicitly set

### LINKED ISSUE #62394: colexec: audit miscellaneous places where SessionData.VectorizeMode is unset
We will begin the process of deprecating the row-by-row execution engine in 21.2 release; however, there are still some cases where we use the old engine. Some of them are tracked in #57268, but what's missing from there is that depending on `SessionData.VectorizeMode` we might not even try to vectorize the flow. This can happen when that field is unset since the default value `0` maps to `VectorizeOff`. We should audit such places and use `VectorizeOn` as much as possible. One way we could go about doing that is we could introduce another value in the enum for `VectorizeOff` and treat `0` value as "unset" which is the same as `VectorizeOn`.

### PR DESCRIPTION
**Pull request by yuzefovich**
**sql: set NeededColumns on TableReaderSpec in some tests**

This field is used by the vectorized cFetcher in order to know which
columns should be actually decoded. The follow-up commit will switch
some of the tests to go through the vectorized engine, and this commit
is a prerequisite for that.

Release note: None

**colexec: do not create a span in the materializer**

This commit removes the creation of a tracing span (when tracing is
enabled) in the materializer. This is a minor performance optimization,
but the change was actually prompted by breaking a unit test of the
migration manager by the follow-up commit if the materializer creates
a tracing span.

I left a somewhat detailed comment of what's wrong with the test, but
not making a tracing span is reasonable on its own, so I think this
change is worth it.

Release note: None

**sql: use vectorize=on when not explicitly set**

Previously, if `Vectorize` value of the session data wasn't explicitly
set, it would remain as 0 which was the equivalent of `VectorizeOff`.
This commit renames the zero value to `VectorizeUnset` that is mapped to
"on", `VectorizeOff` now needs to be set explicitly. Completely removing
zero value is not allowed by the proto3.

Fixes: #62394.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62635#-:-MaoTtSt365LHQ4hlmyW:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
I had to add another commit (now second) to fix an accidental breakage of the test in the last commit (it is actually the test to blame). PTAL at the second commit.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 7 of 7 files at r2, 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62635#-:-MbC5ocC6Rmc-0s_dJHv:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by yuzefovich** [comment]
Oh, need to rebase.

bors r-

**Pull request merged**
