### PR TITLE
Rename GetUVarint to GetUvarint.

### PR DESCRIPTION
**Pull request by petermattis**
Match the capitalization of PutUvarint.

### CODE REVIEW

**Comment by bdarnell** [comment]
FWIW I'd prefer to capitalize the V in both cases unless we're following some other pattern, but either way LGTM.

**Comment by petermattis** [comment]
I don't particular care about the case, just consistency. @spencerkimball?

**Comment by spencerkimball** [comment]
I'd prefer UVarint

**Comment by petermattis** [comment]
The Go standard library prefers Uvarint: `binary.PutUvarint`

**Comment by spencerkimball** [comment]
Fine then go with that.

LGTM

**Pull request merged**
