### PR TITLE
opt: allow join-elimination rules to apply in more cases

### LINKED ISSUE #102614: opt: `TryRemapJoinOuterColsRight` prevents optimal plan
The `TryRemapJoinOuterColsRight` rule, which is newly introduced in v23.1, is preventing an optimal query plan from being produced. 

Here's an example test case showing a suboptimal query plan first, and an optimal query plan when `TryRemapJoinOuterColsRight` is disabled:

```
exec-ddl
CREATE TABLE parent (
  id INT PRIMARY KEY
)
----

exec-ddl
CREATE TABLE child (
  id INT PRIMARY KEY,
  parent_id INT NOT NULL REFERENCES parent(id)
)
----

opt
SELECT
  id,
  (SELECT child.parent_id FROM parent WHERE id = child.parent_id)
FROM child
----
project
 ├── columns: id:1!null parent_id:9!null
 ├── key: (1)
 ├── fd: (1)-->(9)
 ├── inner-join (hash)
 │    ├── columns: child.id:1!null child.parent_id:2!null parent.id:5!null parent_id:8!null
 │    ├── multiplicity: left-rows(exactly-one), right-rows(zero-or-more)
 │    ├── key: (1)
 │    ├── fd: (1)-->(2), (5)==(2,8), (8)==(2,5), (2)==(5,8)
 │    ├── scan child
 │    │    ├── columns: child.id:1!null child.parent_id:2!null
 │    │    ├── key: (1)
 │    │    └── fd: (1)-->(2)
 │    ├── project
 │    │    ├── columns: parent_id:8!null parent.id:5!null
 │    │    ├── key: (5)
 │    │    ├── fd: (5)==(8), (8)==(5)
 │    │    ├── scan parent
 │    │    │    ├── columns: parent.id:5!null
 │    │    │    └── key: (5)
 │    │    └── projections
 │    │         └── parent.id:5 [as=parent_id:8, outer=(5)]
 │    └── filters
 │         └── parent.id:5 = child.parent_id:2 [outer=(2,5), constraints=(/2: (/NULL - ]; /5: (/NULL - ]), fd=(2)==(5), (5)==(2)]
 └── projections
      └── parent_id:8 [as=parent_id:9, outer=(8)]

opt disable=(TryRemapJoinOuterColsRight)
SELECT
  id,
  (SELECT child.parent_id FROM parent WHERE id = child.parent_id)
FROM child
----
project
 ├── columns: id:1!null parent_id:9!null
 ├── key: (1)
 ├── fd: (1)-->(9)
 ├── scan child
 │    ├── columns: child.id:1!null child.parent_id:2!null
 │    ├── key: (1)
 │    └── fd: (1)-->(2)
 └── projections
      └── child.parent_id:2 [as=parent_id:9, outer=(2)]
```

cc @DrewKimball 

Jira issue: CRDB-27561

### PR DESCRIPTION
**Pull request by DrewKimball**
#### opt: allow join elimination rules to remap columns

When it can be proven that a join does not add rows to or remove them
from one of its inputs, the other input can often be removed, eliminating
the join. However, this can only be done if the columns from the
eliminated side are not needed.

This patch allows the join elimination rules to remap columns from the
eliminated side to the preserved side of the join, using the join's
functional dependencies. For example:
```
CREATE TABLE xy (x INT PRIMARY KEY, y INT);
CREATE TABLE fk (k INT PRIMARY KEY, v INT NOT NULL, FOREIGN KEY (v) REFERENCES xy (x));

SELECT x, k, v FROM fk INNER JOIN xy ON v = x;
```
In the example above, the join could not previously be eliminated because
the `x` column is required in the output. Now, the `x` column is remapped
to the equivalent `v` column, allowing the join to be removed.

Fixes #102614

Release note (performance improvement): The optimizer can now eliminate
joins in more cases.

#### opt: infer equality filters for self joins

When a table is joined to itself with an equality that forms a key
over both join inputs, it is possible to infer equality filters
between each pair of columns at the same ordinal position in the base
table. This patch improves the logical props builder to infer these
self-join equalities in a join's FuncDepSet. This improves the quality
of information available to optimization rules, and in particular, join
elimination rules.

Informs #102614

Release note: None

### CODE REVIEW

**Review by msirek — APPROVED** [review]
Very nice performance improvements!
:lgtm_strong: 

> Reviewed 17 of 17 files at r1, 15 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105214#-:-NYUVM3y6EhwWmhBtX_I:bxgdvky)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Review by mgartner — COMMENTED** [review]
Very nice! Just left some minor comments/questions.

> Reviewed 17 of 17 files at r1, 15 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105214#-:-NYZ7XVyBaNE6ycpP5dO:b-d94yfp)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/opt/norm/project_funcs.go` line 862 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105214#-NYYUYrbCv0Ok0FvSRbW:-NYYUYrbCv0Ok0FvSRbX:b-ch1npo) ([raw file](https://github.com/cockroachdb/cockroach/blob/040b95a4ca7335fd3a1635a4fad3b2c1975f85d3/pkg/sql/opt/norm/project_funcs.go#L862)):*
> ```Go
> 	for col, ok := from.Next(0); ok; col, ok = from.Next(col + 1) {
> 		if !to.Contains(col) {
> 			candidates := fds.ComputeEquivGroup(col)
> ```

nit: add  `TODO(mgartner): We don't need to compute the entire equivalence group, we only need to find the first equivalent column that's in the to set`.
___
*[`pkg/sql/opt/norm/project_funcs.go` line 883 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105214#-NYYV7AY5d9IxlQHutvy:-NYYV7AY5d9IxlQHutvz:b-ch1npo) ([raw file](https://github.com/cockroachdb/cockroach/blob/040b95a4ca7335fd3a1635a4fad3b2c1975f85d3/pkg/sql/opt/norm/project_funcs.go#L883)):*
> ```Go
> ) memo.ProjectionsExpr {
> 	getReplacement := func(col opt.ColumnID) opt.ColumnID {
> 		candidates := fds.ComputeEquivGroup(col)
> ```

nit: add  `TODO(mgartner): We don't need to compute the entire equivalence group, we only need to find the first equivalent column that's in the to set`.
___
*[`pkg/sql/opt/norm/rules/project.opt` line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105214#-NYYcS-e3t47R8gyc_Tz:-NYYcS-e3t47R8gyc_U-:b-l59o0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/040b95a4ca7335fd3a1635a4fad3b2c1975f85d3/pkg/sql/opt/norm/rules/project.opt#L36)):*
> ```
> (Project
>     $left
>     (MergeProjections
> ```

Are you convinced we don't need to call `CanMergeProjections` before `MergeProjections`? I think it's fine because the `outer` projections, `(RemapProjectionCols $projections $leftCols $fds)`, will only contain references to columns in `$leftCols`, and the `inner` projections, `(ProjectRemappedCols $passthrough $leftCols $fds)`, will only produce columns in `$passthrough`.
___
*[`pkg/sql/opt/testutils/opttester/forcing_opt.go` line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105214#-NYZ3Tyq5H_r731afIYY:-NYZ3Tyq5H_r731afIYZ:b6zrrk4) ([raw file](https://github.com/cockroachdb/cockroach/blob/040b95a4ca7335fd3a1635a4fad3b2c1975f85d3/pkg/sql/opt/testutils/opttester/forcing_opt.go#L78)):*
> ```Go
> 		if tester.Flags.DisableRules.Contains(int(ruleName)) {
> 			return false
> 		}
> ```

Good catch!
___
*[`pkg/sql/opt/exec/execbuilder/testdata/subquery` line 182 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105214#-NYYSjzL6zmTg-q6RKzq:-NYYSjzL6zmTg-q6RKzr:b9qiexq) ([raw file](https://github.com/cockroachdb/cockroach/blob/040b95a4ca7335fd3a1635a4fad3b2c1975f85d3/pkg/sql/opt/exec/execbuilder/testdata/subquery#L182)):*
> ```
> # IN expression transformed into semi-join.
> query T
> EXPLAIN (VERBOSE) SELECT a FROM abc WHERE a IN (SELECT a FROM abc WHERE b < 0)
> ```

The comment doesn't make sense anymore. Maybe change the `a`s to `b`s here and the semi-join won't be eliminated.
___
*[`pkg/sql/opt/memo/testdata/logprops/join` line 3012 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105214#-NYZ4htwCjwLciyE30M-:-NYZ4htx5iFpsRsP9xKn:b-ntg8sp) ([raw file](https://github.com/cockroachdb/cockroach/blob/546bce0a5abab14d5ec9a11509bd0b1767c937da/pkg/sql/opt/memo/testdata/logprops/join#L3012)):*
> ```
>  ├── multiplicity: left-rows(zero-or-one), right-rows(zero-or-one)
>  ├── key: (6)
>  ├── fd: ()-->(2,7), (1)-->(3), (6)-->(8), (1)==(6), (6)==(1), (2)==(7), (7)==(2), (3)==(8), (8)==(3)
> ```

Walk me through this test case. We can infer equality of 2==7 and 3==8 because 2 and 7 are held constant? Any rows passing the `xyz.x = foo.x` filter and one of the constant equality filters would make 3 funcationally equivalent to 8, even though this is contradiction that no rows can satisfy?
___
*[`pkg/sql/opt/norm/testdata/rules/join` line 1842 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105214#-NYZ5dct6EbHjWKOJFAy:-NYZ5dcu6I-RhvdCH4Ox:byt83jn) ([raw file](https://github.com/cockroachdb/cockroach/blob/546bce0a5abab14d5ec9a11509bd0b1767c937da/pkg/sql/opt/norm/testdata/rules/join#L1842)):*
> ```
> 
> # --------------------------------------------------
> # SimplifyLeftJoin + SimplifyRightJoin
> ```

Do we want to prevent these tests from changing since their suppose to show the left-join => inner-join transformation? I suppose we need to self-join in order to make that transformation, and that also enables the join to be eliminated entirely, so maybe it's fine to leave as-is?

**Review by DrewKimball — COMMENTED** [review]
Thanks for taking a look!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105214#-:-NYbASYg25D_63fOdLFr:bubxju8)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/opt/norm/project_funcs.go` line 862 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105214#-NYYUYrbCv0Ok0FvSRbW:-NYb2ELX6wbkcjZgYu29:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/040b95a4ca7335fd3a1635a4fad3b2c1975f85d3/pkg/sql/opt/norm/project_funcs.go#L862)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: add  `TODO(mgartner): We don't need to compute the entire equivalence group, we only need to find the first equivalent column that's in the to set`.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/norm/project_funcs.go` line 883 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105214#-NYYV7AY5d9IxlQHutvy:-NYb2DYb7M8THb4QyT7H:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/040b95a4ca7335fd3a1635a4fad3b2c1975f85d3/pkg/sql/opt/norm/project_funcs.go#L883)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: add  `TODO(mgartner): We don't need to compute the entire equivalence group, we only need to find the first equivalent column that's in the to set`.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/norm/rules/project.opt` line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105214#-NYYcS-e3t47R8gyc_Tz:-NYb3vh66FJA2hHpHzRM:bgbzub9) ([raw file](https://github.com/cockroachdb/cockroach/blob/040b95a4ca7335fd3a1635a4fad3b2c1975f85d3/pkg/sql/opt/norm/rules/project.opt#L36)):*
>Are you convinced we don't need to call `CanMergeProjections` before `MergeProjections`? I think it's fine because the `outer` projections, `(RemapProjectionCols $projections $leftCols $fds)`, will only contain references to columns in `$leftCols`, and the `inner` projections, `(ProjectRemappedCols $passthrough $leftCols $fds)`, will only produce columns in `$passthrough`.

Yes, `RemapProjectionCols` projections only reference left columns, while `ProjectRemappedCols` only _projects_ right columns. Added a comment.
___
*[`pkg/sql/opt/testutils/opttester/forcing_opt.go` line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105214#-NYZ3Tyq5H_r731afIYY:-NYb4ZQx-1LDkkliGGRA:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/040b95a4ca7335fd3a1635a4fad3b2c1975f85d3/pkg/sql/opt/testutils/opttester/forcing_opt.go#L78)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Good catch!
</blockquote></details>

Thanks!
___
*[`pkg/sql/opt/exec/execbuilder/testdata/subquery` line 182 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105214#-NYYSjzL6zmTg-q6RKzq:-NYb4rcA-Em5RjAB1PQI:b6gl3km) ([raw file](https://github.com/cockroachdb/cockroach/blob/040b95a4ca7335fd3a1635a4fad3b2c1975f85d3/pkg/sql/opt/exec/execbuilder/testdata/subquery#L182)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

The comment doesn't make sense anymore. Maybe change the `a`s to `b`s here and the semi-join won't be eliminated.
</blockquote></details>

It didn't want to use the semi-join when I used `b` instead, but I got around it by just adding a duplicate table `abc2`.
___
*[`pkg/sql/opt/memo/testdata/logprops/join` line 3012 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105214#-NYZ4htwCjwLciyE30M-:-NYb7npI-wx4Q94r657s:b-tnkiv0) ([raw file](https://github.com/cockroachdb/cockroach/blob/546bce0a5abab14d5ec9a11509bd0b1767c937da/pkg/sql/opt/memo/testdata/logprops/join#L3012)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Walk me through this test case. We can infer equality of 2==7 and 3==8 because 2 and 7 are held constant? Any rows passing the `xyz.x = foo.x` filter and one of the constant equality filters would make 3 funcationally equivalent to 8, even though this is contradiction that no rows can satisfy?
</blockquote></details>

`x` implies `y` (and the same `x` implies the same `y` for both tables because it's a self-join), so if the `x` values between `xyz` and `foo` are the same, the `y` values must also be the same in order for there to be any matches. It's a contradiction in this case, but the optimizer doesn't see it because the filters get pushed down before the join's properties are calculated.
___
*[`pkg/sql/opt/norm/testdata/rules/join` line 1842 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105214#-NYZ5dct6EbHjWKOJFAy:-NYb55Zi6agJqb1MBSUd:b5j33m8) ([raw file](https://github.com/cockroachdb/cockroach/blob/546bce0a5abab14d5ec9a11509bd0b1767c937da/pkg/sql/opt/norm/testdata/rules/join#L1842)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Do we want to prevent these tests from changing since their suppose to show the left-join => inner-join transformation? I suppose we need to self-join in order to make that transformation, and that also enables the join to be eliminated entirely, so maybe it's fine to leave as-is?
</blockquote></details>

I think it's ok since the expected rules are still firing, but I'm happy to prevent the elimination if you think that'd be better.

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 20 of 22 files at r3, 15 of 15 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105214#-:-NYd0Bjd0x3fPe8yo6D-:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[`pkg/sql/opt/exec/execbuilder/testdata/subquery` line 182 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105214#-NYYSjzL6zmTg-q6RKzq:-NYd-Bm35bdCF9BJ6lyd:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/040b95a4ca7335fd3a1635a4fad3b2c1975f85d3/pkg/sql/opt/exec/execbuilder/testdata/subquery#L182)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

It didn't want to use the semi-join when I used `b` instead, but I got around it by just adding a duplicate table `abc2`.
</blockquote></details>

:+1: 
___
*[`pkg/sql/opt/memo/testdata/logprops/join` line 3012 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105214#-NYZ4htwCjwLciyE30M-:-NYd-p1i3KJv_o_PRZVf:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/546bce0a5abab14d5ec9a11509bd0b1767c937da/pkg/sql/opt/memo/testdata/logprops/join#L3012)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

`x` implies `y` (and the same `x` implies the same `y` for both tables because it's a self-join), so if the `x` values between `xyz` and `foo` are the same, the `y` values must also be the same in order for there to be any matches. It's a contradiction in this case, but the optimizer doesn't see it because the filters get pushed down before the join's properties are calculated.
</blockquote></details>

:+1: 
___
*[`pkg/sql/opt/norm/testdata/rules/join` line 1842 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/105214#-NYZ5dct6EbHjWKOJFAy:-NYd-yTw2j662OXvDEpu:b-jftn9g) ([raw file](https://github.com/cockroachdb/cockroach/blob/546bce0a5abab14d5ec9a11509bd0b1767c937da/pkg/sql/opt/norm/testdata/rules/join#L1842)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

I think it's ok since the expected rules are still firing, but I'm happy to prevent the elimination if you think that'd be better.
</blockquote></details>

No, I think this is fine as-is.

**Comment by DrewKimball** [comment]
Fixed a few test failures, I think everything should be passing now.

**Comment by DrewKimball** [comment]
TFTRs!

bors r+

**Comment by DrewKimball** [comment]
Looks like `TestExecBuild_upsert` is flaking, will investigate.

**Comment by mgartner** [comment]
🚨 If we backport this, we'll need to also backport #105723, #107319, and #107995. 🚨

**Pull request merged**
