### PR TITLE
ui: enable live reload

### PR DESCRIPTION
**Pull request by maxlang**
---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8679)

### CODE REVIEW

**Comment by maxlang** [comment]
Ok merged correctly for now. Got live-reload working!

aug-19-2016 16-55-39

**Comment by tamird** [comment]
:lgtm: modulo unrelated changes in helpus. They need their own commit, at least.

---

Reviewed 40 of 40 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[ui/app/containers/helpus.tsx, line 76 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8679#-KPmx6kpT12gGqCn__im:-KPmx6kpT12gGqCn__in:bglrpzo) ([raw file](https://github.com/cockroachdb/cockroach/blob/8930f39d70abf2f891150935509cc0615ced2cf6/ui/app/containers/helpus.tsx#L76)):*
> ```XML
>           <div>
>             <input type="checkbox" name="optin" id="optin" checked={attributes.optin} onChange={this.makeOnChange((o, v) => o.optin = v)} />
>             <label htmlFor="optin">Share data with Cockroach Labs</label>
> ```

what's this `for->htmlFor` about? ditto below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8679#-:-KPmx_JjClipMlR-ZBFA:b-d5c1jl)*

**Comment by mrtracy** [comment]
LGTM

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8679#-:-KPnIvrZiPirgPMBMDbR:bb6ywmx)*

**Comment by maxlang** [comment]
Moved unrelated `helpus.tsx` changes to another commit.

I found these issues when I went to each page checking for errors.

---

Review status: 0 of 47 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[ui/app/containers/helpus.tsx, line 76 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8679#-KPmx6kpT12gGqCn__im:-KPnMdabXjfP6tOFlgDS:b-vmj1xq) ([raw file](https://github.com/cockroachdb/cockroach/blob/8930f39d70abf2f891150935509cc0615ced2cf6/ui/app/containers/helpus.tsx#L76)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> what's this `for->htmlFor` about? ditto below.
</details>
React needs `class` to be `className` and `for` to be `htmlFor`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8679#-:-KPnMnlTdcyiacaws8J4:b7mw67q)*

**Comment by tamird** [comment]
Looks like config.js got jacked up again.

---

Review status: 0 of 47 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8679#-:-KPnQV-jmO34xq2J_QXK:bgmoiw8)*

**Comment by maxlang** [comment]
Cleared caches and re-ran make. Hopefully still good.

---

Review status: 0 of 47 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8679#-:-KPnRstNYGiduCeEHX1C:batobcb)*

**Comment by tamird** [comment]
Reviewed 39 of 40 files at r4, 8 of 8 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8679)*

**Pull request merged**
