### PR TITLE
sql: add support for show create database

### PR DESCRIPTION
**Pull request by pawalt**
Previously, this was not supported as databases did not have
attributes.
With the addition of region attributes, this patch adds SHOW CREATE
DATABASE to get database details.

Release note (sql change): The SHOW CREATE DATABASE command was added to
get database metadata.

### CODE REVIEW

**Review by arulajmani — CHANGES_REQUESTED** [review]
Nice quick start! :raised_hands:  

Mostly nits and minor suggestions. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66033#-:-MbHchH5CJiXymvmNftk:b5fi9lw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pawalt)

___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region_show, line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66033#-MbH_KOq7c2lPPLkj_CV:-MbH_KOq7c2lPPLkj_CW:bpkj9ns) ([raw file](https://github.com/cockroachdb/cockroach/blob/791a26f3503e5e33e1d7e9a3ff0f456ffbeb7958/pkg/ccl/logictestccl/testdata/logic_test/multi_region_show#L4)):*
> ```
> 
> query TTTT colnames
> SHOW REGIONS
> ```

Any reason to include these SHOW REGIONS/SHOW REGIONS FROM CLUSTER in this file?
___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region_show, line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66033#-MbHQ1tD7vITDay0L17h:-MbHQ1tD7vITDay0L17i:blqh5je) ([raw file](https://github.com/cockroachdb/cockroach/blob/791a26f3503e5e33e1d7e9a3ff0f456ffbeb7958/pkg/ccl/logictestccl/testdata/logic_test/multi_region_show#L19)):*
> ```
> us-east-1       {us-az1,us-az2,us-az3}
> 
> statement ok
> ```

nit: Instead of creating a bunch of databases and then doing a bunch of `SHOW CREATE` queries, could we instead test these in lockstep? I think it'll make it a bit easier to follow what is being tested. 
___
*[pkg/sql/delegate/show_table.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66033#-MbHRAak46Lam6xe-8wi:-MbHRAak46Lam6xe-8wj:b-jnn0tk) ([raw file](https://github.com/cockroachdb/cockroach/blob/791a26f3503e5e33e1d7e9a3ff0f456ffbeb7958/pkg/sql/delegate/show_table.go#L26)):*
> ```Go
> 
> 	switch n.Mode {
> 	case tree.ShowCreateModeTable:
> ```

nit: you can put the cases for Table/Sequence/View in a single case statement here. 
___
*[pkg/sql/delegate/show_table.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66033#-MbHRSjNBccCAmeKxPON:-MbHRSjNBccCAmeKxPOO:b-5bo0o1) ([raw file](https://github.com/cockroachdb/cockroach/blob/791a26f3503e5e33e1d7e9a3ff0f456ffbeb7958/pkg/sql/delegate/show_table.go#L36)):*
> ```Go
> 	}
> 
> 	// should never reach this case, but need it for compiler
> ```

Could we add a default case above which returns an assertion failed error instead? That should satisfy the compiler and is much more explicit about the expectation here. 
___
*[pkg/sql/delegate/show_table.go, line 50 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66033#-MbHTFUt8cyHU9le1nvE:-MbHTFUt8cyHU9le1nvF:bbq17uq) ([raw file](https://github.com/cockroachdb/cockroach/blob/791a26f3503e5e33e1d7e9a3ff0f456ffbeb7958/pkg/sql/delegate/show_table.go#L50)):*
> ```Go
> `
> 
> 	// checking if the database exists before running the sql
> ```

nit: comments should start with capital letters and end with a fullstop. 
___
*[pkg/sql/delegate/show_table.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66033#-MbHXcP6Al6rYv9BtV2V:-MbHXcP72-SaGV4tQ97z:b-lbli7b) ([raw file](https://github.com/cockroachdb/cockroach/blob/791a26f3503e5e33e1d7e9a3ff0f456ffbeb7958/pkg/sql/delegate/show_table.go#L57)):*
> ```Go
> 
> 	return parse(fmt.Sprintf(showCreateQuery, n.Name))
> }
> ```

I think you might need some escaping logic here -- a database called `"bob""''b"` wouldn't work here. We have this `lex.EscapeSQLString` that might be useful. Also might be worth adding a test for one of these. 
___
*[pkg/sql/parser/sql.y, line 5372 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66033#-MbHSOud8MXaV9kL34Lw:-MbHSOud8MXaV9kL34Lx:bkn97th) ([raw file](https://github.com/cockroachdb/cockroach/blob/791a26f3503e5e33e1d7e9a3ff0f456ffbeb7958/pkg/sql/parser/sql.y#L5372)):*
> ```Yacc
>     $$.val = &tree.ShowCreate{Mode: tree.ShowCreateModeSequence, Name: $4.unresolvedObjectName()}
> 	}
> | SHOW CREATE DATABASE table_name
> ```

nit: s/table_name/database_name/g?

**Review by arulajmani — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66033)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pawalt)

___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region_show, line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66033#-MbHQ1tD7vITDay0L17h:-MbHQ1tD7vITDay0L17i:bfvxbws) ([raw file](https://github.com/cockroachdb/cockroach/blob/791a26f3503e5e33e1d7e9a3ff0f456ffbeb7958/pkg/ccl/logictestccl/testdata/logic_test/multi_region_show#L19)):*
> ```
> us-east-1       {us-az1,us-az2,us-az3}
> 
> statement ok
> ```

nit: Instead of creating a bunch of databases and then doing a bunch of `SHOW CREATE` queries, could we instead test these in lockstep? I think it'll make it a bit easier to follow

**Review by pawalt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66033)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[pkg/ccl/logictestccl/testdata/logic_test/multi_region_show, line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66033#-MbH_KOq7c2lPPLkj_CV:-MbarTC458icSO0arPEH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/791a26f3503e5e33e1d7e9a3ff0f456ffbeb7958/pkg/ccl/logictestccl/testdata/logic_test/multi_region_show#L4)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Any reason to include these SHOW REGIONS/SHOW REGIONS FROM CLUSTER in this file?
</blockquote></details>

Done.
___
*[pkg/sql/delegate/show_table.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66033#-MbHRSjNBccCAmeKxPON:-MbarVEj6PUKQsVDkSqw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/791a26f3503e5e33e1d7e9a3ff0f456ffbeb7958/pkg/sql/delegate/show_table.go#L36)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Could we add a default case above which returns an assertion failed error instead? That should satisfy the compiler and is much more explicit about the expectation here. 
</blockquote></details>

Done.
___
*[pkg/sql/delegate/show_table.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66033#-MbHXcP6Al6rYv9BtV2V:-MbarXei2CMdxpZGoa_N:bctpdcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/791a26f3503e5e33e1d7e9a3ff0f456ffbeb7958/pkg/sql/delegate/show_table.go#L57)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I think you might need some escaping logic here -- a database called `"bob""''b"` wouldn't work here. We have this `lex.EscapeSQLString` that might be useful. Also might be worth adding a test for one of these. 
</blockquote></details>

Makes sense. Done.

**Review by arulajmani — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66033)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @pawalt)

___
*[pkg/sql/delegate/show_table.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66033#-MbHXcP6Al6rYv9BtV2V:-MbbEHLI8DkxJLgBKpwf:bkb2x8) ([raw file](https://github.com/cockroachdb/cockroach/blob/791a26f3503e5e33e1d7e9a3ff0f456ffbeb7958/pkg/sql/delegate/show_table.go#L57)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

Makes sense. Done.
</blockquote></details>

Did that work? Could we add a test for this as well?

**Review by pawalt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66033)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[pkg/sql/delegate/show_table.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66033#-MbHXcP6Al6rYv9BtV2V:-Mbbzp9SDDNHOlunb8c2:b-nitvfm) ([raw file](https://github.com/cockroachdb/cockroach/blob/791a26f3503e5e33e1d7e9a3ff0f456ffbeb7958/pkg/sql/delegate/show_table.go#L57)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Did that work? Could we add a test for this as well?
</blockquote></details>

That worked; I also had to change a bit about how I was constructing the CREATE DATABASE statement since I hadn't thought about escaping. I added a logic test for it as well. Do we need to worry about escaping with region names as well? I'm not sure what kind of strings those are classified as since they don't seem to be the same as Identifiers or SQL strings.

**Review by arulajmani — CHANGES_REQUESTED** [review]
One minor change request, but otherwise I think this is pretty close! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66033#-:-Mbg38ni7jA-7nDAfDf5:b3atrvy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @pawalt)

___
*[pkg/sql/delegate/show_table.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66033#-MbHXcP6Al6rYv9BtV2V:-Mbg2hAG1Nq5bjRKn6OE:bhsdvdl) ([raw file](https://github.com/cockroachdb/cockroach/blob/791a26f3503e5e33e1d7e9a3ff0f456ffbeb7958/pkg/sql/delegate/show_table.go#L57)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

That worked; I also had to change a bit about how I was constructing the CREATE DATABASE statement since I hadn't thought about escaping. I added a logic test for it as well. Do we need to worry about escaping with region names as well? I'm not sure what kind of strings those are classified as since they don't seem to be the same as Identifiers or SQL strings.
</blockquote></details>

Hmm so this conversation prompted me to look at how we format a `tree.CreateDatabase` node. Looks like it already does all the escaping for us. Would it make sense to just construct one of these above and call Format on it?

**Review by pawalt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66033)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[pkg/sql/delegate/show_table.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66033#-MbHXcP6Al6rYv9BtV2V:-MbgNjX-0CFK4A4yMhQ2:b8p0twl) ([raw file](https://github.com/cockroachdb/cockroach/blob/791a26f3503e5e33e1d7e9a3ff0f456ffbeb7958/pkg/sql/delegate/show_table.go#L57)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Hmm so this conversation prompted me to look at how we format a `tree.CreateDatabase` node. Looks like it already does all the escaping for us. Would it make sense to just construct one of these above and call Format on it? 
</blockquote></details>

I don't think so because the escaping in `tree.CreateDatabase` comes from the escaping on `tree.Name`, which I'm using when building the create statement:
https://github.com/pawalt/cockroach/blob/show_create_database/pkg/sql/crdb_internal.go#L252

I think creating the whole `tree.CreateDatabase` node would just be an extra step to get the same thing `tree.Name` already gets us.

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66033)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @pawalt)

___
*[pkg/sql/delegate/show_table.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66033#-MbHXcP6Al6rYv9BtV2V:-MbgSfgs4o4nj6Lx_wP8:bxiwrpq) ([raw file](https://github.com/cockroachdb/cockroach/blob/791a26f3503e5e33e1d7e9a3ff0f456ffbeb7958/pkg/sql/delegate/show_table.go#L57)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

I don't think so because the escaping in `tree.CreateDatabase` comes from the escaping on `tree.Name`, which I'm using when building the create statement:
https://github.com/pawalt/cockroach/blob/show_create_database/pkg/sql/crdb_internal.go#L252

I think creating the whole `tree.CreateDatabase` node would just be an extra step to get the same thing `tree.Name` already gets us.
</blockquote></details>

But doesn't the `Format` statement of `tree.CreateDatabase` build the whole create statement? My point is that we already have machinery to build a create statement which does take care of escaping -- why not use it instead of duplicating (a part of) it here?

**Review by pawalt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66033)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[pkg/sql/delegate/show_table.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66033#-MbHXcP6Al6rYv9BtV2V:-MbgaeQdDt1RG4MYAL3P:b-6v1964) ([raw file](https://github.com/cockroachdb/cockroach/blob/791a26f3503e5e33e1d7e9a3ff0f456ffbeb7958/pkg/sql/delegate/show_table.go#L57)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

But doesn't the `Format` statement of `tree.CreateDatabase` build the whole create statement? My point is that we already have machinery to build a create statement which does take care of escaping -- why not use it instead of duplicating (a part of) it here?
</blockquote></details>

Oh sorry didn't realize you were talking about the whole statement. You're right that's definitely a cleaner way to go about things. Just pushed up that approach; let me know what you think.

**Review by arulajmani — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66033#-:-MbgcYuo1gEWfMYsYQdl:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @pawalt)

___
*[pkg/sql/delegate/show_table.go, line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66033#-MbHXcP6Al6rYv9BtV2V:-MbgcTMk-moWodauGgnx:b4twwk2) ([raw file](https://github.com/cockroachdb/cockroach/blob/791a26f3503e5e33e1d7e9a3ff0f456ffbeb7958/pkg/sql/delegate/show_table.go#L57)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

Oh sorry didn't realize you were talking about the whole statement. You're right that's definitely a cleaner way to go about things. Just pushed up that approach; let me know what you think.
</blockquote></details>

Nice! Thanks for iterating through on this

**Pull request merged**
