### PR TITLE
sql: propagate result types to inputs during set ops with nulls and tuples

### LINKED ISSUE #59611: roachtest: sqlsmith cannot use tuple on datumVec of type unknown
[(roachtest).sqlsmith/setup=seed/setting=no-mutations failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2629400&tab=buildLog) on [master@171cc86d6d84c110197485b5d886d77cddc12399](https://github.com/cockroachdb/cockroach/commits/171cc86d6d84c110197485b5d886d77cddc12399):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/sqlsmith/setup=seed/setting=no-mutations/run_1
	sqlsmith.go:198,sqlsmith.go:228,test_runner.go:767: error: pq: internal error: cannot use value of type tuple{oid, timestamptz, bytes} on a datumVec of type unknown
		stmt:
		WITH
			with_3311 (col_19774)
				AS (
					SELECT
						*
					FROM
						(
							VALUES
								(
									(
										SELECT
											NULL AS col_19773
										FROM
											defaultdb.public.seed@seed__int8__float8__date_idx AS tab_7977
										ORDER BY
											tab_7977._float4
										LIMIT
											1:::INT8
									)
								)
						)
							AS tab_7978 (col_19774)
					UNION
						SELECT
							*
						FROM
							(
								VALUES
									(
										COALESCE(
											(185351876:::OID, '2006-04-21 02:50:20.000257+00:00':::TIMESTAMPTZ, '\x00':::BYTES),
											(314839184:::OID, '1990-10-10 09:04:36.000503+00:00':::TIMESTAMPTZ, '\x21':::BYTES)
										)
									),
									((3901000074:::OID, '1985-06-09 06:19:47.000198+00:00':::TIMESTAMPTZ, '\x764064':::BYTES)),
									((3116072174:::OID, '1993-04-16 05:14:06.000015+00:00':::TIMESTAMPTZ, '\x15a3b1':::BYTES)),
									(
										(2416637916:::OID, '2012-05-13 20:22:26.00034+00:00':::TIMESTAMPTZ, '\x71b859026fb9':::BYTES)
									)
							)
								AS tab_7979 (col_19775)
				)
		SELECT
			(NULL, '2015-12-13 16:14:45.00086+00:00':::TIMESTAMPTZ, '\x7fa0ad092d268f57d7':::BYTES) AS col_19776
		FROM
			with_3311 AS cte_ref_939;

```

<details><summary>More</summary><p>

Artifacts: [/sqlsmith/setup=seed/setting=no-mutations](https://teamcity.cockroachdb.com/viewLog.html?buildId=2629400&tab=artifacts#/sqlsmith/setup=seed/setting=no-mutations)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Asqlsmith%2Fsetup%3Dseed%2Fsetting%3Dno-mutations.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by yuzefovich**
**sql: move MergeResultTypes from physicalplan package and unexport**

Release note: None

**sql: propagate result types to inputs in set ops with nulls and tuples**

The physical planning for set operations is special because it allows
for the result types from its inputs to be of different type family in
some cases. Namely, it is ok if one input has `types.Unknown` whereas
the other input is of some "known" type. In order to handle such case
the execbuilder plans casts; however, currently it is not possible to
plan casts to `Tuple` type. As a result, the vectorized engine is not
able to execute the query because it expects the data coming from both
inputs to be of the same type.

This commit modifies the logic of reconciling the result types from both
inputs to additionally update unknown types on the inputs if the other
input is of a Tuple type. Such behavior is acceptable because in the
original plan we only expected to have NULL values, and the Tuple type
is able to handle such case too.

The problem can also be reproduced in a logic test with the row-by-row
engine in the `fakedist` setting. This bug was introduced in
a76ee31, and before that change we had
the following behavior: overwrite `plan.ResultTypes` to the merged types
and then plan a stage of distinct processors if we have UNION. This
resulted in the input spec for the input stream to distinct having
correctly set types. After the change, that was no longer the case.

Before that change the vectorized engine couldn't handle such queries
due to type mismatch during `SupportsVectorized` check, so we fell back
to the row-by-row engine. However, this commit makes it so that the
vectorized engine is able to execute such queries.

Fixes: #59611.

Release note (bug fix): CockroachDB previously could encounter an
internal error when performing UNION operation when the first input
resulted only in NULL values and consequent inputs produce tuples, and
this is now fixed. Only 21.1 alpha versions are affected.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
Doesn't the optimizer add casts when one side is Unknown and one side isn't? At the very least, the quoted example `SELECT NULL UNION SELECT 1` doesn't have a problem:
```
demo@127.0.0.1:26257/defaultdb> explain (types) select a from (select null) as t(a) union select 1;
                            info
-------------------------------------------------------------
  distribution: local
  vectorized: false

  • union
  │ columns: (a int)
  │ estimated row count: 2
  │
  ├── • values
  │     columns: (a int)
  │     size: 1 column, 1 row
  │     row 0, expr 0: (CAST((NULL)[unknown] AS INT8))[int]
  │
  └── • values
        columns: ("?column?" int)
        size: 1 column, 1 row
        row 0, expr 0: (1)[int]
```


The problem in the example is that we can't plan casts to tuple:
https://github.com/cockroachdb/cockroach/blob/894efb0215580cddc285e21b1232326b375d391c/pkg/sql/opt/exec/execbuilder/scalar.go#L340

If we want to make this fix until that problem is solved, that's ok, but it should be clearly documented that it only addresses this narrow case.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60827#-:-MU6CmSW9lw3sunWGCZy:b-5wco1u)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by yuzefovich — COMMENTED** [review]
Indeed, I think you're right, my initial explanation was too wide, updated.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60827#-:-MU9y-GQ7C8J0BDmQ56a:b-qdyk2i)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60827#-:-MUB58Iw0dy9YN9xXLuv:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
