### PR TITLE
sql: Fix TestCancelQueriesRace

### LINKED ISSUE #105853: sql: TestCancelQueriesRace is flaky
First observed this failure in a PR that changed unrelated code [1]. I was also able to reproduce the failure by stressing the test with the command below:

```console
./dev test ./pkg/sql -f TestCancelQueriesRace --stress --ignore-cache --cpus 16 --timeout 10m
--- FAIL: TestCancelQueriesRace (1.55s)
    test_log_scope.go:167: test logs captured to: /tmp/cockroach/_tmp/b287de7194e17a0386ee1775f0d198ba/logTestCancelQueriesRace219461028
    test_log_scope.go:81: use -show-logs to present logs inline
    show_test.go:1351: 
                Error Trace:    github.com/cockroachdb/cockroach/pkg/sql_test/pkg/sql/show_test.go:1351
                Error:          Received unexpected error:
                                pq: could not cancel query 176d3f136c1d12710000000000000001: query ID 176d3f136c1d12710000000000000001 not found
                Test:           TestCancelQueriesRace
    panic.go:522: -- test log scope end --
FAIL
I230629 21:39:48.032652 1 (gostd) testmain.go:1030  [-] 1  Test //pkg/sql:sql_test exited with error code 1


ERROR: exit status 1

421 runs completed, 1 failures, over 1m3s
```

[1] <https://teamcity.cockroachdb.com/viewLog.html?buildId=10734269&buildTypeId=Cockroach_BazelEssentialCi>

Jira issue: CRDB-29235

### PR DESCRIPTION
**Pull request by rimadeodhar**
TestCancelQueriesRace attempts to run two query cancellations at the same time in order to reproduce potential data race. However, it makes an invalid assumption that both query cancellations will always succeed which is not true. This PR updates the check to ensure that at least one of the query cancellations is successful.

I stress tested this test locally using `./dev test ./pkg/sql -f TestCancelQueriesRace --stress --ignore-cache --cpus 16 --timeout 5m`. It ran successfully with over a 1000 successful runs.

Epic: none
Fixes: https://github.com/cockroachdb/cockroach/issues/105853
Release note: none

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106458)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rimadeodhar)

**Comment by rimadeodhar** [comment]
TFTR!

bors r=rafiss

**Comment by yuzefovich** [comment]
blathers backport 23.1

**Comment by mgartner** [comment]
blathers backport 22.2

**Pull request merged**
