### PR TITLE
sql: implement `CREATE SCHEMA ... AUTHORIZATION`

### LINKED ISSUE #53559: CREATE SCHEMA... AUTHORIZATION is unsupported
In Postgres,
```
postgres=# create user andy;
CREATE ROLE
postgres=# CREATE SCHEMA AUTHORIZATION andy;
CREATE SCHEMA
postgres=# CREATE SCHEMA andy_schema AUTHORIZATION andy;
CREATE SCHEMA
postgres=# \dn
    List of schemas
    Name     |  Owner
-------------+----------
 andy        | andy
 andy_schema | andy
 public      | postgres
(3 rows)
```

In CockroachDB,
```
root@127.0.0.1:63916/vy> CREATE SCHEMA AUTHORIZATION andy;
invalid syntax: statement ignored: at or near "andy": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
CREATE SCHEMA AUTHORIZATION andy
                            ^
root@127.0.0.1:63916/vy> CREATE SCHEMA andy_schema AUTHORIZATION andy;
invalid syntax: statement ignored: at or near "authorization": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
CREATE SCHEMA andy_schema AUTHORIZATION andy
                          ^
```

We should at least return an unimplemented error

### PR DESCRIPTION
**Pull request by rohany**
Fixes #53559.

This commit adds the `CREATE SCHEMA ... AUTHORIZATION` command. When
authorization is provided, the target user is given ownership of the
schema. If the schema name is not provided, then the schema is named the
same name as the target role.

Release justification: low risk updates to new functionality
Release note (sql change): Support the `CREATE SCHEMA ... AUTHORIZATION`
command.

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53583#-:-MG4TvFd9jLXgJz8R1Pj:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lucy-zhang, @rohany, and @solongordon)

___
*[pkg/sql/create_schema.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53583#-MG4T98i5tko7h4S5Gbv:-MG4T98j1XgSgUMsVf3x:b-41l6w9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dac1884f97b468fbb31b11de887d643745cd011/pkg/sql/create_schema.go#L73)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 	// Check validity of the schema name.
> 	if err := schemadesc.IsSchemaNameValid(schemaName); err != nil {
> 		return err
> 	}
> ```
</details>

Should we do this check before the existence check?
___
*[pkg/sql/parser/sql.y, line 5297 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53583#-MG4TG7X3TbOJnELf60m:-MG4TG7X3TbOJnELf60n:b-elnhe3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4dac1884f97b468fbb31b11de887d643745cd011/pkg/sql/parser/sql.y#L5297)):*
> ```Yacc
> // %Category: DDL
> // %Text:
> // CREATE SCHEMA [IF NOT EXISTS] <schemaname> [AUTHORIZATION <rolename>]
> ```

nit: should this be `CREATE SCHEMA [IF NOT EXISTS] { <schemaname> | [ [<schemaname>] AUTHORIZATION <rolename>] }`

**Comment by rohany** [comment]
Done, addressed both comments

bors r+

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53583)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @lucy-zhang, @rohany, and @solongordon)

___
*[pkg/sql/create_schema.go, line 59 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53583#-MG4omeQCqrpD4dKJ46k:-MG4omeQCqrpD4dKJ46l:bv1mo0j) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c061b7e603d6c3a8376e4362d187aa94135bcfb/pkg/sql/create_schema.go#L59)):*
> ```Go
> 
> 	// Check validity of the schema name.
> 	if err := schemadesc.IsSchemaNameValid(schemaName); err != nil {
> ```

seems like re-arranging this broke some tests :grimacing:

**Review by ajwerner — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53583)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @lucy-zhang, @rohany, and @solongordon)

___
*[pkg/sql/parser/sql.y, line 5297 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/53583#-MG4owAI7GKB2JPCeTA_:-MG4owAI7GKB2JPCeTAa:b-x8h8r) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c061b7e603d6c3a8376e4362d187aa94135bcfb/pkg/sql/parser/sql.y#L5297)):*
> ```Yacc
> // %Category: DDL
> // %Text:
> // CREATE SCHEMA [IF NOT EXISTS] { <schemaname> | [<schemaname>] [AUTHORIZATION <rolename>] }
> ```

also, I don't think this means the same thing as what I wrote. This seems to imply that you could omit both elements of the RHS. I think you could do:

`CREATE SCHEMA [IF NOT EXISTS] { <schemaname> | [<schemaname>] AUTHORIZATION <rolename> }`

**Comment by rohany** [comment]
Ah yeah you're right, can't have brackets around the `AUTHORIZATION ...`

**Comment by knz** [comment]
this is failing ci - removing from the bors queue

bors r-

**Comment by rohany** [comment]
Updated the help message.

Seems like we need to keep the name check after the existence check.

**Comment by rohany** [comment]
@ajwerner can you stamp this?

**Review by thoszhang — APPROVED** [review]
> Reviewed 4 of 6 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53583)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rohany and @solongordon)

**Review by ajwerner — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53583#-:-MG5M9-j99BSFY6sIsjD:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rohany and @solongordon)

**Pull request merged**
