### PR TITLE
storage: ingest columnar-block sstables when enabled

### PR DESCRIPTION
**Pull request by jbowens**
When the active cluster verison is sufficiently high and the columnar blocks cluster setting is enabled, build sstables for ingestion in table format TableFormatPebblev5 with columnar blocks.

Epic: none
Release note: none

### CODE REVIEW

**Review by jbowens — COMMENTED** [review]
Looks like the MVCC histories tests are going to require some work; they add keys to the sstable out-of-order? Not sure how that wasn't caught by the old SST writer.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134671#-:-OBBXwSh8arEqt-G6Ary:b-46z6vd)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Review by RaduBerinde — APPROVED** [review]

**Review by jbowens — COMMENTED** [review]
@RaduBerinde I made some minor tweaks to fix up the remaining tests, if you want to give it another look, otherwise I'll merge away in a few days (want to avoid adding fuel to the fire on master with this replica inconsistency investigation ongoing)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134671#-:-OBfMF5PARFgsGu3iFuJ:bm0pkf0)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained

**Review by RaduBerinde — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134671#-:-OBfkpdjALJMXh8E7u0t:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained

**Comment by jbowens** [comment]
TFTR!

bors r=RaduBerinde

**Review by RaduBerinde — APPROVED** [review]

**Comment by jbowens** [comment]
poked the cla status

bors r=RaduBerinde

**Pull request merged**
