### PR TITLE
sql: Add the ability to access a specific column in a labeled tuple

### PR DESCRIPTION
**Pull request by BramGruneir**
This work is yet another step towards #16971.

The labeled tuples introduced in #25283 can now be accessed using their labels.
It's important to note that they require an extra parentheses around them to
do so.

```sql
SELECT (((1,'2',true) AS a, b, c)).a
+---+
| a |
+---+
| 1 |
+---+

SELECT (((1,'2',true) AS a, b, c)).b
+---+
| b |
+---+
| 2 |
+---+

SELECT (((1,'2',true) AS a, b, c)).c
+------+
|  c   |
+------+
| true |
+------+
```

This change prompted the need to restrict the labels in the tuple to be unique;
checks and test cases for that have been added as well.

Star expansion is still not allowed.

Release note: Labeled tuples can now be accessed using their labels (e.g.
`SELECT (((1,'2',true) AS a, b, c)).a` but it requires an extra level of
parentheses to do so.

### CODE REVIEW

**Comment by BramGruneir** [comment]
*[pkg/sql/sem/tree/type_check.go, line 890 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25810#-LD7lbx3EtNXifWE3MgR:-LD7lbx54IzoTNLB4ofN:b-4h7lar) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7705eee4eaef025abbbb7d31464398ce1e11b7c/pkg/sql/sem/tree/type_check.go#L890)):*
> ```Go
> 	if len(expr.Labels) > 0 {
> 		// Ensure that there are no repeat labels.
> 		uniqueLabels := map[string]struct{}{}
> ```

This worries me a bit.  It uses memory and I don't think it fully safeguards against it.  The alternative is to do a single pass through all the labels in the columnAccessExpr type check to see if there is a double and if so fail for being ambiguous.

Thoughts?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25810)*

**Comment by knz** [comment]
This implementation is adequate because it is correct. Just a few nits below.

Meanwhile, since our discussion yesterday I have thought of an optimization. See my comment below. Let me know what you think.

---

Reviewed 6 of 9 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/logictest/testdata/logic_test/tuple, line 797 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25810#-LDBIIrc6DNlcVs4OWqM:-LDBIIrc6DNlcVs4OWqN:b-m09shn) ([raw file](https://github.com/cockroachdb/cockroach/blob/c18ff54eae446c98bca9e17b5101c90ede01b08a/pkg/sql/logictest/testdata/logic_test/tuple#L797)):*
> ```
> 
> # Ensure the number of labels matches the number of expressions
> query error pq: the number of expressions in a labeled tuple \(2\) must match the number of labels \(1\)
> ```

This is super verbose. I'd recommend more simply: `mismatch in tuple definition: %d expressions, %d labels`

---

*[pkg/sql/sem/tree/eval.go, line 3398 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25810#-LDBJP1x01N9zdc8pGYb:-LDBJP1x01N9zdc8pGYc:b-5r0ia7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c18ff54eae446c98bca9e17b5101c90ede01b08a/pkg/sql/sem/tree/eval.go#L3398)):*
> ```Go
> // Eval implements the TypedExpr interface.
> func (expr *ColumnAccessExpr) Eval(ctx *EvalContext) (Datum, error) {
> 	d, err := expr.Expr.(TypedExpr).Eval(ctx)
> ```

Idea for optimization: keep the error that was here originally. See my other comment below.

---

*[pkg/sql/sem/tree/expr.go, line 1496 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25810#-LDBJUKQ627hNwU5dsdT:-LDBJUKQ627hNwU5dsdU:bteesw8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c18ff54eae446c98bca9e17b5101c90ede01b08a/pkg/sql/sem/tree/expr.go#L1496)):*
> ```Go
> 	ColName  string
> 	Star     bool
> 	ColIndex int // This should only be set during type checking.
> ```

Idea for optimization: do not add this field. See my comment below.

---

*[pkg/sql/sem/tree/type_check.go, line 890 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25810#-LD7lbx3EtNXifWE3MgR:-LDBHyvvCpDQ6HNc5HKw:b-tj8duy) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7705eee4eaef025abbbb7d31464398ce1e11b7c/pkg/sql/sem/tree/type_check.go#L890)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

This worries me a bit.  It uses memory and I don't think it fully safeguards against it.  The alternative is to do a single pass through all the labels in the columnAccessExpr type check to see if there is a double and if so fail for being ambiguous.

Thoughts?

</blockquote></details>

Yes I think the n^2 algorithm is appropriate here:

```go
for i := range expr.Labels {
   for j := 0; j < i; j++ {
       if expr.Labels[i] == expr.Labels[j] { ... error ... }
   }
}
```

Make the error: `"found duplicate tuple label: %q", tree.ErrString(...)`

---

*[pkg/sql/sem/tree/type_check.go, line 406 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25810#-LDBHnVb5Ds_K6_ZfcUV:-LDBHnVb5Ds_K6_ZfcUW:bpwedzk) ([raw file](https://github.com/cockroachdb/cockroach/blob/c18ff54eae446c98bca9e17b5101c90ede01b08a/pkg/sql/sem/tree/type_check.go#L406)):*
> ```Go
> 
> 	// Ensure that the tuple is indeed labeled.
> 	if len(resolvedType.(types.TTuple).Labels) == 0 {
> ```

factor the `.(types.TTuple)` cast so it's just performed once

---

*[pkg/sql/sem/tree/type_check.go, line 417 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25810#-LDBJ_PpBznjE5meBka2:-LDBJ_PpBznjE5meBka3:br4jdk9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c18ff54eae446c98bca9e17b5101c90ede01b08a/pkg/sql/sem/tree/type_check.go#L417)):*
> ```Go
> 
> 	// Go through all of the labels to find a match.
> 	expr.ColIndex = -1
> ```

Idea for optimization: define a local variable `colIndex` instead of storing in `expr`. Then see below.

---

*[pkg/sql/sem/tree/type_check.go, line 429 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25810#-LDBJda9CPmoW8zLED4v:-LDBJda9CPmoW8zLED4w:ba9foqj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c18ff54eae446c98bca9e17b5101c90ede01b08a/pkg/sql/sem/tree/type_check.go#L429)):*
> ```Go
> 			"could not identify column \"%s\" in %s", expr.ColName, resolvedType)
> 	}
> ```

Idea for optimization, here:

`return expr.Expr.(*Tuple).Exprs[colIndex], nil`

And zoooooom - both the ColumnAccessExpr and the tuple evaporate in a puff of nothingness.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25810#-:-LDBJ4je3F5lbPomVhQk:b-bukbe7)*

**Comment by BramGruneir** [comment]
All comments addressed.  PTAL.

---

Review status: 4 of 9 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/sql/logictest/testdata/logic_test/tuple, line 797 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25810#-LDBIIrc6DNlcVs4OWqM:-LDDvb1wBeQhYeArGJNt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c18ff54eae446c98bca9e17b5101c90ede01b08a/pkg/sql/logictest/testdata/logic_test/tuple#L797)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This is super verbose. I'd recommend more simply: `mismatch in tuple definition: %d expressions, %d labels`
</blockquote></details>

Done.

---

*[pkg/sql/sem/tree/eval.go, line 3398 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25810#-LDBJP1x01N9zdc8pGYb:-LDImzTYEFUNy8EfFEmv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c18ff54eae446c98bca9e17b5101c90ede01b08a/pkg/sql/sem/tree/eval.go#L3398)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Idea for optimization: keep the error that was here originally. See my other comment below.
</blockquote></details>

Done.

---

*[pkg/sql/sem/tree/type_check.go, line 890 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25810#-LD7lbx3EtNXifWE3MgR:-LDHWFaJ0I1sx03WHlkM:brjmzwu) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7705eee4eaef025abbbb7d31464398ce1e11b7c/pkg/sql/sem/tree/type_check.go#L890)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Yes I think the n^2 algorithm is appropriate here:

```go
for i := range expr.Labels {
   for j := 0; j < i; j++ {
       if expr.Labels[i] == expr.Labels[j] { ... error ... }
   }
}
```

Make the error: `"found duplicate tuple label: %q", tree.ErrString(...)`

</blockquote></details>

Done,.

I could just check for the duplicate label when pulling out the column instead of during the definition. 
And only do a single pass.

---

*[pkg/sql/sem/tree/type_check.go, line 406 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25810#-LDBHnVb5Ds_K6_ZfcUV:-LDDwZuNB2E8Ai-lxch9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c18ff54eae446c98bca9e17b5101c90ede01b08a/pkg/sql/sem/tree/type_check.go#L406)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

factor the `.(types.TTuple)` cast so it's just performed once
</blockquote></details>

Done.

---

*[pkg/sql/sem/tree/type_check.go, line 417 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25810#-LDBJ_PpBznjE5meBka2:-LDIn9oUEchPP55Ebc2p:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c18ff54eae446c98bca9e17b5101c90ede01b08a/pkg/sql/sem/tree/type_check.go#L417)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Idea for optimization: define a local variable `colIndex` instead of storing in `expr`. Then see below.
</blockquote></details>

Done.

---

*[pkg/sql/sem/tree/type_check.go, line 429 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25810#-LDBJda9CPmoW8zLED4v:-LDIuu7f3BNKyTEY3n2b:b-5tze5q) ([raw file](https://github.com/cockroachdb/cockroach/blob/c18ff54eae446c98bca9e17b5101c90ede01b08a/pkg/sql/sem/tree/type_check.go#L429)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Idea for optimization, here:

`return expr.Expr.(*Tuple).Exprs[colIndex], nil`

And zoooooom - both the ColumnAccessExpr and the tuple evaporate in a puff of nothingness.
</blockquote></details>

Wonderful idea.

Done.

---

*[pkg/sql/sem/tree/expr.go, line 1496 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25810#-LDBJUKQ627hNwU5dsdT:-LDIn-etAOGVcJw5mTgV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c18ff54eae446c98bca9e17b5101c90ede01b08a/pkg/sql/sem/tree/expr.go#L1496)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Idea for optimization: do not add this field. See my comment below.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25810#-:-LDIxhhA81w3L5Jl-zJo:b-eluzqc)*

**Comment by knz** [comment]
:lgtm: with a nit and a required fix. See comment below.

---

Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/sql/sem/tree/type_check.go, line 435 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25810#-LDMPD4b8GOBunmL03Zi:-LDMPD4b8GOBunmL03Zj:b2j3aoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/c249d4519fb1f50ad171b3d8b6695dd29c74bad0/pkg/sql/sem/tree/type_check.go#L435)):*
> ```Go
> 	}
> 
> 	return expr.Expr.(*Tuple).Exprs[colIndex].TypeCheck(ctx, desired)
> ```

You need to call `TypeCheck` here. It was already done at the beginning. Just cast the result with `return ... .(TypedExpr)`

---

*[pkg/sql/sem/tree/type_check.go, line 898 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25810#-LDMPRZcE-s3_nT1aVYS:-LDMPRZcE-s3_nT1aVYT:b-x86ahi) ([raw file](https://github.com/cockroachdb/cockroach/blob/c249d4519fb1f50ad171b3d8b6695dd29c74bad0/pkg/sql/sem/tree/type_check.go#L898)):*
> ```Go
> 				if expr.Labels[i] == expr.Labels[j] {
> 					return nil, pgerror.NewErrorf(pgerror.CodeSyntaxError,
> 						"found duplicate tuple label: %q", ErrString(expr),
> ```

I'd recommend `ErrString(expr.Labels)` otherwise the message could become super verbose (imagine if the expression contains a subquery...).

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25810#-:-LDMPakB8J-EP4vjPsyU:b-bskxxy)*

**Comment by BramGruneir** [comment]
TFTR!

---

Review status: 6 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/sem/tree/type_check.go, line 435 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25810#-LDMPD4b8GOBunmL03Zi:-LDMxWXC3MPaNb-YzYMe:b-fdnmb8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c249d4519fb1f50ad171b3d8b6695dd29c74bad0/pkg/sql/sem/tree/type_check.go#L435)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

You need to call `TypeCheck` here. It was already done at the beginning. Just cast the result with `return ... .(TypedExpr)`
</blockquote></details>

Ah, excellent, I was annoyed by that.

---

*[pkg/sql/sem/tree/type_check.go, line 898 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25810#-LDMPRZcE-s3_nT1aVYS:-LDNAxXh509TUt-YfuKi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c249d4519fb1f50ad171b3d8b6695dd29c74bad0/pkg/sql/sem/tree/type_check.go#L898)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I'd recommend `ErrString(expr.Labels)` otherwise the message could become super verbose (imagine if the expression contains a subquery...).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25810#-:-LDNAtxpEhQsd1lyNAtA:b-814g8k)*

**Comment by knz** [comment]
Reviewed 3 of 4 files at r4.
Review status: 8 of 9 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25810)*

**Comment by knz** [comment]
Reviewed 1 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25810)*

**Pull request merged**
