### PR TITLE
geoprojbase: require bounds for all SRIDs

### PR DESCRIPTION
**Pull request by otan**
Trying to establish good rules and hygiene and force all SRIDs to come
with defined bounds. This will help with some of the primary key
encoding changes that I'm about to do.

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51868#-:-MD-obMPC8TPpGiEu_Hz:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[pkg/geo/geoindex/s2_geometry_index_test.go, line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51868#-MD-n_hW5u4qNkK0TW0L:-MD-n_hW5u4qNkK0TW0M:b-78yfpt) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b3372de8447dc67d6d9c1e946d702f9b499db00/pkg/geo/geoindex/s2_geometry_index_test.go#L132)):*
> ```Go
> 			require.NoError(t, err)
> 			index := NewS2GeometryIndex(*config.S2Geometry)
> 			require.NoError(t, err)
> ```

this second check is unnecessary since err hasn't changed
___
*[pkg/geo/geoprojbase/projections.go, line 4773 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51868#-MD-o8u15oHOXqjuazCp:-MD-o8u15oHOXqjuazCq:b-nbesd3) ([raw file](https://github.com/cockroachdb/cockroach/blob/81cc169f642e98b5f7c3d561519e79a6dcb8f4b1/pkg/geo/geoprojbase/projections.go#L4773)):*
> ```Go
> 		},
> 	},
> 	102017: {
> ```

Why did you get rid of these?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51868)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft and @sumeerbhola)

___
*[pkg/geo/geoindex/s2_geometry_index_test.go, line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51868#-MD-n_hW5u4qNkK0TW0L:-MD0KysM9746c9asTAv3:b-sis5yd) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b3372de8447dc67d6d9c1e946d702f9b499db00/pkg/geo/geoindex/s2_geometry_index_test.go#L132)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

this second check is unnecessary since err hasn't changed
</blockquote></details>

force of habit with Go :\
___
*[pkg/geo/geoprojbase/projections.go, line 4773 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51868#-MD-o8u15oHOXqjuazCp:-MD0L-61AavdrBUfbYvw:bxuac9y) ([raw file](https://github.com/cockroachdb/cockroach/blob/81cc169f642e98b5f7c3d561519e79a6dcb8f4b1/pkg/geo/geoprojbase/projections.go#L4773)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Why did you get rid of these?
</blockquote></details>

Thought they were useful for another builtin but turns out they were not :)

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51868)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @sumeerbhola)

**Comment by otan** [comment]
thanks!

bors r=rytaft

**Pull request merged**
