### PR TITLE
server: fold self-bootstrap into init-bootstrap code

### PR DESCRIPTION
**Pull request by tbg**
The two methods for bootstrapping a new cluster are starting an
uninitialized node without join flags and starting an uninitialized node
with joins flags followed by a BootstrapCluster RPC to it. The former
can easily be modeled by the latter, so let's do that: if we're started
without join flags, start the init server and send an RPC to it.

This unifies our bootstrap code and makes it simpler to think about.

Release note: None

### CODE REVIEW

**Review by andreimatei — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36928)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @tbg)

___
*[pkg/server/server.go, line 1407 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36928#-LcrJKoq4MEVzaBSn38T:-LcrJKoq4MEVzaBSn38U:b-j5kyhh) ([raw file](https://github.com/cockroachdb/cockroach/blob/e03a339995d7297bdbb65663800ab521fb357e2f/pkg/server/server.go#L1407)):*
> ```Go
> 		)
> 	} else {
> 		// We have no existing stores and we've been told to join a cluster. Wait
> ```

update this comment somehow
___
*[pkg/server/server.go, line 1450 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36928#-LcrJfoe29nR72bhFT0y:-LcrJfoe29nR72bhFT0z:b3t4b8f) ([raw file](https://github.com/cockroachdb/cockroach/blob/e03a339995d7297bdbb65663800ab521fb357e2f/pkg/server/server.go#L1450)):*
> ```Go
> 			// this if this node is being started with itself specified as a
> 			// --join host, because that's too likely to be operator error.
> 			if err := s.stopper.RunAsyncTask(ctx, "bootstrap", func(ctx context.Context) {
> ```

did you use `RunAsyncTask()` so that the bootstrap wouldn't be left half-done if the server is asked to shut down nicely while doing it?
Please add some comment justifying it... Or just remove it :)

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36928)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/server/server.go, line 1407 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36928#-LcrJKoq4MEVzaBSn38T:-LdEGE4p73G3PFjkQP4x:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e03a339995d7297bdbb65663800ab521fb357e2f/pkg/server/server.go#L1407)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

update this comment somehow
</blockquote></details>

Done.
___
*[pkg/server/server.go, line 1450 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36928#-LcrJfoe29nR72bhFT0y:-LdEG8kD0HlQ0O8_sls2:bnt4g6z) ([raw file](https://github.com/cockroachdb/cockroach/blob/e03a339995d7297bdbb65663800ab521fb357e2f/pkg/server/server.go#L1450)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

did you use `RunAsyncTask()` so that the bootstrap wouldn't be left half-done if the server is asked to shut down nicely while doing it?
Please add some comment justifying it... Or just remove it :)
</blockquote></details>

No reasoning here. For some reason I thought I would have to call `awaitBootstrap` first and then I could bootstrap, but that's not true. Done.

**Comment by tbg** [comment]
bors r=andreimatei

**Comment by tbg** [comment]
OOM in TestVet

bors r=andreimatei

**Pull request merged**
