### PR TITLE
distsql: post-processing infrastructure for projection, filtering

### PR DESCRIPTION
**Pull request by RaduBerinde**
Adding a generic mechanism to specify output columns and filters; these steps
are described in a `PostProcessSpec` which is part of `ProcessorSpec`.

The intention is to add limit and rendering (replacing evaluator) to
`PostProcessSpec`.

I strongly considered an alternative (suggested by Andrei) to specify these as
full-blown processors but have the `distsqlrun` code figure out that their
processing can be "fused" with that of the previous processor. I didn't go that
route because:

 - it is easier to figure out this "fusing" at the physical planning stage; to
   figure it out in `distsqlrun` we need to traverse processing chains in order
   (which is tedious because the spec is just a list of nodes and edges);

 - with separate processors the spec becomes more verbose with respect to
   output projections; e.g. for a processor that outputs columns 1 and 3 and has
   a filter that uses column 2, we have to specify the intermediary output
   projection 1,2,3;

 - I prefer the spec and flow diagrams to be closer to what we actually end up
   running;

 - `RowReceiver.PushRow` precludes reuse of the row by the caller, requiring an
   allocation in many cases; we don't want to do a useless intermediary
   allocation for rows that end up filtered out. So we couldn't simply hide the
   "fusing" behind the `RowReceiver` interface.

I am open to reconsidering this choice in the future, but for now this solution
is more straightforward.

The post-processing infrastructure allows us to add a filter to any stage; add
support for filter node.

Now that we have a generic way to set a projection on each processor, we can
fix two cases where we had unnecessary columns in output streams:
 - a renderNode with trivial expressions which only exposes a subset
   of the columns (e.g. `SELECT a FROM t WHERE b > 1`),
 - a sortNode which doesn't expose all the source columns (e.g.
   `SELECT a FROM T ORDER BY b`).

CC @arjunravinarayan in case you are interested in taking a look (even if just for the .proto changes).

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13003)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Added a commit that makes things a bit nicer in the planning code.

**Comment by andreimatei** [comment]
LGTM. Good stuff! 

>I prefer the spec and flow diagrams to be closer to what we actually end up
> running;

What we end up running should be custom generated x86 code; then the spec will be super accurate :troll:

> RowReceiver.PushRow precludes reuse of the row by the caller, requiring an
> allocation in many cases; we don't want to do a useless intermediary
> allocation for rows that end up filtered out. So we couldn't simply hide the
> "fusing" behind the RowReceiver interface.

I guess one way to optimize this would be to have a `rowAlloc` per fused group of processors.

---

Reviewed 6 of 31 files at r2.
Review status: 6 of 33 files reviewed at latest revision, 11 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql_physical_planner.go, line 438 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13003#-KbBlP11DeLJr337qHm5:-KbBlP123A454iaodsjv:b-l26mit) ([raw file](https://github.com/cockroachdb/cockroach/blob/132232bb0de7a811b24bad1b31a6887a8d637626/pkg/sql/distsql_physical_planner.go#L438)):*
> ```Go
> // addFilter adds a filter on the output of a plan. The filter is added as a
> // post-processing step to the last stage.
> func addFilter(p *physicalPlan, expr parser.TypedExpr, columnMap []int) {
> ```

I think `columnMap` deserves a comment about how it remaps indexes in the expression.

---

*[pkg/sql/distsql_physical_planner.go, line 441 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13003#-KbBmAHokVuua3_jjonb:-KbBmAHokVuua3_jjonc:bqepxcd) ([raw file](https://github.com/cockroachdb/cockroach/blob/132232bb0de7a811b24bad1b31a6887a8d637626/pkg/sql/distsql_physical_planner.go#L441)):*
> ```Go
> 	post := p.getLastStagePost()
> 
> 	// The filter expression variables (after remapping via the columnMap) refer
> ```

this comment is great, but it can still be made clearer. What is "this processor"? You might have wanted to say "output columns of a planNode". I think we should clarify that the filter is added after processors in the last stage have been configured with their projections.

---

*[pkg/sql/distsql_physical_planner.go, line 763 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13003#-KbBoe_JMCtXCu50xsBd:-KbBoe_JMCtXCu50xsBe:br7gsk3) ([raw file](https://github.com/cockroachdb/cockroach/blob/acad9e441ab8699f03c0e32346d5e9b7e80b9f03/pkg/sql/distsql_physical_planner.go#L763)):*
> ```Go
> 	}
> 	if !needEval {
> 		// We don't need an evaluator stage; we just need to mess with the
> ```

"we just need to adjust the projection to output only the columns of the renderNode"

---

*[pkg/sql/distsqlrun/joinreader.go, line 80 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13003#-KbBbHqe-gJHmuk5IJvQ:-KbBbHqe-gJHmuk5IJvR:b-xb17md) ([raw file](https://github.com/cockroachdb/cockroach/blob/7133fab914c421897990c64bff28225fdd82242d/pkg/sql/distsqlrun/joinreader.go#L80)):*
> ```Go
> 	var err error
> 	jr.index, _, err = initRowFetcher(
> 		&jr.fetcher, &jr.desc, int(spec.IndexIdx), false, jr.out.neededColumns(),
> ```

pls comment the `false` as `/* reverse */`

---

*[pkg/sql/distsqlrun/processors.go, line 100 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13003#-KbBcpDoDRlTXhX-H-3W:-KbBcpDpDAnBqAtJDZYL:b-hq2wax) ([raw file](https://github.com/cockroachdb/cockroach/blob/7133fab914c421897990c64bff28225fdd82242d/pkg/sql/distsqlrun/processors.go#L100)):*
> ```Go
> }
> 
> func (h *procOutputHelper) emitRow(ctx context.Context, row sqlbase.EncDatumRow) bool {
> ```

should we comment that the caller can reuse `row`, in contrast to `RowReceiver.pushRow()`?

---

*[pkg/sql/distsqlrun/processors.go, line 124 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13003#-KbB_sVQ_GlVF1A-0X9F:-KbB_sVQ_GlVF1A-0X9G:b-5w5ezy) ([raw file](https://github.com/cockroachdb/cockroach/blob/7133fab914c421897990c64bff28225fdd82242d/pkg/sql/distsqlrun/processors.go#L124)):*
> ```Go
> 		}
> 	}
> 	if log.VDepth(1, 3) {
> ```

lol that's a new one. Are you sure we need this? The `3` seems very fragile.

---

*[pkg/sql/distsqlrun/processors.proto, line 49 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13003#-KbBDSePQ2Wo9i6tCDXF:-KbBDSePQ2Wo9i6tCDXG:b-nkdrob) ([raw file](https://github.com/cockroachdb/cockroach/blob/7133fab914c421897990c64bff28225fdd82242d/pkg/sql/distsqlrun/processors.proto#L49)):*
> ```protobuf
> // columns of the rows that pass a filter expression.
> //
> // The internal columns of a TableReader are the columns of the table.
> ```

Here and below, what does "internal columns" mean? Maybe put a comment on a processor spec describing them as "the input to the post-processor stage".?

---

*[pkg/sql/distsqlrun/processors.proto, line 49 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13003#-KbBUnteznJI7ZkDI-NM:-KbBUntfMLO1yWryGZKd:bgnrku4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7133fab914c421897990c64bff28225fdd82242d/pkg/sql/distsqlrun/processors.proto#L49)):*
> ```protobuf
> // columns of the rows that pass a filter expression.
> //
> // The internal columns of a TableReader are the columns of the table.
> ```

is it true that the internal columns are *all* the columns of the table? I think it's just the `neededColumns()` returned by the postprocessor?
After reading more code, I think the internal columns are indeed all the columns (in the sense that and `EncDatumRow` with slots for all cols will be passed to the `TableReader`'s `outputHelper`, but not all the slots will be populated with a value. This should be explained somewhere; I think the "internal column" concept needs more explanation.

---

*[pkg/sql/distsqlrun/processors.proto, line 254 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13003#-KbBF4CD3c9u1QipxnR4:-KbBF4CD3c9u1QipxnR5:bh3txxb) ([raw file](https://github.com/cockroachdb/cockroach/blob/7133fab914c421897990c64bff28225fdd82242d/pkg/sql/distsqlrun/processors.proto#L254)):*
> ```protobuf
> // (filtering, projection). It operates on the internal schema of the processor
> // core.
> message PostProcessSpec {
> ```

nit: move `ProcessorSpec` at the top of the file.

---

*[pkg/sql/distsqlrun/processors.proto, line 261 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13003#-KbBMO8rNsEjcMuVJxqC:-KbBMO8smFCE2T1bklSP:b-iazboj) ([raw file](https://github.com/cockroachdb/cockroach/blob/7133fab914c421897990c64bff28225fdd82242d/pkg/sql/distsqlrun/processors.proto#L261)):*
> ```protobuf
>   // Every processor has an internal set of columns (as described above); it may
>   // only emit some of them, as described by this list. This can be omitted for
>   // some processors (like Evaluator, Aggregator) where the mapping is a trivial
> ```

this doesn't make it very clear what it means if the list is empty. Are all "internal cols" going to be emitted?

---

*[pkg/sql/distsqlrun/tablereader.go, line 175 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13003#-KbBX-cUkgW_aEuEo8ym:-KbBX-cVW3oO0txRAFlY:bpntaxo) ([raw file](https://github.com/cockroachdb/cockroach/blob/7133fab914c421897990c64bff28225fdd82242d/pkg/sql/distsqlrun/tablereader.go#L175)):*
> ```Go
> 			return
> 		}
> 		/*
> ```

what's up with this commented out code?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13003#-:-KbBCmTnKiCliJF_G-nF:b-ac2lt)*

**Comment by RaduBerinde** [comment]
TFTR! Great comments, all addressed. Let me know if the proto comments make more sense now.

---

Review status: 0 of 33 files reviewed at latest revision, 11 unresolved discussions.

---

*[pkg/sql/distsql_physical_planner.go, line 438 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13003#-KbBlP11DeLJr337qHm5:-KbCTmRk1MmRaEJiwmLN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/132232bb0de7a811b24bad1b31a6887a8d637626/pkg/sql/distsql_physical_planner.go#L438)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think `columnMap` deserves a comment about how it remaps indexes in the expression.
</blockquote></details>

Done.

---

*[pkg/sql/distsql_physical_planner.go, line 441 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/13003#-KbBmAHokVuua3_jjonb:-KbCUZVrheixuCF8KWU0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/132232bb0de7a811b24bad1b31a6887a8d637626/pkg/sql/distsql_physical_planner.go#L441)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

this comment is great, but it can still be made clearer. What is "this processor"? You might have wanted to say "output columns of a planNode". I think we should clarify that the filter is added after processors in the last stage have been configured with their projections.
</blockquote></details>

Done.

---

*[pkg/sql/distsql_physical_planner.go, line 763 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/13003#-KbBoe_JMCtXCu50xsBd:-KbCUgLCtz0HOx_nOOl8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/acad9e441ab8699f03c0e32346d5e9b7e80b9f03/pkg/sql/distsql_physical_planner.go#L763)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

"we just need to adjust the projection to output only the columns of the renderNode"
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/joinreader.go, line 80 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13003#-KbBbHqe-gJHmuk5IJvQ:-KbCVHqjqgHWvyIwLxwO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7133fab914c421897990c64bff28225fdd82242d/pkg/sql/distsqlrun/joinreader.go#L80)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

pls comment the `false` as `/* reverse */`
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/processors.go, line 100 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13003#-KbBcpDoDRlTXhX-H-3W:-KbCVUX2gN_4WUQ-ah3e:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7133fab914c421897990c64bff28225fdd82242d/pkg/sql/distsqlrun/processors.go#L100)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

should we comment that the caller can reuse `row`, in contrast to `RowReceiver.pushRow()`?
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/processors.go, line 124 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13003#-KbB_sVQ_GlVF1A-0X9F:-KbCVYjFtB61Iygew8Oy:b-bja99m) ([raw file](https://github.com/cockroachdb/cockroach/blob/7133fab914c421897990c64bff28225fdd82242d/pkg/sql/distsqlrun/processors.go#L124)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

lol that's a new one. Are you sure we need this? The `3` seems very fragile.
</blockquote></details>

the 1 was the level (meaning the caller) but I agree it's probably not that useful, simplified to `V(3)`

---

*[pkg/sql/distsqlrun/processors.proto, line 49 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13003#-KbBDSePQ2Wo9i6tCDXF:-KbCSAMu6MwgrKfHhj74:bjfblnd) ([raw file](https://github.com/cockroachdb/cockroach/blob/7133fab914c421897990c64bff28225fdd82242d/pkg/sql/distsqlrun/processors.proto#L49)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Here and below, what does "internal columns" mean? Maybe put a comment on a processor spec describing them as "the input to the post-processor stage".?
</blockquote></details>

I moved the processor spec to the top and explained it better. If you have a short name that's better than "internal columns" let me know (maybe "core output columns"?)

---

*[pkg/sql/distsqlrun/processors.proto, line 254 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13003#-KbBF4CD3c9u1QipxnR4:-KbCSSWflyFhQ2sT82nm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7133fab914c421897990c64bff28225fdd82242d/pkg/sql/distsqlrun/processors.proto#L254)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: move `ProcessorSpec` at the top of the file.
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/processors.proto, line 261 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13003#-KbBMO8rNsEjcMuVJxqC:-KbCSUwrWK3CHSfN1zIr:bjhrbs9) ([raw file](https://github.com/cockroachdb/cockroach/blob/7133fab914c421897990c64bff28225fdd82242d/pkg/sql/distsqlrun/processors.proto#L261)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

this doesn't make it very clear what it means if the list is empty. Are all "internal cols" going to be emitted?
</blockquote></details>

Yes, updated.

---

*[pkg/sql/distsqlrun/tablereader.go, line 175 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13003#-KbBX-cUkgW_aEuEo8ym:-KbCVrOz022LwFGmhK5X:bf57ksj) ([raw file](https://github.com/cockroachdb/cockroach/blob/7133fab914c421897990c64bff28225fdd82242d/pkg/sql/distsqlrun/tablereader.go#L175)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

what's up with this commented out code?
</blockquote></details>

I have a change on top of this PR that adds limit support in PostProcessSpec and cleans this up; I will post that as soon as this is merged.

We can't leave it as is because `hardLimit` used to refer to the number of rows output after any filtering but now filtering happens after (as part of `emitRow`).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13003#-:-KbCWjT5hJaT7BEbpnYv:bewmfpq)*

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 33 files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13003#-:-KbGLOZeExVyPKUXNdxJ:bnfp4nl)*

**Comment by andreimatei** [comment]
thanks

---

Review status: 0 of 33 files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13003#-:-KbGLPRsSagZm0XpkRAI:b-k73z76)*

**Pull request merged**
