### PR TITLE
opt, sql: add end-to-end support for uniqueness checks

### PR DESCRIPTION
**Pull request by rytaft**
**opt: generalize explain output for constraint checks**

This commit changes the explain output for constraint checks to
say "constraint-check" rather than "fk-check" so that it can be used
for uniqueness checks in addition to foreign key checks.

Release note (sql change): The explain output for foreign key checks
is now labeled constraint-check rather than fk-check. This change
is in preparation for adding support for unique constraint checks,
which will use the same label.

**sql: update unique violation error to be Postgres compatible**

This commit fixes the violation error for unique constraints to match
the message used by Postres. Previously, the error would have been
printed as:

`duplicate key value (k)=(1) violates unique constraint "primary"`

Now this message is printed as:
```
ERROR:  duplicate key value violates unique constraint "primary"
DETAIL: Key (k)=(1) already exists.
```
Release note (sql change): The error message for unique constraint
violations now matches the error used by Postgres. For example,
the new error message looks like this:
ERROR:   duplicate key value violates unique constraint "primary"
DETAIL: Key (k)=(1) already exists.

**opt: add end-to-end support for uniqueness checks**

This commit updates the `execbuilder` to build uniqueness checks for
insert and update queries when needed. It also fixes a few other bugs
in the existing code that were preventing the checks from being built.
As of this commit, uniqueness checks for insert and update now work
end-to-end. This commit also includes a number of `execbuilder` and logic
tests for uniqueness checks.

There is no release note since these checks are still gated behind the
`experimental_enable_unique_without_index_constraints` session variable.

Informs #41535

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

Very cool!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58053#-:-MOrXWee1GCpXY6kaJbb:btgo8jj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner, @RaduBerinde, and @rytaft)

___
*[pkg/sql/logictest/testdata/logic_test/unique, line 133 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58053#-MOrX-j31GYWIT6tcph6:-MOrX-j31GYWIT6tcph7:bdsluid) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7a7be7aa6fe7d46b52a78de3ae961055d26a0e9/pkg/sql/logictest/testdata/logic_test/unique#L133)):*
> ```
> INSERT INTO uniq_overlaps_pk VALUES (3, 3, 1, 3)
> 
> query IIII colnames
> ```

rowsort (+ more instances below)
___
*[pkg/sql/opt/exec/execbuilder/mutation.go, line 784 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58053#-MOrUUkiCymxGAscvzfO:-MOrUUkiCymxGAscvzfP:b-afvc69) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7a7be7aa6fe7d46b52a78de3ae961055d26a0e9/pkg/sql/opt/exec/execbuilder/mutation.go#L784)):*
> ```Go
> }
> 
> func (b *Builder) buildUniqueChecks(checks memo.UniqueChecksExpr) error {
> ```

[nit] could use a function comment (again, reminding the reader that this only concerns "unique without index")
___
*[pkg/sql/opt/exec/execbuilder/testdata/unique, line 83 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58053#-MOrWcjz3syJrFAE9BHB:-MOrWcjz3syJrFAE9BHC:bu8tqvs) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7a7be7aa6fe7d46b52a78de3ae961055d26a0e9/pkg/sql/opt/exec/execbuilder/testdata/unique#L83)):*
> ```
> │             size: 5 columns, 2 rows
> │
> ├── • constraint-check
> ```

[nit] please file an issue to plumb some info about the constraint (kind, name) here
___
*[pkg/sql/opt/optbuilder/mutation_builder_unique.go, line 215 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58053#-MOrX8t82dMzTPm25XS8:-MOrX8t82dMzTPm25XS9:b-yupgtj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7a7be7aa6fe7d46b52a78de3ae961055d26a0e9/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L215)):*
> ```Go
> 		Table:        h.mb.tabID,
> 		CheckOrdinal: h.uniqueOrdinal,
> 		KeyCols:      withScanCols[:len(h.uniqueOrdinals)],
> ```

This needs a comment, why is it ok? (I assume `uniqueOrdinals` is always a prefix of `uniqueAndPrimaryKeyOrdinals`)

**Review by rytaft — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58053#-:-MP5APAfAXdodJEWL4x4:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[pkg/sql/logictest/testdata/logic_test/unique, line 133 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58053#-MOrX-j31GYWIT6tcph6:-MP54x-E1q4oPksZHNQo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7a7be7aa6fe7d46b52a78de3ae961055d26a0e9/pkg/sql/logictest/testdata/logic_test/unique#L133)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

rowsort (+ more instances below)
</blockquote></details>

Done.
___
*[pkg/sql/opt/exec/execbuilder/mutation.go, line 784 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58053#-MOrUUkiCymxGAscvzfO:-MP56HFzBjDgmEymExeZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7a7be7aa6fe7d46b52a78de3ae961055d26a0e9/pkg/sql/opt/exec/execbuilder/mutation.go#L784)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] could use a function comment (again, reminding the reader that this only concerns "unique without index")
</blockquote></details>

Done.
___
*[pkg/sql/opt/exec/execbuilder/testdata/unique, line 83 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58053#-MOrWcjz3syJrFAE9BHB:-MP5AGow2oyOwGhUr_wm:b-a5n31) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7a7be7aa6fe7d46b52a78de3ae961055d26a0e9/pkg/sql/opt/exec/execbuilder/testdata/unique#L83)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] please file an issue to plumb some info about the constraint (kind, name) here
</blockquote></details>

Done. #58132
___
*[pkg/sql/opt/optbuilder/mutation_builder_unique.go, line 215 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/58053#-MOrX8t82dMzTPm25XS8:-MP57auT1e_8NjP33ZA1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7a7be7aa6fe7d46b52a78de3ae961055d26a0e9/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L215)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This needs a comment, why is it ok? (I assume `uniqueOrdinals` is always a prefix of `uniqueAndPrimaryKeyOrdinals`)
</blockquote></details>

Done.

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r1, 23 of 23 files at r2, 5 of 5 files at r3, 22 of 28 files at r4, 22 of 23 files at r5, 6 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58053#-:-MP5GYOS6UW9RkXGhykP:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Review by RaduBerinde — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58053#-:-MP5QK6X2YyI9cUnG4aa:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

**Review by rytaft — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58053#-:-MP5jI9p5r7IpglWp5_H:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner)

**Pull request merged**
