### PR TITLE
distsqlrun: add missing close call to backfiller

### PR DESCRIPTION
**Pull request by dt**
Release note: none.

### CODE REVIEW

**Review by vivekmenezes — APPROVED** [review]
Seems okay, but then why have this in the first place if it's not fixing something?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36604#-:-Lbuqe2kEzY-p1q-RAfx:bona46c)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang and @vivekmenezes)

**Comment by dt** [comment]
I'm not sure I follow: it _is_ fixing something -- the missing `close()` that the interface stipulates must be called if `prepare` is called.

In this case that a) prints the on-close summary to the log and b) avoid leaking memory in the c++ SST builder on early error returns.

**Comment by vivekmenezes** [comment]
Thanks. LGTM!

**Comment by dt** [comment]
🥐
bors r+

**Pull request merged**
