### PR TITLE
*: miscellaneous typo and go vet fixes

### PR DESCRIPTION
**Pull request by jordanlewis**
Go vet doesn't get run correctly at the moment, which causes it to miss a few kinds of issues.

I ran `find pkg -type f -name "*.go" | xargs -n1 -Ixxx bash -c "echo xxx; go tool vet xxx"` to find the `go vet` issues.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13772)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1, 6 of 6 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[pkg/cli/context.go, line 234 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13772#-KdgmuoJSQeYII1LNQAA:-KdgmuoJSQeYII1LNQAB:b5uwxa0) ([raw file](https://github.com/cockroachdb/cockroach/blob/06007bf920a914f65f6fc6a44281780c445f9275/pkg/cli/context.go#L234)):*
> ```Go
> 		*k = mvccKey(engine.MakeMVCCMetadataKey(keys.MakeRangeIDPrefix(fromID)))
> 	default:
> 		return fmt.Errorf("unknown key type %d", typ)
> ```

this isn't right, `typ` should have a String() method (see the line `//go:generate stringer -type=keyType`

---

*[pkg/sql/session.go, line 353 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13772#-Kdgn22NA5nb5VeCjiSG:-Kdgn22NA5nb5VeCjiSH:b-14y41h) ([raw file](https://github.com/cockroachdb/cockroach/blob/06007bf920a914f65f6fc6a44281780c445f9275/pkg/sql/session.go#L353)):*
> ```Go
> func (ts *txnState) resetStateAndTxn(state TxnStateEnum) {
> 	if state != NoTxn && state != Aborted && state != CommitWait {
> 		panic(fmt.Sprintf("resetStateAndTxn called with unsupported state: %d", state))
> ```

this is also not right; if `state` doesn't have a stringer, we need to add it, but printing integers is no bueno

---

*[pkg/sql/session.go, line 357 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13772#-Kdgng0ORdhfpMO44Qsp:-Kdgng0Pe0KlUvdpNibO:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/06007bf920a914f65f6fc6a44281780c445f9275/pkg/sql/session.go#L357)):*
> ```Go
> 	if ts.txn != nil && !ts.txn.IsFinalized() {
> 		panic(fmt.Sprintf(
> 			"attempting to move SQL txn to state %d inconsistent with KV txn state: %s "+
> ```

ditto

---

*[pkg/sql/parser/indexed_vars.go, line 65 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13772#-KdgnAtu-ibOSpgdKkpf:-KdgnAtu-ibOSpgdKkpg:b-e0azy5) ([raw file](https://github.com/cockroachdb/cockroach/blob/06007bf920a914f65f6fc6a44281780c445f9275/pkg/sql/parser/indexed_vars.go#L65)):*
> ```Go
> 		// used a column reference in a place where it's not allowed by
> 		// the docs, so just say that instead.
> 		return nil, errors.Errorf("column reference %v not allowed in this context", v)
> ```

what will %v produce? possibly this wants %+v

---

*[pkg/sql/pgwire/types.go, line 711 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13772#-KdgnFPFaiqGrYXpDJ3t:-KdgnFPFaiqGrYXpDJ3u:b-smgqye) ([raw file](https://github.com/cockroachdb/cockroach/blob/06007bf920a914f65f6fc6a44281780c445f9275/pkg/sql/pgwire/types.go#L711)):*
> ```Go
> 		return parser.NewDName(string(b)), nil
> 	default:
> 		return nil, errors.Errorf("unsupported OID %v with format code %d", id, code)
> ```

again, i think code has a stringer (if not, please add one)

---

*[pkg/storage/replica.go, line 3127 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13772#-KdgnNLaLawJb65pUTu4:-KdgnNLaLawJb65pUTu5:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/06007bf920a914f65f6fc6a44281780c445f9275/pkg/storage/replica.go#L3127)):*
> ```Go
> func (r *Replica) refreshProposalsLocked(refreshAtDelta int, reason refreshRaftReason) {
> 	if refreshAtDelta != 0 && reason != reasonTicks {
> 		log.Fatalf(context.TODO(), "refreshAtDelta specified for reason %d != reasonTicks", reason)
> ```

ditto

---

*[pkg/storage/replica.go, line 3143 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13772#-KdgnORZUjxeiQ6uZiu5:-KdgnORZUjxeiQ6uZiu6:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/06007bf920a914f65f6fc6a44281780c445f9275/pkg/storage/replica.go#L3143)):*
> ```Go
> 				roachpb.NewAmbiguousResultError(
> 					fmt.Sprintf("unknown status for command without MaxLeaseIndex "+
> 						"at refreshProposalsLocked time (refresh reason: %d)", reason)))})
> ```

ditto

---

*[pkg/util/encoding/encoding.go, line 1287 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13772#-KdgnsGUJb4XzOMWRVE6:-KdgnsGVv_kVeO_Wn9aw:b-ujv41f) ([raw file](https://github.com/cockroachdb/cockroach/blob/06007bf920a914f65f6fc6a44281780c445f9275/pkg/util/encoding/encoding.go#L1287)):*
> ```Go
> 		return buf, false, nil
> 	default:
> 		return buf, false, fmt.Errorf("value type is not %d or %d: %d", True, False, typ)
> ```

all these changes are also incorrect, `Type` also has a stringer (or should, because `//go:generate stringer -type=Type` is present).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13772)*

**Comment by jordanlewis** [comment]
Yeah so I guess I wasn't running `go vet` correctly either. I got rid of the middle commit with the incorrect format code changes.

**Comment by tamird** [comment]
Reviewed 6 of 6 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13772)*

**Comment by tamird** [comment]
Ping?

**Pull request closed without merging**
