### PR TITLE
sqlproxy: fix flakiness and other small issues

### PR DESCRIPTION
**Pull request by andy-kimball**
- Fix flakiness of the TestDirectoryConnect test.
- Fix minor deleteEntry race condition.
- Consolidate EventType and PodState enumerations.
- Do not add DRAINING pod addresses to directory.
- Avoid locking to check tenantEntry initialization.

Fixes #67406

Release note: None

### CODE REVIEW

**Review by jaylim-crl — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67452#-:-MeDlTCA0o_vrOgPxgD_:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @chrisseto, @darinpp, and @JeffSwenson)

___
*[pkg/ccl/sqlproxyccl/tenant/directory.proto, line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67452#-MeDkJHmC0K528Us8iGb:-MeDkJHmC0K528Us8iGc:by8i2ty) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb17ee5d6d0c05fafafcd27768af24d45ea564d0/pkg/ccl/sqlproxyccl/tenant/directory.proto#L56)):*
> ```
>   Pod pod = 1;
> ```
Note that we should only bump the version of sqlproxy in the CC codebase once tenantdir has been updated to reflect these changes as well. Changing the ordering is fine since both tenantdir and sqlproxy will start up at the same time. 
___
*[pkg/ccl/sqlproxyccl/tenant/entry.go, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67452#-MeDl1aL0I2kBSa_rbrD:-MeDl1aL0I2kBSa_rbrE:bo5l0yz) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb17ee5d6d0c05fafafcd27768af24d45ea564d0/pkg/ccl/sqlproxyccl/tenant/entry.go#L82)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 	// If Initialize has already been successfully called, nothing to do.
> 	if e.initialized.Load() {
> 		return nil
> 	}
> ```
</details>


Hm, I wonder if it's cleaner to use `sync.Once` here.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67452)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @chrisseto, @darinpp, @jaylim-crl, and @JeffSwenson)

___
*[pkg/ccl/sqlproxyccl/tenant/directory.proto, line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67452#-MeDkJHmC0K528Us8iGb:-MeDmRrv1UyOk4ri1i8H:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb17ee5d6d0c05fafafcd27768af24d45ea564d0/pkg/ccl/sqlproxyccl/tenant/directory.proto#L56)):*
<details><summary><i>Previously, jaylim-crl (Jay Lim) wrote…</i></summary><blockquote>

> ```
>   Pod pod = 1;
> ```
Note that we should only bump the version of sqlproxy in the CC codebase once tenantdir has been updated to reflect these changes as well. Changing the ordering is fine since both tenantdir and sqlproxy will start up at the same time. 
</blockquote></details>

Ack.
___
*[pkg/ccl/sqlproxyccl/tenant/entry.go, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67452#-MeDl1aL0I2kBSa_rbrD:-MeDoPmWC-chRNA6Mwcq:b-yews9n) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb17ee5d6d0c05fafafcd27768af24d45ea564d0/pkg/ccl/sqlproxyccl/tenant/entry.go#L82)):*
<details><summary><i>Previously, jaylim-crl (Jay Lim) wrote…</i></summary><blockquote>

> ```
> 	// If Initialize has already been successfully called, nothing to do.
> 	if e.initialized.Load() {
> 		return nil
> 	}
> ```

Hm, I wonder if it's cleaner to use `sync.Once` here.
</blockquote></details>

Yeah, it definitely is cleaner - I was just reimplementing it here. I switched to use it.

**Review by jaylim-crl — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67452)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @chrisseto, @darinpp, and @JeffSwenson)

___
*[pkg/ccl/sqlproxyccl/tenant/entry.go, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67452#-MeDqYJn42XnYIunY_RF:-MeDqYJoBvIxqBDC77-r:b-fm3mly) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb17ee5d6d0c05fafafcd27768af24d45ea564d0/pkg/ccl/sqlproxyccl/tenant/entry.go#L112)):*
> ```Go
> func (e *tenantEntry) RefreshPods(ctx context.Context, client DirectoryClient) error {
> 	if !e.initialized.Load() {
> 		return errors.AssertionFailedf("entry for tenant %d is not initialized", e.TenantID)
> ```

Now that we've removed these assertions, what happens if we invoke RefreshPods / ChoosePodAddr whenever the entry hasn't been initialized?
___
*[pkg/ccl/sqlproxyccl/tenant/entry.go, line 80 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67452#-MeDqL1eBp9PtGYNdC7T:-MeDqL1eBp9PtGYNdC7U:bketfs1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7573b3feb4e16b1b2feae24a1e1b66c13c91bb2b/pkg/ccl/sqlproxyccl/tenant/entry.go#L80)):*
> ```Go
> 	// If Initialize has already been successfully called, nothing to do.
> 	e.initialized.Do(func() {
> 		tenantResp, err := client.GetTenant(ctx, &GetTenantRequest{TenantID: e.TenantID.ToUint64()})
> ```

Do we also need to synchronize access to to the Directory service through `e.calls` here?

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67452)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @chrisseto, @darinpp, @jaylim-crl, and @JeffSwenson)

___
*[pkg/ccl/sqlproxyccl/tenant/entry.go, line 112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67452#-MeDqYJn42XnYIunY_RF:-MeDr7enBCfI9IxYzzJh:b-e7otpb) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb17ee5d6d0c05fafafcd27768af24d45ea564d0/pkg/ccl/sqlproxyccl/tenant/entry.go#L112)):*
<details><summary><i>Previously, jaylim-crl (Jay Lim) wrote…</i></summary><blockquote>

Now that we've removed these assertions, what happens if we invoke RefreshPods / ChoosePodAddr whenever the entry hasn't been initialized?
</blockquote></details>

This was just here to catch bugs. But the bugs are quite unlikely and these have never fired. I don't think it's worth adding back an `initialized` boolean just to catch this very unlikely bug.
___
*[pkg/ccl/sqlproxyccl/tenant/entry.go, line 80 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67452#-MeDqL1eBp9PtGYNdC7T:-MeDqwys4xoSryUNY1L8:b-qplwn5) ([raw file](https://github.com/cockroachdb/cockroach/blob/7573b3feb4e16b1b2feae24a1e1b66c13c91bb2b/pkg/ccl/sqlproxyccl/tenant/entry.go#L80)):*
<details><summary><i>Previously, jaylim-crl (Jay Lim) wrote…</i></summary><blockquote>

Do we also need to synchronize access to to the Directory service through `e.calls` here?
</blockquote></details>

No, because this is always called first before anything else. Any other threads will wait on the `sync.Once` until this initial call is complete.

**Pull request merged**
