### PR TITLE
cli: compound statements that don't return rows aren't reported correctly

### LINKED ISSUE #55234: cli: compound statements that don't return rows aren't reported correctly
The following compound statement works correctly, since each statement returns rows:

```
root@:26257/defaultdb> select 1; select 2;
  ?column?
------------
         1
(1 row)

Note: timings for multiple statements on a single line are not supported. See https://go.crdb.dev/issue-v/48180/v20.2.

  ?column?
------------
         2
(1 row)

Note: timings for multiple statements on a single line are not supported. See https://go.crdb.dev/issue-v/48180/v20.2.
```

The next compound statement doesn't. I'd expect it to say `CREATE TABLE` before returning the results of the second statement, since it did in fact execute both statements:

```
root@:26257/defaultdb> create table testtable(a int); select 1;
  ?column?
------------
         1
(1 row)

Note: timings for multiple statements on a single line are not supported. See https://go.crdb.dev/issue-v/48180/v20.2.

root@:26257/defaultdb> select * from testtable;
  a
-----
(0 rows)

Time: 27ms total (execution 27ms / network 0ms)
```

Jira issue: CRDB-6301

### PR DESCRIPTION
**Pull request by adzimzf**
When running multi-query with a combination of INSERT, CREATE, or UPDATE. The `rows` from `sql.Query()` only returns the last result. It causes the query is executed but doesn't report it.

Fixes #55234.

Release note (CLI change): Fixing the report of multi-query.

### CODE REVIEW

**Comment by jordanlewis** [comment]
Interesting, thanks! You should add a test for this. I think you can add one to `pkg/cli/interactive_tests`, right @knz?

**Comment by knz** [comment]
a test in `cli_test.go` would be sufficient here

**Comment by adzimzf** [comment]
> cli_test.go

noted and thanks, I'll try to add it

**Comment by adzimzf** [comment]
Hi @jordanlewis @knz I have some update

**Review by jordanlewis — COMMENTED** [review]
Hi @adzimzf, reviewing this I see that the patch splits the statements on the client side by `;` and sends each of them to the server, one at a time. Sorry for not saying earlier, but this is not the desired behavior. The client needs to send all of the statements to the server at once: that's part of the expected behavior.

We need to figure out if the server is properly returning status for each statement, one at a time. If it is, we need to fix the code that's listening to those status messages to output them as they arrive.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55554#-:-MKFMscG1vHlg--dWQbO:b-fuigw8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

**Comment by adzimzf** [comment]
Hi, @jordanlewis,
after trying to debug, my finding is the issue is not on the server, but on the `lib/pq`, I've tried to use the Postgres server, but it still happening.
for example when I run the query 
```sql
insert into a values(1); insert into a values(1),(2);
```
it'll only return the result of the last query because the `vendor/github.com/lib/pq/conn.go:669` will override the `res` of the previous query. 
I'm not sure I'm able to fix on the `lib/pq` because I don't have the expertise in that area yet, so I think I make this PR close, and waiting for someone else will work to on the issue.

**Pull request closed without merging**
