### PR TITLE
sql: make sure pgwire bind always happens in a transaction

### LINKED ISSUE #70378: sql: prepared statements against tables with enum types not invalidated when enum changes
The following sequence of commands should work properly, but instead return an error. The issue seems to be that the prepared statement doesn't notice that the table that it's referencing has an ENUM type that got modified, causing it to refresh its referenced descriptors.

```
create type t as enum('a');
create table tab (t t);
prepare x as insert into tab values($1);
execute x('a');
alter type t add value 'b';
execute x('b');

ERROR: invalid input value for enum t: "b"
SQLSTATE: 22P02
demo@127.0.0.1:26257/defaultdb>
```

I'd expect that this should work fine, or at worst, the error should be about the prepared statement being out of date or something.

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/70378
and maybe https://github.com/cockroachdb/cockroach/issues/64140

The approach of using a transaction matches what we do for pgwire Parse
messages already. This is important to make sure that user-defined types
are leased correctly.

This also updated the SQL EXECUTE command to resolve user-defined types
so that it gets the latest changes.

Release note (bug fix): Adding new values to a user-defined enum type
will previously would cause a prepared statement using that type to not
work. This now works as expected.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71632)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @rafiss)

___
*[pkg/sql/execute.go, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71632#-MmIOVOb2bkOPl5NFeyu:-MmIOVOb2bkOPl5NFeyv:bwyjrhk) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d77e1ef39bd3e00624800935a8b2130c73545eb/pkg/sql/execute.go#L48)):*
> ```
> 		// For user-defined types, we need to resolve the type to make sure we get
> 		// the latest changes to the type.
> ```
How does this help us in the case where the type has changed between bind and now?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71632)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/execute.go, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71632#-MmIOVOb2bkOPl5NFeyu:-MmIra9R2tuvKgvIKTDC:bss896e) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d77e1ef39bd3e00624800935a8b2130c73545eb/pkg/sql/execute.go#L48)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 		// For user-defined types, we need to resolve the type to make sure we get
> 		// the latest changes to the type.
> ```
How does this help us in the case where the type has changed between bind and now? 
</blockquote></details>

the code here is for the EXECUTE sql command. binding the placeholders and executing the query is always going to be in the same implicit transaction. in other words:
- PREPARE: creates the prepared statement
- EXECUTE: binds parameters and runs the query in the same implicit txn

but if you're asking about the type changing between the pgwire Bind and the pgwire Exec (which is the code changed in conn_executor_prepare.go), this commit still helps. previously, the Bind would use whichever previous txn happened to be on the conn_executor, and now it gets its own txn. i don't see why Bind and Exec should share the same transaction. first of all, if anyone does change the type in between Bind and Exec, that seems like more of an edge case than what's being fixed here. but even so, it sounds correct to me that the type resolution during `Bind` should use the version of the type as it was at the time of the `Bind` command

but maybe i misunderstand you. if so, could you type out the sequence of pgwire commands and type changes that you're asking about?

**Comment by ajwerner** [comment]
> i don't see why Bind and Exec should share the same transaction. first of all, if anyone does change the type in between Bind and Exec, that seems like more of an edge case than what's being fixed here. 

I agree fully that they should not be using the same transaction. This change is good. I think the hazard is that if there's a change in the type (or, more likely, in the regclass) between the Bind and Exec then we'll use the old value. 

Consider the below contrived example:

```
SELECT * FROM system.namespace WHERE id = $1::regclass;
```

Now, consider the argument is a table name and that between bind and exec we rename the table. Nothing will tell us we got it wrong. I think we can paper over that, but it's interesting. For enum values, we're a bit better off because it's highly likely that the execution plan tracked the version of the enum it used and when we check `memo.IsStale` we'll notice it is and re-plan. Anyway, I think that's all #64140 and isn't intended to be fixed by this.

My question was to check my understanding. Thanks

**Comment by rafiss** [comment]
Filed https://github.com/cockroachdb/cockroach/issues/71665

**Review by otan — APPROVED** [review]

**Comment by nvanbenschoten** [comment]
@rafiss I'm not familiar with this change, but I noticed in passing while looking at a few benchmarks that it made `connExecutor.execBind` more expensive. In a read-only, CPU-bound workload, `execBind` is now responsible for **4.2%** of CPU utilization. Most of that can be attributed to the cost of creating a new short-lived transaction, which is a relatively heavy-weight operation compared to everything else in `execBind`.

Screen Shot 2021-12-30 at 6 21 17 PM

I know this was a bug fix and I unfortunately don't have any good suggestions (beyond https://github.com/cockroachdb/cockroach/pull/74350) to make this cheaper, but I figured I'd mention it here in case there were alternative fixes that didn't require a separate txn.

**Comment by rafiss** [comment]
One optimization potential here is that we only need to create/use a transaction if we end up calling `ResolveTypeByOID` -- that is, if `bindCmd.Args` is non-empty and contains user-defined types.

**Comment by rafiss** [comment]
@nvanbenschoten I made that optimization here: https://github.com/cockroachdb/cockroach/pull/74423

**Pull request merged**
