### PR TITLE
multiregionccl: unskip TestMultiRegionAfterEnterpriseDisabled

### LINKED ISSUE #61163: multiregionccl: TestMultiRegionAfterEnterpriseDisabled skipped under race
This is skipped under race due to an invalid assertion error:

```
diff --git a/pkg/sql/catalog/tabledesc/structured.go b/pkg/sql/catalog/tabledesc/structured.go
index f94c38234c..2f318ac28c 100644
--- a/pkg/sql/catalog/tabledesc/structured.go
+++ b/pkg/sql/catalog/tabledesc/structured.go
@@ -1338,7 +1338,7 @@ func (desc *wrapper) validateCrossReferences(ctx context.Context, dg catalog.Des
                }
                if err := desc.ValidateTableLocalityConfig(ctx, dg); err != nil {
-                       return errors.AssertionFailedf("invalid locality config: %v", errors.Safe(err))
+                       return err
                }
        }
 
```

and something else unrelated:

```
   testcluster.go:135: condition failed to evaluate within 45s: unexpectedly found active spans:
             0.000ms      0.000ms    === operation:job _unfinished:1 intExec:create-stats
        goroutine 84 [running]:
        runtime/debug.Stack(0xc0086b1890, 0x792e940, 0xc009ac37e0)
        	/usr/local/go/src/runtime/debug/stack.go:24 +0xab
```

### PR DESCRIPTION
**Pull request by otan**
Relevant fixes are now committed.

Resolves #61163 

Release note: None

### CODE REVIEW

**Review by ajstorm — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62116)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

**Comment by otan** [comment]
bors r=ajstorm

**Comment by otan** [comment]
hilarious, it failed!

**Comment by otan** [comment]
bors r=ajstorm

**Pull request merged**
