### PR TITLE
sql: Fix databaseCacheHolder deadlock

### LINKED ISSUE #26961: testing: TestRandomSyntaxGeneration panic: timeout
https://teamcity.cockroachdb.com/viewLog.html?buildId=739001&tab=buildResultsDiv&buildTypeId=Cockroach_Nightlies_NightlySuite

```
panic: timeout: "ALTER USER PLACEHOLDER WITH PASSWORD INDEXES". currently executing: map[CREATE DATABASE IF NOT EXISTS ident:1 GRANT ALL ON TABLE ident , COALESCE TO ALTER:1 GRANT ALL ON IFERROR TO ident:1 REVOKE ALL ON SESSION FROM DECIMAL , ROW , SESSION , ident , SUBSTRING:1 ALTER USER PLACEHOLDER WITH PASSWORD INDEXES:1 GRANT ALL ON TABLE TIMESTAMP , BLOB . ident . * , ident TO ident:1 REVOKE ALL ON DATABASE ident , SMALLINT , ident , ident , BOOLEAN FROM TEMPORARY:1 GRANT GRANT , SELECT ON OVERLAY TO CURRENT , REAL:1 REVOKE ALL ON DATABASE COALESCE FROM JSON:1 DROP USER PLACEHOLDER , PLACEHOLDER , PLACEHOLDER:1 GRANT ALL ON WORK TO ident:1 REVOKE CREATE , SELECT ON PASSWORD . * FROM SERIAL8:1 GRANT GRANT ON LIST TO DOUBLE:1 GRANT GRANT , SELECT ON TABLE BY TO ident , ident:1 ALTER USER IF EXISTS ILIKE WITH PASSWORD PLACEHOLDER:1 REVOKE ALL ON START FROM TREAT , COALESCE:1 GRANT ALL ON DATABASE ident , PRECISION , ident TO ident:1 DROP USER IF EXISTS NULLS:1 DROP DATABASE ident:1 ALTER DATABASE ident RENAME TO NUMERIC:1]
```

CC @mjibson

### LINKED ISSUE #27847: sql: deadlock in databaseCacheHolder
This deadlock prevents the server from processing any sql statements until it is restarted.  This appears to be triggered when a `DROP TABLE` command is processed, but the underlying kv transaction to update the database descriptor gets pushed due to concurrent table operations.  Every other call to `getDatabaseCache()` winds up blocked on acquiring the cache's mutex.

This appears to be the cause of #26961.

See goroutine 671:  The cache holder holds the mutex, but it's waiting for a kv transaction which has been pushed.

[dump.txt](https://github.com/cockroachdb/cockroach/files/2219471/dump.txt)

### PR DESCRIPTION
**Pull request by bobvawter**
This change releases the databaseCacheHolder mutex before calling the callback
in waitForCacheState().  In certain cases, the callback can block on other kv
transactions, leading to deadlock.

Fixes #27847
Fixes #26961

Release note: None

### CODE REVIEW

**Review by vivekmenezes — APPROVED** [review]
Great find!

**Review by andreimatei — COMMENTED** [review]
I'm sure this is a great find, but I think the code is incorrect - it can miss updates to the cache:
1. waitForCS is called
2. cond is called
3. cond returns false
4. the cache is updated
5. cv.Wait is called and never triggers; cond is never called again.

Mind spelling out what the deadlock is exactly? How does the callback passed by `TableCollection.releaseTables` end up needing to re-enter the cache's mutex? I looked at the dump in #27847 but failed to immediately answer this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27854#-:-LI7Mlub4gXXyf6vrZSk:b-yhfpv0)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec_util.go, line 417 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27854#-LI7K3yS8wpp6j436pwP:-LI7K3yS8wpp6j436pwQ:b3aw0a4) ([raw file](https://github.com/cockroachdb/cockroach/blob/fab332b10c7fedfd68b05315c7b7fbaa1a8703e4/pkg/sql/exec_util.go#L417)):*
> ```Go
> 			break
> 		}
> 		// Wait for something interesting to happen.
> ```

nit: this comment just repeats the code without adding anything. Either say when cv is signaled, or, better yet, delete the comment.

**Review by bobvawter — COMMENTED** [review]
The deadlock in the referenced issue is somewhat indirect and I might not be understanding what's actually going on.  What it looks like is that the `cond` callback (goroutine 671) winds up blocking on a pushed KV transaction when updating the list of active tables.  That pushed kv transaction is backed up behind an AdminSplit operation, which is also blocked on the mutex (goroutine 755).

More generally, we need to be able to execute the `cond` without holding the mutex, or allowing `getDatabaseCache()` to return something when there's a blocking `cond`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27854#-:-LI7Rhm5BjGUcRMiF2Ao:b-txixlv)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by andreimatei** [comment]
would making the cv's `Locker` a `RWMutex` be sufficient?

**Review by bobvawter — COMMENTED** [review]
Is `cond` intended only to be a reader?  If so, a `RWMutex` seems like it could work.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27854#-:-LI7WjBg7naodd-E7pgx:b-wivzpo)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by andreimatei** [comment]
> Is cond intended only to be a reader? If so, a RWMutex seems like it could work.

The `cond` accesses a cache, not a `databaseCacheHolder`; for our discussion it doesn't matter what it does to the cache (the only thing protected by the holder's lock is a cache pointer, not the contents of a cache).

The other thing to be said here is that the cond passed by `TableCollection.releaseTables()` should probably be a lot simpler. A comment there suggests that the callback is only concerned with the state of the cache, but the implementation, as you say, ends up going through the cache to the db. This is probably because the cache does not currently have a non-through interface (inspecting _only_ the cache). It should probably get one.
I haven't looked into what's involved with dropping a database, though, so I can't speak with too much confidence about what `releaseTables` really wants to do.

**Review by vivekmenezes — COMMENTED** [review]
I think we should continue to use getDatabaseID() because that is the function used within getTableVersion() that is used by the next command on the server. We are trying here to ensure  that when two commands run in a particular sequence, the second command sees what the first command completes. By having the post processing for the first command use the same function: getDatabaseID() we're doing this cleanly.

I think the way forward is to fix the race condition that andrei is talking about. I think that can be done by checking if the pointers have changed after holding on to the lock

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27854#-:-LI7cqms2WkDV8BcteCK:bz3ugcl)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by bobvawter — COMMENTED** [review]
PTAL: I kept the initial approach and added an explicit check to see if the cache has been updated in the meantime.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27854#-:-LI7ZIV4BAS71FILtXFM:b-a7o9qn)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by andreimatei — CHANGES_REQUESTED** [review]
The code now looks correct to me, but I'd rather do something else. The code now looks to me too much like *double-checked locking*, which is generally an anti-pattern. I'd rather leave the locking how it was and switch to an RWLock; I think it was nice that the updates were synchronized with these condition checks. But really, I still think that the true problem is the callback we're passing.

> I think we should continue to use getDatabaseID() because that is the function used within getTableVersion() that is used by the next command on the server. We are trying here to ensure  that when two commands run in a particular sequence, the second command sees what the first command completes. By having the post processing for the first command use the same function: getDatabaseID() we're doing this cleanly.

I don't think I agree. If we want to wait for the database state to change, doing that through this cache interface that's gossip-driven seems bizarre; that interface was thought strictly for inspecting the cache. Also that kind of synchronization does not belong in an obscure place like `TableCollection.releaseTables`. Synchronizing with the database is done naturally - by waiting for the drop schema change to execute successfully before we get to this code.
Synchronizing with the cache, however, seems to be harder and so we have this code.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27854#-:-LI7z8Fj-pn9x-M73To5:b35jd77)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec_util.go, line 410 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27854#-LI83IKR9P-mFCeeTJid:-LI83IKR9P-mFCeeTJie:b-olo0r6) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e19cfaab19060a9a642bcb2b76fa749222bbcf7/pkg/sql/exec_util.go#L410)):*
> ```Go
> 		// We don't want to hold dc.mu.Lock() when running the callback,
> 		// since we don't know how long it's going to take.
> 		cache := dc.getDatabaseCache()
> ```

consider pasting the `getDatabaseCache()` code here. This method now accesses dc.mu.c directly below, and the combination of direct and indirect access is hard to read.
___
*[pkg/sql/exec_util.go, line 412 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27854#-LI7x6aWEkbzVMsBFcRK:-LI7x6aWEkbzVMsBFcRL:bf9hu6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e19cfaab19060a9a642bcb2b76fa749222bbcf7/pkg/sql/exec_util.go#L412)):*
> ```Go
> 		cache := dc.getDatabaseCache()
> 		done, err := cond(cache)
> 		if err != nil {
> ```

nit: 
```
if done || err != nil {
  return err
}
```
___
*[pkg/sql/exec_util.go, line 420 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27854#-LI7xpp5723WvRgh8ILX:-LI7xpp5723WvRgh8ILY:b-wwvzss) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e19cfaab19060a9a642bcb2b76fa749222bbcf7/pkg/sql/exec_util.go#L420)):*
> ```Go
> 		// Avoid losing a race condition by explicitly checking for new cache.
> 		dc.mu.Lock()
> 		for cache == dc.mu.c {
> ```

This loop is not needed. cv is signaled every time the cache changes. Also there's no spurious wakeups in go.

**Review by vivekmenezes — COMMENTED** [review]
I actually like the code the way it is now. There are no limitations on the callback and the for loop is just running the callback on the next version of the cache.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27854#-:-LI8wC7Z6AjLwL17t7XK:b-axv5ev)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec_util.go, line 410 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27854#-LI83IKR9P-mFCeeTJid:-LI8wSVl4T0TF5sOdkKK:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e19cfaab19060a9a642bcb2b76fa749222bbcf7/pkg/sql/exec_util.go#L410)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

consider pasting the `getDatabaseCache()` code here. This method now accesses dc.mu.c directly below, and the combination of direct and indirect access is hard to read.
</blockquote></details>

+1

**Review by bobvawter — COMMENTED** [review]
PTAL: Fixed nits.

@andreimatei, if we went with an `RWLock`, what's to keep a long-running callback that holds a read-lock from blocking a cache replacement indefinitely?

Maybe as part of another PR to decide whatever policy we want to have around whether or not these callbacks ought to be long-running, we could plumb a `Context` into the callback that gets canceled if the callback is blocking a cache replacement for more than some grace period.

At least with this implementation, any specific callback is going to execute serially on some subset of all cache updates and is guaranteed to receive the latest cache.  I wouldn't expect that you'd have different callbacks registered that expect to operate in lock-step with one another.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27854#-:-LIBFMIz3y5rDLpajLR2:b-fpnvpj)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec_util.go, line 410 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27854#-LI83IKR9P-mFCeeTJid:-LIBBhh926lkpbUkxXE_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e19cfaab19060a9a642bcb2b76fa749222bbcf7/pkg/sql/exec_util.go#L410)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[pkg/sql/exec_util.go, line 412 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27854#-LI7x6aWEkbzVMsBFcRK:-LIBBYSC0L0jCWgn70r-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e19cfaab19060a9a642bcb2b76fa749222bbcf7/pkg/sql/exec_util.go#L412)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: 
```
if done || err != nil {
  return err
}
```
</blockquote></details>

Done.
___
*[pkg/sql/exec_util.go, line 420 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27854#-LI7xpp5723WvRgh8ILX:-LIBA9sK3QB8smHLeRk7:biiq35p) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e19cfaab19060a9a642bcb2b76fa749222bbcf7/pkg/sql/exec_util.go#L420)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

This loop is not needed. cv is signaled every time the cache changes. Also there's no spurious wakeups in go.
</blockquote></details>

The docs on `Wait()` mandate the use of a for-loop when testing an associated condition.  If `mu.cv` gets re-purposed in the future, the behavior of this loop won't change.

**Review by andreimatei — CHANGES_REQUESTED** [review]
LGTM

>  There are no limitations on the callback and the for loop is just running the callback on the next version of the cache.

It's not "the next version of the cache", it's "some next version". And the callback inherently has serious limitations - it only works with "monotonic" conditions - conditions that don't flap between true and false. That's why I don't think it's worth putting much thought into the current interface. To make it general and sane it'd need to become a more complex event delivery mechanism with more locking control.

> @andreimatei, if we went with an RWLock, what's to keep a long-running callback that holds a read-lock from blocking a cache replacement indefinitely?

In my opinion, it was a mistake (possibly mine) to offer this general callback mechanism from this `cacheHolder`. It's not necessary and too complicated, leading to the current conversation. The `cacheHolder` should have simply had a targeted `waitForDBToGoAway()`method. Better yet, dropping a database should have facility for putting a tombstone in the cache immediately (why wait for gossip to tell us what we already know) and preventing that tombstone from being clobbered by older info. Then the `cacheHolder` would no longer needs to offer any waiting facilities.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27854#-:-LICCvV56hv2_eiAOIUC:b42ftbv)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/exec_util.go, line 420 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27854#-LI7xpp5723WvRgh8ILX:-LIC8ALY33ZAYiZ3FuxC:b-8vsxvv) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e19cfaab19060a9a642bcb2b76fa749222bbcf7/pkg/sql/exec_util.go#L420)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

The docs on `Wait()` mandate the use of a for-loop when testing an associated condition.  If `mu.cv` gets re-purposed in the future, the behavior of this loop won't change.
</blockquote></details>

The docs don't "mandate" anything.
The documentation you're referencing refers to races on the state protected by the cond var; races that could result in the condition you're testing becoming false in between the time the cond var was signaled and the thread in question wakes up. Think a cond var being signaled when an item a writer pushes to a queue that has potentially many readers waiting to dequeue.
This does not apply here. Once the cond var is signaled, `cache` will be` != dc.mu.c` and there's no way for that to be reversed. Your loop suggests otherwise, making it confusing.
If `mu.cv` gets re-purposed, then this code will have to change, indeed.

If you like the docs on `Cond.Wait()`, though, notice that the real condition we care about in this function is not `cache != dc.mu.c`, but rather our `cond` callback. That one could be false after a signal. The code before this patch was written according to the usual pattern, which made it clear.

**Pull request closed without merging**
