### PR TITLE
sql: no more concurrent requests on RootTxns

### LINKED ISSUE #40487: kv: scan doesn't return row added in the same txn
I've been experimenting with TPCC and the new foreign key path. When I made an improvement that runs multiple FK checks in parallel, I started getting occasional violation errors. I was able to reproduce this locally and capture some traces.

Repro steps:
 - set up a local cluster using the `origin/fk-violation-repro` [branch](https://github.com/cockroachdb/cockroach/tree/fk-violation-repro); it feels like the error happens only when the server is under heavy load so I used GOMAXPROCS=4.
```
GOMAXPROCS=4 ./cockroach start --insecure --logtostderr --max-sql-memory 4GB
```

 - import TPCC fixtures with 100 warehouses
```
bin/workload fixtures import tpcc --warehouses 100
```
 - run
```
bin/workload run tpcc --warehouses=100 --duration=10m --split --wait=false --method=simple --mix=newOrder=100
```

The error is always the same:
```
Error: error in newOrder: ERROR: insert on table "order_line" violates foreign key constraint "fk_ol_w_id_ref_order" (SQLSTATE 23503)
```

This is the parent row in the `order` table which should have been inserted in the same transaction.

I set up a local zipkin and below is the span for the join reader. You can find the relevant span by looking for the `omfg` tag ("annotation query" in zipkin UI). All 9 rows reference the same `order` row (57, 2, 3029) so we scan 1 span. The KV request returns no rows (`0 loop iterations`).

image

This is the corresponding distsender span:
image

Earlier spans in the transaction confirm that we did in fact insert a row with these values.

### LINKED ISSUE #41173: sql: race between gateway refresh and reads performed by remote flows leads to write skew
I believe we fail to synchronize read refreshes performed by the gateway with the ingestion of read spans from remote flows, and so a successful refresh can bump a txn's commit timestamp without all the reads ever being checked, and so - write skew.

Namely, this is the race:
- a query is compiled to a flow on the gateway (n1) and a flow on n2
- the flows execute concurrently, performing requests at timestamp 100
- n1 sends a request and gets back a retriable error that triggers a refresh. In the case of read requests, I think only `ReadWithinUncertaintyIntervalError` applies.
- being the gateway, n1's flow uses the `RootTxn`, and so it has a `txnSpanRefresher` eager to react to the error by refreshing all the previous reads the root `TxnCoordSender` knows about
- say the refresh succeeds. The `RootTxn's` timestamp is increased to, say, 110.
- n2 executes, reads data at ts 100, and at the end it sends it `TxnMeta` back to the gateway (as part of the trailing metadata draining process).
- n1 receives this metadata, ingests n2's read spans, says thank you very much
- the txn commits at 110, but nobody ever verifies n2's reads

I've reproduced the issue in a test; the test is somewhat mocked up, but convincing enough for me that there's no unknown savior.

This started happening once gateway nodes started using the `RootTxn` (so, I believe, in 19.1). Before that all the flows used to use `LeafTxns`, which don't do refreshes.

This is the opposite of https://github.com/cockroachdb/cockroach/issues/24798, where I was complaining that we don't refresh DistSQL reads enough. In the meantime, we've started refreshing them too much :)

The `txnSpanRefresher` has protection against similar races between requests going through the `RootTxn`. It's not clear to me exactly why it has this protection given that it's unclear what concurrent Root requests are safe - given #25329. In any case, it has the [following logic](https://github.com/cockroachdb/cockroach/blob/6ffbc657dc7531806b3ea8d148f2a0114570e43f/pkg/kv/txn_interceptor_span_refresher.go#L367): it detects requests that straddled refresh attempts and, if those requests want to contribute read spans, it pessimistically yells that it's too late and the txn must restart. Similar logic this *could* be used to protect against the ingesting of read spans from leaves (done [here](https://github.com/cockroachdb/cockroach/blob/6ffbc657dc7531806b3ea8d148f2a0114570e43f/pkg/kv/txn_interceptor_span_refresher.go#L408)).

I think a better option is to disable refreshes while leaves are active. Not that the Root can know, by itself, when leaves are in scope, but DistSQL can direct it when to suspend refreshes and when to resume them.

I've discovered this while working on #24798.

### PR DESCRIPTION
**Pull request by andreimatei**
**sql: no more concurrent requests on RootTxns**

Before this patch, a DistSQL flow running on its gateway node would use
the RootTxn for all its processors for row-based flows / all of its
operators for vectorized flows. Some of these processors/operator can
execute concurrently with one another. RootTxns don't support concurrent
requests (see #25329), resulting in some reads possibly missing to see
the transaction's own writes.

This patch rectifies the situation by being discriminate about what
parts of the gateway flow use the RootTxn and what parts use LeafTxns.
LeafTxns can be used concurrently (and they can be used concurrently
with a RootTxn too). Some things need the RootTxn - mutations.
Since #40975, mutations can no longer run concurrently with other
mutations. So, we use the RootTxn for all processors/operators fused
with the DistSQLReceiver, and we use LeafTxns for all others.

Processors and operators no longer use the txn from the FlowCtx (that
field goes away). The exact details on how we determine what runs in
what transactions depend on the type of flow.

i) For row-based flows, the "head processor" and everything fused with
it will use the RootTxn. All the other processors will use the Leaf.
This is done in FlowBase.startInternal().
Processors get the txn to use through Run() and Start() (if they
implement RowSource).

ii) For vectorized flows, I went a different route. These guys don't
have Run() method (they have an Init() but that's more inconvenient to
pass a txn to). They do, however, have facilities for visiting trees of
OpNodes. So, the operators that need a txn declare that by implementing
a new KVOp interface. At flow setup time we visit all the operators and
give them the right txn - in colexec.SetTxn().

Fixes #40487

Release justification: bug fix

Release note (bug fix): Fix the possibility of confusing error messages
caused by transactions that are about to abort missing to see previous
writes performed by the same transaction.

**sql,kv: suspend refreshes while Leaf txns are in use**

Before this patch, races between ingesting leaf txn metadata into the
root and the root performing span refreshes could lead to the failure to
refresh some spans and thus write skew (see #41173).
This patches fixes that by suspending root refreshes while there are
leaves in operation - namely while DistSQL flows that use leaves (either
remotely or locally) are running. So, with this patch, while a
distributed query is running there's going to be no refreshes, but once
it finishes and all leaf metadata has been collected, refreshes are
enabled again.

Refreshes are disabled at different levels depending on the reason:
- they're disabled at the DistSQLPlanner.Run() level for distributed
queries
- they're disabled at the FlowBase level for flows that use leaves
because of concurrency between Processors
- they're disabled at the vectorizedFlow level for vectorized flows that
use leaves internal in their operators

The former two bullets build on facilities built in the previous commit
for detecting concurrency within flows.

Fixes #41173
Touches #24798

Release justification: bug fix

Release note (bug fix): Fix a bug possibly leading to write skew after distributed
queries (#41173).

### CODE REVIEW

**Comment by andreimatei** [comment]
Still have to figure out what tests I want to add here.

**Comment by andreimatei** [comment]
First commits are elsewhere

**Comment by andreimatei** [comment]
I've piled a commit that fixes the refreshing race (#41173). This commit builds on the facilities for detecting concurrency in flows added in the previous commit.

**Comment by nvanbenschoten** [comment]
About to start reviewing, but before I do I have one question: did we consider disallowing Leaf + Root to be used concurrently? I know it was an optimization to use the RootTxn in DistSQL, but I’m curious which cases that actually made a difference. Restricting the model to 1 RootTxn OR N LeadTxns running concurrently would be a nice simplification, at least until we fix the api more directly. 

The reason I ask if because I see RootTxn and LeafTxn coordinators as somewhat analagous to the Txn and TxnHandle constructs we've been dreaming of. In that world, we might want to allow a Txn to be used directly as an optimization, but certainly wouldn't allow the Txn to be used while it has outstanding TxnHandles that haven't been closed. Are we closer to the model from https://github.com/cockroachdb/cockroach/issues/25329 than we realize?

cc. @jordanlewis

**Comment by jordanlewis** [comment]
We could restrict to `root` or `leaf`-only flows without too much trouble. Mutations are the only things that need `root` txns, and they can't be distributed. So the only potential leaf-txn-needing operation in such a flow is a union, and we could add some special casing to remove that concurrency.

Distsql flows could get leaf-only txns but the main reason we stopped doing that was for performance reasons. It's very expensive to make a new txn, so we'd like to avoid it when possible.

**Review by andreimatei — COMMENTED** [review]
There are compelling reasons for mixing root and leaves:
1) Because I want the concurrency, damn it. In fact, I want more concurrency than we currently have. And I don't want all the concurrency to go away just because I have a mutation.
2) Like 1), I don't want to be forced to plan queries with mutations entirely on the gateway. I'm not even sure why we do that currently; I suspect it's because we didn't take the time to ensure that the mutations are planned on the gw without everything else also being planned on the gw.
3) for the fixing the Halloween problem (#28842), what we'll probably end up with is reads using some sort of a transaction handle bound to a sequence number while writes use a different handle (i.e. a leaf and a root).

However, Ill give a try to making unions (i.e. input synchronizers) work sequentially and then use the root txn when there's no remote flows (which also would now imply that there's no concurrency) and use a leaf otherwise. If that code looks good, then I'll do that and keep the current PR for 20.1, perhaps predicated on a better/more thought out txn interface.
Watch this space.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41102#-:-Lq7RUgIEDeKg_5k6TRP:bsrssba)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @nvanbenschoten)

**Comment by andreimatei** [comment]
Sent out #41307 which implements the alternative discussed above.

**Pull request closed without merging**
