### PR TITLE
storage: configuration for writing sstables with value blocks

### PR DESCRIPTION
**Pull request by sumeerbhola**
Cluster version V23_1EnablePebbleFormatSSTableValueBlocks gates writing of value blocks. Additionally, storage.value_blocks.enabled needs to be set to true (default is false).

The lock table key space is excluded from value blocks. The tombstone bit is extracted as a ShortAttribute, to avoid fetching the value to determine whether it is a tombstone.

Informs cockroachdb/pebble#1170

Epic: CRDB-20378

Release note(ops change): The cluster setting storage.value_blocks.enabled, when set to true, writes the values of older versions of the same key to separate value blocks in the same sstable. For workloads that create many versions, this can improve the performance of reads by increasing locality. It can also help scan performance with single versions due to an optimization that avoids a key comparison (useful if the key are not very short). The default value of this setting is currently false.

### CODE REVIEW

**Review by jbowens — APPROVED** [review]
:lgtm:

> Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94634#-:-NL1i_Ip-T2Ad4t3YXuo:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal and @sumeerbhola)

___
*[`pkg/storage/pebble.go` line 886 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94634#-NL1hAbE9aPP_Kl8M-3U:-NL1hAbFCSkcPBAXU1iM:b-m6m8ho) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c2853e680ec8cdb775cf5cb7bbcd45bbe96de56/pkg/storage/pebble.go#L886)):*
> ```Go
> 		}
> 		cfg.Opts.Experimental.EnableValueBlocks = func() bool {
> 			version := settings.Version.ActiveVersionOrEmpty(context.Background())
> ```

should this use the `ctx` passed in through `NewPebble`? 
___
*[`pkg/storage/pebble_iterator.go` line 572 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94634#-NL1hr8q-zmOHaux-PO-:-NL1hr8q-zmOHaux-PO0:bhtvjc1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c2853e680ec8cdb775cf5cb7bbcd45bbe96de56/pkg/storage/pebble_iterator.go#L572)):*
> ```Go
> 		}
> 	}
> 	return lv.Len(), isTombstone, nil
> ```

nit: `lv.Len()` needs to check `if lv.Fetcher == nil`. worth setting a `len` local variable in the if, so that the else can directly use `len(val)`?

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94634#-:-NL1ofTv8WOoOO0wUd2K:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal and @jbowens)

___
*[`pkg/storage/pebble.go` line 886 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94634#-NL1hAbE9aPP_Kl8M-3U:-NL1pv3aAVQDD1dKBUnV:bxbuxez) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c2853e680ec8cdb775cf5cb7bbcd45bbe96de56/pkg/storage/pebble.go#L886)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

should this use the `ctx` passed in through `NewPebble`? 
</blockquote></details>

This is going to be called in the future, for every compaction/flush, and we don't want a current context that can be cancelled by then. I noticed now that we create a `logCtx` below for exactly this purpose, so I've switched the code to use it.
___
*[`pkg/storage/pebble_iterator.go` line 572 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94634#-NL1hr8q-zmOHaux-PO-:-NL1rTnv7E93dp8pCetd:b-ilp05j) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c2853e680ec8cdb775cf5cb7bbcd45bbe96de56/pkg/storage/pebble_iterator.go#L572)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

nit: `lv.Len()` needs to check `if lv.Fetcher == nil`. worth setting a `len` local variable in the if, so that the else can directly use `len(val)`? 
</blockquote></details>

I don't want to peer into the implementation of `LazyValue` too much, so I've changed this to use a local variable, and the if-block calls the inlined `lv.Len()`, and the else-block calls `len(val)`.

**Review by nicktrav — APPROVED** [review]
:lgtm:

> Reviewed 5 of 6 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94634#-:-NL1uaqt5PBHORtmBL3R:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94634#-NKt5QDIEm8fJsuuj4Kt):*
> ... gates writing ...

I think I know the answer to this already, but wanted to confirm my understanding: I assume the _reading_ of value blocks can happen at any point and we don't need a version gate for it? We're just adding the gate for writes.

Thinking of the situation where, during the upgrade to _this_ version (i.e. the one that enables value blocks), one node writes a table with value blocks present that is then sent to a node that hasn't yet finished upgrading? I assume that node could _read_ the new table, as it would be running with a binary version new enough to understand the new format.

Or is there the potential for a race which would necessitate doing the double version gate dance similar to what we needed for enabling range keys?

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94634)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal, @jbowens, and @nicktrav)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94634#-NKt5QDIEm8fJsuuj4Kt):*
> I think I know the answer to this already, but wanted to confirm my understanding: I assume the reading of value blocks can happen at any point and we don't need a version gate for it? We're just adding the gate for writes.

Correct. Once all nodes in the cluster are at the new version and that version if finalized, we are guaranteed that everyone can read value blocks now and in the future.

Hmm, I started looking at `V22_2EnsurePebbleFormatVersionRangeKeys` and `V22_2EnablePebbleFormatVersionRangeKeys` and I was initially confused on why this was needed. And then I realized that it is because Pebble format version has to be bumped before it understands a new sstable format -- it is not an implicit behavior based on what the code understands. As far as I can tell, the only enforcement is for ingestion, where `MaxTableFormat` is enforced, and we don't actually care when reading for flushes or compactions (as long as the code exists for the format). So we will need two cockroach versions for this change too. Does that match your understanding?

**Review by nicktrav — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94634)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94634#-NKt5QDIEm8fJsuuj4Kt):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> I think I know the answer to this already, but wanted to confirm my understanding: I assume the reading of value blocks can happen at any point and we don't need a version gate for it? We're just adding the gate for writes.

Correct. Once all nodes in the cluster are at the new version and that version if finalized, we are guaranteed that everyone can read value blocks now and in the future.

Hmm, I started looking at `V22_2EnsurePebbleFormatVersionRangeKeys` and `V22_2EnablePebbleFormatVersionRangeKeys` and I was initially confused on why this was needed. And then I realized that it is because Pebble format version has to be bumped before it understands a new sstable format -- it is not an implicit behavior based on what the code understands. As far as I can tell, the only enforcement is for ingestion, where `MaxTableFormat` is enforced, and we don't actually care when reading for flushes or compactions (as long as the code exists for the format). So we will need two cockroach versions for this change too. Does that match your understanding?

</blockquote></details>

It's been a while since we added those two versions, so my memory is a bit murky, but we did a lot of back and forth on it at the time - here's the conversation that I could find, that may help (#76085). Here what's in my memory right now:

I believe the salient parts of the range key upgrade that we wanted to guard against were for ingestions of tables sent from other nodes, as you mention. With a single Cockroach cluster version, a node could ratchet its store format major version (FMV) up to enable range keys and then an SSTable could be written with range keys, and sent to a node that had not yet ratcheted its store FMV (or was in the process of ratcheting). The ingest would fail, as that store doesn't yet know about range keys (the binary does, but the application doesn't). The two-version scheme allowed for a synchronization barrier whereby if a node is at version was N (="Pebble store version ratcheted to range keys"), then the upgrade framework guarantees that no other node could be at cluster version N+1 (="Make use of range key features in Cockroach") _until all nodes had reached version N_.

Looking at the current Pebble code, it looks like while we have the new FMV for value blocks, nothing is using it yet (looks like there's a [warning in the code about this](https://github.com/cockroachdb/pebble/blob/bec1aa20c1fd24ffea9323f54b0f4a1087a2c313/format_major_version.go#L125-L131)). I could see a case where a single Cockroach cluster version would be fine if the binary could unconditionally read value blocks (i.e. irrespective of the store FMV). However, I assume the intention is to do some gating on that new FMV in Pebble?

It's possible that the original analysis / reasoning was incorrect and we over-complicated things, so I'd certainly welcome a fresh set of eyes on this.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94634)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal, @jbowens, and @nicktrav)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94634#-NKt5QDIEm8fJsuuj4Kt):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

It's been a while since we added those two versions, so my memory is a bit murky, but we did a lot of back and forth on it at the time - here's the conversation that I could find, that may help (#76085). Here what's in my memory right now:

I believe the salient parts of the range key upgrade that we wanted to guard against were for ingestions of tables sent from other nodes, as you mention. With a single Cockroach cluster version, a node could ratchet its store format major version (FMV) up to enable range keys and then an SSTable could be written with range keys, and sent to a node that had not yet ratcheted its store FMV (or was in the process of ratcheting). The ingest would fail, as that store doesn't yet know about range keys (the binary does, but the application doesn't). The two-version scheme allowed for a synchronization barrier whereby if a node is at version was N (="Pebble store version ratcheted to range keys"), then the upgrade framework guarantees that no other node could be at cluster version N+1 (="Make use of range key features in Cockroach") _until all nodes had reached version N_.

Looking at the current Pebble code, it looks like while we have the new FMV for value blocks, nothing is using it yet (looks like there's a [warning in the code about this](https://github.com/cockroachdb/pebble/blob/bec1aa20c1fd24ffea9323f54b0f4a1087a2c313/format_major_version.go#L125-L131)). I could see a case where a single Cockroach cluster version would be fine if the binary could unconditionally read value blocks (i.e. irrespective of the store FMV). However, I assume the intention is to do some gating on that new FMV in Pebble?

It's possible that the original analysis / reasoning was incorrect and we over-complicated things, so I'd certainly welcome a fresh set of eyes on this.
</blockquote></details>

Yes, I think we are in agreement. Pebble will need this 2 step thing whenever handling something new requires bumping the Pebble format major version. Thanks to both of you for bringing this up.
I've made the necessary change.

**Review by nicktrav — APPROVED** [review]
Follow up lgtm.

> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94634#-:-NL6grJI4Ra8I7SH0-tb:bhny0sf)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @itsbilal and @jbowens)

**Comment by sumeerbhola** [comment]
TFTRs!

**Comment by sumeerbhola** [comment]
bors r=jbowens,nicktrav

**Comment by sumeerbhola** [comment]
bors r=jbowens,nicktrav

**Pull request merged**
