### PR TITLE
engine: actually unlock temp dirs on Windows

### LINKED ISSUE #24144: server: can't restart node on windows
**Description**
Can't restart a node on windows, even if cockroach is run as "Administrator".

I try to delete .LOCK file but cluster don't run anymore. I have to delete data folder to get cockroach working again.

**Version**
```
Build Tag:    v2.0-beta.20180319
Build Time:   2018/03/19 19:04:00
Distribution: CCL
Platform:     windows amd64
Go Version:   go1.10
C Compiler:   gcc 6.3.0
Build SHA-1:  e0b123c2324586c2bd101e27bab468701f8efa5e
Build Type:   release
```

**Console (first start)**
```
PS D:\cockroach> .\cockroach.exe start --insecure
*
* WARNING: RUNNING IN INSECURE MODE!
*
* - Your cluster is open for any client that can access <all your IP addresses>.
* - Any user, even root, can log in without providing a password.
* - Any user, connecting as root, can read or write any data in your cluster.
* - There is no network encryption nor authentication, and thus no confidentiality.
*
* Check out how to secure your cluster: https://www.cockroachlabs.com/docs/v2.0/secure-a-cluster.html
*
CockroachDB node starting at 2018-03-22 06:52:26.0482344 +0000 UTC (took 6.4s)
build:               CCL v2.0-beta.20180319 @ 2018/03/19 19:04:00 (go1.10)
admin:               http://DEMON-CORE:8080
sql:                 postgresql://root@DEMON-CORE:26257?application_name=cockroach&sslmode=disable
logs:                D:\cockroach\cockroach-data\logs
temp dir:            D:\cockroach\cockroach-data\cockroach-temp236256839
external I/O path:   D:\cockroach\cockroach-data\extern
store[0]:            path=D:\cockroach\cockroach-data
status:              initialized new cluster
clusterID:           11421e61-616b-4ed9-ae06-2b6d196c2bd5
nodeID:              1
Note: a second interrupt will skip graceful shutdown and terminate forcefully
initiating graceful shutdown of server
server drained and shutdown completed
*
* INFO: interrupted
*
Failed running "start"
```

**Console (second start)**
```
PS D:\cockroach> .\cockroach.exe start --insecure
*
* WARNING: RUNNING IN INSECURE MODE!
*
* - Your cluster is open for any client that can access <all your IP addresses>.
* - Any user, even root, can log in without providing a password.
* - Any user, connecting as root, can read or write any data in your cluster.
* - There is no network encryption nor authentication, and thus no confidentiality.
*
* Check out how to secure your cluster: https://www.cockroachlabs.com/docs/v2.0/secure-a-cluster.html
*
*
* ERROR: could not cleanup temporary directories from record file: remove D:\cockroach\cockroach-data\cockroach-temp236256839\TEMP_DIR.LOCK: Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus.
*
Failed running "start"
```

### LINKED ISSUE #25272: could not cleanup temporary directories from record file: remove /cockroach/cockroach-data/cockroach-temp713118389
# Description

For some reason nodes that die do not start again due to the failure you can see in the log. The strange thing is, this happens everytime a node stops due to whatever reasons. Unlike cockroach tells, the directory *-tempXYZ is emtpy. As soon as these are removed cockroach boots again. Seems to be a bug and a critical one since this stops the cluster from working without manual intervention.

# Log

```
++ hostname -f
+ exec /cockroach/cockroach start --logtostderr --certs-dir /cockroach/cockroach-certs --host cockroachdb-1.cockroachdb.default.svc.cluster.local --http-host 0.0.0.0 --join cockroachdb-0.cockroachdb,cockroachdb-1.cockroachdb,cockroachdb-2.cockroachdb --cache 25% --max-sql-memory 25%
I180503 11:59:36.331427 1 cli/start.go:918  CockroachDB CCL v2.0.1 (x86_64-unknown-linux-gnu, built 2018/04/23 18:39:21, go1.10)
E180503 11:59:36.590797 1 cli/error.go:109  could not cleanup temporary directories from record file: remove /cockroach/cockroach-data/cockroach-temp713118389: directory not empty
Error: could not cleanup temporary directories from record file: remove /cockroach/cockroach-data/cockroach-temp713118389: directory not empty
Failed running "start"
```

### PR DESCRIPTION
**Pull request by benesch**
File locks are mandatory on Windows; our cleanup code was previously
assuming file system locks were advisory. Specifically, our cleanup code
was locking the temporary directory, then attempting to remove it before
releasing the lock. This worked on Unix platforms where locks are
advisory-only, but failed on Windows because the process's own lock
would prevent the cleanup! Presumably this ordering was meant to avoid a
race condition where the directory was unlocked before it was cleaned
up. It turns out this race condition doesn't matter (see the comment
within), so just unlock the directory before removing it, which works on
both Unix and Windows.

Release note (bug fix): Restarting a CockroachDB server on Windows no
longer fails due to file system locks in the store directory.

Fix #24144.
Fix #25272.

### CODE REVIEW

**Comment by knz** [comment]
The code change looks good to me. I'll let bram also verify that it indeed solves the problem on windows.

**Comment by bdarnell** [comment]
What if the process shuts down uncleanly? Won't the file be left around and then the next run will fail? 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25267#-:-LBc6Epd6vz556LAN3St:b-qrigo)*

**Comment by benesch** [comment]
Yep. At least it’s strictly better than what we have now. (And even if our
temp did doesn’t use locks, RocksDB is still going to leave its data
directory lock around.)

**Comment by bdarnell** [comment]
Yeah, that's my question. If a (non-cockroach, or pre-temp-dir version of cockroach) process uses rocksdb crashes uncleanly, do they have the same problem? How do you recover?

**Comment by benesch** [comment]
Turns out I completely misdiagnosed the problem. We weren't stumbling over lingering locks from the last process... we were tripping over a lock installed by our own process! See the commit message and code comment for details.

**Comment by knz** [comment]
> our cleanup code was previously file system locks were advisory

this sentence a word

**Comment by benesch** [comment]
Thanks. Fixed.

**Comment by BramGruneir** [comment]
Can you point me toa windows binary to test?

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25267#-:-LBgKfdx2Om7RGhTRB7R:bnfp4nl)*

**Comment by benesch** [comment]
Yup, here you go @BramGruneir:
https://www.dropbox.com/s/x5sx4to06hwrzw1/cockroach-unlock-windows.zip?dl=0

**Comment by BramGruneir** [comment]
Wonderful!

* cockroach quit - clean startup
* cockroach ^c - clean startup
* cockroach ^c^c - clean startup
* kill task - clean startup

WGFM (works good for me)  I guess that should be WWFM (works well for me), but that's not as much fun.

**Review by BramGruneir — APPROVED** [review]

**Comment by BramGruneir** [comment]
I killed the process using the task manager.  That's as close to kill as I
know for windows.

**Comment by benesch** [comment]
bors r=knz,bdarnell,Bram-Gruneir

**Comment by tschottdorf** [comment]
pip threw up while downloading flask (SysCallError: (104, 'ECONNRESET'))

bors r=knz,bdarnell,Bram-Gruneir

**Pull request merged**
