### PR TITLE
sql/logictest: fix flakes in select_for_update_read_committed

### LINKED ISSUE #112677: pkg/sql/logictest/tests/local/local_test: TestLogic_select_for_update_read_committed failed
pkg/sql/logictest/tests/local/local_test.TestLogic_select_for_update_read_committed [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_SqlLogicTestHighVModuleNightlyBazel/12247724?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_SqlLogicTestHighVModuleNightlyBazel/12247724?buildTab=artifacts#/) on release-23.2 @ [3744e5655559d3350aedaf1fbbaecbf1e69c98d6](https://github.com/cockroachdb/cockroach/commits/3744e5655559d3350aedaf1fbbaecbf1e69c98d6):

```
[07:42:51] CREATE TABLE bcd (b INT PRIMARY KEY, c INT, d INT, INDEX (c), FAMILY (b, c, d));
[07:42:51] INSERT INTO bcd VALUES (20, 200, 2000), (30, 300, 3000), (40, 400, 4000);
[07:42:51] GRANT ALL on abc TO testuser;
[07:42:51] GRANT ALL on bcd TO testuser;
[07:42:51] BEGIN;
[07:42:51] SELECT * FROM abc WHERE a != 3 FOR UPDATE;
[07:42:51] 	-- OK;
[07:42:51] SELECT * FROM bcd ORDER BY c DESC LIMIT 2 FOR SHARE;
[07:42:51] 	-- OK;
[07:42:51] SELECT * FROM abc;
[07:42:51] 	-- OK;
[07:42:51] SELECT * FROM bcd;
[07:42:51] 	-- OK;
[07:42:51] SELECT * FROM abc FOR UPDATE SKIP LOCKED;
[07:42:51] 	-- OK;
[07:42:51] SELECT * FROM bcd FOR UPDATE SKIP LOCKED;
[07:42:51] 	-- OK;
[07:42:51] SELECT * FROM abc FOR SHARE;
[07:42:51] SELECT * FROM bcd FOR SHARE;
[07:42:52] 	-- OK;
[07:42:52] SELECT * FROM abc FOR UPDATE;
[07:42:52] SELECT * FROM bcd FOR UPDATE;
[07:42:52] SELECT a FROM abc WHERE a = 2 FOR UPDATE;
[07:42:52] SELECT b FROM abc WHERE a = 2 FOR UPDATE;
[07:42:52] SELECT c FROM abc WHERE a = 2 FOR UPDATE;
[07:42:52] SELECT c FROM abc ORDER BY a DESC LIMIT 2 FOR UPDATE;
[07:42:52] SELECT a + b + c FROM abc FOR UPDATE;
[07:42:52] SELECT * FROM abc JOIN bcd USING (b) FOR SHARE;
[07:42:52] SELECT * FROM abc JOIN bcd USING (c) FOR UPDATE;
[07:42:52] UPDATE abc SET b = b + 1, c = c + 1 WHERE a != 3;
[07:42:52] COMMIT;
[07:42:52] 	-- OK;
[07:42:52] 	-- OK;
[07:42:52] 	-- OK;
[07:42:52] 	-- OK;
[07:42:52] 	-- OK;
[07:42:52] 	-- OK;
[07:42:52] 	-- OK;
[07:42:52] 	-- OK;
[07:42:52] 	-- FAIL
    logic.go:2606: 
         to prevent flakes in queries that return multiple rows, add the rowsort option, the valuesort option, the partialsort option, or an ORDER BY clause. If you are certain that your test will not flake due to a non-deterministic ordering of rows, you can add the nosort option to ignore this error
[07:42:52] --- done: /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/4185/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/local/local_test_/local_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/select_for_update_read_committed with config local: 37 tests, 1 failures

    logic.go:3998: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/4185/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/local/local_test_/local_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/select_for_update_read_committed:181: error while processing
    logic.go:3998: /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/4185/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/local/local_test_/local_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/select_for_update_read_committed:181: too many errors encountered, skipping the rest of the input
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/9842ae56c415bac8da2062d2590d733b/logTestLogic_select_for_update_read_committed1621277230
--- FAIL: TestLogic_select_for_update_read_committed (8.38s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestLogic_select_for_update_read_committed.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-32549

### PR DESCRIPTION
**Pull request by mgartner**
The `select_for_update_read_committed` tests were flaking because not
all statements were being run under READ COMMITTED isolation. The logic
test infrastructure does not allow fine-grained control of sessions, and
setting the isolation level in one statement would only apply to a
single session. Subsequent statements are not guaranteed to run in the
same session because they could run in any session in the connection
pool. This commit wraps each statement in an explicitly transaction with
an explicit isolation level to ensure READ COMMITTED is used.

In the future, we should investigate allowing fine-grained and explicit
control of sessions in logic tests.

Fixes #112677

Release note: None

### CODE REVIEW

**Review by michae2 — APPROVED** [review]
:lgtm: Thank you!!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112701#-:-Nh7x7sc3fjee97V5Iht:bwy8rtm)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Review by michae2 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112701)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/logictest/testdata/logic_test/select_for_update_read_committed` line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112701#-Nh7xYNo9u2y5-9rV5l2:-Nh7xYNo9u2y5-9rV5l3:bt57lw8) ([raw file](https://github.com/cockroachdb/cockroach/blob/781841dbbccd9192085527971c54c9f3e7ca787f/pkg/sql/logictest/testdata/logic_test/select_for_update_read_committed#L81)):*
> ```
> COMMIT;
> ----
> 20  200  2000
> ```

I think what's happening here is that SKIP LOCKED doesn't quite work with shared locks yet: https://github.com/cockroachdb/cockroach/issues/110743

Maybe we could bring the (incorrect) 3-row result back, with a note about that issue?

**Comment by mgartner** [comment]
*[`pkg/sql/logictest/testdata/logic_test/select_for_update_read_committed` line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112701#-Nh7xYNo9u2y5-9rV5l2:-Nh8-mv_6WXfTpPV4ZWH:b-i823vl) ([raw file](https://github.com/cockroachdb/cockroach/blob/781841dbbccd9192085527971c54c9f3e7ca787f/pkg/sql/logictest/testdata/logic_test/select_for_update_read_committed#L81)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

I think what's happening here is that SKIP LOCKED doesn't quite work with shared locks yet: https://github.com/cockroachdb/cockroach/issues/110743

Maybe we could bring the (incorrect) 3-row result back, with a note about that issue?
</blockquote></details>

I can't get this failure to reproduce locally, and if I add the three rows back the tests fails locally.

**Comment by mgartner** [comment]
*[`pkg/sql/logictest/testdata/logic_test/select_for_update_read_committed` line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112701#-Nh7xYNo9u2y5-9rV5l2:-Nh8139q0lx6xG--i5O1:bgq6eq) ([raw file](https://github.com/cockroachdb/cockroach/blob/781841dbbccd9192085527971c54c9f3e7ca787f/pkg/sql/logictest/testdata/logic_test/select_for_update_read_committed#L81)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I can't get this failure to reproduce locally, and if I add the three rows back the tests fails locally.
</blockquote></details>

Nevermind, I think I found the problem—I forgot to include the change to set the txn isolation of the first BEGIN.

**Comment by mgartner** [comment]
TFTR!

bors r+

**Pull request merged**
