### PR TITLE
Move `make check` to a shell script; refactor to add XML reports

### PR DESCRIPTION
**Pull request by bdarnell**
This will cause circleci to display `make check` failures more prominently, like the rest of our tests. It should also make complex checks like the "forbidden imports" one easier to work with than embedding them in a makefile, although I haven't actually refactored anything away from one giant statement. 

This branch includes a deliberate error for testing that will be reverted before merging.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6335)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[main.go, line 28 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6335#-KGJNxaq-WuJE_M4S1s2:-KGJNxaq-WuJE_M4S1s3:-1139759415) ([raw file](https://github.com/cockroachdb/cockroach/blob/7359d8cc5538c0b34b334d2b25358a5415c76c8f/main.go#L28)):*
What's this about?

---

*[build/check-style.sh, line 88 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6335#-KGJNcML4-uSfe32EZVi:-KGJNcML4-uSfe32EZVj:686499132) ([raw file](https://github.com/cockroachdb/cockroach/blob/7359d8cc5538c0b34b334d2b25358a5415c76c8f/build/check-style.sh#L88)):*
Lack of indentation here.

---

*[build/check-style.sh, line 144 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6335#-KGJNh42CDB1m1nfYASc:-KGJNh42CDB1m1nfYASd:-1987122306) ([raw file](https://github.com/cockroachdb/cockroach/blob/7359d8cc5538c0b34b334d2b25358a5415c76c8f/build/check-style.sh#L144)):*
Yowza!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6335#-:-KGJNyfw91xWE0lTJyqc:1417088721)*

**Comment by bdarnell** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[build/check-style.sh, line 144 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6335#-KGJNh42CDB1m1nfYASc:-KGJQEnIy2xlmWf11B0D:1699140724) ([raw file](https://github.com/cockroachdb/cockroach/blob/7359d8cc5538c0b34b334d2b25358a5415c76c8f/build/check-style.sh#L144)):*
Comment added.

---

*[main.go, line 28 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6335#-KGJNxaq-WuJE_M4S1s2:-KGJQ3NtvDIami5je7Rp:1034581231) ([raw file](https://github.com/cockroachdb/cockroach/blob/7359d8cc5538c0b34b334d2b25358a5415c76c8f/main.go#L28)):*
To generate this error for testing: https://circleci.com/gh/cockroachdb/cockroach/16935

Removed in the latest commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6335)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r1, 3 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[build/check-style.sh, line 3 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6335#-KGNhx9FzpEplZI4pxbk:-KGNhx9G-QMrJsDxflZu:467740814) ([raw file](https://github.com/cockroachdb/cockroach/blob/5532e246a082a2ff112f8018663e35facad53c16/build/check-style.sh#L3)):*
pipefail?

---

*[build/check-style.sh, line 88 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6335#-KGJNcML4-uSfe32EZVi:-KGNiUhbGOLd0Q32lwGy:-1142993917) ([raw file](https://github.com/cockroachdb/cockroach/blob/7359d8cc5538c0b34b334d2b25358a5415c76c8f/build/check-style.sh#L88)):*
Looks like this was fixed in the wrong commit? just sayin'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6335)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[build/check-style.sh, line 3 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6335#-KGNhx9FzpEplZI4pxbk:-KGNjahozKQpoKF_vgk4:734920691) ([raw file](https://github.com/cockroachdb/cockroach/blob/5532e246a082a2ff112f8018663e35facad53c16/build/check-style.sh#L3)):*
We currently rely on non-pipefail behavior in many of the checks.

---

*[build/check-style.sh, line 88 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6335#-KGJNcML4-uSfe32EZVi:-KGNjg67JtLFeLyCqyVV:778434265) ([raw file](https://github.com/cockroachdb/cockroach/blob/7359d8cc5538c0b34b334d2b25358a5415c76c8f/build/check-style.sh#L88)):*
How so? It was fixed in the commit that moved things into functions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6335)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[build/check-style.sh, line 3 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6335#-KGNhx9FzpEplZI4pxbk:-KGNjycrQY6hafSQt-5V:138565615) ([raw file](https://github.com/cockroachdb/cockroach/blob/5532e246a082a2ff112f8018663e35facad53c16/build/check-style.sh#L3)):*
cool. can you add a comment?

---

*[build/check-style.sh, line 88 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6335#-KGJNcML4-uSfe32EZVi:-KGNk-W2k5HdEaq99_zT:85760869) ([raw file](https://github.com/cockroachdb/cockroach/blob/7359d8cc5538c0b34b334d2b25358a5415c76c8f/build/check-style.sh#L88)):*
Ah, perhaps I'm looking at it wrong? Nevertheless, the indentation in this file is inconsistent at r1

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6335)*

**Pull request merged**
