### PR TITLE
gc: use delete range to remove large number of consecutive keys

### PR DESCRIPTION
**Pull request by aliher1911**
This commit adds range_deletion_keys parameters to GC request.
range_deletion_keys is used by GC queue to remove chunks of
consecutive keys where no new data was written above the GC
threshold and storage can optimize deletions with range
tombstones.
To support new types of keys, GCer interface is also updated
to pass provided keys down to request.

When deleting large chunks of keys usually produced by range tombstones
GC will use point deletion for all versions found within replica key
range.
That kind of operations would generate unnecessary load on the storage
because each individual version must be deleted independently.
This patch adds an ability for GC to find ranges of consecutive keys
which are not interleaved with any newer data and create
delete_range_key GC requests to remove them.

Release note: None

### CODE REVIEW

**Comment by ajwerner** [comment]
Have you seen https://github.com/cockroachdb/cockroach/pull/51230?

**Comment by ajwerner** [comment]
Might I suggest you leverage the word `Clear` when referring to the operations which actually remove data from pebble? We have some nomenclature confusion around the code-base where `Delete` and `DeleteRange` in the KV layer means write tombstones and `Clear` means remove the data. I do understand that in pebble that does mean that a KV `Del` is a pebble `Put` and a KV `Clear` is a pebble `Delete`. Still, best when writing code in the kvserver layer to buy into the nomenclature of `kvserver` and `storage` packages.

**Comment by aliher1911** [comment]
I knew there was an effort, but didn't see the PR before. I think we now have a bigger ask in terms of removing multiple keys with a single op, not only multiple versions. Without that removing everything under range key would be pretty wasteful exercise.
I like how giving variables better names made this code more readable!

**Comment by ajwerner** [comment]
>I think we now have a bigger ask in terms of removing multiple keys with a single op, not only multiple versions. Without that removing everything under range key would be pretty wasteful exercise.

That makes sense. I think we'll have to think about how this interacts with latching. I know that there's ongoing work to make GC hold fewer latches. I think you'll need to have to hold latches to use the approach you're talking about.

One thing I've been thinking about lately in a different context is a new pebble compaction filter which is able to clear keys in a span which match some suffix filter, an MVCCClearRange operation, if you will. If we had such a thing that we could issue to the storage engine then we could avoid the latching.

Given we've latched for all of these years, it's probably okay to latch just when we have a ton of garbage to remove, at least in the first pass.

**Comment by aliher1911** [comment]
Actually I think the idea to tackle those two concerns together (use clean for multiple versions and clean for multiple keys) should be handled separately. Because of latches specifically. There's already a pending change for that I believe.

For multiple versions we can still use latchless, and for multiple keys we don't care about latchless as we don't expect any writes happening.

**Pull request closed without merging**
