### PR TITLE
server: create new endpoint that return the roles of the sql user

### PR DESCRIPTION
**Pull request by maryliag**
The commit creates a new endpoint `/sqlroles` that returns
a list of roles of the SQL user logged in.

Partially addresses #74817

Release note (api change): Creation of new endpoint `/sqlroles` that
returns a list of the SQL roles for the SQL user logged in.

### CODE REVIEW

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74920)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @maryliag)

___
*[pkg/server/serverpb/admin.proto, line 295 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74920#-MtiRukYElIb3gUtdPCF:-MtiRukZEd_mLgvemsZu:b-voyw1v) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d90a93f45f7641064498fbbd46567a0ee384f2f/pkg/server/serverpb/admin.proto#L295)):*
> ```protobuf
> }
> 
> // UserSQLRolesRequest requests a list roles of the logged SQL user.
> ```

nit: do you mean "a list of roles of the logged in SQL user"? 
___
*[pkg/server/admin_test.go, line 1762 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74920#-MtiSAnoA_n1uO-tLbb3:-MtiSAnoA_n1uO-tLbb4:b-86d675) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d90a93f45f7641064498fbbd46567a0ee384f2f/pkg/server/admin_test.go#L1762)):*
> ```Go
> 
> 	// No roles added to the user.
> 	if err := getAdminJSONProtoWithAdminOption(s, "sqlroles", &res, false /* isAdmin */); err != nil {
> ```

minor nit: using `require.NoError` here can help to reduce the verbosity
___
*[pkg/server/admin_test.go, line 1775 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74920#-MtiSx5_5pwFqIX_QJ3s:-MtiSx5_5pwFqIX_QJ3t:bjjuold) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d90a93f45f7641064498fbbd46567a0ee384f2f/pkg/server/admin_test.go#L1775)):*
> ```Go
> 	}
> 	expRoles := []string{"VIEWACTIVITY"}
> 	if !reflect.DeepEqual(res.Roles, expRoles) {
> ```

minor nit: I think `require.Equal` does deep equal check too as well and it does print out better object diffs too as well.
___
*[pkg/server/admin_test.go, line 1787 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74920#-MtiTGwCBKG-g52ynDiW:-MtiTGwCBKG-g52ynDiX:bdnrqh) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d90a93f45f7641064498fbbd46567a0ee384f2f/pkg/server/admin_test.go#L1787)):*
> ```Go
> 	if !reflect.DeepEqual(res.Roles, expRoles) {
> 		t.Errorf("Expected roles %v, but got %v", expRoles, res.Roles)
> 	}
> ```

Should we test role revocation here as well?

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74920)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/server/serverpb/admin.proto, line 295 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74920#-MtiRukYElIb3gUtdPCF:-MtiWjRc8atM7yPZQ8Lw:b-886gsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d90a93f45f7641064498fbbd46567a0ee384f2f/pkg/server/serverpb/admin.proto#L295)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: do you mean "a list of roles of the logged in SQL user"? 
</blockquote></details>

Fixed
___
*[pkg/server/admin_test.go, line 1762 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74920#-MtiSAnoA_n1uO-tLbb3:-MtiWlxN2UzxNV9b9tiz:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d90a93f45f7641064498fbbd46567a0ee384f2f/pkg/server/admin_test.go#L1762)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

minor nit: using `require.NoError` here can help to reduce the verbosity
</blockquote></details>

Done
___
*[pkg/server/admin_test.go, line 1775 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74920#-MtiSx5_5pwFqIX_QJ3s:-MtiWnWX81eqLk1viZAN:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d90a93f45f7641064498fbbd46567a0ee384f2f/pkg/server/admin_test.go#L1775)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

minor nit: I think `require.Equal` does deep equal check too as well and it does print out better object diffs too as well.
</blockquote></details>

Done
___
*[pkg/server/admin_test.go, line 1787 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74920#-MtiTGwCBKG-g52ynDiW:-MtiWrD_0rZoXKvcvtG0:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d90a93f45f7641064498fbbd46567a0ee384f2f/pkg/server/admin_test.go#L1787)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Should we test role revocation here as well? 
</blockquote></details>

Done

**Review by matthewtodd — APPROVED** [review]
Looks good! Does any of this need to be ready for the cloud? (Asking since `/admin` isn't available there.)

> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74920#-:-Mtib2zd-L-YE2M3-ERK:bjw6zs6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

**Review by maryliag — COMMENTED** [review]
Yes, it also needs to work on Cloud. I'm assuming I'll need to add some extra code there, but I'm not sure what yet

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74920#-:-MtjGbMU47yqBOUVQs4k:b-hr7gas)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

**Comment by Azhng** [comment]
Hmm can we use the `_status` API prefix? I think status server should generally be available on the cloud.

**Review by maryliag — COMMENTED** [review]
Moved the new endpoint to `_status`

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74920#-:-MtjZloeAj4cDH1odEnL:bdwkb78)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @matthewtodd)

**Review by Azhng — APPROVED** [review]
:lgtm: Minor refactoring nit and then all looks good.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74920#-:-MtkEhgmEbpmXhoHNym7:btk140d)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, and @matthewtodd)

___
*[pkg/server/user.go, line 22 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74920#-MtkDJvtB8uCD_h_JCw9:-MtkDJvtB8uCD_h_JCwA:btfakc3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cdd16ebc0a1ad058813714164e65b5793088098/pkg/server/user.go#L22)):*
> ```Go
> 
> // UserSQLRoles return a list of the logged in SQL user roles.
> func (s *statusServer) UserSQLRoles(
> ```

nit: I think we only need to define this function once on the `baseStatusServer` and the implementation will be available in both `statusServer` and `tenantStatusServer`. This would be helpful since we don't have to rely on `iterateNodes` and `iteratePods` function.

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74920)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng and @matthewtodd)

___
*[pkg/server/user.go, line 22 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74920#-MtkDJvtB8uCD_h_JCw9:-Mtmjbc788vFk9g5tlC0:bn7h7c8) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cdd16ebc0a1ad058813714164e65b5793088098/pkg/server/user.go#L22)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: I think we only need to define this function once on the `baseStatusServer` and the implementation will be available in both `statusServer` and `tenantStatusServer`. This would be helpful since we don't have to rely on `iterateNodes` and `iteratePods` function. 
</blockquote></details>

TIL! Nice! Change made

**Review by matthewtodd — APPROVED** [review]
:lgtm:

> Reviewed 10 of 12 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74920#-:-Mtn-qG_ESRVkiRrRWcu:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng)

**Review by Azhng — APPROVED** [review]
:lgtm: :rocket:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74920#-:-MtnHXpk-0ZSkHNs06_6:b-snql9h)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @maryliag)

**Comment by maryliag** [comment]
TFTR
bors r+

**Pull request merged**
