### PR TITLE
kv: stop txn heartbeater early on txn abort

### LINKED ISSUE #65194: kvcoord: txn heartbeater should stop monitoring record before sending EndTxn(commit=false)
As seen in e.g. `TestRollbackSyncRangedIntentResolution`, when a large transaction is being rolled back and hits the synchronous intent resolution path because the async task pool is full

https://github.com/cockroachdb/cockroach/blob/a4b7a431093870393cac9f11287eaf282abdbd22/pkg/kv/kvserver/intentresolver/intent_resolver.go#L430-L435

then the txn heartbeater may notice the txn record has been aborted before the `EndTxn` call returns (because it's still cleaning up intents) and kick off its own intent resolution:

https://github.com/cockroachdb/cockroach/blob/5e7f8bd7a511f58204a1419452fd4d439f9ccec8/pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go#L331-L343

This may contend with the `EndTxn` resolution which may be doing ranged intent resolution via `ResumeSpans`, causing the client to wait longer than necessary. This was a contributing factor for #64092.

The heartbeater should probably stop monitoring the tnx record before sending the final `EndTxn` request, rather than waiting for the response.

### PR DESCRIPTION
**Pull request by aliher1911**
Previously `txn_interceptor_heartbeater` was stoping heartbeat loop
on `closeLocked()` lifecycle event.
This behaviour was causing contention on transaction cleanup in
case of `intentresolver` switching to synchronous mode. Heartbeater
found aborted transactions while they were being synchronously
cleaned up.
To address this, `txn_heartbeater_interceptor` is stopping heartbeats
early as soon as EntTxn(commit=false) is observed.

Release note: None

Closes #65194

### CODE REVIEW

**Review by andreimatei — APPROVED** [review]
:lgtm: 

> This behaviour was causing contention on transaction cleanup in
> case of intentresolver switching to synchronous mode.

Would you mind expanding on this in the commit message? It's pretty terse.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65509#-:-Ma9S9Ut14tYK9pcMnDU:b-8ideia)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aliher1911 and @erikgrinaker)

___
*[pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go, line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65509#-Ma9SJWS3m2Xlcp0zJ5L:-Ma9SJWS3m2Xlcp0zJ5M:brecxhs) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c75a437975264785a4d06a9392de21457e817f3/pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go#L167)):*
> ```Go
> 		et := etArg.(*roachpb.EndTxnRequest)
> 
> 		// Set the EndTxn request's TxnHeartbeating flag, if necessary.
> ```

nit: this comment made some sense at the block level to say what a whole block does. At the line level it doesn't make sense because it doesn't add anything. So either expand on "if necessary" or strike it.
___
*[pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go, line 170 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65509#-Ma9Sbqm38dk7hoJim_u:-Ma9Sbqm38dk7hoJim_v:b-w8pn3k) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c75a437975264785a4d06a9392de21457e817f3/pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go#L170)):*
> ```Go
> 		et.TxnHeartbeating = h.mu.loopStarted
> 
> 		// Preemptively stop heartbeat loop in case of transaction abort
> ```

nit: *the* heartbeat loop :)
___
*[pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65509#-Ma9TG4t53SEl2p0LLx3:-Ma9TG4t53SEl2p0LLx4:b-1c3gw3) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c75a437975264785a4d06a9392de21457e817f3/pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go#L171)):*
> to prevent contention that could happen during synchronous cleanup

I don't think anyone will understand what this is talking about. Either expand or delete it. I'd delete the whole comment since it seems clear that we don't want to hb a rolling-back txn. The whole point of the hb is to keep a txn alive.
I personally don't feel a particular need to call out the contention thing that could happen.
___
*[pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go, line 172 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65509#-Ma9SmtE9VVTCgVVXXYN:-Ma9SmtE9VVTCgVVXXYO:brydrkp) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c75a437975264785a4d06a9392de21457e817f3/pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go#L172)):*
> ```
> 		// It is safe to do so, since aborted transactions
> 		// always close coord sender even if send fails.
> ```

I would strike this; I think it will confuse more then help. It seems clear that stopping the loop when we're trying to rollback is the right thing to do. Talking about "safety" only makes me worried about what safety properties we're talking about. I'd say either expand or, better, delete it.
___
*[pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go, line 174 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65509#-Ma9UJtd15PSNFDGj3NK:-Ma9UJtd15PSNFDGj3NL:but951p) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c75a437975264785a4d06a9392de21457e817f3/pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go#L174)):*
> ```Go
> 		// of a transaction. It is safe to do so, since aborted transactions
> 		// always close coord sender even if send fails.
> 		if !et.Commit {
> ```

the thing that deserves a comment here, in my opinion, is why not stop the loop on commit. The reason is that the commit can fail with a retriable error, and we want the transaction to go on into the next epoch.
___
*[pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater_test.go, line 420 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65509#-Ma9Tdyd0_XJJWNhA2MK:-Ma9Tdyd0_XJJWNhA2ML:b27m5x7) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c75a437975264785a4d06a9392de21457e817f3/pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater_test.go#L420)):*
> ```Go
> 
> // TestTxnHeartbeaterAbortStopsLoop tests that interceptor cancels heartbeats
> // early for aborted transactions while keeps it untouched for committed ones.
> ```

s/keeps/keeping
___
*[pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater_test.go, line 421 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65509#-Ma9TmwUEhRI4hdz8h6W:-Ma9TmwUEhRI4hdz8h6X:bih1rct) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c75a437975264785a4d06a9392de21457e817f3/pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater_test.go#L421)):*
> ```Go
> // TestTxnHeartbeaterAbortStopsLoop tests that interceptor cancels heartbeats
> // early for aborted transactions while keeps it untouched for committed ones.
> func TestTxnHeartbeaterAbortStopsLoop(t *testing.T) {
> ```

nit: I'd say `TestTxnHeartbeaterRollbackStopsLoop`. We generally call an `EndTxn(commit=false)` a rollback.
___
*[pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater_test.go, line 425 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65509#-Ma9Uvkx8KzMkP6-YoHC:-Ma9Uvky8WdGIz4Y-GX9:b-z9fn8c) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c75a437975264785a4d06a9392de21457e817f3/pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater_test.go#L425)):*
> ```Go
> 	defer log.Scope(t).Close(t)
> 
> 	testutils.RunTrueAndFalse(t, "transactionCommit", func(t *testing.T, transactionCommit bool) {
> ```

nit: since you've named the test specifically for the rollback case, consider adding a comment here explaining that, we *also* check the commit case for good measure. Better yet, name the test a little more generically `TestTxnHeartbeaterEndTxnStopsHeartbeatLoop`.
___
*[pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater_test.go, line 450 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65509#-Ma9UDnf-azd3nTk-LMJ:-Ma9UDnf-azd3nTk-LMK:b-7k7xnb) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c75a437975264785a4d06a9392de21457e817f3/pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater_test.go#L450)):*
> ```Go
> 		require.Nil(t, pErr)
> 		require.NotNil(t, br)
> 		require.Equal(t, transactionCommit, th.heartbeatLoopRunningLocked(), "heartbeat runs for commit, stops for abort")
> ```

nit: I'd be more explicit with the test expectation, to make it clear at the top of the test that we'll be expecting very different things based on the scenario. Like

```
for _, tc := range []struct{
  commit bool
  expHeatbeatsRunning bool
} {
{true, true}, {false, false},
} {
t.run(fmt.Sprintf("commit:%t", tc.commit), func(t){...}
}
```

**Review by erikgrinaker — APPROVED** [review]
:lgtm:

I agree with @andreimatei that the comments need to be fleshed out a bit more.

I also noticed that the test is failing in CI, so it's likely non-deterministic. You may want to run it though `make stress PKG=./pkg/kv/kvclient/kvcoord TESTS=TestTxnHeartbeaterAbortStopsLoop` for a while to weed it out.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65509#-:-Ma9ZzyK5S6Sq5PpuHW2:b-yiz6a7)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @aliher1911)

**Review by aliher1911 — COMMENTED** [review]
It was flaky because heartbeat loop is not instant and function returns before it actually stops. There's actually a helper there to check it stopped, but test for commit will not always pick the failure. Hard to prove that it doesn't stop from outside, so I'll leave it like that. If we break it, commit test would become flaky.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65509#-:-MaEd8nPE4c3IRQSD7RG:b-l0qxoe)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go, line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65509#-Ma9SJWS3m2Xlcp0zJ5L:-MaEZAwB99iHp30jVWOA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c75a437975264785a4d06a9392de21457e817f3/pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go#L167)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: this comment made some sense at the block level to say what a whole block does. At the line level it doesn't make sense because it doesn't add anything. So either expand on "if necessary" or strike it.
</blockquote></details>

Done.
___
*[pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go, line 170 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65509#-Ma9Sbqm38dk7hoJim_u:-MaEZ83g5NVZLg0SXoNT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c75a437975264785a4d06a9392de21457e817f3/pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go#L170)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: *the* heartbeat loop :)
</blockquote></details>

Done.
___
*[pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65509#-Ma9TG4t53SEl2p0LLx3:-MaEZ3_tD7jGYunJSMOa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c75a437975264785a4d06a9392de21457e817f3/pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go#L171)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> to prevent contention that could happen during synchronous cleanup

I don't think anyone will understand what this is talking about. Either expand or delete it. I'd delete the whole comment since it seems clear that we don't want to hb a rolling-back txn. The whole point of the hb is to keep a txn alive.
I personally don't feel a particular need to call out the contention thing that could happen.


</blockquote></details>

Done.
___
*[pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go, line 172 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65509#-Ma9SmtE9VVTCgVVXXYN:-MaEZMRpC3Rx1bqsscv3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c75a437975264785a4d06a9392de21457e817f3/pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go#L172)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> ```
> 		// It is safe to do so, since aborted transactions
> 		// always close coord sender even if send fails.
> ```

I would strike this; I think it will confuse more then help. It seems clear that stopping the loop when we're trying to rollback is the right thing to do. Talking about "safety" only makes me worried about what safety properties we're talking about. I'd say either expand or, better, delete it.
</blockquote></details>

Done.
___
*[pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go, line 174 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65509#-Ma9UJtd15PSNFDGj3NK:-MaE_5p1-PPbdear8gGS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c75a437975264785a4d06a9392de21457e817f3/pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go#L174)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

the thing that deserves a comment here, in my opinion, is why not stop the loop on commit. The reason is that the commit can fail with a retriable error, and we want the transaction to go on into the next epoch.
</blockquote></details>

Done.
___
*[pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater_test.go, line 420 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/65509#-Ma9Tdyd0_XJJWNhA2MK:-MaE_anTCOuSgkmwHlxt:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c75a437975264785a4d06a9392de21457e817f3/pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater_test.go#L420)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

s/keeps/keeping
</blockquote></details>

Done

**Comment by aliher1911** [comment]
Replying to myself here just for posterity. Test failure was caused by data race because lock was not by test checking the heartbeater loop state. State is always set correctly when method exists regardless if routing is already running or not.

**Comment by aliher1911** [comment]
bors r=erikgrinaker,andreimatei

**Comment by erikgrinaker** [comment]
Can we backport this to 21.1 as well?

**Pull request merged**
