### PR TITLE
sql/opt: cleanup and fixes for assignment casts

### PR DESCRIPTION
**Pull request by mgartner**
#### opt: do not rely on column names for validating updates to GENERATED ALWAYS AS IDENTITY columns

Previously, optbuilder relied on matching column names to validate that
mutations do not explicitly write to `GENERATED ALWAYS AS IDENTITY`
columns. There are no known bugs caused by this, but relying on column
names can be brittle. This commit updates the logic to use ordinals of
columns within their table instead.

Release note: None

#### opt: simplify optbuilder update logic

Release note: None

#### opt: fix type inference of insert values

Previously, the optimizer could infer non-canonical types for constant
values in inserts based on the target column's type. For example, when
inserting the value `1.45` into column `d DECIMAL(5, 1)`, the type of
`1.45` would be inferred as `DECIMAL(5, 1)`. As a result, assignment
casts weren't added in some cases, and incorrect values could be
inserted. This commit fixes the issue by inferring only canonical types
for values that have an ambiguous type.

This commit also changes the type inference of columns for inserts with
multi-row `VALUES` clauses. If constants in a `VALUES` column have
different types but belong to the same family, the canonical type of the
family will be inferred as the `VALUES` column type. This ensures that
an assignment cast will be planned when some constants in a multi-row
`VALUES` clause do not have types identical to their target column's
type.

There is no release note because this bug is not present in any previous
release.

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
The first commit is from #72575. No need to review that here.

cc @ZhouXing19: you might be interested in looking at the commit titled `opt: do not rely for validating updates to GENERATED ALWAYS AS IDENTITY columns`

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72617)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @nehageorge, and @ZhouXing19)

___
*[-- commits, line 38 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72617#-MoAIE1R8qghXh1_Z0E5):*
Is there other motivation for this change? We shouldn't care about allocations in error cases.
___
*[pkg/sql/opt/optbuilder/insert.go, line 585 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72617#-MoAJ8PC3p4B8ADqswEu:-MoAJ8PC3p4B8ADqswEv:b-p0y44b) ([raw file](https://github.com/cockroachdb/cockroach/blob/49dd455a8867b59b5841827629a1c09f8b000f63/pkg/sql/opt/optbuilder/insert.go#L585)):*
> ```Go
> 	//
> 	//   INSERT INTO <table> (...) VALUES (...)
> 	//
> ```

[nit] It's worth explaining why we want the canonical type here
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 1416 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72617#-MoAI7i02lxu15VRnMpQ:-MoAI7i02lxu15VRnMpR:b-uwgyl0) ([raw file](https://github.com/cockroachdb/cockroach/blob/c71f35eeceed2b12a12e81a39b745f5a91b1b004/pkg/sql/opt/optbuilder/mutation_builder.go#L1416)):*
> ```Go
> 			// Check if an assignment cast is available from the inScope column
> 			// type to the out type.
> 			if !tree.ValidCast(srcType, targetType, tree.CastContextAssignment) {
> ```

This was checking all columns, but now it is only checking columns up to the first one that needs a cast.
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 1390 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72617#-MoAIbjZ7rz4qBWw_EGx:-MoAIbjZ7rz4qBWw_EGy:b-kdcq4a) ([raw file](https://github.com/cockroachdb/cockroach/blob/49dd455a8867b59b5841827629a1c09f8b000f63/pkg/sql/opt/optbuilder/mutation_builder.go#L1390)):*
> ```Go
> // assignment casts so that the resulting columns have types identical to those
> // in outTypes. The length of srcCols must be equal to the number of columns in
> // the mutating table, and each column in srcCols represents the new value of
> ```

[nit] mutated table
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 1395 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72617#-MoAIfyO6jzrenu12-tn:-MoAIfyO6jzrenu12-to:b-3ahylv) ([raw file](https://github.com/cockroachdb/cockroach/blob/49dd455a8867b59b5841827629a1c09f8b000f63/pkg/sql/opt/optbuilder/mutation_builder.go#L1395)):*
> ```Go
> //
> // If there is no valid assignment cast from a column type in srcCols to its
> // corresponding target column type, then this function will panic. If all the
> ```

[nit] I'd say "throws an error" since it's not ultimately a panic

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72617)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nehageorge and @ZhouXing19)

___
*[-- commits, line 38 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/72617#-MoAIE1R8qghXh1_Z0E5):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Is there other motivation for this change? We shouldn't care about allocations in error cases.
</blockquote></details>

I've removed this commit.
___
*[pkg/sql/opt/optbuilder/insert.go, line 585 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72617#-MoAJ8PC3p4B8ADqswEu:-MoAW4V_7acnPXIk1Nny:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/49dd455a8867b59b5841827629a1c09f8b000f63/pkg/sql/opt/optbuilder/insert.go#L585)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] It's worth explaining why we want the canonical type here
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 1416 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/72617#-MoAI7i02lxu15VRnMpQ:-MoAX0WR8tQ5w-Cqi8dA:br62lv8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c71f35eeceed2b12a12e81a39b745f5a91b1b004/pkg/sql/opt/optbuilder/mutation_builder.go#L1416)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This was checking all columns, but now it is only checking columns up to the first one that needs a cast.
</blockquote></details>

I removed this commit. In the final commit, it is checking all the columns.
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 1390 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72617#-MoAIbjZ7rz4qBWw_EGx:-MoAWCpr0mBA9su_ceIl:bx9f93v) ([raw file](https://github.com/cockroachdb/cockroach/blob/49dd455a8867b59b5841827629a1c09f8b000f63/pkg/sql/opt/optbuilder/mutation_builder.go#L1390)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] mutated table
</blockquote></details>

Fixed. I was thinking "mutating" was more appropriate since we are in the process of mutating, but maybe it sounds too much like a verb rather than an adjective.
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 1395 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/72617#-MoAIfyO6jzrenu12-tn:-MoAWlrYEr69HFl6HgMs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/49dd455a8867b59b5841827629a1c09f8b000f63/pkg/sql/opt/optbuilder/mutation_builder.go#L1395)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] I'd say "throws an error" since it's not ultimately a panic
</blockquote></details>

Done.

**Comment by mgartner** [comment]
I added some more changes to make inserts with multi-row VALUES work correctly (like `INSERT INTO t(d) VALUES (1.23::DECIMAL(10, 0)), (4.56::DECIMAL(10, 2))`).

**Review by nehageorge — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 15 files at r6, 7 of 7 files at r7, 1 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72617)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @nehageorge, and @ZhouXing19)

___
*[pkg/sql/opt/optbuilder/update.go, line 216 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/72617#-MoZ24yyCEkFKCp5G1ZJ:-MoZ24yyCEkFKCp5G1ZK:b7igw71) ([raw file](https://github.com/cockroachdb/cockroach/blob/23a4896ce7d5467e8023649009577fdbf80b7559/pkg/sql/opt/optbuilder/update.go#L216)):*
> ```Go
> 		} else {
> 			// GENERATED ALWAYS AS IDENTITY columns are not allowed to be
> 			// explicitly written to.
> ```

Does this "not written to" logic in `update.go` and `insert.go` also get used for upserts? I'm assume that the depending on the nature of the upsert, the logic in one of the two files is triggered?
___
*[pkg/sql/opt/optbuilder/update.go, line 221 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/72617#-MoZ4ju59s7oMSMgAdty:-MoZ4ju59s7oMSMgAdtz:bnnk65p) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbdee2653115cb89bfa3c378652091e8c27a2a26/pkg/sql/opt/optbuilder/update.go#L221)):*
> ```Go
> 		texpr := inScope.resolveType(expr, targetCol.DatumType())
> 		targetColName := targetCol.ColName()
> 		colName := scopeColName(targetColName).WithMetadataName(string(targetColName) + "_new")
> ```

Is there a reason that this "_new" metadata name doesn't appear in tests?

**Review by ZhouXing19 — COMMENTED** [review]
Reviewed the commit `opt: do not rely on column names for validating updates to GENERATED ALWAYS AS IDENTITY columns` and  :lgtm: ! Thanks for making this change.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72617#-:-MooiwhQ2dh4bRbNQWOT:b2v523z)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner, @nehageorge, and @RaduBerinde)

**Pull request closed without merging**
