### PR TITLE
internal/issues: remove author CC from Github issue

### PR DESCRIPTION
**Pull request by mgartner**
Previously, automatically created issues would CC the author of the
test. In many cases, tests can fail for reasons outside of the author's
domain of knowledge, and incorrect CC's create unnecessary noise.
Mentioning the team that owns a test is sufficient for routing an issue
to the most appropriate subset of engineers.

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
The author is not pinged. It is only written into the commit message to facilitate manual routing, if necessary. Are you seeing something different? I'm not generally opposed to removing the author entirely, but the goals of the PR should already be achieved today without making any change.

**Comment by tbg** [comment]
Hard for me to speak for everyone, but at least on KV pings are not disseminated to all members (too noisy). So we do rely on git blame for routing occasionally. I would think that by continuing to include this information in the issue we are doing no harm (since the person is not notified; as far as Github is concerned they are not mentioned). If we remove it, we could be annoying someone.

What is maybe another argument for the removal, though, is that it's just such a weird one-off. I think I have seen folks think that there was a bug in the issue poster and that it was accidentally not mentioning the author despite putting it in the issue.

I'm fine removing this.

**Review by tbg — APPROVED** [review]

**Comment by mgartner** [comment]
> I would think that by continuing to include this information in the issue we are doing no harm

The motivation I didn't mention for this (because it's subjective) is that calling out specific people seems counter-productive for team cohesion.

But I don't want to break people's workflows with this change.  I'll close for now.

**Review by tbg — APPROVED** [review]

**Comment by tbg** [comment]
(We talked it over and we think it's time for this half-mention to go; if someone violently objects it's easy to revert)

**Review by erikgrinaker — APPROVED** [review]
I'm fine with removing this. Seems like a team responsibility, and if it's unclear who to route to then it's easy enough to look at the blame.

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
