### PR TITLE
sql: use inaccessible columns for expression indexes

### PR DESCRIPTION
**Pull request by mgartner**
#### sql: rename expression-based indexes to expression indexes

This commit replaces the wordy references to "expression-based indexes"
with "expression indexes", matching the related RFC.

Release note: None

#### sql: add inaccessible columns

This commit adds the `Inaccessible` boolean field to column descriptors.
An inaccessible column does not appear in star expansion and cannot be
referenced in queries. It cannot be viewed when inspecting a table via
SHOW CREATE TABLE and is not shown as an attribute of its table in
pg_catalog.pg_attribute. A column cannot be both hidden and
inaccessible.

Inaccessible columns will be used for implementing expression indexes.

Release note: None

#### sql: use inaccessible columns for expression indexes

Expression indexes (a work-in-progress) now use inaccessible virtual
computed columns to represent expressions. This commit also makes some
expression index related errors more clear.

Release note: None

#### sql: improve type-related expression index errors

This commit improves error messages caused by mistyped expressions in
expression indexes.

Release note: None

#### sql: add docs URL to inverted index errors

This commit adds the inverted index documentation URL to errors related
to inverted indexes. Previously, the error message directed the user to
the documentation without a URL, putting the burden on them to track
down the correct webpage.

Release note: None

#### sql: add AccessibleColumns method to TableDescriptor interface

The `TableDescriptor` interface now includes an `AccessibleColumns`
method that returns all public column with `Inaccessible=false`. This
method simplifies code that needs to access only accessible columns.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
I was playing around with the change but something isn't working:
```
root@127.67.216.62:26257/defaultdb> set experimental_enable_expression_indexes = true;
SET

Time: 0ms total (execution 0ms / network 0ms)

root@127.67.216.62:26257/defaultdb> create table t (a int, b int, index((a+b)));
ERROR: unimplemented: only simple columns are supported as index elements
SQLSTATE: 0A000
HINT: You have attempted to use a feature that is not yet implemented.
See: https://go.crdb.dev/issue-v/9682/v21.2
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66620#-:-McUsNZh0f4ZbXBvYZ-U:b-3p4uhj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/opt_catalog.go, line 678 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66620#-McUppkdEoFeasES5D3H:-McUppkdEoFeasES5D3I:b5j5kq2) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ef8a46ebd1bdb47753b1bbc3709cb18ab1665be/pkg/sql/opt_catalog.go#L678)):*
> ```Go
> 			if col.IsInaccessible() {
> 				visibility = cat.Inaccessible
> 			}
> ```

[nit] maybe swap the order and use `else if`
___
*[pkg/sql/logictest/testdata/logic_test/expression_index, line 59 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66620#-McUsXWAEaElw-Q_kjdV:-McUsXWAEaElw-Q_kjdW:ber71p1) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd68a865ccb532f91034ef351f50f90ce85af948/pkg/sql/logictest/testdata/logic_test/expression_index#L59)):*
> ```
> CREATE INDEX err ON t ((comp + 10))
> 
> statement error type of index element NULL is ambiguous.*\nHINT: consider adding a type cast to the expression
> ```

We should add at least one test with one of these errors when the index is defined directly in CREATE TABLE.
___
*[pkg/sql/logictest/testdata/logic_test/expression_index, line 75 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66620#-McUsRpw7QVElf4FtLQS:-McUsRpw7QVElf4FtLQT:brep9bk) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd68a865ccb532f91034ef351f50f90ce85af948/pkg/sql/logictest/testdata/logic_test/expression_index#L75)):*
> ```
> 
> statement error index element a \+ b of type int is not allowed as the last column in an inverted index.*\nHINT: see the documentation for more information about inverted indexes
> CREATE INVERTED INDEX err ON t (a, (a + b));
> ```

We should add a test with a tuple. `ON (a, ((a+b)))` or `ON (a, (row (a,b)))` might do it

**Review by RaduBerinde — COMMENTED** [review]
Ah, maybe we don't yet support them in CREATE TABLE statements?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66620#-:-McUt9ZD0BgInoP3S5xY:bg0eozz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

**Review by mgartner — COMMENTED** [review]
> Ah, maybe we don't yet support them in CREATE TABLE statements?
 
Correct. I'll add that in #65703. I wanted to bring the `CREATE INDEX` behavior up to spec before reworking that PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66620#-:-McV-Glr9imWHRZ75IfB:bib81ip)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/opt_catalog.go, line 678 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66620#-McUppkdEoFeasES5D3H:-McV0MgO3zA_8zgbxYRl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ef8a46ebd1bdb47753b1bbc3709cb18ab1665be/pkg/sql/opt_catalog.go#L678)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] maybe swap the order and use `else if`
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/expression_index, line 59 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66620#-McUsXWAEaElw-Q_kjdV:-McV0O7G8Xe8BxbsqmZr:b11krnh) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd68a865ccb532f91034ef351f50f90ce85af948/pkg/sql/logictest/testdata/logic_test/expression_index#L59)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We should add at least one test with one of these errors when the index is defined directly in CREATE TABLE.
</blockquote></details>

Absolutely. Will do in #65703.
___
*[pkg/sql/logictest/testdata/logic_test/expression_index, line 75 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/66620#-McUsRpw7QVElf4FtLQS:-McV6aaYB8bBE1MumoWp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd68a865ccb532f91034ef351f50f90ce85af948/pkg/sql/logictest/testdata/logic_test/expression_index#L75)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We should add a test with a tuple. `ON (a, ((a+b)))` or `ON (a, (row (a,b)))` might do it
</blockquote></details>

Done.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> Reviewed 9 of 15 files at r1, 2 of 22 files at r5, 10 of 10 files at r6, 8 of 10 files at r7, 5 of 5 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66620#-:-McVGtdG5gcb_e_8tPQY:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/exec_util.go, line 369 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66620#-McVGpln3wR0OUsGa7LC:-McVGpln3wR0OUsGa7LD:box0ckq) ([raw file](https://github.com/cockroachdb/cockroach/blob/db67862dd35f5d94bb8441a779b99dbf97024bfa/pkg/sql/exec_util.go#L369)):*
> ```Go
> 
> var experimentalExpressionIndexesMode = settings.RegisterBoolSetting(
> 	"sql.defaults.experimental_expression_indexes.enabled",
> ```

We should add the old setting to `retiredSettings` in `settings` package.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66620)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

___
*[pkg/sql/exec_util.go, line 369 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/66620#-McVGpln3wR0OUsGa7LC:-McWfGnW5AWfuIp2fP-k:bfgfohh) ([raw file](https://github.com/cockroachdb/cockroach/blob/db67862dd35f5d94bb8441a779b99dbf97024bfa/pkg/sql/exec_util.go#L369)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We should add the old setting to `retiredSettings` in `settings` package.
</blockquote></details>

Done. Looks like we forgot to do this for other retired experimental settings like the settings for partial indexes and partitioned inverted index :grimacing:

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 9 of 15 files at r1, 2 of 22 files at r5, 24 of 24 files at r9, 11 of 11 files at r10, 11 of 11 files at r11, 6 of 6 files at r12.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66620#-:-Mcin_DuEvul9a4umrjB:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[pkg/sql/create_index.go, line 396 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/66620#-McimoMf6bmk28ObfVdf:-McimoMf6bmk28ObfVdg:biyhufm) ([raw file](https://github.com/cockroachdb/cockroach/blob/42914ae382c392dc9f38ea0c7f743b290f850f73/pkg/sql/create_index.go#L396)):*
> ```Go
> 							typ.Name(),
> 						),
> 						"see the documentation for more information about inverted indexes",
> ```

is there a specific docs page we can link to?
___
*[pkg/sql/show_create.go, line 87 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/66620#-MciiasZ4H0X0VqQxCem:-Mciias_6MBVSnsgdojy:bje65ld) ([raw file](https://github.com/cockroachdb/cockroach/blob/c29a5475ccbdcbc5e09fb50e523c087591487cc8/pkg/sql/show_create.go#L87)):*
> ```Go
> 	for i, col := range desc.PublicColumns() {
> 		// Inaccessible columns are not displayed in SHOW CREATE TABLE.
> 		if col.IsInaccessible() {
> ```

Is there a way to make these columns not get returned by `desc.PublicColumns()`? Or is that more trouble than it's worth?
___
*[pkg/sql/logictest/testdata/logic_test/pg_catalog, line 467 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/66620#-McilxxJ5UDZBu_YupK4:-McilxxJ5UDZBu_YupK5:bxjxzhh) ([raw file](https://github.com/cockroachdb/cockroach/blob/48978eed979b6b0ba893c269f08a995b5607e3ca/pkg/sql/logictest/testdata/logic_test/pg_catalog#L467)):*
> ```
> 61          t6                                                        2332901747    0        0          1546506610  2631952481  0            0
> 4179599057  primary                                                   2332901747    0        0          1546506610  2631952481  0            0
> 4179599058  t6_crdb_internal_idx_expr_idx                             2332901747    0        0          1546506610  2631952481  0            0
> ```

Are you planning to remove `crdb_internal` from the index name? Seems like it adds a lot of unnecessary clunkiness.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66620)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @rytaft)

___
*[pkg/sql/create_index.go, line 396 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/66620#-McimoMf6bmk28ObfVdf:-McjL6RRABVXFjqt6dRF:b-au7021) ([raw file](https://github.com/cockroachdb/cockroach/blob/42914ae382c392dc9f38ea0c7f743b290f850f73/pkg/sql/create_index.go#L396)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

is there a specific docs page we can link to?
</blockquote></details>

Good idea. Added the URL to these errors messages in a new commit.
___
*[pkg/sql/show_create.go, line 87 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/66620#-MciiasZ4H0X0VqQxCem:-McjN6Nv5wrSIekj8Yh5:boo0xwy) ([raw file](https://github.com/cockroachdb/cockroach/blob/c29a5475ccbdcbc5e09fb50e523c087591487cc8/pkg/sql/show_create.go#L87)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Is there a way to make these columns not get returned by `desc.PublicColumns()`? Or is that more trouble than it's worth?
</blockquote></details>

Great question. You might remember that I tried to do this when I originally attempted to create inaccessible columns about a month ago. It required some unsavory changes to the `tabledesc.newColumnCache`.

It seems that "public" designates where a column sits on the mutation axis: public, writable, deletable, not the visibility axis: visible, hidden, inaccessible. The documentation for the `Column` interface's `Public` method states that a public column is any "active, readable column in the table descriptor".  I think the name "public" is causing confusion for us. Maybe "active" is a better description. I'm happy to make that change if we can get consensus on a more clear name.

For now, I've added an `AccessibleColumns` function that returns public, inaccessible=false columns. This cleans up a bit of code.
___
*[pkg/sql/logictest/testdata/logic_test/pg_catalog, line 467 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/66620#-McilxxJ5UDZBu_YupK4:-McjP1UOExkshi_O56VJ:b-jv0ggp) ([raw file](https://github.com/cockroachdb/cockroach/blob/48978eed979b6b0ba893c269f08a995b5607e3ca/pkg/sql/logictest/testdata/logic_test/pg_catalog#L467)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Are you planning to remove `crdb_internal` from the index name? Seems like it adds a lot of unnecessary clunkiness.
</blockquote></details>

Yes. I'm planning on following Postgres's naming convention for anonymous expression indexes in a future PR:

```
marcus=# CREATE TABLE t (a INT, b INT);
CREATE TABLE

marcus=# CREATE INDEX ON t ((a + b));
CREATE INDEX

marcus=# CREATE INDEX ON t ((a + b), (b + 100));
CREATE INDEX

marcus=# \d t
                 Table "public.t"
 Column |  Type   | Collation | Nullable | Default
--------+---------+-----------+----------+---------
 a      | integer |           |          |
 b      | integer |           |          |
Indexes:
    "t_expr_expr1_idx" btree ((a + b), (b + 100))
    "t_expr_idx" btree ((a + b))
```

**Review by rytaft — COMMENTED** [review]
> Reviewed 5 of 5 files at r13, 6 of 6 files at r14.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66620)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner)

___
*[pkg/sql/show_create.go, line 87 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/66620#-MciiasZ4H0X0VqQxCem:-MckB1ls4euckvFk95jW:b-83sjoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/c29a5475ccbdcbc5e09fb50e523c087591487cc8/pkg/sql/show_create.go#L87)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Great question. You might remember that I tried to do this when I originally attempted to create inaccessible columns about a month ago. It required some unsavory changes to the `tabledesc.newColumnCache`.

It seems that "public" designates where a column sits on the mutation axis: public, writable, deletable, not the visibility axis: visible, hidden, inaccessible. The documentation for the `Column` interface's `Public` method states that a public column is any "active, readable column in the table descriptor".  I think the name "public" is causing confusion for us. Maybe "active" is a better description. I'm happy to make that change if we can get consensus on a more clear name.

For now, I've added an `AccessibleColumns` function that returns public, inaccessible=false columns. This cleans up a bit of code.
</blockquote></details>

Nice!
___
*[pkg/sql/catalog/tabledesc/table_desc.go, line 362 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/66620#-MckBZht8pQKSEG0NEE3:-MckBZht8pQKSEG0NEE4:bcex9zx) ([raw file](https://github.com/cockroachdb/cockroach/blob/9873fc47ec66f3f509ac022f0fb5ed930fc844ef/pkg/sql/catalog/tabledesc/table_desc.go#L362)):*
> ```Go
> // VisibleColumns returns a slice of Column interfaces containing the
> // table's visible columns, in the canonical order. Visible columns are public
> // columns with Hidden=false.
> ```

Does this mean inaccessible columns would be included here? Is that desirable?
___
*[pkg/sql/logictest/testdata/logic_test/pg_catalog, line 467 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/66620#-McilxxJ5UDZBu_YupK4:-MckBsnz3bGURT-ejpMU:b-hfghm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/48978eed979b6b0ba893c269f08a995b5607e3ca/pkg/sql/logictest/testdata/logic_test/pg_catalog#L467)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Yes. I'm planning on following Postgres's naming convention for anonymous expression indexes in a future PR:

```
marcus=# CREATE TABLE t (a INT, b INT);
CREATE TABLE

marcus=# CREATE INDEX ON t ((a + b));
CREATE INDEX

marcus=# CREATE INDEX ON t ((a + b), (b + 100));
CREATE INDEX

marcus=# \d t
                 Table "public.t"
 Column |  Type   | Collation | Nullable | Default
--------+---------+-----------+----------+---------
 a      | integer |           |          |
 b      | integer |           |          |
Indexes:
    "t_expr_expr1_idx" btree ((a + b), (b + 100))
    "t_expr_idx" btree ((a + b))
```
</blockquote></details>

Sounds good

**Comment by otan** [comment]
___
*[pkg/sql/create_index.go, line 396 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/66620#-McknEhFDkkhL2ceT5kH:-McknEhFDkkhL2ceT5kI:b-3ghs4m) ([raw file](https://github.com/cockroachdb/cockroach/blob/9873fc47ec66f3f509ac022f0fb5ed930fc844ef/pkg/sql/create_index.go#L396)):*
> ```Go
> 							typ.Name(),
> 						),
> 						"see the documentation for more information about inverted indexes: https://www.cockroachlabs.com/docs/stable/inverted-indexes.html",
> ```

nit: use docs.URL

snoop otan out

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66620)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @rytaft)

___
*[pkg/sql/create_index.go, line 396 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/66620#-McknEhFDkkhL2ceT5kH:-MckqJaM-3A5gGO0g4MW:btqdqpg) ([raw file](https://github.com/cockroachdb/cockroach/blob/9873fc47ec66f3f509ac022f0fb5ed930fc844ef/pkg/sql/create_index.go#L396)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nit: use docs.URL

snoop otan out
</blockquote></details>

Brilliant. Thanks!
___
*[pkg/sql/catalog/tabledesc/table_desc.go, line 362 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/66620#-MckBZht8pQKSEG0NEE3:-MckvYcl6t1DyGwAs9JI:b-4qvsp2) ([raw file](https://github.com/cockroachdb/cockroach/blob/9873fc47ec66f3f509ac022f0fb5ed930fc844ef/pkg/sql/catalog/tabledesc/table_desc.go#L362)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Does this mean inaccessible columns would be included here? Is that desirable?
</blockquote></details>

Good point. I don't think it is desirable. The only place this function is used is in the context of `IMPORT` statements, as far as I can tell. In those cases, it is used to determine which columns to write to. Inaccessible columns are all computed columns (at least for now), so it is invalid to write to them directly. I've updated the function so that it only returns hidden=false and inaccessible=false columns.

Following these code paths allowed to me to discover a bug when`IMPORT`-ing into a table with virtual computed columns: #66694. I'm glad you drew our attention to this!

**Comment by mgartner** [comment]
When I get the build to pass, I'll go ahead and merge this for now. Any late comments I can address in future PRs—there's still a lot of little details I'll continue to work on to get expression indexes working as expected.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 33 of 33 files at r15, 11 of 11 files at r16, 11 of 11 files at r17, 6 of 6 files at r18, 5 of 5 files at r19, 5 of 6 files at r20, 7 of 7 files at r21, 6 of 6 files at r22.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66620#-:-McpHppw701Aj3xLhhKV:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[pkg/sql/catalog/tabledesc/table_desc.go, line 362 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/66620#-MckBZht8pQKSEG0NEE3:-McpGyNc1-kcjHVqgPyh:b-83sjoh) ([raw file](https://github.com/cockroachdb/cockroach/blob/9873fc47ec66f3f509ac022f0fb5ed930fc844ef/pkg/sql/catalog/tabledesc/table_desc.go#L362)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Good point. I don't think it is desirable. The only place this function is used is in the context of `IMPORT` statements, as far as I can tell. In those cases, it is used to determine which columns to write to. Inaccessible columns are all computed columns (at least for now), so it is invalid to write to them directly. I've updated the function so that it only returns hidden=false and inaccessible=false columns.

Following these code paths allowed to me to discover a bug when`IMPORT`-ing into a table with virtual computed columns: #66694. I'm glad you drew our attention to this!
</blockquote></details>

Nice!

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
