### PR TITLE
blobs: Add local client for blob service

### PR DESCRIPTION
**Pull request by g3orgia**
The blob service allows us to access files on any Cockroach node,
from any other node. However, even when we are attempting to access
a local file on the current node, the `remoteClient` for the blob
service still uses the node dialer to find it, and connect to it.
This makes local file access much slower than it should be.

This PR adds a `localClient`, as well as a `wrapperClient` to the
blob service. The `localClient` is given the `localStorage` object,
and runs its code directly, bypassing making a gRPC connection.
The `wrapperClient` is given the current node's node ID, a `localClient`
and a `remoteClient`. Based on the nodeID of the file we are trying
to reach, the `wrapperClient` decides on which client to use.

This PR takes all local file storage operations and puts it into a
`LocalStorage` object. This object is then used in both `localClient`
and `blobService.`

We plan to use this `wrapperClient`, which wraps all the logic necessary
for file access, in `ExternalStorage`.

Release notes: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
How do you feel about going the other way with this? By "going the other way" I mean that we implement `localStorage` or something perhaps with a better name that doesn't know anything about node IDs but does interact with the local filesystem. The `Service` then has a handle to one of these `localStorage` things and uses it. Then in the struct which implements `ExternalStorage` we keep the current node ID and then decide whether to call out to the `localStorage` or to use the `remoteClient`.

The way this code is implemented we have this localClient shim which knows things about gRPC even though it really doesn't need to know anything about the gRPC service. 

Does that seem reasonable? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41955#-:-LsI-67fARKcX4VlEXbT:b-5fh0ju)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

**Review by g3orgia — COMMENTED** [review]
Hmm I think that was originally what we were going to do (that's why we extracted `writeFileLocally` to utils.go), but felt like that's too much custom logic in `ExternalStorage` for local vs. remote. Since this logic has to go _somewhere_ , the conclusion was that it was better to go in the blobClient than in `ExternalStorage`. This way, `blobClient.ReadFile(ctx, nodeID, file)`, always works as expected, no matter the user.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41955#-:-LsI1myb8htmwVU3yLZt:bckbkpk)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by ajwerner — COMMENTED** [review]
> Since this logic has to go somewhere , the conclusion was that it was better to go in the blobClient than in ExternalStorage

Was this discussed on the previous PR and I just misunderstood?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41955#-:-LsI3IVYB0YanGLC24i7:b-v8xu9i)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by g3orgia — COMMENTED** [review]
> We chatted offline and I think it makes sense to make
> a) an interface documenting this API
> b) rename this to remoteClient
> c) add another impl of this interface on top of local io (that ignores node id)
> d) add a wrapper impl where each method just delegates to the local if node id matches, or to this impl if not.

Hmmm I believe so ^ was part of the previous PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41955#-:-LsI4TMK3va9TpESwT2Q:bqbi6lq)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by ajwerner — COMMENTED** [review]
gah in my head I was thinking that impl was of the ExternalStorage interface. My problem with the approach outlined here is that it tangles the dependencies. 

Interacting with nodelocal storage on the local node doesn't depend on anything but the external data directory.

The service that provides access to remote hosts has the same dependency (and should provide identical semantics), thus it seems reasonable for that to just delegate to the local storage. Its interface differs in that it implements the gRPC service which is an implementation detail of the client and won't align perfectly with the implementation of the local storage interface.

The remoteClient needs to know about the gRPC and will depend on the nodeDialer. Then finally we can have an ExternalStorage implementation that knows how to parse these `nodelocal` URIs and can decide whether it needs to use a remote client or can just delegate to the local storage (which sits beneath the gRPC service). 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41955#-:-LsI4u7S2I-vYTThFl6J:b8ibmzy)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by g3orgia — COMMENTED** [review]
@ajwerner hopefully, this solution is cleaner.

This new `LocalStorage` layer sits beneath the blob service and the local client, such that local and remote file access share the same code. However, as @dt envisioned,  all this logic is wrapped within the blob service such that `ExternalStorage` will not need to know whether or not we need to remotely access a file.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41955#-:-LsIYQxs4Z_yNIVhCc9s:brexl9m)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by ajwerner — COMMENTED** [review]
Yeah I'm fine with this. It's cleaner too. I don't see any reason to export `NewLocalClient` or `NewRemoteClient` anymore. 

> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41955#-:-LsIgidk0upEhjedZIUZ:byb8840)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @g3orgia)

___
*[pkg/blobs/local_storage.go, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41955#-LsIgBCTEyHjeOH78oi4:-LsIgBCTEyHjeOH78oi5:b-ad24a5) ([raw file](https://github.com/cockroachdb/cockroach/blob/00150387f6431c1638da4899c78ec98109e81d81/pkg/blobs/local_storage.go#L24)):*
> ```Go
> )
> 
> // LocalStorage wraps all operations with the local file system
> ```

don't export this struct if it doesn't feature on any of the objects you expect your clients to use (and it doesn't). 
___
*[pkg/blobs/local_storage.go, line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41955#-LsIeiM73Jcbp1br5mJO:-LsIeiM73Jcbp1br5mJP:bomi13o) ([raw file](https://github.com/cockroachdb/cockroach/blob/00150387f6431c1638da4899c78ec98109e81d81/pkg/blobs/local_storage.go#L74)):*
> ```Go
> }
> 
> // ReadFile prepends IO dir to filename and reads the content of that local file.
> ```

This should return the `io.ReadCloser` like in the `ExternalStorage` interface, otherwise you're going to end up buffering the whole file in memory on the localhost. The service will need to copy it into memory (until we implement streaming).

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41955#-:-LsIxfXW--0OukVpaqyG:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by g3orgia** [comment]
bors r=ajwerner

**Pull request merged**
