### PR TITLE
sql: improve error message for Test{Active,Idle}CancelSession

### LINKED ISSUE #33415: teamcity: failed test: TestActiveCancelSession
The following tests appear to have failed on master (test): TestActiveCancelSession

You may want to check [for open issues](https://github.com/cockroachdb/cockroach/issues?q=is%3Aissue+is%3Aopen+TestActiveCancelSession).

[#1075102](https://teamcity.cockroachdb.com/viewLog.html?buildId=1075102):

```
TestActiveCancelSession
...:26.508024 99872 server/node.go:696  [n?] connecting to gossip network to verify cluster ID...
I181231 14:38:26.508511 99872 server/node.go:721  [n?] node connected via gossip and verified as part of cluster "9549a22c-f001-439a-95f0-7e2b8b8dd898"
I181231 14:38:26.512107 100406 gossip/server.go:231  [n1] received initial cluster-verification connection from {tcp 127.0.0.1:35063}
I181231 14:38:26.543376 99872 server/node.go:424  [n?] new node allocated ID 2
I181231 14:38:26.544287 99872 gossip/gossip.go:391  [n2] NodeDescriptor set to node_id:2 address:<network_field:"tcp" address_field:"127.0.0.1:35063" > attrs:<> locality:<> ServerVersion:<major_val:2 minor_val:1 patch:0 unstable:3 > build_tag:"v2.2.0-alpha.20181217-315-ga8afcab" started_at:1546267106543815492 
I181231 14:38:26.546128 99872 storage/stores.go:243  [n2] read 0 node addresses from persistent storage
I181231 14:38:26.546654 99872 storage/stores.go:262  [n2] wrote 1 node addresses to persistent storage
I181231 14:38:26.553946 100003 storage/stores.go:262  [n1] wrote 1 node addresses to persistent storage
I181231 14:38:26.578881 99872 server/node.go:671  [n2] bootstrapped store [n2,s2]
I181231 14:38:26.581394 99872 server/node.go:545  [n2] node=2: started with [<no-attributes>=<in-mem>] engine(s) and attributes []
I181231 14:38:26.583938 99872 server/status/recorder.go:610  [n2] available memory from cgroups (8.0 EiB) exceeds system memory 16 GiB, using system memory
I181231 14:38:26.588603 99872 server/server.go:1832  [n2] Could not start heap profiler worker due to: directory to store profiles could not be determined
I181231 14:38:26.591401 99872 server/server.go:1534  [n2] starting https server at 127.0.0.1:36449 (use: 127.0.0.1:36449)
I181231 14:38:26.591612 99872 server/server.go:1536  [n2] starting grpc/postgres server at 127.0.0.1:35063
I181231 14:38:26.591681 99872 server/server.go:1537  [n2] advertising CockroachDB node at 127.0.0.1:35063
I181231 14:38:26.599426 99872 server/server.go:1590  [n2] done ensuring all necessary migrations have run
I181231 14:38:26.599624 99872 server/server.go:1593  [n2] serving sql connections
I181231 14:38:26.758994 100513 server/server_update.go:66  [n2] no need to upgrade, cluster already at the newest version
I181231 14:38:26.773483 100516 sql/event_log.go:131  [n2] Event: "node_join", target: 2, info: {Descriptor:{NodeID:2 Address:{NetworkField:tcp AddressField:127.0.0.1:35063} Attrs: Locality: ServerVersion:2.1-3 BuildTag:v2.2.0-alpha.20181217-315-ga8afcab StartedAt:1546267106543815492 LocalityAddress:[]} ClusterID:9549a22c-f001-439a-95f0-7e2b8b8dd898 StartedAt:1546267106543815492 LastUp:1546267106543815492}
I181231 14:38:26.880849 100040 gossip/gossip.go:1513  [n1] node has connected to cluster via gossip
I181231 14:38:26.881992 100040 storage/stores.go:262  [n1] wrote 1 node addresses to persistent storage
I181231 14:38:27.856151 100596 util/stop/stopper.go:536  quiescing; tasks left:
1      [async] closedts-subscription
1      [async] closedts-rangefeed-subscriber
I181231 14:38:27.858934 100595 util/stop/stopper.go:536  quiescing; tasks left:
1      [async] transport racer
1      [async] closedts-subscription
1      [async] closedts-rangefeed-subscriber
I181231 14:38:27.867779 100595 util/stop/stopper.go:536  quiescing; tasks left:
1      [async] transport racer
1      [async] closedts-subscription
I181231 14:38:27.868734 100595 util/stop/stopper.go:536  quiescing; tasks left:
1      [async] transport racer
I181231 14:38:27.869177 100596 util/stop/stopper.go:536  quiescing; tasks left:
1      [async] closedts-rangefeed-subscriber
I181231 14:38:27.929860 100597 rpc/nodedialer/nodedialer.go:90  [ct-client] unable to connect to n2: context canceled
I181231 14:38:27.965510 100111 kv/transport_race.go:113  transport race promotion: ran 49 iterations on up to 317 requests
I181231 14:38:27.978001 100579 rpc/nodedialer/nodedialer.go:90  [ct-client] unable to connect to n1: context canceled



TestActiveCancelSession
...
I181231 14:17:41.399136 105127 server/status/recorder.go:610  [n2] available memory from cgroups (8.0 EiB) exceeds system memory 16 GiB, using system memory
I181231 14:17:41.399175 105127 server/server.go:1832  [n2] Could not start heap profiler worker due to: directory to store profiles could not be determined
I181231 14:17:41.399233 105127 server/server.go:1534  [n2] starting https server at 127.0.0.1:37041 (use: 127.0.0.1:37041)
I181231 14:17:41.399254 105127 server/server.go:1536  [n2] starting grpc/postgres server at 127.0.0.1:45517
I181231 14:17:41.399265 105127 server/server.go:1537  [n2] advertising CockroachDB node at 127.0.0.1:45517
I181231 14:17:41.400811 105127 server/server.go:1590  [n2] done ensuring all necessary migrations have run
I181231 14:17:41.400841 105127 server/server.go:1593  [n2] serving sql connections
I181231 14:17:41.418756 105664 rpc/nodedialer/nodedialer.go:90  [n1] unable to connect to n2: unable to look up descriptor for n2
I181231 14:17:41.428826 105184 server/server_update.go:66  [n2] no need to upgrade, cluster already at the newest version
I181231 14:17:41.430068 105130 storage/stores.go:262  [n1] wrote 1 node addresses to persistent storage
I181231 14:17:41.438474 105651 sql/event_log.go:131  [n2] Event: "node_join", target: 2, info: {Descriptor:{NodeID:2 Address:{NetworkField:tcp AddressField:127.0.0.1:45517} Attrs: Locality: ServerVersion:2.1-3 BuildTag:v2.2.0-alpha.20181217-315-ga8afcab StartedAt:1546265861397205509 LocalityAddress:[]} ClusterID:85e8fbdb-d985-4e83-a16f-b16e0db17dbc StartedAt:1546265861397205509 LastUp:1546265861397205509}
I181231 14:17:42.163428 105680 storage/replica_consistency.go:126  [n1,consistencyChecker,s1,r1/1:/M{in-ax}] triggering stats recomputation to resolve delta of {ContainsEstimates:true LastUpdateNanos:1546265861445053529 IntentAge:0 GCBytesAge:0 LiveBytes:-49708 LiveCount:-1018 KeyBytes:-48120 KeyCount:-1018 ValBytes:-1588 ValCount:-1018 IntentBytes:0 IntentCount:0 SysBytes:0 SysCount:0}
I181231 14:17:43.050133 105486 gossip/gossip.go:1513  [n2] node has connected to cluster via gossip
I181231 14:17:43.050352 105486 storage/stores.go:262  [n2] wrote 1 node addresses to persistent storage
I181231 14:17:43.182431 105215 gossip/gossip.go:1513  [n1] node has connected to cluster via gossip
I181231 14:17:43.182650 105215 storage/stores.go:262  [n1] wrote 1 node addresses to persistent storage
I181231 14:17:51.146597 105376 server/status/runtime.go:464  [n1] runtime stats: 194 MiB RSS, 688 goroutines, 27 MiB/61 MiB/109 MiB GO alloc/idle/total, 18 MiB/54 MiB CGO alloc/total, 0.0 CGO/sec, 0.0/0.0 %(u/s)time, 0.0 %gc (733x), 6.9 MiB/6.9 MiB (r/w)net
W181231 14:17:51.153953 105378 server/node.go:885  [n1,summaries] health alerts detected: {Alerts:[{StoreID:1 Category:METRICS Description:ranges.underreplicated Value:1}]}
I181231 14:17:51.401195 105619 server/status/runtime.go:464  [n2] runtime stats: 195 MiB RSS, 688 goroutines, 0 B/0 B/0 B GO alloc/idle/total, 19 MiB/55 MiB CGO alloc/total, 0.0 CGO/sec, 0.0/0.0 %(u/s)time, 0.0 %gc (733x), 7.5 MiB/7.5 MiB (r/w)net
E181231 14:17:51.419416 105980 sql/distsqlrun/flow_registry.go:233  [intExec=read orphaned table leases] flow id:ee9df3d0-46e0-4f1a-ab23-5a248e4ea0fd : 1 inbound streams timed out after 10s; propagated error throughout flow
I181231 14:17:51.738964 106036 util/stop/stopper.go:536  quiescing; tasks left:
1      [async] closedts-subscription
1      [async] closedts-rangefeed-subscriber
I181231 14:17:51.739163 106035 util/stop/stopper.go:536  quiescing; tasks left:
1      [async] closedts-subscription
1      [async] closedts-rangefeed-subscriber
W181231 14:17:51.740975 105486 gossip/gossip.go:1499  [n2] no incoming or outgoing connections
I181231 14:17:51.741221 106036 util/stop/stopper.go:536  quiescing; tasks left:
1      [async] closedts-rangefeed-subscriber
I181231 14:17:51.744347 106035 util/stop/stopper.go:536  quiescing; tasks left:
1      [async] closedts-subscription




```

Please assign, take a look and update the issue accordingly.

### LINKED ISSUE #33419: sql: TestIdleCancelSession failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/a8afcabd753eff930f2f1fef5e79718439fbf65a

Parameters:
```
TAGS=
GOFLAGS=
```

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=TestIdleCancelSession PKG=github.com/cockroachdb/cockroach/pkg/sql TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1075315&tab=buildLog

```
I190101 06:20:16.745694 105516 server/status/recorder.go:610  [n2] available memory from cgroups (8.0 EiB) exceeds system memory 16 GiB, using system memory
I190101 06:20:16.745717 105516 server/server.go:1832  [n2] Could not start heap profiler worker due to: directory to store profiles could not be determined
I190101 06:20:16.745771 105516 server/server.go:1534  [n2] starting https server at 127.0.0.1:39931 (use: 127.0.0.1:39931)
I190101 06:20:16.745784 105516 server/server.go:1536  [n2] starting grpc/postgres server at 127.0.0.1:38215
I190101 06:20:16.745794 105516 server/server.go:1537  [n2] advertising CockroachDB node at 127.0.0.1:38215
I190101 06:20:16.746594 105516 server/server.go:1590  [n2] done ensuring all necessary migrations have run
I190101 06:20:16.746698 105516 server/server.go:1593  [n2] serving sql connections
I190101 06:20:16.755891 105830 rpc/nodedialer/nodedialer.go:90  [n1] unable to connect to n2: unable to look up descriptor for n2
I190101 06:20:16.756275 105519 storage/stores.go:262  [n1] wrote 1 node addresses to persistent storage
I190101 06:20:16.760652 105929 server/server_update.go:66  [n2] no need to upgrade, cluster already at the newest version
I190101 06:20:16.809256 105932 sql/event_log.go:131  [n2] Event: "node_join", target: 2, info: {Descriptor:{NodeID:2 Address:{NetworkField:tcp AddressField:127.0.0.1:38215} Attrs: Locality: ServerVersion:2.1-3 BuildTag:v2.2.0-alpha.20181217-315-ga8afcab StartedAt:1546323616743408444 LocalityAddress:[]} ClusterID:ffd52fb9-a3e1-49bb-9945-1cc90917dadc StartedAt:1546323616743408444 LastUp:1546323616743408444}
I190101 06:20:17.561278 106127 storage/replica_consistency.go:126  [n1,consistencyChecker,s1,r1/1:/M{in-ax}] triggering stats recomputation to resolve delta of {ContainsEstimates:true LastUpdateNanos:1546323616758068240 IntentAge:0 GCBytesAge:0 LiveBytes:-49708 LiveCount:-1018 KeyBytes:-48120 KeyCount:-1018 ValBytes:-1588 ValCount:-1018 IntentBytes:0 IntentCount:0 SysBytes:0 SysCount:0}
I190101 06:20:18.190206 105604 gossip/gossip.go:1513  [n1] node has connected to cluster via gossip
I190101 06:20:18.190350 105604 storage/stores.go:262  [n1] wrote 1 node addresses to persistent storage
I190101 06:20:18.588450 105917 gossip/gossip.go:1513  [n2] node has connected to cluster via gossip
I190101 06:20:18.588597 105917 storage/stores.go:262  [n2] wrote 1 node addresses to persistent storage
I190101 06:20:26.542268 105765 server/status/runtime.go:464  [n1] runtime stats: 187 MiB RSS, 684 goroutines, 28 MiB/59 MiB/107 MiB GO alloc/idle/total, 17 MiB/47 MiB CGO alloc/total, 0.0 CGO/sec, 0.0/0.0 %(u/s)time, 0.0 %gc (742x), 6.4 MiB/6.4 MiB (r/w)net
W190101 06:20:26.609652 105767 server/node.go:885  [n1,summaries] health alerts detected: {Alerts:[{StoreID:1 Category:METRICS Description:ranges.underreplicated Value:1}]}
I190101 06:20:26.747722 106040 server/status/runtime.go:464  [n2] runtime stats: 188 MiB RSS, 684 goroutines, 33 MiB/54 MiB/107 MiB GO alloc/idle/total, 18 MiB/48 MiB CGO alloc/total, 0.0 CGO/sec, 0.0/0.0 %(u/s)time, 0.0 %gc (742x), 6.2 MiB/6.2 MiB (r/w)net
E190101 06:20:26.757718 106407 sql/distsqlrun/flow_registry.go:233  [intExec=read orphaned table leases] flow id:c96335f9-98c0-4a9a-a535-0072a4762188 : 1 inbound streams timed out after 10s; propagated error throughout flow
I190101 06:20:27.048809 106446 util/stop/stopper.go:536  quiescing; tasks left:
1      [async] closedts-subscription
1      [async] closedts-rangefeed-subscriber
I190101 06:20:27.048866 106447 util/stop/stopper.go:536  quiescing; tasks left:
1      [async] closedts-subscription
1      [async] closedts-rangefeed-subscriber
W190101 06:20:27.060213 105917 gossip/gossip.go:1499  [n2] no incoming or outgoing connections
I190101 06:20:27.060649 106447 util/stop/stopper.go:536  quiescing; tasks left:
1      [async] closedts-rangefeed-subscriber
I190101 06:20:27.060844 106446 util/stop/stopper.go:536  quiescing; tasks left:
1      [async] closedts-rangefeed-subscriber
--- FAIL: TestIdleCancelSession (10.57s)
	run_control_test.go:321: expected 2 sessions but found 3

```

### PR DESCRIPTION
**Pull request by knz**
Supersedes #34063.
First commit from  #35503.
Fixes #33419
Fixes #33415

Two commits:

###  sql: improve error message for Test{Active,Idle}CancelSession

When the number of sessions differs from the number expected, output the
sessions.

### sql: hide internal sessions by default for SHOW {QUERIES,SESSIONS}

Hide internal sessions by default for `SHOW {QUERIES,SESSIONS}`. This is
motivated by recent flakes in `Test{Active,Idle}CancelSession`. Those
flakes were caused by an expected internal session. Fixing those tests
seems directly is possible, but if we can't get this right, what makes
us think that our users will? The change here is to introduce an
optional `ALL` specifier:

  `SHOW [ALL] [CLUSTER|LOCAL] {QUERIES,SESSIONS}`

If `ALL` is not specified, internal queries/sessions are hidden by
default by tacking a `WHERE application_name NOT LIKE '$ internal-'`
onto the delegated query.

Release note (sql change): SHOW QUERIES and SHOW SESSIONS now omit
internal queries and sessions by default. Use SHOW ALL QUERIES or SHOW
ALL SESSIONS to include internal queries in the output.

### CODE REVIEW

**Comment by knz** [comment]
@petermattis I have tried to push my edit to your branch `pmattis/cancel-session` but I didn't have permission, so I am creating a new PR.
If you prefer I can still push to your branch (if you give me permission) so as to preserve the link from the PR to the review history.

**Comment by petermattis** [comment]
@knz I'm thrilled you've taken over this change. I'm closing this PR.

**Comment by petermattis** [comment]
Gah, I closed the wrong PR! Sorry!

**Review by petermattis — APPROVED** [review]
LGTM

Looks like #35503 was an enabler for keeping the original approach of this PR (filtering based on the application name).

**Comment by knz** [comment]
> Looks like #35503  was an enabler for keeping the original approach of this PR (filtering based on the application name).

Yes correct.

TFYR!

bors r+

**Pull request merged**
