### PR TITLE
roachpb: micro-optimize Value.SetProto

### PR DESCRIPTION
**Pull request by petermattis**
```
name             old time/op    new time/op    delta
ValueSetProto-8     103ns ± 1%      73ns ± 2%  -29.60%  (p=0.000 n=10+10)

name             old allocs/op  new allocs/op  delta
ValueSetProto-8      2.00 ± 0%      1.00 ± 0%  -50.00%  (p=0.000 n=10+10)
```

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9861)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[roachpb/data.go, line 365 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9861#-KTkzlDQjqXJ7Zd9H_rC:-KTkzlDQjqXJ7Zd9H_rD:b-3r84m0) ([raw file](https://github.com/cockroachdb/cockroach/blob/6da548418f67cb14e82708a37479c5bac8862a47/roachpb/data.go#L365)):*
> ```Go
> 		size := m.Size()
> 		v.RawBytes = make([]byte, headerSize+size)
> 		protoutil.Interceptor(msg)
> ```

Isn't this a bit fragile? It might be better for `MarshalTo` to be a static function in `protoutil`.

note that `protoutil.Interceptor` is never called outside `protoutil` currently.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9861#-:-KTl-SH1hTuhcXu-qAdM:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[roachpb/data.go, line 365 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9861#-KTkzlDQjqXJ7Zd9H_rC:-KTl8UfRaUuNBCkKae_K:b-tu7l17) ([raw file](https://github.com/cockroachdb/cockroach/blob/6da548418f67cb14e82708a37479c5bac8862a47/roachpb/data.go#L365)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Isn't this a bit fragile? It might be better for `MarshalTo` to be a static function in `protoutil`.
> 
> note that `protoutil.Interceptor` is never called outside `protoutil` currently.
</details>
I had that same thought at dinner and was wondering if you were going to call me on it. Unfortunately, using a `protoutil.MarshalTo` is significantly slower than this current PR, eliminating all of the gains and then some (`112 ns/op`). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9861)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[roachpb/data.go, line 365 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9861#-KTkzlDQjqXJ7Zd9H_rC:-KTl9BpS4AYhPskJqOPm:b-c5x9nq) ([raw file](https://github.com/cockroachdb/cockroach/blob/6da548418f67cb14e82708a37479c5bac8862a47/roachpb/data.go#L365)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I had that same thought at dinner and was wondering if you were going to call me on it. Unfortunately, using a `protoutil.MarshalTo` is significantly slower than this current PR, eliminating all of the gains and then some (`112 ns/op`). 
</details>
Really? That's surprising. `MarshalTo` is always dynamically dispatched here (and thus never inlined), so...the function call overhead of `protoutil.MarshalTo` accounts for all the speed difference?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9861)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[roachpb/data.go, line 365 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9861#-KTkzlDQjqXJ7Zd9H_rC:-KTlC35ZncQYJUaXSC8J:bubzdxo) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6ca7c95c1630e1658665cc43d6e26d129f1a055/roachpb/data.go#L365)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Really? That's surprising. `MarshalTo` is always dynamically dispatched here (and thus never inlined), so...the function call overhead of `protoutil.MarshalTo` accounts for all the speed difference?
</details>
I agree it is surprising. I'm not sure exactly what the difference is, but it is very repeatable. Cpu profiling shows different functions showing up, almost as if using `protoutil.MarshalTo` affected inlining significantly. That seems weird/unexpected.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9861)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[roachpb/data.go, line 365 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9861#-KTkzlDQjqXJ7Zd9H_rC:-KTlCc6B8XD4W7oY5Zos:b-djbv06) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6ca7c95c1630e1658665cc43d6e26d129f1a055/roachpb/data.go#L365)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I agree it is surprising. I'm not sure exactly what the difference is, but it is very repeatable. Cpu profiling shows different functions showing up, almost as if using `protoutil.MarshalTo` affected inlining significantly. That seems weird/unexpected.
</details>
Sigh. LGTM with a comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9861)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[roachpb/data.go, line 365 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9861#-KTkzlDQjqXJ7Zd9H_rC:-KTlEyz86U4DPNQ9ND2_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6ca7c95c1630e1658665cc43d6e26d129f1a055/roachpb/data.go#L365)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Sigh. LGTM with a comment.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9861)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9861)*

**Pull request merged**
