### PR TITLE
storage: factor out replicaStateLoader and abortCache

### PR DESCRIPTION
**Pull request by tbg**
This is one of the self-contained threads to unravel for #18784.

We probably don't want to merge this just yet, but I think it's worth
basing other refactoring explorations on top of.

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm: though I agree we don't want to merge this yet.

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18785#-:-Kuz-8jTutxWq9UbLm5n:b-a5dxcm)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 16 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/storage/abortcache/abort_cache.go, line 53 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18785#-KuzQwfJXHK5ZVqKucCw:-KuzQwfKOexCDP2OLvLa:b-mpfjh2) ([raw file](https://github.com/cockroachdb/cockroach/blob/48c4a46fd40f5cbea2021780a7eee58ab7166b4e/pkg/storage/abortcache/abort_cache.go#L53)):*
> ```Go
> // this the "AbortSpan" instead, but large parts of the code still call this
> // "Instance". We should settle for one and rename everything post-yellow.
> type Instance struct {
> ```

`type Instance` seems wrong. I think the stuttery `abortcache.AbortCache` is better.

Nit: I don't like that the filename has an underscore and the directory doesn't. 

---

*[pkg/storage/stateloader/instance.go, line 55 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18785#-KuzRSHCy4cyu5uYNzD6:-KuzRSHCy4cyu5uYNzD7:bqat0kv) ([raw file](https://github.com/cockroachdb/cockroach/blob/48c4a46fd40f5cbea2021780a7eee58ab7166b4e/pkg/storage/stateloader/instance.go#L55)):*
> ```Go
> // struct with a mutex, and temporary loaders may be created when
> // locking is less desirable than an allocation.
> type Instance struct {
> ```

Again, I'd rather call this `stateloader.StateLoader`.

---

*[pkg/storage/stateloader/instance.go, line 60 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18785#-KuzRMWt8sNlgm4XIlCF:-KuzRMWt8sNlgm4XIlCG:b-4j54ou) ([raw file](https://github.com/cockroachdb/cockroach/blob/48c4a46fd40f5cbea2021780a7eee58ab7166b4e/pkg/storage/stateloader/instance.go#L60)):*
> ```Go
> }
> 
> // Make creates in Instance.
> ```

/in/an/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18785#-:-KuzSRLJ4DUad6SLvlq_:bnfp4nl)*

**Comment by tschottdorf** [comment]
TFTRs! I'll get back to this once we've released 1.1 and are ready to land refactors.

**Comment by tschottdorf** [comment]
Obsolete; the commits have been reworked and landed (or close to) as #19441 and #19401.

**Pull request closed without merging**
