### PR TITLE
*: use TestLogScope in tests more generally

### PR DESCRIPTION
**Pull request by knz**
The change is mostly mechanical:
```
$ for i in *_test.go; do awk '/leaktest\.AfterTest/ { print; print "\tdefer log.Scope(t).Close(t)"; next; }                                                                                                                                                                                      
{ print; }
' <$i >$i.tmp && \
mv -f $i.tmp $i; \
goimports -w $i; \
done
```

This reduces the size of the build log (`make test TESTFLAGS=-v`) from 80MB to <10MB.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
Can you explain what the consequences of the change will be? Eg when running opt/xform tests manually with -v? I very frequently debug by adding Printf and it's important to be able to delineate the lines printed for the relevant failing test.

BTW why do we run with -v in CI in the first place?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50506#-:-MAT6PJnCe1wz192jzOT:bu6pz7z)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea and @RaduBerinde)

**Comment by knz** [comment]
> Eg when running opt/xform tests manually with -v? I very frequently debug by adding Printf and it's important to be able to delineate the lines printed for the relevant failing test.

Two separate things:

- TestLogScope redirects all the `log.XXX` calls (`log.Info` etc); they will show up upon request with `TESTFLAGS=-show-logs`

- datadriven test traces are now hidden by default and show up with `TESTFLAGS=-datadriven-trace`

- uses of `t.Logf()` (from testing.T) and `fmt.Printf` are unaffected

does this clarify?

**Review by RaduBerinde — COMMENTED** [review]
Sounds like in my case I will have to always use `-datadriven-trace`. I will push on my other question - why do we want to run with `-v` in CI and then go through hoops to make the output smaller?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50506#-:-MAT9dsnC6cXELM1JdRp:bv1v05o)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea)

**Comment by RaduBerinde** [comment]
I guess `-v` is the only way to extract the list of tests that actually ran?

**Comment by knz** [comment]
> I guess -v is the only way to extract the list of tests that actually ran?

yes that is exactly it

**Comment by RaduBerinde** [comment]
I see. But then why not have CI pass a flag that reduces test output (including datadriven traces) instead of making it the default and having everyone who ever runs a test with `-v` know about a second flag?

**Comment by knz** [comment]
> I see. But then why not have CI pass a flag that reduces test output (including datadriven traces) instead of making it the default and having everyone who ever runs a test with -v know about a second flag?

Yes that is reasonable. I will work to flip the switches.

**Comment by tbg** [comment]
I like that you're putting effort into decluttering our test output, but have you considered the following:

1. the TC UI will be less usable. At the moment, you can simply hover a failing test and click "copy stacktrace". In the new world, you expand and see "here's the log file!" and then you will navigate manually through the artifacts and open it. I consider that worse as it is introducing multiple clicks, some of which require focus.
2. The issue posters may regress similarly as they won't have the standard output available, which they try to use heuristically. For example, will fatal errors or timeouts or panics still nicely surface in the issue post or will such problems be hidden behind an opaque "go to this artifact please" test failure?
3. why is any of this necessary? See below.

It's possible that the situation in 2) has overall gotten better (after all, the logs are often just gunk), but this would need to be validated in order to merge this.

re 3): note that there's already a mechanism here that massages the build log:

https://github.com/cockroachdb/cockroach/blob/4a72eb0f5420be23d084539de86e7d9f8ebf9998/build/teamcity-support.sh#L35-L82

`testfilter` is a tool that parses Go test json output. We invoke it such that TC never sees the output of passing tests:

https://github.com/cockroachdb/cockroach/blob/4a72eb0f5420be23d084539de86e7d9f8ebf9998/build/teamcity-support.sh#L47-L50

`-mode=strip` buffers the test output. When a test passes, it emits only the pass line (so that TC can time the test) but omits all other output. When the test fails, it is written out to TC and to an artifact that then powers the issue poster.

For debugging reasons, we also stream the unadulterated JSON output to a file (`${tmpfile}`), but delete it later if everything seems to have gone well.

I am probably missing something and this mechanism doesn't actually work as I describe it, for otherwise I don't understand why you felt that your work here was necessary at all.

**Comment by knz** [comment]
>  the TC UI will be less usable. At the moment, you can simply hover a failing test and click "copy stacktrace". In the new world, you expand and see "here's the log file!" and then you will navigate manually through the artifacts and open it. I consider that worse as it is introducing multiple clicks, some of which require focus.

The current status quo is that the "server log" portion of a test failures is multiple thousands of lines and makes the test result *already* unusable when it fails. 

In fact, having the test failure in the snippet only contain the test failure as reported by `t.Error` / `t.Fatal` / `t.Log` will be an improvement upon that, not a regression.

>  The issue posters may regress similarly as they won't have the standard output available, which they try to use heuristically. For example, will fatal errors or timeouts or panics still nicely surface in the issue post or will such problems be hidden behind an opaque "go to this artifact please" test failure?

The message that reports the location of the log directory generated by  `TestLogScope` can be parsed so that the issue poster can automatically grab the last 50 liens of the log file.

> why is any of this necessary? See below.

The main issue is that running tests locally (e.g. when trying to reproduce an issue, or stressing something), the server output generated with `make TESTFLAGS=-v` is simply obnoxious. 

The secondary issue is that the output of the test as generated by the `make test` command prior to filtering is ginormous, and that slows down the overall execution of the test.


Anyway, all this work is currently blocked on #50507 which I'd like you to have a look before we further this discussion.

**Comment by tbg** [comment]
These arguments work for me, but make sure they make it into the commits somewhere. I assumed you were trying to make "TC parse less logs" but it's already parsing few logs (I hope).

> The secondary issue is that the output of the test as generated by the make test command prior to filtering is ginormous, and that slows down the overall execution of the test.

Is this from your CI examination (can't find the email right now) or just a hunch? It's written to disk in both cases, though with this change across many more files (which should be slower). If disk I/O is not what throttles it then yes, we should get a speedup by piping much less into `testfilter` (and the pipe itself may be too narrow). I guess we'll just look at the CI speed on this PR to see if anything regressed.

**Comment by knz** [comment]
I re-arranged the datadriven verbosity as requested by Radu above. Now interactive runs via `make test` or `go test` will print out the details. Separately, the builder script as used in CI sets DATADRIVEN_QUIET_LOGS to make them more quiet.

RFAL

**Review by RaduBerinde — APPROVED** [review]
Awesome, thank you!

**Comment by tbg** [comment]
Thank you! LGTM conditional on everything looking good on CI

**Comment by knz** [comment]
The CI is fine. The test run went from 33 minutes to 31. (Not huge but we'll take whatever.)

**Comment by knz** [comment]
bors r=tbg,RaduBerinde

**Comment by andreimatei** [comment]
If a test fails because of a panic, you now don't see anything about the panic it in the console output. You just see something like:
```
--- FAIL: TestRangeCacheGeneration (0.01s)
    test_log_scope.go:77: test logs captured to: /var/folders/yn/8njyn10964d54h8t3h6j2lyh0000gp/T/logTestRangeCacheGeneration890850495
    test_log_scope.go:58: use -show-logs to present logs inline
    --- FAIL: TestRangeCacheGeneration/evict_0 (0.00s)
```

Would it be possible to get the stack trace in stderr?

**Comment by knz** [comment]
The stack trace is in cockroach-stderr.log. 

If you run interactively you can do what it says and pass -show-logs. Otherwise fetch the street log in artifacts.


Andrei Matei <notifications@github.com> schreef op 9 juli 2020 04:28:34 CEST:
>If a test fails because of a panic, you now don't see anything about
>the panic it in the console output. You just see something like:
>```
>--- FAIL: TestRangeCacheGeneration (0.01s)
>test_log_scope.go:77: test logs captured to:
>/var/folders/yn/8njyn10964d54h8t3h6j2lyh0000gp/T/logTestRangeCacheGeneration890850495
>    test_log_scope.go:58: use -show-logs to present logs inline
>    --- FAIL: TestRangeCacheGeneration/evict_0 (0.00s)
>```
>
>Would it be possible to get the stack trace in stderr?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cockroachdb/cockroach/pull/50506#issuecomment-655858747

-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by andreimatei** [comment]
I understand where to get the panic info, but I'm saying that it'd be nice if something about it was reflected in the console output, like it is for a `t.Fatal()`.

Another thing that I've ran into is that if I only run a single test with -v, I generally want to see its output. I'm thinking maybe it'd be a good idea for `make test` to automagically pass -show-logs if I specify both TESTS and a -v inside TESTFLAGS.

**Comment by andreimatei** [comment]
> I understand where to get the panic info, but I'm saying that it'd be nice if something about it was reflected in the console output, like it is for a t.Fatal().

I'm confused about why I don't see this line in the console:
https://github.com/cockroachdb/cockroach/blob/ef7ab9bc810fd4be7755ebf8880e36ace9453f4b/pkg/util/log/test_log_scope.go#L160

**Comment by tbg** [comment]
FYI Raphael and I chatted about this over lunch and he had the good idea of having `log.Scope` print the stderr file through `t` if it is nonempty.

**Comment by andreimatei** [comment]
Sounds good. I think there's another testimonial for the need to do something better with panics here: https://github.com/cockroachdb/cockroach/pull/50909#issuecomment-656229123

**Pull request merged**
