### PR TITLE
*: move all cockroach-authored go packages under '/pkg' prefix

### PR DESCRIPTION
**Pull request by dt**
okay, I'm still somewhat hesitant about this -- I liked our nice clean package names -- but per discussion on #4182, it might just be the least-bad approach, if we want to introduce vendoring, or any other non-cockroach-authored code, in the repo.

This move will make it easier to reference the set of all cockroach-authored code, e.g. for linters
or other tools that want to traverse it, if and when the repository root also contains packages
that are not authored by cockroach, such as a populated /vendor directory.

With all cockroach-authored packages living under the /pkg directory, linters can easily be run
against './pkg/...', or, for those that use a directory instead of go package spec, just './pkg'.

Individually tailoring each linter or tool invocation to first list all packages then filter out
those that are not desired (e.g. go list ./...|grep -v vendor) could lead to the same result, but
imposes a continuing cost on adding and maintaining those tools, while also adding a runtime cost
of traversing a much larger file system tree than needed, which is particularly acute in docker.

The name 'pkg' for such a prefix has existing precident in the etcd and kubernetes organizations,
and doesn't confuse tools looking for the GOPATH by searching for 'src' in the symbol (e.g. resolver.go).

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9844)

### CODE REVIEW

**Comment by dt** [comment]
(I don't actually want to merge this right now, just want to see how the CI feels about it.)

**Comment by tschottdorf** [comment]
The proto import paths changed:

```

[20:17:52][Step 2/3] make -C /go/src/github.com/cockroachdb/cockroach/pkg/.. -f cockroach/build/protobuf.mk
[20:17:52][Step 2/3] make[1]: cockroach/build/protobuf.mk: No such file or directory
[20:17:52][Step 2/3] make[1]: Entering directory '/go/src/github.com/cockroachdb/cockroach'
[20:17:52][Step 2/3] make[1]: *** No rule to make target 'cockroach/build/protobuf.mk'.  Stop.
[20:17:52][Step 2/3] make[1]: Leaving directory '/go/src/github.com/cockroachdb/cockroach'
[20:17:52][Step 2/3] Makefile:66: recipe for target 'generated/protos.d.ts' failed
[20:17:52][Step 2/3] make: *** [generated/protos.d.ts] Error 2
```

FWIW, I'm looking forward to this going in.

**Comment by dt** [comment]
finally, a green ci.

**Comment by dt** [comment]
I think I've ironed out all the hard-coded paths that were breaking various scripts and Makefiles so this is ready for wider commentary.

**Comment by bdarnell** [comment]
I'm not even going to try to look at that diff, but assuming it does what it says on the tin it LGTM.

**Comment by dt** [comment]
If anyone does want to look at any subsets of the diff, the interesting parts are probably style_test.go, Makefile, ui/Makefile, etc.

Other than the `git mv` and perl rewrite of go imports and a few full symbol names that were in protos, the by-hand changes in this diff are mostly making various `../../../` have one more set of `../` in them (cgo includes, ui makefiles, go generate calls, etc), and then making the linters and ci scripts happy.

`returncheck` is skipped for now since it hardcodes cockroachdb path -- I'll get that in a followup if this merges (we should probably pull it into our repo if it is going to hardcode our symbol names).

**Comment by dt** [comment]
(@RaduBerinde LGTM'ed this as well in slack)

**Comment by tamird** [comment]
Reviewed 2134 of 2146 files at r1, 11 of 660 files at r2.
Review status: 462 of 1089 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[.gitattributes, line 1 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9844#-KTu1iwQ2HZZ7ioI5hOr:-KTu1iwQ2HZZ7ioI5hOs:b-9rnewo) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ef38d72441225bc3c665af3ae4a2b74d64d93d5/.gitattributes#L1)):*
> ```
> *.pb.* -diff
> ```

shouldn't this file be in `pkg`?

---

*[GLOCKFILE, line 1 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9844#-KTu1qNUbHkbER-t9k7N:-KTu1qNUbHkbER-t9k7O:b-9rnewo) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ef38d72441225bc3c665af3ae4a2b74d64d93d5/GLOCKFILE#L1)):*
> ```
> cmd github.com/client9/misspell/cmd/misspell
> ```

shouldn't this file be in `pkg`?

---

*[main.go, line 26 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9844#-KTu22zriZ5syCnf51Kt:-KTu22zriZ5syCnf51Ku:b1opymv) ([raw file](https://github.com/cockroachdb/cockroach/blob/6baf076da4eb79bff5c6222a672cc8101e0a266d/main.go#L26)):*
> ```Go
> 	"os"
> 
> 	"github.com/cockroachdb/cockroach/pkg/cli"
> ```

shouldn't this file be in `pkg`? seems like we'd want this file linted, too.

---

*[build/protobuf.mk, line 26 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9844#-KTu2I0pY3Gh6aoKhDRx:-KTu2I0pY3Gh6aoKhDRy:b-bnsnrc) ([raw file](https://github.com/cockroachdb/cockroach/blob/6baf076da4eb79bff5c6222a672cc8101e0a266d/build/protobuf.mk#L26)):*
> ```Makefile
> PROTOBUF_ROOT  := $(GOGOPROTO_ROOT)/protobuf
> 
> NATIVE_ROOT := $(REPO_ROOT)/pkg/storage/engine/rocksdb
> ```

seems like replacing REPO_ROOT with PKG_ROOT would be clearer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9844)*

**Comment by dt** [comment]
Review status: 462 of 1089 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[.gitattributes, line 1 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9844#-KTu1iwQ2HZZ7ioI5hOr:-KTu4T8Pe-6b3OdXJGGS:b-57a8gq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ef38d72441225bc3c665af3ae4a2b74d64d93d5/.gitattributes#L1)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> shouldn't this file be in `pkg`?
</details>
Eh, I don't think it particularly needs to be? I think these are still reasonable repo-wide scm settings.

---

*[GLOCKFILE, line 1 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9844#-KTu1qNUbHkbER-t9k7N:-KTu4hqcv2lf6Oz0GxXZ:b-4lla38) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ef38d72441225bc3c665af3ae4a2b74d64d93d5/GLOCKFILE#L1)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> shouldn't this file be in `pkg`?
</details>
Don't think so? they're still our project-level deps (e.g. the tools are invoked from `build/`).

---

*[main.go, line 26 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9844#-KTu22zriZ5syCnf51Kt:-KTu4uSPd3ky6-ZUdyd3:b-weim6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/6baf076da4eb79bff5c6222a672cc8101e0a266d/main.go#L26)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> shouldn't this file be in `pkg`? seems like we'd want this file linted, too.
</details>
I think we want `cockroachdb/cockroach` to remain our go-gettable binary, not `pkg`, so we want *a* `main.go` here that produces that binary, right?

That said, yes, it won't get linted by default if we just lint the`pkg` tree, so we'll want it so ideally its just a tiny proxy to the real code... but it already essentially is that, just calling to `cli`, no?

---

*[build/protobuf.mk, line 26 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9844#-KTu2I0pY3Gh6aoKhDRx:-KTu5lj_u4c9zOpz45-C:bhy9ot6) ([raw file](https://github.com/cockroachdb/cockroach/blob/6baf076da4eb79bff5c6222a672cc8101e0a266d/build/protobuf.mk#L26)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> seems like replacing REPO_ROOT with PKG_ROOT would be clearer.
</details>
Will do.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9844)*

**Comment by tamird** [comment]
Review status: 462 of 1089 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[main.go, line 26 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9844#-KTu22zriZ5syCnf51Kt:-KTu7X07LM6NjI5UcocS:b-kuk373) ([raw file](https://github.com/cockroachdb/cockroach/blob/6baf076da4eb79bff5c6222a672cc8101e0a266d/main.go#L26)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> I think we want `cockroachdb/cockroach` to remain our go-gettable binary, not `pkg`, so we want *a* `main.go` here that produces that binary, right?
> 
> That said, yes, it won't get linted by default if we just lint the`pkg` tree, so we'll want it so ideally its just a tiny proxy to the real code... but it already essentially is that, just calling to `cli`, no?
</details>
`go get github.com/cockroachdb/cockroach` is a nice dream, but it doesn't do anything sensible; we want people building via the makefile, so actually it would be better that `go get` didn't try to compile the binary (and only downloaded the repo).

Anyway, I suppose I don't feel strongly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9844)*

**Pull request merged**
