### PR TITLE
sql: Expose methods rather than fields on types.T (patch 13/)

### PR DESCRIPTION
**Pull request by knz**
Split from #36598 cc @andy-kimball 

Do not export fields from InternalType as fields on types.T. Instead,
corresponding methods. This enables tighter control over how the fields
are set. In particular, the Unmarshal method and the pre-constructed types
can now guarantee that the Oid, Width, and Locale fields are properly
set. This better encapsulation makes it more difficult for callers to
accidentally construct invalid types, which is a real concern, given all
the subtle rules and usages of various Type objects across multiple
releases.

This change means that every types.T constructor now needs to call a
constructor method or use a pre-constructed type.

Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
:lgtm: very nice.

> Reviewed 157 of 157 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36710#-:-Lc61pTh4gI6yyU_e2ff:bhnhlfa)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/crdb_internal_test.go, line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36710#-Lc5zeTpB880w28NNzGF:-Lc5zeTpB880w28NNzGG:bx2mu6v) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e4acbc19f808c938d563a587dbe2f2b9927059c/pkg/sql/crdb_internal_test.go#L96)):*
> ```Go
> 	for i := range tableDesc.Columns {
> 		if tableDesc.Columns[i].Name == "k" {
> 			tableDesc.Columns[i].Type.InternalType.VisibleType = 4 // Pre-2.1 BIT.
> ```

Maybe use methods here too?
___
*[pkg/sql/crdb_internal_test.go, line 193 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36710#-Lc5zg4j6LLjiypiWWJ1:-Lc5zg4kEq5oanfd7SjK:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e4acbc19f808c938d563a587dbe2f2b9927059c/pkg/sql/crdb_internal_test.go#L193)):*
> ```Go
> 			// TODO(knz): post-2.2, visible types for integer types are gone.
> 			if col.Type.InternalType.VisibleType != 0 {
> 				t.Errorf("unexpected visible type: got %d, expected 0", col.Type.InternalType.VisibleType)
> ```

ditto
___
*[pkg/sql/distsql_physical_planner.go, line 3118 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36710#-Lc5zpL01Hcc4YN6P9Be:-Lc5zpL01Hcc4YN6P9Bf:b-i7tqbi) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e4acbc19f808c938d563a587dbe2f2b9927059c/pkg/sql/distsql_physical_planner.go#L3118)):*
> ```Go
> 		// 3. 'row_number' takes no arguments. We compute it and put the result
> 		//    in column 2.
> 		newResultTypes := make([]types.T, 0, len(plan.ResultTypes))
> ```

is it perhaps worth refactoring this API to use a `[]*types.T` instead of `[]types.T`?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36710)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/internal/client/db.go, line 236 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36710#-Lc64P7ZB5CYroFAWgNx:-Lc64P7ZB5CYroFAWgNy:b9rzcgt) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e4acbc19f808c938d563a587dbe2f2b9927059c/pkg/internal/client/db.go#L236)):*
> ```Go
> }
> 
> // InternalType returns the wrapped sender.
> ```

Change this comment back here.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36710)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @knz)

___
*[pkg/internal/client/db.go, line 236 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36710#-Lc64P7ZB5CYroFAWgNx:-Lccbv9c9URBh0XphfYz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e4acbc19f808c938d563a587dbe2f2b9927059c/pkg/internal/client/db.go#L236)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Change this comment back here.
</blockquote></details>

Done.
___
*[pkg/sql/crdb_internal_test.go, line 96 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36710#-Lc5zeTpB880w28NNzGF:-Lccc0f6-Fdjfdytaa9I:b-xrvonq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e4acbc19f808c938d563a587dbe2f2b9927059c/pkg/sql/crdb_internal_test.go#L96)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Maybe use methods here too?
</blockquote></details>

I felt like this code was doing "internal" stuff, so it was OK to poke into the internals like this. This is the only place outside `types` we ever do this. I'd rather not add a method, because it seems like an invitation for other code to use it. In general, I don't want any code outside the `types` package to reference `InternalType` in any way.
___
*[pkg/sql/distsql_physical_planner.go, line 3118 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36710#-Lc5zpL01Hcc4YN6P9Be:-LcccVkn4YLSrefnDuFp:b-ujj3xv) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e4acbc19f808c938d563a587dbe2f2b9927059c/pkg/sql/distsql_physical_planner.go#L3118)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

is it perhaps worth refactoring this API to use a `[]*types.T` instead of `[]types.T`?
</blockquote></details>

I think I addressed this in another one of the commits. I'd be concerned about the creation of a bunch of extra objects during `Unmarshal`. But I don't know for sure...

**Review by knz — COMMENTED** [review]
> Reviewed 34 of 34 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36710)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @RaduBerinde)

___
*[pkg/sql/distsql_physical_planner.go, line 3118 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36710#-Lc5zpL01Hcc4YN6P9Be:-LcfQ9NI8d7W3CtwFd6H:b-3v3xst) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e4acbc19f808c938d563a587dbe2f2b9927059c/pkg/sql/distsql_physical_planner.go#L3118)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I think I addressed this in another one of the commits. I'd be concerned about the creation of a bunch of extra objects during `Unmarshal`. But I don't know for sure...
</blockquote></details>

Maybe that's another example where a second look by @raduberinde and @jordanlewis would be warranted.

**Comment by knz** [comment]
@jordanlewis @RaduBerinde can you have a look at the changes in the `distsql_` files thanks

**Review by RaduBerinde — APPROVED** [review]
`distsql*` LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36710#-:-LcfhNC-3Y6c-0CZBrAV:br54835)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis)

___
*[pkg/sql/distsql_physical_planner.go, line 3118 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36710#-Lc5zpL01Hcc4YN6P9Be:-LcfgZge5X_36Jwb95Xo:boogfbv) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e4acbc19f808c938d563a587dbe2f2b9927059c/pkg/sql/distsql_physical_planner.go#L3118)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Maybe that's another example where a second look by @raduberinde and @jordanlewis would be warranted.
</blockquote></details>

I'm not sure either. The `*types.XX` everywhere are kind of annoying. I would file an issue for someone to investigate switching to `[]*T` later (and check some benchmarks).

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36710)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis)

___
*[pkg/sql/distsql_physical_planner.go, line 3118 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36710#-Lc5zpL01Hcc4YN6P9Be:-Lcft9pyA0V7mQP9q1Na:b6qzfb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e4acbc19f808c938d563a587dbe2f2b9927059c/pkg/sql/distsql_physical_planner.go#L3118)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I'm not sure either. The `*types.XX` everywhere are kind of annoying. I would file an issue for someone to investigate switching to `[]*T` later (and check some benchmarks).
</blockquote></details>

I filed #36909.

**Pull request closed without merging**
