### PR TITLE
cmd/prereqs: remove special chars from testdata

### LINKED ISSUE #33709: Tools that vendor cockroachdb cannot use go modules
Any tool that vendorize cockroachdb cannot migrate it's vendoring system from `dep` to `go mod` as it the following error:

```
go: downloading github.com/cockroachdb/cockroach v2.1.3+incompatible
-> unzip /Users/d.lopez/go/pkg/mod/cache/download/github.com/cockroachdb/cockroach/@v/v2.1.3+incompatible.zip: malformed file path "pkg/cmd/prereqs/testdata/src/example.com/specialchars/a[]*?~ $%#.go": invalid char '*'
```

Seems that the name of the file isn't supported by golang/zip, related issue:

https://github.com/golang/go/issues/28001

Please describe the issue you observed, and any steps we can take to reproduce it:

Clone any repository that vendorize cockroachdb and try to do a, for example:

https://github.com/lopezator/sqlfmt

And:

```
$ export GO111MODULE=on
$ go mod init
$ go build ./...
```
Build will throw the mentioned error.

**Expected behavior**

Being able to build/migrate projects that vendorize cockroachdb to modules.

**Fix**

Not sure what would be the better solution, but seems that the name of the affected test file must be changed.

### LINKED ISSUE #34380: build: Unable to clone repo on Windows
It is currently not possible to clone the git repo for Cockroach to a windows machine, due to a filename that contains several characters that are not valid in the windows filesystem:

`error: unable to create file pkg/cmd/prereqs/testdata/src/example.com/specialchars/a[]*?~ $%#.go: Invalid argument`

This precludes the ability to work with source code on a native Windows environment; builds are already not supported, but would be possible using the official Docker builder image or perhaps the Windows Subsystem for Linux.

### PR DESCRIPTION
**Pull request by petermattis**
Remove the file containing special chars from the testdata
directory. That file prevented git from checking out the cockroach repo
on windows, and also prevented the cockroach code base from being
zipped.

Fixes #33709
Fixes #34380

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]

**Comment by mjibson** [comment]
Yay we can use cockroach with go modules now.

**Comment by petermattis** [comment]
> Yay we can use cockroach with go modules now.

I haven't tested go modules. Can you actually verify they work after this PR merges?

**Comment by lopezator** [comment]
Thanks for this!

**Comment by mjibson** [comment]
I'll test after this merges, yes.

**Comment by petermattis** [comment]
bors r=tbg

**Comment by lopezator** [comment]
I was able to migrate my project that vendorize cockroachdb from dep to modules after this fix, thank you!

In case you find it useful for a modules migration, I found a little problem with MVS. Modules was selecting `github.com/cockroachdb/apd@v1.1.0` with this version, it throwed this error on build:

```
vendor/github.com/cockroachdb/cockroach/pkg/util/json/json.go:872:5: dec.SetFinite undefined (type apd.Decimal has no field or method SetFinite)
```

Forcing modules to use `github.com/cockroachdb/apd@v2.0.0` worked fine!

**Comment by petermattis** [comment]
@lopezator Thanks for checking!

**Comment by lopezator** [comment]
@petermattis update, binary builds fine, but it doesn't work:

It throws:

```
sqlfmt git:(master) ✗ ./bin/sqlfmt-v1.0.1-darwin-amd64
panic: unable to find base path for default call resolver, got /Users/me/go/pkg/mod

goroutine 1 [running]:
github.com/cockroachdb/cockroach/pkg/util/caller.glob..func1(0x1c9dd0b)
	/Users/me/go/pkg/mod/github.com/cockroachdb/cockroach-gen@v0.0.0-20190214143655-8e16789be0d2/pkg/util/caller/resolver.go:76 +0x589
```

I will need to investigate further. I'm playing in a branch, let's see if I find any solution.

**Comment by mjibson** [comment]
The apd module bug is known, I just need to like fix it: https://github.com/cockroachdb/apd/issues/83

**Pull request merged**
