### PR TITLE
storage: avoid boxing allocation in RangeDescriptor.Replicas

### PR DESCRIPTION
**Pull request by nvb**
f96e0f9 introduces a sorting step into MakeReplicaDescriptors, which is
called by `RangeDescriptor.Replicas`. Unfortunately the use of `sort.Interface`
here results in an allocation due to the interface boxing. This is very
noticable on both micro-benchmarks and system-level benchmarks. For
instance, on a large-scale, 192 vCPU kv90 test, this was responsible for
**1.84%** of all allocations in the system. The numbers are similar on
micro-benchmarks, where this PR has the following impact:

```
name                        old time/op    new time/op    delta
KV/Insert/Native/rows=1-16    94.5µs ± 4%    93.9µs ± 1%    ~     (p=0.684 n=10+10)

name                        old alloc/op   new alloc/op   delta
KV/Insert/Native/rows=1-16    11.6kB ± 0%    11.5kB ± 0%  -1.33%  (p=0.000 n=9+10)

name                        old allocs/op  new allocs/op  delta
KV/Insert/Native/rows=1-16       129 ± 0%       124 ± 0%  -3.88%  (p=0.000 n=9+9)
```

Release note: None

### CODE REVIEW

**Review by danhhz — COMMENTED** [review]
This approach seems fine to me, definitely preferable to implementing our own sort (even bubble sort). If we throw a comment on `MakeReplicaDescriptors(` explaining what's going on, I'm happy merging this

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38894#-:-LjvTF820unTe6GONPp3:b21o9qt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz and @nvanbenschoten)

___
*[pkg/roachpb/metadata_replicas.go, line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38894#-LjvT7dx9OEPxcyQTnI7:-LjvT7dx9OEPxcyQTnI8:b-ubf9oi) ([raw file](https://github.com/cockroachdb/cockroach/blob/0358fa14f18c9fe38ff54456c38e6ddad4c50695/pkg/roachpb/metadata_replicas.go#L110)):*
> ```Go
> 	d.wrapped = d.wrapped[:len(d.wrapped)-1]
> 	// The swap may have broken our sortedness invariant, so re-sort.
> 	sort.Sort((*byTypeThenReplicaID)(&d.wrapped))
> ```

checking my understanding: this still allocates, it just rarely gets called, correct?

**Review by nvb — COMMENTED** [review]
> If we throw a comment on MakeReplicaDescriptors( explaining what's going on, I'm happy merging this

Done. I also cleaned up the `RangeDescriptor` methods to make them all use pointer receivers instead of value receivers. See the second commit.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38894#-:-Lk7FatH7n7HeFIMxBGC:b-kar620)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz)

___
*[pkg/roachpb/metadata_replicas.go, line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38894#-LjvT7dx9OEPxcyQTnI7:-Lk7AVoA5HYe1ImxDktK:b1u2m51) ([raw file](https://github.com/cockroachdb/cockroach/blob/0358fa14f18c9fe38ff54456c38e6ddad4c50695/pkg/roachpb/metadata_replicas.go#L110)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

checking my understanding: this still allocates, it just rarely gets called, correct?
</blockquote></details>

Yes, this will cause the receiver to escape. Assuming that `*ReplicaDescriptors` is already on the heap, that's fine. However, it will cause an allocation if `*ReplicaDescriptors` was previously pointing to stack memory, as it will force that memory to be moved to the heap.

This is the case for the one call to this method in `*RangeDescriptor.RemoveReplica`, so there we're trading two allocations for one. If we really cared about the performance of that method then we could assign to `RangeDescriptor.InternalReplicas` before sorting (because `RangeDescriptor`s are pretty much always heap-allocated). I don't think it's worth it though, as I doubt that's called in any hot paths.

**Review by danhhz — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
