### PR TITLE
sql: fix an exported gist out of bounds error

### LINKED ISSUE #111346: Another exported gist failure
An index join wrapped in a group join results in an out of bounds exception.

Gist is: AgFWBgCPAQIAABNWCgsGBwwHHA0UAXoCBgEFUCJ6AQ==

Jira issue: CRDB-31865

### PR DESCRIPTION
**Pull request by cucaroach**
Fixes: #111346
Release note: None
Epic: None

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111347#-:-NfNX35d9AcFUaQ4aQNt:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2)

**Comment by rytaft** [comment]
blathers backport 23.1

**Comment by rytaft** [comment]
blathers backport 23.1.14-rc

**Pull request merged**
