### PR TITLE
sql: support FETCH FIRST syntax in SELECTs

### LINKED ISSUE #16034: sql: add support for "FETCH FIRST"
...for parity with PostgreSQL.

(yes, "LIMIT" is there, but existing applications might prefer "FETCH FIRST" because that apparently is what's in the standard)

See <https://issues.apache.org/jira/browse/OAK-6238> for context.

### PR DESCRIPTION
**Pull request by justinj**
Fixes #16034.

See https://www.postgresql.org/docs/10/static/sql-select.html.

### CODE REVIEW

**Comment by jordanlewis** [comment]
:lgtm:

This is some verbose syntax!

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16083#-:-Kkue_a9GYg24l402Bel:bh2yq61)*

**Comment by justinj** [comment]
It is definitely as SQL-y as SQL syntax gets.

**Comment by tamird** [comment]
No parser tests? Also, don't we want a different AST node for this so we can round trip it through the parser?

**Comment by knz** [comment]
Round trips through the parser is not a religious requirement I think. But yeah this could use a parser test indeed!

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16083#-:-KkwPwNU32wFW9pr0a-7:b6h6a99)*

**Pull request merged**
