### PR TITLE
cli: add debug_zip_command_flags.txt file in debug zip

### PR DESCRIPTION
**Pull request by aa-joshi**
Previously, debug zip doesn't have any way of determining the flags set during command execution. It is a pain point for support team to figure out flag values passesd during debug zip generation. To address this, we have added `debug_zip_command_flags.txt` file in debug zip. It captures flag values set during command execution.

Epic: CRDB-32134
Release note: None

### CODE REVIEW

**Review by arjunmahishi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129785)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aa-joshi and @angles-n-daemons)

___
*[`pkg/cli/zip.go` line 371 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129785#-O5Ni0qwCU57BuyA4gH4:-O5Ni0qwCU57BuyA4gH5:bmilxjc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f53d34b6589343585ad821c6782117ee8f89e176/pkg/cli/zip.go#L371)):*
> ```Go
> 
> 			s = zr.start("capture debug zip flags")
> 			if err := z.createJSON(s, zc.prefix+"/debug_zip_command_flags.json", zipCtx); err != nil {
> ```

Have you considered reading the provided args from `*cobra.Command`? it will have all the flags that the user passed. That would significantly reduce the size of the diff.

**Review by aa-joshi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129785)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @angles-n-daemons and @arjunmahishi)

___
*[`pkg/cli/zip.go` line 371 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129785#-O5Ni0qwCU57BuyA4gH4:-O5No9u_DPdld9xMfTcT:b-k663se) ([raw file](https://github.com/cockroachdb/cockroach/blob/f53d34b6589343585ad821c6782117ee8f89e176/pkg/cli/zip.go#L371)):*
<details><summary><i>Previously, arjunmahishi (Arjun Mahishi) wrote…</i></summary><blockquote>

Have you considered reading the provided args from `*cobra.Command`? it will have all the flags that the user passed. That would significantly reduce the size of the diff.
</blockquote></details>

Thanks for the suggestion! I did explore that cobra command. The challenge with that is we have to iterate over flags to fetch the value & dump into file.
Coming back to diff, The only change is to export field for generating json file. Most of the files are from test case updates.
I can split test & code changes in different commits.
Let me know your thoughts.

**Comment by arjunmahishi** [comment]
*[`pkg/cli/zip.go` line 371 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129785#-O5Ni0qwCU57BuyA4gH4:-O5OUQOw3IKzFmYKpwkD:bj5zl0j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f53d34b6589343585ad821c6782117ee8f89e176/pkg/cli/zip.go#L371)):*
> The challenge with that is we have to iterate over flags to fetch the value & dump into file.

Should be pretty straightforward. I think there is a helper function specifically built for this kind of usecase.

```golang
cmd.Flags().VisitAll(func(f *pflag.Flag) {
  if f.Changed {
    // this condition is true only if the user has set the flag
    // add to a string builder
  }
})
```

Other than the diff size, IMO this is a safer change. Sometime toggling a struct field between exporter/un-exported  can have unexpected side effects. 

Either way, I think it will be good to add a datadriven test that asserts the file generated.

**Review by aa-joshi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129785)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @angles-n-daemons and @arjunmahishi)

___
*[`pkg/cli/zip.go` line 371 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129785#-O5Ni0qwCU57BuyA4gH4:-O5SN03v0aTfKyGqheuw:b23oymy) ([raw file](https://github.com/cockroachdb/cockroach/blob/f53d34b6589343585ad821c6782117ee8f89e176/pkg/cli/zip.go#L371)):*
<details><summary><i>Previously, arjunmahishi (Arjun Mahishi) wrote…</i></summary><blockquote>

> The challenge with that is we have to iterate over flags to fetch the value & dump into file.

Should be pretty straightforward. I think there is a helper function specifically built for this kind of usecase.

```golang
cmd.Flags().VisitAll(func(f *pflag.Flag) {
  if f.Changed {
    // this condition is true only if the user has set the flag
    // add to a string builder
  }
})
```

Other than the diff size, IMO this is a safer change. Sometime toggling a struct field between exporter/un-exported  can have unexpected side effects. 

Either way, I think it will be good to add a datadriven test that asserts the file generated.
</blockquote></details>

Suggested changes are updated in latest commit. PTAL. TIA.

**Review by arjunmahishi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129785#-:-O5WbK_mEEroJ7PuppEl:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @aa-joshi and @angles-n-daemons)

___
*[`pkg/cli/zip.go` line 336 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129785#-O5Wb5oc7m4eMOOuIMgz:-O5Wb5oc7m4eMOOuIMh-:b522y4c) ([raw file](https://github.com/cockroachdb/cockroach/blob/c57e04527fbe285402bcadb7f73ce559e85d0c27/pkg/cli/zip.go#L336)):*
> ```Go
> 			// the profiles.
> 			{
> 				s := zc.clusterPrinter.start("pprof summary script")
> ```

Last question: Was this an intentional change? Removing the `:` (increasing the scope of `s`)

**Review by aa-joshi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129785)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @angles-n-daemons and @arjunmahishi)

___
*[`pkg/cli/zip.go` line 336 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129785#-O5Wb5oc7m4eMOOuIMgz:-O5lG8Wh-GRwKVBoCpjq:bx75zcj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c57e04527fbe285402bcadb7f73ce559e85d0c27/pkg/cli/zip.go#L336)):*
<details><summary><i>Previously, arjunmahishi (Arjun Mahishi) wrote…</i></summary><blockquote>

Last question: Was this an intentional change? Removing the `:` (increasing the scope of `s`)
</blockquote></details>

Yes, it is intentional. `nogo` was throwing error due to re initialisation of `s`.

**Comment by aa-joshi** [comment]
TFTR!

bors r+

**Comment by celiala** [comment]
> Build failed:
> - [unit_tests](https://github.com/cockroachdb/cockroach/actions/runs/10661522415/job/29547138920)

[unit_tests passed](https://github.com/cockroachdb/cockroach/actions/runs/10661522415) on re-try.

bors r+

**Pull request merged**
