### PR TITLE
sql: test backfills run smoothly in the presence of other operations

### PR DESCRIPTION
**Pull request by vivekmenezes**
This first tests that a schema change is unaffected by another schema
change that runs simultaneously. In the future it will also be used to check that
 various operations like INSERT do not affect the schema change.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5945)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/schema_changer_test.go, line 429 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5945#-KEq8YCMUVK4N5YiSZmF:-KEq8YCMUVK4N5YiSZmG:1884340542) ([raw file](https://github.com/cockroachdb/cockroach/blob/88c4337729d38fa510bd0194a541edd0fd16b0ac/sql/schema_changer_test.go#L429)):*
Looks odd to be inserting `max_value, 0` here. I would have inserted `0, max_value` and then looped from `i := 1; i <= max_value` below. Fine as is, though.

---

*[sql/schema_changer_test.go, line 433 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5945#-KEq8i3JL8wGMcGLEvnl:-KEq8i3JL8wGMcGLEvnm:-1331497553) ([raw file](https://github.com/cockroachdb/cockroach/blob/88c4337729d38fa510bd0194a541edd0fd16b0ac/sql/schema_changer_test.go#L433)):*
The semicolon isn't necessary. 

---

*[sql/schema_changer_test.go, line 522 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5945#-KEq9UmYT4iZMbwnGPRS:-KEq9UmYT4iZMbwnGPRT:762592228) ([raw file](https://github.com/cockroachdb/cockroach/blob/88c4337729d38fa510bd0194a541edd0fd16b0ac/sql/schema_changer_test.go#L522)):*
You should check that `rows.Err() == nil` here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5945#-:-KEq9jSkTI_1zxAA3t92:1417088721)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/schema_changer_test.go, line 429 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5945#-KEq8YCMUVK4N5YiSZmF:-KEqK7Q_YU5S1QyPOi3V:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/88c4337729d38fa510bd0194a541edd0fd16b0ac/sql/schema_changer_test.go#L429)):*
done

---

*[sql/schema_changer_test.go, line 433 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5945#-KEq8i3JL8wGMcGLEvnl:-KEqKOZnvzxHLs5zx8uP:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/88c4337729d38fa510bd0194a541edd0fd16b0ac/sql/schema_changer_test.go#L433)):*
done

---

*[sql/schema_changer_test.go, line 522 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5945#-KEq9UmYT4iZMbwnGPRS:-KEqL5vhXiiyQkBY7RAV:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/88c4337729d38fa510bd0194a541edd0fd16b0ac/sql/schema_changer_test.go#L522)):*
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5945)*

**Comment by RaduBerinde** [comment]
LGTM

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/schema_changer_test.go, line 520 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5945#-KEqSZNw6hfwbh0V97RG:-KEqSZNxL8_da5G9DdCF:-790417451) ([raw file](https://github.com/cockroachdb/cockroach/blob/f98e479882217063a7746ddefbe560111278daad/sql/schema_changer_test.go#L520)):*
Might be useful to use `Errorf` to see more of the messages if it ever fails

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5945#-:-KEqSqEGbVaP1bpuHAE8:676834233)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/schema_changer_test.go, line 520 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5945#-KEqSZNw6hfwbh0V97RG:-KEqUyV1Kkfgr9rP_cb6:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/f98e479882217063a7746ddefbe560111278daad/sql/schema_changer_test.go#L520)):*
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5945)*

**Pull request merged**
