### PR TITLE
sql: only create new txn for Bind if necessary

### PR DESCRIPTION
**Pull request by rafiss**
01ca1e53e2c84049abcf0f3d3acefa4bbbdb0db9 changed Bind so that it always
uses a transaction to resolve the arguments. This caused a performance
hit, leading to this code using 4.2% of the CPU utilization in a
read-only workload. To optimize the code, a new transaction is only
created when necessary, which is when we need to resolve user-defined
types or OID types.

No release note since the optimization only applies to unreleased
versions.

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
Do we also need one for evaluating the various oid types as cases. Like IIRC `SELECT $1::regclass` when you bind a string will do a catalog lookup. I could be wrong, but I recall this causing bugs in some very delicate edge cases where we fall back to avoiding the lease manager. Even when we don't it only subtly worked because the planner had not been reset and the committed previous transaction was used for the lease or something like that. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74423#-:-MskimuEC0VawfhpH0QL:b7mmkvr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Comment by rafiss** [comment]
Yeah, you're right. `pgwirebase.DecodeDatum` ends up calling `planner.ResolveOIDFromOID` which needs a transaction. I think the tests in `pkg/sql/pgwire/testdata/pgtest/bind_and_resolve` were supposed to cover this, but I guess they are getting lucky like you said.

**Comment by rafiss** [comment]
I added the check for OID types, but I still am not sure how to test it.

**Review by ajwerner — COMMENTED** [review]
The reason this worked before is pretty insane! It worked before because when we end up resolving the OID, we use the InternalExecutor, which, when it gets a nil txn uses its own. :frowning_face: 

https://github.com/cockroachdb/cockroach/blob/203c7f4ee3d5418ffe3211f8b7e2d9cd6211b0eb/pkg/sql/resolve_oid.go#L77-L78

Pretty wild. Having the internal executor optionally taking a transaction is a little crazy. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74423#-:-MuqpAIx1HAZ0f8TUdIa:bey1ay1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @rafiss)

___
*[pkg/sql/conn_executor_prepare.go, line 437 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74423#-MuqpqhZ1tfVR4hiFo_c:-MuqpqhZ1tfVR4hiFo_d:b-2rzc3t) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f77b90c7eafb6448eb0fbaad01eac00d069b93d/pkg/sql/conn_executor_prepare.go#L437)):*
> ```Go
> 			// Use the existing transaction.
> 			if err := resolve(ctx, txn); err != nil {
> 				return retErr(err)
> ```

Wait, if we have a txn, doesn't that mean the planner is already in a good state? Do we need to reset it and all that jazz?



_Code quote:_
```Go
			// Use the existing transaction.
			if err := resolve(ctx, txn); err != nil {
				return retErr(err)
			}
```

**Review by rafiss — COMMENTED** [review]
nice find on the internalExecutor! hm... 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74423#-:-Mv-ZulR0vbb3nHrPUJE:buhvlzh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/sql/conn_executor_prepare.go, line 437 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74423#-MuqpqhZ1tfVR4hiFo_c:-Mv-ZdUABrbz1Fp5CiDU:bu2bz4i) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f77b90c7eafb6448eb0fbaad01eac00d069b93d/pkg/sql/conn_executor_prepare.go#L437)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Wait, if we have a txn, doesn't that mean the planner is already in a good state? Do we need to reset it and all that jazz?
</blockquote></details>

good point .. i'll try moving the `resetPlanner` stuff into the branch where a new txn is created

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74423)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/sql/conn_executor_prepare.go, line 437 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74423#-MuqpqhZ1tfVR4hiFo_c:-MvonNifBe70Mn3HSq6U:b-mxw5k0) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f77b90c7eafb6448eb0fbaad01eac00d069b93d/pkg/sql/conn_executor_prepare.go#L437)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

good point .. i'll try moving the `resetPlanner` stuff into the branch where a new txn is created
</blockquote></details>

actually, i think it's fine to call `resetPlanner` each time. it's already called any time any pgwire command is exec'd. (e,g, we call `resetPlanner` in `execStmtInOpenState` even though there already is a txn.)

**Comment by rafiss** [comment]
This is ready for review. Given that this is just an optimization, and no existing tests regressed, I think I feel pretty safe about merging this.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74423#-:-Mw2WTi00O9n80a5u7mE:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @otan)

**Comment by rafiss** [comment]
tftr!

bors r=ajwerner

**Pull request merged**
