### PR TITLE
sql,server: remove automatic stats from SHOW JOBS and admin UI

### PR DESCRIPTION
**Pull request by rytaft**
This commit changes `SHOW JOBS` so it does not include automatic
statistics jobs. It also adds a new command `SHOW AUTOMATIC JOBS` which
can be used to view automatic statistics jobs.

This commit also changes the output in the Admin UI so that the
main jobs screen does not show automatic statistics. It is still
possible to see these jobs by selecting "Auto-Statistics Creation"
from the TYPE dropdown.

Informs #36027

Release note (sql change): Changed SHOW JOBS to no longer display
automatic statistics jobs. SHOW AUTOMATIC JOBS can now be used
instead to view automatic statistics jobs.

Release note (admin ui change): Changed the jobs screen in the
Admin UI to no longer show automatic statistics jobs. It is still
possible to see these jobs by selecting "Auto-Statistics Creation"
from the TYPE dropdown.

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:  Good changes!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36083#-:-LahIabH6TGfQpW9FYCc:bh938hc)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @danhhz, @dt, @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/sem/tree/show.go, line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36083#-LahHbYe8UPBwsWt1rsG:-LahHbYe8UPBwsWt1rsH:bho29uy) ([raw file](https://github.com/cockroachdb/cockroach/blob/5be90d51f7ef9bef434cf4f8ad758bd5124b289a/pkg/sql/sem/tree/show.go#L165)):*
> ```Go
> // ShowJobs represents a SHOW JOBS statement
> type ShowJobs struct {
> 	Automatic bool
> ```

[nit] add a comment. In particular it should be clear if this means "include automatic jobs" or "show only automatic jobs"

**Review by rytaft — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36083#-:-LahMOq693GgQBDaeq7B:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @danhhz, @dt, and @justinj)

___
*[pkg/sql/sem/tree/show.go, line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36083#-LahHbYe8UPBwsWt1rsG:-LahMKsoEPapC_VQUy6K:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5be90d51f7ef9bef434cf4f8ad758bd5124b289a/pkg/sql/sem/tree/show.go#L165)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] add a comment. In particular it should be clear if this means "include automatic jobs" or "show only automatic jobs"
</blockquote></details>

Done.

**Review by RaduBerinde — APPROVED** [review]
> Reviewed 10 of 11 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36083)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @danhhz, @dt, and @justinj)

**Comment by rytaft** [comment]
@dt or @danhhz do either of you have time to take a quick look at this today?

Also cc @celiala and @piyush-singh, sign-off from the Admin UI team would be appreciated too.

**Review by danhhz — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36083#-:-LaqBv7J7iXWWPmLFmZv:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @celiala, @danhhz, @dt, @justinj, and @RaduBerinde)

**Comment by rytaft** [comment]
Thanks!

**Review by celiala — APPROVED** [review]
:lgtm: -- nice! LGTM from AdminUI perspective.

**Comment by rytaft** [comment]
Thanks all!

bors r+

**Pull request merged**
