### PR TITLE
sql: add more testing for concurrent region/rbr interactions

### PR DESCRIPTION
**Pull request by arulajmani**
Informs #63462

This patch adds TestRegionAddDropEnclosingRegionalByRowOps, which
contains subtests with the following sketch:

- Client 1 performs an ALTER ADD / DROP REGION. Let the user txn commit.
- Block in the type schema changer.
- Client 2 performs an operation on a REGIONAL BY ROW table, such as creating
 an index, unique constraint, altering the primary key etc.
- Test both a rollback in the type schema changer and a successful execution.
- Ensure the partitions on the REGIONAL BY ROW table are sane.

Release note: None

### CODE REVIEW

**Review by otan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63804)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @arulajmani)

___
*[pkg/ccl/multiregionccl/region_test.go, line 478 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63804#-MYb3tTb1xKHJ7AVbM7p:-MYb3tTb1xKHJ7AVbM7q:blf3fd3) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa5c935359c367f31fa86839b75d7487959a254b/pkg/ccl/multiregionccl/region_test.go#L478)):*
> ```Go
> 					_, err := sqlDB.Exec(regionAlterCmd.cmd)
> 					if regionAlterCmd.shouldSucceed {
> 						require.NoError(t, err)
> ```

t.Fatal on a goroutine is apparently a no-no from my research, can we send an error to a waiting channel to be checked by the main channel?
___
*[pkg/ccl/multiregionccl/region_test.go, line 481 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63804#-MYb45tlDnvoeU4hmXKf:-MYb45tlDnvoeU4hmXKg:b-249789) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa5c935359c367f31fa86839b75d7487959a254b/pkg/ccl/multiregionccl/region_test.go#L481)):*
> ```Go
> 					} else {
> 						if !testutils.IsError(err, "boom") {
> 							t.Errorf("expected error boom, found %v", err)
> ```

probably should be the equivalent of `require.Truef(t, testutils.IsError(err, "boom") )`, but goroutine so should send it out.
___
*[pkg/ccl/multiregionccl/region_test.go, line 484 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63804#-MYb3mEp3Ir4BiXRkfUb:-MYb3mEp3Ir4BiXRkfUc:bqvju1q) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa5c935359c367f31fa86839b75d7487959a254b/pkg/ccl/multiregionccl/region_test.go#L484)):*
> ```Go
> 						}
> 					}
> 					typeChangeFinished <- struct{}{}
> ```

nit: can we defer this to prevent stuck routines? also, do you mind using close instead of send empty struct?
___
*[pkg/ccl/multiregionccl/region_test.go, line 536 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63804#-MYb4K_HDgxLprhRV5wx:-MYb4K_HDgxLprhRV5wy:b97lk24) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa5c935359c367f31fa86839b75d7487959a254b/pkg/ccl/multiregionccl/region_test.go#L536)):*
> ```Go
> 					return nil
> 				})
> 				<-typeChangeFinished
> ```

nit: can we defer this close

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63804)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @arulajmani)

___
*[pkg/ccl/multiregionccl/region_test.go, line 484 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63804#-MYb3mEp3Ir4BiXRkfUb:-MYb9vrX2P6_lYAkX6qC:bg11v7s) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa5c935359c367f31fa86839b75d7487959a254b/pkg/ccl/multiregionccl/region_test.go#L484)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nit: can we defer this to prevent stuck routines? also, do you mind using close instead of send empty struct?
</blockquote></details>

(i.e. defer func() { close (typeChangeFinished) }() at the beginning of the goroutine) 
___
*[pkg/ccl/multiregionccl/region_test.go, line 536 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63804#-MYb4K_HDgxLprhRV5wx:-MYb9r8QD9t5ysrDgbro:b-7krklq) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa5c935359c367f31fa86839b75d7487959a254b/pkg/ccl/multiregionccl/region_test.go#L536)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nit: can we defer this close
</blockquote></details>

oops, ignore this comment!

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63804)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/ccl/multiregionccl/region_test.go, line 478 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63804#-MYb3tTb1xKHJ7AVbM7p:-MYeOX8W2lwY5CnZr2MX:b-ooy47y) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa5c935359c367f31fa86839b75d7487959a254b/pkg/ccl/multiregionccl/region_test.go#L478)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

t.Fatal on a goroutine is apparently a no-no from my research, can we send an error to a waiting channel to be checked by the main channel?
</blockquote></details>

I'll just switch to using `t.Error` which I know is encouraged over `t.Fatal` in goroutines. 
___
*[pkg/ccl/multiregionccl/region_test.go, line 481 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63804#-MYb45tlDnvoeU4hmXKf:-MYeP0OrCiwTOUQryFos:bhx00go) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa5c935359c367f31fa86839b75d7487959a254b/pkg/ccl/multiregionccl/region_test.go#L481)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

probably should be the equivalent of `require.Truef(t, testutils.IsError(err, "boom") )`, but goroutine so should send it out.
</blockquote></details>

Errorf is fine, a linter told me once. 
___
*[pkg/ccl/multiregionccl/region_test.go, line 484 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63804#-MYb3mEp3Ir4BiXRkfUb:-MYeQ0y6BNDywQCfiA5O:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa5c935359c367f31fa86839b75d7487959a254b/pkg/ccl/multiregionccl/region_test.go#L484)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

(i.e. defer func() { close (typeChangeFinished) }() at the beginning of the goroutine) 
</blockquote></details>

Done!

**Comment by arulajmani** [comment]
CI failure is unlreated, gonna merge. TFTR!

bors r=otan

**Pull request merged**
