### PR TITLE
gc: end to end integration test

### LINKED ISSUE #84988: end-to-end test cases for GC are missing
As recently discovered requests were not sent for range tombstones if point keys were also not present in the requests (https://github.com/cockroachdb/cockroach/pull/84987).

This was leading to requests being dropped by GCer instead of sending them to replica.

We must have a cluster based test that would verify flow end to end.

Jira issue: CRDB-17988

Epic CRDB-2624

### PR DESCRIPTION
**Pull request by aliher1911**
Currently tests are covering various components, but there's no end to end flow test that would verify that GC will issue GC requests that would successfully remove all relevant data.
This commit adds a TestCluster based test to verify GC behaviour.

Release justification: test only change
Release note: None
Fixes #84988

### CODE REVIEW

**Comment by aliher1911** [comment]
Those were just minor tweaking of TestCluster settings and it looks like it passed all the stress and race. Should be ok to review.

**Review by tbg — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87516)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911)

___
*[`pkg/kv/kvserver/gc/gc_int_test.go` line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87516#-NBSBk7fBtCfTS-jXFTY:-NBSBk7fBtCfTS-jXFTZ:b27hg7h) ([raw file](https://github.com/cockroachdb/cockroach/blob/d01f9ee39f95e31be2b34c3631797778a96f2b9f/pkg/kv/kvserver/gc/gc_int_test.go#L73)):*
> ```Go
> 	statusServer := tc.Server(0).StatusServer().(serverpb.StatusServer)
> 
> 	execOrFatal := func(stmt string, args ...interface{}) {
> ```

Take `t *testing.T` here, and call `t.Helper()`, that way you can tell which caller fataled.
___
*[`pkg/kv/kvserver/gc/gc_int_test.go` line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87516#-NBSBoJIBMG7x0qwSvNs:-NBSBoJIBMG7x0qwSvNt:b-i92dh6) ([raw file](https://github.com/cockroachdb/cockroach/blob/d01f9ee39f95e31be2b34c3631797778a96f2b9f/pkg/kv/kvserver/gc/gc_int_test.go#L78)):*
> ```Go
> 	}
> 
> 	getTableRangeIDs := func(db *gosql.DB) ids {
> ```

Please pass `*testing.T` in all the methods and call `t.Helper`.
___
*[`pkg/kv/kvserver/gc/gc_int_test.go` line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87516#-NBSBrCsBPuLQwCllnhr:-NBSBrCsBPuLQwCllnhs:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/d01f9ee39f95e31be2b34c3631797778a96f2b9f/pkg/kv/kvserver/gc/gc_int_test.go#L91)):*
> ```Go
> 	}
> 
> 	readSomeKeys := func(db *gosql.DB) []int64 {
> ```

ditto
___
*[`pkg/kv/kvserver/gc/gc_int_test.go` line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87516#-NBSBry37E1jNn4u9Gr0:-NBSBry37E1jNn4u9Gr1:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/d01f9ee39f95e31be2b34c3631797778a96f2b9f/pkg/kv/kvserver/gc/gc_int_test.go#L103)):*
> ```Go
> 	}
> 
> 	getRangeInfo := func(rangeID int64, db *gosql.DB) (startKey, endKey []byte) {
> ```

ditto
___
*[`pkg/kv/kvserver/gc/gc_int_test.go` line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87516#-NBSBslt-RhoiVIUccJB:-NBSBslt-RhoiVIUccJC:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/d01f9ee39f95e31be2b34c3631797778a96f2b9f/pkg/kv/kvserver/gc/gc_int_test.go#L111)):*
> ```Go
> 	}
> 
> 	deleteRangeDataWithRangeTombstone := func(rangeIDs []int64, kvDb *kv.DB) {
> ```

ditto
___
*[`pkg/kv/kvserver/gc/gc_int_test.go` line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87516#-NBSBtHe4ObzEaWKZDll:-NBSBtHe4ObzEaWKZDlm:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/d01f9ee39f95e31be2b34c3631797778a96f2b9f/pkg/kv/kvserver/gc/gc_int_test.go#L119)):*
> ```Go
> 	}
> 
> 	getRangeStats := func(rangeID int64) enginepb.MVCCStats {
> ```

ditto
___
*[`pkg/kv/kvserver/gc/gc_int_test.go` line 129 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87516#-NBSBtlcAKjZjCGnKfz8:-NBSBtlcAKjZjCGnKfz9:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/d01f9ee39f95e31be2b34c3631797778a96f2b9f/pkg/kv/kvserver/gc/gc_int_test.go#L129)):*
> ```Go
> 	}
> 
> 	findNonEmptyRanges := func(rangeIDs ids) (nonEmptyRangeIDs ids) {
> ```

ditto
___
*[`pkg/kv/kvserver/gc/gc_int_test.go` line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87516#-NBSD8FzA34JnwNW2Fv0:-NBSD8FzA34JnwNW2Fv1:b-jcisan) ([raw file](https://github.com/cockroachdb/cockroach/blob/d01f9ee39f95e31be2b34c3631797778a96f2b9f/pkg/kv/kvserver/gc/gc_int_test.go#L132)):*
> ```Go
> 		for _, id := range rangeIDs {
> 			stats := getRangeStats(id)
> 			t.Logf("range %d stats: %s", id, &stats)
> ```

Need to check somewhere that `ContainsEstimates` is false.
___
*[`pkg/kv/kvserver/gc/gc_int_test.go` line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87516#-NBSCWuL33eHxdTKk1lx:-NBSCWuL33eHxdTKk1ly:besiuku) ([raw file](https://github.com/cockroachdb/cockroach/blob/d01f9ee39f95e31be2b34c3631797778a96f2b9f/pkg/kv/kvserver/gc/gc_int_test.go#L165)):*
> ```Go
> 	require.Empty(t, readSomeKeys(sqlDb), "table still contains data after range deletion")
> 
> 	execOrFatal(`alter table kv split at values ($1)`, math.MaxInt64/2)
> ```

Why? And why now?

**Review by aliher1911 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87516)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911 and @tbg)

___
*[`pkg/kv/kvserver/gc/gc_int_test.go` line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87516#-NBSD8FzA34JnwNW2Fv0:-NBSGZXW9VfJVn3BKyhr:bh1xre) ([raw file](https://github.com/cockroachdb/cockroach/blob/d01f9ee39f95e31be2b34c3631797778a96f2b9f/pkg/kv/kvserver/gc/gc_int_test.go#L132)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Need to check somewhere that `ContainsEstimates` is false.
</blockquote></details>

Can we have `ContainsEstimates` true here? I thought they are produced by imports and the such operations. If there are estimates, we won't be able to assert the test result and we can't reasonably recover. We can fail the whole test though.
___
*[`pkg/kv/kvserver/gc/gc_int_test.go` line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87516#-NBSCWuL33eHxdTKk1lx:-NBSG8-2BWLHan8Hxl9Q:b-8je28l) ([raw file](https://github.com/cockroachdb/cockroach/blob/d01f9ee39f95e31be2b34c3631797778a96f2b9f/pkg/kv/kvserver/gc/gc_int_test.go#L165)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Why? And why now?
</blockquote></details>

Checking that range that was split by range split is still deleted correctly.

**Review by tbg — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87516)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911)

___
*[`pkg/kv/kvserver/gc/gc_int_test.go` line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87516#-NBSD8FzA34JnwNW2Fv0:-NBSUZeb6jW1b9lGfLcm:b-ejy7yb) ([raw file](https://github.com/cockroachdb/cockroach/blob/d01f9ee39f95e31be2b34c3631797778a96f2b9f/pkg/kv/kvserver/gc/gc_int_test.go#L132)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

Can we have `ContainsEstimates` true here? I thought they are produced by imports and the such operations. If there are estimates, we won't be able to assert the test result and we can't reasonably recover. We can fail the whole test though.
</blockquote></details>

Right, just assert it's false basically.
___
*[`pkg/kv/kvserver/gc/gc_int_test.go` line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87516#-NBSCWuL33eHxdTKk1lx:-NBSUesqBGaFXEKH0WSe:b5q6fy8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d01f9ee39f95e31be2b34c3631797778a96f2b9f/pkg/kv/kvserver/gc/gc_int_test.go#L165)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

Checking that range that was split by range split is still deleted correctly. 
</blockquote></details>

Maybe add a comment, seems kind of unclear why, but it doesn't hurt either. Is there any interaction with splits that is interesting here? You push them through the queue separately, so it looks the same to me, just doing it twice rather than once.

**Review by tbg — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87516)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911)

**Review by aliher1911 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87516)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[`pkg/kv/kvserver/gc/gc_int_test.go` line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87516#-NBSBoJIBMG7x0qwSvNs:-NBTIntLBYGxlivLiiXq:bdz6sqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/d01f9ee39f95e31be2b34c3631797778a96f2b9f/pkg/kv/kvserver/gc/gc_int_test.go#L78)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Please pass `*testing.T` in all the methods and call `t.Helper`.
</blockquote></details>

What is the benefit of passing t to every helper lambda here, to avoid accessing variables from outer scope? Currently it's a mixed bag, some functions receive connection and some use it from test function itself, I'll fix that as well then.
___
*[`pkg/kv/kvserver/gc/gc_int_test.go` line 165 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87516#-NBSCWuL33eHxdTKk1lx:-NBTHwRoD8mgsjUF01zR:bri7hep) ([raw file](https://github.com/cockroachdb/cockroach/blob/d01f9ee39f95e31be2b34c3631797778a96f2b9f/pkg/kv/kvserver/gc/gc_int_test.go#L165)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Maybe add a comment, seems kind of unclear why, but it doesn't hurt either. Is there any interaction with splits that is interesting here? You push them through the queue separately, so it looks the same to me, just doing it twice rather than once.
</blockquote></details>

You are right, I now think it doesn't belong here. Updating stats should be tested on split/merge separately.

**Comment by aliher1911** [comment]
bors r=tbg

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87516)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[`pkg/kv/kvserver/gc/gc_int_test.go` line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/87516#-NBSBoJIBMG7x0qwSvNs:-NBWl5Wy5mqJF2ktHAqT:bswkzqh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d01f9ee39f95e31be2b34c3631797778a96f2b9f/pkg/kv/kvserver/gc/gc_int_test.go#L78)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

What is the benefit of passing t to every helper lambda here, to avoid accessing variables from outer scope? Currently it's a mixed bag, some functions receive connection and some use it from test function itself, I'll fix that as well then.
</blockquote></details>

https://play.golang.com/p/hWebTlxd9Nk

It makes sure that the errors that get created are made to originate from the line of the caller, not the line of the helper. Note how the calls to `badHelper` can't be traced back to where they were called from.
This is less of an issue with using `require` because that always logs a stack trace anyway, but it's better to pass `t` explicitly just as muscle memory, since not everything uses `require`.

**Comment by aliher1911** [comment]
I don't need to pass t to make helper work as I think it .Helper() only ensures stack frames where helper was invoked are ignored:
https://play.golang.com/p/LREvYRQC5aQ

So we can achieve the same with just using t from main test function. I'm more interested in, if I pass t, then I'd rather pass everything and make this a proper function. I don't see why t has any special meaning here. Either go full on with inheriting everything or pass everything every time. Imho for function literals there's little benefit of passing all shared variables as you will always pass the same values within context of your test anyways.

**Comment by erikgrinaker** [comment]
This only seems to test the range tombstone full-range fast path? Shouldn't we also, at minimum, test that point keys and range keys are GCed correctly, both for updates and deletes?

**Pull request merged**
