### PR TITLE
storage: Update range/lease counts in store pool upon transfers

### PR DESCRIPTION
**Pull request by a-robinson**
We were already doing this for other stats such as qps, but had left out
the range and lease counts themselves. It's worth keeping those up to
date as well.

Release note: None

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm:

Do you expect this to improve anything?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29370#-:-LLBLmNV7AAE307PQerZ:bnxccxc)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by a-robinson — COMMENTED** [review]
> Do you expect this to improve anything?

It's not fixing any specific real-world issue that we've observed, but we do use range/lease counts when making rebalancing decisions so having them be more accurate is beneficial to avoid overcorrecting in any particular direction. Without this, there's a pretty good chance that we'll send a few too many replicas/leases to an underfull node or rebalance too many off an overfull node based on stale data before getting a gossip update with the updated value.

That was observed to be a noticeable problem in stats-based rebalancing when moving ranges with high qps/wps, which is why we added the code in the first place. Moving an extra couple ranges/leases is less of a big deal, but still not really what we want.

I notice now, though, that this breaks the mammoth `Example_rebalancing` test, which is something I was hoping I'd never have to update. I'll take a manual look through to verify that the changes to it are all desirable.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29370#-:-LLBMbq_6fdbXkfTfbOk:bgmmzi8)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by a-robinson — COMMENTED** [review]
I've manually confirmed that the new `Example_rebalancing` output is desirable -- the main difference is that the rebalancing process is smoother - all the underfull stores gain replicas at roughly the same rate now, rather than spiky growth on just a couple stores at a time.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29370#-:-LLBdHbiAxBcha9rR9w8:bm9xmrz)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by petermattis — APPROVED** [review]
Still :lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29370#-:-LLBfyc2-pC-Lf1UFmf9:b-2pygyf)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
