### PR TITLE
tpcc: performance work for making fixture generation faster

### PR DESCRIPTION
**Pull request by danhhz**
See individual commits for details

### CODE REVIEW

**Comment by danhhz** [comment]
Just finished a 4 node `./workload fixtures make tpcc --warehouses=500` in 40m10s with this change

**Comment by jordanlewis** [comment]
Nice. That's a 33% improvement from the ~ 1 hour time I saw previously.

**Comment by jordanlewis** [comment]
:lgtm: besides my one comment

---

Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/workload/csv.go, line 60 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/23564#-L71aF7pyCKujJ3Td0iy:-L71aF7pyCKujJ3Td0iz:bheuxm8) ([raw file](https://github.com/cockroachdb/cockroach/blob/da5ddc37c6a8238210cee7dec13a6b26f7ec06d4/pkg/workload/csv.go#L60)):*
> ```Go
> 			rowStrings = rowStrings[:len(row)]
> 		}
> 		rowStrings := make([]string, len(row))
> ```

this looks like an error - doesn't this shadow your cache?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23564#-:-L71aTmdkTwPkW_FRPop:b-cgeywp)*

**Comment by danhhz** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/workload/csv.go, line 60 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/23564#-L71aF7pyCKujJ3Td0iy:-L756i-X-QKD9oTMdjPI:blixk3j) ([raw file](https://github.com/cockroachdb/cockroach/blob/da5ddc37c6a8238210cee7dec13a6b26f7ec06d4/pkg/workload/csv.go#L60)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

this looks like an error - doesn't this shadow your cache?
</blockquote></details>

Good catch, done! Numbers got a little better

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23564)*

**Pull request merged**
