### PR TITLE
storage: first pass splitting replica.go

### PR DESCRIPTION
**Pull request by tbg**
This is a coarse splitting of replica.go. Opening the file, the reader is now
guided towards `Send` which links further into `replica_{read,write}.go` which
are more distraction-free than the main file.

Things are still a mess, but this seems to be a step up.

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
PS rather than discussing individual movements here I'd rather merge this and send more follow-up work.

**Review by andreimatei — DISMISSED** [review]
LGTM but there's several `.go.go` out of which one I think is a duplicate and also a `.go.foo`.

Good initiative! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33711#-:-LWCTq_O7TowgBLX0Pak:b-babfly)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica.go.foo, line 0 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/33711#-LWCTx7F0u-ryXXKLnj0:-LWCTx7F0u-ryXXKLnj1:b-jfpuzm) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cdd75720d5b8e5cca109bc28549430de36b5d89/pkg/storage/replica.go.foo#L0)):*
what's up with this file
___
*[pkg/storage/replica_evaluate.go.go, line 1 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/33711#-LWCUYdq5SPxpTStR9Z3:-LWCUYdq5SPxpTStR9Z4:bhoicud) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cdd75720d5b8e5cca109bc28549430de36b5d89/pkg/storage/replica_evaluate.go.go#L1)):*
> ```Go
> // Copyright 2019 The Cockroach Authors.
> ```

.go.go
___
*[pkg/storage/replica_raft.go.go, line 1 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/33711#-LWCUgLXDFtv6hFc4qV0:-LWCUgLXDFtv6hFc4qV1:b3kqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cdd75720d5b8e5cca109bc28549430de36b5d89/pkg/storage/replica_raft.go.go#L1)):*
> ```Go
> // Copyright 2019 The Cockroach Authors.
> ```

.
___
*[pkg/storage/replica_range_lease.go.go, line 1 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/33711#-LWCUaxp-W4LYVaF5Vhc:-LWCUaxp-W4LYVaF5Vhd:b2ngvlb) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cdd75720d5b8e5cca109bc28549430de36b5d89/pkg/storage/replica_range_lease.go.go#L1)):*
> ```Go
> // Copyright 2019 The Cockroach Authors.
> ```

,go
___
*[pkg/storage/replica_read.go, line 1 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/33711#-LWCUc8G13kZRkca0yTE:-LWCUc8G13kZRkca0yTF:b3kqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cdd75720d5b8e5cca109bc28549430de36b5d89/pkg/storage/replica_read.go#L1)):*
> ```Go
> // Copyright 2019 The Cockroach Authors.
> ```

.
___
*[pkg/storage/replica_write.go.go, line 1 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/33711#-LWCU2lK8q_2EBZp3Be3:-LWCU2lK8q_2EBZp3Be4:b-yad8tb) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cdd75720d5b8e5cca109bc28549430de36b5d89/pkg/storage/replica_write.go.go#L1)):*
> ```Go
> // Copyright 2019 The Cockroach Authors.
> ```

what's up with this file?

**Review by petermattis — COMMENTED** [review]
Ditto what @andreimatei said. The direction looks good, but there are some weird suffixes in here. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33711#-:-LWCV6BODUibZASK10JE:b-ww5rn2)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by tbg — COMMENTED** [review]
Sorry about the crappy commits. I used `git add .` at some point which is just always a bad idea. The `.go.go` files snuck in because I used GoLand's refactor feature which annoyingly auto-appends `.go`.

bors r=petermattis,andreimatei

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33711#-:-LWDKKaKDPvWrf20qLzc:bz01ppy)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica_read.go, line 1 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/33711#-LWCUc8G13kZRkca0yTE:-LWDIpoq3NiI5Kp5pdZk:b-umyxq0) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cdd75720d5b8e5cca109bc28549430de36b5d89/pkg/storage/replica_read.go#L1)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

.
</blockquote></details>

What's to see here?
___
*[pkg/storage/replica.go.foo, line  at r16](https://reviewable.io/reviews/cockroachdb/cockroach/33711#-LWCTx7F0u-ryXXKLnj0:-LWDIg6J0NZH3rnsAFff:b-4wrax2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cdd75720d5b8e5cca109bc28549430de36b5d89/pkg/storage/replica.go.foo#L)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

what's up with this file
</blockquote></details>

Happy little accident.
___
*[pkg/storage/replica_evaluate.go.go, line 1 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/33711#-LWCUYdq5SPxpTStR9Z3:-LWDIkHP447TwUg9lGzd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cdd75720d5b8e5cca109bc28549430de36b5d89/pkg/storage/replica_evaluate.go.go#L1)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

.go.go
</blockquote></details>

Done.
___
*[pkg/storage/replica_raft.go.go, line 1 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/33711#-LWCUgLXDFtv6hFc4qV0:-LWDIkvJEQIqEwttFIHW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cdd75720d5b8e5cca109bc28549430de36b5d89/pkg/storage/replica_raft.go.go#L1)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[pkg/storage/replica_range_lease.go.go, line 1 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/33711#-LWCUaxp-W4LYVaF5Vhc:-LWDIlQr0yWNEe5b430N:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cdd75720d5b8e5cca109bc28549430de36b5d89/pkg/storage/replica_range_lease.go.go#L1)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

,go
</blockquote></details>

Done.
___
*[pkg/storage/replica_write.go.go, line 1 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/33711#-LWCU2lK8q_2EBZp3Be3:-LWDIrD791k-MHfDTeS3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4cdd75720d5b8e5cca109bc28549430de36b5d89/pkg/storage/replica_write.go.go#L1)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

what's up with this file?
</blockquote></details>

Done.

**Pull request merged**
