### PR TITLE
sql: add missing columns to information_schema.columns

### PR DESCRIPTION
**Pull request by jordanlewis**
It was missing several columns that the version of Postgres we claim
support for has.

Release note (sql change): add missing columns to
information_schema.columns

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Cool this is going to help much!

Please list the new columns in the release note. There are users who are waiting for this and that will ensure they get the information without having to fish for the PR.

> Reviewed 2 of 2 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37271#-:-Ldu7-vm4TMQejl-tPHL:b4f45zk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @knz)

___
*[pkg/sql/information_schema.go, line 334 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37271#-Ldu7cWa0X_fDnmVDcKw:-Ldu7cWa0X_fDnmVDcKx:b-8owd7w) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1aca01ca3b2468ec7fc63cd6fae659c013e11f2/pkg/sql/information_schema.go#L334)):*
> ```Go
> 					tree.DNull,                                           // character_set_schema
> 					tree.DNull,                                           // character_set_name
> 					tree.DNull,                                           // collation_catalog
> ```

for collated strings I think that's `dbNameStr`
___
*[pkg/sql/information_schema.go, line 335 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37271#-Ldu7fHR1sNAoEuf7FAA:-Ldu7fHR1sNAoEuf7FAB:b-rq47dr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1aca01ca3b2468ec7fc63cd6fae659c013e11f2/pkg/sql/information_schema.go#L335)):*
> ```Go
> 					tree.DNull,                                           // character_set_name
> 					tree.DNull,                                           // collation_catalog
> 					tree.DNull,                                           // collation_schema
> ```

collated strings has `tree.PublicSchemaName` or the datum equivalent
___
*[pkg/sql/information_schema.go, line 336 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37271#-Ldu7h_j3QSArsXZWj7b:-Ldu7h_j3QSArsXZWj7c:b-6wz0qa) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1aca01ca3b2468ec7fc63cd6fae659c013e11f2/pkg/sql/information_schema.go#L336)):*
> ```Go
> 					tree.DNull,                                           // collation_catalog
> 					tree.DNull,                                           // collation_schema
> 					tree.DNull,                                           // collation_name
> ```

this you can fish from the column descriptor
___
*[pkg/sql/information_schema.go, line 340 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37271#-Ldu7zYXEqyJvXw6pZja:-Ldu7zYXEqyJvXw6pZjb:bqcbhjx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1aca01ca3b2468ec7fc63cd6fae659c013e11f2/pkg/sql/information_schema.go#L340)):*
> ```Go
> 					tree.DNull,                                           // domain_schema
> 					tree.DNull,                                           // domain_name
> 					tree.DNull,                                           // udt_catalog
> ```

`dbNameStr` here
___
*[pkg/sql/information_schema.go, line 341 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37271#-Ldu8-cTDy88SbcOQbo_:-Ldu8-cTDy88SbcOQboa:bhqr0oq) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1aca01ca3b2468ec7fc63cd6fae659c013e11f2/pkg/sql/information_schema.go#L341)):*
> ```Go
> 					tree.DNull,                                           // domain_name
> 					tree.DNull,                                           // udt_catalog
> 					tree.DNull,                                           // udt_schema
> ```

PublicSchemaName
___
*[pkg/sql/information_schema.go, line 342 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37271#-Ldu80jdAu57XqozoZlR:-Ldu80jdAu57XqozoZlS:b9mog8f) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1aca01ca3b2468ec7fc63cd6fae659c013e11f2/pkg/sql/information_schema.go#L342)):*
> ```Go
> 					tree.DNull,                                           // udt_catalog
> 					tree.DNull,                                           // udt_schema
> 					tree.DNull,                                           // udt_name
> ```

`ColumnType.Oid().String()` maybe?
___
*[pkg/sql/information_schema.go, line 356 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37271#-Ldu7RNh9AyBzlVazHbV:-Ldu7RNh9AyBzlVazHbW:bd28hg2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1aca01ca3b2468ec7fc63cd6fae659c013e11f2/pkg/sql/information_schema.go#L356)):*
> ```Go
> 					tree.DNull,                                           // identity_minimum
> 					tree.DNull,                                           // identity_cycle
> 					tree.DNull,                                           // is_generated
> ```

I think this is `yesOrNoDatum(column.ComputeExpr != nil)` 
___
*[pkg/sql/information_schema.go, line 358 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37271#-Ldu7H3hATUJMnl6zzSh:-Ldu7H3hATUJMnl6zzSi:b-nvxipa) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1aca01ca3b2468ec7fc63cd6fae659c013e11f2/pkg/sql/information_schema.go#L358)):*
> ```Go
> 					tree.DNull,                                           // is_generated
> 					dStringPtrOrEmpty(column.ComputeExpr),                // generation_expression
> 					yesOrNoDatum(!table.IsView()),                        // is_updatable
> ```

`table.IsTable()` may be better here? What's your rationale for using `!IsView()`?
___
*[pkg/sql/vtable/information_schema.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37271#-Ldu79Ni6I2nXARG4kv2:-Ldu79Ni6I2nXARG4kv3:befiecv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1aca01ca3b2468ec7fc63cd6fae659c013e11f2/pkg/sql/vtable/information_schema.go#L52)):*
> ```Go
>   UDT_NAME                 STRING,
>   SCOPE_CATALOG            STRING,
>   SCOPE_SCHEMA             STRING,
> ```

there's some whitespace issue at the start of all the new lines

**Review by knz — COMMENTED** [review]
Maybe also make sure there's a test that demonstrates the values populated in these new columns (e.g. a table with a collated string column and a computed column, and perhaps a few different types to show how `udt_name` gets populated.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37271#-:-Ldu9PqpD1iXDYvYVVCz:b8n6q3x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @knz)

**Review by jordanlewis — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37271#-:-LduHRQF0IEfdnPM50yC:b-896fix)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @knz)

___
*[pkg/sql/information_schema.go, line 335 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37271#-Ldu7fHR1sNAoEuf7FAA:-LduHNB1CPuy-GYM_Eaq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1aca01ca3b2468ec7fc63cd6fae659c013e11f2/pkg/sql/information_schema.go#L335)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

collated strings has `tree.PublicSchemaName` or the datum equivalent
</blockquote></details>

Done.
___
*[pkg/sql/information_schema.go, line 336 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37271#-Ldu7h_j3QSArsXZWj7b:-LduHNQt5HroivO1JF0g:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1aca01ca3b2468ec7fc63cd6fae659c013e11f2/pkg/sql/information_schema.go#L336)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

this you can fish from the column descriptor
</blockquote></details>

Done.
___
*[pkg/sql/information_schema.go, line 340 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37271#-Ldu7zYXEqyJvXw6pZja:-LduHO3tA0kIvs5HdV74:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1aca01ca3b2468ec7fc63cd6fae659c013e11f2/pkg/sql/information_schema.go#L340)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`dbNameStr` here
</blockquote></details>

Done.
___
*[pkg/sql/information_schema.go, line 341 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37271#-Ldu8-cTDy88SbcOQbo_:-LduHOS34wkUePHCIsVP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1aca01ca3b2468ec7fc63cd6fae659c013e11f2/pkg/sql/information_schema.go#L341)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

PublicSchemaName
</blockquote></details>

Done.
___
*[pkg/sql/information_schema.go, line 342 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37271#-Ldu80jdAu57XqozoZlR:-LduHOjoDYGlUaw7MKul:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1aca01ca3b2468ec7fc63cd6fae659c013e11f2/pkg/sql/information_schema.go#L342)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`ColumnType.Oid().String()` maybe?
</blockquote></details>

Done.
___
*[pkg/sql/information_schema.go, line 356 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37271#-Ldu7RNh9AyBzlVazHbV:-LduHPK29GHap5zcD8Nw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1aca01ca3b2468ec7fc63cd6fae659c013e11f2/pkg/sql/information_schema.go#L356)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think this is `yesOrNoDatum(column.ComputeExpr != nil)` 
</blockquote></details>

Done.
___
*[pkg/sql/information_schema.go, line 358 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37271#-Ldu7H3hATUJMnl6zzSh:-LduHPiQ01um2rmYeFQF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1aca01ca3b2468ec7fc63cd6fae659c013e11f2/pkg/sql/information_schema.go#L358)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`table.IsTable()` may be better here? What's your rationale for using `!IsView()`?
</blockquote></details>

Done.
___
*[pkg/sql/vtable/information_schema.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37271#-Ldu79Ni6I2nXARG4kv2:-LduHQhP3r7hN-CofUJ9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1aca01ca3b2468ec7fc63cd6fae659c013e11f2/pkg/sql/vtable/information_schema.go#L52)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

there's some whitespace issue at the start of all the new lines
</blockquote></details>

Done.

**Review by knz — APPROVED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37271)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Pull request merged**
