### PR TITLE
kubernetes: Always create default namespace svc in multi-region setup

### PR DESCRIPTION
**Pull request by a-robinson**
Previously we left it as an extra manual task, but there's no great
reason not to just automate it for people.

Release note: None

### CODE REVIEW

**Comment by mberhault** [comment]
LGTM

**Comment by a-robinson** [comment]
TFTR!

bors r+

**Comment by knz** [comment]
this probably wants a backport

**Comment by a-robinson** [comment]
Does it? We don't typically backport kubernetes configs. If this does then there are a half-dozen other PRs we'd want to backport along with it.

**Pull request merged**
