### PR TITLE
testing: add table id placeholder in multi-node SQLTranslator tests

### LINKED ISSUE #110093: pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/spanconfigsqltranslatorccl_test: TestDataDriven failed
pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/spanconfigsqltranslatorccl_test.TestDataDriven [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/11646697?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/11646697?buildTab=artifacts#/) on master @ [ad4e53f6b4dda9a76c60d4fe52f6f9d7c6afde2a](https://github.com/cockroachdb/cockroach/commits/ad4e53f6b4dda9a76c60d4fe52f6f9d7c6afde2a):

```
=== RUN   TestDataDriven
    test_log_scope.go:167: test logs captured to: /artifacts/tmp/_tmp/95402ff756937342dc1a396f8e8e6bd5/logTestDataDriven3356616149
    test_log_scope.go:81: use -show-logs to present logs inline
=== CONT  TestDataDriven
    datadriven_test.go:85: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/95402ff756937342dc1a396f8e8e6bd5/logTestDataDriven3356616149
--- FAIL: TestDataDriven (485.96s)
=== RUN   TestDataDriven/3node
    --- FAIL: TestDataDriven/3node (468.55s)
=== RUN   TestDataDriven/3node/partition
        --- FAIL: TestDataDriven/3node/partition (0.00s)
=== RUN   TestDataDriven/3node/partition/single_col_list_partitioning_default
=== PAUSE TestDataDriven/3node/partition/single_col_list_partitioning_default
=== CONT  TestDataDriven/3node/partition/single_col_list_partitioning_default
=== CONT  TestDataDriven/3node/partition/single_col_list_partitioning_default
    test_server_shim.go:84: cluster virtualization disabled due to issue: #106818 (expected label: C-test-failure)
    datadriven.go:144: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/3253/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/spanconfigsqltranslatorccl_test_/spanconfigsqltranslatorccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/single_col_list_partitioning_default:1:
        exec-sql [0 args]
        CREATE DATABASE IF NOT EXISTS db;
        CREATE TABLE IF NOT EXISTS db.tbl (a INT PRIMARY KEY);
        ALTER TABLE db.tbl PARTITION BY LIST (a) (
          PARTITION p4 VALUES IN (4),
          PARTITION p5 VALUES IN (5),
          PARTITION pd VALUES IN (DEFAULT)
        );
        ALTER TABLE db.tbl CONFIGURE ZONE DISCARD;
        ALTER PARTITION p4 OF INDEX db.tbl@tbl_pkey CONFIGURE ZONE USING constraints = '[+n2]';
        ALTER PARTITION p5 OF INDEX db.tbl@tbl_pkey CONFIGURE ZONE USING constraints = '[+n3]';
        ALTER PARTITION pd OF INDEX db.tbl@tbl_pkey CONFIGURE ZONE USING constraints = '[+n1]';
        ----
    datadriven.go:144: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/3253/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/spanconfigsqltranslatorccl_test_/spanconfigsqltranslatorccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/single_col_list_partitioning_default:15:
         
        output didn't match expected:
        @@ -1,7 +1,7 @@
        -/Table/106{-/1}                            range default
        -/Table/106/1{-/4}                          constraints=[+n1]
        -/Table/106/1/{4-5}                         constraints=[+n2]
        -/Table/106/1/{5-6}                         constraints=[+n3]
        -/Table/106/{1/6-2}                         constraints=[+n1]
        -/Table/10{6/2-7}                           range default
        +/Table/109{-/1}                            range default
        +/Table/109/1{-/4}                          constraints=[+n1]
        +/Table/109/1/{4-5}                         constraints=[+n2]
        +/Table/109/1/{5-6}                         constraints=[+n3]
        +/Table/109/{1/6-2}                         constraints=[+n1]
        +/Table/109/{2-PrefixEnd}                   range default
         
            --- FAIL: TestDataDriven/3node/partition/single_col_list_partitioning_default (66.81s)
```
<p>Parameters: <code>TAGS=bazel,gss</code>
, <code>stress=true</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestDataDriven.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-31263

### LINKED ISSUE #110158: pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/spanconfigsqltranslatorccl_test: TestDataDriven failed
pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/spanconfigsqltranslatorccl_test.TestDataDriven [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/11665123?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/11665123?buildTab=artifacts#/) on release-23.1.10-rc @ [697d5576a154327698743c7cb7dcfa6a1f41d051](https://github.com/cockroachdb/cockroach/commits/697d5576a154327698743c7cb7dcfa6a1f41d051):

```
=== RUN   TestDataDriven
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/95402ff756937342dc1a396f8e8e6bd5/logTestDataDriven2292021382
    test_log_scope.go:79: use -show-logs to present logs inline
=== CONT  TestDataDriven
    datadriven_test.go:85: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/95402ff756937342dc1a396f8e8e6bd5/logTestDataDriven2292021382
--- FAIL: TestDataDriven (569.38s)
=== RUN   TestDataDriven/3node
    --- FAIL: TestDataDriven/3node (549.37s)
=== RUN   TestDataDriven/3node/repartition
        --- FAIL: TestDataDriven/3node/repartition (0.02s)
=== RUN   TestDataDriven/3node/repartition/single_col_range_partitioning_to_single_col_range_partitioning_maxvalue
=== PAUSE TestDataDriven/3node/repartition/single_col_range_partitioning_to_single_col_range_partitioning_maxvalue
=== CONT  TestDataDriven/3node/repartition/single_col_range_partitioning_to_single_col_range_partitioning_maxvalue
=== CONT  TestDataDriven/3node/repartition/single_col_range_partitioning_to_single_col_range_partitioning_maxvalue
    datadriven.go:144: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/2897/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/spanconfigsqltranslatorccl_test_/spanconfigsqltranslatorccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/single_col_range_partitioning:1:
        exec-sql [0 args]
        CREATE DATABASE IF NOT EXISTS db;
        CREATE TABLE IF NOT EXISTS db.tbl (a INT PRIMARY KEY);
        ALTER TABLE db.tbl PARTITION BY RANGE (a) (
          PARTITION p3 VALUES FROM (MINVALUE) TO (3),
          PARTITION p4 VALUES FROM (3) TO (4)
        );
        ALTER TABLE db.tbl CONFIGURE ZONE USING constraints = '[+n1]';
        ALTER PARTITION p3 OF INDEX db.tbl@tbl_pkey CONFIGURE ZONE USING constraints = '[+n2]';
        ALTER PARTITION p4 OF INDEX db.tbl@tbl_pkey CONFIGURE ZONE USING constraints = '[+n3]';
        ----
    datadriven.go:144: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/2897/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/spanconfigsqltranslatorccl_test_/spanconfigsqltranslatorccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/single_col_range_partitioning:13:
         
        expected:
        /Table/106{-/1}                            constraints=[+n1]
        /Table/106/1{-/3}                          constraints=[+n2]
        /Table/106/1/{3-4}                         constraints=[+n3]
        /Table/10{6/1/4-7}                         constraints=[+n1]
        
        found:
        /Table/109{-/1}                            constraints=[+n1]
        /Table/109/1{-/3}                          constraints=[+n2]
        /Table/109/1/{3-4}                         constraints=[+n3]
        /Table/109/{1/4-PrefixEnd}                 constraints=[+n1]
            --- FAIL: TestDataDriven/3node/repartition/single_col_range_partitioning_to_single_col_range_partitioning_maxvalue (81.27s)
```
<p>Parameters: <code>TAGS=bazel,gss</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #110093 pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/spanconfigsqltranslatorccl_test: TestDataDriven failed [C-test-failure O-robot T-sql-foundations branch-master db-cy-23 release-blocker]
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestDataDriven.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-31290

### LINKED ISSUE #110159: pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/spanconfigsqltranslatorccl_test: TestDataDriven failed
pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/spanconfigsqltranslatorccl_test.TestDataDriven [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/11665128?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/11665128?buildTab=artifacts#/) on release-23.1 @ [914e15822b995399c22b12ed7d0bfe1c24503051](https://github.com/cockroachdb/cockroach/commits/914e15822b995399c22b12ed7d0bfe1c24503051):

```
        output didn't match expected:
        @@ -1,7 +1,7 @@
        -/Table/106{-/1}                            constraints=[+n1]
        -/Table/106/1{-/3}                          constraints=[+n2]
        -/Table/106/1/{3-4}                         constraints=[+n3]
        -/Table/106/1/{4-5/6}                       constraints=[+n1]
        -/Table/106/1/5/{6-7}                       constraints=[+n2]
        -/Table/10{6/1/5/7-7}                       constraints=[+n1]
        +/Table/109{-/1}                            constraints=[+n1]
        +/Table/109/1{-/3}                          constraints=[+n2]
        +/Table/109/1/{3-4}                         constraints=[+n3]
        +/Table/109/1/{4-5/6}                       constraints=[+n1]
        +/Table/109/1/5/{6-7}                       constraints=[+n2]
        +/Table/109/{1/5/7-PrefixEnd}               constraints=[+n1]
         
            --- FAIL: TestDataDriven/3node/partition/multi_col_range_partitioning_maxvalue (93.36s)
=== RUN   TestDataDriven/3node/partition/single_col_range_partitioning_sparse
=== PAUSE TestDataDriven/3node/partition/single_col_range_partitioning_sparse
=== CONT  TestDataDriven/3node/partition/single_col_range_partitioning_sparse
=== CONT  TestDataDriven/3node/partition/single_col_range_partitioning_sparse
    datadriven.go:144: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/2844/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/spanconfigsqltranslatorccl_test_/spanconfigsqltranslatorccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/single_col_range_partitioning_sparse:1:
        exec-sql [0 args]
        CREATE DATABASE IF NOT EXISTS db;
        CREATE TABLE IF NOT EXISTS db.tbl (a INT PRIMARY KEY);
        ALTER TABLE db.tbl PARTITION BY RANGE (a) (
          PARTITION p1 VALUES FROM (1) TO (2),
          PARTITION p3 VALUES FROM (3) TO (4)
        );
        ALTER TABLE db.tbl CONFIGURE ZONE USING constraints = '[+n1]';
        ALTER PARTITION p1 OF INDEX db.tbl@tbl_pkey CONFIGURE ZONE USING constraints = '[+n2]';
        ALTER PARTITION p3 OF INDEX db.tbl@tbl_pkey CONFIGURE ZONE USING constraints = '[+n3]';
        ----
    datadriven.go:144: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/2844/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/spanconfigsqltranslatorccl_test_/spanconfigsqltranslatorccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/single_col_range_partitioning_sparse:13:
         
        output didn't match expected:
        @@ -1,6 +1,6 @@
        -/Table/106{-/1/1}                          constraints=[+n1]
        -/Table/106/1/{1-2}                         constraints=[+n2]
        -/Table/106/1/{2-3}                         constraints=[+n1]
        -/Table/106/1/{3-4}                         constraints=[+n3]
        -/Table/10{6/1/4-7}                         constraints=[+n1]
        +/Table/109{-/1/1}                          constraints=[+n1]
        +/Table/109/1/{1-2}                         constraints=[+n2]
        +/Table/109/1/{2-3}                         constraints=[+n1]
        +/Table/109/1/{3-4}                         constraints=[+n3]
        +/Table/109/{1/4-PrefixEnd}                 constraints=[+n1]
         
            --- FAIL: TestDataDriven/3node/partition/single_col_range_partitioning_sparse (83.37s)
```
<p>Parameters: <code>TAGS=bazel,gss</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #110158 pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/spanconfigsqltranslatorccl_test: TestDataDriven failed [C-test-failure O-robot T-kv branch-release-23.1.10-rc release-blocker]
- #110093 pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/spanconfigsqltranslatorccl_test: TestDataDriven failed [C-test-failure O-robot T-sql-foundations branch-master db-cy-23 release-blocker]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestDataDriven.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-31291

### PR DESCRIPTION
**Pull request by ecwall**
Fixes #110093
Fixes https://github.com/cockroachdb/cockroach/issues/110159
Fixes https://github.com/cockroachdb/cockroach/issues/110158

The table ID in the multi-node SQLTranslator test output can vary between runs.

This PR replaces the table ID with `<table-id>` or `<table-id+1>` to make
output deterministic.

Release note: None

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110120)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall)

___
*[`pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/unpartitioned` line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110120#-Ndhrugo-hpNL8SxPVJz:-Ndhrugo-hpNL8SxPVK-:b-xk8e38) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cceb9edcb2e2bdd220e97e7f179467a663df5b3/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/unpartitioned#L10)):*
> ```
> translate database=db table=tbl
> ----
> [..., ...)                                 range default
> ```

this output seems a little less readable than it was before. and it's odd to have a different format for multinode tests

could it show something like `/Table/ID{6-7}`
___
*[`pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/datadriven_test.go` line 232 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110120#-Ndhs_fi6ZGQvRRoHmkJ:-Ndhs_fi6ZGQvRRoHmkK:b1s8wyd) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cceb9edcb2e2bdd220e97e7f179467a663df5b3/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/datadriven_test.go#L232)):*
> ```Go
> 							startKeyStr := tableIDPrefixRegexp.ReplaceAllString(span.Key.String(), repl)
> 							endKeyStr := tableIDPrefixRegexp.ReplaceAllString(span.EndKey.String(), repl)
> 							spanStr = fmt.Sprintf("[%s, %s)", startKeyStr, endKeyStr)
> ```

maybe this could be something like:
```
spanStr = tableIDPrefixRegexp.ReplaceAllString(record.GetTarget().GetSpan().String(), "/Table/ID$1")
```

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110120)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/unpartitioned` line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110120#-Ndhrugo-hpNL8SxPVJz:-Ndjt4mA92-Fw0_eU5X0:b-75yrga) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cceb9edcb2e2bdd220e97e7f179467a663df5b3/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/unpartitioned#L10)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this output seems a little less readable than it was before. and it's odd to have a different format for multinode tests

could it show something like `/Table/ID{6-7}`
</blockquote></details>

The `6` and `7` in `{6-7}` are the final digits of table IDs 106 and 107 so they can't appear in the output.
___
*[`pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/datadriven_test.go` line 232 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110120#-Ndhs_fi6ZGQvRRoHmkJ:-NdjtOOY5ny3YYNm9GVS:b-qdwlr2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cceb9edcb2e2bdd220e97e7f179467a663df5b3/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/datadriven_test.go#L232)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

maybe this could be something like:
```
spanStr = tableIDPrefixRegexp.ReplaceAllString(record.GetTarget().GetSpan().String(), "/Table/ID$1")
```
</blockquote></details>

That will not properly handle the case where the table ID is partially contained inside `{` `}` like `/Table/10{6-7}` or `/Table/10{6/4-7}`.

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110120)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall)

___
*[`pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/unpartitioned` line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110120#-Ndhrugo-hpNL8SxPVJz:-Ndk7kE00fPjPBZQQ0tB:b-fcyxlf) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cceb9edcb2e2bdd220e97e7f179467a663df5b3/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/unpartitioned#L10)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

The `6` and `7` in `{6-7}` are the final digits of table IDs 106 and 107 so they can't appear in the output.
</blockquote></details>

ah ok, i was misinterpreting the original format. i'm still confused though - it seems like this test only has one table, so why are there two table IDs?

IMO my other point that it's confusing to see `[..., ...)` in the output still holds. maybe we should do something so the min table ID is always normalized to `106` (or some other sensible constant), and all the other table IDs are formatted offset from that.

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110120)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/unpartitioned` line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110120#-Ndhrugo-hpNL8SxPVJz:-NdkFMy66gBM1ERtuO2H:b-wncd1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cceb9edcb2e2bdd220e97e7f179467a663df5b3/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/unpartitioned#L10)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

ah ok, i was misinterpreting the original format. i'm still confused though - it seems like this test only has one table, so why are there two table IDs?

IMO my other point that it's confusing to see `[..., ...)` in the output still holds. maybe we should do something so the min table ID is always normalized to `106` (or some other sensible constant), and all the other table IDs are formatted offset from that.
</blockquote></details>

106 is `db.tbl`'s ID and its keyspace's inclusive lower bound. 107 is `db.tbl`'s keyspace's exclusive upper bound. All keys in the table are between `[/Table/106, /Table/107)`.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110120)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall)

___
*[`pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/unpartitioned` line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110120#-Ndhrugo-hpNL8SxPVJz:-NdkGbn_BaXMg4G0F2Ck:b-ta9xfp) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cceb9edcb2e2bdd220e97e7f179467a663df5b3/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/unpartitioned#L10)):*
<details><summary><i>Previously, ecwall (Evan Wall) wrote…</i></summary><blockquote>

106 is `db.tbl`'s ID and its keyspace's inclusive lower bound. 107 is `db.tbl`'s keyspace's exclusive upper bound. All keys in the table are between `[/Table/106, /Table/107)`.
</blockquote></details>

i see, that part makes sense to me now.

it's still confusing to see `[..., ...)`. that makes it seem like the _entire_ keyspace is included in the range. it doesn't give you any sense of the upper and lower bounds that you just explained to me.

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110120)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/unpartitioned` line 10 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110120#-Ndhrugo-hpNL8SxPVJz:-NdkRbLZ4POLz57gDm6u:b7sm16h) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cceb9edcb2e2bdd220e97e7f179467a663df5b3/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/unpartitioned#L10)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i see, that part makes sense to me now.

it's still confusing to see `[..., ...)`. that makes it seem like the _entire_ keyspace is included in the range. it doesn't give you any sense of the upper and lower bounds that you just explained to me.
</blockquote></details>

I changed this to a `<table-id>` placeholder.

**Review by rafiss — APPROVED** [review]
this looks great, thanks!

> Reviewed 26 of 26 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110120#-:-NdkpzvG6GiaEolfriLH:bpw5zz4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ecwall)

**Comment by ecwall** [comment]
bors r=rafiss

**Pull request merged**
