### PR TITLE
workload: move geospatial data to embedded files

### PR DESCRIPTION
**Pull request by RaduBerinde**
The geospatial workloads includes all table data as constants in Go
code, resulting in a 27MB file. This large file is potentially
processed by linters, static analysis tools, and IDEs (like gopls).

This commit removes these constants and moves the data to gzip
compressed yaml files that are then embedded in the binary using
`go:embed`.

The size of the workload binary is decreased from 190MB to 90MB.

Finding a good encoding was tricky because we need to preserve nils
and maintain the correct type for floats vs ints (which is
surprisingly hard with json or yaml encoding: json decodes all
integers as floats, yaml encodes `5.0` as `5` and it is decoded as an
integer). I ended up using a custom yaml encoder for floats that
(along with some manual postprocssing), allowed us to include the `.0`
in the encoding.

This is the code I used to generate the yaml files, followed by
`%s/FOO//g` and `gzip -9` for each file:
```go
package geospatial

import (
	"fmt"
	"os"
	"testing"

	"gopkg.in/yaml.v2"
)

type myFloat float64

func (f myFloat) MarshalYAML() (interface{}, error) {
	if float64(f) == float64(int64(f)) {
		// Special case; add a .0 to whole numbers so they decode to float.
		// Then we have to manually %s/FOO//g on all files.
		return fmt.Sprintf("FOO%d.0FOO", int64(f)), nil
	}
	return float64(f), nil
}

func TestDumpData(t *testing.T) {
	for _, x := range []struct {
		name   string
		object [][]interface{}
	}{
		{"nyc_census_blocks", nycCensusBlocksRows[:]},
		{"nyc_homicides", nycHomicidesRows[:]},
		{"nyc_neighborhoods", nycNeighborhoodsRows[:]},
		{"nyc_streets", nycStreetsRows[:]},
		{"nyc_subway_stations", nycSubwayStationsRows[:]},
		{"subway_lines", subwayLinesRows[:]},
	} {

		for _, o := range x.object {
			for j := range o {
				f, ok := o[j].(float64)
				if ok {
					o[j] = myFloat(f)
				}
			}
		}

		data, err := yaml.Marshal(x.object)
		if err != nil {
			t.Fatal(err)
		}
		filename := fmt.Sprintf("data/%s.yaml", x.name)
		fi, err := os.OpenFile(filename, os.O_WRONLY|os.O_TRUNC|os.O_CREATE, 0660)
		if err != nil {
			t.Fatal(err)
		}
		fi.Write(data)
	}
}
```

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
What can I do to test this, other than `workload init geospatial` ?

**Review by rafiss — COMMENTED** [review]
would a CSV encoding work? I ask because our own import/export commands support CSV format, so it shouldn't be lossy, right?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74066#-:-MrG431hCApoXtRQiTR1:bk805yh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @RaduBerinde)

___
*[pkg/workload/geospatial/nyc_census_blocks.json, line 0 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74066#-MrG3DrECDOgDuqs-Mb1:-MrG3DrECDOgDuqs-Mb2:b-grt3bb) ([raw file](https://github.com/cockroachdb/cockroach/blob/1efd8ba7549bf41528857a8ca7faef1ba4e3ee14/pkg/workload/geospatial/nyc_census_blocks.json#L0)):*
is this json file supposed to be here?
___
*[pkg/workload/geospatial/geospatial_test.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74066#-MrG4-Wg-ESfbDqF0AQ0:-MrG4-Wg-ESfbDqF0AQ1:b-7ne4oc) ([raw file](https://github.com/cockroachdb/cockroach/blob/1efd8ba7549bf41528857a8ca7faef1ba4e3ee14/pkg/workload/geospatial/geospatial_test.go#L52)):*
> ```Go
> 			t.Fatal(err)
> 		}
> 		//w, err := gzip.NewWriterLevel(fi, gzip.BestCompression)
> ```

commented code

**Review by RaduBerinde — COMMENTED** [review]
CSV decodes everything as string AFAIK, I don't think it would be easy to convert that to the `[]interface{}` stuff used by those tables. Maybe we could use it with some other infrastructure for importing data but I wouldn't know where to start.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74066#-:-MrG6x2_ASgEZUw_uv4Z:b-26jvrl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rafiss)

___
*[pkg/workload/geospatial/geospatial_test.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74066#-MrG4-Wg-ESfbDqF0AQ0:-MrG7K6nDUMgmy0OCcWz:bugqpai) ([raw file](https://github.com/cockroachdb/cockroach/blob/1efd8ba7549bf41528857a8ca7faef1ba4e3ee14/pkg/workload/geospatial/geospatial_test.go#L52)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

commented code
</blockquote></details>

oops, I forgot to delete this file.
___
*[pkg/workload/geospatial/nyc_census_blocks.json, line  at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74066#-MrG3DrECDOgDuqs-Mb1:-MrG7Nt58hMqRsOnJd2f:b-k7mx7q) ([raw file](https://github.com/cockroachdb/cockroach/blob/1efd8ba7549bf41528857a8ca7faef1ba4e3ee14/pkg/workload/geospatial/nyc_census_blocks.json#L)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

is this json file supposed to be here?
</blockquote></details>

Deleted.

**Comment by RaduBerinde** [comment]
I verified that the loaded objects are `DeepEqual()` to the previous constants:
```go
func TestEquiv(t *testing.T) {
	// Load the table rows from the embedded files.
	load := func(name string) [][]interface{} {
		compressed, err := embedded.ReadFile(fmt.Sprintf("data/%s.yaml.gz", name))
		if err != nil {
			panic(err)
		}
		r, err := gzip.NewReader(bytes.NewReader(compressed))
		var result [][]interface{}
		if err := yaml.NewDecoder(r).Decode(&result); err != nil {
			panic(err)
		}
		return result
	}

	for _, o := range []struct {
		name    string
		expRows [][]interface{}
	}{
		{"nyc_census_blocks", nycCensusBlocksRows[:]},
		{"nyc_homicides", nycHomicidesRows[:]},
		{"nyc_neighborhoods", nycNeighborhoodsRows[:]},
		{"nyc_streets", nycStreetsRows[:]},
		{"nyc_subway_stations", nycSubwayStationsRows[:]},
		{"subway_lines", subwayLinesRows[:]},
	} {
		{
			t.Run(o.name, func(t *testing.T) {
				rows := load(o.name)
				if !reflect.DeepEqual(rows, o.expRows) {
					t.Fatal("not equal")
				}
				t.Log("equal")
			})
		}
	}
}
```

**Review by otan — APPROVED** [review]
looks good to me

the init is fine and the DeepEqual looks good.

if you want to be nerdsniped, i was looking at doing similar treatment here (but can also work on this when i return next year): https://github.com/cockroachdb/cockroach/blob/master/pkg/geo/geoprojbase/projections.go / https://github.com/cockroachdb/cockroach/issues/63969

**Pull request merged**
