### PR TITLE
ui: show per-store metrics in storage dashboard

### LINKED ISSUE #90734: ui: read amplification incorrectly sums across stores
**Describe the problem**

Consider this 4-store per-node cluster. On our storage dashboard, it appears that the read-amp is 16. It is in fact 4 in each store.
Screen Shot 2022-10-26 at 4 20 24 PM

Jira issue: CRDB-20913

### LINKED ISSUE #125696: ui: update Storage dashboard graphs to show per-store metrics
As identified in https://github.com/cockroachdb/cockroach/pull/125653#pullrequestreview-2118565134, some metrics on the storage dashboard sum together values across all stores on a node, which can be misleading. Breaking down the following metrics on a per-store basis would help to identify when a single store is causing an issue:
- read amplification
- log and command commit latencies
- SStable count
- memtable flushes
- WAL bytes written
- compactions
- ingestions
- write stalls

The above metrics were chosen by identifying wherever we currently perform an aggregation over all stores in [the storage dashboard](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/storage.tsx).

Jira issue: CRDB-39561

### PR DESCRIPTION
**Pull request by anish-shanbhag**
Many metrics on the storage dashboard are aggregated across all stores, which can be misleading. This change breaks down many storage metrics on a per-store basis to display if certain stores are causing issues. The store-level metrics are only shown when filtering to a single node on the metrics dashboard in order to increase usability when there are thousands of stores in a single cluster.

Also fixes incorrect aggregation of certain metrics across stores; read amplification is now aggregated using averaging, and latency metrics are aggregated using maximum.

See [this comment](https://github.com/cockroachdb/cockroach/pull/125699#issuecomment-2181233647) for an example of the new graphs.

Epic: none
Fixes: #125696, #90734 
Release note (ui change): Updated Storage dashboard graphs to show most metrics on a per-store basis when viewing a single node's metrics. This provides increased visibility into issues caused by specific stores on each node.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
Is there a way to switch how these are shown - per store or aggregated per node? I ask because on a 100+ node cluster with 10 stores/node, the graph with 100 lines is already very hard to use; one with 1000+ would definitely be unusable.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125699#-:-O-NARYs-oN5Pu-OmV6Q:b-vhmlre)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @xinhaoz)

**Comment by anish-shanbhag** [comment]
Summarizing some of the options we discussed:

1. Always show metric on a per-store basis. This would make the graph unusable for large clusters with 1000+ stores
2. Show the metric on a per-store basis as long as the number of stores is below some threshold, otherwise aggregate them for large clusters
    - This may have the downside of being unclear from a user perspective, since it might not be obvious what's causing some graphs to be per-node and others to be per-store
3. Add a checkbox/toggle to each graph which would let users switch between per-node and per-store
    - This would probably improve UX, but it looks like a checkbox like this hasn't been previously used in any other graph on the dashboard. So, we would need to talk with the design team about how this would look
    - Potential downside: the graph would still be unusable for large clusters when toggled to per-store, unless we disable the option to switch.

I think there's another option which might work:

4. Always show per-node metrics when looking at the overall cluster, but show per-store metrics when only looking at a specific node using the dropdown
    - This preserves the current behavior for the full cluster view, meaning there won't ever be 1000+ lines on the same graph. But it still allows us to see if a specific store is causing issues on a certain node
    - No need for UI changes
    - Downside: it might not be super obvious that filtering to a node triggers this to change, but I think it might still be more intuitive than option \# 2

Thoughts on what might work best here?

**Comment by aadityasondhi** [comment]
I like option #4. The downside isn't too bad. I wonder if we can easily change the legend labels to make it super clear that the user is viewing per-store metrics when it is toggled.

**Comment by RaduBerinde** [comment]
Option 4 sounds great to me!

**Comment by itsbilal** [comment]
Also good with option 4 - thanks @anish-shanbhag for thinking this through and digging in!

**Comment by anish-shanbhag** [comment]
UX/design team confirmed that option 4 works well here, with one slight change: we'll include one line for the aggregated node metric, in addition to all of the lines for each store individually. This should preserve all the info we have now while also providing the store-level breakdown.

**Comment by anish-shanbhag** [comment]
Updated with the new behavior, here's what the graphs look like in the full cluster view:
image

and when viewing a single node:
image

I stripped out the node's IP address/port to clean up the legend labels and match more closely with the format from cockroach logs, but let me know if there's a better format for the labels.

**Comment by RaduBerinde** [comment]
I would remove the word `total` (just leave `n6`). In some cases, the correct aggregation should be "average" (e.g. for read amplification) or "maximum" (e.g. for latency). Using "total" for all of these can be confusing.

**Comment by RaduBerinde** [comment]
I guess it really is the sum currently (because of #90734) but hopefully we'll fix that someday :)

**Comment by anish-shanbhag** [comment]
> I guess it really is the sum currently (because of #90734) but hopefully we'll fix that someday :)

The fix for this was pretty straightforward (just including a `aggregateMax`/`aggregateAvg` prop on the `Metric`) so I just pushed a change which addresses this. The legend labels now correctly show "average" for latency-related metrics and "max" for read amp. I left "total" as the label for the rest since I think summing makes sense for those, but let me know if there's a better aggregator for any of them.

**Review by RaduBerinde — COMMENTED** [review]
Very cool!! :lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125699#-:-O-rQgLAE1cZjIxdznm7:b-u55r7k)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @itsbilal and @xinhaoz)

**Comment by anish-shanbhag** [comment]
TFTR!

bors r=RaduBerinde

**Review by itsbilal — APPROVED** [review]
Should go through now, try again

**Comment by anish-shanbhag** [comment]
bors r=itsbilal

**Pull request merged**
