### PR TITLE
rangefeed: create new rangefeed package

### PR DESCRIPTION
**Pull request by nvb**
This is the first "mergable" part of #27285.

The change introduces a new rangefeed package, which exports a `Processor`
that manages a set of rangefeed registrations and handles the routing of
logical updates to these registrations. While routing logical updates to
rangefeed registrations, the processor performs two important tasks:
1. it translates logical updates into rangefeed events. These logical
   updates are provided to the Processor through its `ConsumeLogicalOps`
   method.
2. it transforms a range-level closed timestamp to a rangefeed-level resolved
   timestamp. Closed timestamp updates are passed to the Processor through
   its `ForwardClosedTS` method.

In order to perform its second task, a `Processor` hold on to a `resolvedTimestamp`
object. A rangefeed's "resolved timestamp" is defined as the timestamp at
which no future updates will be emitted to the feed at or before. The timestamp
is monotonically increasing and is communicated through RangeFeedCheckpoint
notifications whenever it changes. The `resolvedTimestamp` itself holds on
to a `unresolvedIntentQueue` (described in #26782) which allows it to efficiently
track unresolved intents that it observes in logical updates provided to the
Processor.

There are two major pieces of this package missing. The first is catch up
scans for new registrations and the second is a mechanism to push intents
that are old enough to be holding back the resolved timestamp.

The change doesn't plug anything in yet, but a rough draft of the plumbing
can be seen in #27285.

Release note: None

### CODE REVIEW

**Review by tbg — CHANGES_REQUESTED** [review]
Looks good! I'm mostly concerned about the fact that the Processor reads from the engine.

> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-:-LIkMtoU6ZH_IvFN1MaA:b-nu60f3)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/rangefeed/processor.go, line 168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-LIkDgeCD2t-RI0Ru_75:-LIkDgeCD2t-RI0Ru_76:b81hr7b) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfb5728e6822f630351745d99ac2828262e44ff4/pkg/storage/rangefeed/processor.go#L168)):*
> ```Go
> 
> 					if err := stopper.RunAsyncTask(
> 						ctx, "rangefeed: WIP need a good name for this",
> ```

rangefeed-{closer,pusher}?
___
*[pkg/storage/rangefeed/processor.go, line 320 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-LIkFGq7AC2gyiuZIAEg:-LIkFGq8-Lz_7abZoUGP:bucp2w6) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfb5728e6822f630351745d99ac2828262e44ff4/pkg/storage/rangefeed/processor.go#L320)):*
> ```Go
> 			// quick.
> 			key := t.Key
> 			val, _, err := engine.MVCCGetWithTombstone(ctx, p.Eng,
> ```

Can this really work? You're reading stuff back from the engine asynchronously, so an arbitrary amount of time after it was written. By that time, the value could've already been GC'ed (as an extreme example, and you're not checking the threshold), or the range been rebalanced away and data GC'ed in the process (and you're not checking the tombstone). I know why you're doing it this way (the intent resolution doesn't actually see the value it commits, so it doesn't have an easy way to put it into the logical op), but could you still populate the event before it hits the `Processor` (which ideally wouldn't even know what an Engine is anyway?)
This could be done right at the caller to `ConsumeLogicalOps` which I assume will sit somewhere downstream of Raft (and *can* read from the engine in a safe way if it applies the appropriate checks).
___
*[pkg/storage/rangefeed/processor.go, line 328 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-LIkGuvFEd3UffcWtVvI:-LIkGuvFEd3UffcWtVvJ:b4nioqa) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfb5728e6822f630351745d99ac2828262e44ff4/pkg/storage/rangefeed/processor.go#L328)):*
> ```Go
> 				// If we see an error then we disconnect all registrations
> 				// that overlap the key. However, we still need to let the
> 				// resolvedTimestamp see the operation or we risk leaking
> ```

Any error here is indicative of a big mess (engine badness, etc) and would likely occur over and over again, right?
___
*[pkg/storage/rangefeed/registry.go, line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-LIkK5JZ-0TPkEz-Gtx7:-LIkK5J_7FlLOO5fHyhL:b-80w1aa) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfb5728e6822f630351745d99ac2828262e44ff4/pkg/storage/rangefeed/registry.go#L97)):*
> ```Go
> // PublishToOverlapping publishes the provided event to all registrations whose
> // range overlaps the specified span.
> func (reg *registry) PublishToOverlapping(span roachpb.Span, event *roachpb.RangeFeedEvent) {
> ```

Are there any events that aren't on a single key?
___
*[pkg/storage/rangefeed/resolved_timestamp.go, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-LIkL-4OAHmQhkaFGZIf:-LIkL-4OAHmQhkaFGZIg:b5pr81b) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfb5728e6822f630351745d99ac2828262e44ff4/pkg/storage/rangefeed/resolved_timestamp.go#L151)):*
> ```Go
> 	newTS := rts.closedTS
> 	if txn := rts.intentQ.Oldest(); txn != nil {
> 		txnTS := txn.timestamp.Prev()
> ```

I stand by my opinion that nobody should be calling `Prev()`. We've (I think) managed to avoid integer overflow so far, and would be nice to keep it that way :-) How do you feel about clipping the logical here? There's no reason you need to are about each logical tick.
___
*[pkg/storage/rangefeed/resolved_timestamp.go, line 320 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-LIkMIVl7t1N28iSndCm:-LIkMIVl7t1N28iSndCn:b-y31uum) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfb5728e6822f630351745d99ac2828262e44ff4/pkg/storage/rangefeed/resolved_timestamp.go#L320)):*
> ```Go
> // IncRef increments the reference count of the specified transaction. It
> // returns whether the update advanced the timestamp of the oldest transaction
> // in the queue.
> ```

How would that happen? I'd expect that to only be possible when the ref decreases.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28072)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/rangefeed/processor.go, line 168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-LIkDgeCD2t-RI0Ru_75:-LIlFoZY2YoPyOjp44NP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfb5728e6822f630351745d99ac2828262e44ff4/pkg/storage/rangefeed/processor.go#L168)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

rangefeed-{closer,pusher}?
</blockquote></details>

Done.
___
*[pkg/storage/rangefeed/processor.go, line 320 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-LIkFGq7AC2gyiuZIAEg:-LIlFoxO1F2skyfNNTg-:bc21bum) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfb5728e6822f630351745d99ac2828262e44ff4/pkg/storage/rangefeed/processor.go#L320)):*
Done. Thanks for the suggestion.

> which ideally wouldn't even know what an Engine is anyway?

The `Processor` will still need some way to access kvs on command in order to perform its catch up scans though. I'm curious if you had any ideas about this (either from before or now). Should each registration provide a rocksdb snapshot? Should a Processor just use a `client.DB` to perform this catchup scan? (almost certainly not) Should we just give in and give `Processor` an Engine?
___
*[pkg/storage/rangefeed/processor.go, line 328 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-LIkGuvFEd3UffcWtVvI:-LIlFrChEpTF797sKY5o:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfb5728e6822f630351745d99ac2828262e44ff4/pkg/storage/rangefeed/processor.go#L328)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Any error here is indicative of a big mess (engine badness, etc) and would likely occur over and over again, right?
</blockquote></details>

Removed.
___
*[pkg/storage/rangefeed/registry.go, line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-LIkK5JZ-0TPkEz-Gtx7:-LIlFvA73GSk4lUj7-CA:b-flwxyo) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfb5728e6822f630351745d99ac2828262e44ff4/pkg/storage/rangefeed/registry.go#L97)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Are there any events that aren't on a single key?
</blockquote></details>

Checkpoint notifications act on a span of keys. We could use knowledge that these operate on all keys in the registry, but if this isn't a performance bottleneck then I'd rather maintain the nice abstraction.
___
*[pkg/storage/rangefeed/resolved_timestamp.go, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-LIkL-4OAHmQhkaFGZIf:-LIlG9o196lOV3RitNJ3:bng21b2) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfb5728e6822f630351745d99ac2828262e44ff4/pkg/storage/rangefeed/resolved_timestamp.go#L151)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

I stand by my opinion that nobody should be calling `Prev()`. We've (I think) managed to avoid integer overflow so far, and would be nice to keep it that way :-) How do you feel about clipping the logical here? There's no reason you need to are about each logical tick.
</blockquote></details>

Done. Created a new `FloorPrev` method.
___
*[pkg/storage/rangefeed/resolved_timestamp.go, line 320 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-LIkMIVl7t1N28iSndCm:-LIlGncO8SxKObKeD_Jm:b-hhgge6) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfb5728e6822f630351745d99ac2828262e44ff4/pkg/storage/rangefeed/resolved_timestamp.go#L320)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

How would that happen? I'd expect that to only be possible when the ref decreases.
</blockquote></details>

It can happen in a sense when if the catchup scan is re-ordered with a flow of events and a refcount goes negative. That whole situation is a little poorly defined (and tested) at the moment, but I'd like to come back to this when I add in the catchup scan.

**Review by tbg — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-:-LIlapcP1ZanD0uUaIbS:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/rangefeed/processor.go, line 320 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-LIkFGq7AC2gyiuZIAEg:-LIlaAYHBdfG2GHT4riN:b-eww6bf) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfb5728e6822f630351745d99ac2828262e44ff4/pkg/storage/rangefeed/processor.go#L320)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Done. Thanks for the suggestion.

> which ideally wouldn't even know what an Engine is anyway?

The `Processor` will still need some way to access kvs on command in order to perform its catch up scans though. I'm curious if you had any ideas about this (either from before or now). Should each registration provide a rocksdb snapshot? Should a Processor just use a `client.DB` to perform this catchup scan? (almost certainly not) Should we just give in and give `Processor` an Engine?
</blockquote></details>

Maybe I'm not deep down in the weeds enough to see the problem with this, but what's wrong with providing an object to the Processor that gives it the API it needs (I assume something to pass a timestamp and keyspace to, and it gives it logical updates). The impl would still run around on an Engine, but that would live in `replica.go` and would perform the proper serialization and checking (gc threshold etc).
___
*[pkg/util/hlc/timestamp.go, line 109 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-LIlafCa16vT7p4JERaW:-LIlafCa16vT7p4JERaX:bj0gne3) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf4f2d479320d8735850e0386ce00fdc1512a4a5/pkg/util/hlc/timestamp.go#L109)):*
> ```Go
> // FloorPrev returns a timestamp earlier than the current timestamp. If it
> // can subtract a logical tick without wrapping around, it does so. Otherwise
> // it subtracts a nanosecond.
> ```

... and clears the logical. (Or you could keep the logical).

**Review by danhhz — APPROVED** [review]
:lgtm_strong: this is excellent work. it's a complicated thing and you've made it super easy to follow

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-:-LImI_Mh4T8FoCGiHIAz:b-oscyvq)* status: :shipit: complete! 2 of 0 LGTMs obtained

___
*[pkg/roachpb/api.proto, line 1521 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-LIlouWL4PORp0xpw3-6:-LIlouWL4PORp0xpw3-7:bzcdlp) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf4f2d479320d8735850e0386ce00fdc1512a4a5/pkg/roachpb/api.proto#L1521)):*
> ```protobuf
> }
> 
> // TODO(nvanbenschoten): Sprinkle some comments in here.
> ```

did you intend to do these comment TODOs before merging?
___
*[pkg/roachpb/api.proto, line 1543 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-LIlof0H9ETXPHxTnTaD:-LIlof0H9ETXPHxTnTaE:biu8xn1) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf4f2d479320d8735850e0386ce00fdc1512a4a5/pkg/roachpb/api.proto#L1543)):*
> ```protobuf
> 
> message RangeFeedEvent {
>   option (gogoproto.onlyone) = true;
> ```

what's the difference between this and the proto `oneof`?
___
*[pkg/storage/rangefeed/processor.go, line 106 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-LIlpdsW9nZIMrJC3HpA:-LIlpdsW9nZIMrJC3HpB:b-1oagcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf4f2d479320d8735850e0386ce00fdc1512a4a5/pkg/storage/rangefeed/processor.go#L106)):*
> ```Go
> 		// Assert that all registrations have disconnected before exiting.
> 		defer func() {
> 			if r := recover(); r != nil {
> ```

what's this for?
___
*[pkg/storage/rangefeed/processor.go, line 165 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-LIlqO_t71YKQobDaSyq:-LIlqO_t71YKQobDaSyr:bb7k6bk) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf4f2d479320d8735850e0386ce00fdc1512a4a5/pkg/storage/rangefeed/processor.go#L165)):*
> ```Go
> 					if err := stopper.RunAsyncTask(ctx, "rangefeed: pushing old intents",
> 						func(ctx context.Context) {
> 							fmt.Printf("need to push the following txns: %v\n", oldTxns)
> ```

log?
___
*[pkg/storage/rangefeed/processor.go, line 166 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-LIlq_W44Sk22gNBKtGG:-LIlq_W44Sk22gNBKtGH:bwwnry8) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf4f2d479320d8735850e0386ce00fdc1512a4a5/pkg/storage/rangefeed/processor.go#L166)):*
> ```Go
> 						func(ctx context.Context) {
> 							fmt.Printf("need to push the following txns: %v\n", oldTxns)
> 							intentPushAttemptC <- struct{}{}
> ```

do you also need to select `ctx.Done` to make the leak detector happy?
___
*[pkg/storage/rangefeed/processor.go, line 253 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-LIlsIMv0DGCoFmaAbVy:-LIlro_VBaYtQtE10mkU:bfw4tj) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf4f2d479320d8735850e0386ce00fdc1512a4a5/pkg/storage/rangefeed/processor.go#L253)):*
> ```Go
> 	// communication so that when this method returns the caller can be sure
> 	// that the Processor goroutine has canceled all registrations and shut
> 	// down.
> ```

wait, has it? looks like the processor goroutine may still be draining events out of out eventsC after this returns
___
*[pkg/storage/rangefeed/registry.go, line 35 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-LIm6uvV0PE6WplZqaAh:-LIm6uvW-_ncHg2KTIPA:bkyy32o) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf4f2d479320d8735850e0386ce00fdc1512a4a5/pkg/storage/rangefeed/registry.go#L35)):*
> ```Go
> // registration is an instance of a rangefeed subscriber who has
> // registered to receive updates for a specific range of keys.
> // Updates are delivered to its stream until on of the following
> ```

nit:on->one
___
*[pkg/storage/rangefeed/registry_test.go, line 131 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-LIm86_mByWJpXCccSDE:-LIm86_mByWJpXCccSDF:bb7n18x) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf4f2d479320d8735850e0386ce00fdc1512a4a5/pkg/storage/rangefeed/registry_test.go#L131)):*
> ```Go
> 	require.NotPanics(t, func() { reg.CheckStreams() })
> 
> 	r1 := newTestRegistration(spAB)
> ```

rAB?
___
*[pkg/storage/rangefeed/registry_test.go, line 136 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-LIm8CrfAtETpJqC9a-3:-LIm8CrfAtETpJqC9a-4:b-qebq96) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf4f2d479320d8735850e0386ce00fdc1512a4a5/pkg/storage/rangefeed/registry_test.go#L136)):*
> ```Go
> 	r4 := newTestRegistration(spAC)
> 
> 	// Register 3 registrations.
> ```

nit:3->4
___
*[pkg/storage/rangefeed/resolved_timestamp.go, line 185 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-LImFIK-EXQeYu0riYmI:-LImFIK-EXQeYu0riYmJ:b-2lwcc4) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf4f2d479320d8735850e0386ce00fdc1512a4a5/pkg/storage/rangefeed/resolved_timestamp.go#L185)):*
> ```Go
> }
> 
> // An "unresolved intent" in the context of the rangefeed primitive is an an
> ```

nit: "an an" -> "an"
___
*[pkg/storage/rangefeed/resolved_timestamp.go, line 222 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-LImFaJQ1D7nAyfHfI8x:-LImFaJQ1D7nAyfHfI8y:b4m8vxo) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf4f2d479320d8735850e0386ce00fdc1512a4a5/pkg/storage/rangefeed/resolved_timestamp.go#L222)):*
> ```Go
> }
> 
> // unresolvedIntentQueue implements heap.Interface and holds unresolvedTxns.
> ```

nit: unresolvedIntentQueue -> unresolvedTxnHeap

**Review by nvb — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-:-LIqRIiUEFnIY3anMS_W:bz5mair)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/roachpb/api.proto, line 1521 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-LIlouWL4PORp0xpw3-6:-LIqJ6juDaaNFSxUN5VW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf4f2d479320d8735850e0386ce00fdc1512a4a5/pkg/roachpb/api.proto#L1521)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

did you intend to do these comment TODOs before merging?
</blockquote></details>

Done.
___
*[pkg/roachpb/api.proto, line 1543 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-LIlof0H9ETXPHxTnTaD:-LIqLQax1sPNf4hWYcAW:bdd7x1d) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf4f2d479320d8735850e0386ce00fdc1512a4a5/pkg/roachpb/api.proto#L1543)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

what's the difference between this and the proto `oneof`?
</blockquote></details>

https://github.com/cockroachdb/cockroach/pull/27112 gives a relatively concise overview of the differences. The TL;DR is that `onlyone` is better for unions with small numbers of variants and `oneof` is better for unions with large numbers of variants. `onlyone` is also creates better generated code so its easier to use.
___
*[pkg/storage/rangefeed/processor.go, line 320 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-LIkFGq7AC2gyiuZIAEg:-LIqNJeb3DVsCHvAV7Nv:b-62x0u) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfb5728e6822f630351745d99ac2828262e44ff4/pkg/storage/rangefeed/processor.go#L320)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Maybe I'm not deep down in the weeds enough to see the problem with this, but what's wrong with providing an object to the Processor that gives it the API it needs (I assume something to pass a timestamp and keyspace to, and it gives it logical updates). The impl would still run around on an Engine, but that would live in `replica.go` and would perform the proper serialization and checking (gc threshold etc).
</blockquote></details>

Yeah, I like that idea. Thanks! I'll work on that next.
___
*[pkg/storage/rangefeed/processor.go, line 106 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-LIlpdsW9nZIMrJC3HpA:-LIqMW6R5ThkHwz7m3f4:bjcjf2l) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf4f2d479320d8735850e0386ce00fdc1512a4a5/pkg/storage/rangefeed/processor.go#L106)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

what's this for?
</blockquote></details>

It's meant to avoid the assertion below it when something panics. I'm removing it all though because it was only useful during development.
___
*[pkg/storage/rangefeed/processor.go, line 165 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-LIlqO_t71YKQobDaSyq:-LIqMqjt1Ipfn5T4sPZR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf4f2d479320d8735850e0386ce00fdc1512a4a5/pkg/storage/rangefeed/processor.go#L165)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

log?
</blockquote></details>

Done.
___
*[pkg/storage/rangefeed/processor.go, line 166 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-LIlq_W44Sk22gNBKtGG:-LIqMtnl2sneOioc0mBN:b-dqa0io) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf4f2d479320d8735850e0386ce00fdc1512a4a5/pkg/storage/rangefeed/processor.go#L166)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

do you also need to select `ctx.Done` to make the leak detector happy?
</blockquote></details>

Good point. I'm just going to close the channel instead.
___
*[pkg/storage/rangefeed/processor.go, line 253 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-LIlsIMv0DGCoFmaAbVy:-LIqNDdxEije661eidHS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf4f2d479320d8735850e0386ce00fdc1512a4a5/pkg/storage/rangefeed/processor.go#L253)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

wait, has it? looks like the processor goroutine may still be draining events out of out eventsC after this returns
</blockquote></details>

Done.
___
*[pkg/storage/rangefeed/registry.go, line 35 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-LIm6uvV0PE6WplZqaAh:-LIqNQ8q1jgc0-250M60:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf4f2d479320d8735850e0386ce00fdc1512a4a5/pkg/storage/rangefeed/registry.go#L35)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

nit:on->one
</blockquote></details>

Done.
___
*[pkg/storage/rangefeed/registry_test.go, line 131 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-LIm86_mByWJpXCccSDE:-LIqNXWu-ujFM6KZ8rwN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf4f2d479320d8735850e0386ce00fdc1512a4a5/pkg/storage/rangefeed/registry_test.go#L131)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

rAB?
</blockquote></details>

Done.
___
*[pkg/storage/rangefeed/registry_test.go, line 136 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-LIm8CrfAtETpJqC9a-3:-LIqNZY74xNXrqPhu0Pp:b-7s4224) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf4f2d479320d8735850e0386ce00fdc1512a4a5/pkg/storage/rangefeed/registry_test.go#L136)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

nit:3->4
</blockquote></details>

That's not a nit, this was just wrong! Done.
___
*[pkg/storage/rangefeed/resolved_timestamp.go, line 185 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-LImFIK-EXQeYu0riYmI:-LIqNmwo6crIwpRIl2r2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf4f2d479320d8735850e0386ce00fdc1512a4a5/pkg/storage/rangefeed/resolved_timestamp.go#L185)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

nit: "an an" -> "an"
</blockquote></details>

Done.
___
*[pkg/storage/rangefeed/resolved_timestamp.go, line 222 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-LImFaJQ1D7nAyfHfI8x:-LIqNt1n6qoLNew_-BPu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf4f2d479320d8735850e0386ce00fdc1512a4a5/pkg/storage/rangefeed/resolved_timestamp.go#L222)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

nit: unresolvedIntentQueue -> unresolvedTxnHeap
</blockquote></details>

Done.
___
*[pkg/util/hlc/timestamp.go, line 109 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28072#-LIlafCa16vT7p4JERaW:-LIqNvAABGcPsMkzd4Un:b-klwwv8) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf4f2d479320d8735850e0386ce00fdc1512a4a5/pkg/util/hlc/timestamp.go#L109)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

... and clears the logical. (Or you could keep the logical).
</blockquote></details>

Well, it doesn't clear the logical because it only subtracts from the walltime if the logical is 0. Added a bit more to the comment.

**Pull request merged**
