### PR TITLE
sql/schemachanger: prerequisite changes for DROP COLUMN

### PR DESCRIPTION
**Pull request by ajwerner**
This PR comes in a number of commits and is best reviewed commit-by-commit. This PR contains cleanup needed to implement `DROP COLUMN` (#84072). The actual support for that feature will follow in a separate PR.

* Two commits do some internal refactoring of the builder.
* The next commit adjust the planning rules which over-constrained the graph.
* The next fixes a rather thorny bug related to multiple dep edges between the same two nodes not being handled correctly.
* The next commit augments descriptor decomposition to include columns referenced in expressions.
* The next commit adds an `IndexSet` to `catid`.
* The next commit fixes a bug which prevents adding a dropping index back to a table.
* The next commit reworks `MakeFirstMutationPublic` in order to make introducing a new filter easier.
* Fixes a bug in scstage which lead to ignoring revertibility in the Statement and PreCommit phases

### CODE REVIEW

**Comment by ajwerner** [comment]
This needs another commit to make the changefeed behavior happy, and maybe there's a `sql` test or two which needs tweaking, but this is ready for an early read.

**Review by postamar — COMMENTED** [review]
In light of the above comment I reviewed all but the last commit. I recommend you put up a separate PR with these so that we can ship these welcome changes right away. The only major comment I have is that if you need to track referenced columns in existing expressions then you should add those IDs to the `Expression` element building block and populate them during `scdecomp`.

> Reviewed 2 of 2 files at r1, 3 of 3 files at r2, 8 of 8 files at r3, 11 of 11 files at r4, 2 of 2 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, 5 of 5 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84157#-:-N6rkxzN0mOKrrBcHUjR:b-1u70s4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[`-- commits` line 42 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/84157#-N6rtiUH0Fxc0YXrUAGr):*
reword
___
*[`pkg/sql/catalog/index_id_set.go` line 90 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/84157#-N6rtWFn5JL2FP0ZAnQk:-N6rtWFoEjlqfiBb3Es7:bcmz8lv) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eb9993e3719b407f0e70b7ff4a21312b4cfdb49/pkg/sql/catalog/index_id_set.go#L90)):*
> ```Go
> // numbers are shown as ranges. For example, for the set {1, 2, 3  5, 6, 10},
> // the output is "(1-3,5,6,10)".
> func (s IndexIDSet) String() string { return s.set.String() }
> ```

This is all fine but should we move this and its cousins to `catid`?
___
*[`pkg/sql/schemachanger/scbuild/builder_state.go` line 559 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/84157#-N6rqcKMAySkAD56_KIA:-N6rqcKMAySkAD56_KIB:b-7h5k1u) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f9d11319b9f6b07af63452de89a7255314f9195/pkg/sql/schemachanger/scbuild/builder_state.go#L559)):*
> ```Go
> 	}
> 	return cols
> }
> ```

Shouldn't these column references be in the `scpb.Expression` element instead, and populated by `scdecomp`?
___
*[`pkg/sql/schemachanger/scplan/plan_explain.go` line 237 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84157#-N6rnadi1M984jGnbsn7:-N6rnadi1M984jGnbsn8:b-6ocqhe) ([raw file](https://github.com/cockroachdb/cockroach/blob/8584018942a29f610c0df821c7781832284d8740/pkg/sql/schemachanger/scplan/plan_explain.go#L237)):*
> ```Go
> 					}
> 					rn.AddLine(fmt.Sprintf("rules: [%s]", strings.Join(rules, ", ")))
> 				}
> ```

Can you treeprinterify the rules to have them printed as separate tree nodes instead, or at least on separate lines? It's good to print them all, but like this it won't age well.
___
*[`pkg/sql/schemachanger/scplan/internal/rules/dep_index_and_column.go` line 366 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84157#-N6rlfCc2UOVV2X4b-ii:-N6rlfCc2UOVV2X4b-ij:bmi5wuo) ([raw file](https://github.com/cockroachdb/cockroach/blob/3105540fa67c6ea7d6934d7c48020dbc473ab1dc/pkg/sql/schemachanger/scplan/internal/rules/dep_index_and_column.go#L366)):*
> ```Go
> 	)
> 
> 	// TODO(ajwerner): Understand this rule and why it needs to exist.
> ```

The reason the name is tied to the column type instead of the column is because otherwise DROP TABLE would be sad. See rules further below involving `IsRelationBeingDropped` (I thought we'd gotten rid of those? idk)

Whether that still applies is unclear.
___
*[`pkg/sql/schemachanger/scplan/internal/scgraph/graph.go` line 375 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84157#-N6rplwX4EB8qy_qO7WF:-N6rplwX4EB8qy_qO7WG:b1gu3jm) ([raw file](https://github.com/cockroachdb/cockroach/blob/8584018942a29f610c0df821c7781832284d8740/pkg/sql/schemachanger/scplan/internal/scgraph/graph.go#L375)):*
> ```Go
> 		if de, ok := e.(*DepEdge); ok {
> 			sb.WriteString(de.rules.String())
> ```

unintentional newline?
___
*[`pkg/sql/logictest/testdata/logic_test/new_schema_changer` line 176 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84157#-N6rpt1U1N-HPwDL2vXH:-N6rpt1U1N-HPwDL2vXI:b-7m35xn) ([raw file](https://github.com/cockroachdb/cockroach/blob/8584018942a29f610c0df821c7781832284d8740/pkg/sql/logictest/testdata/logic_test/new_schema_changer#L176)):*
> ```
>                   RunningStatus: all stages completed
> ```

noise
___
*[`pkg/sql/schemachanger/scplan/plan_test.go` line 176 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84157#-N6rq4fIEbz4ZllkXHJ-:-N6rq4fIEbz4ZllkXHJ0:ba8llhm) ([raw file](https://github.com/cockroachdb/cockroach/blob/8584018942a29f610c0df821c7781832284d8740/pkg/sql/schemachanger/scplan/plan_test.go#L176)):*
> ```Go
> 				screl.ElementString(de.To().Element()), de.To().CurrentStatus)
> 			fmt.Fprintf(&deps, "  kind: %s\n", de.Kind())
> 			fmt.Fprintf(&deps, "  rule: %s\n", de.RuleNames())
> ```

s/rule/rules/

**Review by ajwerner — COMMENTED** [review]
TFTR!

I've peeled the last commit off of this PR and reworked the descriptor so this can merge. I'll put up the last commit separately.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84157#-:-N6up9CJDf938PsguoB6:b-m3xj4e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)

___
*[`-- commits` line 42 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/84157#-N6rtiUH0Fxc0YXrUAGr):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

reword
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/scplan/plan_explain.go` line 237 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84157#-N6rnadi1M984jGnbsn7:-N6un9LM3sl-xjlnSl6N:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8584018942a29f610c0df821c7781832284d8740/pkg/sql/schemachanger/scplan/plan_explain.go#L237)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Can you treeprinterify the rules to have them printed as separate tree nodes instead, or at least on separate lines? It's good to print them all, but like this it won't age well.
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/scplan/internal/rules/dep_index_and_column.go` line 366 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84157#-N6rlfCc2UOVV2X4b-ii:-N6unB0c4M9-7lacK7P7:bb6sh2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/3105540fa67c6ea7d6934d7c48020dbc473ab1dc/pkg/sql/schemachanger/scplan/internal/rules/dep_index_and_column.go#L366)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

The reason the name is tied to the column type instead of the column is because otherwise DROP TABLE would be sad. See rules further below involving `IsRelationBeingDropped` (I thought we'd gotten rid of those? idk)

Whether that still applies is unclear.
</blockquote></details>

Ack.
___
*[`pkg/sql/schemachanger/scplan/internal/scgraph/graph.go` line 375 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84157#-N6rplwX4EB8qy_qO7WF:-N6unCGG3lKcs_2p7GPe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8584018942a29f610c0df821c7781832284d8740/pkg/sql/schemachanger/scplan/internal/scgraph/graph.go#L375)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

unintentional newline?
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/new_schema_changer` line 176 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84157#-N6rpt1U1N-HPwDL2vXH:-N6unXUEBXTt1Wtj49Oj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8584018942a29f610c0df821c7781832284d8740/pkg/sql/logictest/testdata/logic_test/new_schema_changer#L176)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

noise
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/scplan/plan_test.go` line 176 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/84157#-N6rq4fIEbz4ZllkXHJ-:-N6unvZhBtCM4GKW1i5y:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8584018942a29f610c0df821c7781832284d8740/pkg/sql/schemachanger/scplan/plan_test.go#L176)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

s/rule/rules/
</blockquote></details>

Done.
___
*[`pkg/sql/catalog/index_id_set.go` line 90 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/84157#-N6rtWFn5JL2FP0ZAnQk:-N6uVWSf1aS7S1HvlZf0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eb9993e3719b407f0e70b7ff4a21312b4cfdb49/pkg/sql/catalog/index_id_set.go#L90)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

This is all fine but should we move this and its cousins to `catid`?
</blockquote></details>

Done.
___
*[`pkg/sql/schemachanger/scbuild/builder_state.go` line 559 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/84157#-N6rqcKMAySkAD56_KIA:-N6uVZz66ZJRAboFRY6T:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f9d11319b9f6b07af63452de89a7255314f9195/pkg/sql/schemachanger/scbuild/builder_state.go#L559)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Shouldn't these column references be in the `scpb.Expression` element instead, and populated by `scdecomp`?
</blockquote></details>

Done.

**Review by postamar — APPROVED** [review]
:lgtm: 

> Reviewed 53 of 53 files at r11, 3 of 3 files at r12, 6 of 8 files at r13, 10 of 12 files at r14, 8 of 11 files at r15, 2 of 6 files at r16, 1 of 5 files at r17, 9 of 9 files at r18, 4 of 4 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84157#-:-N6wcQaD5fcwv9uAQfo9:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Pull request merged**
