### PR TITLE
sqlstats: increase in-memory fingerprint limit from 5000 to 7500

### PR DESCRIPTION
**Pull request by xinhaoz**
Previously we set the in-memory fingerprints for sql stats to be capped at 5000 each for statemnts and transactions. We've found that 7500 is a more suitable number that will prevent dropped stats for most workloads we have this data for.

Before:
BenchmarkSqlStatsMaxFlushTime/single-application/writes=insert/10000-fingerprints-10   1   13005720666 ns/op
BenchmarkSqlStatsMaxFlushTime/single-application/writes=update/10000-fingerprints-10   1   15769446916 ns/op

After:
BenchmarkSqlStatsMaxFlushTime/single-application/writes=insert/15000-fingerprints-10   1   19813686375 ns/op
BenchmarkSqlStatsMaxFlushTime/single-application/writes=update/15000-fingerprints-10   1   23514272626 ns/op

Release note: None

Epic: CRDB-37544

### CODE REVIEW

**Review by dhartunian — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125343)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @xinhaoz)

___
*[`-- commits` line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125343#-O-1e8AT2LpTXPsoR7d9):*
is there something specific I'm supposed to glean from these benchmarks?

**Review by xinhaoz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125343)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @dhartunian)

___
*[`-- commits` line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125343#-O-1e8AT2LpTXPsoR7d9):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

is there something specific I'm supposed to glean from these benchmarks?
</blockquote></details>

Previously we had values for these settings that took well over the flush interval of 10m since we didn't run microbenchmarks like this. Given that I thought it might be important to continue to roughly track what the range in time for a flush would be when hitting these limits to give us an idea of what to expect in production (although this would be in more or less uninteresting conditions) and make sure nothing is out of the ordinary. Perhaps it would be good to set a threshold we want to stay under but I'm not sure how we'd go about deciding what that would be. Open to suggestions here on setting that guideline.

**Review by dhartunian — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125343#-:-O-6nBLfEff1wfqi46hB:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @abarganier and @xinhaoz)

___
*[`-- commits` line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125343#-O-1e8AT2LpTXPsoR7d9):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Previously we had values for these settings that took well over the flush interval of 10m since we didn't run microbenchmarks like this. Given that I thought it might be important to continue to roughly track what the range in time for a flush would be when hitting these limits to give us an idea of what to expect in production (although this would be in more or less uninteresting conditions) and make sure nothing is out of the ordinary. Perhaps it would be good to set a threshold we want to stay under but I'm not sure how we'd go about deciding what that would be. Open to suggestions here on setting that guideline.
</blockquote></details>

Gotcha. SGTM. just note in commit message what someone is supposed to glean from it in the future.

Generally, when benches are posted it's because the "after" is faster or uses less memory. It's just worth acknowledging in this case that it's higher but well within expected bounds.

**Comment by xinhaoz** [comment]
Ack, TFTR!
bors r+

**Pull request merged**
