### PR TITLE
logictest: add a new file for testing blathers, to be deleted soon

### LINKED ISSUE #127706: blathers test
This is a test for the blathers ability to auto-apply labels.

Jira issue: CRDB-40561

### LINKED ISSUE #127712: blathers test 2
This is a test for the blathers ability to auto-apply labels.

Jira issue: CRDB-40563

### PR DESCRIPTION
**Pull request by rytaft**
Fixes #127706
Closes #127712

Release note: None

### CODE REVIEW

**Comment by rytaft** [comment]
blathers backport 23.1

**Comment by rytaft** [comment]
blathers backport 22.2

**Review by rail — APPROVED** [review]

**Comment by rytaft** [comment]
Thanks!

bors r+

**Comment by rytaft** [comment]
blathers backport 23.2

**Pull request merged**
