### PR TITLE
insights: enable the anomaly detector

### PR DESCRIPTION
**Pull request by matthewtodd**
This change turns on the insights "anomaly detector" by default,
catching statement executions in the >p99 latency for their fingerprint
that are also far enough away from median latency and above a (default
50ms) threshold.

Release justification: Category 2: Bug fixes and low-risk updates to new
functionality.

Release note (ops change): The `sql.insights.anomaly_detection.enabled`
cluster setting now defaults to true, and the
`sql.insights.anomaly_detection.latency_threshold` cluster setting now
defaults to 50ms, down from 100ms to complement the fixed-threshold
detector's default of 100ms.

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
if the user fits both the anomaly detector and the "regular" detector, you will see one row for each, or just one row?

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86673#-:-NAA_9Em5Ne6bRDdn7ox:brxbizx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @matthewtodd)

**Review by maryliag — COMMENTED** [review]
*if the query fits

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86673#-:-NAA_KtGAET2wIJviHej:bj91xrb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @matthewtodd)

**Review by matthewtodd — COMMENTED** [review]
Good q! Just the one row. (That's the point of the [compositeDetector](https://github.com/cockroachdb/cockroach/blob/823e3a77d7fc0f46a0837ab881b2fac62fd8519e/pkg/sql/sqlstats/insights/detector.go#L30-L51).)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86673#-:-NAArJs19Jd8UHARxCTm:b2pmb7r)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @matthewtodd)

**Review by maryliag — APPROVED** [review]
Awesome! :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86673#-:-NAAsOPpAFRXcoWIatTX:b-i581jd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @matthewtodd)

**Comment by matthewtodd** [comment]
I watched the anomaly detector's memory usage while running the ycsb-b workload. With 22 total statement fingerprints, memory reached 37KiB then settled down at just under 15 KiB.

Our default memory limit of 1MiB means we would track somewhere in the range of 600-1500 distinct fingerprints.

Screen Shot 2022-08-24 at 12 58 06 PM

**Pull request merged**
