### PR TITLE
sql: support regr_avgx()

### PR DESCRIPTION
**Pull request by obahareth**
Support aggregate function `regr_avgx()`. It referred to the PostgreSQL implementation, but the implementation details follow SQL 2003. See: postgresql.org/docs/10/functions-aggregate.html

See #41274

### CODE REVIEW

**Comment by obahareth** [comment]
I'm fixing the conflicts and pushing a better version of the tests.

**Comment by yuzefovich** [comment]
Hey @obahareth, thanks for pushing this PR out! Is this ready for review?

**Comment by obahareth** [comment]
Hey @yuzefovich, I should have fixed the failing tests/lint issues with this recent push. I think we should be good to go.

How should I handle the conflict with `pkg/sql/execinfrapb/processors_sql.pb.go` seeing as it's a generated file?

**Review by yuzefovich — COMMENTED** [review]
You need to regenerate those files and include the changes to your commit (I usually do `make buildshort`, but I think we also have `make protobuf`).

nit: we try to keep the commit messages with 80 character limit per line.
nit: the commit message should also contain a release note, something like
```
Release note (sql change): Aggregate function `regr_avgx` is now supported.
```

The code looks good to me with minor nits. We also should add some unit tests in `aggregate_builtins_test.go` similar to what we do for other statistics aggregates.

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57295#-:-MNZOF6m0GchrHuJSnh3:b3718kp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @obahareth)

___
*[pkg/sql/distsql/columnar_operators_test.go, line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57295#-MNZPJj55x7d82llKaRn:-MNZPJj55x7d82llKaRo:bv4k609) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec1bb009b01a05ca93efa46e1b8951f881da2731/pkg/sql/distsql/columnar_operators_test.go#L75)):*
> ```Go
> 	execinfrapb.AggregatorSpec_COVAR_POP:            2,
> 	execinfrapb.AggregatorSpec_COVAR_SAMP:           2,
> 	execinfrapb.AggregatorSpec_REGR_AVGX:            2,
> ```

nit: add it as the last entry so that the order is the same as in `processors_sql.proto`.
___
*[pkg/sql/sem/builtins/aggregate_builtins.go, line 2021 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57295#-MNZQ3Yv9ZPe9klrq11Q:-MNZQ3Yv9ZPe9klrq11R:b-b59ujg) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec1bb009b01a05ca93efa46e1b8951f881da2731/pkg/sql/sem/builtins/aggregate_builtins.go#L2021)):*
> ```Go
> }
> 
> // regressionAvgXAggregate represents SQL:2003 average of the independent variable (sum(X)/N)
> ```

nit: we try to keep comments also at 80 character limit, and a period is missing.

**Comment by obahareth** [comment]
Got it, I'll make the changes in a few.

**Comment by obahareth** [comment]
There we go @yuzefovich, I believe I took care of all the comments you had, please let me know if I missed anything.

**Review by yuzefovich — APPROVED** [review]
:lgtm: Thanks for the contribution!

Note: the CI is red due to a flake.

bors r=yuzefovich

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57295#-:-MNiVlpqE5PUsv5ETors:btyh155)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by SWDevAngel** [comment]
@obahareth Hi Omar. Thank you for contributing to CockroachDB this year. As a token of our appreciation we would like to send you a gift. Please DM me on our [community Slack](https://cockroa.ch/slack) `@lisa` so I can send you a link. (If you don’t want a gift, we also have a charitable contribution choice.) All orders need to be in by December 13, so please send this asap. :)

**Pull request merged**
