### PR TITLE
sql: sort overload functions according to search_path

### PR DESCRIPTION
**Pull request by XiaochenCui**
### PR Description

Previously, overload functions were returned without being sorted based on the `search_path`, causing issue #124538.

This PR introduces sorting logic in the `combineOverloads` function and includes a `search_path` argument to address the problem. With this update, users can now override built-in functions using `search_path`.

**Fixes:** #124538

**Release note:** None

### Changes Made
1. **Sorting Logic in `combineOverloads`:** 
   - Implemented sorting based on `search_path` to ensure correct overload resolution.
2. **New Argument:**
   - Added `search_path` as an argument to support user-defined function overrides.
3. **Unit Tests Added:**
   - Added unit tests to cover issue #124538, ensuring proper functionality:
     [udf_override_built_in](https://github.com/XiaochenCui/cockroach/blob/49a3ccb81722841460a45c6bd39bf4960a15c2da/pkg/sql/logictest/testdata/logic_test/udf_override_built_in)

### Questions

As this is my first contribution to CockroachDB, I have a few questions:

1. **Testing `SHOW search_path`:**
   - How can I test the output of the SQL command `SHOW search_path`?
   
2. **SQL Test File Syntax Guide:**
   - Is there a syntax guide for the format of SQL test files (the files in `pkg/sql/logictest/testdata/logic_test/`)? I guessed the syntax by reading the source code, which is inefficient.
   
3. **Checking for `nil` in Interface Arguments:**
   - For arguments with an interface type, what is the recommended way to check if it's `nil`? Comparing to `nil` directly seems insufficient as it may be a `nil` pointer with a concrete type.
   
4. **FunctionClass Constraint:**
   - There is a constraint that all overload functions inside `ResolvedFunctionDefinition.Overloads` should have the same `FunctionClass`. What is the reason for this constraint?
   
5. **`maybeLookupRoutine` Return Value:**
   - The function `maybeLookupRoutine` returns `tree.ResolvedFunctionDefinition` with `FunctionClass` set to `NormalClass`. Shouldn't it be `SQLClass` for UDF (user-defined functions)?

### CODE REVIEW

**Comment by XiaochenCui** [comment]
Some tests failed, I'm working on it.

**Comment by XiaochenCui** [comment]
The core issue described in [issue #124538](https://github.com/cockroachdb/cockroach/issues/124538) is not merely the order of "overloads," but rather the fact that built-in functions are being "preferred" over user-defined functions. 

This preference is evident in the following sections of the code:

- [overload.go: Lines 166-174](https://github.com/XiaochenCui/cockroach/blob/49a3ccb81722841460a45c6bd39bf4960a15c2da/pkg/sql/sem/tree/overload.go#L166-L174)
- [builtins.go: Lines 9243-9254](https://github.com/XiaochenCui/cockroach/blob/49a3ccb81722841460a45c6bd39bf4960a15c2da/pkg/sql/sem/builtins/builtins.go#L9243-L9254)

This preference leads to built-in functions being chosen during the type-checking phase:

- [overload.go: Lines 1257-1259](https://github.com/XiaochenCui/cockroach/blob/49a3ccb81722841460a45c6bd39bf4960a15c2da/pkg/sql/sem/tree/overload.go#L1257-L1259)

The links provided are directed to my fork for context. Please let me know if they should link to the official repository instead. Thank you.

**Comment by XiaochenCui** [comment]
Seems that we don't have a clear overload rule set. I summarized some rules from the current implementation:

- The "preferred" function should be picked.
- Overload functions should be sorted according to "search_path".
- Built-in functions in the "pg_catalog" schema are always "preferred".
- When two overload functions appear with the same signature (name, args, return type), an "ambiguous error" should be thrown out.

**Comment by XiaochenCui** [comment]
Sorry I didn't use a dedicated branch for this pr, should I recreate this pr using a "overload-124538" branch?

**Comment by XiaochenCui** [comment]
I saw these checks have a status of "Waiting for status to be reported" for hours, what's the reason for that?

**Review by rafiss — CHANGES_REQUESTED** [review]
thanks for your contribution! this is looking pretty good

nice work identifying that issue with `PreferredOverload`. i didn't realize that would cause issues here.

> Sorry I didn't use a dedicated branch for this pr, should I recreate this pr using a "overload-124538" branch?

that's fine in this case, since you pushed the change to your own fork.

> I saw these checks have a status of "Waiting for status to be reported" for hours, what's the reason for that?

new contributors need approval in order to run the CI tests. i have started them now, so let's see if any other tests have issues.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126048#-:-O09oSve6DkQiv_Nha4p:ba00ggh)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @XiaochenCui)

___
*[`pkg/sql/sem/tree/function_definition.go` line 442 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126048#-O09mV5u2D1UIhXo-PVW:-O09mV5u2D1UIhXo-PVX:brmtf8n) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f94f5bb8cbcde5291709774d14b6a9d51c41813/pkg/sql/sem/tree/function_definition.go#L442)):*
> ```Go
> 
> func combineOverloads(a, b []QualifiedOverload, path SearchPath) []QualifiedOverload {
> 	// return append(append(make([]QualifiedOverload, 0, len(a)+len(b)), a...), b...)
> ```

nit: remove the commented line
___
*[`pkg/sql/sem/tree/function_definition.go` line 452 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126048#-O09n5qW44Sv4rIahVfc:-O09n5qX9Gng0dwE7noC:b-g3ei5j) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f94f5bb8cbcde5291709774d14b6a9d51c41813/pkg/sql/sem/tree/function_definition.go#L452)):*
> ```Go
> 
> 	// Append overloads to the result according to the schema order in the path.
> 	paths := make(map[string]bool, path.NumElements())
> ```

nit: i think the code would be more clear if the variable name were something like `isSchemaInSearchPath`
___
*[`pkg/sql/sem/tree/function_definition.go` line 485 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126048#-O09ovIiEc-kLTyMgR5T:-O09ovIiEc-kLTyMgR5U:bximo4q) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f94f5bb8cbcde5291709774d14b6a9d51c41813/pkg/sql/sem/tree/function_definition.go#L485)):*
> ```Go
> 	// When the path is specified, the "prefered" attribute is not used.
> 	for i, overload := range result {
> 		overload.PreferredOverload = false
> ```

instead of unconditionally setting `PreferredOverload` to false, i think we should only do this if a user-defined function overload conflicts with a builtin function overload. 

so perhaps in the main loop above, there should be another flag like `foundUDFOverload`, which is set to true if a function that is not from the `pg_catalog`, `crdb_internal`, or `information_schema` schemas is added.
___
*[`pkg/sql/logictest/testdata/logic_test/udf_override_built_in` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126048#-O09nqfuEIef7K3TvF4z:-O09nqfv-8JomudsK6dm:b-2x4214) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f94f5bb8cbcde5291709774d14b6a9d51c41813/pkg/sql/logictest/testdata/logic_test/udf_override_built_in#L2)):*
> ```
> statement ok
> CREATE FUNCTION now() RETURNS TIMESTAMP STABLE LANGUAGE SQL AS $$ SELECT TIMESTAMP '1999-12-31 23:59:59.999999'; $$;
> ```

nit: we can avoid generating new files by adding this test to an existing file. let's put it in: `testdata/logic_test/udf_regressions`

**Comment by rafiss** [comment]
In case you can't see the results, these existing tests failed:
```
=== RUN   TestGetMostSignificantOverload/overloads_from_all_schemas_in_path_but_ambiguous
    overload_test.go:501: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/overload_test.go:501
        	Error:      	An error is expected but got nil.
        	Test:       	TestGetMostSignificantOverload/overloads_from_all_schemas_in_path_but_ambiguous
    --- FAIL: TestGetMostSignificantOverload/overloads_from_all_schemas_in_path_but_ambiguous (0.00s)

**Comment by XiaochenCui** [comment]
@rafiss 

Thank you! I will work on these issues.

**Review by XiaochenCui — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126048)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @rafiss)

___
*[`pkg/sql/sem/tree/function_definition.go` line 485 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126048#-O09ovIiEc-kLTyMgR5T:-O0B_JAr1A0fJqh2gVUN:b-m04tam) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f94f5bb8cbcde5291709774d14b6a9d51c41813/pkg/sql/sem/tree/function_definition.go#L485)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

instead of unconditionally setting `PreferredOverload` to false, i think we should only do this if a user-defined function overload conflicts with a builtin function overload. 

so perhaps in the main loop above, there should be another flag like `foundUDFOverload`, which is set to true if a function that is not from the `pg_catalog`, `crdb_internal`, or `information_schema` schemas is added.
</blockquote></details>

I check the UDF by "overload.Type" attribute. By the way, the squash strategy which is preferred by cockroach leads to the loss of original changes.

**Comment by XiaochenCui** [comment]
Btw, what's the best approach for running pre-commit actions (`./dev generate && ./dev lint && ./dev test`) when my laptop isn't powerful enough? I'm considering using GitHub Actions for this. Any advice would be appreciated.

**Comment by XiaochenCui** [comment]
Hi, @rafiss:
I run the lint and test on my local env and it seems great. Can you start the ci?
Btw, the overload is ambiguous and I'm working on it.
Thanks

**Review by rafiss — COMMENTED** [review]
> Btw, what's the best approach for running pre-commit actions (`./dev generate && ./dev lint && ./dev test`) when my laptop isn't powerful enough? I'm considering using GitHub Actions for this. Any advice would be appreciated.

i normally use `./dev gen`, and only `./dev test` for the packages/tests that are relevant to my changes. it's possible other tests would be affected too, but it's ok to rely on CI to catch that.

---

apologies, i accidentally closed the PR while trying to adjust the release note. could you push it again?

the changes all look good to me. i will merge it once the PR is open again.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126048#-:-O0JnFPV9uf4Nz2_W91L:boh9bzc)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained

___
*[`-- commits` line 25 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126048#-O0JqGj8BldqiK0DbPwA):*
could you add a release note:

    Release note (bug fix): Fixed a bug where a user-defined function that
    shared a name with a builtin function would not be resolved, even if it
    had higher precedence from the search_path variable.
___
*[`pkg/sql/sem/tree/function_definition.go` line 485 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126048#-O09ovIiEc-kLTyMgR5T:-O0JnaqF6rZCSduKxWOu:brl2c8l) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f94f5bb8cbcde5291709774d14b6a9d51c41813/pkg/sql/sem/tree/function_definition.go#L485)):*
> By the way, the squash strategy which is preferred by cockroach leads to the loss of original changes.

we use the Reviewable tool, which does preserve each set of changes

**Pull request closed without merging**
