### PR TITLE
changefeedccl: fix memory leak in deprecatedGcpPubsubClient

### PR DESCRIPTION
**Pull request by wenyihu6**
Previously, `deprecatedGcpPubsubClient` did not close `pubsub.Client` properly
which could lead to memory leaks. This patch fixes the problem by invoking
`pubsub.Client.Close()` during `deprecatedGcpPubsubClient.Close()`.

Epic: none
Release note: Fixed a slow memory leak in deprecated pubsub changefeeds which
can accumulate when restarting/cancelling many deprecated pubsub changefeeds.
The bug had been there since the deprecated pubsub was introduced in 22.1
(beta).

### CODE REVIEW

**Review by rharding6373 — APPROVED** [review]
:lgtm: Nice fix! How did you find this bug? Another motivation to delete this sink implementation in  https://github.com/cockroachdb/cockroach/issues/121249. 

I added backport labels so your fix will be backported.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121817#-:-NujVSfX9N8seMNERtuB:bvsccar)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andyyang890)

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121817)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @wenyihu6)

___
*[`pkg/ccl/changefeedccl/sink_pubsub.go` line 506 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121817#-NujYZSe6-2V3nFrY7Cl:-NujYZSe6-2V3nFrY7Cm:b-oivq9z) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce9609080b277bcb368e114533295cf8318b6c43/pkg/ccl/changefeedccl/sink_pubsub.go#L506)):*
> ```Go
> 		return nil
> 	})
> 	if p.client != nil {
> ```

nit: instead of putting this in `closeTopics` and renaming it, maybe just put it directly in `func (p *deprecatedPubsubSink) Close() error`? And maybe also add a comment explaining why it's necessary.

**Review by wenyihu6 — COMMENTED** [review]
Thanks for adding the backport labels! It was inspired by Yahor in [https://cockroachlabs.slack.com/archives/C9TGBJB44/p1712259683589099](https://cockroachlabs.slack.com/archives/C9TGBJB44/p1712259683589099).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121817#-:-NujYlfMDCYAkzmA2OB6:b-46r85l)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andyyang890)

___
*[`pkg/ccl/changefeedccl/sink_pubsub.go` line 506 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/121817#-NujYZSe6-2V3nFrY7Cl:-NujaSoE4MSRGQ5z0JvR:b-qijoty) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce9609080b277bcb368e114533295cf8318b6c43/pkg/ccl/changefeedccl/sink_pubsub.go#L506)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

nit: instead of putting this in `closeTopics` and renaming it, maybe just put it directly in `func (p *deprecatedPubsubSink) Close() error`? And maybe also add a comment explaining why it's necessary.
</blockquote></details>

Added more comments. `deprecatedPubsubSink.client` is an interface, so `pubsubclient.close()` can't be called directly in `func (p *deprecatedPubsubSink) Close()`.

**Review by andyyang890 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121817#-:-Nujb_tY9yCDxA4_HhtG:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale)

**Comment by wenyihu6** [comment]
The last push was to trigger build - an unrelated test flaked. 

TFTRs!!

bors r=rharding6373,andyyang890

**Pull request merged**
