### PR TITLE
sql: add internal tables cross db refs and interleaved indexes/tables

### LINKED ISSUE #58867: sql: Add SQL command to view existing interleaved and cross database reference usage
Before interleaved tables/indexes and cross-database references are no longer supported, users should be able to query for existing usage from SQL in 21.1. This can be a new `SHOW` command

### PR DESCRIPTION
**Pull request by fqazi**
Fixes: #58867

Previously, users had no way of determining which objects in
their database utilized either deprecated features like
interleaved indexes/tables or cross DB references. This was
inadequate since users need to know which object utilize
this functionality. To address this, this patch introduces
the crdb_internal tables: cross_db_references, interleaved_indexes,
interleaved_tables.

Release justification: Low risk internal tables for detecting
deprecated features.
Release note (sql change): Added crdb_internal tables cross_db_references,
interleaved_indexes, and interleaved_tables for detecting the
deprecated features cross db references and interleaved tables
/ indexes within a given database.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61629)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[pkg/cli/zip_test.go, line 76 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61629#-MVJnuH136hv2dNzRufc:-MVJnuH29dFk3TkSdYtb:b-qvjclg) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d6a1f28a22fe166c46042a637903392780fe436/pkg/cli/zip_test.go#L76)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>   'cross_db_references',
> 	'databases',
> 	'forward_dependencies',
> 	'index_columns',
>   'interleaved_indexes',
>   'interleaved_tables',
> ```
</details>

I think this needs a gofmt
___
*[pkg/sql/crdb_internal.go, line 4034 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61629#-MVJoJdG7VrCvBiUy-o7:-MVJoJdG7VrCvBiUy-o8:b9ssb7v) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d6a1f28a22fe166c46042a637903392780fe436/pkg/sql/crdb_internal.go#L4034)):*
> ```Go
> }
> 
> var crdbInternalInterleavedTables = virtualSchemaTable{
> ```

Is this table useful? I worry that it might be confusing. When would you ever want this and not `interleaved_indexes`?
___
*[pkg/sql/crdb_internal.go, line 4042 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61629#-MVJpaYG5NhuTK2iaN4M:-MVJpaYG5NhuTK2iaN4N:bq5op64) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d6a1f28a22fe166c46042a637903392780fe436/pkg/sql/crdb_internal.go#L4042)):*
> ```Go
> 	parent_table  STRING NOT NULL
> )`,
> 	populate: func(ctx context.Context, p *planner, dbContext *dbdesc.Immutable, addRow func(...tree.Datum) error) error {
> ```

I feel like this `dbContext` may surprise you. Are you familiar with the `"".crdb_internal.interleaved_tables` weird syntax we have for all databases. I think it's just something to be aware of. I suspect that we're going to end up recommending it so we should probably focus on it. 
___
*[pkg/sql/crdb_internal.go, line 4045 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61629#-MVJo-cR2v7kY1yNgepF:-MVJo-cR2v7kY1yNgepG:bfm4v4f) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d6a1f28a22fe166c46042a637903392780fe436/pkg/sql/crdb_internal.go#L4045)):*
> ```Go
> 		return forEachTableDescAll(ctx, p, dbContext, hideVirtual,
> 			func(db *dbdesc.Immutable, schemaName string, table catalog.TableDescriptor) error {
> 				if table.IsInterleaved() {
> ```

total and complete nit: invert this condition and early return? I feel like the code base tends to prefer that pattern. 
___
*[pkg/sql/crdb_internal.go, line 4050 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61629#-MVJpWcr7hhFQNdsk7zw:-MVJpWcr7hhFQNdsk7zx:b-1hnxww) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d6a1f28a22fe166c46042a637903392780fe436/pkg/sql/crdb_internal.go#L4050)):*
> ```Go
> 						ancestor := index.GetInterleaveAncestor(index.NumInterleaveAncestors() - 1)
> 						parentID := ancestor.TableID
> 						parentTable, err := p.Descriptors().GetImmutableTableByID(ctx, p.txn, parentID,
> ```

maybe `forEachTableDescWithTableLookup` which will use the already fetched descriptors. Another thing is that we probably want to look up the parent's database and schema.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61629)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

___
*[pkg/sql/crdb_internal.go, line 4034 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61629#-MVJoJdG7VrCvBiUy-o7:-MVMm92a2TAph4RMHU9D:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d6a1f28a22fe166c46042a637903392780fe436/pkg/sql/crdb_internal.go#L4034)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Is this table useful? I worry that it might be confusing. When would you ever want this and not `interleaved_indexes`?
</blockquote></details>

Done.
___
*[pkg/sql/crdb_internal.go, line 4050 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61629#-MVJpWcr7hhFQNdsk7zw:-MVMfQ505IAvHQK6n-_q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d6a1f28a22fe166c46042a637903392780fe436/pkg/sql/crdb_internal.go#L4050)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

maybe `forEachTableDescWithTableLookup` which will use the already fetched descriptors. Another thing is that we probably want to look up the parent's database and schema. 
</blockquote></details>

Done.

**Review by ajwerner — COMMENTED** [review]
> Reviewed 6 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61629)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[pkg/sql/crdb_internal.go, line 4052 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61629#-MVNeqsV76dD4nTLiA-t:-MVNeqsV76dD4nTLiA-u:b-zfytty) ([raw file](https://github.com/cockroachdb/cockroach/blob/da064d2b9c3c4cb90ff6d7a9c517d808a93234ab/pkg/sql/crdb_internal.go#L4052)):*
> ```
> 					if index.NumInterleaveAncestors() == 0 {
> 						return nil
> 					}
> ```
should this be `continue`? Maybe worth adding a test that would have caught this by having a table with some indexes which are not interleaved?

Perhaps built yourself a closure to invoke per index (I don't feel strongly about that suggestion).
___
*[pkg/sql/logictest/testdata/logic_test/pg_catalog, line 2102 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61629#-MVNeMnU8hK3B5C16ScV:-MVNeMnU8hK3B5C16ScW:b-fmpont) ([raw file](https://github.com/cockroachdb/cockroach/blob/da064d2b9c3c4cb90ff6d7a9c517d808a93234ab/pkg/sql/logictest/testdata/logic_test/pg_catalog#L2102)):*
> ```
> 4294967277  4294967189  0         index columns for all indexes accessible by current user in current database (KV scan)
> 4294967247  4294967189  0         virtual table with interleaved index information
> 4294967248  4294967189  0         virtual table with interleaved table information
> ```

seems stale, may need a `--rewrite`
___
*[pkg/sql/logictest/testdata/logic_test/views, line 905 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61629#-MVNeXpzAnqV2qqzYKjG:-MVNeXpzAnqV2qqzYKjH:b9chdt) ([raw file](https://github.com/cockroachdb/cockroach/blob/da064d2b9c3c4cb90ff6d7a9c517d808a93234ab/pkg/sql/logictest/testdata/logic_test/views#L905)):*
> ```
> statement ok
> DROP TABLE t
> ```

can you check on views which reference types, sequences, and views in other databases?

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61629)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/crdb_internal.go, line 4052 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61629#-MVNeqsV76dD4nTLiA-t:-MVNgyOR7pjm4ov0jumL:b-7hz42j) ([raw file](https://github.com/cockroachdb/cockroach/blob/da064d2b9c3c4cb90ff6d7a9c517d808a93234ab/pkg/sql/crdb_internal.go#L4052)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 					if index.NumInterleaveAncestors() == 0 {
> 						return nil
> 					}
> ```
should this be `continue`? Maybe worth adding a test that would have caught this by having a table with some indexes which are not interleaved?

Perhaps built yourself a closure to invoke per index (I don't feel strongly about that suggestion).
</blockquote></details>

Yes should have been a continue. Done
___
*[pkg/sql/logictest/testdata/logic_test/pg_catalog, line 2102 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61629#-MVNeMnU8hK3B5C16ScV:-MVNnR_G5ml6NMkoMn8Y:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/da064d2b9c3c4cb90ff6d7a9c517d808a93234ab/pkg/sql/logictest/testdata/logic_test/pg_catalog#L2102)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

seems stale, may need a `--rewrite`
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/views, line 905 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61629#-MVNeXpzAnqV2qqzYKjG:-MVNnS445eYTlhlK-Q-A:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/da064d2b9c3c4cb90ff6d7a9c517d808a93234ab/pkg/sql/logictest/testdata/logic_test/views#L905)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

can you check on views which reference types, sequences, and views in other databases?
</blockquote></details>

Done.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61629)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

___
*[pkg/sql/crdb_internal.go, line 4092 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61629#-MVXrlgN8NISP5D0acIh:-MVXrlgO4KfuSlXzsFTH:bs3hxb3) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdbaed1a2f779efd3c3e26e0738f1141b986cd43/pkg/sql/crdb_internal.go#L4092)):*
> ```Go
> 	comment: `virtual table with cross db references`,
> 	schema: `
> CREATE TABLE crdb_internal.cross_db_references (
> ```

nit: this is ugly. 
___
*[pkg/sql/crdb_internal.go, line 4174 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61629#-MVYAY_g8f7LxXrGkkle:-MVYAY_g8f7LxXrGkklf:b-j1o9dj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1fc2643b07aa2bbac1c835481d9e739e759906d/pkg/sql/crdb_internal.go#L4174)):*
> ```
> 					// For sequences check if the sequence is owned by
> 					// a different database.
> ```
I think we also want to check the set of used descriptors. Say you do:

```
CREATE DATABASE db;
CREATE SEQUENCE db.s;
CREATE TABLE t (i INT PRIMARY KEY DEFAULT (nextval('db.s')));
```
We'll have a use reference but not an ownership.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61629)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/crdb_internal.go, line 4174 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61629#-MVYAY_g8f7LxXrGkkle:-MVYK3gi2K0y8QjGGddE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1fc2643b07aa2bbac1c835481d9e739e759906d/pkg/sql/crdb_internal.go#L4174)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 					// For sequences check if the sequence is owned by
> 					// a different database.
> ```
I think we also want to check the set of used descriptors. Say you do:

```
CREATE DATABASE db;
CREATE SEQUENCE db.s;
CREATE TABLE t (i INT PRIMARY KEY DEFAULT (nextval('db.s')));
```
We'll have a use reference but not an ownership. 
</blockquote></details>

Done.

**Review by ajwerner — APPROVED** [review]
:lgtm: 

Unfortunately I think you've got some more tests to rewrite due to the new crdb_internal tables. I'm happy when CI is happy. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61629#-:-MVZnKcO3KbOWCylQNZQ:b-7z2ohr)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

___
*[pkg/sql/crdb_internal.go, line 4129 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/61629#-MVZmHrx46pL4XaqTqVW:-MVZmHrx46pL4XaqTqVX:b-xjn5ho) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd1a7bb06352121268f563a6ae46f0b55eeba7d3/pkg/sql/crdb_internal.go#L4129)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
> 								if referencedTable.GetParentSchemaID() == keys.PublicSchemaID {
> 									refSchemaName = tree.PublicSchema
> 								} else {
> 									schema, err := lookupFn.getSchemaByID(referencedTable.GetParentSchemaID())
> 									if err != nil {
> 										return err
> 									}
> 									refSchemaName = schema.GetName()
> 								}
> ```
</details>

factor out the schema name retrieval onto the `internalLookupCtx`? That code shows up like 5 times.

**Pull request merged**
