### PR TITLE
allow TPC-C partition behavior for clients when data is not partitioned

### PR DESCRIPTION
**Pull request by sploiselle**
Currently, you can only get multiple clients to "collaborate" on a TPC-C run when the actual underlying Cockroach cluster is partitioned. This PR introduces a `--client-partition` flag that lets a client behave in the same way, even when the data isn't partitioned.

The motivation behind this is showing the degraded TPC-C performance of a CockcroachDB cluster when the data isn't partitioned. With the prior configuration, this wasn't possible.

I believe this belongs in the repo rather than on a branch because similar types of tests might be useful in the future.

Release note: None

Release justification: workload-only change.

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm: very nice.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39803#-:-Lmpxok5EXcgc6AkmS72:bhnhlfa)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @sploiselle)

___
*[pkg/workload/tpcc/tpcc.go, line 143 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39803#-Lmpy6Vp-TW7fR-wZiHr:-Lmpy6Vp-TW7fR-wZiHs:bqd5yzt) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aebb49c7ad149ce48d8f386eab80bc4d9b296e4/pkg/workload/tpcc/tpcc.go#L143)):*
> ```Go
> 		))
> 		g.flags.IntVar(&g.partitions, `partitions`, 1, `Partition tables`)
> 		g.flags.IntVar(&g.clientPartitions, `client-partitions`, -1, `Make client behave as if the tables are partitioned, but does not actually partition underlying data. Requires --partition-affinity.`)
> ```

Default this to 0, since that's what we're using as the condition to indicate that it's not active.
___
*[pkg/workload/tpcc/tpcc.go, line 190 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39803#-Lmpwuy5C5DwE3Ga7ELF:-Lmpwuy5C5DwE3Ga7ELG:bbm89f8) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aebb49c7ad149ce48d8f386eab80bc4d9b296e4/pkg/workload/tpcc/tpcc.go#L190)):*
> ```Go
> 					return errors.Errorf(`cannot specify both --partitions and --client-partitions;
> 					--partitions actually partitions underlying data.
> 					--client-partitons only modifies client behavior to access a subset of warehouses. Must be used with --partition-afinity`)
> ```

s/partitons/partitions/

s/afinity/affinity/
___
*[pkg/workload/tpcc/tpcc.go, line 560 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39803#-LmpyHpJ07eM0dqdKoOR:-LmpyHpJ07eM0dqdKoOS:b-p81m7x) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aebb49c7ad149ce48d8f386eab80bc4d9b296e4/pkg/workload/tpcc/tpcc.go#L560)):*
> ```Go
> 	}
> 	var partitionDBs [][]*workload.MultiConnPool
> ```

nit: remove this stray line.

**Comment by nvanbenschoten** [comment]
Could you add:
```
Release justification: workload-only change.
```

to your commit message? I think bors might be complaining about that.

**Comment by sploiselle** [comment]
bors r=nvanbenschoten

**Comment by sploiselle** [comment]
bors r=nvanbenschoten

**Pull request merged**
