### PR TITLE
kv/kvserver/rangefeed: fix catchupIter construction synchronization

### PR DESCRIPTION
**Pull request by ajwerner**
The catchupIter could have been constructed after the state of the underlying
store has changed. In general this doesn't seem like a disaster unless the
range has been removed or the gc threshold has changed and data is gone.

So, maybe it is a disaster.

Release justification: fixes for high-priority or high-severity bugs in
existing functionality

Release note: None

### CODE REVIEW

**Comment by ajwerner** [comment]
Any idea whether this needs a release note, and, if so, what it should contain?

**Review by nvb — COMMENTED** [review]
Thanks!

> Any idea whether this needs a release note, and, if so, what it should contain?

We have no evidence that this has ever actually caused an issue, so I don't think a `Release note (bug fix)` is necessary, but if you wanted to include one, I'd be vague and just say that a "potential race condition" has been fixed.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69613#-:-MiO-auJ3-kqaqH8W9oR:b-553csm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/kv/kvserver/replica_rangefeed.go, line 379 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69613#-MiO-35d5Jpai_D3O7vE:-MiO-35d5Jpai_D3O7vF:b-42sd7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/72ef548a374046a3ff59f18b1cfeb08a7eff0f67/pkg/kv/kvserver/replica_rangefeed.go#L379)):*
> ```Go
> 	rtsIter := func() storage.SimpleMVCCIterator {
> 		// Assert that we still hold the raftMu when this is called to ensure
> 		// that the catchUpIter reads from the current snapshot. The replica
> ```

`s/catchUpIter/rtsIter/`
___
*[pkg/kv/kvserver/rangefeed/processor.go, line 276 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69613#-MiO-Ny96XLicUyrgxrN:-MiO-Ny96XLicUyrgxrO:b7l1qm8) ([raw file](https://github.com/cockroachdb/cockroach/blob/72ef548a374046a3ff59f18b1cfeb08a7eff0f67/pkg/kv/kvserver/rangefeed/processor.go#L276)):*
> ```Go
> 				}
> 			}
> 			if err := stopper.RunAsyncTask(ctx, "rangefeed: output loop", runOutputLoop); err != nil {
> ```

Do we need to close the `catchupIter` (if non-nil) on the error path here? Or maybe bake that ownership into `r.disconnect`?

**Review by ajwerner — COMMENTED** [review]
I added another commit to fix the inconsistent capitalization of `catchup` and `catchUp`. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69613#-:-MiO3Ylx3i4uoSm_LE29:bflal26)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_rangefeed.go, line 379 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69613#-MiO-35d5Jpai_D3O7vE:-MiO3hVCAeMf-lnI8Xln:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/72ef548a374046a3ff59f18b1cfeb08a7eff0f67/pkg/kv/kvserver/replica_rangefeed.go#L379)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`s/catchUpIter/rtsIter/`
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/rangefeed/processor.go, line 276 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69613#-MiO-Ny96XLicUyrgxrN:-MiO3iJW46VWsJPB9G1l:b-5fe1ev) ([raw file](https://github.com/cockroachdb/cockroach/blob/72ef548a374046a3ff59f18b1cfeb08a7eff0f67/pkg/kv/kvserver/rangefeed/processor.go#L276)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we need to close the `catchupIter` (if non-nil) on the error path here? Or maybe bake that ownership into `r.disconnect`?
</blockquote></details>

Good catch. Delegated the closing of the iterator to `disconnect` in the error paths.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69613#-:-MiO9MFv-PImDJ9dfX9A:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by ajwerner** [comment]
TFTR!

bors r=nvanbenschoten

**Pull request merged**
