### PR TITLE
sql: support crdb_internal.ranges{_no_leases} for secondary tenants

### PR DESCRIPTION
**Pull request by ecwall**
This PR makes crdb_internal.ranges{_no_leases} and SHOW RANGES
work for secondary tenants.
    
Release note (sql change): crdb_internal.ranges{_no_leases} and
SHOW RANGES statements now work on secondary tenants.

Epic: CRDB-14522

### CODE REVIEW

**Review by knz — APPROVED** [review]
:lgtm: but also get a review from arul.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92131#-:-NIc22fVCj2yRrUTG0dg:bvx6l8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani, @ecwall, @rafiss, @renatolabs, and @srosenberg)

___
*[`pkg/sql/multitenant_admin_function_test.go` line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92131#-NIc1vN-9n2XCIboZBTC:-NIc1vN-9n2XCIboZBTD:bigadvr) ([raw file](https://github.com/cockroachdb/cockroach/blob/56175655486ac94c892dee1669b85b7469018c0d/pkg/sql/multitenant_admin_function_test.go#L71)):*
> ```Go
> 
> 	// TODO(ewall): When moving tenant capability check to KV,
> 	//  merge test w/ SkipSQLSystemTenantCheck variant into single test case if
> ```

nit: remove the extraneous space after `//`

**Review by arulajmani — APPROVED** [review]
Are there any logic tests that used `SHOW RANGES` or the like, that only worked for the system tenant before, but can now be moved such that they run as secondary tenants as well? If so, should we do that either as a separate commit or a new patch entirely? 

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92131#-:-NIcPXs18nFpA5z0BzAv:b-mnxny6)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ecwall, @rafiss, @renatolabs, and @srosenberg)

___
*[`pkg/sql/multitenant_admin_function_test.go` line 309 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92131#-NIcNtty9FWeGI8-ED1S:-NIcNtty9FWeGI8-ED1T:b-ygdfbw) ([raw file](https://github.com/cockroachdb/cockroach/blob/56175655486ac94c892dee1669b85b7469018c0d/pkg/sql/multitenant_admin_function_test.go#L309)):*
> ```Go
> 			false, /* skipSQLSystemTenantCheck */
> 		)
> 		// TODO(ewall): Retain splits after `TRUNCATE` for secondary tenants.
> ```

Let's open an issue about this, if there isn't one? This should be doable now that we've got this `RangeIterator`, right?

**Review by ecwall — COMMENTED** [review]
There are some TTL tests that are commented out that I have a separate ticket for. I will created https://github.com/cockroachdb/cockroach/issues/93148 to look into this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92131#-:-NIckHOC4RylrCkyWBZ8:bca1o7z)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani, @knz, @rafiss, @renatolabs, and @srosenberg)

___
*[`pkg/sql/multitenant_admin_function_test.go` line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92131#-NIc1vN-9n2XCIboZBTC:-NIcka1n9T_IANgQWgGh:b-wfsybx) ([raw file](https://github.com/cockroachdb/cockroach/blob/56175655486ac94c892dee1669b85b7469018c0d/pkg/sql/multitenant_admin_function_test.go#L71)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: remove the extraneous space after `//`
</blockquote></details>

The extra indentation creates a multi-line TODO:

vs

___
*[`pkg/sql/multitenant_admin_function_test.go` line 309 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92131#-NIcNtty9FWeGI8-ED1S:-NIclJV6CCPxCLYbcJV0:b-44ig9e) ([raw file](https://github.com/cockroachdb/cockroach/blob/56175655486ac94c892dee1669b85b7469018c0d/pkg/sql/multitenant_admin_function_test.go#L309)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Let's open an issue about this, if there isn't one? This should be doable now that we've got this `RangeIterator`, right? 
</blockquote></details>

There is already a ticket: https://github.com/cockroachdb/cockroach/issues/82944. 

I am not sure if that was the only thing blocking it though.

**Comment by ecwall** [comment]
bors r=knz,arulajmani

**Pull request merged**
