### PR TITLE
opt: Reorganize code to allow easier testing.

### PR DESCRIPTION
**Pull request by andy-kimball**
Before this change, the opt/xform tests were not able to use the
build.Builder. This is because the opt/build package is dependent
on opt/xform, and Golang doesn't allow circular dependencies.

This change reorganizes and updates files in order to break the
cycle. In particular, the Factory has been made into an interface
and placed in a new "opt" package, along with several other
foundational, but simple classes that many opt packages need to
share. The new set of directories looks like this:

build: build an opt expression from an AST
ops: contains the definitions for opt operators in Optgen format
opt: contains common interfaces and simple classes that other opt
     packages use to interface with one another
optgen: contains the Optgen language compiler and codegen tools
testutils: testing helper functions and packages
xform: the core optimizer files: factory, optimizer, and explorer

Note that the "opt" directory is temporary. Files in that
directory will be moved up one level once we've converted the
existing files (index constraints, old expr, etc.) to use the
new optimization methodology. See README.md in the "opt" directory
for more details.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
The code change LGTM but the structure is non-intuitive: we will have packages `sql/opt/XXX` that depend on `sql/opt`. Usually, it's the other way around..

What packages will the `sql` code depend on? It will have to depend on some `opt/XXX` if `opt` just has interface definitions no?

A possible alternative is to have tests in `xform` that are under package `xform_test`, which can depend on `build`. We would have to export anything needed by the test though.

CC @petermattis too in case he has any thoughts.

**Comment by rytaft** [comment]
:lgtm: assuming you address Radu's concern

---

Reviewed 46 of 46 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/opt/metadata.go, line 38 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22285#-L4HAax5AMVAWGoK4Vyt:-L4HAax5AMVAWGoK4Vyu:b-zhkacp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e54bc346b40550d78ec077d178d332e3aff7d2e7/pkg/sql/opt/opt/metadata.go#L38)):*
> ```Go
> // ColMap provides a 1:1 mapping from one column index to another. It is used
> // by operators that need to match columns from its inputs.
> type ColMap map[ColumnIndex]ColumnIndex
> ```

Should this use Radu's new fast int map?

---

*[pkg/sql/opt/optgen/cmd/optgen/ifactory_gen.go, line 24 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22285#-L4HF7eErKTjM1HjuIcD:-L4HF7eErKTjM1HjuIcE:b-y4fs25) ([raw file](https://github.com/cockroachdb/cockroach/blob/e54bc346b40550d78ec077d178d332e3aff7d2e7/pkg/sql/opt/optgen/cmd/optgen/ifactory_gen.go#L24)):*
> ```Go
> )
> 
> type ifactoryGen struct {
> ```

Can you add a comment to explain how this is different from `factoryGen`?

---

*[pkg/sql/opt/optgen/cmd/optgen/ifactory_gen.go, line 83 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22285#-L4HESwQpv5KoHHp9U3P:-L4HESwQpv5KoHHp9U3Q:b-38lvs3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e54bc346b40550d78ec077d178d332e3aff7d2e7/pkg/sql/opt/optgen/cmd/optgen/ifactory_gen.go#L83)):*
> ```Go
> // filterEnforcerDefines constructs a new define set with any enforcer ops
> // removed from the specified set.
> func filterEnforcerDefines(defines lang.DefineSetExpr) lang.DefineSetExpr {
> ```

Why did you move this? It seems like `factory_gen.go` was the only place it was getting called....

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22285#-:-L4HIWwwuLbZKYLoJzpt:bo0sa1t)*

**Comment by petermattis** [comment]
Having a `sql/opt/opt` package is super awkward, but as long as it is temporary I'm ok with it. Another option is to have a `sql/opt/base` package.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22285#-:-L4HjR0PV_4QKUoxPKmt:b-qhkkyc)*

**Comment by andy-kimball** [comment]
Agree on the awkwardness of `sql/opt/opt`. I thought about `sql/opt/base`, or using the existing `sql/optbase`, but since I'm proposing to put these files in the top-level `opt` directory in the next milestone, I'd like to skip another renaming step from `base` to `opt`.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/opt/metadata.go, line 38 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22285#-L4HAax5AMVAWGoK4Vyt:-L4IR6Sr0hO6IFLtLdhi:blk4onv) ([raw file](https://github.com/cockroachdb/cockroach/blob/e54bc346b40550d78ec077d178d332e3aff7d2e7/pkg/sql/opt/opt/metadata.go#L38)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Should this use Radu's new fast int map?
</blockquote></details>

Yes, good reminder. Done.

---

*[pkg/sql/opt/optgen/cmd/optgen/ifactory_gen.go, line 24 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22285#-L4HF7eErKTjM1HjuIcD:-L4IT2FlvMHEW6oX7bZw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e54bc346b40550d78ec077d178d332e3aff7d2e7/pkg/sql/opt/optgen/cmd/optgen/ifactory_gen.go#L24)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Can you add a comment to explain how this is different from `factoryGen`?
</blockquote></details>

Done.

---

*[pkg/sql/opt/optgen/cmd/optgen/ifactory_gen.go, line 83 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22285#-L4HESwQpv5KoHHp9U3P:-L4IT2zI2mCIYgkJd8Xn:b-31fl9g) ([raw file](https://github.com/cockroachdb/cockroach/blob/e54bc346b40550d78ec077d178d332e3aff7d2e7/pkg/sql/opt/optgen/cmd/optgen/ifactory_gen.go#L83)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why did you move this? It seems like `factory_gen.go` was the only place it was getting called....
</blockquote></details>

I was using it in ifactoryGen, then decided to use genMethodsByTag instead, and forgot to move it back. Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22285#-:-L4IP10PwB95G2UY0ATx:b-bdxujd)*

**Comment by rytaft** [comment]
Reviewed 1 of 46 files at r1, 3 of 6 files at r2.
Review status: 36 of 39 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22285)*

**Pull request merged**
