### PR TITLE
num32: add more functions to the num32 library

### PR DESCRIPTION
**Pull request by andy-kimball**
Add additional numeric functions that vector indexing will use. Use the gonum BLAS library where it gives a performance advantage.

Epic: CRDB-42943

Release note: None

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133417#-:-OAZdj2QAyiR6B9Ju34C:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @mw5h)

___
*[`pkg/util/vector/vector.go` line 156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133417#-OAZYahu59F2fsSXugoW:-OAZYahvCvpFzCXwJEVu:bbrwk5u) ([raw file](https://github.com/cockroachdb/cockroach/blob/29a608ad194e0d7de2b0b66d5a533e77022d8d96/pkg/util/vector/vector.go#L156)):*
> ```Go
> 	// TODO(queries): check for overflow and validate intermediate result if needed.
> 	// NOTE: This does not use the num32.L2Distance function because it needs to
> 	// return a float64 value.
> ```

Do you think we'll use both implementations, or will one go away eventually?

**Comment by andy-kimball** [comment]
*[`pkg/util/vector/vector.go` line 156 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/133417#-OAZYahu59F2fsSXugoW:-OAZpSuUAZk94lEXJ3K8:bdifg8) ([raw file](https://github.com/cockroachdb/cockroach/blob/29a608ad194e0d7de2b0b66d5a533e77022d8d96/pkg/util/vector/vector.go#L156)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Do you think we'll use both implementations, or will one go away eventually?
</blockquote></details>

I don't see how we get rid of one or the other. The results will be different in each case.

**Review by mw5h — APPROVED** [review]
:lgtm:

> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133417#-:-OAZqiYLC1kFwhG5rlFn:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @DrewKimball)

**Comment by andy-kimball** [comment]
bors r=DrewKimball,mw5h

**Pull request merged**
