### PR TITLE
opt,sql: add EXPLAIN (OPT, MEMO) to show optimizer memo

### PR DESCRIPTION
**Pull request by rytaft**
Release note (sql change): Added a new EXPLAIN flag, MEMO, to be used
with `EXPLAIN (OPT)`. When the MEMO flag is passed, a representation of the
optimizer memo will be printed along with the best plan. The MEMO flag
can be used in combination with other flags such as CATALOG and VERBOSE.
For example, `EXPLAIN (OPT, MEMO, VERBOSE)` will print the memo along with
verbose output for the best plan.

### CODE REVIEW

**Comment by rytaft** [comment]
I'd *really* like EXPLAIN (optsteps) or EXPLAIN (optstepsweb), but this seemed like a good (and much simpler) first step.

**Review by cucaroach — APPROVED** [review]
Sweetness!   TIL about explain flags json, deps, catalog, stages etc.   How does this stuff make its way into the docs?   :LGTM:

> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67702#-:-MejXwTk2g2_6heub9Bi:buwgbk8)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/exec/execbuilder/testdata/explain, line 1593 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67702#-MejYJRz-sfIAoQZiTua:-MejYJRz-sfIAoQZiTub:b7f4bbp) ([raw file](https://github.com/cockroachdb/cockroach/blob/8afd198cdf2fc53878ae6d6d006b96d5bc14a643/pkg/sql/opt/exec/execbuilder/testdata/explain#L1593)):*
> ```
>   size: 1 column, 1 row
> 
> # Tests for EXPLAIN (OPT, MEMO)
> ```

nit: missing period

**Comment by jordanlewis** [comment]
Awesome, this is really cool. Yeah EXPLAIN(optsteps) would really be a dream, wouldn't it.

**Comment by jordanlewis** [comment]
For inspiration, have you seen Go's equivalent of `optstepsweb`? It's an HTML page that you can ask it to generate that shows all of the different SSA optimization passes.

Here is an example (some passes are folded, so click around the page): https://segflow.github.io/code/go-compiler-optimization/optimized-map-ssa.html

And here are some docs: https://github.com/golang/go/blob/master/src/cmd/compile/internal/ssa/README.md

**Review by rytaft — COMMENTED** [review]
TFTR!

> How does this stuff make its way into the docs?

The docs team uses the release notes to update the docs, but if you think something is missing from the current docs, feel free to open an issue in the cockroachdb/docs repo.

> For inspiration, have you seen Go's equivalent of optstepsweb? 

Cool, thanks for sharing!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67702#-:-Mel1V2wDLVfMmsV3zLW:b-n4b05a)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @RaduBerinde)

___
*[pkg/sql/opt/exec/execbuilder/testdata/explain, line 1593 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67702#-MejYJRz-sfIAoQZiTua:-Mel1Rsy3bmXG8p6-8w0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8afd198cdf2fc53878ae6d6d006b96d5bc14a643/pkg/sql/opt/exec/execbuilder/testdata/explain#L1593)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

nit: missing period
</blockquote></details>

Done.

**Pull request merged**
