### PR TITLE
When start=end, ContainsKeyRange should return true if the keys fall …

### LINKED ISSUE #1069: Scan with same start/end key causes infinite loop
A scan with the same start and end key currently causes cockroach to enter an infinite loop inside of DistSender.  

Relevant lines: https://github.com/cockroachdb/cockroach/blob/master/kv/dist_sender.go#L563-L567

DistSender always retries immediately when encountering a RangeKeyMismatch or RangeNotFound, assuming that these are the result of an addressing error.  However, attempting a Scan with the same start and end key _also_ returns a RangeKeyMismatch error.

The immediate fix is to assert at a higher level that incoming scans have a different start and end key. We may also want to consider whether there needs to be a check on this behavior in distSender which resulted in a rapid infinite loop.

### PR DESCRIPTION
**Pull request by spencerkimball**
…within the range.

Added a unittest for scan where start key == end key.

Fixes #1069

### CODE REVIEW

**Comment by tamird** [comment]
LGTM

**Comment by bdarnell** [comment]
This is better than the infinite loop, but isn't `StartKey == EndKey` an invalid range? It seems better to detect this and return an error than to treat it as a zero-width range at StartKey. For that matter, don't we have the same problem when `StartKey > EndKey`, even after this change?

**Comment by spencerkimball** [comment]
We may have a problem with startKey > endKey but that's a separate concern.
I don't believe that startKey==endKey is invalid. It's just zero length.  I
definitely don't have a problem with this behavior. I struggle to define
this as invalid, although I guess I wouldn't fight too hard if every other
system considered this an error. I think it's up to us. How strongly do you
feel it should be an error?

**Comment by bdarnell** [comment]
I think it should be an error for internal consistency regardless of what other systems do; we always define StartKey as inclusive and EndKey as exclusive so that the EndKey of one range is the StartKey of the next. More importantly, a "zero-length range" is a useless concept. A Scan with StartKey==EndKey will never return any results even though it looks like it ought to return the value at StartKey (if any). This bug was discovered due to a bug in a client program that was *unintentionally* sending requests with StartKey==EndKey. Allowing these requests will simply invite bugs.

**Comment by spencerkimball** [comment]
Hmm, ok that sounds like a strong opinion. I'll change it. Perhaps this and
others like it (startKey < endKey) should be returning something other than
RangeKeyMismatch--RangeKeyMismatch should be reserved for range descriptor
addressing errors.

**Comment by bdarnell** [comment]
Yes. RangeKeyMismatch means "retry this somewhere else"; whenever we know that an operation will fail wherever it is tried we need to return a non-retryable error.

**Pull request merged**
