### PR TITLE
builtins: add to_tsvector {phrase,plain,}to_tsquery

### PR DESCRIPTION
**Pull request by jordanlewis**
Updates: https://github.com/cockroachdb/cockroach/issues/41288
Epic: CRDB-22357

Release note (sql change): add the to_tsvector, to_tsquery, phraseto_tsquery, and plainto_tsquery builtins which parse input documents into tsvectors and tsqueries respectively.

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
cool how we're growing this functionality!

can we adapt more tests from PG? see the following files
```
src/test/regress/expected/json.out
src/test/regress/expected/tsdicts.out
src/test/regress/expected/tstypes.out
src/test/regress/expected/tsearch.out
src/test/regress/expected/jsonb.out
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92966#-:-NIXycZF5Ri34l3PUWj4:b-xwvqag)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[`pkg/sql/sem/builtins/tsearch_builtins.go` line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92966#-NIXt6Ae5NHFvyD9i0lm:-NIXt6Af3KcQhB1Fbz3w:bk7qn21) ([raw file](https://github.com/cockroachdb/cockroach/blob/3446576e90dc81c69c9868c41bdfd5a95d78224f/pkg/sql/sem/builtins/tsearch_builtins.go#L51)):*
> ```Go
> 			Info: "Converts text to a tsvector, normalizing words according to the specified or default configuration. " +
> 				"Position information is included in the result.",
> 			Volatility: volatility.Immutable,
> ```

in postgres, this is stable (as are all  the other ones you added). any reason to make ours different?
___
*[`pkg/sql/sem/builtins/tsearch_builtins.go` line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92966#-NIXvtDEB8_RKYSq0P7e:-NIXvtDEB8_RKYSq0P7f:b-5o4mrd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3446576e90dc81c69c9868c41bdfd5a95d78224f/pkg/sql/sem/builtins/tsearch_builtins.go#L89)):*
> ```Go
> 			},
> 			Info: "Converts text to a tsquery, normalizing words according to the specified or default configuration." +
> 				" The & operator inserted between each token in the input.",
> ```

missing word in description?
___
*[`pkg/sql/sem/builtins/tsearch_builtins.go` line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92966#-NIXvvO96-KI0Z6YPz6E:-NIXvvO96-KI0Z6YPz6F:b-6d3g6i) ([raw file](https://github.com/cockroachdb/cockroach/blob/3446576e90dc81c69c9868c41bdfd5a95d78224f/pkg/sql/sem/builtins/tsearch_builtins.go#L108)):*
> ```Go
> 			},
> 			Info: "Converts text to a tsquery, normalizing words according to the specified or default configuration." +
> 				" The <-> operator inserted between each token in the input.",
> ```

missing word?
___
*[`pkg/util/tsearch/tsquery.go` line 375 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92966#-NIXy6heEGUoky15AtjK:-NIXy6heEGUoky15AtjL:b-30fwdd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3446576e90dc81c69c9868c41bdfd5a95d78224f/pkg/util/tsearch/tsquery.go#L375)):*
> ```Go
> 		switch len(lexemeTokens) {
> 		case 0:
> 			// TODO(jordan): we need to do different handling here. We found a stop
> ```

does this mean there's a correctness issue? i don't think we should merge it then. or at least, make a loud error rather than a silent correctness bug

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92966)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/sem/builtins/tsearch_builtins.go` line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92966#-NIXt6Ae5NHFvyD9i0lm:-NIt6DJc4qmqhE9xuEUF:bkmzqe6) ([raw file](https://github.com/cockroachdb/cockroach/blob/3446576e90dc81c69c9868c41bdfd5a95d78224f/pkg/sql/sem/builtins/tsearch_builtins.go#L51)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

in postgres, this is stable (as are all  the other ones you added). any reason to make ours different?
</blockquote></details>

The particular overloads of the builtins in this file all should be immutable (and are actually so on Postgres). There are a few overloads for each builtin - the immutable one is the one that does have the config passed in as the first parameter. There are also overloads (that we'll add later) that are stable, these are the ones that pick up the configuration from the session variable)
___
*[`pkg/sql/sem/builtins/tsearch_builtins.go` line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92966#-NIXvtDEB8_RKYSq0P7e:-NIt6kgV5BOiOzi31apo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3446576e90dc81c69c9868c41bdfd5a95d78224f/pkg/sql/sem/builtins/tsearch_builtins.go#L89)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

missing word in description?
</blockquote></details>

Done.
___
*[`pkg/sql/sem/builtins/tsearch_builtins.go` line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92966#-NIXvvO96-KI0Z6YPz6E:-NIt6l-z8TLRQNHiVceh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3446576e90dc81c69c9868c41bdfd5a95d78224f/pkg/sql/sem/builtins/tsearch_builtins.go#L108)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

missing word?
</blockquote></details>

Done.
___
*[`pkg/util/tsearch/tsquery.go` line 375 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/92966#-NIXy6heEGUoky15AtjK:-NP5o-me7FXZUAmwQlax:b7hy91s) ([raw file](https://github.com/cockroachdb/cockroach/blob/3446576e90dc81c69c9868c41bdfd5a95d78224f/pkg/util/tsearch/tsquery.go#L375)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

does this mean there's a correctness issue? i don't think we should merge it then. or at least, make a loud error rather than a silent correctness bug
</blockquote></details>

No, this doesn't come into play until we add configurations that have stop words. That will come soon but we'll fix it then!

**Comment by jordanlewis** [comment]
One thing to note - this PR doesn't get us full compatibility with the "Postgres text search tokenizer", the thing that is exposed via `ts_parse`, which is essentially the first pass of text search document processing. For reference, the phases are:

1. Parse the input document into "tokens" (this phase separates text by whitespace and so on)
2. "Lexize" each token into lexemes (this phase does stemming + stopword elimination which will come soon in another PR)
3. Put all of the lexemes into a tsvector or tsquery for storage or retrieval

The Postgres parser is really complex and detailed, and I don't believe it's worth it to support the full parser at this time. Here is the list of tokens the parser can output: https://www.postgresql.org/docs/current/textsearch-parsers.html This PR only outputs one token type, `ascii`.

It may sound like sacrilege to not merge with full compatibility, but I think in this case it's okay. Reasons:

1. Text search isn't expected to be "precise" like other database facilities
3. Many of the token types seem fairly exotic, like XML tag / entity
4. The main functionality of breaking up text and stemming it will be preserved
5. The token types are exposed for use with configurable / plugin dicitionaries, which we won't support

If you disagree, I still want to merge this as-is because I want to get going merging the rest of this functionality. We can come back and add the missing token types and so on later. I've filed the missing token types issue here: #97669

**Review by rafiss — APPROVED** [review]
that sounds good to me. there's lots of good functionality in this

**Comment by jordanlewis** [comment]
Thanks for the review!

bors r+

**Pull request merged**
