### PR TITLE
roachtest/tests: move prometheus client interface to separate package

### PR DESCRIPTION
**Pull request by ajwerner**
This way mockgen does not depend on the `roachtest/tests` package.

Touches #76851.

Release justification: non-production code change

Release note: None

### CODE REVIEW

**Review by irfansharif — APPROVED** [review]

**Comment by irfansharif** [comment]
Bump, do we want to merge this? (needs release justification). Just seeing what else is left to do for #76851.

**Comment by ajwerner** [comment]
TFTR!

bors r=irfansharif

**Pull request merged**
