### PR TITLE
roachprod: support staging local non-linux binaries

### PR DESCRIPTION
**Pull request by nvb**
This commit adds support to `roachprod stage` to install binaries to a
local non-linux cluster. For instance, Mac users can now use roachprod
stage to stage Darwin binaries on their local cluster instead of needing
to either compile the binary themselves or download it separately.

Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
It can be useful to download linux binaries on the mac. Perhaps add a flag to override runtime.GOOS? Otherwise :lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40198#-:-LnrWWEw-Pn2Ge49vqDw:b-xq1u8d)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

**Comment by nvanbenschoten** [comment]
> Perhaps add a flag to override runtime.GOOS?

Done.

**Review by ajwerner — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40198#-:-LnsOAkV-_n9oi5rzO8a:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @andreimatei)

**Pull request merged**
