### PR TITLE
storage/keys: improve documentation around Meta1KeyMax special-case

### LINKED ISSUE #18998: keys: meta/system split key at wrong point
Continuation of discussion in https://github.com/cockroachdb/cockroach/pull/18709#issuecomment-331607396.

> While making this change I had a realization that I hope is wrong. I think that
> we'll be able to have 3 levels of descriptor indirection for the last range in the
> system once we allow meta2 splits again. To make that concrete, take for
> example:
> ```
>  r1: [/min,/meta2/)
>  r2: [/meta2/,/meta2/m)
>  r3: [/meta2/m,/metaMax) <- can't split at meta2max
>  r4: [/metaMax,keymax)
> ```
> r4's desc lives on r3, r3's desc lives on r2 (**!**), and r2's desc
> lives on r1. Remember `meta(MetaMax) -> /meta2/metaMaxByte`.
> The problem here is that the `EndKey` of a range that contains meta2
> descriptors doesn't need to be a meta2 key itself, meaning that `RangeMetaKey`
> will give a meta2 key address. Consequences of this include that evicting
> `keymax` from the RangeDescriptorCache will evict two meta2 descriptors,
> but there are a lot more.
> 
> Is this ok? Do we expect to have meta2 descriptors stored in meta2 ranges?
> For reference, I think the fundamental issue here was also the cause of https://github.com/cockroachdb/cockroach/pull/1206.
> Life would be so much easier if we stored meta keys at `meta(desc.StartKey)`.

@bdarnell reponded with:

> No, we don't. Meta1 lookups are supposed to be sufficient for finding all meta2 entries. But while it's surprising, I'm not immediately seeing any severe consequences here (I'm probably just missing things). It helps that with our current automatic split policies, the last range in the system is always empty.

The underlying issue here is that even though ranges are inclusive on the start key but exclusive on the end key, we store them at `RangeMetaKey(endKey)`. Because of this, we've had to make workarounds like #1206. Essentially, what this is doing is extending the meta range so that the user range's endkey fits inside of it. This workaround can be pictured by:

```
meta1 -> ["/meta1/a","/meta1/z".next().next())
meta2 -> ["/meta2/a","/meta2/z".next())
user  -> ["a","z")
```

At this point, I'm not sure there's much we can do about this parasitic underlying issue. However, we can at least commit to the workaround fully. There are two ways we can do this in practice.
1. instead of `MetaMax = roachpb.Key{metaMaxByte}` where `metaMaxByte = '\x04'`, we can have `MetaMax = Meta2Prefix.PrefixEnd()`. This would allow `RangeMetaKey(MetaMax)` to address into `Meta1`
2. instead of `Meta1Span` ending at `Meta2Prefix`, it would end at `Meta2Prefix.Next()`. 

In terms of a migration, I think the second approach is easier. No existing cluster should have allowed any splits in their meta2 range, let alone managed to split meta1 and meta2 exactly at `Meta2Prefix`. Because of this, the following change should be harmless (other than making me feel bad):

```
Meta1Span = roachpb.Span{Key: roachpb.KeyMin, EndKey: Meta2Prefix}
would become
Meta1Span = roachpb.Span{Key: roachpb.KeyMin, EndKey: Meta2Prefix.Next()}
```

### PR DESCRIPTION
**Pull request by nvb**
Closes #18998.

The concern about 3 levels of descriptor indirection raised in #18998
was a result of me not understanding how we store range descriptors
for ranges that span meta2 and userspace keys. It turns out that
starting all the way back in #134 we began writing *two* meta records
for ranges that span the meta2 and userspace keys. This allows us
to avoid the indirection issue because it ensures that
`[Meta1Prefix,Meta1KeyMax]` contains descriptors spanning the entire
meta2 range. This change improves the documentation describing this
subtle special-case.

The change also correct the explanation about why we can't allow
splits at `Meta2KeyMax`. If we were to allow splits at this key,
the role of `Meta1KeyMax` would be overloaded and we would end up
overwriting range descriptors, preventing range lookups from working
properly. This was fixed in #1206, but had never been properly
documented.

Release note: None

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
I do think I see another issue here. I think it's possible with our handling of `Meta1KeyMax` to result in an incorrect ordering of range descriptors in meta1. The scenario I'm picturing is the case where a split occurs between `Meta2KeyMax` (`\x03ffff`) and `MetaMax` (`\x04`). Let's pretend this split happens at `\x03ffff11`. In this case, the left range will store its descriptor at `meta(endKey) = \x02ffff11`. However, the right range will store it's descriptor somewhere in meta2 as normal and at `Meta1KeyMax` (`\x02ffff`) because of the special-case discussed above. I think this could lead to problems with range lookups for the first range, especially if the range lookup does not perform prefetching.

**Comment by bdarnell** [comment]
:lgtm:

Maybe we need to extend the prohibition on splits to the entire span between Meta2KeyMax and MetaMax. 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23863#-:-L7aEFBwHdR5IPNc-ljP:b-3fzzt7)*

**Comment by nvanbenschoten** [comment]
I just confirmed that the issue is real. Running with the following diff...

```
diff --git a/pkg/config/system.go b/pkg/config/system.go
index 8ba62ab841..3eefe607e9 100644
--- a/pkg/config/system.go
+++ b/pkg/config/system.go
@@ -215,6 +215,7 @@ func (s SystemConfig) getZoneConfigForID(id uint32, keySuffix []byte) (ZoneConfi
 }

 var staticSplits = []roachpb.RKey{
+       roachpb.RKey(append(keys.Meta2KeyMax, byte('\x88'))), // TODO nvanbenschoten
        roachpb.RKey(keys.SystemPrefix),                 // end of meta records / start of system ranges
        roachpb.RKey(keys.NodeLivenessPrefix),           // start of node liveness span
        roachpb.RKey(keys.NodeLivenessKeyMax),           // end of node liveness span
```

I see these range descriptors:

```
Nathans-MacBook-Pro:cockroach$ ./cockroach debug range-data cockroach-data/ 1 | grep -E ' /Meta[1,2]'
1521491006.355178268,0 /Meta1/Max: [/Meta2/"\xff\xff\x88", /System/"")
1521491006.349746257,0 /Meta1/"\xff\xff\x88": [/Min, /Meta2/"\xff\xff\x88")
1521491006.355178268,0 /Meta2/System/"": [/Meta2/"\xff\xff\x88", /System/"")
1521491006.367987886,0 /Meta2/System/NodeLiveness: [/System/"", /System/NodeLiveness)
1521491006.373392899,0 /Meta2/System/NodeLivenessMax: [/System/NodeLiveness, /System/NodeLivenessMax)
1521491006.378464929,0 /Meta2/System/tsd: [/System/NodeLivenessMax, /System/tsd)
1521491006.383797577,0 /Meta2/System/"tse": [/System/tsd, /System/"tse")
1521491006.396347962,0 /Meta2/Table/SystemConfigSpan/Start: [/System/"tse", /Table/SystemConfigSpan/Start)
1521491006.401713079,0 /Meta2/Table/11: [/Table/SystemConfigSpan/Start, /Table/11)
1521491006.406085007,0 /Meta2/Table/12: [/Table/11, /Table/12)
1521491006.410558662,0 /Meta2/Table/13: [/Table/12, /Table/13)
1521491006.415451717,0 /Meta2/Table/14: [/Table/13, /Table/14)
1521491006.419727382,0 /Meta2/Table/15: [/Table/14, /Table/15)
1521491006.424227497,0 /Meta2/Table/16: [/Table/15, /Table/16)
1521491006.429633685,0 /Meta2/Table/17: [/Table/16, /Table/17)
1521491006.434442253,0 /Meta2/Table/18: [/Table/17, /Table/18)
1521491006.438910515,0 /Meta2/Table/19: [/Table/18, /Table/19)
1521491006.443386834,0 /Meta2/Table/20: [/Table/19, /Table/20)
1521491006.447750318,0 /Meta2/Table/21: [/Table/20, /Table/21)
1521491006.452136806,0 /Meta2/Table/22: [/Table/21, /Table/22)
1521491006.456909802,0 /Meta2/Table/23: [/Table/22, /Table/23)
1521491006.456909802,0 /Meta2/Max: [/Table/23, /Max)
```

Notice that the first two descriptors are inverted. I agree that we should extend the prohibition on splits to the entire span between Meta2KeyMax and MetaMax. I'll add a second commit to this PR.

**Comment by nvanbenschoten** [comment]
> we need to extend the prohibition on splits to the entire span between Meta2KeyMax and MetaMax

Done.

**Review by bdarnell — APPROVED** [review]

**Comment by nvanbenschoten** [comment]
TFTR!

**Pull request merged**
