### PR TITLE
build: use json output and avoid go-test-teamcity

### LINKED ISSUE #15034: teamcity: Post failures as comments on existing issues when possible for master builds
Currently, teamcity posts repeated failures of the same test under stress to the same issue as comments rather than opening a new issue (thanks to https://github.com/cockroachdb/cockroach/pull/13329). However, it does not do this for failures of normal master builds (as discussed in https://github.com/cockroachdb/cockroach/issues/14184#issuecomment-291240684), so we still sometimes have to manually de-dupe issues. It'd be great if we also got the commenting behavior for our non-stress builds.

@justinj

### PR DESCRIPTION
**Pull request by tbg**
Previously, our tests would produce text output and go-test-teamcity
would be charged with translating from that to TeamCity output.
This was buggy, error-prone and undertested. Parsing messy test output
is hard and there are all kinds of corner cases.

Instead of trying to solve this ourselves, rely on the built-in json
output that the go toolchain provides. This output is far from perfect - I'm
pretty sure it has some bugs as well - but it will become better
over time without any involvement on our end. Additionally, TeamCity
knows how to parse this format already, so go-test-teamcity goes away,
and - hopefully - with each TeamCity upgrade the way the tests are
handled is going to improve.

There is one thing that go-test-teamcity did that we would like to keep,
namely filtering the test output to omit the output for tests that
passed. Our tests are really chatty, and we don't want to pollute our
TeamCity machines with 200mb log files.

So I wrote a little tool that does *just* this filtering (called
testfilter) which we'll invoke instead of go-test-teamcity.

The pipeline looks something like this:

```
make test JSON=true ... \
    testfilter -mode=strip \
    | tee tmp.json
testfilter -mode=omit < tmp.json | testfilter -convert > failures.txt
rm tmp.json
```

where

- `mode=strip` removes the output for non-failing tests (but not the
  start-stop events). TeamCity will thus learn about all tests, but won't
  be burdened with retaining (or even parsing) test output that is
  irrelevant.
- `mode=omit` only keeps failing tests (i.e. will never even mention any
  others). We pipe this to:
- `mode=convert` to get back to human-readable text, in case someone
  would like to download an artifact with only relevant lines in it.

I don't expect anyone to really need the artifact, because TeamCity
lets you copy the "stack trace" (=test output) to clipboard from
the UI, but you never know.

The very nature of how robust our CI pipeline is dictates that I will
have broken something, somewhere. I'll be watching out for fallout when
this merges.
However there are also at least two improvements:

- the "stress pull request" failures are now properly recognized by
  TeamCity; previously one had to sift through the build log.
- teamcity-post-failures.py is no more (actually it still is, but
  it's a noop, just to make sure we don't have to maintain two
  separate TeamCity configs for before/after this change). Issue
  posting is now done via github-post.

Fixes #15034.
Informs #40414.

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
This is now ready for review.

**Review by petermattis — COMMENTED** [review]
> @petermattis you'll have opinions on how to best perform the Makefile change. I'm not keen to add yet another variable here, especially given how special purpose it is, but passing GOFLAGS=json breaks the go env invocations the Makefile contains.

You can filter out the `-json` flag from `go env` invocations. Something like `$(filter-out -json,$(TESTFLAGS))`. I see examples of doing this elsewhere in the `Makefile`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42565#-:-LuYoIlk8djVkut3OSZu:bsblafr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @jordanlewis, and @petermattis)

**Review by tbg — COMMENTED** [review]
@petermattis is what you're suggesting better though? That seems brittle in its own way. I can't say I particularly like either option, so I'd tend to the lower-complexity one (leave as is). For example, if I go with your route I will have no confidence that I haven't broken anything, whereas right now I'm pretty certain.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42565#-:-LuamEpd05WRHPvTm4CA:bpjkmpl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @jordanlewis)

**Review by jordanlewis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42565)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @jordanlewis, and @tbg)

___
*[pkg/cmd/testfilter/main.go, line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42565#-LuhmEsVAlD2UNKm7eeZ:-LuhmEsVAlD2UNKm7ee_:b28l4tz) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a208feb2fecec8c7340c08abbea6cbdfb29442f/pkg/cmd/testfilter/main.go#L11)):*
> ```Go
> // licenses/APL.txt.
> 
> package main
> ```

Wanna write a readme kind of comment up here explaining what this thing is and where it's used? just to help out when people inevitably are confused about what it's for later.
___
*[pkg/cmd/testfilter/main.go, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42565#-LuhmRoe7bW1P-fWkNXI:-LuhmRoe7bW1P-fWkNXJ:b-con5uu) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a208feb2fecec8c7340c08abbea6cbdfb29442f/pkg/cmd/testfilter/main.go#L64)):*
> ```Go
> 	ev := &testEvent{}
> 	var n int // number of JSON lines parsed
> 	for scanner.Scan() {
> ```

Put an example input line around here?

Should we write tests for this? I know go test teamcity has problems but it does have some tests.

**Comment by tbg** [comment]
Well, what an awkward snag. Everything works really well, but the built-in Go test detection drops any test that doesn't have a `Test` prefix, this notably includes the acceptance tests.

I think we can still merge this thanks to `failures.txt` which will have the relevant output, and the artifacts. But I did file an issue upstream:

https://youtrack.jetbrains.com/issue/TW-63449

**Comment by tbg** [comment]
Actually no, should not merge this. The issue posters will likely suffer under this. Ugh. What a silly bummer.

**Comment by jordanlewis** [comment]
Dumb question: Can we rename all the acceptance tests to have Test in their
name?

**Comment by tbg** [comment]
I'd rather not rename tests unless that's the last option. Actually I think we're mostly good here. Not having some of the tests in the UI is annoying, but presumably they'll fix that soon, and `failures.log` is still pretty good.

For the issue posting:
nightly stress: unaffected (uses github-post before and after this change, already took JSON)
nightly roachtest: unaffected (roachtest posts its own issues)
master CI: teamcity-post-failures.py is in charge for all tests being run (incl local roachtests), and doesn't understand JSON

So I really need to get rid of teamcity-post-failures, which I have been wanting for a long time anyway. We should use `pkg/cmd/github-post` instead (which already consumes JSON; it's the thing we use for nightly stress).

**Comment by tbg** [comment]
@jordanlewis I think we're good to go. I removed the python-based issue poster (turned it into a noop), so the only wart is that in local roachtests we don't get teamcity parsing the tests (but failures are still filed, failures.txt artifact is available, etc).

I'd like to merge this soon to get a chance at weeding out the handful of issues that inevitably will pop up on master :-)

**Comment by jordanlewis** [comment]
Awesome!

>  I removed the python-based issue poster 

So do failures on "merge to master" use the same poster that the stress builds do now?

**Comment by tbg** [comment]
Correct, see

https://github.com/cockroachdb/cockroach/pull/42565/files#diff-32b0a9bfe0fb66ea8507d35a43d925bcR65

In particular, `master` failures won't open redundant issues any more. The stress failures and master failures will share one issue. I don't think that's 100% the right solution (if an issue fails on master that's more important than it failing on stress) but not having this python script around enables us to do whatever we want here, if nothing else.

**Comment by tbg** [comment]
PS I very much look forward to closing all of these: https://roachdash.crdb.dev/?filter=status%3Aopen+c%3Atest-failure+r%3Acockroachdb%2Fcockroach+teamcity&sort=-created&restgroup=true&display=category+severity+created

**Review by jordanlewis — APPROVED** [review]
:lgtm_strong: 

> Reviewed 17 of 17 files at r2, 3 of 3 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, 3 of 3 files at r6, 21 of 21 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42565#-:-LvGmokK5Zk_AMYtAYav:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @tbg)

**Comment by tbg** [comment]
bors r=jordanlewis

**Pull request merged**
