### PR TITLE
dev: run `build/bazelutil/check.sh` after `dev generate`

### PR DESCRIPTION
**Pull request by rickystewart**
This runs a couple additional checks. I add a fast path to the script to
make sure this doesn't stall anyone.

Release note: None

### CODE REVIEW

**Review by rail — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83188#-:-N5BTkxQ2kI8yEiM-KcH:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rickystewart)

**Comment by rickystewart** [comment]
bors r=rail

**Comment by rickystewart** [comment]
bors r=rail

**Comment by rickystewart** [comment]
bors r=rail

**Pull request merged**
