### PR TITLE
server: rm gossip usage from node/store/cluster ID allocation

### PR DESCRIPTION
**Pull request by irfansharif**
In 20.2, with #52526, we introduced the join RPC for new nodes in the
system to be handed a pre-allocated node ID, a pre-allocated store ID,
and be informed by the existing cluster what the cluster ID was.
In 20.1 and earlier this functionality was provided by our use of
gossip, and by constructing hollowed out servers (without node/store
IDs) and allocating an ID at the joining node. This required an
awkward dance around needing KV to be up in order to allocate the right
IDs, but not having an ID for the server process itself.

We retained the deprecated gossip codepaths in 20.2 in order to maintain
compatibility with 20.1. Now that 20.2 is cut however, in 21.1 code we
can always assume that we're talking to nodes that are at least 20.2,
and therefore nodes that are able to use the join RPC correctly. This
lets us strip out our usage of gossip for ID allocation, which in turn
paves the way for a few other simplifications.

We also delete the mixed-version/join-init roachtest, as it was only
ever relevant for the 20.1/20.2 cycle. The current structure around
joining nodes being allocated/informed of the right IDs has adequate
coverage with TestClusterConnectivity.

Release note: None

### CODE REVIEW

**Review by irfansharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56263)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @tbg)

___
*[pkg/server/node.go, line 561 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56263#-MLFV5e3Eba1i6r5DbhS:-MLFV5e4DKCjAKeTQFyC:b-7dd5c2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f05cc1f0e2e83c7247c53976a74c3c491f1d552f/pkg/server/node.go#L561)):*
> ```Go
> 		// first store ID has already been pre-allocated for us.
> 		//
> 		// TODO(irfansharif): Is this sound? If we're restarting an already
> ```

Sigh, this is unsound on master, https://github.com/cockroachdb/cockroach/issues/56272. Good thing we didn't officially support multiple stores in 20.2. 

#56272 and these TODOs are unrelated to this PR though, I just noticed given I was in the area. I'll work on cleaning them up separately.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56263)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif, @knz, and @tbg)

___
*[pkg/server/init.go, line 181 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56263#-MLIeaMSCH0SAvMZyRzy:-MLIeaMSCH0SAvMZyRzz:b-u4w440) ([raw file](https://github.com/cockroachdb/cockroach/blob/f05cc1f0e2e83c7247c53976a74c3c491f1d552f/pkg/server/init.go#L181)):*
> ```Go
> // on persisted data instead of this flag.
> //
> // [1]: This is not technically true for mixed version clusters where we leave
> ```

Hmm, isn't this gone now, too?
___
*[pkg/server/init.go, line 375 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56263#-MLIfTlFDhNoMl0sNr1S:-MLIfTlFDhNoMl0sNr1T:b-ilw4mm) ([raw file](https://github.com/cockroachdb/cockroach/blob/f05cc1f0e2e83c7247c53976a74c3c491f1d552f/pkg/server/init.go#L375)):*
> ```Go
> 
> 		if errors.Is(err, ErrIncompatibleBinaryVersion) {
> 			// Propagate upwards; these is an error condition the caller knows
> ```

nit: this is
___
*[pkg/server/node.go, line 389 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56263#-MLIfZbo0I8jpOOTGDK1:-MLIfZbo0I8jpOOTGDK2:bwwj4da) ([raw file](https://github.com/cockroachdb/cockroach/blob/e533f1939c55c34470e1c09958fe9f8205b63805/pkg/server/node.go#L389)):*
> ```Go
> 
> 	// Inform the RPC context of the node ID.
> 	n.storeCfg.RPCContext.NodeID.Set(ctx, nodeID)
> ```

This is done elsewhere already?
___
*[pkg/server/node.go, line 561 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56263#-MLFV5e3Eba1i6r5DbhS:-MLIfeaf5AzKhN7hpaWd:bllchbt) ([raw file](https://github.com/cockroachdb/cockroach/blob/f05cc1f0e2e83c7247c53976a74c3c491f1d552f/pkg/server/node.go#L561)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Sigh, this is unsound on master, https://github.com/cockroachdb/cockroach/issues/56272. Good thing we didn't officially support multiple stores in 20.2. 

#56272 and these TODOs are unrelated to this PR though, I just noticed given I was in the area. I'll work on cleaning them up separately.
</blockquote></details>

I mentioned this in #56272, but I'm looking again and still don't see the problem. `storeIDAlloc` is the number of storeIDs we still need. We pass that to allocateStoreIDs which gets us that many IDs from the KV layer. `startID` is the first ID we got back.

Oh, is the problem that the Join RPC also allocated a NodeID/StoreID for us but that we're not properly persisting it? I just briefly looked at the code and was expecting the `initServer` to actually bootstrap the store with the NodeID/ClusterID/StoreID but now I'm not sure where that happens. Oh, it's in this code via firstStoreID? OK, that is all surprising and now I can see why you're concerned. This does need to be cleaned up. I would generally prefer if the auxiliary and first store were treated separately, just to get the code clean. In particular, it looks like we're bootstrapping the first store asynchronously?!
___
*[pkg/server/server.go, line 1396 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56263#-MLIhNJ5AETHd9ijWFt8:-MLIhNJ5AETHd9ijWFt9:bol4tjz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f05cc1f0e2e83c7247c53976a74c3c491f1d552f/pkg/server/server.go#L1396)):*
> ```Go
> 
> 	s.rpcContext.ClusterID.Set(ctx, state.clusterID)
> 	s.rpcContext.NodeID.Set(ctx, state.nodeID)
> ```

ah, here it is.

**Review by tbg — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56263)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif and @knz)

**Review by irfansharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56263)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif, @knz, and @tbg)

___
*[pkg/server/node.go, line 561 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56263#-MLFV5e3Eba1i6r5DbhS:-MLJ78Sv1CNPHSm7Sdq8:bjjml9n) ([raw file](https://github.com/cockroachdb/cockroach/blob/f05cc1f0e2e83c7247c53976a74c3c491f1d552f/pkg/server/node.go#L561)):*
Like I mentioned in https://github.com/cockroachdb/cockroach/pull/56271#issuecomment-721825081, I think our saving grace here around the number of store IDs we allocated was accidental. 

>  In particular, it looks like we're bootstrapping the first store asynchronously?!

Yup, yikes. Here's what I think the new code structure should be.
```
- In the init code:
  - If we're being bootstrapped:
    - Only initialize first store, leave remaining stores to start up code
      later
  - If we're joining an existing cluster:
    - Only initialize first store, leave remaining stores to start up code
      later

- Later, bootstrapping additional new stores:
  - Allocate len(auxiliary engines) store IDs, and bootstrap them
    asynchronously. 

This should let us avoid threading in the first store ID, and always rely on
the KV increment operation to tell us what the first auxiliary store ID should
be.

Cases to consider:
- [x] Bootstrapping first node with single engine
- [x] Bootstrapping first node with multiple engines
- [x] Joining a bootstrapped cluster, with single engine
- [x] Joining a bootstrapped cluster, with multiple engines
- [x] Restarting a bootstrapped node with no new engines
- [x] Restarting a bootstrapped node with new engines
```

What do you think? Ignoring the gossip code paths here because I want to remove them anyway.

**Review by irfansharif — COMMENTED** [review]
PTAL, rebased atop https://github.com/cockroachdb/cockroach/pull/56299 and https://github.com/cockroachdb/cockroach/pull/56302 (first commit here, to be ignored).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56263#-:-MLQx3U_1yVk9n9PuYuw:bxv9l7y)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @tbg)

___
*[pkg/server/init.go, line 181 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56263#-MLIeaMSCH0SAvMZyRzy:-MLQwpVNColTtBS48rX1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f05cc1f0e2e83c7247c53976a74c3c491f1d552f/pkg/server/init.go#L181)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Hmm, isn't this gone now, too?
</blockquote></details>

Done.
___
*[pkg/server/node.go, line 561 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56263#-MLFV5e3Eba1i6r5DbhS:-MLQwvjw56GlFLyeM_sw:b-7js0qp) ([raw file](https://github.com/cockroachdb/cockroach/blob/f05cc1f0e2e83c7247c53976a74c3c491f1d552f/pkg/server/node.go#L561)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Like I mentioned in https://github.com/cockroachdb/cockroach/pull/56271#issuecomment-721825081, I think our saving grace here around the number of store IDs we allocated was accidental. 

>  In particular, it looks like we're bootstrapping the first store asynchronously?!

Yup, yikes. Here's what I think the new code structure should be.
```
- In the init code:
  - If we're being bootstrapped:
    - Only initialize first store, leave remaining stores to start up code
      later
  - If we're joining an existing cluster:
    - Only initialize first store, leave remaining stores to start up code
      later

- Later, bootstrapping additional new stores:
  - Allocate len(auxiliary engines) store IDs, and bootstrap them
    asynchronously. 

This should let us avoid threading in the first store ID, and always rely on
the KV increment operation to tell us what the first auxiliary store ID should
be.

Cases to consider:
- [x] Bootstrapping first node with single engine
- [x] Bootstrapping first node with multiple engines
- [x] Joining a bootstrapped cluster, with single engine
- [x] Joining a bootstrapped cluster, with multiple engines
- [x] Restarting a bootstrapped node with no new engines
- [x] Restarting a bootstrapped node with new engines
```

What do you think? Ignoring the gossip code paths here because I want to remove them anyway.
</blockquote></details>

Cleaned up across https://github.com/cockroachdb/cockroach/pull/56302 and https://github.com/cockroachdb/cockroach/pull/56299.

**Review by tbg — APPROVED** [review]
so satisfying to see this cleaned up.

> Reviewed 2 of 8 files at r2, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56263#-:-MLRb9nm3cxrpxsJp3_d:b-z5g5tj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif and @knz)

**Comment by irfansharif** [comment]
TFTR!

bors r+

**Comment by irfansharif** [comment]
I'm a bit lost with the CI failures here. Looks like it's timing out for some of our docker acceptance tests? See [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=2423117&buildTypeId=Cockroach_UnitTests_Acceptance&tab=artifacts&branch_Cockroach_UnitTests=staging#%2Facceptance%2FTestDockerC%2FSuccess;%2Facceptance%2FTestDockerCSharp%2FrunMode%3Ddocker;%2Facceptance%2FTestDockerNodeJS%2FrunMode%3Ddocker). But I tried running them on my gceworker:

```
$ make acceptance TESTS=TestDockerRuby PKG=./pkg/acceptance TESTFLAGS='-v -show-logs'        
...
--- PASS: TestDockerRuby (10.07s)
    --- PASS: TestDockerRuby/runMode=docker (5.46s)
    --- PASS: TestDockerRuby/runMode=docker#01 (4.61s)
PASS
```

And they work? I'm a bit lost. @knz, @tbg: any ideas what I'm missing? I took a cursory glance at our acceptance testing harness setup, and nothing stands out to me. And the logs aren't super helpful. I've kicked off another run, but I'm pretty sure it'll fail as well (it has before).

**Comment by irfansharif** [comment]
🤷‍♀️

**Comment by knz** [comment]
very nice piece of work :100:  :tada:

**Pull request merged**
