### PR TITLE
clusterversion,storage: remove EnablePebbleFormatVersionBlockProperties

### PR DESCRIPTION
**Pull request by celiala**
Release justification: remove old version gate
Release note: None

Partially addresses https://github.com/cockroachdb/cockroach/issues/80663

### CODE REVIEW

**Comment by celiala** [comment]
I'm not sure how to fix these failing tests -- hopefully someone on Storage can help here?

These tests are failing:

- pkg/upgrade/upgrademanager: TestPrecondition
- pkg/ccl/jobsccl/jobsprotectedtsccl: TestJobsProtectedTimestamp/system-tenant

TestJobsProtectedTimestamp/system-tenant gives:
```
/go/src/github.com/cockroachdb/cockroach/pkg/ccl/jobsccl/jobsprotectedtsccl/jobs_protected_ts_test.go:176
          Error:        Received unexpected error:
                        protected timestamp record does not exist
```

**Comment by nicktrav** [comment]
@bananabrick - mind taking a look at this?

**Comment by bananabrick** [comment]
Removed in this https://github.com/cockroachdb/cockroach/pull/86337

**Comment by celiala** [comment]
Closing in favor of https://github.com/cockroachdb/cockroach/pull/86337

**Pull request closed without merging**
