### PR TITLE
catalog/lease: fix TestLeaseDescriptorRangeFeedFailure test

### LINKED ISSUE #128061: sql/catalog/lease: TestLeaseDescriptorRangeFeedFailure failed
sql/catalog/lease.TestLeaseDescriptorRangeFeedFailure [failed](https://mesolite.cluster.engflow.com/invocations/default/c79dc57f-ab45-42a9-b714-31a24f54bd66?testReportRun=1&testReportShard=4&testReportAttempt=1#targets-Ly9wa2cvc3FsL2NhdGFsb2cvbGVhc2U6bGVhc2VfdGVzdA==) on master @ [2feafe61260c2c3b6d215e938ebafea65909fd67](https://github.com/cockroachdb/cockroach/commits/2feafe61260c2c3b6d215e938ebafea65909fd67):

Fatal error:

```
panic: test timed out after 14m57s
running tests:
	TestLeaseDescriptorRangeFeedFailure (14m40s)

```
Stack: 

```
goroutine 256855 [running]:
testing.(*M).startAlarm.func1()
	GOROOT/src/testing/testing.go:2366 +0x385
created by time.goFunc
	GOROOT/src/time/sleep.go:177 +0x2d
```
<details><summary>Log preceding fatal error</summary>
<p>

```
=== RUN   TestLeaseDescriptorRangeFeedFailure
    test_log_scope.go:170: test logs captured to: outputs.zip/logTestLeaseDescriptorRangeFeedFailure2230519371
    test_log_scope.go:81: use -show-logs to present logs inline
    test_server_shim.go:157: automatically injected a shared process virtual cluster under test; see comment at top of test_server_shim.go for details.
```
</p>
</details>

Parameters:
 - <code>attempt=1</code>
 - <code>run=1</code>
 - <code>shard=4</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestLeaseDescriptorRangeFeedFailure.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-40776

### PR DESCRIPTION
**Pull request by fqazi**
Previously, the TestLeaseDescriptorRangeFeedFailure test did not properly allow the range feed to recover after a simulated range feed failure. This meant the test did not validate whether a refresh would occur after recovery and was succeeding because range feed updates were being noticed. To address this, this patch fixes the TestLeaseDescriptorRangeFeedFailure test to properly simulate recovery happening after a restart.

Fixes: #128061

Release note: None

### CODE REVIEW

**Review by spilchen — COMMENTED** [review]
Good change. I just had a few questions.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128434#-:-O3n65jr86Bw05IBP1sk:b-1jflly)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/catalog/lease/lease.go` line 2067 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128434#-O3n5IBY7PkiTMegxQrg:-O3n5IBY7PkiTMegxQrh:b3ukwiw) ([raw file](https://github.com/cockroachdb/cockroach/blob/15da2f374fb73d49fb309212a96c5c97d2a4c9bb/pkg/sql/catalog/lease/lease.go#L2067)):*
> ```Go
> 	m.mu.rangeFeedCheckpoints = 0
> 	m.testingKnobs.DisableRangeFeedCheckpoint = disable
> 	m.testingKnobs.RangeFeedResetChannel = make(chan struct{})
> ```

Do we want to create the channel only if `disable == true`? Otherwise, I think we'll create a new channel when we call this to disable this knob. 
___
*[`pkg/sql/catalog/lease/lease_test.go` line 3715 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128434#-O3n5mS15hImRXpAvbL6:-O3n5mS15hImRXpAvbL7:b-yj9a9a) ([raw file](https://github.com/cockroachdb/cockroach/blob/15da2f374fb73d49fb309212a96c5c97d2a4c9bb/pkg/sql/catalog/lease/lease_test.go#L3715)):*
> ```Go
> 	enableAfterStageKnob.Store(true)
> 	firstConn.Exec(t, "ALTER TABLE t1 ADD COLUMN j INT DEFAULT 64")
> 	enableAfterStageKnob.Store(false)
> ```

nit: do we need to set this to false? It looks like the AfterStage callback will set it to false too.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128434)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @spilchen)

___
*[`pkg/sql/catalog/lease/lease.go` line 2067 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128434#-O3n5IBY7PkiTMegxQrg:-O3rKSUvCb9CyxGcFVTS:b-rwk1iq) ([raw file](https://github.com/cockroachdb/cockroach/blob/15da2f374fb73d49fb309212a96c5c97d2a4c9bb/pkg/sql/catalog/lease/lease.go#L2067)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Do we want to create the channel only if `disable == true`? Otherwise, I think we'll create a new channel when we call this to disable this knob.
</blockquote></details>

Done

Yeah, fair point, we only want this setup when reset can occur.
___
*[`pkg/sql/catalog/lease/lease_test.go` line 3715 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/128434#-O3n5mS15hImRXpAvbL6:-O3rKcXj-pgiSR_ybpI-:b-1tei6p) ([raw file](https://github.com/cockroachdb/cockroach/blob/15da2f374fb73d49fb309212a96c5c97d2a4c9bb/pkg/sql/catalog/lease/lease_test.go#L3715)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

nit: do we need to set this to false? It looks like the AfterStage callback will set it to false too.
</blockquote></details>

Done

True this was redundant.

**Review by spilchen — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128434#-:-O3ruuKM0K4icqgLTiHS:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @fqazi)

**Comment by fqazi** [comment]
@spilchen TFTR!

bors r+

**Comment by rafiss** [comment]
blathers backport 24.1.4-rc

**Pull request merged**
