### PR TITLE
sql: support READ COMMITTED in transaction_isolation session vars

### LINKED ISSUE #100140: sql: support {default}_transaction_isolation session variables
The `transaction_isolation` and `default_transaction_isolation` session variables are currently ignored. These should be supported and hooked up.

https://github.com/cockroachdb/cockroach/pull/32860 may provide some guidance here.

NB: make sure to exclude this session variable from being inherited by the internal executor. The RFC has additional comments about this.

Jira issue: CRDB-26580

Epic CRDB-26545

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/100140

Release note (sql change): The READ COMMITTED isolation level is now
supported. It can be used in the following ways:
- when starting a transaction, use BEGIN ISOLATION LEVEL READ COMMITTED.
- after starting a transaction, but before performing reads or writes,
  use SET TRANSACTION ISOLATION READ COMMITTED.
- configure it as the default isolation level using the
  default_transaction_isolation session variable.

To see the isolation level of the currently running transaction, use
either:
- SHOW TRANSACTION ISOLATION LEVEL
- SHOW transaction_isolation

### CODE REVIEW

**Review by michae2 — COMMENTED** [review]
Nice!

> Reviewed 5 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103482#-:-NVbCsVc8LWy8Cu97QDu:b-83sjoh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @rafiss)

___
*[`pkg/sql/logictest/testdata/logic_test/txn` line 310 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103482#-NVbCZNt-uer12ZQpJLV:-NVbCZNu1SgckIK-DajL:b40p98y) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9cdecfb5d2400a1cfb25607c6a6dcd1b55dbdbf/pkg/sql/logictest/testdata/logic_test/txn#L310)):*
> ```
> # The isolation level of a transaction can be changed with the session variable too.
> statement ok
> SET transaction_isolation = 'READ COMMITTED'
> ```

Do we have any logictest cases that `SET default_transaction_isolation`?

**Review by nvb — COMMENTED** [review]
> Reviewed 13 of 13 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103482)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/conn_fsm.go` line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103482#-NVbKb9W6T2CR1p9dXiS:-NVbKb9W6T2CR1p9dXiT:bcj2jc0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9cdecfb5d2400a1cfb25607c6a6dcd1b55dbdbf/pkg/sql/conn_fsm.go#L42)):*
> ```Go
> )
> 
> // / States.
> ```

nit: the new version of gofmt must not like these triple forward slashes. Mind replacing them with double forward slashes?
___
*[`pkg/sql/internal.go` line 786 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103482#-NVbLHpdD8Gj-gkZFe0p:-NVbLHpdD8Gj-gkZFe0q:bcc1kt9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9cdecfb5d2400a1cfb25607c6a6dcd1b55dbdbf/pkg/sql/internal.go#L786)):*
> ```Go
> 	// might be using the RootTxn).
> 	sd.LocalOnlySessionData.StreamerEnabled = false
> 	// The internal executor only is allowed to use SERIALIZABLE transactions.
> ```

Is this enough to ensure that all transactions run by the conn executor use serializable isolation instead of a user-configurable default? I'm not sure if you saw, but Raphael had a collection of comments on the [RC RFC](https://github.com/cockroachdb/cockroach/pull/100608) about this topic.
___
*[`pkg/sql/vars.go` line 426 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103482#-NVbLrn55EGU_8I-LZDY:-NVbLrn55EGU_8I-LZDZ:b3jewty) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9cdecfb5d2400a1cfb25607c6a6dcd1b55dbdbf/pkg/sql/vars.go#L426)):*
> ```Go
> 		},
> 		GlobalDefault: func(sv *settings.Values) string {
> 			return strings.ToLower(tree.SerializableIsolation.String())
> ```

There are a few calls to `strings.ToLower` in here. Would it be useful or important (performance-wise) to define a `StringLower()` method on `tree.IsolationLevel`?
___
*[`pkg/sql/sessiondatapb/local_only_session_data.proto` line 404 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103482#-NVbMYe96kkHHFnLJ8vx:-NVbMYe96kkHHFnLJ8vy:b-c5vcmr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9cdecfb5d2400a1cfb25607c6a6dcd1b55dbdbf/pkg/sql/sessiondatapb/local_only_session_data.proto#L404)):*
> ```protobuf
>   // NOTE: we'd prefer to use tree.IsolationLevel here, but doing so would
>   // introduce a package dependency cycle.
>   int64 default_txn_isolation_level = 105;
> ```

I might be wrong, but I think this serialized session state can now cross process boundaries. If so, do we need to now be careful about the integer values of each isolation level in the `tree.IsolationLevel` enum? Does that deserve a comment on that enum?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103482)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @nvanbenschoten)

___
*[`pkg/sql/conn_fsm.go` line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103482#-NVbKb9W6T2CR1p9dXiS:-NVfi5JQ-Psn6lQBf1cD:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9cdecfb5d2400a1cfb25607c6a6dcd1b55dbdbf/pkg/sql/conn_fsm.go#L42)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: the new version of gofmt must not like these triple forward slashes. Mind replacing them with double forward slashes?
</blockquote></details>

done
___
*[`pkg/sql/internal.go` line 786 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103482#-NVbLHpdD8Gj-gkZFe0p:-NVfjnWqDjcxK8obn3Q3:b-29yydb) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9cdecfb5d2400a1cfb25607c6a6dcd1b55dbdbf/pkg/sql/internal.go#L786)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this enough to ensure that all transactions run by the conn executor use serializable isolation instead of a user-configurable default? I'm not sure if you saw, but Raphael had a collection of comments on the [RC RFC](https://github.com/cockroachdb/cockroach/pull/100608) about this topic.
</blockquote></details>

hm yeah the comment i left is actually a bit too broad. but i think this should be safe still. i'll adjust the comment

this change makes it so that any new transaction created when using the IE will run in SERIALIZABLE. this includes things like background jobs where CRDB is the one creating the transaction.

but if the IE is used in the context of a user-created transaction, it would use READ COMMITTED (for example, if the IE is used to implement a builtin function). but in that case, it seems correct and safe for the IE to use RC also.
___
*[`pkg/sql/vars.go` line 426 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103482#-NVbLrn55EGU_8I-LZDY:-NVfiGHVEDF9c6tulkQC:b-e043kv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9cdecfb5d2400a1cfb25607c6a6dcd1b55dbdbf/pkg/sql/vars.go#L426)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

There are a few calls to `strings.ToLower` in here. Would it be useful or important (performance-wise) to define a `StringLower()` method on `tree.IsolationLevel`?
</blockquote></details>

i don't think it matters too much, since this is only used in SET and SHOW statements, which are usually not performance sensitive
___
*[`pkg/sql/sessiondatapb/local_only_session_data.proto` line 404 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103482#-NVbMYe96kkHHFnLJ8vx:-NVfiQ3S3YgFtBcjLxS4:bak1aqm) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9cdecfb5d2400a1cfb25607c6a6dcd1b55dbdbf/pkg/sql/sessiondatapb/local_only_session_data.proto#L404)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I might be wrong, but I think this serialized session state can now cross process boundaries. If so, do we need to now be careful about the integer values of each isolation level in the `tree.IsolationLevel` enum? Does that deserve a comment on that enum?
</blockquote></details>

we should be good with this one since this is in the LocalOnlySessionData, which cannot cross process boundaries. (see the comment on the struct, and the one below)
___
*[`pkg/sql/logictest/testdata/logic_test/txn` line 310 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103482#-NVbCZNt-uer12ZQpJLV:-NVfifxHCXi8Lu2EzdCx:bhb19mk) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9cdecfb5d2400a1cfb25607c6a6dcd1b55dbdbf/pkg/sql/logictest/testdata/logic_test/txn#L310)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Do we have any logictest cases that `SET default_transaction_isolation`?
</blockquote></details>

yeah there's one on line 650 for SNAPSHOT, but i've added one for read committed

**Review by nvb — APPROVED** [review]
> Reviewed 5 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103482)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @rafiss)

___
*[`pkg/sql/sessiondatapb/local_only_session_data.proto` line 404 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103482#-NVbMYe96kkHHFnLJ8vx:-NVjezMj5x4ZNpcxSIEA:b-ww9ead) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9cdecfb5d2400a1cfb25607c6a6dcd1b55dbdbf/pkg/sql/sessiondatapb/local_only_session_data.proto#L404)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

we should be good with this one since this is in the LocalOnlySessionData, which cannot cross process boundaries. (see the comment on the struct, and the one below)
</blockquote></details>

Ack. Thanks for explaining.

**Comment by rafiss** [comment]
tftr!

bors r=nvanbenschoten

**Review by michae2 — APPROVED** [review]
:lgtm: Nice, just one question.

> Reviewed 4 of 13 files at r1, 3 of 5 files at r3, 3 of 3 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103482#-:-NVjyw5p3wZTUf_Ag8u3:b-tub7uu)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/vars.go` line 1486 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/103482#-NVjwkcF4FKUmhrx4Y_2:-NVjwkcF4FKUmhrx4Y_3:b-agkmbw) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6ef5e4af0f61b9d19b1709d770bb504334e1a1a/pkg/sql/vars.go#L1486)):*
> ```Go
> 			level := kvTxnIsolationLevelToTree(evalCtx.Txn.IsoLevel())
> 			if level == tree.UnspecifiedIsolation {
> 				level = tree.SerializableIsolation
> ```

Should this be getting `DefaultTxnIsolationLevel` from the session data? (Or should there be a `GetFromSessionData` that does this?)
___
*[`pkg/sql/logictest/testdata/logic_test/txn` line 310 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103482#-NVbCZNt-uer12ZQpJLV:-NVjmb0H-_U0oQ-Reei7:b-9755fn) ([raw file](https://github.com/cockroachdb/cockroach/blob/a9cdecfb5d2400a1cfb25607c6a6dcd1b55dbdbf/pkg/sql/logictest/testdata/logic_test/txn#L310)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

yeah there's one on line 650 for SNAPSHOT, but i've added one for read committed
</blockquote></details>

Thank you!

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103482)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2)

___
*[`pkg/sql/vars.go` line 1486 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/103482#-NVjwkcF4FKUmhrx4Y_2:-NVk-ElEAp_xTTRSyxfk:b-6oqa9g) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6ef5e4af0f61b9d19b1709d770bb504334e1a1a/pkg/sql/vars.go#L1486)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Should this be getting `DefaultTxnIsolationLevel` from the session data? (Or should there be a `GetFromSessionData` that does this?)
</blockquote></details>

hm yes, that would be more logically correct. but in practice we're fine, since `kvTxnIsolationLevelToTree` cannot return `UnspecifiedIsolation` (i just realized this).

i'll clean this up as another commit in my next PR: https://github.com/cockroachdb/cockroach/pull/103488

**Comment by kibertoad** [comment]
@rafiss Is it recommended to use READ COMMITTED as a default when a stricter isolation level is not needed? Is it generally more performant?

**Comment by rafiss** [comment]
@kibertoad READ COMMITTED will still be a preview feature in the 23.2 release, so we don't recommend using it in production before testing it with your application. It needs to be enabled with the `sql.txn.read_committed_isolation.enabled` cluster setting before it can be used.

**Pull request merged**
