### PR TITLE
pkg: refactor storage.Reader using iterutil

### PR DESCRIPTION
**Pull request by vrongmeal**
Release note: None

Signed-off-by: Vaibhav <vrongmeal@gmail.com>

### CODE REVIEW

**Comment by vrongmeal** [comment]
@tbg I updated the `storage.Reader` interface according to the iterutil package as well

**Comment by tbg** [comment]
@vrongmeal thanks! It seems like there are some compilation errors, mind fixing them before I take a look? `make test TESTS=-` will try to compile anything and can help you weed out the problems.

**Comment by vrongmeal** [comment]
So sorry, I must have made some mistake while rebasing. I'll fix it.

**Review by tbg — APPROVED** [review]
:lgtm:

> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55315#-:-MJWmcIFCYHZeOlFnVvl:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by tbg — APPROVED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55315#-:-MJWmfry0hUUl2Oew-wl:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
