### PR TITLE
sql: fix TestRandomSyntaxFunctions related bugs/flakes

### LINKED ISSUE #107410: sql/tests: TestRandomSyntaxFunctions failed
sql/tests.TestRandomSyntaxFunctions [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RandomSyntaxTestsBazel/11016953?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RandomSyntaxTestsBazel/11016953?buildTab=artifacts#/) on release-23.1 @ [81e44ab558b20b0ff55020ff05621c0ef43b4241](https://github.com/cockroachdb/cockroach/commits/81e44ab558b20b0ff55020ff05621c0ef43b4241):

Fatal error:

```
panic: test timed out after 14m55s

```
Stack: 

```
goroutine 6189047 [running]:
testing.(*M).startAlarm.func1()
	GOROOT/src/testing/testing.go:2036 +0x8e
created by time.goFunc
	GOROOT/src/time/sleep.go:176 +0x32
```
<details><summary>Log preceding fatal error</summary>
<p>

```
    rsg_test.go:832: 45s of 5m0s: 111769 executions, 69628 successful
    rsg_test.go:832: 50s of 5m0s: 126128 executions, 78493 successful
    rsg_test.go:832: 55s of 5m0s: 136660 executions, 85111 successful
    rsg_test.go:832: 1m0s of 5m0s: 146932 executions, 91449 successful
    rsg_test.go:832: 1m5s of 5m0s: 158238 executions, 98490 successful
    rsg_test.go:832: 1m10s of 5m0s: 169771 executions, 105723 successful
    rsg_test.go:832: 1m15s of 5m0s: 184349 executions, 114905 successful
    rsg_test.go:832: 1m20s of 5m0s: 196226 executions, 122244 successful
    rsg_test.go:832: 1m25s of 5m0s: 208803 executions, 130093 successful
    rsg_test.go:832: 1m30s of 5m0s: 219805 executions, 136928 successful
    rsg_test.go:832: 1m35s of 5m0s: 232301 executions, 144781 successful
    rsg_test.go:832: 1m40s of 5m0s: 246840 executions, 153857 successful
    rsg_test.go:832: 1m45s of 5m0s: 258639 executions, 161173 successful
    rsg_test.go:832: 1m50s of 5m0s: 273102 executions, 170201 successful
    rsg_test.go:832: 1m55s of 5m0s: 285366 executions, 177840 successful
    rsg_test.go:832: 2m0s of 5m0s: 299115 executions, 186412 successful
    rsg_test.go:832: 2m5s of 5m0s: 310437 executions, 193443 successful
    rsg_test.go:832: 2m10s of 5m0s: 320473 executions, 199737 successful
    rsg_test.go:832: 2m15s of 5m0s: 329338 executions, 205142 successful
    rsg_test.go:832: 2m20s of 5m0s: 340128 executions, 211817 successful
    rsg_test.go:832: 2m25s of 5m0s: 351299 executions, 218891 successful
    rsg_test.go:832: 2m30s of 5m0s: 362323 executions, 225783 successful
    rsg_test.go:832: 2m35s of 5m0s: 374113 executions, 233161 successful
    rsg_test.go:832: 2m40s of 5m0s: 383512 executions, 238958 successful
    rsg_test.go:832: 2m45s of 5m0s: 393391 executions, 245099 successful
    rsg_test.go:832: 2m50s of 5m0s: 407068 executions, 253572 successful
    rsg_test.go:832: 2m55s of 5m0s: 419710 executions, 261462 successful
    rsg_test.go:832: 3m0s of 5m0s: 431197 executions, 268584 successful
    rsg_test.go:832: 3m5s of 5m0s: 443273 executions, 276076 successful
    rsg_test.go:832: 3m10s of 5m0s: 454205 executions, 282864 successful
    rsg_test.go:832: 3m15s of 5m0s: 464119 executions, 289098 successful
    rsg_test.go:832: 3m20s of 5m0s: 476688 executions, 296854 successful
    rsg_test.go:832: 3m25s of 5m0s: 491639 executions, 306141 successful
    rsg_test.go:832: 3m30s of 5m0s: 507502 executions, 316034 successful
    rsg_test.go:832: 3m35s of 5m0s: 519648 executions, 323647 successful
    rsg_test.go:832: 3m40s of 5m0s: 531334 executions, 330904 successful
    rsg_test.go:832: 3m45s of 5m0s: 546063 executions, 340041 successful
    rsg_test.go:832: 3m50s of 5m0s: 558206 executions, 347665 successful
    rsg_test.go:832: 3m55s of 5m0s: 573092 executions, 357014 successful
    rsg_test.go:832: 4m0s of 5m0s: 586121 executions, 365038 successful
    rsg_test.go:832: 4m5s of 5m0s: 600341 executions, 373917 successful
    rsg_test.go:832: 4m10s of 5m0s: 613452 executions, 382073 successful
    rsg_test.go:832: 4m15s of 5m0s: 624998 executions, 389270 successful
    rsg_test.go:832: 4m20s of 5m0s: 635983 executions, 396013 successful
    rsg_test.go:832: 4m25s of 5m0s: 650663 executions, 405039 successful
    rsg_test.go:832: 4m30s of 5m0s: 660539 executions, 411215 successful
    rsg_test.go:832: 4m35s of 5m0s: 674715 executions, 420176 successful
    rsg_test.go:832: 4m40s of 5m0s: 687160 executions, 427858 successful
    rsg_test.go:832: 4m45s of 5m0s: 701386 executions, 436757 successful
    rsg_test.go:832: 4m50s of 5m0s: 713152 executions, 444114 successful
```
</p>
</details>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #95619 sql/tests: TestRandomSyntaxFunctions failed [C-test-failure O-robot T-sql-foundations branch-release-22.2]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRandomSyntaxFunctions.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-30027

### LINKED ISSUE #107411: sql/tests: TestRandomSyntaxFunctions failed
sql/tests.TestRandomSyntaxFunctions [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RandomSyntaxTestsBazel/11016929?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RandomSyntaxTestsBazel/11016929?buildTab=artifacts#/) on master @ [8d10f15db8e5efaff57ec332c438211895c6c608](https://github.com/cockroachdb/cockroach/commits/8d10f15db8e5efaff57ec332c438211895c6c608):

Fatal error:

```
panic: test timed out after 14m55s

```
Stack: 

```
goroutine 4961895 [running]:
testing.(*M).startAlarm.func1()
	GOROOT/src/testing/testing.go:2036 +0x8e
created by time.goFunc
	GOROOT/src/time/sleep.go:176 +0x32
```
<details><summary>Log preceding fatal error</summary>
<p>

```
    rsg_test.go:828: 45s of 5m0s: 82274 executions, 51184 successful
    rsg_test.go:828: 50s of 5m0s: 88125 executions, 54824 successful
    rsg_test.go:828: 55s of 5m0s: 97750 executions, 60749 successful
    rsg_test.go:828: 1m0s of 5m0s: 107137 executions, 66533 successful
    rsg_test.go:828: 1m5s of 5m0s: 116722 executions, 72462 successful
    rsg_test.go:828: 1m10s of 5m0s: 129451 executions, 80394 successful
    rsg_test.go:828: 1m15s of 5m0s: 139732 executions, 86723 successful
    rsg_test.go:828: 1m20s of 5m0s: 149432 executions, 92756 successful
    rsg_test.go:828: 1m25s of 5m0s: 160058 executions, 99331 successful
    rsg_test.go:828: 1m30s of 5m0s: 169856 executions, 105405 successful
    rsg_test.go:828: 1m35s of 5m0s: 180660 executions, 112071 successful
    rsg_test.go:828: 1m40s of 5m0s: 189252 executions, 117378 successful
    rsg_test.go:828: 1m45s of 5m0s: 198582 executions, 123164 successful
    rsg_test.go:828: 1m50s of 5m0s: 208377 executions, 129210 successful
    rsg_test.go:828: 1m55s of 5m0s: 218959 executions, 135799 successful
    rsg_test.go:828: 2m0s of 5m0s: 230505 executions, 142947 successful
    rsg_test.go:828: 2m5s of 5m0s: 236977 executions, 146975 successful
    rsg_test.go:828: 2m10s of 5m0s: 247131 executions, 153229 successful
    rsg_test.go:828: 2m15s of 5m0s: 252900 executions, 156794 successful
    rsg_test.go:828: 2m20s of 5m0s: 259141 executions, 160665 successful
    rsg_test.go:828: 2m25s of 5m0s: 268083 executions, 166219 successful
    rsg_test.go:828: 2m30s of 5m0s: 277476 executions, 172051 successful
    rsg_test.go:828: 2m35s of 5m0s: 287595 executions, 178341 successful
    rsg_test.go:828: 2m40s of 5m0s: 295109 executions, 183048 successful
    rsg_test.go:828: 2m45s of 5m0s: 305193 executions, 189319 successful
    rsg_test.go:828: 2m50s of 5m0s: 317357 executions, 196761 successful
    rsg_test.go:828: 2m55s of 5m0s: 326636 executions, 202538 successful
    rsg_test.go:828: 3m0s of 5m0s: 334241 executions, 207276 successful
    rsg_test.go:828: 3m5s of 5m0s: 344168 executions, 213409 successful
    rsg_test.go:828: 3m10s of 5m0s: 352836 executions, 218683 successful
    rsg_test.go:828: 3m15s of 5m0s: 361117 executions, 223782 successful
    rsg_test.go:828: 3m20s of 5m0s: 371773 executions, 230346 successful
    rsg_test.go:828: 3m26s of 5m0s: 386249 executions, 239334 successful
    rsg_test.go:828: 3m31s of 5m0s: 402828 executions, 249647 successful
    rsg_test.go:828: 3m36s of 5m0s: 417015 executions, 258327 successful
    rsg_test.go:828: 3m41s of 5m0s: 426158 executions, 264082 successful
    rsg_test.go:828: 3m46s of 5m0s: 434945 executions, 269510 successful
    rsg_test.go:828: 3m51s of 5m0s: 444752 executions, 275597 successful
    rsg_test.go:828: 3m56s of 5m0s: 456440 executions, 282868 successful
    rsg_test.go:828: 4m1s of 5m0s: 463082 executions, 287044 successful
    rsg_test.go:828: 4m6s of 5m0s: 467254 executions, 289636 successful
    rsg_test.go:828: 4m11s of 5m0s: 478535 executions, 296574 successful
    rsg_test.go:828: 4m16s of 5m0s: 489459 executions, 303314 successful
    rsg_test.go:828: 4m21s of 5m0s: 499647 executions, 309649 successful
    rsg_test.go:828: 4m26s of 5m0s: 510365 executions, 316290 successful
    rsg_test.go:828: 4m31s of 5m0s: 522185 executions, 323631 successful
    rsg_test.go:828: 4m36s of 5m0s: 530174 executions, 328624 successful
    rsg_test.go:828: 4m41s of 5m0s: 539890 executions, 334663 successful
    rsg_test.go:828: 4m46s of 5m0s: 550924 executions, 341619 successful
    rsg_test.go:828: 4m51s of 5m0s: 561431 executions, 348048 successful
```
</p>
</details>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #107410 sql/tests: TestRandomSyntaxFunctions failed [C-test-failure O-robot T-sql-foundations branch-release-23.1]
- #95619 sql/tests: TestRandomSyntaxFunctions failed [C-test-failure O-robot T-sql-foundations branch-release-22.2]
</p>
</details>
/cc @cockroachdb/sql-foundations
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRandomSyntaxFunctions.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-30028

### PR DESCRIPTION
**Pull request by fqazi**
Previously TestRandomSyntaxFunctions could flake due to the following bugs:
1. crdb_internal.revalidate_unique_constraints_in_all_tables did not handle cancelled contexts properly which could lead to timeouts
2. crdb_internal.pretty_value could fail on random values could panic decoding, so a recover should be used inside this builtin.
3. TestRandomSyntaxFunctions was testing crdb_internal.gen_rand_ident, which can take a long time based on the input parameters (specifically when a large number of identifiers is requested)

Fixes: #107410
Fixes: #107411

### CODE REVIEW

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107491)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/sem/builtins/builtins.go` line 5768 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107491#-Na8PQJiCiDNfSNGuKUr:-Na8PQJiCiDNfSNGuKUs:b-boyzat) ([raw file](https://github.com/cockroachdb/cockroach/blob/d42c484f6505bff455f961e1c42cedbfaec05327/pkg/sql/sem/builtins/builtins.go#L5768)):*
> ```Go
> 			Fn: func(_ context.Context, _ *eval.Context, args tree.Datums) (d tree.Datum, err error) {
> 				defer func() {
> 					if r := recover(); r != nil {
> ```

i'm curious about this one - i think it's unexpected that the `PrettyPrint` function would ever panic. how does that happen?

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107491)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/sem/builtins/builtins.go` line 5768 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107491#-Na8PQJiCiDNfSNGuKUr:-Na8Q2Y0C6uz9oGoIRfN:b7tvao8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d42c484f6505bff455f961e1c42cedbfaec05327/pkg/sql/sem/builtins/builtins.go#L5768)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i'm curious about this one - i think it's unexpected that the `PrettyPrint` function would ever panic. how does that happen?
</blockquote></details>

@rafiss DecodeUntaggedUUIDValue and DecodeUntaggedIPAddrValue do not validate the input, so that they will hit out-of-bounds errors. The other approach is to update those code paths to generate errors. Not sure if there are performance considerations for those code paths

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107491)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/check.go` line 439 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107491#-Na8cJjVE0alwGSUQ1aG:-Na8cJjVE0alwGSUQ1aH:b-8ibhgo) ([raw file](https://github.com/cockroachdb/cockroach/blob/85ffacfffafc860d90480b6395ecdcf6e0ba64ea/pkg/sql/check.go#L439)):*
> ```Go
> 		// If the context is cancelled, then we should bail out, since
> 		// the actual revalidate operation might not check anything.
> 		if err := ctx.Err(); err != nil {
> ```

i think sql-queries added this builtin so let's get them to sign off
___
*[`pkg/sql/sem/builtins/builtins.go` line 5768 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107491#-Na8PQJiCiDNfSNGuKUr:-Na8cOJi6GWzO6gv-QmF:b-fimn65) ([raw file](https://github.com/cockroachdb/cockroach/blob/d42c484f6505bff455f961e1c42cedbfaec05327/pkg/sql/sem/builtins/builtins.go#L5768)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

@rafiss DecodeUntaggedUUIDValue and DecodeUntaggedIPAddrValue do not validate the input, so that they will hit out-of-bounds errors. The other approach is to update those code paths to generate errors. Not sure if there are performance considerations for those code paths
</blockquote></details>

ah i see. i think we should actually do the `recover` inside of the `PrettyPrint` function, that way the error reporting is consistent with other kinds of errors that can happen in that function.

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107491)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/sem/builtins/builtins.go` line 5768 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107491#-Na8PQJiCiDNfSNGuKUr:-NaDabvNAC0nXiYByvFJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d42c484f6505bff455f961e1c42cedbfaec05327/pkg/sql/sem/builtins/builtins.go#L5768)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

ah i see. i think we should actually do the `recover` inside of the `PrettyPrint` function, that way the error reporting is consistent with other kinds of errors that can happen in that function.
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107491)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by fqazi** [comment]
blathers backport 23.1

**Pull request merged**
