### PR TITLE
storage: reduce Raft per-op overhead

### PR DESCRIPTION
**Pull request by petermattis**
For simple Raft commands, this reduces size of Raft proposals by 45%
which directly reduces the majority of Raft network overhead by 45%. The
proposals are also written to the Raft log and results in a 34%
reduction in Raft log overhead.

These changes are backward compatible because they involve not encoding
zero-valued fields.

See #18659

### CODE REVIEW

**Comment by petermattis** [comment]
I still need to double-check the network and disk bandwidth savings on a real cluster.

**Comment by petermattis** [comment]
Running a write-only workload (`kv --read-percent 0`) shows a modest reduction in network bandwidth:

screen shot 2017-09-22 at 9 15 39 am

The period on the left is for current master and the period on the right is with this PR. Note that I specified `--max-rate 10000` so we're comparing apples-to-apples numbers of operations.

This is smaller than the number calculated above. Probably because I wasn't accounting for other per-op overhead or figuring in the pgwire traffic. 

screen shot 2017-09-22 at 9 16 22 am

Disk bandwidth seems only very slightly lower. Even more surprising is that there is a 15% drop in throughput when the max-rate is not capped. I have no explanation for that. Is there more memory pressure somehow? Are the additional pointers affecting GC?

**Comment by petermattis** [comment]
Figured out the cause of the throughput drop. It was due to allocating `ReplicaState` in `ReplicatedEvalResult` if that field was nil when applying a Raft command in order to pass through `{Raft,Lease}AppliedIndex`. Somewhat surprising that one allocation could cause such a drop and yet it did. I checked and double-check this by removing and adding that allocation.

**Comment by petermattis** [comment]
Added a few more commits which shave down the proposal overhead. Happy to break some of these out into separate PRs.

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 29 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/storage/replica.go, line 3042 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18689#-Kujmi7g6cKQVnMdfFgB:-Kujmi7g6cKQVnMdfFgC:b-11gn5x) ([raw file](https://github.com/cockroachdb/cockroach/blob/87246c43f86f0af25ec3744c1dcd0499eb95a838/pkg/storage/replica.go#L3042)):*
> ```Go
> 	defer r.store.enqueueRaftUpdateCheck(r.RangeID)
> 
> 	if log.V(5) {
> ```

This will probably be annoying with `/debug/logspy`

---

*[pkg/storage/replica_state.go, line 306 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18689#-KujoHkG60EJA_Nk3Gyb:-KujoHkG60EJA_Nk3Gyc:bjy46tb) ([raw file](https://github.com/cockroachdb/cockroach/blob/486050d271a478ed72302e3089db66e454609535/pkg/storage/replica_state.go#L306)):*
> ```Go
> func (rsl replicaStateLoader) loadGCThreshold(
> 	ctx context.Context, reader engine.Reader,
> ) (*hlc.Timestamp, error) {
> ```

It seems weird to return a pointer here when most callers immediately dereference it. I'd rather keep this method (and loadTxnSpanGCThreshold) as it was, and use a local variable in the callers that do need a pointer (only replicaStateLoader.load, right?)

For MVCCStats it makes more sense to return a pointer because that's a big struct to copy around. 

---

*[pkg/storage/replica_test.go, line 5565 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/18689#-KujrOSUqq7LgUWvFPU5:-KujrOSUqq7LgUWvFPU6:bdcotjb) ([raw file](https://github.com/cockroachdb/cockroach/blob/f30c8d3b0553887e924dab3bc62a6e63a6c93432/pkg/storage/replica_test.go#L5565)):*
> ```Go
> 	// nontrivial lease requested with the first write below.
> 	baseStats.Add(enginepb.MVCCStats{
> 		SysBytes: 26,
> ```

Why did this increase? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18689#-:-KujsqnI3gR3LiYyaHs5:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: 0 of 29 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/storage/replica.go, line 3042 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/18689#-Kujmi7g6cKQVnMdfFgB:-Kuk7pnYyEEKBmfQEQM6:b-oqw0rg) ([raw file](https://github.com/cockroachdb/cockroach/blob/87246c43f86f0af25ec3744c1dcd0499eb95a838/pkg/storage/replica.go#L3042)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This will probably be annoying with `/debug/logspy`
</blockquote></details>

Yeah, I'll change this to `if false` before merging. It has been pretty handy it determining where the bytes are going.

---

*[pkg/storage/replica_state.go, line 306 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/18689#-KujoHkG60EJA_Nk3Gyb:-Kuk88IpyseWSkTrR0xU:b-68uhxc) ([raw file](https://github.com/cockroachdb/cockroach/blob/486050d271a478ed72302e3089db66e454609535/pkg/storage/replica_state.go#L306)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

It seems weird to return a pointer here when most callers immediately dereference it. I'd rather keep this method (and loadTxnSpanGCThreshold) as it was, and use a local variable in the callers that do need a pointer (only replicaStateLoader.load, right?)

For MVCCStats it makes more sense to return a pointer because that's a big struct to copy around. 
</blockquote></details>

While the other callers don't need a pointer, the pointer is already present (we're passing `&t` to `MVCCGetProto`). That was my rationale for changing the return type. 

---

*[pkg/storage/replica_test.go, line 5565 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/18689#-KujrOSUqq7LgUWvFPU5:-Kuk8PxDyiWl-32NtZ9Z:bwrj3q6) ([raw file](https://github.com/cockroachdb/cockroach/blob/f30c8d3b0553887e924dab3bc62a6e63a6c93432/pkg/storage/replica_test.go#L5565)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Why did this increase? 
</blockquote></details>

`initialState().SysBytes` decreased by 12 bytes for some reason which was affecting another test but not this one. I've forgotten the exact reason, let me get back to you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18689)*

**Comment by petermattis** [comment]
Review status: 0 of 29 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/storage/replica_test.go, line 5565 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/18689#-KujrOSUqq7LgUWvFPU5:-KukFEzUgPHk36k6PgGI:b2pqnx1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f30c8d3b0553887e924dab3bc62a6e63a6c93432/pkg/storage/replica_test.go#L5565)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`initialState().SysBytes` decreased by 12 bytes for some reason which was affecting another test but not this one. I've forgotten the exact reason, let me get back to you.
</blockquote></details>

When the first range is created, `replicaStateLoader.save` is called on an empty lease. The change to make some fields in `roachpb.Lease` nullable reduced encoded size of an empty lease from 26 bytes to 14 bytes which necessitated the change to `initalState().SysBytes`. But this test forces a valid lease to be written and doing so bumps up `SysBytes` again. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18689)*

**Comment by tschottdorf** [comment]
:lgtm:

The change makes me nervous but I think it's because I just don't know off the top of my head all the places in which we are serializing these. However, `below_raft_protos_test.go` has us covered, right?

Do you think we adequately protect against accidental re-blowup here in future changes? I assume those will be rare enough and scrutinized anyway, but just curious if there would be enough test breakage for the developer to realize that it's a really bad idea to make these structs any bigger than they need to be.

---

Reviewed 1 of 7 files at r1, 9 of 12 files at r6, 4 of 7 files at r7, 11 of 12 files at r8, 4 of 4 files at r9.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18689#-:-KutW5gb_alFAGj7P8Wn:b-ln7s3y)*

**Comment by petermattis** [comment]
Yes, `below_raft_protos_test.go` covers us. That test verifies both that the specified protos are seen below Raft and that their encodings haven't changed. I accidentally triggered breakage there when constructing this PR.

> Do you think we adequately protect against accidental re-blowup here in future changes? 

That's a good point and the answer is definitely no. I'll file an issue as I'm not quite sure what to do, though perhaps something as simple as encoding the zero value of `storagebase.RaftCommand` would be sufficient.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18689#-:-KutYzl_GOs5t9MbQHDe:bqnlz52)*

**Comment by petermattis** [comment]
Making `ReplicaState.Stats` nullable is causing `TestVersionUpgrade` to hang forever. Not at all sure why is that part of these changes looks innocuous. I'm investigating.

**Comment by petermattis** [comment]
The hang was caused by a node in the local cluster used by the acceptance test crashing with an assertion due to an assertion. Old nodes encode a zero-value `ReplicaState.Stats` which the new node happily decodes but was asserting that stats weren't being sent. The fix is a few lines. Thanks for the test @tschottdorf.

**Comment by tschottdorf** [comment]
:thumbsup: We really need to run these mixed-version clusters for longer periods of time. Is that on our priority TODO list somewhere?

---

Reviewed 28 of 28 files at r10, 12 of 12 files at r11, 7 of 7 files at r12, 12 of 12 files at r13, 4 of 4 files at r14.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/storage/replica_proposal.go, line 850 at r14](https://reviewable.io:443/reviews/cockroachdb/cockroach/18689#-KuyTgWj2FL-P3gdW_A4:-KuyTgWj2FL-P3gdW_A5:b97cai7) ([raw file](https://github.com/cockroachdb/cockroach/blob/589d16474fe94048d36dbe7a3d86fbfd4e2af22e/pkg/storage/replica_proposal.go#L850)):*
> ```Go
> 		}
> 
> 		if rResult.State.Stats != nil && (*rResult.State.Stats == enginepb.MVCCStats{}) {
> ```

Comment here wouldn't hurt.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18689#-:-KuyU-y_ikLZCQvpMw8W:b-3b8y1q)*

**Comment by petermattis** [comment]
> We really need to run these mixed-version clusters for longer periods of time. Is that on our priority TODO list somewhere?

Let me check. I'll file an issue if we don't already have one.

---

Review status: 10 of 29 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/storage/replica_proposal.go, line 850 at r14](https://reviewable.io:443/reviews/cockroachdb/cockroach/18689#-KuyTgWj2FL-P3gdW_A4:-KuyVHqrYcI-cIhL2Uyj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/589d16474fe94048d36dbe7a3d86fbfd4e2af22e/pkg/storage/replica_proposal.go#L850)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Comment here wouldn't hurt.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18689#-:-KuyV7lA6c6C85W-o2AE:b-et7oca)*

**Comment by tschottdorf** [comment]
Reviewed 19 of 19 files at r15, 7 of 7 files at r16, 12 of 12 files at r17, 4 of 4 files at r18.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18689)*

**Pull request merged**
