### PR TITLE
sql: add some logic tests for subqueries

### LINKED ISSUE #28716: sql: updates with subqueries with anonymous columns are broken
```
UPDATE abc SET a = 1, (b, c) = (SELECT 1, 2);
```

```
error setting up flow: ((1, 2) AS "?column?", "?column?"): found duplicate tuple label: "?column?"
```

### PR DESCRIPTION
**Pull request by rjnn**
Release note: None

Closes #28716.

### CODE REVIEW

**Review by jordanlewis — APPROVED** [review]
Can you also re-enable the tests I disabled in #28716?

**Comment by arjunravinarayan** [comment]
Are you referring to #28717, which is still an open PR which you have not merged?

**Comment by jordanlewis** [comment]
Er, yeah, oops

**Comment by arjunravinarayan** [comment]
bors r=jordanlewis

**Comment by arjunravinarayan** [comment]
@jordanlewis how do we feel about backporting for pure test changes like this? One the one hand we don't want unnecessary changes, on the other hand it might catch a regression. On the other other hand, there's unlikely to be a regression since it would have been caught in the master branch (since release is a subset of master)

**Comment by jordanlewis** [comment]
I would vote to backport. At the best, it'll issues in the release branch. At worst, it'll lessen any kind of merge conflict pain for tests.

**Comment by knz** [comment]
I would vote to backport too

**Pull request merged**
