### PR TITLE
sqlsmith: improvements

### PR DESCRIPTION
**Pull request by madelynnblue**
Various SQLsmith improvements in preparation for comparison testing and correlated subqueries.

Release note: None

### CODE REVIEW

**Comment by mjibson** [comment]
ping @justinj

**Review by justinj — COMMENTED** [review]
:lgtm:, sorry for the delay and thanks for the ping!

Something I think might be cool with these PRs would be to have a datadriven test that generated a handful of statements (maybe 10, maybe 100), possibly parameterized by the options framework you've added here. It could be seeded so pure refactorings wouldn't change it (up to like, reorderings of random calls, which I think is fine). There would obviously still be a lot of churn in that file but having a handful of examples of what we generate now included directly in a PR would be really nice when looking at code changes.

> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37456#-:-LeqhVED3DZ2txkrM2kw:b-cvpuwm)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mjibson)

___
*[pkg/internal/sqlsmith/relational.go, line 336 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/37456#-Leqh07w2_cDvVmPdBoH:-Leqh07w2_cDvVmPdBoI:b-k2ovrc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d4f9f9996903af4cdfa76aaeb054553e2f79ad5/pkg/internal/sqlsmith/relational.go#L336)):*
> ```Go
> }
> 
> func makeSelectTable(s *scope, refs colRefs, forJoin bool) (tree.TableExpr, colRefs, bool) {
> ```

I think this function could use a comment
___
*[pkg/internal/sqlsmith/relational.go, line 384 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/37456#-LeqhCPuEC3q0tTQuUFX:-LeqhCPuEC3q0tTQuUFY:b-9mpfwk) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d4f9f9996903af4cdfa76aaeb054553e2f79ad5/pkg/internal/sqlsmith/relational.go#L384)):*
> ```Go
> 	var fromRefs colRefs
> 	// Sometimes generate a SELECT with no FROM clause.
> 	for coin() {
> ```

this seems like a high percentage of the time to me but I have no actual evidence for that
___
*[pkg/internal/sqlsmith/relational.go, line 759 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/37456#-LeqhMfM5wl7RqZIU-wt:-LeqhMfM5wl7RqZIU-wu:b-us1lqj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d4f9f9996903af4cdfa76aaeb054553e2f79ad5/pkg/internal/sqlsmith/relational.go#L759)):*
> ```Go
> 	values, valuesRefs := makeValues(s, desiredTypes, refs)
> 
> 	// Returing just &values here would result in a query like `VALUES (...)` where
> ```

nit: `Returing` (present in the old version as well)
___
*[pkg/internal/sqlsmith/sqlsmith.go, line 125 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37456#-LeqfI2ACZYp4vbZYced:-LeqfI2ACZYp4vbZYcee:bi2ul2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f739921194c73f56ad75698d321546141fc51bd8/pkg/internal/sqlsmith/sqlsmith.go#L125)):*
> ```Go
> }
> 
> // SmitherOption is an option for the Smither client.
> ```

this is a cute pattern!

**Review by madelynnblue — COMMENTED** [review]
Yes, I've wanted this too. I want to do it in a way that is fairly deterministic and doesn't cause churn here because someone moved or added a function or operator in the tree package. I'll think about this more.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37456#-:-LerixzO0GMa2DCkT2AE:bmflsv3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj and @mjibson)

___
*[pkg/internal/sqlsmith/relational.go, line 336 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/37456#-Leqh07w2_cDvVmPdBoH:-Lerj6sZBn2N8fovqcjA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d4f9f9996903af4cdfa76aaeb054553e2f79ad5/pkg/internal/sqlsmith/relational.go#L336)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

I think this function could use a comment
</blockquote></details>

Done.
___
*[pkg/internal/sqlsmith/relational.go, line 384 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/37456#-LeqhCPuEC3q0tTQuUFX:-Lerj7JZ71l-PTOifSmG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d4f9f9996903af4cdfa76aaeb054553e2f79ad5/pkg/internal/sqlsmith/relational.go#L384)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

this seems like a high percentage of the time to me but I have no actual evidence for that
</blockquote></details>

Done.

**Pull request merged**
