### PR TITLE
builtins: array builtins handle mismatched tuple types

### LINKED ISSUE #70476: sql/tests: TestRandomSyntaxSQLSmith failed
sql/tests.TestRandomSyntaxSQLSmith [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3473202&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3473202&tab=artifacts#/) on master @ [676dc076dc6a137d88eac9217764bbb63beae86f](https://github.com/cockroachdb/cockroach/commits/676dc076dc6a137d88eac9217764bbb63beae86f):

Random syntax error:

```
    rsg_test.go:779: Crash detected: server panic: pq: internal error: unsupported comparison: oid to bytes
```
Query:

```
        SELECT
        	(-1):::INT8 AS col_1128285,
        	tab_532869.col2_1 AS col_1128286,
        	array_position(ARRAY[(1173684112:::OID,),(NULL,)], ('\xc03b4478eb':::BYTES,))::INT8 AS col_1128287,
        	tab_532867.crdb_internal_idx_expr AS col_1128288,
        	tab_532870.crdb_internal_mvcc_timestamp AS col_1128289,
        	NULL AS col_1128290,
        	tab_532868.tableoid AS col_1128291,
        	tab_532868.tableoid AS col_1128292,
        	'1992-11-20 03:49:26.000695+00:00':::TIMESTAMPTZ AS col_1128293,
        	(tab_532867.col2_3::INT8 >> (-3486767938233063631):::INT8::INT8)::INT8 AS col_1128294,
        	(-1):::INT8 AS col_1128295
        FROM
        	defaultdb.public.table2@table2_col2_0_col2_1_col2_2_col2_3_idx AS tab_532867,
        	defaultdb.public.table2@[0] AS tab_532868
        	JOIN defaultdb.public.table2@[0] AS tab_532869 ON false,
        	defaultdb.public.table2@table2_col2_2_expr_col2_0_expr1_idx AS tab_532870
        WHERE
        	true;
```
Schema:

```
    rsg_test.go:596: To reproduce, use schema:
    rsg_test.go:598: 
        		SET CLUSTER SETTING sql.stats.automatic_collection.enabled = false;
        		SET CLUSTER SETTING sql.stats.histogram_collection.enabled = false;
        		SET CLUSTER SETTING sql.defaults.interleaved_tables.enabled = true;
        	CREATE TABLE table1 (col1_0 INT2 NULL, INDEX (col1_0), UNIQUE (col1_0 DESC) WHERE table1.col1_0 <= 32767:::INT8, INDEX (col1_0), INDEX (col1_0 ASC), UNIQUE (col1_0), INDEX (col1_0) WHERE table1.col1_0 > (-1):::INT8, INDEX (col1_0 DESC) WHERE table1.col1_0 >= 32767:::INT8, INDEX (col1_0), UNIQUE (col1_0));
        CREATE TABLE table2 (col2_0 TIMESTAMPTZ NOT NULL, col2_1 REGPROCEDURE NOT NULL, col2_2 INT4 NOT NULL, col2_3 INT8 NOT NULL, PRIMARY KEY (col2_1 DESC, col2_0 ASC, col2_3), INDEX (col2_2 DESC, col2_0 DESC), UNIQUE (col2_3 DESC, col2_0 ASC) WHERE table2.col2_3 != 32767:::INT8, INDEX (col2_0 DESC, col2_1 ASC, col2_2, col2_3 DESC) WHERE ((table2.col2_2 >= 0:::INT8) OR (table2.col2_0 != '294276-12-31 23:59:59.999999+00:00':::TIMESTAMPTZ)) OR (table2.col2_3 > (-128):::INT8), UNIQUE (col2_1 ASC), INDEX (col2_2 ASC, (CASE WHEN col2_0 IS NULL THEN e'X\x18$\x11I6\r':::STRING ELSE e'C\b\'/6(':::STRING END), col2_0 ASC, (col2_2 + col2_3) DESC), UNIQUE (col2_1, col2_0 DESC, col2_2 ASC) WHERE ((table2.col2_0 = '3000-01-01 00:00:00+00:00':::TIMESTAMPTZ) OR (table2.col2_3 >= (-2147483648):::INT8)) OR (table2.col2_2 >= 1:::INT8), FAMILY (col2_0), FAMILY (col2_2, col2_3, col2_1), UNIQUE (col2_2));
        ALTER TABLE table1 INJECT STATISTICS '[{"columns": ["col1_0"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 5104017871428977943, "histo_buckets": [{"distinct_range": 0, "num_eq": 40000000, "num_range": 0, "upper_bound": "13093"}], "histo_col_type": "INT2", "name": "__auto__", "null_count": 8989897701368440168, "row_count": 9055058578208466492}]':::JSONB;
        ALTER TABLE table2 INJECT STATISTICS '[{"columns": ["col2_2"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 7904702, "histo_buckets": [{"distinct_range": 0, "num_eq": 6921569931402439194, "num_range": 0, "upper_bound": "-1675587582"}, {"distinct_range": 1620191154237186600, "num_eq": 101348852754977614, "num_range": 8976110562440874917, "upper_bound": "-572419750"}, {"distinct_range": 404.33391430455134, "num_eq": 500000000, "num_range": 500, "upper_bound": "1147744038"}], "histo_col_type": "INT4", "name": "__auto__", "null_count": 0, "row_count": 8000000}, {"columns": ["col2_3"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 4845613, "histo_buckets": [{"distinct_range": 0, "num_eq": 8000000000, "num_range": 0, "upper_bound": "-8876981534753377004"}], "histo_col_type": "INT8", "name": "__auto__", "null_count": 0, "row_count": 8000000}, {"columns": ["col2_0"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 5987192, "histo_buckets": [{"distinct_range": 0, "num_eq": 60000, "num_range": 0, "upper_bound": "2029-03-27 21:30:43.000333+00:00"}], "histo_col_type": "TIMESTAMPTZ", "name": "__auto__", "null_count": 0, "row_count": 8000000}, {"columns": ["col2_1"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 3637731, "histo_buckets": [{"distinct_range": 0, "num_eq": 50, "num_range": 0, "upper_bound": "1638559855"}, {"distinct_range": 0, "num_eq": 50000000000, "num_range": 0, "upper_bound": "2729383840"}, {"distinct_range": 70000000, "num_eq": 2627280684520698847, "num_range": 70000000, "upper_bound": "3647080921"}, {"distinct_range": 342.67100677751387, "num_eq": 3000, "num_range": 2000, "upper_bound": "3654389876"}, {"distinct_range": 1037395906969251200, "num_eq": 3200707335841305569, "num_range": 1037395906969251154, "upper_bound": "4006606552"}], "histo_col_type": "REGPROCEDURE", "name": "__auto__", "null_count": 0, "row_count": 8000000}]':::JSONB;
        ALTER TABLE table1 ADD FOREIGN KEY (col1_0) REFERENCES table2 (col2_2) ON DELETE SET DEFAULT;
        CREATE TYPE rand_typ_0 AS ENUM ('rmyhik', 'uxb');
        CREATE TYPE rand_typ_1 AS ENUM ('wo');
        CREATE TYPE rand_typ_2 AS ENUM ('nye', 'a');
        ;
    rsg_test.go:598: 
        CREATE TYPE greeting AS ENUM ('hello', 'howdy', 'hi', 'good day', 'morning');
        CREATE TABLE IF NOT EXISTS seed AS
        	SELECT
        		g::INT2 AS _int2,
        		g::INT4 AS _int4,
        		g::INT8 AS _int8,
        		g::FLOAT4 AS _float4,
        		g::FLOAT8 AS _float8,
        		'2001-01-01'::DATE + g AS _date,
        		'2001-01-01'::TIMESTAMP + g * '1 day'::INTERVAL AS _timestamp,
        		'2001-01-01'::TIMESTAMPTZ + g * '1 day'::INTERVAL AS _timestamptz,
        		g * '1 day'::INTERVAL AS _interval,
        		g % 2 = 1 AS _bool,
        		g::DECIMAL AS _decimal,
        		g::STRING AS _string,
        		g::STRING::BYTES AS _bytes,
        		substring('00000000-0000-0000-0000-' || g::STRING || '00000000000', 1, 36)::UUID AS _uuid,
        		'0.0.0.0'::INET + g AS _inet,
        		g::STRING::JSONB AS _jsonb,
        		enum_range('hello'::greeting)[g] as _enum
        	FROM
        		generate_series(1, 5) AS g;
        
        INSERT INTO seed DEFAULT VALUES;
        CREATE INDEX on seed (_int8, _float8, _date);
        CREATE INVERTED INDEX on seed (_jsonb);
        ;
    rsg_test.go:600: 
    rsg_test.go:601: -- test log scope end --
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestRandomSyntaxSQLSmith274670283
--- FAIL: TestRandomSyntaxSQLSmith (300.97s)
```
<details><summary>Reproduce</summary>
<p>
To reproduce, try:

```bash
make stressrace TESTS=TestRandomSyntaxSQLSmith PKG=./pkg/sql/tests TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #70000 sql/tests: TestRandomSyntaxSQLSmith failed [NPE in index join] [C-test-failure GA-blocker O-robot T-sql-queries branch-release-21.2]
- #64592 sql/tests: TestRandomSyntaxSQLSmith failed [C-test-failure O-robot T-sql-queries branch-release-21.1]
</p>
</details>
<details><summary>Internal log</summary>
<p>

```
mjibson marked as alumn{us/a}; resolving to rafiss instead
```
</p>
</details>

/cc @cockroachdb/sql-experience rafiss
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRandomSyntaxSQLSmith.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #70477: roachtest: sqlsmith/setup=rand-tables/setting=no-ddl failed
roachtest.sqlsmith/setup=rand-tables/setting=no-ddl [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3473201&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3473201&tab=artifacts#/sqlsmith/setup=rand-tables/setting=no-ddl) on master @ [676dc076dc6a137d88eac9217764bbb63beae86f](https://github.com/cockroachdb/cockroach/commits/676dc076dc6a137d88eac9217764bbb63beae86f):

```
			with_1189 (col_7059)
				AS (
					SELECT
						*
					FROM
						(
							VALUES
								(
									CASE
									WHEN false
									THEN ARRAY[(2498598801:::OID, '\x':::BYTES, 'BOX(-1.473549306724302 -1.3600410344013085,0.23926956800717214 0.8180963348960345)':::BOX2D)]
									ELSE ARRAY[]:::RECORD[]
									END
								),
								(
									ARRAY[(2744992465:::OID, '\xfe':::BYTES, 'BOX(0.545468405248748 -0.9431645714585375,0.5635750195823661 -0.4446846801174844)':::BOX2D),(1920508521:::OID, NULL, 'BOX(-1.6320405588326239 -2.7235542450942307,1.580224575524476 1.0509215072592037)':::BOX2D),(4176104366:::OID, NULL, 'BOX(-1.0791788396134159 -0.5683784035565729,0.22911363649496352 0.06660776683378988)':::BOX2D),(936593898:::OID, '\x4c':::BYTES, 'BOX(0.38572015570367824 0.06600980533862477,0.7350638495975028 0.636032225362754)':::BOX2D),(3966419895:::OID, NULL, 'BOX(-10 -10,10 10)':::BOX2D)]
								),
								(
									ARRAY[(209636487:::OID, '\x368044':::BYTES, NULL),(1569974628:::OID, '\x6af68547642d5e95e6':::BYTES, 'BOX(-0.36487022223640864 -0.16444712171311313,0.8493663182844707 1.8182103803843979)':::BOX2D)]
								),
								(
									ARRAY[(2975694003:::OID, '\x22':::BYTES, 'BOX(-0.3485663832426801 -0.8544256669872184,0.5944111285915109 0.6101885378360927)':::BOX2D),(3669526711:::OID, '\x474b725a07':::BYTES, 'BOX(0.3505346936549236 -1.1186423048501075,0.4106421376096584 0.5871813566098203)':::BOX2D),(986739408:::OID, '\x86bbcd614a89f4':::BYTES, 'BOX(-10 -10,10 10)':::BOX2D),(397688687:::OID, '\xb04e':::BYTES, 'BOX(-0.9316307544003903 -0.8348736482597704,0.5494110968839473 1.0894104755156842)':::BOX2D)]
								)
						)
							AS tab_3477 (col_7059)
					EXCEPT ALL
						SELECT
							*
						FROM
							(
								VALUES
									(ARRAY[]:::RECORD[]),
									(NULL),
									(
										ARRAY[(3135613574:::OID, '\xafd8458a2b34a0':::BYTES, 'BOX(0.2831964323498861 -0.5353622726900271,0.5594993099538235 1.213409163649324)':::BOX2D),(160078674:::OID, '\x3932fe':::BYTES, 'BOX(0.23208330216451478 -0.48268581503464275,0.9676324327606974 0.27993347712692973)':::BOX2D),(2118718584:::OID, '\x30':::BYTES, 'BOX(-1.1618342849754377 -0.44730213233472216,-0.049716782872001763 0.9414706895771634)':::BOX2D)]
									),
									(
										ARRAY[(742831845:::OID, NULL, 'BOX(-2.1510834786106874 0.8912499822304156,0.13493658301585068 1.583184003270404)':::BOX2D)]
									)
							)
								AS tab_3478 (col_7060)
				)
		SELECT
			cte_ref_361.col_7059 AS col_7061
		FROM
			with_1189 AS cte_ref_361
		WHERE
			true
		LIMIT
			57:::INT8;
```
<details><summary>Reproduce</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sqlsmith/setup=rand-tables/setting=no-ddl.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #70478: roachtest: sqlsmith/setup=empty/setting=no-mutations failed
roachtest.sqlsmith/setup=empty/setting=no-mutations [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3473201&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3473201&tab=artifacts#/sqlsmith/setup=empty/setting=no-mutations) on master @ [676dc076dc6a137d88eac9217764bbb63beae86f](https://github.com/cockroachdb/cockroach/commits/676dc076dc6a137d88eac9217764bbb63beae86f):

```
													('17:28:14.764522+14:43:00':::TIMETZ),
													('07:23:03.812281+14:50:00':::TIMETZ),
													(
														parse_timetz(COALESCE(st_astext('01030000C0010000000600000070EBF2E3C6B0FCC12418761831E2FEC1BEF7A174620F014290AE7E7800F10042A0E5BFE035CDF8C1FBF9AEBA467F00C2955B7F1FADF900C22E37DC6732D7F9C1F8291D6E8EC7F941342DD7B74BECF6C12CDCD92FA44FFE415C8813B08A060142CA9A4CD716F2FAC160827E0A3AD0E441C2A16B9537A6F441E8E10023E840FF41BC4F7B62083AFBC1009D25D3324EECC1647CD166902AFB418C99946456D0014270EBF2E3C6B0FCC12418761831E2FEC1BEF7A174620F014290AE7E7800F10042':::GEOMETRY::GEOMETRY)::STRING, e'\x1c':::STRING)::STRING)::TIMETZ
													),
													('04:50:55.334281-00:35:00':::TIMETZ)
											)
												AS tab_97115 (col_167897)
											LEFT JOIN (
													VALUES
														('ffc2e94c-474a-45b0-933c-cf76cc75bce3':::UUID),
														('2c6a5785-6910-4180-a14e-71319f6862a5':::UUID),
														(uuid_generate_v4()::UUID),
														('203ac89f-0554-4aed-8f55-e9259898b6a9':::UUID),
														(NULL)
												)
													AS tab_97116 (col_167898) ON false,
											(
												VALUES
													('ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff':::INET),
													('7a5f:be04:ed4a:c9ca:1e60:169f:8a5f:2ab/108':::INET)
											)
												AS tab_97117 (col_167899)
										ORDER BY
											tab_97117.col_167899, tab_97117.col_167899, tab_97117.col_167899
										LIMIT
											1:::INT8
									)
								),
								('0104000060E610000000000000':::GEOGRAPHY, NULL)
						)
							AS tab_97118 (col_167901, col_167902)
				)
		SELECT
			tab_97119.col_167904 AS col_167905
		FROM
			(
				VALUES
					(NULL),
					('20 years 181 days 06:29:21.419479':::INTERVAL),
					('59 years 524 days 02:49:03.527908':::INTERVAL),
					('-51 years -5 mons -748 days -06:39:54.748217':::INTERVAL),
					(parse_interval(e',1-\x04Bh``':::STRING::STRING, e'\x05\x04%R!)EbC':::STRING::STRING)::INTERVAL),
					('-46 years -2 mons -829 days -13:15:27.684704':::INTERVAL)
			)
				AS tab_97119 (col_167904)
		WHERE
			true
		LIMIT
			87:::INT8;
```
<details><summary>Reproduce</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sqlsmith/setup=empty/setting=no-mutations.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #70479: roachtest: sqlsmith/setup=empty/setting=no-ddl failed
roachtest.sqlsmith/setup=empty/setting=no-ddl [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3473201&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3473201&tab=artifacts#/sqlsmith/setup=empty/setting=no-ddl) on master @ [676dc076dc6a137d88eac9217764bbb63beae86f](https://github.com/cockroachdb/cockroach/commits/676dc076dc6a137d88eac9217764bbb63beae86f):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/sqlsmith/setup=empty/setting=no-ddl/run_1
	sqlsmith.go:223,sqlsmith.go:256,test_runner.go:777: error: pq: internal error: unsupported comparison: timestamp to bytes
		stmt:
		WITH
			with_71004 (col_391145)
				AS (
					SELECT * FROM (VALUES (NULL)) AS tab_225807 (col_391145)
					EXCEPT
						SELECT
							*
						FROM
							(
								VALUES
									(NULL),
									(1567895379902433814:::INT8),
									(
										array_position(ARRAY[('1977-01-01 10:45:28.000758':::TIMESTAMP,)], ('\x0a9a3add':::BYTES,))::INT8
									),
									(7654332206291370363:::INT8),
									((-1365007790917372966):::INT8)
							)
								AS tab_225808 (col_391146)
				)
		SELECT
			cte_ref_20869.col_391145 AS col_391147
		FROM
			with_71004 AS cte_ref_20869;
```
<details><summary>Reproduce</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sqlsmith/setup=empty/setting=no-ddl.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #70480: roachtest: sqlsmith/setup=rand-tables/setting=no-mutations failed
roachtest.sqlsmith/setup=rand-tables/setting=no-mutations [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3473201&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3473201&tab=artifacts#/sqlsmith/setup=rand-tables/setting=no-mutations) on master @ [676dc076dc6a137d88eac9217764bbb63beae86f](https://github.com/cockroachdb/cockroach/commits/676dc076dc6a137d88eac9217764bbb63beae86f):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/sqlsmith/setup=rand-tables/setting=no-mutations/run_1
	sqlsmith.go:223,sqlsmith.go:256,test_runner.go:777: error: pq: internal error: unsupported comparison: tuple{string, int, oid} to int
		stmt:
		WITH
			with_71732 (col_414542)
				AS (
					SELECT
						*
					FROM
						(
							VALUES
								(
									array_position(ARRAY[((e'\x0e':::STRING, 31556:::INT8, 331210964:::OID),),(NULL,)], ((-896085258028685518):::INT8,))::INT8
								),
								((-4986756069795272852):::INT8),
								((-7123102237259851310):::INT8)
						)
							AS tab_174992 (col_414542)
				)
		SELECT
			(-2675824421837083566):::INT8 AS col_414543
		FROM
			with_71732 AS cte_ref_20912
		WHERE
			(true OR (false AND false));
```
<details><summary>Reproduce</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sqlsmith/setup=rand-tables/setting=no-mutations.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #70481: roachtest: sqlsmith/setup=seed/setting=no-mutations failed
roachtest.sqlsmith/setup=seed/setting=no-mutations [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3473201&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3473201&tab=artifacts#/sqlsmith/setup=seed/setting=no-mutations) on master @ [676dc076dc6a137d88eac9217764bbb63beae86f](https://github.com/cockroachdb/cockroach/commits/676dc076dc6a137d88eac9217764bbb63beae86f):

```
													),
													('02:03:11.545452-13:43:00':::TIMETZ),
													(
														COALESCE(
															'01:46:27.891035+08:41:00':::TIMETZ,
															'19:24:57.767116+02:22:00':::TIMETZ
														)
													),
													(current_time():::TIMETZ::TIMETZ),
													('07:44:03.830253+09:54:00':::TIMETZ)
											)
												AS tab_201837 (col_494426)
									),
								with_82569 (col_494427) AS (SELECT * FROM (VALUES (NULL)) AS tab_201838 (col_494427))
							SELECT
								xor_agg(NULL::BYTES)::BYTES AS col_494428
							FROM
								with_82569 AS cte_ref_23921, defaultdb.public.seed@[0] AS tab_201839
							GROUP BY
								tab_201839._timestamptz, tab_201839._inet, tab_201839._enum, tab_201839._interval
							HAVING
								bool_and(tab_201839._bool::BOOL)::BOOL
							LIMIT
								1:::INT8
						)
							AS col_494429
				),
			with_82571 (col_494430)
				AS (
					SELECT
						DISTINCT tab_201840.tableoid AS col_494430
					FROM
						defaultdb.public.seed@seed__int8__float8__date_idx AS tab_201840
				),
			with_82572 (col_494431, col_494432)
				AS (
					SELECT
						array_position(ARRAY[('BOX(-1.241191578331188 -0.04261105775422375,0.14167690557916834 0.19717549768354256)':::BOX2D,),('BOX(0.5915456580358189 -0.003393763269594091,1.0262242951906049 1.6577644902169602)':::BOX2D,),(NULL,),(NULL,)], ('':::STRING,))::INT8
							AS col_494431,
						'01070000E0E61000000200000001010000E0E6100000E0D9B6CF314B45407C58689A1D5451404B10DE427411F2C174AAB2472CF9EE4101040000E0E61000000100000001010000C0CEE17B794B886540700D902A9C5F4D40005E325DDD07DF4104D3CAEB2565DBC1':::GEOGRAPHY
							AS col_494432
					FROM
						with_82571 AS cte_ref_23922
					WHERE
						true
				)
		SELECT
			tab_201841.crdb_internal_mvcc_timestamp AS col_494433
		FROM
			defaultdb.public.seed@seed__int8__float8__date_idx AS tab_201841;
```
<details><summary>Reproduce</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sqlsmith/setup=seed/setting=no-mutations.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #70610: roachtest: sqlsmith/setup=tpch-sf1/setting=no-mutations failed
roachtest.sqlsmith/setup=tpch-sf1/setting=no-mutations [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3485082&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3485082&tab=artifacts#/sqlsmith/setup=tpch-sf1/setting=no-mutations) on master @ [a465b0d5d51a6534d39e0683fd037d132bcbd576](https://github.com/cockroachdb/cockroach/commits/a465b0d5d51a6534d39e0683fd037d132bcbd576):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/sqlsmith/setup=tpch-sf1/setting=no-mutations/run_1
	sqlsmith.go:223,sqlsmith.go:256,test_runner.go:777: error: pq: internal error: unsupported comparison: varbit to string
		stmt:
		SELECT
			tab_375.l_linestatus AS col_915,
			tab_375.tableoid AS col_916,
			0.44443737497633484:::FLOAT8 AS col_917,
			'1971-04-29':::DATE AS col_918,
			3373681434006237581:::INT8 AS col_919,
			e'$N``\x12nV\x05)\x16':::STRING AS col_920,
			array_position(ARRAY[(NULL,),(B'00111110111111001011010101101100101001',)], (e'\x06':::STRING,))::INT8 AS col_921,
			tab_374.l_discount AS col_922
		FROM
			defaultdb.public.lineitem@[0] AS tab_374
			JOIN defaultdb.public.lineitem@l_rd AS tab_375 ON (tab_374.l_commitdate) = (tab_375.l_receiptdate)
		WHERE
			false
		ORDER BY
			tab_375.l_tax ASC
		LIMIT
			87:::INT8;
```
<details><summary>Reproduce</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sqlsmith/setup=tpch-sf1/setting=no-mutations.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/70481
fixes https://github.com/cockroachdb/cockroach/issues/70480
fixes https://github.com/cockroachdb/cockroach/issues/70479
fixes https://github.com/cockroachdb/cockroach/issues/70478
fixes https://github.com/cockroachdb/cockroach/issues/70477
fixes https://github.com/cockroachdb/cockroach/issues/70476

The first commit is a refactor to add a new CompareError method
to Datum. It propagates errors instead of panicking.

Since these builtins take in AnyTuple, the tuple contents aren't
type-checked. Instead, we must handle any errors that occur during tuple
comparison at execution-time. This matches the PostgresSQL behavior.

No release note since this bug was never released anywhere.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Drive-by suggestion: maybe it would be simpler to add a panic-catcher specifically when comparing something with arrays?

**Review by otan — APPROVED** [review]
i'm really hesitant on panic catchers and rather we catch em explicitly.
there have been cases (e.g. spatial) where i wanted an error with Compare but never bothered, might as well begin the pain of ripping off the bandaid...

up to rafi too though. the changes here lgtm :)

**Comment by rafiss** [comment]
tftr!

bors r=otan

**Comment by rafiss** [comment]
whoops i missed the github ci failure

**Comment by rafiss** [comment]
bors r=otan

**Comment by rafiss** [comment]
bors r=otan

**Pull request merged**
