### PR TITLE
roachprod:add --aws-use-spot

### PR DESCRIPTION
**Pull request by BabuSrithar**
This change adds an option to use AWS spot VMs to power CRDB clusters. AWS Spot VMs are significantly cheaper, but can be preempted by AWS at anytime.

Related PR : https://github.com/cockroachdb/cockroach/pull/105470

Epic: none

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114342#-:-NjAeTnY62-v-KW4Rb0G:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @BabuSrithar, @DarrylWong, @renatolabs, and @srosenberg)

___
*[`pkg/roachprod/vm/aws/aws.go` line 906 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114342#-NjAeHso7LBy5jGX3w1H:-NjAeHso7LBy5jGX3w1I:b-4taxrw) ([raw file](https://github.com/cockroachdb/cockroach/blob/11b25a39a0245ee5836d8fa4bad4fb77b036fd04/pkg/roachprod/vm/aws/aws.go#L906)):*
> ```Go
> 			InstanceType          string
> 			InstanceLifecycle     string `json:"InstanceLifecycle"`
> 			SpotInstanceRequestId string `json:"SpotInstanceRequestId"`
> ```

[nit] RequestID
___
*[`pkg/roachprod/vm/aws/aws.go` line 914 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114342#-NjAeGiz18obnH7MS2vs:-NjAeGj-4gJtuUrk0scX:b-4taxrw) ([raw file](https://github.com/cockroachdb/cockroach/blob/11b25a39a0245ee5836d8fa4bad4fb77b036fd04/pkg/roachprod/vm/aws/aws.go#L914)):*
> ```Go
> type CancelSpotInstanceRequestsOutput struct {
> 	CancelledSpotInstanceRequests []struct {
> 		SpotInstanceRequestId string `json:"SpotInstanceRequestId"`
> ```

[nit] RequestID

**Comment by BabuSrithar** [comment]
*[`pkg/roachprod/vm/aws/aws.go` line 906 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114342#-NjAeHso7LBy5jGX3w1H:-NjAzamd1RdYHfN93hju:b-hn5buk) ([raw file](https://github.com/cockroachdb/cockroach/blob/11b25a39a0245ee5836d8fa4bad4fb77b036fd04/pkg/roachprod/vm/aws/aws.go#L906)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] RequestID
</blockquote></details>

I went with the naming convention of AWS's json fields. Thought json field and variable names aligned would make sense.

**Comment by BabuSrithar** [comment]
*[`pkg/roachprod/vm/aws/aws.go` line 914 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114342#-NjAeGiz18obnH7MS2vs:-NjAzsfo7EBrs8NDd0Kc:b-hn5buk) ([raw file](https://github.com/cockroachdb/cockroach/blob/11b25a39a0245ee5836d8fa4bad4fb77b036fd04/pkg/roachprod/vm/aws/aws.go#L914)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] RequestID
</blockquote></details>

I went with the naming convention of AWS's json fields. Thought json field and variable names aligned would make sense.

**Review by RaduBerinde — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114342)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong, @renatolabs, and @srosenberg)

**Review by srosenberg — APPROVED** [review]
Minor comments. :lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114342#-:-NjIQ7UYB88h9kuva296:brcxnaa)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @BabuSrithar, @DarrylWong, @RaduBerinde, and @renatolabs)

___
*[`pkg/roachprod/vm/aws/aws.go` line 1184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114342#-NjIOKqaBnsWuecBpI6K:-NjIOKqbBoxBQUkbMecK:b3eowp2) ([raw file](https://github.com/cockroachdb/cockroach/blob/11b25a39a0245ee5836d8fa4bad4fb77b036fd04/pkg/roachprod/vm/aws/aws.go#L1184)):*
> ```Go
> 
> // runSpotInstance uses run-instances command to create a spot instance.
> // It returns an error if the spot request is not fulfilled within 2 minutes.
> ```

What's the significance of the 2 minutes; i.e., how was this value chosen?
___
*[`pkg/roachprod/vm/aws/aws.go` line 1199 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114342#-NjIOob59BycZhlW5ZD8:-NjIOob59BycZhlW5ZD9:brb4c8k) ([raw file](https://github.com/cockroachdb/cockroach/blob/11b25a39a0245ee5836d8fa4bad4fb77b036fd04/pkg/roachprod/vm/aws/aws.go#L1199)):*
> ```Go
> 	}
> 	// If the spot request is accepted, the run-instances command will return an instance-id.
> 	if len(runInstancesOutput.Instances) > 0 {
> ```

Nit: straight-line code is easier to follow, i.e.,

```
if len(runInstancesOutput.Instances) == 0 {
    return errors.Errorf("No instances found for spot request, likely the spot request had bad parameter")
}
``
```

___
*[`pkg/roachprod/vm/aws/aws.go` line 1280 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114342#-NjIPnpz0N3WqWfcnekd:-NjIPnpz0N3WqWfcneke:bl725jt) ([raw file](https://github.com/cockroachdb/cockroach/blob/11b25a39a0245ee5836d8fa4bad4fb77b036fd04/pkg/roachprod/vm/aws/aws.go#L1280)):*
> ```Go
> 	instanceId string,
> ) (fullFilled bool, err error) {
> 	if len(describeSpotInstanceRequestsOutput.SpotInstanceRequests) > 0 {
> ```

Nit: same as above; doing the error check & bailout first leads to more straight-line, and hence readable code.

**Comment by BabuSrithar** [comment]
*[`pkg/roachprod/vm/aws/aws.go` line 1184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114342#-NjIOKqaBnsWuecBpI6K:-NjIVRb9BMfT1zvnIgSb:bbgi8iy) ([raw file](https://github.com/cockroachdb/cockroach/blob/11b25a39a0245ee5836d8fa4bad4fb77b036fd04/pkg/roachprod/vm/aws/aws.go#L1184)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

What's the significance of the 2 minutes; i.e., how was this value chosen?
</blockquote></details>

No concrete reason about the value. Thought 2 mins is a practical time we can wait for. It was also biased by the 2 mins preemption warning that aws gives.

**Comment by BabuSrithar** [comment]
bors+

**Pull request merged**
