### PR TITLE
ui: update docs link to 2.0

### PR DESCRIPTION
**Pull request by couchand**
Fixes: #21892
Release note (admin ui change): Links to documentation in the Admin UI are
updated to point to the docs for version 2.0.

### CODE REVIEW

**Comment by couchand** [comment]
cc @jseldess

**Review by benesch — APPROVED** [review]
It occurs to me that it's no longer as onerous to derive the URL from `build.VersionPrefix()`, since bindata.go is no longer checked in to the repo. Food for thought.

**Comment by couchand** [comment]
@benesch would that be an update to `process-bindata.sed`?  forgive me, I'm not immediately seeing how to stick it in

**Review by jseldess — COMMENTED** [review]
@couchand, @benesch, do we just want the UI to point to the latest stable docs? If so, why wouldn't this just be `https://www.cockroachlabs.com/docs/v2.0`?

**Comment by benesch** [comment]
@jseldess I'm not sure I totally follow. We want e.g. v1.1 binaries to always point to the v1.1 docs and v2.0 binaries to always point to the v2.2 docs, but ideally we could engineer a solution that doesn't involve bumping the versions manually.

@couchand I'm also not sure how to stick it in :). Before it wasn't worth trying, because anything that made bindata.go dependent on what git branch you were on was bad news bears. (Creating a feature branch would mean your next build would create a bindata.go diff.) But now that bindata.go isn't checked in we can actually pursue a solution. I certainly don't recommend you hold up this PR, though.

**Comment by jseldess** [comment]
Ah, that makes sense. We don't want to do this before we release the last 1.1.x version, though, right?

**Comment by benesch** [comment]
We have a separate branch for each major (n.n) release. We actually should have bumped this the day the first 1.2/2.0 alpha came out.

**Comment by jseldess** [comment]
Ah, of course. Good point, @benesch!

**Pull request merged**
