### PR TITLE
ui: add timescale to diag details page

### LINKED ISSUE #92417: Add time selector to the Diagnostics tab including collection time
This issue breaks down https://github.com/cockroachdb/cockroach/issues/90292 and https://github.com/cockroachdb/cockroach/issues/82896#issuecomment-1163812677 in the context of statement bundles.

The time selector and selected ranges should persist across all console pages to allow for correlation, especially for scenarios when troubleshooting outliers. 

Related issues

- https://github.com/cockroachdb/cockroach/issues/92415
- https://github.com/cockroachdb/cockroach/issues/92416

Epic: CRDB-8649

Jira issue: CRDB-21756

### PR DESCRIPTION
**Pull request by maryliag**
Fixes https://github.com/cockroachdb/cockroach/issues/92417

This commit adds a time scale picker to the Diagnostics
tab on Statement Details page. The time scale is aligned
with the other ones, and now is possible to see bundles
from only the selected period.

This commit also makes some UX updates on the same tab,
making it use the same SortedTable component as other pages,
removing the white background and title to align with
all other pages that no longer have those items.

Before
Screenshot 2023-04-13 at 11 12 04 AM

After
Screenshot 2023-04-13 at 3 47 12 PM
Screenshot 2023-04-13 at 3 47 21 PM

https://www.loom.com/share/69f024c0523c4a8c814276f2786ab8a8

Release note (ui change): Add a time scale selector to the Diagnostics
tab under the Statement Details page, make it possible to see bundles
only from the selected period.

### CODE REVIEW

**Review by dongniwang — APPROVED** [review]
LGTM! Thanks!

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101489)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx` line 891 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101489#gh-1170169925:-NTK3Oe21CDY1grDTI1L:b-4y1vfi) ([raw file](https://github.com/cockroachdb/cockroach/blob/a94f97f00b927011433e78bf28d712c093b0a1a7/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx#L891)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Since you're null coalescing here, do we want the first case when it's nullish or 0, i.e. `!this.props.statementDetails?.statement?.metadata?.query.length`, or do you specifically only want to render this.state.formattedQuery if the length is 0?
</blockquote></details>

I want to use the state one when the value of the query is an empty string. I believe we always have a value for the query (if we have metadata), but it can be an empty string. That is the case where I want to use the state one instead, so this is why the check for length 0
___
*[`pkg/ui/workspaces/cluster-ui/src/statementDetails/diagnostics/diagnosticsUtils.ts` line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101489#gh-1170158959:-NTK3oZPCZfrfO_Vfk3d:b-rg5po6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a94f97f00b927011433e78bf28d712c093b0a1a7/pkg/ui/workspaces/cluster-ui/src/statementDetails/diagnostics/diagnosticsUtils.ts#L32)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Do these comparison operators just work with momemt objects, or do we need to use the compare functions on the moment object?
</blockquote></details>

Sorry, I don't follow the two options you mention.
To clarify: start and end are moment objects, if I don't convert the request_at the comparison will not work properly (I indeed tested this initially when creating this function), that is why I converted to moment.

**Comment by xinhaoz** [comment]
*[`pkg/ui/workspaces/cluster-ui/src/statementDetails/diagnostics/diagnosticsUtils.ts` line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101489#gh-1170158959:-NTKUDDu5S5m5ibpupkl:bmggz4k) ([raw file](https://github.com/cockroachdb/cockroach/blob/a94f97f00b927011433e78bf28d712c093b0a1a7/pkg/ui/workspaces/cluster-ui/src/statementDetails/diagnostics/diagnosticsUtils.ts#L32)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

Sorry, I don't follow the two options you mention.
To clarify: start and end are moment objects, if I don't convert the request_at the comparison will not work properly (I indeed tested this initially when creating this function), that is why I converted to moment.
</blockquote></details>

Oh bc I recall moment has functions like `isSame` `isBefore` etc on it, so I was just wondering if the operators `<, <=, etc` worked as expected or if we had to use the specific momentjs comparison functions.

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101489)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/statementDetails/diagnostics/diagnosticsUtils.ts` line 32 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101489#gh-1170158959:-NTK_mGV-RC3LJDJFLuL:banpdl1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a94f97f00b927011433e78bf28d712c093b0a1a7/pkg/ui/workspaces/cluster-ui/src/statementDetails/diagnostics/diagnosticsUtils.ts#L32)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Oh bc I recall moment has functions like `isSame` `isBefore` etc on it, so I was just wondering if the operators `<, <=, etc` worked as expected or if we had to use the specific momentjs comparison functions.
</blockquote></details>

Ahh now I see what you mean. Both ways work, but I changed to use the functions from momentjs to improve clarity :)

**Review by xinhaoz — APPROVED** [review]

**Pull request merged**
