### PR TITLE
kvserver: alter balanceScore result to classify stores into 3 buckets

### PR DESCRIPTION
**Pull request by aayushshah15**
In https://github.com/cockroachdb/cockroach/pull/65379 we changed
`balanceScore()` to classify stores in a cluster into 4 buckets:
underfull, less-than-mean, more-than-mean and overfull. This
allowed for the possibility of thrashing around the mean (i.e. replicas
could ping-pong between stores classified as less-than-mean and
more-than-mean).

This patch moves balanceScore back to its previous incarnation, which
only divided resulting stores into 3 buckets.

Release justification: Fixes regression introduced in a previous patch

Release note: None

### CODE REVIEW

**Comment by aayushshah15** [comment]
I separated this commit out from https://github.com/cockroachdb/cockroach/pull/72296 because it is a dependency of https://github.com/cockroachdb/cockroach/pull/73597

**Comment by aayushshah15** [comment]
This is ready for a look.

**Review by irfansharif — APPROVED** [review]
Drive-by rubber stamp, was curious.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73614#-:-Mr0S2HxEE2vQ7gTrwGM:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15)

**Comment by aayushshah15** [comment]
TFTR!
bors r+

**Pull request merged**
