### PR TITLE
distsql: Add join type to EXPLAIN (DISTSQL) output

### PR DESCRIPTION
**Pull request by abhimadan**
Release note: None

### CODE REVIEW

**Comment by arjunravinarayan** [comment]
*[pkg/sql/distsqlrun/flow_diagram.go, line 139 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22279#-L4DKO8Tu4WR8jMtg38d:-L4DKO8U0qD-D-IKjHoF:bjpl2du) ([raw file](https://github.com/cockroachdb/cockroach/blob/0220012fcd9fbfac7f4881b97b0f062b14d65b41/pkg/sql/distsqlrun/flow_diagram.go#L139)):*
> ```Go
> 	name := "HashJoiner"
> 	if isSetOpJoin(joinType(hj.Type)) {
> 		name = "MergeSetOp"
> ```

s/MergeSetOp/HashSetOp

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22279)*

**Comment by abhimadan** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/distsqlrun/flow_diagram.go, line 139 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22279#-L4DKO8Tu4WR8jMtg38d:-L4GsRzPljCY1PPuDMhF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0220012fcd9fbfac7f4881b97b0f062b14d65b41/pkg/sql/distsqlrun/flow_diagram.go#L139)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

s/MergeSetOp/HashSetOp
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22279)*

**Comment by jordanlewis** [comment]
:lgtm: This is sweet! EXPLAIN(DISTSQL) output is a lot more useful now.

---

Reviewed 6 of 7 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22279#-:-L4GxzIKK5-MwrmEL2lq:baddb1a)*

**Comment by RaduBerinde** [comment]
We could have inner as the default and omit `INNER` to keep diagrams simpler (we would know it's inner if it doesn't say anything else).

PS I hope you know about and used `--rewrite-results-in-testfiles` :)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22279#-:-L4GzAFXGKhV66kzQXDx:bqnfsfd)*

**Comment by arjunravinarayan** [comment]
I don't want to delay merging this PR as its a good improvement on the existing plans, but a line that just says "INNER" could be improved. ("Type: Inner Join") would be more descriptive.

:lgtm: 

---

Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22279#-:-L4H7Cgjez4x5e_Y3HPO:b-123xmr)*

**Comment by abhimadan** [comment]
Omitted INNER from the output, and improved the join type detail line a bit. I actually learned about that logic test flag  when making this PR, and it was very helpful :)

---

Review status: 1 of 5 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22279#-:-L4HGBUVorFyUPk2Ty8N:bi71stw)*

**Comment by arjunravinarayan** [comment]
:lgtm: I like it!

---

Reviewed 1 of 7 files at r3.
Review status: 2 of 5 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22279#-:-L4HGoAWXqeVJj-bsb0g:b779t6b)*

**Pull request merged**
