### PR TITLE
Update STYLE.md to clarify tab sizes for column width

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8412)

### CODE REVIEW

**Comment by tamird** [comment]
LGTM

**Comment by dt** [comment]
Uh, I thought we assumed 2? our `.editorconfig` says 2.

**Comment by tamird** [comment]
What editors even respect .editorconfig? Mine doesn't.

**Comment by bdarnell** [comment]
Yeah, we use 2-space indents in our non-go code and assume that tabs are 2 spaces wide in go code. Tabs should be used for leading indentation and spaces for alignment within a line (I think this is what gofmt uses), in which case the actual tab width doesn't matter in most cases. 

Github respects `.editorconfig`. Plugins are available for most editors at editorconfig.org. I don't have an editorconfig plugin installed but it's still a useful record of our stylistic choices for the things it covers.

**Comment by tamird** [comment]
Neat, thanks,.

**Pull request merged**
