### PR TITLE
sql: cluster setting for early/late binding in udf body

### PR DESCRIPTION
**Pull request by chengxiong-ruan**
This commit adds a cluster setting to allow users to turn off
early binding of referenced objects in function body at definition
time.

Release note: None

### CODE REVIEW

**Comment by michae2** [comment]
Thank you for doing this!

**Comment by jordanlewis** [comment]
Is it ok/desirable that this is a cluster setting (aka, not permitting decisionmaking on a per session basis)?

**Comment by ajwerner** [comment]
> Is it ok/desirable that this is a cluster setting (aka, not permitting decisionmaking on a per session basis)?

I'll go one further: this needs to be a session variable. 

> Release note: None

This will ultimately need a release note, this is going to be something we want to make sure gets discussed in the docs.

**Review by michae2 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85851)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, and @mgartner)

___
*[`pkg/sql/opt/optbuilder/create_function.go` line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85851#-N93WBd_-9LhrOPndMmF:-N93WBd_-9LhrOPndMmG:b6a1n1o) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4806a5b7bb180aeda1c8aa8f8010c2b148d256b/pkg/sql/opt/optbuilder/create_function.go#L44)):*
> ```Go
> 	"set to true to enable early binding of objects referenced in function body, false to disable; default is true",
> 	true,
> ).WithPublic()
> ```

It looks like this only comes into play when the `CREATE FUNCTION` statement is executed (is that correct)? Would it make more sense as a session variable, then? So that we can set it just before executing `CREATE FUNCTION` without affecting other sessions?

**Review by chengxiong-ruan — COMMENTED** [review]
Yes, a session variable sounds more reasonable. I'll change that.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85851#-:-N93ZOG4ExSFjBsdV8bF:bn9ghx1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, and @mgartner)

**Comment by chengxiong-ruan** [comment]
*[`pkg/sql/vars.go` line 2138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85851#-N93mQPrBga4MecdHmS_:-N93mQPrBga4MecdHmSa:b-6awyb3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1633901c4b5ee85e1419b04ed48f7bf72ab7b20b/pkg/sql/vars.go#L2138)):*
> ```Go
> 			return formatBoolAsPostgresSetting(evalCtx.SessionData().UserDefinedFunctionEarlyBinding), nil
> 		},
> 		GlobalDefault: globalTrue,
> ```

do we want a cluster setting as well so user can change the global default? ( I prefer not to heh..)

**Comment by ajwerner** [comment]
I don't think we need such a setting now that we have database level session defaults

**Review by ajwerner — COMMENTED** [review]
It feels to me like we should indicate somewhere on the descriptor whether or not it's late bound. I have a feeling we'll want to treat the references differently. This feels like one of those changes which is going to leave us needing to think hard about things in the future. I can see why we want to do it now, and if folks do reach for it, it will be validating, but it leaves me a little bit worried.

**Comment by chengxiong-ruan** [comment]
> It feels to me like we should indicate somewhere on the descriptor whether or not it's late bound. I have a feeling we'll want to treat the references differently. This feels like one of those changes which is going to leave us needing to think hard about things in the future. I can see why we want to do it now, and if folks do reach for it, it will be validating, but it leaves me a little bit worried.

Yeah, adding an a flag in the descriptor is a good idea. Thanks for the input. We'd also need to add validation for the descriptor as well to make sure references are correct if it's late bound (nothing is tracked). I'll address later after other priorities. For the `leave us needing to think hard about things in the future` part, that worth a conversation at some time.

(I don't think this is a stability period blocker. Will come back to this after other priorities being addressed)

**Review by mgartner — APPROVED** [review]
Optimizer side LGTM.

> Reviewed 3 of 5 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85851#-:-N9981A1Bgq-PJBWYyV3:bmajmch)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan, @mgartner, and @michae2)

___
*[`pkg/sql/opt/optbuilder/create_function.go` line 49 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85851#-N997Tra3McCgKMm4jcN:-N997Tra3McCgKMm4jcO:b-tmd3ee) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccd26475c81f398ff928d268310d36dd6c06ee4c/pkg/sql/opt/optbuilder/create_function.go#L49)):*
> ```Go
> 	// have late-binding. Note that references of user-defined types, including
> 	// table implicit types, used in function signature will still be tracked when
> 	// early binding is off
> ```

nit: end sentence with a period

Does PG track user-defined types in UDFs when using the non-`sql_body` syntax? If not, shouldn't we match their behavior with this setting?
___
*[`pkg/sql/opt/optbuilder/create_function.go` line 53 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85851#-N997wQT2xE9eUKXM273:-N997wQT2xE9eUKXM274:b-4x4b4s) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccd26475c81f398ff928d268310d36dd6c06ee4c/pkg/sql/opt/optbuilder/create_function.go#L53)):*
> ```Go
> 	b.trackSchemaDeps = b.evalCtx.SessionData().UserDefinedFunctionEarlyBinding
> 	// Make sure datasource names are qualified.
> 	b.qualifyDataSourceNamesInAST = b.evalCtx.SessionData().UserDefinedFunctionEarlyBinding
> ```

A logic test showing the unqualified function body would be nice.

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85851)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan, @mgartner, and @michae2)

___
*[`pkg/sql/opt/optbuilder/create_function.go` line 49 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85851#-N997Tra3McCgKMm4jcN:-N9CEc1k3MZQvAQBANbP:bf2dwo) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccd26475c81f398ff928d268310d36dd6c06ee4c/pkg/sql/opt/optbuilder/create_function.go#L49)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: end sentence with a period

Does PG track user-defined types in UDFs when using the non-`sql_body` syntax? If not, shouldn't we match their behavior with this setting?
</blockquote></details>

Yes, pg tracks user-defined types in UDF signature (argument types, return type) with whatever function body.
___
*[`pkg/sql/opt/optbuilder/create_function.go` line 53 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85851#-N997wQT2xE9eUKXM273:-N9CErWo7JfcThXdx2-o:b-49bs7b) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccd26475c81f398ff928d268310d36dd6c06ee4c/pkg/sql/opt/optbuilder/create_function.go#L53)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

A logic test showing the unqualified function body would be nice.
</blockquote></details>

thanks, will add.

**Comment by chengxiong-ruan** [comment]
*[`pkg/sql/opt/optbuilder/create_function.go` line 49 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85851#-N997Tra3McCgKMm4jcN:-N9CF5zd569AZOnNBPPn:b-axkmsg) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccd26475c81f398ff928d268310d36dd6c06ee4c/pkg/sql/opt/optbuilder/create_function.go#L49)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

Yes, pg tracks user-defined types in UDF signature (argument types, return type) with whatever function body.
</blockquote></details>

an example:
```sql
postgres=# CREATE TYPE mood AS ENUM ('sad', 'ok', 'happy');
CREATE TYPE

postgres=# create function f(mood) returns int language sql as $$ select 1 $$;
CREATE FUNCTION

postgres=# drop type mood;
ERROR:  cannot drop type mood because other objects depend on it
DETAIL:  function f(mood) depends on type mood
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

```

**Review by michae2 — COMMENTED** [review]
One reason to include late / early binding in the descriptor: so that it's possible to backup and restore late-binding UDFs.

Are we still thinking of doing this for 22.2.1?

> Reviewed 3 of 5 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85851#-:-NDAdtjF1Qc24sG9qHhh:b12wxhg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan and @mgartner)

___
*[`-- commits` line 9 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85851#-NDAIQueDor5_z1PwQNq):*
nit: "session variable" instead of "session data"
___
*[`-- commits` line 12 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85851#-NDAIfp4By-60T_D6Yrb):*
nit: "function bodies" instead of "function body"
___
*[`-- commits` line 13 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85851#-NDAWvj72v8z5oaAU-MP):*
nit: "accidental" instead of "accident"
___
*[`pkg/sql/vars.go` line 2138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/85851#-N93mQPrBga4MecdHmS_:-NDAdjV22X0Rhta2Tizy:bt5b4e0) ([raw file](https://github.com/cockroachdb/cockroach/blob/1633901c4b5ee85e1419b04ed48f7bf72ab7b20b/pkg/sql/vars.go#L2138)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

do we want a cluster setting as well so user can change the global default? ( I prefer not to heh..)
</blockquote></details>

Cluster settings are deprecated now anyway, so definitely not. :slightly_smiling_face:
___
*[`pkg/sql/sessiondatapb/local_only_session_data.proto` line 280 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/85851#-NDAXMomEp9MNqhk_jgu:-NDAXMomEp9MNqhk_jgv:b-781ny7) ([raw file](https://github.com/cockroachdb/cockroach/blob/ccd26475c81f398ff928d268310d36dd6c06ee4c/pkg/sql/sessiondatapb/local_only_session_data.proto#L280)):*
> ```protobuf
>   // like dropping a table used by the function. Turning this switch off means
>   // we will have late binding with which references are not tracked. In that
>   // scene, schema changes to referenced objects could potentially break the
> ```

nit: Did you mean "scenario" instead of "scene"?

**Comment by chengxiong-ruan** [comment]
@michae2 thanks for the review!

We still hesitate to do it. The reason is that turning this flag on and off and create functions with mixed behaviors might cause a lot of trouble to us in the future. More specifically, we'd have to think hard on reference tracking for two different paths, as well as validation, and not to mention the back references as well. There could other unknown problems hard to reason about without real use case (maybe index corruption and constraint violation we chatted about earlier). It'd be very error prone. It might also confuse users as they forgot what flags they set when creating a UDF as well. Adding this flag (and metadata tracking it) is likely trivial as it showed, but I think we need a good reason to compromise. And I also doubt migrating clients wants to import broken UDFs.

I'll close this PR for now. We can always add this later as more users ramp up with UDFs, at that moment hope we can make easier decision with real use cases. For 22.2, given the limitation of UDF, I doubt this flag would show much value either. One comprise we thought about is to add this flag but not document it anywhere, and only tell client when they need it. But I still want to be cautious with the reason above. Thanks again for bringing up this topic, it's super valuable to discuss on this and think through it.

**Comment by michae2** [comment]
@chengxiong-ruan makes sense. If it's alright with you, I'm going to open an issue about late vs early binding, with some of the examples from the RFC discussion, so that we have something to point people to if they run into this.

**Comment by chengxiong-ruan** [comment]
> @chengxiong-ruan makes sense. If it's alright with you, I'm going to open an issue about late vs early binding, with some of the examples from the RFC discussion, so that we have something to point people to if they run into this.

@michae2 yes, please. That'd be super helpful. Thanks!

**Comment by michae2** [comment]
Ok, filed #89109.

**Pull request closed without merging**
