### PR TITLE
rfc update: Finalize the cluster upgrade process automatically.

### PR DESCRIPTION
**Pull request by ghost**
This commit address some issues encountered while developing:

1. In the daemon that does the upgrade, we are checking by pulling node
liveness status from liveness servers instead of checking gossip_nodes.

2. There are significant changes in testing and I'm proposing 2 ways to test
cluster setting `cluster.preserve_downgrade_option`.

3. UI: removed some work after discussion with UI team.

Issue: #23912.

Release note: None

### CODE REVIEW

**Review by benesch — APPROVED** [review]
Nice, LGTM!

**Comment by BramGruneir** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[docs/RFCS/20180411_finalize_cluster_upgrade_automatically.md, line 2 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/24935#-LCZ75B08V4_5HGJ-7Pj:-LCZ75B08V4_5HGJ-7Pk:b-33qrai) ([raw file](https://github.com/cockroachdb/cockroach/blob/304ef72f39a2935dd365592533d67bed0c9a5c91/docs/RFCS/20180411_finalize_cluster_upgrade_automatically.md#L2)):*
> ```Markdown
> - Feature Name: Finalize cluster upgrades automatically
> - Status: completed
> ```

Is the UI portion complete?  If not, than this isn't complete yet.

---

*[docs/RFCS/20180411_finalize_cluster_upgrade_automatically.md, line 54 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/24935#-LCZ64PA2_KoFts3RmJD:-LCZ64PA2_KoFts3RmJE:buva438) ([raw file](https://github.com/cockroachdb/cockroach/blob/304ef72f39a2935dd365592533d67bed0c9a5c91/docs/RFCS/20180411_finalize_cluster_upgrade_automatically.md#L54)):*
> ```Markdown
> ```
> 
> Finally, trying to set cluster setting version when operators have already set
> ```

trying to set **the** cluster setting 

---

*[docs/RFCS/20180411_finalize_cluster_upgrade_automatically.md, line 77 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/24935#-LCZ6fN04v3NlkC7s0XU:-LCZ6fN04v3NlkC7s0XV:bscs1ec) ([raw file](https://github.com/cockroachdb/cockroach/blob/304ef72f39a2935dd365592533d67bed0c9a5c91/docs/RFCS/20180411_finalize_cluster_upgrade_automatically.md#L77)):*
> ```Markdown
>   - Exit.
> - **ELSE IF**:
>   - Did not preserve downgrade options for current cluster version.
> ```

The preserve downgrade option for the current cluster version is not set.

---

*[docs/RFCS/20180411_finalize_cluster_upgrade_automatically.md, line 85 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/24935#-LCZ6XpfA4kz_bnSC7ZW:-LCZ6XpfA4kz_bnSC7ZX:b-o6lhbs) ([raw file](https://github.com/cockroachdb/cockroach/blob/304ef72f39a2935dd365592533d67bed0c9a5c91/docs/RFCS/20180411_finalize_cluster_upgrade_automatically.md#L85)):*
> ```Markdown
>   non-decommissioned nodes are alive (no missing nodes).
> - **THEN**:
>   - Run following transaction until success:
> ```

Run **the** following

---

*[docs/RFCS/20180411_finalize_cluster_upgrade_automatically.md, line 101 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/24935#-LCZ7DTOEuJT0xLpXe3o:-LCZ7DTQBVHhcwQZ76-r:b-wl9eto) ([raw file](https://github.com/cockroachdb/cockroach/blob/304ef72f39a2935dd365592533d67bed0c9a5c91/docs/RFCS/20180411_finalize_cluster_upgrade_automatically.md#L101)):*
> ```Markdown
> 
> 2. Perform a rolling upgrade for node `1` - `N-1`. At every iteration, we check
> the cluster version is not upgraded.
> ```

At every iteration, check **that** the cluster version ...

---

*[docs/RFCS/20180411_finalize_cluster_upgrade_automatically.md, line 107 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/24935#-LCZ7Hzr10T7F5aPOmV3:-LCZ7Hzr10T7F5aPOmV4:b-jph43z) ([raw file](https://github.com/cockroachdb/cockroach/blob/304ef72f39a2935dd365592533d67bed0c9a5c91/docs/RFCS/20180411_finalize_cluster_upgrade_automatically.md#L107)):*
> ```Markdown
> 4. Perform an upgrade for node `N`, which was running `v2.0.0`.
> 
> 5. Check the cluster version is not upgraded.
> ```

Check **that** the cluster 

---

*[docs/RFCS/20180411_finalize_cluster_upgrade_automatically.md, line 116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/24935#-LCZ7RxbAfaRMZVBRNo_:-LCZ7RxbAfaRMZVBRNoa:b7cr3gj) ([raw file](https://github.com/cockroachdb/cockroach/blob/304ef72f39a2935dd365592533d67bed0c9a5c91/docs/RFCS/20180411_finalize_cluster_upgrade_automatically.md#L116)):*
> ```Markdown
> 8. Set `cluster.preserve_downgrade_option` to be `2.0`.
> 
> 9. Restart node `N-1`, which is previously force stopped.
> ```

... which **was** previously ...

---

*[docs/RFCS/20180411_finalize_cluster_upgrade_automatically.md, line 118 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/24935#-LCZ7UQx6-yugxRAvxBW:-LCZ7UQx6-yugxRAvxBX:buvm40t) ([raw file](https://github.com/cockroachdb/cockroach/blob/304ef72f39a2935dd365592533d67bed0c9a5c91/docs/RFCS/20180411_finalize_cluster_upgrade_automatically.md#L118)):*
> ```Markdown
> 9. Restart node `N-1`, which is previously force stopped.
> 
> 10. Check the cluster version is not upgraded.
> ```

Check **that** the cluster ...

---

*[docs/RFCS/20180411_finalize_cluster_upgrade_automatically.md, line 120 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/24935#-LCZ7XQp1AzVeHKb3MxF:-LCZ7XQp1AzVeHKb3MxG:bw96k11) ([raw file](https://github.com/cockroachdb/cockroach/blob/304ef72f39a2935dd365592533d67bed0c9a5c91/docs/RFCS/20180411_finalize_cluster_upgrade_automatically.md#L120)):*
> ```Markdown
> 10. Check the cluster version is not upgraded.
> 
> 11. Check cannot set cluster setting version until `cluster.preserve_downgrade_option`
> ```

... cannot set **the** cluster setting ...

---

*[docs/RFCS/20180411_finalize_cluster_upgrade_automatically.md, line 125 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/24935#-LCZ7aR247cbMK63RuWJ:-LCZ7aR247cbMK63RuWK:buvm40t) ([raw file](https://github.com/cockroachdb/cockroach/blob/304ef72f39a2935dd365592533d67bed0c9a5c91/docs/RFCS/20180411_finalize_cluster_upgrade_automatically.md#L125)):*
> ```Markdown
> 12. Reset `cluster.preserve_downgrade_option`.
> 
> 13. Check the cluster version is upgraded to new version.
> ```

Check **that** the cluster ...

---

*[docs/RFCS/20180411_finalize_cluster_upgrade_automatically.md, line 127 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/24935#-LCZ7gC2D2McqW9sjWni:-LCZ7gC2D2McqW9sjWnj:b-brd5yw) ([raw file](https://github.com/cockroachdb/cockroach/blob/304ef72f39a2935dd365592533d67bed0c9a5c91/docs/RFCS/20180411_finalize_cluster_upgrade_automatically.md#L127)):*
> ```Markdown
> 13. Check the cluster version is upgraded to new version.
> 
> 14. Check `cluster.preserve_downgrade_option` has been reset.
> ```

Check **that** `cluster.preserve_downgrade_option`...

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24935)*

**Comment by windchan7** [comment]
@piyush-singh Hey Piyush, now that auto upgrade code is merged. Could you please ping here once the UI part for auto upgrade is done? Thanks a lot.

**Comment by windchan7** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[docs/RFCS/20180411_finalize_cluster_upgrade_automatically.md, line 107 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/24935#-LCZ7Hzr10T7F5aPOmV3:-LC_MEMI8ApprUtprhW-:b89cer7) ([raw file](https://github.com/cockroachdb/cockroach/blob/304ef72f39a2935dd365592533d67bed0c9a5c91/docs/RFCS/20180411_finalize_cluster_upgrade_automatically.md#L107)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

nope
</blockquote></details>

Can't believe I always miss style issues. Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24935)*

**Comment by benesch** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24935#-:-LChx2u98LzAmMwgE72q:bnfp4nl)*

**Pull request merged**
