### PR TITLE
cherrypick-1.1: engine: Make temp directory cleanup resilient to rename errors

### LINKED ISSUE #18994: storage: cleaning up old temporary directory doesn't work on OverlayFS
The logic in `engine.cleanupTempStorageDirs` tries to avoid blocking during the startup path by renaming the old temporary storage directory from its normal name to a `TO-DELETE-` prefixed name so that a new temporary directory can be created in its place. The `TO-DELETE-` directory then gets deleted in the background to avoid blocking anything.

Unfortunately, if the old temporary storage directory was created in a lower OverlayFS layer, the rename operation will always fail (https://github.com/moby/moby/issues/25409). This breaks use cases such as those that initialize a database in a certain way as part of a Docker build process so that the resulting image can be used in reproducible tests.

It wouldn't be a huge deal if overlay2 wasn't the default storage driver for Docker on Mac (and possibly other environments like Windows, but I didn't check).

cc @arjunravinarayan - I'm going to just fall back to removing the file if `os.Rename` fails. Is there anything wrong with that approach?

### PR DESCRIPTION
**Pull request by a-robinson**
Fixes #18994 

@cockroachdb/release - very low risk since it only runs in a code path when we'd previously just `log.Fatal`, and fixes a bug that's blocking a user's efforts to run tests against us, but I'll leave the decision to @bdarnell

### CODE REVIEW

**Review by bdarnell — APPROVED** [review]
I think we should hold this until 1.1.1.

**Review by a-robinson — COMMENTED** [review]
👍

**Comment by a-robinson** [comment]
On second thought, I think this does make sense to include in 1.1.0 unless that door is really shut quite hard. It's a system crash that's directly affecting a customer that can't be worked around without asking everyone involved to change their docker storage driver. Given the minimal risk involved, I'd lean toward not making them wait an extra week or two for a fix.

**Comment by bdarnell** [comment]
I guess since we already bumped the rc1 commit we can throw this in too, although let me say that what this customer is doing seems a bit nuts to me and I'm not sure we want to support it (it results in a lot of clusters out there with the same ID).

**Comment by a-robinson** [comment]
Is it actually nuts, though? Wanting to be able to run tests against a database that always starts from the exact same state doesn't seem that crazy to me. Consistency of environment across different machines and instantiations is one of docker's big selling points.

**Comment by bdarnell** [comment]
My concern is that we don't generally support doing things by copying rocksdb files around. If you attempt to back up your database by making filesystem-level backups of the rocksdb state, you'll break things in subtle ways. A cleaner (but admittedly slower) way to do this would be to make a backup of a database in the desired state and then restore it on each use. 

(and if someone tries to extrapolate from this and start up a multi-node cluster by baking things into a docker image, it won't work)

**Comment by richardwu** [comment]
Just a heads up, the temp directory cleanup will be cleaned up once [this PR](https://github.com/cockroachdb/cockroach/pull/18544) is merged and comments addressed (which is targeted for 1.1.x).

**Pull request merged**
