### PR TITLE
sql/parser: Support ARRAY[] constructor syntax

### PR DESCRIPTION
**Pull request by nvb**
This should make adding new ARRAY functionality a lot easier.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10585)

### CODE REVIEW

**Comment by knz** [comment]
:lgtm: with nits

---

Reviewed 8 of 8 files at r1.
Review status: 7 of 10 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/parser/type_check.go, line 574 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10585#-KWDNaVFlhLwQhHEH21Z:-KWDNaVGSztPvTdjanB9:b2jgh7v) ([raw file](https://github.com/cockroachdb/cockroach/blob/013f343c0eb6d155a2c7405f7bc6c1cf22914ba7/pkg/sql/parser/type_check.go#L574)):*
> ```Go
> 	if len(expr.Exprs) == 0 {
> 		if desiredParam == NoTypePreference {
> 			return nil, errors.Errorf("cannot determine type of empty array")
> ```

1) make this a const error
2) suggest using ":::" to disambiguate in the error message.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10585#-:-KWDNr-MaRWnoAo1ZwSx:bfmeux1)*

**Comment by cuongdo** [comment]
Review status: 7 of 10 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/type_check_test.go, line 123 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10585#-KWDYBqHoZCElkYu5hhX:-KWDYBqICU5_e9IlUQDI:b-mgczmf) ([raw file](https://github.com/cockroachdb/cockroach/blob/013f343c0eb6d155a2c7405f7bc6c1cf22914ba7/pkg/sql/parser/type_check_test.go#L123)):*
> ```Go
> 		{`COALESCE(1, 2, 3, 4, '5')`, `incompatible COALESCE expressions: expected 1 to be of type string, found type int`},
> 		{`ARRAY[]`, `cannot determine type of empty array`},
> 		{`ARRAY[1, 2, 3]`, `unhandled parameterized array type parser.tInt`},
> ```

how about throwing in some tests to ensure we have reasonable `NULL` handling for this constructor?

---

*[pkg/sql/testdata/array, line 13 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10585#-KWDYSOnlUNUWFWz6WGH:-KWDYSOnlUNUWFWz6WGI:b-5bm4p7) ([raw file](https://github.com/cockroachdb/cockroach/blob/013f343c0eb6d155a2c7405f7bc6c1cf22914ba7/pkg/sql/testdata/array#L13)):*
> ```
> SELECT ARRAY['a', 'b', 'c']
> ----
> {'a','b','c'}
> ```

maybe also throw in some tests with `NULL`s here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10585)*

**Comment by nvanbenschoten** [comment]
Review status: 4 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/parser/type_check.go, line 574 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10585#-KWDNaVFlhLwQhHEH21Z:-KWNJXwClVpd83LrWCz8:b-a00was) ([raw file](https://github.com/cockroachdb/cockroach/blob/013f343c0eb6d155a2c7405f7bc6c1cf22914ba7/pkg/sql/parser/type_check.go#L574)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> 1) make this a const error
> 2) suggest using ":::" to disambiguate in the error message.
</details>
Done. Postgres returns this suggestion in the error's `HINT` field (see https://www.postgresql.org/docs/current/static/protocol-error-fields.html). It might be worth it to eventually make our error messages more structured.

---

*[pkg/sql/parser/type_check_test.go, line 123 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10585#-KWDYBqHoZCElkYu5hhX:-KWNKy6nFCF6c7j6pggl:b-zafwr5) ([raw file](https://github.com/cockroachdb/cockroach/blob/013f343c0eb6d155a2c7405f7bc6c1cf22914ba7/pkg/sql/parser/type_check_test.go#L123)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary>
> how about throwing in some tests to ensure we have reasonable `NULL` handling for this constructor?
</details>
Done. Although it doesn't really show much right now because we're limiting to `tArray{TypeString}`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10585)*

**Comment by knz** [comment]
Reviewed 3 of 3 files at r2.
Review status: 7 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/parser/type_check.go, line 574 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10585#-KWDNaVFlhLwQhHEH21Z:-KWNZC_8BGuCWYtW788S:b6vgdyk) ([raw file](https://github.com/cockroachdb/cockroach/blob/013f343c0eb6d155a2c7405f7bc6c1cf22914ba7/pkg/sql/parser/type_check.go#L574)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Done. Postgres returns this suggestion in the error's `HINT` field (see https://www.postgresql.org/docs/current/static/protocol-error-fields.html). It might be worth it to eventually make our error messages more structured.
</details>
Agreed. Do we have an issue filed for this already?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10585)*

**Comment by nvanbenschoten** [comment]
Review status: 7 of 10 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/type_check.go, line 574 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10585#-KWDNaVFlhLwQhHEH21Z:-KWWHQInoVYfcmMG-0h6:bufcycm) ([raw file](https://github.com/cockroachdb/cockroach/blob/013f343c0eb6d155a2c7405f7bc6c1cf22914ba7/pkg/sql/parser/type_check.go#L574)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Agreed. Do we have an issue filed for this already?
</details>
We do now #10668.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10585)*

**Pull request merged**
