### PR TITLE
build: improve source archives

### PR DESCRIPTION
**Pull request by benesch**
Teach source archives to install into `/usr/local/bin/cockroach` and (finally) add a basic test to catch future breakage.

@bdarnell: I feel like you might have thoughts on installing into `/usr/local/bin` instead of `$GOPATH/bin`.

### CODE REVIEW

**Comment by tamird** [comment]
Can we do this without adding another docker image? My guess is that you're using docker to avoid polluting the host, but can't you override the install location instead?

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 1 of 3 files at r5.
Review status: 3 of 5 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15622#-:-KjA7RpNP-lQK88xYIB0:bhbnm4x)*

**Comment by benesch** [comment]
I've got to use Docker to make this run on TC, no? (PS. [This works!](https://teamcity.cockroachdb.com/viewLog.html?buildId=240776&buildTypeId=Cockroach_UnitTests_VerifyArchive&tab=buildLog))

Plus, I want to test that the source tarball builds in an environment with zero CockroachDB modifications. The builder Docker image hardcodes `GOPATH=/go` into its env and mounts cockroachdb/cockroach into `$GOPATH/src/github.com`, so it wouldn't have caught the issue I just fixed where `go list` didn't see the adjusted `GOPATH` in the Makefile.

---

Review status: 3 of 5 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15622#-:-KjA8zhwIjC_erYtVWJA:b-oa70vk)*

**Comment by tamird** [comment]
Ah, I see. Okay, can you move the "meat" out into a shell script? You could
then mount cwd into the golang container and run the stuff in there. Minor,
but saves you a random dockerfile.

**Comment by tamird** [comment]
Took a closer look. I don't think we need the golang image after all - we can just set GOPATH to whatever we'd like (as you do in your dockerfile) in a shell script that we run in our normal builder image. I understand your point about having zero crdb modifications to the environment, but you're already manually tweaking GOPATH in your Dockerfile, so is it really worth the extra image?

In particular, consider that we sometimes (often?) have issues with disk space on TC machines, so reducing the expected number of docker images sitting around is a nice bonus.

**Comment by bdarnell** [comment]
LGTM. Two weeks ago I'd be in favor of this change, but now I'm more hesitant. I think it's still a good idea on balance to get this in before 1.0, but it's late to be making this change (if it doesn't make it in before rc2, we shouldn't do it for 1.0-final. The makefile change can go in without a test if necessary). 

For the test, I think if we're going to test this it's probably worthwhile to test with a minimal base image instead of the builder - either start from `golang:1.8.` or from `ubuntu:xenial-20170214` (the current base of the builder image to save space on the TC workers)

---

Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[build/archive/contents/Makefile, line 1 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/15622#-KjB-l3ODdmmWsPptXYe:-KjB-l3PbOWSyUkkRqIL:bmlw0x0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f73045ff9298ab6c7ebb6979fca9f57b9cc5c05b/build/archive/contents/Makefile#L1)):*
> ```Makefile
> PREFIX := /usr/local
> ```

The GNU standard is a lowercase `prefix`: https://www.gnu.org/prep/standards/html_node/Directory-Variables.html#Directory-Variables (although freebsd ports use all-caps). I don't know if there's a standard worth following here (it's most common for prefix to be set through `configure`, which we're not using). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15622#-:-KjB0Uz7RgfeGd_Yu53w:b-nzbw8j)*

**Comment by benesch** [comment]
Ok, factored this out into a shell script. I'm not sure this shakes out to be any cleaner than introducing a new Dockerfile, but I don't care one way or another.

Still using the `golang:1.8.1` image, since using `ubuntu:xenial-20170214` would require manually installing Go into the image. If the TC agents are running out of disk space, I think we should address the root cause.

@bdarnell, looks like this may be ready to go first thing tomorrow. If not, happy to hold off until 1.1 and/or excise the test for now.

---

Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[build/archive/contents/Makefile, line 1 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/15622#-KjB-l3ODdmmWsPptXYe:-KjBbB80cQRrkp1qbvQQ:b9x75bn) ([raw file](https://github.com/cockroachdb/cockroach/blob/f73045ff9298ab6c7ebb6979fca9f57b9cc5c05b/build/archive/contents/Makefile#L1)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

The GNU standard is a lowercase `prefix`: https://www.gnu.org/prep/standards/html_node/Directory-Variables.html#Directory-Variables (although freebsd ports use all-caps). I don't know if there's a standard worth following here (it's most common for prefix to be set through `configure`, which we're not using). 
</blockquote></details>

`prefix` and `bindir` work for me!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15622#-:-KjBc0xv6OdNGf3Mb2we:bev8jgg)*

**Comment by tamird** [comment]
:lgtm:

>  If the TC agents are running out of disk space, I think we should address the root cause.

I'm not sure what you mean. What do you suggest is the root cause? Certain changes naturally cause more space to be consumed on the TC agent - for example, moving the docker $GOPATH namespace caused agents that straddled that change to have two copies of that cache. Updating the builder image causes agents that straddle the change to have two copies of that image (same goes for the postgres-test image). We used to also store (potentially several versions of) the xgo docker image. I don't think there's a root cause, it's just death by a thousand paper cuts, so we should be cognizant when we introduce non-transient increases in disk use.

Manually downloading Go into the image doesn't seem so daunting to me, but the savings are only about 300MB, so maybe it's not worth it.

---

Reviewed 4 of 4 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15622#-:-KjDFe-Jaz-nkJ5V2LLF:b-fud22)*

**Comment by benesch** [comment]
Sorry, I meant we could auto-nuke TC agents that run low on disk space—or perhaps just auto-nuking all TC agents that live longer than _n_ days. 

Do you have strong objections if I merge as-is, @tamird? Would love to get this into rc.2 and we can always modify this to use the same base image as the builder if disk usage does become a problem.

**Comment by tamird** [comment]
No objection at all (hence the LGTM in my last comment).

**Comment by benesch** [comment]
👍 just double checking!

**Pull request merged**
