### PR TITLE
sql: age returns normalized intervals

### LINKED ISSUE #50856: builtins: age returns unnormalized intervals
image

----

otan edit:

`select age('2017-12-10'::timestamptz, '2017-12-01'::timestamptz)` returns 216 hours instead of 9 days. The age function should follow what Postgres does in normalizing intervals here:

https://github.com/postgres/postgres/blob/324435eb14e4f41cd430f96c9b13ad9b160e45e4/src/backend/utils/adt/timestamp.c#L3696-L3791

### PR DESCRIPTION
**Pull request by ekalinin**
Release note (bug fix): The age function previous did not normalize the duration for large day or H:M:S values in the same way PostgreSQL does. This is now fixed.

Closes #50856

### CODE REVIEW

**Review by otan — COMMENTED** [review]
Looking good!

To get this sent through, please ensure your commit message has a release note (and correct typo with normalized, something like the following should suffice:

```
sql: age returns normalized intervals

Release note (bug fix): The age function previous did not normalize the duration for large day or H:M:S values in the same way PostgreSQL does. This is now fixed.
```
)

**Comment by ekalinin** [comment]
> Looking good!
> 

Thanks!

> To get this sent through, please ensure your commit message has a release note (and correct typo with normalized, something like the following should suffice:
> 
> ```
> sql: age returns normalized intervals
> 
> Release note (bug fix): The age function previous did not normalize the duration for large day or H:M:S values in the same way PostgreSQL does. This is now fixed.
> ```
> 
> )

Great, done!

**Comment by otan** [comment]
> Great, done!

This should be your commit message as well as the PR. The PR can have "Closes <task num>" in it as well (optional on the commit message).

You will need to amend the commit message (git commit --amend) and repush (git push --force) after doing so.

We need this because our release note scraper doesn't read PR descriptions (only commit messages).

Also, you'll need to fix the broken optimizer test -- ` make testoptlogic FILES='fold_constants' TESTFLAGS='-rewrite'` should do it!

**Comment by ekalinin** [comment]
> This should be your commit message as well as the PR description. 

Oh, got it. Fixed commit message. Thanks.

> The PR description can have `Closes <task num>` in it as well so it closes the issue afterwards (optional on the commit message).

Fixed.

> You will need to amend the commit message (git commit --amend) and repush (git push --force) after doing so.

Done.

> We need this because our release note scraper doesn't read PR descriptions (only commit messages).

Understood. Thanks.

**Comment by otan** [comment]
Thanks for those updates!

> Also, you'll need to fix the broken optimizer test -- make testoptlogic FILES='fold_constants' TESTFLAGS='-rewrite' should do it!

What about this one?

See failure here: https://teamcity.cockroachdb.com/viewLog.html?buildId=2070031&buildTypeId=Cockroach_UnitTests.

**Comment by ekalinin** [comment]
> Also, you'll need to fix the broken optimizer test -- make testoptlogic FILES='fold_constants' TESTFLAGS='-rewrite' should do it!

```sh
➜ git status                                        
On branch age-returns-normalized-interval
nothing to commit, working tree clean

➜ make testoptlogic FILES='fold_constants' TESTFLAGS='-rewrite'
Running make with -j12
GOPATH set to ~/projects/go
mkdir -p lib
rm -f lib/lib{geos,geos_c}.so
cp -L ~/projects/go/native/x86_64-linux-gnu/geos/lib/lib{geos,geos_c}.so lib
go test -c ./pkg/sql/opt/exec/execbuilder
bin/prereqs -bin-name=logictestopt -test ./pkg/sql/opt/exec/execbuilder > bin/logictestopt.d.tmp
mv -f bin/logictestopt.d.tmp bin/logictestopt.d
GOFLAGS= go test   -mod=vendor -tags ' gss make x86_64_linux_gnu' -ldflags '-X github.com/cockroachdb/cockroach/pkg/build.typ=development -extldflags ""' -c -o bin/logictestopt ./pkg/sql/opt/exec/execbuilder
cd ./pkg/sql/opt/exec/execbuilder && logictestopt -test.run "TestExecBuild//^fold_constants$/" -test.timeout 30m -rewrite
I200707 14:51:01.539180 1 rand.go:85  Random seed: -5149667470228893128
testing: warning: no tests to run
PASS

➜ git status  
On branch age-returns-normalized-interval
nothing to commit, working tree clean
```

What i'm doing wrong?

**Comment by otan** [comment]
ah my bad, try: `go test ./pkg/sql/opt/norm -run 'TestNormRules'` (it should fail), and if so `go test ./pkg/sql/opt/norm -run 'TestNormRules' -rewrite`

**Comment by ekalinin** [comment]
> ah my bad, try: `go test ./pkg/sql/opt/norm -run 'TestNormRules'` (it should fail), and if so `go test ./pkg/sql/opt/norm -run 'TestNormRules' -rewrite`

Thanks! Fixed.

**Review by otan — APPROVED** [review]
Thanks!

**Comment by intech** [comment]
@ekalinin Eugene, please, check the changes. The problem is now actual in versions 20.1.4-20.1.7

**Comment by yuzefovich** [comment]
@intech this change hasn't been backported to 20.1 branch, so all 20.1.x releases have this problem, but it won't be on 20.2 release (coming out within next several weeks).

It looks like a safe backport though, @otan wdyt?

**Comment by intech** [comment]
@yuzefovich thank you for the prompt answer. Hopefully a backport will be added for such an important feature.
In the future, I ask you to indicate in the documentation next to these functions about known problems / limitations, they break large financial systems. :)

**Pull request merged**
