### PR TITLE
builtins: add st_asgeojson for recordsets

### PR DESCRIPTION
**Pull request by otan**
Release note (sql change): Add ST_AsGeoJSON for recordsets, putting row
contents into the properties field of a GeoJSON object.

### CODE REVIEW

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52715#-:-MEhTKLJ0KO13UwygZmY:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/logictest/testdata/logic_test/geospatial, line 426 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52715#-MEhQBV9AZ4hVfVC7_dV:-MEhQBVD3xffo4U_ypsn:b-dy3yct) ([raw file](https://github.com/cockroachdb/cockroach/blob/e93c568731ade9bb6f5cee3ac43c2e16d649cc78/pkg/sql/logictest/testdata/logic_test/geospatial#L426)):*
> ```
> CREATE TABLE parse_test_geojson AS
>   SELECT
>     row_number() OVER (ORDER BY id) as id,
> ```

I didn't quite understand how this table is different from `parse_test` -- isn't it doing a one-to-one mapping of rows and generating an id using the ordering of ids in `parse_test`?
___
*[pkg/sql/logictest/testdata/logic_test/geospatial, line 433 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52715#-MEhRIXb5YQgG7zlCw6w:-MEhRIXb5YQgG7zlCw6x:b-mykfah) ([raw file](https://github.com/cockroachdb/cockroach/blob/e93c568731ade9bb6f5cee3ac43c2e16d649cc78/pkg/sql/logictest/testdata/logic_test/geospatial#L433)):*
> ```
> query TTT
> SELECT
>   ST_AsGeoJSON(parse_test_geojson.*),
> ```

this one without the `geomcolumnname` parameter picks the "geom" column. If there was no column named "geom", what would it do?
___
*[pkg/sql/logictest/testdata/logic_test/geospatial, line 462 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52715#-MEhBo2w-RvCfAvZ7lFQ:-MEhBo2w-RvCfAvZ7lFR:b-uv3gur) ([raw file](https://github.com/cockroachdb/cockroach/blob/e93c568731ade9bb6f5cee3ac43c2e16d649cc78/pkg/sql/logictest/testdata/logic_test/geospatial#L462)):*
> ```
>    },
>    "properties": {
>      "geom": {
> ```

Should `geom` be appearing in `properties` given that it has already been incorporated into `geometry`? The examples at https://postgis.net/docs/ST_AsGeoJSON.html suggest not.
Hmm, is this because we've selected `geog` so all the other columns are in properties, which includes `geom`?
___
*[pkg/sql/sem/builtins/geo_builtins.go, line 4235 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52715#-MEhSW8aCGIcDsmwCt2O:-MEhSW8aCGIcDsmwCt2P:b-lhx3ch) ([raw file](https://github.com/cockroachdb/cockroach/blob/e93c568731ade9bb6f5cee3ac43c2e16d649cc78/pkg/sql/sem/builtins/geo_builtins.go#L4235)):*
> ```Go
> 		}
> 		if label == "" {
> 			label = fmt.Sprintf("f%d", i+1)
> ```

where is this default labeling specified (from a user's perspective)?
___
*[pkg/sql/sem/builtins/geo_builtins.go, line 4260 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52715#-MEhSsY_9PPf1_IGkkSW:-MEhSsYa1-CQUK0PW2MS:b-9b3xaw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e93c568731ade9bb6f5cee3ac43c2e16d649cc78/pkg/sql/sem/builtins/geo_builtins.go#L4260)):*
> ```Go
> 				}
> 				continue
> 			}
> ```

So empty `geoColumn` implies we pick the first one we can parse. Is that consistent with PostGIS?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52715)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/sql/logictest/testdata/logic_test/geospatial, line 426 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52715#-MEhQBV9AZ4hVfVC7_dV:-MEhW_9T51Uyr5Z-aJW4:b-44eyob) ([raw file](https://github.com/cockroachdb/cockroach/blob/e93c568731ade9bb6f5cee3ac43c2e16d649cc78/pkg/sql/logictest/testdata/logic_test/geospatial#L426)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I didn't quite understand how this table is different from `parse_test` -- isn't it doing a one-to-one mapping of rows and generating an id using the ordering of ids in `parse_test`?
</blockquote></details>

i'll add a comment - parse test relies on row_id which changes betwen runs. i needed this to be a fixed number to get this to work.
___
*[pkg/sql/logictest/testdata/logic_test/geospatial, line 433 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52715#-MEhRIXb5YQgG7zlCw6w:-MEhWfkU8EFHb0pADEQK:b4rggqm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e93c568731ade9bb6f5cee3ac43c2e16d649cc78/pkg/sql/logictest/testdata/logic_test/geospatial#L433)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this one without the `geomcolumnname` parameter picks the "geom" column. If there was no column named "geom", what would it do?
</blockquote></details>

pretend it's a NULL geometry
___
*[pkg/sql/logictest/testdata/logic_test/geospatial, line 462 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52715#-MEhBo2w-RvCfAvZ7lFQ:-MEhWjqf8d583m3wkhga:b-50wd5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/e93c568731ade9bb6f5cee3ac43c2e16d649cc78/pkg/sql/logictest/testdata/logic_test/geospatial#L462)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Should `geom` be appearing in `properties` given that it has already been incorporated into `geometry`? The examples at https://postgis.net/docs/ST_AsGeoJSON.html suggest not.
Hmm, is this because we've selected `geog` so all the other columns are in properties, which includes `geom`?
</blockquote></details>

yep that's it -- if there's more than one, the rest go in properties.
___
*[pkg/sql/sem/builtins/geo_builtins.go, line 4235 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52715#-MEhSW8aCGIcDsmwCt2O:-MEhZPhP311A2H4mPXnC:b-ione6k) ([raw file](https://github.com/cockroachdb/cockroach/blob/e93c568731ade9bb6f5cee3ac43c2e16d649cc78/pkg/sql/sem/builtins/geo_builtins.go#L4235)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

where is this default labeling specified (from a user's perspective)?
</blockquote></details>

seems to be the default if the tuple isn't labelled in `row_to_json` / for tuple types if there are no labels.
___
*[pkg/sql/sem/builtins/geo_builtins.go, line 4260 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52715#-MEhSsY_9PPf1_IGkkSW:-MEhWrX82O4ZzOuoodSp:bb7s9xe) ([raw file](https://github.com/cockroachdb/cockroach/blob/e93c568731ade9bb6f5cee3ac43c2e16d649cc78/pkg/sql/sem/builtins/geo_builtins.go#L4260)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

So empty `geoColumn` implies we pick the first one we can parse. Is that consistent with PostGIS?
</blockquote></details>

yep!

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52715)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @otan and @sumeerbhola)

___
*[pkg/sql/sem/builtins/geo_builtins.go, line 4235 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52715#-MEhSW8aCGIcDsmwCt2O:-MEhiAY5CHg1WAVZ31_p:bi9tyx7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e93c568731ade9bb6f5cee3ac43c2e16d649cc78/pkg/sql/sem/builtins/geo_builtins.go#L4235)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

seems to be the default if the tuple isn't labelled in `row_to_json` / for tuple types if there are no labels.
</blockquote></details>

Can you add a code comment with this reference.

**Comment by otan** [comment]
bors r=sumeerbhola

**Pull request merged**
