### PR TITLE
sql: avoid role existence check in DROP ROLE when it's not necessary

### PR DESCRIPTION
**Pull request by rafiss**
We only need to make the RoleExists call when the `IF EXISTS` clause is used.

This check was recently added in 696869afeb369f3999384e2637610f5fee147362.

informs: https://github.com/cockroachdb/cockroach/issues/134538
Release note: None

### CODE REVIEW

**Comment by rafiss** [comment]
I cherry-picked this commit into these backports: #134967, https://github.com/cockroachdb/cockroach/pull/134968, https://github.com/cockroachdb/cockroach/pull/134969, https://github.com/cockroachdb/cockroach/pull/134970

**Review by spilchen — APPROVED** [review]
:lgtm: Good catch. I missed this in my review.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134979#-:-OBWLVrT-EWDsV058Dzy:b-sgkchc)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @Dedej-Bergin)

**Comment by Dedej-Bergin** [comment]
*[`pkg/sql/drop_role.go` line 113 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134979#-OBWSuyb4Dk_vN8ew_3G:-OBWSuyb4Dk_vN8ew_3H:b-y2b2td) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1cc877a8dfaa2a47fc9388cf25731528b3895bf/pkg/sql/drop_role.go#L113)):*
> ```Go
> 				// If `IF EXISTS` was specified, then a non-existing role should be
> 				// skipped without causing any error.
> 				roleExists, err := RoleExists(params.ctx, params.p.InternalSQLTxn(), name)
> ```

Maybe we can combine these here?

```
			if roleExists, err := RoleExists(params.ctx, params.p.InternalSQLTxn(), name); err != nil {
				return err
			} else if !roleExists {
				// If the role does not exist, we can skip the check for targetIsAdmin.
				continue
			}
```

**Review by Dedej-Bergin — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134979#-:-OBWT4OT-qsp1cvcu3Tk:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @rafiss)

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134979)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @Dedej-Bergin)

___
*[`pkg/sql/drop_role.go` line 113 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134979#-OBWSuyb4Dk_vN8ew_3G:-OBWTHZJ68lEsq1wCNSX:b-g2klio) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1cc877a8dfaa2a47fc9388cf25731528b3895bf/pkg/sql/drop_role.go#L113)):*
<details><summary><i>Previously, Dedej-Bergin (Bergin Dedej) wrote…</i></summary><blockquote>

Maybe we can combine these here?

```
			if roleExists, err := RoleExists(params.ctx, params.p.InternalSQLTxn(), name); err != nil {
				return err
			} else if !roleExists {
				// If the role does not exist, we can skip the check for targetIsAdmin.
				continue
			}
```
</blockquote></details>

that is possible, but it does make the if statement a bit longer and hard to read. it also only saves 2 lines of code, so i don't feel that it's needed

**Comment by Dedej-Bergin** [comment]
*[`pkg/sql/drop_role.go` line 113 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134979#-OBWSuyb4Dk_vN8ew_3G:-OBWUEmv6dkYwCsHdLKW:bpb6aaz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1cc877a8dfaa2a47fc9388cf25731528b3895bf/pkg/sql/drop_role.go#L113)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

that is possible, but it does make the if statement a bit longer and hard to read. it also only saves 2 lines of code, so i don't feel that it's needed
</blockquote></details>

What about this to reduce nesting?

```
		if hasAdmin {
			continue
		}

		if n.ifExists {
			// If `IF EXISTS` was specified, then a non-existing role should be
			// skipped without causing any error.
roleExists, err := RoleExists(params.ctx, params.p.InternalSQLTxn(), name)
			if err != nil {
				return err
			}
			if !roleExists {
				// If the role does not exist, we can skip the check for targetIsAdmin.
				continue
                        }
		}

		// Non-admin users cannot drop admins.
		targetIsAdmin, err := params.p.UserHasAdminRole(params.ctx, name)
		if err != nil {
			return err
		}
		if targetIsAdmin {
			return pgerror.New(pgcode.InsufficientPrivilege, "must be superuser to drop superusers")
		}
```

**Comment by rafiss** [comment]
tftr

bors r+

**Pull request merged**
