### PR TITLE
ui next: React router + top level routes

### PR DESCRIPTION
**Pull request by mrtracy**
Commit installs react-router project into the next ui. The four current
top-level routes ("Cluster", "Nodes", "Databases", and "Help Us") have all been
configured in the main application.

Commit also recreates the side navigation bar and header bar from the current UI
(minus the "health" indicator in the header). All links in the navigation bar
are route-aware; the active page is highlighted, and clicking links will
change the current route. The pages have no content yet, only placeholder text
to indicate that they are selected.

This commit establishes an initial skeleton file structure for the next ui;
`components` directory contains stateless view-only components, while
`containers` should contain "smart" components which should eventually be aware
of the program's state.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6089)

### CODE REVIEW

**Comment by maxlang** [comment]
:lgtm: with some minor comments

---

Reviewed 14 of 14 files at r1.
Review status: 14 of 15 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[ui/next/package.json, line 11 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6089#-KFedwckZFwcS3dgz9Eb:-KFedwclJsopYZNvV9Mx:-1502376468) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e23b1ba99920b41a7c189e6be6cde50856522fc/ui/next/package.json#L11)):*
You should add this to typings too I think.

---

*[ui/next/app/app.tsx, line 25 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6089#-KFeTtm3KZyXdvsWVF1y:-KFeTtm3KZyXdvsWVF1z:-764475250) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e23b1ba99920b41a7c189e6be6cde50856522fc/ui/next/app/app.tsx#L25)):*
Looks like you used tabs instead of spaces.

---

*[ui/next/app/tsconfig.json, line 6 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6089#-KFeTyN6N-sYB75pwrXH:-KFeTyN6N-sYB75pwrXI:160419952) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e23b1ba99920b41a7c189e6be6cde50856522fc/ui/next/app/tsconfig.json#L6)):*
tab

---

*[ui/next/app/components/layoutHeader.tsx, line 10 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6089#-KFeeGhYIzyzU14TJbOc:-KFeeGhYIzyzU14TJbOd:-1619842481) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e23b1ba99920b41a7c189e6be6cde50856522fc/ui/next/app/components/layoutHeader.tsx#L10)):*
I suppose `<{}, {}>` is necessary because of the noImplicitAny flag? Any reason you chose to use `{}` instead of `any`? I feel like `any` reads better and is more general.

---

*[ui/next/app/components/layoutHeader.tsx, line 15 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6089#-KFeetZ1i2rg0Fk1yWxN:-KFeetZ1i2rg0Fk1yWxO:570170057) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e23b1ba99920b41a7c189e6be6cde50856522fc/ui/next/app/components/layoutHeader.tsx#L15)):*
Tabs - I'll stop commenting on them, because it looks like they're in most files.

---

*[ui/next/app/components/layoutSidebar.tsx, line 20 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6089#-KFehUpEpkTF1wzTeZ79:-KFefzhuKnA2e8oUkWlu:-1541546222) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e23b1ba99920b41a7c189e6be6cde50856522fc/ui/next/app/components/layoutSidebar.tsx#L20)):*
Make sure this is coming in from the typings correctly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6089#-:-KFehklR0TI35QW_2SXn:-1886319936)*

**Comment by maxlang** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[ui/next/typings.json, line 5 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6089#-KFei3fcP6m_KCnR3OoF:-KFei3fcP6m_KCnR3OoG:91417727) ([raw file](https://github.com/cockroachdb/cockroach/blob/86e931aca160d63ad9bc03aad02b2aaba3ffc57c/ui/next/typings.json#L5)):*
Now I get the following error in the console:
```
logger.js:18 TypeScript http://localhost:8080/next/typings/main/ambient/react-router/index.d.ts:412:64Logger.error @ logger.js:18(anonymous function) @ format-errors.js:14formatErrors @ format-errors.js:8(anonymous function) @ plugin.js:39Promise.resolve (async)Resolver.resolveDependencies @ resolver.js:62Resolver.resolve @ resolver.js:35(anonymous function) @ plugin.js:36Promise.resolve (async)translate @ plugin.js:14(anonymous function) @ system.src.js:5031(anonymous function) @ system.src.js:5031(anonymous function) @ system.src.js:5031Promise.resolve (async)a @ system.src.js:5031i.onreadystatechange @ system.src.js:5031XMLHttpRequest.send (async)X @ system.src.js:5031(anonymous function) @ system.src.js:5031(anonymous function) @ system.src.js:5031(anonymous function) @ system.src.js:5031(anonymous function) @ system.src.js:5031(anonymous function) @ system.src.js:5031(anonymous function) @ system.src.js:5031(anonymous function) @ system.src.js:5031(anonymous function) @ system.src.js:5031(anonymous function) @ system.src.js:5031
logger.js:18 TypeScript Cannot find namespace 'HistoryModule'. (TS2503)
```

If I pull in the non-ambient dep I get other errors.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6089)*

**Comment by mrtracy** [comment]
Review status: 14 of 15 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[ui/next/package.json, line 11 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6089#-KFedwckZFwcS3dgz9Eb:-KFelYmto22wd2WJB_RM:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e23b1ba99920b41a7c189e6be6cde50856522fc/ui/next/package.json#L11)):*
Done.

---

*[ui/next/typings.json, line 5 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6089#-KFei3fcP6m_KCnR3OoF:-KFelVkw708R2pwiBCSz:-1386738069) ([raw file](https://github.com/cockroachdb/cockroach/blob/86e931aca160d63ad9bc03aad02b2aaba3ffc57c/ui/next/typings.json#L5)):*
I believe I have fixed this.

---

*[ui/next/app/components/layoutHeader.tsx, line 10 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6089#-KFeeGhYIzyzU14TJbOc:-KFelEgK-9OS3_xsxnrR:-740126940) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e23b1ba99920b41a7c189e6be6cde50856522fc/ui/next/app/components/layoutHeader.tsx#L10)):*
As we discussed, `{}` is not equivalent to `any`. `{}` is a typed object with no properties, it essentially forbids the component from using anything attached to `this.props`.

---

*[ui/next/app/components/layoutHeader.tsx, line 15 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6089#-KFeetZ1i2rg0Fk1yWxN:-KFelQ0jg3VMOG6N_Z-c:-2068908162) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e23b1ba99920b41a7c189e6be6cde50856522fc/ui/next/app/components/layoutHeader.tsx#L15)):*
I have repaired my editor settings, and will retab all files in a subsequent PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6089)*

**Comment by maxlang** [comment]
Ok typings issues seem resolved and I agree with your use of `{}` over `any`

---

Review status: 14 of 15 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6089#-:-KFelYHxYteVcZ1NpPuN:1532661958)*

**Comment by mrtracy** [comment]
Review status: 14 of 15 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[ui/next/app/components/layoutSidebar.tsx, line 20 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6089#-KFehUpEpkTF1wzTeZ79:-KFeltIzpgtT7odFW3tu:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e23b1ba99920b41a7c189e6be6cde50856522fc/ui/next/app/components/layoutSidebar.tsx#L20)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6089)*

**Pull request merged**
