### PR TITLE
rac2: delay send stream close by 1s

### LINKED ISSUE #129885: rac2: delay closing send stream on probe
From [#129759](https://github.com/cockroachdb/cockroach/pull/129759#pullrequestreview-2267045208):
 
> We should also do the TODO (which we never did in the prototype) to transition from probeRecentlyReplicate to closing the replicaSendStream after x seconds. The reason we had probeRecentlyReplicate is we don't want to admit a flood of elastic work by excluding the slow replica from WaitForEval if it briefly transitioned to probe and back to replicate. Since RangeController relies on Processor for most of its locking, and because we don't want O(ranges) goroutines, we could just assume that RangeController is provided a timer scheduling interface in its options. Something like:
>
>```
>type ProbeToCloseTimerScheduler interface {
>   ScheduleReplicaStreamClose()
>}
>```

Jira issue: CRDB-41750

Epic CRDB-37515

### PR DESCRIPTION
**Pull request by kvoli**
The `RangeController` transitioned a replica send stream directly to closed if it encountered `StateProbe`. This isn't desirable, as streams may quickly transition in and out of `StateProbe` and closing the stream allows elastic work to evaluate without there being available tokens on a stream and/or without deducting tokens.

Delay closing the stream by 1s, which is checked within `HandleRaftEventRaftMuLocked` (calling `handleReadyState`).

`ScheduleSendStreamCloseRaftMuLocked` is now called upon first encountering a replica send stream which transitioned to `StateProbe`. 

`ScheduleSendStreamCloseRaftMuLocked` ensures `HandleRaftEventRaftMuLocked` is at a minimum called once after `now+delay` time.

Resolves: #129885
Release note: None

### CODE REVIEW

**Comment by kvoli** [comment]
@sumeerbhola was this along the lines of what you were thinking for delaying closing the stream?

This is missing tests but the general approach is there.

**Review by kvoli — COMMENTED** [review]
I was also thinking we could make this much simpler if we are happy with a bounded delay, instead of exact.

We could just tick a timer continuously at the configured delay and have a synced buffer the goroutine on the ticker reads from and range controller (scheduler) goroutines write to with a rangeID.

**Review by sumeerbhola — COMMENTED** [review]
I suspect we will eventually care about it being more exact, because this affects eval wait now, and later will also affect when we force-flush (i.e., don't force-flush a long send-queue when another replica that is participating in quorum transitions to StateProbe and back to StateReplicate in a "short duration"). The delayed force-flush will be observable in higher write latency.

And you've written the `streamCloseScheduler` that is nicely abstracted and can be thoroughly tested, so let's use it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129894#-:-O5YsIO30DNO1mV3H8CC:b-7j1ybc)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

**Review by sumeerbhola — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129894)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129894#-O5YwKnj2SVOMSSAZDVP:-O5YwKnj2SVOMSSAZDVQ:b-j8vdwe) ([raw file](https://github.com/cockroachdb/cockroach/blob/d039e5d85bdd608b52417e3c6a45da9a5cb1ae70/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L184)):*
> ```Go
> 	// e.g.,
> 	//
> 	//   HanldeRaftEventRaftMuLocked(ctx, RaftEvent{})
> ```

nit: Handle
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 189 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129894#-O5YwVlmD7QieCJ_aaem:-O5YwVlmD7QieCJ_aaen:bzh8348) ([raw file](https://github.com/cockroachdb/cockroach/blob/d039e5d85bdd608b52417e3c6a45da9a5cb1ae70/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L189)):*
> ```Go
> 	// transitioned to StateReplicate.
> 	//
> 	// Requires replica.raftMu to be held.
> ```

why do we care whether `raftMu` is held, given many ranges can call it? Just for documentation to avoid silly deadlocks? Which is fine to keep.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 511 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129894#-O5Yxi802P9jh4Is-wrJ:-O5Yxi802P9jh4Is-wrK:b-gkkhkl) ([raw file](https://github.com/cockroachdb/cockroach/blob/d039e5d85bdd608b52417e3c6a45da9a5cb1ae70/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L511)):*
> ```Go
> 		syncutil.Mutex
> 		connectedState      connectedState
> 		connectedStateStart time.Time
> ```

is this always the start time for when `connectedState` was changed? This deserves a code comment.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 743 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129894#-O5YyHC3AQKxLMYDpWrU:-O5YyHC3AQKxLMYDpWrV:b11cbwz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d039e5d85bdd608b52417e3c6a45da9a5cb1ae70/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L743)):*
> ```Go
> // after observing a replica in StateProbe before closing the send stream if
> // the replica remains in StateProbe.
> const probeRecentlyReplicateDuration = time.Second
> ```

Consider putting this in options as a `func() time.Duration` so that we can change it via a cluster setting. Fine to do it later too.
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/close_scheduler.go` line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129894#-O5Yygw34ZD3ao5PwZRp:-O5Yygw34ZD3ao5PwZRq:b-l4xl3x) ([raw file](https://github.com/cockroachdb/cockroach/blob/d039e5d85bdd608b52417e3c6a45da9a5cb1ae70/pkg/kv/kvserver/kvflowcontrol/replica_rac2/close_scheduler.go#L56)):*
> ```Go
> // Requires raftMu to be held.
> func (s *streamCloseScheduler) ScheduleSendStreamCloseRaftMuLocked(
> 	ctx context.Context, delay time.Duration, rangeID roachpb.RangeID,
> ```

nit: this isn't the same as the interface, since this expects a `rangeID`.
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/close_scheduler.go` line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129894#-O5Yz6qCCBcyx4CSQnWr:-O5Yz6qD8WTcdCqynbMP:b4fnhef) ([raw file](https://github.com/cockroachdb/cockroach/blob/d039e5d85bdd608b52417e3c6a45da9a5cb1ae70/pkg/kv/kvserver/kvflowcontrol/replica_rac2/close_scheduler.go#L67)):*
> ```Go
> 	if s.mu.scheduled.Len() == 1 {
> 		// This is the first item in the queue, so start the scheduler loop.
> 		_ = s.stopper.RunAsyncTask(ctx,
> ```

It seems possible that the previously started goroutine does not observe that the heap has become empty (because the transition to empty and back to non-empty is very quick, and the goroutine is not holding a lock), and continues running, while that state transition is guaranteed to be observed here and another goroutine is created. It seems safer to never stop that goroutine and make it block on a channel for the heap to be non-empty.

**Review by kvoli — COMMENTED** [review]
TYFTR!

I've (cheekily) pushed in a bit of mechanical refactoring of `TestRangeController`, to encapsulate the test state in a struct and move the several helper functions onto it.

Added a test for the `streamCloseScheduler` and modified the `TestRangeController` test to check the transition between states.

Should be good for another look @sumeerbhola 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129894#-:-O5a-KAPDhrAO91numEm:b-r8yr83)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129894#-O5YwKnj2SVOMSSAZDVP:-O5_3o7K6yVjhki9uNYb:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/d039e5d85bdd608b52417e3c6a45da9a5cb1ae70/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L184)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: Handle
</blockquote></details>

Fixed.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 189 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129894#-O5YwVlmD7QieCJ_aaem:-O5_3opJDs9i9gfJMNm_:b-1qrc6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/d039e5d85bdd608b52417e3c6a45da9a5cb1ae70/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L189)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why do we care whether `raftMu` is held, given many ranges can call it? Just for documentation to avoid silly deadlocks? Which is fine to keep.
</blockquote></details>

Just for documentation to avoid silly deadlocks.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 511 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129894#-O5Yxi802P9jh4Is-wrJ:-O5_4BCiBdIk2Aqw8pO-:bxgm3fg) ([raw file](https://github.com/cockroachdb/cockroach/blob/d039e5d85bdd608b52417e3c6a45da9a5cb1ae70/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L511)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is this always the start time for when `connectedState` was changed? This deserves a code comment.
</blockquote></details>

It is, added a comment.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 743 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129894#-O5YyHC3AQKxLMYDpWrU:-O5_4UmG0RzFr0f1D9Hq:bwit25w) ([raw file](https://github.com/cockroachdb/cockroach/blob/d039e5d85bdd608b52417e3c6a45da9a5cb1ae70/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L743)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Consider putting this in options as a `func() time.Duration` so that we can change it via a cluster setting. Fine to do it later too.
</blockquote></details>

Good idea, updated to a func.
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/close_scheduler.go` line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129894#-O5Yygw34ZD3ao5PwZRp:-O5_4fj3BPN4odfQbnY2:b-8cad0p) ([raw file](https://github.com/cockroachdb/cockroach/blob/d039e5d85bdd608b52417e3c6a45da9a5cb1ae70/pkg/kv/kvserver/kvflowcontrol/replica_rac2/close_scheduler.go#L56)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: this isn't the same as the interface, since this expects a `rangeID`.
</blockquote></details>

I've updated the iface def in range controller to match this one. I realized its desirable to just directly call this w/ a rangeID rather than mediating via the processor which would provide the rangeID.
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/close_scheduler.go` line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129894#-O5Yz6qCCBcyx4CSQnWr:-O5a-BVR4S_bt-BXK12u:b-2xasmn) ([raw file](https://github.com/cockroachdb/cockroach/blob/d039e5d85bdd608b52417e3c6a45da9a5cb1ae70/pkg/kv/kvserver/kvflowcontrol/replica_rac2/close_scheduler.go#L67)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

It seems possible that the previously started goroutine does not observe that the heap has become empty (because the transition to empty and back to non-empty is very quick, and the goroutine is not holding a lock), and continues running, while that state transition is guaranteed to be observed here and another goroutine is created. It seems safer to never stop that goroutine and make it block on a channel for the heap to be non-empty.
</blockquote></details>

I was planning on just allowing it but your plan seems nicer. Updated to just block on a channel when there's nothing in the heap.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 5 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129894)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/close_scheduler.go` line 112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129894#-O5oxgI4-EDYdKNHWSjs:-O5oxgI4-EDYdKNHWSjt:b66udac) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f96441b0bc387b446bb29d6d8636a7d53de7975/pkg/kv/kvserver/kvflowcontrol/replica_rac2/close_scheduler.go#L112)):*
> ```Go
> 			s.scheduler.EnqueueRaftReady(event.rangeID)
> 		}
> 		nextDelay := s.nextDelay(s.clock.Now())
> ```

It seems possible that the heap became empty after `readyEvents` and was non-empty by the time of `nextDelay` and due to some slowness in the goroutine, the ticker fired and it got selected instead of the `nonEmptyCh`. That is, there doesn't seem to be a guarantee that this goroutine will drain the `nonEmptyCh` on a empty => non-empty heap transition. Which is fine for this kind of logic, since the `nonEmptyCh` is just trying to ensure that the goroutine doesn't sit idle with no ticker while there are elements in the heap. But I think we need to make the write to the channel non-blocking by wrapping it in a select.

Also, if we do want to handle arbitrary values of duration in `ScheduleSendStreamCloseRaftMuLocked`, then whenever the heap root changes in `ScheduleSendStreamCloseRaftMuLocked`, the channel should be signaled so that it picks a new `nextDelay`.
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/close_scheduler.go` line 152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129894#-O5ozdwO0uUvxBJ9kKoQ:-O5ozdwO0uUvxBJ9kKoR:ba9cmjf) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f96441b0bc387b446bb29d6d8636a7d53de7975/pkg/kv/kvserver/kvflowcontrol/replica_rac2/close_scheduler.go#L152)):*
> ```Go
> 	var events []scheduledCloseEvent
> 	for s.mu.scheduled.Len() > 0 {
> 		next := heap.Pop(&s.mu.scheduled).(scheduledCloseEvent)
> ```

The top of the heap is at index 0, so we can simply access s.mu.scheduled[0] and decide whether it is ready to run or not. That is, don't do a pop and push pair.

**Review by kvoli — COMMENTED** [review]
TYFTR

Should be good for another look @sumeerbhola.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129894#-:-O5sj44s00EqQHqnNUJO:b-urncql)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/close_scheduler.go` line 112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129894#-O5oxgI4-EDYdKNHWSjs:-O5shR5fAfXFR05xDBHj:bjiesg) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f96441b0bc387b446bb29d6d8636a7d53de7975/pkg/kv/kvserver/kvflowcontrol/replica_rac2/close_scheduler.go#L112)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

It seems possible that the heap became empty after `readyEvents` and was non-empty by the time of `nextDelay` and due to some slowness in the goroutine, the ticker fired and it got selected instead of the `nonEmptyCh`. That is, there doesn't seem to be a guarantee that this goroutine will drain the `nonEmptyCh` on a empty => non-empty heap transition. Which is fine for this kind of logic, since the `nonEmptyCh` is just trying to ensure that the goroutine doesn't sit idle with no ticker while there are elements in the heap. But I think we need to make the write to the channel non-blocking by wrapping it in a select.

Also, if we do want to handle arbitrary values of duration in `ScheduleSendStreamCloseRaftMuLocked`, then whenever the heap root changes in `ScheduleSendStreamCloseRaftMuLocked`, the channel should be signaled so that it picks a new `nextDelay`.
</blockquote></details>

Updated to do a non-blocking  write and also signal when the front of the heap changes, also extended the test to cover it.
___
*[`pkg/kv/kvserver/kvflowcontrol/replica_rac2/close_scheduler.go` line 152 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129894#-O5ozdwO0uUvxBJ9kKoQ:-O5shQ2U4Hamzs443j3y:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f96441b0bc387b446bb29d6d8636a7d53de7975/pkg/kv/kvserver/kvflowcontrol/replica_rac2/close_scheduler.go#L152)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

The top of the heap is at index 0, so we can simply access s.mu.scheduled[0] and decide whether it is ready to run or not. That is, don't do a pop and push pair.
</blockquote></details>

Done.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 9 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129894#-:-O5tS5Ai2RAOhbcfvtkq:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 638 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129894#-O5tRKf76UE4oALz9Z1d:-O5tRKf88AWiInozh-dI:b3qsrsg) ([raw file](https://github.com/cockroachdb/cockroach/blob/43a6fea68e7fb48c9a966951cb796dd59b6d75a8/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L638)):*
> ```Go
> 				// stream. Also schedule an event, so that even if there are no
> 				// entries, we will still reliably close the stream if still in
> 				// StateProbe.
> ```

can you add a TODO(sumeer) here to think through whether we should be returning the tokens immediately. Currently we are not, and my current inclination is that we should. That is, `probeRecentlyReplicate` only affects whether to wait on this replica for eval, and otherwise it behaves like a closed `replicaSendStream`.

**Comment by kvoli** [comment]
Fixed a linter error.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 2 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129894#-:-O5xXou99C0EbjCZ-4p9:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 352 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/129894#-O5xXMk-07UmJJBsCLpW:-O5xXMk-07UmJJBsCLpX:b32vhw) ([raw file](https://github.com/cockroachdb/cockroach/blob/65faa8e9b97a7d0d66ac3ab00fc6ab954da06bf8/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L352)):*
> ```Go
> 	for r, rs := range rc.replicaMap {
> 		info := rc.opts.RaftInterface.FollowerState(r)
> 		shouldWaitChange = rs.handleReadyState(ctx, info) || shouldWaitChange
> ```

:)

**Comment by kvoli** [comment]
TYFTR

bors r=sumeerbhola

**Pull request merged**
