### PR TITLE
opt: move EXPORT planning to the optimizer

### LINKED ISSUE #33469: sql: bring EXPORT under the cost-based optimizer
Currently the logic for EXPORT uses a weird interaction/hack because it's a CCL statement, and does not use the CBO to optimize its input query.

The EXPORT planning code must be amended to utilize the CBO, subject to the `optimizer` session setting.

The litmus test to verify that EXPORT indeed uses the CBO is support for correlated subqueries, for example

```
> create table t(x int); create table u(x int);
> export into csv 'nodelocal:///foo.csv' from select exists(select * from u where u.x = t.x) from t;
```

(currently fails)

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### importccl: move export enterprise check to processor instantiation

This change moves the EXPORT license check from the planning code to
the execution part, when we instantiate the CSV Writer processor. The
planning code will move into the optimizer and making the check from
there is more awkward.

Release note: None

#### opt: move EXPORT planning to the optimizer

This change moves the planning of EXPORT to the optimizer. The
planning logic is fairly straightforward and doesn't need to be CCL.

EXPORT can now be used with EXPLAIN and PREPARE.

EXPORT can now only be used with the optimizer (the heuristic planner
will hopefully be removed soon altogether anyway).

One somewhat tricky aspect of the change is around the `KVOptions`
which have string expressions as values (in order to support
placeholders).

Fixes #33469.

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
Opt stuff :lgtm:

> Reviewed 1 of 1 files at r1, 30 of 30 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39312#-:-LlWmMgDAfI22NCFpAE9:b-ow6v6e)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz, @dt, @justinj, and @RaduBerinde)

___
*[pkg/sql/distsql_physical_planner.go, line 3290 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39312#-LlWgomP9w2Y5ueb-u2B:-LlWgomP9w2Y5ueb-u2C:b-4r0gpd) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aa00da8a6a9794cc9cd11254dc864ebf44b26c4/pkg/sql/distsql_physical_planner.go#L3290)):*
> ```Go
> 
> 	// Overwrite PlanToStreamColMap (used by recv below) to reflect the output of
> 	// the non-grouping stage we've added above. That stage outputs produces
> ```

outputs produces -> outputs (?)
___
*[pkg/sql/export.go, line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39312#-LlWhv4EC2FszR2tf_xf:-LlWhv4EC2FszR2tf_xg:bd2fqma) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aa00da8a6a9794cc9cd11254dc864ebf44b26c4/pkg/sql/export.go#L78)):*
> ```Go
> 	}
> 
> 	if fileFormat != "CSV" {
> ```

Why not have the caller check this so you don't need to pass the extra param?
___
*[pkg/sql/opt/optbuilder/export.go, line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39312#-LlWlIRmBuwbfe5TbhY9:-LlWlIRmBuwbfe5TbhYA:bkssr6v) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aa00da8a6a9794cc9cd11254dc864ebf44b26c4/pkg/sql/opt/optbuilder/export.go#L28)):*
> ```Go
> 	// pass a "blank" scope rather than inScope.
> 	emptyScope := &scope{builder: b}
> 	inputScope := b.buildSelect(export.Query, nil /* desiredTypes */, emptyScope)
> ```

It's not possible to export the output of other types of statements?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39312)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @danhhz, @dt, @justinj, and @rytaft)

___
*[pkg/sql/distsql_physical_planner.go, line 3290 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39312#-LlWgomP9w2Y5ueb-u2B:-LlXPVOy1T81xfYTvjk-:b-kyxarq) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aa00da8a6a9794cc9cd11254dc864ebf44b26c4/pkg/sql/distsql_physical_planner.go#L3290)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

outputs produces -> outputs (?)
</blockquote></details>

Rewrote the whole comment.
___
*[pkg/sql/export.go, line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39312#-LlWhv4EC2FszR2tf_xf:-LlWzmvF3clVQcP2NJkn:bvgj1gv) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aa00da8a6a9794cc9cd11254dc864ebf44b26c4/pkg/sql/export.go#L78)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Why not have the caller check this so you don't need to pass the extra param?
</blockquote></details>

There's no need to hardcode in the optimizer what formats are supported. It's not inconceivable that we may add more in the future.
___
*[pkg/sql/opt/optbuilder/export.go, line 28 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39312#-LlWlIRmBuwbfe5TbhY9:-LlWzg0L4ZT7TGGbLkYc:bgdlrkl) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aa00da8a6a9794cc9cd11254dc864ebf44b26c4/pkg/sql/opt/optbuilder/export.go#L28)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

It's not possible to export the output of other types of statements?
</blockquote></details>

No, `export.Query` is a `*Select`.

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39312)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @danhhz, @dt, and @justinj)

___
*[pkg/sql/export.go, line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39312#-LlWhv4EC2FszR2tf_xf:-LlXSaojBXST31_kyzRf:b1ubcge) ([raw file](https://github.com/cockroachdb/cockroach/blob/1aa00da8a6a9794cc9cd11254dc864ebf44b26c4/pkg/sql/export.go#L78)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

There's no need to hardcode in the optimizer what formats are supported. It's not inconceivable that we may add more in the future.
</blockquote></details>

Makes sense

**Review by adityamaru27 — APPROVED** [review]
BulkIO file changes LGTM. Chimed in because I recently worked with EXPORT.

**Review by dt — APPROVED** [review]
I delegated reviewing on behalf of bulk-io to @adityamaru27 but since this has been on my TODO list forever, I just wanted to say thanks for picking this up!

**Comment by RaduBerinde** [comment]
TFTRs!

bors r+

**Pull request merged**
