### PR TITLE
sql: implement `SHOW JOBS`

### PR DESCRIPTION
**Pull request by julianzq**
Implements RFC #16688.
The result of calling `SHOW JOBS` is the same as `SELECT * FROM crdb_internal.jobs`.

### CODE REVIEW

**Comment by knz** [comment]
Thanks @israelg99 for your contribution!

@benesch hold on this one for a little bit, I'm testing a little improvement.

**Comment by knz** [comment]
@israelg99 please consider replacing this code by the suggestion in https://github.com/cockroachdb/cockroach/pull/16688#issuecomment-311615689.

**Comment by israelg99** [comment]
@knz Done, thank you :+1:

**Comment by knz** [comment]
You forgot to re-generate `sql.go` from `sql.y`.

**Comment by israelg99** [comment]
@knz Oh, done.

**Comment by knz** [comment]
@israelg99 please add tests by extending `jobs_test.go` to use your new statement next to / in addition to the current query on the jobs table.

**Comment by israelg99** [comment]
@knz that's the spot! since we want to test both `crdb_internal.jobs` and `SHOW JOBS` , I wrapped the contents of `verifyJobRecord` func in a closure that takes a `source` string, and simply called it twice. Please take a look :)

**Comment by knz** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16733#-:-KnjsmzZhFSPLk76l-Yf:bnfp4nl)*

**Comment by knz** [comment]
Swell, you are showing us here a job well done (pun intended). :joy_cat: 

Thank you for your contribution!

**Pull request merged**
