### PR TITLE
roachtest: mark some hibernate/pgjdbc tests as flaky

### LINKED ISSUE #98227: roachtest: pgjdbc failed
roachtest.pgjdbc [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/8965205?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/8965205?buildTab=artifacts#/pgjdbc) on master @ [1b162d1b274eec7b307fbbfca7294460bfdef025](https://github.com/cockroachdb/cockroach/commits/1b162d1b274eec7b307fbbfca7294460bfdef025):

```
test artifacts and logs in: /artifacts/pgjdbc/run_1
(orm_helpers.go:212).summarizeFailed: 
Tests run on Cockroach v23.1.0-alpha.6-dev-1b162d1b274eec7b307fbbfca7294460bfdef025
Tests run against pgjdbc REL42.3.3
5788 Total Tests Run
5054 tests passed
734 tests failed
72 tests skipped
182 tests ignored
0 tests passed unexpectedly
1 test failed unexpectedly
0 tests expected failed but skipped
0 tests expected failed but not run
---
--- FAIL: org.postgresql.test.jdbc2.CursorFetchTest.testBasicFetch[binary = FORCE] - https://github.com/cockroachdb/cockroach/issues/40195 (unexpected)
For a full summary look at the pgjdbc artifacts
An updated blocklist (pgjdbcBlocklist) is available in the artifacts' pgjdbc log
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=true</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #94292 roachtest: pgjdbc failed [C-test-failure O-roachtest O-robot T-sql-sessions branch-release-22.2]
- #93242 roachtest: pgjdbc failed [C-test-failure O-roachtest O-robot T-sql-sessions branch-release-22.1]
</p>
</details>
/cc @cockroachdb/sql-sessions
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*pgjdbc.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-25140

### LINKED ISSUE #98288: roachtest: hibernate failed
roachtest.hibernate [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/8981523?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/8981523?buildTab=artifacts#/hibernate) on release-22.1 @ [14204b0e190f146ca46f2cc16f15d0949fc97bbd](https://github.com/cockroachdb/cockroach/commits/14204b0e190f146ca46f2cc16f15d0949fc97bbd):

```
test artifacts and logs in: /artifacts/hibernate/run_1
(orm_helpers.go:193).summarizeFailed: 
Tests run on Cockroach v22.1.16-47-g14204b0e19
Tests run against hibernate 5.4.30
8106 Total Tests Run
8088 tests passed
18 tests failed
1901 tests skipped
0 tests ignored
0 tests passed unexpectedly
2 tests failed unexpectedly
0 tests expected failed but skipped
0 tests expected failed but not run
---
--- FAIL: org.hibernate.serialization.SessionFactorySerializationTest.testUnNamedSessionFactorySerialization - unknown (unexpected)
--- FAIL: org.hibernate.serialization.SessionFactorySerializationTest.testNamedSessionFactorySerialization - unknown (unexpected)
For a full summary look at the hibernate artifacts
An updated blocklist (hibernateBlockList22_1) is available in the artifacts' hibernate log
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_fs=ext4</code>
, <code>ROACHTEST_localSSD=true</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #97842 roachtest: hibernate failed [C-test-failure O-roachtest O-robot T-sql-sessions branch-master]
- #96493 roachtest: hibernate failed [C-test-failure O-roachtest O-robot T-sql-sessions branch-release-22.2]
</p>
</details>
/cc @cockroachdb/sql-sessions
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*hibernate.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-25171

### PR DESCRIPTION
**Pull request by rafiss**
I've noticed these ones coming up more.

fixes https://github.com/cockroachdb/cockroach/issues/98227
fixes https://github.com/cockroachdb/cockroach/issues/98288
Release note: None

### CODE REVIEW

**Review by andyyang890 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98346)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @rafiss, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/canary.go` line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98346#-NQBI3LS-Fx7ZEBWcoxx:-NQBI3LS-Fx7ZEBWcoxy:b3y2gim) ([raw file](https://github.com/cockroachdb/cockroach/blob/afd08c80f39d509a8a906e8b73c9ed54e791e8eb/pkg/cmd/roachtest/tests/canary.go#L40)):*
> ```Go
> 
> // listWithName contains both a blocklist of known test errors and
> // failures but also an optional ignorelist for flaky tests.
> ```

Does this comment need to be updated? It looks like each of these structs is used as either a blocklist or an ignorelist instead of containing both like the comment suggests.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98346)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890, @herkolategan, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/canary.go` line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98346#-NQBI3LS-Fx7ZEBWcoxx:-NQRuEa-6QtAh_ijzxY7:b3dulwk) ([raw file](https://github.com/cockroachdb/cockroach/blob/afd08c80f39d509a8a906e8b73c9ed54e791e8eb/pkg/cmd/roachtest/tests/canary.go#L40)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Does this comment need to be updated? It looks like each of these structs is used as either a blocklist or an ignorelist instead of containing both like the comment suggests.
</blockquote></details>

yeah, nice catch

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98346)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andyyang890, @herkolategan, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/canary.go` line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98346#-NQBI3LS-Fx7ZEBWcoxx:-NQRu_Gb0a4XlgRcynoV:b-qfongl) ([raw file](https://github.com/cockroachdb/cockroach/blob/afd08c80f39d509a8a906e8b73c9ed54e791e8eb/pkg/cmd/roachtest/tests/canary.go#L40)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

yeah, nice catch
</blockquote></details>

actually, it seems better to do things the way the comment says

**Review by andyyang890 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98346#-:-NQS359E4R02jsZPv1YZ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan and @srosenberg)

**Comment by rafiss** [comment]
tftr!

bors r+

**Pull request merged**
