### PR TITLE
rac2,kvserver,raft: use raft LogSnapshot directly

### PR DESCRIPTION
**Pull request by pav-kv**
This PR:

- refactors `raft.MemoryStorage` to support log snapshots
- converts `rac2` tests to use the real `LogSnapshot` (backed by `MemoryStorage`) instead of a fake one
- converts `rac2` code to pass `raft.LogSnapshot` by value instead of hiding it behind an interface that might allocate

Related to #128779

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
> The real implementation computes a full `entry.Size()` for the proto, vs the fake was accounting only the `entry.Data` payload size. This difference is not crucial/significant, but maybe we should revisit which one should be used.

I haven't looked at the PR yet, but regarding this, RACv1 also used `len(entry.Data)`. This is because `entry.Size()` is not super-cheap -- it needs to compute the size of three varints. And I don't expect any write heavy workload will have those sizes be significant compared to `len(entry.Data)`. So we do the same in RACv2, and I don't think we should change that code.
Regarding what Raft does in `LogSnapshot.LogSlice`, it doesn't need to be the same, since RACv2 already needs to compensate for the fact that Raft does not know about what entries are subject to AC. But if it is trivial to change Raft to use `len(entry.Data)`, perhaps we should.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132600#-:-O9Bkf2W4uWHItBbSVT3:b-dqa2us)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

**Review by pav-kv — COMMENTED** [review]
Yeah, I agree we should just use `len(entry.Data)` consistently, for the cost & simplicity reasons. It wouldn't be hard to change in `raft`, though it should probably be done in sync with other log storage things in the stack (the CRDB `raft.Storage` implementation and the raft log cache). I'll do it separately.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132600#-:-O9BoHtaCWaJgvdgljsJ:b-wc5i24)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
still haven't looked at the code, but I am nervous about the datadriven test changes.

> Reviewed 1 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132600#-:-O9LIDseBwUnIP0OVZW9:bjlpi7k)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/do_force_flush` line 235 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/132600#-O9LHXCGB-ax0rguPOEH:-O9LHXCGB-ax0rguPOEI:b-jww6ng) ([raw file](https://github.com/cockroachdb/cockroach/blob/ede46c72f063f2b68264f1748539ee13a99a85eb/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/do_force_flush#L235)):*
> ```
> 
> # Scheduler event. Only two entries are dequeued from the send-queue since 3+3
> # = 6MiB exceeds the 4MiB threshold for sending in one scheduler event.
> ```

This seems stale. Also, given we passed 4MB to `LogSnapshot.LogSlice` and the entry length was ~3MB, I don't understand why we did not get back two entries.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/do_force_flush` line 267 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/132600#-O9LHupwDrlYZfrTWodR:-O9LHupwDrlYZfrTWodS:b-m6f54o) ([raw file](https://github.com/cockroachdb/cockroach/blob/ede46c72f063f2b68264f1748539ee13a99a85eb/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/do_force_flush#L267)):*
> ```
> scheduled-replicas: 2
> 
> # Another scheduler event. The send-queue is empty and force flushing stops.
> ```

I think we need to adjust the test so it does demonstrate the state transitions it was trying to show before.
Same comment applies to send_q_watcher.

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132600)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/do_force_flush` line 235 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/132600#-O9LHXCGB-ax0rguPOEH:-O9LfI3DENuXjoznXUpn:bv12xk0) ([raw file](https://github.com/cockroachdb/cockroach/blob/ede46c72f063f2b68264f1748539ee13a99a85eb/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/do_force_flush#L235)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This seems stale. Also, given we passed 4MB to `LogSnapshot.LogSlice` and the entry length was ~3MB, I don't understand why we did not get back two entries.
</blockquote></details>

The reason we get only one entry is in the semantics of the `LogSlice` method (which were inherited from how things are in the entire `raft` log storage stack): we return a prefix of the requested range with size <= `maxSize` at all times. The only exception when we can return more is when the **first **entry is large.

So, when we read the second entry and spot that adding it to the returned slice would bump the total size above `maxSize`, we drop it on the floor.

This isn't ideal: I think we should return this entry since we've already paid for fetching it. But it's the status quo.

**Comment by sumeerbhola** [comment]
> This isn't ideal: I think we should return this entry since we've already paid for fetching it. But it's the status quo.

Is there an existing issue for changing this, and if not, can you create one?

**Review by pav-kv — COMMENTED** [review]
Filed #132789 and referenced if from code comments. Also, I changed this PR structure a bit: now, the first commit modifies the `LogSlice` method in `rac2` test to mirror the current semantics of `LogStorage` methods. All the datadriven test changes are in the first commit. All other commits cause no change to the datadriven test files, which demonstrates that this change is a no-op.

I am reviewing the datadriven test changes in the first commit, to make it demonstrate what it wants to demonstrate. Other than than, there should be no blockers to review the rest.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132600#-:-O9M3teqD1trgWCuXif6:bskivh3)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @sumeerbhola)

**Comment by pav-kv** [comment]
@sumeerbhola I factored out the semantics change into a separate PR #132791, please review that one first. Then I'll rebase this PR on top which should be a no-op w.r.t. the datadriven tests.

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132600)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/do_force_flush` line 267 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/132600#-O9LHupwDrlYZfrTWodR:-O9MHVby-4ZSfZMx_BKa:b-gly8n4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ede46c72f063f2b68264f1748539ee13a99a85eb/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/do_force_flush#L267)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think we need to adjust the test so it does demonstrate the state transitions it was trying to show before.
Same comment applies to send_q_watcher.
</blockquote></details>

Done in #132791

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
still reading. pushing some initial questions/comments.

> Reviewed 2 of 12 files at r11, 3 of 11 files at r12.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132600#-:-O9RV87I33XFi5DFjW2U:bbfot9l)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

___
*[`pkg/raft/storage.go` line 199 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/132600#-O9RSxiaEpdqQ3Ha6P4m:-O9RSxiaEpdqQ3Ha6P4n:b2x338b) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ac331ba29db23cea6b1f1a685860f2228639ac5/pkg/raft/storage.go#L199)):*
> ```Go
> 	defer ms.Unlock()
> 	ms.callStats.term++
> 	if i < ms.ls.prev.index {
> ```

should this be `i <= ms.ls.prev.index` since `ms.ls.prev.index` is not accessible anymore?

Would the code benefit by defining a ms.ls.firstIndex() method.
___
*[`pkg/raft/storage.go` line 243 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/132600#-O9RTvdx-0_3f0vBgcXI:-O9RTvdx-0_3f0vBgcXJ:b-51k0mh) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ac331ba29db23cea6b1f1a685860f2228639ac5/pkg/raft/storage.go#L243)):*
> ```Go
> 	defer ms.Unlock()
> 
> 	prev := entryID{index: snap.Metadata.Index, term: snap.Metadata.Term}
> ```

nit: why is this called `prev` given this is likely going to be the next state?
___
*[`pkg/raft/storage.go` line 245 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/132600#-O9RU-Hg05ikagNksvfc:-O9RU-Hg05ikagNksvfd:b2xq4e) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ac331ba29db23cea6b1f1a685860f2228639ac5/pkg/raft/storage.go#L245)):*
> ```Go
> 	prev := entryID{index: snap.Metadata.Index, term: snap.Metadata.Term}
> 	// Check whether the snapshot is outdated.
> 	if prev.index <= ms.snapshot.Metadata.Index {
> ```

Do we not need to compare the terms because snapshots always represent committed data (since they represent the state machine)? Should we have an assertion that the term is not regressing.
___
*[`pkg/raft/storage.go` line 251 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/132600#-O9RUUpi3xhL7yd-K3hQ:-O9RUUpi3xhL7yd-K3hR:b-o56ta5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ac331ba29db23cea6b1f1a685860f2228639ac5/pkg/raft/storage.go#L251)):*
> ```Go
> 	ms.snapshot = snap
> 	// TODO(pav-kv): the term must be the last accepted term passed in.
> 	term := max(ms.ls.term, prev.term)
> ```

Can't the term regress in the LogSlice since it could represent uncommitted data? That is, the snapshot's term should always be used?
___
*[`pkg/raft/storage.go` line 255 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/132600#-O9RV2cTE1YgNyCVKKHR:-O9RV2cTE1YgNyCVKKHS:b-pib9ie) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ac331ba29db23cea6b1f1a685860f2228639ac5/pkg/raft/storage.go#L255)):*
> ```Go
> 	return nil
> }
> ```

(note to self: stopped here)

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132600)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @sumeerbhola)

___
*[`pkg/raft/storage.go` line 199 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/132600#-O9RSxiaEpdqQ3Ha6P4m:-O9UBGxw8_8m4mW9-LAc:b-n91ghg) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ac331ba29db23cea6b1f1a685860f2228639ac5/pkg/raft/storage.go#L199)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

should this be `i <= ms.ls.prev.index` since `ms.ls.prev.index` is not accessible anymore?

Would the code benefit by defining a ms.ls.firstIndex() method.
</blockquote></details>

This should be `i < ms.ls.prev.index` as is. For the `prev` entry, we should be able to return its term for log matching purposes. E.g. if we construct a `MsgApp` starting at the first log entry, we also need to set `MsgApp.LogTerm` to the term of the preceding entry.

https://github.com/cockroachdb/cockroach/blob/0866efef94ddde21ae8d273f56dabb1bb46f6c71/pkg/raft/storage.go#L75-L79

I could reinstate the `firstIndex()` method, but I didn't find it much useful myself because `prev` is descriptive enough (the entry before the first), and all the checks can be done against `prev` directly. This follows the convention instated by the `LogSlice` struct and many uses of it in this package.
___
*[`pkg/raft/storage.go` line 243 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/132600#-O9RTvdx-0_3f0vBgcXI:-O9UDFD46JahnYq_bX7m:b-nxpywv) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ac331ba29db23cea6b1f1a685860f2228639ac5/pkg/raft/storage.go#L243)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: why is this called `prev` given this is likely going to be the next state?
</blockquote></details>

This name inherited the `LogSlice` terminology (see the `LogSlice` initialization below). The `LogSlice.prev` field is the entry preceding the first entry of the slice.

So this is sort of a "next prev", if you will. I renamed it to `id` to avoid the terminology clash. This ID is is sort of self-explanatory in the code - the `entryID` at which the snapshot ends.
___
*[`pkg/raft/storage.go` line 245 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/132600#-O9RU-Hg05ikagNksvfc:-O9UGSce-WVoSqVXAook:b-57pyen) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ac331ba29db23cea6b1f1a685860f2228639ac5/pkg/raft/storage.go#L245)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Do we not need to compare the terms because snapshots always represent committed data (since they represent the state machine)? Should we have an assertion that the term is not regressing.
</blockquote></details>

Added an assertion that the `Metadata.Term` does not regress.

---

To help the speed of review: this commit is a no-op. It basically replaces the `entries` slice (in which `entries[0]` is fake and denotes the "prev" entry) with a more straightforward `LogSlice` with the same meaning (`LogSlice.prev == entries[0]`, and `LogSlice.entries == entries[1:]`).

The today's code does not try to enforce correctness much, neither does this PR. There are checks at other levels: `raftLog` and `unstable` struct, and the `raft/RawNode` struct itself; so when things are written to `Storage`, they have been verified. We can look at hardening later, hence various TODOs that I've added.
___
*[`pkg/raft/storage.go` line 251 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/132600#-O9RUUpi3xhL7yd-K3hQ:-O9UDpmx6ta6MJSaPp6r:becigy) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ac331ba29db23cea6b1f1a685860f2228639ac5/pkg/raft/storage.go#L251)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can't the term regress in the LogSlice since it could represent uncommitted data? That is, the snapshot's term should always be used?
</blockquote></details>

That depends on which term we consider:

- If it's the last entry term, it can regress.
- If it's the "leader term", it can not.

Here, `LogSlice.term` is supposed to be the leader term that can not regress. But it's not passed in from the caller yet, and also not used for anything internally in this `MemoryStorage` (though it should in the future). So I just update it to something so that the `LogSlice` is [self-consistent](https://github.com/cockroachdb/cockroach/blob/0866efef94ddde21ae8d273f56dabb1bb46f6c71/pkg/raft/types.go#L64-L100). The TODO captures the need to update the leader term here to the one known to the upper layer, instead of making it up.

I could also leave `LogSlice.term` at zero because it's not used here. But it needs to be set for the `rac2` tests that call `LogSnapshot.LogSlice()`, in one of the next commits.

Made this code simpler for now by setting `LogSlice.term` to the last entry term.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 6 files at r10, 3 of 11 files at r12, 2 of 7 files at r15, 8 of 9 files at r16, 2 of 2 files at r17, 5 of 6 files at r18, 5 of 5 files at r19.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132600#-:-O9UkLARCwnD5U-3aXz-:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

___
*[`pkg/raft/storage.go` line 199 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/132600#-O9RSxiaEpdqQ3Ha6P4m:-O9UbTNIDYJYs_SSbuwo:b-uv4ta) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ac331ba29db23cea6b1f1a685860f2228639ac5/pkg/raft/storage.go#L199)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

This should be `i < ms.ls.prev.index` as is. For the `prev` entry, we should be able to return its term for log matching purposes. E.g. if we construct a `MsgApp` starting at the first log entry, we also need to set `MsgApp.LogTerm` to the term of the preceding entry.

https://github.com/cockroachdb/cockroach/blob/0866efef94ddde21ae8d273f56dabb1bb46f6c71/pkg/raft/storage.go#L75-L79

I could reinstate the `firstIndex()` method, but I didn't find it much useful myself because `prev` is descriptive enough (the entry before the first), and all the checks can be done against `prev` directly. This follows the convention instated by the `LogSlice` struct and many uses of it in this package.
</blockquote></details>

Thanks for the clarification.
___
*[`pkg/raft/storage.go` line 251 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/132600#-O9RUUpi3xhL7yd-K3hQ:-O9UdA67BPDqR5oe0t3F:b2nhb2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ac331ba29db23cea6b1f1a685860f2228639ac5/pkg/raft/storage.go#L251)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

That depends on which term we consider:

- If it's the last entry term, it can regress.
- If it's the "leader term", it can not.

Here, `LogSlice.term` is supposed to be the leader term that can not regress. But it's not passed in from the caller yet, and also not used for anything internally in this `MemoryStorage` (though it should in the future). So I just update it to something so that the `LogSlice` is [self-consistent](https://github.com/cockroachdb/cockroach/blob/0866efef94ddde21ae8d273f56dabb1bb46f6c71/pkg/raft/types.go#L64-L100). The TODO captures the need to update the leader term here to the one known to the upper layer, instead of making it up.

I could also leave `LogSlice.term` at zero because it's not used here. But it needs to be set for the `rac2` tests that call `LogSnapshot.LogSlice()`, in one of the next commits.

Made this code simpler for now by setting `LogSlice.term` to the last entry term.
</blockquote></details>

Ack
___
*[`pkg/raft/storage.go` line 150 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/132600#-O9UazX_2rTrU1CBNE9s:-O9UazX_2rTrU1CBNE9t:b-w6hlic) ([raw file](https://github.com/cockroachdb/cockroach/blob/40304aee1321cc3688436aac83093b9e233e2ea5/pkg/raft/storage.go#L150)):*
> ```Go
> 	//
> 	// TODO(pav-kv): the term field of the logSlice is populated with best effort
> 	// to keep the logSlice valid, but it must be sourced from the upper layer.
> ```

What is the actual todo here? Is it to make it less best effort?
___
*[`pkg/raft/storage.go` line 278 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/132600#-O9Ue7rV90_EDuCZgBXh:-O9Ue7rV90_EDuCZgBXi:b5gic7j) ([raw file](https://github.com/cockroachdb/cockroach/blob/40304aee1321cc3688436aac83093b9e233e2ea5/pkg/raft/storage.go#L278)):*
> ```Go
> 		ms.snapshot.Metadata.ConfState = *cs
> 	}
> 	ms.snapshot.Data = data
> ```

This method is not part of `raft.Storage` so I had to guess based on the code that `CreateSnapshot` means that this is installing a snapshot at index i. 
It's odd that `ms.ls` is not being modified to truncate the log, to start from `i+1`. I suppose this is because `CreateSnapshot` is being used for installing new versions of the state machine, and will happen with each state machine application, and has nothing to do with truncation/compaction. Is my understanding correct?
___
*[`pkg/raft/storage.go` line 293 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/132600#-O9UfJdv0gj8ZesyJsY8:-O9UfJdv0gj8ZesyJsY9:bo506j9) ([raw file](https://github.com/cockroachdb/cockroach/blob/40304aee1321cc3688436aac83093b9e233e2ea5/pkg/raft/storage.go#L293)):*
> ```Go
> 		raftlogger.GetLogger().Panicf("compact %d is out of bound lastindex(%d)", index, last)
> 	}
> 	ms.ls = ms.ls.forward(index)
> ```

Shouldn't this also check that there is a snapshot at index >= index, i.e., we are not creating a gap between the snapshot and the LogSlice? I suppose the method comment about `raftLog.applied` means that a higher layer is guaranteeing that, though I don't see `raftLog` as a member of `MemoryStorage` so unsure how to interpret it.
___
*[`pkg/raft/storage.go` line 324 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/132600#-O9UgfqgDWK8UJ1Hsy0z:-O9UgfqgDWK8UJ1Hsy1-:b-celfpx) ([raw file](https://github.com/cockroachdb/cockroach/blob/40304aee1321cc3688436aac83093b9e233e2ea5/pkg/raft/storage.go#L324)):*
> ```Go
> 		prefix := ms.ls.sub(ms.ls.prev.index, first-1)
> 		// NB: protect the suffix of the old slice from rewrites.
> 		ms.ls.entries = append(prefix[:len(prefix):len(prefix)], entries...)
> ```

Is this code using a cap of `len(prefix)` to make a shallow copy of `LogSlice` immutable?
Is that a general property of all `LogSlice`s, and if yes, should it be documented where `LogSlice` is declared?
___
*[`pkg/raft/storage.go` line 226 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/132600#-O9UhiWJ8ZTlmYDqqOSM:-O9UhiWJ8ZTlmYDqqOSN:b-x19gji) ([raw file](https://github.com/cockroachdb/cockroach/blob/87e47acc97cc3a5877e061326792201d1cb217b9/pkg/raft/storage.go#L226)):*
> ```Go
> func (ms *MemoryStorage) LogSnapshot() LogStorageSnapshot {
> 	// Copy the log slice, and protect it from appends. MemoryStorage never
> 	// overwrites entries in the log slice, so this is sufficient to get an
> ```

That partially answers my previous question.

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132600)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli and @sumeerbhola)

___
*[`pkg/raft/storage.go` line 150 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/132600#-O9UazX_2rTrU1CBNE9s:-O9Unvtd1D2yTdECBSPu:bhooh1v) ([raw file](https://github.com/cockroachdb/cockroach/blob/40304aee1321cc3688436aac83093b9e233e2ea5/pkg/raft/storage.go#L150)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

What is the actual todo here? Is it to make it less best effort?
</blockquote></details>

Yes, make it reflect the actual "last accepted term" / "leader term" of the log. Right now it's conservatively set to the last entry term.
___
*[`pkg/raft/storage.go` line 278 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/132600#-O9Ue7rV90_EDuCZgBXh:-O9UqSxJ7NZRuzLDczuW:b-jj3o6f) ([raw file](https://github.com/cockroachdb/cockroach/blob/40304aee1321cc3688436aac83093b9e233e2ea5/pkg/raft/storage.go#L278)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This method is not part of `raft.Storage` so I had to guess based on the code that `CreateSnapshot` means that this is installing a snapshot at index i. 
It's odd that `ms.ls` is not being modified to truncate the log, to start from `i+1`. I suppose this is because `CreateSnapshot` is being used for installing new versions of the state machine, and will happen with each state machine application, and has nothing to do with truncation/compaction. Is my understanding correct?
</blockquote></details>

Yeah, the log is not necessarily in sync with the state machine / snapshot. Also, this method usually comes together with a subsequent `Compact`.
Right now it's only used in tests (as well as the entire `MemoryStorage` struct).
___
*[`pkg/raft/storage.go` line 293 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/132600#-O9UfJdv0gj8ZesyJsY8:-O9UpdjrE4FlKZOH0R3i:bqkl9av) ([raw file](https://github.com/cockroachdb/cockroach/blob/40304aee1321cc3688436aac83093b9e233e2ea5/pkg/raft/storage.go#L293)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Shouldn't this also check that there is a snapshot at index >= index, i.e., we are not creating a gap between the snapshot and the LogSlice? I suppose the method comment about `raftLog.applied` means that a higher layer is guaranteeing that, though I don't see `raftLog` as a member of `MemoryStorage` so unsure how to interpret it.
</blockquote></details>

Yeah, it's ensured at the higher level: `applied >= snapshot.Index`. If `applied > snapshot.Index`, it should be in theory possible to compact at index > `snapshot.Index`, esp. when we separate the raft log storage from state machine storage. The only requirement is that the compaction is <= the durable `applied` index.
___
*[`pkg/raft/storage.go` line 324 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/132600#-O9UgfqgDWK8UJ1Hsy0z:-O9UoqAv-I-HJBX2fPmi:b-wdgqg5) ([raw file](https://github.com/cockroachdb/cockroach/blob/40304aee1321cc3688436aac83093b9e233e2ea5/pkg/raft/storage.go#L324)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Is this code using a cap of `len(prefix)` to make a shallow copy of `LogSlice` immutable?
Is that a general property of all `LogSlice`s, and if yes, should it be documented where `LogSlice` is declared?
</blockquote></details>

Yes, `LogSlice` is immutable. The only allowed operation is appending to it. Will pop a note about this in `LogSlice`definition.

This capping is a self-defence mechanism of `MemoryStorage`. If the caller appends to this slice (and it may happen inside the `LogSnapshot.LogSlice()` call when we stitch together the storage part of the slice with the in-memory `unstable` slice), the original slice in `MemoryStorage` does not get corrupted.
___
*[`pkg/raft/storage.go` line 226 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/132600#-O9UhiWJ8ZTlmYDqqOSM:-O9Uqxlb43gaDbfKriKR:b-lrhsfc) ([raw file](https://github.com/cockroachdb/cockroach/blob/87e47acc97cc3a5877e061326792201d1cb217b9/pkg/raft/storage.go#L226)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

That partially answers my previous question.
</blockquote></details>

I'll clarify the comment: it should say that there is both self-defence from the `MemoryStorage` (because the caller can append to the slice), but the caller is also defended from appends that `MemoryStorage` does to this slice.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132600#-:-O9V43KB-gpDZfvLj0k5:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

**Comment by pav-kv** [comment]
bors r=sumeerbhola

**Comment by sumeerbhola** [comment]
blathers backport 24.3

**Pull request merged**
