### PR TITLE
sql: add authentication_method to SHOW SESSIONS

### LINKED ISSUE #125099: ldap: extend show sessions to show who is authenticated via LDAP
We should extend SHOW SESSIONS to note which users are authenticated via LDAP.

Currently, show sessions shows:
```
root@localhost:29000/defaultdb> show sessions;
  node_id |            session_id            | status | user_name | client_address | application_name |    active_queries     | last_active_query |         session_start         |      active_query_start       | num_txns_executed | trace_id | goroutine_id
----------+----------------------------------+--------+-----------+----------------+------------------+-----------------------+-------------------+-------------------------------+-------------------------------+-------------------+----------+---------------
        1 | 17f6155404927c480000000000000001 | ACTIVE | root      | [::1]:53416    | $ cockroach sql  | SHOW CLUSTER SESSIONS | SHOW database     | 2024-09-17 16:35:57.741434+00 | 2024-09-17 16:35:59.787579+00 |                 6 |        0 |         2976
(1 row)

Time: 10ms total (execution 9ms / network 0ms)
```
We could add a column here that shows how the user is authenticated, eg: userpass vs ldap vs cert etc.

Jira issue: CRDB-39235

Epic CRDB-33829

### PR DESCRIPTION
**Pull request by rafiss**
Release note (sql change): The SHOW SESSIONS command was changed to
include an `authentication_method` column in the result. This column
will show the method used to authenticate the session, e.g., password,
cert, LDAP, etc.

fixes https://github.com/cockroachdb/cockroach/issues/125099
Release note: None

### CODE REVIEW

**Review by spilchen — COMMENTED** [review]
Looks good to me! I just had one comment/question. Since you mentioned you’re planning to add tests, I’ll hold off on approving it for now and will take another look once they’re in.

> Reviewed 2 of 2 files at r1, 19 of 19 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131625#-:-O8DrlzX4dz_OZBMVxn-:b-v5hub0)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi, @rafiss, and @souravcrl)

___
*[`pkg/sql/delegate/show_sessions.go` line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131625#-O8Dql645CRwUCHtF_Wy:-O8Dql645CRwUCHtF_Wz:b-3gsbh2) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f70f797e7bc6183dd2417417da7cff6fd8bef08/pkg/sql/delegate/show_sessions.go#L21)):*
> ```Go
> 
> func (d *delegator) delegateShowSessions(n *tree.ShowSessions) (tree.Statement, error) {
> 	columns := `node_id, session_id, status, user_name, authentication_method, client_address, application_name, active_queries,
> ```

Is there a rule that requires new columns to be added to the end of the column list? Otherwise, couldn’t this break clients that rely on accessing columns by their index?

**Review by fqazi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 19 of 19 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131625#-:-O8DtHUB0bmg3_TEEOib:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rafiss and @souravcrl)

**Review by rafiss — COMMENTED** [review]
@spilchen the tests are now in authorization_ldap_test.go, so this is ready for a review

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131625#-:-O8DyjO0ClOmxn5aXOgE:bi0qlh9)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @souravcrl and @spilchen)

___
*[`pkg/sql/delegate/show_sessions.go` line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131625#-O8Dql645CRwUCHtF_Wy:-O8DynjX2u6f67YO_zjy:b-2g1wx0) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f70f797e7bc6183dd2417417da7cff6fd8bef08/pkg/sql/delegate/show_sessions.go#L21)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Is there a rule that requires new columns to be added to the end of the column list? Otherwise, couldn’t this break clients that rely on accessing columns by their index?
</blockquote></details>

normally, yes, but `SHOW SESSIONS` is not considered a "stable" API according to our docs: https://www.cockroachlabs.com/docs/stable/api-support-policy#apis

unlike most SQL statements, it's intended for manual usage by humans, not by programmatic access

**Review by rafiss — COMMENTED** [review]
ah i mixed up PRs. authorization_ldap_test.go is in my other PR: https://github.com/cockroachdb/cockroach/pull/131043

i'll add a few more tests in this PR in the datadriven authentication tests

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131625#-:-O8DzONz6mwtzuXFqQ2r:b-thpmyj)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @souravcrl and @spilchen)

**Review by rafiss — COMMENTED** [review]
tests have been added now

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131625#-:-O8EDVIm0WKoViugw4be:b-hh20dm)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @fqazi, @souravcrl, and @spilchen)

**Review by spilchen — APPROVED** [review]
:lgtm:

> Reviewed 19 of 19 files at r3, 25 of 25 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131625#-:-O8EG8iM-xYwBcP2VK6D:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @souravcrl)

___
*[`pkg/sql/delegate/show_sessions.go` line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/131625#-O8Dql645CRwUCHtF_Wy:-O8EETNA6EQliBx7LKZ2:bx7ggcu) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f70f797e7bc6183dd2417417da7cff6fd8bef08/pkg/sql/delegate/show_sessions.go#L21)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

normally, yes, but `SHOW SESSIONS` is not considered a "stable" API according to our docs: https://www.cockroachlabs.com/docs/stable/api-support-policy#apis

unlike most SQL statements, it's intended for manual usage by humans, not by programmatic access
</blockquote></details>

Good to know. Thanks for the explanation.

**Comment by rafiss** [comment]
tftr!

bors r+

**Pull request merged**
