### PR TITLE
kv: Avoid intermediate slice when adding intents to txnMetadata

### PR DESCRIPTION
**Pull request by nvb**
This removed a TODO.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5608)

### CODE REVIEW

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[kv/txn_coord_sender.go, line 795 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5608#-KDpbHQoRCK6yuHB9XB_:-KDpbHQoRCK6yuHB9XBa:-447261463) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c42040217590ad08c2dc33700a739b2e6b82d68/kv/txn_coord_sender.go#L795)):*
Nice to get rid of the `|| newTxn.Writing` here (I think it's correct with the cleanup we've been doing in Store and below).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5608#-:-KDpcmmIchaXww07BfsF:1417088721)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[kv/txn_coord_sender.go, line 795 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5608#-KDpbHQoRCK6yuHB9XB_:-KDpeXSs_VRXjDddrMrZ:1935641594) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c42040217590ad08c2dc33700a739b2e6b82d68/kv/txn_coord_sender.go#L795)):*
That still exists, it's just moved up to `else if pErr == nil || newTxn.Writing`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5608)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[kv/txn_coord_sender.go, line 795 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5608#-KDpbHQoRCK6yuHB9XB_:-KDpf5CpOlwwhkvA7yUz:-1618594027) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c42040217590ad08c2dc33700a739b2e6b82d68/kv/txn_coord_sender.go#L795)):*
Ok, makes sense there actually.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5608)*

**Comment by nvanbenschoten** [comment]
Thanks for the review!

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5608#-:-KDpgGEYJDvAPYGtAgLg:-588504495)*

**Pull request merged**
