### PR TITLE
kvclient: move RangeCache to dedicated package

### PR DESCRIPTION
**Pull request by andreimatei**
It used to live in kvclient/kvcoord, with some interfaces in kvbase. Now
it lives in kvclient/rngcache, and we can get rid of those interafaces;
the cache's interface is sufficiently split between exported and private
parts.
Also rename from RangeDescriptorCache to RangeCache, to acknowledge that
this cache grew in scope beyond just descriptors.

The patch is almost entirely mechanical, with the exception of:
- changing the methods in the cache that were returning the
  kvbase.RangeCacheEntry interface to return directly *CacheEntry.
- exposing some cache methods for tests that stay in the DistSender's
  package
- mucking around with the IntentResolver, which sometimes wants to mock
  out the cache. The IntentResolver keeps its own interface for the
  cache now.

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
sniped by my love of new packages

> Reviewed 2 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53361#-:-MFYfGR35mMvD0-eqVmE:bkrz4r1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/kvclient/rngcache/range_cache.go, line 177 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53361#-MFYe9Re6NLORbjEwvzt:-MFYe9Re6NLORbjEwvzu:b5fwvsz) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e9052473149f5e098074562fc91ca41d7b7e53c/pkg/kv/kvclient/rngcache/range_cache.go#L177)):*
> ```Go
> // uses the given RangeDescriptorDB as the underlying source of range
> // descriptors.
> func NewRangeDescriptorCache(
> ```

nit: rename to `NewRangeCache` or, if you so please, just `New`
___
*[pkg/kv/kvclient/rngcache/range_cache.go, line 1073 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53361#-MFYeOrG5jzVstN5E2Sy:-MFYeOrH5_unuhfYTPcj:bgnjr0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e9052473149f5e098074562fc91ca41d7b7e53c/pkg/kv/kvclient/rngcache/range_cache.go#L1073)):*
> ```Go
> 
> // SetDB allows tests to override the database.
> func (rc *RangeCache) SetDB(db RangeDescriptorDB) {
> ```

Maybe call this `TestingSetDB` just to make it super clear that it exists for testing?

I'm generally suspect here, I feel like if a test wants to set the DB it can create a db implementation that points to another db. I feel like you can constrain this to the distsender tests. A non-directly applicable example would be to inject something like:

```
type settableDB struct {
     rngcache.RangeDescriptorDB
}

func (s *settableDB) SetDB(db rngcache.RangeDescriptorDB) {
    s.RangeDescriptorDB = db
}
```

**Review by nvb — COMMENTED** [review]
> Reviewed 22 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53361)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @andreimatei)

___
*[pkg/kv/kvserver/store.go, line 1422 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53361#-MFlBpLvAGtmb0AhGOpK:-MFlBpLvAGtmb0AhGOpL:b6edkxu) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e9052473149f5e098074562fc91ca41d7b7e53c/pkg/kv/kvserver/store.go#L1422)):*
> ```Go
> 	var intentResolverRangeCache intentresolver.RangeCache
> 	rngCache := s.cfg.RangeDescriptorCache
> 	if rngCache != nil {
> ```

nit: `if s.cfg.RangeDescriptorCache != nil { ... }`

The local var is confusing.
___
*[pkg/kv/kvclient/rngcache/range_cache.go, line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53361#-MFlB2zMEz7vAkrc4z-L:-MFlB2zMEz7vAkrc4z-M:b-tasirq) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e9052473149f5e098074562fc91ca41d7b7e53c/pkg/kv/kvclient/rngcache/range_cache.go#L11)):*
> ```Go
> // licenses/APL.txt.
> 
> package rngcache
> ```

You don't like `kvclient/rangecache`? Seems a bit strange to avoid the vowels in one word but not the other.
___
*[pkg/kv/kvclient/rngcache/range_cache.go, line 177 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53361#-MFYe9Re6NLORbjEwvzt:-MFlBFs24eHEs5faYQC4:b-gull23) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e9052473149f5e098074562fc91ca41d7b7e53c/pkg/kv/kvclient/rngcache/range_cache.go#L177)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: rename to `NewRangeCache` or, if you so please, just `New`
</blockquote></details>

+1 to either.

Also, should `RangeCache` just be `Cache`, given the name of this package? I don't have strong feelings about that one.

**Review by andreimatei — COMMENTED** [review]
OK, one more time with feeling.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53361#-:-MMcDK8I6S48urh3WOtW:b-zcgp8r)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/kv/kvserver/store.go, line 1422 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53361#-MFlBpLvAGtmb0AhGOpK:-MMcCaxD8aED6fj1atLr:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e9052473149f5e098074562fc91ca41d7b7e53c/pkg/kv/kvserver/store.go#L1422)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: `if s.cfg.RangeDescriptorCache != nil { ... }`

The local var is confusing.
</blockquote></details>

done
___
*[pkg/kv/kvclient/rngcache/range_cache.go, line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53361#-MFlB2zMEz7vAkrc4z-L:-MMcBeok8cE_fTxjpQV3:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e9052473149f5e098074562fc91ca41d7b7e53c/pkg/kv/kvclient/rngcache/range_cache.go#L11)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

You don't like `kvclient/rangecache`? Seems a bit strange to avoid the vowels in one word but not the other.
</blockquote></details>

done
___
*[pkg/kv/kvclient/rngcache/range_cache.go, line 177 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53361#-MFYe9Re6NLORbjEwvzt:-MMcBh_y-gt-PJwo_8As:bpctpw5) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e9052473149f5e098074562fc91ca41d7b7e53c/pkg/kv/kvclient/rngcache/range_cache.go#L177)):*
went with `NewRangeCache`

> Also, should RangeCache just be Cache, given the name of this package?

I wouldn't say so...
___
*[pkg/kv/kvclient/rngcache/range_cache.go, line 1073 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53361#-MFYeOrG5jzVstN5E2Sy:-MMcC7arE1S9GRJhs6PP:b-eybtgl) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e9052473149f5e098074562fc91ca41d7b7e53c/pkg/kv/kvclient/rngcache/range_cache.go#L1073)):*
> Maybe call this TestingSetDB just to make it super clear that it exists for testing?

done

I'm not too keen on the rest, unless you insist.

**Review by ajwerner — COMMENTED** [review]
I like it. Make it build and I'll stamp it. 

> Reviewed 5 of 24 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53361#-:-MNOpKnLASd3E_zuf8Ya:b-tc3quk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

**Review by andreimatei — COMMENTED** [review]
Now it should build.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53361#-:-MNf0SUGB5fUCwam3STP:bpyjnrb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

**Review by ajwerner — APPROVED** [review]
:lgtm: merge it before it skews

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53361#-:-MO7cJf-E2tfK7Xaa1Vo:b-p0jr8p)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

**Review by andreimatei — COMMENTED** [review]
TFTR

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53361#-:-MO7cw_015sPWjWMaCf8:b-4as1hm)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

**Pull request merged**
