### PR TITLE
roachtest: disable journaling in dmsetupDiskStaller

### LINKED ISSUE #129619: roachtest: failover/non-system/disk-stall failed
roachtest.failover/non-system/disk-stall [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/16608098?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/16608098?buildTab=artifacts#/failover/non-system/disk-stall) on release-23.1 @ [53c2718ea13bfe632da68d25c64182fdf9648d80](https://github.com/cockroachdb/cockroach/commits/53c2718ea13bfe632da68d25c64182fdf9648d80):

```
(disk_stall.go:303).Setup: full command output in run_131337.075895949_n1-7_echo-0-sudo-blockdev.log: COMMAND_PROBLEM: exit status 1
test artifacts and logs in: /artifacts/failover/non-system/disk-stall/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_cpu=2</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-16608098/failover-non-system-disk-stall/1724591615635/1724591748169)

</p>
</details>
/cc @cockroachdb/kv-triage
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*failover/non-system/disk-stall.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-41620

### PR DESCRIPTION
**Pull request by tbg**
The journaling kernel threads can interfere with the `dmsetup create`
call.

See https://github.com/cockroachdb/cockroach/issues/129619#issuecomment-2316147244.

Fixes #129619.

Epic: none
Release note: None

### CODE REVIEW

**Review by herkolategan — APPROVED** [review]
Nice, thanks for delving deeper into the issue! Hopefully this reduces the flakes.

**Review by itsbilal — APPROVED** [review]
LGTM

**Comment by tbg** [comment]
> You may want to re-enable journaling in Cleanup() in case the cluster is reused for other tests. Some of the tests [opt out of reuse](https://github.com/cockroachdb/cockroach/blob/33d0af019285722c5aacb22495015abe0c5e43f4/pkg/cmd/roachtest/tests/failover.go#L142-L144), but perhaps not all.

Good idea, done. Also added a check that we're not reusing the cluster whenever `(eitherDiskStaller).Setup()` is called. I audited and all tests seem to already opt out, but you never know.

I'll run another smoke test and merge later today should all be well.

**Comment by tbg** [comment]
> 2024/09/03 15:00:02 test_runner.go:1183: --- PASS: failover/non-system/disk-stall (1226.22s)

bors r+

**Pull request merged**
