### PR TITLE
sql: make the "native" KV benchmarks run over the network

### PR DESCRIPTION
**Pull request by petermattis**
The "native" versions of the KV benchmarks were not actually performing
operations over the network as TestServer.DB() is wrapped around the
local node's TxnCoordSender. Cheating cheater. This made the "native" KV
benchmarks look a lot better than reality.

Note that the "native" operations still scale better than the SQL
operations which is indicative of the per-row overhead for SQL.

```
name                     old time/op    new time/op    delta
KVInsert1_Native-32         264µs ± 1%     635µs ± 1%  +140.44%         (p=0.000 n=9+10)
KVInsert1_SQL-32            495µs ± 1%     496µs ± 2%      ~           (p=0.739 n=10+10)
KVInsert10_Native-32        477µs ± 2%     887µs ± 1%   +86.08%        (p=0.000 n=10+10)
KVInsert10_SQL-32           977µs ± 1%     979µs ± 2%      ~           (p=0.481 n=10+10)
KVInsert100_Native-32      2.32ms ± 1%    3.04ms ± 2%   +31.29%        (p=0.000 n=10+10)
KVInsert100_SQL-32         5.39ms ± 2%    5.46ms ± 4%      ~            (p=0.055 n=8+10)
KVInsert1000_Native-32     21.8ms ± 2%    25.0ms ± 3%   +14.45%         (p=0.000 n=9+10)
KVInsert1000_SQL-32        55.6ms ± 3%    55.5ms ± 5%      ~           (p=0.853 n=10+10)
KVInsert10000_Native-32     248ms ± 7%     283ms ± 7%   +14.04%        (p=0.000 n=10+10)
KVInsert10000_SQL-32        725ms ± 7%     731ms ± 4%      ~           (p=0.529 n=10+10)
KVUpdate1_Native-32         345µs ± 2%    1002µs ± 1%  +190.16%        (p=0.000 n=10+10)
KVUpdate1_SQL-32            677µs ± 3%     676µs ± 4%      ~           (p=0.912 n=10+10)
KVUpdate10_Native-32        773µs ± 2%    1576µs ± 2%  +103.70%        (p=0.000 n=10+10)
KVUpdate10_SQL-32          1.22ms ± 2%    1.23ms ± 2%      ~           (p=0.853 n=10+10)
KVUpdate100_Native-32      4.14ms ± 2%    5.56ms ± 1%   +34.11%        (p=0.000 n=10+10)
KVUpdate100_SQL-32         5.80ms ± 2%    5.88ms ± 3%      ~           (p=0.089 n=10+10)
KVUpdate1000_Native-32     38.7ms ± 2%    45.1ms ± 2%   +16.56%        (p=0.000 n=10+10)
KVUpdate1000_SQL-32        51.4ms ± 3%    52.5ms ± 3%    +2.12%        (p=0.002 n=10+10)
KVUpdate10000_Native-32     473ms ± 8%     525ms ± 3%   +10.91%         (p=0.000 n=10+9)
KVUpdate10000_SQL-32        660ms ± 2%     678ms ± 9%      ~            (p=0.278 n=9+10)
KVDelete1_Native-32         264µs ± 2%     626µs ± 3%  +137.33%        (p=0.000 n=10+10)
KVDelete1_SQL-32            533µs ± 3%     535µs ± 2%      ~            (p=0.604 n=10+9)
KVDelete10_Native-32        521µs ± 2%     931µs ± 2%   +78.94%        (p=0.000 n=10+10)
KVDelete10_SQL-32           900µs ± 3%     910µs ± 3%      ~           (p=0.218 n=10+10)
KVDelete100_Native-32      2.53ms ± 3%    3.23ms ± 1%   +27.79%        (p=0.000 n=10+10)
KVDelete100_SQL-32         3.84ms ± 3%    3.85ms ± 2%      ~           (p=0.739 n=10+10)
KVDelete1000_Native-32     22.5ms ± 2%    25.6ms ± 2%   +14.20%        (p=0.000 n=10+10)
KVDelete1000_SQL-32        34.4ms ± 5%    34.2ms ± 2%      ~            (p=0.780 n=9+10)
KVDelete10000_Native-32     264ms ± 5%     292ms ± 8%   +10.57%        (p=0.000 n=10+10)
KVDelete10000_SQL-32        457ms ± 3%     451ms ± 6%      ~            (p=0.497 n=9+10)
KVScan1_Native-32          75.4µs ± 2%   372.9µs ± 2%  +394.38%        (p=0.000 n=10+10)
KVScan1_SQL-32              199µs ± 3%     197µs ± 3%      ~            (p=0.356 n=10+9)
KVScan10_Native-32          110µs ± 2%     439µs ± 2%  +298.09%        (p=0.000 n=10+10)
KVScan10_SQL-32             292µs ± 2%     292µs ± 3%      ~           (p=0.631 n=10+10)
KVScan100_Native-32         360µs ± 5%     814µs ± 3%  +126.19%        (p=0.000 n=10+10)
KVScan100_SQL-32           1.05ms ± 5%    1.05ms ± 7%      ~           (p=0.579 n=10+10)
KVScan1000_Native-32       2.66ms ± 5%    4.11ms ± 3%   +54.33%         (p=0.000 n=10+9)
KVScan1000_SQL-32          8.43ms ± 4%    8.30ms ± 4%      ~           (p=0.218 n=10+10)
KVScan10000_Native-32      28.8ms ± 3%    41.9ms ± 1%   +45.40%          (p=0.000 n=9+9)
KVScan10000_SQL-32         82.9ms ± 3%    82.9ms ± 5%      ~           (p=0.853 n=10+10)
```

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6090)

### CODE REVIEW

**Comment by petermattis** [comment]
Below is a comparison of Native (old) vs SQL (new) with a patch to SQL so that it doesn't write out the sentinel key for a row. This isn't a valid optimization by itself, but indicative of what could be achieved if we did something like [column groups](https://github.com/cockroachdb/cockroach/pull/3435) or skipped writing the sentinel of the table had a non-NULL/non-primary key column. 

```
name              old time/op    new time/op    delta
KVInsert1-32         626µs ± 1%     467µs ± 1%   -25.36%   (p=0.000 n=10+7)
KVInsert10-32        877µs ± 1%     761µs ± 1%   -13.28%   (p=0.000 n=10+9)
KVInsert100-32      3.01ms ± 1%    3.26ms ± 1%    +8.43%  (p=0.000 n=10+10)
KVInsert1000-32     24.9ms ± 3%    28.1ms ± 2%   +13.15%  (p=0.000 n=10+10)
KVInsert10000-32     266ms ± 6%     333ms ± 7%   +25.33%  (p=0.000 n=10+10)
KVUpdate1-32         992µs ± 1%     651µs ± 3%   -34.38%    (p=0.000 n=9+9)
KVUpdate10-32       1.59ms ± 1%    1.19ms ± 2%   -24.95%  (p=0.000 n=10+10)
KVUpdate100-32      5.68ms ± 2%    5.45ms ± 1%    -3.98%   (p=0.000 n=10+9)
KVUpdate1000-32     44.9ms ± 2%    48.8ms ± 4%    +8.77%  (p=0.000 n=10+10)
KVUpdate10000-32     522ms ± 3%     584ms ± 8%   +12.02%   (p=0.000 n=9+10)
KVDelete1-32         620µs ± 1%     527µs ± 3%   -14.95%   (p=0.000 n=10+9)
KVDelete10-32        921µs ± 1%     871µs ± 1%    -5.51%   (p=0.000 n=10+9)
KVDelete100-32      3.20ms ± 1%    3.66ms ± 2%   +14.18%    (p=0.000 n=9+9)
KVDelete1000-32     25.3ms ± 1%    31.4ms ± 3%   +23.99%  (p=0.000 n=10+10)
KVDelete10000-32     285ms ± 4%     390ms ± 4%   +36.80%  (p=0.000 n=10+10)
KVScan1-32           367µs ± 3%     193µs ± 4%   -47.54%  (p=0.000 n=10+10)
KVScan10-32          438µs ± 3%     256µs ± 3%   -41.66%  (p=0.000 n=10+10)
KVScan100-32         823µs ± 3%     717µs ± 3%   -12.83%   (p=0.000 n=10+9)
KVScan1000-32       4.21ms ± 6%    5.01ms ± 2%   +18.93%  (p=0.000 n=10+10)
KVScan10000-32      42.3ms ± 1%    49.3ms ± 3%   +16.71%   (p=0.000 n=9+10)
```

You should notice a pattern that SQL performs better when operating on small numbers of rows while Native performs better on large numbers. AFAICT, this is due to a) the Native network protocol (gRPC) is quite a bit slower than pgwire and b) the SQL execution engine performs more allocations per row which seems to hurt performance as the number of rows gets large. I'm reasonably confident that we can fix the allocation issue. 

Btw, this is how Native compares to SQL when the SQL row sentinel is present:

```
name              old time/op    new time/op    delta
KVInsert1-32         635µs ± 1%     496µs ± 2%   -21.87%  (p=0.000 n=10+10)
KVInsert10-32        887µs ± 1%     979µs ± 2%   +10.41%  (p=0.000 n=10+10)
KVInsert100-32      3.04ms ± 2%    5.46ms ± 4%   +79.38%  (p=0.000 n=10+10)
KVInsert1000-32     25.0ms ± 3%    55.5ms ± 5%  +122.19%  (p=0.000 n=10+10)
KVInsert10000-32     283ms ± 7%     731ms ± 4%  +158.81%  (p=0.000 n=10+10)
KVUpdate1-32        1.00ms ± 1%    0.68ms ± 4%   -32.48%  (p=0.000 n=10+10)
KVUpdate10-32       1.58ms ± 2%    1.23ms ± 2%   -22.10%  (p=0.000 n=10+10)
KVUpdate100-32      5.56ms ± 1%    5.88ms ± 3%    +5.85%  (p=0.000 n=10+10)
KVUpdate1000-32     45.1ms ± 2%    52.5ms ± 3%   +16.40%  (p=0.000 n=10+10)
KVUpdate10000-32     525ms ± 3%     678ms ± 9%   +29.20%   (p=0.000 n=9+10)
KVDelete1-32         626µs ± 3%     535µs ± 2%   -14.63%   (p=0.000 n=10+9)
KVDelete10-32        931µs ± 2%     910µs ± 3%    -2.31%  (p=0.002 n=10+10)
KVDelete100-32      3.23ms ± 1%    3.85ms ± 2%   +19.30%  (p=0.000 n=10+10)
KVDelete1000-32     25.6ms ± 2%    34.2ms ± 2%   +33.51%  (p=0.000 n=10+10)
KVDelete10000-32     292ms ± 8%     451ms ± 6%   +54.74%  (p=0.000 n=10+10)
KVScan1-32           373µs ± 2%     197µs ± 3%   -47.21%   (p=0.000 n=10+9)
KVScan10-32          439µs ± 2%     292µs ± 3%   -33.64%  (p=0.000 n=10+10)
KVScan100-32         814µs ± 3%    1050µs ± 7%   +29.02%  (p=0.000 n=10+10)
KVScan1000-32       4.11ms ± 3%    8.30ms ± 4%  +102.25%   (p=0.000 n=9+10)
KVScan10000-32      41.9ms ± 1%    82.9ms ± 5%   +97.67%   (p=0.000 n=9+10)
```

Clearly, processing twice as many key/value pairs is problematic.

**Comment by bdarnell** [comment]
LGTM, but the numbers look fishy. With the row sentinel present SQL is *faster* than raw KV for single-row operations? That doesn't make sense. Even if the GRPC network protocol is slower, the SQL layer still uses GRPC to talk to the KV nodes. In a single-node benchmark SQL can benefit from the local call optimization; is that where SQL's advantage comes from?

There may be something simple we can do for GRPC performance. For example, grpc/grpc-java#256 set `TCP_NODELAY`, but I don't see any calls to `SetNoDelay` in `grpc-go`. (The problem is [more likely to be delayed acks than Nagle's algorithm](https://news.ycombinator.com/item?id=10607422), but poor Nagle tends to get blamed for these things because options to control Nagle's algorithm are much more widespread than options to control ack behavior)

**Comment by petermattis** [comment]
Here is a comparison of Native vs SQL with `COCKROACH_ENABLE_LOCAL_CALLS=0` and the SQL sentinel key enabled:

```
name              old time/op    new time/op    delta
KVInsert1-32         889µs ± 6%     821µs ± 3%    -7.70%  (p=0.000 n=10+10)
KVInsert10-32       1.23ms ± 3%    1.41ms ± 4%   +14.45%  (p=0.000 n=10+10)
KVInsert100-32      3.73ms ± 4%    6.72ms ± 5%   +80.10%  (p=0.000 n=10+10)
KVInsert1000-32     28.8ms ± 4%    63.2ms ± 3%  +119.27%  (p=0.000 n=10+10)
KVInsert10000-32     330ms ± 5%     982ms ±26%  +197.16%  (p=0.000 n=10+10)
KVUpdate1-32        1.54ms ± 5%    1.32ms ± 7%   -14.48%  (p=0.000 n=10+10)
KVUpdate10-32       2.31ms ± 4%    2.14ms ± 4%    -7.42%  (p=0.000 n=10+10)
KVUpdate100-32      7.19ms ± 4%    7.90ms ± 6%    +9.86%  (p=0.000 n=10+10)
KVUpdate1000-32     52.4ms ± 3%    59.9ms ± 5%   +14.24%   (p=0.000 n=9+10)
KVUpdate10000-32     623ms ± 8%     792ms ± 6%   +27.19%  (p=0.000 n=10+10)
KVDelete1-32         895µs ± 4%     845µs ± 5%    -5.67%   (p=0.000 n=9+10)
KVDelete10-32       1.25ms ± 2%    1.28ms ± 3%    +1.81%   (p=0.010 n=10+9)
KVDelete100-32      3.92ms ± 4%    4.77ms ± 6%   +21.60%  (p=0.000 n=10+10)
KVDelete1000-32     28.4ms ± 3%    37.8ms ± 3%   +33.09%   (p=0.000 n=10+9)
KVDelete10000-32     340ms ± 3%     513ms ± 9%   +50.71%   (p=0.000 n=9+10)
KVScan1-32           571µs ± 5%     529µs ± 6%    -7.36%   (p=0.001 n=9+10)
KVScan10-32          727µs ± 4%     710µs ± 7%      ~     (p=0.143 n=10+10)
KVScan100-32        1.21ms ± 3%    1.70ms ± 6%   +40.70%  (p=0.000 n=10+10)
KVScan1000-32       5.39ms ± 5%   11.05ms ± 5%  +104.81%  (p=0.000 n=10+10)
KVScan10000-32      54.3ms ±11%   115.3ms ± 4%  +112.21%  (p=0.000 n=10+10)
```

So SQL is still faster at small row sizes. For the single row case, my suspicion is that the cost of inserting/deleting/scanning 2 keys is outweighed by the slowness of gRPC vs pgwire.

**Comment by bdarnell** [comment]
That doesn't make sense. With local calls disabled, the two versions should be making the same number of GRPC calls, so even if it's slower it should affect both equally.

**Comment by petermattis** [comment]
Eh? With local calls disabled, Native will perform 1 GRPC call from the client (the benchmark) to the gateway and 1 GRPC call from the gateway to the node. SQL will perform 1 pgwire call from the client to the gateway and 1 GRPC all from the gateway to the node.

**Comment by bdarnell** [comment]
Oh, there's still an extra hop because this is going through a client.Sender instead of a DistSender. Got it.

**Comment by petermattis** [comment]
Right. Before this change, the Native benchmarks were going straight through the DistSender and doing one less network hop than the SQL benchmarks which doesn't allow for a fair comparison.

**Pull request merged**
