### PR TITLE
distsql: marshall the origin node in retryable errors

### PR DESCRIPTION
**Pull request by andreimatei**
It's necessary for ReadWithinUncertaintyInterval errors; otherwise we
were failing to find the required updated timestamp when restarting the
txn.

cc @RaduBerinde

### CODE REVIEW

**Comment by RaduBerinde** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15473#-:-KipeoWv6Je0mFwMxe7q:bnfp4nl)*

**Comment by bdarnell** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/roachpb/errors.proto, line 344 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15473#-KipgEpHYequB-b0MJnK:-KipgEpHYequB-b0MJnL:b-yr9fru) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab6d1bf1372574bf4c27139d2b5f8857896e1d14/pkg/roachpb/errors.proto#L344)):*
> ```protobuf
>   optional Transaction transaction = 4;
> 
>   // Node at which the error was generated (zero if does not apply).
> ```

Can you either add more detail about when this applies (or just point back to `Error.origin_node`, which doesn't have any more information but gives us just one place to add it)?

`roachpb.Error` also has a `now` field; should we go ahead and pass that through too? More generally, should DistSQLRetryableError contain an Error instead of an ErrorDetail and all its sibling fields?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15473)*

**Comment by andreimatei** [comment]
Review status: 2 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/roachpb/errors.proto, line 344 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15473#-KipgEpHYequB-b0MJnK:-Kiq-8OYbBzGkn0D0xQ1:b-ysdc5m) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab6d1bf1372574bf4c27139d2b5f8857896e1d14/pkg/roachpb/errors.proto#L344)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Can you either add more detail about when this applies (or just point back to `Error.origin_node`, which doesn't have any more information but gives us just one place to add it)?

`roachpb.Error` also has a `now` field; should we go ahead and pass that through too? More generally, should DistSQLRetryableError contain an Error instead of an ErrorDetail and all its sibling fields?
</blockquote></details>

switched to marshalling the whole pErr

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15473)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15473#-:-KiqBYxTR-O8gBPgzBJL:bnfp4nl)*

**Pull request merged**
