### PR TITLE
ui: default filter on Transaction and Statement pages now exclude internals

### LINKED ISSUE #70544: Allow excluding internal statement, transactions, and sessions in SQL activity pages
We've received feedback that internal statements/transaction/sessions create noise on the overview pages where we should provide a mechanism to filter out these statements by default. This would allow users to quickly identify their application workload.

One possible option is to make the 'App" filter on the overview pages multi-select and have all Apps selected except for '(internal)' by default. Note this would also require us to add the App filter to the sessions page.

+ @Annebirzin 

image

### PR DESCRIPTION
**Pull request by maryliag**
Previously, the default value when no App filter was
selected on Transactions and Statements page, we were showing
all data, now we're excluding internal transaction/statements.

Fixes #70544

Release note (ui change): The default value when no App is selected
on Transactions and Statements filter is now excluding internal
Transactions and Statements.

### CODE REVIEW

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71966)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/transactionsPage/utils.ts, line 174 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71966#-MmxCOxQ20x8q2D35-RY:-MmxCOxQ20x8q2D35-RZ:b51o6ta) ([raw file](https://github.com/cockroachdb/cockroach/blob/92ff0bbde92cb4d54df5bf8b93862ead9c408ac3/pkg/ui/workspaces/cluster-ui/src/transactionsPage/utils.ts#L174)):*
> ```XML
>         }
>         if (apps.includes("(unset)")) {
>           apps.push("");
> ```

Hmm what does this `.push("")` do? it seems like it's just adding another empty string into a list of app filters? 
___
*[pkg/ui/workspaces/cluster-ui/src/transactionsPage/utils.ts, line 184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71966#-MmxBTLV4kd_u1KJgHSv:-MmxBTLV4kd_u1KJgHSw:b-cj9qex) ([raw file](https://github.com/cockroachdb/cockroach/blob/92ff0bbde92cb4d54df5bf8b93862ead9c408ac3/pkg/ui/workspaces/cluster-ui/src/transactionsPage/utils.ts#L184)):*
> ```XML
>       } else {
>         // We don't want to show internal transactions by default.
>         return !isInternal(t);
> ```

super minor style nit: how do you feel about put the default code path a bit higher in the code? (more just my personal style preference so feel free to ignore )

``` typescript

// ...

if (app === "All") {
  return !isInternal(t);
}

// ... codepath when app name is not default  

return (
  (showInternal && isInternal(t))
  t.stats_data.app === filters.app ||
  apps.includes(t.stats_data.app)
);

```
___
*[pkg/ui/workspaces/db-console/src/views/statements/statementsPage.tsx, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71966#-MmxB9Cn3G1HLWOPazGU:-MmxB9Cn3G1HLWOPazGV:b-jw6nmi) ([raw file](https://github.com/cockroachdb/cockroach/blob/92ff0bbde92cb4d54df5bf8b93862ead9c408ac3/pkg/ui/workspaces/db-console/src/views/statements/statementsPage.tsx#L71)):*
> ```XML
> // selectStatements returns the array of AggregateStatistics to show on the
> // StatementsPage, based on if the appAttr route parameter is set.
> export const selectStatements = createSelector(
> ```

can we remove this function and just import from cluster ui ?

**Review by lindseyjin — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71966)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @lindseyjin, and @maryliag)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71966#-MmxAKDQ8PUClMLlO-ZB):*
nit: Previously*/Previosuly

Not sure if typos in commit messages also matter?

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71966)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @lindseyjin)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71966#-MmxAKDQ8PUClMLlO-ZB):*
<details><summary><i>Previously, lindseyjin (Lindsey Jin) wrote…</i></summary><blockquote>

nit: Previously*/Previosuly

Not sure if typos in commit messages also matter? 
</blockquote></details>

Fixed
___
*[pkg/ui/workspaces/cluster-ui/src/transactionsPage/utils.ts, line 174 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71966#-MmxCOxQ20x8q2D35-RY:-MmxGs9dA_08PWSC-jmc:bra6sz7) ([raw file](https://github.com/cockroachdb/cockroach/blob/92ff0bbde92cb4d54df5bf8b93862ead9c408ac3/pkg/ui/workspaces/cluster-ui/src/transactionsPage/utils.ts#L174)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm what does this `.push("")` do? it seems like it's just adding another empty string into a list of app filters? 
</blockquote></details>

The filter is `(unset)`, but the app on the statement will be saved as an empty string, so if the user selects `(unset)` we need to match that with any statement with empty string. We could find the location of `(unset)` in the apps filter array and replace that by the empty string, but a simpler solution is to just add the value that would be able to match
___
*[pkg/ui/workspaces/cluster-ui/src/transactionsPage/utils.ts, line 184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71966#-MmxBTLV4kd_u1KJgHSv:-MmxHttzAzxdLdFhYIEs:b-mdhi60) ([raw file](https://github.com/cockroachdb/cockroach/blob/92ff0bbde92cb4d54df5bf8b93862ead9c408ac3/pkg/ui/workspaces/cluster-ui/src/transactionsPage/utils.ts#L184)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

super minor style nit: how do you feel about put the default code path a bit higher in the code? (more just my personal style preference so feel free to ignore )

``` typescript

// ...

if (app === "All") {
  return !isInternal(t);
}

// ... codepath when app name is not default  

return (
  (showInternal && isInternal(t))
  t.stats_data.app === filters.app ||
  apps.includes(t.stats_data.app)
);

```
</blockquote></details>

I would normally agree and add the default case first, but since this one is not just app == All, it also not null, not undefined, not empty string, so the way is currently is more "clean"  so I'll leave this one as is.
___
*[pkg/ui/workspaces/db-console/src/views/statements/statementsPage.tsx, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71966#-MmxB9Cn3G1HLWOPazGU:-MmxLV8PB0DO5-D92b7H:b-nd8gp4) ([raw file](https://github.com/cockroachdb/cockroach/blob/92ff0bbde92cb4d54df5bf8b93862ead9c408ac3/pkg/ui/workspaces/db-console/src/views/statements/statementsPage.tsx#L71)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

can we remove this function and just import from cluster ui ? 
</blockquote></details>

selectors have to be separate on CC and DB console, those are the files that are duplicated

**Review by matthewtodd — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71966#-:-MmyCwoR-rBR7BUVMltN:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng and @lindseyjin)

**Review by Azhng — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71966#-:-MmyDkOe5LTLLchOtjEH:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @lindseyjin and @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/transactionsPage/utils.ts, line 174 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71966#-MmxCOxQ20x8q2D35-RY:-MmyDR-tDRwN8HSqAJLl:b2rd9px) ([raw file](https://github.com/cockroachdb/cockroach/blob/92ff0bbde92cb4d54df5bf8b93862ead9c408ac3/pkg/ui/workspaces/cluster-ui/src/transactionsPage/utils.ts#L174)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

The filter is `(unset)`, but the app on the statement will be saved as an empty string, so if the user selects `(unset)` we need to match that with any statement with empty string. We could find the location of `(unset)` in the apps filter array and replace that by the empty string, but a simpler solution is to just add the value that would be able to match
</blockquote></details>

I see, that makes sense :+1:
___
*[pkg/ui/workspaces/cluster-ui/src/transactionsPage/utils.ts, line 184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71966#-MmxBTLV4kd_u1KJgHSv:-MmyDdlS8S4HIKbkc8m1:b-8fx2u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/92ff0bbde92cb4d54df5bf8b93862ead9c408ac3/pkg/ui/workspaces/cluster-ui/src/transactionsPage/utils.ts#L184)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

I would normally agree and add the default case first, but since this one is not just app == All, it also not null, not undefined, not empty string, so the way is currently is more "clean"  so I'll leave this one as is.
</blockquote></details>

:+1: 
___
*[pkg/ui/workspaces/db-console/src/views/statements/statementsPage.tsx, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71966#-MmxB9Cn3G1HLWOPazGU:-MmyDhAOCvcUGnW8bat_:bb6mt9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/92ff0bbde92cb4d54df5bf8b93862ead9c408ac3/pkg/ui/workspaces/db-console/src/views/statements/statementsPage.tsx#L71)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

selectors have to be separate on CC and DB console, those are the files that are duplicated
</blockquote></details>

:+1:

**Pull request merged**
