### PR TITLE
kvserver: disallow replica rebalancing to dead nodes

### PR DESCRIPTION
**Pull request by aayushshah15**
The previously existing logic to prevent replica rebalances to dead nodes was
totally broken, and it was never caught because the accompanying unit test was
also broken.

The previous logic had an early return clause during the computation of
diversity stats for _existing replicas_ rather than during the computation of
stats for _potential candidates_. Additionally, the scenario that was
previously created by this unit test was never going to trigger a replica
rebalance, and the unit test would never actually execute any of its checks in
the face of an empty result set.

This commit fixes the check to actually prevent rebalancing to dead nodes and
also re-structures the test.

Noticed while working on #61883.

/cc @cockroachdb/kv

Release note (bug fix): Replica rebalancing could previously sometimes
rebalance to stores on dead nodes. This bug is now fixed.

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm: nice catch!

I'm not very familiar with this code, so I do think we should get a second look from someone who is. @lunevalex do you feel comfortable giving this a second pass? I see your name in some of the recent changes in this area.

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65312#-:-Ma-9hoP-jzmcnmQiceN:bviw82n)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15)

___
*[pkg/kv/kvserver/allocator_scorer.go, line 643 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65312#-Ma-Aa5bAQKcFPYlPM9H:-Ma-Aa5bAQKcFPYlPM9I:bre6jbw) ([raw file](https://github.com/cockroachdb/cockroach/blob/568a5c6732ee1596978458ed1b8366ac689f1833/pkg/kv/kvserver/allocator_scorer.go#L643)):*
> ```Go
> 				continue
> 			}
> 			for _, onExemptedStore := range replicasOnExemptedStores {
> ```

nit: `repl` or `replOnExemptedStore` to make it more clear what this object is.
___
*[pkg/kv/kvserver/allocator_test.go, line 2698 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65312#-Ma-AKgtB6uVxmxKTR5f:-Ma-AKgtB6uVxmxKTR5g:bms614t) ([raw file](https://github.com/cockroachdb/cockroach/blob/568a5c6732ee1596978458ed1b8366ac689f1833/pkg/kv/kvserver/allocator_test.go#L2698)):*
> ```Go
> 			)
> 			if len(tc.expected) > 0 {
> 				require.Len(t, rebalanceOpts, 1)
> ```

Do we ever expect this test to generate multiple `rebalanceOptions`?
___
*[pkg/kv/kvserver/allocator_test.go, line 2708 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65312#-Ma-A7kP59c4LJpvODOa:-Ma-A7kP59c4LJpvODOb:b-uxmujb) ([raw file](https://github.com/cockroachdb/cockroach/blob/568a5c6732ee1596978458ed1b8366ac689f1833/pkg/kv/kvserver/allocator_test.go#L2708)):*
> ```Go
> 					existingStores[i] = cand.store.StoreID
> 				}
> 				require.ElementsMatch(t, existingStores, tc.existing)
> ```

nit: do we want `tc.existing` to come first?

**Comment by lunevalex** [comment]
___
*[pkg/kv/kvserver/allocator_test.go, line 2582 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65312#-Ma-wsbEAwiB0RaYefIE:-Ma-wsbFEirolEFLQBHl:bw8urnf) ([raw file](https://github.com/cockroachdb/cockroach/blob/568a5c6732ee1596978458ed1b8366ac689f1833/pkg/kv/kvserver/allocator_test.go#L2582)):*
> ```Go
> // of candidates for an allocation.
> func TestAllocateCandidatesExcludeNonReadyNodes(t *testing.T) {
> 	defer leaktest.AfterTest(t)()
> ```

I wonder why the `TestAllocatorRebalanceDeadNodes` test did not catch this problem to begin with, should we modify that one to include a condition for a very desirable dead node and make sure it does not get picked? I think we need a high level test somewhere to make sure the issue is actually fixed.

**Comment by aayushshah15** [comment]
___
*[pkg/kv/kvserver/allocator_test.go, line 2582 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65312#-Ma-wsbEAwiB0RaYefIE:-Ma028iL0WZ3pfUD11wl:b-857w5a) ([raw file](https://github.com/cockroachdb/cockroach/blob/568a5c6732ee1596978458ed1b8366ac689f1833/pkg/kv/kvserver/allocator_test.go#L2582)):*
<details><summary><i>Previously, lunevalex wrote…</i></summary><blockquote>

I wonder why the `TestAllocatorRebalanceDeadNodes` test did not catch this problem to begin with, should we modify that one to include a condition for a very desirable dead node and make sure it does not get picked? I think we need a high level test somewhere to make sure the issue is actually fixed.  
</blockquote></details>

The distinction is that this test (and this fix) are concerned with not rebalancing to nodes that have a non-live `NodeLiveness` record. Note that this is distinct from "dead" nodes (which is what's determined by `server.time_until_store_dead`).  

So:
- `TestAllocateCandidatesExcludeNonReadyNodes` is concerned with nodes that have simply missed liveness heartbeats but aren't considered "dead" yet
- `TestAllocatorRebalanceDeadNodes` is concerned with nodes that _haven't been live since `server.time_until_store_dead` minutes ago_

Does that make sense?

**Review by lunevalex — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65312)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15)

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65312)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/allocator_scorer.go, line 643 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65312#-Ma-Aa5bAQKcFPYlPM9H:-Ma0AdPO0SEhDpzHO4M9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/568a5c6732ee1596978458ed1b8366ac689f1833/pkg/kv/kvserver/allocator_scorer.go#L643)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: `repl` or `replOnExemptedStore` to make it more clear what this object is.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/allocator_test.go, line 2698 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65312#-Ma-AKgtB6uVxmxKTR5f:-Ma093QB1rNs9WutgV5K:b5pye22) ([raw file](https://github.com/cockroachdb/cockroach/blob/568a5c6732ee1596978458ed1b8366ac689f1833/pkg/kv/kvserver/allocator_test.go#L2698)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we ever expect this test to generate multiple `rebalanceOptions`?
</blockquote></details>

Nope. This is because all stores are identical in terms of their localities, so they all get classified as "comparable". We would have multiple `rebalanceOptions` if these stores had different localities (thus resulted in different diversity scores depending on which replica was being rebalanced).
___
*[pkg/kv/kvserver/allocator_test.go, line 2708 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/65312#-Ma-A7kP59c4LJpvODOa:-Ma09RfsAr3sMZyDA_ls:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/568a5c6732ee1596978458ed1b8366ac689f1833/pkg/kv/kvserver/allocator_test.go#L2708)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: do we want `tc.existing` to come first?
</blockquote></details>

Done.

**Comment by aayushshah15** [comment]
TFTR!

bors r=nvanbenschoten,lunevalex

**Pull request merged**
