### PR TITLE
kv: Add metrics and telemetry for remaining types of transaction restart errors

### PR DESCRIPTION
**Pull request by bdarnell**

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35438)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @dt, and @nvanbenschoten)

___
*[pkg/kv/txn_coord_sender.go, line 898 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35438#-L_FO2h21UUMqq69kybM:-L_FO2h21UUMqq69kybN:b-dxu1ka) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea4baec336a068423645c7bec8c87428ce67fb9f/pkg/kv/txn_coord_sender.go#L898)):*
> ```Go
> 
> 	case *roachpb.WriteTooOldError:
> 		// TODO(bdarnell): Is this possible here? They're supposed to be
> ```

I think this is only the case for `EndTransaction` requests where the `WriteTooOld` flag is set. For requests like `CPut`s, we might returns one of these immediately.
___
*[pkg/kv/txn_coord_sender.go, line 912 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35438#-L_FNQttDBR3yP6DR_Ka:-L_FNQtu4waf9dqDQVcU:byjnhry) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea4baec336a068423645c7bec8c87428ce67fb9f/pkg/kv/txn_coord_sender.go#L912)):*
> ```Go
> 
> 	case *roachpb.TransactionPushError:
> 		// TODO(bdarnell): Is this possible here? They're not transaction
> ```

I think @andreimatei and @ajwerner were rationalizing this error recently to determine what kinds of retry errors a follower read could hit. What was the conclusion?

**Review by dt — APPROVED** [review]
telemetry part LGTM

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35438)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @nvanbenschoten)

___
*[pkg/kv/txn_coord_sender.go, line 898 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35438#-L_FO2h21UUMqq69kybM:-L_IcR4hBQupzTCKG2Ye:bkz82bc) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea4baec336a068423645c7bec8c87428ce67fb9f/pkg/kv/txn_coord_sender.go#L898)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think this is only the case for `EndTransaction` requests where the `WriteTooOld` flag is set. For requests like `CPut`s, we might returns one of these immediately.
</blockquote></details>

It's the other way around. Regular KV ops generate WriteTooOldError in MVCC, but they are transmuted in the Store/Replica into non-errors with Transaction.WriteTooOld set. EndTransaction returns TransactionRetryError with reason RETRY_WRITE_TOO_OLD when this flag is set.

But I think I see it now:

https://github.com/cockroachdb/cockroach/blob/ab142881bddd3707245ee37b4df7cf6f20a214e4/pkg/storage/replica_write.go#L450-L454

We only try once to transmute a WriteTooOldError; if we hit a second WTOE when retrying the batch the WTOE gets returned directly and generates a retry (this can happen if you're getting write/write conflicts between more than two transactions, and pushing past the first txn's timestamp isn't enough to get you past the second). Maybe we want to track the two kinds of WriteTooOld restarts separately - this path is inefficient and if it's happening a lot we might want to do something about it.

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35438)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/txn_coord_sender.go, line 912 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35438#-L_FNQttDBR3yP6DR_Ka:-L_JOmGZ3fVE5EF3KmYv:b8em1b5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea4baec336a068423645c7bec8c87428ce67fb9f/pkg/kv/txn_coord_sender.go#L912)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think @andreimatei and @ajwerner were rationalizing this error recently to determine what kinds of retry errors a follower read could hit. What was the conclusion?
</blockquote></details>

I've pulled on this thread a little bit. TransactionPushErrors are normally retried in the store:

https://github.com/cockroachdb/cockroach/blob/b4de5debda7b2ba297f820908966818b878ec247/pkg/storage/store.go#L2909-L2922

When the txnwait queue went in, certain tests started suppressing this retry because it became blocking (and could deadlock). In that case, the TransactionPushError escapes up to TxnCoordSender, where it is retried. (at line 2918, we try to convert the TransactionPushError to a TransactionRetryError, but I think this is dead code because it is run on the PushTxn operation which is non-transactional). 

For some reason doing the retry in the store with the txn queue will deadlock in some tests (like txn_correctness_test), but doing the same (?) retry in TxnCoordSender does not. While there might be some potential cleanup here I don't think it's worth digging in any deeper.

**Review by bdarnell — COMMENTED** [review]
Some updates here:
- Changes in the telemetry layer so that metric registration works properly
- New metrics for the different types of write-to-old errors and capturing "unknown" errors if they ever occur

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35438#-:-L_KDDuS5airwfA3TgDN:b-wh685)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by andreimatei — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35438#-:-L_O-atw8pBPk3SJY2N1:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @nvanbenschoten)

___
*[pkg/kv/txn_coord_sender.go, line 308 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35438#-L_NyCXq64woDpxIxVGu:-L_NyCXq64woDpxIxVGv:bsmxp5k) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f08d61064684bd9b9af2f2195afa9d9ee0a5bfe/pkg/kv/txn_coord_sender.go#L308)):*
> ```Go
> 	metaRestartsWriteTooOldMulti = metric.Metadata{
> 		Name:        "txn.restarts.writetoooldmulti",
> 		Help:        "Number of restarts due to multiple concurrent writers committing first",
> ```

can you please explain more the difference between this one and the previous one?
___
*[pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/distributed.tsx, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35438#-L_O-4APBdubyayRPiAA:-L_O-4APBdubyayRPiAB:b-ekykrm) ([raw file](https://github.com/cockroachdb/cockroach/blob/79f4d365f58d4a80b98131e5d2b42bbaaad661ac/pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/distributed.tsx#L60)):*
> ```XML
>       <Axis label="restarts">
>         <Metric name="cr.node.txn.restarts.writetooold" title="Write Too Old" nonNegativeRate />
>         <Metric name="cr.node.txn.restarts.deleterange" title="Forwarded Timestamp (delete range)" nonNegativeRate />
> ```

what happened to this one?

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35438)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/txn_coord_sender.go, line 308 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35438#-L_NyCXq64woDpxIxVGu:-L_O_kquESLjikUUijSU:bdbsvjc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f08d61064684bd9b9af2f2195afa9d9ee0a5bfe/pkg/kv/txn_coord_sender.go#L308)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

can you please explain more the difference between this one and the previous one?
</blockquote></details>

Do you mean more than what I have below or that this would be a better place for that explanation? I don't think we want that much detail in a tooltip but I could move the comment below up here to the metric metadata. 
___
*[pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/distributed.tsx, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35438#-L_O-4APBdubyayRPiAA:-L_Oa4WY0gJJ8nzHxga_:b-m09syb) ([raw file](https://github.com/cockroachdb/cockroach/blob/79f4d365f58d4a80b98131e5d2b42bbaaad661ac/pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/distributed.tsx#L60)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

what happened to this one?
</blockquote></details>

It was removed a while back, I think when we dropped support for snapshot isolation.

**Review by andreimatei — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35438)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @bdarnell, and @nvanbenschoten)

___
*[pkg/kv/txn_coord_sender.go, line 308 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35438#-L_NyCXq64woDpxIxVGu:-L_ObPL7E-nVlqcLb7H7:b-s3kt5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f08d61064684bd9b9af2f2195afa9d9ee0a5bfe/pkg/kv/txn_coord_sender.go#L308)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Do you mean more than what I have below or that this would be a better place for that explanation? I don't think we want that much detail in a tooltip but I could move the comment below up here to the metric metadata. 
</blockquote></details>

yeah, I guess I'd move the comment here. But also the code comment has less information than your code review comment. I'd put all the words in the code comment.

**Comment by bdarnell** [comment]
OK, consolidated the comments and expanded the one about WriteTooOld.

bors r+

**Pull request merged**
