### PR TITLE
sql: add generate_series for decimals and arithmetic ops between decimal and float

### PR DESCRIPTION
**Pull request by RaduBerinde**
I was playing around with some recursive CTEs for fractals ([link](https://malisper.me/generating-fractals-with-postgres-escape-time-fractals/#targetText=CTEs%20effectively%20give%20you%20a,the%20query%20into%20smaller%20pieces.&targetText=After%20running%20that%20query%20Postgres,of%20that%20query%20as%20numbers)) and hit these missing things. 

#### sql: add generate_series for decimals

This was added in recent versions of Postgres.

Release note (sql change): generate_series with decimal arguments is
now supported.

#### sql: add arithmetic operations between decimal and float

In these cases, the decimal is cast to float and the result is float
(this is consistent with postgres).

Release note (sql change): arithmetic operations (`+,-,/,*`) are
now supported between a decimal and a float (with float return value).

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41357)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @knz)

___
*[pkg/sql/sem/tree/testdata/eval/annotate, line 111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41357#-LqSjKDJ3P13xlNxehcj:-LqSjKDJ3P13xlNxehck:b73hgkr) ([raw file](https://github.com/cockroachdb/cockroach/blob/445ec411db8cde8cc090c7ffcd7ac70be9b21954/pkg/sql/sem/tree/testdata/eval/annotate#L111)):*
> ```
> 
> eval
> (123 + 1):::float
> ```

This test now errors out with `unsupported binary operator: <int> + <int> (desired <float>)`. Not sure if this is expected from just addin a new `float + decimal` operator.. CC @knz

**Review by knz — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41357)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @nvanbenschoten, and @RaduBerinde)

___
*[pkg/sql/sem/tree/eval.go, line 1250 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41357#-LqTcOxiDQ8cERFCGadl:-LqTcOxkDxhFWipnfaKg:b-8776vn) ([raw file](https://github.com/cockroachdb/cockroach/blob/bacfa1275bd6556ce03f6146481e16d879060eb5/pkg/sql/sem/tree/eval.go#L1250)):*
> ```Go
> 			RightType:  types.Decimal,
> 			ReturnType: types.Float,
> 			Fn: func(_ *EvalContext, left Datum, right Datum) (Datum, error) {
> ```

You need to check the division by zero here like the implementations above to be compatible with pg.
___
*[pkg/sql/sem/tree/eval.go, line 1267 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41357#-LqTcTD51i8RUjYmjPja:-LqTcTD51i8RUjYmjPjb:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/bacfa1275bd6556ce03f6146481e16d879060eb5/pkg/sql/sem/tree/eval.go#L1267)):*
> ```Go
> 				l := left.(*DDecimal)
> 				r := *right.(*DFloat)
> 				lFloat, err := l.Float64()
> ```

ditto
___
*[pkg/sql/sem/tree/testdata/eval/annotate, line 111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41357#-LqSjKDJ3P13xlNxehcj:-LqTc_et1Tugr1ucNUBN:b-k17zh5) ([raw file](https://github.com/cockroachdb/cockroach/blob/445ec411db8cde8cc090c7ffcd7ac70be9b21954/pkg/sql/sem/tree/testdata/eval/annotate#L111)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This test now errors out with `unsupported binary operator: <int> + <int> (desired <float>)`. Not sure if this is expected from just addin a new `float + decimal` operator.. CC @knz 
</blockquote></details>

It's very probably a feature of typeCheckOverloadedExprs() in `type_check.go`.
I don't recall the details fully but I think it's because `float` is not at the head of decimal-like types in `naturalConstantType()`.
That will require some digging and/or participation from @nvanbenschoten. We may be able to decide peacefully that this type annotation reasonably results in an ambiguous type error, but I'd like the argument to be fleshed out, or alternatively find a reasonable tweak to typeCheckOverloadedExprs(), before we merge this PR.

Also I encourage you to propagate a few test cases to `type_check_test.go` (in sem/tree)

**Comment by RaduBerinde** [comment]
Unfortunately I am hitting other issues related to the type system.
```
CREATE TABLE mnop (
  m INT PRIMARY KEY,
  n FLOAT,
  o DECIMAL,
  p BIGINT
)

statement ok
INSERT INTO mnop (m, n) SELECT i, (1e9 + i/2e4)::float FROM
  generate_series(1, 2e4) AS i(i)
```

Now this uses the decimal variation of `generate_series` and errors out with `value type decimal doesn't match type int of column "m"`. The same query works in postgres, even though `i` is also `numeric` in their case. I think they allow implicit conversion from decimal to integer, and we do not. 

In fact, by poked around `pg_catalog.pg_operator` and I don't think postgres has a + operator between float and decimal - they allow implicit conversion from decimal to float.

Maybe we should allow thee conversions?

**Comment by knz** [comment]
Now that we have more staff in house and more pressure to gain compatibility with pg, perhaps it's time for a type system overhaul including matching pg's overloading and auto-conversion rules? 

A year ago I'd have said it was too soon, but now... There is so much to gain from switching over, and relatively little to lose.

**Comment by RaduBerinde** [comment]
I will close this for now, I thought it would be a simple change. @jordanlewis perhaps someone from your team wants to pick it up if we think it's useful.

**Comment by jordanlewis** [comment]
Yeah I think we're getting painted more and more into a corner with our type system. An external contributor ran into something very similar - tried to add another overload for something (so there was an int, float and decimal overload) but it was impossible due to some details of `typeCheckOverloadedExprs`.

**Pull request closed without merging**
