### PR TITLE
acceptance: check replica count std dev after stable interval

### LINKED ISSUE #8051: acceptance: StableInterval leads to false positives in allocator tests
There's no way TestUpreplicate_1To6Medium completed in 2h:58m, but the log suggests so:

```
[21:30:01][TestUpreplicate_1To6Medium] I160726 21:30:01.064351 acceptance/allocator_test.go:281  last range event: add for range 1406/store 4 (3m1.286513s ago)
[21:30:01][TestUpreplicate_1To6Medium] I160726 21:30:01.133859 acceptance/allocator_test.go:210  cluster took 2h29m8.360463s to rebalance
[21:30:01][TestUpreplicate_1To6Medium] I160726 21:30:01.187378 acceptance/allocator_test.go:221  4479 range events
[21:30:01][TestUpreplicate_1To6Medium] I160726 21:30:01.267697 acceptance/allocator_test.go:242  stddev(replica count) = 588.83
```

The high standard deviation makes it obvious that the cluster wasn't stable, but simply stuck for >3 minutes (the stable interval).
We ought to put in a harder criterion for stableness than just nothing going on for minutes.

https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=4876#_focus=86

### PR DESCRIPTION
**Pull request by tbg**
Fixes #8051.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8225)

### CODE REVIEW

**Comment by cuongdo** [comment]
:lgtm: w/ comments

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[acceptance/allocator_test.go, line 85 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8225#-KOAe0eRQnP3hU5y2vw6:-KOAe0eSrX9iTps2McMe:914932360) ([raw file](https://github.com/cockroachdb/cockroach/blob/943661ff85a54cdfd7e4b0ca6b8102a28583d217/acceptance/allocator_test.go#L85)):*
> ```Go
> 	archivedStoreURL = "gs://cockroach-test/allocatortest"
> 	StableInterval   = 3 * time.Minute
> 	StableStdDev     = 10
> ```

Can you make this a flag? This probably will need be tweaked as we continue iterating on the rebalancer, and it'd be convenient to avoid needing PRs to do that. Since you'll be off soon, feel free to put that off.

---

*[acceptance/allocator_test.go, line 270 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8225#-KOAecQZdCl4PmexWFp-:-KOAecQZdCl4PmexWFp0:-1276315636) ([raw file](https://github.com/cockroachdb/cockroach/blob/943661ff85a54cdfd7e4b0ca6b8102a28583d217/acceptance/allocator_test.go#L270)):*
> ```Go
> // changes) and the standard deviation in replica counts. Only unrecoverable
> // errors are returned.
> func (at *allocatorTest) checkAllocatorStable(db *gosql.DB) (
> ```

This method has new functionality and thus deserves a new name... maybe `allocatorStats`?

---

*[acceptance/allocator_test.go, line 301 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8225#-KOAfg_-l_IwcqKj6Jv8:-KOAfg_0lD9VVxCxZ5kT:1089682223) ([raw file](https://github.com/cockroachdb/cockroach/blob/943661ff85a54cdfd7e4b0ca6b8102a28583d217/acceptance/allocator_test.go#L301)):*
> ```Go
> 	}
> 
> 	log.Infof(context.TODO(), "last range event: %s for range %d/store %d (%s ago)",
> ```

Since this is now a getter method, this `log` call should probably move to `WaitForRebalance`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8225#-:-KOAfoQZ4Mfjv6haP80S:-1477467219)*

**Comment by tschottdorf** [comment]
TFTR, PTAL!

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[acceptance/allocator_test.go, line 85 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8225#-KOAe0eRQnP3hU5y2vw6:-KOAj9aX1nvaAANKiGYl:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/943661ff85a54cdfd7e4b0ca6b8102a28583d217/acceptance/allocator_test.go#L85)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary>
> Can you make this a flag? This probably will need be tweaked as we continue iterating on the rebalancer, and it'd be convenient to avoid needing PRs to do that. Since you'll be off soon, feel free to put that off.
</details>
Done.

---

*[acceptance/allocator_test.go, line 270 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8225#-KOAecQZdCl4PmexWFp-:-KOAjA5zAo-utmYYOD9G:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/943661ff85a54cdfd7e4b0ca6b8102a28583d217/acceptance/allocator_test.go#L270)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary>
> This method has new functionality and thus deserves a new name... maybe `allocatorStats`?
</details>
Done.

---

*[acceptance/allocator_test.go, line 301 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8225#-KOAfg_-l_IwcqKj6Jv8:-KOAjBfc5ubHeGAw1XVa:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/943661ff85a54cdfd7e4b0ca6b8102a28583d217/acceptance/allocator_test.go#L301)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary>
> Since this is now a getter method, this `log` call should probably move to `WaitForRebalance`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8225#-:-KOAjDyJTPn_lzAVicyV:-1619447991)*

**Comment by cuongdo** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8225)*

**Comment by cuongdo** [comment]
Still :LGTM:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8225#-:-KOAlwaD4cq5CLK6LnFJ:-195068759)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[acceptance/allocator_test.go, line 206 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8225#-KOAlr1U4fcG9htCTyCD:-KOAlr1Vom_srmrQJBNM:1298353948) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5618f274fc4ec403b1ab0c13bf211f113b41540/acceptance/allocator_test.go#L206)):*
> ```Go
> 	url := fmt.Sprintf("http://%s:%s/_status/nodes", host, adminPort)
> 	if err := util.GetJSON(client, url, &nodesResp); err != nil {
> 		return math.MaxFloat64
> ```

can this just return an error? ditto below

---

*[acceptance/allocator_test.go, line 301 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8225#-KOAm9qVY1Qh37aQErMf:-KOAm9qVY1Qh37aQErMg:-2123008469) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5618f274fc4ec403b1ab0c13bf211f113b41540/acceptance/allocator_test.go#L301)):*
> ```Go
> 	row := db.QueryRow(q, eventTypes...)
> 	if row == nil {
> 		log.Errorf(context.TODO(), "couldn't find any range events")
> ```

all this error handling is real strange

---

*[acceptance/allocator_test.go, line 305 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8225#-KOAmEoqnaueSgRAtUyQ:-KOAmEoqnaueSgRAtUyR:-1541195472) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5618f274fc4ec403b1ab0c13bf211f113b41540/acceptance/allocator_test.go#L305)):*
> ```Go
> 	}
> 	if err := row.Scan(&elapsedStr, &s.RangeID, &s.StoreID, &s.EventType); err != nil {
> 		// Log but don't return errors, to increase resilience against transient
> ```

transient errors on row.Scan()? wat

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8225)*

**Comment by tschottdorf** [comment]
@tamird I don't disagree, but this just got green, so I'll leave the sanity refactor to @cuongdo who afaik is touching this code right now.

**Pull request merged**
