### PR TITLE
sql: bevy of fixes for ActiveRecord compatibility

### PR DESCRIPTION
**Pull request by jordanlewis**
- improve efficiency of `'foo'::REGCLASS`
- improve efficiency of `pg_get_coldesc`
- parse INTERVAL(6) as a no-op meaning INTERVAL
- bugfix to generate_subscripts for oidvector and int2vector
- add pg_available_extensions
- fix `pg_get_indexdef` and `pg_attrdef.adbin` to be more Postgres compatible

With these fixes, 90% of the fork in `activerecord-cockroachdb-adapter` can go away.

### CODE REVIEW

**Comment by awoods187** [comment]
Excited for this work!

**Review by yuzefovich — APPROVED** [review]
Nice work! :lgtm:

> Reviewed 6 of 6 files at r1, 2 of 2 files at r2, 5 of 5 files at r3, 5 of 5 files at r4, 1 of 1 files at r5, 7 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41323#-:-LqbUIOl5t8twT9ByeQo:b-8ewgme)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @rafiss)

___
*[pkg/sql/parser/sql.y, line 6851 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41323#-LqbSdhw7-hFXsxv1S5R:-LqbSdhw7-hFXsxv1S5S:b-49ltg6) ([raw file](https://github.com/cockroachdb/cockroach/blob/092941f3e1a6166c615cd8328cff708259fd8867/pkg/sql/parser/sql.y#L6851)):*
> ```Yacc
>       return setErr(sqllex, err)
>     }
>     if prec == 6 {
> ```

Why this particular precision? Is it just what ActiveRecord uses?
___
*[pkg/sql/sem/tree/eval.go, line 2521 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41323#-LqbS1k17bsBoNq55Vdo:-LqbS1k17bsBoNq55Vdp:b-5trg5o) ([raw file](https://github.com/cockroachdb/cockroach/blob/29c3003aee7fd97416d997ebced8e698e5c71643/pkg/sql/sem/tree/eval.go#L2521)):*
> ```Go
> 	// sets it on the returned TableName.
> 	// It returns an error if the table doesn't exist.
> 	ResolveTableName(ctx context.Context, tn *TableName) (ID, error)
> ```

[nit]: I'd update the comment to mention that the identified is returned.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41323)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/sem/tree/datum.go, line 3137 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41323#-LqbVNC-3o4WK9Jf38DX:-LqbVNC-3o4WK9Jf38DY:b-nhkmtn) ([raw file](https://github.com/cockroachdb/cockroach/blob/06a51b4adee7e6a3b64e3e1d26c4320d0f354dc9/pkg/sql/sem/tree/datum.go#L3137)):*
> ```Go
> 	switch d.customOid {
> 	case oid.T_int2vector, oid.T_oidvector:
> 		return 0
> ```

would it be more reliable to specify the `firstIndex` as a field in the DArray struct? that way it's harder to forget to add a type here?

though i guess if the list of zero-indexed types really never changes, then this way is fine. up to you

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41323)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rafiss and @yuzefovich)

___
*[pkg/sql/parser/sql.y, line 6851 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41323#-LqbSdhw7-hFXsxv1S5R:-LqcCiFyEWf1m17NauB9:b-guvft7) ([raw file](https://github.com/cockroachdb/cockroach/blob/092941f3e1a6166c615cd8328cff708259fd8867/pkg/sql/parser/sql.y#L6851)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Why this particular precision? Is it just what ActiveRecord uses?
</blockquote></details>

It is the maximum supported precision by Postgres.
___
*[pkg/sql/sem/tree/datum.go, line 3137 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41323#-LqbVNC-3o4WK9Jf38DX:-LqcEFoc63a6Mot8cZaE:blf8zf4) ([raw file](https://github.com/cockroachdb/cockroach/blob/06a51b4adee7e6a3b64e3e1d26c4320d0f354dc9/pkg/sql/sem/tree/datum.go#L3137)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

would it be more reliable to specify the `firstIndex` as a field in the DArray struct? that way it's harder to forget to add a type here?

though i guess if the list of zero-indexed types really never changes, then this way is fine. up to you
</blockquote></details>

I think I'll leave this for now as I doubt it'll ever change. Hopefully this won't come up again! And at least it's in the `datum.go` file, should be at least vaguely discoverable. :grimacing: 
___
*[pkg/sql/sem/tree/eval.go, line 2521 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41323#-LqbS1k17bsBoNq55Vdo:-LqcHlrB10tbUPAy7Md2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/29c3003aee7fd97416d997ebced8e698e5c71643/pkg/sql/sem/tree/eval.go#L2521)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: I'd update the comment to mention that the identified is returned.
</blockquote></details>

Done.

**Comment by nvanbenschoten** [comment]
bors r-

Looks like aaec91104c1904887feca379c9a82b86b5ae9ac3 is hitting issues with `TestParse`.
> parse_test.go:1364: '0'::INTERVAL: expected success, but found at or near "0": syntax error

I only noticed because I thought I had caused it with https://github.com/cockroachdb/cockroach/pull/41404.

**Comment by jordanlewis** [comment]
Sorry @nvanbenschoten 😬

**Pull request merged**
