### PR TITLE
sql: physical plan design that allows clean merging

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### sql: don't create values processors for zig-zag

The zig-zag joiner spec contains `ValuesCoreSpec`s (which only have a
single row). This is questionable to begin with, but the code that
generates this is also very hacky - it creates a plan with a full
processor. These throw-away processors interfere with an unrelated
redesign of PhysicalPlan.

This change refactors the code so that we only generate the spec and
not the processor.

Release note: None

#### sql: use single PlanningCtx in experimental factory

The experimental factory uses two PlanningCtx instances which are the
same other than the isLocal flag. We change this to use a single
context, and we change the flag as needed each time.

Release note: None

#### sql: physical plan design that allows clean merging

When we create a distsql plan, we create a `PhysicalPlan` for each
leaf of the plan, and these plans merge with each other according to
the tree. When two plans merge, the processors and streams merge as
well. Unfortunately, the plan internally refers to
processors/streams/stages by index, so there is some renumbering that
has to happen.

The unstable indexing cause some additional nastiness: local
processors store pointers to indexes and `LocalProcessorIndexes`
remembers those pointers so that the indexes can be readjusted on
merge.

The unstable indexing is also a problem for ongoing work on execution
statistics: we can associate processors to execution nodes when we
have just built the plan for that node, but we'd need to update the
indexes on merge.

This change cleans up this situation as follows:

 - the processors and streams are pulled out into a separate
   `PlanInfrastructure` structure.

 - the PhysicalPlan embeds a `*PlanInfrastructure`. Critically, all
   the plans in a tree share the same infrastructure, so all
   processors/streams get appended to a single backing container.
   Thus, merging becomes a no-op as far as the processors and streams
   are concerned.

The single set of slices should also reduce allocations during planning.

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
Very nice!

Should we bump the distsql version because of the change to `LocalPlanNode` spec?

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 20 of 20 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56808#-:-MMMGGZR0EQw-mhE51K_:b-a0blio)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @pbardea, and @RaduBerinde)

___
*[pkg/sql/distsql_physical_planner.go, line 2793 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56808#-MMMDXRxEbVyBY-JiB_Y:-MMMDXRxEbVyBY-JiB_Z:b-fwuusl) ([raw file](https://github.com/cockroachdb/cockroach/blob/82efb6c6f9dadb83e444cc8e54f55437f88ce397/pkg/sql/distsql_physical_planner.go#L2793)):*
> ```Go
> 	wrapper.firstNotWrapped = firstNotWrapped
> 
> 	localProxIdx := p.AddLocalProcessor(wrapper)
> ```

nit: `s/localProxIdx/localProcIdx/`.

**Review by yuzefovich — APPROVED** [review]
Actually bump is unnecessary since we never distribute the stage with LocalPlanNode cores.

:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56808#-:-MMMJ6Kt92qe4ftfCEX0:bhl1wsk)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @pbardea, and @RaduBerinde)

**Review by RaduBerinde — COMMENTED** [review]
Yeah, also I don't think anything over the wire would change anyway. TFTR!

CC @jordanlewis - thinking you'll be happy to see the last of `LocalProcessorIndexes` :)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56808#-:-MMMYQpr1s5uE8L5GR38:bysbyj9)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @pbardea, and @yuzefovich)

**Review by jordanlewis — COMMENTED** [review]
Sorry I didn't get to reviewing this, but very glad to see that LocalIndexes thing gone... thank you!

**Pull request merged**
