### PR TITLE
sql: add crdb_internal.show_create_all_tables builtin

### PR DESCRIPTION
**Pull request by RichardJCai**
sql: add crdb_internal.show_create_all_tables builtin

Making this a PR first before continuing with #53488, we can alias this builtin with SHOW CREATE ALL TABLES.

Example output:
```
query T
SELECT crdb_internal.show_create_all_tables('d')
----
CREATE TABLE public.parent (
  x INT8 NULL,
  y INT8 NULL,
  z INT8 NULL,
  UNIQUE INDEX parent_x_y_z_key (x ASC, y ASC, z ASC),
  UNIQUE INDEX parent_x_key (x ASC),
  FAMILY f1 (x, y, z, rowid)
);
CREATE TABLE public.full_test (
  x INT8 NULL,
  y INT8 NULL,
  z INT8 NULL,
  UNIQUE INDEX full_test_x_key (x ASC),
  FAMILY f1 (x, y, z, rowid)
);
CREATE SEQUENCE public.s MINVALUE 1 MAXVALUE 9223372036854775807 INCREMENT 1 START 1;
CREATE VIEW public.vx ("?column?") AS SELECT 1;
ALTER TABLE public.full_test ADD CONSTRAINT fk_x_ref_parent FOREIGN KEY (x, y, z) REFERENCES public.parent(x, y, z) MATCH FULL ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE public.full_test ADD CONSTRAINT test_fk FOREIGN KEY (x) REFERENCES public.parent(x) ON DELETE CASCADE;
-- Validate foreign key constraints. These can fail if there was unvalidated data during the SHOW CREATE ALL TABLES
ALTER TABLE public.full_test VALIDATE CONSTRAINT fk_x_ref_parent;
ALTER TABLE public.full_test VALIDATE CONSTRAINT test_fk;
```

Release note (sql change): crdb_internal.show_create_all_tables is
a new builtin that takes in a database name (string) and returns
a flat log of all the CREATE TABLE statements in the database followed
by alter statements to add constraints. The output can be used
to recreate a database. This builtin was added to replace old dump logic.

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
awesome! just have relatively minor comments

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60154#-:-MT6coHj1bBynIZjNFW8:bgobh2d)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[pkg/sql/logictest/testdata/logic_test/show_create_all_tables_builtin, line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60154#-MT6cblZEQ75TUnNHWf_:-MT6cblZEQ75TUnNHWfa:bcmeai7) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bc4968f5dc74789948c50b825b2ba9ff57f0554/pkg/sql/logictest/testdata/logic_test/show_create_all_tables_builtin#L2)):*
> ```
> query T
> SELECT crdb_internal.show_create_all_tables('d')
> ```

nice tests! maybe you did this already, but perhaps you could take a look to see if `dump` used to have any other good test cases that we could pull in here too?
___
*[pkg/sql/sem/builtins/builtins.go, line 4829 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60154#-MT6bmrU44hSjgARw-34:-MT6bmrU44hSjgARw-35:bkk9ete) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bc4968f5dc74789948c50b825b2ba9ff57f0554/pkg/sql/sem/builtins/builtins.go#L4829)):*
> ```Go
> 	),
> 
> 	"crdb_internal.show_create_all_tables": makeBuiltin(
> ```

hmm random thing i just thought of -- is this OK to have in crdb_internal? aren't things in crdb_internal usually experimental/undocumented? (idk though maybe it's too sketchy to put into the normal namespace)
___
*[pkg/sql/sem/builtins/show_create_all_tables_builtin.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60154#-MT6c9sL0Ed5vKvVS1Bm:-MT6c9sL0Ed5vKvVS1Bn:b-h5n5oo) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bc4968f5dc74789948c50b825b2ba9ff57f0554/pkg/sql/sem/builtins/show_create_all_tables_builtin.go#L39)):*
> ```Go
> }
> 
> func showCreateAllTablesBuiltin(evalCtx *tree.EvalContext, arg tree.Datums) (tree.Datum, error) {
> ```

nit: could you add a comment?
___
*[pkg/sql/sem/builtins/show_create_all_tables_builtin.go, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60154#-MT6bT2r8Iq4o15JK0-D:-MT6bT2r8Iq4o15JK0-E:b-hkj4tw) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bc4968f5dc74789948c50b825b2ba9ff57f0554/pkg/sql/sem/builtins/show_create_all_tables_builtin.go#L46)):*
> ```Go
> 
> 	if len(mds) == 0 {
> 		return tree.NewDString("no tables found"), nil
> ```

is this what dump used to return? i wonder if it would be better for this function to always return valid SQL so that way a tool that relies on it doesn't get confused. (in this case it could just return NULL or an empty string
___
*[pkg/sql/sem/builtins/show_create_all_tables_builtin.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60154#-MT6cEBY5VQf0Zjg_1RS:-MT6cEBY5VQf0Zjg_1RT:b1r5byz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bc4968f5dc74789948c50b825b2ba9ff57f0554/pkg/sql/sem/builtins/show_create_all_tables_builtin.go#L111)):*
> ```Go
> }
> 
> func getMetadataForTablesInDB(evalCtx *tree.EvalContext, arg tree.Datums) ([]tableMetadata, error) {
> ```

need a comment
___
*[pkg/sql/sem/builtins/show_create_all_tables_builtin.go, line 135 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60154#-MT6cGr83SVJEitST8g7:-MT6cGr83SVJEitST8g8:b1r5byz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bc4968f5dc74789948c50b825b2ba9ff57f0554/pkg/sql/sem/builtins/show_create_all_tables_builtin.go#L135)):*
> ```Go
> }
> 
> func getTableMetadata(
> ```

need a comment
___
*[pkg/sql/sem/builtins/show_create_all_tables_builtin.go, line 264 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60154#-MT6cKQg8kPyqpltnp7a:-MT6cKQg8kPyqpltnp7b:b-f4taa7) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bc4968f5dc74789948c50b825b2ba9ff57f0554/pkg/sql/sem/builtins/show_create_all_tables_builtin.go#L264)):*
> ```Go
> }
> 
> func collect(tid int64, byID map[int64]tableMetadata, seen map[int64]bool, collected *[]int64) {
> ```

need a comment -- could you mention why a table could get collected twice?

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60154)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[pkg/sql/logictest/testdata/logic_test/show_create_all_tables_builtin, line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60154#-MT6cblZEQ75TUnNHWf_:-MTBwHtm0uFCraKGG2Vi:b-y50501) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bc4968f5dc74789948c50b825b2ba9ff57f0554/pkg/sql/logictest/testdata/logic_test/show_create_all_tables_builtin#L2)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nice tests! maybe you did this already, but perhaps you could take a look to see if `dump` used to have any other good test cases that we could pull in here too?
</blockquote></details>

Yep pulled some more tests in, good call
___
*[pkg/sql/sem/builtins/builtins.go, line 4829 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60154#-MT6bmrU44hSjgARw-34:-MTBwQR363nEgheEdTaj:b-1nbhoj) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bc4968f5dc74789948c50b825b2ba9ff57f0554/pkg/sql/sem/builtins/builtins.go#L4829)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hmm random thing i just thought of -- is this OK to have in crdb_internal? aren't things in crdb_internal usually experimental/undocumented? (idk though maybe it's too sketchy to put into the normal namespace)
</blockquote></details>

After some offline discussion, I think leaving this in crdb_internal is fine and we'll expose this through SHOW CREATE ALL TABLES
___
*[pkg/sql/sem/builtins/show_create_all_tables_builtin.go, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60154#-MT6bT2r8Iq4o15JK0-D:-MTC-K8O-5huEEsCod-x:bmt6e0p) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bc4968f5dc74789948c50b825b2ba9ff57f0554/pkg/sql/sem/builtins/show_create_all_tables_builtin.go#L46)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

is this what dump used to return? i wonder if it would be better for this function to always return valid SQL so that way a tool that relies on it doesn't get confused. (in this case it could just return NULL or an empty string
</blockquote></details>

Updated to return empty string
___
*[pkg/sql/sem/builtins/show_create_all_tables_builtin.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60154#-MT6cEBY5VQf0Zjg_1RS:-MTBzmeh2C-qmpAVQb0S:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bc4968f5dc74789948c50b825b2ba9ff57f0554/pkg/sql/sem/builtins/show_create_all_tables_builtin.go#L111)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

need a comment
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/show_create_all_tables_builtin.go, line 135 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60154#-MT6cGr83SVJEitST8g7:-MTBzlmWC0YKO92POIt2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bc4968f5dc74789948c50b825b2ba9ff57f0554/pkg/sql/sem/builtins/show_create_all_tables_builtin.go#L135)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

need a comment
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/show_create_all_tables_builtin.go, line 264 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60154#-MT6cKQg8kPyqpltnp7a:-MTBzm19CvEEOrZ8N0hw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0bc4968f5dc74789948c50b825b2ba9ff57f0554/pkg/sql/sem/builtins/show_create_all_tables_builtin.go#L264)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

need a comment -- could you mention why a table could get collected twice?
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
looks great! thanks

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60154#-:-MTC7tQh7nDLTGIjDjBB:bneeeg4)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by RichardJCai** [comment]
Thanks for the quick reviews!
bors r=rafiss

**Comment by otan** [comment]
bors r-

this needs a rebase

**Comment by RichardJCai** [comment]
Updated!
bors r=rafiss

**Comment by otan** [comment]
bors r-

```
[23:46:18][Ensure generated code is up-to-date] pkg/sql/sem/builtins/show_create_all_tables_builtin.go:204:39: evalCtx.InternalExecutor.Query undefined (type tree.InternalExecutor has no field or method Query)
[23:46:18][Ensure generated code is up-to-date] pkg/sql/sem/builtins/show_create_all_tables_builtin.go:254:39: evalCtx.InternalExecutor.Query undefined (type tree.InternalExecutor has no field or method Query)
```

**Comment by rafiss** [comment]
looks like @yuzefovich just removed that function in #60428. it seems like we have to use `QueryIterator` now?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60154)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[pkg/sql/sem/builtins/show_create_all_tables_builtin.go, line 204 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60154#-MTEdX8Z9SZrxEtMPu0V:-MTEdX8Z9SZrxEtMPu0W:bhrzdyo) ([raw file](https://github.com/cockroachdb/cockroach/blob/64ab2876f1044845d416bcaf98eff7c7fb687934/pkg/sql/sem/builtins/show_create_all_tables_builtin.go#L204)):*
> ```Go
> 		WHERE descriptor_id = $1
> 		`, dbName, ts)
> 	rows, err := evalCtx.InternalExecutor.Query(
> ```

Yeah, you'll need to use `QueryIterator` method here. The code should be refactored to something like:
```
it, err := evalCtx.InternalExecutor.QueryIterator(...)
if err != nil {
  return tableMetadata{}, err
}
var refs []int64
var ok bool
for ok, err = it.Next(ctx); ok; ok, err = it.Next(ctx) {
  id := tree.MustBeDInt(it.Cur()[0])
  refs = append(refs, int64(id))
}
if err != nil {
  return tableMetadata{}, err
}
...
```

**Comment by RichardJCai** [comment]
This time for sure!
bors r=rafiss

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60154)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[pkg/sql/sem/builtins/show_create_all_tables_builtin.go, line 205 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/60154#-MTHTgmiERoz1UIbO4-4:-MTHTgmiERoz1UIbO4-5:bjv5qty) ([raw file](https://github.com/cockroachdb/cockroach/blob/6285cd3a57a4edfa717b099987d379b5e2024ff5/pkg/sql/sem/builtins/show_create_all_tables_builtin.go#L205)):*
> ```Go
> 		WHERE descriptor_id = $1
> 		`, dbName, ts)
> 	it, err := evalCtx.InternalExecutor.(sqlutil.InternalExecutor).QueryIterator(
> ```

we don't want to do a type assertion here -- instead add QueryIterator to the `pkg/sql/sem/tree.InternalExecutor` interface

**Comment by RichardJCai** [comment]
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60154)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)
> 
> _[pkg/sql/sem/builtins/show_create_all_tables_builtin.go, line 205 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/60154#-MTHTgmiERoz1UIbO4-4:-MTHTgmiERoz1UIbO4-5:bjv5qty) ([raw file](https://github.com/cockroachdb/cockroach/blob/6285cd3a57a4edfa717b099987d379b5e2024ff5/pkg/sql/sem/builtins/show_create_all_tables_builtin.go#L205)):_
> 
> > ```go
> > 		WHERE descriptor_id = $1
> > 		`, dbName, ts)
> > 	it, err := evalCtx.InternalExecutor.(sqlutil.InternalExecutor).QueryIterator(
> > ```
> 
> we don't want to do a type assertion here -- instead add QueryIterator to the `pkg/sql/sem/tree.InternalExecutor` interface

Can't add QueryIteratorEx to the InternalExecutor interface due to cyclic dependencies.
Added a followup issue to remove that Interface completely #60507

**Comment by RichardJCai** [comment]
Ok this time for sure for sure.

bors r=rafiss

**Review by rafiss — APPROVED** [review]

**Pull request merged**
