### PR TITLE
sql: Add information_schema.statistics

### PR DESCRIPTION
**Pull request by yznming**
#8675 add information_schema.statistics table.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10220)

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Thanks for putting this together! I have a few comments, but the general approach looks good.

---

Review status: 0 of 2 files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[pkg/sql/information_schema.go, line 410 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10220#-KV2d8dPGLYOMxGNdZ_J:-KV2d8dPGLYOMxGNdZ_K:bidir1z) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe43abda4725546470ef0c05dc58b2e8280c8bc/pkg/sql/information_schema.go#L410)):*
> ```Go
> }
> 
> var informationSchemaStatisticsTable = virtualSchemaTable{
> ```

Lets move this up to be in lexicographical order.

---

*[pkg/sql/information_schema.go, line 421 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10220#-KV2d0DN3Tj3R52_l70A:-KV2d0DN3Tj3R52_l70B:b-ksik9w) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe43abda4725546470ef0c05dc58b2e8280c8bc/pkg/sql/information_schema.go#L421)):*
> ```Go
> 	SEQ_IN_INDEX INT NOT NULL DEFAULT 0,
> 	COLUMN_NAME STRING NOT NULL DEFAULT '',
> 	"COLLATION" STRING NOT NULL DEFAULT '',
> ```

Why the quotes?

---

*[pkg/sql/information_schema.go, line 430 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10220#-KV2lMe_5uKuB6h0rAg-:-KV2lMe_5uKuB6h0rAg0:bz6ovzl) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe43abda4725546470ef0c05dc58b2e8280c8bc/pkg/sql/information_schema.go#L430)):*
> ```Go
> 			func(db *sqlbase.DatabaseDescriptor, table *sqlbase.TableDescriptor) error {
> 				appendRow := func(index sqlbase.IndexDescriptor, colName string, sequence int,
> 					direction string, isStored bool) error {
> ```

`direction` has a limited set of values (ASC, DESC, N/A). It's probably worth making constants for these values (see `tableTypeSystemView`)

---

*[pkg/sql/information_schema.go, line 432 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10220#-KV2dYc3zn8ZpuIfavLa:-KV2dYc4G-rGFGGaQhTo:b-mchi8s) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe43abda4725546470ef0c05dc58b2e8280c8bc/pkg/sql/information_schema.go#L432)):*
> ```Go
> 					direction string, isStored bool) error {
> 					return addRow(
> 						parser.NewDString("def"),                     //table_catalog
> ```

Use `defString` here

---

*[pkg/sql/information_schema.go, line 432 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10220#-KV2liP8aqiOapUsFyia:-KV2liP8aqiOapUsFyib:btkgmmf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe43abda4725546470ef0c05dc58b2e8280c8bc/pkg/sql/information_schema.go#L432)):*
> ```Go
> 					direction string, isStored bool) error {
> 					return addRow(
> 						parser.NewDString("def"),                     //table_catalog
> ```

nit: The comments has traditionally had a space after `//`

---

*[pkg/sql/information_schema.go, line 447 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10220#-KV2dPv4qYlnlY3HiHdd:-KV2dPv4qYlnlY3HiHde:b5x6efd) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe43abda4725546470ef0c05dc58b2e8280c8bc/pkg/sql/information_schema.go#L447)):*
> ```Go
> 				}
> 
> 				for _, index := range append([]sqlbase.IndexDescriptor{table.PrimaryIndex}, table.Indexes...) {
> ```

We have a line length limit of 100 characters.

---

*[pkg/sql/information_schema.go, line 447 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10220#-KV2dnGyYQXUfQRsdLbk:-KV2dnGyYQXUfQRsdLbl:b-23zh6b) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe43abda4725546470ef0c05dc58b2e8280c8bc/pkg/sql/information_schema.go#L447)):*
> ```Go
> 				}
> 
> 				for _, index := range append([]sqlbase.IndexDescriptor{table.PrimaryIndex}, table.Indexes...) {
> ```

See `forEachIndexInTable`

---

*[pkg/sql/information_schema.go, line 449 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10220#-KV2kycmrchlUuT20LJK:-KV2kycmrchlUuT20LJL:b-hoiozi) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe43abda4725546470ef0c05dc58b2e8280c8bc/pkg/sql/information_schema.go#L449)):*
> ```Go
> 				for _, index := range append([]sqlbase.IndexDescriptor{table.PrimaryIndex}, table.Indexes...) {
> 					sequence := 1
> 					for i, col := range index.ColumnNames {
> ```

This deserves a quick comment. Something like "We add a row for each..."

---

*[pkg/sql/testdata/information_schema, line 667 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10220#-KV2e7q6J8-BQq0n-QcV:-KV2e7q6J8-BQq0n-QcW:b-tqpo2g) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe43abda4725546470ef0c05dc58b2e8280c8bc/pkg/sql/testdata/information_schema#L667)):*
> ```
> ## information_schema.statistics
> statement ok
> CREATE TABLE other_db.cde(id INT PRIMARY KEY, c INT, d INT, e STRING, INDEX idx_c(c), UNIQUE INDEX idx_cd(c,d))
> ```

`cde`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10220#-:-KV2m-Ri_uqdVwsAEWGE:b-canrak)*

**Comment by yznming** [comment]
*[pkg/sql/information_schema.go, line 421 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10220#-KV2d0DN3Tj3R52_l70A:-KV36yoEC8ckW0Pi-joa:br9u61n) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe43abda4725546470ef0c05dc58b2e8280c8bc/pkg/sql/information_schema.go#L421)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Why the quotes?
</details>
`collation` is a key word. Create table would execute failed without the quote.
```
F161027 11:16:38.445281 1 sql/executor.go:289  [startup] syntax error at or near "COLLATION"                                                                       
                                                                                                                                                                   
CREATE TABLE information_schema.statistics (                                                                                                                       
        TABLE_CATALOG STRING NOT NULL DEFAULT '',                                                                                                                  
        TABLE_SCHEMA STRING NOT NULL DEFAULT '',                                                                                                                   
        TABLE_NAME STRING NOT NULL DEFAULT '',                                                                                                                     
        NON_UNIQUE BOOL NOT NULL DEFAULT FALSE,                                                                                                                    
        INDEX_SCHEMA STRING NOT NULL DEFAULT '',                                                                                                                   
        INDEX_NAME STRING NOT NULL DEFAULT '',                                                                                                                     
        SEQ_IN_INDEX INT NOT NULL DEFAULT 0,                                                                                                                       
        COLUMN_NAME STRING NOT NULL DEFAULT '',                                                                                                                    
        COLLATION STRING NOT NULL DEFAULT '',                                                                                                                      
 ^                                             
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10220)*
<!-- Sent from Reviewable.io -->

**Comment by yznming** [comment]
*[pkg/sql/testdata/information_schema, line 667 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10220#-KV2e7q6J8-BQq0n-QcV:-KV3Erl6lPlY-1y4xpb_:b-4071a) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe43abda4725546470ef0c05dc58b2e8280c8bc/pkg/sql/testdata/information_schema#L667)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> `cde`?
</details>
sorry, it doesn't means 'Color Doppler Energy' here. I would change the table name .

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10220)*

**Comment by nvanbenschoten** [comment]
:lgtm: other than the one final comment. Thanks!

---

Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[pkg/sql/information_schema.go, line 321 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10220#-KV7FarfRs08grN39RDW:-KV7FarfRs08grN39RDX:b-ra8f52) ([raw file](https://github.com/cockroachdb/cockroach/blob/25627f7e519abb77ffca67a78f437380f7da08bb/pkg/sql/information_schema.go#L321)):*
> ```Go
> 					}
> 					for _, col := range index.StoreColumnNames {
> 						// We add a row for each column of index
> ```

"for each stored column"

also, punctuation is needed here and above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10220#-:-KV7FxfhfjmGiMepF1tm:b-pxa1gm)*

**Pull request merged**
