### PR TITLE
docgen: update URL in logging doc

### PR DESCRIPTION
**Pull request by taroface**
Changed a docs URL that will be updated in https://github.com/cockroachdb/docs/pull/16151

Epic: none

Release note: none

Release justification: non-production code change

### CODE REVIEW

**Review by nickvigilante — APPROVED** [review]

**Comment by taroface** [comment]
bors r=nickvigilante

**Comment by taroface** [comment]
bors r=nickvigilante

**Comment by taroface** [comment]
@nickvigilante It looks like there was a flake in one of the tests, but let me know if I'm wrong. Can you help me re-run the build?

**Comment by taroface** [comment]
blathers backport 22.2

**Pull request merged**
