### PR TITLE
sql/mutations: add stats injector + refactor

### PR DESCRIPTION
**Pull request by madelynnblue**

### CODE REVIEW

**Comment by mjibson** [comment]
@rohany can you review the first commit?

@rytaft can you review the second commit?

**Comment by rohany** [comment]
First commit LGTM

**Review by rytaft — APPROVED** [review]
Second commit :LGTM:

> Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42448#-:-LtaeyymEdOvV8U_2Xzb:bbskxhq)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mjibson and @rohany)

___
*[pkg/sql/mutations/mutations.go, line 143 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42448#-LtaeHsF-WJaIdefepH3:-LtaeHsF-WJaIdefepH4:bw7sqjw) ([raw file](https://github.com/cockroachdb/cockroach/blob/93cde453ba1dcb611e0faa30891630166ae091f6/pkg/sql/mutations/mutations.go#L143)):*
> ```Go
> 			rowCount = rng.Int63()
> 		}
> 		fmt.Println("ROWCOUNT", rowCount)
> ```

Should this be here?

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42448)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rohany and @rytaft)

___
*[pkg/sql/mutations/mutations.go, line 143 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42448#-LtaeHsF-WJaIdefepH3:-LtalG1u7zLFn9Xx0KSt:b-feepo5) ([raw file](https://github.com/cockroachdb/cockroach/blob/93cde453ba1dcb611e0faa30891630166ae091f6/pkg/sql/mutations/mutations.go#L143)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Should this be here?
</blockquote></details>

Oops. Removed, thanks.

**Pull request merged**
