### PR TITLE
[wip] sql: Create benchmark test for multi-row statements involving FKs

### PR DESCRIPTION
**Pull request by emsal0**
Release note: None

### CODE REVIEW

**Comment by emsal1863** [comment]
This is only one benchmark, I will definitely need to add more.

**Comment by BramGruneir** [comment]
So the code looks ok.  But think about the scenarios you want to test.  We do want to test extremes, like this 10000 to 1.  But this is being inserted in a single batch.  Is this ideal?  Does that match a real use case? 

Perhaps before we add any fk benchmarks, come up with a plan of the benchmarks you think are required and we can send that out for review and get some feedback.

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-:-LFJmpvQ4IuvgLshdA-J:b-73n38y)*

**Comment by BramGruneir** [comment]
Also, did you run this benchmark?  How did it perform?  How much slower is it than without having the fk constraint?

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-:-LFJnRw_96a6wgKtgb7o:b-yaocn7)*

**Comment by knz** [comment]
Emmanuel:

1)  it's common for PRs that propose benchmarks to include a copy of current measurements for reference and as a baseline. See for example commits 583db769089292fe41e0ff51c9be798177a09dc8 and 1f44de17e1236bbebc176d305c1f704524d2e9b1.

2) run your benchmarks with `-benchmem` to include memory stats.

**Comment by emsal1863** [comment]
I've added some "FK-less" benchmarks to compare the FK benchmarks against as a baseline.

Also, after a run of this I get the following:

```
BenchmarkMultiRowFKChecks/10KRows_NoFK-8         	2000000000	         0.00 ns/op	       0 B/op	       0 allocs/op
BenchmarkMultiRowFKChecks/10KRows_IdenticalFK-8  	       3	 333782404 ns/op	88810666 B/op	  493716 allocs/op

BenchmarkMultiRowFKChecks/SelfReferential_Delete-8         	       1	5939059383 ns/op	1598824728 B/op	 6403809 allocs/op
BenchmarkMultiRowFKChecks/SR_No_FK_Delete-8                	       1	2656026713 ns/op	400579768 B/op	 2121820 allocs/op
```

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-:-LFO2Tm-0669Z9VB8Se_:by0k381)*

**Comment by BramGruneir** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/sqlbase/fk_test.go, line 279 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-LFSnCQiCyNOPLqaBcjR:-LFSnCQj5oYLnNko_nJ5:b1gs6rn) ([raw file](https://github.com/cockroachdb/cockroach/blob/121e5c2ecf72dbd363321148f3296915549839f8/pkg/sql/sqlbase/fk_test.go#L279)):*
> ```Go
> 		var run bytes.Buffer
> 
> 		run.WriteString(`INSERT INTO example2(baz, foo) VALUES `)
> ```

it's probably bet to tear down and create new tables, just to be sure for each sub benchmark.

---

*[pkg/sql/sqlbase/fk_test.go, line 323 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-LFSnJxH3a97E3e7HPLc:-LFSnJxH3a97E3e7HPLd:bycpbqs) ([raw file](https://github.com/cockroachdb/cockroach/blob/121e5c2ecf72dbd363321148f3296915549839f8/pkg/sql/sqlbase/fk_test.go#L323)):*
> ```Go
> 		}
> 	})
> 	b.Run("SelfReferential_Delete", func(b *testing.B) {
> ```

Can you add tests with cascading deletes and one without for both no_FK_Deletes and with FK_Deletes?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26806)*

**Review by emsal0 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26806)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sqlbase/fk_test.go, line 279 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-LFSnCQiCyNOPLqaBcjR:-LHZSi-i1lGEjUX7AVtO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/121e5c2ecf72dbd363321148f3296915549839f8/pkg/sql/sqlbase/fk_test.go#L279)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

it's probably bet to tear down and create new tables, just to be sure for each sub benchmark.
</blockquote></details>

Done.

**Review by emsal0 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26806)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sqlbase/fk_test.go, line 323 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-LFSnJxH3a97E3e7HPLc:-LHZhdvk1qGt8R3TbOXi:b-ybwpjy) ([raw file](https://github.com/cockroachdb/cockroach/blob/121e5c2ecf72dbd363321148f3296915549839f8/pkg/sql/sqlbase/fk_test.go#L323)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Can you add tests with cascading deletes and one without for both no_FK_Deletes and with FK_Deletes?
</blockquote></details>

Done, unless I misread this comment; see `SelfReferential_SetNull_{NoFK_}Delete`

**Review by knz — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26806)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sqlbase/fk_test.go, line 219 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-LHbssoC0JXGIO1Qe2kv:-LHbssoC0JXGIO1Qe2kw:b-22wzcf) ([raw file](https://github.com/cockroachdb/cockroach/blob/96698d028b09cbaca1819ef71f89acd2e53fe46e/pkg/sql/sqlbase/fk_test.go#L219)):*
> ```Go
> }
> 
> // BenchmarkMultiRowFKChecks does a benchmark on a multi-row insert statement that has to check foreign keys.
> ```

The body of this benchmark should be extended with copious comments that explain:

- what is being benchmarked
- how the code works
- what is the relationship between the constants in the code and the measurements. For example it should be possible to easily answer the question "which constant should I update if I want to make this particular benchmark phase run twice as long"

**Comment by knz** [comment]
Other than that the PR looks good, but please request an additional review from Bram.

**Review by knz — APPROVED** [review]

**Review by emsal0 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26806)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sqlbase/fk_test.go, line 219 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-LHbssoC0JXGIO1Qe2kv:-LHdHnho15T33H14uuj2:bakcas4) ([raw file](https://github.com/cockroachdb/cockroach/blob/96698d028b09cbaca1819ef71f89acd2e53fe46e/pkg/sql/sqlbase/fk_test.go#L219)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

The body of this benchmark should be extended with copious comments that explain:

- what is being benchmarked
- how the code works
- what is the relationship between the constants in the code and the measurements. For example it should be possible to easily answer the question "which constant should I update if I want to make this particular benchmark phase run twice as long"
</blockquote></details>

Done, see if you like the new comments/where more description is needed

**Review by BramGruneir — CHANGES_REQUESTED** [review]
Great progress.  But we still need more here.

Please add a cascaded vs non-cascaded interleaved delete benchmarks.  (maybe in a follow up PR)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-:-LHdbbFs6jJoQF7VDQYq:b7d7ztl)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sqlbase/fk_test.go, line 220 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-LHdVdjPEFWie5Kkca0Q:-LHdVdjPEFWie5Kkca0R:b20ekpw) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f069453180cd10dbc276b7970fec2de54dcf6c9/pkg/sql/sqlbase/fk_test.go#L220)):*
> ```Go
> 
> // BenchmarkMultiRowFKChecks performs several benchmarks that pertain to operations involving foreign keys and cascades.
> // TODO
> ```

Leftover TODO Here.
___
*[pkg/sql/sqlbase/fk_test.go, line 230 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-LHdVlow1URRzksOV_QF:-LHdVlow1URRzksOV_QG:b-bvvbja) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f069453180cd10dbc276b7970fec2de54dcf6c9/pkg/sql/sqlbase/fk_test.go#L230)):*
> ```Go
> 	// 		on delete, it sets the reference field to null.
> 	schema1 := `
> CREATE TABLE IF NOT EXISTS example1(
> ```

Can we call this parent?  And example2 child?
___
*[pkg/sql/sqlbase/fk_test.go, line 266 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-LHdZicL7xkH45M2073H:-LHdZicM8evOKpeas9lk:b-dw2r08) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f069453180cd10dbc276b7970fec2de54dcf6c9/pkg/sql/sqlbase/fk_test.go#L266)):*
> ```Go
> 			}
> 		}
> 		run1 := `
> ```

What's the point of this?  Just to check to make sure its working.
___
*[pkg/sql/sqlbase/fk_test.go, line 289 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-LHdaZAVEh_8nJtEcH0r:-LHdaZAVEh_8nJtEcH0s:bb8h7m7) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f069453180cd10dbc276b7970fec2de54dcf6c9/pkg/sql/sqlbase/fk_test.go#L289)):*
> ```Go
> 	// In the first test, the rows have no foreign key references to rows in `example1`.
> 	// In the second, the rows all have references to a particular row in `example1`.
> 	// The benchmarks primarily measure how insert performance changes when foreign key checks are present.
> ```

I don't think this is entirely true.  
We should have four tables here, one without any FK relationships, one with.  So ParentNoFK, ChildNoFK and ParentFK, ChildFK.
___
*[pkg/sql/sqlbase/fk_test.go, line 310 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-LHdascjCsMktJd2095b:-LHdascjCsMktJd2095c:bqahxdh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f069453180cd10dbc276b7970fec2de54dcf6c9/pkg/sql/sqlbase/fk_test.go#L310)):*
> ```Go
> 		}
> 	})
> 	b.Run("10KRows_IdenticalFK", func(b *testing.B) {
> ```

So there are two cases here, one where the inserts reference the same parent row, one where they reference different ones.  I think this deserves two different benchmarks.
___
*[pkg/sql/sqlbase/fk_test.go, line 341 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-LHdb7L9CjDOF-bOeMcG:-LHdb7L9CjDOF-bOeMcH:b-42brnz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f069453180cd10dbc276b7970fec2de54dcf6c9/pkg/sql/sqlbase/fk_test.go#L341)):*
> ```Go
> 	// For the self-referential table benchmarks, `numSRRows` rows are inserted and there is again a contrast between
> 	// rows with foreign key references and those without.
> 	// This measures the performance of cascading deletes.
> ```

Again here, Let's use a table without any FK relationships and one with.

Is this one long chain, or are they all referencing a single value?  Again I think this is two benchmarks.

And we should also look at the delete performance of non-self-refenencing deletes as well.

**Review by emsal0 — COMMENTED** [review]
I've restructured the sub-benchmarks and updated the comments accordingly.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-:-LHi0nak8I9hvZs1s7oE:b-aswprm)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sqlbase/fk_test.go, line 220 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-LHdVdjPEFWie5Kkca0Q:-LHi0R2-EF2gw2dGcXFb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f069453180cd10dbc276b7970fec2de54dcf6c9/pkg/sql/sqlbase/fk_test.go#L220)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Leftover TODO Here.
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/fk_test.go, line 230 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-LHdVlow1URRzksOV_QF:-LHi0RvX0OGUdzyXaNhj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f069453180cd10dbc276b7970fec2de54dcf6c9/pkg/sql/sqlbase/fk_test.go#L230)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Can we call this parent?  And example2 child?
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/fk_test.go, line 266 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-LHdZicL7xkH45M2073H:-LHi0SeqA66nXJsvxI-2:b-ircux8) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f069453180cd10dbc276b7970fec2de54dcf6c9/pkg/sql/sqlbase/fk_test.go#L266)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

What's the point of this?  Just to check to make sure its working.
</blockquote></details>

Done - did more specific setup steps for each sub-benchmark
___
*[pkg/sql/sqlbase/fk_test.go, line 289 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-LHdaZAVEh_8nJtEcH0r:-LHi0_HNE9Izw0aoiPS7:b-tsujc) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f069453180cd10dbc276b7970fec2de54dcf6c9/pkg/sql/sqlbase/fk_test.go#L289)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

I don't think this is entirely true.  
We should have four tables here, one without any FK relationships, one with.  So ParentNoFK, ChildNoFK and ParentFK, ChildFK.
</blockquote></details>

Done - see new tests
___
*[pkg/sql/sqlbase/fk_test.go, line 310 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-LHdascjCsMktJd2095b:-LHi0elP8k7O-zlePuFd:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f069453180cd10dbc276b7970fec2de54dcf6c9/pkg/sql/sqlbase/fk_test.go#L310)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

So there are two cases here, one where the inserts reference the same parent row, one where they reference different ones.  I think this deserves two different benchmarks.
</blockquote></details>

Done
___
*[pkg/sql/sqlbase/fk_test.go, line 341 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-LHdb7L9CjDOF-bOeMcG:-LHi0g8K6NMQKShfvU3s:bf6ju7k) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f069453180cd10dbc276b7970fec2de54dcf6c9/pkg/sql/sqlbase/fk_test.go#L341)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Again here, Let's use a table without any FK relationships and one with.

Is this one long chain, or are they all referencing a single value?  Again I think this is two benchmarks.

And we should also look at the delete performance of non-self-refenencing deletes as well.
</blockquote></details>

Done

In addition to long chain I added benchmarks for the case where many children reference one parent row in the self referential table.

**Review by BramGruneir — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r10, 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26806)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sqlbase/fk_test.go, line 223 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-LHiuiwn9A4Z-REwanJX:-LHiuiwo5EV-_Ds1NkC8:bxqntaw) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd283a33d230eeb8096dab967b951794acdd6b9b/pkg/sql/sqlbase/fk_test.go#L223)):*
> ```Go
> 	// torn down at the end of each sub-benchmark.
> 	// `childFK` has a foreign key that references `parentFK`.
> 	parentFKSchema := `
> ```

Put these in one array struct.  That's got 

 fktables :] []struct {
  name string
  schema string
} {
...
}

Just for readability
___
*[pkg/sql/sqlbase/fk_test.go, line 313 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-LHivb8iCFLcarDqNmfH:-LHivb8iCFLcarDqNmfI:b-jac69l) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd283a33d230eeb8096dab967b951794acdd6b9b/pkg/sql/sqlbase/fk_test.go#L313)):*
> ```Go
> 
> 	// run an initial drop to make sure we're clean
> 	drop()
> ```

not needed if setup calls drop
___
*[pkg/sql/sqlbase/fk_test.go, line 349 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-LHivPeN9aYyUzrTDtH1:-LHivPeN9aYyUzrTDtH2:ba32syl) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd283a33d230eeb8096dab967b951794acdd6b9b/pkg/sql/sqlbase/fk_test.go#L349)):*
> ```Go
> 	b.Run("deleteRows_IdenticalFK", func(b *testing.B) {
> 		drop()
> 		setup()
> ```

just have setup call drop, and just in case, have defer drop after setup.

**Review by emsal0 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26806)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sqlbase/fk_test.go, line 223 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-LHiuiwn9A4Z-REwanJX:-LI6DToV7awr2nLH5Ddw:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd283a33d230eeb8096dab967b951794acdd6b9b/pkg/sql/sqlbase/fk_test.go#L223)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Put these in one array struct.  That's got 

 fktables :] []struct {
  name string
  schema string
} {
...
}

Just for readability
</blockquote></details>

Done
___
*[pkg/sql/sqlbase/fk_test.go, line 313 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-LHivb8iCFLcarDqNmfH:-LI6DVIxC45O6WhIPQS1:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd283a33d230eeb8096dab967b951794acdd6b9b/pkg/sql/sqlbase/fk_test.go#L313)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

not needed if setup calls drop
</blockquote></details>

Done
___
*[pkg/sql/sqlbase/fk_test.go, line 349 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-LHivPeN9aYyUzrTDtH1:-LI6DUlGEdckIsrM2GuB:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd283a33d230eeb8096dab967b951794acdd6b9b/pkg/sql/sqlbase/fk_test.go#L349)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

just have setup call drop, and just in case, have defer drop after setup.
</blockquote></details>

Done

**Review by BramGruneir — CHANGES_REQUESTED** [review]
This is looking really good.  Almost ready to merge.

Once you make those last changes, can you run the benchmarks to get a baseline?

> Reviewed 1 of 1 files at r17.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-:-LI6TTTQ6WhW8uKGyaW0:bmrjeoh)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sqlbase/fk_test.go, line 223 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-LHiuiwn9A4Z-REwanJX:-LI6SFa_6MR4hZI-LtA8:b-9fh12s) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd283a33d230eeb8096dab967b951794acdd6b9b/pkg/sql/sqlbase/fk_test.go#L223)):*
<details><summary><i>Previously, emsal1863 (Emmanuel Sales) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Just had a thought while reading this through.  Put this in a map, then you can access the table by name.
___
*[pkg/sql/sqlbase/fk_test.go, line 318 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-LI6SORsDFQVBKsxe1K7:-LI6SORsDFQVBKsxe1K8:b-71jf1e) ([raw file](https://github.com/cockroachdb/cockroach/blob/f506e64b0ad59a537789fc3349109fddd610bf34/pkg/sql/sqlbase/fk_test.go#L318)):*
> ```Go
> 	// This function tears down all the tables and is meant to be called at the beginning and  end of each sub-benchmark.
> 	drop := func() {
> 		// dropping has to be done in reverse so no drop causes a foreign key violation
> ```

You can also add `CASCADE` to the drop statement too.
___
*[pkg/sql/sqlbase/fk_test.go, line 327 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-LI6TMgD-4wsWsnH8MMC:-LI6TMgD-4wsWsnH8MMD:bo48qdb) ([raw file](https://github.com/cockroachdb/cockroach/blob/f506e64b0ad59a537789fc3349109fddd610bf34/pkg/sql/sqlbase/fk_test.go#L327)):*
> ```Go
> 
> 	// This function is to be called at the beginning of each sub-benchmark to set up the necessary tables.
> 	setup := func() {
> ```

Make setup take the names of the tables being added, so you don't need to add tables that are not used in a test.

**Review by emsal0 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26806)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/sqlbase/fk_test.go, line 223 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-LHiuiwn9A4Z-REwanJX:-LIBdEvl5I2IzTBn-zYm:b-hk1vql) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd283a33d230eeb8096dab967b951794acdd6b9b/pkg/sql/sqlbase/fk_test.go#L223)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Just had a thought while reading this through.  Put this in a map, then you can access the table by name.
</blockquote></details>

The only way the structure is used is by iteration, not by accessing any particular schema. Turning this into a map actually makes it more difficult to iterate over because iterating on a map iterates over the keys out-of-order.
___
*[pkg/sql/sqlbase/fk_test.go, line 318 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-LI6SORsDFQVBKsxe1K7:-LIBfZodAhKTdcvGfseX:b-hbhuww) ([raw file](https://github.com/cockroachdb/cockroach/blob/f506e64b0ad59a537789fc3349109fddd610bf34/pkg/sql/sqlbase/fk_test.go#L318)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

You can also add `CASCADE` to the drop statement too.
</blockquote></details>

Done, now more natural iteration
___
*[pkg/sql/sqlbase/fk_test.go, line 327 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-LI6TMgD-4wsWsnH8MMC:-LIBfSEI-qNg69A8Z5KH:b-896fjb) ([raw file](https://github.com/cockroachdb/cockroach/blob/f506e64b0ad59a537789fc3349109fddd610bf34/pkg/sql/sqlbase/fk_test.go#L327)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Make setup take the names of the tables being added, so you don't need to add tables that are not used in a test.
</blockquote></details>

Done

**Comment by emsal1863** [comment]
here's the result of a run, let me know if anything is fishy

```
BenchmarkMultiRowFKChecks/insertRows_IdenticalFK-8                                  	               2          	          511461207     ns/op
BenchmarkMultiRowFKChecks/deleteRows_IdenticalFK-8                                  	               1          	          1354106068    ns/op
BenchmarkMultiRowFKChecks/insertRows_UniqueFKs-8                                      	               1          	          1559161162    ns/op
BenchmarkMultiRowFKChecks/deleteRows_UniqueFKs-8                                      	               1          	          1187440427    ns/op
BenchmarkMultiRowFKChecks/insertRows_NoFK-8                                                	       50         	          21042415      ns/op
BenchmarkMultiRowFKChecks/deleteRows_NoFK-8                                                	       2000000000 	          0.12          ns/op
BenchmarkMultiRowFKChecks/insertRows_multiple_refs-8                              	                   1          	          2679001389    ns/op
BenchmarkMultiRowFKChecks/deleteRows_multiple_refs-8                              	                   5          	          202168434     ns/op
BenchmarkMultiRowFKChecks/insertRows_multiple_refs_noFK-8                    	                       300        	          3340552       ns/op
BenchmarkMultiRowFKChecks/deleteRows_multiple_refs_No_FK-8                  	                       2000000000 	          0.12          ns/op
BenchmarkMultiRowFKChecks/insertRows_interleaved-8                                  	               2000000000 	          0.36          ns/op
BenchmarkMultiRowFKChecks/deleteRows_interleaved-8                                  	               2000000000 	          0.19          ns/op
BenchmarkMultiRowFKChecks/SelfReferential_Cascade_FK_Chain_Delete-8                 	               1          	          10050644101   ns/op
BenchmarkMultiRowFKChecks/SelfReferential_Cascade_FK_ManyChildren_Delete-8   	                       1          	          3550952975    ns/op
BenchmarkMultiRowFKChecks/SelfReferential_No_FK_Chain_Delete-8                           	           2000000000 	          0.08          ns/op
BenchmarkMultiRowFKChecks/SelfReferential_No_FK_ManyChildren_Delete-8             	                   1000000000 	          0.06          ns/op
BenchmarkMultiRowFKChecks/SelfReferential_SetNull_FK_Chain_Delete-8                 	               1          	          9889315916    ns/op
BenchmarkMultiRowFKChecks/SelfReferential_SetNull_FK_ManyChildren-8                 	               1          	          5305118658    ns/op
```

**Review by BramGruneir — APPROVED** [review]
:lgtm: With one final change request.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-:-LICLNZn47B1lArsjUzI:b-d60by8)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/sqlbase/fk_test.go, line 223 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-LHiuiwn9A4Z-REwanJX:-LICKyr33XatNozGXPNO:bw1mxqc) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd283a33d230eeb8096dab967b951794acdd6b9b/pkg/sql/sqlbase/fk_test.go#L223)):*
<details><summary><i>Previously, emsal1863 (Emmanuel Sales) wrote…</i></summary><blockquote>

The only way the structure is used is by iteration, not by accessing any particular schema. Turning this into a map actually makes it more difficult to iterate over because iterating on a map iterates over the keys out-of-order.
</blockquote></details>

See my comment below, I still think this should be a map.
___
*[pkg/sql/sqlbase/fk_test.go, line 327 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-LI6TMgD-4wsWsnH8MMC:-LICKn_nDREYLdKGPu8P:b-ahcyw8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f506e64b0ad59a537789fc3349109fddd610bf34/pkg/sql/sqlbase/fk_test.go#L327)):*
<details><summary><i>Previously, emsal1863 (Emmanuel Sales) wrote…</i></summary><blockquote>

Done 
</blockquote></details>

Instead of a hashtable, why not just a slice of strings?

So when you're passing in a slice of strings to setup, you can ensure the order they will be created in.

**Review by emsal0 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26806)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/sqlbase/fk_test.go, line 223 at r13](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-LHiuiwn9A4Z-REwanJX:-LICZjlX4lOhIC9tgouv:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd283a33d230eeb8096dab967b951794acdd6b9b/pkg/sql/sqlbase/fk_test.go#L223)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

See my comment below, I still think this should be a map.
</blockquote></details>

Done
___
*[pkg/sql/sqlbase/fk_test.go, line 327 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/26806#-LI6TMgD-4wsWsnH8MMC:-LICZj0J0PA6uaAGodxm:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f506e64b0ad59a537789fc3349109fddd610bf34/pkg/sql/sqlbase/fk_test.go#L327)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Instead of a hashtable, why not just a slice of strings?

So when you're passing in a slice of strings to setup, you can ensure the order they will be created in.
</blockquote></details>

Done

**Review by BramGruneir — APPROVED** [review]
> Reviewed 1 of 1 files at r20.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26806)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by BramGruneir** [comment]
Can you update the commit message to list the names of the specific benchmarks that you've added.

**Pull request merged**
