### PR TITLE
roachprod: made it possible to specify number of nodes per zone with the

### PR DESCRIPTION
**Pull request by rkruze**
--aws-dist flag has been added to allow for specifying the exact number of nodes to deploy into each zone. This starts to address https://github.com/cockroachdb/cockroach/issues/43499, at least for AWS.

### CODE REVIEW

**Comment by ajwerner** [comment]
Can you provide an example of how to use this in the commit message?

**Comment by ajwerner** [comment]
I think bram actually addressed #43499 in #40931, unless I misunderstand. If the number of zones passed to `--aws-zones` is exactly the same length as the number of nodes, the zone for each node will correspond to its entry in `--aws-zones`.

**Comment by rkruze** [comment]
I've updated the commit message. I don't believe https://github.com/cockroachdb/cockroach/pull/40931 addresses this as with this I want to be able to specify either having 5,10 or 15 nodes in a given zone.

**Comment by ajwerner** [comment]
> I've updated the commit message. I don't believe #40931 addresses this as with this I want to be able to specify either having 5,10 or 15 nodes in a given zone.

It's onerous to use but I think #40931 does address that. Say you want to have 30 nodes with 5 in zone a, 10 in zone b and 15 in zone c. You'd do that by doing something like:

`roachprod create ajwerner-test -n30 --clouds aws --geo --aws-zones $(python -c 'print(",".join(["us-east-1a"]*5 + ["us-east-1b"]*10 + ["us-east-1c"]*15))' )`

**Comment by ajwerner** [comment]
I've verified that the above command works as described.

**Comment by rkruze** [comment]
Your example works as it is in only one region. If you cross regions this doesn't work as expected. For example: `./bin/roachprod create roko-test -n10 --clouds aws --geo --aws-zones $(python -c 'print(",".join(["us-east-1a"]*2 + ["us-east-1b"]*2 + ["us-east-1c"]*2 + ["us-west-2a"]*4))' )` 

Build a cluster which looks like the following: 
image

**Comment by ajwerner** [comment]
Alright, I dug in a bit more and it seems like the GCP code works the way you'd like. The AWS code behaves a bit differently by treating different regions independently for placement. We probably don't want that. Rather I'd think that we want to treat AWS just like GCP. I can't think of any specific reason that we want to keep it the way that it is. 

I've created a new PR https://github.com/cockroachdb/cockroach/pull/43700 that should have the behavior you're looking for. PTAL.

**Comment by knz** [comment]
Before this merges, the PR title and commit messages need to be cleaned up.

See https://wiki.crdb.io/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages

**Comment by rkruze** [comment]
It looks like we won't be merged, so I'll close the PR. I do find having to list out each zone for each node to be onerous and not something that is intuitive.

**Pull request closed without merging**
