### PR TITLE
sql: fix overload type checking of nested case expressions

### LINKED ISSUE #101418: internal error: failed to parse locale "": language: tag is not well-formed
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

The following program triggers an internal error:
```
USE test;
DROP DATABASE IF EXISTS database16 CASCADE;
CREATE DATABASE database16;
USE database16;
CREATE TABLE t0 (c0 SMALLINT, c1 STRING COLLATE cmn);
CREATE TABLE t1 (c0 BOOL);
UPSERT INTO t1 (c0) VALUES(true);
SELECT t1.rowid FROM t1 WHERE ((CASE  WHEN false THEN CASE  WHEN (NOT (false)) THEN NULL END ELSE ((((''))) COLLATE es) END)>=(SELECT MAX(t0.c1) AS c0 FROM t0));
```

The error message:
```
> SELECT t1.rowid FROM t1 WHERE ((CASE  WHEN false THEN CASE  WHEN (NOT (false)) THEN NULL END ELSE ((((''))) COLLATE es) END)>=(SELECT MAX(t0.c1) AS c0 FROM t0));
ERROR: internal error: failed to parse locale "": language: tag is not well-formed
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/sql/sem/tree/datum.go:1381: getCacheEntry()
github.com/cockroachdb/cockroach/pkg/sql/sem/tree/datum.go:1396: NewDCollatedString()
github.com/cockroachdb/cockroach/pkg/sql/sem/eval/cast.go:525: performCastWithoutPrecisionTruncation()
github.com/cockroachdb/cockroach/pkg/sql/sem/eval/cast.go:68: PerformCast()
github.com/cockroachdb/cockroach/bazel-out/k8-fastbuild/bin/pkg/sql/colexec/colexecbase/cast.eg.go:14918: func1()
github.com/cockroachdb/cockroach/pkg/sql/colmem/allocator.go:460: PerformOperation()
github.com/cockroachdb/cockroach/bazel-out/k8-fastbuild/bin/pkg/sql/colexec/colexecbase/cast.eg.go:14784: Next()
github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/operator.go:157: Next()
github.com/cockroachdb/cockroach/bazel-out/k8-fastbuild/bin/pkg/sql/colexec/colexecbase/const.eg.go:611: Next()
github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/operator.go:157: Next()
github.com/cockroachdb/cockroach/bazel-out/k8-fastbuild/bin/pkg/sql/colexec/colexecbase/cast.eg.go:1199: Next()
github.com/cockroachdb/cockroach/bazel-out/k8-fastbuild/bin/pkg/sql/colexec/colexecsel/selection_ops.eg.go:56977: Next()
github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecbase/simple_project.go:124: Next()
github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:118: next()
github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92: CatchVectorizedRuntimeError()
github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:126: Next()
github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:250: nextAdapter()
github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92: CatchVectorizedRuntimeError()
github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:254: next()
github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:286: Run()
github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:317: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:902: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1913: PlanAndRun()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1645: func3()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1648: PlanAndRunAll()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2090: execWithDistSQLEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1648: dispatchToExecutionEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:963: execStmtInOpenState()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:141: func1()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2979: execWithProfiling()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:140: execStmt()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2169: func1()

HINT: You have encountered an unexpected error.

Please check the public issue tracker to check whether this problem is
already tracked. If you cannot find it there, please report the error
with details by creating a new issue.

If you would rather not post publicly, please contact us directly
using the support form.

We appreciate your feedback.
```
**To Reproduce**

I build CockroachDB from last commit version (https://github.com/cockroachdb/cockroach/commit/678cfd4cbebbf3cced16747baf42a4c54cb2a92d), run the program with CLI

**Expected behavior**
No error.

**Environment:**
 - CockroachDB version https://github.com/cockroachdb/cockroach/commit/678cfd4cbebbf3cced16747baf42a4c54cb2a92d
 - Server OS: [Ubuntu 22.04]
 - Client app [CLI]

Jira issue: CRDB-26936

### PR DESCRIPTION
**Pull request by cucaroach**
If we have a nested case expression where the inner case expression
is ambiguous the AnyCollatedString type would be selected and it would
leak to the execution engine causing the 'failed to parse locale ""'
internal error. Instead have the overload type checker remember if
it saw a AnyCollatedString type and go back and repair types if a
concrete type is found in any of the other exprs.

Release note: none
Epic: none
Fixes: #101418

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108199#-:-NbGfklM9V8hxhoH1BOm:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108199#-NbGfhHm5PE0ZFz6dBtz):*
nit: `Release note` has to be last, doesn't it?
___
*[`pkg/sql/sem/tree/overload.go` line 882 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108199#-NbGfEkb8PE2f991ZMpj:-NbGfEkb8PE2f991ZMpk:b-vp7mgv) ([raw file](https://github.com/cockroachdb/cockroach/blob/3871b1b528d14438d3135424ea374cecea2b2e81/pkg/sql/sem/tree/overload.go#L882)):*
> ```Go
> 				}
> 			}
> 		}
> ```

Good job finding another place where our semantic analysis diverges from Postgres. I think we're still not consistent with how PG determines collation, specifically the rules regarding implicit and explicit collation mentioned here: https://www.postgresql.org/docs/current/collation.html#id-1.6.11.4.4

But this is better than erroring like before. Maybe leave a TODO to mark that this isn't perfect yet?
___
*[`pkg/sql/sem/tree/type_check_test.go` line 484 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108199#-NbGdAqD6_XZvPj9jzGR:-NbGdAqD6_XZvPj9jzGS:buql2p6) ([raw file](https://github.com/cockroachdb/cockroach/blob/3871b1b528d14438d3135424ea374cecea2b2e81/pkg/sql/sem/tree/type_check_test.go#L484)):*
> ```Go
> 	// Typecheck without any restrictions.
> 	semaCtx := tree.MakeSemaContext()
> 	semaCtx.Properties.Require("", 0 /* flags */)
> ```

nit: Is this line necessary if there are no flags being passed?

**Review by cucaroach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108199)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108199#-NbGfhHm5PE0ZFz6dBtz):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: `Release note` has to be last, doesn't it?
</blockquote></details>

News to me, its never occurred to me to order them.   Looking over my commits I seem to randomize the order.
___
*[`pkg/sql/sem/tree/overload.go` line 882 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108199#-NbGfEkb8PE2f991ZMpj:-NbGqariB2oNoF0hR8Cb:b-80tlqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/3871b1b528d14438d3135424ea374cecea2b2e81/pkg/sql/sem/tree/overload.go#L882)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Good job finding another place where our semantic analysis diverges from Postgres. I think we're still not consistent with how PG determines collation, specifically the rules regarding implicit and explicit collation mentioned here: https://www.postgresql.org/docs/current/collation.html#id-1.6.11.4.4

But this is better than erroring like before. Maybe leave a TODO to mark that this isn't perfect yet?
</blockquote></details>

Sure.

**Review by cucaroach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108199)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[`pkg/sql/sem/tree/type_check_test.go` line 484 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108199#-NbGdAqD6_XZvPj9jzGR:-NbGrJ0u8kvST8GZkz2t:b-if55xl) ([raw file](https://github.com/cockroachdb/cockroach/blob/3871b1b528d14438d3135424ea374cecea2b2e81/pkg/sql/sem/tree/type_check_test.go#L484)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: Is this line necessary if there are no flags being passed?
</blockquote></details>

Nope appears not, copy-pasta.

**Review by mgartner — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108199)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108199#-NbGfhHm5PE0ZFz6dBtz):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

News to me, its never occurred to me to order them.   Looking over my commits I seem to randomize the order.
</blockquote></details>

:+1: 
___
*[`pkg/sql/sem/tree/overload.go` line 882 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108199#-NbGfEkb8PE2f991ZMpj:-NbGvXDI8tN2SD4H_2GD:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/3871b1b528d14438d3135424ea374cecea2b2e81/pkg/sql/sem/tree/overload.go#L882)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

Sure.
</blockquote></details>

Thanks!

**Comment by cucaroach** [comment]
bors r=mgartner

**Pull request merged**
