### PR TITLE
release-21.1: distsql: eagerly cancel remote flows on a query error

### PR DESCRIPTION
**Pull request by yuzefovich**
Backport 1/2 commits from #65073.
Backport 1/1 commits from #66301.

/cc @cockroachdb/release

---

**distsql: eagerly cancel remote flows on a query error**

This commit introduce another RPC to the DistSQLServer interface to
cancel scheduled flows (i.e. those setup via SetupFlow RPC) when the
relevant queries error out on the gateway. Previously, in such cases the
dead flows would be started on the remote nodes only to realize that the
consumer is gone and shut themselves down. However, this required
performing FlowStream RPC from the remote nodes. This commit fixes the
issue by eagerly canceling such abandoned flows.

This behavior is especially useful if the cluster is overwhelmed with
DistSQL flows and is hitting the limit (500 by default per node) on the
number active flows at once. If the load keeps on hammering the cluster,
and more and more flows will be queued up on the remote nodes, yet the
local (from the perspective of the gateway) flow errors out (e.g.
because it timed out waiting for the remote flows to connect), all those
queued up flows will be dead before they start.

Fixes: #64916.

Release note (sql change): The remote DistSQL flows are now eagerly
canceled if they were queued up and the query was canceled.

**flowinfra: fix a bug in recent CancelDeadFlows function**

We recently added `CancelDeadFlows` RPC to the DistSQLServer. This
method is essentially calling `CancelDeadFlows` on the flow scheduler.
It takes in a list of FlowIDs to cancel, iterates over the queue of the
flow scheduler, and removes all entries that are mentioned in the list
to cancel.

The iteration code currently has a bug which was introduced due to not
understanding `list.Element` interface. Namely, if we keep on calling
`Next`, eventually it will return `nil` once we have iterated over the
whole queue. However, our iteration code assumes that the queue element
is never `nil`. This commit fixes the problem and simplifies the
iteration code.

The code in Go SDK in `list/list_test.go` in `TestList` was used as
a reference.

Release note: None (no stable release with this bug)

### CODE REVIEW

**Comment by yuzefovich** [comment]
I'll hold off on merging this for a month or so, targeting 21.1.4 (scheduled to release on July 19th).

**Comment by yuzefovich** [comment]
Looks like there haven't any new issues found with this work on master, so I think we should backport it. @jordanlewis

**Review by rytaft — APPROVED** [review]
:lgtm: although I didn't review the original PRs and I didn't attempt to review in a lot of detail here. Might be worth a sanity check from @jordanlewis or someone else who reviewed the original PRs.

> Reviewed 13 of 13 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66331#-:-Me_D2wa1JNDzr37C4k7:b-d2btb7)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Comment by yuzefovich** [comment]
I think @jordanlewis was the main reviewer, but @mgartner also took a look.

**Comment by yuzefovich** [comment]
Looks like the SHA for 21.1.6 has already been picked, so there are a couple more weeks before 21.1.7 SHA is picked, so I'll wait till @jordanlewis gets some time to take a look at this backport.

**Comment by yuzefovich** [comment]
@jordanlewis let's get this merged, do I have your blessing?

**Comment by jordanlewis** [comment]
LGTM 👍

**Pull request merged**
