### PR TITLE
schemachanger: improve observability

### PR DESCRIPTION
**Pull request by postamar**
schemachanger: add test for declarative schema changer error details
    
    This commit adds a test that ensures that an error occurring during
    a declarative schema change job will be serialized and added to the job
    payload with all its details, which include a plan for the rollback and
    graphviz URLs.
    
    Touches #77158.
    
    Release note: None

----

    schemachanger: update declarative schema changer job running status
    
    Previously, declarative schema changer jobs did not populate the running
    status field. This commit addresses that by printing the previous and the
    subsequent stages to execute.
    
    Touches #77158.
    
    Release note: None

----

    sql: Add VIZ flag to EXPLAIN (DDL)
    
    Recently, EXPLAIN (DDL) was overhauled to produce a textual rendering of
    a declarative schema changer plan instead of a URL to a GraphViz
    rendering.
    
    While the former is arguably more useful to users, the latter is
    definitely useful to contributing engineers. This commit reintroduces
    this functionality under the VIZ flag. The output of EXPLAIN (DDL, VIZ)
    is now two URLs, one for the stage rendering and another for the
    dependency graph. A few commits ago, these would have been separately
    rendered via EXPLAIN (DDL, STAGES) or EXPLAIN (DDL, DEPS).
    
    Touches #77158.
    
    Release note: None

### CODE REVIEW

**Comment by postamar** [comment]
There's some flakiness due to overly-long running status strings, which I'll fix, otherwise this PR is ready for review.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, 24 of 24 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79867#-:-N-ZsVrD8-o-_UTly6sT:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @postamar)

___
*[pkg/sql/schemachanger/scplan/internal/scstage/build.go, line 494 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79867#-N-Zs4Ca3SpL10jJkJCs:-N-Zs4Ca3SpL10jJkJCt:bweul1v) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8def96b4a496224bbb118d6fefa2eda3474e4a1/pkg/sql/schemachanger/scplan/internal/scstage/build.go#L494)):*
> ```Go
> 		runningStatus := "all stages completed"
> 		if next != nil {
> 			runningStatus = fmt.Sprintf("%s pending", next)
> ```

nit: I don't think `pending` add a lot of value.

**Comment by postamar** [comment]
Thanks for the review!

bors r+

**Comment by postamar** [comment]
>  I don't think pending add a lot of value.

FWIW I found it unclear when that qualifier wasn't there and ended up confusing myself about what had happened vs what was going to happen.

**Pull request merged**
