### PR TITLE
changefeedccl: update row.Fetcher for key_only envelope and UDTs

### LINKED ISSUE #80976: changefeedccl: have rowfetchers only request the desired values
Currently, our rowfetcher code calls `rowenc.InitIndexFetchSpec` with `tableDesc.PublicColumnIDs()` as the list of desired columns. This should instead be a union of the primary key columns and the columns in the family being processed (we already have separate rowfetchers per family even if we're watching all of them). If using the `key_only` envelope, it should only be the primary key columns.

This didn't work when I tried it the first time, but it was probably a trivial bug in either my code or InitIndexFetchSpec code.

Jira issue: CRDB-15415

### PR DESCRIPTION
**Pull request by jayshrivastava**
### cdcevent: fetch only key columns when using key_only envelope
Previously, when using the key_only envelope, the row.Fetcher would fetch more
columns than just the key columns. These columns would be ignored during
encoding. This change makes is so that non-key columns are omitted at the
row.Fetcher level.

Release note: None

### cdcevent: do not invalidate cache for fam if UDT in different fam changes

Previously, we would evict an entry from the rowFetcherCache if any UDT was
updated. This PR makes it so that we only evict the entry if a UDT in a target
column family changes.

Release note: None

Fixes: https://github.com/cockroachdb/cockroach/issues/80976
Epic: none

### CODE REVIEW

**Review by HonoreDB — APPROVED** [review]
LGTM! I'd just suggest adding a test for the corner case where a UDT is referenced in a changefeed expression but not in any watched families. I think it'll pass, though. Something like

```
	sqlDB.Exec(t, `CREATE TYPE status AS ENUM ('open', 'closed', 'inactive')`)
	sqlDB.Exec(t, `CREATE TYPE priority AS ENUM ('high', 'low')`)
	sqlDB.Exec(t, `
		CREATE TABLE foo (
			a INT PRIMARY KEY,
			b status,
			c priority,
			FAMILY only_b (b),
			FAMILY only_c (c)
   )`)
foo := feed(t, `CREATE CHANGEFEED AS SELECT 'inactive'::status, c FROM foo`)
// mess with status udt
// touch foo records
// assert foo feed still evaluates correctly
// remove the inactive type from status udt
// touch foo records
// assert foo feed fails gracefully
```

> Reviewed 12 of 12 files at r1, 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90195#-:-NFF_oxXCuUb3jnx1ikJ:b-fqxa3k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava and @stevendanna)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90195#-NFFXwu8D9WIEsbym3-g):*
typo: s/is so/it so
___
*[`pkg/ccl/changefeedccl/changefeed_stmt.go` line 891 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90195#-NFFUgR7EJVKB3vlYvEP:-NFFUgR7EJVKB3vlYvEQ:b15rndo) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe03e65dfe0d1493613e8df6823f4f7bccab6249/pkg/ccl/changefeedccl/changefeed_stmt.go#L891)):*
> ```Go
> 	}
> 	return cdceval.NormalizeAndValidateSelectForTarget(
> 		ctx, execCtx, tableDescr, targets[0], sc, includeVirtual, keyOnly, splitColFams)
> ```

Nonblocking: At some point it'd be neat to retire keyOnly for changefeed expressions and give it a similar treatment to diff: if your SELECT clause is a constant expression, treat that as keyOnly everywhere but in the encoder.
___
*[`pkg/sql/catalog/table_elements.go` line 779 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90195#-NFFZSOoDlzVj25qVq5i:-NFFZSOs7Y23BuVq8Pcs:btudel5) ([raw file](https://github.com/cockroachdb/cockroach/blob/97a35b87a0a2bd28e0d75680249288b101a8eed2/pkg/sql/catalog/table_elements.go#L779)):*
> ```Go
> 	}
> 
> 	familyCols := util.FastIntSet{}
> ```

nit: `catalog.MakeTableColSet`
___
*[`pkg/ccl/changefeedccl/cdcevent/rowfetcher_test.go` line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90195#-NFF_g_t6IcdjWpJZQW4:-NFF_g_t6IcdjWpJZQW5:b10ca2m) ([raw file](https://github.com/cockroachdb/cockroach/blob/97a35b87a0a2bd28e0d75680249288b101a8eed2/pkg/ccl/changefeedccl/cdcevent/rowfetcher_test.go#L29)):*
> ```Go
> )
> 
> func TestRowFetcherCache(t *testing.T) {
> ```

Nice tests!

**Review by jayshrivastava — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90195)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @stevendanna)

___
*[`pkg/ccl/changefeedccl/changefeed_stmt.go` line 891 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90195#-NFFUgR7EJVKB3vlYvEP:-NFFu11K4LtH4u7UELE8:bmyark5) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe03e65dfe0d1493613e8df6823f4f7bccab6249/pkg/ccl/changefeedccl/changefeed_stmt.go#L891)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

Nonblocking: At some point it'd be neat to retire keyOnly for changefeed expressions and give it a similar treatment to diff: if your SELECT clause is a constant expression, treat that as keyOnly everywhere but in the encoder.
</blockquote></details>

Ack. I'll make an issue for this.

**Review by jayshrivastava — COMMENTED** [review]
Thanks for reviewing! I seem to be getting some errors when running creating the changefeed statement:

```
root@localhost:26257/defaultdb> CREATE CHANGEFEED WITH split_column_families AS SELECT 'inactive'::status, c FROM foo;
ERROR: undefined object with OID 100113
SQLSTATE: 42704

root@localhost:26257/defaultdb> CREATE CHANGEFEED WITH split_column_families AS SELECT 'inactive'::status from foo;
ERROR: using "AS SELECT" requires option schema_change_policy='stop'

root@localhost:26257/defaultdb> CREATE CHANGEFEED WITH split_column_families, schema_change_policy='stop' AS SELECT 'inactive'::status from foo;
ERROR: expressions can't reference columns from more than one column family
SQLSTATE: 22023


root@localhost:26257/defaultdb> CREATE CHANGEFEED WITH schema_change_policy='stop' AS SELECT 'inactive'::status from foo;
ERROR: CHANGEFEED targeting a table (foo) with multiple column families requires WITH split_column_families and will emit multiple events per row.
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90195#-:-NFG--US2KM9syhc8otp:bkujs8p)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @stevendanna)

**Comment by jayshrivastava** [comment]
Filed https://github.com/cockroachdb/cockroach/issues/90714, which blocks testing with UDTs in changefeed expressions.

**Pull request merged**
