### PR TITLE
opt: fix some issues with WITH

### PR DESCRIPTION
**Pull request by justinj**
This pair of commits fixes several issues involved with WITH planning, most notably around their use in prepared statements (or any situation where memos could get re-used).

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
Putting the logical properties in `WithScan` is great.. Why do we still need the `withExpr`s at all?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39047#-:-LkULrN41Wrb_x8meH5W:bhvdf73)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/memo/logical_props_builder.go, line 757 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39047#-LkUM_LuBf9GcrOmVVTc:-LkUM_LuBf9GcrOmVVTd:b-k4sjdx) ([raw file](https://github.com/cockroachdb/cockroach/blob/079c67d77789f47d90040b03060a5ea96d7b0bcc/pkg/sql/opt/memo/logical_props_builder.go#L757)):*
> ```Go
> 
> func (b *logicalPropsBuilder) buildWithScanProps(ref *WithScanExpr, rel *props.Relational) {
> 	e := b.mem.WithExpr(ref.ID)
> ```

Why do we need `e` now? We should just use `ref.Props`
___
*[pkg/sql/opt/ops/relational.opt, line 880 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39047#-LkUM2Ly92aKolhmEU4r:-LkUM2LzCB0GNu75ruvK:bbuy2kv) ([raw file](https://github.com/cockroachdb/cockroach/blob/079c67d77789f47d90040b03060a5ea96d7b0bcc/pkg/sql/opt/ops/relational.opt#L880)):*
> ```
> 
>     # Props stores the relational properties of the referenced expression.
>     Props RelPropsPtr
> ```

This should have a more specific name (e.g. `BindingProps`), because it's different conceptually from the `WithScan` properties. And maybe it belongs next to the `ID`

**Review by rytaft — APPROVED** [review]
in commit message flimsly -> flimsy

otherwise, :LGTM:

> Reviewed 5 of 5 files at r1, 4 of 7 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39047#-:-LkZBswO-H5aKfMLbo9p:b-1ceqid)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj)

**Review by justinj — COMMENTED** [review]
We still need them to compute colStats (which we can do over non-parameterized columns), unless you had a different idea for how we could do that? I know we talked about having a callback... Going to merge this as I let it sit for a while, but happy to revisit storing the `withExpr`s

TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39047#-:-LkUrxdI3el7O11RsUij:b-ftlpkj)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj and @rytaft)

___
*[pkg/sql/opt/memo/logical_props_builder.go, line 757 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39047#-LkUM_LuBf9GcrOmVVTc:-LkUs_Kj9PXwt0vEricd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/079c67d77789f47d90040b03060a5ea96d7b0bcc/pkg/sql/opt/memo/logical_props_builder.go#L757)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Why do we need `e` now? We should just use `ref.Props`
</blockquote></details>

Done.

**Comment by RaduBerinde** [comment]
I thought we discussed that we won't support calculating new column stats for `WithRef`s.

**Comment by justinj** [comment]
Ah right, I had forgotten about that, I'll open a new PR removing the withExprs.

**Pull request merged**
