### PR TITLE
ui: do not set timeout on raftDebug

### PR DESCRIPTION
**Pull request by tamird**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8647)

### CODE REVIEW

**Comment by bdarnell** [comment]
LGTM to merge to master, but I defer to Max or Matt for the actual review. 

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8647#-:-KPTZsRUYB3OuMQClM5-:bw8sgfz)*

**Comment by maxlang** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[ui/app/redux/apiReducers.ts, line 15 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8647#-KPTw7VHOKYoe_-7h6kD:-KPTw7VHOKYoe_-7h6kE:blvys3u) ([raw file](https://github.com/cockroachdb/cockroach/blob/566ad970b533ddd909806efefa0d54a557d6e71b/ui/app/redux/apiReducers.ts#L15)):*
> ```XML
> export const refreshCluster = clusterReducerObj.refresh;
> 
> const eventsReducerObj = new CachedDataReducer(api.getEvents, "events", TEN_SECONDS);
> ```

For things like this with a specified refresh rate, can you set the timeout to that rate? It'll just require passing in the invalidation period in the `refresh` method of `CachedDataReducer` (`cachedDataReducer.ts` line 154.)

---

*[ui/app/redux/cachedDataReducer.ts, line 157 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8647#-KPTwcbEQXEo3IvUdSDE:-KPTwcbEQXEo3IvUdSDF:b-4mrkrj) ([raw file](https://github.com/cockroachdb/cockroach/blob/566ad970b533ddd909806efefa0d54a557d6e71b/ui/app/redux/cachedDataReducer.ts#L157)):*
> ```XML
>       dispatch(this.requestData(req));
>       // Fetch data from the servers. Return the promise for use in tests.
>       return this.apiEndpoint(req).then((data) => {
> ```

Pass in the invalidation period here.

---

*[ui/app/util/api.ts, line 82 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8647#-KPU2imWgmNqz0l0Tjz_:-KPU2imXSnnkL8hklm0U:b8ee2ap) ([raw file](https://github.com/cockroachdb/cockroach/blob/566ad970b533ddd909806efefa0d54a557d6e71b/ui/app/util/api.ts#L82)):*
> ```XML
>   decode(buffer: ByteBuffer): TResponseMessage
>   decode64(buffer: string): TResponseMessage
> }>(builder: TResponseMessageBuilder, url: string, req: TRequestMessage = null, timeout: moment.Duration = moment.duration(30000)): Promise<TResponseMessage> {
> ```

This is probably a fine default as long as you change the timeout for components that refresh more frequently as mentioned elsewhere.

Also, if you're using moment.duration, might as well say `moment.duration(30, 's')`

---

*[ui/app/util/api.ts, line 116 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8647#-KPTx2piwoSOfVYvR9ij:-KPTx2piwoSOfVYvR9ik:bjwyxc4) ([raw file](https://github.com/cockroachdb/cockroach/blob/566ad970b533ddd909806efefa0d54a557d6e71b/ui/app/util/api.ts#L116)):*
> ```XML
> 
> // getDatabaseList gets a list of all database names
> export function getDatabaseList(timeout?: moment.Duration): Promise<DatabasesResponseMessage> {
> ```

I'm surprised this isn't causing typescript issues. `CachedDataReducer` always passes in a `TRequest` as the first argument. I don't think it'll cause anything to actually break, since the request here will always be `undefined`, but it seems like it ought to be a compilation error. Maybe it would make sense to add in the empty requests I originally removed as confusing?

---

*[ui/app/util/api.ts, line 117 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8647#-KPTxlZ69pX6_yDGP5st:-KPTxlZ69pX6_yDGP5su:b-msymx4) ([raw file](https://github.com/cockroachdb/cockroach/blob/566ad970b533ddd909806efefa0d54a557d6e71b/ui/app/util/api.ts#L117)):*
> ```XML
> // getDatabaseList gets a list of all database names
> export function getDatabaseList(timeout?: moment.Duration): Promise<DatabasesResponseMessage> {
>   return timeoutFetch(serverpb.DatabasesResponse, `${API_PREFIX}/databases`, null, timeout);
> ```

I wish there was a better pattern for this. I don't like passing around `null`s everywhere like this - I think it makes the code harder to both read and write. Maybe there's a better pattern?

A simple pattern:

```timeoutGET(serverpb.DatabasesResponse, `${API_PREFIX}/databases`, timeout);```  
```timeoutPOST(serverpb.SetUIDataResponse, `${API_PREFIX}/uidata`, req, timeout);```

Or something more complex like:

```js
class TimeoutablePromise<T> extends Promise<T>  {
  
  constructor(...) {
    super(...)
    this.originalPromise = this;
  }
  
  timeout(t: moment.Duration) {
    return withTimeout(originalPromise);
  }
}

...

Fetch<...>(...): TimeoutablePromise<T> {

...

return Fetch(...).timeout(moment.duration(...))

```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8647)*

**Comment by maxlang** [comment]
:lgtm:

It feels like there might be a slightly more optimal pattern for setting the timeout.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8647#-:-KPU3ZBcyJDN3-qG09s8:brb789d)*

**Comment by tamird** [comment]
Review status: 1 of 10 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[ui/app/redux/apiReducers.ts, line 15 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8647#-KPTw7VHOKYoe_-7h6kD:-KPU8I2em58FpYlCU517:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/566ad970b533ddd909806efefa0d54a557d6e71b/ui/app/redux/apiReducers.ts#L15)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> For things like this with a specified refresh rate, can you set the timeout to that rate? It'll just require passing in the invalidation period in the `refresh` method of `CachedDataReducer` (`cachedDataReducer.ts` line 154.)
</details>
Done.

---

*[ui/app/redux/cachedDataReducer.ts, line 157 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8647#-KPTwcbEQXEo3IvUdSDE:-KPUFUCBoV9ORQ3nuG5P:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/566ad970b533ddd909806efefa0d54a557d6e71b/ui/app/redux/cachedDataReducer.ts#L157)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> Pass in the invalidation period here.
</details>
Done.

---

*[ui/app/util/api.ts, line 82 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8647#-KPU2imWgmNqz0l0Tjz_:-KPUFVEjUeYi5BWi6AHX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/566ad970b533ddd909806efefa0d54a557d6e71b/ui/app/util/api.ts#L82)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> This is probably a fine default as long as you change the timeout for components that refresh more frequently as mentioned elsewhere.
> 
> Also, if you're using moment.duration, might as well say `moment.duration(30, 's')`
</details>
Done.

---

*[ui/app/util/api.ts, line 116 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8647#-KPTx2piwoSOfVYvR9ij:-KPU4Gf6pmFUdrQolhG0:brj0ogv) ([raw file](https://github.com/cockroachdb/cockroach/blob/566ad970b533ddd909806efefa0d54a557d6e71b/ui/app/util/api.ts#L116)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> I'm surprised this isn't causing typescript issues. `CachedDataReducer` always passes in a `TRequest` as the first argument. I don't think it'll cause anything to actually break, since the request here will always be `undefined`, but it seems like it ought to be a compilation error. Maybe it would make sense to add in the empty requests I originally removed as confusing?
</details>
We looked into this together - indeed there was some sketchy stuff here. Fixed by making all the API methods take RequestMessage types.

---

*[ui/app/util/api.ts, line 117 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8647#-KPTxlZ69pX6_yDGP5st:-KPUFbrS_6-Zk8i8k1R0:b2ufwuh) ([raw file](https://github.com/cockroachdb/cockroach/blob/566ad970b533ddd909806efefa0d54a557d6e71b/ui/app/util/api.ts#L117)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> I wish there was a better pattern for this. I don't like passing around `null`s everywhere like this - I think it makes the code harder to both read and write. Maybe there's a better pattern?
> 
> A simple pattern:
> 
> ```timeoutGET(serverpb.DatabasesResponse, `${API_PREFIX}/databases`, timeout);```  
> ```timeoutPOST(serverpb.SetUIDataResponse, `${API_PREFIX}/uidata`, req, timeout);```
> 
> Or something more complex like:
> 
> ```js
> class TimeoutablePromise<T> extends Promise<T>  {
>   
>   constructor(...) {
>     super(...)
>     this.originalPromise = this;
>   }
>   
>   timeout(t: moment.Duration) {
>     return withTimeout(originalPromise);
>   }
> }
> 
> ...
> 
> Fetch<...>(...): TimeoutablePromise<T> {
> 
> ...
> 
> return Fetch(...).timeout(moment.duration(...))
> 
> ```
</details>
Decided against this for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8647)*

**Comment by maxlang** [comment]
:lgtm: Again

---

Reviewed 9 of 9 files at r2.
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[ui/app/redux/apiReducers.ts, line 38 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8647#-KPUI-LFk3MMshn9BvJI:-KPUI-LGwk4W-VXWr9n_:b-1txoya) ([raw file](https://github.com/cockroachdb/cockroach/blob/10009dd3fa41cb35ab548de7945606e2ebafdbe4/ui/app/redux/apiReducers.ts#L38)):*
> ```XML
> 
> const databasesReducerObj = new CachedDataReducer(api.getDatabaseList, "databases");
> export const refreshDatabases = databasesReducerObj.refresh;
> ```

I'm kind of surprised we didn't get any issues with this actually. We made the request required, but when this is called in `databaseList.tsx` nothing is passed in.

I guess this is something that would be caught by strict null checks?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8647#-:-KPUIU0TYp7-XGiZI8MS:b-8nqvv3)*

**Comment by tamird** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[ui/app/redux/apiReducers.ts, line 38 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8647#-KPUI-LFk3MMshn9BvJI:-KPUIsBs-5exnigGNhkl:bmd1vsn) ([raw file](https://github.com/cockroachdb/cockroach/blob/10009dd3fa41cb35ab548de7945606e2ebafdbe4/ui/app/redux/apiReducers.ts#L38)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> I'm kind of surprised we didn't get any issues with this actually. We made the request required, but when this is called in `databaseList.tsx` nothing is passed in.
> 
> I guess this is something that would be caught by strict null checks?
</details>
:( yep

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8647)*

**Pull request merged**
