### PR TITLE
sql: handle inserts for partial indexes

### PR DESCRIPTION
**Pull request by mgartner**
This commit makes INSERTs only write new entries to partial indexes when
the new row satisfies the predicate expression of the partial index.

In order to do this, the optimizer synthesizes a column for each partial
index defined on the table that evaluates to true if the respective
partial index should be written to. These columns are interpretted by the
execution engine into a set of IndexIDs to not write to.

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
Nice work! The third commit :lgtm: 

> Reviewed 10 of 10 files at r1, 6 of 6 files at r2, 30 of 30 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49671#-:-M8m3W_d61Z3CVjj-ZDJ:bwwosox)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/insert.go, line 144 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49671#-M8loQco5UJGirfeIzLb:-M8loQcpDDw_SdKi49UX:bp31o6c) ([raw file](https://github.com/cockroachdb/cockroach/blob/954821431895f6300605e9db436a2732ffeec547/pkg/sql/insert.go#L144)):*
> ```Go
> 	// Create a set of index IDs to not write to. Indexes should not be written
> 	// to when they are partial indexes and the row does not satisfy the
> 	// predicate. This set is passed as a parameter tableInserter.row below.
> ```

[nit] parameter -> parameter to
___
*[pkg/sql/opt_catalog.go, line 963 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49671#-M8lpKrQ3pCNUsEGYkDf:-M8lpKrQ3pCNUsEGYkDg:b-eteux1) ([raw file](https://github.com/cockroachdb/cockroach/blob/954821431895f6300605e9db436a2732ffeec547/pkg/sql/opt_catalog.go#L963)):*
> ```Go
> }
> 
> func (oi *optIndex) Predicate() string {
> ```

Need a comment
___
*[pkg/sql/tablewriter.go, line 57 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49671#-M8lpcICD7chlQkrwwkk:-M8lpcID24YAHm_SOK6z:b-dox6cg) ([raw file](https://github.com/cockroachdb/cockroach/blob/954821431895f6300605e9db436a2732ffeec547/pkg/sql/tablewriter.go#L57)):*
> ```Go
> 	//
> 	// The ignoreIndexes parameter is a set of IndexIDs to avoid updating when
> 	// performing the row modification. It necessary to avoid writing to
> ```

It necessary -> It is necessary
___
*[pkg/sql/tablewriter.go, line 58 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49671#-M8lpf2D7IHCxsiTCdSO:-M8lpf2D7IHCxsiTCdSP:baaxyym) ([raw file](https://github.com/cockroachdb/cockroach/blob/954821431895f6300605e9db436a2732ffeec547/pkg/sql/tablewriter.go#L58)):*
> ```Go
> 	// The ignoreIndexes parameter is a set of IndexIDs to avoid updating when
> 	// performing the row modification. It necessary to avoid writing to
> 	// partial indexes when rows do no satisfy the partial index predicate.
> ```

do no -> do not
___
*[pkg/sql/opt/ops/mutation.opt, line 112 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49671#-M8lswqq8YlhCxwuJBhM:-M8lswqr9rfrWz1-A32x:b-gamis3) ([raw file](https://github.com/cockroachdb/cockroach/blob/954821431895f6300605e9db436a2732ffeec547/pkg/sql/opt/ops/mutation.opt#L112)):*
> ```
>     # value which is projected as a column and used during execution to
>     # determine whether or not to write a row to the partial index. The count
>     # order of columns corresponds to the count and order of the target table's
> ```

order -> and order
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 176 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49671#-M8m0uMA6ue9TFh2v_Y_:-M8m0uMA6ue9TFh2v_Ya:brp63wi) ([raw file](https://github.com/cockroachdb/cockroach/blob/954821431895f6300605e9db436a2732ffeec547/pkg/sql/opt/optbuilder/mutation_builder.go#L176)):*
> ```Go
> 	mb.checkOrds = scopeOrds[n*4 : n*4+tab.CheckCount()]
> 	mb.indexPredicateOrds = scopeOrds[n*4+tab.CheckCount():]
> 	// TODO: I think I'll need two sets of Ords here, 1 for writes and another
> ```

this should be TODO(mgartner)
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 739 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49671#-M8m1Y3YDZFKbDPd-BH4:-M8m1Y3YDZFKbDPd-BH5:b-q9g8hf) ([raw file](https://github.com/cockroachdb/cockroach/blob/954821431895f6300605e9db436a2732ffeec547/pkg/sql/opt/optbuilder/mutation_builder.go#L739)):*
> ```Go
> 
> 		// TODO(ridwanmsharif): Maybe we can avoid building constraints here
> 		// and instead use the constraints stored in the table metadata.
> ```

I don't think this comment applies here
___
*[pkg/sql/opt/optbuilder/testdata/insert, line 1243 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49671#-M8m22P506yDJk55uxy0:-M8m22P506yDJk55uxy1:b-t2j7kw) ([raw file](https://github.com/cockroachdb/cockroach/blob/954821431895f6300605e9db436a2732ffeec547/pkg/sql/opt/optbuilder/testdata/insert#L1243)):*
> ```
>  │    ├── column2:5 => b:2
>  │    └── column3:6 => c:3
>  ├── index partial pred columns: indexpred1:7 indexpred2:8
> ```

[nit] I'd flip this to say "partial index pred columns"
___
*[pkg/sql/row/helper.go, line 94 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49671#-M8m2oDx6B3OlI8_b-tQ:-M8m2oDx6B3OlI8_b-tR:b-48a2hg) ([raw file](https://github.com/cockroachdb/cockroach/blob/954821431895f6300605e9db436a2732ffeec547/pkg/sql/row/helper.go#L94)):*
> ```Go
> 
> // encodeSecondaryIndexes encodes the secondary index keys. Any index IDs that
> // have been ignored via ignoreIndex() will not be encoded.
> ```

is there actually an `ignoreIndex` function?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49671)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)

___
*[pkg/sql/create_table.go, line 473 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49671#-M8mKPrdD8jfIjS_5YOO:-M8mKPrdD8jfIjS_5YOP:b2gpjlp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1aa093809641c666c23fb3417a8b1723faf93f2/pkg/sql/create_table.go#L473)):*
> ```Go
> 
> 				// TODO(mgartner): Add partial index IDs to ignoreIndexes that we should
> 				// not delete entries from.
> ```

[nit] this seems off, we aren't deleting anything here
___
*[pkg/sql/opt_catalog.go, line 963 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49671#-M8mKfG8CONGC3TPfDE0:-M8mKfG8CONGC3TPfDE1:b-ckt0mz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1aa093809641c666c23fb3417a8b1723faf93f2/pkg/sql/opt_catalog.go#L963)):*
> ```Go
> }
> 
> func (oi *optIndex) Predicate() string {
> ```

Needs comment, and must explain that this is specific to partial indexes.
___
*[pkg/sql/opt/cat/table.go, line 94 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49671#-M8mKxdI9mxAk28vI4ia:-M8mKxdI9mxAk28vI4ib:b-ndexku) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1aa093809641c666c23fb3417a8b1723faf93f2/pkg/sql/opt/cat/table.go#L94)):*
> ```Go
> 	// delete-only indexes defined on the table that are partial indexes,
> 	// indicated by a non-zero-value predicate expression.
> 	PartialIndexCount() int
> ```

This seems a bit random. All the other counts translate to ranges of IndexOrdinals for certain types of indexes. This can't be used like that, you still have to go through all the indexes. I would remove it from the interface. You can write a helper that counts the partial indexes by going through each index.
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 738 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49671#-M8mLphP32YjRw1_sXHK:-M8mLphP32YjRw1_sXHL:bssfyby) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1aa093809641c666c23fb3417a8b1723faf93f2/pkg/sql/opt/optbuilder/mutation_builder.go#L738)):*
> ```Go
> 		scopeCol := mb.b.addColumn(projectionsScope, alias, texpr)
> 
> 		// TODO(ridwanmsharif): Maybe we can avoid building constraints here
> ```

I don't think this comment applies here, does it?

**Review by rytaft — COMMENTED** [review]
> Reviewed 3 of 35 files at r4, 30 of 30 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49671)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

**Review by mgartner — COMMENTED** [review]
Thanks for the reviews @raduberinde and @rytaft. Apologies for the sloppiness of some of it, looks like I forgot to look it over and remove some temporary stuff before submitting.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49671#-:-M8qJB-E1qNgr6NFXgun:b-4m1696)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

___
*[pkg/sql/create_table.go, line 473 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49671#-M8mKPrdD8jfIjS_5YOO:-M8pxafDA_3zcQ_9unGh:b-q7v841) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1aa093809641c666c23fb3417a8b1723faf93f2/pkg/sql/create_table.go#L473)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] this seems off, we aren't deleting anything here
</blockquote></details>

Good catch. Copy-pasta :spaghetti: 
___
*[pkg/sql/insert.go, line 144 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49671#-M8loQco5UJGirfeIzLb:-M8pxnN8CdTA5kG9bAm4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/954821431895f6300605e9db436a2732ffeec547/pkg/sql/insert.go#L144)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] parameter -> parameter to
</blockquote></details>

Done.
___
*[pkg/sql/opt_catalog.go, line 963 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49671#-M8lpKrQ3pCNUsEGYkDf:-M8pyXwt0uA20lrldG-f:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/954821431895f6300605e9db436a2732ffeec547/pkg/sql/opt_catalog.go#L963)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Need a comment
</blockquote></details>

Done.
___
*[pkg/sql/opt_catalog.go, line 963 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49671#-M8mKfG8CONGC3TPfDE0:-M8pyZLA0gTCYPdetvXL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1aa093809641c666c23fb3417a8b1723faf93f2/pkg/sql/opt_catalog.go#L963)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Needs comment, and must explain that this is specific to partial indexes.
</blockquote></details>

Done.
___
*[pkg/sql/tablewriter.go, line 57 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49671#-M8lpcICD7chlQkrwwkk:-M8pyn5s03fnnSPS9bIG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/954821431895f6300605e9db436a2732ffeec547/pkg/sql/tablewriter.go#L57)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

It necessary -> It is necessary
</blockquote></details>

Done.
___
*[pkg/sql/tablewriter.go, line 58 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49671#-M8lpf2D7IHCxsiTCdSO:-M8pypL64tAgik0RcN9i:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/954821431895f6300605e9db436a2732ffeec547/pkg/sql/tablewriter.go#L58)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

do no -> do not
</blockquote></details>

Done.
___
*[pkg/sql/opt/cat/table.go, line 94 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49671#-M8mKxdI9mxAk28vI4ia:-M8qJ7pKA2EbJ-BaKuSb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1aa093809641c666c23fb3417a8b1723faf93f2/pkg/sql/opt/cat/table.go#L94)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This seems a bit random. All the other counts translate to ranges of IndexOrdinals for certain types of indexes. This can't be used like that, you still have to go through all the indexes. I would remove it from the interface. You can write a helper that counts the partial indexes by going through each index.
</blockquote></details>

Done.
___
*[pkg/sql/opt/ops/mutation.opt, line 112 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49671#-M8lswqq8YlhCxwuJBhM:-M8pzHxGEsqoDlhsD5z6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/954821431895f6300605e9db436a2732ffeec547/pkg/sql/opt/ops/mutation.opt#L112)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

order -> and order
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 176 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49671#-M8m0uMA6ue9TFh2v_Y_:-M8pzy7m56jE8zrer5A0:b-1hss5d) ([raw file](https://github.com/cockroachdb/cockroach/blob/954821431895f6300605e9db436a2732ffeec547/pkg/sql/opt/optbuilder/mutation_builder.go#L176)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

this should be TODO(mgartner)
</blockquote></details>

Good catch. I've reworded and moved it up to the comment for `indexPredicateOrds`.
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 739 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49671#-M8m1Y3YDZFKbDPd-BH4:-M8q-Xv5DHLtNmMc4WEW:b-qios0s) ([raw file](https://github.com/cockroachdb/cockroach/blob/954821431895f6300605e9db436a2732ffeec547/pkg/sql/opt/optbuilder/mutation_builder.go#L739)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I don't think this comment applies here
</blockquote></details>

Correct. Fixed!
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 738 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49671#-M8mLphP32YjRw1_sXHK:-M8q-SU5AqWoj0UTUoB3:b-m4yw32) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1aa093809641c666c23fb3417a8b1723faf93f2/pkg/sql/opt/optbuilder/mutation_builder.go#L738)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I don't think this comment applies here, does it?
</blockquote></details>

Correct. More copy-pasta. :spaghetti: 
___
*[pkg/sql/opt/optbuilder/testdata/insert, line 1243 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49671#-M8m22P506yDJk55uxy0:-M8q66rz8ziNu-QuCnRt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/954821431895f6300605e9db436a2732ffeec547/pkg/sql/opt/optbuilder/testdata/insert#L1243)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] I'd flip this to say "partial index pred columns"
</blockquote></details>

Done.
___
*[pkg/sql/row/helper.go, line 94 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49671#-M8m2oDx6B3OlI8_b-tQ:-M8q6tLc0vlLfQXP-Dz7:bnaxha8) ([raw file](https://github.com/cockroachdb/cockroach/blob/954821431895f6300605e9db436a2732ffeec547/pkg/sql/row/helper.go#L94)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

is there actually an `ignoreIndex` function?
</blockquote></details>

No there is not. This was left-over from a different iteration on the solution. I've updated the comment.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49671#-:-M8r12hmCLcYn4hdihp3:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/cat/index.go, line 61 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49671#-M8qzs5c9yoLtJMJlYwK:-M8qzs5c9yoLtJMJlYwL:bi8zkii) ([raw file](https://github.com/cockroachdb/cockroach/blob/96d727c3e105860b780ec2407af18535124e24f9/pkg/sql/opt/cat/index.go#L61)):*
> ```Go
> 	// IsPartial returns true if the index is a partial index with a predicate
> 	// expression.
> 	IsPartial() bool
> ```

[nit] consider making this return both the string and the bool so there's a single API
___
*[pkg/sql/opt/ops/mutation.opt, line 119 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49671#-M8r-RFA69wVmeOjOx4q:-M8r-RFA69wVmeOjOx4r:b-nipud3) ([raw file](https://github.com/cockroachdb/cockroach/blob/96d727c3e105860b780ec2407af18535124e24f9/pkg/sql/opt/ops/mutation.opt#L119)):*
> ```
>     #     INDEX (a) WHERE b > 0,
>     #     INDEX (b),
>     #     INDEX (c) WHERE b > 0
> ```

[nit] having the same predicate twice raises unnecessary questions (eg are the two columns one and the same?)
___
*[pkg/sql/opt/ops/mutation.opt, line 123 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49671#-M8r-AbRCo0P_sjxGFZM:-M8r-AbRCo0P_sjxGFZN:b-wdvb3d) ([raw file](https://github.com/cockroachdb/cockroach/blob/96d727c3e105860b780ec2407af18535124e24f9/pkg/sql/opt/ops/mutation.opt#L123)):*
> ```
>     #
>     # In this case, the 0th column is the result of evaluating the predicate
>     # expression of the index on a. The 1st column is the result of evaluating
> ```

0th and 1st is confusing. Just say In this case there are two columns: the first one is.., the second one is..
___
*[pkg/sql/opt/optbuilder/insert.go, line 635 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49671#-M8r-maD8j0UDAkuI9zG:-M8r-maD8j0UDAkuI9zH:b-dtu2l) ([raw file](https://github.com/cockroachdb/cockroach/blob/96d727c3e105860b780ec2407af18535124e24f9/pkg/sql/opt/optbuilder/insert.go#L635)):*
> ```Go
> // operator that corresponds to the given RETURNING clause.
> func (mb *mutationBuilder) buildInsert(returning tree.ReturningExprs) {
> 	// Disambiguate names so that references in the constraint expression refer
> ```

What is "the constraint expression" referring to? Maybe "references in any constraint expressions"?

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 15 of 15 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49671#-:-M8rCFME4HhROQ62vd6g:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49671)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @pbardea and @rytaft)

___
*[pkg/sql/opt/cat/index.go, line 61 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49671#-M8qzs5c9yoLtJMJlYwK:-M8rUJ4I8m-uh6R4QRsn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/96d727c3e105860b780ec2407af18535124e24f9/pkg/sql/opt/cat/index.go#L61)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] consider making this return both the string and the bool so there's a single API
</blockquote></details>

Done.
___
*[pkg/sql/opt/ops/mutation.opt, line 119 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49671#-M8r-RFA69wVmeOjOx4q:-M8rUxnbEj-OY0M_jzgE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/96d727c3e105860b780ec2407af18535124e24f9/pkg/sql/opt/ops/mutation.opt#L119)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] having the same predicate twice raises unnecessary questions (eg are the two columns one and the same?)
</blockquote></details>

Done.
___
*[pkg/sql/opt/ops/mutation.opt, line 123 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49671#-M8r-AbRCo0P_sjxGFZM:-M8rV0C85r_QvIiI4iQK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/96d727c3e105860b780ec2407af18535124e24f9/pkg/sql/opt/ops/mutation.opt#L123)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

0th and 1st is confusing. Just say In this case there are two columns: the first one is.., the second one is..
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/insert.go, line 635 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49671#-M8r-maD8j0UDAkuI9zG:-M8rWg3g0OyZ7iLa-1No:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/96d727c3e105860b780ec2407af18535124e24f9/pkg/sql/opt/optbuilder/insert.go#L635)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

What is "the constraint expression" referring to? Maybe "references in any constraint expressions"?
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 9 of 9 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49671)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @pbardea)

**Pull request merged**
