### PR TITLE
colexecjoin: optimize the initialization of the merge joiner

### PR DESCRIPTION
**Pull request by yuzefovich**
Whenever the merge joiner doesn't know whether the group continues into
the next batch, it appends all tuples belonging to the group currently
being built to the "buffered group". Internally, that append requires us
that we perform a deep copy of the relevant tuples from the input batch
into a scratch space since `Enqueue` method only supports full-batch
operation.

Previously, we would always allocate the scratch batch in `Init` with
maximum possible size; however, this is too much when the input data
sets are small. This commit switches the allocation to be lazy and
utilizes our `ResetMaybeReallocate` method of dynamic batch sizing. This
shows up somewhat noticeably, for example, on
`SQL/MultinodeCockroach/InterleavedSelect` benchmark (which is using the
merge join since the interleaved reader joiner has been removed).

Addresses: #62212.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Quick benchmarks show the following:
```
name                                                    old time/op    new time/op    delta
SQL/MultinodeCockroach/InterleavedSelect/count=10-24      1.28ms ± 1%    1.27ms ± 1%   -0.72%  (p=0.043 n=10+8)
SQL/MultinodeCockroach/InterleavedSelect/count=100-24     1.59ms ± 6%    1.51ms ± 2%   -4.89%  (p=0.000 n=10+9)
SQL/MultinodeCockroach/InterleavedSelect/count=1000-24    3.05ms ± 1%    3.05ms ± 2%     ~     (p=1.000 n=10+10)

name                                                    old alloc/op   new alloc/op   delta
SQL/MultinodeCockroach/InterleavedSelect/count=10-24       269kB ±18%     198kB ± 3%  -26.26%  (p=0.000 n=10+8)
SQL/MultinodeCockroach/InterleavedSelect/count=100-24      287kB ± 2%     233kB ± 1%  -18.74%  (p=0.000 n=9+8)
SQL/MultinodeCockroach/InterleavedSelect/count=1000-24     590kB ± 1%     548kB ± 3%   -7.15%  (p=0.000 n=10+8)

name                                                    old allocs/op  new allocs/op  delta
SQL/MultinodeCockroach/InterleavedSelect/count=10-24       1.47k ± 6%     1.43k ± 1%   -3.03%  (p=0.008 n=10+8)
SQL/MultinodeCockroach/InterleavedSelect/count=100-24      1.82k ± 2%     1.81k ± 1%     ~     (p=0.056 n=9+10)
SQL/MultinodeCockroach/InterleavedSelect/count=1000-24     3.80k ± 1%     3.81k ± 1%     ~     (p=0.283 n=10+8)
```
I think the change is well-isolated, so it could be backported. Yet it doesn't offer that much performance gains, so the backport might not be justifiable. Curious to hear thoughts.

**Review by asubiotto — APPROVED** [review]
Based on the release meeting on Monday, I don't think we can backport this because we're trying to reduce the rate of backports and this is not a critical fix.

:lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62513#-:-MWZsMPRA6pK7Jm9P3k3:b5uop7m)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Review by asubiotto — COMMENTED** [review]
Probably something we could backport in .1 though

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62513#-:-MWZtCTI8jfeDl7tDPPy:b19dmci)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by yuzefovich** [comment]
Cool, sounds good.

TFTR!

bors r+

**Pull request merged**
