### PR TITLE
cli: demo uses in-process tenant infrastructure by default

### PR DESCRIPTION
**Pull request by dhartunian**
Previously, using `--multitenant=true` in demo would run an in-process tenant
that was configured to behave like an out-of-process one.

Given the goal of a unified architecture where all SQL interactions occur with
a tenant context, the multitenant demo will now use the `serverController` to
instantiate tenants, which will mimic UA clusters that will be the default in
the future.

An additional flag `--in-process-tenant` has been added that allows for
overriding this behavior at runtime. Setting this to `false` will use the test
server tenant infra that simulates an "out of process" tenant. This behavior
was retained also to keep prior tenant tests stable.

Informs #94310
Informs #94308.
Epic: CRDB-14537

Release note: None

### CODE REVIEW

**Review by knz — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93344#-:-NIsOP1U01R36k4Sce50:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi, @smg260, and @srosenberg)

**Review by aadityasondhi — APPROVED** [review]
thanks!

**Review by knz — APPROVED** [review]
still looks good

> Reviewed 2 of 10 files at r4, 10 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93344#-:-NL1C0u708cKqkte3g5z:b-3m7wt6)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @smg260 and @srosenberg)

**Comment by dhartunian** [comment]
TFTRs

bors r=knz,aadityasondhi

**Pull request merged**
