### PR TITLE
cli: Include collected goroutine dumps in debug zip

### LINKED ISSUE #33318: cli: include collected goroutine dumps in debug zip
This should follow a pattern similar to https://github.com/cockroachdb/cockroach/pull/26797.

### PR DESCRIPTION
**Pull request by giorgosp**
This PR makes the debug zip command include the goroutine dump files in the final zip, if the
GoroutineDumper has run until the command is triggered.

Also enhances the testing of the GetFiles endpoint by testing the names and the contents of the downloaded files.

Fixes #33318 

cc @tbg

### CODE REVIEW

**Review by tbg — COMMENTED** [review]
Nice, thanks @giorgosp! Only minor comments.

> Reviewed 2 of 2 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36813#-:-LcVhcDzCCUaKnvwiU6B:b-br3oal)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @giorgosp)

___
*[pkg/cli/zip.go, line 403 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36813#-LcVgu0J6eOsPGkAZScy:-LcVgu0J6eOsPGkAZScz:b-tt4les) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc3fd2592673c91027e45936bca3e324a818262b/pkg/cli/zip.go#L403)):*
> ```Go
> 				} else {
> 					for _, file := range goroutinesResp.Files {
> 						name := prefix + "/goroutines/" + file.Name + ".pprof"
> ```

Use `.txt` here and code like

https://github.com/cockroachdb/cockroach/blob/a17d619154365452ec75b2b26579b203b0ff289f/pkg/cli/zip.go#L346-L348
___
*[pkg/server/status_test.go, line 325 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36813#-LcVh39JEeXxZuNqCvqr:-LcVh39JEeXxZuNqCvqs:bb284u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc3fd2592673c91027e45936bca3e324a818262b/pkg/server/status_test.go#L325)):*
> ```Go
> 
> // TestStatusLocalGoroutineDumpsRetrieval tests the retrieval of the goroutine dumps.
> func TestStatusLocalGoroutineDumpsRetrieval(t *testing.T) {
> ```

Fold this into the previous test. First, you set up both the heap files and the goroutine files. Then, you run two subtest

```go
t.Run("heap", func(t *testing.T) {
 // fetch the heap files and verify
})

t.Run("heap", func(t *testing.T) {
 // fetch the goroutine files and verify
})
```

That way we're not setting up two servers. You can rename the test to `TestStatusGetFiles`

**Comment by giorgosp** [comment]
Thank you @tbg, force-pushed some adjustments.

**Review by tbg — APPROVED** [review]
Only minor nits. Btw, if you're not using reviewable yet, follow the button and ack the comments you've addressed, that makes it easier for me to follow what you've done. (Reviewable is also overall a bit more powerful which you'll appreciate once you end up contributing some more, which I hope you will!)

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36813#-:-LcXfS43-gi3STBC8sD-:b9v4ogd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @giorgosp)

___
*[pkg/cli/zip.go, line 398 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36813#-LcXfCuH-s6t-q3Q69eW:-LcXfCuH-s6t-q3Q69eX:b-jza3gb) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc3fd2592673c91027e45936bca3e324a818262b/pkg/cli/zip.go#L398)):*
> ```Go
> 						return err
> 					}); err != nil {
> 					if err := z.createError(prefix+"/goroutinefiles", err); err != nil {
> ```

wanna give the same treatment to `/heapfiles` above which should be `/heapprof` on error?
___
*[pkg/server/status_test.go, line 309 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36813#-LcXf0ZD3nnYRmmR2smD:-LcXf0ZD3nnYRmmR2smE:b-j9t08o) ([raw file](https://github.com/cockroachdb/cockroach/blob/9efc6c045d1a39e12c13ca15dff8db780ad01704/pkg/server/status_test.go#L309)):*
> ```Go
> 	})
> 
> 	// Test fetching goroutine files
> ```

nit: style guide asks for punctuation for comments on their own line. (i.e. add trailing dot).

https://github.com/cockroachdb/cockroach/blob/master/docs/style.md
___
*[pkg/server/status_test.go, line 357 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/36813#-LcXeuTt-3ds5G3Z1ciP:-LcXeuTt-3ds5G3Z1ciQ:babznsv) ([raw file](https://github.com/cockroachdb/cockroach/blob/9efc6c045d1a39e12c13ca15dff8db780ad01704/pkg/server/status_test.go#L357)):*
> ```Go
> 			Type: -1, Patterns: []string{"*"}}
> 		_, err = client.GetFiles(context.Background(), &request)
> 		if err == nil {
> ```

nit: we usually try to match the error more precisely, using `testutils.IsError`. (Same applies above).

**Review by tbg — COMMENTED** [review]
PS here's another issue that'd be a good next one for you to tackle: https://github.com/cockroachdb/cockroach/issues/36846

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36813#-:-LcXgyCV3c3yatX5aX_6:b-j40bcb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @giorgosp)

**Review by giorgosp — COMMENTED** [review]
Thank you Tobias, please take another look.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36813#-:-LcbbeGP4VwkdPrvUmIZ:b-7u2g2d)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/cli/zip.go, line 398 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36813#-LcXfCuH-s6t-q3Q69eW:-Lcb_Hg69BqF4PO7mOc0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc3fd2592673c91027e45936bca3e324a818262b/pkg/cli/zip.go#L398)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

wanna give the same treatment to `/heapfiles` above which should be `/heapprof` on error?
</blockquote></details>

Done.
___
*[pkg/cli/zip.go, line 403 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36813#-LcVgu0J6eOsPGkAZScy:-LcbYDEwBQy9Kxm_a0JC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc3fd2592673c91027e45936bca3e324a818262b/pkg/cli/zip.go#L403)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Use `.txt` here and code like

https://github.com/cockroachdb/cockroach/blob/a17d619154365452ec75b2b26579b203b0ff289f/pkg/cli/zip.go#L346-L348
</blockquote></details>

Done.
___
*[pkg/server/status_test.go, line 325 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36813#-LcVh39JEeXxZuNqCvqr:-LcbYLEg5AjBxL2g52zD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc3fd2592673c91027e45936bca3e324a818262b/pkg/server/status_test.go#L325)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Fold this into the previous test. First, you set up both the heap files and the goroutine files. Then, you run two subtest

```go
t.Run("heap", func(t *testing.T) {
 // fetch the heap files and verify
})

t.Run("heap", func(t *testing.T) {
 // fetch the goroutine files and verify
})
```

That way we're not setting up two servers. You can rename the test to `TestStatusGetFiles`
</blockquote></details>

Done.

**Review by tbg — APPROVED** [review]
Wonderful, thank you!

bors r+

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36813#-:-Lcbs_EJ16pq88TJQsN8:b6u55c2)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Pull request merged**
