### PR TITLE
acceptance: speed up tests by several minutes

### PR DESCRIPTION
**Pull request by benesch**

### CODE REVIEW

**Review by bdarnell — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28070)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by petermattis — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28070#-:-LIhwRY57aPMTWENeXTq:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by benesch** [comment]
Ugh, in making `TestGossipRestarts` faster I made it 5m slower. PTAQL at the new commit I just pushed up.

**Review by tbg — APPROVED** [review]
:lgtm: and big thanks.

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28070#-:-LIiSmML3A560yZZC2xy:b-rgl3g3)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Pull request merged**
