### PR TITLE
cli/sql: ensure that statements don't get mangled by history handling

### LINKED ISSUE #14484: cli: SQL shell history rewriting mangles INTERVAL
Repro:
1. Launch SQL shell
2. Run `SELECT DATE '1998-12-01' - INTERVAL '95' DAY;`
3. Hit up to recall the `SELECT` and run it again. You'll get the error `pq: unsupported binary operator: <date> - <string>`.

Expected: #3 should return 0 rows

SQL shell transcript:
```sql
root@:26257/tpch> SELECT DATE '1998-12-01' - INTERVAL '95' DAY;
+--------------------------------+
| DATE '1998-12-01' - '0m95d0ns' |
+--------------------------------+
| 1998-08-28 00:00:00+00:00      |
+--------------------------------+
(1 row)
--- I hit "up" then "enter" here
root@:26257/tpch> SELECT DATE '1998-12-01' - '0m95d0ns';
pq: unsupported binary operator: <date> - <string>
```

### PR DESCRIPTION
**Pull request by knz**
Fixes #14484.

cc @cuongdo

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14496)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Nice, LGTM!

**Comment by knz** [comment]
@RaduBerinde there's something else going on here. For INTERVAL specifically, the current pretty-print format is simply not parsable. I'll look at this but it means distsql is not handling interval datums properly now anyway. This didn't show up in tests because we were not using datums larger than a day.

**Comment by RaduBerinde** [comment]
Ha, yes, `0m95d0ns` doesn't look right at all

**Comment by knz** [comment]
Split off to  #14499

**Comment by knz** [comment]
@cdo this doesn't fix your issue completely, the remaining work is in #14499, I already started.

**Pull request merged**
