### PR TITLE
kvcoord: ignore follower reads in DistSender circuit breakers

### LINKED ISSUE #119923: kvcoord: handle follower reads with DistSender circuit breakers
The DistSender circuit breakers from https://github.com/cockroachdb/cockroach/pull/118943 should possibly handle follower reads better. The two main cases are:

* A replica partitioned away from the leader will fail to acquire a lease which may cause repeated client timeout errors, but it may still be able to serve follower reads below the closed timestamp.
* A stalled replica may not be able to serve follower reads either.

There are two interactions to keep in mind:

* Successful follower reads may mix with lease timeout errors, preventing the breaker from tripping and causing leased request failures.
* It may be possible for a replica with a tripped breaker to serve follower reads.

Potential follower reads use `RoutingPolicy_NEAREST`. We should consider adding specialized handling for these. Also keep in mind that meta range descriptor lookups use follower reads.

It may be reasonable to assume that the follower read timestamp is in the recent past, and that a faulty replica will remain faulty for longer than the follower read lag. Given that, we can likely omit successful follower reads when considering recent error runs, and trip the breaker regardless of successful follower reads. This will incur a latency penalty for follower reads that now have to hit other replicas, but once the follower read lag moves above the closed timestamp (typically a few seconds later) it will incur that penalty anyway.

Alternatively, we can differentiate handling of follower reads and other requests, and e.g. use separate breakers and probes for them, but it isn't clear that this is worthwhile.

### PR DESCRIPTION
**Pull request by erikgrinaker**
This patch ignores follower reads in the DistSender circuit breakers. Follower reads will not be taken into account when considering whether to trip the breaker, nor will they be rejected when the breaker is tripped. This can be controlled via the cluster setting `kv.dist_sender.circuit_breaker.ignore_follower_reads.enabled`.

This is a very simple policy to allow follower reads to succeed even if the replica or range is otherwise not functional (e.g. unable to establish a lease), but it will risk follower reads getting stuck on stalled or faulty replicas. A more sophisticated policy should be considered later.

Resolves #119923.
Epic: none
Release note: None

### CODE REVIEW

**Review by andrewbaptist — APPROVED** [review]
:lgtm:

Modulo the couple comments above.

> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120198#-:-Nsj-8_tCi1vYZ-cl0-x:bs37zfp)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @erikgrinaker and @nvanbenschoten)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 2283 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120198#-Nsiy5Wh3mjG0-6t9nmx:-Nsiy5Wh3mjG0-6t9nmy:b-5zhkv4) ([raw file](https://github.com/cockroachdb/cockroach/blob/13076fb928830d28c4dff0926f6ab23e4a0dfaf3/pkg/kv/kvclient/kvcoord/dist_sender.go#L2283)):*
> ```Go
> 	// assume that it's LEAD_FOR_GLOBAL_READS, because if it is, and we assumed
> 	// otherwise, we may send a request to a remote region unnecessarily.
> 	origRoutingPolicy := ba.RoutingPolicy
> ```

The fact that we modify the RoutingPolicy on the request at all here is a little silly and requires this additional `ShallowCopy`. This code would be cleaner if we simply changed an in-memory variable `requestRoutingPolicy` rather than keeping the code the way it is. Since we are introducing another variable here anyway this might be a good time to clean it up. Then you could just use the `ba` that is already passed to the Track method and not have to pass an additional variable.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker_test.go` line 221 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120198#-NsiztqzAb4P-Fyq6ZAc:-NsiztqzAb4P-Fyq6ZAd:bw63eei) ([raw file](https://github.com/cockroachdb/cockroach/blob/13076fb928830d28c4dff0926f6ab23e4a0dfaf3/pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker_test.go#L221)):*
> ```Go
> 	})
> 
> 	br := &kvpb.BatchResponse{}
> ```

Add a test to verify that we don't track requests that are sent to followers.

**Review by nvb — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120198)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @erikgrinaker)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker.go` line 496 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120198#-Nsj44IdE0Waswap3tqK:-Nsj44IdE0Waswap3tqL:bkl3q8c) ([raw file](https://github.com/cockroachdb/cockroach/blob/13076fb928830d28c4dff0926f6ab23e4a0dfaf3/pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker.go#L496)):*
> ```Go
> 	// We still record the lastRequest timestamp, to avoid GCing the breaker.
> 	//
> 	// NB: we check origRoutingPolicy rather than ba.RoutingPolicy, because the
> ```

Exact timestamp follower reads (e.g. `AS OF SYSTEM TIME follower_read_timestamp()`) will have an origRoutingPolicy of `RoutingPolicy_LEASEHOLDER`, not `RoutingPolicy_NEAREST`, won't they? Isn't it the check of `CanSendToFollower` in `sendToReplicas` that switches them to `RoutingPolicy_NEAREST`?

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120198)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist, @erikgrinaker, and @nvanbenschoten)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 2283 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120198#-Nsiy5Wh3mjG0-6t9nmx:-Nsm5JrzAKmoLL0cWMyf:b8fhxj8) ([raw file](https://github.com/cockroachdb/cockroach/blob/13076fb928830d28c4dff0926f6ab23e4a0dfaf3/pkg/kv/kvclient/kvcoord/dist_sender.go#L2283)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

The fact that we modify the RoutingPolicy on the request at all here is a little silly and requires this additional `ShallowCopy`. This code would be cleaner if we simply changed an in-memory variable `requestRoutingPolicy` rather than keeping the code the way it is. Since we are introducing another variable here anyway this might be a good time to clean it up. Then you could just use the `ba` that is already passed to the Track method and not have to pass an additional variable.
</blockquote></details>

I think the motivation is that this way anyone downstream can see the actual routing policy used for the request. I don't think anyone really cares right now (except perhaps for tracing and logging), but it seems reasonable enough to propagate this information.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker.go` line 496 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120198#-Nsj44IdE0Waswap3tqK:-Nsm5oOhD_bCHR95dIyw:b-n46mu4) ([raw file](https://github.com/cockroachdb/cockroach/blob/13076fb928830d28c4dff0926f6ab23e4a0dfaf3/pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker.go#L496)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Exact timestamp follower reads (e.g. `AS OF SYSTEM TIME follower_read_timestamp()`) will have an origRoutingPolicy of `RoutingPolicy_LEASEHOLDER`, not `RoutingPolicy_NEAREST`, won't they? Isn't it the check of `CanSendToFollower` in `sendToReplicas` that switches them to `RoutingPolicy_NEAREST`?
</blockquote></details>

I think that's right. But I'm wary of bypassing the circuit breaker for these, for the reasons outlined in this comment. There is a race here between a lease being established elsewhere and the DistSender discovering it, and request retries falling below the closed timestamp and bypassing the breaker where they can get stuck forever on a stalled replica. So I worry that doing this will undermine the effectiveness of the circuit breaker for reads that aren't explicit follower reads.

It's also tricky to distinguish between a stall and a partial partition, because writes that were proposed before the partition will appear to have stalled to a client.

I don't have any good ideas for how to avoid this right now, will revisit.
___
*[`pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker_test.go` line 221 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120198#-NsiztqzAb4P-Fyq6ZAc:-Nsm9PtL3vBLQV7BoaeS:b-kz2huj) ([raw file](https://github.com/cockroachdb/cockroach/blob/13076fb928830d28c4dff0926f6ab23e4a0dfaf3/pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker_test.go#L221)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

Add a test to verify that we don't track requests that are sent to followers.
</blockquote></details>

I've punted testing of the circuit breaker to get all the necessary functionality in before the branch cut, it's tracked in #119918.

**Review by andrewbaptist — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120198#-:-Nt1FtO47wACqsi6btVi:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @erikgrinaker and @nvanbenschoten)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 2283 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120198#-Nsiy5Wh3mjG0-6t9nmx:-Nt1EW5PEqw9s_DZ0w4r:bhxxlsp) ([raw file](https://github.com/cockroachdb/cockroach/blob/13076fb928830d28c4dff0926f6ab23e4a0dfaf3/pkg/kv/kvclient/kvcoord/dist_sender.go#L2283)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

I think the motivation is that this way anyone downstream can see the actual routing policy used for the request. I don't think anyone really cares right now (except perhaps for tracing and logging), but it seems reasonable enough to propagate this information.
</blockquote></details>

The concern for me is more about which information the "end user" cares about. There are two pieces of information:
1) What the client requested we set this to
2) How DistSender decided to route it.

If the downstream server was going to make different decisions on this request, it seems they would care more about what the client wanted rather than what DistSender did with it. That said, since we are not making this distinction today, and no-one downstream is looking at this field, it doesn't really matter either way. 

Our current batch request/response API is pretty leaky and messy today with the way we handle fields like this as well as a few other fields. It would be worth an effort to try and rationalize and clean it up, but I don't know what the correct approach should be.

**Comment by erikgrinaker** [comment]
I'm not convinced we should do this. Let's discuss in person next week.

**Pull request closed without merging**
