### PR TITLE
storage: move node initialization to before serving

### LINKED ISSUE #5024: circleci: failed tests (14133): TestClusterRecovery
The following test appears to have failed:

[#14133](https://circleci.com/gh/cockroachdb/cockroach/14133):

```
I160309 18:29:07.486135 acceptance/chaos_test.go:178  client 2 shutting down
I160309 18:29:07.487760 acceptance/chaos_test.go:178  client 0 shutting down
I160309 18:29:07.513134 acceptance/chaos_test.go:361  40 7.3/sec
W160309 18:29:07.700835 acceptance/chaos_test.go:250  round 3: cluster recovered
I160309 18:29:07.801244 acceptance/cluster/localcluster.go:585  stopping
--- FAIL: TestClusterRecovery (11.69s)
	chaos_test.go:268: pq: storage/stores.go:87: store 2 not found
=== RUN   TestNodeRestart
I160309 18:29:09.799293 acceptance/cluster/localcluster.go:254  Initializing Cluster:
Cluster Setup: AdHoc 3x1
Duration: 5s, Stall: 2m0s
Node 0 - Store 0
Node 1 - Store 0
Node 2 - Store 0
Total Nodes Count:3, Total Store Count:3
I160309 18:29:09.799481 acceptance/cluster/docker.go:73  ImagePull cockroachdb/builder:20160305-182433 starting
--
--- SKIP: TestBuildBabyCluster (0.00s)
	terraform_test.go:30: only enabled during testing
=== RUN   TestFiveNodesAndWriters
--- SKIP: TestFiveNodesAndWriters (0.00s)
	util_test.go:64: running in docker mode
FAIL
ok github.com/cockroachdb/cockroach/acceptance 1337s

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by vivekmenezes**
This is not guaranteed to fix the bug but I'm marking it fixed for now. Let's see if we see it after this fix.

closes #5024 

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5441)

### CODE REVIEW

**Comment by tamird** [comment]
any reason not to go all the way and move the serving down to the very bottom of the method?

**Comment by vivekmenezes** [comment]
No particular reason. I could do that. I'd like you to review this because I'm not familiar with all the serving code and what gossip depends on. The node can be initialized after gossip is ready.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5441#-:-KDPesjdg7vQ1hHaWJlu:464773376)*

**Comment by tamird** [comment]
Seems easy enough to try?

---

Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5441#-:-KDPk8nKAN6W-G7KaTHp:948290219)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5441)*

**Comment by vivekmenezes** [comment]
Is this okay?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5441#-:-KDPpI6VhpcfOa5yfTdL:946158426)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/server.go, line 290 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5441#-KDPrdRkIkxVVI_4RVHI:-KDPrdRkIkxVVI_4RVHJ:-319668233) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb3b0d8569c13989a430f4e41808ab9a6dd53aa6/server/server.go#L290)):*
i think you can revert these guys now that `m.Serve` is called at the bottom.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5441)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/server.go, line 290 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5441#-KDPrdRkIkxVVI_4RVHI:-KDPvPAeTBPNBnzobKYY:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb3b0d8569c13989a430f4e41808ab9a6dd53aa6/server/server.go#L290)):*
done

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5441)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5441#-:-KDPvjgIUUvWCFMUHAdj:1417088721)*

**Pull request merged**
