### PR TITLE
sql: run TestQueryCache subtests in parallel

### PR DESCRIPTION
**Pull request by RaduBerinde**
This speeds up the test from ~3s to ~.5s.

Release note: None

### CODE REVIEW

**Review by justinj — COMMENTED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37033#-:-LdA0IkT77ixwDcXkgPS:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj)

**Comment by RaduBerinde** [comment]
Very strange - I keep failing an unrelated test `TestShowFingerprintsAsOfSystemTime` in `StartTestCluster` with `[n1,s1] has 19 underreplicated ranges` repeating until timeout. @jordanlewis @andreimatei any ideas how to debug this?

**Comment by RaduBerinde** [comment]
Sigh.. it's this issue:

https://github.com/cockroachdb/cockroach/blob/4d6f3081748a3448489427a3976fc4102d8235f6/pkg/server/testserver.go#L318

Then `WaitForFullReplication` is being run on a 1-node cluster which should just exit but it sees `NumReplicas=1`. Though not clear why there would be unreplicated ranges if the cluster uses the default zone config.

**Comment by andreimatei** [comment]
But is there any parallelism between tests in what you were running? I don't see `TestShowFingerprintsAsOfSystemTime` running more than one server, and the comment says there's problems when you run more than one.

**Comment by RaduBerinde** [comment]
The test I'm changing runs subtests in parallel, and `TestShowFingerprintsAsOfSystemTime` is the test that follows. I added a commit that fixes this particular issue, PTAL.

**Review by andreimatei — DISMISSED** [review]
How about localizing your hack to the particular test(s) that need this?
I'm thinking:
- make the code in `TestServer.Start()` only set `NumReplicas` to ` if the default zone config has not already been set to 1 by someone else.
- create an object called `ParallelTestServersGuard` that changes replication from 3->1 and 1->3 in the cleanup. No refcount needed. Use this object in your test (above the parallel tests).
- make the restoring of the default replication from 1 to 3 done by (deferred by) `TestServer.Start()` yell if it'd overwrite a config with a replication value != 1. This would catch the situation that you ran into in the future.

I think that'd be better... Not that the current code in `TestServer` is particularly nice... What do you think?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37033#-:-LdBJdoKC2JuTOjQSmZc:bj8p9xl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @RaduBerinde)

___
*[pkg/server/testserver.go, line 312 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37033#-LdBHt9F1QZK8kelQcet:-LdBHt9F1QZK8kelQceu:b-v4qxvr) ([raw file](https://github.com/cockroachdb/cockroach/blob/5af0305242b9375f484624b4cb6eb64021a826fe/pkg/server/testserver.go#L312)):*
> ```Go
> var messWithZoneConfig struct {
> 	mutex    syncutil.Mutex
> 	refCount int
> ```

embed the mutex in an anonymous struct named `mu`, and put `refcount` in there, as we do everywhere.
___
*[pkg/testutils/testcluster/testcluster.go, line 556 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37033#-LdBHRtC76bhjSoqqGs3:-LdBHRtC76bhjSoqqGs4:b-i9ic8t) ([raw file](https://github.com/cockroachdb/cockroach/blob/5af0305242b9375f484624b4cb6eb64021a826fe/pkg/testutils/testcluster/testcluster.go#L556)):*
> ```Go
> func (tc *TestCluster) WaitForFullReplication() error {
> 	if int32(len(tc.Servers)) < *config.DefaultZoneConfig().NumReplicas {
> 		// TODO(radu): in this case, ReplicationManual should be used.
> ```

I'd also put a reference to the zone config messing that test servers do for related reasons - in that case, log spam, here avoiding waiting forever.
___
*[pkg/testutils/testcluster/testcluster.go, line 556 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37033#-LdBL2A34kHs8UMdyUNy:-LdBL2A34kHs8UMdyUNz:b-r5p07j) ([raw file](https://github.com/cockroachdb/cockroach/blob/5af0305242b9375f484624b4cb6eb64021a826fe/pkg/testutils/testcluster/testcluster.go#L556)):*
> ```Go
> func (tc *TestCluster) WaitForFullReplication() error {
> 	if int32(len(tc.Servers)) < *config.DefaultZoneConfig().NumReplicas {
> 		// TODO(radu): in this case, ReplicationManual should be used.
> ```

Well I don't think we want people to have to explicitly say `ReplicationManual` in one node `TestClusters`. And I guess there are reasons for creating a one-node `TestCluster` as opposed to a `TestServer` cause I've seen at least one test do that...

**Review by RaduBerinde — COMMENTED** [review]
Why do you think that would be better? This is a net improvement over the current broken code in TestServer. If I put something in my test, the next person trying to parallelize a bunch of subtests will have to spend time understanding this issue and how to use that guard. Then we'll have to revert that stuff if we ever stop using a global default config.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37033#-:-LdBP4Fe8TQORD1Fta5W:b-c3yygu)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @RaduBerinde)

___
*[pkg/testutils/testcluster/testcluster.go, line 556 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37033#-LdBL2A34kHs8UMdyUNy:-LdBPl301Xsx64mEeIOe:b-49bodw) ([raw file](https://github.com/cockroachdb/cockroach/blob/5af0305242b9375f484624b4cb6eb64021a826fe/pkg/testutils/testcluster/testcluster.go#L556)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Well I don't think we want people to have to explicitly say `ReplicationManual` in one node `TestClusters`. And I guess there are reasons for creating a one-node `TestCluster` as opposed to a `TestServer` cause I've seen at least one test do that...
</blockquote></details>

Then maybe we should automatically set it to `Manual` for anything less than 3 nodes?

By the way, there must be something else wrong here. If the zone config had `NumReplicas=1`, why does the code below detect unreplicated ranges? It's not a matter of this test racing with my test - my test fully completes before this one starts (it was just leaving the wrong zone config).

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37033)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @RaduBerinde)

___
*[pkg/testutils/testcluster/testcluster.go, line 556 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37033#-LdBL2A34kHs8UMdyUNy:-LdBSLc597OSbnqUIvgG:b-hugv91) ([raw file](https://github.com/cockroachdb/cockroach/blob/5af0305242b9375f484624b4cb6eb64021a826fe/pkg/testutils/testcluster/testcluster.go#L556)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Then maybe we should automatically set it to `Manual` for anything less than 3 nodes?

By the way, there must be something else wrong here. If the zone config had `NumReplicas=1`, why does the code below detect unreplicated ranges? It's not a matter of this test racing with my test - my test fully completes before this one starts (it was just leaving the wrong zone config).
</blockquote></details>

I changed the default zone config and started a one node cluster and the graph shows 19 under-replicated ranges. It seems that it is incorrect to rely on this metric for a 1 node cluster regardless of the zone config..

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37033)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @RaduBerinde)

___
*[pkg/testutils/testcluster/testcluster.go, line 556 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37033#-LdBL2A34kHs8UMdyUNy:-LdBUUy69yzaqQW8BG1j:bkvxfzd) ([raw file](https://github.com/cockroachdb/cockroach/blob/5af0305242b9375f484624b4cb6eb64021a826fe/pkg/testutils/testcluster/testcluster.go#L556)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I changed the default zone config and started a one node cluster and the graph shows 19 under-replicated ranges. It seems that it is incorrect to rely on this metric for a 1 node cluster regardless of the zone config..
</blockquote></details>

Looks like we have a different default zone config for system tables. It has 5 replicas by default. But the under-replicated range count doesn't report them as under-replicated if we have only 3 nodes.

I think it's pretty clear that this NumReplica check is completely bogus. I propose removing it and instead setting the mode to Manual if `n < 3`.

**Comment by RaduBerinde** [comment]
@andreimatei Updated as discussed, PTAL.

**Comment by RaduBerinde** [comment]
There were a couple of tests that were doing stuff with the queues in testcluster smaller than 3 nodes. I removed the change to override the `ReplicationMode` and instead just fixed the check to compare against 3.

**Review by andreimatei — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37033#-:-LdKxvqa00u6NCRnczLl:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @andreimatei and @RaduBerinde)

**Comment by RaduBerinde** [comment]
TFTR!

bors r+

**Pull request merged**
