### PR TITLE
WIP tests/orms: import examples-orms tests

### PR DESCRIPTION
**Pull request by dt**
since we're now running the ORM tests as part of our regular build testing,
it makes sense to bring them into the same repo -- any changes in behavior
can atomically change the tests as well, and as we add new features that the
ORMs utilize, including those in the changesets also helps document them.
The tests are also more discoverable than they were in a separate repo,
and can more easily reuse infrasturue, like the docker build env.

Still todo:

- [ ] test with build/builder.sh
- [ ] build/teamcity-orms.sh
- [ ] figure out deps -- I dropped the examples-orms `vendor` folder, but we'll either need to add to our top-level one, add one under tests/orms with what top-level is missing (just gorm I think), or leave it .gitignored for just-in-time fetching client side.
  - the other langs currently do just-in-time fetching, but the test harness depends on the go example.
  - just-in-time fetching doesn't provide reproducible builds, since it still depends on an external resource.
  - Solving the non-go deps is out of scope for the initial import, but worth considering when picking a solution for the go code.

### CODE REVIEW

**Comment by dt** [comment]
@tamir 1¢ for your thoughts on handling orms deps.

**Comment by benesch** [comment]
I know we already bikeshedded on Slack, but I think putting these in a top-level `tests` directory is bound to confuse newcomers. No matter how many places we put a note about where tests actually live, the first place people will look is the `tests` directory... and it'll only contain some ORM tests. At the very least we should include a `TEST-LAYOUT.md` in the directory to point people in the right direction. I'll cast one more [weak] vote in favor of a top-level `examples` instead.

**Comment by dt** [comment]
+cc @bdarnell @jordanlewis for the directory bike shed

**Comment by bdarnell** [comment]
>  the first place people will look is the tests directory... and it'll only contain some ORM tests

And the first thing they'll do with an `examples` directory is look to what's inside for "exemplary" code using different frameworks. What's there now is generally fine as examples, but I think we're going to introduce a lot more test-style code in the future. I'm more worried about providing bad "example" code than someone getting the false impression that a sparsely-populated "tests" directory is the whole of our testing. So I'm still (weakly) in favor of `tests` instead of `examples` (or even something like `langtests` to emphasize that this is for our foreign-language tests).

**Comment by jordanlewis** [comment]
I think `tests` is still okay if there's a readme. I think we may want to add more external tests to this directory at some point so I'd prefer to stay away from `langtests` if we can.

Here's the first paragraph from PostgreSQL's `tests/README.md`:

```md
PostgreSQL tests
================

This directory contains a variety of test infrastructure as well as some of the
tests in PostgreSQL. Not all tests are here -- in particular, there are more in
individual contrib/ modules and in src/bin.
```

**Comment by dt** [comment]
I don't have particularly strong opinions on _where_ we put these in the repo -- just that they're in the repo somewhere.

some more possible name ideas:
 - `resources/orm-tests`: "resources" is almost as non-specific and vague asl "util"
 - `contrib/orm-tests`: kinda strange, since usually that's just hosting random, adopted tools/utilities/plugins, not something relied on by main build process.
 - `verification/orm-tests` (doesn't imply as broad a responsibility as `tests`, but `verification` seems to a bit strong of a claim)

**Comment by dt** [comment]
these seem about as close to "acceptance" tests as we have, so we could also try just adding them to existing pkg/acceptance, but my guess is that'll result in ongoing fighting (social-casing) of the lint  rules, that assume everything under `pkg` is cockroach-authored go code (the whole point of that structure)... We could lift `acceptance` _out_ of `pkg`?

**Comment by benesch** [comment]
I think @bdarnell is :-1: on a top-level `acceptance`. (He suggested `pkg/acceptance/testdata` as an alternative.)

`tests` seems fine provided we have a `README.md` like the one from `postgresql/tests`.

**Comment by dt** [comment]
fwiw, I believe our previous discussion of top-level `acceptance` was specifically in the context of it being *duplicative* with `pkg/acceptance` -- maybe I'm reading too much into it though. my latest suggestion was that we extend the existing `acceptance` (e.g. by adding `testdata/orms`), but that we also hoist it up to top-level while doing so, to keep the preserve the invariants for the `pkg` prefix.

**Comment by benesch** [comment]
Is this abandoned? 😞

**Comment by dt** [comment]
:( maybe another friday

**Comment by benesch** [comment]
cc @tamird think we could advocate for some dedicated eng time to merge repos during the 1.2 cycle?

**Comment by tamird** [comment]
Happy to advocate, do not want to do it.

**Pull request closed without merging**
