### PR TITLE
storage/engine: Fix rocksdb assertions

### PR DESCRIPTION
**Pull request by bdarnell**
Our tests currently fail with debug builds of rocksdb because of additional assertions enabled in this mode. With these changes our tests pass with debug builds of rocksdb 4.8.

See #9168 

@cockroachdb/stability

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9179)

### CODE REVIEW

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9179#-:-KR4JDDcn4wbR9A404Mp:bnfp4nl)*

**Comment by a-robinson** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9179#-:-KR4JyQIOuITuIfReQKx:bnfp4nl)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1, 3 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9179)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9179#-:-KR591bu6VqlRucuLLFx:bnfp4nl)*

**Pull request merged**
