### PR TITLE
storage/report: don't deserialize zone configs over and over

### LINKED ISSUE #41609: storage: replication reports generation takes 20% of a node's CPU for 200k ranges
On a TPCC-100k run, with partitioning, the following profile shows report generation (at the left) taking a bunch of CPU. The generation of each report seems to take minutes.

image

We're unmarshalling the same zone protos over and over again.

### PR DESCRIPTION
**Pull request by andreimatei**
This patch is expected to speedup reports generation considerably by not
unmarshalling zone config protos for every range. Instead, the
report-geneating visitors now keep state around the zone that a visited
range is in and reuse that state if they're told that the following
range is in the same zone. The range iteration infrastructure was
enhanced to figure out when zones change from range to range and tell
that to the visitors.

Without this patch, generating the reports was pinning a core for
minutes for a cluster with partitioning and 200k ranges. The profiles
showed that it's all zone config unmarshalling.

Fixes #41609

Release note (performance improvement): The performance of generating
the system.replication_* reports was greatly improved for large
clusters.

### CODE REVIEW

**Comment by andreimatei** [comment]
I still need to write some new tests, but PTAL

**Review by darinpp — APPROVED** [review]
Looks good.

**Review by ajwerner — COMMENTED** [review]
Seems fine to me. Mostly just nits. 

> Reviewed 2 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41711#-:-LrVTHCO1uVHuKnIHr9V:b-558nuj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @andreimatei)

___
*[pkg/storage/reports/constraint_stats_report.go, line 445 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41711#-LrVMfuX0yQvNE0yKmTF:-LrVMfuX0yQvNE0yKmTG:b-380kce) ([raw file](https://github.com/cockroachdb/cockroach/blob/a704750f9e72a509ed3f15cad303f1e94a0b1a6f/pkg/storage/reports/constraint_stats_report.go#L445)):*
> ```Go
> 
> 	defer func() {
> 		if retErr != nil {
> ```

super nit: `v.visitErr = retErr != nil`?
___
*[pkg/storage/reports/critical_localities_report.go, line 318 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41711#-LrVMyrxAUjnZcDVFD_Y:-LrVMyryAgqHTKvsowXm:b4h8del) ([raw file](https://github.com/cockroachdb/cockroach/blob/a704750f9e72a509ed3f15cad303f1e94a0b1a6f/pkg/storage/reports/critical_localities_report.go#L318)):*
> ```Go
> 
> 	defer func() {
> 		if retErr != nil {
> ```

super nit: `v.visitErr = retErr != nil`
___
*[pkg/storage/reports/critical_localities_report.go, line 349 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41711#-LrVN4Dy7RU2XTCoyvlv:-LrVN4Dy7RU2XTCoyvlw:b2ngvnt) ([raw file](https://github.com/cockroachdb/cockroach/blob/a704750f9e72a509ed3f15cad303f1e94a0b1a6f/pkg/storage/reports/critical_localities_report.go#L349)):*
> ```Go
> ) (retErr error) {
> 	defer func() {
> 		if retErr != nil {
> ```

...
___
*[pkg/storage/reports/reporter.go, line 345 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41711#-LrVO2T28PIQSkHIzInP:-LrVO2T28PIQSkHIzInQ:b-crni87) ([raw file](https://github.com/cockroachdb/cockroach/blob/a704750f9e72a509ed3f15cad303f1e94a0b1a6f/pkg/storage/reports/reporter.go#L345)):*
> ```Go
> 	}
> 	// Check that the subzone, if any, is the same.
> 	if r.lastZone == nil {
> ```

I don't really get this case. Are we saying that sometimes we call `setZone` with `nil`?
___
*[pkg/storage/reports/reporter.go, line 555 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41711#-LrVT2Lv8nQ00g5ceEzn:-LrVT2LwA2hY0DLWjN13:by7tmzj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a704750f9e72a509ed3f15cad303f1e94a0b1a6f/pkg/storage/reports/reporter.go#L555)):*
> ```Go
> 
> // visitorError is returned by visitRanges when one or more visitors failed.
> type visitorError struct {
> ```

style question which I could go either way on: how about `type visitorError []error`
___
*[pkg/storage/reports/reporter.go, line 635 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41711#-LrVOvhN4KUp2bOchXXy:-LrVOvhN4KUp2bOchXXz:b-vj4qcu) ([raw file](https://github.com/cockroachdb/cockroach/blob/a704750f9e72a509ed3f15cad303f1e94a0b1a6f/pkg/storage/reports/reporter.go#L635)):*
> ```Go
> 				// Sanity check - v.failed() should return an error now (the same as err above).
> 				if !v.failed() {
> 					return errors.Errorf("expected visitor %T to have failed() after error: %s", v, err)
> ```

Would this be a reasonable use case for `errors.NewAssertionErrorWithWrappedErrf`?

**Review by andreimatei — COMMENTED** [review]
I've got a better structure now and added a bunch of tests. PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41711#-:-LrVwfsZ70D_wbnH-Hgv:b56ovfr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/storage/reports/constraint_stats_report.go, line 445 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41711#-LrVMfuX0yQvNE0yKmTF:-LrVwdcSDICF6Booh21I:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a704750f9e72a509ed3f15cad303f1e94a0b1a6f/pkg/storage/reports/constraint_stats_report.go#L445)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

super nit: `v.visitErr = retErr != nil`?
</blockquote></details>

done
___
*[pkg/storage/reports/critical_localities_report.go, line 318 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41711#-LrVMyrxAUjnZcDVFD_Y:-LrVwCSD3zPNYZO5c5DQ:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a704750f9e72a509ed3f15cad303f1e94a0b1a6f/pkg/storage/reports/critical_localities_report.go#L318)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

super nit: `v.visitErr = retErr != nil`
</blockquote></details>

done
___
*[pkg/storage/reports/critical_localities_report.go, line 349 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41711#-LrVN4Dy7RU2XTCoyvlv:-LrVwCue-NKftue-w7_t:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a704750f9e72a509ed3f15cad303f1e94a0b1a6f/pkg/storage/reports/critical_localities_report.go#L349)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

...
</blockquote></details>

done
___
*[pkg/storage/reports/reporter.go, line 345 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41711#-LrVO2T28PIQSkHIzInP:-LrVwELHChUTaIavt1kx:bh2qzg9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a704750f9e72a509ed3f15cad303f1e94a0b1a6f/pkg/storage/reports/reporter.go#L345)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I don't really get this case. Are we saying that sometimes we call `setZone` with `nil`?
</blockquote></details>

this was some nonsense
___
*[pkg/storage/reports/reporter.go, line 555 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41711#-LrVT2Lv8nQ00g5ceEzn:-LrVwHg39Z89PAw5_YNI:b2ni7qj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a704750f9e72a509ed3f15cad303f1e94a0b1a6f/pkg/storage/reports/reporter.go#L555)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

style question which I could go either way on: how about `type visitorError []error`
</blockquote></details>

meh
___
*[pkg/storage/reports/reporter.go, line 635 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41711#-LrVOvhN4KUp2bOchXXy:-LrVwVkZD0Z-pOFuaR9D:blygput) ([raw file](https://github.com/cockroachdb/cockroach/blob/a704750f9e72a509ed3f15cad303f1e94a0b1a6f/pkg/storage/reports/reporter.go#L635)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Would this be a reasonable use case for `errors.NewAssertionErrorWithWrappedErrf`?
</blockquote></details>

I don't think so. Here the original err is not a "cause" of the assertion failure; this is not a usual wrapping situation

**Review by ajwerner — APPROVED** [review]
:lgtm:

There's something unsatisfying about the copy-pasta on each of the visitor implementations but I can live with it. 

> Reviewed 4 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41711#-:-LriiLIg1CJeztmL_Urr:b-bgwbde)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/storage/reports/reporter.go, line 354 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41711#-LrihqLS3bbbkdVdFaRt:-LrihqLS3bbbkdVdFaRu:b-r8qk3o) ([raw file](https://github.com/cockroachdb/cockroach/blob/44ee9b3d071ba953a77ed8926aee35c7c4a2af94/pkg/storage/reports/reporter.go#L354)):*
> ```Go
> ) (ZoneKey, error) {
> 	objectID, _ := config.DecodeKeyIntoZoneIDAndSuffix(rd.StartKey)
> 	first := true
> ```

super nit: add commentary to make it clearer to the reader that visitZones walks from the bottom up. The logic is clear once you know that fact. 
___
*[pkg/storage/reports/reporter.go, line 389 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41711#-Lrih3OK2fbbqNiAqwoE:-Lrih3OLA3XFiR5f7hzz:b-390he) ([raw file](https://github.com/cockroachdb/cockroach/blob/44ee9b3d071ba953a77ed8926aee35c7c4a2af94/pkg/storage/reports/reporter.go#L389)):*
> ```Go
> // example, if the zoneChecker was previously configured for a range starting at
> // /Table/51 and is now queried for /Table/52, it will say that the zones don't
> // match even if in fact they do ( because neither table defines its own zone
> ```

nit: extra space.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41711)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)

___
*[pkg/storage/reports/reporter.go, line 354 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41711#-LrihqLS3bbbkdVdFaRt:-LrikEa970MNrhYk_NZF:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/44ee9b3d071ba953a77ed8926aee35c7c4a2af94/pkg/storage/reports/reporter.go#L354)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

super nit: add commentary to make it clearer to the reader that visitZones walks from the bottom up. The logic is clear once you know that fact. 
</blockquote></details>

done
___
*[pkg/storage/reports/reporter.go, line 389 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41711#-Lrih3OK2fbbqNiAqwoE:-Lril3Yt8pGR9K9lS9EA:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/44ee9b3d071ba953a77ed8926aee35c7c4a2af94/pkg/storage/reports/reporter.go#L389)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: extra space. 
</blockquote></details>

done

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41711#-:-Lriy4tX-bkuByHUVx7i:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)

**Pull request merged**
