### PR TITLE
sql: Replace shopspring/decimal library with inf.v0 decimal library

### PR DESCRIPTION
**Pull request by nvb**
## Reasons for the change:
- It had become apparent that `shopspring/decimal.Decimal` did not
  provide the level of control over memory allocations that we needed,
  which was a result of their explicit emphasis on ease-of-use over
  performance and immutability. Unfortunately, we are at a point where
  this poor performance was unacceptable, and we needed better memory
  management control when dealing with Decimal calculations. Because
  `inf.Dec` provides pointer semantics in an identical way to the
  `math/big` library, it gives us much better control over when to
  allocate and when to avoid allocations. This is apparent in the
  performance improvements we have seen from switching libraries and
  being smarter about allocations. For example, a relatively naive
  implementation of `dec.Sqrt` using `inf.Dec` to avoid allocations
  resulted in over a 80x speed boost, and an identical implementation of
  `inf.Mod` that simply avoids extra allocations and uses the more
  performant `inf.QuoRound` method over `decimal.Div` resulted in over a
  100x speed boost (see below). It is expected that the speedup would have
  been even more pronounced in the Decimal aggregation routines (`sum`,
  `average`, `variance`, `stddev`), which were able to remove all
  iterative decimal allocations (O(n) space efficiency -> O(1) space
  efficiency).
- Better, more transparent, precision semantics with `inf.Scale`.
- Precision is a retained trait of each decimal. This is important when
  dealing with computation that expects significant digits to be
  preserved (ie. 12 \* 0.50 == 6.0 != 6).
- `inf.Dec` provides direct access to the underlying `big.Int` using
  `dec.Unscaled`, and exposes a constructor that takes a `big.Int`. Both
  features we need that I had been struggling to push upstream.
### Effect on Encoding/Decoding:

```
name             old time/op  new time/op  delta
EncodeDecimal-4   504ns ± 9%   443ns ± 1%  -12.02%  (p=0.008 n=5+5)
DecodeDecimal-4   575ns ±12%   621ns ± 8%     ~     (p=0.056 n=5+5)
```
### Computation Performance Comparison

With `decimal.Decimal`:

```
BenchmarkDecimalMod-4      30000             33416 ns/op
BenchmarkDecimalSqrt-4      2000           1169745 ns/op
```

With `inf.Dec`:

```
BenchmarkDecimalMod-4    2000000               829 ns/op
BenchmarkDecimalSqrt-4     20000             76165 ns/op
```

Comparison:

```
name           old time/op  new time/op  delta
DecimalMod-4    116µs ± 7%     1µs ± 2%  -99.34%  (p=0.008 n=5+5)
DecimalSqrt-4  4.02ms ±11%  0.05ms ± 1%  -98.70%  (p=0.008 n=5+5)
```

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4045)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 24 files reviewed at latest revision, 5 unresolved discussions.

---

*[sql/group.go, line 842 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4045#-K9JJ8tywqu56U0G95PQ:-K9JJ8tywqu56U0G95PR:-2044507101) ([raw file](https://github.com/cockroachdb/cockroach/blob/10ce330903bb79039fefb5728507cd2ebb26de3b/sql/group.go#L842)):*
Does this need to be a pointer?

---

*[sql/group.go, line 854 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4045#-K9JJGJximxte8mPTrNz:-K9JJGJximxte8mPTrO-:-579037959) ([raw file](https://github.com/cockroachdb/cockroach/blob/10ce330903bb79039fefb5728507cd2ebb26de3b/sql/group.go#L854)):*
This constructs the error even what it is unused which is unfortunate. Perhaps just pull out the format string into a constant.

---

*[sql/parser/builtins.go, line 867 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4045#-K9JKH9-FP5szbriQMja:-K9JKH9-FP5szbriQMjb:24297127) ([raw file](https://github.com/cockroachdb/cockroach/blob/10ce330903bb79039fefb5728507cd2ebb26de3b/sql/parser/builtins.go#L867)):*
We generally use composite literal syntax instead of new: `&inf.Dec{}`. I don't think there is any reason to prefer one style over the other except consistency.

---

*[sql/parser/datum.go, line 314 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4045#-K9JJmVEBglpmPSeIDvB:-K9JJmVEBglpmPSeIDvC:740089098) ([raw file](https://github.com/cockroachdb/cockroach/blob/10ce330903bb79039fefb5728507cd2ebb26de3b/sql/parser/datum.go#L314)):*
Why is this a pointer?

---

*[util/decimal.go, line 17 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4045#-K9JLcQsMiQBZnVEbMXq:-K9JLcQsMiQBZnVEbMXr:17267589) ([raw file](https://github.com/cockroachdb/cockroach/blob/10ce330903bb79039fefb5728507cd2ebb26de3b/util/decimal.go#L17)):*
Wonder if this should go in a `util/decimal` package. Any reason for it to live here? Then you could have `decimal.NewFromFloat`, `decimal.Sqrt`, etc.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4045)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 24 files reviewed at latest revision, 5 unresolved discussions.

---

*[sql/group.go, line 842 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4045#-K9JJ8tywqu56U0G95PQ:-K9Jf-F4kgwKIo5So4_p:1747958857) ([raw file](https://github.com/cockroachdb/cockroach/blob/10ce330903bb79039fefb5728507cd2ebb26de3b/sql/group.go#L842)):*
It makes using it a lot more convenient if it is. Same with the fields in `decimalVarianceAggregate`. Otherwise I would need to take each of their addresses during every use

---

*[sql/group.go, line 854 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4045#-K9JJGJximxte8mPTrNz:-K9J_LCsWMLkY_DVAGb0:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/10ce330903bb79039fefb5728507cd2ebb26de3b/sql/group.go#L854)):*
Done.

---

*[sql/parser/builtins.go, line 867 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4045#-K9JKH9-FP5szbriQMja:-K9J_Tuo59EjN_1jIoLO:-1891122515) ([raw file](https://github.com/cockroachdb/cockroach/blob/10ce330903bb79039fefb5728507cd2ebb26de3b/sql/parser/builtins.go#L867)):*
It seems like the `new` syntax is a lot more common when it comes to the `math/big` package.  One nice benefit of this syntax is that it supports chaining directly onto the `new(inf.Big).Mul(...)`. In the past I've generally seen that `new` is used for allocating types that have no exported fields and use pointers as their "natural" form (pointer receivers), so I would prefer to keep it here.

---

*[sql/parser/datum.go, line 314 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4045#-K9JJmVEBglpmPSeIDvB:-K9Jb88q7qHlwWmka45D:1206834278) ([raw file](https://github.com/cockroachdb/cockroach/blob/10ce330903bb79039fefb5728507cd2ebb26de3b/sql/parser/datum.go#L314)):*
Because a pointer to an `inf.Dec` is the "natural" form of `inf.Dec`, which means it is a lot more convenient to have this as a pointer. An example is using `DDecimal.Dec` as arguments to decimal operations directly, instead of having take its address every time it needs to be used. That said, I'm not 100% convinced on this one, so what reasons do you have against using a pointer here?

---

*[util/decimal.go, line 17 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4045#-K9JLcQsMiQBZnVEbMXq:-K9Je70Q7x_q2dC36U8A:-244638468) ([raw file](https://github.com/cockroachdb/cockroach/blob/10ce330903bb79039fefb5728507cd2ebb26de3b/util/decimal.go#L17)):*
Done. Although I'm keeping the name `NewDecFromFloat` to keep the name consistent with `NewDec` and `NewDecBig`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4045)*

**Comment by petermattis** [comment]
LGTM modulo the pointer vs value stuff.

---

Review status: 0 of 24 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[sql/group.go, line 842 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4045#-K9JJ8tywqu56U0G95PQ:-K9KGW-hdRHWPclus4lY:-1436280209) ([raw file](https://github.com/cockroachdb/cockroach/blob/10ce330903bb79039fefb5728507cd2ebb26de3b/sql/group.go#L842)):*
Taking the address of a field in a struct is a small price to avoid an allocation. Let's switch this and the other places to a value. 

---

*[sql/group.go, line 941 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4045#-K9KHEDmiVGyFHDh-kLJ:-K9KHEDmiVGyFHDh-kLK:1996296084) ([raw file](https://github.com/cockroachdb/cockroach/blob/c21c1fbc47156c70ebcddfa6cf12114459d94476/sql/group.go#L941)):*
As mentioned above, these should all be values to avoid allocations. 

---

*[sql/group.go, line 948 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4045#-K9KHWUZaKBTza0-fXFe:-K9KHWUZaKBTza0-fXFf:1529013852) ([raw file](https://github.com/cockroachdb/cockroach/blob/c21c1fbc47156c70ebcddfa6cf12114459d94476/sql/group.go#L948)):*
What's the difference between `inf.NewDec(0, 0)` and `new(inf.Dec)`? Looks like they should be equivalent to me, but perhaps I'm missing something.

---

*[sql/parser/datum.go, line 314 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4045#-K9JJmVEBglpmPSeIDvB:-K9KHyL0m3XksaKKvwG7:-344734153) ([raw file](https://github.com/cockroachdb/cockroach/blob/10ce330903bb79039fefb5728507cd2ebb26de3b/sql/parser/datum.go#L314)):*
As mentioned in another response, using a pointer implies an extra allocation that can be easily avoided by not using a pointer. Let's switch this to a value. The compiler will tell you everywhere the code needs to be fixed.

As another point in favor of making this a value, notice how `inf.Dec` itself is implemented. It internally has a `Dec.unscaled` field which is a `big.Int`, not `*big.Int`. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4045#-:-K9KJAKEn42aQR5a17NL:1407720279)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 24 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[sql/group.go, line 948 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4045#-K9KHWUZaKBTza0-fXFe:-K9PezHJCWzVZHI9SVpt:-437427662) ([raw file](https://github.com/cockroachdb/cockroach/blob/c21c1fbc47156c70ebcddfa6cf12114459d94476/sql/group.go#L948)):*
Yeah, they are equivalent. I'll make the change wherever needed.

---

*[sql/parser/datum.go, line 314 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4045#-K9JJmVEBglpmPSeIDvB:-K9PcFCcFj4CAPKtHZuh:1548695330) ([raw file](https://github.com/cockroachdb/cockroach/blob/10ce330903bb79039fefb5728507cd2ebb26de3b/sql/parser/datum.go#L314)):*
Making this change across the board was pretty straightforward, but it prompted the issue that because `inf.Dec.unscaled ` contains a `big.nat`, which in turn contains a slice of `Word`s, `DDecimal` itself will now become unhashable (can't be used as a map key), and more importantly, will now become uncomparable. This presents a bigger issue because comparing `Datum` against `parser.DNull` is [extremely](https://github.com/cockroachdb/cockroach/blob/master/sql/select.go#L1066) [common](https://github.com/cockroachdb/cockroach/blob/191a473649cc3fe752af5515f391ea359455947a/sql/parser/eval.go#L743) throughout the `sql` package. Going forward with this, I think I'd have to find another way to make these comparisons (something like `parser.IsNull(Datum) bool` which would do a type switch), but before doing so, I'm curious if you have any better ideas for this issue?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4045)*

**Comment by petermattis** [comment]
Review status: 0 of 24 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/parser/datum.go, line 314 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4045#-K9JJmVEBglpmPSeIDvB:-K9PhJ6voaVXRKvABmlE:801621785) ([raw file](https://github.com/cockroachdb/cockroach/blob/10ce330903bb79039fefb5728507cd2ebb26de3b/sql/parser/datum.go#L314)):*
Do we use `parser.Datum` as the key in any `map` structures? I see the `datumToOid` map, but I think that is fixable using `reflect.TypeOf`. 

Even though `parser.DDecimal` cannot be compared with itself, you should still be able to compare `parser.DDecimal` with `parser.DNull` : http://play.golang.org/p/NnLh09H1gp. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4045)*

**Comment by tamird** [comment]
Reviewed 22 of 24 files at r1, 5 of 7 files at r2, 2 of 2 files at r3, 8 of 8 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[util/decimal_test.go, line 23 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4045#-K9Jj0WMEoGUgF8bbdyy:-K9Jj0WMEoGUgF8bbdyz:-375874694) ([raw file](https://github.com/cockroachdb/cockroach/blob/56bec3a9683289b2b39458cdd903689fba01b60d/util/decimal_test.go#L23)):*
nit: swap with the inf import

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4045)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[sql/parser/datum.go, line 314 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4045#-K9JJmVEBglpmPSeIDvB:-K9Q00EzQ-q6iWYX_hdb:228797639) ([raw file](https://github.com/cockroachdb/cockroach/blob/10ce330903bb79039fefb5728507cd2ebb26de3b/sql/parser/datum.go#L314)):*
Ah sorry, I missed exactly what was breaking my tests. The actual issue is our use of sentinel variables as type indicators (`DummyBool`, `DummyDecimal`, etc.) and comparing them directly during type checking. In any of these cases, if two `DummyDecimal`s are involved, the comparison will panic. I'm wondering if we need to change all of the `DummyABC == DummyXYZ` to `DummyABC.Type() == DummyXYZ.Type()` to force a string comparison. Another option would be to pass references to these sentinel values, but that might mess with their shared Datum interface.

---

*[util/decimal/decimal_test.go, line 23 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4045#-K9Jj0WMEoGUgF8bbdyy:-K9Q1TYIKG19P6Wa4LVm:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/56bec3a9683289b2b39458cdd903689fba01b60d/util/decimal/decimal_test.go#L23)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4045)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/parser/datum.go, line 314 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4045#-K9JJmVEBglpmPSeIDvB:-K9Q6EpR2ZKut6JuWMj4:-1685667996) ([raw file](https://github.com/cockroachdb/cockroach/blob/10ce330903bb79039fefb5728507cd2ebb26de3b/sql/parser/datum.go#L314)):*
Another option would be to change all Dummy variable comparisons to call some method like (or just do it inline):

```
func EqualDatumTypes(x, y Datum) bool {
	return reflect.TypeOf(x) == reflect.TypeOf(y)
}
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4045)*

**Comment by nvanbenschoten** [comment]
Review status: 10 of 26 files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/group.go, line 842 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4045#-K9JJ8tywqu56U0G95PQ:-K9YB535dDmEQHBbE-yB:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/10ce330903bb79039fefb5728507cd2ebb26de3b/sql/group.go#L842)):*
Done.

---

*[sql/group.go, line 941 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4045#-K9KHEDmiVGyFHDh-kLJ:-K9YB6UgYxv_NYTTn9e1:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/c21c1fbc47156c70ebcddfa6cf12114459d94476/sql/group.go#L941)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4045)*

**Comment by nvanbenschoten** [comment]
Review status: 10 of 26 files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/parser/datum.go, line 314 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4045#-K9JJmVEBglpmPSeIDvB:-K9YBHnq1rseWh28frIN:872148848) ([raw file](https://github.com/cockroachdb/cockroach/blob/10ce330903bb79039fefb5728507cd2ebb26de3b/sql/parser/datum.go#L314)):*
This was resolved in #4075, allowing this PR to now work correctly.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4045)*

**Comment by tamird** [comment]
Reviewed 16 of 16 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4045)*

**Pull request merged**
