### PR TITLE
*: upgrade grpc to v1.47.0

### LINKED ISSUE #81227: kvserver: v21.2.7: nil pointer in gRPC transport when sending snapshots
This issue was autofiled by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry link: https://sentry.io/organizations/cockroach-labs/issues/3269587070/?referrer=webhooks_plugin

Panic message:

>panic.go:965: runtime error: invalid memory address or nil pointer dereference
--
runtime.errorString
panic.go:965: *withstack.withStack (top exception)

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

/usr/local/go/src/runtime/panic.go#L964-L966 in runtime.gopanic
/usr/local/go/src/runtime/panic.go#L211-L213 in runtime.panicmem
/usr/local/go/src/runtime/signal_unix.go#L733-L735 in runtime.sigpanic
https://github.com/cockroachdb/cockroach/blob/37dee546a7c52870a8dc58826f0cffe2afa8d47a/vendor/google.golang.org/grpc/internal/transport/transport.go#L308-L310 in google.golang.org/grpc/internal/transport.(*Stream).compareAndSwapState
https://github.com/cockroachdb/cockroach/blob/37dee546a7c52870a8dc58826f0cffe2afa8d47a/vendor/google.golang.org/grpc/internal/transport/http2_client.go#L927-L929 in google.golang.org/grpc/internal/transport.(*http2Client).Write
https://github.com/cockroachdb/cockroach/blob/37dee546a7c52870a8dc58826f0cffe2afa8d47a/vendor/google.golang.org/grpc/stream.go#L845-L847 in google.golang.org/grpc.(*clientStream).CloseSend.func1
https://github.com/cockroachdb/cockroach/blob/37dee546a7c52870a8dc58826f0cffe2afa8d47a/vendor/google.golang.org/grpc/stream.go#L661-L663 in google.golang.org/grpc.(*clientStream).withRetry
https://github.com/cockroachdb/cockroach/blob/37dee546a7c52870a8dc58826f0cffe2afa8d47a/vendor/google.golang.org/grpc/stream.go#L852-L854 in google.golang.org/grpc.(*clientStream).CloseSend
https://github.com/cockroachdb/cockroach/blob/37dee546a7c52870a8dc58826f0cffe2afa8d47a/pkg/kv/kvserver/raft_transport.go#L690-L692 in pkg/kv/kvserver.(*RaftTransport).SendSnapshot.func1
https://github.com/cockroachdb/cockroach/blob/37dee546a7c52870a8dc58826f0cffe2afa8d47a/pkg/kv/kvserver/raft_transport.go#L694-L696 in pkg/kv/kvserver.(*RaftTransport).SendSnapshot
https://github.com/cockroachdb/cockroach/blob/37dee546a7c52870a8dc58826f0cffe2afa8d47a/pkg/kv/kvserver/replica_command.go#L2524-L2526 in pkg/kv/kvserver.(*Replica).sendSnapshot.func4
https://github.com/cockroachdb/cockroach/blob/37dee546a7c52870a8dc58826f0cffe2afa8d47a/pkg/util/contextutil/context.go#L88-L90 in pkg/util/contextutil.RunWithTimeout
https://github.com/cockroachdb/cockroach/blob/37dee546a7c52870a8dc58826f0cffe2afa8d47a/pkg/kv/kvserver/replica_command.go#L2522-L2524 in pkg/kv/kvserver.(*Replica).sendSnapshot
https://github.com/cockroachdb/cockroach/blob/37dee546a7c52870a8dc58826f0cffe2afa8d47a/pkg/kv/kvserver/replica_command.go#L1679-L1681 in pkg/kv/kvserver.(*Replica).initializeRaftLearners
https://github.com/cockroachdb/cockroach/blob/37dee546a7c52870a8dc58826f0cffe2afa8d47a/pkg/kv/kvserver/replica_command.go#L1048-L1050 in pkg/kv/kvserver.(*Replica).changeReplicasImpl
https://github.com/cockroachdb/cockroach/blob/37dee546a7c52870a8dc58826f0cffe2afa8d47a/pkg/kv/kvserver/replicate_queue.go#L1362-L1364 in pkg/kv/kvserver.(*replicateQueue).changeReplicas
https://github.com/cockroachdb/cockroach/blob/37dee546a7c52870a8dc58826f0cffe2afa8d47a/pkg/kv/kvserver/replicate_queue.go#L1123-L1125 in pkg/kv/kvserver.(*replicateQueue).considerRebalance
https://github.com/cockroachdb/cockroach/blob/37dee546a7c52870a8dc58826f0cffe2afa8d47a/pkg/kv/kvserver/replicate_queue.go#L481-L483 in pkg/kv/kvserver.(*replicateQueue).processOneChange
https://github.com/cockroachdb/cockroach/blob/37dee546a7c52870a8dc58826f0cffe2afa8d47a/pkg/kv/kvserver/replicate_queue.go#L303-L305 in pkg/kv/kvserver.(*replicateQueue).process
https://github.com/cockroachdb/cockroach/blob/37dee546a7c52870a8dc58826f0cffe2afa8d47a/pkg/kv/kvserver/queue.go#L958-L960 in pkg/kv/kvserver.(*baseQueue).processReplica.func1
https://github.com/cockroachdb/cockroach/blob/37dee546a7c52870a8dc58826f0cffe2afa8d47a/pkg/util/contextutil/context.go#L88-L90 in pkg/util/contextutil.RunWithTimeout
https://github.com/cockroachdb/cockroach/blob/37dee546a7c52870a8dc58826f0cffe2afa8d47a/pkg/kv/kvserver/queue.go#L917-L919 in pkg/kv/kvserver.(*baseQueue).processReplica
https://github.com/cockroachdb/cockroach/blob/37dee546a7c52870a8dc58826f0cffe2afa8d47a/pkg/kv/kvserver/queue.go#L837-L839 in pkg/kv/kvserver.(*baseQueue).processLoop.func2.1
https://github.com/cockroachdb/cockroach/blob/37dee546a7c52870a8dc58826f0cffe2afa8d47a/pkg/util/stop/stopper.go#L441-L443 in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
/usr/local/go/src/runtime/asm_amd64.s#L1370-L1372 in runtime.goexit
</details>

```
/usr/local/go/src/runtime/panic.go in runtime.gopanic at line 965
/usr/local/go/src/runtime/panic.go in runtime.panicmem at line 212
/usr/local/go/src/runtime/signal_unix.go in runtime.sigpanic at line 734
vendor/google.golang.org/grpc/internal/transport/transport.go in google.golang.org/grpc/internal/transport.(*Stream).compareAndSwapState at line 309
vendor/google.golang.org/grpc/internal/transport/http2_client.go in google.golang.org/grpc/internal/transport.(*http2Client).Write at line 928
vendor/google.golang.org/grpc/stream.go in google.golang.org/grpc.(*clientStream).CloseSend.func1 at line 846
vendor/google.golang.org/grpc/stream.go in google.golang.org/grpc.(*clientStream).withRetry at line 662
vendor/google.golang.org/grpc/stream.go in google.golang.org/grpc.(*clientStream).CloseSend at line 853
pkg/kv/kvserver/raft_transport.go in pkg/kv/kvserver.(*RaftTransport).SendSnapshot.func1 at line 691
pkg/kv/kvserver/raft_transport.go in pkg/kv/kvserver.(*RaftTransport).SendSnapshot at line 695
pkg/kv/kvserver/replica_command.go in pkg/kv/kvserver.(*Replica).sendSnapshot.func4 at line 2525
pkg/util/contextutil/context.go in pkg/util/contextutil.RunWithTimeout at line 89
pkg/kv/kvserver/replica_command.go in pkg/kv/kvserver.(*Replica).sendSnapshot at line 2523
pkg/kv/kvserver/replica_command.go in pkg/kv/kvserver.(*Replica).initializeRaftLearners at line 1680
pkg/kv/kvserver/replica_command.go in pkg/kv/kvserver.(*Replica).changeReplicasImpl at line 1049
pkg/kv/kvserver/replicate_queue.go in pkg/kv/kvserver.(*replicateQueue).changeReplicas at line 1363
pkg/kv/kvserver/replicate_queue.go in pkg/kv/kvserver.(*replicateQueue).considerRebalance at line 1124
pkg/kv/kvserver/replicate_queue.go in pkg/kv/kvserver.(*replicateQueue).processOneChange at line 482
pkg/kv/kvserver/replicate_queue.go in pkg/kv/kvserver.(*replicateQueue).process at line 304
pkg/kv/kvserver/queue.go in pkg/kv/kvserver.(*baseQueue).processReplica.func1 at line 959
pkg/util/contextutil/context.go in pkg/util/contextutil.RunWithTimeout at line 89
pkg/kv/kvserver/queue.go in pkg/kv/kvserver.(*baseQueue).processReplica at line 918
pkg/kv/kvserver/queue.go in pkg/kv/kvserver.(*baseQueue).processLoop.func2.1 at line 838
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 442
/usr/local/go/src/runtime/asm_amd64.s in runtime.goexit at line 1371
```

| Tag | Value |
|---|---|
| Cockroach Release | `v21.2.7` |
| Cockroach SHA: | 37dee546a7c52870a8dc58826f0cffe2afa8d47a |
| Platform | linux amd64 |
| Distribution | CCL |
| Environment | v21.2.7 |
| Command | server |
| Go Version | ``|
| # of CPUs ||
| # of Goroutines ||

Jira issue: CRDB-15285

### PR DESCRIPTION
**Pull request by pav-kv**
Fixes #81227

Release note: upgrade grpc from v1.46.0 to v.1.47.0 which fixes a subtle bug
causing panic on a nil pointer.

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]
LGTM, but we should squash this into a single commit so the deps aren't out of sync on the first one.

**Comment by pavelkalinnikov** [comment]
bors r=erikgrinaker

**Comment by pavelkalinnikov** [comment]
bors retry

**Comment by pavelkalinnikov** [comment]
blathers backport 22.2

**Pull request merged**
