### PR TITLE
Absorb log/logpb into log

### PR DESCRIPTION
**Pull request by tamird**
@tschottdorf

### CODE REVIEW

**Comment by tschottdorf** [comment]
`util/log` doesn't have to depend on `proto` (it currently does because of the log reading logic, but that could refactor out). If we don't care about that LGTM, otherwise moving the part of `util/log` that needs `proto` together with `logpb` seems better.

**Comment by tamird** [comment]
Wait, I don't follow - if `util/log` -> `util/log/logpb` -> `proto` then `util/log` does depend on `proto`.

**Comment by tschottdorf** [comment]
Sorry, that got muddled up. I'm suggesting (not 100% sure it would work, but I think)
`util/log` (without dependency to `proto`) -> `util/logpb` <- `util/log/logparser` -> `proto`.

**Comment by tamird** [comment]
Oh, I see. That does seem worthwhile. I'll file an issue.

**Comment by tamird** [comment]
Wait, I was wrong. `logpb` will always depend on `proto`, so that won't work.

**Comment by tschottdorf** [comment]
oh, right. Casttype. Well, isn't merging this fine then?

**Comment by tamird** [comment]
Yep.

**Pull request merged**
