### PR TITLE
sql: add database as stmt key and return on stmts stats

### PR DESCRIPTION
**Pull request by maryliag**
The database should be part of a statement key, so that the same query executed
on different databases are considered different fingerprints.
These changes were made so that not only the database is added to the key,
but its value is also returned as a parameter for each statement,
so it can be displayed on the console.

A new function returning all databases was also created
and will be used to create a filter on Statements Page.

A following PR with the changes on cluster-ui to display the database
information and also the filter  will be created shortly.

New routes were created based on existing statement routes that add
the possibility of a database name to be passed on it,
and resulting on the page displaying only statements that were
executed under the selected database.

See also: https://github.com/cockroachdb/cockroach/issues/33316

Release note (sql change): Returning database name as part of the
key on statement statistics

Release note (ui change): New routes created for statements.
A database name can be passed on statements routes,
so only statements executed on that particular database are displayed.

New function returning all databases that had at least one statement
executed during the current statistics collection period.

### CODE REVIEW

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64087)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[pkg/roachpb/app_stats.proto, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64087#-MYudMEuD_R1CX9sCFG8:-MYudMEuD_R1CX9sCFG9:b-do16b9) ([raw file](https://github.com/cockroachdb/cockroach/blob/972f5945333cc03f4c06a90ebbc31c7984ef4a56/pkg/roachpb/app_stats.proto#L101)):*
> ```protobuf
> 
>   // Database is the name of the session's database where the statement was executed
>   optional string database = 24 [(gogoproto.nullable) = false];
> ```

Do we need to add this field to both `StatementStatistics` and `StatementStatisticsKey`? It feels a bit redundant to me :thinking:

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64087)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/roachpb/app_stats.proto, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64087#-MYudMEuD_R1CX9sCFG8:-MYunAYwARpkrO1lJM06:bmclyor) ([raw file](https://github.com/cockroachdb/cockroach/blob/972f5945333cc03f4c06a90ebbc31c7984ef4a56/pkg/roachpb/app_stats.proto#L101)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Do we need to add this field to both `StatementStatistics` and `StatementStatisticsKey`? It feels a bit redundant to me :thinking:
</blockquote></details>

They serve different purposes. On `StatementStatistics` it will be a value returned on the statement stats so it can be used to display on the ui for example. On `StatementStatisticsKey` is a value being used to group statements, so the same query but on different databases are not considered the same fingerprint

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64087)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[pkg/roachpb/app_stats.proto, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64087#-MYudMEuD_R1CX9sCFG8:-MYutFm1BcWy2eP8gyH9:bh9i8s0) ([raw file](https://github.com/cockroachdb/cockroach/blob/972f5945333cc03f4c06a90ebbc31c7984ef4a56/pkg/roachpb/app_stats.proto#L101)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

They serve different purposes. On `StatementStatistics` it will be a value returned on the statement stats so it can be used to display on the ui for example. On `StatementStatisticsKey` is a value being used to group statements, so the same query but on different databases are not considered the same fingerprint
</blockquote></details>

I think we [returns](https://github.com/cockroachdb/cockroach/blob/8f3924a3771052911d9827338dfda36e4e812d9f/pkg/server/serverpb/status.proto#L920) `StatementStatisticsKey` as part of our `StatementResponse` for the RPC endpoint on the status server. If I didn't miss anything, I think UI can fetch that value directly from the `StatementStatisticsKey` part of the protobuf instead of the `StatementStatistics` part of the protobuf.

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64087)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/roachpb/app_stats.proto, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64087#-MYudMEuD_R1CX9sCFG8:-MYuyyxX8nt1iab8durH:b-tpmfee) ([raw file](https://github.com/cockroachdb/cockroach/blob/972f5945333cc03f4c06a90ebbc31c7984ef4a56/pkg/roachpb/app_stats.proto#L101)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

I think we [returns](https://github.com/cockroachdb/cockroach/blob/8f3924a3771052911d9827338dfda36e4e812d9f/pkg/server/serverpb/status.proto#L920) `StatementStatisticsKey` as part of our `StatementResponse` for the RPC endpoint on the status server. If I didn't miss anything, I think UI can fetch that value directly from the `StatementStatisticsKey` part of the protobuf instead of the `StatementStatistics` part of the protobuf.
</blockquote></details>

I did this way to have stats separated of key, in case we decide to change to key in the future, the stats wouldn't be affected. But since you mention, I see that a few other fields also used on key are not being duplicated here, so I'll remove it from stats and leav only on key

**Review by Azhng — COMMENTED** [review]
Backend code looks good to me. 

Started reviewing frontend stuff but realized I am not really that familiar with the code there and have too many questions. I left some of them here. It would be great if we can get one of the cluster-ui ppl here to take a look.

> Reviewed 8 of 16 files at r1, 7 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64087#-:-MYw36-A3h9GqbpB2ZWo:b-espacn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @maryliag)

___
*[pkg/ui/src/app.tsx, line 206 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64087#-MYw1vAzDVO07j8xKzn8:-MYw1vAzDVO07j8xKzn9:b-aihbw8) ([raw file](https://github.com/cockroachdb/cockroach/blob/380e3321a25e45a922565c1376663ee15da5f83f/pkg/ui/src/app.tsx#L206)):*
> ```XML
>                 <Route
>                   exact
>                   path={`/statements/:${appAttr}/:${databaseAttr}/:${implicitTxnAttr}/:${statementAttr}`}
> ```

I'm not too familiar with the `Route` component here. So I have a few questions:
1. when we parse the url embedded arguments, is the position for each argument fixed in the url? 
2. seems like we are omitting `${appAttr}` in the `/statement` routes, is this intentional? 
___
*[pkg/ui/src/views/statements/statementDetails.tsx, line 137 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64087#-MYw-VwW9kWaus8Or50V:-MYw-VwW9kWaus8Or50W:b-a2i6il) ([raw file](https://github.com/cockroachdb/cockroach/blob/380e3321a25e45a922565c1376663ee15da5f83f/pkg/ui/src/views/statements/statementDetails.tsx#L137)):*
> ```XML
>     stmt.statement === statement &&
>     stmt.implicit_txn === implicitTxn &&
>     (stmt.database == database || database == null);
> ```

Hmm why are we using `==` + checking for null here instead of `===` ?
___
*[pkg/ui/src/views/statements/statementsPage.tsx, line 48 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64087#-MYw-wBuDV65bsdQW2cU:-MYw-wBuDV65bsdQW2cV:b-8yyvp0) ([raw file](https://github.com/cockroachdb/cockroach/blob/380e3321a25e45a922565c1376663ee15da5f83f/pkg/ui/src/views/statements/statementsPage.tsx#L48)):*
> ```XML
> } from "src/redux/analyticsActions";
> import { resetSQLStatsAction } from "src/redux/sqlStats";
> import { LocalSetting } from "oss/src/redux/localsettings";
> ```

Maybe just `src/redux/localsettings` instead of `oss/src/redux/localsettings`?  Is there a specific reason that there's a `oss` prefix here?
___
*[pkg/ui/src/views/statements/statementsPage.tsx, line 64 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64087#-MYw0o7X8bAqlA5uZqGt:-MYw0o7X8bAqlA5uZqGu:b-n9vlvg) ([raw file](https://github.com/cockroachdb/cockroach/blob/380e3321a25e45a922565c1376663ee15da5f83f/pkg/ui/src/views/statements/statementsPage.tsx#L64)):*
> ```XML
> // that should be used to group statements on this page.
> // Parameters being used: using node_id, implicit_txn and database.
> function statementKey(stmt: ExecutionStatistics): string {
> ```

I think there's another copy of this function in `statementDetails.tsx`. Perhaps refactor them so we don't have duplicated code?

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64087)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/roachpb/app_stats.proto, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64087#-MYudMEuD_R1CX9sCFG8:-MYyqyUD1JP92u4Ne6oA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/972f5945333cc03f4c06a90ebbc31c7984ef4a56/pkg/roachpb/app_stats.proto#L101)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

I did this way to have stats separated of key, in case we decide to change to key in the future, the stats wouldn't be affected. But since you mention, I see that a few other fields also used on key are not being duplicated here, so I'll remove it from stats and leav only on key
</blockquote></details>

Done.
___
*[pkg/ui/src/app.tsx, line 206 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64087#-MYw1vAzDVO07j8xKzn8:-MYyr5iN4i_Jxau3-Ot_:bzghf96) ([raw file](https://github.com/cockroachdb/cockroach/blob/380e3321a25e45a922565c1376663ee15da5f83f/pkg/ui/src/app.tsx#L206)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

I'm not too familiar with the `Route` component here. So I have a few questions:
1. when we parse the url embedded arguments, is the position for each argument fixed in the url? 
2. seems like we are omitting `${appAttr}` in the `/statement` routes, is this intentional? 
</blockquote></details>

1. Yes, the position is fixed
2. Yes, on statements we use app to filter the statements we want to display, so we have that info on the path. On statement the filter was already applied, so we don't need to provide that extra info
___
*[pkg/ui/src/views/statements/statementDetails.tsx, line 137 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64087#-MYw-VwW9kWaus8Or50V:-MYysrkvDriNZTh9st_N:b-5sblcd) ([raw file](https://github.com/cockroachdb/cockroach/blob/380e3321a25e45a922565c1376663ee15da5f83f/pkg/ui/src/views/statements/statementDetails.tsx#L137)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm why are we using `==` + checking for null here instead of `===` ?
</blockquote></details>

I was indeed suppose to use `===`, but the check for null is still necessary. Because I want to return the statement if matches the database I added to my filter OR if I don't have any database on my filter (the null check)
___
*[pkg/ui/src/views/statements/statementsPage.tsx, line 48 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64087#-MYw-wBuDV65bsdQW2cU:-MYytFq-6KdGxp_P0UPt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/380e3321a25e45a922565c1376663ee15da5f83f/pkg/ui/src/views/statements/statementsPage.tsx#L48)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Maybe just `src/redux/localsettings` instead of `oss/src/redux/localsettings`?  Is there a specific reason that there's a `oss` prefix here?
</blockquote></details>

Done.
___
*[pkg/ui/src/views/statements/statementsPage.tsx, line 64 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64087#-MYw0o7X8bAqlA5uZqGt:-MYyvaSgA5olNahZVyna:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/380e3321a25e45a922565c1376663ee15da5f83f/pkg/ui/src/views/statements/statementsPage.tsx#L64)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

I think there's another copy of this function in `statementDetails.tsx`. Perhaps refactor them so we don't have duplicated code?
</blockquote></details>

Done.

**Review by dhartunian — COMMENTED** [review]
> Release note: None
> 
> Returns the database on the stats of each statement
> Returns the list of all databases as part of props
> 
> Addresses: #33316

Please make sure to follow the commit message structure described here: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages
The Release note should be at the end.

In addition, I think some more discussion in the commit message would be helpful here. You've made changes to UI code but your release note is "None". Is that because this change is not user visible? Why not? Will it be made visible in a separate commit? That would be useful to know. You added new routes, so again would be good to note what they are and who will be using them. As someone who is not acquainted with the work you're doing here it's useful to capture that context in the commit message so that future readers can understand why this piece of work was done.

> Reviewed 1 of 16 files at r1, 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64087#-:-MYzBrso6wwE3kjnVuQo:bfvftir)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @koorosh, @maryliag, and @nathanstilwell)

___
*[pkg/ui/src/views/statements/statementsPage.tsx, line 178 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64087#-MYzANw30W6F84sPZNwx:-MYzANw30W6F84sPZNwy:bjts4y7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a79b2168ac8e5270f2b2e75436389962a57c2405/pkg/ui/src/views/statements/statementsPage.tsx#L178)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
>     const databases: { [app: string]: boolean } = {};
>     state.data.statements.forEach(
>       (statement: ICollectedStatementStatistics) => {
>         if (statement.key.key_data.database) {
>           databases[statement.key.key_data.database] = true;
>         }
>       },
>     );
>     return Object.keys(databases);
> ```
</details>


This chunk of code seems to be looking for a "set of all database names" so it might be better to signal this by using the Set object and converting to an array afterwards. Would something like:

`Array.from(new Set(state.data.statements.map((s) => s.key.key_data.database)))`

work? (Might need a bit more code to omit nulls)

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64087)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @maryliag, and @nathanstilwell)

___
*[pkg/ui/src/util/appStats.ts, line 200 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64087#-MYzKek4Dd5M2EPesJos:-MYzKek4Dd5M2EPesJot:b6ltx3x) ([raw file](https://github.com/cockroachdb/cockroach/blob/a79b2168ac8e5270f2b2e75436389962a57c2405/pkg/ui/src/util/appStats.ts#L200)):*
> ```XML
>     statement: stmt.key.key_data.query,
>     app: stmt.key.key_data.app,
>     database: stmt.key.key_data.database,
> ```

@maryliag , is it possible to receive statements stats without `database` field? Or this field will always be populated even if it is defined as optional in proto definition?
___
*[pkg/ui/src/views/statements/statementDetails.tsx, line 137 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64087#-MYw-VwW9kWaus8Or50V:-MYzJCw8BVHE93bFowd9:b3wckyb) ([raw file](https://github.com/cockroachdb/cockroach/blob/380e3321a25e45a922565c1376663ee15da5f83f/pkg/ui/src/views/statements/statementDetails.tsx#L137)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

I was indeed suppose to use `===`, but the check for null is still necessary. Because I want to return the statement if matches the database I added to my filter OR if I don't have any database on my filter (the null check)
</blockquote></details>

As I understood, `database` param might be omitted in in a route so filter should ignore it in this case. Is it correct?
I also noticed that `database` field can contain an empty string. Should this case be handled as NULL or somehow else?

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64087)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @dhartunian, @koorosh, and @nathanstilwell)

___
*[pkg/ui/src/util/appStats.ts, line 200 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64087#-MYzKek4Dd5M2EPesJos:-MYzUWcA4GNz1Kf4Yj98:b6nhauz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a79b2168ac8e5270f2b2e75436389962a57c2405/pkg/ui/src/util/appStats.ts#L200)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

@maryliag , is it possible to receive statements stats without `database` field? Or this field will always be populated even if it is defined as optional in proto definition?
</blockquote></details>

yes, it is possible to have statements without database. Some internal statements might not have it (I've been testing this using cockroach demo and I can see several there with no database associated to it)
___
*[pkg/ui/src/views/statements/statementDetails.tsx, line 137 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64087#-MYw-VwW9kWaus8Or50V:-MYzV5Gz944k9t-658Dc:b-oeutod) ([raw file](https://github.com/cockroachdb/cockroach/blob/380e3321a25e45a922565c1376663ee15da5f83f/pkg/ui/src/views/statements/statementDetails.tsx#L137)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

As I understood, `database` param might be omitted in in a route so filter should ignore it in this case. Is it correct?
I also noticed that `database` field can contain an empty string. Should this case be handled as NULL or somehow else?
</blockquote></details>

My idea was: if a database is null it means we didn't pass that info, so we don't want to filter, so I won't filter in this case. Since we do have database as empty string and if the user passes that data, I assume it wants to match with the empty string, so I treat as any other database name and filter by the empty string. Does that make sense?
___
*[pkg/ui/src/views/statements/statementsPage.tsx, line 178 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64087#-MYzANw30W6F84sPZNwx:-MYzW5Wo05eFaiVnk9uQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a79b2168ac8e5270f2b2e75436389962a57c2405/pkg/ui/src/views/statements/statementsPage.tsx#L178)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

> ```
>     const databases: { [app: string]: boolean } = {};
>     state.data.statements.forEach(
>       (statement: ICollectedStatementStatistics) => {
>         if (statement.key.key_data.database) {
>           databases[statement.key.key_data.database] = true;
>         }
>       },
>     );
>     return Object.keys(databases);
> ```

This chunk of code seems to be looking for a "set of all database names" so it might be better to signal this by using the Set object and converting to an array afterwards. Would something like:

`Array.from(new Set(state.data.statements.map((s) => s.key.key_data.database)))`

work? (Might need a bit more code to omit nulls)
</blockquote></details>

Done.

**Review by koorosh — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64087)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @dhartunian, @koorosh, and @nathanstilwell)

___
*[pkg/ui/src/views/statements/statementDetails.tsx, line 137 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64087#-MYw-VwW9kWaus8Or50V:-MYzojMT29p72uE534FO:bn3pjvb) ([raw file](https://github.com/cockroachdb/cockroach/blob/380e3321a25e45a922565c1376663ee15da5f83f/pkg/ui/src/views/statements/statementDetails.tsx#L137)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

My idea was: if a database is null it means we didn't pass that info, so we don't want to filter, so I won't filter in this case. Since we do have database as empty string and if the user passes that data, I assume it wants to match with the empty string, so I treat as any other database name and filter by the empty string. Does that make sense?
</blockquote></details>

Probably here it's not a problem and there is no chances to get empty string because value is retrieved from url path.

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64087)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @dhartunian, @koorosh, and @nathanstilwell)

___
*[pkg/ui/src/views/statements/statementDetails.tsx, line 137 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64087#-MYw-VwW9kWaus8Or50V:-MYzqsoJ-fZl9hP2IVka:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/380e3321a25e45a922565c1376663ee15da5f83f/pkg/ui/src/views/statements/statementDetails.tsx#L137)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Probably here it's not a problem and there is no chances to get empty string because value is retrieved from url path. 
</blockquote></details>

Done.

**Pull request merged**
