### PR TITLE
exec: make the output of explain(vec) more compact

### PR DESCRIPTION
**Pull request by jordanlewis**
The treeprinter was extended to learn about different indentation width,
and explain(vec) now uses a rather compact setting.

Release note: None

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
Very nice! :lgtm:

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40565#-:-Lo845Lp6w-j31i82Evk:bh12bql)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Comment by jordanlewis** [comment]
Flake in TestDockerCLI?

bors r+

**Pull request merged**
