### PR TITLE
sql/parser: more builtin categorization

### PR DESCRIPTION
**Pull request by dt**
use constants for repeated category names and combine date and timestamp into single category.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7292)

### CODE REVIEW

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/parser/builtins.go, line 58 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7292#-KKPqMVG9dGRRTwfeo-y:-KKPqMVG9dGRRTwfeo-z:1673917655) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ccb53ea36457350b26e3c876a873ff63bb242e1/sql/parser/builtins.go#L58)):*
> ```Go
> 
> const (
> 	CategoryIDGeneration = "ID Generation"
> ```

Do these need to be exported?

---

*[sql/parser/builtins.go, line 88 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7292#-KKPqSNE3qC6M5ZOPKKP:-KKPqSNE3qC6M5ZOPKKQ:-794261688) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ccb53ea36457350b26e3c876a873ff63bb242e1/sql/parser/builtins.go#L88)):*
> ```Go
> func categoryizeType(t Datum) string {
> 	switch t {
> 	case TypeTimestamp, TypeDate, TypeInterval:
> ```

TimestampTZ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7292#-:-KKPr4DO9y1MZCv2b_qJ:1417088721)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[sql/parser/builtins.go, line 91 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7292#-KKPr0snnLJ0lwsn43px:-KKPr0snnLJ0lwsn43py:1963578187) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ccb53ea36457350b26e3c876a873ff63bb242e1/sql/parser/builtins.go#L91)):*
> ```Go
> 		return CategoryDateAndTime
> 	default:
> 		return strings.ToUpper(t.Type())
> ```

nit: how come uppercase? we don't use CAPS CASE for the constant categories =/

---

*[sql/parser/builtins_test.go, line 26 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7292#-KKPqmzZuG-8irhkWZ5J:-KKPqmzZuG-8irhkWZ5K:-1875823916) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ccb53ea36457350b26e3c876a873ff63bb242e1/sql/parser/builtins_test.go#L26)):*
> ```Go
> 		t.Fatalf("bad category: expected %q got %q", expected, actual)
> 	}
> 	if expected, actual := "Date and Time", Builtins["now"][0].Category(); expected != actual {
> ```

use the consts, luke

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7292#-:-KKPqwggBlV-T5OaQ9le:1417088721)*

**Comment by dt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[sql/parser/builtins.go, line 58 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7292#-KKPqMVG9dGRRTwfeo-y:-KKPtSSYfEXmjmsURLxP:886651903) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ccb53ea36457350b26e3c876a873ff63bb242e1/sql/parser/builtins.go#L58)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> Do these need to be exported?
</details>
nope. Done.

---

*[sql/parser/builtins.go, line 88 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7292#-KKPqSNE3qC6M5ZOPKKP:-KKPuhrnWXTytEogiR0z:-1414713386) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ccb53ea36457350b26e3c876a873ff63bb242e1/sql/parser/builtins.go#L88)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> TimestampTZ?
</details>
Done (though I don't think it ever actually gets hit -- it wasn't showing up toString'ed either) 

---

*[sql/parser/builtins.go, line 91 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7292#-KKPr0snnLJ0lwsn43px:-KKPtX-3KRdyQv8um29r:1323947265) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ccb53ea36457350b26e3c876a873ff63bb242e1/sql/parser/builtins.go#L91)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit: how come uppercase? we don't use CAPS CASE for the constant categories =/
</details>
when we fallback to the type name, putting it in uppercase matches how we usually refer to types, eg we usually say `a STRING column`.

That said, as I chatted with @jseldess after submitting this, we ended up coming up with hand-curated categories for all the types so this could actually be moot.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7292)*

**Comment by dt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[sql/parser/builtins_test.go, line 26 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7292#-KKPqmzZuG-8irhkWZ5J:-KKPv_uinibZo18Q2ce3:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ccb53ea36457350b26e3c876a873ff63bb242e1/sql/parser/builtins_test.go#L26)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> use the consts, luke
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7292)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[sql/parser/builtins.go, line 91 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7292#-KKPr0snnLJ0lwsn43px:-KKPw1s6-h7NiCJfsv6y:-1749482558) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ccb53ea36457350b26e3c876a873ff63bb242e1/sql/parser/builtins.go#L91)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> when we fallback to the type name, putting it in uppercase matches how we usually refer to types, eg we usually say `a STRING column`.
> 
> That said, as I chatted with @jseldess after submitting this, we ended up coming up with hand-curated categories for all the types so this could actually be moot.
</details>
OK, should there be some kind of assertion in the `default` case?

---

*[sql/parser/builtins.go, line 91 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7292#-KKPvzUhUinPdrh3aMCi:-KKPvzUhUinPdrh3aMCj:-1564050917) ([raw file](https://github.com/cockroachdb/cockroach/blob/b37b15832a9c6ba588d839c63777d897f8b24341/sql/parser/builtins.go#L91)):*
> ```Go
> func categoryizeType(t Datum) string {
> 	switch t {
> 	case TypeTimestamp, TypeDate, TypeInterval, TypeTimestampTZ:
> ```

something about this ordering is tickling my OCD

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7292)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/parser/builtins.go, line 91 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7292#-KKPr0snnLJ0lwsn43px:-KKPwO8Q0vzPp4zSVhR4:-752359743) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ccb53ea36457350b26e3c876a873ff63bb242e1/sql/parser/builtins.go#L91)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> OK, should there be some kind of assertion in the `default` case?
</details>
i guess that depends if we want to keep the fallback or fail loudly. As fallbacks go, it categorizing by the type name isn't the worst -- it's what we were doing until today.

---

*[sql/parser/builtins.go, line 91 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7292#-KKPvzUhUinPdrh3aMCi:-KKPwuoQBqdhNwulnzx0:1116916985) ([raw file](https://github.com/cockroachdb/cockroach/blob/b37b15832a9c6ba588d839c63777d897f8b24341/sql/parser/builtins.go#L91)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> something about this ordering is tickling my OCD
</details>
hasn't go's map iteration taught you to let go of preconceived notions of ordering?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7292)*

**Comment by mjibson** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7292)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/parser/builtins.go, line 91 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7292#-KKPr0snnLJ0lwsn43px:-KKQ0axIiKOVNe5zUcJn:917985355) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ccb53ea36457350b26e3c876a873ff63bb242e1/sql/parser/builtins.go#L91)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> i guess that depends if we want to keep the fallback or fail loudly. As fallbacks go, it categorizing by the type name isn't the worst -- it's what we were doing until today.
</details>
Well, OK.

---

*[sql/parser/builtins.go, line 91 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7292#-KKPvzUhUinPdrh3aMCi:-KKQ0d6m8TGO87exsZO0:-1507367734) ([raw file](https://github.com/cockroachdb/cockroach/blob/b37b15832a9c6ba588d839c63777d897f8b24341/sql/parser/builtins.go#L91)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> hasn't go's map iteration taught you to let go of preconceived notions of ordering?
</details>
Eh, this isn't semantic, just ugly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7292)*

**Comment by dt** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/parser/builtins.go, line 91 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7292#-KKPvzUhUinPdrh3aMCi:-KKQ45zvVoj3sfg-R5jk:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/b37b15832a9c6ba588d839c63777d897f8b24341/sql/parser/builtins.go#L91)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Eh, this isn't semantic, just ugly.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7292)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7292)*

**Pull request merged**
