### PR TITLE
storage: use `SetOptions()` when reusing Pebble iterators

### PR DESCRIPTION
**Pull request by erikgrinaker**
Iterator reuse now relies on `Pebble.SetOptions()` to configure the
reused Pebble iterator. This allows a wider range of iterators to be
reused, since previously only the bounds could be changed on existing
iterators.

Release note: None

### CODE REVIEW

**Review by jbowens — COMMENTED** [review]
Heads up that while cockroachdb/pebble#1675 merged, the Pebble bump is blocked on resolving a breaking code change to `vfs.WithDiskHealthChecks`, which in turn is blocked on cockroachdb/pebble#1690. :dizzy_face: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81242#-:-N2DmASD483vXL1uya_k:bt61hlm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nicktrav and @sumeerbhola)

**Comment by erikgrinaker** [comment]
This should be good to go now, PTAL.

A quick `kv95` run shows a slight performance regression here. I think we can merge this anyway, and work on performance optimizations later:

```
master:

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  180.0s        0       19341212       107450.5      1.6      1.1      4.5     10.5    159.4  read

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  180.0s        0        1017946         5655.2      4.0      3.3      8.9     15.2    121.6  write

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
  180.0s        0       20359158       113105.7      1.7      1.2      5.0     11.0    159.4  

setoptions:

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  180.0s        0       18849240       104717.1      1.6      1.2      4.7     10.5    117.4  read

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  180.0s        0         992337         5512.9      4.1      3.4      9.4     15.7    201.3  write

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
  180.0s        0       19841577       110230.1      1.7      1.2      5.2     11.0    201.3  
```

**Review by jbowens — APPROVED** [review]
:lgtm: 

> I think we can merge this anyway, and work on performance optimizations later

Sounds good. I'll look at cockroachdb/pebble#1709 this week, which I think might make a difference here.

> Reviewed 4 of 5 files at r4, 4 of 14 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81242#-:-N2lUYWE8CeS3Avc8rg-:bnw18r2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @erikgrinaker, @nicktrav, and @sumeerbhola)

___
*[`pkg/storage/pebble_iterator.go` line 117 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/81242#-N2lWby12m1lbFZkeygA:-N2lWby12m1lbFZkeygB:b-cyoevf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a00291aa700486027d60e3b24b3509f442871f9/pkg/storage/pebble_iterator.go#L117)):*
> ```Go
> 		} else {
> 			var err error
> 			if p.iter, err = iterToClone.Clone(); err != nil {
> ```

Just a fyi, I filed cockroachdb/pebble#1712 so that we can avoid the `SetOptions` call in this case.

**Comment by erikgrinaker** [comment]
Sounds good, TFTR!

bors r=jbowens

**Pull request merged**
