### PR TITLE
distsql: plumb fake span resolver, misc fixes

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13385)

### CODE REVIEW

**Comment by knz** [comment]
Very good work.
LGTM with two nits.

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 6 of 6 files at r3, 2 of 2 files at r4, 5 of 5 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/internal/client/txn.go, line 355 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13385#-Kc4i3FnyqsvaS9bGxRM:-Kc4i3Foj-pV3nL8-41W:b-x538sn) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9a9bcc8f1ea8429db3b0b11e30715b9866f45e2/pkg/internal/client/txn.go#L355)):*
> ```Go
> 		panic("no error")
> 	}
> 	if txn.Proto.Status == roachpb.PENDING {
> ```

I'd suggest `!= roachpb.ABORTED` here to make the intent clearer. It's not clear here that the only other possible value is ABORTED.

---

*[pkg/sql/distsql_physical_planner.go, line 114 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/13385#-Kc4ihT3xs_P_rtjGLMT:-Kc4ihT4OceHc64iWUvX:bdxovle) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc83a86ee6baad160bafb0f96ce765bf04624a9b/pkg/sql/distsql_physical_planner.go#L114)):*
> ```Go
> 		return false, expr
> 
> 	case *parser.CollateExpr:
> ```

I don't think this change belongs here (if it is necessary perhaps you can place it in a different commit.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13385#-:-Kc4iv_X5qrUeTOab_do:b-hbx76h)*

**Comment by RaduBerinde** [comment]
TFTR!

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/internal/client/txn.go, line 355 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13385#-Kc4i3FnyqsvaS9bGxRM:-Kc4jpyJYbUa4q58R-pX:bwvmt3r) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9a9bcc8f1ea8429db3b0b11e30715b9866f45e2/pkg/internal/client/txn.go#L355)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I'd suggest `!= roachpb.ABORTED` here to make the intent clearer. It's not clear here that the only other possible value is ABORTED.
</blockquote></details>

I wrote it like that initially, Andrei preferred it this way. I guess trying to `Rollback()`if we're in a `COMMIT` state is going to fail anyway, but it doesn't sound like something we should ever do.  I don't have a preference, I'll let @andreimatei chime in.

---

*[pkg/sql/distsql_physical_planner.go, line 114 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/13385#-Kc4ihT3xs_P_rtjGLMT:-Kc4kXX9iNYieQuPro_a:b-tkymcn) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc83a86ee6baad160bafb0f96ce765bf04624a9b/pkg/sql/distsql_physical_planner.go#L114)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I don't think this change belongs here (if it is necessary perhaps you can place it in a different commit.)
</blockquote></details>

Will put it in a separate commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13385#-:-Kc4jpM5mXK3RqcBr_H7:b-814g8k)*

**Comment by andreimatei** [comment]
:lgtm: this is big!

Just one question about whether the fake span resolver could be made part of `TestServerArgs`

---

Review status: 0 of 12 files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[pkg/internal/client/txn.go, line 355 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13385#-Kc4i3FnyqsvaS9bGxRM:-KcTZoNdn_h5jhtFYNHw:bpqpbkt) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9a9bcc8f1ea8429db3b0b11e30715b9866f45e2/pkg/internal/client/txn.go#L355)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I wrote it like that initially, Andrei preferred it this way. I guess trying to `Rollback()`if we're in a `COMMIT` state is going to fail anyway, but it doesn't sound like something we should ever do.  I don't have a preference, I'll let @andreimatei chime in.
</blockquote></details>

I don't feel strongly. To me, `status == PENDING` expresses the intent better.

---

*[pkg/sql/distsql_physical_planner.go, line 115 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/13385#-KcTdWAXPU_JqH06GaLe:-KcTdWAXPU_JqH06GaLf:b-ns2iav) ([raw file](https://github.com/cockroachdb/cockroach/blob/13467f2adfc21471b678c6d5537e5d3b0a6d3ce5/pkg/sql/distsql_physical_planner.go#L115)):*
> ```Go
> 
> 	case *parser.CollateExpr:
> 		v.err = errors.Errorf("collations not supported yet")
> ```

mind adding a hint about why that is or a link to a bug?

---

*[pkg/sql/executor.go, line 362 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/13385#-KcTcH0O1E5br1e3ZwwT:-KcTcH0O1E5br1e3ZwwU:b-dq4qy4) ([raw file](https://github.com/cockroachdb/cockroach/blob/42268648cb39aade119b28b08f142b49f868d9cb/pkg/sql/executor.go#L362)):*
> ```Go
> 
> // SetDistSQLSpanResolver changes the SpanResolver used for DistSQL. It is the
> // caller's responsibility to make sure no queries are being run with DistSQL at // the same time.
> ```

funky wrapping

---

*[pkg/sql/logic_test.go, line 489 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/13385#-KcTb4djKj-iegZmeBYw:-KcTb4djKj-iegZmeBYx:br2x58o) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a8694624a4871e53cb10848787766a2158d8471/pkg/sql/logic_test.go#L489)):*
> ```Go
> 			},
> 		},
> 		ReplicationMode: base.ReplicationManual,
> ```

why `manual`? Explain (maybe in the next commit) that we're going to use the fake resolver so we don't really care where the data is.
But still, would something bad happen if we don't specify the "manual" option? Having some chaos in the cluster might not be bad...

---

*[pkg/sql/logic_test.go, line 1112 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/13385#-KcTd5ssv2FLRlZlKJ6t:-KcTd5ssv2FLRlZlKJ6u:b-oy804b) ([raw file](https://github.com/cockroachdb/cockroach/blob/42268648cb39aade119b28b08f142b49f868d9cb/pkg/sql/logic_test.go#L1112)):*
> ```Go
> }
> 
> func runLogicTest(l *logicTest) {
> ```

I think I'd look better to me if `runLogicTest` were a method on `logicTest`, and if we had a ctor for `logicTest` that initialized an instance fully as opposed to having the caller initialize some fields and this initialize others.

---

*[pkg/sql/parallel_test.go, line 61 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/13385#-KcTazt-Bg6IXg2RPEKf:-KcTazt0jFY8OR1XJIfh:b-37sgul) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a8694624a4871e53cb10848787766a2158d8471/pkg/sql/parallel_test.go#L61)):*
> ```Go
> 	*testing.T
> 	ctx     context.Context
> 	cluster serverutils.TestClusterInterface
> ```

how come `parallelTest` already took a cluster?

---

*[pkg/sql/distsqlplan/fake_span_resolver.go, line 57 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/13385#-KcT_LqU0vTPOIFBxyol:-KcT_LqU0vTPOIFBxyom:b2modj5) ([raw file](https://github.com/cockroachdb/cockroach/blob/dce28237fc062d6f2f19b79952d8fb10d10db434/pkg/sql/distsqlplan/fake_span_resolver.go#L57)):*
> ```Go
> type fakeSpanResolverIterator struct {
> 	fsr *fakeSpanResolver
> 	txn *client.Txn
> ```

add a comment saying that all scans will be done in the context of `txn`, which should be the same txn as the one using the results of the fake resolver, so that resolving doesn't introduce conflicts

---

*[pkg/testutils/serverutils/test_server_shim.go, line 92 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/13385#-KcTbxeVV9PPE-eyHieO:-KcTbxeWSWMCeEJKPm2y:ba6paml) ([raw file](https://github.com/cockroachdb/cockroach/blob/42268648cb39aade119b28b08f142b49f868d9cb/pkg/testutils/serverutils/test_server_shim.go#L92)):*
> ```Go
> 	// It is the caller's responsibility to make sure no queries are being run
> 	// with DistSQL at the same time.
> 	SetDistSQLSpanResolver(spanResolver interface{})
> ```

can't the `spanResolver` be part of `TestServerArgs` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13385#-:-KcTd_hbJl8ze_oxyq7L:b-qhf55j)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 12 files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[pkg/sql/logic_test.go, line 489 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/13385#-KcTb4djKj-iegZmeBYw:-KcTzzibjnndjhcsF9nV:bl4ehf2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a8694624a4871e53cb10848787766a2158d8471/pkg/sql/logic_test.go#L489)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

why `manual`? Explain (maybe in the next commit) that we're going to use the fake resolver so we don't really care where the data is.
But still, would something bad happen if we don't specify the "manual" option? Having some chaos in the cluster might not be bad...
</blockquote></details>

Why? We're not testing KV stability here. I'd rather have the tests as reproducible as possible..

---

*[pkg/sql/parallel_test.go, line 61 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/13385#-KcTazt-Bg6IXg2RPEKf:-KcU-7wHzNG19C4UmSXs:bp165k2) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a8694624a4871e53cb10848787766a2158d8471/pkg/sql/parallel_test.go#L61)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

how come `parallelTest` already took a cluster?
</blockquote></details>

it supports multi-node (though the multi-node test is not enabled by default, #8057).

---

*[pkg/testutils/serverutils/test_server_shim.go, line 92 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/13385#-KcTbxeVV9PPE-eyHieO:-KcU-BR3hvhoOe5YRQvg:b-90bdat) ([raw file](https://github.com/cockroachdb/cockroach/blob/42268648cb39aade119b28b08f142b49f868d9cb/pkg/testutils/serverutils/test_server_shim.go#L92)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

can't the `spanResolver` be part of `TestServerArgs` ?
</blockquote></details>

From the commit message:
```
To create a fake span resolver, we need information (nodeIDs, addresses) from
all the nodes in the cluster. This prevents us from being able to pass one in
the testing knobs, as these need to be populated before server start.
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13385)*

**Comment by andreimatei** [comment]
Review status: 0 of 12 files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[pkg/testutils/serverutils/test_server_shim.go, line 92 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/13385#-KcTbxeVV9PPE-eyHieO:-KcUGn61jkdxhKqGc1G1:b1dv65l) ([raw file](https://github.com/cockroachdb/cockroach/blob/42268648cb39aade119b28b08f142b49f868d9cb/pkg/testutils/serverutils/test_server_shim.go#L92)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

From the commit message:
```
To create a fake span resolver, we need information (nodeIDs, addresses) from
all the nodes in the cluster. This prevents us from being able to pass one in
the testing knobs, as these need to be populated before server start.
```
</blockquote></details>

Ah I knew there was an explanation somewhere... I though you just said something to me offline that I forgot.
LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13385)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 12 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsql_physical_planner.go, line 115 at r11](https://reviewable.io:443/reviews/cockroachdb/cockroach/13385#-KcTdWAXPU_JqH06GaLe:-KcUe6e2FAVMcTQSQb_D:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/13467f2adfc21471b678c6d5537e5d3b0a6d3ce5/pkg/sql/distsql_physical_planner.go#L115)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

mind adding a hint about why that is or a link to a bug?
</blockquote></details>

Done.

---

*[pkg/sql/executor.go, line 362 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/13385#-KcTcH0O1E5br1e3ZwwT:-KcUeaA0O6zZjcZtg8TM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/42268648cb39aade119b28b08f142b49f868d9cb/pkg/sql/executor.go#L362)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

funky wrapping
</blockquote></details>

Done.

---

*[pkg/sql/logic_test.go, line 1112 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/13385#-KcTd5ssv2FLRlZlKJ6t:-KcUhAHKabOwowmQ6f2L:b-9if036) ([raw file](https://github.com/cockroachdb/cockroach/blob/42268648cb39aade119b28b08f142b49f868d9cb/pkg/sql/logic_test.go#L1112)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think I'd look better to me if `runLogicTest` were a method on `logicTest`, and if we had a ctor for `logicTest` that initialized an instance fully as opposed to having the caller initialize some fields and this initialize others.
</blockquote></details>

Indeed, done.

---

*[pkg/sql/distsqlplan/fake_span_resolver.go, line 57 at r8](https://reviewable.io:443/reviews/cockroachdb/cockroach/13385#-KcT_LqU0vTPOIFBxyol:-KcUjOdV45ZQkU3Zx8UM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dce28237fc062d6f2f19b79952d8fb10d10db434/pkg/sql/distsqlplan/fake_span_resolver.go#L57)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

add a comment saying that all scans will be done in the context of `txn`, which should be the same txn as the one using the results of the fake resolver, so that resolving doesn't introduce conflicts
</blockquote></details>

Done.

---

*[pkg/testutils/serverutils/test_server_shim.go, line 92 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/13385#-KcTbxeVV9PPE-eyHieO:-KcUfZhVQQMUG-X4Megd:bd0san9) ([raw file](https://github.com/cockroachdb/cockroach/blob/42268648cb39aade119b28b08f142b49f868d9cb/pkg/testutils/serverutils/test_server_shim.go#L92)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Ah I knew there was an explanation somewhere... I though you just said something to me offline that I forgot.
LGTM
</blockquote></details>

Cool, I added this information in the method comment as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13385)*

**Pull request merged**
