### PR TITLE
Revert "cli, ui: dismiss release notes signup banner per environment ...variable"

### LINKED ISSUE #57002: bank: cluster-recovery and node-restart are throughly flaky or broken
These tests are consistently failing. Here are 2 separate, unrelated PRs that can't be merged because of the tests:

https://github.com/cockroachdb/cockroach/pull/56940
https://github.com/cockroachdb/cockroach/pull/56963

Here is the test history:

https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_UnitTests_Roachtest&branch_Cockroach_UnitTests=staging&tab=buildTypeHistoryList

It's clear that it got flaky very recently, but nothing is jumping out at me.

cc @yuzefovich @nvanbenschoten

### PR DESCRIPTION
**Pull request by jordanlewis**
Closes #57002

This reverts commit dd9613cb3d5135da94cd0570351c042d19d390bb.

Release note: None

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57003#-:-MMlJaea6Ob65nRe8fLb:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @nkodali)

**Review by thoszhang — APPROVED** [review]

**Comment by nkodali** [comment]
Thanks for looking into this and reverting @jordanlewis! Will look into this tomorrow.

**Comment by jordanlewis** [comment]
No problem!

**Pull request merged**
