### PR TITLE
sqlsmith: various improvements

### PR DESCRIPTION
**Pull request by madelynnblue**

### CODE REVIEW

**Review by justinj — COMMENTED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35565#-:-L_h0nHXBUQo_kiV-Abw:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mjibson)

___
*[pkg/internal/sqlsmith/relational.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35565#-L_gsxN84o7QrP_sxFOL:-L_gsxN84o7QrP_sxFOM:bo2rfjz) ([raw file](https://github.com/cockroachdb/cockroach/blob/20ce16d1aca3325b19244469deb2c1a719f84f48/pkg/internal/sqlsmith/relational.go#L35)):*
> ```Go
> 	desiredTypes []types.T, refs colRefs,
> ) (stmt tree.SelectStatement, stmtRefs colRefs, ok bool) {
> 	if s.canRecurse() {
> ```

nit: invert and move the makeValues to the top to reduce indentation?
___
*[pkg/internal/sqlsmith/relational.go, line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35565#-L_gtb540s-dJYKYHKvA:-L_gtb540s-dJYKYHKvB:b5jlajk) ([raw file](https://github.com/cockroachdb/cockroach/blob/20ce16d1aca3325b19244469deb2c1a719f84f48/pkg/internal/sqlsmith/relational.go#L130)):*
> ```Go
> 		}
> 	}
> 	return getTableExpr(s, refs, forJoin)
> ```

nit: ditto here
___
*[pkg/internal/sqlsmith/relational.go, line 232 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35565#-L_gu-nS3X1jvlU0udS6:-L_gu-nS3X1jvlU0udS7:b-z2vfbl) ([raw file](https://github.com/cockroachdb/cockroach/blob/20ce16d1aca3325b19244469deb2c1a719f84f48/pkg/internal/sqlsmith/relational.go#L232)):*
> ```Go
> 	if d100() == 1 {
> 		clause.Distinct = true
> 		orderByRefs = selectRefs
> ```

I think this could use a comment as to why the refs need to switch here
___
*[pkg/internal/sqlsmith/relational.go, line 293 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35565#-L_guf454Zpg8jn8ybK7:-L_guf46CaXsfgskbfNZ:bp65n0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/20ce16d1aca3325b19244469deb2c1a719f84f48/pkg/internal/sqlsmith/relational.go#L293)):*
> ```Go
> 	}
> 
> 	// Use DEFAULT VALUES only sometimes.
> ```

if the select is nil does that imply `DEFAULT VALUES`? can you comment that?
___
*[pkg/internal/sqlsmith/relational.go, line 423 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35565#-L_gw9Aj-YfUUJKvHGtI:-L_gw9Aj-YfUUJKvHGtJ:b1bnm1k) ([raw file](https://github.com/cockroachdb/cockroach/blob/20ce16d1aca3325b19244469deb2c1a719f84f48/pkg/internal/sqlsmith/relational.go#L423)):*
> ```Go
> 
> 	// Returing just &values here would result in a query like `VALUES (...)` where
> 	// the columns are arbitrarily named by index (column1, column2, etc.). Since
> ```

I did not know this!
___
*[pkg/internal/sqlsmith/sampler.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35565#-L_gwl3X0kErUSbUJjTT:-L_gwl3X0kErUSbUJjTU:b4dzok4) ([raw file](https://github.com/cockroachdb/cockroach/blob/20ce16d1aca3325b19244469deb2c1a719f84f48/pkg/internal/sqlsmith/sampler.go#L26)):*
> ```Go
> // corresponding to positions in weights. They are returned at the relative
> // frequency of the values of weights. For example, if weights is {1, 3},
> // reading 4 values from the chan would return `0` one time and `1` three
> ```

Is this the desired behaviour? It seems to me like we want the possibility for a query to have like, 5 of the same operator, even if it's rare (not bothered too much either way, though).

If only some subset of them can potentially succeed then we'll still hit those with probability 1 :)
___
*[pkg/internal/sqlsmith/scalar.go, line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35565#-L_gxpmw4l_ZK941pRjY:-L_gxpmw4l_ZK941pRjZ:b-fwk7rj) ([raw file](https://github.com/cockroachdb/cockroach/blob/20ce16d1aca3325b19244469deb2c1a719f84f48/pkg/internal/sqlsmith/scalar.go#L74)):*
> ```Go
> func makeScalarSample(
> 	sampler *WeightedSampler, weights []scalarWeight, s *scope, typ types.T, refs colRefs,
> ) (tree.TypedExpr, bool) {
> ```

I don't think this needs the bool return any more.
___
*[pkg/internal/sqlsmith/scope.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35565#-L_gzElm71saDAPXxlzc:-L_gzElnE_JE7M6lIhUm:b-l3xkzi) ([raw file](https://github.com/cockroachdb/cockroach/blob/20ce16d1aca3325b19244469deb2c1a719f84f48/pkg/internal/sqlsmith/scope.go#L41)):*
> ```Go
> 
> 	// The budget tracks available complexity. It is randomly generated. Each
> 	// call to canRecurse decreases it such that canRecurse will eventually will
> ```

nit: `such that canRecurse will eventually always return false`

nice solution to this! cleaner than I was envisioning. I like how "requesting" recursion simultaneously consumes the budget.

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35565)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj)

___
*[pkg/internal/sqlsmith/relational.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35565#-L_gsxN84o7QrP_sxFOL:-L_joSAy8beletPXgVmR:b8elw5t) ([raw file](https://github.com/cockroachdb/cockroach/blob/20ce16d1aca3325b19244469deb2c1a719f84f48/pkg/internal/sqlsmith/relational.go#L35)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

nit: invert and move the makeValues to the top to reduce indentation?
</blockquote></details>

It's like this because it matches the style of the other sampling methods, some of which have a retry counter and need a safe fallback. Structuring the code this way makes the fallback always at the bottom.
___
*[pkg/internal/sqlsmith/relational.go, line 232 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35565#-L_gu-nS3X1jvlU0udS6:-L_jopxsAZO3euFz6VEF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/20ce16d1aca3325b19244469deb2c1a719f84f48/pkg/internal/sqlsmith/relational.go#L232)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

I think this could use a comment as to why the refs need to switch here
</blockquote></details>

Done.
___
*[pkg/internal/sqlsmith/relational.go, line 293 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35565#-L_guf454Zpg8jn8ybK7:-L_jp5B474Wsi2cGaIPL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/20ce16d1aca3325b19244469deb2c1a719f84f48/pkg/internal/sqlsmith/relational.go#L293)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

if the select is nil does that imply `DEFAULT VALUES`? can you comment that?
</blockquote></details>

Done.
___
*[pkg/internal/sqlsmith/relational.go, line 423 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35565#-L_gw9Aj-YfUUJKvHGtI:-L_jpGLYCIj0RsMVN-C9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/20ce16d1aca3325b19244469deb2c1a719f84f48/pkg/internal/sqlsmith/relational.go#L423)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

I did not know this!
</blockquote></details>

Done.
___
*[pkg/internal/sqlsmith/sampler.go, line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35565#-L_gwl3X0kErUSbUJjTT:-L_jpZqy40ORdx5RKAyp:b-lbx0k4) ([raw file](https://github.com/cockroachdb/cockroach/blob/20ce16d1aca3325b19244469deb2c1a719f84f48/pkg/internal/sqlsmith/sampler.go#L26)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Is this the desired behaviour? It seems to me like we want the possibility for a query to have like, 5 of the same operator, even if it's rare (not bothered too much either way, though).

If only some subset of them can potentially succeed then we'll still hit those with probability 1 :)
</blockquote></details>

Hmm good point. It's also a simpler implementation. And I can't see any obvious downsides. Done.
___
*[pkg/internal/sqlsmith/scalar.go, line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35565#-L_gxpmw4l_ZK941pRjY:-L_juDOl46AEqjMJERHd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/20ce16d1aca3325b19244469deb2c1a719f84f48/pkg/internal/sqlsmith/scalar.go#L74)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

I don't think this needs the bool return any more.
</blockquote></details>

Done.
___
*[pkg/internal/sqlsmith/scope.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35565#-L_gzElm71saDAPXxlzc:-L_juYdgBFisO-Zc7aAw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/20ce16d1aca3325b19244469deb2c1a719f84f48/pkg/internal/sqlsmith/scope.go#L41)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

nit: `such that canRecurse will eventually always return false`

nice solution to this! cleaner than I was envisioning. I like how "requesting" recursion simultaneously consumes the budget.
</blockquote></details>

Done.

**Pull request merged**
