### PR TITLE
kv,sql,storage: avoid various allocs

### PR DESCRIPTION
**Pull request by tbg**
```
$ benchdiff --old lastmerge  ./pkg/sql/tests -b -r 'Sysbench/SQL/3node/oltp_write_only' -d 1000x -c 20
test binaries already exist for 9354770: Merge #137344
test binaries already exist for 1b46187: server: remove alloc in setupSpanForIncomingRPC

  pkg=1/1 iter=20/20 cockroachdb/cockroach/pkg/sql/tests -

name                                   old time/op    new time/op    delta
Sysbench/SQL/3node/oltp_write_only-24    4.42ms ± 3%    4.43ms ± 3%    ~     (p=0.687 n=19+20)

name                                   old alloc/op   new alloc/op   delta
Sysbench/SQL/3node/oltp_write_only-24     956kB ± 3%     954kB ± 3%    ~     (p=0.134 n=18+19)

name                                   old allocs/op  new allocs/op  delta
Sysbench/SQL/3node/oltp_write_only-24     6.17k ± 1%     6.09k ± 1%  -1.31%  (p=0.000 n=16+16)
```

- **kvserver: avoid an alloc**
- **kvserver: step 1 in reducing abandon() alloc**
- **kvserver: step 2 in removing abandon() alloc**
- **kvserver: avoid allocation due to `abandon` closure in hot path**
- **kvserver: avoid Veventf-related allocs**
- **kvserverbase: make tracing alloc in hot path conditional**
- **sql: avoid ctx moving to heap in dispatchToExecutionEngine**
- **sql: avoid some vevent-related allocs**
- **storage: pool unlimited standalone BoundAccounts**
- **mvcc: remove minor allocation in MVCCGarbageCollect**
- **server: remove alloc in setupSpanForIncomingRPC**

Epic: CRDB-42584

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137569)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[`pkg/storage/mvcc.go` line 1516 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/137569#-OEPMd8H8D6W3B7BO-jH:-OEPMd8H8D6W3B7BO-jI:bukymg6) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf69152d3b788c24663feef518269a596eb46cf1/pkg/storage/mvcc.go#L1516)):*
> ```Go
> var standaloneUnlimitedBoundAccountPool = sync.Pool{
> 	New: func() interface{} {
> 		return mon.NewStandaloneUnlimitedAccount()
> ```

Can't this be a global singleton? It doesn't do anything right? CC @yuzefovich

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137569)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[`pkg/storage/mvcc.go` line 1516 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/137569#-OEPMd8H8D6W3B7BO-jH:-OEPUKyZ7Kx61YMP6att:b-cu4f4n) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf69152d3b788c24663feef518269a596eb46cf1/pkg/storage/mvcc.go#L1516)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Can't this be a global singleton? It doesn't do anything right? CC @yuzefovich
</blockquote></details>

I think it does get mutated, `b.used`. Here for example: https://github.com/cockroachdb/cockroach/blob/b87b043346c35a9291dce9a721fccc513cf22055/pkg/util/mon/bytes_usage.go#L1094

**Review by RaduBerinde — COMMENTED** [review]
Storage part :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137569#-:-OEPmqDZ2g1pbeXhOQh-:bhoblsh)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[`pkg/storage/mvcc.go` line 1516 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/137569#-OEPMd8H8D6W3B7BO-jH:-OEPmd94DOZ0KN7ONnTF:b38m5v) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf69152d3b788c24663feef518269a596eb46cf1/pkg/storage/mvcc.go#L1516)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I think it does get mutated, `b.used`. Here for example: https://github.com/cockroachdb/cockroach/blob/b87b043346c35a9291dce9a721fccc513cf22055/pkg/util/mon/bytes_usage.go#L1094
</blockquote></details>

Ah, thanks, I wonder how that is used.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137569)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde, @tbg, and @yuzefovich)

___
*[`pkg/storage/mvcc.go` line 1516 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/137569#-OEPMd8H8D6W3B7BO-jH:-OEQ7Zrz05h6KCTWxhq7:b-wowi7z) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf69152d3b788c24663feef518269a596eb46cf1/pkg/storage/mvcc.go#L1516)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Ah, thanks, I wonder how that is used.
</blockquote></details>

It gets mutated. This was a somewhat recent addition in b8d259d04cc5e7fee7742be0d853befdb8327400 when we tightened the bytes monitor API. If the standalone account is `Clear`ed or `Close`d, then it's only job is to ensure that the user never `Shrink`s by more than it called `Grow`. (This wasn't the case in the storage package because before this change the account was never cleared or closed.)

Should we consider embedding the unlimited standalone account into `pebbleMVCCScanner`? This way we'd avoid an additional `sync.Pool` access and all code paths would eliminate the allocation (this PR changes only Gets, but not Scans).

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137569)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @yuzefovich)

___
*[`pkg/storage/mvcc.go` line 1516 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/137569#-OEPMd8H8D6W3B7BO-jH:-OET4ARb0-J_9uZ-zoGP:bis5n68) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf69152d3b788c24663feef518269a596eb46cf1/pkg/storage/mvcc.go#L1516)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

It gets mutated. This was a somewhat recent addition in b8d259d04cc5e7fee7742be0d853befdb8327400 when we tightened the bytes monitor API. If the standalone account is `Clear`ed or `Close`d, then it's only job is to ensure that the user never `Shrink`s by more than it called `Grow`. (This wasn't the case in the storage package because before this change the account was never cleared or closed.)

Should we consider embedding the unlimited standalone account into `pebbleMVCCScanner`? This way we'd avoid an additional `sync.Pool` access and all code paths would eliminate the allocation (this PR changes only Gets, but not Scans).
</blockquote></details>

Good idea, https://github.com/cockroachdb/cockroach/pull/137750

**Comment by tbg** [comment]
Commits have been split out into individual PRs (all linking back to this PR), closing.

**Pull request closed without merging**
