### PR TITLE
ui: expandable job descriptions

### PR DESCRIPTION
**Pull request by madelynnblue**
Release note: None

Job descriptions are very long, and generally not that useful. Truncate
them with an expandable ellipsis to show the full description.

ss

### CODE REVIEW

**Comment by couchand** [comment]
BTW the HTML5 built-in is https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details, we might think about marking it up with that.

Seems like this is worth a release note?

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[pkg/ui/src/views/jobs/index.tsx, line 22 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21333#-L2QWrlRYsrKInEDpaCo:-L2QWrlRYsrKInEDpaCp:b-8s4cjx) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dfbdc2ea9475aa19c15d076fa8fde0d751b642f/pkg/ui/src/views/jobs/index.tsx#L22)):*
> ```XML
> import spinner from "assets/spinner.gif";
> import noResults from "assets/noresults.svg";
> import { ExpandableString } from "src/views/shared/components/expandableString";
> ```

import this above with the other code imports rather than with the assets (between dropdown and loading to alphabetize)

---

*[pkg/ui/src/views/shared/components/expandableString/index.tsx, line 5 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21333#-L2QWLA4CTcx1IKzkT3D:-L2QWLA4CTcx1IKzkT3E:be0jdnr) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dfbdc2ea9475aa19c15d076fa8fde0d751b642f/pkg/ui/src/views/shared/components/expandableString/index.tsx#L5)):*
> ```XML
> // ExpandableString displays a short string with a clickable ellipsis. When
> // clicked, the component displays long. If short is not specified, it uses
> // the first 50 chars of long.
> ```

Why 50?

---

*[pkg/ui/src/views/shared/components/expandableString/index.tsx, line 12 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21333#-L2QU-q_9IwmYG_-r_aj:-L2QU-q_9IwmYG_-r_ak:bdezhpp) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dfbdc2ea9475aa19c15d076fa8fde0d751b642f/pkg/ui/src/views/shared/components/expandableString/index.tsx#L12)):*
> ```XML
> }
> 
> export interface ExpandableStringState {
> ```

don't export this, nobody else should ever need it

---

*[pkg/ui/src/views/shared/components/expandableString/index.tsx, line 22 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21333#-L2QWV2Ddr0jY-HE_Rqr:-L2QWV2Ddr0jY-HE_Rqs:b3ogdtl) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dfbdc2ea9475aa19c15d076fa8fde0d751b642f/pkg/ui/src/views/shared/components/expandableString/index.tsx#L22)):*
> ```XML
>   constructor(props?: ExpandableStringProps, context?: any) {
>     super(props, context);
>     this.state = { expanded: false };
> ```

Instead of a constructor, default the state with a property, as in https://github.com/cockroachdb/cockroach/blob/606610b4c0be0c08b0febf8a294685fba639b36a/pkg/ui/src/views/devtools/containers/raftRanges/index.tsx#L57

---

*[pkg/ui/src/views/shared/components/expandableString/index.tsx, line 30 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21333#-L2QTPYxyOZojhJFmEtN:-L2QTPYxyOZojhJFmEtO:b-g7ta56) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dfbdc2ea9475aa19c15d076fa8fde0d751b642f/pkg/ui/src/views/shared/components/expandableString/index.tsx#L30)):*
> ```XML
>   render() {
>     const short = this.props.short || this.props.long.substr(0, 50).trim();
>     if (this.state.expanded || short === this.props.long) {
> ```

I feel like if you're going to special case the full text being short, you should be slightly smarter.  It's absolutely infuriating when one of these components hides just one or two characters, only to replace them with something longer.

That being said, I'd actually prefer if we made this more semantic.  Rather than just undifferentiated short and long text, it would be stronger as something like summary and details.  We should be more opinionated about what's the most important information to always convey in the table versus details a user can explore just if they need them.  But perhaps that's a bigger change than you want to make at the moment.

---

*[pkg/ui/src/views/shared/components/expandableString/index.tsx, line 36 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21333#-L2QR-IWIe95vWO4fBpo:-L2QR-IWIe95vWO4fBpp:b-lwrp10) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dfbdc2ea9475aa19c15d076fa8fde0d751b642f/pkg/ui/src/views/shared/components/expandableString/index.tsx#L36)):*
> ```XML
>       <span>
>         {short}
>         <a href="#" onClick={this.onClick.bind(this)}>
> ```

Instead of binding here, autobind the handler method with the syntax `onClick = (...) => {`

---

*[pkg/ui/src/views/shared/components/expandableString/index.tsx, line 37 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21333#-L2QVtgAggRwbKiaVlTr:-L2QVtgBRUifQuq6HKJC:b-5vkhip) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dfbdc2ea9475aa19c15d076fa8fde0d751b642f/pkg/ui/src/views/shared/components/expandableString/index.tsx#L37)):*
> ```XML
>         {short}
>         <a href="#" onClick={this.onClick.bind(this)}>
>           {" "}
> ```

I'd remove this space: it's just asking for a line break to push the ellipsis onto its own line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21333#-:-L2QQlppHL7hV-XNwR54:bc0qehn)*

**Comment by couchand** [comment]
I'm wondering if the ellipsis is enough of an indicator that there's more content here.  Perhaps we should give this a more obvious treatment.

@kuanluo or @josueeee do either of you have thoughts on the design of this component?  I was thinking we could probably use the same thing for the updates to the events list, so perhaps we can use some of the ideas from that work?

**Comment by kuanluo** [comment]
Thanks for surfacing this, @couchand. 

I remembered having a discussion on this when the jobs table was developed that truncating is even less useful because you can't tell what's happening at all, so we decided to have it always fully expanded.  cc: @benesch

**Comment by mjibson** [comment]
I didn't know about the `details` element, but it doesn't seem like the thing we want here, since the summary part is still displayed after it has been opened. It seems much easier to just use this component instead.

Also I dislike using a `<a href` here because it forces the use of preventDefault, but I also just want to ship this and don't care too much about finding better styling.

---

Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

*[pkg/ui/src/views/jobs/index.tsx, line 22 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21333#-L2QWrlRYsrKInEDpaCo:-L2RVn4g6wxFDw70Wp_L:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dfbdc2ea9475aa19c15d076fa8fde0d751b642f/pkg/ui/src/views/jobs/index.tsx#L22)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

import this above with the other code imports rather than with the assets (between dropdown and loading to alphabetize)
</blockquote></details>

Done.

---

*[pkg/ui/src/views/shared/components/expandableString/index.tsx, line 5 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21333#-L2QWLA4CTcx1IKzkT3D:-L2RVqqjbU41LvSU8Lpe:b50ki1f) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dfbdc2ea9475aa19c15d076fa8fde0d751b642f/pkg/ui/src/views/shared/components/expandableString/index.tsx#L5)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

Why 50?
</blockquote></details>

Had to choose something. 50 looked pretty good on the page.

---

*[pkg/ui/src/views/shared/components/expandableString/index.tsx, line 12 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21333#-L2QU-q_9IwmYG_-r_aj:-L2RVwK6w1IY9Ih4ior4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dfbdc2ea9475aa19c15d076fa8fde0d751b642f/pkg/ui/src/views/shared/components/expandableString/index.tsx#L12)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

don't export this, nobody else should ever need it
</blockquote></details>

Done.

---

*[pkg/ui/src/views/shared/components/expandableString/index.tsx, line 22 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21333#-L2QWV2Ddr0jY-HE_Rqr:-L2RWLk0XlsQo1Rb4nLM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dfbdc2ea9475aa19c15d076fa8fde0d751b642f/pkg/ui/src/views/shared/components/expandableString/index.tsx#L22)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

Instead of a constructor, default the state with a property, as in https://github.com/cockroachdb/cockroach/blob/606610b4c0be0c08b0febf8a294685fba639b36a/pkg/ui/src/views/devtools/containers/raftRanges/index.tsx#L57
</blockquote></details>

Done.

---

*[pkg/ui/src/views/shared/components/expandableString/index.tsx, line 30 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21333#-L2QTPYxyOZojhJFmEtN:-L2RWp2L7zNcKOF1gU0c:b-z789c9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dfbdc2ea9475aa19c15d076fa8fde0d751b642f/pkg/ui/src/views/shared/components/expandableString/index.tsx#L30)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

I feel like if you're going to special case the full text being short, you should be slightly smarter.  It's absolutely infuriating when one of these components hides just one or two characters, only to replace them with something longer.

That being said, I'd actually prefer if we made this more semantic.  Rather than just undifferentiated short and long text, it would be stronger as something like summary and details.  We should be more opinionated about what's the most important information to always convey in the table versus details a user can explore just if they need them.  But perhaps that's a bigger change than you want to make at the moment.
</blockquote></details>

I've made it slightly smarter: it now displays long if long.length <= 50+2, so that should account for the ellipsis being longer than the text it is replacing.

The details a user wants to see is generally just the first word ("IMPORT", "RESTORE", "BACKUP", "ALTER"), and they know the rest. The purpose of this change is to make the other columns findable. There's no details/summary stuff going on here, it's just trying to reduce row height so users can see what's going on. If we want to do a details/summary thing later that's fine with me, but I still like this method more for now.

---

*[pkg/ui/src/views/shared/components/expandableString/index.tsx, line 36 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21333#-L2QR-IWIe95vWO4fBpo:-L2RWWHV8AwiX5RjIvUR:b4o0fov) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dfbdc2ea9475aa19c15d076fa8fde0d751b642f/pkg/ui/src/views/shared/components/expandableString/index.tsx#L36)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

Instead of binding here, autobind the handler method with the syntax `onClick = (...) => {`
</blockquote></details>

Done. Considered that but was trying to maintain what I had seen other components do.

---

*[pkg/ui/src/views/shared/components/expandableString/index.tsx, line 37 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21333#-L2QVtgAggRwbKiaVlTr:-L2RWQOi5ICZKfvuSiGf:be17hp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dfbdc2ea9475aa19c15d076fa8fde0d751b642f/pkg/ui/src/views/shared/components/expandableString/index.tsx#L37)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

I'd remove this space: it's just asking for a line break to push the ellipsis onto its own line.
</blockquote></details>

I personally think it looks better with the space, but the newline concern is real. Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21333#-:-L2RVXlsedZXs9cO2Z4D:b-y62ivf)*

**Comment by couchand** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/ui/src/views/shared/components/expandableString/index.tsx, line 30 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21333#-L2QTPYxyOZojhJFmEtN:-L2RqhcMyMcqUm2QrhBI:b11n5hz) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dfbdc2ea9475aa19c15d076fa8fde0d751b642f/pkg/ui/src/views/shared/components/expandableString/index.tsx#L30)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

I've made it slightly smarter: it now displays long if long.length <= 50+2, so that should account for the ellipsis being longer than the text it is replacing.

The details a user wants to see is generally just the first word ("IMPORT", "RESTORE", "BACKUP", "ALTER"), and they know the rest. The purpose of this change is to make the other columns findable. There's no details/summary stuff going on here, it's just trying to reduce row height so users can see what's going on. If we want to do a details/summary thing later that's fine with me, but I still like this method more for now.
</blockquote></details>

Sounds good.  I think we'll circle back on this in the future, but this is good enough for the moment.

---

*[pkg/ui/src/views/shared/components/expandableString/index.tsx, line 36 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21333#-L2QR-IWIe95vWO4fBpo:-L2Rqo6a1T2kjexvfgT_:b-m91r2e) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dfbdc2ea9475aa19c15d076fa8fde0d751b642f/pkg/ui/src/views/shared/components/expandableString/index.tsx#L36)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Done. Considered that but was trying to maintain what I had seen other components do.
</blockquote></details>

Yep, there's a lot of inconsistency floating around.  I'm hoping we can start getting the momentum to doing the right thing on new stuff at least, and at some point I'll have time to go through and regularize the rest of it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21333#-:-L2Rr3wg61oGwjGcpUMh:bnfp4nl)*

**Pull request merged**
