### PR TITLE
workload: add an option to remove foreign keys from tpcc

### LINKED ISSUE #37265: workload: add flag to remove FKs and Indexes from tpc-c
**Describe the problem**

We want to test FK performance by using TPC-C with and without FKs. It requires a manual process to remove FKs (and their indexes) that can be error-prone and time-consuming. I'd like to add a flag to workload to load TPC-C without these FKs and indexes for easier testing. 

Here is what needs to be removed:

FKs
- [x] ALTER TABLE customer DROP CONSTRAINT fk_c_w_id_ref_district;
- [x] ALTER TABLE DISTRICT DROP CONSTRAINT fk_d_w_id_ref_warehouse;
- [x] ALTER TABLE history DROP CONSTRAINT fk_h_c_w_id_ref_customer;
- [x] ALTER TABLE history DROP CONSTRAINT fk_h_w_id_ref_district;
- [x] ALTER TABLE tpcc.order DROP CONSTRAINT fk_o_w_id_ref_customer;
- [x] ALTER TABLE order_line DROP CONSTRAINT fk_ol_supply_w_id_ref_stock;
- [x] ALTER TABLE order_line DROP CONSTRAINT fk_ol_w_id_ref_order;
- [x] ALTER TABLE stock DROP CONSTRAINT fk_s_i_id_ref_item;
- [x] ALTER TABLE stock DROP CONSTRAINT fk_s_w_id_ref_warehouse;

Indexes:
- [ ] drop index order_idx cascade;
- [x] drop index history_h_w_id_h_d_id_idx;
- [x] drop index history_h_c_w_id_h_c_d_id_h_c_id_idx;
- [x] drop index order_o_w_id_o_d_id_o_c_id_idx;
- [x] drop index order_line_fk;
- [x] drop index stock_s_i_id_idx;

### PR DESCRIPTION
**Pull request by yuzefovich**
Adds a --drop-foreign-keys flag that will remove the foreign keys
as well as the associated indexes.

Fixes: #37265.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
I didn't quite figure out how to generate fixtures with no foreign keys - I tried `./bin/workload fixtures make tpcc --fks=false --warehouses=1` and thought that would make what I needed, but when I ran `./bin/workload fixtures import tpcc --fks=false --warehouse=1 --db=tpcc-no-fk` the constraints and the indexes were there. What am I missing?

**Review by danhhz — CHANGES_REQUESTED** [review]
Note that `fixtures import` doesn't use the output of `fixtures make`. If you're trying to use something created by `fixtures make` then you need `fixtures load`.

The `fixtures import` you have above doesn't actually run (the --warehouse flag should be --warehouses). I tried `./bin/workload fixtures import tpcc --fks=false --warehouses=1` on master, which seems to have worked.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37345#-:-LeHjdXtCZ9CGjmccvK0:b-swlpby)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz, @jordanlewis, and @yuzefovich)

___
*[pkg/workload/tpcc/tpcc.go, line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37345#-LeHj0uS0s1XkfGdO3_R:-LeHj0uS0s1XkfGdO3_S:byqoj7f) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f69c31da71e0d4245b3587e677bfd7c27e9aad0/pkg/workload/tpcc/tpcc.go#L110)):*
> ```Go
> 		g.flags.Meta = map[string]workload.FlagMeta{
> 			`db`:                 {RuntimeOnly: true},
> 			`fks`:                {RuntimeOnly: true},
> ```

The `fks` flag doesn't modify the schema, so it should stay marked as runtime only.
___
*[pkg/workload/tpcc/tpcc.go, line 158 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37345#-LeHj4Df4avSRAbhtV8O:-LeHj4Df4avSRAbhtV8P:b4n9adh) ([raw file](https://github.com/cockroachdb/cockroach/blob/db67b3d6a32e47b4ba0115412c4c8c88d4078020/pkg/workload/tpcc/tpcc.go#L158)):*
> ```Go
> 		g.flags.BoolVar(&g.split, `split`, false, `Split tables`)
> 		g.flags.StringSliceVar(&g.zones, "zones", []string{}, "Zones for partitioning, the number of zones should match the number of partitions and the zones used to start cockroach.")
> 		g.flags.BoolVar(&g.dropForeignKeys, `drop-foreign-keys`, false, `Drops the foreign keys and the associated indexes`)
> ```

This seems quite specific to whatever you're doing and tpcc already has enough complicated flags that I'm hesitant to add more. I'm not sure it makes sense to check in like this. What's the more general problem you're trying to solve? (This is good information to include in the commit message, btw).

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37345)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/workload/tpcc/tpcc.go, line 158 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37345#-LeHj4Df4avSRAbhtV8O:-LeHqX0w6DuJl9fsAzYo:b-o10ifd) ([raw file](https://github.com/cockroachdb/cockroach/blob/db67b3d6a32e47b4ba0115412c4c8c88d4078020/pkg/workload/tpcc/tpcc.go#L158)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

This seems quite specific to whatever you're doing and tpcc already has enough complicated flags that I'm hesitant to add more. I'm not sure it makes sense to check in like this. What's the more general problem you're trying to solve? (This is good information to include in the commit message, btw).
</blockquote></details>

I just saw the issue andyw filed that you linked. Instead of this flag, can we skip the indexes that are only there for fks when the --fk flag is false? I think that would solve his problem

**Review by yuzefovich — COMMENTED** [review]
What is the difference between `fixtures import` and `fixtures load`? I think that's where my confusion comes from.

I tried `./bin/workload fixtures import tpcc --fks=false --warehouses=1` on master, and it did import the dataset without the constraints; however, the implicit indexes were imported as well (all that AndyW mentioned in the issue). I don't really understand why it happened though, are those indexes a part of the "true" tpcc schema? At first, I thought that maybe they weren't properly deleted when I dropped `tpcc` dataset, but I tried with a brand new store, and the indexes were imported.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37345#-:-LeNPBmS8hDlU3cjPv2x:bzbfjqa)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz, @jordanlewis, and @yuzefovich)

___
*[pkg/workload/tpcc/tpcc.go, line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37345#-LeHj0uS0s1XkfGdO3_R:-LeNPkW1EM_uJuaXoKCl:b-irlxj8) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f69c31da71e0d4245b3587e677bfd7c27e9aad0/pkg/workload/tpcc/tpcc.go#L110)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

The `fks` flag doesn't modify the schema, so it should stay marked as runtime only.
</blockquote></details>

I made this change so that `fks` option was visible in `./bin/workload fixtures import tpcc -h`. Is there another way to expose it there?

**Review by danhhz — COMMENTED** [review]
> What is the difference between fixtures import and fixtures load? I think that's where my confusion comes from.

OOC did you read the --help text? If that doesn't clarify this for you (and the help text is pretty short so I wouldn't be surprised), then we need to update it.

> I tried ./bin/workload fixtures import tpcc --fks=false --warehouses=1 on master, and it did import the dataset without the constraints; however, the implicit indexes were imported as well (all that AndyW mentioned in the issue). I don't really understand why it happened though, are those indexes a part of the "true" tpcc schema? At first, I thought that maybe they weren't properly deleted when I dropped tpcc dataset, but I tried with a brand new store, and the indexes were imported.

Some of the indexes are needed for query performance and some are needed for fks. If there are any that are only needed for fks, then we should alter the schemas in the tables returned by `(*tpcc).Tables` to not have them when fks is set to false. It doesn't look like we're doing that, so that's probably what you want to make this PR into. I'm not a tpcc expert though, so I couldn't tell you which index is which. cc @nvanbenschoten who may be able to tell you this off the top of his head

(In case you're wondering, we have the indexes in the schemas in the first place so that IMPORT will fill them for us, which is much faster than doing it after the fact with a bunch of schema changes.)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37345#-:-LeNe1Uy8SE1HubSAfJV:bqj1am4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/workload/tpcc/tpcc.go, line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37345#-LeHj0uS0s1XkfGdO3_R:-LeNe2eED97amog0g1hX:b-hzwqfz) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f69c31da71e0d4245b3587e677bfd7c27e9aad0/pkg/workload/tpcc/tpcc.go#L110)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I made this change so that `fks` option was visible in `./bin/workload fixtures import tpcc -h`. Is there another way to expose it there?
</blockquote></details>

Oh, I see. There's some subtly here that I don't think we've hit before. RuntimeOnly is used for two places that have so far wanted exactly the same thing. One is the set of flags that make a difference in a the data generated and saved by `fixtures make`. The other is which flags are used by `fixtures make/load/import`. At this exact moment, fks is not in the first but is in the second, which is unlike the other RuntimeOnly flags. We'd need to introduce another FlagMeta field to differentiate.

However, if you do what I suggested above (fks=false modifies the schemas to omit the indexes which are only needed for fks), then it would affect the fixture and removing RuntimeOnly would be correct. Note that this would also mean you need to regenerate the fixtures. Nathan has to do this already for one of his PRs, so maybe you could coordinate with him.

**Comment by yuzefovich** [comment]
> OOC did you read the --help text? If that doesn't clarify this for you (and the help text is pretty short so I wouldn't be surprised), then we need to update it.

Yes, I did look at the help text, but that didn't fully answer my question (so I asked you). Here is the relevant snapshot:
```
  import      import a fixture into a running cluster. An enterprise license is NOT required.
  load        load a fixture into a running cluster. An enterprise license is required.
```
My guess is that underneath these two commands use two different CRDB commands (probably `import -> IMPORT` and `load -> RESTORE`).

**Comment by nvanbenschoten** [comment]
@yuzefovich do we need this if we have https://github.com/cockroachdb/cockroach/pull/36854?

**Comment by yuzefovich** [comment]
@nvanbenschoten I think #36854 covers what I was trying to do in this PR, thanks. So I'll mark this one as DNM, wait for 36854 to go in, and will verify that #37265 is resolved.

**Comment by danhhz** [comment]
🤦‍♂ I knew that PR existed (and reviewed it) and almost mentioned it but I misremembered what it did

**Comment by nvanbenschoten** [comment]
Thanks Yahor, and sorry for sitting on that PR long enough that you had to do this extra work.

**Comment by yuzefovich** [comment]
I've just confirmed that #36854 does, indeed, accomplish what I wanted to do here, so I'm closing this PR.

**Pull request closed without merging**
