### PR TITLE
roachtest: wait for workload to ramp-up in tpcc/mixed-headroom

### PR DESCRIPTION
**Pull request by renatolabs**
In light of the recent failure investigations of the
`tpcc/mixed-headroom` roachtest, it was observed that certain errors
(such as the data race in the pebble data format upgrade) would happen
with increased frequency if the upgrade migrations are running while
the `tpcc` workload has had enough time to ramp up.

In order to increase the concurrency exposed to the
`tpcc/mixed-headroom` test, we wait a `rampDuration` (5 minutes by
default) before attempting to upgrade the cluster version.

Informs https://github.com/cockroachdb/cockroach/issues/83079.

Epic: CRDB-19321.

Release note: None.

### CODE REVIEW

**Review by srosenberg — COMMENTED** [review]
> it was observed that certain errors would happen with increased frequency

What were these errors? 

> if the upgrade migrations are running while the tpcc workload has had enough time to ramp up.

During the ramp, all nodes are running the latest _binary_ version while the cluster version remains at the fixtures' version. I believe no migrations are allowed at this stage; after `allowAutoUpgradeStep`, migrations can begin, including pebble's major format rewrites.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90399#-:-NFGI7zf8ykTgqMbrACG:b3kktae)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, and @smg260)

___
*[`pkg/cmd/roachtest/tests/tpcc.go` line 463 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90399#-NFGUiMtCD098l1HDXQC:-NFGUiMtCD098l1HDXQD:b8in1ko) ([raw file](https://github.com/cockroachdb/cockroach/blob/047744073aee36f7cdf5fe20dae2b0d9c35522b8/pkg/cmd/roachtest/tests/tpcc.go#L463)):*
> ```Go
> 				// Now start running TPCC in the background.
> 				tpccBackgroundStepper.launch,
> 				waitForWorkloadToRampUp,
> ```

Methinks you want this after the next step? Otherwise, no migrations can begin until the ramp completes.

**Review by renatolabs — COMMENTED** [review]
> What were these errors?

I was referring to the pebble migration data race (aka `exit 1`). Updated commit message to reflect that.

> During the ramp, all nodes are running the latest binary version while the cluster version remains at the fixtures' version.

That's correct; that's what I wanted here. Let me know if it the rationale is clearer now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90399#-:-NFJgsuCCLVFyu1BV2B9:b-wqpkf2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @smg260, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/tpcc.go` line 463 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90399#-NFGUiMtCD098l1HDXQC:-NFJh9MC3ruoyWf7iY3f:b-q0ca7b) ([raw file](https://github.com/cockroachdb/cockroach/blob/047744073aee36f7cdf5fe20dae2b0d9c35522b8/pkg/cmd/roachtest/tests/tpcc.go#L463)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Methinks you want this after the next step? Otherwise, no migrations can begin until the ramp completes.
</blockquote></details>

I intended for it to be here, not after the next step. The goal of this PR is to give enough time for the `runTPCC` function to set up and ramp up. I want an increased txn/sec by the time the migrations are kicked in (`allowAutoUpgradeStep`). Previously (or if we move this call as you suggest), the migrations would kick in immediately after the asynchronous `runTPCC` call and they would often finish before TPCC even had a chance to pick up the pace.

By allowing the workload to ramp up, by the time the migrations start, there will be a lot of things happening in the database at the same time as it deals with foreground traffic coming from the workload. This change, btw, led to an increase in the probability of observing the Pebble data race, and I think it makes the test stronger as it exposes the migrations to higher concurrency.

**Review by srosenberg — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90399)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, and @smg260)

___
*[`pkg/cmd/roachtest/tests/tpcc.go` line 463 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90399#-NFGUiMtCD098l1HDXQC:-NFKe8rT3zdO-uFkbtUE:b-rs4rxf) ([raw file](https://github.com/cockroachdb/cockroach/blob/047744073aee36f7cdf5fe20dae2b0d9c35522b8/pkg/cmd/roachtest/tests/tpcc.go#L463)):*
> By allowing the workload to ramp up, by the time the migrations start, there will be a lot of things happening in the database at the same time as it deals with foreground traffic coming from the workload. 

Makes sense, thanks for clarifying! It's not so much the ramp up of the foreground traffic, because I am almost certain that doesn't need 5 minutes, as it is a build-up of work items (e.g., range merges/splits, compactions, transaction retries, etc.) which have to been completed at the same time as migrations.
___
*[`pkg/cmd/roachtest/tests/tpcc.go` line 463 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90399#-NFKf8gD7mARKLpKCikf:-NFKf8gD7mARKLpKCikg:b5y9dzo) ([raw file](https://github.com/cockroachdb/cockroach/blob/36bc17e93f4f5e758df9581942342d76b515534f/pkg/cmd/roachtest/tests/tpcc.go#L463)):*
> ```Go
> 				// Now start running TPCC in the background.
> 				tpccBackgroundStepper.launch,
> 				waitForWorkloadToRampUp,
> ```

Could we add the above comment before the `waitForWorkloadToRampUp` step, since it's far from obvious.

**Review by renatolabs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90399)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @smg260, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/tpcc.go` line 463 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90399#-NFGUiMtCD098l1HDXQC:-NFKozZg-ByiC-MRxxjM:bl3eyin) ([raw file](https://github.com/cockroachdb/cockroach/blob/047744073aee36f7cdf5fe20dae2b0d9c35522b8/pkg/cmd/roachtest/tests/tpcc.go#L463)):*
> It's not so much the ramp up of the foreground traffic, because I am almost certain that doesn't need 5 minutes

It does take that amount of time because `workload` won't start all workers immediately if a ramp argument is passed:

https://github.com/cockroachdb/cockroach/blob/f64c283ac3a2987b0e6a3c41b13c1db059b78706/pkg/workload/cli/run.go#L483-L493
___
*[`pkg/cmd/roachtest/tests/tpcc.go` line 463 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90399#-NFKf8gD7mARKLpKCikf:-NFKpRHI0CwAU6BMRUfA:by3qpfw) ([raw file](https://github.com/cockroachdb/cockroach/blob/36bc17e93f4f5e758df9581942342d76b515534f/pkg/cmd/roachtest/tests/tpcc.go#L463)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Could we add the above comment before the `waitForWorkloadToRampUp` step, since it's far from obvious.
</blockquote></details>

Fair, comment added.

**Comment by renatolabs** [comment]
bors r=srosenberg

TFTR!

**Review by srosenberg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90399)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, and @smg260)

___
*[`pkg/cmd/roachtest/tests/tpcc.go` line 463 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90399#-NFGUiMtCD098l1HDXQC:-NFKrg4k01kuh-lwrb3z:b7dmlkd) ([raw file](https://github.com/cockroachdb/cockroach/blob/047744073aee36f7cdf5fe20dae2b0d9c35522b8/pkg/cmd/roachtest/tests/tpcc.go#L463)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

> It's not so much the ramp up of the foreground traffic, because I am almost certain that doesn't need 5 minutes

It does take that amount of time because `workload` won't start all workers immediately if a ramp argument is passed:

https://github.com/cockroachdb/cockroach/blob/f64c283ac3a2987b0e6a3c41b13c1db059b78706/pkg/workload/cli/run.go#L483-L493
</blockquote></details>

I meant that we don't necessarily have to wait 5 minutes to generate a full load. Certainly, `time.Sleep(time.Duration(i) * rampPerWorker)` will impose a proportional delay. However, we could a) increase the number of workers, b) run without wait times. In any case, reducing the wait of 5-minutes doesn't seem that material in the grand scheme of things.

**Pull request merged**
