### PR TITLE
sql: clarify error message when subtracting NaN from pg_lsn

### LINKED ISSUE #115136: sql: clarify text in pg_lsn error message
The following error message differs between postgres and crdb:

```
SELECT '0/16AE7F7'::pg_lsn - 'NaN'::numeric; 
-- postgres: ERROR:  cannot subtract NaN to pg_lsn
-- crdb: ERROR:  cannot add NaN to pg_lsn
```

Found in pg_regress pg_lsn

Jira issue: CRDB-33907

### PR DESCRIPTION
**Pull request by da-ket**
Release note: None
Fixes: #115136

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
Thanks for the contribution, @da-ket!

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124711#-:-NzFNLwaAFZYjxyCJJbs:bo6q87n)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @da-ket and @rharding6373)

___
*[`pkg/sql/sem/eval/binary_op.go` line 1569 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124711#-NzFNds47zuoLnHDKpBD:-NzFNds54RCLohvXjxEn:b31i6d7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d76b8cecd78f880419c283b8f78d81c40589e7/pkg/sql/sem/eval/binary_op.go#L1569)):*
> ```Go
> // namedLSNMathOp contains an LSN math operation and its name to clarify
> // error messages (GH issue #115136).
> type namedLSNMathOp struct {
> ```

Seems excessive to create a new struct just for one error message. I think it would be better to add a check where the error message is constructed and adjust the message there based on the operator. This will also allow you to easily say "subtract ... from" instead of "subtract ... to".
___
*[`pkg/sql/logictest/testdata/logic_test/pg_lsn` line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124711#-NzFO2Qn5bp2PWL67FML:-NzFO2Qn5bp2PWL67FMM:b9mnqxq) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d76b8cecd78f880419c283b8f78d81c40589e7/pkg/sql/logictest/testdata/logic_test/pg_lsn#L35)):*
> ```
> SELECT '0/0'::pg_lsn + 'NaN'
> 
> statement error cannot subtract NaN to pg_lsn
> ```

This should say "cannot subtract NaN from pg_lsn"

**Review by da-ket — COMMENTED** [review]
Thanks for the review, @rytaft !

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124711#-:-NzSZgZM6rgYcvAz6Dg5:bdiilz3)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rharding6373 and @rytaft)

___
*[`pkg/sql/sem/eval/binary_op.go` line 1569 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124711#-NzFNds47zuoLnHDKpBD:-NzSTpD91gc5vzsG1GbS:b-hkjcvp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d76b8cecd78f880419c283b8f78d81c40589e7/pkg/sql/sem/eval/binary_op.go#L1569)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Seems excessive to create a new struct just for one error message. I think it would be better to add a check where the error message is constructed and adjust the message there based on the operator. This will also allow you to easily say "subtract ... from" instead of "subtract ... to".
</blockquote></details>

I agree. I created two global variables, `lsnMathAdd` and `lsnMathSub`, to store function values and compare them in order to identify which operator is passed. I think comparing the addresses of operators through the `reflect` package might work, but I don't use it since it relies on the implementation of Golang rather than its specification.
___
*[`pkg/sql/logictest/testdata/logic_test/pg_lsn` line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124711#-NzFO2Qn5bp2PWL67FML:-NzSZc-196M20pt9M386:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d76b8cecd78f880419c283b8f78d81c40589e7/pkg/sql/logictest/testdata/logic_test/pg_lsn#L35)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This should say "cannot subtract NaN from pg_lsn"
</blockquote></details>

Done.

**Comment by mgartner** [comment]
*[`pkg/sql/sem/eval/binary_op.go` line 1569 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124711#-NzFNds47zuoLnHDKpBD:-NzTS1UO-WxAm5hpSlbx:beyksz8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d76b8cecd78f880419c283b8f78d81c40589e7/pkg/sql/sem/eval/binary_op.go#L1569)):*
<details><summary><i>Previously, da-ket (daket) wrote…</i></summary><blockquote>

I agree. I created two global variables, `lsnMathAdd` and `lsnMathSub`, to store function values and compare them in order to identify which operator is passed. I think comparing the addresses of operators through the `reflect` package might work, but I don't use it since it relies on the implementation of Golang rather than its specification.
</blockquote></details>

An alternative that avoid the pointers-to-functions indirection is to pass a `subtraction bool` parameter.

**Review by da-ket — COMMENTED** [review]
Thanks for the comment @mgartner ! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124711#-:-NzWZoMz3Ys1RXXVy7Cf:b-76croa)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[`pkg/sql/sem/eval/binary_op.go` line 1569 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124711#-NzFNds47zuoLnHDKpBD:-NzWZYGe-k-bSKRD_9Mg:b-q4kr5s) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6d76b8cecd78f880419c283b8f78d81c40589e7/pkg/sql/sem/eval/binary_op.go#L1569)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

An alternative that avoid the pointers-to-functions indirection is to pass a `subtraction bool` parameter.
</blockquote></details>

I agree that this is the simplest and most straightforward method. I have updated the pull request.

**Review by rytaft — APPROVED** [review]
:lgtm: Thanks for the contribution, @da-ket and sorry for the delay!

bors r+

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124711#-:-O-6eBaV57Bx5SNVuYea:b8trl1v)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @da-ket)

**Pull request merged**
