### PR TITLE
sql: remove redundant TableReaderSpan

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit removes the redundant `TableReaderSpan` protobuf message in
favor of using `roachpb.Span`s directly in the spec. This simplifies
some things. One notable change is that we no longer need to hold on to
`Spans` slice in the `TableReaderSpec` because we're using the passed-in
spans slices directly (rather having to copy as we used to).

Release note: None

### CODE REVIEW

**Review by cucaroach — APPROVED** [review]
Seems pretty straightforward and a nice cleanup, was there a reason for this TableReaderSpan abstraction that might cause us to bring it back in the future?   Why didn't we do the same to the BackfillerSpec?

> Reviewed 18 of 27 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71904#-:-Mn3OC7XDAv30Fj1-cW3:bd6v085)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Review by yuzefovich — COMMENTED** [review]
> was there a reason for this TableReaderSpan abstraction that might cause us to bring it back in the future?

My guess is that back in 2016 when the DistSQL framework was just being introduced, it was not clear how we would specify to the table readers what key spans to read, an implementation was picked, and it worked out ok. Over time we started using `roachpb.Span`s everywhere, so I doubt we will move away for the spans any time soon.

Maybe @raduberinde could share more historical anecdotes about it.

> Why didn't we do the same to the BackfillerSpec?

Not sure I understand your question - this PR does update the BackfillerSpec to use `roachpb.Span`s directly. Am I missing something?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71904#-:-Mn3SLEE3TAy0i_NQOCP:b-u3qqvn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Review by cucaroach — APPROVED** [review]
Nevermind, I was confused.   :LGTM:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71904#-:-Mn3VyoAEu4nfrwNQuec:b-d8qngm)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Review by RaduBerinde — COMMENTED** [review]
The original intention was to avoid baking in details of how we encode datums into keys into the DistSQL interface. But the original simple implementation of just using Span has worked well enough.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71904#-:-Mn3fUFS9c99SZHpXo9X:b-8ulsks)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Pull request merged**
