### PR TITLE
roachtest: trace slow query in election test

### PR DESCRIPTION
**Pull request by tbg**
See
https://github.com/cockroachdb/cockroach/issues/30613#issuecomment-425700921.

Touches #30613

Release note: None

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm:

Though I think I'm getting close to understanding the `breaker open` problem on #29149. See https://github.com/cockroachdb/cockroach/issues/29149#issuecomment-425909594. Are you adding this for a different reason?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30817#-:-LNjqiJ35HaVktp0MjW0:b-kl64oq)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by tschottdorf** [comment]
Yep, this is specifically for the newest failure mode:

> The test failed on master:
	test.go:503,election.go:72: expected query to succeed in less than 15s, took 1m9.906603757s

**Comment by tschottdorf** [comment]
bors r=petermattis

**Comment by benesch** [comment]
Bors is stuck.

bors r-

**Pull request merged**
