### PR TITLE
sql/parser: permit untyped string constant coercion to DBools

### PR DESCRIPTION
**Pull request by nvb**
Postgres supports a large number of type aliases for booleans:
https://www.postgresql.org/docs/current/static/datatype-boolean.html
These include booleans within quotes.

Previously we only allowed the values `true` and `false` to be used for
boolean types. We now take advantage of our untyped constant literal
system for booleans by adding `TypeBool` as an available type for
string literals.

This means that the following create table statement will now work:
```
CREATE TABLE t (b BOOL DEFAULT 'f');
```

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13685)

### CODE REVIEW

**Comment by knz** [comment]
LGTM but since we aim to support all the literals that pg support, we should have a test for each of them. I don't see any existing test that does this.

---

Reviewed 6 of 6 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13685#-:-KdWyDi9Hm2bTqGnFDYy:b8trrba)*

**Comment by nvanbenschoten** [comment]
I don't think that we do try to support all the literals that pg supports for untyped string constant coercion or explicit type casting. Notably, we do not support `'y'`, `'yes'`, or `'on'`, or their negative counterparts. Instead, we simply pass the string through [`strconv.ParseBool`](https://golang.org/src/strconv/atob.go?s=351:391#L1). @petermattis's [TODO](https://github.com/cockroachdb/cockroach/blob/3122cae8797865826957c423f2a1f0cc67e60f8b/pkg/sql/parser/datum.go#L168) implies that we were only attempting to support the SQL spec, and it looks like those extra literals are PG-extensions. Do you think it's worth supporting them?

**Comment by knz** [comment]
no, not yet. Let's test (and document!) just what we support for now, and see if someone comes to us asking for more.

**Comment by knz** [comment]
(document = please add a doc issue with a link to here to request documenting the valid string->bool conversions.)

**Comment by petermattis** [comment]
I don't recall intentionally trying to restrict ourselves to the SQL standard. That TODO indicates we're clearly not doing that currently.

**Comment by nvanbenschoten** [comment]
@knz Got it, I'll add tests for each other the current boolean conversions and an issue in docs.

@petermattis, I didn't mean the TODO implied that we were restricting ourselves to the SQL standard. Rather, I thought it implied that our goal (at the time anyway) was to support the SQL standard at a minimum, as opposed to the full pg-extensions at a minimum.

**Comment by nvanbenschoten** [comment]
Went to add the tests but found that we actually did already have them in [eval_test.go](https://github.com/cockroachdb/cockroach/blob/f89ad5b009c068cdb81e798639e7d889377b1729/pkg/sql/parser/eval_test.go#L500).

Opened https://github.com/cockroachdb/docs/issues/1108 in docs.

**Pull request merged**
