### PR TITLE
roachprod: Add support for Microsoft Azure cloud

### PR DESCRIPTION
**Pull request by bobvawter**
This commit adds support for geodistributed roachprod clusters running on Azure
VMs. Refer to the azure/doc.go package comments for additional information
about how the deployment operates.

Release note: None

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
For AWS and GCP we shell out to the `aws` and `gcloud` tools rather than embedding their client APIs. Is there a reason you didn't take that approach here? My understanding is that we've found the command line tools to be easier to use and their APIs more stable than the client libraries. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-:-LpYU91E3FPOO3Op69J6:bz8sgmd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @kenliu, and @petermattis)

**Review by bobvawter — COMMENTED** [review]
Following up from in-person discussion:  I went with the direct API use because the tooling interface for the `az` CLI is JSON blobs, I can program using `Future`s to easily perform long-running tasks in parallel, and MS is really good about providing backwards-compatibility for API surfaces.

@ajwerner, do you have cycles to take point on this review?  If not, no worries.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-:-LpZu4dO9rouPoSvGSRD:bszbi7m)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @kenliu)

**Review by ajwerner — COMMENTED** [review]
I can get to it later tomorrow. I'm close to closing out release blocker PRs today. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-:-Lp_6plQ1ad1SJLWtRk_:b-eycd8z)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @kenliu)

**Review by ajwerner — COMMENTED** [review]
Made a first pass, mostly minor stuff. I am worried about the cross cluster connectivity because migrating might be annoying if we change it later. I'm less worried about the availability zone stuff in this first iteration. 

> Reviewed 12 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-:-Lpd3y2xBVvp1pcbjpzY:bjl479b)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter and @kenliu)

___
*[pkg/cmd/roachprod/install/cockroach.go, line 207 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-LpclEBx4CDGh1OAqeK4:-LpclEBx4CDGh1OAqeK5:b-bv5aou) ([raw file](https://github.com/cockroachdb/cockroach/blob/a80f0dd5f7c692ed2ddd682e004ec5247b0327f4/pkg/cmd/roachprod/install/cockroach.go#L207)):*
> ```Go
> 			args = append(args, fmt.Sprintf("--advertise-host=%s", c.host(i+1)))
> 		} else {
> 			args = append(args, "--advertise-host=$(hostname -I)")
> ```

`-I` is going to return all of the IPs right? is that intentional/does that work if there were more than 1? Are we just getting lucky that there's only one?
___
*[pkg/cmd/roachprod/vm/azure/azure.go, line 145 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-Lpd2JGS8ULqvDmrOqCS:-Lpd2JGS8ULqvDmrOqCT:b-42o9g9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a80f0dd5f7c692ed2ddd682e004ec5247b0327f4/pkg/cmd/roachprod/vm/azure/azure.go#L145)):*
> ```Go
> 
> 			// Create the VNet and the subset
> 			vnet, subnet, err := p.createVNet(ctx, group, locIdx+1)
> ```

If I read the vnet configuration correctly, we're going to create new vnets and peerings for every roachprod cluster in azure. IIUC this means that different azure roachprod clusters will not be able to talk to eachother on the internal IPs. Is there a way we can have a static global set of roachprod vnets and peerings and then use those for all roachprod clusters? That's what we do on AWS and it effectively "just works" on GCP. It can be seriously handy when you want to say spin up a new cluster for load generation against an existing roachprod cockroach deployment. 
___
*[pkg/cmd/roachprod/vm/azure/azure.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-LpcpcFkC-lveOagHWQY:-LpcpcFkC-lveOagHWQZ:bju15xc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a80f0dd5f7c692ed2ddd682e004ec5247b0327f4/pkg/cmd/roachprod/vm/azure/azure.go#L171)):*
> ```Go
> // Delete implements the vm.Provider interface.
> func (p *Provider) Delete(vms vm.List) error {
> 	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Minute)
> ```

Can we const this 10 minute timeout? Might be worth eventually moving it to a flag but no need to do that now
___
*[pkg/cmd/roachprod/vm/azure/azure.go, line 172 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-LpcpjObD_kVghZe7a7z:-LpcpjObD_kVghZe7a8-:biflahm) ([raw file](https://github.com/cockroachdb/cockroach/blob/a80f0dd5f7c692ed2ddd682e004ec5247b0327f4/pkg/cmd/roachprod/vm/azure/azure.go#L172)):*
> ```Go
> func (p *Provider) Delete(vms vm.List) error {
> 	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Minute)
> 	defer cancel()
> ```

How come you assign and defer cancel this one but not the one above? Both seem fine just looking for some consistency. 
___
*[pkg/cmd/roachprod/vm/azure/azure.go, line 378 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-Lpd0Q4X5mAipHltNzsm:-Lpd0Q4X5mAipHltNzsn:b-p34f9e) ([raw file](https://github.com/cockroachdb/cockroach/blob/a80f0dd5f7c692ed2ddd682e004ec5247b0327f4/pkg/cmd/roachprod/vm/azure/azure.go#L378)):*
> ```Go
> 			MachineType: string(found.HardwareProfile.VMSize),
> 			// We add a fake availability-zone suffix since other roachprod
> 			// code assumes particular formats.
> ```

nit: can you add to this comment what `*found.Location` looks like so it's clearer what it will look like with a `z` at the end
___
*[pkg/cmd/roachprod/vm/azure/azure.go, line 450 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-Lpd1Fxn-kVW7poEvBRs:-Lpd1FxoBFeRIebqeAGI:b8hz2lq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a80f0dd5f7c692ed2ddd682e004ec5247b0327f4/pkg/cmd/roachprod/vm/azure/azure.go#L450)):*
> ```Go
> 		}
> 		if opts.SSDOpts.NoExt4Barrier {
> 			cmds = append(cmds, "mount -o remount,nobarrier /mnt/data")
> ```

It seems like we generally also mount with `discard,defaults` in the AWS vms. I think that discard thing is supposed to be good for SSDs.
___
*[pkg/cmd/roachprod/vm/azure/azure.go, line 532 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-Lpd1o2E82WhAmzJru0k:-Lpd1o2E82WhAmzJru0l:b9u5xj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a80f0dd5f7c692ed2ddd682e004ec5247b0327f4/pkg/cmd/roachprod/vm/azure/azure.go#L532)):*
> ```Go
> 				ComputerName:  to.StringPtr(name),
> 				AdminUsername: to.StringPtr(remoteUser),
> 				CustomData:    to.StringPtr(base64.StdEncoding.EncodeToString([]byte(cloudConfig))),
> ```

Is this base64 encoded yaml inside what ultimately gets encoded as json? fun!
___
*[pkg/cmd/roachprod/vm/azure/doc.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-Lpd3Xu85Lsxq7bt_Ny5:-Lpd3Xu85Lsxq7bt_Ny6:blxhl9s) ([raw file](https://github.com/cockroachdb/cockroach/blob/a80f0dd5f7c692ed2ddd682e004ec5247b0327f4/pkg/cmd/roachprod/vm/azure/doc.go#L23)):*
> ```Go
> // "Resource Group", which lives in a particular "Location", such as
> // "eastus", and which are roughly equivalent to other cloud provider's
> // regions.  Individual availability zones don't surface directly unless
> ```

Is this implying that we currently don't support creating clusters which have nodes in a location which are guaranteed to be in different availability zones? Can you put a TODO that describes that limitation and what it would take to lift it?
___
*[pkg/cmd/roachprod/vm/azure/doc.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-Lpd3GPF6_VJIog6OxfY:-Lpd3FHh8AksGzjGFYPi:ba1jx90) ([raw file](https://github.com/cockroachdb/cockroach/blob/a80f0dd5f7c692ed2ddd682e004ec5247b0327f4/pkg/cmd/roachprod/vm/azure/doc.go#L31)):*
> ```Go
> //
> //  | Resource Group (one per Location / Region)
> //  |   VNet          (10.<offset>/16)
> ```

Commented on the `Create` code because I got there first but I wonder if we should iterate on this setup to share a VNet.

**Review by bobvawter — COMMENTED** [review]
PTAL. Comments addressed.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-:-Lq2fkO80NBUqhxXlt7U:bigep29)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @kenliu)

___
*[pkg/cmd/roachprod/install/cockroach.go, line 207 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-LpclEBx4CDGh1OAqeK4:-LpiksGc7eYLBVo3FPWn:b-e0gzi2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a80f0dd5f7c692ed2ddd682e004ec5247b0327f4/pkg/cmd/roachprod/install/cockroach.go#L207)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

`-I` is going to return all of the IPs right? is that intentional/does that work if there were more than 1? Are we just getting lucky that there's only one?
</blockquote></details>

You're right, this will print all of the addresses.  We've been lucky in that the network configuration is trivial.  I've amended this with an `awk` pipe to grab the first IP.
___
*[pkg/cmd/roachprod/vm/azure/azure.go, line 145 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-Lpd2JGS8ULqvDmrOqCS:-Lq2e46iBTrv85_Craw8:bkhn4s4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a80f0dd5f7c692ed2ddd682e004ec5247b0327f4/pkg/cmd/roachprod/vm/azure/azure.go#L145)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

If I read the vnet configuration correctly, we're going to create new vnets and peerings for every roachprod cluster in azure. IIUC this means that different azure roachprod clusters will not be able to talk to eachother on the internal IPs. Is there a way we can have a static global set of roachprod vnets and peerings and then use those for all roachprod clusters? That's what we do on AWS and it effectively "just works" on GCP. It can be seriously handy when you want to say spin up a new cluster for load generation against an existing roachprod cockroach deployment. 
</blockquote></details>

This is a really good suggestion.  I have changed the deployment so that there's only ever one VNet and Subnet created per region.  Clusters can now communicate arbitrarily between themselves.  If isolation is desired, the `--azure-vnet-name` flag can be used to override the "common" vnet.
___
*[pkg/cmd/roachprod/vm/azure/azure.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-LpcpcFkC-lveOagHWQY:-LpjAbbb03-nuRBAsEXP:b-byjcem) ([raw file](https://github.com/cockroachdb/cockroach/blob/a80f0dd5f7c692ed2ddd682e004ec5247b0327f4/pkg/cmd/roachprod/vm/azure/azure.go#L171)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Can we const this 10 minute timeout? Might be worth eventually moving it to a flag but no need to do that now
</blockquote></details>

Moved it to a `providerOpts` flag.
___
*[pkg/cmd/roachprod/vm/azure/azure.go, line 172 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-LpcpjObD_kVghZe7a7z:-LpiljIn99gUO0hQZ8T8:bn5bi35) ([raw file](https://github.com/cockroachdb/cockroach/blob/a80f0dd5f7c692ed2ddd682e004ec5247b0327f4/pkg/cmd/roachprod/vm/azure/azure.go#L172)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

How come you assign and defer cancel this one but not the one above? Both seem fine just looking for some consistency. 
</blockquote></details>

Missed the one.  Fixed.
___
*[pkg/cmd/roachprod/vm/azure/azure.go, line 378 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-Lpd0Q4X5mAipHltNzsm:-LpimCW_EyVEzZuXN0il:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a80f0dd5f7c692ed2ddd682e004ec5247b0327f4/pkg/cmd/roachprod/vm/azure/azure.go#L378)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: can you add to this comment what `*found.Location` looks like so it's clearer what it will look like with a `z` at the end
</blockquote></details>

Done.
___
*[pkg/cmd/roachprod/vm/azure/azure.go, line 450 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-Lpd1Fxn-kVW7poEvBRs:-LpimJKA03QiFX8h_0nf:bgi4rfi) ([raw file](https://github.com/cockroachdb/cockroach/blob/a80f0dd5f7c692ed2ddd682e004ec5247b0327f4/pkg/cmd/roachprod/vm/azure/azure.go#L450)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

It seems like we generally also mount with `discard,defaults` in the AWS vms. I think that discard thing is supposed to be good for SSDs.
</blockquote></details>

Added `discard`, since `defaults` would already be present from the OS image.
___
*[pkg/cmd/roachprod/vm/azure/doc.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-Lpd3Xu85Lsxq7bt_Ny5:-Lpj7apN6z3ueQcTBPsy:b-7yd1q4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a80f0dd5f7c692ed2ddd682e004ec5247b0327f4/pkg/cmd/roachprod/vm/azure/doc.go#L23)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Is this implying that we currently don't support creating clusters which have nodes in a location which are guaranteed to be in different availability zones? Can you put a TODO that describes that limitation and what it would take to lift it?
</blockquote></details>

Added a TODO.
___
*[pkg/cmd/roachprod/vm/azure/doc.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-Lpd3GPF6_VJIog6OxfY:-Lpj9p1R21yHT5HwUVn-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a80f0dd5f7c692ed2ddd682e004ec5247b0327f4/pkg/cmd/roachprod/vm/azure/doc.go#L31)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Commented on the `Create` code because I got there first but I wonder if we should iterate on this setup to share a VNet. 
</blockquote></details>

Done.

**Review by ajwerner — COMMENTED** [review]
Mostly nits with a couple of questions. Seems like you also need a rebase. 

> Reviewed 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-:-Lq67raK4_IvNFVOb-72:b-jaeib3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bobvawter and @kenliu)

___
*[pkg/cmd/roachprod/vm/azure/azure.go, line 153 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-Lq66MEw-vZtkugF1DvR:-Lq66MEx1kjXo2-VC-Os:bf8hl05) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9b1887050359ebdd5a7380d15c2c0ac773a869b/pkg/cmd/roachprod/vm/azure/azure.go#L153)):*
> ```Go
> 
> 			p.mu.Lock()
> 			subnet := p.mu.subnets[location]
> ```

nit: consider checking the existence so we get a better error than ultimately an empty subnet not existing. 
___
*[pkg/cmd/roachprod/vm/azure/azure.go, line 627 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-Lq63uVB8ZilTfl_YKsX:-Lq63uVB8ZilTfl_YKsY:bp0h16l) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9b1887050359ebdd5a7380d15c2c0ac773a869b/pkg/cmd/roachprod/vm/azure/azure.go#L627)):*
> ```Go
> 
> // createVNets will create a VNet in each of the given locations to be
> // shared across roachprod clusters.  Thus, all roachprod clusters will
> ```

nit: double space.
___
*[pkg/cmd/roachprod/vm/azure/azure.go, line 682 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-Lq64LEzAXi7PFkusBb4:-Lq64LF--8S7aHEzbExL:b-szafvz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9b1887050359ebdd5a7380d15c2c0ac773a869b/pkg/cmd/roachprod/vm/azure/azure.go#L682)):*
> ```Go
> 
> 	// First, find or create a resource group for roachprod to create
> 	// the VNets in.  We need one per location.
> ```

nit: double space
___
*[pkg/cmd/roachprod/vm/azure/azure.go, line 700 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-Lq64a7Y91L5xh9gXTw4:-Lq64a7Y91L5xh9gXTw5:b39zn15) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9b1887050359ebdd5a7380d15c2c0ac773a869b/pkg/cmd/roachprod/vm/azure/azure.go#L700)):*
> ```Go
> 	// to allocate new subnets at the same time. If this happens, it can
> 	// be easily fixed by deleting one of resource groups and re-running
> 	// roachprod to select a new network prefix.
> ```

Can you make the error which you'd expect to be caused by this race somewhat clearer by having the message indicate that the command should be retried? I imagine that's the error from the `setVNetSubnetPrefix` call below. 

Just to confirm my understanding, this will only happen the first time a location is used by roachprod, right?
___
*[pkg/cmd/roachprod/vm/azure/azure.go, line 743 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-Lq67el02nW5IpVOqAN4:-Lq67el02nW5IpVOqAN5:ba0mbk3) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9b1887050359ebdd5a7380d15c2c0ac773a869b/pkg/cmd/roachprod/vm/azure/azure.go#L743)):*
> ```Go
> 
> 	// Set up VNet peering.
> 	return ret, p.createVNetPeerings(ctx, vnets)
> ```

Do we need to create peerings every time we create a cluster even if we didn't create any new vnets? 
___
*[pkg/cmd/roachprod/vm/azure/azure.go, line 800 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-Lq67X8B9u9SCP1S29_D:-Lq67X8B9u9SCP1S29_E:b-8bfk7o) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9b1887050359ebdd5a7380d15c2c0ac773a869b/pkg/cmd/roachprod/vm/azure/azure.go#L800)):*
> ```Go
> }
> 
> // createVNetPeerings creates a full compliment of
> ```

Incomplete comment.
___
*[pkg/cmd/roachprod/vm/azure/azure_test.go, line 13 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-Lq65aUQA1LhXeIUMAnY:-Lq65aUQA1LhXeIUMAnZ:b82hbz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9b1887050359ebdd5a7380d15c2c0ac773a869b/pkg/cmd/roachprod/vm/azure/azure_test.go#L13)):*
> ```Go
> func Test(t *testing.T) {
> 	a := assert.New(t)
> 	ctx, _ := context.WithTimeout(context.Background(), 10*time.Minute)
> ```

Is this going to work in CI?
___
*[pkg/cmd/roachprod/vm/azure/doc.go, line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-Lq65izP-JQf2qF2KZ0v:-Lq65izQ4DK5CMik0vMi:b2t0qq9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9b1887050359ebdd5a7380d15c2c0ac773a869b/pkg/cmd/roachprod/vm/azure/doc.go#L45)):*
> ```Go
> //
> // Roachprod creates a "common" resource group, VNet, and Subnet for
> // each location that clusters may be deployed into.  Each NIC that is
> ```

nit: double spaced here and on the next line.

**Review by bobvawter — COMMENTED** [review]
Fixed the nits.  Two spaces after a period... for life!

The conflicting subnet condition would only be a problem if two users are running roachprod simultaneously against two different, previously-unused locations.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-:-Lq8BpAHEuG88NCMkakm:b-fj1cjl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @kenliu)

___
*[pkg/cmd/roachprod/vm/azure/azure.go, line 153 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-Lq66MEw-vZtkugF1DvR:-Lq6wYKe4aUGaXJ_5Whg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9b1887050359ebdd5a7380d15c2c0ac773a869b/pkg/cmd/roachprod/vm/azure/azure.go#L153)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: consider checking the existence so we get a better error than ultimately an empty subnet not existing. 
</blockquote></details>

Done.
___
*[pkg/cmd/roachprod/vm/azure/azure.go, line 627 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-Lq63uVB8ZilTfl_YKsX:-Lq89gWvBpT_GrEqG4_6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9b1887050359ebdd5a7380d15c2c0ac773a869b/pkg/cmd/roachprod/vm/azure/azure.go#L627)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: double space.
</blockquote></details>

Done.
___
*[pkg/cmd/roachprod/vm/azure/azure.go, line 682 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-Lq64LEzAXi7PFkusBb4:-Lq89hJE4njP-gO2YB6N:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9b1887050359ebdd5a7380d15c2c0ac773a869b/pkg/cmd/roachprod/vm/azure/azure.go#L682)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: double space
</blockquote></details>

Done.
___
*[pkg/cmd/roachprod/vm/azure/azure.go, line 700 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-Lq64a7Y91L5xh9gXTw4:-Lq89jfbDuftxJNyxsVJ:bwc3q0j) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9b1887050359ebdd5a7380d15c2c0ac773a869b/pkg/cmd/roachprod/vm/azure/azure.go#L700)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Can you make the error which you'd expect to be caused by this race somewhat clearer by having the message indicate that the command should be retried? I imagine that's the error from the `setVNetSubnetPrefix` call below. 

Just to confirm my understanding, this will only happen the first time a location is used by roachprod, right?
</blockquote></details>

This is only ever an issue the first time any given location would be used by roachprod.
___
*[pkg/cmd/roachprod/vm/azure/azure.go, line 743 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-Lq67el02nW5IpVOqAN4:-Lq89sxkE3kEZyjjXQ76:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9b1887050359ebdd5a7380d15c2c0ac773a869b/pkg/cmd/roachprod/vm/azure/azure.go#L743)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Do we need to create peerings every time we create a cluster even if we didn't create any new vnets? 
</blockquote></details>

Fixed.
___
*[pkg/cmd/roachprod/vm/azure/azure.go, line 800 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-Lq67X8B9u9SCP1S29_D:-Lq8AYoS3d5zOTSScjzo:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9b1887050359ebdd5a7380d15c2c0ac773a869b/pkg/cmd/roachprod/vm/azure/azure.go#L800)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Incomplete comment.
</blockquote></details>

Fixed.
___
*[pkg/cmd/roachprod/vm/azure/azure_test.go, line 13 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-Lq65aUQA1LhXeIUMAnY:-Lq8AZvC56dziJnz5rKk:bbzoq3w) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9b1887050359ebdd5a7380d15c2c0ac773a869b/pkg/cmd/roachprod/vm/azure/azure_test.go#L13)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Is this going to work in CI?
</blockquote></details>

This file shouldn't have been checked in; removed.
___
*[pkg/cmd/roachprod/vm/azure/doc.go, line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-Lq65izP-JQf2qF2KZ0v:-Lq8AbtM2yj6L99hovl7:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9b1887050359ebdd5a7380d15c2c0ac773a869b/pkg/cmd/roachprod/vm/azure/doc.go#L45)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: double spaced here and on the next line.
</blockquote></details>

Fixed.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41031#-:-Lq8WwGB-f_sLBaJ-sW8:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @kenliu)

**Comment by kenliu** [comment]
talked to @pbardea about rebasing this branch to see if that gets past the test flake

**Comment by bobvawter** [comment]
bors ping

**Pull request merged**
