### PR TITLE
storage: Don't record stats for requests that lack a GatewayNodeID

### PR DESCRIPTION
**Pull request by a-robinson**
Based on comment on #13797

@tamird

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13825)

### CODE REVIEW

**Comment by a-robinson** [comment]
I should add that in my local testing, I only saw such requests from `(*pendingLeaseRequest).requestLeaseAsync`, but it looks like they're possible from another couple internal places.

**Comment by tamird** [comment]
absolutely science dog on this, but it seems unfortunate that this machinery needs to be aware of "weird" callers rather than being installed in the remote-only path.

**Comment by a-robinson** [comment]
How's this as the simplest alternative?

**Comment by tamird** [comment]
Better, thanks.

**Pull request merged**
