### PR TITLE
execgen: permit customization of template path

### LINKED ISSUE #56982: execgen: make file i/o more "unix"-ey
**Describe the problem**

The UX around execgen i/o is a bit non-standard. Let's consider one example:

```
execgen -fmt=false pkg/cmd/colexec/hash_any_not_null_agg.eg.go
```

At first glance it may seem that it's taking the `hash_any_not_null_agg.eg.go` file as input, but in fact the file path is a positional argument tells `execgen` which specific `.eg.go` file to generate, which it then prints to stdout. For it's "input", the `execgen` program has a hardcoded list of `_tmpl.go` files relative to the repo root that it knows to read and use in order to generate the relevant `.eg.go` file.

**Expected behavior**
Lets consider how `optgen` behaves instead.
```
optgen -out pkg/sql/opt/operator.og.go ops pkg/sql/opt/ops/*.opt
```
It's a bit simpler to understand. The `-out` parameter specifies where the output file is to be placed. The `ops` argument tells optgen that it needs to generate operator definitions. The `pkg/sql/opt/ops/*.opt` arguments tell optgen where to look to find all relevant "input" files (the opt rules).

**Additional data / screenshots**
N/A

**Additional context**

The `execgen` UX has worked well for us thus far, but is exceedingly difficult to work with now that we're trying bazel in earnest (#55687). Specifically, bazel wants to auto-generate code within its sandbox where the template files are not necessarily placed in the same path as it does in the crdb repo itself. Because the template paths are hard-coded, it takes a few hacks to get it working just right with Bazel. Compare the `optgen` bazel gen rule with the `execgen` one:

https://github.com/cockroachdb/cockroach/blob/9806c1c0db4390e65e60e41fbe35405afefc88ff/pkg/sql/opt/BUILD.bazel#L67-L76

https://github.com/cockroachdb/cockroach/blob/9806c1c0db4390e65e60e41fbe35405afefc88ff/pkg/sql/colexec/COLEXEC.bzl#L1-L43

Right now the bazel targets for `pkg/sql/colexec` don't work for running tests (they do for building the test binaries, confusingly), as the sandbox places the template files in a location other than what `execgen` has been taught to expect.

```
$ bazel test @cockroach//pkg/sql/colexec:colexec_test
...
INFO: From Generating pkg/cmd/colexec/and_or_projection.eg.go:
ERROR: open pkg/sql/colexec/and_or_projection_tmpl.go: no such file or directory
```

If the UX looked something similar to the following:
```
execgen hash_sum_agg  -t <relevant template files>
```

Where it would print to stdout the intended contents of `pkg/sql/colexec/colexecagg/hash_sum_agg.eg.go`, life would be much easier. Specifically what I'm looking for is for the arguments fully specify where exactly to look for all the "inputs", instead of it internally hardcoding those paths. It'd be more “unix”-ey that way, I think. Specifically for bazel, we’d then be able to declare the full set of template files as data dependencies, while still allowing bazel to place those files in any arbitrary path within the sandbox.

To add more words to my word soup above, another reason the status quo feels gross in bazel is because the template files in one package (`colexec`) can be used to generate `eg.go` files in another (`colconv` for e.g.). By default bazel wants to treat `colexec` as a dependency for `colconv`, but in our code it’s the other way around. For now we've settled for not generating the `eg.go~ files in `colconv`, but we'll want to remove this stopgap soon. 

(Aside: that’s yet another thing that's slightly better in optgen. The rules for each package are wholly contained within that package itself or in children packages.)

---

cc-ing @jordanlewis for triage/routing.

### PR DESCRIPTION
**Pull request by jordanlewis**
Closes #56982

This commit adds a new argument to execgen, -template, which allows
customization of the file path of the input template for a given output
file.

Here's an example of how to run execgen with cutomized paths:

```
execgen -template path/to/template_tmpl.go path/to/eventual/generated/code.eg.go > path/to/wherever/you/want/to/write/the/file.eg.o
```

The second argument is important because it is used as an argument to
`goimports`, which needs to the actual, eventual path that the generated
code will live at. Note that it doesn't actually need to *write* to that
filepath - just needs to know what the name will be, eventually.

Release note: None

### CODE REVIEW

**Comment by jordanlewis** [comment]
@irfansharif I don't necessarily need a review, but please LMK if the proposed change would fix the Bazel issue.

**Review by irfansharif — APPROVED** [review]
This works. Sorry for the delay, wanted to see what the bazel rules would change to.

```diff
diff --git i/pkg/sql/colexec/BUILD.bazel w/pkg/sql/colexec/BUILD.bazel
index ff48f4de4d..a39d8b0eea 100644
--- i/pkg/sql/colexec/BUILD.bazel
+++ w/pkg/sql/colexec/BUILD.bazel
@@ -52,6 +52,7 @@ go_library(
         "unordered_distinct.go",
         "utils.go",
         ":gen-exec",  # keep
+        ":gen-and-or-projection",  # keep
     ],
     importpath = "github.com/cockroachdb/cockroach/pkg/sql/colexec",
     visibility = ["//visibility:public"],
@@ -201,7 +202,6 @@ go_test(

 # Define a file group for all the .eg.go targets.
 targets = [
-    "and_or_projection.eg.go",
     "cast.eg.go",
     "const.eg.go",
     "default_cmp_expr.eg.go",
@@ -254,3 +254,15 @@ generate(
     targets = targets,
     templates = glob(["*_tmpl.go"]),
 )
+
+# XXX: Rule generation for and_or_projection.eg.go. We'll want one per eg.go
+# file; we'll write a helper method to make it look nicer.
+genrule(
+    name = "gen-and-or-projection",
+    srcs = ["and_or_projection_tmpl.go"],
+    outs = ["and_or_projection.eg.go"],
+    cmd = """
+      $(location //pkg/sql/colexec/execgen/cmd/execgen) -template $(location and_or_projection_tmpl.go) -fmt=false pkg/sql/colexec/and_or_projection.eg.go > $@
+      $(location //vendor/github.com/cockroachdb/gostdlib/x/tools/cmd/goimports) -w $@
+    """,
+    tools = ["//pkg/sql/colexec/execgen/cmd/execgen", "//vendor/github.com/cockroachdb/gostdlib/x/tools/cmd/goimports"],
+)
```

**Comment by jordanlewis** [comment]
Nice - that seems pretty close to the optgen one, so victory?

I'm happy to help out with creating the genrules if it's annoying, if you tell me how to do it.

bors r+

**Comment by irfansharif** [comment]
> I'm happy to help out with creating the genrules if it's annoying.

Not annoying at all, thanks for helping me out here Jordan. See https://github.com/cockroachdb/cockroach/pull/57075.

**Pull request merged**
