### PR TITLE
sql: Defer string conversion of AST until SHOW QUERIES/SESSIONS.

### LINKED ISSUE #16531: sql: allocation regression by `SHOW SESSIONS` commit
I've bisected a regression in the number of allocations on a decent SQL benchmark to the following commit:
f95a4702 - Add SHOW SESSIONS and SHOW QUERIES statements - Add node-local session registry - Make Session struct partially thread-safe (with mu sub-struct) - Add Sessions and LocalSessions RPC endpoints, called upon SHOW  {SESSIONS,QUERIES}

Peter doesn't like it when there's new allocations :P
The increase is large enough that I think some investigation is in order to see if we can reduce the allocs, or at least understand if they're really needed. I can help with the memory profiling tools.

```
make bench PKG=./pkg/sql BENCHES=KV/Scan1_SQL TESTFLAGS="-benchmem"
    5000	    252865 ns/op	   29566 B/op	     292 allocs/op
```

The previous commit, 79f65ab, had:
```
    5000	    243949 ns/op	   29229 B/op	     278 allocs/op
```

Note that at HEAD the number of allocs is even higher until I fix #16518.

### PR DESCRIPTION
**Pull request by itsbilal**
The conversion of an AST to string is expensive, memory-wise. This change defers it until `SHOW SESSIONS` or `SHOW QUERIES` is called, instead of doing it at the start of query execution and storing the resultant string.

Fixes #16531 .

Difference in memory allocations with the KV/Scan1_SQL microbenchmark:
Before:
```
 make bench PKG=./pkg/sql BENCHES=KV/Scan1_SQL TESTFLAGS="-benchmem"
    5000	    268001 ns/op	   35935 B/op	     402 allocs/op
```

After:
```
 make bench PKG=./pkg/sql BENCHES=KV/Scan1_SQL TESTFLAGS="-benchmem"
    5000	    265156 ns/op	   35531 B/op	     389 allocs/op
```

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/session.go, line 718 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16543#-Kmh1P66Bh-YF_wSUGaN:-Kmh1P67I6tN8NkqMK-m:b-dj1k7k) ([raw file](https://github.com/cockroachdb/cockroach/blob/5614de6e451f5b99515c1c9638214bfc26a9d0aa/pkg/sql/session.go#L718)):*
> ```Go
> 
> 	for query := range s.mu.ActiveQueries {
> 		sql := query.stmt.String()
> ```

Is it possible that `query.stmt` is being modified concurrently at this point? I'm not familiar with the locking and I have a lurking fear that `parser.Statement` isn't immutable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16543)*

**Comment by itsbilal** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/session.go, line 718 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16543#-Kmh1P66Bh-YF_wSUGaN:-Kmh6JGpuEVjMHYKMNgA:b-tqmgch) ([raw file](https://github.com/cockroachdb/cockroach/blob/5614de6e451f5b99515c1c9638214bfc26a9d0aa/pkg/sql/session.go#L718)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is it possible that `query.stmt` is being modified concurrently at this point? I'm not familiar with the locking and I have a lurking fear that `parser.Statement` isn't immutable.
</blockquote></details>

I took a look through many different types of `parser.Statement`s, and they all seemed immutable so I made the assumption that all `parser.Statement`s are.

`query` doesn't have a lock on it directly but all reads/mutations on it happen with a `session.mu` lock. So no, `query.stmt` shouldn't be changed concurrently. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16543)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/session.go, line 718 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16543#-Kmh1P66Bh-YF_wSUGaN:-KmhJVEdKEHqXCRi80eD:b-iwkj62) ([raw file](https://github.com/cockroachdb/cockroach/blob/5614de6e451f5b99515c1c9638214bfc26a9d0aa/pkg/sql/session.go#L718)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

I took a look through many different types of `parser.Statement`s, and they all seemed immutable so I made the assumption that all `parser.Statement`s are.

`query` doesn't have a lock on it directly but all reads/mutations on it happen with a `session.mu` lock. So no, `query.stmt` shouldn't be changed concurrently. 
</blockquote></details>

@knz and @jordanlewis would know more about `parser.Statement` than I do. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16543)*

**Comment by itsbilal** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/session.go, line 718 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16543#-Kmh1P66Bh-YF_wSUGaN:-KmhMyP9wZ0gbKpjNu1E:b-ia1jrw) ([raw file](https://github.com/cockroachdb/cockroach/blob/5614de6e451f5b99515c1c9638214bfc26a9d0aa/pkg/sql/session.go#L718)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

@knz and @jordanlewis would know more about `parser.Statement` than I do. 
</blockquote></details>

Jordan says it's immutable. Violating that invariant [has caused bugs before](https://github.com/cockroachdb/cockroach/pull/16434), so we should be able to rely on its immutability.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16543)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/session.go, line 718 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16543#-Kmh1P66Bh-YF_wSUGaN:-KmhSkZgexLKxw5cd5-Q:b-5gwryt) ([raw file](https://github.com/cockroachdb/cockroach/blob/5614de6e451f5b99515c1c9638214bfc26a9d0aa/pkg/sql/session.go#L718)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Jordan says it's immutable. Violating that invariant [has caused bugs before](https://github.com/cockroachdb/cockroach/pull/16434), so we should be able to rely on its immutability.
</blockquote></details>

Fantastic!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16543#-:-KmhSlrvg-kcEa2d7utT:bnfp4nl)*

**Comment by knz** [comment]
Can you look at my comments below and file the corresponding follow-up issues :)

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/session.go, line 718 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16543#-Kmh1P66Bh-YF_wSUGaN:-Kmi1OHVI_38oPlkXJhP:bia95cv) ([raw file](https://github.com/cockroachdb/cockroach/blob/5614de6e451f5b99515c1c9638214bfc26a9d0aa/pkg/sql/session.go#L718)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Fantastic!
</blockquote></details>

Ugh we do have several places where we still use in-place replacement (for name resolution, for example). The contract "query.stmt is immutable" is only valid after the logical plan has been built.

---

*[pkg/sql/session.go, line 720 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16543#-Kmi1exgQ_5mIG0rLhnu:-Kmi1exgQ_5mIG0rLhnv:b-hm9r77) ([raw file](https://github.com/cockroachdb/cockroach/blob/5614de6e451f5b99515c1c9638214bfc26a9d0aa/pkg/sql/session.go#L720)):*
> ```Go
> 		sql := query.stmt.String()
> 		if len(sql) > 1000 {
> 			sql = sql[:997] + "..."
> ```

careful with that (it's incorrect, as currently written). the [...] operator can break UTF-8 code sequences, and SQL can contain non-ASCII UTF-8 sequences. The correct algorithm to break a string and insert an ellipsis requires backtracking on the bytes until the first ASCII character is found.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16543#-:-Kmi2GlsdVQjPpmeYgrL:b-9ouqwy)*

**Comment by itsbilal** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/session.go, line 718 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16543#-Kmh1P66Bh-YF_wSUGaN:-KmmdvNhnLWI_lMvX38B:bw1j820) ([raw file](https://github.com/cockroachdb/cockroach/blob/5614de6e451f5b99515c1c9638214bfc26a9d0aa/pkg/sql/session.go#L718)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Ugh we do have several places where we still use in-place replacement (for name resolution, for example). The contract "query.stmt is immutable" is only valid after the logical plan has been built.
</blockquote></details>

I couldn't find any instances of the AST's expressions changing in the name resolver (`pkg/sql/select_name_resolution.go`), or in `planner.makePlan`/`planner.newPlan`. `planner.prepare` doesn't really count since we share `queryMeta` after it has been called. Do you have a specific reference in mind?

---

*[pkg/sql/session.go, line 720 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16543#-Kmi1exgQ_5mIG0rLhnu:-KmmgJXJNOjJT0h-e_TX:b-vqya7) ([raw file](https://github.com/cockroachdb/cockroach/blob/5614de6e451f5b99515c1c9638214bfc26a9d0aa/pkg/sql/session.go#L720)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

careful with that (it's incorrect, as currently written). the [...] operator can break UTF-8 code sequences, and SQL can contain non-ASCII UTF-8 sequences. The correct algorithm to break a string and insert an ellipsis requires backtracking on the bytes until the first ASCII character is found.
</blockquote></details>

Filed #16570 .

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16543)*

**Pull request merged**
