### PR TITLE
release 23.1: changefeedccl: add `changefeed.lagging_ranges` metric

### PR DESCRIPTION
**Pull request by jayshrivastava**
Backport commits from https://github.com/cockroachdb/cockroach/pull/109835, https://github.com/cockroachdb/cockroach/pull/110250

---

This change is a backport of the commit from https://github.com/cockroachdb/cockroach/pull/109835. The original chance uses
changefeed options to configure lagging ranges metrics. Because changefeed options
require version gates, they cannot be backported. This change instead uses cluster
settings.

This change adds the `changefeed.lagging_ranges` metric which can be used to track
ranges which are behind. This metric is calculated based on a new changefeed option
`lagging_ranges_threshold` which is the amount of time that a range
checkpoint needs to be in the past to be considered lagging. This defaults to 3 minutes.
This change also adds the changefeed option `lagging_ranges_polling_interval` which is
the polling rate at which a rangefeed will poll for lagging ranges and update the metric.
This defaults to 1 minute.

Sometimes a range may not have any checkpoints for a while because the start time
may be far in the past (this causes a catchup scan during which no checkpoints are emitted).
In this case, the range is considered to the lagging if the created timestamp of the
rangefeed is older than `changefeed.lagging_ranges_threshold`. Note that this means that
any changefeed which starts with an initial scan containing a significant amount of data will
likely indicate nonzero `changefeed.lagging_ranges` until the initial scan is complete. This
is intentional.

Release note (ops change): A new metric `changefeed.lagging_ranges` is added to show the number of
ranges which are behind in changefeeds. This metric can be used with the `metrics_label` changefeed
option. A new cluser setting `changefeed.lagging_ranges_threshold` is added which is the amount of
time a range needs to be behind to be considered lagging. By default this is 3 minutes. There is also
a new cluster setting `changefeed.lagging_ranges_polling_interval` which controls how often
the lagging ranges calculation is done. This setting defaults to polling every 1 minute.

Note that polling adds latency to the metric being updated. For example, if a range falls behind
by 3 minutes, the metric may not update until an additional minute afterwards.

Also note that ranges undergoing an initial scan for longer than the threshold are considered to be
lagging. Starting a changefeed with an initial scan on a large table will likely increment the metric
for each range in the table. However, as ranges complete the initial scan, the number of ranges will
decrease.

Epic: [CRDB-9181](https://cockroachlabs.atlassian.net/browse/CRDB-9181)

Release justification: Customer ask.

### CODE REVIEW

**Review by miretskiy — CHANGES_REQUESTED** [review]
Same comments as the 22.2 backport.

**Comment by jayshrivastava** [comment]
@miretskiy 

Here are some screenshots of the roachtest. No panics :). The closed timestamp interval is 3s, which is why you see the lagging ranges metric fluctuate so much when the threshold is 3s. It might be worth adding a verifier in code that checks if the threshold is greater than the closed ts interval. Lmk what you think about that.

I noticed a small "bug". When we do an initial scan, we don't register ranges with the rangefeed until the initial scan terminates, so the lagging ranges monitor sees 0 ranges, meaning 0 ranges are behind. I say this is a bug because when wrote this feature, I expected all the ranges to be lagging at the start of the initial scan and slowly decrease until none are lagging. What actually will happen is that the initial scan will finish and then there will be a big spike in lagging ranges when the catchup scan starts. Then, this spike will slowly decrease as the ranges catch up. I'm concerned that this spike will be unexpected if users see it hours after they started their changefeed. The alternative is to seed the lagging ranges metric with the number of ranges (perhaps with `divideAllSpansOnRangeBoundaries`). I don't really see any issues with that. Lmk what you think!


Normal operation:
Screenshot 2023-09-26 at 12 57 47 PM

Initial scan (threshold = 2sec):
image

**Comment by miretskiy** [comment]
CI failing because of the old catalog chart test (removed on the master).  This will need to be updated.

I think it's fine to merge w/out addressing that issue.  Perhaps we can do that separately, and backport as need.

**Review by miretskiy — APPROVED** [review]
Thanks for running large scale tests to verify this backport is safe.

**Pull request merged**
