### PR TITLE
kv: run TestStoreRangeMergeTimestampCacheCausality with leader leases

### PR DESCRIPTION
**Pull request by arulajmani**
It's easier to run all 3 lease types explicitly for this test.

References https://github.com/cockroachdb/cockroach/issues/133763 
Release note: None

### CODE REVIEW

**Review by iskettaneh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136329)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/kv/kvserver/client_merge_test.go` line 1034 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136329#-OCnUwn6BttUOicJQdyG:-OCnUwn7AmKmeBFwhKpk:b-ls7xdc) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f43e79a1f8f63832835a476c6b164d8a39fb579/pkg/kv/kvserver/client_merge_test.go#L1034)):*
> ```Go
> 				return errors.New("s2 does not own valid lease for lhs range")
> 			}
> 			if leaseType != roachpb.LeaseLeader {
> ```

Shouldn't this condition be:

if leaseType != roachpb.LeaseExpiration {

?

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136329)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @iskettaneh)

___
*[`pkg/kv/kvserver/client_merge_test.go` line 1034 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136329#-OCnUwn6BttUOicJQdyG:-OCniM342_X_7gb3uzPn:b-smbad) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f43e79a1f8f63832835a476c6b164d8a39fb579/pkg/kv/kvserver/client_merge_test.go#L1034)):*
<details><summary><i>Previously, iskettaneh wrote…</i></summary><blockquote>

Shouldn't this condition be:

if leaseType != roachpb.LeaseExpiration {

?
</blockquote></details>

Yeah, it should be. Thanks for catching; fixed.

**Review by iskettaneh — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136329)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

**Review by iskettaneh — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136329)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

**Comment by arulajmani** [comment]
Thanks! 

bors r+

**Pull request merged**
