### PR TITLE
sql: let AS OF SYSTEM TIME requests use table descriptor cache

### LINKED ISSUE #30967: sql: use descriptor cache for AS OF SYSTEM TIME
Queries with `AS OF SYSTEM TIME` avoid the descriptor cache. This means that even for a very simple point query we have to do a KV op for each query to read the table descriptor. Given that in some cases we have recommended `AS OF SYSTEM TIME` to users to speed up certain workloads, we should fix this.

Here's an idea:
 - keep a timestamp interval, such that reading the descriptor at any timestamp in this interval would return the same version
 - initially, the timestamp interval only contains the timestamp at which we read the descriptor
 - when we get an `AS OF SYSTEM TIME` query, if the timestamp is not within the known interval, then we re-read. After that, we compare the result against the descriptor in the cache; if they are the same version, we extend the known interval to contain the AOST timestamp.

### PR DESCRIPTION
**Pull request by vivekmenezes**
This change also fixes a problem where TRUNCATE was not
setting the ModificationTime on the descriptor.

This change also fixes a bug where we were not using
Timestamp.Prev() to compute the previous timestamp
when reading the previous version of a descriptor.

This change disables the use of the descriptor cache
when AS OF SYSTEM TIME is for a timestamp before
a DROP or a TRUNCATE on a table because of a bug
in AcquireByName().

fixes #30967

Release note (sql change): Speedup AS OF SYSTEM TIME requests by
letting them use the table descriptor cache.

### CODE REVIEW

**Comment by vivekmenezes** [comment]
FYI @nvanbenschoten

**Review by dt — APPROVED** [review]

**Review by nvb — APPROVED** [review]
Thanks for getting this out so fast! I'm a little concerned about the general lack of testing around here, but perhaps I'm just missing it.

**Comment by vivekmenezes** [comment]
This code is tested through TestAsOfTime and TestTxnCanStillResolveOldName, so the approach is correct. The only problem with this change is that it's not testing that the cache is indeed being used. Let me add a test just for that.

**Comment by vivekmenezes** [comment]
Added TestAsOfSystemTimeUsingCache

**Pull request merged**
