### PR TITLE
scripts: add a log2html script

### PR DESCRIPTION
**Pull request by RaduBerinde**
A script that uses vim to convert a log to HTML using syntax highlighting. A
custom syntax highlighting file for CR logs is included.

The intention is to try to wire this up to generate highlighted reports in
TeamCity.

CC @jordanlewis

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9662)

### CODE REVIEW

**Comment by tschottdorf** [comment]
18:18 $ ./scripts/log2html.sh out
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Jun 14 2016 16:06:49)
Unknown option argument: "--not-a-term"
More info with: "vim -h"

**Comment by tschottdorf** [comment]
Works after `brew install vim` (I use neovim so I didn't have that). I don't know how essential `--not-a-term` is; the script would be a bit more useful if non-vimmers could use it out of the box.

**Comment by tschottdorf** [comment]
Just tested the highlighting and it's definitely useful. LGTM as far as I'm concerned.

**Comment by jordanlewis** [comment]
LGTM - nice!

**Comment by RaduBerinde** [comment]
Hm. The `--not-a-term` is used to prevent "warning: output is not a terminal", which comes with a sleep of a couple of seconds. I couldn't find any other way to suppress that, and I couldn't figure out how to do this in "exim" mode which has a silent flag.

I could add a "dummy run" to check if the binary supports that flag.

**Comment by RaduBerinde** [comment]
Updated script and improved the syntax a bit.

**Pull request merged**
