### PR TITLE
[WIP] cloudkms/cloudkmsimpl: adds KMS interface and basic AWS KMS integration

### PR DESCRIPTION
**Pull request by adityamaru**
This change is a first pass design of how the KMS API will look.
It also adds a basic implementation of the AWS KMS service and
an encrypt-decrypt unit test.

Release note: None

### CODE REVIEW

**Comment by adityamaru** [comment]
The design is largely driven by discussions we have had in context of improving pkg dependencies on ExternalStorage - https://github.com/cockroachdb/cockroach/issues/50788

**Review by miretskiy — CHANGES_REQUESTED** [review]
You need to split vendor changes into separate PR.  Send it out separately from the rest of these changes.

> Reviewed 10 of 10 files at r1, 13 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51779#-:-MCsArW_2LixEk9ujVuz:b-t5ssnq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @dt, and @miretskiy)

___
*[pkg/base/config.go, line 544 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51779#-MCsB9pT4GdEupxS6QBE:-MCsB9pUAms7QWmZa2X9:b7sw8ha) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdc76b245f504107033f0333dfd7a6dccd50dabf/pkg/base/config.go#L544)):*
> ```Go
> 
> // KMSConfig describes various configuration options pertaining
> // to kms implementations.
> ```

Maybe just do
`type KMSConfig ExternalIODirCOnfig`

At least for now, these are identical.
___
*[pkg/roachpb/api.proto, line 1264 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51779#-MCsBdxR69hgz1Vub96_:-MCsBdxR69hgz1Vub96a:b-ss8gdh) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdc76b245f504107033f0333dfd7a6dccd50dabf/pkg/roachpb/api.proto#L1264)):*
> ```protobuf
> enum KMSProvider {
>   UnknownKMS = 0;
>   AWSKMS = 1;
> ```

Probably doesn't make sense to suffix those constants w/ `KMS`: These are already typed and scoped (to KMSProvider)
___
*[pkg/roachpb/api.proto, line 1289 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51779#-MCsr6GP8hGTaGSun4zT:-MCsr6GP8hGTaGSun4zU:bw65mqa) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdc76b245f504107033f0333dfd7a6dccd50dabf/pkg/roachpb/api.proto#L1289)):*
<details><summary><i alt="summary">Quoted 15 lines of code…</i></summary>

> ```
>   message AWSKMS {
>     option (gogoproto.equal) = true;
>     string auth = 1;
>     string access_key = 2;
>     string secret = 3;
>     string temp_token = 4;
>     string endpoint = 5;
>     string region = 6;
>     // This identifies the Customer Master Key associated with the KMS. It can
>     // be a KeyARN, KeyID, AliasARN or Alias.
>     // Refer to https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html#encrypt_context
>     // for details.
>     string keyID = 7;
>   }
>   AWSKMS AWSKMSConfig = 2;
> ```
</details>


I'm not a huge fan of this  (and I'm not too big on how it was done w/ external storage either).
Basically, we have a supposedly generic proto, but inside, we have exclusive list of configurations.

My personal preference would be to have
```
message KMS {
  option (gogoproto.equal) = true;
  KMSProvider provider = 1;
  google.protobuf.Any config = 2;
}
```
Config, in turn, would store implementation specific config, encoded inside protobuf.Any

I'd like to get @dt  input on this as well.
___
*[pkg/storage/cloud/external_storage.go, line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51779#-MCsA7C-CYAUVPq-nHax:-MCsA7C-CYAUVPq-nHay:b-nca13n) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdc76b245f504107033f0333dfd7a6dccd50dabf/pkg/storage/cloud/external_storage.go#L45)):*
> ```Go
> 	// GoogleBillingProjectParam is the query parameter for the billing project
> 	// in a gs URI.
> 	GoogleBillingProjectParam = "GOOGLE_BILLING_PROJECT"
> ```

It's a bit strange to see provider specific settings in a "generic" location...
Could the specific service params stay inside service specific implementations?
___
*[pkg/storage/cloudkms/kms.go, line 26 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51779#-MCs73-L8LfFbJw2pFYG:-MCs73-L8LfFbJw2pFYH:b-xntl31) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdc76b245f504107033f0333dfd7a6dccd50dabf/pkg/storage/cloudkms/kms.go#L26)):*
> ```Go
> // KMS provides an API to interact with a KMS service.
> type KMS interface {
> 	ID() (string error)
> ```

Let's document each method? (I don't know what ID() represents for example)
___
*[pkg/storage/cloudkms/kms.go, line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51779#-MCsttkn2LZ9vTP9g_4U:-MCsttkn2LZ9vTP9g_4V:b7vm3rj) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdc76b245f504107033f0333dfd7a6dccd50dabf/pkg/storage/cloudkms/kms.go#L29)):*
> ```Go
> 	Conf() roachpb.KMS
> 	Encrypt(data []byte) ([]byte, error)
> 	Decrypt(data []byte) ([]byte, error)
> ```

I was wondering why you were passing ctx to the factory function below.  I assume
that was because the factory may do some "work" -- whatever it means, to initialize this kms, etc.
This got me thinking... perhaps it's a wrong thing to do.

Perhaps, KMS interface ought to have
```
  Open() error
  Close() error
```

(maybe those 2 above could take ctx).  Open() -- that's pretty clear -- do your thing, contact
kms services, etc, etc.

But I also think we need Close() -- for example to wipe keys from memory, etc.

What do you think? @dt might also want to chime in on that. 
___
*[pkg/storage/cloudkms/kms.go, line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51779#-MCssZkt741Hnrj8ZKsR:-MCssZkt741Hnrj8ZKsS:b-hhg9mb) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdc76b245f504107033f0333dfd7a6dccd50dabf/pkg/storage/cloudkms/kms.go#L39)):*
> ```Go
> 
> // KMSFromURIFactory describes a factory function for KMS given a URI.
> type KMSFromURIFactory func(ctx context.Context, uri string, env KMSEnv) (KMS, error)
> ```

Do you think having KMSFactory interface might be beneficial?

```
type KMSFactory interface {
   FromURI(uri string, env KMSEnv) (KMS, error)
   FromConfig(uri string, config *pbtypes.Any) (KMS, error)
}

func RegisterKMSFactory(scheme string, factory KMSFactory)
```

The FromConfig() assumes we go w/ what I suggested in api.proto; so you might need to be able to create
KMS from opaque config.
___
*[pkg/storage/cloudkms/kms.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51779#-MCstcRqEmWdNeqDox1D:-MCstcRqEmWdNeqDox1E:b-i6b2i2) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdc76b245f504107033f0333dfd7a6dccd50dabf/pkg/storage/cloudkms/kms.go#L47)):*
> ```Go
> // register its factory method.
> func RegisterKMSFromURIFactory(factory KMSFromURIFactory, scheme string) {
> 	kmsFactoryMap[scheme] = factory
> ```

I would add

```
if _, ok := kmsFactory[name]; ok {
		panic("kms implementation " + scheme + " already registered")
}
```

**Review by miretskiy — COMMENTED** [review]
> Reviewed 1 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51779)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @dt)

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51779)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @miretskiy)

___
*[pkg/base/config.go, line 544 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51779#-MCsB9pT4GdEupxS6QBE:-MCviPgc0DZ8uPtsWKUg:b-mavdin) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdc76b245f504107033f0333dfd7a6dccd50dabf/pkg/base/config.go#L544)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Maybe just do
`type KMSConfig ExternalIODirCOnfig`

At least for now, these are identical.
</blockquote></details>

I actually think the existing`ExternalIODirConfig` and flags that set it are what we should be using.
Talking to an external KMS _is_ IO, to an external thing, just like IO to external storage is.

(we could remove the `dir` from the name since it also affect network access, but let's do that separately).
___
*[pkg/roachpb/api.proto, line 1264 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51779#-MCsBdxR69hgz1Vub96_:-MCvlDpHAYI4RuuW4dA7:b9juoqn) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdc76b245f504107033f0333dfd7a6dccd50dabf/pkg/roachpb/api.proto#L1264)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Probably doesn't make sense to suffix those constants w/ `KMS`: These are already typed and scoped (to KMSProvider)
</blockquote></details>

mention this below, but we could maybe just not have a proto repr of kms config at all for now and just use the URI.
___
*[pkg/roachpb/api.proto, line 1289 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51779#-MCsr6GP8hGTaGSun4zT:-MCvj9Kh2nrCPPm1ohSc:bvamzu3) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdc76b245f504107033f0333dfd7a6dccd50dabf/pkg/roachpb/api.proto#L1289)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

> ```
>   message AWSKMS {
>     option (gogoproto.equal) = true;
>     string auth = 1;
>     string access_key = 2;
>     string secret = 3;
>     string temp_token = 4;
>     string endpoint = 5;
>     string region = 6;
>     // This identifies the Customer Master Key associated with the KMS. It can
>     // be a KeyARN, KeyID, AliasARN or Alias.
>     // Refer to https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html#encrypt_context
>     // for details.
>     string keyID = 7;
>   }
>   AWSKMS AWSKMSConfig = 2;
> ```

I'm not a huge fan of this  (and I'm not too big on how it was done w/ external storage either).
Basically, we have a supposedly generic proto, but inside, we have exclusive list of configurations.

My personal preference would be to have
```
message KMS {
  option (gogoproto.equal) = true;
  KMSProvider provider = 1;
  google.protobuf.Any config = 2;
}
```
Config, in turn, would store implementation specific config, encoded inside protobuf.Any

I'd like to get @dt  input on this as well.

</blockquote></details>

Eh, maybe we can just punt this entirely: as @miretskiy pointed out to me yesterday that these configs are pure functions of the URIs, and we can round-trip to/from them. We can just put the URI in our spec for now and decide if/how to replace it with a proto repr later?
___
*[pkg/storage/cloud/external_storage.go, line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51779#-MCsA7C-CYAUVPq-nHax:-MCvjrXT0Yr5bC4IM78K:bgv3cqd) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdc76b245f504107033f0333dfd7a6dccd50dabf/pkg/storage/cloud/external_storage.go#L45)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

It's a bit strange to see provider specific settings in a "generic" location...
Could the specific service params stay inside service specific implementations?

</blockquote></details>

Eh, we don't have the separate cloud impl's in separate packages yet. That maybe should change *but* is is outside the scope of this change.

That said, I wonder if for now, to minimize this diff, we could leave all these symbols where they were, and either just let kmscloudimpl depend on cloudimpl or perhaps even just put the new code currently in kmscloudimpl instead just in the existing cloudimpl package, side-by-side with the storage api for that provider. The reason I might want to consider the latter is code for interacting with aws storage api seems likely to have more overlap with code for interacting with aws kms api than with other storage APIs, so separation on provider may make more sense than on basis of storage vs kms. 
___
*[pkg/storage/cloudkms/kms.go, line 10 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51779#-MCvplTv7OIdF7svCvBr:-MCvplTv7OIdF7svCvBs:b-ijc924) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdc76b245f504107033f0333dfd7a6dccd50dabf/pkg/storage/cloudkms/kms.go#L10)):*
> ```Go
> // by the Apache License, Version 2.0, included in the file
> // licenses/APL.txt.
> package cloudkms
> ```

I could see just sticking this in `cloud` too
___
*[pkg/storage/cloudkms/kms.go, line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51779#-MCsttkn2LZ9vTP9g_4U:-MCvo2Ha1z66QHzu-9nI:bj36a23) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdc76b245f504107033f0333dfd7a6dccd50dabf/pkg/storage/cloudkms/kms.go#L29)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I was wondering why you were passing ctx to the factory function below.  I assume
that was because the factory may do some "work" -- whatever it means, to initialize this kms, etc.
This got me thinking... perhaps it's a wrong thing to do.

Perhaps, KMS interface ought to have
```
  Open() error
  Close() error
```

(maybe those 2 above could take ctx).  Open() -- that's pretty clear -- do your thing, contact
kms services, etc, etc.

But I also think we need Close() -- for example to wipe keys from memory, etc.

What do you think? @dt might also want to chime in on that. 
</blockquote></details>

Encrypt and Decrypt are going to make network calls so they should be passed contexts with which they will make them, rather than using a stored context.
I don't know about Open() / how it differs from the constructor/factory.
We probably do want Close just in case there are network clients to close or whatever.
___
*[pkg/storage/cloudkms/kms.go, line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51779#-MCssZkt741Hnrj8ZKsR:-MCvopYIEFWtGsaHJ2Ze:bvyji83) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdc76b245f504107033f0333dfd7a6dccd50dabf/pkg/storage/cloudkms/kms.go#L39)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Do you think having KMSFactory interface might be beneficial?

```
type KMSFactory interface {
   FromURI(uri string, env KMSEnv) (KMS, error)
   FromConfig(uri string, config *pbtypes.Any) (KMS, error)
}

func RegisterKMSFactory(scheme string, factory KMSFactory)
```

The FromConfig() assumes we go w/ what I suggested in api.proto; so you might need to be able to create
KMS from opaque config.


</blockquote></details>

my vote is we just skip the config entirely for now?
___
*[pkg/storage/cloudkmsimpl/aws_kms.go, line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51779#-MCvpxVX5PArIO6aF5Ds:-MCvpxVX5PArIO6aF5Dt:b-xc0wwp) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdc76b245f504107033f0333dfd7a6dccd50dabf/pkg/storage/cloudkmsimpl/aws_kms.go#L34)):*
> ```Go
> 
> func init() {
> 	cloudkms.RegisterKMSFromURIFactory(awsKMSFromURIFactory, awsScheme)
> ```

@miretskiy I like this pattern _a lot_: we just register for the URI `scheme` and then get the whole URI for our provider-specific function to decode and configure its impl. IMO this is what paves the way to move to separate packages for the provider-specific code, moving those provider-specific URI param symbols you mentioned above.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51779)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @dt, and @miretskiy)

___
*[pkg/storage/cloudkms/kms.go, line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51779#-MCsttkn2LZ9vTP9g_4U:-MCwBJcA0glszbb68Jun:b-h6rn9d) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdc76b245f504107033f0333dfd7a6dccd50dabf/pkg/storage/cloudkms/kms.go#L29)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Encrypt and Decrypt are going to make network calls so they should be passed contexts with which they will make them, rather than using a stored context.
I don't know about Open() / how it differs from the constructor/factory.
We probably do want Close just in case there are network clients to close or whatever.


</blockquote></details>

Right now -- no difference; but then why pass in the context.
Also, I'm on board w/ extendng ecnrypt/decrypt w/ context -- and dropping ctx from constructor arg.
___
*[pkg/storage/cloudkms/kms.go, line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51779#-MCssZkt741Hnrj8ZKsR:-MCwBYtE1izyNqL39tpg:b-bbz0cg) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdc76b245f504107033f0333dfd7a6dccd50dabf/pkg/storage/cloudkms/kms.go#L39)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

my vote is we just skip the config entirely for now?
</blockquote></details>

If we skip config entirely -- the sure.  No need to overcomplicate.
___
*[pkg/storage/cloudkmsimpl/aws_kms.go, line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51779#-MCvpxVX5PArIO6aF5Ds:-MCwB6wv7R5s1FPnxOK5:b-buty3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdc76b245f504107033f0333dfd7a6dccd50dabf/pkg/storage/cloudkmsimpl/aws_kms.go#L34)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

@miretskiy I like this pattern _a lot_: we just register for the URI `scheme` and then get the whole URI for our provider-specific function to decode and configure its impl. IMO this is what paves the way to move to separate packages for the provider-specific code, moving those provider-specific URI param symbols you mentioned above. 
</blockquote></details>

Yup -- exactly what I used in the schedule job executor stuff.
Also, makes it easy to write tests -- for example, you can have
scoped implementations registered in tests.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51779)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @dt, and @miretskiy)

___
*[pkg/storage/cloud/external_storage.go, line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51779#-MCsA7C-CYAUVPq-nHax:-MCwG21E6Odj4myWOkfk:b-toxbed) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdc76b245f504107033f0333dfd7a6dccd50dabf/pkg/storage/cloud/external_storage.go#L45)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Eh, we don't have the separate cloud impl's in separate packages yet. That maybe should change *but* is is outside the scope of this change.

That said, I wonder if for now, to minimize this diff, we could leave all these symbols where they were, and either just let kmscloudimpl depend on cloudimpl or perhaps even just put the new code currently in kmscloudimpl instead just in the existing cloudimpl package, side-by-side with the storage api for that provider. The reason I might want to consider the latter is code for interacting with aws storage api seems likely to have more overlap with code for interacting with aws kms api than with other storage APIs, so separation on provider may make more sense than on basis of storage vs kms. 
</blockquote></details>

I didn't mean separate packages for each imple -- just keep those inside cloudimpl.  That's good enough.

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51779)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @miretskiy)

___
*[pkg/base/config.go, line 544 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51779#-MCsB9pT4GdEupxS6QBE:-MCyacKhDuJnVYRsNjyk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdc76b245f504107033f0333dfd7a6dccd50dabf/pkg/base/config.go#L544)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I actually think the existing`ExternalIODirConfig` and flags that set it are what we should be using.
Talking to an external KMS _is_ IO, to an external thing, just like IO to external storage is.

(we could remove the `dir` from the name since it also affect network access, but let's do that separately).

</blockquote></details>

Done.
___
*[pkg/roachpb/api.proto, line 1264 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51779#-MCsBdxR69hgz1Vub96_:-MCybhz082E5RuQy9aHG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdc76b245f504107033f0333dfd7a6dccd50dabf/pkg/roachpb/api.proto#L1264)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

mention this below, but we could maybe just not have a proto repr of kms config at all for now and just use the URI.
</blockquote></details>

Done.
___
*[pkg/roachpb/api.proto, line 1289 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51779#-MCsr6GP8hGTaGSun4zT:-MCybcX45rNU_m77EGN2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdc76b245f504107033f0333dfd7a6dccd50dabf/pkg/roachpb/api.proto#L1289)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Eh, maybe we can just punt this entirely: as @miretskiy pointed out to me yesterday that these configs are pure functions of the URIs, and we can round-trip to/from them. We can just put the URI in our spec for now and decide if/how to replace it with a proto repr later?
</blockquote></details>

Done.
___
*[pkg/storage/cloud/external_storage.go, line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51779#-MCsA7C-CYAUVPq-nHax:-MCz3-pT8sRkeX8LHsta:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdc76b245f504107033f0333dfd7a6dccd50dabf/pkg/storage/cloud/external_storage.go#L45)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I didn't mean separate packages for each imple -- just keep those inside cloudimpl.  That's good enough.
</blockquote></details>

Done.
___
*[pkg/storage/cloudkms/kms.go, line 10 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51779#-MCvplTv7OIdF7svCvBr:-MCyc12k3XBXVbKyYCyT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdc76b245f504107033f0333dfd7a6dccd50dabf/pkg/storage/cloudkms/kms.go#L10)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I could see just sticking this in `cloud` too
</blockquote></details>

Done.
___
*[pkg/storage/cloudkms/kms.go, line 26 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51779#-MCs73-L8LfFbJw2pFYG:-MD-yhJs7RHi7M8zY-_T:bzc0g5m) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdc76b245f504107033f0333dfd7a6dccd50dabf/pkg/storage/cloudkms/kms.go#L26)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Let's document each method? (I don't know what ID() represents for example)
</blockquote></details>

Done. I foresee us using ID() when writing {keyID, encrypted DataKey} to the manifest file. This will allow each KMS to decide what they want written to the file KeyARN, hashed key etc
___
*[pkg/storage/cloudkms/kms.go, line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51779#-MCsttkn2LZ9vTP9g_4U:-MCz2j4wCOmpn2VVAZLi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdc76b245f504107033f0333dfd7a6dccd50dabf/pkg/storage/cloudkms/kms.go#L29)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Right now -- no difference; but then why pass in the context.
Also, I'm on board w/ extendng ecnrypt/decrypt w/ context -- and dropping ctx from constructor arg.
</blockquote></details>

Done.
___
*[pkg/storage/cloudkms/kms.go, line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51779#-MCssZkt741Hnrj8ZKsR:-MD-xCvgDFKnk7eowDO6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdc76b245f504107033f0333dfd7a6dccd50dabf/pkg/storage/cloudkms/kms.go#L39)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

If we skip config entirely -- the sure.  No need to overcomplicate.
</blockquote></details>

Done.
___
*[pkg/storage/cloudkms/kms.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51779#-MCstcRqEmWdNeqDox1D:-MCz2cLm1Wk8eCTIXJYK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdc76b245f504107033f0333dfd7a6dccd50dabf/pkg/storage/cloudkms/kms.go#L47)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I would add

```
if _, ok := kmsFactory[name]; ok {
		panic("kms implementation " + scheme + " already registered")
}
```
</blockquote></details>

Done.
___
*[pkg/storage/cloudkmsimpl/aws_kms.go, line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51779#-MCvpxVX5PArIO6aF5Ds:-MCz37ID8_FbBv2BTlxR:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdc76b245f504107033f0333dfd7a6dccd50dabf/pkg/storage/cloudkmsimpl/aws_kms.go#L34)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Yup -- exactly what I used in the schedule job executor stuff.
Also, makes it easy to write tests -- for example, you can have
scoped implementations registered in tests.
</blockquote></details>

:thumbsup:

**Comment by adityamaru** [comment]
Made a new PR incorporating the WIP comments at #51884.

**Pull request closed without merging**
