### PR TITLE
distsqlrun: add benchmarks for distsql infrastructure

### PR DESCRIPTION
**Pull request by jordanlewis**
For #24690 - this completes all of them except for the outbox (and `RowChannel` which was already benchmarked).

```
BenchmarkRouter/BY_RANGE/outputs=2-8                  30          35692346 ns/op          29.38 MB/s
BenchmarkRouter/BY_RANGE/outputs=4-8                  30          34937864 ns/op          60.03 MB/s
BenchmarkRouter/BY_RANGE/outputs=8-8                  30          35112627 ns/op         119.45 MB/s
BenchmarkRouter/BY_HASH/outputs=2-8                  100          19840820 ns/op          52.85 MB/s
BenchmarkRouter/BY_HASH/outputs=4-8                  100          18774629 ns/op         111.70 MB/s
BenchmarkRouter/BY_HASH/outputs=8-8                   50          27249006 ns/op         153.93 MB/s
BenchmarkRouter/MIRROR/outputs=2-8                    30          34873995 ns/op          30.07 MB/s
BenchmarkRouter/MIRROR/outputs=4-8                    20          59782584 ns/op          35.08 MB/s
BenchmarkRouter/MIRROR/outputs=8-8                    10         153532931 ns/op          27.32 MB/s
```

```
BenchmarkMultiplexedRowChannel/senders=2-8                   500           2841863 ns/op          56.30 MB/s
BenchmarkMultiplexedRowChannel/senders=4-8                   100          10030833 ns/op          31.90 MB/s
BenchmarkMultiplexedRowChannel/senders=8-8                    50          32353212 ns/op          19.78 MB/s
```

```
BenchmarkStreamEncoder/cols=1-8                      500           3074456 ns/op         170.53 MB/s
BenchmarkStreamEncoder/cols=4-8                      200           8792420 ns/op         238.52 MB/s
BenchmarkStreamEncoder/cols=16-8                      50          34338533 ns/op         244.29 MB/s
BenchmarkStreamEncoder/cols=64-8                      10         131163270 ns/op         255.82 MB/s
```

```
BenchmarkStreamDecoder/cols=1-8                  1000000              1058 ns/op         120.92 MB/s
BenchmarkStreamDecoder/cols=4-8                   500000              2792 ns/op         183.32 MB/s
BenchmarkStreamDecoder/cols=16-8                  200000              9592 ns/op         213.50 MB/s
BenchmarkStreamDecoder/cols=64-8                   50000             35636 ns/op         229.88 MB/s
```

### CODE REVIEW

**Comment by solongordon** [comment]
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/sql/distsqlrun/base_test.go, line 103 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24823#-LAJA_ZM0iBYRutLEdiF:-LAJA_ZM0iBYRutLEdiG:bqmetn) ([raw file](https://github.com/cockroachdb/cockroach/blob/54e4e1653bda7dd959ca4fa0adee4defec8476bd/pkg/sql/distsqlrun/base_test.go#L103)):*
> ```Go
> 
> func BenchmarkMultiplexedRowChannel(b *testing.B) {
> 	numRows := 10000
> ```

Maybe nicer to make this `1 << 16` for comparison with other benchmarks.

---

*[pkg/sql/distsqlrun/base_test.go, line 104 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24823#-LAJB0w46gu8y969JVq0:-LAJ7u12Dn0ExYnTbEDU:bfrxs6s) ([raw file](https://github.com/cockroachdb/cockroach/blob/54e4e1653bda7dd959ca4fa0adee4defec8476bd/pkg/sql/distsqlrun/base_test.go#L104)):*
> ```Go
> func BenchmarkMultiplexedRowChannel(b *testing.B) {
> 	numRows := 10000
> 	row := sqlbase.EncDatumRow{sqlbase.DatumToEncDatum(oneIntCol[0], tree.NewDInt(0))}
> ```

or `row := sqlbase.EncDatumRow{intEncDatum(0)}`

---

*[pkg/sql/distsqlrun/base_test.go, line 113 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24823#-LAJA5835Fe6dMVYCCoB:-LAJA5835Fe6dMVYCCoC:b-9vz41x) ([raw file](https://github.com/cockroachdb/cockroach/blob/54e4e1653bda7dd959ca4fa0adee4defec8476bd/pkg/sql/distsqlrun/base_test.go#L113)):*
> ```Go
> 				mrc := &MultiplexedRowChannel{}
> 				mrc.Init(senders, oneIntCol)
> 				go func() {
> ```

Minor: Is it necessary for this to be a goroutine? Seems like you could just move it after the senders. Then you can ditch the `WaitGroup` entirely.

---

*[pkg/sql/distsqlrun/routers_test.go, line 702 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24823#-LAJ-ha39MRVAxYQNSir:-LAJ-ha39MRVAxYQNSis:b-fcvbuc) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e292eed3ef66bee6594ac49819fa7a22481946b/pkg/sql/distsqlrun/routers_test.go#L702)):*
> ```Go
> 
> func BenchmarkRouter(b *testing.B) {
> 	numCols := 1
> ```

Not sure how much it affects the numbers, but might be good to use 2 columns since that's what the processor benchmarks tend to use.

---

*[pkg/sql/distsqlrun/routers_test.go, line 736 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24823#-LAJ6so81YTTahR4BlyX:-LAJ6so81YTTahR4BlyY:b-5rw5w1) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e292eed3ef66bee6594ac49819fa7a22481946b/pkg/sql/distsqlrun/routers_test.go#L736)):*
> ```Go
> 					for i := 0; i < b.N; i++ {
> 						input.Reset()
> 						// Reset the EncDatums' encoded bytes cache.
> ```

Per our discussion, maybe better to allow it to use the cached values (or proactively warm the cache in `makeIntRows`).

---

*[pkg/sql/distsqlrun/routers_test.go, line 732 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24823#-LAJAiPK5vGSnLnRm8YN:-LAJAiPK5vGSnLnRm8YO:b-4cyt3u) ([raw file](https://github.com/cockroachdb/cockroach/blob/54e4e1653bda7dd959ca4fa0adee4defec8476bd/pkg/sql/distsqlrun/routers_test.go#L732)):*
> ```Go
> 				chans := make([]RowChannel, nOutputs)
> 				recvs := make([]RowReceiver, nOutputs)
> 				b.Run(fmt.Sprintf("outputs=%d", nOutputs), func(b *testing.B) {
> ```

Could be nice to always include `rows` in the output to facilitate comparison with other benchmarks.

---

*[pkg/sql/distsqlrun/stream_data_test.go, line 207 at r4](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24823#-LAJHRkd5eHto9gsNw8y:-LAJHRkd5eHto9gsNw8z:bvgvdsz) ([raw file](https://github.com/cockroachdb/cockroach/blob/eec0cf968636ccecda775338135f8cca42008c48/pkg/sql/distsqlrun/stream_data_test.go#L207)):*
> ```Go
> 			msg := se.FormMessage(ctx)
> 
> 			for i := 0; i < b.N; i++ {
> ```

Do we need any cache busting here?

---

*[pkg/sql/distsqlrun/stream_data_test.go, line 210 at r4](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24823#-LAJFzyQ6F0W_39TW0mQ:-LAJFzyQ6F0W_39TW0mR:bfep75y) ([raw file](https://github.com/cockroachdb/cockroach/blob/eec0cf968636ccecda775338135f8cca42008c48/pkg/sql/distsqlrun/stream_data_test.go#L210)):*
> ```Go
> 				var sd StreamDecoder
> 				sd.AddMessage(msg)
> 				for {
> ```

Minor: I wonder if `for j := 0; j < outboxBufRows; j++ {` would be better. That way we don't accidentally short-circuit if we get the setup wrong.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24823)*

**Comment by danhhz** [comment]
Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsqlrun/routers_test.go, line 702 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24823#-LAJ-ha39MRVAxYQNSir:-LAJId4u4UraHo7NeFsP:b-n3r2sk) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e292eed3ef66bee6594ac49819fa7a22481946b/pkg/sql/distsqlrun/routers_test.go#L702)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

Not sure how much it affects the numbers, but might be good to use 2 columns since that's what the processor benchmarks tend to use.
</blockquote></details>

Don't hold the current work up for this, but standardizing these sorts of up-and-down-the-stack benchmarks so that they're directly comparable was one of the design goals of workload. Might be worth keeping in mind for future work like this

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24823)*

**Comment by jordanlewis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsqlrun/base_test.go, line 103 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24823#-LAJA_ZM0iBYRutLEdiF:-LAJj5JADjI754dGsuO_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/54e4e1653bda7dd959ca4fa0adee4defec8476bd/pkg/sql/distsqlrun/base_test.go#L103)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

Maybe nicer to make this `1 << 16` for comparison with other benchmarks.
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/base_test.go, line 104 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24823#-LAJB0w46gu8y969JVq0:-LAJjXsgCwQgAELSpPIj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/54e4e1653bda7dd959ca4fa0adee4defec8476bd/pkg/sql/distsqlrun/base_test.go#L104)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

or `row := sqlbase.EncDatumRow{intEncDatum(0)}`
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/base_test.go, line 113 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24823#-LAJA5835Fe6dMVYCCoB:-LAJhxuJDlPx-KnhV4WH:bcfgjb4) ([raw file](https://github.com/cockroachdb/cockroach/blob/54e4e1653bda7dd959ca4fa0adee4defec8476bd/pkg/sql/distsqlrun/base_test.go#L113)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

Minor: Is it necessary for this to be a goroutine? Seems like you could just move it after the senders. Then you can ditch the `WaitGroup` entirely.
</blockquote></details>

It needs to be a goroutine if we want to simulate what happens in the best case - that the consumer is able to keep up with the producers. Otherwise, the router will store all of the values that are sent to it in buffers, which will eventually spill to disk. This is an interesting thing to benchmark as well, but it's not exactly the happy path. Perhaps we should add a separate benchmark for it.

---

*[pkg/sql/distsqlrun/routers_test.go, line 702 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24823#-LAJ-ha39MRVAxYQNSir:-LAJWtu14ojddbBSaFEh:bv7dnv0) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e292eed3ef66bee6594ac49819fa7a22481946b/pkg/sql/distsqlrun/routers_test.go#L702)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Don't hold the current work up for this, but standardizing these sorts of up-and-down-the-stack benchmarks so that they're directly comparable was one of the design goals of workload. Might be worth keeping in mind for future work like this
</blockquote></details>

Could you say more? These benchmarks aren't designed to replace the functionality of workload. We're trying to create a bottleneck analysis of the DistSQL system, to understand how performance is limited by each aspect.

We're planning to use workload to understand the system's performance on our actual set of "significant queries, and these benchmarks to understand (at a very high level) the performance of each component of the overall system.

---

*[pkg/sql/distsqlrun/routers_test.go, line 736 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24823#-LAJ6so81YTTahR4BlyX:-LAJkIIJ6nc44nvgRg2a:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e292eed3ef66bee6594ac49819fa7a22481946b/pkg/sql/distsqlrun/routers_test.go#L736)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

Per our discussion, maybe better to allow it to use the cached values (or proactively warm the cache in `makeIntRows`).
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/routers_test.go, line 732 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24823#-LAJAiPK5vGSnLnRm8YN:-LAJjnOXD8tSc_Z4DO_R:bl1h72v) ([raw file](https://github.com/cockroachdb/cockroach/blob/54e4e1653bda7dd959ca4fa0adee4defec8476bd/pkg/sql/distsqlrun/routers_test.go#L732)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

Could be nice to always include `rows` in the output to facilitate comparison with other benchmarks.
</blockquote></details>

Ok, done.

---

*[pkg/sql/distsqlrun/stream_data_test.go, line 207 at r4](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24823#-LAJHRkd5eHto9gsNw8y:-LAJl-9-5mDlMPKNy5Gx:b-noxzc9) ([raw file](https://github.com/cockroachdb/cockroach/blob/eec0cf968636ccecda775338135f8cca42008c48/pkg/sql/distsqlrun/stream_data_test.go#L207)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

Do we need any cache busting here?
</blockquote></details>

Similar question as before - I guess the answer is that it's likely that rows will be decoded at this stage in the pipeline, and we should be benchmarking EncDatum's encoding to bytes as a separate benchmark. So we shouldn't bust any caches.

---

*[pkg/sql/distsqlrun/stream_data_test.go, line 210 at r4](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24823#-LAJFzyQ6F0W_39TW0mQ:-LAJvferDMHP7WzYFeCA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eec0cf968636ccecda775338135f8cca42008c48/pkg/sql/distsqlrun/stream_data_test.go#L210)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

Minor: I wonder if `for j := 0; j < outboxBufRows; j++ {` would be better. That way we don't accidentally short-circuit if we get the setup wrong.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24823)*

**Comment by solongordon** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/distsqlrun/base_test.go, line 113 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24823#-LAJA5835Fe6dMVYCCoB:-LAOCq0l3k5spTIbyBTO:b-35jxq4) ([raw file](https://github.com/cockroachdb/cockroach/blob/54e4e1653bda7dd959ca4fa0adee4defec8476bd/pkg/sql/distsqlrun/base_test.go#L113)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

It needs to be a goroutine if we want to simulate what happens in the best case - that the consumer is able to keep up with the producers. Otherwise, the router will store all of the values that are sent to it in buffers, which will eventually spill to disk. This is an interesting thing to benchmark as well, but it's not exactly the happy path. Perhaps we should add a separate benchmark for it.
</blockquote></details>

Oh I see. Though it's not obvious to me why having it in a goroutine affects whether the consumer can keep up. Is it just because `mrc.Next()` is called before the first push?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24823#-:-LAODjmDBnPIiDjBNzlk:bnfp4nl)*

**Comment by jordanlewis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/distsqlrun/base_test.go, line 113 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24823#-LAJA5835Fe6dMVYCCoB:-LAOEhyu7TxoOMRd2CT0:b-9u2o28) ([raw file](https://github.com/cockroachdb/cockroach/blob/54e4e1653bda7dd959ca4fa0adee4defec8476bd/pkg/sql/distsqlrun/base_test.go#L113)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Oh I see. Though it's not obvious to me why having it in a goroutine affects whether the consumer can keep up. Is it just because `mrc.Next()` is called before the first push?
</blockquote></details>

Oh, wait, I see what you're saying - you can have the consumer bit happen in the main thread because the main thread isn't doing anything else. I think nevertheless that it's slightly clearer to have a goroutine doing it, because it starts before you start up the sender goroutines, so there's no initial lag of consuming while you're initializing the rest of the senders. Going to leave as-is.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24823)*

**Comment by jordanlewis** [comment]
TFTR!

bors r+

**Comment by solongordon** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/distsqlrun/base_test.go, line 113 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24823#-LAJA5835Fe6dMVYCCoB:-LAOGlq_7B4KuzCYXtSl:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/54e4e1653bda7dd959ca4fa0adee4defec8476bd/pkg/sql/distsqlrun/base_test.go#L113)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Oh, wait, I see what you're saying - you can have the consumer bit happen in the main thread because the main thread isn't doing anything else. I think nevertheless that it's slightly clearer to have a goroutine doing it, because it starts before you start up the sender goroutines, so there's no initial lag of consuming while you're initializing the rest of the senders. Going to leave as-is.
</blockquote></details>

:thumbsup: 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24823)*

**Pull request merged**
