### PR TITLE
sql: add access control checks to multi-region related builtins

### LINKED ISSUE #83912: sql/builtins: multitenant related crdb_internal function access checks should match ALTER TABLE/DATABASE access checks
The following two functions should have access control checks that match the access checks that would occur if you attempted the same modifications via `ALTER TABLE` or `ALTER DATABASE`:

```
crdb_internal.reset_multi_region_zone_configs_for_database
crdb_internal.reset_multi_region_zone_configs_for_table
```

Jira issue: CRDB-17349

Epic: CRDB-17355

### PR DESCRIPTION
**Pull request by stevendanna**
This adds access checks to the functions that power the following
builtins:

 - crdb_internal.reset_multi_region_zone_configs_for_database
 - crdb_internal.reset_multi_region_zone_configs_for_table
 - crdb_internal.validate_multi_region_zone_configs

Fixes #83912

Release note (security update): Multi-region related builtin functions
now have access control checks.

### CODE REVIEW

**Review by knz — APPROVED** [review]
great thanks

**Comment by stevendanna** [comment]
bors r=knz

**Comment by stevendanna** [comment]
blathers backport 22.1

**Comment by stevendanna** [comment]
blathers backport 21.2

**Pull request merged**
