### PR TITLE
sql: make schema between `crdb_internal.ranges` and `range_no_leases` consistent

### LINKED ISSUE #93788: sql: inconsistent schema between `crdb_internal.ranges` and `.ranges_no_leases`
Found while working on #93617.

**Describe the problem**

The columns `replicas`, `voting_replicas`, `learning_replicas` have type `INT[]` (`types.IntArray`) when produced by `crdb_internal.ranges_no_leases`.

This is a regular SQL array type and is 1-indexed.

However, the same columns in the view `crdb_internal.ranges` (a view over `ranges_no_leases`)  overrides their type to become `INT2VECTOR`, a weird, vestigial 0-indexed type from PostgreSQL.

This means that we have ostensibly incompatible indexing behavior between `.ranges` and `.ranges_no_leases`. This seems undesirable.

**Expected behavior**

Both should just use `INT[]`.

Jira issue: CRDB-22528

Epic CRDB-17785

### PR DESCRIPTION
**Pull request by e-mbrown**
Resolves #93788

Release note (backward-incompatible change): The type of the `replicas`, `voting_replicas`, `non_voting_replicas` and `learner_replicas` in `crdb_internal.ranges` were overriden to `INT2VECTOR` causing incompatible indexing between `.ranges` and `.ranges_no_leases`. Now the types of those columns in the two tables are all INT[].

### CODE REVIEW

**Comment by ajwerner** [comment]
What are compatibility considerations for this change?

**Review by rafiss — CHANGES_REQUESTED** [review]
re: compatibility, we warn users to not rely on this table here: https://www.cockroachlabs.com/docs/stable/crdb-internal.html

so this seems fine to fix in a major version release

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96287#-:-NND8NoeA9MHUNX6czIg:b552l59)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @knz)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96287#-NND83VDDS3ukas-w_Xu):*
we don't need to add a release note, since this `crdb_internal` table is not a public interface. this info can still be in the commit message, just not a release note.
___
*[`pkg/sql/catalog/colinfo/result_columns.go` line 349 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96287#-NND7WIy7JeZKEX8teaw:-NND7WIz7DoiPAgX9ezS:blaish2) ([raw file](https://github.com/cockroachdb/cockroach/blob/778b6fbb15ebc9dfcb519b47b0afdeda9aade3a8/pkg/sql/catalog/colinfo/result_columns.go#L349)):*
> ```Go
> func init() {
> 	// This check can be removed once Ranges can be constructed
> 	// using append(RangesNoLeases, ...).
> ```

if you'd like to remove this code, then we should also do what it's suggesting. change the definition of `Ranges` so that it is:
```
var Ranges = append(RangesNoLeases, <columns that are unique to Ranges>)`
```

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96287)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @rafiss)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96287#-NND83VDDS3ukas-w_Xu):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

we don't need to add a release note, since this `crdb_internal` table is not a public interface. this info can still be in the commit message, just not a release note.
</blockquote></details>

We have reasons to believe the reality in the field on this specific table is diferent (i.e. many folk inside and outside CRL have already built upon it).
So I think the conservative approach here is to include a reelase note (in category backward-incompatible change)

**Review by e-mbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96287)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rafiss)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96287#-NND83VDDS3ukas-w_Xu):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

We have reasons to believe the reality in the field on this specific table is diferent (i.e. many folk inside and outside CRL have already built upon it).
So I think the conservative approach here is to include a reelase note (in category backward-incompatible change)
</blockquote></details>

Done.
___
*[`pkg/sql/catalog/colinfo/result_columns.go` line 349 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96287#-NND7WIy7JeZKEX8teaw:-NNDNgpO02sGYA7Vxx-Q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/778b6fbb15ebc9dfcb519b47b0afdeda9aade3a8/pkg/sql/catalog/colinfo/result_columns.go#L349)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

if you'd like to remove this code, then we should also do what it's suggesting. change the definition of `Ranges` so that it is:
```
var Ranges = append(RangesNoLeases, <columns that are unique to Ranges>)`
```

</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
lgtm after addressing two nits!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96287#-:-NNE9c-iB43X2OWYJSew:bkz9qi4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @knz)

___
*[`-- commits` line 9 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96287#-NNE8qFb1SbTE2B2RRnZ):*
nit: can you add more specifics so this is clear? instead of "Now those column types and indexing are consistent between the two tables." maybe say "Now the types of those columns in the two tables are all INT[]."
___
*[`pkg/sql/catalog/colinfo/result_columns.go` line 312 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96287#-NNE93RC3RBS0Sn2t2tR:-NNE93RC3RBS0Sn2t2tS:b-57kkz6) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa142d2feffb5ce070c18eec35d71a8eb399eaba/pkg/sql/catalog/colinfo/result_columns.go#L312)):*
> ```Go
> }
> 
> var colUniquetoRange = ResultColumns{
> ```

nit: this var isn't that necessary. Ranges can be defined as 
```
var Ranges = append(
	RangesNoLeases,
	ResultColumn{Name: "lease_holder", Typ: types.Int},
	ResultColumn{Name: "range_size", Typ: types.Int},
)
```

**Comment by e-mbrown** [comment]
Thanks for the reviews!

bors r=rafiss

**Pull request merged**
