### PR TITLE
licenses: updating licenses

### PR DESCRIPTION
**Pull request by celiala**
As part of [Creating a release branch](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/187859111/Creating+a+release+branch) for release-21.2, this PR:
- Adds the following new licenses:
	- BSL-1.0 (Boost Software License)
	- CC-BY-3.0
	- CC0-1.0
	- JSON
	- MPL-2.0
	- The Unlicense
- Updates the BSL change date for 21.2 (we missed updating this last Spring; a separate PR will update this for master/22.1 after branch cut).

This PR is one of the tasks detailed in #70751, which tracks all the steps relevant to creating a release branch for `${vBRANCH_CUT}` and preparing master for the `${vNEXT}` major version.

Release justification: Non-production code change
Release note: None

### CODE REVIEW

**Review by jlinder — APPROVED** [review]
Looking at http://unlicense.org, the license can be slightly modified to not include the last line ("For more information, please refer to <https://unlicense.org>"). If all the dependencies that use this license do not remove that line, then including just one file for it seems right.

> Reviewed 6 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69904#-:-MjAaweWCU_YYVmIOGw0:b-arxvtm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell)

**Review by bdarnell — APPROVED** [review]
The presence of two BSL licenses is unfortunate. Let's rename the boost one to Boost-BSL.txt. (alternately, we could follow the [SPDX](https://spdx.org/licenses/) convention and use BSL for boost and BUSL for business. But we refer to BSL.txt all over the place and I'm not eager to make that change right now).

**Review by celiala — COMMENTED** [review]
TFTRs! 

I'll plan to merge this as soon as tests pass. Afterwards, I'll also backport this to `release-21.2`, as approved in triage meeting.


> Looking at http://unlicense.org, the license can be slightly modified to not include the last line ("For more information, please refer to https://unlicense.org"). If all the dependencies that use this license do not remove that line, then including just one file for it seems right.

Ack, done.

> The presence of two BSL licenses is unfortunate. Let's rename the boost one to Boost-BSL.txt. (alternately, we could follow the SPDX convention and use BSL for boost and BUSL for business. But we refer to BSL.txt all over the place and I'm not eager to make that change right now).

Ack, done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69904#-:-Mkx_PSdDMewyJhz5stH:b7jetbn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jlinder)

**Pull request merged**
