### PR TITLE
storage: disable checkUncertainty on failOnMoreRecent in scanner

### LINKED ISSUE #119681: kv/kvnemesis: TestKVNemesisMultiNode failed
kv/kvnemesis.TestKVNemesisMultiNode [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/14169943?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/14169943?buildTab=artifacts#/) on release-23.1 @ [5d02fdf2851038279f7544e6271a08e1036a2966](https://github.com/cockroachdb/cockroach/commits/5d02fdf2851038279f7544e6271a08e1036a2966):

```
=== RUN   TestKVNemesisMultiNode
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/logTestKVNemesisMultiNode681426315
    test_log_scope.go:79: use -show-logs to present logs inline
    kvnemesis_test.go:180: seed: 8246618713428840787
    kvnemesis_test.go:124: kvnemesis logging to /artifacts/tmp/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/kvnemesis2506896689
    kvnemesis.go:165: error applying x.ScanForUpdate(ctx, tk(7627554184111334918), tk(11297944047384909700), 0) // WriteTooOldError: write for key /Table/100/"83f343408bfd2cf2" at timestamp 1709031554.741791117,0 too old; wrote at 1709031554.784361740,1: {<nil> 0 {0xc002fbb670} <nil> 1709031554.919155299,0}
    kvnemesis.go:185: failures(verbose): /artifacts/tmp/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/kvnemesis2506896689/failures
        repro steps: /artifacts/tmp/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/kvnemesis2506896689/repro.go
        rangefeed KVs: /artifacts/tmp/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/kvnemesis2506896689/kvs-rangefeed.txt
        scan KVs: /artifacts/tmp/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/kvnemesis2506896689/kvs-scan.txt
    kvnemesis_test.go:207: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/kv/kvnemesis/pkg/kv/kvnemesis/kvnemesis_test.go:207
        	            				github.com/cockroachdb/cockroach/pkg/kv/kvnemesis/pkg/kv/kvnemesis/kvnemesis_test.go:160
        	Error:      	Should be zero, but was 1
        	Test:       	TestKVNemesisMultiNode
        	Messages:   	kvnemesis detected failures
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/logTestKVNemesisMultiNode681426315
--- FAIL: TestKVNemesisMultiNode (19.24s)
```

Parameters:
 - <code>TAGS=bazel,gss</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #118471 kv/kvnemesis: TestKVNemesisMultiNode failed [C-test-failure O-robot P-2 T-kv X-duplicate branch-release-23.2]
- #118017 kv/kvnemesis: TestKVNemesisMultiNode failed [A-testing C-bug C-test-failure O-robot P-2 T-kv branch-master]
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestKVNemesisMultiNode.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-36279

### LINKED ISSUE #131005: kv/kvnemesis: TestKVNemesisMultiNode failed
kv/kvnemesis.TestKVNemesisMultiNode [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/16952817?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/16952817?buildTab=artifacts#/) on release-23.1 @ [9d6bfa8c50584f8092dd43c8a139959a584fd72f](https://github.com/cockroachdb/cockroach/commits/9d6bfa8c50584f8092dd43c8a139959a584fd72f):

```
=== RUN   TestKVNemesisMultiNode
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/logTestKVNemesisMultiNode683581851
    test_log_scope.go:79: use -show-logs to present logs inline
    kvnemesis_test.go:180: seed: 9201876552453284660
    kvnemesis_test.go:124: kvnemesis logging to /artifacts/tmp/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/kvnemesis3556606767
    kvnemesis.go:165: error applying x.GetForUpdate(ctx, tk(3100587421328275948)) // WriteTooOldError: write for key /Table/100/"2b077fd50350f9ec" at timestamp 1726742753.752932905,0 too old; wrote at 1726742753.795305116,1: {<nil> 0 {0xc001a83320} <nil> 1726742753.934287619,0}
    kvnemesis.go:185: failures(verbose): /artifacts/tmp/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/kvnemesis3556606767/failures
        repro steps: /artifacts/tmp/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/kvnemesis3556606767/repro.go
        rangefeed KVs: /artifacts/tmp/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/kvnemesis3556606767/kvs-rangefeed.txt
        scan KVs: /artifacts/tmp/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/kvnemesis3556606767/kvs-scan.txt
    kvnemesis_test.go:207: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/kv/kvnemesis/pkg/kv/kvnemesis/kvnemesis_test.go:207
        	            				github.com/cockroachdb/cockroach/pkg/kv/kvnemesis/pkg/kv/kvnemesis/kvnemesis_test.go:160
        	Error:      	Should be zero, but was 1
        	Test:       	TestKVNemesisMultiNode
        	Messages:   	kvnemesis detected failures
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/1f42cf5be2fc021646bf9b2daf5eaef3/logTestKVNemesisMultiNode683581851
--- FAIL: TestKVNemesisMultiNode (18.73s)
```

Parameters:
 - <code>TAGS=bazel,gss</code>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #129194 kv/kvnemesis: TestKVNemesisMultiNode failed [C-test-failure O-robot P-3 T-kv X-duplicate branch-master no-test-failure-activity]
- #118471 kv/kvnemesis: TestKVNemesisMultiNode failed [A-testing C-bug C-test-failure O-robot P-3 T-kv branch-release-23.2]
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestKVNemesisMultiNode.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-42333

### PR DESCRIPTION
**Pull request by tbg**
It was possible for reads with failOnMoreRecent to hit a
ReadWithinUncertaintyIntervalError instead of the desired
WriteTooOldError. This commit disables uncertainty checks when
failOnMoreRecent is active, as the latter is a stronger check anyway.

Fixes https://github.com/cockroachdb/cockroach/issues/119681.
Fixes https://github.com/cockroachdb/cockroach/issues/131005.

Epic: none
Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131093)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[`pkg/storage/pebble_mvcc_scanner.go` line 890 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131093#-O7UjHHR6-8tnAsMnx1l:-O7UjHHSCbP4CBHu479T:b10m5jq) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fae54ee58a6e31db6106d80087f9b0ecd1694b4/pkg/storage/pebble_mvcc_scanner.go#L890)):*
> ```Go
> 				p.mostRecentKey = append(p.mostRecentKey, p.curUnsafeKey.Key...)
> 			}
> 			// We don't have to fall through to `p.checkUncertainty` because FIXME.
> ```

We don't have to fall through to `p.checkUncertainty` because we are already considering any key that is more recent to be a write-write conflict which will cause a write-too-old error to be thrown. Uncertainty checks are only needed if we would otherwise ignore keys that are more recent.

Here, we could return a WriteTooOld error immediately, but we defer that through `mostRecentTS` so that we return the maximum conflicting timestamp. We are trying to do the same thing below in `processRangeKeys`, but notice that there's no early return in the `p.failOnMoreRecent` case (we don't want an early return, but a `continue` or an `else if` would work). As a result, the deferred-but-preferred error case loses out to the immediate-but-less-preferred case.

This does raise the question of whether we should actually make `p.failOnMoreRecent` and `p.checkUncertainty` mutually exclusive. We could set `checkUncertainty` to false when `failOnMoreRecent` is set to true, so that we don't need to rely on the logic in each of these functions getting it right. This would be easy to do in `pebbleMVCCScanner.init` when setting `checkUncertainty`.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131093)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/storage/pebble_mvcc_scanner.go` line 890 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131093#-O7UjHHR6-8tnAsMnx1l:-O7cMCnPEvI4JcqxE7_n:bz9oi0r) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fae54ee58a6e31db6106d80087f9b0ecd1694b4/pkg/storage/pebble_mvcc_scanner.go#L890)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We don't have to fall through to `p.checkUncertainty` because we are already considering any key that is more recent to be a write-write conflict which will cause a write-too-old error to be thrown. Uncertainty checks are only needed if we would otherwise ignore keys that are more recent.

Here, we could return a WriteTooOld error immediately, but we defer that through `mostRecentTS` so that we return the maximum conflicting timestamp. We are trying to do the same thing below in `processRangeKeys`, but notice that there's no early return in the `p.failOnMoreRecent` case (we don't want an early return, but a `continue` or an `else if` would work). As a result, the deferred-but-preferred error case loses out to the immediate-but-less-preferred case.

This does raise the question of whether we should actually make `p.failOnMoreRecent` and `p.checkUncertainty` mutually exclusive. We could set `checkUncertainty` to false when `failOnMoreRecent` is set to true, so that we don't need to rely on the logic in each of these functions getting it right. This would be easy to do in `pebbleMVCCScanner.init` when setting `checkUncertainty`.
</blockquote></details>

Done. I still need to add a test.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131093)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/storage/pebble_mvcc_scanner.go` line 890 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131093#-O7UjHHR6-8tnAsMnx1l:-O7cP08X9LcftwTulujU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fae54ee58a6e31db6106d80087f9b0ecd1694b4/pkg/storage/pebble_mvcc_scanner.go#L890)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Done. I still need to add a test.
</blockquote></details>

Done.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131093#-:-O7dZsA46ICpaT29YOSd:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @tbg)

**Comment by tbg** [comment]
bors r+
TFTR!

**Comment by tbg** [comment]
> /github-actions-runner/_work/_temp/76ea3ede-7a2b-4587-9cc3-dbbe871ca2b7.sh: line 1: ./build/github/summarize-build.sh: No such file or directory

🤷🏽 

bors r+

**Comment by arulajmani** [comment]
bors retry

**Comment by tbg** [comment]
blathers backport 24.2

**Comment by tbg** [comment]
blathers backport 24.1

**Comment by tbg** [comment]
blathers backport 23.1

**Comment by arulajmani** [comment]
blathers backport 23.2

**Pull request merged**
