### PR TITLE
build: speed up nightly stress jobs

### PR DESCRIPTION
**Pull request by benesch**
As discussed on Slack. See individual commit messages for details.

### CODE REVIEW

**Review by bdarnell — APPROVED** [review]

**Comment by benesch** [comment]
bors r=bdarnell

**Comment by benesch** [comment]
bors r=bdarnell

(I amended the `chmod +x` to the wrong commit.)

**Comment by benesch** [comment]
bors r=bdarnell

**Comment by benesch** [comment]
bors r=bdarnell

**Pull request merged**
