### PR TITLE
storage: remove older migrations

### PR DESCRIPTION
**Pull request by spencerkimball**
Both of these migrations are safe to remove for v2.2.

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
This is missing a few parts of the leaked raft entries migration. For instance, we can now get rid of `localRemovedLeakedRaftEntriesSuffix`. I'd take a look at a05ee7bf97580556544c061b228477013c2200d5 and make sure we remove pretty much everything there that isn't still useful.

@tschottdorf should sign off on the legacy tombstone migration and confirm that this is the full extent of removing that migration.

**Comment by spencerkimball** [comment]
Yes, sorry, was rushing to get this sent out. I've updated the PR with the unused stuff now removed.

**Review by bdarnell — APPROVED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31828)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/keys/constants.go, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31828#-LPg7Lwn1FzHHll68rcB:-LPg7Lwo0vScFPy5ALfx:b6nczpx) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ee3e10883c716c0831af6eefb729afc85dadbe4/pkg/keys/constants.go#L82)):*
> ```Go
> 	// its migration to remove all possibly-leaked Raft entries.
> 	// TODO(nvanbenschoten): This can be removed in 2.2.
> 	localRemovedLeakedRaftEntriesSuffix = []byte("dlre")
> ```

I think this constant should stick around forever to make sure we don't accidentally reuse it.
___
*[pkg/storage/store.go, line 291 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31828#-LPg7d-05KyWQoBnOcN1:-LPg7d-05KyWQoBnOcN2:b6lqek0) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ee3e10883c716c0831af6eefb729afc85dadbe4/pkg/storage/store.go#L291)):*
> ```Go
> // InOrder tells the visitor to visit replicas in increasing RangeID order.
> func (rs *storeReplicaVisitor) InOrder() *storeReplicaVisitor {
> 	rs.ordered = true
> ```

Can the `ordered` field be removed now too? Alternately, keep `InOrder()` around in case we need it in the future, even if we're not using it at the moment.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31828#-:-LPgGci3AlY1lkYEkAjO:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/keys/constants.go, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31828#-LPg7Lwn1FzHHll68rcB:-LPgGOTBCp7kM0BUWf_O:bf9c3ix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ee3e10883c716c0831af6eefb729afc85dadbe4/pkg/keys/constants.go#L82)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I think this constant should stick around forever to make sure we don't accidentally reuse it.
</blockquote></details>

That's a good point. We did the same thing with `LocalRangeFrozenStatusSuffix`.
___
*[pkg/storage/store.go, line 291 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31828#-LPg7d-05KyWQoBnOcN1:-LPgGVeu60smHSi-zpIj:b-nclbis) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ee3e10883c716c0831af6eefb729afc85dadbe4/pkg/storage/store.go#L291)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Can the `ordered` field be removed now too? Alternately, keep `InOrder()` around in case we need it in the future, even if we're not using it at the moment.
</blockquote></details>

Yeah, I think it's worth keeping this around.

**Review by spencerkimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31828)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/keys/constants.go, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31828#-LPg7Lwn1FzHHll68rcB:-LPgTfdT0np6VnT-j6Ig:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ee3e10883c716c0831af6eefb729afc85dadbe4/pkg/keys/constants.go#L82)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

That's a good point. We did the same thing with `LocalRangeFrozenStatusSuffix`.
</blockquote></details>

Done.
___
*[pkg/storage/store.go, line 291 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31828#-LPg7d-05KyWQoBnOcN1:-LPgUrsv5jiUlM7eTzXB:b-88j5k8) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ee3e10883c716c0831af6eefb729afc85dadbe4/pkg/storage/store.go#L291)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yeah, I think it's worth keeping this around.
</blockquote></details>

OK, added it back and added to the replica visitor unittest so that this is tested and not marked as unused by the linter.

**Pull request merged**
