### PR TITLE
sql/server/ui: Use summarized statement formats on Sessions and Transactions pages

### PR DESCRIPTION
**Pull request by lindseyjin**
Resolves #71730

Previously, we implemented new statement summaries (for SELECT,
INSERT/UPSERT, and UPDATE statement types) to be used on the Statements
page to provide more detail and reduce ambiguity between short
statements.

For consistency's sake, we are also going to default to using these
summarized formats on the Sessions and Transactions pages. For Sessions,
this change involves adding a new field "sql_summary", to the active
queries proto so that it can be passed to the front-end. For
Transactions, instead of showing all the query text concatenated as
the label, we now show all the query summary text concatenated.

Sessions page
image
Screen Shot 2021-10-21 at 2 07 26 PM

Transactions page
image

Additionally, we now show "Mean Rows Written" as a metric on the
Statement Details page for all statement types, including SELECT
statements, since we realized there's an edge case where SELECT
statements that embed INSERT statements may still modify rows.

Release note (ui change): Use new summarized formats for SELECT,
INSERT/UPSERT, and UPDATE statements on the Sessions and Transaction
pages, to be consistent with the Statements page. Show "Mean rows
written" as a metric for all statement types on the Statements page,
instead of hiding this metric for SELECT statements.

### CODE REVIEW

**Review by lindseyjin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71817)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx, line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71817#-MmYe45H2hSk1-uhcrMu:-MmYe45H2hSk1-uhcrMv:b-o672ng) ([raw file](https://github.com/cockroachdb/cockroach/blob/323250da545166fbdd21567a3453cd47457e9d61/pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx#L115)):*
> ```XML
>     } = this.props;
>     // don't show rows written if every statement is a select statement.
>     const showRowsWritten = statements.some(
> ```

Added this in for consistency, since I realized we were hiding "Mean Rows Written" on the Statements Details page for SELECT statements, but not on the Transaction Details page. But let me know if this change is unnecessary, or if I should be putting it into a different PR!
___
*[pkg/ui/workspaces/cluster-ui/src/transactionsPage/utils.ts, line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71817#-MmYeQCN-ymdTLJc6JIa:-MmYeQCN-ymdTLJc6JIb:b-p9tsp) ([raw file](https://github.com/cockroachdb/cockroach/blob/323250da545166fbdd21567a3453cd47457e9d61/pkg/ui/workspaces/cluster-ui/src/transactionsPage/utils.ts#L84)):*
> ```XML
> 
> // Combine all statement summaries into a string.
> export const aggregateStatementSummaries = (
> ```

Expand above function for context.

This is basically the same as the old function we were using, but now we concatenate all the query summary strings instead of the original queries.

**Review by lindseyjin — COMMENTED** [review]
Question: now that we've replaced the statement on the Sessions page with the statement summary instead, do we also want to show a tooltip with the full statement if user hover over it?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71817#-:-MmYf8Ws5whI4MCWKR9T:bsuxz57)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by maryliag — COMMENTED** [review]
Good idea! Add the tooltip so it's consistent with other pages

> Reviewed 7 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71817#-:-MmYnQcLC84wKwvcRjDk:b-6iobj0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lindseyjin and @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx, line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71817#-MmYe45H2hSk1-uhcrMu:-MmYnyDsB5zFS62HJ3kx:b40sxar) ([raw file](https://github.com/cockroachdb/cockroach/blob/323250da545166fbdd21567a3453cd47457e9d61/pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx#L115)):*
<details><summary><i>Previously, lindseyjin (Lindsey Jin) wrote…</i></summary><blockquote>

Added this in for consistency, since I realized we were hiding "Mean Rows Written" on the Statements Details page for SELECT statements, but not on the Transaction Details page. But let me know if this change is unnecessary, or if I should be putting it into a different PR!
</blockquote></details>

good change!
___
*[pkg/ui/workspaces/cluster-ui/src/util/sql/summarize.ts, line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71817#-MmYoORKB0leIQlSC70K:-MmYoORKB0leIQlSC70L:b-g7g9zj) ([raw file](https://github.com/cockroachdb/cockroach/blob/323250da545166fbdd21567a3453cd47457e9d61/pkg/ui/workspaces/cluster-ui/src/util/sql/summarize.ts#L65)):*
> ```XML
> ): string {
>   // previous way of summarizing statements with regex.
>   const oldSummary = summarize(statement);
> ```

we probably need a better name here, since oldSummary doesn't make it clear what is the difference between this and the new summary

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71817)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @lindseyjin, and @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71817#-MmYhlBX7Rd8f6xUamG8:-MmYhlBY08wGSmH_hgvR:b-1v8khx) ([raw file](https://github.com/cockroachdb/cockroach/blob/323250da545166fbdd21567a3453cd47457e9d61/pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx#L114)):*
> ```XML
>       nodeRegions,
>     } = this.props;
>     // don't show rows written if every statement is a select statement.
> ```

super nit: `s/don't/Don't/`
___
*[pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx, line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71817#-MmYe45H2hSk1-uhcrMu:-MmYjLFE62OSjBOd6zDb:b-g62j2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/323250da545166fbdd21567a3453cd47457e9d61/pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx#L115)):*
<details><summary><i>Previously, lindseyjin (Lindsey Jin) wrote…</i></summary><blockquote>

Added this in for consistency, since I realized we were hiding "Mean Rows Written" on the Statements Details page for SELECT statements, but not on the Transaction Details page. But let me know if this change is unnecessary, or if I should be putting it into a different PR!
</blockquote></details>

Hmm, IIUC, it seems like this is using regex to see if this the statement is a `SELECT` statements. If so, then it will hide the mean rows written stats. 

However, come complicated CTE query can come along and embeds both INSERT and SELECT, and currently we don't have a good way of detecting those. I think this problem currently also exists for Statement Detail Page, :thinking: , 

@maryliag do you think we should just proceed our current approach? Or we need to invest some resources in figuring out how do we categorize CTEs ? 
___
*[pkg/ui/workspaces/cluster-ui/src/transactionsPage/utils.ts, line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71817#-MmYeQCN-ymdTLJc6JIa:-MmYi-Ts69ijnWtYdsG5:b-fzw8sm) ([raw file](https://github.com/cockroachdb/cockroach/blob/323250da545166fbdd21567a3453cd47457e9d61/pkg/ui/workspaces/cluster-ui/src/transactionsPage/utils.ts#L84)):*
<details><summary><i>Previously, lindseyjin (Lindsey Jin) wrote…</i></summary><blockquote>

Expand above function for context.

This is basically the same as the old function we were using, but now we concatenate all the query summary strings instead of the original queries. 
</blockquote></details>

minor nit: seems like we are more doing a `lookup` than `aggregation` ? perhaps something like `statementFingerprintIdsToSummarizedText` 
___
*[pkg/ui/workspaces/cluster-ui/src/transactionsTable/transactionsCells/transactionsCells.tsx, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71817#-MmYlS3F7pre94b-mlSz:-MmYlS3F7pre94b-mlT-:b-t5blmp) ([raw file](https://github.com/cockroachdb/cockroach/blob/323250da545166fbdd21567a3453cd47457e9d61/pkg/ui/workspaces/cluster-ui/src/transactionsTable/transactionsCells/transactionsCells.tsx#L52)):*
> ```XML
>         <div className={textWrapper}>
>           <div onClick={onClick} className={hoverAreaClassName}>
>             {getHighlightedText(limitText(summary, 200), search, false, true)}
> ```

nit: do you mind add in some inline comment on the boolean literals? e.g. `false /* some param names */,`
___
*[pkg/ui/workspaces/cluster-ui/src/util/sql/summarize.ts, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71817#-MmYnekV0YK1lXmA0zCy:-MmYnekV0YK1lXmA0zCz:b-wkh98x) ([raw file](https://github.com/cockroachdb/cockroach/blob/323250da545166fbdd21567a3453cd47457e9d61/pkg/ui/workspaces/cluster-ui/src/util/sql/summarize.ts#L60)):*
> ```XML
> }
> 
> export function getStmtSummary(
> ```

Hmm I feel this function name might be slightly misleading. Reading through the function, it seems like we check that if the statement is DML, then we go ahead use the new code summary format, else we compute the old summary format.

`getStmtSummary` was a bit confusing especially given the two parameters here

**Review by lindseyjin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71817)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @lindseyjin, and @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx, line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71817#-MmYhlBX7Rd8f6xUamG8:-MmYvCSe8wSdLtAbF0Ut:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/323250da545166fbdd21567a3453cd47457e9d61/pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx#L114)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

super nit: `s/don't/Don't/`
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/cluster-ui/src/transactionsPage/utils.ts, line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71817#-MmYeQCN-ymdTLJc6JIa:-MmYvF3qEHXPmuqjhCm_:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/323250da545166fbdd21567a3453cd47457e9d61/pkg/ui/workspaces/cluster-ui/src/transactionsPage/utils.ts#L84)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

minor nit: seems like we are more doing a `lookup` than `aggregation` ? perhaps something like `statementFingerprintIdsToSummarizedText` 
</blockquote></details>

Done!
___
*[pkg/ui/workspaces/cluster-ui/src/transactionsTable/transactionsCells/transactionsCells.tsx, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71817#-MmYlS3F7pre94b-mlSz:-MmYvHle7qWhyokT17Hd:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/323250da545166fbdd21567a3453cd47457e9d61/pkg/ui/workspaces/cluster-ui/src/transactionsTable/transactionsCells/transactionsCells.tsx#L52)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

nit: do you mind add in some inline comment on the boolean literals? e.g. `false /* some param names */,`
</blockquote></details>

Done!
___
*[pkg/ui/workspaces/cluster-ui/src/util/sql/summarize.ts, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71817#-MmYnekV0YK1lXmA0zCy:-MmYvJ0Z5UbTRRUEJM2w:b-67hq3l) ([raw file](https://github.com/cockroachdb/cockroach/blob/323250da545166fbdd21567a3453cd47457e9d61/pkg/ui/workspaces/cluster-ui/src/util/sql/summarize.ts#L60)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm I feel this function name might be slightly misleading. Reading through the function, it seems like we check that if the statement is DML, then we go ahead use the new code summary format, else we compute the old summary format.

`getStmtSummary` was a bit confusing especially given the two parameters here 
</blockquote></details>

hmm, does this function name work better?
___
*[pkg/ui/workspaces/cluster-ui/src/util/sql/summarize.ts, line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71817#-MmYoORKB0leIQlSC70K:-MmYvLkE2CpskWWwJmP7:b38jqfh) ([raw file](https://github.com/cockroachdb/cockroach/blob/323250da545166fbdd21567a3453cd47457e9d61/pkg/ui/workspaces/cluster-ui/src/util/sql/summarize.ts#L65)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

we probably need a better name here, since oldSummary doesn't make it clear what is the difference between this and the new summary
</blockquote></details>

Is this variable name better?

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71817)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @lindseyjin, and @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/transactionsTable/transactionsCells/transactionsCells.tsx, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71817#-MmYlS3F7pre94b-mlSz:-MmYxvvA3x1wNGlVa2ND:bwuv9up) ([raw file](https://github.com/cockroachdb/cockroach/blob/323250da545166fbdd21567a3453cd47457e9d61/pkg/ui/workspaces/cluster-ui/src/transactionsTable/transactionsCells/transactionsCells.tsx#L52)):*
<details><summary><i>Previously, lindseyjin (Lindsey Jin) wrote…</i></summary><blockquote>

Done!
</blockquote></details>

Nice! 
___
*[pkg/ui/workspaces/cluster-ui/src/util/sql/summarize.ts, line 60 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71817#-MmYnekV0YK1lXmA0zCy:-MmYxyNh0qSlt9-u7vUa:bx87e1l) ([raw file](https://github.com/cockroachdb/cockroach/blob/323250da545166fbdd21567a3453cd47457e9d61/pkg/ui/workspaces/cluster-ui/src/util/sql/summarize.ts#L60)):*
<details><summary><i>Previously, lindseyjin (Lindsey Jin) wrote…</i></summary><blockquote>

hmm, does this function name work better?
</blockquote></details>

Definitely better! :+1:

**Review by lindseyjin — COMMENTED** [review]
Done, and I've added a screenshot to the PR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71817#-:-MmZ1vAF-cdOcOP7V2NM:b-h3bv49)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @lindseyjin, and @maryliag)

**Review by lindseyjin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71817)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @lindseyjin, and @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx, line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71817#-MmYe45H2hSk1-uhcrMu:-Mm_05g-0PdqgdOQc9ew:b-r7uq1e) ([raw file](https://github.com/cockroachdb/cockroach/blob/323250da545166fbdd21567a3453cd47457e9d61/pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx#L115)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm, IIUC, it seems like this is using regex to see if this the statement is a `SELECT` statements. If so, then it will hide the mean rows written stats. 

However, come complicated CTE query can come along and embeds both INSERT and SELECT, and currently we don't have a good way of detecting those. I think this problem currently also exists for Statement Detail Page, :thinking: , 

@maryliag do you think we should just proceed our current approach? Or we need to invest some resources in figuring out how do we categorize CTEs ? 
</blockquote></details>

I've added in some test cases for the regex to check that it can identify query types. I tried throwing in some basic queries and a few more advanced ones, but let me know if you can think of more complicated queries that I haven't covered! 

Since we scan the statements one by one and check if they match the regex starting with SELECT, I think that all statements that we identify to be SELECT statements will be correct, although we might not catch all SELECT statements? 

eg) If there's a select statement starting with a WITH clause, we may not be able to identify that as a SELECT statement and we'l show the "Mean Rows Written" metric. However, I can't think of any counterexamples of complete SQL queries that match the SELECT regex but aren't select statements, although correct me if I'm wrong.

**Review by lindseyjin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71817)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @lindseyjin, and @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx, line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71817#-MmYe45H2hSk1-uhcrMu:-MmcbX6z6vH6FCbhKSyZ:b2lsh1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/323250da545166fbdd21567a3453cd47457e9d61/pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx#L115)):*
<details><summary><i>Previously, lindseyjin (Lindsey Jin) wrote…</i></summary><blockquote>

I've added in some test cases for the regex to check that it can identify query types. I tried throwing in some basic queries and a few more advanced ones, but let me know if you can think of more complicated queries that I haven't covered! 

Since we scan the statements one by one and check if they match the regex starting with SELECT, I think that all statements that we identify to be SELECT statements will be correct, although we might not catch all SELECT statements? 

eg) If there's a select statement starting with a WITH clause, we may not be able to identify that as a SELECT statement and we'l show the "Mean Rows Written" metric. However, I can't think of any counterexamples of complete SQL queries that match the SELECT regex but aren't select statements, although correct me if I'm wrong.
</blockquote></details>

Nvm, you're right! If I run the example: `SELECT * FROM [INSERT INTO t VALUES (1) RETURNING i];`, that gets classified as a SELECT statement, although it still modifies rows.

I can't really think of a good solution around this using regex. One thing we could try is hiding "Mean Rows Written" only for SELECT statements that also haven't modified any rows? Although that seems a bit hacky.

I'll follow up with Kevin on whether we can just show the "Mean Rows Written" metric for all statements types anyways. Might be better for the sake of consistency?

**Review by lindseyjin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71817)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng, @lindseyjin, and @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx, line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71817#-MmYe45H2hSk1-uhcrMu:-Mmd34Q8EEvB5yH26fEe:b7mdtnw) ([raw file](https://github.com/cockroachdb/cockroach/blob/323250da545166fbdd21567a3453cd47457e9d61/pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx#L115)):*
<details><summary><i>Previously, lindseyjin (Lindsey Jin) wrote…</i></summary><blockquote>

Nvm, you're right! If I run the example: `SELECT * FROM [INSERT INTO t VALUES (1) RETURNING i];`, that gets classified as a SELECT statement, although it still modifies rows.

I can't really think of a good solution around this using regex. One thing we could try is hiding "Mean Rows Written" only for SELECT statements that also haven't modified any rows? Although that seems a bit hacky.

I'll follow up with Kevin on whether we can just show the "Mean Rows Written" metric for all statements types anyways. Might be better for the sake of consistency?
</blockquote></details>

Follow up: Talked to Kevin and he said it was fine if we just show "Mean Rows Written" for all statements instead of hiding them for SELECT statements, unless y'all have any suggestions on a good way to implement that

**Review by maryliag — APPROVED** [review]
Looks great!
:lgtm: 

> Reviewed 5 of 8 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71817#-:-MmrbxHA5IxcookOMrWR:bql1rwv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lindseyjin)

___
*[pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx, line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71817#-MmYe45H2hSk1-uhcrMu:-MmrbQMR3SuqfmZdz32z:b-2gv9is) ([raw file](https://github.com/cockroachdb/cockroach/blob/323250da545166fbdd21567a3453cd47457e9d61/pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx#L115)):*
<details><summary><i>Previously, lindseyjin (Lindsey Jin) wrote…</i></summary><blockquote>

Follow up: Talked to Kevin and he said it was fine if we just show "Mean Rows Written" for all statements instead of hiding them for SELECT statements, unless y'all have any suggestions on a good way to implement that
</blockquote></details>

sounds good, let's keep showing Mean Rows for all cases
___
*[pkg/ui/workspaces/cluster-ui/src/util/sql/summarize.ts, line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71817#-MmYoORKB0leIQlSC70K:-MmZKECuAH7AQHAwtRji:b-sr8b0r) ([raw file](https://github.com/cockroachdb/cockroach/blob/323250da545166fbdd21567a3453cd47457e9d61/pkg/ui/workspaces/cluster-ui/src/util/sql/summarize.ts#L65)):*
<details><summary><i>Previously, lindseyjin (Lindsey Jin) wrote…</i></summary><blockquote>

Is this variable name better?
</blockquote></details>

better

**Review by Azhng — APPROVED** [review]
:fire:

**Pull request merged**
