### PR TITLE
backupccl: deflake backup tests

### PR DESCRIPTION
**Pull request by adityamaru**
See individual commits.

Release note: None

### CODE REVIEW

**Review by msbutler — APPROVED** [review]
Thanks for doing this!

Are there any more unit tests we need to unskip? If so, I think we should create a stability tracking issue for the remaining ones.

**Comment by adityamaru** [comment]
I've been using https://roachdash.crdb.dev/?filter=status%3Aopen+l%3Askipped-test+*skipped+r%3Acockroachdb%2Fcockroach&group=project&sort=-lastcommented&restgroup=true&display=project+category+lastorigin+lastcommented to find skipped test. There are a few more left which we should be able to see more clearly once all these issues close.

bors r=msbutler

**Comment by msbutler** [comment]
heh, didn't realize roachdash existed.

**Comment by adityamaru** [comment]
blathers backport release-22.2

**Pull request merged**
