### PR TITLE
roachtest: add AWS-specific tpcc/nodes=3/w=max test

### PR DESCRIPTION
**Pull request by nvb**

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
I'm still confirming that 2200 warehouses is the right number for this.

**Comment by nvanbenschoten** [comment]
Bumping this to 2300. The latencies are very good on `master` with 2200 warehouses:
```
_elapsed___errors__ops/sec(inst)___ops/sec(cum)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
  30m45s        0           67.3           46.9    134.2    369.1    419.4    486.5 delivery
  30m45s        0          553.3          466.7    121.6    243.3    302.0    385.9 newOrder
  30m45s        0           41.2           47.1      8.9     27.3     48.2     48.2 orderStatus
  30m45s        0          540.2          469.9     92.3    218.1    302.0    436.2 payment
  30m45s        0           53.2           47.0     56.6    104.9    130.0    159.4 stockLevel
```

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35287#-:-LZrEWXr7l21Cna-pGb_:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by nvanbenschoten** [comment]
2300 warehouses looks good. We're still at a very comfortable latency, but we're starting to get close to where we see it shoot up:
```
_elapsed___errors__ops/sec(inst)___ops/sec(cum)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
1h37m41s        0           43.0           48.9    436.2    973.1   2281.7   2281.7 delivery
1h37m41s        0          400.1          488.0    335.5    604.0    704.6    738.2 newOrder
1h37m41s        0           45.0           48.9     27.3     88.1    121.6    121.6 orderStatus
1h37m41s        0          406.1          489.1    285.2    469.8    604.0   1073.7 payment
1h37m41s        0           50.0           48.9    100.7    192.9    209.7    209.7 stockLevel
```

All nodes are also hovering around 80% of cpu. We could probably push this further, but let's let this warehouse count stabilize first.

**Pull request merged**
