### PR TITLE
crosscluster/logical: add job ID to application name

### LINKED ISSUE #127746: crosscluster/logical: include job_id or table name in replication application name
It would be nice to be able to quickly identify which sql activity entries were for which stream.

Jira issue: CRDB-40581

### PR DESCRIPTION
**Pull request by stevendanna**
The goal of this change is to make it a bit easier to identify the queries for a particular job on the SQL activity page.

Fixes #127746

Release note: None

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
lgtm! should we backport this?

**Comment by stevendanna** [comment]
bors r=msbutler

**Comment by stevendanna** [comment]
bors r=rafiss

**Comment by stevendanna** [comment]
bors cancel

**Comment by stevendanna** [comment]
bors r=rafiss

**Pull request merged**
