### PR TITLE
sql: clarify SQL instance IDs in misc observability code

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit renames "Nodes" into "SQLInstanceIDs" when it pertains StatementStatistics (i.e. "app stats"). The following changes are made:
- `exec_node_ids` column of a few virtual tables is renamed into `sql_instance_ids`
- in `appstatspb.StatementStatistics` proto we begin deprecating `Nodes []int64` field in favor of `SQLInstanceIDs []int32`. This allows us to remove some type conversions since instance IDs are int32.
  - lots of places in the DB Console code is updated accordingly.
    TODO(check with reviewers): how can we make this backwards-compatible?
- ditto for `insights.Statement` proto where we begin deprecating `Nodes []int64` in favor of `SQLInstanceIDs []int32`.

Informs: #91774.
Epic: None.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Note that some of the changes will make it so that `Nodes` attribute on SQL Activity pages would be empty in mixed-version state. I outlined what I observed [here](https://github.com/cockroachdb/cockroach/pull/124681#pullrequestreview-2086473466).

**Review by dhartunian — CHANGES_REQUESTED** [review]
> Note that some of the changes will make it so that `Nodes` attribute on SQL Activity pages would be empty in mixed-version state. I outlined what I observed [here](https://github.com/cockroachdb/cockroach/pull/124681#pullrequestreview-2086473466).

@yuzefovich isn't it a bit worse than that: persisted stats prior to upgrade will no longer show node info because it won't get decoded correctly. you'll have to wait for new stats to be collected post-upgrade to see data.

We have a new mixed-version sql stats roachtest that could catch problems like this: `"sql-stats/mixed-version"`

Is there a reason we can't have this new field be additive and file an issue to deprecate `Nodes`?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124833#-:-NzU8wRR0gpr0SYAhYnX:b-ktstiz)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz and @yuzefovich)

___
*[`pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding_test.go` line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124833#-NzUBwpx4wkdTxF6q2lo:-NzUBwpx4wkdTxF6q2lp:b-vl91rj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8542508040bdbe6ebf19ad0b89f6ff1015946c85/pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding_test.go#L103)):*
> ```Go
>            "sqDiff": {{.Float}}
>          },
>          "sqlInstanceIds": [{{joinInt32s .Int32Array}}],
> ```

I'd expect to see test cases here with this field intact and with the new field showing that decoding works successfully with both.

**Comment by xinhaoz** [comment]
*[`pkg/ui/workspaces/cluster-ui/src/queryFilter/filter.tsx` line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124833#-NzUCWU17nGyXz6TTVEx:-NzUCWU17nGyXz6TTVEy:bx5hwhs) ([raw file](https://github.com/cockroachdb/cockroach/blob/8542508040bdbe6ebf19ad0b89f6ff1015946c85/pkg/ui/workspaces/cluster-ui/src/queryFilter/filter.tsx#L77)):*
> ```XML
>   fullScan?: boolean;
>   regions?: string;
>   // TODO: should this be renamed?
> ```

Do want to change the user visible labelling of 'Node(s)' for sql stats in db console to `SQL Instance ID` too? I can create a follow-up issue for that if so. There are a number of places in the code where we're referencing this field as 'node' or similar.

**Review by yuzefovich — COMMENTED** [review]
> persisted stats prior to upgrade will no longer show node info because it won't get decoded correctly. you'll have to wait for new stats to be collected post-upgrade to see data

Yes, that's my understanding too. All already collected stmt stats won't be able to show `Nodes` attribute on newer binaries, and newly collected stats won't show it on the older binaries.

> Is there a reason we can't have this new field be additive and file an issue to deprecate `Nodes`?

Do you mean having both `Nodes` and `SQLInstanceIDs` fields present while compatibility with 24.1 is needed? Yeah, we can do that. What changes should be applied to typescript code then so that we attempt to access `SqlInstanceIds` first, and if that's unavailable, then `Nodes`?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124833#-:-NzZef784IiywfHevqPg:by31izk)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/queryFilter/filter.tsx` line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124833#-NzUCWU17nGyXz6TTVEx:-NzZkuFK7PJz0Dss_cRJ:bkjr5nc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8542508040bdbe6ebf19ad0b89f6ff1015946c85/pkg/ui/workspaces/cluster-ui/src/queryFilter/filter.tsx#L77)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Do want to change the user visible labelling of 'Node(s)' for sql stats in db console to `SQL Instance ID` too? I can create a follow-up issue for that if so. There are a number of places in the code where we're referencing this field as 'node' or similar.
</blockquote></details>

I'm not sure whether we expose "SQL instance" as a concept anywhere (apart from serverless), so I think that user-facing things could remain "nodes". I care about differentiating SQL instance IDs vs KV node IDs in the code, mostly on backend, so I'll leave further renaming to you.

**Comment by yuzefovich** [comment]
I don't feel too strongly about this, will let observability team to do this if they care.

**Pull request closed without merging**
