### PR TITLE
server: windows builds do not need to set file descriptors limits

### LINKED ISSUE #14437: server: syscall.{Rlimit,{Get,Set}rlimit} not available on windows
See https://github.com/cockroachdb/cockroach/blob/c15aa90/pkg/server/config.go#L281:L369.

### PR DESCRIPTION
**Pull request by BramGruneir**
Fixes #14437 

cc: @jseldess

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14447)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/server/config_unix.go, line 14 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14447#-KgQAnBg92IFHydmA-71:-KgQAnBg92IFHydmA-72:bjf9c6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/1362c77f3ced9203802baa61fb05d1e3b64d92d2/pkg/server/config_unix.go#L14)):*
> ```Go
> // implied. See the License for the specific language governing
> // permissions and limitations under the License.
> //
> ```

blank out this line - the build tag is not part of this comment.

also, you don't need this build tag at all because of the _unix on the file name.

---

*[pkg/server/config_windows.go, line 15 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14447#-KgQAtFZRlmQG329nL26:-KgQAtFZRlmQG329nL27:bpb4dnh) ([raw file](https://github.com/cockroachdb/cockroach/blob/1362c77f3ced9203802baa61fb05d1e3b64d92d2/pkg/server/config_windows.go#L15)):*
> ```Go
> // permissions and limitations under the License.
> //
> // +build windows
> ```

see other comment; remove this and the preceding line.

---

*[pkg/server/config_windows.go, line 23 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14447#-KgQAy3S_Fq9AwQISLiI:-KgQAy3S_Fq9AwQISLiJ:b-ahotgz) ([raw file](https://github.com/cockroachdb/cockroach/blob/1362c77f3ced9203802baa61fb05d1e3b64d92d2/pkg/server/config_windows.go#L23)):*
> ```Go
> )
> 
> // setOpenFileLimit on windows does not need to change the file descriptor,
> ```

I think you should have a separate `inner` function so that you can stick this comment on it. I believe godoc will show documentation only for the current build tags, so we want doc comments like this somewhere that builds on all platforms.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14447)*

**Comment by tamird** [comment]
This commit message is quite anemic; consider including in in the justification you have included in the new windows-only comment.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14447#-:-KgQBGv8JvGogEvm1PhC:bd9s3v0)*

**Comment by BramGruneir** [comment]
Update the commit message as well.

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/server/config_unix.go, line 14 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14447#-KgQAnBg92IFHydmA-71:-KgQJNEe0RS1IYznOwsm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1362c77f3ced9203802baa61fb05d1e3b64d92d2/pkg/server/config_unix.go#L14)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

blank out this line - the build tag is not part of this comment.

also, you don't need this build tag at all because of the _unix on the file name.
</blockquote></details>

Done.

---

*[pkg/server/config_windows.go, line 15 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14447#-KgQAtFZRlmQG329nL26:-KgQJNoj_kD5tcpzPj0t:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1362c77f3ced9203802baa61fb05d1e3b64d92d2/pkg/server/config_windows.go#L15)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

see other comment; remove this and the preceding line.
</blockquote></details>

Done.

---

*[pkg/server/config_windows.go, line 23 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14447#-KgQAy3S_Fq9AwQISLiI:-KgQN6kb3d-WVhG7ywe6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1362c77f3ced9203802baa61fb05d1e3b64d92d2/pkg/server/config_windows.go#L23)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I think you should have a separate `inner` function so that you can stick this comment on it. I believe godoc will show documentation only for the current build tags, so we want doc comments like this somewhere that builds on all platforms.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14447#-:-KgQN99J6Q6XQELbm8ZW:b4c4yxf)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/server/config.go, line 273 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14447#-KgQTaXXD7UwPNamEDM6:-KgQTaXYH8TTn1GWRAn8:b-4cwwqb) ([raw file](https://github.com/cockroachdb/cockroach/blob/364ce15777322944a26ce2e243d1fc21846546e4/pkg/server/config.go#L273)):*
> ```Go
> // setOpenFileLimit sets the soft limit for open file descriptors to the hard
> // limit if needed. Returns an error if the hard limit is too low. Returns the
> // value to set maxOpenFiles to for each store. See the appropriate os suffixed
> ```

what details? if they are implementation details, they shouldn't be doc comments. if they document behaviour, just inline it here.

---

*[pkg/server/config.go, line 274 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14447#-KgQTJU1wwFFFqwdfz3T:-KgQTJU1wwFFFqwdfz3U:b-4u597p) ([raw file](https://github.com/cockroachdb/cockroach/blob/364ce15777322944a26ce2e243d1fc21846546e4/pkg/server/config.go#L274)):*
> ```Go
> // limit if needed. Returns an error if the hard limit is too low. Returns the
> // value to set maxOpenFiles to for each store. See the appropriate os suffixed
> // file for more details.
> ```

put an empty comment line between this and the next paragraph, otherwise editors will ignore the line break when automatically re-wrapping.

while you're here, consider adding a blank comment line between each of the items below:

```
// file for more details.
//
// Minimum - 1700 per store, 256 saved for networking
//
// Constrained - 256 saved for networking, rest divided evenly per store
//
// Constrained (network only) - 10000 per store, rest saved for networking
//
// Recommended - 10000 per store, 5000 for network
//
// Also, please note that current and max limits are commonly referred to as
```

---

*[pkg/server/config_unix.go, line 27 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14447#-KgQTExvGlbM4DmNHHPW:-KgQTExwtRQjwyzNx5gg:b-15v7m1) ([raw file](https://github.com/cockroachdb/cockroach/blob/364ce15777322944a26ce2e243d1fc21846546e4/pkg/server/config_unix.go#L27)):*
> ```Go
> )
> 
> // setOpenFileLimitInner contains unix specific system calls in order to get and
> ```

remove this unhelpful comment.

---

*[pkg/server/config_windows.go, line 23 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14447#-KgQAy3S_Fq9AwQISLiI:-KgQSzwWMZZgMekRNPbS:b-9pxw8n) ([raw file](https://github.com/cockroachdb/cockroach/blob/1362c77f3ced9203802baa61fb05d1e3b64d92d2/pkg/server/config_windows.go#L23)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I should have been clearer; this comment should either be inside the function, if it is documenting implementation details, or on `setOpenFileLimit` if it documenting behaviour.

Perhaps it should be broken into two comments.

There is also a typo in "cahnged" here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14447)*

**Comment by BramGruneir** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/server/config.go, line 273 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14447#-KgQTaXXD7UwPNamEDM6:-KgQVomDUaQaMvLoxj77:b-btpbt3) ([raw file](https://github.com/cockroachdb/cockroach/blob/364ce15777322944a26ce2e243d1fc21846546e4/pkg/server/config.go#L273)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

what details? if they are implementation details, they shouldn't be doc comments. if they document behaviour, just inline it here.
</blockquote></details>

I meant implementation.  Fixed the comment.

---

*[pkg/server/config.go, line 274 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14447#-KgQTJU1wwFFFqwdfz3T:-KgQW-d3DK1ohtkaggov:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/364ce15777322944a26ce2e243d1fc21846546e4/pkg/server/config.go#L274)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

put an empty comment line between this and the next paragraph, otherwise editors will ignore the line break when automatically re-wrapping.

while you're here, consider adding a blank comment line between each of the items below:

```
// file for more details.
//
// Minimum - 1700 per store, 256 saved for networking
//
// Constrained - 256 saved for networking, rest divided evenly per store
//
// Constrained (network only) - 10000 per store, rest saved for networking
//
// Recommended - 10000 per store, 5000 for network
//
// Also, please note that current and max limits are commonly referred to as
```
</blockquote></details>

Done.

---

*[pkg/server/config_unix.go, line 27 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14447#-KgQTExvGlbM4DmNHHPW:-KgQUTZ5arIf7rVyh4I_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/364ce15777322944a26ce2e243d1fc21846546e4/pkg/server/config_unix.go#L27)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

remove this unhelpful comment.
</blockquote></details>

Done.

---

*[pkg/server/config_windows.go, line 23 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14447#-KgQAy3S_Fq9AwQISLiI:-KgQV_oStnKF1LgoSfxP:b-xykx3m) ([raw file](https://github.com/cockroachdb/cockroach/blob/1362c77f3ced9203802baa61fb05d1e3b64d92d2/pkg/server/config_windows.go#L23)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I should have been clearer; this comment should either be inside the function, if it is documenting implementation details, or on `setOpenFileLimit` if it documenting behaviour.

Perhaps it should be broken into two comments.

There is also a typo in "cahnged" here.
</blockquote></details>

Fixed the typo and I moved the comment into setOpenFileLimit.  It just seems strange to include OS specific behaviour in the non-os specific function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14447)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/server/config.go, line 273 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14447#-KgQTaXXD7UwPNamEDM6:-KgQX9FCKP6mTz3HGxA-:b6eor52) ([raw file](https://github.com/cockroachdb/cockroach/blob/364ce15777322944a26ce2e243d1fc21846546e4/pkg/server/config.go#L273)):*
> //See the appropriate os suffixed
> // file for implementations.

 Remove this, it isn't helpful.

---

*[pkg/server/config.go, line 287 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14447#-KgQXKHG4--p82LxfFQi:-KgQXKHG4--p82LxfFQj:b-1y03xg) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b64fa0f01d236ddedd0021c65a83a73b6fe51ae/pkg/server/config.go#L287)):*
> ```Go
> // and hard limits respectively.
> //
> // On Windows there is no need to change the file descriptor, known as file
> ```

they're just handles, not file handles.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14447#-:-KgQXVa79VKJPSRgS3P1:bnfp4nl)*

**Comment by BramGruneir** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/server/config.go, line 273 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14447#-KgQTaXXD7UwPNamEDM6:-KgQYJ0hcMETdej5u31W:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/364ce15777322944a26ce2e243d1fc21846546e4/pkg/server/config.go#L273)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

> //See the appropriate os suffixed
> // file for implementations.

 Remove this, it isn't helpful.
</blockquote></details>

Done.

---

*[pkg/server/config.go, line 287 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14447#-KgQXKHG4--p82LxfFQi:-KgQYJo-NZEwYtTKpujd:b-8nmxn9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b64fa0f01d236ddedd0021c65a83a73b6fe51ae/pkg/server/config.go#L287)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

they're just handles, not file handles.
</blockquote></details>

I've heard them referred to as both.  Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14447)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14447)*

**Pull request merged**
