### PR TITLE
 sql: remove tableState -> LeaseManager dependency

### PR DESCRIPTION
**Pull request by vivekmenezes**
This is another refactor required for the LRU cache

### CODE REVIEW

**Review by andreimatei — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28248)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/lease.go, line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJK3B-7Bgdv5Cn5CKTr:-LJK3B-7Bgdv5Cn5CKTs:b-4t0xb3) ([raw file](https://github.com/cockroachdb/cockroach/blob/be1aee52a78cb850d7f3106ed8b3248821ec3c71/pkg/sql/lease.go#L84)):*
> ```Go
> }
> 
> func (s *tableVersionState) String() string {
> ```

if `String` really assumes that the lock is help, name it `StringLocked` (and break the `stringer` interface). But I don't think it should; I think it should take the lock.
Separately, you may also need a private `stringLocked()`
___
*[pkg/sql/lease.go, line 655 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJK6n3S5JNj0d4ZMV68:-LJK6n3S5JNj0d4ZMV69:b-sokhfs) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc75c6b24038aa4f78c749e1354253a91d089de/pkg/sql/lease.go#L655)):*
> ```Go
> }
> 
> // Find the table descriptor valid for the particular timestamp.
> ```

nit: here and elsewhere, our convention is to start method comments with the method name. vet only enforces it for exported methods.
___
*[pkg/sql/lease.go, line 656 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJK5cmy9-a1drJu4VaC:-LJK5cmy9-a1drJu4VaD:bbs9jtj) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc75c6b24038aa4f78c749e1354253a91d089de/pkg/sql/lease.go#L656)):*
> ```
> Normally the latest version of a table descriptor if valid is returned.
> ```

I don't understand what this means, given that this method asks for a ts at a timestamp. Maybe more words would help.
___
*[pkg/sql/lease.go, line 657 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJKBrGZ62lKDaAfv8d6:-LJKBrGZ62lKDaAfv8d7:b-faks95) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc75c6b24038aa4f78c749e1354253a91d089de/pkg/sql/lease.go#L657)):*
> ```
> when a lease doesn't exist of needs renewal.
> ```

What's the difference between a lease "not existing" and "needing renewal"? Just say that the lease, if any, doesn't cover the requested timestamp. "Needing renewal" makes one think of our eager renewal policies.

Also I don't quite understand the distinction between the two errors. Say the `tableState` is empty. How would we know which one of the errors to return?
___
*[pkg/sql/lease.go, line 659 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJK5ziJ6DvEMYzpf6Og:-LJK5ziJ6DvEMYzpf6Oh:b-8itxv7) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc75c6b24038aa4f78c749e1354253a91d089de/pkg/sql/lease.go#L659)):*
> ```Go
> // This returns errRenewLease when a lease doesn't exist of needs renewal.
> // If the valid version doesn't exist errOlderReadTableVersion is returned
> // requesting a higher layer to read the required table version before calling
> ```

s/read the required table/populate the tableState ?
___
*[pkg/sql/lease.go, line 665 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJK5BdPBebTSCj8BPLF:-LJK5BdPBebTSCj8BPLG:bpahi5u) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc75c6b24038aa4f78c749e1354253a91d089de/pkg/sql/lease.go#L665)):*
> ```Go
> func (t *tableState) findForTimestamp(
> 	ctx context.Context, timestamp hlc.Timestamp,
> ) (*tableVersionState, bool, error) {
> ```

nit: a returned bool with these semantics from a `find` function is confusing; one would expect that to be `true` if something was found. I'd suggest returning a struct instead.
Or at least name the return value.
___
*[pkg/sql/lease.go, line 669 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJK6DVG8O1ldg3H4jgs:-LJK6DVG8O1ldg3H4jgt:b-el7ntg) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc75c6b24038aa4f78c749e1354253a91d089de/pkg/sql/lease.go#L669)):*
> ```Go
> 	defer t.mu.Unlock()
> 
> 	// Acquire a lease if no lease exists or if the latest lease is about to
> ```

stale comment?
___
*[pkg/sql/lease.go, line 680 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJK7nU6AFG2aUgMZ7iC:-LJK7nU6AFG2aUgMZ7iD:by0pqp5) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc75c6b24038aa4f78c749e1354253a91d089de/pkg/sql/lease.go#L680)):*
> ```Go
> 	// Walk back the versions to find one that is valid for the timestamp.
> 	for i := len(t.mu.active.data) - 1; i >= 0; i-- {
> 		// Check to see if the ModififcationTime is valid.
> ```

Modififcation
___
*[pkg/sql/lease.go, line 683 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJK7fHr7nEL7JEZGJVq:-LJK7fHr7nEL7JEZGJVr:b-jnohm1) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc75c6b24038aa4f78c749e1354253a91d089de/pkg/sql/lease.go#L683)):*
> ```Go
> 		if table := t.mu.active.data[i]; !timestamp.Less(table.ModificationTime) {
> 			latest := i+1 == len(t.mu.active.data)
> 			if timestamp.Less(table.expiration) {
> ```

use `hasExpired` since you used it above
___
*[pkg/sql/lease.go, line 690 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJK8C9P6jtdt03UymfC:-LJK8C9P6jtdt03UymfD:bjwhkhe) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc75c6b24038aa4f78c749e1354253a91d089de/pkg/sql/lease.go#L690)):*
> ```Go
> 
> 			if latest {
> 				return nil, false, errRenewLease
> ```

isn't this case handled before the loop? Can that code go away?
___
*[pkg/sql/lease.go, line 701 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJKAGAd5zVZI-gap-Uy:-LJKAGAd5zVZI-gap-Uz:blyedy0) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc75c6b24038aa4f78c749e1354253a91d089de/pkg/sql/lease.go#L701)):*
> ```Go
> // Read an older table descriptor version for the particular timestamp
> // from the store. We unfortunately need to read more than one table
> // version just so that we can set the expiration time on the descriptor
> ```

I think it's time we introduce a `Get` that returns all the key's versions. We'd still need to maintain other code for a version for backward compatibility (we'd guard the use of the new operation on a cluster version). Consider it.
___
*[pkg/sql/lease.go, line 703 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJK8jUmEcQtS6SsWFkd:-LJK8jUmEcQtS6SsWFke:b-z084d5) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc75c6b24038aa4f78c749e1354253a91d089de/pkg/sql/lease.go#L703)):*
> ```
> // TODO(vivek): We still do not use this cache for AS OF SYSTEM TIME
> // queries so this implementation is rather complex. Consider simplifying
> // it.
> ```

I don't understand this comment. First of all, either explain or strike the "still".
And then I don't understand if you're saying AOST should use the cache or not. Also I don't understand why AOST is being called out; what's special about AOST queries? 
___
*[pkg/sql/lease.go, line 711 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJKAnhs0M8sSqZPHnJK:-LJKAnhs0M8sSqZPHnJL:b-vibf2o) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc75c6b24038aa4f78c749e1354253a91d089de/pkg/sql/lease.go#L711)):*
> ```Go
> 	expiration, done := func() (hlc.Timestamp, bool) {
> 		t := m.findTableState(tableID, false /* create */)
> 		t.mu.Lock()
> ```

what if `t == nil`?
___
*[pkg/sql/lease.go, line 1464 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJKB0pB-yUN6TnTZfN_:-LJKB0pB-yUN6TnTZfNa:b-u6upo8) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc75c6b24038aa4f78c749e1354253a91d089de/pkg/sql/lease.go#L1464)):*
> ```Go
> ) (*sqlbase.TableDescriptor, hlc.Timestamp, error) {
> 	for {
> 		t := m.findTableState(tableID, true)
> ```

pls comment the `true`. Or take the opportunity to make it an enum.
___
*[pkg/sql/lease.go, line 1525 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJKBPJRBnXg1hxa_di_:-LJKBPJRBnXg1hxa_dia:bmpafwz) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc75c6b24038aa4f78c749e1354253a91d089de/pkg/sql/lease.go#L1525)):*
> ```Go
> }
> 
> func (m *LeaseManager) removeOnceDereferenced() bool {
> ```

pls add a comment

**Review by vivekmenezes — COMMENTED** [review]
TFTR! I'm looking forward to merging this and you looking at the real deal.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-:-LJLJD_r-cn1VC3p4FLH:b-u29pve)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/lease.go, line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJK3B-7Bgdv5Cn5CKTr:-LJKsL8J98BxZYFTGkPQ:b-60r10o) ([raw file](https://github.com/cockroachdb/cockroach/blob/be1aee52a78cb850d7f3106ed8b3248821ec3c71/pkg/sql/lease.go#L84)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

if `String` really assumes that the lock is help, name it `StringLocked` (and break the `stringer` interface). But I don't think it should; I think it should take the lock.
Separately, you may also need a private `stringLocked()`
</blockquote></details>

This actually violates the lock. It has always been this way and we've known about it. Is there a strong reason to not keep it this way. If we're concerned about it we could I suppose get rid of it recording refcount.
___
*[pkg/sql/lease.go, line 656 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJK5cmy9-a1drJu4VaC:-LJKuWsA54qfH5sCM9oS:b-e33khk) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc75c6b24038aa4f78c749e1354253a91d089de/pkg/sql/lease.go#L656)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> ```
> Normally the latest version of a table descriptor if valid is returned.
> ```

I don't understand what this means, given that this method asks for a ts at a timestamp. Maybe more words would help.
</blockquote></details>

I've updated the comment. Part of me feels like deleting the comment I just added :-)
___
*[pkg/sql/lease.go, line 657 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJKBrGZ62lKDaAfv8d6:-LJKyt3-7ikYJ43qyzgJ:b-2hv9v4) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc75c6b24038aa4f78c749e1354253a91d089de/pkg/sql/lease.go#L657)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> ```
> when a lease doesn't exist of needs renewal.
> ```

What's the difference between a lease "not existing" and "needing renewal"? Just say that the lease, if any, doesn't cover the requested timestamp. "Needing renewal" makes one think of our eager renewal policies.

Also I don't quite understand the distinction between the two errors. Say the `tableState` is empty. How would we know which one of the errors to return?


</blockquote></details>

I've reworded the code and the comment to make this more precise.
___
*[pkg/sql/lease.go, line 659 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJK5ziJ6DvEMYzpf6Og:-LJKzF6rEBZX8Vj49_ER:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc75c6b24038aa4f78c749e1354253a91d089de/pkg/sql/lease.go#L659)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

s/read the required table/populate the tableState ?
</blockquote></details>

Done.
___
*[pkg/sql/lease.go, line 665 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJK5BdPBebTSCj8BPLF:-LJKx4FQ3ubWcTRgCPw2:b-2j51dl) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc75c6b24038aa4f78c749e1354253a91d089de/pkg/sql/lease.go#L665)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: a returned bool with these semantics from a `find` function is confusing; one would expect that to be `true` if something was found. I'd suggest returning a struct instead.
Or at least name the return value.
</blockquote></details>

I'm leaving it as is because it will change in the next PR.
___
*[pkg/sql/lease.go, line 669 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJK6DVG8O1ldg3H4jgs:-LJKynFtBEUR-dsARAuo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc75c6b24038aa4f78c749e1354253a91d089de/pkg/sql/lease.go#L669)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

stale comment?
</blockquote></details>

Done.
___
*[pkg/sql/lease.go, line 680 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJK7nU6AFG2aUgMZ7iC:-LJKzKvl0lIrp99a9Jiq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc75c6b24038aa4f78c749e1354253a91d089de/pkg/sql/lease.go#L680)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Modififcation
</blockquote></details>

Done.
___
*[pkg/sql/lease.go, line 683 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJK7fHr7nEL7JEZGJVq:-LJKzJVX0og-DEvpuoLP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc75c6b24038aa4f78c749e1354253a91d089de/pkg/sql/lease.go#L683)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

use `hasExpired` since you used it above
</blockquote></details>

Done.
___
*[pkg/sql/lease.go, line 690 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJK8C9P6jtdt03UymfC:-LJKzR-R9miys-Pm2DLc:bly6uw5) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc75c6b24038aa4f78c749e1354253a91d089de/pkg/sql/lease.go#L690)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

isn't this case handled before the loop? Can that code go away?
</blockquote></details>

I've take the code out at the top and kept this so that the renewal is requested only if the leased descriptor is considered to be returned.
___
*[pkg/sql/lease.go, line 701 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJKAGAd5zVZI-gap-Uy:-LJLF0Dp8YmIB-myKRSE:b-p8qyyd) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc75c6b24038aa4f78c749e1354253a91d089de/pkg/sql/lease.go#L701)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think it's time we introduce a `Get` that returns all the key's versions. We'd still need to maintain other code for a version for backward compatibility (we'd guard the use of the new operation on a cluster version). Consider it.
</blockquote></details>

well to tell you the truth the AS OF SYSTEM TIME code is still not using this cache and I've many times considered getting rid of this because I don't see why we need to cache for that case. We cache for the ongoing txn with slightly older timestamp that hasn't yet requested this table. But  we might also go down the path of slowing down releasing older version leases until all gateway txn timestamps are above the new descriptors ModificationTime and then get rid of this cache of older descriptors I've updated the TODO to reflect this thought.
___
*[pkg/sql/lease.go, line 703 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJK8jUmEcQtS6SsWFkd:-LJLI5LZ4Y3pmiH1D2YX:bljda1c) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc75c6b24038aa4f78c749e1354253a91d089de/pkg/sql/lease.go#L703)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> ```
> // TODO(vivek): We still do not use this cache for AS OF SYSTEM TIME
> // queries so this implementation is rather complex. Consider simplifying
> // it.
> ```

I don't understand this comment. First of all, either explain or strike the "still".
And then I don't understand if you're saying AOST should use the cache or not. Also I don't understand why AOST is being called out; what's special about AOST queries? 
</blockquote></details>

Updated this TODO.
___
*[pkg/sql/lease.go, line 711 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJKAnhs0M8sSqZPHnJK:-LJLI9sv0MGlVJVRW5J4:b91dwu2) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc75c6b24038aa4f78c749e1354253a91d089de/pkg/sql/lease.go#L711)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

what if `t == nil`?
</blockquote></details>

it can't, but it can once we start deleting tableState in a future PR, but that is handled in that PR.
___
*[pkg/sql/lease.go, line 1464 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJKB0pB-yUN6TnTZfN_:-LJLIRPP3AfBZF44wLd7:b-401z99) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc75c6b24038aa4f78c749e1354253a91d089de/pkg/sql/lease.go#L1464)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

pls comment the `true`. Or take the opportunity to make it an enum.
</blockquote></details>

Done. The boolean is removed in the future PR.
___
*[pkg/sql/lease.go, line 1525 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJKBPJRBnXg1hxa_di_:-LJLI_tZ57HE8kR7IsGa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc75c6b24038aa4f78c749e1354253a91d089de/pkg/sql/lease.go#L1525)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

pls add a comment
</blockquote></details>

Done.

**Review by andreimatei — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28248)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/lease.go, line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJK3B-7Bgdv5Cn5CKTr:-LJOs2bD9XdD1NV5_RHt:b-1ovqqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/be1aee52a78cb850d7f3106ed8b3248821ec3c71/pkg/sql/lease.go#L84)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

This actually violates the lock. It has always been this way and we've known about it. Is there a strong reason to not keep it this way. If we're concerned about it we could I suppose get rid of it recording refcount.
</blockquote></details>

If indeed it "violates the lock", then it's just a matter of time until it'll be caught by the race detector.
If all the callers hold the lock, I'd call it `stringLocked()` or at least put a comment about it.
___
*[pkg/sql/lease.go, line 656 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJK5cmy9-a1drJu4VaC:-LJP8LDO3ozx4Zd24oU1:b7svfxd) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc75c6b24038aa4f78c749e1354253a91d089de/pkg/sql/lease.go#L656)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

I've updated the comment. Part of me feels like deleting the comment I just added :-)
</blockquote></details>

looks good to me now
___
*[pkg/sql/lease.go, line 657 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJKBrGZ62lKDaAfv8d6:-LJPA033APkwVYGEZtqP:bjds7lg) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc75c6b24038aa4f78c749e1354253a91d089de/pkg/sql/lease.go#L657)):*
Sorry to bother some more, but I think it's important enough to get the cleanest possible API here. The way I see it, if the cache has a lease the timestamp requested is above its expiration, then the cache doesn't know if a new lease is required or if one of the "old versions" of the table should be read. Similarly if there's no cached state for the table.
The method now tries to not admit this uncertainty by separating the two returned errors instead of being honest, and that's why I think the comments on it are still not quite legible. For example, I've stared at the phrase below for a second now even while knowing what we're talking about. 2 weeks from now, I'll stare at this for two hours.

> ```
> // or the latest lease on the table was picked for the timestamp but
> // has expired for the timestamp. This allows a higher layer to renew
> ```

Here's one suggestion to see if the cat licks it up: return a single error saying `errNoStateForTimestamp`, with a `bool` in it saying `newerVersionInCache`. The bool would be set if... the cache has (one or more) table version that is valid above the requested timestamp. That'll accurately model what the cache knows. Then, the caller can use this information however it sees fit when deciding whether to acquire a lease or do something else (e.g. as far as the cache is concerned, the caller might decide to try acquiring a lease and then observe that that's still not good for the timestamp).

I'll take the current API too if you massage the comments more :)
___
*[pkg/sql/lease.go, line 701 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJKAGAd5zVZI-gap-Uy:-LJPViM0EYEJ4mxzdJNw:b7s2nmc) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc75c6b24038aa4f78c749e1354253a91d089de/pkg/sql/lease.go#L701)):*
> slowing down releasing older version leases until all gateway txn timestamps are above the new descriptors ModificationTime

But I don't think the point when "all gateway txn timestamps are above..." can be defined; for the most part we don't disallow long-running txn. In fact, I think it's likely we'll start running more and more queries with old timestamps (e.g. follower reads, bounded staleness  https://github.com/cockroachdb/cockroach/issues/25405)

In my opinion, this cache makes sense. This is not to say that we couldn't be more aggressive about trimming old descriptors when there's pressure.

**Review by vivekmenezes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28248)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/lease.go, line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJK3B-7Bgdv5Cn5CKTr:-LJQFdEU3zEwBA9rhHls:befpwdi) ([raw file](https://github.com/cockroachdb/cockroach/blob/be1aee52a78cb850d7f3106ed8b3248821ec3c71/pkg/sql/lease.go#L84)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

If indeed it "violates the lock", then it's just a matter of time until it'll be caught by the race detector.
If all the callers hold the lock, I'd call it `stringLocked()` or at least put a comment about it.
</blockquote></details>

Added a comment saying we violate the lock
___
*[pkg/sql/lease.go, line 656 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJK5cmy9-a1drJu4VaC:-LJQFnml3ME3_-Btj0O8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc75c6b24038aa4f78c749e1354253a91d089de/pkg/sql/lease.go#L656)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

looks good to me now
</blockquote></details>

Done.
___
*[pkg/sql/lease.go, line 657 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJKBrGZ62lKDaAfv8d6:-LJQM6wVCJ2tH4B1eyJz:b-z9ht2y) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc75c6b24038aa4f78c749e1354253a91d089de/pkg/sql/lease.go#L657)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Sorry to bother some more, but I think it's important enough to get the cleanest possible API here. The way I see it, if the cache has a lease the timestamp requested is above its expiration, then the cache doesn't know if a new lease is required or if one of the "old versions" of the table should be read. Similarly if there's no cached state for the table.
The method now tries to not admit this uncertainty by separating the two returned errors instead of being honest, and that's why I think the comments on it are still not quite legible. For example, I've stared at the phrase below for a second now even while knowing what we're talking about. 2 weeks from now, I'll stare at this for two hours.

> ```
> // or the latest lease on the table was picked for the timestamp but
> // has expired for the timestamp. This allows a higher layer to renew
> ```

Here's one suggestion to see if the cat licks it up: return a single error saying `errNoStateForTimestamp`, with a `bool` in it saying `newerVersionInCache`. The bool would be set if... the cache has (one or more) table version that is valid above the requested timestamp. That'll accurately model what the cache knows. Then, the caller can use this information however it sees fit when deciding whether to acquire a lease or do something else (e.g. as far as the cache is concerned, the caller might decide to try acquiring a lease and then observe that that's still not good for the timestamp).

I'll take the current API too if you massage the comments more :)

</blockquote></details>

Updated the comment. I hope that's better.
___
*[pkg/sql/lease.go, line 701 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJKAGAd5zVZI-gap-Uy:-LJQNQRvB1JRjTLBs7Ir:b-hfww98) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc75c6b24038aa4f78c749e1354253a91d089de/pkg/sql/lease.go#L701)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

> slowing down releasing older version leases until all gateway txn timestamps are above the new descriptors ModificationTime

But I don't think the point when "all gateway txn timestamps are above..." can be defined; for the most part we don't disallow long-running txn. In fact, I think it's likely we'll start running more and more queries with old timestamps (e.g. follower reads, bounded staleness  https://github.com/cockroachdb/cockroach/issues/25405)

In my opinion, this cache makes sense. This is not to say that we couldn't be more aggressive about trimming old descriptors when there's pressure.
</blockquote></details>

Updated the comment to reflect a couple of TODOs that we could work on in the future.

**Review by andreimatei — CHANGES_REQUESTED** [review]
LGTM mod that pesky lock

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-:-LJQd5_b7m70zo1d5Szs:bgf6wnn)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/lease.go, line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJK3B-7Bgdv5Cn5CKTr:-LJQYVatEDyCymHxavuz:b-z8t1c2) ([raw file](https://github.com/cockroachdb/cockroach/blob/be1aee52a78cb850d7f3106ed8b3248821ec3c71/pkg/sql/lease.go#L84)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Added a comment saying we violate the lock
</blockquote></details>

I don't think we can do that... I don't think it's ever permissible to "violate" a lock. If for no other reason because the race detector will unavoidably catch you.
I was say add a comment saying that we are *not* in fact violating the lock (if that's true) because all the callers are holding it (or, rather, a comment saying that the callers must hold the lock).

If all else fails, make this field an atomic.

PS: there is precedent for a String/stringLocked duo.
___
*[pkg/sql/lease.go, line 657 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJKBrGZ62lKDaAfv8d6:-LJQ_dDWEVf0BpgmBgV_:b-svxf8p) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc75c6b24038aa4f78c749e1354253a91d089de/pkg/sql/lease.go#L657)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Updated the comment. I hope that's better.
</blockquote></details>

it is, thanks

**Review by vivekmenezes — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-:-LJTbahe0zNzPrCzrhtG:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/lease.go, line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJK3B-7Bgdv5Cn5CKTr:-LJTbX8u2HZANaJE_j_G:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/be1aee52a78cb850d7f3106ed8b3248821ec3c71/pkg/sql/lease.go#L84)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I don't think we can do that... I don't think it's ever permissible to "violate" a lock. If for no other reason because the race detector will unavoidably catch you.
I was say add a comment saying that we are *not* in fact violating the lock (if that's true) because all the callers are holding it (or, rather, a comment saying that the callers must hold the lock).

If all else fails, make this field an atomic.

PS: there is precedent for a String/stringLocked duo.
</blockquote></details>

Done!
___
*[pkg/sql/lease.go, line 657 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-LJKBrGZ62lKDaAfv8d6:-LJTbZ3m1faVAWq72vtV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcc75c6b24038aa4f78c749e1354253a91d089de/pkg/sql/lease.go#L657)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

it is, thanks
</blockquote></details>

Done.

**Review by andreimatei — COMMENTED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28248#-:-LJVgnfUDkAAiTJFuFrp:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by jordanlewis** [comment]
Totally coincidental but I happened to be profiling stuff and noticed that this introduced a reasonably serious performance regression - moving the String() to stringLocked() is what did it, because it means that we unconditionally do that Sprintf instead of only when log.V(2) is true. I'm sending a PR because I'm already messing with some stuff in this area!

**Pull request merged**
