### PR TITLE
opt: DistinctOn operator

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: DistinctOn operator

This change introduces the DistinctOn operator, which is polymorphic
with GroupBy and can be used (as appropriate) in the same rules. We
add a `FirstAgg` aggregate function that is used with this operator.

Changing the build code for `SELECT DISTINCT` to use this operator.
There will be follow-up work to support `DISTINCT ON`.

Note that it's hard to come up with testcases for rules without
`DISTINCT ON`, I plan to add more tests when that is implemented.

In this change, `DistinctOn` doesn't provide any ordering; this will
be improved after we support `DISTINCT ON`.

Release note: None

### CODE REVIEW

**Review by rytaft — CHANGES_REQUESTED** [review]
> Reviewed 24 of 24 files at r1, 26 of 26 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28106)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/exec/factory.go, line 123 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28106#-LIlfHYk4zNCKLE9ifXi:-LIlfHYl55tgkVZ69S0d:b-52dslt) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef4cb95c3f31a596b95f1cfdfc374bb6b4b989b0/pkg/sql/opt/exec/factory.go#L123)):*
> ```Go
> 	// The orderedCols are a subset of distinctCols, along which the input is
> 	// guaranteed to be ordered (i.e. all rows with the same values on these
> 	// columns are a contiguous part of the input).
> ```

[nit] How does distinctNode guarantee this? Maybe it would be better to say the input is required to have the given ordering?
___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 551 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28106#-LIlxZoU1TgiWSr7BAtT:-LIlxZoU1TgiWSr7BAtU:bxq9swd) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef4cb95c3f31a596b95f1cfdfc374bb6b4b989b0/pkg/sql/opt/exec/execbuilder/relational_builder.go#L551)):*
> ```Go
> 	if n := def.GroupingCols.Len() + aggs.ChildCount(); n != input.outputCols.Len() {
> 		cols := make(opt.ColList, 0, n)
> 		for i, ok := def.GroupingCols.Next(0); ok; i, ok = def.GroupingCols.Next(i + 1) {
> ```

[nit] I think you could use `def.GroupingCols.ForEach` here since you don't need to break out of the loop early.
___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 568 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28106#-LIlxxem6W9GkE6tpYSS:-LIlxxem6W9GkE6tpYST:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef4cb95c3f31a596b95f1cfdfc374bb6b4b989b0/pkg/sql/opt/exec/execbuilder/relational_builder.go#L568)):*
> ```Go
> 
> 	var distinctCols exec.ColumnOrdinalSet
> 	for i, ok := def.GroupingCols.Next(0); ok; i, ok = def.GroupingCols.Next(i + 1) {
> ```

ditto
___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 576 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28106#-LIlygxT7O-MIpHKDOU3:-LIlygxT7O-MIpHKDOU4:b-ljybs3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef4cb95c3f31a596b95f1cfdfc374bb6b4b989b0/pkg/sql/opt/exec/execbuilder/relational_builder.go#L576)):*
> ```Go
> 	for i := range ordering.Columns {
> 		g := ordering.Columns[i].Group
> 		if !g.Intersects(distinctCols) {
> ```

Isn't `distinctCols` now using column ordinals instead of ColumnIDs? Maybe you should check if `g` intersects `def.GroupingCols`?
___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 581 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28106#-LIlzFqABEoepAKcFe9L:-LIlzFqABEoepAKcFe9M:b4zpneh) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef4cb95c3f31a596b95f1cfdfc374bb6b4b989b0/pkg/sql/opt/exec/execbuilder/relational_builder.go#L581)):*
> ```Go
> 			break
> 		}
> 		orderedCols.UnionWith(g)
> ```

Again here - don't you need to convert g to use ColumnOrdinals?
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 580 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28106#-LIlznhd6r8Cs57Vbbbk:-LIlznhd6r8Cs57Vbbbl:b-ak0unn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef4cb95c3f31a596b95f1cfdfc374bb6b4b989b0/pkg/sql/opt/memo/logical_props_builder.go#L580)):*
> ```Go
> 		// GroupBy and DistinctOn act like a filter, never returning more rows than the input
> 		// has. However, if the input has at least one row, then at least one row
> 		// will also be returned by GroupBy.
> ```

[nit] GroupBy -> GroupBy and DistinctOn
___
*[pkg/sql/opt/norm/rules/scalar.opt, line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28106#-LIm0ZHq3M7pM3GblllS:-LIm0ZHq3M7pM3GblllT:b47itki) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef4cb95c3f31a596b95f1cfdfc374bb6b4b989b0/pkg/sql/opt/norm/rules/scalar.opt#L148)):*
> ```
> (Exists (Project $input:*)) => (Exists $input)
> 
> # EliminateExistsGroupBy discards a non-scalar GroupBy input to the Exists
> ```

[nit] or DistinctOn
___
*[pkg/sql/opt/norm/testdata/props/prune_cols, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28106#-LIm2HygET5RyE66ANqb:-LIm2HygET5RyE66ANqc:byowska) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8cc99438fc6ba3d01d6583ef3d1b5ccd9eb8e07/pkg/sql/opt/norm/testdata/props/prune_cols#L1)):*
> ```
> # Tests for PruneCols property
> ```

This seems unrelated to your change... did you mean to add this?

**Comment by rytaft** [comment]
___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 545 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28106#-LIm34LI5mq_pkHxcZv5:-LIm34LI5mq_pkHxcZv6:bl7tmf6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8cc99438fc6ba3d01d6583ef3d1b5ccd9eb8e07/pkg/sql/opt/exec/execbuilder/relational_builder.go#L545)):*
> ```Go
> 
> 	// The DistinctOn operator can effectively project away columns if they don't
> 	// have a corresponding aggregation. Introduce that project before the
> ```

This seems like something that should have been done already by a pruneCols rule -- Is there a reason it has to happen here?

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28106#-:-LImHMH_9SnfiEmp3EXH:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/exec/factory.go, line 123 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28106#-LIlfHYk4zNCKLE9ifXi:-LImEF4G9dAOFMTqnN8_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef4cb95c3f31a596b95f1cfdfc374bb6b4b989b0/pkg/sql/opt/exec/factory.go#L123)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] How does distinctNode guarantee this? Maybe it would be better to say the input is required to have the given ordering?
</blockquote></details>

Done.
___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 551 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28106#-LIlxZoU1TgiWSr7BAtT:-LImE_7BDMwNGggUApbu:b-7gmvuq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef4cb95c3f31a596b95f1cfdfc374bb6b4b989b0/pkg/sql/opt/exec/execbuilder/relational_builder.go#L551)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] I think you could use `def.GroupingCols.ForEach` here since you don't need to break out of the loop early.
</blockquote></details>

I prefer this pattern so I don't have to wonder if anything is getting allocated for the callback.
___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 576 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28106#-LIlygxT7O-MIpHKDOU3:-LImFSs_0vnkvI5yBWn9:b4yzb0b) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef4cb95c3f31a596b95f1cfdfc374bb6b4b989b0/pkg/sql/opt/exec/execbuilder/relational_builder.go#L576)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Isn't `distinctCols` now using column ordinals instead of ColumnIDs? Maybe you should check if `g` intersects `def.GroupingCols`?
</blockquote></details>

Oops, good catch. We aren't using the ordering yet so this code isn't being exercised.
___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 581 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28106#-LIlzFqABEoepAKcFe9L:-LImF_RO4jwzsl20oEVV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef4cb95c3f31a596b95f1cfdfc374bb6b4b989b0/pkg/sql/opt/exec/execbuilder/relational_builder.go#L581)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Again here - don't you need to convert g to use ColumnOrdinals?
</blockquote></details>

Done.
___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 545 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28106#-LIm34LI5mq_pkHxcZv5:-LImEHHtBDXfb0aRqoz4:b-p7m1sl) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8cc99438fc6ba3d01d6583ef3d1b5ccd9eb8e07/pkg/sql/opt/exec/execbuilder/relational_builder.go#L545)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This seems like something that should have been done already by a pruneCols rule -- Is there a reason it has to happen here?
</blockquote></details>

We don't prune unneeded `GroupBy` input columns (in fact the opposite - we have a rule that discards any Project under it). DistinctOn is keeping the same semantics so we can safely convert between them and/or reuse code.
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 580 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28106#-LIlznhd6r8Cs57Vbbbk:-LImFoD1634Sowp1Ews3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef4cb95c3f31a596b95f1cfdfc374bb6b4b989b0/pkg/sql/opt/memo/logical_props_builder.go#L580)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] GroupBy -> GroupBy and DistinctOn
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/rules/scalar.opt, line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28106#-LIm0ZHq3M7pM3GblllS:-LImFwsg2iJZ9Srjo3ID:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef4cb95c3f31a596b95f1cfdfc374bb6b4b989b0/pkg/sql/opt/norm/rules/scalar.opt#L148)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] or DistinctOn
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/testdata/props/prune_cols, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28106#-LIm2HygET5RyE66ANqb:-LImFxj28J6fBl2k0ek7:bg2h2yj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8cc99438fc6ba3d01d6583ef3d1b5ccd9eb8e07/pkg/sql/opt/norm/testdata/props/prune_cols#L1)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This seems unrelated to your change... did you mean to add this?
</blockquote></details>

Oops, rebase issue, removed.

**Review by andy-kimball — APPROVED** [review]
:lgtm:

Can't you add testcases for regular `GroupBy` with no aggregate columns, since we're mapping that into `DistinctOn`?

> Reviewed 24 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28106#-:-LIltnu26LWlepjGmWqu:b-kuevn4)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 554 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28106#-LIlhdjL-QiDjbJwPl9b:-LIlhdjMEBCc6zU1lLeM:b-oqnds5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef4cb95c3f31a596b95f1cfdfc374bb6b4b989b0/pkg/sql/opt/exec/execbuilder/relational_builder.go#L554)):*
> ```Go
> 			cols = append(cols, opt.ColumnID(i))
> 		}
> 		for _, v := range aggs.Private().(opt.ColList) {
> ```

Can't this just be: `cols = append(cols, aggs.Private().(opt.ColList)...)`
___
*[pkg/sql/opt/memo/logical_props_builder.go, line 578 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28106#-LIlsACZ4Y6gfnFSIg0x:-LIlsACZ4Y6gfnFSIg0y:bh2xv56) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef4cb95c3f31a596b95f1cfdfc374bb6b4b989b0/pkg/sql/opt/memo/logical_props_builder.go#L578)):*
> ```Go
> 		relational.Cardinality = props.OneCardinality
> 	} else {
> 		// GroupBy and DistinctOn act like a filter, never returning more rows than the input
> ```

NIT: Comment more than 80 chars.
___
*[pkg/sql/opt/norm/rules/groupby.opt, line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28106#-LIlsmBp5_UslhwhHTyI:-LIlsmBp5_UslhwhHTyJ:b-kilowc) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef4cb95c3f31a596b95f1cfdfc374bb6b4b989b0/pkg/sql/opt/norm/rules/groupby.opt#L5)):*
> ```
> # =============================================================================
> 
> # ConvertGroupByToDsitinct converts a GroupBy operator that has no aggregations
> ```

NIT: spelling
___
*[pkg/sql/opt/ops/relational.opt, line 255 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28106#-LIltM5kEiRBaVHXRPMP:-LIltM5kEiRBaVHXRPMQ:b8gdu2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef4cb95c3f31a596b95f1cfdfc374bb6b4b989b0/pkg/sql/opt/ops/relational.opt#L255)):*
> ```
> # values, like decimals. For example, if we have rows (1, 2.0) and (1.0, 2) and
> # we are grouping on these two columns, the values output can be either (1, 2.0)
> # or (1.0, 2), but not (1.0, 2.0).
> ```

Is this not true for regular `GroupBy`? If not, is there any issue with mapping `GroupBy` with no aggregate functions into `DistinctOn`? Do we care that the semantics become more restrictive when we do that?

**Review by RaduBerinde — COMMENTED** [review]
Good point, I added a bunch. I still can't build a DistinctOn with FirstAggs like that (would need it to test `PruneAggCols`).

I am having second thoughts about `PushSelectIntoGroupBy`.
I don't think it's correct as-is for DistinctOn (though I can't really test it to confirm):
`SELECT * FROM (SELECT DISTINCT ON (a) a, b, c ORDER BY a, b, c) WHERE b>1`
is different from
`SELECT DISTINCT ON (a) a, b, c WHERE b>1 ORDER BY a, b, c`
The problem is that DistinctOn passes through the colID of b so the rule would fire.
I think I need to adjust the rule to not use `IsBoundBy` with `input`, and instead check if it is bound by the grouping columns.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28106#-:-LIn8Q1GBSIDe-EzY18i:bxnulo0)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 554 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28106#-LIlhdjL-QiDjbJwPl9b:-LIn0l-F1jYHffpMAB9C:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef4cb95c3f31a596b95f1cfdfc374bb6b4b989b0/pkg/sql/opt/exec/execbuilder/relational_builder.go#L554)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Can't this just be: `cols = append(cols, aggs.Private().(opt.ColList)...)`
</blockquote></details>

Done.
___
*[pkg/sql/opt/ops/relational.opt, line 255 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28106#-LIltM5kEiRBaVHXRPMP:-LInAGKHCo3XPmR7cZ3J:b-ti77no) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef4cb95c3f31a596b95f1cfdfc374bb6b4b989b0/pkg/sql/opt/ops/relational.opt#L255)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Is this not true for regular `GroupBy`? If not, is there any issue with mapping `GroupBy` with no aggregate functions into `DistinctOn`? Do we care that the semantics become more restrictive when we do that?
</blockquote></details>

It is in practice, I can't imagine what execution implementation wouldn't use values from the same row. It's just not explicitly stated for GroupBy. It's true that DistinctOn is technically more restrictive in that sense, but I don't see any practical problem.

**Review by rytaft — APPROVED** [review]
:lgtm:, assuming you make the change to `PushSelectIntoGroupBy`

> Reviewed 7 of 33 files at r3, 25 of 25 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28106#-:-LIpwyfJ9uVxlOdZi95B:b-d1gx37)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 545 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28106#-LIm34LI5mq_pkHxcZv5:-LIptYQJ9roQd2Ph4o44:bjtb84p) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8cc99438fc6ba3d01d6583ef3d1b5ccd9eb8e07/pkg/sql/opt/exec/execbuilder/relational_builder.go#L545)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We don't prune unneeded `GroupBy` input columns (in fact the opposite - we have a rule that discards any Project under it). DistinctOn is keeping the same semantics so we can safely convert between them and/or reuse code.
</blockquote></details>

got it - thanks!

**Review by andy-kimball — COMMENTED** [review]
Yes, you're right about `PushSelectIntoGroupBy`. Reusing the `colID`s in aggregates breaks the current logic. The intent was always to test if the filter is bound only by grouping columns. Good news is that should be fairly easy fix.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28106#-:-LIpy5DmCD-praGMxUeA:b-ughpmv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Comment by RaduBerinde** [comment]
Ok, that rule is now rewritten. I added some TODOs for testcases that require `DISTINCT ON`, I'll probably make another pass over the rules when it's available.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 1 of 33 files at r3, 5 of 30 files at r5, 25 of 25 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28106#-:-LIqmTbt9hJojG7_8X58:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Pull request merged**
