### PR TITLE
Use glock to get dependencies.

### PR DESCRIPTION
**Pull request by petermattis**
Using glock removes the need to "bake" dependencies (go_resources) into
the cockroach formula. Without the need to add the go_resources to the
formula the primary motivation for the make-brew-formula.sh
disappeared. The expected usage is to update the tag and revision in
this file when a new version is released.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3503)

### CODE REVIEW

**Comment by petermattis** [comment]
This is an alternative to #3500. Not sure if it is acceptable to the homebrew maintainers, but it certainly is a lot simpler (at least the end result, took me a while to get here). The only downside is that using `go_resources` caches the dependent git repos between `brew install` invocations. That is unlikely to be important in practice as the install time is dominated by compiling `c-rocksdb` which has to be rebuilt with either approach.

**Comment by bdarnell** [comment]
LGTM.

We could simplify this even further by removing `SKIP_BOOTSTRAP` from the `make` invocation and letting it handle the installation and running of `glock`. It is a bit wasteful to build and install all our development dependencies, but stripping the `cmd` lines from the `GLOCKFILE` doesn't go far enough; we still download them.

**Comment by petermattis** [comment]
Yeah, it's mildly simpler to just let bootstrapping do its thing. Unfortunately I can't test this with the slow airplane wifi.

**Comment by tschottdorf** [comment]
LGTM

**Pull request merged**
