### PR TITLE
server: default clock protections to on

### LINKED ISSUE #25109: util/hlc: Consider enabling extra clock protections by default
@vijaykarthik-rubrik added two new settings to perform additional validation of the clock behavior in #23717 and #23744. These happened so late in the 2.0 cycle that we decided to leave them off by default for that release. We should decide whether we want to change that for 2.1 and enable one or both of them by default. 

- `server.clock.forward_jump_check_enabled` may experience false positives leading to crashes if run on a laptop or a VM that gets suspended and resumed. 
- `server.clock.persist_upper_bound_interval` has a performance cost due to extra disk writes

These settings are probably good ideas for production deployments but might cause problems or confusion in development environments. Whichever way we decide to set the defaults, we'll need documentation about changing them.

### PR DESCRIPTION
**Pull request by tbg**
Fixes #25109.

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
TODO:

- improve fatal error msgs, to hint at the env vars

**Comment by bdarnell** [comment]
This env var/setting combination pattern is subtle and confusing; I'd rather not propagate it any further (I'd prefer to only use it in places where you can't just set the setting after the fact and have the same results, as with the telemetry opt-in). I wish we had a better way to set cluster settings at init time. I wouldn't mind having a `--dev` flag on `start-single-node` that sets a bunch of "dev mode" settings including turning off forward clock jump checks.

**Comment by tbg** [comment]
> This env var/setting combination pattern is subtle and confusing; I'd rather not propagate it any further (I'd prefer to only use it in places where you can't just set the setting after the fact and have the same results, as with the telemetry opt-in). I wish we had a better way to set cluster settings at init time. I wouldn't mind having a --dev flag on start-single-node that sets a bunch of "dev mode" settings including turning off forward clock jump checks.

I (somewhat) understand your distaste for the env solutions but I don't want to disrupt people's long-running servers. And I'm apprehensive to block the defaults change on whatever the replacement to env vars should be; we had all of the discussions years ago and then never did anything, that is the one undesirable outcome here. Instead, could you file an issue about the env var pattern, put it into the server team, and when the time comes we can migrate out of it?

**Comment by tbg** [comment]
> if you're running on a laptop

The question is more, what do folks expect? I personally don't care if any servers that I forgot to shut down crash when my laptop goes to sleep; I don't expect to set the env vars myself. But that's just me. Running an eng-wide (or even corp-wide? community-wide?) process to collect everyone's preferences is way beyond what I can invest here. But landing it without an escape hatch is going to unnecessarily interrupt the (hopefully few) who rely on today's defaults.

> For example, should start-single-node imply no forward clock jump checking?

No, single nodes break just the same way as multi-nodes if your clock temporarily jumps into the future. So on production single nodes, the settings should be set just the same.

Speaking of UX and production, there's also concern (at least on my part) that the forward clock jump setting may cause fatal errors. Checking for max_offset/2 can be pretty tight, I'm not sure what max_offsets folks out there are using. And we have only very little operational experience with the settings.

Also, from an operational perspective, there are more problems. We can expect many deployments to auto-restart the node when it crashes. So how will what we have actually solve the problem?

- node is running
- clock jumps +8h
- forward_jump_detection catches it, fatals (this also prevents the other setting from seeing the future timestamps, as it pulls them through these checks)
- node restarts.... here we are, it's 8h in the future and we're screwed anyway?

So it seems that at the very least the forward jump detection would need to write a death rattle, and the operator would have to remove it (thereby promising that the clock is "now good"). Or we need to have some synchronous check at start-up where a node gets at least one other node to sign off on its timestamps.

Unfortunately I think it was premature of me to think that we could "just" adjust the settings. I'll close this PR and copy the learnings to #25109, which I will move to the Server team (which I believe is where this issue belongs these days).

**Comment by bdarnell** [comment]
> So it seems that at the very least the forward jump detection would need to write a death rattle

Oh, that's a good point. So this setting as-is doesn't really do anything valuable.

**Comment by rmloveland** [comment]
Tobias Grieger ***@***.***> writes:

>     if you're running on a laptop
>
> The question is more, what do folks expect? I personally don't care if
> any servers that I forgot to shut down crash when my laptop goes to
> sleep; I don't expect to set the env vars myself. But that's just me.
> Running an eng-wide (or even corp-wide? community-wide?) process to
> collect everyone's preferences is way beyond what I can invest here.
> But landing it without an escape hatch is going to unnecessarily
> interrupt the (hopefully few) who rely on today's defaults.

From a docs POV, if we can't find a middle ground, I think saying
"laptop suspend/resume doesn't work, here is the flag to set if you
care" is probably the simplest thing to document without breaking
anybody's prod stuff.

Re: UX, on a laptop I most often use `cockroach demo`, so if we updated
that (and `start-single-node`) with the necessary clock jump settings it
seems like it would cover most of the affected use cases.  Hopefully :-)

Anecdotally, for larger things that need persistence but still need to
happen on my laptop (like for spatial docs loading some multi-GB data
sets) I use a script I wrote when I started here that does the init/join
dance for me. In that case I'd expect to update my script once with
whatever the new env var / flag we choose (if any) and then promptly
forget everything again (which is the point of that script).

(Figured it's worth commenting here since folks are being directed here
from #25109)

**Pull request closed without merging**
