### PR TITLE
demo: stop using random ports for tenants

### LINKED ISSUE #72544: cockroach demo port changes to a different port each time
Previously, running `cockroach demo` would always use port `26257`, now it uses a different port each time.

Intrusion/console (used for CC Console development) checks `localhost:26257`, but since a different port is used on demo, the intrusion/console fails to run.

### PR DESCRIPTION
**Pull request by rafiss**
fixes #72544

This change makes the SQL ports used by tenants in a demo
cluster deterministic. The result is that tenant 1 ends up with the
default SQL port (or the one passed by --sql-port). The first system
tenant ends up with a port that is numNodes larger.

Although HTTP does not yet work on tenant nodes, this change also gives
tenant 1 the default HTTP port (or the one passed by --http-port).

Example:
```
> ./cockroach demo

system tenant
node 1:
  (webui)    http://127.0.0.1:8081/demologin?password=demo91305&username=demo
  (sql)      postgresql://demo:demo91305@127.0.0.1:26258/movr?sslmode=require

tenant 1:
   (sql):  postgresql://demo:demo91305@127.0.0.1:26257/movr?sslmode=require

> ./cockroach demo --multitenant=false

node 1:
  (webui)    http://127.0.0.1:8080/demologin?password=demo91294&username=demo
  (sql)      postgresql://demo:demo91294@127.0.0.1:26257/movr?sslmode=require

> ./cockroach demo --nodes 3 --sql-port 26000

system tenant
node 1:
  (webui)    http://127.0.0.1:8083/demologin?password=demo91220&username=demo
  (sql)      postgresql://demo:demo91220@127.0.0.1:26003/movr?sslmode=require

node 2:
  (webui)    http://127.0.0.1:8084/demologin?password=demo91220&username=demo
  (sql)      postgresql://demo:demo91220@127.0.0.1:26004/movr?sslmode=require

node 3:
  (webui)    http://127.0.0.1:8085/demologin?password=demo91220&username=demo
  (sql)      postgresql://demo:demo91220@127.0.0.1:26005/movr?sslmode=require

tenant 1:
   (sql):  postgresql://demo:demo91220@127.0.0.1:26000/movr?sslmode=require

tenant 2:
   (sql):  postgresql://demo:demo91220@127.0.0.1:26001/movr?sslmode=require

tenant 3:
   (sql):  postgresql://demo:demo91220@127.0.0.1:26002/movr?sslmode=require
```

Release note: None

### CODE REVIEW

**Review by otan — APPROVED** [review]
i was half thinking that we'd add a `StartingSystemTenantHostPort` or something so we can customise the range of "system tenants", and use `SQLStartPort` for tenants if `--multitenant` is enabled.

I think the current `SQLStartPort-1` is flawed in a multi-node demo setup, because it still tries to startup a system tenant on each node as well. no?

**Review by otan — CHANGES_REQUESTED** [review]
oops

**Comment by rafiss** [comment]
> I think the current SQLStartPort-1 is flawed in a multi-node demo setup, because it still tries to startup a system tenant on each node as well. no?

confirmed, this PR is flawed due to that

**Comment by otan** [comment]
don't need CI to see the errors; just need me

**Comment by rafiss** [comment]
lol i was worried about that too, but figured i'd just let you tell me :P

**Review by otan — COMMENTED** [review]
i'm a bit lost with this - can you label with a comment somewhere what ports get allocated to what tenant with this new PR?

tbh i was kinda hoping the first user tenant ends up being port 26257 (and system tenants reserve a separate address space, which defaults to 27257 and is specified with a `--system-tenant-port` or the like)

**Comment by rafiss** [comment]
ok, i can comment it more.

> tbh i was kinda hoping the first user tenant ends up being port 26257 

that's what's happening now

> (and system tenants reserve a separate address space, which defaults to 27257 and is specified with a --system-tenant-port or the like)

it is defaulting to 26357 right now. i can add a --system-tenant-port flag to customize it, but not sure if it's that valuable.

**Comment by rafiss** [comment]
More comments added. I actually don't understand the use case for making the system tenant port configurable with a flag. Could you explain more?

**Comment by otan** [comment]
> More comments added. I actually don't understand the use case for making the system tenant port configurable with a flag. Could you explain more?

oh i'm not too strong on the matter, i thought it'd be easier is all

**Review by otan — APPROVED** [review]

**Comment by rafiss** [comment]
tftr!

bors r=otan

**Pull request merged**
