### PR TITLE
Alias bytes to bytea

### LINKED ISSUE #4069: Support "bytea" as alias for "bytes" in the syntax for pg compatibiity, perhaps other types too?
It is desirable for tutorials / doc etc to be able to provide examples that can be copy and pasted both in CockroachDB and PostgreSQL. For example:

```
select length('a'::string) + length('b'::bytes)
```

works in CockroachDB but not with pg, because pg knows neither `string` nor `bytes`. However pg knows `text` and `bytea`. Cockroach knows `text` as an alias for `string`, but does not know `bytea`. This issue suggests to add "bytea" as a syntactic alias for `bytes`.

### PR DESCRIPTION
**Pull request by knz**
Fixes #4069.

Also I scanned through @bdarnell's SQLAlchemy log linked from https://github.com/cockroachdb/cockroach/issues/4069#issuecomment-178611719. 

The only type names mentioned in there that are not yet reported by CockroachDB are the integer ranges, serial, hstore and "bytea".  Since "bytea" thus is the only overlap (as used in this test) let's constrain the compatibility to that, as requested in #4069.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4211)

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
LGTM, but could we test this alias in a unit test somewhere? Perhaps in the logic tests?

**Comment by tamird** [comment]
We should have a parser test for this as well.

**Comment by petermattis** [comment]
LGTM, though add a test to `sql/parser/types_test.go`.

**Comment by knz** [comment]
Test is there now.

**Comment by petermattis** [comment]
LGTM

**Pull request merged**
