### PR TITLE
kvserver: reintroduce RangeDesc.GenerationComparable

### LINKED ISSUE #53535: roachtest: tpcc/mixed-headroom/n5cpu16 failed
[(roachtest).tpcc/mixed-headroom/n5cpu16 failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2225322&tab=buildLog) on [provisional_202008261913_v20.2.0-beta.1@eaa939ce6548a54a23970814ff00f30ad87680ac](https://github.com/cockroachdb/cockroach/commits/eaa939ce6548a54a23970814ff00f30ad87680ac):

```
		  | _elapsed___errors__ops/sec(inst)___ops/sec(cum)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
		  |  2393.0s        0           23.0           19.0     54.5     75.5    121.6    121.6 delivery
		  |  2393.0s        0          199.3          189.3     33.6     92.3    130.0    151.0 newOrder
		  |  2393.0s        0           19.0           19.1      7.1     11.0     13.6     13.6 orderStatus
		  |  2393.0s        0          199.3          190.1     19.9     71.3    121.6    142.6 payment
		  |  2393.0s        0           18.0           19.0     24.1     60.8     65.0     65.0 stockLevel
		  |  2394.0s        0           20.0           19.0     52.4     71.3     92.3     92.3 delivery
		  |  2394.0s        0          171.7          189.3     32.5     50.3     83.9     92.3 newOrder
		  |  2394.0s        0           15.0           19.1      7.9      9.4     16.3     16.3 orderStatus
		  |  2394.0s        0          183.7          190.1     17.8     29.4     37.7     88.1 payment
		  |  2394.0s        0           20.0           19.0     24.1     56.6     71.3     71.3 stockLevel
		  |  2395.0s        0           35.0           19.0     58.7     92.3    134.2    134.2 delivery
		  |  2395.0s        0          203.3          189.3     33.6     62.9     92.3    113.2 newOrder
		  |  2395.0s        0           15.0           19.0      7.3      8.9     13.1     13.1 orderStatus
		  |  2395.0s        0          176.2          190.1     21.0     39.8     46.1     48.2 payment
		  |  2395.0s        0           19.0           19.0     30.4     67.1     96.5     96.5 stockLevel
		Wraps: (4) exit status 20
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *main.withCommandDetails (4) *exec.ExitError

	cluster.go:2613,tpcc.go:187,tpcc.go:286,test_runner.go:754: monitor failure: monitor task failed: t.Fatal() was called
		(1) attached stack trace
		  -- stack trace:
		  | main.(*monitor).WaitE
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2601
		  | main.(*monitor).Wait
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2609
		  | main.runTPCC
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tpcc.go:187
		  | main.registerTPCC.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tpcc.go:286
		  | main.(*testRunner).runTest.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:754
		Wraps: (2) monitor failure
		Wraps: (3) attached stack trace
		  -- stack trace:
		  | main.(*monitor).wait.func2
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2657
		Wraps: (4) monitor task failed
		Wraps: (5) attached stack trace
		  -- stack trace:
		  | main.init
		  | 	/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:2571
		  | runtime.doInit
		  | 	/usr/local/go/src/runtime/proc.go:5228
		  | runtime.main
		  | 	/usr/local/go/src/runtime/proc.go:190
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
		Wraps: (6) t.Fatal() was called
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.withPrefix (5) *withstack.withStack (6) *errutil.leafError

```

<details><summary>More</summary><p>

Artifacts: [/tpcc/mixed-headroom/n5cpu16](https://teamcity.cockroachdb.com/viewLog.html?buildId=2225322&tab=artifacts#/tpcc/mixed-headroom/n5cpu16)
Related:
- #52693 roachtest: tpcc/mixed-headroom/n5cpu16 failed  [C-test-failure](https://api.github.com/repos/cockroachdb/cockroach/labels/C-test-failure) [O-roachtest](https://api.github.com/repos/cockroachdb/cockroach/labels/O-roachtest) [O-robot](https://api.github.com/repos/cockroachdb/cockroach/labels/O-robot) [branch-master](https://api.github.com/repos/cockroachdb/cockroach/labels/branch-master) [release-blocker](https://api.github.com/repos/cockroachdb/cockroach/labels/release-blocker)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Atpcc%2Fmixed-headroom%2Fn5cpu16.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by andreimatei**
We dropped this field recently, but unfortunately that wasn't safe for
mixed-version clusters. The rub is that 20.1 nodes need to roundtrip the
proto through 20.2 nodes in a fairly subtle way. When it comes back to
the 20.1 node, the descriptor needs to compare Equal() to the original.
We configure our protos to not preserve unrecognized fields, so removing
the field breaks this round-tripping.

Specifically, the scenario which broke is the following:
1. A 20.1 node processes an AdminSplit, and performs the tranction
   writing the new descriptors. The descriptors have the
   GenerationCompable field set.
2. The lease changes while the respective txn is running. The lease
   moves to a 20.2 node.
3. The 20.2 node evaluates the EndTxn, and computes the split trigger
   info that's going to be replicated. The EndTxn has split info in it
   containing the field set, but the field is dropped when converting
   that into the proposed SplitTrigger (since the 20.2 unmarshalls and
   re-marshalls the descriptors).
4. All the 20.1 replicas of the ranges involved now apply the respective
   trigger via Raft, and their in-memory state doesn't have the field
   set. This doesn't match the bytes written in the database, which have
   the field.
5. The discrepancy between the in-memory state and the db state is a
   problem, as it causes the 20.1 node to spin if it tries to perform
   subsequent merge/split operations. The reason is that the code
   performing these operations short-circuits itself if it detects that
   the descriptor has changed while the operation was running. This
   detection is performed via the generated Equals() method, and it
   mis-fires because of the phantom field. That detection happens here:
   https://github.com/cockroachdb/cockroach/blob/79c01d28da9c379f67bb41beef3d85ad3bee1da1/pkg/kv/kvserver/replica_command.go#L1957

This patch takes precautions so that we can remove the field again in
21.1 - I'm merging this in 21.1, I'll backport it to 20.2, and then I'll
come back to 20.2 and remove the field.

Fixes #53535

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54199)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @tbg)

___
*[pkg/kv/kvserver/replica_command.go, line 1984 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54199#-MGtrF92E6mtnXyiGB2j:-MGtrF92E6mtnXyiGB2k:bbhyjkb) ([raw file](https://github.com/cockroachdb/cockroach/blob/2240e9f88a29c957c379ff9452c0163695319ef1/pkg/kv/kvserver/replica_command.go#L1984)):*
> ```Go
> 	// round-trip a desc from 20.1 through a 20.2 node and still have it compare
> 	// equal back on 20.1.
> 	if desc.DeprecatedGenerationComparable != nil {
> ```

nit: consider pulling this into a helper, since we do the same thing twice.
___
*[pkg/kv/kvserver/replica_command.go, line 2013 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54199#-MGtrMxx35Z4Rm6d1EEY:-MGtrMxx35Z4Rm6d1EEZ:bmnaalw) ([raw file](https://github.com/cockroachdb/cockroach/blob/2240e9f88a29c957c379ff9452c0163695319ef1/pkg/kv/kvserver/replica_command.go#L2013)):*
> ```Go
> 		}
> 
> 		return desc.Equal(desc2)
> ```

Are you concerned that we might have similar bugs lurking in other calls to `RangeDescriptor.Equal`? I wonder if we should change the impl of that for this one release.
___
*[pkg/roachpb/metadata.proto, line 131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54199#-MGtrdN8CWmHgmq6wY3N:-MGtrdN8CWmHgmq6wY3O:bfjwvqf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2240e9f88a29c957c379ff9452c0163695319ef1/pkg/roachpb/metadata.proto#L131)):*
> ```protobuf
> // NOTE: Care must be taken when adding or removing fields from this proto
> // because we have code relies on the descriptor comparing Equal() after
> // round-tripping thorough a previous/next version node (i.e. in mixed-version
> ```

"thorough"

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54199)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvserver/replica_command.go, line 2013 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54199#-MGtrMxx35Z4Rm6d1EEY:-MGtwn1yAkTPwtJO8pX6:bx0mxu5) ([raw file](https://github.com/cockroachdb/cockroach/blob/2240e9f88a29c957c379ff9452c0163695319ef1/pkg/kv/kvserver/replica_command.go#L2013)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Are you concerned that we might have similar bugs lurking in other calls to `RangeDescriptor.Equal`? I wonder if we should change the impl of that for this one release.
</blockquote></details>

change it to what? To only look at the generation? Or change `checkDescsEqual` to only look at the generation?

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54199)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @tbg)

___
*[pkg/kv/kvserver/replica_command.go, line 2013 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54199#-MGtrMxx35Z4Rm6d1EEY:-MGuiHmI0XP_jlOYH8Y9:b-5xasor) ([raw file](https://github.com/cockroachdb/cockroach/blob/2240e9f88a29c957c379ff9452c0163695319ef1/pkg/kv/kvserver/replica_command.go#L2013)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

change it to what? To only look at the generation? Or change `checkDescsEqual` to only look at the generation?
</blockquote></details>

Change it to look at everything it currently does _except_ `DeprecatedGenerationComparable`. I wonder if gogoproto has a knob for that. At a minimum, I think you can disable the auto-generation of the method. What do you think?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54199)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @tbg)

___
*[pkg/kv/kvserver/replica_command.go, line 1984 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54199#-MGtrF92E6mtnXyiGB2j:-MHChkDmEk1DLitnXs_I:b2ni76j) ([raw file](https://github.com/cockroachdb/cockroach/blob/2240e9f88a29c957c379ff9452c0163695319ef1/pkg/kv/kvserver/replica_command.go#L1984)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: consider pulling this into a helper, since we do the same thing twice.
</blockquote></details>

n/a
___
*[pkg/kv/kvserver/replica_command.go, line 2013 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54199#-MGtrMxx35Z4Rm6d1EEY:-MHCHYRWBfyhY8weWBui:b-9lh4k1) ([raw file](https://github.com/cockroachdb/cockroach/blob/2240e9f88a29c957c379ff9452c0163695319ef1/pkg/kv/kvserver/replica_command.go#L2013)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Change it to look at everything it currently does _except_ `DeprecatedGenerationComparable`. I wonder if gogoproto has a knob for that. At a minimum, I think you can disable the auto-generation of the method. What do you think?
</blockquote></details>

I had looked for a gogoproto option to skip a field in `Equal()`, but didn't find any.
I was reticent to implement Equal() by hand, but I've worked over it.
___
*[pkg/roachpb/metadata.proto, line 131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54199#-MGtrdN8CWmHgmq6wY3N:-MHCa1Vv581v_VhN6wht:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2240e9f88a29c957c379ff9452c0163695319ef1/pkg/roachpb/metadata.proto#L131)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"thorough"
</blockquote></details>

done

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54199#-:-MHD3zDfDdRfyrFT4mzX:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @tbg)

___
*[pkg/roachpb/metadata.go, line 149 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54199#-MHD3weC55qJc74V2T6n:-MHD3weC55qJc74V2T6o:b-ldanv2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b530e9191279046980b8ac45c0567164aea879db/pkg/roachpb/metadata.go#L149)):*
> ```Go
> }
> 
> func (r *RangeDescriptor) Equal(other *RangeDescriptor) bool {
> ```

This might need a comment.
___
*[pkg/roachpb/metadata.proto, line 143 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54199#-MHD3nOkAs_ch7EI0NUf:-MHD3nOkAs_ch7EI0NUg:bssy09u) ([raw file](https://github.com/cockroachdb/cockroach/blob/b530e9191279046980b8ac45c0567164aea879db/pkg/roachpb/metadata.proto#L143)):*
> ```protobuf
>   option (gogoproto.goproto_stringer) = false;
>   // We implement the Equal method by hand so that it can ignore deprecated
>   // fields.
> ```

Mind mentioning that this is only temporary and that we can remove it in v21.1?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54199)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @nvanbenschoten, and @tbg)

___
*[pkg/roachpb/metadata.proto, line 143 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54199#-MHD3nOkAs_ch7EI0NUf:-MHD8Iyf1oAv3e_YiqiU:bqznzcg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b530e9191279046980b8ac45c0567164aea879db/pkg/roachpb/metadata.proto#L143)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Mind mentioning that this is only temporary and that we can remove it in v21.1?
</blockquote></details>

But is it temporary? I'd rather keep it under our control. The range id and generation should be sufficient for declaring equality.

**Review by nvb — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54199)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @tbg)

___
*[pkg/roachpb/metadata.proto, line 143 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54199#-MHD3nOkAs_ch7EI0NUf:-MHF3GYp9_PUhoHQiNU8:bc092p3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b530e9191279046980b8ac45c0567164aea879db/pkg/roachpb/metadata.proto#L143)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

But is it temporary? I'd rather keep it under our control. The range id and generation should be sufficient for declaring equality.
</blockquote></details>

I would avoid changing the meaning of Equal further (e.g. past field equality) without a full audit of its callers.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54199)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten and @tbg)

___
*[pkg/roachpb/metadata.go, line 149 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54199#-MHD3weC55qJc74V2T6n:-MHMRo_N5nT1WkxcudHA:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b530e9191279046980b8ac45c0567164aea879db/pkg/roachpb/metadata.go#L149)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This might need a comment.
</blockquote></details>

done
___
*[pkg/roachpb/metadata.proto, line 143 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/54199#-MHD3nOkAs_ch7EI0NUf:-MHMSAEP4_ghogLrCGw7:b-761mg1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b530e9191279046980b8ac45c0567164aea879db/pkg/roachpb/metadata.proto#L143)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I would avoid changing the meaning of Equal further (e.g. past field equality) without a full audit of its callers.
</blockquote></details>

I've added a non-committal "this can be reverted..."

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54199#-:-MHMkvabEzaNADfLasJW:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten and @tbg)

**Pull request merged**
