### PR TITLE
opt: first batch of changes for porting the index constraints code

### PR DESCRIPTION
**Pull request by RaduBerinde**
This is the first batch of commits for porting the index constraints code. I broke it up into commits so it's easier to see the diffs - the main changes are in r3->r4 and r4->r5

#### opt: minor cleanup to index constraints code

Moving isIndexedVar out of index_constraint_spans, and moving
in IndexColumnInfo.

Release note: None

#### opt: copy index_constraints_spans code to idxconstraints

This is the first in a series of commits that attempt to port the
index constraints code to a new package that uses the new optimizer
structures (ExprView).

Release note: None

#### opt: copy index_constraints code

Copying the index constraints code; this does not build yet.

Release note: None

#### opt: refactor index constraints code

Refactor the code to use the new opt structures.

The code for computing a remaining filter is not refactored; instead
it is commented out for now.

Release note: None

#### opt: port the index constraints tests

Refactoring (part of) opt_test to an idxconstraints test.

The test file has the Remaining filter results commented out as well
as some test cases that we don't yet support.

Release note: None

### CODE REVIEW

**Comment by andy-kimball** [comment]
Overall, LGTM, just had one substantive factoring comment.

---

Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, 6 of 6 files at r4, 3 of 3 files at r5.
Review status: 7 of 9 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/xform/expr.go, line 263 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22820#-L5njFUGsHXeco9Ce0Pl:-L5njFUGsHXeco9Ce0Pm:b9tdxer) ([raw file](https://github.com/cockroachdb/cockroach/blob/7efbd04cd959985a3d5ca83f1092424886cf2045/pkg/sql/opt/xform/expr.go#L263)):*
> ```Go
> // IsTupleOfConstants returns true if the expression is a TupleOp with ConstOp
> // children.
> func (ev ExprView) IsTupleOfConstants() bool {
> ```

I don't think we want helper methods like this on `ExprView`. It might seem clean now, but it will be a mess in 2-3 years if developers follow this new precedent and add their own specific pattern-matching code to this file. In the spirit of making each class do one thing, and do it well, `ExprView` should be about traversal of the expr tree and nothing more.

I would address this by either copy-pasting simple code like this in multiple locations (DRY blasphemy, I know), or I'd create a separate helper file, maybe called `match.go` to house shared functions like this.

---

*[pkg/sql/opt/xform/expr.go, line 276 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22820#-L5nmus_iSticHAAXXxt:-L5nmus_iSticHAAXXxu:be5tdw5) ([raw file](https://github.com/cockroachdb/cockroach/blob/7efbd04cd959985a3d5ca83f1092424886cf2045/pkg/sql/opt/xform/expr.go#L276)):*
> ```Go
> }
> 
> // IsConstNull returns true if ev is a ConstOp with NULL value.
> ```

Ideally, we create a new `Null` operator, but until then this also would go in `match.go`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22820#-:-L5np7F06wvTQDq106a3:b-emagrb)*

**Comment by RaduBerinde** [comment]
Review status: 7 of 9 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/xform/expr.go, line 263 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22820#-L5njFUGsHXeco9Ce0Pl:-L5nq4E1gNnAwIiOtPj8:b-pz04c1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7efbd04cd959985a3d5ca83f1092424886cf2045/pkg/sql/opt/xform/expr.go#L263)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I don't think we want helper methods like this on `ExprView`. It might seem clean now, but it will be a mess in 2-3 years if developers follow this new precedent and add their own specific pattern-matching code to this file. In the spirit of making each class do one thing, and do it well, `ExprView` should be about traversal of the expr tree and nothing more.

I would address this by either copy-pasting simple code like this in multiple locations (DRY blasphemy, I know), or I'd create a separate helper file, maybe called `match.go` to house shared functions like this.
</blockquote></details>

I will move them. Would they still be methods of ExprView, or should I change to `IsTupleOfConstants(ev ExprView)`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22820)*

**Comment by andy-kimball** [comment]
Review status: 7 of 9 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/xform/expr.go, line 263 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22820#-L5njFUGsHXeco9Ce0Pl:-L5nrLyOC_nJToCRco-O:b-elqkyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/7efbd04cd959985a3d5ca83f1092424886cf2045/pkg/sql/opt/xform/expr.go#L263)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I will move them. Would they still be methods of ExprView, or should I change to `IsTupleOfConstants(ev ExprView)`?
</blockquote></details>

The latter - we want a little shared library of matching functions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22820)*

**Comment by andy-kimball** [comment]
Review status: 7 of 9 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/xform/expr.go, line 263 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22820#-L5njFUGsHXeco9Ce0Pl:-L5nt4mVYP3kEv3kTyto:b5hxm0d) ([raw file](https://github.com/cockroachdb/cockroach/blob/7efbd04cd959985a3d5ca83f1092424886cf2045/pkg/sql/opt/xform/expr.go#L263)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

The latter - we want a little shared library of matching functions.
</blockquote></details>

One other suggestion: maybe we call this `MatchesTupleOfConstants(ev ExprView)` and `MatchesConstNull`. We can establish a pattern of prefixing matching functions like this with `Matches` to keep them nicely grouped.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22820)*

**Comment by RaduBerinde** [comment]
Review status: 5 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/opt/xform/expr.go, line 263 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22820#-L5njFUGsHXeco9Ce0Pl:-L5nvYP_aG1PIJVb5_m_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7efbd04cd959985a3d5ca83f1092424886cf2045/pkg/sql/opt/xform/expr.go#L263)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

One other suggestion: maybe we call this `MatchesTupleOfConstants(ev ExprView)` and `MatchesConstNull`. We can establish a pattern of prefixing matching functions like this with `Matches` to keep them nicely grouped.
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/expr.go, line 276 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/22820#-L5nmus_iSticHAAXXxt:-L5nveSo2VF7kwH-2jbh:b-9d9r5j) ([raw file](https://github.com/cockroachdb/cockroach/blob/7efbd04cd959985a3d5ca83f1092424886cf2045/pkg/sql/opt/xform/expr.go#L276)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Ideally, we create a new `Null` operator, but until then this also would go in `match.go`.
</blockquote></details>

Moved and added a TODO to that effect.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22820)*

**Comment by andy-kimball** [comment]
:lgtm:

---

Review status: 5 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22820#-:-L5nzD3YxPIo8NqT1taL:bnfp4nl)*

**Comment by rytaft** [comment]
Looking good so far. Taking a break and will be back for the other files.

---

Reviewed 1 of 2 files at r1, 1 of 6 files at r4, 2 of 3 files at r5, 1 of 5 files at r7.
Review status: 6 of 9 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/index_constraints_spans.go, line 165 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22820#-L5nqPksPeO72e1jpmmg:-L5nqPksPeO72e1jpmmh:bdk7ku9) ([raw file](https://github.com/cockroachdb/cockroach/blob/906d84b00afd3518b7bbca84007330053068f770/pkg/sql/opt/index_constraints_spans.go#L165)):*
> ```Go
> }
> 
> var _ = ExactPrefix
> ```

Why is this needed?

---

*[pkg/sql/opt/idxconstraint/index_constraints.go, line 32 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22820#-L5nqqxHDmhrMU0Mqs2r:-L5nqqxHDmhrMU0Mqs2s:blbhs9o) ([raw file](https://github.com/cockroachdb/cockroach/blob/906d84b00afd3518b7bbca84007330053068f770/pkg/sql/opt/idxconstraint/index_constraints.go#L32)):*
> ```Go
> // makeEqSpan returns a span that constraints column <offset> to a single value.
> // The value can be NULL.
> func (c *indexConstraintCtx) makeEqSpan(offset int, value tree.Datum) LogicalSpan {
> ```

You're not using the parameter `offset`

---

*[pkg/sql/opt/idxconstraint/index_constraints.go, line 56 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22820#-L5nrCd0JUKupd-Y2BXs:-L5nrCd1wPZfkR5sn60A:b-ecz0o4) ([raw file](https://github.com/cockroachdb/cockroach/blob/906d84b00afd3518b7bbca84007330053068f770/pkg/sql/opt/idxconstraint/index_constraints.go#L56)):*
> ```Go
> }
> 
> // makeStringPrefixSpan returns a span that constraints string column <offset>
> ```

constraints -> constrains

---

*[pkg/sql/opt/idxconstraint/index_constraints.go, line 118 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22820#-L5nsygjVYVmmHeJNbMp:-L5nsygkMzwERHSrTgiW:b-jk2vuo) ([raw file](https://github.com/cockroachdb/cockroach/blob/906d84b00afd3518b7bbca84007330053068f770/pkg/sql/opt/idxconstraint/index_constraints.go#L118)):*
> ```Go
> 				continue
> 			}
> 			spans = append(spans, LogicalSpan{
> ```

why not use `makeEqSpan`?

---

*[pkg/sql/opt/idxconstraint/index_constraints.go, line 176 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22820#-L5nuHRRIzOTyZeuLMqY:-L5nuHRS2eCwFVIN34Qf:b-jcltjb) ([raw file](https://github.com/cockroachdb/cockroach/blob/906d84b00afd3518b7bbca84007330053068f770/pkg/sql/opt/idxconstraint/index_constraints.go#L176)):*
> ```Go
> 		sp := c.makeNotNullSpan(offset)
> 		inclusive := (op == opt.LeOp || op == opt.GeOp)
> 		if (op == opt.LtOp || op == opt.LeOp) == (c.colInfos[offset].Direction == encoding.Ascending) {
> ```

This is a lot of `==` operators! Maybe add a comment to say in words what this is doing?

---

*[pkg/sql/opt/idxconstraint/index_constraints.go, line 205 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22820#-L5nx1ghk1wqXIoEqzgx:-L5nx1ghk1wqXIoEqzgy:b9sgjur) ([raw file](https://github.com/cockroachdb/cockroach/blob/906d84b00afd3518b7bbca84007330053068f770/pkg/sql/opt/idxconstraint/index_constraints.go#L205)):*
> ```Go
> 				// A mask like ABC%Z requires restricting the prefix, but is a stronger
> 				// condition.
> 				tight := (i == len(s)-1) && s[i] == '%'
> ```

Shouldn't you also check '_'?

---

*[pkg/sql/opt/idxconstraint/index_constraints.go, line 357 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22820#-L5ny9ozgBpmr_wZZ1Ds:-L5ny9p-kgARMiLkvESl:bxo8c0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/906d84b00afd3518b7bbca84007330053068f770/pkg/sql/opt/idxconstraint/index_constraints.go#L357)):*
> ```Go
> 		tight = true
> 	} else if !tight {
> 		// If we only keep a prefix, exclusive inequalities become exclusive.
> ```

become exclusive -> become inclusive

---

*[pkg/sql/opt/idxconstraint/index_constraints.go, line 904 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22820#-L5o-454VKsZrXl64bQM:-L5o-454VKsZrXl64bQN:bsuto73) ([raw file](https://github.com/cockroachdb/cockroach/blob/906d84b00afd3518b7bbca84007330053068f770/pkg/sql/opt/idxconstraint/index_constraints.go#L904)):*
> ```Go
> }
> 
> //var constTrueExpr = &Expr{
> ```

Do you need to keep these commented out?

---

*[pkg/sql/opt/idxconstraint/index_constraints.go, line 972 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22820#-L5o-GOAbnSDv0SrvsQX:-L5o-GOAbnSDv0SrvsQY:b-fg95or) ([raw file](https://github.com/cockroachdb/cockroach/blob/906d84b00afd3518b7bbca84007330053068f770/pkg/sql/opt/idxconstraint/index_constraints.go#L972)):*
> ```Go
> }
> 
> //// simplifyFilterImpl is the internal (recursive) implementation of simplifyFilter.
> ```

How about all of this stuff? Do you need to keep it?

---

*[pkg/sql/opt/idxconstraint/index_constraints.go, line 1099 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22820#-L5o-QWpu3SJ-UwU_v3h:-L5o-QWpu3SJ-UwU_v3i:bzbe37d) ([raw file](https://github.com/cockroachdb/cockroach/blob/906d84b00afd3518b7bbca84007330053068f770/pkg/sql/opt/idxconstraint/index_constraints.go#L1099)):*
> ```Go
> //	return remainingFilter
> //}
> var _ = (*indexConstraintCtx).getMaxSimplifyPrefix
> ```

What is this for?

---

*[pkg/sql/opt/idxconstraint/index_constraints.go, line 1145 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22820#-L5o05e0mL_1Bvtjy4C_:-L5o05e0mL_1Bvtjy4Ca:b-5ijwpk) ([raw file](https://github.com/cockroachdb/cockroach/blob/906d84b00afd3518b7bbca84007330053068f770/pkg/sql/opt/idxconstraint/index_constraints.go#L1145)):*
> ```Go
> }
> 
> //// RemainingFilter calculates a simplified filter that needs to be applied
> ```

Do you need this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22820#-:-L5o11InIp-KPRWF4URD:b-8khoq0)*

**Comment by RaduBerinde** [comment]
Review status: 6 of 9 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/index_constraints_spans.go, line 165 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22820#-L5nqPksPeO72e1jpmmg:-L5o5Axff2bqRcEhC47g:b-hyj9lq) ([raw file](https://github.com/cockroachdb/cockroach/blob/906d84b00afd3518b7bbca84007330053068f770/pkg/sql/opt/index_constraints_spans.go#L165)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why is this needed?
</blockquote></details>

Linter complains about unused. It will go away when we actually use this code.

---

*[pkg/sql/opt/idxconstraint/index_constraints.go, line 32 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22820#-L5nqqxHDmhrMU0Mqs2r:-L5o2uaS_gQJFGKbpxgQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/906d84b00afd3518b7bbca84007330053068f770/pkg/sql/opt/idxconstraint/index_constraints.go#L32)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

You're not using the parameter `offset`
</blockquote></details>

Done.

---

*[pkg/sql/opt/idxconstraint/index_constraints.go, line 56 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22820#-L5nrCd0JUKupd-Y2BXs:-L5o2xBI-xnwwGZXM5pr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/906d84b00afd3518b7bbca84007330053068f770/pkg/sql/opt/idxconstraint/index_constraints.go#L56)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

constraints -> constrains
</blockquote></details>

Done.

---

*[pkg/sql/opt/idxconstraint/index_constraints.go, line 118 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22820#-L5nsygjVYVmmHeJNbMp:-L5o35poUx8L-pmEQib7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/906d84b00afd3518b7bbca84007330053068f770/pkg/sql/opt/idxconstraint/index_constraints.go#L118)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

why not use `makeEqSpan`?
</blockquote></details>

Done.

---

*[pkg/sql/opt/idxconstraint/index_constraints.go, line 176 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22820#-L5nuHRRIzOTyZeuLMqY:-L5o4UDiKTnPCPgInIIr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/906d84b00afd3518b7bbca84007330053068f770/pkg/sql/opt/idxconstraint/index_constraints.go#L176)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

This is a lot of `==` operators! Maybe add a comment to say in words what this is doing?
</blockquote></details>

Done.

---

*[pkg/sql/opt/idxconstraint/index_constraints.go, line 205 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22820#-L5nx1ghk1wqXIoEqzgx:-L5o4YVEujYao6KWzc4y:b-tha0hk) ([raw file](https://github.com/cockroachdb/cockroach/blob/906d84b00afd3518b7bbca84007330053068f770/pkg/sql/opt/idxconstraint/index_constraints.go#L205)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Shouldn't you also check '_'?
</blockquote></details>

With '_', the span is not "tight" (it is weaker than the condition).

---

*[pkg/sql/opt/idxconstraint/index_constraints.go, line 357 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22820#-L5ny9ozgBpmr_wZZ1Ds:-L5o4kTJofFKhv4LzP_i:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/906d84b00afd3518b7bbca84007330053068f770/pkg/sql/opt/idxconstraint/index_constraints.go#L357)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

become exclusive -> become inclusive
</blockquote></details>

Done.

---

*[pkg/sql/opt/idxconstraint/index_constraints.go, line 904 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22820#-L5o-454VKsZrXl64bQM:-L5o4meZKm0iLRnVq5GV:b7nzty1) ([raw file](https://github.com/cockroachdb/cockroach/blob/906d84b00afd3518b7bbca84007330053068f770/pkg/sql/opt/idxconstraint/index_constraints.go#L904)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Do you need to keep these commented out?
</blockquote></details>

They don't build as they are. I'm cleaning them up in the next PR.

---

*[pkg/sql/opt/idxconstraint/index_constraints.go, line 972 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22820#-L5o-GOAbnSDv0SrvsQX:-L5o4thdGgQ035xSRdFc:bp76i8r) ([raw file](https://github.com/cockroachdb/cockroach/blob/906d84b00afd3518b7bbca84007330053068f770/pkg/sql/opt/idxconstraint/index_constraints.go#L972)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

How about all of this stuff? Do you need to keep it?
</blockquote></details>

Yes, this is needed and will be refactored in a separate PR. Just wanted to keep the PRs sane.

---

*[pkg/sql/opt/idxconstraint/index_constraints.go, line 1099 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22820#-L5o-QWpu3SJ-UwU_v3h:-L5o5-xguWEgjfDLC3C3:b-yos0ha) ([raw file](https://github.com/cockroachdb/cockroach/blob/906d84b00afd3518b7bbca84007330053068f770/pkg/sql/opt/idxconstraint/index_constraints.go#L1099)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

What is this for?
</blockquote></details>

Some linter complains about unused stuff. It will be cleaned up in the next PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22820)*

**Comment by rytaft** [comment]
Review status: 4 of 9 files reviewed at latest revision, 11 unresolved discussions, some commit checks pending.

---

*[pkg/sql/opt/idxconstraint/index_constraints.go, line 32 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/22820#-L5nqqxHDmhrMU0Mqs2r:-L5oXu33JkG24Sq8fZFp:b-laasec) ([raw file](https://github.com/cockroachdb/cockroach/blob/906d84b00afd3518b7bbca84007330053068f770/pkg/sql/opt/idxconstraint/index_constraints.go#L32)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think you made all of these changes in sql/opt/index_constraints.go, not this file....

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22820)*

**Comment by RaduBerinde** [comment]
Review status: 4 of 9 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/idxconstraint/index_constraints.go, line 32 at r6](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22820#-L5nqqxHDmhrMU0Mqs2r:-L5oZ4AOD4FTDpaln3C6:b-8i20x6) ([raw file](https://github.com/cockroachdb/cockroach/blob/906d84b00afd3518b7bbca84007330053068f770/pkg/sql/opt/idxconstraint/index_constraints.go#L32)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I think you made all of these changes in sql/opt/index_constraints.go, not this file....
</blockquote></details>

Hahaha, so glad you noticed :)  Fixed.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22820)*

**Comment by RaduBerinde** [comment]
Review status: 4 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/sql/opt/idxconstraint/index_constraints.go, line 30 at r11](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22820#-L5oZykbEKOoVH37JsiE:-L5ok7XKE_NCbUnIB84K:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e55d060f64e6d3f59803ff31f5c746b1d75a7418/pkg/sql/opt/idxconstraint/index_constraints.go#L30)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

constraints -> constrains
</blockquote></details>

Done.

---

*[pkg/sql/opt/idxconstraint/spans.go, line 211 at r11](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22820#-L5og4pfrZaKKOz5jeNn:-L5okrfU7gGf52cj3Eko:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e55d060f64e6d3f59803ff31f5c746b1d75a7418/pkg/sql/opt/idxconstraint/spans.go#L211)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

I think this is missing some info - what are the other return values besides 0?
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/match.go, line 17 at r11](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22820#-L5oiaZZ4cAqDnsLIvFG:-L5ol-yl6PkNaWPPuPrI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e55d060f64e6d3f59803ff31f5c746b1d75a7418/pkg/sql/opt/xform/match.go#L17)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

check a -> check the
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22820)*

**Pull request merged**
