### PR TITLE
go.mod: bump Pebble to e25c9d5142cf

### LINKED ISSUE #97076: ccl/kvccl/kvtenantccl: TestTenantUpgrade failed
ccl/kvccl/kvtenantccl.TestTenantUpgrade [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/8691945?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/8691945?buildTab=artifacts#/) on master @ [8511dc08269679b6562f2010ef357c2384649871](https://github.com/cockroachdb/cockroach/commits/8511dc08269679b6562f2010ef357c2384649871):

Fatal error:

```
panic: test timed out after 4m55s

```
Stack: 

```
goroutine 22439 [running]:
testing.(*M).startAlarm.func1()
	GOROOT/src/testing/testing.go:2036 +0x88
created by time.goFunc
	GOROOT/src/time/sleep.go:176 +0x38
```
<details><summary>Log preceding fatal error</summary>
<p>

```
=== RUN   TestTenantUpgrade
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/c33cccbcd49aa55ca01529df00fb9d50/logTestTenantUpgrade2115985398
    test_log_scope.go:79: use -show-logs to present logs inline
=== RUN   TestTenantUpgrade/upgrade_tenant
```
</p>
</details>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/multi-tenant
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestTenantUpgrade.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-24493

Epic CRDB-20293

### PR DESCRIPTION
**Pull request by jbowens**
```
e25c9d51 sstable: fix RewriteKeySuffixes to disallow format changes
1c38c4cb objstorage: break up provider test
```

Close #97076.
Release note: None

### CODE REVIEW

**Review by nicktrav — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98687#-:-NQa2AnA6xPZ6zBsuk6j:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @sumeerbhola)

**Comment by jbowens** [comment]
TFTR!

bors r=nicktrav

**Comment by jbowens** [comment]
bors r=nicktrav

**Review by sumeerbhola — APPROVED** [review]
Thanks for doing this!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98687#-:-NQadSqeAeMev_5qCSX4:bxgavm9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Pull request merged**
