### PR TITLE
backupccl: split up backup/restore code

### PR DESCRIPTION
**Pull request by dt**
This is change is purely moving without any changes.

All the helpers for looking up, resolving, finding, etc SQL descriptor targets
is moved to targets.go where the descriptor resolver was already.

Helpers for fetching, writing, encryption, etc backup manifests are moved to
manifest_handling.go.

The remaining code is split between the statement that plans a backup or restore
in a planHook up to the point of creating a job record versus the code that is
actually run to execute that job.

Release note: none.

### CODE REVIEW

**Comment by dt** [comment]
Added a third commit which is essentially s/backupDesc(riptor)?/backupManifest/

**Review by pbardea — APPROVED** [review]
LGTM. Minor thing, which I'm not sure about. Should the year in the copyright of the newly updated files be updated?

> Reviewed 2 of 2 files at r1, 4 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44866#-:-M-hSeqv69UzBiWEIQVr:bnoc9cz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea)

**Comment by dt** [comment]
I believe the usual answer is no: if we’re just splitting an existing file as opposed to creating an original work, the pieces retain the original file’s date (but AFAIK, it also probably doesn’t matter)

**Pull request merged**
