### PR TITLE
ccl: checksum backup/restore files

### LINKED ISSUE #13482: sqlccl: figure out import/export checksums (for backup/restore)
Backup (via export) creates a number of files containing data and saves the path of each file with its checksum in a BackupDescriptor. We need to decide how we plan to use these checksums during restore (via import) and also which checksum to use.

If we only care about the checksum as a basic verification that files referenced in the BackupDescriptor haven't been changed in the interim, we could piggyback on the one kept by the various cloud storages (md5 for s3/azure, crc32c for gcs) and avoid the need to compute it ourselves.

If we want to verify the actual bytes as received on the CockroachDB nodes, we're free to pick any checksum we like. This will definitely be necessary if we ever use AddFile (or something like it), but even if not, we may want to go this route to defend against corruptions when fetching the file.

@bdarnell has expressed a preference for sha256 over crc32c (https://reviewable.io/reviews/cockroachdb/cockroach/13417#-KcOVgrrYgcdoNoCn8kj) but it looks like the go stdlib implementation of it only operates on byte slices (https://golang.org/pkg/crypto/sha256/), which is a little unfortunate.

cc @dt @mjibson

### PR DESCRIPTION
**Pull request by danhhz**
To make sure the files in the restore are the same ones from the backup
and to make sure no errors occured in any intermediate transmission or
storage.

Seems like the benchmarks are a bit slower for backp, but it's in the
noise.

Closes #13482.

```
name              old time/op    new time/op    delta
ClusterBackup-8     1.09µs ± 8%    1.18µs ±14%    ~             (p=0.095 n=5+5)
ClusterRestore-8    5.25µs ± 7%    4.97µs ± 4%  -5.25%          (p=0.032 n=5+5)

name              old speed      new speed      delta
ClusterBackup-8    113MB/s ± 8%   104MB/s ±13%    ~             (p=0.095 n=5+5)
ClusterRestore-8  23.5MB/s ± 6%  24.7MB/s ± 4%  +5.41%          (p=0.032 n=5+5)

name              old alloc/op   new alloc/op   delta
ClusterBackup-8       188B ±31%      193B ±56%    ~             (p=0.508 n=5+5)
ClusterRestore-8    7.63kB ± 4%    7.86kB ± 5%    ~             (p=0.151 n=5+5)

name              old allocs/op  new allocs/op  delta
ClusterBackup-8       3.00 ± 0%      3.00 ± 0%    ~     (all samples are equal)
ClusterRestore-8      2.00 ± 0%      2.00 ± 0%    ~     (all samples are equal)
```
cc @bdarnell

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13861)

### CODE REVIEW

**Comment by mjibson** [comment]
I think it is worth it to add a test that mutates or appends to a backup to guarantee failure during restore, just to test that this thing is on.

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/ccl/sqlccl/backup.proto, line 35 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13861#-Ke7aVBvLiWCwA2IJtz-:-Ke7aVBvLiWCwA2IJtz0:bj7pqbe) ([raw file](https://github.com/cockroachdb/cockroach/blob/eec2e496438a78c2f671181d6f7175bdb94ddcce/pkg/ccl/sqlccl/backup.proto#L35)):*
> ```protobuf
>     string path = 2;
>     bytes sha512 = 4;
>     reserved 3;
> ```

The other `reserved` keywords in the proto files have retained their position instead of being sorted to the bottom.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13861#-:-Ke7aAmQIdDGs3npG5Mk:b8m7v3k)*

**Comment by danhhz** [comment]
Added a test

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/ccl/sqlccl/backup.proto, line 35 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13861#-Ke7aVBvLiWCwA2IJtz-:-KeQ6M1Mc4DGi_wLg9qn:bskaa90) ([raw file](https://github.com/cockroachdb/cockroach/blob/eec2e496438a78c2f671181d6f7175bdb94ddcce/pkg/ccl/sqlccl/backup.proto#L35)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

The other `reserved` keywords in the proto files have retained their position instead of being sorted to the bottom.
</blockquote></details>

This isn't quite universal, but done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13861#-:-KeQBySW4Uw_xWfua4sz:bkdqbhy)*

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13861#-:-Ke_4mkOrTXHCHqKTPrm:bnfp4nl)*

**Comment by danhhz** [comment]
TFTR!

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13861#-:-Ke_5Td2UYeWxEc7xwua:b-814g8k)*

**Pull request merged**
