### PR TITLE
ui: ux updates to console jobs page

### LINKED ISSUE #85253: Jobs Pages - UI/UX improvements
- [ ] We should probably have the Execution Count and Last Execution Time columns next to each other.
- [ ] The jobs overview table does not have a horizontal scrollbar. As a result, users can't see the entirety of the table.
- [ ] There are probably too many columns by default. We should add a column picker.
- [ ] In the CC Console, the filters take a very long time to take effect. We need to speed this up.

image

Jira issue: CRDB-18138

### PR DESCRIPTION
**Pull request by ericharmeling**
This commit refactors the JobsPage and JobsTable components that
make up the Jobs Page in the DB/CC consoles, with the following
changes:

- The Jobs Page now includes a column picker.
- The Jobs Table now includes a horizontal scroll bar.
- The local Jobs options are now used to filter full Jobs Responses on
the frontend, with all jobs requested by default from the backend.
- The Execution Count and Last Execution Time columns are now adjacent.

Fixes https://github.com/cockroachdb/cockroach/issues/85253.

Release note (ui change): The Jobs Page now includes a column picker.

CC Console Loom: https://www.loom.com/share/55195521dc5d4105a10c7dfc3c6fb7cc

DB Console Loom: https://www.loom.com/share/b94dccccd0564d27b5fc5e9869753a0b

### CODE REVIEW

**Review by maryliag — APPROVED** [review]
just a small nit, otherwise :lgtm: 

> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89678#-:-NECJQXQ61b56F7hRM_8:boph6aq)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling)

___
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89678#-NECJDhH4MEmrpBn51IW):*
since it's not fixing all the items from the issue, you should change to "partially addresses" and then check on the issue which ones are fixed
___
*[`pkg/ui/workspaces/cluster-ui/src/pagination/pagination.module.scss` line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89678#-NECIq1c2aKvF9AEAIHE:-NECIq1c2aKvF9AEAIHF:b-sgbk1f) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca316877f088bba7978ddc662b875b2b5e193a59/pkg/ui/workspaces/cluster-ui/src/pagination/pagination.module.scss#L40)):*
> ```SCSS
>   text-align: center;
>   float: unset;
>   margin-bottom: 10px;
> ```

nit: use `$spacing-smaller`
___
*[`pkg/ui/workspaces/cluster-ui/src/sortedtable/sortedtable.module.scss` line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89678#-NECJ-hw29egJQYb2794:-NECJ-hw29egJQYb2795:b-sgbk1f) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca316877f088bba7978ddc662b875b2b5e193a59/pkg/ui/workspaces/cluster-ui/src/sortedtable/sortedtable.module.scss#L117)):*
> ```SCSS
>   justify-content: left;
>   align-items: center;
>   margin-bottom: 12px;
> ```

nit: use `$spacing-smaller`

**Review by ericharmeling — COMMENTED** [review]
TFTR

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89678#-:-NECXUde8ZcWlmytQScn:bb73zsl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @maryliag)

___
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89678#-NECJDhH4MEmrpBn51IW):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

since it's not fixing all the items from the issue, you should change to "partially addresses" and then check on the issue which ones are fixed
</blockquote></details>

I believe this commit does fix all of the items in the issue - I just neglected to list all of them here :). Fixed.

Let me know if you don't think the commit resolves any of the issues listed though!
___
*[`pkg/ui/workspaces/cluster-ui/src/pagination/pagination.module.scss` line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89678#-NECIq1c2aKvF9AEAIHE:-NECXCTf1Iejx2rfTREd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca316877f088bba7978ddc662b875b2b5e193a59/pkg/ui/workspaces/cluster-ui/src/pagination/pagination.module.scss#L40)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: use `$spacing-smaller`
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/sortedtable/sortedtable.module.scss` line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89678#-NECJ-hw29egJQYb2794:-NECXD9M8oIPLyPhIQAM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca316877f088bba7978ddc662b875b2b5e193a59/pkg/ui/workspaces/cluster-ui/src/sortedtable/sortedtable.module.scss#L117)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: use `$spacing-smaller`
</blockquote></details>

Done.

**Review by maryliag — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89678)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ericharmeling)

___
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89678#-NECJDhH4MEmrpBn51IW):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

I believe this commit does fix all of the items in the issue - I just neglected to list all of them here :). Fixed.

Let me know if you don't think the commit resolves any of the issues listed though!
</blockquote></details>

Oh I think I missed the fix for the filters that were taking too long

**Review by ericharmeling — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89678)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @maryliag)

___
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89678#-NECJDhH4MEmrpBn51IW):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

Oh I think I missed the fix for the filters that were taking too long
</blockquote></details>

You're right. I thought adding the additional componentDidUpdate refresh was speeding it up, but it's still not nearly as fast as it should be.


Before, the refresh was sending a new request to the jobs endpoint, using the local storage parameters as request parameters. Instead, we should just get all of the jobs and then dynamically filter them on the frontend. So I've reworked the jobs options to do that. And I also updated the sagas to stop refreshing so frequently. Should work as expected now.

**Review by maryliag — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89678)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ericharmeling)

___
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89678#-NECJDhH4MEmrpBn51IW):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

You're right. I thought adding the additional componentDidUpdate refresh was speeding it up, but it's still not nearly as fast as it should be.


Before, the refresh was sending a new request to the jobs endpoint, using the local storage parameters as request parameters. Instead, we should just get all of the jobs and then dynamically filter them on the frontend. So I've reworked the jobs options to do that. And I also updated the sagas to stop refreshing so frequently. Should work as expected now.
</blockquote></details>

The reason why the filter was done on the backend was because some cluster could have a lot of jobs, so forcing limit 50 instead of all would help with that issue, but if you filter the amount on the frontend, this improvement get lost, so I think the limit should be done indeed on the backend.
Now if you add the limit 50 on the backend, but the filter type on the frontend, you could have a case that your 50 doesn't have any of the type selected and it won't show anything, instead of the case of passing both values to the backend and making sure you have the right results.

There are a few options here: 
- making sure if the limit 50 is selected, you're returning 50 of each type (and then the frontend can filter by the selection)
- make a new request for each selection, but add a loading of some sort on the page, because the weird thing was that once you had a new selection, the page wouldn't change for awhile, so you wouldn't know something was happening. But adding a loading can help that (you should still keep current values on the page so they still see something while you're retrieving the new data)
- make a new request each time, but save each option on cache, with the key being type-limit, so now when you make a selection you can show what you have on cache right away (if you have something), while you make a new call to update the data

**Review by ericharmeling — COMMENTED** [review]
I updated the PR to address the filter bug. I've also added updated looms for both CC console and DB console.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89678#-:-NEbWoNY-z7Tj7jvs4Nm:b-wq6z5m)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @maryliag)

___
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89678#-NECJDhH4MEmrpBn51IW):*
> The reason why the filter was done on the backend was because some cluster could have a lot of jobs, so forcing limit 50 instead of all would help with that issue, but if you filter the amount on the frontend, this improvement get lost, so I think the limit should be done indeed on the backend.

Makes a lot of sense. We don't want to lose that optimization.

> making sure if the limit 50 is selected, you're returning 50 of each type (and then the frontend can filter by the selection)

This sounds like the best option to me. It is the easiest to implement, and I think it resolves the issue with the filter scalability.

**Review by maryliag — COMMENTED** [review]
> Reviewed 4 of 6 files at r3, 4 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89678)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ericharmeling)

___
*[`pkg/ui/workspaces/cluster-ui/src/jobs/jobsPage/jobsPage.tsx` line 44 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89678#-NEfTRrp02jtJgWgGcrY:-NEfTRrp02jtJgWgGcrZ:b11v5oe) ([raw file](https://github.com/cockroachdb/cockroach/blob/83e555d9b3d466a370f5ce5c75241ef703a31075/pkg/ui/workspaces/cluster-ui/src/jobs/jobsPage/jobsPage.tsx#L44)):*
> ```XML
> 
> export const DEFAULT_JOBS_REQUEST = new cockroach.server.serverpb.JobsRequest({
>   limit: 50 * typeOptions.length * statusOptions.length,
> ```

just increasing the limit won't guarantee you will have 50 of each type. You might be returning all from a same type

**Review by maryliag — COMMENTED** [review]
One suggestion I can make is keep this PR with the most straight forward fixes, update the description to say this PR is `Part Of` instead of `Fixes`, and then do a following PR focused just on the filter improvements. (You can change back the filter to just 50 instead of the 50 * options for this PR for example, but keep the default as 50)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89678#-:-NEfTn5UBQRLxvlzAwGw:bqkdnr4)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ericharmeling)

**Review by ericharmeling — COMMENTED** [review]
> One suggestion I can make is keep this PR with the most straight forward fixes, update the description to say this PR is Part Of instead of Fixes, and then do a following PR focused just on the filter improvements. (You can change back the filter to just 50 instead of the 50 * options for this PR for example, but keep the default as 50)

Okay - I'll do that. For now, I'll just use the local settings for the frontend (with a default show of 50) filters, and then just request all of the jobs from the server. This will mean we lose the limit optimization in clusters with a lot of jobs, but I can leave that for another PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89678#-:-NEfdKE_EcS9CbT6QBm_:b3y8jjt)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/jobs/jobsPage/jobsPage.tsx` line 44 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/89678#-NEfTRrp02jtJgWgGcrY:-NEfd4qN4MHVgUiRChkQ:b-m5s1z8) ([raw file](https://github.com/cockroachdb/cockroach/blob/83e555d9b3d466a370f5ce5c75241ef703a31075/pkg/ui/workspaces/cluster-ui/src/jobs/jobsPage/jobsPage.tsx#L44)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

just increasing the limit won't guarantee you will have 50 of each type. You might be returning all from a same type
</blockquote></details>

:face_palm:

You're right.

**Review by ericharmeling — COMMENTED** [review]
As we discussed offline, we can probably keep the request parameters separate from the local filter options for now. So, with this PR, the jobs page pulls all jobs from the admin server by default, and the page filters all jobs on the frontend based on dropdown option selections stored in the "local settings" redux store, with all jobs stored in the "jobs" redux store. 

The biggest concern here is that pulling all jobs at the refresh interval (currently set at 10 seconds) will make loading/refreshing the page slow. However, since jobs are cleared every two weeks, and the number of jobs is likely much smaller than the number of statements, the request time shouldn't be any worse than that of the statements page over a similar time scale. 

Users are unlikely to run into a request timeout (currently set at 10 minutes in DB console and 30 minutes for CC console). But, to test the timeout scenario, I lowered the timeout in CC console to 1ms and tried loading the page. When a timeout occurs, the web console reports a 504 error ("Gateway Timeout"):

```
main.js:1582          GET http://localhost:8081/db-console/fd7a9943-1f32-4e6e-9a05-278359f431bb/us-central1/0/_admin/v1/jobs?status=&type=0&limit=0 504 (Gateway Timeout)
```

It doesn't look like this error is passed through to the Jobs Page component as a JobsError though. The actual Jobs page keeps "loading", does not display an error on the page itself, and will attempt a new request at the refresh interval. I did update the delay message to *not* suggest using filters to speed up the jobs request, as this will do nothing to the request parameters.

I've also updated the commit and PR messages to fix https://github.com/cockroachdb/cockroach/issues/85253, since this PR resolves all of the UX problems listed in that issue. I opened a separate issue to track the filter optimization: https://github.com/cockroachdb/cockroach/issues/90252

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89678#-:-NEkdp1jCDDx6W2mgTuD:boba5u0)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @maryliag)

**Review by maryliag — APPROVED** [review]
just a small nit, otherwise :lgtm: 

> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89678#-:-NEusWix7whWhfPz5uh5:boph6aq)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling)

___
*[`pkg/ui/workspaces/cluster-ui/src/jobs/jobsPage/jobsPage.tsx` line 129 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89678#-NEus55z-Jmwo5tSdygE:-NEus55z-Jmwo5tSdygF:bcgwofj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5a6b39132136c0a8054df7f50531539a08a550b/pkg/ui/workspaces/cluster-ui/src/jobs/jobsPage/jobsPage.tsx#L129)):*
> ```XML
> 
>   componentDidMount(): void {
>     // Refresh every 10 seconds
> ```

any reason for the removal of this comment? isn't still valid?
we want to keep updating because the status of jobs are also updating.

**Review by ericharmeling — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89678#-:-NEv4xMm99tFGnNj1pBN:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/jobs/jobsPage/jobsPage.tsx` line 129 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89678#-NEus55z-Jmwo5tSdygE:-NEv4VvT9u6BAdPwLdxy:bal4xqj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5a6b39132136c0a8054df7f50531539a08a550b/pkg/ui/workspaces/cluster-ui/src/jobs/jobsPage/jobsPage.tsx#L129)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

any reason for the removal of this comment? isn't still valid?
we want to keep updating because the status of jobs are also updating. 
</blockquote></details>

It's still valid! I think I accidentally removed the comment when testing out different values.

**Comment by ericharmeling** [comment]
blathers backport release-22.2

**Pull request merged**
