### PR TITLE
release-21.1: server,sql,kvtenantccl: start a path to upgrading tenants

### PR DESCRIPTION
**Pull request by ajwerner**
Backport 9/9 commits from #60730.

/cc @cockroachdb/release

---

This PR provides support for upgrading tenant clusters from 20.2 to 21.1. The protocol
is sketched out in `tenant_cluster.go`. See individual commits. 

Release note: None

### CODE REVIEW

**Comment by ajwerner** [comment]
@tbg I'm ooo all week. The backport was clean. Please press the button if it looks good to you.

**Comment by tbg** [comment]
I'm inclined to hold off until 21.1.1, as the release branch is currently clean. This should be ok, since the only user of this is CC and they can make sure they're running a patch release that has this code before the major upgrade.

cc @andy-kimball @alyshanjahani-crl let me know if there's any pressing reason this needs to be in 21.1.0.

**Comment by andy-kimball** [comment]
Wouldn't we need to be running a patched version of 20.2 in order to _upgrade_ to 21.1 safely? What does this patch to 21.1 have to do with CC? Or is that your point? Do we have another PR that applies this patch to 20.2?

**Comment by tbg** [comment]
CC won't be attempting to upgrade from 21.1.0 into 21.2.x, we can expect CC to run at least 21.1.1 before attempting the next major upgrade.

By the way, I think it is possible to upgrade from 20.2 to 21.1.1 if you so desire, assuming you never run v21.1.0 (i.e. go straight into 21.1.1) or are willing to do an extra "SET CLUSTER SETTING version" step on all tenants before attempting the upgrade (which will backfill the cluster version for tenants created under 21.1.0).

**Comment by ajwerner** [comment]
@tbg is it time?

**Comment by tbg** [comment]
It is time! Sorry somehow missed this ping.

**Comment by ajwerner** [comment]
TFTR!

**Pull request merged**
