### PR TITLE
colexec: hooking up disk/mem monitors to explain analyze

### LINKED ISSUE #45231: colexec: add memory and disk usage statistics to EXPLAIN ANALYZE

### PR DESCRIPTION
**Pull request by Azhng**
Release justification: low risk, high benefit changes to
existing functionality, since adding disk/mem usage to
explain analyze is relatively non-intrusive change and
it helps end users to better understand their query

Release note (sql change): explain analyze in vectorized
engine displays memory and disk usage for the query

Closes #45231

rowexec: omits allocation stats in explain analyze if it is zero

Release justification: low risk, high benefit changes to existing
functionality

Release note (sql change): explain analyze will omits allocation
stats if it is zero

### CODE REVIEW

**Review by asubiotto — COMMENTED** [review]
Going back to our conversation during our standup, did you consider passing in a reference to a memory/disk monitor to the vectorized stats collector? I think it's beneficial to do this in order to avoid implementing a chain of `memAllocStatExporter` and `diskAllocStatExporter`. This also means that awareness of stat collection remains in the planning phase so operators don't need to worry about it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46316#-:-M2s4o3v7Za3NX_i_jcH:boe1pww)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by Azhng — COMMENTED** [review]
Actually spent more time thinking about it and found out that I can directly get the monitors from the new operator results. 

Updated to let stats collector have access to disk/mem monitors 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46316#-:-M2tPdP77hDRC0yjgMdB:b-ahztoc)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 4 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46316)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/sql/colexec/execpb/stats.go, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46316#-M366XMb7Ie1YyA6IPkW:-M366XMb7Ie1YyA6IPkX:b8vid6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8561c21d66b632d9d6de2352137f16faae260fe/pkg/sql/colexec/execpb/stats.go#L64)):*
> ```Go
> 	stallTimeQueryPlanSuffix      = "stall time"
> 	executionTimeQueryPlanSuffix  = "execution time"
> 	maxMemoryBytesQueryPlanSuffix = "max memory allocated"
> ```

In the row engine this is displayed as `max memory used`. I think users might get confused by the difference. Maybe it would be better to make this `max vectorized {memory, disk} used`?
___
*[pkg/sql/colflow/vectorized_flow.go, line 316 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46316#-M366k2U7zAhuJW0e1Z2:-M366k2U7zAhuJW0e1Z3:b-kjzhun) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8561c21d66b632d9d6de2352137f16faae260fe/pkg/sql/colflow/vectorized_flow.go#L316)):*
> ```Go
> 	var diskMonitors, memMonitors []*mon.BytesMonitor
> 	for _, m := range monitors {
> 		if strings.Contains(m.Name(), "disk") {
> ```

This might be a bit brittle. I would at least extract a constant and use that both here and when creating disk monitors in the vectorized engine. The other option I prefer is to add a public accessor for the `resource` field in `bytes_usage.go` and check the type here instead of exposing `Name`.
___
*[pkg/sql/colflow/vectorized_flow.go, line 646 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46316#-M367xtXCs24YUw-OK10:-M367xtXCs24YUw-OK11:b-y5elq1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8561c21d66b632d9d6de2352137f16faae260fe/pkg/sql/colflow/vectorized_flow.go#L646)):*
> ```Go
> 			foundLocalOutput = true
> 			if s.recordingStats {
> 				mons := []*mon.BytesMonitor{hashRouterMemMonitor, diskMon}
> ```

This is interesting. We only usually have one output per hash router and what you're doing here is passing in the stats for the hash router in general, not for a specific output. Since these stats are not actually output in `EXPLAIN ANALYZE` (they don't get displayed) but can be found in the trace, I think it's fine to leave it as is, but we probably will want to distinguish between outputs at some point (and give each one a separate monitor both for memory and disk).

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46316)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/execpb/stats.go, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46316#-M366XMb7Ie1YyA6IPkW:-M36syOw16lV1CCHqHfP:b-hboohw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8561c21d66b632d9d6de2352137f16faae260fe/pkg/sql/colexec/execpb/stats.go#L64)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

In the row engine this is displayed as `max memory used`. I think users might get confused by the difference. Maybe it would be better to make this `max vectorized {memory, disk} used`?
</blockquote></details>

Done 

Do we also want to rename it for the tag suffix above ? 
___
*[pkg/sql/colflow/vectorized_flow.go, line 316 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46316#-M366k2U7zAhuJW0e1Z2:-M37-Plk-arsFtrBFCwB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8561c21d66b632d9d6de2352137f16faae260fe/pkg/sql/colflow/vectorized_flow.go#L316)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This might be a bit brittle. I would at least extract a constant and use that both here and when creating disk monitors in the vectorized engine. The other option I prefer is to add a public accessor for the `resource` field in `bytes_usage.go` and check the type here instead of exposing `Name`.
</blockquote></details>

Done.
___
*[pkg/sql/colflow/vectorized_flow.go, line 646 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46316#-M367xtXCs24YUw-OK10:-M373myt4QJN9trVNmNr:b-1opf3z) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8561c21d66b632d9d6de2352137f16faae260fe/pkg/sql/colflow/vectorized_flow.go#L646)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This is interesting. We only usually have one output per hash router and what you're doing here is passing in the stats for the hash router in general, not for a specific output. Since these stats are not actually output in `EXPLAIN ANALYZE` (they don't get displayed) but can be found in the trace, I think it's fine to leave it as is, but we probably will want to distinguish between outputs at some point (and give each one a separate monitor both for memory and disk).
</blockquote></details>

Created issue https://github.com/cockroachdb/cockroach/issues/46419

**Review by asubiotto — COMMENTED** [review]
> Reviewed 2 of 12 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46316)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @Azhng)

___
*[pkg/sql/colexec/execpb/stats.go, line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46316#-M366XMb7Ie1YyA6IPkW:-M37Lwiy49oS7oP-lO35:bgesttl) ([raw file](https://github.com/cockroachdb/cockroach/blob/e8561c21d66b632d9d6de2352137f16faae260fe/pkg/sql/colexec/execpb/stats.go#L64)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Done 

Do we also want to rename it for the tag suffix above ? 
</blockquote></details>

Yes, that's what will be output in the traces as the key.
___
*[pkg/util/mon/bytes_usage.go, line 457 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46316#-M37MDEj9o5-eehLGCMa:-M37MDEj9o5-eehLGCMb:bv51awu) ([raw file](https://github.com/cockroachdb/cockroach/blob/7430e2811419f809411cd36fcb89c384ae2ef864/pkg/util/mon/bytes_usage.go#L457)):*
> ```Go
> func (mm *BytesMonitor) MonitorType() MonitorType {
> 	var typ MonitorType
> 	if _, ok := mm.resource.(memoryResource); ok {
> ```

nit: I think this code might be easier to read:
```
switch mm.resource.(type) {
    case memoryResource:
    case diskResource:
    default:
        error
}
```

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46316)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @Azhng)

___
*[pkg/sql/colexec/stats.go, line 43 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/46316#-M38Wjh5DuCvyVi_pfoX:-M38Wjh689syAT-Kbo2k:b-nusuau) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2b384f122ae991b1a1eb064ee281d38515bb41e/pkg/sql/colexec/stats.go#L43)):*
> ```Go
> 	outputWatch *timeutil.StopWatch
> 
> 	diskMonitors []*mon.BytesMonitor
> ```

super nit: usually "memory" monitors are used before "disk" ones.
___
*[pkg/sql/colexec/stats.go, line 58 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/46316#-M38X3ai1R3IxUgEp89H:-M38X3ai1R3IxUgEp89I:b-nnassj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2b384f122ae991b1a1eb064ee281d38515bb41e/pkg/sql/colexec/stats.go#L58)):*
> ```Go
> 	isStall bool,
> 	inputWatch *timeutil.StopWatch,
> 	diskMonitors []*mon.BytesMonitor,
> ```

ditto to switch the order
___
*[pkg/sql/colexec/stats_test.go, line 34 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/46316#-M38X6wv2w-9geu6Qy5a:-M38X6wv2w-9geu6Qy5b:buxvjaf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2b384f122ae991b1a1eb064ee281d38515bb41e/pkg/sql/colexec/stats_test.go#L34)):*
> ```Go
> 	noop := NewNoop(makeFiniteChunksSourceWithBatchSize(nBatches, coldata.BatchSize()))
> 	vsc := NewVectorizedStatsCollector(noop, 0 /* id */, true /* isStall */, timeutil.NewStopWatch(),
> 		nil, nil)
> ```

super nit: it's nice to have inlined comments for `nil` parameters.
___
*[pkg/sql/logictest/testdata/logic_test/dist_vectorize, line 59 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/46316#-M38ZflP9pr4tAFMkfYq:-M38ZflP9pr4tAFMkfYr:bktua3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2b384f122ae991b1a1eb064ee281d38515bb41e/pkg/sql/logictest/testdata/logic_test/dist_vectorize#L59)):*
> ```
> SELECT url FROM [EXPLAIN ANALYZE SELECT * FROM kv JOIN kw ON kv.k = kw.k]
> ----
> https://cockroachdb.github.io/distsqlplan/decode.html#eJzcl11vo0YUhu_7K0bnarc7DgyY7AZpJadtKnmbtbdJLtqufEHgNEbGDB0GJ2mU_15hWqXB8RzIaCOUO3_wwLzHzysd30H5VwYhnJ-cnvx4wSqVsZ_P5p_Z15PfvpweT2fseHZ8-vsfJ-zNT9Pzi_NfT9-yfy_9vrlwtWGf5tMZW12z-YytNgcr9pGtrg9WC-CQywRn0RpLCL-CAA4ecPCBwxg4BLDgUCgZY1lKVV9ytwWmyQ2ELoc0Lypdf7zgEEuFEN6BTnWGEMJFdJnhGUYJKscFDgnqKM22jylUuo7U7WS1AQ7nRZSXIRs59YMvIx0vsWSy0kWlQ1YfSFdF1vqoxAxjnW5SfRsy98Ct71_qKMuYTtcYMreExT2HBmmO_d-xLm_ZMiqXjw80EbC4X2zvcYUQinv-vJyHe3JeP-R0xJCSenuTPtxHqgQVJu37vKsf3OmqJ4b2GdUVfpJpjsoRLTsy_FO_mYh3bz-q9GrZvAQO83okE8EnHp_4fDK2myHeYFzpVOYPc-Swjm7YBmMtVfo3JmyNa6luWZRlMo40JiELXPZL-kNr4g_T9DtMs8qfmtSTQ5rJkSwcETweTzt0sBs66B56X5TxoyiiewUEXXXHGzn-YCognpv0fYeyDyqptzfpC5ZdvM6ye9298To0xB85lpm_WUN6JP3QoSGDSurtTfqCDfFeZ0P87t74HRoyHjnBYLwRz0161KEhg0rq7U36gg3xX2dDxt29GXdoSDAajDXiuTkDuh8jR7AoT5hgUi9RDSaztzfzCzZl_DqbQvwlP8OykHmJrb9YT9_ZrYeIyRU2P00pKxXjFyXj7WOat_Mtt92ZEyx1863XvJnmzVf1AbvDhzbwkQ0srM4tAjMteozM6wcf2sBHNrCwOndrZDu016bd_9O-ed6-ERaPZ-a26bGN4GaYENwME4KbYUpwgiYED2wEN8OE4GaYENwMU4ITNCH4oY3g720UNcOEomaYUNQMU4oSNKHoBxtFzTChqBkmFDXDlKIETSh6ZKOosNoTCJqQlKAJSwma0pTCqV3Bblmw2xbs1gXLfcFuYRBWG4PYWRl62WqmKVvNNGWrmSZtJXDK1j7L0u5v1mdb6ktTtvbal3rjlK07y4PR1sX9d_8EAAD___mDJ6M=
> ```

I noticed that this plan contains non-zero memory. In logic tests it should be 0. To fix this we need to update `finishVectorizedStatsCollectors` method to set memory and disk usage to 0 if `DeterministicStats` flag is set.
___
*[pkg/util/mon/bytes_usage.go, line 244 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/46316#-M38ZH3z6Unx719swXBo:-M38ZH3z6Unx719swXBp:beyhcip) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2b384f122ae991b1a1eb064ee281d38515bb41e/pkg/util/mon/bytes_usage.go#L244)):*
> ```Go
> 
> // MonitorType specify the type of resource this monitor is tracking.
> type MonitorType int
> ```

I think we already have `mon.Resource` type that should serve our needs. We could simply add a getter method (i.e. `BytesMonitor.Resource() Resource`) to expose `resource` field and then compare that against `mon.DiskResource` directly.
___
*[pkg/util/mon/bytes_usage.go, line 463 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/46316#-M38Z3mYCLi91G6q7iI7:-M38Z3mZ08gGLcS1Gekm:b48sp30) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2b384f122ae991b1a1eb064ee281d38515bb41e/pkg/util/mon/bytes_usage.go#L463)):*
> ```Go
> 		typ = DiskMonitorType
> 	default:
> 		execerror.VectorizedInternalPanic(
> ```

We should not be dragging `execerror` here, use regular `panic` instead.

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46316)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/stats.go, line 43 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/46316#-M38Wjh5DuCvyVi_pfoX:-M3CqKOhAqzoizkaUGqw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2b384f122ae991b1a1eb064ee281d38515bb41e/pkg/sql/colexec/stats.go#L43)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

super nit: usually "memory" monitors are used before "disk" ones.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/stats.go, line 58 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/46316#-M38X3ai1R3IxUgEp89H:-M3CqKkj4oa0x3sMUkWD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2b384f122ae991b1a1eb064ee281d38515bb41e/pkg/sql/colexec/stats.go#L58)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

ditto to switch the order
</blockquote></details>

Done.
___
*[pkg/sql/colexec/stats_test.go, line 34 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/46316#-M38X6wv2w-9geu6Qy5a:-M3CqLg-B1DAQx08tKb4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2b384f122ae991b1a1eb064ee281d38515bb41e/pkg/sql/colexec/stats_test.go#L34)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

super nit: it's nice to have inlined comments for `nil` parameters.
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/dist_vectorize, line 59 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/46316#-M38ZflP9pr4tAFMkfYq:-M3Cry5Y8qBQ7I1XNjzW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2b384f122ae991b1a1eb064ee281d38515bb41e/pkg/sql/logictest/testdata/logic_test/dist_vectorize#L59)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I noticed that this plan contains non-zero memory. In logic tests it should be 0. To fix this we need to update `finishVectorizedStatsCollectors` method to set memory and disk usage to 0 if `DeterministicStats` flag is set.
</blockquote></details>

Done.
___
*[pkg/util/mon/bytes_usage.go, line 244 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/46316#-M38ZH3z6Unx719swXBo:-M3Cuk4r6Pg1HdLyxV8A:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2b384f122ae991b1a1eb064ee281d38515bb41e/pkg/util/mon/bytes_usage.go#L244)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think we already have `mon.Resource` type that should serve our needs. We could simply add a getter method (i.e. `BytesMonitor.Resource() Resource`) to expose `resource` field and then compare that against `mon.DiskResource` directly.
</blockquote></details>

Done.
___
*[pkg/util/mon/bytes_usage.go, line 463 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/46316#-M38Z3mYCLi91G6q7iI7:-M3Cpxqy9RktHh3tiGqP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2b384f122ae991b1a1eb064ee281d38515bb41e/pkg/util/mon/bytes_usage.go#L463)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

We should not be dragging `execerror` here, use regular `panic` instead.
</blockquote></details>

Done.

**Review by yuzefovich — COMMENTED** [review]
The code looks good to me, but I'll defer to Alfonso.

> Reviewed 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46316#-:-M3Cxxqw9FF14GjF1oX7:bl1ii79)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @Azhng)

___
*[pkg/sql/colexec/execpb/stats.go, line 87 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/46316#-M3CxHfr7bezRakD2-Ip:-M3CxHfr7bezRakD2-Iq:bbzbz0m) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac0e8b5584ffbe18cdeeca160ec5364f92022c9b/pkg/sql/colexec/execpb/stats.go#L87)):*
> ```Go
> 	}
> 
> 	if vs.MaxAllocatedMem != 0 {
> ```

Hm, I believe in row execution we do print out 0 values for memory and disk usage, and I think it'd be nice to be consistent. I'm not sure which option I prefer though (probably I would lean towards not showing zero values as the current PR does and would hide them as well in rowexec case). Thoughts?

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46316#-:-M3G48whCgIB32-epT4u:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/execpb/stats.go, line 87 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/46316#-M3CxHfr7bezRakD2-Ip:-M3G3vKQ1el5cY56atFq:b-7893ca) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac0e8b5584ffbe18cdeeca160ec5364f92022c9b/pkg/sql/colexec/execpb/stats.go#L87)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Hm, I believe in row execution we do print out 0 values for memory and disk usage, and I think it'd be nice to be consistent. I'm not sure which option I prefer though (probably I would lean towards not showing zero values as the current PR does and would hide them as well in rowexec case). Thoughts?
</blockquote></details>

I prefer doing in rowexec what the current PR does.

**Review by Azhng — COMMENTED** [review]
Added a separate commit to update the rowexec stats 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46316#-:-M3Hqrb3CfoB0CmYkhQv:b29vr0n)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto and @yuzefovich)

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46316#-:-M3LDaJwB4ce_HeLjHJ3:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

**Comment by Azhng** [comment]
Will send a followup PR to fix rowexec `DeterministicStats` 

TFTR! 

bors r+

**Pull request merged**
