### PR TITLE
Expose SpanStats method over Status API

### PR DESCRIPTION
**Pull request by mrtracy**
Expose SpanStats method, which queries a node for the sum stats of all ranges it
contains, on any store, that have keys in the supplied span.  The intention is
for this to find the total stats for a specific table on a specific node, but it
  can be used for any key range.

Commit also addresses some comment issues from PR #7921

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7948)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/serverpb/status.proto, line 128 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7948#-KN8xlS2vWam6D14sVEK:-KN8xlS2vWam6D14sVEL:1032501856) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa0e389b9a307f0093e1b4a0cedd6d038aa5e6d9/server/serverpb/status.proto#L128)):*
> ```protobuf
> }
> 
> message SpanStatsRequest {
> ```

Can you sketch out how this is going to be used to get the (replicated) stats for a table? Are you going to contact every node in the system? Are you going to use the meta2 keys to locate which nodes you need to talk to? The change itself looks fine otherwise, just wondering how this is going to fit in with high-level goal of gathering table-level stats.

An alternative would be to add a `StatsRequest` operation to `BatchRequest` in order to utilize the `DistSender` machinery to send the request to the relevant ranges. See also `roachpb.combinable` which allows `DistSender` to combine multiple responses from different ranges. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7948)*

**Comment by mrtracy** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/serverpb/status.proto, line 128 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7948#-KN8xlS2vWam6D14sVEK:-KN91WdS3Da4mOP-2Kmx:-1898339830) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa0e389b9a307f0093e1b4a0cedd6d038aa5e6d9/server/serverpb/status.proto#L128)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Can you sketch out how this is going to be used to get the (replicated) stats for a table? Are you going to contact every node in the system? Are you going to use the meta2 keys to locate which nodes you need to talk to? The change itself looks fine otherwise, just wondering how this is going to fit in with high-level goal of gathering table-level stats.
> 
> An alternative would be to add a `StatsRequest` operation to `BatchRequest` in order to utilize the `DistSender` machinery to send the request to the relevant ranges. See also `roachpb.combinable` which allows `DistSender` to combine multiple responses from different ranges. 
</details>
My current plan was to read the meta2 keys and compute a list of nodes to contact, although the StatsRequest might be a good alternative. Let me look into that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7948)*

**Comment by mrtracy** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/serverpb/status.proto, line 128 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7948#-KN8xlS2vWam6D14sVEK:-KN91yDnb0rC2LaZEtDk:1287747158) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa0e389b9a307f0093e1b4a0cedd6d038aa5e6d9/server/serverpb/status.proto#L128)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> My current plan was to read the meta2 keys and compute a list of nodes to contact, although the StatsRequest might be a good alternative. Let me look into that.
</details>
Actually, I don't think that would work, I need a response from every replica, not every range.

The StatsRequest might be a good alternative for getting unique stats, now that I think about it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7948)*

**Comment by petermattis** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/serverpb/status.proto, line 128 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7948#-KN8xlS2vWam6D14sVEK:-KN9D_qrUr1haRe3YFNY:-634428523) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa0e389b9a307f0093e1b4a0cedd6d038aa5e6d9/server/serverpb/status.proto#L128)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> Actually, I don't think that would work, I need a response from every replica, not every range.
> 
> The StatsRequest might be a good alternative for getting unique stats, now that I think about it.
</details>
Do we need replicated stats if we can get unique stats? Something to consider about the replicated stats is what happens if we can't talk to a particular node because it is temporarily down. We'll get a hiccup in the stats that would be less likely if we only have to talk to one of the replicas in a range.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7948)*

**Comment by petermattis** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/serverpb/status.proto, line 128 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7948#-KN8xlS2vWam6D14sVEK:-KN9EoplZYTV49Njl6ds:1515925560) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa0e389b9a307f0093e1b4a0cedd6d038aa5e6d9/server/serverpb/status.proto#L128)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Do we need replicated stats if we can get unique stats? Something to consider about the replicated stats is what happens if we can't talk to a particular node because it is temporarily down. We'll get a hiccup in the stats that would be less likely if we only have to talk to one of the replicas in a range.
</details>
As I think about it, we probably won't both replicated and unique stats, though certainly they don't have to land in the code base at the same time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7948)*

**Comment by mrtracy** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/serverpb/status.proto, line 128 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7948#-KN8xlS2vWam6D14sVEK:-KN9EaffeYQDaZYCZVEi:2008179054) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa0e389b9a307f0093e1b4a0cedd6d038aa5e6d9/server/serverpb/status.proto#L128)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> As I think about it, we probably won't both replicated and unique stats, though certainly they don't have to land in the code base at the same time.
</details>
I guess the biggest issue is, I don't know what questions we are looking to answer in the UI.  The Unique stats can be used to *infer* replicated stats, but only if we assume replication is working correctly; replicated stats can tell us exactly how much of a table is spread across an availability zone, or on a specific machine, etc.

The "node down" problem, I believe, lends credibility to spencer's idea of placing that information in the Node Status.

Really need to focus this down to specific use cases, or else we are apt (as I am currently apt) to second guess every decision made.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7948)*

**Comment by mrtracy** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/serverpb/status.proto, line 128 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7948#-KN8xlS2vWam6D14sVEK:-KN9KedYq6mFSchgm8Ak:-638945030) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa0e389b9a307f0093e1b4a0cedd6d038aa5e6d9/server/serverpb/status.proto#L128)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> I guess the biggest issue is, I don't know what questions we are looking to answer in the UI.  The Unique stats can be used to *infer* replicated stats, but only if we assume replication is working correctly; replicated stats can tell us exactly how much of a table is spread across an availability zone, or on a specific machine, etc.
> 
> The "node down" problem, I believe, lends credibility to spencer's idea of placing that information in the Node Status.
> 
> Really need to focus this down to specific use cases, or else we are apt (as I am currently apt) to second guess every decision made.
</details>
After becoming re-acquainted with DistSender and Batching, I think that a `StatsRequest` would simply be too expensive.  It has to send a separate request to every range of the table.  It would probably work if requests to different ranges on the same node were somehow batched, by I do not think this is the case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7948)*

**Comment by petermattis** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/serverpb/status.proto, line 128 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7948#-KN8xlS2vWam6D14sVEK:-KN9rFwmsYaRQlxjB1ma:1936018404) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa0e389b9a307f0093e1b4a0cedd6d038aa5e6d9/server/serverpb/status.proto#L128)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> After becoming re-acquainted with DistSender and Batching, I think that a `StatsRequest` would simply be too expensive.  It has to send a separate request to every range of the table.  It would probably work if requests to different ranges on the same node were somehow batched, by I do not think this is the case.
</details>
Eventually that limitation of `DistSender` needs to be fixed. I'm fine with not doing that now. Let's just put a little commentary on the `SpanStats` method down below about how it is intended to be used and what it returns. It is a shame that none of the other methods here are documented, but that is not a good reason to continue that bad habit.

UI questions we should be able to answer:
* How big is a table? How many ranges does it contain?
* How many reads / writes is a table receiving?
* How many keys / rows are in a table?
* How does a table's zone config affect data placement?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7948)*

**Comment by mrtracy** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[server/serverpb/status.proto, line 128 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7948#-KN8xlS2vWam6D14sVEK:-KNDQ7fyAncW0fHMVv0A:900003810) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa0e389b9a307f0093e1b4a0cedd6d038aa5e6d9/server/serverpb/status.proto#L128)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Eventually that limitation of `DistSender` needs to be fixed. I'm fine with not doing that now. Let's just put a little commentary on the `SpanStats` method down below about how it is intended to be used and what it returns. It is a shame that none of the other methods here are documented, but that is not a good reason to continue that bad habit.
> 
> UI questions we should be able to answer:
> * How big is a table? How many ranges does it contain?
> * How many reads / writes is a table receiving?
> * How many keys / rows are in a table?
> * How does a table's zone config affect data placement?
</details>
Updated the method with a comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7948)*

**Comment by petermattis** [comment]
Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[server/serverpb/status.proto, line 178 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7948#-KNDTXQob-7os259CFwN:-KNDTXQob-7os259CFwO:-1814605068) ([raw file](https://github.com/cockroachdb/cockroach/blob/4830c42bd56eb48bcfadf9ebe3416829d1a6b4f8/server/serverpb/status.proto#L178)):*
> ```protobuf
>   // in that span. This is designed to compute stats specific to a SQL table:
>   // it will be called with the highest/lowest key for a SQL table, and return
>   // information about the resources on a node used by that table.
> ```

This is the endpoint the UI is going to use, correct? So shouldn't it be summing across all nodes and not just the node that received the request?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7948)*

**Comment by mrtracy** [comment]
Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[server/serverpb/status.proto, line 178 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7948#-KNDTXQob-7os259CFwN:-KNE-Gi4Mnk1rhNtz-Jo:1590910683) ([raw file](https://github.com/cockroachdb/cockroach/blob/4830c42bd56eb48bcfadf9ebe3416829d1a6b4f8/server/serverpb/status.proto#L178)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> This is the endpoint the UI is going to use, correct? So shouldn't it be summing across all nodes and not just the node that received the request?
</details>
No, the endpoint is going to use another method, that will call THIS method on all of the individual nodes. I'm working on that right now, it's a bit more complicated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7948)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[server/serverpb/status.proto, line 178 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7948#-KNDTXQob-7os259CFwN:-KNE0_rKMYwmOHh2rGLJ:1314108204) ([raw file](https://github.com/cockroachdb/cockroach/blob/4830c42bd56eb48bcfadf9ebe3416829d1a6b4f8/server/serverpb/status.proto#L178)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> No, the endpoint is going to use another method, that will call THIS method on all of the individual nodes. I'm working on that right now, it's a bit more complicated.
</details>
Oh. I thought this was the method exposed to the UI because it is part of the `Status` service. Color me confused, though I guess there isn't any real harm in putting this here. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7948#-:-KNE0yBP_si9zk1_pGog:1417088721)*

**Comment by mrtracy** [comment]
Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[server/serverpb/status.proto, line 178 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7948#-KNDTXQob-7os259CFwN:-KNE1orIv2eLQy6e1MaD:-1806314079) ([raw file](https://github.com/cockroachdb/cockroach/blob/4830c42bd56eb48bcfadf9ebe3416829d1a6b4f8/server/serverpb/status.proto#L178)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Oh. I thought this was the method exposed to the UI because it is part of the `Status` service. Color me confused, though I guess there isn't any real harm in putting this here. 
</details>
I've already added a TODO (in my next PR) to sort out the differences between status and admin.  Two services are not necessary at all, there's no clear dividing line (the UI already calls methods on both).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7948)*

**Pull request merged**
