### PR TITLE
syncutil: special case one error in WaitGroupWithError

### PR DESCRIPTION
**Pull request by danhhz**
This improves readability in chains of error.Wrap.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14144)

### CODE REVIEW

**Comment by andreimatei** [comment]
mmm I'm not sure I like this change. Why should we treat the "one of the waitgroup tasks returned an error" differently from "many of the waitgroup tasks returned an error"? Granted, in one case information is not lost and in the other it is (since everything but the first err is lost), but how could a client take advantage of this difference? Clients should always be prepared for more than one error to have happened, right?

Maybe tell me more concretely the motivation. 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14144#-:-KfIGjmS4Yo6Ma5sU13L:balbs1d)*

**Comment by danhhz** [comment]
"in one case information is not lost and in the other it is" is exactly why I think they should be treated differently. Concretely, I did this because ```pq: exporting 3 ranges: first of 1 errors: storage: service returned error: ...``` is made harder to read by this extraneous information

**Comment by andreimatei** [comment]
I don't have a problem with that error message.
If you do, what do you think of still wrapping the error into a custom error type, so that at least clients can't depend directly on the type of the error (even if they can depend on the text) and force them to inspect `.Cause`.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14144#-:-KfIr5fZ_jgKBap5QWdJ:b-3x0bsa)*

**Comment by danhhz** [comment]
> If you do, what do you think of still wrapping the error into a custom error type, so that at least clients can't depend directly on the type of the error (even if they can depend on the text) and force them to inspect .Cause.

Why? I don't see what that gets us

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14144#-:-KfIs6lxd0aFLNbpmEW1:bs8ub4e)*

**Comment by andreimatei** [comment]
A client handling an error correctly when only one wg task failed, but failing to handle the same error correctly when more than one task failed. If more than one task failed, the client is missing information so it may not want to handle the error in exactly the same way, but it may also want to - e.g. invalidate some caches on a `RangeMismatch` error.
If we always wrap, we force the error handling code to make handling decisions more explicitly.

If we do this, then we might as well also switch to accumulating all errors - since we won't be using the `errors` library any more.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14144#-:-KfIsSgnqMC4gTEhauCq:bvmzas7)*

**Comment by danhhz** [comment]
@tamird happened upon golang.org/x/sync/errgroup, which I like better than WaitGroupWithError anyway. I'll definitely be switching the ccl stuff to it, so closing this

**Pull request closed without merging**
