### PR TITLE
Fork snappy-go.

### PR DESCRIPTION
**Pull request by petermattis**
Use C++ snappy instead of Go snappy for encoding/decoding.

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM. For performance reasons?

**Comment by petermattis** [comment]
Primarily to get rid of our last code.google.com dependency. But the performance increase is nice too.

**Comment by petermattis** [comment]
FYI, I move the snappy-go fork into `github.com/cockroachdb/c-snappy`. This dramatically simplifies this change and fixes the test failure (the snappy tests did not have the glog flags).

**Comment by tamird** [comment]
:star2:

**Pull request merged**
