### PR TITLE
storage: add `TestMVCCHistories` metamorphic param for TBIs

### PR DESCRIPTION
**Pull request by erikgrinaker**
This patch adds the metamorphic test parameter
`mvcc-histories-separate-engine-blocks`, which will configure Pebble
with very small blocks and trigger a flush after every command. This
may uncover bugs in TBI optimizations.

Release justification: non-production code changes

Release note: None

### CODE REVIEW

**Comment by erikgrinaker** [comment]
@jbowens In addition to the issue in https://github.com/cockroachdb/pebble/issues/1895, this also occasionally fails with a goroutine leak, after about 6 seconds. Am I holding this wrong somehow?

**Review by tbg — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86256)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens)

**Review by jbowens — APPROVED** [review]
:lgtm:

Filed cockroachdb/pebble#1898 for the goroutine exit race at Close.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86256#-:-N9h6WLt90ZHPeOjWT1j:b-zfdy8u)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @erikgrinaker)

**Comment by erikgrinaker** [comment]
@jbowens Any chance we can get that race fixed? I'd really like to merge this (and get some similar metamorphic params in) for better TBI test coverage.

**Comment by erikgrinaker** [comment]
@jbowens Afraid I'm still seeing goroutine leaks after the Pebble bump, even when I give it 30 seconds to clean up. This only happens when I call `Flush()` after every write.

```
    mvcc_history_test.go:644: Leaked goroutine: goroutine 5517 [chan receive]:
        github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop.func1({0x1e87760, 0xc000640120})
        	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go:324 +0x9f
        runtime/pprof.Do({0x1e876f0?, 0xc0001b2000?}, {{0xc00004eca0?, 0x5e4a60?, 0xe4c9c0?}}, 0xc0004d47a8)
        	GOROOT/src/runtime/pprof/runtime.go:40 +0xa3
        github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop(0xc0004d4798?)
        	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go:322 +0x58
        created by github.com/cockroachdb/pebble.(*tableCacheShard).init
        	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go:314 +0xe5
        Leaked goroutine: goroutine 5521 [chan receive]:
        github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop.func1({0x1e87760, 0xc0006402a0})
        	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go:324 +0x9f
        runtime/pprof.Do({0x1e876f0?, 0xc0001b2000?}, {{0xc00004eca0?, 0x0?, 0xe4c9c0?}}, 0xc000652fa8)
        	GOROOT/src/runtime/pprof/runtime.go:40 +0xa3
        github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop(0xc000652f98?)
        	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go:322 +0x58
        created by github.com/cockroachdb/pebble.(*tableCacheShard).init
        	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go:314 +0xe5
        Leaked goroutine: goroutine 5537 [chan receive]:
        github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop.func1({0x1e87760, 0xc00036c540})
        	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go:324 +0x9f
        runtime/pprof.Do({0x1e876f0?, 0xc0001b2000?}, {{0xc00004eca0?, 0x1e876f0?, 0xe4c9c0?}}, 0xc00049efa8)
        	GOROOT/src/runtime/pprof/runtime.go:40 +0xa3
        github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop(0xc00049ef98?)
        	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go:322 +0x58
        created by github.com/cockroachdb/pebble.(*tableCacheShard).init
        	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go:314 +0xe5
```

**Comment by erikgrinaker** [comment]
CI failed with some weird `npm-run-all: command not found` error, assuming it's dependency flake or some such.

bors r=tbg,jbowens

**Pull request merged**
