### PR TITLE
server, ccl: adjust more tests to work with test tenant

### PR DESCRIPTION
**Pull request by yuzefovich**
Informs: #76378.
Epic: CRDB-18499.

### CODE REVIEW

**Review by knz — APPROVED** [review]
LGTM with a request for clarification.

> Reviewed 3 of 3 files at r1, 9 of 9 files at r2, 22 of 22 files at r3, 13 of 13 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107470#-:-NaBi8oo6rQQJUxju0_a:bvb47l0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @stevendanna and @yuzefovich)

___
*[`-- commits` line 32 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/107470#-NaBhhS3AXFsjMRxJCM9):*
nit: you can mention that the long-term fix will be to move the tests to at `_test` package.
___
*[`pkg/sql/sqlstats/test_utils.go` line 68 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107470#-NaBg8rYBqMa5XgNQoGU:-NaBg8rYBqMa5XgNQoGV:b-si3jq2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b98e082c0b1b0ea25e69b69deab1a87a1ccfd127/pkg/sql/sqlstats/test_utils.go#L68)):*
> ```Go
> // Note: SQL Stats’s read path uses follower read
> //
> //	(AS OF SYSTEM TIME follower_read_timestamp()) to ensure that contention
> ```

nit: something is off with the comment formatting.
___
*[`pkg/server/server_test.go` line 778 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107470#-NaBgctP9anSGTWBMuOY:-NaBgctP9anSGTWBMuOZ:b-ohild3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b98e082c0b1b0ea25e69b69deab1a87a1ccfd127/pkg/server/server_test.go#L778)):*
> ```Go
> 
> 			respString := string(respBytes)
> 			// Since server test package links ccl, build.GetInfo() says that we
> ```

I'm confused - why is this true? 

This particular file (server_test.go) has `package server` at the top. It's not `server_test`. How come this logic is necessary?

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107470#-:-NaDYtTYAZc3WegWBn8t:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @stevendanna)

___
*[`pkg/server/server_test.go` line 778 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107470#-NaBgctP9anSGTWBMuOY:-NaDYPggD0mJ1_O63Uek:bs2zn0n) ([raw file](https://github.com/cockroachdb/cockroach/blob/b98e082c0b1b0ea25e69b69deab1a87a1ccfd127/pkg/server/server_test.go#L778)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I'm confused - why is this true? 

This particular file (server_test.go) has `package server` at the top. It's not `server_test`. How come this logic is necessary?
</blockquote></details>

Discussed this offline.

**Comment by renatolabs** [comment]
Any chance this could be making `TestZoneConfigAppliesToTemporaryIndex` flaky? It failed on the bors run above.

**Comment by yuzefovich** [comment]
Yes, this PR is the culprit, thanks.

bors r-

**Pull request merged**
