### PR TITLE
sqlliveness: reduce log spam about 0 expired sessions

### PR DESCRIPTION
**Pull request by dt**
Release note: none.

### CODE REVIEW

**Review by spaskob — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52692#-:-MEYRbOQDNILxAbxNp9J:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @spaskob)

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52692#-:-MEYjb2s7JnjXUu8x0Lm:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52692)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/sql/sqlliveness/slstorage/slstorage.go, line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52692#-MEZ4oyDEBG7Ot4uQDld:-MEZ4oyDEBG7Ot4uQDle:b-bor2yh) ([raw file](https://github.com/cockroachdb/cockroach/blob/c31cc9ddb6cfd5b89647c762665b0ce67d4b9108/pkg/sql/sqlliveness/slstorage/slstorage.go#L252)):*
> ```Go
> 	s.metrics.SessionDeletionsRuns.Inc(1)
> 	s.metrics.SessionsDeleted.Inc(n)
> 	if log.V(2) || n > 0 {
> ```

fwiw we also have `log.ExpensiveLogEnabled(ctx,level)` which is usually better cause it also looks at whether the operation is traced

**Pull request merged**
