### PR TITLE
sql: add distsql and vectorize settings to bundles

### PR DESCRIPTION
**Pull request by RaduBerinde**
Release justification: Low risk, high benefit changes to existing
functionality.

Release note: None

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
Nice! :lgtm:

But I also was thinking why wouldn't we include a separate file into a bundle that shows all cluster setting values? That could provide even more value but might be not backportable.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61134#-:-MUPvF_u4NbPcDOHjew_:brgi6lm)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner, @RaduBerinde, and @rytaft)

___
*[pkg/sql/explain_bundle.go, line 590 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61134#-MUPut_ICmW_xv3RBiY4:-MUPut_ICmW_xv3RBiY5:b-edritd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5758af8e8159825f82bf55da328fc07b1fca80d/pkg/sql/explain_bundle.go#L590)):*
> ```Go
> 		}
> 		// Get the default value for the cluster setting.
> 		//def := s.clusterSetting.EncodedDefault()
> ```

nit: this line seems like a leftover. The comment probably should be adjusted slightly.

**Review by RaduBerinde — COMMENTED** [review]
Good idea, I printed the cluster settings too.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61134#-:-MUQFWcI693AazTMBDw9:bq1gqb2)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @rytaft, and @yuzefovich)

**Review by yuzefovich — COMMENTED** [review]
Thanks!

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61134#-:-MUQO95S8bhwu5hHYY60:b-ucfknh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @RaduBerinde, and @rytaft)

___
*[pkg/sql/explain_bundle.go, line 358 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61134#-MUQMk8M1e-85aWvgfWC:-MUQMk8M1e-85aWvgfWD:bbpbr8e) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e362243d78543188c1b87be8d227f07949dae2a/pkg/sql/explain_bundle.go#L358)):*
> ```Go
> 	fmt.Fprintf(&buf, "\n")
> 
> 	// Show the values of any non-default session variables that can impact
> ```

super nit: I think we print all relevant session variables and not only "non-default". Or maybe the comment should be that the session variables with default values will be SQL-commented out.
___
*[pkg/sql/explain_bundle.go, line 613 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61134#-MUQNk5vCeQXGBzUKM7c:-MUQNk5vCeQXGBzUKM7d:b8gxws1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e362243d78543188c1b87be8d227f07949dae2a/pkg/sql/explain_bundle.go#L613)):*
> ```Go
> }
> 
> func (c *stmtEnvCollector) PrintClusterSettings(w io.Writer) error {
> ```

Is there some unit test for what's included in the bundle? I'd expect that something needs to be updated.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61134)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @rytaft, and @yuzefovich)

___
*[pkg/sql/explain_bundle.go, line 358 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61134#-MUQMk8M1e-85aWvgfWC:-MUQT_Fm9trknZpogMyF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e362243d78543188c1b87be8d227f07949dae2a/pkg/sql/explain_bundle.go#L358)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

super nit: I think we print all relevant session variables and not only "non-default". Or maybe the comment should be that the session variables with default values will be SQL-commented out.
</blockquote></details>

Done.
___
*[pkg/sql/explain_bundle.go, line 613 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61134#-MUQNk5vCeQXGBzUKM7c:-MUQTDgI3kKbltGVKlnY:bifbzcl) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e362243d78543188c1b87be8d227f07949dae2a/pkg/sql/explain_bundle.go#L613)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Is there some unit test for what's included in the bundle? I'd expect that something needs to be updated.
</blockquote></details>

Unfortunately we don't have tests for the contents of the files (there are some tests that verify the list of files). I tested this manually.

**Review by yuzefovich — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61134#-:-MUQUPCfCsJCTQs1evPs:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61134)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/explain_bundle.go, line 587 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61134#-MUQYHii4gv4rI57M-V5:-MUQYHii4gv4rI57M-V6:bar470p) ([raw file](https://github.com/cockroachdb/cockroach/blob/987cb694d4ba7c294defc01be4b5faef5f1f68ad/pkg/sql/explain_bundle.go#L587)):*
> ```Go
> 		{sessionSetting: "optimizer_use_multicol_stats", clusterSetting: optUseMultiColStatsClusterMode, convFunc: boolToOnOff},
> 		{sessionSetting: "distsql", clusterSetting: DistSQLClusterExecMode, convFunc: distsqlConv},
> 		{sessionSetting: "vectorize", clusterSetting: VectorizeClusterMode, convFunc: vectorizeConv},
> ```

While you're making changes here, can you add the new setting for locality optimized search (`locality_optimized_partitioned_index_scan`)? Sorry I forgot to add it earlier...

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61134)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @rytaft, and @yuzefovich)

___
*[pkg/sql/explain_bundle.go, line 587 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61134#-MUQYHii4gv4rI57M-V5:-MURME3U7MTEznwl_YZE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/987cb694d4ba7c294defc01be4b5faef5f1f68ad/pkg/sql/explain_bundle.go#L587)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

While you're making changes here, can you add the new setting for locality optimized search (`locality_optimized_partitioned_index_scan`)? Sorry I forgot to add it earlier...
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 2 files at r2, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61134#-:-MUUpEsZ5QrjCxsh4JkA:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[pkg/sql/explain_bundle.go, line 587 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61134#-MUQYHii4gv4rI57M-V5:-MUUoOAN3YxMRRe9ipVB:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/987cb694d4ba7c294defc01be4b5faef5f1f68ad/pkg/sql/explain_bundle.go#L587)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks!

**Review by RaduBerinde — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61134#-:-MUUu8ec-m2NXV2in-Pf:b-tlx7ko)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

**Comment by lucy-zhang** [comment]
I think this has a semantic merge conflict with the internal executor changes:

```
[20:39:19][run] # github.com/cockroachdb/cockroach/pkg/sql [github.com/cockroachdb/cockroach/pkg/util/log/logcrash.test]
[20:39:19][run] pkg/sql/explain_bundle.go:614:19: c.ie.QueryEx undefined (type *InternalExecutor has no field or method QueryEx)
```

bors r-

**Comment by RaduBerinde** [comment]
Thanks @lucy-zhang!

**Pull request merged**
