### PR TITLE
acceptance: kill stale docker containers.

### LINKED ISSUE #7097: acceptance: tests should try to kill leftover containers from failed previous invocations.
I ran `make acceptance` against sha `093e1e3` and encountered the following panic:

```
+ go test -tags acceptance ./acceptance -run . -timeout 10m -v -nodes 3
I160608 09:58:36.104754 rand.go:76  Random seed: -7777799812709100292
=== RUN   TestAdminLossOfQuorum
I160608 09:58:36.156787 acceptance/cluster/localcluster.go:658  stopping
--- FAIL: TestAdminLossOfQuorum (0.05s)
panic: Error response from daemon: network cockroachdb_acceptance has active endpoints [recovered]
        panic: Error response from daemon: network cockroachdb_acceptance has active endpoints [recovered]
        panic: Error response from daemon: network cockroachdb_acceptance has active endpoints

goroutine 9 [running]:
panic(0x5217c20, 0xc8202e8030)
        /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
testing.tRunner.func1(0xc820084510)
        /usr/local/Cellar/go/1.6.2/libexec/src/testing/testing.go:467 +0x192
panic(0x5217c20, 0xc8202e8030)
        /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:443 +0x4e9
github.com/cockroachdb/cockroach/acceptance/cluster.(*LocalCluster).stopOnPanic(0xc82012e1c0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/acceptance/cluster/localcluster.go:238 +0x9b
panic(0x5217c20, 0xc8202e8030)
        /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:443 +0x4e9
github.com/cockroachdb/cockroach/acceptance/cluster.maybePanic(0xb740028, 0xc8202e8030)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/acceptance/cluster/docker.go:166 +0x4b
github.com/cockroachdb/cockroach/acceptance/cluster.(*LocalCluster).createNetwork(0xc82012e1c0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/acceptance/cluster/localcluster.go:268 +0x2ef
github.com/cockroachdb/cockroach/acceptance/cluster.(*LocalCluster).Start(0xc82012e1c0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/acceptance/cluster/localcluster.go:588 +0xc2
github.com/cockroachdb/cockroach/acceptance.StartCluster(0xc820084510, 0xc82017ab60, 0x9, 0xc82017c4e0, 0x1, 0x1, 0x12a05f200, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/acceptance/util_test.go:184 +0x3d1
github.com/cockroachdb/cockroach/acceptance.runTestOnConfigs.func1(0xc820084510, 0xc82013bec8, 0x580b240)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/acceptance/util_test.go:157 +0x34
github.com/cockroachdb/cockroach/acceptance.runTestOnConfigs(0xc820084510, 0x580b240)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/acceptance/util_test.go:160 +0x247
github.com/cockroachdb/cockroach/acceptance.TestAdminLossOfQuorum(0xc820084510)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/acceptance/admin_test.go:34 +0x2d
testing.tRunner(0xc820084510, 0x6056d80)
        /usr/local/Cellar/go/1.6.2/libexec/src/testing/testing.go:473 +0x98
created by testing.RunTests
        /usr/local/Cellar/go/1.6.2/libexec/src/testing/testing.go:582 +0x892
exit status 2
FAIL    github.com/cockroachdb/cockroach/acceptance     0.100s
```

### PR DESCRIPTION
**Pull request by jordanlewis**
If an acceptance test fails, docker containers for that test can be left
in an orphaned, still-running state. Previously, the next run of the
acceptance tests would then fail when trying to destroy the acceptance
test docker network because the network still contained running
containers.

This commit ensures that any running docker instances inside of the
docker network for the acceptance test will be terminated before
attempting to destroy the network.

Resolves #7097.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7114)

### CODE REVIEW

**Comment by tschottdorf** [comment]
:lgtm:

<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary>
> #### acceptance: kill stale docker containers\.
> 
> If an acceptance test fails, docker containers for that test can be left
> 
> in an orphaned, still-running state. Previously, the next run of the
> 
> acceptance tests would then fail when trying to destroy the acceptance
> 
> test docker network because the network still contained running
> 
> containers.
> 
> 
> 
> This commit ensures that any running docker instances inside of the
> 
> docker network for the acceptance test will be terminated before
> 
> attempting to destroy the network.
> 
> 
> 
> Resolves #7097.
> 
> 
> 
</details>


---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[acceptance/cluster/localcluster.go, line 266 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7114#-KJlcRV1QKTEGqJ9i-8v:-KJlcRV1QKTEGqJ9i-8w:-1282150047) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ccd44cc82bc915e1ec269b77787a8e20eba617/acceptance/cluster/localcluster.go#L266)):*
> ```Go
> 	net, err := l.client.NetworkInspect(context.Background(), networkName)
> 	if err == nil {
> 		// we need to destroy the network and any running containers inside of it.
> ```

s/we/We/

---

*[acceptance/cluster/localcluster.go, line 268 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7114#-KJlcaYpeiCOyh5t9R7A:-KJlcaYpeiCOyh5t9R7B:-77770301) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ccd44cc82bc915e1ec269b77787a8e20eba617/acceptance/cluster/localcluster.go#L268)):*
> ```Go
> 		// we need to destroy the network and any running containers inside of it.
> 		for containerID := range net.Containers {
> 			maybePanic(l.client.ContainerKill(context.Background(), containerID, "9"))
> ```

The container could have terminated when you call this. Might be better to ignore the error here (but things can go awkward either way, so I'm fine as is).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7114#-:-KJlciXeKV2uZfc3e6_E:1417088721)*

**Comment by tschottdorf** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7114)*

**Comment by tschottdorf** [comment]
The test failure is unrelated. I retriggered the tests for you.

**Comment by jordanlewis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[acceptance/cluster/localcluster.go, line 266 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7114#-KJlcRV1QKTEGqJ9i-8v:-KJlfuNiMpJPH8TMyjHd:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ccd44cc82bc915e1ec269b77787a8e20eba617/acceptance/cluster/localcluster.go#L266)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> s/we/We/
</details>
Done.

---

*[acceptance/cluster/localcluster.go, line 268 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7114#-KJlcaYpeiCOyh5t9R7A:-KJlg-voLGu4hSf3YBhL:636957258) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8ccd44cc82bc915e1ec269b77787a8e20eba617/acceptance/cluster/localcluster.go#L268)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> The container could have terminated when you call this. Might be better to ignore the error here (but things can go awkward either way, so I'm fine as is).
</details>
I wrote a comment to address this. I don't think it will be too problematic so I left the code as-is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7114)*

**Comment by tschottdorf** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7114)*

**Pull request merged**
