### PR TITLE
quantize: add rabitq quantization

### PR DESCRIPTION
**Pull request by andy-kimball**
This commit implements RaBitQ quantization according to the algorithm described in this paper:

    "RaBitQ: Quantizing High-Dimensional Vectors with a Theoretical Error Bound
    for Approximate Nearest Neighbor Search" by Jianyang Gao & Cheng Long.

The RaBitQ quantization method provides good accuracy, produces compact codes, provides practical error bounds, is easy to implement, and can be accelerated with fast SIMD instructions. RaBitQ quantization codes use only 1 bit per dimension in the original vector.

Epic: CRDB-42943

Release note: None

### CODE REVIEW

**Review by mw5h — CHANGES_REQUESTED** [review]
Looks good. Just a few nits. 

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134370#-:-OB1fGMC7lV2vViaZ1ED:b-2mlyah)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @DrewKimball)

___
*[`pkg/sql/vecindex/quantize/rabitq.go` line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134370#-OB15ICk-H62ngUsLgeo:-OB15ICk-H62ngUsLgep:bggc0jw) ([raw file](https://github.com/cockroachdb/cockroach/blob/21d0b79a7cb1fc5912b3b6d804146a0f72c840f7/pkg/sql/vecindex/quantize/rabitq.go#L25)):*
> ```Go
> //	"RaBitQ: Quantizing High-Dimensional Vectors with a Theoretical Error Bound
> //	for Approximate Nearest Neighbor Search" by Jianyang Gao & Cheng Long.
> //	URL: https://arxiv.org/pdf/2405.12497
> ```

Add this URL to the commit message. Maybe consider committing the paper? We don't know what the future availability of it will be.
___
*[`pkg/sql/vecindex/quantize/rabitq.go` line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134370#-OB1YCTE8sM8ytaqp05S:-OB1YCTE8sM8ytaqp05T:bhv7d64) ([raw file](https://github.com/cockroachdb/cockroach/blob/21d0b79a7cb1fc5912b3b6d804146a0f72c840f7/pkg/sql/vecindex/quantize/rabitq.go#L36)):*
> ```Go
> // vector index. This is important, because the ROT matrix is expensive to
> // generate and can use quite a bit of memory.
> type raBitQuantizer struct {
> ```

I find that comments describing non-obvious struct fields to be very high value. I normally don't like code with a lot of inline comments, but I'm never sad about well documented structs.
___
*[`pkg/sql/vecindex/quantize/rabitq.go` line 384 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134370#-OB1e3om9W0QUKPjYncU:-OB1e3om9W0QUKPjYncV:b-lxbaen) ([raw file](https://github.com/cockroachdb/cockroach/blob/21d0b79a7cb1fc5912b3b6d804146a0f72c840f7/pkg/sql/vecindex/quantize/rabitq.go#L384)):*
> ```Go
> 			codeBits |= getSignBit(elements[7])
> 
> 			dim += 8
> ```

Why is this not part of the for loop decl?
___
*[`pkg/sql/vecindex/quantize/rabitqpb.go` line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134370#-OB17I8N6X2eFIbp7hi-:-OB17I8N6X2eFIbp7hi0:b5raxnp) ([raw file](https://github.com/cockroachdb/cockroach/blob/21d0b79a7cb1fc5912b3b6d804146a0f72c840f7/pkg/sql/vecindex/quantize/rabitqpb.go#L67)):*
> ```Go
> // set to defined values before use.
> func (cs *RaBitQCodeSet) AddUndefined(count int) {
> 	cs.Data = slices.Grow(cs.Data, count*cs.Width)
> ```

Maybe I'm overthinking things, but these Grow()/append() operations seem like they could be expensive. Did you consider a either a list or a dictionary of fixed-size pages?
___
*[`pkg/sql/vecindex/quantize/rabitq_test.go` line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134370#-OB1Vb9k34n0vQfiFfDh:-OB1Vb9k34n0vQfiFfDi:b-ldahhn) ([raw file](https://github.com/cockroachdb/cockroach/blob/21d0b79a7cb1fc5912b3b6d804146a0f72c840f7/pkg/sql/vecindex/quantize/rabitq_test.go#L83)):*
> ```Go
> 
> // Edge cases.
> func TestRaBitQuantizerEdge(t *testing.T) {
> ```

Is there any value in testing large vectors (2k-ish elements)? 
___
*[`pkg/sql/vecindex/quantize/rabitq_test.go` line 274 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134370#-OB1WjQT5x7qLRIPEnlv:-OB1WjQT5x7qLRIPEnlw:b-cdq1ed) ([raw file](https://github.com/cockroachdb/cockroach/blob/21d0b79a7cb1fc5912b3b6d804146a0f72c840f7/pkg/sql/vecindex/quantize/rabitq_test.go#L274)):*
> ```Go
> 
> func loadFeatures(t testing.TB) vector.Set {
> 	f, err := os.Open("../features_10000.gob")
> ```

Since features is an opaque binary, maybe include some information about what this is?

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134370)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mw5h)

___
*[`pkg/sql/vecindex/quantize/rabitq.go` line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134370#-OB15ICk-H62ngUsLgeo:-OB2L6-SDSmQPTPl6zOI:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/21d0b79a7cb1fc5912b3b6d804146a0f72c840f7/pkg/sql/vecindex/quantize/rabitq.go#L25)):*
<details><summary><i>Previously, mw5h (Matt White) wrote…</i></summary><blockquote>

Add this URL to the commit message. Maybe consider committing the paper? We don't know what the future availability of it will be.
</blockquote></details>

Done
___
*[`pkg/sql/vecindex/quantize/rabitq.go` line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134370#-OB1YCTE8sM8ytaqp05S:-OB2SLxW5iLeJWFyMfir:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/21d0b79a7cb1fc5912b3b6d804146a0f72c840f7/pkg/sql/vecindex/quantize/rabitq.go#L36)):*
<details><summary><i>Previously, mw5h (Matt White) wrote…</i></summary><blockquote>

I find that comments describing non-obvious struct fields to be very high value. I normally don't like code with a lot of inline comments, but I'm never sad about well documented structs.
</blockquote></details>

Done.
___
*[`pkg/sql/vecindex/quantize/rabitq.go` line 384 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134370#-OB1e3om9W0QUKPjYncU:-OB2SRXB-WonCXi82ctf:b-jh4x9d) ([raw file](https://github.com/cockroachdb/cockroach/blob/21d0b79a7cb1fc5912b3b6d804146a0f72c840f7/pkg/sql/vecindex/quantize/rabitq.go#L384)):*
<details><summary><i>Previously, mw5h (Matt White) wrote…</i></summary><blockquote>

Why is this not part of the for loop decl?
</blockquote></details>

Just to avoid adding 8 twice. I went ahead and changed it, though.
___
*[`pkg/sql/vecindex/quantize/rabitqpb.go` line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134370#-OB17I8N6X2eFIbp7hi-:-OB2Svfo71UR77J-JV9F:bwtf7vl) ([raw file](https://github.com/cockroachdb/cockroach/blob/21d0b79a7cb1fc5912b3b6d804146a0f72c840f7/pkg/sql/vecindex/quantize/rabitqpb.go#L67)):*
<details><summary><i>Previously, mw5h (Matt White) wrote…</i></summary><blockquote>

Maybe I'm overthinking things, but these Grow()/append() operations seem like they could be expensive. Did you consider a either a list or a dictionary of fixed-size pages?
</blockquote></details>

I think slices are the simplest and clearest. However, if perf testing shows that some other data structure out-performs slices, we could switch to them. I didn't see any evidence of this being a perf bottleneck on profiles, though.
___
*[`pkg/sql/vecindex/quantize/rabitq_test.go` line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134370#-OB1Vb9k34n0vQfiFfDh:-OB2THmN2SIrkFua56nA:b2aha95) ([raw file](https://github.com/cockroachdb/cockroach/blob/21d0b79a7cb1fc5912b3b6d804146a0f72c840f7/pkg/sql/vecindex/quantize/rabitq_test.go#L83)):*
<details><summary><i>Previously, mw5h (Matt White) wrote…</i></summary><blockquote>

Is there any value in testing large vectors (2k-ish elements)?
</blockquote></details>

I do test 512 byte vectors below. Given how the algorithm works, I don't think there's much additional value to testing even more than that in unit tests. As we do more perf testing, though, we will want to test higher-dimensionality vectors.
___
*[`pkg/sql/vecindex/quantize/rabitq_test.go` line 274 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134370#-OB1WjQT5x7qLRIPEnlv:-OB2U7249YstQ-p-HZZm:b-z395xe) ([raw file](https://github.com/cockroachdb/cockroach/blob/21d0b79a7cb1fc5912b3b6d804146a0f72c840f7/pkg/sql/vecindex/quantize/rabitq_test.go#L274)):*
<details><summary><i>Previously, mw5h (Matt White) wrote…</i></summary><blockquote>

Since features is an opaque binary, maybe include some information about what this is?
</blockquote></details>

I added a descriptive comment.

**Review by mw5h — APPROVED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134370)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball)

**Review by mw5h — APPROVED** [review]
:lgtm: Thanks!

> Reviewed 1 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134370#-:-OB7-Bwc1JQ5sWipOTA2:b-g2a5fb)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

**Comment by andy-kimball** [comment]
bors r=mw5h

**Pull request merged**
