### PR TITLE
roachtest: randomly run with runtime assertions by default

### LINKED ISSUE #86678: enable running non-perf roachtests with runtime assertions (crdb_test build tag)
Recent PR [1] added the ability to run roachtests with runtime assertions enabled. TC will now produce `cockroach-short-ea`. This binary can be staged (instead of `cockroach`) with the default probability of .5 by invoking `maybeUseBuildWithEnabledAssertions`.

Let's try to enable this for all non-perf roachtests and conditionally opt out those if the assertions result in longer timeouts.

[1] https://github.com/cockroachdb/cockroach/pull/86625

Jira issue: CRDB-18869

### PR DESCRIPTION
**Pull request by renatolabs**
This changes the semantics of `t.Cockroach()` to use a binary with
runtime assertions enabled by default. Performance tests (i.e., tests
that export to roachperf) will be able to continue using the standard
binary, without runtime assertions, as usual.

This commit also opts-out other tests that cannot easily be run with
runtime assertions enabled, most often due to timeouts.

Resolves #86678.
Informs #94986.

Epic: none

Release note: None

### CODE REVIEW

**Comment by renatolabs** [comment]
I think it's unlikely we will actually be able to do this, but I want to run a nightly build on this branch to see what happens.

**Review by srosenberg — COMMENTED** [review]
> Reviewed 1 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98351)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @renatolabs)

___
*[`pkg/cmd/roachtest/test/test_interface.go` line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98351#-NQ8eAxJ5SI8KGeE8USj:-NQ8eAxJ5SI8KGeE8USk:b-c4wimc) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef1e9be389277ee130b3d2a42d436c4902424f00/pkg/cmd/roachtest/test/test_interface.go#L26)):*
> ```Go
> )
> 
> // BinaryChoice allows the selection of two possible options; the
> ```

"To be or not to be" is the binary choice :) This is just the standard Bernoulli distribution. Maybe we should just use `distuv` [1]; it has other goodies for future needs?

[1] https://pkg.go.dev/gonum.org/v1/gonum/stat/distuv#Bernoulli

**Review by renatolabs — COMMENTED** [review]
This is ready for real review now. Failures in a full nightly build on this branch (forcing `assertionsEnabledProbability` to `1`) are the same as those we get on master [1].

[1] <https://teamcity.cockroachdb.com/viewLog.html?buildId=9066055&tab=queuedBuildOverviewTab>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98351#-:-NQaRD9k5sPR_IgP0SCo:b-vqh27n)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @srosenberg)

___
*[`pkg/cmd/roachtest/test/test_interface.go` line 26 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98351#-NQ8eAxJ5SI8KGeE8USj:-NQaJwY88swzlsWkbQnQ:b-v0fs9a) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef1e9be389277ee130b3d2a42d436c4902424f00/pkg/cmd/roachtest/test/test_interface.go#L26)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

"To be or not to be" is the binary choice :) This is just the standard Bernoulli distribution. Maybe we should just use `distuv` [1]; it has other goodies for future needs?

[1] https://pkg.go.dev/gonum.org/v1/gonum/stat/distuv#Bernoulli
</blockquote></details>

I ended up changing my mind on this API; it's more complex than necessary and I think what we have now is simpler. `t.Cockroach` will return a random binary (based on the global `rand`) and if individual tests want to have finer control over that (by using their own RNG), they can do it in the test itself; and if that becomes a pattern, it can become a test helper function instead of something linked to the `test.Test` interface.

**Review by srosenberg — APPROVED** [review]
:lgtm:

Excited to see what we'll find by randomly enabling assertions!

> Reviewed 12 of 23 files at r1, 8 of 13 files at r3, 3 of 5 files at r4, 1 of 1 files at r5, 5 of 5 files at r6, 6 of 8 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98351#-:-NR3MGyo2KkPjzxy3z6C:bipgfjq)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan and @renatolabs)

___
*[`pkg/cmd/roachtest/main.go` line 77 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/98351#-NR3IAyS5bv_w_l4V081:-NR3IAyS5bv_w_l4V082:bv5vrc6) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc055478cc17c8756b457a31d35285ea25a3f250/pkg/cmd/roachtest/main.go#L77)):*
> ```Go
> 
> func main() {
> 	globalSeed := timeutil.Now().UnixNano()
> ```

Not a super-random seed. Roachtest nightlies are co-occurring. Why not just use a stronger seed? E.g., `randutil.NewPseudoSeed`?
___
*[`pkg/cmd/roachtest/test_impl.go` line 153 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/98351#-NR3MqlJ-IdzF53McO0J:-NR3MqlJ-IdzF53McO0K:bcv4aj7) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc055478cc17c8756b457a31d35285ea25a3f250/pkg/cmd/roachtest/test_impl.go#L153)):*
> ```Go
> 			// call.
> 			if path := t.RuntimeAssertionsCockroach(); path != "" {
> 				t.randomizedCockroach = path
> ```

Do we have rough some stats on how many tests would use it out of a nightly run?
___
*[`pkg/cmd/roachtest/test_impl.go` line 156 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/98351#-NR3Kf8SCmgGHrc2rDcb:-NR3Kf8SCmgGHrc2rDcc:b-sp1u2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc055478cc17c8756b457a31d35285ea25a3f250/pkg/cmd/roachtest/test_impl.go#L156)):*
> ```Go
> 				return
> 			} else {
> 				t.l.Printf("WARNING: running without runtime assertions since the corresponding binary was not passed")
> ```

Nit: passed -> specified

**Review by renatolabs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98351)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @herkolategan and @srosenberg)

___
*[`pkg/cmd/roachtest/main.go` line 77 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/98351#-NR3IAyS5bv_w_l4V081:-NR8cNHh9gpQ-i1y_H7m:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc055478cc17c8756b457a31d35285ea25a3f250/pkg/cmd/roachtest/main.go#L77)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Not a super-random seed. Roachtest nightlies are co-occurring. Why not just use a stronger seed? E.g., `randutil.NewPseudoSeed`?
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/test_impl.go` line 153 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/98351#-NR3MqlJ-IdzF53McO0J:-NR8cTvNBoQVSdx-Pll1:b-pso7ll) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc055478cc17c8756b457a31d35285ea25a3f250/pkg/cmd/roachtest/test_impl.go#L153)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Do we have rough some stats on how many tests would use it out of a nightly run?
</blockquote></details>

I ran the acceptance tests in this branch previously and the ratio was 6:9 (standard:runtime assertions). I'll run a larger set of tests now that I rebased and compute this ratio again.
___
*[`pkg/cmd/roachtest/test_impl.go` line 156 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/98351#-NR3Kf8SCmgGHrc2rDcb:-NR8cSqO9Ts8Bd_ebe0G:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bc055478cc17c8756b457a31d35285ea25a3f250/pkg/cmd/roachtest/test_impl.go#L156)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Nit: passed -> specified
</blockquote></details>

Done.

**Comment by renatolabs** [comment]
Closing in favour of #111949.

**Pull request closed without merging**
