### PR TITLE
catalog/replication: test long running txns while advancing timestamps

### LINKED ISSUE #133731: catalog/replication: validate behaviour with long running txns for PCR reader catalog with a test
Currently we have no test coverage for the case where the timestamp is advanced in the PCR reader catalog while a long running txn is using any of the objects involved. This should work correctly and eventually unwedge, but we should add an explicit test to confirm that this waits for lease expiration.

Jira issue: CRDB-43736

Epic CRDB-43310

### PR DESCRIPTION
**Pull request by fqazi**
Previously, all of our PCR reader catalog tests tested fairly short txn's when advancing the timestamp. This confirmed that in the common case the reader catalog timestamp could be pushed forward. However, when long running txn's are executing we will need to wait for their leases to expire before the timestamps can be moved forward. To address this, this patch adds a test to confirm that we wait for leases to expire and that user txn's cannot be impacted because they have a AOST set.

Fixes: #133731

Release note: None

### CODE REVIEW

**Review by spilchen — COMMENTED** [review]
Looks good. I just had a few questions and some minor suggestions.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134240#-:-OAwYZHWC3VzMM4NENOK:bq3tyqp)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/catalog/replication/reader_catalog_test.go` line 431 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134240#-OAwVgKB7sz02GogGhYM:-OAwVgKB7sz02GogGhYN:b6zzob8) ([raw file](https://github.com/cockroachdb/cockroach/blob/159ddf1a3fb347780fefd41aed4fb77e273db7be/pkg/sql/catalog/replication/reader_catalog_test.go#L431)):*
> ```Go
> }
> 
> // TestReaderCatalogTSAdvanceWithLongTxn confirms that timestamps can advanced
> ```

nit: spelling



_Suggestion:_
```Go
// TestReaderCatalogTSAdvanceWithLongTxn confirms that timestamps can advance
```
___
*[`pkg/sql/catalog/replication/reader_catalog_test.go` line 435 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134240#-OAwTYde6kGKrT5aGKBP:-OAwTYde6kGKrT5aGKBQ:blpsw0t) ([raw file](https://github.com/cockroachdb/cockroach/blob/159ddf1a3fb347780fefd41aed4fb77e273db7be/pkg/sql/catalog/replication/reader_catalog_test.go#L435)):*
> ```Go
> func TestReaderCatalogTSAdvanceWithLongTxn(t *testing.T) {
> 	defer leaktest.AfterTest(t)()
> 	skip.UnderDuressWithIssue(t, 130901)
> ```

Is this issue correct? It was closed last month.
___
*[`pkg/sql/catalog/replication/reader_catalog_test.go` line 494 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134240#-OAwXSJPCysXDubg7OvC:-OAwXSJQBtnzfVoXVkN2:bvj093t) ([raw file](https://github.com/cockroachdb/cockroach/blob/159ddf1a3fb347780fefd41aed4fb77e273db7be/pkg/sql/catalog/replication/reader_catalog_test.go#L494)):*
> ```Go
> 	destRunner := sqlutils.MakeSQLRunner(destConn)
> 
> 	check := func(query string, isEqual bool) {
> ```

nit: do we ever pass `false` for `isEqual`? 
___
*[`pkg/sql/catalog/replication/reader_catalog_test.go` line 541 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134240#-OAwWvw402df_YjY_q3p:-OAwWvw402df_YjY_q3q:b-vv6c3d) ([raw file](https://github.com/cockroachdb/cockroach/blob/159ddf1a3fb347780fefd41aed4fb77e273db7be/pkg/sql/catalog/replication/reader_catalog_test.go#L541)):*
> ```Go
> 	require.NoError(t, advanceTS(now))
> 	// Confirm we waited for the lease to expire.
> 	require.LessOrEqual(t, LeaseExpirationTime, timeutil.Since(advanceStartTime))
> ```

We set the lease duration to `LeaseExpirationTime`, but I noticed that some jitter is applied to the actual duration. Is there a chance this could result in waiting slightly longer than `LeaseExpirationTime`?

**Review by fqazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134240)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @spilchen)

___
*[`pkg/sql/catalog/replication/reader_catalog_test.go` line 435 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134240#-OAwTYde6kGKrT5aGKBP:-OB5tx23-ytvfrx50g0-:bb9nis0) ([raw file](https://github.com/cockroachdb/cockroach/blob/159ddf1a3fb347780fefd41aed4fb77e273db7be/pkg/sql/catalog/replication/reader_catalog_test.go#L435)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Is this issue correct? It was closed last month.
</blockquote></details>

Done.

Yeah this is a copy and paste thing, cleaned it up.
___
*[`pkg/sql/catalog/replication/reader_catalog_test.go` line 541 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134240#-OAwWvw402df_YjY_q3p:-OB5us0RA6KMTX7nAdsD:b-g4d8gb) ([raw file](https://github.com/cockroachdb/cockroach/blob/159ddf1a3fb347780fefd41aed4fb77e273db7be/pkg/sql/catalog/replication/reader_catalog_test.go#L541)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

We set the lease duration to `LeaseExpirationTime`, but I noticed that some jitter is applied to the actual duration. Is there a chance this could result in waiting slightly longer than `LeaseExpirationTime`?
</blockquote></details>

Done.

I added code to disable the jitter, since it could make things faster. Longer doesn't really matter for this test.

**Review by spilchen — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134240#-:-OB64xEzAZXk1kooEXXb:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @fqazi)

**Comment by fqazi** [comment]
@spilchen TFTR!

bors r+

**Comment by fqazi** [comment]
blathers backport 24.3

**Pull request merged**
