### PR TITLE
opt: Enhance optsteps command to support exploration rules

### PR DESCRIPTION
**Pull request by andy-kimball**
This PR has 2 commits, for easier review:

1. Add AppliedRule event to memo: adds a new callback that the optimizer fires once it's done applying a rule; opsteps uses this to determine which part of the tree is affected by a rule

2. Enhance optsteps command to support exploration rules

### CODE REVIEW

**Comment by rytaft** [comment]
Reviewed 9 of 9 files at r1, 14 of 14 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[pkg/sql/opt/memo/best_expr.go, line 87 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24804#-LADpAbYBdkOYQStSh7L:-LADpAbYBdkOYQStSh7M:b76dxnz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4df75206f6dbcbcc0e782c4283352ec55115521/pkg/sql/opt/memo/best_expr.go#L87)):*
> ```Go
> // Expr returns the memo expression referenced by this best expression. Note
> // that if the best expression is an enforcer (like a Sort), then the memo
> // expression is wrapped by the enforcer (maybe even by multiple enforcers).
> ```

How does that change the Expr ID that is output?

---

*[pkg/sql/opt/norm/factory.go, line 28 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24804#-LADkO6pBjXMwgmPdQi1:-LADkO6pBjXMwgmPdQi2:bm68wii) ([raw file](https://github.com/cockroachdb/cockroach/blob/0da4d1472897579a4b3f5e0cd25f07ccb3eabeab/pkg/sql/opt/norm/factory.go#L28)):*
> ```Go
> 
> // MatchedRuleFunc defines the callback function for the NotifyOnMatchedRule
> // event. It is invoked each time a normalization rule has been matched by the
> ```

Why only normalization rules? If we want to disable optimizations, shouldn't we also be able to disable exploration rules?

---

*[pkg/sql/opt/norm/factory.go, line 104 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24804#-LADkfrK7deGzMPzy4v_:-LADkfrK7deGzMPzy4va:b-3g1r1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/0da4d1472897579a4b3f5e0cd25f07ccb3eabeab/pkg/sql/opt/norm/factory.go#L104)):*
> ```Go
> // NotifyOnMatchedRule sets a callback function which is invoked each time a
> // normalize rule has been matched by the factory. If matchedRule is nil, then
> // no further notifications are sent. If no callback function is set, then all
> ```

Isn't matchedRule the same as the callback function?  This pair of sentences almost makes it sound like you're talking about different things. Why not say: "If matchedRule is nil, then no notifications are sent, and all rules are applied by default."

---

*[pkg/sql/opt/norm/testdata/combo, line 1547 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24804#-LADqYal3FZrWDYxceXL:-LADqYal3FZrWDYxceXM:bhs7jb2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4df75206f6dbcbcc0e782c4283352ec55115521/pkg/sql/opt/norm/testdata/combo#L1547)):*
> ```
>          └── variable: column6 [type=decimal, outer=(6)]
> --------------------------------------------------------------------------------
> GenerateIndexScans (higher cost)
> ```

Why is it showing the higher cost tree here but not above? Did those rules not produce any new expressions?

---

*[pkg/sql/opt/testutils/opt_steps.go, line 47 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24804#-LADr9ex8UH8S9oX5OJN:-LADr9ex8UH8S9oX5OJO:bnku77s) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4df75206f6dbcbcc0e782c4283352ec55115521/pkg/sql/opt/testutils/opt_steps.go#L47)):*
> ```Go
> //      more difficult. This is because exploration rules are not guaranteed to
> //      produce a lower cost tree. Unless extra measures are taken, the returned
> //      ExprView would not included the changed portion of the Memo, since
> ```

would not included -> would not include

---

*[pkg/sql/opt/testutils/opt_steps.go, line 116 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24804#-LADrl4-5AdTuDQSFnen:-LADrl4-5AdTuDQSFneo:bxpdq4b) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4df75206f6dbcbcc0e782c4283352ec55115521/pkg/sql/opt/testutils/opt_steps.go#L116)):*
> ```Go
> // method will result in a panic.
> func (os *optSteps) done() bool {
> 	return os.remaining != 0
> ```

shouldn't this be `os.remaining == 0`?

---

*[pkg/sql/opt/testutils/opt_steps.go, line 123 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24804#-LADs4De3Z5MBzKuQwZx:-LADs4De3Z5MBzKuQwZy:b-h3u9x2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4df75206f6dbcbcc0e782c4283352ec55115521/pkg/sql/opt/testutils/opt_steps.go#L123)):*
> ```Go
> // isBetter methods.
> func (os *optSteps) next() error {
> 	if os.remaining != 0 {
> ```

why not call `os.done()` here?

---

*[pkg/sql/opt/testutils/opt_steps.go, line 142 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24804#-LADvNoQ25Pbe2ZBYdvS:-LADvNoQ25Pbe2ZBYdvT:b5g2it9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4df75206f6dbcbcc0e782c4283352ec55115521/pkg/sql/opt/testutils/opt_steps.go#L142)):*
> ```Go
> 			// an existing group. Record the id of the first of those expressions.
> 			// Previous expressions will be suppressed.
> 			ord := memo.ExprOrdinal(o.Memo().ExprCount(group) - added)
> ```

What if there are multiple expressions added? Can you print all of them?

---

*[pkg/sql/opt/testutils/opt_steps.go, line 160 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24804#-LADsbAq2ABKbtmBmK8r:-LADsbAq2ABKbtmBmK8s:b-fl3kwx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4df75206f6dbcbcc0e782c4283352ec55115521/pkg/sql/opt/testutils/opt_steps.go#L160)):*
> ```Go
> 	if os.better {
> 		os.best = text
> 	} else if os.remaining == 0 {
> ```

can use `os.done()` here too

---

*[pkg/sql/opt/testutils/opt_tester.go, line 329 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24804#-LADwJSi84VrAWQwaYKg:-LADwJSi84VrAWQwaYKh:b-d3jsrv) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4df75206f6dbcbcc0e782c4283352ec55115521/pkg/sql/opt/testutils/opt_tester.go#L329)):*
> ```Go
> 		next = os.exprView().FormatString(ot.Flags.Format)
> 
> 		if os.done() {
> ```

shouldn't this come before the line above?

---

*[pkg/sql/opt/xform/optimizer.go, line 32 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24804#-LADobOO5eyqO7XjPgYr:-LADobOO5eyqO7XjPgYs:bxp2tuf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0da4d1472897579a4b3f5e0cd25f07ccb3eabeab/pkg/sql/opt/xform/optimizer.go#L32)):*
> ```Go
> // The name of the matched rule is passed as a parameter. If the function
> // returns false, then the rule is not applied (i.e. skipped).
> type MatchedRuleFunc func(ruleName opt.RuleName) bool
> ```

why not reuse the definitions from `norm/factory.go` since those are exported (or use these definitions there)?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24804)*

**Comment by andy-kimball** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[pkg/sql/opt/memo/best_expr.go, line 87 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24804#-LADpAbYBdkOYQStSh7L:-LAF8OVF3HwKt7jNpVpr:b1mtqb3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4df75206f6dbcbcc0e782c4283352ec55115521/pkg/sql/opt/memo/best_expr.go#L87)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

How does that change the Expr ID that is output?
</blockquote></details>

The `ExprID` value is the same. The only difference is that `Operator` would be different (e.g. `Sort` rather than `Select`, or whatever). I added some more to the comment to clarify (I mention this above in the comment for the `eid` field as well).

---

*[pkg/sql/opt/norm/factory.go, line 28 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24804#-LADkO6pBjXMwgmPdQi1:-LAF9T_zAVj67I_u4Ead:b-hp5zjn) ([raw file](https://github.com/cockroachdb/cockroach/blob/0da4d1472897579a4b3f5e0cd25f07ccb3eabeab/pkg/sql/opt/norm/factory.go#L28)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why only normalization rules? If we want to disable optimizations, shouldn't we also be able to disable exploration rules?
</blockquote></details>

You're looking at the comment for the `Factory`, which only implements normalization rules. However, based on your comment below, I just went ahead and consolidated the definitions, so it now mentions exploration rules.

---

*[pkg/sql/opt/norm/factory.go, line 104 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24804#-LADkfrK7deGzMPzy4v_:-LAFAPjdEYImKVgUEmiP:b-ckbmlr) ([raw file](https://github.com/cockroachdb/cockroach/blob/0da4d1472897579a4b3f5e0cd25f07ccb3eabeab/pkg/sql/opt/norm/factory.go#L104)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Isn't matchedRule the same as the callback function?  This pair of sentences almost makes it sound like you're talking about different things. Why not say: "If matchedRule is nil, then no notifications are sent, and all rules are applied by default."
</blockquote></details>

Done, this comment is the result of many patches and cut and pastes that needed more final editing.

---

*[pkg/sql/opt/norm/testdata/combo, line 1547 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24804#-LADqYal3FZrWDYxceXL:-LAFAqAn2tdZqzkfax88:bpyz67k) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4df75206f6dbcbcc0e782c4283352ec55115521/pkg/sql/opt/norm/testdata/combo#L1547)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Why is it showing the higher cost tree here but not above? Did those rules not produce any new expressions?
</blockquote></details>

Correct, they produced no new expressions, probably because the indexes were not covering. Once Justin's done with his changes, the examples above will start producing index joins.

---

*[pkg/sql/opt/testutils/opt_steps.go, line 47 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24804#-LADr9ex8UH8S9oX5OJN:-LAFB0lQ0JX9tjJmOG4w:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4df75206f6dbcbcc0e782c4283352ec55115521/pkg/sql/opt/testutils/opt_steps.go#L47)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

would not included -> would not include
</blockquote></details>

Done.

---

*[pkg/sql/opt/testutils/opt_steps.go, line 116 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24804#-LADrl4-5AdTuDQSFnen:-LAFB41m8KR2RE7i9BSl:b-f56hjo) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4df75206f6dbcbcc0e782c4283352ec55115521/pkg/sql/opt/testutils/opt_steps.go#L116)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

shouldn't this be `os.remaining == 0`?
</blockquote></details>

`remaining` is the number of steps remaining in the "step budget" that gets set at the beginning of each iteration. If the entire "budget" was not used (i.e. remaining > 0), then we know that all steps were run. I added a comment to explain better.

---

*[pkg/sql/opt/testutils/opt_steps.go, line 123 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24804#-LADs4De3Z5MBzKuQwZx:-LAFBETx3J6rBQdlM6cs:b-fznogt) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4df75206f6dbcbcc0e782c4283352ec55115521/pkg/sql/opt/testutils/opt_steps.go#L123)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

why not call `os.done()` here?
</blockquote></details>

Good idea, done.

---

*[pkg/sql/opt/testutils/opt_steps.go, line 142 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24804#-LADvNoQ25Pbe2ZBYdvS:-LAFCcZZ2DAu8OobGGHt:bmtbo2n) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4df75206f6dbcbcc0e782c4283352ec55115521/pkg/sql/opt/testutils/opt_steps.go#L142)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

What if there are multiple expressions added? Can you print all of them?
</blockquote></details>

Currently, I don't. But I do have an idea of how I can at least print the root of those expressions. But if I do that, it will be in another PR.

---

*[pkg/sql/opt/testutils/opt_steps.go, line 160 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24804#-LADsbAq2ABKbtmBmK8r:-LAFCqTT58CJXSRF_TbR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4df75206f6dbcbcc0e782c4283352ec55115521/pkg/sql/opt/testutils/opt_steps.go#L160)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

can use `os.done()` here too
</blockquote></details>

Done.

---

*[pkg/sql/opt/testutils/opt_tester.go, line 329 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24804#-LADwJSi84VrAWQwaYKg:-LAFCvJbCU2zMO5rE46l:b5ljrg8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4df75206f6dbcbcc0e782c4283352ec55115521/pkg/sql/opt/testutils/opt_tester.go#L329)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

shouldn't this come before the line above?
</blockquote></details>

No, because I want to print out the final expression here:
```
	bestHeader(os.exprView(), "Final best expression\n")
	indent(next)
```
There's no diff between the final and the one before, but printing out the "clean" no-diff version at the end is helpful. I added a comment to the line to explain.

---

*[pkg/sql/opt/xform/optimizer.go, line 32 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24804#-LADobOO5eyqO7XjPgYr:-LAFDWqL9slhwDbXz6gm:b7kaixg) ([raw file](https://github.com/cockroachdb/cockroach/blob/0da4d1472897579a4b3f5e0cd25f07ccb3eabeab/pkg/sql/opt/xform/optimizer.go#L32)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

why not reuse the definitions from `norm/factory.go` since those are exported (or use these definitions there)?
</blockquote></details>

I think I was having issues with import cycles, and did it this way to workaround. I'm not sure why I didn't centralize these definitions in the `norm` package, though. I went ahead and did that, and made the definitions in `optimizer.go` be aliases of the ones in `factory.go`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24804)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 15 of 15 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/opt/testutils/opt_steps.go, line 142 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24804#-LADvNoQ25Pbe2ZBYdvS:-LAFIiWT-8HXAEupi-wQ:brxp9sq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4df75206f6dbcbcc0e782c4283352ec55115521/pkg/sql/opt/testutils/opt_steps.go#L142)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Currently, I don't. But I do have an idea of how I can at least print the root of those expressions. But if I do that, it will be in another PR.
</blockquote></details>

Sounds good.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24804#-:-LAFJRbrDuYkgu6iYcRU:bnfp4nl)*

**Comment by andy-kimball** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/opt/norm/testdata/combo, line 284 at r4](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24804#-LAIyE5M5QrUCnll4eU8:-LAIzK666TWK9OoZ24sX:b-8ibm7b) ([raw file](https://github.com/cockroachdb/cockroach/blob/57c0f14cb92322ae595a6b9ee95a04327f9b5155/pkg/sql/opt/norm/testdata/combo#L284)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

How come there are no changes here? These rules should be adding expressions to the memo, no?
</blockquote></details>

No, because the secondary index does not include the "i" column, which is needed by the query.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24804)*

**Comment by RaduBerinde** [comment]
:lgtm:   Very nice!

---

Review status: 2 of 17 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24804#-:-LAJ2GMOBCbbzxgDXTcY:b-97oliv)*

**Pull request merged**
