### PR TITLE
storage: implemented RuleSolver into allocator

### PR DESCRIPTION
**Pull request by d4l3k**
@BramGruneir @bdarnell

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8959)

### CODE REVIEW

**Comment by d4l3k** [comment]
Note: currently Example_rebalancing doesn't pass because the allocator isn't deterministic.

**Comment by BramGruneir** [comment]
Reviewed 3 of 3 files at r1, 8 of 8 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[storage/allocator.go, line 202 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8959#-KQW7eQ-1k1a3oudzCm5:-KQW7eQ0G8D7xsLVroqj:b-lplh28) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa2b13d8101a76bb87aa0b0b6f68ec84fb1c565e/storage/allocator.go#L202)):*
> ```Go
> 	}
> 
> 	log.Infof(context.TODO(), "AllocateTarget condidates %+v", candidates)
> ```

s/condidates/candidates

---

*[storage/allocator.go, line 344 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8959#-KQW8q7BQPHqectb3iEb:-KQW8q7BQPHqectb3iEc:bw111xu) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa2b13d8101a76bb87aa0b0b6f68ec84fb1c565e/storage/allocator.go#L344)):*
> ```Go
> 	// the mean range count.
> 	//
> 	// TODO(peter,bram,cuong): The FractionUsed check seems suspicious. When a
> ```

What makes this suspicious?

---

*[storage/rule_solver.go, line 69 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8959#-KQSLRPfooZpKFRfkxr_:-KQSLRPgzOJ-VfkiyfvB:bo98mtq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a1c86677e97ea7a5a6826cf28ac0229149fc3a1/storage/rule_solver.go#L69)):*
> ```Go
> // makeDefaultRuleSolver returns a ruleSolver with defaultRules.
> func makeDefaultRuleSolver(storePool *StorePool) *ruleSolver {
> 	return makeRuleSolver(storePool, defaultRules)
> ```

Is there any plan to use the non-default rules?  I'm wondering if that's just adding some needless complexity.

---

*[storage/rule_solver.go, line 88 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8959#-KQW4icyg66BkThman_z:-KQW4icyg66BkThmana-:b-t69bdb) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a1c86677e97ea7a5a6826cf28ac0229149fc3a1/storage/rule_solver.go#L88)):*
> ```Go
> }
> 
> // solve solves given constraints. See (*ruleSolver).solveInternal.
> ```

just remove one of the `solves`.

---

*[storage/rule_solver.go, line 104 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8959#-KQW558s6M4-C9kjGGiZ:-KQW558tgpzdYjWu8m9J:b-r0fexv) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a1c86677e97ea7a5a6826cf28ac0229149fc3a1/storage/rule_solver.go#L104)):*
> ```Go
> }
> 
> // solveScores solves given constraints and returns the score.
> ```

Does this need to be it's own function?  Why not mix it with solve or at least have it return the map instead of an array so you don't need to walk the array again in solves?  If needed you could return the sorted scores as well (but it looks like you toss them).

Oh, I see that this is called via the allocator.  It is unclear that this is the entry point to be called externally.  Can you capitalize the functions that are meant to be called externally?  (and I still think solve and solvescores might be combined.)

---

*[storage/rule_solver.go, line 127 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8959#-KQW5e55n39xBESKyJMR:-KQW5e55n39xBESKyJMS:b-79j5w9) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a1c86677e97ea7a5a6826cf28ac0229149fc3a1/storage/rule_solver.go#L127)):*
> ```Go
> }
> 
> func (rs *ruleSolver) computeCandidate(
> ```

Please add a description. (to all the functions without actually)

---

*[storage/store_pool.go, line 95 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8959#-KQW6zPmgre0-KQUH5Eb:-KQW6zPn85isNdT2Qomk:bvk7d9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa2b13d8101a76bb87aa0b0b6f68ec84fb1c565e/storage/store_pool.go#L95)):*
> ```Go
> }
> 
> // storeMatch is the return value for match().
> ```

fix comment.

---

*[storage/simulation/cluster.go, line 295 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8959#-KQWAusZLyHo71VZNNpT:-KQWAusZLyHo71VZNNpU:b-bi3zm6) ([raw file](https://github.com/cockroachdb/cockroach/blob/904b294d4f9d9850a02ca50fb8577bf1a925e0fb/storage/simulation/cluster.go#L295)):*
> ```Go
> 			rep.action, rep.priority = r.allocator.ComputeAction(r.zone, &r.desc)
> 			if rep.action == storage.AllocatorNoop {
> 				if _, ok := r.getRebalanceTarget(storeID); ok && c.rand.Float64() < 0.5 {
> ```

It might be worth rebalancing every time it can.  Since that's closer to what we do right now.  Or does it not converge?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8959)*

**Comment by d4l3k** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[storage/allocator.go, line 202 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8959#-KQW7eQ-1k1a3oudzCm5:-KQXBiBWVJ98k81nloDd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa2b13d8101a76bb87aa0b0b6f68ec84fb1c565e/storage/allocator.go#L202)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary>
> s/condidates/candidates
</details>
Done.

---

*[storage/rule_solver.go, line 88 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8959#-KQW4icyg66BkThman_z:-KQXHXvN7MaiE4Vij3LC:b45lxww) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a1c86677e97ea7a5a6826cf28ac0229149fc3a1/storage/rule_solver.go#L88)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary>
> just remove one of the `solves`.
</details>
Done in #8786.

---

*[storage/rule_solver.go, line 104 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8959#-KQW558s6M4-C9kjGGiZ:-KQXHbKJzoq8wLqwf5CY:bqn6y26) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a1c86677e97ea7a5a6826cf28ac0229149fc3a1/storage/rule_solver.go#L104)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary>
> Does this need to be it's own function?  Why not mix it with solve or at least have it return the map instead of an array so you don't need to walk the array again in solves?  If needed you could return the sorted scores as well (but it looks like you toss them).
> 
> Oh, I see that this is called via the allocator.  It is unclear that this is the entry point to be called externally.  Can you capitalize the functions that are meant to be called externally?  (and I still think solve and solvescores might be combined.)
</details>
Yeah, I was thinking just solve would be required for the exported interface and then we could use solveScores in tests. However, we need the scores to be public for use in the webui and allocator. Done in #8786.

---

*[storage/rule_solver.go, line 127 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8959#-KQW5e55n39xBESKyJMR:-KQXIfINbRX7OGKyN-u4:b45lxww) ([raw file](https://github.com/cockroachdb/cockroach/blob/4a1c86677e97ea7a5a6826cf28ac0229149fc3a1/storage/rule_solver.go#L127)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary>
> Please add a description. (to all the functions without actually)
</details>
Done in #8786.

---

*[storage/store_pool.go, line 95 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8959#-KQW6zPmgre0-KQUH5Eb:-KQXBxaOR9qXjf5Z5i2Y:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa2b13d8101a76bb87aa0b0b6f68ec84fb1c565e/storage/store_pool.go#L95)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary>
> fix comment.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8959)*

**Comment by d4l3k** [comment]
Just pushed some changes to make the results of Example_rebalancing deterministic and stripped out the old randGen framework.

---

Review status: 0 of 13 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8959#-:-KQXraacP8kWsYk9lnOq:bvdjjbk)*

**Comment by BramGruneir** [comment]
Reviewed 12 of 12 files at r5, 11 of 11 files at r6, 1 of 1 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[storage/rule_solver.go, line 205 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8959#-KQa8FbFAlL6a5lskPdn:-KQa8FbFAlL6a5lskPdo:b-ncbhhd) ([raw file](https://github.com/cockroachdb/cockroach/blob/c846a1858017e9d408284267ac0eee869334217d/storage/rule_solver.go#L205)):*
> ```Go
> 			continue
> 		}
> 		//tierScore := float64(int(1) << uint(len(state.tierOrder)-i-1))
> ```

Leftover?

---

*[storage/rule_solver.go, line 229 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8959#-KQa8MMs6hkiWJWqXm6i:-KQa8MMs6hkiWJWqXm6j:b-e68907) ([raw file](https://github.com/cockroachdb/cockroach/blob/c846a1858017e9d408284267ac0eee869334217d/storage/rule_solver.go#L229)):*
> ```Go
> }
> 
> // canonicalTierOrder returns the most key at each tier level.
> ```

the most key?

---

*[storage/rule_solver.go, line 238 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8959#-KQa8g-5arDFmmUmqwri:-KQa8g-5arDFmmUmqwrj:b9a1mm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c846a1858017e9d408284267ac0eee869334217d/storage/rule_solver.go#L238)):*
> ```Go
> 	}
> 
> 	tiers := make([]roachpb.Tier, 0, maxTierCount)
> ```

Could you a comment on what this is doing?

---

*[storage/simulation/cluster.go, line 295 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8959#-KQWAusZLyHo71VZNNpT:-KQa8vUBDtApyVPfhVi7:b5s538w) ([raw file](https://github.com/cockroachdb/cockroach/blob/904b294d4f9d9850a02ca50fb8577bf1a925e0fb/storage/simulation/cluster.go#L295)):*
<details><summary><i>Previously, d4l3k (Tristan Rice) wrote…</i></summary>
> Yeah, it doesn't converge. The real issue with the simulator is that it rebalances all nodes at the same time. So you  get 3 nodes with ranges counts of [10, 15,20] which will then rebalance to [20, 15, 10]. This wouldn't happen the same way when actually running since the replicate_queues fire at different times. Please correct me if I'm wrong.
</details>
Yeah, it's not a perfect solution, just designed to be an approximation.  This is good for now, but I need to add reservation hooks and maybe some simulated parallelism that would prevent the situation you're talking about.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8959)*

**Comment by BramGruneir** [comment]
Just a few minor issues left.  LGTM with those fixes.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8959#-:-KQaAA8xMk9H--xCNxAi:b-2stioi)*

**Comment by d4l3k** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[storage/rule_solver.go, line 205 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8959#-KQa8FbFAlL6a5lskPdn:-KQb7YXHTHy6nM5wv6dC:b45lxww) ([raw file](https://github.com/cockroachdb/cockroach/blob/c846a1858017e9d408284267ac0eee869334217d/storage/rule_solver.go#L205)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary>
> Leftover?
</details>
Done in #8786.

---

*[storage/rule_solver.go, line 229 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8959#-KQa8MMs6hkiWJWqXm6i:-KQb7bjLM7JyxN6SqNhJ:bd8s5j6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c846a1858017e9d408284267ac0eee869334217d/storage/rule_solver.go#L229)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary>
> the most key?
</details>
I a word. Done in #8786.

---

*[storage/rule_solver.go, line 238 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8959#-KQa8g-5arDFmmUmqwri:-KQb8U2XVoAiNVxvev67:b45lxww) ([raw file](https://github.com/cockroachdb/cockroach/blob/c846a1858017e9d408284267ac0eee869334217d/storage/rule_solver.go#L238)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary>
> Could you a comment on what this is doing?
</details>
Done in #8786.

---

*[storage/simulation/cluster.go, line 295 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8959#-KQWAusZLyHo71VZNNpT:-KQb7JzkYW1JZXSrWa-l:b-xalwcr) ([raw file](https://github.com/cockroachdb/cockroach/blob/904b294d4f9d9850a02ca50fb8577bf1a925e0fb/storage/simulation/cluster.go#L295)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary>
> Yeah, it's not a perfect solution, just designed to be an approximation.  This is good for now, but I need to add reservation hooks and maybe some simulated parallelism that would prevent the situation you're talking about.
</details>
That sounds like the ideal situation.         

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8959)*

**Comment by d4l3k** [comment]
@bdarnell @petermattis Any comments before merging this in?

**Comment by bdarnell** [comment]
No more comments from me.

**Pull request merged**
