### PR TITLE
opt: export build scalar functionality

### PR DESCRIPTION
**Pull request by RaduBerinde**
We will need to build scalars for calculating index constraints.

Release note: None

### CODE REVIEW

**Comment by andy-kimball** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22681#-:-L5JroEs8xr_8Dv17B0D:bnfp4nl)*

**Comment by rytaft** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/opt/optbuilder/builder.go, line 1188 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22681#-L5K1Lxiuxo9a0Cqjw0l:-L5K1Lxiuxo9a0Cqjw0m:b4tizr1) ([raw file](https://github.com/cockroachdb/cockroach/blob/021221b7c707601deaf28d25828d831aa444835a/pkg/sql/opt/optbuilder/builder.go#L1188)):*
> ```Go
> // Context, Factory, and TypedExpr.
> func NewScalar(ctx context.Context, factory opt.Factory) *ScalarBuilder {
> 	return &ScalarBuilder{
> ```

You're not initializing `semaCtx.IVarHelper` or `semaCtx.Placeholders`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22681)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/opt/optbuilder/builder.go, line 1188 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22681#-L5K1Lxiuxo9a0Cqjw0l:-L5KBtRjG_TVERlB2zBT:b-2tac7e) ([raw file](https://github.com/cockroachdb/cockroach/blob/021221b7c707601deaf28d25828d831aa444835a/pkg/sql/opt/optbuilder/builder.go#L1188)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

You're not initializing `semaCtx.IVarHelper` or `semaCtx.Placeholders`
</blockquote></details>

I don't know what IVarHelper in SemaContext is for; I don't think we use it. Not sure if we need the Placeholders, figured I'd look at it if it breaks in some test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22681)*

**Comment by rytaft** [comment]
:lgtm: just fix the minor issues with the comments

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/optbuilder/builder.go, line 1186 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22681#-L5KDoB_AVsg52DBMS1w:-L5KDoB_AVsg52DBMS1x:b8uh82g) ([raw file](https://github.com/cockroachdb/cockroach/blob/021221b7c707601deaf28d25828d831aa444835a/pkg/sql/opt/optbuilder/builder.go#L1186)):*
> ```Go
> 
> // NewScalar creates a new ScalarBuilder structure initialized with the given
> // Context, Factory, and TypedExpr.
> ```

Update comment - you're not providing a TypedExpr

---

*[pkg/sql/opt/optbuilder/builder.go, line 1188 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22681#-L5K1Lxiuxo9a0Cqjw0l:-L5KDgScrg8T9hjC8Q_0:b2nhlkw) ([raw file](https://github.com/cockroachdb/cockroach/blob/021221b7c707601deaf28d25828d831aa444835a/pkg/sql/opt/optbuilder/builder.go#L1188)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I don't know what IVarHelper in SemaContext is for; I don't think we use it. Not sure if we need the Placeholders, figured I'd look at it if it breaks in some test.
</blockquote></details>

Ok!

---

*[pkg/sql/opt/optbuilder/builder.go, line 1196 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22681#-L5KELmmRxbnWLV_evp2:-L5KELmmRxbnWLV_evp3:b-b1fs73) ([raw file](https://github.com/cockroachdb/cockroach/blob/021221b7c707601deaf28d25828d831aa444835a/pkg/sql/opt/optbuilder/builder.go#L1196)):*
> ```Go
> 
> // Build is the top-level function to build the memo structure inside
> // Builder.factory from the parsed SQL statement in Builder.stmt. See the
> ```

Update comment to mention the TypedExpr instead of parsed SQL statement

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22681#-:-L5KEkBOrmVWKcxMjORT:b-hxt3fj)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt/optbuilder/builder.go, line 1186 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22681#-L5KDoB_AVsg52DBMS1w:-L5Latvk2uThurvdcsc0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/021221b7c707601deaf28d25828d831aa444835a/pkg/sql/opt/optbuilder/builder.go#L1186)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Update comment - you're not providing a TypedExpr
</blockquote></details>

Done.

---

*[pkg/sql/opt/optbuilder/builder.go, line 1196 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22681#-L5KELmmRxbnWLV_evp2:-L5LbL_WqtKQJ9sZx0ky:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/021221b7c707601deaf28d25828d831aa444835a/pkg/sql/opt/optbuilder/builder.go#L1196)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Update comment to mention the TypedExpr instead of parsed SQL statement
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22681)*

**Comment by rytaft** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22681)*

**Pull request merged**
