### PR TITLE
ui: remove unnecessary uses of lodash in database pages

### LINKED ISSUE #68820: ui: replace lodash with vanilla Array methods where possible in the databases pages
As a quick-fix follow to #68390.

### PR DESCRIPTION
**Pull request by xinhaoz**
Closes #68820

This commit removes the ue of functions from the lodash function
where regular JS can be used.

Release note: None

### CODE REVIEW

**Review by maryliag — APPROVED** [review]
:lgtm: 

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78203#-:-MyiQPET8WxgW22MggpY:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @xinhaoz)

**Review by Azhng — COMMENTED** [review]
Should we purge the lodash from our `package.json` as well ? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78203#-:-MyiRtI09TKPhU2SOk7V:bmkxyh4)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @xinhaoz)

**Comment by xinhaoz** [comment]
Unfortunately we're still using it in other places. Most of the use cases are from years ago and can be replaced with simple JS (e.g. `isNil`, array functions, noops), but there are some places where we don't have an appropriate utility function equivalent, like lodash's deep equals or merge functions. Not sure if we want to purge all of lodash from our package and create utils for those as well, or if it'd be worth it. Perhaps @jocrl might have more insight into whether or not it would be worthwhile to update those use cases and get rid of lodash entirely. From what I understand it is a pretty large package.

**Comment by jocrl** [comment]
Agreed with Xin Hao, that there are still some places where lodash is useful. Lodash also exports the functions individually, so if we can define a specific set that we want to use we can just import those. I think it's a question of what our goals and priorities are.

I also think this might also involve a bigger picture of frontend decisions. For instance, `managed-service` still uses the whole loadash package. If anyone feels particularly motivated to try to get rid of it, I think a slack thread/RFC/file it for a CRUX ticket would be a good idea.

**Comment by xinhaoz** [comment]
TFTR!
bors r+

**Pull request merged**
