### PR TITLE
storage/engine: adjust {start,end} arg types on `{Writer,Reader}` methods

### PR DESCRIPTION
**Pull request by petermattis**
* storage/engine: remove unused Iterator.PrevKey
* storage/engine: adjust {start,end} arg types for FindSplitKey
* storage/engine: adjust {start,end} arg types for ComputeStats
* storage/engine: adjust {start,end} arg types for ClearIterRange
* storage/engine: adjust {start,end} arg types for {Iterate,Scan}

Release note: None

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
> Reviewed 13 of 25 files at r2, 7 of 12 files at r3, 16 of 21 files at r4, 1 of 4 files at r5, 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41897)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @sumeerbhola)

___
*[pkg/storage/engine/engine.go, line 240 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/41897#-LrxdnTy8kB3u9Wc5Vbj:-LrxdnTy8kB3u9Wc5Vbk:bntl5et) ([raw file](https://github.com/cockroachdb/cockroach/blob/2672716c9e382886ad11241e2772babf1849682f/pkg/storage/engine/engine.go#L240)):*
> ```Go
> 	// TODO(peter): Most callers want to pass roachpb.Key, except for
> 	// MVCCClearTimeRange. That function actually does what to clear records
> 	// between specific versions.
> ```

I can see an argument for leaving the `start` and `end` arg types for `ClearIterRange` as `MVCCKey` for symmetry. What do other folks think?

**Comment by petermattis** [comment]
Added another commit here which fixes crlfmt lint errors in `storage/engine`. These are apparently broken on master. Hmm, I should pull that out into a separate PR.

**Review by itsbilal — APPROVED** [review]
:lgtm:

> Reviewed 9 of 25 files at r2, 32 of 32 files at r7, 12 of 12 files at r8, 21 of 21 files at r9, 5 of 5 files at r10, 4 of 4 files at r11, 3 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41897#-:-LsJ7_nCAgo8B-MR9LBo:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajkr, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/engine.go, line 240 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/41897#-LrxdnTy8kB3u9Wc5Vbj:-LsIx1wcDgbkNA6BH-4Z:bxk2wtf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2672716c9e382886ad11241e2772babf1849682f/pkg/storage/engine/engine.go#L240)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I can see an argument for leaving the `start` and `end` arg types for `ClearIterRange` as `MVCCKey` for symmetry. What do other folks think?
</blockquote></details>

I think it's better to change it. I seem to associate `ClearIterRange` more strongly with `Iterate` than with `ClearRange`, for implementation reasons. It's probably best to convey that message in the interface as well - some of our `ClearIterRange` implementations already assume zero-timestamp keys as input.
___
*[pkg/storage/engine/engine.go, line 650 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/41897#-LsJ4c4hDo0ii6W9ylpO:-LsJ4c4hDo0ii6W9ylpP:b-4of01g) ([raw file](https://github.com/cockroachdb/cockroach/blob/30d443bc59d8a49d00c9e491518207d55f25918a/pkg/storage/engine/engine.go#L650)):*
> ```Go
> }
> 
> // Helper function to implement Iterate() on Pebble, pebbleSnapshot,
> ```

Also used with RocksDB now - might want to update the comment to reflect that.

**Review by petermattis — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41897#-:-LsJBx_500xmrf_AWi_3:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajkr, @itsbilal, and @sumeerbhola)

___
*[pkg/storage/engine/engine.go, line 240 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/41897#-LrxdnTy8kB3u9Wc5Vbj:-LsJBqD23VpcRc2j1BaI:b-8ns3tb) ([raw file](https://github.com/cockroachdb/cockroach/blob/2672716c9e382886ad11241e2772babf1849682f/pkg/storage/engine/engine.go#L240)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

I think it's better to change it. I seem to associate `ClearIterRange` more strongly with `Iterate` than with `ClearRange`, for implementation reasons. It's probably best to convey that message in the interface as well - some of our `ClearIterRange` implementations already assume zero-timestamp keys as input.
</blockquote></details>

Great. Thanks for the thoughts.
___
*[pkg/storage/engine/engine.go, line 650 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/41897#-LsJ4c4hDo0ii6W9ylpO:-LsJBvbD2JhXH3PAXrkT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/30d443bc59d8a49d00c9e491518207d55f25918a/pkg/storage/engine/engine.go#L650)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Also used with RocksDB now - might want to update the comment to reflect that.
</blockquote></details>

Done.

**Comment by petermattis** [comment]
bors r=itsbilal

**Pull request merged**
