### PR TITLE
storage: DRY {client_,}range_tree_test.go #7495

### PR DESCRIPTION
**Pull request by a6802739**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7639)

### CODE REVIEW

**Comment by knz** [comment]
cc @BramGruneir @tamird

**Comment by BramGruneir** [comment]
Hey @a6802739.  This is looking good.

Can you sign the CLA.

Also, please squash the 2 commits into a single commit.  
Rename it to storage: delete range tree

And  in the commit message, have the last line read "Closes #7495" so it will close the issue directly.  

---

Reviewed 13 of 13 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[storage/store_test.go, line 1801 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7639#-KM0qPCn-xua0mzY62vN:-KM0qPCn-xua0mzY62vO:-1664674655) ([raw file](https://github.com/cockroachdb/cockroach/blob/ecc93e65bafe9ad013e90c091395edd1328b8073/storage/store_test.go#L1801)):*
> ```Go
> 		t.Fatal(err)
> 	}
> 	args6 := scanArgs(keys.RangeTreeNodeKey(rangeTreeRootAddr), roachpb.Key("a"))
> ```

Is there another range local address you can use here.  Seems like that's what this test is looking for.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7639#-:-KM0X3gjbMcyDVFW6v6G:1756731674)*

**Comment by tamird** [comment]
This PR description is incorrect.

**Comment by a6802739** [comment]
@BramGruneir , it's my first PR,  thanks for your advice. I'll try it again as you say. So should I close this issue and propose another PR again? my previous local git's config was wrong, I just correct it.

**Comment by knz** [comment]
You can continue to use this PR.

Simply modify your commit then overwrite the same branch on github with 'git push -f'


-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by knz** [comment]
Deprecated by #7692.

**Pull request closed without merging**
