### PR TITLE
serverutils: make test logs quieter

### PR DESCRIPTION
**Pull request by dt**
Release note: none.
Epic: none

### CODE REVIEW

**Review by stevendanna — COMMENTED** [review]
I think we've gotten mixed feedback about this.  Some find it rather verbose. Others like that it is easy to notice.

Wonder if you'd be opposed to something in between:

```
Test server is using a secondary tenant (virtual cluster). A test
failure may be a problem specific to multi-tenancy. To investigate,
"COCKROACH_TEST_TENANT=true" will force-enable secondary tenants in
all runs ("false" to force-disable).
```

**Comment by dt** [comment]
I don’t think it should be more than one line. 

The verbosity might be handy the _first time_ you see it, so the verbosity at initia introduction was many worth while, but it very quickly becomes noise, and many of us have now seen it hundreds/thousands of times. Being multi-line is pushing other lines, that are actually unique to a specific test run, below the fold. The log-line doesn’t need  to explain the situation in detail, and absolutely does not need to explain how to debug it further, every time it is logged: it just needs to indicate you are in the situation or not, and can point you towards an explainer if you are seeing it for the first time and thus need it, but the leave room in the rest of the logs for actual unique information.

**Review by stevendanna — COMMENTED** [review]
I have few opinions on the content, my main concern is whether it is easy to spot when investigating a test failure.

That said, this is the kinda change that I don't think should require any gatekeeping. The proof will be in the pudding. We can try this message for a bit. Perhaps one day someone spends a lot of time debugging a test and makes the warning more prominent as a result. Or perhaps we never change this message again.

**Review by stevendanna — APPROVED** [review]

**Comment by dt** [comment]
I am ambivalent about the prominence -- we can use ALL CAPS or some exclamation points or unicode to make it more eye catching if we want -- I just don't like it pushing all the information unique to one specific execution below the fold.

TFTR!

bors r+

**Pull request merged**
