### PR TITLE
kvserver: version gate locality-aware load-based rebalancing

### LINKED ISSUE #76702: kvserver: version gate the new `StoreRebalancer` implementation
We rewrote the load-based rebalancing scheme in https://github.com/cockroachdb/cockroach/pull/65379 and https://github.com/cockroachdb/cockroach/pull/72296. We'll need to version gate this implementation of the `StoreRebalancer` for mixed version settings and probably have mixed version clusters behave identically to 21.2 clusters in terms of their load-based rebalancing behavior. 

To this end, we should introduce a `DeprecatedStoreRebalancer` that is the 21.2 implementation and only switch to the new implementation after the version upgrade is finalized.

Jira issue: CRDB-13240

### PR DESCRIPTION
**Pull request by aayushshah15**
This commit introduces a set of deprecated store rebalancer methods
corresponding to the pre-22.1 load-rebalancing scheme. Until a store detects
that the version upgrade (to 22.1) has been finalized, the store will fall back
to the old (pre-22.1) load-based rebalancing logic that wasn't locality aware.

This is done in order to minimize risk of unexpected behavior in mixed version
clusters.

All the tests corresponding to the old logic have been re-introduced, and are unchanged.

Resolves https://github.com/cockroachdb/cockroach/issues/76702

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80190)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15)

___
*[-- commits, line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80190#-N07tB8T5U1_RLs2QJmD):*
Could you link to the commit(s) that this is referencing? I know a lot of this was changed in https://github.com/cockroachdb/cockroach/pull/72296/commits/13ac98397793857ecb614a30cd6fad4ea3f424e4, but it's difficult for me to convince myself that the logic in `pkg/kv/kvserver/deprecated_store_rebalancer.go` is exactly the same as it was before that commit. It doesn't appear to be. Were there other changes in this area that impacted that logic?

Did you pull `pkg/kv/kvserver/deprecated_store_rebalancer.go` straight from the `release-21.2` release branch? Were any changes needed?
___
*[pkg/cmd/roachtest/tests/rebalance_load.go, line 72 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80190#-N07u_8zDecx45CuPH6g:-N07u_8zDecx45CuPH6h:bswbiub) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2dc4bba579fa46021b39c7f9ea5ff0b67ff58cf/pkg/cmd/roachtest/tests/rebalance_load.go#L72)):*
> ```Go
> 			// Upgrade some (or all) of the first N-1 nodes. Ignore the very last node
> 			// since it is the app node.
> 			lastNodeToUpgrade := rand.Intn(c.Spec().NodeCount - 1)
> ```

`rand.Intn` returns a value from the interval [0,n). So this is returning a value between `[0, node_count - 1)`. We then pass this to `c.Range`, which expects 1-indexed node IDs. Does this mean that we'll never update the last CRDB node and sometimes not even update the first?
___
*[pkg/kv/kvserver/allocator_scorer.go, line 919 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80190#-N07sk3K68ZXzdlQ7zpC:-N07sk3K68ZXzdlQ7zpD:be0x4tk) ([raw file](https://github.com/cockroachdb/cockroach/blob/a26cfaaba8ab63fc392bb939a8ec4dc57c87aa6f/pkg/kv/kvserver/allocator_scorer.go#L919)):*
> ```Go
> 		// NB: This is only applicable in mixed version clusters.
> 		// `rankedCandidateListForAllocation` will never be called in 22.1 with a
> 		// `qpsScorerOptions`.
> ```

When should we plan to remove this kind of compatibility logic?

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80190)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[-- commits, line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80190#-N07tB8T5U1_RLs2QJmD):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Could you link to the commit(s) that this is referencing? I know a lot of this was changed in https://github.com/cockroachdb/cockroach/pull/72296/commits/13ac98397793857ecb614a30cd6fad4ea3f424e4, but it's difficult for me to convince myself that the logic in `pkg/kv/kvserver/deprecated_store_rebalancer.go` is exactly the same as it was before that commit. It doesn't appear to be. Were there other changes in this area that impacted that logic?

Did you pull `pkg/kv/kvserver/deprecated_store_rebalancer.go` straight from the `release-21.2` release branch? Were any changes needed?
</blockquote></details>

This was pulled straight from `release-21.2` with no material changes. None of the tests were changed either.

I did so because, as you mentioned, there were a bunch of changes in the area because of https://github.com/cockroachdb/cockroach/pull/65379 and https://github.com/cockroachdb/cockroach/pull/72296  (and other minor commits), which I didn't want.
___
*[pkg/cmd/roachtest/tests/rebalance_load.go, line 72 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80190#-N07u_8zDecx45CuPH6g:-N07wrso6A3o5jBz6r5m:bg6k5hm) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2dc4bba579fa46021b39c7f9ea5ff0b67ff58cf/pkg/cmd/roachtest/tests/rebalance_load.go#L72)):*
> Does this mean that we'll never update the last CRDB node

Yep, this was intentional, though I did want to update at least one node. Updated.
___
*[pkg/kv/kvserver/allocator_scorer.go, line 919 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80190#-N07sk3K68ZXzdlQ7zpC:-N07x1fq59ZNA5sDvJr4:bsefzh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a26cfaaba8ab63fc392bb939a8ec4dc57c87aa6f/pkg/kv/kvserver/allocator_scorer.go#L919)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

When should we plan to remove this kind of compatibility logic?
</blockquote></details>

Updated the comment.

We don't _need_ to merge this PR on `master` but I thought that was a good idea regardless, in order to get the extra CI coverage.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80190#-:-N0HZJfN7eexgv3J20-G:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15)

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 10 of 13 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80190#-:-N0XqR_tAOnU9DyUGWLm:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15)

**Comment by aayushshah15** [comment]
TFTR!

bors r+

**Comment by aayushshah15** [comment]
Bumping the priority on this so this can go in before I merge the backport and we can close the blocker out. 

bors p=999

**Pull request merged**
