### PR TITLE
c-deps: bump rocksdb for WAL recycling fix

### PR DESCRIPTION
**Pull request by ajkr**
Picks up https://github.com/cockroachdb/rocksdb/pull/64.

Release note: None

### CODE REVIEW

**Comment by ajkr** [comment]
Do bugs that only ever existed in a beta deserve a release note? (My guess was no for master, not sure for the upcoming 19.2 backport.)

**Review by sumeerbhola — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41502)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @BramGruneir, @itsbilal, and @petermattis)

**Review by BramGruneir — APPROVED** [review]
Doesn't hurt to put it in. Just write that it was only present in the alphas and previous beta.

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41502#-:-LqrMHSi8EE3JSAT4PIL:b-lans5c)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @BramGruneir, @itsbilal, and @petermattis)

**Comment by ajkr** [comment]
Got it, thanks. I'll do that on the upcoming PR for backport to 19.2 as putting that here would look confusing on the 20.1 release notes.

bors r+

**Pull request merged**
