### PR TITLE
ui: add licensing notification to Db Console

### LINKED ISSUE #98589: observability: show license expiry date in DB Console
Currently, the only way to find out when the license expires is by inspecting the metric `seconds_until_enterprise_license_expiry` and do a little bit of math.

It would be friendlier to have this information in the DB Console, and/or backed into the license key itself, as in `crl-0-EZASDEJNFIiCFfswegG8w-2023-04-01`.

[slack](https://cockroachlabs.slack.com/archives/CHKQGKYEM/p1678808651499069)

gz#16317

Jira issue: CRDB-25437

### PR DESCRIPTION
**Pull request by koorosh**
Before, there was a change which added alert pop up to notify users about remaining days before license expires. Instead, it requires to show this information permanently for clusters with Enterprise of Trial licenses.
This change:
- removes pop up alert with licensing
- adds notification message on top panes (left to user's name) which indicates how many days left before license expires. Also it shows as a warning if less than 30 days remains, and with "danger" icon - if license expired.

Release note: show notification message about license expiration for clusters with enterprise or trial license.

Resolves: #98589

License expires today:
Screenshot 2024-03-21 at 13 20 35

License expires in 30 days:
Screenshot 2024-03-21 at 13 18 31

License expires in 365 days:
Screenshot 2024-03-21 at 13 17 05

License expired many days ago:
Screenshot 2024-03-21 at 13 15 15

### CODE REVIEW

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120830)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @innabs, @koorosh, and @xinhaoz)

___
*[`pkg/ui/workspaces/db-console/src/views/app/containers/licenseNotification/licenseNotification.tsx` line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120830#-NtX1XmREFyxYG8CnSYn:-NtX1XmREFyxYG8CnSYo:b-x4pb2k) ([raw file](https://github.com/cockroachdb/cockroach/blob/3afb1156ff64127512055e2ebee600f1fa57c2e5/pkg/ui/workspaces/db-console/src/views/app/containers/licenseNotification/licenseNotification.tsx#L75)):*
> ```XML
>         You are using {licenseType} license of CockroachDB. <br />
>         To avoid service disruption, please renew it.{" "}
>         <a
> ```

Can we share the link sentence between the different tooltip content values? maybe lift the `<span>` tag into a functional component that takes the specific license text as a prop.
___
*[`pkg/ui/workspaces/db-console/src/views/app/containers/licenseNotification/licenseNotification.tsx` line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120830#-NtX1gLt2zAHwHPgBc39:-NtX1gLt2zAHwHPgBc3A:bdygvxx) ([raw file](https://github.com/cockroachdb/cockroach/blob/3afb1156ff64127512055e2ebee600f1fa57c2e5/pkg/ui/workspaces/db-console/src/views/app/containers/licenseNotification/licenseNotification.tsx#L83)):*
> ```XML
>           Learn more
>         </a>{" "}
>         how to renew.
> ```

Can you check with Kevin and Inna about the `Learn more how to renew.` sentence. I don't think that's what we want. Maybe just a link with `How to renew.` or `Learn more about renewing your license`. Not sure.

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120830)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @dhartunian, @innabs, and @xinhaoz)

___
*[`pkg/ui/workspaces/db-console/src/views/app/containers/licenseNotification/licenseNotification.tsx` line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120830#-NtX1XmREFyxYG8CnSYn:-Nto_u2N2JDDCvzv5HTO:bit0c9v) ([raw file](https://github.com/cockroachdb/cockroach/blob/3afb1156ff64127512055e2ebee600f1fa57c2e5/pkg/ui/workspaces/db-console/src/views/app/containers/licenseNotification/licenseNotification.tsx#L75)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Can we share the link sentence between the different tooltip content values? maybe lift the `<span>` tag into a functional component that takes the specific license text as a prop.
</blockquote></details>

Combined two "if" cases into single one as they describe expired condition. Now, only `title` field defined conditionally.

**Review by dhartunian — APPROVED** [review]
:lgtm: assuming we vet this for cloud before merging.

> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120830#-:-Ntqq6xEEMAtnhXwJaA-:b-o0b3id)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @abarganier, @innabs, and @xinhaoz)

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120830)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier, @dhartunian, @innabs, and @xinhaoz)

___
*[`pkg/util/log/flags.go` line 57 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/120830#-NtzgR121d4yKx6iw9iU:-NtzgR121d4yKx6iw9iV:b-d7djj8) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ea85d09a58f0d0cfcd9c6c959dd1c5623735de1/pkg/util/log/flags.go#L57)):*
> ```Go
> const redactionPolicyManagedEnvVar = "COCKROACH_REDACTION_POLICY_MANAGED"
> 
> var RedactionPolicyManaged = envutil.EnvOrDefaultBool(redactionPolicyManagedEnvVar, false)
> ```

@dhartunian , it requires to change the way env variable retrieved to reuse it in `ui` package.
My only concern here that this variable now is public but couldn't find a better place to move it.

**Review by dhartunian — COMMENTED** [review]
> Reviewed 4 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120830)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier, @innabs, @koorosh, and @xinhaoz)

___
*[`-- commits` line 18 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/120830#-Nu-aagm0rCrzGAV2_1p):*
nit: add that this is in a header in DB Console
___
*[`pkg/ui/workspaces/db-console/src/views/app/containers/licenseNotification/licenseNotification.tsx` line 47 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/120830#-Nu-amu07qy4C6gr5dgF:-Nu-amu07qy4C6gr5dgG:b-ctsz16) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ea85d09a58f0d0cfcd9c6c959dd1c5623735de1/pkg/ui/workspaces/db-console/src/views/app/containers/licenseNotification/licenseNotification.tsx#L47)):*
> ```XML
>   let tooltipContent: JSX.Element;
> 
>   const learMore = (
> ```

nit: "learn"

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120830)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @abarganier, @innabs, and @xinhaoz)

___
*[`-- commits` line 18 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/120830#-Nu-aagm0rCrzGAV2_1p):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: add that this is in a header in DB Console
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/db-console/src/views/app/containers/licenseNotification/licenseNotification.tsx` line 47 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/120830#-Nu-amu07qy4C6gr5dgF:-Nu0FcYN3pw5Ff6vYdGl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ea85d09a58f0d0cfcd9c6c959dd1c5623735de1/pkg/ui/workspaces/db-console/src/views/app/containers/licenseNotification/licenseNotification.tsx#L47)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: "learn"
</blockquote></details>

Done.

**Review by dhartunian — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120830#-:-Nu05hU-5eTJlrKpdX3r:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @abarganier, @innabs, and @xinhaoz)

**Pull request merged**
