### PR TITLE
opt: improve comment for mapSetOptFilter

### PR DESCRIPTION
**Pull request by mgartner**
#### opt: improve comment for mapSetOptFilter

This commit clarifies a comment in the mapSetOptFilter function. It
specifies that column IDs that are not part of the output columns are
not replaced by this function.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
While you're at it, would you mind moving the definition of this rule to `select.opt` where it belongs?

**Comment by RaduBerinde** [comment]
(and I guess the testcases too)

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47095#-:-M4GV4vFC6ONW5U0s4BU:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/norm/custom_funcs.go, line 1478 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47095#-M4GUVrt4vovreHuh4Gu:-M4GUVrt4vovreHuh4Gv:bnscv1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad700ab19ac9a8747dde854280e3f60488a17d10/pkg/sql/opt/norm/custom_funcs.go#L1478)):*
> ```Go
> 		switch t := nd.(type) {
> 		case *memo.VariableExpr:
> 			dstCol, inCol := colMap.Get(int(t.Col))
> ```

While you're here I'd also change `inCol` to `ok`, which is more idiomatic.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47095)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/norm/custom_funcs.go, line 1478 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47095#-M4GUVrt4vovreHuh4Gu:-M4GZjqPBUcrncEZIAMQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad700ab19ac9a8747dde854280e3f60488a17d10/pkg/sql/opt/norm/custom_funcs.go#L1478)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

While you're here I'd also change `inCol` to `ok`, which is more idiomatic.
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47095)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47095#-:-M4GtlAw2dVOYnm5nhEM:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @rytaft)

**Pull request merged**
