### PR TITLE
c-deps: bump rocksdb for multiple backported PRs

### LINKED ISSUE #37752: While sync_file_range offset 0 bytes 557056
**Describe the problem**

```
[n1,s1,r4/1:/System{/tsd-tse}] while committing batch: while committing batch: IO error: While sync_file_range offset 0 bytes 557056: /mnt/d/debian/store1/000003.log: Function not implemented
goroutine 212 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc0004b8000, 0xc0004b8060, 0x53d3200, 0x10)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1020 +0xd4
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x5b5d300, 0xc000000004, 0x53d326d, 0x10, 0xe63, 0xc0009fa900, 0xbf)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:876 +0x95a
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x3a431c0, 0xc00a668ea0, 0x4, 0x2, 0x32c0ea2, 0x6, 0xc009587eb0, 0x2, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:85 +0x2d8
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x3a431c0, 0xc00a668ea0, 0x1, 0x4, 0x32c0ea2, 0x6, 0xc009587eb0, 0x2, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:71 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(0x3a431c0, 0xc00a668ea0, 0x32c0ea2, 0x6, 0xc009587eb0, 0x2, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:182 +0x7e
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processReady(0xc000cc2000, 0x3a431c0, 0xc00a668ea0, 0x4)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3683 +0x4f4
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc000507600, 0x3a431c0, 0xc000c6c3f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:214 +0x258
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x3a431c0, 0xc000c6c3f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:165 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc0002194f0, 0xc0009bc000, 0xc0002194e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:200 +0xe1
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:193 +0xa8
```

**Additional data / screenshots**
image

**Environment:**
 - CockroachDB version : 2.x
 - Server OS: windows wsl debian
 - Client app: psql

### PR DESCRIPTION
**Pull request by ajkr**
Includes the following changes, all of which have landed upstream.

- cockroachdb/rocksdb#32: "Fix merging range tombstone covering put during flush/compaction"
- cockroachdb/rocksdb#33: "Dynamic test whether sync_file_range returns ENOSYS"
- cockroachdb/rocksdb#34: "Potential fix for stress test failure due to "SST file ahead of WAL" error"
- cockroachdb/rocksdb#35: "Avoid deadlock between mutex_ and log_write_mutex_"

Fixes #37752.

Release note (bug fix): Fixed possible deadlock when storage engine
write fails.

Release note (bug fix): Fixed potential reappearance of deleted
timeseries data, which could trip consistency checker.

Release note (bug fix): Removed dependency on `sync_file_range` on
Linux platforms on which it returns `ENOSYS`, such as WSL (Windows
Subsystem for Linux).

### CODE REVIEW

**Comment by ajkr** [comment]
Ugh, I'm a little bit worried that the WSL fix is the wrong approach after seeing this page mention that WSL has partial support for `sync_file_range`: https://docs.microsoft.com/en-us/windows/wsl/release-notes. If that is the case then probably a no-op `sync_file_range` would be supported. Postgres's approach was better because they just check if their regular call to `sync_file_range` returned `ENOSYS` and, if so, don't try calling it again.

I might just leave it because programming to a platform that I don't have is too speculative and annoying, unless anyone objects.

**Comment by ajkr** [comment]
Well, it's Friday, so I tried out installing WSL and running the no-op `sync_file_range`. It indeed returned `ENOSYS`. So that means the change we already made works, and the docs about a partial implementation are misleading.

**Review by petermattis — APPROVED** [review]
LGTM

The release note for `sync_file_range` should mention Windows Subsystem for Linux as being a Linux system which doesn't support `sync_file_range`.

**Pull request merged**
