### PR TITLE
sql: refactor the handling of query placeholders.

### PR DESCRIPTION
**Pull request by knz**
This patch is mostly a clean-up of the code supporting SQL
placeholders:
- The placeholder map is now constructed directly in the pgwire
  driver, instead of being first stored in an array and then converted.
- As a result, the Args interface disappears.
- TypeCheck() now directly replaces a Placeholder with its assigned
  value (query argument) if any is supplied, so that FillArgs and the
  argVisitor are not required any more.
- As a result, the Expr objects in syntax trees now are immutable
  throughout a query execution and even across retries. This may
  obviate the need to test that the syntax tree hasn't changed by
  comparing its string representation before and after execution.

This changeset introduces no user-visible changes.

cc @RaduBerinde

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6983)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Review status: 0 of 21 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[sql/executor.go, line 330 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJL5zRI6fUg6qYsYvWB:-KJL5zRI6fUg6qYsYvWC:-2073623660) ([raw file](https://github.com/cockroachdb/cockroach/blob/f225b3f5ae980b8d44c80aacd93eaa66b620b043/sql/executor.go#L330)):*
> ```Go
> func (e *Executor) ExecuteStatements(
> 	ctx context.Context, session *Session, stmts string,
> 	pinfo *parser.PlaceholderInfo) StatementResults {
> ```

[nit] can you reformat the declaration according to the style guide?

---

*[sql/parser/eval.go, line 1925 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJL9Qp3kao2lQsiTAa2:-KJL9Qp3kao2lQsiTAa3:1649353210) ([raw file](https://github.com/cockroachdb/cockroach/blob/f225b3f5ae980b8d44c80aacd93eaa66b620b043/sql/parser/eval.go#L1925)):*
> ```Go
> }
> 
> // Eval implements the Expr interface.
> ```

TypedExpr

---

*[sql/parser/eval.go, line 1927 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJL8e2OMZG-c4L3CpVa:-KJL8e2OMZG-c4L3CpVb:2125771577) ([raw file](https://github.com/cockroachdb/cockroach/blob/f225b3f5ae980b8d44c80aacd93eaa66b620b043/sql/parser/eval.go#L1927)):*
> ```Go
> // Eval implements the Expr interface.
> func (t *DPlaceholder) Eval(_ *EvalContext) (Datum, error) {
> 	if v, ok := t.pmap.Value(t.name); ok {
> ```

How can this happen? We should have converted any placeholders with the value when we did TypeCheck right? The only way I can think of is if a value is set after we call `TypeCheck` but  I don't think that's supposed to happen..

---

*[sql/parser/placeholders.go, line 42 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJL4tCEGu_dFlT-yVLV:-KJL4tCF8a2Z2CmkP4uf:-1930705874) ([raw file](https://github.com/cockroachdb/cockroach/blob/f225b3f5ae980b8d44c80aacd93eaa66b620b043/sql/parser/placeholders.go#L42)):*
> ```Go
> // Clear resets the placeholder info map.
> func (p *PlaceholderInfo) Clear() {
> 	p.Types = PlaceholderTypes{}
> ```

could we use the typical "make" syntax here? I wasn't sure if this syntax creates the map.

---

*[sql/parser/placeholders.go, line 78 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJL7L0sOo46Ax79FTuO:-KJL7L0t0JrvyZT9jZOu:1424206625) ([raw file](https://github.com/cockroachdb/cockroach/blob/f225b3f5ae980b8d44c80aacd93eaa66b620b043/sql/parser/placeholders.go#L78)):*
> ```Go
> func (p *PlaceholderInfo) SetValue(name string, val Datum) error {
> 	if _, ok := p.Values[name]; ok {
> 		return fmt.Errorf("placeholder %s already has a value", name)
> ```

we are never actually checking the returned error.. should this be a panic instead?

---

*[sql/parser/placeholders.go, line 99 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJL7pnAAf8QixvyxTc9:-KJL7pnAAf8QixvyxTcA:-1873782534) ([raw file](https://github.com/cockroachdb/cockroach/blob/f225b3f5ae980b8d44c80aacd93eaa66b620b043/sql/parser/placeholders.go#L99)):*
> ```Go
> 
> // SetTypes resets the type and values in the map. If src is nil, the
> // map is cleared.
> ```

It should be specified here that we are aliasing the given map and not making a copy.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983)*

**Comment by knz** [comment]
Review status: 0 of 21 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[sql/executor.go, line 330 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJL5zRI6fUg6qYsYvWB:-KJMfbEf-BLd2Fr2ZLfz:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/f225b3f5ae980b8d44c80aacd93eaa66b620b043/sql/executor.go#L330)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> [nit] can you reformat the declaration according to the style guide?
</details>
Done.

---

*[sql/parser/eval.go, line 1925 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJL9Qp3kao2lQsiTAa2:-KJMdg5Kqx4s00V_Nj1S:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/f225b3f5ae980b8d44c80aacd93eaa66b620b043/sql/parser/eval.go#L1925)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> TypedExpr
</details>
Done.

---

*[sql/parser/eval.go, line 1927 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJL8e2OMZG-c4L3CpVa:-KJMe15WMPaMJzOfpWqG:452878259) ([raw file](https://github.com/cockroachdb/cockroach/blob/f225b3f5ae980b8d44c80aacd93eaa66b620b043/sql/parser/eval.go#L1927)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> How can this happen? We should have converted any placeholders with the value when we did TypeCheck right? The only way I can think of is if a value is set after we call `TypeCheck` but  I don't think that's supposed to happen..
</details>
Good catch, this is a leftover from a previous implementation. Fixed.

---

*[sql/parser/placeholders.go, line 42 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJL4tCEGu_dFlT-yVLV:-KJMe61uW6C_TPEgZLjG:77051938) ([raw file](https://github.com/cockroachdb/cockroach/blob/f225b3f5ae980b8d44c80aacd93eaa66b620b043/sql/parser/placeholders.go#L42)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> could we use the typical "make" syntax here? I wasn't sure if this syntax creates the map.
</details>
I am not overly fond of the make() syntax for non-slice, non-array parameters. It puts too much emphasis on the underlying implementation of an abstract type.

---

*[sql/parser/placeholders.go, line 78 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJL7L0sOo46Ax79FTuO:-KJMeQDkS6BGCrFK4yFv:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/f225b3f5ae980b8d44c80aacd93eaa66b620b043/sql/parser/placeholders.go#L78)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> we are never actually checking the returned error.. should this be a panic instead?
</details>
Done.

---

*[sql/parser/placeholders.go, line 99 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJL7pnAAf8QixvyxTc9:-KJMetqdDEB54ByirD3l:901904630) ([raw file](https://github.com/cockroachdb/cockroach/blob/f225b3f5ae980b8d44c80aacd93eaa66b620b043/sql/parser/placeholders.go#L99)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> It should be specified here that we are aliasing the given map and not making a copy.
</details>
Done. Also added a comment to motivate.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983)*

**Comment by nvanbenschoten** [comment]
Reviewed 17 of 21 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 18 unresolved discussions, all commit checks successful.

---

*[server/admin.go, line 935 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJaQpFwF8u8ixefYS_U:-KJaQpFwF8u8ixefYS_V:-1548690030) ([raw file](https://github.com/cockroachdb/cockroach/blob/93fa0937e53fd656fac1cbe1bd29bca740f44c10/server/admin.go#L935)):*
> ```Go
> 	buf   bytes.Buffer
> 	pidx  int
> 	qargs *parser.PlaceholderInfo
> ```

Do we need the indirection here?

---

*[server/admin.go, line 996 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJaJRqHDaCfB6I21aDt:-KJaJRqHDaCfB6I21aDu:-470403090) ([raw file](https://github.com/cockroachdb/cockroach/blob/93fa0937e53fd656fac1cbe1bd29bca740f44c10/server/admin.go#L996)):*
> ```Go
> 			util.Errorf("# of placeholders %d != # of params %d", placeholders, len(params)))
> 	}
> 	for i := 0; i < placeholders; i++ {
> ```

`for i, param := range params {`is a little more idiomatic.

---

*[sql/executor.go, line 287 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJaJf2_3xVPlAzw4H9l:-KJaJf2_3xVPlAzw4H9m:400781043) ([raw file](https://github.com/cockroachdb/cockroach/blob/93fa0937e53fd656fac1cbe1bd29bca740f44c10/sql/executor.go#L287)):*
> ```Go
> // Prepare returns the result types of the given statement. pinfo may
> // contain partial type information for placeholders. Prepare will
> // populate the missing types The column result types are returned (or
> ```

`s/types The/types. The/`

---

*[sql/executor.go, line 289 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJaJoJDaSRg6j-XBiH0:-KJaJoJDaSRg6j-XBiH1:1567356340) ([raw file](https://github.com/cockroachdb/cockroach/blob/93fa0937e53fd656fac1cbe1bd29bca740f44c10/sql/executor.go#L289)):*
> ```Go
> // populate the missing types The column result types are returned (or
> // nil if there are no results).
> func (e *Executor) Prepare(ctx context.Context,
> ```

Can we fix these params?

---

*[sql/pgwire_test.go, line 283 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJaKID_H4WHeyCriTvf:-KJaKID_H4WHeyCriTvg:-1476523536) ([raw file](https://github.com/cockroachdb/cockroach/blob/93fa0937e53fd656fac1cbe1bd29bca740f44c10/sql/pgwire_test.go#L283)):*
> ```Go
> 			}
> 		} else if err.Error() != reason {
> 			t.Errorf(`%s: got: "%s", expected: "%s"`, query, err, reason)
> ```

`s/"%s"/%q/` in two places.

---

*[sql/planner.go, line 161 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJaKRMHwrF4iTCEAbLX:-KJaKRMHwrF4iTCEAbLY:-2116608979) ([raw file](https://github.com/cockroachdb/cockroach/blob/93fa0937e53fd656fac1cbe1bd29bca740f44c10/sql/planner.go#L161)):*
> ```Go
> // resetEvalContext (re-)initializes the structures
> // needed for expression handling.
> func (p *planner) resetEvalContext() {
> ```

Why rename this to `resetEvalContext`? It's not really correct, because we do more than just rest the evalContext.

---

*[sql/parser/placeholders.go, line 78 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJL7L0sOo46Ax79FTuO:-KJaJFaINJwIeuppKXle:-256423066) ([raw file](https://github.com/cockroachdb/cockroach/blob/f225b3f5ae980b8d44c80aacd93eaa66b620b043/sql/parser/placeholders.go#L78)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Done.
</details>
So we no longer need to return an `error`, right?

---

*[sql/parser/placeholders.go, line 34 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJaQCDUp02nYR7S8MgP:-KJaQCDUp02nYR7S8MgQ:880806526) ([raw file](https://github.com/cockroachdb/cockroach/blob/93fa0937e53fd656fac1cbe1bd29bca740f44c10/sql/parser/placeholders.go#L34)):*
> ```Go
> 
> // MakePlaceholderInfo constructs an empty PlaceholderInfo.
> func MakePlaceholderInfo() *PlaceholderInfo {
> ```

This should be `NewPlaceholderInfo`, because it's returning a pointer, not a value.

---

*[sql/parser/type_check.go, line 66 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJaPzjjoMqfSG7a7HIx:-KJaPzjjoMqfSG7a7HIy:1061919678) ([raw file](https://github.com/cockroachdb/cockroach/blob/93fa0937e53fd656fac1cbe1bd29bca740f44c10/sql/parser/type_check.go#L66)):*
> ```Go
> // expressions.
> func MakeSemaContext() SemaContext {
> 	return SemaContext{Placeholders: MakePlaceholderInfo()}
> ```

It would be nice if `Placeholders` was "nil-safe", so that we woudn't need this at all and a nil `SemaContext` could be used.

---

*[sql/pgwire/v3.go, line 345 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJaOs2p2rQ1N3GUC7gJ:-KJaOs2p2rQ1N3GUC7gK:-1046717539) ([raw file](https://github.com/cockroachdb/cockroach/blob/93fa0937e53fd656fac1cbe1bd29bca740f44c10/sql/pgwire/v3.go#L345)):*
> ```Go
> 	}
> 	// The client may provide type information for (some of) the
> 	// placeholders.  Read this first.
> ```

Extra space.

---

*[sql/pgwire/v3.go, line 560 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJaPBi-2g5wLWszqMuf:-KJaPBi-2g5wLWszqMug:-1056620116) ([raw file](https://github.com/cockroachdb/cockroach/blob/93fa0937e53fd656fac1cbe1bd29bca740f44c10/sql/pgwire/v3.go#L560)):*
> ```Go
> 		return c.sendInternalError(fmt.Sprintf("expected %d arguments, got %d", numQArgs, numValues))
> 	}
> 	qargs := make(parser.QueryArguments)
> ```

If you dont want to use `make` above, why use it here?

---

*[sql/sqlbase/table.go, line 1045 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJaPguadxzt0Yemkxk7:-KJaPgubP6Qof4TJQJEl:-1552738193) ([raw file](https://github.com/cockroachdb/cockroach/blob/93fa0937e53fd656fac1cbe1bd29bca740f44c10/sql/sqlbase/table.go#L1045)):*
> ```Go
> 	}
> 
> 	// Give a chance to the placeholder type first.
> ```

This comment doesnt make sense.

---

*[sql/sqlbase/table.go, line 1058 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJaPoz6yswZatJLfwew:-KJaPoz6yswZatJLfwex:1560259480) ([raw file](https://github.com/cockroachdb/cockroach/blob/93fa0937e53fd656fac1cbe1bd29bca740f44c10/sql/sqlbase/table.go#L1058)):*
> ```Go
> 		}
> 	}
> 	return err
> ```

Do we ever assign to `err`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 18 unresolved discussions, all commit checks successful.

---

*[server/admin.go, line 935 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJaQpFwF8u8ixefYS_U:-KJbCtp-w89tBKMvJnax:-1485391931) ([raw file](https://github.com/cockroachdb/cockroach/blob/93fa0937e53fd656fac1cbe1bd29bca740f44c10/server/admin.go#L935)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Do we need the indirection here?
</details>
It kinda does since that's what parser.MakePlaceholderInfo returns. Unless you have a better suggestion?

---

*[server/admin.go, line 996 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJaJRqHDaCfB6I21aDt:-KJbD4_I0ctoopngMMQy:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/93fa0937e53fd656fac1cbe1bd29bca740f44c10/server/admin.go#L996)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> `for i, param := range params {`is a little more idiomatic.
</details>
Done.

---

*[sql/executor.go, line 287 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJaJf2_3xVPlAzw4H9l:-KJbDA_1LmsXWqz0pOLg:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/93fa0937e53fd656fac1cbe1bd29bca740f44c10/sql/executor.go#L287)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> `s/types The/types. The/`
</details>
Done.

---

*[sql/executor.go, line 289 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJaJoJDaSRg6j-XBiH0:-KJbDG5rY0U984JTWJ4L:1090269266) ([raw file](https://github.com/cockroachdb/cockroach/blob/93fa0937e53fd656fac1cbe1bd29bca740f44c10/sql/executor.go#L289)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Can we fix these params?
</details>
Yes we can!

(nit: sometimes instructions are better phrased as such instead of as questions.)

---

*[sql/pgwire_test.go, line 283 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJaKID_H4WHeyCriTvf:-KJbOm87wvdpLWT6AAPP:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/93fa0937e53fd656fac1cbe1bd29bca740f44c10/sql/pgwire_test.go#L283)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> `s/"%s"/%q/` in two places.
</details>
Done.

---

*[sql/planner.go, line 161 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJaKRMHwrF4iTCEAbLX:-KJbOyPqVlJkYoiQq6qJ:762912396) ([raw file](https://github.com/cockroachdb/cockroach/blob/93fa0937e53fd656fac1cbe1bd29bca740f44c10/sql/planner.go#L161)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Why rename this to `resetEvalContext`? It's not really correct, because we do more than just rest the evalContext.
</details>
It's not renamed. resetForBatch still exists, see below. There's a  new function resetEvalContext added on top of that.

---

*[sql/parser/placeholders.go, line 78 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJL7L0sOo46Ax79FTuO:-KJbPfc2lzkDGwTCwc9l:1972386422) ([raw file](https://github.com/cockroachdb/cockroach/blob/f225b3f5ae980b8d44c80aacd93eaa66b620b043/sql/parser/placeholders.go#L78)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> So we no longer need to return an `error`, right?
</details>
Indeed. Fixed.

---

*[sql/parser/placeholders.go, line 34 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJaQCDUp02nYR7S8MgP:-KJbPDNQM9r_j1p2-snE:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/93fa0937e53fd656fac1cbe1bd29bca740f44c10/sql/parser/placeholders.go#L34)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> This should be `NewPlaceholderInfo`, because it's returning a pointer, not a value.
</details>
Done.

---

*[sql/parser/type_check.go, line 66 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJaPzjjoMqfSG7a7HIx:-KJbQiJ-5oMNrFj3Tt3l:1046285172) ([raw file](https://github.com/cockroachdb/cockroach/blob/93fa0937e53fd656fac1cbe1bd29bca740f44c10/sql/parser/type_check.go#L66)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> It would be nice if `Placeholders` was "nil-safe", so that we woudn't need this at all and a nil `SemaContext` could be used.
</details>
I'm not sure what you are referring to.
1) regarding whether PlaceholderInfo should be allocated on the heap and referred to by pointer in SemaContext. This is actually rather important: parser.semaCtx is being copied around in different places; whereas the references to PlaceholderInfo carried in the DPlaceholder object need to stay stable.

2) regarding whether we should be able to type placeholders without a PlaceholderInfo. This doesn't make sense: the types of placeholders are *only* stored in the PlaceholderInfo and thus you couldn't type the placeholders without one.

---

*[sql/pgwire/v3.go, line 345 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJaOs2p2rQ1N3GUC7gJ:-KJbQ0Q5XgvOwNkzoIG9:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/93fa0937e53fd656fac1cbe1bd29bca740f44c10/sql/pgwire/v3.go#L345)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Extra space.
</details>
Done.

---

*[sql/pgwire/v3.go, line 560 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJaPBi-2g5wLWszqMuf:-KJbQ5da4iNnjuyPhK9X:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/93fa0937e53fd656fac1cbe1bd29bca740f44c10/sql/pgwire/v3.go#L560)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> If you dont want to use `make` above, why use it here?
</details>
Done.

---

*[sql/sqlbase/table.go, line 1045 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJaPguadxzt0Yemkxk7:-KJbQJ5v6CMCNJsxBPAj:79276406) ([raw file](https://github.com/cockroachdb/cockroach/blob/93fa0937e53fd656fac1cbe1bd29bca740f44c10/sql/sqlbase/table.go#L1045)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> This comment doesnt make sense.
</details>
Fixed that.

---

*[sql/sqlbase/table.go, line 1058 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJaPoz6yswZatJLfwew:-KJbQZIVS30u6QsOCwD0:416376302) ([raw file](https://github.com/cockroachdb/cockroach/blob/93fa0937e53fd656fac1cbe1bd29bca740f44c10/sql/sqlbase/table.go#L1058)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Do we ever assign to `err`?
</details>
I guess not. Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983)*

**Comment by RaduBerinde** [comment]
:lgtm:

<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> #### sql: refactor the handling of query placeholders\.
> 
> This patch is mostly a clean-up of the code supporting SQL
> 
> placeholders:
> 
> 
> 
> - The placeholder map is now constructed directly in the pgwire
> 
>   driver, instead of being first stored in an array and then converted.
> 
> 
> 
> - As a result, the Args interface disappears.
> 
> 
> 
> - TypeCheck() now directly replaces a Placeholder with its assigned
> 
>   value (query argument) if any is supplied, so that FillArgs and the
> 
>   argVisitor are not required any more.
> 
> 
> 
> - As a result, the Expr objects in syntax trees now are immutable
> 
>   throughout a query execution and even across retries. This may
> 
>   obviate the need to test that the syntax tree hasn't changed by
> 
>   comparing its string representation before and after execution.
> 
> 
> 
> This changeset introduces no user-visible changes.
> 
> 
> 
> cc @RaduBerinde
> 
> 
> 
</details>


---

Review status: 11 of 21 files reviewed at latest revision, 13 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-:-KJbXG9N2fcM7SGIyMNH:1417088721)*

**Comment by nvanbenschoten** [comment]
Reviewed 1 of 10 files at r3.
Review status: 12 of 21 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/admin.go, line 935 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJaQpFwF8u8ixefYS_U:-KJg4DMVoHtiHDz8WKI7:1461067424) ([raw file](https://github.com/cockroachdb/cockroach/blob/93fa0937e53fd656fac1cbe1bd29bca740f44c10/server/admin.go#L935)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> It kinda does since that's what parser.MakePlaceholderInfo returns. Unless you have a better suggestion?
</details>
You could just use a value here and `Clear` the value in the `makeSQLQuery` constructor.

---

*[sql/planner.go, line 161 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJaKRMHwrF4iTCEAbLX:-KJg4qeSoqZfeNWqGRs9:706919045) ([raw file](https://github.com/cockroachdb/cockroach/blob/93fa0937e53fd656fac1cbe1bd29bca740f44c10/sql/planner.go#L161)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> It's not renamed. resetForBatch still exists, see below. There's a  new function resetEvalContext added on top of that.
</details>
But this is doing more than just resetting the eval context!

---

*[sql/parser/type_check.go, line 66 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJaPzjjoMqfSG7a7HIx:-KJg53y9R1tJk9X_7iVn:-1983808637) ([raw file](https://github.com/cockroachdb/cockroach/blob/93fa0937e53fd656fac1cbe1bd29bca740f44c10/sql/parser/type_check.go#L66)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> I'm not sure what you are referring to.
> 1) regarding whether PlaceholderInfo should be allocated on the heap and referred to by pointer in SemaContext. This is actually rather important: parser.semaCtx is being copied around in different places; whereas the references to PlaceholderInfo carried in the DPlaceholder object need to stay stable.
> 
> 2) regarding whether we should be able to type placeholders without a PlaceholderInfo. This doesn't make sense: the types of placeholders are *only* stored in the PlaceholderInfo and thus you couldn't type the placeholders without one.
</details>
My point is that if the `PlaceholderInfo` results are ignored, why create them in the first place? Just add methods that are no-ops if the reference is nil. Go stresses useful default values. This also allows us to save two allocations everywhere that this function (which probably shouldn't need to exist) is called.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983)*

**Comment by knz** [comment]
Review status: 9 of 21 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[server/admin.go, line 935 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJaQpFwF8u8ixefYS_U:-KJklJ5F5m5G5wwhNAa7:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/93fa0937e53fd656fac1cbe1bd29bca740f44c10/server/admin.go#L935)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> You could just use a value here and `Clear` the value in the `makeSQLQuery` constructor.
</details>
Done.

---

*[sql/planner.go, line 161 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJaKRMHwrF4iTCEAbLX:-KJkmAIxJCZfbcZBqkVr:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/93fa0937e53fd656fac1cbe1bd29bca740f44c10/sql/planner.go#L161)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> But this is doing more than just resetting the eval context!
</details>
Done.

---

*[sql/parser/type_check.go, line 66 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJaPzjjoMqfSG7a7HIx:-KJknFMEFO0rYX2LqCDW:-862307387) ([raw file](https://github.com/cockroachdb/cockroach/blob/93fa0937e53fd656fac1cbe1bd29bca740f44c10/sql/parser/type_check.go#L66)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> My point is that if the `PlaceholderInfo` results are ignored, why create them in the first place? Just add methods that are no-ops if the reference is nil. Go stresses useful default values. This also allows us to save two allocations everywhere that this function (which probably shouldn't need to exist) is called.
</details>
Where I'm coming from is that the number of cases where PlaceholderInfo results are ignored is smaller than the number of cases where it is not. Is it worth going through the conditional every time?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983)*

**Comment by knz** [comment]
Ok in the process of polishing this I made some additional refactorings which extend the scope of the commit slightly. Let me know if anything needs tweaking.

<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> :lgtm:
</details>


---

Review status: 8 of 31 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[sql/parser/type_check.go, line 66 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-KJaPzjjoMqfSG7a7HIx:-KJlbMlT7BCL933Va3_D:87094579) ([raw file](https://github.com/cockroachdb/cockroach/blob/93fa0937e53fd656fac1cbe1bd29bca740f44c10/sql/parser/type_check.go#L66)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Where I'm coming from is that the number of cases where PlaceholderInfo results are ignored is smaller than the number of cases where it is not. Is it worth going through the conditional every time?
</details>
Thanks for the explaination, this is now fixed/simplified.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-:-KJlbVjRUns6OAHJ-34Z:1313236009)*

**Comment by nvanbenschoten** [comment]
:lgtm:

<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Ok in the process of polishing this I made some additional refactorings which extend the scope of the commit slightly. Let me know if anything needs tweaking.
</details>


---

Reviewed 2 of 10 files at r3.
Review status: 6 of 32 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6983#-:-KJlzslk_Lc7jlV5d5vs:1417088721)*

**Pull request merged**
