### PR TITLE
Upgrading @cockroachlabs/cluster-ui for truncation update

### PR DESCRIPTION
**Pull request by nathanstilwell**
Upgraded @cockroachlabs/cluster-ui to version 0.1.46 to get updates in
how long text content (long queries and app names) are truncated in
tables and in menus.

Release note (ui change): Truncating long queries in tables

### CODE REVIEW

**Review by koorosh — APPROVED** [review]
LGTM!

**Comment by koorosh** [comment]
@nathanstilwell , just noticed, that your `yarn-vendored` [branch](https://github.com/cockroachdb/yarn-vendored/tree/nathanstilwell/upgrade-cluster-ui) isn't merged into `master`.

**Comment by nathanstilwell** [comment]
@koorosh Right. Thanks for the reminder.

**Comment by nathanstilwell** [comment]
bors retry

**Comment by awoods187** [comment]
Does this require a version bump? I don't think I can see it on master. Can we merge it in there and or provide some screen shots/a build to review? I'd like to test this out.

**Pull request merged**
