### PR TITLE
roachtest: remove tags

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change retires the roachtest tags in favor of the `--cloud`,
`--suite`, `--owner` flags.

We provide some basic backward compatibility: if we encounter a single
tag which matches a suite, we convert it to a suite.  There is really
one case we care about: a `tag:release_qualification` used by a
TeamCity build.

Epic: none
Release note: None

### CODE REVIEW

**Review by herkolategan — APPROVED** [review]
Thanks, this will certainly make things much less ambiguous going forward! Had a look through, and everything seems in order to me, but a second pair of eyes might be handy in case I missed anything. A small `roachtest` TC run might be worth it for a sanity check.

> Reviewed 66 of 66 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115391#-:-NlOSjLQ77GfWF5k3Yjz:b-sda0xn)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde, @renatolabs, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/disagg_rebalance.go` line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115391#-NlORwY59idjZarkDmcw:-NlORwY62gbpiFWFSPLp:b-s956nv) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bffc8fa884a8c2768bc3462ab0bd861c3bf011f/pkg/cmd/roachtest/tests/disagg_rebalance.go#L41)):*
> ```Go
> 		Timeout:           1 * time.Hour,
> 		Run: func(ctx context.Context, t test.Test, c cluster.Cluster) {
> 			if c.Cloud() != spec.AWS {
> ```

Just noting for reference: https://github.com/cockroachdb/cockroach/pull/115997/files
@dt Patched up the tags/clouds vs. skip here.

**Comment by RaduBerinde** [comment]
*[`pkg/cmd/roachtest/tests/disagg_rebalance.go` line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115391#-NlORwY59idjZarkDmcw:-NlOWEGP6QkUtW1r63Hx:b-6ixhnn) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bffc8fa884a8c2768bc3462ab0bd861c3bf011f/pkg/cmd/roachtest/tests/disagg_rebalance.go#L41)):*
<details><summary><i>Previously, herkolategan (Herko Lategan) wrote…</i></summary><blockquote>

Just noting for reference: https://github.com/cockroachdb/cockroach/pull/115997/files
@dt Patched up the tags/clouds vs. skip here.
</blockquote></details>

@dt I think your change will be much simplified if you rebase on top of this. But if you want to merge ASAP I can wait and clean things up after.

**Review by srosenberg — APPROVED** [review]
Thanks and good riddance!

:lgtm:

> Reviewed 66 of 66 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115391#-:-NlOdjPS0jnlFZPS0uDY:bvb7v8f)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dt and @renatolabs)

**Pull request merged**
