### PR TITLE
sql: fix a race with finishing a span and executing RPCs

### LINKED ISSUE #92809: logictest: setup-flow-async span is used after finish
pkg/ccl/logictestccl/tests/fakedist/fakedist_test.TestCCLLogic_new_schema_changer [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/7784384?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/7784384?buildTab=artifacts#/) on master @ [db71e045cc3f2937bf20170d254dd7e54a620ffb](https://github.com/cockroachdb/cockroach/commits/db71e045cc3f2937bf20170d254dd7e54a620ffb):

```
*   -- stack trace:
*   | runtime.gopanic
*   | 	GOROOT/src/runtime/panic.go:884
*   | github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).detectUseAfterFinish
*   | 	github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:181
*   | github.com/cockroachdb/cockroach/pkg/util/tracing.WithParent
*   | 	github.com/cockroachdb/cockroach/pkg/util/tracing/span_options.go:204
*   | github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor.ClientInterceptor.func2
*   | 	github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go:234
*   | google.golang.org/grpc.(*ClientConn).Invoke
*   | 	google.golang.org/grpc/external/org_golang_google_grpc/call.go:35
*   | github.com/cockroachdb/cockroach/pkg/sql/execinfrapb.(*distSQLClient).SetupFlow
*   | 	github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/bazel-out/k8-fastbuild/bin/pkg/sql/execinfrapb/execinfrapb_go_proto_/github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/api.pb.go:499
*   | github.com/cockroachdb/cockroach/pkg/sql.runnerRequest.run
*   | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:114
*   | github.com/cockroachdb/cockroach/pkg/sql.(*runnerCoordinator).init.func1
*   | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:149
*   | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
*   | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470
*   | runtime.goexit
*   | 	GOROOT/src/runtime/asm_amd64.s:1594
* Wraps: (2) panic: use of Span after Finish. Span: setup-flow-async. Finish previously called at: <stack not captured. Set debugUseAfterFinish>
* Error types: (1) *withstack.withStack (2) *errutil.leafError
*
panic: use of Span after Finish. Span: setup-flow-async. Finish previously called at: <stack not captured. Set debugUseAfterFinish> [recovered]
	panic: use of Span after Finish. Span: setup-flow-async. Finish previously called at: <stack not captured. Set debugUseAfterFinish>

goroutine 30 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).recover(0xc0012649f8?, {0x699cfc8, 0xc000c64840})
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:229 +0x6a
panic({0x4b2c1e0, 0xc005ff78d0})
	GOROOT/src/runtime/panic.go:884 +0x212
github.com/cockroachdb/cockroach/pkg/util/tracing.(*Span).detectUseAfterFinish(0x99ea708?)
	github.com/cockroachdb/cockroach/pkg/util/tracing/span.go:181 +0x12b
github.com/cockroachdb/cockroach/pkg/util/tracing.WithParent(0xc007780800)
	github.com/cockroachdb/cockroach/pkg/util/tracing/span_options.go:204 +0x27
github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor.ClientInterceptor.func2({0x699cfc8, 0xc009059470}, {0x558b096, 0x2b}, {0x52a9240, 0xc00740de00}, {0x52a9380, 0xc00bbccfc0}, 0xc009059470?, 0x57f47a0, ...)
	github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go:234 +0x10b
google.golang.org/grpc.(*ClientConn).Invoke(0xc008ca6ff8?, {0x699cfc8?, 0xc009059470?}, {0x558b096?, 0x0?}, {0x52a9240?, 0xc00740de00?}, {0x52a9380?, 0xc00bbccfc0?}, {0x0, ...})
	google.golang.org/grpc/external/org_golang_google_grpc/call.go:35 +0x223
github.com/cockroachdb/cockroach/pkg/sql/execinfrapb.(*distSQLClient).SetupFlow(0xc001264e00, {0x699cfc8, 0xc009059470}, 0xc001264e8c?, {0x0, 0x0, 0x0})
	github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/bazel-out/k8-fastbuild/bin/pkg/sql/execinfrapb/execinfrapb_go_proto_/github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/api.pb.go:499 +0xc9
github.com/cockroachdb/cockroach/pkg/sql.runnerRequest.run({{0x699cfc8, 0xc009059470}, 0xc000c17580, 0xc00740de00, 0x3, 0xc005a95f20})
	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:114 +0x10e
github.com/cockroachdb/cockroach/pkg/sql.(*runnerCoordinator).init.func1({0xc001174800, 0xc000607fa8})
	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:149 +0x8f
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470 +0x146
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:461 +0x43b
```
<p>Parameters: <code>TAGS=bazel,gss</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestCCLLogic_new_schema_changer.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-21980

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit fixes a race that was introduced when we fully parallelized the execution of the setup of the remote flows. In particular, it became possible for a `setup-flow-async` "runner" tracing span be finished before a concurrent `SetupFlow` RPC is issued, which uses that span as a parent for the RPC span. The issue is only present in the case that we didn't spin up a "listener" goroutine for whatever reason (most likely because the server is quescing), in which case we didn't block to wait for the concurrent RPCs to be evaluated. We canceled the context of those RPCs, but it appears that the context cancellation is not immediately noticed by the RPC call (or at least it is noticed _after_ the gRPC interceptor code attempt to create a new tracing span). This is now fixed by blocking the cleanup until all concurrently-issued RPCs are completed.

Fixes: #92809.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
On one of the logic tests, I reproduced the problem in 4 minutes before this patch and got no failures with the patch in 55 minutes.

**Review by msirek — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95482)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @yuzefovich)

___
*[`pkg/sql/distsql_running.go` line 519 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95482#-NM7-N2AAtMuOWox56Yl:-NM7-N2AAtMuOWox56Ym:b8l9mmb) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bde78b68513c8ffa89d3bb65ba61da57ac598ce/pkg/sql/distsql_running.go#L519)):*
> ```Go
> 			// send on the result channel.
> 			for i := 0; i < numAsyncRequests+numSerialRequests; i++ {
> 				<-resultChan
> ```

If `runnerRequest.run` encounters a fatal error, might a send to the channel get missed causing us to block indefinitely here? Perhaps using `defer` in `runnerRequest.run` could ensure we always send on the channel.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95482)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @msirek)

___
*[`pkg/sql/distsql_running.go` line 519 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95482#-NM7-N2AAtMuOWox56Yl:-NM70L2D6ckzd28FzJKh:b-uxf2ey) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bde78b68513c8ffa89d3bb65ba61da57ac598ce/pkg/sql/distsql_running.go#L519)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

If `runnerRequest.run` encounters a fatal error, might a send to the channel get missed causing us to block indefinitely here? Perhaps using `defer` in `runnerRequest.run` could ensure we always send on the channel.
</blockquote></details>

If that runner goroutine encounters a fatal crash, then the whole process will crash, and it doesn't matter whether we'd block here or not.

I do see that `defer`ring a send on the result channel in `runnerRequest.run` would make that code slightly easier to follow (i.e. it'll be more clear that under all circumstances (modulo a panic) a single object is sent on the results channel), so I could make the corresponding change if you think it's worth it. This would result in an additional function allocation though, but it's probably not that important, and personally I'm ok with either option.

**Review by msirek — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95482#-:-NM73N6M0e7WlCbAmtZd:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @yuzefovich)

___
*[`pkg/sql/distsql_running.go` line 519 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95482#-NM7-N2AAtMuOWox56Yl:-NM71vym88U6J9-ln1Bl:b-6lx2pa) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bde78b68513c8ffa89d3bb65ba61da57ac598ce/pkg/sql/distsql_running.go#L519)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

If that runner goroutine encounters a fatal crash, then the whole process will crash, and it doesn't matter whether we'd block here or not.

I do see that `defer`ring a send on the result channel in `runnerRequest.run` would make that code slightly easier to follow (i.e. it'll be more clear that under all circumstances (modulo a panic) a single object is sent on the results channel), so I could make the corresponding change if you think it's worth it. This would result in an additional function allocation though, but it's probably not that important, and personally I'm ok with either option.
</blockquote></details>

Oh, if the whole process crashes (when there's a panic), then maybe there's no point to use `defer`. Thanks for clarifying. Maybe there is potential for future improvement by adding a panic catcher.

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95482#-:-NM74mSq0eH0lOEW8eXg:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @msirek)

___
*[`pkg/sql/distsql_running.go` line 519 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95482#-NM7-N2AAtMuOWox56Yl:-NM74FGiDETRmajD94M3:b-b9anc6) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bde78b68513c8ffa89d3bb65ba61da57ac598ce/pkg/sql/distsql_running.go#L519)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Oh, if the whole process crashes (when there's a panic), then maybe there's no point to use `defer`. Thanks for clarifying. Maybe there is potential for future improvement by adding a panic catcher.
</blockquote></details>

In this case a panic-catcher doesn't seem worth it - `runnerRequest.run` seems so simple that if we do hit a panic for some reason I can't really imagine (without any code modifications), then something has gone truly wrong, and it might actually be better to crash. FWIW this code hasn't really been changed in over 5 years, so it should be pretty safe :)

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95482)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @yuzefovich)

___
*[`pkg/sql/distsql_running.go` line 519 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95482#-NM7-N2AAtMuOWox56Yl:-NM756H8AR2O6I7wh6Eo:b-hfk55u) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bde78b68513c8ffa89d3bb65ba61da57ac598ce/pkg/sql/distsql_running.go#L519)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

In this case a panic-catcher doesn't seem worth it - `runnerRequest.run` seems so simple that if we do hit a panic for some reason I can't really imagine (without any code modifications), then something has gone truly wrong, and it might actually be better to crash. FWIW this code hasn't really been changed in over 5 years, so it should be pretty safe :)
</blockquote></details>

OK, thanks

**Comment by yuzefovich** [comment]
It appears that several recent bors runs failed due to this flake, bumping the priority.

bors r+ p=999

**Review by andreimatei — COMMENTED** [review]
:lgtm: but please go through my comments

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95482#-:-NM9gVCYBP_hQ38PJ_jK:bnd4jbx)* status: :shipit: complete! 2 of 0 LGTMs obtained

___
*[`pkg/sql/distsql_running.go` line 469 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95482#-NM9bMIuCgGQyNMEmO4D:-NM9bMIuCgGQyNMEmO4E:b-py2pc5) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bde78b68513c8ffa89d3bb65ba61da57ac598ce/pkg/sql/distsql_running.go#L469)):*
> ```Go
> 	// numAsyncRequests tracks the number of the SetupFlow RPCs that were
> 	// delegated to the DistSQL runner goroutines.
> 	var numAsyncRequests int
> ```

We only seem to use the sum of these new variables; do we need to introduce them?
Particularly since one of the code paths seems to refer to the sum as `len(flows)-1`.

I would also consider trying to use a higher-level structure for managing the fanout, like an error group (perhaps by replacing `runnerRequest.resultChan` with a callback). That would remove the need to keep the producer and consumers in sync with respect to the number of requests, and would probably also make the error deduplication code nicer.
___
*[`pkg/sql/distsql_running.go` line 519 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95482#-NM7-N2AAtMuOWox56Yl:-NM9ekSE9Tm2xFr54D3Y:b6qrqli) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bde78b68513c8ffa89d3bb65ba61da57ac598ce/pkg/sql/distsql_running.go#L519)):*
> If that runner goroutine encounters a fatal crash, then the whole process will crash, and it doesn't matter whether we'd block here or not.

Not in the synchronous call case. In that case, if there were such a panic, I think we would end up deadlocking on the unwind path (right?).
It's not a huge deal in my book, but since that function already uses a defer, it'd be good to also deal with the channel in a defer. I don't think it'd be an extra allocation (or at least I hope it wouldn't). I think most allocations from deferred went away many compiler versions ago.
This discussion would be moot with an errorGroup.

> > Maybe there is potential for future improvement by adding a panic catcher.

> In this case a panic-catcher doesn't seem worth it - runnerRequest.run seems so simple that if we do hit a panic for some reason I can't really imagine (without any code modifications), then something has gone truly wrong, and it might actually be better to crash.

This is always the case, in my opinion. Recovering from panics (i.e. recovering without re-panicking) is a fool's game.
___
*[`pkg/sql/distsql_running.go` line 557 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95482#-NM9da6BEDWJo_mYOyDf:-NM9da6C4aBGJEga1pq6:b-16ih0w) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bde78b68513c8ffa89d3bb65ba61da57ac598ce/pkg/sql/distsql_running.go#L557)):*
> ```Go
> 		}
> 	}
> 	if buildutil.CrdbTestBuild {
> ```

Why is this a test-only assertion? The check is cheap (particularly if you make copies of the printed variables inside the check block to prevent the originals from escaping).
In my opinion, making checks test only should only be done when there's a specific reason to do so because the extra `if` for test check is generally not worth having. But in this specific case, in addition, if the assertion fails, then we'll probably deadlock something, which is probably worse than the crash you're trying to avoid.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95482)* status: :shipit: complete! 2 of 0 LGTMs obtained

___
*[`pkg/sql/distsql_running.go` line 469 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95482#-NM9bMIuCgGQyNMEmO4D:-NMA4DSwBLuOlqGTGQ-V:b-b1j7d4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bde78b68513c8ffa89d3bb65ba61da57ac598ce/pkg/sql/distsql_running.go#L469)):*
We need two pieces of information: the total number of RPCs issued (which can be smaller than `len(flows)-1` when a synchronous RPC call results in an error), and whether we issued at least one RPC asynchronously by the DistSQL worker (in which case we must spin up a new "listener" goroutine). This can be achieved by having two `int`s or an `int` and a `bool`. Perhaps, the latter option is cleaner, I'll open up a PR.

> Particularly since one of the code paths seems to refer to the sum as `len(flows)-1`.

That code path is only reached if no error was encountered on a synchronous RPC call, in which case sum of these variables always equals `len(flows)-1`.

> I would also consider trying to use a higher-level structure for managing the fanout, like an error group

IIUC correctly `errgroup.Group` would be able to spin up new goroutines on demand in order to issue RPCs asynchronously. However, this is not the behavior that we want (or at least currently expect) - we already have a pool of DistSQL worker goroutines (with 4 x vCPUs number of goroutines by default) that are shared and reused across all queries in the node, and it'd likely be worse to always spin up new goroutines just to issue a single RPC. Am I missing something about the error group? Let's continue this discussion on a new PR I'm about to open.
___
*[`pkg/sql/distsql_running.go` line 519 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95482#-NM7-N2AAtMuOWox56Yl:-NMA72tl138HgSHYFByj:b-trx3j8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bde78b68513c8ffa89d3bb65ba61da57ac598ce/pkg/sql/distsql_running.go#L519)):*
> Not in the synchronous call case. In that case, if there were such a panic, I think we would end up deadlocking on the unwind path (right?).

Yeah, you're right. I'll adjust it to use the defer.

> Recovering from panics (i.e. recovering without re-panicking) is a fool's game.

Unless you're using panic-catching mechanism of error propagation (which we do in the vectorized execution engine and in the optimizer). It's a separate discussion whether such pattern is a good one, but I believe on SQL Queries team we like it (e.g. in the vectorized engine it significantly improved the stability of the system by converting crashes into internal errors).
___
*[`pkg/sql/distsql_running.go` line 557 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95482#-NM9da6BEDWJo_mYOyDf:-NMA7wi6A0ORUm8Ggeib:bm9zn5v) ([raw file](https://github.com/cockroachdb/cockroach/blob/4bde78b68513c8ffa89d3bb65ba61da57ac598ce/pkg/sql/distsql_running.go#L557)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Why is this a test-only assertion? The check is cheap (particularly if you make copies of the printed variables inside the check block to prevent the originals from escaping).
In my opinion, making checks test only should only be done when there's a specific reason to do so because the extra `if` for test check is generally not worth having. But in this specific case, in addition, if the assertion fails, then we'll probably deadlock something, which is probably worse than the crash you're trying to avoid.
</blockquote></details>

I'll just remove this assertion since it's probably not that useful. I don't believe we'd deadlock if this assertion fired though, quite the opposite - it could prevent a deadlock, or at least leaking a goroutine (if we issued less requests than `len(flows)-1`, then the listener goroutine would never exit).

**Pull request merged**
