### PR TITLE
settings/cluster: clarify some version godocs

### PR DESCRIPTION
**Pull request by benesch**
(Hopefully) improve the clarity of godoc comments in the cluster version
implementation.

Release note: None

### CODE REVIEW

**Comment by tschottdorf** [comment]
Thanks! And, are you actually using godoc to look at comments? I'm sure it's a painful experience (since we have done zero polish on it).

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/settings/cluster/cockroach_versions.go, line 86 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20633#-L06aV7zAX_dyrWmgqZP:-L06aV7zAX_dyrWmgqZQ:b-gjwpu4) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdee0318b82a8ee5c1c57019ca614c6c724837e0/pkg/settings/cluster/cockroach_versions.go#L86)):*
> ```Go
> 	{
> 		// Version1_1 is CockroachDB v1.1. It remains unchanged for all v1.1.x
> 		// releases unless we need to introduce a new migration.
> ```

This somewhat contradicts the comment that we couldn't actually introduce migrations in patch releases (which we could, but we'd have to verify that it's a safe one). I think this is safe to remove.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20633#-:-L06adbaVBSgO7oxjc-f:b69biw1)*

**Comment by benesch** [comment]
TFTR!

I only look at godoc infrequently—though I think @mjibson actually uses it daily—but you'd be surprised how pleasant it actually is even without any polish. In this case though I was just using "godoc" as shorthand for "documentation comments".

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/settings/cluster/cockroach_versions.go, line 86 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20633#-L06aV7zAX_dyrWmgqZP:-L0AL9RZPHQGsYPpwfJA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdee0318b82a8ee5c1c57019ca614c6c724837e0/pkg/settings/cluster/cockroach_versions.go#L86)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

This somewhat contradicts the comment that we couldn't actually introduce migrations in patch releases (which we could, but we'd have to verify that it's a safe one). I think this is safe to remove.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20633#-:-L0AL8GuJ-Wi7l_ou2oo:b-m6ozzo)*

**Comment by mjibson** [comment]
Yes, I always program with godoc open in a window. I don't understand how everyone else works without it. But having nicely formatted godoc comments is really nice.

**Comment by benesch** [comment]
@tschottdorf is that an LGTM? :)

**Review by tbg — APPROVED** [review]
Yep, sorry!

**Pull request merged**
