### PR TITLE
sql: enable client to override index selection for DELETE and UPDATE

### PR DESCRIPTION
**Pull request by knz**
Informs #30734.

Prior to this patch, if the automatic index selection for DELETE or
UPDATE was inadequate, there was no way to override it like it is
possible for SELECT/INSERT/UPSERT.

This patch fixes this by extending and supporting the syntax for
DELETE and UPDATE:

```
DELETE FROM tbl@idx ...
UPDATE tbl@idx SET ...
```

Release note (sql change): it is now possible to force a specific
index for DELETE or UPDATE.

### CODE REVIEW

**Comment by knz** [comment]
@awoods187 this PR is meant to enable the workaround hinted in https://github.com/cockroachdb/cockroach/issues/30734#issuecomment-427411654

This PR is also sufficiently simple that we can back-port it to both 2.0 and 2.1.

Can you check whether the customer finds this adequate?

**Comment by awoods187** [comment]
Asked the customer and am awaiting the response

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

Thanks for adding this workaround!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31012#-:-LOFap6S6VmMlLdrA53s:b9wdaw3)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by BramGruneir — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31012#-:-LOJlZt14wo-yyq-fdwP:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Comment by knz** [comment]
Thanks for your reviews!

However I'll hold off merging this until we get a confirmation from the user that the approach is adequate for their needs.

**Comment by BramGruneir** [comment]
I still think you should merge this.  It's sensible to allow overrides the the index selection.

**Comment by knz** [comment]
Yeah but it's a feature extension, and so late in the release cycle it would not be appropriate for a gratuitous backport. Then:

- if we don't backport it into 2.1, then I think this PR should not be merged as-is and instead we should wait for later 2.2 work on plan hints. Maybe the syntax designed for that roadmap item will be better.

- to force a backport into 2.1 (and possibly 2.0) we need a strong customer case. This is what I am requesting.

**Comment by awoods187** [comment]
While it would be nice to get customer confirmation, I think we should go ahead and do this. Even if we decide to implement a different hint syntax in the future this can still be valuable to customers now.

**Comment by knz** [comment]
All right, let's do this.

bors r+

**Pull request merged**
