### PR TITLE
rfc: token-based authentication for SQL session revival

### PR DESCRIPTION
**Pull request by rafiss**
Release note: None

### CODE REVIEW

**Review by jaylim-crl — COMMENTED** [review]
This mostly :lgtm: since we've already discussed all the concerns on the initial Google Docs draft.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74640#-:-Mt4QGDK8D_evRmPL7Xs:b-9qduyo)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm, @catj-cockroach, @knz, and @rafiss)

___
*[docs/RFCS/20211203_session_revival_token.md, line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74640#-Mt4Od5t8ORJ611DPNVL:-Mt4Od5t8ORJ611DPNVM:b1pj2rt) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cb13b7412598450a214d7565677b1d91f51e10f/docs/RFCS/20211203_session_revival_token.md#L92)):*
> ```Markdown
> #### Update pgwire code to look out for the new token
> 
> We will add a CockroachDB-specific “StartupMessage” in the [pgwire/server.go](https://github.com/cockroachdb/cockroach/blob/b4ab627436afd8d9ed23330cd4026aa435b5b65d/pkg/sql/pgwire/server.go#L731) code. We’ll name it **<code>session_revival_token</code></strong>.
> ```

nit: formatting error here



_Code quote:_
```Markdown
We’ll name it **<code>session_revival_token</code></strong>
```
___
*[docs/RFCS/20211203_session_revival_token.md, line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74640#-Mt4OvWOA7eI-vLBggGf:-Mt4OvWOA7eI-vLBggGg:btcmhjv) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cb13b7412598450a214d7565677b1d91f51e10f/docs/RFCS/20211203_session_revival_token.md#L102)):*
> ```Markdown
> 
> 
> #### In order to sign the token, we will introduce a new signing key (either [Ed25519](https://pkg.go.dev/crypto/ed25519) or RSA depending on what the Intrusion team decides) that is unique per tenant, and is shared by all SQL nodes of the same tenant. The advantage of Ed25519 is that it is fast and generates small signatures. The signing key will be generated by the Vault. Unlike the existing tenant-client cert, this new signing cert doesn't require any DNS or IP information baked into the certificate and the certificate can be self-signed. This makes it easier to rotate if a tenant pod becomes compromised. When creating a tenant SQL node, Intrusion will need to put the key into the `certs-dir` of the SQL node (similar to how the tenant certs are added now). The cert will be named `tenant-signing.&lt;ID>.key`. The `crdb_internal.create_session_token` function will fail if this key is not present, and the token creation will be able to detect the algorithm used by the cert and call the according signature methods. A `cockroach mt cert create-tenant-signing` command will be added for testing purposes.
> ```

nit: formatting error. Don't think the `####` is intentional
___
*[docs/RFCS/20211203_session_revival_token.md, line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74640#-Mt4PUdD6OQfiOPeP0F6:-Mt4PUdD6OQfiOPeP0F7:b-pyku8m) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cb13b7412598450a214d7565677b1d91f51e10f/docs/RFCS/20211203_session_revival_token.md#L102)):*
> ```Markdown
> 
> 
> #### In order to sign the token, we will introduce a new signing key (either [Ed25519](https://pkg.go.dev/crypto/ed25519) or RSA depending on what the Intrusion team decides) that is unique per tenant, and is shared by all SQL nodes of the same tenant. The advantage of Ed25519 is that it is fast and generates small signatures. The signing key will be generated by the Vault. Unlike the existing tenant-client cert, this new signing cert doesn't require any DNS or IP information baked into the certificate and the certificate can be self-signed. This makes it easier to rotate if a tenant pod becomes compromised. When creating a tenant SQL node, Intrusion will need to put the key into the `certs-dir` of the SQL node (similar to how the tenant certs are added now). The cert will be named `tenant-signing.&lt;ID>.key`. The `crdb_internal.create_session_token` function will fail if this key is not present, and the token creation will be able to detect the algorithm used by the cert and call the according signature methods. A `cockroach mt cert create-tenant-signing` command will be added for testing purposes.
> ```

nit: tenant-signing.<ID>.key



_Code quote:_
```Markdown
tenant-signing.&lt;ID>.key
```
___
*[docs/RFCS/20211203_session_revival_token.md, line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74640#-Mt4PfyJ5xqyQoGQH2mj:-Mt4PfyJ5xqyQoGQH2mk:b493dkj) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cb13b7412598450a214d7565677b1d91f51e10f/docs/RFCS/20211203_session_revival_token.md#L116)):*
> ```Markdown
> #### Configuration in the sqlServer
> 
> Since the mechanism should only be available in CRDB-Serverless deployments, we will make it configurable so that it is not enabled by default on dedicated or self-hosted clusters. A new field will be added to `sqlServerArgs` named **<code>sessionRevivalTokenEnabled</code></strong> which defaults to false, and it will control if the SQL node looks for the <strong><code>session_revival_token</code></strong> parameter. The field will be set to true only in the <code>server.StartTenant</code> function, so the functionality only is enabled in multitenant clusters.
> ```

nit: Not sure if the ** is intentional



_Code quote:_
```Markdown
**<code>sessionRevivalTokenEnabled</code></strong>
```

**Review by knz — APPROVED** [review]
:lgtm: modulo the formatting fixes

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74640#-:-Mt4UXoa1TVGgoNA_fIj:b8zopde)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @ajstorm, @catj-cockroach, and @rafiss)

___
*[docs/RFCS/20211203_session_revival_token.md, line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74640#-Mt4U32wBkW-4UC-80q9:-Mt4U32wBkW-4UC-80qA:bc0uo51) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cb13b7412598450a214d7565677b1d91f51e10f/docs/RFCS/20211203_session_revival_token.md#L5)):*
> ```Markdown
> - Start Date: 2021-12-03
> - Authors: Rafi Shamim
> - RFC PR: (PR # after acceptance of initial draft)
> ```

you can update the metadata now
___
*[docs/RFCS/20211203_session_revival_token.md, line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74640#-Mt4U4rt1dhRLsbS-D2r:-Mt4U4rt1dhRLsbS-D2s:biitap4) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cb13b7412598450a214d7565677b1d91f51e10f/docs/RFCS/20211203_session_revival_token.md#L6)):*
> ```Markdown
> - Authors: Rafi Shamim
> - RFC PR: (PR # after acceptance of initial draft)
> - Cockroach Issue: (one or more # from the issue tracker)
> ```

we need to file an issue retroactively in order to have a tracking item in milestones
___
*[docs/RFCS/20211203_session_revival_token.md, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74640#-Mt4ULv_97ptIosZniWd:-Mt4ULv_97ptIosZniWe:bvwreei) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cb13b7412598450a214d7565677b1d91f51e10f/docs/RFCS/20211203_session_revival_token.md#L94)):*
> ```Markdown
> We will add a CockroachDB-specific “StartupMessage” in the [pgwire/server.go](https://github.com/cockroachdb/cockroach/blob/b4ab627436afd8d9ed23330cd4026aa435b5b65d/pkg/sql/pgwire/server.go#L731) code. We’ll name it **<code>session_revival_token</code></strong>.
> 
> Before reaching the password authentication code, the server will see the token, and if it’s valid, will bypass the regular session initialization and [authentication code](https://github.com/cockroachdb/cockroach/blob/b4ab627436afd8d9ed23330cd4026aa435b5b65d/pkg/sql/pgwire/auth_methods.go#L40).
> ```

are you sure about this line reference?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74640)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @ajstorm, @catj-cockroach, and @knz)

___
*[docs/RFCS/20211203_session_revival_token.md, line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74640#-Mt4U32wBkW-4UC-80q9:-Mt4YmOp2xPQ4dObsyn6:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cb13b7412598450a214d7565677b1d91f51e10f/docs/RFCS/20211203_session_revival_token.md#L5)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

you can update the metadata now
</blockquote></details>

done
___
*[docs/RFCS/20211203_session_revival_token.md, line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74640#-Mt4U4rt1dhRLsbS-D2r:-Mt4YjZK5fHIVeMpoQXG:b-op7po8) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cb13b7412598450a214d7565677b1d91f51e10f/docs/RFCS/20211203_session_revival_token.md#L6)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

we need to file an issue retroactively in order to have a tracking item in milestones
</blockquote></details>

for sure. filed https://github.com/cockroachdb/cockroach/issues/74643
___
*[docs/RFCS/20211203_session_revival_token.md, line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74640#-Mt4Od5t8ORJ611DPNVL:-Mt4ZQWT-ANYfddxCMpy:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cb13b7412598450a214d7565677b1d91f51e10f/docs/RFCS/20211203_session_revival_token.md#L92)):*
<details><summary><i>Previously, jaylim-crl (Jay Lim) wrote…</i></summary><blockquote>

nit: formatting error here
</blockquote></details>

done
___
*[docs/RFCS/20211203_session_revival_token.md, line 94 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74640#-Mt4ULv_97ptIosZniWd:-Mt4a8015OdVxgQbzHtj:b-rlsp3x) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cb13b7412598450a214d7565677b1d91f51e10f/docs/RFCS/20211203_session_revival_token.md#L94)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

are you sure about this line reference?
</blockquote></details>

nice catch, fixed
___
*[docs/RFCS/20211203_session_revival_token.md, line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74640#-Mt4OvWOA7eI-vLBggGf:-Mt4aMh9E1E7Qph1I7KO:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cb13b7412598450a214d7565677b1d91f51e10f/docs/RFCS/20211203_session_revival_token.md#L102)):*
<details><summary><i>Previously, jaylim-crl (Jay Lim) wrote…</i></summary><blockquote>

nit: formatting error. Don't think the `####` is intentional
</blockquote></details>

done
___
*[docs/RFCS/20211203_session_revival_token.md, line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74640#-Mt4PUdD6OQfiOPeP0F6:-Mt4aSHuC0dwh3ZXWcy-:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cb13b7412598450a214d7565677b1d91f51e10f/docs/RFCS/20211203_session_revival_token.md#L102)):*
<details><summary><i>Previously, jaylim-crl (Jay Lim) wrote…</i></summary><blockquote>

nit: tenant-signing.<ID>.key
</blockquote></details>

done
___
*[docs/RFCS/20211203_session_revival_token.md, line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74640#-Mt4PfyJ5xqyQoGQH2mj:-Mt4aXUE4X99yOxt4MIE:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6cb13b7412598450a214d7565677b1d91f51e10f/docs/RFCS/20211203_session_revival_token.md#L116)):*
<details><summary><i>Previously, jaylim-crl (Jay Lim) wrote…</i></summary><blockquote>

nit: Not sure if the ** is intentional
</blockquote></details>

done

**Review by jaylim-crl — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74640#-:-Mt4g2z56kJ_fr8G32eQ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ajstorm, @catj-cockroach, @knz, and @rafiss)

___
*[docs/RFCS/20211203_session_revival_token.md, line 102 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74640#-Mt4fh5GEUAOOMmHpZRI:-Mt4fh5GEUAOOMmHpZRJ:b-acugsq) ([raw file](https://github.com/cockroachdb/cockroach/blob/54efd4b0b6263402846e4ab79f4aa6058a51f53e/docs/RFCS/20211203_session_revival_token.md#L102)):*
> ```Markdown
> 
> 
> In order to sign the token, we will introduce a new signing key (either [Ed25519](https://pkg.go.dev/crypto/ed25519) or RSA depending on what the Intrusion team decides) that is unique per tenant, and is shared by all SQL nodes of the same tenant. The advantage of Ed25519 is that it is fast and generates small signatures. The signing key will be generated by the Vault. Unlike the existing tenant-client cert, this new signing cert doesn't require any DNS or IP information baked into the certificate and the certificate can be self-signed. This makes it easier to rotate if a tenant pod becomes compromised. When creating a tenant SQL node, Intrusion will need to put the key into the `certs-dir` of the SQL node (similar to how the tenant certs are added now). The cert will be named `tenant-signing.<ID>.key`. The `crdb_internal.create_session_token` function will fail if this key is not present, and the token creation will be able to detect the algorithm used by the cert and call the according signature methods. A `cockroach mt cert create-tenant-signing` command will be added for testing purposes.
> ```

Just talked to @catj-cockroach, it's likely that we'll be using a self-signed cert here. Could we make this phrase generic so that we don't fix ourselves on an approach? If we're using a self-signed cert, the cert will be generated by intrusion instead of vault.



_Code quote:_
```Markdown
The signing key will be generated by the Vault
```

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74640)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ajstorm, @catj-cockroach, and @knz)

___
*[docs/RFCS/20211203_session_revival_token.md, line 102 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74640#-Mt4fh5GEUAOOMmHpZRI:-Mt53EzyAGae6QrtvXG7:bnvydnc) ([raw file](https://github.com/cockroachdb/cockroach/blob/54efd4b0b6263402846e4ab79f4aa6058a51f53e/docs/RFCS/20211203_session_revival_token.md#L102)):*
<details><summary><i>Previously, jaylim-crl (Jay Lim) wrote…</i></summary><blockquote>

Just talked to @catj-cockroach, it's likely that we'll be using a self-signed cert here. Could we make this phrase generic so that we don't fix ourselves on an approach? If we're using a self-signed cert, the cert will be generated by intrusion instead of vault.
</blockquote></details>

sure, good to know! so does that mean you can easily use ed25519? (fyi, i started work on this: https://github.com/cockroachdb/cockroach/pull/74646)

**Comment by rafiss** [comment]
thanks for your reviews!

bors=knz,jaylim-crl

**Review by jaylim-crl — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74640)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajstorm, @catj-cockroach, and @knz)

___
*[docs/RFCS/20211203_session_revival_token.md, line 102 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74640#-Mt4fh5GEUAOOMmHpZRI:-Mt5pUeC3uZOVWnDqx95:bdzdpnt) ([raw file](https://github.com/cockroachdb/cockroach/blob/54efd4b0b6263402846e4ab79f4aa6058a51f53e/docs/RFCS/20211203_session_revival_token.md#L102)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

sure, good to know! so does that mean you can easily use ed25519? (fyi, i started work on this: https://github.com/cockroachdb/cockroach/pull/74646)
</blockquote></details>

Yes, that's correct. I'd imagine intrusion to have code that looks like the following: https://github.com/cockroachdb/cockroach/blob/d6a7c039d6cad2d3f9185a6adcfa0af6436b4a71/pkg/security/certs.go#L546-L596

We could technically rely on vault to generate those certs for us, but we'd have to update vault, and based on conversations with @catj-cockroach, it appears that there's no huge benefit to using vault here. Cert rotation for signing certs would just be to regenerate the keypairs for the tenant that got compromised.

**Comment by rafiss** [comment]
nice to hear that!

bors r=knz,jaylim-crl

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74640)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[docs/RFCS/20211203_session_revival_token.md, line 87 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74640#-Mt9WlXyCCCtrspDvuw2:-Mt9WlXz3AchupFZ3a2T:bpu6adw) ([raw file](https://github.com/cockroachdb/cockroach/blob/069a0079468eb1cac238e712711ec33063aae639/docs/RFCS/20211203_session_revival_token.md#L87)):*
> ```Markdown
> 
> 
> One may notice that the structure of the token is similar to a [JSON Web Token](https://datatracker.ietf.org/doc/html/rfc7519#section-3.1), with some differences. For example, we use protocol buffers so that new fields can easily be added and remain backwards compatible, and we do not base64-encode the result.
> ```

Signing protos can be tricky. There is no formal guarantee that the outcome is deterministic, and this gets especially complicated across different versions of the `.proto` file. It is more robust to change the first field to `bytes payload = 1` so that the SessionToken message is always unambiguous about the exact bytes that were signed. And then the recipient of this message can decode the payload bytes into a SessionToken.Payload message object. 
___
*[docs/RFCS/20211203_session_revival_token.md, line 102 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74640#-Mt9Zc9R-qJsv-Lc-QAP:-Mt9Zc9R-qJsv-Lc-QAQ:bscva6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/069a0079468eb1cac238e712711ec33063aae639/docs/RFCS/20211203_session_revival_token.md#L102)):*
> ```Markdown
> 
> 
> In order to sign the token, we will introduce a new signing key (either [Ed25519](https://pkg.go.dev/crypto/ed25519) or RSA depending on what the Intrusion team decides) that is unique per tenant, and is shared by all SQL nodes of the same tenant. The advantage of Ed25519 is that it is fast and generates small signatures. The signing key will be generated by the Intrusion team. Unlike the existing tenant-client cert, this new signing cert doesn't require any DNS or IP information baked into the certificate and the certificate can be self-signed. This makes it easier to rotate if a tenant pod becomes compromised. When creating a tenant SQL node, Intrusion will need to put the key into the `certs-dir` of the SQL node (similar to how the tenant certs are added now). The cert will be named `tenant-signing.<ID>.key`. The `crdb_internal.create_session_token` function will fail if this key is not present, and the token creation will be able to detect the algorithm used by the cert and call the according signature methods. A `cockroach mt cert create-tenant-signing` command will be added for testing purposes.
> ```

What is the ID in `tenant-signing.<ID>.key`? 
___
*[docs/RFCS/20211203_session_revival_token.md, line 123 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74640#-Mt9bnrH7teGRfdk4f1-:-Mt9bnrH7teGRfdk4f10:b-4xk0q9) ([raw file](https://github.com/cockroachdb/cockroach/blob/069a0079468eb1cac238e712711ec33063aae639/docs/RFCS/20211203_session_revival_token.md#L123)):*
> ```Markdown
> One drawback of this design is that it requires the token to be passed in as a CockroachDB-specific StartupMessage. This means that 3rd party drivers won’t be able to use this flow unless we fork them. Currently, that is not a use case we need to support, but if it does become one later, we can add in other ways for the SQL server to receive the token.
> 
> Another drawback is that it needs to handle the case where the signing key is rotated or revoked. In the case of rotation, we can introduce a grace period so that multiple signing keys are present for a 10-minute grace period. Every signature verification attempt needs to first try the new key, and then try the old key if that fails. If the signing key is **revoked**, then all tokens signed with that key will become invalid.
> ```

How are the multiple keys represented on the filesystem?

Instead of trying multiple keys, it would probably be better if the SessionToken message included a key ID or fingerprint.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74640)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[docs/RFCS/20211203_session_revival_token.md, line 87 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74640#-Mt9WlXyCCCtrspDvuw2:-MtJWWHpBRsBOgyEdWpx:b96xs5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/069a0079468eb1cac238e712711ec33063aae639/docs/RFCS/20211203_session_revival_token.md#L87)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Signing protos can be tricky. There is no formal guarantee that the outcome is deterministic, and this gets especially complicated across different versions of the `.proto` file. It is more robust to change the first field to `bytes payload = 1` so that the SessionToken message is always unambiguous about the exact bytes that were signed. And then the recipient of this message can decode the payload bytes into a SessionToken.Payload message object. 
</blockquote></details>

oh, very good to know.
___
*[docs/RFCS/20211203_session_revival_token.md, line 102 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74640#-Mt9Zc9R-qJsv-Lc-QAP:-MtJcnvB9FU60rsGBUuV:b-2iucs6) ([raw file](https://github.com/cockroachdb/cockroach/blob/069a0079468eb1cac238e712711ec33063aae639/docs/RFCS/20211203_session_revival_token.md#L102)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

What is the ID in `tenant-signing.<ID>.key`? 
</blockquote></details>

the tenant ID. the naming convention is what the `client-tenant.<ID>.crt` file uses too. i'll clarify the ID
___
*[docs/RFCS/20211203_session_revival_token.md, line 123 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74640#-Mt9bnrH7teGRfdk4f1-:-MtJfczdA3zXPT0BkLSt:bxuvsbs) ([raw file](https://github.com/cockroachdb/cockroach/blob/069a0079468eb1cac238e712711ec33063aae639/docs/RFCS/20211203_session_revival_token.md#L123)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

How are the multiple keys represented on the filesystem?

Instead of trying multiple keys, it would probably be better if the SessionToken message included a key ID or fingerprint. 
</blockquote></details>

do you know a conventional way to get a key ID/fingerprint? like could i just generate a random `SerialNumber` for the `x509.Certificate` struct?

**Pull request merged**
