### PR TITLE
[wip] tree: add AnyEnum array to AnyEnum concatenation

### PR DESCRIPTION
**Pull request by otan**
Refs: #71446

See individual commits for details.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Perplexing indeed, I'll try to debug later today

**Comment by RaduBerinde** [comment]
Ah, then CC @yuzefovich

**Comment by RaduBerinde** [comment]
The generated code in question doesn't perform the operation if the input is NULL:

```go
					if !colNulls.NullAt(i) {
						// We only want to perform the projection operation if the value is not null.
						arg := col.Get(i)

						_res, err := _overloadHelper.BinFn(_overloadHelper.EvalCtx, arg.(tree.Datum), p.constArg.(tree.Datum))
						if err != nil {
							colexecerror.ExpectedError(err)
						}
						if _res == tree.DNull {
							_outNulls.SetNull(i)
						}
						projCol.Set(i, _res)

					}
				}
```

**Review by yuzefovich — COMMENTED** [review]
The change in the second commit seems sane to me.

> Reviewed 7 of 7 files at r1, 7 of 7 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71447#-:-Mlx0eyG-vCO3XiJ7Sql:b4rmml6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rafiss)

___
*[pkg/sql/colexec/colexecproj/proj_const_ops_tmpl.go, line 125 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71447#-Mlx-zpO361IwyndX3bp:-Mlx-zpO361IwyndX3bq:bzg5dk0) ([raw file](https://github.com/cockroachdb/cockroach/blob/070442be542c9200f4b83cb868a133b1b71c1783/pkg/sql/colexec/colexecproj/proj_const_ops_tmpl.go#L125)):*
> ```Go
> 		// of a projection is Null.
> 		_outNulls := projVec.Nulls()
> 		if vec.Nulls().MaybeHasNulls() && !_overloadHelper.NullableArgs {
> ```

I think we'll want to apply the same change to `proj_non_const_ops_tmpl`. Maybe try a logic test from the third commit where values for concat come from columns rather than being constants? I'm guessing that we should be able to reproduce the bug there too.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71447)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @yuzefovich)

___
*[pkg/sql/colexec/colexecproj/proj_const_ops_tmpl.go, line 125 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71447#-Mlx-zpO361IwyndX3bp:-MlxWHffDgx5bFHCjM3o:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/070442be542c9200f4b83cb868a133b1b71c1783/pkg/sql/colexec/colexecproj/proj_const_ops_tmpl.go#L125)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I think we'll want to apply the same change to `proj_non_const_ops_tmpl`. Maybe try a logic test from the third commit where values for concat come from columns rather than being constants? I'm guessing that we should be able to reproduce the bug there too.
</blockquote></details>

Done.

**Pull request closed without merging**
