### PR TITLE
release-23.1: kvserver: transfer lease when acquiring lease outside preferences

### PR DESCRIPTION
**Pull request by kvoli**
Backport 3/3 commits from #107507.
Backport 1/1 commits from #107967.

/cc @cockroachdb/release

---

When a leaseholder is lost, any surviving replica may acquire the lease, even if it violates lease preferences. There are two main reasons for this: we need to elect a new Raft leader who will acquire the lease, which is agnostic to lease preferences, and there may not even be any surviving replicas that satisfy the lease preferences at all, so we don't want to keep the range unavailable while we try to figure this out (considering e.g. network timeouts can delay this for many seconds).

However, after acquiring a lease, we rely on the replicate queue to transfer the lease back to a replica that conforms with the preferences, which can take several minutes. In multi-region clusters, this can cause severe latency degradation if the lease is acquired in a remote region.

This PR will detect lease preference violations when a replica acquires a new lease, and eagerly enqueue it in the replicate queue for transfer (if possible). If the first process fails, the replica will be sent to purgatory and retried soon after.

Additionally, two roachtests are added for lease preference conformance timing. The first test, .../partial-first-preference-down, takes down one of the preferred locality nodes (1/2). The second test, .../full-first-preference-down, takes down both the preferred locality nodes (2/2).

Resolves https://github.com/cockroachdb/cockroach/issues/106100.
Epic: none

Release note (bug fix): When losing a leaseholder and using lease preferences, the lease can be acquired by any other replica (regardless of lease preferences) in order to restore availability as soon as possible. The new leaseholder will now immediately check if it violates the lease preferences, and attempt to transfer the lease to a replica that satisfies the preferences if possible.

----

Release justification: Increases lease preference conformance significantly in the common case. User ask.

### CODE REVIEW

**Comment by kvoli** [comment]
With #107655 backported to release 23.1, the initial preference conformance speed is similar to master. 

Should be good to take a look!

**Comment by andrewbaptist** [comment]
Can we let this sit on master for a few days before backporting. This type of change (reordering of the priority within the replicate_queue) often has subtle and unexpected consequences and letting it bake first will help.

**Review by erikgrinaker — DISMISSED** [review]
LGTM, but agree with letting this bake on master for a bit.

**Comment by kvoli** [comment]
Sounds good. I'll hold off merging.

**Comment by kvoli** [comment]
Baked on master for 5 days. 

TYFTRs!

**Comment by kvoli** [comment]
TYFTRs!

Rebased on `release-23.1`. I'll merge once green.

**Comment by kvoli** [comment]
`lease-preferences/full-first-preference-down` failed on master last night #107862. I'm going to hold off merging until the failure is understood.

**Comment by kvoli** [comment]
We understand why #107862 failled. #107967 is a candidate fix.

**Review by erikgrinaker — APPROVED** [review]
LGTM

**Comment by kvoli** [comment]
I'm going to merge this tomorrow, barring any test failures overnight on master.

**Review by andrewbaptist — APPROVED** [review]
:lgtm: I would let this bake a little longer on master still since there were new changes. These changes are a little hard to track down and there is not a rush since we aren't going to pull this into a 23.1 release for a few more days still. Maybe merge on Monday? These types of changes are hard to predict the impact as there is often a lot of assumed behavior both in tests and existing code.

**Comment by kvoli** [comment]
> :lgtm: I would let this bake a little longer on master still since there were new changes. These changes are a little hard to track down and there is not a rush since we aren't going to pull this into a 23.1 release for a few more days still. Maybe merge on Monday? These types of changes are hard to predict the impact as there is often a lot of assumed behavior both in tests and existing code.

I'm thinking there is benefit to getting more bake time on 23.1. I want to take the cautious approach though, merging on Monday SGTM!

Thanks for the reviews, and helping this along. Much appreciated!

**Pull request merged**
