### PR TITLE
db-console: enable type-checking during linting

### LINKED ISSUE #81203: pkg/ui/workspaces/db-console isn't type-checked under Bazel
Bazel builds don't perform any typechecking of `pkg/ui/workspaces/db-console/`. TypeScript compilation failures are exposed only via `make`.

**To Reproduce**
Add this line to any TypeScript file:

```ts
"".butReverseIt();
```

**Expected behavior**
TypeScript compilation should fail, and no `cockroach` binary should be produced.

Jira issue: CRDB-15303

### PR DESCRIPTION
**Pull request by sjbarag**
TypeScript type-checking was previously not configured for db-console
due to dependency version mismatches [1]. Now that those have been
resolved, configure type-checking in the
//pkg/ui/workspaces/db-console:lint test suite.

[1] https://github.com/cockroachdb/cockroach/pull/81409
fixes #81203

Release note: None

### CODE REVIEW

**Comment by sjbarag** [comment]
@sjbarag remember to rebase on top of #81954 when that lands :)

**Review by laurenbarker — COMMENTED** [review]
I don't think I have enough context to approve this, so I just asked some questions :)

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81952#-:-N35IVUg1UqjqjBDzwU4:bknhgm5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nathanstilwell, @rickystewart, and @sjbarag)

___
*[`pkg/ui/workspaces/db-console/BUILD.bazel` line 276 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81952#-N35IFtG4wJYpxpTlZgC:-N35IFtG4wJYpxpTlZgD:bnjxkm7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9f892af924b8a37f7142b03d53480cd332a9107/pkg/ui/workspaces/db-console/BUILD.bazel#L276)):*
> ```Starlark
>         exclude = [
>             "src/**/*.stories.tsx",
>             "src/**/*.spec.tsx",
> ```

We don't type-check the tests? That seems weird since they're written in TS.
___
*[`pkg/ui/workspaces/db-console/BUILD.bazel` line 288 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81952#-N35IhgU8vm-I08Hx7rc:-N35IhgU8vm-I08Hx7rd:b7y2w8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9f892af924b8a37f7142b03d53480cd332a9107/pkg/ui/workspaces/db-console/BUILD.bazel#L288)):*
> ```Starlark
>         "//pkg/ui/workspaces/db-console/src/js:crdb-protobuf-client",
>         "//pkg/ui/workspaces/db-console/ccl/src/js:crdb-protobuf-client-ccl",
>         "@npm_db_console//@babel/parser",
> ```

What are these dependencies for? Do all deps need to be added here?

**Review by rickystewart — APPROVED** [review]
Nice!

**Review by sjbarag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81952)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @laurenbarker and @nathanstilwell)

___
*[`pkg/ui/workspaces/db-console/BUILD.bazel` line 276 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81952#-N35IFtG4wJYpxpTlZgC:-N3Ps4mpBJrSF2uGUPmc:bm8hxuo) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9f892af924b8a37f7142b03d53480cd332a9107/pkg/ui/workspaces/db-console/BUILD.bazel#L276)):*
<details><summary><i>Previously, laurenbarker (Lauren Barker) wrote…</i></summary><blockquote>

We don't type-check the tests? That seems weird since they're written in TS.
</blockquote></details>

Good point, we definitely could! And probably should!  I'll fix that real fast :)
___
*[`pkg/ui/workspaces/db-console/BUILD.bazel` line 288 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81952#-N35IhgU8vm-I08Hx7rc:-N3Pq29tBvRJAJIVzZX_:b-xvkw3y) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9f892af924b8a37f7142b03d53480cd332a9107/pkg/ui/workspaces/db-console/BUILD.bazel#L288)):*
<details><summary><i>Previously, laurenbarker (Lauren Barker) wrote…</i></summary><blockquote>

What are these dependencies for? Do all deps need to be added here?
</blockquote></details>

These are only the dependencies required to run the equivalent of `tsc --noEmit`!  Bazel tries to keep the dependencies for each task as minimal as possible, so it's generally not recommended to specify something like `@npm_db_console//:node_modules` (though that is supported).

**Review by laurenbarker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81952)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nathanstilwell and @sjbarag)

___
*[`pkg/ui/workspaces/db-console/BUILD.bazel` line 276 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81952#-N35IFtG4wJYpxpTlZgC:-N3PvBN5-g11VopC0n0k:bgc7vqv) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9f892af924b8a37f7142b03d53480cd332a9107/pkg/ui/workspaces/db-console/BUILD.bazel#L276)):*
<details><summary><i>Previously, sjbarag (Sean Barag) wrote…</i></summary><blockquote>

Good point, we definitely could! And probably should!  I'll fix that real fast :)
</blockquote></details>

:heart: 
___
*[`pkg/ui/workspaces/db-console/BUILD.bazel` line 288 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81952#-N35IhgU8vm-I08Hx7rc:-N3Pv0z7ETcdv2HFMNLJ:br3tytw) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9f892af924b8a37f7142b03d53480cd332a9107/pkg/ui/workspaces/db-console/BUILD.bazel#L288)):*
<details><summary><i>Previously, sjbarag (Sean Barag) wrote…</i></summary><blockquote>

These are only the dependencies required to run the equivalent of `tsc --noEmit`!  Bazel tries to keep the dependencies for each task as minimal as possible, so it's generally not recommended to specify something like `@npm_db_console//:node_modules` (though that is supported).
</blockquote></details>

Ahh, that does make sense.

**Comment by sjbarag** [comment]
Rebased on `master` again, and now with 100% more typechecking of db-console tests!

**Comment by sjbarag** [comment]
bors r=rickystewart,laurenbarker

**Pull request merged**
