### PR TITLE
colexec: add disk monitor to disk queue

### LINKED ISSUE #45169: colexec: add disk monitoring
The row execution temporary storage engine has disk monitoring:
https://github.com/cockroachdb/cockroach/blob/9c72e72cb969c77a233df0a7f25dde014cd8060b/pkg/sql/execinfra/server_config.go#L147
We need to plumb this disk monitor down to the `colcontainer.DiskQueue` to count the number of bytes written to disk and subtract the number of bytes when a file is removed.

Additionally, I don't think the disk monitor is hooked up to a cluster metric, which would be a good idea to do.

### PR DESCRIPTION
**Pull request by Azhng**
This commit plumbs down disk monitor from FlowCtx to disk queue. It will
be monitoring disk usage of vectorize engine similar to row engine.

Release justification: bug fixes and low-risk updates to new functionality
since it is necessary for the new disk spilling infrastructure to have
disk monitoring

Release note: None

Closes #45169

### CODE REVIEW

**Review by asubiotto — CHANGES_REQUESTED** [review]
Nice, could you also add the graph metric for the disk monitor? Take a look at `DistSQLMetrics` and `metaMemCurBytes` and (max as well) to use that where the disk monitor is created.

> Reviewed 38 of 38 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46062#-:-M2J5IAL25gYyE-1klM3:bxix9tg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/sql/colcontainer/diskqueue.go, line 428 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46062#-M2J33D40IwL87z7rl8o:-M2J33D40IwL87z7rl8p:b-ekbbeb) ([raw file](https://github.com/cockroachdb/cockroach/blob/196dae8f435b811bf6cfafb27123ee7c6ac064ae/pkg/sql/colcontainer/diskqueue.go#L428)):*
> ```Go
> 		totalSize += int64(file.totalSize)
> 	}
> 	d.diskAcc.Shrink(ctx, totalSize)
> ```

I think instead of `Shrink`ing this manually, you should call `Close`, which would be less error prone.
___
*[pkg/sql/colexec/operator.go, line 169 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46062#-M2J4mpW1jgXZW_9iB-m:-M2J4mpW1jgXZW_9iB-n:b-39ni6d) ([raw file](https://github.com/cockroachdb/cockroach/blob/196dae8f435b811bf6cfafb27123ee7c6ac064ae/pkg/sql/colexec/operator.go#L169)):*
> ```Go
> }
> 
> type closableOperator interface {
> ```

nice, could you replace references to `io.Closer` with `closableOperator` while you're at it?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46062)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @Azhng)

___
*[pkg/sql/colcontainer/diskqueue.go, line 428 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46062#-M2J33D40IwL87z7rl8o:-M2JRtdT1cEpvixje5iG:by49q35) ([raw file](https://github.com/cockroachdb/cockroach/blob/196dae8f435b811bf6cfafb27123ee7c6ac064ae/pkg/sql/colcontainer/diskqueue.go#L428)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think instead of `Shrink`ing this manually, you should call `Close`, which would be less error prone.
</blockquote></details>

But not if the disk queue is rewindable, right?
___
*[pkg/sql/colexec/execplan.go, line 141 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46062#-M2JS4681BI_PrkcGAOu:-M2JS469DH-BVItpv6H_:b-9tkdfp) ([raw file](https://github.com/cockroachdb/cockroach/blob/196dae8f435b811bf6cfafb27123ee7c6ac064ae/pkg/sql/colexec/execplan.go#L141)):*
> ```Go
> 	BufferingOpMemMonitors []*mon.BytesMonitor
> 	BufferingOpMemAccounts []*mon.BoundAccount
> 	DiskMonitors           []*mon.BytesMonitor
> ```

Do we actually need this separation between "buffering mem" and "disk" infrastructure? I think it'd be nicer if we just had `Monitors` and `Accounts` for both.
___
*[pkg/sql/colexec/execplan.go, line 877 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46062#-M2JSxzL9YnWdGoBYC66:-M2JSxzL9YnWdGoBYC67:b-wzon9z) ([raw file](https://github.com/cockroachdb/cockroach/blob/196dae8f435b811bf6cfafb27123ee7c6ac064ae/pkg/sql/colexec/execplan.go#L877)):*
> ```Go
> 
> 			monitorName := "merge-joiner"
> ```

nit: I'd say this newline is unnecessary.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46062#-M2JT3NdEW4PDTOioVG6:-M2JT3NdEW4PDTOioVG7:b-o1al0g) ([raw file](https://github.com/cockroachdb/cockroach/blob/196dae8f435b811bf6cfafb27123ee7c6ac064ae/pkg/sql/colexec/external_hash_joiner.go#L18)):*
> ```Go
> 	"math"
> 
> 	"github.com/cockroachdb/errors"
> ```

nit: not sure why this changed.
___
*[pkg/sql/colexec/external_hash_joiner.go, line 209 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46062#-M2JTlba6mj0U9ZogueT:-M2JTlba6mj0U9ZogueU:bw9ngu4) ([raw file](https://github.com/cockroachdb/cockroach/blob/196dae8f435b811bf6cfafb27123ee7c6ac064ae/pkg/sql/colexec/external_hash_joiner.go#L209)):*
> ```Go
> }
> 
> var _ Operator = &externalHashJoiner{}
> ```

nit: this declaration is redundant given `closableOperator` declaration below (and in other files as well).
___
*[pkg/sql/colexec/fn_op.go, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46062#-M2JTUu4AORkvZat5-Gf:-M2JTUu4AORkvZat5-Gg:bmlknlt) ([raw file](https://github.com/cockroachdb/cockroach/blob/196dae8f435b811bf6cfafb27123ee7c6ac064ae/pkg/sql/colexec/fn_op.go#L40)):*
> ```Go
> }
> 
> func (f fnOp) reset(_ context.Context) {}
> ```

Not that it's your fault, but I think this is wrong - we should be attempting to call `f.input.reset()`.
___
*[pkg/sql/colexec/spilling_queue.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46062#-M2JUK0CBoSy5qhDmSrl:-M2JUK0CBoSy5qhDmSrm:b-doqxq4) ([raw file](https://github.com/cockroachdb/cockroach/blob/196dae8f435b811bf6cfafb27123ee7c6ac064ae/pkg/sql/colexec/spilling_queue.go#L23)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/util/log"
> 	"github.com/cockroachdb/cockroach/pkg/util/mon"
> ```

nit: extra newline.
___
*[pkg/sql/colexec/utils_test.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46062#-M2JUURECWsuOrIICkZ4:-M2JUURECWsuOrIICkZ5:b-m5v4ox) ([raw file](https://github.com/cockroachdb/cockroach/blob/196dae8f435b811bf6cfafb27123ee7c6ac064ae/pkg/sql/colexec/utils_test.go#L25)):*
> ```Go
> 
> 	"github.com/cockroachdb/apd"
> 	"github.com/pkg/errors"
> ```

nit: why this change?

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46062)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @yuzefovich)

___
*[pkg/sql/colcontainer/diskqueue.go, line 428 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46062#-M2J33D40IwL87z7rl8o:-M2JYEk9DySMmnxNDV5Q:b-kjzf46) ([raw file](https://github.com/cockroachdb/cockroach/blob/196dae8f435b811bf6cfafb27123ee7c6ac064ae/pkg/sql/colcontainer/diskqueue.go#L428)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

But not if the disk queue is rewindable, right?
</blockquote></details>

This was a leftover comment. You would need to create a new account per diskqueue for that, which I don't think is necessary. It shouldn't matter if the disk queue is rewindable I think, since this is `Close`

**Review by Azhng — COMMENTED** [review]
Added metrics to the disk monitors 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46062#-:-M2Vb5vbCzCbR-WW0EsM:b-qoud8q)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colcontainer/diskqueue.go, line 428 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46062#-M2J33D40IwL87z7rl8o:-M2LoBfRELy-VipNsJt6:b-c8up5g) ([raw file](https://github.com/cockroachdb/cockroach/blob/196dae8f435b811bf6cfafb27123ee7c6ac064ae/pkg/sql/colcontainer/diskqueue.go#L428)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This was a leftover comment. You would need to create a new account per diskqueue for that, which I don't think is necessary. It shouldn't matter if the disk queue is rewindable I think, since this is `Close`
</blockquote></details>

The issue with directly closing the disaccount here is that `diskqueue` is used by `partitionqueue`. `partitionqueue` is given one disk account and it is shared among all the partitions. If the disk account is closed here then it's gonna affect the accounting in other `diskqueue`s inside the `partitionqueue`

I also don't think we should be allowing the `partitionqueue` to create disk account on the fly since we return all the disk monitors / disk account created during the `NewColOperator` to the vectorized flow and vectorized flow will keep track of all of the monitors and accounts. 

It will be difficult for vectorized flow to keep track of all the accounts/monitors that were created on the fly. 
___
*[pkg/sql/colexec/execplan.go, line 141 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46062#-M2JS4681BI_PrkcGAOu:-M2Ln7_F-k3KsNqsDOjz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/196dae8f435b811bf6cfafb27123ee7c6ac064ae/pkg/sql/colexec/execplan.go#L141)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Do we actually need this separation between "buffering mem" and "disk" infrastructure? I think it'd be nicer if we just had `Monitors` and `Accounts` for both.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/fn_op.go, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46062#-M2JTUu4AORkvZat5-Gf:-M2LnTCb2y2Fzn1cPDB6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/196dae8f435b811bf6cfafb27123ee7c6ac064ae/pkg/sql/colexec/fn_op.go#L40)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Not that it's your fault, but I think this is wrong - we should be attempting to call `f.input.reset()`.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/operator.go, line 169 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46062#-M2J4mpW1jgXZW_9iB-m:-M2QHJFzEuVCRozewfTC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/196dae8f435b811bf6cfafb27123ee7c6ac064ae/pkg/sql/colexec/operator.go#L169)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nice, could you replace references to `io.Closer` with `closableOperator` while you're at it?
</blockquote></details>

Done.

**Review by asubiotto — CHANGES_REQUESTED** [review]
Could you also try running a disk spilling operation and seeing how this metric evolves over an operation? You should be able to `generate_series` a table, set the memory limit low to `10KiB` and sort the values in the table using `PREPARE x AS SELECT * FROM table ORDER BY something; EXECUTE x DISCARD ROWS` to discard the rows. The metric you added can be accessed by going to: `<AdminUI>/#/debug/chart` and selecting the metric you added in the `Select a metric` dropdown.

> Reviewed 25 of 26 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46062#-:-M2Y36Pe4uQ3Mgp6gOKI:boxcjqe)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @Azhng, and @yuzefovich)

___
*[pkg/server/server.go, line 670 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46062#-M2Y0iq8-fQ4JDbuS693:-M2Y0iq8-fQ4JDbuS694:b-frdsm3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1a0ca4fa3f99a69d06a4826bc8e18015d7db52b/pkg/server/server.go#L670)):*
> ```Go
> 		ExternalStorageFromURI: externalStorageFromURI,
> 	}
> 	s.cfg.TempStorageConfig.Mon.SetMetrics(distSQLMetrics.DiskMonsCount, distSQLMetrics.DiskMonsHist)
> ```

I would prefer if we can pass in `Count` and `Hist` into `TempStorageConfigFromEnv` to keep the setup of this monitor in one place.
___
*[pkg/sql/colflow/vectorized_flow.go, line 210 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46062#-M2Y1gPcCKrQVPeueVKo:-M2Y1gPd5hLCYEh3_9Qv:b-hxats2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1a0ca4fa3f99a69d06a4826bc8e18015d7db52b/pkg/sql/colflow/vectorized_flow.go#L210)):*
> ```Go
> 		acc.Close(ctx)
> 	}
> 	for _, momn := range creator.monitors {
> ```

nit: `s/momn/mon`
___
*[pkg/sql/execinfra/metrics.go, line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46062#-M2Y2ANI1J8lls3I7714:-M2Y2ANI1J8lls3I7715:bmhfzq2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1a0ca4fa3f99a69d06a4826bc8e18015d7db52b/pkg/sql/execinfra/metrics.go#L31)):*
> ```Go
> 	CurBytesCount *metric.Gauge
> 	VecOpenFDs    *metric.Gauge
> 	DiskMonsCount *metric.Gauge
> ```

I would rename this to be more in line with the memory: `CurDiskBytesCount`, `MaxDiskBytesHist`.
___
*[pkg/sql/execinfra/metrics.go, line 96 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46062#-M2Y1pCB9TA-q7V9R6hW:-M2Y1pCB9TA-q7V9R6hX:b5vaw9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1a0ca4fa3f99a69d06a4826bc8e18015d7db52b/pkg/sql/execinfra/metrics.go#L96)):*
> ```Go
> 	}
> 	metaDiskMonitors = metric.Metadata{
> 		Name:        "sql.distsql.diskmon.current",
> ```

To be in line with the memory settings I suggest we rename this and below to: `sql.disk.distsql.{current,max}`
___
*[pkg/sql/execinfra/metrics.go, line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46062#-M2Y203dC6wHaQpF2ilT:-M2Y203dC6wHaQpF2ilU:bxi8tkf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1a0ca4fa3f99a69d06a4826bc8e18015d7db52b/pkg/sql/execinfra/metrics.go#L97)):*
> ```Go
> 	metaDiskMonitors = metric.Metadata{
> 		Name:        "sql.distsql.diskmon.current",
> 		Help:        "Current number of disk monitors opened for distsql",
> ```

This should be the number of bytes on disk, no?
___
*[pkg/sql/execinfra/metrics.go, line 99 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46062#-M2Y1y6oBP0FVo6AalXe:-M2Y1y6oBP0FVo6AalXf:b-ee1fet) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1a0ca4fa3f99a69d06a4826bc8e18015d7db52b/pkg/sql/execinfra/metrics.go#L99)):*
> ```Go
> 		Help:        "Current number of disk monitors opened for distsql",
> 		Measurement: "Disk",
> 		Unit:        metric.Unit_COUNT,
> ```

This should be `metric.Unit_BYTES` here and below.

**Review by Azhng — COMMENTED** [review]
Here is the what the size of the temp directory look like over time when when I was running a join of two tables of 20000 rows: 
```
Reserving: Temp Dir Size on reserve: 188K	/Users/azhng/src/github.com/cockroach/cockroach-data/cockroach-temp968568970

Reserving: Temp Dir Size on reserve: 4.7M	/Users/azhng/src/github.com/cockroach/cockroach-data/cockroach-temp968568970

Reserving: Temp Dir Size on reserve:  12M	/Users/azhng/src/github.com/cockroach/cockroach-data/cockroach-temp968568970

Reserving: Temp Dir Size on reserve:  12M	/Users/azhng/src/github.com/cockroach/cockroach-data/cockroach-temp968568970

Releasing: Temp Dir Size on reserve: 180K	/Users/azhng/src/github.com/cockroach/cockroach-data/cockroach-temp968568970

Releasing: Temp Dir Size on reserve: 180K	/Users/azhng/src/github.com/cockroach/cockroach-data/cockroach-temp968568970

Releasing: Temp Dir Size on reserve: 180K	/Users/azhng/src/github.com/cockroach/cockroach-data/cockroach-temp968568970
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46062#-:-M2ZpuOI9L3G9fAL5mSd:bg2vko4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/server/server.go, line 670 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46062#-M2Y0iq8-fQ4JDbuS693:-M2YsJxK54PnQSblVzY5:b-egpnz2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1a0ca4fa3f99a69d06a4826bc8e18015d7db52b/pkg/server/server.go#L670)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I would prefer if we can pass in `Count` and `Hist` into `TempStorageConfigFromEnv` to keep the setup of this monitor in one place.
</blockquote></details>

`TempStorageConfigFromEnv` is called in `runStart` [here][1] which is before `distSQLMetrics` is created [here][2] . So `TempStorageConfigEnv` won't have access to any metrics until the server is in the middle of being bootstrapped later. I feel `distSQLMetrics` should only be created inside `server.NewServer`. 

[1]: https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/start.go#L570
[2]: https://github.com/cockroachdb/cockroach/blob/master/pkg/server/server.go#L606
___
*[pkg/sql/execinfra/metrics.go, line 31 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46062#-M2Y2ANI1J8lls3I7714:-M2Yjcp00v95nAIzLnML:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1a0ca4fa3f99a69d06a4826bc8e18015d7db52b/pkg/sql/execinfra/metrics.go#L31)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I would rename this to be more in line with the memory: `CurDiskBytesCount`, `MaxDiskBytesHist`.
</blockquote></details>

Done.
___
*[pkg/sql/execinfra/metrics.go, line 96 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46062#-M2Y1pCB9TA-q7V9R6hW:-M2Yjn-xBSMcINlDPdqx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1a0ca4fa3f99a69d06a4826bc8e18015d7db52b/pkg/sql/execinfra/metrics.go#L96)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

To be in line with the memory settings I suggest we rename this and below to: `sql.disk.distsql.{current,max}`
</blockquote></details>

Done.
___
*[pkg/sql/execinfra/metrics.go, line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46062#-M2Y203dC6wHaQpF2ilT:-M2YkC4_9kwZUVypfKHq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1a0ca4fa3f99a69d06a4826bc8e18015d7db52b/pkg/sql/execinfra/metrics.go#L97)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This should be the number of bytes on disk, no?
</blockquote></details>

Done.
___
*[pkg/sql/execinfra/metrics.go, line 99 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46062#-M2Y1y6oBP0FVo6AalXe:-M2YkCgl69dCN9e8HytY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1a0ca4fa3f99a69d06a4826bc8e18015d7db52b/pkg/sql/execinfra/metrics.go#L99)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This should be `metric.Unit_BYTES` here and below.
</blockquote></details>

Done.

**Review by Azhng — COMMENTED** [review]
Rebased to pick up `relative_rank`. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46062#-:-M2Zv9iE3hdK9LWUQhh_:bvh0zhp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

**Review by asubiotto — COMMENTED** [review]
Nice, did this sort of line up with the monitor usage?

> Reviewed 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46062#-:-M2c103VCVv7_LlsXBhu:b4galj6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @Azhng, and @yuzefovich)

___
*[pkg/server/server.go, line 670 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46062#-M2Y0iq8-fQ4JDbuS693:-M2c1mblAm4Be5Iixm5k:b-81nlyc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1a0ca4fa3f99a69d06a4826bc8e18015d7db52b/pkg/server/server.go#L670)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

`TempStorageConfigFromEnv` is called in `runStart` [here][1] which is before `distSQLMetrics` is created [here][2] . So `TempStorageConfigEnv` won't have access to any metrics until the server is in the middle of being bootstrapped later. I feel `distSQLMetrics` should only be created inside `server.NewServer`. 

[1]: https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/start.go#L570
[2]: https://github.com/cockroachdb/cockroach/blob/master/pkg/server/server.go#L606

</blockquote></details>

SGTM.
___
*[pkg/server/server.go, line 671 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/46062#-M2c1nkC94Q4ZFEDas91:-M2c1nkC94Q4ZFEDas92:b-av3xnu) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bc3ed73b3a84181bf49ce6c50c7913682498507/pkg/server/server.go#L671)):*
> ```Go
> 		ExternalStorageFromURI: externalStorageFromURI,
> 	}
> 	s.cfg.TempStorageConfig.Mon.SetMetrics(distSQLMetrics.CurByteDiskCount, distSQLMetrics.MaxDiskByteHist)
> ```

nit: make these plural like the other metrics and I think it makes more sense to call it `CurDiskBytesCount` rather than `CudBytesDiskCount`.

**Review by Azhng — COMMENTED** [review]
Yep

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46062#-:-M2d4Whs-20j1AZKFkbl:b2nhswv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/server/server.go, line 670 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46062#-M2Y0iq8-fQ4JDbuS693:-M2dFkJJ9rqHfVvGojej:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1a0ca4fa3f99a69d06a4826bc8e18015d7db52b/pkg/server/server.go#L670)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

SGTM.
</blockquote></details>

Done.

**Review by asubiotto — APPROVED** [review]
nit: Please add explanation of why this is a low-risk update to new functionality in the release justification.

:lgtm: otherwise

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46062#-:-M2dNpoT1Rlr9QvU9e0m:b-my8uju)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

**Comment by Azhng** [comment]
TFTR!

bors r+

**Pull request merged**
