### PR TITLE
cmd/reduce: only walk window frames if present

### PR DESCRIPTION
**Pull request by madelynnblue**
Release note: None

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42501#-:-Ltg8jRlBdL1n5kP6OhN:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mjibson)

___
*[pkg/testutils/reduce/reducesql/reducesql.go, line 269 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42501#-Ltg8fm_BieeAgYTN6pj:-Ltg8fm_BieeAgYTN6pk:b8uhzt9) ([raw file](https://github.com/cockroachdb/cockroach/blob/823d2c27b832cd635edbe5409377186e58737812/pkg/testutils/reduce/reducesql/reducesql.go#L269)):*
> ```Go
> 				walk(node.Expr)
> 			case *tree.WindowDef:
> 				walk(node.Partitions)
> ```

Do we also need to walk the ORDER BY clause?

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42501)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/testutils/reduce/reducesql/reducesql.go, line 269 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42501#-Ltg8fm_BieeAgYTN6pj:-LtgmxNG9ng9DOiblC2A:b-by7bqe) ([raw file](https://github.com/cockroachdb/cockroach/blob/823d2c27b832cd635edbe5409377186e58737812/pkg/testutils/reduce/reducesql/reducesql.go#L269)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Do we also need to walk the ORDER BY clause?
</blockquote></details>

Theoretically yes, but not yet. SELECT doesn't even descend into ORDER BY. Instead we just attempt to remove it completely, which is already done for WindowDef.

**Pull request merged**
