### PR TITLE
license: change to using the new CockroachDB Software License

### PR DESCRIPTION
**Pull request by jlinder**
1. Update the LICENSE file to the new CockroachDB Softare License
2. Update the Licensing section in README.md
3. Move THIRD-PARTY-NOTICES.txt file to the root level of the repository (out of the /licenses folder)
4. Remove the /licenses folder and all its remaining contents
5. Update the license linters to lint for the new license in source files
6. Update source files to reference the new license, including adding license headers for files that didn't previously contain them.

Part of RE-658

Release note (general change): Change the license cockroach is
distributed under to the new CockroachDB Software License.

### CODE REVIEW

**Comment by jlinder** [comment]
A few notes:

- I structured the commits to make reviewing this change easier. Once it passes review, I will squash the linter update commit and the commits that update the license headers.
- In a follow-on PR, I will be adding a new linter to check the .sh, makefile and .py files contain the right license headers.

**Review by rail — APPROVED** [review]
LGTM, :shipit:

**Review by celiala — APPROVED** [review]
LGTM 👍🏼

**Review by dt — CHANGES_REQUESTED** [review]
Already discussed concerns offline w.r.t 3rd party license requirements so just noting that here until we sort that out.

**Pull request closed without merging**
