### PR TITLE
stmtdiagnostics: support probabilistic bundle collection

### PR DESCRIPTION
**Pull request by irfansharif**
We enable the following ability (the first half of #82896):
```
  Pick a stmt fingerprint, declare a sampling probability which controls
  when verbose tracing is enabled for it, and a latency threshold for
  which a trace is persisted.
```
With a given stmt rate (say 1000/s) and a given percentile we're trying
to capture (say p99.9), we have 0.001R stmt/s in the 99.9th percentile
(1/s in our example). We should be able to set a sampling probability P
such that with high likelihood (>95%) we capture at least one trace over
the next S seconds. The sampling rate lets you control how the overhead
you’re introducing for those statements in aggregate, which if dialed up
higher lets you lower S. You might want to do such a thing for
infrequently executed statements. We do all this using the existing
statement diagnostics machinery. It looks roughly as follows
```
   > SELECT crdb_internal.request_statement_bundle(
      'INSERT INTO ...', -- fingerprint
      0.01,              -- sampling probability
      '120ms'::INTERVAL, -- latency target
      '15m'::INTERVAL    -- request expiration
     );

   $ cockroach statement-diag list --insecure
    No statement diagnostics bundles available.
    Outstanding activation requests:
      ID                  Statement        Sampling probability  Min latency
      770367610894417921  INSERT INTO ...  0.0100                90ms

   # wait for an eventual capture..

   $ cockroach statement-diag list --insecure
    Statement diagnostics bundles:
      ID                  Collection time          Statement
      770367073624621057  2022-06-14 00:49:33 UTC  INSERT INTO ...

   $ cockroach statement-diag download 770367073624621057 --insecure
   Bundle saved to "stmt-bundle-770367073624621057.zip"

   $ unzip stmt-bundle-770367073624621057.zip stmt
   $ cat stmt/trace.txt
    ...
        0.846ms      0.017ms      event:kv/kvserver/spanlatch/manager.go:532
                                    [n1,s1,r76/1:/Table/10{7/1-8}] waiting to
                                    acquire read latch /Table/107/1/41/7/0@0,0,
                                    held by write latch
                                    /Table/107/1/41/7/0@1655167773.362147000,0
        98.776ms     97.930ms     event:kv/kvserver/concurrency/concurrency_manager.go:301
                                    [n1,s1,r76/1:/Table/10{7/1-8}] scanning
                                    lock table for conflicting locks
```
We leave wiring this up to the UI and continuous capture (second half of
\#82896) to future PRs.

Release note: None

### CODE REVIEW

**Comment by irfansharif** [comment]
Still have a few TODOs but read for a look. Have to confirm it works with more things.

**Review by yuzefovich — COMMENTED** [review]
Thanks! Looks good to me, and once unit tests are added, it can go in.

Also, in #82750 you were mentioning "backportable" prototypes to 22.1 and 21.2 - this was so that you could build an instrumented binary, and we don't have plans to actually backport this change (because of the migration), right?

> Reviewed 6 of 6 files at r1, 30 of 30 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82750#-:-N4bxqJT4QZgphuKMNRZ:b7yttyo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @irfansharif)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82750#-N4bnRVp3oF2tlCsm_A4):*
nit: do you wanna remove all of 22.1 migrations? It's ok if not - I personally get a lot of gratification from removing the code :)
___
*[`pkg/sql/catalog/systemschema/system.go` line 416 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82750#-N4bpm_F3sT3xQt8-LLo:-N4bpm_F3sT3xQt8-LLp:b-2lsxdr) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5a0e11b92875b59e4c408e30855bae8b41628ed/pkg/sql/catalog/systemschema/system.go#L416)):*
> ```Go
> 	sampling_probability FLOAT NULL,
> 	CONSTRAINT "primary" PRIMARY KEY (id),
> 	CONSTRAINT check_sampling_probability CHECK (sampling_probability between 0.0 and 1.0),
> ```

nit: `s/between/BETWEEN/` and `s/and/AND/`.
___
*[`pkg/sql/stmtdiagnostics/statement_diagnostics.go` line 336 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82750#-N4bvqMr0KwjXBEz60Rc:-N4bvqMr0KwjXBEz60Rd:b-ysptj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5a0e11b92875b59e4c408e30855bae8b41628ed/pkg/sql/stmtdiagnostics/statement_diagnostics.go#L336)):*
> ```Go
> 		now := timeutil.Now()
> 		insertColumns := "statement_fingerprint, requested_at"
> 		qargs := make([]interface{}, 2, 4)
> ```

nit: this is minuscule, but let's bump capacity to 5.
___
*[`pkg/sql/stmtdiagnostics/statement_diagnostics.go` line 511 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82750#-N4bwXzi0KK3M3PS6m51:-N4bwXzi0KK3M3PS6m52:b205w65) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5a0e11b92875b59e4c408e30855bae8b41628ed/pkg/sql/stmtdiagnostics/statement_diagnostics.go#L511)):*
> ```Go
> 	}
> 
> 	if req.samplingProbability == 0 || rand.Float64() < req.samplingProbability {
> ```

Do you think it's safe (from the mutex contention point of view) to use the global random source? Maybe we should create a separate source for each `Request` when it has non-zero sampling probability?
___
*[`pkg/util/admission/stmt.zip` line 0 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82750#-N4bxl-O8gJok2ZY0pdy:-N4bxl-O8gJok2ZY0pdz:b-q0onf7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5a0e11b92875b59e4c408e30855bae8b41628ed/pkg/util/admission/stmt.zip#L0)):*
This file seems off.

**Review by irfansharif — COMMENTED** [review]
Added a test, PTAL.

> you were mentioning "backportable" prototypes to 22.1 and 21.2

Yea this PR can't be backported because of the migration. I was imagining something more like https://github.com/cockroachdb/cockroach/pull/82864 which introduces a set of cluster settings to replicate this functionality. I'll work on that separately. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82750#-:-N4dKAz13WnZXPRDPyNx:bj1nahd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @yuzefovich)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/82750#-N4bnRVp3oF2tlCsm_A4):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: do you wanna remove all of 22.1 migrations? It's ok if not - I personally get a lot of gratification from removing the code :)
</blockquote></details>

Too lazy :stuck_out_tongue: 
___
*[`pkg/sql/stmtdiagnostics/statement_diagnostics.go` line 511 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82750#-N4bwXzi0KK3M3PS6m51:-N4dNapEB7tuC6AtmAAS:bh95rf2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5a0e11b92875b59e4c408e30855bae8b41628ed/pkg/sql/stmtdiagnostics/statement_diagnostics.go#L511)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Do you think it's safe (from the mutex contention point of view) to use the global random source? Maybe we should create a separate source for each `Request` when it has non-zero sampling probability?
</blockquote></details>

Great catch! Looks like at the this point we're already under the Registry mutex, so changed it to use a per-Registry rand.Rand (with it's own source) instead.
___
*[`pkg/util/admission/stmt.zip` line  at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82750#-N4bxl-O8gJok2ZY0pdy:-N4dKoX037H26J5diqJX:b-675ezt) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5a0e11b92875b59e4c408e30855bae8b41628ed/pkg/util/admission/stmt.zip#L)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

This file seems off.
</blockquote></details>

Woops, removed.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82750#-:-N4dtoFh5t-iFXqxOOBn:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

**Comment by yuzefovich** [comment]
nit: don't forget to update the PR description.

**Comment by irfansharif** [comment]
Done, thanks!

bors r+

**Comment by tbg** [comment]
Nice! This is really useful.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82750)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[`pkg/cli/clisqlclient/statement_diag.go` line 107 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/82750#-N56h0pQBVzWJ1ZVTI4m:-N56h0pQBVzWJ1ZVTI4n:b542xbo) ([raw file](https://github.com/cockroachdb/cockroach/blob/19541357fa74af84adbf20561cb5794c611aa7dd/pkg/cli/clisqlclient/statement_diag.go#L107)):*
> ```Go
> 
> // TODO(irfansharif): Remove this in 23.1.
> func isAtLeast22dot2ClusterVersion(ctx context.Context, conn Conn) (bool, error) {
> ```

how come we don't look at `clusterversion.SampledStmtDiagReqs` ?

**Comment by irfansharif** [comment]
*[`pkg/cli/clisqlclient/statement_diag.go` line 107 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/82750#-N56h0pQBVzWJ1ZVTI4m:-N57LRad5Cx8FaukLABj:b7w0xb8) ([raw file](https://github.com/cockroachdb/cockroach/blob/19541357fa74af84adbf20561cb5794c611aa7dd/pkg/cli/clisqlclient/statement_diag.go#L107)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

how come we don't look at `clusterversion.SampledStmtDiagReqs` ?
</blockquote></details>

This is code running in the CLI where we don’t have gossiped cluster versions to check against. I guess we could've polled the cluster for the active version instead of checking the schema, but this felt reasonabl (the real reason is I was lazy and just cargo culted https://github.com/cockroachdb/cockroach/commit/077025470af81b32634880be250b92964ec1db05#diff-e32ce0eb18132e16e033d89268f1c7d5272b34e1db2f28290e3c55cf63085681L103-L104).

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82750)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[`pkg/cli/clisqlclient/statement_diag.go` line 107 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/82750#-N56h0pQBVzWJ1ZVTI4m:-N5Aqr--DDZjtS-xM9WS:b2nhysk) ([raw file](https://github.com/cockroachdb/cockroach/blob/19541357fa74af84adbf20561cb5794c611aa7dd/pkg/cli/clisqlclient/statement_diag.go#L107)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

This is code running in the CLI where we don’t have gossiped cluster versions to check against. I guess we could've polled the cluster for the active version instead of checking the schema, but this felt reasonabl (the real reason is I was lazy and just cargo culted https://github.com/cockroachdb/cockroach/commit/077025470af81b32634880be250b92964ec1db05#diff-e32ce0eb18132e16e033d89268f1c7d5272b34e1db2f28290e3c55cf63085681L103-L104).
</blockquote></details>

ack

**Pull request merged**
