### PR TITLE
cli: include crdb_internal.table_indexes in debug.zip

### PR DESCRIPTION
**Pull request by andreimatei**
Without this table, mapping an index id to the index name is all but
impossible.

Release note: None

### CODE REVIEW

**Comment by ajwerner** [comment]
All of the info used to derive this data is already in the debug zip. Do you still want it?

**Comment by ajwerner** [comment]
I sort of hate this. It can be very large.

**Review by andreimatei — COMMENTED** [review]
By included in the debug.zip, you mean in the form of the encoded system.descriptors.txt? Cause that one is not exactly readable...
Why do you say it can be large? Like, we already have all the schemas in different forms; larger than that?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69336#-:-Mhz4HVs7j5InpJS6BVu:b-qgtt1f)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

**Review by ajwerner — COMMENTED** [review]
Fair enough, I was thinking that this was the virtual table that has all of the columns for each index as a row, but that's `index_columns`. This one is okay. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69336#-:-Mhz4wC37dfC0bv8w6MJ:brmqhf5)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by ajwerner — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69336#-:-Mhz5G9D9FlMOSUp1KtH:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69336#-:-MjoiRx91uWflftzPJA-:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
