### PR TITLE
roachtest: add hibernate roachtest

### PR DESCRIPTION
**Pull request by BramGruneir**
This add a new roachtest that executes hibernate's test suite.

Specifically, it runs the hibernate-core test suite, in full and parses the 
results against a known blacklist of test failures.

It only requires a single node takes around 4 hours to complete.

It cannot be run locally.

This new test required allowing xml.Marshall/Unmarshall in our linter.  The first commit handles that.

Release note: None

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30565)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/hibernate.go, line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30565#-LNBUIZv04j5qy5ix0BN:-LNBUIZv04j5qy5ix0BO:b-xuksb5) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb137324296d9627200c677666a9affad20c3581/pkg/cmd/roachtest/hibernate.go#L50)):*
> ```Go
> 		c.GitClone(ctx, "https://github.com/hibernate/hibernate-orm.git", "/mnt/data1/hibernate", "5.3.6", node)
> 		c.Run(ctx, node, `sudo apt-get -q update`)
> 		c.Run(ctx, node, `yes | sudo apt-get -q install default-jre openjdk-8-jdk-headless gradle`)
> ```

I think the `yes |` is equivalent to `apt-get install -y`. The latter seems to be a slightly more direct way of specifying what you want.
___
*[pkg/cmd/roachtest/hibernate.go, line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30565#-LNBU_eMEqwXiC-9QVuJ:-LNBU_eMEqwXiC-9QVuK:bre4s1x) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb137324296d9627200c677666a9affad20c3581/pkg/cmd/roachtest/hibernate.go#L73)):*
> ```Go
> 		// test run command.
> 		// Note that this will take upwards of 3 hours.
> 		c.RunE(ctx, node, `cd /mnt/data1/hibernate/hibernate-core/ && ./../gradlew test -Pdb=cockroach`)
> ```

Nit: there are a number of lines in this file that exceed 100 columns which makes this more difficult to review in reviewable. 
___
*[pkg/cmd/roachtest/hibernate.go, line 98 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30565#-LNBV4fp0xrtc06Oy5eP:-LNBV4fp0xrtc06Oy5eQ:b-lcd3rd) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb137324296d9627200c677666a9affad20c3581/pkg/cmd/roachtest/hibernate.go#L98)):*
> ```Go
> 		if err != nil {
> 			t.Fatal(err)
> 		}
> ```

I think the above is more or less what `cluster.RunWithBuffer` does.
___
*[pkg/cmd/roachtest/hibernate.go, line 112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30565#-LNBVEX-71QkovdwPW1I:-LNBVEX-71QkovdwPW1J:b-ezxves) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb137324296d9627200c677666a9affad20c3581/pkg/cmd/roachtest/hibernate.go#L112)):*
> ```Go
> 			c.l.Printf("Parsing %d of %d: %s\n", i, len(files), file)
> 			fileCmd := exec.CommandContext(ctx, roachprod, "run", nodeString, `cat `+file)
> 			fileOutput, err := fileCmd.Output()
> ```

`RunWithBuffer` looks usable here as well.
___
*[pkg/cmd/roachtest/hibernate.go, line 140 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30565#-LNBVTk1ALc2RvQHplp1:-LNBVTk1ALc2RvQHplp2:bd0lvj) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb137324296d9627200c677666a9affad20c3581/pkg/cmd/roachtest/hibernate.go#L140)):*
> ```Go
> 		}
> 
> 		t.Status("writing results back to the cluster's logs")
> ```

I'm guessing you're doing this in order to populate the artifacts directory. Or is there another reason? If it is just to populate the artifacts directory, we should add a more direct mechanism. See `cluster.FetchLogs`. Adding another method such as `cluster.ArtifactsDir()` seems reasonable.
___
*[pkg/cmd/roachtest/hibernate.go, line 171 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30565#-LNBWCIm7hdTgRpJjTKy:-LNBWCIm7hdTgRpJjTKz:b-5foahc) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb137324296d9627200c677666a9affad20c3581/pkg/cmd/roachtest/hibernate.go#L171)):*
> ```Go
> 		writeResults(failExpected, "failExpected", false /* asGoArray */)
> 		writeResults(failUnexpected, "failUnexpected", false /* asGoArray */)
> 		writeResults(notRunExpectedFail, "notRunExpectedFail", false /* asGoArray */)
> ```

If I understand this correctly, you're writing separate files for each of these different types of pass and failure. I don't have a strong objection to this, though it does seem different than the normal Go test output (that roachtest also follows). These files aren't being interpreted anywhere, so perhaps that is ok, but it also doesn't seem hard to make them follow the `--- PASS: ...` and `--- FAIL: ...` format and to put all of the output in one file.
___
*[pkg/cmd/roachtest/hibernate_blacklist.go, line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30565#-LNBTp6jE-jEnG11_NYq:-LNBTp6jE-jEnG11_NYr:b-8n1q6w) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb137324296d9627200c677666a9affad20c3581/pkg/cmd/roachtest/hibernate_blacklist.go#L21)):*
> ```Go
> // When the hibernate test suite is run, the results are compared to this list.
> // Please keep this list alphabetized.
> // After a run, check out artifacts/hibernate/log/logs/report/hibernateBlackList.txt
> ```

Can you elaborate on what you're supposed to check in that file?

**Review by benesch — COMMENTED** [review]
The approach LGTM! I'll leave the review of the specifics to Peter.

> Reviewed 1 of 1 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30565#-:-LNBXcrM8C28kkyqsQQn:b-n5fmgb)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/hibernate.go, line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30565#-LNBUIZv04j5qy5ix0BN:-LNBX8PX4Nz54ogrt5_Q:b-hodfls) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb137324296d9627200c677666a9affad20c3581/pkg/cmd/roachtest/hibernate.go#L50)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think the `yes |` is equivalent to `apt-get install -y`. The latter seems to be a slightly more direct way of specifying what you want.
</blockquote></details>

`apt-get install -qy`, if you would! (This was copied from the cdc roachtest, if I'm not mistaken, which also uses this nonstandard pattern.)

**Review by BramGruneir — COMMENTED** [review]
Fixed the linter errors and all the nits.

Peter, let me know what you think I should do output-wise.  I can turn the whole thing into actual subtests, but I'm not sure that's the best approach.  I'm pretty amenable on this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30565#-:-LNBqbAI3d3KXxjWMy22:b-d4h3r6)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/hibernate.go, line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30565#-LNBUIZv04j5qy5ix0BN:-LNBXcVB7rTA3tFcapbY:b2qzzxa) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb137324296d9627200c677666a9affad20c3581/pkg/cmd/roachtest/hibernate.go#L50)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

`apt-get install -qy`, if you would! (This was copied from the cdc roachtest, if I'm not mistaken, which also uses this nonstandard pattern.)
</blockquote></details>

Indeed it was, I'll fix that one too.
___
*[pkg/cmd/roachtest/hibernate.go, line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30565#-LNBU_eMEqwXiC-9QVuJ:-LNBYaQQ3CxgR--anu5h:busb6cf) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb137324296d9627200c677666a9affad20c3581/pkg/cmd/roachtest/hibernate.go#L73)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Nit: there are a number of lines in this file that exceed 100 columns which makes this more difficult to review in reviewable. 
</blockquote></details>

Fixed.  
___
*[pkg/cmd/roachtest/hibernate.go, line 98 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30565#-LNBV4fp0xrtc06Oy5eP:-LNBZWob6hBSJLFppmce:b-4pj5my) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb137324296d9627200c677666a9affad20c3581/pkg/cmd/roachtest/hibernate.go#L98)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think the above is more or less what `cluster.RunWithBuffer` does.
</blockquote></details>

Nice, done.
___
*[pkg/cmd/roachtest/hibernate.go, line 112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30565#-LNBVEX-71QkovdwPW1I:-LNBZYqrAaAqgqo8Q-YD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb137324296d9627200c677666a9affad20c3581/pkg/cmd/roachtest/hibernate.go#L112)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`RunWithBuffer` looks usable here as well.
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/hibernate.go, line 140 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30565#-LNBVTk1ALc2RvQHplp1:-LNBZbQT9qGuKq9pdnBe:bpya3kh) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb137324296d9627200c677666a9affad20c3581/pkg/cmd/roachtest/hibernate.go#L140)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm guessing you're doing this in order to populate the artifacts directory. Or is there another reason? If it is just to populate the artifacts directory, we should add a more direct mechanism. See `cluster.FetchLogs`. Adding another method such as `cluster.ArtifactsDir()` seems reasonable.
</blockquote></details>

I wanted to put it back on the cluster because I found that after a failed run, it was useful to have it locally on the machine as well as in the artifacts directory.  These files are quite small, just lists of tests.  See my other comment about the `--- pass / --- fail:`.
___
*[pkg/cmd/roachtest/hibernate.go, line 171 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30565#-LNBWCIm7hdTgRpJjTKy:-LNBe-U2DyvPicyjQZfI:b-r7bmg0) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb137324296d9627200c677666a9affad20c3581/pkg/cmd/roachtest/hibernate.go#L171)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

If I understand this correctly, you're writing separate files for each of these different types of pass and failure. I don't have a strong objection to this, though it does seem different than the normal Go test output (that roachtest also follows). These files aren't being interpreted anywhere, so perhaps that is ok, but it also doesn't seem hard to make them follow the `--- PASS: ...` and `--- FAIL: ...` format and to put all of the output in one file.
</blockquote></details>

The only one that is designed to be directly parsed is the hibernateBlackList.txt.

As an alternative, I could instead create a subtest for each test, and have it pass or fail that way.  And skip this writing back of files entirely, except for the updated blacklist.  What do you think?

I would worry if there were suddenly a huge number of failures that turn into github issues.  Say all the tests fail for some reason, like if the cluster doesn't start correctly so all 6k test report as failed.
___
*[pkg/cmd/roachtest/hibernate_blacklist.go, line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30565#-LNBTp6jE-jEnG11_NYq:-LNBd9va0tWKT_Sjdrh0:b-sjnzml) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb137324296d9627200c677666a9affad20c3581/pkg/cmd/roachtest/hibernate_blacklist.go#L21)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Can you elaborate on what you're supposed to check in that file?
</blockquote></details>

Done.  It's just a fresh, "copy and paste"-able version of this blacklist.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30565)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/hibernate.go, line 140 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30565#-LNBVTk1ALc2RvQHplp1:-LNC-H3--Vl4tiLPPXN0:b-cxku8z) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb137324296d9627200c677666a9affad20c3581/pkg/cmd/roachtest/hibernate.go#L140)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

I wanted to put it back on the cluster because I found that after a failed run, it was useful to have it locally on the machine as well as in the artifacts directory.  These files are quite small, just lists of tests.  See my other comment about the `--- pass / --- fail:`.
</blockquote></details>

I'm not worried about the size. It just seemed awkward to do this. I'm curious why it is useful to have these files on the cluster node vs just locally.
___
*[pkg/cmd/roachtest/hibernate.go, line 171 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30565#-LNBWCIm7hdTgRpJjTKy:-LNC-SKhATYqUGjq3zjq:b-anqr6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb137324296d9627200c677666a9affad20c3581/pkg/cmd/roachtest/hibernate.go#L171)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

The only one that is designed to be directly parsed is the hibernateBlackList.txt.

As an alternative, I could instead create a subtest for each test, and have it pass or fail that way.  And skip this writing back of files entirely, except for the updated blacklist.  What do you think?

I would worry if there were suddenly a huge number of failures that turn into github issues.  Say all the tests fail for some reason, like if the cluster doesn't start correctly so all 6k test report as failed.
</blockquote></details>

I'm not sure how subtests would be used here. Usually, each subtest is running  something, but you're running all of the hibernate tests as once. Are you thinking you could run each hibernate test individually. That feels like overkill (thousands of subtests). And your point about github issues is good. We wouldn't want to accidentally created thousands of issues.

Rather than the individual files, I would have looped over the test results and printed them to `c.l` with lines like:

```
PASS: <test>
PASS: <test> (unexpected)
FAIL: <test> (expected)
FAIL: <test>
FAIL: <test> (not run)
```

This isn't quite the same format as what `go test` uses, but is visually similar. The `c.l` logger will redirect to the `test.log` file giving us one place to look for results.

**Review by BramGruneir — COMMENTED** [review]
Made the requested changes, PTAL.  I think this is good to merge.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30565#-:-LNGwm__BjaQsMATN6AZ:bvmd0ps)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/hibernate.go, line 140 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30565#-LNBVTk1ALc2RvQHplp1:-LNGwbIi1_PJwfDJtpCB:b-z0fbhj) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb137324296d9627200c677666a9affad20c3581/pkg/cmd/roachtest/hibernate.go#L140)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm not worried about the size. It just seemed awkward to do this. I'm curious why it is useful to have these files on the cluster node vs just locally.
</blockquote></details>

I've removed all the files except for the blacklist.
___
*[pkg/cmd/roachtest/hibernate.go, line 171 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30565#-LNBWCIm7hdTgRpJjTKy:-LNGwRI47E44hY8RfP7-:b2d0yg) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb137324296d9627200c677666a9affad20c3581/pkg/cmd/roachtest/hibernate.go#L171)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm not sure how subtests would be used here. Usually, each subtest is running  something, but you're running all of the hibernate tests as once. Are you thinking you could run each hibernate test individually. That feels like overkill (thousands of subtests). And your point about github issues is good. We wouldn't want to accidentally created thousands of issues.

Rather than the individual files, I would have looped over the test results and printed them to `c.l` with lines like:

```
PASS: <test>
PASS: <test> (unexpected)
FAIL: <test> (expected)
FAIL: <test>
FAIL: <test> (not run)
```

This isn't quite the same format as what `go test` uses, but is visually similar. The `c.l` logger will redirect to the `test.log` file giving us one place to look for results.
</blockquote></details>

Done.

```
--- PASS: org.hibernate.test.annotations.lob.ImageTest.testBoundedLongByteArrayAccess
--- PASS: org.hibernate.test.annotations.lob.LobTest.testBinary
--- FAIL: org.hibernate.test.annotations.lob.LobTest.testBlob (expected)
--- FAIL: org.hibernate.test.annotations.lob.LobTest.testClob (expected)
--- FAIL: org.hibernate.test.annotations.lob.LobTest.testSerializableToBlob (expected)
--- PASS: org.hibernate.test.annotations.lob.LobWithSequenceIdentityGeneratorTest.testLobInsertUpdateDeleteSelect
--- FAIL: org.hibernate.test.annotations.lob.MaterializedBlobTest.testSaving (expected)
--- PASS: org.hibernate.test.annotations.lob.MaterializedBlobTest.testTypeSelection
--- FAIL: org.hibernate.test.annotations.lob.SerializableToBlobTypeTest.testPersist (expected)
--- PASS: org.hibernate.test.annotations.lob.SerializableToBlobTypeTest.testTypeDefinition
--- PASS: org.hibernate.test.annotations.lob.TextTest.testBoundedLongStringAccess
--- PASS: org.hibernate.test.annotations.lob.VersionedLobTest.testBinary
--- FAIL: org.hibernate.test.annotations.lob.VersionedLobTest.testBlob (expected)
--- FAIL: org.hibernate.test.annotations.lob.VersionedLobTest.testClob (expected)
--- FAIL: org.hibernate.test.annotations.lob.VersionedLobTest.testSerializableToBlob
--- FAIL: org.hibernate.test.annotations.lob.VersionedLobTest.testVersionUnchangedByteArray (expected)
--- FAIL: org.hibernate.test.annotations.lob.VersionedLobTest.testVersionUnchangedCharArray (expected)
--- FAIL: org.hibernate.test.annotations.lob.VersionedLobTest.testVersionUnchangedPrimitiveByteArray (expected)
--- FAIL: org.hibernate.test.annotations.lob.VersionedLobTest.testVersionUnchangedPrimitiveCharArray (expected)
--- FAIL: org.hibernate.test.annotations.lob.VersionedLobTest.testVersionUnchangedString (expected)
--- PASS: org.hibernate.test.annotations.lob.hhh4635.LobTest.hibernateTest
--- PASS: org.hibernate.test.annotations.lob.locator.LobLocatorTest.testStreamResetBeforeParameterBinding
```

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30565#-:-LNHSIjX7rD1J0hL5o6W:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/hibernate.go, line 171 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30565#-LNBWCIm7hdTgRpJjTKy:-LNHRWZA7ygk4fTXzy7o:bkaf15p) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb137324296d9627200c677666a9affad20c3581/pkg/cmd/roachtest/hibernate.go#L171)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Done.

```
--- PASS: org.hibernate.test.annotations.lob.ImageTest.testBoundedLongByteArrayAccess
--- PASS: org.hibernate.test.annotations.lob.LobTest.testBinary
--- FAIL: org.hibernate.test.annotations.lob.LobTest.testBlob (expected)
--- FAIL: org.hibernate.test.annotations.lob.LobTest.testClob (expected)
--- FAIL: org.hibernate.test.annotations.lob.LobTest.testSerializableToBlob (expected)
--- PASS: org.hibernate.test.annotations.lob.LobWithSequenceIdentityGeneratorTest.testLobInsertUpdateDeleteSelect
--- FAIL: org.hibernate.test.annotations.lob.MaterializedBlobTest.testSaving (expected)
--- PASS: org.hibernate.test.annotations.lob.MaterializedBlobTest.testTypeSelection
--- FAIL: org.hibernate.test.annotations.lob.SerializableToBlobTypeTest.testPersist (expected)
--- PASS: org.hibernate.test.annotations.lob.SerializableToBlobTypeTest.testTypeDefinition
--- PASS: org.hibernate.test.annotations.lob.TextTest.testBoundedLongStringAccess
--- PASS: org.hibernate.test.annotations.lob.VersionedLobTest.testBinary
--- FAIL: org.hibernate.test.annotations.lob.VersionedLobTest.testBlob (expected)
--- FAIL: org.hibernate.test.annotations.lob.VersionedLobTest.testClob (expected)
--- FAIL: org.hibernate.test.annotations.lob.VersionedLobTest.testSerializableToBlob
--- FAIL: org.hibernate.test.annotations.lob.VersionedLobTest.testVersionUnchangedByteArray (expected)
--- FAIL: org.hibernate.test.annotations.lob.VersionedLobTest.testVersionUnchangedCharArray (expected)
--- FAIL: org.hibernate.test.annotations.lob.VersionedLobTest.testVersionUnchangedPrimitiveByteArray (expected)
--- FAIL: org.hibernate.test.annotations.lob.VersionedLobTest.testVersionUnchangedPrimitiveCharArray (expected)
--- FAIL: org.hibernate.test.annotations.lob.VersionedLobTest.testVersionUnchangedString (expected)
--- PASS: org.hibernate.test.annotations.lob.hhh4635.LobTest.hibernateTest
--- PASS: org.hibernate.test.annotations.lob.locator.LobLocatorTest.testStreamResetBeforeParameterBinding
```
</blockquote></details>

The output looks good. What order does hibernate run the tests? The `results` map and `allTests` is a bit excessive for sorted ordering unless hibernate is outputting test results in random order. Oh well, you've already done it, so no use removing it at this point.
___
*[pkg/cmd/roachtest/hibernate.go, line 163 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30565#-LNHSLEcA_tW3USgNm6G:-LNHSLEcA_tW3USgNm6H:b5dwxf) ([raw file](https://github.com/cockroachdb/cockroach/blob/117274b8f91f737806e669d51b9031f2783e458a/pkg/cmd/roachtest/hibernate.go#L163)):*
> ```Go
> 
> 		// Log all the test results.
> 		sort.Strings(allTests)
> ```

Perhaps add a comment that the hibernate results are in some order X, while we want to provide them in a deterministic order.
___
*[pkg/cmd/roachtest/hibernate.go, line 249 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30565#-LNHRJtJ935aQPdW8na3:-LNHRJtJ935aQPdW8na4:bbxeuph) ([raw file](https://github.com/cockroachdb/cockroach/blob/117274b8f91f737806e669d51b9031f2783e458a/pkg/cmd/roachtest/hibernate.go#L249)):*
> ```Go
> 	if len(testSuite.TestCases) > 1000000 {
> 		testSuite.XMLName = xml.Name{}
> 	}
> ```

What is the lint error here? I'v used the pattern `_ = testSuite.XMLName` to force linters to ignore unused warnings.

**Pull request merged**
