### PR TITLE
storage: removed unnecessary comment

### PR DESCRIPTION
**Pull request by BramGruneir**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13289)

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
LGTM

**Comment by RaduBerinde** [comment]
Typo in commit message (unnecessary).

**Comment by BramGruneir** [comment]
fixed typo

**Comment by tamird** [comment]
You left the typo in the commit message.

**Comment by BramGruneir** [comment]
fixed for reals this time

**Comment by tamird** [comment]
:+1:

**Pull request merged**
