### PR TITLE
rac2: use LogSlice semantics consistent with raft

### PR DESCRIPTION
**Pull request by pav-kv**
This PR converts the test-only implementation of the `LogSlice` method to behave exactly as the raft's `LogStorage` does. Specifically:

- The entry size is the proto `Size()` rather than `len(entry.Data)`
- The `maxSize` can not be exceeded unless the first entry is large

Both semantics can/should be changed in the future to what RACv2 previously assumed, but this PR eliminates the diff between the two in the short term so that the `rac2` tests are reflective of the real behaviour.

Epic: none
Release note: none

### CODE REVIEW

**Comment by pav-kv** [comment]
@sumeerbhola Probably best to review this one wholesale, without the commit separation. The diff is clearer that way.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 5 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132791#-:-O9PqpvL7458uDAYirlw:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pav-kv)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/send_q_watcher` line 181 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/132791#-O9PpZJN8TpjIPPU-W_C:-O9PpZJO1C-fgVyEQIjr:b7pld8n) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdc9e4d1489cef6f00193dc2707bd8a23f43fbc2/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/send_q_watcher#L181)):*
> ```
> 
> # Scheduler event. Only the first entry in the send-queue is sent, because the
> # second entry would exceed the max size limit.
> ```

can you add the following to the comment:
Replica 2 still have 512KiB of deducted tokens that are not used, and is waiting for a scheduler event.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller_test.go` line 449 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/132791#-O9PqOw41Kcv0rqH5IUz:-O9PqOw41Kcv0rqH5IV-:bs2ylpx) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdc9e4d1489cef6f00193dc2707bd8a23f43fbc2/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller_test.go#L449)):*
> ```Go
> 		if size >= maxSize {
> 			break
> 		}
> ```

nit: I don't think we need this second `size >= maxSize` for a test, since we don't care about the efficiency of an extra `entry.Size()`. On the other hand, if this code is lifted from raft package code, ok to make it identical here to ensure semantics are the same.

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132791)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/send_q_watcher` line 181 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/132791#-O9PpZJN8TpjIPPU-W_C:-O9QMFY42tArN8mWa3U7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdc9e4d1489cef6f00193dc2707bd8a23f43fbc2/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/send_q_watcher#L181)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can you add the following to the comment:
Replica 2 still have 512KiB of deducted tokens that are not used, and is waiting for a scheduler event.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller_test.go` line 449 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/132791#-O9PqOw41Kcv0rqH5IUz:-O9QMIha7t6DpZ6j_8kE:b6o7hjw) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdc9e4d1489cef6f00193dc2707bd8a23f43fbc2/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller_test.go#L449)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: I don't think we need this second `size >= maxSize` for a test, since we don't care about the efficiency of an extra `entry.Size()`. On the other hand, if this code is lifted from raft package code, ok to make it identical here to ensure semantics are the same.
</blockquote></details>

Left as is. Not an optimization, just mirroring the logic. If we remove this check, and `entry.Size()` is zero when we wrap around, we may add more entries than raft would do.

Don't know if that can happen though (probably only if everything is zero). But prefer not to overly depend on proto intrinsics and assume it can.

**Comment by pav-kv** [comment]
bors r=sumeerbhola

**Pull request merged**
