### PR TITLE
build: upgrade to Go 1.23.2

### LINKED ISSUE #129897: build: Update to go 1.23
Due primarily to the linking changes made in 1.23, this will be a more involved upgrade than usual.

This is a WIP patch that as of right now will not build. In addition I believe we need to update `x/tools`.

```
diff --git a/WORKSPACE b/WORKSPACE
index 474eec5eb9c..467a69026c2 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -8,12 +8,10 @@ load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
 # Load go bazel tools. This gives us access to the go bazel SDK/toolchains.
 http_archive(
     name = "io_bazel_rules_go",
-    sha256 = "ada68324bc20ffd1b557bab4cf8dba9b742570a46a505b0bc99c1fde5132cce5",
-    strip_prefix = "cockroachdb-rules_go-734c37d",
+    sha256 = "d93ef02f1e72c82d8bb3d5169519b36167b33cf68c252525e3b9d3d5dd143de7",
     urls = [
-        # cockroachdb/rules_go as of 734c37d6e2e6570f420d27fd97424b2fe2b402af
-        # (upstream release-0.46 plus a few patches).
-        "https://storage.googleapis.com/public-bazel-artifacts/bazel/cockroachdb-rules_go-v0.27.0-459-g734c37d.tar.gz",
+        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.49.0/rules_go-v0.49.0.zip",
+        "https://github.com/bazelbuild/rules_go/releases/download/v0.49.0/rules_go-v0.49.0.zip",
     ],
 )
 
@@ -91,9 +89,10 @@ go_deps()
 
 http_archive(
     name = "platforms",
-    sha256 = "079945598e4b6cc075846f7fd6a9d0857c33a7afc0de868c2ccb96405225135d",
+    sha256 = "218efe8ee736d26a3572663b374a253c012b716d8af0c07e842e82f238a0a7ee",
     urls = [
-        "https://storage.googleapis.com/public-bazel-artifacts/bazel/platforms-0.0.4.tar.gz",
+        "https://mirror.bazel.build/github.com/bazelbuild/platforms/releases/download/0.0.10/platforms-0.0.10.tar.gz",
+        "https://github.com/bazelbuild/platforms/releases/download/0.0.10/platforms-0.0.10.tar.gz",
     ],
 )
 
@@ -164,15 +163,7 @@ load(
 #
 go_download_sdk(
     name = "go_sdk",
-    sdks = {
-        "darwin_amd64": ("go1.22.5.darwin-amd64.tar.gz", "0eca73b33e9fc3b8eae28c4873b979f5ebd4b7dc8771b9b13ba2d70517309a4d"),
-        "darwin_arm64": ("go1.22.5.darwin-arm64.tar.gz", "2d72a9301bf73f5429cbc40ba08b6602b1af91a5d5eed302fef2b92ae53b0b56"),
-        "linux_amd64": ("go1.22.5.linux-amd64.tar.gz", "477ec7b6f76e6c38d83fbd808af0729299b40a8e99796ac3b2fec50d62e20938"),
-        "linux_arm64": ("go1.22.5.linux-arm64.tar.gz", "fbaf48b411d434aad694fddc8a036ce7374f2d8459518a25fec4f58f3bca0c20"),
-        "windows_amd64": ("go1.22.5.windows-amd64.tar.gz", "8fc3ccf439e93521faa0411702ef4e598c80ded514bada5fedc11846c284d3d2"),
-    },
-    urls = ["https://storage.googleapis.com/public-bazel-artifacts/go/20240708-162411/{}"],
-    version = "1.22.5",
+    version = "1.23.0",
 )
 
 # To point to a local SDK path, use the following instead. We'll call the
@@ -457,11 +448,9 @@ http_archive(
 
 http_archive(
     name = "rules_proto",
-    sha256 = "88b0a90433866b44bb4450d4c30bc5738b8c4f9c9ba14e9661deb123f56a833d",
-    strip_prefix = "rules_proto-b0cc14be5da05168b01db282fe93bdf17aa2b9f4",
-    urls = [
-        "https://storage.googleapis.com/public-bazel-artifacts/bazel/rules_proto-b0cc14be5da05168b01db282fe93bdf17aa2b9f4.tar.gz",
-    ],
+    sha256 = "303e86e722a520f6f326a50b41cfc16b98fe6d1955ce46642a5b7a67c11c0f5d",
+    strip_prefix = "rules_proto-6.0.0",
+    url = "https://github.com/bazelbuild/rules_proto/releases/download/6.0.0/rules_proto-6.0.0.tar.gz",
 )
 
 load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")
diff --git a/go.mod b/go.mod
index 08cb0a98176..9ffb7f84c9c 100644
--- a/go.mod
+++ b/go.mod
@@ -1,6 +1,6 @@
 module github.com/cockroachdb/cockroach
 
-go 1.22.5
+go 1.23.0
 
 // golang.org/x/* packages are maintained and curated by the go project, just
 // without the backwards compatibility promises the standard library, and thus

```

Jira issue: CRDB-41759

Epic CRDB-41921

### LINKED ISSUE #129900: ctxutil: Guard linkname of `context.cancelCtxKey` behind `bazel` build tag
This is an illegal use of `go:linkname` as of Go 1.23:

```
pkg/util/ctxutil/context.go
83://go:linkname context_cancelCtxKey context.cancelCtxKey
```

Assigning to dev-inf for now, but I don't think that team is the correct owner.

Part of #128922

Jira issue: CRDB-41761

Epic CRDB-41921

### LINKED ISSUE #129902: goschedstats: Gurad linknames of runtime.{allp,lock,unlock} behind bazel build tag
The following uses of `linkname` are disallowed in Go 1.23 and must be removed.

```
pkg/util/goschedstats/runtime_go1.23.go
168://go:linkname allp runtime.allp
174://go:linkname lock runtime.lock
177://go:linkname unlock runtime.unlock

pkg/util/goschedstats/runtime_go1.19.go
126://go:linkname allp runtime.allp
132://go:linkname lock runtime.lock
135://go:linkname unlock runtime.unlock

pkg/util/goschedstats/runtime_go1.20_21_22.go
160://go:linkname allp runtime.allp
166://go:linkname lock runtime.lock
169://go:linkname unlock runtime.unlock

```

Assigning to dev-inf for now, but I don't think that team is the correct owner.

Part of #128922

Jira issue: CRDB-41762

Epic CRDB-41921

### PR DESCRIPTION
**Pull request by rickystewart**
* [x] Adjust the Pebble tests to run in new version.
* [x] Update `build/teamcity/internal/release/build-and-publish-patched-go/impl.sh` with the new version and adjust SHA256 sums as necessary.
* [x] Adjust `GO_VERSION` and `GO_FIPS_COMMIT` for the FIPS Go toolchain ([source](./teamcity/internal/release/build-and-publish-patched-go/impl-fips.sh)).
* [x] Run the `Internal / Cockroach / Build / Toolchains / Publish Patched Go for Mac` build configuration in TeamCity with your latest version of the script above. Note the job depends on another job `Build and Publish Patched Go`. That job prints out the SHA256 of all tarballs, which you will need to copy-paste into `WORKSPACE` (see below). `Publish Patched Go for Mac` is an extra step that publishes the *signed* `go` binaries for macOS. That job also prints out the SHA256 of the Mac tarballs in particular.
* [x] Adjust `--@io_bazel_rules_go//go/toolchain:sdk_version` in [.bazelrc](../.bazelrc).
* [x] Bump the version in `WORKSPACE` under `go_download_sdk`. You may need to bump [rules_go](https://github.com/bazelbuild/rules_go/releases). Also edit the filenames listed in `sdks` and update all the hashes to match what you built in the step above.
* [x] Bump the version in `WORKSPACE` under `go_download_sdk` for the FIPS version of Go (`go_sdk_fips`).
* [ ] Run `./dev generate bazel` to refresh `distdir_files.bzl`, then `bazel fetch @distdir//:archives` to ensure you've updated all hashes to the correct value.
* [x] Bump the go version in `go.mod`.
* [x] Bump the default installed version of Go in `bootstrap-debian.sh` ([source](./bootstrap/bootstrap-debian.sh)).
* [ ] Replace other mentions of the older version of go (grep for `golang:<old_version>` and `go<old_version>`).

In addition to the upgrade, the following changes had to be made:

* Needed to ugprade `staticcheck` to a version that supported Go 1.23
* Needed to update `errcheck` to a version that supported Go 1.23
* Needed to update `gosnowflake` to work around an issue that manifested
  in the error "failed to parse CA certificate". Updating this to the
  latest version would have resulted in a ton of packages being upgraded
  which would increase the risk of this change proportionally. Instead,
  I opted for a smaller jump plus the addition of a patch that applies
  https://github.com/snowflakedb/gosnowflake/commit/f33dfc7eb567.

Epic: CRDB-41921
Release note (build change): Upgrade to Go 1.23.2

Closes: https://github.com/cockroachdb/cockroach/issues/129900
Closes: https://github.com/cockroachdb/cockroach/issues/129897
Closes: https://github.com/cockroachdb/cockroach/issues/129902

### CODE REVIEW

**Comment by rickystewart** [comment]
This is ready for review but I'm going to come back tomorrow with a fresh set of eyes to make sure all my t's are crossed and i's dotted, all the developer tooling still works, error messages still look OK, etc.

**Review by rail — APPROVED** [review]
The changes look good to me. Not sure why one of the unit tests fail though 🤔

**Review by fqazi — APPROVED** [review]
Reviewed the keep alive changes these are good.

**Comment by rickystewart** [comment]
TFTRs!

bors r=rail,fqazi

**Pull request merged**
