### PR TITLE
distsql: Remove algebraicSetOp processor

### PR DESCRIPTION
**Pull request by abhimadan**
Originally, algebraicSetOp was intended to be used for set operation
queries. However, the physical planner uses joins to plan EXCEPT and
INTERSECT queries, so this processor is no longer necessary. This commit
removes the processor.

Release note: None

### CODE REVIEW

**Comment by abhimadan** [comment]
Not sure if this change requires a distsql version bump.

**Comment by arjunravinarayan** [comment]
It does!

**Comment by arjunravinarayan** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/distsqlrun/processors.proto, line 123 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23029#-L63lbjwbH2QLuv_jPsO:-L63lbjwbH2QLuv_jPsP:b-dq8hfl) ([raw file](https://github.com/cockroachdb/cockroach/blob/62b36e64d8703a6f87dff9d5bb3f22eb34a67b04/pkg/sql/distsqlrun/processors.proto#L123)):*
> ```protobuf
>   optional ValuesCoreSpec values = 10;
>   optional BackfillerSpec backfiller = 11;
>   optional AlgebraicSetOpSpec setOp = 12;
> ```

you need to reserve this value. in effect, `12` can never be used again. See https://developers.google.com/protocol-buffers/docs/proto#reserved
There are other examples in our proto files if you grep for `reserved`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23029)*

**Comment by abhimadan** [comment]
Review status: 5 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/distsqlrun/processors.proto, line 123 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23029#-L63lbjwbH2QLuv_jPsO:-L63ttMBKe2bSYYFL3Xw:b-j0okfh) ([raw file](https://github.com/cockroachdb/cockroach/blob/62b36e64d8703a6f87dff9d5bb3f22eb34a67b04/pkg/sql/distsqlrun/processors.proto#L123)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

you need to reserve this value. in effect, `12` can never be used again. See https://developers.google.com/protocol-buffers/docs/proto#reserved
There are other examples in our proto files if you grep for `reserved`.
</blockquote></details>

TIL about reserved protobuf values. Marked as reserved.

I noticed that 6 was also missing, and through some digging, I found that it was the Evaluator processor spec (removed in #13120) and not a value skip, so I've marked that as reserved too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23029)*

**Comment by arjunravinarayan** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/distsqlrun/processors.proto, line 123 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23029#-L63lbjwbH2QLuv_jPsO:-L6IZTS3vjpLFqS6B-EA:b-73m6vw) ([raw file](https://github.com/cockroachdb/cockroach/blob/62b36e64d8703a6f87dff9d5bb3f22eb34a67b04/pkg/sql/distsqlrun/processors.proto#L123)):*
<details><summary><i>Previously, abhimadan (Abhishek Madan) wrote…</i></summary><blockquote>

TIL about reserved protobuf values. Marked as reserved.

I noticed that 6 was also missing, and through some digging, I found that it was the Evaluator processor spec (removed in #13120) and not a value skip, so I've marked that as reserved too.
</blockquote></details>

Nice catch!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23029#-:-L6IZmXc9Si4qd_Q-ehn:bnfp4nl)*

**Comment by andreimatei** [comment]
@arjunravinarayan , I believe this didn't require a DistSQL version bump - I believe the change is backwards compatible.
I'll cherry-pick it in 2.0 so it doesn't become the first (and potentially only) version bump in 2.0->2.1.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23029#-:-L7k163QMfyus-xaL5wH:b8nezg3)*

**Pull request merged**
