### PR TITLE
tree: cleanup time type formatting

### LINKED ISSUE #41563: sql: differing TIMESTAMPTZ::TEXT output with respect to postgres
Ran into this while running the `lib/pq` tests:
Postgres:
```
asubiotto=# SET timezone='Etc/UTC';
asubiotto=# SELECT ('2001-02-03 BC'::timestamptz)::text;
           text            
---------------------------
 2001-02-03 00:00:00+00 BC
(1 row)
```
Cockroach:
```
root@:26257/defaultdb> SELECT ('2001-02-03 BC'::timestamptz)::text;
             text
+----------------------------+
  -2000-02-03 00:00:00+00:00
(1 row)
```

Jira issue: CRDB-5434

### PR DESCRIPTION
**Pull request by otan**
fixes https://github.com/cockroachdb/cockroach/issues/41563

Remove all the duplicate time formatting solutions from tree,
centralising on `Format` / `PGWireFormat` instead.

Release note (bug fix): We previously have included the minute/second
offset for TimestampTZ in certain places when casting it to string even
when they were zero. This does not match PostgreSQL and now has been resolved.

Release note (bug fix): We previously used negative years instead of BC
when casting a timestamptz to a string. This has now been resolved.

### CODE REVIEW

**Review by HonoreDB — APPROVED** [review]
CDC output change is fine, only affects cdc transformations which are in preview.

**Review by rafiss — APPROVED** [review]
cool to see this!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96833#-:-NNrY_Rr1Tx7AzO4FLmg:bai3b37)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @otan, and @shermanCRL)

___
*[`pkg/sql/sem/tree/pgwire_encode.go` line 332 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96833#-NNrYUS-EtWpylCsDSNQ:-NNrYUS-EtWpylCsDSNR:bfdftoo) ([raw file](https://github.com/cockroachdb/cockroach/blob/2938d3322fdc160efa0d47bc7e00df9d553df246/pkg/sql/sem/tree/pgwire_encode.go#L332)):*
> ```Go
> 
> // PGWireFormatTimestamp formats t into a format lib/pq understands.
> // If offset is not nil, it
> ```

just noticed an unfinished sentence
___
*[`pkg/sql/sem/tree/pgwire_encode.go` line 333 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96833#-NNrYRuSEhXPXM7yibDN:-NNrYRuT2oSGz5b21SbJ:b-d8uxro) ([raw file](https://github.com/cockroachdb/cockroach/blob/2938d3322fdc160efa0d47bc7e00df9d553df246/pkg/sql/sem/tree/pgwire_encode.go#L333)):*
> ```Go
> // PGWireFormatTimestamp formats t into a format lib/pq understands.
> // If offset is not nil, it
> // TODO(#sql-sessions): merge implementation with DTimestamp/DTimestampTZ.Format.
> ```

nit: we can remove this todos now, right?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96833)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @rafiss, and @shermanCRL)

___
*[`pkg/sql/sem/tree/pgwire_encode.go` line 332 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96833#-NNrYUS-EtWpylCsDSNQ:-NNrrGaV5lZDRNXmmM15:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2938d3322fdc160efa0d47bc7e00df9d553df246/pkg/sql/sem/tree/pgwire_encode.go#L332)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

just noticed an unfinished sentence
</blockquote></details>

Done.

**Comment by otan** [comment]
tftr!

bors r=rafiss

**Pull request merged**
