### PR TITLE
kvserver: get rid of bespoke relocation logic used by the mergeQueue

### LINKED ISSUE #62370: kvserver: update AdminRelocateRange to use explicit swaps of voters and non-voters
`AdminRelocateRange` currently doesn’t make use of the ability to [promote non-voters to voters, demote voters to non-voters or swap voters and non-voters](https://github.com/cockroachdb/cockroach/pull/58627). Because of this limitation, the [mergeQueue has to resort to a fairly complex way](https://github.com/cockroachdb/cockroach/blob/df1c620dc4d95a9e598ff852753d3a7e61d01cb6/pkg/kv/kvserver/replica_command.go#L2489) of determining which targets to relocate a range’s replicas to during a merge in order to avoid redundant data movement.

There are a few problems with this:
- With the ability to swap replica types, the complexity mentioned above is unnecessary. We can avoid redundant data movement by performing all the promotions / demotions / swaps and _then_ relocating the rest of the misaligned replicas.
- The merge queue relocation code was written before https://github.com/cockroachdb/cockroach/pull/57184. We’ve since introduced the concept of `voter_constraints` which govern the constraints over just the set of voting replicas.  This means that the relocation algorithm computes results that may not necessarily meet the {voter_}constraints placed over the RHS. In such cases, the range merge will fail. 
- It also has this limitation: https://github.com/cockroachdb/cockroach/blob/df1c620dc4d95a9e598ff852753d3a7e61d01cb6/pkg/kv/kvserver/replica_command.go#L2547-L2559

We need to update `AdminRelocateRange` to use the aforementioned voter<->non-voter swaps and simply have the merge queue directly call into it, instead of having it perform its own calculation of where to move the {voter,non-voter} replicas.

### PR DESCRIPTION
**Pull request by aayushshah15**
This PR contains two main commits:

**kvserver: update `AdminRelocateRange` to leverage explicit swaps of
voters to non-voters**

This commit updates `AdminRelocateRange` to use explicit atomic swaps of
voting replicas with non-voting replicas, that #58627 initially added
support for. The patch does so by generalizing behavior that's already
exercised by the `replicateQueue` when it decides to rebalance replicas.
See #61239.

This allows us, in the next commit, to remove bespoke relocation logic
that's used by the `mergeQueue` to align replica sets for the sake of a
range merge.

Release note: None

**kvserver: get rid of bespoke relocation logic used by the mergeQueue**

This commit removes the relocation logic used by the `mergeQueue` thus
far to align replica sets (added in #56197). This logic previously
existed in order to allow us to align the replica sets of a pair of
ranges (which is required for the range merge to proceed), while
avoiding redundant data movement.

Before #58627 and the previous commit in this PR, `AdminRelocateRange`
couldn't be directly used by the mergeQueue under various configurations
of the LHS and RHS ranges. Furthermore, even when it could be used, it
would involve redundant data movement. This all required us to compute
relocation targets for the RHS of a merge separately, above the call to
`AdminRelocateRange`, for the range merge to proceed.

All these limitations have been resolved by the previous commit which
teaches `AdminRelocateRange` to promote non-voters and demote voters
when needed, and the aforementioned bespoke relocation logic is no
longer needed.

Resolves #62370

Release note: None

### CODE REVIEW

**Comment by aayushshah15** [comment]
I'm going to add a randomized test (that just issues a bunch of random calls to `AdminRelocateRange`) -- kinda like https://github.com/cockroachdb/cockroach/blob/7899744d137334e8337e3bc3122f816c141ed7b5/pkg/kv/kvserver/replicate_queue_test.go#L655. Feel free to hold off on reviewing until then if you'd prefer.

**Review by nvb — CHANGES_REQUESTED** [review]
Very satisfying!

> Reviewed 1 of 1 files at r1, 4 of 4 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62631#-:-MWk1uhfA703-IvjYThs:b-jmlher)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @andreimatei)

___
*[pkg/kv/kvserver/allocator.go, line 193 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62631#-MWjy2Nd8DV8bv6HoV20:-MWjy2Nd8DV8bv6HoV21:b-dlu7p0) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f714fa17fe316af12589a91497048ced766fe1a/pkg/kv/kvserver/allocator.go#L193)):*
> ```Go
> // targetReplicaType.{Add,Remove}ChangeType methods wherever possible.
> func (t targetReplicaType) AddChangeType() roachpb.ReplicaChangeType {
> 	switch typ := t; typ {
> ```

Is there a reason for the value assignment in these switch statements? Would `switch t {` accomplish the same thing with less code and less room for confusion?
___
*[pkg/kv/kvserver/allocator.go, line 205 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62631#-MWjyiERDPMhVxYfdCu9:-MWjyiERDPMhVxYfdCuA:b-wm62p0) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f714fa17fe316af12589a91497048ced766fe1a/pkg/kv/kvserver/allocator.go#L205)):*
> ```Go
> // RemoveChangeType returns the roachpb.ReplicaChangeType corresponding to the
> // given targetReplicaType.
> func (t targetReplicaType) RemoveChangeType() roachpb.ReplicaChangeType {
> ```

Can we use this in `replicateQueue.removeDead`?
___
*[pkg/kv/kvserver/client_merge_test.go, line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62631#-MWjyJK1C1QyBrtyNHH8:-MWjyJK20oH7MEuCI4Lk:b-b2koxa) ([raw file](https://github.com/cockroachdb/cockroach/blob/cafa371d9554c7af0b5bb9082356f402af0c65d2/pkg/kv/kvserver/client_merge_test.go#L21)):*
> ```Go
> 	"reflect"
> 	"regexp"
> 	"sort"
> ```

I'm surprised to see an import change with no other code changes. Does this commit compile?
___
*[pkg/kv/kvserver/replica_command.go, line 2469 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62631#-MWk1orE1I8N_6-0Do_s:-MWk1orE1I8N_6-0Do_t:bmi8ppe) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f714fa17fe316af12589a91497048ced766fe1a/pkg/kv/kvserver/replica_command.go#L2469)):*
> ```Go
> }
> 
> // GetTargetsToCollocateRHSForMerge decides the configuration of RHS replicas
> ```

:100: 
___
*[pkg/kv/kvserver/replica_command.go, line 2875 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62631#-MWjznlzChrEQk4diZWh:-MWjznlzChrEQk4diZWi:b-kpm388) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f714fa17fe316af12589a91497048ced766fe1a/pkg/kv/kvserver/replica_command.go#L2875)):*
> ```Go
> 			StoreID: targetStore.StoreID,
> 		}
> 		if args.targetType == voterTarget {
> ```

Was there a reason to separate this block out from the next? Do you find it easier to read?

If we merged them, we could avoid scanning through the replicas twice, and could instead of a single iteration through `existingNonVoters`.
___
*[pkg/kv/kvserver/replica_command.go, line 3001 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62631#-MWk0jy8Ee50mkVzhTOP:-MWk0jy8Ee50mkVzhTOQ:b-51vwm7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f714fa17fe316af12589a91497048ced766fe1a/pkg/kv/kvserver/replica_command.go#L3001)):*
> ```Go
> 		// (Note that !shouldRemove implies that we're trying to remove the last
> 		// replica left in the descriptor which is illegal).
> 		ops = append(ops, roachpb.MakeReplicationChanges(args.targetType.RemoveChangeType(), removalTarget)...)
> ```

Why the `append` here?
___
*[pkg/kv/kvserver/replicate_queue.go, line 1130 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62631#-MWk1Ias8jciKE4_MnRo:-MWk1Ias8jciKE4_MnRp:bs17ign) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f714fa17fe316af12589a91497048ced766fe1a/pkg/kv/kvserver/replicate_queue.go#L1130)):*
> ```Go
> 				return false, err
> 			}
> 			if performingSwap {
> ```

nit: consider pulling this below `rq.metrics.RebalanceReplicaCount.Inc(1)` so that the non-conditional metric comes first and the conditional metrics come after.
___
*[pkg/kv/kvserver/replicate_queue.go, line 1221 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62631#-MWk10ca5KxFhVxOpoHc:-MWk10ca5KxFhVxOpoHd:b-28ur2q) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f714fa17fe316af12589a91497048ced766fe1a/pkg/kv/kvserver/replicate_queue.go#L1221)):*
> ```Go
> 		}
> 		log.VEventf(ctx, 1, "can't swap replica due to lease; falling back to add")
> 		return chgs, performingSwap, err
> ```

nit: we generally prefer returning a constant instead of a named return variable when the value is known. It makes things easier to read. So this would be `return chgs, false, err`.

**Review by aayushshah15 — COMMENTED** [review]
I cleaned some things up and added a bunch more testing -- all in the second commit. Should be RFAL.  

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62631#-:-MWlDMi_CXhA-gf29LgH:b-x83z3u)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @andreimatei, and @nvanbenschoten)

___
*[pkg/kv/kvserver/allocator.go, line 193 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62631#-MWjy2Nd8DV8bv6HoV20:-MWlCUjdERh4kr2acoMf:b5qx0y4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f714fa17fe316af12589a91497048ced766fe1a/pkg/kv/kvserver/allocator.go#L193)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is there a reason for the value assignment in these switch statements? Would `switch t {` accomplish the same thing with less code and less room for confusion?
</blockquote></details>

No reason. Fixed now. 
___
*[pkg/kv/kvserver/allocator.go, line 205 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62631#-MWjyiERDPMhVxYfdCu9:-MWlCb4F9RQ4LSGTjDS5:b-1sgfmr) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f714fa17fe316af12589a91497048ced766fe1a/pkg/kv/kvserver/allocator.go#L205)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can we use this in `replicateQueue.removeDead`?
</blockquote></details>

Done there and in `removeDecommissioning`.
___
*[pkg/kv/kvserver/client_merge_test.go, line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62631#-MWjyJK1C1QyBrtyNHH8:-MWlCedBD_JUDP9VMEBy:b9v4iqj) ([raw file](https://github.com/cockroachdb/cockroach/blob/cafa371d9554c7af0b5bb9082356f402af0c65d2/pkg/kv/kvserver/client_merge_test.go#L21)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm surprised to see an import change with no other code changes. Does this commit compile?
</blockquote></details>

Messed up while re-organizing my changes. Fixed now.
___
*[pkg/kv/kvserver/replica_command.go, line 2875 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62631#-MWjznlzChrEQk4diZWh:-MWlCxtx8LQVvDmyduFB:b-qurqt1) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f714fa17fe316af12589a91497048ced766fe1a/pkg/kv/kvserver/replica_command.go#L2875)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Was there a reason to separate this block out from the next? Do you find it easier to read?

If we merged them, we could avoid scanning through the replicas twice, and could instead of a single iteration through `existingNonVoters`.
</blockquote></details>

That wasn't intentional, fixed.
___
*[pkg/kv/kvserver/replica_command.go, line 3001 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62631#-MWk0jy8Ee50mkVzhTOP:-MWlDIMG2uMP51MhRxB-:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f714fa17fe316af12589a91497048ced766fe1a/pkg/kv/kvserver/replica_command.go#L3001)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why the `append` here?
</blockquote></details>

Fixed.
___
*[pkg/kv/kvserver/replicate_queue.go, line 1130 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62631#-MWk1Ias8jciKE4_MnRo:-MWlDKMH8D15knoZLXV0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f714fa17fe316af12589a91497048ced766fe1a/pkg/kv/kvserver/replicate_queue.go#L1130)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: consider pulling this below `rq.metrics.RebalanceReplicaCount.Inc(1)` so that the non-conditional metric comes first and the conditional metrics come after.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replicate_queue.go, line 1221 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62631#-MWk10ca5KxFhVxOpoHc:-MWlDLVw1FvHQlUVsVeT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f714fa17fe316af12589a91497048ced766fe1a/pkg/kv/kvserver/replicate_queue.go#L1221)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: we generally prefer returning a constant instead of a named return variable when the value is known. It makes things easier to read. So this would be `return chgs, false, err`.
</blockquote></details>

Done.

**Comment by aayushshah15** [comment]
The new randomized test I added is flaking because it also asserts that `AdminRelocateRange` moved [the lease to the first voter](https://github.com/cockroachdb/cockroach/blob/d2deebe969dbabb834292c78f76bb558d3b73265/pkg/kv/kvserver/client_relocate_range_test.go#L53) in the given list of `voterTargets`. However, under stress sometimes the leaseholder node misses a liveness heartbeat, which ends up failing the test. I think maybe a 9 node `TestCluster` is a bit too much. I'm stressing with a 6 node `TestCluster` to see how that goes. If that doesn't do the trick, I thinking we can do away with the leaseholder check under `stress`.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 6 of 7 files at r4, 7 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62631#-:-MWyTVIr8WqSTYzCQabu:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15 and @andreimatei)

___
*[pkg/kv/kvserver/replica_command.go, line 2875 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62631#-MWjznlzChrEQk4diZWh:-MWyScgw1V8zvWj7gusa:b-30sstw) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f714fa17fe316af12589a91497048ced766fe1a/pkg/kv/kvserver/replica_command.go#L2875)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

That wasn't intentional, fixed.
</blockquote></details>

We're still searching for the non-voter twice, once with `GetReplicaDescriptor` and once with an iteration over `existingNonVoters`. Should we avoid that?
___
*[pkg/kv/kvserver/replica_command.go, line 2957 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/62631#-MWySxiH-l2tzvQT4sUU:-MWySxiH-l2tzvQT4sUV:b-3n079k) ([raw file](https://github.com/cockroachdb/cockroach/blob/74b6ec95345d4b46380871d2b0172a4fb7d22597/pkg/kv/kvserver/replica_command.go#L2957)):*
> ```Go
> 		}
> 	} else if shouldAdd {
> 		ops = roachpb.MakeReplicationChanges(args.targetType.AddChangeType(), additionTarget)
> ```

It's probably better to avoid setting `ops` if we're just going to immediately overwrite it on the `canPromoteNonVoter`/`canDemoteVoter` paths. This is currently a bit misleading and looks error-prone.

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62631)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_command.go, line 2875 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62631#-MWjznlzChrEQk4diZWh:-MWzIJHN7clTpUaRTwgc:b-skhluo) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f714fa17fe316af12589a91497048ced766fe1a/pkg/kv/kvserver/replica_command.go#L2875)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We're still searching for the non-voter twice, once with `GetReplicaDescriptor` and once with an iteration over `existingNonVoters`. Should we avoid that?
</blockquote></details>

Ugh, sorry for being careless!

Fixed for real now. 
___
*[pkg/kv/kvserver/replica_command.go, line 2957 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/62631#-MWySxiH-l2tzvQT4sUU:-MWzIR5mD79muKGE-Rnz:bnz2g29) ([raw file](https://github.com/cockroachdb/cockroach/blob/74b6ec95345d4b46380871d2b0172a4fb7d22597/pkg/kv/kvserver/replica_command.go#L2957)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It's probably better to avoid setting `ops` if we're just going to immediately overwrite it on the `canPromoteNonVoter`/`canDemoteVoter` paths. This is currently a bit misleading and looks error-prone.
</blockquote></details>

Done (this is what you meant, right?).

**Review by nvb — COMMENTED** [review]
> Reviewed 5 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62631)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15 and @andreimatei)

___
*[pkg/kv/kvserver/replica_command.go, line 2957 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/62631#-MWySxiH-l2tzvQT4sUU:-MWzah0-6ibjfAUyjx6S:b-1vijnd) ([raw file](https://github.com/cockroachdb/cockroach/blob/74b6ec95345d4b46380871d2b0172a4fb7d22597/pkg/kv/kvserver/replica_command.go#L2957)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Done (this is what you meant, right?).
</blockquote></details>

Exactly.
___
*[pkg/kv/kvserver/replica_command.go, line 2847 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/62631#-MWzaYUp3qGZbbOAOK2p:-MWzaYUp3qGZbbOAOK2q:b-s0hve2) ([raw file](https://github.com/cockroachdb/cockroach/blob/db731982a66a29e68e6952b673b435d84b5fd339/pkg/kv/kvserver/replica_command.go#L2847)):*
> ```Go
> 				}
> 			}
> 			if promotionTargetIdx >= 0 {
> ```

Do we need `promotionTargetIdx`? Can we just move this condition into the loop?

**Review by aayushshah15 — COMMENTED** [review]
Thanks for being patient with me for these last few comments, and thanks for the review. 

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62631#-:-MWzc4rr0tQ-0f7_GPue:bham068)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_command.go, line 2847 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/62631#-MWzaYUp3qGZbbOAOK2p:-MWzbwB08uZ2KGtOZt6j:b-xswa6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/db731982a66a29e68e6952b673b435d84b5fd339/pkg/kv/kvserver/replica_command.go#L2847)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we need `promotionTargetIdx`? Can we just move this condition into the loop?
</blockquote></details>

Moved it into the loop.

**Review by nvb — APPROVED** [review]
> Reviewed 5 of 5 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62631)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei)

**Pull request merged**
