### PR TITLE
server: start jobs registry before running startup migrations

### PR DESCRIPTION
**Pull request by dt**
This contains two changes: one bakes in the startup migration that adds the `progress` column and family to the jobs table, and the other moves the execution of startup migrations to after the jobs registry has been started.

The later is important since migrations themselves often run commands such as REVOKE or CREATE TABLE that themselves can spawn jobs.

Release note: none.

### CODE REVIEW

**Review by spaskob — APPROVED** [review]
Thanks for taking care of this!
Please stress test `jobs_test.go` locally - it has helped me uncover a lot of subtle issues with jobs.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45828#-:-M1o1ePqAI99Mm6-_eTl:bqt4xa1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @lucy-zhang, and @spaskob)

**Comment by dt** [comment]
`403 runs so far, 0 failures, over 7m30s`

**Comment by dt** [comment]
@lucy-zhang I tested this locally on top of 497f15e and it looked like the startup deadlock is gone

**Comment by lucy-zhang** [comment]
Thanks for dealing with this.

**Pull request merged**
