### PR TITLE
sql: Fix panic adding unique, non-indexable column

### LINKED ISSUE #26483: sql: panic: add column T[] unique
`create table t(); alter table t ADD COLUMN c int[] UNIQUE;`

panic while executing 1 statements: ALTER TABLE _ ADD COLUMN _ INT[] UNIQUE; caused by unimplemented: column c is of type ARRAY and thus is not indexable

Found with RSG.

### PR DESCRIPTION
**Pull request by bobvawter**
This change updates the `checkColumnsFor...Index` functions to use
`allNonDropColumns()` to validate against any proposed mutations.  Otherwise, a
`ColumnMutation` that adds a non-indexable column followed by an
`IndexMutation` creating an index on that column would would be incorrectly
accepted, leading to a panic.

Fixes #26483

Release note (sql change): Return an error to the user instead of panicing when
trying to add a column with a unique constraint when that column's type is not
indexable.

### CODE REVIEW

**Review by madelynnblue — COMMENTED** [review]
My concern from a high level is that this is an unsafe API for us to use. The change here makes it safe by going through a special path because we have special knowledge of how to do things in the right order.

Is there a solution which makes the invalid state impossible to produce using the public API?

**Comment by vivekmenezes** [comment]
I'd add a test that adds the same column type and an index as two statements in the same transaction.

I wonder if this problem can be fixed by allowing the index to be added but then changing 
```func (desc *TableDescriptor) ValidateTable(``` to check for this problem by including the column mutations in the check.

**Comment by knz** [comment]
@bobvawter as commented on the linked issue, this bug is not specific to arrays, it is general to any non-indexable type. That includes json, for example. I recommend updating the commit title and PR title accordingly, for clarity in the git history.

**Comment by bobvawter** [comment]
PTAL: I found a much simpler way to do this by just using `allNonDropColumns()`; updated the test to also check `ADD COLUMN; CREATE INDEX` in a transaction; revised the commit message.

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26684#-:-LEybrnEC4pzt-c_thsz:bak1483)*

**Comment by knz** [comment]
:lgtm: very nice find.

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26684#-:-LEypejB1ptZV2UtSyKf:b-63nbwz)*

**Pull request merged**
