### PR TITLE
sql/pgwire: use OIDs when encoding some datum types

### PR DESCRIPTION
**Pull request by madelynnblue**
Teach pgwire how to encode int and float with the various widths. Do
this by saving the oids during SetColumns.

Teach cmd/generate-binary to also record oids and use those in tests.

Fix varbits to expect the same OID as postgres produces.

Sadly, our int2 and int4 types don't yet propagate all the way down
and so we still encode them as an int8. This commit is a precursor to
supporting that.

Release note: None

### CODE REVIEW

**Review by knz — APPROVED** [review]
:lgtm: thanks!

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34818#-:-LYVzJpf5bJ-q0Txnjuc:brfqlux)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bobvawter)

**Review by bobvawter — APPROVED** [review]
:lgtm: w/ nits.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34818#-:-LYX67wE2-3bs5rFiTcH:b-1ewmqt)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mjibson)

___
*[pkg/sql/pgwire/command_result.go, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34818#-LYX5j0F0Epm73d214j4:-LYX5j0F0Epm73d214j5:b-ha0xbn) ([raw file](https://github.com/cockroachdb/cockroach/blob/10af5d7b8a28630b6aaa5e7ed58d9835ecc6026b/pkg/sql/pgwire/command_result.go#L81)):*
> ```Go
> 	formatCodes []pgwirebase.FormatCode
> 
> 	oids []oid.Oid
> ```

Document this. I'm assuming it's a map of column index to `Oid` like `formatCodes`?
___
*[pkg/sql/pgwire/types.go, line 248 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34818#-LYX5Dkf925hXsXttBae:-LYX5Dkf925hXsXttBaf:b-g8hh29) ([raw file](https://github.com/cockroachdb/cockroach/blob/10af5d7b8a28630b6aaa5e7ed58d9835ecc6026b/pkg/sql/pgwire/types.go#L248)):*
> ```Go
> 			b.putInt32(8)
> 			b.putInt64(int64(*v))
> 		default:
> ```

Do you need to detect the `Oid == 0` case in order for the doc comment to be correct?

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34818)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @bobvawter and @knz)

___
*[pkg/sql/pgwire/command_result.go, line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34818#-LYX5j0F0Epm73d214j4:-LYY0cEr56hse3HPKFTB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/10af5d7b8a28630b6aaa5e7ed58d9835ecc6026b/pkg/sql/pgwire/command_result.go#L81)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Document this. I'm assuming it's a map of column index to `Oid` like `formatCodes`?
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/types.go, line 248 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34818#-LYX5Dkf925hXsXttBae:-LYY0dkm7B_BuNfz-V-R:b-uq2xfy) ([raw file](https://github.com/cockroachdb/cockroach/blob/10af5d7b8a28630b6aaa5e7ed58d9835ecc6026b/pkg/sql/pgwire/types.go#L248)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Do you need to detect the `Oid == 0` case in order for the doc comment to be correct?
</blockquote></details>

No, the 0 case is for types that have a 1:1 mapping. The oid must be specified otherwise. I've updated the comment to reflect this.

**Pull request merged**
