### PR TITLE
rpc: windows: unskip TestHeartbeatHealthTransport

### PR DESCRIPTION
**Pull request by tbg**

### CODE REVIEW

**Review by a-robinson — APPROVED** [review]
How/when will we find out if the test still doesn't work?

**Comment by tschottdorf** [comment]
Unclear to me. Don't we run windows CI on appveyor? Not sure if and when, unfortunately.

**Comment by a-robinson** [comment]
If you don't mind waiting a few days until he's back, I imagine @BramGruneir knows

**Comment by bdarnell** [comment]
We do not run windows CI on either appveyor or teamcity (appveyor is extremely slow, so if we want to start running CI for windows we should start some windows teamcity agents)

**Comment by tschottdorf** [comment]
@benesch looks like you had a windows box, care to test run this?

**Comment by tschottdorf** [comment]
Nevermind.

**Pull request closed without merging**
