### PR TITLE
sql: various allocation optimizations

### PR DESCRIPTION
**Pull request by petermattis**
- client: reduce allocations in Batch.initResult()
- sql: avoid allocations when passing keys to `client` methods
- sql: change marshalColumnValue() to return a roachpb.Value
- roachpb: avoid an allocation NewConditionalPut

```
name                  old time/op    new time/op    delta
KVInsert1_SQL-32         494µs ± 2%     494µs ± 3%     ~     (p=0.799 n=20+20)
KVInsert10_SQL-32        959µs ± 2%     947µs ± 2%   -1.17%  (p=0.001 n=19+20)
KVInsert100_SQL-32      5.22ms ± 3%    5.11ms ± 1%   -2.11%  (p=0.000 n=19+20)
KVInsert1000_SQL-32     52.2ms ± 4%    50.2ms ± 5%   -3.86%  (p=0.000 n=20+19)
KVInsert10000_SQL-32     669ms ± 8%     646ms ± 7%   -3.50%  (p=0.035 n=20+19)

name                  old alloc/op   new alloc/op   delta
KVInsert1_SQL-32        25.2kB ± 0%    25.1kB ± 0%   -0.32%  (p=0.000 n=20+20)
KVInsert10_SQL-32        101kB ± 0%     100kB ± 0%   -1.82%  (p=0.000 n=20+20)
KVInsert100_SQL-32       850kB ± 0%     832kB ± 0%   -2.17%  (p=0.000 n=18+20)
KVInsert1000_SQL-32     9.65MB ± 3%    9.51MB ± 4%   -1.37%  (p=0.001 n=19+20)
KVInsert10000_SQL-32     157MB ±29%     152MB ±18%     ~     (p=0.070 n=20+19)

name                  old allocs/op  new allocs/op  delta
KVInsert1_SQL-32           310 ± 0%       304 ± 0%   -1.94%  (p=0.000 n=17+20)
KVInsert10_SQL-32          825 ± 0%       754 ± 0%   -8.64%  (p=0.000 n=19+18)
KVInsert100_SQL-32       5.83k ± 0%     5.04k ± 0%  -13.48%  (p=0.000 n=20+20)
KVInsert1000_SQL-32      56.5k ± 1%     48.6k ± 2%  -13.87%  (p=0.000 n=19+20)
KVInsert10000_SQL-32      647k ±13%      563k ± 9%  -13.03%  (p=0.000 n=20+19)
```

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6378)

### CODE REVIEW

**Comment by dt** [comment]
Reviewed 1 of 1 files at r1, 5 of 5 files at r2, 2 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[client/batch.go, line 81 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6378#-KGSeBxcBK3zKXCYrwEz:-KGSeBxdCIr6T6dPzWva:1187583602) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f9adca5226fa1dd4cd974c8a7d1997943b04748/client/batch.go#L81)):*
This is unreachable, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6378)*

**Comment by RaduBerinde** [comment]
LGTM (modulo David's comment)

---

Reviewed 1 of 1 files at r1, 3 of 5 files at r2, 2 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6378#-:-KGSmtBebtiuu0fWdlhp:-11731693)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[client/batch.go, line 81 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6378#-KGSeBxcBK3zKXCYrwEz:-KGSnlHpRkXDcU3nO3zn:-420069405) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f9adca5226fa1dd4cd974c8a7d1997943b04748/client/batch.go#L81)):*
Yes it is. Good catch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6378)*

**Comment by dt** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r5, 5 of 5 files at r6, 2 of 2 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6378#-:-KGSo_2WhaIJtaPKn-K1:1417088721)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[client/batch.go, line 80 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6378#-KGSpPvzXk6nvS7hxAnd:-KGSpPvzXk6nvS7hxAne:610091905) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e6fd044bdbadf3078190d9333286c9c023084b4/client/batch.go#L80)):*
this just became a very fancy way of writing `if numRows == 1`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6378)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[client/batch.go, line 80 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6378#-KGSpPvzXk6nvS7hxAnd:-KGSq0JFXfD7tf-Mnlm3:1799698019) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e6fd044bdbadf3078190d9333286c9c023084b4/client/batch.go#L80)):*
Yeah, I realized that too. The generated code is probably equivalent. I mildly prefer the switch format to the `if-else`, but happy to change this if you'd like.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6378)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[client/batch.go, line 80 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6378#-KGSpPvzXk6nvS7hxAnd:-KGSqeKPlnxZq5ARdbUb:-977413526) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e6fd044bdbadf3078190d9333286c9c023084b4/client/batch.go#L80)):*
Up to you. We need a [feel-free-to-ignore-without-further-discussion] tag for comments :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6378)*

**Pull request merged**
