### PR TITLE
sqlccl: return an error when a BACKUP mentions nonexistent targets

### LINKED ISSUE #14118: backup: specifying bogus descriptors to BACKUP doesn't fail
This query claims to succeed

```
BACKUP garbage_a, garbage_b TO 'foo';
```

even though `garbage_a` and `garbage_b` don't name valid objects. The fix for this should properly abort with partially-valid specifiers too, like `foo.bar, baz.*` where `baz.*` is valid but `foo.bar` is not.

### PR DESCRIPTION
**Pull request by benesch**
Fixes #14118.

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/ccl/sqlccl/targets_test.go, line 103 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15313#-KiXuYnrS8eR618EtJQL:-KiXuYnsgMdCjxwSSkcj:b-onchhd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a97111c3d2bc9d32adfc68cb4137763efc92b538/pkg/ccl/sqlccl/targets_test.go#L103)):*
> ```Go
> 					t.Fatalf("expected error matching '%v', but got '%v'", test.err, err)
> 				}
> 				return
> ```

else below rather than `return` here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15313)*

**Comment by benesch** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/ccl/sqlccl/targets_test.go, line 103 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15313#-KiXuYnrS8eR618EtJQL:-Ki_iJgn-OMfAK6f-hFs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a97111c3d2bc9d32adfc68cb4137763efc92b538/pkg/ccl/sqlccl/targets_test.go#L103)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

else below rather than `return` here?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15313)*

**Comment by tamird** [comment]
Reviewed 1 of 2 files at r2.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15313)*

**Comment by danhhz** [comment]
:lgtm: I think we should also error if 0 tables are selected (regardless of the number of databases), though that feels more like it should live in the backup & restore impls to me and so could be a followup PR

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15313#-:-KiaE8veJjqnMIuGJWVd:b-nw2e5v)*

**Comment by benesch** [comment]
Agreed, I'll do that in a followup. TFTR!

**Pull request merged**
