### PR TITLE
opt: fix duplicate empty JSON value spans for <@ expressions

### PR DESCRIPTION
**Pull request by angelazxu**
Previously, there were some duplicate spans produced for empty JSON values,
such as {"a": []} and {"a": {}}. This was discovered in the spans produced
from contained by and fetch/contained by expressions.

This commit fixes this issue, only allowing one empty object or array span to
be created per level of nesting, in encodedContainedInvertedIndexSpans.

Informs: #61430

Release note: None

### CODE REVIEW

**Review by angelazxu — COMMENTED** [review]
Also, I'm not sure if isObjectValue is the best name for the boolean being passed in the functions, it's more like isNonEmptyObjectOrArrayValue (!isEnd), not sure if there's a more fitting yet simple name?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63355#-:-MXnm2i-8SXd6PhH9kcb:b-plbtxm)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by rytaft — COMMENTED** [review]
Good find!

How about keeping the name `isObjectValue`, but making it actually mean that (i.e., you would pass `true` from the function calls inside `jsonObject.encodeContainedInvertedIndexSpans()`)? Then you'd need to check `if !isObjectValue || len(j) == 0`. I think that should work, right?

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63355#-:-MXnvTBBAPjL9IuyAA20:bsad1ob)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @angelazxu)

**Review by angelazxu — COMMENTED** [review]
yup that works!! thanks :D 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63355#-:-MXraUnN8DoH3h8G6pBA:b-hmedzv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63355#-:-MXriHvm9Lx2tqwvUZcb:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @angelazxu)

___
*[pkg/util/json/json.go, line 108 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63355#-MXrhwZr4Wgwte2sMMqr:-MXrhwZr4Wgwte2sMMqs:b3n4w0s) ([raw file](https://github.com/cockroachdb/cockroach/blob/70e58a099da410806ef4d3616117d33b3efb2094/pkg/util/json/json.go#L108)):*
> ```Go
> 	//
> 	// If isRoot is true, this function is being called at the root level of the
> 	// JSON hierarchy.
> ```

add a description of the `isObjectValue` param here

**Comment by knz** [comment]
this might benefit from a backport to the stable release branch(es).

**Comment by rytaft** [comment]
I think fixes a bug that was introduced after the branch cut for 21.1, so I don't think it needs a backport.

**Pull request merged**
