### PR TITLE
asim: add size based range splits

### LINKED ISSUE #82660: asim: simulate size based range splitting
Size based splitting of a range occurs when a range size (bytes) exceeds the threshold set by the span config associated with that range.

https://github.com/cockroachdb/cockroach/blob/c520ac8272a59415ad975ac9cc41b075c5b449ab/pkg/kv/kvserver/split_queue.go#L108-L111

The allocation simulator does not currently support support this behavior, ranges will not split after initialization. This is an issue as in practice, the range count will vary as data is written into ranges, due to splitting. The range count is a balancing metric that is used in to reconfigure allocations of ranges to stores. Therefore, it should be simulated within the allocation simulator.

The solution is to add a size based splitter, that is ticked in the simulator loop. It should act in much the same manner of the replicate queue - where ranges are periodically checked for enqueuing, if they meet the split criteria. The split queue should then split these ranges.

An alternative solution is to scan every range, each tick and split them at some delay as opposed to pacing range consideration inside a queue.

Jira issue: CRDB-16614

Epic CRDB-14561

### PR DESCRIPTION
**Pull request by kvoli**
This patch introduces size based (byte) splitting of ranges in the
simulator. Previously, ranges would only be split manually, on setup.
Now, ranges will be split when their estimated size exceeds a
threshold. The estimated size is the sum of all writes that have
previously occurred to the range since the simulation began

resolves https://github.com/cockroachdb/cockroach/issues/82660

Release note: None

### CODE REVIEW

**Comment by kvoli** [comment]
Waiting on the earlier patch to merge. Ignore the first patch here.

**Review by lidorcarmel — APPROVED** [review]
> Reviewed 9 of 9 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83211)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/asim/asim.go` line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83211#-N5CGZcV3BaJmTryi4Ha:-N5CGZcV3BaJmTryi4Hb:bpf25jt) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a70ee501566286a583cc182b4ab59882d65340f/pkg/kv/kvserver/asim/asim.go#L34)):*
> ```Go
> 
> 	pacers map[state.StoreID]ReplicaPacer
> 	rqs    map[state.StoreID]RangeQueue
> ```

do you mind adding a comment for these 2 lines?
`// Replicate queues` and `// Store Rebalancer queues` I assume.



_Code quote:_
```Go
	rqs    map[state.StoreID]RangeQueue
	sqs    map[state.StoreID]RangeQueue
```
___
*[`pkg/kv/kvserver/asim/pacer.go` line 22 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83211#-N5CHZCb2LXs4rj2JS3n:-N5CHZCb2LXs4rj2JS3o:b-coxrli) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a70ee501566286a583cc182b4ab59882d65340f/pkg/kv/kvserver/asim/pacer.go#L22)):*
> ```Go
> // ReplicaPacer controls the speed of considering a replica.
> type ReplicaPacer interface {
> ```

nit: empty line? intentional?
___
*[`pkg/kv/kvserver/asim/pacer.go` line 85 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83211#-N5CHo089zYQ75OzFH2H:-N5CHo089zYQ75OzFH2I:bb7phvt) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a70ee501566286a583cc182b4ab59882d65340f/pkg/kv/kvserver/asim/pacer.go#L85)):*
> ```Go
> 
> 	// If there are no replicas, we cannot determine the correct iter interval,
> 	// instead of waitng for the loop interval return early and try again on next
> ```

typo



_Code quote:_
```Go
waitng
```
___
*[`pkg/kv/kvserver/asim/replicate_queue.go` line 112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83211#-N5CIkp40Bk9CZ-pIGFm:-N5CIkp40Bk9CZ-pIGFn:bdwvdct) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a70ee501566286a583cc182b4ab59882d65340f/pkg/kv/kvserver/asim/replicate_queue.go#L112)):*
> ```Go
> 	allocator allocatorimpl.Allocator
> 	// TOOD(kvoli): Delay is used as a fixed delay we pass for all replica
> 	// changes. In the future we should pass in a delay function which returns
> ```

drop the todo? I think you just implemented that.



_Code quote:_
```Go
	// TOOD(kvoli): Delay is used as a fixed delay we pass for all replica
	// changes. In the future we should pass in a delay function which returns
	// a duration given the size of the range, snapshot rates and overload.
```
___
*[`pkg/kv/kvserver/asim/replicate_queue.go` line 243 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83211#-N5CIVcKEnY6JNmyP5VA:-N5CIVcKEnY6JNmyP5VB:bnehrxo) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a70ee501566286a583cc182b4ab59882d65340f/pkg/kv/kvserver/asim/replicate_queue.go#L243)):*
> ```Go
> 
> //NewSplitQueue returns a new split queue, implementing the range queue
> //interface.
> ```

nit: spaces after the `//`



_Code quote:_
```Go
//NewSplitQueue returns a new split queue, implementing the range queue
//interface.
```
___
*[`pkg/kv/kvserver/asim/replicate_queue.go` line 284 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83211#-N5CLmjX1jZAD9fBnQCQ:-N5CLmjX1jZAD9fBnQCR:b-wzkgbm) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a70ee501566286a583cc182b4ab59882d65340f/pkg/kv/kvserver/asim/replicate_queue.go#L284)):*
> ```Go
> // FIFO order on ties. The tick currently only considers size based range
> // splitting.
> func (sq *splitQueue) Tick(ctx context.Context, tick time.Time, s state.State) {
> ```

should we split more than one range per tick?
___
*[`pkg/kv/kvserver/asim/replicate_queue.go` line 325 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83211#-N5CM84Q6d5WOS_SlUho:-N5CM84Q6d5WOS_SlUhp:b215mg3) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a70ee501566286a583cc182b4ab59882d65340f/pkg/kv/kvserver/asim/replicate_queue.go#L325)):*
> ```Go
> // shouldSplit returns whether a range should be split into two. When the
> // floating point number returned is greater than or equal to 1, it should be
> // split with that priority, else it shouldn't
> ```

why not just return a bool? it looks like MaybeAdd is calculating the priority so here a bool should be enough.

nit: period at the end.
___
*[`pkg/kv/kvserver/asim/settings.go` line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83211#-N5CWTlOCOgBpZrA3ERC:-N5CWTlOCOgBpZrA3ERD:buntpuv) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a70ee501566286a583cc182b4ab59882d65340f/pkg/kv/kvserver/asim/settings.go#L40)):*
> ```Go
> 	// ReplicaChangeBaseDelay + (RangeSize(MB)  * ReplicaAddDelayFactor)
> 	// milliseconds.
> 	ReplicaAddDelayFactor float64
> ```

this is fine, but it can be ReplicaAddRate, where a rate of 10 means 10MB/s. up to you if you want to change..
___
*[`pkg/kv/kvserver/asim/settings.go` line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83211#-N5CWtQgD3YndggmWmW4:-N5CWtQgD3YndggmWmW5:brw94p6) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a70ee501566286a583cc182b4ab59882d65340f/pkg/kv/kvserver/asim/settings.go#L43)):*
> ```Go
> 	// SplitQueueDelay is the delay that range splits take to complete.
> 	SplitQueueDelay time.Duration
> 	// RangeSizeSplitThreshold is the threshold below which ranges will not
> ```

.. the threshold `in MBs` below which..
___
*[`pkg/kv/kvserver/asim/state/change.go` line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83211#-N5CYFuzChRnyhuxNUOt:-N5CYFuzChRnyhuxNUOu:b-188zaj) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a70ee501566286a583cc182b4ab59882d65340f/pkg/kv/kvserver/asim/state/change.go#L55)):*
> ```Go
> }
> 
> // RangeSplitChange contains information necessary to split a range at a given
> ```

mention this is implementing the `Change` interface?
___
*[`pkg/kv/kvserver/asim/replicate_queue_test.go` line 133 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83211#-N5CZ2jN66MqAz8pPpGc:-N5CZ2jN66MqAz8pPpGd:bgd28rd) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a70ee501566286a583cc182b4ab59882d65340f/pkg/kv/kvserver/asim/replicate_queue_test.go#L133)):*
> ```Go
> 			results := make(map[int64]map[int]int)
> 			// Initialize the store pool information.
> 			exchange := state.NewFixedDelayExhange(start, testSettings.StateExchangeInterval, time.Second*0 /* no state update delay */)
> ```

nit: long lines.



_Code quote:_
```Go
			rq := NewReplicateQueue(store.StoreID(), changer, ReplicaChangeDelayFn(testSettings), s.MakeAllocator(store.StoreID()))
			s.TickClock(start)

			results := make(map[int64]map[int]int)
			// Initialize the store pool information.
			exchange := state.NewFixedDelayExhange(start, testSettings.StateExchangeInterval, time.Second*0 /* no state update delay */)
```
___
*[`pkg/kv/kvserver/asim/replicate_queue_test.go` line 181 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83211#-N5CZBpx49uiqaA6fdJx:-N5CZBpx49uiqaA6fdJy:b54c0e4) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a70ee501566286a583cc182b4ab59882d65340f/pkg/kv/kvserver/asim/replicate_queue_test.go#L181)):*
> ```Go
> 	testingStore := state.StoreID(1)
> 
> 	testingState := func(replicaCounts map[state.StoreID]int, replicationFactor int32, leaseholder state.StoreID) state.State {
> ```

break the long line?

**Review by kvoli — COMMENTED** [review]
TYFTR

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83211#-:-N5G36xO2_9cSzgtniQR:b-80sls6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lidorcarmel)

___
*[`pkg/kv/kvserver/asim/asim.go` line 34 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83211#-N5CGZcV3BaJmTryi4Ha:-N5FfehECKrSgNwtwch-:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a70ee501566286a583cc182b4ab59882d65340f/pkg/kv/kvserver/asim/asim.go#L34)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

do you mind adding a comment for these 2 lines?
`// Replicate queues` and `// Store Rebalancer queues` I assume.
</blockquote></details>

Updated.
___
*[`pkg/kv/kvserver/asim/pacer.go` line 22 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83211#-N5CHZCb2LXs4rj2JS3n:-N5FflLt44YWHSK3I9o2:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a70ee501566286a583cc182b4ab59882d65340f/pkg/kv/kvserver/asim/pacer.go#L22)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

nit: empty line? intentional?
</blockquote></details>

Updated.
___
*[`pkg/kv/kvserver/asim/pacer.go` line 85 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83211#-N5CHo089zYQ75OzFH2H:-N5Ffny86QFkj9lv9mxC:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a70ee501566286a583cc182b4ab59882d65340f/pkg/kv/kvserver/asim/pacer.go#L85)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

typo
</blockquote></details>

Updated.
___
*[`pkg/kv/kvserver/asim/replicate_queue.go` line 112 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83211#-N5CIkp40Bk9CZ-pIGFm:-N5Ffy7U0RUdIXsw89iY:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a70ee501566286a583cc182b4ab59882d65340f/pkg/kv/kvserver/asim/replicate_queue.go#L112)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

drop the todo? I think you just implemented that.
</blockquote></details>

Updated.
___
*[`pkg/kv/kvserver/asim/replicate_queue.go` line 243 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83211#-N5CIVcKEnY6JNmyP5VA:-N5Fg0rmB1OiPV108dJa:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a70ee501566286a583cc182b4ab59882d65340f/pkg/kv/kvserver/asim/replicate_queue.go#L243)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

nit: spaces after the `//`
</blockquote></details>

Updated.
___
*[`pkg/kv/kvserver/asim/replicate_queue.go` line 284 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83211#-N5CLmjX1jZAD9fBnQCQ:-N5FmxCQ41jZCkDxfw8I:b-hdgdh9) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a70ee501566286a583cc182b4ab59882d65340f/pkg/kv/kvserver/asim/replicate_queue.go#L284)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

should we split more than one range per tick?
</blockquote></details>

Good idea. Added in and rearranged some things so this will work correctly. 
___
*[`pkg/kv/kvserver/asim/replicate_queue.go` line 325 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83211#-N5CM84Q6d5WOS_SlUho:-N5FgF_F1O7AvLQ8us01:btzznoo) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a70ee501566286a583cc182b4ab59882d65340f/pkg/kv/kvserver/asim/replicate_queue.go#L325)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

why not just return a bool? it looks like MaybeAdd is calculating the priority so here a bool should be enough.

nit: period at the end.
</blockquote></details>

Maybe add is using this method to calculate the priority. Updated the period.
___
*[`pkg/kv/kvserver/asim/settings.go` line 40 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83211#-N5CWTlOCOgBpZrA3ERC:-N5FgqBA22_JZZWNsxQs:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a70ee501566286a583cc182b4ab59882d65340f/pkg/kv/kvserver/asim/settings.go#L40)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

this is fine, but it can be ReplicaAddRate, where a rate of 10 means 10MB/s. up to you if you want to change..
</blockquote></details>

Updated.
___
*[`pkg/kv/kvserver/asim/settings.go` line 43 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83211#-N5CWtQgD3YndggmWmW4:-N5Fh5SXEalh_4pTguw6:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a70ee501566286a583cc182b4ab59882d65340f/pkg/kv/kvserver/asim/settings.go#L43)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

.. the threshold `in MBs` below which..
</blockquote></details>

Updated.
___
*[`pkg/kv/kvserver/asim/state/change.go` line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83211#-N5CYFuzChRnyhuxNUOt:-N5FhCYiAH_iZnounyYV:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a70ee501566286a583cc182b4ab59882d65340f/pkg/kv/kvserver/asim/state/change.go#L55)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

mention this is implementing the `Change` interface?
</blockquote></details>

Updated.
___
*[`pkg/kv/kvserver/asim/replicate_queue_test.go` line 133 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83211#-N5CZ2jN66MqAz8pPpGc:-N5Fj_p4536-SFY-IU_T:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a70ee501566286a583cc182b4ab59882d65340f/pkg/kv/kvserver/asim/replicate_queue_test.go#L133)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

nit: long lines.
</blockquote></details>

Updated.
___
*[`pkg/kv/kvserver/asim/replicate_queue_test.go` line 181 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83211#-N5CZBpx49uiqaA6fdJx:-N5FjaPpAOxed46JEX1p:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a70ee501566286a583cc182b4ab59882d65340f/pkg/kv/kvserver/asim/replicate_queue_test.go#L181)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

break the long line?
</blockquote></details>

Updated.

**Pull request merged**
