### PR TITLE
release-23.2: sql/stats: fix panic catching in the stats cache, show histogram

### LINKED ISSUE #135940: sql: panic when decoding table stats can crash the process
We have observed occasional issues in the past where attempting to decode table statistics histograms causes a panic (e.g., https://github.com/cockroachdb/cockroach/issues/128876). We catch panics in some parts of the stats cache, but there are some paths through the stats cache where panics are not caught. This causes certain operations that access the stats cache to crash the cockroach process. We should add panic catching for these alternate paths.

Jira issue: CRDB-44798

### PR DESCRIPTION
**Pull request by rytaft**
Backport 1/1 commits from #135944.

/cc @cockroachdb/release

---

This commit removes a top-level panic catcher from `GetTableStats` in the stats
cache, and instead adds a couple of lower level panic catchers. The problems
with the top-level catcher are:
- There are other entry points into the stats cache besides `GetTableStats`, so
  it missed some cases.
- Because the stats cache contains shared state, condition variables, mutexes,
  etc, it was possible to get into a scenario where a panic would bypass
  important logic (such as broadcasting when a resource is available), but the
  panic would be caught at the top level and leave the cache in a bad state.

The new panic catchers are below the level of this shared state manipulation,
but also ensure that all paths into the stats cache that might panic are
covered.

This commit also adds panic catching to `SHOW HISTOGRAM` so that decoding errors
do not crash the process when running `SHOW HISTOGRAM`.

Fixes #135940

Release note (bug fix): Fixed an issue where corrupted table statistics could cause the cockroach process to crash.

### CODE REVIEW

**Review by michae2 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136043#-:-OCL7yoKDATSdyuccP_R:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

**Review by mgartner — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136043)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

___
*[`pkg/sql/show_histogram.go` line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136043#-OCZ1xmvAadGXTfIUXHp:-OCZ1xmvAadGXTfIUXHq:bt5syvs) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f5c983fc028c81b7936260b20aeef70ac422f69/pkg/sql/show_histogram.go#L75)):*
> ```Go
> 					// manipulate locks.
> 					if ok, e := errorutil.ShouldCatch(r); ok {
> 						err = e
> ```

See my comment here: https://github.com/cockroachdb/cockroach/pull/136041#pullrequestreview-2458854459

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136043)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @michae2)

___
*[`pkg/sql/show_histogram.go` line 75 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136043#-OCZ1xmvAadGXTfIUXHp:-OCZsful27kqCnHGpVfx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0f5c983fc028c81b7936260b20aeef70ac422f69/pkg/sql/show_histogram.go#L75)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

See my comment here: https://github.com/cockroachdb/cockroach/pull/136041#pullrequestreview-2458854459
</blockquote></details>

Done.

**Review by mgartner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136043#-:-OC_3ub75x3MnUjFv1e0:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

**Pull request merged**
