### PR TITLE
sqlccl: record low-water mark to system.jobs during restore

### PR DESCRIPTION
**Pull request by benesch**
During a restore, record the highest key beneath which all ImportRequests have completed. This paves the way to resumable coordinators, which can use this information to skip over work that's
already been done.

@jordanlewis, the first commit is more relevant to you.

### CODE REVIEW

**Comment by danhhz** [comment]
:lgtm:

---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/ccl/sqlccl/backup_test.go, line 421 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16791#-Koi3P-maoaKk9pUy9rr:-Koi3P-maoaKk9pUy9rs:b-j1we20) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b49d014d93203574da917bd1d60e42b0d4d3223/pkg/ccl/sqlccl/backup_test.go#L421)):*
> ```Go
> func TestBackupRestoreSystemJobs(t *testing.T) {
> 	defer leaktest.AfterTest(t)()
> 	t.Skip("TODO(dan): BEFORE MERGE")
> ```

:raised_hands: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16791#-:-Koi5-vK-_2SbEMlqFum:bnfp4nl)*

**Comment by jordanlewis** [comment]
Reviewed 6 of 6 files at r1.
Review status: 6 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/sqlccl/backup_test.go, line 421 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16791#-Koi3P-maoaKk9pUy9rr:-KolYqtUKCiO7aYwdpff:bgzyalb) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b49d014d93203574da917bd1d60e42b0d4d3223/pkg/ccl/sqlccl/backup_test.go#L421)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

:raised_hands: 
</blockquote></details>

:lgtm: but I don't love the new progressed api - suggestion within!

---

*[pkg/sql/jobs/jobs.go, line 205 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16791#-KolYUw3mTNaTStPgYa9:-KolYUw3mTNaTStPgYaA:bbwqopi) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e97a8296e1c0c7eed0c81fe67d9856fdaf6777a/pkg/sql/jobs/jobs.go#L205)):*
> ```Go
> // instead of nil for readability.
> func (jl *JobLogger) Progressed(
> 	ctx context.Context, fractionCompleted float32, progressedFn ProgressedFn,
> ```

I don't love this to be honest - not only does it introduce an extra arg every time Progressed is called, but it means that you can't update details without updating the progress.

Consider my approach in https://github.com/jordanlewis/cockroach/commit/340e115dd877eaa1141df4427e75e6217894d3b1 - just a setDetails method?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16791)*

**Comment by jordanlewis** [comment]
:lgtm: but I don't love the new progressed api - suggestion within!

---

Review status: 6 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/sqlccl/backup_test.go, line 421 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16791#-Koi3P-maoaKk9pUy9rr:-KolZ0ZRMHpxT48wyO0I:b-yn6sbe) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b49d014d93203574da917bd1d60e42b0d4d3223/pkg/ccl/sqlccl/backup_test.go#L421)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

:lgtm: but I don't love the new progressed api - suggestion within!
</blockquote></details>

Ugh this was the wrong place to write that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16791#-:-KolZ-H6Uu2G76Vy7O_2:bgzyalb)*

**Comment by benesch** [comment]
Review status: 6 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/jobs/jobs.go, line 205 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16791#-KolYUw3mTNaTStPgYa9:-Kom0qIknqLzTnoNxbpy:blf8rpl) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e97a8296e1c0c7eed0c81fe67d9856fdaf6777a/pkg/sql/jobs/jobs.go#L205)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I don't love this to be honest - not only does it introduce an extra arg every time Progressed is called, but it means that you can't update details without updating the progress.

Consider my approach in https://github.com/jordanlewis/cockroach/commit/340e115dd877eaa1141df4427e75e6217894d3b1 - just a setDetails method?
</blockquote></details>

I know what you mean, but I think it's important to minimize the number of updates to `system.jobs` because each update rewrites the entire protobuf. I think we'll want your `SetDetails` in addition to this method for exactly the case you describe. Thoughts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16791)*

**Comment by jordanlewis** [comment]
Review status: 6 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/jobs/jobs.go, line 205 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16791#-KolYUw3mTNaTStPgYa9:-Kom2DBOuoHl-1o2x_pS:b-8sol25) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e97a8296e1c0c7eed0c81fe67d9856fdaf6777a/pkg/sql/jobs/jobs.go#L205)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I know what you mean, but I think it's important to minimize the number of updates to `system.jobs` because each update rewrites the entire protobuf. I think we'll want your `SetDetails` in addition to this method for exactly the case you describe. Thoughts?
</blockquote></details>

I would argue that it actually doesn't matter, because the frequency of updates to system.jobs is actually rather low. To me this feels like premature optimization. I'm okay with merging this though - I don't really think it matters much either way besides OCD-ish API cleanliness concerns :thumbsup: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16791)*

**Comment by benesch** [comment]
Review status: 6 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/jobs/jobs.go, line 205 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16791#-KolYUw3mTNaTStPgYa9:-Kon2lzT-x4NsMMG_EoY:b-x7pmmr) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e97a8296e1c0c7eed0c81fe67d9856fdaf6777a/pkg/sql/jobs/jobs.go#L205)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I would argue that it actually doesn't matter, because the frequency of updates to system.jobs is actually rather low. To me this feels like premature optimization. I'm okay with merging this though - I don't really think it matters much either way besides OCD-ish API cleanliness concerns :thumbsup: 
</blockquote></details>

Some quick back of the envelope math suggests that a restore that runs for one day uses at least 13.6 MB of `system.jobs` storage, given that the protobuf is currently ~150 bytes and updated every second:

    (60 seconds/minute * 60 minutes/hour * 24 hours/day) * 156 bytes = 13.4 MB/day

It's not a ton, but it's not nothing. I'm going to merge as is in the interest of moving forward, but definitely not married to this API.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16791)*

**Pull request merged**
