### PR TITLE
persistedsqlstats: add cluster setting to enable flush on row limit r…

### LINKED ISSUE #108771: sqlstats: create cluster setting to bypass count rows in stats tables on flush
In order to limit the growth of the sql stats tables, we introduced a query to run before flushing stats that checks to ensure the number of rows has not surpassed 1.5x the value of `sql.stats.persisted_rows.max`. This query has been causing contention with the compaction job delete rows stmts and can cause the job to fail. We should add a cluster setting to bypass this check and just let the compaction job try to catch up as it's worse for the compaction job to fail indefinitely.

Jira issue: CRDB-30630

### PR DESCRIPTION
**Pull request by xinhaoz**
…eached

This commit introduces the cluster setting `sql.stats.limit_table_size.enabled` which controls whether or not we enforce the row limit set by `sql.stats.persited_rows.max` in the system.{statement,transaction} statistics tables. Previously, when the sql stats tables reach the row limit set by `sql.stats.persisted_rows.max`, we disable flushing any more stats to the tables. This restriction involved issuing a query during the flush process to check the number of rows currently in the tables. This query can often contend with the compaction job queries and so we should allow a method to bypass this check to alleviate the contention.

Furhtermore, in some cases we'd like to allow the system tables to grow in order to not have gaps in sql stats observability. In these cases we can attempt to modify the compaction settings to allow the job to catch up to the target number of rows.

Fixes: #108771

Release note (sql change):
This commit introduces the cluster setting `sql.stats.limit_table_size.enabled` which controls whether or not we enforce the row limit set by `sql.stats.persited_rows.max` in the system.{statement,transaction} statistics tables.

### CODE REVIEW

**Review by j82w — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108835)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`pkg/sql/sqlstats/persistedsqlstats/cluster_settings.go` line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108835#-NbyYUii7bH59FJgx8Fq:-NbyYUii7bH59FJgx8Fr:b2a82ub) ([raw file](https://github.com/cockroachdb/cockroach/blob/00105acc8284e173447a4cff1bd07a7e09ead178/pkg/sql/sqlstats/persistedsqlstats/cluster_settings.go#L133)):*
> ```Go
> )
> 
> // CompactionJobRowsToDeletePerTxn is the cluster setting that controls
> ```

nit: update

**Review by maryliag — COMMENTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108835)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @xinhaoz)

___
*[`-- commits` line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108835#-NbykXzx6iejvzRgmxpG):*
nit: looks like your release notes got messed up

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108835#-:-Nbzid312fo7BO3fmWgL:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`-- commits` line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108835#-NbykXzx6iejvzRgmxpG):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: looks like your release notes got messed up
</blockquote></details>

Don't forget to update the PR description too

**Comment by xinhaoz** [comment]
TFTR!
bors r+

**Pull request merged**
