### PR TITLE
kv: limit the size of a command in a particular Warning log to 500 bytes

### PR DESCRIPTION
**Pull request by vivekmenezes**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5958)

### CODE REVIEW

**Comment by bdarnell** [comment]
LGTM, although this probably isn't the only place where we log batch requests on errors. We could fix this more generally by either limiting the string produced by BatchRequest.String() or filtering long lines before piping into `go2xunit`.

**Comment by tschottdorf** [comment]
+1 for limiting BatchRequest.String

On Sat, Apr 9, 2016, 03:59 Ben Darnell <notifications@github.com> wrote:

> LGTM, although this probably isn't the only place where we log batch
> requests on errors. We could fix this more generally by either limiting the
> string produced by BatchRequest.String() or filtering long lines before
> piping into go2xunit.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/cockroach/pull/5958#issuecomment-207682708>
>
-- 

-- Tobias

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[kv/dist_sender.go, line 701 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5958#-KEwKm_UKCwh16ZUHztQ:-KEwKm_UKCwh16ZUHztR:-1284945215) ([raw file](https://github.com/cockroachdb/cockroach/blob/b85c1941f3e439507556c6f4e8495eb9858d1636/kv/dist_sender.go#L701)):*
Did you test this? I did: http://play.golang.org/p/mJAtRuy8eN

The docs say: `For strings, byte slices and byte arrays, however, precision limits the length of the input to be formatted (not the size of the output), truncating if necessary.`

AFAIK, you can't use formatting specifiers to truncate a string. You have to do it manually.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5958)*

**Comment by bdarnell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[kv/dist_sender.go, line 701 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5958#-KEwKm_UKCwh16ZUHztQ:-KEwLr-TsFOts-F4J1LQ:-1264203460) ([raw file](https://github.com/cockroachdb/cockroach/blob/b85c1941f3e439507556c6f4e8495eb9858d1636/kv/dist_sender.go#L701)):*
You can, but you have to use the "precision" field and not the "width" field: `%.500s`. (https://play.golang.org/p/x_fwa6A07E)

That confusingly-worded statement from the docs is because e.g. `%.5q` can produce more than 5 characters of output after quoting and escaping. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5958)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[kv/dist_sender.go, line 701 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5958#-KEwKm_UKCwh16ZUHztQ:-KEwN2kZYpOcc8Bcpn5f:868849986) ([raw file](https://github.com/cockroachdb/cockroach/blob/b85c1941f3e439507556c6f4e8495eb9858d1636/kv/dist_sender.go#L701)):*
Oh. I just learned something new. Neat.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5958)*

**Comment by vivekmenezes** [comment]
I've restructured BatchRequest.String() it to output out a maximum of 20 commands. Let me know if this is okay. Thanks for pointing out the problem with the original implementation.

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[kv/dist_sender.go, line 701 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5958#-KEwKm_UKCwh16ZUHztQ:-KF4TC-K_-hvfQgoDXTr:2049044905) ([raw file](https://github.com/cockroachdb/cockroach/blob/b85c1941f3e439507556c6f4e8495eb9858d1636/kv/dist_sender.go#L701)):*
We don't use `err = ` in other format strings. For consistency, probably best to just revert this.

---

*[roachpb/batch.go, line 263 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5958#-KF4TRuf7dorcAJ-ph2V:-KF4TRuf7dorcAJ-ph2W:-1676778720) ([raw file](https://github.com/cockroachdb/cockroach/blob/9feb6ef8941b572cfce957bf211a75b067cec5d8/roachpb/batch.go#L263)):*
`s/a log/log/g`
`s/will be/can be/g`

---

*[roachpb/batch.go, line 265 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5958#-KF4Tf57Rvfet63aVMOU:-KF4Tf57Rvfet63aVMOV:1870522976) ([raw file](https://github.com/cockroachdb/cockroach/blob/9feb6ef8941b572cfce957bf211a75b067cec5d8/roachpb/batch.go#L265)):*
Would be good to indicate how many requests were not output:

```
str = append(str, fmt.Sprintf("%d skipped", len(ba.Requests) - count))
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5958)*

**Comment by bdarnell** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[roachpb/batch.go, line 265 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5958#-KF4Tf57Rvfet63aVMOU:-KF5-MEns3k_7bnK0kCV:-322626393) ([raw file](https://github.com/cockroachdb/cockroach/blob/9feb6ef8941b572cfce957bf211a75b067cec5d8/roachpb/batch.go#L265)):*
It's also valuable to know the how the batch ended (specifically whether it contained an `EndTransaction` or not). Maybe this should print the first 10 and last 10 instead of the first 20, or we could treat a final `EndTransaction` as a special case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5958)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[roachpb/batch.go, line 263 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5958#-KF4TRuf7dorcAJ-ph2V:-KF55lEde4YVtSp3oQ9A:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/9feb6ef8941b572cfce957bf211a75b067cec5d8/roachpb/batch.go#L263)):*
done

---

*[roachpb/batch.go, line 265 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5958#-KF4Tf57Rvfet63aVMOU:-KF55mTM6jtxyvpJTSa-:1772217385) ([raw file](https://github.com/cockroachdb/cockroach/blob/9feb6ef8941b572cfce957bf211a75b067cec5d8/roachpb/batch.go#L265)):*
Done. I've added the first 20 values at the start and the last 5 values at the end.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5958)*

**Comment by bdarnell** [comment]
:lgtm:

Commit message needs s/20/25/. Maybe a simple test?

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5958#-:-KF56Al-rLBLY9q_WxOW:-1891044653)*

**Comment by vivekmenezes** [comment]
Added a test. Thanks

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5958#-:-KF5hne5RLgFUUQgFmnT:1322155729)*

**Pull request merged**
