### PR TITLE
sql: implement a preliminary system to limit memory consumption by clients

### PR DESCRIPTION
**Pull request by knz**
The goal is to alleviate #2524 and #7572.

Overview:
- `planNode` gets a new method `Close()` to release memory early. This is called e.g. by `joinNode` to release the underlying memory from the right operand after it has been copied, or by `unionNode` for its right operand after it has completed.
- `valuesNode` does not use a `[]DTuple` to hold rows any more, but a `*RowContainer` instead.
- `RowContainer` tracks approximate memory usage of the rows stored in it. It does this by biling new rows to a `MemoryUsageMonitor.ReserveMemory()` as new rows are added; and crediting back memory via `MemoryUsageMonitor.ReleaseMemory()`.

A few things are still missing from this PR, but can be delayed until the discussion below has advanced:
- `planner` should really have a smarter policy than the current limit on 10MB.
- `distinctNode` should report its memory to `RowMonitor` separately from the `RowContainer` machinery.
- In addition to the memory allocated by the `planNode` tree, `Executor` _also_ makes another copy of all the rows in the `Result` struct. This should be tracked as well.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7608)

### CODE REVIEW

**Comment by knz** [comment]
cc @dt, @tamird, @RaduBerinde, @petermattis: please chime in with comments and suggestions regarding the discussion above.

Also, note that although the `planNode.Close()` interface is generally useful and is probably there to remain, this entire enterprise is really a stop-gap to work around the lack of memory accounting in the Go runtime. 

I am worried in particular about the delay between `planNode.Close()` and the next GC round where the memory will be actually freed. My design currently decreases the allocation counter in the finalizer, so that it is "accurate", but that means that if there are two successive queries, and the first fails with a "too many rows" error, the 2nd one may also fail with the same error even if it uses fewer rows because the first row container has not been freed yet (and its bytes not yet marked as released). Conversely, if I changed the design to immediately decrease the usage counter upon `planNode.Close()`, the memory will not be effectively free yet, and a subsequent query that also needs a lot of memory may actually cause the server to die with an OOM error.

What is wisdom?

**Comment by petermattis** [comment]
Haven't looked at the code, but we absolutely shouldn't be using `SetFinalizer` for this purpose. Rather than trying to track precisely when memory is released, I propose that it is considered released when the query response is sent (or when the planner is "closed"). This isn't quite accurate but should be more than sufficient for limiting per-query resources.

**Comment by knz** [comment]
PTAL. Not using `SetFinalizer`. Gathering feedback about the overall design at this point; needs more work before merging.

**Comment by knz** [comment]
Superseded by  #8691 (working off `develop` now).

**Pull request closed without merging**
