### PR TITLE
cluster-ui: fix statement name label on column selector

### PR DESCRIPTION
**Pull request by maryliag**
The label for Statement Time wasn't properly showing
on the column selctor on Statements page.

Release note (bug fix): Display Statement Time label on column selector
on Statements page.

### CODE REVIEW

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67327)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @THardy98)

___
*[pkg/ui/cluster-ui/src/statementsPage/statementsPage.tsx, line 434 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67327#-Me1gcTX-c6zntGRWSSU:-Me1gcTX-c6zntGRWSSV:b-802ps8) ([raw file](https://github.com/cockroachdb/cockroach/blob/23964d5a31c86b894b639e80817832e0fe9b6a22/pkg/ui/cluster-ui/src/statementsPage/statementsPage.tsx#L434)):*
> ```XML
>             c.name !== "time"
>               ? statisticsColumnLabels[c.name as StatisticTableColumnKeys]
>               : "Statement " +
> ```

Why not change the the [`statisticsColumnLabels[time]`](https://github.com/Azhng/cockroach/blob/ca53b36b572dce1dd951f104790712c9e00b8ff2/pkg/ui/cluster-ui/src/statsTableUtil/statsTableUtil.tsx#L35) from `Time` to `Statement Time` ?

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67327)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @THardy98)

___
*[pkg/ui/cluster-ui/src/statementsPage/statementsPage.tsx, line 434 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67327#-Me1gcTX-c6zntGRWSSU:-Me1hKCvDcIR-U0peXbr:b2e6toh) ([raw file](https://github.com/cockroachdb/cockroach/blob/23964d5a31c86b894b639e80817832e0fe9b6a22/pkg/ui/cluster-ui/src/statementsPage/statementsPage.tsx#L434)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Why not change the the [`statisticsColumnLabels[time]`](https://github.com/Azhng/cockroach/blob/ca53b36b572dce1dd951f104790712c9e00b8ff2/pkg/ui/cluster-ui/src/statsTableUtil/statsTableUtil.tsx#L35) from `Time` to `Statement Time` ? 
</blockquote></details>

Seems like we are not using this for the transaction page.

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67327)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @THardy98)

___
*[pkg/ui/cluster-ui/src/statementsPage/statementsPage.tsx, line 434 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67327#-Me1gcTX-c6zntGRWSSU:-Me1hmm0DS247a-ppY-p:bcypxj4) ([raw file](https://github.com/cockroachdb/cockroach/blob/23964d5a31c86b894b639e80817832e0fe9b6a22/pkg/ui/cluster-ui/src/statementsPage/statementsPage.tsx#L434)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Seems like we are not using this for the transaction page. 
</blockquote></details>

We're. We use to create the transactions page column on statsTableUtil file called "Transaction Time" and we will eventually add the column selector into the transactions page too.

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67327)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @THardy98)

___
*[pkg/ui/cluster-ui/src/statementsPage/statementsPage.tsx, line 434 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67327#-Me1gcTX-c6zntGRWSSU:-Me1lV9e7rpWGhy6b-P_:bbghrh9) ([raw file](https://github.com/cockroachdb/cockroach/blob/23964d5a31c86b894b639e80817832e0fe9b6a22/pkg/ui/cluster-ui/src/statementsPage/statementsPage.tsx#L434)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

We're. We use to create the transactions page column on statsTableUtil file called "Transaction Time" and we will eventually add the column selector into the transactions page too.
</blockquote></details>

I see :/ .  I feel it's really error prone and easy to forget if in the future we are to introduce more columns with their filter labels depending on whether they are displayed on the statement page or transaction page. Perhaps we can introduce a helper function in the `statsTableUtil` for this? What do you think?

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67327)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Azhng and @THardy98)

___
*[pkg/ui/cluster-ui/src/statementsPage/statementsPage.tsx, line 434 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67327#-Me1gcTX-c6zntGRWSSU:-Me1y4BB1AXyrWYJvD-r:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/23964d5a31c86b894b639e80817832e0fe9b6a22/pkg/ui/cluster-ui/src/statementsPage/statementsPage.tsx#L434)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

I see :/ .  I feel it's really error prone and easy to forget if in the future we are to introduce more columns with their filter labels depending on whether they are displayed on the statement page or transaction page. Perhaps we can introduce a helper function in the `statsTableUtil` for this? What do you think? 
</blockquote></details>

Done

**Review by Azhng — APPROVED** [review]
This is awesome :D :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67327#-:-Me1zFceCEwcByZWVzfG:bue6y7o)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @THardy98)

**Pull request merged**
