### PR TITLE
backupccl: move backup.proto into backuppb

### PR DESCRIPTION
**Pull request by adityamaru**
Release note: None

### CODE REVIEW

**Comment by adityamaru** [comment]
I want to follow this up with https://github.com/cockroachdb/cockroach/pull/81833

**Review by dt — APPROVED** [review]
would it make sense to name this backupmeta or something like that while we're doing all this churn? wondering if we think as we switch to sst manifests or whatever, if we think we'll swap the proto out for some other implementation?

**Comment by adityamaru** [comment]
> would it make sense to name this backupmeta or something 

So the follow-up PR mentioned above introduces a `backupinfo` (which we could also call `backupmeta`?) which will have all the sst/manifest accessors, modifiers etc. Were you thinking those would lie side by side with `backup.proto`?

 Even when we do switch to sst manifests `backup.proto` will have some other proto defs like `ScheduledBackupExecutionArgs`, `RestoreProgress` etc so I thought having a canonical pb package might make sense.

**Comment by dt** [comment]
> I thought having a canonical pb package might make sense.

SGTM

**Comment by adityamaru** [comment]
bors r=dt

**Comment by adityamaru** [comment]
bors r=dt

**Pull request merged**
