### PR TITLE
parser: support empty target list in SELECT

### LINKED ISSUE #83255: sql: support for SELECT with no projections
Postgres allows this syntax to `SELECT` from a table with no projections.

```
jordan=# CREATE TABLE a (a int); INSERT INTO a VALUES(1);
CREATE TABLE
INSERT 0 1

jordan=# SELECT FROM a;
--
(1 row)
```

This is not supported by CockroachDB.

Jira issue: CRDB-16953

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit adds support for parsing empty target list for SELECT stmts (i.e. queries of the form `SELECT;`, `SELECT ALL FROM t;`, `SELECT FROM t;` where the projection column list is omitted). Apparently, some tools like hasura use it to get the row count.

This is achieved by making `target_list` optional. However, the caveat is that the new parsing rule runs into a shift/reduce conflict with `SELECT error` rule (since now both options can match empty string after `SELECT` AFAICT). I tried adjusting the precedence of the newly adjusted rule to resolve this conflict but didn't succeed (Raphael tried doing the same with the same result).

Fixes: #83255.

Release note (sql change): CockroachDB now supports parsing queries like `SELECT FROM t` that only produce the row count and do not output any columns.

### CODE REVIEW

**Comment by michae2** [comment]
Nice! I like this.

(I vote that you do `VALUES ();` next!)

> Any suggestions on how to preserve the contextual help rule would be appreciated.

I don't think there is a way to preserve this exact contextual help rule, since `SELECT;` is no longer a syntax error. But maybe you could add more contextual help rules for other patterns like:
- `SELECT opt_all_clause target_list ',' error`
- `WHERE error`
- `SELECT distinct_clause error`
- `SELECT distinct_on_clause error`

**Comment by yuzefovich** [comment]
Interestingly, Raphael [arrived](https://github.com/cockroachdb/cockroach/issues/83255#issuecomment-1165850752) at the same solution to this issue and also didn't see a way to not remove the contextual help.

I'll play around with some rules to preserve the contextual help.

**Comment by yuzefovich** [comment]
Added these suggestions which reverted 2 of the tests to the previous state. However, I'm not sure whether these new rules are actually worth it - like the grammar now looks even dirtier, and this help in a few cases might not be that helpful. These new rules are also quite arbitrary - we could probably come up with a dozen of others, so why stop here?

So I'm leaning towards not adding these new error rules, and the question is whether we're ok removing the contextual error help in order to support this syntax. It seems worth it to me. Thoughts?

**Review by rafiss — APPROVED** [review]
lgtm! i think losing the help output for `SELECT` (with no other tokens) is fine

**Review by michae2 — COMMENTED** [review]
Will the `\h SELECT` command in the cli still work?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116835#-:-NnADM8GEfGnYpQUbY2P:bvnl1m1)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained

**Review by yuzefovich — COMMENTED** [review]
`\h SELECT` still works, yes. @michae2 are you ok with this change without any extra rules for partial error support too?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116835#-:-NnKgzqr3ExfDg8WTWjb:b-hwak1p)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained

**Review by michae2 — APPROVED** [review]
LGTM!

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

**Pull request merged**
