### PR TITLE
security,rpc: introduce tenant client/server TLS configs

### PR DESCRIPTION
**Pull request by tbg**
This commit allows creating tenant certs via the `./cockroach mt cert`
subcommand. It also embeds a set of tenant certs via the securitytest
package; since the cli command generated these certs and since we set
up a simple client-server in testing, this makes sure they actually
work.

With this commit, the the stage is set for actually addressing #47898,
i.e. for updating a SQL tenant's `*rpc.Context` to use the tenant client
cert instead of the regular client cert, and introducing a corresponding
tenant server at the KV nodes.

This commit also fixes a buglet in the embedded certs asset loader.
Its ReadDir was returning os.ErrNotExist whenever a subdirectory
would be encountered (because it would look up the subdir as a file
which would not be found). Fixing this exposed that TestSSLClient
relied on this behavior and would not behave the same way on the
real FS, which in turn prompted a small fix in the certs loader to
hint at a missing certs dir if no cert was loaded but the config
specified to be secure.

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm: but @bdarnell should also take a pass over this since he's much more familiar with all of this than I am.

> Reviewed 5 of 5 files at r1, 1 of 1 files at r2, 29 of 29 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50082#-:-M9_K-Ni5h5Hrdu4ZCql:b-imwqvl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bdarnell and @tbg)

___
*[pkg/base/config.go, line 384 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50082#-M9_HSrnADoUfXncsRl8:-M9_HSrnADoUfXncsRl9:b-474qcj) ([raw file](https://github.com/cockroachdb/cockroach/blob/307198e554c94da67f7b5e6a71b4f7ddb3d24fc2/pkg/base/config.go#L384)):*
> ```Go
> 		cfg.certificateManager.cm, cfg.certificateManager.err =
> 			security.NewCertificateManager(cfg.SSLCertsDir)
> 		if cfg.certificateManager.err == nil && !cfg.Insecure {
> ```

Give this a comment describing the side-effect we want this to have.
___
*[pkg/cli/mt_cert.go, line 19 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50082#-M9_IIC67jMLQBwbYAGy:-M9_IIC67jMLQBwbYAGz:b-1dvtfm) ([raw file](https://github.com/cockroachdb/cockroach/blob/307198e554c94da67f7b5e6a71b4f7ddb3d24fc2/pkg/cli/mt_cert.go#L19)):*
> ```Go
> )
> 
> // mtCreateTenantClientCACertCmd generates a tenant CA certificate and stores it
> ```

nit: consider keeping these in the same order they're used in `mt.go`. Or at least in a consistent order, instead of `client-ca`, `server-ca`, `server`, `client`.
___
*[pkg/security/certificate_manager.go, line 782 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/50082#-M9_J5fjCv2lO3P9t6_L:-M9_J5fjCv2lO3P9t6_M:b-h7l42s) ([raw file](https://github.com/cockroachdb/cockroach/blob/307198e554c94da67f7b5e6a71b4f7ddb3d24fc2/pkg/security/certificate_manager.go#L782)):*
> ```Go
> }
> 
> // getTenantClientCertLocked returns the tenant node cert.
> ```

nit: similar point about the order of these. Right now it goes: server-ca, server, client, client-ca.

**Review by tbg — COMMENTED** [review]
TFTR! I cleaned up the order so that it's serverCA, server, clientCA, client.
I'll wait for @bdarnell to take a look.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50082#-:-M9cE9IuErrP9bwrfreL:b66sf6t)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @bdarnell and @nvanbenschoten)

**Review by bdarnell — COMMENTED** [review]
> Reviewed 3 of 5 files at r1, 1 of 1 files at r5, 29 of 29 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50082)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @tbg)

___
*[pkg/security/certificate_manager.go, line 123 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50082#-M9dHWte5F6p90DNOPpA:-M9dHWtf6lzIMxMKJKc_:b-l43rf4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f12e86814ee4c9e3a5a40d2953b8adbef9dda18/pkg/security/certificate_manager.go#L123)):*
> ```Go
> 	clientConfig *tls.Config
> 	// Client config for the tenant (if running in a SQL tenant server).
> 	tenantClientConfig *tls.Config
> ```

This struct is all getting ripped apart soon but I guess this is fine for now. 
___
*[pkg/security/certificate_manager.go, line 147 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50082#-M9dHKR4EMOoRDo4aWr3:-M9dHKR5B7UpYMhUeKiU:bp51tkh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f12e86814ee4c9e3a5a40d2953b8adbef9dda18/pkg/security/certificate_manager.go#L147)):*
> ```Go
> 	return &CertificateManager{
> 		cmOptions: o,
> 		certMetrics: CertificateMetrics{
> ```

All the new cert types you're adding need corresponding expiration metrics. 
___
*[pkg/security/certificate_manager.go, line 657 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50082#-M9dI9kpCjoUit6yYA6L:-M9dI9kpCjoUit6yYA6M:bvc6oxl) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f12e86814ee4c9e3a5a40d2953b8adbef9dda18/pkg/security/certificate_manager.go#L657)):*
> ```Go
> 	}
> 	return &tls.Config{
> 		GetConfigForClient: f,
> ```

Why is the work being done in GetConfigForClient instead of GetCertificate? You're not actually varying anything based on SNI. 
___
*[pkg/security/certs.go, line 334 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50082#-M9dBFP929PG_wlD72aK:-M9dBFP929PG_wlD72aL:bsgafsf) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f12e86814ee4c9e3a5a40d2953b8adbef9dda18/pkg/security/certs.go#L334)):*
> ```Go
> 	}
> 
> 	serverCert, err := GenerateServerCert(caCert, caPrivateKey,
> ```

GenerateServerCert actually creates a dual-use client and server cert (see the way it sets ExtKeyUsage). The tenant server cert should be configured only for server usage.

**Review by tbg — COMMENTED** [review]
Finally got around to polishing this up again, comments should be addressed, @bdarnell PTAFL at the new commits (rest is rebase without conflicts)

> Dismissed @bdarnell from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50082#-:-MAB6c_C4MjzzNG-A65z:b-anbf7y)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @bdarnell)

___
*[pkg/security/certificate_manager.go, line 147 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50082#-M9dHKR4EMOoRDo4aWr3:-MAB47126ffdVwNTYyGv:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f12e86814ee4c9e3a5a40d2953b8adbef9dda18/pkg/security/certificate_manager.go#L147)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

All the new cert types you're adding need corresponding expiration metrics. 
</blockquote></details>

Good point, done.
___
*[pkg/security/certificate_manager.go, line 657 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50082#-M9dI9kpCjoUit6yYA6L:-MAB4BzY9cuy2GNtS-kF:bb9o5r9) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f12e86814ee4c9e3a5a40d2953b8adbef9dda18/pkg/security/certificate_manager.go#L657)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Why is the work being done in GetConfigForClient instead of GetCertificate? You're not actually varying anything based on SNI. 
</blockquote></details>

a) I'm just cargo culting and b) `GetCertificate`  returns a certificate only, not a full `*tls.Config`. We could move things around so that we create most of the config statically in the beginning and return only the certificate from `GetCertificate` I suppose? I will leave it alone since it's not trivial.
___
*[pkg/security/certs.go, line 334 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50082#-M9dBFP929PG_wlD72aK:-MAB6ZjB6-iW58dtFVJb:b-l97i80) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f12e86814ee4c9e3a5a40d2953b8adbef9dda18/pkg/security/certs.go#L334)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

GenerateServerCert actually creates a dual-use client and server cert (see the way it sets ExtKeyUsage). The tenant server cert should be configured only for server usage. 
</blockquote></details>

Good point, fixed.

**Review by bdarnell — APPROVED** [review]
> Reviewed 1 of 1 files at r8, 28 of 29 files at r9, 2 of 2 files at r10, 3 of 3 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50082)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @bdarnell and @tbg)

___
*[pkg/security/certificate_manager.go, line 657 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/50082#-M9dI9kpCjoUit6yYA6L:-MASHxaWCv9Pe1K6R77D:b-ykd9uh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f12e86814ee4c9e3a5a40d2953b8adbef9dda18/pkg/security/certificate_manager.go#L657)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

a) I'm just cargo culting and b) `GetCertificate`  returns a certificate only, not a full `*tls.Config`. We could move things around so that we create most of the config statically in the beginning and return only the certificate from `GetCertificate` I suppose? I will leave it alone since it's not trivial.
</blockquote></details>

Ack. And now that I look at it, it may not be safe to do that refactoring, since one thing we're doing in GetConfigForClient is letting the client CA certs vary over time. I think this is probably an abuse of GetConfigForClient and we should be overwriting/regenerating the outermost tls.Config, but that's a bigger refactoring.

**Comment by tbg** [comment]
bors r=bdarnell,nvanbenschoten

Thanks for the reviews.

**Comment by tbg** [comment]
Caught a merge conflict, rebased and fixed now.

bors r=bdarnell,nvanbenschoten

**Pull request merged**
