### PR TITLE
roachtest: move CheckReplicaDivergenceOnDB to util

### PR DESCRIPTION
**Pull request by tbg**
This had no business sitting on `Cluster`.

Release note: None
Release justification: testing code

### CODE REVIEW

**Review by renatolabs — APPROVED** [review]
:lgtm:

Thanks for refactoring! I had seen this code in the past and thought it was weird that it was a method on `Cluster`.

Since we're looking at this code, I wanted to double check that the comments in that function are still accurate (that we need to set a timeout explicitly, and that the check can fail easily). @tbg would you know if that's still the case?

And a more general question: currently this function is only used by one upgrade test that doesn't use the `versionUpgradeTest` struct. Would this consistency check be useful in the other upgrade tests as well?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87383#-:-NBJcISNE50LcbAKhlWK:blbsj5h)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @srosenberg)

**Review by tbg — COMMENTED** [review]
> Since we're looking at this code, I wanted to double check that the comments in that function are still accurate (that we need to set a timeout explicitly, and that the check can fail easily). @tbg would you know if that's still the case?

They are, but I have a string of commits that make them more useful: https://github.com/cockroachdb/cockroach/pull/87378
TFTR!
bors r=renatolabs

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87383#-:-NBNUaPz8fOtumqN1cgZ:b-6raykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @srosenberg)

**Comment by tbg** [comment]
`eslint` failed on PR CI, but that's not this PR's fault, [discussion here](https://cockroachlabs.slack.com/archives/C016CAD2HQ8/p1662564795510359).

bors r=renatolabs

**Comment by tbg** [comment]
bors r=renatolabs

**Comment by tbg** [comment]
bors r=renatolabs

**Pull request merged**
