### PR TITLE
distsql: Implement EXCEPT and INTERSECT plans

### LINKED ISSUE #10432: distsql: Set operations (UNION, INTERSECT, EXCEPT)
Implementation of a processor "core" type from #7587. 
Set operations would include `UNION`, `UNION ALL`, `INTERSECT`, `INTERSECT ALL`, `EXCEPT`, `EXCEPT ALL`.

This processor, like join processors, would have two input streams and one output stream. Some of existing processor core type implementations under `pkg/sql/distsql` and spec definitions in `pkg/sql/distsql/processors.proto` can be used for reference.

### LINKED ISSUE #21661: distsql: Implement INTERSECT and EXCEPT plans using semi-joins and anti-joins
The `INTERSECT` operator is similar to a left semi-join, where rows on the left side are output if and only if they have a match on the right side, and all columns are equality columns. Similarly, `EXCEPT` is similar to a left anti-join, where rows on the left side are output if and only if they don't have a match on the right side, and all columns are equality columns. Therefore, it makes sense to plan these operations using joins, which would also allow us to leverage existing DistSQL join planning logic to distribute the computation.

The primary roadblock on this is the difference in duplicate semantics between `{INTERSECT,EXCEPT} ALL` and {semi,anti}-joins. Suppose a row has n duplicates on the left side and m duplicates on the right side. `INTERSECT ALL` requires that the result table contains min(n, m) duplicates, while a left semi-join will contain n duplicates. Similarly, `EXCEPT ALL` requires that the result table contains max(n-m, 0) duplicates, while a left anti-join will contain 0 duplicates.

### LINKED ISSUE #21706: distsql: EXCEPT ALL can be refactored as a left anti semi join
Currently we have a separate EXCEPT ALL processor. It can be refactored to use the new anti and semi join code, to reduce the maintenance burden of porting features (e.g. external storage) to more processors.

When doing this refactor, careful attention should be paid to behavior regarding duplicate rows. See #21530 for more details.

See the conversation in #21560, which refactored the EXCEPT ALL processor.

### PR DESCRIPTION
**Pull request by abhimadan**
Fixes #10432.
Fixes #21661.
Fixes #21706.

Release note (performance improvement): Support distributed execution of
INTERSECT and EXCEPT queries.

### CODE REVIEW

**Comment by solongordon** [comment]
Nice. The explain plans in your test cases look good to me. I left some suggestions, mostly around code clarity. Some of the implementation details (esp. in AddDistinctSetOpStage) are beyond my understanding so it would be good for someone with more distsql experience to have a look.

---

Review status: 0 of 3 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql_physical_planner.go, line 1956 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22442#-L5KYf0tcdOUvrjsa9m5:-L5KYf0tcdOUvrjsa9m6:b-75h8ph) ([raw file](https://github.com/cockroachdb/cockroach/blob/01b666aeaa77392f30cb0bc3d3ce345994caf5e9/pkg/sql/distsql_physical_planner.go#L1956)):*
> ```Go
> func (dsp *DistSQLPlanner) createPlanForSetOp(
> 	planCtx *planningCtx, n *unionNode,
> ) (physicalPlan, error) {
> ```

General comment: I had a hard time grokking this function since there are so many conditional branches for UNION vs. INTERSECT/EXCEPT and DISTINCT vs. ALL. Do you see any opportunities for refactoring to reduce this complexity? Not necessarily a blocker for this PR but it would be nice to get ahead of this.

---

*[pkg/sql/distsql_physical_planner.go, line 1976 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22442#-L5KPPzdFi69itXMMw5_:-L5KPPzdFi69itXMMw5a:b-4m5qhy) ([raw file](https://github.com/cockroachdb/cockroach/blob/01b666aeaa77392f30cb0bc3d3ce345994caf5e9/pkg/sql/distsql_physical_planner.go#L1976)):*
> ```Go
> 	// Even if the left and right planToStreamColMaps are mismatched,
> 	// they will have the same length, otherwise the logical plan would
> 	// not have been constructed.
> ```

Should we assert this and error if it's not the case?

---

*[pkg/sql/distsql_physical_planner.go, line 1988 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22442#-L5KSJZKr3-OOAsPs5mb:-L5KSJZKr3-OOAsPs5mc:b-hxtrd5) ([raw file](https://github.com/cockroachdb/cockroach/blob/01b666aeaa77392f30cb0bc3d3ce345994caf5e9/pkg/sql/distsql_physical_planner.go#L1988)):*
> ```Go
> 
> 	leftProps, rightProps := planPhysicalProps(leftLogicalPlan), planPhysicalProps(rightLogicalPlan)
> 	var leftDistinctOrd, rightDistinctOrd distsqlrun.Ordering
> ```

Looks like these don't need to be declared outside the `if !n.all` block.

---

*[pkg/sql/distsql_physical_planner.go, line 1994 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22442#-L5KZbEvrGDGhvTO4FRm:-L5KZbEwhrZwo-QHdvGI:b-vgxlns) ([raw file](https://github.com/cockroachdb/cockroach/blob/01b666aeaa77392f30cb0bc3d3ce345994caf5e9/pkg/sql/distsql_physical_planner.go#L1994)):*
> ```Go
> 	if !n.all {
> 		leftDistinctProps = leftProps.project(planCols)
> 		rightDistinctProps = rightProps.project(planCols)
> ```

Possibly more straightforward to just reassign `leftProps` and `rightProps` in the distinct case?

---

*[pkg/sql/distsql_physical_planner.go, line 2064 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22442#-L5KZnHzmP1QXvg3nNt3:-L5KZnHzmP1QXvg3nNt4:b-boxmpk) ([raw file](https://github.com/cockroachdb/cockroach/blob/01b666aeaa77392f30cb0bc3d3ce345994caf5e9/pkg/sql/distsql_physical_planner.go#L2064)):*
> ```Go
> 		// columns in the result.
> 		var newOrdering sqlbase.ColumnOrdering
> 		if n.all {
> ```

Wouldn't need this conditional if we reassign `leftProps` and `rightProps`.

---

*[pkg/sql/distsqlplan/physical_plan.go, line 843 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22442#-L5Ko_AnLODyJtAF8-n1:-L5Ko_AnLODyJtAF8-n2:bsa77ju) ([raw file](https://github.com/cockroachdb/cockroach/blob/01b666aeaa77392f30cb0bc3d3ce345994caf5e9/pkg/sql/distsqlplan/physical_plan.go#L843)):*
> ```Go
> // AddDistinctSetOpStage creates a distinct stage and a join stage to implement
> // INTERSECT and EXCEPT plans.
> func (p *PhysicalPlan) AddDistinctSetOpStage(
> ```

I noticed this has a fair bit of overlap with `AddJoinStage`. Any opportunity for code reuse here, or would that just make things more confusing?

---

*[pkg/sql/distsqlplan/physical_plan.go, line 858 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22442#-L5KjY4nLBoZoSC6NJvW:-L5KjY4nLBoZoSC6NJvX:b5co7o9) ([raw file](https://github.com/cockroachdb/cockroach/blob/01b666aeaa77392f30cb0bc3d3ce345994caf5e9/pkg/sql/distsqlplan/physical_plan.go#L858)):*
> ```Go
> 
> 	// Create a distinct stage, where left and right sources are sent by hash to
> 	// the node which will contain the join processor.
> ```

Might be worth adding a comment that the distinct stage must come before the join stage for EXCEPT to work properly. That was not at all obvious to me.

---

*[pkg/sql/distsqlplan/physical_plan.go, line 902 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22442#-L5Klea5Wxu1YdCVI8oN:-L5Klea5Wxu1YdCVI8oO:b-n5rgsu) ([raw file](https://github.com/cockroachdb/cockroach/blob/01b666aeaa77392f30cb0bc3d3ce345994caf5e9/pkg/sql/distsqlplan/physical_plan.go#L902)):*
> ```Go
> 	for bucket := 0; bucket < len(nodes); bucket++ {
> 		for side, routers := range inputResultRouters {
> 			pIdx := ProcessorIdx(distinctIdxStart + bucket*2 + side)
> ```

I see what's happening with this arithmetic but it's kind of confusing. Any way to make it more obvious?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22442#-:-L5KpHfSr07HurEd1Qvm:bljl6fd)*

**Comment by abhimadan** [comment]
Review status: 0 of 3 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsql_physical_planner.go, line 1956 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22442#-L5KYf0tcdOUvrjsa9m5:-L5LFtnz7zeDZV2GQomM:bflj34q) ([raw file](https://github.com/cockroachdb/cockroach/blob/01b666aeaa77392f30cb0bc3d3ce345994caf5e9/pkg/sql/distsql_physical_planner.go#L1956)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

General comment: I had a hard time grokking this function since there are so many conditional branches for UNION vs. INTERSECT/EXCEPT and DISTINCT vs. ALL. Do you see any opportunities for refactoring to reduce this complexity? Not necessarily a blocker for this PR but it would be nice to get ahead of this.
</blockquote></details>

I agree that this function needs to be refactored, but I don't see a simple way of doing it that I can include in this PR. I left a TODO to address this.

---

*[pkg/sql/distsql_physical_planner.go, line 1976 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22442#-L5KPPzdFi69itXMMw5_:-L5LG6SwZYrcx04vp6gk:b-q8ts0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/01b666aeaa77392f30cb0bc3d3ce345994caf5e9/pkg/sql/distsql_physical_planner.go#L1976)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

Should we assert this and error if it's not the case?
</blockquote></details>

I realized that the comment was somewhat misleading and this code did assume that the two sides had equivalent `planToStreamColMap`s, so I moved the `DeepEqual` up to here.

---

*[pkg/sql/distsql_physical_planner.go, line 1988 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22442#-L5KSJZKr3-OOAsPs5mb:-L5LGJvvzHIeSmeNr6q8:b-g7q827) ([raw file](https://github.com/cockroachdb/cockroach/blob/01b666aeaa77392f30cb0bc3d3ce345994caf5e9/pkg/sql/distsql_physical_planner.go#L1988)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

Looks like these don't need to be declared outside the `if !n.all` block.
</blockquote></details>

Thanks for catching this! Moved the ordering vars and removed the extra physical props (as per your comment below).

---

*[pkg/sql/distsql_physical_planner.go, line 1994 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22442#-L5KZbEvrGDGhvTO4FRm:-L5LGNad8KTPRfJinjZi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/01b666aeaa77392f30cb0bc3d3ce345994caf5e9/pkg/sql/distsql_physical_planner.go#L1994)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

Possibly more straightforward to just reassign `leftProps` and `rightProps` in the distinct case?
</blockquote></details>

Done.

---

*[pkg/sql/distsql_physical_planner.go, line 2064 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22442#-L5KZnHzmP1QXvg3nNt3:-L5LGPFbVlZaok34IkbA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/01b666aeaa77392f30cb0bc3d3ce345994caf5e9/pkg/sql/distsql_physical_planner.go#L2064)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

Wouldn't need this conditional if we reassign `leftProps` and `rightProps`.
</blockquote></details>

Done.

---

*[pkg/sql/distsqlplan/physical_plan.go, line 843 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22442#-L5Ko_AnLODyJtAF8-n1:-L5LIQ4IzABhL-SX5Gfl:by0jbjx) ([raw file](https://github.com/cockroachdb/cockroach/blob/01b666aeaa77392f30cb0bc3d3ce345994caf5e9/pkg/sql/distsqlplan/physical_plan.go#L843)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

I noticed this has a fair bit of overlap with `AddJoinStage`. Any opportunity for code reuse here, or would that just make things more confusing?
</blockquote></details>

I did copy a lot of code from `AddJoinStage` here at the beginning, but in its current state, I think there are enough small differences between the two that factoring out shared logic might make it more confusing. I'll think about this a bit more though, and see if there are some useful helpers that can be added (maybe one for wiring up hash-routed inputs to a set of processors?).

---

*[pkg/sql/distsqlplan/physical_plan.go, line 858 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22442#-L5KjY4nLBoZoSC6NJvW:-L5LGR_upCQa1RzmPRLU:b7zx7uj) ([raw file](https://github.com/cockroachdb/cockroach/blob/01b666aeaa77392f30cb0bc3d3ce345994caf5e9/pkg/sql/distsqlplan/physical_plan.go#L858)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

Might be worth adding a comment that the distinct stage must come before the join stage for EXCEPT to work properly. That was not at all obvious to me.
</blockquote></details>

Done. Also gave an example query where `EXCEPT` won't work without the input distinct stage.

---

*[pkg/sql/distsqlplan/physical_plan.go, line 902 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/22442#-L5Klea5Wxu1YdCVI8oN:-L5LHV8UMmsJz0UFsxka:b-8la9fv) ([raw file](https://github.com/cockroachdb/cockroach/blob/01b666aeaa77392f30cb0bc3d3ce345994caf5e9/pkg/sql/distsqlplan/physical_plan.go#L902)):*
<details><summary><i>Previously, solongordon wrote…</i></summary><blockquote>

I see what's happening with this arithmetic but it's kind of confusing. Any way to make it more obvious?
</blockquote></details>

I made a constant and computed the index offset from the bucket separately. Not sure if this helps, but at least the seemingly random 2 is gone.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22442)*

**Comment by solongordon** [comment]
:lgtm: 

---

Review status: 0 of 3 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22442#-:-L5LQKHcyklxuxK7wZLV:bg7igkv)*

**Comment by abhimadan** [comment]
@RaduBerinde can you take a look at this PR as a second reviewer for giving the green light?

**Comment by RaduBerinde** [comment]
Great work! I know it can get very tedious making sure we come up with a correct plan. I have a few comments, nothing major.

---

Review status: 0 of 3 files reviewed at latest revision, 12 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql_physical_planner.go, line 1956 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22442#-L5PKAh9CCTwVesd_eny:-L5PKAh9CCTwVesd_enz:bjgwhcr) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b433d509eb0985a2299cd62efe92759513db6d2/pkg/sql/distsql_physical_planner.go#L1956)):*
> ```Go
> // TODO(abhimadan): Refactor this function to reduce the UNION vs
> // EXCEPT/INTERSECT and DISTINCT vs ALL branching.
> func (dsp *DistSQLPlanner) createPlanForSetOp(
> ```

Please add a comment explaining what the plan is supposed to look like. It should list the distinct stages and the join stage and provide a few examples.

---

*[pkg/sql/distsql_physical_planner.go, line 2166 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22442#-L5PJVLwaCoMJih70iqD:-L5PJVLwaCoMJih70iqE:booq8km) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b433d509eb0985a2299cd62efe92759513db6d2/pkg/sql/distsql_physical_planner.go#L2166)):*
> ```Go
> 			)
> 		} else {
> 			p.AddDistinctSetOpStage(
> ```

We should elide the distinct stages when we know the inputs don't have duplicates (i.e. the physicalProps show that we have a key). This can be a TODO for now.

---

*[pkg/sql/distsqlplan/physical_plan.go, line 864 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22442#-L5PKk4f-Q4PsGDXZGz3:-L5PKk4f-Q4PsGDXZGz4:b-abuf6i) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b433d509eb0985a2299cd62efe92759513db6d2/pkg/sql/distsqlplan/physical_plan.go#L864)):*
> ```Go
> 	// (2) if there was no distinct processor before the EXCEPT ALL join).
> 	distinctIdxStart := len(p.Processors)
> 	distinctStageID := p.NewStageID()
> ```

It would be good if the distinct processors for the left side would have a different StageID from those on the right side (in the plan viewer, hovering above one of them should show highlight the ones for that side only). In addition, we will need (at some point) the ability to decide to elide the distinct stage on either side (or both), so it would be worth looking at reorganizing this code to have an outer`for side` loop and deal with each side separately.

---

*[pkg/sql/logictest/testdata/logic_test/distsql_union, line 62 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22442#-L5PIWlGVr729c7rdXDI:-L5PIWlHyDGBIBJoZlhY:b-8nke34) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b433d509eb0985a2299cd62efe92759513db6d2/pkg/sql/logictest/testdata/logic_test/distsql_union#L62)):*
> ```
> SELECT "URL" FROM [EXPLAIN (DISTSQL) SELECT x FROM xyz UNION SELECT x FROM xyz ORDER BY x]
> ----
> https://cockroachdb.github.io/distsqlplan/decode.html?eJzElrFunEAQhvs8RTRttvDsgh1TUaRxE0dOuoiCsCML6cyi3UWyY_HuEVA4nI7ZQ6ClBO6fj__mk5Z3aIym7-ULOch-A4IACQIUCEhAQAqFgNaaipwzdvjJFHjQr5DdCKibtvPD7UJAZSxB9g6-9ieCDH6Vf070RKUmCwI0-bI-jZDW1i-lfctf3_6CgMfOZ59zhKIXYDr_Mc_58pkgw15cz_xWO183lZ8Dc7yCI9dwduqmInVLFjkf47vGWE2W9Gx-0a95kyV-uqbnT2P9-d-a45fF4bez4XiAlAHmblLG6aYidZtLKQ_YW4C5297idFORus33pg7YW4C5297idFORus33lhywtwBzt73F6aYidVs-vC9wnsi1pnF0dohfnnwzHO6kn2n6EnCmsxX9sKYaMdPl45gbb2hyfnqK08VDMz0aXvD_MLLhZBbG87Bkw4onqy3khA2nPDllw1Ly6Vs2fceH77aU_sqG73ny_RYyBhwLSbbJMuQ1w4BnuEk05E3DgGrIuxaC865hQDbcZBvyumHAN9wknOSFkwHh5Drhiv7TvwAAAP__yzkLEg==
> ```

Are these changes intended? We are adding an unnecessary projection, it would be nice to not set it if it doesn't do anything. Maybe physicalPlan.AddProjection could check for identity (though if you want to do that, please do it in a separate commit as it will probably improve other existing plans).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22442#-:-L5PLZ695dHIIkjlmu2k:b-5zkblz)*

**Comment by abhimadan** [comment]
Review status: 0 of 3 files reviewed at latest revision, 12 unresolved discussions.

---

*[pkg/sql/distsql_physical_planner.go, line 1956 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22442#-L5PKAh9CCTwVesd_eny:-L5Pjh-L_S8k0cvHiRe7:b-7yavom) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b433d509eb0985a2299cd62efe92759513db6d2/pkg/sql/distsql_physical_planner.go#L1956)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Please add a comment explaining what the plan is supposed to look like. It should list the distinct stages and the join stage and provide a few examples.
</blockquote></details>

Done. I only gave single-node examples because my ASCII art skills can only take me so far, and the logic tests are a better source for up-to-date EXPLAIN diagrams.

---

*[pkg/sql/distsql_physical_planner.go, line 2166 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22442#-L5PJVLwaCoMJih70iqD:-L5PjsqQ6E08wFsrq-6N:becmsse) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b433d509eb0985a2299cd62efe92759513db6d2/pkg/sql/distsql_physical_planner.go#L2166)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We should elide the distinct stages when we know the inputs don't have duplicates (i.e. the physicalProps show that we have a key). This can be a TODO for now.
</blockquote></details>

Made a TODO at `AddDistinctSetOpStage`.

---

*[pkg/sql/distsqlplan/physical_plan.go, line 864 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22442#-L5PKk4f-Q4PsGDXZGz3:-L5PjxzIS-3p6ZeaVL-r:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b433d509eb0985a2299cd62efe92759513db6d2/pkg/sql/distsqlplan/physical_plan.go#L864)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It would be good if the distinct processors for the left side would have a different StageID from those on the right side (in the plan viewer, hovering above one of them should show highlight the ones for that side only). In addition, we will need (at some point) the ability to decide to elide the distinct stage on either side (or both), so it would be worth looking at reorganizing this code to have an outer`for side` loop and deal with each side separately.
</blockquote></details>

Done.

---

*[pkg/sql/logictest/testdata/logic_test/distsql_union, line 62 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22442#-L5PIWlGVr729c7rdXDI:-L5Pjz6zibF4ogkBhbZX:b8z13al) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b433d509eb0985a2299cd62efe92759513db6d2/pkg/sql/logictest/testdata/logic_test/distsql_union#L62)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Are these changes intended? We are adding an unnecessary projection, it would be nice to not set it if it doesn't do anything. Maybe physicalPlan.AddProjection could check for identity (though if you want to do that, please do it in a separate commit as it will probably improve other existing plans).
</blockquote></details>

I like the idea of changing AddProjection. I'll make a follow-up PR to make that change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22442)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql_physical_planner.go, line 1957 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22442#-L5QP6WnAPVT_XUd7sc3:-L5QP6WnAPVT_XUd7sc4:bwyswz) ([raw file](https://github.com/cockroachdb/cockroach/blob/0469aeeb04c98e286f6ff8c8c1914606c64311ea/pkg/sql/distsql_physical_planner.go#L1957)):*
> ```Go
> // EXCEPT/INTERSECT and DISTINCT vs ALL branching.
> //
> // createPlanForSetOp creates a physical plan for "set operations". UNION plans
> ```

Very nice comment, thanks!

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22442#-:-L5QPL052fEPALCcHydm:bnfp4nl)*

**Comment by abhimadan** [comment]
TFTRs!

---

Review status: 0 of 3 files reviewed at latest revision, 11 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22442#-:-L5QSyhu7nsjV0AGgrbM:bz5mair)*

**Pull request merged**
