### PR TITLE
client: pool allocations of client.Batch

### PR DESCRIPTION
**Pull request by jordanlewis**
This object is over 1500 bytes and is frequently allocated just to be
thrown away again right away. Use a sync pool to avoid these
allocations.

Release note: None

### CODE REVIEW

**Review by nvb — CHANGES_REQUESTED** [review]
I like the idea! I hear you typing, which must mean that benchmark results are on the way.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33521#-:-LVQIwse-vABt8wDbwWU:btaj4ex)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/internal/client/batch.go, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33521#-LVQIkVv1VZ0UY_5IIPX:-LVQIkVv1VZ0UY_5IIPY:bqw7lhu) ([raw file](https://github.com/cockroachdb/cockroach/blob/af873c60691e84f2ea7a4885e52e486706fdff37/pkg/internal/client/batch.go#L104)):*
> ```Go
> }
> 
> func (b *Batch) release() {
> ```

I'd export this. We discussed in person that it's ok to "leak" these, but let's give users an easy way to recycle `Batch`es if their lifetimes are clean.
___
*[pkg/internal/client/db.go, line 348 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33521#-LVQIKGP9_UExtRtgFMd:-LVQIKGQDhfp63gdrjkz:bv4ki93) ([raw file](https://github.com/cockroachdb/cockroach/blob/af873c60691e84f2ea7a4885e52e486706fdff37/pkg/internal/client/db.go#L348)):*
> ```Go
> 	b.PutInline(key, value)
> 	err := getOneErr(db.Run(ctx, b), b)
> 	b.release()
> ```

nit: might as well just use a `defer` for all of these.

**Review by andreimatei — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33521)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/internal/client/batch.go, line 70 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33521#-LVda3841_azNpZl-sW6:-LVda3841_azNpZl-sW7:b-jutb10) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f86ce82145d568d7fa36725e36550ee3d7d40f4/pkg/internal/client/batch.go#L70)):*
> ```Go
> }
> 
> var batchPool = sync.Pool{
> ```

ummm I think globals are always evil. I'd hang this from the DB.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33521)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/internal/client/batch.go, line 70 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33521#-LVda3841_azNpZl-sW6:-LVeLA_14wAg5FzTX4Gh:b-soq863) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f86ce82145d568d7fa36725e36550ee3d7d40f4/pkg/internal/client/batch.go#L70)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

ummm I think globals are always evil. I'd hang this from the DB.
</blockquote></details>

`sync.Pool`'s are one of the few exceptions. If they don't need to be scoped to some tighter scope then they're always declared statically.

**Review by andreimatei — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33521)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/internal/client/batch.go, line 70 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33521#-LVda3841_azNpZl-sW6:-LVePb1b4XGXExOUC5Yq:b-drv4l4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f86ce82145d568d7fa36725e36550ee3d7d40f4/pkg/internal/client/batch.go#L70)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`sync.Pool`'s are one of the few exceptions. If they don't need to be scoped to some tighter scope then they're always declared statically.
</blockquote></details>

But why? Think concurrent tests with one of them being buggy and releasing batches prematurely.

**Review by andreimatei — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33521)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/internal/client/batch.go, line 70 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33521#-LVda3841_azNpZl-sW6:-LVePzk-0eD7bKJ6-ITm:b272027) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f86ce82145d568d7fa36725e36550ee3d7d40f4/pkg/internal/client/batch.go#L70)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

But why? Think concurrent tests with one of them being buggy and releasing batches prematurely.
</blockquote></details>

Also think benchmarks that want to start from a clean state regardless of whether they run in isolation or after some other benchmark.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33521)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/internal/client/batch.go, line 70 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/33521#-LVda3841_azNpZl-sW6:-LVeWBA29IBLRONdJ4Kr:bwvksji) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f86ce82145d568d7fa36725e36550ee3d7d40f4/pkg/internal/client/batch.go#L70)):*
> But why? Think concurrent tests with one of them being buggy and releasing batches prematurely.

Assuming complete isolation between tests in every single case seems like a fraught effort in Go.

> Also think benchmarks that want to start from a clean state regardless of whether they run in isolation or after some other benchmark.

This is more compelling, but if anything, I'd want my benchmarks to start with all pools properly primed to simulate real-world performance.

`DB` has a large enough lifetime that I don't feel super strongly about this, so I'll defer to Jordan.

**Comment by petermattis** [comment]
@jordanlewis Are you planning to do anything with this PR? It has been open a long time.

**Comment by jordanlewis** [comment]
Nope. @nvanbenschoten I'll close this but I do think `client.Batch` is a sad state of affairs for allocations, think you can figure out how to fix it? :)

**Pull request closed without merging**
