### PR TITLE
Enable 1PC optimization for inserts.

### PR DESCRIPTION
**Pull request by petermattis**
```
name                   old time/op  new time/op  delta
Insert1_Cockroach-8     876µs ± 1%   542µs ± 2%  -38.20%  (p=0.000 n=8+10)
Insert10_Cockroach-8   1.26ms ± 2%  0.94ms ± 0%  -25.69%  (p=0.000 n=10+7)
Insert100_Cockroach-8  4.77ms ± 1%  4.45ms ± 1%   -6.65%  (p=0.000 n=10+9)
```

See #3417.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3616)

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM, though a comment in the code about this being hackish/preliminary in nature would be good.

**Comment by tamird** [comment]
LGTM

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/insert.go, line 249 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3616#-K7HScC8AK_w2ETYPj1L:-K7HScC8AK_w2ETYPj1M:-1052461493) ([raw file](https://github.com/cockroachdb/cockroach/blob/223f90c09479057e63ca01db4dca4248b0d8b57b/sql/insert.go#L249)):*
weird to see a dereference here - can you change `(*Txn).NewBatch` to `(*Txn).MakeBatch` and have it return a value?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3616#-:-K7HSzDSxXd9j29EUrEw:676834233)*

**Comment by vivekmenezes** [comment]
LGTM

**Comment by petermattis** [comment]
@tschottdorf: Comment add to `planner.makePlan`.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/insert.go, line 249 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3616#-K7HScC8AK_w2ETYPj1L:-K7HTJl0qzng-FkQNKTw:508177647) ([raw file](https://github.com/cockroachdb/cockroach/blob/223f90c09479057e63ca01db4dca4248b0d8b57b/sql/insert.go#L249)):*
The returned `Batch` value will have to be heap allocated in order to be passed to `Txn.Run`. I suppose we could clean that up as well, but that's beyond the scope of this PR. I'll file an issue. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3616#-:-K7HU7dEE2BWLdjiY2sp:270716273)*

**Comment by tschottdorf** [comment]
Reviewed 5 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3616)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[sql/insert.go, line 249 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3616#-K7HScC8AK_w2ETYPj1L:-K7HVnYqBmX3nw-TpjYF:770067588) ([raw file](https://github.com/cockroachdb/cockroach/blob/223f90c09479057e63ca01db4dca4248b0d8b57b/sql/insert.go#L249)):*
As discussed in person, `Txn.Run` mutates its argument, so its signature must remain as-is. The returned `Batch` will have to be heap allocated, that's true, but that's a compiler limitation, not an inherent property of this code - if/when the compiler's escape analysis becomes more sophisticated, a by-value `Batch` may be put on the stack, while a reference will probably be forced on the heap.

Thinking about this a bit more, a future compiler with such an optimization may also stack-allocate the pointer case, if it can infer that the referenced memory doesn't escape. With that, this is just a matter of taste, so whatever you prefer is fine.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3616)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/insert.go, line 249 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3616#-K7HScC8AK_w2ETYPj1L:-K7Hj7Lq1ce5miFv-Ub1:2132675254) ([raw file](https://github.com/cockroachdb/cockroach/blob/223f90c09479057e63ca01db4dca4248b0d8b57b/sql/insert.go#L249)):*
I'm going to leave this as-is for now. Feels like a change here might be the wrong one and we'll surely be aware of when the compiler gets better escape-analysis.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3616)*

**Pull request merged**
