### PR TITLE
sql: fix reparse issues due to string syntax

### PR DESCRIPTION
**Pull request by e-mbrown**
Related to: #60722

Certain statements were dealing with reparse issues
due to string syntax. This change adds a case for
statments requiring string syntax solving the issues.

Release note:None

Release justification: low risk, high priority change

### CODE REVIEW

**Review by otan — APPROVED** [review]
looks good! needs a rebase before you merge i think

Your commit message has a typo, can you amend it? Maybe:
```
Certain statements were dealing with reparse issues
due to string syntax emitting the non-string `_`. This
commit changes this by emitting `'_'` instead so it can
be reparsed.
```

**Comment by e-mbrown** [comment]
bors r=otan

**Comment by otan** [comment]
i'm going to bors this for you, as there may be changes coming which will cause this conflict again!
bors r+

**Comment by otan** [comment]
looks like you'll need to add a `Release justification: low risk, high priority change` to your commit

**Pull request merged**
