### PR TITLE
roachtest: two easy changefeed test fixes

### PR DESCRIPTION
**Pull request by danhhz**
See commits for details

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35654)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz and @tbg)

___
*[pkg/cmd/roachtest/cdc.go, line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35654#-L_n1FiJ4UP_JTx4Hi-m:-L_n1FiK9NAcXtb-DjLE:b-je4dcn) ([raw file](https://github.com/cockroachdb/cockroach/blob/f325b2d09f13549557579c826fed722ed202622d/pkg/cmd/roachtest/cdc.go#L76)):*
> ```Go
> 	// The 2.1 branch doesn't have this cluster setting, so ignore the error if
> 	// there is one.
> 	_, _ = db.Exec(`SET CLUSTER SETTING changefeed.push.enabled = $1`, args.rangefeed)
> ```

For our own sanity, it's probably a better idea to do something like `disableLoadBasedSplitting` so that we don't swallow an unrelated error and spend hours debugging an issue that we don't think is possible with rangefeeds. Maybe even pull that logic into a setting-agnostic utility function.
___
*[pkg/cmd/roachtest/cluster.go, line 921 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35654#-L_n0ihyDxpvKot_LCBh:-L_n0ihz1Uyzr_Vejh0j:b-we14m8) ([raw file](https://github.com/cockroachdb/cockroach/blob/552f61d62d6d0455a8c31e7c958a3de6e7941727/pkg/cmd/roachtest/cluster.go#L921)):*
> ```Go
> 			"./cockroach", "debug", "zip", "--url", "{pgurl:1}", zipName)
> 		if err != nil {
> 			c.l.Printf("./cockroach debug zip failed: %s", output)
> ```

I suspect that this output is going to be useless because it is formatting a byte slice with the `%s` verb.

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35654)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @tbg)

___
*[pkg/cmd/roachtest/cdc.go, line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/35654#-L_n1FiJ4UP_JTx4Hi-m:-L_n3m8O1tMQqiAVPbyz:b17vnke) ([raw file](https://github.com/cockroachdb/cockroach/blob/f325b2d09f13549557579c826fed722ed202622d/pkg/cmd/roachtest/cdc.go#L76)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

For our own sanity, it's probably a better idea to do something like `disableLoadBasedSplitting` so that we don't swallow an unrelated error and spend hours debugging an issue that we don't think is possible with rangefeeds. Maybe even pull that logic into a setting-agnostic utility function.
</blockquote></details>

Done. Seems like a `SET CLUSTER SETTING IF EXISTS` would be nice for this but that's certainly for another PR
___
*[pkg/cmd/roachtest/cluster.go, line 921 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35654#-L_n0ihyDxpvKot_LCBh:-L_n3xz9-MFAJkpm7kPu:b-5f3815) ([raw file](https://github.com/cockroachdb/cockroach/blob/552f61d62d6d0455a8c31e7c958a3de6e7941727/pkg/cmd/roachtest/cluster.go#L921)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I suspect that this output is going to be useless because it is formatting a byte slice with the `%s` verb.
</blockquote></details>

I've always seen it be equivalent to first casting it to a string https://play.golang.org/p/cP6z0WOr8Q7. Anecdotally I also tested this codepath before sending the PR and saw it work

**Review by nvb — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35654#-:-L_n5II42bFgXotPBMDq:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz, @nvanbenschoten, and @tbg)

___
*[pkg/cmd/roachtest/cluster.go, line 921 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35654#-L_n0ihyDxpvKot_LCBh:-L_n5KzH8TvYBND3U0f7:b-n4cd5) ([raw file](https://github.com/cockroachdb/cockroach/blob/552f61d62d6d0455a8c31e7c958a3de6e7941727/pkg/cmd/roachtest/cluster.go#L921)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I've always seen it be equivalent to first casting it to a string https://play.golang.org/p/cP6z0WOr8Q7. Anecdotally I also tested this codepath before sending the PR and saw it work
</blockquote></details>

Ah, I was thinking `%v`. Carry on.

**Comment by danhhz** [comment]
TFTR!

bors r=nvanbenschoten

**Pull request merged**
