### PR TITLE
backupccl: replace restore2TB and restoretpccInc tests

### LINKED ISSUE #92699: backupccl: change default restore roachtest configuration
Our current restore roachtest suite should be updated to better reflect customer workloads/topologies. I propose creating a default topology/workload and refactoring our existing tests to be more intentional in how they branch from the default configuration. Ideally, each test that deviates from the default configuration should explicitly test how this deviation affects performance. The new default configuration is described in detail [here](https://docs.google.com/document/d/1HfCKk55NwxLuNL3Lg_rLsd8eIPz1bwdwPlhL0toptzw/edit).  

This issue will track work to:

- [x] create a new roachtest with the default configuration
- [ ] modify restore2TB/nodes=10 to use the new default workload
- [ ] modify restore2TB/nodes=32 to use the new default workload
- [ ] modify restore2TB/nodes=6/cpus=16/pd-volume=2500GB to use the default workload, 4 nodes, and the default pd-ssd size

Epic [CRDB-20915](https://cockroachlabs.atlassian.net/browse/CRDB-20915)

Jira issue: CRDB-21924

Epic CRDB-20915

### PR DESCRIPTION
**Pull request by msbutler**
This patch removes the restore2TB* roachtests which ran a 2TB bank restore to
benchmark restore performance across a few hardware configurations. This patch
also replaces the `restoreTPCCInc/nodes=10` test which tested our ability to
handle a backup with a long chain.

This patch also adds:
1. `restore/tpce/400GB/aws/nodes=4/cpus=16` to measure how per-node throughput
scales when the per node vcpu count doubles relative to default.
2. `restore/tpce/400GB/aws/nodes=8/cpus=8` to measure how per-node throughput
scales when the number of nodes doubles relative to default.
3. `restore/tpce/400GB/aws/backupsIncluded=48/nodes=4/cpus=8` to measure
restore reliability and performance on 48 length long backup chain relative to
default.

A future patch will update the fixtures used in the restore node shutdown
scripts, and add more perf based tests.

Fixes https://github.com/cockroachdb/cockroach/issues/92699

Release note: None

### CODE REVIEW

**Review by lidorcarmel — COMMENTED** [review]
overall makes sense, a few things:
- you're also dropping a tpcc roachperf, right? probably intentional, mention it in the pr/commit description?
- in roachperf we have 2 bank tests with 6 nodes, one has no data, I'm guessing it was removed from restore.go but not from roachperf? or something like that.. which brings me to the question - do you need to remove those from roachperf also?
- the 32 nodes bank test [1] shows a regression since last Dec, we're going to lose this info now. The newly added tests here don't backfill, so maybe we should keep those tests for a few more months to have an overlap with the new tests? WDYT?
[1] https://roachperf.crdb.dev/?filter=restore&view=restore2TB%2Fnodes%3D32&tab=gce

**Comment by msbutler** [comment]
> `you're also dropping a tpcc roachperf, right?`

- there's isn't actually a tpcc restore workload in roachperf, but your comment did made me realize I am dropping our current "long chain" roachtest. I will add a new variant of the long chain test once #98087 merges.

> do you need to remove those from roachperf also?

- i'm assuming that the DR team will stop using roachperf in a month or so once we can observe test perf in prom/grafana. So I dont think we need to do any extra clean up in roachperf. I'd rather let it rot >:)

to paraphrase your last question: " should we keep them around for a couple months for perf regression detection?"

- the roachperf graphs for the old tests aren't getting deleted, nor do I think anyone is actively looking into that regression.  - Further these bank2tb tests aren't a very good signal of restore perf as the fixtures were created in 2019. IMHO I don't think we can learn much wrt restore perf from these old tests. I also think the new tests provide much more general test coverage.
- We also need to delete them in the next few weeks anyway to let https://github.com/cockroachdb/cockroach/pull/93804 pass.

**Comment by lidorcarmel** [comment]
> the roachperf graphs for the old tests aren't getting deleted, nor do I think anyone is actively looking into that regression. - Further these bank2tb tests aren't a very good signal of restore perf as the fixtures were created in 2019

I think it is helpful to have it, it helps us understand that things regressed slowly in that time range. I know it's not the best test but it's info I'd like to have available for debugging. anyway, sounds like we'll have the history so we're good, thank you!

**Review by lidorcarmel — APPROVED** [review]

**Comment by msbutler** [comment]
TFTR!

bors r=lidorcarmel

**Pull request merged**
