### PR TITLE
clusterversion: temporarily set dev branch to false

### PR DESCRIPTION
**Pull request by celiala**
The Serverless team wants to ship a 23.1 build in early December to customers as a preview, which they would like to subsequently update to a beta and beyond.

This PR temporarily overrides the developmentBranch setting so that to generate an alpha that Serverless can use and then subsequently upgrade to release builds.

See internal Slack thread: https://cockroachlabs.slack.com/archives/CUVEFUU3C/p1668117198092449?thread_ts=1668111921.220539&cid=CUVEFUU3C

### CODE REVIEW

**Comment by celiala** [comment]
Adding `do-not-merge`, as this is to kick-off discussion.

**Comment by dt** [comment]
I don't think this is safe right now, until we bump minBinary to 22.2 given we've heard from engineers who said they've already broken <22.2 compatibility on the dev branch and that it would be too much to go back and figure out where.

I'm skeptical we want to do this at all, but certainly not until we bump minBinary.

**Comment by celiala** [comment]
> I don't think this is safe right now, until we bump minBinary to 22.2 

Doooh 🤦🏼‍♀️ . Right, this. Okay, I'd better prioritize https://github.com/cockroachdb/cockroach/pull/91559.

> I'm skeptical we want to do this at all..

Got it / makes sense 👍🏼 

Instead of this PR, an alternate proposal was to cut a distinct binary for serverless from a distinct branch that has a patch that marks it intentionally as not in the development branch.

[Closing this idea/proposal]

**Comment by dt** [comment]
I don't really know that the separate branch saves us from the underlying reasons we would not want to upgrade from an alpha cut while teams are making non-upgrade safe changes to a final; those still apply both in serverless and not.

**Pull request closed without merging**
