### PR TITLE
upgrades: remove pre-24.1 upgrades, rename obsolete gates

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### upgrades: remove pre-24.1 upgrades

Epic: REL-1163
Release note: None

#### clusterversion: rename obsolete gates

Prepend `TODO_Delete_` to obsolete gates. These will be cleaned up in
follow-up PRs.

Epic: REL-1163
Release note: None

### CODE REVIEW

**Review by celiala — APPROVED** [review]
thank you - LGTM!

versions in comments / example can stay as-is (noted inline)

> Reviewed 11 of 11 files at r1, 5 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128603#-:-O3nEeYR4HJeIl3qGvMj:bv9ciy5)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @msbutler, and @RaduBerinde)

___
*[`pkg/clusterversion/cockroach_versions.go` line 377 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128603#-O3nEJBu2j31UaLOUrt1:-O3nEJBu2j31UaLOUrt2:b-4cqmbq) ([raw file](https://github.com/cockroachdb/cockroach/blob/84a82dc402c6f64bdabcc901f2a6edf9e0ab6518/pkg/clusterversion/cockroach_versions.go#L377)):*
> ```Go
> 
> // finalVersion should be set on a release branch to the minted final cluster
> // version key, e.g. to TODO_Delete_V23_2 on the release-23.2 branch once it is minted.
> ```

example can stay `V23_2`
___
*[`pkg/clusterversion/cockroach_versions.go` line 405 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128603#-O3nEMSfDiGFwfrZnOP2:-O3nEMSg1Oy5GkkM4k2s:b-vk858f) ([raw file](https://github.com/cockroachdb/cockroach/blob/84a82dc402c6f64bdabcc901f2a6edf9e0ab6518/pkg/clusterversion/cockroach_versions.go#L405)):*
> ```Go
> 
> // ReleaseSeries returns the release series the Key. Specifically:
> //   - if the key corresponds to a final version (e.g. TODO_Delete_V23_2), the result has the
> ```

same (example can stay `V23_2`)

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/128603)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @celiala, and @msbutler)

___
*[`pkg/clusterversion/cockroach_versions.go` line 377 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128603#-O3nEJBu2j31UaLOUrt1:-O3nGWec0lPWzan5LEfq:b8gj3mm) ([raw file](https://github.com/cockroachdb/cockroach/blob/84a82dc402c6f64bdabcc901f2a6edf9e0ab6518/pkg/clusterversion/cockroach_versions.go#L377)):*
<details><summary><i>Previously, celiala wrote…</i></summary><blockquote>

example can stay `V23_2`
</blockquote></details>

Good catch, fixed!
___
*[`pkg/clusterversion/cockroach_versions.go` line 405 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/128603#-O3nEMSfDiGFwfrZnOP2:-O3nGXyWCGyKHQglOW8p:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/84a82dc402c6f64bdabcc901f2a6edf9e0ab6518/pkg/clusterversion/cockroach_versions.go#L405)):*
<details><summary><i>Previously, celiala wrote…</i></summary><blockquote>

same (example can stay `V23_2`)
</blockquote></details>

Done.

**Comment by RaduBerinde** [comment]
bots r+

**Pull request merged**
