### PR TITLE
prereqs: delete tests

### LINKED ISSUE #61924: broken tests in Bazel under `pkg/cmd`
The following tests are all broken in Bazel:

```
pkg/cmd/github-post
pkg/cmd/publish-artifacts
pkg/cmd/roachtest
pkg/cmd/teamcity-trigger
pkg/cmd/prereqs
pkg/cmd/cockroach-oss
```

There's a lot going on here, but I think generally all these tests expect to be run from the root of the checkout.

Jira issue: CRDB-2711

### LINKED ISSUE #92814: cmd/prereqs: TestPrereqs failed
cmd/prereqs.TestPrereqs [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/7785221?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/7785221?buildTab=artifacts#/) on release-22.2 @ [ca673993473629a46370100108dd8c185a592e91](https://github.com/cockroachdb/cockroach/commits/ca673993473629a46370100108dd8c185a592e91):

```
        --- FAIL: TestPrereqs/symlink=false/example.com/b (0.00s)
=== RUN   TestPrereqs/symlink=true/example.com/a/../b
    prereqs_test.go:135: failed to import example.com/a/../b: err: go resolves to executable in current directory (./go): stderr: 
        --- FAIL: TestPrereqs/symlink=true/example.com/a/../b (0.00s)
=== RUN   TestPrereqs/symlink=false/example.com/test
    prereqs_test.go:135: failed to import example.com/test: err: go resolves to executable in current directory (./go): stderr: 
        --- FAIL: TestPrereqs/symlink=false/example.com/test (0.00s)
=== RUN   TestPrereqs/symlink=true/example.com/a
    prereqs_test.go:135: failed to import example.com/a: err: go resolves to executable in current directory (./go): stderr: 
        --- FAIL: TestPrereqs/symlink=true/example.com/a (0.00s)
=== RUN   TestPrereqs/example.com/specialchars
    prereqs_test.go:166: failed to import example.com/specialchars: err: go resolves to executable in current directory (./go): stderr: 
    --- FAIL: TestPrereqs/example.com/specialchars (0.00s)
=== RUN   TestPrereqs/symlink=true/./vendor/foo.com/foo
    prereqs_test.go:135: failed to import ./vendor/foo.com/foo: err: go resolves to executable in current directory (./go): stderr: 
        --- FAIL: TestPrereqs/symlink=true/./vendor/foo.com/foo (0.00s)
=== RUN   TestPrereqs/symlink=true/example.com/test
    prereqs_test.go:135: failed to import example.com/test: err: go resolves to executable in current directory (./go): stderr: 
        --- FAIL: TestPrereqs/symlink=true/example.com/test (0.00s)
=== RUN   TestPrereqs/symlink=false/./vendor/foo.com/foo
    prereqs_test.go:135: failed to import ./vendor/foo.com/foo: err: go resolves to executable in current directory (./go): stderr: 
        --- FAIL: TestPrereqs/symlink=false/./vendor/foo.com/foo (0.00s)
=== RUN   TestPrereqs/symlink=false/example.com/vendor/foo.com/foo
    prereqs_test.go:135: failed to import example.com/vendor/foo.com/foo: err: go resolves to executable in current directory (./go): stderr: 
        --- FAIL: TestPrereqs/symlink=false/example.com/vendor/foo.com/foo (0.00s)
=== RUN   TestPrereqs/symlink=false
    --- FAIL: TestPrereqs/symlink=false (0.00s)
=== RUN   TestPrereqs/symlink=true/./a/../b
    prereqs_test.go:135: failed to import ./a/../b: err: go resolves to executable in current directory (./go): stderr: 
        --- FAIL: TestPrereqs/symlink=true/./a/../b (0.00s)
=== RUN   TestPrereqs/symlink=true/example.com/b
    prereqs_test.go:135: failed to import example.com/b: err: go resolves to executable in current directory (./go): stderr: 
        --- FAIL: TestPrereqs/symlink=true/example.com/b (0.00s)
=== RUN   TestPrereqs/symlink=true/example.com/vendor/foo.com/foo
    prereqs_test.go:135: failed to import example.com/vendor/foo.com/foo: err: go resolves to executable in current directory (./go): stderr: 
        --- FAIL: TestPrereqs/symlink=true/example.com/vendor/foo.com/foo (0.00s)
=== RUN   TestPrereqs/symlink=true
    --- FAIL: TestPrereqs/symlink=true (0.00s)
=== RUN   TestPrereqs/symlink=false/./b
    prereqs_test.go:135: failed to import ./b: err: go resolves to executable in current directory (./go): stderr: 
        --- FAIL: TestPrereqs/symlink=false/./b (0.00s)
=== RUN   TestPrereqs/symlink=false/./a/../b
    prereqs_test.go:135: failed to import ./a/../b: err: go resolves to executable in current directory (./go): stderr: 
        --- FAIL: TestPrereqs/symlink=false/./a/../b (0.00s)
=== RUN   TestPrereqs/symlink=false/example.com/a/../b
    prereqs_test.go:135: failed to import example.com/a/../b: err: go resolves to executable in current directory (./go): stderr: 
        --- FAIL: TestPrereqs/symlink=false/example.com/a/../b (0.00s)
=== RUN   TestPrereqs/symlink=true/./b
    prereqs_test.go:135: failed to import ./b: err: go resolves to executable in current directory (./go): stderr: 
        --- FAIL: TestPrereqs/symlink=true/./b (0.00s)
```
<p>Parameters: <code>TAGS=bazel,gss</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/dev-inf
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestPrereqs.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-21985

### PR DESCRIPTION
**Pull request by rickystewart**
These tests have always been skipped under Bazel because the implementation doesn't work in a Bazel world due to the dependency on `"golang.org/x/tools/go/packages"`. Since the command is only useful/ used in `make`, which is going to be deleted shortly, just delete the tests rather than waste time getting it working.

Also this is the last `broken_in_bazel` test, so rip out all the corresponding
logic too.

Epic: none
Release note: None
Closes: #61924
Closes: #92814

### CODE REVIEW

**Review by rail — APPROVED** [review]

**Comment by rickystewart** [comment]
bors r=rail

**Comment by rickystewart** [comment]
@rail FYI: I updated the PR to rip out `broken_in_bazel` infrastructure which is no longer necessary.

**Comment by rickystewart** [comment]
bors r=rail

**Comment by rickystewart** [comment]
bors r=rail

**Pull request merged**
