### PR TITLE
sql: show full table scans query

### LINKED ISSUE #41340: sql: SHOW FULL TABLE SCANS
Customers can have poor performance (and trigger support) if they see high latency related to mostly bad schema design (no indexes, a bunch of full table scans for instance). Right now, there is the ability to see full table scans via EXPLAIN or in the WebUI but it isn't front and center. There are various issues to expose it better in the WebuI but we could also improve this experience via SQL.

Similarly to https://github.com/cockroachdb/cockroach/issues/41259, we have an opportunity to improve our users experiences with full table scans by providing them tools to introspect them. One idea is a SHOW FULL TABLE SCANS query.

This tool would show all queries in the last hour that used a full table scan. We could order the list by frequency such to show the most frequently occurring full table scan. This, in conjunction with EXPLAIN or with https://github.com/cockroachdb/cockroach/issues/41259 would allow the users to improve their schema in service of their workload.

### PR DESCRIPTION
**Pull request by barryhe2000**
Show full table scans query shows queries that used a full table scan
within the past hour or two.

Fixes: #41340

Release note (sql change): SHOW FULL TABLE SCANS query added

### CODE REVIEW

**Comment by barryhe2000** [comment]
Screen Shot 2021-04-06 at 3 28 05 PM

Here's what my manual testing shows

**Review by yuzefovich — CHANGES_REQUESTED** [review]
Very nice!

As you can see, currently the build is green. You'll need to update the logic tests (because you're adding a new column to an internal table). You can do it with `make testbaselogic TESTFLAGS='-rewrite' FILES=create_statements` and run similar command for other relevant files. Also, you need to run `make bazel-generate` to update bazel dependencies.

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63165#-:-MXd18nVAYOpKVtkFrPL:b-7j3zre)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @barryhe2000)

___
*[pkg/sql/delegate/show_full_table_scans.go, line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63165#-MXd-S2r4BZnTqSGX3F_:-MXd-S2r4BZnTqSGX3Fa:b-x94v4j) ([raw file](https://github.com/cockroachdb/cockroach/blob/eaaae468ecdc0291cfbfc1fdac7b9afda78b9e5c/pkg/sql/delegate/show_full_table_scans.go#L19)):*
> ```Go
> 
> func (d *delegator) delegateShowFullTableScans(n *tree.ShowFullTableScans) (tree.Statement, error) {
> 	sqltelemetry.IncrementShowCounter(sqltelemetry.Queries)
> ```

I think we might want to introduce a separate counter for SHOW FULL TABLE SCANS. Using `sqltelemetry.Queries` tracks `SHOW QUERIES` command, and using the same counter will confuse our telemetry.
___
*[pkg/sql/delegate/show_full_table_scans.go, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63165#-MXd-qoE92a2dxyAr_9E:-MXd-qoE92a2dxyAr_9F:b-bdks4l) ([raw file](https://github.com/cockroachdb/cockroach/blob/eaaae468ecdc0291cfbfc1fdac7b9afda78b9e5c/pkg/sql/delegate/show_full_table_scans.go#L22)):*
> ```Go
> 	const query = `
>   SELECT 
>     key, count, rows_read_avg, bytes_read_avg, service_lat_avg, contention_time_avg, max_mem_usage_avg, network_bytes_avg, max_retries
> ```

nit: I'd name the first column as "query" or something like that, i.e. instead of `key,` use `key AS query,`.

Also the columns you chose seem reasonable to me, but I'd like to hear Andy's thoughts. cc @awoods187 @jordanlewis on which columns to show in this view.
___
*[pkg/sql/delegate/show_full_table_scans.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63165#-MXd09HGD_3uAe0pNNRx:-MXd09HGD_3uAe0pNNRy:b-ri0od2) ([raw file](https://github.com/cockroachdb/cockroach/blob/eaaae468ecdc0291cfbfc1fdac7b9afda78b9e5c/pkg/sql/delegate/show_full_table_scans.go#L23)):*
> ```Go
>   SELECT 
>     key, count, rows_read_avg, bytes_read_avg, service_lat_avg, contention_time_avg, max_mem_usage_avg, network_bytes_avg, max_retries
>   FROM crdb_internal.node_statement_statistics WHERE full_scan = TRUE`
> ```

We should specify an ORDER BY clause, I'd probably order by the number of times each query run or by the latency of the query. Andy suggested the former on the issue.
___
*[pkg/sql/sem/tree/stmt.go, line 1663 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63165#-MXd0vjRCboaMa1_j7QR:-MXd0vjRCboaMa1_j7QS:b-cffp6p) ([raw file](https://github.com/cockroachdb/cockroach/blob/eaaae468ecdc0291cfbfc1fdac7b9afda78b9e5c/pkg/sql/sem/tree/stmt.go#L1663)):*
> ```Go
> func (n *ShowTransactions) String() string               { return AsString(n) }
> func (n *ShowLastQueryStatistics) String() string        { return AsString(n) }
> func (n *ShowFullTableScans) String() string             { return AsString(n) }
> ```

super nit: it appears as if the list here is sorted (almost), so I'd put it a bit higher.

**Comment by yuzefovich** [comment]
Also, update the PR description to close the corresponding issue once the PR merges.

**Review by barryhe2000 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63165)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/delegate/show_full_table_scans.go, line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63165#-MXd-S2r4BZnTqSGX3F_:-MXdfUeTCyBD9cKA4rY4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eaaae468ecdc0291cfbfc1fdac7b9afda78b9e5c/pkg/sql/delegate/show_full_table_scans.go#L19)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I think we might want to introduce a separate counter for SHOW FULL TABLE SCANS. Using `sqltelemetry.Queries` tracks `SHOW QUERIES` command, and using the same counter will confuse our telemetry.
</blockquote></details>

Done.
___
*[pkg/sql/delegate/show_full_table_scans.go, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63165#-MXd-qoE92a2dxyAr_9E:-MXdfW7K4yjPk9tZkU7w:bt1b19p) ([raw file](https://github.com/cockroachdb/cockroach/blob/eaaae468ecdc0291cfbfc1fdac7b9afda78b9e5c/pkg/sql/delegate/show_full_table_scans.go#L22)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: I'd name the first column as "query" or something like that, i.e. instead of `key,` use `key AS query,`.

Also the columns you chose seem reasonable to me, but I'd like to hear Andy's thoughts. cc @awoods187 @jordanlewis on which columns to show in this view.
</blockquote></details>

Renamed.
___
*[pkg/sql/delegate/show_full_table_scans.go, line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63165#-MXd09HGD_3uAe0pNNRx:-MXdfY8W4kdp2IUMybcR:b-igb08y) ([raw file](https://github.com/cockroachdb/cockroach/blob/eaaae468ecdc0291cfbfc1fdac7b9afda78b9e5c/pkg/sql/delegate/show_full_table_scans.go#L23)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

We should specify an ORDER BY clause, I'd probably order by the number of times each query run or by the latency of the query. Andy suggested the former on the issue.
</blockquote></details>

Done by the former.
___
*[pkg/sql/sem/tree/stmt.go, line 1663 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63165#-MXd0vjRCboaMa1_j7QR:-MXdfb4p-A1kmYHCikoE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eaaae468ecdc0291cfbfc1fdac7b9afda78b9e5c/pkg/sql/sem/tree/stmt.go#L1663)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

super nit: it appears as if the list here is sorted (almost), so I'd put it a bit higher.
</blockquote></details>

Done.

**Comment by yuzefovich** [comment]
I see that you're trying to fix a logic test failure. You're adding a boolean column, and in the logic test it is `B` not `R` type (unlike all previous columns in the test which are either integers or decimals/floats). You can also try the fix locally with `make testbaselogic FILES=crdb_internal` and see whether the fix does work - no need to wait for CI for that.

**Review by barryhe2000 — COMMENTED** [review]
The odd thing is implicit_txn is also a boolean but it's currently R type instead of B, and also currently with this fix it shows a "pass" after running testbaselogic for crdb_internal, but regardless I'm looking through the other logictest files right now and I will change both of them to a B just to see the result.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63165#-:-MXe1G5BEx_8B1k1Z-VN:bgxs50e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @awoods187, @jordanlewis, and @yuzefovich)

**Comment by yuzefovich** [comment]
Oh, I see - because the query doesn't actually return any rows, you only need to specify the correct number of columns that are returned, and type information ends up being ignored.

**Comment by barryhe2000** [comment]
Screen Shot 2021-04-06 at 10 57 19 PM

Updated screenshot of what SHOW FULL TABLE SCANS currently looks like, with all tests passing and rows ordered by descending count.

**Comment by awoods187** [comment]
Nice! This is great!

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63165#-:-MXgx1UO87fZdOvTId0y:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @awoods187 and @barryhe2000)

___
*[pkg/sql/sem/tree/show.go, line 522 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63165#-MXgwlM61-WxbEtUom_F:-MXgwlM61-WxbEtUom_G:baq5mao) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eb2b536fa8259627b120aceb7cc0b62fca7d8b0/pkg/sql/sem/tree/show.go#L522)):*
> ```Go
> 
> // ShowLastQueryStatistics represents a SHOW LAST QUERY STATS statement.
> type ShowLastQueryStatistics struct {
> ```

super nit: no need to modify this. The reason why it is mildly important is that making this very minor change will make it so that on git blame your commit will show up, and not the one that introduced it or last time meaningfully modified it.

**Comment by barryhe2000** [comment]
TFTR!

bors r=yuzefovich

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63165)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @awoods187 and @barryhe2000)

___
*[pkg/sql/sem/tree/show.go, line 522 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63165#-MXgwlM61-WxbEtUom_F:-MXhSXUrCYQvGOMawwgK:b-hyrqg4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8eb2b536fa8259627b120aceb7cc0b62fca7d8b0/pkg/sql/sem/tree/show.go#L522)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

super nit: no need to modify this. The reason why it is mildly important is that making this very minor change will make it so that on git blame your commit will show up, and not the one that introduced it or last time meaningfully modified it.
</blockquote></details>

Note that I did leave this "super nit" comment (I think it's actually a "nit") which you should address/acknowledge somehow.

It is quite common to give an LGTM to a PR but leave some comments that affect only minor details and don't require an additional round of review once resolved.

**Comment by barryhe2000** [comment]
Nit fix.

bors r=yuzefovich

**Pull request merged**
