### PR TITLE
timeutil: prevent illegal sharing of Timers

### LINKED ISSUE #119593: stmtdiagnostics: seemingly a deadlock in spanlatch.(*Manager).wait
Extracted from [this](https://teamcity.cockroachdb.com/viewLog.html?buildId=14135501&buildTypeId=Cockroach_BazelEssentialCi) failure of `TestDiagnosticsRequest`:
```
* INFO: slow quiesce. stack traces:
...
    test_server_shim.go:157: automatically injected a shared process virtual cluster under test; see comment at top of test_server_shim.go for details.
...
goroutine 3547 [chan receive (nil chan), 4 minutes]:
github.com/cockroachdb/cockroach/pkg/util/timeutil.(*Timer).Reset(0xc0062988d0, 0xc002ad16f0?)
	github.com/cockroachdb/cockroach/pkg/util/timeutil/timer.go:83 +0x5a
github.com/cockroachdb/cockroach/pkg/kv/kvserver/spanlatch.(*Manager).wait(0xc004499b00?, {0x65c13b8, 0xc00163f290}, 0xc003f40400, {{{{0x0, 0x0}, {0x0, 0x0}}, {{0x0, 0x0}, ...}}})
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/spanlatch/manager.go:499 +0x8f
github.com/cockroachdb/cockroach/pkg/kv/kvserver/spanlatch.(*Manager).Acquire(0x4322203a2265756c?, {0x65c13b8, 0xc00163f290}, 0x51c9a46?, 0x22ee95b?, {0x6584680?, 0xc003c19320?})
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/spanlatch/manager.go:251 +0x1a5
github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency.(*latchManagerImpl).Acquire(0xc00449f2c0?, {0x65c13b8?, 0xc00163f290?}, {0x0, {0x17b68ddcf017e2ae, 0x0}, 0x0, 0x0, 0x0, 0x0, ...})
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency/latch_manager.go:29 +0x45
```
The test failed during the server shutdown. To me it seems like a deadlock - the timer in question uses 15 seconds.

I think we have a problematic pattern of using `timeutil.Timer` at least in `stmtdiagnostics.Registry.poll` - namely we allocate the timer locally but then calling `Stop` on it puts it into the `sync.Pool`, yet we later will keep on using the same timer which can result in concurrent access to the same timer object, which is invalid.

### PR DESCRIPTION
**Pull request by yuzefovich**
**timeutil: prevent illegal sharing of Timers**

Currently, whenever `Timer.Stop` is called, we unconditionally put that timer into `timerPool`. This works well assuming that the contract of `Stop` is satisfied - namely that the stopped timer can no longer be used.

However, we have at least one case where this contract is violated (fixed in the following commit), and in such a scenario it is possible for multiple users to access the same timer object which can lead to an undefined behavior (we've seen a deadlock on a test server shutdown).

This commit hardens the timer code to prevent a class of such issues by putting the timer into the pool on `Stop` only if the timer originally came from the pool.

Release note: None

**stmtdiagnostics: fix incorrect usage of timeutil.Timer**

The contract of `timeutil.Timer.Stop` is such that the timer can no longer be used, and it was violated in `Registry.poll`. This now fixed by allocating a fresh timer after each `Stop` call.

Fixes: #119593.

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
Nice debugging! The fix in the second commit here :lgtm:. I left a question about the first patch though.

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119595#-:-NrO37E9D_kkYJIidYNc:b-rt7b0g)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @yuzefovich)

___
*[`pkg/util/timeutil/timer.go` line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119595#-NrO2bGG90giCZ5iac5m:-NrO2bGG90giCZ5iac5n:bcssxk9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a20c30b46d878db20dd7465da31eaa5a4adf602/pkg/util/timeutil/timer.go#L110)):*
> ```Go
> 		}
> 	}
> 	if !t.fromPool {
> ```

I don't entirely follow why this provides protection from misuse if the contract is still that "a Timer must never be used again after calls to Stop". Is the idea that stack allocated timers (which I assume still escape to the heap and would always benefit from just using `NewTimer`) can now be re-used after Stop is called? In other words, is this allowing us to change the contract? Or just making a common misuse of the contract less impactful, with the assumption that stack allocation is often paired with violating this contract?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119595)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @nvanbenschoten)

___
*[`pkg/util/timeutil/timer.go` line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119595#-NrO2bGG90giCZ5iac5m:-NrO6Z7h0YfAi4TcPlty:b-z5z9ak) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a20c30b46d878db20dd7465da31eaa5a4adf602/pkg/util/timeutil/timer.go#L110)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I don't entirely follow why this provides protection from misuse if the contract is still that "a Timer must never be used again after calls to Stop". Is the idea that stack allocated timers (which I assume still escape to the heap and would always benefit from just using `NewTimer`) can now be re-used after Stop is called? In other words, is this allowing us to change the contract? Or just making a common misuse of the contract less impactful, with the assumption that stack allocation is often paired with violating this contract?
</blockquote></details>

This is a defensive mechanism that prevents problems from one class of misuse (like the one the second commit fixes). In particular, now with the "stack-allocated" (that, indeed, should actually escape) timer it won't ever be possible to share the timer by mistake. It is still possible for this problem to occur if the timer is created via `NewTimer` and the contract of `Stop` not being honored.

I'm somewhat on the fence about the first commit, but I'm leaning towards being defensive and merging it due to:
- if the timer originally didn't come from the pool, then it seems somewhat strange to put it into the pool on `Stop`
- this mechanism does protect from misuse - with low overhead - at least in some cases, and even very experienced engineers can make mistakes like this (the bug fixed in the second commit was introduced by Andrew W in 4ef67a0a98f22ad8b01aa2a46b46fad79e6c0df2).

**Review by mgartner — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119595#-:-Nrc2vFt470rKR4vzJzc:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @nvanbenschoten and @yuzefovich)

___
*[`-- commits` line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119595#-Nrc-QSwDwvQOzl9IJJj):*
nit: remove one of the two "only"'s
___
*[`pkg/util/timeutil/timer.go` line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119595#-NrO2bGG90giCZ5iac5m:-Nrc0v5T5y_DTVf3JUfj:b-lfz15h) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a20c30b46d878db20dd7465da31eaa5a4adf602/pkg/util/timeutil/timer.go#L110)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

This is a defensive mechanism that prevents problems from one class of misuse (like the one the second commit fixes). In particular, now with the "stack-allocated" (that, indeed, should actually escape) timer it won't ever be possible to share the timer by mistake. It is still possible for this problem to occur if the timer is created via `NewTimer` and the contract of `Stop` not being honored.

I'm somewhat on the fence about the first commit, but I'm leaning towards being defensive and merging it due to:
- if the timer originally didn't come from the pool, then it seems somewhat strange to put it into the pool on `Stop`
- this mechanism does protect from misuse - with low overhead - at least in some cases, and even very experienced engineers can make mistakes like this (the bug fixed in the second commit was introduced by Andrew W in 4ef67a0a98f22ad8b01aa2a46b46fad79e6c0df2).
</blockquote></details>

Is there any reasonable use case for a stack allocated timer? If not, why not prevent stack allocated timers by making `Timer` a point to an internal type struct:

```go
type Timer = *t

type t struct {
	timer *time.Timer
	// C is a local "copy" of timer.C that can be used in a select case before
	// the timer has been initialized (via Reset).
	C    <-chan time.Time
	Read bool
}
```

Then trying to use an uninitialized `var t Timer` will result in a NPE, which should force all timers to be allocated via the pool.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119595)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @nvanbenschoten)

___
*[`pkg/util/timeutil/timer.go` line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119595#-NrO2bGG90giCZ5iac5m:-NrcBzcU-38OLJ0k1_Zq:b-ioktye) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a20c30b46d878db20dd7465da31eaa5a4adf602/pkg/util/timeutil/timer.go#L110)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Is there any reasonable use case for a stack allocated timer? If not, why not prevent stack allocated timers by making `Timer` a point to an internal type struct:

```go
type Timer = *t

type t struct {
	timer *time.Timer
	// C is a local "copy" of timer.C that can be used in a select case before
	// the timer has been initialized (via Reset).
	C    <-chan time.Time
	Read bool
}
```

Then trying to use an uninitialized `var t Timer` will result in a NPE, which should force all timers to be allocated via the pool.
</blockquote></details>

On a quick search there are like 20 places where the timers are allocated on the "stack" and don't use the pool. For example, `replicaScanner` from `server/scanner.go` - it seems reasonable to me that we embed the timer into the parent struct to avoid accessing `timerPool` (although, later, on `Reset` we'll still access the shared `timeTimerPool`). To me this seems like a reasonable use case  since we avoid an extra pointer to track / extra access to `timerPool` - WDYT?

**Comment by mgartner** [comment]
*[`pkg/util/timeutil/timer.go` line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119595#-NrO2bGG90giCZ5iac5m:-NrfzaUF6XHWN54Go9e9:b-k4n5vg) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a20c30b46d878db20dd7465da31eaa5a4adf602/pkg/util/timeutil/timer.go#L110)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

On a quick search there are like 20 places where the timers are allocated on the "stack" and don't use the pool. For example, `replicaScanner` from `server/scanner.go` - it seems reasonable to me that we embed the timer into the parent struct to avoid accessing `timerPool` (although, later, on `Reset` we'll still access the shared `timeTimerPool`). To me this seems like a reasonable use case  since we avoid an extra pointer to track / extra access to `timerPool` - WDYT?
</blockquote></details>

I see, makes sense. No need to disallow stack allocation here then.

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119595)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[`pkg/util/timeutil/timer.go` line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119595#-NrO2bGG90giCZ5iac5m:-NrsoetD-w-aIjmPGtBv:b93z2nr) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a20c30b46d878db20dd7465da31eaa5a4adf602/pkg/util/timeutil/timer.go#L110)):*
> Is the idea that stack allocated timers (which I assume still escape to the heap and would always benefit from just using NewTimer) can now be re-used after Stop is called? In other words, is this allowing us to change the contract?

So can the contact be relaxed now for timers that didn't come from the pool? Seems like code actually does want to reuse timers after `Stop`.

**Pull request merged**
