### PR TITLE
sql: normalize IS/IS NOT to IS NOT DISTINCT FROM/IS DISTINCT FROM

### LINKED ISSUE #19111: sql: normalize IS/IS NOT to IS NOT DISTINCT FROM/IS DISTINCT FROM
`IS` and `IS NOT` expressions are specializations of `IS NOT DISTINCT FROM` and `IS DISTINCT FROM`, respectively. These specialized expressions behave the same way as their more general forms but have a limited set of allowable values (`NULL`, `UNKNOWN` (same as null), `TRUE`, `FALSE`, `NaN`) as their right operand. On the other hand, the general forms can have any arbitrarily-complex expression as their right operand. Unlike standard comparison operations that propagate `NULL` values if seen for either of their operands, these four expressions all treat `NULL` like an ordinary value (see [Postgres' docs](https://www.postgresql.org/docs/9.6/static/functions-comparison.html#FUNCTIONS-COMPARISON-PRED-TABLE)). 

It doesn't make sense for us to worry about four comparison operators during index selection or evaluation if `IS` and `IS NOT` can be normalized to their more general forms. In fact, because we don't perform this normalization in all cases right now, our index selection logic is lacking in certain cases for the `IS (NOT) DISTINCT FROM` expressions. We should add the following normalization rules to `normalize.go` (`ComparisonExpr.normalize`) and remove all references to the `Is` and `IsNot` operator above the normalization step (expr simplification, index selection, evaluation):
```
ComparisonExpr{Is,   left,right} -> ComparisonExpr{IsNotDistinctFrom,left,right}
ComparisonExpr{IsNot,left,right} -> ComparisonExpr{IsDistinctFrom,   left,right}
```

### PR DESCRIPTION
**Pull request by yuhit**
Fixes #19111.

Normalise Is/IsNot to IsDistinctFrom/IsNotDistinctFrom, and change all references to the Is and IsNot operator.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
What's the motivation for this? `IS NULL`, `IS NOT NULL` are ANSI standard and used by other databases.

**Comment by nvanbenschoten** [comment]
Thanks @yuhit! I'll be reviewing this shortly.

@RaduBerinde this is addressing https://github.com/cockroachdb/cockroach/issues/19111.

**Comment by nvanbenschoten** [comment]
Awesome job @yuhit! I left a few comments but overall this looks good.

I'd be curious if @knz has any input here.

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/sql/group.go, line 465 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20346#-L-Cq_60nQOSikiD5Zg_:-L-Cq_61W1CbBXAj4Nrw:bozgirm) ([raw file](https://github.com/cockroachdb/cockroach/blob/3667428d275649a0c2eb833e076db6a994a9adf0/pkg/sql/group.go#L465)):*
> ```Go
> // isNotNullFilter adds as a "col IS DISTINCT FROM NULL" constraint to the filterNode
> // (which is under the renderNode).
> func (n *groupNode) addIsNotNullFilter(where *filterNode, render *renderNode) {
> ```

Let's fix this method name since it's now creating an `IsDistnctFromNull` node.

---

*[pkg/sql/opt_decompose.go, line 218 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20346#-L-D8v_QI8KUZKBkWdx6:-L-D8v_QI8KUZKBkWdx7:b-u5ltyd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3667428d275649a0c2eb833e076db6a994a9adf0/pkg/sql/opt_decompose.go#L218)):*
> ```Go
> 		case tree.IsNotDistinctFrom:
> 			op = tree.IsDistinctFrom
> 		case tree.Is:
> ```

We can remove these, right?

---

*[pkg/sql/opt_index_selection_test.go, line 206 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20346#-L-DDXWhbXy8jQ-LJj6F:-L-DDXWhbXy8jQ-LJj6G:btfyze7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3667428d275649a0c2eb833e076db6a994a9adf0/pkg/sql/opt_index_selection_test.go#L206)):*
> ```Go
> 		{`c IS NOT TRUE`, `c`, `[c IS DISTINCT FROM NULL, c <= false] OR [c IS NOT DISTINCT FROM NULL]`},
> 		{`c IS FALSE`, `c`, `[c = false]`},
> 		{`c IS NOT FALSE`, `c`, `[c >= true] OR [c IS NOT DISTINCT FROM NULL]`},
> ```

We should add tests similar to those added in https://github.com/cockroachdb/cockroach/pull/19106 but for `IsDistinctFrom` and `IsNotDistinctFrom`.

---

*[pkg/sql/opt_index_selection_test.go, line 287 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20346#-L-D6GYp78v4GL1r6zCO:-L-D6GYp78v4GL1r6zCP:b4vs6ll) ([raw file](https://github.com/cockroachdb/cockroach/blob/3667428d275649a0c2eb833e076db6a994a9adf0/pkg/sql/opt_index_selection_test.go#L287)):*
> ```Go
> 
> 		{`a IS NULL`, `a`, `[a IS NOT DISTINCT FROM NULL]`},
> 		{`a IS NOT NULL`, `a`, `[a IS DISTINCT FROM NULL]`},
> ```

Let's add cases for `IS NOT DISTINCT FROM` and `IS DISTINCT FROM` here.

---

*[pkg/sql/sem/tests/normalize_test.go, line 163 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20346#-L-D6rCl3xUWum7oIoSM:-L-D6rCl3xUWum7oIoSN:befgk5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/3667428d275649a0c2eb833e076db6a994a9adf0/pkg/sql/sem/tests/normalize_test.go#L163)):*
> ```Go
> 		{`1 IS NOT NULL`, `true`},
> 		{`d IS NULL`, `d IS NOT DISTINCT FROM NULL`},
> 		{`d IS NOT NULL`, `d IS DISTINCT FROM NULL`},
> ```

Could we add cases like these for `IS NOT DISTINCT FROM` or `IS DISTINCT FROM`? Notably, the change I described below should make normalizations like the following possible:
```
`d IS NOT DISTINCT FROM TRUE`, `(d = true) AND (d IS DISTINCT FROM NULL)`
```

---

*[pkg/sql/sem/tree/normalize.go, line 449 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20346#-L-D9NlxIzqm32DWT5pT:-L-D9NlxIzqm32DWT5pU:bl9p3c0) ([raw file](https://github.com/cockroachdb/cockroach/blob/3667428d275649a0c2eb833e076db6a994a9adf0/pkg/sql/sem/tree/normalize.go#L449)):*
> ```Go
> 		}
> 	case Is:
> 		if expr.TypedRight() != DNull {
> ```

I think we want to map `Is/IsNot` to `IsNotDistinctFrom/IsDistinctFrom` and then call `normalize()` on the resulting expression. We should then add cases to `ComparisonExpr.normalize` for `IsNotDistinctFrom/IsDistinctFrom` that handle the `if expr.TypedRight() != DNull {` normalization we have here. This will allow all four operator types to benefit from this normalization.

---

*[pkg/sql/sem/tree/normalize.go, line 461 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20346#-L-D74nDJjr5IWrQbfVs:-L-D74nDJjr5IWrQbfVt:b-3296qo) ([raw file](https://github.com/cockroachdb/cockroach/blob/3667428d275649a0c2eb833e076db6a994a9adf0/pkg/sql/sem/tree/normalize.go#L461)):*
> ```Go
> 				NewTypedComparisonExpr(IsDistinctFrom, expr.TypedLeft(), DNull),
> 			)
> 		} else {
> ```

Add a comment here that we normalize `Is` to `IsNotDistinctFrom`. Maybe explain why and reference the Github issue.

We also don't need the `else` block, which golint is complaining about.

Finally, I think this would be easier to read if you switch the two cases, so that the first case is
```
if expr.TypedRight() == DNull {
```

All of this is pending the more important change above though.

---

*[pkg/sql/sem/tree/normalize.go, line 477 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20346#-L-D7d4ruWa5SVanzOis:-L-D7d4ruWa5SVanzOit:b-l7n66u) ([raw file](https://github.com/cockroachdb/cockroach/blob/3667428d275649a0c2eb833e076db6a994a9adf0/pkg/sql/sem/tree/normalize.go#L477)):*
> ```Go
> 				NewTypedComparisonExpr(IsNotDistinctFrom, expr.TypedLeft(), DNull),
> 			)
> 		} else {
> ```

Same three comments as above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20346#-:-L-D7h1Z54zdL0XmIjLV:b-p5roo4)*

**Comment by knz** [comment]
The overall approach *after normalization* LGTM - I'll need to review in detail but I'll look at this afterwards.

For the stage before that I am not fully happy though -- it seems overly complex, I would have recommended to simply desugar IS/IS NOT during *parsing* to IS (NOT) DISTINCT FROM, and eliminate the AST nodes for IS/IS NOT entirely. Why keep them?

---

Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20346#-:-L-E49OvmzxJas34GUHM:b-ebt1hl)*

**Comment by nvanbenschoten** [comment]
> For the stage before that I am not fully happy though -- it seems overly complex, I would have recommended to simply desugar IS/IS NOT during parsing to IS (NOT) DISTINCT FROM, and eliminate the AST nodes for IS/IS NOT entirely. Why keep them?

That's a good point @knz, but at least for this change, I think there is a good reason to keep them: we currently never do this kind of desugaring during parsing of comparison expressions even when there are many cases where we could. For instance, all of our `NotXYZ` operators could be desugared to `NotExpr{ComparisonExpr{...}}` by the parser. However, I believe the reason we don't do this is that we want our parser to round trip from string->AST->string. Whether we want to change that in the future is a valid question that I'd be happy to discuss, but I'd rather not decide on a policy half-way and try to force it into this unrelated change. I'd also politely argue that what we have here is already a big simplification and that "overly complex" is a stretch for 2 one-line normalization rules.

**Comment by RaduBerinde** [comment]
> However, I believe the reason we don't do this is that we want our parser to round trip from string->AST->string. 

We do some desugaring in the parser (e.g. IFNULL/COALESCE), and we store enough information in the node so it comes out the same during formatting.

**Comment by RaduBerinde** [comment]
Although, we definitely have statements that don't roundtrip, e.g. `TestParse2`.

I was wondering if it would be feasible to format the node representing `IS NOT DISTINCT FROM NULL` as `IS NULL` to keep the expressions more readable (e.g. in distsql plans).

**Comment by yuhit** [comment]
It seems nothing going wrong if desugaring IS/IS NOT during parsing, Should I do that in this issue or just do a normalise and have a further discussing in another issue?

**Comment by knz** [comment]
Please just do the normalizing in this PR, then make a proposal for the desugaring in a followup. Thanks for investigating!

**Comment by yuhit** [comment]
@nvanbenschoten  I have changed the code accordingly.

**Comment by nvanbenschoten** [comment]
Reviewed 10 of 12 files at r2.
Review status: 11 of 13 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/sql/sem/tree/normalize.go, line 449 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20346#-L-D9NlxIzqm32DWT5pT:-L-bdxSpIox9DoExQ1oZ:b-1kyvgt) ([raw file](https://github.com/cockroachdb/cockroach/blob/3667428d275649a0c2eb833e076db6a994a9adf0/pkg/sql/sem/tree/normalize.go#L449)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think we want to map `Is/IsNot` to `IsNotDistinctFrom/IsDistinctFrom` and then call `normalize()` on the resulting expression. We should then add cases to `ComparisonExpr.normalize` for `IsNotDistinctFrom/IsDistinctFrom` that handle the `if expr.TypedRight() != DNull {` normalization we have here. This will allow all four operator types to benefit from this normalization.
</blockquote></details>

This is close, but what I had in mind was something closer to:

```
case Is:
    return NewTypedComparisonExpr(IsNotDistinctFrom, expr.TypedLeft(), expr.TypedRight()).normalize(v)
case IsNot:
    return NewTypedComparisonExpr(IsDistinctFrom, expr.TypedLeft(), expr.TypedRight()).normalize(v)
case IsNotDistinctFrom:
    ...
case IsDistinctFrom:
    ...
```

Does that make sense?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20346)*

**Comment by yuhit** [comment]
@nvanbenschoten OK, it seems more readable, i have changed the code.

**Comment by nvanbenschoten** [comment]
:lgtm: thanks @yuhit!

---

Reviewed 1 of 12 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20346#-:-L-hV6Yk1pTldfUO0F59:b-ve2d3y)*

**Pull request merged**
