### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by tamird**
Omits coreos/etcd#5468 which changed the
behaviour of raft elections so as to break TestLeaderAfterSplit.

Also changes the expected error in TestClientNotReady because upstream
is now using an unexported error.

The second commit reverts #7723 because https://github.com/grpc/grpc-go/pull/751 was merged upstream.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8107)

### CODE REVIEW

**Comment by tschottdorf** [comment]
Lgtm

**Comment by petermattis** [comment]
:lgtm:

---

Reviewed 29 of 29 files at r1.
Review status: 29 of 30 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[util/leaktest/leaktest.go, line 40 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8107#-KNo-QO1qkyj0MogilOC:-KNo-QO1qkyj0MogilOD:-324754848) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfe26d540bd4bbed54e7dad22b4cdde5d543a386/util/leaktest/leaktest.go#L40)):*
> ```Go
> 			// something similar is done, opening a gRPC client connection does not
> 			// timeout properly. See also
> 			// https://github.com/cockroachdb/cockroach/issues/7524.
> ```

I'm assuming you tested this on go1.7rc3 as the leak didn't happen on go1.6. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8107#-:-KNo-_XL21U_5pLrq_Rr:1417088721)*

**Comment by tamird** [comment]
I didn't test it at all since I was never able to reproduce it in the first
place. Could you test it? That was my thinking when assigning you.

**Comment by tamird** [comment]
Added a commit here to address some flakiness I saw in gossip. PTAL.

**Pull request merged**
