### PR TITLE
opt: execute correlated Exists as Routines and and allow Exists in UDFs

### PR DESCRIPTION
**Pull request by mgartner**
#### opt: add SubqueryPrivate.Ordering check to CheckExpr

Expressions with `SubqueryPrivate` fields are not optimized with respect
to any ordering, except for `ArrayFlatten` expressions. This commit adds
a check to `CheckExpr` to ensure that `SubqueryPrivate.Ordering` is only
set for `ArrayFlatten`.

Release note: None

#### opt: convert uncorrelated Exists to Coalesce+Subquery expressions

This commit adds the `ConvertUncorrelatedExistsToCoalesceSubquery`
normalization rule which transforms uncorrelated Exists into
Coalesce+Subquery expressions. Below is an example of the transformation
made.

    SELECT EXISTS (
      SELECT * FROM b
    ) FROM a
    =>
    SELECT COALESCE(
      (SELECT true FROM (SELECT * FROM b) LIMIT 1),
      false
    ) FROM a

By eliminating the uncorrelated Exists, we now support execution of
uncorrelated Exists that are within correlated subqueries or UDFs. These
are supported without execbuilder changes because execbuilder already
knows how to build correlated Subquery expressions within correlated
subqueries or UDFs.

This change also makes the `exists` subquery execution mode, which only
works for uncorrelated subqueries, obsolete. The related code paths
should never be executed. I plan on removing them in a future commit.

Release note: None

#### opt: build correlated Exists as Coalesce+Routine expressions

This commit allows for the execution of correlated Exists subqueries by
building them as Coalesce+Routine expressions in execbuilder.

Routines do not have a special mode for Exists subqueries, like the
legacy, eager-evaluation subquery machinery does, so we must transform
the Exists expression. The transformation is modelled after the
ConvertUncorrelatedExistsToCoalesceSubquery normalization rule. The
transformation is effectively:

    EXISTS (<input>)
    =>
    COALESCE((SELECT true FROM (<input>) LIMIT 1), false)

We don't implement this as a normalization rule for correlated Exists
subqueries because the transformation would prevent decorrelation rules
from turning the Exists expression into a join, if it is possible.
Marking the rule as LowPriority would not be sufficient because the rule
would operate on the Exists scalar expression, while the decorrelation
rules operate on relational expressions that contain Exists expresions.
The Exists would always be converted to a Coalesce before the
decorrelation rules can match.

Informs: #87291

Epic: CRDB-19257

Release note (sql change): Some queries with `EXISTS` subqueries which
previously resulted in the error "could not decorrelate subquery" now
succeed.

### CODE REVIEW

**Review by rharding6373 — APPROVED** [review]
:lgtm: very nice!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95883#-:-NMfPmox5z_GL3wNY-4D:bhnhlex)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @mgartner)

___
*[`pkg/sql/opt/memo/check_expr.go` line 428 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95883#-NMfHy9i9raHbT3Q9PXz:-NMfHy9i9raHbT3Q9PY-:b-jmxqyd) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a0be89a85659c8842f0abdc180a6c3540f201af/pkg/sql/opt/memo/check_expr.go#L428)):*
> ```Go
> 	case *SubqueryPrivate:
> 		if !ordering.Any() && e.Op() != opt.ArrayFlattenOp {
> 			panic(errors.AssertionFailedf(
> ```

Not really relevant to this PR, but do you happen to know why we panic in this function instead of making graceful errors?

**Review by DrewKimball — APPROVED** [review]
:lgtm: Cool!

> Reviewed 1 of 1 files at r1, 15 of 15 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95883#-:-NMfeczd4IE-4C-kRKcH:b-8mhwdz)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`-- commits` line 23 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95883#-NMfbUQp9lKlx4mLaYNc):*
I think we could even remove the coalesce in most cases, since Select and Join filters treat `false` and `NULL` predicates the same way.
___
*[`pkg/sql/opt/exec/execbuilder/scalar.go` line 614 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95883#-NMfcVTPDw5BVa_FhMD7:-NMfcVTPDw5BVa_FhMD8:bqofoa1) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b3356eb542b9315666f594f370b09e5f4ce2af2/pkg/sql/opt/exec/execbuilder/scalar.go#L614)):*
> ```Go
> 		// mutations.
> 		if input.Relational().CanMutate {
> 			return nil, b.decorrelationError()
> ```

[nit] Do you think it would be worth annotating the error with some context about the reason it can't be decorrelated? Maybe this'll be solved soon enough that it doesn't matter.
___
*[`pkg/sql/opt/exec/execbuilder/scalar.go` line 954 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95883#-NMfe-Sc7DvIoS9wqn4y:-NMfe-Sc7DvIoS9wqn4z:b-i5wuuo) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b3356eb542b9315666f594f370b09e5f4ce2af2/pkg/sql/opt/exec/execbuilder/scalar.go#L954)):*
> ```Go
> 			if onReplaceExpr != nil {
> 				if e, ok := onReplaceExpr(f, e, replaceFn); ok {
> 					return e
> ```

[nit] Could returning early here cause problems with future usage of `onReplaceExpr`? It might be safer to fall through afterward.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95883)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @DrewKimball and @rharding6373)

___
*[`-- commits` line 23 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95883#-NMfbUQp9lKlx4mLaYNc):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

I think we could even remove the coalesce in most cases, since Select and Join filters treat `false` and `NULL` predicates the same way.
</blockquote></details>

I think this should be easy to add as a normalization rule in a future PR. I'll look into it.
___
*[`pkg/sql/opt/exec/execbuilder/scalar.go` line 614 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95883#-NMfcVTPDw5BVa_FhMD7:-NN2oF7T17Jg4vMco5yk:bwgfhrw) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b3356eb542b9315666f594f370b09e5f4ce2af2/pkg/sql/opt/exec/execbuilder/scalar.go#L614)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Do you think it would be worth annotating the error with some context about the reason it can't be decorrelated? Maybe this'll be solved soon enough that it doesn't matter.
</blockquote></details>

Good idea. I created a new error specifically for this case.
___
*[`pkg/sql/opt/exec/execbuilder/scalar.go` line 954 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95883#-NMfe-Sc7DvIoS9wqn4y:-NN2iXSUE6_dLNWITzES:bxa5rab) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b3356eb542b9315666f594f370b09e5f4ce2af2/pkg/sql/opt/exec/execbuilder/scalar.go#L954)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Could returning early here cause problems with future usage of `onReplaceExpr`? It might be safer to fall through afterward.
</blockquote></details>

If we falled-through, then we'd be re-walking the tree again, since we call CopyAndReplaceDefaults in the onReplaceExpr.

Thanks for pointing this out, though, because it's confusing. I've reworked the code a bit to make it more clear, albeit less general.
___
*[`pkg/sql/opt/memo/check_expr.go` line 428 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95883#-NMfHy9i9raHbT3Q9PXz:-NN2c5swBOgBsEvdPt2b:b-qfh34j) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a0be89a85659c8842f0abdc180a6c3540f201af/pkg/sql/opt/memo/check_expr.go#L428)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Not really relevant to this PR, but do you happen to know why we panic in this function instead of making graceful errors?
</blockquote></details>

The `CheckExpr` function is a no-op for release builds. It's meant to panic test builds to signal that an invariant has been violated. We don't perform these checks in release builds because they can be computationally expensive.

**Review by DrewKimball — APPROVED** [review]
> Reviewed 12 of 16 files at r5, 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95883)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @rharding6373)

**Review by rharding6373 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95883#-:-NN3H8cmBzAyuYF-Uqhb:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball)

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
