### PR TITLE
Switch to `log.Trace`, passing context instead of spans

### PR DESCRIPTION
**Pull request by dt**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5317)

### CODE REVIEW

**Comment by tschottdorf** [comment]
I think you still need to remove the "old" tracing functions. LGTM mod minor fallout otherwise, thanks!

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 10 of 10 files at r3.
Review status: 9 of 18 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[kv/send.go, line 232 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5317#-KD0QL7lp1PUZTk6Hnow:-KD0QL7m4WFjYZuw0OoQ:-1770086839) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d0c3fe60c20513310415719413689751718fcc5/kv/send.go#L232)):*
This should fix #5288 and maybe #5311 (unless there are more places where we pass a ctx into a goroutine (really a shame that that's an issue)).

---

*[sql/trace.go, line 65 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5317#-KD0SQMrMsLObXYbs020:-KD0SQMrMsLObXYbs021:1983874474) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d0c3fe60c20513310415719413689751718fcc5/sql/trace.go#L65)):*
we should actually log `pErr.Error())` to get the full gist of it.

---

*[storage/intent_resolver.go, line 391 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5317#-KD0Tjg1CapW68cKAwTp:-KD0Tjg2c7z0xOP8VCxy:91096668) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd2f7296d6e7ad179277d3d02dfbb19f0371ed25/storage/intent_resolver.go#L391)):*
add comment here that currently passing spans over goroutine boundaries is bad and so we don't do it here.

---

*[storage/replica.go, line 518 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5317#-KD0SXfXe_3WiEJTWUBD:-KD0SXfXe_3WiEJTWUBE:160402253) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d0c3fe60c20513310415719413689751718fcc5/storage/replica.go#L518)):*
asd

---

*[storage/replica.go, line 701 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5317#-KD0TsX6wGpjTjqVBK-v:-KD0TsX7m-vbZ8Pi0BXH:-598332646) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd2f7296d6e7ad179277d3d02dfbb19f0371ed25/storage/replica.go#L701)):*
might wanna play the ensure game here as well; some queues talk to this directly.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5317#-:-KD0U3da-ObllHD3n-dG:-342382637)*

**Comment by tschottdorf** [comment]
Reviewed 9 of 9 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5317)*

**Comment by dt** [comment]
Review status: 9 of 18 files reviewed at latest revision, 5 unresolved discussions.

---

*[sql/trace.go, line 65 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5317#-KD0SQMrMsLObXYbs020:-KD0Zvswb63shAsSZIQ7:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d0c3fe60c20513310415719413689751718fcc5/sql/trace.go#L65)):*
Done.

---

*[storage/intent_resolver.go, line 391 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5317#-KD0Tjg1CapW68cKAwTp:-KD0ZjNOhYA5SiTtDwnn:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd2f7296d6e7ad179277d3d02dfbb19f0371ed25/storage/intent_resolver.go#L391)):*
Done.

---

*[storage/replica.go, line 518 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5317#-KD0SXfXe_3WiEJTWUBD:-KD0ZQgBCccSveb42PvS:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d0c3fe60c20513310415719413689751718fcc5/storage/replica.go#L518)):*
Done.

---

*[storage/replica.go, line 701 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5317#-KD0TsX6wGpjTjqVBK-v:-KD0Yuc_qQlD_XiLivbY:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd2f7296d6e7ad179277d3d02dfbb19f0371ed25/storage/replica.go#L701)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5317)*

**Comment by tschottdorf** [comment]
Reviewed 9 of 9 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[kv/dist_sender.go, line 56 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5317#-KD0f_QkFn_wOV9268D7:-KD0f_QkFn_wOV9268D8:-1807313274) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd2f7296d6e7ad179277d3d02dfbb19f0371ed25/kv/dist_sender.go#L56)):*
`make unused` might catch some more

---

*[kv/txn_coord_sender.go, line 332 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5317#-KD0fkufnVVyFKpgASj2:-KD0fkufnVVyFKpgASj3:-1016338323) ([raw file](https://github.com/cockroachdb/cockroach/blob/0de37e3739cbe2f18f546c2a0b735f31ded3e78d/kv/txn_coord_sender.go#L332)):*
move this to the span creation - the comment is stale, dates back to a time at which we created the trace id from the txn id.

---

*[util/tracing/tracer.go, line 44 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5317#-KD0gSfGCWtPl5yfPu8q:-KD0gSfGCWtPl5yfPu8r:1129317553) ([raw file](https://github.com/cockroachdb/cockroach/blob/0de37e3739cbe2f18f546c2a0b735f31ded3e78d/util/tracing/tracer.go#L44)):*
is this ever called?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5317)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[kv/dist_sender.go, line 389 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5317#-KD0yC6EPLDyKSOJrzUe:-KD0yC6FH238esN9L_5m:-1524899299) ([raw file](https://github.com/cockroachdb/cockroach/blob/0de37e3739cbe2f18f546c2a0b735f31ded3e78d/kv/dist_sender.go#L389)):*
Can we change this to `log.Tracef` and avoid calling `fmt.Sprintf` if there is no span?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5317)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[kv/dist_sender.go, line 389 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5317#-KD0yC6EPLDyKSOJrzUe:-KD1Bf67nJUNDmfW_ZQS:-94879739) ([raw file](https://github.com/cockroachdb/cockroach/blob/0de37e3739cbe2f18f546c2a0b735f31ded3e78d/kv/dist_sender.go#L389)):*
I'd rather punt on introducing the `f` family for now. This is a case where it's truly useful, and the allocation won't kill us, but I'd rather remove this `Sprintf` than introduce `Tracef`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5317)*

**Comment by dt** [comment]
Review status: 17 of 18 files reviewed at latest revision, 5 unresolved discussions.

---

*[kv/dist_sender.go, line 389 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5317#-KD0yC6EPLDyKSOJrzUe:-KD3w9q1cZxzZx9_Vt4C:-479086156) ([raw file](https://github.com/cockroachdb/cockroach/blob/0de37e3739cbe2f18f546c2a0b735f31ded3e78d/kv/dist_sender.go#L389)):*
Yeah, I think we want to avoid the `*f` family which would encourage non-const strings being logged more -- I'd rather make the caller explicitly choose to pay the allocation when they really want it.

---

*[kv/txn_coord_sender.go, line 332 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5317#-KD0fkufnVVyFKpgASj2:-KD3wwxpCUUp5N3k7WFx:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/0de37e3739cbe2f18f546c2a0b735f31ded3e78d/kv/txn_coord_sender.go#L332)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5317)*

**Comment by dt** [comment]
Review status: 17 of 18 files reviewed at latest revision, 4 unresolved discussions.

---

*[util/tracing/tracer.go, line 44 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5317#-KD0gSfGCWtPl5yfPu8q:-KD3zvVO8hlB8Bg67-24:-1115908538) ([raw file](https://github.com/cockroachdb/cockroach/blob/0de37e3739cbe2f18f546c2a0b735f31ded3e78d/util/tracing/tracer.go#L44)):*
server/node.go:663

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5317)*

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[kv/txn_coord_sender.go, line 306 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5317#-KD4EKL9jNlwSAakFn8x:-KD4EGJRAgTjnbHgHP21:-1279282149) ([raw file](https://github.com/cockroachdb/cockroach/blob/0038707a672aad7946ddcee94175e804f78c0c0d/kv/txn_coord_sender.go#L306)):*
maybe you can block-scope this and below so that `sp` doesn't escape below where the call to `Inject` happens.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5317#-:-KD4EROKjicR_d2MyUi7:1417088721)*

**Comment by dt** [comment]
Review status: 17 of 18 files reviewed at latest revision, 3 unresolved discussions.

---

*[kv/dist_sender.go, line 56 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5317#-KD0f_QkFn_wOV9268D7:-KD41lE1c6D9MdP6Galn:677886459) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd2f7296d6e7ad179277d3d02dfbb19f0371ed25/kv/dist_sender.go#L56)):*
nope

---

*[kv/txn_coord_sender.go, line 306 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5317#-KD4EKL9jNlwSAakFn8x:-KD4F23ns9AmAAjr4RVO:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/0038707a672aad7946ddcee94175e804f78c0c0d/kv/txn_coord_sender.go#L306)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5317)*

**Pull request merged**
