### PR TITLE
Grafana dashboard sync

### PR DESCRIPTION
**Pull request by smg260**
2 commits for the Grafana dashboard jsons
- update the repo with the latest from https://grafana.testeng.crdb.io/dashboards/f/PYSGrKenz/crdb
- update the dashboards to utilise `test_run_id` and `test_name` introduced as part of #107965

1 commit is just adding the latest prom config for testeng grafana

Dashboards available at: https://grafana.testeng.crdb.io/dashboards/f/Kmw561gIk/crdb-by-test-run-and-name
Home page: https://grafana.testeng.crdb.io/d/crdb-home/crdb-home?orgId=1

Release note: none
Epic: none

### CODE REVIEW

**Review by srosenberg — APPROVED** [review]
Changes look good. It would be good to double-check that the updated dashboards can be exported; most of the changes appear to be a result of a newer version of grafana, e.g., `"pluginVersion": "9.4.7`.

**Comment by smg260** [comment]
Verified that dashboards could be viewed via `demo/docker-compose`. That highlighted the need for two separate folders containing the old `by cluster` dashboards, and the new `by roachtest` dashboards. The former to be used when inspecting metrics for non roachtest workloads.

Updated demo prom config to use both sets of dashboards.

**Comment by smg260** [comment]
Latest `prometheus.yaml` added just to get it in version control.

@herkolategan I also updated `pkg/cmd/roachprod/grafana/configs` to be the same as those in `monitoring/grafana-dashboards/by-cluster`. Not sure we need them to exist in both places, but that's what we have today.

**Review by herkolategan — APPROVED** [review]
@smg260 The ones you are referring to in `roachprod` get embedded, so they can be used directly from the binary. They are only deployed with grafana if no other dashboard is passed to `roachprod`. So the duplication might be necessary unless we can point `bazel` to use the monitoring folder rather.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109642#-:-NdkAKPt3Gk9ozTLWzot:bssh4c9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @srosenberg)

**Comment by smg260** [comment]
Thanks @herkolategan - will merge as is and revisit removing the duplication

TFTR

bors r=srosenberg,herkolategan

**Pull request merged**
