### PR TITLE
storage: introduce, use and expose RangeState proto

### PR DESCRIPTION
**Pull request by tbg**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7250)

### CODE REVIEW

**Comment by tschottdorf** [comment]
Removed the last commit, there is some ui-next-protobuf funkiness due to importing from coreos/etcd/raft/raftpb.

**Comment by BramGruneir** [comment]
:lgtm:

---

Reviewed 8 of 9 files at r1, 2 of 6 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/storagebase/range.proto, line 53 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7250#-KKKmMLKzEHs8IWeEaP_:-KKKmMLKzEHs8IWeEaPa:-529191373) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bcbf21422f9ae8b768d6a69ca790d7a6be3f7f9/storage/storagebase/range.proto#L53)):*
> ```protobuf
>                                       (gogoproto.customname) = "GCThreshold"];
>   storage.engine.enginepb.MVCCStats stats = 10 [(gogoproto.nullable) = false];
>   bool frozen = 11;
> ```

Can you add a comment for frozen?  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7250#-:-KKKn6h1272wzCfosu7Q:1417088721)*

**Comment by bdarnell** [comment]
LGTM

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[storage/storagebase/range.proto, line 31 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7250#-KKL3fuI7SWbOxSNQrqC:-KKL3fuJCQxTuvD2L1e7:813518929) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bcbf21422f9ae8b768d6a69ca790d7a6be3f7f9/storage/storagebase/range.proto#L31)):*
> ```protobuf
> // RangeState is the part of the Range Raft state machine which is cached in
> // memory and which is manipulated exclusively through consensus.
> message RangeState {
> ```

RangeState or ReplicaState? I guess it's mostly (one replica's view of) the shared range state, although `raftAppliedIndex` is a per-replica value.

Why did you skip field numbers 1-3?

---

*[storage/storagebase/range.proto, line 33 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7250#-KKL3z8L7ypGwniTybLB:-KKL3z8MpXpy0018US9l:2060498740) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bcbf21422f9ae8b768d6a69ca790d7a6be3f7f9/storage/storagebase/range.proto#L33)):*
> ```protobuf
> message RangeState {
>   // The highest (and last) index applied to the state machine.
>   uint64 raftAppliedIndex = 4;
> ```

In protos, use `lowercase_with_underscores` and let protoc adapt to go conventions.

---

*[storage/storagebase/range.proto, line 37 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7250#-KKL4bSQSTltKs91ys6i:-KKL4bSQSTltKs91ys6j:-648942297) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bcbf21422f9ae8b768d6a69ca790d7a6be3f7f9/storage/storagebase/range.proto#L37)):*
> ```protobuf
>   uint64 leaseAppliedIndex = 5;
>   // The Range descriptor.
>   // The pointer may change, but the referenced RangeDescriptor struct itself
> ```

This comment is a little out of place now, since it is specific to the use of this struct in `Replica`. I guess we don't have a better place for it, though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7250#-:-KKL53-DxWS23ZYpgq0h:676834233)*

**Comment by tschottdorf** [comment]
Thanks Ben, I'll send a follow-up.

On Wed, Jun 15, 2016 at 6:04 PM Ben Darnell <notifications@github.com>
wrote:

> LGTM
> ------------------------------
>
> Review status: all files reviewed at latest revision, 4 unresolved
> discussions, all commit checks successful.
> ------------------------------
>
> *storage/storagebase/range.proto, line 31 [r5]
> <https://reviewable.io:443/reviews/cockroachdb/cockroach/7250#-KKL3fuI7SWbOxSNQrqC:-KKL3fuJCQxTuvD2L1e7:813518929>
> (raw file
> <https://github.com/cockroachdb/cockroach/blob/2bcbf21422f9ae8b768d6a69ca790d7a6be3f7f9/storage/storagebase/range.proto#L31>):*
>
> // RangeState is the part of the Range Raft state machine which is cached in// memory and which is manipulated exclusively through consensus.message RangeState {
>
> RangeState or ReplicaState? I guess it's mostly (one replica's view of)
> the shared range state, although raftAppliedIndex is a per-replica value.
>
> Why did you skip field numbers 1-3?
> ------------------------------
>
> *storage/storagebase/range.proto, line 33 [r5]
> <https://reviewable.io:443/reviews/cockroachdb/cockroach/7250#-KKL3z8L7ypGwniTybLB:-KKL3z8MpXpy0018US9l:2060498740>
> (raw file
> <https://github.com/cockroachdb/cockroach/blob/2bcbf21422f9ae8b768d6a69ca790d7a6be3f7f9/storage/storagebase/range.proto#L33>):*
>
> message RangeState {
>   // The highest (and last) index applied to the state machine.
>   uint64 raftAppliedIndex = 4;
>
> In protos, use lowercase_with_underscores and let protoc adapt to go
> conventions.
> ------------------------------
>
> *storage/storagebase/range.proto, line 37 [r5]
> <https://reviewable.io:443/reviews/cockroachdb/cockroach/7250#-KKL4bSQSTltKs91ys6i:-KKL4bSQSTltKs91ys6j:-648942297>
> (raw file
> <https://github.com/cockroachdb/cockroach/blob/2bcbf21422f9ae8b768d6a69ca790d7a6be3f7f9/storage/storagebase/range.proto#L37>):*
>
>   uint64 leaseAppliedIndex = 5;
>   // The Range descriptor.
>   // The pointer may change, but the referenced RangeDescriptor struct itself
>
> This comment is a little out of place now, since it is specific to the use
> of this struct in Replica. I guess we don't have a better place for it,
> though.
> ------------------------------
>
> *Comments from Reviewable
> <https://reviewable.io:443/reviews/cockroachdb/cockroach/7250#-:-KKL53-DxWS23ZYpgq0h:676834233>*
>
> —
> You are receiving this because you modified the open/close state.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/pull/7250#issuecomment-226334061>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AE135HgKY8jHGHZK4-jo4c5c9UxL57fYks5qMHcHgaJpZM4I2uR->
> .
>
-- 

-- Tobias

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[storage/storagebase/range.proto, line 31 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7250#-KKL3fuI7SWbOxSNQrqC:-KKL8s4DNYBzejgKykFe:-1840919746) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bcbf21422f9ae8b768d6a69ca790d7a6be3f7f9/storage/storagebase/range.proto#L31)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> RangeState or ReplicaState? I guess it's mostly (one replica's view of) the shared range state, although `raftAppliedIndex` is a per-replica value.
> 
> Why did you skip field numbers 1-3?
</details>
I went back and forth about it. Decided against `ReplicaState` because the important thing about this struct is that it's changed only according to applied Raft commands. But now that I think about it, I think `ReplicaState` makes more sense and is clear enough in the context it's used in.

---

*[storage/storagebase/range.proto, line 33 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7250#-KKL3z8L7ypGwniTybLB:-KKL9Es31Kh8kNIeV6IW:1310470104) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bcbf21422f9ae8b768d6a69ca790d7a6be3f7f9/storage/storagebase/range.proto#L33)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> In protos, use `lowercase_with_underscores` and let protoc adapt to go conventions.
</details>
Done. (new PR)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7250)*

**Comment by tamird** [comment]
Reviewed 9 of 9 files at r1, 6 of 6 files at r3, 6 of 6 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[storage/storagebase/range.proto, line 18 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7250#-KKLGKGdaCv_RaXNueSo:-KKLGKGdaCv_RaXNueSp:-199767815) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bcbf21422f9ae8b768d6a69ca790d7a6be3f7f9/storage/storagebase/range.proto#L18)):*
> ```protobuf
> 
> syntax = "proto3";
> package cockroach.storage.storagebase;
> ```

why storagebase and not storagepb?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7250)*

**Comment by tschottdorf** [comment]
`storagebase` already existed and its reason for existence is that we
needed a package which random places can import from without paying for a
`storage` dependency. `storagepb` would be the same. I don't feel strongly
either way.

On Wed, Jun 15, 2016 at 6:55 PM Tamir Duberstein <notifications@github.com>
wrote:

> Reviewed 9 of 9 files at r1, 6 of 6 files at r3, 6 of 6 files at r4, 3 of
> 3 files at r5.
> Review status: all files reviewed at latest revision, 5 unresolved
> discussions, all commit checks successful.
> ------------------------------
>
> *storage/storagebase/range.proto, line 18 [r5]
> <https://reviewable.io:443/reviews/cockroachdb/cockroach/7250#-KKLGKGdaCv_RaXNueSo:-KKLGKGdaCv_RaXNueSp:-199767815>
> (raw file
> <https://github.com/cockroachdb/cockroach/blob/2bcbf21422f9ae8b768d6a69ca790d7a6be3f7f9/storage/storagebase/range.proto#L18>):*
>
>
> syntax = "proto3";package cockroach.storage.storagebase;
>
> why storagebase and not storagepb?
> ------------------------------
>
> *Comments from Reviewable
> <https://reviewable.io:443/reviews/cockroachdb/cockroach/7250>*
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/pull/7250#issuecomment-226343906>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AE135BE7gJetXoBRoejXhKaez4cIjlvJks5qMILtgaJpZM4I2uR->
> .
>
-- 

-- Tobias

**Comment by tamird** [comment]
Ah, didn't realize it already existed.

On Wed, Jun 15, 2016 at 6:58 PM, Tobias Schottdorf <notifications@github.com

**Pull request merged**
