### PR TITLE
distsql: extend joinReader to do lookupJoin

### PR DESCRIPTION
**Pull request by pbardea**
First step in extending the joinReader to do a lookup join. The
joinReader used to drop all the columns that were not part of the index
on the floor, how it keeps them around if it uses them in the post
processing projection.

Processor implementation towards issue #19038.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Nice, thanks for working on this!

Shouldn't the processor spec (in processors.proto) be updated with the new parameter `eqCols`? The comment there should also explain how this parameters affects the "internal schema" (i.e. what columns we output before post-processing).

Btw `indexCols` or `lookupCols` would be better than `eqCols`. 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21801#-:-L3ivfpfNltL2aMmMd3O:bn5mk4g)*

**Comment by pbardea** [comment]
I actually wasn't sure what should go in the `processors.proto`, for example the `input` is not in the processor spec and other joiners such as the `mergeJoiner` don't include the equality columns in the spec either.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21801#-:-L3j2YkgJ7rRygcE55FX:bvryftg)*

**Comment by RaduBerinde** [comment]
If they are not in the spec, how are we going to plan a query to use a join reader in this manner?

The merge joiner has LeftOrdering and RightOrdering which double as a specification of the equality columns. HashJoiner has LeftEqColumns, RightEqColumns.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21801#-:-L3j3If1jHuO6vMWGb2i:b74xir5)*

**Comment by petermattis** [comment]
@pbardea Do you have any thoughts on what heuristics we'll use to decide to use `joinReader`? @raduberinde, @arjunravinarayan have you thought about this? Clearly table statistics will help the new optimizer make this decision, but what can we do in the short term?

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21801#-:-L3jwXfzK-FftogSa0wv:b1ixjop)*

**Comment by RaduBerinde** [comment]
In the short term, we will probably want to add syntax for a hint.

One heuristic I can think of is to use it when one side of the join is a full table scan.

**Comment by petermattis** [comment]
> One heuristic I can think of is to use it when one side of the join is a full table scan.

Might need to make that: one side of the join has constrained spans and the other side is a full table scan. If both sides are a full table scan, we'd likely be better off with a merge join or hash join.

@arjunravinarayan Do you know off-hand if that heuristic would have fired on the query that is motivating this work?

**Comment by pbardea** [comment]
In addition to the above conditions the table doing the full table scan should have a primary index on the equality columns of the join. 

My only concern wrt whether or not this would trigger on the motivating TPCC query is whether or not be left side was a full table scan or had constrained spans, but such that it would select nearly all rows from the original table. 

Additionally, right now joinReader only works on primary indices. I am looking into expanding it to work with secondary indicies too. Those may need a separate set of heuristics all together depending on if the output columns are a subset of the indexed columns.

**Comment by arjunravinarayan** [comment]
@petermattis I would not add any heuristics. I would only enable this with a hint. The cost of misplanning is too high: if there are indeed a lot of matches, then a lookup join will have pathological performance.

Later on when we have table statistics, we will be able to say when one side of the query has constrained spans and the number of rows in the constrained spans are small (say 1000 rows or fewer, or whatever the cost model says), and we have an unconstrained full table scan on the other side. But right now I wouldn't automatically plan this join strategy without hints. The cost of a false positive is too high.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21801#-:-L3o-TsPiF_C7m-ECFf0:b-jonzbu)*

**Comment by petermattis** [comment]
I imagine a hint syntax will require bike shedding. 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21801#-:-L3oEzGDLTBq144rC0SZ:b-qgd2vx)*

**Comment by arjunravinarayan** [comment]
We can bikeshed the hint syntax in a new PR that does the planning work. Let's focus on the implementation in this PR.

@pbardea: general structure looks good to me, you're just going to have to push this one through and work through debugging all the various test failures for a bit. Let me know if you want some help in doing so.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsqlrun/joinreader.go, line 37 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21801#-L41erl9azFX3-Xd6FGY:-L41erl9azFX3-Xd6FGZ:b-m97x3u) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4af10f2ccd611314f627bbad36c60aa727723e4/pkg/sql/distsqlrun/joinreader.go#L37)):*
> ```Go
> const joinReaderBatchSize = 100
> 
> // A joinReader can preform an index join or a lookup join. Specifying a
> ```

typo "preform"

---

*[pkg/sql/distsqlrun/joinreader.go, line 40 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21801#-L41ezr9JY8ZOVjG6vDo:-L41ezr9JY8ZOVjG6vDp:b-ndcx42) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4af10f2ccd611314f627bbad36c60aa727723e4/pkg/sql/distsqlrun/joinreader.go#L40)):*
> ```Go
> // non-empty value for eqCols indicates it is a lookup join.
> //
> // For an index join, the input is subset of rows of the `desc` table where the
> ```

Also add that the left input is from the secondary index and the right input is from the primary index.

---

*[pkg/sql/distsqlrun/joinreader.go, line 111 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21801#-L41jqXdQcSdgJXpr6og:-L41jqXdQcSdgJXpr6oh:b-d0g3b6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4af10f2ccd611314f627bbad36c60aa727723e4/pkg/sql/distsqlrun/joinreader.go#L111)):*
> ```Go
> }
> 
> func (jr *joinReader) leftCols() util.FastIntSet {
> ```

This function needs a comment as to its purpose. Right now I can only figure out what its doing by studying its callers carefully.

---

*[pkg/sql/distsqlrun/joinreader.go, line 206 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21801#-L41kFIFAws9SxHg-MKa:-L41kFIFAws9SxHg-MKb:b-1ymr4s) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4af10f2ccd611314f627bbad36c60aa727723e4/pkg/sql/distsqlrun/joinreader.go#L206)):*
> ```Go
> 				EndKey: key.PrefixEnd(),
> 			}
> 			// TODO: Should only need to do this in the else case of the
> ```

pro tip: if this is a note to yourself, you can mark it as `TODO(DONOTMERGE)` so that I know its something you'll fix up in a later revision within this PR and not to bother commenting.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21801#-:-L41kgXTLM_6o297DRD-:bqiemc3)*

**Comment by pbardea** [comment]
Thanks for the comments! Updated based on comments and fixed tests + rebased. PTAL when you have a chance.

---

Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/joinreader.go, line 37 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21801#-L41erl9azFX3-Xd6FGY:-L42bwNHKZTS63EieDMO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4af10f2ccd611314f627bbad36c60aa727723e4/pkg/sql/distsqlrun/joinreader.go#L37)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

typo "preform"
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/joinreader.go, line 40 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21801#-L41ezr9JY8ZOVjG6vDo:-L431TrswsvFbvHlrkEW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4af10f2ccd611314f627bbad36c60aa727723e4/pkg/sql/distsqlrun/joinreader.go#L40)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

Also add that the left input is from the secondary index and the right input is from the primary index.
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/joinreader.go, line 111 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21801#-L41jqXdQcSdgJXpr6og:-L42bymmHcsiG2gr9Plh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4af10f2ccd611314f627bbad36c60aa727723e4/pkg/sql/distsqlrun/joinreader.go#L111)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

This function needs a comment as to its purpose. Right now I can only figure out what its doing by studying its callers carefully.
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/joinreader.go, line 206 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21801#-L41kFIFAws9SxHg-MKa:-L42cCN1xo6AEtP9VYFr:bhy9ost) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4af10f2ccd611314f627bbad36c60aa727723e4/pkg/sql/distsqlrun/joinreader.go#L206)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

pro tip: if this is a note to yourself, you can mark it as `TODO(DONOTMERGE)` so that I know its something you'll fix up in a later revision within this PR and not to bother commenting.
</blockquote></details>

Will do!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21801#-:-L431mRn-MOdggpHF6br:b-eff76u)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 4 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/joinreader.go, line 244 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21801#-L43Ce5fg1DWcu8bMu5c:-L43Ce5fg1DWcu8bMu5d:bb7fni6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a97ef870f3b1e746899201c40e711051cf6b2890/pkg/sql/distsqlrun/joinreader.go#L244)):*
> ```Go
> 		}
> 
> 		if !jr.isLookupJoin() {
> ```

else

---

*[pkg/sql/distsqlrun/joinreader.go, line 274 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21801#-L43CUmNGoTiUYlQufLR:-L43CUmNGoTiUYlQufLS:bgavc8j) ([raw file](https://github.com/cockroachdb/cockroach/blob/a97ef870f3b1e746899201c40e711051cf6b2890/pkg/sql/distsqlrun/joinreader.go#L274)):*
> ```Go
> // then the lookup will emit the concatenation of the rows from both tables.
> func (jr *joinReader) indexLookup(
> 	ctx context.Context, txn *client.Txn, spans roachpb.Spans, row *sqlbase.EncDatumRow,
> ```

this doesn't need to be a pointer, you can use a `nil` slice if it's not needed.

---

*[pkg/sql/distsqlrun/processors.proto, line 191 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21801#-L43BO9kNPw9CXAULXHw:-L43BO9lkBFvU7wmfiZx:b-j79kxv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a97ef870f3b1e746899201c40e711051cf6b2890/pkg/sql/distsqlrun/processors.proto#L191)):*
> ```protobuf
> // values in the input stream (join by lookup).
> //
> // The "internal columns" of a JoinReader (see ProcessorSpec) are all the
> ```

This is no longer accurate, is it? The processor has the capability to output extra columns from the input; we need to describe them so it's clear what @1, @2, etc means in a projection or filter. It would be good to have two examples here, one with no extra columns and one with extra columns.

---

*[pkg/sql/distsqlrun/processors.proto, line 202 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21801#-L43AsjcpU793AZbQLJK:-L43AsjcpU793AZbQLJL:bgm2khx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a97ef870f3b1e746899201c40e711051cf6b2890/pkg/sql/distsqlrun/processors.proto#L202)):*
> ```protobuf
>   optional uint32 index_idx = 2 [(gogoproto.nullable) = false];
> 
>   // If `lookup_columns` is empty, joinReader will lookup values from the
> ```

The comment doesn't explain what the values are: column indices in the input stream.

[nit] It's good to avoid including the name in the comment because the go code will have a different looking name (LookupColumns).

I would also rephrase "if it is empty, the input columns are assumed to be all the index columns for index_idx".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21801)*

**Comment by pbardea** [comment]
Review status: 0 of 4 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/joinreader.go, line 244 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21801#-L43Ce5fg1DWcu8bMu5c:-L43EFY1RCSWVGfa_U__:b-b58cs7) ([raw file](https://github.com/cockroachdb/cockroach/blob/a97ef870f3b1e746899201c40e711051cf6b2890/pkg/sql/distsqlrun/joinreader.go#L244)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

else
</blockquote></details>

Where would an else be used here? We don't do anything here in the case where `jr.isLookupJoin()` is truthy. 

---

*[pkg/sql/distsqlrun/joinreader.go, line 274 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21801#-L43CUmNGoTiUYlQufLR:-L43ETyEDP_Kw_gB0-mI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a97ef870f3b1e746899201c40e711051cf6b2890/pkg/sql/distsqlrun/joinreader.go#L274)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

this doesn't need to be a pointer, you can use a `nil` slice if it's not needed.
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/processors.proto, line 191 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21801#-L43BO9kNPw9CXAULXHw:-L43JONrVte57LuFmi87:bcr0ltc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a97ef870f3b1e746899201c40e711051cf6b2890/pkg/sql/distsqlrun/processors.proto#L191)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is no longer accurate, is it? The processor has the capability to output extra columns from the input; we need to describe them so it's clear what @1, @2, etc means in a projection or filter. It would be good to have two examples here, one with no extra columns and one with extra columns.
</blockquote></details>

Done. Updated to refer to comment below which explains the internal columns based on the lookup columns specified. Also added an example showing when and how the two schemas are combined. 

---

*[pkg/sql/distsqlrun/processors.proto, line 202 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21801#-L43AsjcpU793AZbQLJK:-L43JOA1vRSDrCcM0xFb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a97ef870f3b1e746899201c40e711051cf6b2890/pkg/sql/distsqlrun/processors.proto#L202)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The comment doesn't explain what the values are: column indices in the input stream.

[nit] It's good to avoid including the name in the comment because the go code will have a different looking name (LookupColumns).

I would also rephrase "if it is empty, the input columns are assumed to be all the index columns for index_idx".
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21801)*

**Comment by RaduBerinde** [comment]
LGTM, just one more comment.

---

Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsqlrun/joinreader.go, line 244 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21801#-L43Ce5fg1DWcu8bMu5c:-L46dZ6H7mQmsybPb_JX:b-vgwhya) ([raw file](https://github.com/cockroachdb/cockroach/blob/a97ef870f3b1e746899201c40e711051cf6b2890/pkg/sql/distsqlrun/joinreader.go#L244)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Where would an else be used here? We don't do anything here in the case where `jr.isLookupJoin()` is truthy. 
</blockquote></details>

Ah, sorry, I saw the `if jr.isLookupJoin()` above but that's inside the loop.

---

*[pkg/sql/distsqlrun/joinreader.go, line 293 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21801#-L46eP-rp_Ie57l5AV46:-L46eP-rp_Ie57l5AV47:b-rvo0af) ([raw file](https://github.com/cockroachdb/cockroach/blob/812c8629b7695d82ef82ca16155e5058b044385c/pkg/sql/distsqlrun/joinreader.go#L293)):*
> ```Go
> 			break
> 		}
> 		var renderedRow sqlbase.EncDatumRow
> ```

Do we need to allocate this every time? Can't we allocate it once, store it in `jr` and reuse it?

Even if we do, we should do a `make(sqlbase.EncDatumRow, 0, len(row) + len(indexRow))` to allocate only once.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21801#-:-L46egAt3ZgDmArbrXTR:b-xfyz3b)*

**Comment by arjunravinarayan** [comment]
:lgtm:

---

Reviewed 1 of 5 files at r2, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21801#-:-L4HArpRwnE-DkNKYxh5:bnfp4nl)*

**Comment by pbardea** [comment]
Thank you both for the reviews.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21801#-:-L4HBDbN3g6nXeZ8Bohl:b-unkjo)*

**Comment by RaduBerinde** [comment]
Just realized something.  Unlike index joins, lookup joins could get the same PK multiple times, and the expectation would be that those would be returned multiple times. I am not 100% sure that works properly.. if we request a batch of spans that has duplicates, does that work as expected? Would be good to add a test along these lines.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21801#-:-L5Alnm4NnLcMrb2Zz6V:b-z2fm4n)*

**Comment by pbardea** [comment]
@radu Yep, I'm working on a PR that I'm planning on putting up by EOD that finishes up some cases that were missed here. Cleaning it up right now, but it handles that case.

If I understand correctly, the primary key itself should not appear multiple times but it could match to multiple rows. When requesting a batch of spans that have duplicates the rowFetcher doesn't return duplicates, but I have found a way to work around.

**Comment by RaduBerinde** [comment]
We can get multiple PKs, consider `SELECT * FROM kv INNER JOIN (VALUES (1), (1), (1)) AS t(k) USING k`.

How could a single PK match to multiple rows?

**Pull request merged**
