### PR TITLE
vecstore: add the vecstore package

### PR DESCRIPTION
**Pull request by andy-kimball**
The vecstore package defines a Store interface that abstracts away the interactions that a vector index has with the component storing the vectors. This PR contains a simple implementation of Store that stores the vectors in memory. In the future, we'll have an implementation that stores the vectors in CRDB. The Store interface supports batching of important operations like Search so that in the future we can push such operations closer to the data. In addition, Store methods take a transaction so that the vector index can perform complex multi-step operations like split or merge with transactional guarantees.

Epic: CRDB-42943

Release note: None

### CODE REVIEW

**Review by mw5h — CHANGES_REQUESTED** [review]
> Reviewed 9 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134597)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @DrewKimball)

___
*[`pkg/sql/vecindex/vecstore/in_memory_store.go` line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134597#-OB8n6sI68nYI_GNCR65:-OB8n6sJ0T7gkkvHVEre:b-bgo4xr) ([raw file](https://github.com/cockroachdb/cockroach/blob/629dbb771be076fe1138d799ea1ec8b4b91022f8/pkg/sql/vecindex/vecstore/in_memory_store.go#L72)):*
> ```Go
> 	st := &InMemoryStore{
> 		raBitQuantizer: quantize.NewRaBitQuantizer(dims, seed),
> 		unquantizer:    quantize.NewUnQuantizer(dims),
> ```

I guess it doesn't matter really, but why instantiate both?
___
*[`pkg/sql/vecindex/vecstore/in_memory_store.go` line 345 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134597#-OB8mb5k5_HFHgYX7LUu:-OB8mb5k5_HFHgYX7LUv:b-odf4y2) ([raw file](https://github.com/cockroachdb/cockroach/blob/629dbb771be076fe1138d799ea1ec8b4b91022f8/pkg/sql/vecindex/vecstore/in_memory_store.go#L345)):*
> ```Go
> // DeleteVector deletes the vector associated with the given foreign key from
> // the in-memory store.
> func (s *InMemoryStore) DeleteVector(txn Txn, foreignKey ForeignKey) {
> ```

I would've assumed that these functions were meant to remove vectors from the index, including from leaf partitions.
___
*[`pkg/sql/vecindex/vecstore/partition.go` line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134597#-OB7mjFB2ysOAjcTfR8v:-OB7mjFB2ysOAjcTfR8w:b-ihv4cs) ([raw file](https://github.com/cockroachdb/cockroach/blob/629dbb771be076fe1138d799ea1ec8b4b91022f8/pkg/sql/vecindex/vecstore/partition.go#L18)):*
> ```Go
> // PartitionKey uniquely identifies a partition. Keys should never be reused as
> // partitions are created and deleted.
> type PartitionKey uint64
> ```

We can't name these Partitions, it's way too confusing. I just got done working on a bug involving SQL partitions and am currently working on another bug where we're merging partitions in an external sort incorrectly. Didn't the SPANN paper have another word they were using?
___
*[`pkg/sql/vecindex/vecstore/partition.go` line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134597#-OB8k4aLDTehAWdp8SKu:-OB8k4aLDTehAWdp8SKv:bu43fhl) ([raw file](https://github.com/cockroachdb/cockroach/blob/629dbb771be076fe1138d799ea1ec8b4b91022f8/pkg/sql/vecindex/vecstore/partition.go#L18)):*
> ```Go
> // PartitionKey uniquely identifies a partition. Keys should never be reused as
> // partitions are created and deleted.
> type PartitionKey uint64
> ```

If the expectation is that we're going to insert these sequentially, adding partitions is going to be quite slow. Maybe partition keys should be UUIDs?
___
*[`pkg/sql/vecindex/vecstore/partition.go` line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134597#-OB7nbid8dKkWPBahJF1:-OB7nbieBL5ka-4hXJgU:baadoi7) ([raw file](https://github.com/cockroachdb/cockroach/blob/629dbb771be076fe1138d799ea1ec8b4b91022f8/pkg/sql/vecindex/vecstore/partition.go#L30)):*
> ```Go
> // ForeignKey points to the unique row in the primary index that contains the
> // indexed vector.
> type ForeignKey []byte
> ```

Another loaded term. Also, a foreign key normally maps to another table. If the expectation is that that this is the primary key, why not just call it that?
___
*[`pkg/sql/vecindex/vecstore/store.go` line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134597#-OB8j4qlCEe7BK7Uz8XZ:-OB8j4qlCEe7BK7Uz8X_:b950jgb) ([raw file](https://github.com/cockroachdb/cockroach/blob/629dbb771be076fe1138d799ea1ec8b4b91022f8/pkg/sql/vecindex/vecstore/store.go#L27)):*
> ```Go
> 	// Key is a partition key (for an interior partition) or a foreign key (for
> 	// a leaf partition). If a partition key, the vector is the centroid of the
> 	// partition. Otherwise, it's the primary key of the row in the table that
> ```

I don't understand how a vector can be a primary key or why we would want this.
___
*[`pkg/sql/vecindex/vecstore/store.go` line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134597#-OB8jj9BDNwHGThReZNB:-OB8jj9BDNwHGThReZNC:bqr1x0a) ([raw file](https://github.com/cockroachdb/cockroach/blob/629dbb771be076fe1138d799ea1ec8b4b91022f8/pkg/sql/vecindex/vecstore/store.go#L84)):*
> ```Go
> 	) (int, error)
> 
> 	// RemoveFromPartition removes the given vector and its associated child key
> ```

Can you walk me through what we want to happen when a user deletes a row from the table? We obviously can figure out the childkey in that case, but how do we know the partitionKey?
___
*[`pkg/sql/vecindex/vecstore/store.go` line 118 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134597#-OB8lRV19XmObyp2AQnH:-OB8lRV19XmObyp2AQnI:b38x234) ([raw file](https://github.com/cockroachdb/cockroach/blob/629dbb771be076fe1138d799ea1ec8b4b91022f8/pkg/sql/vecindex/vecstore/store.go#L118)):*
> ```Go
> 	// deleted, then its corresponding reference will be set to nil. If a
> 	// partition cannot be found, GetFullVectors returns ErrPartitionNotFound.
> 	GetFullVectors(ctx context.Context, txn Txn, refs []VectorWithKey) error
> ```

This is a complicated function if, as I thought was decided, the full vectors live in the PK. We'll need to be able to figure out which column to get from the PK to read these values.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134597)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @mw5h)

___
*[`pkg/sql/vecindex/vecstore/in_memory_store.go` line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134597#-OB8n6sI68nYI_GNCR65:-OB8xTI111B6AbXkoPgS:bhjlm61) ([raw file](https://github.com/cockroachdb/cockroach/blob/629dbb771be076fe1138d799ea1ec8b4b91022f8/pkg/sql/vecindex/vecstore/in_memory_store.go#L72)):*
<details><summary><i>Previously, mw5h (Matt White) wrote…</i></summary><blockquote>

I guess it doesn't matter really, but why instantiate both?
</blockquote></details>

I was thinking about referencing these in a future PR, but not sure if that will happen. I can remove for now.
___
*[`pkg/sql/vecindex/vecstore/in_memory_store.go` line 345 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134597#-OB8mb5k5_HFHgYX7LUu:-OB8z0qP5DtBXFcaT4o9:b-64tnl2) ([raw file](https://github.com/cockroachdb/cockroach/blob/629dbb771be076fe1138d799ea1ec8b4b91022f8/pkg/sql/vecindex/vecstore/in_memory_store.go#L345)):*
<details><summary><i>Previously, mw5h (Matt White) wrote…</i></summary><blockquote>

I would've assumed that these functions were meant to remove vectors from the index, including from leaf partitions.
</blockquote></details>

The InsertVector/DeleteVector methods are not part of the Store interface. They're just here to mimic inserting/deleting a vector into/from the primary index. We need to simulate doing that as part of testing, and this is how we'll do it. I added a bit to the comments to try and make that more clear.

To insert/remove a vector into/from the vector index, there will be InsertVector/DeleteVector methods on the `VectorIndex` class.
___
*[`pkg/sql/vecindex/vecstore/partition.go` line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134597#-OB7mjFB2ysOAjcTfR8v:-OB90SiDAPb6OOA6S8sn:b1xlzlz) ([raw file](https://github.com/cockroachdb/cockroach/blob/629dbb771be076fe1138d799ea1ec8b4b91022f8/pkg/sql/vecindex/vecstore/partition.go#L18)):*
<details><summary><i>Previously, mw5h (Matt White) wrote…</i></summary><blockquote>

We can't name these Partitions, it's way too confusing. I just got done working on a bug involving SQL partitions and am currently working on another bug where we're merging partitions in an external sort incorrectly. Didn't the SPANN paper have another word they were using?
</blockquote></details>

The paper is not very consistent in its naming, using the words "cluster", "partition", and "posting list" in various places. I originally was using the word "cluster", but that seemed even worse than "partition".

I'm not sure the examples you give are actually a big deal. SQL partitions vs. sort partitions vs. vector partitions are used in different contexts and should never overlap. Vector partitions are only used down deep in the vector indexing code and don't really "leak" out of that context. Furthermore, the entire design doc was filled with the usage of the word "partition" and I got no objections from any of the many reviewers who reviewed it. It would be a ton of busy work to change this terminology now, including thousands of references in the design doc and in thousands of lines of code and comments.
___
*[`pkg/sql/vecindex/vecstore/partition.go` line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134597#-OB8k4aLDTehAWdp8SKu:-OB92veB96rryaaHlko7:b-x1z5f8) ([raw file](https://github.com/cockroachdb/cockroach/blob/629dbb771be076fe1138d799ea1ec8b4b91022f8/pkg/sql/vecindex/vecstore/partition.go#L18)):*
<details><summary><i>Previously, mw5h (Matt White) wrote…</i></summary><blockquote>

If the expectation is that we're going to insert these sequentially, adding partitions is going to be quite slow. Maybe partition keys should be UUIDs?
</blockquote></details>

I'm expecting these to be unique row IDs (i.e. generated by `unique_rowid`), and so should not have hot-spot issues. These are shorter than UUIDs, but should have similar properties for this use-case.
___
*[`pkg/sql/vecindex/vecstore/partition.go` line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134597#-OB7nbid8dKkWPBahJF1:-OB946b26y4fcpYGFDlt:b-892mu1) ([raw file](https://github.com/cockroachdb/cockroach/blob/629dbb771be076fe1138d799ea1ec8b4b91022f8/pkg/sql/vecindex/vecstore/partition.go#L30)):*
<details><summary><i>Previously, mw5h (Matt White) wrote…</i></summary><blockquote>

Another loaded term. Also, a foreign key normally maps to another table. If the expectation is that that this is the primary key, why not just call it that?
</blockquote></details>

Yeah, during my prototyping the vector index was more of a standalone thing and I pulled the code over from that. I'll switch it to `PrimaryKey`.
___
*[`pkg/sql/vecindex/vecstore/store.go` line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134597#-OB8j4qlCEe7BK7Uz8XZ:-OB96prE7xSwjCsTblmT:bbv2ezx) ([raw file](https://github.com/cockroachdb/cockroach/blob/629dbb771be076fe1138d799ea1ec8b4b91022f8/pkg/sql/vecindex/vecstore/store.go#L27)):*
<details><summary><i>Previously, mw5h (Matt White) wrote…</i></summary><blockquote>

I don't understand how a vector can be a primary key or why we would want this.
</blockquote></details>

"it's the primary key" is referring to the `Key` field, not to the `Vector` field. I updated the comment.
___
*[`pkg/sql/vecindex/vecstore/store.go` line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134597#-OB8jj9BDNwHGThReZNB:-OB97a-qE1ZO_p8MaHBH:b36hw38) ([raw file](https://github.com/cockroachdb/cockroach/blob/629dbb771be076fe1138d799ea1ec8b4b91022f8/pkg/sql/vecindex/vecstore/store.go#L84)):*
Here's a bit of context from the spec:
> To delete a vector from the index, it first must be located in the tree. As long as beam_size is set high enough for the search, it is extremely likely that the search will find the vector. A garbage detection and collection mechanism (described later) will handle the case where it cannot be found. Assuming the vector is found, it is removed from the owning leaf partition.

> Updating a vector can simply be treated as a delete followed by an insert.

So when we find the vector in the index during the search, we know the key of the partition where we found it. And in the rare case where we can't locate the vector in the index, we end up with a "dangling vector" and would not be able to call `Store.RemoveFromPartition`.
___
*[`pkg/sql/vecindex/vecstore/store.go` line 118 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134597#-OB8lRV19XmObyp2AQnH:-OB98rPK3xOvys4WFr3p:btr37ia) ([raw file](https://github.com/cockroachdb/cockroach/blob/629dbb771be076fe1138d799ea1ec8b4b91022f8/pkg/sql/vecindex/vecstore/store.go#L118)):*
<details><summary><i>Previously, mw5h (Matt White) wrote…</i></summary><blockquote>

This is a complicated function if, as I thought was decided, the full vectors live in the PK. We'll need to be able to figure out which column to get from the PK to read these values.
</blockquote></details>

I think this is a misunderstanding; the full vectors aren't part of the primary key. In fact, it's an error if you try to include a vector column in a primary key. For leaf partitions, the `VectorWithKey` slice would contain the primary keys of the rows containing the vectors we want to fetch. `GetFullVectors` would then fetch those vectors using the primary keys and then store them in the `VectorWithKey.Vector` fields.

**Comment by andy-kimball** [comment]
*[`pkg/sql/vecindex/vecstore/partition.go` line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134597#-OB7mjFB2ysOAjcTfR8v:-OB9Acbo5BCoIVteIElp:brerd4k) ([raw file](https://github.com/cockroachdb/cockroach/blob/629dbb771be076fe1138d799ea1ec8b4b91022f8/pkg/sql/vecindex/vecstore/partition.go#L18)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

The paper is not very consistent in its naming, using the words "cluster", "partition", and "posting list" in various places. I originally was using the word "cluster", but that seemed even worse than "partition".

I'm not sure the examples you give are actually a big deal. SQL partitions vs. sort partitions vs. vector partitions are used in different contexts and should never overlap. Vector partitions are only used down deep in the vector indexing code and don't really "leak" out of that context. Furthermore, the entire design doc was filled with the usage of the word "partition" and I got no objections from any of the many reviewers who reviewed it. It would be a ton of busy work to change this terminology now, including thousands of references in the design doc and in thousands of lines of code and comments.
</blockquote></details>

Whoops, I meant hundreds in the design doc, not thousands.

**Comment by andy-kimball** [comment]
*[`pkg/sql/vecindex/vecstore/partition.go` line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134597#-OB8k4aLDTehAWdp8SKu:-OBB2KC64iGGTP2Xgu0N:b1k767i) ([raw file](https://github.com/cockroachdb/cockroach/blob/629dbb771be076fe1138d799ea1ec8b4b91022f8/pkg/sql/vecindex/vecstore/partition.go#L18)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I'm expecting these to be unique row IDs (i.e. generated by `unique_rowid`), and so should not have hot-spot issues. These are shorter than UUIDs, but should have similar properties for this use-case.
</blockquote></details>

One thing I have considered is switching this to be `[]byte`, so that it can support multi-column keys in the future. But I decided to hold off on that for the time being, until we get more clarity on how that might work.

**Review by mw5h — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2, 6 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134597)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball and @DrewKimball)

___
*[`pkg/sql/vecindex/vecstore/store.go` line 84 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134597#-OB8jj9BDNwHGThReZNB:-OBBoUfB9jAW_9tkbDSa:b-jmkbjx) ([raw file](https://github.com/cockroachdb/cockroach/blob/629dbb771be076fe1138d799ea1ec8b4b91022f8/pkg/sql/vecindex/vecstore/store.go#L84)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Here's a bit of context from the spec:
> To delete a vector from the index, it first must be located in the tree. As long as beam_size is set high enough for the search, it is extremely likely that the search will find the vector. A garbage detection and collection mechanism (described later) will handle the case where it cannot be found. Assuming the vector is found, it is removed from the owning leaf partition.

> Updating a vector can simply be treated as a delete followed by an insert.

So when we find the vector in the index during the search, we know the key of the partition where we found it. And in the rare case where we can't locate the vector in the index, we end up with a "dangling vector" and would not be able to call `Store.RemoveFromPartition`.
</blockquote></details>

Okay, but we can at least detect that when we try to retrieve the full vector. It's imperfect, but way cheaper than keeping a separate sorting of the data to support deleting. Thanks!
___
*[`pkg/sql/vecindex/vecstore/store.go` line 118 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134597#-OB8lRV19XmObyp2AQnH:-OBBoky72Uc5MZ7fM3wa:b4fe2ow) ([raw file](https://github.com/cockroachdb/cockroach/blob/629dbb771be076fe1138d799ea1ec8b4b91022f8/pkg/sql/vecindex/vecstore/store.go#L118)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I think this is a misunderstanding; the full vectors aren't part of the primary key. In fact, it's an error if you try to include a vector column in a primary key. For leaf partitions, the `VectorWithKey` slice would contain the primary keys of the rows containing the vectors we want to fetch. `GetFullVectors` would then fetch those vectors using the primary keys and then store them in the `VectorWithKey.Vector` fields.
</blockquote></details>

By 'in the PK', I meant as payload, not as part of the key. I thought the plan was to store the full length vectors as payload in the primary index, but maybe I'm misremembering?

**Review by mw5h — APPROVED** [review]
:lgtm:

> Reviewed 4 of 10 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134597#-:-OBSLYcQ6lSP5hs5BLVg:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @DrewKimball)

**Comment by andy-kimball** [comment]
bors r=mw5h

**Pull request merged**
