### PR TITLE
concurrency: introduce lock.Mode concept 

### PR DESCRIPTION
**Pull request by arulajmani**
This patch introduces the concept of a `lock.Mode`, which ties together
`lock.Strength` with other auxiliary information (read: timestamps) to
resolve conflicts between 2 lock holders.

Previously, `lock.Strength` was used both by users of the KV layer to
indicate desired locking intention and by the `concurrency` package
internally to do conflict resolution. `lock.Strength` continues to
do the former. With this change, `lock.Mode` assumes the responsibility
for the latter.

Given this motivation, this patch expresses lock compatiility/conflict
as pure functions of 2 `lock.Modes`.

This patch also introduces a new lock Strength, called Intent.
Conceptually, these are stronger than `Exclusive` locks and map on-to
the existing concept of Intents. The difference lies in their
interaction with non-locking reads. Non-locking reads conflict with
intents, whereas `Exclusive` locks do not. This is a forward looking
change with non-blocking reads in mind.

Note that non-locking reads not blocking on `Exclusive` locks changes
existing behavior. As such, we introduce a new cluster setting
(`kv.lock.exclusive_locks_block_non_locking_reads`) which, when set,
reverts to the old behavior. By default, this setting is set to true,
which means we're not changing any default behavior with this patch
just yet.

Informs https://github.com/cockroachdb/cockroach/issues/91545

Release note: None

### CODE REVIEW

**Comment by arulajmani** [comment]
@nvanbenschoten I want to take another pass here before I ask you to take an in-depth look, but let's discuss the high level stuff in todays Txn weekly.

**Comment by yuzefovich** [comment]
SQL changes LGTM.

**Review by nvb — COMMENTED** [review]
> Reviewed 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96026)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks, @arulajmani, and @RaduBerinde)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96026#-NN8thOv8ocdfVx5goN-):*
After thinking about this more, I agree with @shralex that the naming change isn't quite right. Interestingly, PG's code has a notion of a lock "strength" and a lock "mode", but their meanings are roughly switched from what you have here. A locking mode includes a strength and a few other details about the target of the lock. So I'd suggest we switch the two names.

I'd also suggest that so that the `LockingStrength` concept in SQL (which is analogous to PG's `LockClauseStrength`) doesn't need to change.
___
*[`pkg/kv/kvserver/concurrency/lock/locking.go` line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96026#-NN8uixU4ClQ_6pNCjVU:-NN8uixU4ClQ_6pNCjVV:b-6pof9v) ([raw file](https://github.com/cockroachdb/cockroach/blob/b490de944c016f318e032f3529e9218046749705/pkg/kv/kvserver/concurrency/lock/locking.go#L97)):*
> ```Go
> 
> // MakeStrength constructs a well-formed lock Strength.
> func MakeStrength(mode LockMode, opts ...StrengthOption) Strength {
> ```

The functional option pattern is nice, but it's also expensive. For instance, I think `AtTimestamp` allocates the returned closure.

We only have a few strengths, so I wonder if we could get away with specialized constructors for each locking strength. Would that make the code easier to read at callers?
___
*[`pkg/kv/kvserver/concurrency/lock/locking.proto` line 157 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96026#-NN8vEjA9blZ23ep6jdr:-NN8vEjA9blZ23ep6jds:b-7wlw27) ([raw file](https://github.com/cockroachdb/cockroach/blob/b490de944c016f318e032f3529e9218046749705/pkg/kv/kvserver/concurrency/lock/locking.proto#L157)):*
> ```protobuf
> //  | None       |         |           |           |      X^*    |    X^†   |
> //  +------------+---------+-----------+-----------+-------------+----------+
> //  | Shared     |         |           |     X     |      X      |    X     |
> ```

You were planning to fix the Upgrade lock description, right? An Upgrade lock does not conflict with Shared locks, but does conflict with other Upgrade locks.

Also, I got the name wrong. They're actually called Update locks (see https://learn.microsoft.com/en-us/sql/relational-databases/sql-server-transaction-locking-and-row-versioning-guide?view=sql-server-ver16#update) :facepalm: 
___
*[`pkg/kv/kvserver/concurrency/lock/locking.proto` line 180 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96026#-NN8vuTD2NVQgGr2tEBD:-NN8vuTD2NVQgGr2tEBE:bljibcq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b490de944c016f318e032f3529e9218046749705/pkg/kv/kvserver/concurrency/lock/locking.proto#L180)):*
> ```protobuf
> // TODO(arul): Add a reference to the cluster setting here.
> //
> // TODO(XXX): Do we need this to be a proto? Or are we happy with a regular go
> ```

I think a proto makes sense, in case we want to store these in persisted locks if/when we get there.

**Review by arulajmani — COMMENTED** [review]
I'll do the `s/Update/Upgrade/g` switch in another commit so that reviewing it is easy. I'll tack it on this PR tomorrow; pushing out all other changes before I sign off for the day though. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96026#-:-NNoO0rs9F3MNIyjkdgQ:b4p39a)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks, @nvanbenschoten, and @RaduBerinde)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96026#-NN8thOv8ocdfVx5goN-):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

After thinking about this more, I agree with @shralex that the naming change isn't quite right. Interestingly, PG's code has a notion of a lock "strength" and a lock "mode", but their meanings are roughly switched from what you have here. A locking mode includes a strength and a few other details about the target of the lock. So I'd suggest we switch the two names.

I'd also suggest that so that the `LockingStrength` concept in SQL (which is analogous to PG's `LockClauseStrength`) doesn't need to change.
</blockquote></details>

Done. Dropped the first commit entirely and added `lock.Mode` to encapsulate `lock.Strength` + auxiliary information, like you suggested. 
___
*[`pkg/kv/kvserver/concurrency/lock/locking.go` line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96026#-NN8uixU4ClQ_6pNCjVU:-NNoAwXRBl4rqa3c0w__:brjto2i) ([raw file](https://github.com/cockroachdb/cockroach/blob/b490de944c016f318e032f3529e9218046749705/pkg/kv/kvserver/concurrency/lock/locking.go#L97)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The functional option pattern is nice, but it's also expensive. For instance, I think `AtTimestamp` allocates the returned closure.

We only have a few strengths, so I wonder if we could get away with specialized constructors for each locking strength. Would that make the code easier to read at callers?
</blockquote></details>

Changed explicit constructors for all (what is now) lock modes. 
___
*[`pkg/kv/kvserver/concurrency/lock/locking.proto` line 157 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96026#-NN8vEjA9blZ23ep6jdr:-NNoFGRf5-C5bMl-bjFb:b-1vg7du) ([raw file](https://github.com/cockroachdb/cockroach/blob/b490de944c016f318e032f3529e9218046749705/pkg/kv/kvserver/concurrency/lock/locking.proto#L157)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

You were planning to fix the Upgrade lock description, right? An Upgrade lock does not conflict with Shared locks, but does conflict with other Upgrade locks.

Also, I got the name wrong. They're actually called Update locks (see https://learn.microsoft.com/en-us/sql/relational-databases/sql-server-transaction-locking-and-row-versioning-guide?view=sql-server-ver16#update) :facepalm: 
</blockquote></details>

Yeah, I didn't get a chance to push changes here after our discussion -- changed this matrix and the implementation/tests of our compatibility function. 
___
*[`pkg/kv/kvserver/concurrency/lock/locking.proto` line 180 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96026#-NN8vuTD2NVQgGr2tEBD:-NNoBP0k6va_Z6ogKpYN:b-5ixv2r) ([raw file](https://github.com/cockroachdb/cockroach/blob/b490de944c016f318e032f3529e9218046749705/pkg/kv/kvserver/concurrency/lock/locking.proto#L180)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I think a proto makes sense, in case we want to store these in persisted locks if/when we get there.
</blockquote></details>

Makes sense!

**Review by arulajmani — COMMENTED** [review]
> I'll do the s/Update/Upgrade/g switch in another commit so that reviewing it is easy.
 
Done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96026#-:-NNvsYzp1OPIUvG5qRu7:bpkpthk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks, @nvanbenschoten, and @RaduBerinde)

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 27 of 27 files at r3, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96026#-:-NNxLAGc6FSiGNzackuV:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @AlexTalks, @arulajmani, and @RaduBerinde)

___
*[`pkg/kv/kvserver/concurrency/lock/locking.go` line 19 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96026#-NNwXvuo7R_51iKGt0EH:-NNwXvuo7R_51iKGt0EI:bptgdbm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef9b260caa71ff78b55dd13a54ea99831ceaaac6/pkg/kv/kvserver/concurrency/lock/locking.go#L19)):*
> ```Go
> 
> 	"github.com/cockroachdb/cockroach/pkg/settings"
> 	hlc "github.com/cockroachdb/cockroach/pkg/util/hlc"
> ```

nit: no need for the alias here, Goland
___
*[`pkg/kv/kvserver/concurrency/lock/locking.go` line 39 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96026#-NNxKaTDAzhom_tLnXaa:-NNxKaTDAzhom_tLnXab:b-v0fmz3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef9b260caa71ff78b55dd13a54ea99831ceaaac6/pkg/kv/kvserver/concurrency/lock/locking.go#L39)):*
> ```Go
> 	"dictates the locking interactions between exclusive locks and non-locking reads",
> 	true,
> ).WithPublic()
> ```

We should probably keep this setting hidden for now.
___
*[`pkg/kv/kvserver/concurrency/lock/locking.go` line 55 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96026#-NNwY7ItCcaGmIt53Jwk:-NNwY7ItCcaGmIt53Jwl:b6fie16) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef9b260caa71ff78b55dd13a54ea99831ceaaac6/pkg/kv/kvserver/concurrency/lock/locking.go#L55)):*
> ```Go
> // the receiver. The conflict rules are as described in the compatibility matrix
> // in locking.pb.go.
> func (m *Mode) CheckLockConflicts(sv *settings.Values, o *Mode) bool {
> ```

Consider just naming this `Conflicts` for succinctness. Same thing with the method below. `Compatible` would be enough.
___
*[`pkg/kv/kvserver/concurrency/lock/locking.go` line 59 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96026#-NNwYswOEX8PrG-MN1v8:-NNwYswOEX8PrG-MN1v9:busfnvg) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef9b260caa71ff78b55dd13a54ea99831ceaaac6/pkg/kv/kvserver/concurrency/lock/locking.go#L59)):*
> ```Go
> }
> 
> // CheckLockCompatibility returns whether the supplied lock mode is
> ```

It might be confusing to have two methods here. Callers will need to ask which one they want to use and will need to jump to this code to convince themselves that the two predicates are inverses. Do we need them both?
___
*[`pkg/kv/kvserver/concurrency/lock/locking.proto` line 18 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96026#-NNxJ6qe1MQ11Q2sBXZL:-NNxJ6qe1MQ11Q2sBXZM:b3mlmzf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef9b260caa71ff78b55dd13a54ea99831ceaaac6/pkg/kv/kvserver/concurrency/lock/locking.proto#L18)):*
> ```protobuf
> import "util/hlc/timestamp.proto";
> 
> // Strength represents the different locking strength that determines how
> ```

"locking strengths that determine how"?
___
*[`pkg/kv/kvserver/concurrency/lock/locking.proto` line 90 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96026#-NNxJWFe8g9guk8TVwZa:-NNxJWFe8g9guk8TVwZb:b-lpkqhx) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef9b260caa71ff78b55dd13a54ea99831ceaaac6/pkg/kv/kvserver/concurrency/lock/locking.proto#L90)):*
> ```protobuf
>   // holders are not waiting on the Upgrade lock in any way.
>   //
>   // Under pure pessimistic concurrency control, an Upgrade lock is equivalent
> ```

Should these two paragraphs be moved to Exclusive and reworded?
___
*[`pkg/kv/kvserver/concurrency/lock/locking.proto` line 109 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96026#-NNxJqbc3IEXmWXcClnG:-NNxJqbd0v-qU_7zSfmE:b-vk1jig) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef9b260caa71ff78b55dd13a54ea99831ceaaac6/pkg/kv/kvserver/concurrency/lock/locking.proto#L109)):*
> ```protobuf
>   // TODO(XXX): How should we frame the wording around "being forced to increase
>   // write timestamp when converting to an Exclusive lock" -- is this something
>   // that will (can?) happen? Or will this only happen when laying down intents.
> ```

Yeah, this should only happen when laying down intents.
___
*[`pkg/kv/kvserver/concurrency/lock/locking_test.go` line 26 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96026#-NNxKVB-BiWm_0YeEp5-:-NNxKVB0CO_Z5pb7HF2M:bds3i29) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef9b260caa71ff78b55dd13a54ea99831ceaaac6/pkg/kv/kvserver/concurrency/lock/locking_test.go#L26)):*
> ```Go
> // TestCheckLockCompatibility ensures the compatibility semantics, as
> // illustrated in the compatibility matrix in locking.pb.go, are upheld.
> func TestCheckLockCompatibility(t *testing.T) {
> ```

Nice test!

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96026)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @AlexTalks, @arulajmani, and @RaduBerinde)

___
*[`pkg/kv/kvserver/concurrency/lock/locking.proto` line 180 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96026#-NOAaUcH7p5uxTf8vvjW:-NOAaUcH7p5uxTf8vvjX:b9bcrkh) ([raw file](https://github.com/cockroachdb/cockroach/blob/baef5d6635776ca351619443e387cf2b46616e2d/pkg/kv/kvserver/concurrency/lock/locking.proto#L180)):*
> ```protobuf
> // above the Exclusive lock's timestamp. Now that there is a distinction between
> // Exclusive locks and Intents, non-locking reads do not block on Exclusive
> // locks, regardless of their timestamp. However, there is a desire to let users
> ```

(drive-by) will these exclusive locks be persisted, like we currently persist intents, or will they be best-effort, like our current unreplicated locks?

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96026)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @AlexTalks, @RaduBerinde, and @sumeerbhola)

___
*[`pkg/kv/kvserver/concurrency/lock/locking.proto` line 180 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96026#-NOAaUcH7p5uxTf8vvjW:-NOQ1Eby8AisCHO52_AX:b-tcmxke) ([raw file](https://github.com/cockroachdb/cockroach/blob/baef5d6635776ca351619443e387cf2b46616e2d/pkg/kv/kvserver/concurrency/lock/locking.proto#L180)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

(drive-by) will these exclusive locks be persisted, like we currently persist intents, or will they be best-effort, like our current unreplicated locks?
</blockquote></details>

They won't be persisted and will continue to be best effort, like today. We've been discussing how to make this "best effort" situation better, in the context of lower isolation levels where we need locks for correctness, but I don't think we've bottomed out there yet.

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96026)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @AlexTalks, @nvanbenschoten, @RaduBerinde, and @sumeerbhola)

___
*[`pkg/kv/kvserver/concurrency/lock/locking.go` line 39 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96026#-NNxKaTDAzhom_tLnXaa:-NORMEcP-b-cOjLGrQCT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef9b260caa71ff78b55dd13a54ea99831ceaaac6/pkg/kv/kvserver/concurrency/lock/locking.go#L39)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We should probably keep this setting hidden for now.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/concurrency/lock/locking.go` line 55 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96026#-NNwY7ItCcaGmIt53Jwk:-NORAiyg7iqXAzr0ddqt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef9b260caa71ff78b55dd13a54ea99831ceaaac6/pkg/kv/kvserver/concurrency/lock/locking.go#L55)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Consider just naming this `Conflicts` for succinctness. Same thing with the method below. `Compatible` would be enough.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/concurrency/lock/locking.go` line 59 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96026#-NNwYswOEX8PrG-MN1v8:-NORAk3tE2wmLpnZ2Jsq:b4bvonw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef9b260caa71ff78b55dd13a54ea99831ceaaac6/pkg/kv/kvserver/concurrency/lock/locking.go#L59)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It might be confusing to have two methods here. Callers will need to ask which one they want to use and will need to jump to this code to convince themselves that the two predicates are inverses. Do we need them both?
</blockquote></details>

Got rid of the `Compatible` method -- like we discussed, we don't need both. 
___
*[`pkg/kv/kvserver/concurrency/lock/locking.proto` line 90 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96026#-NNxJWFe8g9guk8TVwZa:-NORK_m8BUrNLVD_l0SL:b3ihkwc) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef9b260caa71ff78b55dd13a54ea99831ceaaac6/pkg/kv/kvserver/concurrency/lock/locking.proto#L90)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should these two paragraphs be moved to Exclusive and reworded?
</blockquote></details>

Done. I ended up hinting at buffered writes here:

```
  // Note that for this to be meaningful, the write transaction
  // must acquire Exclusive locks as it is executing and only lay down Intents
  // once it is ready to commit.
```

Let me know if you're not a fan. 
___
*[`pkg/kv/kvserver/concurrency/lock/locking.proto` line 109 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/96026#-NNxJqbc3IEXmWXcClnG:-NORCA6pBXwL5ytLmcX-:b5usyo1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef9b260caa71ff78b55dd13a54ea99831ceaaac6/pkg/kv/kvserver/concurrency/lock/locking.proto#L109)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yeah, this should only happen when laying down intents.
</blockquote></details>

Thanks, clarified.

**Comment by arulajmani** [comment]
TFTR! 

bors r=nvanbenschoten

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96026)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[`pkg/kv/kvserver/concurrency/lock/locking.proto` line 125 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/96026#-NQ_uJmDE9f0PHqmPsYR:-NQ_uJmDE9f0PHqmPsYS:b-qs7jsi) ([raw file](https://github.com/cockroachdb/cockroach/blob/42db3e9ae57948125f2fd81b7952317896f02c6d/pkg/kv/kvserver/concurrency/lock/locking.proto#L125)):*
> ```protobuf
>   // that key. The lock holder is free to read from and write to the key as
>   // frequently as it would like.
>   Intent = 4;
> ```

We serialize the `lock.Strength` in `LockTableKey` and currently `Exclusive` is used for intents. I assume we will want to switch to `Intent`, but then we need to assign `Intent = 3`.

**Pull request merged**
