### PR TITLE
pkg/ui: Don't force tracez tags to uppercase.

### PR DESCRIPTION
**Pull request by benbardin**
Also, deprecate uses of db-console/.../Badge in favor of the identical version
in cluster-ui.

Screen Shot 2022-07-06 at 1 21 50 PM

Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
thanks

**Review by benbardin — COMMENTED** [review]
You're welcome @knz ! CI is passing now, can I get an LGTM? Thank you!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83913#-:-N6TFdCADUibeP6Svetd:bqzkeoq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @andreimatei)

**Comment by knz** [comment]
I'm OK with the change, but I'm not technology expert on the front-end.
Do you want to get your code review from someone with front-end expertise? For example @nathanstilwell , @dhartunian or @koorosh

**Review by benbardin — COMMENTED** [review]
Can do!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83913#-:-N6TH3qN37KoJbZJ-6Kt:b13pu5d)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @andreimatei)

**Comment by nathanstilwell** [comment]
*[`pkg/ui/workspaces/cluster-ui/src/badge/badge.tsx` line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83913#-N6TTIta21yE7a4aCWhV:-N6TTIta21yE7a4aCWhW:bpkej5m) ([raw file](https://github.com/cockroachdb/cockroach/blob/302e95cff50fc8e65fe2d95c3e689900b38bfdbc/pkg/ui/workspaces/cluster-ui/src/badge/badge.tsx#L35)):*
> ```XML
>     styles.push("badge--uppercase");
>   }
>   const classes = cx(...styles);
> ```

So `classnames` already [has the functionality you are creating here](https://github.com/JedWatson/classnames#usage) (the ability to add a className based on a boolean variable). So I think what you want is something like,

```
const classes = cx("badge", `badge--size-${size}`, `badge--status-${status}`{
    "badge--uppercase": !allowLowerCase,
  });
```

This actually makes this kind of confusing for me to read since we are applying the `badge--uppercase` class after negating a variable. It seems like the default for badges should be that they are uppercase and we want the ability to override that. So what if we had a prop called something like `uppercase` and defaulted it to false? Then the `cx` call would look like,

```
const classes = cx("badge", `badge--size-${size}`, `badge--status-${status}`{
    "badge--uppercase": uppercase,
  });
```

giving us something like,

```
export function Badge(props: BadgeProps) {
  const { size, status, icon, iconPosition, text, uppercase = true } = props;
  const classes = cx("badge", `badge--size-${size}`, `badge--status-${status}`{
    "badge--uppercase": uppercase,
  });

```

Anyway, just a thought.



_Code quote:_
```XML
  const { size, status, icon, iconPosition, text, allowLowerCase } = props;
  const styles = ["badge", `badge--size-${size}`, `badge--status-${status}`];
  if (!allowLowerCase) {
    styles.push("badge--uppercase");
  }
  const classes = cx(...styles);
```

**Comment by nathanstilwell** [comment]
Thanks for cutting out a duplicate! I think I would prefer that we use `Badge` from `@cockroachlabs/ui-components` everywhere, but looking at the implementation it differs slightly from what's in this repo and doesn't support all the features that have been added in Figma for badges (which makes me suspect that this implementation may differ from what's in Managed Service).  All that to say, we can worry about migrating to the UI repo another time.

Thank you.

**Review by benbardin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83913)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @andreimatei, @dhartunian, @koorosh, and @nathanstilwell)

___
*[`pkg/ui/workspaces/cluster-ui/src/badge/badge.tsx` line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83913#-N6TTIta21yE7a4aCWhV:-N6hhwVu3zNA6X1uGaSG:b5xj4l4) ([raw file](https://github.com/cockroachdb/cockroach/blob/302e95cff50fc8e65fe2d95c3e689900b38bfdbc/pkg/ui/workspaces/cluster-ui/src/badge/badge.tsx#L35)):*
<details><summary><i>Previously, nathanstilwell (Nathan Stilwell) wrote…</i></summary><blockquote>

So `classnames` already [has the functionality you are creating here](https://github.com/JedWatson/classnames#usage) (the ability to add a className based on a boolean variable). So I think what you want is something like,

```
const classes = cx("badge", `badge--size-${size}`, `badge--status-${status}`{
    "badge--uppercase": !allowLowerCase,
  });
```

This actually makes this kind of confusing for me to read since we are applying the `badge--uppercase` class after negating a variable. It seems like the default for badges should be that they are uppercase and we want the ability to override that. So what if we had a prop called something like `uppercase` and defaulted it to false? Then the `cx` call would look like,

```
const classes = cx("badge", `badge--size-${size}`, `badge--status-${status}`{
    "badge--uppercase": uppercase,
  });
```

giving us something like,

```
export function Badge(props: BadgeProps) {
  const { size, status, icon, iconPosition, text, uppercase = true } = props;
  const classes = cx("badge", `badge--size-${size}`, `badge--status-${status}`{
    "badge--uppercase": uppercase,
  });

```

Anyway, just a thought.
</blockquote></details>

Oh, neat trick! Thanks! How's this look?

**Comment by nathanstilwell** [comment]
*[`pkg/ui/workspaces/cluster-ui/src/badge/badge.tsx` line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83913#-N6TTIta21yE7a4aCWhV:-N6hr9jD7wk7uAjW5ayB:bx9dolu) ([raw file](https://github.com/cockroachdb/cockroach/blob/302e95cff50fc8e65fe2d95c3e689900b38bfdbc/pkg/ui/workspaces/cluster-ui/src/badge/badge.tsx#L35)):*
<details><summary><i>Previously, benbardin (Ben Bardin) wrote…</i></summary><blockquote>

Oh, neat trick! Thanks! How's this look?
</blockquote></details>

I still find reviewable very confusing, but I'm not seeing a change yet. Am I missing something?

**Review by benbardin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83913)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @andreimatei, @dhartunian, @koorosh, and @nathanstilwell)

___
*[`pkg/ui/workspaces/cluster-ui/src/badge/badge.tsx` line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83913#-N6TTIta21yE7a4aCWhV:-N6i1Dy97P4sqOT5hSUM:bvk3g94) ([raw file](https://github.com/cockroachdb/cockroach/blob/302e95cff50fc8e65fe2d95c3e689900b38bfdbc/pkg/ui/workspaces/cluster-ui/src/badge/badge.tsx#L35)):*
<details><summary><i>Previously, nathanstilwell (Nathan Stilwell) wrote…</i></summary><blockquote>

I still find reviewable very confusing, but I'm not seeing a change yet. Am I missing something?
</blockquote></details>

No, I just forgot to commit locally before pushing :facepalm: How about now?

**Comment by nathanstilwell** [comment]
*[`pkg/ui/workspaces/cluster-ui/src/badge/badge.tsx` line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83913#-N6TTIta21yE7a4aCWhV:-N6iR9qOB7s9y_w2O8cI:b-83sjo4) ([raw file](https://github.com/cockroachdb/cockroach/blob/302e95cff50fc8e65fe2d95c3e689900b38bfdbc/pkg/ui/workspaces/cluster-ui/src/badge/badge.tsx#L35)):*
<details><summary><i>Previously, benbardin (Ben Bardin) wrote…</i></summary><blockquote>

No, I just forgot to commit locally before pushing :facepalm: How about now?
</blockquote></details>

Nice.

**Review by nathanstilwell — APPROVED** [review]
> Reviewed 10 of 10 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83913)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @andreimatei, @dhartunian, and @koorosh)

**Pull request merged**
