### PR TITLE
sql: allow primary key changes on an interleaved child

### PR DESCRIPTION
**Pull request by rohany**
This PR allows for users to change the primary key of a table
that is an interleaved child which also doesn't have any children.

Importantly, note that if the user does not specify an
`INTERLEAVE IN PARENT...` clause in their `ALTER PRIMARY KEY`
statement, then the new primary key _will not be interleaved_,
even if the current table is an interleaved child. If users
their interleaved table to have a new primary key that is
also interleaved, then they will need to use the `INTERLEAVE IN PARENT`
clause.

Release note (sql change): This PR allows for primary key changes to
be performed on interleaved children.

### CODE REVIEW

**Comment by rohany** [comment]
Depends on https://github.com/cockroachdb/cockroach/pull/44038, the second commit is this PR.

**Comment by rohany** [comment]
I think this PR needs some more work. I realized I didn't think about the case when a secondary index that needs to be rewritten is interleaved into another table -- then some more bookkeeping needs to occur.

**Comment by rohany** [comment]
Alright, thats been updated -- its ready for a look now.

**Review by solongordon — APPROVED** [review]
> Reviewed 7 of 7 files at r1, 2 of 5 files at r2, 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44075)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang, @rohany, and @solongordon)

___
*[pkg/sql/schema_changer.go, line 1347 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44075#-LykMJEFCHiKewEpVgDs:-LykMJEFCHiKewEpVgDt:b-6r9izb) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa68ea2508b5d3f8df29285c963d3180354cc36a/pkg/sql/schema_changer.go#L1347)):*
> ```Go
> 					}
> 					for k, ref := range ancestorIdx.InterleavedBy {
> 						if ref.Table == scDesc.ID && ref.Index == oldPrimaryIndex.ID {
> ```

We expect to find exactly one element where this is the case, right? Maybe worth asserting that. This would produce weird results if it found more than one.

Though now I see this is already what we do in DROP TABLE, so maybe it's ok...
___
*[pkg/sql/schema_changer.go, line 1273 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44075#-Lzbuth82hWxP64Bp_88:-Lzbuth82hWxP64Bp_89:bc74xum) ([raw file](https://github.com/cockroachdb/cockroach/blob/8be96915bc22586cd7199a2ddb4fc2426a83c6f4/pkg/sql/schema_changer.go#L1273)):*
> ```Go
> 					}
> 				}
> 				// Because we are not currently supporting primary key changes on tables/indexes that are interleaved
> ```

Nit: long line
___
*[pkg/sql/schema_changer.go, line 1342 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44075#-LzbuD-P016vzi1WLI6T:-LzbuD-P016vzi1WLI6U:bc74xum) ([raw file](https://github.com/cockroachdb/cockroach/blob/8be96915bc22586cd7199a2ddb4fc2426a83c6f4/pkg/sql/schema_changer.go#L1342)):*
> ```Go
> 				}
> 				// If any old index had an interleaved parent, remove the backreference from the parent.
> 				for _, idxID := range append([]sqlbase.IndexID{pkSwap.OldPrimaryIndexId}, pkSwap.OldIndexes...) {
> ```

Nit: long line

**Comment by rohany** [comment]
>We expect to find exactly one element where this is the case, right? Maybe worth asserting that. This would produce weird results if it found more than one.

We expect to find exactly one, but if it happened that there were multiple pointers from the parent to the child we'd want to remove them anyway.

**Comment by rohany** [comment]
wait waht just happened

**Comment by rohany** [comment]
turns out i'm small brain at rebasing.

**Comment by solongordon** [comment]
The current code doesn't work for the "more than one" case though, right? I think the indices would be screwed up after you remove the first one. That was my main concern.

**Comment by rohany** [comment]
Yeah, you're right. I can just drop an assertion into both places.

**Comment by rohany** [comment]
bors r=solongordon

**Pull request merged**
