### PR TITLE
kvserver: enqueue decom ranges at an interval behind a setting

### LINKED ISSUE #130085: server: add configurable decommission nudger
Its common that decommissions can take a long time or stall when there are repeated restarts or disruptions to the cluster.

Introduce a configurable decommission nudger, which will enqueue any ranges with replicas which should be decommissioned into the replicate queue.

Jira issue: CRDB-41870

Epic CRDB-37617

### PR DESCRIPTION
**Pull request by kvoli**
Introduce the `ranges.decommissioning` gauge metric, which represents
the number of ranges with at least one replica on a decommissioning
node.

The metric is reported by the leaseholder, or if there is no valid
leaseholder, the first live replica in the descriptor, similar to
(under|over)-replication metrics.

The metric can be used to approximately identify the distribution of
decommissioning work remaining across nodes, as the leaseholder replica
is responsible for triggering the replacement of decommissioning
replicas for its own range.

Informs: https://github.com/cockroachdb/cockroach/issues/130085
Release note (ops change): The `ranges.decommissioning` metric is added,
representing the number of ranges which have a replica on a
decommissioning node.

---

When `kv.enqueue_in_replicate_queue_on_problem.interval` is set to a
positive non-zero value, leaseholder replicas of ranges which are
underreplicated will be enqueued into the replicate queue every
`kv.enqueue_in_replicate_queue_on_problem.interval` interval.

When `kv.enqueue_in_replicate_queue_on_problem.interval` is set to 0,
no enqueueing on underreplication will take place, outside of the
regular replica scanner.

A recommended value for users enabling the enqueue (non-zero), is 15
minutes e.g.,

```
SET CLUSTER SETTING
kv.enqueue_in_replicate_queue_on_problem.interval='900s'
```

---

Resolves: https://github.com/cockroachdb/cockroach/issues/130085
Release note (ops change): The `ranges.decommissioning` metric is added,
representing the number of ranges which have a replica on a
decommissioning node.

### CODE REVIEW

**Review by arulajmani — APPROVED** [review]
:lgtm: Thanks for digging into this by the way!

The patch itself looks good to merge and backport, esp given it's default off. Do you see a world where we turn this default on and subsume the logic introduced in https://github.com/cockroachdb/cockroach/pull/80993 into `maybeEnqueueProblemRange`? It should be doable with a bit of tweaking, right?

Separately, it feels a bit unsatisfying that there's a bug lurking here somewhere which we haven't found. 

> Reviewed 5 of 5 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130117#-:-O62wuiTD_qxqcFIxcd3:b-31ehlu)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/replica.go` line 2581 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130117#-O62y0-dE0WHyerrmYNN:-O62y0-e9IN6LJartWcJ:bfsnb9o) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b6600c7b8e189b46990d7ff80d6ad628f70c1e2/pkg/kv/kvserver/replica.go#L2581)):*
> ```Go
> // NOT be called unless the range is known to require action e.g.,
> // decommissioning|underreplicated.
> func (r *Replica) maybeEnqueueProblemRange(
> ```

Do we want to add some commentary about the motivation for introducing this method and why it isn't needed in the bug free case (which will also explain to readers why it is default off)?

**Review by kvoli — COMMENTED** [review]
TYFTR!

> Do you see a world where we turn this default on and subsume the logic introduced in [#80993](https://reviewable.io/reviews/cockroachdb/cockroach/80993) into `maybeEnqueueProblemRange`? It should be doable with a bit of tweaking, right?

I do see a world where that occurs, probably on a new async task goroutine which iterates over every replica on the node at most every 30s-60s+ (adding a validator to the setting to prevent configuring less than that interval). 

> Separately, it feels a bit unsatisfying that there's a bug lurking here somewhere which we haven't found.

Indeed, I'd much rather we fix the bug than ship this patch realistically unless we can reproduce the problem ourselves that seems unlikely. I filed https://github.com/cockroachdb/cockroach/issues/130199 for tracking.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130117#-:-O63JhYvDlJR_DFC6cRG:b-pvi88o)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani)

___
*[`pkg/kv/kvserver/replica.go` line 2581 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130117#-O62y0-dE0WHyerrmYNN:-O63Kg6k5oJkOZ7l6wJs:b-ro38td) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b6600c7b8e189b46990d7ff80d6ad628f70c1e2/pkg/kv/kvserver/replica.go#L2581)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Do we want to add some commentary about the motivation for introducing this method and why it isn't needed in the bug free case (which will also explain to readers why it is default off)?
</blockquote></details>

Good idea, I've added it here and also filed the issue for the bug https://github.com/cockroachdb/cockroach/issues/130199.

**Comment by kvoli** [comment]
bors r=arulajmani

**Comment by kvoli** [comment]
> Encountered an error creating backports. Some common things that can go wrong:
> 1. The backport branch might have already existed.
> 2. There was a merge conflict.
> 3. The backport branch contained merge commits.
> 
> You might need to create your backport manually using the [backport](https://github.com/benesch/backport) tool.
> 
> ----
> 
> error creating merge commit from a98fe59c3a0201389975074f9f0e310659038843 to blathers/backport-release-23.1-130117: POST https://api.github.com/repos/cockroachdb/cockroach/merges: 409 Merge conflict []
> 
> you may need to manually resolve merge conflicts with the backport tool.
> 
> Backport to branch 23.1.x failed. See errors above.
> 
> ----
> 
> error creating merge commit from a98fe59c3a0201389975074f9f0e310659038843 to blathers/backport-release-23.2-130117: POST https://api.github.com/repos/cockroachdb/cockroach/merges: 409 Merge conflict []
> 
> you may need to manually resolve merge conflicts with the backport tool.
> 
> Backport to branch 23.2.x failed. See errors above.
> 
> ----
> 
> error creating merge commit from a98fe59c3a0201389975074f9f0e310659038843 to blathers/backport-release-24.1-130117: POST https://api.github.com/repos/cockroachdb/cockroach/merges: 409 Merge conflict []
> 
> you may need to manually resolve merge conflicts with the backport tool.
> 
> Backport to branch 24.1.x failed. See errors above.
> 
> ----
> 
> error creating merge commit from a98fe59c3a0201389975074f9f0e310659038843 to blathers/backport-release-24.2-130117: POST https://api.github.com/repos/cockroachdb/cockroach/merges: 409 Merge conflict []
> 
> you may need to manually resolve merge conflicts with the backport tool.
> 
> Backport to branch 24.2.x failed. See errors above.
> 
> ----
> 
> <sub>:owl: Hoot! I am a [Blathers](https://github.com/apps/blathers-crl), a bot for [CockroachDB](https://github.com/cockroachdb). My owner is [dev-inf](https://github.com/orgs/cockroachdb/teams/dev-inf).</sub>

This will be fun. I'll cherry-pick the commits onto the release branches and sort out the conflicts tomorrow.

**Pull request merged**
