### PR TITLE
Pin pgjdbc roachtest to REL42.2.9

### PR DESCRIPTION
**Pull request by apantel**
Release note: none

This passed running on my test cluster

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
thanks! do you think we should just do this for pgjdbc for now? if so, can you make another issue about pinning other tests, and making a way to bump the versions when we want to?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44937#-:-M-l5tKl3D0K12GmP1eX:b-ykwoqi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @apantel and @rafiss)

___
*[pkg/cmd/roachtest/pgjdbc.go, line 19 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44937#-M-l5dDFB5sFaUhjgLIR:-M-l5dDFB5sFaUhjgLIS:b-4ioedx) ([raw file](https://github.com/cockroachdb/cockroach/blob/6476ad328ddb04271ddfb2a4e776317efc8f6c48/pkg/cmd/roachtest/pgjdbc.go#L19)):*
> ```Go
> )
> 
> var pgjdbcReleaseTagRegex = regexp.MustCompile(`^REL(?P<major>\d+)\.(?P<minor>\d+)\.(?P<point>\d+)$`)
> ```

we should explain why we are not using this anymore -- and maybe come up with some way that we can easily bump the pgjdbc release when we want to

**Comment by apantel** [comment]
Yes, I think we should just pin this for now, and make a ticket to pin everything + figure out reporting version changes. I'll make the issue.

**Review by rafiss — APPROVED** [review]
sounds good!

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44937#-:-M-lZVo_0lVE-rActdGf:bp7vbfx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @apantel)

**Pull request merged**
