### PR TITLE
sqlsmith: improve vectorized checking

### PR DESCRIPTION
**Pull request by madelynnblue**

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41435)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mjibson)

___
*[pkg/internal/sqlsmith/sqlsmith_test.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41435#-LqgXUuW84jqIxCzFN0f:-LqgXUuW84jqIxCzFN0g:bz2ych7) ([raw file](https://github.com/cockroachdb/cockroach/blob/2327c6113743b0020438f86013cde86575819bf9/pkg/internal/sqlsmith/sqlsmith_test.go#L73)):*
> ```Go
> 	}
> 
> 	if *flagVec {
> ```

Why are we removing this?
___
*[pkg/internal/sqlsmith/sqlsmith_test.go, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41435#-LqgWjiO7sKc22K_pb0E:-LqgWjiO7sKc22K_pb0F:b2qax68) ([raw file](https://github.com/cockroachdb/cockroach/blob/5188eac960cb1642dbc2a5fe226c1eaecccc86ea/pkg/internal/sqlsmith/sqlsmith_test.go#L101)):*
> ```Go
> 					// false` similarly remove rows but are
> 					// harder to detect.
> 					"num_rows:0",
> ```

[nit]: I'd extract these error messages into a constant array of strings somewhere outside of the function (maybe under the `var` definition in the beginning of the file).

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41435)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/internal/sqlsmith/sqlsmith_test.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41435#-LqgXUuW84jqIxCzFN0f:-Lqgar326f7ZvqLX67Ia:be1uum9) ([raw file](https://github.com/cockroachdb/cockroach/blob/2327c6113743b0020438f86013cde86575819bf9/pkg/internal/sqlsmith/sqlsmith_test.go#L73)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Why are we removing this?
</blockquote></details>

Because it no longer is useful. It was used before as a way to detect non-vectorizable queries. Now we can do that optionally with the new check-vec flag.
___
*[pkg/internal/sqlsmith/sqlsmith_test.go, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41435#-LqgWjiO7sKc22K_pb0E:-Lqgb1t0DoSNSzArbcKj:b69pxhi) ([raw file](https://github.com/cockroachdb/cockroach/blob/5188eac960cb1642dbc2a5fe226c1eaecccc86ea/pkg/internal/sqlsmith/sqlsmith_test.go#L101)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: I'd extract these error messages into a constant array of strings somewhere outside of the function (maybe under the `var` definition in the beginning of the file).
</blockquote></details>

I...kinda like them here.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41435#-:-LqgX9d8Cbn7jwiuiH5c:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mjibson)

___
*[pkg/internal/sqlsmith/sqlsmith_test.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41435#-LqgXUuW84jqIxCzFN0f:-LqgblUG0PI4Hil5Fadw:bxtmqgl) ([raw file](https://github.com/cockroachdb/cockroach/blob/2327c6113743b0020438f86013cde86575819bf9/pkg/internal/sqlsmith/sqlsmith_test.go#L73)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Because it no longer is useful. It was used before as a way to detect non-vectorizable queries. Now we can do that optionally with the new check-vec flag.
</blockquote></details>

I see, thx.
___
*[pkg/internal/sqlsmith/sqlsmith_test.go, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41435#-LqgWjiO7sKc22K_pb0E:-LqgbqAIBMceb-kr73gg:b-va0mq2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5188eac960cb1642dbc2a5fe226c1eaecccc86ea/pkg/internal/sqlsmith/sqlsmith_test.go#L101)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

I...kinda like them here.
</blockquote></details>

Okay :)

**Pull request merged**
