### PR TITLE
build: break up big regex into multiple ones and write them down

### PR DESCRIPTION
**Pull request by yuzefovich**
Apparently, we are at the limit of the size of a regular expression
that sed can handle. Previously, we'd populate TYPES environment
variable and pass a lot of its contents (some 2000 characters) into
the regular expression to be executed by sed, but when I added another
type, the build failed. Now, for every type we write down a separate
regex and execute all of them in turn.

(We tried to write the regex with all types into a file and execute
it from there, but it didn't work, so my guess is that it wasn't a
buffering issue but the size of the regex.)

Release note: None

### CODE REVIEW

**Review by jordanlewis — APPROVED** [review]
LGTM - thanks for fixing this!

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by yuzefovich** [comment]
Seems like this PR was skipped by bors due to CLA issue. Cancelling and trying to merge it again.

bors r-

**Pull request merged**
