### PR TITLE
kv: pipeline replicated lock acquisition

### LINKED ISSUE #117978: kv: pipeline replicated lock acquisition
Replicated lock acquisition currently replicates through Raft synchronously. This can impose a high latency on read committed transactions which perform a large number of SELECT FOR UPDATE operations or a large number of FK lookups.

This was discussed in the Read Committed RFC under the [Row-Level Locks > Reliability and Enforcement](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20230122_read_committed_isolation.md#reliability-and-enforcement) section. That section also outlined a collection of [possible optimizations](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20230122_read_committed_isolation.md#alternative-replicate-locks) that we could make to avoid this latency penalty.

The most promising of the optimizations is to pipeline this lock acquisition using the using `AsyncConsensus` infrastructure. This will require client-side tracking and a new protocol to validate pipelined lock acquisition. It is analogous to our existing [write intent pipelining](https://www.cockroachlabs.com/blog/transaction-pipelining/) approach.

Jira issue: CRDB-35440

### PR DESCRIPTION
**Pull request by nvb**
Fixes #117978.

Builds upon the foundation laid in [#119975](https://github.com/cockroachdb/cockroach/pull/119975), [#119933](https://github.com/cockroachdb/cockroach/pull/119933), [#121065](https://github.com/cockroachdb/cockroach/pull/121065), and [#121086](https://github.com/cockroachdb/cockroach/pull/121086).

This commit completes the client-side handling of replicated lock acquisition pipelining. Replicated lock acquisition through `Get`, `Scan`, and `ReverseScan` requests now qualifies to be pipelined. The `txnPipeliner` is updated to track the strength associated with each in-flight write and pass that along to the corresponding `QueryIntentRequest`.

See [benchmark with TPC-C results here](https://github.com/cockroachdb/cockroach/pull/121088#issuecomment-2027848825).

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121088)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @nvanbenschoten)

___
*[`pkg/sql/row/kv_batch_fetcher.go` line 636 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/121088#-Nu4tZSk2EiE7B-FCHqG:-Nu4tZSk2EiE7B-FCHqH:bs8eudm) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fb68c84be3fbdaa6a5c9acb6b4ac6b4a5d4f857/pkg/sql/row/kv_batch_fetcher.go#L636)):*
> ```Go
> 	// alive.
> 	// TODO(nvanbenschoten): explain why this was needed.
> 	if f.lockDurability != lock.Replicated {
> ```

nit: it might be a good idea to apply a similar change to `txnKVStreamer.SetupNextFetch` and `buildResumeSingleRangeBatch` in `streamer.go` even if this is not needed at the moment (is it needed? we currently don't enable the streamer when non-default key locking is used - is this related?)

**Review by arulajmani — COMMENTED** [review]
Looks good. I can have another look once we've added tests for this PR before stamping.

> Reviewed 1 of 1 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121088#-:-Nu5XkY50hE4MuxTsJ27:bklnag4)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go` line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/121088#-Nu5N0icAFxDgkCocBpu:-Nu5N0icAFxDgkCocBpv:b-l7zx8e) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fb68c84be3fbdaa6a5c9acb6b4ac6b4a5d4f857/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go#L45)):*
> ```Go
> )
> 
> var pipelinedRangedWritesEnabled = settings.RegisterBoolSetting(
> ```

Should we make these settings public so that there's documentation for them?
___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go` line 549 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/121088#-Nu5RF2X0I_3_AwegBPM:-Nu5RF2X0I_3_AwegBPN:b-xar784) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fb68c84be3fbdaa6a5c9acb6b4ac6b4a5d4f857/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go#L549)):*
> ```Go
> 		// writes that a ranged request will add. To our in-flight writes set. And
> 		// once we perform async consensus, we can't merge them away until we prove
> 		// that they have succeeded. What should we do?
> ```

Nice find! Do you think it's okay to let our lock tracking potentially exceed `maxTrackingBytes` in such cases, as long as we have added observability to react? 

Concretely, I was thinking we could add metrics/logs on the response path whenever tracking pipelined locks for a ranged request causes us to go over budget. If imprecisely predicting the memory usage for ranged requests ever becomes a problem, we can always reach for the cluster settings that disable lock pipelining for `DeleteRange`/locking `{,Reverse}Scan` requests.

Separately, I'm not sure what (if anything) we can do to better estimate how much our in-flight write set will grow by. I was looking at `TargetBytes` which are set on `{,Reverse}Scan` requests, but those include both the key and value portion.
___
*[`pkg/kv/kvserver/txnrecovery/manager.go` line 210 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/121088#-Nu5Wm_5Bh2LOFevynUs:-Nu5Wm_5Bh2LOFevynUt:b-6wkvzo) ([raw file](https://github.com/cockroachdb/cockroach/blob/2db94e4d973362064f5756c35ce695fe913899c6/pkg/kv/kvserver/txnrecovery/manager.go#L210)):*
> ```Go
> 			},
> 			Txn: meta,
> 			// TODO(nvanbenschoten): pass in the correct lock strength here.
> ```

This didn't last too long! :fire:

**Comment by nvanbenschoten** [comment]
### Summary

For a multi-region cluster running TPC-C under Read Committed, this change provides a 75% speedup for the `delivery` transaction and a 38% speedup the `newOrder` transaction. 

For a single-region cluster running TPC-C under Read Committed, this change provides a 32% speedup for the `delivery` transaction, a 21% speedup for the `newOrder` transaction, and a 13% speedup for the `payment` transaction.

-----

### Impact on multi-region TPC-C

This change will be most impactful for clusters that with cross-region synchronous replication, where each round of raft takes O(10ms). We can see a significant improvement in multi-region clusters on Read Committed workloads that use SELECT FOR UPDATE and/or perform foreign key checks.

The following performance summary comes from a modified version of the `tpcc/headroom/isolation-level=read-committed/n4cpu16` roachtest which replicates across three regions, uses region survivability, and pins all leases to the region with the workload. Of note are the p50 latencies for the `delivery`, `newOrder`, and `payment` transactions.

**Before**
```
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
 7200.0s        0         131480           18.3    381.5    385.9    402.7    419.4   1208.0  delivery

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
 7200.0s        0        1315851          182.8    172.6    176.2    184.5    226.5    738.2  newOrder

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
 7200.0s        0         131514           18.3      4.1      4.1      5.2      6.6    226.5  orderStatus

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
 7200.0s        0        1315369          182.7     71.7     71.3     79.7    142.6    671.1  payment

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
 7200.0s        0         131600           18.3      9.9      8.9     13.1     41.9    218.1  stockLevel
```

**After**
```
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
 7200.0s        0         131705           18.3     92.1     96.5    100.7    113.2    369.1  delivery

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
 7200.0s        0        1318307          183.1    109.4    109.1    113.2    159.4    486.5  newOrder

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
 7200.0s        0         131764           18.3      4.5      4.7      6.0      7.1    184.5  orderStatus

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
 7200.0s        0        1318058          183.1     72.0     71.3     75.5    134.2    469.8  payment

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
 7200.0s        0         131696           18.3     10.1      9.4     13.1     37.7    234.9  stockLevel
```

`delivery` performs 10 sequential single-row SELECT FOR UPDATE statements (`selectNewOrder`), so pipelining this replicated lock acquisition is a big deal. With this change, its p50 latency from **385.9ms** to **96.5ms**, a **75%** improvement.

`newOrder` performs 1 multi-row SELECT FOR UPDATE statement (`selectStock`). It also performs 4 foreign key checks (1x in `insertOrder`, 1x in `insertNewOrder`, 2x in `insertOrderLine`). With this change, its p50 latency from **176.2ms** to **109.1ms**, a **38%** improvement.

`payment` performs performs 2 foreign key checks (2x in `insertHistory`). We don't see a meaningful improvement for this test case, but do see one below.


### Impact on single-region TPC-C

This change will be most impactful for clusters that with cross-region replication. However, we do see an improvement in single-region clusters on Read Committed workloads that use SELECT FOR UPDATE and/or perform foreign key checks. This is because pipelining allows the disk writes for replicated locks to be parallelized.

The following performance summary comes from the `tpcc/headroom/isolation-level=read-committed/n4cpu16` roachtest. Of note are the p50 latencies for the `delivery`, `newOrder`, and `payment` transactions.

**Before**
```
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
 7200.0s        0         132250           18.4     57.9     58.7     71.3     83.9    436.2  delivery

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
 7200.0s        0        1322298          183.7     25.5     25.2     31.5     41.9    318.8  newOrder

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
 7200.0s        0         132210           18.4      5.4      5.5      7.1      8.4    192.9  orderStatus

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
 7200.0s        0        1321391          183.5     12.5     12.6     15.7     22.0    251.7  payment

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
 7200.0s        0         132120           18.3     10.9     11.0     15.2     19.9     75.5  stockLevel
```

**After**
```
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
 7200.0s        0         132228           18.4     38.9     39.8     48.2     54.5    251.7  delivery

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
 7200.0s        0        1322691          183.7     20.0     19.9     24.1     29.4    218.1  newOrder

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
 7200.0s        0         132230           18.4      4.8      5.0      6.3      7.3    104.9  orderStatus

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
 7200.0s        0        1321782          183.6     11.0     11.0     13.6     16.8    209.7  payment

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
 7200.0s        0         132061           18.3     10.0     10.0     14.2     17.8     54.5  stockLevel
```

With this change, the `delivery` transaction's p50 latency drops from **58.7ms** to **39.8ms**, a **32%** speedup.

With this change, the `newOrder` transaction's p50 latency drops from **25.2ms** to **19.9ms**, a **21%** speedup.

With this change, the `payment` transaction's p50 latency drops from **12.6ms** to **11.0ms**, a **13%** speedup.

**Review by nvb — COMMENTED** [review]
> I can have another look once we've added tests for this PR before stamping.

The testing should all be here now. I think we will want a few end-to-end tests around parallel commits as sanity checks, but these can come in a later PR. So this should be good for a full review.

I also found that our hypothesis about savepoint rollbacks not playing well with non-intent locks was correct — we'll want to land https://github.com/cockroachdb/cockroach/pull/121458 as well.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121088#-:-NuPmaIyDSqCvvszF2fh:b3sr2wc)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @yuzefovich)

___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go` line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/121088#-Nu5N0icAFxDgkCocBpu:-NuPjnkwACorQ0SMouYm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fb68c84be3fbdaa6a5c9acb6b4ac6b4a5d4f857/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go#L45)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Should we make these settings public so that there's documentation for them?
</blockquote></details>

Done.
___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go` line 549 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/121088#-Nu5RF2X0I_3_AwegBPM:-NuPk0V6AL9s-mmFq3dA:b-dtuu4e) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fb68c84be3fbdaa6a5c9acb6b4ac6b4a5d4f857/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go#L549)):*
> Do you think it's okay to let our lock tracking potentially exceed `maxTrackingBytes` in such cases, as long as we have added observability to react?

> Concretely, I was thinking we could add metrics/logs on the response path whenever tracking pipelined locks for a ranged request causes us to go over budget. If imprecisely predicting the memory usage for ranged requests ever becomes a problem, we can always reach for the cluster settings that disable lock pipelining for `DeleteRange`/locking `{,Reverse}Scan` requests.

This all sounds reasonable to me. I opened https://github.com/cockroachdb/cockroach/issues/121471 to track this.

> I'm not sure what (if anything) we can do to better estimate how much our in-flight write set will grow by. I was looking at `TargetBytes` which are set on `{,Reverse}Scan` requests, but those include both the key and value portion.

I don't think we can do anything better without server-side changes to dynamically decide whether to respect `AsyncConsensus` or not. And then to communicate this back to the client. Given the conversations we've had about the key and byte limits already in place, the escape hatches we have with the cluster setting, and some manual testing I ran on Friday, I'm ok with deferring this until we see it become a problem.
___
*[`pkg/sql/row/kv_batch_fetcher.go` line 636 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/121088#-Nu4tZSk2EiE7B-FCHqG:-NuPlawd4jZxBm7CCw43:b-4ak70w) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fb68c84be3fbdaa6a5c9acb6b4ac6b4a5d4f857/pkg/sql/row/kv_batch_fetcher.go#L636)):*
> is it needed? we currently don't enable the streamer when non-default key locking is used - is this related

If we don't enable the streamer when non-default key locking is used, then this is not needed. It's only needed when `lockDurability` == `lock.Replicated`. I'll add an assertion in `Streamer` so that we catch this if/when we decide to use it for locking reads.

**Review by arulajmani — APPROVED** [review]
:lgtm: 

It's nice to see these benchmark numbers :fire: 

> Reviewed 13 of 13 files at r7, 1 of 1 files at r8, 11 of 13 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121088#-:-NuZAPojAqec8Ms6Gv8a:b-mf8i2x)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @yuzefovich)

___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go` line 549 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/121088#-Nu5RF2X0I_3_AwegBPM:-NuZ4Cbj5WvykxpZC3WW:b-iyx1od) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fb68c84be3fbdaa6a5c9acb6b4ac6b4a5d4f857/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go#L549)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> Do you think it's okay to let our lock tracking potentially exceed `maxTrackingBytes` in such cases, as long as we have added observability to react?

> Concretely, I was thinking we could add metrics/logs on the response path whenever tracking pipelined locks for a ranged request causes us to go over budget. If imprecisely predicting the memory usage for ranged requests ever becomes a problem, we can always reach for the cluster settings that disable lock pipelining for `DeleteRange`/locking `{,Reverse}Scan` requests.

This all sounds reasonable to me. I opened https://github.com/cockroachdb/cockroach/issues/121471 to track this.

> I'm not sure what (if anything) we can do to better estimate how much our in-flight write set will grow by. I was looking at `TargetBytes` which are set on `{,Reverse}Scan` requests, but those include both the key and value portion.

I don't think we can do anything better without server-side changes to dynamically decide whether to respect `AsyncConsensus` or not. And then to communicate this back to the client. Given the conversations we've had about the key and byte limits already in place, the escape hatches we have with the cluster setting, and some manual testing I ran on Friday, I'm ok with deferring this until we see it become a problem.
</blockquote></details>

All this sounds good to me. Thanks for opening the issue!
___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go` line 614 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/121088#-NuZ4H9a4BIyc3DeSVN7:-NuZ4H9a4BIyc3DeSVN8:b-hhchjz) ([raw file](https://github.com/cockroachdb/cockroach/blob/dec4830045fd1d6d9daf857d78d2c8509f8640ee/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go#L614)):*
> ```Go
> 						Txn:      meta,
> 						Strength: w.Strength,
> 						// TODO: test, maybe extend TestTxnPipelinerSavepoints
> ```

Did you want to add your name to the TODO before merging? or were you meaning to address this before the PR merges?
___
*[`pkg/sql/row/kv_batch_fetcher.go` line 635 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/121088#-NuZ4wtHAdagTeZUYqaA:-NuZ4wtHAdagTeZUYqaB:b-9g3pu7) ([raw file](https://github.com/cockroachdb/cockroach/blob/dec4830045fd1d6d9daf857d78d2c8509f8640ee/pkg/sql/row/kv_batch_fetcher.go#L635)):*
> ```Go
> 	// the underlying Get and Scan requests which could keep large byte slices
> 	// alive.
> 	// However, we do not re-use the requests slice if we're using the replicated
> ```

nit: new line before the new paragraph? :joy: 
___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner_test.go` line 679 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/121088#-NuZ7gE-64W9bcHqaQKm:-NuZ7gE-64W9bcHqaQKn:bgbt9sx) ([raw file](https://github.com/cockroachdb/cockroach/blob/dec4830045fd1d6d9daf857d78d2c8509f8640ee/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner_test.go#L679)):*
> ```Go
> 	require.Equal(t, expIfWrites, ifWrites)
> 
> 	// Replicated locking read before write. Some existing in-flight replicated
> ```

Should we also add a ranged request here as well? Concretely, I was thinking we could lock more keys above and add a `ScanRequest` that partially overlaps with some of the newly locked keys.

EDIT: I see you already have a `ScanRequest` below; feel free to disregard.

**Review by nvb — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121088#-:-NuZ_NBw9FP_JTGsltuZ:b-tlx7ko)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani and @yuzefovich)

___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go` line 614 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/121088#-NuZ4H9a4BIyc3DeSVN7:-NuZG58T33ufKWaDeIr_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dec4830045fd1d6d9daf857d78d2c8509f8640ee/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go#L614)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Did you want to add your name to the TODO before merging? or were you meaning to address this before the PR merges?
</blockquote></details>

Done.
___
*[`pkg/sql/row/kv_batch_fetcher.go` line 635 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/121088#-NuZ4wtHAdagTeZUYqaA:-NuZDKNa6X3CSsIhqndz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dec4830045fd1d6d9daf857d78d2c8509f8640ee/pkg/sql/row/kv_batch_fetcher.go#L635)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: new line before the new paragraph? :joy:
</blockquote></details>

Done.
___
*[`pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner_test.go` line 679 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/121088#-NuZ7gE-64W9bcHqaQKm:-NuZDsbC11gkwaOw8L0K:bfal11a) ([raw file](https://github.com/cockroachdb/cockroach/blob/dec4830045fd1d6d9daf857d78d2c8509f8640ee/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner_test.go#L679)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Should we also add a ranged request here as well? Concretely, I was thinking we could lock more keys above and add a `ScanRequest` that partially overlaps with some of the newly locked keys.

EDIT: I see you already have a `ScanRequest` below; feel free to disregard.
</blockquote></details>

I'll disregard then :smiley:

**Comment by nvanbenschoten** [comment]
blathers backport release-24.1

**Comment by nvanbenschoten** [comment]
blathers backport release-24.1

**Pull request merged**
