### PR TITLE
sql: Add assertions for {Unary,Binary,Func}Expr return types

### LINKED ISSUE #20465: sql: Ensure functions return the Datum specified in the return signature
A recent panic was caused by a built-in function returning a datum type that did not match the built-in signature. From brief testing, this discrepancy appears to work in very basic queries when running in the local execution engine, but will cause panics in the distributed execution engine when streaming rows.

See #20464 for the specific panic that came up.

One preventative solution would be to make builtins check datums being returned during logictests, making sure they match the type signature (before casts). cc: @knz as you're probably interested in these testing improvements. An extension of this can also test all other operators, not just built-ins.

Alternatively, this may be a specific problem with the distSQL streamers where the types should be properly handled. I'm not knowledgeable in this, so I'd love some input. While returning an error instead of panic-ing would be nice, implicitly casting does not seem like the way to go.

### PR DESCRIPTION
**Pull request by lgo**
Assertions were added to BinaryExpr, UnaryExpr, and FuncExpr evaluation
to ensure that the returned datum type matches the declared expression
return type. If this assertion is violated, the datum that mismatches
the type annotations will continue to be used but may cause subtle or
unexpected bugs.

For example, local execution worked correctly in a basic query with
this problem, but distSQL would always panic if a FuncExpr returned
datum did not match the type annotation. (#20465)

Closes #20465.

Fix return type signature of JSON #>> operator and array_positions.
The following type signatures were changed

    JSON #>> STRING[] now returns a STRING (previously JSON)

    array_positions(<TYPE>[], <TYPE>) now returns a INT[] (previously
        <TYPE>[])

Release note (bug fix): Fixed the return type signature of JSON #>>
operator.

Release note (bug fix): Fixed the return type signature of the
array_positions built-in funtion.

Release note: none

### CODE REVIEW

**Comment by lego** [comment]
Agh, I thought this would have worked but it didn't fail in a known bad case. I don't think the assertions are actually working. (This is going back to WIP, sorry!)

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/sem/tree/eval.go, line 3052 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20524#-L-h4Dq46UQnXva9xCI6:-L-h4Dq46UQnXva9xCI7:bvj6x8b) ([raw file](https://github.com/cockroachdb/cockroach/blob/653ddf6e4a11e62f8bf99b257189098741a0ad35/pkg/sql/sem/tree/eval.go#L3052)):*
> ```Go
> 	}
> 	res, err := expr.fn.fn(ctx, d)
> 	// FIXME(joey): Add test knob condition.
> ```

@knz would it be appropriate to plumb test knobs via. `EvalContext`? There are currently no testing knobs on it. I wanted to get your thoughts on that or a suggestion for the best way to plumb knobs into here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20524#-:-L-h4XrQudBp_GmMNase:btt8rcy)*

**Comment by lego** [comment]
Nevermind, I was testing the wrong branch by accident. Good news: the assertion does work. Bad news: the existing logic tests don't catch the known bad `date_trunc`. Either the tests aren't exhaustive enough, or they aren't sufficing if they don't do a storage round trip. I believe it's the former.

**Comment by knz** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/sem/tree/eval.go, line 2170 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20524#-L-ldMrhgDfD9pY1LO12:-L-ldMrhgDfD9pY1LO13:b-pb9t6d) ([raw file](https://github.com/cockroachdb/cockroach/blob/653ddf6e4a11e62f8bf99b257189098741a0ad35/pkg/sql/sem/tree/eval.go#L2170)):*
> ```Go
> 	if true {
> 		if err := ensureExpectedType(expr.fn.ReturnType, res); err != nil {
> 			panic(fmt.Sprintf("binary op %q: %s", expr.String(), err))
> ```

make it return via `errors.Wrapf` instead of panic

---

*[pkg/sql/sem/tree/eval.go, line 2930 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20524#-L-ld3g0GMGNs7oXJbgM:-L-ld3g19yqUvcvwZeh2:bt7mcnj) ([raw file](https://github.com/cockroachdb/cockroach/blob/653ddf6e4a11e62f8bf99b257189098741a0ad35/pkg/sql/sem/tree/eval.go#L2930)):*
> ```Go
> 
> func ensureExpectedType(exp types.T, d Datum) error {
> 	if !exp.Equivalent(types.Any) && !d.ResolvedType().Equivalent(exp) {
> ```

`Equivalent` on all `types.T` instances already handles `Any`

---

*[pkg/sql/sem/tree/eval.go, line 3052 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20524#-L-h4Dq46UQnXva9xCI6:-L-ldIqp3F0a31Rj0DEB:b-uvypgu) ([raw file](https://github.com/cockroachdb/cockroach/blob/653ddf6e4a11e62f8bf99b257189098741a0ad35/pkg/sql/sem/tree/eval.go#L3052)):*
<details><summary><i>Previously, lego (Joey Pereira) wrote…</i></summary><blockquote>

@knz would it be appropriate to plumb test knobs via. `EvalContext`? There are currently no testing knobs on it. I wanted to get your thoughts on that or a suggestion for the best way to plumb knobs into here.
</blockquote></details>

Yes it is a good idea.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20524)*

**Comment by lego** [comment]
Some type failures caught by this:

```
	test_log_scope.go:61: use -show-logs to present logs inline
    --- FAIL: TestLogic/default (0.10s)
        --- FAIL: TestLogic/default/json (0.16s)
        	logic_test.go:1955:
        		testdata/logic_test/json:312: SELECT '{"a": 1}'::JSONB#>>'{a}'::STRING[]
        		expected success, but found
        		pq: binary op "'{\"a\":1}'#>>ARRAY['a']": expected return type "jsonb", got: "string"
        	logic_test.go:1976: testdata/logic_test/json:317: too many errors encountered, skipping the rest of the input
        --- FAIL: TestLogic/default/array (0.55s)
        	logic_test.go:1955:
        		testdata/logic_test/array:981: SELECT ARRAY_POSITIONS(ARRAY['A','A','B','A'], 'A'), ARRAY_POSITIONS(ARRAY['A','A','B','A'], 'C')
        		expected success, but found
        		pq: function "array_positions(ARRAY['A','A','B','A'], 'A')": expected return type "string[]", got: "int[]"
        	logic_test.go:1976: testdata/logic_test/array:986: too many errors encountered, skipping the rest of the input
```

@justinj you're familiar with both arrays and json, correct? Do you know what the right way to handle these are?

i.e. the signatures of operations mismatch the output datum type, which may cause issues.

---

Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/sql/sem/tree/eval.go, line 2170 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20524#-L-ldMrhgDfD9pY1LO12:-L-mXDFJpFNWaUNiRSHw:b-33qa7e) ([raw file](https://github.com/cockroachdb/cockroach/blob/653ddf6e4a11e62f8bf99b257189098741a0ad35/pkg/sql/sem/tree/eval.go#L2170)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

make it return via `errors.Wrapf` instead of panic
</blockquote></details>

Done. This now also returns an error instead of calling panic.

---

*[pkg/sql/sem/tree/eval.go, line 2930 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20524#-L-ld3g0GMGNs7oXJbgM:-L-mXRnROobArA-uPX8v:b-94jsne) ([raw file](https://github.com/cockroachdb/cockroach/blob/653ddf6e4a11e62f8bf99b257189098741a0ad35/pkg/sql/sem/tree/eval.go#L2930)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`Equivalent` on all `types.T` instances already handles `Any`
</blockquote></details>

So this is not true for a few `types.T`. In particular, `TTable` and `TTuple`. I'm not familiar with these types so I don't know what is appropriate here. There are cases where those are returned with an `types.Any` signature. I also had to check a test for `types.Null`, because some types are not equivalent to it.

---

*[pkg/sql/sem/tree/eval.go, line 3052 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20524#-L-h4Dq46UQnXva9xCI6:-L-mXG2kKI0sylC1mf0h:b-1tuzcq) ([raw file](https://github.com/cockroachdb/cockroach/blob/653ddf6e4a11e62f8bf99b257189098741a0ad35/pkg/sql/sem/tree/eval.go#L3052)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Yes it is a good idea.
</blockquote></details>

Done in a first commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20524#-:-L-m_-YBOe9D7FoOcZ0x:b-gefpda)*

**Comment by justinj** [comment]
Yes, the stated signatures of both of those functions are wrong, good catch! Feel free to change them here if you need them to pass for your change, or I can do it if you'd prefer.

**Comment by lego** [comment]
@justinj did those changes here, as they are needed to pass the tests. PTAL. Thanks! :)

**Comment by justinj** [comment]
Oh sorry I didn't re-review! This LGTM!

**Comment by lego** [comment]
NP. TYFRs!

**Pull request merged**
