### PR TITLE
sqlsmith: improve vec for bin exprs and distinct

### PR DESCRIPTION
**Pull request by madelynnblue**

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40314)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mjibson and @rafiss)

___
*[pkg/internal/sqlsmith/relational.go, line 499 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40314#-LnPkTgdE6mC6y9mAMgJ:-LnPkTge7xGzSKh85vlU:b-jg25ju) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f57d6638ddebb77e8169404c78886c8f61780d6/pkg/internal/sqlsmith/relational.go#L499)):*
> ```Go
> 	clause.Exprs = selectList
> 
> 	if !s.schema.vectorizable && s.d100() == 1 {
> ```

What's the reason for this change?
___
*[pkg/internal/sqlsmith/scalar.go, line 383 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40314#-LnPk6e-3mUrE-KOG5LG:-LnPk6e-3mUrE-KOG5LH:bypofrh) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f57d6638ddebb77e8169404c78886c8f61780d6/pkg/internal/sqlsmith/scalar.go#L383)):*
> ```Go
> 	}
> 	if s.schema.vectorizable {
> 		// TODO(mjibson): Improve this when #39189 is fixed.
> ```

I think #39189 is fixed now.

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40314)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @yuzefovich)

___
*[pkg/internal/sqlsmith/relational.go, line 499 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40314#-LnPkTgdE6mC6y9mAMgJ:-LnQr8FWBWHTdHNaEBb2:b-pp04kk) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f57d6638ddebb77e8169404c78886c8f61780d6/pkg/internal/sqlsmith/relational.go#L499)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

What's the reason for this change?
</blockquote></details>

vec often errors on queries with DISTINCT. It might support some, but for now it gets removed.
___
*[pkg/internal/sqlsmith/scalar.go, line 383 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40314#-LnPk6e-3mUrE-KOG5LG:-LnQuNNLCb5Oqoa_FPr9:b3zdecw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f57d6638ddebb77e8169404c78886c8f61780d6/pkg/internal/sqlsmith/scalar.go#L383)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think #39189 is fixed now.
</blockquote></details>

Ah! Simplified. Thanks.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40314)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mjibson and @yuzefovich)

___
*[pkg/internal/sqlsmith/scalar.go, line 365 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40314#-LnSrfj12VgGooTpaCEZ:-LnSrfj12VgGooTpaCE_:bo4iv11) ([raw file](https://github.com/cockroachdb/cockroach/blob/aecd192903e6dbb5d1f5759970caebaa0996c316/pkg/internal/sqlsmith/scalar.go#L365)):*
> ```Go
> 	tree.Minus: true,
> 	tree.Mult:  true,
> 	tree.Div:   true,
> ```

it could be useful to include the other binops in this map (and map them to false). even better, could they be added programmatically? that way when support is added, it might be easier to switch it on here.

by the way, https://github.com/cockroachdb/cockroach/issues/40312 is one issue to add support for more binops, so that could be referenced with a todo here.

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40314)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @yuzefovich)

___
*[pkg/internal/sqlsmith/scalar.go, line 365 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40314#-LnSrfj12VgGooTpaCEZ:-LnVs-2sCYug6aWTGFjr:b-n1hocu) ([raw file](https://github.com/cockroachdb/cockroach/blob/aecd192903e6dbb5d1f5759970caebaa0996c316/pkg/internal/sqlsmith/scalar.go#L365)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

it could be useful to include the other binops in this map (and map them to false). even better, could they be added programmatically? that way when support is added, it might be easier to switch it on here.

by the way, https://github.com/cockroachdb/cockroach/issues/40312 is one issue to add support for more binops, so that could be referenced with a todo here.


</blockquote></details>

I would love to be able to automate both this and the cmp ops. Is there an exported variable or function I can call in the exec stuff that has this information up to date?

**Review by rafiss — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40314)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mjibson and @yuzefovich)

___
*[pkg/internal/sqlsmith/scalar.go, line 365 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40314#-LnSrfj12VgGooTpaCEZ:-LnXv2sE40vc0pbUePTu:bq03r0i) ([raw file](https://github.com/cockroachdb/cockroach/blob/aecd192903e6dbb5d1f5759970caebaa0996c316/pkg/internal/sqlsmith/scalar.go#L365)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

I would love to be able to automate both this and the cmp ops. Is there an exported variable or function I can call in the exec stuff that has this information up to date?
</blockquote></details>

i'm not sure of the best way to export it.. it is in overloads.go, but that is in the `main` package of our execgen CLI tool, and i'm guessing sqlsmith should not depend on that? i can try to ask others on the team if there would be a better place to put that. but no need to block this PR on it

what i was thinking of for this specific case though was just

```
for op := tree.Bitand; op < tree.NumBinaryOperators; op++ {
  vecBinOps[op] = false
}
```

although now i remember that go maps will default to returning the zero value already, so this suggestion is not actually that helpful.

**Pull request merged**
