### PR TITLE
sql: add `StmtPosInTxn` to CommonSQLExecDetails

### PR DESCRIPTION
**Pull request by xinhaoz**
This commit adds the `StmtPosInTxn` field to the `CommonSQLExecDetails` event. `StmtPosInTxn` represents the stmt's index in the transaction, starting at 1.

Epic: none

Release note (sql change): In `CommonSQLExecDetails`, which is emitted as part of the sql audit logs, sql exec logs and telemetry events, there is a new field:
- `StmtPosInTxn`: represents the stmt's index in the transaction, starting at 1.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107081)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rharding6373 and @xinhaoz)

___
*[`pkg/util/log/eventpb/sql_audit_events.proto` line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107081#-N_jwv8d5GNuyEaYdLOP:-N_jwv8d5GNuyEaYdLOQ:b-jf9y54) ([raw file](https://github.com/cockroachdb/cockroach/blob/522fbcf7ff551412cd7ec8284309683fdc8010a6/pkg/util/log/eventpb/sql_audit_events.proto#L49)):*
> ```proto
>   uint64 bulk_job_id = 10 [(gogoproto.jsontag) = ",omitempty"];
>  // The statement's index in the transaction, starting at 1.
>   uint32 stmt_count = 11 [(gogoproto.jsontag) = ",omitempty"];
> ```

For consistency with `txn_counter` just above, why not `stmt_counter_in_txn`?

**Review by rharding6373 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107081)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @xinhaoz)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107081#-N_kWNR7EtiTpHRumDCv):*
High level comment:  When I read`stmtCount`, I immediate think this is going to refer to something like the number of statements in a transaction, as opposed to the statement's position in the transaction. Consider renaming this to `stmtIdx` or `stmtPos` or similar so it's more intuitive.

**Review by j82w — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107081)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @rharding6373, and @xinhaoz)

___
*[`pkg/util/log/eventpb/sql_audit_events.proto` line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107081#-N_jwv8d5GNuyEaYdLOP:-N_nbor631258MEXDBiP:bz74wmb) ([raw file](https://github.com/cockroachdb/cockroach/blob/522fbcf7ff551412cd7ec8284309683fdc8010a6/pkg/util/log/eventpb/sql_audit_events.proto#L49)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

For consistency with `txn_counter` just above, why not `stmt_counter_in_txn`?
</blockquote></details>

What about `stmt_pos_in_txn` ?

**Comment by xinhaoz** [comment]
Thanks for the feedback, all! I've renamed to `StmtPosInTxn` for clarity. LMK If you have any concerns with this.

**Review by j82w — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107081#-:-N_nybWy6DIFa8F1G_3m:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz, @rharding6373, and @xinhaoz)

**Review by maryliag — APPROVED** [review]
small nit, otherwise :lgtm: 

> Reviewed 3 of 8 files at r1, 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107081#-:-N_ulB1U91-4gKwbTEO8:bwg40qh)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @j82w, @knz, @rharding6373, and @xinhaoz)

___
*[`pkg/sql/exec_log.go` line 124 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107081#-N_ukmGy4A-bRgl3_tXW:-N_ukmGy4A-bRgl3_tXX:bx7v4qe) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b12b7231bf2ffd35b9e46202267536ef55d9c1b/pkg/sql/exec_log.go#L124)):*
> ```Go
> 	execType executorType,
> 	isCopy bool,
> 	numRetries, txnCounter, rows, stmtCount int,
> ```

nit: use `StmtPosInTxn` here (and the other ones below) to keep it consistent

**Comment by xinhaoz** [comment]
TFTR!
bors r+

**Comment by xinhaoz** [comment]
backport 23.1

**Comment by xinhaoz** [comment]
blathers backport 23.1

**Pull request merged**
