### PR TITLE
kvserver: remove redundant Tracer from RaftTransport

### PR DESCRIPTION
**Pull request by pav-kv**
All the call sites of `NewRaftTransport` take the `Tracer` from the `AmbientContext`
which is also passed in. This PR removes `Tracer` from the argument list, and the
duplicate `tracer` stored in the struct.

Release note: None

### CODE REVIEW

**Review by erikgrinaker — COMMENTED** [review]
Seems fine to me, but @andreimatei may have opinions on this.

**Comment by pavelkalinnikov** [comment]
Possibly contradicts #74291. @knz What's your take on this? Is putting out the tracer still the plan?

**Review by andreimatei — COMMENTED** [review]
Putting the `Tracer` explicitly in the `RaftTransport` was on purpose - you can see some discussion on the recent PR that introduced it. Coupling the `Tracer` with the `AmbientCtx` was, in my opinion, a mistake. Where it's feasible to plumb it explicitly, we should do so.
It's possible that in the future we'll plumb the `Tracer` through the `ctx` to some users.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85733#-:-N8yCuH-Db-j88WCwDi_:b-8v7uad)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

**Comment by pavelkalinnikov** [comment]
Reverting this.

**Pull request closed without merging**
