### PR TITLE
storage: make requiresExpiringLease a function, not a constant

### LINKED ISSUE #12353: storage: Replica.requiresExpiringLease initialized too early
`Replica.requiresExpiringLeases` is initialized in `Replica.initLocked` which often does not have the range descriptor. In particular, any replica which is created after the store is initialized. Thus `desc.StartKey.Less(roachpb.RKey(keys.NodeLivenessKeyMax))` will be set to true incorrectly. I think we need to set `requiresExpiringLeases` in `Replica.setDescWithoutProcessUpdate` or change the field to a method.

Noticed via this graph on `delta` which showed an unexpected number of expiration-based leases:

screen shot 2016-12-14 at 3 40 20 pm

### PR DESCRIPTION
**Pull request by spencerkimball**
There are pathways through the code which result in the replica's
descriptor not being known when `Replica.initLocked` is invoked.
There's not much cost to computing this, so just moving it to a
function instead.

Fixes #12353

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12354)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/storage/replica_range_lease.go, line 376 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12354#-KYz8JI8Snc6kbU688It:-KYz8JI8Snc6kbU688Iu:bxtuin8) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a1251bc34298a45b59d667017f71713ee70911/pkg/storage/replica_range_lease.go#L376)):*
> ```Go
> func (r *Replica) requiresExpiringLease() bool {
> 	return r.store.cfg.NodeLiveness == nil || !r.store.cfg.EnableEpochRangeLeases ||
> 		r.mu.state.Desc.StartKey.Less(roachpb.RKey(keys.NodeLivenessKeyMax))
> ```

Accessing `r.mu.state.Desc` isn't safe. Sometimes you're holding `Replica.mu` but sometimes you're not. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12354)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/storage/replica_range_lease.go, line 371 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12354#-KYzBa32vv3dA6D6EPYC:-KYzBa32vv3dA6D6EPYD:b-jxxcgv) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a1251bc34298a45b59d667017f71713ee70911/pkg/storage/replica_range_lease.go#L371)):*
> ```Go
> 
> // requiresExpiringLease returns whether this range uses an
> // expiration-based lease; false if epoch-based. Ranges located before
> ```

"located at the ... table" is odd. how about "ranges whose start keys are not greater than the node liveness prefix"

---

*[pkg/storage/replica_range_lease.go, line 376 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12354#-KYz8JI8Snc6kbU688It:-KYzBOIfRVowyqQDcLhQ:b-t6v4ez) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a1251bc34298a45b59d667017f71713ee70911/pkg/storage/replica_range_lease.go#L376)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Accessing `r.mu.state.Desc` isn't safe. Sometimes you're holding `Replica.mu` but sometimes you're not. 
</blockquote></details>

You could use r.mu.AssertHeld here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12354)*

**Comment by spencerkimball** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/storage/replica_range_lease.go, line 371 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12354#-KYzBa32vv3dA6D6EPYC:-KYzPxHo7YAA6LvxmPS-:b-9h3jl5) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a1251bc34298a45b59d667017f71713ee70911/pkg/storage/replica_range_lease.go#L371)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

"located at the ... table" is odd. how about "ranges whose start keys are not greater than the node liveness prefix"
</blockquote></details>

Why just restate what the code is doing? I added a bit to the comment.

---

*[pkg/storage/replica_range_lease.go, line 376 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12354#-KYz8JI8Snc6kbU688It:-KYzOenTS8TNSGbJKIMp:b-8p7oc1) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a1251bc34298a45b59d667017f71713ee70911/pkg/storage/replica_range_lease.go#L376)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

You could use r.mu.AssertHeld here.
</blockquote></details>

We're always holding `Replica.mu` here. Where do you get the idea we're not?

@tamird are we using `r.mu.AssertHeld()` consistently elsewhere? I'm against starting to use this at seeming random unless we've committed to it in our style guide.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12354)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/storage/replica_range_lease.go, line 376 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12354#-KYz8JI8Snc6kbU688It:-KYzQOn8i--lb_RTky4c:bppd7be) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a1251bc34298a45b59d667017f71713ee70911/pkg/storage/replica_range_lease.go#L376)):*
<details><summary><i>Previously, spencerkimball (Spencer Kimball) wrote…</i></summary><blockquote>

We're always holding `Replica.mu` here. Where do you get the idea we're not?

@tamird are we using `r.mu.AssertHeld()` consistently elsewhere? I'm against starting to use this at seeming random unless we've committed to it in our style guide.
</blockquote></details>

Probably not - it was on my mind because @bdarnell used it in a recent change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12354)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/replica_range_lease.go, line 376 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12354#-KYz8JI8Snc6kbU688It:-KYzR6j00--wjsnoJkfz:b-4j3csl) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a1251bc34298a45b59d667017f71713ee70911/pkg/storage/replica_range_lease.go#L376)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Probably not - it was on my mind because @bdarnell used it in a recent change.
</blockquote></details>

Oh, it wasn't clear the call from `pendingLeaseRequest.InitOrJoinRequest` was correct. But now I see it is. Might be worth `s/requiresExpiringLease/requiresExpiringLeaseLocked/g`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12354)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12354#-:-KYzRTwRU_vwOa3Sdzl1:bnfp4nl)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/replica_range_lease.go, line 376 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12354#-KYz8JI8Snc6kbU688It:-KZ-Z374TKc0yJrUV3hy:blh40eh) ([raw file](https://github.com/cockroachdb/cockroach/blob/83a1251bc34298a45b59d667017f71713ee70911/pkg/storage/replica_range_lease.go#L376)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Oh, it wasn't clear the call from `pendingLeaseRequest.InitOrJoinRequest` was correct. But now I see it is. Might be worth `s/requiresExpiringLease/requiresExpiringLeaseLocked/g`.
</blockquote></details>

I would like to introduce `AssertHeld` everywhere we can, but haven't done any mass changes yet. We are, however, pretty consistent in our use of the `Locked` suffix and should use it here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12354)*

**Pull request merged**
