### PR TITLE
sql,builtins: add builtin functions to perform descriptor repair

### LINKED ISSUE #50948: sql: writing new descriptors to `system.descriptor` from SQL is not possible
**Describe the problem**

The `system.descriptor` table contains two column families. It has the following structure:

```sql
         table_name        |                create_statement
---------------------------+-------------------------------------------------
  system.public.descriptor | CREATE TABLE descriptor (
                           |     id INT8 NOT NULL,
                           |     descriptor BYTES NULL,
                           |     CONSTRAINT "primary" PRIMARY KEY (id ASC),
                           |     FAMILY "primary" (id),
                           |     FAMILY fam_2_descriptor (descriptor)
                           | )
```

The problem, however, is that we only ever write to this table by writing values into the second column family `fam_2_descriptor`. 
All over the place we anticipate only ever finding entries for the second column family. If you blindly attempt to insert into this table, you will write to the first column family and ultimately corrupt everything. For example:

```
root@localhost:26257/defaultdb> INSERT INTO system.descriptor VALUES (57, decode('121f0a046a756e6b10391a150a090a0561646d696e10020a080a04726f6f741002', 'hex'));
INSERT 1

root@localhost:26257/defaultdb> SHOW TABLES;
ERROR: value type is not BYTES: TUPLE
```

**Expected behavior**

We should be able to create new descriptors in the descriptors table from SQL in emergency situations.

### PR DESCRIPTION
**Pull request by ajwerner**
There are bugs in previous versions (#51782, #54861, and surely others) which
can leave descriptors in an invalid state. When this occurs, the only recourse
is to inject either repaired versions directly or other descriptors that allow
use of normal DDL statements to reach the desired state. Prior to this change,
the mechanism by which this repair could be achieved was a bit of a hack
whereby the "node" users which is used internally to muck with certain system
tables could be granted to the "root" user for purposes of updating entries
in tables like system.namespace and system.descriptor. Even this was
problematic because those tables do not utilize all of the column families
when written to using the KV API. That made writing new rows to such tables
extremely dangerous as low-level code for determining zone configurations in
kv assumes that there will be appropriate values in all kv rows in those
tables (which is not the case for certain column families).

Fixes #50948.

Release note (sql change): Added admin-only, crdb_internal functions to enable
descriptor repair in dire circumstances.

### CODE REVIEW

**Comment by ajwerner** [comment]
This deserved more testing but is RFAL.

**Review by thoszhang — COMMENTED** [review]
LGTM so far.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55699#-:-ML6RORy71Iw9S2GGoH4:bgm2fo4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @lucy-zhang)

___
*[pkg/sql/repair.go, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55699#-ML6PcYw1EinNWNZTdgW:-ML6PcYw1EinNWNZTdgX:b9183iu) ([raw file](https://github.com/cockroachdb/cockroach/blob/f311dc7f5dca489a4d82350c4fc267bd2b822f88/pkg/sql/repair.go#L42)):*
> ```
> // is of the subsequent version. This method may only be used to update a
> // descriptor one time per transaction and may not be used to interact with a
> ```
nit: this makes it sound like one descriptor update total is allowed per transaction (and not per descriptor).
___
*[pkg/sql/repair.go, line 324 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55699#-ML6P54BDiuGKBlTmjJL:-ML6P54BDiuGKBlTmjJM:b3f7ib2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f311dc7f5dca489a4d82350c4fc267bd2b822f88/pkg/sql/repair.go#L324)):*
> ```Go
> 	if val.Value == nil {
> 		// Perhaps this is not the best pgcode but it's something.
> 		return pgerror.Newf(pgcode.InvalidCatalogName,
> ```

Why do we want to return pgcodes for these errors?
___
*[pkg/sql/tests/repair_test.go, line 121 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55699#-ML6R8IM7vACcXTpsezR:-ML6R8IM7vACcXTpsezS:b-ejbci6) ([raw file](https://github.com/cockroachdb/cockroach/blob/f311dc7f5dca489a4d82350c4fc267bd2b822f88/pkg/sql/tests/repair_test.go#L121)):*
> ```Go
> 	// This test will inject the table an demonstrate
> 	// that there are problems. It will then repair it by injecting a new
> 	// database descriptor and namespace entry and then
> ```

nit: finish this sentence

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55699)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang)

___
*[pkg/sql/repair.go, line 324 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55699#-ML6P54BDiuGKBlTmjJL:-MMJfuxw8XA2ckiWSjK5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f311dc7f5dca489a4d82350c4fc267bd2b822f88/pkg/sql/repair.go#L324)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Why do we want to return pgcodes for these errors?
</blockquote></details>

Done.

**Review by thoszhang — APPROVED** [review]

**Comment by ajwerner** [comment]
TFTR!

bors r=lucy-zhang

**Pull request merged**
