### PR TITLE
log: support to archive log using gzip 

### LINKED ISSUE #40861: log: support to archive log instead of delete it only
(edited: @knz 2020-01-09)

This issue is to propose expanding CockroachDB's log file handling with another feature from [`logrotate(8)`](https://linux.die.net/man/8/logrotate): compression of the rotated log files.

In a nutshell:

1. the current log file should remain uncompressed;
2. the last rotated log file should also remain uncompressed;
3. all previous rotated log files before that are compressed;
4. older files, including compressed files, whose size cause the directory to exceed the configured `--log-dir-max-size` are still removed, as currently.

That is, the rotation behavior should be extended to compress the previously-rotated log file.
For example, a directory listing would look as follows:

```
cockroach.kenax.kena.2020-01-02T15_46_38Z.044260.log.gz
cockroach.kenax.kena.2020-01-02T15_46_45Z.044269.log.gz
cockroach.kenax.kena.2020-01-02T18_55_28Z.062609.log.gz
cockroach.kenax.kena.2020-01-03T12_50_04Z.042125.log
cockroach.kenax.kena.2020-01-03T12_50_04Z.042125.log
cockroach.log@ -> cockroach.kenax.kena.2020-01-03T12_50_04Z.042125.log
```

This behavior would be opt-in and activated by `--log-compress-old-files`.

The  issue does not suggest introducing a maximum number of log files (as in the default `logrotate` behavior), i.e. we propose to keep  `--log-dir-max-size` parameter as main capacity control. 

The two features can then be combined by users to keep all files around, compressed, by providing `--log-compress-old-files --log-dir-max-size=1TB` (or some other large value).

Jira issue: CRDB-5505

### PR DESCRIPTION
**Pull request by seekingua**
use gzip to archive log file instead of removing it, not only for cockroach log, but for sql-audit log and rocksdb log

Fixes #40861

### CODE REVIEW

**Comment by seekingua** [comment]
code for new feature in #40861

**Comment by knz** [comment]
Hi @seekingua I will be reviewing this work.
First, thank you for your contribution!

We're excited to see an external contributor like you come to the project and help.
As you may have noticed, most of our other commits in the repository follow a regular format: we use unit testing, we write commit messages with a particular format, etc.

Therefore we would be grateful if you could invest a bit more time to polish the change here according to our community guidelines.

You can start here:
https://wiki.crdb.io/wiki/spaces/CRDB/pages/73072641/How+to+submit+a+good+CockroachDB+PR

Then I'd also like to invite you to explain a bit more what is the idea behind this change inside the commit message. We have some guidelines as to how to write a commit message here:
https://wiki.crdb.io/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages

Once you have performed a few tweaks according to these pages, I will be glad to review your change further.

Thank you!

**Comment by seekingua** [comment]
@knz ok, i am learning these specifications. will try again and @you after all checks passed

**Comment by seekingua** [comment]
@knz hi, ci #74541 has passed. so review could be started?😊thx

**Comment by knz** [comment]
Thank you for the update.
I have a few questions about the approach you've taken:

1. your change suggests that each secondary logger can use its separate logging directory. But is that the case? What happens with your change if I select a non-standard log directory for the main logger? Where are the secondary log files created?

2. you appear to be creating a gzipped tar archive to store individual log files. The tar format is a multi-file archive format. Why did you choose the tar format? Why did you not chose to simply compress each log file with gzip directly?

**Comment by seekingua** [comment]
@knz thank you for your reply 😄, let me explain them

> 1. your change suggests that each secondary logger can use its separate logging directory. But is that the case? What happens with your change if I select a non-standard log directory for the main logger? Where are the secondary log files created?

main and secondary logger can use same logging directory as default, but can also use different directories, all of this is same as before, you can use separate logging directory for audit log when using flag '--sql-audit-dir', nothing about this be changed in this pr.
 
case 1: use same directory
```
start 
--insecure 
--store=/data/cockroach-data/store1 
--log-dir=/tmp/cockroach 
--log-file-max-size=100k 
--log-dir-max-size=300k 
--log-file-archive=true
```
WeChatfdcfe8b31f28573cf049cf9df2724b2a

case 2: use different directories
```
start 
--insecure 
--store=/data/cockroach-data/store1 
--log-dir=/tmp/cockroach
--sql-audit-dir=/tmp/cockroach_audit
--log-file-max-size=100k 
--log-dir-max-size=300k 
--log-file-archive=true
```
WeChat199533cdcdce3afcb0a9bbe2c4983dca


> 2. you appear to be creating a gzipped tar archive to store individual log files. The tar format is a multi-file archive format. Why did you choose the tar format? Why did you not chose to simply compress each log file with gzip directly?

you're right. in this case,  there's no need to use tar because compress is only for single file, use gzip is ok, i'll fix this in next commit

**Review by knz — COMMENTED** [review]
Thank you for your answer. Based on your explanation and looking at the code, I am optimistic we can accept your change. You convinced me this is a useful feature.

From now on, the review process will go in two phases. 
In the first phase, I will make high-level comments about the overall structure of the code. Once the overall structure is fine, we will go in the second phase where we look at smaller details. 

Also even after we complete the review, you will see that we will wait a couple of weeks before merging the result. This is because our `master` branch is currently frozen for feature changes, until we release CockroachDB 19.2 in october. Your new feature will be integrated towards the 20.1 release in 2020.

For the first phase, I am happy to see that the change is not too invasive. However, while reviewing your change I noticed that our prior code in `util/log` is very complex and hard to understand. (I can compliment you for understanding it — we certainly lack documentation). 

In order to protect us (both you and the rest of our team) from fragility, I have decided to invest some time to "prepare" the package for your change. Please consider my branch here: #40993 (from https://github.com/knz/cockroach/tree/20190323-util-log-refactor ).
I would like to invite you to rebase your change on top of that branch. 

Once you have performed this rebase and extracted the file rotation logic into a separate function, we can move to the second phase of the review.

Thank you

> Reviewed 2 of 6 files at r2, 2 of 2 files at r3, 3 of 3 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40835#-:-LpUnMU44i99UPOnNtVQ:b-lnh8fr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @seekingua)

___
*[pkg/util/log/clog.go, line 1332 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/40835#-LpUnGumBQXeXcYqC1-7:-LpUnGun1sJd06nyd8XV:brihrfr) ([raw file](https://github.com/cockroachdb/cockroach/blob/62a69596b0b298a819b584c573f94a223f909f07/pkg/util/log/clog.go#L1332)):*
> ```Go
> 
> 		// archive log file
> 		if LogFileArchive {
> ```

Please extract this branch into a separate function, for clarity.

**Comment by seekingua** [comment]
@knz already create a pr with this change to your branch 20190323-util-log-refactor 😄

**Comment by knz** [comment]
Hi @seekingua! Sorry it took a bit long, we were very busy preparing the new release of cockroachdb 19.2.

I'd like to resume work on this PR. As you can see indeed you'll need to rebase your PR and integrate your changes to the new file layout. I think your code change will be mostly focused on `log_gc.go`.

**Comment by seekingua** [comment]
> Hi @seekingua! Sorry it took a bit long, we were very busy preparing the new release of cockroachdb 19.2.
> 
> I'd like to resume work on this PR. As you can see indeed you'll need to rebase your PR and integrate your changes to the new file layout. I think your code change will be mostly focused on `log_gc.go`.

@knz ok, will resubmit pr in the next few days，😄

**Comment by knz** [comment]
Thank you for your change! This looks good.
When do you plan to add the corresponding unit tests?

**Comment by seekingua** [comment]
> Thank you for your change! This looks good.
> When do you plan to add the corresponding unit tests?

@knz sorry about unit tests, a little busy in recent days 😭, will finish in one or two more days

**Comment by seekingua** [comment]
@knz all done this time

**Comment by knz** [comment]
Thank you for the update.
A few things that need polishing before we merge this:

- the issue #40861 that you filed to describe the feature mentions the feature should be configurable. However I don't see the configuration option any more. Was this intentional?

- try to make code comments into full sentences: capital at start of sentence, period at end, a verb etc.

- we don't need to check the result status of `fmt.Printf`

**Comment by seekingua** [comment]
> Thank you for the update.
> A few things that need polishing before we merge this:
> 
> * the issue #40861 that you filed to describe the feature mentions the feature should be configurable. However I don't see the configuration option any more. Was this intentional?

@knz the configurable mentioned in the issue #40861 , I have removed it, it was previously configurable for backward compatibility. But as you mentioned, this feature will be added to the new version, so it may be enabled by default. of course, depending on your planning for this.


> * try to make code comments into full sentences: capital at start of sentence, period at end, a verb etc.
> * we don't need to check the result status of `fmt.Printf`
Ok, i'll rewrite comments and remove ignore for result status of `fmt.Printf`

**Comment by seekingua** [comment]
@knz what else needs to be done next？ 😄

**Comment by knz** [comment]
My apologies, we've been very busy releasing the first bug/security fixes for 19.2. This PR is nearly ready to go, we'll pick it up very soon now.

**Comment by knz** [comment]
Hello @seekingua 
I have reviewed your PR and consulted with the team.
There are several open issues with the functionality which we need to address before we can merge this:

- we prefer to keep enforcing the `--log-dir-max-size` parameter. That is, the GC process must continue to delete files beyond that size.
- the idea of compression is still useful to keep a larger number of log files around within the directory max size limit. For this to be meaningful, the compression must be activated for most rotated log files, starting soon after the current log file.
- to ease adoption of CockroachDB we would prefer to provide a behavior close to that of other tools. For example, [`logrotate(8)`](https://linux.die.net/man/8/logrotate):
  1. the current log file is uncompressed
  2. the last rotated log file is also uncompressed
  3. all previous rotated log files before that are compressed
  4. files beyond the maximum limit are removed
- the behavior should be opt-in (configurable), not enabled by default.

I will reword the text of #40861 accordingly.

**Pull request closed without merging**
