### PR TITLE
storage: de-flake TestLeaderLeaseConcurrent

### PR DESCRIPTION
**Pull request by tbg**
Reproposals were causing spurious test failures; the test now logs
a warning in this case (and tests less).
A missing return statement caused (much rarer) deadlock due to prompting
a possibly dead-blocking channel send.

Ran 110k+ iterations of this without issues; the failures would usually
manifest locally in <10k iterations.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6194)

### CODE REVIEW

**Comment by vivekmenezes** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/replica_test.go, line 1331 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6194#-KFt0kFJg7OfeQWJvmLS:-KFt0kFJg7OfeQWJvmLT:458804221) ([raw file](https://github.com/cockroachdb/cockroach/blob/b91a25c498374f9ec7cb741498a2f00723dc4604/storage/replica_test.go#L1331)):*
If this is expected under rare circumstances why keep it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6194)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/replica_test.go, line 1331 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6194#-KFt0kFJg7OfeQWJvmLS:-KFt15yEbAh0OXAHgdEY:1337507533) ([raw file](https://github.com/cockroachdb/cockroach/blob/b91a25c498374f9ec7cb741498a2f00723dc4604/storage/replica_test.go#L1331)):*
You want to keep it around just to log a message during a reproposal. Makes sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6194)*

**Comment by vivekmenezes** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6194#-:-KFt1IW94qOWM_8_0ki2:1417088721)*

**Comment by bdarnell** [comment]
LGTM

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6194#-:-KFtW4Yw1o-ZE4mlTyMf:676834233)*

**Pull request merged**
