### PR TITLE
sql: skip TestTruncateWhileColumnBackfill

### PR DESCRIPTION
**Pull request by tbg**
See https://github.com/cockroachdb/cockroach/issues/43990.

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
@knz as you LGTM it, might as well bors it for me. Thanks!

**Comment by knz** [comment]
LGTM

bors r+

-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by knz** [comment]
There's one issue in that CI failure that's on me (the trace mismatch thing - I have an issue for it already assigned for me) but the other colexec assertion failure is a recent regression which I do not know about.

**Comment by tbg** [comment]
@knz the colexec assertion looks like https://github.com/cockroachdb/cockroach/issues/43357#issuecomment-574865874

bors r=knz

**Comment by knz** [comment]
round and round goes the merry go round :carousel_horse: 

bors r+

**Comment by tbg** [comment]
^- last one was https://github.com/cockroachdb/cockroach/issues/43357#issuecomment-568192479

**Comment by knz** [comment]
I'm going to make a combined PR with the other two failing tests

**Comment by knz** [comment]
added a commit to skip over the two other SQL things.

bors r+

**Pull request merged**
