### PR TITLE
storage: enable columnar blocks by default, metamorphically toggle

### PR DESCRIPTION
**Pull request by jbowens**
Enable use of columnar blocks, metamorphically toggling it in tests.

Epic: none
Release note: none

### CODE REVIEW

**Review by itsbilal — APPROVED** [review]
LGTM

**Comment by RaduBerinde** [comment]
We'll probably need the fix in https://github.com/cockroachdb/pebble/pull/4101

**Review by RaduBerinde — APPROVED** [review]
LGTM

I'd change the description and commit to say that we're enabling them by default

**Comment by jbowens** [comment]
TFTRs!

bors r+

**Pull request merged**
