### PR TITLE
storage: propagate errors from contentionQueue, catch stalls in roachtest

### LINKED ISSUE #36089: roachtest: kv/contention/nodes=4 failed
SHA: https://github.com/cockroachdb/cockroach/commits/c59f5347d5424edb90575fb0fd50bad677953752

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=kv/contention/nodes=4 PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1195732&tab=buildLog

```
The test failed on release-19.1:
	ts_util.go:89,kv.go:186,cluster.go:1605,errgroup.go:57: spent 5.263158% of time below target of 10.000000 txn/s, wanted no more than 5.000000%
	cluster.go:1626,kv.go:189,test.go:1214: Goexit() was called

```

### PR DESCRIPTION
**Pull request by nvb**
Informs #36089.

The PR is split into a series of commits. The first fixes part of a bug that was causing #36089  to fail (thanks to #36748) and the second improves the test to have a more obvious failure condition for this class of bug in the future. The third, fifth, and sixth clean up code. Finally, the fourth fixes another bug that could cause issues with #36089.

Before the first commit, requests could get stuck repeatedly attempting to push a transaction only to repeatedly find that they themselves were already aborted. The error would not propagate up to the transaction coordinator and the request would get stuck. This commit fixes this behavior by correctly propagating errors observed by the `contentionQueue`.

The second commit bumps the TxnLivenessThreshold for clusters running `kv/contention/nodes=4` to 10 minutes. This is sufficiently large such that if at any point a transaction is abandoned then all other transactions will begin waiting for it, throughput will drop to 0 for 10 straight minutes, and the test will fail to achieve its minimum QPS requirement.

The fourth commit instructs pushers in the `txnwait.Queue` to inform all other pushers that are waiting for the same transaction when it observes an ABORTED transaction. I never saw this cause issues with #36089, but it seems very possible that it could given frequent tscache rotations.

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
NOTE: I saw this get stuck once after bumping the `TxnLivenessThreshold` in the roachtest. That indicates that there is another stall lingering. I'm not planning on merging this PR until I gain a better understanding of what's going on there.

**Review by ajwerner — APPROVED** [review]
Nice find! I know you're not planning on merging this yet but :lgtm: 

> Reviewed 3 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37199#-:-LdiIktn6WN2KOj3xOYj:b9r6xji)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by nvanbenschoten** [comment]
I think I tracked down the other stall here. It has to do with a rare interleaving of requests in the `contentionQueue`. I found this all by looking at the `/debug/requests` page after bumping the page's [`maxActiveTraces`](https://github.com/cockroachdb/vendored/blob/a7dd57ee014cb7c9b20b77d638038552b8264e9a/golang.org/x/net/trace/trace.go#L436) to a more reasonable 300. The expanded view of the active traces revealed the following deadlock:
```
txn 8703f023
    pushing ee447be3
    behind f081497c in the queue
    stuck after noticing pushee aborted
        waiting for f081497c to notice
    aborted itself

txn ee447be3
    pushing 8703f023
    behind f081497c in the queue
    stuck after noticing pushee aborted
        waiting for f081497c to notice
    aborted itself

txn f081497c
    pushing both 8703f023 and ee447be3
    front of queue in both
    stuck pushing both txns

all other txns: stuck on f081497c
```

The first two transactions are stuck in the `contentionQueue` after observing each other as aborted. The don't realize that they themselves are aborted because transactions in the `contentionQueue` don't query their own disposition. They also don't immediately exit the queue when they determine that the front of the queue is aborted. Instead, they wait on their predecessor in the queue to notice to avoid a thundering herd.

#### So what's going wrong? Why isn't this resolving itself?

##### If `8703f023` and `ee447be3` are aborted, why isn't `f081497c` noticing?

It is stuck in the `TxnWaitQueue`, waiting for updates to either of these transactions. Specifically, it is waiting for one of two things:
1. updates to its pushees' transaction records
2. [its pushees' expirations](https://github.com/cockroachdb/cockroach/blob/6ff43d555e9e22426b4939041a2b4247ef289a7e/pkg/storage/txnwait/txnqueue.go#L565), which are set to 5m!

##### Why aren't there any updates to `8703f023` and `ee447be3`'s transaction records

They are stuck in the contentionQueue and haven't noticed that they are aborted. This hasn't been propagated back to their transaction coordinator so no one has rolled back their transaction records.

##### Why isn't deadlock detection working?

Because both `8703f023` and `ee447be3` are already aborted, so the two transactions aren't sitting in each other's `TxnWaitQueue`s.

##### Why do `8703f023` and `ee447be3` think each other are aborted but `f081497c` is still in the `TxnWaitQueue`?

There actually appear to be two ways for us to get in this deadlock scenario. The first is due to a timestamp cache rotation. Imagine that `8703f023` and `ee447be3` queried each other's transaction records *after* `f081497c` queried their transaction records. Between this time, nothing was written. However, there was a timestamp cache rotation! Each of these transactions would consider the other aborted because of `ABORT_REASON_TIMESTAMP_CACHE_REJECTED_POSSIBLE_REPLAY`. If the abort was noticed during a `QueryTxnRequest`, no one would notify `f081497c`, who is still sitting in the `TxnWaitQueue`, and it would be stuck there until the pushee expired. We can fix this case by informing the `TxnWaitQueue` if a `QueryTxnRequest` ever decides that a transaction is aborted.

The second way to get into this deadlock scenario is more tricky, but it shows up more in this workload. A contention point when designing https://github.com/cockroachdb/cockroach/pull/33523 was deciding how pushes of transactions originating from intents with `txnMeta.timestamp >> txn.OrigTimestamp`. The problem is that when a transaction is aborted, the write timestamp cache is only bumped to its current timestamp. However, that transaction can keep writing if it isn't immediately informed of the abort, potentially at higher timestamps. So if a contending transaction observes one of these intents with a higher timestamp and pushes, it may not realize that the transaction was already aborted because it compares its timestamp against the write timestamp cache and find that its timestamp is above the cache. This is discussed in the following three places:

https://github.com/cockroachdb/cockroach/blob/5c1497ab719342c5666ce6d684c6d76dcbb3821e/pkg/storage/batcheval/transaction.go#L134-L141

and 

https://github.com/cockroachdb/cockroach/blob/5c1497ab719342c5666ce6d684c6d76dcbb3821e/pkg/storage/batcheval/cmd_push_txn.go#L161-L167

and 

https://github.com/cockroachdb/cockroach/blob/5c1497ab719342c5666ce6d684c6d76dcbb3821e/pkg/storage/replica_tscache.go#L286-L292

It turns out that this scenario can cause issues when combined with the dependencies enforced by the `contentionQueue`. If the first transaction in the queue falls into this trap of falsely assuming a pushee is not aborted and later transactions don't, the later transactions can get stuck waiting on the first transaction to notice that the pushee has already been aborted. If the pushee itself is stuck in a second `contentionQueue` on the same situation then it will never rollback its transaction record and inform the first transaction in the queue that it is indeed aborted. So everything gets stuck. It turns out that it is not ok for some pushees to consider a transaction to be pending while other pushees consider a transaction to be aborted.

The solution to this isn't immediately clear. I see two options at the moment:
1. we begin storing the `EpochZeroOrigTimestamp` in intents. This allows all pushers to have perfect accuracy about whether or not a transaction has been aborted by any other pusher. In other words, it allows us to get rid of [this nastiness](https://github.com/cockroachdb/cockroach/blob/5c1497ab719342c5666ce6d684c6d76dcbb3821e/pkg/storage/batcheval/transaction.go#L134-L141). Interestingly, it would come for free with the proposal to change transaction IDs to be a combination of the epoch-zero-orig-timestamp and a gateway ID.
2. we go back to always leaving an ABORTED transaction record before a pushee can consider a transaction to be aborted. This feels safer (although there is still come complication around QueryTxn requests that find a missing txn record), but is also a large step backward away from a proposal like [this](https://github.com/cockroachdb/cockroach/blob/5c1497ab719342c5666ce6d684c6d76dcbb3821e/pkg/storage/replica_tscache.go#L378). It also returns to letting pushers create transaction records as long as they are in the ABORTED state.

@tbg @andreimatei I'm curious whether either of you two has a strong preference here.

On the positive side, with `QueryTxn` requests updating the `TxnWaitQueue` when they observe a transaction to be aborted and with the first of these options implemented, the test seems to pass without any stalls (after about 6 hrs of running).

**Comment by tbg** [comment]
Great writeup! Before I dive in, I'm curious if any of the stuff @darinpp added to the txnWaitQ helped (https://github.com/cockroachdb/cockroach/pull/35921) or would've helped figure out where "something" was stuck. (Or, if you repro this scenario again, I'd be grateful if you gave it a try and reported back, in particular the "have been waiting" log message).

I just took a look at the contentionQ code to remind myself how it works. Oof. I'd be surprised if this were the last bug.

> There actually appear to be two ways for us to get in this deadlock scenario. The first is due to a timestamp cache rotation. Imagine that 8703f023 and ee447be3 queried each other's transaction records after f081497c queried their transaction records. Between this time, nothing was written. However, there was a timestamp cache rotation!

We query the pushee periodically, but I just realized that this is based on the TxnExpiration, which is artificially high in this test. Just pointing this out for anyone else wondering.

I like option 1. We can optimize for the common case in which Timestamp == Epoch0Timestamp by adding the convention that the epoch 0 timestamp defaults to the timestamp to avoid writing more than we do today (if we also decide to make the field nullable).

**Comment by nvanbenschoten** [comment]
> I'm curious if any of the stuff @darinpp added to the txnWaitQ helped (#35921) or would've helped figure out where "something" was stuck. (Or, if you repro this scenario again, I'd be grateful if you gave it a try and reported back, in particular the "have been waiting" log message).

The "have been waiting" log message in `txnqueue.go` was very helpful and helped point me at the offending transactions once I knew to look for them. The metrics themselves would have pointed me at the blockage, but I'm not sure whether they would have helped in the actual debugging. The problem with these kinds of issues is that most of the questions a debugger would like to ask are "what sequence of events led to this situation?", not "what situation are we in now that we're stalled?".

I also think the reason why the "have been waiting" log message was more useful than the metrics is because the log message actually includes transaction ids. Without that, it's not really possible to come to any conclusions about the state of a deadlock. With that in mind, a "have been waiting" log message in `contentionQueue.go` would be helpful.

> I like option 1. We can optimize for the common case in which Timestamp == Epoch0Timestamp by adding the convention that the epoch 0 timestamp defaults to the timestamp to avoid writing more than we do today (if we also decide to make the field nullable).

👍 I was leaning that way myself. It will be really nice to remove this uncertainty. I don't think the migration will be too difficult either, as the new field will need to be optional no matter what.

**Comment by tbg** [comment]
> The "have been waiting" log message in txnqueue.go was very helpful and helped point me at the offending transactions once I knew to look for them. The metrics themselves would have pointed me at the blockage, but I'm not sure whether they would have helped in the actual debugging. The problem with these kinds of issues is that most of the questions a debugger would like to ask are "what sequence of events led to this situation?", not "what situation are we in now that we're stalled?".

👍 that's about as good as I hoped it was going to get. The metrics can't do the debugging for you but looks like they gave you a good starting point to logspy in.

**Comment by andreimatei** [comment]
I like option 1 too. Option 2 - writing more ABORTED txn records - seems indeed that we'd be going backwards. I hope we get to where we never write any ABORTED records.

**Comment by tbg** [comment]
Friendly ping, was just looking through our roachtests and this seems like a nice wart to iron out.

**Comment by nvanbenschoten** [comment]
Yep, this is on my plate for after we stabilize parallel commits. The two additional items that I need to polish off are:
1. `QueryTxn` requests update the `TxnWaitQueue` when they observe a transaction to be aborted
2. we begin storing the `EpochZeroOrigTimestamp` in intents. This allows all pushers to have perfect accuracy about whether or not a transaction has been aborted by any other pusher

**Comment by nvanbenschoten** [comment]
I've updated this PR to address the first additional item that we need to fix. The second one is larger, so I'm going to put that into a different PR. I've downgraded this to no longer say "Fixes" because it doesn't include the full fix.

PTAL @ajwerner.

**Review by ajwerner — APPROVED** [review]
:lgtm: 

Thanks for the great writeup. My mental model on the TxnWaitQueue is still fuzzier than I'd like but this change is straightforward enough. Are there any downsides to notifying all of the pushees upon a single abort? 

> Reviewed 3 of 5 files at r3, 1 of 2 files at r4, 2 of 2 files at r5, 2 of 3 files at r6, 10 of 10 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37199#-:-LjGTqFU8SD7aIBkYfoj:b-9u2ijo)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by nvanbenschoten** [comment]
> Are there any downsides to notifying all of the pushees upon a single abort?

I don't think so. Once the pushee is aborted, all of the pushers would like to know ASAP.

Thanks for the review.

bors r+

**Pull request merged**
