### PR TITLE
kv: address comments from #10772

### PR DESCRIPTION
**Pull request by spencerkimball**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10790)

### CODE REVIEW

**Comment by spencerkimball** [comment]
+cc @bdarnell

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/storage/replica.go, line 1806 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10790#-KWth9tIqupTJeZWfdbI:-KWth9tIqupTJeZWfdbJ:bmp2l2n) ([raw file](https://github.com/cockroachdb/cockroach/blob/06dfa6667356fc9007b3bd6d05d1fd5f1e100f5b/pkg/storage/replica.go#L1806)):*
From #10772:

> The ambiguous result error is only returned if the context was cancelled and the command might already be executing, right? The first sentence states that the ambiguous result is returned unconditionally, and then the second sentence adds a condition.

---

*[pkg/storage/replica.go, line 1820 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10790#-KWthv5-bE1mOi9t_raO:-KWthv50OG1m0EQDaNVN:b-1mzltg) ([raw file](https://github.com/cockroachdb/cockroach/blob/06dfa6667356fc9007b3bd6d05d1fd5f1e100f5b/pkg/storage/replica.go#L1820)):*
> ```Go
> 			// We return an AmbiguousResultError to indicate to caller that
> 			// the command may have executed.
> 			//
> ```

can you mention that we loop around because our context is in use? should use similar language to the preceding clause (after addressing the confusion in that comment)

---

*[pkg/storage/replica.go, line 3148 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10790#-KWti6QGKyJL1lbBsK2H:-KWti6QGKyJL1lbBsK2I:br5ndjd) ([raw file](https://github.com/cockroachdb/cockroach/blob/06dfa6667356fc9007b3bd6d05d1fd5f1e100f5b/pkg/storage/replica.go#L3148)):*
from #10772:
> not your code, but what is this? 

Non-blocking, but would be good to not leave this for the next poor sap.

---

*[pkg/storage/replica_test.go, line 5777 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10790#-KWtiaDFV-rifM-0uH75:-KWtiaDFV-rifM-0uH76:bai43wg) ([raw file](https://github.com/cockroachdb/cockroach/blob/06dfa6667356fc9007b3bd6d05d1fd5f1e100f5b/pkg/storage/replica_test.go#L5777)):*
From #10772:

> Meant to skip actually sending something down to Raft.

Can you add a comment explaining why this is necessary?

---

*[pkg/storage/replica_test.go, line 5790 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10790#-KWtiOgDnl4MAS47SzKz:-KWtiOgE9qCsBd7gKIoo:bgdzh65) ([raw file](https://github.com/cockroachdb/cockroach/blob/06dfa6667356fc9007b3bd6d05d1fd5f1e100f5b/pkg/storage/replica_test.go#L5790)):*
from #10772:

>  You're failing the test if the error is nil, meaning that you expect an error. I'm suggesting you check explicitly for the error you expect.

I suggested that the code be roughly
```
if cancelEary {
  // check the expected outcome
} else {
 // check the expected outcome
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10790)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/storage/replica.go, line 1371 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10790#-KWtmz8jfmap4U667LyT:-KWtmz8jfmap4U667LyU:bkins1y) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c620b78494d7446bd592a27db96ddcd1e33d4bf/pkg/storage/replica.go#L1371)):*
> ```Go
> 						select {
> 						case <-ch:
> 						case <-r.store.stopper.ShouldQuiesce():
> ```

can you help me understand why this wasn't necessary before #10772?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10790)*

**Comment by spencerkimball** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica.go, line 1806 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10790#-KWth9tIqupTJeZWfdbI:-KWuD-3_AANMLBq9IcNK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/06dfa6667356fc9007b3bd6d05d1fd5f1e100f5b/pkg/storage/replica.go#L1806)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> From #10772:
> 
> > The ambiguous result error is only returned if the context was cancelled and the command might already be executing, right? The first sentence states that the ambiguous result is returned unconditionally, and then the second sentence adds a condition.
</details>
Done.

---

*[pkg/storage/replica.go, line 1820 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10790#-KWthv5-bE1mOi9t_raO:-KWuDJRGZSnm0SAnuEYD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/06dfa6667356fc9007b3bd6d05d1fd5f1e100f5b/pkg/storage/replica.go#L1820)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can you mention that we loop around because our context is in use? should use similar language to the preceding clause (after addressing the confusion in that comment)
</details>
Done.

---

*[pkg/storage/replica.go, line 3148 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10790#-KWti6QGKyJL1lbBsK2H:-KWuDMfJBZb_rkJWLH2q:b3kre) ([raw file](https://github.com/cockroachdb/cockroach/blob/06dfa6667356fc9007b3bd6d05d1fd5f1e100f5b/pkg/storage/replica.go#L3148)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> from #10772:
> > not your code, but what is this? 
> 
> Non-blocking, but would be good to not leave this for the next poor sap.
</details>
?

---

*[pkg/storage/replica.go, line 1371 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10790#-KWtmz8jfmap4U667LyT:-KWuCOqFRo2UYxPs5ZoP:b-awx14w) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c620b78494d7446bd592a27db96ddcd1e33d4bf/pkg/storage/replica.go#L1371)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can you help me understand why this wasn't necessary before #10772?
</details>
I didn't trace the exact difference. Presumably the fact that we now allow commands to cancel is also allowing them to also continue adding additional commands to the command queue which get stuck waiting for that original (now cancelled) command's `endCmds.done()` call.

---

*[pkg/storage/replica_test.go, line 5777 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10790#-KWtiaDFV-rifM-0uH75:-KWuDP95e04RUqiTK7Gg:b-gq4wyn) ([raw file](https://github.com/cockroachdb/cockroach/blob/06dfa6667356fc9007b3bd6d05d1fd5f1e100f5b/pkg/storage/replica_test.go#L5777)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> From #10772:
> 
> > Meant to skip actually sending something down to Raft.
> 
> Can you add a comment explaining why this is necessary?
</details>
actually I don't think it is necessary. I just resurrected this test; wasn't original author. I couldn't see why it would be necessary, removed it, and the test is passing under stress, so meh..

---

*[pkg/storage/replica_test.go, line 5790 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10790#-KWtiOgDnl4MAS47SzKz:-KWuEc2HVTtSnYNeIiS-:b-yqqvr9) ([raw file](https://github.com/cockroachdb/cockroach/blob/06dfa6667356fc9007b3bd6d05d1fd5f1e100f5b/pkg/storage/replica_test.go#L5790)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> from #10772:
> 
> >  You're failing the test if the error is nil, meaning that you expect an error. I'm suggesting you check explicitly for the error you expect.
> 
> I suggested that the code be roughly
> ```
> if cancelEary {
>   // check the expected outcome
> } else {
>  // check the expected outcome
> }
> ```
</details>
Well I honestly don't know if that's better. It's a confusing test – the fact it's written as a function is very off-putting, as is this random return. But your suggestion to check the expected outcome for the `!cancelEarly` code path doesn't make a ton of sense. What's to check? We're expecting no error in that case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10790)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica.go, line 3148 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10790#-KWti6QGKyJL1lbBsK2H:-KWuICzuynRS-0nLZTr3:b-t3awz3) ([raw file](https://github.com/cockroachdb/cockroach/blob/06dfa6667356fc9007b3bd6d05d1fd5f1e100f5b/pkg/storage/replica.go#L3148)):*
<details><summary><i>Previously, spencerkimball (Spencer Kimball) wrote…</i></summary>
> ?
</details>
In #10772 I asked about this code, and you said you weren't sure. I'm saying that while you're here, it would be good to figure out what it's about and either expand the comment if it's not FUD, or remove this line if it is.

---

*[pkg/storage/replica.go, line 1371 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10790#-KWtmz8jfmap4U667LyT:-KWuHpjqDPwe42_8xxe4:b-sp6seh) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c620b78494d7446bd592a27db96ddcd1e33d4bf/pkg/storage/replica.go#L1371)):*
<details><summary><i>Previously, spencerkimball (Spencer Kimball) wrote…</i></summary>
> I didn't trace the exact difference. Presumably the fact that we now allow commands to cancel is also allowing them to also continue adding additional commands to the command queue which get stuck waiting for that original (now cancelled) command's `endCmds.done()` call.
</details>
We had a form of cancellation before #10279, and yet this was not required. I'm not comfortable pushing this through without understanding the cause.

---

*[pkg/storage/replica_test.go, line 5790 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10790#-KWtiOgDnl4MAS47SzKz:-KWuIWmIKsSBDeCIERRa:b-slof99) ([raw file](https://github.com/cockroachdb/cockroach/blob/06dfa6667356fc9007b3bd6d05d1fd5f1e100f5b/pkg/storage/replica_test.go#L5790)):*
<details><summary><i>Previously, spencerkimball (Spencer Kimball) wrote…</i></summary>
> Well I honestly don't know if that's better. It's a confusing test – the fact it's written as a function is very off-putting, as is this random return. But your suggestion to check the expected outcome for the `!cancelEarly` code path doesn't make a ton of sense. What's to check? We're expecting no error in that case.
</details>
I'm not sure what this has to do with it being written as a function, so perhaps we're not understanding each other. What I'm suggesting is:
```
br, pErr := tc.repl.addWriteCmd(ctx, ba)
if cancelEarly {
  if !testutils.IsPError(pErr, context.Canceled.Error()) {
    t.Fatalf("unexpected error %v", pErr)
  }
} else {
  if detail := pErr.GetDetail(); detail != nil {
    if _, ok := detail.(*roachpb.AmbiguousResultError); !ok {
      t.Fatalf("unexpected error %T: %s", detail, detail)
    }
  }
}
```

I believe the logic is equivalent, but please confirm.

The benefit is that the positive and negative cases of cancelEarly are not entangled with error checking as they are in the current implementation which I find hard to read.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10790)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica.go, line 1371 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10790#-KWtmz8jfmap4U667LyT:-KWvJY3g8m_iArUnfrui:b-h35uhb) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c620b78494d7446bd592a27db96ddcd1e33d4bf/pkg/storage/replica.go#L1371)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> We had a form of cancellation before #10279, and yet this was not required. I'm not comfortable pushing this through without understanding the cause.
</details>
Simply removing things from the command queue out of sequence during shutdown seems like it could allow inconsistencies.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10790)*

**Comment by spencerkimball** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica.go, line 3148 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10790#-KWti6QGKyJL1lbBsK2H:-KX1FYR6C_dp6LJv8tEj:b9if61c) ([raw file](https://github.com/cockroachdb/cockroach/blob/06dfa6667356fc9007b3bd6d05d1fd5f1e100f5b/pkg/storage/replica.go#L3148)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> In #10772 I asked about this code, and you said you weren't sure. I'm saying that while you're here, it would be good to figure out what it's about and either expand the comment if it's not FUD, or remove this line if it is.
</details>
I unfortunately cannot see into the workings of Tobi's mind. I'm pretty sure he just wanted to avoid confusion with too many contexts floating around because using the wrong one has led to panics in the past.

---

*[pkg/storage/replica.go, line 1371 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10790#-KWtmz8jfmap4U667LyT:-KX1A8ZTLrozSqZIvcL6:bkyl4fl) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c620b78494d7446bd592a27db96ddcd1e33d4bf/pkg/storage/replica.go#L1371)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Simply removing things from the command queue out of sequence during shutdown seems like it could allow inconsistencies.  
</details>
@tamird, yes we had a form of cancellation and that earlier form was incorrect, since it removed the command from the command queue, allowing others that had been blocked on it to proceed. Since the command wasn't actually cancelled, and was still somewhere in the bowels of Raft preparing to be executed, you would lose the guarantees of the command queue.

Now we wait for the still-executing command to finish before unblocking the queue. What that means is that previously on various shutdown scenarios, we'd allow commands to cancel and clear out command queue (since Raft no longer makes forward progress when `ShouldQuiesce` is true).

Now in the same scenario, we leave the command queue blocked forever and subsequent commands get stuck in `Replica.beginCmds` instead of making it through to `tryAddWriteCmd`, where they'd also exit at the `ShouldQuiesce()` select case.

@bdarnell, the comment above says that the command queue expects a command to outlive its prerequisites, so I've altered the code slightly to bail out with an error from `Replica.beginCmds` but avoid removing it from the command queue. Since this is a shutdown scenario, leaving commands in the queue (and the queue in a bad state) seems like an acceptable tradeoff to prevent any more insidious badness.

---

*[pkg/storage/replica_test.go, line 5790 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10790#-KWtiOgDnl4MAS47SzKz:-KX1H9Kud1Mee7RgDlEi:b46pw0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/06dfa6667356fc9007b3bd6d05d1fd5f1e100f5b/pkg/storage/replica_test.go#L5790)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I'm not sure what this has to do with it being written as a function, so perhaps we're not understanding each other. What I'm suggesting is:
> ```
> br, pErr := tc.repl.addWriteCmd(ctx, ba)
> if cancelEarly {
>   if !testutils.IsPError(pErr, context.Canceled.Error()) {
>     t.Fatalf("unexpected error %v", pErr)
>   }
> } else {
>   if detail := pErr.GetDetail(); detail != nil {
>     if _, ok := detail.(*roachpb.AmbiguousResultError); !ok {
>       t.Fatalf("unexpected error %T: %s", detail, detail)
>     }
>   }
> }
> ```
> 
> I believe the logic is equivalent, but please confirm.
> 
> The benefit is that the positive and negative cases of cancelEarly are not entangled with error checking as they are in the current implementation which I find hard to read.
</details>
You missed case of getting a successful result when not cancelling early. But I've changed the code to match your suggestions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10790)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica.go, line 3148 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10790#-KWti6QGKyJL1lbBsK2H:-KX2FpzS4OMOkYCSkRyt:b-u97j0h) ([raw file](https://github.com/cockroachdb/cockroach/blob/06dfa6667356fc9007b3bd6d05d1fd5f1e100f5b/pkg/storage/replica.go#L3148)):*
<details><summary><i>Previously, spencerkimball (Spencer Kimball) wrote…</i></summary>
> I unfortunately cannot see into the workings of Tobi's mind. I'm pretty sure he just wanted to avoid confusion with too many contexts floating around because using the wrong one has led to panics in the past.
</details>
Thanks for expanding the comment.

---

*[pkg/storage/replica_test.go, line 5797 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10790#-KX2Fyoga7fqQtiedtKP:-KX2Fyoga7fqQtiedtKQ:b-p9jtap) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f2202fc2c4c5fabde61b970d51e6fba8ea20af9/pkg/storage/replica_test.go#L5797)):*
> ```Go
> 				}
> 				if err, ok := pErr.GetDetail().(*roachpb.AmbiguousResultError); !ok {
> 					t.Fatalf("expected AmbiguousResultError error; got %s (%T)", err, err)
> ```

`err` is always nil here, so this is not what you want to log

https://play.golang.org/p/EvWD4fWAXW

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10790)*

**Comment by spencerkimball** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica_test.go, line 5797 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/10790#-KX2Fyoga7fqQtiedtKP:-KX2nx6Ok7f1Kilp_SeV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f2202fc2c4c5fabde61b970d51e6fba8ea20af9/pkg/storage/replica_test.go#L5797)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> `err` is always nil here, so this is not what you want to log
> 
> https://play.golang.org/p/EvWD4fWAXW
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10790)*

**Comment by tamird** [comment]
:lgtm: but the second commit seems to have absorbed all the fixes intended for the first commit.

---

Reviewed 1 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10790#-:-KX2oqkFnYLSuqiIIKr8:byuh1vb)*

**Pull request merged**
