### PR TITLE
github-post: add timeout handling to the stress issue poster

### PR DESCRIPTION
**Pull request by andreimatei**
Add explicit support to the issue poster for timeouts:
- on all runs, publish an artifacts file with a list of slow tests
- when timeouts happen, distinguish between the case where the test
currently running at the timeout point is the culprit (i.e. if it is the
longest running test) versus situations where that test is just an
innocent bystender

This patch also spruces up the github-post script in various ways. Among
them there's now better support for running it on an input that comes
directly from a test run, and not from a stress wrapper.

Release note: None

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
Thanks for tackling this! I gave the changes in `listFailures` a quick review. Tons of logic in that method now. I wonder if it should be broken into smaller pieces. Regardless, the test case additions give me some confidence in this PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29987#-:-LLzrFORCumL44Oj5TS7:b-z6zopb)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[build/teamcity-stress.sh, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29987#-LLzf1KiCCGwWSyszNxO:-LLzf1KiCCGwWSyszNxP:bg8vclp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e73e5c90ec68a287d189c35e921e609717aa2de2/build/teamcity-stress.sh#L38)):*
> ```Shell
> make stress PKG="$PKG" TESTTIMEOUT=40m GOFLAGS="$GOFLAGS" TAGS="$TAGS" STRESSFLAGS="-maxruns 100 -maxfails 1 -stderr $STRESSFLAGS" \
>   | tee artifacts/stress.log \
>   | go tool test2json -t | github-post
> ```

@benesch or someone else who is knowledgable about shell pipelines will have to review this.
___
*[pkg/cmd/github-post/main.go, line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29987#-LLzq4AXCYpUfzb6Lfai:-LLzq4AXCYpUfzb6Lfaj:b-ozumzm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e73e5c90ec68a287d189c35e921e609717aa2de2/pkg/cmd/github-post/main.go#L97)):*
> ```Go
> 	// tests. Those tests will remain "outstanding" and will be ignored for the
> 	// purpose of issue reporting.
> 	outstendingOutput := make(map[string][]testEvent)
> ```

`s/outstending/outstanding/g`
___
*[pkg/cmd/github-post/main.go, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29987#-LLznkdk-77Qt8ou6rbh:-LLznkdk-77Qt8ou6rbi:b-hxs21t) ([raw file](https://github.com/cockroachdb/cockroach/blob/e73e5c90ec68a287d189c35e921e609717aa2de2/pkg/cmd/github-post/main.go#L100)):*
> ```Go
> 	failures := make(map[string][]testEvent)
> 	slowPassingTests := make([]testEvent, 0, 1000)
> 	slowFailingTests := make([]testEvent, 0, 1000)
> ```

I doubt there is a measurable effect for pre-allocating these slices. In non-performance sensitive code, I'd go with something more like:

```
var slowPassingTests []testEvent
var slowFailingTests []testEvent
```
___
*[pkg/cmd/github-post/main.go, line 304 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29987#-LLzro6Y5jgnCoSDdk9N:-LLzro6Y5jgnCoSDdk9O:b-u6azrn) ([raw file](https://github.com/cockroachdb/cockroach/blob/e73e5c90ec68a287d189c35e921e609717aa2de2/pkg/cmd/github-post/main.go#L304)):*
> ```Go
> 	}
> 
> 	// Sort slow test descendingly by duration.
> ```

`s/test/tests/g`
___
*[pkg/cmd/github-post/main.go, line 393 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29987#-LLzqjsB0AllaQvV_ERj:-LLzqjsB0AllaQvV_ERk:bixgvj3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e73e5c90ec68a287d189c35e921e609717aa2de2/pkg/cmd/github-post/main.go#L393)):*
> ```Go
> 	if _, err := f.WriteString(report); err != nil {
> 		return err
> 	}
> ```

The above can be written as:

```
if err := ioutil.WriteFile("artifacts/slow-tests-report.txt", []byte(report), 0644); err != nil {
  return err
}
```

**Review by benesch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29987)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[build/teamcity-stress.sh, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29987#-LLzf1KiCCGwWSyszNxO:-LM-u5Ac1X3LLX260sf2:bgicovb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e73e5c90ec68a287d189c35e921e609717aa2de2/build/teamcity-stress.sh#L38)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

@benesch or someone else who is knowledgable about shell pipelines will have to review this.
</blockquote></details>

LGTM but can you stick a `2>&1` onto the `make stress` invocation? We should have had that there all along, I think.

**Review by andreimatei — COMMENTED** [review]
well, I have tried to leave the place cleaner than I found it... I'm not keen to attempt more refactoring now cause I'm not entirely sure what I would do :)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29987#-:-LM3CuyO2P6XP2hiW6l7:b-8gi4o1)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[build/teamcity-stress.sh, line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29987#-LLzf1KiCCGwWSyszNxO:-LM3C8IV1-YPpTkfHdp8:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e73e5c90ec68a287d189c35e921e609717aa2de2/build/teamcity-stress.sh#L38)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

LGTM but can you stick a `2>&1` onto the `make stress` invocation? We should have had that there all along, I think.
</blockquote></details>

done
___
*[pkg/cmd/github-post/main.go, line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29987#-LLzq4AXCYpUfzb6Lfai:-LM3CNJX8uJtYowpe4I0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e73e5c90ec68a287d189c35e921e609717aa2de2/pkg/cmd/github-post/main.go#L97)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/outstending/outstanding/g`
</blockquote></details>

Done.
___
*[pkg/cmd/github-post/main.go, line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29987#-LLznkdk-77Qt8ou6rbh:-LM3CUknCXAj9pjyjNnt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e73e5c90ec68a287d189c35e921e609717aa2de2/pkg/cmd/github-post/main.go#L100)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I doubt there is a measurable effect for pre-allocating these slices. In non-performance sensitive code, I'd go with something more like:

```
var slowPassingTests []testEvent
var slowFailingTests []testEvent
```
</blockquote></details>

Done.
___
*[pkg/cmd/github-post/main.go, line 304 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29987#-LLzro6Y5jgnCoSDdk9N:-LM3CZDJ8FBnCToiDcdl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e73e5c90ec68a287d189c35e921e609717aa2de2/pkg/cmd/github-post/main.go#L304)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/test/tests/g`
</blockquote></details>

Done.
___
*[pkg/cmd/github-post/main.go, line 393 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29987#-LLzqjsB0AllaQvV_ERj:-LM3Co3Z-D25clvsetcN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e73e5c90ec68a287d189c35e921e609717aa2de2/pkg/cmd/github-post/main.go#L393)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The above can be written as:

```
if err := ioutil.WriteFile("artifacts/slow-tests-report.txt", []byte(report), 0644); err != nil {
  return err
}
```
</blockquote></details>

Done.

**Review by petermattis — APPROVED** [review]
> well, I have tried to leave the place cleaner than I found it... I'm not keen to attempt more refactoring now cause I'm not entirely sure what I would do :)

Ack. You should probably prepare yourself for a bit of inevitable fallout. I find that occurs whenever these helper programs are changed. 

:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29987#-:-LM3KNq5-wbktp4-XBCp:b-qlrzn5)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by benesch — APPROVED** [review]
The changes to the shell script :lgtm:. Deferring to Peter's LGTM on the rest.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29987#-:-LM3PNTp9d--wqMowhji:b-flze1l)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Review by andreimatei — COMMENTED** [review]
TFTRs
Btw, the real thing to do, in my opinion, is not so much refactoring the `listFailures` method more, but considering options for not relying on a pipeline of less-than-ideal tools: stress -> go test runner -> test2son -> github-post. The combination of the first 3 produces input that's really hard to operate on, so whatever you do on top is probably going to ugly.</rant>

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29987#-:-LM3hRKCB6onH9jR0OWk:bs25wrc)* status: :shipit: complete! 2 of 0 LGTMs obtained

**Pull request merged**
