### PR TITLE
sql/schemachanger: various fixes to improve runtime

### PR DESCRIPTION
**Pull request by ajwerner**
These commits improve the runtime in very large graphs. Mostly they address quadratic behavior. Some of them just optimize things internally or do minor cleanup. See the individual commits. There still remains one bad point in stage construction to be sorted. 

Release justification: bug fixes and low-risk updates to new functionality

### CODE REVIEW

**Review by fqazi — APPROVED** [review]
> Reviewed 6 of 6 files at r1, 2 of 2 files at r2, 3 of 3 files at r3, 10 of 10 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 8 of 8 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77534)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/schemachanger/scbuild/build.go, line 126 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77534#-MxjDHEB7MomDVZ751uw:-MxjDHEB7MomDVZ751ux:b-4t3m0i) ([raw file](https://github.com/cockroachdb/cockroach/blob/93906d5830bcde327f98d99e4ad5930f36583ef2/pkg/sql/schemachanger/scbuild/build.go#L126)):*
> ```Go
> 	hasOwnership bool
> 
> 	// elementIndexMap maps from the string serialization of the element
> ```

We don't ever modify elements so this looks reasonable. Don't think we would have a use case like that in the builder ever.
___
*[pkg/sql/schemachanger/scpb/constants.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77534#-MxjCTBS3zC097Ms3zAz:-MxjCTBS3zC097Ms3zB-:bizquhd) ([raw file](https://github.com/cockroachdb/cockroach/blob/9adf2f60c12f69dac7ae741eefcaf0f9f3efa0fd/pkg/sql/schemachanger/scpb/constants.go#L71)):*
> ```Go
> }
> 
> // StatusMax is the maximum value of Status.
> ```

The comment looks out of place

**Review by ajwerner — COMMENTED** [review]
TFTR

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77534#-:-MxkS_U8Ecb-Br7g-nMt:bb73zsl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[pkg/sql/schemachanger/scbuild/build.go, line 126 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77534#-MxjDHEB7MomDVZ751uw:-MxjzOgV6prHpWvXip6K:b54u5t2) ([raw file](https://github.com/cockroachdb/cockroach/blob/93906d5830bcde327f98d99e4ad5930f36583ef2/pkg/sql/schemachanger/scbuild/build.go#L126)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

We don't ever modify elements so this looks reasonable. Don't think we would have a use case like that in the builder ever.
</blockquote></details>

It doesn't matter whether we update them under the assumption that if we update them we don't update any attributes which define the key. 
___
*[pkg/sql/schemachanger/scpb/constants.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77534#-MxjCTBS3zC097Ms3zAz:-Mxk19nU-HRJsjECCm7s:bqi30f6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9adf2f60c12f69dac7ae741eefcaf0f9f3efa0fd/pkg/sql/schemachanger/scpb/constants.go#L71)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

The comment looks out of place
</blockquote></details>

indeed, removed

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Comment by ajwerner** [comment]
bors r+

Flake

**Pull request merged**
