### PR TITLE
sql: rework SHOW REGIONS to SHOW REGIONS FROM CLUSTER

### LINKED ISSUE #56331: sql: replace SHOW REGIONS with SHOW REGIONS FROM CLUSTER
Switch the syntax to more clearly contrast it with `SHOW REGIONS FROM DATABASE`.

### PR DESCRIPTION
**Pull request by otan**
Resolves #56331 

Release note (sql change): SHOW REGIONS functionality is now deferred to
SHOW REGIONS FROM CLUSTER.

### CODE REVIEW

**Review by ajstorm — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56627)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/sql/parser/sql.y, line 5127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56627#-MLywXoe5B2ALuxvrhse:-MLywXof-WwYYuJsc1iU:b9gvf7w) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b19543f27708b8678bc6be92543a773829fa22a/pkg/sql/parser/sql.y#L5127)):*
> ```Yacc
> // %Category: DDL
> // %Text:
> // SHOW REGIONS CLUSTER
> ```

Should this be `FROM` CLUSTER?
___
*[pkg/sql/parser/sql.y, line 5128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56627#-MLywahK0i3dw5NRxGHn:-MLywahK0i3dw5NRxGHo:bi53e02) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b19543f27708b8678bc6be92543a773829fa22a/pkg/sql/parser/sql.y#L5128)):*
> ```Yacc
> // %Text:
> // SHOW REGIONS CLUSTER
> // SHOW REGIONS FOR DATABASE <database>
> ```

Should this be `FROM` DATABASE

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56627)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm)

___
*[pkg/sql/parser/sql.y, line 5127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56627#-MLywXoe5B2ALuxvrhse:-MLyypvG12b3Ab7tNXEx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b19543f27708b8678bc6be92543a773829fa22a/pkg/sql/parser/sql.y#L5127)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Should this be `FROM` CLUSTER?
</blockquote></details>

Done.
___
*[pkg/sql/parser/sql.y, line 5128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56627#-MLywahK0i3dw5NRxGHn:-MLyyqFN9z1X6yxzQgCX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b19543f27708b8678bc6be92543a773829fa22a/pkg/sql/parser/sql.y#L5128)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Should this be `FROM` DATABASE
</blockquote></details>

Done.

**Review by ajstorm — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56627#-:-MLyzl226-TTyGUzyqvV:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm)

**Comment by otan** [comment]
bors r=ajstorm

tftr!

**Comment by otan** [comment]
bors r=ajstorm

**Pull request merged**
