### PR TITLE
opt: support INSERT ON CONFLICT DO NOTHING with partial unique constraints

### PR DESCRIPTION
**Pull request by mgartner**
#### opt: move INSERT DO NOTHING arbiter code to mutation_builder_arbiter.go

Arbiter-related code in `pkg/sql/opt/optbuilder/insert.go` has grown
unruly due to the added complexity of partial indexes and unique
constraints. This commit moves some arbiter-related functions to a new
file to accommodate the growth. It also breaks some anonymous closures
into independent functions, for clarity.

Release note: None

#### opt: pass column ordinals directly to arbiter building functions

This commit makes the arguments of `buildAntiJoinForDoNothingArbiter` and
`buildDistinctOnForDoNothingArbiter` more intuitive. Columns ordinals
are now passed directly to these functions, rather than a column count
and ordinal-returning callback.

Release note: None

#### opt: create arbiterPredicateHelper for picking partial index arbiters

This commit adds a new helper struct that can determine if a partial
index can be used as an arbiter based on the arbiter predicate of an
`INSERT ON CONFLICT` statement. This will also be a useful utility to
determine if partial unique constraints can be used as arbiters.

Release note: None

#### opt: support INSERT ON CONFLICT DO NOTHING with partial unique constraints

To support INSERT ON CONFLICT DO NOTHING statements on tables with
partial UNIQUE WITHOUT INDEX constraints, partial constraints are now
selected as arbiters. These arbiters are used to filter out insert rows
that would conflict with existing rows in the table.

Informs #59195

There is no release note because these constraints are gated behind the
experimental_enable_unique_without_index_constraints session variable.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60680)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/optbuilder/insert.go, line 1343 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60680#-MTlghjH9ZQ7fDX-Edmc:-MTlghjH9ZQ7fDX-Edmd:b-ho9aeb) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a87f56941cd381b67af2084535269ad893b9535/pkg/sql/opt/optbuilder/insert.go#L1343)):*
> ```Go
> 	// predicates.
> 	var tableScope *scope
> 	initializeTableScopeOnce := func() {
> ```

[nit] these inline methods suggest this code could benefit from separating various routines in a helper
___
*[pkg/sql/opt/optbuilder/insert.go, line 1379 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60680#-MTlh438CP3aZn6bntff:-MTlh438CP3aZn6bntfg:bueldjb) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a87f56941cd381b67af2084535269ad893b9535/pkg/sql/opt/optbuilder/insert.go#L1379)):*
> ```Go
> 			var err error
> 			arbiterFilters, err = mb.b.buildPartialIndexPredicate(
> 				tabMeta, tableScope, arbiterPredicate, "arbiter predicate",
> ```

This is fragile, this function requires that `initializeTableScopeOnce` was called already. It would be more robust to obfuscate the variable (e.g. `tableScopeLazy`) and make the function `tableScope()` return the scope (and use that everywhere).

**Review by rytaft — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60680)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/opt/optbuilder/insert.go, line 1062 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60680#-MTlz-gvBC-UUU0-nUog:-MTlz-gvBC-UUU0-nUoh:b1qvll2) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a87f56941cd381b67af2084535269ad893b9535/pkg/sql/opt/optbuilder/insert.go#L1062)):*
> ```Go
> 		var partialIndexDistinctCol *scopeColumn
> 		if isPartial {
> 			alias := fmt.Sprintf("upsert_partial_index_distinct%d", idx)
> ```

[nit] I feel like it would be cleaner to just pass the type as a string (e.g., "index" or "constraint"), and construct the alias inside the function. Another option would be to pass the type as an enum with a `String()` method, but maybe that's overkill.
___
*[pkg/sql/opt/optbuilder/testdata/unique-checks-insert, line 1339 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60680#-MTm-TUb2LImzuM6JwaF:-MTm-TUb2LImzuM6JwaG:bwd3yba) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a87f56941cd381b67af2084535269ad893b9535/pkg/sql/opt/optbuilder/testdata/unique-checks-insert#L1339)):*
> ```
> insert uniq_partial_constraint_and_index
>  ├── columns: <none>
>  ├── arbiter constraints: unique_a
> ```

It's using the constraint, not the index
___
*[pkg/sql/opt/optbuilder/testdata/unique-checks-insert, line 1419 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60680#-MTm-Wap3OXbDdP4pVUW:-MTm-Wap3OXbDdP4pVUX:bdkjpo0) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a87f56941cd381b67af2084535269ad893b9535/pkg/sql/opt/optbuilder/testdata/unique-checks-insert#L1419)):*
> ```
> insert uniq_constraint_and_partial_index
>  ├── columns: <none>
>  ├── arbiter indexes: secondary
> ```

It's using the index, not the constraint

**Review by mgartner — COMMENTED** [review]
I did quite a bit of refactoring. If this totally screws up the review diff, let me know and I can open a new PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60680#-:-MTnGPXp5rloR1Qp5Z7T:b-75lp6x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/optbuilder/insert.go, line 1062 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60680#-MTlz-gvBC-UUU0-nUog:-MTnDBmu5A_AY5cafAKM:bpjaono) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a87f56941cd381b67af2084535269ad893b9535/pkg/sql/opt/optbuilder/insert.go#L1062)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] I feel like it would be cleaner to just pass the type as a string (e.g., "index" or "constraint"), and construct the alias inside the function. Another option would be to pass the type as an enum with a `String()` method, but maybe that's overkill.
</blockquote></details>

The function would still need `idx` to know the integer suffix. Are you suggesting passing just that?
___
*[pkg/sql/opt/optbuilder/insert.go, line 1343 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60680#-MTlghjH9ZQ7fDX-Edmc:-MTnDMk5C9OgloUGbcBG:baql0hh) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a87f56941cd381b67af2084535269ad893b9535/pkg/sql/opt/optbuilder/insert.go#L1343)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] these inline methods suggest this code could benefit from separating various routines in a helper
</blockquote></details>

Great point. I just did a pretty big refactoring of a lot of this arbiter code to facilitate this. Let me know what you think.
___
*[pkg/sql/opt/optbuilder/insert.go, line 1379 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60680#-MTlh438CP3aZn6bntff:-MTnDV42BjMbX9TyMAxv:b-irqrwv) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a87f56941cd381b67af2084535269ad893b9535/pkg/sql/opt/optbuilder/insert.go#L1379)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is fragile, this function requires that `initializeTableScopeOnce` was called already. It would be more robust to obfuscate the variable (e.g. `tableScopeLazy`) and make the function `tableScope()` return the scope (and use that everywhere).
</blockquote></details>

I think I've made this less fragile with the refactoring I've done. Unfortunately there's still 1 point of fragility in that we rely on the tableScope's Scan being built to retrieve partial index predicate from the Scan table's metadata. Notice the `h.tableScope()` in the `arbiterPredicateHelper.partialIndexPredicate` function. I'm open to ways to make this better, if you can think of any.

This was an optimization to reduce rebuilding partial index predicates unnecessarily that was added here: https://github.com/cockroachdb/cockroach/pull/59879/commits/8b7cf44930aef4a5dfcc37a84e8e331f297c71d9
___
*[pkg/sql/opt/optbuilder/testdata/unique-checks-insert, line 1339 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60680#-MTm-TUb2LImzuM6JwaF:-MTnFh779dBCtK-fE5qx:b-y06o7s) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a87f56941cd381b67af2084535269ad893b9535/pkg/sql/opt/optbuilder/testdata/unique-checks-insert#L1339)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

It's using the constraint, not the index
</blockquote></details>

This baffled me for a while, until I realized that we have to use the `norm` directive so that the predicates are fully normalized, otherwise `pred.IsTrue()`, which we use to check for pseudo-partial indexes and constraints,  won't work. Fixed.
___
*[pkg/sql/opt/optbuilder/testdata/unique-checks-insert, line 1419 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60680#-MTm-Wap3OXbDdP4pVUW:-MTnG7TB09BUWqVgUmvn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a87f56941cd381b67af2084535269ad893b9535/pkg/sql/opt/optbuilder/testdata/unique-checks-insert#L1419)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

It's using the index, not the constraint
</blockquote></details>

Done.

**Review by rytaft — COMMENTED** [review]
Nice cleanup!

> Reviewed 6 of 6 files at r2, 7 of 7 files at r3, 2 of 2 files at r4, 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60680#-:-MTpCCVrBzHMQqyCnype:b7oy6or)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/optbuilder/insert.go, line 1062 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60680#-MTlz-gvBC-UUU0-nUog:-MTp2eOK63l7niz9gUJz:b-v7y3ub) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a87f56941cd381b67af2084535269ad893b9535/pkg/sql/opt/optbuilder/insert.go#L1062)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

The function would still need `idx` to know the integer suffix. Are you suggesting passing just that?
</blockquote></details>

I see, sure, you could pass that too. But I don't feel too strongly -- if you don't feel like it's cleaner feel free to ignore. (you could also theoretically make a different alias, right? with the index/constraint name or something?)
___
*[pkg/sql/opt/optbuilder/insert.go, line 758 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/60680#-MTpAQviB1wqP9vnR5PQ:-MTpAQviB1wqP9vnR5PR:b-tcnkom) ([raw file](https://github.com/cockroachdb/cockroach/blob/80dab3b2eeae044bdf1d7beb970385c6020aac0a/pkg/sql/opt/optbuilder/insert.go#L758)):*
> ```Go
> 			partialIndexDistinctCol,
> 		)
> ```

[nit] extra line
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 192 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/60680#-MTp6aqD6ASqbZJIOun0:-MTp6aqEBL-w1xM3uy2D:b-jwt7ab) ([raw file](https://github.com/cockroachdb/cockroach/blob/654c197b3b9942125cd7e45bd23d1c09026abca2/pkg/sql/opt/optbuilder/mutation_builder.go#L192)):*
> ```Go
> 	uniqueCheckHelper uniqueCheckHelper
> 
> 	// arbiterHelper is used to prevent allocating the helper separately.
> ```

arbiterHelper -> arbiterPredicateHelper
___
*[pkg/sql/opt/optbuilder/mutation_builder_arbiter.go, line 287 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60680#-MTp4cA35F6n396vaqgg:-MTp4cA35F6n396vaqgh:b-wfxdjw) ([raw file](https://github.com/cockroachdb/cockroach/blob/93515dba875f98b02d4d6ba1cb11651509d90234/pkg/sql/opt/optbuilder/mutation_builder_arbiter.go#L287)):*
> ```Go
> }
> 
> // buildInputForDoNothingArbiter builds the input for a single arbiter index or
> ```

name doesn't match function name. I think this whole comment may be mismatched....
___
*[pkg/sql/opt/optbuilder/mutation_builder_arbiter.go, line 339 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/60680#-MTp7JhA0AZIZ6nMRtSg:-MTp7JhA0AZIZ6nMRtSh:bbfzmz9) ([raw file](https://github.com/cockroachdb/cockroach/blob/654c197b3b9942125cd7e45bd23d1c09026abca2/pkg/sql/opt/optbuilder/mutation_builder_arbiter.go#L339)):*
> ```Go
> 	tableScopeLazy *scope
> 
> 	// arbiterFilters is a lazily initialized scalar expression that represents
> ```

arbiterFilters -> arbiterFiltersLazy

[nit] what does "represents" mean in this context? maybe "is the result of building arbiterPredicate"?
___
*[pkg/sql/opt/optbuilder/mutation_builder_arbiter.go, line 372 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/60680#-MTp84Kf6TqQ2c79RUy-:-MTp84Kf6TqQ2c79RUy0:b-tcnkom) ([raw file](https://github.com/cockroachdb/cockroach/blob/654c197b3b9942125cd7e45bd23d1c09026abca2/pkg/sql/opt/optbuilder/mutation_builder_arbiter.go#L372)):*
> ```Go
> 			h.mb.b.allocScope(),
> 		)
> ```

[nit] extra line
___
*[pkg/sql/opt/optbuilder/mutation_builder_arbiter.go, line 381 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/60680#-MTp8O1S78nbQbqw520m:-MTp8O1S78nbQbqw520n:bw4ebfa) ([raw file](https://github.com/cockroachdb/cockroach/blob/654c197b3b9942125cd7e45bd23d1c09026abca2/pkg/sql/opt/optbuilder/mutation_builder_arbiter.go#L381)):*
> ```Go
> // catalog, it fetches the predicates from the table metadata. These predicates
> // are populated when the Scan expression is built for the tableScope. This
> // eliminate unnecessarily rebuilding partial index predicate expressions.
> ```

eliminates
___
*[pkg/sql/opt/optbuilder/mutation_builder_arbiter.go, line 397 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/60680#-MTp8xWr5zsrP8eJb8HL:-MTp8xWs8-ohZ0_ewusW:b-juaff0) ([raw file](https://github.com/cockroachdb/cockroach/blob/654c197b3b9942125cd7e45bd23d1c09026abca2/pkg/sql/opt/optbuilder/mutation_builder_arbiter.go#L397)):*
> ```Go
> 	// The filters have been initialized if they are non-nil or
> 	// invalidArbiterPredicate has been set to true.
> 	arbiterFiltersInitialized := h.arbiterFiltersLazy != nil || h.invalidArbiterPredicate
> ```

if we already know that the arbiter predicate is invalid, why are we trying to build it again? won't we just get the same result?
___
*[pkg/sql/opt/optbuilder/mutation_builder_arbiter.go, line 195 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/60680#-MTpBOST9Iu_KiQj6n2Y:-MTpBOST9Iu_KiQj6n2Z:b9y0u5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/80dab3b2eeae044bdf1d7beb970385c6020aac0a/pkg/sql/opt/optbuilder/mutation_builder_arbiter.go#L195)):*
> ```Go
> //     guarantees uniqueness of.
> // 	 - pred is the partial index predicate. If the arbiter is not a partial
> //     index, pred is nil.
> ```

[nit] index or constraint
___
*[pkg/sql/opt/optbuilder/testdata/unique-checks-insert, line 1339 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60680#-MTm-TUb2LImzuM6JwaF:-MTpBthR5q5sirvGywyF:bd4svmy) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a87f56941cd381b67af2084535269ad893b9535/pkg/sql/opt/optbuilder/testdata/unique-checks-insert#L1339)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This baffled me for a while, until I realized that we have to use the `norm` directive so that the predicates are fully normalized, otherwise `pred.IsTrue()`, which we use to check for pseudo-partial indexes and constraints,  won't work. Fixed.
</blockquote></details>

good find!

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60680)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/optbuilder/insert.go, line 1062 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60680#-MTlz-gvBC-UUU0-nUog:-MTqI13rAz_wSuHOearc:bayg939) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a87f56941cd381b67af2084535269ad893b9535/pkg/sql/opt/optbuilder/insert.go#L1062)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I see, sure, you could pass that too. But I don't feel too strongly -- if you don't feel like it's cleaner feel free to ignore. (you could also theoretically make a different alias, right? with the index/constraint name or something?)
</blockquote></details>

I like that idea. I added a new commit that uses the index or constraint name instead.
___
*[pkg/sql/opt/optbuilder/insert.go, line 758 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/60680#-MTpAQviB1wqP9vnR5PQ:-MTqAEdfDvQB6GpdpIT_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/80dab3b2eeae044bdf1d7beb970385c6020aac0a/pkg/sql/opt/optbuilder/insert.go#L758)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] extra line
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/mutation_builder.go, line 192 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/60680#-MTp6aqD6ASqbZJIOun0:-MTq5wox4idDPI3HuUOb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/654c197b3b9942125cd7e45bd23d1c09026abca2/pkg/sql/opt/optbuilder/mutation_builder.go#L192)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

arbiterHelper -> arbiterPredicateHelper
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/mutation_builder_arbiter.go, line 287 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60680#-MTp4cA35F6n396vaqgg:-MTq76LP1xslkkruzI4N:bmtreqm) ([raw file](https://github.com/cockroachdb/cockroach/blob/93515dba875f98b02d4d6ba1cb11651509d90234/pkg/sql/opt/optbuilder/mutation_builder_arbiter.go#L287)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

name doesn't match function name. I think this whole comment may be mismatched....
</blockquote></details>

Good catch. Must have mucked this up during some rebasing. Fixed.
___
*[pkg/sql/opt/optbuilder/mutation_builder_arbiter.go, line 339 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/60680#-MTp7JhA0AZIZ6nMRtSg:-MTq7ddg5pNRB0haVxV7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/654c197b3b9942125cd7e45bd23d1c09026abca2/pkg/sql/opt/optbuilder/mutation_builder_arbiter.go#L339)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

arbiterFilters -> arbiterFiltersLazy

[nit] what does "represents" mean in this context? maybe "is the result of building arbiterPredicate"?
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/mutation_builder_arbiter.go, line 372 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/60680#-MTp84Kf6TqQ2c79RUy-:-MTq7s-i9eTOJEMsyVpw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/654c197b3b9942125cd7e45bd23d1c09026abca2/pkg/sql/opt/optbuilder/mutation_builder_arbiter.go#L372)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] extra line
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/mutation_builder_arbiter.go, line 381 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/60680#-MTp8O1S78nbQbqw520m:-MTq7zKi9jPKCvRgYYtH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/654c197b3b9942125cd7e45bd23d1c09026abca2/pkg/sql/opt/optbuilder/mutation_builder_arbiter.go#L381)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

eliminates
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/mutation_builder_arbiter.go, line 397 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/60680#-MTp8xWr5zsrP8eJb8HL:-MTq83cs4On-gB02BQ-c:bsyu10r) ([raw file](https://github.com/cockroachdb/cockroach/blob/654c197b3b9942125cd7e45bd23d1c09026abca2/pkg/sql/opt/optbuilder/mutation_builder_arbiter.go#L397)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

if we already know that the arbiter predicate is invalid, why are we trying to build it again? won't we just get the same result?
</blockquote></details>

If it's invalid then we won't try to build again because `arbiterFiltersInitialized` will be `true`, and we check `if !arbiterFiltersInitialized` below. This is confusing tho, maybe due to some double or triple negatives. This version was the least evil that I could come up with though.
___
*[pkg/sql/opt/optbuilder/mutation_builder_arbiter.go, line 195 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/60680#-MTpBOST9Iu_KiQj6n2Y:-MTqAm3h5vld-RXMFFVu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/80dab3b2eeae044bdf1d7beb970385c6020aac0a/pkg/sql/opt/optbuilder/mutation_builder_arbiter.go#L195)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] index or constraint
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 10 of 10 files at r6, 7 of 7 files at r7, 2 of 2 files at r8, 5 of 5 files at r9, 5 of 5 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60680#-:-MTqQOa796Ae8Q2OgCpY:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/optbuilder/insert.go, line 956 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/60680#-MTqQ6qX73kCaiVlXjQa:-MTqQ6qX73kCaiVlXjQb:b-lrpgqw) ([raw file](https://github.com/cockroachdb/cockroach/blob/83d8bedaa23a5886b82e836025905708317713ee/pkg/sql/opt/optbuilder/insert.go#L956)):*
> ```Go
> 		var partialIndexDistinctCol *scopeColumn
> 		if isPartial {
> 			alias := fmt.Sprintf("upsert_partial_index_distinct%d", idx)
> ```

[nit] change this one to pass the index name too
___
*[pkg/sql/opt/optbuilder/mutation_builder_arbiter.go, line 397 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/60680#-MTp8xWr5zsrP8eJb8HL:-MTqOvgl8ZnsdRPs1F3d:b89rdmy) ([raw file](https://github.com/cockroachdb/cockroach/blob/654c197b3b9942125cd7e45bd23d1c09026abca2/pkg/sql/opt/optbuilder/mutation_builder_arbiter.go#L397)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

If it's invalid then we won't try to build again because `arbiterFiltersInitialized` will be `true`, and we check `if !arbiterFiltersInitialized` below. This is confusing tho, maybe due to some double or triple negatives. This version was the least evil that I could come up with though.
</blockquote></details>

Oh I see -- yep, sorry I confused myself. I think this is fine.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60680)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/optbuilder/insert.go, line 956 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/60680#-MTqQ6qX73kCaiVlXjQa:-MTqU6nv0_sPKus1dhdi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83d8bedaa23a5886b82e836025905708317713ee/pkg/sql/opt/optbuilder/insert.go#L956)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] change this one to pass the index name too
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 2 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60680)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @RaduBerinde)

**Review by RaduBerinde — APPROVED** [review]
:lgtm: Very nice cleanup!

> Reviewed 1 of 10 files at r6, 3 of 7 files at r7, 1 of 2 files at r8, 1 of 5 files at r9, 5 of 5 files at r13.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60680#-:-MTsDzVW6gsEwzN-HFpG:b-d1xu7v)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/optbuilder/mutation_builder_arbiter.go, line 429 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/60680#-MTsDHTf3nwepH8NrdW2:-MTsDHTf3nwepH8NrdW3:b-f6xiee) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c03864b14cba73b113867102ba274f727d8c11f/pkg/sql/opt/optbuilder/mutation_builder_arbiter.go#L429)):*
> ```Go
> 	// Initialize the Implicator once.
> 	if h.im == nil {
> 		h.im = &partialidx.Implicator{}
> ```

[nit] Any reason `im` has to be a pointer? (btw it's ok to call Init every time since it doesn't do much)

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60680)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/optbuilder/mutation_builder_arbiter.go, line 429 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/60680#-MTsDHTf3nwepH8NrdW2:-MTvIkeB366PPR1_n3Ee:b9mza5v) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c03864b14cba73b113867102ba274f727d8c11f/pkg/sql/opt/optbuilder/mutation_builder_arbiter.go#L429)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] Any reason `im` has to be a pointer? (btw it's ok to call Init every time since it doesn't do much)
</blockquote></details>

Nope, good catch. Fixed.

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
