### PR TITLE
sql/parser: parse (but do not interpret) column families on secondary indexes

### PR DESCRIPTION
**Pull request by rohany**
Work towards #41964.

Adding column family support onto secondary indexes is important for making
primary keys "less unique". This work is necessary to enable primary key
changes within cockroachdb. This PR adds syntax only support for column
families on secondary indexes, using the following syntax:

```sql
CREATE INDEX b(x) STORING (y, FAMILY fy(y), z, FAMILY fz(z))
```

The idea here is that column families are related to the columns that the
secondary index is storing, so it is natural to group the concepts syntactically.

This PR includes @knz's contributions in updating the syntax from the original version.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Sorry if this was already discussed, but why do we want different indexes to have different column families? In what circumstances would you want to separate a column (or subset of columns) in a family in only some indexes?

To me a column family is a table concept, roughly saying "I want to be able to modify this column without interacting with accesses on other columns". All indexes should respect the column families.

Specifying families per index leads to a lot of complexity in the schema and as a user it would leave me scratching my head. It is similar to the partitioning syntax issues we've been discussing where you have to specify the same thing over and over. There had better be a very strong reason to go this route.

**Comment by RaduBerinde** [comment]
CC @nvanbenschoten who probably knows the most about performance characteristics of column families.

**Comment by rohany** [comment]
In most cases you won’t want them to have families, but column families need to be added to secondary indexes to allow for primary key changes — when the primary key has changed, it must be possible to interpret the old primary index (with families) as a secondary index without rewriting the old primary index. We’re open to ideas about how the syntax should look, but it seems like we need some way to give indexes column families to allow for future work.

**Comment by knz** [comment]
I'm :+1: on stopping to reason about primary indexes being special. Whatever feature is available to a PK should be available to a secondary index too.

**Comment by RaduBerinde** [comment]
My point is that all indexes should respect the same families (I thought I was pretty clear above). Can you explain more why "in most cases you won't want secondary indexes to have families"?

I think introducing new syntax here should go through the RFC process, as it's something that's very hard to undo later.

**Review by knz — COMMENTED** [review]
Thanks for the work btw.
A couple of things:
- clarify the commit title, see my change to the PR title
- replace "adds syntax only"  in the commit message by "adds parsing support for" and then extend with a message "attempts by clients to use this syntax will still be rejected by a 'feature unsupported' error" to clarify the current behavior.
- the syntax choice is problematic. I think this new FAMILIES keyword should not exist at all. I am moving for an alternate proposal, which I have prototyped on top of your branch here: https://github.com/rohany/cockroach/pull/1

Please inspect this and tell us what you think (and consider going the RFC route).

> Reviewed 2 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41965#-:-LsLwaD1DGVYGtI82Wzo:b-qmyt75)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @solongordon)

**Comment by rohany** [comment]
Thanks for the discussions — let me take a look at that branch. I remember running into some shift reduce conflicts without the families keyword, which is why I included it.

Yes, Solon and I will have a bigger rfc out for primary key changes, and this will be discussed in there.

**Comment by RaduBerinde** [comment]
> > My point is that all indexes should respect the same families (I thought I was pretty clear above)

> If that were the case, it would be impossible to change the families when one goes from one PK to another. Or do you see another mechanism?

The families (as a concept in the schema) would be a higher level thing and wouldn't change. `FAMILY fam (c)` would simply mean "keep values of `c` separated from other values as much as possible", and that can continue to mean the same thing when you change the PK. The concept applies equally well to any index. Of course, how that concept gets translated to the underlying key/value representation will depend on the index and the PK, but we can figure out those details automatically, rather than relying on the user dictating the exact encoding of each index.

**Comment by rohany** [comment]
It feels like families should be a separation of the stored columns of an index — I can try and work out some details of what it would look like if every index had the same family setup as the primary key.

**Comment by knz** [comment]
If you start comparing alternatives and weighing pros and cons then for the sake of transparency please lay down your arguments side by side in writing. (Somewhere under docs/? I suppose we have a place for this type of comparison already?)
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by danhhz** [comment]
I agree with radu here. Families should be something defined at the table level, not the index level. I also agree that this PR needs to wait on the RFC.

> If that were the case, it would be impossible to change the families when one goes from one PK to another. Or do you see another mechanism?

Why does this have to be tied to a PK change? A column's family can be changed by adding a computed column that's the value of the old column, then once the backfill is complete, swapping the name and dropping the old column. (Though now that I mention it, this sounds like a good thing to automate under some sort of ALTER TABLE).

**Comment by nvanbenschoten** [comment]
> To me a column family is a table concept, roughly saying "I want to be able to modify this column without interacting with accesses on other columns". All indexes should respect the column families.

I agree with this pretty strongly with @RaduBerinde. I can't think of a single scenario where a user would want to have different column families in different indexes for the same table. Doing so would lead to a strange coupling between index selection, contention, and read amplification. It would also allow an index using poorly constructed column family spec to eliminate the write amplification benefit that a well-thought-out column family spec on a different index could provide.

Secondary indexes that don't respect column families already cause some of these kinds of issues, which is a pretty big gotcha with column families. We should push to respect a single table-level column family specification across all of a table's indexes.

**Comment by andy-kimball** [comment]
+1 to what Radu and Nathan have said. Allowing indexes to have their own column family specifications would add a great deal of additional complexity to a feature that is already complex enough. Our goal should be to make all indexes have the _same_ structure (by having all indexes follow the same column family spec), not to allow them to diverge even further than today (by allowing indexes to use whatever column family spec they like).

**Pull request closed without merging**
