### PR TITLE
schemachanger: support idx zone config

### LINKED ISSUE #128594: schemachanger: add support for subzone, subzonespan changes
When we model index/partition changes as its own element -- separate from the table zone config these subzones belong in -- we need to add proper logic to update our zone config.

This includes writing a new method during `exec_deps` that will retrieve the table config of an index/partition (if exists), and properly merge the existing subzones/subzone spans into the table zone config before we write these changes to KV.

For subzones, a method exists already, as the unique identifier of `(indexID, PartitionName)` allows us to replace a subzone at index `x` where IndexID = toReplaceIndexID and PartitionName = toReplacePartitionName.

For subzone spans, it seems like we can model these as an ADD if new subzones are getting added for the particular index/partition

Jira issue: CRDB-41096

### LINKED ISSUE #129887: Implement ALTER INDEX ... CONFIGURE ZONE USING ... in declarative schema changer
This issue tracks our progress of supporting zone configs in declarative schema changer and let's concretize it into implementing ALTER INDEX ... CONFIGURE ZONE stmt in declarative schema changer.

Epic: [CRDB-31473](https://cockroachlabs.atlassian.net/browse/CRDB-31473)

### PR DESCRIPTION
**Pull request by annrpom**
### scpb: modify IndexZoneConfig element
This commit modifies the IndexZoneConfig element
that will become relevant for supporting
`ALTER INDEX ... CONFIGURE ZONE` in the DSC.

Release note: None

---

### schemachanger/scexec: add support for writing subzone configs
This patch adds support for writing subzone configs.

Informs: https://github.com/cockroachdb/cockroach/issues/117574
Fixes: #128594
Release note: None

---

### schemachanger: add idx zone config opgen rule
This patch adds an opgen rule for idx zone configs
in the ADD direction, along with the logic to configure
replication controls on an index.

Informs: https://github.com/cockroachdb/cockroach/issues/117574
Release note: None

Fixes: #129887

### CODE REVIEW

**Comment by annrpom** [comment]
Let me open this up for comments while I fix tests & transactional behavior

**Review by spilchen — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 5 of 5 files at r2, 21 of 21 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126128)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom and @fqazi)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go` line 521 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126128#-O1NuSjwBwldVsgOZEUs:-O1NuSjwBwldVsgOZEUt:b-1w522j) ([raw file](https://github.com/cockroachdb/cockroach/blob/b17b6d78a8ac394828f1f9db9de8a3f5cfd95670/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go#L521)):*
> ```Go
> 			partialZone.CopyFromZone(zoneInheritedFields, copyFromParentList)
> 		} else {
> 			// If we are operating on a subZone, we need to inherit all remaining
> ```

Do we have any general guidelines on the size of functions? `applyZoneConfig` is getting quite big now. I wonder if it makes sense to split it up somehow.
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go` line 777 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126128#-O1Nv2i4CumQGPq_ObLa:-O1Nv2i4CumQGPq_ObLb:bxzkx9i) ([raw file](https://github.com/cockroachdb/cockroach/blob/b17b6d78a8ac394828f1f9db9de8a3f5cfd95670/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go#L777)):*
> ```Go
> 			// We want to get the most recent change that has not applied yet. For transactions, this will
> 			// be the most recent (last) zone config elem added.
> 			if e.TableID == targetID && e.IndexID == idxID {
> ```

Haven't we already filtered by `targetID` with `b.QueryByID`?  Also, would it be better to have a reusable filter function for the index ID? Assuming there are other places where we could make use of it.
___
*[`pkg/sql/schemachanger/scexec/scmutationexec/index.go` line 503 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126128#-O1NxLtAELZh_a9AAynq:-O1NxLtAELZh_a9AAynr:bjomqzj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b17b6d78a8ac394828f1f9db9de8a3f5cfd95670/pkg/sql/schemachanger/scexec/scmutationexec/index.go#L503)):*
> ```Go
> func (i *immediateVisitor) AddIndexZoneConfig(
> 	ctx context.Context, op scop.AddIndexZoneConfig,
> ) error {
> ```

nit: does it make sense to return an error since it will always be `nil`?

**Review by annrpom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126128)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @spilchen)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go` line 521 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126128#-O1NuSjwBwldVsgOZEUs:-O1ShMxH1v0Ko-Ci2NAI:bmb2sps) ([raw file](https://github.com/cockroachdb/cockroach/blob/b17b6d78a8ac394828f1f9db9de8a3f5cfd95670/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go#L521)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Do we have any general guidelines on the size of functions? `applyZoneConfig` is getting quite big now. I wonder if it makes sense to split it up somehow.
</blockquote></details>

yeah; i agree it's getting quite large. we have a helpers.go for the `scbuildstmt` pkg and i don't see anything wrong with moving stuff to a new zone_config_helpers,go file. let me do that. that will also help out on my subzone spans additions (i could probably just separate these changes out into a new PR)
___
*[`pkg/sql/schemachanger/scexec/scmutationexec/index.go` line 503 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126128#-O1NxLtAELZh_a9AAynq:-O1Sh1mi8FXCMb2lNKnH:bvbsij8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b17b6d78a8ac394828f1f9db9de8a3f5cfd95670/pkg/sql/schemachanger/scexec/scmutationexec/index.go#L503)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

nit: does it make sense to return an error since it will always be `nil`?
</blockquote></details>

true -- now that i don't checkout any descriptor, i don't need this anymore

**Review by fqazi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 5 of 5 files at r2, 21 of 21 files at r4, 24 of 24 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126128)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom and @spilchen)

___
*[`pkg/sql/schemachanger/scexec/scmutationexec/index.go` line 501 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126128#-O1SiHZ24FvxQvhYC_bS:-O1SiHZ24FvxQvhYC_bT:b-2m63hw) ([raw file](https://github.com/cockroachdb/cockroach/blob/efbe18dcc858043d7414905c2df9f3e044139847/pkg/sql/schemachanger/scexec/scmutationexec/index.go#L501)):*
> ```Go
> }
> 
> // TODO
> ```

Nit: clean up
___
*[`pkg/sql/schemachanger/scexec/scmutationexec/index.go` line 504 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/126128#-O1SkJiI1OT3HBy0x71I:-O1SkJiI1OT3HBy0x71J:b-bmipst) ([raw file](https://github.com/cockroachdb/cockroach/blob/18be3d3409c825b2f9d670c0ae8d003d8312e87b/pkg/sql/schemachanger/scexec/scmutationexec/index.go#L504)):*
> ```Go
> 	ctx context.Context, op scop.AddIndexZoneConfig,
> ) error {
> 	i.ImmediateMutationStateUpdater.UpdateZoneConfig(op.TableID, *op.ZoneConfig)
> ```

I guess the zone config here encodes the entire tables zone config with the all the indexes? If we have multiple index zone configs how does everything layer (i.e. imagine I have a table with two sub zones)? Mentally I was expecting this part to be just the subzone bits for that index, so it sort of acts like inheritance.

**Review by annrpom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126128)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @spilchen)

___
*[`pkg/sql/schemachanger/scexec/scmutationexec/index.go` line 501 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126128#-O1SiHZ24FvxQvhYC_bS:-O1SlN1o1IldVMTx184K:b-57xpcd) ([raw file](https://github.com/cockroachdb/cockroach/blob/efbe18dcc858043d7414905c2df9f3e044139847/pkg/sql/schemachanger/scexec/scmutationexec/index.go#L501)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Nit: clean up
</blockquote></details>

ok will do ty for catching
___
*[`pkg/sql/schemachanger/scexec/scmutationexec/index.go` line 504 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/126128#-O1SkJiI1OT3HBy0x71I:-O1SlOo-4qQZqvaB0NWX:b-gfy289) ([raw file](https://github.com/cockroachdb/cockroach/blob/18be3d3409c825b2f9d670c0ae8d003d8312e87b/pkg/sql/schemachanger/scexec/scmutationexec/index.go#L504)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

I guess the zone config here encodes the entire tables zone config with the all the indexes? If we have multiple index zone configs how does everything layer (i.e. imagine I have a table with two sub zones)? Mentally I was expecting this part to be just the subzone bits for that index, so it sort of acts like inheritance.
</blockquote></details>

i agree -- i was approaching this change a bit mechanically (so like db, tbl), but while I was going through configure_zone updates, i actually do think it makes more sense for this to be the subzone bits. let me do that

**Review by spilchen — COMMENTED** [review]
> Reviewed 27 of 27 files at r6, 4 of 4 files at r7, 26 of 26 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126128)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom and @fqazi)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go` line 359 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/126128#-O1vVIgLDGXBAxC4T4Lp:-O1vVIgLDGXBAxC4T4Lq:bc0xglv) ([raw file](https://github.com/cockroachdb/cockroach/blob/693ab1b8ed8d3bcc3496bc4214f6b36be87a6997/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go#L359)):*
> ```Go
> }
> 
> func applyZoneConfig(
> ```

I think this was just copied from configure_zone.go from the prior commit. But I still feel like this function is too big and handles too many cases. One idea to make it small, and easier to understand, is to create two variants of the function: one for tables and one for index/partitions. This eliminates a lot of the `indexID != 0` checks. For the bits that are duplicated in both functions, they can be added to helper functions that each variant call.

Or if you want to keep one function, an alternative is to implement the template method pattern. You basically have one version of the function. The parts that need to do stuff different if it's for an index or not are handled in separate functions that this function calls.
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go` line 376 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/126128#-O1vYC6zEAdfLN2wF3wc:-O1vYC6zEAdfLN2wF3wd:b-h1a5d0) ([raw file](https://github.com/cockroachdb/cockroach/blob/693ab1b8ed8d3bcc3496bc4214f6b36be87a6997/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go#L376)):*
> ```Go
> 	// we will need to guard against secondary tenants from configuring such
> 	// ranges.
> 	if objType == tableObj {
> ```

Should we check against configuring zones for indexes on system tables?

**Review by spilchen — COMMENTED** [review]
Thanks for trying to refactor `zone_config_helpers.go`. I think what you have is fine.

> Reviewed 29 of 29 files at r9, 8 of 8 files at r10, 4 of 4 files at r11, 2 of 23 files at r12, 6 of 40 files at r17, 8 of 8 files at r18, 4 of 4 files at r19, 25 of 25 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126128#-:-O397f1Y50wN44gDdHn7:b-px0t6q)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom and @fqazi)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go` line 504 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/126128#-O395EXLDc4lu5TTxqIB:-O395EXM2jOFw-Sg9F5T:b-epz8cq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fb78e06d4a875a4ca05e405dc23e28c07e00baf/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go#L504)):*
> ```Go
> 		// NumReplicas field, set it to nil so that the zone isn't considered a
> 		// placeholder anymore.
> 		if partialZone.IsSubzonePlaceholder() {
> ```

Comparing with the old code, we would make the partial zone not a placeholder anymore if `zc != nil`. Not sure if it matters here, but wanted to make sure this change was intentional.



_Suggestion:_
```Go
if zc != nil && partialZone.IsSubzonePlaceholder() {
```
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go` line 932 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/126128#-O397DII6GUyAS7tp1H1:-O397DII6GUyAS7tp1H2:b-ocz263) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fb78e06d4a875a4ca05e405dc23e28c07e00baf/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go#L932)):*
> ```Go
> 					subzones = e.Subzones
> 					seqNum = e.SeqNum
> 					targetID = 0
> ```

Is there a dependency on the order of the elements? What if an earlier iteration had already seen the `TableZoneConfig` for this table? The `zone` variable would be set. But if it comes after, then `zone` remains nil.
___
*[`pkg/sql/schemachanger/scop/immediate_mutation.go` line 910 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/126128#-O25AXZz2aYVipBt5hSj:-O25AXZz2aYVipBt5hSk:b-f4xz9u) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba36cf64e424a13adbd200b51625c7967c230d13/pkg/sql/schemachanger/scop/immediate_mutation.go#L910)):*
> ```Go
> 	Subzones     []zonepb.Subzone
> 	SubzoneSpans []zonepb.SubzoneSpan
> 	SeqNum       uint32
> ```

Is the `SeqNum` required in the op?

**Review by annrpom — COMMENTED** [review]
i have another idea to refactor -- the changes are in a draft at https://github.com/cockroachdb/cockroach/pull/129065/commits/5eeeb4ce6fbf7864df23983add32de5646af1338, but i'll get those changes up after this PR is merged

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126128#-:-O4LnY5S6_2wvMWUAHDf:b-fffsvi)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @spilchen)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go` line 359 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/126128#-O1vVIgLDGXBAxC4T4Lp:-O21BiJz4WMGF9rEUgU_:bn82g8u) ([raw file](https://github.com/cockroachdb/cockroach/blob/693ab1b8ed8d3bcc3496bc4214f6b36be87a6997/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go#L359)):*
> I think this was just copied from configure\_zone.go from the prior commit

Fixed -- this one escaped me after I moved things over to zone_config_helpers
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go` line 376 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/126128#-O1vYC6zEAdfLN2wF3wc:-O21DFZ_-unPXEErvbUJ:b-4yvgcy) ([raw file](https://github.com/cockroachdb/cockroach/blob/693ab1b8ed8d3bcc3496bc4214f6b36be87a6997/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go#L376)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Should we check against configuring zones for indexes on system tables?
</blockquote></details>

right -- this doesn't need to object type guard. i dug into this a bit more and found out that this check is a bit too late as well -- ensureDescriptor ends up getting called in order to resolve the physical table (ResolvePhysicalTable) to get the targetID. this ends up in [https://github.com/cockroachdb/cockroach/blob/39a064df78c890bf6fbf6ec2efff3b88d5348ea5/pkg/sql/schemachanger/scbuild/builder_state.go#L1500-L1511](https://github.com/cockroachdb/cockroach/blob/39a064df78c890bf6fbf6ec2efff3b88d5348ea5/pkg/sql/schemachanger/scbuild/builder_state.go#L1504-L1506)

so ultimately, we fallback to the legacy

i think the most i will do here for the time being is track it in the comments since #125882 seems related and more work different from this PR, but it seems *fine* to fallback to lsc in this case considering that it is just a matter of returning an error
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go` line 504 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/126128#-O395EXLDc4lu5TTxqIB:-O4GUEs_8C6501X0DXK9:b-93s6wl) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fb78e06d4a875a4ca05e405dc23e28c07e00baf/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go#L504)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Comparing with the old code, we would make the partial zone not a placeholder anymore if `zc != nil`. Not sure if it matters here, but wanted to make sure this change was intentional.
</blockquote></details>

Thanks for the callout! This change was intentional -- this nil check is not needed anymore
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go` line 932 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/126128#-O397DII6GUyAS7tp1H1:-O4Lo2eJ8smmJ356YCMB:b-mnnirz) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fb78e06d4a875a4ca05e405dc23e28c07e00baf/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go#L932)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Is there a dependency on the order of the elements? What if an earlier iteration had already seen the `TableZoneConfig` for this table? The `zone` variable would be set. But if it comes after, then `zone` remains nil.
</blockquote></details>

There is a dependency on the order of elements here -- I can write a comment to make this more apparent. Let me see if I can do something else about this
___
*[`pkg/sql/schemachanger/scop/immediate_mutation.go` line 910 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/126128#-O25AXZz2aYVipBt5hSj:-O4GmhdiCQWu3a6GwuyC:bss4a1y) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba36cf64e424a13adbd200b51625c7967c230d13/pkg/sql/schemachanger/scop/immediate_mutation.go#L910)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Is the `SeqNum` required in the op?
</blockquote></details>

Removed!

**Comment by annrpom** [comment]
Almost RFAL -- I'll ping once ready

**Comment by annrpom** [comment]
> There is a dependency on the order of elements here -- I can write a comment to make this more apparent. Let me see if I can do something else about this

Actually, this should have been doing what retrievePartialZoneConfig was doing

The current suite of tests has to do with EXPLAINing an index zone config change. The DSC will throw out an error `ERROR: use of replication zones on indexes or partitions requires an enterprise license. see https://cockroachlabs.com/pricing for details on how to enable enterprise features`, but the legacy does not

I'm wondering how this pans out with https://cockroachlabs.slack.com/archives/C07GE2Q1QN8/p1724089719368749

These changes are RFAL

**Review by spilchen — COMMENTED** [review]
Looks good. I just had a follow-up question and a few nits.

> Reviewed 42 of 42 files at r25, 7 of 8 files at r26, 34 of 34 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126128#-:-O4kjxJP5MElZkk3yZMD:bddwa3o)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom and @fqazi)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go` line 932 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/126128#-O397DII6GUyAS7tp1H1:-O4kh1vZ6ywAmUFwULg1:bq2kx8y) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fb78e06d4a875a4ca05e405dc23e28c07e00baf/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go#L932)):*
<details><summary><i>Previously, annrpom (annie pompa) wrote…</i></summary><blockquote>

There is a dependency on the order of elements here -- I can write a comment to make this more apparent. Let me see if I can do something else about this
</blockquote></details>

Where is the dependency enforced? Is it just based on how how the elements are created in scdecomp?
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go` line 1646 at r27](https://reviewable.io/reviews/cockroachdb/cockroach/126128#-O4kjJk3BtOPqFbqexFk:-O4kjJk3BtOPqFbqexFl:b-rjmbv0) ([raw file](https://github.com/cockroachdb/cockroach/blob/494e890c4053d7391e9dbcc181ec451b79c694ff/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go#L1646)):*
> ```Go
> }
> 
> func mustRetrieveIndexColumnElements(
> ```

nit: can we move this function to schemachanger/scbuild/internal/scbuildstmt/helpers.go? It doesn't seem specific to index zone.
___
*[`pkg/sql/schemachanger/scpb/element_collection.go` line 158 at r27](https://reviewable.io/reviews/cockroachdb/cockroach/126128#-O4kiAijDAFvRx3X4dsA:-O4kiAijDAFvRx3X4dsB:bmikfw0) ([raw file](https://github.com/cockroachdb/cockroach/blob/494e890c4053d7391e9dbcc181ec451b79c694ff/pkg/sql/schemachanger/scpb/element_collection.go#L158)):*
> ```Go
> // ForEachUntil is like ForEach, but if fn returns true, we exit early from
> // iterating over c.
> func (c *ElementCollection[E]) ForEachUntil(
> ```

nit: is there someone using this function? I couldn't find one. If not, I would suggest we remove it.

**Review by annrpom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126128)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @spilchen)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go` line 932 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/126128#-O397DII6GUyAS7tp1H1:-O4qBnoC3WLqn1NPe0nq:br19hlm) ([raw file](https://github.com/cockroachdb/cockroach/blob/4fb78e06d4a875a4ca05e405dc23e28c07e00baf/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go#L932)):*
ah i think reviewable and github comments don't sync well -- this is my bad; i left this comment:

> There is a dependency on the order of elements here -- I can write a comment to make this more apparent. Let me see if I can do something else about this

I changed this to rely on the object type specified. This seems better than having to rely on the order of resolution in scdecomp (but yes, this is where i believe the dependency was enforced). Also, I think it fits into my refactor nicer
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go` line 1646 at r27](https://reviewable.io/reviews/cockroachdb/cockroach/126128#-O4kjJk3BtOPqFbqexFk:-O4qCvIjBoP8e0jp-Wxg:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/494e890c4053d7391e9dbcc181ec451b79c694ff/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go#L1646)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

nit: can we move this function to schemachanger/scbuild/internal/scbuildstmt/helpers.go? It doesn't seem specific to index zone.
</blockquote></details>

done
___
*[`pkg/sql/schemachanger/scpb/element_collection.go` line 158 at r27](https://reviewable.io/reviews/cockroachdb/cockroach/126128#-O4kiAijDAFvRx3X4dsA:-O4qCy8P0XKn8GoSG44R:b-cp9pj5) ([raw file](https://github.com/cockroachdb/cockroach/blob/494e890c4053d7391e9dbcc181ec451b79c694ff/pkg/sql/schemachanger/scpb/element_collection.go#L158)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

nit: is there someone using this function? I couldn't find one. If not, I would suggest we remove it.
</blockquote></details>

done -- you're right it has no uses; this was me fiddling

**Comment by annrpom** [comment]
> The current suite of tests has to do with EXPLAINing an index zone config change. The DSC will throw out an error ERROR: use of replication zones on indexes or partitions requires an enterprise license. see https://cockroachlabs.com/pricing for details on how to enable enterprise features, but the legacy does not

I'm wondering how this pans out with https://cockroachlabs.slack.com/archives/C07GE2Q1QN8/p1724089719368749

I just deleted the ALTER INDEX configure zone from the explain test since it requires a CCL license. There is a difference in how EXPLAIN interacts in the DSC vs legacy schema changer; one example is below:
```
demo@127.0.0.1:26257/demoapp/defaultdb> explain alter table t add column id int;                                                                                            
ERROR: column "id" of relation "t" already exists
SQLSTATE: 42701
demo@127.0.0.1:26257/demoapp/defaultdb> set use_declarative_schema_changer = off;                                                                                           
SET

Time: 2ms total (execution 1ms / network 0ms)

demo@127.0.0.1:26257/demoapp/defaultdb> explain alter table t add column id int;                                                                                            
         info
-----------------------
  distribution: local
  vectorized: true

  • alter table
(4 rows)

Time: 6ms total (execution 6ms / network 0ms)
```

This is why the zone config index statement failed for our explain_test -- likely has to do with the DSC `panic`-ing errors. I think this behavior is fine as the errors are correct.

**Review by fqazi — APPROVED** [review]
@annrpom Great work! This looks amazing.'

One question:  Do we need extra rules to make sure dependencies between different parts of the zone config exist . I think for the initial cut the lack of them isn't a problem.

> Reviewed 1 of 40 files at r17, 42 of 42 files at r25, 8 of 8 files at r26, 34 of 34 files at r28, 35 of 35 files at r29, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126128#-:-O4qOlxS-GSGlmtvDpKM:b3ega8n)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom and @spilchen)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go` line 1246 at r29](https://reviewable.io/reviews/cockroachdb/cockroach/126128#-O4qNX3n3YUGyiOxRdd1:-O4qNX3n3YUGyiOxRdd2:bdc1shq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b37e07aaaa174e8d65052ae731dc1d1507d9dcae/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go#L1246)):*
> ```Go
> // `Key.PrefixEnd()` it is omitted.
> //
> // TODO(benesch): remove the hasNewSubzones parameter when a statement to clear
> ```

Nit: Does this apply still?

**Review by spilchen — APPROVED** [review]
:lgtm: The latest changes look good to me. Thanks for making those revisions.

> Reviewed 34 of 34 files at r28, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126128#-:-O4ttyFRBvYfeED9goKj:bn7lbz9)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @annrpom and @fqazi)

**Review by annrpom — COMMENTED** [review]
thank you both for your reviews on this!!

@fqazi I think I am a bit confused by that question -- would you mind giving an example of why we might need extra rules?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126128#-:-O4uVh2GDqTsv9vQkh-6:bb00pou)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go` line 1246 at r29](https://reviewable.io/reviews/cockroachdb/cockroach/126128#-O4qNX3n3YUGyiOxRdd1:-O4uVaZM7_7vSuDu98C3:b3ixk) ([raw file](https://github.com/cockroachdb/cockroach/blob/b37e07aaaa174e8d65052ae731dc1d1507d9dcae/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go#L1246)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Nit: Does this apply still?
</blockquote></details>

likely not -- let me see when i get partitions in!

**Comment by fqazi** [comment]
@annrpom I think just making sure stuff is made in sequence number order. I.e. could we have any ordering issues where we try to mix subzones from different sequence number for example.

Not sure if this is a real problem 🤔

**Comment by annrpom** [comment]
@fqazi ohhh i think i see what you are saying now (perhaps) -- so for something like:
```
begin;
alter index t@idx1 configure zone using num_replicas = 10;
alter index t@idx1 configure zone using gc.ttlseconds = 1600;
alter index t@idx1 configure zone using num_replicas = 11;
end;
```

are we concerned that this might get resolved to something out of order like:
```
seqNum 0: num_replicas = 11
seqNum 1: gc.ttlseconds = 1600
seqNum 2: gc.ttlseconds = 10
```

which would result in a zone config of `num_replicas = 10, gc.ttlseconds = 1600` instead of the intended `num_replicas = 11, gc.ttlseconds = 1600`

is "would the out of order resolution be possible" be the question on the table?

**Comment by fqazi** [comment]
@annrpom Yeah, but I think the sequence numbers would be right. Just that may apply them in an unintended order. I.e. we evaluate higher sequence numbers for some reason, because there is no rule.

**Comment by annrpom** [comment]
salute https://github.com/cockroachdb/cockroach/issues/129482

**Comment by annrpom** [comment]
TFTRs! ('-')7

bors r=spilchen, fqazi

**Comment by annrpom** [comment]
bors retry

**Comment by annrpom** [comment]
bors r-

found a debugging line

**Comment by annrpom** [comment]
bors r=spilchen, fqazi

sorry for the noise

**Pull request merged**
