### PR TITLE
sql: support IF NOT EXISTS in CREATE TENANT

### LINKED ISSUE #98990: sql: support IF NOT EXISTS in CREATE TENANT (and possibly IF EXISTS in DROP)
This will simplify  #98466.
Epic: CRDB-23559

Jira issue: CRDB-25641

### PR DESCRIPTION
**Pull request by knz**
Fixes #98990
Epic: CRDB-23559

Release note: None

### CODE REVIEW

**Review by stevendanna — APPROVED** [review]
Thanks! This seems reasonable to me.

I was going to leave a nit that it seems like a bummer that we have to teach CreateTenantRecord about ifNotExists rather than just handling that in the caller. But, then I noticed that there are multiple places that might return DuplicateObject in CreateTenantRecord.

**Comment by knz** [comment]
TFYR!

bors r=stevendanna

**Comment by knz** [comment]
flake from #98916, adding skip

**Comment by knz** [comment]
bors r=stevendanna

**Pull request merged**
