### PR TITLE
roachtest: add KV/YCSB benchmarks with global MVCC range tombstones

### LINKED ISSUE #84384: roachtest: add benchmarks with MVCC range tombstones
`roachtest` should support writing MVCC range tombstones into the bottom of keyspans that we then run workloads across. Mainly kv0/95 and YCSB. I.e. write either a single MVCC range tombstone across the entire keyspan at the cluster initialization time, or a set of random MVCC range tombstones across it. This allows benchmarking of reads in the presence of MVCC range tombstones.

Jira issue: CRDB-17628

Epic CRDB-2624

### PR DESCRIPTION
**Pull request by erikgrinaker**
**kvserver: add env var to write global MVCC range tombstone**

This patch adds the envvar `COCKROACH_GLOBAL_MVCC_RANGE_TOMBSTONE`.
When enabled, it will write a global MVCC range tombstone across the
entire table data keyspan during cluster bootstrapping. This can be used
to test performance and correctness in the presence of MVCC range
tombstones, by activating range key-specific code paths while not
semantically affecting the data above it.

Touches #84384.

Release note: None

**roachtest: add KV/YCSB benchmarks with global MVCC range tombstones**

This patch adds a set of benchmark variants that write a single MVCC
range tombstone across the entire SQL keyspan at cluster start, via the
`COCKROACH_GLOBAL_MVCC_RANGE_TOMBSTONE` env var. Even though this range
tombstone will not affect the data written during the benchmarks, it
activates range key-specific code paths in the storage layer which can
have a significant impact on performance.

The new benchmarks are:

* `kv0/enc=false/nodes=3/cpu=32/mvcc-range-keys=global`
* `kv95/enc=false/nodes=3/cpu=32/mvcc-range-keys=global`
* `ycsb/A/nodes=3/cpu=32/mvcc-range-keys=global`
* `ycsb/B/nodes=3/cpu=32/mvcc-range-keys=global`
* `ycsb/C/nodes=3/cpu=32/mvcc-range-keys=global`
* `ycsb/D/nodes=3/cpu=32/mvcc-range-keys=global`
* `ycsb/E/nodes=3/cpu=32/mvcc-range-keys=global`
* `ycsb/F/nodes=3/cpu=32/mvcc-range-keys=global`

Resolves #84384.

Release note: None

### CODE REVIEW

**Comment by erikgrinaker** [comment]
First kv95 run is looking pretty bad, with a ~30% regression. For comparison, the last nightly came in at 116,870 ops/s total (about 110k reads/s and 5,700 writes/s).

```
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
 1800.0s        0      138764578        77091.4      2.3      1.7      6.6     12.1    125.8  read

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
 1800.0s        0        7301068         4056.1      4.1      3.3      9.4     16.3    184.5  write

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
 1800.0s        0      146065646        81147.5      2.4      1.7      6.6     12.6    184.5  
```

**Review by jbowens — APPROVED** [review]
:lgtm:

> First kv95 run is looking pretty bad, with a ~30% regression. 

:sweat_smile: 

> Reviewed 6 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85368#-:-N8QLDpL07YVcPIpeOgX:b-w607kg)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aliher1911 and @pavelkalinnikov)

**Comment by erikgrinaker** [comment]
TFTR!

bors r=jbowens

**Comment by nicktrav** [comment]
> First kv95 run is looking pretty bad, with a ~30% regression.

Thanks for adding this, @erikgrinaker. Gotta start somewhere!

**Review by nicktrav — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85368#-:-N8Q_8GB5C2UL0LblQlf:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @aliher1911 and @pavelkalinnikov)

**Comment by erikgrinaker** [comment]
Oof, YCSB/B is look at a 78% regression:

*No range keys: https://roachperf.crdb.dev/?filter=&view=ycsb%2FB%2Fnodes%3D3%2Fcpu%3D32&tab=gce

* Range keys: https://roachperf.crdb.dev/?filter=&view=ycsb%2FB%2Fnodes%3D3%2Fcpu%3D32%2Fmvcc-range-keys%3Dglobal&tab=gce

**Comment by jbowens** [comment]
I had a thought about this case where there's a single very broad range key. The range key will be split into 1 fragment for every sstable in L6. During iteration we defragment to ensure deterministic bounds, which means we need to load every range key block in L6, and compare bounds to defragment it.

Respecting the iterator bounds when defragmenting should help, so that worst case we need to defragment across all the range key blocks that overlap the KV range we're reading. Filed cockroachdb/pebble#1861.

**Pull request merged**
