### PR TITLE
roachprod-microbench: post to slack

### PR DESCRIPTION
**Pull request by herkolategan**
Previously the only way to inspect results of a microbenchmark run would be to
look at the google sheets individually. This change creates a summary that is
posted to slack containing links to the google sheets as well as listing the top
3 changes for each metric in a package group.

Epic: None
Release note: None

### CODE REVIEW

**Review by smg260 — COMMENTED** [review]
Looks good. Can you post a screenshot of the slack message?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110026#-:-Ne4pxUNCsHs2YIz0UpM:b-27mkfg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @renatolabs)

___
*[`pkg/cmd/roachprod-microbench/compare.go` line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110026#-Ne46Ca75NluA-Itic9O:-Ne46Ca75NluA-Itic9P:bhofei7) ([raw file](https://github.com/cockroachdb/cockroach/blob/966ad71937bd948e5994055dcce49ca9d7d90e14/pkg/cmd/roachprod-microbench/compare.go#L53)):*
> ```Go
> )
> 
> /*
> ```

Delete?
___
*[`pkg/cmd/roachprod-microbench/slack.go` line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110026#-Ne4pUAB2a4_Hp2h63LY:-Ne4pUAB2a4_Hp2h63LZ:b-axrw7d) ([raw file](https://github.com/cockroachdb/cockroach/blob/966ad71937bd948e5994055dcce49ca9d7d90e14/pkg/cmd/roachprod-microbench/slack.go#L22)):*
> ```Go
> const (
> 	slackUser    = "microbench"
> 	slackChannel = "aptt-community-service-team"
> ```

Do you think these might make more sense as parameters?

**Review by herkolategan — COMMENTED** [review]
Sure!


> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110026#-:-Ne8iEvP6aL_fIjXC5Vz:b-m805d8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @renatolabs and @smg260)

___
*[`pkg/cmd/roachprod-microbench/compare.go` line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110026#-Ne46Ca75NluA-Itic9O:-Ne8hxBJANTTr8aoRJJW:b-193vbr) ([raw file](https://github.com/cockroachdb/cockroach/blob/966ad71937bd948e5994055dcce49ca9d7d90e14/pkg/cmd/roachprod-microbench/compare.go#L53)):*
<details><summary><i>Previously, smg260 (Miral Gadani) wrote…</i></summary><blockquote>

Delete?
</blockquote></details>

Oops! forgot my comments. Used a template before this. Thanks for catching, I'll remove it.
___
*[`pkg/cmd/roachprod-microbench/slack.go` line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/110026#-Ne4pUAB2a4_Hp2h63LY:-Ne8i83d8VBc64vvxVBP:bi38r6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/966ad71937bd948e5994055dcce49ca9d7d90e14/pkg/cmd/roachprod-microbench/slack.go#L22)):*
<details><summary><i>Previously, smg260 (Miral Gadani) wrote…</i></summary><blockquote>

Do you think these might make more sense as parameters?
</blockquote></details>

Probably, I'll set these as defaults and pass it in.

**Review by smg260 — APPROVED** [review]
Dumb questions, but 
- is this 23.1 in relation to master, or vice versa?
- what does the orange diamond signify? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110026#-:-NeiSstV2lYo7eO2LS8P:bbhtfux)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @renatolabs)

**Comment by herkolategan** [comment]
bors r=smg260

**Review by herkolategan — COMMENTED** [review]
> is this 23.1 in relation to master, or vice versa?
Yes, 23.1 is "old" (or the old revision being compared to) and master is "new" in relation to the comparison. It's relatively important to get the order of those right otherwise a regression might be interpreted as an improvement.
> what does the orange diamond signify?
It's a regression that is significant, but could likely just be variance from the run. In code there are thresholds to decide between the two icons indicating the seriousness of a regression. Red is worse, orange is maybe bad.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/110026#-:-NemBhlP0Ii0uFY8JcbW:b-gjehdv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @renatolabs and @smg260)

**Pull request merged**
