### PR TITLE
sql/parser: Fix crash on DO NOTHING without conflict column causes

### LINKED ISSUE #6732: ON CONFLICT DO NOTHING without conflict column causes crash
Please follow the steps below to help us help you.

1. Please supply the header (i.e. the first few lines) of your most recent
   log file **for each node in your cluster**. On most unix-based systems
   running with defaults, this boils down to the output of

 ```
JESSEs-MacBook-Pro:cockroach jesseseldess$ grep -F '[config]' cockroach-data/logs/cockroach.INFO
I160516 18:28:09.179679 util/log/clog.go:998  [config] file created at: 2016/05/16 18:28:09
I160516 18:28:09.179679 util/log/clog.go:998  [config] running on machine: JESSEs-MacBook-Pro
I160516 18:28:09.179679 util/log/clog.go:998  [config] binary: CockroachDB beta-20160512-121-g7332e99 (darwin amd64, built 2016/05/16 20:22:13, go1.6)
I160516 18:28:09.179679 util/log/clog.go:998  [config] arguments: [./cockroach start --background --background=false]
```

2. Please describe the issue you observed:

- What did you do?
I tried using `ON CONFLICT DO NOTHING` to cause an insert with a uniqueness violation to go through without an error. I inadvertently left the constraint column out of the clause, and this seems to have caused a crash. 

- What did you expect to see?
I expected to insert statement to go through without an error and without making any change. But given that I had mistakenly left out the constraint column, I really should have received an error.

- What did you see instead?

A crash:

```
root@:26257> insert into test.uniques values (1, 1, 'c') ON CONFLICT DO NOTHING;
driver: bad connection
root@:26257> panic: interface conversion: interface is nil, not []string [recovered]
	panic: interface conversion: interface is nil, not []string

goroutine 104 [running]:
panic(0x5163d00, 0xc8207eac80)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
github.com/cockroachdb/cockroach/sql/parser.(*Parser).Parse.func1(0xc82081d240)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/sql/parser/parse.go:74 +0x106
panic(0x5163d00, 0xc8207eac80)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:426 +0x4e9
github.com/cockroachdb/cockroach/sql/parser.(*sqlParserImpl).Parse(0xc8203d4230, 0x6f72b98, 0xc8203d4158, 0x0)
	sql.y:1893 +0x1fd8c
github.com/cockroachdb/cockroach/sql/parser.(*Parser).Parse(0xc8203d4158, 0xc8201e0064, 0x43, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/sql/parser/parse.go:78 +0x149
github.com/cockroachdb/cockroach/sql.(*Executor).execRequest(0xc820150380, 0x7403500, 0xc8206f4bc0, 0xc8203d4000, 0xc8201e0064, 0x43, 0x0, 0x0, 0x0, 0x6f78c00)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/sql/executor.go:369 +0x104
github.com/cockroachdb/cockroach/sql.(*Executor).ExecuteStatements(0xc820150380, 0x7403500, 0xc8206f4bc0, 0xc8203d4000, 0xc8201e0064, 0x43, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/sql/executor.go:330 +0xe5
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).executeStatements(0xc820110a80, 0x7403500, 0xc8206f4bc0, 0xc8201e0064, 0x43, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:646 +0xb2
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).handleSimpleQuery(0xc820110a80, 0x7403500, 0xc8206f4bc0, 0xc820110aa8, 0x0, 0x0)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:323 +0xf2
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).serve(0xc820110a80, 0x0, 0x0, 0x0)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:279 +0x1095
github.com/cockroachdb/cockroach/sql/pgwire.(*Server).ServeConn(0xc820328480, 0x75a1ce8, 0xc82022e000, 0x0, 0x0)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/sql/pgwire/server.go:226 +0x9e5
github.com/cockroachdb/cockroach/server.(*Server).Start.func6.1(0x75a1ce8, 0xc82022e000)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/server/server.go:342 +0x3f
github.com/cockroachdb/cockroach/util.ServeHandler.func3.1(0xc8203aa100, 0x75a1ce8, 0xc82022e000, 0xc8201e6000)
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/util/net.go:125 +0x5a
created by github.com/cockroachdb/cockroach/util.ServeHandler.func3
	/Users/jesseseldess/src/github.com/cockroachdb/cockroach/util/net.go:127 +0x31f
```

### PR DESCRIPTION
**Pull request by nvb**
Fixes #6732.

The reason this was crashing is described at the top of `sql.y`:

> It is important to note that when assigning values to sqlSymUnion.val, all
> nil values should be typed so that they are stored as nil instances in the
> empty interface, instead of setting the empty interface to nil. This means
> that:
>     $$ = []String(nil)
> should be used, instead of:
>     $$ = nil
> to assign a nil string slice to the union.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6795)

### CODE REVIEW

**Comment by tamird** [comment]
needs a test

**Comment by paperstreet** [comment]
Ha. I was just sitting down to do this one

<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> needs a test
</details>


---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6795#-:-KI8UP1klaAyicGO1--7:697044808)*

**Comment by nvanbenschoten** [comment]
Adding a test now.

@paperstreet I figured this was the issue, and didn't want to send you on a chase to figure it out. Any idea if `INSERT INTO a VALUES (1) ON CONFLICT DO UPDATE SET a = 1` is valid by the way?

<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> Ha. I was just sitting down to do this one
</details>


---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6795#-:-KI8UlUbaTtaCg2Lmjoj:167290545)*

**Comment by nvanbenschoten** [comment]
Looks like it. PTAL with the test and formatting change.

<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Adding a test now.
> 
> @paperstreet I figured this was the issue, and didn't want to send you on a chase to figure it out. Any idea if `INSERT INTO a VALUES (1) ON CONFLICT DO UPDATE SET a = 1` is valid by the way?
</details>


---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6795#-:-KI8YATJH3u_AOfOWFQJ:455792269)*

**Comment by paperstreet** [comment]
LGTM. Thanks for the PR! 

<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Looks like it. PTAL with the test and formatting change.
</details>


---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6795#-:-KI8_e_OM0WLHEyjhaGx:-553634765)*

**Comment by tamird** [comment]
Can you add a testdata test?

<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> LGTM. Thanks for the PR! 
</details>


---

Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6795#-:-KI8c-oQel6AdZrX8Zz0:-1021634915)*

**Comment by nvanbenschoten** [comment]
Done.

<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Can you add a testdata test?
</details>


---

Review status: 4 of 5 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6795#-:-KI8nZ2ZKnwY54vYPbWx:-499146009)*

**Comment by tamird** [comment]
LGTM

**Pull request merged**
