### PR TITLE
ui: bump cluster-ui version to 23.2.0-prerelease.1

### PR DESCRIPTION
**Pull request by THardy98**
Version bump includes cluster-ui connected component for the databases page, to be used on managed-service.

Epic: None
Release note: None

### CODE REVIEW

**Review by maryliag — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104508)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @THardy98)

___
*[`pkg/ui/workspaces/cluster-ui/package.json` line 3 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104508#-NXLL2Kw0oDUlSVZFFO_:-NXLL2Kw0oDUlSVZFFOa:b-md7r3x) ([raw file](https://github.com/cockroachdb/cockroach/blob/023864ec2243c296fad4076260dbf6e81b2fb377/pkg/ui/workspaces/cluster-ui/package.json#L3)):*
> ```JSON
> {
>   "name": "@cockroachlabs/cluster-ui",
>   "version": "23.1.0-prerelease.6",
> ```

actually, since this is on master, these are changes for 23.2, so you can update the version to be `23.2.0-prerelease.1`. And then on the 23.1 branch is where you update once you have all your backports merged

**Comment by THardy98** [comment]
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104508)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @THardy98)
> 
> _[`pkg/ui/workspaces/cluster-ui/package.json` line 3 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104508#-NXLL2Kw0oDUlSVZFFO_:-NXLL2Kw0oDUlSVZFFOa:b-md7r3x) ([raw file](https://github.com/cockroachdb/cockroach/blob/023864ec2243c296fad4076260dbf6e81b2fb377/pkg/ui/workspaces/cluster-ui/package.json#L3)):_
> 
> > ```json
> > {
> >   "name": "@cockroachlabs/cluster-ui",
> >   "version": "23.1.0-prerelease.6",
> > ```
> 
> actually, since this is on master, these are changes for 23.2, so you can update the version to be `23.2.0-prerelease.1`. And then on the 23.1 branch is where you update once you have all your backports merged

Should I wait to version bump 23.1 cluster-ui once all connected components are backported, or can I bump per connected component?

**Review by maryliag — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104508)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @THardy98)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/104508#-NXLWVI016_h_PxA3yBD):*
nit: don't forget to update this commit message and PR title/description
___
*[`pkg/ui/workspaces/cluster-ui/package.json` line 3 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104508#-NXLL2Kw0oDUlSVZFFO_:-NXLWQ0F2NMe2noJ-zFv:by1hd46) ([raw file](https://github.com/cockroachdb/cockroach/blob/023864ec2243c296fad4076260dbf6e81b2fb377/pkg/ui/workspaces/cluster-ui/package.json#L3)):*
<details><summary><i>Previously, THardy98 (Thomas Hardy) wrote…</i></summary><blockquote>

Should I wait to version bump cluster-ui once all connected components are backported, or can I bump per connected component?
</blockquote></details>

up to you, might be worth waiting, so you only have to do it once

**Comment by THardy98** [comment]
Just want to double check that the generated files I'm seeing here are ok (`pnpm-lock.yaml` and `.aspect/rules/...`), sees like it from [this thread](https://cockroachlabs.slack.com/archives/C0182T8NUH0/p1685742783968119), but want to make sure.

**Comment by maryliag** [comment]
looks like your PR now has a few file changes I wasn't expecting, for example, why the update on `core-js` and `markdown-to-jsx`.
@sjbarag can you confirm if these are expected with the recent changes in flow?

**Review by sjbarag — APPROVED** [review]
Looks reasonable! Hopefully the new `rules_js` work is going smoothly for ya :) :lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104508#-:-NYOef-rEHRaufTeAcYQ:bcom5n6)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag and @THardy98)

___
*[`.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE5OTU2Mjk4ODM=` line 6 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104508#-NYOeL8-3_1UtOurwNa0:-NYOeL8-3_1UtOurwNa1:b-i6vq7b) ([raw file](https://github.com/cockroachdb/cockroach/blob/7892fea144080b2b0d1353711301df7914b8921e/.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE5OTU2Mjk4ODM%3D#L6)):*
> ```
> pkg/ui/workspaces/cluster-ui/pnpm-lock.yaml=-216806008
> pkg/ui/workspaces/cluster-ui/yarn.lock=1601010899
> pkg/ui/workspaces/cluster-ui/package.json=-1596820040
> ```

These changes are reasonable! We should probably `.gitattributes` them at some point since they're pretty much opaque values. @rickystewart FYI on some followup `rules_js` QoL tweaks
___
*[`pkg/ui/workspaces/cluster-ui/pnpm-lock.yaml` line 11559 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104508#-NYOeXAtEHt2wsxLMRcS:-NYOeXAtEHt2wsxLMRcT:b-9ejyzg) ([raw file](https://github.com/cockroachdb/cockroach/blob/7892fea144080b2b0d1353711301df7914b8921e/pkg/ui/workspaces/cluster-ui/pnpm-lock.yaml#L11559)):*
> ```YAML
>       react: '>= 0.14.0'
>     dependencies:
>       react: 16.12.0
> ```

These changes aren't terribly surprising. A bit odd that there'd already be a dependency change, but I'm willing to see how it goes! Linting passes so it seems safe.

**Comment by THardy98** [comment]
TYFR

**Pull request merged**
