### PR TITLE
geomfn: implement ST_Simplify, 3 arg variant

### LINKED ISSUE #49037: geo/geomfn: implement ST_Simplify({geometry,float8,bool})
Implement `ST_Simplify` on arguments {geometry,float8,bool}, which should adopt [PostGIS behaviour](https://postgis.net/docs/ST_Simplify.html).

_Observers: Please react to this issue if you need this functionality._

For Geometry builtins, please do the following:
* Ideally add a relevant helper function in [`pkg/geo/geomfn`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo/geomfn) (parse and output related functions can go in [`pkg/geo`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo)). Add exhaustive unit tests here - you can run through example test cases and make sure that PostGIS and CRDB return the same result within a degree of accuracy (1cm for geography).
  * When using GEOS, you can reference the [C API](https://github.com/libgeos/geos/blob/master/capi/geos_c.h.in) for which functions are available. Unfortunately, Windows is not currently supported when using GEOS.
* Create a new builtin that references this function in [`pkg/sql/sem/builtins/geo_builtins.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/geo_builtins.go). Note that we currently do not support optional arguments, so we define functions that have optional arguments once without the optional argument (using the default value in the optional position), and once with the optional argument.
* Modify the tests in [`pkg/sql/logictest/testdata/logic_test/geospatial`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/geospatial) to call this functionality at least once. You can call `make testbaselogic FILES='geospatial' TESTFLAGS='-rewrite'` to regenerate the output. Tests here should just ensure the builtin is linked end to end (your exhaustive unit tests go the above mentioned packages!).
* Ensure the documentation is regenerated by calling `make buildshort`. You can also play with it by calling `./cockroach demo --empty` afterwards.
* Submit your PR - make sure to follow the guidelines from [creating your first PR](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR]).

You can follow #48552 for an example PR.

**The following additional guidance has been issued on implementing this function:**

Cannot use GEOS for this one -- but should be straightforward-ish without GEOS. Feel free to replace the ST_Simplify implementation with this too so it&#39;s all in Go. You will need to implement the douglas peucker algorithm yourself.

<sub>:robot: This issue was synced with a spreadsheet by [gsheets-to-github-issues](https://github.com/cockroachlabs/gsheet-to-github-issues) by [otan](https://github.com/otan) on 2021-04-23T06:19:46Z. Changes to titles, body and labels may be overwritten.</sub>

### PR DESCRIPTION
**Pull request by otan**
Resolves #49037 
Refs: #52013

See individual commits for details.

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
sorry about the delay.

> Reviewed 5 of 5 files at r1, 3 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64314#-:-M_Mya4M2hdNFBMhE2BW:b-4d6bd7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

**Review by sumeerbhola — CHANGES_REQUESTED** [review]

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r3, 1 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64314)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[pkg/geo/geomfn/simplify.go, line 70 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64314#-MZM54rEdeF8Z5Uk_zGZ-r2-70:-M_RVj7ACZ3njyYUyb0f:b-nadru2) ([raw file](https://github.com/cockroachdb/cockroach/blob/fed3f3c7f64c1de71aad0ece65ad31a792da72cb/pkg/geo/geomfn/simplify.go#L70)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

yes, geometrycollections.
</blockquote></details>

I meant callee, i.e., `simplifySimplifiableShape`. But this was mostly a nit.
___
*[pkg/geo/geomfn/simplify.go, line 208 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64314#-MZM54rEdeF8Z5Uk_zGZ-r2-208:-M_RWPl19cKN4mdtEBC6:bypqj6b) ([raw file](https://github.com/cockroachdb/cockroach/blob/fed3f3c7f64c1de71aad0ece65ad31a792da72cb/pkg/geo/geomfn/simplify.go#L208)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

not sure what you mean by this, i think that changes the algorithm.
it is most closest to the wikipedia algorithm so i'm inclined to keep it this way.
</blockquote></details>

I don't think I am saying anything different from the wikipedia algorithm, which doesn't use `keepPoints`. I was suggesting
```
	var recurse func(startIdx, endIdx int)
        // INVARIANT: keepPoints[startIdx]=true, keepPoints[endIdx]=true, and these are included in numKeepPoints.
	recurse = func(startIdx, endIdx int) {
		splitIdx := findSplitIndexForSimplifiableShape(t, startIdx, endIdx, tolerance, minPoints > numKeepPoints)
		if splitIdx == startIdx {
			return
		}
		keepPoints[splitIdx] = true
		numKeepPoints++
		recurse(startIdx, splitIdx)
		recurse(splitIdx, endIdx)
	}
	recurse(0, numCoords-1)
```
It makes it easier to understand the invariant regarding `keepPoints` IMO.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64314)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[pkg/geo/geomfn/simplify.go, line 236 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64314#-MZM54rEdeF8Z5Uk_zGZ-r2-236:-M_R_sSu0BFUg9cP_iH1:b-h15j3y) ([raw file](https://github.com/cockroachdb/cockroach/blob/fed3f3c7f64c1de71aad0ece65ad31a792da72cb/pkg/geo/geomfn/simplify.go#L236)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

when we simplify a polygon that is some sort of straight line, e.g. 
```
		{
			desc:              "polygon which gets preserved",
			wkt:               `POLYGON((-1 -1, -1 1, 1 1, 1 -1, -1 -1), (0 0, 100 0, 100 100, 0 100, 0 0))`,
			tolerance:         10,
			preserveCollapsed: true,
			expectedWKT:       "POLYGON ((-1 -1, -1 1, 1 1, -1 -1), (0 0, 100 0, 100 100, 0 100, 0 0))",
		},
```
</blockquote></details>


Can you say something like this in a code comment, and include a justification on why it is ok to keep the first N non-kept points until we hit `numKeepPoints==minPoints`.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64314)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/geo/geomfn/simplify.go, line 60 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64314#-MZM54rEdeF8Z5Uk_zGZ-r2-60:-M_S138B5LeNesHewVkd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fed3f3c7f64c1de71aad0ece65ad31a792da72cb/pkg/geo/geomfn/simplify.go#L60)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

GeometryCollections can have points/multipoints.
</blockquote></details>

Done.
___
*[pkg/geo/geomfn/simplify.go, line 70 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64314#-MZM54rEdeF8Z5Uk_zGZ-r2-70:-M_Sj9Vb1JtDxTIdzlr5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fed3f3c7f64c1de71aad0ece65ad31a792da72cb/pkg/geo/geomfn/simplify.go#L70)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I meant callee, i.e., `simplifySimplifiableShape`. But this was mostly a nit.
</blockquote></details>

Done.
___
*[pkg/geo/geomfn/simplify.go, line 105 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64314#-MZM54rEdeF8Z5Uk_zGZ-r2-105:-M_S18pV5wUyhh9BSoko:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fed3f3c7f64c1de71aad0ece65ad31a792da72cb/pkg/geo/geomfn/simplify.go#L105)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is there a possibility that simplification could cause an inner ring to protrude out of an outer ring? If not, it would be worth a code comment
</blockquote></details>

Done.
___
*[pkg/geo/geomfn/simplify.go, line 180 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64314#-MZM54rEdeF8Z5Uk_zGZ-r2-180:-M_S1m3yAEi8UXhGQpzF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fed3f3c7f64c1de71aad0ece65ad31a792da72cb/pkg/geo/geomfn/simplify.go#L180)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This would be simpler to understand if A is prevCoord, B is currCoord and C is nextCoord.
The immediately following code seems consistent with the comment, but later comments seem to assume B is currCoord, so I'm confused.
</blockquote></details>

Done.
___
*[pkg/geo/geomfn/simplify.go, line 208 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64314#-MZM54rEdeF8Z5Uk_zGZ-r2-208:-M_Sfnoo0y2OHlt4WmcU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fed3f3c7f64c1de71aad0ece65ad31a792da72cb/pkg/geo/geomfn/simplify.go#L208)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I don't think I am saying anything different from the wikipedia algorithm, which doesn't use `keepPoints`. I was suggesting
```
	var recurse func(startIdx, endIdx int)
        // INVARIANT: keepPoints[startIdx]=true, keepPoints[endIdx]=true, and these are included in numKeepPoints.
	recurse = func(startIdx, endIdx int) {
		splitIdx := findSplitIndexForSimplifiableShape(t, startIdx, endIdx, tolerance, minPoints > numKeepPoints)
		if splitIdx == startIdx {
			return
		}
		keepPoints[splitIdx] = true
		numKeepPoints++
		recurse(startIdx, splitIdx)
		recurse(splitIdx, endIdx)
	}
	recurse(0, numCoords-1)
```
It makes it easier to understand the invariant regarding `keepPoints` IMO.
</blockquote></details>

Done.
___
*[pkg/geo/geomfn/simplify.go, line 236 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/64314#-MZM54rEdeF8Z5Uk_zGZ-r2-236:-M_SiTFe5BwdYDVMhl6R:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fed3f3c7f64c1de71aad0ece65ad31a792da72cb/pkg/geo/geomfn/simplify.go#L236)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Can you say something like this in a code comment, and include a justification on why it is ok to keep the first N non-kept points until we hit `numKeepPoints==minPoints`.
</blockquote></details>

Done.

**Review by sumeerbhola — APPROVED** [review]
:lgtm_strong:  

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64314#-:-M_VtTnh3jCnPjOVraTy:b-yncq5v)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Comment by otan** [comment]
bors r=sumeerbhola

thanks

**Pull request merged**
