### PR TITLE
errors: introduce a general-purpose modular error library with good properties

### PR DESCRIPTION
**Pull request by knz**
This PR introduces an error library implemented after the principles laid out in #36987.

It subsumes the following two PRs:

- #38127 *: demonstrate uses of the errors library 
  - review approval: https://github.com/cockroachdb/cockroach/pull/38127#issuecomment-500391874
- #37813 sql, *: simplify remove dependencies on pgerror, util/log
  - review approval: https://github.com/cockroachdb/cockroach/pull/37813#issuecomment-498788826

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
r1 LGTM except we should look at contributing the source line context stuff to `testify/assert` and using that instead (we already use it quite a bit)

I have some some comments on r2 for now

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37121#-:-LfQHCKT1-iGU8GDb5Kv:b-f5fl5l)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @RaduBerinde)

___
*[pkg/errors/errbase_api.go, line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37121#-LfQSmO_7p8Kgrr5AFMD:-LfQSmO_7p8Kgrr5AFME:b-8y15xf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c301759de025148f2b82ca5ac37a2a1b9435ffec/pkg/errors/errbase_api.go#L21)):*
> ```Go
> // UnwrapOnce accesses the direct cause of the error if any, otherwise
> // returns nil.
> var UnwrapOnce func(err error) error = errbase.UnwrapOnce
> ```

Defining copies of functions like this is pretty hacky, and makes navigating code annoying.. And same goes for using a lot of type aliases. Adding different names for the same thing makes it harder to figure out what's going on. It's fine to use these on a limited basis, but this pretty much the main API..

What's the problem with calling this stuff from `errbase` directly? Alternatively, can't all the stuff in `errbase` just live in `errors` (and stuff on top of it can be in another package)? (although `errors` is already used by at least two different packages, so maybe it's good to have a different name)
___
*[pkg/errors/errbase_api.go, line 46 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37121#-LfQUcgWDkBH67swiaFV:-LfQUcgWDkBH67swiaFW:bddwvpg) ([raw file](https://github.com/cockroachdb/cockroach/blob/c301759de025148f2b82ca5ac37a2a1b9435ffec/pkg/errors/errbase_api.go#L46)):*
> ```Go
> var GetAllSafeDetails func(err error) []SafeDetailPayload = errbase.GetAllSafeDetails
> 
> // GetSafeDetails collects the safe details from the given error
> ```

These comments are copies of comments in errbase and are likely to go stale.
___
*[pkg/errors/errbase/data.proto, line 10 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37121#-LfQST147gb9VHQUb08b:-LfQST15EY8p5Apk4VL3:b-22qfvw) ([raw file](https://github.com/cockroachdb/cockroach/blob/c301759de025148f2b82ca5ac37a2a1b9435ffec/pkg/errors/errbase/data.proto#L10)):*
> ```protobuf
> message EncodedError {
> 	// An error is either...
> 	oneof error {
> ```

[nit] I think we don't have tabs in proto files usually
___
*[pkg/errors/errbase/data.proto, line 25 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37121#-LfQI5AUElgX3XBTUJ9g:-LfQI5AUElgX3XBTUJ9h:b7i16sa) ([raw file](https://github.com/cockroachdb/cockroach/blob/c301759de025148f2b82ca5ac37a2a1b9435ffec/pkg/errors/errbase/data.proto#L25)):*
> ```protobuf
> 	string message = 1;
> 
> 	// always a fully qualified go type name, which will
> ```

[nit] This commenting style is kind of odd, especially when you want to look at a specific field.
___
*[pkg/errors/errbase/data.proto, line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37121#-LfQJlI57ePVKZp5QIwQ:-LfQJlI57ePVKZp5QIwR:bgkyxr5) ([raw file](https://github.com/cockroachdb/cockroach/blob/c301759de025148f2b82ca5ac37a2a1b9435ffec/pkg/errors/errbase/data.proto#L27)):*
> ```protobuf
> 	// always a fully qualified go type name, which will
> 	// be used to look up a decoding function.
> 	string type_name = 2;
> ```

I think using fully qualified go type names is flawed. What happens when we move code around? We will lose backward compatibility just because this name changes. I think instead this should be a more generic "handler id", and let the caller of Register come up with a name. And we should have a list of "deprecated id"s which prevent registering with that name again.
___
*[pkg/testutils/simplecheck.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37121#-LfQH90Y3dWndWxVL-cP:-LfQH90Z5D1kYRdO6wCJ:btopuka) ([raw file](https://github.com/cockroachdb/cockroach/blob/256741e93d58497deebbc1bf500df840c69515f3/pkg/testutils/simplecheck.go#L31)):*
> ```Go
> 
> // This file provides assertions and checks for Go tests, two
> // facilities which also provide somes lines of source code around the
> ```

[nit] some

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37121)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @RaduBerinde)

___
*[pkg/util/protoutil/marshal.go, line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37121#-LfQXMc262-tmiDlM9tw:-LfQXMc262-tmiDlM9tx:b-nnvc9n) ([raw file](https://github.com/cockroachdb/cockroach/blob/c301759de025148f2b82ca5ac37a2a1b9435ffec/pkg/util/protoutil/marshal.go#L33)):*
> ```Go
> 
> // SimpleMessage forwards the proto.Message interface and can be used
> // when the additional methods on Message are not relevant.
> ```

What's the point of this alias? The two names can be used interchangeably so I don't see what it buys us

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37121)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @RaduBerinde)

___
*[pkg/errors/errbase_api.go, line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37121#-LfQSmO_7p8Kgrr5AFMD:-Lffi4q46ElQNbCTxZBT:b-q2hnua) ([raw file](https://github.com/cockroachdb/cockroach/blob/c301759de025148f2b82ca5ac37a2a1b9435ffec/pkg/errors/errbase_api.go#L21)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Defining copies of functions like this is pretty hacky, and makes navigating code annoying.. And same goes for using a lot of type aliases. Adding different names for the same thing makes it harder to figure out what's going on. It's fine to use these on a limited basis, but this pretty much the main API..

What's the problem with calling this stuff from `errbase` directly? Alternatively, can't all the stuff in `errbase` just live in `errors` (and stuff on top of it can be in another package)? (although `errors` is already used by at least two different packages, so maybe it's good to have a different name)
</blockquote></details>

I do not have a good answer for this. To me, this code layout is the least worse of the various alternatives:

- everything in the same package would fail to ensure the code stays modular without dense dependencies over time
- using the individual sub-packages directly in client code would require the human developers to remember which function belongs to which package

I'd like to point out that code navigation makes the following of these aliases relatively trivial.
___
*[pkg/errors/errbase_api.go, line 46 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37121#-LfQUcgWDkBH67swiaFV:-LffiUbV7pomk9ouThTN:byc0nh3) ([raw file](https://github.com/cockroachdb/cockroach/blob/c301759de025148f2b82ca5ac37a2a1b9435ffec/pkg/errors/errbase_api.go#L46)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

These comments are copies of comments in errbase and are likely to go stale.
</blockquote></details>

Yes I agree. I am thinking about automatically generating these _api files to keep them in sync.
___
*[pkg/errors/errbase/data.proto, line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37121#-LfQJlI57ePVKZp5QIwQ:-Lffibun91EqL6ESm65w:b-t3ryuw) ([raw file](https://github.com/cockroachdb/cockroach/blob/c301759de025148f2b82ca5ac37a2a1b9435ffec/pkg/errors/errbase/data.proto#L27)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I think using fully qualified go type names is flawed. What happens when we move code around? We will lose backward compatibility just because this name changes. I think instead this should be a more generic "handler id", and let the caller of Register come up with a name. And we should have a list of "deprecated id"s which prevent registering with that name again.
</blockquote></details>

This is discussed in the RFC. This design makes it possible to apply the logic to non-registered errors.
___
*[pkg/testutils/simplecheck.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37121#-LfQH90Y3dWndWxVL-cP:-LffiibsEQf7WEZzjUv_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/256741e93d58497deebbc1bf500df840c69515f3/pkg/testutils/simplecheck.go#L31)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] some
</blockquote></details>

Done.
___
*[pkg/util/protoutil/marshal.go, line 33 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37121#-LfQXMc262-tmiDlM9tw:-Lffijyl1CGHve1j7gvB:b8xmgix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c301759de025148f2b82ca5ac37a2a1b9435ffec/pkg/util/protoutil/marshal.go#L33)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

What's the point of this alias? The two names can be used interchangeably so I don't see what it buys us
</blockquote></details>

This was required by a linter that rejects any use of `proto.Message` outside of this package.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37121)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @RaduBerinde)

___
*[pkg/errors/errbase/data.proto, line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37121#-LfQJlI57ePVKZp5QIwQ:-LfgbNPY6xzAbB9tshPY:bmntgp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c301759de025148f2b82ca5ac37a2a1b9435ffec/pkg/errors/errbase/data.proto#L27)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This is discussed in the RFC. This design makes it possible to apply the logic to non-registered errors.
</blockquote></details>

Would it be possible to we use types for non-registered errors but still allow registering with arbitrary strings? It would be nice to be free to move code around without having to worry about this library.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37121)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @RaduBerinde)

___
*[pkg/errors/errbase_api.go, line 46 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37121#-LfQUcgWDkBH67swiaFV:-Lfgc5xHBETWxx96kBbv:b-br6a9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c301759de025148f2b82ca5ac37a2a1b9435ffec/pkg/errors/errbase_api.go#L46)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Yes I agree. I am thinking about automatically generating these _api files to keep them in sync.
</blockquote></details>

Honestly I would just remove them instead of adding more complexity. Like you said, it's easy to navigate to the original definition which has the comment.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37121)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @RaduBerinde)

___
*[pkg/errors/errbase_api.go, line 46 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37121#-LfQUcgWDkBH67swiaFV:-LfiJEKg4oZXSo-_PVMt:b-7ztywp) ([raw file](https://github.com/cockroachdb/cockroach/blob/c301759de025148f2b82ca5ac37a2a1b9435ffec/pkg/errors/errbase_api.go#L46)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Honestly I would just remove them instead of adding more complexity. Like you said, it's easy to navigate to the original definition which has the comment.
</blockquote></details>

ok :+1: 
___
*[pkg/errors/errbase/data.proto, line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37121#-LfQJlI57ePVKZp5QIwQ:-LfiJH1KBV4Z_U4UU-Jp:b-mtjp47) ([raw file](https://github.com/cockroachdb/cockroach/blob/c301759de025148f2b82ca5ac37a2a1b9435ffec/pkg/errors/errbase/data.proto#L27)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Would it be possible to we use types for non-registered errors but still allow registering with arbitrary strings? It would be nice to be free to move code around without having to worry about this library.
</blockquote></details>

Oh that's a clever idea. I hadn't thought of that. I'll try doing this next week.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37121)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @RaduBerinde)

___
*[pkg/errors/errbase_api.go, line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37121#-LfQSmO_7p8Kgrr5AFMD:-LfjBwoo3V5YUlkPDqvh:bq9xpuz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c301759de025148f2b82ca5ac37a2a1b9435ffec/pkg/errors/errbase_api.go#L21)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I do not have a good answer for this. To me, this code layout is the least worse of the various alternatives:

- everything in the same package would fail to ensure the code stays modular without dense dependencies over time
- using the individual sub-packages directly in client code would require the human developers to remember which function belongs to which package

I'd like to point out that code navigation makes the following of these aliases relatively trivial.
</blockquote></details>

I'm not sure I'm convinced about the modularity aspect. I looked at the tree as of 37765 and most of the sublibraries (e.g. hintdetail, safedetails, markers etc) are only imported by `pkg/errors`. I don't see the downside of putting all that stuff in `errors`. There are some that need to stay separate and for those we can keep these aliases.

That said, it's a fairly cosmetic issue so we don't have to change anything now. Maybe we can look at merging some of the sublibraries into `errors` later.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37121)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @RaduBerinde)

___
*[pkg/errors/errbase_api.go, line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37121#-LfQSmO_7p8Kgrr5AFMD:-LfzbiemAPWNxUjb2qnc:btrswt5) ([raw file](https://github.com/cockroachdb/cockroach/blob/c301759de025148f2b82ca5ac37a2a1b9435ffec/pkg/errors/errbase_api.go#L21)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I'm not sure I'm convinced about the modularity aspect. I looked at the tree as of 37765 and most of the sublibraries (e.g. hintdetail, safedetails, markers etc) are only imported by `pkg/errors`. I don't see the downside of putting all that stuff in `errors`. There are some that need to stay separate and for those we can keep these aliases.

That said, it's a fairly cosmetic issue so we don't have to change anything now. Maybe we can look at merging some of the sublibraries into `errors` later.
</blockquote></details>

I'm inclined to be with Radu here, although I'm just beginning the review. I got here by way of `sql/pgwire/pgerror.GetPGCode` calls `errors.GetPGCodeEx` which is an alias for `errpgcode.GetPGCode`. At least for the particular case of pg codes, it seems to me that client code could use the `errpgcode` package directly. Postgres codes seem like  a pretty specialized concern, even for CRDB (and definitely if you want to publish this library more broadly), so I think it'd be fair enough to require a different package for this functionality. And in fact you seem to already require use of that package for `errpgcode.SimpleCombineCodes`.
___
*[pkg/errors/errpgcode_api.go, line 30 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/37121#-LfzadEc4LkuhLR8Fs3D:-LfzadEc4LkuhLR8Fs3E:b-prb9nb) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e9a19a2df86cc852075cb90ffb734fb92cbd2bc/pkg/errors/errpgcode_api.go#L30)):*
> ```Go
> // - at each level:
> //   - if there is a candidate code at that level, that is used;
> //   - otherwise, it calls computeDefaultCode().
> ```

the argument here is called `compute`, not `computeDefaultCode`.
___
*[pkg/errors/errpgcode_api.go, line 35 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/37121#-LfzaaCoAa38zhf9116L:-LfzaaCoAa38zhf9116M:b47ib93) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e9a19a2df86cc852075cb90ffb734fb92cbd2bc/pkg/errors/errpgcode_api.go#L35)):*
> ```Go
> // - after that, it calls combineCodes() with the code computed already
> //   for the cause and the new code just computed at the current level.
> // Two example functions for computeDefaultCode and combineCode are
> ```

missing examples?
___
*[pkg/errors/errpgcode_api.go, line 40 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/37121#-LfzcsVz27zhG-H3rcVl:-LfzcsVz27zhG-H3rcVm:bjwglby) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e9a19a2df86cc852075cb90ffb734fb92cbd2bc/pkg/errors/errpgcode_api.go#L40)):*
> ```Go
> // For the actual GetPGCode() used throughout SQL, see pgerror.GetPGCode.
> // It cannot be implemented here due to possible cyclical dependencies.
> var GetPGCodeEx func(err error, compute ComputeCodeFn, combine CombineCodeFn) (code string) = errpgcode.GetPGCode
> ```

As far as I can see, `combine` is ever `errpgcode.SimpleCombineCodes`. If I'm not missing something, I think it'd be better if we documented that behavior and got rid of the arg. At which point I think the implementation would also change and simplify - we'd just be going down the cause chain without going back up to "combine" anything.
___
*[pkg/errors/errpgcode_api.go, line 40 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/37121#-Lfzdw9FBSufzPd7OOTT:-Lfzdw9G2QMWaO4QYJI6:b-i2g1bb) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e9a19a2df86cc852075cb90ffb734fb92cbd2bc/pkg/errors/errpgcode_api.go#L40)):*
> ```Go
> // For the actual GetPGCode() used throughout SQL, see pgerror.GetPGCode.
> // It cannot be implemented here due to possible cyclical dependencies.
> var GetPGCodeEx func(err error, compute ComputeCodeFn, combine CombineCodeFn) (code string) = errpgcode.GetPGCode
> ```

why the `Ex` suffix? What is it EXtending?
___
*[pkg/errors/errpgcode_api.go, line 43 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/37121#-Lfz_27-4FRKE70BnHyj:-Lfz_270BclQ9uAHUNM6:b-9f3tk) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e9a19a2df86cc852075cb90ffb734fb92cbd2bc/pkg/errors/errpgcode_api.go#L43)):*
> ```Go
> 
> // ComputeCodeFn is the callback type suitable for GetPGCode.
> type ComputeCodeFn = func(err error) (code string, ok bool)
> ```

I find the use of a type alias here confusing. It doesn't just work if you remove the `=`? If not, I think it'd be better if the type were defined in the `errpgcode` package, or if we did without it completely.
Same for `CombineCodeFn`.
___
*[pkg/errors/errpgcode/pgcode.go, line 62 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/37121#-Lfz_xON2efb0EhEXr5G:-Lfz_xOO1F_OHZVBCC92:b-cm2puj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e9a19a2df86cc852075cb90ffb734fb92cbd2bc/pkg/errors/errpgcode/pgcode.go#L62)):*
> ```Go
> //   - if there is a candidate code at that level, that is used;
> //   - otherwise, it calls computeDefaultCode().
> //     if the function returns false in its second return value,
> ```

can we use `""` as the sentinel for `UncategorizedError` and get rid of the second ret val? I think that'd be better.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37121)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @RaduBerinde)

___
*[pkg/errors/errbase_api.go, line 21 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37121#-LfQSmO_7p8Kgrr5AFMD:-LgWpGQHCo6Hhm_Pp3ls:b-9s08rm) ([raw file](https://github.com/cockroachdb/cockroach/blob/c301759de025148f2b82ca5ac37a2a1b9435ffec/pkg/errors/errbase_api.go#L21)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'm inclined to be with Radu here, although I'm just beginning the review. I got here by way of `sql/pgwire/pgerror.GetPGCode` calls `errors.GetPGCodeEx` which is an alias for `errpgcode.GetPGCode`. At least for the particular case of pg codes, it seems to me that client code could use the `errpgcode` package directly. Postgres codes seem like  a pretty specialized concern, even for CRDB (and definitely if you want to publish this library more broadly), so I think it'd be fair enough to require a different package for this functionality. And in fact you seem to already require use of that package for `errpgcode.SimpleCombineCodes`.
</blockquote></details>

I removed the GetPGCode forward as suggested. For the other thing, I'd like to iterate on this in a later PR (when we revisit the question of extracting the library into a different repo).
___
*[pkg/errors/errpgcode_api.go, line 30 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/37121#-LfzadEc4LkuhLR8Fs3D:-LgWkxr8AIbcXBtsQfcX:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e9a19a2df86cc852075cb90ffb734fb92cbd2bc/pkg/errors/errpgcode_api.go#L30)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

the argument here is called `compute`, not `computeDefaultCode`.
</blockquote></details>

Fixed.
___
*[pkg/errors/errpgcode_api.go, line 35 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/37121#-LfzaaCoAa38zhf9116L:-LgWohVW7v9bXOTW6W5H:b-97xb04) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e9a19a2df86cc852075cb90ffb734fb92cbd2bc/pkg/errors/errpgcode_api.go#L35)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

missing examples?
</blockquote></details>

In other file.
___
*[pkg/errors/errpgcode_api.go, line 40 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/37121#-LfzcsVz27zhG-H3rcVl:-LgWkPzj1W4NuRH7Ik8b:b6u49ed) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e9a19a2df86cc852075cb90ffb734fb92cbd2bc/pkg/errors/errpgcode_api.go#L40)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

As far as I can see, `combine` is ever `errpgcode.SimpleCombineCodes`. If I'm not missing something, I think it'd be better if we documented that behavior and got rid of the arg. At which point I think the implementation would also change and simplify - we'd just be going down the cause chain without going back up to "combine" anything.
</blockquote></details>

I removed the additional function argument, and added the combination in the main function. As we discussed, it is better for performance and there is no compelling case we need a different algorithm yet. 

(The algorithm for the combination preserves the behavior already present in CockroachDB - I do not wish to introduce a behavior change in this PR.)
___
*[pkg/errors/errpgcode_api.go, line 40 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/37121#-Lfzdw9FBSufzPd7OOTT:-LgWoolh43qVjXk-ivlI:bm93r7h) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e9a19a2df86cc852075cb90ffb734fb92cbd2bc/pkg/errors/errpgcode_api.go#L40)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

why the `Ex` suffix? What is it EXtending?
</blockquote></details>

N/A now.
___
*[pkg/errors/errpgcode_api.go, line 43 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/37121#-Lfz_27-4FRKE70BnHyj:-LgWoqxK7PZGA-sMjqCW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e9a19a2df86cc852075cb90ffb734fb92cbd2bc/pkg/errors/errpgcode_api.go#L43)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I find the use of a type alias here confusing. It doesn't just work if you remove the `=`? If not, I think it'd be better if the type were defined in the `errpgcode` package, or if we did without it completely.
Same for `CombineCodeFn`.
</blockquote></details>

Done.
___
*[pkg/errors/errbase/data.proto, line 10 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37121#-LfQST147gb9VHQUb08b:-LgWp8242mqJz7q1m4CN:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/c301759de025148f2b82ca5ac37a2a1b9435ffec/pkg/errors/errbase/data.proto#L10)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] I think we don't have tabs in proto files usually
</blockquote></details>

Fixed.
___
*[pkg/errors/errbase/data.proto, line 25 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37121#-LfQI5AUElgX3XBTUJ9g:-LgWrMer-Zdss3v4Wf-U:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/c301759de025148f2b82ca5ac37a2a1b9435ffec/pkg/errors/errbase/data.proto#L25)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] This commenting style is kind of odd, especially when you want to look at a specific field.
</blockquote></details>

Fixed.
___
*[pkg/errors/errpgcode/pgcode.go, line 62 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/37121#-Lfz_xON2efb0EhEXr5G:-LgWs-kM9XXFdcJs_F0W:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e9a19a2df86cc852075cb90ffb734fb92cbd2bc/pkg/errors/errpgcode/pgcode.go#L62)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

can we use `""` as the sentinel for `UncategorizedError` and get rid of the second ret val? I think that'd be better.
</blockquote></details>

Done.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37121)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @RaduBerinde)

___
*[pkg/errors/errbase/data.proto, line 27 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37121#-LfQJlI57ePVKZp5QIwQ:-LgcQ5VJ0ujGaJ485I3K:b-rsusfe) ([raw file](https://github.com/cockroachdb/cockroach/blob/c301759de025148f2b82ca5ac37a2a1b9435ffec/pkg/errors/errbase/data.proto#L27)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Oh that's a clever idea. I hadn't thought of that. I'll try doing this next week.
</blockquote></details>

Heads up that I have done a couple days additional research and defined the API and data structures for proper error migrations. I have added many migration tests and updated the RFC with the explanation.

**Comment by knz** [comment]
Done:
- [x] initial implementation
- [x] additional research + implementation to solve the migration problem as requested by Radu
- [x] migrated to separate repo with API license, only SQL-specific handling remains in main repo
- [x] troubleshooted + fixed go 1.11/1.12 stack trace compatibility problem

Remains:

- [ ] make the encode/decode functions take context.Context as argument
- [ ] inject `log.Warning` as a dependency during initialization

I'm aiming to merge this early next week unless there are more requests/objections.

**Comment by knz** [comment]
Ok I am getting stable green builds, let's make this fly.

bors r+

**Comment by knz** [comment]
bors r-

(Failed on testrace due to an unrelated flaky test)

**Comment by tbg** [comment]
Wohoo!

**Comment by knz** [comment]
bors r+

(crossing fingers)

**Comment by knz** [comment]
failed again, this time because of a real merge skew. Fixing a test and retrying

**Pull request merged**
