### PR TITLE
sql: add several compatibility features

### LINKED ISSUE #20785: sql: implement pg_catalog.pg_user virtual table
https://www.postgresql.org/docs/10/static/view-pg-user.html

Needed for `pgadmin`.

### LINKED ISSUE #20786: sql: regclass casts must accept schema.name format
For example, `SELECT 'db.name'::regclass` must return the regclass object for the table `name` in the db/schema `db`. Currently, it parses the input string as an unqualified table name.

Required for [pgweb](https://github.com/sosedoff/pgweb).

### LINKED ISSUE #20787: sql: implement pg_get_constraintdef
Needed for `pgweb`.

https://www.postgresql.org/docs/10/static/functions-info.html

### PR DESCRIPTION
**Pull request by jordanlewis**
[pgweb](http://sosedoff.github.io/pgweb/) has been requested by several users. All of the following compatibility items are required by that tool. `has_schema_privilege` is still a blocker for `pgweb` and will be added in a separate PR.

- Add `pg_get_constraintdef`. Closes #20787.
- Add no-op `inet_{client_server}_{addr,port}`
- Add `pg_catalog.pg_user` virtual table. Closes #20785.
- Add some missing always-NULL fields to `information_schema.columns`
- Support `schema.name` format in `::regclass` casts. Closes #20786.

### CODE REVIEW

**Comment by knz** [comment]
Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 5 of 5 files at r3.
Review status: 6 of 9 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/sql/pg_catalog.go, line 1597 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20788#-L0dBn4DfG18odNejFXz:-L0dBn4GfHex7N2niLbq:bj00q1k) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e7813b2080101597982f81ad3e3e77e65145cd9/pkg/sql/pg_catalog.go#L1597)):*
> ```Go
> 					tree.DBoolFalse,             // userepl
> 					tree.DBoolFalse,             // usebypassrls
> 					tree.NewDString("********"), // passwd
> ```

factor the allocation of this string at the beginning of the `populate` function

---

*[pkg/sql/pg_catalog.go, line 446 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20788#-L0dC4UXE5ngmRLUr8C9:-L0dC4UYcQK7sWVD6-qj:bjrqzki) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ef22264061f4db077ad8dd2c5d426405ce68c28/pkg/sql/pg_catalog.go#L446)):*
> ```Go
> 	conbin STRING,
> 	consrc STRING,
> 	condef STRING
> ```

Move the explanatory comment above to a SQL comment here. (`-- ...`)

---

*[pkg/sql/pg_catalog.go, line 526 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20788#-L0dCFQC0L47p-V8XwE0:-L0dCFQD5eVECW1kd0Si:b32xhie) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ef22264061f4db077ad8dd2c5d426405ce68c28/pkg/sql/pg_catalog.go#L526)):*
> ```Go
> 						return err
> 					}
> 					condef = tree.NewDString(fmt.Sprintf("UNIQUE (%s)", c.Index.ColNamesString()))
> ```

Any way to call a `Format` method and allocate just once instead of allocating and copying 3 strings in a row?

---

*[pkg/sql/pg_catalog.go, line 536 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20788#-L0dCRgB0c97HGQ73g7d:-L0dCRgB0c97HGQ73g7e:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ef22264061f4db077ad8dd2c5d426405ce68c28/pkg/sql/pg_catalog.go#L536)):*
> ```Go
> 					consrc = tree.NewDString(c.Details)
> 					conbin = consrc
> 					condef = tree.NewDString(fmt.Sprintf("CHECK (%s)", c.Details))
> ```

ditto

---

*[pkg/sql/show_create.go, line 114 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20788#-L0dC_Q5cdnQIcWRcUrh:-L0dC_Q65fIvQngLu7ip:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ef22264061f4db077ad8dd2c5d426405ce68c28/pkg/sql/show_create.go#L114)):*
> ```Go
> 	}
> 	fmt.Fprintf(buf, "FOREIGN KEY (%s) REFERENCES %s (%s)",
> 		quoteNames(idx.ColumnNames[0:idx.ForeignKey.SharedPrefixLen]...),
> ```

ditto

---

*[pkg/sql/show_create.go, line 120 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20788#-L0dCaCqZI5qj2H-ssT6:-L0dCaCrXZPRNp_O4fyu:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ef22264061f4db077ad8dd2c5d426405ce68c28/pkg/sql/show_create.go#L120)):*
> ```Go
> 	idx.ColNamesString()
> 	if fk.OnDelete != sqlbase.ForeignKeyReference_NO_ACTION {
> 		fmt.Fprintf(buf, " ON DELETE %s", fk.OnDelete.String())
> ```

ditto

---

*[pkg/sql/show_create.go, line 123 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20788#-L0dCbDwGGcmgJmnMwlv:-L0dCbDwGGcmgJmnMwlw:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ef22264061f4db077ad8dd2c5d426405ce68c28/pkg/sql/show_create.go#L123)):*
> ```Go
> 	}
> 	if fk.OnUpdate != sqlbase.ForeignKeyReference_NO_ACTION {
> 		fmt.Fprintf(buf, " ON UPDATE %s", fk.OnUpdate.String())
> ```

ditto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20788)*

**Comment by knz** [comment]
Reviewed 2 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[pkg/sql/sem/builtins/pg_builtins.go, line 423 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20788#-L0dD0WHt9Sxd5BZP8GJ:-L0dD0WJ7v2g9MCtDF9Y:bjo76wv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a686a9379a9672bb860b7d612a6db0d8cac32bf8/pkg/sql/sem/builtins/pg_builtins.go#L423)):*
> ```Go
> 		},
> 	},
> 	"inet_client_addr": {
> ```

Please add comments above each of these new definitions that point to the pg docs for them.
Also explain 1) why you thought it would be OK to have them return incorrect/incomplete values -- are the clients not using them for anything important? 2) what, in the future, we should be returning here instead, and suggest how we should do it, or, if impossible, explain why this is a necessary incompatibility. 

---

*[pkg/sql/sem/tree/eval.go, line 2809 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/20788#-L0dDhquCp4iFG42E3Dh:-L0dDhqvFezIU3XpHPVP:bmyerl3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e2c19cc003693d1fc46db77e9963ce48632a1f8/pkg/sql/sem/tree/eval.go#L2809)):*
> ```Go
> 
> 			case coltypes.RegClass:
> 				tn, err := ctx.Planner.ParseQualifiedTableName(ctx.Ctx(), origS)
> ```

This change needs a test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20788)*

**Comment by jordanlewis** [comment]
Review status: 1 of 9 files reviewed at latest revision, 9 unresolved discussions.

---

*[pkg/sql/pg_catalog.go, line 1597 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20788#-L0dBn4DfG18odNejFXz:-L0hAeg1FvAVHhFi69KB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2e7813b2080101597982f81ad3e3e77e65145cd9/pkg/sql/pg_catalog.go#L1597)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

factor the allocation of this string at the beginning of the `populate` function
</blockquote></details>

Done.

---

*[pkg/sql/pg_catalog.go, line 446 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20788#-L0dC4UXE5ngmRLUr8C9:-L0hAcpefIBMn_wS1JsQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ef22264061f4db077ad8dd2c5d426405ce68c28/pkg/sql/pg_catalog.go#L446)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Move the explanatory comment above to a SQL comment here. (`-- ...`)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20788)*

**Comment by knz** [comment]
Reviewed 2 of 3 files at r7, 3 of 5 files at r8, 2 of 2 files at r9, 1 of 1 files at r10.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20788)*

**Comment by jordanlewis** [comment]
Review status: 0 of 11 files reviewed at latest revision, 7 unresolved discussions.

---

*[pkg/sql/pg_catalog.go, line 526 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20788#-L0dCFQC0L47p-V8XwE0:-L0v53p1RulxuJrM7z-T:bwpcuz2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ef22264061f4db077ad8dd2c5d426405ce68c28/pkg/sql/pg_catalog.go#L526)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Any way to call a `Format` method and allocate just once instead of allocating and copying 3 strings in a row?
</blockquote></details>

You'll have to spell it out for me I'm afraid - what exactly do you suggest for all of these comments?

---

*[pkg/sql/sem/builtins/pg_builtins.go, line 423 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20788#-L0dD0WHt9Sxd5BZP8GJ:-L0v51qB7IyuBdB-yJPe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a686a9379a9672bb860b7d612a6db0d8cac32bf8/pkg/sql/sem/builtins/pg_builtins.go#L423)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please add comments above each of these new definitions that point to the pg docs for them.
Also explain 1) why you thought it would be OK to have them return incorrect/incomplete values -- are the clients not using them for anything important? 2) what, in the future, we should be returning here instead, and suggest how we should do it, or, if impossible, explain why this is a necessary incompatibility. 
</blockquote></details>

Done.

---

*[pkg/sql/sem/tree/eval.go, line 2809 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/20788#-L0dDhquCp4iFG42E3Dh:-L0v3h7hKQ68gahZaMGe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e2c19cc003693d1fc46db77e9963ce48632a1f8/pkg/sql/sem/tree/eval.go#L2809)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This change needs a test.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20788)*

**Comment by knz** [comment]
Thanks for all the updates. You should rebase to pick up the context linter and EXPLAIN output changes.

Also I have clarified what I meant with the formatter functions below.

---

Reviewed 1 of 9 files at r11, 3 of 4 files at r12, 3 of 5 files at r13, 2 of 2 files at r14, 2 of 2 files at r15.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[pkg/sql/pg_catalog.go, line 526 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20788#-L0dCFQC0L47p-V8XwE0:-L1NYWqWXqItFJi8L_HP:byuanii) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ef22264061f4db077ad8dd2c5d426405ce68c28/pkg/sql/pg_catalog.go#L526)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

You'll have to spell it out for me I'm afraid - what exactly do you suggest for all of these comments?
</blockquote></details>

For this specific one only:
```
var buf bytes.Buffer
buf.WriteString("UNIQUE (")
c.Index.ColNames.Format(&buf)
buf.WriteByte(')')
```

---

*[pkg/sql/pg_catalog.go, line 536 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20788#-L0dCRgB0c97HGQ73g7d:-L1NYfH_7pW3k0-EXXV8:b-tokpm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ef22264061f4db077ad8dd2c5d426405ce68c28/pkg/sql/pg_catalog.go#L536)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

same pattern as above

---

*[pkg/sql/show_create.go, line 113 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/20788#-L1NYk16ok-znuYzrKqA:-L1NYk16ok-znuYzrKqB:b-serr9r) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7982a6b7d77c2d6cbd63371dfe42f52ea32c087/pkg/sql/show_create.go#L113)):*
> ```Go
> 		DBNameOriginallyOmitted: fkDb.Name == dbPrefix,
> 	}
> 	fmt.Fprintf(buf, "FOREIGN KEY (%s) REFERENCES %s (%s)",
> ```

buf.WriteString("FOREIGN KEY(")
formatQuotedNames(&buf, idx.ColumnNames[...])
buf.WriteString(") REFERENCES ")
tree.FormatNode(&buf, &fkTableName)
buf.WriteString(" (")
formatQuotedNames(&buf, fkIdx.ColumnNames...)
buf.WriteByte(')')

---

*[pkg/sql/show_create.go, line 120 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/20788#-L1NZ3HMYIUQmA3fs_TI:-L1NZ3HMYIUQmA3fs_TJ:b2ni25r) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7982a6b7d77c2d6cbd63371dfe42f52ea32c087/pkg/sql/show_create.go#L120)):*
> ```Go
> 	idx.ColNamesString()
> 	if fk.OnDelete != sqlbase.ForeignKeyReference_NO_ACTION {
> 		fmt.Fprintf(buf, " ON DELETE %s", fk.OnDelete.String())
> ```

etc

---

*[pkg/sql/show_create.go, line 123 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/20788#-L1NZ3kqckqMtdV32pNz:-L1NZ3kqckqMtdV32pO-:b2ni25r) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7982a6b7d77c2d6cbd63371dfe42f52ea32c087/pkg/sql/show_create.go#L123)):*
> ```Go
> 	}
> 	if fk.OnUpdate != sqlbase.ForeignKeyReference_NO_ACTION {
> 		fmt.Fprintf(buf, " ON UPDATE %s", fk.OnUpdate.String())
> ```

etc

---

*[pkg/sql/sem/builtins/pg_builtins.go, line 432 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/20788#-L1NYDY3JyEMiKX7nJUs:-L1NYDY3JyEMiKX7nJUt:b34jmq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/39a955462198217f94e03c7df3e51eb8bc04e3dd/pkg/sql/sem/builtins/pg_builtins.go#L432)):*
> ```Go
> 	// is used in an advisory capacity for displaying in a UI, and is therefore
> 	// okay to fake for the time being. Implementing these properly requires
> 	// plumbing these values into the EvalContext.
> ```

Ok then please extend the commit message where you added this change to name the specific UI tool that motivated the change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20788#-:-L1NZ6HXXVnb8uBNngmS:b5lxvg2)*

**Comment by jordanlewis** [comment]
Review status: 0 of 11 files reviewed at latest revision, 9 unresolved discussions.

---

*[pkg/sql/pg_catalog.go, line 526 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20788#-L0dCFQC0L47p-V8XwE0:-L1Nq3FSc77veFAL02Wo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ef22264061f4db077ad8dd2c5d426405ce68c28/pkg/sql/pg_catalog.go#L526)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

For this specific one only:
```
var buf bytes.Buffer
buf.WriteString("UNIQUE (")
c.Index.ColNames.Format(&buf)
buf.WriteByte(')')
```
</blockquote></details>

Done.

---

*[pkg/sql/pg_catalog.go, line 536 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20788#-L0dCRgB0c97HGQ73g7d:-L1NlggARLU5rVSrpnaN:b-5ehku6) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ef22264061f4db077ad8dd2c5d426405ce68c28/pkg/sql/pg_catalog.go#L536)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

same pattern as above
</blockquote></details>

This one is okay since c.Details is already a `string`. 

---

*[pkg/sql/show_create.go, line 113 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/20788#-L1NYk16ok-znuYzrKqA:-L1NnicTo423okYOxg9v:b5xy9m3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7982a6b7d77c2d6cbd63371dfe42f52ea32c087/pkg/sql/show_create.go#L113)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

buf.WriteString("FOREIGN KEY(")
formatQuotedNames(&buf, idx.ColumnNames[...])
buf.WriteString(") REFERENCES ")
tree.FormatNode(&buf, &fkTableName)
buf.WriteString(" (")
formatQuotedNames(&buf, fkIdx.ColumnNames...)
buf.WriteByte(')')
</blockquote></details>

This entire file has Fprintf like this - changing just this one wouldn't make any sense. This is also just SHOW CREATE - it's not hugely important to optimize these routines. I'd be okay with taking a stab at fixing all of this file at once in a different PR - seems excessive to do it here just for this one spot.

---

*[pkg/sql/sem/builtins/pg_builtins.go, line 432 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/20788#-L1NYDY3JyEMiKX7nJUs:-L1Npzg7lgUntaW51odD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/39a955462198217f94e03c7df3e51eb8bc04e3dd/pkg/sql/sem/builtins/pg_builtins.go#L432)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Ok then please extend the commit message where you added this change to name the specific UI tool that motivated the change.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20788)*

**Comment by knz** [comment]
:lgtm:

---

Reviewed 1 of 11 files at r16, 2 of 4 files at r17, 4 of 6 files at r18, 2 of 2 files at r19, 2 of 2 files at r20.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/sql/show_create.go, line 113 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/20788#-L1NYk16ok-znuYzrKqA:-L1Nrzk2JUUxB8qCWNdB:bjjbflo) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7982a6b7d77c2d6cbd63371dfe42f52ea32c087/pkg/sql/show_create.go#L113)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This entire file has Fprintf like this - changing just this one wouldn't make any sense. This is also just SHOW CREATE - it's not hugely important to optimize these routines. I'd be okay with taking a stab at fixing all of this file at once in a different PR - seems excessive to do it here just for this one spot.
</blockquote></details>

Ok for a followup PR - but if you don't plan on doing this soon, please at least file an issue. Tag it as "help needed" "good first issue"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20788#-:-L1NsHwnAgdJ2x6XwBhS:bnfp4nl)*

**Comment by jordanlewis** [comment]
TFTR!

**Pull request merged**
