### PR TITLE
build: rewrite release scripts in Go

### PR DESCRIPTION
**Pull request by tamird**
Out for early review. Needs manual testing and possibly some unit tests. Bikeshedding welcome.

### CODE REVIEW

**Comment by a-robinson** [comment]
:lgtm: I'm not very familiar with everything being removed, but the new file looks great!

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/cmd/release/main.go, line 83 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15410#-KikLypPz1RhO5HahoZR:-KikLypPz1RhO5HahoZS:b62y32k) ([raw file](https://github.com/cockroachdb/cockroach/blob/503794011f433323762b0325cc2fcc5ed6a46408/pkg/cmd/release/main.go#L83)):*
> ```Go
> 		out, err := cmd.Output()
> 		if err != nil {
> 			log.Fatal(err)
> ```

It's been useful in the past for me to include `out` in this output as well, to avoid depending on how good the underlying command is at separating its stdout from stderr. The same comment goes for all the uses of `cmd.Output`

---

*[pkg/cmd/release/main.go, line 252 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15410#-KikPw0TM6V0cFqxCgEh:-KikPw0TM6V0cFqxCgEi:b-2mgp0d) ([raw file](https://github.com/cockroachdb/cockroach/blob/503794011f433323762b0325cc2fcc5ed6a46408/pkg/cmd/release/main.go#L252)):*
> ```Go
> 			for relativePath, targetSuffix := range map[string]string{
> 				"cockroach-darwin-10.9-amd64": "darwin-10.9-amd64",
> 				// TODO(tamird): make this linux-gnu-amd64 and add versions to
> ```

For what it's worth, I have no idea what's blocking this from being done. That's fine as long as someone other than you understands, but otherwise this TODO isn't a whole lot to go on.

---

*[pkg/cmd/release/main.go, line 328 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15410#-KikQkBkZGJjEvSideIx:-KikQkBoCdBY7A2eeqZ-:boi9wyi) ([raw file](https://github.com/cockroachdb/cockroach/blob/503794011f433323762b0325cc2fcc5ed6a46408/pkg/cmd/release/main.go#L328)):*
> ```Go
> 		}
> 
> 		dockerAuth, ok := os.LookupEnv(dockerAuthKey)
> ```

Doing this input validation at the beginning of the script rather than after doing so much other work would be nice

---

*[pkg/cmd/release/main.go, line 334 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15410#-KikR-ZZdZbtArnr9fNW:-KikR-ZZdZbtArnr9fNX:bttwe8m) ([raw file](https://github.com/cockroachdb/cockroach/blob/503794011f433323762b0325cc2fcc5ed6a46408/pkg/cmd/release/main.go#L334)):*
> ```Go
> 		dockerEmail, ok := os.LookupEnv(dockerEmailKey)
> 		if !ok {
> 			log.Fatalf("docker auth environment variable %s is not set", dockerEmailKey)
> ```

s/auth/email

---

*[pkg/cmd/release/main.go, line 376 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15410#-KikSKyUDQx30iT_Qgxk:-KikSKyUDQx30iT_Qgxl:b-lilyrn) ([raw file](https://github.com/cockroachdb/cockroach/blob/503794011f433323762b0325cc2fcc5ed6a46408/pkg/cmd/release/main.go#L376)):*
> ```Go
> 			log.Fatal(err)
> 		}
> 		rc, err := cli.ImagePush(ctx, image, types.ImagePushOptions{
> ```

Something tells me you may need to do this separately for each tag, but let me know how the manual testing goes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15410#-:-KikSWmJ9-0Msdqb4wcl:b6aqfpw)*

**Comment by benesch** [comment]
I do think we need to extract a few helpers to make it easier to follow the conditionals, but the approach :lgtm_strong:.

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/cmd/release/main.go, line 252 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15410#-KikPw0TM6V0cFqxCgEh:-KikTqZrukVGbghQqQe0:bedy5e1) ([raw file](https://github.com/cockroachdb/cockroach/blob/503794011f433323762b0325cc2fcc5ed6a46408/pkg/cmd/release/main.go#L252)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

For what it's worth, I have no idea what's blocking this from being done. That's fine as long as someone other than you understands, but otherwise this TODO isn't a whole lot to go on.
</blockquote></details>

Other repositories (cockroach-go and docs) that refer to the less-specific `linux-amd64` name, I believe?

---

*[pkg/cmd/release/main.go, line 313 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15410#-KikUMmRrIiLVUdQCYOO:-KikUMmRrIiLVUdQCYOP:bo3lct) ([raw file](https://github.com/cockroachdb/cockroach/blob/503794011f433323762b0325cc2fcc5ed6a46408/pkg/cmd/release/main.go#L313)):*
> ```Go
> 				if _, err := f.Seek(0, 0); err != nil {
> 					log.Fatal(err)
> 				}
> ```

I think a `makeBinaryZip(targetArchive, binary string)` and a `makeBinaryTargz(targetArchive, binary string)` would go a long way here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15410#-:-KikVRuveLTBhZHwWzXC:b-zajams)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/cmd/release/main.go, line 83 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15410#-KikLypPz1RhO5HahoZR:-KikYSGJFPiCJmqNEMEs:bgt0ph7) ([raw file](https://github.com/cockroachdb/cockroach/blob/503794011f433323762b0325cc2fcc5ed6a46408/pkg/cmd/release/main.go#L83)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

It's been useful in the past for me to include `out` in this output as well, to avoid depending on how good the underlying command is at separating its stdout from stderr. The same comment goes for all the uses of `cmd.Output`
</blockquote></details>

Done, and also spruced up the various log.Fatal calls that could benefit from context.

---

*[pkg/cmd/release/main.go, line 252 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15410#-KikPw0TM6V0cFqxCgEh:-KikT1qUwEps5GyHx9KW:bexsyvh) ([raw file](https://github.com/cockroachdb/cockroach/blob/503794011f433323762b0325cc2fcc5ed6a46408/pkg/cmd/release/main.go#L252)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

For what it's worth, I have no idea what's blocking this from being done. That's fine as long as someone other than you understands, but otherwise this TODO isn't a whole lot to go on.
</blockquote></details>

Ah, good point; this is blocked on updating all the external things that might depend on the current location (docs, https://godoc.org/github.com/cockroachdb/cockroach-go/testserver#NewTestServer, maybe others). I've updated the comment.

---

*[pkg/cmd/release/main.go, line 328 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15410#-KikQkBkZGJjEvSideIx:-KikTIhFt_WP0Ofe_1-B:b-jq9vgv) ([raw file](https://github.com/cockroachdb/cockroach/blob/503794011f433323762b0325cc2fcc5ed6a46408/pkg/cmd/release/main.go#L328)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Doing this input validation at the beginning of the script rather than after doing so much other work would be nice
</blockquote></details>

Fair enough. I did it here because it's only needed for release builds, but that's not super compelling. Done.

---

*[pkg/cmd/release/main.go, line 334 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15410#-KikR-ZZdZbtArnr9fNW:-KikTSedv0PKERVDJYHE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/503794011f433323762b0325cc2fcc5ed6a46408/pkg/cmd/release/main.go#L334)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

s/auth/email
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15410)*

**Comment by a-robinson** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15410)*

**Comment by tamird** [comment]
Pushed an update, and with the help of a fake local s3 was able to test up to docker upload which failed per the comments I've added. I'll move that back out into shell tomorrow since it has to run on the host.

Please have another look at the latest changes!

---

Review status: 10 of 22 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15410#-:-KiljPuK1CJMETxsOLge:b-2ga1lp)*

**Comment by tamird** [comment]
OK, this is pretty much tested end to end with the exception of docker deploy tests.

**Comment by a-robinson** [comment]
Reviewed 10 of 13 files at r3, 3 of 3 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[build/teamcity-release-upload.sh, line 20 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15410#-KimRVQhoilUtPVbZ3ts:-KimRVQhoilUtPVbZ3tt:b-52yx0s) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb9a613a5d174575dec655f9bd4d75ced2085cfe/build/teamcity-release-upload.sh#L20)):*
> ```Shell
> 	time ./acceptance.test -i cockroachdb/cockroach -b /cockroach/cockroach -nodes 3 -test.v -test.timeout -5m
> 
> 	docker push docker.io/cockroachdb/cockroach
> ```

I'd prefer explicitly including the tag here to avoid accidentally overwriting ":latest" or pushing any other tags that happen to be sitting around locally

---

*[pkg/cmd/release/main.go, line 211 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15410#-KimRFsmWABXQ-ErPpGw:-KimRFsmWABXQ-ErPpGx:b6mxitu) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb9a613a5d174575dec655f9bd4d75ced2085cfe/pkg/cmd/release/main.go#L211)):*
> ```Go
> 				log.Fatalf("os.Open(%s): %s", absolutePath, err)
> 			}
> 			// NB: This slash is required to make redirects work correctly
> ```

The comment isn't very clear given that there are two slashes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15410)*

**Comment by tamird** [comment]
Review status: 20 of 22 files reviewed at latest revision, 5 unresolved discussions.

---

*[build/teamcity-release-upload.sh, line 20 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15410#-KimRVQhoilUtPVbZ3ts:-KimUJux0rcMmDh3OMrw:bc2b1dy) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb9a613a5d174575dec655f9bd4d75ced2085cfe/build/teamcity-release-upload.sh#L20)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

I'd prefer explicitly including the tag here to avoid accidentally overwriting ":latest" or pushing any other tags that happen to be sitting around locally
</blockquote></details>

In this case, updating ":latest" was is intended, but I take your point; changed to pushing explicit tags.

---

*[pkg/cmd/release/main.go, line 376 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15410#-KikSKyUDQx30iT_Qgxk:-KimVBNrKPowcFpp6tR0:bus451l) ([raw file](https://github.com/cockroachdb/cockroach/blob/503794011f433323762b0325cc2fcc5ed6a46408/pkg/cmd/release/main.go#L376)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Something tells me you may need to do this separately for each tag, but let me know how the manual testing goes
</blockquote></details>

Moot now, I think.

---

*[pkg/cmd/release/main.go, line 211 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15410#-KimRFsmWABXQ-ErPpGw:-KimUHCP1Kdsm77mVo01:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb9a613a5d174575dec655f9bd4d75ced2085cfe/pkg/cmd/release/main.go#L211)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

The comment isn't very clear given that there are two slashes
</blockquote></details>

Updated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15410)*

**Comment by dt** [comment]
:lgtm_strong: 

bash: kill it with fire.

---

Review status: 19 of 22 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15410#-:-KioLtbMARsiSZzPQOii:bbzc7mm)*

**Comment by a-robinson** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[build/teamcity-release-upload.sh, line 20 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15410#-KimRVQhoilUtPVbZ3ts:-KiozuY_U1FJSubfAIdS:b-lmgkfs) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb9a613a5d174575dec655f9bd4d75ced2085cfe/build/teamcity-release-upload.sh#L20)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

In this case, updating ":latest" was is intended, but I take your point; changed to pushing explicit tags.
</blockquote></details>

Thanks, only pushing for beta/release builds LGTM.

cc https://github.com/cockroachdb/cockroach/issues/5756#issuecomment-295357412

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15410#-:-Kip-IuyMmz7QQKMfCc6:bnfp4nl)*

**Comment by tamird** [comment]
OK, since we're lagging on the release this week, I'm going to merge this and iterate on it while the kinks are worked out over in https://github.com/cockroachdb/cockroach/issues/15382.

I'll immediately update the candidate to this merge commit.

**Comment by bdarnell** [comment]
LGTM

---

Review status: 17 of 21 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/cmd/release/main.go, line 252 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15410#-KikPw0TM6V0cFqxCgEh:-KipNYZKdvSkj_ShJaB8:bsswolr) ([raw file](https://github.com/cockroachdb/cockroach/blob/503794011f433323762b0325cc2fcc5ed6a46408/pkg/cmd/release/main.go#L252)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Ah, good point; this is blocked on updating all the external things that might depend on the current location (docs, https://godoc.org/github.com/cockroachdb/cockroach-go/testserver#NewTestServer, maybe others). I've updated the comment.
</blockquote></details>

I'm -1 on changing these names. They may not be maximally precise, but that's OK. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15410#-:-KipPyHA7K7lGdd8otVd:bb6ywmx)*

**Comment by tamird** [comment]
Review status: 17 of 21 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/cmd/release-upload/main.go, line 252 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15410#-KikPw0TM6V0cFqxCgEh:-KipQuKfTIBYY9vteTK_:bhrib02) ([raw file](https://github.com/cockroachdb/cockroach/blob/503794011f433323762b0325cc2fcc5ed6a46408/pkg/cmd/release-upload/main.go#L252)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I'm -1 on changing these names. They may not be maximally precise, but that's OK. 
</blockquote></details>

Are you saying that you're -1 on this TODO, or some other change here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15410)*

**Comment by a-robinson** [comment]
Reviewed 5 of 6 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15410)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/cmd/release-upload/main.go, line 252 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15410#-KikPw0TM6V0cFqxCgEh:-KipR7TwnUvSJETlq7C-:b9tkruq) ([raw file](https://github.com/cockroachdb/cockroach/blob/503794011f433323762b0325cc2fcc5ed6a46408/pkg/cmd/release-upload/main.go#L252)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Are you saying that you're -1 on this TODO, or some other change here?
</blockquote></details>

Yes, -1 on the TODO. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15410)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/cmd/release-upload/main.go, line 252 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15410#-KikPw0TM6V0cFqxCgEh:-KipRUe3ohtVRSdWCiN8:b-vyemue) ([raw file](https://github.com/cockroachdb/cockroach/blob/503794011f433323762b0325cc2fcc5ed6a46408/pkg/cmd/release-upload/main.go#L252)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Yes, -1 on the TODO. 
</blockquote></details>

Got it. Seems like something we can bikeshed in future work, so I'm going to merge this now to avoid more CI cycles.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15410)*

**Pull request merged**
