### PR TITLE
kvserver: use Counters instead of Gauges for storage metrics

### PR DESCRIPTION
**Pull request by RaduBerinde**
First commit is #125611.

#### kvserver: use Counters instead of Gauges for storage metrics

Until recently, `Counter` did not have an `Update` method, so all
these metrics were inappropriately using gauges.

Epic: none
Release note: None

### CODE REVIEW

**Review by sean- — APPROVED** [review]
Thank you for correcting the metrics types!!!

> Reviewed 9 of 9 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125613#-:-O-F5fvNEkAFzn3-no1j:b-vgl7zr)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @DarrylWong, @jbowens, @nkodali, @renatolabs, and @stevendanna)

**Review by stevendanna — APPROVED** [review]

**Review by aadityasondhi — APPROVED** [review]
:lgtm:

thanks for doing this!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125613#-:-O-GvH3R1ibkvPKRHEP1:bdtxj5p)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong, @jbowens, @nkodali, @RaduBerinde, and @renatolabs)

___
*[`pkg/util/metric/metric.go` line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/125613#-O-GuRYiAXxRoZhxby6F:-O-GuRYiAXxRoZhxby6G:bcwqaey) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ff30a0d71ab9a20506e2e6940c7bae8dddaeae2/pkg/util/metric/metric.go#L27)):*
> ```Go
> 	"github.com/prometheus/client_golang/prometheus"
> 	prometheusgo "github.com/prometheus/client_model/go"
> 	"github.com/rcrowley/go-metrics"
> ```

Love to see this!

**Review by RaduBerinde — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/125613#-:-O-H20o_5ut4N7Pk3kFX:bz5mair)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong, @jbowens, @nkodali, and @renatolabs)

**Pull request merged**
