### PR TITLE
Raft: Move the leader lease into the loving arms of the replica mutex.

### PR DESCRIPTION
**Pull request by BramGruneir**
See #3270
Removing unsafe and sync/atomic from the requires lines make me happy.  :)

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3795)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[storage/replica.go, line 178 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3795#-K7rvRdFuxNJqsg9Gxzk:-K7rvRdFuxNJqsg9Gxzl:1640584706) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e475ee3259c5237cc8ecc447b19d32f6280da01/storage/replica.go#L178)):*
it seems that this guy is never nil, and we never nil check it. how about making it a value, rather than a pointer?

---

*[storage/replica.go, line 197 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3795#-K7rvsGHDiSpLNP188dO:-K7rvsGHDiSpLNP188dP:-531983257) ([raw file](https://github.com/cockroachdb/cockroach/blob/228a79dffbede371ec12084f4ce870f2d8b0f19c/storage/replica.go#L197)):*
what happened here?

---

*[storage/replica_command.go, line 1135 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3795#-K7rw7huO6bLmlgnwLU2:-K7rw7huO6bLmlgnwLU3:716876143) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e475ee3259c5237cc8ecc447b19d32f6280da01/storage/replica_command.go#L1135)):*
hm. how come?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3795)*

**Comment by BramGruneir** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[storage/replica.go, line 178 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3795#-K7rvRdFuxNJqsg9Gxzk:-K7rxYuEpsHhNkYp_QLv:-1098425691) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e475ee3259c5237cc8ecc447b19d32f6280da01/storage/replica.go#L178)):*
I considered it, but loadLeaderLease might return nil.

---

*[storage/replica.go, line 197 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3795#-K7rvsGHDiSpLNP188dO:-K7rwu_5KtcwK2GCianV:-1401026004) ([raw file](https://github.com/cockroachdb/cockroach/blob/228a79dffbede371ec12084f4ce870f2d8b0f19c/storage/replica.go#L197)):*
Moved it into maybeGossipSystemConfig (where it should be).

---

*[storage/replica_command.go, line 1135 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3795#-K7rw7huO6bLmlgnwLU2:-K7rwbecI8hbQ7sunXZB:-1578667145) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e475ee3259c5237cc8ecc447b19d32f6280da01/storage/replica_command.go#L1135)):*
It can't be called when locked.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3795)*

**Comment by bdarnell** [comment]
LGTM

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[storage/replica.go, line 178 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3795#-K7rvRdFuxNJqsg9Gxzk:-K7t4iIEfpocgGzbMIEn:-1120753851) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e475ee3259c5237cc8ecc447b19d32f6280da01/storage/replica.go#L178)):*
`loadLeaderLease` never returns nil unless there is an error, so in that respect it's safe to make it a value. However, `getLeaderLease` returns a pointer. If `r.mu.leaderLease` is a pointer then the pointed-to object never changes, but if this becomes a value then `getLeaderLease` returns a pointer to an object that may be changed after the lock is released. If we make this field a value then `getLeaderLease` needs to return a copy. 

---

*[storage/replica.go, line 370 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3795#-K7t6Bbw9b7VyRPEF9Yy:-K7t6BbxY-sYH-d07NAr:-2285206) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e475ee3259c5237cc8ecc447b19d32f6280da01/storage/replica.go#L370)):*
s/getLease/getLeaderLease/

---

*[storage/replica_command.go, line 1135 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3795#-K7rw7huO6bLmlgnwLU2:-K7t4TjGShzJLPhOPZXE:1078744366) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e475ee3259c5237cc8ecc447b19d32f6280da01/storage/replica_command.go#L1135)):*
This needs a comment.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3795#-:-K7t6Qz0x1rcilW5_WAS:676834233)*

**Comment by BramGruneir** [comment]
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[storage/replica.go, line 178 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3795#-K7rvRdFuxNJqsg9Gxzk:-K7vhNwpv7MyAL8CTAXl:767715001) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e475ee3259c5237cc8ecc447b19d32f6280da01/storage/replica.go#L178)):*
I'm not going to do the conversion with this PR.  I'll do it in a subsequent one.

---

*[storage/replica.go, line 370 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3795#-K7t6Bbw9b7VyRPEF9Yy:-K7vgMqWz8C17O7f_50O:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e475ee3259c5237cc8ecc447b19d32f6280da01/storage/replica.go#L370)):*
done

---

*[storage/replica_command.go, line 1135 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3795#-K7rw7huO6bLmlgnwLU2:-K7vhLvqzsajF-DdDF_T:677588487) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e475ee3259c5237cc8ecc447b19d32f6280da01/storage/replica_command.go#L1135)):*
done

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3795)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3795)*

**Pull request merged**
