### PR TITLE
sql: don't double parse decimals in AS OF

### LINKED ISSUE #10260: sql: don't double parse decimals in AS OF
See: https://reviewable.io/reviews/cockroachdb/cockroach/10242#-KV479e1-il0bR3xmnji:-KV4E5ZelwdknWOnCF_C:b-1t4bve

### PR DESCRIPTION
**Pull request by a6802739**
Fixes #10260.

cc @knz , @mjibson .

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10429)

### CODE REVIEW

**Comment by mjibson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/executor.go, line 1384 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10429#-KVf5Dqey0-cGA7UIsXZ:-KVf5Dqey0-cGA7UIsX_:b-svnfcx) ([raw file](https://github.com/cockroachdb/cockroach/blob/24d161f019c44abd9ae64da0e61ab84375681938/pkg/sql/executor.go#L1384)):*
> ```Go
> 		// Allow nanosecond precision because the timestamp is only used by the
> 		// system and won't be returned to the user over pgwire.
> 		dm, err := d.ResolveAsType(&planMaker.semaCtx, parser.TypeTimestamp)
> ```

This looks like it will drop the nanosecond precision in a timestamp.

---

*[pkg/sql/executor.go, line 1399 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10429#-KVf5mFsgtwTpNdn6_k3:-KVf5mFtlY0mccAblmz_:bbiugrj) ([raw file](https://github.com/cockroachdb/cockroach/blob/24d161f019c44abd9ae64da0e61ab84375681938/pkg/sql/executor.go#L1399)):*
> ```Go
> 			ts.WallTime = int64(*i)
> 		} else {
> 			de, err := d.ResolveAsType(&planMaker.semaCtx, parser.TypeDecimal)
> ```

The point of this PR is to not parse the string into a decimal and back. This, I think, does exactly that parsing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10429)*

**Comment by a6802739** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/executor.go, line 1399 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10429#-KVf5mFsgtwTpNdn6_k3:-KViQuvIjyTLl2eKzef7:bwa7ub2) ([raw file](https://github.com/cockroachdb/cockroach/blob/24d161f019c44abd9ae64da0e61ab84375681938/pkg/sql/executor.go#L1399)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> The point of this PR is to not parse the string into a decimal and back. This, I think, does exactly that parsing.
</details>
then, should I directly `OrigString` here. just like `s := OrigString`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10429)*

**Comment by knz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/executor.go, line 1399 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10429#-KVf5mFsgtwTpNdn6_k3:-KVjAQ27QNKaDBNJunsf:b-1onpsa) ([raw file](https://github.com/cockroachdb/cockroach/blob/24d161f019c44abd9ae64da0e61ab84375681938/pkg/sql/executor.go#L1399)):*
<details><summary><i>Previously, a6802739 (songhao) wrote…</i></summary>
> then, should I directly `OrigString` here. just like `s := OrigString`?
</details>
Yes that was the idea.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10429)*

**Comment by a6802739** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/executor.go, line 1399 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10429#-KVf5mFsgtwTpNdn6_k3:-KVjF4qScC70tWQPCFzA:b-ux28zo) ([raw file](https://github.com/cockroachdb/cockroach/blob/24d161f019c44abd9ae64da0e61ab84375681938/pkg/sql/executor.go#L1399)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Yes that was the idea.
</details>
then, how could we parse like `1e10`, `1.2345e2`, `8/19`. Do you mean I should first  
parse them to `10000000000`, `123.45`, `0.4210526`?

If I did that, doesn't it turn to parse `OrigString` to `Decimal`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10429)*

**Comment by a6802739** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/executor.go, line 1384 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10429#-KVf5Dqey0-cGA7UIsXZ:-KVjIUvfpsP6Gqk1S0Oe:bgy352q) ([raw file](https://github.com/cockroachdb/cockroach/blob/24d161f019c44abd9ae64da0e61ab84375681938/pkg/sql/executor.go#L1384)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> This looks like it will drop the nanosecond precision in a timestamp.
</details>
yeah, it will turn to be Microsecond precision. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10429)*

**Comment by mjibson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/executor.go, line 1384 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10429#-KVf5Dqey0-cGA7UIsXZ:-KVkRC4W6-Hkn5g0PiOu:bblt8wx) ([raw file](https://github.com/cockroachdb/cockroach/blob/24d161f019c44abd9ae64da0e61ab84375681938/pkg/sql/executor.go#L1384)):*
<details><summary><i>Previously, a6802739 (songhao) wrote…</i></summary>
> yeah, it will turn to be Microsecond precision. 
</details>
That's not acceptable for this feature. Actually I'm worried that a test didn't catch it. But it must have nanosecond precision.

---

*[pkg/sql/executor.go, line 1399 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10429#-KVf5mFsgtwTpNdn6_k3:-KVkRQBPS49Yc-I52KDP:b-ovz00q) ([raw file](https://github.com/cockroachdb/cockroach/blob/24d161f019c44abd9ae64da0e61ab84375681938/pkg/sql/executor.go#L1399)):*
<details><summary><i>Previously, a6802739 (songhao) wrote…</i></summary>
> then, how could we parse like `1e10`, `1.2345e2`, `8/19`. Do you mean I should first  
> parse them to `10000000000`, `123.45`, `0.4210526`?
> 
> If I did that, doesn't it turn to parse `OrigString` to `Decimal`?
</details>
Hmm. I think when we came up with this we were assuming that the input would be in the form of 1234.5678 and not have any math or exponents in it. Considering these inputs, it may not be worth doing this PR at all. (I don't think it's worth it anyway, because the performance benefits are so tiny and this feature used so rarely.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10429)*

**Comment by knz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/executor.go, line 1399 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10429#-KVf5mFsgtwTpNdn6_k3:-KVlTvqVEvWCjCDBQsfY:b-3zjk2f) ([raw file](https://github.com/cockroachdb/cockroach/blob/24d161f019c44abd9ae64da0e61ab84375681938/pkg/sql/executor.go#L1399)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> Hmm. I think when we came up with this we were assuming that the input would be in the form of 1234.5678 and not have any math or exponents in it. Considering these inputs, it may not be worth doing this PR at all. (I don't think it's worth it anyway, because the performance benefits are so tiny and this feature used so rarely.)
</details>
I don't think we would like to support special notations for the timestamp. It seems silly (to me) that we would allow users to enter values with exponents or as fractions.

*however* the current code happens to support things like `(now()-'3 day'::interval)::decimal` which may be useful. @mjibson what do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10429)*

**Comment by mjibson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/executor.go, line 1399 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10429#-KVf5mFsgtwTpNdn6_k3:-KVlZlYeYh0kjSyZfouL:bnpghne) ([raw file](https://github.com/cockroachdb/cockroach/blob/24d161f019c44abd9ae64da0e61ab84375681938/pkg/sql/executor.go#L1399)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> I don't think we would like to support special notations for the timestamp. It seems silly (to me) that we would allow users to enter values with exponents or as fractions.
> 
> *however* the current code happens to support things like `(now()-'3 day'::interval)::decimal` which may be useful. @mjibson what do you think?
</details>
I personally think we should keep all the code as is so we can continue to support expressions of that type, and close the issue (leaving it unfixed) that prompted this PR because it is a teeeeny performance gain and not worth the features lost.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10429)*

**Comment by a6802739** [comment]
@knz , @mjibson , should I close this PR, or continue?

**Comment by mjibson** [comment]
Let's close these.

**Pull request closed without merging**
