### PR TITLE
sql: allow interleaving table and index data

### PR DESCRIPTION
**Pull request by danhhz**
Also changes the interleaving sentinel to encoding.descNotNull (0xfe) because
the other one could be used in keys. We want to be able to pull table and index
ids out of a key without the descriptor and it was possible for there to be
ambiguity with the previously used encoding.descNull (0xff).

Followup work:
- Allow interleaving indexes declared in a CREATE TABLE
- Support the CASCADE/RESTRICT foreign key shorthands
- Clean up the InterleavedBy back references when dropping a table/index
- Write some interleaving benchmarks
- Optimize the case where lots of interleaved data has to be scanned over (it
  currently always looks at every key.)
- Remove the SKIP DOC comments on opt_interleave in sql.y

For #2972.

Benchmarks are unchanged for non-interleaved data.

```
name                       old time/op    new time/op    delta
Insert1000_Cockroach-8       9.75ms ± 4%    9.71ms ± 5%   ~             (p=0.690 n=5+5)
Update1000_Cockroach-8       26.6ms ± 3%    26.3ms ± 5%   ~             (p=0.841 n=5+5)
Delete1000_Cockroach-8       13.1ms ± 3%    13.4ms ± 3%   ~             (p=0.421 n=5+5)
Scan1000_Cockroach-8         2.20ms ± 1%    2.20ms ± 1%   ~             (p=0.841 n=5+5)
WideTable1000_Cockroach-8     105ms ± 4%     107ms ± 6%   ~             (p=0.690 n=5+5)

name                       old alloc/op   new alloc/op   delta
Insert1000_Cockroach-8       4.25MB ± 0%    4.25MB ± 0%   ~             (p=0.111 n=4+5)
Update1000_Cockroach-8       6.42MB ± 0%    6.42MB ± 0%   ~             (p=0.841 n=5+5)
Delete1000_Cockroach-8       1.07MB ± 0%    1.07MB ± 0%   ~             (p=1.000 n=5+5)
Scan1000_Cockroach-8          317kB ± 0%     317kB ± 0%   ~             (p=0.444 n=5+5)
WideTable1000_Cockroach-8    21.3MB ± 0%    21.3MB ± 0%   ~             (p=0.222 n=5+5)

name                       old allocs/op  new allocs/op  delta
Insert1000_Cockroach-8        20.4k ± 0%     20.4k ± 0%   ~             (p=0.056 n=5+5)
Update1000_Cockroach-8        28.7k ± 0%     28.7k ± 0%   ~             (p=0.643 n=5+5)
Delete1000_Cockroach-8        12.6k ± 0%     12.6k ± 0%   ~             (p=1.000 n=5+5)
Scan1000_Cockroach-8          2.30k ± 0%     2.30k ± 0%   ~     (all samples are equal)
WideTable1000_Cockroach-8      224k ± 0%      224k ± 0%   ~             (p=0.841 n=5+5)
```

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7855)

### CODE REVIEW

**Comment by paperstreet** [comment]
I wrote all the logic test cases I could think of, but it still feels like I'm missing some. I'd really like to be more confident about this before I merge, but everything else is more-or-less done so I figured I'd get the review process started.

I wonder how hard it would be to generate a bunch of them and put them in our big test suite...

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7855#-:-KMkEVlPfpMfU3CwUMtJ:-7450717)*

**Comment by jseldess** [comment]
@paperstreet, is this docs-ready?

**Comment by paperstreet** [comment]
Definitely not going to be ready for this week's beta

**Comment by RaduBerinde** [comment]
:lgtm:

In terms of tests, it would be nice to have cases when the first/last row fetched from KV is either the child table or the parent table (or grandparent) - just to verify that rowfetcher behaves correctly if it has to skip the first/last row.  We could do this by inserting a row in one table, rechecking some selects, repeat.

Also consider writing a standalone test that performs the same randomized workload on both a set of interleaved tables, and on a set of similar non-interleaved tables (cross-checking all results).

---

Review status: 0 of 14 files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

*[sql/create.go, line 339 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7855#-KMyoB3I6u83a0gdjgjO:-KMyoB3I6u83a0gdjgjP:1375681746) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f7725409df832d4d6e24732df8bf78a9aaad46/sql/create.go#L339)):*
> ```Go
> 	}
> 
> 	created, err := n.p.createDescriptor(tableKey{n.dbDesc.ID, n.n.Table.Table()}, &desc, n.n.IfNotExists)
> ```

[nit] long line

---

*[sql/create.go, line 502 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7855#-KMyoTBUjIJ0uqnIF_2Y:-KMyoTBUjIJ0uqnIF_2Z:100445579) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f7725409df832d4d6e24732df8bf78a9aaad46/sql/create.go#L502)):*
> ```Go
> }
> 
> func (p *planner) addInterleave(
> ```

a brief function comment would help

---

*[sql/create.go, line 506 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7855#-KMyoCtiOgOCdt3Ixm0R:-KMyoCtiOgOCdt3Ixm0S:1375681746) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f7725409df832d4d6e24732df8bf78a9aaad46/sql/create.go#L506)):*
> ```Go
> ) error {
> 	if interleave.DropBehavior != parser.DropDefault {
> 		return util.UnimplementedWithIssueErrorf(7854, "unsupported shorthand %s", interleave.DropBehavior)
> ```

[nit] long line

---

*[sql/create.go, line 533 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7855#-KMyoDtPuQV2d0qbumQq:-KMyoDtPuQV2d0qbumQr:1375681746) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f7725409df832d4d6e24732df8bf78a9aaad46/sql/create.go#L533)):*
> ```Go
> 			return fmt.Errorf("declared columns must match index being interleaved")
> 		}
> 		if col.Type != targetCol.Type || index.ColumnDirections[i] != parentIndex.ColumnDirections[i] {
> ```

[nit] long line

---

*[sql/create.go, line 538 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7855#-KMyoDZ1rDZgny5Glnbo:-KMyoDZ1rDZgny5Glnbp:1375681746) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f7725409df832d4d6e24732df8bf78a9aaad46/sql/create.go#L538)):*
> ```Go
> 	}
> 
> 	ancestorPrefix := append([]sqlbase.InterleaveDescriptor_Ancestor(nil), parentIndex.Interleave.Ancestors...)
> ```

[nit] long line

---

*[sql/create.go, line 587 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7855#-KMyoVmJdA3QUD4dcPYb:-KMyoVmJdA3QUD4dcPYc:1288414015) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f7725409df832d4d6e24732df8bf78a9aaad46/sql/create.go#L587)):*
> ```Go
> 
> // TODO(dan): This is similar to finalizeFKs. Consolidate them.
> func (p *planner) finalizeInterleave(
> ```

a function comment that briefly explains what the function does would help

---

*[sql/show.go, line 96 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7855#-KMyonc434-n4wV4sNiC:-KMyonc434-n4wV4sNiD:-479785402) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f7725409df832d4d6e24732df8bf78a9aaad46/sql/show.go#L96)):*
> ```Go
> // Privileges: None.
> func (p *planner) ShowCreateTable(n *parser.ShowCreateTable) (planNode, error) {
> 	showCreateInterleave := func(idx *sqlbase.IndexDescriptor) (string, error) {
> ```

this can be a separate function

---

*[sql/sqlbase/rowfetcher.go, line 201 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7855#-KMyqw8YgRXxslglApAa:-KMyqw8YgRXxslglApAb:500653123) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f7725409df832d4d6e24732df8bf78a9aaad46/sql/sqlbase/rowfetcher.go#L201)):*
> ```Go
> 		}
> 
> 		rf.keyRemainingBytes, err = rf.ReadIndexKey(rf.kv.Key)
> ```

Nice, doing this here makes more sense.

---

*[sql/sqlbase/rowfetcher.go, line 203 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7855#-KMyqGllcENvIcNBaCxy:-KMyqGllcENvIcNBaCxz:-442163461) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f7725409df832d4d6e24732df8bf78a9aaad46/sql/sqlbase/rowfetcher.go#L203)):*
> ```Go
> 		rf.keyRemainingBytes, err = rf.ReadIndexKey(rf.kv.Key)
> 		if err != nil {
> 			if _, ok := err.(KeyDescriptorMismatchError); ok {
> ```

This is the way we are "skipping" over interleaved rows that don't belong to us, correct?

It's probably not ideal to have an error involved in a "normal" hot path. There may be performance concerns, plus it would be nice to differentiate between the expected descriptors, and some arbitrary descriptor (which should be an actual error). Fine to go in as-is, but maybe leave a TODO to investigate in the future.

---

*[sql/sqlbase/table.go, line 726 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7855#-KMyrhtTzFNbxaLIEWDc:-KMyrhtU_ScE3QUzRwL0:1639851627) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f7725409df832d4d6e24732df8bf78a9aaad46/sql/sqlbase/table.go#L726)):*
> ```Go
> 			}
> 			if decodedTableID != ancestor.TableID || decodedIndexID != ancestor.IndexID {
> 				return nil, KeyDescriptorMismatchError{}
> ```

I believe that returning `KeyDescriptorMismatchError{}` hides an allocation - something must be allocated on the heap if we are to have an `error` interface point to it.

So it might be faster to use a pointer receiver when implementing `Error`, and define a "singleton" const `*KeyDescriptorMismatchError` so we always return the same pointer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7855#-:-KMysbUquCnRNWTijll4:28395324)*

**Comment by paperstreet** [comment]
Thanks for the review!

> In terms of tests, it would be nice to have cases when the first/last row fetched from KV is either the child table or the parent table (or grandparent) - just to verify that rowfetcher behaves correctly if it has to skip the first/last row.  We could do this by inserting a row in one table, rechecking some selects, repeat.

It was almost doing this before, but not quite. Done.

> Also consider writing a standalone test that performs the same randomized workload on both a set of interleaved tables, and on a set of similar non-interleaved tables (cross-checking all results).

I was thinking of doing this as a followup but before I uncomment the syntax (it'll still be hidden from docs after this commit).

---

Review status: 0 of 15 files reviewed at latest revision, 10 unresolved discussions, some commit checks pending.

---

*[sql/create.go, line 339 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7855#-KMyoB3I6u83a0gdjgjO:-KMz1VTngdx4UW8ituvW:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f7725409df832d4d6e24732df8bf78a9aaad46/sql/create.go#L339)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> [nit] long line
</details>
Done.

---

*[sql/create.go, line 502 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7855#-KMyoTBUjIJ0uqnIF_2Y:-KMz1HoH9RhgATNkmJkP:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f7725409df832d4d6e24732df8bf78a9aaad46/sql/create.go#L502)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> a brief function comment would help
</details>
Done.

---

*[sql/create.go, line 506 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7855#-KMyoCtiOgOCdt3Ixm0R:-KMz1J7DjuQ52JC7kk1C:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f7725409df832d4d6e24732df8bf78a9aaad46/sql/create.go#L506)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> [nit] long line
</details>
Done.

---

*[sql/create.go, line 533 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7855#-KMyoDtPuQV2d0qbumQq:-KMz1KJVvFnCu7LtF8vI:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f7725409df832d4d6e24732df8bf78a9aaad46/sql/create.go#L533)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> [nit] long line
</details>
Done.

---

*[sql/create.go, line 538 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7855#-KMyoDZ1rDZgny5Glnbo:-KMz1L6F92eLin_0gF9T:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f7725409df832d4d6e24732df8bf78a9aaad46/sql/create.go#L538)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> [nit] long line
</details>
Done.

---

*[sql/create.go, line 587 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7855#-KMyoVmJdA3QUD4dcPYb:-KMz1MVDtBMW8xCP9imY:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f7725409df832d4d6e24732df8bf78a9aaad46/sql/create.go#L587)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> a function comment that briefly explains what the function does would help
</details>
Done.

---

*[sql/show.go, line 96 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7855#-KMyonc434-n4wV4sNiC:-KMz1O88uKiaXh1xZDJa:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f7725409df832d4d6e24732df8bf78a9aaad46/sql/show.go#L96)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> this can be a separate function
</details>
Done.

---

*[sql/sqlbase/rowfetcher.go, line 201 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7855#-KMyqw8YgRXxslglApAa:-KMyzYKm0f_8pkLTvxWj:521471062) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f7725409df832d4d6e24732df8bf78a9aaad46/sql/sqlbase/rowfetcher.go#L201)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Nice, doing this here makes more sense.
</details>
I had to to avoid doing it twice.

---

*[sql/sqlbase/rowfetcher.go, line 203 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7855#-KMyqGllcENvIcNBaCxy:-KMyzciOwAlnQ3ouqCwG:-476215310) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f7725409df832d4d6e24732df8bf78a9aaad46/sql/sqlbase/rowfetcher.go#L203)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> This is the way we are "skipping" over interleaved rows that don't belong to us, correct?
> 
> It's probably not ideal to have an error involved in a "normal" hot path. There may be performance concerns, plus it would be nice to differentiate between the expected descriptors, and some arbitrary descriptor (which should be an actual error). Fine to go in as-is, but maybe leave a TODO to investigate in the future.
</details>
Yeah, it's unclear how you'd detect an arbitrary descriptor without doing too much extra work in a normal hot path. 

---

*[sql/sqlbase/table.go, line 726 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7855#-KMyrhtTzFNbxaLIEWDc:-KMyzzXtPx8xf5k4E2Z-:-635671892) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f7725409df832d4d6e24732df8bf78a9aaad46/sql/sqlbase/table.go#L726)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> I believe that returning `KeyDescriptorMismatchError{}` hides an allocation - something must be allocated on the heap if we are to have an `error` interface point to it.
> 
> So it might be faster to use a pointer receiver when implementing `Error`, and define a "singleton" const `*KeyDescriptorMismatchError` so we always return the same pointer.
</details>
I've been vaguely uncomfortable about this since I did it and I've been thinking about it since. I've changed it to return an additional bool in this revision. WDYT?

I'm also considering something like the behavior checking described in http://dave.cheney.net/2016/04/27/dont-just-check-errors-handle-them-gracefully

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7855#-:-KMz2j9l5OF65rb7Fj_P:-899725980)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/sqlbase/table.go, line 726 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7855#-KMyrhtTzFNbxaLIEWDc:-KMz6VjjhiTEEjRQuoIi:435828336) ([raw file](https://github.com/cockroachdb/cockroach/blob/15f7725409df832d4d6e24732df8bf78a9aaad46/sql/sqlbase/table.go#L726)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> I've been vaguely uncomfortable about this since I did it and I've been thinking about it since. I've changed it to return an additional bool in this revision. WDYT?
> 
> I'm also considering something like the behavior checking described in http://dave.cheney.net/2016/04/27/dont-just-check-errors-handle-them-gracefully
</details>
LGTM. I think either a flag or a constant/sentinel value is ok. The behavior stuff in the article might be a bit overkill for this (and even in that case I would use a constant value to avoid allocating the error every time).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7855)*

**Pull request merged**
