### PR TITLE
storageccl: retry WriteFile during errors

### PR DESCRIPTION
**Pull request by madelynnblue**
WriteFile occasionally fails for unknown reasons on Azure. Retrying
just the line that failed (the put block list) doesn't fix the
problem. We suspect this is a problem with Azure itself. This change
adds a higher level retry for the entire operation.

### CODE REVIEW

**Comment by tamird** [comment]
> We suspect this is a problem with Azure itself.

Where's the investigation being tracked?

**Comment by danhhz** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/ccl/sqlccl/backup.go, line 407 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14771#-KhOeh3h5TSzXHjGcxlR:-KhOeh3h5TSzXHjGcxlS:b-gmpwl9) ([raw file](https://github.com/cockroachdb/cockroach/blob/8961d319a3e3904a8fd888850ca5b1af2971d473/pkg/ccl/sqlccl/backup.go#L407)):*
> ```Go
> 	defer exportStore.Close()
> 
> 	if err := storageccl.RetryWriteFile(ctx, BackupDescriptorName, exportStore, func() (io.Reader, error) {
> ```

I think this top level retry should stay azure-only until we see issues with the other storages

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14771)*

**Comment by mjibson** [comment]
It's being tracked in the backup channel. No issue.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/ccl/sqlccl/backup.go, line 407 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14771#-KhOeh3h5TSzXHjGcxlR:-KhOf-UU0GZmoWv5oEfb:bognjb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8961d319a3e3904a8fd888850ca5b1af2971d473/pkg/ccl/sqlccl/backup.go#L407)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I think this top level retry should stay azure-only until we see issues with the other storages
</blockquote></details>

This would force the azure code to cache all bytes from the io.Reader since it doesn't have access to the os.File and so can't do a Seek. WriteFile is also called with a `bytes.NewReader([]byte)` which doesn't support seek, so it's not trivial to plumb through an os.File instead of a io.Reader. You ok with the caching solution? It would theoretically hold an additional 64MB or whatever the max split size is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14771#-:-KhOfoc9hYO-s3Vu9YlH:bzaqsge)*

**Comment by danhhz** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/ccl/sqlccl/backup.go, line 407 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14771#-KhOeh3h5TSzXHjGcxlR:-KhSHqEPtnyR957K2rsl:b-9558i0) ([raw file](https://github.com/cockroachdb/cockroach/blob/8961d319a3e3904a8fd888850ca5b1af2971d473/pkg/ccl/sqlccl/backup.go#L407)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

This would force the azure code to cache all bytes from the io.Reader since it doesn't have access to the os.File and so can't do a Seek. WriteFile is also called with a `bytes.NewReader([]byte)` which doesn't support seek, so it's not trivial to plumb through an os.File instead of a io.Reader. You ok with the caching solution? It would theoretically hold an additional 64MB or whatever the max split size is.
</blockquote></details>

Ah, I see. I'm less happy about throwing more retries at the problem if it's going to affect non-azure code. cc @dt thoughts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14771)*

**Comment by danhhz** [comment]
And tamir has a point, we should be tracking these sorts of things in issues. I made one here (https://github.com/cockroachdb/cockroach/issues/14788) can you link it from the commit, plz?

**Comment by dt** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/sqlccl/backup.go, line 408 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14771#-KhTeBoMz2T08Muf15CW:-KhTeBoNazv1M-37BRZ2:b4mhnf1) ([raw file](https://github.com/cockroachdb/cockroach/blob/8961d319a3e3904a8fd888850ca5b1af2971d473/pkg/ccl/sqlccl/backup.go#L408)):*
> ```Go
> 
> 	if err := storageccl.RetryWriteFile(ctx, BackupDescriptorName, exportStore, func() (io.Reader, error) {
> 		return bytes.NewReader(descBuf), nil
> ```

`bytes.Reader` has a `Reset()`.

Maybe that's the interface we want to pass: am io.Reader w/ Reset (implemented as Seek for files)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14771)*

**Comment by dt** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/sqlccl/backup.go, line 408 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14771#-KhTeBoMz2T08Muf15CW:-KhThSER-h1KMbEfDIZo:b-kayf72) ([raw file](https://github.com/cockroachdb/cockroach/blob/8961d319a3e3904a8fd888850ca5b1af2971d473/pkg/ccl/sqlccl/backup.go#L408)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

"Reset resets the buffer to be empty, but it retains the underlying storage for use by future writes. Reset is the same as Truncate(0)." so I don't think it works.
</blockquote></details>

That's bytes.Buffer, not bytes.Reader

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14771)*

**Comment by dt** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/sqlccl/backup.go, line 408 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14771#-KhTeBoMz2T08Muf15CW:-KhTi3UF_GDFOrIrQpMv:b-q6m2dw) ([raw file](https://github.com/cockroachdb/cockroach/blob/8961d319a3e3904a8fd888850ca5b1af2971d473/pkg/ccl/sqlccl/backup.go#L408)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

That's bytes.Buffer, not bytes.Reader
</blockquote></details>

actually, maybe we just want to pass a io.ReadSeeker and let the retry loop reset the seeker itself?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14771)*

**Comment by mjibson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/ccl/sqlccl/backup.go, line 407 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14771#-KhOeh3h5TSzXHjGcxlR:-KhToSgRlaJ9FKG_k69o:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8961d319a3e3904a8fd888850ca5b1af2971d473/pkg/ccl/sqlccl/backup.go#L407)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Ah, I see. I'm less happy about throwing more retries at the problem if it's going to affect non-azure code. cc @dt thoughts?
</blockquote></details>

Done.

---

*[pkg/ccl/sqlccl/backup.go, line 408 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14771#-KhTeBoMz2T08Muf15CW:-KhToR1b7XGxmytJLyvY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8961d319a3e3904a8fd888850ca5b1af2971d473/pkg/ccl/sqlccl/backup.go#L408)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

actually, maybe we just want to pass a io.ReadSeeker and let the retry loop reset the seeker itself?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14771)*

**Comment by dt** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14771#-:-KhTr5vvAWYsaAhhP6Jg:bnfp4nl)*

**Pull request merged**
