### PR TITLE
descpb: rework RegionConfig to be nilable

### PR DESCRIPTION
**Pull request by otan**
* Moved RegionConfig to be a property of the DatabaseDescriptor.
* Made RegionConfig nil-able.

Release note: None

### CODE REVIEW

**Review by ajstorm — APPROVED** [review]
:lgtm: The nilability cleans things up.  Nice!

> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57151#-:-MN3vCv-5RfEH3KpPc-K:b-se8npd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm and @arulajmani)

**Review by arulajmani — CHANGES_REQUESTED** [review]
Couple nits but :LGTM: otherwise. Thanks for making this change! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57151#-:-MN4g66u44bHr0O0j5mz:b-heuuqa)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @otan)

___
*[pkg/sql/crdb_internal.go, line 239 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57151#-MN4foTz41Z-52xT1Oc2:-MN4foTz41Z-52xT1Oc3:b-6cmset) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c63074fe9710cc6b8835c6e8c462d2dd329fc46/pkg/sql/crdb_internal.go#L239)):*
> ```Go
> 				var primaryRegion tree.Datum = tree.DNull
> 				regions := tree.NewDArray(types.String)
> 				if db.RegionConfig != nil {
> ```

Can we abstract this into a function on the database descriptor? `IsMultiRegionDatabase` or something? 
___
*[pkg/sql/catalog/descpb/structured.proto, line 1101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57151#-MN4gJmp2tGmDgLMK82I:-MN4gJmq4uUSplDg6oq6:b-40jx7z) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c63074fe9710cc6b8835c6e8c462d2dd329fc46/pkg/sql/catalog/descpb/structured.proto#L1101)):*
> ```protobuf
> 
>   // RegionConfig stores region configuration for a given database.
>   message RegionConfig {
> ```

More merge conflicts hahahaha
___
*[pkg/sql/catalog/descpb/structured.proto, line 1108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57151#-MN4fOZi8bSFCsNgYfVD:-MN4fOZi8bSFCsNgYfVE:b-4pyw2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c63074fe9710cc6b8835c6e8c462d2dd329fc46/pkg/sql/catalog/descpb/structured.proto#L1108)):*
> ```protobuf
>     optional string primary_region = 3 [(gogoproto.nullable)=false,(gogoproto.casttype)="Region"];
>   }
>   optional RegionConfig region_config = 10;
> ```

This could use a comment that says the region config being set indicates that the database is a multi-region database.

**Review by otan — COMMENTED** [review]
@arulajmani if this LGTM feel free to `bors r+` to unblock you.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57151#-:-MN58e6LE_7aN_7a8hk0:b-ghg27i)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajstorm, @arulajmani, and @otan)

___
*[pkg/sql/crdb_internal.go, line 239 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57151#-MN4foTz41Z-52xT1Oc2:-MN58_QC6azWyst3rv8n:by9nnkp) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c63074fe9710cc6b8835c6e8c462d2dd329fc46/pkg/sql/crdb_internal.go#L239)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Can we abstract this into a function on the database descriptor? `IsMultiRegionDatabase` or something? 
</blockquote></details>

i did it but i'm not sure i'm a fan. not fussed tho.
___
*[pkg/sql/catalog/descpb/structured.proto, line 1108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57151#-MN4fOZi8bSFCsNgYfVD:-MN58dCt1-ctqJr_wGIp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c63074fe9710cc6b8835c6e8c462d2dd329fc46/pkg/sql/catalog/descpb/structured.proto#L1108)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

This could use a comment that says the region config being set indicates that the database is a multi-region database.
</blockquote></details>

Done.

**Comment by arulajmani** [comment]
Thanks, yee this LGTM. 

bors r+

**Pull request merged**
