### PR TITLE
sql: big batch of allocation reductions

### PR DESCRIPTION
**Pull request by jordanlewis**
See individual commits.

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, 4 of 4 files at r2, 2 of 2 files at r3, 3 of 3 files at r4, 1 of 1 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56801#-:-MMM9bpb0lbgOzIL5j5t:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/colconv/vec_to_datum_tmpl.go, line 79 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56801#-MMM88geB1lAi90c4E9C:-MMM88geB1lAi90c4E9D:b-yvg8pj) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a04e7d3af54919a85e82a71beb24ffc1b5c548c/pkg/sql/colconv/vec_to_datum_tmpl.go#L79)):*
> ```Go
> // Release is part of the execinfra.Releasable interface.
> func (c *VecToDatumConverter) Release() {
> 	c.convertedVecs = c.convertedVecs[:0]
> ```

nit: it probably would be nice to do
```
*c = VecToDatumConverter { ... }
```
___
*[pkg/sql/colexec/materializer.go, line 181 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56801#-MMM82fm-I8yvs8xg_1o:-MMM82fm-I8yvs8xg_1p:b3iemud) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a04e7d3af54919a85e82a71beb24ffc1b5c548c/pkg/sql/colexec/materializer.go#L181)):*
> ```Go
> 		typs:          typs,
> 		drainHelper:   newDrainHelper(metadataSourcesQueue),
> 		converter:     colconv.NewAllVecToDatumConverter(len(typs)),
> ```

I don't think we have such method?
___
*[pkg/sql/colflow/vectorized_flow.go, line 217 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56801#-MMM8xeE8aOSyCAJj7Hl:-MMM8xeE8aOSyCAJj7Hm:b-bm4apq) ([raw file](https://github.com/cockroachdb/cockroach/blob/556082013446d32b738bca3eea62394fb65160ce/pkg/sql/colflow/vectorized_flow.go#L217)):*
> ```Go
> 	diskQueueCfg := colcontainer.DiskQueueCfg{
> 		FS:        f.Cfg.TempFS,
> 		GetPather: f,
> ```

What is the allocation that is being removed here with introduction of an interface? We no longer need to create a `func()`?

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56801)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

___
*[pkg/sql/colexec/materializer.go, line 181 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56801#-MMM82fm-I8yvs8xg_1o:-MMMf27YA50ktGt0kEJN:bqbvn3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a04e7d3af54919a85e82a71beb24ffc1b5c548c/pkg/sql/colexec/materializer.go#L181)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I don't think we have such method?
</blockquote></details>

Done, accidentally had added things just to .eg.go.
___
*[pkg/sql/colflow/vectorized_flow.go, line 217 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56801#-MMM8xeE8aOSyCAJj7Hl:-MMMf5Xe0Kq7PyoXczP9:b-ize631) ([raw file](https://github.com/cockroachdb/cockroach/blob/556082013446d32b738bca3eea62394fb65160ce/pkg/sql/colflow/vectorized_flow.go#L217)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

What is the allocation that is being removed here with introduction of an interface? We no longer need to create a `func()`?
</blockquote></details>

Yes, creating that function requires an allocation because it's a closure. Also, even making that function into a method creates an allocation, presumably because passing a method requires making a closure with the method's receiver.

This pattern avoids that allocation altogether. I think we could apply it in more places.

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 9 of 9 files at r7, 2 of 2 files at r8, 4 of 4 files at r9, 1 of 1 files at r10, 2 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56801)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis)

___
*[pkg/sql/colflow/vectorized_flow.go, line 217 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/56801#-MMM8xeE8aOSyCAJj7Hl:-MMMo9cpAwbLncnwZ3bZ:b-kufkx2) ([raw file](https://github.com/cockroachdb/cockroach/blob/556082013446d32b738bca3eea62394fb65160ce/pkg/sql/colflow/vectorized_flow.go#L217)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Yes, creating that function requires an allocation because it's a closure. Also, even making that function into a method creates an allocation, presumably because passing a method requires making a closure with the method's receiver.

This pattern avoids that allocation altogether. I think we could apply it in more places.
</blockquote></details>

I see, thanks.

**Pull request merged**
