### PR TITLE
storage: fix split / split-queue race

### LINKED ISSUE #29144: server: had X ranges at startup, expected 22
https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=864518&_focus=46771

```
[20:21:58][Run Go tests] TestDropDatabaseDeleteData
...
[20:21:58][TestDropDatabaseDeleteData] test_server_shim.go:176: had 9 ranges at startup, expected 22
```

### LINKED ISSUE #30660: sql: TestCommandsWhileTableBeingDropped failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/c7b6cb20b36696d65853c3e16c0aec44d1e6fb2a

Parameters:
```
TAGS=
GOFLAGS=
```

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stressrace instead of stress and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
make stress TESTS=TestCommandsWhileTableBeingDropped PKG=github.com/cockroachdb/cockroach/pkg/sql TESTTIMEOUT=5m STRESSFLAGS='-stderr=false -maxtime 20m -timeout 10m'
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=926394&tab=buildLog

```

I180926 06:00:57.365559 74038 storage/split_queue.go:116  [n1,split,s1,r6/1:/{System/tse-Table/System…}] shouldQueue: shouldQ=false priority=0.0
I180926 06:00:57.365589 74038 storage/split_queue.go:116  [n1,split,s1,r13/1:/{Table/16-Max}] shouldQueue: shouldQ=true priority=1.0
I180926 06:00:57.365618 74038 storage/split_queue.go:116  [n1,split,s1,r5/1:/System/ts{d-e}] shouldQueue: shouldQ=false priority=0.0
I180926 06:00:57.365645 74038 storage/split_queue.go:116  [n1,split,s1,r2/1:/System/{-NodeLive…}] shouldQueue: shouldQ=false priority=0.0
I180926 06:00:57.365680 74038 storage/split_queue.go:116  [n1,split,s1,r1/1:/{Min-System/}] shouldQueue: shouldQ=false priority=0.0
I180926 06:00:57.365713 74038 storage/split_queue.go:116  [n1,split,s1,r11/1:/Table/1{4-5}] shouldQueue: shouldQ=false priority=0.0
I180926 06:00:57.369842 74240 sql/event_log.go:126  [n1,intExec=create-default-db] Event: "create_database", target: 51, info: {DatabaseName:postgres Statement:CREATE DATABASE IF NOT EXISTS postgres User:root}
I180926 06:00:57.372018 73843 server/server.go:1605  [n1] done ensuring all necessary migrations have run
I180926 06:00:57.372039 73843 server/server.go:1608  [n1] serving sql connections
I180926 06:00:57.388306 74038 storage/split_queue.go:116  [n1,split,s1,r14/1:/{Table/17-Max}] shouldQueue: shouldQ=true priority=1.0
I180926 06:00:57.388706 74038 storage/split_queue.go:116  [n1,split,s1,r9/1:/Table/1{2-3}] shouldQueue: shouldQ=false priority=0.0
I180926 06:00:57.388785 74038 storage/split_queue.go:116  [n1,split,s1,r7/1:/Table/{SystemCon…-11}] shouldQueue: shouldQ=false priority=0.0
I180926 06:00:57.388806 74038 storage/split_queue.go:116  [n1,split,s1,r10/1:/Table/1{3-4}] shouldQueue: shouldQ=false priority=0.0
I180926 06:00:57.388835 74038 storage/split_queue.go:116  [n1,split,s1,r8/1:/Table/1{1-2}] shouldQueue: shouldQ=false priority=0.0
I180926 06:00:57.388855 74038 storage/split_queue.go:116  [n1,split,s1,r12/1:/Table/1{5-6}] shouldQueue: shouldQ=false priority=0.0
I180926 06:00:57.388872 74038 storage/split_queue.go:116  [n1,split,s1,r3/1:/System/NodeLiveness{-Max}] shouldQueue: shouldQ=false priority=0.0
I180926 06:00:57.388905 74038 storage/split_queue.go:116  [n1,split,s1,r9/1:/Table/1{2-3}] shouldQueue: shouldQ=false priority=0.0
I180926 06:00:57.388920 74038 storage/split_queue.go:116  [n1,split,s1,r4/1:/System/{NodeLive…-tsd}] shouldQueue: shouldQ=false priority=0.0
I180926 06:00:57.388942 74038 storage/split_queue.go:116  [n1,split,s1,r1/1:/{Min-System/}] shouldQueue: shouldQ=false priority=0.0
I180926 06:00:57.388962 74038 storage/split_queue.go:116  [n1,split,s1,r11/1:/Table/1{4-5}] shouldQueue: shouldQ=false priority=0.0
I180926 06:00:57.388980 74038 storage/split_queue.go:116  [n1,split,s1,r8/1:/Table/1{1-2}] shouldQueue: shouldQ=false priority=0.0
I180926 06:00:57.388999 74038 storage/split_queue.go:116  [n1,split,s1,r10/1:/Table/1{3-4}] shouldQueue: shouldQ=false priority=0.0
I180926 06:00:57.389017 74038 storage/split_queue.go:116  [n1,split,s1,r7/1:/Table/{SystemCon…-11}] shouldQueue: shouldQ=false priority=0.0
I180926 06:00:57.389034 74038 storage/split_queue.go:116  [n1,split,s1,r6/1:/{System/tse-Table/System…}] shouldQueue: shouldQ=false priority=0.0
I180926 06:00:57.389065 74038 storage/split_queue.go:116  [n1,split,s1,r5/1:/System/ts{d-e}] shouldQueue: shouldQ=false priority=0.0
I180926 06:00:57.389082 74038 storage/split_queue.go:116  [n1,split,s1,r3/1:/System/NodeLiveness{-Max}] shouldQueue: shouldQ=false priority=0.0
I180926 06:00:57.389097 74038 storage/split_queue.go:116  [n1,split,s1,r2/1:/System/{-NodeLive…}] shouldQueue: shouldQ=false priority=0.0
I180926 06:00:57.389313 74278 server/server_update.go:67  [n1] no need to upgrade, cluster already at the newest version
I180926 06:00:57.389377 74028 storage/split_queue.go:116  [n1,split,s1,r13/1:/Table/1{6-7}] shouldQueue: shouldQ=false priority=0.0
I180926 06:00:57.389394 74028 storage/split_queue.go:116  [n1,split,s1,r14/1:/{Table/17-Max}] shouldQueue: shouldQ=true priority=1.0
```

### PR DESCRIPTION
**Pull request by petermattis**
Fix a race during splits where the right-hand side of a split was
temporarily removed from the Store.mu.replicas map when the split was being
committed, opening a tiny window where that replica could be added to a
queue (e.g. the split queue) but not be present when it came time to
process the replica. The fix is to simply not perform this temporary
removal from Store.mu.replicas and instead adjust adding a replica to
Store.mu.replicas to be successful if the replica either doesn't exist in
the map, or does exist and is the same object (pointer equality).

Fixes #30660 Fixes #29144

Release note: None

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
I'd like to add a more targeted test for this race before this merges. My plan is a test that starts a test server while a goroutine sits in the background looping over the replicas and verifying that they are never temporarily removed. I'm open to a better suggestion.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30778#-:-LNWpUOZEPp1VKHmmdiw:b-pqo8cx)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by nvb — CHANGES_REQUESTED** [review]
:lgtm: 

> My plan is a test that starts a test server while a goroutine sits in the background looping over the replicas and verifying that they are never temporarily removed. I'm open to a better suggestion.

We could create a racetest-only replica tombstone map that sits on a Store and keeps track of replicas that have been removed. We could check this map in `addReplicaToRangeMapLocked` to make sure that removed replicas never get added back in. Something like that would have a much better chance of actually catching one of these bugs.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30778#-:-LNWzCR3-MVZsGdL9nLZ:bm83ial)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/store.go, line 2459 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30778#-LNWyied1xxRDcreu9zX:-LNWyied1xxRDcreu9zY:b-sct9d6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a237782b769afa112d0812c07db5c1b2f7cd474b/pkg/storage/store.go#L2459)):*
> ```Go
> 		// present in Store.mu.replicas.
> 		delete(s.mu.uninitReplicas, rightDesc.RangeID)
> 		s.replicaQueues.Delete(int64(rightDesc.RangeID))
> ```

Why do we need to remove the replica from the queues?

**Review by nvb — APPROVED** [review]

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30778)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/storage/store.go, line 2459 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30778#-LNWyied1xxRDcreu9zX:-LNX2blw4nkYJ9_YIs2N:b-o1wsn0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a237782b769afa112d0812c07db5c1b2f7cd474b/pkg/storage/store.go#L2459)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why do we need to remove the replica from the queues?
</blockquote></details>

I'm not sure. We've been doing it for a long time: https://github.com/cockroachdb/cockroach/blame/0b78bee63e24ad44aa6e372eb27c7cd20c10d48c/storage/store.go#L1576

**Review by petermattis — COMMENTED** [review]
> We could create a racetest-only replica tombstone map that sits on a Store and keeps track of replicas that have been removed. We could check this map in addReplicaToRangeMapLocked to make sure that removed replicas never get added back in. Something like that would have a much better chance of actually catching one of these bugs.

I did something sort of like this, but the map is external to the store and only used by the test. See `TestStoreWaitForInitialSplitsRace`. It triggers almost instantly under stress before this PR, and passes afterwards.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30778#-:-LNXAtrh3ZqI8ckqF98d:bigqaw2)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by nvb — APPROVED** [review]
Yeah, that looks good. It's only useful for tests that can't lose replicas due to merges or rebalancing, but that's fine. Still LGTM.

> Reviewed 1 of 1 files at r8, 2 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30778#-:-LNXC0TtCmT8H0K2eVdY:bxe9py2)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by petermattis** [comment]
Added another commit which reverts the verbose split-queue logging that was added in order to track down #29144/#30660.

**Comment by petermattis** [comment]
bors r=nvanbenschoten

**Pull request merged**
