### PR TITLE
log: secondary logger fixes

### PR DESCRIPTION
**Pull request by knz**
Needed by / will be exercised by  #45193

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45587#-:-M1R2C4S6-LBIqdIzl7M:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/util/log/secondary_log.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45587#-M1R1qHo0q_vjR0Vm4hv:-M1R15t08xwHChC_1GLv:bt12mu7) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a2e13c62333968f3f4cc40382ac43c9f864b01e/pkg/util/log/secondary_log.go#L95)):*
> ```Go
> 					continue
> 				}
> 				copy(secondaryLogRegistry.mu.loggers[i:], secondaryLogRegistry.mu.loggers[i+1:])
> ```

nit for readability:
```
secondaryLogRegistry.mu.loggers = append(secondaryLogRegistry.mu.loggers[:i], secondaryLogRegistry.mu.loggers[i+1:]...)
```

**Comment by knz** [comment]
> nit for readability

I think this solution is guaranteed to allocate, whereas mine is guaranteed to not allocate? Is that right? does it matter?

**Review by ajwerner — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45587)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/util/log/secondary_log.go, line 95 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45587#-M1R1qHo0q_vjR0Vm4hv:-M1RQxyz61BNQTvHo7b5:b-p3bnt4) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a2e13c62333968f3f4cc40382ac43c9f864b01e/pkg/util/log/secondary_log.go#L95)):*
> I think this solution is guaranteed to allocate, whereas mine is guaranteed to not allocate? Is that right? does it matter?

No, it will not allocate. The above suggestion should be semantically equivalent to the original. The sub-slice passed as the first argument to append will have the same `cap` as the whole slice. The append will then overwrite the tail of the underlying array and adjust the `len` field appropriately. If you wanted to force and allocation you can use the 3-form of slicing which would constrain the `cap` (see below but don't do it).

```
secondaryLogRegistry.mu.loggers = append(secondaryLogRegistry.mu.loggers[:i:i], secondaryLogRegistry.mu.loggers[i+1:]...)
```

**Review by ajwerner — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45587)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/util/log/secondary_log.go, line 83 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45587#-M1RRxVmBH7K5UQJJRF1:-M1RRxVmBH7K5UQJJRF2:b29j85r) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd3f7a7f55966f22c8d245b84083936fcb322bc4/pkg/util/log/secondary_log.go#L83)):*
> ```Go
> 
> 	// Make the registry forget about this logger when the context is
> 	// cancelled. This avoids stacking many secondary loggers together
> ```

gah the two spellings of `canceled`
___
*[pkg/util/log/secondary_log.go, line 87 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45587#-M1RRsRT7ehzltrq2i7s:-M1RRsRUEq_EFV7XWEkN:b-gjrphj) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd3f7a7f55966f22c8d245b84083936fcb322bc4/pkg/util/log/secondary_log.go#L87)):*
> ```Go
> 	// package.
> 	go func() {
> 		select {
> ```

The linter had a reasonable suggestion here to remove the select with a single case.

**Comment by knz** [comment]
Thanks, done.

bors r=ajwerner

**Comment by knz** [comment]
darn it
bors r=ajwerner

**Comment by ajwerner** [comment]
bors r=ajwerner

**Comment by knz** [comment]
okay one more time

bors r=ajwerner

**Pull request merged**
