### PR TITLE
closedts/sidetransport: fix goroutine leak

### PR DESCRIPTION
**Pull request by andreimatei**
Fix a goroutine leak caused by gRPC streams. It turns out that
receiving an error from an RPC's stream is not enough to cleanup the
stream, you need to do something else as described here
https://pkg.go.dev/google.golang.org/grpc#ClientConn.NewStream

This patch starts canceling the stream's context whenever the stream is
discarded.

Release note: None
Release justification: Bug fix for new functionality.

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61413)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/kvserver/closedts/sidetransport/sender.go, line 700 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61413#-MUtGWcN81L779nkrux2:-MUtGWcN81L779nkrux3:b-ai7cqi) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac8138d67f055c512853d86280d4ef1de0f2c85a/pkg/kv/kvserver/closedts/sidetransport/sender.go#L700)):*
> ```Go
> 					// and get a notification when it succeeds.
> 					if r.stream != nil {
> 						r.cleanupStream()
> ```

If we called `r.stream.CloseSend()` here, would that be sufficient? I'm not sure I understand why we need to call Close and cancel the context.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61413)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/closedts/sidetransport/sender.go, line 700 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61413#-MUtGWcN81L779nkrux2:-MUtHAqU4rqzoOSnyDxR:b47l6p3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac8138d67f055c512853d86280d4ef1de0f2c85a/pkg/kv/kvserver/closedts/sidetransport/sender.go#L700)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

If we called `r.stream.CloseSend()` here, would that be sufficient? I'm not sure I understand why we need to call Close and cancel the context.
</blockquote></details>

I don't think `CloseSend` is sufficient - at least not according to https://pkg.go.dev/google.golang.org/grpc#ClientConn.NewStream
Also I don't know if you're supposed to be calling `CloseSend`after a `Send` gave you an error. Although this stuff is not well documented, I think the cleanup that we need to perform is about the receiving side of the stream.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61413)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/kvserver/closedts/sidetransport/sender.go, line 700 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61413#-MUtGWcN81L779nkrux2:-MUtIK3X2OHlWNf1lj9h:b-x6tgau) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac8138d67f055c512853d86280d4ef1de0f2c85a/pkg/kv/kvserver/closedts/sidetransport/sender.go#L700)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I don't think `CloseSend` is sufficient - at least not according to https://pkg.go.dev/google.golang.org/grpc#ClientConn.NewStream
Also I don't know if you're supposed to be calling `CloseSend`after a `Send` gave you an error. Although this stuff is not well documented, I think the cleanup that we need to perform is about the receiving side of the stream.
</blockquote></details>

Oh, I see, it's the `ClientConn`, not the `SideTransportClient`. So should we hold on to the connection returned from `r.dialer.Dial(ctx, r.nodeID, rpc.SystemClass)` and `Close` that? Right now, I'm still not sure that canceling the context passed only to `PushUpdates` is sufficient.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61413)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/kvserver/closedts/sidetransport/sender.go, line 630 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61413#-MUtKztzE-O01z82sPs6:-MUtKztzE-O01z82sPs7:b-w7va2t) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac8138d67f055c512853d86280d4ef1de0f2c85a/pkg/kv/kvserver/closedts/sidetransport/sender.go#L630)):*
> ```Go
> 		r.stream, err = ctpb.NewSideTransportClient(conn).PushUpdates(streamCtx)
> 		if err != nil {
> 			return err
> ```

Do you want to cancel and clean up `r.cleanupStream` in this case?
___
*[pkg/kv/kvserver/closedts/sidetransport/sender.go, line 699 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61413#-MUtL76L9J17UoFDIS87:-MUtL76L9J17UoFDIS88:b-izfmeu) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac8138d67f055c512853d86280d4ef1de0f2c85a/pkg/kv/kvserver/closedts/sidetransport/sender.go#L699)):*
> ```Go
> 					// should have a blocking version of Dial() that we just leave hanging
> 					// and get a notification when it succeeds.
> 					if r.stream != nil {
> ```

Let's pull this and the deferred logic into a single `cleanupStream` method.
___
*[pkg/kv/kvserver/closedts/sidetransport/sender.go, line 700 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61413#-MUtGWcN81L779nkrux2:-MUtLANnEw9Pb2oaslHa:b-yo2bfp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac8138d67f055c512853d86280d4ef1de0f2c85a/pkg/kv/kvserver/closedts/sidetransport/sender.go#L700)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Oh, I see, it's the `ClientConn`, not the `SideTransportClient`. So should we hold on to the connection returned from `r.dialer.Dial(ctx, r.nodeID, rpc.SystemClass)` and `Close` that? Right now, I'm still not sure that canceling the context passed only to `PushUpdates` is sufficient.
</blockquote></details>

Doesn't seem to work.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61413)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/closedts/sidetransport/sender.go, line 630 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61413#-MUtKztzE-O01z82sPs6:-MUtPHnl4WW-B-pFiFwh:bw2j9cj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac8138d67f055c512853d86280d4ef1de0f2c85a/pkg/kv/kvserver/closedts/sidetransport/sender.go#L630)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do you want to cancel and clean up `r.cleanupStream` in this case?
</blockquote></details>

yes, see now
___
*[pkg/kv/kvserver/closedts/sidetransport/sender.go, line 699 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61413#-MUtL76L9J17UoFDIS87:-MUtQWbjBxZEdUZsK_28:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac8138d67f055c512853d86280d4ef1de0f2c85a/pkg/kv/kvserver/closedts/sidetransport/sender.go#L699)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's pull this and the deferred logic into a single `cleanupStream` method.
</blockquote></details>

done

**Review by nvb — APPROVED** [review]

**Review by RaduBerinde — COMMENTED** [review]
Thanks!! Any idea why leaktest didn't detect the leaked goroutines?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61413#-:-MUtRYEM3ZIxUAC8SPKC:bb96ag2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by andreimatei — COMMENTED** [review]
No, but I do want to check that.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61413#-:-MUtSbnp-9HqC-SkVhaK:b-t2lwi3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61413#-:-MUtcsx7-Q5c_lbBe16S:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by andreimatei — COMMENTED** [review]
bors r-

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61413#-:-MUtfYGr8675BGYXZkAd:b-616qm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by andreimatei — COMMENTED** [review]
bors r+ p=9999 single on

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61413#-:-MUtf_W9196x-ZzLUf-t:b-4iwluq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Pull request merged**
