### PR TITLE
sql: make zone configs much cheaper

### PR DESCRIPTION
**Pull request by ajwerner**
When we look up zone configs for a table, we figure out the inheritence by
looking at its parent. Once we find a parent, we don't get any value out
of decoding that parent. The problem is that the database descriptor has
a map that is O(schemas). This can lead to excessive CPU usage just decoding
the database descriptor for every range. There's no need for that. Let's
just skip it.

Relates to #60724. 

Release note (performance improvement): Improved logic in determining the
configuration for data to avoid expensive work when there are a large number
of user-defined schemas.

### CODE REVIEW

**Comment by ajwerner** [comment]
This ends up mattering a lot if you have a large number of schemas as the database stores them all. Before this change we'd decode the database descriptor at least once per range. Now we never decode it. This change is not a panacea but it is something. There's more that could be done but I wanted to do something that I could backport to 20.2. 


This CPU profile is from before the change:

Screenshot_2021-03-19 cockroach cpu

The below graph show the same migration with and without the change:

image

**Comment by ajwerner** [comment]
This is a 2 vCPU instance. In practice one is bound on processing the updates and the other on GC, or so it seems. This change helps. I've got another one to control how frequently we process these updates that I fear there may be less appetite to backport. 

image

**Review by postamar — APPROVED** [review]
LGTM assuming the roundtrips benchmark is the only test that failed as of now. I understand that that's expected with these changes.

**Comment by ajwerner** [comment]
> LGTM assuming the roundtrips benchmark is the only test that failed as of now. I understand that that's expected with these changes.

I actually don't understand what's going on with that. If I run them on master, I get what these test get. Makes me think there's skew but then again, I don't understand how we didn't catch that.

**Comment by ajwerner** [comment]
I'm confused.

**Comment by ajwerner** [comment]
Nevermind, it all makes sense, we avoid reading the database descriptor twice now. One on the complete path and once in the main path.

**Review by ajwerner — COMMENTED** [review]
TFTR!

bors r=postamar

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62280#-:-MWPQuJkCJBg8F7mlgj_:bdclo5q)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Comment by nvanbenschoten** [comment]
Very nice!

**Pull request merged**
