### PR TITLE
kvserver: remove replica GC heuristic for quiesced followers

### PR DESCRIPTION
**Pull request by erikgrinaker**
In #65062 we added a condition to the replica GC queue that quiescent
followers with a single unavailable voter would be considered suspect.
This was added to try to detect followers who were partitioned away from
the Raft group during its own removal from the range. However, this case
has a very high false positive rate, and on second thought it is probably
higher than it is worth.

There is already a secondary condition that considers followers who have
lost touch with their leader suspect, which would be somewhat sufficient
in this case, and with a far lower false positive rate. Even though this
heuristic is vulnerable to race conditions, it seems a better fit
considering that in the worst case the replica will always be GCed
within 12 hours anyway. We have also since moved range-level metrics
to the leaseholder, which reduces the impact of these stale replicas.

This patch therefore removes the quiescent replica condition, and
reduces `ReplicaGCQueueSuspectCheckInterval` from 5 to 3 seconds since
we now expect far fewer false positives.

Touches #65202.

Release note: None

/cc @cockroachdb/kv

### CODE REVIEW

**Review by tbg — APPROVED** [review]
It's interesting that this didn't affect a single test. We didn't have coverage for this case then, or rather the existing coverage actually fell into the `StateFollower` branch?

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65609#-:-Mb1mqjQCJbrHAbUvkbu:bxglo2x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

**Review by erikgrinaker — COMMENTED** [review]
We have unit tests for `replicaGCShouldQueueImpl` (i.e., given a suspect replica, make shorten the timeout and increase the priority), but not `replicaIsSuspect`. I was considering this when I restructured this code: the way I see it, it's usually more cost-effective to unit test mechanism but not policy, since policy typically changes much more frequently, and in this case the test would basically just mirror the branch conditions in the code which doesn't seem very useful.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65609#-:-Mb1ubDC9AkRu7nIz2Rw:b-mgphyk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

**Review by tbg — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/65609#-:-Mb1x6xu7H0krKcJIwUm:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @erikgrinaker)

**Comment by erikgrinaker** [comment]
bors r=tbg

**Pull request merged**
