### PR TITLE
roachtest: remove COCKROACH_DISABLE_LEADER_FOLLOWS_LEASEHOLDER from `failover` tests

### LINKED ISSUE #125259: kv: remove COCKROACH_DISABLE_LEADER_FOLLOWS_LEASEHOLDER
Part of https://github.com/cockroachdb/cockroach/issues/123847.

From [prototype doc](https://docs.google.com/document/d/1zai1PAh6MwDMIIt6LxOR33KOaqctSs7fOKmHaGBENpw/edit):

> To validate this requirement, we manually test out the indefinite outage scenario from the failover/partial/lease-leader test ([reference](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/tests/failover.go#L520)) with the prototype. We can’t run the roachtest directly, because it (ab)uses the `COCKROACH_DISABLE_LEADER_FOLLOWS_LEASEHOLDER` environment variable to configure a split leader and epoch-leaseholder configuration. Instead, we do something better and create the type of network partition that would lead to a split leader+leaseholder configuration in a real environment.
>
> To do so, our test creates a network partition between a leader+leaseholder and its two followers. However, it keeps the leader+leaseholder node connected to the node liveness range. This allows epoch-based leases to be extended even when the leaseholder cannot contact the rest of its peers. The outage persists as long as the lease is held by the partitioned node.
>
> We will update the roachtest to do something similar and not rely on the test-only environment variable.

Jira issue: CRDB-39350

Epic CRDB-37522

### PR DESCRIPTION
**Pull request by nvb**
Fixes #125259.

This commit removes the use of COCKROACH_DISABLE_LEADER_FOLLOWS_LEASEHOLDER from the `failover/partial/lease-leader` tests. Instead of using the cluster setting to disable leader follows leaseholder, the tests now creates the kind of situation where leader and leaseholder could be split indefinitely when using epoch-based leases.

This is more realistic and allows us to test lease+leader failover with leader leases when the leaseholder gets partitioned from its followers but remains connected to the liveness range.

I confirmed that by default, both the epoch-based and expiration-based lease variants of this test still fail at 60s due to stuck requests. This is what we see in roachperf on master as well:
- https://roachperf.crdb.dev/?filter=leader&view=failover%2Fpartial%2Flease-leader&tab=gce
- https://roachperf.crdb.dev/?filter=leader&view=failover%2Fpartial%2Flease-leader%2Flease%3Dexpiration&tab=gce

However, notice that the expiration-based variant temporarily improved when we enabled DistSender circuit breakers, which add a timeout to all KV requests. This is because the expiration-based lease setup can actually recover range availability, we just don't currently unwedge requests that were stuck before the recovery. This is of arguable importance, as most real-world users run with application side timeouts. Regardless, I see the same improvement if I re-enable DistSender circuit breakers. With them, `failover/partial/lease-leader` stays at 60s (infinite) recovery time while `failover/partial/lease-leader/lease=expiration` drops to recovering in ~20s.

Release note: None

### CODE REVIEW

**Review by arulajmani — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129844#-:-O5Tc2V_BXKdUxf9KBRT:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong, @miraradeva, @nvanbenschoten, and @vidit-bhat)

___
*[`pkg/cmd/roachtest/tests/failover.go` line 532 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129844#-O5Tbjc3BCCFFGYSmdGT:-O5Tbjc3BCCFFGYSmdGU:b-u6wy16) ([raw file](https://github.com/cockroachdb/cockroach/blob/8da8a9104c6c5c6e92e7347f39313416a82b0412/pkg/cmd/roachtest/tests/failover.go#L532)):*
> ```Go
> // other two nodes but is still able to reach the liveness range. This will
> // cause split leader/leaseholder scenarios if raft leadership fails over from a
> // partitioned node but the lease does not. We expect this to be a problem for
> ```

nit: fails over from a partitioned node (due to check quorum) but the lease does not.

**Review by miraradeva — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129844#-:-O5TdYLPCVQbendabFvq:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @DarrylWong, @nvanbenschoten, and @vidit-bhat)

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129844)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @arulajmani, @DarrylWong, and @vidit-bhat)

___
*[`pkg/cmd/roachtest/tests/failover.go` line 532 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/129844#-O5Tbjc3BCCFFGYSmdGT:-O5TnJA042qmmSZuO_CY:b5hm24r) ([raw file](https://github.com/cockroachdb/cockroach/blob/8da8a9104c6c5c6e92e7347f39313416a82b0412/pkg/cmd/roachtest/tests/failover.go#L532)):*
> due to check quorum

These cases never need check quorum to fail over. The leader is completely partitioned from its followers, so even without check quorum, the other two followers will independently campaign and recover. I don't actually think check quorum is needed until RF=4 (with a config like the RF=5 config from https://decentralizedthoughts.github.io/2020-12-12-raft-liveness-full-omission/).

**Review by nvb — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129844#-:-O5UIxfwAdnfk9wLlgiH:b-ydi9ay)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @arulajmani, @DarrylWong, and @vidit-bhat)

**Pull request merged**
