### PR TITLE
sql: de-flake TestDistSQLFlowsVirtualTables

### LINKED ISSUE #75208: sql: TestDistSQLFlowsVirtualTables failed
sql.TestDistSQLFlowsVirtualTables [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4162676&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4162676&tab=artifacts#/) on master @ [fb72381cab272a4f03871032cc2195e97c11260a](https://github.com/cockroachdb/cockroach/commits/fb72381cab272a4f03871032cc2195e97c11260a):

```
=== RUN   TestDistSQLFlowsVirtualTables
    test_log_scope.go:79: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestDistSQLFlowsVirtualTables3497067877
    test_log_scope.go:80: use -show-logs to present logs inline
=== CONT  TestDistSQLFlowsVirtualTables
    crdb_internal_test.go:550: stalling on scan at /Table/56/1/1 and waiting for test to unblock...
    crdb_internal_test.go:550: stalling on scan at /Table/56/1/2 and waiting for test to unblock...
    crdb_internal_test.go:550: stalling on scan at /Table/56/1 and waiting for test to unblock...
=== CONT  TestDistSQLFlowsVirtualTables
    crdb_internal_test.go:721: -- test log scope end --
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestDistSQLFlowsVirtualTables3497067877
--- FAIL: TestDistSQLFlowsVirtualTables (11.02s)
=== RUN   TestDistSQLFlowsVirtualTables/MaxRunningFlows=0
    crdb_internal_test.go:641: waiting for remote flows to be scheduled or run
    crdb_internal_test.go:659: checking the virtual tables
    crdb_internal_test.go:688: unexpected output from cluster_distsql_flows on node 3
    --- FAIL: TestDistSQLFlowsVirtualTables/MaxRunningFlows=0 (1.53s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
Parameters in this failure:

- GOFLAGS=-json
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestDistSQLFlowsVirtualTables.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by irfansharif**
Fixes #75208 (speculatively). Wasn't able to repro the original failure,
so here's a blind stab at fixing it. See [this](github.com/cockroachdb/cockroach/issues/75208#issuecomment-1023800242) for the theory; I think
it's possible for the query this test fires off to error out + get
dequeued concurrently with when the assertions are made about it being
enqueued. We should relax our assertions accordingly.

Release note: None

### CODE REVIEW

**Comment by irfansharif** [comment]
Aside: I'm not really sure how #73876 caused this to flake more often. After staring at this test for hours I'm not really sure it's uncovering bugs in the span configs infra as much as shaking out latent flakiness in the test itself (which I still can't repro, 4hrs later). I'd be happy to hand off further investigation here to folks more familiar with this area if this PR ends up being insufficient.

**Comment by irfansharif** [comment]
Actually I'm pretty sure it's that, this test has a pretty aggressive timeout for the query and the failing runs certainly take longer:

https://github.com/cockroachdb/cockroach/blob/eb2a5cfcf21a24efe93460b3a1df1630e9478541/pkg/sql/crdb_internal_test.go#L594-L595

We could alternatively make the timeout less aggressive.

**Review by yuzefovich — APPROVED** [review]
Indeed, I think this 1 second timeout is the cause of flakiness - in all failures in #75208 we see an output like
```
FAIL: TestDistSQLFlowsVirtualTables/MaxRunningFlows=0 (1.53s)
```
and the test run time is always greater than 1 second.

I'm also not sure how span config work caused this to flake more often, and I agree that it looks like the test problem, so apologies for pushing this flake to you. Thanks for figuring it out though!

:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75638#-:-MuTz4fU3h-KyfgQfHvx:b-dfnda0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @arulajmani)

**Comment by irfansharif** [comment]
Thanks!

bors r+

**Pull request merged**
