### PR TITLE
vendor: bump twpayne/go-geom to v1.1.0

### PR DESCRIPTION
**Pull request by otan**
Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49340#-:-M7nQBGg9kP8d9i3dbfU:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by otan** [comment]
bors r=rytaft

**Comment by otan** [comment]
bors r=rytaft

**Pull request merged**
