### PR TITLE
rowexec: fix some issues with aggregation

### LINKED ISSUE #45975: rowexec: panic in HashMemRowContainer.AddRowToBucket
[(roachtest).sqlsmith/setup=seed/setting=no-ddl failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=1801614&tab=buildLog) on [master@5570c01402796edb7cd06eb8ce7f615371f22d42](https://github.com/cockroachdb/cockroach/commits/5570c01402796edb7cd06eb8ce7f615371f22d42):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/20200311-1801614/sqlsmith/setup=seed/setting=no-ddl/run_1
	sqlsmith.go:185,sqlsmith.go:199,test_runner.go:747: ping: dial tcp 35.225.170.171:26257: connect: connection refused
		previous sql:
		INSERT
		INTO
			defaultdb.public.seed AS tab_827
		SELECT
			(-6769):::INT8 AS col_1997,
			(-1885658008):::INT8 AS col_1998,
			((-3617870019796154521):::INT8::INT8 % ((-7829511338012323029):::INT8::INT8 % (999754452227079239:::INT8::INT8 % 1457631285488654207:::INT8::INT8)::INT8::INT8)::INT8::INT8)::INT8
				AS col_1999,
			2.145972490310669:::FLOAT8 AS col_2000,
			(-0.19535191773842797):::FLOAT8 AS col_2001,
			'1981-07-24':::DATE AS col_2002,
			'1970-01-04 21:49:21.000481+00:00':::TIMESTAMP AS col_2003,
			NULL AS col_2004,
			age('0001-01-01 00:00:00+00:00':::TIMESTAMPTZ::TIMESTAMPTZ, '1970-01-10 22:07:11.000203+00:00':::TIMESTAMPTZ::TIMESTAMPTZ)::INTERVAL
				AS col_2005,
			(NOT false) AS col_2006,
			NULL AS col_2007,
			COALESCE('5':::STRING, NULL) AS col_2008,
			'\x18406acd731524e7':::BYTES AS col_2009,
			'b0f2d274-349b-4531-ad83-a3ada0835b0b':::UUID AS col_2010,
			'5020:9e29:e0f:fb13:59e5:29ec:1ed8:3217/57':::INET AS col_2011,
			'{"87/": [], ">]D8FaLq<k": [[null, {}], 1.6002049925945476, [], {}], "`H4duM[": [{"hSdIH<h{O": []}], "b": [[], "#3?~%$>54jh"], "vlEW": null}':::JSONB
				AS col_2012
		LIMIT
			39:::INT8;

	cluster.go:1410,context.go:135,cluster.go:1399,test_runner.go:801: dead node detection: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod monitor teamcity-1801614-1583911542-16-n4cpu4 --oneshot --ignore-empty-nodes: exit status 1 2: 6656
		3: 6734
		4: 5083
		1: dead
		Error:  1: dead

```

<details><summary>More</summary><p>

Artifacts: [/sqlsmith/setup=seed/setting=no-ddl](https://teamcity.cockroachdb.com/viewLog.html?buildId=1801614&tab=artifacts#/sqlsmith/setup=seed/setting=no-ddl)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Asqlsmith%2Fsetup%3Dseed%2Fsetting%3Dno-ddl.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by yuzefovich**
Release justification: fixes for high-priority or high-severity bugs in
existing functionality (we were incorrectly doing memory accounting plus
performing some unnecessary copies and allocations).

This commit fixes a couple of problems with aggregation in row-by-row
engine:
1. the memory under the "lastOrdGroupCols" row is not accounted for, and
a new row was always allocated. This leads to significant drift in memory
accounting. This is now fixed by allocating the row only once and
reusing the same memory later (with the memory being not accounted for,
but that's ok).
2. the overhead of `aggregateFuncs` slice hasn't been accounted for.
3. `bucketIter` slice of strings (which captures a particular order of
items in `buckets` map making it fixed) hasn't been accounted for.
4. memory internal to Golang's map (for `buckets`) hasn't been accounted
for. I don't think we can reliably get that memory's size, so we're
employing some heuristics to get the estimate. The updates to memory
accounts occur only on logarithmic scale in order to not degrade the
performance.

Also, this commit refactors `canAdd` function to make its purpose more
clear.

Fixes: #45975.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
I'm continuing digging into this, and I think there are more places in which we don't account for allocated memory. I'll ping this when it is RFAL. (Or that could be follow-up work since this commit is already a step in the right direction.)

**Comment by yuzefovich** [comment]
Friendly ping @asubiotto @jordanlewis since it is a release blocker (and it possibly blocks investigation of another release blocker).

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46162)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/sql/rowexec/aggregator.go, line 610 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46162#-M2inZuM-ip4fJPoAMlF:-M2inZuM-ip4fJPoAMlG:b-7g41wx) ([raw file](https://github.com/cockroachdb/cockroach/blob/69d05693d9532d75982deb1d5b0fa90c1183d611/pkg/sql/rowexec/aggregator.go#L610)):*
> ```Go
> 		// 'buckets' map (except for the case when that number if below our
> 		// initial length estimate - then, we have accounted for any items).
> 		accountedForMapItems := ag.bucketsLenGrowThreshold / 2
> ```

Not sure why we're making a decision here. Could we use `Resize` to make this easier to read?
___
*[pkg/sql/rowexec/aggregator.go, line 824 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46162#-M2imQbu1jcJLQEdlYfF:-M2imQbu1jcJLQEdlYfG:b-3rrzto) ([raw file](https://github.com/cockroachdb/cockroach/blob/69d05693d9532d75982deb1d5b0fa90c1183d611/pkg/sql/rowexec/aggregator.go#L824)):*
> ```Go
> 		ag.buckets[s] = bucket
> 		if len(ag.buckets) == ag.bucketsLenGrowThreshold {
> 			if err := ag.bucketsAcc.Grow(ag.Ctx, int64(ag.bucketsLenGrowThreshold)*hashAggregatorSizeOfBucketsItem); err != nil {
> ```

Shouldn't this be an incremental `Grow`? i.e. we know we've already accounted for half of these items, so we only need to `Grow` by `bucketsLenGrowThreshold/2`

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46162)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/rowexec/aggregator.go, line 610 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46162#-M2inZuM-ip4fJPoAMlF:-M2iwJ448JmuVSFpgpx2:buvg8vc) ([raw file](https://github.com/cockroachdb/cockroach/blob/69d05693d9532d75982deb1d5b0fa90c1183d611/pkg/sql/rowexec/aggregator.go#L610)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Not sure why we're making a decision here. Could we use `Resize` to make this easier to read?
</blockquote></details>

The complication here is that many components are growing this `bucketsAcc`, so we cannot just resize to some initial number. We're making this decision here because we're creating a new `map` below, and initially we want no memory to be accounted for in that map, so we need to subtract whatever we have accounted for in the about-to-be-released map.
___
*[pkg/sql/rowexec/aggregator.go, line 824 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46162#-M2imQbu1jcJLQEdlYfF:-M2ixjV58qJ-5rmHqWMU:bl4hm9q) ([raw file](https://github.com/cockroachdb/cockroach/blob/69d05693d9532d75982deb1d5b0fa90c1183d611/pkg/sql/rowexec/aggregator.go#L824)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Shouldn't this be an incremental `Grow`? i.e. we know we've already accounted for half of these items, so we only need to `Grow` by `bucketsLenGrowThreshold/2`
</blockquote></details>

Yes, you're right, fixed.

This double counting must have been the reason for why I saw the reported memory usage increase about twice as big as I expected in some tests that I ran. My initial estimate was 64 bytes for an "item" which I then lowered to 32 to make it more inline with my expectations. Now I bumped it back up to 64.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46162#-:-M2jNmq6E942-lJbckFD:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by yuzefovich** [comment]
@asubiotto @jordanlewis do you guys think we should backport this? I think so.

**Comment by asubiotto** [comment]
Yes, I think so

**Pull request merged**
