### PR TITLE
replicastats: miscellaneous improvements

### PR DESCRIPTION
**Pull request by yuzefovich**
See each commit for details.

Epic: None

Release note: None

### CODE REVIEW

**Review by kvoli — APPROVED** [review]

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by yuzefovich** [comment]
Thoughts on backporting this @kvoli @nvanbenschoten? Seems like a pretty safe change that would benefit large clusters.

**Comment by kvoli** [comment]
> Thoughts on backporting this @kvoli @nvanbenschoten? Seems like a pretty safe change that would benefit large clusters.

I'm pro backporting. Seems like an impactful change for minimal risk.

**Comment by yuzefovich** [comment]
Sounds good, I'll open up backports to 23.2 and 24.1 and we can discuss more whether to merge them there.

blathers backport release-24.1
blathers backport release-23.2

**Comment by yuzefovich** [comment]
blathers backport release-23.2

**Pull request merged**
