### PR TITLE
sql: set hash-sharded index column type to INT8

### PR DESCRIPTION
**Pull request by mgartner**
Shard columns of hash-sharded indexes are computed columns with an
expression in the form `mod(fnv32(crdb_internal.datums_to_bytes(...)))`.
The `mod()` builtin returns a value of type `INT8`, while the shard
column's type was previously `INT4`. Because these types did not match,
`mod` expressions were wrapped in the assignment cast function,
`crdb_internal.assignment_cast`, in mutation query plans.

This commit changes the type of newly created shard columns to `INT8`,
eliminating the need for an assignment cast. Because all integers are
encoded as varints in keys and values, this will not increase the amount
of space on disk required for these columns.

Release justification: This is a minor change to hash-sharded indexes,
which are a newly un-experimentalized feature in the upcoming release.

Release note (sql change): The type of shard columns created for
hash-sharded indexes have changed from `INT4` to `INT8`. This should
have no effect on behavior or performance.

### CODE REVIEW

**Review by chengxiong-ruan — APPROVED** [review]
This is awesome~

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76930#-:-MwbRVevBcFew8Xk_3vE:b-glzdm4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

**Review by michae2 — COMMENTED** [review]
Does this mean we could / should use `fnv64` instead of `fnv32`?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76930#-:-MwbaJhq89lpPX0K2nvC:b30wglo)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

**Review by mgartner — COMMENTED** [review]
> Does this mean we could / should use fnv64 instead of fnv32?

I think this would only be useful when the bucket count is greater than `2^32 - 1`, which seems unlikely. In fact, I just tried to create a hash-sharded index with a bucket count of `999999999` (which is less than `2^32 - 1`), and the `CREATE TABLE` statement locked up. I created an issue to track this: https://github.com/cockroachdb/cockroach/issues/77000.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76930#-:-Mwh7L3JBmiOXmgqnRFy:bj728y9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by mgartner** [comment]
@ajwerner can you take a look at this and sign-off if you're ok with it.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76930#-:-MxfOvNtDenMEwDS8U9P:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
