### PR TITLE
sql: deflake TestDropWhileBackfill

### LINKED ISSUE #77881: sql: TestDropWhileBackfill failed
sql.TestDropWhileBackfill [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4582385&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4582385&tab=artifacts#/) on master @ [be54b854824dc00dea8e3cf6289a1b020621c491](https://github.com/cockroachdb/cockroach/commits/be54b854824dc00dea8e3cf6289a1b020621c491):

```
=== RUN   TestDropWhileBackfill
    test_log_scope.go:79: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestDropWhileBackfill3173526640
    test_log_scope.go:80: use -show-logs to present logs inline
    schema_changer_test.go:816: expected 402 key value pairs, but got 442
    panic.go:661: -- test log scope end --
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestDropWhileBackfill3173526640
--- FAIL: TestDropWhileBackfill (15.09s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
Parameters in this failure:

- GOFLAGS=-json
</p>
</details>
/cc @cockroachdb/sql-schema
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestDropWhileBackfill.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-13808

### PR DESCRIPTION
**Pull request by ajwerner**
Fixes #77881

Release justification: non-production code changes

Release note: None

### CODE REVIEW

**Review by fqazi — APPROVED** [review]

**Review by stevendanna — APPROVED** [review]
Thank you!

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Comment by yuzefovich** [comment]
Looks like the test is still failing with this PR.

**Comment by stevendanna** [comment]
Oh, I think this PR is actually a bit off.  We need to move the wait until after

```
	// Wait until the schema change is done.
	wg.Wait()
```

since the clean up job isn't guaranteed to be enqueued until then.

**Comment by ajwerner** [comment]
Done.

**Comment by ajwerner** [comment]
Okay, I figured this out. It wasn't the temp index. Nobody writes to the temp index after we start creating it, so it can't be that. It's that we let the backfill go. I'm not sure why this wasn't flaky before.

**Comment by ajwerner** [comment]
`3251 runs so far, 0 failures, over 10m30s`

I'm calling it. It usually would fail in ~500

**Pull request merged**
