### PR TITLE
kvserver,sql: hook up stores to crdb_internal vtables/builtins

### PR DESCRIPTION
**Pull request by irfansharif**
We've built a fair share of crdb_internal.* builtins to directly
read/modify in-memory state, or issue useful requests. They come in
handy during escalations when it's helpful to read internal state that
isn't logged already, or something we've exported a metric over. They
also provide a conduit for out-of-band operations we've found ourselves
reaching for during incidents.

That said, these builtins weren't previously able to access KV state. It
was only because we were missing pre-requisite plumbing to make that
happen -- something this commit introduces. To motivate this further,
this commit introduces two possibly-helpful primitives, one of which we
had to previously use the (janky) advanced debug page for:

    SELECT crdb_internal.kv_set_queue_active(false, 'replicate');
    SELECT crdb_internal.kv_enqueue_replica($rangeid, 'mvccGC', true);

These built-ins execute on the gateway and is able to access the node's
embedded stores directly. It does it through this thin interface:

    // Store is an adapter to the underlying KV store.
    type Store interface {
      // StoreID returns the store identifier.
      StoreID() roachpb.StoreID

      // Enqueue the replica with the given range ID into the named queue.
      Enqueue(
        ctx context.Context,
        queue string,
        rangeID roachpb.RangeID,
        skipShouldQueue bool,
      ) error

      // SetQueueActive disables/enables the named queue.
      SetQueueActive(active bool, queue string) error
    }

The hope here is that we can continue to add whatever relevant
knobs/controls we find ourselves wanting to this interface and easily
expose as crdb_internal.kv_* builtins. If these prove to be useful and
we have a desire to access them even outside of SQL, this commit does
not preclude backing this functionality through explicit RPCs. In future
PRs we also envision exposing read-only access to in-memory KV state
through these builtins; think "a store's view of its liveness state" or
"reading a specific field off of a replica".

Release justification: low risk, high benefit
Release note: None

Jira issue: CRDB-14804

### CODE REVIEW

**Comment by irfansharif** [comment]
```
WARNING: DATA RACE
Read at 0x00c006de024f by goroutine 1686:
  github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestStrictGCEnforcement.func19.2()
      github.com/cockroachdb/cockroach/pkg/kv/kvserver_test/pkg/kv/kvserver/client_replica_test.go:3669 +0x34
```

CI failure is just https://github.com/cockroachdb/cockroach/pull/77806, safe to ignore here.

**Review by AlexTalks — CHANGES_REQUESTED** [review]
This looks super useful, nice work!  Had a couple naming issues, and then the main issue I see is making sure these functions are  privileged to only admins.  It looks like the tenant case is taken care of (as unsupported) as well.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77847#-:-MyyNa1QDWZDnvc8lDQB:b-uhfcp0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @erikgrinaker, @irfansharif, and @nvanbenschoten)

___
*[pkg/kv/kvserver/stores_base.go, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77847#-MyyKINgBJ3yF-KmlvlC:-MyyKINgBJ3yF-KmlvlD:bwxjyy4) ([raw file](https://github.com/cockroachdb/cockroach/blob/440108ed060080ff3f6a9555e6c4ff4196e67166/pkg/kv/kvserver/stores_base.go#L24)):*
> ```Go
> 
> // StoresBase is the concrete implementation of kvserverbase.Stores.
> type StoresBase struct {
> ```

nit: this nomenclature may be a bit confusing.  There is no `kvserverbase.Stores`, this type is actually an implementation of `kvserverbase.StoresIterator`, it wraps `kvserver.Stores`, and also `StoresBase` sounds like it would be an interface rather than an implementation / wrapper.  Not to :bike: :house: too much, but consider cleaning up the names if possible?  Maybe change the one in `kvserverbase` to `StoresIteratorBase` and this could be changed to `StoresIterator`?
___
*[pkg/kv/kvserver/stores_base.go, line 48 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77847#-MyyLeQc8uTI_K4CQOzI:-MyyLeQc8uTI_K4CQOzJ:bcr89jx) ([raw file](https://github.com/cockroachdb/cockroach/blob/440108ed060080ff3f6a9555e6c4ff4196e67166/pkg/kv/kvserver/stores_base.go#L48)):*
> ```Go
> 
> // StoreBase is the concrete implementation of kvserverbase.Store.
> type StoreBase struct {
> ```

nit: similarly confusing as above.
___
*[pkg/sql/sem/builtins/builtins.go, line 6556 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77847#-MyyMQKe6z0bfN1CEdlA:-MyyMQKfEuG-BTzyPqfq:b-ol99tc) ([raw file](https://github.com/cockroachdb/cockroach/blob/440108ed060080ff3f6a9555e6c4ff4196e67166/pkg/sql/sem/builtins/builtins.go#L6556)):*
> ```Go
> 			ReturnType: tree.FixedReturnType(types.Bool),
> 			Fn: func(ctx *tree.EvalContext, args tree.Datums) (tree.Datum, error) {
> 				active := bool(tree.MustBeDBool(args[0]))
> ```

Perhaps this should first have some priv checking?  e.g. `isAdmin, err := ctx.SessionAccessor.HasAdminRole(ctx.Context)`, etc.
___
*[pkg/sql/sem/builtins/builtins.go, line 6580 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77847#-MyyMltv5pQ1ihIC1Dwy:-MyyMltv5pQ1ihIC1Dwz:bpv6fe0) ([raw file](https://github.com/cockroachdb/cockroach/blob/440108ed060080ff3f6a9555e6c4ff4196e67166/pkg/sql/sem/builtins/builtins.go#L6580)):*
> ```Go
> 			ReturnType: tree.FixedReturnType(types.Bool),
> 			Fn: func(ctx *tree.EvalContext, args tree.Datums) (tree.Datum, error) {
> 				active := bool(tree.MustBeDBool(args[0]))
> ```

Priv checking here as well.
___
*[pkg/sql/sem/builtins/builtins.go, line 6621 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77847#-MyyMs6U8fGOcyDYPaT8:-MyyMs6U8fGOcyDYPaT9:bpv6fe0) ([raw file](https://github.com/cockroachdb/cockroach/blob/440108ed060080ff3f6a9555e6c4ff4196e67166/pkg/sql/sem/builtins/builtins.go#L6621)):*
> ```Go
> 			ReturnType: tree.FixedReturnType(types.Bool),
> 			Fn: func(ctx *tree.EvalContext, args tree.Datums) (tree.Datum, error) {
> 				rangeID := roachpb.RangeID(tree.MustBeDInt(args[0]))
> ```

Priv checking here as well.
___
*[pkg/sql/sem/builtins/builtins.go, line 6661 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77847#-MyyNM6R-__FX1hS4Goz:-MyyNM6R-__FX1hS4Gp-:bpv6fe0) ([raw file](https://github.com/cockroachdb/cockroach/blob/440108ed060080ff3f6a9555e6c4ff4196e67166/pkg/sql/sem/builtins/builtins.go#L6661)):*
> ```Go
> 			ReturnType: tree.FixedReturnType(types.Bool),
> 			Fn: func(ctx *tree.EvalContext, args tree.Datums) (tree.Datum, error) {
> 				rangeID := roachpb.RangeID(tree.MustBeDInt(args[0]))
> ```

Priv checking here as well.

**Comment by andreimatei** [comment]
Is it time to move to a model where different packages can register builtins, instead of all of them being in the `sem` package?

**Comment by ajwerner** [comment]
>  Is it time to move to a model where different packages can register builtins, instead of all of them being in the sem package?

I dream of this sometimes. It's not exactly clear how to let builtins express their dependencies. I'm sure we could come up with something. https://github.com/cockroachdb/cockroach/issues/60547 is a good place to stash any ideas or votes in favor of such a refactor.

**Review by irfansharif — COMMENTED** [review]
I'm going to be lazy and leave the builtins/sem refactor to smarter people. I'm also hoping to backport this patch to 22.1 so keeping it small intentionally.

@alextalks PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77847#-:-Mz_l5hP60lk0aoBoDkV:b-uemppg)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @AlexTalks, @arulajmani, @erikgrinaker, and @nvanbenschoten)

___
*[pkg/kv/kvserver/stores_base.go, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77847#-MyyKINgBJ3yF-KmlvlC:-Mz_lCB_3DuItWXU4RJo:bkl08u) ([raw file](https://github.com/cockroachdb/cockroach/blob/440108ed060080ff3f6a9555e6c4ff4196e67166/pkg/kv/kvserver/stores_base.go#L24)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

nit: this nomenclature may be a bit confusing.  There is no `kvserverbase.Stores`, this type is actually an implementation of `kvserverbase.StoresIterator`, it wraps `kvserver.Stores`, and also `StoresBase` sounds like it would be an interface rather than an implementation / wrapper.  Not to :bike: :house: too much, but consider cleaning up the names if possible?  Maybe change the one in `kvserverbase` to `StoresIteratorBase` and this could be changed to `StoresIterator`?
</blockquote></details>

Renamed, and made `baseStore` package internal + got rid of the confusingly named constructor.
___
*[pkg/sql/sem/builtins/builtins.go, line 6556 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77847#-MyyMQKe6z0bfN1CEdlA:-Mz_l8gIEPgmcCVPLtxg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/440108ed060080ff3f6a9555e6c4ff4196e67166/pkg/sql/sem/builtins/builtins.go#L6556)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

Perhaps this should first have some priv checking?  e.g. `isAdmin, err := ctx.SessionAccessor.HasAdminRole(ctx.Context)`, etc.
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/builtins.go, line 6580 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77847#-MyyMltv5pQ1ihIC1Dwy:-Mz_lAZF0BEU0El06PGc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/440108ed060080ff3f6a9555e6c4ff4196e67166/pkg/sql/sem/builtins/builtins.go#L6580)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

Priv checking here as well.
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/builtins.go, line 6621 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77847#-MyyMs6U8fGOcyDYPaT8:-Mz_lB3420dXMgtPijmZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/440108ed060080ff3f6a9555e6c4ff4196e67166/pkg/sql/sem/builtins/builtins.go#L6621)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

Priv checking here as well.
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/builtins.go, line 6661 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77847#-MyyNM6R-__FX1hS4Goz:-Mz_lBePDrWkJnFBgy_2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/440108ed060080ff3f6a9555e6c4ff4196e67166/pkg/sql/sem/builtins/builtins.go#L6661)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

Priv checking here as well.
</blockquote></details>

Done.

**Review by nvb — APPROVED** [review]
:lgtm_strong: 

> Reviewed 7 of 19 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77847#-:-Mzq6j-uAyE-Czsyp7Ly:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @AlexTalks, @arulajmani, @erikgrinaker, and @irfansharif)

___
*[pkg/kv/kvserver/stores_base.go, line 49 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77847#-Mzq50KQBZwKmE534V6B:-Mzq50KQBZwKmE534V6C:b-c45lci) ([raw file](https://github.com/cockroachdb/cockroach/blob/66c44b0b744317032994ecb2bfbaab223720e4f9/pkg/kv/kvserver/stores_base.go#L49)):*
> ```Go
> 
> // baseStore is the concrete implementation of kvserverbase.Store.
> type baseStore struct {
> ```

nit: we can avoid the heap allocations whenever we package pointers up into interfaces by changing this to:
```
type StoresIterator Stores
type baseStore Store

func MakeStoresIterator(stores *Stores) *StoresIterator {
	return (*StoresIterator)(stores)
}

...
    err = f((*baseStore)(store))
``` 

And then implement the interfaces on pointer receivers.
___
*[pkg/kv/kvserver/stores_base.go, line 84 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77847#-Mzq5X926FmrQsGVZzCN:-Mzq5X926FmrQsGVZzCO:b-rrqazp) ([raw file](https://github.com/cockroachdb/cockroach/blob/66c44b0b744317032994ecb2bfbaab223720e4f9/pkg/kv/kvserver/stores_base.go#L84)):*
> ```Go
> 	for _, rq := range s.store.scanner.queues {
> 		if strings.EqualFold(rq.Name(), queue) {
> 			kvQueue = rq
> ```

nit: `break` after this
___
*[pkg/kv/kvserver/kvserverbase/stores.go, line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77847#-Mzq5jyT0wMRyLSwAL-8:-Mzq5jyT0wMRyLSwAL-9:b42asf0) ([raw file](https://github.com/cockroachdb/cockroach/blob/66c44b0b744317032994ecb2bfbaab223720e4f9/pkg/kv/kvserver/kvserverbase/stores.go#L50)):*
> ```Go
> // ForEachStore is part of the StoresIterator interface.
> func (i UnsupportedStoresIterator) ForEachStore(f func(Store) error) error {
> 	return errors.New("unsupported in multi-tenancy mode")
> ```

Should this be using `errorutil.UnsupportedWithMultiTenancy`?
___
*[pkg/sql/sem/builtins/builtins.go, line 6636 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77847#-Mzq64Sw1vmYAd6zUcR4:-Mzq64SxB7vZlsGFGS98:b46yv5) ([raw file](https://github.com/cockroachdb/cockroach/blob/66c44b0b744317032994ecb2bfbaab223720e4f9/pkg/sql/sem/builtins/builtins.go#L6636)):*
> ```Go
> 		tree.Overload{
> 			Types: tree.ArgTypes{
> 				{"active", types.Bool},
> ```

nit: I would have expected the queue name to come before the active flag. No need to change unless you agree that that would be more natural.

**Review by irfansharif — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77847#-:-Mzr8X35DVnCAukqW2x-:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @AlexTalks, @arulajmani, @erikgrinaker, and @nvanbenschoten)

___
*[pkg/kv/kvserver/stores_base.go, line 49 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77847#-Mzq50KQBZwKmE534V6B:-Mzr8T918MfBvvzQyaGw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/66c44b0b744317032994ecb2bfbaab223720e4f9/pkg/kv/kvserver/stores_base.go#L49)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: we can avoid the heap allocations whenever we package pointers up into interfaces by changing this to:
```
type StoresIterator Stores
type baseStore Store

func MakeStoresIterator(stores *Stores) *StoresIterator {
	return (*StoresIterator)(stores)
}

...
    err = f((*baseStore)(store))
``` 

And then implement the interfaces on pointer receivers.
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/builtins.go, line 6636 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/77847#-Mzq64Sw1vmYAd6zUcR4:-Mzr8WAo1I-lA5ilzIC9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/66c44b0b744317032994ecb2bfbaab223720e4f9/pkg/sql/sem/builtins/builtins.go#L6636)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: I would have expected the queue name to come before the active flag. No need to change unless you agree that that would be more natural.
</blockquote></details>

Done.

**Comment by irfansharif** [comment]
blathers backport 21.2

**Pull request merged**
