### PR TITLE
execstats: use ExtractStatsFromSpans in TraceAnalyzer

### PR DESCRIPTION
**Pull request by tbg**
Simplify `(*TraceAnalyzer).AddTrace` by calling into
`ExtractStatsFromSpans`. In particular, this removes reliance on tags
which will not be available any more once SpanStats become "just
another" always-on tracing payload.

This simpler implementation will reduce the migration burden incurred by
always-on tracing, as only ExtractStatsFromSpans will need to be updated
to handle legacy behavior in incoming trace recordings.

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
Hmm, TestTraceAnalyzer is failing here with a zero:

https://github.com/cockroachdb/cockroach/blob/dc39c1d216bb69964244d27530dd183b741b2539/pkg/sql/execstats/traceanalyzer_test.go#L166

I looked a bit and it looks like we cut some corners, i.e. we need to address this TODO:

https://github.com/cockroachdb/cockroach/blob/999533fa13cf7374eff61abce30464c63a16e4ae/pkg/sql/colflow/vectorized_flow.go#L953-L958

It seems that there are a handful places that put the tag in manually, and then later put a SpanStats that doesn't also reflect the tag. The code snippet linked above is easy to fix, but there are a few others where we set the tag way before setting the SpanStats. I assume we can simply remove the manual tag setting once the span stats is fixed, right?

**Comment by tbg** [comment]
I added a commit that highlights the problematic places. I'd appreciate some guidance from either @RaduBerinde or @asubiotto (I'll take anyone's help really :) )
This isn't urgent - I'm also heading out for the holidays soon.

**Comment by tbg** [comment]
(cc @irfansharif @knz for pod-awareness)

**Comment by RaduBerinde** [comment]
Hi Tobi! I have made some many changes here recently; my goal was indeed to never have to look at the tags. A third type of usage was added while I was making the changes, and I left it as a TODO. I will work on fixing it soon.

**Comment by tbg** [comment]
Thanks, sounds good! I'll work around it in my main branch and abandon this
PR (you can pick what you like of course...).

**Comment by RaduBerinde** [comment]
Thanks! I picked it up (it was very close already actually). I will post a separate PR when it's ready.

**Pull request closed without merging**
