### PR TITLE
git: pdfs are binary

### PR DESCRIPTION
**Pull request by dt**
[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4742)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
LGTM

**Comment by bdarnell** [comment]
Why is this necessary? Doesn't git auto-detect binary files based on their contents in most cases? We are abusing the "binary" feature to suppress generated code in diffs, but we haven't had a problem with the png and jpg images in the repo.

BTW, the only two pdf files in the repo are of our old logo, which we should probably just remove.

**Comment by dt** [comment]
Hm, it looked like git wasn't detecting it since it made a mess of `git grep cf_`

**Comment by bdarnell** [comment]
LGTM

**Pull request merged**
