### PR TITLE
storage/engine: allow specifying lower bounds

### PR DESCRIPTION
**Pull request by benesch**
**storage/engine: allow specifying lower bounds**

In #26872 it was mandated that all iterators be either prefix iterators
or explicitly set an upper bound. This vastly improved performance with
range tombstones.

For completeness, we need to specify lower bounds on iterators that scan
in reverse. (This was left out of #26872 so that it could merge ASAP.)
This commit adds the necessary plumbing, and applies appropriate lower
bounds in the two code paths that perform reverse iteration.

---

**storage: improve layering of mvcc scan/iterate functions**

mvccScanInternal previously took both a Reader and an Iterator. If the
Iterator was nil, it would use the Reader to create itself an Iterator;
otherwise, it would use Iterator and entirely ignore Reader.

This was impressively confusing. Just teach all of mvccScanInternal's
callers (there are only five) to create an iterator if they don't have
one already.

We could further reduce duplication by collapsing all scan variants
(MVCCScanToBytes, MVCCReverseScan) into one function, MVCCScan, that
takes a ScanOptions struct, but that cleanup is left to a future commit.

---

@jordanlewis this should improve your life when you get back to #31909.

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32072)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/engine/rocksdb.go, line 2042 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32072#-LQERYPZ5zZ1I2BDoy9X:-LQERYPZ5zZ1I2BDoy9Y:b-peo4e2) ([raw file](https://github.com/cockroachdb/cockroach/blob/429eeff8d7f0b252768e16fe0e723b1760bef5e1/pkg/storage/engine/rocksdb.go#L2042)):*
> ```Go
> 	}
> 
> 	if !opts.Prefix && len(opts.UpperBound) == 0 && len(opts.LowerBound) == 0 {
> ```

Is there a danger here that a caller can set `LowerBound` but then perform forward iteration? I'm guessing it is onerous to require all callers to set `LowerBound`, but they already set `UpperBound`, right?

**Comment by benesch** [comment]
> Is there a danger here that a caller can set LowerBound but then perform forward iteration? I'm guessing it is onerous to require all callers to set LowerBound, but they already set UpperBound, right?

Yes, there is that possibility. It didn't seem like a particularly likely scenario so I figured I'd leave it for later. Are you comfortable merging as is for now? I think it's still a big improvement over what we had.

**Comment by petermattis** [comment]
> Are you comfortable merging as is for now? I think it's still a big improvement over what we had.

Yes. I already approved.

**Comment by benesch** [comment]
Ack, just making sure it was an LGTM-with-optional-nits and not an LGTM-modulo-comments. TFTR!

bors r=petermattis

**Pull request merged**
