### PR TITLE
roachtest: add `failover` variants for partial network partitions

### LINKED ISSUE #94614: roachtest: `failover` variant for partial network partitions
We should add `failover` roachtest variants that benchmark range unavailability in the case of partial network partitions. There are two main variants, where all nodes can reach the liveness leaseholder: range leaseholder partitioned away from Raft leader, and SQL gateway partitioned away from range leaseholder.

See also [internal doc](https://docs.google.com/document/d/134eVs69fVBhP-01bxfrdjPxz--drNjOQ8AI-7Z3UD6U/edit).

Jira issue: CRDB-23045

### PR DESCRIPTION
**Pull request by erikgrinaker**
**roachtest: improve zone config readability in failover tests**

This patch improves readability of zone configs in `failover` tests, by tweaking the APIs. It also fixes a bug which placed replicas on the wrong nodes in `failover/partial/lease-liveness`.

**roachtest: improve `failover/partial/lease-liveness`**

This test did not sufficiently constrain range/lease placement, which caused occasional permanent unavailability as it randomly hit other failure modes than the one it's trying to test.

This patch makes the test more prescriptive, by separating out the system ranges, SQL gateways, liveness leaseholder, and user ranges, and only introducing a partial partition between a user leaseholder and the liveness leaseholder.
  
**roachtest: add `failover/partial/lease-gateway`**

This patch adds a roachtest that benchmarks the pMax unavailability during a partial network partition between a SQL gateway and a leaseholder. We currently don't handle this failure mode at all, and expect this to result in permanent unavailability.

**kvserver: add `COCKROACH_DISABLE_LEADER_FOLLOWS_LEASEHOLDER`**

This patch adds `COCKROACH_DISABLE_LEADER_FOLLOWS_LEASEHOLDER` which will disable colocation of the Raft leader and leaseholder. This is useful for tests.

**roachtest: add `failover/partial/lease-leader`**

This patch adds a roachtest that benchmarks unavailability during a partial partition between a Raft leader and leaseholder.

Resolves #94614.
Touches #93503.
Epic: none

Release note: None

### CODE REVIEW

**Comment by erikgrinaker** [comment]
We also need a test/benchmark for a partial partition between the leaseholder and Raft leader, but that scenario is harder to arrange and may need additional test infrastructure so I'll submit it separately.

@AlexTalks This benchmark covers the the main scenarios for the follower routing work in #93503.

**Comment by erikgrinaker** [comment]
>We also need a test/benchmark for a partial partition between the leaseholder and Raft leader, but that scenario is harder to arrange and may need additional test infrastructure so I'll submit it separately.

Found a pretty straightforward way to do this, added the test here.

**Review by andrewbaptist — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103254#-:-NVaZLmdB1xR9KSs9BU-:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @AlexTalks, @erikgrinaker, @herkolategan, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/failover.go` line 989 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103254#-NVUkb8N2kz28cvj9qup:-NVUkb8N2kz28cvj9quq:b-2lrxoj) ([raw file](https://github.com/cockroachdb/cockroach/blob/96398a12a14b48ab30e78bebf947d7a46d35cfef/pkg/cmd/roachtest/tests/failover.go#L989)):*
> ```Go
> 	var constraintsString string
> 	if len(cfg.onlyNodes) > 0 {
> 		for _, nodeID := range excludeNodes(cfg.onlyNodes) {
> ```

nit: I don't see the advantage to making `exlcludeNodes` a func rather than just computing it right before this for loop. I don't see anything wrong with it, but it is a little harder to read this way as its only ever called once.
___
*[`pkg/cmd/roachtest/tests/failover.go` line 163 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103254#-NVUsqp7A_-u1MwvwMMA:-NVUsqp7A_-u1MwvwMMB:b-13bcg9) ([raw file](https://github.com/cockroachdb/cockroach/blob/b58e3f4a9810828554ec316d2f50df7c25bc8022/pkg/cmd/roachtest/tests/failover.go#L163)):*
> ```Go
> 	c.Run(ctx, c.Node(6), `./cockroach workload init kv --splits 1000 {pgurl:1}`)
> 
> 	// The replicate queue takes forever to move the ranges, so we do it
> ```

nit: Wouldn't it be better to submit all the ranges to the replicate queue immediately? That would prevent any divergence between the ranges and the configuration above. (In this and other places). I think it should be similar speed to this approach, although it might still be necessary to do it in a loop. It would be much cleaner if this test just called `relocateRangesUntilStable` with no real parameters passed to it, and it continues running until there is nothing moved.
___
*[`pkg/cmd/roachtest/tests/failover.go` line 201 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103254#-NVUuBWe-kwqA0KeDU91:-NVUuBWe-kwqA0KeDU92:bi62dbw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b58e3f4a9810828554ec316d2f50df7c25bc8022/pkg/cmd/roachtest/tests/failover.go#L201)):*
> ```Go
> 				}
> 
> 				randTimer := time.After(randutil.RandDuration(rng, raftCfg.RangeLeaseRenewalDuration()))
> ```

Shouldn't you create this after you move the leases and ranges? Otherwise, this timer will fire immediately if they take longer than the ~3s to move ranges/leases.  I see your comment below, but I'm not sure if this is the right approach as it might remove some of the randomness about when it fires.
___
*[`pkg/cmd/roachtest/tests/failover.go` line 835 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103254#-NVUti2d2_UepRpl3kkl:-NVUti2d2_UepRpl3kkm:b-uf6ddw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b58e3f4a9810828554ec316d2f50df7c25bc8022/pkg/cmd/roachtest/tests/failover.go#L835)):*
> ```Go
> 		if f.input && f.output {
> 			f.c.Run(ctx, f.c.Node(nodeID), fmt.Sprintf(
> 				`sudo iptables -A INPUT -m multiport -p tcp -s %s --ports 26257 -j DROP`, peerIP))
> ```

nit: I don't think you need to specify `--multiport` here since only one port is blocked. This doesn't conflict with the following line since that is on a different chain.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103254)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @AlexTalks, @andrewbaptist, @herkolategan, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/failover.go` line 989 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103254#-NVUkb8N2kz28cvj9qup:-NVdOM6N-bPtYELOy9nx:b9s45l7) ([raw file](https://github.com/cockroachdb/cockroach/blob/96398a12a14b48ab30e78bebf947d7a46d35cfef/pkg/cmd/roachtest/tests/failover.go#L989)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: I don't see the advantage to making `exlcludeNodes` a func rather than just computing it right before this for loop. I don't see anything wrong with it, but it is a little harder to read this way as its only ever called once.
</blockquote></details>

Yeah, it used to be called in a couple of spots, but no longer. Inlined.
___
*[`pkg/cmd/roachtest/tests/failover.go` line 163 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103254#-NVUsqp7A_-u1MwvwMMA:-NVdEjlI3gJz-tbofZ-6:bywapsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b58e3f4a9810828554ec316d2f50df7c25bc8022/pkg/cmd/roachtest/tests/failover.go#L163)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: Wouldn't it be better to submit all the ranges to the replicate queue immediately? That would prevent any divergence between the ranges and the configuration above. (In this and other places). I think it should be similar speed to this approach, although it might still be necessary to do it in a loop. It would be much cleaner if this test just called `relocateRangesUntilStable` with no real parameters passed to it, and it continues running until there is nothing moved.
</blockquote></details>

For sure. This is a kludge, but I've had a really hard time getting the replicate queue to place replicas and leases correctly in these tests -- they will frequently end up on the wrong nodes, even after they've initially been placed correctly.

I didn't know about `relocateRangesUntilStable`, thanks for the tip -- I'll give that a shot. I'm going to merge this as-is for now, since I know that this works and want to have the code handy in case the other approach ends up being flaky and we need to revert, but I have a final cleanup PR in #103264 with some general improvements and will try `relocateRangesUntilStable` there.
___
*[`pkg/cmd/roachtest/tests/failover.go` line 201 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103254#-NVUuBWe-kwqA0KeDU91:-NVdHDg86At1sIoDguLW:bwhw9ef) ([raw file](https://github.com/cockroachdb/cockroach/blob/b58e3f4a9810828554ec316d2f50df7c25bc8022/pkg/cmd/roachtest/tests/failover.go#L201)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

Shouldn't you create this after you move the leases and ranges? Otherwise, this timer will fire immediately if they take longer than the ~3s to move ranges/leases.  I see your comment below, but I'm not sure if this is the right approach as it might remove some of the randomness about when it fires.
</blockquote></details>

An annoying issue in these tests is that the workload runs for a fixed amount of time (usually 20 minutes), and we have to get through 9 cycles of fail/recover in that time. Because of this, I've tried to avoid synchronous waits that will skew the fail/recover schedule, and stick to the 1 minute intervals so that we're certain that we can fit it within the workload time budget.

There may be a better way to do this, but we need to let the workload run to completion, since we need the final pMax readings. It's possible that it'll already dump pMax on SIGINT, in which case we can simply use context cancellation to end the workload once we're done with the failures instead of trying to stick to some arbitrary time budget. Let me see if we can improve this over in #103264, since this applies to all the tests.
___
*[`pkg/cmd/roachtest/tests/failover.go` line 835 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103254#-NVUti2d2_UepRpl3kkl:-NVdIKgJ9eSqNnhyqi_W:b-wb9hw1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b58e3f4a9810828554ec316d2f50df7c25bc8022/pkg/cmd/roachtest/tests/failover.go#L835)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: I don't think you need to specify `--multiport` here since only one port is blocked. This doesn't conflict with the following line since that is on a different chain. 
</blockquote></details>

I think we had this discussion before on a different PR. :) Without `--multiport` we're only blocking packets in 2 out of 4 directions, so nodes will still be seeing TCP retransmits and such from peers which isn't representative of a real network outage.

But I've changed this to use 4 explicit rules instead, with some additional commentary, so we won't have to discuss this again next time. :)

**Review by erikgrinaker — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103254#-:-NVdYJG-D0TyParDQHoR:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @AlexTalks, @andrewbaptist, @herkolategan, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/failover.go` line 163 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103254#-NVUsqp7A_-u1MwvwMMA:-NVdW12m4cMYW095UedN:bva00il) ([raw file](https://github.com/cockroachdb/cockroach/blob/b58e3f4a9810828554ec316d2f50df7c25bc8022/pkg/cmd/roachtest/tests/failover.go#L163)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

For sure. This is a kludge, but I've had a really hard time getting the replicate queue to place replicas and leases correctly in these tests -- they will frequently end up on the wrong nodes, even after they've initially been placed correctly.

I didn't know about `relocateRangesUntilStable`, thanks for the tip -- I'll give that a shot. I'm going to merge this as-is for now, since I know that this works and want to have the code handy in case the other approach ends up being flaky and we need to revert, but I have a final cleanup PR in #103264 with some general improvements and will try `relocateRangesUntilStable` there.
</blockquote></details>

Ah, I see that `relocateRangesUntilStable` isn't a thing. I'll see if we can write something up.
___
*[`pkg/cmd/roachtest/tests/failover.go` line 835 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/103254#-NVUti2d2_UepRpl3kkl:-NVdVzQ46A-xfn_gtn82:b-exydw2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b58e3f4a9810828554ec316d2f50df7c25bc8022/pkg/cmd/roachtest/tests/failover.go#L835)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

I think we had this discussion before on a different PR. :) Without `--multiport` we're only blocking packets in 2 out of 4 directions, so nodes will still be seeing TCP retransmits and such from peers which isn't representative of a real network outage.

But I've changed this to use 4 explicit rules instead, with some additional commentary, so we won't have to discuss this again next time. :)
</blockquote></details>

In case it wasn't clear, the reason `--multiport` does this is because it matches on either the source port or the destination port -- it's equivalent to two separate rules specifying `--sport` and `--dport`, hence multiport. So the `INPUT` variant will match both on packets from a remote server to a local client on an outbound connection (`--sport 26257`) and on packets from a remote client to a local server on an inbound connection (`--dport 26257`). Similarly for the `OUTPUT` variant, just in reverse.

**Pull request merged**
