### PR TITLE
sql: add named arguments to signatures in builtin help

### PR DESCRIPTION
**Pull request by dt**
hopefully I'll hook this up to the docs generator on friday

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9766)

### CODE REVIEW

**Comment by dt** [comment]
This takes a slightly different approach than #8577 to passing the names -- adding a new `ArgTypes` replacement that takes tuples -- that hopefully is less prone to them getting out of sync with the args.

**Comment by knz** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9766#-:-KTLotts2OWa1CNZvXmN:bnfp4nl)*

**Comment by mjibson** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[sql/parser/builtins.go, line 370 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9766#-KTLpPxdHEFaxKMylLAq:-KTLpPxdHEFaxKMylLAr:bhimy5g) ([raw file](https://github.com/cockroachdb/cockroach/blob/b82e71000790e9bfde9d7a9f415dcfe9e054a2b8/sql/parser/builtins.go#L370)):*
> ```Go
> 	"replace": {
> 		{
> 			Types:      NamedArgTypes{{"input", TypeString}, {"from", TypeString}, {"to", TypeString}},
> ```

Using this pattern instead of the `stringBuiltin3` and similar functions will lead to a lot of the silly argument extraction functions you have below. I suggest adding `stringBuiltin3Named` or something that takes named types + an info.

---

*[sql/parser/overload.go, line 95 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9766#-KTLpvfflWoLGRp6LYUo:-KTLpvfflWoLGRp6LYUp:b-17b0y7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b82e71000790e9bfde9d7a9f415dcfe9e054a2b8/sql/parser/overload.go#L95)):*
> ```Go
> 		if first {
> 			first = false
> 		} else {
> ```

if i > 0, can remove first

---

*[sql/parser/overload.go, line 98 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9766#-KTLq3llWvZNB-M7Ah5H:-KTLq3llWvZNB-M7Ah5I:b-5lu24w) ([raw file](https://github.com/cockroachdb/cockroach/blob/b82e71000790e9bfde9d7a9f415dcfe9e054a2b8/sql/parser/overload.go#L98)):*
> ```Go
> 			s.WriteString(", ")
> 		}
> 		s.WriteString(a[i].Name)
> ```

Why not use the provided a[i] in the range above instead of fetching it here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9766)*

**Comment by dt** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/parser/builtins.go, line 370 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9766#-KTLpPxdHEFaxKMylLAq:-KTLywbPVi7eLsCBikhJ:b-3ddh7f) ([raw file](https://github.com/cockroachdb/cockroach/blob/b82e71000790e9bfde9d7a9f415dcfe9e054a2b8/sql/parser/builtins.go#L370)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> Using this pattern instead of the `stringBuiltin3` and similar functions will lead to a lot of the silly argument extraction functions you have below. I suggest adding `stringBuiltin3Named` or something that takes named types + an info.
</details>
that seems more likely to be worth it for one with more than one callsite, but there's literally only one other caller to `stringBuiltin3`.

---

*[sql/parser/overload.go, line 95 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9766#-KTLpvfflWoLGRp6LYUo:-KTLzEIv7rQF6ka6FEY6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b82e71000790e9bfde9d7a9f415dcfe9e054a2b8/sql/parser/overload.go#L95)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> if i > 0, can remove first
</details>
Done.

---

*[sql/parser/overload.go, line 98 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9766#-KTLq3llWvZNB-M7Ah5H:-KTLzWRwI1VDajDgC1Nd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b82e71000790e9bfde9d7a9f415dcfe9e054a2b8/sql/parser/overload.go#L98)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> Why not use the provided a[i] in the range above instead of fetching it here?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9766)*

**Comment by mjibson** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/parser/builtins.go, line 370 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9766#-KTLpPxdHEFaxKMylLAq:-KTNCQNR6rENVjMUMAwg:b-mccqnh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b82e71000790e9bfde9d7a9f415dcfe9e054a2b8/sql/parser/builtins.go#L370)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> that seems more likely to be worth it for one with more than one callsite, but there's literally only one other caller to `stringBuiltin3`.
</details>
While I agree about that in this case, I want to establish a good pattern for when the other call site and all of the other various builtin function wrappers are converted to this format. If it was just this one I wouldn't care. If you still don't think it's worth it or want to do this later, then :lgtm:.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9766)*

**Comment by dt** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/parser/builtins.go, line 370 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9766#-KTLpPxdHEFaxKMylLAq:-KTP1SM-DXh05SEP43Qk:b5a7zdd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b82e71000790e9bfde9d7a9f415dcfe9e054a2b8/sql/parser/builtins.go#L370)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> While I agree about that in this case, I want to establish a good pattern for when the other call site and all of the other various builtin function wrappers are converted to this format. If it was just this one I wouldn't care. If you still don't think it's worth it or want to do this later, then :lgtm:.
</details>
Done (made stringBuiltin3 take the names, and added names to the only other callsite).

I'm skeptical that these helpers will continue to provide as much value, as there becomes that is unique to a `Builtin` than just the `fn`, and thus the helpers end up needing to pass along more than they're adding themselves. I suspect we'll end up wanting more granular helpers (e.g. a typed n'th arg accessor or a shorthand constructor for a n*<type> `NamedArgTypes`, etc) that make creating `Builtin` literals directly instead less cluttered, but I think that'll all be much more apparent when tackling the functions that rely on the more widely used stringBuiltin2 and co.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9766)*

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9766#-:-KTPoA4R6w9mjOLGag36:bnfp4nl)*

**Pull request merged**
