### PR TITLE
pretty: implement various statements

### PR DESCRIPTION
**Pull request by madelynnblue**
Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Thank you for tackling these. I have a few comments.

The main comment however is that the changes were orthogonal from each other (and non-overlapping) so this should really have been multiple PRs. It would have made the review much easier.

> Reviewed 1 of 1 files at r1, 13 of 14 files at r2, 5 of 5 files at r3, 5 of 5 files at r4, 9 of 9 files at r5, 17 of 17 files at r6, 5 of 5 files at r7, 8 of 9 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29979#-:-LM31YulBOyY6FosR0cu:bsb363w)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[.gitattributes, line 2 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/29979#-LM31ACz4UhlSuq3Tn44:-LM31AD-4krWtO5Yqq43:bqmp0wm) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa2313de735a51b752350b180cd5a5259d775c58/.gitattributes#L2)):*
> ```
> *.pb.* -diff
> *.golden -diff
> ```

What? No. There is too much noise in the output of `git diff` otherwise.

If you want to argue "we want the diff to show an example output" I am fine with the argument but then please invent yet another test file that only shows 1 example at some reasonable width (e.g. 80) to be included in the diff. We don't want to have dozens of examples in each diff.

Also reviewable can expand the diffs even if this is there, so it doesn't change anything for reviews.
___
*[pkg/sql/sem/tree/pretty.go, line 1263 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/29979#-LM2yiP5CPcehq6_t57t:-LM2yiP5CPcehq6_t57u:b-heepg5) ([raw file](https://github.com/cockroachdb/cockroach/blob/bccf09cfa7a723a72d5a4deb6aaef7a8ae2c9482/pkg/sql/sem/tree/pretty.go#L1263)):*
> ```Go
> 	)
> 	docs := []pretty.Doc{
> 		pretty.BracketDoc(d, p.Doc(&node.Columns), pretty.Text(")")),
> ```

This does not respect the logical grouping. I would recommend this instead:
```
	docs := []pretty.Doc{
             pretty.Fold(
		pretty.ConcatSpace,
		d,
		pretty.Text("ON"),
		p.Doc(&node.Table),
		pretty.Bracket("(", p.Doc(&node.Columns), ")")),
      } 
```
___
*[pkg/sql/sem/tree/pretty.go, line 1285 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/29979#-LM2zuNe8FHxMw2lBQxr:-LM2zuNe8FHxMw2lBQxs:b-h1t788) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c59f0b5e0801a7af8e6e3f4b7a14a65f08bc4a0/pkg/sql/sem/tree/pretty.go#L1285)):*
> ```Go
> 	d := pretty.ConcatSpace(
> 		p.Doc(&node.Name),
> 		pretty.Text(coltypes.ColTypeAsString(node.Type)),
> ```

I think the type and all the attributes can be nested under the column name. This ensures the create becomes more compact if the display is narrow.

Also I would add a TODO here to add a new LLTable prettifier (in addition / next to RLTable) so we can have all the types aligned under each other. Because I find it sad that the output of sqlfmt is currently worse than the input SQL you've used in the test :)

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29979)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[.gitattributes, line 2 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/29979#-LM31ACz4UhlSuq3Tn44:-LM3xH_hE9GaO3V_o_RB:b-ei52me) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa2313de735a51b752350b180cd5a5259d775c58/.gitattributes#L2)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

What? No. There is too much noise in the output of `git diff` otherwise.

If you want to argue "we want the diff to show an example output" I am fine with the argument but then please invent yet another test file that only shows 1 example at some reasonable width (e.g. 80) to be included in the diff. We don't want to have dozens of examples in each diff.

Also reviewable can expand the diffs even if this is there, so it doesn't change anything for reviews.
</blockquote></details>

Reviewable might be able to, but git won't, which means I can't see how certain things changed or were created using `git gui` or `git diff`. I spent a while just figuring out why my normal diff viewing tools weren't showing me diffs and it interrupted my workflow. I'd prefer not to have to remove this line every time I work on pretty.
___
*[pkg/sql/sem/tree/pretty.go, line 1263 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/29979#-LM2yiP5CPcehq6_t57t:-LM3zgM34T684mQQx8_8:be4n6ya) ([raw file](https://github.com/cockroachdb/cockroach/blob/bccf09cfa7a723a72d5a4deb6aaef7a8ae2c9482/pkg/sql/sem/tree/pretty.go#L1263)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This does not respect the logical grouping. I would recommend this instead:
```
	docs := []pretty.Doc{
             pretty.Fold(
		pretty.ConcatSpace,
		d,
		pretty.Text("ON"),
		p.Doc(&node.Table),
		pretty.Bracket("(", p.Doc(&node.Columns), ")")),
      } 
```

</blockquote></details>

This doesn't change the output at all, even with multiple columns in node.Columns. Can you show me the output you are wanting?
___
*[pkg/sql/sem/tree/pretty.go, line 1285 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/29979#-LM2zuNe8FHxMw2lBQxr:-LM47BCQ2t189zI4s9Cb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c59f0b5e0801a7af8e6e3f4b7a14a65f08bc4a0/pkg/sql/sem/tree/pretty.go#L1285)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I think the type and all the attributes can be nested under the column name. This ensures the create becomes more compact if the display is narrow.

Also I would add a TODO here to add a new LLTable prettifier (in addition / next to RLTable) so we can have all the types aligned under each other. Because I find it sad that the output of sqlfmt is currently worse than the input SQL you've used in the test :)
</blockquote></details>

Done.

**Review by knz — APPROVED** [review]
> Reviewed 1 of 4 files at r19.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29979)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[.gitattributes, line 2 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/29979#-LM31ACz4UhlSuq3Tn44:-LMJiyYC7M17HKha_vbx:b-bv82lx) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa2313de735a51b752350b180cd5a5259d775c58/.gitattributes#L2)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Reviewable might be able to, but git won't, which means I can't see how certain things changed or were created using `git gui` or `git diff`. I spent a while just figuring out why my normal diff viewing tools weren't showing me diffs and it interrupted my workflow. I'd prefer not to have to remove this line every time I work on pretty.
</blockquote></details>

Yes as @couchand was saying your solution here is `git diff -a`. 

If you really want to change this please at least ensure that reviewable still hides the things by default (with the generated file marker)
___
*[pkg/sql/sem/tree/pretty.go, line 1263 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/29979#-LM2yiP5CPcehq6_t57t:-LMJjYDK-Kk7sjBIpiq5:b1bjjws) ([raw file](https://github.com/cockroachdb/cockroach/blob/bccf09cfa7a723a72d5a4deb6aaef7a8ae2c9482/pkg/sql/sem/tree/pretty.go#L1263)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

This doesn't change the output at all, even with multiple columns in node.Columns. Can you show me the output you are wanting?
</blockquote></details>

Oh I am sorry I had misread and was seeing ConcatLine where you used ConcatSpace. Please ignore my comment.

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29979)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[.gitattributes, line 2 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/29979#-LM31ACz4UhlSuq3Tn44:-LMJkrUZ6BsLi_9_45PR:b-v1sxuo) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa2313de735a51b752350b180cd5a5259d775c58/.gitattributes#L2)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Yes as @couchand was saying your solution here is `git diff -a`. 

If you really want to change this please at least ensure that reviewable still hides the things by default (with the generated file marker)
</blockquote></details>

I confirmed that reviewable by default doesn't show these files since they are generated, so I'm moving forward.

**Comment by knz** [comment]
cool thanks :+1:

**Pull request merged**
