### PR TITLE
sql: add a rule to push a distinct modifier into a scalargroupby

### LINKED ISSUE #46899: opt: add rule to push down agg DISTINCT to input
We should add a rule to the optimizer which rewrites queries like this:
```
CREATE TABLE xy (x INT PRIMARY KEY, y INT, INDEX (y));
INSERT INTO xy SELECT x, x % 100 FROM generate_series(1,100000) t(x);
SELECT COUNT(DISTINCT y) FROM xy;
```
to this:
```
SELECT COUNT(*) FROM (SELECT DISTINCT y FROM xy);
```
The first runs in ~80ms on my laptop. The second runs in ~55ms. The biggest reason for the drop is that the second formulation can take advantage of our streaming group-by execution operator, since the `y` index can be used.

### PR DESCRIPTION
**Pull request by DrewKimball**
Previously, the optimizer could not take advantage of an index on
a variable with a command like the following:

SELECT COUNT(DISTINCT y) FROM xy;

To address this, PushAggDistinctIntoScalarGroupBy pushes the
distinct operation from the aggregate function and into the
input of the ScalarGroupBy.

Fixes #46899

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm: Very nice work, thanks!

It looks like a stats_quality test needs to be updated. These can be confusing to update (a simple `-rewrite` doesn't work), so I did it for you - just apply this patch: https://gist.github.com/RaduBerinde/1b66ce6df89e0caae1a323f9e7415501

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47589#-:-M55hxw-5UXMJniRhzIr:b-u24d3c)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

___
*[pkg/sql/opt/norm/rules/groupby.opt, line 213 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47589#-M55flE_-MsH8SYeeAYg:-M55flEa9ACIIzgtnIhh:b-bvyuim) ([raw file](https://github.com/cockroachdb/cockroach/blob/87e72224a4326986dd4b28b27dabf8b2e522aa62/pkg/sql/opt/norm/rules/groupby.opt#L213)):*
> ```
>     $aggregations:
>     [
>         $item:
> ```

[nit] remove this line break (`$item:(AggregationsItem)`)
___
*[pkg/sql/opt/norm/rules/groupby.opt, line 228 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47589#-M55fsld9ohQbdn0hm_f:-M55fsld9ohQbdn0hm_g:b-70ksks) ([raw file](https://github.com/cockroachdb/cockroach/blob/87e72224a4326986dd4b28b27dabf8b2e522aa62/pkg/sql/opt/norm/rules/groupby.opt#L228)):*
> ```
>         (MakeUnorderedGrouping (ExtractAggInputColumns $agg))
>     )
>     [
> ```

[nit] can just be `[ (AggregationsItem ..) ]`
___
*[pkg/sql/opt/norm/testdata/rules/groupby, line 2093 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47589#-M55gF6d58AgJJneJARQ:-M55gF6d58AgJJneJARR:b2ir2dd) ([raw file](https://github.com/cockroachdb/cockroach/blob/87e72224a4326986dd4b28b27dabf8b2e522aa62/pkg/sql/opt/norm/testdata/rules/groupby#L2093)):*
> ```
> # Multiple input arguments for aggregate function.
> norm expect=PushAggDistinctIntoScalarGroupBy
> SELECT string_agg(DISTINCT s, '-') FROM (SELECT s FROM xyzbs ORDER BY s) xyzbs
> ```

[nit] I don't think the last `xyzbs` is needed

**Review by DrewKimball — COMMENTED** [review]
Should there also be a stats table for stock_level_02_distinct_on_2?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47589#-:-M583R9m3OzUI2QLxLRK:b-ebjnzi)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/norm/rules/groupby.opt, line 213 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47589#-M55flE_-MsH8SYeeAYg:-M584F2AEOi4nP-owngL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/87e72224a4326986dd4b28b27dabf8b2e522aa62/pkg/sql/opt/norm/rules/groupby.opt#L213)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] remove this line break (`$item:(AggregationsItem)`)
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/rules/groupby.opt, line 228 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47589#-M55fsld9ohQbdn0hm_f:-M584ziz5kuPp5_8t3JG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/87e72224a4326986dd4b28b27dabf8b2e522aa62/pkg/sql/opt/norm/rules/groupby.opt#L228)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] can just be `[ (AggregationsItem ..) ]`
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/testdata/rules/groupby, line 2093 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47589#-M55gF6d58AgJJneJARQ:-M584CvzDAiV-oHYq_bY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/87e72224a4326986dd4b28b27dabf8b2e522aa62/pkg/sql/opt/norm/testdata/rules/groupby#L2093)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] I don't think the last `xyzbs` is needed
</blockquote></details>

Done.

**Review by RaduBerinde — COMMENTED** [review]
Yeah, but it would be a pain to generate it (we'd need to run against an instance with a real dataset) and I don't think it would add too much value in this case. You can leave a `TODO(radu): add stock_level_02_distinct_on_2`.

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47589#-:-M588bit6epRIWZMBAcg:b-qhtev9)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by mgartner — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47589#-:-M58MtWB1NQ4xKcGMCad:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball)

___
*[pkg/sql/opt/memo/testdata/stats_quality/tpcc, line 609 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47589#-M58MTvY5Zw2Z_NVwchD:-M58MTvY5Zw2Z_NVwchE:b-6p5qdc) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb507a41ad3cdf667932025b19cf2bba8f0f370e/pkg/sql/opt/memo/testdata/stats_quality/tpcc#L609)):*
> ```
> {s_w_id}      216.00         14.40 <==      1.00                1.00                0.00            1.00
> 
> TODO(radu): add stock_level_02_distinct_on_2.
> ```

It looks like the build is failing because this isn't a comment. Prefix this line with `#` + a space.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47589)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner)

___
*[pkg/sql/opt/memo/testdata/stats_quality/tpcc, line 609 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47589#-M58MTvY5Zw2Z_NVwchD:-M58Sn4O34Yew2Xnt0VA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb507a41ad3cdf667932025b19cf2bba8f0f370e/pkg/sql/opt/memo/testdata/stats_quality/tpcc#L609)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

It looks like the build is failing because this isn't a comment. Prefix this line with `#` + a space.
</blockquote></details>

Done.

**Pull request merged**
