### PR TITLE
schemachanger: clean up role sets when dropping databases

### PR DESCRIPTION
**Pull request by fqazi**
Previously, the declarative schema changer did not clean up
role sets associated with a database. This was inadequate
because dangling role set entries could be left in the
system.database_role_settings table. To address this,
this patch introduces a database role set element and
implements support for dropping entries in the
system.database_role_settings table via MetadataUpdater.

Release Note: None

### CODE REVIEW

**Review by postamar — COMMENTED** [review]
Nicely done. I realized that this PR is still a draft but I wanted to look at it and see what it was about. I only noticed minor issues and I look forward to stamping this. I see that CI doesn't pass but I think I know why, at least in part. See below.

> Reviewed 24 of 24 files at r1, 22 of 22 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75245#-:-MtyIi9E2RtO2gTaco7E:bckagl9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

___
*[pkg/sql/schemachanger/scexec/exec_mutation.go, line 279 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75245#-MtyCzPwBPr2g1_i41V9:-MtyCzPwBPr2g1_i41VA:b-1pcmx0) ([raw file](https://github.com/cockroachdb/cockroach/blob/83360a985cfcba4033ff96adc0f356d1301c4ba5/pkg/sql/schemachanger/scexec/exec_mutation.go#L279)):*
> ```Go
> 	commentsToUpdate             []commentToUpdate
> 	constraintCommentsToUpdate   []constraintCommentToUpdate
> 	databaseRoleSettingsToDelete []*databaseRoleSettingToDelete
> ```

There's no good reason for this to be a slice of pointers.
___
*[pkg/sql/schemachanger/scop/mutation.go, line 412 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75245#-MtyDVH1DbEm4mB2SqJO:-MtyDVH1DbEm4mB2SqJP:b-y4bxl6) ([raw file](https://github.com/cockroachdb/cockroach/blob/83360a985cfcba4033ff96adc0f356d1301c4ba5/pkg/sql/schemachanger/scop/mutation.go#L412)):*
> ```Go
> 
> // RemoveDatabaseRoleSetting is used to delete a role setting for a database.
> type RemoveDatabaseRoleSetting struct {
> ```

Shouldn't this name be in the plural form? i.e. `RemoveDatabaseRoleSettings`
___
*[pkg/sql/schemachanger/screl/attr.go, line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75245#-MtyEPay0v877DJyhB0e:-MtyEPay0v877DJyhB0f:bia485s) ([raw file](https://github.com/cockroachdb/cockroach/blob/83360a985cfcba4033ff96adc0f356d1301c4ba5/pkg/sql/schemachanger/screl/attr.go#L73)):*
> ```Go
> 	// ConstraintOrdinal is the ordinal of the constraints
> 	ConstraintOrdinal
> 	// RoleName is the role name of an element
> ```

Can you improve this comment please?
___
*[pkg/sql/descmetadata/metadata_updater.go, line 166 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75245#-MtyBkOk5GRcmTzwPCpp:-MtyBkOk5GRcmTzwPCpq:b-vp0ba2) ([raw file](https://github.com/cockroachdb/cockroach/blob/b90a0c65bc666c7e7424c0f2bee2f340640f625a/pkg/sql/descmetadata/metadata_updater.go#L166)):*
> ```Go
> 
> // DeleteConstraintComment implements scexec.DescriptorMetadataUpdater.
> func (cu metadataUpdater) DeleteConstraintComment(
> ```

nit: consider renaming the receiver to `u` or whatever, `cu` dates back to when it was for a `CommentUpdater`.
___
*[pkg/sql/descmetadata/metadata_updater.go, line 182 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75245#-MtyFVXb9YVkpsYhPhYw:-MtyFVXb9YVkpsYhPhYx:b-o0u7yr) ([raw file](https://github.com/cockroachdb/cockroach/blob/83360a985cfcba4033ff96adc0f356d1301c4ba5/pkg/sql/descmetadata/metadata_updater.go#L182)):*
> ```Go
> 
> // DeleteDatabaseRoleSettings implement scexec.DescriptorMetaDataUpdater.
> func (cu metadataUpdater) DeleteDatabaseRoleSettings(id descpb.ID) error {
> ```

Whenever possible, prefer passing descriptors as arguments instead of IDs. Furthermore, in this case, it seems that the descriptors are readily available.
___
*[pkg/sql/descmetadata/metadata_updater.go, line 196 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75245#-MtyCPQu8yw-MQFzlHm6:-MtyCPQu8yw-MQFzlHm7:b-k2k3ws) ([raw file](https://github.com/cockroachdb/cockroach/blob/83360a985cfcba4033ff96adc0f356d1301c4ba5/pkg/sql/descmetadata/metadata_updater.go#L196)):*
> ```Go
> 	// TODO(fqazi): The existing role setting code will update the version number
> 	// of the table here, we need to execute the same logic. A later commit will
> 	// this add this in before adoption.
> ```

I appreciate you adding this comment here, but shouldn't the table-version-bumping behaviour already be present in this commit? Perhaps there's something I'm not seeing. It's not a big deal, either way.
___
*[pkg/sql/descmetadata/metadata_updater.go, line 186 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75245#-MtyGjwh-2DicodzHpHq:-MtyGjwh-2DicodzHpHr:b-oj66se) ([raw file](https://github.com/cockroachdb/cockroach/blob/251a2ff6656baae3c5e5c31f048bac63881c1de9/pkg/sql/descmetadata/metadata_updater.go#L186)):*
> ```Go
> // DeleteDatabaseRoleSettings implement scexec.DescriptorMetaDataUpdater.
> func (cu metadataUpdater) DeleteDatabaseRoleSettings(id descpb.ID) error {
> 	rowsDeleted, err := cu.ie.ExecEx(context.Background(),
> ```

Shouldn't we be plumbing a real context in here instead?
___
*[pkg/sql/descmetadata/metadata_updater.go, line 205 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75245#-MtyGq3jEcxdp-KZel7z:-MtyGq3jEcxdp-KZel8-:blrqmth) ([raw file](https://github.com/cockroachdb/cockroach/blob/251a2ff6656baae3c5e5c31f048bac63881c1de9/pkg/sql/descmetadata/metadata_updater.go#L205)):*
> ```Go
> 	}
> 	// Bump the table version for the role settings table when we modify it.
> 	return cu.collectionFactory.Txn(context.TODO(),
> ```

Same comment about context as above.
___
*[pkg/sql/descmetadata/metadata_updater.go, line 209 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75245#-MtyHUpOEsEVz2SRmbYi:-MtyHUpOEsEVz2SRmbYj:bih9xxx) ([raw file](https://github.com/cockroachdb/cockroach/blob/251a2ff6656baae3c5e5c31f048bac63881c1de9/pkg/sql/descmetadata/metadata_updater.go#L209)):*
> ```Go
> 		cu.txn.DB(),
> 		func(ctx context.Context, txn *kv.Txn, descriptors *descs.Collection) error {
> 			_, desc, err := descriptors.GetMutableTableByName(
> ```

Is there a reason why you're looking the table up by name?
___
*[pkg/sql/descmetadata/metadata_updater.go, line 210 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75245#-MtyGtzA7EsYxUMQqoQk:-MtyGtzA7EsYxUMQqoQl:bniep26) ([raw file](https://github.com/cockroachdb/cockroach/blob/251a2ff6656baae3c5e5c31f048bac63881c1de9/pkg/sql/descmetadata/metadata_updater.go#L210)):*
> ```Go
> 		func(ctx context.Context, txn *kv.Txn, descriptors *descs.Collection) error {
> 			_, desc, err := descriptors.GetMutableTableByName(
> 				context.TODO(),
> ```

You want to use the `ctx` from the callback here.
___
*[pkg/sql/descmetadata/metadata_updater.go, line 211 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75245#-MtyH0_m2fjkVI8_87Iw:-MtyH0_m2fjkVI8_87Ix:b-mwbyde) ([raw file](https://github.com/cockroachdb/cockroach/blob/251a2ff6656baae3c5e5c31f048bac63881c1de9/pkg/sql/descmetadata/metadata_updater.go#L211)):*
> ```Go
> 			_, desc, err := descriptors.GetMutableTableByName(
> 				context.TODO(),
> 				cu.txn,
> ```

Similarly, you want to use `txn` here.
___
*[pkg/sql/descmetadata/metadata_updater.go, line 222 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75245#-MtyHuji-w1B0AbXOQp2:-MtyHuji-w1B0AbXOQp3:b-4rugh) ([raw file](https://github.com/cockroachdb/cockroach/blob/251a2ff6656baae3c5e5c31f048bac63881c1de9/pkg/sql/descmetadata/metadata_updater.go#L222)):*
> ```Go
> 				return err
> 			}
> 			desc.MaybeIncrementVersion()
> ```

This does bump the version in the `tabledesc.Mutable` but it doesn't do anything to the contents of `system.descriptor`. Why not reuse the existing code in `bumpDatabaseRoleSettingsTableVersion`? It does exactly what you want. 
___
*[pkg/sql/descmetadata/metadata_updater_factory.go, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75245#-MtyBwz53mPF20gBQd6z:-MtyBwz53mPF20gBQd7-:boxdvpx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b90a0c65bc666c7e7424c0f2bee2f340640f625a/pkg/sql/descmetadata/metadata_updater_factory.go#L46)):*
> ```Go
> // create / destroy metadata (i.e. comments) associated with different
> // schema objects.
> func (cf MetadataUpdaterFactory) NewMetadataUpdater(
> ```

nit: same comment as above for `cu` receivers.

**Review by fqazi — COMMENTED** [review]
This is happening because of the session data picking up flags we would normally never pick up. To work around the issue, I have explicitly disabled distsql planning on that internal executor sessiondata. The existing code, just continues with the defaults I think.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75245#-:-MuIyBbsEqQg64qGq9DI:bittw72)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/sql/schemachanger/scexec/exec_mutation.go, line 279 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75245#-MtyCzPwBPr2g1_i41V9:-MuInZBj4w1acRxIjCWz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83360a985cfcba4033ff96adc0f356d1301c4ba5/pkg/sql/schemachanger/scexec/exec_mutation.go#L279)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

There's no good reason for this to be a slice of pointers.
</blockquote></details>

Done.
___
*[pkg/sql/schemachanger/scop/mutation.go, line 412 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75245#-MtyDVH1DbEm4mB2SqJO:-MuInZqPBVnrZDj0mGAT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83360a985cfcba4033ff96adc0f356d1301c4ba5/pkg/sql/schemachanger/scop/mutation.go#L412)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Shouldn't this name be in the plural form? i.e. `RemoveDatabaseRoleSettings`
</blockquote></details>

Done.
___
*[pkg/sql/schemachanger/screl/attr.go, line 73 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75245#-MtyEPay0v877DJyhB0e:-MuIn_ZV8RRKL2NMoTJ5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83360a985cfcba4033ff96adc0f356d1301c4ba5/pkg/sql/schemachanger/screl/attr.go#L73)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Can you improve this comment please?
</blockquote></details>

Done.
___
*[pkg/sql/descmetadata/metadata_updater.go, line 182 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75245#-MtyFVXb9YVkpsYhPhYw:-MuIlLcl7kvSCgdpK1Uk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83360a985cfcba4033ff96adc0f356d1301c4ba5/pkg/sql/descmetadata/metadata_updater.go#L182)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Whenever possible, prefer passing descriptors as arguments instead of IDs. Furthermore, in this case, it seems that the descriptors are readily available.
</blockquote></details>

Done.
___
*[pkg/sql/descmetadata/metadata_updater.go, line 196 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/75245#-MtyCPQu8yw-MQFzlHm6:-MuIlP7R1B_0CNxHknig:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/83360a985cfcba4033ff96adc0f356d1301c4ba5/pkg/sql/descmetadata/metadata_updater.go#L196)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

I appreciate you adding this comment here, but shouldn't the table-version-bumping behaviour already be present in this commit? Perhaps there's something I'm not seeing. It's not a big deal, either way.
</blockquote></details>

Done.
___
*[pkg/sql/descmetadata/metadata_updater.go, line 186 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75245#-MtyGjwh-2DicodzHpHq:-MuIlMFJ7X7qWpiPQ1UD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/251a2ff6656baae3c5e5c31f048bac63881c1de9/pkg/sql/descmetadata/metadata_updater.go#L186)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Shouldn't we be plumbing a real context in here instead?
</blockquote></details>

Done.
___
*[pkg/sql/descmetadata/metadata_updater.go, line 205 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75245#-MtyGq3jEcxdp-KZel7z:-MuIlPpkBAKKkFyDaTIg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/251a2ff6656baae3c5e5c31f048bac63881c1de9/pkg/sql/descmetadata/metadata_updater.go#L205)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Same comment about context as above.
</blockquote></details>

Done.
___
*[pkg/sql/descmetadata/metadata_updater.go, line 209 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75245#-MtyHUpOEsEVz2SRmbYi:-MuIlQj-E2Y8BZKEuZ1N:b-gi3m47) ([raw file](https://github.com/cockroachdb/cockroach/blob/251a2ff6656baae3c5e5c31f048bac63881c1de9/pkg/sql/descmetadata/metadata_updater.go#L209)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Is there a reason why you're looking the table up by name?
</blockquote></details>

Good point, we can just use the ID from keys.
___
*[pkg/sql/descmetadata/metadata_updater.go, line 210 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75245#-MtyGtzA7EsYxUMQqoQk:-MuIm3g05focM1RsGfFv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/251a2ff6656baae3c5e5c31f048bac63881c1de9/pkg/sql/descmetadata/metadata_updater.go#L210)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

You want to use the `ctx` from the callback here.
</blockquote></details>

Done.
___
*[pkg/sql/descmetadata/metadata_updater.go, line 211 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75245#-MtyH0_m2fjkVI8_87Iw:-MuIm4As7RQQ0kI0IwJh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/251a2ff6656baae3c5e5c31f048bac63881c1de9/pkg/sql/descmetadata/metadata_updater.go#L211)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

Similarly, you want to use `txn` here.
</blockquote></details>

Done.
___
*[pkg/sql/descmetadata/metadata_updater.go, line 222 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75245#-MtyHuji-w1B0AbXOQp2:-MuIm5SrDxuKr7ipD0Qr:b-47s5y) ([raw file](https://github.com/cockroachdb/cockroach/blob/251a2ff6656baae3c5e5c31f048bac63881c1de9/pkg/sql/descmetadata/metadata_updater.go#L222)):*
<details><summary><i>Previously, postamar (Marius Posta) wrote…</i></summary><blockquote>

This does bump the version in the `tabledesc.Mutable` but it doesn't do anything to the contents of `system.descriptor`. Why not reuse the existing code in `bumpDatabaseRoleSettingsTableVersion`? It does exactly what you want. 
</blockquote></details>

I was avoiding pulling in the planner in here since on the declarative side we would need another interface that gets passed into NewMetadataUpdater. We can't get the planner when constructing the factory. Longer-term we can eliminate that code once updates are implemented in declarative too.

**Review by postamar — APPROVED** [review]
:lgtm: 

I'm not sure I understand the thing with `ExperimentalDistSQLPlanningMode ` though. cc @ajwerner

> Reviewed 18 of 18 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75245#-:-MuOIU315KPvmpUooFeg:b-89oewv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

___
*[pkg/sql/descmetadata/metadata_updater.go, line 222 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/75245#-MtyHuji-w1B0AbXOQp2:-MuOHi6CEs8bt7rRpjms:b-j3bjc1) ([raw file](https://github.com/cockroachdb/cockroach/blob/251a2ff6656baae3c5e5c31f048bac63881c1de9/pkg/sql/descmetadata/metadata_updater.go#L222)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

I was avoiding pulling in the planner in here since on the declarative side we would need another interface that gets passed into NewMetadataUpdater. We can't get the planner when constructing the factory. Longer-term we can eliminate that code once updates are implemented in declarative too.
</blockquote></details>

Ah, I keep forgetting about this. Makes sense.
___
*[pkg/sql/descmetadata/metadata_updater.go, line 225 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/75245#-MuOHm8Y6r3ur8u8IV0m:-MuOHm8Y6r3ur8u8IV0n:b-u89rcu) ([raw file](https://github.com/cockroachdb/cockroach/blob/755caf865f48f6693cc6ae5c69aab2edc063ea57/pkg/sql/descmetadata/metadata_updater.go#L225)):*
> ```Go
> 			}
> 			desc.MaybeIncrementVersion()
> 			return descriptors.WriteDesc(ctx, false, desc, txn)
> ```

nit: comment the `false` literal

**Comment by fqazi** [comment]
@postamar TFTR!

**Pull request merged**
