### PR TITLE
upgrades: skip known userfile-related corruption in desc validation

### PR DESCRIPTION
**Pull request by stevendanna**
In previous releases, userfiles would create broken tables because
of incorrect use of the internal executor.  As a result, any user that
has used userfile, would fail the 22.2 upgrade precondition check.

This does 2 things:

- 1 allows the precondition to pass even in the presence of an invalid
  object as long as that object is very likely the userfile payload table.

- Adds a new migration that removes the foreign key mutation for userfile
  payload tables.

We determine whether something is a "userfile payload table" by checking
its name, the column names, the column types, the name of the referenced table,
the column names of the referenced table, and the column types of the referenced table.

Release justification: Avoid having a failed upgrade for every user of
userfile.

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm:

This is good, thanks for doing it!

> Reviewed 5 of 5 files at r1, 4 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88878#-:-ND4R5Jn4Doei5yHlSSB:brkt9w5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru and @ajwerner)

**Comment by ajwerner** [comment]
Should we add a userfile step to the mixed version roachtests?

**Comment by yuzefovich** [comment]
I think there is a merge skew with #88875, and it looks like the batch with that PR has smaller number and should go in sooner, so this will need to be rebased.

bors r-

**Comment by stevendanna** [comment]
@yuzefovich Thanks

**Comment by stevendanna** [comment]
bors retry

**Pull request merged**
