### PR TITLE
spanconfig: correctly order updates when applying in the KVSubscriber

### LINKED ISSUE #110908: Span configs incorrect after switching to from regional by table to regional by row
**Describe the problem**

After converting a system from regional by row to regional by table, there are keys in the `spanConfigStore` that return an error on `getSpanConfigForKey`. Specifically, keys that were generated for the regional by row tables. This prevents the queues from working on these ranges.

**To Reproduce**

```
cockroach demo --nodes=3 --demo-locality=region=us-east1,zone=a:region=us-central1,zone=a:region=us-west1,zone=a --empty --multitenant=false --log-dir=/tmp/logs

-- Prevent the ranges from merging back - on a real cluster they may or may not merge based on data in adjacent ranges
 SET CLUSTER SETTING kv.range_merge.queue_enabled=false;

alter database defaultdb set primary region 'us-east1';
alter database defaultdb add region 'us-central1';
alter database defaultdb add region 'us-west1';

-- create regional by table
create table t (i int primary key);
select start_key, end_key, range_id, lease_holder from [show ranges from table t with details];
   start_key   |   end_key    | range_id | lease_holder
---------------+--------------+----------+---------------
  …/<TableMin> | <after:/Max> |       65 |            1

-- alter to regional by row
alter table t set locality regional by row;
-- wait a few seconds...
select start_key, end_key, range_id, lease_holder from [show ranges from table t with details];
       start_key       |       end_key        | range_id | lease_holder
-----------------------+----------------------+----------+---------------
  …/<TableMin>         | …/2                  |       65 |            1
  …/2                  | …/2/"@"              |       66 |            1
  …/2/"@"              | …/2/"@"/PrefixEnd    |       67 |            2
  …/2/"@"/PrefixEnd    | …/2/"\xc0"           |       68 |            1
  …/2/"\xc0"           | …/2/"\xc0"/PrefixEnd |       69 |            3
  …/2/"\xc0"/PrefixEnd | <after:/Max>         |       70 |            1

-- alter back to regional by table
alter table t set locality regional by table;
select start_key, end_key, range_id, lease_holder from [show ranges from table t with details];
                             ->
       start_key       |       end_key        | range_id | lease_holder
-----------------------+----------------------+----------+---------------
  …/<TableMin>         | …/2                  |       65 |            1
  …/2                  | …/2/"@"              |       66 |            1
  …/2/"@"              | …/2/"@"/PrefixEnd    |       67 |            2
  …/2/"@"/PrefixEnd    | …/2/"\xc0"           |       68 |            1
  …/2/"\xc0"           | …/2/"\xc0"/PrefixEnd |       69 |            3
  …/2/"\xc0"/PrefixEnd | …/4                  |       70 |            1
  …/4                  | <after:/Max>         |       71 |            1

-- manually enqueue a range and look at the logs
 select crdb_internal.kv_enqueue_replica(70, 'replicate', true);
```
From the log after enqueing all the ranges on n1
```
W230919 15:53:50.293293 9623 spanconfig/spanconfigstore/span_store.go:239 ⋮ [T1,Vsystem,n1,client=127.0.0.1:60377,hostssl,user=‹demo›,s1,r70/1:‹/Table/106/{2/"\xc0…-4}›] 6984  span config not found for ‹/Table/106/2/"\xc0"/PrefixEnd›
W230919 15:54:32.634871 9623 spanconfig/spanconfigstore/span_store.go:239 ⋮ [T1,Vsystem,n1,client=127.0.0.1:60377,hostssl,user=‹demo›,s1,r71/1:‹/{Table/106/4-Max}›] 7025  span config not found for ‹/Table/106/4›
W230919 15:55:39.371312 9623 spanconfig/spanconfigstore/span_store.go:239 ⋮ [T1,Vsystem,n1,client=127.0.0.1:60377,hostssl,user=‹demo›,s1,r68/1:‹/Table/106/2/"{@"/Pr…-\xc0"}›] 7109  span config not found for ‹/Table/106/2/"@"/PrefixEnd›
```

If the ranges are merged because the left hand neighbor of the range is small enough, then it may merge away, but this is not guaranteed to ever happen

**Expected behavior**
A span config is expected to be returned for all ranges. This should then adjust the leases for these ranges to the correct place.

### PR DESCRIPTION
**Pull request by arulajmani**
Previously, there was no ordering guarantee between KVSubscriber events at the same timestamp. As a result, if a batch of events included updates to overlapping spans at the same timestamp, we could apply additions before deletions -- this would cause the additions to get clobbered, which was not the intention. This could lead to missing span configurations, resulting in bugs such as the linked issue.

This patch fixes the issue by sorting deletions before additions if two span configuration events have the same timestamp.

Closes https://github.com/cockroachdb/cockroach/issues/110908

Release note (bug fix): Previously, altering from a Regional By Row table to a Regional By Table table could cause leaseholders to never move to the databse's primary region. This is now fixed.

### CODE REVIEW

**Review by andrewbaptist — COMMENTED** [review]
:lgtm:

Just need to resolve some of the build / lint failures.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118001#-:-NpKobCL4JUFsdgNihJS:b7xx8o9)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/spanconfig/spanconfigkvsubscriber/kvsubscriber.go` line 455 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118001#-NpKnvoD3u-DPR8Q6sH8:-NpKnvoD3u-DPR8Q6sH9:b-yoe1rg) ([raw file](https://github.com/cockroachdb/cockroach/blob/caca81c5f252a46e79e931aed2262066acec0f95/pkg/spanconfig/spanconfigkvsubscriber/kvsubscriber.go#L455)):*
> ```Go
> 		if events[i].Timestamp().Less(events[j].Timestamp()) {
> 			return true
> 		} else if events[j].Timestamp().Less(events[i].Timestamp()) {
> ```

nit: remove the unnecessary `else` here. 

Also it might be slightly cleaner to call `Compare()` once and switch rather than calling `Less()` twice.

**Review by arulajmani — COMMENTED** [review]
TFTR! The linter should be happy now. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118001#-:-NpfIvS332CnASoPs5Rc:b-1orvqt)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andrewbaptist)

___
*[`pkg/spanconfig/spanconfigkvsubscriber/kvsubscriber.go` line 455 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118001#-NpKnvoD3u-DPR8Q6sH8:-NpfIuPxEWCRtTaqsxZL:bs7wumx) ([raw file](https://github.com/cockroachdb/cockroach/blob/caca81c5f252a46e79e931aed2262066acec0f95/pkg/spanconfig/spanconfigkvsubscriber/kvsubscriber.go#L455)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: remove the unnecessary `else` here. 

Also it might be slightly cleaner to call `Compare()` once and switch rather than calling `Less()` twice.
</blockquote></details>

Done.

**Review by andrewbaptist — APPROVED** [review]
:lgtm:

Thanks for the updates.

**Comment by arulajmani** [comment]
TFTR!

bors r=andrewbaptist

**Comment by arulajmani** [comment]
Looks like the test I introduced is failing under stress -- leaseholders aren't moving quick enough. I'll deflake before merging.

bors r-

**Comment by arulajmani** [comment]
Deflaked and merging. I just bumped the scan interval for this test, to ensure leases end up in the right place quickly. 

bors r+

**Pull request merged**
