### PR TITLE
bulk,kv: create initial splits in imports and backfills

### LINKED ISSUE #74826: bulk: pre-split more before ingesting unsorted data
It has been observed that during a backfill or import, the split-as-we-go behavior used by the sst batcher, where it only explicitly splits and scatters after sending some amount of data all to one range, does not send any splits in the steady state when importing out of order data: since it is out of order, after chunking it by destination range, no one chunk is large enough to be considered filling that range enough to cause us to send a split. Of course, the range may fill on its own, as many processors send it small chunks over and over and those add up, but no one processor knows when that happens, so we simply leave it up to the range to split itself when it is full as it would in any other heavy write-rate, non-bulk ingestion case.

However, we've seen this lead to hotspots during bulk ingestion. Until the range becomes full and decides to split, it can be a bottleneck as many processors send it data at once. Existing mechanisms for kv-driven load-based splitting are not tuned for ingestion workloads. When it does decide to split and rebalance, that is a more expensive operation, as we're now needing to read, move and ingest half of that full range that we just spend so much work sending data to and ingesting, all while still being sent more ingestion load.

Ideally, we'd prefer to split the span before we start ingesting, both to spread ingestion load over our available capacity better, and to reduce how much ingested data it will need to shuffle if we waited to split and scatter only once a range filled. By scattering first, we'll just ingest directly to the right place initially. However a challenge in doing this is that in many cases, we don't know what data we'll be ingesting until we start reading input and producing it -- it could be that we're working off of a key-ordered CSV, or it could be that we have a uniform random distribution. In some cases, such as an index backfill, we may be able to use some external information like a SQL statistics or a sampling scan of the table to derive a good partitioning, but in others, like IMPORTs or view materialization, we have no way to know what the data will be until we start producing it.

However we can do a bit better than not pre-splitting at all though, by instead using the first buffer's worth of data, if it was read out of sorted order, as if it is a representative sample of the rest of the data to come and then generating splits from it and splitting and scatter the target spans using those before proceeding to flush. If this buffer turns out not to be a good sample after all, this is no worse than before, where we pre-split not at all. If the input data was sorted, this step is unnecessary as we'll just split as we go, after each range we fill and scatter the empty remainder before moving to fill it, as we already do today.

Epic: CRDB-2340

### PR DESCRIPTION
**Pull request by dt**
It has been observed that during a backfill or import, the split-as-we-go behavior used by the sst batcher, where it only explicitly splits and scatters after sending some amount of data all to one range, does not send any splits in the steady state when importing out of order data: since it is out of order, after chunking it by destination range, no one chunk is large enough to be considered filling that range enough to cause us to send a split. Of course, the range may fill on its own, as many processors send it small chunks over and over and those add up, but no one processor knows when that happens, so we simply leave it up to the range to split itself when it is full as it would in any other heavy write-rate, non-bulk ingestion case.

However, we've seen this lead to hotspots during bulk ingestion. Until the range becomes full and decides to split, it can be a bottleneck as many processors send it data at once.  Existing mechanisms for kv-driven load-based splitting are not tuned for ingestion workloads. When it does decide to split and rebalance, that is a more expensive operation, as we're now needing to read, move and ingest half of that *full* range that we just spend so much work sending data to and ingesting, all while still being sent more ingestion load.

Ideally, we'd prefer to split the span before we start ingesting, both to spread ingestion load over our available capacity better, and to reduce how much ingested data it will need to shuffle if we waited to split and scatter only once a range filled. By scattering first, we'll just ingest directly to the right place initially. However a challenge in doing this is that in many cases, we don't know what data we'll be ingesting until we start reading input and producing it -- it could be that we're working off of a key-ordered CSV, or it could be that we have a uniform random distribution. In some cases, such as an index backfill, we may be able to use some external information like a SQL statistics or a sampling scan of the table to derive a good partitioning, but in others, like IMPORTs or view materialization, we have no way to know what the data will be until we start producing it.

This change tries to do a bit better than not presplitting at all though, by instead using the first buffer's worth of data, if it was read out of sorted order, as if it is a representative sample of the rest of the data to come and then generating splits from it and splitting and scatter the target spans using those before proceeding to flush. If this buffer turns out not to be a good sample after all, this is no worse than before, where we pre-split not at all. If the input data was sorted, this step is unnecessary as we'll just split as we go, after each range we fill and scatter the empty remainder before moving to fill it, as we already do today.

Release note (performance improvement): IMPORTs and Index Creation attempt to better balance their expected data between nodes before ingesting data.

### CODE REVIEW

**Comment by dt** [comment]
This is a quick sketch based on conversation last night -- I haven't tested it at all but wanted to see if this looks like _roughly_ what we were thinking.

**Comment by dt** [comment]
@nvanbenschoten what do you think about the conditional splits here?

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 7 of 7 files at r2, 2 of 2 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74816)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @andreimatei, and @dt)

___
*[pkg/kv/bulk/buffering_adder.go, line 234 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74816#-MuSaoijAHk4crhtFvUv:-MuSaoijAHk4crhtFvUw:b1dhojj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b65fe665c548e96a718691aee1b3fdaab27d6db/pkg/kv/bulk/buffering_adder.go#L234)):*
> ```Go
> 	beforeSort := timeutil.Now()
> 
> 	if !b.sorted {
> ```

Should `b.sorted` be reset to `true` after this check?
___
*[pkg/kv/bulk/buffering_adder.go, line 215 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74816#-MuSc1sp48INufHtMeDH:-MuSc1sp48INufHtMeDI:bx8ww8z) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5cf13a7b09a6456840662bceed9a0219fc66ac2/pkg/kv/bulk/buffering_adder.go#L215)):*
> ```Go
> }
> 
> // Flush flushes any buffered kvs to the batcher.
> ```

Looks like this comment is in the wrong place now.
___
*[pkg/kv/kvserver/kvserverbase/bulk_adder.go, line 77 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74816#-MuScxjM0hMuegEmdfXX:-MuScxjM0hMuegEmdfXY:b-e9vzey) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5cf13a7b09a6456840662bceed9a0219fc66ac2/pkg/kv/kvserver/kvserverbase/bulk_adder.go#L77)):*
> ```Go
> 	// InitialSplitsIfUnordered specifies a number of splits to make before the
> 	// first flush of the buffer if the contents of that buffer were unsorted.
> 	// Being unsorted suggests the remaining input is like unsorted as well and
> ```

`s/like/likely/`
___
*[pkg/roachpb/api.proto, line 767 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74816#-MuSdIPx9Wk7eDmQgbyi:-MuSdIPx9Wk7eDmQgbyj:b95f6dd) ([raw file](https://github.com/cockroachdb/cockroach/blob/087f134fa69f77a78fbbb1a0614c0a58d99d29e7/pkg/roachpb/api.proto#L767)):*
> ```protobuf
>   util.hlc.Timestamp expiration_time = 4 [(gogoproto.nullable) = false];
> 
>   // PredicateKeys specifies keys which if not contained within the range should
> ```

Did you consider making the predicate here be the range descriptor itself? So we would only split if the range's current descriptor is identical to the (optional) client-provided descriptor. I'd gravitate towards a solution like that because it feels more generally applicable and also has prior precedence with requests like `AdminChangeReplicasRequest`.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74816)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @andreimatei, @dt, and @nvanbenschoten)

___
*[pkg/kv/bulk/buffering_adder.go, line 234 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74816#-MuSaoijAHk4crhtFvUv:-MuSebfj5NuuBrztqOH9:b-cv4tih) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b65fe665c548e96a718691aee1b3fdaab27d6db/pkg/kv/bulk/buffering_adder.go#L234)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should `b.sorted` be reset to `true` after this check?
</blockquote></details>

Eh, it seemed to me that once we've seen an unsorted key, we can assume all future keys are unsorted and not even bother comparing them, and get better branch prediction in the tight loop?
___
*[pkg/roachpb/api.proto, line 767 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74816#-MuSdIPx9Wk7eDmQgbyi:-MuSf8-6-8iIvkH4VKDG:b-y2b7ux) ([raw file](https://github.com/cockroachdb/cockroach/blob/087f134fa69f77a78fbbb1a0614c0a58d99d29e7/pkg/roachpb/api.proto#L767)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Did you consider making the predicate here be the range descriptor itself? So we would only split if the range's current descriptor is identical to the (optional) client-provided descriptor. I'd gravitate towards a solution like that because it feels more generally applicable and also has prior precedence with requests like `AdminChangeReplicasRequest`.
</blockquote></details>

I didn't consider that.

I'm happy to defer to KV on the right KV API here, but naively, just thinking of what API I might find easiest to use:  "split at 5 if you contain 1 and 10" captures the thing I care about: split if it is a certain width (1-10). And exact range descriptor requirement is maybe more than I really care about, which might matter both from a convince of calling it standpoint (now I need to go find a rangedesc) but also could now spuriously fail: say my range was 1-20. I think "if a single range is covering the width of 1-10, it should split at 5" and in the meantime, someone else says "if a single range is covering 11-20, it should split at 15".  Even if they come along and split before me, I actually still think we should split because we still contain 1 and 10, even though my rangedescriptor that says 20 is stale.

Anyway, I'm happy to change it if you think it should be rangedesc, just wanted to lay out what I was thinking with the key inclusion predicate.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74816)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @andreimatei, @dt, and @nvanbenschoten)

___
*[pkg/roachpb/api.proto, line 767 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74816#-MuSdIPx9Wk7eDmQgbyi:-MuSkyJU6kmDGvuvifnm:b-oibwj) ([raw file](https://github.com/cockroachdb/cockroach/blob/087f134fa69f77a78fbbb1a0614c0a58d99d29e7/pkg/roachpb/api.proto#L767)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I didn't consider that.

I'm happy to defer to KV on the right KV API here, but naively, just thinking of what API I might find easiest to use:  "split at 5 if you contain 1 and 10" captures the thing I care about: split if it is a certain width (1-10). And exact range descriptor requirement is maybe more than I really care about, which might matter both from a convince of calling it standpoint (now I need to go find a rangedesc) but also could now spuriously fail: say my range was 1-20. I think "if a single range is covering the width of 1-10, it should split at 5" and in the meantime, someone else says "if a single range is covering 11-20, it should split at 15".  Even if they come along and split before me, I actually still think we should split because we still contain 1 and 10, even though my rangedescriptor that says 20 is stale.

Anyway, I'm happy to change it if you think it should be rangedesc, just wanted to lay out what I was thinking with the key inclusion predicate.
</blockquote></details>

Oh, and I sorta like the key inclusion predicate's simplicity if you only provide one, smaller, key, since then it is just saying "please make sure this key (split key) is not in the same range as that key (predicate[0])" without expressing to much about the kv internals/specifics, just that you want those keys in separate ranges.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74816)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @andreimatei, and @dt)

___
*[pkg/kv/db.go, line 584 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74816#-MuvwkUp4nx2CdxfoLxf:-MuvwkUp4nx2CdxfoLxg:b-c6wwgq) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bdc9155fbe49940424ad47d2020660656a5d3ea/pkg/kv/db.go#L584)):*
> ```Go
> // SplitAndScatter is a helper that wraps AdminSplit + AdminScatter.
> func (db *DB) SplitAndScatter(
> 	ctx context.Context, key roachpb.Key, expirationTime hlc.Timestamp, predicateKeys []roachpb.Key,
> ```

Should we make this variadic?
___
*[pkg/kv/bulk/buffering_adder.go, line 234 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74816#-MuSaoijAHk4crhtFvUv:-MubZMr53ZLdZBqgsauB:b597hcx) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b65fe665c548e96a718691aee1b3fdaab27d6db/pkg/kv/bulk/buffering_adder.go#L234)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Eh, it seemed to me that once we've seen an unsorted key, we can assume all future keys are unsorted and not even bother comparing them, and get better branch prediction in the tight loop?
</blockquote></details>

Seems reasonable. It's probably worth a comment either here or on the field then.
___
*[pkg/kv/bulk/buffering_adder.go, line 315 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74816#-Muvx-Vc-9QaAUoDKY8P:-Muvx-VdB712Z8RZMXIe:b-ob695m) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bdc9155fbe49940424ad47d2020660656a5d3ea/pkg/kv/bulk/buffering_adder.go#L315)):*
> ```Go
> 		log.VEventf(ctx, 1, "splitting at key %d / %d: %s", i, b.curBuf.Len(), k)
> 		if err := b.sink.db.SplitAndScatter(ctx, k, hour, []roachpb.Key{prev}); err != nil {
> 			if strings.Contains(err.Error(), "predicate") {
> ```

Was the plan to keep this string matching, or did we want to strongly type this error?
___
*[pkg/kv/kvserver/replica_command.go, line 312 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74816#-Muvw37Y3ofAiNxDbwQk:-Muvw37Y3ofAiNxDbwQl:b-nmgrsk) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bdc9155fbe49940424ad47d2020660656a5d3ea/pkg/kv/kvserver/replica_command.go#L312)):*
> ```Go
> 	var reply roachpb.AdminSplitResponse
> 
> 	for _, k := range args.PredicateKeys {
> ```

nit: move this down below the `splitKey` computation block and give this a comment.
___
*[pkg/roachpb/api.proto, line 767 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74816#-MuSdIPx9Wk7eDmQgbyi:-MuvwNrQBlBwrtNEgDHn:b-n2h0cl) ([raw file](https://github.com/cockroachdb/cockroach/blob/087f134fa69f77a78fbbb1a0614c0a58d99d29e7/pkg/roachpb/api.proto#L767)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Oh, and I sorta like the key inclusion predicate's simplicity if you only provide one, smaller, key, since then it is just saying "please make sure this key (split key) is not in the same range as that key (predicate[0])" without expressing to much about the kv internals/specifics, just that you want those keys in separate ranges.
</blockquote></details>

I think what you said here makes sense. This API is already in terms of keys (`split_key`), so including some additional predicate keys feels consistent.
___
*[pkg/roachpb/api.proto, line 770 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74816#-Muvwwhi1lcy8La0b8_o:-Muvwwhj2vGfIUXni87Z:bta3b5w) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bdc9155fbe49940424ad47d2020660656a5d3ea/pkg/roachpb/api.proto#L770)):*
> ```protobuf
>   // cause the split to be rejected. This can be used by a caller to effectively
>   // send a "conditional split" request, i.e. a split if not already split.
>   repeated bytes predicate_keys = 5 [(gogoproto.casttype) = "Key"];
> ```

Could we add a test for this behavior?

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74816)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @andreimatei, and @nvanbenschoten)

___
*[pkg/kv/db.go, line 584 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74816#-MuvwkUp4nx2CdxfoLxf:-Mv-xHyDDoWOlNfndzo7:b3oh8n) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bdc9155fbe49940424ad47d2020660656a5d3ea/pkg/kv/db.go#L584)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we make this variadic?
</blockquote></details>


Done.
___
*[pkg/kv/bulk/buffering_adder.go, line 234 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74816#-MuSaoijAHk4crhtFvUv:-Mv02jl8ElnN3Ci0b7Fs:bqx1far) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b65fe665c548e96a718691aee1b3fdaab27d6db/pkg/kv/bulk/buffering_adder.go#L234)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Seems reasonable. It's probably worth a comment either here or on the field then.
</blockquote></details>

Done (put it in Reset which is where I'd have thought to look for it).
___
*[pkg/kv/bulk/buffering_adder.go, line 215 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74816#-MuSc1sp48INufHtMeDH:-Mv02iur-GB8poAl9U4b:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5cf13a7b09a6456840662bceed9a0219fc66ac2/pkg/kv/bulk/buffering_adder.go#L215)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Looks like this comment is in the wrong place now.
</blockquote></details>

Done.
___
*[pkg/kv/bulk/buffering_adder.go, line 315 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74816#-Muvx-Vc-9QaAUoDKY8P:-Mv02p4jBnuzrobp258w:b-xhwbj8) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bdc9155fbe49940424ad47d2020660656a5d3ea/pkg/kv/bulk/buffering_adder.go#L315)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Was the plan to keep this string matching, or did we want to strongly type this error?
</blockquote></details>

Added a TODO. 
___
*[pkg/kv/kvserver/replica_command.go, line 312 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74816#-Muvw37Y3ofAiNxDbwQk:-Mv03G_w3pxzc05YIlB1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bdc9155fbe49940424ad47d2020660656a5d3ea/pkg/kv/kvserver/replica_command.go#L312)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: move this down below the `splitKey` computation block and give this a comment.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/kvserverbase/bulk_adder.go, line 77 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74816#-MuScxjM0hMuegEmdfXX:-Mv04Kgk-u1U56T5_5y_:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5cf13a7b09a6456840662bceed9a0219fc66ac2/pkg/kv/kvserver/kvserverbase/bulk_adder.go#L77)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`s/like/likely/`
</blockquote></details>

Done
___
*[pkg/roachpb/api.proto, line 770 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/74816#-Muvwwhi1lcy8La0b8_o:-Mv04l5kBIUm2B5ChtC-:b-hphei9) ([raw file](https://github.com/cockroachdb/cockroach/blob/1bdc9155fbe49940424ad47d2020660656a5d3ea/pkg/roachpb/api.proto#L770)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Could we add a test for this behavior?
</blockquote></details>

Yep, done (was just waiting to see if kv liked the proposed api before wrote a test against it).

**Review by nvb — APPROVED** [review]
> Reviewed 1 of 14 files at r5, 6 of 7 files at r6, 1 of 2 files at r7, 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74816)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @andreimatei, and @dt)

___
*[pkg/ccl/importccl/import_processor_planning.go, line 267 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/74816#-Mv0D2n05xm1eDpBqsne:-Mv0D2n05xm1eDpBqsnf:b-s5ckrk) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c725885020480b971523e8c2e9f08e68f35a549/pkg/ccl/importccl/import_processor_planning.go#L267)):*
> ```Go
> 				UserProto:             user.EncodeProto(),
> 				DatabasePrimaryRegion: details.DatabasePrimaryRegion,
> 				InitialSplits:         int32(len(sqlInstanceIDs)),
> ```

Are we ok with this change? This is now the number of SQL pods in a serverless cluster, not the number of KV nodes, right?

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74816)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @andreimatei, and @nvanbenschoten)

___
*[pkg/ccl/importccl/import_processor_planning.go, line 267 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/74816#-Mv0D2n05xm1eDpBqsne:-Mv0ImEz6AQdHFEqT4uC:b-td37wp) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c725885020480b971523e8c2e9f08e68f35a549/pkg/ccl/importccl/import_processor_planning.go#L267)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Are we ok with this change? This is now the number of SQL pods in a serverless cluster, not the number of KV nodes, right?
</blockquote></details>

I think this is correct. We should be pre-splitting according the the size of the tenant, not the shared storage cluster that has hundreds/thousands of other tenants on it too.

**Comment by dt** [comment]
TFTR!

bors r+

**Pull request merged**
