### PR TITLE
config/storage: cache zone config values to avoid repetitive deserialization

### LINKED ISSUE #21702: storage: unmarshaling descriptors makes 35% of garbage on cluster with many ranges
I noticed this while playing with the TPCC-1000 dataset against a cluster that exhibited #21689, which creates a ton of ranges. The cluster had around 50,000 ranges.

The metrics collector is supposed to iterate over every range every 10 seconds, collecting stats on it. One of the steps to collecting stats is to check the range zone config to see how many replicas it's supposed to have. Checking the zone config requires demarshalling the range's table descriptor and the table's zone config, if it has one, which is the source of the garbage.

The reason that this produces so much garbage in the end is that there's no caching for any of these lookups, so each of the 50,000 ranges causes a full table descriptor unmarshal.

We should figure out a way to fix this. Here are some ideas:

1. Cache the results of `getZoneConfigForID`, which is a map from descriptor ID to zone config. The challenge here would be determining the correct eviction policy, its relation to descriptor changes from gossip, and so on.
2. Simpler would be to memoize the results of the above call just for the lifetime of the scan over all of the ranges. This way I think we could avoid thinking about eviction.
3. @benesch suggested adding an index to the `system.namespace` table on its config id column, which would permit looking up whether a range has a specialized zone config for its table or partition without having to demarshal its descriptor to check.

I uploaded the profiles I used to find this issue below. You can see that this ComputeMetrics flow takes 20% of the CPU of the cluster, which was at the time of profiling running a large `COUNT(*)`. @danhhz rightly points out that you can't conclude much there since the cluster wasn't fully loaded, but it's still concerning in my opinion.

[pprof.alloc_objects.alloc_space.inuse_objects.inuse_space.tpcc-1000-1node-count-stock.pb.gz](https://github.com/cockroachdb/cockroach/files/1656605/pprof.alloc_objects.alloc_space.inuse_objects.inuse_space.tpcc-1000-1node-count-stock.pb.gz)
[pprof.cockroach.samples.cpu.tpcc-1000-1node-count-stock.pb.gz](https://github.com/cockroachdb/cockroach/files/1656606/pprof.cockroach.samples.cpu.tpcc-1000-1node-count-stock.pb.gz)

I think it would be great to get this fixed by 2.0. I can't prove it, but I suspect that this issue is one of the reasons why idle clusters eat up a lot of CPU, something that several users have asked about.

### PR DESCRIPTION
**Pull request by spencerkimball**
This change allows a `SystemConfig` to cache object ID -> `ZoneConfig`
lookups to avoid repetitively deserializing table descriptors and zone
configs for every replica in the system. Replicas themselves now also
cache zone config entries to avoid maintaining per-replica min/max bytes
and for making future use of additional zone config parameters simpler
(e.g. zone config GC policies, number of replicas, etc.).

Fixes #21702

### CODE REVIEW

**Review by nvb — DISMISSED** [review]
Mechanically this :lgtm: However, I'm not familiar enough with zone configs and especially subzones and placeholder zones to be able to comment about them.

> Reviewed 61 of 67 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30143#-:-LMJZoQn7a-Ytj-W3nfO:b-rgs77c)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/replica_proposal.go, line 537 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30143#-LMJZ5HX2b-fVTJNuwFV:-LMJZ5HYE0LG1N_5XOz8:bvydt9y) ([raw file](https://github.com/cockroachdb/cockroach/blob/b27fe13a5df7a9e06b3b8305eb00dadf4aafcc7b/pkg/storage/replica_proposal.go#L537)):*
> ```Go
> 
> 	if needsSplitBySize {
> 		log.Infof(context.TODO(), "zone for %s: %+v", r, r.GetZoneConfig())
> ```

Did you mean to remove this?

**Review by spencerkimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30143)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/storage/replica_proposal.go, line 537 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30143#-LMJZ5HX2b-fVTJNuwFV:-LMNxvMhEoP36Y0s-F_Z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b27fe13a5df7a9e06b3b8305eb00dadf4aafcc7b/pkg/storage/replica_proposal.go#L537)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Did you mean to remove this?
</blockquote></details>

Done.

**Comment by spencerkimball** [comment]
Added @benesch to review.

**Review by benesch — COMMENTED** [review]
Whew, that looked like it was painful. Thanks for finally fixing this! And sorry I didn't get to this yesterday; I got stuck tracking down fallout from the go1.11 bump.

The only thing I'd like to get resolved before merging is my confusion about the `cache` return parameter from `sql.ZoneConfigHook`. Feel free to ignore everything else.

> Reviewed 67 of 67 files at r1, 2 of 6 files at r2, 24 of 24 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30143#-:-LMhW3hi1dWlEilR966t:b-5j4kqy)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/config/system.go, line 201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30143#-LMh4WtqEpD9wskWiWFa:-LMh4WtrCd5W4QCYBQvz:b-yneszy) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd767f478e3fe397fe20614b801cb660aaa6bb0e/pkg/config/system.go#L201)):*
> ```Go
> // GetZoneConfigForKey looks up the zone config for the object (table
> // or database, specified by key.id) and optional partition (specified
> // by key.suffix). It is the caller's responsibility to ensure that
> ```

Is this true? Seems like `key` is still just a `roachpb.RKey`. I think maybe this comment should have gone on `getZoneConfigForKey`?
___
*[pkg/config/system.go, line 244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30143#-LMhVFmhB03HvM9HRIt3:-LMhVFmhB03HvM9HRIt4:b-y7oe6o) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd767f478e3fe397fe20614b801cb660aaa6bb0e/pkg/config/system.go#L244)):*
> ```Go
> 		} else if zone != nil {
> 			entry = zoneEntry{zone: zone, placeholder: placeholder}
> 			if cache {
> ```

What's this `cache` param about? It seems to always be equivalent to `err != nil`.
___
*[pkg/sql/show_zone_config.go, line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30143#-LMhSfDxBlKplcs1vMEQ:-LMhSfDxBlKplcs1vMER:bkmce3t) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd767f478e3fe397fe20614b801cb660aaa6bb0e/pkg/sql/show_zone_config.go#L109)):*
> ```Go
> 			zone = &subzone.Config
> 		}
> 	}
> ```

I think I'd have preferred to keep this complexity in `GetZoneConfigInTxn`, since this chunk of logic is duplicated in `setZoneConfig` and `showZoneConfig`, and `verifyZoneConfigs`. Feel free to leave to a follow up, since I think Ridwan's going to be doing cleanup in the area anyway.
___
*[pkg/storage/replica.go, line 6735 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30143#-LMh8aH-3XqCjQztjJ3e:-LMh8aH-3XqCjQztjJ3f:b-pr8uok) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd767f478e3fe397fe20614b801cb660aaa6bb0e/pkg/storage/replica.go#L6735)):*
> ```Go
> 	kvs := br.Responses[0].GetInner().(*roachpb.ScanResponse).Rows
> 	sysCfg := config.NewSystemConfig()
> 	sysCfg.Values = kvs
> ```

Food for thought: perhaps `NewSystemConfig` should take the values as an argument.
___
*[pkg/storage/store_rebalancer.go, line 391 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30143#-LMh9hzS9ARr7Fp6l4WB:-LMh9hzS9ARr7Fp6l4WC:b10mf32) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd767f478e3fe397fe20614b801cb660aaa6bb0e/pkg/storage/store_rebalancer.go#L391)):*
> ```Go
> 
> 		desc, zone := replWithStats.repl.DescAndZone()
> 		if zone == nil {
> ```

Could this really be nil? It seems like repl.mu.zone is always set to a non-nil zone config.

**Review by spencerkimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30143)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/config/system.go, line 201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30143#-LMh4WtqEpD9wskWiWFa:-LMhdwUkEOHOetjDCoEo:bg1ktfs) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd767f478e3fe397fe20614b801cb660aaa6bb0e/pkg/config/system.go#L201)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Is this true? Seems like `key` is still just a `roachpb.RKey`. I think maybe this comment should have gone on `getZoneConfigForKey`?
</blockquote></details>

You're right. Fixed.
___
*[pkg/config/system.go, line 244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30143#-LMhVFmhB03HvM9HRIt3:-LMhe-l52ZpPqTqeVBuL:b-9y0s1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd767f478e3fe397fe20614b801cb660aaa6bb0e/pkg/config/system.go#L244)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

What's this `cache` param about? It seems to always be equivalent to `err != nil`.
</blockquote></details>

The cache param is returned by the zone config hook. It specifies whether the hook allows its results to be cached by the `SystemConfig`. This is always true in production, but not true in some test cases where there's a testing hook set.
___
*[pkg/sql/show_zone_config.go, line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30143#-LMhSfDxBlKplcs1vMEQ:-LMheKDIE7zHRMTQlm4z:b-ey31x4) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd767f478e3fe397fe20614b801cb660aaa6bb0e/pkg/sql/show_zone_config.go#L109)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I think I'd have preferred to keep this complexity in `GetZoneConfigInTxn`, since this chunk of logic is duplicated in `setZoneConfig` and `showZoneConfig`, and `verifyZoneConfigs`. Feel free to leave to a follow up, since I think Ridwan's going to be doing cleanup in the area anyway.
</blockquote></details>

No, that's a solid idea. I wasn't sure about the various ways that `GetZoneConfigInTxn` was used when I started this. I'll move this code back into that method and return the subzone from there instead.
___
*[pkg/storage/replica.go, line 6735 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30143#-LMh8aH-3XqCjQztjJ3e:-LMhfEO6Ba3jgPCfUv5Y:b-3sx2ts) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd767f478e3fe397fe20614b801cb660aaa6bb0e/pkg/storage/replica.go#L6735)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Food for thought: perhaps `NewSystemConfig` should take the values as an argument.
</blockquote></details>

In this case we don't want to use `NewSystemConfig` because we want the underlying protobuf, not the caching parent struct
___
*[pkg/storage/store_rebalancer.go, line 391 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30143#-LMh9hzS9ARr7Fp6l4WB:-LMhhtFg1-g8iQaiGlVS:b-9tac9d) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd767f478e3fe397fe20614b801cb660aaa6bb0e/pkg/storage/store_rebalancer.go#L391)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Could this really be nil? It seems like repl.mu.zone is always set to a non-nil zone config.
</blockquote></details>

It is in some test conditions and it's a pain to work around it from the test itself. (e.g. `storage.TestChooseLeaseToTransfer`)

**Review by benesch — APPROVED** [review]
:lgtm_strong: 

> Reviewed 13 of 13 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30143#-:-LMmtNS-9go8s3vUWvQH:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/config/system.go, line 244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30143#-LMhVFmhB03HvM9HRIt3:-LMmszq_DdCgwCTBEUnR:b4jmnot) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd767f478e3fe397fe20614b801cb660aaa6bb0e/pkg/config/system.go#L244)):*
<details><summary><i>Previously, spencerkimball (Spencer Kimball) wrote…</i></summary><blockquote>

The cache param is returned by the zone config hook. It specifies whether the hook allows its results to be cached by the `SystemConfig`. This is always true in production, but not true in some test cases where there's a testing hook set.
</blockquote></details>

Ah! Thanks, missed that. 

Now that zone configs are accessible from SQL we can probably get rid of that testing hook with some elbow grease. (Definitely not suggested that you do that.)
___
*[pkg/storage/replica.go, line 6735 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30143#-LMh8aH-3XqCjQztjJ3e:-LMmsT8C6rFfnh6KB6xz:bn9kqfh) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd767f478e3fe397fe20614b801cb660aaa6bb0e/pkg/storage/replica.go#L6735)):*
<details><summary><i>Previously, spencerkimball (Spencer Kimball) wrote…</i></summary><blockquote>

In this case we don't want to use `NewSystemConfig` because we want the underlying protobuf, not the caching parent struct
</blockquote></details>

Ack. That comment was on an earlier revision of your PR. Design as-is LGTM.
___
*[pkg/storage/store_rebalancer.go, line 391 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30143#-LMh9hzS9ARr7Fp6l4WB:-LMmsiRl6fqRG_Y2rT1T:bwt9wd0) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd767f478e3fe397fe20614b801cb660aaa6bb0e/pkg/storage/store_rebalancer.go#L391)):*
<details><summary><i>Previously, spencerkimball (Spencer Kimball) wrote…</i></summary><blockquote>

It is in some test conditions and it's a pain to work around it from the test itself. (e.g. `storage.TestChooseLeaseToTransfer`)
</blockquote></details>

Seems like you did, though? :raised_hands:

**Pull request merged**
