### PR TITLE
changefeedccl: improve parquet byte estimates and flushing scheme

### PR DESCRIPTION
**Pull request by jayshrivastava**
### changefeedccl: ensure that parquet counts emitted rows in metrics
Previously, the parquet sink would not update the `EmittedMessages`
metric for emitted rows. This change updates the sink to do so.
This change does not add a test, but there is an open issue to add tests
for metrics: https://github.com/cockroachdb/cockroach/issues/111042.

Release note: None
Epic: None

---

### roachtest/cdc: add parquet initial scan roachtest
This change adds a simple parquet initial scan roachtest.

Release note: None
Epic: None

---

### util/parquet: support explicit flushing and add byte estimation
This change updates the parquet writer to have two new
APIs `BufferedBytesEstimate() int64` and `Flush() error`.

`BufferedBytesEstimate` returns the number of bytes currently
buffered by the writer (ie. bytes which have not been written
to the sink). This value is calcualted continuously by the writer
as rows are written.

`Flush` flushes buffered bytes by closing the current row group writer
and initializing a new one.

These methods can be used by a caller to flush the writer depending on
how much data is buffered in mem.

This change also adds testing for both of these methods. `BufferedBytesEstimate`
is tested via a unit test. `Flush` test coverage is added in `TestRandomDatums`.
The test calls `Flush` randomly and asserts the output is correct.

Release note: None
Epic: None

---

### changefeedccl: use byte estimate when flushing parquet files
Previously, the parquet sink/encoder would use a buffer to decide
when it emit files to cloudstorage. This scheme did not take into
account the bytes buffered by the parquet writer library. This change
makes it so that the parquet sink/encoder takes into account
memory buffered by the library when deciding if it needs to perform
a size-based flush.

Release note: None
Epic: None

---

### changefeedccl: add changefeed.cloudstorage_buffered_bytes metric
This change adds a metric to track the number of bytes buffered by
the cloudstorage sink.

Release note: None
Epic: None

### CODE REVIEW

**Review by miretskiy — CHANGES_REQUESTED** [review]
> Reviewed 13 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111138)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @jayshrivastava, and @smg260)

___
*[`pkg/ccl/changefeedccl/parquet_sink_cloudstorage.go` line 237 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111138#-NfBOtNT8GRbw9nTm2Ex:-NfBOtNT8GRbw9nTm2Ey:benvraf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae3db43c920a1c57fd44c829c203f5a7365b7039/pkg/ccl/changefeedccl/parquet_sink_cloudstorage.go#L237)):*
> ```Go
> 
> 	if log.V(1) {
> 		if parquetSink.everyN.ShouldLog() {
> ```

collapse log.V(1) && everyN.ShouldLog?
___
*[`pkg/util/parquet/writer.go` line 136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111138#-NfBLAWVCSJ6-NPkBtFh:-NfBLAWVCSJ6-NPkBtFi:bl1lzae) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae3db43c920a1c57fd44c829c203f5a7365b7039/pkg/util/parquet/writer.go#L136)):*
> ```Go
> //
> // NB: The writer may buffer all the written data in memory until it is
> // Flush()ed to the sink.
> ```

Thanks for adding this important notice.

I understand why you say "may buffer" -- I think that's because the underlying group write has a 64M
limit on how much it buffers before it decides to auto flush.

I think that, at least in theory, if you allow underlying group write to flush automatically, it's possible
that your byte estimate may get out of whack because of the updateBytesEstimate line:
`w.bufferedBytesEstimate += internalCw.EstimatedBufferedValueBytes()`
This additive update only works if you can guarantee that underlying group write does not flush.

I think you should make this notice a lot stronger to say that this writer buffers *all* data in memory until
explicit flush is called.  You should use math.MaxInt64 as the row writer parameter to guarantee that it does not
flush (and of course, you should add a note why this is used).

I may be misunderstanding something and if so, please correct me if I am.
___
*[`pkg/util/parquet/writer.go` line 248 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111138#-NfBMBMt6KKeV1zskJ_3:-NfBMBMt6KKeV1zskJ_4:b-fk8sgz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae3db43c920a1c57fd44c829c203f5a7365b7039/pkg/util/parquet/writer.go#L248)):*
> ```Go
> 	w.bufferedBytesEstimate = 0
> 	for datumColIdx, d := range datums {
> 		if err := w.sch.cols[datumColIdx].colWriter.Write(d, w.columnChunkWriterCache[datumColIdx], w.ba, w.updateByteEstimate); err != nil {
> ```

I think it would be better if you changed the colWriter interface (Write method) to instead return the number of bytes currently buffered.  Update your estimate after calling colWriter.Write explicitly.
There are few benefits imo: 1.  I think you won't need to do type assertions in updateByteEstimate since the underlying writer knows its byte estimate 2. you won't be bleeding internals of "writer" implementation into your write functions .
___
*[`pkg/util/parquet/writer.go` line 304 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111138#-NfBJBMCEa_MHAah_FjU:-NfBJBMCEa_MHAah_FjV:b-o5ylm5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae3db43c920a1c57fd44c829c203f5a7365b7039/pkg/util/parquet/writer.go#L304)):*
> ```Go
> // internalColumnWriter is an interface used to expose methods on the column
> // chunk writers below which are not a part of the file.ColumnChunkWriter
> // inteface.
> ```

nit : augment comment  it a bit to indicate that the underlying parquet types (BytesWrite, IntWriter, etc) all implement this method.
___
*[`pkg/ccl/changefeedccl/changefeed_test.go` line 8909 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111138#-NfBOBlqDjomSIHchn3j:-NfBOBlqDjomSIHchn3k:bx6mkuj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae3db43c920a1c57fd44c829c203f5a7365b7039/pkg/ccl/changefeedccl/changefeed_test.go#L8909)):*
> ```Go
> 		// Because checkpoints are disabled, we should have some bytes build up
> 		// in the sink.
> 		// Parquet is a much more efficient format, so the buffered files will
> ```

nit: move parquet part of the comment inside if?
___
*[`pkg/ccl/changefeedccl/changefeed_test.go` line 8924 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111138#-NfBOH0aECqsPMmLX5n1:-NfBOH0aECqsPMmLX5n2:b-7m74ok) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae3db43c920a1c57fd44c829c203f5a7365b7039/pkg/ccl/changefeedccl/changefeed_test.go#L8924)):*
> ```Go
> 
> 		// Allow checkpoints to pass through and flush the sink. We should see
> 		// zero bytes buffered after that.
> ```

nice.
___
*[`pkg/ccl/changefeedccl/testfeed_test.go` line 1089 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111138#-NfBO-oiAp7Rl1bN0Wr-:-NfBO-oiAp7Rl1bN0Wr0:bspmqza) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae3db43c920a1c57fd44c829c203f5a7365b7039/pkg/ccl/changefeedccl/testfeed_test.go#L1089)):*
> ```Go
> 		}
> 		randNum := rand.Intn(5)
> 		if randNum < 0 {
> ```

did you mean to include this change?
___
*[`pkg/util/parquet/writer_test.go` line 705 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111138#-NfBNs5-2ogh1N7FTAc8:-NfBNs5-2ogh1N7FTAc9:bru2he8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae3db43c920a1c57fd44c829c203f5a7365b7039/pkg/util/parquet/writer_test.go#L705)):*
> ```Go
> 		tree.NewDTuple(tupleTyp, tree.NewDInt(8), tree.NewDInt(9), tree.NewDString("uiop")),
> 		da,
> 	}}
> ```

let's add a test case that adds identical tuple too.
___
*[`pkg/util/parquet/writer_test.go` line 737 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111138#-NfBNOrMAwNJ_UtAnYZ2:-NfBNOrMAwNJ_UtAnYZ3:b-yehlkk) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae3db43c920a1c57fd44c829c203f5a7365b7039/pkg/util/parquet/writer_test.go#L737)):*
> ```Go
> 	// The first estimate is large because of the overhead of the encoder.
> 	// The deltas are small because parquet is good at bit packing.
> 	expectedEstimates := []int64{754, 792, 830, 866, 904}
> ```

i'm a bit worried this test may become brittle if the underlying parquet library changes
(it's encoder, compressor, etc)...
I understand what you're trying to do here, and I wonder if we should settle on something that's
a bit less precise.  Like: asserting the estimate is >0 when you add something.  Asserting that
it increases when you add something new.  It must also increase even if you add identical row again --
no such thing as infinite compression.
And of course, estimate should be exactly 0 after flush.

**Review by jayshrivastava — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111138)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @miretskiy, and @smg260)

___
*[`pkg/ccl/changefeedccl/parquet_sink_cloudstorage.go` line 237 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111138#-NfBOtNT8GRbw9nTm2Ex:-NfBovT0AyjInkILvTI8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae3db43c920a1c57fd44c829c203f5a7365b7039/pkg/ccl/changefeedccl/parquet_sink_cloudstorage.go#L237)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

collapse log.V(1) && everyN.ShouldLog?
</blockquote></details>

Done.
___
*[`pkg/util/parquet/write_functions.go` line 227 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111138#-NfCg-c-8Qyvr_20iuXQ:-NfCg-c-8Qyvr_20iuXR:b-ufhc5x) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6b72120129d0922d9560f0d3bbe71c0c61989f3/pkg/util/parquet/write_functions.go#L227)):*
> ```Go
> 			len(cw), len(tw))
> 	}
> 	return writeTuple(d, cw, a, tw)
> ```

Unlike the arraywriter and scalarwriter, we don't call `estimatedBufferedBytesForChunkWriter(cw[0])` because we actually need to call it for each column writer. We push this call down to `writeTuple` because that is actually doing the iteration.
___
*[`pkg/util/parquet/writer.go` line 136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111138#-NfBLAWVCSJ6-NPkBtFh:-NfCZ7mx1RUOjqqTpBRb:bxrz19t) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae3db43c920a1c57fd44c829c203f5a7365b7039/pkg/util/parquet/writer.go#L136)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Thanks for adding this important notice.

I understand why you say "may buffer" -- I think that's because the underlying group write has a 64M
limit on how much it buffers before it decides to auto flush.

I think that, at least in theory, if you allow underlying group write to flush automatically, it's possible
that your byte estimate may get out of whack because of the updateBytesEstimate line:
`w.bufferedBytesEstimate += internalCw.EstimatedBufferedValueBytes()`
This additive update only works if you can guarantee that underlying group write does not flush.

I think you should make this notice a lot stronger to say that this writer buffers *all* data in memory until
explicit flush is called.  You should use math.MaxInt64 as the row writer parameter to guarantee that it does not
flush (and of course, you should add a note why this is used).

I may be misunderstanding something and if so, please correct me if I am.
</blockquote></details>

Okay so I think it's ideal to have full control over flushing. Therefore, I pushed what you recommended. Having the data page size uncapped and row group size uncapped means that we can control when exactly to flush. 

With my most recent changes, calling Flush() will flush the whole row group. Because all the data is buffered, one data page is created per column. So if we flush every 1MB, we have one 1MB row groups and 1/16MB data pages if the table has 16 cols. 

There are some recommendations on row group sizes and data pages sizes https://parquet.apache.org/docs/file-format/configurations/#:~:text=Data%20Page%20Size,-Data%20pages%20should&text=Larger%20page%20sizes%20incur%20less,recommend%208KB%20for%20page%20sizes, but I don't think this is too important to worry about now. Maybe if a customer has a real concern in the future, we can come up with something else.
___
*[`pkg/util/parquet/writer.go` line 248 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111138#-NfBMBMt6KKeV1zskJ_3:-NfCd30LBUl2NMJ81UP4:bv8crua) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae3db43c920a1c57fd44c829c203f5a7365b7039/pkg/util/parquet/writer.go#L248)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

I think it would be better if you changed the colWriter interface (Write method) to instead return the number of bytes currently buffered.  Update your estimate after calling colWriter.Write explicitly.
There are few benefits imo: 1.  I think you won't need to do type assertions in updateByteEstimate since the underlying writer knows its byte estimate 2. you won't be bleeding internals of "writer" implementation into your write functions .
</blockquote></details>

Done. I think it's better too. I put it in the writer so I could pass in testing knobs. Now the testing knob is just a global var. 
___
*[`pkg/ccl/changefeedccl/changefeed_test.go` line 8909 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111138#-NfBOBlqDjomSIHchn3j:-NfCfNFt1e1z4MgomzrK:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae3db43c920a1c57fd44c829c203f5a7365b7039/pkg/ccl/changefeedccl/changefeed_test.go#L8909)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

nit: move parquet part of the comment inside if?
</blockquote></details>

Done
___
*[`pkg/ccl/changefeedccl/testfeed_test.go` line 1089 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111138#-NfBO-oiAp7Rl1bN0Wr-:-NfBp0Lo6JMYGqaVHLnO:bu2j3sr) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae3db43c920a1c57fd44c829c203f5a7365b7039/pkg/ccl/changefeedccl/testfeed_test.go#L1089)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

did you mean to include this change?
</blockquote></details>

Nope. Removed.
___
*[`pkg/util/parquet/writer_test.go` line 705 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111138#-NfBNs5-2ogh1N7FTAc8:-NfCdOdz-OiOdSpKzR0F:b-v9oqgu) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae3db43c920a1c57fd44c829c203f5a7365b7039/pkg/util/parquet/writer_test.go#L705)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

let's add a test case that adds identical tuple too.
</blockquote></details>

Done. I added a test which inserts identical rows.
___
*[`pkg/util/parquet/writer_test.go` line 737 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111138#-NfBNOrMAwNJ_UtAnYZ2:-NfCdP8hBqW_lwSnkO83:b-5kpsbr) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae3db43c920a1c57fd44c829c203f5a7365b7039/pkg/util/parquet/writer_test.go#L737)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

i'm a bit worried this test may become brittle if the underlying parquet library changes
(it's encoder, compressor, etc)...
I understand what you're trying to do here, and I wonder if we should settle on something that's
a bit less precise.  Like: asserting the estimate is >0 when you add something.  Asserting that
it increases when you add something new.  It must also increase even if you add identical row again --
no such thing as infinite compression.
And of course, estimate should be exactly 0 after flush.
</blockquote></details>

Updated the test. Lmk what you think!

**Review by miretskiy — APPROVED** [review]
> Reviewed 1 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111138)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @jayshrivastava, and @smg260)

___
*[`pkg/util/parquet/write_functions.go` line 227 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111138#-NfCg-c-8Qyvr_20iuXQ:-NfCkvckDUii8FuYo9VE:bb7cwne) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6b72120129d0922d9560f0d3bbe71c0c61989f3/pkg/util/parquet/write_functions.go#L227)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

Unlike the arraywriter and scalarwriter, we don't call `estimatedBufferedBytesForChunkWriter(cw[0])` because we actually need to call it for each column writer. We push this call down to `writeTuple` because that is actually doing the iteration.
</blockquote></details>

ack.
___
*[`pkg/util/parquet/write_functions.go` line 145 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/111138#-NfCiP3V1wCFBa-1-5Kc:-NfCiP3WAr4SYveG0D5j:bz22p2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8344270c58ca0d755d40c8491d700df6f1595f0/pkg/util/parquet/write_functions.go#L145)):*
> ```Go
> // and writing it to a file.ColumnChunkWriter. For tuples, there is a
> // file.ColumnChunkWriter per tuple field. The `callback` is executed
> // once per file.ColumnChunkWriter after the respective datums are written.
> ```

nit: callback  comment no longer applicable.
___
*[`pkg/util/parquet/write_functions.go` line 258 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/111138#-NfCjKaoBJ0i41CC0iXQ:-NfCjKaoBJ0i41CC0iXR:b5q3c9d) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8344270c58ca0d755d40c8491d700df6f1595f0/pkg/util/parquet/write_functions.go#L258)):*
> ```Go
> 			defLevel = tupleFieldNilDefLevel
> 		}
> 		if err := wFn(dt.D[i], w[i], a, defLevel, newEntryRepLevel); err != nil {
> ```

kind of a shame to repeat (almost verbatim) the code here, and on top for the d == tree.DNull case.
What do you think of something like:
```
var dt *tree.DTuple
if d != tree.DNull {
   if tup, ok := tree.AsDTuple(d); ok {
      dt = tup
   } else {
      return 0, pgerror.Newf(pgcode.DatatypeMismatch, "expected DTuple, found %T", d)
   }
}

// Helper function to return datum at specified tuple position and def level.
tupleDatumAndDefLevel := func(pos int) (tree.Datum, []int16) {
   if  dt == nil {
      return tree.DNull, nilTupleDefLevel
   }
   if dt.D[i] == tree.DNull {
      return tree.DNull,  tupleFieldNilDefLevel
   }
   return dt.D[i], tupleFieldNonNilDefLevel
```

And then, basically, have a single loop that accesses appropriate datum/deflevel for each i.
___
*[`pkg/util/parquet/writer.go` line 136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111138#-NfBLAWVCSJ6-NPkBtFh:-NfChonM8sUqvcd4oz9x:b-jdokbq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae3db43c920a1c57fd44c829c203f5a7365b7039/pkg/util/parquet/writer.go#L136)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

Okay so I think it's ideal to have full control over flushing. Therefore, I pushed what you recommended. Having the data page size uncapped and row group size uncapped means that we can control when exactly to flush. 

With my most recent changes, calling Flush() will flush the whole row group. Because all the data is buffered, one data page is created per column. So if we flush every 1MB, we have one 1MB row groups and 1/16MB data pages if the table has 16 cols. 

There are some recommendations on row group sizes and data pages sizes https://parquet.apache.org/docs/file-format/configurations/#:~:text=Data%20Page%20Size,-Data%20pages%20should&text=Larger%20page%20sizes%20incur%20less,recommend%208KB%20for%20page%20sizes, but I don't think this is too important to worry about now. Maybe if a customer has a real concern in the future, we can come up with something else.
</blockquote></details>

You could consider making this threshold somewhat dynamic based on  the number of columns.  But I think it's fine as is.
___
*[`pkg/util/parquet/writer.go` line 168 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/111138#-NfCi7Jm5jgP_K-l7hPu:-NfCi7Jm5jgP_K-l7hPv:b-tckiwq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8344270c58ca0d755d40c8491d700df6f1595f0/pkg/util/parquet/writer.go#L168)):*
> ```Go
> 	// data page size and row group size are uncapped. This means that the library will not flush
> 	// automatically when the buffered data size is large. It will only flush the caller calls Flush().
> 	// Note that this means there will be one data page per column per row group in the final file.
> ```

` one data page per column per row group in the final file.`... that's if the caller calls Flush only once?
___
*[`pkg/util/parquet/writer_test.go` line 790 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/111138#-NfCl_cTBr0jwRXehcH4:-NfCl_cTBr0jwRXehcH5:b-p5wy1o) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8344270c58ca0d755d40c8491d700df6f1595f0/pkg/util/parquet/writer_test.go#L790)):*
> ```Go
> 				for i := 0; i < tc.numInsertsPerStep; i++ {
> 					for _, d := range tc.datums {
> 						err := writer.AddRow(d)
> ```

perhaps a short comment why we add the same thing multiple times.

**Review by jayshrivastava — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111138)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @miretskiy, and @smg260)

___
*[`pkg/util/parquet/write_functions.go` line 258 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/111138#-NfCjKaoBJ0i41CC0iXQ:-NfCux8Z5k-SlGsNHXvt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8344270c58ca0d755d40c8491d700df6f1595f0/pkg/util/parquet/write_functions.go#L258)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

kind of a shame to repeat (almost verbatim) the code here, and on top for the d == tree.DNull case.
What do you think of something like:
```
var dt *tree.DTuple
if d != tree.DNull {
   if tup, ok := tree.AsDTuple(d); ok {
      dt = tup
   } else {
      return 0, pgerror.Newf(pgcode.DatatypeMismatch, "expected DTuple, found %T", d)
   }
}

// Helper function to return datum at specified tuple position and def level.
tupleDatumAndDefLevel := func(pos int) (tree.Datum, []int16) {
   if  dt == nil {
      return tree.DNull, nilTupleDefLevel
   }
   if dt.D[i] == tree.DNull {
      return tree.DNull,  tupleFieldNilDefLevel
   }
   return dt.D[i], tupleFieldNonNilDefLevel
```

And then, basically, have a single loop that accesses appropriate datum/deflevel for each i.
</blockquote></details>

Done.
___
*[`pkg/util/parquet/writer.go` line 136 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111138#-NfBLAWVCSJ6-NPkBtFh:-NfCuyatBXRw-nzMABYK:b2nhb2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/ae3db43c920a1c57fd44c829c203f5a7365b7039/pkg/util/parquet/writer.go#L136)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

You could consider making this threshold somewhat dynamic based on  the number of columns.  But I think it's fine as is.
</blockquote></details>

Ack
___
*[`pkg/util/parquet/writer.go` line 168 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/111138#-NfCi7Jm5jgP_K-l7hPu:-NfCv0c64ogafgAfTsEs:b-v8epdz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8344270c58ca0d755d40c8491d700df6f1595f0/pkg/util/parquet/writer.go#L168)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

` one data page per column per row group in the final file.`... that's if the caller calls Flush only once?
</blockquote></details>

My comment doesn't say there is one row group :). 
___
*[`pkg/util/parquet/writer_test.go` line 790 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/111138#-NfCl_cTBr0jwRXehcH4:-NfCvKbB30XnD-sUQZsT:b-w13kyg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b8344270c58ca0d755d40c8491d700df6f1595f0/pkg/util/parquet/writer_test.go#L790)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

perhaps a short comment why we add the same thing multiple times.
</blockquote></details>

I had the comment on tc.numInsertsPerStep, but I can move it here.

**Pull request merged**
