### PR TITLE
sql: rewrite cfetcher to be an explicit state machine

### PR DESCRIPTION
**Pull request by jordanlewis**
Based on #32120. Possible that it would be easier to just review this one on its own, since
the bugfixes in that PR got subsumed by this larger rewrite.

@danhhz, tagging you on the review for this as a general RowFetcher stakeholder if you're interested. This PR is modifying CFetcher, not Fetcher, which is only used by the columnar execution engine today, but PTAL because I'd like to eventually "backport" this state machine to the normal row fetcher as well. It's too bad that the two can't share a common codebase, but I tried that without any success.

CFetcher is now an explicit state machine with 7 states:

    stateInitFetch
    stateNoRow
    stateSeekPrefix
    stateHasRow
    stateDoneRow
    stateEmitLastBatch
    stateFinished

This state machine is more efficient than the original implementation,
because it allows expressing the flow of the fetcher in a significantly
more simple way.

The following optimizations were added as a natural result of the
conversion:

1. never decode index keys of non-0 column families
2. never decode index keys of interleaves we're not interested in, after
   the first one, by noting the next "interesting" prefix and skipping
   keys that don't match that prefix

A major future optimization that's now possible but not yet implemented:

1. record the common prefix of the just-fetched span of keys. Determine
   the *logical* common prefix: the prefix of complete encoded values in
   the common prefix. Then, we can fully decode that logical common
   prefix once, writing the decoded values into all following rows until
   the beginning of the next span. Then, new keys in that span don't
   have decode any of the logical common prefix - that part of decoding
   can be completely skipped.

These optimizations will significantly increase the performance of scans
over:

1. interleaved hierarchies
2. multi-column-family tables

and once the future optimization above is finished,

3. scans over tables with composite keys where the prefix of the
   composite key is oft-repeated.

The first commit improves the clarity of the kvFetcher interface:

1. rename the kvFetcher interface to kvBatchFetcher, since that's what
   it does now.
2. extract the common bits of functionality that de-batches the
   kvBatchFetcher's output into a concrete struct called kvFetcher, and
   embed that into row/fetcher and row/cfetcher.

Release note: None

### CODE REVIEW

**Comment by danhhz** [comment]
I only scanned the code; state machine idea sgtm

**Review by asubiotto — CHANGES_REQUESTED** [review]
Nice work. First commit LGTM with the assumption that it is all code movement/renaming.

My comments on the second commit are mostly nits. @solongordon, you might also want to take a look at this, I think it would be good to have a second pair of eyes.

It would be interesting to see some benchmark results as well if possible.

> Reviewed 10 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32201#-:-LR831pW9UlWrsg7XkWJ:bcqq24k)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/roachpb/data.go, line 580 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32201#-LR84-gc8L5uHovn3lvh:-LR84-gc8L5uHovn3lvi:bxs4vf7) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b0f19a6a142521739f5c0dac75bc6ad81cc854d/pkg/roachpb/data.go#L580)):*
> ```Go
> // tag is not DECIMAL an error will be returned.
> func (v Value) GetDecimalInto(d *apd.Decimal) error {
> 	if tag := v.GetTag(); tag != ValueType_DECIMAL {
> ```

Wondering if you can somehow share logic between this and `GetDecimal`.
___
*[pkg/sql/colencoding/key_encoding.go, line 308 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32201#-LR88b6S4OuD-Obszg3n:-LR88b6S4OuD-Obszg3o:bndsrcn) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b0f19a6a142521739f5c0dac75bc6ad81cc854d/pkg/sql/colencoding/key_encoding.go#L308)):*
> ```Go
> 			vec.Int64()[idx] = v
> 		default:
> 			return errors.Errorf("Invalid int width: %d", typ.Width)
> ```

nit: lowercase the error message
___
*[pkg/sql/row/cfetcher.go, line 92 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32201#-LR88q1o3RqNS6t00juz:-LR88q1o3RqNS6t00jv-:b-2l8acn) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b0f19a6a142521739f5c0dac75bc6ad81cc854d/pkg/sql/row/cfetcher.go#L92)):*
> ```Go
> 	extraTypes  []sqlbase.ColumnType
> 
> 	// -- Fields updated during a scan --
> ```

Can get rid of the comment
___
*[pkg/sql/row/cfetcher.go, line 166 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32201#-LR8DQyP6e47MYopjsfr:-LR8DQyP6e47MYopjsfs:bc8moei) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b0f19a6a142521739f5c0dac75bc6ad81cc854d/pkg/sql/row/cfetcher.go#L166)):*
> ```Go
> 		lastRowPrefix roachpb.Key
> 		// prettyValueBuf is a temp buffer used to create strings for tracing.
> 		prettyValueBuf *bytes.Buffer
> ```

Why is this a pointer?
___
*[pkg/sql/row/cfetcher.go, line 193 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32201#-LR8FMoNEHN-pAcLYwAG:-LR8FMoNEHN-pAcLYwAH:b2nv3qp) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b0f19a6a142521739f5c0dac75bc6ad81cc854d/pkg/sql/row/cfetcher.go#L193)):*
> ```Go
> 	// We must always decode the index key if we need to distinguish between
> 	// rows from more than one table.
> 	nTables := len(tables)
> ```

nit: I don't think `nTables` is used anywhere else so would remove these couple of lines and just have `if len(tables) > 1 { return error }`
___
*[pkg/sql/row/cfetcher.go, line 197 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32201#-LR8F1SY2VowafBdSiKB:-LR8F1SY2VowafBdSiKC:b-76lbxa) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b0f19a6a142521739f5c0dac75bc6ad81cc854d/pkg/sql/row/cfetcher.go#L197)):*
> ```Go
> 	rf.mustDecodeIndexKey = multipleTables
> 
> 	if multipleTables {
> ```

Seems like there's another `multipleTables` check below with a panic which can probably be removed?
___
*[pkg/sql/row/cfetcher.go, line 381 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32201#-LR8NVJn2prFtc2EhlKG:-LR8NVJn2prFtc2EhlKH:bm0iggu) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b0f19a6a142521739f5c0dac75bc6ad81cc854d/pkg/sql/row/cfetcher.go#L381)):*
> ```Go
> }
> 
> /*
> ```

Is this fine as a block comment? I feel like we rarely use these.
___
*[pkg/sql/row/cfetcher.go, line 387 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32201#-LR8R6Z6EbopqDqMAbO4:-LR8R6Z6EbopqDqMAbO5:bj9rjff) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b0f19a6a142521739f5c0dac75bc6ad81cc854d/pkg/sql/row/cfetcher.go#L387)):*
> ```Go
>   -> noRow
> 
> state: noRow
> ```

Wondering what you think of having these state names be more active. i.e. `s/noRow/decodeKV`, `s/hasRow/buildRow`, `s/doneRow/finalizeRow` or something like that. I feel like it makes the states more understandable.
___
*[pkg/sql/row/cfetcher.go, line 388 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32201#-LR8HVM08epRpYHajge8:-LR8HVM08epRpYHajge9:b-x10eyz) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b0f19a6a142521739f5c0dac75bc6ad81cc854d/pkg/sql/row/cfetcher.go#L388)):*
> ```Go
> 
> state: noRow
>   2. skip common prefix
> ```

nit: should start at 1
___
*[pkg/sql/row/cfetcher.go, line 461 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32201#-LR8STJ1003Xo1cugHnW:-LR8STJ1003Xo1cugHnX:bieksb1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b0f19a6a142521739f5c0dac75bc6ad81cc854d/pkg/sql/row/cfetcher.go#L461)):*
> ```Go
> 
> // Turn this on to enable super verbose logging of the fetcher state machine.
> const debugState = false
> ```

Should this be done with log verbosity instead?
___
*[pkg/sql/row/cfetcher.go, line 469 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32201#-LR8TQsq9O_s_izJq9kx:-LR8TQsq9O_s_izJq9ky:bb614s3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b0f19a6a142521739f5c0dac75bc6ad81cc854d/pkg/sql/row/cfetcher.go#L469)):*
> ```Go
> // ColBatch should not be modified and is only valid until the next call.
> // When there are no more rows, the ColBatch.Length is 0.
> // It also returns the table and index descriptor associated with the row
> ```

Outdated comment?
___
*[pkg/sql/row/cfetcher.go, line 471 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32201#-LR8U_yWEQgpe3qPkSFL:-LR8U_yWEQgpe3qPkSFM:bpsig4u) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b0f19a6a142521739f5c0dac75bc6ad81cc854d/pkg/sql/row/cfetcher.go#L471)):*
> ```Go
> // It also returns the table and index descriptor associated with the row
> // (relevant when more than one table is specified during initialization).
> func (rf *CFetcher) NextBatch(ctx context.Context) (exec.ColBatch, error) {
> ```

Have you considered extracting the separate states into methods? 
___
*[pkg/sql/row/cfetcher.go, line 568 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32201#-LR8Tzg5ElCqNIVsafFD:-LR8Tzg5ElCqNIVsafFE:b-167hqi) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b0f19a6a142521739f5c0dac75bc6ad81cc854d/pkg/sql/row/cfetcher.go#L568)):*
> ```Go
> 				if !moreRows {
> 					rf.machine.state[0] = stateEmitLastBatch
> 					continue STATEMACHINE
> ```

Could you get rid of the `STATEMACHINE` tag if you set the next `state[1] = stateEmitLastBatch` and `break`?
___
*[pkg/sql/row/cfetcher.go, line 667 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32201#-LR8UrmX7OVzpM8D3obi:-LR8UrmX7OVzpM8D3obj:b-7sh76l) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b0f19a6a142521739f5c0dac75bc6ad81cc854d/pkg/sql/row/cfetcher.go#L667)):*
> ```Go
> }
> 
> // processKV processes the given key/value, setting values in the row
> ```

The comment needs to be updated.
___
*[pkg/sql/row/cfetcher.go, line 808 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32201#-LR8V44k51jVlCCPd3hN:-LR8V44k51jVlCCPd3hO:b3kre) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b0f19a6a142521739f5c0dac75bc6ad81cc854d/pkg/sql/row/cfetcher.go#L808)):*
> ```Go
> 				return "", "", err
> 			}
> 			/*
> ```

?
___
*[pkg/sql/row/fetcher.go, line 92 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32201#-LR8VW5x-pjFPIc2-hbg:-LR8VW5y8RVFYXacmEIU:ba09f9k) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b0f19a6a142521739f5c0dac75bc6ad81cc854d/pkg/sql/row/fetcher.go#L92)):*
> ```Go
> 	// Fetcher is configured for. The index key prefix is the table id, index
> 	// id pair at the start of the key.
> 	knownPrefixLength int
> ```

Does this belong in the previous commit?
___
*[pkg/sql/sqlbase/index_encoding.go, line 419 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32201#-LR8WGRC8080VedSyniv:-LR8WGRC8080VedSyniw:bkzsluy) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b0f19a6a142521739f5c0dac75bc6ad81cc854d/pkg/sql/sqlbase/index_encoding.go#L419)):*
> ```Go
> 	// table.
> 	if _, ok := encoding.DecodeIfInterleavedSentinel(key); ok {
> 		return key, false, nil
> ```

Does this deserve an update to the function comment?

**Review by jordanlewis — COMMENTED** [review]
Thanks for the thorough review!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32201#-:-LSHtprlE5jET7kqNY1u:bst74u7)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/roachpb/data.go, line 580 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32201#-LR84-gc8L5uHovn3lvh:-LRQ-5WG9k4qHnGAKWFc:bz8gpn7) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b0f19a6a142521739f5c0dac75bc6ad81cc854d/pkg/roachpb/data.go#L580)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Wondering if you can somehow share logic between this and `GetDecimal`.
</blockquote></details>

The only way I see to do that it is to pull out a verify decimal tag function. But both will still have to call that function, which is 3 lines of code, same as this...
___
*[pkg/sql/row/cfetcher.go, line 92 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32201#-LR88q1o3RqNS6t00juz:-LRQ-gO44W59HgjNj55O:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b0f19a6a142521739f5c0dac75bc6ad81cc854d/pkg/sql/row/cfetcher.go#L92)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Can get rid of the comment
</blockquote></details>

Done.
___
*[pkg/sql/row/cfetcher.go, line 166 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32201#-LR8DQyP6e47MYopjsfr:-LRQ-kgJ8h2MAXJyUW_R:b-t9o1ta) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b0f19a6a142521739f5c0dac75bc6ad81cc854d/pkg/sql/row/cfetcher.go#L166)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why is this a pointer?
</blockquote></details>

It's used to avoid an allocation when tracing is off, same as the old code.
___
*[pkg/sql/row/cfetcher.go, line 193 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32201#-LR8FMoNEHN-pAcLYwAG:-LRQ-r4iCjSYeBgYsqHC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b0f19a6a142521739f5c0dac75bc6ad81cc854d/pkg/sql/row/cfetcher.go#L193)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: I don't think `nTables` is used anywhere else so would remove these couple of lines and just have `if len(tables) > 1 { return error }`
</blockquote></details>

Done.
___
*[pkg/sql/row/cfetcher.go, line 197 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32201#-LR8F1SY2VowafBdSiKB:-LRQ0GX84qEKfi-CngaR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b0f19a6a142521739f5c0dac75bc6ad81cc854d/pkg/sql/row/cfetcher.go#L197)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Seems like there's another `multipleTables` check below with a panic which can probably be removed?
</blockquote></details>

Done.
___
*[pkg/sql/row/cfetcher.go, line 381 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32201#-LR8NVJn2prFtc2EhlKG:-LSHtfTUBBW00eNJKc8N:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b0f19a6a142521739f5c0dac75bc6ad81cc854d/pkg/sql/row/cfetcher.go#L381)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Is this fine as a block comment? I feel like we rarely use these.
</blockquote></details>

Done.
___
*[pkg/sql/row/cfetcher.go, line 387 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32201#-LR8R6Z6EbopqDqMAbO4:-LSHolZz7RQRyk1stTli:bypkubv) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b0f19a6a142521739f5c0dac75bc6ad81cc854d/pkg/sql/row/cfetcher.go#L387)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Wondering what you think of having these state names be more active. i.e. `s/noRow/decodeKV`, `s/hasRow/buildRow`, `s/doneRow/finalizeRow` or something like that. I feel like it makes the states more understandable.
</blockquote></details>

Ok, I tried a new (verbose) naming scheme... let me know what you think :)
___
*[pkg/sql/row/cfetcher.go, line 461 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32201#-LR8STJ1003Xo1cugHnW:-LRQ0NVh-5t5wxulsRiE:b-qvu547) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b0f19a6a142521739f5c0dac75bc6ad81cc854d/pkg/sql/row/cfetcher.go#L461)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Should this be done with log verbosity instead?
</blockquote></details>

This is just for debugging - it gets compiled out if it's false, but useful to keep around for now as we're still developing. It's too expensive to check a log verbosity so many times during decode. the old rowfetcher has a similar pattern. 
___
*[pkg/sql/row/cfetcher.go, line 469 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32201#-LR8TQsq9O_s_izJq9kx:-LSHp2U-7gWMJWgWTNKF:bnma67e) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b0f19a6a142521739f5c0dac75bc6ad81cc854d/pkg/sql/row/cfetcher.go#L469)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Outdated comment?
</blockquote></details>

Thanks, Done.
___
*[pkg/sql/row/cfetcher.go, line 471 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32201#-LR8U_yWEQgpe3qPkSFL:-LSHp3zC9QU3-OFRXhns:bca6up5) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b0f19a6a142521739f5c0dac75bc6ad81cc854d/pkg/sql/row/cfetcher.go#L471)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Have you considered extracting the separate states into methods? 
</blockquote></details>

I could... but paradoxically I feel that having all of the states be inlined makes the code easier to read, because all of the context for each of the states is very close by.... Maybe I'm wrong though, what do you think?
___
*[pkg/sql/row/cfetcher.go, line 568 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32201#-LR8Tzg5ElCqNIVsafFD:-LSHpOdE7WQyB-E0bq_q:b-4k0685) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b0f19a6a142521739f5c0dac75bc6ad81cc854d/pkg/sql/row/cfetcher.go#L568)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Could you get rid of the `STATEMACHINE` tag if you set the next `state[1] = stateEmitLastBatch` and `break`?
</blockquote></details>

Good point! Done.
___
*[pkg/sql/row/cfetcher.go, line 667 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32201#-LR8UrmX7OVzpM8D3obi:-LSHqBMR1LMbIPDY1OFv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b0f19a6a142521739f5c0dac75bc6ad81cc854d/pkg/sql/row/cfetcher.go#L667)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

The comment needs to be updated.
</blockquote></details>

Done.
___
*[pkg/sql/row/cfetcher.go, line 808 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32201#-LR8V44k51jVlCCPd3hN:-LSHqh5oAuJZoTdcVg0q:b-ohni02) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b0f19a6a142521739f5c0dac75bc6ad81cc854d/pkg/sql/row/cfetcher.go#L808)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

?
</blockquote></details>

Done. We'll need to add a templated prettyprint function to handle all of these similar cases. It'll come later.
___
*[pkg/sql/row/fetcher.go, line 92 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32201#-LR8VW5x-pjFPIc2-hbg:-LSHs8ZDEljBvI9cQmbi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b0f19a6a142521739f5c0dac75bc6ad81cc854d/pkg/sql/row/fetcher.go#L92)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Does this belong in the previous commit?
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/index_encoding.go, line 419 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32201#-LR8WGRC8080VedSyniv:-LSHr3jK56dI-SgR7ISp:bdqkscx) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b0f19a6a142521739f5c0dac75bc6ad81cc854d/pkg/sql/sqlbase/index_encoding.go#L419)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Does this deserve an update to the function comment?
</blockquote></details>

Oops, I this was an aborted experiment that goes along with the TODO to parse the logical longest common prefix. Thanks for catching, I deleted it.

**Comment by asubiotto** [comment]
Will take a look at this today.

**Comment by jordanlewis** [comment]
I forgot also that I was leery of using util/fsm due to its heavy use of maps. The fetcher state machine makes many more transitions than the conn_executor, the main user of util/fsm. I would like to avoid multiple map lookups per row.

**Review by asubiotto — APPROVED** [review]
> Reviewed 2 of 8 files at r1, 11 of 11 files at r3, 11 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32201)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/row/cfetcher.go, line 166 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32201#-LR8DQyP6e47MYopjsfr:-LSuHXIZ-YTnHp3AL_PO:b3ap1os) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b0f19a6a142521739f5c0dac75bc6ad81cc854d/pkg/sql/row/cfetcher.go#L166)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

It's used to avoid an allocation when tracing is off, same as the old code.
</blockquote></details>

Nice. Maybe comment?
___
*[pkg/sql/row/cfetcher.go, line 387 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32201#-LR8R6Z6EbopqDqMAbO4:-LSuKB8T-J5UL_0yubiD:b-gsrnja) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b0f19a6a142521739f5c0dac75bc6ad81cc854d/pkg/sql/row/cfetcher.go#L387)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Ok, I tried a new (verbose) naming scheme... let me know what you think :)
</blockquote></details>

Looks good! Seems like the big state machine comment is slightly out of sync now though

**Comment by nvanbenschoten** [comment]
> the state machine change is in a different PR - #32201. I took a brief look at using the util/fsm library but found its abstraction to be too heavyweight for my needs. I didn't know how to decompose the machine into events - the events in the fetcher are conditions that don't quite feel like they fit the event model. But perhaps I just wasn't looking at things in the right way... what do you think?

`util/fsm` isn't all that heavyweight - you don't need to use the `EventPayload` or `ExtendedState` if you don't need to. I think the process of decompose the machine into events is actually extremely useful, even if you don't end up using `util/fsm`. The benfit of finite state machines is that they operate on a finite set of states and events. Making both aspects explicit makes the entire system easier to reason about.

> I forgot also that I was leery of using util/fsm due to its heavy use of maps. The fetcher state machine makes many more transitions than the conn_executor, the main user of util/fsm. I would like to avoid multiple map lookups per row.

I think this is the biggest reason not to use `util/fsm`. Each state transition equates to a map lookup, which is `O(100 ns)`. It you're making a large number of state transitions (which I think you will be here) then this may become too costly.

**Comment by jordanlewis** [comment]
TFTRs!

bors r+

**Pull request merged**
