### PR TITLE
sql: remove the interleaved logic from fetchers

### PR DESCRIPTION
**Pull request by yuzefovich**
**row: simplify fetcher to only handle a single table**

Previously, `row.Fetcher` could handle multiple tables at the same time.
This was needed to support the interleaved tables efficiently, but since
the interleaved tables are no more, we can simplify the fetcher now.

There are more things that can be removed from the fetcher about
handling of the interleaved tables, but I chose to defer them to a later
commit. This commit's main focus is simplifying the fetcher to work
under the assumption that it will be fetching only from a single table.

Addresses: #69150

Release note: None

**colbuilder: remove the check for index join on the interleaved index**

Interleaved indexes are no more.

Release note: None

**sql: remove the interleaved logic from fetchers**

This commit removes the remaining bits of handling the interleaved
tables from both row fetcher and cFetcher. It also removes a test that
verifies that we can read from the interleaved table restored from
a backup.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Will hold off on merging this until 21.2.0 is out.

**Review by michae2 — CHANGES_REQUESTED** [review]
The best type of PR. :slightly_smiling_face:

Searching for "interleave" in `fetcher.go` turned up a few more spots. Not sure how comprehensive you're trying to make this... if I'm asking too much just skip them.

> Reviewed 6 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70239#-:-Mjfrh0h5i1Hs6KjMVcJ:bs21ex5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/row/fetcher.go, line 147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70239#-Mjfl5ek3StvWD_OfSTq:-Mjfl5ek3StvWD_OfSTr:boocmbv) ([raw file](https://github.com/cockroachdb/cockroach/blob/72ad1e95d1acc3c7bbd2c9e12f6fdc38e446e207/pkg/sql/row/fetcher.go#L147)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> 	// The spans of keys to return for the given table. Fetcher
> 	// ignores keys outside these spans.
> 	// This is irrelevant if Fetcher is initialize with only one
> 	// table.
> 	Spans            roachpb.Spans
> ```
</details>


Should this also be deleted? (Or the comment changed?)
___
*[pkg/sql/row/fetcher.go, line 188 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70239#-MjflLdT5stcn5jDAH0g:-MjflLdT5stcn5jDAH0h:b-wcb573) ([raw file](https://github.com/cockroachdb/cockroach/blob/72ad1e95d1acc3c7bbd2c9e12f6fdc38e446e207/pkg/sql/row/fetcher.go#L188)):*
> ```
> // Fetcher handles fetching kvs and forming table rows for an
> // arbitrary number of tables.
> ```

nit: Should this now say "a single table"?
___
*[pkg/sql/row/fetcher.go, line 222 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70239#-MjfqVK--RutNae3Odws:-MjfqVK--RutNae3Odwt:b-izuizm) ([raw file](https://github.com/cockroachdb/cockroach/blob/72ad1e95d1acc3c7bbd2c9e12f6fdc38e446e207/pkg/sql/row/fetcher.go#L222)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> 	// True if the index key must be decoded.
> 	// If there is more than one table, the index key must always be decoded.
> 	// This is only false if there are no needed columns and the (single)
> 	// table has no interleave children.
> 	mustDecodeIndexKey bool
> ```
</details>


Is this still necessary?
___
*[pkg/sql/row/fetcher.go, line 414 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70239#-MjfoSkp9xjaDnI_pWmX:-MjfoSkp9xjaDnI_pWmY:brf5rwh) ([raw file](https://github.com/cockroachdb/cockroach/blob/72ad1e95d1acc3c7bbd2c9e12f6fdc38e446e207/pkg/sql/row/fetcher.go#L414)):*
<details><summary><i alt="summary">Quoted 10 lines of code…</i></summary>

> ```
> 	// - If there is more than one table, we have to decode the index key to
> 	//   figure out which table the row belongs to.
> 	// - If there are interleaves, we need to read the index key in order to
> 	//   determine whether this row is actually part of the index we're scanning.
> 	// - If there are needed columns from the index key, we need to read it.
> 	//
> 	// Otherwise, we can completely avoid decoding the index key.
> 	if !rf.mustDecodeIndexKey && (neededIndexCols > 0 || table.index.NumInterleavedBy() > 0 || table.index.NumInterleaveAncestors() > 0) {
> 		rf.mustDecodeIndexKey = true
> 	}
> ```
</details>


I think some of this can also be deleted.
___
*[pkg/sql/row/fetcher.go, line 713 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70239#-MjfqiMg0h7MtNVHub0G:-MjfqiMg0h7MtNVHub0H:b-mslw0p) ([raw file](https://github.com/cockroachdb/cockroach/blob/72ad1e95d1acc3c7bbd2c9e12f6fdc38e446e207/pkg/sql/row/fetcher.go#L713)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> 			if _, foundSentinel := encoding.DecodeIfInterleavedSentinel(keySuffix); foundSentinel {
> 				// We found an interleaved sentinel, which means that the key we just
> 				// found belongs to a different interleave. That means we have to go
> 				// through with index key decoding.
> 				unchangedPrefix = false
> ```
</details>


Should some of this also be deleted?
___
*[pkg/sql/row/fetcher.go, line 731 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70239#-MjfqpqL3WRosyh_wk-I:-MjfqpqL3WRosyh_wk-J:b-kd3yhz) ([raw file](https://github.com/cockroachdb/cockroach/blob/72ad1e95d1acc3c7bbd2c9e12f6fdc38e446e207/pkg/sql/row/fetcher.go#L731)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> 			if !moreKVs {
> 				// The key did not match any of the table
> 				// descriptors, which means it's interleaved
> 				// data from some other table or index.
> 				continue
> 			}
> ```
</details>


Can this be deleted?
___
*[pkg/sql/row/fetcher.go, line 1562 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70239#-Mjfr2xz3ia87j68Ip0U:-Mjfr2y-99rRQAZVV58t:b-kseo3h) ([raw file](https://github.com/cockroachdb/cockroach/blob/72ad1e95d1acc3c7bbd2c9e12f6fdc38e446e207/pkg/sql/row/fetcher.go#L1562)):*
<details><summary><i alt="summary">Quoted 41 lines of code…</i></summary>

> ```
> 	for i := 0; i < index.NumInterleaveAncestors(); i++ {
> 		ancestor := index.GetInterleaveAncestor(i)
> 		length := int(ancestor.SharedPrefixLen)
> 		// Skip up to length values.
> 		for j := 0; j < length; j++ {
> 			if consumedCols == nCols {
> 				// We're done early, in the middle of an interleave.
> 				return origKeyLen - len(key), nil
> 			}
> 			l, err := encoding.PeekLength(key)
> 			if err != nil {
> 				return 0, err
> 			}
> 			key = key[l:]
> 			consumedCols++
> 		}
> 		var ok bool
> 		key, ok = encoding.DecodeIfInterleavedSentinel(key)
> 		if !ok {
> 			return 0, errors.New("unexpected lack of sentinel key")
> 		}
> 		// Skip the TableID/IndexID pair for each ancestor except for the
> 		// first, which has already been skipped in our input.
> 		for j := 0; j < 2; j++ {
> 			idLen, err := encoding.PeekLength(key)
> 			if err != nil {
> 				return 0, err
> 			}
> 			key = key[idLen:]
> 		}
> 	}
> 	// Decode the remaining values in the key, in the final interleave.
> 	for ; consumedCols < nCols; consumedCols++ {
> 		l, err := encoding.PeekLength(key)
> 		if err != nil {
> 			return 0, err
> 		}
> 		key = key[l:]
> 	}
> 	return origKeyLen - len(key), nil
> }
> ```
</details>


Some of this can probably change.

**Review by yuzefovich — COMMENTED** [review]
Oh yes, it's quite a pleasant exercise :)

Thanks for the review! I consciously deferred the removal of some other interleaved business from these files to make this commit simpler and serve the goal of making fetcher work only on one table. Updated the commit message to include this context.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70239#-:-Mjg-dGjAgx9__UpxU6H:b5x2yr5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2)

___
*[pkg/sql/row/fetcher.go, line 147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70239#-Mjfl5ek3StvWD_OfSTq:-Mjg0gK_-zeFI_6G5kWx:bs2vhuc) ([raw file](https://github.com/cockroachdb/cockroach/blob/72ad1e95d1acc3c7bbd2c9e12f6fdc38e446e207/pkg/sql/row/fetcher.go#L147)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

> ```
> 	// The spans of keys to return for the given table. Fetcher
> 	// ignores keys outside these spans.
> 	// This is irrelevant if Fetcher is initialize with only one
> 	// table.
> 	Spans            roachpb.Spans
> ```

Should this also be deleted? (Or the comment changed?)
</blockquote></details>

Good point, removed.
___
*[pkg/sql/row/fetcher.go, line 222 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70239#-MjfqVK--RutNae3Odws:-Mjg0siL1s_GVAMkuhyC:b-sdhrkh) ([raw file](https://github.com/cockroachdb/cockroach/blob/72ad1e95d1acc3c7bbd2c9e12f6fdc38e446e207/pkg/sql/row/fetcher.go#L222)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

> ```
> 	// True if the index key must be decoded.
> 	// If there is more than one table, the index key must always be decoded.
> 	// This is only false if there are no needed columns and the (single)
> 	// table has no interleave children.
> 	mustDecodeIndexKey bool
> ```

Is this still necessary?
</blockquote></details>

It needs to be adjusted, and I deferred this spot for #70235.
___
*[pkg/sql/row/fetcher.go, line 414 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70239#-MjfoSkp9xjaDnI_pWmX:-Mjg13az6GPlAPMOAi6a:b-gcn87z) ([raw file](https://github.com/cockroachdb/cockroach/blob/72ad1e95d1acc3c7bbd2c9e12f6fdc38e446e207/pkg/sql/row/fetcher.go#L414)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

> ```
> 	// - If there is more than one table, we have to decode the index key to
> 	//   figure out which table the row belongs to.
> 	// - If there are interleaves, we need to read the index key in order to
> 	//   determine whether this row is actually part of the index we're scanning.
> 	// - If there are needed columns from the index key, we need to read it.
> 	//
> 	// Otherwise, we can completely avoid decoding the index key.
> 	if !rf.mustDecodeIndexKey && (neededIndexCols > 0 || table.index.NumInterleavedBy() > 0 || table.index.NumInterleaveAncestors() > 0) {
> 		rf.mustDecodeIndexKey = true
> 	}
> ```

I think some of this can also be deleted.
</blockquote></details>

True, but I decided to defer this to #70235.
___
*[pkg/sql/row/fetcher.go, line 713 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70239#-MjfqiMg0h7MtNVHub0G:-Mjg19w21D4kLekq84iW:b-89a4l7) ([raw file](https://github.com/cockroachdb/cockroach/blob/72ad1e95d1acc3c7bbd2c9e12f6fdc38e446e207/pkg/sql/row/fetcher.go#L713)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

> ```
> 			if _, foundSentinel := encoding.DecodeIfInterleavedSentinel(keySuffix); foundSentinel {
> 				// We found an interleaved sentinel, which means that the key we just
> 				// found belongs to a different interleave. That means we have to go
> 				// through with index key decoding.
> 				unchangedPrefix = false
> ```

Should some of this also be deleted?
</blockquote></details>

Ditto
___
*[pkg/sql/row/fetcher.go, line 731 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70239#-MjfqpqL3WRosyh_wk-I:-Mjg1BbO0k4z-qYEWuLT:b-89a4l7) ([raw file](https://github.com/cockroachdb/cockroach/blob/72ad1e95d1acc3c7bbd2c9e12f6fdc38e446e207/pkg/sql/row/fetcher.go#L731)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

> ```
> 			if !moreKVs {
> 				// The key did not match any of the table
> 				// descriptors, which means it's interleaved
> 				// data from some other table or index.
> 				continue
> 			}
> ```

Can this be deleted?
</blockquote></details>

Ditto
___
*[pkg/sql/row/fetcher.go, line 1562 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70239#-Mjfr2xz3ia87j68Ip0U:-Mjg1DQB5zHIcY7z2lDq:bs4q9op) ([raw file](https://github.com/cockroachdb/cockroach/blob/72ad1e95d1acc3c7bbd2c9e12f6fdc38e446e207/pkg/sql/row/fetcher.go#L1562)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

> ```
> 	for i := 0; i < index.NumInterleaveAncestors(); i++ {
> 		ancestor := index.GetInterleaveAncestor(i)
> 		length := int(ancestor.SharedPrefixLen)
> 		// Skip up to length values.
> 		for j := 0; j < length; j++ {
> 			if consumedCols == nCols {
> 				// We're done early, in the middle of an interleave.
> 				return origKeyLen - len(key), nil
> 			}
> 			l, err := encoding.PeekLength(key)
> 			if err != nil {
> 				return 0, err
> 			}
> 			key = key[l:]
> 			consumedCols++
> 		}
> 		var ok bool
> 		key, ok = encoding.DecodeIfInterleavedSentinel(key)
> 		if !ok {
> 			return 0, errors.New("unexpected lack of sentinel key")
> 		}
> 		// Skip the TableID/IndexID pair for each ancestor except for the
> 		// first, which has already been skipped in our input.
> 		for j := 0; j < 2; j++ {
> 			idLen, err := encoding.PeekLength(key)
> 			if err != nil {
> 				return 0, err
> 			}
> 			key = key[idLen:]
> 		}
> 	}
> 	// Decode the remaining values in the key, in the final interleave.
> 	for ; consumedCols < nCols; consumedCols++ {
> 		l, err := encoding.PeekLength(key)
> 		if err != nil {
> 			return 0, err
> 		}
> 		key = key[l:]
> 	}
> 	return origKeyLen - len(key), nil
> }
> ```

Some of this can probably change.
</blockquote></details>

Ditto.

**Comment by yuzefovich** [comment]
Decided to include two more commits that are related to the fetchers simplification into this PR, and I think all spots mentioned by Michael should now be addressed.

**Comment by yuzefovich** [comment]
Rebased on top of the latest master.

**Review by michae2 — APPROVED** [review]
Really nice! :lgtm:

> Reviewed 6 of 7 files at r2, 11 of 11 files at r5, 3 of 3 files at r6, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70239#-:-MkE5urI40B4bJtOERZH:bdlfvfc)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/row/fetcher.go, line 1153 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/70239#-MkE6R4r-ReQGoTqI9co:-MkE6R4r-ReQGoTqI9cp:bjmicdi) ([raw file](https://github.com/cockroachdb/cockroach/blob/84d330199584116b086dbea5f335bcd651b68631/pkg/sql/row/fetcher.go#L1153)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> // It also returns the table and index descriptor associated with the row
> // (relevant when more than one table is specified during initialization).
> func (rf *Fetcher) NextRow(
> 	ctx context.Context,
> ) (row rowenc.EncDatumRow, table catalog.TableDescriptor, index catalog.Index, err error) {
> ```
</details>


One day (future PR) we could probably get rid of the `table` return value.

**Comment by yuzefovich** [comment]
@dt could you please take a look at the first commit?

**Comment by yuzefovich** [comment]
> it looks like this is deleting the interleaved backup from testdata and then removing the only call to `restoreOldVersionTestWithInterleave` which asserts that we get the rejection error? or am I misreading it?

Yes, that's currently the case.

With the removal of all interleaved tables logic from the fetchers, we are now hitting an internal error when attempting to restore a backup with an interleaved table. Is that acceptable? I guess a more user-friendly thing to do would be to convert that error to rejecting the backup.

**Comment by yuzefovich** [comment]
I misunderstood things, sorry for the noise - we only want to remove the test that actually attempts to read from the interleaved table.

**Pull request merged**
