### PR TITLE
cli: render select results with no columns

### LINKED ISSUE #13769: cli: results with no columns are rendered incorrectly
Our CLI renders results of a select with no columns by just printing `OK`, which doesn't make too much sense.

Us:
```
root@:26257/jordan> SELECT * FROM empty;
OK
```
psql:
```
$ psql -p 26257 -h localhost
psql (9.6.2, server 9.5.0)
Type "help" for help.

jordan=> select * from empty;
--
(0 rows)
```

Found after fixing #13725.

### PR DESCRIPTION
**Pull request by sethpollack**
Fixes #13769

### CODE REVIEW

**Comment by tamird** [comment]
Looks like this causes many tests to fail.

**Comment by sethpollack** [comment]
I see, tests passed locally but I may have been running them wrong.

**Comment by tamird** [comment]
How did you run them?

**Comment by sethpollack** [comment]
I can only get the Makefile working with `sudo`.

**Comment by sethpollack** [comment]
I think they passed just using `go test`

**Comment by tamird** [comment]
`go test` only tests the top level package. You need to run `go test ./...` to run the full test suite.

**Comment by dt** [comment]
To clarify, `go test ./pkg/...` (though you likely need to up the timeout too) -- `./...` will go in to /vendor, which you probably don't want.

**Comment by sethpollack** [comment]
Ok, so I took a look at this again. The tag is missing, which I think is related to this https://github.com/lib/pq/blob/master/conn.go#L656

When I change the code to `len(res.colNames) == 0` instead of `res.colNames == nil ` it fixes the issue and the tests pass.

Before I make a PR to `pq` can you let me know if i'm on the right track with this?  And if this commit is too hacky? https://github.com/cockroachdb/cockroach/pull/14973/commits/0db0b20d20f015673bee353dbedce792909c92bf

**Comment by tamird** [comment]
re-assigning @mjibson who might be able to answer the `lib/pq` questions.

**Comment by mjibson** [comment]
I don't think it's safe to use the tag because `INSERT ... RETURNING` and others can return rows when the tag is not SELECT. I'm not sure off the top of my head of the correct way to fix this bug.

**Comment by knz** [comment]
Hi @sethpollack I had a look at this and it turned out that the solution was somewhat more involved than what you had imagined. Check it out in #17816. Do you reckon there is anything to add?

**Comment by sethpollack** [comment]
@knz  Looks good. I'll close this PR

**Pull request closed without merging**
