### PR TITLE
storageccl: improved tracing of RESTORE

### PR DESCRIPTION
**Pull request by tbg**

### CODE REVIEW

**Comment by benesch** [comment]
:tada:

How urgent is this PR? I think we'll want @danhhz to review as well, if it's not too much of a hassle to wait for him to get back.

**Comment by tschottdorf** [comment]
I don't want to wait for @danhhz as we have to have this in good shape for the all-hands on the 12th.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16913#-:-KoOfON8AcN4gW6w8jtF:blcfqfl)*

**Comment by benesch** [comment]
Fair enough! I'll review tonight, in that case.

**Comment by benesch** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/sqlccl/restore.go, line 747 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16913#-KoOoYyxnOA3-HyDrMLb:-KoOoYyxnOA3-HyDrMLc:b-uxmecs) ([raw file](https://github.com/cockroachdb/cockroach/blob/0de466b9b33fb439e534c7999a1bd9730bc6c645/pkg/ccl/sqlccl/restore.go#L747)):*
> ```Go
> 			span := newSpans[i]
> 			g.Go(func() error {
> 				scatterCtx, sp := tracing.ChildSpan(gCtx, "scatter")
> ```

To me, the casual observer, it seems like you'd want one scatter span per restore, not one per table in restore? I'm not the one looking at the traces, of course.

---

*[pkg/ccl/sqlccl/restore.go, line 790 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16913#-KoOojK9Y7kju5pkzFZ4:-KoOojK9Y7kju5pkzFZ5:bdymv8f) ([raw file](https://github.com/cockroachdb/cockroach/blob/0de466b9b33fb439e534c7999a1bd9730bc6c645/pkg/ccl/sqlccl/restore.go#L790)):*
> ```Go
> 	importsSem := make(chan struct{}, maxConcurrentImports)
> 
> 	log.Eventf(ctx, "commencing import of data with at concurrency %d", maxConcurrentImports)
> ```

"with at concurrency"

---

*[pkg/ccl/sqlccl/restore.go, line 860 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16913#-KoOpDtg7j9dIvKdwu_Q:-KoOpDtg7j9dIvKdwu_R:b6q2lje) ([raw file](https://github.com/cockroachdb/cockroach/blob/0de466b9b33fb439e534c7999a1bd9730bc6c645/pkg/ccl/sqlccl/restore.go#L860)):*
> ```Go
> 	log.Eventf(ctx, "restore completed: ingested %s of data (before replication) at %s/sec",
> 		humanizeutil.IBytes(mu.res.DataSize), humanizeutil.IBytes(mu.res.DataSize/int64(1+timeutil.Since(tBegin).Seconds())),
> 	)
> ```

nit: this line is 118 chars. I'd advocate for one more line break:

```
// Don't need the lock any more; we're the only moving part at this stage.
log.Eventf(ctx, "restore completed: ingested %s of data (before replication) at %s/sec",
  humanizeutil.IBytes(mu.res.DataSize),
  humanizeutil.IBytes(mu.res.DataSize/int64(1+timeutil.Since(tBegin).Seconds())),
)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16913#-:-KoOpw7QeXkWvdegvcBN:bnfp4nl)*

**Comment by tschottdorf** [comment]
TFTR!

---

Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/ccl/sqlccl/restore.go, line 747 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16913#-KoOoYyxnOA3-HyDrMLb:-KoOrQ-Zmf0pdZTVBO-q:b8p7em9) ([raw file](https://github.com/cockroachdb/cockroach/blob/0de466b9b33fb439e534c7999a1bd9730bc6c645/pkg/ccl/sqlccl/restore.go#L747)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

To me, the casual observer, it seems like you'd want one scatter span per restore, not one per table in restore? I'm not the one looking at the traces, of course.
</blockquote></details>

I think you want one per goroutine here -- imagine what the alternative would look like: you're scattering, say, 5 tables at the same time, but all the messages interleave and in particular if one of the scatters has problems, you semi-manually have to pick out what belongs to which. That said, the traces for RESTORE end up with a lot of spans, but the scatter one's aren't the problem. It's more the gazillion of individual RPCs we send below. Really blows up lightstep, looks like they have a hard cap of 2000 spans/trace and once you're above that, it puts things in places they don't belong.

---

*[pkg/ccl/sqlccl/restore.go, line 790 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16913#-KoOojK9Y7kju5pkzFZ4:-KoOsTuhwurKKV3oUl-p:bmpsbo1) ([raw file](https://github.com/cockroachdb/cockroach/blob/0de466b9b33fb439e534c7999a1bd9730bc6c645/pkg/ccl/sqlccl/restore.go#L790)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

"with at concurrency"
</blockquote></details>

Oops, done :)

---

*[pkg/ccl/sqlccl/restore.go, line 860 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16913#-KoOpDtg7j9dIvKdwu_Q:-KoOsZgaEAm7nvg6fuwL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0de466b9b33fb439e534c7999a1bd9730bc6c645/pkg/ccl/sqlccl/restore.go#L860)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

nit: this line is 118 chars. I'd advocate for one more line break:

```
// Don't need the lock any more; we're the only moving part at this stage.
log.Eventf(ctx, "restore completed: ingested %s of data (before replication) at %s/sec",
  humanizeutil.IBytes(mu.res.DataSize),
  humanizeutil.IBytes(mu.res.DataSize/int64(1+timeutil.Since(tBegin).Seconds())),
)
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16913#-:-KoOtQUF-2JqKxoS4wHa:b-814g8k)*

**Comment by benesch** [comment]
Gotcha, your reasoning for one-per table SGTM!

**Pull request merged**
