### PR TITLE
storage: hold raftMu when requiring Raft-consistent snapshot

### PR DESCRIPTION
**Pull request by tbg**
I went through the other call sites and none need it. Open to ideas
for not getting it wrong in future code changes, but it does not seem
particularly urgent.

See #16263.

### CODE REVIEW

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17088#-:-KpMRq1yXV3zA5WPglpC:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/replica_raftstorage.go, line 379 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17088#-KpMTTcob-1l4A6-JBDq:-KpMTTcob-1l4A6-JBDr:b-95wexx) ([raw file](https://github.com/cockroachdb/cockroach/blob/2de1e247cf2927c5f624529a41837326d1e872d9/pkg/storage/replica_raftstorage.go#L379)):*
> ```Go
> 			"%s: not generating %s snapshot because replica is too large: %d > 2 * %d",
> 			r, snapType, size, maxBytes)
> 		return &OutgoingSnapshot{}, err
> ```

You need to close the snapshot on this code path.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17088)*

**Comment by tschottdorf** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/replica_raftstorage.go, line 379 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17088#-KpMTTcob-1l4A6-JBDq:-KpMZ350ykWy5IJ_lk-l:b5hnuij) ([raw file](https://github.com/cockroachdb/cockroach/blob/2de1e247cf2927c5f624529a41837326d1e872d9/pkg/storage/replica_raftstorage.go#L379)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

You need to close the snapshot on this code path.
</blockquote></details>

Oops, good catch. I think the other error return had the same problem -- should be more bullet-proof now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17088)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17088#-:-KpMajPFYetynBLakzSd:bnfp4nl)*

**Pull request merged**
