### PR TITLE
sql: Add information_schema.schemata table

### PR DESCRIPTION
**Pull request by nvb**
This table provides information about databases.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8433)

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Ping.

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[sql/database.go, line 199 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8433#-KPJOUn7rGZ1goGpjF_V:-KPJOUn88jN1OszEQWOl:b-48vo0k) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6a880a9b7964f06be0adc075c4479ea7289da64/sql/database.go#L199)):*
> ```Go
> 	}
> 
> 	var dbDescs []*sqlbase.DatabaseDescriptor
> ```

pre-allocate

---

*[sql/descriptor.go, line 235 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8433#-KPJOaCA-Dno05v9_KvR:-KPJOaCA-Dno05v9_KvS:bospgat) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6a880a9b7964f06be0adc075c4479ea7289da64/sql/descriptor.go#L235)):*
> ```Go
> 	}
> 
> 	descs := make([]sqlbase.DescriptorProto, 0, len(kvs))
> ```

nit: avoid append while you're here

---

*[sql/information_schema.go, line 195 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8433#-KPJP-kJoW92VqOE7TaG:-KPJP-kJoW92VqOE7TaH:b-vsq7jp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6a880a9b7964f06be0adc075c4479ea7289da64/sql/information_schema.go#L195)):*
> ```Go
> type sortedDBDescs []*sqlbase.DatabaseDescriptor
> 
> // sortedDBDescs implements sort.Interface.
> ```

should probably indicate somehow that the sorting is by name (rather than ID, for instance)

---

*[sql/information_schema.go, line 207 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8433#-KPJP3URx-_AlcYhK--g:-KPJP3URx-_AlcYhK--h:baeyfir) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6a880a9b7964f06be0adc075c4479ea7289da64/sql/information_schema.go#L207)):*
> ```Go
> 	fn func(*sqlbase.DatabaseDescriptor),
> ) error {
> 	var dbDescs []*sqlbase.DatabaseDescriptor
> ```

pre-allocate?

---

*[sql/information_schema.go, line 214 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8433#-KPJP8FDA9ySiJLEncN5:-KPJP8FDA9ySiJLEncN6:b-5v84lp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6a880a9b7964f06be0adc075c4479ea7289da64/sql/information_schema.go#L214)):*
> ```Go
> 	}
> 
> 	// Handle real schemas
> ```

do this first, since it can error (and you'll also be able to save some allocs)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8433#-:-KPJPJ__u7MsaBGjhTX7:bnfp4nl)*

**Comment by tamird** [comment]
This should go to `develop` rather than `master`. You can change that without opening a new PR.

**Comment by nvanbenschoten** [comment]
TFTR.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[sql/database.go, line 199 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8433#-KPJOUn7rGZ1goGpjF_V:-KPJroCBI9HyGJJhaBuS:b-wkzsnc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6a880a9b7964f06be0adc075c4479ea7289da64/sql/database.go#L199)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> pre-allocate
</details>
Most descriptors wont be `DatabaseDescriptor`s, so it would be a large over-allocation.

---

*[sql/descriptor.go, line 235 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8433#-KPJOaCA-Dno05v9_KvR:-KPJs1Yxvw7jChXSfbQw:b84k0jf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6a880a9b7964f06be0adc075c4479ea7289da64/sql/descriptor.go#L235)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit: avoid append while you're here
</details>
Why avoid append? Do you mean index into the slice instead of appending?

---

*[sql/information_schema.go, line 195 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8433#-KPJP-kJoW92VqOE7TaG:-KPJsUm_0j7Mydi11y7x:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6a880a9b7964f06be0adc075c4479ea7289da64/sql/information_schema.go#L195)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> should probably indicate somehow that the sorting is by name (rather than ID, for instance)
</details>
Done.

---

*[sql/information_schema.go, line 207 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8433#-KPJP3URx-_AlcYhK--g:-KPJsmqwE0zaDA5FJFzx:b8ub356) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6a880a9b7964f06be0adc075c4479ea7289da64/sql/information_schema.go#L207)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> pre-allocate?
</details>
Not needed after your other suggestion.

---

*[sql/information_schema.go, line 214 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8433#-KPJP8FDA9ySiJLEncN5:-KPJsgB0RFqHGUCVuYJ6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6a880a9b7964f06be0adc075c4479ea7289da64/sql/information_schema.go#L214)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> do this first, since it can error (and you'll also be able to save some allocs)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8433#-:-KPJspGSNDGT9nKq2rDO:b-814g87)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/descriptor.go, line 235 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8433#-KPJOaCA-Dno05v9_KvR:-KPJy5bxLFMBmvDPlwYV:b-dwqzh8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6a880a9b7964f06be0adc075c4479ea7289da64/sql/descriptor.go#L235)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Why avoid append? Do you mean index into the slice instead of appending?
</details>
Yeah, since append is known to be slower. Not that perf here matters, but there's no reason not to be deliberate.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8433)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/descriptor.go, line 235 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8433#-KPJOaCA-Dno05v9_KvR:-KPJzdfrg_2E8Sc0oR4i:b-if2clz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6a880a9b7964f06be0adc075c4479ea7289da64/sql/descriptor.go#L235)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Yeah, since append is known to be slower. Not that perf here matters, but there's no reason not to be deliberate.
</details>
Do you have sources for that? I've benchmarked them before and saw exactly the same results.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8433)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/descriptor.go, line 235 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8433#-KPJOaCA-Dno05v9_KvR:-KPJzyHh1ZB2leCSXUTp:bafo995) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6a880a9b7964f06be0adc075c4479ea7289da64/sql/descriptor.go#L235)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Do you have sources for that? I've benchmarked them before and saw exactly the same results.
</details>
You were my source for that - didn't you file an issue upstream about this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8433)*

**Comment by paperstreet** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/descriptor.go, line 235 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8433#-KPJOaCA-Dno05v9_KvR:-KPK-L3jIhIv4XILoFM9:b91zm2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6a880a9b7964f06be0adc075c4479ea7289da64/sql/descriptor.go#L235)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> You were my source for that - didn't you file an issue upstream about this?
</details>
fwiw, I've done this benchmark before and seen indexing be noticeably faster than append

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8433)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/descriptor.go, line 235 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8433#-KPJOaCA-Dno05v9_KvR:-KPK14PInAUWL23VfnuI:bwyj6ay) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6a880a9b7964f06be0adc075c4479ea7289da64/sql/descriptor.go#L235)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> fwiw, I've done this benchmark before and seen indexing be noticeably faster than append
</details>
Ah I believe that was `append(x, []byte...)` vs `copy(x, []byte)`. 

But yeah Dan, I just reran the benchmark I had and saw very different results from what I remember. I wonder why. It looks like indexing is about 10x faster. I'll make the change here and in the future.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8433)*

**Pull request merged**
