### PR TITLE
sql/opt/bench: fix invalid JSON in `INJECT STATISTICS`

### LINKED ISSUE #93565: sql/opt/bench: BenchmarkPhases is flakey
```
[Bench //pkg/sql/opt/bench:bench_test] BenchmarkPhases-16         	panic: could not parse JSON: unable to decode JSON: invalid character ']' looking for beginning of value
[Bench //pkg/sql/opt/bench:bench_test] 
[Bench //pkg/sql/opt/bench:bench_test] goroutine 13 [running]:
[Bench //pkg/sql/opt/bench:bench_test] github.com/cockroachdb/cockroach/pkg/sql/opt/testutils/testcat.injectTableStats(0xc000b06b00, {0x5882f78, 0xc000cea540})
[Bench //pkg/sql/opt/bench:bench_test] 	github.com/cockroachdb/cockroach/pkg/sql/opt/testutils/testcat/alter_table.go:64 +0x5b8
[Bench //pkg/sql/opt/bench:bench_test] github.com/cockroachdb/cockroach/pkg/sql/opt/testutils/testcat.(*Catalog).AlterTable(0x0?, 0xc000051aa0)
[Bench //pkg/sql/opt/bench:bench_test] 	github.com/cockroachdb/cockroach/pkg/sql/opt/testutils/testcat/alter_table.go:40 +0x365
[Bench //pkg/sql/opt/bench:bench_test] github.com/cockroachdb/cockroach/pkg/sql/opt/testutils/testcat.(*Catalog).ExecuteDDLWithIndexVersion(0xc000b44060?, {0x47d85a6?, 0x0?}, 0x0?)
[Bench //pkg/sql/opt/bench:bench_test] 	github.com/cockroachdb/cockroach/pkg/sql/opt/testutils/testcat/test_catalog.go:454 +0x21f
[Bench //pkg/sql/opt/bench:bench_test] github.com/cockroachdb/cockroach/pkg/sql/opt/testutils/testcat.(*Catalog).ExecuteDDL(...)
[Bench //pkg/sql/opt/bench:bench_test] 	github.com/cockroachdb/cockroach/pkg/sql/opt/testutils/testcat/test_catalog.go:422
[Bench //pkg/sql/opt/bench:bench_test] github.com/cockroachdb/cockroach/pkg/sql/opt/bench.newHarness({0x58c4fe0, 0xc0003aa480}, {{0x45de339, 0x7}, {0x46547f8, 0x23}, {0x7ec43b0, 0x1, 0x1}, {0x0, ...}}, ...)
[Bench //pkg/sql/opt/bench:bench_test] 	github.com/cockroachdb/cockroach/pkg/sql/opt/bench/bench_test.go:734 +0xe7a
[Bench //pkg/sql/opt/bench:bench_test] github.com/cockroachdb/cockroach/pkg/sql/opt/bench.BenchmarkPhases(0xc0003aa480?)
[Bench //pkg/sql/opt/bench:bench_test] 	github.com/cockroachdb/cockroach/pkg/sql/opt/bench/bench_test.go:673 +0x1cf
[Bench //pkg/sql/opt/bench:bench_test] testing.(*B).runN(0xc0003aa480, 0x1)
[Bench //pkg/sql/opt/bench:bench_test] 	GOROOT/src/testing/benchmark.go:193 +0x102
[Bench //pkg/sql/opt/bench:bench_test] testing.(*B).run1.func1()
[Bench //pkg/sql/opt/bench:bench_test] 	GOROOT/src/testing/benchmark.go:233 +0x59
[Bench //pkg/sql/opt/bench:bench_test] created by testing.(*B).run1
[Bench //pkg/sql/opt/bench:bench_test] 	GOROOT/src/testing/benchmark.go:226 +0x9c
```

Build: <https://teamcity.cockroachdb.com/viewLog.html?buildId=7950950&buildTypeId=Cockroach_Ci_Tests_Bench&tab=buildResultsDiv>

Seems to be introduced by #93482. Using the random seed from one of the failed builds consistently reproduces the failure.

Jira issue: CRDB-22405

### PR DESCRIPTION
**Pull request by renatolabs**
Fixes: #93565
Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: thank you!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93605#-:-NJG5DY13VRo2jKlF6AV:bro3093)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @renatolabs)

**Comment by renatolabs** [comment]
> Thanks for fixing this! I wonder why it is successful some of the time but not all of the time...

I was also curious so I dug a little deeper. Turns out this will fail with 50% probability depending on which JSON parser is picked:

https://github.com/cockroachdb/cockroach/blob/dc9cfae6a4a1bd46f2f8d8b6ea0cc12d8f121483/pkg/util/json/config.go#L69-L74

The standard Go JSON parser does not allow trailing commas while the fast JSON parser does. Given trailing commas are technically not allowed in JSON, I wonder if this intended behavior or not. I'll inquire.

**Comment by rytaft** [comment]
Interesting! Good find!

**Comment by renatolabs** [comment]
Benchmark failures in this PR are unrelated (another bug, it seems).

bors r=rytaft

**Pull request merged**
