### PR TITLE
distsql: add missing MoveToDraining in windower

### PR DESCRIPTION
**Pull request by jordanlewis**
Release note: None

### CODE REVIEW

**Review by solongordon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28821)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/windower.go, line 339 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28821#-LKMitM35tsRE4ekp5Rh:-LKMitM4BhGKDBvzvtOg:b5u9g9n) ([raw file](https://github.com/cockroachdb/cockroach/blob/da8da674fb1053eb5e7543485ac74adcda414c1d/pkg/sql/distsqlrun/windower.go#L339)):*
> ```Go
> 				if err != nil {
> 					w.MoveToDraining(err)
> 					return windowerStateUnknown, nil, &ProducerMetadata{Err: err}
> ```

Should this return `DrainHelper()` instead?  It seems redundant to return error metadata here since `MoveToDraining` already added it to the trailing metadata.

**Comment by jordanlewis** [comment]
Done.

**Review by solongordon — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28821#-:-LKMqE1JERK09-8UPNj9:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
