### PR TITLE
sql: rename virtual inverted columns as artificial inverted columns

### PR DESCRIPTION
**Pull request by mgartner**
The term "virtual" is overloaded. It can refer to virtual tables,
virtual indexes, and virtual computed columns. It was also used in
"virtual inverted columns" to describe pseudo-columns containing
inverted index keys, which have values different than the indexed
column. To prevent confusion with virtual computed columns, these
columns are now called "artificial inverted columns".

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
The first commit is from #67693.

**Review by RaduBerinde — COMMENTED** [review]
Great idea! :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67696#-:-MehHDED8gKpzuZBlbOr:b-tpuhzu)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, @michae2, and @rytaft)

___
*[pkg/sql/opt/cat/column.go, line 193 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67696#-MehH5xv-v7oancxz0Co:-MehH5xv-v7oancxz0Cp:b-ot8wgn) ([raw file](https://github.com/cockroachdb/cockroach/blob/4de36d5964ce51ae8b5f70a859cc5bffd45b0119/pkg/sql/opt/cat/column.go#L193)):*
> ```Go
> 
> // InitNonArtificial is used by catalog implementations to populate a
> // non-artificial Column. It should not be used anywhere else.
> ```

Does that mean you can use this for virtual computed columns? If yes, do we still need InitVirtualComputed?

**Comment by mgartner** [comment]
___
*[pkg/sql/opt/cat/column.go, line 193 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67696#-MehH5xv-v7oancxz0Co:-Melq_qq9SQaqxDFH8hv:b-jq8bsq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4de36d5964ce51ae8b5f70a859cc5bffd45b0119/pkg/sql/opt/cat/column.go#L193)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Does that mean you can use this for virtual computed columns? If yes, do we still need InitVirtualComputed?
</blockquote></details>

`InitVirtualComputed` automatically sets the `kind` to `Ordinary` because virtual columns don't need to be backfilled - they are never write-only or delete-only. I could combine that logic into `InitNonArtificial` if you think that would make things more clear.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67696)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, @michae2, and @rytaft)

___
*[pkg/sql/opt/cat/column.go, line 193 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67696#-MehH5xv-v7oancxz0Co:-MerjCWKBdmqGrVO3ptj:b13tziv) ([raw file](https://github.com/cockroachdb/cockroach/blob/4de36d5964ce51ae8b5f70a859cc5bffd45b0119/pkg/sql/opt/cat/column.go#L193)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

`InitVirtualComputed` automatically sets the `kind` to `Ordinary` because virtual columns don't need to be backfilled - they are never write-only or delete-only. I could combine that logic into `InitNonArtificial` if you think that would make things more clear.
</blockquote></details>

No, I would just update this description to say "non-artificial and non-virtual column"

**Review by rytaft — COMMENTED** [review]
I like the idea of reducing the proliferation of the word "virtual". Did you consider just calling these columns "inverted" instead of "artificial inverted"?

> Reviewed 2 of 2 files at r1, 32 of 32 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67696#-:-Mf-mZctCyK9myY3y9VT:b-ciw4lc)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach, @mgartner, and @michae2)

**Comment by mgartner** [comment]
> I like the idea of reducing the proliferation of the word "virtual". Did you consider just calling these columns "inverted" instead of "artificial inverted"?

That's a good idea. I created #67784 that does just that. If @raduberinde agrees with the naming, I'll go ahead and close this.

**Comment by mgartner** [comment]
Closing in favor of #67784.

**Pull request closed without merging**
