### PR TITLE
[2.0 backport] rocksdb: Update ref to include SST unique ID fix

### PR DESCRIPTION
**Pull request by itsbilal**
This change updates the RocksDB ref on 2.0 to include this fix:
https://github.com/cockroachdb/rocksdb/pull/65

Release note: None

### CODE REVIEW

**Comment by itsbilal** [comment]
@garvitjuniwal You should be able to merge this into your branch

**Review by petermattis — APPROVED** [review]

**Comment by itsbilal** [comment]
Can't merge due to failing stale Docker acceptance tests on this branch. So I'll close this PR as-is and leave the branch in place; anyone interested can just merge this branch / update the ref as they find fit.

**Comment by neeral** [comment]
@itsbilal i'm running into the same problem with acceptance tests failing. What's your assessment of the failures? Does it indicate that this change to rocksdb could have introduced a bug? The acceptance tests are passing without this change.

**Comment by itsbilal** [comment]
@neeral Thanks for the ping! It's actually this issue: https://github.com/cockroachdb/cockroach/pull/33446 and is related to how we generate a version string from `git describe`. You should be able to add a version tag (eg. `v2.0.x-rubrik`) to the latest commit on your branch and that should fix it. Seems like the code fix for not having acceptance tests rely on it was backported to 2.1 but not 2.0.

**Comment by neeral** [comment]
Thanks, I've cherry-picked #33446 and it is working now :)

**Pull request closed without merging**
