### PR TITLE
jobs: add VIEWJOB role option

### PR DESCRIPTION
**Pull request by jayshrivastava**
#### jobs: allow CONTROLJOB users to view all jobs 
This is a preliminary change before adding the `VIEWJOB` role
option. The purpose of the `VIEWJOB` role option
will be to allow TSEs to view jobs in admin clusters without
modifying them. This requires access to view all jobs, including ones
owned by admins.

Adding `VIEWJOB` will conflict with the present `CONTROLJOB` implementation.
It will be stronger than `CONTROLJOB` because it lets one view admin jobs when
`CONTROLJOB` doesn't, yet it will be weaker because it only allows viewing
jobs and not pause/cancel/resume-ing them.

This change is introduced to make `CONTROLJOB` at least as strong
as `VIEWJOB`: it now allows for all jobs to be viewed. In other words,
`VIEWJOB` lets you do a subset of things `CONTROLJOB` lets you do.

Also, the reason that `CONTROLJOB` prevents access to admin-owned
jobs is not well defined. This is tracked in https://github.com/cockroachdb/cockroach/issues/96432.

Release note (general change):
Previously, users with the `CONTROLJOB` role option could not view
owned by admins (ex. via `SHOW JOBS`). Now, they can.

Epic: none

---

#### jobs: add VIEWJOB role option
Release note (general change):
Users can now be granted the `VIEWJOB` role option
to be able to view all jobs (ex. via `SHOW JOBS`).
This role can be revoked using `NOVIEWJOB`.

Epic: none

### CODE REVIEW

**Review by jayshrivastava — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96382)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[`pkg/jobs/jobsauth/authorization.go` line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96382#-NNHu02XA-WYhMXqb6X-:-NNHu02XA-WYhMXqb6X0:bky0usl) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ae413bd7157fbaf11885772aa694671ace717b5/pkg/jobs/jobsauth/authorization.go#L40)):*
> ```Go
> 	// ViewAccess. In other words: if a user with a given set of privileges is
> 	// authorized to modify a job using ControlAccess, they will be authorized to
> 	// view it using ViewAccess.
> ```

This is unnecessary because job-type specific checks may not obey this, depending on the implementation. This restriction is also not that important imo.

**Review by HonoreDB — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96382)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by jayshrivastava** [comment]
bors r=HonoreDB TYFR!

**Comment by jayshrivastava** [comment]
bors r=HonoreDB

**Comment by jayshrivastava** [comment]
bors r=HonoreDB

**Pull request merged**
