### PR TITLE
opt: rename ScalarID to ScalarRank

### PR DESCRIPTION
**Pull request by mgartner**
Previously, every scalar expression (except lists and list items) had an
ID that was said to be unique within the context of a memo. These IDs
were originally added as a way to canonically order filters. Being named
"IDs", their use later expanded to check for equality of two scalar
expressions.

Maintaining this uniqueness invariant is difficult in practice and has
dangerous implications when it is violated, as seen in #71002. While two
different scalar expressions with the same ID could certainly cause
problems for sorting filters, using these IDs to check for scalar
expression equality can be catastrophic. For example, a filter
expression that shares an ID with another expression could be completely
removed from the filter.

Unfortunately, there's no obvious way to add test build assertions that
scalar IDs are in fact unique, as explained in #71035. In order to
lessen the blast radius of breaking this invariant, this commit renames
"scalar ID" to "scalar rank". The comment for this attribute does not
explicitly guarantee its uniqueness. This renaming should urge
contributors to only use this value for ordering scalar expressions
canonically, not for scalar expression equality. Instead, pointer
equality should be used to check if two scalar expressions are the same.

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
The first commit is from #71035.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71037#-:-MlBTXBL4L01D58uam7V:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/norm/select_funcs.go, line 278 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71037#-MlBSFtw9vXPE8h3jIPz:-MlBSFtw9vXPE8h3jIQ-:b-j0sfwb) ([raw file](https://github.com/cockroachdb/cockroach/blob/bac288971c5ca199a214fc562f767db0740949e0/pkg/sql/opt/norm/select_funcs.go#L278)):*
> ```Go
> 
> // AreFiltersSorted determines whether the expressions in a FiltersExpr are
> // ordered by their expression IDs.
> ```

IDs -> ranks

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71037)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/norm/select_funcs.go, line 278 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71037#-MlBSFtw9vXPE8h3jIPz:-MlMQqKfA0poyidQtdtY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bac288971c5ca199a214fc562f767db0740949e0/pkg/sql/opt/norm/select_funcs.go#L278)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

IDs -> ranks
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71037)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

**Pull request merged**
