### PR TITLE
acceptance: skip update check for remote tests

### PR DESCRIPTION
**Pull request by cuongdo**
- acceptance: skip update check for remote tests
- acceptance: use correct SHA when downloading photos

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8312)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[acceptance/terrafarm/farmer.go, line 101 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8312#-KOHHbljAjjtefVpY411:-KOHHbljAjjtefVpY412:1647379689) ([raw file](https://github.com/cockroachdb/cockroach/blob/a29d2d2f744b679794aa5590d1280b74b60b622c/acceptance/terrafarm/farmer.go#L101)):*
> ```Go
> 	// Disable update checks for test clusters.
> 	const skipCheck = "COCKROACH_SKIP_UPDATE_CHECK=1"
> 	const envVar = "cockroach_env"
> ```

comment on where this comes from

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8312#-:-KOHHlIeMzvc6d4cWtQ9:1417088721)*

**Comment by cuongdo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[acceptance/terrafarm/farmer.go, line 101 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8312#-KOHHbljAjjtefVpY411:-KOHKuDgx_SLSpUK5Xb-:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/a29d2d2f744b679794aa5590d1280b74b60b622c/acceptance/terrafarm/farmer.go#L101)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> comment on where this comes from
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8312)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[acceptance/terrafarm/farmer.go, line 102 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8312#-KOHM9sBg2mr32YtP0vf:-KOHM9sCW0oL1iONPCQf:414277946) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70f9359d4dc6ac534aec6b252c77b2e62fb87f2/acceptance/terrafarm/farmer.go#L102)):*
> ```Go
> 	// variable.
> 	const skipCheck = "COCKROACH_SKIP_UPDATE_CHECK=1"
> 	// This is a Terraform variable defined in the acceptance Terraform config
> ```

can you reference the specific file? otherwise, you can do something gross and try to parse that file from here at `init()`. There's prior art, sort of, in build/builder.sh.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8312)*

**Comment by cuongdo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[acceptance/terrafarm/farmer.go, line 102 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8312#-KOHM9sBg2mr32YtP0vf:-KOIU4zMNprzsb0u7TjG:1485829145) ([raw file](https://github.com/cockroachdb/cockroach/blob/e70f9359d4dc6ac534aec6b252c77b2e62fb87f2/acceptance/terrafarm/farmer.go#L102)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can you reference the specific file? otherwise, you can do something gross and try to parse that file from here at `init()`. There's prior art, sort of, in build/builder.sh.
</details>
comments added

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8312)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8312)*

**Pull request merged**
