### PR TITLE
clusterversion: cockroach versions cleanup

### PR DESCRIPTION
**Pull request by RaduBerinde**
This commit cleans up the code and constants in
`cockroach_versions.go`:
 - we separate out the "dev offset" code and improve the documentation;
 - we replace the key-to-version slice with a table (array). This makes the declaration much cleaner and makes the lookup easier.
 - we replace `ByKey()` with a method, to make the call site less messy, e.g. `clusterversion.ByKey(clusterversion.V23_2)` becomes `clusterversion.V23_2.Version()`;
 - we deprecate `BinaryMinSupportedVersionKey` in favor of `MinSupported`;
 - we deprecate `BinaryVersionKey` in favor of `Latest`;
 - we remove `roachpb.Version` "constants" in favor of using the `Version()` method.

Informs: #112629
Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
I plan to do similar related cleanup (e.g. to the methods of the version Handle) once this is approved.

**Comment by RaduBerinde** [comment]
Friendly ping

**Review by andyyang890 — COMMENTED** [review]
Started reviewing this and it looks pretty good so far! Had a few questions and a small nit.

> Reviewed 4 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113314#-:-NiGOTqS9GL_CT6L2zI3:b11mhnk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @celiala, @dt, @RaduBerinde, and @rail)

___
*[`pkg/clusterversion/cockroach_versions.go` line 517 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113314#-NiGERWH2rhm9YE6MfpG:-NiGERWH2rhm9YE6MfpH:bhh14c3) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cce778ea1d73fb3f6b7bc969cf4a42bf75a3cf0/pkg/clusterversion/cockroach_versions.go#L517)):*
> ```Go
> //
> // Note that versions in this table can be modified by applying a "dev offset"
> // to ensure that upgrades don't occur between in-developent and relased
> ```

nit: `s/developent/development/` and `s/relased/released/`
___
*[`pkg/clusterversion/dev_offset.go` line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113314#-NiGKHXq6bBcAmWJUuTu:-NiGKHXq6bBcAmWJUuTv:bpvifkx) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cce778ea1d73fb3f6b7bc969cf4a42bf75a3cf0/pkg/clusterversion/dev_offset.go#L41)):*
> ```Go
> // version! For example, on a cluster that is on released version 3, a dev
> // binary containing versions 1, 2, 3, and 4 started with this flag would
> // renumber only 2-4 to be +1M. It would then step from 3 "up" to 1000002 --
> ```

```
// ... For example, on a cluster that is on released version 3, a dev
// binary containing versions 1, 2, 3, and 4 started with this flag would
// renumber only 2-4 to be +1M. ...
```
I know this comment was just copied over but I'm kind of confused about this sentence. Is it because we had the implicit assumption before that `MinSupported` is 1 version lower (i.e. 2 in this example)?
___
*[`pkg/clusterversion/dev_offset.go` line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113314#-NiGLOz04xbR2aggUm-b:-NiGLOz04xbR2aggUm-c:bfbih37) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cce778ea1d73fb3f6b7bc969cf4a42bf75a3cf0/pkg/clusterversion/dev_offset.go#L46)):*
> ```Go
> var devOffsetKeyStart = func() Key {
> 	forceDev := envutil.EnvOrDefaultBool("COCKROACH_FORCE_DEV_VERSION", false)
> 	forceRelease := envutil.EnvOrDefaultBool("COCKROACH_TESTING_FORCE_RELEASE_BRANCH", false)
> ```

What is the use case for `COCKROACH_TESTING_FORCE_RELEASE_BRANCH`? It seems like it would be used to allow us to build a non-dev binary from a release branch after it is cut and before we change `developmentBranch` to `false`. When would we want to do this?

Also, do we want to rename it to something like `COCKROACH_FORCE_NON_DEV_VERSION` or something more specific that indicates what exactly we are forcing?

**Review by RaduBerinde — COMMENTED** [review]
Thanks for reviewing!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113314#-:-NiGTCoa3Gy0tmq4YdGD:b-yz40g0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @andyyang890, @celiala, @dt, and @rail)

___
*[`pkg/clusterversion/cockroach_versions.go` line 517 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113314#-NiGERWH2rhm9YE6MfpG:-NiGTPyU5P66NLOKkvrN:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cce778ea1d73fb3f6b7bc969cf4a42bf75a3cf0/pkg/clusterversion/cockroach_versions.go#L517)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

nit: `s/developent/development/` and `s/relased/released/`
</blockquote></details>

Fixed.
___
*[`pkg/clusterversion/dev_offset.go` line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113314#-NiGKHXq6bBcAmWJUuTu:-NiGSOpJAuzxm6n6AlRi:bikusgy) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cce778ea1d73fb3f6b7bc969cf4a42bf75a3cf0/pkg/clusterversion/dev_offset.go#L41)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

```
// ... For example, on a cluster that is on released version 3, a dev
// binary containing versions 1, 2, 3, and 4 started with this flag would
// renumber only 2-4 to be +1M. ...
```
I know this comment was just copied over but I'm kind of confused about this sentence. Is it because we had the implicit assumption before that `MinSupported` is 1 version lower (i.e. 2 in this example)?
</blockquote></details>

Correct, I improved the comment.
___
*[`pkg/clusterversion/dev_offset.go` line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113314#-NiGLOz04xbR2aggUm-b:-NiGS_kU2yZboGsQfw1n:bz3np6i) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cce778ea1d73fb3f6b7bc969cf4a42bf75a3cf0/pkg/clusterversion/dev_offset.go#L46)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

What is the use case for `COCKROACH_TESTING_FORCE_RELEASE_BRANCH`? It seems like it would be used to allow us to build a non-dev binary from a release branch after it is cut and before we change `developmentBranch` to `false`. When would we want to do this?

Also, do we want to rename it to something like `COCKROACH_FORCE_NON_DEV_VERSION` or something more specific that indicates what exactly we are forcing?
</blockquote></details>

It is used for some tests where we actually want to test things as they would happen in the "real" release (as much as possible).

I agree the name could be better but I'm not keen on renaming it in case it is already in use (e.g. in scripts).

**Review by celiala — APPROVED** [review]
O.M.G. - this is such an elegant-looking improvement :heart_eyes:  -- thank you for doing this! 
LGTM!

> Reviewed 13 of 15 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113314#-:-NiG_OEz01dcpQ6rrVTW:bf43non)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @andyyang890, @dt, @RaduBerinde, and @rail)

___
*[`pkg/clusterversion/cockroach_versions.go` line 622 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113314#-NiGXkkY5UOPrQdZDIxt:-NiGXkkY5UOPrQdZDIxu:b-3593u4) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3964a097978f8383ce71351a3d29cd6892e78b7/pkg/clusterversion/cockroach_versions.go#L622)):*
> ```Go
> // Note: this is always the last element of SupportedPreviousReleases(); it is
> // also provided as a constant for convenience.
> const PreviousRelease Key = V23_2
> ```

maybe linter to verify that PreviousRelease always equals Latest - 1?
___
*[`pkg/clusterversion/cockroach_versions.go` line 633 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113314#-NiGXuZNBcrM2gc3OMzC:-NiGXuZNBcrM2gc3OMzD:b-p1q1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3964a097978f8383ce71351a3d29cd6892e78b7/pkg/clusterversion/cockroach_versions.go#L633)):*
> ```Go
> 
> // DEPRECATED: use MinSupported.
> const BinaryMinSupportedVersionKey = MinSupported
> ```

should we rename `BinaryMinSupportedVersionKey` to 'DEPRECATED_BinaryMinSupportedVersionKey`? (suggestion for future, not this PR necessarily)
___
*[`pkg/clusterversion/cockroach_versions.go` line 635 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113314#-NiGY6g_8m142UTXSdo4:-NiGY6g_8m142UTXSdo5:bf0mie8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3964a097978f8383ce71351a3d29cd6892e78b7/pkg/clusterversion/cockroach_versions.go#L635)):*
> ```Go
> const BinaryMinSupportedVersionKey = MinSupported
> 
> // DEPRECATED: use Latest.
> ```

(same)
___
*[`pkg/clusterversion/cockroach_versions.go` line 661 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113314#-NiGYKur-FbQpSqZZH9u:-NiGYKusCW_gT3fDTNzs:b-ir0h1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3964a097978f8383ce71351a3d29cd6892e78b7/pkg/clusterversion/cockroach_versions.go#L661)):*
> ```Go
> 			panic("latest version does not match final version")
> 		}
> 		if developmentBranch {
> ```

add the "if Previous != Latest - 1 then panic" check here?

**Review by RaduBerinde — COMMENTED** [review]
Thanks!!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113314#-:-NiGanbA0tbkfq2Qtk0U:b-hay2ia)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @andyyang890, @celiala, @dt, and @rail)

___
*[`pkg/clusterversion/cockroach_versions.go` line 622 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113314#-NiGXkkY5UOPrQdZDIxt:-NiGaqU8Bs1KXadPpZPI:bcme8co) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3964a097978f8383ce71351a3d29cd6892e78b7/pkg/clusterversion/cockroach_versions.go#L622)):*
<details><summary><i>Previously, celiala wrote…</i></summary><blockquote>

maybe linter to verify that PreviousRelease always equals Latest - 1?
</blockquote></details>

Note that it is not "previous version" but "previous release". So it's the last version key before Latest that has `Internal = 0`.`TestKeyConstants` verifies the constant.
___
*[`pkg/clusterversion/cockroach_versions.go` line 633 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/113314#-NiGXuZNBcrM2gc3OMzC:-NiGaEIZ2JKPaI0PARGS:br3jthx) ([raw file](https://github.com/cockroachdb/cockroach/blob/f3964a097978f8383ce71351a3d29cd6892e78b7/pkg/clusterversion/cockroach_versions.go#L633)):*
<details><summary><i>Previously, celiala wrote…</i></summary><blockquote>

should we rename `BinaryMinSupportedVersionKey` to 'DEPRECATED_BinaryMinSupportedVersionKey`? (suggestion for future, not this PR necessarily)
</blockquote></details>

Just adding the comment is enough to make all uses look crossed out in Goland. I plan to clean it up soon, just didn't want to make it all in a huge PR.

**Review by andyyang890 — APPROVED** [review]
:lgtm: This is awesome!

> Reviewed 10 of 15 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113314#-:-NiGtLUf-Lxx6B7m06ud:b5qwx29)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi, @celiala, @dt, @RaduBerinde, and @rail)

___
*[`pkg/clusterversion/dev_offset.go` line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113314#-NiGLOz04xbR2aggUm-b:-NiGeV7t7ph0Vu20GCmj:bria5zi) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cce778ea1d73fb3f6b7bc969cf4a42bf75a3cf0/pkg/clusterversion/dev_offset.go#L46)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It is used for some tests where we actually want to test things as they would happen in the "real" release (as much as possible).

I agree the name could be better but I'm not keen on renaming it in case it is already in use (e.g. in scripts).
</blockquote></details>

Ah got it, would it be possible to maybe add a note documenting it to the comment above `devOffsetKeyStart`?

**Review by RaduBerinde — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113314#-:-NiGvZH_EqNcVADw0UqE:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aadityasondhi, @andyyang890, @celiala, @dt, and @rail)

___
*[`pkg/clusterversion/dev_offset.go` line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113314#-NiGLOz04xbR2aggUm-b:-NiGvLZE27-EZQbssiSK:b2ruhn1) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cce778ea1d73fb3f6b7bc969cf4a42bf75a3cf0/pkg/clusterversion/dev_offset.go#L46)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Ah got it, would it be possible to maybe add a note documenting it to the comment above `devOffsetKeyStart`?
</blockquote></details>

Done. Good idea, I added some documentation for both env vars.

**Comment by renatolabs** [comment]
```
pkg/clusterversion/setting_test.go:69:51: undefined: clusterversion.VCurrent_Start
```

bors r-

**Pull request merged**
