### PR TITLE
config, sql: completing partial zone configs

### PR DESCRIPTION
**Pull request by ridwanmsharif**
With cascading zone configs, as explained in the RFC it is possible
to get into situations where the zones find themselves in an invalid
state as a result of changes made to parent zone configs. This addresses
that issue by writing fields in tandem in the partial zone.

Release note (sql change): Setting only one bound for the range sizes or
setting per-replica constraints will implicitly set other fields in the
zone config for future validation purposes.

### CODE REVIEW

**Review by ridwanmsharif — COMMENTED** [review]
`ALTER TABLE f CONFIGURE ZONE USING range_min_bytes = 4MB, range_max_bytes = COPY FROM PARENT`

This is essentially what is happening here but implicitly (which I prefer). The issue of the changes to the default max bytes not applying to the child zone will exist regardless, unless we write validation code that validates all descendants when validating a given zone when making a change. There we have a penalty for sure. We talked about this being a problem in the RFC and thought that having these two pairs written in tandem would avoid problems later on fairly easily and it'd me appropriate for most cases. That was a while ago, we may have changed our mind since then. I think the reason we moved away from the descendants validation idea was also in part due to the complexity that would add (in addition to the time penalty), so this + some documentation of what the new behavior under cascading looks like, seemed preferable.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32059#-:-LQA_ziIAbbSGV9oNavR:b-6r0zi3)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by benesch** [comment]
> This is essentially what is happening here but implicitly (which I prefer)

Yes, exactly—it's the implicitness that scares me.  To be clear I'm very much in favor of a solution that doesn't involve descendent validation. I just think that we need to force users to explicitly indicate that they understand when they set field A that they're setting B along with it.

**Review by ridwanmsharif — COMMENTED** [review]
Not necessarily disagreeing but to be clear, you'd rather have the user figure out what the `range_max_bytes` are from the default and only then apply a change to them in tandem manually? Also, what about for per-replica constraints? 
when someone does something like:
`ALTER ... CONFIGURE ZONE USING constraints = '{+region=west: 2, +region=east: 3}'"`
at this point we just *solidify* the `num_replicas` that was being applied to the zone. 

So in this case, later on when a parent's `num_replica`s value reduces to < 5, we are rest assured the value for this zone is still >= 5 because of the implicit setting before. Are you saying you want the client to now have to do this instead?:
`ALTER ... CONFIGURE ZONE USING num_replicas = num_ge_5, constraints = '{+region=west: 2, +region=east: 3}'"`

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32059#-:-LQAtC4h5QW3kykqQSp3:b-wkbnk2)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by benesch** [comment]
> Are you saying you want the client to now have to do this instead?:
> `ALTER ... CONFIGURE ZONE USING num_replicas = num_ge_5, constraints = '{+region=west: 2, +region=east: 3}'"`

Yes, exactly. That way the user will hopefully realize that they are overriding _both_ values. And in the common case where you only intend to set one of the values and want to copy the other from the parent, I think `COPY FROM PARENT` is a reasonable choice. So in your example:

```
ALTER ... CONFIGURE ZONE USING num_replicas = COPY FROM PARENT, constraints = '{+region=west: 2, +region=east: 3}'"
```

But before you go down this road I definitely want to hear what @knz and @a-robinson think.

**Comment by ridwanmsharif** [comment]
Taking a second stab at this in #32861. We're not moving forward with this approach.

**Pull request closed without merging**
