### PR TITLE
ui: Add CircleFilled component

### PR DESCRIPTION
**Pull request by ericharmeling**
Previously, there was no component for a filled circle icon in the `ui` package.
Recent product designs have requested this icon for the DB Console (see #67510, #73463).
This PR adds a `CircleFilled` component to the `ui` package.

Release note: None

### CODE REVIEW

**Review by gtr — APPROVED** [review]
LGTM! Thanks 😄

**Review by maryliag — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75807#-:-MuqgUOF3Duidrp5HeX3:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by ericharmeling** [comment]
The Bazel CI keeps failing for this PR. It looks like a [timeout that is unrelated to the changes made in this PR](https://cockroachlabs.slack.com/archives/CJ0H8Q97C/p1643751082871709?thread_ts=1643750414.242969&cid=CJ0H8Q97C).

Any objections to just ignoring the Bazel CI, as it's technically optional, and merging?

**Comment by maryliag** [comment]
No objections, you can go ahead with the merge

**Pull request merged**
