### PR TITLE
sql: fix flakiness with InternalExecutorFactoryMemMonitor closing TestServers

### PR DESCRIPTION
**Pull request by RichardJCai**
Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84212)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai and @yuzefovich)

___
*[`pkg/server/server_sql.go` line 934 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84212#-N6jEwHX6NjZc5YfbQHe:-N6jEwHY5W-mFxi38kp7:b-q8kxk6) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb1d7b61ac6711c619af64f7f8349748fa853075/pkg/server/server_sql.go#L934)):*
> ```Go
> 	// systemIeMonitor is used for the jobsIeFactory and for the
> 	// circularInternalExecutor.
> 	// The schema changer may still be executing jobs queries.
> ```

Can you help me understand how this happens? Shouldn't the schema changer queries stop before the Closer gets called?

**Comment by RichardJCai** [comment]
> > Reviewed all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84212)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai and @yuzefovich)
> 
> _[`pkg/server/server_sql.go` line 934 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84212#-N6jEwHX6NjZc5YfbQHe:-N6jEwHY5W-mFxi38kp7:b-q8kxk6) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb1d7b61ac6711c619af64f7f8349748fa853075/pkg/server/server_sql.go#L934)):_
> 
> > ```go
> > 	// systemIeMonitor is used for the jobsIeFactory and for the
> > 	// circularInternalExecutor.
> > 	// The schema changer may still be executing jobs queries.
> > ```
> 
> Can you help me understand how this happens? Shouldn't the schema changer queries stop before the Closer gets called?

I just updated the PR to just not close anything.

I was seeing in `TestAtMostOneRunningCreateStats` that the monitor I attached to the jobs internal executor was still allocated some memory when `Closer` was called. Is it possible that the query stops but theres a race with the memory being cleared.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84212#-:-N6jWIL2AqZDAxQkX6y2:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by RichardJCai** [comment]
Thanks!

bors r=yuzefovich

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84212)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[`pkg/server/server_sql.go` line 934 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84212#-N6jEwHX6NjZc5YfbQHe:-N6kF9DJ-BIWRbnsAhUD:b-cxxvdc) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb1d7b61ac6711c619af64f7f8349748fa853075/pkg/server/server_sql.go#L934)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I just updated the PR to just not close anything.

I was seeing in `TestAtMostOneRunningCreateStats` that the monitor I attached to the jobs internal executor was still allocated some memory when `Closer` was called. Is it possible that the query stops but theres a race with the memory being cleared.

</blockquote></details>

:thinking: that's not very satisfying. Do you have more details on what was not released? If we could get to the bottom of it, it'd be really nice. It'd give us a claim that we do actually clean up properly. If we don't then we'll just let more folks get away with not cleaning up properly.

**Comment by RichardJCai** [comment]
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84212)_ status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RichardJCai)
> 
> _[`pkg/server/server_sql.go` line 934 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/84212#-N6jEwHX6NjZc5YfbQHe:-N6kF9DJ-BIWRbnsAhUD:b-cxxvdc) ([raw file](https://github.com/cockroachdb/cockroach/blob/cb1d7b61ac6711c619af64f7f8349748fa853075/pkg/server/server_sql.go#L934)):_
> 
> Previously, RichardJCai (Richard Cai) wrote…
> 🤔 that's not very satisfying. Do you have more details on what was not released? If we could get to the bottom of it, it'd be really nice. It'd give us a claim that we do actually clean up properly. If we don't then we'll just let more folks get away with not cleaning up properly.

Opened up an issue with context for now - https://github.com/cockroachdb/cockroach/issues/84302 don't have much time in the near future to dig into this.

**Pull request merged**
