### PR TITLE
distsql: clean up lookup join internal columns

### LINKED ISSUE #24401: sql: bug with lookup join
Version: CockroachDB CCL v2.1-alpha.00000000-1468-gb9d7e8b12

The following table and query produces an error:

```
SET experimental_force_lookup_join = true;
create database d;
use d;
CREATE TABLE players (
	game INT NOT NULL,
	mode INT NULL,
	"time" TIMESTAMP NULL,
	hero INT NULL,
	team INT NULL,
	blizzid INT NOT NULL,
	CONSTRAINT "primary" PRIMARY KEY (game ASC, blizzid ASC)
);
select p.team = games.team as sameteam, p.hero
from (
	select game, max(team) team
	from players
	group by game
) games
join players p  on games.game = p.game;
```

`pq: "$4" = "$1": unsupported comparison operator: <timestamp> = <int>`

If I remove the SET line it runs. Interestingly, if I remove pretty much any line of the CREATE it also runs. Kinda feels like an incorrect index offset somewhere.

### PR DESCRIPTION
**Pull request by pbardea**
Fixes #24401.

The distsql physical planner was not properly forming the post processor
spec according to the internal columns of lookup joins.

For the hash and merge joiners, the internal columns depend on the
streamToColMap of its upstream nodes. However since the lookup join's
internal columns consist of the entire right side of table columns, the
planner must modify the post processor spec and various maps.

This simplifies code inside the lookup joiner.

Release notes: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---

*[pkg/sql/distsqlrun/joinreader.go, line 142 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24697#-L9qL0Mj7za1vWWkFKn2:-L9qL0Mj7za1vWWkFKn3:b6qazlm) ([raw file](https://github.com/cockroachdb/cockroach/blob/0345e9df4449ae33c8d5182172f6eb1f1de6d0d0/pkg/sql/distsqlrun/joinreader.go#L142)):*
> ```Go
> 	neededCols = neededCols.Shift(-1 * len(jr.inputTypes))
> 
> 	rightSide := util.MakeFastIntSet()
> ```

Instead of building another set and intersecting, I'd just do
```go
for i, ok := neededCols.Next(len(jr.inputTypes)); ok; i, ok = neededCols.Next(i+1) {
  x.Add(i-len(jr.inputTypes))
}
```

---

*[pkg/sql/distsqlrun/joinreader.go, line 146 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24697#-L9qKwbO86CcYAe6nlWX:-L9qKwbO86CcYAe6nlWY:bvv839v) ([raw file](https://github.com/cockroachdb/cockroach/blob/0345e9df4449ae33c8d5182172f6eb1f1de6d0d0/pkg/sql/distsqlrun/joinreader.go#L146)):*
> ```Go
> 	neededCols.IntersectionWith(rightSide)
> 
> 	for i, val := range rightColMap {
> ```

Why isn't the `neededCols` at this point the result we want? We shouldn't need to do anything else here.. Why would we have a column in this rightColMap that isn't actually needed for anything?

---

*[pkg/sql/distsqlrun/processors.proto, line 244 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24697#-L9qIwZ1Ad8yxNvoK8TQ:-L9qIwZ1Ad8yxNvoK8TR:bg80o20) ([raw file](https://github.com/cockroachdb/cockroach/blob/0345e9df4449ae33c8d5182172f6eb1f1de6d0d0/pkg/sql/distsqlrun/processors.proto#L244)):*
> ```protobuf
>   optional Expression on_expr = 4 [(gogoproto.nullable) = false];
> 
>   repeated int32 right_column_map = 5 [packed = true];
> ```

What is this? I thought that our schema now has all the columns of the right table, so why do we need a map?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24697)*

**Comment by pbardea** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/distsqlrun/joinreader.go, line 142 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24697#-L9qL0Mj7za1vWWkFKn2:-L9qOfAZ8rxJ8Ym8B-TX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0345e9df4449ae33c8d5182172f6eb1f1de6d0d0/pkg/sql/distsqlrun/joinreader.go#L142)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Instead of building another set and intersecting, I'd just do
```go
for i, ok := neededCols.Next(len(jr.inputTypes)); ok; i, ok = neededCols.Next(i+1) {
  x.Add(i-len(jr.inputTypes))
}
```

</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/joinreader.go, line 146 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24697#-L9qKwbO86CcYAe6nlWX:-L9qN7uPCCq-Mf8MxMw_:b-jtyln5) ([raw file](https://github.com/cockroachdb/cockroach/blob/0345e9df4449ae33c8d5182172f6eb1f1de6d0d0/pkg/sql/distsqlrun/joinreader.go#L146)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Why isn't the `neededCols` at this point the result we want? We shouldn't need to do anything else here.. Why would we have a column in this rightColMap that isn't actually needed for anything?
</blockquote></details>

The added columns are the ones that we need to evaluate the `onExpr` of the join as well as the equality columns of the join. This is shown by the logic_test:
```
statement ok
CREATE TABLE distsql_lookup_test_1 (a INT, b INT, c INT, PRIMARY KEY (a, c)); INSERT INTO distsql_lookup_test_1 VALUES (1, 1, 2), (2, 1, 1), (2, NULL, 2)


statement ok
CREATE TABLE distsql_lookup_test_2 (d INT, e INT, f INT, PRIMARY KEY (f, e)); INSERT INTO distsql_lookup_test_2 VALUES (1, 1, 2), (2, 1, 1), (NULL, 2, 1)


# Test lookup join with selecting a subset of the columns.
query III rowsort
SELECT a, b, e FROM distsql_lookup_test_1 JOIN distsql_lookup_test_2 ON f = b WHERE a >= e
----
1  1  1
2  1  1
2  1  2
```

(The onExpr `a >= e` uses columns which are not in the post processing spec output, namely `e`).

---

*[pkg/sql/distsqlrun/processors.proto, line 244 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24697#-L9qIwZ1Ad8yxNvoK8TQ:-L9qOoW985txqZZkssFC:bjh8k0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/0345e9df4449ae33c8d5182172f6eb1f1de6d0d0/pkg/sql/distsqlrun/processors.proto#L244)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

What is this? I thought that our schema now has all the columns of the right table, so why do we need a map?
</blockquote></details>

This map specifies which of the right columns are needed to evaluate the `onExpr` of the join and the equality columns of the join. Added comment to indicate this.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24697)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/distsqlrun/joinreader.go, line 146 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24697#-L9qKwbO86CcYAe6nlWX:-L9qVdcF72YduMBSC7n4:bpyasvm) ([raw file](https://github.com/cockroachdb/cockroach/blob/0345e9df4449ae33c8d5182172f6eb1f1de6d0d0/pkg/sql/distsqlrun/joinreader.go#L146)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

The added columns are the ones that we need to evaluate the `onExpr` of the join as well as the equality columns of the join. This is shown by the logic_test:
```
statement ok
CREATE TABLE distsql_lookup_test_1 (a INT, b INT, c INT, PRIMARY KEY (a, c)); INSERT INTO distsql_lookup_test_1 VALUES (1, 1, 2), (2, 1, 1), (2, NULL, 2)


statement ok
CREATE TABLE distsql_lookup_test_2 (d INT, e INT, f INT, PRIMARY KEY (f, e)); INSERT INTO distsql_lookup_test_2 VALUES (1, 1, 2), (2, 1, 1), (NULL, 2, 1)


# Test lookup join with selecting a subset of the columns.
query III rowsort
SELECT a, b, e FROM distsql_lookup_test_1 JOIN distsql_lookup_test_2 ON f = b WHERE a >= e
----
1  1  1
2  1  1
2  1  2
```

(The onExpr `a >= e` uses columns which are not in the post processing spec output, namely `e`).
</blockquote></details>

`ProcOutputHelper.neededColumns` figures out what columns are needed by the post-processing filter. We can do the same on the onExpr.

		// See if filter requires this column.
		if h.filter != nil && h.filter.vars.IndexedVarUsed(i) {
			colIdxs.Add(i)
			continue
		}

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24697)*

**Comment by pbardea** [comment]
I don't think we do because it's experimental, but I will double check.

---

Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/distsql_plan_join.go, line 264 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24697#-L9rBeJl4J1wej425zYK:-L9uSJ_173TrK5T3VMAq:b-v64ob2) ([raw file](https://github.com/cockroachdb/cockroach/blob/03998395b31bd2af3c94ecd00d6ebc8993d76d5c/pkg/sql/distsql_plan_join.go#L264)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] If we want to localize this logic, we can pass the right planToStreamColMap to these functions (and in the lookup case we pass an identity). That way we can explain this in a single place. It would also be a bit nicer conceptually to not pass the `rightPlan` since there is no right plan anymore for lookup joins.

We should also add a comment somewhere explaining that the table must have `n.pred.numRightCols` columns since the right side is a `scanNode`, and scanNodes always produce all columns of the table.
</blockquote></details>

Done. Wasn't sure where to add the comment, so added it to the code in the distsql physical planner where the identity map is created.

---

*[pkg/sql/distsqlrun/joinreader.go, line 157 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24697#-L9r8ymB-fqJpA1h4vjs:-L9uSQZa2Ve2paqCpJp0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/03998395b31bd2af3c94ecd00d6ebc8993d76d5c/pkg/sql/distsqlrun/joinreader.go#L157)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I don't think we need these.
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/processors.proto, line 213 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24697#-L9r97Ff9radBXXDDSep:-L9uSRcHC8KBDvztARix:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/03998395b31bd2af3c94ecd00d6ebc8993d76d5c/pkg/sql/distsqlrun/processors.proto#L213)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Maybe port over the improvement to this comment you had in the other PR (invalid example for index join + I think lookup columns here should be `[0]` not `[0, 2]`)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24697#-:-L9uSVK-CgqqIdHwxMP5:b-7cydpx)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/sql/distsql_physical_planner.go, line 1796 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24697#-L9uWk-AAuP70pXxZC6U:-L9uWk-AAuP70pXxZC6V:b-gw8r0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/12c09754b902384fe1488893f26f8efd2f5e0805/pkg/sql/distsql_physical_planner.go#L1796)):*
> ```Go
> 		}
> 	} else {
> 		rightMap = rightPlan.planToStreamColMap
> ```

we're allocating the rightMap for nothing in this case. I'd move the `make` call inside the other branch

---

*[pkg/sql/distsql_plan_join.go, line 257 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24697#-L9uZDbe8wx6O78618VI:-L9uZDbe8wx6O78618VJ:b2mp87h) ([raw file](https://github.com/cockroachdb/cockroach/blob/03998395b31bd2af3c94ecd00d6ebc8993d76d5c/pkg/sql/distsql_plan_join.go#L257)):*
> ```Go
> 	joinCol := 0
> 	for i := 0; i < n.pred.numLeftCols; i++ {
> 		if !n.columns[joinCol].Omitted {
> ```

Why are we adding omitted columns now? These are columns that are not actually needed after the join, so we shouldn't be producing them.

---

*[pkg/sql/distsql_plan_join.go, line 257 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24697#-L9uX6fiEnay-Jab9Nbo:-L9uX6fiEnay-Jab9Nbp:bus5tm4) ([raw file](https://github.com/cockroachdb/cockroach/blob/12c09754b902384fe1488893f26f8efd2f5e0805/pkg/sql/distsql_plan_join.go#L257)):*
> ```Go
> 	joinCol := 0
> 	leftSize := 0
> 	for i := 0; i < n.pred.numLeftCols; i++ {
> ```

[nit] `leftCols`

---

*[pkg/sql/distsql_plan_join.go, line 290 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24697#-L9uXK9q8S3NqEz0hGzx:-L9uXK9q8S3NqEz0hGzy:b-c4vx40) ([raw file](https://github.com/cockroachdb/cockroach/blob/12c09754b902384fe1488893f26f8efd2f5e0805/pkg/sql/distsql_plan_join.go#L290)):*
> ```Go
> 	joinColMap := make([]int, len(n.columns))
> 	idx := 0
> 	leftOffset := 0
> ```

[nit] leftCols

---

*[pkg/sql/distsqlrun/processors.proto, line 214 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24697#-L9uXhK11ybQkvCTrcOw:-L9uXhK11ybQkvCTrcOx:b-u6k5ee) ([raw file](https://github.com/cockroachdb/cockroach/blob/12c09754b902384fe1488893f26f8efd2f5e0805/pkg/sql/distsqlrun/processors.proto#L214)):*
> ```protobuf
> //
> // If performing a lookup join on a = c (lookup columns is [0]), outputting a, b, c, e:
> //        Internal columns: | a | c | e |
> ```

isn't this a, b, c, d, e?

---

*[pkg/sql/logictest/testdata/logic_test/lookup_join, line 186 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24697#-L9uYS7HEzpz6kmmnxTE:-L9uYS7HEzpz6kmmnxTF:b-g2j5ug) ([raw file](https://github.com/cockroachdb/cockroach/blob/12c09754b902384fe1488893f26f8efd2f5e0805/pkg/sql/logictest/testdata/logic_test/lookup_join#L186)):*
> ```
> SELECT "URL" FROM [EXPLAIN (DISTSQL) SELECT DISTINCT(authors.name) FROM authors, books AS b1, books AS b2 WHERE b1.title = b2.title AND authors.book = b1.title AND b1.shelf <> b2.shelf]
> ----
> https://cockroachdb.github.io/distsqlplan/decode.html?eJysk09rMjEQh-_vp5A5KeQF95-HhUIOPdRStEhvxUPcTDV1zSxJFlrE716ye9BdulGhxyTzzPOb0T2CJokLcUAL-TtEwCCDNYPKUIHWkvHXbdFcfkE-ZaB0VTt_vWZQkEHIj-CUKxFyWNB_qoCBRCdU2RSdGFDtzoh1YouQz07som0UbvsmNiWuUEg0neZQGXUQ5puL2u18VgbL2uUjHjEew5A6-lP1hmjfESeD4vge8TMpfYv3hWhfV6NPUnpE2kfobIHxhPGU8WwwVTKY6hym1mQkGpT93_Z6yS-jPQm78-P1Ryvxw415PHkwartzYx5NzqMMxk_vWeqjsk7pwnW9ge5Zp_uVf_8KbUXa4k0fwNRvBuUW201bqk2Br4aKRtMelw3XXEi0rn2dtYe5bp98wEs4CsJpB476cByEk7A5ucMc9-E0CGdhcxaEpz14ffr3EwAA__9Ts6Lr
> ```

This change is in the wrong direction (probably because of the Omitted thing). It looks like we should only need to output `@1` here; what is missing to make that happen? Looking at the `setNeededColumns` code, we should be marking everything but that as omitted.. It would help if the testcase below was `EXPLAIN (VERBOSE)` so we could see this information.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24697)*

**Comment by pbardea** [comment]
Review status: 0 of 6 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsql_physical_planner.go, line 1796 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24697#-L9uWk-AAuP70pXxZC6U:-L9utpNv1hKVoNxWO3hP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/12c09754b902384fe1488893f26f8efd2f5e0805/pkg/sql/distsql_physical_planner.go#L1796)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

we're allocating the rightMap for nothing in this case. I'd move the `make` call inside the other branch
</blockquote></details>

Done.

---

*[pkg/sql/distsql_plan_join.go, line 257 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24697#-L9uZDbe8wx6O78618VI:-L9uvp6I1n7gwlVzchbb:b-uk2fnm) ([raw file](https://github.com/cockroachdb/cockroach/blob/03998395b31bd2af3c94ecd00d6ebc8993d76d5c/pkg/sql/distsql_plan_join.go#L257)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Why are we adding omitted columns now? These are columns that are not actually needed after the join, so we shouldn't be producing them.
</blockquote></details>

Done. Makes sense now.

---

*[pkg/sql/distsql_plan_join.go, line 257 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24697#-L9uX6fiEnay-Jab9Nbo:-L9utpzn6csWVv6EfUcy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/12c09754b902384fe1488893f26f8efd2f5e0805/pkg/sql/distsql_plan_join.go#L257)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] `leftCols`
</blockquote></details>

Done.

---

*[pkg/sql/distsql_plan_join.go, line 290 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24697#-L9uXK9q8S3NqEz0hGzx:-L9utqQtBp7v1aH7ptvt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/12c09754b902384fe1488893f26f8efd2f5e0805/pkg/sql/distsql_plan_join.go#L290)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] leftCols
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/processors.proto, line 214 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24697#-L9uXhK11ybQkvCTrcOw:-L9uthvh2oCJDYzyoeWm:bngnjfl) ([raw file](https://github.com/cockroachdb/cockroach/blob/12c09754b902384fe1488893f26f8efd2f5e0805/pkg/sql/distsqlrun/processors.proto#L214)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

isn't this a, b, c, d, e?
</blockquote></details>

Indeed and it shouldn't depend on what is being outputted. Updated.

---

*[pkg/sql/logictest/testdata/logic_test/lookup_join, line 186 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24697#-L9uYS7HEzpz6kmmnxTE:-L9uw3CI28iBdFMMEVww:b-8ipmmc) ([raw file](https://github.com/cockroachdb/cockroach/blob/12c09754b902384fe1488893f26f8efd2f5e0805/pkg/sql/logictest/testdata/logic_test/lookup_join#L186)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This change is in the wrong direction (probably because of the Omitted thing). It looks like we should only need to output `@1` here; what is missing to make that happen? Looking at the `setNeededColumns` code, we should be marking everything but that as omitted.. It would help if the testcase below was `EXPLAIN (VERBOSE)` so we could see this information.
</blockquote></details>

Changed it back. Also added an `EXPLAIN (VERBOSE)` test case below.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24697)*

**Comment by RaduBerinde** [comment]
:lgtm_strong:   Thanks!

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsql_plan_join.go, line 290 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24697#-L9uXK9q8S3NqEz0hGzx:-L9uyJNr3UM5eb6FPiu-:bpzufcj) ([raw file](https://github.com/cockroachdb/cockroach/blob/12c09754b902384fe1488893f26f8efd2f5e0805/pkg/sql/distsql_plan_join.go#L290)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Doesn't look like it was changed

---

*[pkg/sql/logictest/testdata/logic_test/lookup_join, line 186 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24697#-L9uYS7HEzpz6kmmnxTE:-L9uyS4j-meNrniW9_SH:bmi8ppe) ([raw file](https://github.com/cockroachdb/cockroach/blob/12c09754b902384fe1488893f26f8efd2f5e0805/pkg/sql/logictest/testdata/logic_test/lookup_join#L186)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Changed it back. Also added an `EXPLAIN (VERBOSE)` test case below.
</blockquote></details>

:100: 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24697#-:-L9uyYNYEJMCX7S7Nem_:b-rc30b)*

**Comment by pbardea** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/distsql_plan_join.go, line 290 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24697#-L9uytIh4enRMY6CJVip:-L9uytIh4enRMY6CJViq:bjwoneu) ([raw file](https://github.com/cockroachdb/cockroach/blob/12c09754b902384fe1488893f26f8efd2f5e0805/pkg/sql/distsql_plan_join.go#L290)):*
> Doesn't look

---

*[pkg/sql/distsql_plan_join.go, line 290 at r3](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24697#-L9uXK9q8S3NqEz0hGzx:-L9uzSwz2HGdcxQPYNl8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/12c09754b902384fe1488893f26f8efd2f5e0805/pkg/sql/distsql_plan_join.go#L290)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Doesn't look like it was changed
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24697)*

**Comment by RaduBerinde** [comment]
Reviewed 1 of 6 files at r3, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24697)*

**Comment by pbardea** [comment]
Thanks for the review Radu!
bors r+

**Pull request merged**
