### PR TITLE
cli: default to num procs concurrency in debug compact

### PR DESCRIPTION
**Pull request by jbowens**
**cli: remove OpenExistingStore**

Remove OpenExistingStore, replacing its call sites with calls to OpenEngine,
including the storage.MustExist config option.

**cli: default to num procs concurrency in debug compact**

Now that some concurrency within manual offline compactions is possible,
default to a max compaction concurrency equal to the number of
processors during offline manual compactions. Add a new
`--max-concurrency` flag to the debug compact command to override this
default.

The undocumented `COCKROACH_ROCKSDB_CONCURRENCY` environment variable
will no longer affect the maximum concurrency for this offline
compaction. That environment variable is intended for controlling
compaction concurrency for a running CockroachDB node. The switch to an
explicit flag for this command makes the concurrency control more
discoverable (it appears within the command help output) and allows for
the more reasonable default concurrency in this context.

Release note (cli change): Changes the default `debug compact`
maximum compaction concurrency to the number of processors, and adds a
`--max-concurrency` flag for overriding the new default.

### CODE REVIEW

**Review by jbowens — COMMENTED** [review]
I'm hoping to backport this to 22.1 in time for the .1 release. I don't think it's important to get it into .0.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78987#-:-MzMUUXv1YAeRbDNJl1g:bz3e590)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by mufeez-amjad — APPROVED** [review]
:lgtm: - missed the max concurrency change in my PR, thank you for circling back and adding it

> Reviewed 5 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78987#-:-MzMZWwnDLgxEp2UehB5:bxv6jyh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens)

**Review by nicktrav — APPROVED** [review]
:lgtm:

The second commit looks like something that's worthy of going in to the major release (i.e. `.0`), given that we're making a "breaking change" to the debug tool (no longer using the env var). Not sure what precedent would dictate here about these types of changes.

> Reviewed 6 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78987#-:-MzMpamFDL2ZvaxkpELI:b-fa6tth)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @jbowens)

**Review by jbowens — COMMENTED** [review]
@nicktrav I _think_ it's okay for the point release, because `debug compact` is an undocumented command: https://www.cockroachlabs.com/docs/stable/cockroach-commands.html and the `COCKROACH_ROCKSDB_CONCURRENCY` environment variable is an undocumented env var.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78987#-:-MzVpdxCAYwURbUY8BcQ:b2gqtns)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @jbowens)

**Review by nicktrav — APPROVED** [review]
:ship: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78987#-:-MzVs-pT6zaaP5hvea5T:bjj6nav)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @jbowens)

**Comment by jbowens** [comment]
TFTRs!

bors r+

**Pull request merged**
