### PR TITLE
sql/parser: reduce the overhead for parsing simple expressions.

### PR DESCRIPTION
**Pull request by knz**
Prior to this patch, all simple expressions were parsed as a SELECT
clause. This patch changes this logic to use a SET statement
instead. This reduces the overhead from ~15 to 2 allocations.

Moreover groups of CHECK and DEFAULT expressions are now processed
just once through the parser.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7333)

### CODE REVIEW

**Comment by knz** [comment]
cc @petermattis @nvanbenschoten

**Comment by knz** [comment]
(Found while investigating #6745)

**Comment by petermattis** [comment]
:lgtm:, though I wonder if there is something better than `SET DATA`. Perhaps `SET ROW (expr_list)` to match up with the `ROW` syntax. (See the `explicit_row` rule).

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/parser/sql.y, line 1090 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7333#-KKjBFgNdX2mClkuqMNa:-KKjBFgNdX2mClkuqMNb:658223070) ([raw file](https://github.com/cockroachdb/cockroach/blob/f63d04ae7219a32d954ebf58fd71c38cbc82714f/sql/parser/sql.y#L1090)):*
> ```Yacc
> 
> set_exprs_internal:
>   SET DATA expr_list
> ```

`DATA` is a somewhat strange keyword to be using here. This deserves a comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7333#-:-KKjByHcnJDJoJFc1ApH:-169441393)*

**Comment by knz** [comment]
Done, using SET ROW instead.

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/parser/sql.y, line 1090 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7333#-KKjBFgNdX2mClkuqMNa:-KKjFm6d51cODN6iJkTR:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/f63d04ae7219a32d954ebf58fd71c38cbc82714f/sql/parser/sql.y#L1090)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `DATA` is a somewhat strange keyword to be using here. This deserves a comment
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7333#-:-KKjFjKReiCl00PKnyZ-:-957971545)*

**Comment by petermattis** [comment]
Reviewed 8 of 8 files at r1.
Review status: 4 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/parser/expr_test.go, line 124 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7333#-KKjHQ-he30euhGC1Mvn:-KKjHQ-iW9g7tNuuXGAk:81636400) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c2ee4b25c5bd37567860586612727fde48ec8de/sql/parser/expr_test.go#L124)):*
> ```Go
> 
> 	for _, tc := range testCases {
> 		stmt, err := ParseOneTraditional("SELECT " + tc.in)
> ```

Why did this need to change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7333)*

**Comment by knz** [comment]
Review status: 4 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/parser/expr_test.go, line 124 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7333#-KKjHQ-he30euhGC1Mvn:-KKjKB6tI0SFEPo7ey9k:941829723) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c2ee4b25c5bd37567860586612727fde48ec8de/sql/parser/expr_test.go#L124)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Why did this need to change?
</details>
Because the test also wants to check that "*" (starDatum) gets normalized. However "*" is not a valid expr in the grammar; it is merely a valid target_expr for SELECT.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7333)*

**Comment by knz** [comment]
Review status: 4 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/parser/expr_test.go, line 124 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7333#-KKjHQ-he30euhGC1Mvn:-KKjKZFZAImi_w9LWL8x:-689235575) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c2ee4b25c5bd37567860586612727fde48ec8de/sql/parser/expr_test.go#L124)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Because the test also wants to check that "*" (starDatum) gets normalized. However "*" is not a valid expr in the grammar; it is merely a valid target_expr for SELECT.
</details>
I meant `"*"`, boo on MarkDown.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7333)*

**Pull request merged**
