### PR TITLE
*: Insignificant miscellaneous cleanups

### PR DESCRIPTION
**Pull request by a-robinson**
Fix some typos around the code base and remove an unused method parameter.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9847)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 12 of 12 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[gossip/info.go, line 19 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9847#-KTjlnGxm0F78u6dSxTt:-KTjlnGxm0F78u6dSxTu:b-mk7rj4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca0bc9a99187691dcd837c29ff97dc1bda785acd/gossip/info.go#L19)):*
> ```Go
> package gossip
> 
> // expired returns true if the info's time to live (TTL) has expired.
> ```

s/the info's// or just remove this comment altogether since it doesn't seem to be useful.

---

*[sql/schema_changer.go, line 148 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9847#-KTjlwMG2jaNhanHJifK:-KTjlwMG2jaNhanHJifL:b-2bzer1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca0bc9a99187691dcd837c29ff97dc1bda785acd/sql/schema_changer.go#L148)):*
> ```Go
> }
> 
> // ReleaseLease releases the table lease if it is the one registered with
> ```

does this need re-wrapping?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9847#-:-KTjm9ORcHjgEE805x0r:bnfp4nl)*

**Comment by a-robinson** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[gossip/info.go, line 19 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9847#-KTjlnGxm0F78u6dSxTt:-KTk-aMyGEX_lNBscOXV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca0bc9a99187691dcd837c29ff97dc1bda785acd/gossip/info.go#L19)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> s/the info's// or just remove this comment altogether since it doesn't seem to be useful.
</details>
Done.

---

*[sql/schema_changer.go, line 148 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9847#-KTjlwMG2jaNhanHJifK:-KTk-dMdcK8akLxoT_wH:b-3qvkc1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca0bc9a99187691dcd837c29ff97dc1bda785acd/sql/schema_changer.go#L148)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> does this need re-wrapping?
</details>
No, the line is only 73 characters long

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9847)*

**Comment by tamird** [comment]
Reviewed 1 of 3 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/schema_changer.go, line 148 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9847#-KTjlwMG2jaNhanHJifK:-KTkBRrvjIWwsxRbY_pA:bday9b4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca0bc9a99187691dcd837c29ff97dc1bda785acd/sql/schema_changer.go#L148)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary>
> No, the line is only 73 characters long
</details>
so...wouldn't `the` fit on it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9847)*

**Comment by a-robinson** [comment]
Review status: 10 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/schema_changer.go, line 148 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9847#-KTjlwMG2jaNhanHJifK:-KTkCf1YEwvsL-Nnllls:b-bpcdfd) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca0bc9a99187691dcd837c29ff97dc1bda785acd/sql/schema_changer.go#L148)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> so...wouldn't `the` fit on it?
</details>
Yes, but I didn't realize we cared about wrapping so precisely? There are tons of comments throughout the repo that wrap before they need to.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9847)*

**Comment by tamird** [comment]
It's optional, but many people re-wrap comments when they encounter them
(and especially when acquiring the git-blame).

**Pull request merged**
