### PR TITLE
colexec: fix performance inefficiency in materializer

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: fix performance inefficiency in materializer**

We mistakenly were passing `sqlbase.DatumAlloc` by value, and not by
pointer, and as a result we would always be allocating 16 datums but
using only 1 - i.e. we were not only not pooling the allocations, but
actually making a bunch of useless allocations as well.

This inefficiency becomes noticeable when the vectorized query returns
many rows and when we have wrapped processors and those processors get
a lot of input rows - in all cases when we need to materialize a lot.
For example, TPC-H query 16 sees about 10% improvement (it returns 18k
rows) and TPC-DS query 6 sees 2x improvement (it has wrapped hash
aggregator with a decimal column) with this fix.

Release note (performance improvement): A performance inefficiency has
been fixed in the vectorized execution engine which results in speed ups
on all queries when run via the vectorized engine, with most noticeable
gains on the queries that output many rows.

**sqlbase: prohibit copying DatumAlloc by value**

This commit adds `_ util.NoCopy` to `DatumAlloc` struct to prevent us
from misusing it. A few places failed the linter, and those have been
addressed, but there was no performance problems AFAICT due to the
removed copies by value.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
For some context, I noticed this on `tpcdsvec` run:
```
09:05:28 test.go:190: test status: [q6] took about 57.07s to run on both configs
09:05:28 test.go:190: test status: WARNING: suboptimal plan when stats are present
no stats: 22.05s	with stats: 57.07s
```
so I looked into query 6, and it would run in like 15 seconds with `vectorize=off` but in 28 seconds with `vectorize=on`.

Here is what showed up in the profile
Screen Shot 2020-05-10 at 5 19 05 PM
and with this fix it runs in about 15 seconds as well with `vectorize=on`.

**Comment by jordanlewis** [comment]
LGTM! Nice find! (I guess there are some problems w/ nocopy, but this is great)

**Comment by yuzefovich** [comment]
Yeah, my second commit was WIP - I was lazy to run the linter myself, and now I updated the second commit to appease the linter (nothing bad was shaken out, but I think it is beneficial to have `util.NoCopy` in `DatumAlloc`). Also, I think we should backport the first commit to 20.1 and 19.2.

RFAL.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48669#-:-M78AZxq5pkko-neeOxz:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
