### PR TITLE
sql: Rename types.ColumnType to types.T and delete VisibleType (patch 11/)

### PR DESCRIPTION
**Pull request by knz**
Split from #36598 cc @andy-kimball 

Remove the "type T = ColumnType" alias by renaming ColumnType to T. Now
there is just one way to refer to SQL types in the system: types.T, which
should reduce confusion.

Also delete VisibleType, since it's no longer used, except for mapping
to/from the legacy ColumnType representation.

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
(but don't merge this directly)

**Review by knz — COMMENTED** [review]
:lgtm:

> Reviewed 133 of 133 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36708#-:-Lc6BA6M1jZ8PGLN6VlZ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/sqlbase/index_encoding.go, line 213 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36708#-Lc6Ar1UBimMyCDYRniz:-Lc6Ar1VDEyIhZvoy7ik:bas04xp) ([raw file](https://github.com/cockroachdb/cockroach/blob/9150107df3fc71bacbc9e1e8fafab78e4eb32440/pkg/sql/sqlbase/index_encoding.go#L213)):*
> ```Go
> 	keyPrefix []byte,
> 	values EncDatumRow,
> 	types []types.T,
> ```

Please create a follow-up issue (and ping the SQL team) that the APIs in this file needs to be reworked to use `[]*types.T` instead.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36708)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @knz)

___
*[pkg/sql/sqlbase/index_encoding.go, line 213 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36708#-Lc6Ar1UBimMyCDYRniz:-LcJt0h90QLQibImsJAr:bxlfgna) ([raw file](https://github.com/cockroachdb/cockroach/blob/9150107df3fc71bacbc9e1e8fafab78e4eb32440/pkg/sql/sqlbase/index_encoding.go#L213)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please create a follow-up issue (and ping the SQL team) that the APIs in this file needs to be reworked to use `[]*types.T` instead.
</blockquote></details>

I'm not convinced they should be. These arrays of types are used by DistSQL. There might be performance impact to sending arrays of pointers around the cluster, since un-marshaling these arrays will lead to a lot individual objects being created. Also, it'd probably be a lot of work for what would likely bring no gains. If you still feel like something should be done, I think it'd be better for you to file the issue, since I'm not yet convinced.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36708)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @knz)

___
*[pkg/sql/sqlbase/index_encoding.go, line 213 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36708#-Lc6Ar1UBimMyCDYRniz:-LcfOcWBEpfjnW6hGbLo:b-h4lqsg) ([raw file](https://github.com/cockroachdb/cockroach/blob/9150107df3fc71bacbc9e1e8fafab78e4eb32440/pkg/sql/sqlbase/index_encoding.go#L213)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I'm not convinced they should be. These arrays of types are used by DistSQL. There might be performance impact to sending arrays of pointers around the cluster, since un-marshaling these arrays will lead to a lot individual objects being created. Also, it'd probably be a lot of work for what would likely bring no gains. If you still feel like something should be done, I think it'd be better for you to file the issue, since I'm not yet convinced.
</blockquote></details>

On second thought, I find myself agreeing. You can leave as-is.

**Pull request closed without merging**
