### PR TITLE
doc:Add design document in Chinese.

### PR DESCRIPTION
**Pull request by EamonZhang**
This document may useful for Chinese people.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13445)

### CODE REVIEW

**Comment by andreimatei** [comment]
Hi @EamonZhang! This is a great contribution, thank you!

We've discussed this briefly; unfortunately not many people here can actually review your text, which also means that we can't maintain it, so I don't think that having it as a regular file in the repo is the best option.
I think a better place for it would be on our github wiki: https://github.com/cockroachdb/cockroach/wiki
Would you mind putting it there, in a new page? Everybody can edit the wiki at the moment. That way other people can edit it more easily. If you do this, I'll link to it from the english design doc and other places.
And if you don't mind, please add a note at the top of the text listing your name as "originally translated by" (or whatever you think is appropriate) and state that the document is maintained by the community, not by the Cockroach Labs team.

Does this work?

Thanks again!

**Comment by jseldess** [comment]
Hi @EamonZhang, we discussed this further and would like to suggest a different approach: 

Instead of adding your translation to the cockroach repo or wiki, we'd like you to host it in your own repo and we'll link to it from the cockroach repo and from our user documentation. 

Does that work for you?

**Comment by EamonZhang** [comment]
Hi  @jseldess  It is OK to me. Thanks!

**Comment by jseldess** [comment]
Thanks, @EamonZhang. I'll close this PR. Once you have your final location for the translation, please post the link here and I'll add it to our repo and docs.

**Comment by EamonZhang** [comment]
Hi @jseldess 

New place for the document, it is Chinese and English version.

https://bodani.github.io/docs/cockroach/design.html

Thanks

**Pull request closed without merging**
