### PR TITLE
server, ui: fix the raft debug page

### PR DESCRIPTION
**Pull request by d4l3k**
- Adds 3s timeout when calling Ranges rpc from /_status/raft.
- Parallelize Ranges rpc calls.
- Make it clearer in the UI the difference between loading and not having any
  results.

Mitigates #8079.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8546)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[server/status.go, line 573 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8546#-KPECW0q4ttkfwQqVI9K:-KPECW0q4ttkfwQqVI9L:b-b5164h) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1a703c7d5529480b183700187ec14406d4abb9c/server/status.go#L573)):*
> ```Go
> 	// Parallelize fetching of ranges to minimize total time.
> 	var wg sync.WaitGroup
> 	ctx, cancel := context.WithTimeout(ctx, base.NetworkTimeout)
> ```

Hm, I'm pretty sure there's a way to pass the timeout via grpc-gateway, so that it can be controlled from the UI. Can you look into that?

---

*[server/status.go, line 604 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8546#-KPECB29ZA2pme6xWT4S:-KPECB29ZA2pme6xWT4T:b-f3vfx5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1a703c7d5529480b183700187ec14406d4abb9c/server/status.go#L604)):*
> ```Go
> 		}()
> 	}
> 	// After this wait there is only this goroutine accessing mu.resp.
> ```

Seems clearer just to acquire the lock.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8546)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[server/status.go, line 573 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8546#-KPEKKbOIiira799A2KU:-KPEKKbOIiira799A2KV:b-474zt1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1a703c7d5529480b183700187ec14406d4abb9c/server/status.go#L573)):*
> ```Go
> 	// Parallelize fetching of ranges to minimize total time.
> 	var wg sync.WaitGroup
> 	ctx, cancel := context.WithTimeout(ctx, base.NetworkTimeout)
> ```

I think the individual requests may be taking longer than 3s because of locking issues. We should make the timeout 30s both here and in the UI. 

---

*[server/status.go, line 582 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8546#-KPEKdWNEq2vIXD_1gSs:-KPEKdWOoiy4kqkZpOjQ:bbcdufw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1a703c7d5529480b183700187ec14406d4abb9c/server/status.go#L582)):*
> ```Go
> 			ranges, err := s.Ranges(ctx, &serverpb.RangesRequest{NodeId: nodeID.String()})
> 			if err != nil {
> 				log.Infof(ctx, "Failed to get ranges from %d: %q", nodeID, err)
> ```

This should put some indication of failure into the response. 

---

*[ui/app/containers/raftRanges.tsx, line 211 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8546#-KPEK36G4oGJ3DHEwNLt:-KPEK36G4oGJ3DHEwNLu:bc6n1nn) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1a703c7d5529480b183700187ec14406d4abb9c/ui/app/containers/raftRanges.tsx#L211)):*
> ```XML
>       }
>     } else {
>       content = <div className="section">Loading...</div>;
> ```

This also needs an error indicator if it fails to load. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8546#-:-KPEKxu3o8Iil1pcfjg5:bnfp4nl)*

**Comment by maxlang** [comment]
LGTM but might be worth upping the timeout in `api.ts` as well?

**Comment by tamird** [comment]
@maxlang can you change the `timeout` function in `api.ts` so that it sets the `Grpc-Timeout` header? That is supported by grpc-gateway as a way of propagating the timeout into the handler.

**Comment by maxlang** [comment]
Sure, just make an issue for it.

**Comment by maxlang** [comment]
@d4l3k 

You can add the header to `api.ts` for now, and make an issue and assign it to me to make the timeout flexible.

```
...
    headers: {
      "Accept": "application/x-protobuf",
      "Content-Type": "application/x-protobuf",
      "Grpc-Timeout": TIMEOUT,
    },
...
```

**Comment by d4l3k** [comment]
Added.

---

Review status: 1 of 9 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[server/status.go, line 573 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8546#-KPECW0q4ttkfwQqVI9K:-KPEJTU3dDuV5816RMUf:b-fjny5z) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1a703c7d5529480b183700187ec14406d4abb9c/server/status.go#L573)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Hm, I'm pretty sure there's a way to pass the timeout via grpc-gateway, so that it can be controlled from the UI. Can you look into that?
</details>
Apparently you just set the `Grpc-Timeout` header.

https://github.com/grpc-ecosystem/grpc-gateway/blob/9b71cfe3e13976ec408aad6a3df389b0beef358a/runtime/context.go#L41

Added.

---

*[server/status.go, line 573 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8546#-KPEKKbOIiira799A2KU:-KPEaeS1zvkkxrJQyFxZ:bvnmbyc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1a703c7d5529480b183700187ec14406d4abb9c/server/status.go#L573)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> I think the individual requests may be taking longer than 3s because of locking issues. We should make the timeout 30s both here and in the UI. 
</details>
Done. Have to subtract base.NetworkTimeout from the passed in deadline in order to have time to return results.

---

*[server/status.go, line 582 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8546#-KPEKdWNEq2vIXD_1gSs:-KPEavLF60IUHnMuCzkA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1a703c7d5529480b183700187ec14406d4abb9c/server/status.go#L582)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> This should put some indication of failure into the response. 
</details>
Done.

---

*[server/status.go, line 604 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8546#-KPECB29ZA2pme6xWT4S:-KPEM-dYuCqC5nuJbEz_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1a703c7d5529480b183700187ec14406d4abb9c/server/status.go#L604)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Seems clearer just to acquire the lock.
</details>
Done.

---

*[ui/app/containers/raftRanges.tsx, line 211 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8546#-KPEK36G4oGJ3DHEwNLt:-KPEgvwGxxMRIIvf7cBq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1a703c7d5529480b183700187ec14406d4abb9c/ui/app/containers/raftRanges.tsx#L211)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> This also needs an error indicator if it fails to load. 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8546#-:-KPEgzfug8srMH8HB9_D:bqmjwcz)*

**Comment by tamird** [comment]
Reviewed 8 of 9 files at r2.
Review status: 8 of 9 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[server/status.go, line 592 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8546#-KPEineEwaXGlqMJQIKZ:-KPEineEwaXGlqMJQIK_:b-stxreb) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a1a3768f694bc5d49f8edb233ae5c117a8ca862/server/status.go#L592)):*
> ```Go
> 			if err != nil {
> 				err := errors.Wrapf(err, "failed to get ranges from %d", nodeID)
> 				log.Info(ctx, err)
> ```

no need to log now that the error is being returned.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8546)*

**Comment by d4l3k** [comment]
Review status: 7 of 9 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[server/status.go, line 592 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8546#-KPEineEwaXGlqMJQIKZ:-KPEkYGsulU3KT27gPHU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a1a3768f694bc5d49f8edb233ae5c117a8ca862/server/status.go#L592)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> no need to log now that the error is being returned.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8546)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: 8 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8546)*

**Comment by d4l3k** [comment]
@tamird, @maxlang LGTY?

**Comment by bdarnell** [comment]
LGTM

---

Review status: 8 of 9 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[server/status.go, line 573 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8546#-KPEKKbOIiira799A2KU:-KPF--xBaUwIB7EyO3vq:b1p0s33) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1a703c7d5529480b183700187ec14406d4abb9c/server/status.go#L573)):*
<details><summary><i>Previously, d4l3k (Tristan Rice) wrote…</i></summary>
> Done. Have to subtract base.NetworkTimeout from the passed in deadline in order to have time to return results.
</details>
The subtraction should have a floor; this will make any attempt to use a 3-second timeout immediately fail because there won't be enough time left.  Or maybe it's better to use a fraction of the allowable deadline (80%?) instead of a fixed subtraction.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8546#-:-KPF1OZkN3hcBucjbGcP:bb6ywmx)*

**Comment by d4l3k** [comment]
*[server/status.go, line 573 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8546#-KPEKKbOIiira799A2KU:-KPJ2THCdN9aeDOBSzXc:b-vetmfs) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1a703c7d5529480b183700187ec14406d4abb9c/server/status.go#L573)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> The subtraction should have a floor; this will make any attempt to use a 3-second timeout immediately fail because there won't be enough time left.  Or maybe it's better to use a fraction of the allowable deadline (80%?) instead of a fixed subtraction.
</details>
Fractions don't really make any sense since the processing and network transport time will be more or less a fixed time. I'm also not sure why you'd be calling this with a tiny timeout anyways. You'd be running into errored results anyway due to remote timeouts.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8546)*

**Comment by tamird** [comment]
This appears to have broken generating embedded.go. I'm not sure how that snuck past CI.

**Comment by tamird** [comment]
This was some badness on my local machine, fixed via `git clean -dxf && go generate ./…`.

**Pull request merged**
