### PR TITLE
release-21.1: sessionphase: fix service latency computation in an error case

### PR DESCRIPTION
**Pull request by yuzefovich**
Backport 1/1 commits from #72493.

/cc @cockroachdb/release

---

If we encounter an error during the logical planning, then the end
execution phase is never set. Previously, we would use that unset value
in order to compute the latency of planning and execution and would get
a negative result. This is now fixed.

Release note: None

Release justification: low-risk fix to a low impact bug.

### CODE REVIEW

**Comment by yuzefovich** [comment]
Friendly ping @maryliag @Azhng

**Review by maryliag — APPROVED** [review]
Don't forget to add a Release justification :) 
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72543#-:-MooNoqu6jwq0t6G9_Qi:bk9zd0v)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng)

**Comment by yuzefovich** [comment]
Are release justifications required? I thought we only needed them during the stabilization period after branch for a new release is cut.

**Comment by maryliag** [comment]
Oh I though they were required for _all_ backports, that is why we have the blathers/backport-check (that is currently failing on this PR)

**Comment by yuzefovich** [comment]
Indeed, I think this changed several months ago, and I never noticed.

**Comment by yuzefovich** [comment]
Hm, so the blathers is happy if I add the justification into the PR description, but then it doesn't go into the git log. I guess it just serves as a nudge to consider whether the backport is worth it or not.

**Pull request merged**
