### PR TITLE
sql/parser: Create AnnotateTypeExpr to annotate expression types

### PR DESCRIPTION
**Pull request by nvb**
See https://github.com/cockroachdb/cockroach/pull/6895.

This change is the initial implementation of type annotations. It adds
support for the expression type and demonstrates its effect on type
checking. Later commits add support for the effect of type annotations
on placeholders, and improve normalization over type annotations.

**Note:** For now this change is using a temporary shorthand syntax `!` for
type annotations, but this "placeholder" syntax is commented out in the last
commit so that it will be easy to add in the new syntax once one is decided 
upon.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7083)

### CODE REVIEW

**Comment by knz** [comment]
Reviewed 10 of 10 files at r1.
Review status: 3 of 13 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[sql/parser/expr.go, line 1163 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7083#-KJqCfg6HTXojOWPbSOR:-KJqCfg7ElJi2paKCB_Z:-193159353) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eb5eb6af8421a003fd96be6c91b25c76dc9da75/sql/parser/expr.go#L1163)):*
> ```Go
> 	Type ColumnType
> 
> 	typeAnnotation
> ```

I am not too happy seeing both a Type field and a typeAnnotation, knowing that *by definition* they will always be the same. Can't we skip the typeAnnotation for this struct?

---

*[sql/parser/keywords.go, line 13 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7083#-KJqCu9XDsMvCiONMfR9:-KJqCu9ZojhCcrsS5Yak:1247538769) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eb5eb6af8421a003fd96be6c91b25c76dc9da75/sql/parser/keywords.go#L13)):*
> ```Go
> 	"ANALYZE":           ANALYZE,
> 	"AND":               AND,
> 	"ANNOTATE_TYPE":     ANNOTATE_TYPE,
> ```

This does not need to be a keyword. 

---

*[sql/parser/sql.y, line 3200 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7083#-KJqDds8OixzcgeguEfM:-KJqDdsA5t7yV7t7Qu8U:-1899201133) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eb5eb6af8421a003fd96be6c91b25c76dc9da75/sql/parser/sql.y#L3200)):*
> ```Yacc
>     $$.val = &CastExpr{Expr: $1.expr(), Type: $3.colType()}
>   }
> | b_expr '!' typename
> ```

If you intend to leave this  syntax when this PR is merged and there is no consensus yet as to whether we want to keep it, please also add the necessary comment to avoid its inclusion in the documentation.

---

*[sql/parser/type_check.go, line 262 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7083#-KJqECDx0KbER5C6tdKd:-KJqECDznOG3pTKnZQJC:-325087618) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eb5eb6af8421a003fd96be6c91b25c76dc9da75/sql/parser/type_check.go#L262)):*
> ```Go
> 	expr.Expr = subExpr
> 	expr.typ = subExpr.ReturnType()
> 	return expr, nil
> ```

See my comment above about the struct definition. I think this function could be 3 lines shorter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7083)*

**Comment by knz** [comment]
Reviewed 3 of 3 files at r2.
Review status: 5 of 13 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[sql/parser/type_check.go, line 995 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7083#-KJqEeNphomM0ElamReM:-KJqEeNqoXP5o9i_7zQW:717610515) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac33fd4f424a5d4d2d4ad5073d401808a723a1fa/sql/parser/type_check.go#L995)):*
> ```Go
> 	case *AnnotateTypeExpr:
> 		if arg, ok := t.Expr.(Placeholder); ok {
> 			assertType := t.annotationType()
> ```

Since "Type" is an exported field of that struct, not sure a method "annotationType" is really needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7083)*

**Comment by knz** [comment]
Reviewed 3 of 3 files at r3.
Review status: 7 of 13 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7083)*

**Comment by knz** [comment]
Reviewed 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7083)*

**Comment by nvanbenschoten** [comment]
Review status: 3 of 13 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[sql/parser/expr.go, line 1163 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7083#-KJqCfg6HTXojOWPbSOR:-KJw6r55dEycY7H9pRlZ:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eb5eb6af8421a003fd96be6c91b25c76dc9da75/sql/parser/expr.go#L1163)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> I am not too happy seeing both a Type field and a typeAnnotation, knowing that *by definition* they will always be the same. Can't we skip the typeAnnotation for this struct?
</details>
Done.

---

*[sql/parser/keywords.go, line 13 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7083#-KJqCu9XDsMvCiONMfR9:-KJwBx5BMcqvJxhBCBuJ:-1230482938) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eb5eb6af8421a003fd96be6c91b25c76dc9da75/sql/parser/keywords.go#L13)):*
These are `col_name_keyword`s, not reserved keywords. The comment below describes them. Other keywords in list list include `EXTRACT` and `OVERLAY`, so it seems like the correct place.

> // Column identifier --- keywords that can be column, table, etc names.
> //
> // Many of these keywords will in fact be recognized as type or function names
> // too; but they have special productions for the purpose, and so can't be
> // treated as "generic" type or function names.

---

*[sql/parser/sql.y, line 3200 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7083#-KJqDds8OixzcgeguEfM:-KJwA9eCqU6sCThiIW60:1873692466) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eb5eb6af8421a003fd96be6c91b25c76dc9da75/sql/parser/sql.y#L3200)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> If you intend to leave this  syntax when this PR is merged and there is no consensus yet as to whether we want to keep it, please also add the necessary comment to avoid its inclusion in the documentation.
</details>
Talked in person. Decided that this being commented out is fine.

---

*[sql/parser/type_check.go, line 262 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7083#-KJqECDx0KbER5C6tdKd:-KJwAQfur2r94TJS7Q4D:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eb5eb6af8421a003fd96be6c91b25c76dc9da75/sql/parser/type_check.go#L262)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> See my comment above about the struct definition. I think this function could be 3 lines shorter.
</details>
Done.

---

*[sql/parser/type_check.go, line 995 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7083#-KJqEeNphomM0ElamReM:-KJwASRlKWqB0-eVOCzX:1487990510) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac33fd4f424a5d4d2d4ad5073d401808a723a1fa/sql/parser/type_check.go#L995)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Since "Type" is an exported field of that struct, not sure a method "annotationType" is really needed.
</details>
`annotationType` is mapping a `ColumnType` to a `Datum` type.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7083)*

**Comment by knz** [comment]
Reviewed 2 of 3 files at r6, 2 of 3 files at r7, 6 of 6 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[sql/parser/expr.go, line 1184 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7083#-KK-BsoMqIqqGwQ7w8sE:-KK-BsoMqIqqGwQ7w8sF:1114513853) ([raw file](https://github.com/cockroachdb/cockroach/blob/6af733c791a2e5381a046c7c262f3035d453b77c/sql/parser/expr.go#L1184)):*
> ```Go
> 
> func (node *AnnotateTypeExpr) annotationType() Datum {
> 	typ, _ := colTypeToTypeAndValidArgTypes(node.Type)
> ```

Ok, no this doesn't work for me. This method is recomputing the Datum type every time it is called! I think the better solution is to:

1. set the Type field in AnnotateTypeExpr stuct to be of type Datum, not ColumnType
2. have the grammar rule in the parser call colTypeToTypeAndValidArgTypes just once
3. remove this method annotationType altogether
4. simplify the TypeCheck method further.

---

*[sql/parser/keywords.go, line 13 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7083#-KJqCu9XDsMvCiONMfR9:-KK-B7s0GcKzTj3spFXd:-270183659) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eb5eb6af8421a003fd96be6c91b25c76dc9da75/sql/parser/keywords.go#L13)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> These are `col_name_keyword`s, not reserved keywords. The comment below describes them. Other keywords in list list include `EXTRACT` and `OVERLAY`, so it seems like the correct place.
> 
> > // Column identifier --- keywords that can be column, table, etc names.
> > //
> > // Many of these keywords will in fact be recognized as type or function names
> > // too; but they have special productions for the purpose, and so can't be
> > // treated as "generic" type or function names.
</details>
Right, sorry for the misread.

---

*[sql/parser/type_check.go, line 262 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7083#-KJqECDx0KbER5C6tdKd:-KK-Cx0spCIqfnFZ5WZd:-1862657115) ([raw file](https://github.com/cockroachdb/cockroach/blob/7eb5eb6af8421a003fd96be6c91b25c76dc9da75/sql/parser/type_check.go#L262)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Done.
</details>
still one or two lines too long :) see my comment above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7083)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/parser/expr.go, line 1184 \[r8\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7083#-KK-BsoMqIqqGwQ7w8sE:-KK0IHqwWSVtnD2LZpmL:1243135909) ([raw file](https://github.com/cockroachdb/cockroach/blob/6af733c791a2e5381a046c7c262f3035d453b77c/sql/parser/expr.go#L1184)):*
I disagree. `ColumnType != (Type)Datum`. If we performed the mapping during parsing, then we would lose a lot of information. For instance, `AnnotateType(1, BIT)` would be printed as `AnnotateType(1, integer)`. That's why other expressions like `CastExpr` avoid this approach as well, and it's why you always see the parser working with `ColumnType`s instead of `Datum`s. 

Also, 

> recomputing the Datum type

is a single switch statement, so it's not expensive. Still, the reason I was using the `typeAnnotation` in the first place was to memoize this mapping! In addition, `typeAnnotation` also allows us to check if the annotation has been set, which implies that a `TypedExpr` is being used correctly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7083)*

**Comment by knz** [comment]
Ok then it's best to leave typeAnnotation in, like you did originally.

(For the record I am still not fond of preserving everything needed to print out the original query text. )

**Comment by knz** [comment]
LGTM

**Comment by knz** [comment]
I'm sorry for the earlier confusion / inconvenience. Is there anything I can help about this now?

**Comment by nvanbenschoten** [comment]
Ah no that's on me. I've still been trying to think of a good shorthand syntax for type annotations, and forget that I had set this up to stand on its own without one. I'll address that comment and merge this.

**Pull request merged**
