### PR TITLE
sql: automatically disable result buffering for sinkless changefeeds

### PR DESCRIPTION
**Pull request by knz**
Discussed on #34423.

This is limited in scope, but it will do in 19.1 where the feature is experimental anyway. In 19.2, bulk i/o will come into the CBO, and we can build a more robust solution there.

### CODE REVIEW

**Review by danhhz — COMMENTED** [review]
:lgtm: thanks! it's much nicer for the user to not have to worry about setting connection parameters. this means we should revert my results_buffer_size pgwire parameter PR before 19.1 gets cut, right?

nit on the commit message: i wouldn't mention bulk i/o. this is only turned on, and only will be turned on, for sinkless/pgwire/non-enterprise changefeeds

you should probably also include a release note

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35529#-:-L_PEBwV-L71cnfRdk7l:bw90kmr)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @danhhz, and @knz)

___
*[pkg/sql/conn_io.go, line 710 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35529#-L_PDrZj5SIaPdATSlAn:-L_PDrZj5SIaPdATSlAo:bcrxdpg) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f7aa354be0f20921a66460dad7d0ec12cfc229e/pkg/sql/conn_io.go#L710)):*
> ```Go
> 	RowsAffected() int
> 
> 	// DisableBuffering can be called during execution to cause the next
> ```

can you define "next results" more precisely in this comment please?
___
*[pkg/sql/plan.go, line 513 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35529#-L_PDiQ58pSAenCEU0BS:-L_PDiQ58pSAenCEU0BT:bx042hx) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f7aa354be0f20921a66460dad7d0ec12cfc229e/pkg/sql/plan.go#L513)):*
> ```Go
> 		} else if fn != nil {
> 			if avoidStreaming {
> 				p.curPlan.avoidBuffering = true
> ```

should be avoidBuffering, right? avoidStreaming sounds like it has the opposite semantics
___
*[pkg/sql/planhook.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35529#-L_PDkDN1eX68J6y1V-U:-L_PDkDN1eX68J6y1V-V:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f7aa354be0f20921a66460dad7d0ec12cfc229e/pkg/sql/planhook.go#L39)):*
> ```Go
> type planHookFn func(
> 	context.Context, tree.Statement, PlanHookState,
> ) (fn PlanHookRowFn, header sqlbase.ResultColumns, subplans []planNode, avoidStreaming bool, err error)
> ```

ditto

**Review by knz — COMMENTED** [review]
> this means we should revert my results_buffer_size pgwire parameter PR before 19.1 gets cut, right?

I don't see this to be true. IMHO this parameter is useful for testing/troubleshooting.

> nit on the commit message: i wouldn't mention bulk i/o. this is only turned on, and only will be turned on, for sinkless/pgwire/non-enterprise changefeeds

Done.

> you should probably also include a release note

Yes, agreed if only to say to people that `results_buffer_size` is not needed any more.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35529#-:-L_T64vt1K2Ya0B7XxVw:bz8q8ff)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei)

___
*[pkg/sql/conn_io.go, line 710 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35529#-L_PDrZj5SIaPdATSlAn:-L_T60Vy-E_wiCyp-_L7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f7aa354be0f20921a66460dad7d0ec12cfc229e/pkg/sql/conn_io.go#L710)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

can you define "next results" more precisely in this comment please?
</blockquote></details>

Done.
___
*[pkg/sql/plan.go, line 513 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35529#-L_PDiQ58pSAenCEU0BS:-L_T61w2C57rrv6JZImS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f7aa354be0f20921a66460dad7d0ec12cfc229e/pkg/sql/plan.go#L513)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

should be avoidBuffering, right? avoidStreaming sounds like it has the opposite semantics
</blockquote></details>

Done.
___
*[pkg/sql/planhook.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35529#-L_PDkDN1eX68J6y1V-U:-L_T62b88IRG935eeDXs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2f7aa354be0f20921a66460dad7d0ec12cfc229e/pkg/sql/planhook.go#L39)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Comment by knz** [comment]
failed on #35551 .

bors r+

**Pull request merged**
