### PR TITLE
sql: add square and cube root unary operators (|/ and ||/)

### LINKED ISSUE #47544: sql: implement square and cube root unary operators (|/ and ||/)
In Postgres, there are unary operators for square and cube root:

```
jordan=# select |/ 25.0;
 ?column?
----------
        5
(1 row)

jordan=# select ||/ 25.0;
     ?column?
------------------
 2.92401773821287
(1 row)
```

CockroachDB should gain support for these unary operators.

### PR DESCRIPTION
**Pull request by hueypark**
Fixes #47544

Release note (sql change): add square and cube root unary operators (|/ and ||/)

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

CC @yuzefovich if you want to take a quick look as well

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47680#-:-M5Nkdpn6j8hhAmMlQaS:b5jih3o)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by yuzefovich — COMMENTED** [review]
Very nice work! :lgtm: if edge cases (NULLs and NaNs) are handled correctly.

> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47680#-:-M5NoPtJ4oaFMw7nigqn:b6ax2l4)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @hueypark)

___
*[pkg/sql/logictest/testdata/logic_test/operator, line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47680#-M5NmwGY3aabZoW8FZof:-M5NmwGZ6fwLWfNeOfW7:b-7c975j) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fcc5ea2153223a83c5d8347ed6bf74fc1b845ae/pkg/sql/logictest/testdata/logic_test/operator#L7)):*
> ```
> 
> query error cannot take square root of a negative number
> SELECT |/ -1.0::float
> ```

I'd be curious to see test cases with `NULL`s and `NaN`s (not sure if those are applicable here though).

nit: I think this test belongs in `sem/tree/eval` folder.

**Review by hueypark — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47680#-:-M5OUtMY0U-z_PrioYYo:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @yuzefovich)

___
*[pkg/sql/logictest/testdata/logic_test/operator, line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47680#-M5NmwGY3aabZoW8FZof:-M5R_GifBc0Pga1BXDp6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fcc5ea2153223a83c5d8347ed6bf74fc1b845ae/pkg/sql/logictest/testdata/logic_test/operator#L7)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I'd be curious to see test cases with `NULL`s and `NaN`s (not sure if those are applicable here though).

nit: I think this test belongs in `sem/tree/eval` folder.
</blockquote></details>

Done.

**Review by yuzefovich — APPROVED** [review]
Thanks for your contribution!

bors r=raduberinde,yuzefovich

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47680#-:-M5SCbrM5bizMFeUB5_c:b-z06o7l)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Comment by yuzefovich** [comment]
Hey @hueypark, do you mind rebasing your PR on top of the current master? We have a fix for some infrastructure problems in there that we need to pick up before merging this.

**Comment by hueypark** [comment]
@yuzefovich Done!

**Comment by yuzefovich** [comment]
Thanks!

The build failure seems like a flake to me.

bors r=raduberinde,yuzefovich

**Pull request merged**
