### PR TITLE
release-23.1: testutils: automate maintenance of predecessor release information

### PR DESCRIPTION
**Pull request by renatolabs**
Backport 3/3 commits from #105231.

Up to this point, we have manually maintained a `predecessor_version.json`
file that maps each release series to the latest published
release of the predecessor series. This information is then used
by tests in mixed-version and upgrade contexts.

With the end goal of testing upgrades that do not use the latest
published version, this commit enriches the release information file
to also include which releases have been _withdrawn_. With that
information, the test harness can choose any patch release of the
predecessor release series excluding withdrawn releases, which could
lead to undesired flakes and noise.

In summary, the following changes are made:

* replacement of `predecessor_version.json` file for
`cockroach_releases.yaml`. The new file includes which releases have
been withdrawn.
* automation of the process of keeping `cockroach_releases.yaml`
up to date. The docs team already maintains all this information in a
structured format [1], so we leverage that here.
* Predecessor logic is moved from `pkg/util` to `pkg/testutils`, where
it makes more sense, since that code is only used in tests.
* Introduction of `RandomPredecessor` and `RandomPredecessorHistory`,
which make use of the new data file to pick a random non-withdrawn
predecessor instead of the latest one.

In following commits, tests (such as roachtests and logic tests) may
choose to use this new functionality instead of always picking the
latest predecessor.

[1] https://github.com/cockroachdb/docs/blob/main/src/current/_data/releases.yml

Epic: CRDB-19321

Release note: None

/cc @cockroachdb/release

Release justification: test-only changes.

### CODE REVIEW

**Comment by renatolabs** [comment]
Please review new commit to fix `backup-restore/mixed-version` which needs changes to work without flakes with this backport.

**Comment by renatolabs** [comment]
Brought the fix from #106718 here as well. I already ran `backup-restore/mixed-version` several times on this branch, I'll start a run of `tpcc/mixed-headroom/multiple-upgrades` as well just to be sure.

**Comment by renatolabs** [comment]
> Brought the fix from #106718 here as well. I already ran `backup-restore/mixed-version` several times on this branch, I'll start a run of `tpcc/mixed-headroom/multiple-upgrades` as well just to be sure.

Tests have passed: https://teamcity.cockroachdb.com/viewLog.html?buildId=10899368&buildTypeId=Cockroach_Nightlies_RoachtestNightlyGceBazel&tab=testsInfo&branch_Cockroach_Nightlies=106695.

**Comment by renatolabs** [comment]
Fixed conflicts.

**Review by srosenberg — APPROVED** [review]

**Pull request merged**
