### PR TITLE
sql: add optional ESCAPE clause

### PR DESCRIPTION
**Pull request by yuzefovich**
Adds optional ESCAPE clause rules to the grammar
for LIKE/ILIKE/NOT LIKE/NOT ILIKE/SIMILAR TO/
NOT SIMILAR TO operators.

Resolves: #23538

Release note (sql change): Adds optional ESCAPE clause rules to
the grammar for LIKE/ILIKE/NOT LIKE/NOT ILIKE/SIMILAR TO/NOT SIMILAR TO
operators along with corresponding parser and logic tests.

### CODE REVIEW

**Comment by knz** [comment]
Yes! Very good. You'll add a release note too.

You'll want to get the other PR merged first, so that you can add logic tests in this one too.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26260#-:-LDq4MA29GiT6fqsDtdl:b-ytqp5i)*

**Comment by yuzefovich** [comment]
#26176 is merged, and I added some logic tests to this PR as well. Is there anything else necessary?

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26260#-:-LFSbdOR57fcR4OUHhL-:bhsoob9)*

**Comment by knz** [comment]
:lgtm: thank you!

---

Reviewed 4 of 4 files at r2.
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26260#-:-LFcal114aGPP7SenmuS:bro3093)*

**Comment by yuzefovich** [comment]
Thanks for all the advice and the comments!

---

Review status: :shipit: complete! 1 of 0 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26260#-:-LFccCTKBX8zvVjMtBJJ:b-rkok4c)*

**Pull request merged**
