### PR TITLE
storage: Disable campaign-on-wake when receiving raft messages

### LINKED ISSUE #26391: storage: very slow restart of local cluster
I created a 3-node local cluster using roachdemo on top of 98b1ceb6975874c5a8670b56e6540307ab791728 with minor unrelated modifications to the SQL layer. I created a simple table with 100 ranges but no data in it (`create table foo (k int primary key, v int); alter table foo [Csplit at select generate_series(0, 10000, 100);`).

I stopped the cluster for about a minute then restarted it, and after restarting it any query that tried to touch the table took multiple minutes to complete (e.g. `SHOW TESTING_RANGES FOR TABLE foo;` or `SELECT * FROM foo;`). After the first one succeeds, additional such queries complete in well under a second.

The cluster is hardly using any CPU, so it's not spinning on a bunch of real work.

The most suspicious bit I've noticed so far is a lot of raft election traffic until the moment when things start working:

screen shot 2018-06-04 at 3 02 40 pm

screen shot 2018-06-04 at 3 29 30 pm

Also showing the slow startup is the very slow ramp-up of the replicas and leaseholders metrics:

screen shot 2018-06-04 at 3 14 14 pm

screen shot 2018-06-04 at 3 14 18 pm

Maybe relevant is an "Invalid Lease" for range 9, the eventlog range, although that seems unlikely, particularly since it remains "Invalid" even after the cluster has started responding to queries quickly.

screen shot 2018-06-04 at 3 16 24 pm

### PR DESCRIPTION
**Pull request by bdarnell**
When the incoming message is a MsgVote (which is likely the case for
the first message received by a quiesced follower), immediate
campaigning will cause the election to fail.

This is similar to reverting commit 44e3977, but only disables
campaigning in one location.

Fixes #26391

Release note: None

### CODE REVIEW

**Comment by a-robinson** [comment]
:lgtm: but I didn't really vet every call point. Let me know if you'd like me to. Thanks for tracking this down!

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26463#-:-LEKizCR2tRWz9qPMXV2:b-bo3h5p)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/cmd/roachtest/cluster.go, line 721 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26463#-LEKmr1M34keTF_I1GlS:-LEKmr1M34keTF_I1GlT:b-2rpom0) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b5864e318047a42e18beaf14ac43d3a4a509518/pkg/cmd/roachtest/cluster.go#L721)):*
> ```Go
> 	if local {
> 		// This avoids annoying firewall prompts on macos
> 		args = append(args, "--args", "--host=127.0.0.1")
> ```

Does that work? I would have though you needed `--args=--host=127.0.0.1`.

---

*[pkg/storage/replica.go, line 3456 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26463#-LEKnC651aMHCPDMwzGM:-LEKnC651aMHCPDMwzGN:b-384g4r) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7e89b4123b912b7a01a972b11e3558c90c10b19/pkg/storage/replica.go#L3456)):*
> ```Go
> 	// include MsgVotes), so don't campaign if we wake up our raft
> 	// group.
> 	return r.withRaftGroup(false, func(raftGroup *raft.RawNode) (bool, error) {
> ```

An inline comment such as `false /* mayCampaign */` would be helpful for future readers.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26463#-:-LEKnVuQ7j-IvxO_K5ML:bnfp4nl)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/cmd/roachtest/cluster.go, line 721 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26463#-LEKmr1M34keTF_I1GlS:-LEL9WSV0K81NP-CeTFU:b-y4mwx7) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b5864e318047a42e18beaf14ac43d3a4a509518/pkg/cmd/roachtest/cluster.go#L721)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Does that work? I would have though you needed `--args=--host=127.0.0.1`.
</blockquote></details>

Yes, it works. 

---

*[pkg/storage/replica.go, line 3456 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26463#-LEKnC651aMHCPDMwzGM:-LEL9YPWB0fXF8xgRLBu:b-4refin) ([raw file](https://github.com/cockroachdb/cockroach/blob/a7e89b4123b912b7a01a972b11e3558c90c10b19/pkg/storage/replica.go#L3456)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

An inline comment such as `false /* mayCampaign */` would be helpful for future readers.
</blockquote></details>

Maybe, but then it's likely to push the function literal onto the next line so I don't think it's a net win. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26463)*

**Comment by tschottdorf** [comment]
LGTM 👍 going to try this on my 100k range cluster.

**Pull request merged**
