### PR TITLE
sql/parser: force parens around join expression

### PR DESCRIPTION
**Pull request by eisenstatdavid**
Fixes a dangling modifier problem with, e.g., WITH ORDINALITY.

### CODE REVIEW

**Comment by eisenstatdavid** [comment]
Oops, this isn't ready yet.

**Comment by eisenstatdavid** [comment]
Now it's ready. PTAL

**Comment by knz** [comment]
Ok, but why this way? Why not the other way instead? Only add parentheses in the AliasTableExpr formatter around its operand? This way the parentheses would only be used in the (less common) case where they are necessary.

**Comment by eisenstatdavid** [comment]
Did it the other way, PTAL

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15778#-:-Kjhb4njYA9cbkKIFSaN:b-gu0sos)*

**Comment by knz** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15778#-:-Kjhf5yVtL7pL7-FNRO9:bnfp4nl)*

**Pull request merged**
