### PR TITLE
avoid reflection-based Transaction cloning

### PR DESCRIPTION
**Pull request by tamird**
This allows reverting the ugly hacks in util/uuid. See gogo/protobuf#147.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4383)

### CODE REVIEW

**Comment by petermattis** [comment]
LGTM

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4383#-:-KAaGma3wiaWzZzq4tgW:676834233)*

**Comment by tschottdorf** [comment]
LGTM (whether or not you want to wrap `proto.Clone` as we discussed one-to-one).

**Comment by tamird** [comment]
Wrapper is ready, you guys are gonna wanna take another look at this. :bomb::mag:

**Comment by petermattis** [comment]
Review status: 8 of 24 files reviewed at latest revision, 2 unresolved discussions.

---

*[util/clone_proto.go, line 50 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4383#-KAahmOXIurpYzFDtlbL:-KAahmOXIurpYzFDtlbM:-1323861272) ([raw file](https://github.com/cockroachdb/cockroach/blob/c32d3b572f5b1e722c5129f4a97cac48357fda96/util/clone_proto.go#L50)):*
I'm not clear on why you need both `isOrContainsUUID` and `findUUIDValue`. I'm also not clear on why `UUID` is special. Can't you recursively look for any embedded array? Or are there embedded arrays that are ok>

---

*[util/clone_proto.go, line 57 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4383#-KAai1HDxBsy6CWmp9hy:-KAai1HE-26QX-PmxXcA:-2074818080) ([raw file](https://github.com/cockroachdb/cockroach/blob/c32d3b572f5b1e722c5129f4a97cac48357fda96/util/clone_proto.go#L57)):*
You don't need to hold the `types` lock while cloning.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4383)*

**Comment by tamird** [comment]
Review status: 8 of 24 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[util/clone_proto.go, line 50 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4383#-KAahmOXIurpYzFDtlbL:-KAaiDX6u1sPN8WbhdM1:966665084) ([raw file](https://github.com/cockroachdb/cockroach/blob/c32d3b572f5b1e722c5129f4a97cac48357fda96/util/clone_proto.go#L50)):*
isOrContainsUUID is meant to rule out types that are definitely never going to contain "forbidden" types. It's an optimization.

You're right, the problem is any array, not just uuid.UUID - I've made that change.

---

*[util/clone_proto.go, line 57 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4383#-KAai1HDxBsy6CWmp9hy:-KAaiTlp89gpsZJG6OYD:-813964511) ([raw file](https://github.com/cockroachdb/cockroach/blob/c32d3b572f5b1e722c5129f4a97cac48357fda96/util/clone_proto.go#L57)):*
Ah, you're right, and in an earlier change, I wasn't. Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4383)*

**Comment by petermattis** [comment]
Review status: 8 of 24 files reviewed at latest revision, 2 unresolved discussions.

---

*[util/clone_proto.go, line 50 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4383#-KAahmOXIurpYzFDtlbL:-KAaktfqlxWPIz8PCYQl:-239104152) ([raw file](https://github.com/cockroachdb/cockroach/blob/c32d3b572f5b1e722c5129f4a97cac48357fda96/util/clone_proto.go#L50)):*
The optimization is that instead of iterating over every value of a slice/map you just use the type? I'm not sure that is worthwhile given this is going to happen once per type. I'm also not clear on why you need to find the specific array value. I think it would be as or more useful to output that path from the top-level struct down to the first array element found and that can be done in a single pass. 

---

*[util/clone_proto.go, line 54 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4383#-KAalPHRw2T3ybSodmth:-KAalPHRw2T3ybSodmti:969878875) ([raw file](https://github.com/cockroachdb/cockroach/blob/507e026a7c0d278f9683457cd12b96b2d7fdf5e2/util/clone_proto.go#L54)):*
When can the type contain an array but you can't find it using `findArrayValue`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4383)*

**Comment by tamird** [comment]
Review status: 8 of 24 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[util/clone_proto.go, line 50 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4383#-KAahmOXIurpYzFDtlbL:-KAamlfaEXQTD4lHl6hx:2125713261) ([raw file](https://github.com/cockroachdb/cockroach/blob/c32d3b572f5b1e722c5129f4a97cac48357fda96/util/clone_proto.go#L50)):*
The optimization is that for types which never contain arrays, they will be iterated over just once. To determine that, I have to iterate over the type.

For types which _might_ contain arrays, I have to iterate over the value and see if it actually contains an array.

---

*[util/clone_proto.go, line 54 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4383#-KAalPHRw2T3ybSodmth:-KAalmT9dOhTtKnlFX-x:-557968543) ([raw file](https://github.com/cockroachdb/cockroach/blob/507e026a7c0d278f9683457cd12b96b2d7fdf5e2/util/clone_proto.go#L54)):*
```
type foo struct {
  arrayPtr *[16]byte
}

var doesNotContainArray = foo{}
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4383)*

**Comment by petermattis** [comment]
Review status: 8 of 24 files reviewed at latest revision, 2 unresolved discussions.

---

*[util/clone_proto.go, line 50 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4383#-KAahmOXIurpYzFDtlbL:-KAaoUGWQMWiTwusAVCe:335227952) ([raw file](https://github.com/cockroachdb/cockroach/blob/c32d3b572f5b1e722c5129f4a97cac48357fda96/util/clone_proto.go#L50)):*
See my other comment below. I would determination of whether the proto contains an array (and is thus not clone-able) should be based purely on the type. 

---

*[util/clone_proto.go, line 54 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4383#-KAalPHRw2T3ybSodmth:-KAanlKTJkNi3StuKh0Q:124335373) ([raw file](https://github.com/cockroachdb/cockroach/blob/507e026a7c0d278f9683457cd12b96b2d7fdf5e2/util/clone_proto.go#L54)):*
Won't that fail to clone? And iterating over the value to find the arrays means that the contents of the `knownGood` map are dependent on the contents of the `pb` passed to `ProtoClone`. That doesn't seem right. What am I missing?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4383)*

**Comment by tschottdorf** [comment]
Reviewed 12 of 12 files at r1, 16 of 16 files at r2, 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4383)*

**Comment by tamird** [comment]
I've optimized this further so that each type (including inner types) only gets traversed once (values may still be traversed many times).

---

Review status: 23 of 24 files reviewed at latest revision, 2 unresolved discussions.

---

*[util/clone_proto.go, line 50 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4383#-KAahmOXIurpYzFDtlbL:-KAaomt6LS3X0FLCrNuz:-1579444233) ([raw file](https://github.com/cockroachdb/cockroach/blob/c32d3b572f5b1e722c5129f4a97cac48357fda96/util/clone_proto.go#L50)):*
Yes, that would be nice, but would break existing usage.

---

*[util/clone_proto.go, line 54 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4383#-KAalPHRw2T3ybSodmth:-KAaosI_MqEqNS9d_o7N:855513736) ([raw file](https://github.com/cockroachdb/cockroach/blob/507e026a7c0d278f9683457cd12b96b2d7fdf5e2/util/clone_proto.go#L54)):*
Why would it fail to clone? What does failing to clone mean?

The contents of the `known` map depend only on the type of `pb`, not its value.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4383#-:-KAarG228O5YMPBdZqKo:455093600)*

**Comment by petermattis** [comment]
Review status: 23 of 24 files reviewed at latest revision, 2 unresolved discussions.

---

*[util/clone_proto.go, line 50 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4383#-KAahmOXIurpYzFDtlbL:-KAargV_muA9tTtxgi0a:-1367419806) ([raw file](https://github.com/cockroachdb/cockroach/blob/c32d3b572f5b1e722c5129f4a97cac48357fda96/util/clone_proto.go#L50)):*
Ah, you're calling `CloneProto` on types which contain a nil `Transaction`. Ok, I think I understand this now. And I think this code needs a healthy dose of explanatory comments. The relation between `isOrContainsArray` and `findArrayValue` is not obvious. That you want to check that the proto has an actually reachable array vs one that is potentially reachable is also not obvious. 

---

*[util/clone_proto.go, line 54 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4383#-KAalPHRw2T3ybSodmth:-KAasABXdjYitVFq_nKz:1001858456) ([raw file](https://github.com/cockroachdb/cockroach/blob/507e026a7c0d278f9683457cd12b96b2d7fdf5e2/util/clone_proto.go#L54)):*
Yes `knownGood` is solely dependent on the type. I misread that. 

Failing to clone would be the error (or is it a panic) you've seen when trying to clone a proto containing an array. But now that we've established that you're examining the value and not just the type I'm wondering what the utility is. If you call `proto.Clone` won't you also discover the proto contains an array/UUID?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4383)*

**Comment by tamird** [comment]
Review status: 23 of 24 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[util/clone_proto.go, line 54 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4383#-KAalPHRw2T3ybSodmth:-KAat_ZW3iK1yQggqXKS:1821638595) ([raw file](https://github.com/cockroachdb/cockroach/blob/507e026a7c0d278f9683457cd12b96b2d7fdf5e2/util/clone_proto.go#L54)):*
There's no panic and no error. Behold the glory of https://github.com/golang/protobuf/blob/master/proto/clone.go#L204 (this code is the same in gogo/protobuf).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4383)*

**Comment by petermattis** [comment]
Review status: 23 of 24 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[util/clone_proto.go, line 54 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4383#-KAalPHRw2T3ybSodmth:-KAauKyAGDCr9q2lnEN9:1447772559) ([raw file](https://github.com/cockroachdb/cockroach/blob/507e026a7c0d278f9683457cd12b96b2d7fdf5e2/util/clone_proto.go#L54)):*
Oh, lovely. Ok, the rationale for this is good, the implementation looks good, just sprinkle some comments about what is going on. Oh, and the `CloneProto` comment is out of date (referring only to UUID). I think the `CloneProto` function comment would be a good place for some explanation about why this is necessary and the short comings of `proto.Clone`. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4383)*

**Comment by tamird** [comment]
Review status: 23 of 24 files reviewed at latest revision, 1 unresolved discussion.

---

*[util/clone_proto.go, line 54 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4383#-KAalPHRw2T3ybSodmth:-KAb0-f2Ygc6bHBjPUt1:-1454260613) ([raw file](https://github.com/cockroachdb/cockroach/blob/507e026a7c0d278f9683457cd12b96b2d7fdf5e2/util/clone_proto.go#L54)):*
Done and also generalized this in case we find more kinds that need this treatment in the future.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4383)*

**Comment by petermattis** [comment]
LGTM

---

Review status: 23 of 24 files reviewed at latest revision, 2 unresolved discussions.

---

*[util/clone_proto.go, line 67 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4383#-KAb1nqIxt3sCOujzYbC:-KAb1nqIxt3sCOujzYbD:-843867059) ([raw file](https://github.com/cockroachdb/cockroach/blob/254dde22572cd3ecb3202ce2722264052e735519/util/clone_proto.go#L67)):*
Verboten. Is Tobias infecting you?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4383#-:-KAb2fpxfNpBO8jiznDj:676834233)*

**Comment by tschottdorf** [comment]
Reviewed 1 of 1 files at r5.
Review status: 23 of 24 files reviewed at latest revision, 2 unresolved discussions.

---

*[util/clone_proto.go, line 67 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4383#-KAb1nqIxt3sCOujzYbC:-KAb3V_b1gfGcYSAWhHH:-455626659) ([raw file](https://github.com/cockroachdb/cockroach/blob/254dde22572cd3ecb3202ce2722264052e735519/util/clone_proto.go#L67)):*
ssht.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4383)*

**Comment by tamird** [comment]
Review status: 23 of 24 files reviewed at latest revision, 2 unresolved discussions.

---

*[util/clone_proto.go, line 67 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4383#-KAb1nqIxt3sCOujzYbC:-KAb2t_wfPNNzPD34_53:-169312157) ([raw file](https://github.com/cockroachdb/cockroach/blob/254dde22572cd3ecb3202ce2722264052e735519/util/clone_proto.go#L67)):*
No way, man. I've been saying verboten for years. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4383)*

**Pull request merged**
