### PR TITLE
Storage: Hook up size limitations to RocksDB engines.

### LINKED ISSUE #4621: storage: limit stores by their sizes
This is a soft limit, but it should be used for calculating the free space for rebalancing purposes.

### PR DESCRIPTION
**Pull request by BramGruneir**
Fixes #4621 

I've done a good amount of manual testing of this change and more tests will come in my change to add sizes to acceptance tests #4561 

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4777)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[storage/engine/rocksdb.go, line 212 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4777#-KBs_kScDa8SYhQ12gfX:-KBs_kSdKjf5qTeYJvpN:-1907996207) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d779a2b58da4da447c1945a2b33035c849db0c8/storage/engine/rocksdb.go#L212)):*
Heh, that comment is accurate, but not terribly insightful: the code says as much.

---

*[storage/engine/rocksdb.go, line 223 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4777#-KBsbEbjZYsM09mOt7n5:-KBsbEbjZYsM09mOt7n6:-374648780) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d779a2b58da4da447c1945a2b33035c849db0c8/storage/engine/rocksdb.go#L223)):*
I think it would be clearer to make this condition: `if r.maxSize == 0 || r.maxSize >= fsuTotal`. Then you don't have to worry about the `r.maxSize >= fsuTotal` case below.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4777)*

**Comment by BramGruneir** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[storage/engine/rocksdb.go, line 212 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4777#-KBs_kScDa8SYhQ12gfX:-KBtQW4mT_FB4PVZ7T1K:1826029387) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d779a2b58da4da447c1945a2b33035c849db0c8/storage/engine/rocksdb.go#L212)):*
Yeah, I think I did that for my own sanity when moving code around, removed.

---

*[storage/engine/rocksdb.go, line 223 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4777#-KBsbEbjZYsM09mOt7n5:-KBtR9C0rOTuqIm5C4i_:-1840326491) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d779a2b58da4da447c1945a2b33035c849db0c8/storage/engine/rocksdb.go#L223)):*
Good call, that cleans up the logic a lot.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4777)*

**Comment by petermattis** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[storage/engine/rocksdb.go, line 238 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4777#-KBu796fmS_zBdHIdrhq:-KBu796fmS_zBdHIdrhr:-1169852075) ([raw file](https://github.com/cockroachdb/cockroach/blob/78c14d6325516fe6f9480079e62c2a4391576961/storage/engine/rocksdb.go#L238)):*
Is this doing what you want it to do? Let's say we're running on a 100GB disk with 50GB available and we set a max-size for the store of 1GB.  This will compute `reserved`  as 99GB (`100GB - 1GB`) and `available` as 0GB.  Am I missing something about how this calculation is supposed to work?

When `r.maxSize != 0`, I think we need to be computing how much space the rocksdb directory is consuming and take take `max(0, min(fsuAvail, r.maxSize - rocksdbSpaceUsed))`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4777)*

**Comment by tamird** [comment]
Reviewed 1 of 5 files at r1.
Review status: 1 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/store_spec.go, line 38 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4777#-KBuEsybcxBrhMr6EkkL:-KBuEsycN1NKWYPpptVL:193301128) ([raw file](https://github.com/cockroachdb/cockroach/blob/99191fea2f525cac5b206eb713a7a34970c67ab1/server/store_spec.go#L38)):*
why did this change? there's no arithmetic being done on this value and you're having to upcast it everywhere now.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4777)*

**Comment by tamird** [comment]
Reviewed 2 of 5 files at r1, 1 of 2 files at r2.
Review status: 4 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[server/store_spec.go, line 159 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4777#-KBuFW635BwrotZqtVm5:-KBuFW635BwrotZqtVm6:-367035327) ([raw file](https://github.com/cockroachdb/cockroach/blob/78c14d6325516fe6f9480079e62c2a4391576961/server/store_spec.go#L159)):*
why change this at all? ah, the cast.

---

*[storage/engine/rocksdb.go, line 28 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4777#-KBuFNR9qP-9GSA64-b-:-KBuFNR9qP-9GSA64-b0:-318347114) ([raw file](https://github.com/cockroachdb/cockroach/blob/78c14d6325516fe6f9480079e62c2a4391576961/storage/engine/rocksdb.go#L28)):*
whoa these imports are pretty weird

---

*[storage/engine/rocksdb.go, line 56 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4777#-KBuFJ5NE5gayK_EMtlE:-KBuFJ5NE5gayK_EMtlF:-1870869242) ([raw file](https://github.com/cockroachdb/cockroach/blob/78c14d6325516fe6f9480079e62c2a4391576961/storage/engine/rocksdb.go#L56)):*
why is this a different signedness from everything else in here?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4777)*

**Comment by BramGruneir** [comment]
Review status: 4 of 5 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[server/store_spec.go, line 38 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4777#-KBuEsybcxBrhMr6EkkL:-KBx-8Qe39ftLEMpIaqu:1661842127) ([raw file](https://github.com/cockroachdb/cockroach/blob/99191fea2f525cac5b206eb713a7a34970c67ab1/server/store_spec.go#L38)):*
Our policy is to use int64 for on disk sizes and not uint64.  I was just changing it to match.

---

*[storage/engine/rocksdb.go, line 28 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4777#-KBuFNR9qP-9GSA64-b-:-KBx-R_WSKb8qEg5y5SN:-1817362115) ([raw file](https://github.com/cockroachdb/cockroach/blob/78c14d6325516fe6f9480079e62c2a4391576961/storage/engine/rocksdb.go#L28)):*
What's weird?

---

*[storage/engine/rocksdb.go, line 56 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4777#-KBuFJ5NE5gayK_EMtlE:-KBx-kWK9yQBGUgW4BSd:1014694118) ([raw file](https://github.com/cockroachdb/cockroach/blob/78c14d6325516fe6f9480079e62c2a4391576961/storage/engine/rocksdb.go#L56)):*
Size on disk should be signed.

---

*[storage/engine/rocksdb.go, line 238 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4777#-KBu796fmS_zBdHIdrhq:-KBx02u4AEqX8c-duDFO:604046605) ([raw file](https://github.com/cockroachdb/cockroach/blob/78c14d6325516fe6f9480079e62c2a4391576961/storage/engine/rocksdb.go#L238)):*
You're absolutely right.  I'll update this.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4777)*

**Comment by tamird** [comment]
Review status: 4 of 5 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[server/store_spec.go, line 38 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4777#-KBuEsybcxBrhMr6EkkL:-KBx6TEnAhFD3N8eDLuq:-48809800) ([raw file](https://github.com/cockroachdb/cockroach/blob/99191fea2f525cac5b206eb713a7a34970c67ab1/server/store_spec.go#L38)):*
Where's this policy? I've seen the argument that arithmetic on unsigned values can be dangerous, but there's no arithmetic on this value at all, and negative sizes are nonsense.

---

*[storage/engine/rocksdb.go, line 28 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4777#-KBuFNR9qP-9GSA64-b-:-KBx6ediPhoKf6cvdeHC:767207731) ([raw file](https://github.com/cockroachdb/cockroach/blob/78c14d6325516fe6f9480079e62c2a4391576961/storage/engine/rocksdb.go#L28)):*
That this cockroach import is away from the other cockroach imports?

---

*[storage/engine/rocksdb.go, line 56 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4777#-KBuFJ5NE5gayK_EMtlE:-KBx6j2lSxcsARoH9b_9:677194780) ([raw file](https://github.com/cockroachdb/cockroach/blob/78c14d6325516fe6f9480079e62c2a4391576961/storage/engine/rocksdb.go#L56)):*
Why?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4777)*

**Comment by BramGruneir** [comment]
Review status: 2 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[server/store_spec.go, line 38 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4777#-KBuEsybcxBrhMr6EkkL:-KByCE5yaLX9g35_dwFN:-574747450) ([raw file](https://github.com/cockroachdb/cockroach/blob/99191fea2f525cac5b206eb713a7a34970c67ab1/server/store_spec.go#L38)):*
Go always uses int64 for sizes, see https://golang.org/pkg/os/#FileInfo.  We also use int64 in roachpb.StoreCapacity.

---

*[storage/engine/rocksdb.go, line 28 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4777#-KBuFNR9qP-9GSA64-b-:-KBx74x_0KEWOVHjOxmC:865407451) ([raw file](https://github.com/cockroachdb/cockroach/blob/78c14d6325516fe6f9480079e62c2a4391576961/storage/engine/rocksdb.go#L28)):*
Ah, I didn't see the extra line.  Fixed.

---

*[storage/engine/rocksdb.go, line 56 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4777#-KBuFJ5NE5gayK_EMtlE:-KBx79HGHhSDnK6WAZfO:-701763365) ([raw file](https://github.com/cockroachdb/cockroach/blob/78c14d6325516fe6f9480079e62c2a4391576961/storage/engine/rocksdb.go#L56)):*
See my other response.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4777)*

**Comment by BramGruneir** [comment]
So I've been testing this and it looks like the sigar library is returning the blocks and not the size.  It's also been stagnant for a long time and nobody is contributing to it.  I'm going to either fork it or just add in the memory and file system stuff directly in utils.

**Comment by BramGruneir** [comment]
The sigar library has been updated with one that's more current.  And I've tested the code manually a number of times.

I think this is ready to go, uint64 vs int64 not withstanding.  Let's discuss that issue tomorrow.

---

Review status: 1 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[storage/engine/rocksdb.go, line 238 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4777#-KBu796fmS_zBdHIdrhq:-KCEakTSZtLqYLJ8iotF:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/78c14d6325516fe6f9480079e62c2a4391576961/storage/engine/rocksdb.go#L238)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4777#-:-KCEao6rCj1oWE5USQV0:-130476054)*

**Comment by petermattis** [comment]
LGTM

---

Review status: 1 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[storage/engine/rocksdb.go, line 215 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4777#-KCGR_BzsIRKOY3kwTyk:-KCGR_BzsIRKOY3kwTyl:1152798062) ([raw file](https://github.com/cockroachdb/cockroach/blob/346b4ab4433d2968b406b0489447eb72c7ea9497/storage/engine/rocksdb.go#L215)):*
I'm not aware of us using `Cockroach` in other error messages. And we don't capitalize or punctuate error messages so they can be composed. Let's simplify this to `unsupported disk size: %d`. Ditto for the other error below.

---

*[storage/engine/rocksdb.go, line 250 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4777#-KCGRFNlVezXSchoV1Z2:-KCGRFNlVezXSchoV1Z3:308467798) ([raw file](https://github.com/cockroachdb/cockroach/blob/346b4ab4433d2968b406b0489447eb72c7ea9497/storage/engine/rocksdb.go#L250)):*
This is a small nit, but I find blocks of code like the above more symmetric if the variables remain on the same side of the expression and assignment:

```
if available > fsuAvail {
  available = fsuAvail
}
```

---

*[storage/engine/rocksdb.go, line 251 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4777#-KCGQw5j8ZBwhi9EU0SI:-KCGQw5j8ZBwhi9EU0SJ:525408610) ([raw file](https://github.com/cockroachdb/cockroach/blob/346b4ab4433d2968b406b0489447eb72c7ea9497/storage/engine/rocksdb.go#L251)):*
Heh, that looks like one of those old coding guidelines to always put constants on the left side of comparisons. But there is no need for such a rule in Go since assignment is not an expression. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4777#-:-KCGRolNJzK5P2OG1cp0:676834233)*

**Comment by BramGruneir** [comment]
Review status: 1 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[storage/engine/rocksdb.go, line 215 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4777#-KCGR_BzsIRKOY3kwTyk:-KCGzFVK0SHtxoKQu0cN:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/346b4ab4433d2968b406b0489447eb72c7ea9497/storage/engine/rocksdb.go#L215)):*
Done.

---

*[storage/engine/rocksdb.go, line 250 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4777#-KCGRFNlVezXSchoV1Z2:-KCGyiNrdqn5zda4Z9Jo:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/346b4ab4433d2968b406b0489447eb72c7ea9497/storage/engine/rocksdb.go#L250)):*
Done.

---

*[storage/engine/rocksdb.go, line 251 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4777#-KCGQw5j8ZBwhi9EU0SI:-KCGy_HfzmlTvXlIy2j7:610101667) ([raw file](https://github.com/cockroachdb/cockroach/blob/346b4ab4433d2968b406b0489447eb72c7ea9497/storage/engine/rocksdb.go#L251)):*
:)  
if (null == some_pointer) {

I swapped this one as well.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4777)*

**Pull request merged**
