### PR TITLE
all: Remove (now unused) Retryable error interface

### LINKED ISSUE #2500: all: rationalize retry options
We have default retry options in many places throughout the system, and they're not always consistent. We need to make a pass through the codebase to verify that all retry options are consistent, large enough for real-world deployments, and configurable.

Case in point: #2495 resulted in mysterious timeout-related failures in race builds. This turned out to be because we have two different retry policies for client operations: `client.rpcSender` defaults to `InitialBackoff: 50*time.Millisecond, MaxRetries: 1`, while `kv.distSender` defaults to `InitialBackoff: 250*time.Millisecond`. Completing an SSL handshake in a race build takes more than 50ms, so if the first client operation used `client.rpcSender`, it would run out of retries and fail before the connection became healthy. If the first client operation used `kv.distSender` that operation would succeed, and then the healthy connection would be in the global cache for use by future `client.rpcSender`. #2495 happened to remove an operation that used `kv.distSender`, causing the first operation in many tests to use `client.rpcSender` instead.

We should have one place that sets retry options for client connections (and harmonize `rpcSender` and `distSender` in other ways, e.g. `distSender` will wait a short time for the connection to become healthy before going into its first backoff, while `rpcSender` starts its first backoff immediately). 50ms is clearly too short for race-enabled builds; we also need to decide on retry policies for real-world networks. Only some of the various options are currently configurable, but timeouts and backoff intervals will need to be set differently depending on the scale of the deployment.

### PR DESCRIPTION
**Pull request by bdarnell**
This interface was misguided since there is no universal notion of a
retryable error; some errors should only be retried in certain places.

Closes #2500

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6738)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm: 

<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> #### all: Remove \(now unused\) Retryable error interface
> 
> This interface was misguided since there is no universal notion of a
> 
> retryable error; some errors should only be retried in certain places.
> 
> 
> 
> Closes #2500
> 
> 
> </details>


---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[roachpb/errors.proto, line 278 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6738#-KHw82LuVNno07-Ao6r9:-KHw82LuVNno07-Ao6rA:967517548) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fe70fc5ef38e467314835f4dbe7246971aac834/roachpb/errors.proto#L278)):*
> ```protobuf
>   optional Timestamp now = 8 [(gogoproto.nullable) = false];
> 
>   reserved 2;
> ```

perhaps not for this change, but are we putting these at the bottom or the top?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6738#-:-KHw886CLsKgh4-9ng6O:980077423)*

**Comment by RaduBerinde** [comment]
:lgtm:

<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> :lgtm: </details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6738#-:-KHw9Qo7cT4CR_QBKWhs:1417088721)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[roachpb/errors.proto, line 278 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6738#-KHw82LuVNno07-Ao6r9:-KHw9W4g61rhPMCu8sOc:-1463022790) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fe70fc5ef38e467314835f4dbe7246971aac834/roachpb/errors.proto#L278)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> perhaps not for this change, but are we putting these at the bottom or the top?</details>
I prefer putting them at the bottom because they're unimportant to any human reader (except when adding new fields, when you have to scan the whole message declaration anyway). @dt put them in the same place as the removed field used to be to minimize movement in the diff. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6738)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[roachpb/errors.proto, line 278 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6738#-KHw82LuVNno07-Ao6r9:-KHwAY5LOY6PGfHGMOki:-510466975) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fe70fc5ef38e467314835f4dbe7246971aac834/roachpb/errors.proto#L278)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> I prefer putting them at the bottom because they're unimportant to any human reader (except when adding new fields, when you have to scan the whole message declaration anyway). @dt put them in the same place as the removed field used to be to minimize movement in the diff. </details>
:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6738)*

**Comment by andreimatei** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[kv/send_test.go, line 113 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/6738#-Kh8iUguyPrAt3PtCEDa:-Kh8iUguyPrAt3PtCEDb:bwtqa0d) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fe70fc5ef38e467314835f4dbe7246971aac834/kv/send_test.go#L113)):*
> ```Go
> // TestRetryableError verifies that Send returns a retryable error
> // when it hits an RPC error.
> func TestRetryableError(t *testing.T) {
> ```

does this test still have a point after this change?
At the very least, I think the name is wrong.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6738)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[kv/send_test.go, line 113 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/6738#-Kh8iUguyPrAt3PtCEDa:-Kh8kCZ7VRtDA2hKNB5_:b6h9e) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fe70fc5ef38e467314835f4dbe7246971aac834/kv/send_test.go#L113)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

does this test still have a point after this change?
At the very least, I think the name is wrong.
</blockquote></details>

Hmm. I don't see the point of it now

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6738)*

**Comment by andreimatei** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[kv/send_test.go, line 113 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/6738#-Kh8iUguyPrAt3PtCEDa:-Kh8n-3MMyR6DhfC4_SS:b-2829jn) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fe70fc5ef38e467314835f4dbe7246971aac834/kv/send_test.go#L113)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Hmm. I don't see the point of it now
</blockquote></details>

Indeed. Great. I'll delete it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6738)*

**Pull request merged**
