### PR TITLE
rpc: don't impersonate calling tenant when doing local RPCs

### PR DESCRIPTION
**Pull request by andreimatei**
This patch fixes a bug around tenant authentication: say a KV server is serving a tenant RPC. During this serving, it makes another RPC. If that RPC ends up going to itself and using the internalClientAdapter to bypass gRPC, then the inner RPC ends up carrying the tenant's identity in its ctx. If the RPC goes to another node, that node will treat the RPC as coming from a KV server / the system tenant.

I presume this inconsistency was not intended. It has condequences like the fact that, in the local case, the tenant ends up being charged twice against its request limit, whereas if the inner RPC is remote, it's only charged once. This seems backwards, if anything.

This patch fixes it by wiping out any tenant identity from the RPC ctx when handling local RPCs.

Release note: None
Epic: None

### CODE REVIEW

**Comment by andreimatei** [comment]
I don't know what I'm doing; please scrutinize.

**Review by nvb — CHANGES_REQUESTED** [review]
This change makes sense to me, though others should also sign off. Thanks for making it. Can we find a way to test it?

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93826#-:-NKZK11GBwk08wxSRbaq:b-xel2ld)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @andreimatei, and @knz)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93826#-NKZI-f_4BQ6CTvC3Tj1):*
"consequences"
___
*[`pkg/roachpb/tenant.go` line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93826#-NKZJvmEB4cRwfEQ6T9H:-NKZJvmF6aqhQgB3fDsI:b-3c0fer) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f504102b8cd0ede5c9d67a3d382e537e04cd186/pkg/roachpb/tenant.go#L116)):*
> ```Go
> func NewContextForTenant(ctx context.Context, tenID TenantID) context.Context {
> 	var val any
> 	if tenID != (TenantID{}) {
> ```

`tenID.IsSet()`? Here and below.
___
*[`pkg/roachpb/tenant.go` line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93826#-NKZJ6kMC4J3NvgTlYG7:-NKZJ6kMC4J3NvgTlYG8:b-orcfc3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f504102b8cd0ede5c9d67a3d382e537e04cd186/pkg/roachpb/tenant.go#L119)):*
> ```Go
> 		val = tenID
> 	} else {
> 		val = nil
> ```

It's probably worth avoiding the new heap alloc in non-MT clusters by short-circuiting without the call to `context.WithValue` if `!TenantFromContext(ctx)`.
___
*[`pkg/rpc/auth.go` line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93826#-NKZJf1Q8qAOt8caTrS0:-NKZJf1Q8qAOt8caTrS1:b-k9eteu) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f504102b8cd0ede5c9d67a3d382e537e04cd186/pkg/rpc/auth.go#L67)):*
> ```Go
> 		return nil, err
> 	}
> 	ctx = contextWithTenant(ctx, tenID)
> ```

`contextWithTenant` is also adding a `logtag`. Do we want it to if `tenID == (roachpb.TenantID{})` and a tenant logtag is not already set?

**Review by andreimatei — COMMENTED** [review]
> Can we find a way to test it?

Added a test.

@ajstorm @knz can I get a review please?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93826#-:-NLOXgvUC9ogRuOACKci:b-a3rzka)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @knz, and @nvanbenschoten)

___
*[`pkg/roachpb/tenant.go` line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93826#-NKZJvmEB4cRwfEQ6T9H:-NLMTahm53UDAe_Qt1Ek:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f504102b8cd0ede5c9d67a3d382e537e04cd186/pkg/roachpb/tenant.go#L116)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`tenID.IsSet()`? Here and below.
</blockquote></details>

done
___
*[`pkg/roachpb/tenant.go` line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93826#-NKZJ6kMC4J3NvgTlYG7:-NLMUj3s1hBqwa9J3W6P:b-2cqfr5) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f504102b8cd0ede5c9d67a3d382e537e04cd186/pkg/roachpb/tenant.go#L119)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It's probably worth avoiding the new heap alloc in non-MT clusters by short-circuiting without the call to `context.WithValue` if `!TenantFromContext(ctx)`.
</blockquote></details>

done; I've also short-circuited if the right tenant is already set
___
*[`pkg/rpc/auth.go` line 67 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93826#-NKZJf1Q8qAOt8caTrS0:-NLMWyx73NVvrmebedQP:blfhx8t) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f504102b8cd0ede5c9d67a3d382e537e04cd186/pkg/rpc/auth.go#L67)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`contextWithTenant` is also adding a `logtag`. Do we want it to if `tenID == (roachpb.TenantID{})` and a tenant logtag is not already set?
</blockquote></details>

I guess we don't.
Done.

**Review by knz — APPROVED** [review]
Thanks, nice work.

> Reviewed 6 of 6 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93826#-:-NLPiH8wDjePGk5f3Urx:b-7y6010)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @andreimatei, @herkolategan, @nvanbenschoten, and @srosenberg)

___
*[`pkg/testutils/serverutils/test_tenant_shim.go` line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93826#-NLPhSskCttj0_JZGOCf:-NLPhSsl3foiTBsI4aQo:byxh2uh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d41543f35b5d4f0aa0550ee59ced36beda0927e7/pkg/testutils/serverutils/test_tenant_shim.go#L52)):*
> ```Go
> 
> 	// DB returns a handle to the cluster's KV interface.
> 	DB() *kv.DB
> ```

Then you can remove this from the TestServerInterface which embeds TestTenantInterface (test_server_shim.go)
___
*[`pkg/kv/kvserver/client_tenant_test.go` line 211 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93826#-NLPhatPEGnvz-o5CX3R:-NLPhatPEGnvz-o5CX3S:b-i40ait) ([raw file](https://github.com/cockroachdb/cockroach/blob/d41543f35b5d4f0aa0550ee59ced36beda0927e7/pkg/kv/kvserver/client_tenant_test.go#L211)):*
> ```Go
> 	writeCostLower := cfg.WriteBatchUnits + cfg.WriteRequestUnits
> 	writeCostUpper := cfg.WriteBatchUnits + cfg.WriteRequestUnits + float64(32)*cfg.WriteUnitsPerByte
> 	tolerance := 10.0 // leave space for a couple of other background requests
> ```

nit: period at end.
___
*[`pkg/kv/kvserver/client_tenant_test.go` line 211 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93826#-NLPhdqsAZbRiMdPIxN5:-NLPhdqsAZbRiMdPIxN6:b-gsvgvq) ([raw file](https://github.com/cockroachdb/cockroach/blob/d41543f35b5d4f0aa0550ee59ced36beda0927e7/pkg/kv/kvserver/client_tenant_test.go#L211)):*
> ```Go
> 	writeCostLower := cfg.WriteBatchUnits + cfg.WriteRequestUnits
> 	writeCostUpper := cfg.WriteBatchUnits + cfg.WriteRequestUnits + float64(32)*cfg.WriteUnitsPerByte
> 	tolerance := 10.0 // leave space for a couple of other background requests
> ```

probably skip.UnderRace() then
___
*[`pkg/kv/kvserver/client_tenant_test.go` line 358 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93826#-NLPi562ApFHLSiQ8R2H:-NLPi562ApFHLSiQ8R2I:bbktm2r) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce83d77fa83a132de26729f0d54a52d8ca4c82ea/pkg/kv/kvserver/client_tenant_test.go#L358)):*
> ```Go
> 	tx1, err := tsql.BeginTx(ctx, nil /* opts */)
> 	require.NoError(t, err)
> 	_, err = tx1.Exec("insert into t(x) values (424242)")
> ```

nit: `$1` then refer to `magicKey`
___
*[`pkg/kv/kvserver/client_tenant_test.go` line 367 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93826#-NLPi8ki3no33lBnuap6:-NLPi8ki3no33lBnuap7:b-8xbfb5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce83d77fa83a132de26729f0d54a52d8ca4c82ea/pkg/kv/kvserver/client_tenant_test.go#L367)):*
> ```Go
> 		tx2, err = tsql.BeginTx(ctx, nil /* opts */)
> 		assert.NoError(t, err)
> 		_, err = tx2.Exec("select * from t where x = " + magicKey)
> ```

you could also use a placeholder here instead of string concat.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93826)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @herkolategan, @knz, @nvanbenschoten, and @srosenberg)

___
*[`pkg/testutils/serverutils/test_tenant_shim.go` line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93826#-NLPhSskCttj0_JZGOCf:-NLRzKYf0KGg79jzj0gc:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d41543f35b5d4f0aa0550ee59ced36beda0927e7/pkg/testutils/serverutils/test_tenant_shim.go#L52)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Then you can remove this from the TestServerInterface which embeds TestTenantInterface (test_server_shim.go)
</blockquote></details>

done
___
*[`pkg/kv/kvserver/client_tenant_test.go` line 211 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93826#-NLPhatPEGnvz-o5CX3R:-NLRujYn-sIMmqt4B1VZ:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d41543f35b5d4f0aa0550ee59ced36beda0927e7/pkg/kv/kvserver/client_tenant_test.go#L211)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: period at end.
</blockquote></details>

done
___
*[`pkg/kv/kvserver/client_tenant_test.go` line 211 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93826#-NLPhdqsAZbRiMdPIxN5:-NLRzi_399LUK_pwAOCr:b-vox38n) ([raw file](https://github.com/cockroachdb/cockroach/blob/d41543f35b5d4f0aa0550ee59ced36beda0927e7/pkg/kv/kvserver/client_tenant_test.go#L211)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

probably skip.UnderRace() then
</blockquote></details>

I've stressed it a bunch under race; seems stable.
___
*[`pkg/kv/kvserver/client_tenant_test.go` line 358 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93826#-NLPi562ApFHLSiQ8R2H:-NLRukzi-QOb2aC_Sc88:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce83d77fa83a132de26729f0d54a52d8ca4c82ea/pkg/kv/kvserver/client_tenant_test.go#L358)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: `$1` then refer to `magicKey`
</blockquote></details>

done
___
*[`pkg/kv/kvserver/client_tenant_test.go` line 367 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93826#-NLPi8ki3no33lBnuap6:-NLRulaE8mXzvHfVm0ld:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce83d77fa83a132de26729f0d54a52d8ca4c82ea/pkg/kv/kvserver/client_tenant_test.go#L367)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

you could also use a placeholder here instead of string concat.
</blockquote></details>

done

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93826#-:-NLSdMak64B_RCekU0Ni:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @herkolategan, @knz, @nvanbenschoten, and @srosenberg)

**Review by andreimatei — COMMENTED** [review]
bors r+ single on

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93826#-:-NLTEdO7EnQ3wgvk04js:bsuwfi5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @herkolategan, @knz, @nvanbenschoten, and @srosenberg)

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 3 of 6 files at r2, 5 of 5 files at r4, 3 of 4 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93826#-:-NLWSaShAwC6P5ffQ08n:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm, @andreimatei, @herkolategan, @knz, and @srosenberg)

___
*[`pkg/rpc/auth_tenant.go` line 436 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/93826#-NLWSAuI167ycjZZdwrX:-NLWSAuI167ycjZZdwrY:bbu22fz) ([raw file](https://github.com/cockroachdb/cockroach/blob/424f1f052cf6daa675b7e470dc71168f6ffe4439/pkg/rpc/auth_tenant.go#L436)):*
> ```Go
> 		tags := logtags.FromContext(ctx)
> 		if tags != nil {
> 			for _, t := range tags.Get() {
> ```

Think it's worth pulling some or all of this search into either a function in the `logtag` package or a method on `*logtag.Buffer`?

**Review by andreimatei — COMMENTED** [review]
TFTRs

bors r+ single on

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93826#-:-NLXBAwG8IqlodO-Xq-k:b4ejbus)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm, @herkolategan, @knz, @nvanbenschoten, and @srosenberg)

___
*[`pkg/rpc/auth_tenant.go` line 436 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/93826#-NLWSAuI167ycjZZdwrX:-NLXB26nCXLw_LSGJx68:b-24e6zs) ([raw file](https://github.com/cockroachdb/cockroach/blob/424f1f052cf6daa675b7e470dc71168f6ffe4439/pkg/rpc/auth_tenant.go#L436)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Think it's worth pulling some or all of this search into either a function in the `logtag` package or a method on `*logtag.Buffer`?
</blockquote></details>

yes, I want to do that.
<shakes fist at whoever moved that code out of this repo>

**Comment by rail** [comment]
bors r-
We have temporarily disabled bors for merges. Please merge the PR manually when all required checks pass.

**Pull request merged**
