### PR TITLE
opt: support locality optimized search for scans with more than 1 row

### PR DESCRIPTION
**Pull request by rytaft**
This commit updates the logic for planning locality optimized search to
allow the optimization the be planned if there are fewer than 100,000
keys selected.

The optimization is not yet supported for scans with a hard limit.

Informs #64862

Release justification: Low risk, high benefit change to existing functionality.

Release note (performance improvement): locality optimized search
is now supported for scans that are guaranteed to return 100000 keys
or less. This optimization allows the execution engine to avoid
visiting remote regions if all requested keys are found in the local
region, thus reducing the latency of the query.

### CODE REVIEW

**Review by cucaroach — COMMENTED** [review]
Why is there a 10k limit?    Is it an oom avoidance thing?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69395#-:-Mi1-Tjy4_8DHKNgcB66:b-uzigfs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @yuzefovich)

**Review by yuzefovich — COMMENTED** [review]
Nice!

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69395#-:-Mi2rNXzDJcgx0mRRX86:b-83sjoh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69395#-Mi2qLV94fdc2M_eRAZ6):*
super nit: `s/are fewer/are no more/`.
___
*[pkg/sql/opt_exec_factory.go, line 561 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69395#-Mi2qc4d6InLagFF6nMo:-Mi2qc4e--5QlzyT0rGJ:bhn2tko) ([raw file](https://github.com/cockroachdb/cockroach/blob/36d95e46219aa5abbc73fb241644c59436e60986/pkg/sql/opt_exec_factory.go#L561)):*
> ```Go
> 	left, right exec.Node, reqOrdering exec.OutputOrdering, hardLimit uint64,
> ) (exec.Node, error) {
> 	if hardLimit > 1 {
> ```

Should we assert that `hardLimit <= 10000`?
___
*[pkg/sql/opt/xform/scan_funcs.go, line 155 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69395#-Mi2r4uR7CMWwbTOLVs5:-Mi2r4uR7CMWwbTOLVs6:b-sn8fkq) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2735ee4bff842886affa72837770f01a7d526eb/pkg/sql/opt/xform/scan_funcs.go#L155)):*
> ```Go
> 	// TODO(rytaft): Revisit this when we have a more accurate cost model for data
> 	// distribution.
> 	const localityOptScanMaxRows = 10000
> ```

I think this number has actually been increased to 100k recently by Andrei, so I wonder whether we should just use `row.productionKVBatchSize` directly here (possibly moving into some common base package)?

**Review by rytaft — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69395#-:-Mi6aYZa1x2VzZkl5eb2:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @yuzefovich)

___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69395#-Mi2qLV94fdc2M_eRAZ6):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

super nit: `s/are fewer/are no more/`.
</blockquote></details>

Done.
___
*[pkg/sql/opt_exec_factory.go, line 561 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69395#-Mi2qc4d6InLagFF6nMo:-Mi6Q800EfimGkxYbhNi:b9rr8nl) ([raw file](https://github.com/cockroachdb/cockroach/blob/36d95e46219aa5abbc73fb241644c59436e60986/pkg/sql/opt_exec_factory.go#L561)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Should we assert that `hardLimit <= 10000`?
</blockquote></details>

I'm inclined not to, since 10000 was just an arbitrary number. We had this assertion for 1 row before since we thought the optimization wouldn't work with more than row, but as I've discovered, it works just fine. I'd rather not have to keep this assertion in sync with whatever limit we place in the optimizer.
___
*[pkg/sql/opt/xform/scan_funcs.go, line 155 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69395#-Mi2r4uR7CMWwbTOLVs5:-Mi6_EnP0i0gLA0WX_MQ:bi52qww) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2735ee4bff842886affa72837770f01a7d526eb/pkg/sql/opt/xform/scan_funcs.go#L155)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I think this number has actually been increased to 100k recently by Andrei, so I wonder whether we should just use `row.productionKVBatchSize` directly here (possibly moving into some common base package)?
</blockquote></details>

Done. I made a new package since none of the existing packages seemed appropriate (added in a separate commit). Let me know if you have an idea of a better place for it.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 26 of 26 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69395#-:-Mi7hk3MD3VYmgCY49GB:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[-- commits, line 24 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69395#-Mi7hOWL6nxRS0yIu6e2):*
nit: `s/10000/100000/`.
___
*[-- commits, line 34 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69395#-Mi7hSxBBIZrjrb3m6Gb):*
ditto
___
*[pkg/sql/opt_exec_factory.go, line 561 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69395#-Mi2qc4d6InLagFF6nMo:-Mi7hUV_CaXVdxPrjfe0:b-dxcbts) ([raw file](https://github.com/cockroachdb/cockroach/blob/36d95e46219aa5abbc73fb241644c59436e60986/pkg/sql/opt_exec_factory.go#L561)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I'm inclined not to, since 10000 was just an arbitrary number. We had this assertion for 1 row before since we thought the optimization wouldn't work with more than row, but as I've discovered, it works just fine. I'd rather not have to keep this assertion in sync with whatever limit we place in the optimizer.
</blockquote></details>

Makes sense.
___
*[pkg/sql/opt/xform/scan_funcs.go, line 155 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69395#-Mi2r4uR7CMWwbTOLVs5:-Mi7h_3iDqoDjhIMjoUp:b9j9n43) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2735ee4bff842886affa72837770f01a7d526eb/pkg/sql/opt/xform/scan_funcs.go#L155)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Done. I made a new package since none of the existing packages seemed appropriate (added in a separate commit). Let me know if you have an idea of a better place for it.
</blockquote></details>

Looks good to me.

**Review by rytaft — COMMENTED** [review]
Thanks!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69395#-:-Mi83w6e2GWdD5-JtkrC:b-voiyyw)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde, @rytaft, and @yuzefovich)

___
*[-- commits, line 24 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69395#-Mi7hOWL6nxRS0yIu6e2):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: `s/10000/100000/`.
</blockquote></details>

Done.
___
*[-- commits, line 34 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69395#-Mi7hSxBBIZrjrb3m6Gb):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Comment by yuzefovich** [comment]
bors r-

This needs a rebase and rewrite of `regional_by_row` logic test (which I'll do in a minute).

**Comment by yuzefovich** [comment]
I removed the `DISTSQL` option from the logic test (because the physical plan differs between vectorize=on and vectorize=off configs).

bors r+

**Comment by rytaft** [comment]
> I removed the DISTSQL option from the logic test (because the physical plan differs between vectorize=on and vectorize=off configs).

Thanks!

**Pull request merged**
