### PR TITLE
storage,migrations: respect DisableSeparatedIntents in memory, shorte…

### LINKED ISSUE #69689: migrations: TestSeparatedIntentsMigration is very slow
This test takes ~150s on a corporate MacBook (with their sluggish, intercepted IO), and about 30s on a beefy linux host. 

It looks like it is using on-disk stores which probably explains the slowdown when running with intercepted IO, but the 30s under CI is still quite slow. It looks like the test is Sleep()'ing for 10/5/.5 seconds in various places, which we almost always try to avoid, instead adding knobs to block until the specific needed action has completed.

### PR DESCRIPTION
**Pull request by ajwerner**
…n test

This test was crazy slow before because of its use of the real disk. It did
this, I presume, because the in-memory engine was not respecting the testing
knobs. Also, removed the sleeps.

Before:
`ok  	github.com/cockroachdb/cockroach/pkg/migration/migrations	158.574s`

After:
`ok  	github.com/cockroachdb/cockroach/pkg/migration/migrations	11.132s`

Fixes #69689.

Release justification: non-production code changes

Release note: None

### CODE REVIEW

**Review by fqazi — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69694)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal)

**Review by itsbilal — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69694#-:-MiWz7_p1k_TeuW490sA:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/migration/migrations/separated_intents_external_test.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69694#-MiWz-Wu0K7SJk0nfmFb:-MiWz-Wv-YNC7dwBN121:b-2wvva5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7b3f99f4c09d81a2f39f7f1bb3312a6f5a449a3/pkg/migration/migrations/separated_intents_external_test.go#L55)):*
> ```Go
> 		StorageKnobs: storage.TestingKnobs{DisableSeparatedIntents: true},
> 	}
> 	reg := server.NewStickyInMemEnginesRegistry(server.ReplaceEngines)
> ```

Nice! `ReplaceEngines` is new (added Aug 13) and allows us to go back to using in-mem engines. Previously all sticky engines would remain open through a node restart, making it really difficult to propagate a knob change.

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Pull request merged**
