### PR TITLE
spanconfig/{sqltranslator,testcluster}: support multi-tenant tests

### PR DESCRIPTION
**Pull request by irfansharif**
**spanconfig/{sqltranslator,testcluster}: support multi-tenant tests**

We introduce a nimble testing framework for multi-tenant span config
tests, and use it to power tests for spanconfig.SQLTranslator when run
on behalf of secondary tenants. This framework will see further addition
when testing spanconfig.Reconciler -- we'll maintain a handle on each
tenant's reconciler, kvaccessor, and use both to determine what
span config mutations are made after SQL changes.

This commit also leverages the ExcludeDroppedDescriptorsFromLookup
testing knob we introduced in an earlier commit -- it obviates the need
for arbitrary sleeps (which are both fragile and slow). It also packages
a PrintSpanConfigDiffedAgainstDefaults helper that we'll use in a future
PR (#71994).

**sqltranslatorccl: carve standalone package for tests**

Rename-only commit. We'll use subpackages within ccl/spanconfigccl when
testing other components (spanconfig.Reconciler; [#71994](#71994)).

**spanconfig/{watcher,translator}: add testing knobs**

We introduce two testing knobs that we'll use in future commits:

- SQLWatcherCheckpointNoopsEveryDurationOverride, if set, will override
  how often the SQLWatcher checkpoints no-ops (follow up to [#73171](#73171))

- ExcludeDroppedDescriptorsFromLookup will control whether the
  SQLTranslator ignores dropped descriptors. We'll also use this knob
  for the Reconciler ([#71994](#71994)), for the same purpose. Ignoring dropped
  descriptors in tests is a convenient (and faster!) alternative to
  waiting for the descriptor to actually get GC-ed by the GC job. It
  also makes it easier to order events transactionally -- it's
  sufficient for a checkpoint to cross the timestamp when the table is
  dropped, instead of waiting for the GC job to pick it up post TTL.
  This latter form is used in our current sqltranslator tests where we
  sleep arbitrarily:

      # Sleep for 5 seconds, which is more than the TTL on db.t1, so that
      # the gc job can delete the descriptor.
      sleep duration=5

  This is unfortunate and makes for slower tests than necessary. We can
  get rid of it in a subsequent commit.

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
> Reviewed 8 of 8 files at r1, 12 of 12 files at r2, 20 of 20 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73416)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, and @irfansharif)

___
*[pkg/spanconfig/spanconfig.go, line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73416#-MqFdVIMEIBdhmeO7bqC:-MqFdVIMEIBdhmeO7bqD:b-jw6snr) ([raw file](https://github.com/cockroachdb/cockroach/blob/eea11eebb70c81b6a998e3a12721e4d342a90e0b/pkg/spanconfig/spanconfig.go#L109)):*
> ```Go
> }
> 
> // FullTranslate translates the entire SQL zone configuration state to the
> ```

Did this need to move? It's part of the `spanconfig` interface, not it's implementation, so it feels like it should live here and not in `pkg/sql/spanconfig/spanconfigsqltranslator`.
___
*[pkg/spanconfig/testing_knobs.go, line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73416#-MqFdy9b6OtlYHxiZDYC:-MqFdy9b6OtlYHxiZDYD:b-7nlm51) ([raw file](https://github.com/cockroachdb/cockroach/blob/d199581639982b3d042fb9e943762b294e716b51/pkg/spanconfig/testing_knobs.go#L69)):*
> ```Go
> 	// ExcludeDroppedDescriptorsFromLookup is used to control if the
> 	// SQLTranslator ignores dropped descriptors. If enabled, dropped
> 	// descriptors appear missing -- a convenient+faster alternative to waiting
> ```

Appear missing to whom?
___
*[pkg/spanconfig/spanconfigsqlwatcher/sqlwatcher.go, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73416#-MqFeZtz6HFX-quJ3PHa:-MqFeZtz6HFX-quJ3PHb:b-bwpn92) ([raw file](https://github.com/cockroachdb/cockroach/blob/d199581639982b3d042fb9e943762b294e716b51/pkg/spanconfig/spanconfigsqlwatcher/sqlwatcher.go#L150)):*
> ```Go
> 	defer zonesRF.Close()
> 
> 	noopCheckpointInterval := s.checkpointNoopsEvery
> ```

It's odd to see the `SQLWatcher` configured with a `checkpointNoopsEvery` field that is then ignored (at least on this code path). It seems more natural to consult the testing knob during construction instead. In fact, we may want to push the responsibility of consulting the knob to above the constructor, since the constructor already accepts a `checkpointNoopsEvery` parameter.
___
*[pkg/spanconfig/spanconfigtestutils/spanconfigtestcluster/cluster.go, line 99 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73416#-MqFhH6r2QPVDwtcmCLp:-MqFhH6r2QPVDwtcmCLq:bih7yhx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a67af449f2e88f09266783e398cf587e8c39d2a5/pkg/spanconfig/spanconfigtestutils/spanconfigtestcluster/cluster.go#L99)):*
> ```Go
> 	for _, tenantState := range h.ts {
> 		tenantState.cleanup()
> 	}
> ```

Should it also clear `h.ts`?
___
*[pkg/spanconfig/spanconfigtestutils/spanconfigtestcluster/tenant_state.go, line 50 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73416#-MqFgly22LbWG-HTdqSU:-MqFgly22LbWG-HTdqSV:b-feuge2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a67af449f2e88f09266783e398cf587e8c39d2a5/pkg/spanconfig/spanconfigtestutils/spanconfigtestcluster/tenant_state.go#L50)):*
> ```Go
> 
> // WithMutableTableDescriptor invokes the provided callback with a mutable table
> // descriptor, changes to which are then committed back to the system.
> ```

The callback needs to be idempotent, right? I'm assuming it can be called multiple times if the DescsTxn hits a retryable error.
___
*[pkg/spanconfig/spanconfigtestutils/spanconfigtestcluster/tenant_state.go, line 69 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73416#-MqFggQ7AMbtk3Rf0uU-:-MqFggQ7AMbtk3Rf0uU0:b-jb2t3i) ([raw file](https://github.com/cockroachdb/cockroach/blob/a67af449f2e88f09266783e398cf587e8c39d2a5/pkg/spanconfig/spanconfigtestutils/spanconfigtestcluster/tenant_state.go#L69)):*
> ```Go
> 			},
> 		)
> 		require.NoError(s.t, err)
> ```

nit here and below: should we be returning these errors instead of immediately asserting that they are nil here? We're already asserting that the `sql.DescsTxn` function returns no error. And this might be an error that is handled by whoever is calling the closure, like a txn retry error.
___
*[pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/datadriven_test.go, line 96 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73416#-MqFiLnZEem8brJbxY9B:-MqFiLnZEem8brJbxY9C:b-f30zny) ([raw file](https://github.com/cockroachdb/cockroach/blob/a67af449f2e88f09266783e398cf587e8c39d2a5/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/datadriven_test.go#L96)):*
> ```Go
> 
> 		var tenant *spanconfigtestcluster.Tenant
> 		if strings.Contains(path, "tenant") {
> ```

Should we be more specific about where in the path the term "tenant" exists? For instance, make this condition that the bottom-level directory is exactly "tenant"?

**Review by arulajmani — APPROVED** [review]
> Reviewed 8 of 8 files at r1, 11 of 12 files at r2, 9 of 20 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73416)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @irfansharif)

___
*[pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go, line 403 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73416#-MqF55og0drcdLFh-Z0-:-MqF55og0drcdLFh-Z00:b3tcc3w) ([raw file](https://github.com/cockroachdb/cockroach/blob/d199581639982b3d042fb9e943762b294e716b51/pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go#L403)):*
> ```Go
> // span configuration state. The timestamp at which such a translation is valid
> // is also returned.
> func FullTranslate(
> ```

Having this next to the interface definitions was intentional, could you revert this change please.

**Review by irfansharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73416)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @irfansharif, and @nvanbenschoten)

___
*[pkg/spanconfig/spanconfig.go, line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73416#-MqFdVIMEIBdhmeO7bqC:-MqFlp1z7XxUfXp8H94Y:bp3aow6) ([raw file](https://github.com/cockroachdb/cockroach/blob/eea11eebb70c81b6a998e3a12721e4d342a90e0b/pkg/spanconfig/spanconfig.go#L109)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Did this need to move? It's part of the `spanconfig` interface, not it's implementation, so it feels like it should live here and not in `pkg/sql/spanconfig/spanconfigsqltranslator`.
</blockquote></details>

Reverted.
___
*[pkg/spanconfig/testing_knobs.go, line 69 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73416#-MqFdy9b6OtlYHxiZDYC:-MqFlrlz6HnLHDigml71:bgbduvb) ([raw file](https://github.com/cockroachdb/cockroach/blob/d199581639982b3d042fb9e943762b294e716b51/pkg/spanconfig/testing_knobs.go#L69)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Appear missing to whom?
</blockquote></details>

To the SQLTranslator (in the previous sentence). Later this comment is reworded to include the Reconciler as well.
___
*[pkg/spanconfig/spanconfigsqlwatcher/sqlwatcher.go, line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73416#-MqFeZtz6HFX-quJ3PHa:-MqFmNys9qYttrda87LD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d199581639982b3d042fb9e943762b294e716b51/pkg/spanconfig/spanconfigsqlwatcher/sqlwatcher.go#L150)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It's odd to see the `SQLWatcher` configured with a `checkpointNoopsEvery` field that is then ignored (at least on this code path). It seems more natural to consult the testing knob during construction instead. In fact, we may want to push the responsibility of consulting the knob to above the constructor, since the constructor already accepts a `checkpointNoopsEvery` parameter.
</blockquote></details>

Done.
___
*[pkg/spanconfig/spanconfigtestutils/spanconfigtestcluster/tenant_state.go, line 50 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73416#-MqFgly22LbWG-HTdqSU:-MqFmiYk8H7UOjoDfAgH:b8eqox4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a67af449f2e88f09266783e398cf587e8c39d2a5/pkg/spanconfig/spanconfigtestutils/spanconfigtestcluster/tenant_state.go#L50)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The callback needs to be idempotent, right? I'm assuming it can be called multiple times if the DescsTxn hits a retryable error.
</blockquote></details>

Done (specified idempotency in the comment).
___
*[pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/datadriven_test.go, line 96 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/73416#-MqFiLnZEem8brJbxY9B:-MqFnvll1dLK8MBDqMs-:b-mg7iof) ([raw file](https://github.com/cockroachdb/cockroach/blob/a67af449f2e88f09266783e398cf587e8c39d2a5/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/datadriven_test.go#L96)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we be more specific about where in the path the term "tenant" exists? For instance, make this condition that the bottom-level directory is exactly "tenant"?
</blockquote></details>

Hm, if it's all the same I'd prefer to keep it as is. Checking for the bottom-level directory would preclude adding sub-directories within these tests. We could test for the directory immediately below the testdata path, but for bazel paths that would take a bit more string mangling:

`/private/var/tmp/_bazel_irfansharif/99e666e4e674209ecdb66b46371278df/sandbox/darwin-sandbox/207/execroot/cockroach/bazel-out/darwin-fastbuild/bin/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/spanconfigsqltranslatorccl_test_/spanconfigsqltranslatorccl_test.runfiles/cockroach/pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/tenant/misc`

**Comment by irfansharif** [comment]
TFTRs!

bors r+

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 5 of 28 files at r4, 3 of 15 files at r5, 18 of 23 files at r6, 5 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73416#-:-MqFxVeD7IN09rYfS_9l:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @irfansharif)

**Comment by irfansharif** [comment]
Caught a flakey test.

bors r+

**Pull request merged**
