### PR TITLE
cli: minor cleanup to TestDeclarativeRules

### PR DESCRIPTION
**Pull request by RaduBerinde**
Epic: none
Release note: None

### CODE REVIEW

**Review by fqazi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115117#-:-NkIlbzz78VAou_pw3YW:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Xiang-Gu)

**Comment by RaduBerinde** [comment]
TFTR!

bors r+

**Review by dt — APPROVED** [review]

**Comment by RaduBerinde** [comment]
bors retry

**Pull request merged**
