### PR TITLE
parser: adjust ALTER TENANT ALL syntax

### PR DESCRIPTION
**Pull request by rafiss**
This change brings the syntax inline to what was proposed in the RFC.
This is worthwhile since it matches with the syntax we use in other
"ALL" cases -- notably `ALTER ROLE ALL SET ...``.

Release justification: low risk update to new functionality
Release note: None

### CODE REVIEW

**Review by knz — APPROVED** [review]
nice, thanks

**Review by ajstorm — APPROVED** [review]
Fancy!  :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77519#-:-Mxin0oW4ph96-nZjjIB:b6uk2qf)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by rafiss** [comment]
seems like an unrelated flake

bors r=knz,ajstorm

**Comment by rafiss** [comment]
error was
```
root@127.92.221.248:26257/movr> \demo restart 3
node 3 has been restarted
root@127.92.221.248:26257/movr> select node_id, draining, decommissioning, membe rship from crdb_internal.gossip_liveness ORDER BY node_id;
  node_id | draining | decommissioning | membership
----------+----------+-----------------+-------------
        1 |  false   |      false      | active
        2 |  false   |      false      | active
        3 |   true   |      false      | active
        4 |  false   |      false      | active
        5 |  false   |      false      | active
(5 rows)


Time: 1ms total (execution 1ms / network 0ms)

root@127.92.221.248:26257/movr> 
.220309 16:54:15.699234348 EXPECT TEST: TIMEOUT WAITING FOR "3 |  false   |      false      | active"
non-zero exit code: 1
```

this is captured in https://github.com/cockroachdb/cockroach/issues/76448

**Pull request merged**
