### PR TITLE
sql: coherent handling of hidden session vars in info_schema

### LINKED ISSUE #109870: sql: hidden session vars are hidden in pg_catalog but not information_schema
**Describe the problem**

I can see hidden session vars (e.g. `ssl`) in `information_schema.session_variables`.

**Expected behavior**

If they are hidden in `pg_catalog` they should be hidden in `information_schema` too.

Jira issue: CRDB-31127

Epic CRDB-28893

### PR DESCRIPTION
**Pull request by knz**
Fixes #109870.
Epic: CRDB-28893

Release note (bug fix): Certain SQL session variables are meant
to be hidden from introspection but were showing up in
`information_schema.session_variables`, which was incoherent with the
handling in `pg_catalog.pg_settings`. This bug has now been fixed.

### CODE REVIEW

**Comment by knz** [comment]
@rafiss the second and third commit are "nice to have"; i'm not too attached to them if you don't like them. LMK

**Review by rafiss — APPROVED** [review]
thank you! the thing i'm less sure about is hiding the experimental settings. we don't do that for most experimental cluster settings. also, in the future if we start auto-generating docs for session variables, i think it could be good to include experimental settings too. however, i'm also fine to revisit this later at that point if you think it should be hidden now.

all the other changes lgtm; especially hiding the ones that are aliases

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109872#-:-NdGFraK4QXMFDPF0w21:b-rzfd64)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by knz** [comment]
> i think it could be good to include experimental settings too 

ok I will restore these.

**Comment by knz** [comment]
Done.

bors r=rafiss

**Pull request merged**
