### PR TITLE
sql: add TestSchemaChangeRetryError

### PR DESCRIPTION
**Pull request by vivekmenezes**
This reproduces the problem seen in #17698. It's gonna take some
work to fix.

Release note: None

### CODE REVIEW

**Comment by vivekmenezes** [comment]
@andreimatei FYI

**Review by justinj — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29648#-:-LLjppkmCscpezt2QYZh:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/schema_changer_test.go, line 3508 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29648#-LLjp_AE1cM3lFexknyt:-LLjp_AE1cM3lFexknyu:b-yk6y3f) ([raw file](https://github.com/cockroachdb/cockroach/blob/831038d5a10636dd6388347d920389acc1c63ae6/pkg/sql/schema_changer_test.go#L3508)):*
> ```Go
> 	}
> 
> 	sqlDB1 := tc.ServerConn(1)
> ```

Maybe call this `otherSqlDB` or something to get around the 0-indexing making this read a bit weird?
___
*[pkg/sql/schema_changer_test.go, line 3530 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29648#-LLjpuTA7NgVKo48idd6:-LLjpuTA7NgVKo48idd7:b-nnmc9m) ([raw file](https://github.com/cockroachdb/cockroach/blob/831038d5a10636dd6388347d920389acc1c63ae6/pkg/sql/schema_changer_test.go#L3530)):*
> ```Go
> 
> 	// Fix #17698. The transaction should get retried without returning
> 	// this error to the user.
> ```

Consider prefixing this with a `TODO` to highlight that the behaviour seen here is undesirable.

**Review by vivekmenezes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29648)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/schema_changer_test.go, line 3508 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29648#-LLjp_AE1cM3lFexknyt:-LLjvAhH4VNMNqWY_8zF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/831038d5a10636dd6388347d920389acc1c63ae6/pkg/sql/schema_changer_test.go#L3508)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Maybe call this `otherSqlDB` or something to get around the 0-indexing making this read a bit weird?
</blockquote></details>

Done.
___
*[pkg/sql/schema_changer_test.go, line 3530 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/29648#-LLjpuTA7NgVKo48idd6:-LLjvC-T2HfBUBQRwBqn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/831038d5a10636dd6388347d920389acc1c63ae6/pkg/sql/schema_changer_test.go#L3530)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Consider prefixing this with a `TODO` to highlight that the behaviour seen here is undesirable.
</blockquote></details>

Done.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29648)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/schema_changer_test.go, line 3518 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29648#-LLkJVhF5mCmVsmIXjQA:-LLkJVhHCL-pENJSUdSf:blntsiv) ([raw file](https://github.com/cockroachdb/cockroach/blob/794be468a8aa8639d3695bda29ef44001abc1ae7/pkg/sql/schema_changer_test.go#L3518)):*
> ```Go
> 
> 	if _, err := tx.Exec(`
> 		CREATE TABLE t.another (k INT PRIMARY KEY, v INT, pi DECIMAL DEFAULT (DECIMAL '3.14'));
> ```

What does this table have to do with anything?
___
*[pkg/sql/schema_changer_test.go, line 3529 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29648#-LLkIc2xBGkhvew110ux:-LLkIc2y5RXxzGgMNyUr:bn9mjpp) ([raw file](https://github.com/cockroachdb/cockroach/blob/794be468a8aa8639d3695bda29ef44001abc1ae7/pkg/sql/schema_changer_test.go#L3529)):*
> ```Go
> 	}
> 
> 	// TODO(andreimatei): fix #17698. The transaction should get retried
> ```

The name on a TODO indicates the person to ask about it. I have no idea what's going on :)
Also the PR description has no info. And this test appears to test the opposite of what it claims... Why is it merged? :)

**Review by vivekmenezes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29648)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/schema_changer_test.go, line 3518 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29648#-LLkJVhF5mCmVsmIXjQA:-LLkYll1-YsXQ6r8vJKu:b4astul) ([raw file](https://github.com/cockroachdb/cockroach/blob/794be468a8aa8639d3695bda29ef44001abc1ae7/pkg/sql/schema_changer_test.go#L3518)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

What does this table have to do with anything?
</blockquote></details>

when the schema change below is the second command only then the retry error happens below. I believe it's because our sql executor doesn't have the logic to correctly rewind this case.
___
*[pkg/sql/schema_changer_test.go, line 3529 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29648#-LLkIc2xBGkhvew110ux:-LLkZ0LN2x3lvER3uwhW:bkennnl) ([raw file](https://github.com/cockroachdb/cockroach/blob/794be468a8aa8639d3695bda29ef44001abc1ae7/pkg/sql/schema_changer_test.go#L3529)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

The name on a TODO indicates the person to ask about it. I have no idea what's going on :)
Also the PR description has no info. And this test appears to test the opposite of what it claims... Why is it merged? :)
</blockquote></details>

It is currently testing the failure. I wanted to ensure that this was documented and merged so that you, me or someone else would eventually fix it. I would have not merged it if you were around, and I'd like to discuss how we could fix this test. The issue remains open.

**Pull request merged**
