### PR TITLE
build,cmd/github-post: add nightly Pebble metamorphic tests

### PR DESCRIPTION
**Pull request by jbowens**
Add a new teamcity script to run the Pebble metamorphic tests under
stress each night.

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
Does this need to be a `roachtest`? I'm wondering why we can't just run the metamorphic test directly on the TeamCity test runner. It isn't like that VM is doing anything else other than waiting for the roachtest to finish.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51887#-:-MDFfF3U8i7iiIM2PTHy:b-pl6aep)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @petermattis)

**Review by jbowens — COMMENTED** [review]
ok @itsbilal, @petermattis — this PR is ready for your :eyes: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51887#-:-MHO2u9X96PaockhiAwE:bkicsf2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal)

**Review by petermattis — COMMENTED** [review]
The new `*pebble-metamorphic.sh` script LGTM. My knowledge of `github-post` and `internal/issues` is quite stale. The changes there look fine, though perhaps someone like @tbg should give them a looksie.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51887#-:-MHklLIt7dWF6UyOktwN:b-ek89c3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal and @petermattis)

**Comment by tbg** [comment]
A looksie (i.e. shallow review) was given. Looks good, thank you! This will also help having a roachtest-specific template. (I think @irfansharif was looking into that?)

**Review by tbg — APPROVED** [review]

**Comment by jbowens** [comment]
TFTRs!

bors r+

**Pull request merged**
