### PR TITLE
asim: add lease preference testing

### LINKED ISSUE #111838: kvserver: use simulator to evaluate 23.2 allocation changes
We should use the Simulator to evaluate any 23.2 changes, related to MR or other.

Jira issue: CRDB-32088

### PR DESCRIPTION
**Pull request by kvoli**
Add support for parsing and asserting on lease preferences in simulator
tests. This commit adds support for asserting on the number of leases
violating preferences and the number of leases on store's with less
preferred localities/attributes.

Resolves: https://github.com/cockroachdb/cockroach/issues/111838
Release note: None

### CODE REVIEW

**Review by wenyihu6 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114080)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/asim/assertion/assert.go` line 337 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/114080#-Nioeqe8DLHlr_3DkGO3:-Nioeqe8DLHlr_3DkGO4:botdm3h) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a86d51c8c9a92d89cc843b058c264e2bedfed66/pkg/kv/kvserver/asim/assertion/assert.go#L337)):*
> ```Go
> 				lessPreferred = append(lessPreferred, roachpb.ConformanceReportedRange{
> 					RangeDescriptor: *r.Descriptor(),
> 					Config:          *spanConf,
> ```

Can r.Descriptor() or spanConf ever be nil?
___
*[`pkg/kv/kvserver/asim/assertion/assert.go` line 342 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/114080#-NioewleBeu8t_7c-MBe:-NioewleBeu8t_7c-MBf:b-ya81ng) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a86d51c8c9a92d89cc843b058c264e2bedfed66/pkg/kv/kvserver/asim/assertion/assert.go#L342)):*
> ```Go
> 				violating = append(violating, roachpb.ConformanceReportedRange{
> 					RangeDescriptor: *r.Descriptor(),
> 					Config:          *spanConf,
> ```

Same as above
___
*[`pkg/kv/kvserver/asim/assertion/assert.go` line 360 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/114080#-NiofMT75V24zXS8tBbQ:-NiofMT75V24zXS8tBbR:b64hp8e) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a86d51c8c9a92d89cc843b058c264e2bedfed66/pkg/kv/kvserver/asim/assertion/assert.go#L360)):*
> ```Go
> ) (holds bool, reason string) {
> 	replicaReport := h.S.Report()
> 	leaseViolatingPrefs, leaseLessPref := leasePreferenceReport(ctx, h)
> ```

nit: leaseViolatingPref or  leaseLessPrefs
___
*[`pkg/kv/kvserver/asim/tests/testdata/non_rand/example_lease_preferences` line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/114080#-NiofY-61InOiV0HLiUE:-NiofY-61InOiV0HLiUF:bold58l) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a86d51c8c9a92d89cc843b058c264e2bedfed66/pkg/kv/kvserver/asim/tests/testdata/non_rand/example_lease_preferences#L25)):*
> ```
> # The second span config will be impossible to satisfy, so should produce a
> # violation. The last span config lease preferences will be only satisfiable by
> # a less preferred preference.
> ```

I'm interested to learn what less preferred means. It's impossible to satisfy the lease preference since there are no nodes in region C. Why is this less preferred compared to the second span config producing a violation?

**Comment by wenyihu6** [comment]
oops didn't mean to request changes, just nits - my first time reviewing PRs 😭

**Review by kvoli — COMMENTED** [review]
> oops didn't mean to request changes, just nits - my first time reviewing PRs 😭

Completely fine to request changes :smile:. Thanks for taking a look, updated a few pieces from your review.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114080#-:-Niokk3lBwlF4L6ojGsl:b-3hhtz4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @wenyihu6)

___
*[`pkg/kv/kvserver/asim/assertion/assert.go` line 337 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/114080#-Nioeqe8DLHlr_3DkGO3:-NiojkmS0NGNi8-L7VvZ:b-toc5t2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a86d51c8c9a92d89cc843b058c264e2bedfed66/pkg/kv/kvserver/asim/assertion/assert.go#L337)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

Can r.Descriptor() or spanConf ever be nil?
</blockquote></details>

Descriptor cant be nil, we reference a value on the range struct here https://github.com/kvoli/cockroach/blob/7a86d51c8c9a92d89cc843b058c264e2bedfed66/pkg/kv/kvserver/asim/state/impl.go#L1406-L1406

spanConf isn't guaranteed to be non-nil here, but for all purposes will be (see the range split logic) -- we assume its non-nil in many other parts of the asim code.
___
*[`pkg/kv/kvserver/asim/assertion/assert.go` line 360 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/114080#-NiofMT75V24zXS8tBbQ:-NiokZzqBZbUnkjW-6ZD:b-7jkqvk) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a86d51c8c9a92d89cc843b058c264e2bedfed66/pkg/kv/kvserver/asim/assertion/assert.go#L360)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

nit: leaseViolatingPref or  leaseLessPrefs
</blockquote></details>

Updated to `leaselessPrefs`.
___
*[`pkg/kv/kvserver/asim/tests/testdata/non_rand/example_lease_preferences` line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/114080#-NiofY-61InOiV0HLiUE:-NiohtOtBRFUwyC07AJ1:b38qibu) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a86d51c8c9a92d89cc843b058c264e2bedfed66/pkg/kv/kvserver/asim/tests/testdata/non_rand/example_lease_preferences#L25)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

I'm interested to learn what less preferred means. It's impossible to satisfy the lease preference since there are no nodes in region C. Why is this less preferred compared to the second span config producing a violation?
</blockquote></details>

Ordering is wrong way round for the 2nd and last span config comment. I updated to switch them back. 

A less preferred preference is one which in the lease preferences list, but not the first entry. Lease preferences are ordered, from most preferred to less preferred. The idea being, if one locality goes down, the 2nd locality will gain the lease etc.

**Review by wenyihu6 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114080#-:-Nioli8UB3Rkgc_DGFyI:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/asim/tests/testdata/non_rand/example_lease_preferences` line 25 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/114080#-NiofY-61InOiV0HLiUE:-Niol_57BIvbqIHhzwJ8:bydqpu2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a86d51c8c9a92d89cc843b058c264e2bedfed66/pkg/kv/kvserver/asim/tests/testdata/non_rand/example_lease_preferences#L25)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Ordering is wrong way round for the 2nd and last span config comment. I updated to switch them back. 

A less preferred preference is one which in the lease preferences list, but not the first entry. Lease preferences are ordered, from most preferred to less preferred. The idea being, if one locality goes down, the 2nd locality will gain the lease etc.
</blockquote></details>

Ahh i see. Makes sense. Thanks for the explanation!

**Comment by kvoli** [comment]
TYFTR!

bors r=wenyihu6

**Comment by kvoli** [comment]
Retrying, failure unrelated.

bors r=wenyihu6

**Pull request merged**
