### PR TITLE
sql/opt/memo: chunk allocate logical properties

### PR DESCRIPTION
**Pull request by petermattis**
Only a small time delta, but a significant reduction in allocs which is
likely worthwhile regardless.

```
name                      old time/op    new time/op    delta
Phases/kv-read/OptBuild     17.3µs ± 3%    17.0µs ± 2%   -1.89%  (p=0.015 n=10+10)
Phases/kv-read/Normalize    17.1µs ± 3%    17.1µs ± 2%     ~     (p=0.631 n=10+10)
Phases/kv-read/Explore      22.2µs ± 2%    22.0µs ± 5%     ~     (p=0.400 n=9+10)

name                      old alloc/op   new alloc/op   delta
Phases/kv-read/OptBuild     7.78kB ± 0%    7.97kB ± 0%   +2.47%  (p=0.000 n=10+10)
Phases/kv-read/Normalize    7.78kB ± 0%    7.97kB ± 0%   +2.47%  (p=0.000 n=10+10)
Phases/kv-read/Explore      9.23kB ± 0%    9.42kB ± 0%   +2.08%  (p=0.000 n=10+10)

name                      old allocs/op  new allocs/op  delta
Phases/kv-read/OptBuild       68.0 ± 0%      57.0 ± 0%  -16.18%  (p=0.000 n=10+10)
Phases/kv-read/Normalize      68.0 ± 0%      57.0 ± 0%  -16.18%  (p=0.000 n=10+10)
Phases/kv-read/Explore        77.0 ± 0%      66.0 ± 0%  -14.29%  (p=0.000 n=10+10)
```

Release note: None

### CODE REVIEW

**Review by andy-kimball — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28680)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/memo.go, line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28680#-LK02d-A4HJemZCP0FV5:-LK02d-B7e177jkB-tmT:b-us9y4v) ([raw file](https://github.com/cockroachdb/cockroach/blob/de2ddcd7f57bcd7f3afbf6374c999ed4b9d92fb5/pkg/sql/opt/memo/memo.go#L136)):*
> ```Go
> 	root BestExprID
> 
> 	logPropsFactory logicalPropsBuilder
> ```

This is what I have in my branch:
```
	// logPropsBuilder is inlined in the memo so that it can be reused each time
	// scalar or relational properties need to be built.
	logPropsBuilder logicalPropsBuilder
```

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28680)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/memo/memo.go, line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28680#-LK02d-A4HJemZCP0FV5:-LK1UH4UBknlVx3eS4vh:b-s5oy57) ([raw file](https://github.com/cockroachdb/cockroach/blob/de2ddcd7f57bcd7f3afbf6374c999ed4b9d92fb5/pkg/sql/opt/memo/memo.go#L136)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

This is what I have in my branch:
```
	// logPropsBuilder is inlined in the memo so that it can be reused each time
	// scalar or relational properties need to be built.
	logPropsBuilder logicalPropsBuilder
```
</blockquote></details>

Done. I'll let your PR merge first.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28680#-:-LK1wwQ130kDC5Kfq4f1:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/memo/logical_props_builder.go, line 1286 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28680#-LK1wPDy5TWcJdtlGYP1:-LK1wPDy5TWcJdtlGYP2:bpbnz5i) ([raw file](https://github.com/cockroachdb/cockroach/blob/58d76e93bbb6b7390d02885f0c0e25aa1f862c93/pkg/sql/opt/memo/logical_props_builder.go#L1286)):*
> ```Go
> 		// size. A larger chunk size can be a pessimization as the GC has to scan
> 		// the pointers in any unallocated entries. A value of 2 was chosen at this
> 		// captures scans from a single relation and a 2 way joins.
> ```

[nit] a 2 way -> 2 way
___
*[pkg/sql/opt/memo/memo.go, line 138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28680#-LK1wmWpAUPkMrbyjrIk:-LK1wmWpAUPkMrbyjrIl:b-7pfjbz) ([raw file](https://github.com/cockroachdb/cockroach/blob/58d76e93bbb6b7390d02885f0c0e25aa1f862c93/pkg/sql/opt/memo/memo.go#L138)):*
> ```Go
> 	// logPropsBuilder is inlined in the memo so that it can be reused each time
> 	// scalar or relational properties need to be built.
> 	logPropsBuilder logicalPropsBuilder // logPropsBuilder is inlined in
> ```

extra comment at end of line

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28680)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/memo/logical_props_builder.go, line 1286 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28680#-LK1wPDy5TWcJdtlGYP1:-LK2J38C4Ga_QFGmA6u2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/58d76e93bbb6b7390d02885f0c0e25aa1f862c93/pkg/sql/opt/memo/logical_props_builder.go#L1286)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] a 2 way -> 2 way
</blockquote></details>

Done.
___
*[pkg/sql/opt/memo/memo.go, line 138 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28680#-LK1wmWpAUPkMrbyjrIk:-LK2J4Nk37lpqN88GBju:bbexbat) ([raw file](https://github.com/cockroachdb/cockroach/blob/58d76e93bbb6b7390d02885f0c0e25aa1f862c93/pkg/sql/opt/memo/memo.go#L138)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

extra comment at end of line
</blockquote></details>

Hmm, not sure where that came from. I think I copied this code from Andy, but it isn't present in his comment above. Removed.

**Review by rytaft — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28680)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by petermattis** [comment]
bors r=andy-kimball,rytaft

**Pull request merged**
