### PR TITLE
sql: add support for DROP PROCEDURE

### PR DESCRIPTION
**Pull request by mgartner**
#### sql/logictest: move DROP FUNCTION tests to drop_routine file

The new logic test file `drop_routine` will contain tests for
`DROP FUNCTION` and `DROP PROCEDURE` in future commits.

Release note: None

#### sql: rename tree.DropFunction to tree.DropRoutine

Release note: None

#### sql/parser: add DROP PROCEDURE syntax

This commit updates the parser so that the `DROP PROCEDURE` statement
can be parsed.

Release note: None

#### sql: rename ErrFunctionUndefined to ErrRoutineUndefined

This commit generalized `ErrFunctionUndefined` to `ErrRoutineUndefined`
in preparation of its usage for undefined procedures. In addition,
redundant text in the error message has been removed.

Release note: None

#### sql: add support for DROP PROCEDURE

The `DROP PROCEDURE` statement has been implemented. It relies on most
of the existing logic supporting `DROP FUNCTION`. The majority of
changes are plumbing the type of routine to resolvers and error
messages.

Epic: CRDB-25388

Release note: None

### CODE REVIEW

**Review by rharding6373 — APPROVED** [review]
:lgtm: Nice!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111808#-:-Ng-h7u8BP8GZpjQ0pr7:b-8gk8uj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball, @ecwall, @mgartner, and @miretskiy)

___
*[`pkg/sql/delegate/show_function.go` line 42 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/111808#-Ng-fdKY4lpvcYtOprAo:-Ng-fdKY4lpvcYtOprAp:bnuxbfe) ([raw file](https://github.com/cockroachdb/cockroach/blob/36faeb95d5eaf650882c198d60fbe1f996c233e2/pkg/sql/delegate/show_function.go#L42)):*
> ```Go
> 		fn, err = resolvableFunctionReference.Resolve(d.ctx, searchPath, d.catalog)
> 	} else {
> 		// TODO(mgartner): We can probably make the distinction between the two
> ```

nit: could you open an issue and put the issue number in if this isn't going to be a priority for 23.2? Here and below.
___
*[`pkg/sql/parser/sql.y` line 4915 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111808#-Ng-bXaB0lO-Up5fxbBE:-Ng-bXaB0lO-Up5fxbBF:bpyfpwu) ([raw file](https://github.com/cockroachdb/cockroach/blob/75486b3009a2f881fab0233de5dc752787a26c8d/pkg/sql/parser/sql.y#L4915)):*
> ```Yacc
>     $$.val = &tree.DropRoutine{
>       IfExists: true,
>       Routines: $5.routineObjs(),
> ```

I think this change should have been in the previous commit (r2), but it doesn't matter much as long as these commits aren't split.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111808)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @ecwall, @miretskiy, and @rharding6373)

___
*[`pkg/sql/delegate/show_function.go` line 42 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/111808#-Ng-fdKY4lpvcYtOprAo:-Ng-oct25PgPLosaaP46:bd6xhwm) ([raw file](https://github.com/cockroachdb/cockroach/blob/36faeb95d5eaf650882c198d60fbe1f996c233e2/pkg/sql/delegate/show_function.go#L42)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

nit: could you open an issue and put the issue number in if this isn't going to be a priority for 23.2? Here and below.
</blockquote></details>

I'd like to get this cleaned up, but there's a bunch of other things that are higher priority.

Is the preference for issue numbers in TODOs instead of names a new guideline that I've missed? I usually use my username unless it's something related to a user-facing bug or limitation.
___
*[`pkg/sql/parser/sql.y` line 4915 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111808#-Ng-bXaB0lO-Up5fxbBE:-Ng-plk7Ez4mJgCFMXW0:b-p1u6ho) ([raw file](https://github.com/cockroachdb/cockroach/blob/75486b3009a2f881fab0233de5dc752787a26c8d/pkg/sql/parser/sql.y#L4915)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

I think this change should have been in the previous commit (r2), but it doesn't matter much as long as these commits aren't split.
</blockquote></details>

Great catch! I fixed this—a `sql.y` that doesn't compile would be very annoying to encounter during a `git bisect`.

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r1, 3 of 7 files at r2, 49 of 49 files at r8, 4 of 4 files at r9, 23 of 23 files at r10, 35 of 35 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111808#-:-Ng1cWvOAI45JqD3oZWd:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ecwall, @mgartner, @miretskiy, and @rharding6373)

___
*[`pkg/sql/sem/tree/function_definition.go` line 278 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/111808#-Ng1W9SR1BGPiRZ5KnFU:-Ng1W9SR1BGPiRZ5KnFV:b-j5cipp) ([raw file](https://github.com/cockroachdb/cockroach/blob/944ec4c3a0377ff21647ca6964ad568dd7dbae82/pkg/sql/sem/tree/function_definition.go#L278)):*
> ```Go
> 	findMatches := func(schema string) {
> 		for i := range fd.Overloads {
> 			if procedure && fd.Overloads[i].Type != ProcedureRoutine ||
> ```

[nit] Can we add parentheses to make the precedence clear here?

**Review by mgartner — COMMENTED** [review]
I had to make some edits to get the code working properly.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111808#-:-Ng5NEA03Kzr5BDNnrcD:b-nkmzg8)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball, @ecwall, @miretskiy, and @rharding6373)

___
*[`pkg/sql/sem/tree/function_definition.go` line 278 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/111808#-Ng1W9SR1BGPiRZ5KnFU:-Ng5N9LU4BolMaVGSW2e:b-swpu9o) ([raw file](https://github.com/cockroachdb/cockroach/blob/944ec4c3a0377ff21647ca6964ad568dd7dbae82/pkg/sql/sem/tree/function_definition.go#L278)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Can we add parentheses to make the precedence clear here?
</blockquote></details>

This code is diferent now, and there should be no ambiguity.

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 53 of 53 files at r12, 31 of 31 files at r13, 41 of 41 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111808#-:-Ng5Zk1b-UUp9kPBWkK6:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ecwall, @miretskiy, and @rharding6373)

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
