### PR TITLE
storage: account for sideloaded data in Replica.mu.raftLogSize

### LINKED ISSUE #18077: sideloading: 2x disk usage after a restore
When restoring X bytes of data, you need 2X (plus some headroom) of available space on the cluster. This is because (until the new tables get some traffic) the raft log for the new ranges is not truncated, so an entire copy of the restored data ends up sitting in raft logs.

We fixed this once by making the raft log truncation work by both number of entries and total size, but it seems there's a regression when it comes to sideloading. Perhaps the truncation threshold logic doesn't take into account the fully hydrated command size?

### PR DESCRIPTION
**Pull request by petermattis**
Fixes #18077

### CODE REVIEW

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/18098#-:-KsuTnTv7EUg4IVzj86a:bnfp4nl)*

**Comment by petermattis** [comment]
@cuongdo Can you test another restore and see if this reduces the resulting data size multiple?

**Comment by cuongdo** [comment]
Yes, doing that now.

**Comment by cuongdo** [comment]
👍 

The RESTOREd data is now 17 GB, exactly as expected.

**Pull request merged**
