### PR TITLE
distsql: buffer messages in routers

### LINKED ISSUE #17097: distsql: distributed plans can deadlock
I am filing this "master" issue to keep track of our discussions on this problem.

One instance of the problem is described in https://github.com/cockroachdb/cockroach/issues/16875#issuecomment-315939351

Another possible instance is illustrated below:
image
We have a table reader that's feeding input to two Merge Joiner shards. These output their results to a final processor, which uses an "ordered" synchronizer to maintain ordering. Now suppose that we read a bunch of rows that all go to hash bucket 1 (can easily happen if they all have the same value). Also assume that the merge joiner already produced some rows and is blocked trying to send rows to the ordered synchronizer. The ordered synchronizer needs to read a row from both sides to decide which row to let through first. So the synchronizer is blocked trying to read a row from the right input. But the only way this will ever receive any rows is if the table reader sends something to the merge join on the right; which it won't because it is blocked.

One proposal from @knz is to introduce buffering wherever multiple inputs go to a single processor (joiners, ordered synchronizer). Deciding when it is necessary is not trivial however.

@arjunravinarayan points out that we can alternatively buffer on the output side, only when we have multiple consumers and some are blocked and others aren't. We currently only have a single case where a processor outputs to multiple consumers: the hash router.

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### distsql: generalize outbox.start calls

We will require a start call for the new hash router, similar to outboxes.
Making the flow code keep track of a list of generic `startable`s instead of
outboxes. Also moving the WaitGroup.Add() calls inside start.

#### distsql: minor cleanup to router tests

Remove the factory methods and just use `makeRouter`. Also remove a duplicate
`ConsumerClosed` call.

#### distsql: buffer messages in routers

This change implements RFC #17105 to avoid deadlocks in distsql: instead of the
routers blocking whenever some consumer is blocked, they now block only when all
consumers are blocked.

The router tests are adjusted; they need to be more relaxed as the consumer
state changes are no longer synchronous. Also enabling the deadlock test and
adding a new test that verifies the router blocks when expected (I verified the
test fails if we remove the semaphore).

Fixes #17097.

### CODE REVIEW

**Comment by arjunravinarayan** [comment]
LGTM commit 1 through 4. Will review commit 5 soon.

---

Reviewed 4 of 4 files at r1, 1 of 1 files at r2, 10 of 10 files at r3, 1 of 1 files at r4, 3 of 6 files at r5.
Review status: 16 of 19 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/distsqlrun/flow.go, line 108 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqPUlWQIAY9W74CyqG0:-KqPUlWQIAY9W74CyqG1:b-dodzdi) ([raw file](https://github.com/cockroachdb/cockroach/blob/207ebad849ab3745a38c0595bdef0d3683f2672f/pkg/sql/distsqlrun/flow.go#L108)):*
> ```Go
> 	flowRegistry *flowRegistry
> 	processors   []processor
> 	startables   []startable
> ```

`startable` is vague enough a name that it now needs a comment. `outbox` was more self explanatory.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-:-KqPbmd-8ivDdWWmfN7A:b4da7rn)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/distsqlrun/flow.go, line 108 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqPUlWQIAY9W74CyqG0:-KqPg-0L-rScGPWZ5UYF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/207ebad849ab3745a38c0595bdef0d3683f2672f/pkg/sql/distsqlrun/flow.go#L108)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

`startable` is vague enough a name that it now needs a comment. `outbox` was more self explanatory.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328)*

**Comment by knz** [comment]
LGTM, modulo missing comments. I am confident this implements the scheme set forward in the RFC. Curious about further comments from other reviewers.

---

Reviewed 3 of 4 files at r1, 16 of 16 files at r6, 1 of 1 files at r7, 10 of 10 files at r8, 1 of 1 files at r9, 6 of 6 files at r10.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/routers.go, line 85 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqSUVkdWCocIIAhGRYm:-KqSUVkeKtiWUkJht72j:bd1wnz4) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f1204b33d6ce44e2557b871053e5b89eb3c4e49/pkg/sql/distsqlrun/routers.go#L85)):*
> ```Go
> 
> 		// The "level 2" rowContainer is used when we need to buffer more rows than
> 		// rowBuf allows. The rowContainer always contains rows "older" than those
> ```

Extend the comment to remind the reader the oldest rows are present at the beginning.

---

*[pkg/sql/distsqlrun/routers.go, line 142 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqSUgAstnxD7Eilx70r:-KqSUgAtS6urqfCo7Rmb:bia7w5r) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f1204b33d6ce44e2557b871053e5b89eb3c4e49/pkg/sql/distsqlrun/routers.go#L142)):*
> ```Go
> }
> 
> const semaphorePeriod = 8
> ```

Please add a comment for this constant.

---

*[pkg/sql/distsqlrun/routers_test.go, line 177 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqSV1c0bL9kI3c-W-D9:-KqSV1c0bL9kI3c-W-DA:b-3yf32t) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f1204b33d6ce44e2557b871053e5b89eb3c4e49/pkg/sql/distsqlrun/routers_test.go#L177)):*
> ```Go
> 		}
> 
> 		flowCtx := FlowCtx{evalCtx: parser.MakeTestingEvalContext()}
> ```

The repetition in logic here, above and below suggest an abstraction in a common function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-:-KqSVQilZ-IFtJvzKIBc:bnr2mhr)*

**Comment by RaduBerinde** [comment]
TFTR!

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/routers.go, line 85 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqSUVkdWCocIIAhGRYm:-KqSkI7AzU7mwED7L3Yb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f1204b33d6ce44e2557b871053e5b89eb3c4e49/pkg/sql/distsqlrun/routers.go#L85)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Extend the comment to remind the reader the oldest rows are present at the beginning.
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/routers.go, line 142 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqSUgAstnxD7Eilx70r:-KqSkTHW2ZfpR-j1sZxX:biuns51) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f1204b33d6ce44e2557b871053e5b89eb3c4e49/pkg/sql/distsqlrun/routers.go#L142)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please add a comment for this constant.
</blockquote></details>

We have a comment just below that explains it. I added a pointer to it here.

---

*[pkg/sql/distsqlrun/routers_test.go, line 177 at r10](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqSV1c0bL9kI3c-W-D9:-KqSrY0kpRXfwfOw0g5O:b-hjnrde) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f1204b33d6ce44e2557b871053e5b89eb3c4e49/pkg/sql/distsqlrun/routers_test.go#L177)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

The repetition in logic here, above and below suggest an abstraction in a common function.
</blockquote></details>

Done (in a separate commit).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-:-KqSrl3n4gGjLkD2yPaV:b-814g8k)*

**Comment by andreimatei** [comment]
:lgtm: nice

---

Reviewed 1 of 19 files at r11, 1 of 1 files at r12, 1 of 10 files at r13, 1 of 6 files at r15.
Review status: 2 of 19 files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsqlrun/aggregator.go, line 99 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqTJG716d8DH_N_GDZS:-KqTJG716d8DH_N_GDZT:bsj5jl8) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d137a2d11dad457eb4f37ab88124a60cb5191b0/pkg/sql/distsqlrun/aggregator.go#L99)):*
> ```Go
> 	buckets map[string]struct{} // The set of bucket keys.
> 
> 	processorBase
> ```

nit: if you embed it, make it the first member

---

*[pkg/sql/distsqlrun/flow.go, line 211 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqTPOXUFX8oETlevad5:-KqTPOXV30Vj3f4Wfqqj:bcawiw) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e13aadb4dc5eef0419761e70c829b1764f0c368/pkg/sql/distsqlrun/flow.go#L211)):*
> ```Go
> }
> 
> func (f *Flow) setupRouter(spec *OutputRouterSpec) (router, error) {
> ```

carry over comment about passthrough routers not being supported

---

*[pkg/sql/distsqlrun/flow.go, line 240 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqTPTvCTCqfCBWH4UMK:-KqTPTvCTCqfCBWH4UML:b-u1yczy) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e13aadb4dc5eef0419761e70c829b1764f0c368/pkg/sql/distsqlrun/flow.go#L240)):*
> ```Go
> 	for i := range ps.Output {
> 		spec := &ps.Output[i]
> 		if spec.Type == OutputRouterSpec_PASS_THROUGH {
> ```

please say something about how passthrough are special

---

*[pkg/sql/distsqlrun/processors.go, line 50 at r12](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqTHeqf5qhV9hAJjtad:-KqTHeqf5qhV9hAJjtae:b1a9j1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e2f1fbeed63db2460a8c9367ffe8abfd585d464/pkg/sql/distsqlrun/processors.go#L50)):*
> ```Go
> 	outputCols  []uint32
> 
> 	outputTypes []sqlbase.ColumnType
> ```

members around here deserve some comments now. At most one (but also none) of `outputCols` and `renderExprs` is set? And is `outputTypes` parallel to the one of `outputCols/renderExprs` that's filled in, if any, and otherwise this will be set to the "internal schema"?

---

*[pkg/sql/distsqlrun/processors.go, line 302 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqTJYThFHAbeM0NKPeF:-KqTJYThFHAbeM0NKPeG:b-w9fxwn) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d137a2d11dad457eb4f37ab88124a60cb5191b0/pkg/sql/distsqlrun/processors.go#L302)):*
> ```Go
> }
> 
> type processorBase struct {
> ```

what's the point of this new type? Why not embed `procOutputHelper` in the processors directly?

---

*[pkg/sql/distsqlrun/routers.go, line 40 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqTLp50Zkv1TBds-zj0:-KqTLp50Zkv1TBds-zj1:b-el7ntg) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e13aadb4dc5eef0419761e70c829b1764f0c368/pkg/sql/distsqlrun/routers.go#L40)):*
> ```Go
> }
> 
> // makeRouter creates a router and returns it as a RowReceiver. If the router
> ```

stale comment?

---

*[pkg/sql/distsqlrun/routers.go, line 44 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqTP7RfqOo-DjHchwaD:-KqTP7RfqOo-DjHchwaE:b-t4qf92) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e13aadb4dc5eef0419761e70c829b1764f0c368/pkg/sql/distsqlrun/routers.go#L44)):*
> ```Go
> // called before the router can be started.
> //
> // Passthrough routers are not supported; they should be handled separately.
> ```

can you suggest why? I guess they don't actually exist, so maybe say that a higher layer is expected to elide them

---

*[pkg/sql/distsqlrun/routers.go, line 69 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqTQGwMS3yPe3G6T8vC:-KqTQGwMS3yPe3G6T8vD:bwn9ntm) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e13aadb4dc5eef0419761e70c829b1764f0c368/pkg/sql/distsqlrun/routers.go#L69)):*
> ```Go
> 	mu     struct {
> 		syncutil.Mutex
> 		cond         *sync.Cond
> ```

say something about when this is signaled? Every time something is buffered or the producer says it's done?

---

*[pkg/sql/distsqlrun/routers.go, line 80 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqTQcMshnozNdQJ40EP:-KqTQcMtJBupRsm-mPut:b-4wrrqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e13aadb4dc5eef0419761e70c829b1764f0c368/pkg/sql/distsqlrun/routers.go#L80)):*
> ```Go
> 		rowBufLeft, rowBufLen uint32
> 
> 		// The "level 2" rowContainer is used when we need to buffer more rows than
> ```

why the need for the two levels? What's expensive about the `rowContainer`?

---

*[pkg/sql/distsqlrun/routers.go, line 143 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqTRh0yc0AOrTH2pKT6:-KqTRh0yc0AOrTH2pKT7:b-mv0xaq) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e13aadb4dc5eef0419761e70c829b1764f0c368/pkg/sql/distsqlrun/routers.go#L143)):*
> ```Go
> type routerBase struct {
> 	outputs []routerOutput
> 	numCols int
> ```

I don't see this `numCols` being used...

---

*[pkg/sql/distsqlrun/routers.go, line 196 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqTSM9lVfoMqnehu9DY:-KqTSM9lVfoMqnehu9DZ:bxif3s1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e13aadb4dc5eef0419761e70c829b1764f0c368/pkg/sql/distsqlrun/routers.go#L196)):*
> ```Go
> 	wg.Add(len(rb.outputs))
> 	for i := range rb.outputs {
> 		go func(rb *routerBase, ro *routerOutput, wg *sync.WaitGroup, x int) {
> ```

I don't see `x` being used... 

---

*[pkg/sql/distsqlrun/routers.go, line 210 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqTSh8RpmGPPvFyp-9c:-KqTSh8RpmGPPvFyp-9d:b-f5tayz) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e13aadb4dc5eef0419761e70c829b1764f0c368/pkg/sql/distsqlrun/routers.go#L210)):*
> ```Go
> 
> 					status := ro.stream.Push(nil /*row*/, m)
> 					rb.updateStreamState(&streamStatus, status)
> ```

nit: move the `updateStreamState` out of the semaphore region to make it clear that the semaphore is about the `Push()` call blocking

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-:-KqTVn6_fhebFRgrADrf:bb76hxo)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 19 files reviewed at latest revision, 15 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/aggregator.go, line 99 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqTJG716d8DH_N_GDZS:-KqTcGK_70sRpiJ_Uj7c:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d137a2d11dad457eb4f37ab88124a60cb5191b0/pkg/sql/distsqlrun/aggregator.go#L99)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: if you embed it, make it the first member
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/flow.go, line 211 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqTPOXUFX8oETlevad5:-KqTcqsvmqWGcu6xDLkw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e13aadb4dc5eef0419761e70c829b1764f0c368/pkg/sql/distsqlrun/flow.go#L211)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

carry over comment about passthrough routers not being supported
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/flow.go, line 240 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqTPTvCTCqfCBWH4UMK:-KqTcrIjijkgaw7JiihT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e13aadb4dc5eef0419761e70c829b1764f0c368/pkg/sql/distsqlrun/flow.go#L240)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

please say something about how passthrough are special
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/processors.go, line 50 at r12](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqTHeqf5qhV9hAJjtad:-KqTgAQ60mnKNKym44Uh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e2f1fbeed63db2460a8c9367ffe8abfd585d464/pkg/sql/distsqlrun/processors.go#L50)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

members around here deserve some comments now. At most one (but also none) of `outputCols` and `renderExprs` is set? And is `outputTypes` parallel to the one of `outputCols/renderExprs` that's filled in, if any, and otherwise this will be set to the "internal schema"?
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/processors.go, line 302 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqTJYThFHAbeM0NKPeF:-KqTcwBwQ0wLZIcK0LrE:bkp73hw) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d137a2d11dad457eb4f37ab88124a60cb5191b0/pkg/sql/distsqlrun/processors.go#L302)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

what's the point of this new type? Why not embed `procOutputHelper` in the processors directly?
</blockquote></details>

1. I don't want the procOutHelper methods to suddenly be methods on the processor.
2. We may add more stuff here (the FlowCtx is a prime candidate).
3. I don't want to change the many calls to `proc.out.something`

---

*[pkg/sql/distsqlrun/routers.go, line 40 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqTLp50Zkv1TBds-zj0:-KqTdYsF5CCSmJtkA8vS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e13aadb4dc5eef0419761e70c829b1764f0c368/pkg/sql/distsqlrun/routers.go#L40)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

stale comment?
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/routers.go, line 44 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqTP7RfqOo-DjHchwaD:-KqTdH1r7GhB18t7Scu3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e13aadb4dc5eef0419761e70c829b1764f0c368/pkg/sql/distsqlrun/routers.go#L44)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

can you suggest why? I guess they don't actually exist, so maybe say that a higher layer is expected to elide them
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/routers.go, line 69 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqTQGwMS3yPe3G6T8vC:-KqTdwlSxCmFE-C-lEdv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e13aadb4dc5eef0419761e70c829b1764f0c368/pkg/sql/distsqlrun/routers.go#L69)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

say something about when this is signaled? Every time something is buffered or the producer says it's done?
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/routers.go, line 80 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqTQcMshnozNdQJ40EP:-KqTdl-9_gYRrf8A-kUK:b-uxqxj2) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e13aadb4dc5eef0419761e70c829b1764f0c368/pkg/sql/distsqlrun/routers.go#L80)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

why the need for the two levels? What's expensive about the `rowContainer`?
</blockquote></details>

Memory accounting, for one.

---

*[pkg/sql/distsqlrun/routers.go, line 143 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqTRh0yc0AOrTH2pKT6:-KqTe3-cUVwpyb1lanuZ:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e13aadb4dc5eef0419761e70c829b1764f0c368/pkg/sql/distsqlrun/routers.go#L143)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I don't see this `numCols` being used...
</blockquote></details>

Removed.

---

*[pkg/sql/distsqlrun/routers.go, line 196 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqTSM9lVfoMqnehu9DY:-KqTegAWR8A-YbOm5avE:b-29kflr) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e13aadb4dc5eef0419761e70c829b1764f0c368/pkg/sql/distsqlrun/routers.go#L196)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I don't see `x` being used... 
</blockquote></details>

Sorry, leftover from some debugging messages.

---

*[pkg/sql/distsqlrun/routers.go, line 210 at r15](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqTSh8RpmGPPvFyp-9c:-KqTenUJJ7le-vJfcNSo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e13aadb4dc5eef0419761e70c829b1764f0c368/pkg/sql/distsqlrun/routers.go#L210)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: move the `updateStreamState` out of the semaphore region to make it clear that the semaphore is about the `Push()` call blocking
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328)*

**Comment by asubiotto** [comment]
Reviewed 3 of 19 files at r11, 1 of 16 files at r16, 1 of 1 files at r17, 10 of 10 files at r18, 1 of 1 files at r19, 6 of 6 files at r20, 1 of 1 files at r21.
Review status: all files reviewed at latest revision, 22 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/flow.go, line 316 at r16](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqUB2CXgcDzzqJxPdHL:-KqUB2CY9iuwSEpqE9PF:bnaz27c) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a792e07a109348262f7e964f83f8ee0db703b8a/pkg/sql/distsqlrun/flow.go#L316)):*
> ```Go
> 	f.doneFn = doneFn
> 	log.VEventf(
> 		ctx, 1, "starting (%d processors, %d startables)", len(f.startables), len(f.processors),
> ```

`len(f.startables)` and `len(f.processors)` are in the wrong position

---

*[pkg/sql/distsqlrun/flow.go, line 328 at r16](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqUAujTf0KP3EYqwXks:-KqUAujUUkdtPyn_qonE:b-uvn7yd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a792e07a109348262f7e964f83f8ee0db703b8a/pkg/sql/distsqlrun/flow.go#L328)):*
> ```Go
> 		log.Infof(ctx, "registered flow %s", f.id.Short())
> 	}
> 	for _, o := range f.startables {
> ```

`s/o/s`?

---

*[pkg/sql/distsqlrun/outbox.go, line 60 at r16](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqUBb_3DktPsaZCdS15:-KqUBb_3DktPsaZCdS16:bnvioyg) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a792e07a109348262f7e964f83f8ee0db703b8a/pkg/sql/distsqlrun/outbox.go#L60)):*
> ```Go
> }
> 
> var _ RowReceiver = &outbox{}
> ```

Not sure if it's a convention or not, but maybe add `var _ starter = &outbox{}`

---

*[pkg/sql/distsqlrun/routers.go, line 99 at r20](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqYODW5_fO-Zv_6gvK9:-KqYODW5_fO-Zv_6gvKA:borz62j) ([raw file](https://github.com/cockroachdb/cockroach/blob/e626263fc86aa0eccaa2677695eeaf633b616b97/pkg/sql/distsqlrun/routers.go#L99)):*
> ```Go
> }
> 
> // addRowLocked adds a row to rowBuf (potentially evicting an older row into
> ```

s/an older/the oldest

---

*[pkg/sql/distsqlrun/routers.go, line 202 at r20](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqYR-5E-RL1WJdY2tBx:-KqYR-5E-RL1WJdY2tBy:bc3gylo) ([raw file](https://github.com/cockroachdb/cockroach/blob/e626263fc86aa0eccaa2677695eeaf633b616b97/pkg/sql/distsqlrun/routers.go#L202)):*
> ```Go
> 			for {
> 				// Send any metadata that has been buffered.
> 				if len(ro.mu.metadataBuf) > 0 {
> ```

What are the ordering guarantees between metadata and rows? It seems to me that row A can be pushed before metadata B but metadata B is sent over before row A, does that matter?

---

*[pkg/sql/distsqlrun/routers.go, line 204 at r20](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqYPOhq52K2kV7W7gfj:-KqYPOhq52K2kV7W7gfk:b5pqjpb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e626263fc86aa0eccaa2677695eeaf633b616b97/pkg/sql/distsqlrun/routers.go#L204)):*
> ```Go
> 				if len(ro.mu.metadataBuf) > 0 {
> 					m := ro.mu.metadataBuf[0]
> 					ro.mu.metadataBuf = ro.mu.metadataBuf[1:]
> ```

Add `ro.mu.metadataBuf[0] = nil` to mark the memory for garbage collection

---

*[pkg/sql/distsqlrun/routers_test.go, line 547 at r21](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqYW2pVwWCsp5Zz4lWl:-KqYW2pVwWCsp5Zz4lWm:b-pb93kq) ([raw file](https://github.com/cockroachdb/cockroach/blob/783fa1cc473fb5a06d43106351fd17a7b72cb508/pkg/sql/distsqlrun/routers_test.go#L547)):*
> ```Go
> 			}()
> 
> 			// We are no reading from the row channels; the router should become
> ```

s/no/not

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328)*

**Comment by RaduBerinde** [comment]
Review status: 2 of 19 files reviewed at latest revision, 22 unresolved discussions.

---

*[pkg/sql/distsqlrun/flow.go, line 316 at r16](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqUB2CXgcDzzqJxPdHL:-KqZ1HzAvEJ29d9RrvaB:b-4c5ezp) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a792e07a109348262f7e964f83f8ee0db703b8a/pkg/sql/distsqlrun/flow.go#L316)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

`len(f.startables)` and `len(f.processors)` are in the wrong position
</blockquote></details>

Good catch, done.

---

*[pkg/sql/distsqlrun/flow.go, line 328 at r16](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqUAujTf0KP3EYqwXks:-KqZ1INDWxGX_ohwRSyH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a792e07a109348262f7e964f83f8ee0db703b8a/pkg/sql/distsqlrun/flow.go#L328)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

`s/o/s`?
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/outbox.go, line 60 at r16](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqUBb_3DktPsaZCdS15:-KqZ1RSExudPoM5CZ2bs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a792e07a109348262f7e964f83f8ee0db703b8a/pkg/sql/distsqlrun/outbox.go#L60)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Not sure if it's a convention or not, but maybe add `var _ starter = &outbox{}`
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/routers.go, line 99 at r20](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqYODW5_fO-Zv_6gvK9:-KqZ1atjJ_-x9aH5Db6C:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e626263fc86aa0eccaa2677695eeaf633b616b97/pkg/sql/distsqlrun/routers.go#L99)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

s/an older/the oldest
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/routers.go, line 202 at r20](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqYR-5E-RL1WJdY2tBx:-KqZ1nZHNxbWC7ql6XmI:bocnhui) ([raw file](https://github.com/cockroachdb/cockroach/blob/e626263fc86aa0eccaa2677695eeaf633b616b97/pkg/sql/distsqlrun/routers.go#L202)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

What are the ordering guarantees between metadata and rows? It seems to me that row A can be pushed before metadata B but metadata B is sent over before row A, does that matter?
</blockquote></details>

Good question - it doesn't matter (currently); I added a comment.

---

*[pkg/sql/distsqlrun/routers.go, line 204 at r20](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqYPOhq52K2kV7W7gfj:-KqZ2MVWXeGS7f2SiyC6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e626263fc86aa0eccaa2677695eeaf633b616b97/pkg/sql/distsqlrun/routers.go#L204)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Add `ro.mu.metadataBuf[0] = nil` to mark the memory for garbage collection
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/routers_test.go, line 547 at r21](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328#-KqYW2pVwWCsp5Zz4lWl:-KqZ2XiQsd6xkGLIMHgz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/783fa1cc473fb5a06d43106351fd17a7b72cb508/pkg/sql/distsqlrun/routers_test.go#L547)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

s/no/not
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17328)*

**Review by asubiotto — APPROVED** [review]

**Pull request merged**
