### PR TITLE
ts: Fix occasional dips at leading edge of graphs

### LINKED ISSUE #13537: ui: sql queries graph occasionally drops at the end
screen shot 2017-02-10 at 3 45 18 pm

### PR DESCRIPTION
**Pull request by mrtracy**
As captured in #13537, occasionally our Admin UI graphs will display
precipitous drops at the leading moment of time. This is due to a
combination of clock skew and aggregation:

+ Some nodes have reported the latest datapoint, while others have not
+ The aggregation only includes the datapoints that have reported.

The interpolation system is able to cover gaps like this that occur in
the middle of data, but it was unable to interpolate the most recent
datapoint. This commit adds the ability to interpolate the most recent
data point by assuming the same value as the most recent datapoint.

Note that this interpolation only occurs very explicitly at the current
moment; interpolated datapoints must be within 2 sample periods of the
current wallclock on the server being queried.

Resolves #13537

Release note: Fixed a bug where Admin UI graphs would occasionally have
a persistent "dip" at the leading edge of data.

screen shot 2018-02-07 at 6 33 09 pm

Note this screenshot: the top graph shows an individual series for each node, and clearly demonstrates that data samples are staggered. The second graph is an aggregation, which previously would have displayed a massive dip at the leading edge.

### CODE REVIEW

**Comment by bdarnell** [comment]
:lgtm:, but can we treat this as "no data" instead of continuing the previous data point? That is, the "capacity" graph in the screenshot above should stop at the same time as the short lines on the per-node graph. 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22490#-:-L4pwhgeje36xWDd0AiU:b-ktcgsk)*

**Review by a-robinson — APPROVED** [review]
This makes me so happy. Thanks, @mrtracy!

**Comment by mrtracy** [comment]
@bdarnell yes, we can do the "no-data" fix, but that's different enough in terms of implementation that I'm likely to close this PR and open another one.  Let me make sure it can be done first, I don't think its any more difficult than this fix was.

**Comment by couchand** [comment]
@mrtracy I thought that was just NVD3 behaving poorly.  Thanks for taking care of it!

@bdarnell Good point.  We've discussed implementing that in the middle of the series, but as Matt mentioned it will be a more significant change.  It's being tracked in #17552.

**Comment by mrtracy** [comment]
@couchand These are slightly different issues. This particular dip is caused on the backend by aggregation/interpolation issues (e.g. the final datapoint is the sum of only 1 node out of six, because the other five nodes haven't reported a datapoint yet).  The "gap in the middle" situation occurs when there are no datapoints at all in a gap, but the datapoints are visually connected by a line.

This is a solution to the first issue, but not the second, and it's not particularly similar to a solution for the second.

**Comment by couchand** [comment]
I mean to say, we don't currently have any support for "no data" in the first place, and that would be necessary to make it work here.  On second thought, in this case, since it's the end of the line, returning a series with fewer data points would just render a shorter line, so it probably isn't related.

In the future we may want to visually distinguish missing data, in which case an affirmative "no data" data point would be helpful, but I'm probably getting ahead of myself there.

**Comment by mrtracy** [comment]
Closed in favor of #22570

**Pull request closed without merging**
