### PR TITLE
storage: set default of storage.value_blocks.enabled to true

### PR DESCRIPTION
**Pull request by sumeerbhola**
This enables the use of sstable format TableFormatPebblev3 which improves read performance with MVCC keys with multiple versions.

Informs cockroachdb/pebble#1170

Epic: CRDB-20378

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
I'll run tpcc, kv95, kv0 and report results before merging this PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96669#-:-NNc2baqA7aeOVYeTPHU:b-r04u1r)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens)

**Review by nicktrav — APPROVED** [review]
Exciting! :lgtm: 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96669#-:-NNh7D9w7uISyPni6Hn_:b-cmslz)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens)

**Comment by sumeerbhola** [comment]
tpccbench results are a tiny bit better with value blocks.
enabled=true:
```
20:33:56 tpcc.go:1379: --- SEARCH ITER FAIL: TPCC 3329 resulted in 37727.5 tpmC and failed due to 90th percentile latency for delivery at 6.442450943s exceeds passing threshold of 5s
20:49:31 tpcc.go:1375: --- SEARCH ITER PASS: TPCC 3310 resulted in 41449.2 tpmC (99.3% of max tpmC)
MAX WAREHOUSES = 3319
```

enabled=false
```
01:18:48 tpcc.go:1379: --- SEARCH ITER FAIL: TPCC 3291 resulted in 33020.4 tpmC and failed due to efficiency value of 79.59967171984087 is below passing threshold of 85
01:34:24 tpcc.go:1375: --- SEARCH ITER PASS: TPCC 3253 resulted in 40780.7 tpmC (99.5% of max tpmC)
02:15:27 tpcc.go:1375: --- SEARCH ITER PASS: TPCC 3272 resulted in 41121.1 tpmC (99.7% of max tpmC)
MAX WAREHOUSES = 3281
```

No difference for `kv95/enc=false/nodes=1/cpu=32`. The read-path is all `MVCCGet` so there is no use of `NextPrefix`. Compactions are 0.2% of cpu profile. So the no difference is unsurprising.

Also ran with keys being overwritten (to create more versions) and scans. The following writes to the same 50,000 keys repeatedly and is 5% writes and 95% scans.
```
workload run kv --tolerate-errors --init --histograms=perf/stats.json --concurrency=64 --splits=1000 --duration=15m0s --span-percent=95 --span-limit=100 --cycle-length=50000 --min-block-bytes=100 --max-block-bytes=100 {pgurl:1-1}
```

enabled=true
```
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
  900.0s        0       14539862        16155.4      4.0      3.1     10.0     16.3    385.9  
```
enabled=false
```
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
  900.0s        0       13930731        15478.6      4.1      3.3     10.5     17.8    352.3  
```

Profiles indicated that the improvement is due to `NextPrefix` being cheaper with value blocks. > 50% of the cpu is being spent in SQL optimizer code, which lowers the improvement due to value blocks.
In comparison, v22.2.3, which does not have any `NextPrefix` implementation and ends up doing seeks is even slower than `enabled=false`
```
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
  900.0s        0       12408584        13787.3      4.6      3.5     12.1     19.9    402.7  
```

**Review by sumeerbhola — COMMENTED** [review]
`kv0/enc=false/nodes=1/cpu=32` looks the same, but since there is a large variation between runs I looked at the profiles to see if there is anything related to value blocks. Unsurprisingly, there isn't since the the standard kv workload uniformly distributes across the full range of int64, so keys are not rewritten.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96669#-:-NNt8mG31L-DWASSV1Dk:bc1f1ge)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens)

**Review by nicktrav — APPROVED** [review]
Latest changes :lgtm: Benchmarks look great too, thanks for adding! Any benefit in also doing a run with a larger `--{min,max}-block-bytes`? Do we know what a typical value size is (assuming a large distribution)?

Should we consider making the value blocks setting metamorphic? Or is there limited value given that it's on by default.

> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96669#-:-NNvrT1b1X0aI181TFMV:bf4dfef)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens)

**Review by sumeerbhola — COMMENTED** [review]
> Any benefit in also doing a run with a larger --{min,max}-block-bytes? Do we know what a typical value size is (assuming a large distribution)?

Larger block bytes shifts the bottleneck to compactions, and admission control kicks in frequently, which makes the results generally unpredictable.
It would be good to know the distribution of key and value sizes across the fleet of clusters, and how compressible they are.

> Should we consider making the value blocks setting metamorphic? 

Good point. Done

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96669#-:-NOAJe4R-1iqc5jUjaNT:b-u7ulz7)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens)

**Comment by sumeerbhola** [comment]
TFTR!

**Comment by sumeerbhola** [comment]
bors r=nicktrav

**Pull request merged**
