### PR TITLE
sqlsmith: refactor + add roachtest

### PR DESCRIPTION
**Pull request by madelynnblue**

### CODE REVIEW

**Comment by mjibson** [comment]
This is my first roachtest so comments on the last commit are most interesting to me. The first commits are just some internal sqlsmith refactoring and improvements, no need to be very detailed about them if you don't want to.

**Review by yuzefovich — COMMENTED** [review]
Very nice work! I believe it already found a query cancellation issue, right? :tada:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 6 of 6 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42036#-:-LsTclfk8tUm9nqA-1F6:bbrl7qa)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mjibson)

___
*[pkg/cmd/roachtest/sqlsmith.go, line 29 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42036#-LsTc0HK-NesgiO46noO:-LsTc0HK-NesgiO46noP:boqjc6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/6906b8198cfc00d0fb36a9a3ee8254e2d9f28547/pkg/cmd/roachtest/sqlsmith.go#L29)):*
> ```Go
> 		"seed":  sqlsmith.Setups["seed"],
> 		"tpch-sf1": func(r *rand.Rand) string {
> 			return `RESTORE DATABASE tpch FROM 'gs://cockroach-fixtures/workload/tpch/scalefactor=1/backup';`
> ```

Does the database also need to be created before `RESTORE`?
___
*[pkg/cmd/roachtest/sqlsmith.go, line 64 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42036#-LsTaSaJ97bMkqH_wHRo:-LsTaSaJ97bMkqH_wHRp:bzcq8be) ([raw file](https://github.com/cockroachdb/cockroach/blob/6906b8198cfc00d0fb36a9a3ee8254e2d9f28547/pkg/cmd/roachtest/sqlsmith.go#L64)):*
> ```Go
> 
> 		t.Status("smithing")
> 		until := time.After(time.Hour)
> ```

[nit]: I'd extract `time.Hour` into a const and then use that x 2 in the `testSpec` below.
___
*[pkg/cmd/roachtest/sqlsmith.go, line 103 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42036#-LsTbRQZC8Cl4uGSwSQ7:-LsTbRQZC8Cl4uGSwSQ8:bx0sq70) ([raw file](https://github.com/cockroachdb/cockroach/blob/6906b8198cfc00d0fb36a9a3ee8254e2d9f28547/pkg/cmd/roachtest/sqlsmith.go#L103)):*
> ```Go
> 					// a non-gateway node has crashed.
> 					t.Fatalf("error: %s\nstmt:\n%s;", err, stmt)
> 				}
> ```

What about other errors? Should we log them?
___
*[pkg/cmd/roachtest/sqlsmith.go, line 107 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42036#-LsTcbH92HLzAVTraHF1:-LsTcbH92HLzAVTraHF2:bjq7yuh) ([raw file](https://github.com/cockroachdb/cockroach/blob/6906b8198cfc00d0fb36a9a3ee8254e2d9f28547/pkg/cmd/roachtest/sqlsmith.go#L107)):*
> ```Go
> 
> 			// Ping the gateway to make sure it didn't crash.
> 			if err := conn.PingContext(ctx); err != nil {
> ```

Should we also ping the non-gateway nodes? Or the communication error above will always handle such cases?
___
*[pkg/cmd/roachtest/sqlsmith.go, line 119 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42036#-LsTbq3D6rxTqWJ3878r:-LsTbq3D6rxTqWJ3878s:bunoa9c) ([raw file](https://github.com/cockroachdb/cockroach/blob/6906b8198cfc00d0fb36a9a3ee8254e2d9f28547/pkg/cmd/roachtest/sqlsmith.go#L119)):*
> ```Go
> 			r.Add(testSpec{
> 				Name:    fmt.Sprintf("sqlsmith/setup=%s/setting=%s", setupName, settingName),
> 				Cluster: makeClusterSpec(4),
> ```

What is reasoning behind choosing 4 node cluster?
___
*[pkg/internal/sqlsmith/setup.go, line 176 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42036#-LsT__zJ-gjNcomXt6Yb:-LsT__zJ-gjNcomXt6Yc:bmvbl1c) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6afce9f4a3218b4f344a7c31482fad93166f696/pkg/internal/sqlsmith/setup.go#L176)):*
> ```Go
> }
> 
> // randOptions is the list of SmitherOptions that can be chosen from randomly that are guaranteed to not add mutations or remove determinism from generated queries.
> ```

[nit]: very long line.

**Review by madelynnblue — COMMENTED** [review]
Yes, and the evalctx txn thing.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42036#-:-LsTi7fi76VgDpp30VW1:b-pos79j)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/cmd/roachtest/sqlsmith.go, line 29 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42036#-LsTc0HK-NesgiO46noO:-LsTiAkx8sdAnyYEYb3N:b-tx4twr) ([raw file](https://github.com/cockroachdb/cockroach/blob/6906b8198cfc00d0fb36a9a3ee8254e2d9f28547/pkg/cmd/roachtest/sqlsmith.go#L29)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Does the database also need to be created before `RESTORE`?
</blockquote></details>

Nope, it must not exist.
___
*[pkg/cmd/roachtest/sqlsmith.go, line 64 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42036#-LsTaSaJ97bMkqH_wHRo:-LsTiY5j9Ia9xg7gJF0e:b-18c6i8) ([raw file](https://github.com/cockroachdb/cockroach/blob/6906b8198cfc00d0fb36a9a3ee8254e2d9f28547/pkg/cmd/roachtest/sqlsmith.go#L64)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: I'd extract `time.Hour` into a const and then use that x 2 in the `testSpec` below.
</blockquote></details>

done by using the test spec timeout / 2
___
*[pkg/cmd/roachtest/sqlsmith.go, line 103 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42036#-LsTbRQZC8Cl4uGSwSQ7:-LsTikvr1w0ndAmsfO-6:b97e0ih) ([raw file](https://github.com/cockroachdb/cockroach/blob/6906b8198cfc00d0fb36a9a3ee8254e2d9f28547/pkg/cmd/roachtest/sqlsmith.go#L103)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

What about other errors? Should we log them?
</blockquote></details>

nope, they should be ignored. added a comment.
___
*[pkg/cmd/roachtest/sqlsmith.go, line 107 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42036#-LsTcbH92HLzAVTraHF1:-LsTinDN66Aq_2lCQc5c:b-wz8xo8) ([raw file](https://github.com/cockroachdb/cockroach/blob/6906b8198cfc00d0fb36a9a3ee8254e2d9f28547/pkg/cmd/roachtest/sqlsmith.go#L107)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Should we also ping the non-gateway nodes? Or the communication error above will always handle such cases?
</blockquote></details>

the communication error handles those is my understanding
___
*[pkg/cmd/roachtest/sqlsmith.go, line 119 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42036#-LsTbq3D6rxTqWJ3878r:-LsTirku5NuNsnzCBYxM:bie3jd3) ([raw file](https://github.com/cockroachdb/cockroach/blob/6906b8198cfc00d0fb36a9a3ee8254e2d9f28547/pkg/cmd/roachtest/sqlsmith.go#L119)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

What is reasoning behind choosing 4 node cluster?
</blockquote></details>

at 4 nodes data doesn't live everywhere, so seems like a more interesting case? not a lot of reasoning besides it's more than 1.
___
*[pkg/internal/sqlsmith/setup.go, line 176 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42036#-LsT__zJ-gjNcomXt6Yb:-LsTj9Gf3vo2fsIyIk2O:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6afce9f4a3218b4f344a7c31482fad93166f696/pkg/internal/sqlsmith/setup.go#L176)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: very long line.
</blockquote></details>

Done.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, 6 of 6 files at r7, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42036#-:-LsTkjKy6UQ6eOsl7oAS:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mjibson and @yuzefovich)

___
*[pkg/cmd/roachtest/sqlsmith.go, line 119 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/42036#-LsTbq3D6rxTqWJ3878r:-LsTkRihAddwA9km2yyU:bg2j5hf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6906b8198cfc00d0fb36a9a3ee8254e2d9f28547/pkg/cmd/roachtest/sqlsmith.go#L119)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

at 4 nodes data doesn't live everywhere, so seems like a more interesting case? not a lot of reasoning besides it's more than 1.
</blockquote></details>

Makes sense, thanks.

**Pull request merged**
