### PR TITLE
sql: allow kvBatchSize to be customized

### LINKED ISSUE #33660: roachtest: hotspotsplits/nodes=4 failed
SHA: https://github.com/cockroachdb/cockroach/commits/f5e3c29b2eed92868cf3d449575283e2e383f199

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=hotspotsplits/nodes=4 PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1088848&tab=buildLog

```
The test failed on master:
	test.go:696,hotspotsplits.go:94,hotspotsplits.go:110: dial tcp 35.193.104.30:26257: connect: connection refused

```

### PR DESCRIPTION
**Pull request by rytaft**
This commit allows the `kvBatchSize` to be customized per `txnKVFetcher`
so that `CREATE STATISTICS` jobs can use a smaller batch size. Prior to
this commit, `kvBatchSize` was always 10000 rows for all queries. It
could be customized using a function `SetKVBatchSize`, but that function
is only useful for testing because it changes the value of `kvBatchSize`
at a global level and is not thread safe. This commit makes it possible
to change the batch size locally, and sets the default `kvBatchSize` for
`CREATE STATISTICS` to 1000.

This is necessary to minimize the risk of out-of-memory errors when
running `CREATE STATISTICS` on tables with very wide columns.

Fixes #33660

Release note: None
Release justification: The potential for OOM due to CREATE STATISTICS
makes this category 3: Fixes for high-priority or high-severity
bugs in existing functionality.

### CODE REVIEW

**Comment by rytaft** [comment]
Whoops this is buggy -- please hold off on reviewing

**Review by rytaft — COMMENTED** [review]
Ok -- confirmed that this reduces memory utilization so no machine exceeds utilization of 7 GB during the `hotspotsplits/nodes=4` test.

Ready for review

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40850#-:-Lp0ns3j8BjNWdvlqHxU:b-vke0bm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @RaduBerinde)

**Review by RaduBerinde — COMMENTED** [review]
Code LGTM, just some nits. We should run the tpcc roachtest a few times with and without the change to make sure there is no regression in the # of warehouses. Also run some `CREATE STATISTICS` on a large table to see if there is a lot of perf difference. Thanks!

[nit] we had (and still have) `kvBatchSize` but all the new parameters are called "batch limit". We should keep them consistent (I'd keep "size" for both).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40850#-:-Lp3J90yC8Atzq9N1udd:b-eve7j7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @RaduBerinde, and @rytaft)

___
*[pkg/sql/distsql_plan_stats.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40850#-Lp3I_YZA4KPDfsX0bke:-Lp3I_YZA4KPDfsX0bkf:b-ceqk6o) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fcdd4fd79b2015094d27178606469bbe7e2bd6e/pkg/sql/distsql_plan_stats.go#L41)):*
> ```Go
> const histogramSamples = 10000
> const histogramBuckets = 200
> const kvBatchLimit = 1000
> ```

rename to `statsKVBatchLimit` (`sql.kvBatchLimit` suggests something else)
___
*[pkg/sql/execinfra/rowfetcher.go, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40850#-Lp3JsMRErAEROMGQKE0:-Lp3JsMRErAEROMGQKE1:bu1pgek) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fcdd4fd79b2015094d27178606469bbe7e2bd6e/pkg/sql/execinfra/rowfetcher.go#L83)):*
> ```Go
> 		ValNeededForCol:  valNeededForCol,
> 	}
> 	if err := fetcher.Init(
> ```

Any reason we can't pass it to Init?
I'd also consider renaming `kvBatchSize` to `defaultKVBatchSize` and using that instead of 0 everywhere.
___
*[pkg/sql/row/kv_batch_fetcher.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40850#-Lp3KPhk0MSomziFX1DE:-Lp3KPhk0MSomziFX1DF:bn26bzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fcdd4fd79b2015094d27178606469bbe7e2bd6e/pkg/sql/row/kv_batch_fetcher.go#L36)):*
> ```Go
> 
> // SetKVBatchSize changes the kvBatchFetcher batch size, and returns a function that restores it.
> func SetKVBatchSize(val int64) func() {
> ```

This could be `SetDefaultKVBatchSize` and have it just change the default, rather than always overriding.

**Review by rytaft — COMMENTED** [review]
TFTR! Updated to use batchSize instead of batchLimit.

I'll run some benchmarks now to check performance.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40850#-:-Lp4Ofs_5I-s98z2KXeN:bb3wd54)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @RaduBerinde)

___
*[pkg/sql/distsql_plan_stats.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40850#-Lp3I_YZA4KPDfsX0bke:-Lp4L_207YnZnfzRj2sE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fcdd4fd79b2015094d27178606469bbe7e2bd6e/pkg/sql/distsql_plan_stats.go#L41)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

rename to `statsKVBatchLimit` (`sql.kvBatchLimit` suggests something else)
</blockquote></details>

Done.
___
*[pkg/sql/execinfra/rowfetcher.go, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40850#-Lp3JsMRErAEROMGQKE0:-Lp4JNB14BXzBtJX0rtO:b-secus) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fcdd4fd79b2015094d27178606469bbe7e2bd6e/pkg/sql/execinfra/rowfetcher.go#L83)):*
> Any reason we can't pass it to Init?

Init is called by about 20 other functions, so it just explodes the number of places we'd need to plumb through the `batchSize` param. I can do it if you think that would be cleaner, but I was just trying to keep the footprint of this PR as small as possible...

> I'd also consider renaming kvBatchSize to defaultKVBatchSize and using that instead of 0 everywhere.

Do you think I should export `defaultKVBatchSize`? The places I'm passing 0 are not all in the same package.
___
*[pkg/sql/row/kv_batch_fetcher.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40850#-Lp3KPhk0MSomziFX1DE:-Lp4Ji04BZ3EyjaM5BR9:b-d6j2ky) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fcdd4fd79b2015094d27178606469bbe7e2bd6e/pkg/sql/row/kv_batch_fetcher.go#L36)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This could be `SetDefaultKVBatchSize` and have it just change the default, rather than always overriding.
</blockquote></details>

The problem is that `create_stats_job_test.go` is using this function to set `defaultKVBatchSize` to 10, and I want to make sure that it overrides `statsKVBatchSize`. Do you think it would be better to instead have a `SetStatsKVBatchSize` function to override `statsKVBatchSize`?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40850)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rytaft)

___
*[pkg/sql/execinfra/rowfetcher.go, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40850#-Lp3JsMRErAEROMGQKE0:-Lp4Qsv76p3NVhZ3ipOH:b-94vozr) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fcdd4fd79b2015094d27178606469bbe7e2bd6e/pkg/sql/execinfra/rowfetcher.go#L83)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

> Any reason we can't pass it to Init?

Init is called by about 20 other functions, so it just explodes the number of places we'd need to plumb through the `batchSize` param. I can do it if you think that would be cleaner, but I was just trying to keep the footprint of this PR as small as possible...

> I'd also consider renaming kvBatchSize to defaultKVBatchSize and using that instead of 0 everywhere.

Do you think I should export `defaultKVBatchSize`? The places I'm passing 0 are not all in the same package.
</blockquote></details>

Ah, separate function is ok then. I would export the constant.
___
*[pkg/sql/row/fetcher.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40850#-Lp4RLFKBuIZ9mmhd7Ed:-Lp4RLFKBuIZ9mmhd7Ee:b-8lxto6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab99ab7f408dce93ebe671b5ffdeaf15c5e9b48b/pkg/sql/row/fetcher.go#L47)):*
> ```Go
> 		batchResponse []byte, origSpan roachpb.Span, err error)
> 	GetRangesInfo() []roachpb.RangeInfo
> 	SetBatchSize(batchSize int64)
> ```

A comment here would be good.
___
*[pkg/sql/row/kv_batch_fetcher.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40850#-Lp3KPhk0MSomziFX1DE:-Lp4RC4x7ojZxQXSOBxY:b-2ojr31) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fcdd4fd79b2015094d27178606469bbe7e2bd6e/pkg/sql/row/kv_batch_fetcher.go#L36)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

The problem is that `create_stats_job_test.go` is using this function to set `defaultKVBatchSize` to 10, and I want to make sure that it overrides `statsKVBatchSize`. Do you think it would be better to instead have a `SetStatsKVBatchSize` function to override `statsKVBatchSize`?
</blockquote></details>

Oh,  yeah, `SetStatsKVBatchSize` makes more sense to me
___
*[pkg/sql/row/kv_batch_fetcher.go, line 90 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40850#-Lp4RRN600PLNowd0X4G:-Lp4RRN600PLNowd0X4H:b-ik6v3j) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab99ab7f408dce93ebe671b5ffdeaf15c5e9b48b/pkg/sql/row/kv_batch_fetcher.go#L90)):*
> ```Go
> var _ kvBatchFetcher = &txnKVFetcher{}
> 
> func (f *txnKVFetcher) SetBatchSize(batchSize int64) {
> ```

[nit] SetBatchSize is part of the kvBatchFetcher interface

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40850)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/execinfra/rowfetcher.go, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40850#-Lp3JsMRErAEROMGQKE0:-Lp4d-zr9n7oMlaf2Ne7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fcdd4fd79b2015094d27178606469bbe7e2bd6e/pkg/sql/execinfra/rowfetcher.go#L83)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Ah, separate function is ok then. I would export the constant.
</blockquote></details>

Done.
___
*[pkg/sql/row/fetcher.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40850#-Lp4RLFKBuIZ9mmhd7Ed:-Lp4kmar2ZVm7zxjHmzM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab99ab7f408dce93ebe671b5ffdeaf15c5e9b48b/pkg/sql/row/fetcher.go#L47)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

A comment here would be good.
</blockquote></details>

Done.
___
*[pkg/sql/row/kv_batch_fetcher.go, line 36 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40850#-Lp3KPhk0MSomziFX1DE:-Lp4kp0M6XRHkorvTqC9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fcdd4fd79b2015094d27178606469bbe7e2bd6e/pkg/sql/row/kv_batch_fetcher.go#L36)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Oh,  yeah, `SetStatsKVBatchSize` makes more sense to me
</blockquote></details>

Done.
___
*[pkg/sql/row/kv_batch_fetcher.go, line 90 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40850#-Lp4RRN600PLNowd0X4G:-Lp4dNePC7w4XQZm_zVN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab99ab7f408dce93ebe671b5ffdeaf15c5e9b48b/pkg/sql/row/kv_batch_fetcher.go#L90)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] SetBatchSize is part of the kvBatchFetcher interface
</blockquote></details>

Done.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40850#-:-Lp57XupBj5ekC-yZaI6:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @rytaft)

___
*[pkg/sql/distsql_plan_stats.go, line 54 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40850#-Lp57I2b-pEK5helz8C-:-Lp57I2cAAlBIkAWAred:bim60hb) ([raw file](https://github.com/cockroachdb/cockroach/blob/61c00f848f79b16544e106d099d3f56fc6a5aede/pkg/sql/distsql_plan_stats.go#L54)):*
> ```Go
> )
> 
> var statsKVBatchSize int64 = 1000
> ```

[nit] Add a comment explaining that we want a lower limit for stats to reduce memory usage. And maybe a TODO about improving the SQL-KV interface.

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40850)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis)

___
*[pkg/sql/distsql_plan_stats.go, line 54 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40850#-Lp57I2b-pEK5helz8C-:-Lp5KCVq1Fi5SBcnZXkx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/61c00f848f79b16544e106d099d3f56fc6a5aede/pkg/sql/distsql_plan_stats.go#L54)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] Add a comment explaining that we want a lower limit for stats to reduce memory usage. And maybe a TODO about improving the SQL-KV interface.
</blockquote></details>

Done.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40850)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @rytaft)

___
*[pkg/sql/distsql_physical_planner.go, line 871 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/40850#-Lp537dh2H-mRZDAF64c:-Lp537dh2H-mRZDAF64d:b-3vsafc) ([raw file](https://github.com/cockroachdb/cockroach/blob/61c00f848f79b16544e106d099d3f56fc6a5aede/pkg/sql/distsql_physical_planner.go#L871)):*
> ```Go
> // corresponds to a scanNode, except for the Spans and OutputColumns.
> func initTableReaderSpec(
> 	n *scanNode, planCtx *PlanningCtx, indexVarMap []int, batchSize int64,
> ```

From an API point of view, it might be better to just have the caller set the BatchSize field. That way, every caller doesn't have to pass an extra parameter, and probably end up with different values over time, even though they just want the default. I often like to follow a pattern of only having the "required" (or almost-always-used) parameters passed to constructors, and then any "optional" parameters get set after initial construction. See `optbuilder.Builder` for example, where we construct builder using `New`, and then sometimes set additional attributes afterwards.

**Comment by rytaft** [comment]
Closing this due to the performance issues identified here: https://github.com/cockroachdb/cockroach/issues/33660#issuecomment-533714082

> Unfortunately reducing the batch size to 1000 for stats seems to have a negative impact on performance. I ran the `tpccbench/nodes=3/cpu=16` roachtest twice with the stats batch size set to 1000, and twice with the batch size set to 10000. With 1000, max warehouses was 1315 and 1365. With 10000, it was 1605 and 1685. I'm not sure exactly why the difference is so great, but it seems clear that I should not merge #40850.

**Pull request closed without merging**
