### PR TITLE
cdc: Refactor "tick function" in changefeeds.

### PR DESCRIPTION
**Pull request by miretskiy**
The main function running changefeeds used a series of nested
callbacks to maintain state.  Refactor the inner workings of this
tick function to use consumer/producer interfaces.

The producer, as the name implies, produces KV events (from KV feed),
while consumer is responsible for consuming these events.

The producer and consumer implementations currently do the work previously
done by `emitEntries` and `kvsToRows`.  As much as possible, the actual
implementation of those methods was not changed -- their logic simply moved
inside producer/consumer.

Doing this refactor enables us to extend changefeeds to be able to use
different types of consumers -- for example, consumers that emit raw KVs.

Release Notes: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm_strong: That third commit is a serious improvement. The tickFn code, I suspect, at some point involved some amount of internal buffering, which, as you've revealed, doesn't actually exist anymore. Really nice cleanup!

My preference if I'm being nitpicky is that you peel off the `OptSchemaChangePolicyIgnore` commit and put it in a PR that actually takes advantage of it. On that note, the first commit also feels under-motivated and doesn't have a testing component to demonstrate why it exists. How about just splitting off the third commit to uncontroversially bors straight away as a serious win.

> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59770#-:-MSeq2m067G8TfadAlRn:b-fomhar)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt, @HonoreDB, and @miretskiy)

___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 408 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59770#-MSenyiv8y6F_b0We6ei:-MSenyiv8y6F_b0We6ej:b-a3915v) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e86ec75f5837bae8779bfc9b377b47eea523a1/pkg/ccl/changefeedccl/changefeed_processors.go#L408)):*
> ```Go
> 
> // tick is the workhorse behind Next(). It pulls kv changes from the
> // buffer that poller fills, handles table leasing, converts them to rows,
> ```

the `poller` language is pretty old. Maybe `kvfeed`? There isn't really any polling anymore. 
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 439 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59770#-MSeoWN31UUywKghy2jk:-MSeoWN31UUywKghy2jl:bxnqj0k) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e86ec75f5837bae8779bfc9b377b47eea523a1/pkg/ccl/changefeedccl/changefeed_processors.go#L439)):*
> ```Go
> func (ca *changeAggregator) maybeFlush(resolvedSpan *jobspb.ResolvedSpan) error {
> 	if resolvedSpan != nil {
> 		_ = ca.spanFrontier.Forward(resolvedSpan.Span, resolvedSpan.Timestamp)
> ```

nit: it's not an error, you don't need to `_ = ` with it. 
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 442 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59770#-MSeoSBO71VT1Av81Bwj:-MSeoSBO71VT1Av81Bwk:b-iwrlye) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e86ec75f5837bae8779bfc9b377b47eea523a1/pkg/ccl/changefeedccl/changefeed_processors.go#L442)):*
> ```
> 
> 	if resolvedSpan == nil ||
> ```
nil `else if `?
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 655 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59770#-MSeovxy70eWGP1PGund:-MSeovxz87sx4O0hSFOL:b-m4hf9h) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e86ec75f5837bae8779bfc9b377b47eea523a1/pkg/ccl/changefeedccl/changefeed_processors.go#L655)):*
> ```Go
> }
> 
> // ConsumeEvent implements kvEventConsumer interface
> ```

very nit: put this above the private methods. I prefer when reading a file to hit the raison d'etre for an object and then go unpack helpers as they come into context.

**Review by miretskiy — COMMENTED** [review]
Other commits gone.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59770#-:-MSh77aHCVuSfGj62LqB:bf70niu)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt and @HonoreDB)

___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 408 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59770#-MSenyiv8y6F_b0We6ei:-MSh7Eq4B5ZVhRAqow_t:b-ilai1n) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e86ec75f5837bae8779bfc9b377b47eea523a1/pkg/ccl/changefeedccl/changefeed_processors.go#L408)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

the `poller` language is pretty old. Maybe `kvfeed`? There isn't really any polling anymore. 
</blockquote></details>

Just moved the comment from where tickFN used to be.  Comment updated.
___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 442 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59770#-MSeoSBO71VT1Av81Bwj:-MSh8Bi-7083vFo1vrUU:bat7l8j) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e86ec75f5837bae8779bfc9b377b47eea523a1/pkg/ccl/changefeedccl/changefeed_processors.go#L442)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 
> 	if resolvedSpan == nil ||
> ```
nil `else if `?
</blockquote></details>

Code copied from old code.  Not sure if the code is cleaner w/ else if.

```
if resolvedSpan == nil {
   return
} else {
   sf.Forward()
   if (timeutil.Since(ca.lastFlush) < ca.flushFrequency && !resolvedSpan.BoundaryReached) {
    return
  }
}

```
Going to keep it as is.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59770)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt and @HonoreDB)

___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 655 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59770#-MSeovxy70eWGP1PGund:-MSh9Wv913Ta7ZWXAbg1:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3e86ec75f5837bae8779bfc9b377b47eea523a1/pkg/ccl/changefeedccl/changefeed_processors.go#L655)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

very nit: put this above the private methods. I prefer when reading a file to hit the raison d'etre for an object and then go unpack helpers as they come into context. 
</blockquote></details>

done

**Review by ajwerner — COMMENTED** [review]
It is a little bit alarming that this failed the cdc/bank local roachtest in CI. 

> Reviewed 1 of 3 files at r3, 1 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59770#-:-MShW51XAc_i7chKsKit:b-73eqz0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt and @HonoreDB)

**Comment by miretskiy** [comment]
Looks like the failures are due to permissions changes on the storage
bucket.

**Comment by ajwerner** [comment]
> Looks like the failures are due to permissions changes on the storage
bucket.

We should really confirm this. Where's the thing that only would run this test if you touch CDC? Are we definitively sure this is the case?

**Comment by miretskiy** [comment]
@ajwerner Turns out there was a bug around flushing.  It is now fixed.  Please, take another look.

**Review by ajwerner — COMMENTED** [review]
I don't think I understand this change. Can you add more commentary to elucidate the subtle interactions? I also worry that this now is going to emit a bunch of extra resolved events. 

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59770#-:-MT1T0Ez6-2qmJtITjqC:b-20nspx)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt, @HonoreDB, and @miretskiy)

___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 82 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59770#-MT1T6-qE-P4oNIRFxIR:-MT1T6-qE-P4oNIRFxIS:b-rhkohk) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6468dc5c08df292faa271b9d77c89a74f9fae6e/pkg/ccl/changefeedccl/changefeed_processors.go#L82)):*
> ```
> 	// spansToFlush keeps track of resolved spans that have not been flushed yet.
> 	spansToFlush []*jobspb.ResolvedSpan
> ```
Help me understand this. Not all resolved spans need to be flushed every time. Shouldn't https://github.com/cockroachdb/cockroach/blob/a0b86467f6f442e43dc91e19139e49d0f9a2736e/pkg/ccl/changefeedccl/kvfeed/kv_feed.go#L196 ensure that every relevant span ends up sending a resolved span with the `BoundaryReached` flag?

**Review by miretskiy — COMMENTED** [review]
Discussed in person.  Basically, the old code closed over resolvedSpan array -- and kept accumulating changes there until it was time to flush those spans.  This code restores this behavior in a more straightforward way.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59770#-:-MT1YfrJD_XGjbqAaIGi:b-18xnpo)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt, @HonoreDB, and @miretskiy)

**Review by ajwerner — APPROVED** [review]
:lgtm: but there's clearly some wins to be had here. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59770#-:-MT1YtC_4RNP8CROh55T:b-frw0nk)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt, @HonoreDB, and @miretskiy)

___
*[pkg/ccl/changefeedccl/changefeed_processors.go, line 82 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59770#-MT1T6-qE-P4oNIRFxIR:-MT1XtgX-bXOMffzh5uC:b62rzku) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6468dc5c08df292faa271b9d77c89a74f9fae6e/pkg/ccl/changefeedccl/changefeed_processors.go#L82)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	// spansToFlush keeps track of resolved spans that have not been flushed yet.
> 	spansToFlush []*jobspb.ResolvedSpan
> ```
Help me understand this. Not all resolved spans need to be flushed every time. Shouldn't https://github.com/cockroachdb/cockroach/blob/a0b86467f6f442e43dc91e19139e49d0f9a2736e/pkg/ccl/changefeedccl/kvfeed/kv_feed.go#L196 ensure that every relevant span ends up sending a resolved span with the `BoundaryReached` flag? 
</blockquote></details>

I get it now. This has nothing to do with `BoundaryReached`. This is pretty horrible that we hold onto all of these intermediate resolved spans. It feels like we should add a TODO to compress this. Alternatively, we could just emit the current frontier timestamp for just the set of spans that this change aggregator is tracking. We don't do checkpointing of anything less than the entire changefeed currently so doing that wouldn't break anything. I have a feeling that this would greatly aid in overall scalability of the changefeed when there are a large number of ranges. Imagine we have a rate of resolved checkpoints of ranges * 600ms but then we have a resolved timestamp of 5s. If we have 10k ranges underneath this aggreagtor, we're going to buffer 83k resolved timestamps :/

**Comment by miretskiy** [comment]
tftr
bors r=ajwerner

**Pull request merged**
