### PR TITLE
importccl,*: remove legacy sorted IMPORT

### PR DESCRIPTION
**Pull request by dt**
This removes the 'sorted' implementation of IMPORT which pre-reads and samples to setup a partitioning and then re-reads using that partitioning to route keys to non-overlapping ingestion processes. This initial implementation closely followed how RESTORE ingests data, but doing so incurred additional overhead: multiple read passes, pushing every key, one by one, though distsql, buffering, etc. It was replaced with 'direct' ingestion import where keys are simply ingested as they are read.

However keeping both implementations around in the codebase has started to cause confusion as new team members try to learn the code and start working on new features for the next release, motivating removing the dead code sooner rather than later.

Release note: none.

### CODE REVIEW

**Comment by dt** [comment]
I think we can also just remove all the conditional `experimental_direct_ingest` additions from workload too, since the default `IMPORT` -- whether that is sorted or direct -- should work in any version, so workload/roachtest's cross-version support should be ok with removing it.

**Comment by danhhz** [comment]
\o/

> I think we can also just remove all the conditional experimental_direct_ingest additions from workload too, since the default IMPORT -- whether that is sorted or direct -- should work in any version, so workload/roachtest's cross-version support should be ok with removing it.

sgtm

**Review by pbardea — APPROVED** [review]
🎉
LGTM

> Reviewed 20 of 20 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41417#-:-LqftQBv4HFJuMgW4n31:b-ryu49g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang and @spaskob)

**Review by thoszhang — APPROVED** [review]

**Pull request merged**
