### PR TITLE
replace oss with bsl

### PR DESCRIPTION
**Pull request by tisonkun**
Release note (build change): Replace all OSS occurances with BSL.

This is driven from #78558. I think you guys in CockroachLabs will have another discussion on whether or not and how to make this change. And this patch is an example from my perspective those should be updated reflecting that `buildoss` is actually producing a BSL licensed work.

### CODE REVIEW

**Comment by tisonkun** [comment]
Well. I cannot access the failure logs and thus have no ideas on fixing them. I can run `make buildbsl` locally and get the `cockroachbsl` binary.

**Comment by otan** [comment]
hmm, what do you see when trying to see the logs?

either way, it doesn't seem to compile with `bazel`

```

[01:50:30][Run Bazel build] https://github.com/browserslist/browserslist#browsers-data-updating
[01:50:31][Run Bazel build] ERROR: /go/src/github.com/cockroachdb/cockroach/pkg/ui/distbsl/BUILD.bazel:21:11: GoCompilePkg pkg/ui/distbsl/distbsl.a failed: missing input file '//pkg/ui/distbsl:distbsl.go'
[01:50:31][Run Bazel build] ERROR: /go/src/github.com/cockroachdb/cockroach/pkg/ui/distbsl/BUILD.bazel:21:11: GoCompilePkg pkg/ui/distbsl/distbsl.a failed: 1 input file(s) do not exist
[01:50:32][Run Bazel build] ERROR: /go/src/github.com/cockroachdb/cockroach/pkg/ui/distbsl/BUILD.bazel:21:11 GoCompilePkg pkg/ui/distbsl/distbsl.a failed: 1 input file(s) do not exist
[01:50:32][Run Bazel build] INFO: Elapsed time: 798.339s, Critical Path: 696.72s
[01:50:32][Run Bazel build] INFO: 5984 processes: 593 internal, 5391 processwrapper-sandbox.
```

use `./dev doctor` to get instructions right, then try `./dev build pkg/ui/distbsl:all`. i suspect you need a `./dev bazel generate` to fix the existing failure.

also you'll need to rebase.

cc @jlinder to find the appropriate reviewer

**Comment by tisonkun** [comment]
@otan it asks me for login TeamCity and obviously I don't have a CockroachLabs account 😆.

Let me try to resolve the conflict and dig the build errors.

**Comment by rafiss** [comment]
To clarify, you'll need to run `./dev generate bazel` (not `./dev bazel generate`)

**Comment by tisonkun** [comment]
@rafiss thanks! Tests seem failed on:

```
pkg/migration/migrations/migrations_test_/migrations_test_shard_14/16
```

I don't know whether it's a known issue or something I should try to find the cause. The test name seems unrelated to the change.

**Comment by otan** [comment]
yeah i wouldn't worry about it. someone on the dev-inf should stamp this.

**Comment by tisonkun** [comment]
@otan any update or plan? I'm afraid that this PR will be always conflicted if there is no progress on the review side. It touches many files and I do want to do one or several conflicts fixing.

**Pull request closed without merging**
