### PR TITLE
builtins: support third argument for array_position() built-in

### LINKED ISSUE #109953: sql: support third argument (startIndex) for function array_position
CockroachDB doesn't support third argument for function `array_position`

Error:
```
unknown signature: array_position(int4[], int, int)
```

**Describe the solution you'd like**

```
array_position ( anycompatiblearray, anycompatible [, integer ] ) → integer

Returns the subscript of the first occurrence of the second argument in the array, or NULL if it's not present. If the third argument is given, the search begins at that subscript. The array must be one-dimensional. Comparisons are done using IS NOT DISTINCT FROM semantics, so it is possible to search for NULL.

array_position(ARRAY['sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat'], 'mon') → 2
```

**Additional context**
This affects efcore.pg tests

Jira issue: CRDB-31179

### PR DESCRIPTION
**Pull request by charlespnh**
Resolves: https://github.com/cockroachdb/cockroach/issues/109953

Release note (sql change): The array_position() built-in function with additional third argument was added.

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
thanks for your contribution!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112161#-:-NgZOLRhDMEMHn5zxZhI:b3akoa5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @charlespnh)

___
*[`pkg/sql/sem/builtins/builtins.go` line 3802 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112161#-NgZNrFSCux-N2zbv8Ww:-NgZNrFT1PGQTfS2uKjH:b8uy51c) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4f7afc8ea3281ff85f322478eda62e3922e4025/pkg/sql/sem/builtins/builtins.go#L3802)):*
> ```Go
> 					start := int(tree.MustBeDInt(args[2])) - 1
> 					darray := tree.MustBeDArray(args[0]).Array
> 					if start > len(darray) || start < 1 {
> ```

i don't think the `start < 1` condition matches the PostgreSQL behavior:

```
postgres=# SELECT array_position(ARRAY['sun','mon','tue','wed','thu','fri','sat','mon'], 'wed', 0);
 array_position
----------------
              4

postgres=# SELECT array_position(ARRAY['sun','mon','tue','wed','thu','fri','sat','mon'], 'wed', -1);
 array_position
----------------
              4

postgres=# SELECT array_position(ARRAY['sun','mon','tue','wed','thu','fri','sat','mon'], 'wed', -3);
 array_position
----------------
              4

postgres=# SELECT array_position(ARRAY['sun','mon','tue','wed','thu','fri','sat','mon'], 'wed', 1);
 array_position
----------------
              4
```

It looks like any `start` value less than 1 is implicitly treated as 1. Can you make that change (perhaps include a comment), and add tests for that?
___
*[`pkg/sql/logictest/testdata/logic_test/array` line 1140 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112161#-NgZOGYtBxBCbFZgRUG0:-NgZOGYtBxBCbFZgRUG1:bevi18w) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4f7afc8ea3281ff85f322478eda62e3922e4025/pkg/sql/logictest/testdata/logic_test/array#L1140)):*
> ```
> SELECT array_position(ARRAY['sun','mon','tue','wed','thu','fri','sat','mon'], 'wed', 0)
> ----
> NULL
> ```

in postgres, this returns `4`
___
*[`pkg/sql/logictest/testdata/logic_test/array` line 1146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112161#-NgZP-aHAK7YIUsI567n:-NgZP-aHAK7YIUsI567o:b-j8gpp4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4f7afc8ea3281ff85f322478eda62e3922e4025/pkg/sql/logictest/testdata/logic_test/array#L1146)):*
> ```
> ----
> NULL
> ```

could you add these tests to verify that the second occurrence of an element is found correctly:
```
postgres=# SELECT array_position(ARRAY['sun','mon','tue','wed','thu','fri','sat','mon'], 'mon', 7);
 array_position
----------------
              8
(1 row)

postgres=# SELECT array_position(ARRAY['sun','mon','tue','wed','thu','fri','sat','mon'], 'mon', 1);
 array_position
----------------
              2
```

**Review by charlespnh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112161)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/sem/builtins/builtins.go` line 3802 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112161#-NgZNrFSCux-N2zbv8Ww:-NkBQwWi4b4CZElfrk07:b-fnk889) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4f7afc8ea3281ff85f322478eda62e3922e4025/pkg/sql/sem/builtins/builtins.go#L3802)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i don't think the `start < 1` condition matches the PostgreSQL behavior:

```
postgres=# SELECT array_position(ARRAY['sun','mon','tue','wed','thu','fri','sat','mon'], 'wed', 0);
 array_position
----------------
              4

postgres=# SELECT array_position(ARRAY['sun','mon','tue','wed','thu','fri','sat','mon'], 'wed', -1);
 array_position
----------------
              4

postgres=# SELECT array_position(ARRAY['sun','mon','tue','wed','thu','fri','sat','mon'], 'wed', -3);
 array_position
----------------
              4

postgres=# SELECT array_position(ARRAY['sun','mon','tue','wed','thu','fri','sat','mon'], 'wed', 1);
 array_position
----------------
              4
```

It looks like any `start` value less than 1 is implicitly treated as 1. Can you make that change (perhaps include a comment), and add tests for that?
</blockquote></details>

Change is applied and comment has been added!
___
*[`pkg/sql/logictest/testdata/logic_test/array` line 1140 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112161#-NgZOGYtBxBCbFZgRUG0:-NkBRkmU0fhhGyIK7Gbo:b-b4u0b5) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4f7afc8ea3281ff85f322478eda62e3922e4025/pkg/sql/logictest/testdata/logic_test/array#L1140)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

in postgres, this returns `4`
</blockquote></details>

Change is applied!
___
*[`pkg/sql/logictest/testdata/logic_test/array` line 1146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112161#-NgZP-aHAK7YIUsI567n:-NkBRnk455qGohZAr52B:b-wj4eaj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4f7afc8ea3281ff85f322478eda62e3922e4025/pkg/sql/logictest/testdata/logic_test/array#L1146)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

could you add these tests to verify that the second occurrence of an element is found correctly:
```
postgres=# SELECT array_position(ARRAY['sun','mon','tue','wed','thu','fri','sat','mon'], 'mon', 7);
 array_position
----------------
              8
(1 row)

postgres=# SELECT array_position(ARRAY['sun','mon','tue','wed','thu','fri','sat','mon'], 'mon', 1);
 array_position
----------------
              2
```
</blockquote></details>

Tests added!

**Comment by charlespnh** [comment]
@rafiss Thanks for the feedback! Please let me know if there are any other meaningful tests I should have added

**Review by rafiss — APPROVED** [review]
i added one more test i just thought of, to check for null inputs, which required a change to null handling in the code. thanks for your contribution!

bors r+

**Pull request merged**
