### PR TITLE
admission: refactor locking code in GrantCoordinator

### PR DESCRIPTION
**Pull request by andrewbaptist**
Refactor the GrantCoordinator mutex to use a struct that
includes all the lock protected members.
Remove the GrantCoordinator mutex from ioLoadListener
since its only use case was to protect changes to the
kvStoreTokenGranter which can do the locking itself.

Release note: None
Epic: none

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93086)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist and @irfansharif)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93086#-NJ2lsQV9qoHKcgOtd1y):*
nit: start of sentence should be lower case

"cleanup locks" is overly broad. Suggest something specific like "refactor locking code and names in GrantCoordinator and ioLoadListener". If that is too long "refactor locking code and names" is fine.
___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93086#-NJ2mOS750TW8f4JeaLW):*
Description can be more specific, and the structs are named ioLoadListener and GrantCoordinator. So something like:

- Refactor the GrantCoordinator mutex to use a struct that includes all the lock protected members.
- Remove the GrantCoordinator mutex from ioLoadListener since its only use case was to protect changes to the kvStoreTokenGranter which can do the locking itself. 
- ...
___
*[`pkg/util/admission/admission.go` line 261 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93086#-NJ2nSrcDw3AY9x6cPOf:-NJ2nSrcDw3AY9x6cPOg:b223f7t) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c333c54e1cf6d8e753ed7b676797f187967e778/pkg/util/admission/admission.go#L261)):*
> ```Go
> type granterWithIOTokens interface {
> 	// setAvailableTokens bounds the available tokens that can be granted to the
> 	// value provided in the ioTokens parameter. This is not a tight bound when
> ```

there are 2 parameters, and this comment mostly talks only about one, and then relegates `elasticDiskBandwidthTokens` to a sentence at the end (which also omits part of the original comment "bounds the available tokens that can be granted to elastic work"). I'd suggest rewriting it so that introductory sentence mentions both. 
___
*[`pkg/util/admission/grant_coordinator.go` line 225 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93086#-NJ2oT67ARCgcJWyqX4o:-NJ2oT67ARCgcJWyqX4p:b7131k9) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c333c54e1cf6d8e753ed7b676797f187967e778/pkg/util/admission/grant_coordinator.go#L225)):*
> ```Go
> 
> 	// mu is ordered before any mutex acquired in a requester implementation.
> 	// TODO(sumeer): move everything covered by mu into a nested struct.
> ```

This todo is now done.
___
*[`pkg/util/admission/grant_coordinator.go` line 241 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93086#-NJ2q6uDAhOFfiZrkRxp:-NJ2q6uDAhOFfiZrkRxq:b-1y0lbs) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c333c54e1cf6d8e753ed7b676797f187967e778/pkg/util/admission/grant_coordinator.go#L241)):*
> ```Go
> 		grantChainStartTime time.Time
> 		// NB: Some granters can be nil.
> 		granters [numWorkKinds]granterWithLockedCalls
> ```

Given that all methods on `cpuOverloadIndicator` and `cpuLoadListener` require holding mu, its fine to put them here, but let's keep the `granters` out. Also add a comment saying that none of these references are changing, so the mu protection is not for the pointer.
___
*[`pkg/util/admission/grant_coordinator.go` line 247 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93086#-NJ2porj57xdQKLyiyYB:-NJ2porj57xdQKLyiyYC:bix53lc) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c333c54e1cf6d8e753ed7b676797f187967e778/pkg/util/admission/grant_coordinator.go#L247)):*
> ```Go
> 		cpuOverloadIndicator    cpuOverloadIndicator
> 		cpuLoadListener         CPULoadListener
> 		lastCPULoadSamplePeriod time.Duration
> ```

lastCPULoadSamplePeriod is not protected by mu.
___
*[`pkg/util/admission/grant_coordinator.go` line 664 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93086#-NJ2sTIyEKRL10l3uNIA:-NJ2sTIyEKRL10l3uNIB:b-30ac7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c333c54e1cf6d8e753ed7b676797f187967e778/pkg/util/admission/grant_coordinator.go#L664)):*
> ```Go
> 
> 	coord.mu.Lock()
> 	defer coord.mu.Unlock()
> ```

I don't think this needs to be lifted up.
The calls to `CPULoad` are already serialized and that's the only place we look at `lastCPULoadSamplePeriod`
___
*[`pkg/util/admission/granter.go` line 351 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93086#-NJ3g0axBwuDgj99DTN1:-NJ3g0axBwuDgj99DTN2:b-g1uyxt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c333c54e1cf6d8e753ed7b676797f187967e778/pkg/util/admission/granter.go#L351)):*
> ```Go
> 	elasticRequester requester
> 	// There is no rate limiting in granting these tokens. That is, they are all
> 	// burst tokens.
> ```

I think it's good to have a code comment that says something like
// Protected by coord.mu.Lock.
for each field that is protected in that manner.
___
*[`pkg/util/admission/granter.go` line 544 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93086#-NJ3fSBY5jZQtLYHC40I:-NJ3fSBZ1OuCdwIia6ey:b-u77ewc) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c333c54e1cf6d8e753ed7b676797f187967e778/pkg/util/admission/granter.go#L544)):*
> ```Go
> 	sg.coord.mu.Lock()
> 	defer sg.coord.mu.Unlock()
> 	tokensUsed = sg.startingIOTokens - sg.availableIOTokens
> ```

s/tokensUsed/ioTokensUsed
___
*[`pkg/util/admission/testdata/granter` line 508 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93086#-NJ3iZi34AX0pBWXjvzJ:-NJ3iZi34AX0pBWXjvzK:b3i7aa9) ([raw file](https://github.com/cockroachdb/cockroach/blob/15a761d5aac27782b135f109d1e5a4083c16846a/pkg/util/admission/testdata/granter#L508)):*
> ```
> 
> # kv-elastic is granted.
> set-io-tokens tokens=100
> ```

is there a reason to change this test in this manner, since it is eliminating one of the grants?

```
# kv-elastic is granted.
set-tokens io-tokens=100 elastic-disk-bw-tokens=100300
```
would have kept the first grant

and then
```
# Nothing is granted
set-tokens io-tokens=0 elastic-disk-bw-tokens=50
```
would have kept this second case where nothing is granted

and then
```
# Both kinds of tokens are decremented and become negative.
set-io-tokens tokens=200 elastic-disk-bw-tokens=50
```
___
*[`pkg/util/admission/testdata/granter` line 553 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93086#-NJ3k-Q54G5eQg7-BcUl:-NJ3k-Q54G5eQg7-BcUm:bnmivwo) ([raw file](https://github.com/cockroachdb/cockroach/blob/15a761d5aac27782b135f109d1e5a4083c16846a/pkg/util/admission/testdata/granter#L553)):*
> ```
> (chain: id: 0 active: false index: 5) io-avail: 91, elastic-disk-bw-tokens-avail: -100
> 
> # Even more IO tokens.
> ```

this can be kept by not adding io-tokens.

**Review by irfansharif — COMMENTED** [review]
> Reviewed 4 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93086)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93086#-NJ2lsQV9qoHKcgOtd1y):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: start of sentence should be lower case

"cleanup locks" is overly broad. Suggest something specific like "refactor locking code and names in GrantCoordinator and ioLoadListener". If that is too long "refactor locking code and names" is fine.
</blockquote></details>

Done.
___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93086#-NJ2mOS750TW8f4JeaLW):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Description can be more specific, and the structs are named ioLoadListener and GrantCoordinator. So something like:

- Refactor the GrantCoordinator mutex to use a struct that includes all the lock protected members.
- Remove the GrantCoordinator mutex from ioLoadListener since its only use case was to protect changes to the kvStoreTokenGranter which can do the locking itself. 
- ...
</blockquote></details>

Done.
___
*[`pkg/util/admission/admission.go` line 261 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93086#-NJ2nSrcDw3AY9x6cPOf:-NOTK55l3maH8ETyHqM9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c333c54e1cf6d8e753ed7b676797f187967e778/pkg/util/admission/admission.go#L261)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

there are 2 parameters, and this comment mostly talks only about one, and then relegates `elasticDiskBandwidthTokens` to a sentence at the end (which also omits part of the original comment "bounds the available tokens that can be granted to elastic work"). I'd suggest rewriting it so that introductory sentence mentions both. 
</blockquote></details>

Done.
___
*[`pkg/util/admission/grant_coordinator.go` line 225 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93086#-NJ2oT67ARCgcJWyqX4o:-NOTLk8P57uuVj4BqFvF:bss4a2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c333c54e1cf6d8e753ed7b676797f187967e778/pkg/util/admission/grant_coordinator.go#L225)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This todo is now done.
</blockquote></details>

Removed.
___
*[`pkg/util/admission/grant_coordinator.go` line 241 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93086#-NJ2q6uDAhOFfiZrkRxp:-NOTLE7C3THdFBiqP-Dd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c333c54e1cf6d8e753ed7b676797f187967e778/pkg/util/admission/grant_coordinator.go#L241)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Given that all methods on `cpuOverloadIndicator` and `cpuLoadListener` require holding mu, its fine to put them here, but let's keep the `granters` out. Also add a comment saying that none of these references are changing, so the mu protection is not for the pointer.
</blockquote></details>

Done.
___
*[`pkg/util/admission/grant_coordinator.go` line 247 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93086#-NJ2porj57xdQKLyiyYB:-NOTKhS-4V4IFMjTZ_dY:b-a9hhko) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c333c54e1cf6d8e753ed7b676797f187967e778/pkg/util/admission/grant_coordinator.go#L247)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

lastCPULoadSamplePeriod is not protected by mu.
</blockquote></details>

Done (moved out of the mu struct).
___
*[`pkg/util/admission/grant_coordinator.go` line 664 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93086#-NJ2sTIyEKRL10l3uNIA:-NOTN6nm9HjAG-m0oNV8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c333c54e1cf6d8e753ed7b676797f187967e778/pkg/util/admission/grant_coordinator.go#L664)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I don't think this needs to be lifted up.
The calls to `CPULoad` are already serialized and that's the only place we look at `lastCPULoadSamplePeriod`
</blockquote></details>

Done.
___
*[`pkg/util/admission/granter.go` line 351 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93086#-NJ3g0axBwuDgj99DTN1:-NOTPDCK45VmZXgeq6dr:b-4aiyj9) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c333c54e1cf6d8e753ed7b676797f187967e778/pkg/util/admission/granter.go#L351)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think it's good to have a code comment that says something like
// Protected by coord.mu.Lock.
for each field that is protected in that manner.
</blockquote></details>

Moved relevant fields into a coordMu struct instead.
___
*[`pkg/util/admission/granter.go` line 544 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93086#-NJ3fSBY5jZQtLYHC40I:-NOTRFuN6z-RiMcza7QZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7c333c54e1cf6d8e753ed7b676797f187967e778/pkg/util/admission/granter.go#L544)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

s/tokensUsed/ioTokensUsed
</blockquote></details>

Done.
___
*[`pkg/util/admission/testdata/granter` line 508 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93086#-NJ3iZi34AX0pBWXjvzJ:-NOTKpCU285ix9wYhOKa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/15a761d5aac27782b135f109d1e5a4083c16846a/pkg/util/admission/testdata/granter#L508)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is there a reason to change this test in this manner, since it is eliminating one of the grants?

```
# kv-elastic is granted.
set-tokens io-tokens=100 elastic-disk-bw-tokens=100300
```
would have kept the first grant

and then
```
# Nothing is granted
set-tokens io-tokens=0 elastic-disk-bw-tokens=50
```
would have kept this second case where nothing is granted

and then
```
# Both kinds of tokens are decremented and become negative.
set-io-tokens tokens=200 elastic-disk-bw-tokens=50
```
</blockquote></details>

Done.
___
*[`pkg/util/admission/testdata/granter` line 553 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93086#-NJ3k-Q54G5eQg7-BcUl:-NOTPxzB6Hl_2gA-pmV3:b-ook6p1) ([raw file](https://github.com/cockroachdb/cockroach/blob/15a761d5aac27782b135f109d1e5a4083c16846a/pkg/util/admission/testdata/granter#L553)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

this can be kept by not adding io-tokens.
</blockquote></details>

Done. BTW, don't you mean elastic-disk-bw-tokens?

**Comment by irfansharif** [comment]
CI failure is just https://github.com/cockroachdb/cockroach/issues/97076.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93086)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist)

___
*[`pkg/util/admission/work_queue.go` line 558 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93086#-NOpKkCe3T9c2_PUmUR4:-NOpKkCf41l1wG87mF-2:blme6sg) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ea649160f60de297f650411955b866e934ef672/pkg/util/admission/work_queue.go#L558)):*
> ```Go
> 		// add additional synchronization (and complexity to the granter
> 		// interface) to deal with this, by keeping the granter's lock
> 		// (GrantCoordinator.mu) locked when returning from tryGrantLocked and call
> ```

nit: assuming this change was accidental, since it should continue to say `tryGrant`.
___
*[`pkg/util/admission/testdata/granter` line 553 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93086#-NJ3k-Q54G5eQg7-BcUl:-NOpNlt36lJqAfROs2_J:bheya57) ([raw file](https://github.com/cockroachdb/cockroach/blob/15a761d5aac27782b135f109d1e5a4083c16846a/pkg/util/admission/testdata/granter#L553)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

Done. BTW, don't you mean elastic-disk-bw-tokens?
</blockquote></details>

ah yes.
___
*[`pkg/util/admission/testdata/granter` line 516 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93086#-NOpMpFd78TdjyKKHNfa:-NOpMpFd78TdjyKKHNfb:b-9srsyf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ea649160f60de297f650411955b866e934ef672/pkg/util/admission/testdata/granter#L516)):*
> ```
> set-tokens io-tokens=0 elastic-disk-bw-tokens=50
> ----
> kv-elastic: granted in chain 0, and returning 200
> ```

This looks like a bug in that io-avail is -199, so nothing should be granted. Oddly, both `io-avail` and `elastic-disk-bw-tokens-avail` are unchanged, despite the grant and despite the set-tokens (which should have clamped before the grant).

**Review by irfansharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93086)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist and @sumeerbhola)

___
*[`pkg/util/admission/work_queue.go` line 558 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93086#-NOpKkCe3T9c2_PUmUR4:-NP3Q3Cs7NtEr2fba3uU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ea649160f60de297f650411955b866e934ef672/pkg/util/admission/work_queue.go#L558)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: assuming this change was accidental, since it should continue to say `tryGrant`.
</blockquote></details>

Done.
___
*[`pkg/util/admission/testdata/granter` line 516 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/93086#-NOpMpFd78TdjyKKHNfa:-NP3i-9qAh8g41ov3pmn:bwqazn2) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ea649160f60de297f650411955b866e934ef672/pkg/util/admission/testdata/granter#L516)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

This looks like a bug in that io-avail is -199, so nothing should be granted. Oddly, both `io-avail` and `elastic-disk-bw-tokens-avail` are unchanged, despite the grant and despite the set-tokens (which should have clamped before the grant).
</blockquote></details>

Good catch, this was a actually a bug in the test directive above where instead of four dashes, we had five, and the test data file below that point was not getting updated. Not sure when that happened but fixed.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93086#-:-NP4SPoe4SxpZrCHEmDJ:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist)

**Pull request merged**
