### PR TITLE
sql: death to DOidWrapper

### PR DESCRIPTION
**Pull request by jordanlewis**
This commit makes an explicit DName, removing the last use case for
DOidWrapper, which was a hack that made lots of things harder to deal
with.

Release note: None

### CODE REVIEW

**Comment by otan** [comment]
https://frinkiac.com/meme/S06E22/870652.jpg?b64lines=IERFQVRIIFNUQUxLUwogWU9VIEFUIEVWRVJZIFRVUk4h

**Review by andy-kimball — COMMENTED** [review]
Love to see this going away.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43158#-:-LwEn5aE8Vc7UB7vncfB:b-crttvj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andy-kimball)

**Comment by jordanlewis** [comment]
Okay, so I ran into a ton of problems doing this - I should have expected it.

The fundamental issue is, again, overload resolution. We need to provide extra overloads for all functions that need to expect both string and name, but the overload resolver can't handle having 2 overloads of the same family...

**Comment by bobvawter** [comment]
[CLA assistant check](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=43158) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=43158) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.crdb.dev/check/cockroachdb/cockroach?pullRequest=43158) it.</sub>

**Pull request closed without merging**
