### PR TITLE
sql: rework deterministic flag for exec stats

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### sql: remove DistSQLSpanStats

This interface is no longer useful - we now have a single known
implementation.

Release note: None

#### sql: improve ComponentStats.MakeDeterministic

This commit improves MakeDeterministic to use the tuples received/sent
to set the bytes received/sent. It also adds a unit test.

Release note: None

#### sql: rework deterministic flag for exec stats

We currently have two testing knobs for making exec stats
deterministic, one used at the execution level and one at the sql
level. This means that relevant logic is sprinkled in many places.

This change removes all handling at the execution level and instead
makes the stats deterministic after they are collected.

The TuplesRead stat is now populated by the outbox.

Release note: None

### CODE REVIEW

**Review by asubiotto — APPROVED** [review]
Nice cleanup! :lgtm: 

> Reviewed 4 of 4 files at r1, 3 of 3 files at r2, 17 of 17 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57203#-:-MNNbgYs1IKAcu8SpSyY:bkt4ztb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cathymw, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/flowinfra/outbox.go, line 157 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57203#-MNNbYy_2mODpT5Kc0oN:-MNNbYy_2mODpT5Kc0oO:bre7gzd) ([raw file](https://github.com/cockroachdb/cockroach/blob/54cdc5fec0e7dc835af7d2fc4231b52d49a71bf8/pkg/sql/flowinfra/outbox.go#L157)):*
> ```Go
> 			// Some fields in the msg have variable sizes across different runs (e.g.
> 			// metadata). To keep a useful bytes value for tests, we only count the
> 			// encoded row message size.
> ```

Might be nice to keep a comment about how `BytesSent` can be non-deterministic for future readers.

**Review by RaduBerinde — COMMENTED** [review]
TFTR! I added a comment to `getNetworkBytesFromComponentStats`, let me know if it is accurate.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57203#-:-MNPlk_x0F48S3hFwfwO:bbvundv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @cathymw, and @yuzefovich)

___
*[pkg/sql/flowinfra/outbox.go, line 157 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57203#-MNNbYy_2mODpT5Kc0oN:-MNPlfPU8idhOlBYAsv0:b-hpspjh) ([raw file](https://github.com/cockroachdb/cockroach/blob/54cdc5fec0e7dc835af7d2fc4231b52d49a71bf8/pkg/sql/flowinfra/outbox.go#L157)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Might be nice to keep a comment about how `BytesSent` can be non-deterministic for future readers.
</blockquote></details>

Done, I put it in MakeDeterministic.

**Review by asubiotto — COMMENTED** [review]
Looks good

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57203#-:-MNSjrvTBVcabmGkh8Pg:bsrfkwe)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @cathymw, and @yuzefovich)

**Pull request merged**
