### PR TITLE
storage: reuse iter and buffer between mvcc calls

### PR DESCRIPTION
**Pull request by dt**
```
name                    old time/op    new time/op    delta
Insert1_Cockroach-8        385µs ± 2%     388µs ± 1%    ~       (p=0.114 n=9+8)
Insert10_Cockroach-8       749µs ± 2%     734µs ± 1%  -2.12%    (p=0.000 n=9+7)
Insert100_Cockroach-8     3.48ms ± 0%    3.32ms ± 1%  -4.67%    (p=0.000 n=9+9)
Insert1000_Cockroach-8    34.4ms ± 7%    32.8ms ± 7%  -4.64%  (p=0.043 n=10+10)

name                    old alloc/op   new alloc/op   delta
Insert1_Cockroach-8       23.0kB ± 0%    23.0kB ± 0%    ~     (p=0.670 n=10+10)
Insert10_Cockroach-8      67.3kB ± 0%    66.7kB ± 0%  -0.83%   (p=0.000 n=10+9)
Insert100_Cockroach-8      508kB ± 0%     501kB ± 0%  -1.26%  (p=0.000 n=10+10)
Insert1000_Cockroach-8    4.56MB ± 1%    4.50MB ± 1%  -1.47%  (p=0.000 n=10+10)

name                    old allocs/op  new allocs/op  delta
Insert1_Cockroach-8          357 ± 0%       357 ± 0%    ~      (p=0.294 n=10+8)
Insert10_Cockroach-8         908 ± 0%       899 ± 0%  -0.99%    (p=0.002 n=7+8)
Insert100_Cockroach-8      6.18k ± 0%     6.08k ± 0%  -1.60%  (p=0.000 n=10+10)
Insert1000_Cockroach-8     59.0k ± 0%     57.9k ± 1%  -1.72%  (p=0.000 n=10+10)

name                    old time/op    new time/op    delta
Delete1_Cockroach-8        566µs ± 3%     560µs ± 3%    ~     (p=0.218 n=10+10)
Delete10_Cockroach-8      1.78ms ± 2%    1.74ms ± 3%  -1.92%  (p=0.023 n=10+10)
Delete100_Cockroach-8     13.7ms ± 2%    13.5ms ± 3%    ~       (p=0.442 n=8+8)
Delete1000_Cockroach-8     156ms ± 9%     150ms ± 6%    ~     (p=0.165 n=10+10)

name                    old alloc/op   new alloc/op   delta
Delete1_Cockroach-8       29.9kB ± 0%    29.9kB ± 0%    ~     (p=0.896 n=10+10)
Delete10_Cockroach-8      75.7kB ± 0%    75.1kB ± 0%  -0.72%   (p=0.000 n=9+10)
Delete100_Cockroach-8      537kB ± 0%     530kB ± 0%  -1.24%   (p=0.000 n=10+9)
Delete1000_Cockroach-8    4.83MB ± 1%    4.76MB ± 1%  -1.35%  (p=0.000 n=10+10)

name                    old allocs/op  new allocs/op  delta
Delete1_Cockroach-8          567 ± 0%       567 ± 0%    ~     (p=0.650 n=10+10)
Delete10_Cockroach-8       1.24k ± 0%     1.23k ± 0%  -0.70%    (p=0.000 n=9+9)
Delete100_Cockroach-8      7.68k ± 0%     7.58k ± 0%  -1.32%   (p=0.000 n=10+9)
Delete1000_Cockroach-8     71.8k ± 1%     70.8k ± 1%  -1.41%  (p=0.000 n=10+10)
```

---

This change is [Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5031)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[storage/engine/mvcc.go, line 1395 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5031#-KCS2Ol5KC0w6mTRkb3q:-KCS2Ol5KC0w6mTRkb3r:-1218447937) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cc0a2178a86dc01def18b6f4c0e1f17b60b1a69/storage/engine/mvcc.go#L1395)):*
`MVCCResolveWriteIntent` should be calling this method. Otherwise it doesn't have test coverage.

---

*[storage/engine/mvcc.go, line 1655 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5031#-KCS2IrIj1ML0iCZaNRI:-KCS2IrIj1ML0iCZaNRJ:13893302) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cc0a2178a86dc01def18b6f4c0e1f17b60b1a69/storage/engine/mvcc.go#L1655)):*
`MVCCResolveWriteIntentRange` should be calling this method, otherwise it doesn't have test coverage. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5031)*

**Comment by dt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[storage/engine/mvcc.go, line 1395 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5031#-KCS2Ol5KC0w6mTRkb3q:-KCS2kLa3AwuVa-6i9E7:-2134720920) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cc0a2178a86dc01def18b6f4c0e1f17b60b1a69/storage/engine/mvcc.go#L1395)):*
Hm, I was a little worried about allocating the struct just to make the call. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5031)*

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[storage/engine/mvcc.go, line 1395 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5031#-KCS2Ol5KC0w6mTRkb3q:-KCS3dbau2RhC6E7N0sy:-14894135) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cc0a2178a86dc01def18b6f4c0e1f17b60b1a69/storage/engine/mvcc.go#L1395)):*
You don't have to allocate it: `iterAndBuf` is currently a value.

---

*[storage/engine/mvcc.go, line 1581 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5031#-KCS3prlFO1eBHe3jRcP:-KCS3prlFO1eBHe3jRcQ:-1755741895) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cc0a2178a86dc01def18b6f4c0e1f17b60b1a69/storage/engine/mvcc.go#L1581)):*
I'm not sure if you're getting value from `keyBuf` because you're passing `IterAndBuf` by value to the `MVCCResolveWriteIntent...UsingIter` methods.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5031)*

**Comment by dt** [comment]
So, apparently iterators don't see writes to the batch after they are created.
https://github.com/cockroachdb/cockroach/compare/master...dt:iter?expand=1
Unless there's a way to change that, reusing iterators might be risky?

**Comment by dt** [comment]
cc @tschottdorf who helped debug.

**Comment by dt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[storage/engine/mvcc.go, line 1395 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5031#-KCS2Ol5KC0w6mTRkb3q:-KCgK9ULWTPB4Sb2YI07:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cc0a2178a86dc01def18b6f4c0e1f17b60b1a69/storage/engine/mvcc.go#L1395)):*
Done.

---

*[storage/engine/mvcc.go, line 1581 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5031#-KCS3prlFO1eBHe3jRcP:-KCgKAQJQHEcdUzq4H9U:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cc0a2178a86dc01def18b6f4c0e1f17b60b1a69/storage/engine/mvcc.go#L1581)):*
Done.

---

*[storage/engine/mvcc.go, line 1655 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5031#-KCS2IrIj1ML0iCZaNRI:-KCgKBmdU5PMXJJbQY-5:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/7cc0a2178a86dc01def18b6f4c0e1f17b60b1a69/storage/engine/mvcc.go#L1655)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5031)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5031#-:-KCgNWsw-6NpH5KTofBB:1417088721)*

**Comment by tamird** [comment]
Disregard my last comment, that was nonsense.

**Pull request merged**
