### PR TITLE
opt: remember subquery ASTs for explain

### LINKED ISSUE #29350: opt: EXPLAIN doesn't show subquery
```
root@127.60.114.93:43143/defaultdb> explain  select ( (select 1));
           tree           |   field   | description  
+-------------------------+-----------+-------------+
  root                    |           |              
   ├── render             |           |              
   │    └── emptyrow      |           |              
   └── subquery           |           |              
        │                 | id        | @S1          
        │                 | sql       | <unknown>    
        │                 | exec mode | one row      
        └── render        |           |              
             └── emptyrow |           |              
(9 rows)

Time: 3.09355ms

root@127.60.114.93:43143/defaultdb> set experimental_opt = off;
SET

Time: 385.083µs

root@127.60.114.93:43143/defaultdb> explain  select ( (select 1));
              tree             |   field   | description   
+------------------------------+-----------+--------------+
  root                         |           |               
   ├── render                  |           |               
   │    └── emptyrow           |           |               
   └── subquery                |           |               
        │                      | id        | @S1           
        │                      | sql       | ((SELECT 1))  
        │                      | exec mode | one row       
        └── limit              |           |               
             └── render        |           |               
                  └── emptyrow |           |               
(10 rows)

Time: 904.03µs
```

The `<unknown>` under the subquery sql is what's broken.

cc @RaduBerinde.

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### sql: rename "sql" to "original sql" in subquery EXPLAIN

With the optimizer, this field will show the original subquery which
might have been modified by transforms.

Release note: None

#### opt: remember subquery ASTs for explain

Store the original `*tree.Subquery` in `Any`, `Exists`, `Subquery` and
use it to populate the subquery during execbuild. This causes the
original subquery to show up in `EXPLAIN`.

Fixes #29350.

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, 14 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29597#-:-LLfGToS7F1_FzkHuGuX:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/memo/expr_view_format.go, line 395 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29597#-LLfDFrn0sxzMPnnObmh:-LLfDFrn0sxzMPnnObmi:b-aa4oin) ([raw file](https://github.com/cockroachdb/cockroach/blob/31b310b058e55af7f74194a2528a0d15497da5ce/pkg/sql/opt/memo/expr_view_format.go#L395)):*
> ```Go
> 
> 	case opt.SubqueryOp, opt.ExistsOp:
> 		private = nil
> ```

We have comments above to explain why `private` is set to nil for some operators -- might be worth doing that here too.
___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 689 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29597#-LLfF_ib4POR3yriaj4p:-LLfF_ib4POR3yriaj4q:btz6dgx) ([raw file](https://github.com/cockroachdb/cockroach/blob/31b310b058e55af7f74194a2528a0d15497da5ce/pkg/sql/opt/norm/rules/decorrelate.opt#L689)):*
> ```
>                 (Filters [ (ConstructAnyCondition $input $scalar $subqueryDef) ])
>             )
>             $subqueryDef
> ```

Is there any issue with reusing the same subqueryDef even though this is a different subquery?

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29597)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/memo/expr_view_format.go, line 395 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29597#-LLfDFrn0sxzMPnnObmh:-LLjX3uXD-A7GoHXjM8_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/31b310b058e55af7f74194a2528a0d15497da5ce/pkg/sql/opt/memo/expr_view_format.go#L395)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

We have comments above to explain why `private` is set to nil for some operators -- might be worth doing that here too.
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/rules/decorrelate.opt, line 689 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/29597#-LLfF_ib4POR3yriaj4p:-LLjX5-78FIM8VVMiQLD:b-25qs48) ([raw file](https://github.com/cockroachdb/cockroach/blob/31b310b058e55af7f74194a2528a0d15497da5ce/pkg/sql/opt/norm/rules/decorrelate.opt#L689)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Is there any issue with reusing the same subqueryDef even though this is a different subquery?
</blockquote></details>

No, that's the point of `OriginalExpr`. It's true that we copy `Cmp` too but it's fine since it's not used by `Exists`.

**Review by andy-kimball — COMMENTED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29597#-:-LLjYI960R0PWjuL15fJ:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/29597)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
