### PR TITLE
server: let periodic reporter manage periodic stats reset

### PR DESCRIPTION
**Pull request by dt**

### CODE REVIEW

**Comment by tamird** [comment]
Nice improvement, LGTM. Consider adding some tests to exercise the corner case this is meant to prevent.

---

Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/server/updates.go, line 278 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15570#-Kj4zS1a4eMA2gRp8yuR:-Kj4zS1a4eMA2gRp8yuS:byr6t7s) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b33e22db5e95cdb03ebe56a4a738d0b9b6231d1/pkg/server/updates.go#L278)):*
> ```Go
> 	q.Set("version", build.GetInfo().Tag)
> 	q.Set("uuid", s.node.ClusterID.String())
> 	q.Set("uptime", strconv.Itoa(int(runningTime.Seconds())))
> ```

could this be FormatFloat to avoid the type conversion?

---

*[pkg/server/updates.go, line 115 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15570#-Kj5-6xcXEFXH4TcTOT6:-Kj5-6xdJoED5M6dhPYU:bbiagph) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f25655fcebceb4e163957ff0507df19d4629a2d/pkg/server/updates.go#L115)):*
> ```Go
> 	s.stopper.RunWorker(context.TODO(), func(ctx context.Context) {
> 		startup := timeutil.Now()
> 		var nextUpdateCheck, nextDiagnosticReport = startup, startup
> ```

while you're here, could this be `:=` rather than this unusual `var` use?

---

*[pkg/server/updates.go, line 348 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15570#-Kj5-WpiZO7zse7Nqg7x:-Kj5-WpiZO7zse7Nqg7y:bq2uu7b) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f25655fcebceb4e163957ff0507df19d4629a2d/pkg/server/updates.go#L348)):*
> ```Go
> 	nextReset := scheduledReset.Add(statsResetFrequency)
> 
> 	// If the next diag report is within the reset interval, wait to reset then.
> ```

this method mixes calculating the next reset with actually performing the reset; I think this might be clearer if inlined into the caller. In any case, it seems worthwhile to add some tests while you're here.

---

*[pkg/server/updates_test.go, line 190 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15570#-Kj4zvnDMFUwqpj6E_fm:-Kj4zvnDMFUwqpj6E_fn:bhor27s) ([raw file](https://github.com/cockroachdb/cockroach/blob/2abc4da2d9600ca3eb43ad89b73fe84a05190215/pkg/server/updates_test.go#L190)):*
> ```Go
> 
> 		node := ts.node.recorder.GetStatusSummary()
> 		ts.reportDiagnostics(0)
> ```

I think this landed in the wrong commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15570#-:-Kj5-rwHV-BF8WkjAydx:bgqzb8e)*

**Comment by knz** [comment]
LGTM, could indeed use atest.

Also I think the various "frequencies" (really, "periods" or "intervals") in`updates.go` ought to become configurable.

---

Reviewed 2 of 3 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/server/updates.go, line 278 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15570#-Kj4zS1a4eMA2gRp8yuR:-Kj7YeUczu3wLRbX1BEs:b4ck8jl) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b33e22db5e95cdb03ebe56a4a738d0b9b6231d1/pkg/server/updates.go#L278)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

could this be FormatFloat to avoid the type conversion?
</blockquote></details>

or alternatively `fmt.Sprintf("%d", runningTime.Seconds())`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15570#-:-Kj7Z1e3JegGTen7zuoO:b-mfo0bt)*

**Comment by dt** [comment]
Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/server/updates.go, line 278 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15570#-Kj4zS1a4eMA2gRp8yuR:-KjEPkVpV1K1NpQVjjWi:b-b0qpsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b33e22db5e95cdb03ebe56a4a738d0b9b6231d1/pkg/server/updates.go#L278)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

or alternatively `fmt.Sprintf("%d", runningTime.Seconds())`
</blockquote></details>

Eh, the remote side, as it stands, expects an integer number of seconds -- truncating the float to an int seems fine?

---

*[pkg/server/updates.go, line 115 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15570#-Kj5-6xcXEFXH4TcTOT6:-KjEPdv3N7ej9x0ng9ob:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f25655fcebceb4e163957ff0507df19d4629a2d/pkg/server/updates.go#L115)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

while you're here, could this be `:=` rather than this unusual `var` use?
</blockquote></details>

Done.

---

*[pkg/server/updates.go, line 348 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15570#-Kj5-WpiZO7zse7Nqg7x:-KjER2VHgNyW0Insm18W:b3ftzhb) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f25655fcebceb4e163957ff0507df19d4629a2d/pkg/server/updates.go#L348)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this method mixes calculating the next reset with actually performing the reset; I think this might be clearer if inlined into the caller. In any case, it seems worthwhile to add some tests while you're here.
</blockquote></details>

Eh, I think I the caller loop, which is running three different periodic events now, is easier to follow with the individual events handled in their own methods? 

---

*[pkg/server/updates_test.go, line 190 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15570#-Kj4zvnDMFUwqpj6E_fm:-KjEPurc0EbzkwOAgSRL:b-sxkjjh) ([raw file](https://github.com/cockroachdb/cockroach/blob/2abc4da2d9600ca3eb43ad89b73fe84a05190215/pkg/server/updates_test.go#L190)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I think this landed in the wrong commit.
</blockquote></details>

Squashed it anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15570)*

**Comment by dt** [comment]
added settings for the reset and report frequencies.

---

Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15570#-:-KjEUcBIuU7kxTIwDfmS:buznc88)*

**Comment by knz** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/server/updates.go, line 278 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15570#-Kj4zS1a4eMA2gRp8yuR:-KjEUnv8EVY3BxQJ6HL-:bvf36h0) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b33e22db5e95cdb03ebe56a4a738d0b9b6231d1/pkg/server/updates.go#L278)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Eh, the remote side, as it stands, expects an integer number of seconds -- truncating the float to an int seems fine?
</blockquote></details>

"%d" prints the integer part

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15570)*

**Comment by dt** [comment]
Review status: 1 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/server/updates.go, line 278 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15570#-Kj4zS1a4eMA2gRp8yuR:-KjEWQgVusJska1eTUx-:b4mdw5f) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b33e22db5e95cdb03ebe56a4a738d0b9b6231d1/pkg/server/updates.go#L278)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

"%d" prints the integer part
</blockquote></details>

... and fails `vet` for not matching its arg type.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15570)*

**Comment by tamird** [comment]
Reviewed 3 of 4 files at r5.
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/server/updates.go, line 278 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15570#-Kj4zS1a4eMA2gRp8yuR:-KjEvb-mqRkYYp3vqscz:b-h4lwgy) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b33e22db5e95cdb03ebe56a4a738d0b9b6231d1/pkg/server/updates.go#L278)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

... and fails `vet` for not matching its arg type.
</blockquote></details>

the type cast makes me nervous in general, though it is extremely unlikely to be a problem here. just registering my concern, i suppose.

---

*[pkg/server/updates.go, line 348 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15570#-Kj5-WpiZO7zse7Nqg7x:-KjEw-zsFRP46EgqjXxj:bx1u612) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f25655fcebceb4e163957ff0507df19d4629a2d/pkg/server/updates.go#L348)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Eh, I think I the caller loop, which is running three different periodic events now, is easier to follow with the individual events handled in their own methods? 
</blockquote></details>

Maybe you're right. Still, this method has a complicated relationship with its name and semantics.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15570)*

**Comment by knz** [comment]
The general direction of this PR is insufficient - there must be a separate reporting period for SQL stats.

It would be unreasonable to reset every day because that would let too much data accumulate in RAM
It would be unreasonable to report every day and reset every hour because then we lose data, see #15689

---

Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15570#-:-KjIw7neR7gftYiO_Zws:bnvg4ar)*

**Comment by knz** [comment]
The only alternative is to drop the entire reporting period down to one hour. 

---

Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15570#-:-KjIwNnRjmDjb8PGREBj:b-pnp2jx)*

**Comment by knz** [comment]
Reporting on a 1-1 discussion with @dt:
- we're going to decrease the overall reporting period to 1 hour. The amount of node health data is negligible compared to sql data anyway, so it doesn't hurt to report it too often.
- the reporting function will take charge of resetting the sql stats, with a configurable probability parameter (set to 1 to start)

---

Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15570#-:-KjJ0GLyN-EpqVch6UXj:brwtdzx)*

**Comment by dt** [comment]
Punting the probabilistic sampling to 1.0.1 to keep things simple for now: 1h interval on reports + reports do resets (even if disabled by setting).

---

Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15570#-:-KjJ9VPMydkkxfsxE1Q5:b-ge5spo)*

**Comment by knz** [comment]
:lgtm: modulo question about reset on error

---

Reviewed 2 of 4 files at r5, 1 of 2 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/server/updates.go, line 255 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/15570#-KjJB8It_f8DzRi4dlPe:-KjJB8It_f8DzRi4dlPf:b-uzsedl) ([raw file](https://github.com/cockroachdb/cockroach/blob/094d37f7805a143658435d1654fa1b3e8851017d/pkg/server/updates.go#L255)):*
> reset
I'd say only reset if the HTTP request succeeds, what do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15570#-:-KjJB4NkoKdL5TZIRHZH:bdkjs2y)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/server/updates.go, line 255 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/15570#-KjJB8It_f8DzRi4dlPe:-KjJBPBHEydP1WIeUf-V:b5wezrb) ([raw file](https://github.com/cockroachdb/cockroach/blob/094d37f7805a143658435d1654fa1b3e8851017d/pkg/server/updates.go#L255)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

> reset
I'd say only reset if the HTTP request succeeds, what do you think?
</blockquote></details>

strongly disagree: if our reg server is down / unreachable / etc, we don't want people's clusters OOMing or really to change their runtime characteristics in any way.

I expect any real deployments won't be routable to the open internet anyway, so we should expect the http request to fail in the common case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15570)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/server/updates.go, line 255 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/15570#-KjJB8It_f8DzRi4dlPe:-KjJL_uRWBSktCZdEqIa:b-o5lq8j) ([raw file](https://github.com/cockroachdb/cockroach/blob/094d37f7805a143658435d1654fa1b3e8851017d/pkg/server/updates.go#L255)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

strongly disagree: if our reg server is down / unreachable / etc, we don't want people's clusters OOMing or really to change their runtime characteristics in any way.

I expect any real deployments won't be routable to the open internet anyway, so we should expect the http request to fail in the common case.
</blockquote></details>

Ack, sounds good.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15570)*

**Pull request merged**
