### PR TITLE
sql: fix connection stuck in scram auth

### LINKED ISSUE #103108: server: shutdown blocked by pending scram auth
This ticket describes a bug where pending scram auth is blocking graceful server shutdown: https://cockroachlabs.atlassian.net/browse/CC-24517?focusedCommentId=166961

It looks like 3 connections using scram to authenticate were started, but scram auth was not completed. While the connections were in this state, the server began shutting down, but it could not complete due to blocking channel selects here https://cockroachlabs.atlassian.net/browse/CC-24517?focusedCommentId=166895.

Jira issue: CRDB-27834

### PR DESCRIPTION
**Pull request by ecwall**
Fixes #103108

Previously `authPipe.noMorePwdData()` would set the `authPipe.writerDone` chan to nil after closing it. This means that `case <-authPipe.writerDone` will never be selected if the select is entered after `authPipe.writerDone` is nil.

For SCRAM authentication, `authPipe.GetPwdData()` is called in a loop which can result in a race between `authPipe.writerDone = nil` and `case <-authPipe.writerDone`.

This race condition is fixed by not setting `authPipe.writerDone` to nil after closing it.

Release note (bug fix): Fixed a bug that could cause goroutines to hang during SCRAM authentication.

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104167#-:-NWnN4OR9RV-2HlVEbOG:b-j4xmku)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @carloruiz, @ecwall, and @rimadeodhar)

___
*[`-- commits` line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104167#-NWnMtbYC80zQ3YTHE8V):*
nit: should we add a bug fix release note, like "Fixed a bug that could cause goroutines to hang if the connection was terminated during SCRAM authentication."

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104167)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @carloruiz, @rafiss, and @rimadeodhar)

___
*[`-- commits` line 17 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104167#-NWnMtbYC80zQ3YTHE8V):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: should we add a bug fix release note, like "Fixed a bug that could cause goroutines to hang if the connection was terminated during SCRAM authentication."
</blockquote></details>

Added. I'm not sure if it was related to the connection closing. I think it could just hang regardless.

**Review by rafiss — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104167)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @carloruiz and @rimadeodhar)

**Comment by ecwall** [comment]
bors r=rafiss

**Pull request merged**
