### PR TITLE
workload/kv: support target compression ratio

### PR DESCRIPTION
**Pull request by ajkr**
RocksDB only stores compressed data blocks if they meet some lower-bound
on compression ratio. Otherwise it stores them in the uncompressed form.
Since workload/kv was synthesizing random data, data blocks were always
stored uncompressed.

This PR adds a knob, `--target-compression-ratio`. Increasing it makes
the synthesized data more repetitive, which makes RocksDB more likely to
write compressed data blocks.

Release note: None

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm:

Cc @nvanbenschoten as you recently added a roachtest to exercise larger block sizes. Might be more realistic of those blocks were compressible. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34881#-:-LYgTXbVC4EWS50sHhTZ:by5xi2n)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajkr)

___
*[pkg/workload/kv/kv.go, line 504 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34881#-LYgTSST5VPUp38b68jJ:-LYgTSST5VPUp38b68jK:bnxqe4e) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2b9715ea65cb3bf3c346f612fc587c02cd18905/pkg/workload/kv/kv.go#L504)):*
> ```Go
> 			blockData[i] = byte(r.Int() & 0xff)
> 		}
> 	}
> ```

Does this work in practice? I've never thought about how to make randomly generated data with a target compression ratio.

**Review by nvb — APPROVED** [review]
:lgtm:

I'll hold off on that roachtest until we get this in. I think it's a good idea to make large blocks moderately compressible in the test to simulate more realistic load.

Welcome @ajkr, by the way!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34881#-:-LYgiK5G0IyGgGfkQHab:bvqjmd6)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @ajkr)

**Comment by ajkr** [comment]
> Does this work in practice? I've never thought about how to make randomly generated data with a target compression ratio.

Sort of. In practice I saw actual compression ratio ~1.5 when setting `--target-compression-ratio=2.0`, and actual compression ratio 6-7 when setting `--target-compression-ratio=10.0`. Perhaps the name should reflect this gap, like "max achievable compression ratio" or something.

**Comment by petermattis** [comment]
One of the linters suggests that you don't have `go fmt` hooked up to your editor:

```
=== PAUSE TestLint/TestGofmtSimplify
        lint_test.go:742: 
            /go/src/github.com/cockroachdb/cockroach/pkg/workload/kv/kv.go
            diff -u /go/src/github.com/cockroachdb/cockroach/pkg/workload/kv/kv.go.orig /go/src/github.com/cockroachdb/cockroach/pkg/workload/kv/kv.go
            --- /go/src/github.com/cockroachdb/cockroach/pkg/workload/kv/kv.go.orig	2019-02-13 20:47:15.394492109 +0000
            +++ /go/src/github.com/cockroachdb/cockroach/pkg/workload/kv/kv.go	2019-02-13 20:47:15.394492109 +0000
            @@ -497,7 +497,7 @@
             	}
             	for i := range blockData {
             		if i >= uniqueSize {
            -			blockData[i] = blockData[i - uniqueSize]
            +			blockData[i] = blockData[i-uniqueSize]
             		} else {
             			blockData[i] = byte(r.Int() & 0xff)
             		}
```

**Comment by ajkr** [comment]
Perhaps the test failure is fixed by #35088

**Comment by nvanbenschoten** [comment]
I just kicked off another run for you.

**Comment by ajkr** [comment]
> I just kicked off another run for you.

Thanks. I cannot find how to rerun in the UI. Is it documented or do you mind explaining?

**Comment by petermattis** [comment]
> Thanks. I cannot find how to rerun in the UI. Is it documented or do you mind explaining?

You need to be added to the appropriate teamcity group so that you can login to teamcity. Then you have to deal with teamcity's super confusing UI. Which step are you at?

**Comment by ajkr** [comment]
> > Thanks. I cannot find how to rerun in the UI. Is it documented or do you mind explaining?
> 
> You need to be added to the appropriate teamcity group so that you can login to teamcity. Then you have to deal with teamcity's super confusing UI. Which step are you at?

I am logged in now but cannot find the rerun button.

**Comment by ajkr** [comment]
bors r=nvanbenschoten,petermattis

**Comment by petermattis** [comment]
screen shot 2019-02-20 at 1 46 59 pm

See the "Run..." button in the upper right corner.

**Comment by petermattis** [comment]
@ajkr I just added you as a reviewer. Try bors'ing again. Not clear why that is necessary as you're part of the cockroachdb org.

**Comment by ajkr** [comment]
bors r=nvanbenschoten,petermattis

**Comment by ajkr** [comment]
bors r=nvanbenschoten

**Comment by ajkr** [comment]
I must've missed something, or several things, in permissions setup. My UI doesn't have the "Run" button.

image

**Comment by ajkr** [comment]
bors r=nvanbenschoten,petermattis

**Comment by ajkr** [comment]
bors r=nvanbenschoten,petermattis

**Pull request merged**
