### PR TITLE
 builkio: Add schedule control statements. 

### PR DESCRIPTION
**Pull request by miretskiy**
Informs #51600 

Introduce schedule control statements responsible for
managing scheduled jobs.

```
PAUSE SCHEDULE 123
PAUSE SCHEDULES SELECT ...

RESUME SCHEDULES SELECT schedule_id FROM system.schedules_jobs ...

DROP SCHEDULE 123
```

Release Notes (enterprise): Implement schedule control statements
to pause, resume, or delete scheduled jobs.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
opt part LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51896#-:-MD7SYG37shb0ooINuh3:b-33fro1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @pbardea)

**Review by pbardea — APPROVED** [review]
> Reviewed 32 of 32 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51896)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @miretskiy)

___
*[pkg/sql/opt/exec/factory.go, line 582 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51896#-MDDX7Zh1cDnc4oGd6Ox:-MDDX7Zh1cDnc4oGd6Oy:b-30ywqq) ([raw file](https://github.com/cockroachdb/cockroach/blob/59f14340349c5a820750f64aad7965e8771d8235/pkg/sql/opt/exec/factory.go#L582)):*
> ```Go
> 
> 	// ConstructControlSchedules creates a node that implements PAUSE/CANCEL/RESUME
> 	// JOBS.
> ```

 `PAUSE/CANCEL/RESUME JOBS` -> `PAUSE/CANCEL/RESUME SCHEDULES`
___
*[pkg/sql/opt/exec/execbuilder/statement.go, line 242 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51896#-MDDYBVp6vrgkFF1axnn:-MDDYBVp6vrgkFF1axno:b-v6itsm) ([raw file](https://github.com/cockroachdb/cockroach/blob/59f14340349c5a820750f64aad7965e8771d8235/pkg/sql/opt/exec/execbuilder/statement.go#L242)):*
> ```Go
> 		return execPlan{}, err
> 	}
> 	// ControlJobs returns no columns.
> ```

`ControlSchedules` returns no columns?

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51896)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @pbardea)

___
*[pkg/sql/opt/exec/factory.go, line 582 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51896#-MDDX7Zh1cDnc4oGd6Ox:-MDG6z0f8_I6kzW9zgTN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/59f14340349c5a820750f64aad7965e8771d8235/pkg/sql/opt/exec/factory.go#L582)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

 `PAUSE/CANCEL/RESUME JOBS` -> `PAUSE/CANCEL/RESUME SCHEDULES`
</blockquote></details>

Done.
___
*[pkg/sql/opt/exec/execbuilder/statement.go, line 242 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51896#-MDDYBVp6vrgkFF1axnn:-MDG76-7D297l_30v3it:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/59f14340349c5a820750f64aad7965e8771d8235/pkg/sql/opt/exec/execbuilder/statement.go#L242)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

`ControlSchedules` returns no columns?
</blockquote></details>

Done.

**Pull request merged**
