### PR TITLE
opt: improve func deps to remember lax keys

### LINKED ISSUE #31628: opt: lax key info is lost on projections
```sql
CREATE TABLE t (a INT, b INT, UNIQUE (a, b))
SELECT DISTINCT a, b FROM t WHERE (a, b) IN ((1, 1), (2, 2))
  distinct-on
   ├── columns: a:1(int!null) b:2(int!null)
   ├── grouping columns: a:1(int!null) b:2(int!null)
   ├── key: (1,2)
   └── scan t@secondary
        ├── columns: a:1(int!null) b:2(int!null)
        └── constraint: /1/2: [/1/1 - /1/1] [/2/2 - /2/2]
```

Note that the distinct is not elided; we don't know that `(a,b)` forms a key.

The problem is that we are projecting away the implicit pk and from that point we lose the information that `(a,b)` was a lax key.

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: improve func deps to remember lax keys

Currently `FuncDepSet` remembers a strict key. When a `FuncDepSet` has
a strict key, adding lax keys only adds the lax FDs. If the key is
projected away, we no longer have the information of what lax keys we
had.

This can be seen even in simple cases like:
```
CREATE TABLE ab (a INT, b INT, UNIQUE INDEX(a,b))
SELECT a, b FROM ab WHERE a IS NOT NULL AND b IS NOT NULL
```
In this case, we won't know that `a,b` is a lax key at the level of
the scan (and thus a key at the level of the select).

This change fixes this by making `FuncDepSet` remember a lax key (when
it has no strict key). The `hasKey` bool is changed to an enum
indicating the kind of key. Most importantly, when we project and the
remaining columns no longer form a strict key, but they form a lax
key, this key will be retained.

Note that it's not important which lax key we remember - the important
thing is to know when there is *some* lax key; the FDs take care of
the rest.

Fixes #31628.

Release note (performance improvement): The optimizer can determine
more keys in certain cases involving unique indexes, potentially
resulting in better plans.

#### opt: make func dep test more readable

Replace `util.MakeFastIntSet` with a short wrapper `c()`.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
CC @jordanlewis - if you want you can rebase your PR on top of this and see if it fixes the issue you saw (it should).

**Review by andy-kimball — APPROVED** [review]
:lgtm:, nice work, I think it just needs a few more tests to cover some of the code you added. Maybe put panics in some of those ifs you added and make sure the FD tests are covering the various cases.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31662#-:-LPEOkPD0b1H8OmA7KqC:b-x8eh9a)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/props/func_dep.go, line 467 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31662#-LPDrdBw0_2DzuRUngvs:-LPDrdBw0_2DzuRUngvt:b8o9ltc) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6bb75195bb0056e40b2ffeb1943ea173cfb0c5/pkg/sql/opt/props/func_dep.go#L467)):*
> ```Go
> }
> 
> // ClearKey marks the FD set as having no strict key. If there was a strict key,
> ```

ClearKey -> DowngradeKey
___
*[pkg/sql/opt/props/func_dep.go, line 1218 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31662#-LPDw4ZQ2awuF96r9ESb:-LPDw4ZQ2awuF96r9ESc:b44trpl) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6bb75195bb0056e40b2ffeb1943ea173cfb0c5/pkg/sql/opt/props/func_dep.go#L1218)):*
> ```Go
> 		if !cols.SubsetOf(closure) {
> 			cols = cols.Difference(closure)
> 			// If we have a strict key, we add a strict dependency; otherwise we add a
> ```

NIT: I always add blank lines before comments that don't begin a block.
___
*[pkg/sql/opt/props/func_dep_test.go, line 293 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31662#-LPE1RKkC1VdIAGAyJ44:-LPE1RKkC1VdIAGAyJ45:b-jemx9j) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e5edef9ec3c78420206c3ac4a7bcda82556a65/pkg/sql/opt/props/func_dep_test.go#L293)):*
> ```Go
> }
> 
> func TestFuncDeps_AddLaxKey(t *testing.T) {
> ```

Add test to make sure that adding a smaller lax key will overwrite a bigger lax key.
___
*[pkg/sql/opt/props/func_dep_test.go, line 739 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31662#-LPE0qBfCY2lmjrq2IQG:-LPE0qBfCY2lmjrq2IQH:bf6bz8t) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e5edef9ec3c78420206c3ac4a7bcda82556a65/pkg/sql/opt/props/func_dep_test.go#L739)):*
> ```Go
> }
> 
> func TestFuncDeps_MakeProduct(t *testing.T) {
> ```

`MakeProduct` needs new test(s), since you added cases where lax key * strict key = lax key, and lax key * lax key = lax key.

**Review by RaduBerinde — COMMENTED** [review]
TFTR! Added more tests. Verified new lines are covered (using `go test -coverprofile`).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31662#-:-LPIxsfPE33SBoqVEq2W:bngrv9n)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/props/func_dep.go, line 467 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/31662#-LPDrdBw0_2DzuRUngvs:-LPIsHTf3iONu2RHFkT9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad6bb75195bb0056e40b2ffeb1943ea173cfb0c5/pkg/sql/opt/props/func_dep.go#L467)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

ClearKey -> DowngradeKey
</blockquote></details>

Done.
___
*[pkg/sql/opt/props/func_dep_test.go, line 293 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31662#-LPE1RKkC1VdIAGAyJ44:-LPItaBz1UuoWVJk-wZ2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e5edef9ec3c78420206c3ac4a7bcda82556a65/pkg/sql/opt/props/func_dep_test.go#L293)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Add test to make sure that adding a smaller lax key will overwrite a bigger lax key.
</blockquote></details>

Done.
___
*[pkg/sql/opt/props/func_dep_test.go, line 739 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31662#-LPE0qBfCY2lmjrq2IQG:-LPIxOS4AURDZRtjP9yl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e5edef9ec3c78420206c3ac4a7bcda82556a65/pkg/sql/opt/props/func_dep_test.go#L739)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

`MakeProduct` needs new test(s), since you added cases where lax key * strict key = lax key, and lax key * lax key = lax key.
</blockquote></details>

Done.

**Comment by jordanlewis** [comment]
Something potentially funky with this (or maybe it's a separate deficiency).

It seems that if a not-null constraint is imposed on a column in one index, it's not properly propagated to all of the indexes.

```
CREATE TABLE a (a INT, b INT, PRIMARY KEY (a, b)); // a,b both not null because part of pk
CREATE INDEX ON a(b); // b should still be not null here
```

But at this point, the code in #31616 thinks that the columns are nullable and won't parallelize the scan.

**Comment by RaduBerinde** [comment]
Interesting.. That might be a separate issue, I'll take a look. Good find, thank you!

**Comment by RaduBerinde** [comment]
@jordanlewis are you sure you tested that correctly? Maybe you used one of the files that tests the heuristic planner? Or with a DML query?

```
statement ok
CREATE TABLE foo (a INT, b INT, PRIMARY KEY (a, b), UNIQUE INDEX (b))

query TTTTT
EXPLAIN (VERBOSE) SELECT b FROM foo WHERE b in (1, 3, 5)
----
scan  ·         ·                  (b)  ·
·     table     foo@foo_b_key      ·    ·
·     spans     /1-/2 /3-/4 /5-/6  ·    ·
·     parallel  ·                  ·    ·
```

**Comment by jordanlewis** [comment]
Look at my PR - there's a to-do for you in it with the bad example. Definitely possible I screwed up.

**Pull request merged**
