### PR TITLE
kvserver: increase rebalance action impact req

### LINKED ISSUE #98890: kvserver: increase min action impact required
In #59094 we saw very rapid lease transfers which raced with the replicate queue and other stores within the cluster. Part of the issue was that the store rebalancer is only limited by the number of hot replicas it tracks, in terms of how many actions it could take in a cycle.

Of the lease transfer that occurred, there were many which were likely more costly to execute than the benefit they provided. For example, a lease worth 662µs shown below.

```
I230313 23:39:08.736026 297 13@kv/kvserver/store_rebalancer.go:777 ⋮ [T1,n1,s1,store-rebalancer] 1009  transferring lease for r9 load=‹(queries-per-second=7.0 cpu-per-second=662µs)› to store s2 load=‹(queries-per-second=319.6 cpu-per-second=197ms)› from local store s1 load=‹(queries-per-second=666.7 cpu-per-second=317ms)›
```

Currently the only mechanism which excludes actions which are low benefit is the `minLoadFraction`. The impact of an action must exceed `minLoadFraction * localLoad`. `minLoadFraction` is currently 0.01%.

https://github.com/cockroachdb/cockroach/blob/0495342e81d473901278993f6162b1d78b685bc1/pkg/kv/kvserver/store_rebalancer.go#L709-L709

The current setting is too low, given that if the top-k replicas aren't more than 0.01%, it is likely that the replica load distribution within a store is fairly uniform. In which case, it would be better to let the replicate queue rebalance based on replica counts and lease counts.

This issue is to increase the `minLoadFraction` from 0.01% to a higher value. The value for range rebalancing should be higher than lease rebalancing, due to the much higher cost.

### PR DESCRIPTION
**Pull request by kvoli**
Previously, the store rebalancer would attempt to transfer leases or relocate replicas of a range so long as the load of the range (estimated using the local leaseholder replica) was greater than 0.1% of the store's load.

This commit updates the value to be higher for both lease rebalancing and range rebalancing, specifically:

lease rebalancing: 0.1% -> 0.5%
range rebalancing: 0.1% -> 2.0%

The documented rationale, as for why these values exist is also the reason for the increase: decrease unnecessary churn. Only the hottest ranges are considered, when the impact of a rebalance action for these ranges is estimated to be less than a small fraction of the store's total load, it is indicative that the distribution of replica load is not skewed. Letting the replicate queue balance replica and lease counts is a better option in such distributions (until we consolidate rebalancing responsibility).

Making the minimum for range rebalancing higher is also added, as multiple replicas for a range is inherently more costly than moving a lease.

Resolves: https://github.com/cockroachdb/cockroach/issues/98890

Release note: None

### CODE REVIEW

**Review by andrewbaptist — APPROVED** [review]
:lgtm: I'm a little concerned with the potential impact of this change in the sense that it makes some rebalancing less likely to occur, but as you mentioned, the replicate_queue will also do rebalancing. I'm not sure we should backport this as I'm not aware of any field cases that are impacted negativity by this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98889#-:-NTFZ4S4BlWkmKET4eh1:b-yk9mlf)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @kvoli)

**Comment by kvoli** [comment]
Won't backport. I agree, it's generally a risky change and we don't have a pressing need.

**Comment by kvoli** [comment]
In light of https://github.com/cockroachdb/cockroach/issues/104292 I'm going to merge this now and see how we do.

**Comment by kvoli** [comment]
bors r=andrewbaptist

**Pull request merged**
