### PR TITLE
opt: Enable additional logic tests for opt configs

### PR DESCRIPTION
**Pull request by andy-kimball**
Enable remainder of non-dist sql tests that I skipped during the
last pass through the tests.
Enable ColumnAccessExpr to work on non-Tuple exprs.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Regarding the change to ColumnAccessExpr. This is not the right approach IMHO.  ColumnAccessExpr ought to evaporate during semantic analysis. It should not exist any more in the logical plan.

The correct substitutions are:

- `(tablename).colname` -> replace by the var reference to that specific column
- `(SRF).colname` -> migrate the SRF to a `ROWS FROM` relational expression in the FROM clause, then replace the remaining expression by a var reference to one of the columns of the ROWS FROM expression

Supporting arbitrary access to elements in a named tuple may be useful in the future (and then warrant the code you're proposed here) but that is 1) not needed for the compatibility arc that was motivating this work 2)  introducing complexity which IMHO is not warranted here.

**Comment by knz** [comment]
Also *please* do not include a commit with semantic analysis changes in a PR whose title is about tests. Please do split the PR in two.

**Comment by BramGruneir** [comment]
The ROWS FROM work is here #26223
And I'll have a PR that handles the `(tablename).colname` out today (I hope).

It might be best to wait to enable the rest of these tests until after that is done.

**Comment by andy-kimball** [comment]
I just updated the PR to simply throw an error on attempted column access to a non-tuple expression (as per an offline discussion with Raphael). I'll let Bram/Raphael sort out what they want to do longer-term here.

**Comment by knz** [comment]
thanks - LGTM

@BramGruneir this way we can decouple the work from the progress on the optimizer. Let's re-sync the two teams when some dust has settled.

**Comment by RaduBerinde** [comment]
LGTM

**Comment by rytaft** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[pkg/sql/plan.go, line 385 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26191#-LDqaogn1bAVtqiGfaEK:-LDqaogo104t0q-9hjS1:b-oy6jbi) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dc84378c5bc3d4a9fe3a6f8dff74227f39b4811/pkg/sql/plan.go#L385)):*
> ```Go
> 		if !stmt.ExpectedTypes.TypesEqual(cols) {
> 			return pgerror.NewError(pgerror.CodeFeatureNotSupportedError,
> 				"cached plan must not change result type")
> ```

Is this actually a cached plan? Looks like it's being built...

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26191#-:-LDqdD7uBGB-b1wsodx-:bnfp4nl)*

**Comment by andy-kimball** [comment]
*[pkg/sql/plan.go, line 385 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26191#-LDqaogn1bAVtqiGfaEK:-LDqjmWm0vK3FMM6A6Km:b-71lhbm) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dc84378c5bc3d4a9fe3a6f8dff74227f39b4811/pkg/sql/plan.go#L385)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Is this actually a cached plan? Looks like it's being built...
</blockquote></details>

`stmt.ExpectedTypes` are set during the prepare phase. That's what's meant by "cached plan". The comment is taken from `makePlan`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26191)*

**Comment by rytaft** [comment]
*[pkg/sql/plan.go, line 385 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26191#-LDqaogn1bAVtqiGfaEK:-LDqkaOk3008Lhc6dMuG:bjtb84p) ([raw file](https://github.com/cockroachdb/cockroach/blob/1dc84378c5bc3d4a9fe3a6f8dff74227f39b4811/pkg/sql/plan.go#L385)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

`stmt.ExpectedTypes` are set during the prepare phase. That's what's meant by "cached plan". The comment is taken from `makePlan`.
</blockquote></details>

got it - thanks!

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26191)*

**Pull request merged**
