### PR TITLE
sql/catalog/lease: attempt to fix a flakey test

### LINKED ISSUE #52385: sql/catalog: TestRangefeedUpdatesHandledProperlyInTheFaceOfRaces appears to be flaky
See https://teamcity.cockroachdb.com/viewLog.html?buildId=2149254&tab=buildResultsDiv&buildTypeId=Cockroach_EssentialCi on a branch for a seemingly unrelated change.

```
panic: test timed out after 30m0s

goroutine 70211 [running]:
testing.(*M).startAlarm.func1()
        /usr/local/go/src/testing/testing.go:1459 +0xdf
created by time.goFunc
        /usr/local/go/src/time/sleep.go:168 +0x44

goroutine 1 [chan receive, 29 minutes]:
testing.(*T).Run(0xc003462b40, 0x444fb80, 0x33, 0x4542678, 0x73ec01)
        /usr/local/go/src/testing/testing.go:1043 +0x37e
testing.runTests.func1(0xc00020fb00)
        /usr/local/go/src/testing/testing.go:1284 +0x78
testing.tRunner(0xc00020fb00, 0xc00082bdf0)
        /usr/local/go/src/testing/testing.go:991 +0xdc
testing.runTests(0xc00087eee0, 0x729f620, 0x25, 0x25, 0x0)
        /usr/local/go/src/testing/testing.go:1282 +0x2a7
testing.(*M).Run(0xc0004cca00, 0x0)
        /usr/local/go/src/testing/testing.go:1199 +0x15f
github.com/cockroachdb/cockroach/pkg/sql/catalog/lease_test.TestMain(0xc0004cca00)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/lease/main_test.go:32 +0xb6
main.main()
        _testmain.go:118 +0x135

...

goroutine 41406 [chan receive, 29 minutes]:
github.com/cockroachdb/cockroach/pkg/sql/catalog/lease_test.TestRangefeedUpdatesHandledProperlyInTheFaceOfRaces(0xc003462b40)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/lease/lease_test.go:2356 +0x6f5
testing.tRunner(0xc003462b40, 0x4542678)
        /usr/local/go/src/testing/testing.go:991 +0xdc
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1042 +0x357
```

### PR DESCRIPTION
**Pull request by ajwerner**
I think this test was going to fail.

Fixes #52385.

Release note: None

### CODE REVIEW

**Comment by ajwerner** [comment]
FWIW I stress-raced this and couldn't repro it.

**Comment by ajwerner** [comment]
I'd also say that this doesn't actually fix the test it's just going to give more insights if it fails again instead of just blocking forever.

**Review by thoszhang — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52408)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by ajwerner** [comment]
TFTR!

bors r=lucy-zhang

**Pull request merged**
