### PR TITLE
roachtest: create simple tpce workload driver

### PR DESCRIPTION
**Pull request by msbutler**
Currently, the tpce workload is used in 2 roachtests in tpce.go. This patch makes it easier for other roachtests to init and run a tpce workload by creating a tpce driver that abstracts away the actual cmds required to init and run a tpce workload. This will make it easier to address #99787, for example.

Informs #99787

Release note: none

### CODE REVIEW

**Review by renatolabs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99810)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @msbutler and @smg260)

___
*[`pkg/cmd/roachtest/tests/tpce.go` line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99810#-NRjGvQU8TnPmEaXS_1I:-NRjGvQU8TnPmEaXS_1J:b7in8r7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e20d32fc1e6a42227b0a64bbae70eb265452b54/pkg/cmd/roachtest/tests/tpce.go#L30)):*
> ```Go
> 
> type tpceSpec struct {
> 	loadNode         option.NodeListOption
> ```

Nit: make this an `int` if you have any intentions of really having just one "load node", or rename it to `loadNodes` if having multiple workload nodes is officially supported (as suggested by the current type).
___
*[`pkg/cmd/roachtest/tests/tpce.go` line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99810#-NRjG07Y0Fk9NF4P-1s8:-NRjG07Y0Fk9NF4P-1s9:bgefxv1) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e20d32fc1e6a42227b0a64bbae70eb265452b54/pkg/cmd/roachtest/tests/tpce.go#L56)):*
> ```Go
> 		builder.WriteString(fmt.Sprintf(" --threads=%d", to.threads))
> 	}
> 	return builder.String()
> ```

May I suggest the use of `commandbuilder` here?
___
*[`pkg/cmd/roachtest/tests/tpce.go` line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99810#-NRjGChZ1l6QBkOzBuHz:-NRjGChZ1l6QBkOzBuI-:b-7rgrj3) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e20d32fc1e6a42227b0a64bbae70eb265452b54/pkg/cmd/roachtest/tests/tpce.go#L61)):*
> ```Go
> func initTPCESpec(
> 	ctx context.Context, t test.Test, c cluster.Cluster, loadNode,
> 	roachNodes option.NodeListOption,
> ```

TIL this is `crlfmt` compliant.
___
*[`pkg/cmd/roachtest/tests/tpce.go` line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99810#-NRjGGwt3G8p_tH_1VYQ:-NRjGGwt3G8p_tH_1VYR:bulxj0r) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e20d32fc1e6a42227b0a64bbae70eb265452b54/pkg/cmd/roachtest/tests/tpce.go#L63)):*
> ```Go
> 	roachNodes option.NodeListOption,
> ) (*tpceSpec, error) {
> 	t.Status("installing docker")
> ```

Suggestion: can we take a logger instance as argument and use that here instead of `t.Status` / `t.L()`. You can keep existing behavior in the your caller by passing `t.L()` and would make this struct friendlier to implementations that desire more fine grained control of test logging.

**Review by msbutler — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99810)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @renatolabs and @smg260)

___
*[`pkg/cmd/roachtest/tests/tpce.go` line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99810#-NRjGvQU8TnPmEaXS_1I:-NRmOrLtEICPAEbyMqts:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e20d32fc1e6a42227b0a64bbae70eb265452b54/pkg/cmd/roachtest/tests/tpce.go#L30)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Nit: make this an `int` if you have any intentions of really having just one "load node", or rename it to `loadNodes` if having multiple workload nodes is officially supported (as suggested by the current type).
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/tests/tpce.go` line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99810#-NRjG07Y0Fk9NF4P-1s8:-NRmcnpI0Fg0s6UBZdDY:b-pvjtin) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e20d32fc1e6a42227b0a64bbae70eb265452b54/pkg/cmd/roachtest/tests/tpce.go#L56)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

May I suggest the use of `commandbuilder` here?
</blockquote></details>

dang this is slick!!! Sadly I had to sprintf the hosts as they're passed as duplicate flags: e.g "hosts=ip1 hosts=ip2".
___
*[`pkg/cmd/roachtest/tests/tpce.go` line 61 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99810#-NRjGChZ1l6QBkOzBuHz:-NRmdJ8q4jmYrxILAczW:b-mpr7dy) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e20d32fc1e6a42227b0a64bbae70eb265452b54/pkg/cmd/roachtest/tests/tpce.go#L61)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

TIL this is `crlfmt` compliant.
</blockquote></details>

:shrug: 

```
crlfmt
diff -u old/pkg/cmd/roachtest/tests/tpce.go new/pkg/cmd/roachtest/tests/tpce.go
--- old/pkg/cmd/roachtest/tests/tpce.go	2023-03-30 09:16:29
+++ new/pkg/cmd/roachtest/tests/tpce.go	2023-03-30 09:16:29
@@ -13,17 +13,17 @@
 import (
 	"context"
 	"fmt"
-	"github.com/cockroachdb/cockroach/pkg/cmd/roachtest/roachtestutil"
-	"github.com/cockroachdb/cockroach/pkg/roachprod/logger"
 	"strings"
 	"time"

 	"github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster"
 	"github.com/cockroachdb/cockroach/pkg/cmd/roachtest/option"
 	"github.com/cockroachdb/cockroach/pkg/cmd/roachtest/registry"
+	"github.com/cockroachdb/cockroach/pkg/cmd/roachtest/roachtestutil"
 	"github.com/cockroachdb/cockroach/pkg/cmd/roachtest/spec"
 	"github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test"
 	"github.com/cockroachdb/cockroach/pkg/roachprod/install"
+	"github.com/cockroachdb/cockroach/pkg/roachprod/logger"
 	"github.com/cockroachdb/errors"
 	"github.com/stretchr/testify/require"
 )
@@ -49,7 +49,10 @@
 }

 func initTPCESpec(
-	ctx context.Context, l *logger.Logger, c cluster.Cluster, loadNode int,
+	ctx context.Context,
+	l *logger.Logger,
+	c cluster.Cluster,
+	loadNode int,
 	roachNodes option.NodeListOption,
 ) (*tpceSpec, error) {
 	l.Printf("Installing docker")
```
___
*[`pkg/cmd/roachtest/tests/tpce.go` line 63 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99810#-NRjGGwt3G8p_tH_1VYQ:-NRme4W09FcamkWAZnsQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e20d32fc1e6a42227b0a64bbae70eb265452b54/pkg/cmd/roachtest/tests/tpce.go#L63)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Suggestion: can we take a logger instance as argument and use that here instead of `t.Status` / `t.L()`. You can keep existing behavior in the your caller by passing `t.L()` and would make this struct friendlier to implementations that desire more fine grained control of test logging.
</blockquote></details>

Done.

**Review by renatolabs — APPROVED** [review]
:lgtm:

Sorry, forgot about this PR. Just one small nit!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99810#-:-NSGvOM23wpsIN6DBmNx:b-lqq75j)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msbutler and @smg260)

___
*[`pkg/cmd/roachtest/tests/tpce.go` line 56 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99810#-NRjG07Y0Fk9NF4P-1s8:-NSGuj0FDT6-_lujkUUk:b-xbnhj2) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e20d32fc1e6a42227b0a64bbae70eb265452b54/pkg/cmd/roachtest/tests/tpce.go#L56)):*
<details><summary><i>Previously, msbutler (Michael Butler) wrote…</i></summary><blockquote>

dang this is slick!!! Sadly I had to sprintf the hosts as they're passed as duplicate flags: e.g "hosts=ip1 hosts=ip2".
</blockquote></details>

Yeah, when I saw this code I thought of how we could have some APIs in that package to support use cases like this one. I'll eventually get to it.
___
*[`pkg/cmd/roachtest/tests/tpce.go` line 86 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/99810#-NSGv15K0iYHgfFGILTx:-NSGv15K0iYHgfFGILTy:b-piscfr) ([raw file](https://github.com/cockroachdb/cockroach/blob/57d3650557593403111479dbc4fcd2c75606e8a6/pkg/cmd/roachtest/tests/tpce.go#L86)):*
> ```Go
> // import of the data and schema creation.
> func (ts *tpceSpec) init(ctx context.Context, t test.Test, c cluster.Cluster, o tpceCmdOptions) {
> 	cmd := ts.newCmd(o).Flag("init", "")
> ```

Nit: while the command will run fine with this (the formatting will include extra spaces due to the empty string), the API for flags/options that don't take a corresponding value is `Option("init")`.

**Review by msbutler — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99810)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @renatolabs and @smg260)

___
*[`pkg/cmd/roachtest/tests/tpce.go` line 86 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/99810#-NSGv15K0iYHgfFGILTx:-NSLjONo5xswwITHEVY-:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/57d3650557593403111479dbc4fcd2c75606e8a6/pkg/cmd/roachtest/tests/tpce.go#L86)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Nit: while the command will run fine with this (the formatting will include extra spaces due to the empty string), the API for flags/options that don't take a corresponding value is `Option("init")`.
</blockquote></details>

Done

**Comment by msbutler** [comment]
TFTR!

bors=renatolabs

**Comment by msbutler** [comment]
bors r=renatolabs

**Pull request merged**
