### PR TITLE
sqlccl: checkpoint backup progress every minute

### PR DESCRIPTION
**Pull request by benesch**
During a backup, checkpoint the descriptor to the export storage every minute. This paves the way for resumable coordinators, as described in the backup/restore RFC (#16633).

### CODE REVIEW

**Comment by danhhz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/sqlccl/backup.go, line 53 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17070#-KpHxIvv1VCIzYD2ELOg:-KpHxIvwRMf3lI-BLnkM:b-cpym07) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0495305a7420e1c068ab59eafce4166663decb9/pkg/ccl/sqlccl/backup.go#L53)):*
> ```Go
> )
> 
> // backupCheckpointInterval is how long.
> ```

"is how long."

---

*[pkg/ccl/sqlccl/backup.go, line 54 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17070#-KpHxN5FPQg_ZDf0R9Vu:-KpHxN5Gd-4_NHkgwEyb:bbnjgno) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0495305a7420e1c068ab59eafce4166663decb9/pkg/ccl/sqlccl/backup.go#L54)):*
> ```Go
> 
> // backupCheckpointInterval is how long.
> var backupCheckpointInterval = settings.RegisterDurationSetting(
> ```

As I understand it, we generally shy away from knobs unless we really need them. I'd say this is fine as a constant

---

*[pkg/ccl/sqlccl/backup.go, line 415 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17070#-KpHxwnAOCXKtk3AEDD4:-KpHxwnAOCXKtk3AEDD5:b-7dzz07) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0495305a7420e1c068ab59eafce4166663decb9/pkg/ccl/sqlccl/backup.go#L415)):*
> ```Go
> 	stopCheckpointing := make(chan struct{})
> 	wroteCheckpoint := false
> 	go func() {
> ```

this extra goroutine is ugly (and more to keep in mind when grokking this process). how about keeping track of the last time it was checkpointed and checking if you're past some threshold when an export request comes back?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17070)*

**Comment by benesch** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/sqlccl/backup.go, line 53 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17070#-KpHxIvv1VCIzYD2ELOg:-KpI20ZBXj7l1eCoLUS9:bny0lc5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0495305a7420e1c068ab59eafce4166663decb9/pkg/ccl/sqlccl/backup.go#L53)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

"is how long."
</blockquote></details>

Hah, thanks. Will fix shortly.

---

*[pkg/ccl/sqlccl/backup.go, line 54 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17070#-KpHxN5FPQg_ZDf0R9Vu:-KpI1vwT_EL1_fZ1LR9a:b-dnyrro) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0495305a7420e1c068ab59eafce4166663decb9/pkg/ccl/sqlccl/backup.go#L54)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

As I understand it, we generally shy away from knobs unless we really need them. I'd say this is fine as a constant
</blockquote></details>

I need to turn the knob wayyyy down for testing, though, and I know you hate the mutate-defer-unmutate constant pattern. Thoughts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17070)*

**Comment by danhhz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/sqlccl/backup.go, line 54 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17070#-KpHxN5FPQg_ZDf0R9Vu:-KpI5PZiMEDaNn9_sg71:bg7f02b) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0495305a7420e1c068ab59eafce4166663decb9/pkg/ccl/sqlccl/backup.go#L54)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I need to turn the knob wayyyy down for testing, though, and I know you hate the mutate-defer-unmutate constant pattern. Thoughts?
</blockquote></details>

I have no issues with mutate-defer-unmutate. You must be thinking of someone else : - )

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17070)*

**Comment by benesch** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/ccl/sqlccl/backup.go, line 53 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17070#-KpHxIvv1VCIzYD2ELOg:-KpLMjuJDfXWvi6usE1w:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0495305a7420e1c068ab59eafce4166663decb9/pkg/ccl/sqlccl/backup.go#L53)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Hah, thanks. Will fix shortly.
</blockquote></details>

Done.

---

*[pkg/ccl/sqlccl/backup.go, line 54 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17070#-KpHxN5FPQg_ZDf0R9Vu:-KpLMiV9TzSTmglHG0nc:brnh2vc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0495305a7420e1c068ab59eafce4166663decb9/pkg/ccl/sqlccl/backup.go#L54)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I have no issues with mutate-defer-unmutate. You must be thinking of someone else : - )
</blockquote></details>

Hah, okay. Done.

---

*[pkg/ccl/sqlccl/backup.go, line 415 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17070#-KpHxwnAOCXKtk3AEDD4:-KpLMl7mbwFwXH6MLyNp:bltoxg2) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0495305a7420e1c068ab59eafce4166663decb9/pkg/ccl/sqlccl/backup.go#L415)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

this extra goroutine is ugly (and more to keep in mind when grokking this process). how about keeping track of the last time it was checkpointed and checking if you're past some threshold when an export request comes back?
</blockquote></details>

Done, but it's still somewhat ugly. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17070)*

**Comment by danhhz** [comment]
:lgtm: though it looks like you have some CI failures

---

Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/sqlccl/backup.go, line 485 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17070#-KpL_j0lz_VuQgL8PIE8:-KpL_j0lz_VuQgL8PIE9:b-zflppw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada69d8edbd0bd957b283537133fe4e9fe811b4b/pkg/ccl/sqlccl/backup.go#L485)):*
> ```Go
> 			if doCheckpoint {
> 				desc.Lock()
> 				desc.Files = make(backupFileDescriptors, len(mu.files))
> ```

the usual pattern for this is desc.Files = append(backupFileDescriptors(nil), mu.files...)

---

*[pkg/ccl/sqlccl/backup_test.go, line 427 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17070#-KpLbMb9UuAkSmjSCSc0:-KpLbMb9UuAkSmjSCSc1:b6znot2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada69d8edbd0bd957b283537133fe4e9fe811b4b/pkg/ccl/sqlccl/backup_test.go#L427)):*
> ```Go
> }
> 
> func TestBackupRestoreSystemJobs(t *testing.T) {
> ```

I'm a little concerned about how complicated this test is getting. Maybe split it into system.jobs stuff and checkpointing stuff?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17070#-:-KpLbUAsfrXlqKNOfN-f:bsdcwts)*

**Comment by benesch** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/ccl/sqlccl/backup.go, line 485 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17070#-KpL_j0lz_VuQgL8PIE8:-KpPf_-3T-dWg70f8jeE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada69d8edbd0bd957b283537133fe4e9fe811b4b/pkg/ccl/sqlccl/backup.go#L485)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

the usual pattern for this is desc.Files = append(backupFileDescriptors(nil), mu.files...)
</blockquote></details>

Done.

---

*[pkg/ccl/sqlccl/backup_test.go, line 427 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17070#-KpLbMb9UuAkSmjSCSc0:-KpPf_kxLMmLEkRD9jx-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ada69d8edbd0bd957b283537133fe4e9fe811b4b/pkg/ccl/sqlccl/backup_test.go#L427)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I'm a little concerned about how complicated this test is getting. Maybe split it into system.jobs stuff and checkpointing stuff?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17070)*

**Comment by danhhz** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/storageccl/export_storage.go, line 180 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17070#-KpQLVLgOXzbuD09QNwk:-KpQLVLh2sN5wBA-cVlR:bh5ygnq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5553dee27bc5662b2375267c293f909768ff166/pkg/ccl/storageccl/export_storage.go#L180)):*
> ```Go
> 	}
> 	path := filepath.Join(l.base, basename)
> 	fmt.Printf("NIKHIL writing path %s\n", path)
> ```

debugging?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17070)*

**Comment by benesch** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[pkg/ccl/sqlccl/backup_test.go, line 607 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/17070#-KpQmP2pluoOAZ7mjX0V:-KpQmP2pluoOAZ7mjX0W:b-4v132m) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba7be19d15e2a29514e608b113ecfe700e670b89/pkg/ccl/sqlccl/backup_test.go#L607)):*
> ```Go
> 		if len(checkpointDesc.Files) == 0 {
> 			return errors.Errorf("empty backup checkpoint descriptor")
> 		}
> ```

Also, I'm in love with how simple this diff is. Thanks for pushing me to refactor this test.

---

*[pkg/ccl/storageccl/export_storage.go, line 180 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17070#-KpQLVLgOXzbuD09QNwk:-KpQmIJAR93AePVvyWMh:bbwr2xf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5553dee27bc5662b2375267c293f909768ff166/pkg/ccl/storageccl/export_storage.go#L180)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

debugging?
</blockquote></details>

How embarrassing. Removed, thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17070)*

**Pull request merged**
