### PR TITLE
ui: add hot ranges page in Db Console

### LINKED ISSUE #40536: Human friendly hot ranges screen
**Is your feature request related to a problem? Please describe.**
There's `/_status/hotranges`, which tells us the hot ranges, but it's quite hard to use that information to gather really usable data (mapping rangeId back to exact tables etc).

**Describe the solution you'd like**
It would be nice to have some intuitive UI for this data, which could be used to identify possible application design problems (like when most of the operations happen in only a small amount of ranges).

Epic CRDB-2323

Jira issue: CRDB-5534

### PR DESCRIPTION
**Pull request by koorosh**
This change adds a new page in Db Console - Hot Ranges that display list
of hot ranges in the cluster and some useful information related to each
range. The main goal of this page is to help eliminate root cause of
hot ranges.

This page uses already implemented hot ranges API (V2) that provides
all necessary data to show.

Release note (ui change): add Hot Ranges page and link to it on the sidebar

Release justification: bug fixes and low-risk updates to new functionality

This PR is mostly based on https://github.com/cockroachdb/cockroach/pull/75073 with additional changes to apply server side pagination.

Resolves: https://github.com/cockroachdb/cockroach/issues/40536

Screen Shot 2022-03-03 at 17 19 31

### CODE REVIEW

**Review by Santamaura — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77330)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian and @koorosh)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/77330#-MxGTx0Y3BL6GcTwFSmF:-MxGTx0Y3BL6GcTwFSmG:bsd16py) (no related file):*
:lgtm: just a few wording nits :thumbsup: 

---
___
*[pkg/ui/workspaces/db-console/src/redux/cachedDataReducer.ts, line 428 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77330#-MxGRHjV1gYZktN6MaJO:-MxGRHjW0gsI9VLozOSV:bxy03ho) ([raw file](https://github.com/cockroachdb/cockroach/blob/54637a8415fc52f6c6a2b67e4703c8e4e8685111/pkg/ui/workspaces/db-console/src/redux/cachedDataReducer.ts#L428)):*
> ```XML
>   }
> 
>   // receiveCompleted is action creator to indicate that no more data to receive.
> ```

nit wording: recieveCompleted is an action creator to indicate that there is no more data to receive.
___
*[pkg/ui/workspaces/db-console/src/redux/cachedDataReducer.ts, line 438 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77330#-MxGR_LrEa4CB92VgXlm:-MxGR_LrEa4CB92VgXln:b9cyjxn) ([raw file](https://github.com/cockroachdb/cockroach/blob/54637a8415fc52f6c6a2b67e4703c8e4e8685111/pkg/ui/workspaces/db-console/src/redux/cachedDataReducer.ts#L438)):*
> ```XML
>   };
> 
>   // clearData is action creator to delete previously received data.
> ```

nit wording: clearData is an action creator to delete previously received data.
___
*[pkg/ui/workspaces/db-console/src/redux/cachedDataReducer.ts, line 527 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77330#-MxGS8457JIKbTuGlBPk:-MxGS8465A0dII1B7Ag3:b-vndllg) ([raw file](https://github.com/cockroachdb/cockroach/blob/54637a8415fc52f6c6a2b67e4703c8e4e8685111/pkg/ui/workspaces/db-console/src/redux/cachedDataReducer.ts#L527)):*
> ```XML
>       // pagination params are used across entire app, because all results are
>       // stored in single store's slice. Current implementation doesn't support
>       // to request data with different page sizes or call some arbitrary page.
> ```

nit wording: Override page_token and page_size fields to ensure that the exact same pagination params are used across the entire app because all the results are stored in the single store's slice. The current implementation doesn't support requesting data with different page sizes or calls to an arbitrary page.

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77330)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian and @koorosh)

___
*[pkg/ui/workspaces/db-console/src/redux/cachedDataReducer.ts, line 428 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77330#-MxGRHjV1gYZktN6MaJO:-MxO960C7VVn6pO0mTVe:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/54637a8415fc52f6c6a2b67e4703c8e4e8685111/pkg/ui/workspaces/db-console/src/redux/cachedDataReducer.ts#L428)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

nit wording: recieveCompleted is an action creator to indicate that there is no more data to receive.
</blockquote></details>

Done!
___
*[pkg/ui/workspaces/db-console/src/redux/cachedDataReducer.ts, line 438 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77330#-MxGR_LrEa4CB92VgXlm:-MxO9CTZ7J8Ab4OR088D:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/54637a8415fc52f6c6a2b67e4703c8e4e8685111/pkg/ui/workspaces/db-console/src/redux/cachedDataReducer.ts#L438)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

nit wording: clearData is an action creator to delete previously received data.
</blockquote></details>

Done.
___
*[pkg/ui/workspaces/db-console/src/redux/cachedDataReducer.ts, line 527 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77330#-MxGS8457JIKbTuGlBPk:-MxO9NvQE9OqlJQqwQmt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/54637a8415fc52f6c6a2b67e4703c8e4e8685111/pkg/ui/workspaces/db-console/src/redux/cachedDataReducer.ts#L527)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

nit wording: Override page_token and page_size fields to ensure that the exact same pagination params are used across the entire app because all the results are stored in the single store's slice. The current implementation doesn't support requesting data with different page sizes or calls to an arbitrary page.
</blockquote></details>

Done.

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77330)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian and @Santamaura)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/77330#-MxGTx0Y3BL6GcTwFSmF:-MxO9_huA-i7mv6KEBhn:b7269f5) (no related file):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

:lgtm: just a few wording nits :thumbsup: 
</blockquote></details>

Thanks Alex!

---

**Comment by stbof** [comment]
@Annebirzin @koorosh Can we change the spelling of Hot ranges to Hot Ranges so it matches the capitalization convention of the other labels?

**Comment by taroface** [comment]
+1 to @stbof, but please note I will be covering this and other copy changes in https://cockroachlabs.atlassian.net/browse/DOC-2840

**Pull request merged**
