### PR TITLE
sql, distsql: add scalar vs non-scalar flag to groupNode and AggregatorSpec

### PR DESCRIPTION
**Pull request by RaduBerinde**
A "scalar" aggregation is one that has no grouping columns and which
always yields one row (even if the input is empty).

Currently we designate any aggregation without grouping columns as
"scalar". This will not work anymore because the optimizer will be
able to remove grouping columns (e.g. when it knows the input has at
most one row, or when we're grouping on a constant column).

This commit makes the following changes:

 - the `addNullBucketIfEmpty` flag is moved from `groupNode.run` to
   `groupNode` and renamed to `isScalar`; when it is set, the EXPLAIN
   output shows "scalar".

 - the distsql planner now looks at this flag and populates a new
   field in the aggregator spec. The new field is a tri-state to
   provide backwards compatibility.

 - the exec factory now has separate `ConstructGroupBy` and
   `ConstructScalarGroupBy` methods.

Note that a previous change added a new distsql version in the history
but didn't actually bump the version (so I'm bumping it by 2).

Release note: None

### CODE REVIEW

**Review by rytaft — CHANGES_REQUESTED** [review]
:lgtm: 

> Reviewed 19 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27650#-:-LHhfAlH7AfNbpeLGiVY:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsqlrun/processors.proto, line 460 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27650#-LHhdf8lAA-27E3wTCKO:-LHhdf8m4qH3aJ86XyZu:baz8p6k) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fd2dd3d67efa9ef577d1371f47c5b08b9eae9d9/pkg/sql/distsqlrun/processors.proto#L460)):*
> ```protobuf
>   // Type of aggregation: a scalar aggregation has no grouping columns and
>   // always returns one result row, even when there are no input rows. A
>   // non-scalar aggregation returns no results when there are 
> ```

Looks like this comment got cut off.
___
*[pkg/sql/distsqlrun/processors.proto, line 499 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27650#-LHhdyk10eeCKE3auoby:-LHhdyk25Do18OVDEEfv:bo3g1lx) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fd2dd3d67efa9ef577d1371f47c5b08b9eae9d9/pkg/sql/distsqlrun/processors.proto#L499)):*
> ```protobuf
>   }
> 
>   optional Type type = 5 [(gogoproto.nullable) = false];
> ```

Just out of curiosity - is there a reason you added this field here? Intuitively it seems that 5 would be after 4....

**Review by knz — APPROVED** [review]
:lgtm: with comment/nit

> Reviewed 19 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27650#-:-LHhmi7A1jbSyckqBuP-:bg4wt4u)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/distsqlrun/server.go, line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27650#-LHhmDBq8spU_Gmw8WL5:-LHhmDBq8spU_Gmw8WL6:b-s7esvx) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fd2dd3d67efa9ef577d1371f47c5b08b9eae9d9/pkg/sql/distsqlrun/server.go#L78)):*
> ```Go
> // ATTENTION: When updating these fields, add to version_history.txt explaining
> // what changed.
> const Version DistSQLVersion = 17
> ```

Aside: @jordanlewis can you double-check this and see if we've released a beta version with DistSQL not correctly bumped. We'd need to keep this in mind when troubleshooting execution errors.
___
*[pkg/sql/logictest/testdata/planner_test/srfs, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27650#-LHhmXRRAUE-987Mit65:-LHhmXRRAUE-987Mit66:b-vz3f4t) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fd2dd3d67efa9ef577d1371f47c5b08b9eae9d9/pkg/sql/logictest/testdata/planner_test/srfs#L99)):*
> ```
> group                       ·                                            (count)
>  │                          count_rows()                                 ·
>  │                          ·                                            ·
> ```

huh why is there an empty line here now?

**Review by RaduBerinde — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27650#-:-LHhohgIAqDywYEQECCo:bz5mair)* status: :shipit: complete! 2 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/processors.proto, line 460 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27650#-LHhdf8lAA-27E3wTCKO:-LHhnXXjBJU79uQvO_Nd:b-5z66ao) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fd2dd3d67efa9ef577d1371f47c5b08b9eae9d9/pkg/sql/distsqlrun/processors.proto#L460)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Looks like this comment got cut off.
</blockquote></details>

I meant to remove this comment, since I put everything in the comments for the values. Fixed.
___
*[pkg/sql/distsqlrun/processors.proto, line 499 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27650#-LHhdyk10eeCKE3auoby:-LHhnh1n3aG2-QSVBOk_:b-73mx50) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fd2dd3d67efa9ef577d1371f47c5b08b9eae9d9/pkg/sql/distsqlrun/processors.proto#L499)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Just out of curiosity - is there a reason you added this field here? Intuitively it seems that 5 would be after 4....
</blockquote></details>

The field belongs next to `group_cols` because it's very related to that. The numbers are effectively a history of when fields were added, which shouldn't drive the ordering.
___
*[pkg/sql/logictest/testdata/planner_test/srfs, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27650#-LHhmXRRAUE-987Mit65:-LHhoWotDHP0jM7G6pM_:b9mmu4z) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fd2dd3d67efa9ef577d1371f47c5b08b9eae9d9/pkg/sql/logictest/testdata/planner_test/srfs#L99)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

huh why is there an empty line here now?
</blockquote></details>

It's the row that shows `scalar`, but we're removing that column here.

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27650)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/distsqlrun/processors.proto, line 499 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27650#-LHhdyk10eeCKE3auoby:-LHhpRmHDEhpP3JhEsTD:bgdws1l) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fd2dd3d67efa9ef577d1371f47c5b08b9eae9d9/pkg/sql/distsqlrun/processors.proto#L499)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The field belongs next to `group_cols` because it's very related to that. The numbers are effectively a history of when fields were added, which shouldn't drive the ordering.
</blockquote></details>

ok thanks!

**Review by rytaft — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27650)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Review by jordanlewis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27650)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/distsqlrun/server.go, line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27650#-LHhmDBq8spU_Gmw8WL5:-LHiam1K4whjVVxApNvM:bvm0zt9) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fd2dd3d67efa9ef577d1371f47c5b08b9eae9d9/pkg/sql/distsqlrun/server.go#L78)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Aside: @jordanlewis can you double-check this and see if we've released a beta version with DistSQL not correctly bumped. We'd need to keep this in mind when troubleshooting execution errors.
</blockquote></details>

Yeah, the previous patch was definitely released as an alpha. However the previous patch (ProjectSet) *did* bump the version, but just by one. The patch before it (support tuples in DistSQL) did not.

I think this just means that the last alpha doesn't actually support ProjectSet despite advertising so. I'm a little surprised that tests passed due to this.

**Comment by jordanlewis** [comment]
Whoops, didn't mean to mark that as approved... I still haven't gotten the hang of the new reviewable..

**Review by andy-kimball — APPROVED** [review]
Opt-related changes look good.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27650#-:-LHidclp1pDvLV-2arv7:babotr5)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Pull request merged**
