### PR TITLE
storage: messing with Liveness.IsHealthy

### PR DESCRIPTION
**Pull request by andreimatei**
See individual commits.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43873)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, and @asubiotto)

___
*[pkg/server/status.go, line 676 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43873#-LyFjEbPD7c-dnFakLNV:-LyFjEbQ-5FWmK5Ln8vD:bg3u4eh) ([raw file](https://github.com/cockroachdb/cockroach/blob/14780dd8ccc0f921b40736621f677a117722910d/pkg/server/status.go#L676)):*
> ```Go
> 	ls := l.LivenessStatus(
> 		clock.PhysicalTime(),
> 		0, /* threshold */
> ```

Do you not want to remove this parameter while you're here?

**Review by ajwerner — APPROVED** [review]
I'm cool with this under the expectation that you clean up this mess and remove that threshold in future PRs. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43873#-:-LyFlENI2BavMqcV7U6P:b-rcwph4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @asubiotto)

**Review by andreimatei — COMMENTED** [review]
yeah, I'm trying

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43873#-:-LyFlSso04JMTlNjkQCq:b-8mqv7g)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @asubiotto)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43873#-:-LyFlbV04pi_3litIgIU:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @asubiotto)

**Review by andreimatei — COMMENTED** [review]
acceptance/version-upgrade timed out. Couldn't repro.

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43873#-:-LyGMtEj8mWfZ7V_djmb:b-1u69us)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @asubiotto)

**Pull request merged**
