### PR TITLE
"Help Us" request on by default, and fixes

### PR DESCRIPTION
**Pull request by maxlang**
- Turned the "help us" banner on by default.
- Fixed an issue where the help us page was resetting as people entered in form data.
- Added the real privacy policy.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5485)

### CODE REVIEW

**Comment by maxlang** [comment]
cc @spencerkimball 
I added the privacy policy, but wanted to confirm that I should have accepted all edits in the word doc from the email.

**Comment by maxlang** [comment]
Also, this doesn't talk to the cockroachlabs server just yet. I'm going to add that in a separate PR.

**Comment by spencerkimball** [comment]
Kind of hard to read that privacy policy! I just sent you the most up to date one via email.

**Comment by maxlang** [comment]
@spencerkimball I confirmed I had the correct privacy policy up, and also reformatted the html (which I just auto-generated from the Word doc) to make it easier to review. Here are a couple screenshots showing what it will look like. We could also have DivisionOf take a crack at it if we want it to be nicely styled.

screen shot 2016-03-23 at 11 55 01 am
screen shot 2016-03-23 at 11 55 14 am

**Comment by spencerkimball** [comment]
Looks fine to me.

**Comment by mrtracy** [comment]
Reviewed 2 of 6 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: 5 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[ui/ts/pages/helpusprompt.ts, line 90 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5485#-KD_BXrJ3XDvyOeaX6yf:-KD_BXrJ3XDvyOeaX6yg:-1679311150) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a1590609ec56e018ac6c11f8121ef9636ec509e/ui/ts/pages/helpusprompt.ts#L90)):*
I'm reasonably sure that the linter does not, in fact, make you do this.  The type is completely apparent from the following declaration.  Just try

`hide: (): void => {`

---

*[ui/ts/pages/helpusprompt.ts, line 110 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5485#-KD_CrKv4chGb0taSrOP:-KD_CrKv4chGb0taSrOQ:1575192222) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a1590609ec56e018ac6c11f8121ef9636ec509e/ui/ts/pages/helpusprompt.ts#L110)):*
Move this "Fade the correct modal" into a subroutine, its repeated thrice.

---

*[ui/ts/pages/helpusprompt.ts, line 120 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5485#-KD_DKPkvyJg-fwIaJ30:-KD_DKPkvyJg-fwIaJ31:1056847117) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a1590609ec56e018ac6c11f8121ef9636ec509e/ui/ts/pages/helpusprompt.ts#L120)):*
Where is close even being called anymore?  Seems like it's always `dismiss()` now. 

Also, is this being executed from a timeout?  I don't understand why it needs to call `redraw()`.

---

*[ui/ts/pages/helpusprompt.ts, line 151 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5485#-KD_Cd6miSHSm-zWOlQd:-KD_Cd6miSHSm-zWOlQe:-1730212300) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a1590609ec56e018ac6c11f8121ef9636ec509e/ui/ts/pages/helpusprompt.ts#L151)):*
You can define these methods on the controller in such a way that they are bound; in fact, you are doing just that with the `hide` method in this PR! 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5485)*

**Comment by maxlang** [comment]
Review status: 5 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[ui/ts/pages/helpusprompt.ts, line 90 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5485#-KD_BXrJ3XDvyOeaX6yf:-KD_R8GQm0fo8PnnqP3M:1134087595) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a1590609ec56e018ac6c11f8121ef9636ec509e/ui/ts/pages/helpusprompt.ts#L90)):*
I get ```ts/pages/helpusprompt.ts[90, 13]: expected member-variable-declaration: 'hide' to have a typedef```

---

*[ui/ts/pages/helpusprompt.ts, line 110 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5485#-KD_CrKv4chGb0taSrOP:-KD_Q_nh9u16VrRe8akQ:-493906223) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a1590609ec56e018ac6c11f8121ef9636ec509e/ui/ts/pages/helpusprompt.ts#L110)):*
The 3rd is different, but I can combine them into one.

---

*[ui/ts/pages/helpusprompt.ts, line 120 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5485#-KD_DKPkvyJg-fwIaJ30:-KD_PmVlFcQLdnEnfHnA:-1668698214) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a1590609ec56e018ac6c11f8121ef9636ec509e/ui/ts/pages/helpusprompt.ts#L120)):*
Close is still called after the modal has been submitted (specifically from the "Thanks" modal.)

It's sometimes called by a keydown callback which isn't wired up by mithril, but I can move this to the closeOnEscape function in modal.ts where it's perhaps more appropriate.

---

*[ui/ts/pages/helpusprompt.ts, line 151 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5485#-KD_Cd6miSHSm-zWOlQd:-KD_QyrxMSonFfpXd2tm:-1497966766) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a1590609ec56e018ac6c11f8121ef9636ec509e/ui/ts/pages/helpusprompt.ts#L151)):*
Good point

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5485)*

**Comment by mrtracy** [comment]
:lgtm:

---

Review status: 4 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[ui/ts/pages/helpusprompt.ts, line 90 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5485#-KD_BXrJ3XDvyOeaX6yf:-KDdVfGJdBg--NJpM-8q:-352898587) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a1590609ec56e018ac6c11f8121ef9636ec509e/ui/ts/pages/helpusprompt.ts#L90)):*
Fine, but we are going over that linter and disabling a good bit of it after beta release.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5485#-:-KDdXcoecaO_k7gsW5UG:1417088721)*

**Pull request merged**
