### PR TITLE
kv: batch ranged intent resolution

### LINKED ISSUE #46752: kv: ranged intent resolution is not batched, regresses performance on TPC-C
Over the past few weeks, we've been tracking a performance regression in TPC-C of 4-5% that occurs when implicit SELECT FOR UPDATE is enabled (see `enable_implicit_select_for_update`).

One thing that became clear early in the investigation was that the total number of batches sent in the system rose by about 25% when running TPC-C with implicit SELECT FOR UPDATE enabled. This was surprising, as implicit SELECT FOR UPDATE is not supposed to cause the system to perform any extra work - we built it to only activate opportunistically when a scan was already going to be visiting a leaseholder to perform the row-fetch for an upcoming mutation. Using https://github.com/cockroachdb/cockroach/pull/46747, I was able to track down this increase in RPCs to a switch from `ResolveIntent` requests to `ResolveIntentRange` requests when implicit SELECT FOR UPDATE is in use. Remember that because SQL only currently issues ranged `Scan` requests and never point `Get` requests, implicit SFU is always acquiring ranged upgrade locks that overlap the point exclusive locks acquired by the following mutation, so we must release these with `ResolveIntentRange` requests.

The following graph demonstrates this effect:

Screen Shot 2020-03-30 at 5 11 56 PM

The graph shows two runs of TPC-C, first with `sql.defaults.implicit_select_for_update.enabled` set to true (the default) and second with `sql.defaults.implicit_select_for_update.enabled` set to false. The top graph shows what we had already been seeing - with implicit SFU, we issue about 25% more batches (21k vs. 16k). The bottom graph is more interesting. It shows that with implicit SFU, we issue about 11k `ResolveIntent` requests and about 5k `ResolveIntentRange` requests. Without implicit SFU, we issue about 20k `ResolveIntent` requests and no `ResolveIntentRange` requests.

So aren't we issuing more batches without implicit SFU? The answer is no, because `ResolveIntent` requests are [batched together](https://github.com/cockroachdb/cockroach/blob/93cb2eb7cac9a8e918721b5f5cbdb0f4a0823f45/pkg/kv/kvserver/intentresolver/intent_resolver.go#L823) by the `IntentResolver`. So even though we actually issue more requests, these requests are issued in [batches of 100](https://github.com/cockroachdb/cockroach/blob/93cb2eb7cac9a8e918721b5f5cbdb0f4a0823f45/pkg/kv/kvserver/intentresolver/intent_resolver.go#L64). However, `ResolveIntentRange` requests are not batched together (see below), so each request is a separate batch. So these 5k `ResolveIntentRange` requests are exactly the missing 5k extra RPCs that we see with implicit SFU enabled.
 https://github.com/cockroachdb/cockroach/blob/93cb2eb7cac9a8e918721b5f5cbdb0f4a0823f45/pkg/kv/kvserver/intentresolver/intent_resolver.go#L839-L841

This explains the modest regression in TPC-C performance and indicates that if we can lift this restriction on intent resolution batching, we should be able to close the gap.

### PR DESCRIPTION
**Pull request by nvb**
Fixes #46752.
Resolves the recent perf regression on TPC-C.

This commit follows in the footsteps of #34803 and introduces batching for ranged intent resolution, where previously only point intent resolution was batched. As we found in #46752, this is more important than it has been in the past, because implicit SELECT FOR UPDATE acquires a ranged lock on each row that it updates instead of a single-key lock.

The change addresses this by adding a third request batcher to IntentResolver. ResolveIntent requests and ResolveIntentRange requests are batched separately, which is necessary for the use of MaxSpanRequestKeys to work properly (in fact, to be accepted by DistSender at all).

To accommodate the ranged nature of ResolveIntentRange request, the notion of pagination is introduced into RequestBatcher. A MaxKeysPerBatchReq option is added to the configuration of a RequestBatcher, which corresponds to the MaxSpanRequestKeys value set on each BatchRequest header. The RequestBatcher is then taught about request pagination and how to work with partial responses. The semantics at play here are clarified in an earlier commit in the PR.

Release justification: important fix to avoid a performance regression when implicit SELECT FOR UPDATE is enabled. All commits except the last are testing-only. The last commit is subtle but small and well-tested.

@andreimatei: I assigned you because I think you know the most about `MaxSpanRequestKeys`. I'm mostly interested to get your input on the "rationalize Header.MaxSpanRequestKeys" commit (testing + comments only).

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm_strong: nice

> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 3 of 3 files at r3, 3 of 3 files at r4, 4 of 4 files at r5, 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46952#-:-M3yChYXEN_hbVzdb4Yh:b1hiy8g)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/internal/client/requestbatcher/batcher_test.go, line 32 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/46952#-M3yBph9-goAFxDgxkGk:-M3yBph9-goAFxDgxkGl:b-88bvjv) ([raw file](https://github.com/cockroachdb/cockroach/blob/801f5c1bf4c6784d11848067a1927d03076e82dc/pkg/internal/client/requestbatcher/batcher_test.go#L32)):*
> ```Go
> 
> type batchResp struct {
> 	// TODO(ajwerner): we never actually test that this result is what we expect
> ```

Fair.
___
*[pkg/internal/client/requestbatcher/batcher_test.go, line 434 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/46952#-M3yDQYvA3qpSb6OIhWM:-M3yDQYvA3qpSb6OIhWN:b-wqj1fw) ([raw file](https://github.com/cockroachdb/cockroach/blob/801f5c1bf4c6784d11848067a1927d03076e82dc/pkg/internal/client/requestbatcher/batcher_test.go#L434)):*
> ```Go
> }
> 
> // TestMaxKeysPerBatchReq exercises the RequestBatcher when it is configured to
> ```

This test is nice.

**Review by andreimatei — COMMENTED** [review]
r5 LGTM. God's work.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46952#-:-M41-ax7Di36LPJ3KmH1:b-e42gyh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/roachpb/api.proto, line 1833 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/46952#-M40zQdA1OTgrAxuVBB8:-M40zQdA1OTgrAxuVBB9:bk7qxmx) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcebaf0099586c00c10ceb4de985bb5523d44a44/pkg/roachpb/api.proto#L1833)):*
> ```protobuf
>   // Overlapping requests
>   //
>   // The spans accessed by the requests are allowed overlap. However, if any
> ```

allowed *to* overlap
___
*[pkg/roachpb/api.proto, line 1837 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/46952#-M40zZLb3PhdS9BkALOQ:-M40zZLb3PhdS9BkALOR:b-nrefu7) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcebaf0099586c00c10ceb4de985bb5523d44a44/pkg/roachpb/api.proto#L1837)):*
> ```protobuf
>   // responses in the corresponding BatchResponse. If no requests overlap, then
>   // only up to one request will return a partial result. Additionally, if two
>   // requests touch the same key, it is double counted towards the key limit.
> ```

wanna put some words here about how the distsender split factors in?
___
*[pkg/roachpb/api.proto, line 1843 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/46952#-M41-PgM5Ga5jr295wd7:-M41-PgN8KsySv-6v7N-:b10ngt6) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcebaf0099586c00c10ceb4de985bb5523d44a44/pkg/roachpb/api.proto#L1843)):*
> ```protobuf
>   // The spans accessed by requests do not need to be in sorted order. However,
>   // if the requests are not in sorted order (e.g. increasing key order for
>   // Scans and other forward requests, decreasing key order for ReverseScans),
> ```

wanna say that mixing forward and reverse scans is not permitted when the limit is used?
Also, do you know why it isn't permitted?
___
*[pkg/roachpb/api.proto, line 1854 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/46952#-M40zkmj-TUvc41FGBc-:-M40zkmj-TUvc41FGBc0:bqes59y) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcebaf0099586c00c10ceb4de985bb5523d44a44/pkg/roachpb/api.proto#L1854)):*
> ```protobuf
>   // If a limit is provided, the batch can contain only the following range
>   // request types:
>   // - ScanRequest
> ```

If this is true, please put a nod to it at the beginning of the comment where you say that this param applies to range requests. Or cut "ranged" from that sentence.

**Review by nvb — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46952#-:-M41LwDP4RTc0cGXKx4q:b-tlx7ko)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/roachpb/api.proto, line 1833 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/46952#-M40zQdA1OTgrAxuVBB8:-M41GMJ05zsPSVix45f2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcebaf0099586c00c10ceb4de985bb5523d44a44/pkg/roachpb/api.proto#L1833)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

allowed *to* overlap
</blockquote></details>

Done.
___
*[pkg/roachpb/api.proto, line 1837 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/46952#-M40zZLb3PhdS9BkALOQ:-M41LHoiBx6qFxORDcOn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcebaf0099586c00c10ceb4de985bb5523d44a44/pkg/roachpb/api.proto#L1837)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

wanna put some words here about how the distsender split factors in?
</blockquote></details>

Done.
___
*[pkg/roachpb/api.proto, line 1843 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/46952#-M41-PgM5Ga5jr295wd7:-M41GwVyBgjDCbSB39dM:b8okj9k) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcebaf0099586c00c10ceb4de985bb5523d44a44/pkg/roachpb/api.proto#L1843)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

wanna say that mixing forward and reverse scans is not permitted when the limit is used?
Also, do you know why it isn't permitted?
</blockquote></details>

I'm guessing they're not permitted because it's hard to interpret their results, but essentially that's because mixing them causes the request to be unorderable. I added a bit about this.
___
*[pkg/roachpb/api.proto, line 1854 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/46952#-M40zkmj-TUvc41FGBc-:-M41GuGp6xfsugWE7KTa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcebaf0099586c00c10ceb4de985bb5523d44a44/pkg/roachpb/api.proto#L1854)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

If this is true, please put a nod to it at the beginning of the comment where you say that this param applies to range requests. Or cut "ranged" from that sentence.
</blockquote></details>

Done.

**Comment by nvanbenschoten** [comment]
Made a "fundemental" misspelling of the word fundamental.

bors r+

**Pull request merged**
