### PR TITLE
server: add the range logs into the range debug page

### PR DESCRIPTION
**Pull request by BramGruneir**
This also adds a new range log endpoint to the admin server.

### CODE REVIEW

**Comment by BramGruneir** [comment]
screen shot 2017-05-15 at 16 03 21

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/server/debug_range.go, line 725 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15932#-KkDlRrNinF46dPUSyQN:-KkDlRrNinF46dPUSyQO:b4ux0gd) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb650e4108b2d6888a7141635b9d7105651f3af3/pkg/server/debug_range.go#L725)):*
> ```Go
> 				otherRangeID = debugRangeOutput{
> 					Value: event.OtherRangeID.String(),
> 					Title: fmt.Sprintf("Range %d", event.OtherRangeID),
> ```

`s/Range %d/r%d/g`

---

*[pkg/server/debug_range.go, line 733 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15932#-KkDlVMkNfJ5xQn23tQw:-KkDlVMkNfJ5xQn23tQx:b-apkie2) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb650e4108b2d6888a7141635b9d7105651f3af3/pkg/server/debug_range.go#L733)):*
> ```Go
> 				OtherRangeID: otherRangeID,
> 				StoreID:      *outputSameTitleValue(fmt.Sprintf("s%d", event.StoreID)),
> 				Info:         *outputSameTitleValue(event.Info),
> ```

The `Info`column is very ugly in its raw form. Could it be parsed and have useful info extracted?

---

*[pkg/server/serverpb/admin.proto, line 369 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15932#-KkDkIbieIYaKFq7_a8O:-KkDkIbieIYaKFq7_a8P:b-ev5rit) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb650e4108b2d6888a7141635b9d7105651f3af3/pkg/server/serverpb/admin.proto#L369)):*
> ```protobuf
>   // TODO(tamird): use [(gogoproto.customname) = "RangeID"] below. Need to
>   // figure out how to teach grpc-gateway about custom names.
>   int64 range_id = 1;
> ```

So you can only retrieve the last 1000 range log events? That seems limiting, though I see this is following the pattern for the `Events` endpoint. 

---

*[pkg/server/serverpb/admin.proto, line 537 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15932#-KkDkZT543A4jwO9kVrZ:-KkDkZT6nkT4uV4BS44w:b99sqkb) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb650e4108b2d6888a7141635b9d7105651f3af3/pkg/server/serverpb/admin.proto#L537)):*
> ```protobuf
>     };
>   }
> }
> ```

You've got some spurious whitespace and a missing newline (I think).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15932#-:-KkDlnA5WOqkt6dO-EUx:bnfp4nl)*

**Comment by petermattis** [comment]
Also, I wonder if it makes more sense (in a future PR) to combine the lease history and range log (a.k.a replica history) into a single range history table.

---

Review status: 0 of 11 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/server/admin.go, line 750 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15932#-KkDmwVRWXR9tQzZD_Bk:-KkDmwVSUSzrzbf2stuE:b819ywo) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb650e4108b2d6888a7141635b9d7105651f3af3/pkg/server/admin.go#L750)):*
> ```Go
> 	q.Append("SELECT timestamp, rangeID, storeID, eventType, otherRangeID, info ")
> 	q.Append("FROM system.rangelog ")
> 	q.Append("WHERE rangeID = $ ", parser.NewDInt(parser.DInt(req.RangeId)))
> ```

I think you need to query for `rangeID = $1 OR otherRangeID = $1`, otherwise you'll miss the first event for a range where it is split from its parent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15932#-:-KkDlyCBlJY_RHmdueUk:bftyogx)*

**Comment by BramGruneir** [comment]
I was thinking about combining them.  Not sure if that's the right way to go.  I'm going to be to clean up the infos in the log first.

---

Review status: 0 of 11 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/server/admin.go, line 750 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15932#-KkDmwVRWXR9tQzZD_Bk:-KkGgXegkiJOWcBUxSGR:b-4ozx14) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb650e4108b2d6888a7141635b9d7105651f3af3/pkg/server/admin.go#L750)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think you need to query for `rangeID = $1 OR otherRangeID = $1`, otherwise you'll miss the first event for a range where it is split from its parent.
</blockquote></details>

Excellent point, done, and I added the output for the range id too on the debug page, since it might be different now.  And added a light yellow highlight for a range log in which its rangeID != this rangeID. 

---

*[pkg/server/debug_range.go, line 725 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15932#-KkDlRrNinF46dPUSyQN:-KkH3abf39OqenPpFbEJ:bbkqleb) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb650e4108b2d6888a7141635b9d7105651f3af3/pkg/server/debug_range.go#L725)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/Range %d/r%d/g`
</blockquote></details>

Of course, not sure why I didn't do that in the first place.

---

*[pkg/server/debug_range.go, line 733 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15932#-KkDlVMkNfJ5xQn23tQw:-KkH3eZTh2rro5Jy3rlI:b-neiqgd) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb650e4108b2d6888a7141635b9d7105651f3af3/pkg/server/debug_range.go#L733)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The `Info`column is very ugly in its raw form. Could it be parsed and have useful info extracted?
</blockquote></details>

It can be, and will be.  But in a follow up PR.  Didn't want to do too much at once.

---

*[pkg/server/serverpb/admin.proto, line 369 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15932#-KkDkIbieIYaKFq7_a8O:-KkH3kGI4ipXyVuXFgaW:b-mglyal) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb650e4108b2d6888a7141635b9d7105651f3af3/pkg/server/serverpb/admin.proto#L369)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

So you can only retrieve the last 1000 range log events? That seems limiting, though I see this is following the pattern for the `Events` endpoint. 
</blockquote></details>

I think the correct option here would be to make this a setting.  I'll send out a follow up PR for that.

---

*[pkg/server/serverpb/admin.proto, line 537 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15932#-KkDkZT543A4jwO9kVrZ:-KkH4KmQpRX77JDNoXe6:bxv20ag) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb650e4108b2d6888a7141635b9d7105651f3af3/pkg/server/serverpb/admin.proto#L537)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

You've got some spurious whitespace and a missing newline (I think).
</blockquote></details>

Weird.  I think it's fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15932#-:-KkGgHdaix5YoJfAFV_r:bvml0on)*

**Comment by BramGruneir** [comment]
---

Review status: 0 of 11 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15932#-:-KkH9sc4TxV6E4itxxTL:bsv5bq8)*

**Comment by bdarnell** [comment]
LGTM

---

Review status: 0 of 11 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/server/serverpb/admin.proto, line 369 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15932#-KkDkIbieIYaKFq7_a8O:-KkHOAHMysme34ZCIlGr:b-bts7th) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb650e4108b2d6888a7141635b9d7105651f3af3/pkg/server/serverpb/admin.proto#L369)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

I think the correct option here would be to make this a setting.  I'll send out a follow up PR for that.
</blockquote></details>

Why a setting instead of an argument to the request? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15932#-:-KkHON67-E4IP7CQPyy2:bb6ywmx)*

**Comment by BramGruneir** [comment]
Review status: 0 of 11 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/server/serverpb/admin.proto, line 369 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15932#-KkDkIbieIYaKFq7_a8O:-KkHPrtwFgQvMTXbTTkf:b-bfswuo) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb650e4108b2d6888a7141635b9d7105651f3af3/pkg/server/serverpb/admin.proto#L369)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Why a setting instead of an argument to the request? 
</blockquote></details>

That works too.  Follow up PR coming soon.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15932)*

**Pull request merged**
