### PR TITLE
sql: add spilling to disk for window functions

### PR DESCRIPTION
**Pull request by yuzefovich**
Instead of using maps and slices for computing window functions,
we now utilize disk backed hashRowContainer and sortableRowContainer.
First, we accumulate all rows in the former and then process one
partition at a time using the latter (reusing the container in
the process).

Fixes: #32226.
Addresses: #34060.

### CODE REVIEW

**Comment by yuzefovich** [comment]
Here are some benchmarks. The performance hit is expected and is mostly caused by conversion from rows of `Datum`s to rows of `EncDatum`s, back and forth.

**Microbenchmarks.**

Microbenchmark of windower on master:
```
SUM()_OVER_()-12         	             30	  40510314 ns/op	  59.24 MB/s
SUM()_OVER_(PARTITION_BY)-12         	      5	 208841093 ns/op	  11.49 MB/s
SUM()_OVER_(ORDER_BY)-12             	     20	  75329374 ns/op	  31.86 MB/s
SUM()_OVER_(PARTITION_BY_ORDER_BY)-12         5	  234741602 ns/op	  10.22 MB/s
```

Microbenchmark of windower with this change:
```
SUM()_OVER_()-12         	              20	  84146547 ns/op	  28.52 MB/s
SUM()_OVER_(PARTITION_BY)-12         	       5	 243083195 ns/op	   9.87 MB/s
SUM()_OVER_(ORDER_BY)-12             	      10	 162281637 ns/op	  14.79 MB/s
SUM()_OVER_(PARTITION_BY_ORDER_BY)-12          5	 267884421 ns/op	   8.96 MB/s
```

**Comparison on 4 node roachprod cluster on TPCH dataset.**

Comparison on **orders** table (1500000 rows)

| Query | Master | With spilling | Difference |
| --- | --- | --- | --- |
| `SELECT count(*) OVER (PARTITION BY o_orderdate) FROM orders ORDER BY o_orderkey LIMIT 10;` | 2.136618s | 2.573388s | **+20.44%** |
| `SELECT sum(o_totalprice) OVER (PARTITION BY o_orderdate ORDER BY o_orderkey) FROM orders ORDER BY o_orderkey LIMIT 10;` | 2.9605s | 3.853905s | **+30.18%** |
| `SELECT avg(o_totalprice) OVER (PARTITION BY o_orderdate ORDER BY o_orderkey) FROM orders ORDER BY o_orderkey LIMIT 10;` | 2.878294s | 3.889543s | **+35.13%** |
| `SELECT avg(o_totalprice) OVER w, sum(o_custkey) OVER w FROM orders WINDOW w AS (PARTITION BY o_orderdate ORDER BY o_orderkey) ORDER BY o_orderkey LIMIT 10;` | 3.586276s | 5.324659s | **+48.47%** |
| `SELECT count(*) OVER w1, rank() OVER w2, avg(o_totalprice) OVER w1, sum(o_custkey) OVER w2, max(o_shippriority) OVER w2 FROM orders WINDOW w1 AS (PARTITION BY o_orderdate), w2 AS (PARTITION BY o_orderpriority ORDER BY o_orderkey) ORDER BY o_orderkey LIMIT 10;` | 8.488297s | 12.036597s | **+41.80%** |

Comparison on **lineitem** table (6001215 rows)

| Query | Master | With spilling | Difference |
| --- | --- | --- | --- |
| `SELECT count(*) OVER (PARTITION BY l_shipdate) FROM lineitem ORDER BY l_orderkey LIMIT 10;` | 6.983665s | 8.284781s | **+18.63%** |
| `SELECT sum(l_quantity) OVER (PARTITION BY l_shipdate ORDER BY l_orderkey) FROM lineitem ORDER BY l_orderkey LIMIT 10;` | 9.501593s | 12.477697s | **+31.32%** |
| `SELECT avg(l_quantity) OVER (PARTITION BY l_shipdate ORDER BY l_orderkey) FROM lineitem ORDER BY l_orderkey LIMIT 10;` | 9.588085s | 12.326114s | **+28.56%** |
| `SELECT avg(l_quantity) OVER w, sum(l_linenumber) OVER w FROM lineitem WINDOW w AS (PARTITION BY l_receiptdate ORDER BY l_orderkey) ORDER BY l_orderkey LIMIT 10;` | 12.612061s | 16.551581s | **+31.24%** |
| `SELECT row_number() OVER w1, sum(l_discount) OVER w2, last_value(l_comment) OVER w1, min(l_suppkey) OVER w2 FROM lineitem WINDOW w1 AS (PARTITION BY l_shipmode ORDER BY l_orderkey), w2 AS (PARTITION BY l_commitdate) ORDER BY l_orderkey LIMIT 10;` | 29.75081s | 41.872176s | **+40.74%** |

**Comment by yuzefovich** [comment]
@jordanlewis @asubiotto It is ready for a look.

I left several TODOs with the questions, and that leaking iterators panic when the node ctrl-c'ed while window functions are being computed needs to be figured out.

**Review by jordanlewis — COMMENTED** [review]
Pretty much :lgtm: at this point, a few comments left

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34308#-:-LY5KPbA7DmLbnbMkcb4:b-o2slb1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/distsqlrun/windower.go, line 457 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34308#-LY4tq8570I-YWop1F69:-LY4tq87EWm-09k4aowQ:bw8oszx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c461f9ac6f8d1400075e178f10480bddc78aa211/pkg/sql/distsqlrun/windower.go#L457)):*
> ```Go
> // This allows for using the same row container without having to resort it
> // multiple times.
> func (w *windower) findOrderOfWindowFnsToProcessIn() {
> ```

Cool stuff! Simple, but effective.
___
*[pkg/sql/distsqlrun/windower.go, line 174 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34308#-LY5JgIDBkOjGdkfHgox:-LY5JgIDBkOjGdkfHgoy:bnvdg9f) ([raw file](https://github.com/cockroachdb/cockroach/blob/45d50b2702882b5d8da56f812f8f9d0487275ece/pkg/sql/distsqlrun/windower.go#L174)):*
> ```Go
> 	w.inputTypes = input.OutputTypes()
> 	// TODO(yuzefovich): should this be processorBase.Ctx?
> 	ctx := w.evalCtx.Ctx()
> ```

I think processorBase.Ctx gets initialized down below in Init. It gets set to `flowCtx.NewEvalCtx()`. So what I would consider doing is using `InitWithEvalCtx`on `windower` down below instead of `init`, and then everyone will be sharing the new evalCtx you just created.
___
*[pkg/sql/distsqlrun/windower.go, line 641 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34308#-LY5J04X4nbP6W3EJs0F:-LY5J04X4nbP6W3EJs0G:b4cuu5z) ([raw file](https://github.com/cockroachdb/cockroach/blob/45d50b2702882b5d8da56f812f8f9d0487275ece/pkg/sql/distsqlrun/windower.go#L641)):*
> ```Go
> 	// TODO(yuzefovich): we don't know how many partitions there are. How should
> 	// we account for this memory?
> 	w.partitionSizes = make([]int, 0, 8)
> ```

I think we should probably grow an account each time this slice is appended to.
___
*[pkg/sql/rowcontainer/hash_row_container.go, line 957 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34308#-LY5HVYnDW0Hc-S8P20U:-LY5HVYnDW0Hc-S8P20V:bvkw58f) ([raw file](https://github.com/cockroachdb/cockroach/blob/45d50b2702882b5d8da56f812f8f9d0487275ece/pkg/sql/rowcontainer/hash_row_container.go#L957)):*
> ```Go
> 			newIterator := h.NewUnmarkedIterator(ctx)
> 			i := 0
> 			for newIterator.Rewind(); ; newIterator.Next() {
> ```

This should use Seek to jump to the previous spot rather than iterating, which will take a long time. Isn't it possible?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34308)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/distsqlrun/windower.go, line 174 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34308#-LY5JgIDBkOjGdkfHgox:-LYMtSmM3WKPPSrvbVuG:b1icake) ([raw file](https://github.com/cockroachdb/cockroach/blob/45d50b2702882b5d8da56f812f8f9d0487275ece/pkg/sql/distsqlrun/windower.go#L174)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think processorBase.Ctx gets initialized down below in Init. It gets set to `flowCtx.NewEvalCtx()`. So what I would consider doing is using `InitWithEvalCtx`on `windower` down below instead of `init`, and then everyone will be sharing the new evalCtx you just created.
</blockquote></details>

Done. Also, the answer to my TODO question is probably "no" because as far as I see `processorBase.Ctx` is initialized within `Start` method by `processorBase.StartInternal`.
___
*[pkg/sql/distsqlrun/windower.go, line 641 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34308#-LY5J04X4nbP6W3EJs0F:-LYMwNY6EHE5cHljB5lj:bn2wr4) ([raw file](https://github.com/cockroachdb/cockroach/blob/45d50b2702882b5d8da56f812f8f9d0487275ece/pkg/sql/distsqlrun/windower.go#L641)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think we should probably grow an account each time this slice is appended to.
</blockquote></details>

I agree since I don't see any other way without doing an extra iteration over the container (or maintaining a map).
___
*[pkg/sql/rowcontainer/hash_row_container.go, line 957 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34308#-LY5HVYnDW0Hc-S8P20U:-LYMyroF3NkonbdBFy_z:b-5dyqgb) ([raw file](https://github.com/cockroachdb/cockroach/blob/45d50b2702882b5d8da56f812f8f9d0487275ece/pkg/sql/rowcontainer/hash_row_container.go#L957)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This should use Seek to jump to the previous spot rather than iterating, which will take a long time. Isn't it possible?
</blockquote></details>

To use `Seek` we need to have last read key by the in-memory iterator which it doesn't maintain. We could add that, do you think it's worth it?

Also, please take a look at another TODO question I've just added below.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34308)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/rowcontainer/hash_row_container.go, line 924 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34308#-LYTYbSN0UNetqLp_kWx:-LYTYbSN0UNetqLp_kWy:bs2kf5t) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5e95bd4c4a3f92074fde568a4b5ec85fa861d61/pkg/sql/rowcontainer/hash_row_container.go#L924)):*
> ```Go
> // h.unmarkedIterators. All such iterators will be recreated if the container
> // spills to disk.
> // Note: it is the responsibility of iterator's owner to remove the iterator
> ```

This approach seems dirty to me. @jordanlewis do you have any suggestions? Should I possibly introduce a new wrapper, like `RecreatableRowIterator`?

**Review by jordanlewis — COMMENTED** [review]
I would:

1. Get rid of the "recreatable" name for the iterators
2. Add a backreference from the iterator to its container
3. Tell the Close method to remove the iterator from the container so you can get rid of the NotRecreate thing

Then I think we're good to go here.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34308#-:-LYX58TsBF4xU3y6Zpau:bdzd8my)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/rowcontainer/hash_row_container.go, line 957 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34308#-LY5HVYnDW0Hc-S8P20U:-LYX3ixxDcxCewfKW8Ti:b-vbj2v2) ([raw file](https://github.com/cockroachdb/cockroach/blob/45d50b2702882b5d8da56f812f8f9d0487275ece/pkg/sql/rowcontainer/hash_row_container.go#L957)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

To use `Seek` we need to have last read key by the in-memory iterator which it doesn't maintain. We could add that, do you think it's worth it?

Also, please take a look at another TODO question I've just added below.
</blockquote></details>

I do think this is worth it, yes, it's just one key, right?
___
*[pkg/sql/rowcontainer/hash_row_container.go, line 924 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34308#-LYTYbSN0UNetqLp_kWx:-LYX45awClx45eeAjMVi:b-ns4o34) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5e95bd4c4a3f92074fde568a4b5ec85fa861d61/pkg/sql/rowcontainer/hash_row_container.go#L924)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

This approach seems dirty to me. @jordanlewis do you have any suggestions? Should I possibly introduce a new wrapper, like `RecreatableRowIterator`?
</blockquote></details>

Yeah I think the way to fix this would be to do it in iterator.Close, by keeping a backreference to the row container that owns the iterator. 
___
*[pkg/sql/rowcontainer/hash_row_container.go, line 939 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/34308#-LYX4ezVBim2y7e5M2dF:-LYX4ezVBim2y7e5M2dG:b-g7vx4w) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b41aef4c2066bd28c5aabef896135f3b12d974c/pkg/sql/rowcontainer/hash_row_container.go#L939)):*
> ```Go
> 	for j, iterator := range h.unmarkedIterators {
> 		if i == iterator {
> 			h.unmarkedIterators = append(h.unmarkedIterators[:j], h.unmarkedIterators[j+1:]...)
> ```

Does this panic if `j` is the last index in the slice?
___
*[pkg/sql/rowcontainer/hash_row_container_test.go, line 197 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/34308#-LYX3eoo7JTGYfL4D_5w:-LYX3eoo7JTGYfL4D_5x:bds3i2m) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b41aef4c2066bd28c5aabef896135f3b12d974c/pkg/sql/rowcontainer/hash_row_container_test.go#L197)):*
> ```Go
> 	// container to disk, and verifies that the iterator was recreated and points
> 	// to the appropriate row.
> 	t.Run("VerifyIteratorRecreation", func(t *testing.T) {
> ```

Nice test.
___
*[pkg/sql/sqlbase/errors.go, line 221 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/34308#-LYX3_29APZWD1ih_YW2:-LYX3_2A9TkLSgs5VxSE:b-6tcvx2) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b41aef4c2066bd28c5aabef896135f3b12d974c/pkg/sql/sqlbase/errors.go#L221)):*
> ```Go
> 	return errHasCode(err, pgerror.CodeOutOfMemoryError)
> }
> ```

nit: extra blank line

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34308)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/rowcontainer/hash_row_container.go, line 957 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34308#-LY5HVYnDW0Hc-S8P20U:-LYXRuO31fZiLu_vC4s7:b-dtkdrq) ([raw file](https://github.com/cockroachdb/cockroach/blob/45d50b2702882b5d8da56f812f8f9d0487275ece/pkg/sql/rowcontainer/hash_row_container.go#L957)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I do think this is worth it, yes, it's just one key, right?
</blockquote></details>

Done, thanks.
___
*[pkg/sql/rowcontainer/hash_row_container.go, line 924 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34308#-LYTYbSN0UNetqLp_kWx:-LYXTt4E5pZdr72e8n4t:b-xlhlo9) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5e95bd4c4a3f92074fde568a4b5ec85fa861d61/pkg/sql/rowcontainer/hash_row_container.go#L924)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Yeah I think the way to fix this would be to do it in iterator.Close, by keeping a backreference to the row container that owns the iterator. 
</blockquote></details>

Done with introducing a wrapper, or were you thinking of modifying the current iterators?
___
*[pkg/sql/rowcontainer/hash_row_container.go, line 939 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/34308#-LYX4ezVBim2y7e5M2dF:-LYXDc0fEdvhv-kn5ahD:b-x0yesg) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b41aef4c2066bd28c5aabef896135f3b12d974c/pkg/sql/rowcontainer/hash_row_container.go#L939)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Does this panic if `j` is the last index in the slice?
</blockquote></details>

No panic, works correctly as expected.
___
*[pkg/sql/sqlbase/errors.go, line 221 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/34308#-LYX3_29APZWD1ih_YW2:-LYXAKTI2oHWWefiyZ3k:b-7tv3xi) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b41aef4c2066bd28c5aabef896135f3b12d974c/pkg/sql/sqlbase/errors.go#L221)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

nit: extra blank line
</blockquote></details>

I don't think it is extra (there is no blank line here https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sqlbase/errors.go#L221, I probably incorrectly resolved merge conflict in a previous PR).

**Review by jordanlewis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34308)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/distsqlrun/windower.go, line 670 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/34308#-LYYfshRDI_SJ8O-JqF5:-LYYfshS4ayEHYyr42H7:b-epwtz1) ([raw file](https://github.com/cockroachdb/cockroach/blob/78bb02624a7462f24071349f621a22e12555eefc/pkg/sql/distsqlrun/windower.go#L670)):*
> ```Go
> 		return err
> 	}
> 	defer (*i).Close()
> ```

Also this should not be dereferenced.
___
*[pkg/sql/rowcontainer/hash_row_container_test.go, line 223 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/34308#-LYYfhsD2q5tyw6QIrRj:-LYYfhsD2q5tyw6QIrRk:bknn7od) ([raw file](https://github.com/cockroachdb/cockroach/blob/78bb02624a7462f24071349f621a22e12555eefc/pkg/sql/rowcontainer/hash_row_container_test.go#L223)):*
> ```Go
> 			t.Fatal(err)
> 		}
> 		defer (*i).Close()
> ```

I believe doing it this way will have the same problem as before - the iterator won't be closed correctly. You shouldn't dereference it before calling Close - that makes a copy of the iterator.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34308)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/distsqlrun/windower.go, line 670 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/34308#-LYYfshRDI_SJ8O-JqF5:-LYYhUWXElIgg82GLUYW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/78bb02624a7462f24071349f621a22e12555eefc/pkg/sql/distsqlrun/windower.go#L670)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Also this should not be dereferenced.
</blockquote></details>

Done.
___
*[pkg/sql/rowcontainer/hash_row_container_test.go, line 223 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/34308#-LYYfhsD2q5tyw6QIrRj:-LYYhK7G4kkNqtjKn7Hw:b-i080hs) ([raw file](https://github.com/cockroachdb/cockroach/blob/78bb02624a7462f24071349f621a22e12555eefc/pkg/sql/rowcontainer/hash_row_container_test.go#L223)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I believe doing it this way will have the same problem as before - the iterator won't be closed correctly. You shouldn't dereference it before calling Close - that makes a copy of the iterator.
</blockquote></details>

You're right, fixed, thanks!

**Comment by yuzefovich** [comment]
Thanks a lot for patiently reviewing this and related PRs!

bors r+

**Pull request merged**
