### PR TITLE
storage: deflake TestStoreRangeRemoveDead

### LINKED ISSUE #6319: storage: TestStoreRangeRemoveDead is flaky
https://circleci.com/gh/cockroachdb/cockroach/16885

Test is sitting on its WaitGroup:

```
goroutine 14692 [semacquire]:
sync.runtime_Semacquire(0xc82139f62c)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*WaitGroup).Wait(0xc82139f620)
	/usr/local/go/src/sync/waitgroup.go:127 +0xb4
github.com/cockroachdb/cockroach/storage_test.TestStoreRangeRemoveDead(0xc821691ef0)
	/go/src/github.com/cockroachdb/cockroach/storage/client_raft_test.go:1168 +0x617
testing.tRunner(0xc821691ef0, 0x23ab710)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892
```

```
I160426 14:50:28.310914 kv/txn_coord_sender.go:286  txn coordinator: 0.05 txn/sec, 100.00/0.00/0.00/0.00 %cmmt/cmmt1pc/abrt/abnd, 0/0/0 avg/σ/max duration, 0.0/0.0/0 avg/σ/max restarts (2 samples)
I160426 14:50:28.312368 kv/txn_coord_sender.go:286  txn coordinator: 0.00 txn/sec, 0.00/0.00/0.00/0.00 %cmmt/cmmt1pc/abrt/abnd, 0/0/0 avg/σ/max duration, 0.0/0.0/0 avg/σ/max restarts (0 samples)
I160426 14:50:28.327542 kv/txn_coord_sender.go:286  txn coordinator: 0.00 txn/sec, 0.00/0.00/0.00/0.00 %cmmt/cmmt1pc/abrt/abnd, 0/0/0 avg/σ/max duration, 0.0/0.0/0 avg/σ/max restarts (0 samples)
panic: test timed out after 1m10s

goroutine 14940 [running]:
panic(0x14e9560, 0xc820cae540)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:725 +0x14b
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x3a
```

### PR DESCRIPTION
**Pull request by BramGruneir**
We were too fancy with the test.  IIRC, we couldn't just gossip stores when I
originally wrote it and we needed to use the store gossiper.  But now we can
just rely on stores gossiping themselves.

Fixes #6319

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7484)

### CODE REVIEW

**Comment by tamird** [comment]
Were you able to reproduce this before the change? How many runs did it take? After the change, how many runs did you run without reproducing?

I can't reproduce this locally at all.

**Comment by BramGruneir** [comment]
Yes, I was able to reproduce the failure easily, usually after 300-400 stressrace runs.

I did 10k stressrace runs without it showing up again.

**Comment by tamird** [comment]
I'm at 1000 stressrace runs (9 minutes) pre-change and haven't reproduced

**Comment by BramGruneir** [comment]
Not sure what to tell you, it reliably failed for me.

**Comment by tamird** [comment]
Indeed, the trick was to run it with a reduced timeout (see updated commit message).

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7484#-:-KLIayI8IVgnYHTGgqhK:1417088721)*

**Comment by tschottdorf** [comment]
https://circleci.com/gh/tschottdorf/cockroach/2387

On Mon, Jun 27, 2016 at 4:41 PM Tobias Schottdorf <tobias@cockroachlabs.com>
wrote:

> This one definitely failed spuriously for me as well.
>
> On Mon, Jun 27, 2016 at 1:59 PM Bram Gruneir <notifications@github.com>
> wrote:
>
>> Not sure what to tell you, it reliably failed for me.
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/cockroachdb/cockroach/pull/7484#issuecomment-228824400>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AE135ATWruwSoGUZ2SkEtPKpCWQCjiRGks5qQA-CgaJpZM4I_S1E>
>> .
>>
> --
>
> -- Tobias
>
-- 

-- Tobias

**Comment by tamird** [comment]
Looks like that build doesn't include this PR.

**Pull request merged**
