### PR TITLE
cluster-ui: speed up insights page request 

### LINKED ISSUE #107291: ui: schema insights request timing out
The schema insights page is reading from `crdb_internal.statement_statistics` which triggers a cluster-wide fanout to collect in-memory sql stats. This request can timeout for larger clusters with a lot of in-memory data.

Jira issue: CRDB-29980

### PR DESCRIPTION
**Pull request by xinhaoz**
Previously, we were querying from `crdb_internal.statement_statistics` and
`crdb_internal.transaction_statistics` on the schema insights and txn insights
pages. Querying from this table is slow because it triggers a cluster-wide
fanout to collect unflushsed sql stats. We can use the persisted table instead,
which will lag behind a little in live data, but will be much faster to query from.

Epic: none
Fixes: https://github.com/cockroachdb/cockroach/issues/107291

Release note (bug fix): Schema insights page should hit request timeouts less
frequently, if at all.

DB Console Loom, showing pages issuing requests work as expected:
https://www.loom.com/share/ef1baad105d0444596a32c8430234b88

### CODE REVIEW

**Comment by xinhaoz** [comment]
Will update with Loom.

**Review by maryliag — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107292)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh and @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/schemaInsightsApi.ts` line 199 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/107292#-N_um6WJ8tEv_bfRbjlm:-N_um6WK89zM4uL2aVu4:bju3e9k) ([raw file](https://github.com/cockroachdb/cockroach/blob/db6369176472346f9a2680182f71eb664c9116ad/pkg/ui/workspaces/cluster-ui/src/api/schemaInsightsApi.ts#L199)):*
> ```XML
>       ) AS rank 
>     FROM 
>       crdb_internal.statement_statistics_persisted 
> ```

is there any call to the transaction table that should also be updated on this PR?

**Review by maryliag — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107292)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh and @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/txnInsightsApi.ts` line 264 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/107292#-Navc3xs6YVUfTUqrm6G:-Navc3xs6YVUfTUqrm6H:b-j5k52l) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca371163d97c96a67f0f50440ee5f9c7390effd3/pkg/ui/workspaces/cluster-ui/src/api/txnInsightsApi.ts#L264)):*
> ```XML
>       id =>
>         stmtFingerprintToQuery.get(id) ??
>         `Query unavailable for stmt fingerprint ${id}`,
> ```

is this showing on the UI? if so, use the full name, so `statement` and not `stmt`

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107292#-:-Nb0BAUdAF9zbj0RhMFm:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @koorosh)

**Comment by xinhaoz** [comment]
TFTR!
bors r+

**Comment by xinhaoz** [comment]
blathers backport 23.1

**Pull request merged**
