### PR TITLE
Decommissioning a node (i)

### PR DESCRIPTION
**Pull request by neeral**
As part of RFC to [decommission a node](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/decommission.md) and issue #6198. The overall feature will be broken down into smaller changes.

Two commits:
-  Add new Decommission field to node liveness table
    - storage: Add Decommissioning field to Node Liveness
-  Mark node as Draining when it discovers it is in Decommission state
    - server: Set draining when in Decommission

@tschottdorf has the most context, also @bdarnell 
I've incorporated some comments from a prior review: https://reviewable.io/reviews/cockroachdb/cockroach/16425#-KmS9vV3e0v20Cr8mVZx

### CODE REVIEW

**Comment by neeral** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/server/server.go, line 819 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16528#-Kmc7eelb2NoB2lAGJj4:-Kmc7eelb2NoB2lAGJj5:b-ndep0u) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbc7c88da2469a1e5601b8a96871375d4d8b7822/pkg/server/server.go#L819)):*
> ```Go
> 		}
> 		if liveness != nil && liveness.Decommissioning && !liveness.Draining {
> 			s.stopper.RunWorker(ctx, func(context.Context) {
> ```

This runs in a worker to avoid deadlock on `NodeLiveness.sem`. The heartbeat function locks `sem` and will release it after the callback completes. The callback calls `SetDraining` which is blocked on acquiring `sem`, and so cannot complete.
The worker allows `SetDraining` to be performed asychronously. This design is after discussion with @tschottdorf

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16528)*

**Comment by tschottdorf** [comment]
Some comments, but looks good so far! I think it's better to squash the two commits you have here since we have an overall preference to not introduce things before they are used.

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/server/server.go, line 819 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16528#-Kmc7eelb2NoB2lAGJj4:-KmcB_xatJkGWtXlwyJS:b-1k09zx) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbc7c88da2469a1e5601b8a96871375d4d8b7822/pkg/server/server.go#L819)):*
<details><summary><i>Previously, neeral (Neeral Dodhia) wrote…</i></summary><blockquote>

This runs in a worker to avoid deadlock on `NodeLiveness.sem`. The heartbeat function locks `sem` and will release it after the callback completes. The callback calls `SetDraining` which is blocked on acquiring `sem`, and so cannot complete.
The worker allows `SetDraining` to be performed asychronously. This design is after discussion with @tschottdorf
</blockquote></details>

I originally suggested adding a `drainingSem` to nodeLiveness to avoid multiple in-flight requests to go out of order. For example, we don't want calls to `SetDraining` and multiple decommission-commission calls to go out of order; that could lead to a node in decommissioning mode, but without being in the right draining mode. `drainingSem` is a 1-buffered channel that is also consulted by `SetDraining` where it would be blocked on. Here I think it's better to just noop and have an additional check that's not in a callback but at the end of each node liveness heartbeat so that omitting calls to `SetDraining` is OK given that you'll drain later).

In other words, if the node finds out it's decommissioned and starts draining, and then someone explicitly undrains, then it should still enter draining mode at least after the next heartbeat. And if someone de- and recommissions rapidly, we shouldn't have 10 tasks around that fight each other with draining and undraining operations.

---

*[pkg/storage/node_liveness.go, line 150 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16528#-KmcDw7Id2h858pbs5lw:-KmcDw7Id2h858pbs5lx:b-7mn9bo) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbc7c88da2469a1e5601b8a96871375d4d8b7822/pkg/storage/node_liveness.go#L150)):*
> ```Go
> var (
> 	errNodeDrainingSet        = errors.New("node already has given draining value")
> 	errNodeDecommissioningSet = errors.New("node already has given decommissioning value")
> ```

why not just "node is already decommissioning" (`errNodeDrainingSet` isn't really a good example to follow... :smile:)

---

*[pkg/storage/node_liveness_test.go, line 731 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16528#-KmcDWcZTgd8VrcPR7qK:-KmcDWcZTgd8VrcPR7qL:b-5jdn5k) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbc7c88da2469a1e5601b8a96871375d4d8b7822/pkg/storage/node_liveness_test.go#L731)):*
> ```Go
> 	defer mtc.Stop()
> 	mtc.Start(t, 3)
> 	mtc.initGossipNetwork()
> ```

Can this test also check the case in which one node marks another one as decommissioning as well? I've looked at the code and I think that's basically what happens, but better to have it be an explicit case.

---

*[pkg/storage/node_liveness_test.go, line 755 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16528#-KmcDidyxoBWdVLHyR_g:-KmcDidyxoBWdVLHyR_h:bvnxxcq) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbc7c88da2469a1e5601b8a96871375d4d8b7822/pkg/storage/node_liveness_test.go#L755)):*
> ```Go
> 
> 	// Restarted node appears once again in the store list.
> 	verifyNodeIsDecommissioning(t, mtc, nodeID)
> ```

Would this just see the pre-restart state? I.e. would it really fail if the node just wiped the decommissioned flag?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16528#-:-KmcE6bWBJSqRzpT7xKB:b-jvqcqw)*

**Comment by neeral** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/server/server.go, line 819 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16528#-Kmc7eelb2NoB2lAGJj4:-Kmd5r6jEXX_7ZYSjuLQ:bro7h6z) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbc7c88da2469a1e5601b8a96871375d4d8b7822/pkg/server/server.go#L819)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

I originally suggested adding a `drainingSem` to nodeLiveness to avoid multiple in-flight requests to go out of order. For example, we don't want calls to `SetDraining` and multiple decommission-commission calls to go out of order; that could lead to a node in decommissioning mode, but without being in the right draining mode. `drainingSem` is a 1-buffered channel that is also consulted by `SetDraining` where it would be blocked on. Here I think it's better to just noop and have an additional check that's not in a callback but at the end of each node liveness heartbeat so that omitting calls to `SetDraining` is OK given that you'll drain later).

In other words, if the node finds out it's decommissioned and starts draining, and then someone explicitly undrains, then it should still enter draining mode at least after the next heartbeat. And if someone de- and recommissions rapidly, we shouldn't have 10 tasks around that fight each other with draining and undraining operations.
</blockquote></details>

I don't quite follow your suggestion. I've tried to put everything down explicitly below.


I understand that the concerns are:
- multiple decommission/recommission/drain/undrain actions causing:
   - these calls to go out-of-order
   - multiple tasks all trying to drain/undrain causing contention


These are the places in the code to consider:
- node liveness heartbeat:
  - locks `sem`
- heartbeat callback
  - called by above and so runs holding `sem`
  - calls `SetDraining`via server.Drain()
- server.Drain()
  - invoked from elsewhere (e.g. control signal)
  - calls `SetDraining`
- node_liveness.SetDraining
  - locks `sem`


A proposed solution is to use `drainingSem`, which is a unbuffered channel.
- `node_liveness.SetDraining` reads from `drainingSem` and blocks if it's empty.
- heartbeat callback fires off a stopper.Task which attempts to write into `drainingSem`. Using `select`, if it can't it becomes a noop. If it can write, then it calls `SetDraining`.
- `server.Drain()` writes into `drainingSem` and blocks if it's full.


This would achieve the following:
- at most one task from the heartbeat callback will exist at all times, even with repeated decommission/recommission operations 
- explicit drain/undrain actions will block and be performed at some point


Things I don't understand:
- "Here I think it's better to just noop and have an additional check that's not in a callback but at the end of each node liveness heartbeat so that omitting calls to SetDraining is OK given that you'll drain later)."
  - I don't understand why we need an additional check. What would the additional check do? At some point, the callback would succeed in calling `SetDraining`
- "if the node finds out it's decommissioned and starts draining, and then someone explicitly undrains, then it should still enter draining mode at least after the next heartbeat"
  - Is the following flow of node liveness states as per your understanding:
    1. draining and decommissioning
    1. user explicitly undrains
    1. undraining and decommissioning
    1. next heartbeat occurs and its callback runs
    1. draining and decommissioning
- Why does it need to be a 1-buffered channel? I think an un-buffered channel would work.

---

*[pkg/storage/node_liveness_test.go, line 731 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16528#-KmcDWcZTgd8VrcPR7qK:-KmdBzSNCQYFbQssVYrG:bfx70ex) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbc7c88da2469a1e5601b8a96871375d4d8b7822/pkg/storage/node_liveness_test.go#L731)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Can this test also check the case in which one node marks another one as decommissioning as well? I've looked at the code and I think that's basically what happens, but better to have it be an explicit case.
</blockquote></details>

Where should I put this test? I understand that this would need `test_cluster` and `test_cluster` depends on both `storage` and `server` packages.

---

*[pkg/storage/node_liveness_test.go, line 754 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16528#-KmdD6DU8nvd8G7YxilV:-KmdD6DU8nvd8G7YxilW:bsrfxn7) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbc7c88da2469a1e5601b8a96871375d4d8b7822/pkg/storage/node_liveness_test.go#L754)):*
> ```Go
> 	mtc.restartStore(nodeIdx)
> 
> 	// Restarted node appears once again in the store list.
> ```

stale comment (from copy-paste)

---

*[pkg/storage/node_liveness_test.go, line 755 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16528#-KmcDidyxoBWdVLHyR_g:-KmdDEuQ2kQQYCd9QlPM:b-805237) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbc7c88da2469a1e5601b8a96871375d4d8b7822/pkg/storage/node_liveness_test.go#L755)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Would this just see the pre-restart state? I.e. would it really fail if the node just wiped the decommissioned flag?
</blockquote></details>

I'm not sure. Is it fine to add a sleep before verifying? Is there some other way I can check that the node restarted (e.g. would the Epoch change?)

So, I wait until the Epoch changes and this implies that the node has restarted and sent a new heartbeat. Hence, can then assert the Decommissioning flag. If the node wiped the Decommissioning flag on restart, this would then fail.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16528)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/server/server.go, line 819 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16528#-Kmc7eelb2NoB2lAGJj4:-KmdPJgyYSPHOeHTsjpd:b-h8f9sl) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbc7c88da2469a1e5601b8a96871375d4d8b7822/pkg/server/server.go#L819)):*
<details><summary><i>Previously, neeral (Neeral Dodhia) wrote…</i></summary><blockquote>

I don't quite follow your suggestion. I've tried to put everything down explicitly below.


I understand that the concerns are:
- multiple decommission/recommission/drain/undrain actions causing:
   - these calls to go out-of-order
   - multiple tasks all trying to drain/undrain causing contention


These are the places in the code to consider:
- node liveness heartbeat:
  - locks `sem`
- heartbeat callback
  - called by above and so runs holding `sem`
  - calls `SetDraining`via server.Drain()
- server.Drain()
  - invoked from elsewhere (e.g. control signal)
  - calls `SetDraining`
- node_liveness.SetDraining
  - locks `sem`


A proposed solution is to use `drainingSem`, which is a unbuffered channel.
- `node_liveness.SetDraining` reads from `drainingSem` and blocks if it's empty.
- heartbeat callback fires off a stopper.Task which attempts to write into `drainingSem`. Using `select`, if it can't it becomes a noop. If it can write, then it calls `SetDraining`.
- `server.Drain()` writes into `drainingSem` and blocks if it's full.


This would achieve the following:
- at most one task from the heartbeat callback will exist at all times, even with repeated decommission/recommission operations 
- explicit drain/undrain actions will block and be performed at some point


Things I don't understand:
- "Here I think it's better to just noop and have an additional check that's not in a callback but at the end of each node liveness heartbeat so that omitting calls to SetDraining is OK given that you'll drain later)."
  - I don't understand why we need an additional check. What would the additional check do? At some point, the callback would succeed in calling `SetDraining`
- "if the node finds out it's decommissioned and starts draining, and then someone explicitly undrains, then it should still enter draining mode at least after the next heartbeat"
  - Is the following flow of node liveness states as per your understanding:
    1. draining and decommissioning
    1. user explicitly undrains
    1. undraining and decommissioning
    1. next heartbeat occurs and its callback runs
    1. draining and decommissioning
- Why does it need to be a 1-buffered channel? I think an un-buffered channel would work.
</blockquote></details>

The considerations are basically due to the following:

1. the callback shouldn't block (if it does, perhaps because draining has a problem, then the node liveness loop would be stuck as well, i.e. the node would be marked as dead after a while)
2. I assumed that the callback wouldn't fire after every heartbeat. Seems it does though, so in the event of an explicit `SetDraining(false)`, it seems that we'd be OK, with the succession of events that you outlined!
3. Just seems preferable not to have multiple competing tasks, in particular since `SetDraining(.)` may not even be threadsafe (it may be, but would have to check & augment commentary throughout appropriately).

---

*[pkg/storage/node_liveness_test.go, line 731 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16528#-KmcDWcZTgd8VrcPR7qK:-KmdS0XEBFo3qtldzCDI:b-xlveis) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbc7c88da2469a1e5601b8a96871375d4d8b7822/pkg/storage/node_liveness_test.go#L731)):*
<details><summary><i>Previously, neeral (Neeral Dodhia) wrote…</i></summary><blockquote>

Where should I put this test? I understand that this would need `test_cluster` and `test_cluster` depends on both `storage` and `server` packages.
</blockquote></details>

Maybe I'm missing something - your `SetDeommissioning` methods allow one node to mark another one as being decommissioned, right? I thought you would just have another node mark `nodeIdx` as decommissioned in one run of the test.

---

*[pkg/storage/node_liveness_test.go, line 755 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16528#-KmcDidyxoBWdVLHyR_g:-KmdT7efm0NMa4g_JmBe:b-gjcdwz) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbc7c88da2469a1e5601b8a96871375d4d8b7822/pkg/storage/node_liveness_test.go#L755)):*
<details><summary><i>Previously, neeral (Neeral Dodhia) wrote…</i></summary><blockquote>

I'm not sure. Is it fine to add a sleep before verifying? Is there some other way I can check that the node restarted (e.g. would the Epoch change?)

So, I wait until the Epoch changes and this implies that the node has restarted and sent a new heartbeat. Hence, can then assert the Decommissioning flag. If the node wiped the Decommissioning flag on restart, this would then fail.
</blockquote></details>

Yeah, looks like `restartStore` gives makes a new node liveness, and when the heartbeat loop starts it first increments the epoch - I think your suggestion should work! You can use `testutils.SucceedsSoon`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16528)*

**Comment by neeral** [comment]
Review status: 6 of 10 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/server/server.go, line 819 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16528#-Kmc7eelb2NoB2lAGJj4:-KmhTETt3DxjdPGWvdWW:b-7sk2rw) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbc7c88da2469a1e5601b8a96871375d4d8b7822/pkg/server/server.go#L819)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

The considerations are basically due to the following:

1. the callback shouldn't block (if it does, perhaps because draining has a problem, then the node liveness loop would be stuck as well, i.e. the node would be marked as dead after a while)
2. I assumed that the callback wouldn't fire after every heartbeat. Seems it does though, so in the event of an explicit `SetDraining(false)`, it seems that we'd be OK, with the succession of events that you outlined!
3. Just seems preferable not to have multiple competing tasks, in particular since `SetDraining(.)` may not even be threadsafe (it may be, but would have to check & augment commentary throughout appropriately).
</blockquote></details>

Cool. I have added a 1-buffered channel to act as a semaphore that restricts at most one callback worker from running, and this is surrounded in a `select`. This should satisfy 1 and 3. I've read `SetDraining(.)` and it seems thread-safe.

---

*[pkg/storage/node_liveness.go, line 150 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16528#-KmcDw7Id2h858pbs5lw:-KmdElDr1s6IZhZyOeeY:bc3iqo8) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbc7c88da2469a1e5601b8a96871375d4d8b7822/pkg/storage/node_liveness.go#L150)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

why not just "node is already decommissioning" (`errNodeDrainingSet` isn't really a good example to follow... :smile:)
</blockquote></details>

This error can be thrown when either decommissioning or recommissioning the node, i.e. setting or unsetting the value. While  "node is already decommissioning" is more human-readable, it doesn't capture both cases.

---

*[pkg/storage/node_liveness_test.go, line 754 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16528#-KmdD6DU8nvd8G7YxilV:-Kme8Djx-7kc2Tyki8Mz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbc7c88da2469a1e5601b8a96871375d4d8b7822/pkg/storage/node_liveness_test.go#L754)):*
<details><summary><i>Previously, neeral (Neeral Dodhia) wrote…</i></summary><blockquote>

stale comment (from copy-paste)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16528)*

**Comment by neeral** [comment]
I've squashed the commits, addressed comments. I've left you a slack message about how to write some additional unit tests which involve restarting the server.

---

Review status: 6 of 10 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16528#-:-KmhTo8z-Bt167UBvTPE:b-xrdk35)*

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/server/server.go, line 819 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16528#-Kmc7eelb2NoB2lAGJj4:-KmmYKeZTZmds8YMC4Fl:b148as) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbc7c88da2469a1e5601b8a96871375d4d8b7822/pkg/server/server.go#L819)):*
<details><summary><i>Previously, neeral (Neeral Dodhia) wrote…</i></summary><blockquote>

Cool. I have added a 1-buffered channel to act as a semaphore that restricts at most one callback worker from running, and this is surrounded in a `select`. This should satisfy 1 and 3. I've read `SetDraining(.)` and it seems thread-safe.
</blockquote></details>

You don't need to put the semaphore on `Server` since you only use it here. Just allocate it before the call to `RunWorker`.

---

*[pkg/storage/node_liveness_test.go, line 144 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16528#-KmmWNBaYVMMB9ALSfX4:-KmmWNBaYVMMB9ALSfX5:by8ypst) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ba66fcce2be766792547b3b0747035cdd1bd78a/pkg/storage/node_liveness_test.go#L144)):*
> ```Go
> }
> 
> func verifyEpochIncremented(t *testing.T, mtc *multiTestContext, nodeIdx int, expectedEpoch int64) {
> ```

I know it's not your code, but it's not technically guaranteed that you get to see exactly epoch 2 (it could increment twice, somehow, perhaps). All you care about is that it's `>=2` (so `expectedEpoch` -> `minExpEpoch` and change the comparison and error message).
Also I think you extracted the code here but forgot to remove the original.

---

*[pkg/storage/node_liveness_test.go, line 741 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16528#-KmmX30w9gWaLDqtKDjj:-KmmX30w9gWaLDqtKDjk:b-wyjspc) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ba66fcce2be766792547b3b0747035cdd1bd78a/pkg/storage/node_liveness_test.go#L741)):*
> ```Go
> // TestNodeLivenessSetDecommissioning verifies that when decommissioning, a
> // node's liveness record is updated and remains after restart.
> func testNodeLivenessSetDecommissioning(t *testing.T, nodeIdx int) {
> ```

maybe `decommissioningNodeIdx` is better here.

The comment is stale (move it to the actual test function).

---

*[pkg/storage/node_liveness_test.go, line 768 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16528#-KmmWpcBbcSeWrfiqWZz:-KmmWpcBbcSeWrfiqW_-:b-yktfx3) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ba66fcce2be766792547b3b0747035cdd1bd78a/pkg/storage/node_liveness_test.go#L768)):*
> ```Go
> 	mtc.restartStore(nodeIdx)
> 
> 	// wait until store has restarted and published a new heartbeat to ensure not
> ```

Capitalization, punctuation.

---

*[pkg/storage/node_liveness_test.go, line 777 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16528#-KmmXFawN82GwR-94H2L:-KmmXFawN82GwR-94H2M:b868ykq) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ba66fcce2be766792547b3b0747035cdd1bd78a/pkg/storage/node_liveness_test.go#L777)):*
> ```Go
> func TestNodeLivenessSetDecommissioning(t *testing.T) {
> 	defer leaktest.AfterTest(t)()
> 	// sets itself to decommissioning
> ```

Capitalization, punctuation (here and below).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16528#-:-KmmYeYo79QihDw9hLfb:bnfp4nl)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/storage/node_liveness.go, line 150 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16528#-KmcDw7Id2h858pbs5lw:-KmmYfYDUzOJE_cqOzHM:b1jvzfz) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbc7c88da2469a1e5601b8a96871375d4d8b7822/pkg/storage/node_liveness.go#L150)):*
<details><summary><i>Previously, neeral (Neeral Dodhia) wrote…</i></summary><blockquote>

This error can be thrown when either decommissioning or recommissioning the node, i.e. setting or unsetting the value. While  "node is already decommissioning" is more human-readable, it doesn't capture both cases.
</blockquote></details>

I still think these error messages are so bad that when you see them you will have to go through the code and figure out what they mean, but it also looks like they're purely internal and can be removed (?) - see my other comment.

---

*[pkg/storage/node_liveness.go, line 247 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16528#-KmmZ6QjzWfVUV-t6F7_:-KmmZ6QjzWfVUV-t6F7a:bnrr3py) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ba66fcce2be766792547b3b0747035cdd1bd78a/pkg/storage/node_liveness.go#L247)):*
> ```Go
> 	if err := nl.updateLiveness(ctx, &newLiveness, liveness, func(actual Liveness) error {
> 		if actual.Decommissioning == newLiveness.Decommissioning {
> 			return errNodeDecommissioningSet
> ```

why not return `nil` here? You make it `nil` at the caller. Probably the same applies to `errNodeDrainingSet`,

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16528)*

**Comment by neeral** [comment]
Thanks, please take another look - addressed the minor comments. If there's nothing more, go ahead and merge.

---

Review status: 7 of 10 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/server/server.go, line 819 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16528#-Kmc7eelb2NoB2lAGJj4:-Kn1nP_YuMNWfFP2ikU_:b6vris3) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbc7c88da2469a1e5601b8a96871375d4d8b7822/pkg/server/server.go#L819)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

You don't need to put the semaphore on `Server` since you only use it here. Just allocate it before the call to `RunWorker`.
</blockquote></details>

Done. `sem` is allocated before the call to `StartHeartbeat`. It can't be done before `RunWorker` as that's inside the heartbeat callback function and would get re-allocated each time.

---

*[pkg/storage/node_liveness.go, line 150 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16528#-KmcDw7Id2h858pbs5lw:-Kn1bfvpOBkv81Pa8Yua:b-c00xcy) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbc7c88da2469a1e5601b8a96871375d4d8b7822/pkg/storage/node_liveness.go#L150)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

I still think these error messages are so bad that when you see them you will have to go through the code and figure out what they mean, but it also looks like they're purely internal and can be removed (?) - see my other comment.
</blockquote></details>

Yes, agree completely.

---

*[pkg/storage/node_liveness.go, line 247 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16528#-KmmZ6QjzWfVUV-t6F7_:-Kn1bkpJ3i-0IZ9SCXzJ:bgxp0vb) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ba66fcce2be766792547b3b0747035cdd1bd78a/pkg/storage/node_liveness.go#L247)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

why not return `nil` here? You make it `nil` at the caller. Probably the same applies to `errNodeDrainingSet`,
</blockquote></details>

Agree.
I've also done the same for `errNodeDrainingSet`. This has slightly different semantics: see how `setSelf` is called on failure vs success case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16528#-:-Kn1nlTqwurA9vmzjb7y:b-b14zx6)*

**Comment by tschottdorf** [comment]
Thanks Neeral! Looking good.

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16528#-:-Kn5AxcY6fOAHTxfeeDF:b-a17c7g)*

**Comment by tschottdorf** [comment]
Reviewed 7 of 7 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16528)*

**Comment by tschottdorf** [comment]
@neeral I rebased this for you and ran `make generate` (I also added some missing dots at the end of comments because OCD). Will merge on green, thanks again!

**Pull request merged**
