### PR TITLE
intentresolver: coalesce GCRequests into batches

### LINKED ISSUE #33574: storage: Coalesce Transaction Record GC
**Problem**

Currently when a transaction commits its leaseholder launches an async task to resolve all intents and then subsequently issues a request to GC the transaction record. This means that all committed transactions require an additional raft entry to remove their transaction records. These transaction record deletions could occur in a single batch. For write-only, transactional workloads this could remove almost one raft entry per transaction which is a potentially huge win. 

An implementation will likely involve extending the `storage.intentResolver` to group transaction records on a per-range basis and issue a single batch request per range. While there is a chance that the range may have changed for a given transaction record, the DistSender will deal separating the batch.

**Benchmarking**

Most of the existing write heavy work loads, like kv0 avoid transactions and hit the one-phase-commit fast path. To reveal this change we'll likely need to use kv0 with a large number of splits and a batch size of 2.

### PR DESCRIPTION
**Pull request by ajwerner**
This PR comes in two commits. The first introduces a library for batching individual requests by range ID and sends them based on configured size and time policies, the second adopts this library in the IntentResolver. There is certainly some tuning and cleanup to be done in the first commit but I wanted to get this out there and see how y'all feel about it. The most egregious part is likely the naming.

On the plus side, for a specific and certainly somewhat contrived benchmark using the below command on 3x n1-standard-32's the change yields an appreciable win.
 ```
roachprod run ajwerner-test:4 -- ./workload run kv '{pgurl:1-3}' --init --splits=256 --duration 90s --batch 2 --read-percent=0 --concurrency=2048
```
```
name       old ops/s   new ops/s   delta
KV0     6.23k ± 1%  7.49k ± 2%  +20.12%  (p=0.008 n=5+5)
```

Fixes #33574.

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
This is great! I'm curious what the effects are on smaller machines as well (i.e. 4 and 16-core).

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34242#-:-LXKwc7U-aTBbOYpyMpe:b-89xh2r)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/storage/intentresolver/intent_resolver.go, line 70 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34242#-LXKvyq01ifgBNnsBGZw:-LXKvyq01ifgBNnsBGZx:b-ljgl6k) ([raw file](https://github.com/cockroachdb/cockroach/blob/087e4657014d1559cf431ebdc420f524691bf051/pkg/storage/intentresolver/intent_resolver.go#L70)):*
> ```Go
> 	// defaultGCBatchIdle is the default duration which the gc request batcher
> 	// will wait between requests for a range before sending it.
> 	defaultGCBatchIdle = 50 * time.Millisecond
> ```

Same thing here, these both seem a little conservative. This is just a GC process, so there's really no urgency here. Is there any movement in benchmarks if you double both of these?

I'm also not sure whether we need an idle wait at all for this Txn record GC process. What do you think?
___
*[pkg/storage/intentresolver/intent_resolver.go, line 149 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34242#-LXKvjUn1yNIUQxGjE0L:-LXKvjUn1yNIUQxGjE0M:b-534vpd) ([raw file](https://github.com/cockroachdb/cockroach/blob/087e4657014d1559cf431ebdc420f524691bf051/pkg/storage/intentresolver/intent_resolver.go#L149)):*
> ```Go
> 	ir.batcher = batcher.New(batcher.Config{
> 		Name:            "intent_resolver_batcher",
> 		MaxMsgsPerBatch: 100,
> ```

This could probably be larger, maybe 1024?
___
*[pkg/util/batcher/batcher.go, line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34242#-LXKJ5lf72PVI7pIZWle:-LXKJ5lf72PVI7pIZWlf:b-jzsy6s) ([raw file](https://github.com/cockroachdb/cockroach/blob/04f591364a43d384f1fc755f124829dbc4a2746e/pkg/util/batcher/batcher.go#L15)):*
> ```Go
> // permissions and limitations under the License.
> 
> // Package batcher is a library to enable easy batching.
> ```

s/batching/batching of operations/
___
*[pkg/util/batcher/batcher.go, line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34242#-LXKbcvABvSX8o4519aq:-LXKbcvABvSX8o4519ar:b-yx6b6k) ([raw file](https://github.com/cockroachdb/cockroach/blob/04f591364a43d384f1fc755f124829dbc4a2746e/pkg/util/batcher/batcher.go#L130)):*
> ```Go
> // Send sends req as a part of a batch. An error is returned if the context
> // is canceled before the sending of the request completes.
> func (b *Batcher) Send(
> ```

I'm a little surprised that this abstraction is dealing with `roachpb.Requet`s and `client.Sender`s. I would have expected it to be more generic, along the lines of `singleflight.Group`. What inspired this approach?
___
*[pkg/util/batcher/batcher.go, line 271 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34242#-LXKQKkc3x5q7hvdzvdU:-LXKQKkc3x5q7hvdzvdV:b-o2gzv4) ([raw file](https://github.com/cockroachdb/cockroach/blob/04f591364a43d384f1fc755f124829dbc4a2746e/pkg/util/batcher/batcher.go#L271)):*
> ```Go
> func (b *batch) batchRequest() roachpb.BatchRequest {
> 	req := roachpb.BatchRequest{}
> 	for _, r := range b.reqs {
> ```

`req.Add(b.reqs...)`

Also, let's preallocate `req.Requests`:

`ba.Requests = make([]roachpb.RequestUnion, 0, len(b.reqs))`. You could also bake that logic into `BatchRequest.Add` if you'd like.
___
*[pkg/util/batcher/batcher.go, line 338 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34242#-LXKLbf4-j9cElb99Hbg:-LXKLbf57w00UDdQXt2O:bq9nib1) ([raw file](https://github.com/cockroachdb/cockroach/blob/04f591364a43d384f1fc755f124829dbc4a2746e/pkg/util/batcher/batcher.go#L338)):*
> ```Go
> }
> 
> // batchQueue is a container for batch objects which offers O(1) get based on
> ```

Make a note here about the ordering of `batch` structs in this queue.

**Review by ajwerner — COMMENTED** [review]
I'll run some more benchmarks. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34242#-:-LXLGSmP17qP7y7CCRrz:bqpshdl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/storage/intentresolver/intent_resolver.go, line 70 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34242#-LXKvyq01ifgBNnsBGZw:-LXLG27HDXt6d4Z_eJvY:b-cthejr) ([raw file](https://github.com/cockroachdb/cockroach/blob/087e4657014d1559cf431ebdc420f524691bf051/pkg/storage/intentresolver/intent_resolver.go#L70)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Same thing here, these both seem a little conservative. This is just a GC process, so there's really no urgency here. Is there any movement in benchmarks if you double both of these?

I'm also not sure whether we need an idle wait at all for this Txn record GC process. What do you think?
</blockquote></details>

My concern about not including an idle wait is in the case where we have a very large volume of transactions over a very large number of different ranges. If we find ourselves in a scenario where intent resolution becomes synchronous, not having an idle wait could lead to a major impact on latency.
___
*[pkg/storage/intentresolver/intent_resolver.go, line 149 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34242#-LXKvjUn1yNIUQxGjE0L:-LXLGbOQ9GBH0O6M2DuD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/087e4657014d1559cf431ebdc420f524691bf051/pkg/storage/intentresolver/intent_resolver.go#L149)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This could probably be larger, maybe 1024?
</blockquote></details>

Done.
___
*[pkg/util/batcher/batcher.go, line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34242#-LXKbcvABvSX8o4519aq:-LXLDS0aAWY8fMpFQR9c:b8h5d6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/04f591364a43d384f1fc755f124829dbc4a2746e/pkg/util/batcher/batcher.go#L130)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm a little surprised that this abstraction is dealing with `roachpb.Requet`s and `client.Sender`s. I would have expected it to be more generic, along the lines of `singleflight.Group`. What inspired this approach?
</blockquote></details>

My initial implementation was somewhat more generic but I worried that I was making it too generic. My perspective was that it ought to be easy to take a more specific interface and generalize it. It's easy enough to turn rangeID into `interface{}` here and abstract the Sender into either a function or simple interface to round-trip a batch.  I'll take a stab at generalizing it and you can see how you feel.
___
*[pkg/util/batcher/batcher.go, line 271 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34242#-LXKQKkc3x5q7hvdzvdU:-LXLEV71AOWYGS08qH11:boby7e8) ([raw file](https://github.com/cockroachdb/cockroach/blob/04f591364a43d384f1fc755f124829dbc4a2746e/pkg/util/batcher/batcher.go#L271)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`req.Add(b.reqs...)`

Also, let's preallocate `req.Requests`:

`ba.Requests = make([]roachpb.RequestUnion, 0, len(b.reqs))`. You could also bake that logic into `BatchRequest.Add` if you'd like.
</blockquote></details>

can't quite call use variadic because r here isn't a req but rather embeds one but the preallocation is done.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34242)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/storage/intentresolver/intent_resolver.go, line 149 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34242#-LXKvjUn1yNIUQxGjE0L:-LXLRr156ARaJa8aHBTX:b-3jqx6o) ([raw file](https://github.com/cockroachdb/cockroach/blob/087e4657014d1559cf431ebdc420f524691bf051/pkg/storage/intentresolver/intent_resolver.go#L149)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The performance here ends up being very finicky. Moving the MaxWait up to 1s and this batch size up to 1024 means that we're very commonly going to hit the 1000 limit in the intentresolver to make resolution synchronous. This makes tail latency higher than not batching. Interestingly with these settings we see a ~3% throughput increase on 4 cores and a ~25% throughput decrease on 16 cores. This is just due to the dramatically larger general throughput and thus greater number of requests forced to resolve synchronously. I think in the previous benchmarking the smaller MsgsPerBatch prevent the backpressure.

One option would be to run the GC task separately on a different semaphore or no semaphore at all. I'm going to play with that.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34242)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/storage/intentresolver/intent_resolver.go, line 149 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34242#-LXKvjUn1yNIUQxGjE0L:-LXLbfiK2CakHBnnui1W:b-27a0pv) ([raw file](https://github.com/cockroachdb/cockroach/blob/087e4657014d1559cf431ebdc420f524691bf051/pkg/storage/intentresolver/intent_resolver.go#L149)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

The performance here ends up being very finicky. Moving the MaxWait up to 1s and this batch size up to 1024 means that we're very commonly going to hit the 1000 limit in the intentresolver to make resolution synchronous. This makes tail latency higher than not batching. Interestingly with these settings we see a ~3% throughput increase on 4 cores and a ~25% throughput decrease on 16 cores. This is just due to the dramatically larger general throughput and thus greater number of requests forced to resolve synchronously. I think in the previous benchmarking the smaller MsgsPerBatch prevent the backpressure.

One option would be to run the GC task separately on a different semaphore or no semaphore at all. I'm going to play with that.
</blockquote></details>

At 1024 MaxMsgsPerBatch and 1s MaxWait and 200ms MaxIdle with the gc request run in a separate goroutine off of the semaphore I see on 16 core machines:
```
name       old ops/s   new ops/s   delta
Cockroach  6.13k ± 1%  6.43k ± 0%  +4.93%  (p=0.008 n=5+5)
```

on 4 core machines:
```
name       old ops/s   new ops/s   delta
Cockroach  2.32k ± 1%  2.47k ± 1%  +6.38%  (p=0.008 n=5+5)
```

I'm starting to feel pretty surprised by the initial huge win on 32 core machines. Running more benchmarks there now.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34242)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/storage/intentresolver/intent_resolver.go, line 149 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34242#-LXKvjUn1yNIUQxGjE0L:-LXLfztC0jmWCnFuZAll:bknwvm8) ([raw file](https://github.com/cockroachdb/cockroach/blob/087e4657014d1559cf431ebdc420f524691bf051/pkg/storage/intentresolver/intent_resolver.go#L149)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

At 1024 MaxMsgsPerBatch and 1s MaxWait and 200ms MaxIdle with the gc request run in a separate goroutine off of the semaphore I see on 16 core machines:
```
name       old ops/s   new ops/s   delta
Cockroach  6.13k ± 1%  6.43k ± 0%  +4.93%  (p=0.008 n=5+5)
```

on 4 core machines:
```
name       old ops/s   new ops/s   delta
Cockroach  2.32k ± 1%  2.47k ± 1%  +6.38%  (p=0.008 n=5+5)
```

I'm starting to feel pretty surprised by the initial huge win on 32 core machines. Running more benchmarks there now.
</blockquote></details>

I'm seeing the win more than hold up on 32 core machines. I can't explain the complete lack of linearity. 
```
name       old ops/s   new ops/s   delta
Cockroach  6.27k ± 1%  8.36k ± 1%  +33.28%  (p=0.008 n=5+5)
```

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34242)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/storage/intentresolver/intent_resolver.go, line 70 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34242#-LXKvyq01ifgBNnsBGZw:-LXOx3818F6FHYrAiguu:b-e1god5) ([raw file](https://github.com/cockroachdb/cockroach/blob/087e4657014d1559cf431ebdc420f524691bf051/pkg/storage/intentresolver/intent_resolver.go#L70)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

My concern about not including an idle wait is in the case where we have a very large volume of transactions over a very large number of different ranges. If we find ourselves in a scenario where intent resolution becomes synchronous, not having an idle wait could lead to a major impact on latency.
</blockquote></details>

That makes me wonder whether coalescing requests _beneath_ the semi-synchronous boundary is the right approach or whether we'll want to restructure this slightly. Would we ever want a synchronous resolution to wait in a batch? Similarly, should every request in a batch contribute to the async limit (which causes the issue you brought up)?
___
*[pkg/storage/intentresolver/intent_resolver.go, line 149 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34242#-LXKvjUn1yNIUQxGjE0L:-LXOyIgmB39ov4VNadx2:b-e7lhsz) ([raw file](https://github.com/cockroachdb/cockroach/blob/087e4657014d1559cf431ebdc420f524691bf051/pkg/storage/intentresolver/intent_resolver.go#L149)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I'm seeing the win more than hold up on 32 core machines. I can't explain the complete lack of linearity. 
```
name       old ops/s   new ops/s   delta
Cockroach  6.27k ± 1%  8.36k ± 1%  +33.28%  (p=0.008 n=5+5)
```
</blockquote></details>

Glad it held up!
___
*[pkg/util/batcher/batcher.go, line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34242#-LXKbcvABvSX8o4519aq:-LXOyUYm7aBsTckvy7Ev:bk1g9vs) ([raw file](https://github.com/cockroachdb/cockroach/blob/04f591364a43d384f1fc755f124829dbc4a2746e/pkg/util/batcher/batcher.go#L130)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

My initial implementation was somewhat more generic but I worried that I was making it too generic. My perspective was that it ought to be easy to take a more specific interface and generalize it. It's easy enough to turn rangeID into `interface{}` here and abstract the Sender into either a function or simple interface to round-trip a batch.  I'll take a stab at generalizing it and you can see how you feel.
</blockquote></details>

I'll defer to you on whether that makes this more or less readable.
___
*[pkg/util/batcher/batcher.go, line 271 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34242#-LXKQKkc3x5q7hvdzvdU:-LXOyerM9-j4zTAoPfNt:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/04f591364a43d384f1fc755f124829dbc4a2746e/pkg/util/batcher/batcher.go#L271)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

can't quite call use variadic because r here isn't a req but rather embeds one but the preallocation is done.
</blockquote></details>

:thumbsup: 
___
*[pkg/util/batcher/batcher.go, line 338 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34242#-LXKLbf4-j9cElb99Hbg:-LXOykatDOotMGXLkk3v:b-xzrnjx) ([raw file](https://github.com/cockroachdb/cockroach/blob/04f591364a43d384f1fc755f124829dbc4a2746e/pkg/util/batcher/batcher.go#L338)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Make a note here about the ordering of `batch` structs in this queue.
</blockquote></details>

Sorry, I meant make a note that they were ordered based on deadline. Otherwise, it's not particularly clear what `popFront` means.

**Comment by nvanbenschoten** [comment]
Let me know when this is ready for another look.

**Review by ajwerner — COMMENTED** [review]
@nvanbenschoten PTAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34242#-:-LXv0D-J9Q1W6-lB-k0l:bt5xftw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/storage/intentresolver/intent_resolver.go, line 70 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/34242#-LXKvyq01ifgBNnsBGZw:-LXv07-P76mZtL5YGrXi:brloo0t) ([raw file](https://github.com/cockroachdb/cockroach/blob/087e4657014d1559cf431ebdc420f524691bf051/pkg/storage/intentresolver/intent_resolver.go#L70)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

That makes me wonder whether coalescing requests _beneath_ the semi-synchronous boundary is the right approach or whether we'll want to restructure this slightly. Would we ever want a synchronous resolution to wait in a batch? Similarly, should every request in a batch contribute to the async limit (which causes the issue you brought up)?
</blockquote></details>

See how you feel about the new behavior. 
___
*[pkg/util/batcher/batcher.go, line 130 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/34242#-LXKbcvABvSX8o4519aq:-LXv01mN3fqsCTna1ah2:bp9rff0) ([raw file](https://github.com/cockroachdb/cockroach/blob/04f591364a43d384f1fc755f124829dbc4a2746e/pkg/util/batcher/batcher.go#L130)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'll defer to you on whether that makes this more or less readable.
</blockquote></details>

It did not.

**Review by nvb — APPROVED** [review]
:lgtm_strong: and nice testing too.

> Reviewed 2 of 4 files at r7, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34242#-:-LXvo60y3KGOG2M7tmQd:b7sfga9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/storage/intentresolver/intent_resolver.go, line 683 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/34242#-LXvnP8I2hhORR-GvxKn:-LXvnP8I2hhORR-GvxKo:b3u2ft7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bd95e904db0fb35f26b5dfa6aa074ed49ac5fe8/pkg/storage/intentresolver/intent_resolver.go#L683)):*
> ```Go
> 	now hlc.Timestamp,
> 	poison bool,
> 	asyncGC bool,
> ```

It's worth mentioning somewhere that if `asyncGC = false`, the caller should be prepared for this method to take longer than strictly necessary due to the batch waiting mechanism.

**Review by nvb — COMMENTED** [review]
:lgtm: once we address the last comment.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34242#-:-LXypMw0EdHO9tYkabN_:b66gsho)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/storage/intentresolver/intent_resolver.go, line 722 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/34242#-LXyp4Cw4vlg3M99mJAk:-LXyp4Cw4vlg3M99mJAl:bss79ba) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e72c01020fee84720d5d4f4649367ec82d3e21b/pkg/storage/intentresolver/intent_resolver.go#L722)):*
> ```Go
> 			}
> 		})
> 	if err != nil && onComplete != nil {
> ```

Leave a note that this means that the async task never started (so there's no race when accessing `onComplete`).

You could also cover both cases in this function with
```
defer func() {
    if err != nil && onComplete != nil {
        onComplete(err)
    }
}()
```

**Comment by tbg** [comment]
Nice! Thanks for getting this done.

**Pull request merged**
