### PR TITLE
settings: classify jobs.retention_time as a public cluster setting

### PR DESCRIPTION
**Pull request by johnrk-zz**
**Classify jobs.retention_time as public cluster setting**
Inspired by both of these issues [Missing jobs cluster setting doc](https://github.com/cockroachdb/docs/issues/7334) and [cluster setting mentioned on one page and not another](https://github.com/cockroachdb/docs/issues/7452), it's been concluded that jobs.retention_time cluster setting should be public. In our public docs, [it's been updated](https://github.com/cockroachdb/docs/pull/7511).

However, it's still listed as non-public when querying SHOW ALL CLUSTER SETTINGS; in the SQL Client.

This change follows the patterns when we first [classified cluster settings as public and non-public](https://github.com/cockroachdb/cockroach/pull/42520/commits).

**Testing:**
Environment:
Screen Shot 2020-06-15 at 4 09 09 PM

cockroach demo

1. When running SHOW ALL CLUSTER SETTINGS;
Expected: in the "public column," it should show as "true"
Actual: it appears as true
2. When running "SHOW CLUSTER SETTINGS;
Expected: it should be listed
Actual: it's listed

**Output:**
jobs.retention_time                                              | 336h0m0s                                  | d            |  true  | the amount of time to retain records for completed jobs before

### CODE REVIEW

**Comment by dt** [comment]
I think you need to run `make` to re-generate the automated listing of public settings to reflect the changed status and then amend the commit to include that as well to get the CI to pass.

**Comment by johnrk** [comment]
Got it. i've added the autogenerated files from running make.

**Comment by johnrk** [comment]
Are the *.pb.go files needed?

**Comment by dt** [comment]
I don't _think_ you should be seeing any generated pb diffs from that source diff, so something might be a bit off -- could try checking out those files and re-running. 

Also, we usually either rebase and squash or just amend the original commit, rather than put fixes in a separate commit, since post-merge when going back through the history, we like to have all the tests / checks able to pass on each individual commit.

**Comment by knz** [comment]
@johnrk you can remove the .pb.go files from the PR. They appear as changed beause you likely are using Go 1.14, and the generation format changed between 1.13 (which we use in the repo) and 1.14.

**Comment by knz** [comment]
The remainder of the changes LGTM for me

**Comment by johnrk** [comment]
closing the PR in favor of this new one: https://github.com/cockroachdb/cockroach/pull/50585

**Pull request closed without merging**
