### PR TITLE
stats: fix race condition when refreshing cache

### PR DESCRIPTION
**Pull request by rytaft**
This commit fixes a race condition that was introduced in #51616.
The race condition existed because it was possible for two refreshes
to be triggered in close succession, and there was no mechanism to
prevent the first refresh from overwriting the second if it was
delayed.

We fix the race condition by introducing two boolean flags into each
cache entry: `refreshing` and `mustRefreshAgain`. If `refreshing` is true,
that indicates that the current statistics for this table are stale,
and we are in the process of fetching the updated stats from the database.
In the mean time, other callers can use the stale stats and do not need to
wait.

If a goroutine tries to perform a refresh when a refresh is already
in progress, it will see that `refreshing=true` and will set the
`mustRefreshAgain` flag to `true` before returning. When the original
goroutine that was performing the refresh returns from the database and
sees that `mustRefreshAgain=true`, it will trigger another refresh.

Informs #50863

Release note: None

### CODE REVIEW

**Comment by rytaft** [comment]
First commit is #51780

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51805#-:-MCsUd9G4kOnNYUdUrCL:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Comment by rytaft** [comment]
TFTR!

bors r+

**Pull request merged**
