### PR TITLE
config: databases descriptors don't initiate splits

### PR DESCRIPTION
**Pull request by ridwanmsharif**
Adds a hook to the sqlbase package to see if a descriptor
ID is referring to a Database, in which case, it is no longer
considered for a split

Confirm if it makes sense to not consider view descriptors 
for splitting too.
cc @benesch 

Fixes: #30923 

Release note: None

### CODE REVIEW

**Review by benesch — COMMENTED** [review]
Neat! This is a lot smaller than I expected. See the note below about caching IsDatabaseOrView, though.

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30981#-:-LO-mW846XVrEBGAwo3q:b-6dm8tb)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/config/system.go, line 34 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30981#-LO-jrCV4fqYeDQuGY8P:-LO-jrCWCmQRZdrBy1Kw:b-id0ses) ([raw file](https://github.com/cockroachdb/cockroach/blob/525de2992ec384eeebc2e01bb612611c4ee92ea4/pkg/config/system.go#L34)):*
> ```Go
> 
> type isDatabaseOrView func(
> 	objectID uint32, cfg *SystemConfig) bool
> ```

Just inline this. It's only used in one place.
___
*[pkg/config/system.go, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30981#-LO-jyYa5BJHjB6elWVD:-LO-jyYa5BJHjB6elWVE:b-japqsr) ([raw file](https://github.com/cockroachdb/cockroach/blob/525de2992ec384eeebc2e01bb612611c4ee92ea4/pkg/config/system.go#L46)):*
> ```Go
> 	testingLargestIDHook func(uint32) uint32
> 
> 	IsDatabaseOrView isDatabaseOrView
> ```

`IsDatabaseOrViewHook`
___
*[pkg/config/system.go, line 334 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30981#-LO-jloFBxrLs0ru5gUd:-LO-jloFBxrLs0ru5gUe:b3kre) ([raw file](https://github.com/cockroachdb/cockroach/blob/525de2992ec384eeebc2e01bb612611c4ee92ea4/pkg/config/system.go#L334)):*
> ```Go
> 	// findSplitKey returns the first possible split key between the given range
> 	// of IDs.
> 	// This is a table descriptor. Look up its parent database zone config.
> ```

?
___
*[pkg/config/system.go, line 340 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30981#-LO-mIdh5wlJHqsxa6B7:-LO-mIdh5wlJHqsxa6B8:bubn3t2) ([raw file](https://github.com/cockroachdb/cockroach/blob/525de2992ec384eeebc2e01bb612611c4ee92ea4/pkg/config/system.go#L340)):*
> ```Go
> 			if IsDatabaseOrView(id, s) {
> 				continue
> 			}
> ```

`ComputeSplitKey` is called constantly. Unmarshalling a protobuf, like IsDatabaseOrView does, on every call is going to show up in allocation profiles. We need to build a cache here, like the zone config cache, that remembers the result of IsDatabaseOrView for a given sysCfg and ID.
___
*[pkg/sql/sqlbase/system.go, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30981#-LO-lzTr7T-R5poEvhHE:-LO-lzTr7T-R5poEvhHF:b-a1y22u) ([raw file](https://github.com/cockroachdb/cockroach/blob/525de2992ec384eeebc2e01bb612611c4ee92ea4/pkg/sql/sqlbase/system.go#L49)):*
> ```Go
> 	}
> 	return false
> }
> ```

Ugh, this couples the `config` package even more tightly to `sqlbase`. I'm not seeing a better approach, though. @petermattis do you have any ideas for dealing with this? 
___
*[pkg/sql/tests/split_test.go, line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30981#-LO-lIVu6bdcVyRpz-8e:-LO-lIVu6bdcVyRpz-8f:b-xssh6c) ([raw file](https://github.com/cockroachdb/cockroach/blob/525de2992ec384eeebc2e01bb612611c4ee92ea4/pkg/sql/tests/split_test.go#L132)):*
> ```Go
> 	// Verify the actual splits.
> 	// TODO(ridwanmsharif): Check if the mismatch is okay? Seems a little weird.
> 	splits = []roachpb.RKey{keys.MakeTablePrefix(objectID + 3), roachpb.RKeyMax}
> ```

This seems extraordinarily weird. Let's track down why this is happening. The first thing I'd do is print out the ID of the table that gets created alongside all of the splits reported by `getRangeKeys`.

**Review by benesch — COMMENTED** [review]
Also, you misspelled "descriptors" in the commit message/PR title.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30981#-:-LO-mdNJ6OMPcN2GSF58:bcoyxge)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30981)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/config/system.go, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30981#-LO-l1Bt19G9k2s_R845:-LO-l1Bt19G9k2s_R846:b-ihrunm) ([raw file](https://github.com/cockroachdb/cockroach/blob/525de2992ec384eeebc2e01bb612611c4ee92ea4/pkg/config/system.go#L46)):*
> ```Go
> 	testingLargestIDHook func(uint32) uint32
> 
> 	IsDatabaseOrView isDatabaseOrView
> ```

Rather than naming this in a way that is specific to databases or views, I'd go with something like `SplitAtIDHook`. 
___
*[pkg/config/system.go, line 340 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30981#-LO-mIdh5wlJHqsxa6B7:-LO-vWbO47HYY3_YWktt:bnpltlv) ([raw file](https://github.com/cockroachdb/cockroach/blob/525de2992ec384eeebc2e01bb612611c4ee92ea4/pkg/config/system.go#L340)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

`ComputeSplitKey` is called constantly. Unmarshalling a protobuf, like IsDatabaseOrView does, on every call is going to show up in allocation profiles. We need to build a cache here, like the zone config cache, that remembers the result of IsDatabaseOrView for a given sysCfg and ID.
</blockquote></details>

In addition to what @benesch said, I think this check can be add to the `if startKey.Less(tableKey)` conditional which will reduce the overhead. Something like:

```
if startKey.Less(tableKey) && !IsDatabaseOrView(id, s) {
 ...
}
```

We'd still fall through to retrieving the zone for the database or view, but that's ok. Or perhaps the cache suggestion is better.
___
*[pkg/sql/sqlbase/system.go, line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30981#-LO-lzTr7T-R5poEvhHE:-LO-wBapAF4X6Z_ULtVq:b-z6mdps) ([raw file](https://github.com/cockroachdb/cockroach/blob/525de2992ec384eeebc2e01bb612611c4ee92ea4/pkg/sql/sqlbase/system.go#L49)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Ugh, this couples the `config` package even more tightly to `sqlbase`. I'm not seeing a better approach, though. @petermattis do you have any ideas for dealing with this? 
</blockquote></details>

No better thoughts from me.

**Review by benesch — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30981)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/config/system.go, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30981#-LO-l1Bt19G9k2s_R845:-LO-wtp22PfvPn1MH6z-:b-v693yz) ([raw file](https://github.com/cockroachdb/cockroach/blob/525de2992ec384eeebc2e01bb612611c4ee92ea4/pkg/config/system.go#L46)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Rather than naming this in a way that is specific to databases or views, I'd go with something like `SplitAtIDHook`. 
</blockquote></details>

Peter's suggestion is better than mine.

**Review by benesch — APPROVED** [review]
:lgtm_strong: as soon as you get that test fixed up. Nice work!

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30981#-:-LO5F15o1ucM6J00szOt:bjl8skq)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/tests/split_test.go, line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30981#-LO-lIVu6bdcVyRpz-8e:-LO5EsSoD1BUAVjMfwC0:b-yf2xxw) ([raw file](https://github.com/cockroachdb/cockroach/blob/525de2992ec384eeebc2e01bb612611c4ee92ea4/pkg/sql/tests/split_test.go#L132)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

This seems extraordinarily weird. Let's track down why this is happening. The first thing I'd do is print out the ID of the table that gets created alongside all of the splits reported by `getRangeKeys`.
</blockquote></details>

@ridwansharif tracked this down as a bug in the test. It _should_ have been `objectID + 3` before his change, ever since the defaultdb and postgres databases were created by default.

**Review by petermattis — APPROVED** [review]
:lgtm:

Nice quick work on this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30981#-:-LO5iATG7wXADmWkQfLi:b-qiac07)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
