### PR TITLE
opt: use dynamic construct for aggs

### PR DESCRIPTION
**Pull request by justinj**
Not sure if there's a nicer way to construct the DynamicOperands.

Address post-merge comment from @RaduBerinde to remove a big map.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28698)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/optbuilder/groupby.go, line 247 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28698#-LK26yXy5yDMVmwzqufy:-LK26yXy5yDMVmwzqufz:b-vhxgl3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d7bbf462f508a96f72ddce0b6afcbceaab03cd2/pkg/sql/opt/optbuilder/groupby.go#L247)):*
> ```Go
> 		operands := memo.DynamicOperands{}
> 		for i, a := range argList {
> 			operands[i] = memo.DynamicID(a)
> ```

Hm, operands has length 0, isn't this an index out of bounds?

**Review by justinj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28698)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/opt/optbuilder/groupby.go, line 247 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28698#-LK26yXy5yDMVmwzqufy:-LK299TPEKS9k6t4YHqn:bfyq1xr) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d7bbf462f508a96f72ddce0b6afcbceaab03cd2/pkg/sql/opt/optbuilder/groupby.go#L247)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Hm, operands has length 0, isn't this an index out of bounds?
</blockquote></details>

`DynamicOperands` has a fixed size of `opt.MaxOperands`, so it actually has size 3, but I went back and realized we don't even need `argList` anymore, so I think it's a bit clearer now. I think it might also save an allocation now.

**Review by andy-kimball — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28698#-:-LK2NhIBCaiaE_aHfMWX:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/optbuilder/groupby.go, line 247 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28698#-LK26yXy5yDMVmwzqufy:-LK2NJcJEoSQa-Z1K2aV:b-ltzq7s) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d7bbf462f508a96f72ddce0b6afcbceaab03cd2/pkg/sql/opt/optbuilder/groupby.go#L247)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

`DynamicOperands` has a fixed size of `opt.MaxOperands`, so it actually has size 3, but I went back and realized we don't even need `argList` anymore, so I think it's a bit clearer now. I think it might also save an allocation now.
</blockquote></details>

Yes, it has a fixed size in order to avoid allocations (at cost of sometimes making it clunkier to use). It would require special-handling to take care of a `ListID` argument, but since aggregates never have those (and are unlikely to ever have in the future), the way you've got it should work fine.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28698#-:-LK2Ry1Z8X41c2tQgTLh:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/optbuilder/groupby.go, line 247 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28698#-LK26yXy5yDMVmwzqufy:-LK2Rvu_314NyRgguKCj:bo44f1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/8d7bbf462f508a96f72ddce0b6afcbceaab03cd2/pkg/sql/opt/optbuilder/groupby.go#L247)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Yes, it has a fixed size in order to avoid allocations (at cost of sometimes making it clunkier to use). It would require special-handling to take care of a `ListID` argument, but since aggregates never have those (and are unlikely to ever have in the future), the way you've got it should work fine.
</blockquote></details>

Ah, right, neat.

**Comment by justinj** [comment]
Thanks!

bors r+

**Pull request merged**
