### PR TITLE
roachtest: Improve feature coverage in cdc test

### PR DESCRIPTION
**Pull request by miretskiy**
changefeedccl: Remove unused channel buffer

Cleanup PR to remove channel buffer which was only
used in tests.

Add few knobs to improve feature coverage in various
CDC tests:
  * metamorphically use mux rangefeed
  * metamorphically use schema_locked on tpcc workload

Epic: None

Release note: None

### CODE REVIEW

**Review by jayshrivastava — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109556)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/cdc.go` line 262 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109556#-NcxKu9V1l2w7t8284cR:-NcxKu9V1l2w7t8284cS:bgnniu9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d18cf108ff7f76e2142cec08038e976f57e17170/pkg/cmd/roachtest/tests/cdc.go#L262)):*
> ```Go
> 	conns          int
> 	noWait         bool
> 	lockSchema     featureFlag // default metamorphically locked.
> ```

This is a bit awkward. 
1. I think it's odd to have featureFlag apply to both creating changefeeds and the tpcc workload. Scattering these feature flags and having the implementation of each one in different places might get messy.
2. What if we add a feature flag which we don't want to default to metamorphic?
3. Who is responsible for logging the metamorphic values before the test starts?

I think we can lock the schema in the changefeed creator and lock the schema before creating the changefeed. We can make the changefeed creator responsible for logging the feature flags when it is initialized and implementing them. And we can add a constructor for a feature flags set struct to apply appropriate defaults. 
___
*[`pkg/cmd/roachtest/tests/cdc.go` line 2370 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109556#-NcxIIpu1-Q48zxJIf5H:-NcxIIpu1-Q48zxJIf5I:bp53mh1) ([raw file](https://github.com/cockroachdb/cockroach/blob/d18cf108ff7f76e2142cec08038e976f57e17170/pkg/cmd/roachtest/tests/cdc.go#L2370)):*
> ```Go
> 
> func newChangefeedCreator(
> 	db *gosql.DB, targets, sinkURL string, useMux featureFlag,
> ```

Does it make sense to create something like this and use it as a parameter here?

```
type cdcRoachtestFeatureFlagSet struct {
    MuxRangefeed: featureFlag,
}

func() makeDefaultFeatureFlags () cdcRoachtestFeatureFlagSet {
    return cdcRoachtestFeatureFlagSet{MuxRangefeed: metamorphic},
}
```
This makes it easier to add more feature flags (ex. resolved timestamps, select * from table).

If someone wants to use the default feature flags and override one, they can. Allocating a new struct is important in this case (as opposed to `var defaultFlags cdcRoachtestFeatureFlagSet`) because we would be mutating. We've seen some bugs happen before due to shared state between tests. 
___
*[`pkg/cmd/roachtest/tests/cdc.go` line 2372 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109556#-NcxJcHIATC0vuOh0Mw7:-NcxJcHIATC0vuOh0Mw8:b-jbetcn) ([raw file](https://github.com/cockroachdb/cockroach/blob/d18cf108ff7f76e2142cec08038e976f57e17170/pkg/cmd/roachtest/tests/cdc.go#L2372)):*
> ```Go
> 	db *gosql.DB, targets, sinkURL string, useMux featureFlag,
> ) *changefeedCreator {
> 	return &changefeedCreator{
> ```

I think we should log the feature flags here too so we can debug things later.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109556)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/cdc.go` line 262 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109556#-NcxKu9V1l2w7t8284cR:-Ncxsdnr3oxHteCHus8e:b-ycy110) ([raw file](https://github.com/cockroachdb/cockroach/blob/d18cf108ff7f76e2142cec08038e976f57e17170/pkg/cmd/roachtest/tests/cdc.go#L262)):*
Perhaps it's a bit awkward.  Not sure if alternatives are better.

> I think it's odd to have featureFlag apply to both creating changefeeds and the tpcc workload. Scattering these feature flags and having the implementation of each one in different places might get messy.

I somewhat agree.  However, just being a bit pragmatic here.  The problem is that if I defer application of this feature flag until after changefeed creation, I could get mixed performance; not only that, changing schema for tables that are under constant load tends to take time -- as much as 5 minutes.  Setting this flag when creating tpcc makes sense as it's pragmatic.  I figured if we want to support more places for this, we can add them as needed.

> What if we add a feature flag which we don't want to default to metamorphic?

That part is simple.. I had to delete other constants, such as featureMuxEnabled, featureMuxDisabled because they were not used.  But basically, if you don't want to default to metamorphic, you'd add "disable" constant and use that as default.

3. Who is responsible for logging the metamorphic values before the test starts?

That's a good point; I cleaned up the uses of this to make sure I log messages directly when using muxrf.

>I think we can lock the schema in the changefeed creator and lock the schema before creating the changefeed. We can make the changefeed creator responsible for logging the feature flags when it is initialized and implementing them. And we can add a constructor for a feature flags set struct to apply appropriate defaults.

See above -- doing schema locked during creation might be too late and take (literally) 40 minutes -- up to 5 minutes per tpcc table. I'd rather do it on as needed basis.
___
*[`pkg/cmd/roachtest/tests/cdc.go` line 2370 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109556#-NcxIIpu1-Q48zxJIf5H:-Ncy3yNfER3zGzqVvTcN:b-mfresw) ([raw file](https://github.com/cockroachdb/cockroach/blob/d18cf108ff7f76e2142cec08038e976f57e17170/pkg/cmd/roachtest/tests/cdc.go#L2370)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

Does it make sense to create something like this and use it as a parameter here?

```
type cdcRoachtestFeatureFlagSet struct {
    MuxRangefeed: featureFlag,
}

func() makeDefaultFeatureFlags () cdcRoachtestFeatureFlagSet {
    return cdcRoachtestFeatureFlagSet{MuxRangefeed: metamorphic},
}
```
This makes it easier to add more feature flags (ex. resolved timestamps, select * from table).

If someone wants to use the default feature flags and override one, they can. Allocating a new struct is important in this case (as opposed to `var defaultFlags cdcRoachtestFeatureFlagSet`) because we would be mutating. We've seen some bugs happen before due to shared state between tests.
</blockquote></details>

I like this idea.  Added.
___
*[`pkg/cmd/roachtest/tests/cdc.go` line 2372 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/109556#-NcxJcHIATC0vuOh0Mw7:-NcxwsNg4YSb99z-F6L9:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/d18cf108ff7f76e2142cec08038e976f57e17170/pkg/cmd/roachtest/tests/cdc.go#L2372)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

I think we should log the feature flags here too so we can debug things later.
</blockquote></details>

done.

**Review by jayshrivastava — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109556)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/cdc.go` line 416 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109556#-Nd0jfsZ9JhLyNVIMQFf:-Nd0jfsZ9JhLyNVIMQFg:bxs3jvi) ([raw file](https://github.com/cockroachdb/cockroach/blob/4833f4e775ae982d4ab8295bc01bca3699d33ba3/pkg/cmd/roachtest/tests/cdc.go#L416)):*
> ```Go
> }
> 
> // cdcFeatureFlags describes varouis cdc feature flags.
> ```

nit: typo
___
*[`pkg/cmd/roachtest/tests/cdc.go` line 2418 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/109556#-Nd0jpUt9cNuR9HWjpP4:-Nd0jpUt9cNuR9HWjpP5:b-j0808p) ([raw file](https://github.com/cockroachdb/cockroach/blob/4833f4e775ae982d4ab8295bc01bca3699d33ba3/pkg/cmd/roachtest/tests/cdc.go#L2418)):*
> ```Go
> 	}
> 
> 	cfc.logger.Printf("Using mux_rangefeed to %t", cfc.useMux)
> ```

nit: "setting changefeed.mux_rangefeed.enabled = %t"

**Comment by miretskiy** [comment]
> nit: typo

Done

> nit: "setting changefeed.mux_rangefeed.enabled = %t"

Done.

**Pull request merged**
