### PR TITLE
workload/yscb: use UPDATEs in workloads A and B

### LINKED ISSUE #24287: workload: YCSB does not behave according to spec
Our YCSB workload only does reads and inserts, but the [spec](https://b9f6702a-a-62cb3a1a-s-sites.googlegroups.com/site/brianfrankcooper/home/publications/ycsb.pdf?attachauth=ANoY7cqzsUsiCta6aSYLKRdC5geHyLNNgYw5e80xg_-kDrAyhTECOsQ4y2JyT2mAwmtx4tTx8pkiI7yOpxuv1AvUloH7zwv73Uct_Vdl3oaIhE0yhroeT8KWHxqNxa4pQr5y3uvC9TSKA05ZiKo7cM3dQy4D1h66-Coz5H0zcvCpmEshqY2yCN5KbINACgMDaE-N674PmpKOug-hbHpVIrMzwRfmEmjwF2LunZFCnWjbZJRVXkxYXdM%3D&attredirects=0) says that workloads A and B should be a mix of reads and updates. (This is also how the [official benchmark](https://github.com/brianfrankcooper/YCSB) behaves.)

screen shot 2018-03-28 at 11 04 08 am

This is a big difference, since the Zipfian distribution causes significant write contention on certain rows. ~~(I also question whether `ZipfGenerator` is working properly, since we should be seeing tons of primary key conflicts on the inserts.)~~

### PR DESCRIPTION
**Pull request by solongordon**
Our YCSB workload was incorrectly using INSERTs rather than UPDATEs in
the A and B workloads.

Also made a few related tweaks:
- Changed field names to be 0-indexed to simplify some logic and better
  match the official YCSB tool.
- Fixed broken initiation in JSON mode.

Fixes #24287

Release note: None

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/workload/ycsb/ycsb.go, line 45 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24335#-L96Fxhd9k1jJnZjhItm:-L96Fxhd9k1jJnZjhItn:b4vac3t) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dde2dd042aaa9d8cf6576f3bda91b22baaf444e/pkg/workload/ycsb/ycsb.go#L45)):*
> ```Go
> 	usertableSchemaRelational = `(
> 		ycsb_key BIGINT PRIMARY KEY NOT NULL,
>     FIELD0 TEXT,
> ```

Spacing seems off on this.

---

*[pkg/workload/ycsb/ycsb.go, line 72 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24335#-L96FzTu6c_E19bGIEBv:-L96FzTu6c_E19bGIEBw:b-238whi) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dde2dd042aaa9d8cf6576f3bda91b22baaf444e/pkg/workload/ycsb/ycsb.go#L72)):*
> ```Go
> 
> 	workload                                  string
> 	readFreq, writeFreq, updateFreq, scanFreq float32
> ```

Change "write" to "insert" everywhere where it's applicable. "write" generally implies inserts or updates, but that's no longer what we mean.

---

*[pkg/workload/ycsb/ycsb.go, line 302 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24335#-L96GTO6CO32A3oI4N69:-L96GTO6CO32A3oI4N6A:b-fawa1q) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dde2dd042aaa9d8cf6576f3bda91b22baaf444e/pkg/workload/ycsb/ycsb.go#L302)):*
> ```Go
> const (
> 	updateOp operation = `update`
> 	writeOp  operation = `write`
> ```

For example, this should be `insertOp` now.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24335)*

**Comment by solongordon** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/workload/ycsb/ycsb.go, line 45 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24335#-L96Fxhd9k1jJnZjhItm:-L96REfp3R3du95n1iRg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dde2dd042aaa9d8cf6576f3bda91b22baaf444e/pkg/workload/ycsb/ycsb.go#L45)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Spacing seems off on this.
</blockquote></details>

Done.

---

*[pkg/workload/ycsb/ycsb.go, line 72 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24335#-L96FzTu6c_E19bGIEBv:-L96RYLK-W5R1il58HCw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dde2dd042aaa9d8cf6576f3bda91b22baaf444e/pkg/workload/ycsb/ycsb.go#L72)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Change "write" to "insert" everywhere where it's applicable. "write" generally implies inserts or updates, but that's no longer what we mean.
</blockquote></details>

Done.

---

*[pkg/workload/ycsb/ycsb.go, line 302 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24335#-L96GTO6CO32A3oI4N69:-L96RYe8EP0qigLrxk2m:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9dde2dd042aaa9d8cf6576f3bda91b22baaf444e/pkg/workload/ycsb/ycsb.go#L302)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

For example, this should be `insertOp` now.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24335)*

**Comment by nvanbenschoten** [comment]
:lgtm: but @arjunravinarayan should take a quick look as well.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24335#-:-L96Z8wIC8tLF78ccUHy:b73zf93)*

**Comment by arjunravinarayan** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24335#-:-L96v1Pj9iTjVp2wyWDD:bnfp4nl)*

**Pull request merged**
