### PR TITLE
sql/sem/builtins: make EXTRACT return float

### LINKED ISSUE #41548: sql: support more time spans for EXTRACT
Currently we support these "fields": `year, quarter, month, week, dayofweek, dayofyear, hour, minute, second, millisecond, microsecond, epoch`.

Postgres supports [more](https://www.postgresql.org/docs/8.3/functions-datetime.html). Some of the missing ones are `century, decade, isodow, isoyear, millenium`. The relevant code lives in `pkg/sql/sem/builtins/builtins.go`.

As a bonus, Postgres returns "double precision" type for EXTRACT, but Cockroach returns "int". It could be fixed as well (cc @jordanlewis in case I'm missing why we do it that way).

### PR DESCRIPTION
**Pull request by rogaps**
Previously, EXTRACT returned values of type int. In PostgreSQL, EXTRACT
returns values of type double precision. This patch makes EXTRACT return
float and include fractional parts for 'second', 'millisecond', 'julian',
and 'epoch' elements.

Resolves: #41548

Release note (sql change): EXTRACT now returns values of type float and
includes fractional parts in the values for element 'second',
'millisecond', 'julian', and 'epoch'. This improves compatibility with
PostgreSQL's EXTRACT which returns values of type double precision.

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
Thanks! I left a few nits, but it :lgtm:

Also, could you please modify the commit message (and the PR description) so that:
1. make the release note more explicit - describe what the previous behavior was, what the new behavior will be, and why we're doing this change. There is a good description of what should be in the release notes in githooks (when you're making/amending the commit message, you should be able to see all of those as the comments)
2. replace `Issue` with `Fixes` or `Resolves` so that once the PR is merged, the relevant issue is closed (since it will have been fully addressed).

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42131#-:-LssXrqi-_1j7rtrD7uF:btb620x)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rogaps)

___
*[pkg/sql/sem/builtins/builtins.go, line 4489 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42131#-LssWBTXE8clNzkMXnSK:-LssWBTXE8clNzkMXnSL:b-8zj295) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f016b018c72b9e5185b63abab9dc716f0f37e70/pkg/sql/sem/builtins/builtins.go#L4489)):*
> ```Go
> 		return tree.NewDFloat(tree.DFloat(float64(t.Second()) + float64(t.Microsecond())/(1000*1000))), nil
> 	case "millisecond", "milliseconds":
> 		return tree.NewDFloat(tree.DFloat(float64(t.Second()*1000) + float64(t.Microsecond())/microsPerMilli)), nil
> ```

[nit]: it seems weird that we have `microsPerMilli` which equals to 1000, but we also use the value `1000` directly. It might be nicer to also define `millisPerSec` so that we can replace all explicit `1000`s with either of the defined constants.
___
*[pkg/sql/sem/builtins/builtins.go, line 4580 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42131#-LssXW5HE6FPBZt1gTaJ:-LssXW5HE6FPBZt1gTaK:bwzfjoi) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f016b018c72b9e5185b63abab9dc716f0f37e70/pkg/sql/sem/builtins/builtins.go#L4580)):*
> ```Go
> 		julianDay := float64(dateToJulianDay(fromTime.Year(), int(fromTime.Month()), fromTime.Day())) +
> 			(float64(fromTime.Hour()*3600+fromTime.Minute()*60+fromTime.Second())+
> 				float64(fromTime.Nanosecond())/float64(time.Second))/86400
> ```

[nit]: I'd definitely extract `86400` into a constant, possibly `3600` and `60` as well.
___
*[pkg/sql/sem/builtins/builtins.go, line 4594 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42131#-LssXgzBBiOOMh6SV3Un:-LssXgzBBiOOMh6SV3Uo:brs41sj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f016b018c72b9e5185b63abab9dc716f0f37e70/pkg/sql/sem/builtins/builtins.go#L4594)):*
> ```Go
> 	case "millisecond", "milliseconds":
> 		// This a PG extension not supported in MySQL.
> 		return tree.NewDFloat(tree.DFloat(float64(fromTime.Second()*1000) + float64(fromTime.Nanosecond())/float64(time.Millisecond))), nil
> ```

ditto for usage of constant variables

**Comment by rogaps** [comment]
Hi, @yuzefovich. I have addressed your change requests and updated the commit message. PTAL.

**Review by yuzefovich — COMMENTED** [review]
Thanks @rogaps!

bors r=yuzefovich

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42131#-:-LtVaCBq3tzvALxjy_-h:b-i6j6z8)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rogaps)

**Comment by yuzefovich** [comment]
An agent ran out of space.

bors r=yuzefovich

**Pull request merged**
