### PR TITLE
kvserver/rangefeed: replace StreamMuxer with UnbufferedSender

### PR DESCRIPTION
**Pull request by wenyihu6**
**kvserver/rangefeed: rename stream with muxstream in node.MuxRangefeed**

This patch renames stream with muxstream in node.MuxRangefeed to avoid
confusion.

Release note: none
Epic: none

----

**kvserver/rangefeed: replace StreamMuxer with UnbufferedSender**

Previously, StreamMuxer was wrapped inside every rangefeed.PerRangeEventSink,
where it was responsible for forwarding events to the underlying gRPC stream.
However, with the introduction of a buffered stream sender in future commits,
the responsibilities of StreamMuxer became unclear, as it needed to be able to
forward events for both unbuffered and buffered senders. To simplify and clarify
this functionality, this patch removes StreamMuxer and introduces a new struct,
UnbufferedSender, which takes the responsibilities previously handled by
StreamMuxer. Note that UnbufferedSender should have the exact same
functionalities as current StreamMuxer.

Part of: #129813
Release note: none

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 5 of 5 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129637)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @wenyihu6)

___
*[`-- commits` line 36 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129637#-O5EdfdT94lJa45Hgf7h):*
Are tests broken between commits 2 and 3? If so, we should squash these two commits together. Even with multi-commit PRs, it's important for CI to be green at each intermediate commit. If not, we break `git bisect`.
___
*[`pkg/kv/kvserver/rangefeed/unbuffered_sender.go` line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129637#-O5EalPM7eolE1TdlAMi:-O5EalPM7eolE1TdlAMj:b-8nmh85) ([raw file](https://github.com/cockroachdb/cockroach/blob/2140ebe27f76b362af4483eae7cabc3e3fb8f633/pkg/kv/kvserver/rangefeed/unbuffered_sender.go#L39)):*
> ```Go
> }
> 
> //		                                                  				                            ┌───────────────────────────┐
> ```

Did this diagram format correctly? It looks off to me.
___
*[`pkg/kv/kvserver/rangefeed/unbuffered_sender.go` line 131 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129637#-O5EcAKl0IkF4FmiY_HO:-O5EcAKl0IkF4FmiY_HP:b-hgx3gn) ([raw file](https://github.com/cockroachdb/cockroach/blob/2140ebe27f76b362af4483eae7cabc3e3fb8f633/pkg/kv/kvserver/rangefeed/unbuffered_sender.go#L131)):*
> Note that streamReg.Send is blocking

Is this comment stale? What is `streamReg.Send`?
___
*[`pkg/kv/kvserver/rangefeed/unbuffered_sender.go` line 132 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129637#-O5Ebzr-5qIm5cn2ZIPr:-O5Ebzr-5qIm5cn2ZIPs:bdiagin) ([raw file](https://github.com/cockroachdb/cockroach/blob/2140ebe27f76b362af4483eae7cabc3e3fb8f633/pkg/kv/kvserver/rangefeed/unbuffered_sender.go#L132)):*
> ```Go
> 	// reg is used to send events to the underlying grpc server stream. Note
> 	// that streamReg.Send is blocking.
> 	reg struct {
> ```

This would be a candidate to extract into a small helper struct with relevant methods so that it can be shared with a a ``
___
*[`pkg/kv/kvserver/rangefeed/unbuffered_sender.go` line 171 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129637#-O5EbFWzB6GvZyUk_4cE:-O5EbFWzB6GvZyUk_4cF:b6snrxn) ([raw file](https://github.com/cockroachdb/cockroach/blob/2140ebe27f76b362af4483eae7cabc3e3fb8f633/pkg/kv/kvserver/rangefeed/unbuffered_sender.go#L171)):*
> ```Go
> //
> // Note that this function can be called by the processor worker while holding
> // raftMu, so it is important that this function doesn't block IO. Caller needs
> ```

"block on IO"
___
*[`pkg/kv/kvserver/rangefeed/unbuffered_sender.go` line 174 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129637#-O5EbX-79j0uBhcbbKIm:-O5EbX-79j0uBhcbbKIn:benzam) ([raw file](https://github.com/cockroachdb/cockroach/blob/2140ebe27f76b362af4483eae7cabc3e3fb8f633/pkg/kv/kvserver/rangefeed/unbuffered_sender.go#L174)):*
> ```Go
> // to make sure this is called only with non-nil error events. Important to be
> // thread-safe.
> func (ubs *UnbufferedSender) SendErrorWithoutBlocking(ev *kvpb.MuxRangeFeedEvent) {
> ```

Did you consider calling this `SendBufferedError` to contrast it with `SendUnbuffered` and to draw a parallel with the future `SendBuffered` method on the `BufferedSender`?
___
*[`pkg/kv/kvserver/rangefeed/unbuffered_sender.go` line 193 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129637#-O5Ebn6h1Az3NMNR_DzS:-O5Ebn6h1Az3NMNR_DzT:b-tmn97a) ([raw file](https://github.com/cockroachdb/cockroach/blob/2140ebe27f76b362af4483eae7cabc3e3fb8f633/pkg/kv/kvserver/rangefeed/unbuffered_sender.go#L193)):*
> ```Go
> // play safe.) Important to be thread-safe.
> func (ubs *UnbufferedSender) SendUnbuffered(event *kvpb.MuxRangeFeedEvent) error {
> 	return ubs.sender.Send(event)
> ```

Should we check here that `ev.Error == nil`? To force all error handling through the other method?

**Review by wenyihu6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129637)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`-- commits` line 36 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/129637#-O5EdfdT94lJa45Hgf7h):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Are tests broken between commits 2 and 3? If so, we should squash these two commits together. Even with multi-commit PRs, it's important for CI to be green at each intermediate commit. If not, we break `git bisect`.
</blockquote></details>

I see, squashed.
___
*[`pkg/kv/kvserver/rangefeed/unbuffered_sender.go` line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129637#-O5EalPM7eolE1TdlAMi:-O5EvnP6BaqhVPCT98Ln:b-piy8xq) ([raw file](https://github.com/cockroachdb/cockroach/blob/2140ebe27f76b362af4483eae7cabc3e3fb8f633/pkg/kv/kvserver/rangefeed/unbuffered_sender.go#L39)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Did this diagram format correctly? It looks off to me.
</blockquote></details>

I think the diagram was too large to include both BufferedSender and UnbufferedSender. I changed it to include UnbufferedSend only. I will draw another one for BufferedSender in future commits. 
___
*[`pkg/kv/kvserver/rangefeed/unbuffered_sender.go` line 131 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129637#-O5EcAKl0IkF4FmiY_HO:-O5Ew1bm2hUTefk3RfQ5:b-u6a9d9) ([raw file](https://github.com/cockroachdb/cockroach/blob/2140ebe27f76b362af4483eae7cabc3e3fb8f633/pkg/kv/kvserver/rangefeed/unbuffered_sender.go#L131)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> Note that streamReg.Send is blocking

Is this comment stale? What is `streamReg.Send`?
</blockquote></details>

Ahh, oops. Removed.
___
*[`pkg/kv/kvserver/rangefeed/unbuffered_sender.go` line 132 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129637#-O5Ebzr-5qIm5cn2ZIPr:-O5Ew5Xc4B8vRFQh5KWw:b59iyfs) ([raw file](https://github.com/cockroachdb/cockroach/blob/2140ebe27f76b362af4483eae7cabc3e3fb8f633/pkg/kv/kvserver/rangefeed/unbuffered_sender.go#L132)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This would be a candidate to extract into a small helper struct with relevant methods so that it can be shared with a a ``
</blockquote></details>

Hm, I ended up just removing this small struct. Wdyt? Adding a separate helper struct here feels a bit like embedding StreamMuxer again. Not sure if you've seen this - I started a discussion (https://cockroachlabs.slack.com/archives/C05JB0QURND/p1724683756580649?thread\_ts=1724072786.336579&cid=C05JB0QURND) about whether we should embed StreamMuxer in Buffered/Unbuffered Sender. I'm leaning towards no for now.
___
*[`pkg/kv/kvserver/rangefeed/unbuffered_sender.go` line 171 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129637#-O5EbFWzB6GvZyUk_4cE:-O5EwpneAsdSlIjHIosP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2140ebe27f76b362af4483eae7cabc3e3fb8f633/pkg/kv/kvserver/rangefeed/unbuffered_sender.go#L171)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"block on IO"
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/rangefeed/unbuffered_sender.go` line 174 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129637#-O5EbX-79j0uBhcbbKIm:-O5EwqLqD9ofYEnst3_U:br24ekt) ([raw file](https://github.com/cockroachdb/cockroach/blob/2140ebe27f76b362af4483eae7cabc3e3fb8f633/pkg/kv/kvserver/rangefeed/unbuffered_sender.go#L174)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Did you consider calling this `SendBufferedError` to contrast it with `SendUnbuffered` and to draw a parallel with the future `SendBuffered` method on the `BufferedSender`?
</blockquote></details>

Renamed to SendBufferedError. 
___
*[`pkg/kv/kvserver/rangefeed/unbuffered_sender.go` line 193 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129637#-O5Ebn6h1Az3NMNR_DzS:-O5EwtB9ErWef1vJNyzD:b-o387qs) ([raw file](https://github.com/cockroachdb/cockroach/blob/2140ebe27f76b362af4483eae7cabc3e3fb8f633/pkg/kv/kvserver/rangefeed/unbuffered_sender.go#L193)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we check here that `ev.Error == nil`? To force all error handling through the other method?
</blockquote></details>

I made it to log.Fatal if that is the case.

**Review by nvb — COMMENTED** [review]
> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129637)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @wenyihu6)

___
*[`pkg/kv/kvserver/rangefeed/unbuffered_sender.go` line 132 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/129637#-O5Ebzr-5qIm5cn2ZIPr:-O5F3rwD5bmUwFsI5Z8E:b-ss07in) ([raw file](https://github.com/cockroachdb/cockroach/blob/2140ebe27f76b362af4483eae7cabc3e3fb8f633/pkg/kv/kvserver/rangefeed/unbuffered_sender.go#L132)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

Hm, I ended up just removing this small struct. Wdyt? Adding a separate helper struct here feels a bit like embedding StreamMuxer again. Not sure if you've seen this - I started a discussion (https://cockroachlabs.slack.com/archives/C05JB0QURND/p1724683756580649?thread\_ts=1724072786.336579&cid=C05JB0QURND) about whether we should embed StreamMuxer in Buffered/Unbuffered Sender. I'm leaning towards no for now.
</blockquote></details>

I agree that for now we can just have some duplication. If it gets too bad, we'll end up wanting to extract the logic anyway.
___
*[`pkg/kv/kvserver/rangefeed/unbuffered_sender.go` line 152 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/129637#-O5F40no561Y0hLA32e2:-O5F40no561Y0hLA32e3:ba4098y) ([raw file](https://github.com/cockroachdb/cockroach/blob/99bc7654cbcec1bef9f4c7048c81d53d21e58878/pkg/kv/kvserver/rangefeed/unbuffered_sender.go#L152)):*
> ```Go
> 		sender:         sender,
> 	}
> 	ubs.metrics = metrics
> ```

Can this just move into the struct construction above, now that it's not in an anonymous struct?
___
*[`pkg/kv/kvserver/rangefeed/unbuffered_sender.go` line 177 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/129637#-O5F4TTw3eUR38zRX9HZ:-O5F4TTw3eUR38zRX9H_:b-s4rbaz) ([raw file](https://github.com/cockroachdb/cockroach/blob/99bc7654cbcec1bef9f4c7048c81d53d21e58878/pkg/kv/kvserver/rangefeed/unbuffered_sender.go#L177)):*
> ```Go
> 	}
> 
> 	if cancel, ok := ubs.streams.LoadAndDelete(ev.StreamID); ok {
> ```

Did you consider having `SendBufferedError` unconditionally call `ubs.appendMuxError` and then having `run` handle the `LoadAndDelete` logic for each error event that it processes? That seems functionally equivalent and would make `UnbufferedSender` more similar to what `BufferedSender` will eventually look like, except that `BufferedSender` will push all events through the "buffer" whereas `UnbufferedSender` is only pushing errors through a buffer.

If we make that change then there's probably a world where we don't even need a separate "Unbuffered" and "Buffered" sender implementation, though I don't think we need to go that far.

**Review by wenyihu6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129637)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/rangefeed/unbuffered_sender.go` line 152 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/129637#-O5F40no561Y0hLA32e2:-O5F9CiMANdP_1Nu46hM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/99bc7654cbcec1bef9f4c7048c81d53d21e58878/pkg/kv/kvserver/rangefeed/unbuffered_sender.go#L152)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can this just move into the struct construction above, now that it's not in an anonymous struct?
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/rangefeed/unbuffered_sender.go` line 177 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/129637#-O5F4TTw3eUR38zRX9HZ:-O5F9Dpc5NKzLarO4sne:bpznbi4) ([raw file](https://github.com/cockroachdb/cockroach/blob/99bc7654cbcec1bef9f4c7048c81d53d21e58878/pkg/kv/kvserver/rangefeed/unbuffered_sender.go#L177)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Did you consider having `SendBufferedError` unconditionally call `ubs.appendMuxError` and then having `run` handle the `LoadAndDelete` logic for each error event that it processes? That seems functionally equivalent and would make `UnbufferedSender` more similar to what `BufferedSender` will eventually look like, except that `BufferedSender` will push all events through the "buffer" whereas `UnbufferedSender` is only pushing errors through a buffer.

If we make that change then there's probably a world where we don't even need a separate "Unbuffered" and "Buffered" sender implementation, though I don't think we need to go that far.
</blockquote></details>

Hm, we rely on `LoadAndDelete` to ensure metrics are decremented only once per stream disconnection. And metrics updates should happen right after stream context cancellation for UnbufferedSender since that is when the registration is removed from the processor. Delaying this to the separate goroutine could introduce timing inaccuracy in the metrics. Wdyt?

**Review by nvb — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129637)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @wenyihu6)

___
*[`pkg/kv/kvserver/rangefeed/unbuffered_sender.go` line 177 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/129637#-O5F4TTw3eUR38zRX9HZ:-O5FDwp02-oWNghKFTSV:b-6eeuxh) ([raw file](https://github.com/cockroachdb/cockroach/blob/99bc7654cbcec1bef9f4c7048c81d53d21e58878/pkg/kv/kvserver/rangefeed/unbuffered_sender.go#L177)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

Hm, we rely on `LoadAndDelete` to ensure metrics are decremented only once per stream disconnection. And metrics updates should happen right after stream context cancellation for UnbufferedSender since that is when the registration is removed from the processor. Delaying this to the separate goroutine could introduce timing inaccuracy in the metrics. Wdyt?
</blockquote></details>

We would still use `LoadAndDelete` to make sure the metric is only decremented once per stream disconnection, we would just call that in the `run` goroutine instead of here.

I don't understand the concern about timing inaccuracy. We would call the context cancellation from `run` as well, so we would still be updating the metrics shortly after removing the stream. Do you have an example of a situation which would be handled poorly by moving the disconnection logic?

**Comment by wenyihu6** [comment]
*[`pkg/kv/kvserver/rangefeed/unbuffered_sender.go` line 177 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/129637#-O5F4TTw3eUR38zRX9HZ:-O5FG62U20JIQ6mnFL8T:bq0mflj) ([raw file](https://github.com/cockroachdb/cockroach/blob/99bc7654cbcec1bef9f4c7048c81d53d21e58878/pkg/kv/kvserver/rangefeed/unbuffered_sender.go#L177)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We would still use `LoadAndDelete` to make sure the metric is only decremented once per stream disconnection, we would just call that in the `run` goroutine instead of here.

I don't understand the concern about timing inaccuracy. We would call the context cancellation from `run` as well, so we would still be updating the metrics shortly after removing the stream. Do you have an example of a situation which would be handled poorly by moving the disconnection logic?
</blockquote></details>

I think this is goes back to why I didn't want to embed `StreamMuxer` inside `UnbufferedSender`. If we do context cancellation and metrics updates in the goroutine, 

1. Context cancellation is delayed to the goroutine and more events are buffered in registration until this happens. We don't check for `r.disconnected` during `r.publish`. I'm not sure if this is a concern in practice, but I feel it may happen very late if stream is blocking and the goroutine is processing mux errors really slow. Do you see this as a problem irl?

2. Once the `UnbufferedSender` goroutine completes (node level shutdown), context cancellation happens at the node level. If metrics are only updated inside goroutine, they may remain uncleaned because the goroutine has shut down. We now rely on SendBufferedError still being able to do metrics updates and context cancellation after goroutine shuts down.

Technically, we could solve 1. by adding a context cancel function to `perRangeEventSink` and solve 2 by adding a disconnectAll method to UnbufferedSender to ensure that stream context and metrics are properly updated during node level shutdown which might be more similar to BufferedSender. BufferedSender has `diconnectAll` for rangefeed clean up callbacks. If we go with this approach, it would address my concerns about embedding StreamMuxer inside Buffered/Unbuffered Senders.

**Review by wenyihu6 — COMMENTED** [review]
> How are we planning to solve this problem with the `BufferedSender`?
 
We can do the same here as we did for UnbufferedSender (expect BufferedSender cancel context in response to SendError). And I changed r.publish to check for r.disconnected to prevent  since we plan to unregister (rangefeed clean up callback) registration from processor very late in the stage - only when the error events are popped from the queue and about to be sent to grpc stream. 

> Why can't it just exit on its own after sending that error to the stream?

We can solve this by adding the context cancel function to `perRangeEventSink`.  It sounds like we want to proceed with both solutions proposed above in https://github.com/cockroachdb/cockroach/pull/129637#issuecomment-2311001104. And they would address my concerns about embedding `StreamMuxer` inside Buffered/Unbuffered Senders as well. I will open a new patch to fix this as we are adding BufferedSender. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129637#-:-O5P-0ZQ9qH0tIrCJ9u1:b-oog6hy)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by wenyihu6 — COMMENTED** [review]
> How are we planning to solve this problem with the `BufferedSender`?
 
We can do the same as what we did for UnbufferedSender (expect BufferedSender cancel context in response to SendError). And I changed r.publish to check for r.disconnected to prevent  since we plan to unregister (rangefeed clean up callback) registration from processor very late in the stage - only when the error events are popped from the queue and about to be sent to grpc stream. 

> Why can't it just exit on its own after sending that error to the stream?

We can solve this by adding the context cancel function to `perRangeEventSink`.  It sounds like we want to proceed with both solutions proposed above in https://github.com/cockroachdb/cockroach/pull/129637#issuecomment-2311001104. And they would address my concerns about embedding `StreamMuxer` inside Buffered/Unbuffered Senders as well. I will open a new patch to fix this as we are adding BufferedSender. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129637#-:-O5P0N1z-uJEZg52TIs5:b-nb2mri)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Comment by wenyihu6** [comment]
Also, I think context cancellation isn’t as critical for BufferedSender as it is for UnbufferedSender because BufferedSender doesn’t have a long-running goroutine, and the current catch-up scans are not properly watching context cancellation anyways. It would mainly help in stopping the draining of the catch-up scan buffer in the separate goroutine. Is this correct? I didn't find anything else in the code path that relies on this context cancellation but not 100% sure.

**Review by nvb — APPROVED** [review]
LGTM. We can merge this PR and then continue to discuss next steps on the other PRs that you have queued up.

To be honest, I'm having some trouble understanding the details and implications of the plans we are discussing here. In general, (and I know this contradicts some of my previous suggestions) I think we should err on the side of not making broad refactors to the existing mechanisms while we're in the process of phasing them out. So for example, please feel free to disregard the comment about moving the context cancellation from `SendBufferedError` to the `run` goroutine. I think we now have a good enough plan for the new code (`BufferedSender`) to slot in next to this old code.

Separately, I'd gently encourage not making large code renames and especially not file renames in the same commits that also make meaningful changes to code. It makes the git diff inscrutable and requires a reviewer to manually put the two files side-by-side to understand the changes. It also makes it much easier for small changes to pass by unnoticed.

**Comment by wenyihu6** [comment]
Sounds good, thanks for the discussion! I will keep going with BufferedSender and leave the implementation of UnbufferedSender unchanged. 

> To be honest, I'm having some trouble understanding the details and implications of the plans we are discussing here.

Would it help if I create a draft pr for the final prototype first? Hope it will become clearer with the next two PRs as we integrate BufferedSender and unbuffered registrations. We can iterate on the design afterwards. 

> I'd gently encourage not making large code renames and especially not file renames in the same commits that also make meaningful changes to code

Appreciate the suggestions, I will keep these in mind for future commits.

**Comment by wenyihu6** [comment]
TFTR!

bors r=nvanbenschoten

**Pull request merged**
