### PR TITLE
Add a test for out-of-order put operations

### PR DESCRIPTION
**Pull request by kkaneda**
This is more like a question... Currently the test fails since `MVCCGet` returns `value1`, not `value2`. I'm wondering `mvccPutInternal` should always process a put operation even when its timestamp is older than that of `meta`.

### CODE REVIEW

**Comment by tschottdorf** [comment]
The current behaviour is correct. A transaction's write timestamps always moves forward in time, so anything that comes in from the past is invalid and must be an old request.
You could picture situations in which you want to write into the past (after all, you can place whole transactions in the past, for instance you could sneak in a write prior to another one assuming there wasn't a read that would have their outcome changed by that) but we haven't had a use case for that.

**Comment by kkaneda** [comment]
Ah, I see. Thanks for the explanation! Updated the PR by removing the question comments.

**Comment by bdarnell** [comment]
LGTM. This is very similar to `TestMVCCUpdateExistingKeyOldVersion`, which was intended to test the same thing, but this test is a little better since it ensures that the old value can still be read. Maybe delete TestMVCCUpdateExistingKeyOldVersion and replace it with this one?

**Comment by kkaneda** [comment]
Hmm, `TestMVCCUpdateExistingKeyOldVersion` is slightly different that this since `TestMVCCUpdateExistingKeyOldVersion` doesn't use a transaction? (Put fails in the test.)

**Comment by bdarnell** [comment]
OK, if the tests are different then let's keep both.

**Comment by kkaneda** [comment]
Sure, merged and broke build. Sorry :( 

Fix: https://github.com/cockroachdb/cockroach/pull/1411

**Pull request merged**
