### PR TITLE
Rename proto roachpb

### PR DESCRIPTION
**Pull request by tamird**
This should go in after #2675 and #2678, should we decide to do it.

### CODE REVIEW

**Comment by petermattis** [comment]
I'm fine with renaming the `proto` package, but I'm not sure if I like `roachpb` much better, though it does avoid the conflict with the `gogoproto` package. Last I recall, we were trying to move stuff out of the `proto` package. Is that work complete? I ask because a quick inspection revealed `proto/heartbeat.proto` which looks like it can move to `rpc`.

**Comment by tamird** [comment]
That work isn't complete; nobody is actively working on it. I agree the name roachpb is not awesome, so I'm open to suggestions.

You're right, heartbeat.proto can move to rpc. I'll do that in another PR.

**Comment by petermattis** [comment]
I'm blanking on a better name that `roachpb` right now. But I also don't think `roachpb` is significantly better than `proto` to justify this change. I'd prefer to see us move stuff out of the `proto` directory and then see if what is left has a more obvious name.

**Comment by tamird** [comment]
It's better only in that it avoids the conflict with gogo/protobuf/proto

**Comment by tschottdorf** [comment]
I don't mind `roachpb` (I got the impression that the `pb` suffix was somewhat standard, at least `raft` has `raftpb`). Of course we should still try to untangle `proto` but not having to manually fix up imports every now and then will be nice.

**Comment by tschottdorf** [comment]
LGTM. Are you going to squash everything before you merge (since most of the intermediate commits likely don't compile/test/...) or what's the plan?

**Comment by tamird** [comment]
You tell me; I think it may be worth keeping as a record of work. Starting with 518bf542488e888721136d1b0b46b0e11c83cc51 the commits will compile/test

**Comment by tschottdorf** [comment]
Maybe squash everything before 518bf54 then?

**Comment by tamird** [comment]
squashed; every commit should compile/test now

**Pull request merged**
