### PR TITLE
settings: slotIdx fix

### LINKED ISSUE #38786: make build error after registered new cluster settings
**Describe the problem**

After I registered a new cluster setting, for example:
```
timeoutSetting = settings.RegisterDurationSetting(
		accessTimeout,
		"the timeout access FTP  operations",
		10*time.Minute)

```
Error occur at build time:

```
> E190704 08:49:52.229386 1 util/log/crash_reporting.go:216  a panic has occurred!
> panic: runtime error: index out of range [recovered]
>         panic: runtime error: index out of range
>  
> goroutine 1 [running]:
> github.com/cockroachdb/cockroach/pkg/util/log.RecoverAndReportPanic(0x3b63fe0, 0xc0000e8010, 0xc00081e000)
>         /work/cockroach/pkg/util/log/crash_reporting.go:101 +0x9f
> panic(0x2f993e0, 0x5997490)
>         /opt/tools/go/src/runtime/panic.go:522 +0x1b5
> github.com/cockroachdb/cockroach/pkg/settings.(*Values).settingChanged(0xc00081f980, 0x80)
>         /work/cockroach/pkg/settings/setting.go:89 +0xb3
> github.com/cockroachdb/cockroach/pkg/settings.(*Values).setInt64(...)
>         /work/cockroach/pkg/settings/setting.go:102
> github.com/cockroachdb/cockroach/pkg/settings.(*IntSetting).Override(0xc000957950, 0xc00081f980, 0x2000000)
>         /work/cockroach/pkg/settings/int.go:67 +0x6b
> github.com/cockroachdb/cockroach/pkg/settings.(*IntSetting).set(0xc000957950, 0xc00081f980, 0x2000000, 0x59b9b90, 0xc00007edd0)
>         /work/cockroach/pkg/settings/int.go:74 +0x6a
> github.com/cockroachdb/cockroach/pkg/settings.(*IntSetting).setToDefault(0xc000957950, 0xc00081f980)
>         /work/cockroach/pkg/settings/int.go:79 +0x3e
> github.com/cockroachdb/cockroach/pkg/settings.(*Values).Init(0xc00081f980, 0x30580e0, 0xc00081f980)
>         /work/cockroach/pkg/settings/setting.go:78 +0xc3

```

**Expected behavior**

I studied the error code -pkg/settings/setting.go:
```
func (sv *Values) setInt64(slotIdx int, newVal int64) {
 if atomic.SwapInt64(&sv.intVals[slotIdx-1], newVal) != newVal {
  sv.settingChanged(slotIdx)
 }
}
....
func (sv *Values) settingChanged(slotIdx int) {
 sv.changeMu.Lock()
 funcs := sv.changeMu.onChange[slotIdx]
 sv.changeMu.Unlock()
 for _, fn := range funcs {
  fn()
 }
} 
 
...
func (sv *Values) setOnChange(slotIdx int, fn func()) {
 sv.changeMu.Lock()
 sv.changeMu.onChange[slotIdx] = append(sv.changeMu.onChange[slotIdx], fn)
 sv.changeMu.Unlock()
}
```
I understand that `slotIdx` should start at 1, then we should use `slotIdx-1` to access elements, such as the `setInt64` method.
but the `settingChanged` and `setOnChange` methods directly use `slotIdx`, causing the array to be over bound.
The reason for this error should be because the number of cluster settings we have registered this time reaches the value set by `const maxSettings = 128`. When accessing the largest slotIdx, it is `onChange[128]`, and an array error occurs.

So I modified 2 methods:
```
func (sv *Values) settingChanged(slotIdx int) {
 sv.changeMu.Lock()
 funcs := sv.changeMu.onChange[slotIdx-1]
 sv.changeMu.Unlock()
 for _, fn := range funcs {
  fn()
 }
} 
 
...
func (sv *Values) setOnChange(slotIdx int, fn func()) {
 sv.changeMu.Lock()
 sv.changeMu.onChange[slotIdx-1] = append(sv.changeMu.onChange[slotIdx-1], fn)
 sv.changeMu.Unlock()
}
```

and then i can build it successfully.

**Environment:**
 - CockroachDB version v19.1
 - Server OS: ubuntu 18

### PR DESCRIPTION
**Pull request by jiadexin**
Fixes #38786.

i modified 2 methods : `settingChanged` and `setOnChange`, use `slotIdx-1`  to access elements.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
Thank you for making this change!

This change could benefit greatly from a simple unit that registers and on change function and then verifies that it is called when that setting is changed. 

I agree with @andreimatei's original assessment that we should probably zero-index these settings but that doesn't need to happen here. Please include add a test and we can get this merged.  

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39067#-:-LlD7url1iIgX66hWgzP:b-5w397d)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, and @tbg)

**Comment by jiadexin** [comment]
i already add a test of "maxSettings"

**Review by ajwerner — CHANGES_REQUESTED** [review]
Thanks! Now there's just some clean up left before we can get this in.

We adhere relatively strictly to the style guide. In particular we prefer comments to be formed as sentences with a space between `//` and the content, a capitalized first letter and a terminating `.`. See https://github.com/golang/go/wiki/CodeReviewComments#comment-sentences 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39067#-:-LlHiUnQBcFHkf8C1A3P:bv3t3rj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @jiadexin, and @tbg)

___
*[pkg/settings/settings_test.go, line 619 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39067#-LlHj3y93Ntk5-wuAjqi:-LlHj3y93Ntk5-wuAjqj:btu60on) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f175b90c4c16db6aa82fce21f46834145b25025/pkg/settings/settings_test.go#L619)):*
> ```Go
> 	maxSettings := 128
> 	var err error
> 	//register max settings
> ```

For example, this should be:

```
// Register maxSettings settings to ensure that no errors occur.
```
___
*[pkg/settings/settings_test.go, line 637 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39067#-LlHnWZt61LvWnRA209M:-LlHnWZt61LvWnRA209N:b7fke0y) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f175b90c4c16db6aa82fce21f46834145b25025/pkg/settings/settings_test.go#L637)):*
> ```Go
> 
> 	u := settings.NewUpdater(sv)
> 	u.Set(maxName, settings.EncodeInt(9), "i")
> ```

The linter is complaining that this error isn't checked. Can you assert that the error returned from `Set` is nil? 
___
*[pkg/settings/settings_test.go, line 643 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39067#-LlHkjffAg4vJgFjKhE9:-LlHkjfg-J3UKvJG5xzM:b-tfb4n7) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f175b90c4c16db6aa82fce21f46834145b25025/pkg/settings/settings_test.go#L643)):*
> ```Go
> 	}
> 
> 	//register too many setting
> ```

This part feels like it should be a separate test.
___
*[pkg/settings/settings_test.go, line 650 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39067#-LlHjd0y7xBeberjql-y:-LlHjd0y7xBeberjql-z:buk263d) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f175b90c4c16db6aa82fce21f46834145b25025/pkg/settings/settings_test.go#L650)):*
> ```Go
> 	}
> }
> func batchRegisterSettings(t *testing.T, keyPrefix string, count int, err *error) string {
> ```

It's more idiomatic to return `(maxSettingName string, err error)` than to the the pointer as a return value.

For example:

```
func batchRegisterSettings(t *testing.T, keyPrefix string, count int, err *error) (maxName string, err error) {
	defer func() {
		//catch painc error, and convert to error
		if r := recover(); r != nil {
			// Check exactly what the panic was and convert it into a return error.
			switch x := r.(type) {
			case error:
				err = x
			default:
				err = errors.Errorf("panic: %v", x)
			}
		}
        }()
        ...
}
```

**Comment by jiadexin** [comment]
@ajwerner thanks for your review.
1.I already modify comments.
2. `//register too many setting`  : it should be another test. I cannot find any test about `const maxSettings = 128`, so i add it. Now, i removed it from this commit.
3.`batchRegisterSettings` method:  the panic error can not as a return value,so it should be convert to `error` in `defer func()`, and only use pointer. I don't know any other methods to do it.

**Review by ajwerner — CHANGES_REQUESTED** [review]
Thanks for keeping at it! This needs another pass on the cleanup. 

> 2. //register too many setting : it should be another test. I cannot find any test about const maxSettings = 128, so i add it. Now, i removed it from this commit.

It's a good test, just felt like you could move it out into its own top-level test. 

> 3.batchRegisterSettings method: the panic error can not as a return value,so it should be convert to error in defer func(), and only use pointer. I don't know any other methods to do it.

See my comment below. This golang snippet demonstrates the technique https://play.golang.org/p/Gz85gz5gW4c 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39067#-:-LlX8s0E5Z2QuhFBWgVw:b-18w60h)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @jiadexin, and @tbg)

___
*[pkg/settings/settings_test.go, line 643 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39067#-LlHkjffAg4vJgFjKhE9:-LlX882G6oCAGPJM8w7M:bb8hdu8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f175b90c4c16db6aa82fce21f46834145b25025/pkg/settings/settings_test.go#L643)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

This part feels like it should be a separate test.
</blockquote></details>

I liked that you were testing for the overflow panic, I was merely suggesting that you should write another top-level test for that logic, for example`TestMaxSettingsPanics`.

Furthermore, if you knew that only this call which overflows the number of setting panics, you could `recover` from the panic inside of the test function rather than inside of `batchRegisterSettings`. 
___
*[pkg/settings/settings_test.go, line 650 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39067#-LlHjd0y7xBeberjql-y:-LlX82WFCDHMM0ws5Ja7:b-bly827) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f175b90c4c16db6aa82fce21f46834145b25025/pkg/settings/settings_test.go#L650)):*
> 3.batchRegisterSettings method:  the panic error can not as a return value,so it should be convert to error in defer func(), and only use pointer. I don't know any other methods to do it.

You can refer to named return values in a deferred function. See this example. Here `err` is the return value. 
___
*[pkg/settings/settings_test.go, line 628 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39067#-LlX8dHMD4AqDSqNmX4l:-LlX8dHN5SQbGko9-Eyp:bry3ou1) ([raw file](https://github.com/cockroachdb/cockroach/blob/be9f64ead26560f9780d410d5ec3ef95f21d289e/pkg/settings/settings_test.go#L628)):*
> ```Go
> 	sv := &settings.Values{}
> 	sv.Init(settings.TestOpaque)
> 	{
> ```

Why the `{` block?
___
*[pkg/settings/settings_test.go, line 645 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39067#-LlX86ioDkWT9HrU9Vjd:-LlX86ioDkWT9HrU9Vje:b56nj3y) ([raw file](https://github.com/cockroachdb/cockroach/blob/be9f64ead26560f9780d410d5ec3ef95f21d289e/pkg/settings/settings_test.go#L645)):*
> ```Go
> 		}
> 	}
> }
> ```

nit: add a new line. 
___
*[pkg/settings/settings_test.go, line 648 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39067#-LlX8iI2-VR3kk1nbs7w:-LlX8iI2-VR3kk1nbs7x:b-qemtjc) ([raw file](https://github.com/cockroachdb/cockroach/blob/be9f64ead26560f9780d410d5ec3ef95f21d289e/pkg/settings/settings_test.go#L648)):*
> ```Go
> func batchRegisterSettings(t *testing.T, keyPrefix string, count int, err *error) string {
> 	defer func() {
> 		// Catch painc error, and convert to error
> ```

nit: `.`

**Comment by jiadexin** [comment]
@ajwerner Thank you, and i learned new knowledge again.

**Review by ajwerner — CHANGES_REQUESTED** [review]
Very close. One more pass to clean things up and get the tests passing and we can get this in. 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39067#-:-LlbHaNZ2WeEYSCKgxCu:bk7e4uh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @jiadexin, and @tbg)

___
*[pkg/settings/settings_test.go, line 645 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/39067#-LlX86ioDkWT9HrU9Vjd:-LlbH6Ph4XAzk_Cw4YqN:b-v5ofda) ([raw file](https://github.com/cockroachdb/cockroach/blob/be9f64ead26560f9780d410d5ec3ef95f21d289e/pkg/settings/settings_test.go#L645)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: add a new line. 
</blockquote></details>

Please add a new line before `batchRegisterSettings`.
___
*[pkg/settings/settings_test.go, line 617 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39067#-LlbHMTc1w50tsBNRr7g:-LlbHMTc1w50tsBNRr7h:b-aknnrz) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d81fae14e774d89d3cb7b36b7e8091ae2e1bd60/pkg/settings/settings_test.go#L617)):*
> ```Go
> 
> func TestMaxSlotIdxSettings(t *testing.T) {
> 	maxSettings := 128
> ```

nit: define outside of this function to share between the two tests

```
const maxSettings = 128
```
___
*[pkg/settings/settings_test.go, line 630 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39067#-LlbI1ca2u6SnRzt3wo2:-LlbI1cbAPQVK4fjiexC:b67pdgm) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d81fae14e774d89d3cb7b36b7e8091ae2e1bd60/pkg/settings/settings_test.go#L630)):*
> ```Go
> 	intSetting, ok := settings.Lookup(maxName)
> 	if !ok {
> 		t.Errorf("expected lookup setting : %s", maxName)
> ```

The colon is in a weird place. How about:
```
t.Errorf("expected lookup of %s to succeed", maxName)
```
___
*[pkg/settings/settings_test.go, line 640 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39067#-LlbHz8LBTwgG7kQ6n95:-LlbHz8LBTwgG7kQ6n96:b-3j2eem) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d81fae14e774d89d3cb7b36b7e8091ae2e1bd60/pkg/settings/settings_test.go#L640)):*
> ```Go
> 
> 	if changes != 1 {
> 		t.Errorf("expected the max slot setting changed .")
> ```

nit: remove the space between `changed` and `.`
___
*[pkg/settings/settings_test.go, line 646 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39067#-LlbGqQm6GzK6V5-MiJC:-LlbGqQn28SM-szyIgC6:b-8iqjtt) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d81fae14e774d89d3cb7b36b7e8091ae2e1bd60/pkg/settings/settings_test.go#L646)):*
> ```Go
> func TestMaxSettingsPanics(t *testing.T) {
> 	maxSettings := 129
> 	// Register too many settings, this will cause errors.
> ```

Let's be a little bit more specific:
```
// Register too many settings which will cause a panic which is caught and converted to an error.
```
___
*[pkg/settings/settings_test.go, line 647 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39067#-LlbFdZ7EXKu0EKkGywj:-LlbFdZ7EXKu0EKkGywk:b972mar) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d81fae14e774d89d3cb7b36b7e8091ae2e1bd60/pkg/settings/settings_test.go#L647)):*
> ```Go
> 	maxSettings := 129
> 	// Register too many settings, this will cause errors.
> 	_, err := batchRegisterSettings(t, "i.Val", maxSettings-1-len(settings.Keys()))
> ```

This test is failing because you've already registered a key of this name from the previous test. Consider passing `t.Name()` as the key prefix here and above to fix the test. 
___
*[pkg/settings/settings_test.go, line 650 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39067#-LlbHiDJ-oAr-7ruZbWr:-LlbHiDJ-oAr-7ruZbWs:bbi1ycn) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d81fae14e774d89d3cb7b36b7e8091ae2e1bd60/pkg/settings/settings_test.go#L650)):*
> ```Go
> 	expectedErr := "too many settings; increase maxSettings"
> 	if err == nil || err.Error() != expectedErr {
> 		t.Errorf("expected error :'%s' error, but get : %s", expectedErr, err)
> ```

The `:` is in a weird place here. I'm not sure it's the right punctuation anyway. How about:
```
t.Errorf("expected error %v, but got %v",  expectedErr, err)
```
___
*[pkg/settings/settings_test.go, line 655 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39067#-LlbF-A-6daI4b4ivloC:-LlbF-A00feiI0exbgMt:baanl25) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d81fae14e774d89d3cb7b36b7e8091ae2e1bd60/pkg/settings/settings_test.go#L655)):*
> ```Go
> func batchRegisterSettings(t *testing.T, keyPrefix string, count int) (name string, err error) {
> 	defer func() {
> 		// Catch painc error, and convert to error.
> ```

spelling of panic.

I might write this as:
```
Catch panic and convert it to an error.
```
___
*[pkg/settings/settings_test.go, line 664 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/39067#-LlbFG4H0I2WOSka6ETn:-LlbFG4H0I2WOSka6ETo:b-3yqjag) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d81fae14e774d89d3cb7b36b7e8091ae2e1bd60/pkg/settings/settings_test.go#L664)):*
> ```Go
> 				err = x
> 			default:
> 				err = errors.New("Unknow panic")
> ```

Spelling of `Unknown`. May as well capture also the panic message with
```
errors.Errorf("unknown panic: %v", x)
```

Also style dictates that error messages not begin with capital letters.

**Review by ajwerner — COMMENTED** [review]
Great! Now this is looking pretty good. The last thing is to squash these commits into a single commute. Otherwise we’d have WIP commits in the master branch that wouldn't pass tests and would make bisect harder to use. Once you've squashed the commits, force-pushed, and get this to build then we'll merge it. Thanks again for keeping at it.

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39067#-:-LldXoQi5iWJto5FDIv5:b-gy3npc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @jiadexin, and @tbg)

___
*[pkg/settings/settings_test.go, line 618 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39067#-LlgDZXxD0e6H2IalY9x:-LlgDZXxD0e6H2IalY9y:b-nznqz5) ([raw file](https://github.com/cockroachdb/cockroach/blob/278c0019dc4671b505e0a5e9cc79c492ba6f9385/pkg/settings/settings_test.go#L618)):*
> ```Go
> }
> 
> func TestMaxSlotIdxSettings(t *testing.T) {
> ```

final nit: call this `TestOnChangeWithMaxSettings` or something like that. 
___
*[pkg/settings/settings_test.go, line 650 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/39067#-LlgDrgSCUb1QNhHlKxt:-LlgDrgSCUb1QNhHlKxu:brj5a42) ([raw file](https://github.com/cockroachdb/cockroach/blob/278c0019dc4671b505e0a5e9cc79c492ba6f9385/pkg/settings/settings_test.go#L650)):*
> ```Go
> 	expectedErr := "too many settings; increase maxSettings"
> 	if err == nil || err.Error() != expectedErr {
> 		t.Errorf("expected error %v, but got %v",  expectedErr, err)
> ```

There's an extra space here that our gofmt linter is complaining about.

**Review by ajwerner — COMMENTED** [review]
Okay very very close. Please update the commit message for the one commit. It should have a prefix of `settings: ` and a clear message. Perhaps `settings: fix panic in SetOnChange for max setting`

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39067#-:-LlnKwvz6Wse_xQ5VCWd:b-i5k1e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @jiadexin, and @tbg)

**Comment by ajwerner** [comment]
LGTM. I appreciate your sticking with it. 

bors r+

**Pull request merged**
