### PR TITLE
ui: add attributes to login form so LastPass will autofill it

### LINKED ISSUE #29529: UI: ensure password managers are happy with the login form
Two things when I try to login:
* lastpass does seem to detect that this is a login and does not offer to save the username/password
* when clicking 'login', LastPass throws `LastPass detected a login form that is insecure`

According to the [LastPass docs](https://lastpass.com/support.php?cmd=showfaq&id=7336):

```
This means that the webpage you are on uses an insecure method to submit data.
We specifically look for GET and mailto: methods on the page
```

This happens on `adriatic` which has a real server certificate for the Admin UI.
This was tested on Chrome 68.0.3440.106 for Linux, LastPass Chrome Toolbar: 4.17.0.

### PR DESCRIPTION
**Pull request by vilterp**
LastPass wasn't confident enough to autofill and autologin without these
attributes.

Fixes #29529 (fixes for LastPass, but maybe not other PW managers)

Release note (admin ui change): Add attributes to the login form to allow LastPass to properly recognize it.

### CODE REVIEW

**Review by benesch — APPROVED** [review]
Sweet! Thanks!

**Review by couchand — APPROVED** [review]
LGTM.

Seems reasonable to just say this fixes #29529 and wait to see if we get complaints about other password managers, or if we have bandwidth, make a different issue to tackle testing of other ones.

**Comment by mberhault** [comment]
LGTM. Thanks!

**Pull request merged**
