### PR TITLE
roachtest: fix tpchvec/perf in some cases

### PR DESCRIPTION
**Pull request by yuzefovich**
Previously, whenever a slowness threshold is exceeded, we would run
EXPLAIN ANALYZE (DEBUG) on the query at fault using the same connection
for all cluster setups. This would result in running the query only with
vectorize=on which is not what we want. We will now be opening up new
connections to the database after the cluster settings have been updated
in order to get the correct behavior for each of the setups.

Informs: #53884.

Release note: None

### CODE REVIEW

**Review by asubiotto — COMMENTED** [review]
I'm a bit confused. I'm not sure I understand how this log message helps determining whether `EXPLAIN ANALYZE` ran on the query. Is it part of cluster setup?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53911#-:-MGJtvNRAaYynMtkp0Tq:b-x4ukns)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

**Review by yuzefovich — COMMENTED** [review]
Before we run `EXPLAIN ANALYZE`, we perform the necessary cluster setup on all configs, so I want to make sure that the correct queries are executed during that setup. Confusingly, in the logs I did see a message about vectorize being set to `off`, but still only the vectorized stats were available.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53911#-:-MGJuPYm0Khw0TJ7Lb0b:b-p3rwzw)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
To provide more context - the sequence is:
- for every cluster setup
  - perform all queries in the setup
  - run EXPLAIN ANALYZE on the query the desired number of times

So printing the queries into the logs will show exactly what queries have been executed before running EXPLAIN ANALYZE.

**Review by asubiotto — APPROVED** [review]
Have you tried inducing a failure locally? Does `EXPLAIN ANALYZE` get run in this case?

:lgtm: if it does not occur locally

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53911#-:-MGNfxm9-KDPIm9kVcLD:bhn1lsk)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
Forcing the collection of the bundle manually I still see that we correctly execute the cluster setup for vectorize=off case, yet the stats are collected as if vectorize=on is set. Digging into this.

**Comment by yuzefovich** [comment]
Updated the PR to fix the problem with the wrong config being used during EXPLAIN ANALYZE (DEBUG) and confirmed manually that the bundles are as expected. RFAL.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53911#-:-MGslQrj0DLYIlP-ls7U:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
