### PR TITLE
kvtenantccl: unskip TestTenantUpgradeInterlock (and move it to its own package)

### LINKED ISSUE #99593: ccl/kvccl/kvtenantccl: TestTenantUpgradeInterlock failed
ccl/kvccl/kvtenantccl.TestTenantUpgradeInterlock [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsGcpLinuxX8664BigVm_CclUnitTests/9261217?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsGcpLinuxX8664BigVm_CclUnitTests/9261217?buildTab=artifacts#/) on master @ [d107217dac5d817cc115bc0e97b7e53c0f2878bf](https://github.com/cockroachdb/cockroach/commits/d107217dac5d817cc115bc0e97b7e53c0f2878bf):

Fatal error:

```
panic: test timed out after 14m55s

```
Stack: 

```
goroutine 466229 [running]:
testing.(*M).startAlarm.func1()
	GOROOT/src/testing/testing.go:2036 +0x8e
created by time.goFunc
	GOROOT/src/time/sleep.go:176 +0x32
```
<details><summary>Log preceding fatal error</summary>
<p>

```
=== RUN   TestTenantUpgradeInterlock
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/e7ead71a4f5b50fae4d2996264db30c2/logTestTenantUpgradeInterlock3136512125
    test_log_scope.go:79: use -show-logs to present logs inline
=== RUN   TestTenantUpgradeInterlock/current_binary_version_pause_after_first_check_for_instances
    tenant_upgrade_test.go:525: upgrade interlock test: running variant "current binary version", configuration: "pause after first check for instances"
```
</p>
</details>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/multi-tenant
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestTenantUpgradeInterlock.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-25961

### PR DESCRIPTION
**Pull request by knz**
Fixes #99593

It does takes an enormous amount of time to run successfully, more than the previous timeout allowed:

```
--- PASS: TestTenantUpgradeInterlock (316.36s)
    --- PASS: TestTenantUpgradeInterlock/lagging_binary_version (120.85s)
        --- PASS: TestTenantUpgradeInterlock/lagging_binary_version/pause_after_first_check_for_instances (9.02s)
        --- PASS: TestTenantUpgradeInterlock/lagging_binary_version/pause_after_fence_RPC (10.11s)
        --- PASS: TestTenantUpgradeInterlock/lagging_binary_version/pause_after_fence_write_to_settings_table (20.27s)
        --- PASS: TestTenantUpgradeInterlock/lagging_binary_version/pause_after_second_check_of_instances (20.20s)
        --- PASS: TestTenantUpgradeInterlock/lagging_binary_version/pause_after_migration (20.45s)
        --- PASS: TestTenantUpgradeInterlock/lagging_binary_version/pause_after_version_bump_RPC (20.28s)
        --- PASS: TestTenantUpgradeInterlock/lagging_binary_version/pause_after_write_to_settings_table (20.51s)
    --- PASS: TestTenantUpgradeInterlock/current_binary_version (195.51s)
        --- PASS: TestTenantUpgradeInterlock/current_binary_version/pause_after_first_check_for_instances (20.00s)
        --- PASS: TestTenantUpgradeInterlock/current_binary_version/pause_after_fence_RPC (30.23s)
        --- PASS: TestTenantUpgradeInterlock/current_binary_version/pause_after_fence_write_to_settings_table (29.02s)
        --- PASS: TestTenantUpgradeInterlock/current_binary_version/pause_after_second_check_of_instances (29.14s)
        --- PASS: TestTenantUpgradeInterlock/current_binary_version/pause_after_migration (29.00s)
        --- PASS: TestTenantUpgradeInterlock/current_binary_version/pause_after_version_bump_RPC (29.03s)
        --- PASS: TestTenantUpgradeInterlock/current_binary_version/pause_after_write_to_settings_table (29.08s)
PASS
INFO: Elapsed time: 318.059s, Critical Path: 317.36s
INFO: 2 processes: 1 internal, 1 processwrapper-sandbox.
//pkg/ccl/kvccl/kvtenantccl:kvtenantccl_test                             PASSED in 317.2s
```

(and this is on a faster machine than in CI)

Release note: None

### CODE REVIEW

**Review by arulajmani — APPROVED** [review]
> Reviewed 6 of 6 files at r1, 1 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100536)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[`pkg/ccl/kvccl/kvtenantccl/upgradeinterlockccl/tenant_upgrade_test.go` line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100536#-NS8LvsU9uGZwd2Bk6ou:-NS8LvsU9uGZwd2Bk6ov:bb8i652) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ad49012aa15efc3a1dec2bf3d69bf38ecb8dbea/pkg/ccl/kvccl/kvtenantccl/upgradeinterlockccl/tenant_upgrade_test.go#L55)):*
> ```Go
> func TestTenantUpgradeInterlock(t *testing.T) {
> 	defer leaktest.AfterTest(t)()
> 	// Times out under stress race
> ```

nit: here, and below, fullstops.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100536)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/ccl/kvccl/kvtenantccl/upgradeinterlockccl/tenant_upgrade_test.go` line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100536#-NS8LvsU9uGZwd2Bk6ou:-NS8OuGOEMB01C_-B_BM:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/2ad49012aa15efc3a1dec2bf3d69bf38ecb8dbea/pkg/ccl/kvccl/kvtenantccl/upgradeinterlockccl/tenant_upgrade_test.go#L55)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: here, and below, fullstops. 
</blockquote></details>

Done

**Comment by knz** [comment]
TFYR!

bors r=arulajmani

**Comment by knz** [comment]
bors r=arulajmani

**Pull request merged**
