### PR TITLE
server: include schema info in reported diagnostics

### PR DESCRIPTION
**Pull request by dt**

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r1, 3 of 4 files at r2.
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/server/updates.go, line 308 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15314#-KiZ1kJrU0Rz-pQrfzjF:-KiZ1kJrU0Rz-pQrfzjG:b-hu10x8) ([raw file](https://github.com/cockroachdb/cockroach/blob/3377d51308b27c25f9a2ce3ba004362ed1398df3/pkg/server/updates.go#L308)):*
> ```Go
> 	startKey := roachpb.Key(keys.MakeTablePrefix(keys.DescriptorTableID))
> 	endKey := startKey.PrefixEnd()
> 	rows, err := s.db.Scan(ctx, startKey, endKey, 0)
> ```

these are kvs, not rows

---

*[pkg/server/updates_test.go, line 138 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15314#-KiZ2EB4c6EZ9A1BIcyF:-KiZ2EB57-HiDKi_VZId:b-f2c36o) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ffb5fadef4107d8de86e5a0d9da7ab032f71e9c/pkg/server/updates_test.go#L138)):*
> ```Go
> 		t.Fatalf("unexpected table count %d", actual)
> 	}
> 	if expected, actual := "_", tables[0].Name; expected != actual {
> ```

why not check them all?

---

*[pkg/server/updates_test.go, line 199 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15314#-KiZ2IE6YcnCz5lvnjpG:-KiZ2IE6YcnCz5lvnjpH:bf6nd2v) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ffb5fadef4107d8de86e5a0d9da7ab032f71e9c/pkg/server/updates_test.go#L199)):*
> ```Go
> 	})
> 
> 	for _, redacted := range []string{"foobar", "baz", "somestring"} {
> ```

it would be great if you didn't rely on magic strings here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15314)*

**Comment by knz** [comment]
Please extend the 2nd commit message to explain how this is done.
LGTM modulo your reactions to tamir's comments.

---

Reviewed 2 of 2 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/server/updates.go, line 305 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15314#-Ki_00bN2KdOUKUDT9uu:-Ki_00bN2KdOUKUDT9uv:bxn9u3m) ([raw file](https://github.com/cockroachdb/cockroach/blob/3377d51308b27c25f9a2ce3ba004362ed1398df3/pkg/server/updates.go#L305)):*
> ```Go
> }
> 
> func (s *Server) collectSchemaInfo(ctx context.Context) ([]sqlbase.TableDescriptor, error) {
> ```

What about a shared method in `sqlbase` reused both here and for `sqlccl.allSQLDescriptors()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15314#-:-KiZzBGxqvolD_p8zhtT:b-5aj1ff)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/server/updates.go, line 305 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15314#-Ki_00bN2KdOUKUDT9uu:-Ki_13y5DQzVwhDKSn3c:b-rlxw2x) ([raw file](https://github.com/cockroachdb/cockroach/blob/3377d51308b27c25f9a2ce3ba004362ed1398df3/pkg/server/updates.go#L305)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

What about a shared method in `sqlbase` reused both here and for `sqlccl.allSQLDescriptors()`.
</blockquote></details>

This has diverged a bit from sqlccl.allSQLDescriptors() -- redacting strings and skipping system tables.

We could parameterize it, or could accumulate all the results first to then filter into a second slice at the caller, but is it enough reuse to warrant either of those?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15314)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/server/updates.go, line 305 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15314#-Ki_00bN2KdOUKUDT9uu:-Ki_3KAVtcoy2HA4IPef:b-7exwys) ([raw file](https://github.com/cockroachdb/cockroach/blob/3377d51308b27c25f9a2ce3ba004362ed1398df3/pkg/server/updates.go#L305)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

This has diverged a bit from sqlccl.allSQLDescriptors() -- redacting strings and skipping system tables.

We could parameterize it, or could accumulate all the results first to then filter into a second slice at the caller, but is it enough reuse to warrant either of those?
</blockquote></details>

I was thinking about doing the redacting after the new method has returned, not as a part of it. (separation of concerns, yada yada)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15314)*

**Comment by dt** [comment]
Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/server/updates.go, line 305 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15314#-Ki_00bN2KdOUKUDT9uu:-Ki_8UnXGfBS-_GLay4g:bcdpurj) ([raw file](https://github.com/cockroachdb/cockroach/blob/3377d51308b27c25f9a2ce3ba004362ed1398df3/pkg/server/updates.go#L305)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I was thinking about doing the redacting after the new method has returned, not as a part of it. (separation of concerns, yada yada)
</blockquote></details>

yeah, if it were just the redacting, it would be simple second pass in the caller, but the callsite in sqlccl does its read with a Txn, it includes non-Table Descriptors, it includes system tables -- reusing ends up kinda clunky, but i can take another stab at it if you want.

---

*[pkg/server/updates.go, line 308 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15314#-KiZ1kJrU0Rz-pQrfzjF:-Ki_2PaOLhBXhXAWPUho:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3377d51308b27c25f9a2ce3ba004362ed1398df3/pkg/server/updates.go#L308)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

these are kvs, not rows
</blockquote></details>

Done.

---

*[pkg/server/updates_test.go, line 138 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15314#-KiZ2EB4c6EZ9A1BIcyF:-Ki_2TrZz6e6RZGlh3k6:b-pfqkgh) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ffb5fadef4107d8de86e5a0d9da7ab032f71e9c/pkg/server/updates_test.go#L138)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why not check them all?
</blockquote></details>

what do you mean by "them all"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15314)*

**Comment by knz** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/server/updates.go, line 305 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15314#-Ki_00bN2KdOUKUDT9uu:-Ki_IaXQeOUiykdldne4:b-rpm2gy) ([raw file](https://github.com/cockroachdb/cockroach/blob/3377d51308b27c25f9a2ce3ba004362ed1398df3/pkg/server/updates.go#L305)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

yeah, if it were just the redacting, it would be simple second pass in the caller, but the callsite in sqlccl does its read with a Txn, it includes non-Table Descriptors, it includes system tables -- reusing ends up kinda clunky, but i can take another stab at it if you want.
</blockquote></details>

Ok I don't know about system tables but it seems to me we want at least to include the index and view descriptors too here.
(I don't feel too strongly about the reuse)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15314)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/server/updates.go, line 305 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15314#-Ki_00bN2KdOUKUDT9uu:-Ki_JCQEv_uqVABCZ4mI:b-m18vy0) ([raw file](https://github.com/cockroachdb/cockroach/blob/3377d51308b27c25f9a2ce3ba004362ed1398df3/pkg/server/updates.go#L305)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Ok I don't know about system tables but it seems to me we want at least to include the index and view descriptors too here.
(I don't feel too strongly about the reuse)
</blockquote></details>

Index and view descriptors are fields of the table descriptor, so they are there (though the views are pretty useless with the current scrub, but that's the best we can do for now).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15314)*

**Comment by tamird** [comment]
Reviewed 1 of 4 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/server/updates_test.go, line 138 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15314#-KiZ2EB4c6EZ9A1BIcyF:-Ki_SBYh9yxqAN5glTng:b-ysrp0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ffb5fadef4107d8de86e5a0d9da7ab032f71e9c/pkg/server/updates_test.go#L138)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

what do you mean by "them all"?
</blockquote></details>

I had missed the length assertion, but still:

```
for _, desc := range tables {
  if expected, actual := "_", desc.Name; ... {
   ....
  }
}
```

---

*[pkg/server/updates_test.go, line 132 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15314#-Ki_SWI6PfEa6hBj7i6h:-Ki_SWI6PfEa6hBj7i6i:b-v6tckt) ([raw file](https://github.com/cockroachdb/cockroach/blob/039e93a1363d419729e1951e7944dcde0907d2e1/pkg/server/updates_test.go#L132)):*
> ```Go
> 	}
> 	if _, err := db.Exec(fmt.Sprintf(
> 		`CREATE TABLE %s.%s (%s INT CONSTRAINT %s CHECK (%s > 1))`,
> ```

you can use `%[1]s` instead of passing `elemName` 5 times.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15314)*

**Comment by dt** [comment]
TFTR!

---

Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/server/updates_test.go, line 138 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15314#-KiZ2EB4c6EZ9A1BIcyF:-Ki_SzSnszua62qTxvHZ:b-ikp520) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ffb5fadef4107d8de86e5a0d9da7ab032f71e9c/pkg/server/updates_test.go#L138)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I had missed the length assertion, but still:

```
for _, desc := range tables {
  if expected, actual := "_", desc.Name; ... {
   ....
  }
}
```
</blockquote></details>

i guess?

Done.

---

*[pkg/server/updates_test.go, line 199 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15314#-KiZ2IE6YcnCz5lvnjpG:-Ki_P2bUhmlyZFjBKEGZ:b-gq70ph) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ffb5fadef4107d8de86e5a0d9da7ab032f71e9c/pkg/server/updates_test.go#L199)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

it would be great if you didn't rely on magic strings here
</blockquote></details>

Pulled into a constant. This check is mostly just i

---

*[pkg/server/updates_test.go, line 132 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15314#-Ki_SWI6PfEa6hBj7i6h:-Ki_TAEGdfE7VamQos2z:b-1dfpj4) ([raw file](https://github.com/cockroachdb/cockroach/blob/039e93a1363d419729e1951e7944dcde0907d2e1/pkg/server/updates_test.go#L132)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

you can use `%[1]s` instead of passing `elemName` 5 times.
</blockquote></details>

Oh that's much better, thanks!

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15314#-:-Ki_WAi2U9WJnYJ9Secu:b-814g8k)*

**Comment by dt** [comment]
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/server/updates_test.go, line 199 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15314#-KiZ2IE6YcnCz5lvnjpG:-Ki_WGPfRgdUEOOPnr3r:bi1fpv5) ([raw file](https://github.com/cockroachdb/cockroach/blob/8ffb5fadef4107d8de86e5a0d9da7ab032f71e9c/pkg/server/updates_test.go#L199)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Pulled into a constant. This check is mostly just i
</blockquote></details>

whoops, draft comment caught in Publish, s/This check.*//.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15314)*

**Comment by knz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/server/updates.go, line 305 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15314#-Ki_00bN2KdOUKUDT9uu:-Ki_XTAZex2bcjY7jUnR:b2nhb2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/3377d51308b27c25f9a2ce3ba004362ed1398df3/pkg/server/updates.go#L305)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Index and view descriptors are fields of the table descriptor, so they are there (though the views are pretty useless with the current scrub, but that's the best we can do for now).
</blockquote></details>

Ack

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15314#-:-Ki_XYWNFiW75IyM_Tta:bnfp4nl)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15314#-:-Ki_hRS1viKtVqeZlbFV:bnfp4nl)*

**Comment by dt** [comment]
cc @benesch in case this is interesting in the reg-server work you're doing.

**Pull request merged**
