### PR TITLE
Correction to backup sql diagram

### PR DESCRIPTION
**Pull request by katmayb**
Release note: None

### CODE REVIEW

**Comment by kathancox** [comment]
Hey @ericharmeling Would you mind peeking at this, I forgot one of the links in the backup diagram... discovered when building a docs PR!

**Review by lnhsingh — APPROVED** [review]

**Review by ericharmeling — APPROVED** [review]
This fix LGTM, but should we also unlink `database_name` and `table_pattern`?

**Comment by kathancox** [comment]
`table_pattern` and `database_name` were already there and I just checked from the backup page... and they do actually have links to the sql grammar. Also the subdirectory one, was the only one appearing in docs builds as a problem, so I think this is enough

**Comment by ericharmeling** [comment]
> table_pattern and database_name were already there and I just checked from the backup page... and they do actually have links to the sql grammar. Also the subdirectory one, was the only one appearing in docs builds as a problem, so I think this is enough

SGTM!

**Pull request merged**
