### PR TITLE
Support SHOW (INDEXES | KEYS) as alias to SHOW INDEX.

### LINKED ISSUE #4932: sql: Support "indexes" keyword in addition to "index" on SHOW
MySQL supports both `SHOW INDEXES FROM <table>` and `SHOW INDEX FROM <table>`. Most web searches yield results mentioning `INDEXES`. We should probably support both, as `INDEX` (what we currently support) doesn't make as much sense in most contexts.

### PR DESCRIPTION
**Pull request by knz**
"KEYS" for symmetry with the CREATE syntax for tables.
"INDEXES" for symmetry with "SHOW COLUMNS" and "SHOW TABLES".

Fixes #4932.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4935)

### CODE REVIEW

**Comment by tamird** [comment]
Can you add some parser tests?

**Comment by knz** [comment]
@tamird I'm not sure I want to introduce a parser test for this. The reason is that it's a simple desugaring and there is absolutely no user/product value in carrying extra parsing state about which keyword was used in the input. 

Also I have prior art on my side; the following are supported but do not have a parser test for the same reason:

```
SELECT * FROM t OFFSET 12 ROWS;
SELECT * FROM t OFFSET 12 ROW;
SELECT CURRENT_TIMESTAMP;
SELECT CURRENT_TIMESTAMP();
SELECT SUBSTRING('foo' FROM 2 FOR 3);
SELECT SUBSTRING('foo' FOR 2 FROM 3);
```

and so on...

**Comment by tamird** [comment]
@petermattis feels strongly about this, I'll let him weigh in.

**Comment by petermattis** [comment]
See `sql/parser.TestParse2`. You can write a test case that parses one form and outputs another.

**Comment by tamird** [comment]
Weren't we striving for our parser to have the property that the AST can transit strings unmolested?

**Comment by petermattis** [comment]
@tamird Yes, that is something we strive for, but you can see from `TestParse2` that we fall short in many places. I'm fine with this change as long as we document this with additional cases in `TestParse2`.

**Comment by knz** [comment]
@tamird @petermattis sorry I hadn't seen `TestParse2`. I added the test cases to it now.

**Comment by petermattis** [comment]
LGTM

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/testdata/create_index, line 40 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4935#-KCHhYkJRosG2aBBOE-5:-KCHhYkJRosG2aBBOE-6:615967326) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ccd09f224f0a5e53a7a286234f584c289ab51a5/sql/testdata/create_index#L40)):*
I wonder if this should be `SHOW INDEX FROM` and we should `s/SHOW INDEX FROM/SHOW INDEXES FROM/g` elsewhere in these test files. This doesn't need to be done in this PR.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4935#-:-KCHhjUxYkXMcOOESSCr:676834233)*

**Comment by tamird** [comment]
Reviewed 3 of 4 files at r1, 1 of 2 files at r2, 11 of 11 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4935)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/testdata/create_index, line 40 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4935#-KCHhYkJRosG2aBBOE-5:-KCHy2FxV0GLFnuUS_YZ:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/9ccd09f224f0a5e53a7a286234f584c289ab51a5/sql/testdata/create_index#L40)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4935)*

**Pull request merged**
