### PR TITLE
roachtest: add new tpcc/w=1000/nodes=3 test

### PR DESCRIPTION
**Pull request by nvb**
This change adds a new `tpcc/w=1000/nodes=3` test. In doing so,
it adds support for tpcc roachtests to import fixtures.

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28064#-:-LIgy-6s8S0ISdOG2G9r:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/tpcc.go, line 64 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28064#-LIgxrM71nfMyvicnNcX:-LIgxrM71nfMyvicnNcY:b-qok8rp) ([raw file](https://github.com/cockroachdb/cockroach/blob/41c1c48d799a4ed78208af3706ec965773ac96e6/pkg/cmd/roachtest/tpcc.go#L64)):*
> ```Go
> 			t.Status("running workload")
> 			ramp := " --ramp=" + ifLocal("0s", "3m")
> 			duration := " --duration=" + ifLocal("10s", "20m")
> ```

Curious of the 3m ramp and 20m duration came from anywhere?

**Review by petermattis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28064)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/tpcc.go, line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28064#-LIgy6XX4lT16NTCZO7b:-LIgy6XX4lT16NTCZO7c:bkwuivq) ([raw file](https://github.com/cockroachdb/cockroach/blob/41c1c48d799a4ed78208af3706ec965773ac96e6/pkg/cmd/roachtest/tpcc.go#L52)):*
> ```Go
> 			if useFixture {
> 				cmd := fmt.Sprintf(
> 					"./workload fixtures load tpcc --warehouses=%d --checks=false {pgurl:1}",
> ```

Do you know how long this takes? I seem to recall it taking an hour or more.

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28064)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/tpcc.go, line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28064#-LIgy6XX4lT16NTCZO7b:-LIkuXbW7SD9WeyLMnBF:b-donflr) ([raw file](https://github.com/cockroachdb/cockroach/blob/41c1c48d799a4ed78208af3706ec965773ac96e6/pkg/cmd/roachtest/tpcc.go#L52)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Do you know how long this takes? I seem to recall it taking an hour or more. 
</blockquote></details>

I've been doing this for cdc testing. 1000 is long enough that I've been switching to something else while it runs, but certainly not an hour. Maybe 20 minutes.

FYI we added the checks in response to some bad fixtures that got generated once. They're disabled in the cdc roachtest because it really just needs some cluster traffic, but if we care about using the results from this as performance numbers, we may want to run them to make sure the data is valid.

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28064)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/tpcc.go, line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28064#-LIgy6XX4lT16NTCZO7b:-LIlN67wA_6N0DbVMmNt:btw1pok) ([raw file](https://github.com/cockroachdb/cockroach/blob/41c1c48d799a4ed78208af3706ec965773ac96e6/pkg/cmd/roachtest/tpcc.go#L52)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I've been doing this for cdc testing. 1000 is long enough that I've been switching to something else while it runs, but certainly not an hour. Maybe 20 minutes.

FYI we added the checks in response to some bad fixtures that got generated once. They're disabled in the cdc roachtest because it really just needs some cluster traffic, but if we care about using the results from this as performance numbers, we may want to run them to make sure the data is valid.
</blockquote></details>

I lied. 43m

**Review by nvb — COMMENTED** [review]
@petermattis I thought I had merged this, but I guess not. Going to merge now, at which point I'd like to get it hooked up to roachdash. Anything I can do to help with that?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28064#-:-LKvYX8x8qXd-JhxsW-M:b-vj6mza)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/tpcc.go, line 64 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28064#-LIgxrM71nfMyvicnNcX:-LKvYK-894iGiL4pgtnv:b-bbbymk) ([raw file](https://github.com/cockroachdb/cockroach/blob/41c1c48d799a4ed78208af3706ec965773ac96e6/pkg/cmd/roachtest/tpcc.go#L64)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Curious of the 3m ramp and 20m duration came from anywhere? 
</blockquote></details>

Nowhere in particular, it's just close to what I've been using in tpccbench. I'm going to bump it up to a more standard 5m and 1h run.

**Comment by petermattis** [comment]
> Going to merge now, at which point I'd like to get it hooked up to roachdash. Anything I can do to help with that?

Nothing comes to mind. I'll run a backfill of this test sometime this week (or this weekend).

**Review by nvb — COMMENTED** [review]
> I'll run a backfill of this test sometime this week (or this weekend).

Ok, thanks.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28064#-:-LKv_aKn7ZbHBuEvxRMd:b-a0cpk5)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/roachtest/tpcc.go, line 64 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28064#-LIgxrM71nfMyvicnNcX:-LKv_P56CaK1Pk-rHcQQ:bum49cr) ([raw file](https://github.com/cockroachdb/cockroach/blob/41c1c48d799a4ed78208af3706ec965773ac96e6/pkg/cmd/roachtest/tpcc.go#L64)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Nowhere in particular, it's just close to what I've been using in tpccbench. I'm going to bump it up to a more standard 5m and 1h run.
</blockquote></details>

Actually, going to leave this as is. 20m should be sufficient for a 3 node cluster with 1000 warehouses.

**Comment by knz** [comment]
@nvanbenschoten I think the merge got stuck and then you forgot about it ...

**Pull request closed without merging**
