### PR TITLE
deps: remove go-libedit

### LINKED ISSUE #105283: deps: remove the libedit dependency
It was deprecated in 23.1 so we can remove it in 23.2.

Epic: CRDB-28893

Jira issue: CRDB-28962

### PR DESCRIPTION
**Pull request by knz**
The libedit-based editor was deprecated in 23.1. We can remove it in 23.2. This simplifies the build system.

Release note: None
Fixes #105283.
Epic: CRDB-28893

### CODE REVIEW

**Review by rickystewart — APPROVED** [review]

**Review by rickystewart — CHANGES_REQUESTED** [review]
Looks like CI fails. Do you need to `rm -rf c-deps/libedit`?

**Comment by knz** [comment]
RFAL

**Review by rickystewart — APPROVED** [review]
Awesome!

**Comment by knz** [comment]
TFYR :)

bors r=rickystewart

**Pull request merged**
