### PR TITLE
sql: Enable diff tool for mysql

### LINKED ISSUE #64609: sql: Expand pg_catalog diff tool to compare information_schema against MySQL and Postgres
We built a diff tool that compared `pg_catalog` tables against CockroachDB and Postgres 13. CockroachDB's `information_schema` has parts that are compatible with MySQL or Postgres.

We should expand the diff tool to understand CockroachDB's `information_schema` differences compared to MySQL and Postgres.

### PR DESCRIPTION
**Pull request by mnovelodou**
Previously, diff tool could only compare cockroach with postgres
This was inadequate because we need to know how different we are
from mysql.information_schema
To address this, this patch change the way it connects to retrieve
data either from mysql and postgres

Release note: None

Fixes #64609

### CODE REVIEW

**Review by RichardJCai — CHANGES_REQUESTED** [review]
> Reviewed 7 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64910)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mnovelodou)

___
*[pkg/cmd/generate-metadata-tables/main.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64910#-Ma-ef1MDb3XB2KHj2GZ:-Ma-ef1NAbhwRwO533lv:b-tmvlcl) ([raw file](https://github.com/cockroachdb/cockroach/blob/d43771a20d18be72d663593f6a8d4cdcfb421cd3/pkg/cmd/generate-metadata-tables/main.go#L41)):*
> ```Go
> // Flags or command line arguments.
> var (
> 	flagAddress = flag.String("addr", "localhost:5432", "Postgres server address")
> ```

Technically this isn't just a postgres server address anymore right? Can be mysql?
___
*[pkg/cmd/generate-metadata-tables/main.go, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64910#-Ma-eiiy6HlPMrTD8Bxs:-Ma-eiiy6HlPMrTD8Bxt:bp217vy) ([raw file](https://github.com/cockroachdb/cockroach/blob/d43771a20d18be72d663593f6a8d4cdcfb421cd3/pkg/cmd/generate-metadata-tables/main.go#L42)):*
> ```Go
> var (
> 	flagAddress = flag.String("addr", "localhost:5432", "Postgres server address")
> 	flagUser    = flag.String("user", "postgres", "Postgres user")
> ```

RDMS user
___
*[pkg/cmd/generate-metadata-tables/rdbms/mysql.go, line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64910#-Ma-exyu9poZNU8NjGKb:-Ma-exyu9poZNU8NjGKc:b-nuhitt) ([raw file](https://github.com/cockroachdb/cockroach/blob/d43771a20d18be72d663593f6a8d4cdcfb421cd3/pkg/cmd/generate-metadata-tables/rdbms/mysql.go#L51)):*
> ```Go
> 	row := conn.QueryRow("SELECT version()")
> 	err = row.Scan(&version)
> 	return
> ```

Should change the function signature if the return is never actually used
___
*[pkg/sql/pg_metadata_test.go, line 1246 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64910#-Ma-fndqB-utb5yZ2Tem:-Ma-fndqB-utb5yZ2Ten:b4btssx) ([raw file](https://github.com/cockroachdb/cockroach/blob/d43771a20d18be72d663593f6a8d4cdcfb421cd3/pkg/sql/pg_metadata_test.go#L1246)):*
> ```Go
> 	}
> 
> 	var sum Summary
> ```

Just curious, why did this change from 
`sum := &summary{}` to `var sum Summary`

**Review by mnovelodou — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64910)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[pkg/cmd/generate-metadata-tables/main.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64910#-Ma-ef1MDb3XB2KHj2GZ:-Ma0EXq13qRTkLzSibj6:b-l5e45n) ([raw file](https://github.com/cockroachdb/cockroach/blob/d43771a20d18be72d663593f6a8d4cdcfb421cd3/pkg/cmd/generate-metadata-tables/main.go#L41)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Technically this isn't just a postgres server address anymore right? Can be mysql?
</blockquote></details>

Yes, nice catch, I changed it to RDBMS address
___
*[pkg/cmd/generate-metadata-tables/main.go, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64910#-Ma-eiiy6HlPMrTD8Bxs:-Ma0EaSCEat_hJQ3yLt2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d43771a20d18be72d663593f6a8d4cdcfb421cd3/pkg/cmd/generate-metadata-tables/main.go#L42)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

RDMS user
</blockquote></details>

Done.
___
*[pkg/cmd/generate-metadata-tables/rdbms/mysql.go, line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64910#-Ma-exyu9poZNU8NjGKb:-Ma0JQOWET5Q4zb1NTZo:b-tvygzk) ([raw file](https://github.com/cockroachdb/cockroach/blob/d43771a20d18be72d663593f6a8d4cdcfb421cd3/pkg/cmd/generate-metadata-tables/rdbms/mysql.go#L51)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Should change the function signature if the return is never actually used
</blockquote></details>

I am not getting your comment, this database Version is used and stored in the JSON files, this was one of the first requirements when starting the diff tool is to know the version of the RDBMS now.

Notice that these are not the function signature these are Named Return Values.
___
*[pkg/sql/pg_metadata_test.go, line 1246 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64910#-Ma-fndqB-utb5yZ2Tem:-Ma0JpRVBVwiUitzBFj1:bsjilys) ([raw file](https://github.com/cockroachdb/cockroach/blob/d43771a20d18be72d663593f6a8d4cdcfb421cd3/pkg/sql/pg_metadata_test.go#L1246)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Just curious, why did this change from 
`sum := &summary{}` to `var sum Summary`
</blockquote></details>

I didn't find any value of having as a pointer. This are just a couple of integers and the structure is not like a share resource that needs to be updated in multiple places.

**Review by RichardJCai — APPROVED** [review]
LGTM after nit comment

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64910#-:-Ma9VgnIEE3JKLgCTJf8:brkxe99)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mnovelodou and @RichardJCai)

___
*[pkg/cmd/generate-metadata-tables/rdbms/mysql.go, line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64910#-Ma-exyu9poZNU8NjGKb:-Ma9VKLO5gFdKl-I5eJV:bo08720) ([raw file](https://github.com/cockroachdb/cockroach/blob/d43771a20d18be72d663593f6a8d4cdcfb421cd3/pkg/cmd/generate-metadata-tables/rdbms/mysql.go#L51)):*
<details><summary><i>Previously, mnovelodou (Miguel Novelo) wrote…</i></summary><blockquote>

I am not getting your comment, this database Version is used and stored in the JSON files, this was one of the first requirements when starting the diff tool is to know the version of the RDBMS now.

Notice that these are not the function signature these are Named Return Values.
</blockquote></details>

Ah yes, I prefer if you still add the variables to the return statement just to make it clear.
`return version, err` should still work.

**Review by mnovelodou — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64910)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[pkg/cmd/generate-metadata-tables/rdbms/mysql.go, line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64910#-Ma-exyu9poZNU8NjGKb:-MaA--X_0f5cVW0SsbZS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d43771a20d18be72d663593f6a8d4cdcfb421cd3/pkg/cmd/generate-metadata-tables/rdbms/mysql.go#L51)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Ah yes, I prefer if you still add the variables to the return statement just to make it clear.
`return version, err` should still work. 
</blockquote></details>

Done.

**Pull request merged**
