### PR TITLE
storage: reuse process raft goroutines

### PR DESCRIPTION
**Pull request by petermattis**
Reuse process raft goroutines instead of creating a new goroutine for
every invocation of Replica.handleRaftReady. Using a pool of goroutines
reduces stack growth.

Use the process raft worker goroutines to parallelize Replica.tick
invocations. Replica.tick is intended to be fast, yet it indirectly
makes RocksDB calls which can be parallelized.

See #8544.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8574)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/store.go, line 2352 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8574#-KPIYjzncbr5-TuqIUfD:-KPIYjzncbr5-TuqIUfE:b9mvcfq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3959f249ceced20327dd06c9002b41e1dd315fbc/storage/store.go#L2352)):*
> ```Go
> 			}
> 		}()
> 	}
> ```

FYI, the theory here is that if we're processing a whole mess of replicas the stack for a goroutine will grow while we're quickly processing them and then shrink when it is idle. 

---

*[storage/store.go, line 2451 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8574#-KPIYtWxv-3--5SgwG11:-KPIYtWxv-3--5SgwG12:b-b8lh3w) ([raw file](https://github.com/cockroachdb/cockroach/blob/3959f249ceced20327dd06c9002b41e1dd315fbc/storage/store.go#L2451)):*
> ```Go
> 					}
> 				}
> 				wg.Wait()
> ```

I'm happy to leave this part out if we want to be conservative. It won't actually reduce the cpu for performing `Replica.tick`, but should reduce the wall time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8574)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[storage/store.go, line 2342 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8574#-KPInKX1BieSDWc1nsj4:-KPInKX1BieSDWc1nsj5:bx4b1e9) ([raw file](https://github.com/cockroachdb/cockroach/blob/3959f249ceced20327dd06c9002b41e1dd315fbc/storage/store.go#L2342)):*
> ```Go
> 	workQueue := make(chan func(), storeReplicaRaftReadyConcurrency)
> 	for i := 0; i < cap(workQueue); i++ {
> 		// We don't use stopper.RunWorker because these goroutines need to continue
> ```

Why not use `RunWorker` without selecting on `ShouldStop`?

---

*[storage/store.go, line 2451 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8574#-KPIYtWxv-3--5SgwG11:-KPInvXKNs4g9O3PXsZG:bun6sqo) ([raw file](https://github.com/cockroachdb/cockroach/blob/3959f249ceced20327dd06c9002b41e1dd315fbc/storage/store.go#L2451)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I'm happy to leave this part out if we want to be conservative. It won't actually reduce the cpu for performing `Replica.tick`, but should reduce the wall time.
</details>
Seems OK to leave it out for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8574)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[storage/store.go, line 2342 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8574#-KPInKX1BieSDWc1nsj4:-KPIz9NW7LwyZmpVbosU:b-ojkzw9) ([raw file](https://github.com/cockroachdb/cockroach/blob/3959f249ceced20327dd06c9002b41e1dd315fbc/storage/store.go#L2342)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Why not use `RunWorker` without selecting on `ShouldStop`?
</details>
I don't see much point in using `RunWorker`, though I do see a point in moving the goroutine creation inside the `RunWorker` call below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8574)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[storage/store.go, line 2342 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8574#-KPInKX1BieSDWc1nsj4:-KPJ0UTi5Njy3lI5XHEi:b-3v32kh) ([raw file](https://github.com/cockroachdb/cockroach/blob/3959f249ceced20327dd06c9002b41e1dd315fbc/storage/store.go#L2342)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I don't see much point in using `RunWorker`, though I do see a point in moving the goroutine creation inside the `RunWorker` call below.
</details>
OK, then this comment should explain that there's no point in using `RunWorker` - it is currently confusing because using RunWorker doesn't necessarily imply selecting on ShouldStop.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8574)*

**Comment by bdarnell** [comment]
:lgtm:

Does this show up in any benchmarks?

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[storage/store.go, line 2352 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8574#-KPIYjzncbr5-TuqIUfD:-KPJ89vcPkPQIhZqoPHE:b9d4vtk) ([raw file](https://github.com/cockroachdb/cockroach/blob/3959f249ceced20327dd06c9002b41e1dd315fbc/storage/store.go#L2352)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> FYI, the theory here is that if we're processing a whole mess of replicas the stack for a goroutine will grow while we're quickly processing them and then shrink when it is idle. 
</details>
Add a comment that we are reusing these goroutines because it's common for them to grow beyond the default stack size and it's cheaper to reuse a goroutine with a larger stack than to start a new goroutine from scratch. 

---

*[storage/store.go, line 2451 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8574#-KPIYtWxv-3--5SgwG11:-KPJ7g8gMBypGEvLik-h:b5ab1sw) ([raw file](https://github.com/cockroachdb/cockroach/blob/3959f249ceced20327dd06c9002b41e1dd315fbc/storage/store.go#L2451)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Seems OK to leave it out for now.
</details>
Yeah, I'd leave it out for now. Once spencer's caching change goes in we can evaluate whether it still makes sense to parallelize here. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8574#-:-KPJ875mjWE1F1BmoT_9:b-azgcu0)*

**Comment by petermattis** [comment]
No, the benchmarks appear unchanged. This was motivated by #8544 and the observation that we're spending a lot of time resizing stacks. My analysis there is that we always grow our `handleRaftReady` goroutine stacks from 2K -> 4K -> 8K and very often then to 16K and 32K. 

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[storage/store.go, line 2342 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8574#-KPInKX1BieSDWc1nsj4:-KPJmKFQVmaSe56hPqzM:b-3ckx5f) ([raw file](https://github.com/cockroachdb/cockroach/blob/3959f249ceced20327dd06c9002b41e1dd315fbc/storage/store.go#L2342)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> OK, then this comment should explain that there's no point in using `RunWorker` - it is currently confusing because using RunWorker doesn't necessarily imply selecting on ShouldStop.
</details>
I've reworked the comment.

---

*[storage/store.go, line 2352 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8574#-KPIYjzncbr5-TuqIUfD:-KPJmiRHItgIY76tvL3w:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3959f249ceced20327dd06c9002b41e1dd315fbc/storage/store.go#L2352)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Add a comment that we are reusing these goroutines because it's common for them to grow beyond the default stack size and it's cheaper to reuse a goroutine with a larger stack than to start a new goroutine from scratch. 
</details>
Done.

---

*[storage/store.go, line 2451 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8574#-KPIYtWxv-3--5SgwG11:-KPJmjs0PfJLLNmt3UZo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3959f249ceced20327dd06c9002b41e1dd315fbc/storage/store.go#L2451)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Yeah, I'd leave it out for now. Once spencer's caching change goes in we can evaluate whether it still makes sense to parallelize here. 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8574#-:-KPJlgjWa6gnH9hw6JpE:b99uq58)*

**Comment by bdarnell** [comment]
LGTM

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8574#-:-KPJp_de-bm67d8sQBk-:bnfp4nl)*

**Pull request merged**
