### PR TITLE
plpgsql: improve block formatting and unimplemented errors

### PR DESCRIPTION
**Pull request by DrewKimball**
#### plpgsql: misc formatting fixes

This commit makes a few fixes to formatting for PL/pgSQL routines in
preparation for nested blocks support, as well as a few misc fixes:
1. Blocks now print a semicolon after `END`. While the semicolon is
   optional for the root block, it is non-optional for nested blocks.
2. Block labels are now correctly displayed (previously, they were ignored).
3. An extra newline has been removed from the output of `SHOW CREATE FUNCTION`
   and `SHOW CREATE PROCEDURE`.
4. RAISE statements now capitalize the log level (e.g. `notice` -> `NOTICE`).

Informs #114775
Informs #112136

Release note: None

#### plpgsql: return errors for block labels

This commit adds a parse-time check that the labels on a PLpgSQL block
(if any) match. If the labels do not match, an expected syntax error is
returned. This commit also adds an "unimplemented" error for block labels.
Finally, errors that don't use formatting arguments have been moved to the
bottom of the file for clarity.

Informs #114775

Release note (bug fix): Incorrectly labeled PL/pgSQL blocks now return
an expected syntax error.

### CODE REVIEW

**Comment by DrewKimball** [comment]
The first commit is #117511.

**Review by rharding6373 — APPROVED** [review]
:lgtm: Great! Looks like there's a few more tests to clean up with the new formatting, but otherwise, LGTM!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117608#-:-Nntm70d5N-72_ZiIg8E:buw19uy)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by DrewKimball** [comment]
TFTR!

**Pull request merged**
