### PR TITLE
*: update protobuf-related deps

### PR DESCRIPTION
**Pull request by RaduBerinde**
This change updates the protobuf deps and makes various fixes. Most
fixes are related to new `XXX_` fields. In particular, the new fields
interfere with JSON marshaling and printing with `%v`.

Note that the new fields could be omitted but that is undesirable:
`XXX_NoUnkeyedLiteral` is a good idea and there would be a performance
cost associated with removing `XXX_sizecache`.

Some more info on important protobuf changes here:
https://groups.google.com/forum/#!topic/golang-nuts/F5xFHTfwRnY

Change lists:
https://github.com/gogo/protobuf/compare/1adfc126...936d59a5
https://github.com/google/go-genproto/compare/f676e0f3...a1fde740

Note that gogo/protobuf was forked under cockroachdb, and I made a fix
in our fork. This commit should be reviewed:
https://github.com/gogo/protobuf/commit/d0154bee94d99cf7d4064c2a26b6f413f1d0afd7

Informs #30774.

Release note: None

I ran some before/after tests with a KV workload, didn't see any difference beyond the usual variations.

### CODE REVIEW

**Review by tbg — APPROVED** [review]
:lgtm: but I had some minor comments on the gogoproto commit.

> Reviewed 90 of 90 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33329#-:-LUp6ZcGBgKrMcBRwXZM:b-blv0vm)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[Makefile, line 1087 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33329#-LUp5HPk8xPakXKrojUr:-LUp5HPk8xPakXKrojUs:b3kre) ([raw file](https://github.com/cockroachdb/cockroach/blob/814e3709cc36348f8a8053cdb2a9627c358948e7/Makefile#L1087)):*
> ```Makefile
> 	gofmt -s -w $(GO_SOURCES)
> 	touch $@
> 		# -e 's!cockroachdb/cockroach/pkg/(prometheus/client_model)!\1/go!g' \
> ```

?
___
*[pkg/roachpb/errors.go, line 530 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33329#-LUp5ycW16LPjyHvId1K:-LUp5ycW16LPjyHvId1L:bk4upef) ([raw file](https://github.com/cockroachdb/cockroach/blob/814e3709cc36348f8a8053cdb2a9627c358948e7/pkg/roachpb/errors.go#L530)):*
> ```Go
> 		"previous write with future timestamp %s within uncertainty interval `t <= %v`; "+
> 		"observed timestamps: %s",
> 		e.ReadTimestamp, e.ExistingTimestamp, e.MaxTimestamp, ts.String())
> ```

It's a shame that these aren't omitted when they're empty via some default stringer. Then again they probably are, but we have the default stringer disabled? Anyway, this is fine.
___
*[pkg/server/node.go, line 376 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33329#-LUp67kXDjJhQe09WmBl:-LUp67kXDjJhQe09WmBm:b48q513) ([raw file](https://github.com/cockroachdb/cockroach/blob/814e3709cc36348f8a8053cdb2a9627c358948e7/pkg/server/node.go#L376)):*
> ```Go
> 	ctx := n.AnnotateCtx(context.Background())
> 	if err := n.stores.OnClusterVersionChange(ctx, cv); err != nil {
> 		log.Fatal(ctx, errors.Wrapf(err, "updating cluster version to %v", cv))
> ```

What forced you to make these changes?

**Review by RaduBerinde — COMMENTED** [review]
Thank you! Updated.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33329#-:-LVF9LvNAkTT-pkyXqGN:b-85wlmy)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[Makefile, line 1087 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33329#-LUp5HPk8xPakXKrojUr:-LVF8Gkd4gXy_r-JXn3V:bgim6jn) ([raw file](https://github.com/cockroachdb/cockroach/blob/814e3709cc36348f8a8053cdb2a9627c358948e7/Makefile#L1087)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

?
</blockquote></details>

Oops, leftover, removed. We no longer need this one.
___
*[pkg/server/node.go, line 376 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/33329#-LUp67kXDjJhQe09WmBl:-LVF96ve0EBl-3Y28eSL:bc0mbur) ([raw file](https://github.com/cockroachdb/cockroach/blob/814e3709cc36348f8a8053cdb2a9627c358948e7/pkg/server/node.go#L376)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

What forced you to make these changes?
</blockquote></details>

I think that while I was fixing stuff I hit this panic and the message didn't look good (I don't think it has a Stringer implemented).

**Review by tbg — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/33329#-:-LVFIRYQ8JsKr_8WD4zJ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by tbg** [comment]
Hooray!

**Pull request merged**
