### PR TITLE
util/log: new config field `format-options`, custom timezones in log output

### LINKED ISSUE #39097: util/log: enable logging using the system TZ instead of UTC
Cockroach logs currently log in UTC time format.

An option to change this setting to log in system time would be very beneficial to users that have other logs using the same format.

The solution would allow a more simple debugging experience for folks with other application logs in system time.

Jira issue: CRDB-5594
Epic: CRDB-24406

### LINKED ISSUE #88741: logging: use human readable timestamp in JSON based log formats
Currently, the timestamp in the JSON based log messages is using epoch, which is surely parseable by computers but not so much by humans. More often then not, however, devops engs read through log files on the server, rather than on Splunk.

It would be good to give an option to use something like ISO 8601 instead of epoch. Something like `2022-09-26 13:28:45.123456789` is a good example. No `T` in the middle and no need to add the tz since we default to UTC.

gz#14106

Jira issue: CRDB-19901

Epic CRDB-21266

### PR DESCRIPTION
**Pull request by knz**
Fixes #39097.
Fixes #88741.

This PR introduces a framework to define per-format customization options.
See the individual commits for details. 

# JSON output changes

The following options for the `json` format are available:
- `datetime-format`: introduce a new `datetime` field
- `datetime-timezone`: configure the tz for the new `datetime` field
- `fluent-tag`: see format doc
- `tag-style`: see format doc
 
Example:

```yaml
file-defaults:
  format: json
  format-options: { datetime-format: rfc3339, datetime-timezone: America/New_York }
```

Results in entries like this:
```json
{...,"timestamp":"1685719746.454267736","datetime":"2023-06-02T11:29:06.454267736-04:00",...}
```

i.e. the `timestamp` field is unchanged for backward-compatibility; a new `datetime` field is introduced alongside it.

# Text output format changes

Format options are now also supported for `crdb-v1` and `crdb-v2`. In particular, the `timezone` option changes the time zone used to print out the timestamp columns.

For example:
```yaml
file-defaults:
   format: crdb-v2
   format-options: {timezone: america/new_york}
```

Example logging output:
```
I230606 12:43:01.553407-040000 1 1@cli/start.go:575 ⋮ [n?] 4  soft memory limit of Go runtime is set to 35 GiB
                       ^^^^^^^ indicates GMT-4 was used.
```

See the individual commits and the generated documentation for details.

### CODE REVIEW

**Review by Santamaura — COMMENTED** [review]
> Reviewed 3 of 9 files at r1, 1 of 3 files at r2, 3 of 5 files at r6, 1 of 7 files at r7, 3 of 3 files at r8, 5 of 10 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104265)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @knz)

___
*[`pkg/util/log/flags.go` line 262 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/104265#-NXVqjLDAM-fAPqnmZ_t:-NXVqjLDAM-fAPqnmZ_u:b-78y0v2) ([raw file](https://github.com/cockroachdb/cockroach/blob/38d3c33e5d88a9724aeb8e09da58e3bf1280c9fd/pkg/util/log/flags.go#L262)):*
> ```Go
> 		case *formatCrdbV2:
> 			t.colorProfile = nil
> 		}
> ```

When we are in this if condition, why do we need to do the switch statement if the result would be the same?
___
*[`pkg/util/log/format_crdb_v2.go` line 749 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/104265#-NXjzowkDShdG3MKCXrT:-NXjzowkDShdG3MKCXrU:bs6efp8) ([raw file](https://github.com/cockroachdb/cockroach/blob/38d3c33e5d88a9724aeb8e09da58e3bf1280c9fd/pkg/util/log/format_crdb_v2.go#L749)):*
> ```Go
> func (f entryDecoderV2Fragment) getTimestamp() (unixNano int64) {
> 	ts := string(f[v2DateTimeIdx])
> 	timeFormat := MessageTimeFormat
> ```

the way `timeFormat` is set is also done identically in `format_crdb_v1.go` should it be in some util function to avoid code duplication?

**Review by knz — COMMENTED** [review]
Thanks for the initial review - RFAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104265#-:-NXoHsHaCXKRKdYW8TDB:bjvcetk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @Santamaura)

___
*[`pkg/util/log/flags.go` line 262 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/104265#-NXVqjLDAM-fAPqnmZ_t:-NXo-Uv9CaVzBhndIY6t:b-dcondm) ([raw file](https://github.com/cockroachdb/cockroach/blob/38d3c33e5d88a9724aeb8e09da58e3bf1280c9fd/pkg/util/log/flags.go#L262)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

When we are in this if condition, why do we need to do the switch statement if the result would be the same?
</blockquote></details>

Because there are other formats than crdb-v1 and crdb-v2. For these other formats, we can't reset colorProfile to nil (the attribute doesn't even exist). 

(Note: this is a type switch, not a value switch.)
___
*[`pkg/util/log/format_crdb_v2.go` line 749 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/104265#-NXjzowkDShdG3MKCXrT:-NXo-j8U7YEheFlbsWuV:bvmsx4d) ([raw file](https://github.com/cockroachdb/cockroach/blob/38d3c33e5d88a9724aeb8e09da58e3bf1280c9fd/pkg/util/log/format_crdb_v2.go#L749)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

the way `timeFormat` is set is also done identically in `format_crdb_v1.go` should it be in some util function to avoid code duplication?
</blockquote></details>

Sure, why not. Done.

**Review by Santamaura — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r7, 5 of 10 files at r9, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104265#-:-NXqKm14B_gqCR5xlDI3:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier)

**Review by abarganier — APPROVED** [review]
:lgtm_strong: 

This is really excellent work. I feel like it gets rid of a solid amount of tech debt on top of delivering an important feature! 

Reducing the number of log format aliases in favor of format options, and nuking all that code (e.g. `formatJsonCompact`) was an especially nice surprise.

The config for the formatting options is great, it feels simple & extensible. I'm sure that will come in handy in the future.

Again, nice work on this! 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104265#-:-NXr-5Lu4S5BEx8MZJib:bypasjb)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @knz)

___
*[`-- commits` line 24 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/104265#-NXqrm5cDrGLgdhNv3u2):*
Good call on the escape hatch. This is a nice feature!

**Comment by knz** [comment]
TFYRs!

bors r=Santamaura,abargainier

**Pull request merged**
