### PR TITLE
storage: make RaftTruncatedState unreplicated

### PR DESCRIPTION
**Pull request by tbg**
This isn't 100% polished yet, but generally ready for review.

----

See #34287.

Today, Raft (or preemptive) snapshots include the past Raft log, that is,
log entries which are already reflected in the state of the snapshot.
Fundamentally, this is because we have historically used a replicated
TruncatedState.

TruncatedState essentially tells us what the first index in the log is
(though it also includes a Term). If the TruncatedState cannot diverge
across replicas, we *must* send the whole log in snapshots, as the first
log index must match what the TruncatedState claims it is.

The Raft log is typically, but not necessarily small. Log truncations are
driven by a queue and use a complex decision process. That decision process
can be faulty and even if it isn't, the queue could be held up. Besides,
even when the Raft log contains only very few entries, these entries may be
quite large (see SSTable ingestion during RESTORE).

All this motivates that we don't want to (be forced to) send the Raft log
as part of snapshots, and in turn we need the TruncatedState to be
unreplicated.

This change migrates the TruncatedState into unreplicated keyspace. It does
not yet allow snapshots to avoid sending the past Raft log, but that is a
relatively straightforward follow-up change.

VersionUnreplicatedRaftTruncatedState, when active, moves the truncated
state into unreplicated keyspace on log truncations.

The migration works as follows:

1. at any log position, the replicas of a Range either use the new
(unreplicated) key or the old one, and exactly one of them exists.

2. When a log truncation evaluates under the new cluster version, it
initiates the migration by deleting the old key. Under the old cluster
version, it behaves like today, updating the replicated truncated state.

3. The deletion signals new code downstream of Raft and triggers a write to
the new, unreplicated, key (atomic with the deletion of the old key).

4. Future log truncations don't write any replicated data any more, but
(like before) send along the TruncatedState which is written downstream of
Raft atomically with the deletion of the log entries. This actually uses
the same code as 3. What's new is that the truncated state needs to be
verified before replacing a previous one. If replicas disagree about their
truncated state, it's possible for replica X at FirstIndex=100 to apply a
truncated state update that sets FirstIndex to, say, 50 (proposed by a
replica with a "longer" historical log). In that case, the truncated state
update must be ignored (this is straightforward downstream-of-Raft code).

5. When a split trigger evaluates, it seeds the RHS with the legacy key iff
the LHS uses the legacy key, and the unreplicated key otherwise. This makes
sure that the invariant that all replicas agree on the state of the
migration is upheld.

6. When a snapshot is applied, the receiver is told whether the snapshot
contains a legacy key. If not, it writes the truncated state (which is part
of the snapshot metadata) in its unreplicated version. Otherwise it doesn't
have to do anything (the range will migrate later).

The following diagram visualizes the above. Note that it abuses sequence
diagrams to get a nice layout; the vertical lines belonging to NewState and
OldState don't imply any particular ordering of operations.

```
┌────────┐                            ┌────────┐
│OldState│                            │NewState│
└───┬────┘                            └───┬────┘
   │                        Bootstrap under old version
   │ <─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─
─ ─
   │                                     │
   │                                     │     Bootstrap under new version
   │                                     │ <─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─
─ ─
   │                                     │
   │─ ─ ┐
   │    | Log truncation under old version
   │< ─ ┘
   │                                     │
   │─ ─ ┐                                │
   │    | Snapshot                       │
   │< ─ ┘                                │
   │                                     │
   │                                     │─ ─ ┐
   │                                     │    | Snapshot
   │                                     │< ─ ┘
   │                                     │
   │   Log truncation under new version  │
   │ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─>│
   │                                     │
   │                                     │─ ─ ┐
   │                                     │    | Log truncation under new version
   │                                     │< ─ ┘
   │                                     │
   │                                     │─ ─ ┐
   │                                     │    | Log truncation under old version
   │                                     │< ─ ┘ (necessarily running new binary)
```

Release note: None

### CODE REVIEW

**Review by bdarnell — COMMENTED** [review]
Generally looks good aside from the unfinished test.

> Reviewed 11 of 11 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 29 of 30 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34660#-:-LY3sewO22cezfuyq2yd:b7ze4m5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @tbg)

___
*[pkg/server/version_cluster_test.go, line 207 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/34660#-LY3HJfs7Wk9jNNhYeVJ:-LY3HJfs7Wk9jNNhYeVK:b-b3jbun) ([raw file](https://github.com/cockroachdb/cockroach/blob/c529afc343048b86a2c44d9f5add50bfc5f9fb32/pkg/server/version_cluster_test.go#L207)):*
> ```Go
> 	oldVersionS := oldVersion.String()
> 	newVersionS := cluster.VersionByKey(cluster.VersionUnreplicatedRaftTruncatedState).String()
> 	_ = newVersionS
> ```

Obsolete?
___
*[pkg/server/version_cluster_test.go, line 215 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/34660#-LY3HgIjBKkLNNLdb4Ms:-LY3HgIjBKkLNNLdb4Mt:b-9kqz8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c529afc343048b86a2c44d9f5add50bfc5f9fb32/pkg/server/version_cluster_test.go#L215)):*
> ```Go
> 		{oldVersionS, newVersionS},
> 		{oldVersionS, newVersionS},
> ```

Remove this blank line. This array doesn't seem to match the comment (unless I'm confused about how this test harness works). 
___
*[pkg/server/version_cluster_test.go, line 241 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/34660#-LY3HxN9714s0YbZ4zJF:-LY3HxN9714s0YbZ4zJG:b-xll8zz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c529afc343048b86a2c44d9f5add50bfc5f9fb32/pkg/server/version_cluster_test.go#L241)):*
> ```Go
> 
> 	scatter := func() {
> 		return // HACK
> ```

Don't forget this. I'll stop reviewing this test here since it seems unfinished.
___
*[pkg/settings/cluster/cockroach_versions.go, line 74 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/34660#-LY3IRCc2NMbW916Ixmf:-LY3IRCc2NMbW916Ixmg:behee8q) ([raw file](https://github.com/cockroachdb/cockroach/blob/c529afc343048b86a2c44d9f5add50bfc5f9fb32/pkg/settings/cluster/cockroach_versions.go#L74)):*
> ```Go
> 	VersionLazyTxnRecord
> 	VersionSequencedReads
> 	// VersionUnreplicatedRaftTruncatedState, when active, moves the truncated
> ```

I think this list should just be the list of constant declarations; it's not the place for comments about migrations. I'd probably put this in the storage package on handleTruncatedStateBelowRaft.
___
*[pkg/storage/replica_raftstorage.go, line 498 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/34660#-LY3Yjwn3f5UIavMy_uL:-LY3Yjwn3f5UIavMy_uM:b-gpgka) ([raw file](https://github.com/cockroachdb/cockroach/blob/c529afc343048b86a2c44d9f5add50bfc5f9fb32/pkg/storage/replica_raftstorage.go#L498)):*
> ```Go
> 	//
> 	// See the comment on VersionUnreplicatedRaftTruncatedState for details.
> 	UsesLegacyTruncatedState bool
> ```

It's confusing that you use "legacy" for this bool but "unreplicated" for the bool in the proto. That creates a link in my mind that unreplicated is the legacy mode when it's the reverse. Since we need default=false for the proto, I'd stick with "UsesUnreplicatedTruncatedState" here.
___
*[pkg/storage/batcheval/cmd_truncate_log.go, line 88 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/34660#-LY3mndb6VQ5iRn-YAVz:-LY3mndb6VQ5iRn-YAW-:b-o1yy22) ([raw file](https://github.com/cockroachdb/cockroach/blob/c529afc343048b86a2c44d9f5add50bfc5f9fb32/pkg/storage/batcheval/cmd_truncate_log.go#L88)):*
> ```Go
> 	//
> 	// TODO(tbg): think about synthesizing a valid term. Can we use the next
> 	// existing entry's term?
> ```

The term and index must match; raft won't be happy if you use index `i` but the term of index `i+1`. You might be able to get clever (I think the first entry after a term change is always empty, so if `i+1` is non-empty it's safe to project its term backwards one entry), but that's probably not a great idea. I'm fine for now with just skipping truncations in this case unless we make further changes to truncation that make it more common.

Or if the leader has already truncated to index `i`, maybe we just truncate the whole cluster at that point (regardless of the index in the request)? I haven't paged in where this index is coming from; why would the leader be processing a truncation that is behind its own index?
___
*[pkg/storage/batcheval/cmd_truncate_log.go, line 108 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/34660#-LY3qZ_-6jlROLiJXPUP:-LY3qZ_-6jlROLiJXPUQ:b4tlayp) ([raw file](https://github.com/cockroachdb/cockroach/blob/c529afc343048b86a2c44d9f5add50bfc5f9fb32/pkg/storage/batcheval/cmd_truncate_log.go#L108)):*
> ```Go
> 	// still using the legacy truncated state key). On followers, this can in
> 	// principle be off either way, though in practice we expect followers to
> 	// have shorter logs than the leaseholder (see #34287).
> ```

s/shorter logs/logs that are no longer than/

The common case remains that everything is equal. 
___
*[pkg/storage/stateloader/initial.go, line 58 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/34660#-LY3qwso0lzVfDFMGNPX:-LY3qwso0lzVfDFMGNPY:b-s4pgq5) ([raw file](https://github.com/cockroachdb/cockroach/blob/c529afc343048b86a2c44d9f5add50bfc5f9fb32/pkg/storage/stateloader/initial.go#L58)):*
> ```Go
> 	txnSpanGCThreshold hlc.Timestamp,
> 	activeVersion roachpb.Version,
> 	useLegacyTruncatedState bool, // see VersionUnreplicatedRaftTruncatedState
> ```

Same comment as before regarding legacy vs unreplicated.

Maybe make an enum instead of a bool so you don't have to comment at all the call sites?
___
*[pkg/storage/stateloader/stateloader.go, line 132 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/34660#-LY3rbOG0uoMPcZ3S2AG:-LY3rbOG0uoMPcZ3S2AH:b-fztimf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c529afc343048b86a2c44d9f5add50bfc5f9fb32/pkg/storage/stateloader/stateloader.go#L132)):*
> ```Go
> 	eng engine.ReadWriter,
> 	state storagepb.ReplicaState,
> 	useLegacyTruncatedState bool, // see VersionUnreplicatedRaftTruncatedState
> ```

Same comment as in initial.go.

**Review by tbg — COMMENTED** [review]
TFTR, PTAL!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34660#-:-LYRfa5t-bYApqwcAdle:b-qs6e2f)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @tbg)

___
*[pkg/server/version_cluster_test.go, line 207 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/34660#-LY3HJfs7Wk9jNNhYeVJ:-LYRZUL182Z8GPiHP_zD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c529afc343048b86a2c44d9f5add50bfc5f9fb32/pkg/server/version_cluster_test.go#L207)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Obsolete?
</blockquote></details>

Done.
___
*[pkg/server/version_cluster_test.go, line 215 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/34660#-LY3HgIjBKkLNNLdb4Ms:-LYRe6Y-3sj6LP9zvzH4:b-amr0gt) ([raw file](https://github.com/cockroachdb/cockroach/blob/c529afc343048b86a2c44d9f5add50bfc5f9fb32/pkg/server/version_cluster_test.go#L215)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Remove this blank line. This array doesn't seem to match the comment (unless I'm confused about how this test harness works). 
</blockquote></details>

Done. The comments were out of sync with what the test is now doing.
___
*[pkg/server/version_cluster_test.go, line 241 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/34660#-LY3HxN9714s0YbZ4zJF:-LYRWISP3BqKA3ZtkL8n:b-emi4dd) ([raw file](https://github.com/cockroachdb/cockroach/blob/c529afc343048b86a2c44d9f5add50bfc5f9fb32/pkg/server/version_cluster_test.go#L241)):*
Done. Amazingly this didn't turn up a new failure mode (that test helped me find a bunch of other errors before PR though).

> 1082 runs so far, 0 failures, over 10m40s
___
*[pkg/settings/cluster/cockroach_versions.go, line 74 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/34660#-LY3IRCc2NMbW916Ixmf:-LYRWUTQ7oFaoGrervdu:b-9hnwmo) ([raw file](https://github.com/cockroachdb/cockroach/blob/c529afc343048b86a2c44d9f5add50bfc5f9fb32/pkg/settings/cluster/cockroach_versions.go#L74)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I think this list should just be the list of constant declarations; it's not the place for comments about migrations. I'd probably put this in the storage package on handleTruncatedStateBelowRaft.
</blockquote></details>

Are you sure that's better? I personally would love a high level explanation with all of these migrations, especially since this one is linked to from so many places.
___
*[pkg/storage/replica_raftstorage.go, line 498 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/34660#-LY3Yjwn3f5UIavMy_uL:-LYRXwpu6TdWmKTFYtjg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c529afc343048b86a2c44d9f5add50bfc5f9fb32/pkg/storage/replica_raftstorage.go#L498)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

It's confusing that you use "legacy" for this bool but "unreplicated" for the bool in the proto. That creates a link in my mind that unreplicated is the legacy mode when it's the reverse. Since we need default=false for the proto, I'd stick with "UsesUnreplicatedTruncatedState" here.
</blockquote></details>

Done.
___
*[pkg/storage/batcheval/cmd_truncate_log.go, line 108 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/34660#-LY3qZ_-6jlROLiJXPUP:-LYRZ6R15Q4otttlbyjS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c529afc343048b86a2c44d9f5add50bfc5f9fb32/pkg/storage/batcheval/cmd_truncate_log.go#L108)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

s/shorter logs/logs that are no longer than/

The common case remains that everything is equal. 
</blockquote></details>

Done.
___
*[pkg/storage/stateloader/initial.go, line 58 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/34660#-LY3qwso0lzVfDFMGNPX:-LYRdqdI3BcbNhMttT80:b3ymcr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c529afc343048b86a2c44d9f5add50bfc5f9fb32/pkg/storage/stateloader/initial.go#L58)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Same comment as before regarding legacy vs unreplicated.

Maybe make an enum instead of a bool so you don't have to comment at all the call sites?
</blockquote></details>

Good call on the enum, done.
___
*[pkg/storage/stateloader/stateloader.go, line 132 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/34660#-LY3rbOG0uoMPcZ3S2AG:-LYRdsgL47AUamPQ0R35:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c529afc343048b86a2c44d9f5add50bfc5f9fb32/pkg/storage/stateloader/stateloader.go#L132)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Same comment as in initial.go.
</blockquote></details>

Done.

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34660)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell)

___
*[pkg/storage/batcheval/cmd_truncate_log.go, line 88 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/34660#-LY3mndb6VQ5iRn-YAVz:-LYRiBWa-6y9O7wNvM4h:be7s0le) ([raw file](https://github.com/cockroachdb/cockroach/blob/c529afc343048b86a2c44d9f5add50bfc5f9fb32/pkg/storage/batcheval/cmd_truncate_log.go#L88)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

The term and index must match; raft won't be happy if you use index `i` but the term of index `i+1`. You might be able to get clever (I think the first entry after a term change is always empty, so if `i+1` is non-empty it's safe to project its term backwards one entry), but that's probably not a great idea. I'm fine for now with just skipping truncations in this case unless we make further changes to truncation that make it more common.

Or if the leader has already truncated to index `i`, maybe we just truncate the whole cluster at that point (regardless of the index in the request)? I haven't paged in where this index is coming from; why would the leader be processing a truncation that is behind its own index?
</blockquote></details>

The index is coming from the raft log queue, i.e. almost always from the leaseholder's own Raft instance. I agree that this is mostly a non-issue, we're not planning any changes that make this a common occurrence (or an occurrence at all, really). Typically with what we're planning followers after having received a snapshot will have a shorter log than the leaseholder, but this check doesn't care.

**Review by bdarnell — APPROVED** [review]
> Reviewed 30 of 30 files at r10.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34660)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @tbg)

___
*[pkg/settings/cluster/cockroach_versions.go, line 74 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/34660#-LY3IRCc2NMbW916Ixmf:-LYTARgw055Q4S58qlCR:bnf1ice) ([raw file](https://github.com/cockroachdb/cockroach/blob/c529afc343048b86a2c44d9f5add50bfc5f9fb32/pkg/settings/cluster/cockroach_versions.go#L74)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Are you sure that's better? I personally would love a high level explanation with all of these migrations, especially since this one is linked to from so many places.
</blockquote></details>

This list is where I look for "which release included VersionBitArrayColumns", so I like having it compact enough that I can see that the constant is between Version2_0 and Version2_1. I agree it might be nice to use something in this package for comments like this. Maybe put it on the entry in versionsSingleton? (which already has a one-line comment with a link for each migration). 
___
*[pkg/storage/stateloader/stateloader.go, line 123 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/34660#-LYTCrXb74P7YQrW07V7:-LYTCrXb74P7YQrW07V8:b-xeux4o) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d67d68f8a5c597ab5cb9b555727b6c6165d0d23/pkg/storage/stateloader/stateloader.go#L123)):*
> ```Go
> const (
> 	// UseReplicatedTruncatedState means use the legacy (replicated) key.
> 	UseReplicatedTruncatedState TruncatedStateType = iota
> ```

Nit: `TruncatedStateReplicated` and `TruncatedStateUnreplicated`? Maybe even `TruncatedStateLegacyReplicated` to make it clear which one is older.

**Review by tbg — COMMENTED** [review]
TFTR, comments addressed!

Thanks to megacheck/staticcheck I found a bug in the test -- it wasn't actually verifying that the old truncated state disappeared up but simply exited with a nil error. In fact the old truncated state didn't disappear reliably because that needed log truncations. Changed the test to force a log truncation instead. This has surived 5 minutes under stress without a failure, so I'm going to go ahead and merge.

bors r=bdarnell

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34660#-:-LYTTNVwBX6xZaHZmadR:bmln7u2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell)

___
*[pkg/settings/cluster/cockroach_versions.go, line 74 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/34660#-LY3IRCc2NMbW916Ixmf:-LYTHEW7Effzz5hnZQsT:b-fznogt) ([raw file](https://github.com/cockroachdb/cockroach/blob/c529afc343048b86a2c44d9f5add50bfc5f9fb32/pkg/settings/cluster/cockroach_versions.go#L74)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This list is where I look for "which release included VersionBitArrayColumns", so I like having it compact enough that I can see that the constant is between Version2_0 and Version2_1. I agree it might be nice to use something in this package for comments like this. Maybe put it on the entry in versionsSingleton? (which already has a one-line comment with a link for each migration). 
</blockquote></details>

Good idea, done.

**Review by tbg — COMMENTED** [review]
bors r-

Branch shuffling wasn't done yet.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34660#-:-LYTU6lL7b6zTa8ysRYf:b-76xcei)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell)

**Review by tbg — COMMENTED** [review]
bors r=bdarnell

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34660#-:-LYTUEnWCAPrVKV5gmWS:be6c9ya)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell)

**Pull request merged**
