### PR TITLE
sql: deflake distsql_automatic_stats logic test

### LINKED ISSUE #99751: sql: flake with distsql_automatic_stats
Seen on [this](https://teamcity.cockroachdb.com/viewLog.html?buildId=9282206&buildTypeId=Cockroach_BazelEssentialCi) CI run on staging.
```
Failed
=== RUN   TestTenantLogic_distsql_automatic_stats
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/8808ff176222b1d4cd31f20d03de82b0/logTestTenantLogic_distsql_automatic_stats1986543448
    test_log_scope.go:79: use -show-logs to present logs inline
[01:21:48] setting distsql_workmem='27352B';
[01:21:48] setting distsql_workmem='27352B';
    logic.go:2829: 
         
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/4242/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/logictestccl/tests/3node-tenant/3node-tenant_test_/3node-tenant_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/distsql_automatic_stats:25: SELECT DISTINCT ON (column_names) statistics_name, column_names, row_count, distinct_count, null_count
        FROM [SHOW STATISTICS FOR TABLE data] ORDER BY column_names, created DESC
        expected:
            statistics_name  column_names  row_count  distinct_count  null_count
            __auto__         {a}           1000       10              0
            __auto__         {a,b}         1000       100             0
            __auto__         {a,b,c}       1000       1000            0
            __auto__         {b}           1000       10              0
            __auto__         {c}           1000       10              0
            __auto__         {d}           1000       1               1000
            
        but found (query options: "colnames,retry") :
            statistics_name  column_names  row_count  distinct_count  null_count
```

Jira issue: CRDB-26052

### LINKED ISSUE #100243: sql: formatting of CREATE TABLE AS with storage parameters is wrong
We're putting the storage parameters after the as-clause, when they should be before:

```
demo@127.0.0.1:26257/defaultdb> CREATE TABLE a (a INT);
CREATE TABLE

Time: 3ms total (execution 3ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> CREATE TABLE b WITH (fillfactor = 100) AS SELECT * FROM a;
NOTICE: storage parameter "fillfactor" is ignored
CREATE TABLE AS

Time: 40ms total (execution 40ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> SELECT prettify_statement('CREATE TABLE b WITH (fillfactor = 100) AS SELECT * FROM a');
                     prettify_statement
-------------------------------------------------------------
  CREATE TABLE b AS SELECT * FROM a WITH (fillfactor = 100)

(1 row)

Time: 2ms total (execution 2ms / network 0ms)
```

Jira issue: CRDB-26318

### PR DESCRIPTION
**Pull request by michae2**
**sql: fix formatting of CREATE TABLE AS with storage parameters**

We were placing the storage parameters in the wrong place when formatting `CREATE TABLE AS` statements.

Fixes: #100243

Epic: None

Release note: None

**sql: deflake distsql_automatic_stats logic test**

Now that automatic stats are disabled for system tables in logic tests, `distsql_automatic_stats` was opening the floodgates with its first `SET CLUSTER SETTING sql.stats.automatic_collection.enabled = true`. With this enabled, the automatic stats refresher was executing `CREATE STATISTICS` for every system table, one at a time, often taking longer than the 45s logic test retry limit to get to the user-defined table we really care about.

Instead of using the cluster setting, change `distsql_automatic_stats` to use the per-table setting.

Fixes: #99751

Epic: None

Release note: None

### CODE REVIEW

**Comment by michae2** [comment]
Not sure how important it is, but we might consider backporting the first commit to v22.2 and v22.1 as well. WDYT?

**Review by rytaft — APPROVED** [review]
:lgtm: great find! Thanks for fixing this!

> Reviewed 3 of 3 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100246#-:-NRpKbPZCk72KSERtaxi:bu9rb8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[`pkg/sql/logictest/testdata/logic_test/distsql_automatic_stats` line 9 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100246#-NRpKAFlCK-Qua9PIsdQ:-NRpKAFlCK-Qua9PIsdR:beei1td) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c3116f26ee0672431498348714ff54a08e66b83/pkg/sql/logictest/testdata/logic_test/distsql_automatic_stats#L9)):*
> ```
> # Enable automatic stats for this table.
> statement ok
> CREATE TABLE data (a INT, b INT, c FLOAT, d DECIMAL, PRIMARY KEY (a, b, c), INDEX d_idx (d)) WITH (sql_stats_automatic_collection_enabled = true)
> ```

won't this trigger automatic collection on the empty table? 
___
*[`pkg/sql/logictest/testdata/logic_test/distsql_automatic_stats` line 176 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100246#-NRpJtqm6-JWC7sl1Jd4:-NRpJtqm6-JWC7sl1Jd5:b-7xx6xj) ([raw file](https://github.com/cockroachdb/cockroach/blob/2af36b80e744f1b43c25d53b2b33d9d611fa49c8/pkg/sql/logictest/testdata/logic_test/distsql_automatic_stats#L176)):*
> ```
> # Test user-defined schemas.
> 
> # Disable automatic stats
> ```

nit: leave this comment in so we know what's going on

**Comment by rytaft** [comment]
> we might consider backporting the first commit to v22.2 and v22.1 as well. WDYT?

Sure

**Review by yuzefovich — APPROVED** [review]
Nice! :lgtm:

Probably I wouldn't bother with 22.1 backport - it's almost at the end of non-security bug fixes.

> Reviewed 3 of 3 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100246#-:-NRpSSjy9fOtQE5TyEQc:bworabh)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @michae2)

___
*[`pkg/sql/logictest/testdata/logic_test/distsql_automatic_stats` line 3 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100246#-NRpS-3P4kNybipk28WW:-NRpS-3P4kNybipk28WX:b-bnl15k) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c3116f26ee0672431498348714ff54a08e66b83/pkg/sql/logictest/testdata/logic_test/distsql_automatic_stats#L3)):*
> ```
> # LogicTest: !metamorphic-batch-sizes
> 
> # TODO(yuzefovich): at the moment the tests below that assert a particular set
> ```

nit: remove this TODO.

**Review by michae2 — COMMENTED** [review]
Thanks! I will backport both commits to v23.1 and just the first to v22.2.

bors r=rytaft,yuzefovich

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100246#-:-NRshqm6A3TdQrwW8277:b-cfpew6)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @rytaft and @yuzefovich)

___
*[`pkg/sql/logictest/testdata/logic_test/distsql_automatic_stats` line 3 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100246#-NRpS-3P4kNybipk28WW:-NRsi2y542IlwZLd6oCF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c3116f26ee0672431498348714ff54a08e66b83/pkg/sql/logictest/testdata/logic_test/distsql_automatic_stats#L3)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: remove this TODO.
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/distsql_automatic_stats` line 9 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100246#-NRpKAFlCK-Qua9PIsdQ:-NRsi3rz5aJ3om0JKRxf:b-15lzpz) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c3116f26ee0672431498348714ff54a08e66b83/pkg/sql/logictest/testdata/logic_test/distsql_automatic_stats#L9)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

won't this trigger automatic collection on the empty table? 
</blockquote></details>

Yes, possibly, but then I think automatic collection will happen again after the insert. (This is how the test was before, too: we enabled automatic stats before creating the table.)
___
*[`pkg/sql/logictest/testdata/logic_test/distsql_automatic_stats` line 176 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/100246#-NRpJtqm6-JWC7sl1Jd4:-NRsiI5g14kQ3Sjx3MKi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2af36b80e744f1b43c25d53b2b33d9d611fa49c8/pkg/sql/logictest/testdata/logic_test/distsql_automatic_stats#L176)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: leave this comment in so we know what's going on
</blockquote></details>

Done.

**Pull request merged**
