### PR TITLE
sql: allow arrays to be compared with greater and less than operators

### PR DESCRIPTION
**Pull request by rohany**
Release justification: low risk change to existing functionality

Release note (sql change): This PR allows for arrays to be compared
using the `<`, `<=`, `>`, and `>=` operations.

### CODE REVIEW

**Comment by rohany** [comment]
cc @jordanlewis for thoughts on 20.1 or 20.2

**Comment by rohany** [comment]
It seems like adding support for `ORDER BY` array would just take deleting a check in planning now.

**Review by otan — APPROVED** [review]
lgtm, i think it'd be safe for 20.1 as it's new functionality that wasn't implemented before, as long as it's been tested before!

**Comment by rohany** [comment]
bors r=otan

**Comment by yuzefovich** [comment]
This was canceled because of my PR.

bors r=otan

**Comment by rohany** [comment]
bors r=otan

**Comment by rohany** [comment]
Flake

bors r+

**Pull request merged**
