### PR TITLE
scexec: refactor schema changer job update

### PR DESCRIPTION
**Pull request by postamar**
This PR rebases https://github.com/cockroachdb/cockroach/pull/83724 on top of a few commits which refactor the schema changer job update machinery.

### CODE REVIEW

**Comment by postamar** [comment]
Naturally, my own commits are also heavily inspired by https://github.com/cockroachdb/cockroach/pull/83724 . I also couldn't find a way to test this since the declarative schema changer cannot be enabled in explicit transactions yet.

**Comment by postamar** [comment]
I rewrote the planner in a different way; @ajwerner consider this an instance of async-pair-programming :)

**Review by ajwerner — APPROVED** [review]
:lgtm: Thanks for doing this! My PR was definitely getting too complex. 

One thing I'm interested in seeing, but definitely don't want to block this PR on is an invariant check that if we drop a descriptor that no other element which isn't also absent references it.

> Reviewed 4 of 4 files at r1, 4 of 4 files at r2, 5 of 5 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83784#-:-N6DKKyLErO43WkZVl6A:b-h0cij5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @postamar)

___
*[`pkg/sql/schemachanger/scexec/exec_mutation.go` line 346 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/83784#-N6DJg_R5XvX9JHQRS7s:-N6DJg_R5XvX9JHQRS7t:b-d6ny41) ([raw file](https://github.com/cockroachdb/cockroach/blob/80974fc79bd4fd64a91e60f5039567e5365da007/pkg/sql/schemachanger/scexec/exec_mutation.go#L346)):*
> ```Go
> 				if filtered.Len() < len(md.Payload.DescriptorIDs) {
> 					s.updatedPayload().DescriptorIDs = filtered.Ordered()
> 				}
> ```

just add a set difference function?



_Code quote:_
```Go
				var filtered catalog.DescriptorIDSet
				for _, descID := range md.Payload.DescriptorIDs {
					if update.descriptorIDsToRemove.Contains(descID) {
						continue
					}
					filtered.Add(descID)
				}
				if filtered.Len() < len(md.Payload.DescriptorIDs) {
					s.updatedPayload().DescriptorIDs = filtered.Ordered()
				}
```

**Review by postamar — COMMENTED** [review]
Thanks for the review!

> One thing I'm interested in seeing, but definitely don't want to block this PR on is an invariant check that if we drop a descriptor that no other element which isn't also absent references it.

More generally, we should assert that:
- each element with forward references also is responsible for its back-references;
- the drop rules in `dep_drop.go` are exhaustive.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83784#-:-N6DVssr0h6c2BcE_yFH:b-eu9at9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @postamar)

___
*[`pkg/sql/schemachanger/scexec/exec_mutation.go` line 346 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/83784#-N6DJg_R5XvX9JHQRS7s:-N6Da_fn-Yu-gu29O_4j:bmixn5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/80974fc79bd4fd64a91e60f5039567e5365da007/pkg/sql/schemachanger/scexec/exec_mutation.go#L346)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

just add a set difference function?
</blockquote></details>

Done. I removed it and forgot to try to add it back.

**Review by ajwerner — APPROVED** [review]
LGTM, thanks again

**Pull request merged**
