### PR TITLE
geo: store BoundingBox on each geo object

### PR DESCRIPTION
**Pull request by otan**
This PR stores the bounding box on each geo object. This is stored by
default, since we now store the whole proto.

We special case empties to store nil BoundingBoxes.

Release note: None

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49196)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[pkg/geo/geopb/geopb.proto, line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49196#-M7jBQ4gB9e9FRkRIPYd:-M7jBQ4gB9e9FRkRIPYe:bqx9dcg) ([raw file](https://github.com/cockroachdb/cockroach/blob/775557cd79d3d4e0a6f0c2df4c770293a6435b0c/pkg/geo/geopb/geopb.proto#L45)):*
> ```protobuf
>   Shape shape = 3;
>   // BoundingBox is the bounding box of the SpatialObject.
>   BoundingBox bounding_box = 4;
> ```

Are we going to use this to accelerate predicates like ST_Intersects, or is there some other motivation?

**Comment by otan** [comment]
___
*[pkg/geo/geopb/geopb.proto, line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49196#-M7jBQ4gB9e9FRkRIPYd:-M7jKTlL9WUjXUSgY-a_:buewstf) ([raw file](https://github.com/cockroachdb/cockroach/blob/775557cd79d3d4e0a6f0c2df4c770293a6435b0c/pkg/geo/geopb/geopb.proto#L45)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Are we going to use this to accelerate predicates like ST_Intersects, or is there some other motivation?
</blockquote></details>

Yep, that and perhaps even https://docs.google.com/document/d/1zOivG20xCdHi0CqWu-7Ws6e3yFk8NUFEKwyDwgDLjRg/edit

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49196)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/geo/geopb/geopb.proto, line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49196#-M7jBQ4gB9e9FRkRIPYd:-M7rQH5p9kj7lbqhIpVv:b-142mpv) ([raw file](https://github.com/cockroachdb/cockroach/blob/775557cd79d3d4e0a6f0c2df4c770293a6435b0c/pkg/geo/geopb/geopb.proto#L45)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

Yep, that and perhaps even https://docs.google.com/document/d/1zOivG20xCdHi0CqWu-7Ws6e3yFk8NUFEKwyDwgDLjRg/edit
</blockquote></details>

I think the latter does not need storing the bounding box. The indexing code would
- compute the covering of the original shape, C1
- compute the bounding box and the covering of the bounding box, C2
if C2 is "smaller" than C1, use C2 for indexing, else use C1.

The performance is enough motivation to store these.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 5 of 11 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49196#-:-M7sxzHi9AXlYIu6kTgS:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/geo/bbox.go, line 57 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49196#-M7sxFuY67NJVtS1Ld3Y:-M7sxFuY67NJVtS1Ld3Z:bhdco9r) ([raw file](https://github.com/cockroachdb/cockroach/blob/be4e4786f7a5dffc36ab7b65ecfe74bf300e72c3/pkg/geo/bbox.go#L57)):*
> ```Go
> 	case *geom.GeometryCollection:
> 		for i := 0; i < g.NumGeoms(); i++ {
> 			innerBBox, err := BoundingBoxFromGeom(g.Geom(i))
> ```

innerBBox sounds like a new geometric concept.
How about `shapeBBox`?
___
*[pkg/geo/geopb/bbox.go, line 15 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49196#-M7sw-Sq8pNXDzJzsbod:-M7sw-Sq8pNXDzJzsboe:b-fn6sjb) ([raw file](https://github.com/cockroachdb/cockroach/blob/be4e4786f7a5dffc36ab7b65ecfe74bf300e72c3/pkg/geo/geopb/bbox.go#L15)):*
> ```Go
> import "math"
> 
> // NewBoundingBox returns a properly initialized bounding box.
> ```

... initialized empty bounding box.
___
*[pkg/geo/geopb/geopb.proto, line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49196#-M7swiDRCmxwm8L7Jj4C:-M7swiDRCmxwm8L7Jj4D:b7glt61) ([raw file](https://github.com/cockroachdb/cockroach/blob/be4e4786f7a5dffc36ab7b65ecfe74bf300e72c3/pkg/geo/geopb/geopb.proto#L45)):*
> ```protobuf
>   Shape shape = 3;
>   // BoundingBox is the bounding box of the SpatialObject.
>   BoundingBox bounding_box = 4;
> ```

Do we need the `[(gogoproto.nullable) = false]` annotation, so that the `pb.go` file does not use `*BoundingBox` here?
Or do we need to distinguish between an empty bounding box and a nil bounding box?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49196)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/geo/bbox.go, line 57 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49196#-M7sxFuY67NJVtS1Ld3Y:-M7tMkyBASkm-PtUw2gD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/be4e4786f7a5dffc36ab7b65ecfe74bf300e72c3/pkg/geo/bbox.go#L57)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

innerBBox sounds like a new geometric concept.
How about `shapeBBox`?
</blockquote></details>

Done.
___
*[pkg/geo/geopb/bbox.go, line 15 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49196#-M7sw-Sq8pNXDzJzsbod:-M7tMsup44S1II28UQiF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/be4e4786f7a5dffc36ab7b65ecfe74bf300e72c3/pkg/geo/geopb/bbox.go#L15)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

... initialized empty bounding box.
</blockquote></details>

Done.
___
*[pkg/geo/geopb/geopb.proto, line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49196#-M7jBQ4gB9e9FRkRIPYd:-M7tN3TD4SRJSbjytbDN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/775557cd79d3d4e0a6f0c2df4c770293a6435b0c/pkg/geo/geopb/geopb.proto#L45)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think the latter does not need storing the bounding box. The indexing code would
- compute the covering of the original shape, C1
- compute the bounding box and the covering of the bounding box, C2
if C2 is "smaller" than C1, use C2 for indexing, else use C1.

The performance is enough motivation to store these.
</blockquote></details>

Done.
___
*[pkg/geo/geopb/geopb.proto, line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49196#-M7swiDRCmxwm8L7Jj4C:-M7tKvg-61kTujibv-yu:bprfa9f) ([raw file](https://github.com/cockroachdb/cockroach/blob/be4e4786f7a5dffc36ab7b65ecfe74bf300e72c3/pkg/geo/geopb/geopb.proto#L45)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Do we need the `[(gogoproto.nullable) = false]` annotation, so that the `pb.go` file does not use `*BoundingBox` here?
Or do we need to distinguish between an empty bounding box and a nil bounding box?
</blockquote></details>

I want a nil bounding box fo the empty geometry for now.

**Comment by otan** [comment]
bors r=sumeerbhola

**Pull request merged**
