### PR TITLE
 sql: fix the handling of FLOAT column types 

### PR DESCRIPTION
**Pull request by knz**
Forked from #28690.
First commit from #28792.

Prior to this patch, CockroachDB incorrectly concerned itself to
preserve the precision specification on the FLOAT type if any was
specified. It behaved as if `FLOAT`, `FLOAT(10)` and `FLOAT(20)` were
all different types.

However, in the PostgreSQL dialect there are really just two types
called `float4` and `float8`. The engine ought to distinguish them
upfront during parsing and desugar any specified precision
immediately. A precision between 1 and 24 (inclusive) implies
`float4`, a precision between 25 and 54 (inclusive) implies `float8`,
and anything else is invalid.

There is thus no need to store the precision, and a data width field
is sufficient to distinguish between the two possible column types.

This patch simplifies the code as follows:

- `coltypes.TFloat` is simplified accordingly.
- in column descriptors, only `VisibleType` is now used
  to determine which type is in use.
- to accommodate descriptors created pre-2.1, the code fishes
  for which type to use from `Precision` if it was set.

Here's the encoding of FLOAT in sqlbase.ColumnType.

Before:

| SQL Type                       | SemanticType | VisibleType      | Precision |
|--------------------------------|--------------|------------------|-----------|
| FLOAT                          | FLOAT        | NONE             | 0         |
| REAL, FLOAT4                   | FLOAT        | REAL             | 0         |
| FLOAT(N)                       | FLOAT        | NONE             | N         |
| DOUBLE PRECISION,DOUBLE,FLOAT8 | FLOAT        | DOUBLE PRECISION | 0         |

After:

| SQL Type | SemanticType | VisibleType | Precision |
|----------|--------------|-------------|-----------|
| FLOAT8   | FLOAT        | NONE        | 0         |
| FLOAT4   | FLOAT        | REAL        | 0         |

These two cases overlap with the REAL/FLOAT types previously.

In addition the code is equipped to detect in an existing descriptor
if the precision was >0, in which case it further decides between
FLOAT4 and FLOAT8 based on the value of N, like in the parser.

An alternative approach was to use `Width` instead of `VisibleType`
however the VisibleType values are more compact to encode.

Release note (sql change): The FLOAT column types are now reported
as `FLOAT4` and `FLOAT8` (the default) in the output of SHOW CREATE,
instead of `REAL` and `FLOAT` as previously.

### CODE REVIEW

**Comment by knz** [comment]
@jordanlewis this is the change we discussed earlier today.

**Review by BramGruneir — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 42 of 42 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28776#-:-LKMqBux1xZ7V0_0ADUR:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/sqlbase/structured.proto, line 158 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28776#-LKMk-R5AHAEU6Cy7O7q:-LKMk-R5AHAEU6Cy7O7r:b-vf3y44) ([raw file](https://github.com/cockroachdb/cockroach/blob/c21b5583adb6636c9d4b4b75ed327c00c96d2b7f/pkg/sql/sqlbase/structured.proto#L158)):*
> ```protobuf
>   // BIT, INT, DECIMAL, CHAR and BINARY
>   optional int32 width = 2 [(gogoproto.nullable) = false];
>   // DECIMAL.
> ```

nit: no need for the period
___
*[pkg/sql/sqlbase/structured_test.go, line 1077 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28776#-LKMk8cr3e23jcTB_ZYt:-LKMk8cr3e23jcTB_ZYu:b-zaut0g) ([raw file](https://github.com/cockroachdb/cockroach/blob/c21b5583adb6636c9d4b4b75ed327c00c96d2b7f/pkg/sql/sqlbase/structured_test.go#L1077)):*
> ```Go
> 		{ColumnType{SemanticType: ColumnType_INT}, "INT"},
> 		{ColumnType{SemanticType: ColumnType_INT, VisibleType: ColumnType_BIT, Width: 2}, "BIT(2)"},
> 		{ColumnType{SemanticType: ColumnType_FLOAT, VisibleType: ColumnType_REAL}, "FLOAT4"},
> ```

you have a repeat test case

`{ColumnType{SemanticType: ColumnType_FLOAT, VisibleType: ColumnType_REAL}, "FLOAT4"},`
___
*[pkg/sql/sqlbase/structured_test.go, line 1100 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28776#-LKMlD8yB8ZXi_z6KbuB:-LKMlD8yB8ZXi_z6KbuC:b-gbqsnh) ([raw file](https://github.com/cockroachdb/cockroach/blob/c21b5583adb6636c9d4b4b75ed327c00c96d2b7f/pkg/sql/sqlbase/structured_test.go#L1100)):*
> ```Go
> 			}
> 		})
> 	}
> ```

Is it worthwhile to add tests for when the precision is out of bounds?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28776)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/sqlbase/structured.proto, line 158 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28776#-LKMk-R5AHAEU6Cy7O7q:-LKNU6Jj72s40kLet0Be:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c21b5583adb6636c9d4b4b75ed327c00c96d2b7f/pkg/sql/sqlbase/structured.proto#L158)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

nit: no need for the period
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/structured_test.go, line 1077 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28776#-LKMk8cr3e23jcTB_ZYt:-LKNUBVqAh5cn2cc3sZm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c21b5583adb6636c9d4b4b75ed327c00c96d2b7f/pkg/sql/sqlbase/structured_test.go#L1077)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

you have a repeat test case

`{ColumnType{SemanticType: ColumnType_FLOAT, VisibleType: ColumnType_REAL}, "FLOAT4"},`
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/structured_test.go, line 1100 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28776#-LKMlD8yB8ZXi_z6KbuB:-LKNUwdaCVLc3Ekjyp28:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/c21b5583adb6636c9d4b4b75ed327c00c96d2b7f/pkg/sql/sqlbase/structured_test.go#L1100)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Is it worthwhile to add tests for when the precision is out of bounds?
</blockquote></details>

Good idea. Done.

**Comment by knz** [comment]
TFYR!

bors r+

**Pull request merged**
