### PR TITLE
tabledesc: improve index column ID and name validation

### LINKED ISSUE #72771: sql: alter column type can corrupt tables with secondary indexes storing the column
**Describe the problem**

The experimental `ALTER COLUMN TYPE` has an egregious bug. We seemingly don't do anything about indexes which store the column. This leads to these indexes persisting with the old column even after it is not in the table. For various reasons, this sort of worked out surprisingly well because the implementation of the various column ordinal maps wouldn't find the column and stored columns end up, mostly, being an optimization. 

**To Reproduce**

The repro from https://github.com/cockroachdb/cockroach/issues/72718#issuecomment-967782088 demonstrates it.

**Expected behavior**
We should have rewritten the index.

**Additional context**

This leaves us in a sticky situation. These indexes might exist in the wild. Ideally we'd properly validate that all the columns in an index exist in the table descriptor. I'm inclined to add such validation now. In the meantime, existing descriptors will be broken and we'll need to drop the index.

----
https://github.com/cockroachdb/cockroach/issues/72718 is caused by this and https://github.com/cockroachdb/cockroach/pull/72676 reveals it. The way that it gets revealed, which is rather horrific, is that there's a different behavior in the small and large FastIntMap. If the value does not exist in small, you'll get `-1, false`, but if it does not exist in large, you'll get `0, false`. See https://github.com/cockroachdb/cockroach/blob/47a2e2f8cccacea7d3fe653dfc8864c46d609706/pkg/util/fast_int_map.go#L79-L82

### PR DESCRIPTION
**Pull request by postamar**
This commit adds missing index column ID and name validation, in
particular concerning stored- and key-suffix-columns.

Fixes #72771.

Release note: None

### CODE REVIEW

**Comment by postamar** [comment]
This validation is not gated behind any descriptor version formats. Existing corrupted primary indexes will be fixed automatically and so will pass validation, existing corrupted secondary indexes will fail validation and so will require the user to drop them and recreate them.

**Comment by postamar** [comment]
This is interesting. The ADD COLUMN test case in TestRollback is hanging, and this is because we're failing these new validation checks in the rollbacks. I haven't yet found the bug in the declarative schema changer's ADD COLUMN implementation, instead I made some improvements to that test suite so that it wouldn't hang:
https://github.com/cockroachdb/cockroach/pull/73177

I also made these driven by the side-effects test definitions, which is quite nice here because it makes it easy to see where the problem is. Here, bad things happen when failing the validation ops stage after backfilling.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73142#-:-Mu9FX-NErC8lKupjs0z:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @postamar)

**Comment by postamar** [comment]
Thanks for the review!

bors r+

**Pull request merged**
