### PR TITLE
issues: filter by exact title match when looking for existing issue

### PR DESCRIPTION
**Pull request by renatolabs**
This changes the logic used to find existing and related issues when posting test failures on GitHub. Previously, we would rely on the GitHub API to find issues with the a certain title; however, the GitHub API does not provide a way to filter by exact title match. Instead, issues that have a "similar" name are returned. As a consequence, when a test fails, we might comment on an existing issue for a different test, which is confusing and may mask failures.

As a means of example, check issue #91594: failures for `schemachange/mixed-versions` and `schemachange/mixed-versions-compat` are both posted there for this reason.

This commit does some further filtering on our end to ensure that an issue is only considered existing or related if the titles match exactly.

Epic: none

Release note: None

### CODE REVIEW

**Review by herkolategan — CHANGES_REQUESTED** [review]
> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96389)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @renatolabs, @smg260, and @srosenberg)

___
*[`pkg/cmd/internal/issues/issues_test.go` line 180 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96389#-NNI-h8g8xTlv6edvMYO:-NNI-h8g8xTlv6edvMYP:b-ku1gj4) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb3530403d001403bcb32399db7077f4dc80a1b7/pkg/cmd/internal/issues/issues_test.go#L180)):*
> ```Go
> 		factories := make([]issueFactory, 0, len(suffixes))
> 		for k, suffix := range suffixes {
> 			suffix := suffix // capture range variable
> ```

shouldn't `k` be captured as well?

**Review by herkolategan — COMMENTED** [review]
Nice fix, I'm sure this will prevent unwarranted confusion in the future.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96389#-:-NNI0jh02VzqCCKABmAP:b-hky18l)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @renatolabs, @smg260, and @srosenberg)

**Review by renatolabs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96389)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @smg260, and @srosenberg)

___
*[`pkg/cmd/internal/issues/issues_test.go` line 180 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96389#-NNI-h8g8xTlv6edvMYO:-NNI3Sen7V04ro02CE8j:b50osz3) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb3530403d001403bcb32399db7077f4dc80a1b7/pkg/cmd/internal/issues/issues_test.go#L180)):*
<details><summary><i>Previously, herkolategan (Herko Lategan) wrote…</i></summary><blockquote>

shouldn't `k` be captured as well?
</blockquote></details>

Hah, nice catch, it's funny how often I still make this mistake even after thinking about it for so long while writing that linter. Fixed.

**Review by herkolategan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96389)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @smg260 and @srosenberg)

**Review by herkolategan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96389)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @renatolabs, @smg260, and @srosenberg)

___
*[`pkg/cmd/internal/issues/issues_test.go` line 180 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96389#-NNI-h8g8xTlv6edvMYO:-NNI5g5q8adcIWBuS9fW:brmk1mx) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb3530403d001403bcb32399db7077f4dc80a1b7/pkg/cmd/internal/issues/issues_test.go#L180)):*
<details><summary><i>Previously, renatolabs (Renato Costa) wrote…</i></summary><blockquote>

Hah, nice catch, it's funny how often I still make this mistake even after thinking about it for so long while writing that linter. Fixed.
</blockquote></details>

Easy to miss those! And still something I'm getting used to, having worked in `Java` for a long time, I'm very use to the compiler complaining that a variable needs to be `final` if you're capturing it in a lambda.

**Comment by renatolabs** [comment]
bors r=herkolategan

TFTR!

**Pull request merged**
