### PR TITLE
ui: sql activity pages depend on node info

### LINKED ISSUE #85249: Regions/Nodes columns not showing up on Dedicated
The column for Node/Regions are not being displayed on Statement Page. The filter of nodes is being displayed so the value must be correct, but some other check must be wrong, since it's not showing the column itself or on the column selector list.

To be clear, this column should not be displayed on Serverless

Jira issue: CRDB-18136

### PR DESCRIPTION
**Pull request by matthewtodd**
Fixes #85249.

Previously, the statements, transactions, and transaction details pages had an implicit dependency on the `state.adminUI.nodes` list in the redux store, and without that list, the Regions/Nodes columns and filters would be incorrectly hidden for multiregion clusters, unless the user happened to have already browsed through a page (such as statement details) that loaded the list.

(This bug was affecting dedicated cloud clusters only. Self-hosted clusters were working properly because their global mechanism to sync alert data happened to [refresh the node list][1].)

This change makes the dependency explicit and refreshes the list of nodes on entering those three pages.

[1]: https://github.com/cockroachdb/cockroach/blob/6a25c6f4b985ddcd08ed51772f9e8a2645aa4582/pkg/ui/workspaces/db-console/src/redux/alerts.ts#L678-L682

| Before | After |
|--|--|
|Screen Shot 2022-09-22 at 10 42 33 AM|Screen Shot 2022-09-22 at 10 41 12 AM|
|Screen Shot 2022-09-22 at 10 42 42 AM|Screen Shot 2022-09-22 at 10 41 22 AM|
|Screen Shot 2022-09-22 at 10 43 00 AM|Screen Shot 2022-09-22 at 10 41 38 AM|

Release note (bug fix): The statements, transactions, and transaction details pages in the admin console now properly show the Regions/Nodes columns and filters for multiregion clusters.

### CODE REVIEW

**Review by maryliag — APPROVED** [review]
Nice! Just one small questions, otherwise :lgtm: 

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88461#-:-NCaFRA00Z5XE-ge3Lel:boh0pvx)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @matthewtodd)

___
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88461#-NCaFLzX25sBTA0Euz8W):*
can you confirm that this info is not being displayed on Serverless?

**Review by maryliag — COMMENTED** [review]
this will need to be backported to 22.1 and 22.2

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88461#-:-NCaFk0xETIQ6KnqYWx8:bhx9u0d)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @matthewtodd)

**Review by matthewtodd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88461)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88461#-NCaFLzX25sBTA0Euz8W):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

can you confirm that this info is not being displayed on Serverless?
</blockquote></details>

Sure thing! It's already [filtered](https://github.com/cockroachdb/cockroach/blob/018e180dc367c82fc5fbe7eb95a447f500cb90ff/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx#L577-L594) on the statements page, we recently [removed](https://github.com/cockroachdb/cockroach/pull/87531) it from the transaction details page, and a [couple](https://github.com/matthewtodd/cockroach/blob/1c9e24b5bb760e9ebac64705acb2a297d09d5c76/pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.tsx#L492-L501) of [calls](https://github.com/matthewtodd/cockroach/blob/1c9e24b5bb760e9ebac64705acb2a297d09d5c76/pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.tsx#L506-L516) filter it on the transactions page.

**Comment by matthewtodd** [comment]
(I'm having trouble getting the build to kick off, have force-pushed a couple of times to see if that'll do it. 🤞🏻)

**Review by maryliag — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88461)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @matthewtodd)

___
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88461#-NCaFLzX25sBTA0Euz8W):*
<details><summary><i>Previously, matthewtodd (Matthew Todd) wrote…</i></summary><blockquote>

Sure thing! It's already [filtered](https://github.com/cockroachdb/cockroach/blob/018e180dc367c82fc5fbe7eb95a447f500cb90ff/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx#L577-L594) on the statements page, we recently [removed](https://github.com/cockroachdb/cockroach/pull/87531) it from the transaction details page, and a [couple](https://github.com/matthewtodd/cockroach/blob/1c9e24b5bb760e9ebac64705acb2a297d09d5c76/pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.tsx#L492-L501) of [calls](https://github.com/matthewtodd/cockroach/blob/1c9e24b5bb760e9ebac64705acb2a297d09d5c76/pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.tsx#L506-L516) filter it on the transactions page.
</blockquote></details>

Great!

**Comment by maryliag** [comment]
@matthewtodd looks like the backport to 22.1 didn't happen, can you create one? Thanks!

**Pull request merged**
