### PR TITLE
scripts/bump-pebble: markdown format commit list links

### PR DESCRIPTION
**Pull request by dt**
Release note: none.
Epic: none.

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116874#-:-Nm7QfMX6fnO-Y1ActiU:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dt)

___
*[`scripts/bump-pebble.sh` line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116874#-Nm7QF_2BVZG7paKFV4k:-Nm7QF_2BVZG7paKFV4l:b-2lx522) ([raw file](https://github.com/cockroachdb/cockroach/blob/f994aa363770251665fb0d7de3c3bc7b63773011/scripts/bump-pebble.sh#L5)):*
> ```Shell
> # NOTE: After a new release has been cut, update this to the appropriate
> # Cockroach branch name (i.e. release-23.2, etc.), and corresponding Pebble
> # branch name (e.g. crl-release-23.2, etc.).
> ```

This comment should stay.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116874)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[`scripts/bump-pebble.sh` line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116874#-Nm7QF_2BVZG7paKFV4k:-Nm7R2Yk4ySSy9iEGAVP:b-4fs71g) ([raw file](https://github.com/cockroachdb/cockroach/blob/f994aa363770251665fb0d7de3c3bc7b63773011/scripts/bump-pebble.sh#L5)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This comment should stay.
</blockquote></details>

huh, I have no idea how this removal got in here.

**Review by RaduBerinde — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116874)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dt)

___
*[`scripts/bump-pebble.sh` line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/116874#-Nm7QF_2BVZG7paKFV4k:-Nm7RbZf5ENYS-BfeWAp:b-b13yyh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f994aa363770251665fb0d7de3c3bc7b63773011/scripts/bump-pebble.sh#L5)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

huh, I have no idea how this removal got in here.
</blockquote></details>

It was recently added, maybe some snafu during rebase

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/116874#-:-Nm7Sdkn0Zvn-__FE5JS:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dt)

**Comment by dt** [comment]
TFTR!

bors r+

**Pull request merged**
