### PR TITLE
exec: refactor comparison overloads

### PR DESCRIPTION
**Pull request by rafiss**
Previously, the comparison overload required a function call to be made.
It's refactored now so that we can inline some code.

Release note: None

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
Nice! :lgtm:

Do you know of any benchmarks that will show the performance improvement (I feel like the gain shouldn't be that big)?

> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39742#-:-Lmf6k8yEXrrq-OOhQ3H:b-bcawrk)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss and @solongordon)

___
*[pkg/sql/exec/execgen/cmd/execgen/overloads.go, line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39742#-Lmf58hSB6Xoabl77dcH:-Lmf58hSB6Xoabl77dcI:b-l17cnh) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a7d17ca692a825f6dae0c724fc49901a6c4ff60/pkg/sql/exec/execgen/cmd/execgen/overloads.go#L128)):*
> ```Go
> // Compare produces a Go source string that assigns the "target" variable to the
> // result of comparing the two inputs, l and r. The target will be negative,
> // zero, or positive depending if l is less-than, equal-to, or greater-than r.
> ```

[nit]: `s/if/on whether/`.

**Comment by rafiss** [comment]
Good point, here is a relevant benchmark. Small but noticeable change.

```
name                                              old time/op    new time/op    delta
SelLTInt64Int64Op/useSel=true,hasNulls=true-24      2.96µs ± 1%    2.89µs ± 0%   -2.12%  (p=0.000 n=10+9)
SelLTInt64Int64Op/useSel=true,hasNulls=false-24     1.80µs ± 1%    1.81µs ± 1%     ~     (p=0.339 n=10+10)
SelLTInt64Int64Op/useSel=false,hasNulls=true-24     3.12µs ± 3%    2.80µs ± 0%  -10.32%  (p=0.000 n=10+9)
SelLTInt64Int64Op/useSel=false,hasNulls=false-24    1.57µs ± 0%    1.43µs ± 0%   -9.09%  (p=0.000 n=8+10)

name                                              old speed      new speed      delta
SelLTInt64Int64Op/useSel=true,hasNulls=true-24    5.54GB/s ± 1%  5.66GB/s ± 0%   +2.17%  (p=0.000 n=10+9)
SelLTInt64Int64Op/useSel=true,hasNulls=false-24   9.09GB/s ± 1%  9.07GB/s ± 1%     ~     (p=0.393 n=10+10)
SelLTInt64Int64Op/useSel=false,hasNulls=true-24   5.24GB/s ± 3%  5.85GB/s ± 0%  +11.48%  (p=0.000 n=10+9)
SelLTInt64Int64Op/useSel=false,hasNulls=false-24  10.4GB/s ± 0%  11.5GB/s ± 0%  +10.00%  (p=0.000 n=8+10)
```

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39742)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @solongordon and @yuzefovich)

___
*[pkg/sql/exec/execgen/cmd/execgen/overloads.go, line 128 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39742#-Lmf58hSB6Xoabl77dcH:-LmfCth48Kxnmyhsro5T:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a7d17ca692a825f6dae0c724fc49901a6c4ff60/pkg/sql/exec/execgen/cmd/execgen/overloads.go#L128)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: `s/if/on whether/`.
</blockquote></details>

done

**Comment by rafiss** [comment]
thanks for the review! 

bors r+

**Pull request merged**
