### PR TITLE
geos: do not build windows on more files

### PR DESCRIPTION
**Pull request by otan**
Release note: None

### CODE REVIEW

**Comment by otan** [comment]
https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_MergeToMaster&tab=buildTypeStatusDiv&branch_Cockroach=47351

**Review by petermattis — APPROVED** [review]
:lgtm: though I'm sort of reviewing my own idea here.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47351#-:-M4_X5kj91OauYSxBSw_:b9kx5un)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by otan** [comment]
haha well i approve of your idea

**Comment by otan** [comment]
bors r=petermattis

it worked! can't believe i didn't do that >_>

**Pull request merged**
