### PR TITLE
sql: plumb bulk-adder support to index backfill

### PR DESCRIPTION
**Pull request by dt**
This adds support for adding indexes in bulk, via `AddSSTable`, gated by a default-off setting for now.

This is still a WIP and requires more testing (and support for unique indexes) before it can be enabled.

### CODE REVIEW

**Review by vivekmenezes — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32668)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/backfill.go, line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32668#-LTTSbnc6gHLk6OatESj:-LTTSbnc6gHLk6OatESk:buqe8ns) ([raw file](https://github.com/cockroachdb/cockroach/blob/61bbfa47856e6afc25870ab3768e5bc4028cde65/pkg/sql/backfill.go#L66)):*
> ```Go
> 
> var indexBulkBackfillChunkSize = settings.RegisterIntSetting(
> 	"sql.backfill.bulk.batch_size",
> ```

we already have settings with the schemachanger. prefix.
___
*[pkg/sql/backfill/backfill.go, line 365 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32668#-LTTT2tV7NPnSvnWpIju:-LTTT2tV7NPnSvnWpIjv:bb7od0r) ([raw file](https://github.com/cockroachdb/cockroach/blob/61bbfa47856e6afc25870ab3768e5bc4028cde65/pkg/sql/backfill/backfill.go#L365)):*
> ```Go
> // BulkWriteIndex enables experimental bulk-ingestion of index entries.
> var BulkWriteIndex = settings.RegisterBoolSetting(
> 	"sql.backfill.bulk.enabled", "backfill indexes if able in bulk via addsstable", false,
> ```

same
___
*[pkg/storage/storagebase/bulk_adder.go, line 37 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32668#-LTTRysT3VccRWTN-Xee:-LTTRysT3VccRWTN-Xef:bka7omq) ([raw file](https://github.com/cockroachdb/cockroach/blob/61bbfa47856e6afc25870ab3768e5bc4028cde65/pkg/storage/storagebase/bulk_adder.go#L37)):*
> ```Go
> 	Close()
> 	GetSummary() roachpb.BulkOpSummary
> }
> ```

It's worth adding comments for all these methods. What exactly are they doing?

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32668)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @vivekmenezes)

___
*[pkg/sql/backfill.go, line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32668#-LTTSbnc6gHLk6OatESj:-LWqtF2h1QwdLWyUWL-m:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/61bbfa47856e6afc25870ab3768e5bc4028cde65/pkg/sql/backfill.go#L66)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

we already have settings with the schemachanger. prefix.
</blockquote></details>

Done.
___
*[pkg/sql/backfill/backfill.go, line 365 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32668#-LTTT2tV7NPnSvnWpIju:-LWqtFWpBedDxaVvfhfB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/61bbfa47856e6afc25870ab3768e5bc4028cde65/pkg/sql/backfill/backfill.go#L365)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[pkg/storage/storagebase/bulk_adder.go, line 37 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32668#-LTTRysT3VccRWTN-Xee:-LWqztKL8dkksXFmHrd_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/61bbfa47856e6afc25870ab3768e5bc4028cde65/pkg/storage/storagebase/bulk_adder.go#L37)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

It's worth adding comments for all these methods. What exactly are they doing?
</blockquote></details>

Done.

**Review by vivekmenezes — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32668)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/sql/backfill.go, line 199 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32668#-LWrF8WY8qQG59rzleqh:-LWrF8WY8qQG59rzleqi:b-2226hz) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaf003f4827504c273c26d18a6b2aee3c3ad2091/pkg/sql/backfill.go#L199)):*
> ```Go
> 					break
> 				}
> 			}
> ```

you could use ContainsUnique() that you define below.
___
*[pkg/sql/backfill.go, line 483 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32668#-LWrEfaJDdPc9tu4FqB-:-LWrEfaJDdPc9tu4FqB0:bt29xtl) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaf003f4827504c273c26d18a6b2aee3c3ad2091/pkg/sql/backfill.go#L483)):*
> ```Go
> 	lease *sqlbase.TableDescriptor_SchemaChangeLease,
> 	version sqlbase.DescriptorVersion,
> 	useBulkChunkSize bool,
> ```

we could pass in the chunk size here.
___
*[pkg/sql/distsqlrun/indexbackfiller.go, line 125 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32668#-LWrFinj4ODrCUKTOuze:-LWrFinj4ODrCUKTOuzf:b-qzmpyx) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaf003f4827504c273c26d18a6b2aee3c3ad2091/pkg/sql/distsqlrun/indexbackfiller.go#L125)):*
> ```Go
> 	}
> 
> 	// Check if enough entries are being written that adding via SST is faster.
> ```

is it really worth using the threshold of 100 here. I ask because all the logic tests and a a large number of unittests will not use the new bulk import mechanism which is non ideal.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32668)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @vivekmenezes)

___
*[pkg/sql/backfill.go, line 199 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32668#-LWrF8WY8qQG59rzleqh:-LWrfQHl7EjoHHDO6cS8:b-ae97oo) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaf003f4827504c273c26d18a6b2aee3c3ad2091/pkg/sql/backfill.go#L199)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

you could use ContainsUnique() that you define below.
</blockquote></details>

Deleted the helper and unique checks entirely -- I came around to your suggestion that if this is still behind a setting, we can just use it all the time for now since we'll fast-follow with the validation step.
___
*[pkg/sql/backfill.go, line 483 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32668#-LWrEfaJDdPc9tu4FqB-:-LWrho4P56625baObl_X:bam3oyv) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaf003f4827504c273c26d18a6b2aee3c3ad2091/pkg/sql/backfill.go#L483)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

we could pass in the chunk size here.
</blockquote></details>

I ended up passing nothing and just reading the setting here since I no longer care about unique indexes.
___
*[pkg/sql/distsqlrun/indexbackfiller.go, line 125 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32668#-LWrFinj4ODrCUKTOuze:-LWre2uj4x7EiD7L14gL:b-742d54) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaf003f4827504c273c26d18a6b2aee3c3ad2091/pkg/sql/distsqlrun/indexbackfiller.go#L125)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

is it really worth using the threshold of 100 here. I ask because all the logic tests and a a large number of unittests will not use the new bulk import mechanism which is non ideal.
</blockquote></details>

We really don't want to make / add small SSTs. This is a good first place to skip making the SST adder at all if we have too few entries, though ideally we'd push this even further down to the SST batcher itself so it could switch to a batch of puts if after batching (by range boundaries), we end up with a small batch.

So yeah, we could remove this one here and push it down, but that'd still mean we don't add SSTs in small unit tests but that's ~what we want. We should have roach tests that are big enough to trigger the switch to bulk sized batches?

**Review by vivekmenezes — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32668)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/sql/distsqlrun/indexbackfiller.go, line 125 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32668#-LWrFinj4ODrCUKTOuze:-LWvG-Sh3QtF50CGe6gh:b-qi41z2) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaf003f4827504c273c26d18a6b2aee3c3ad2091/pkg/sql/distsqlrun/indexbackfiller.go#L125)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

We really don't want to make / add small SSTs. This is a good first place to skip making the SST adder at all if we have too few entries, though ideally we'd push this even further down to the SST batcher itself so it could switch to a batch of puts if after batching (by range boundaries), we end up with a small batch.

So yeah, we could remove this one here and push it down, but that'd still mean we don't add SSTs in small unit tests but that's ~what we want. We should have roach tests that are big enough to trigger the switch to bulk sized batches?
</blockquote></details>

Is there a specific reason why we don't want small SSTs? Thanks

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32668)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @vivekmenezes)

___
*[pkg/sql/distsqlrun/indexbackfiller.go, line 125 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32668#-LWrFinj4ODrCUKTOuze:-LWvGLWe8KL0IjADkYe2:b-v8u7p8) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaf003f4827504c273c26d18a6b2aee3c3ad2091/pkg/sql/distsqlrun/indexbackfiller.go#L125)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Is there a specific reason why we don't want small SSTs? Thanks
</blockquote></details>

adding an SST has some fixed overhead -- RocksDB has to grab a lock on the metadata, it has to flush the memtable, etc. Also, if it goes into L0, it counts towards the 16 files we can have there before slowdown. So we only really want to add an SST if we're getting enough bang for our buck -- if we're only adding a small number of keys, it'll probably be slower than just writing normally (i.e. to the memtable) and lots of little files is likely to hit the dreaded L0 limit.

**Review by vivekmenezes — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32668)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/sql/distsqlrun/indexbackfiller.go, line 125 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32668#-LWrFinj4ODrCUKTOuze:-LWvHa543YUPA7xjFZqO:bxw9sjz) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaf003f4827504c273c26d18a6b2aee3c3ad2091/pkg/sql/distsqlrun/indexbackfiller.go#L125)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

adding an SST has some fixed overhead -- RocksDB has to grab a lock on the metadata, it has to flush the memtable, etc. Also, if it goes into L0, it counts towards the 16 files we can have there before slowdown. So we only really want to add an SST if we're getting enough bang for our buck -- if we're only adding a small number of keys, it'll probably be slower than just writing normally (i.e. to the memtable) and lots of little files is likely to hit the dreaded L0 limit.
</blockquote></details>

Do you think it's better to wait and see if we have a problem before making the optimization? I only say this because it's valuable to have all tests test the same code path.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32668)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @vivekmenezes)

___
*[pkg/sql/distsqlrun/indexbackfiller.go, line 125 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32668#-LWrFinj4ODrCUKTOuze:-LWvW-hMEY-CaUczVWFa:bftw5vx) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaf003f4827504c273c26d18a6b2aee3c3ad2091/pkg/sql/distsqlrun/indexbackfiller.go#L125)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Do you think it's better to wait and see if we have a problem before making the optimization? I only say this because it's valuable to have all tests test the same code path.
</blockquote></details>

I'm fine with making it a setting, or even a TODO for now, but I'd really be wary of the worst-case adversarial data distribution that throws thousands of tiny files at us if we don't have anything at all.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32668)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @vivekmenezes)

___
*[pkg/sql/distsqlrun/indexbackfiller.go, line 125 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32668#-LWrFinj4ODrCUKTOuze:-LWvwPDrEWtEyWJGKZS8:b-n1lwkk) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaf003f4827504c273c26d18a6b2aee3c3ad2091/pkg/sql/distsqlrun/indexbackfiller.go#L125)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I'm fine with making it a setting, or even a TODO for now, but I'd really be wary of the worst-case adversarial data distribution that throws thousands of tiny files at us if we don't have anything at all.
</blockquote></details>

I've remove the check for now -- I think we should bring it back, and I think we'll also want something similar after the SSTs get chunked by range bounds by the batcher, but I'm fine with that being a followup.

**Review by vivekmenezes — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32668)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Pull request merged**
