### PR TITLE
vendor: bump Pebble to 3358c2be85f7

### PR DESCRIPTION
**Pull request by jbowens**
```
3358c2be internal/keyspan: remove unnecessary allocations
eb5c079c metamorphic: synchronize iterator ops with indexed batch
33c108eb metamorphic: add limited concurrency
acc59654 *: Add random test for iterator seek - BlockPropertyFilters interaction
3f835a3d metamorphic: test RangeKeyChanged=false in the metamorphic tests
4ab85a4d metamorphic: increase probability of valid SeekPrefixGE calls
```

Release note: None
Release justification: Non-production code changes and low-risk bug
fix to new functionality.

### CODE REVIEW

**Review by bananabrick — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/87333#-:-NBNgkFV-WinpjT6ZNHP:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by jbowens** [comment]
TFTR!

bors r=bananabrick

**Comment by jbowens** [comment]
bors r=bananabrick

**Comment by jbowens** [comment]
T_T going to just recreate this with a more recent SHA given the merge conflict

**Pull request closed without merging**
