### PR TITLE
sql: more RowFetcher optimizations

### PR DESCRIPTION
**Pull request by RaduBerinde**
### sql: don't set composite columns as needed in row fetcher
We don't need to fully decode all key columns if they are not needed.

### sql: remove unsetCols map
Removing the unsetCols map which is only used to avoid some assertions. Creating
this map was about 3.7% in a profile of a large scan where we don't need column
values.

### sql: avoid KV decoding altogether if no values are required
Special optimization when no columns are needed in the row fetcher. This is only
useful for `COUNT(*)` but the speedup for that is significant (20%).

### CODE REVIEW

**Comment by arjunravinarayan** [comment]
:LGTM:, nice cleanups!

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/sqlbase/rowfetcher.go, line 324 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16467#-KmWmNKv0xzi1XYhc0Qk:-KmWmNKwbSR01Cl_sRIu:bd03n6z) ([raw file](https://github.com/cockroachdb/cockroach/blob/c89888a7c9ee80166ada76e8f1b15c12bef61812/pkg/sql/sqlbase/rowfetcher.go#L324)):*
> ```Go
> 		}
> 
> 		// If familyID is 0, this value contains values for the composite
> ```

This comment doesn't make sense any more with the code deletion(?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16467#-:-KmWhcF9s3EF1JqGolc0:b-lbrmks)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/sqlbase/rowfetcher.go, line 324 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16467#-KmWmNKv0xzi1XYhc0Qk:-KmWnhCgnLh3D6HjlxsD:b-6zihxe) ([raw file](https://github.com/cockroachdb/cockroach/blob/c89888a7c9ee80166ada76e8f1b15c12bef61812/pkg/sql/sqlbase/rowfetcher.go#L324)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

This comment doesn't make sense any more with the code deletion(?)
</blockquote></details>

It does.. There is no special code we need to run in this case now but I think it's important to point out what's going on.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16467)*

**Comment by arjunravinarayan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/sqlbase/rowfetcher.go, line 324 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16467#-KmWmNKv0xzi1XYhc0Qk:-KmWrM3yOCFVfF6imVDR:b-7zw09v) ([raw file](https://github.com/cockroachdb/cockroach/blob/c89888a7c9ee80166ada76e8f1b15c12bef61812/pkg/sql/sqlbase/rowfetcher.go#L324)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It does.. There is no special code we need to run in this case now but I think it's important to point out what's going on.
</blockquote></details>

OK. s/this value/`family`/?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16467)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/sqlbase/rowfetcher.go, line 324 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16467#-KmWmNKv0xzi1XYhc0Qk:-KmWsPB4I9uZbmkkl5eU:b-npjxwd) ([raw file](https://github.com/cockroachdb/cockroach/blob/c89888a7c9ee80166ada76e8f1b15c12bef61812/pkg/sql/sqlbase/rowfetcher.go#L324)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

OK. s/this value/`family`/?
</blockquote></details>

It's value as in Key-Value

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16467)*

**Comment by arjunravinarayan** [comment]
*[pkg/sql/sqlbase/rowfetcher.go, line 324 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16467#-KmWmNKv0xzi1XYhc0Qk:-KmWsfrSt1HqSpQNx7JO:b-oqqb6q) ([raw file](https://github.com/cockroachdb/cockroach/blob/c89888a7c9ee80166ada76e8f1b15c12bef61812/pkg/sql/sqlbase/rowfetcher.go#L324)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It's value as in Key-Value
</blockquote></details>

OK clearly it needs rewording since I'm confused about what is being said now that it accompanies no code...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16467)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/sqlbase/rowfetcher.go, line 324 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16467#-KmWmNKv0xzi1XYhc0Qk:-KmWvE_Xu9fDV_Q3vU5q:bdubnrc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c89888a7c9ee80166ada76e8f1b15c12bef61812/pkg/sql/sqlbase/rowfetcher.go#L324)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

OK clearly it needs rewording since I'm confused about what is being said now that it accompanies no code...
</blockquote></details>

Expanded, let me know if it's clearer now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16467)*

**Comment by arjunravinarayan** [comment]
*[pkg/sql/sqlbase/rowfetcher.go, line 324 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16467#-KmWmNKv0xzi1XYhc0Qk:-KmWvk0ep9qiwb0Cr5-O:b-w77lbi) ([raw file](https://github.com/cockroachdb/cockroach/blob/c89888a7c9ee80166ada76e8f1b15c12bef61812/pkg/sql/sqlbase/rowfetcher.go#L324)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Expanded, let me know if it's clearer now.
</blockquote></details>

This is a wonderful comment now, Thank you! :100: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16467)*

**Comment by eisenstatdavid** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16467#-:-Kman8KTuYRvp4RpCxqp:bnfp4nl)*

**Pull request merged**
