### PR TITLE
sql: use crdb_internal for pg_proc.pronamespace when needed

### LINKED ISSUE #94952: sql: pg_proc.pronamespace is not populated for built-in functions
Found while working on #88061.

**Describe the problem**

The `pronamespace` column in `pg_proc` is NULL for all the built-in functions.

This is incorrect:

- we want the OID of `pg_catalog` for all the "base" built-ins
- and the OID of `crdb_internal` for the crdb_internal built-ins

Additionally, once the above is achieved, the `crdb_internal.` prefix should be stripped in the `proname` column.

**To Reproduce**

```sql
SELECT n.nspname AS "Schema"
    p.proname AS "Name"
FROM pg_proc p
  LEFT JOIN ps_namespace n ON n.oid = p.pronamespace
```

cc @rafiss for triage.

Jira issue: CRDB-23240

### PR DESCRIPTION
**Pull request by rafiss**
Epic: CRDB-23454
fixes https://github.com/cockroachdb/cockroach/issues/94952

Release note (bug fix): The pronamespace column of the pg_proc table now correctly reports the crdb_internal schema for built-in functions that have the "crdb_internal" prefix.

---

comprules: support completion for qualified functions

The syntax completion engine now generates suggestion for user-defined
functions. It restricts the suggestions to only functions in the schema
name if one was provided, or else to the schemas in the search_path.

No release note since this functionality is new in v23.1.

### CODE REVIEW

**Review by e-mbrown — APPROVED** [review]
LGTM!

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95029#-:-NLVGRGM7D9G8mHTxBHG:b-85i648)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

**Comment by rafiss** [comment]
@knz could you PTAL at the changes in the `show completions` test? CI fails with
```
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/9461/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/local-vec-off/local-vec-off_test_/local-vec-off_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/show_completions:40: SELECT completion FROM [SHOW COMPLETIONS AT OFFSET 10 FOR 'SHOW CREAT']
        expected:
            CREATE
            CREATEDB
            CREATELOGIN
            CREATEROLE
        but found (query options: "") :
            CREATE
            CREATEDB
            CREATELOGIN
            CREATEROLE
            create_join_token(
            create_regclass(
            create_regnamespace(
            create_regproc(
            create_regprocedure(
            create_regrole(
            create_regtype(
            create_session_revival_token(
            create_sql_schema_telemetry_job(
```

So it looks like it's suggesting `crdb_internal` builtin functions now. But the suggestion won't work, since `crdb_internal` is not on the `search_path` by default. We want to restrict the suggested completions to only include items resolvable in the `search_path`. Would you agree, and if so, where should I make the change?

**Review by knz — APPROVED** [review]
> where should I make the change?
Very good question!

You'd need to modify the completion rule for functions, at pkg/sql/comprules/rules.go line 160.
We want to use a query that enumerate the functions _visible from the current search_path_.

So I believe this willb e something like replacing
```sql
SELECT DISTINCT proname FROM pg_catalog.pg_proc
```

to 
```sql
SELECT DISTINCT proname FROM pg_catalog.pg_proc p,
 JOIN  pg_catalog.pg_namespace n ON p.pronamespace = n.oid
WHERE n.nspname = ANY pg_catalog.current_schemas(TRUE)
```

You'll also see that function says something about built-in function comments not being available through pg_objdescription yet. Should we file an issue about that?

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95029#-:-NLXXvYt3PUIT1n1OVqT:b-jpthe0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

**Review by knz — COMMENTED** [review]
Ooh wait my previous explanation is wrong. That completion rule is a bit more intelligent, and is able to recognize a namespace prefix earlier in the SQL syntax. This should be used *instead* of `current_schemas` if available.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95029#-:-NLXYptk-hTNKJ3vvVMX:bbsrnsl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

**Comment by rafiss** [comment]
> You'll also see that function says something about built-in function comments not being available through pg_objdescription yet. Should we file an issue about that?

since we don't have `comment on function` support yet (https://github.com/cockroachdb/cockroach/issues/44135) i think we can just track built-in function comments using that issue as well.

**Comment by rafiss** [comment]
@knz thanks for the pointer. I added a new commit to fix the completion rules. Can you review it when you have time?

**Review by knz — APPROVED** [review]
You got this! I'm so glad you found the simplification. This architecture works.

There's a few nits we need to take care of: https://github.com/cockroachdb/cockroach/pull/95029

LGTM modulo something like that + necessary test adjustments.

> Reviewed 1 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95029#-:-NLc0x7g7cQhr0Akg8Za:b-cqmrja)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @rafiss)

___
*[`pkg/sql/comprules/rules.go` line 150 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95029#-NLc0ubuAzmezC3oBhJ6:-NLc0ubuAzmezC3oBhJ7:b6u1a37) ([raw file](https://github.com/cockroachdb/cockroach/blob/9941ce1ef61ef80571a9d7fc12ed1c7341fdf425/pkg/sql/comprules/rules.go#L150)):*
> ```Go
> 	// built-in functions through pg_catalog.
> 	const query = `
> WITH p AS (SELECT DISTINCT proname, nspname FROM pg_catalog.pg_proc JOIN pg_catalog.pg_namespace n ON n.oid = pronamespace)
> ```

:clap: :clap: :clap:

**Review by knz — COMMENTED** [review]
Sorry I meant to link to this: https://github.com/rafiss/cockroach/pull/1

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95029#-:-NLc18d27jp8Iq3VGq3x:b-on0k7o)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown and @rafiss)

**Review by knz — APPROVED** [review]
> Reviewed 3 of 5 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95029)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

**Comment by knz** [comment]
The remaining flake in CI here is not yours. Let's file an issue for it (and perhaps skip it), you can merge your PR.

**Comment by knz** [comment]
i'll file it for you

**Comment by knz** [comment]
#95201

**Comment by rafiss** [comment]
flake was https://github.com/cockroachdb/cockroach/issues/94956 which is also on me to fix (unrelated to this PR)

bors r=knz

**Pull request merged**
