### PR TITLE
sql: add support for x'val'-style hexadecimal literals

### LINKED ISSUE #4017: sql: add support for hexadecimal literals
After switching to the postgres driver, I had to comment out the `Example_zone` in `cli/cli_test.go` (see: https://github.com/cockroachdb/cockroach/pull/3757/files#diff-7d7fb132e111ef7398af7150b1d54a32 L480-L535.

The actual statement being run is (from `cli/zone.go`, removing boilerplate error handling and other stuff):
```
  buf, err := proto.Marshal(&pbZoneConfig)
  // TODO(marc): switch to placeholders when they're fixed with pgwire.
  err = runPrettyQuery(db, os.Stdout,
    fmt.Sprintf(`INSERT INTO system.zones VALUES (%d, '%s'::bytes)`, id, string(buf)))
```

This now fails because the string version of `buf` contains a newline, so we get the error:
```
Query with %s: INSERT INTO system.zones VALUES (100, '


us-east-1a
ssd


us-east-1b
ssd


us-west-1b
ssd������ "'::bytes)
Query with %q: "INSERT INTO system.zones VALUES (100, '\n\x11\n\nus-east-1a\n\x03ssd\n\x11\n\nus-east-1b\n\x03ssd\n\x11\n\nus-west-1b\n\x03ssd\x10\x80\x80\x80\x04\x18\x80\x80\x80 \"\x02\b\x00'::bytes)"
E0128 15:35:10.743505 21079 cli/zone.go:239  statement error: pq: unterminated string
INSERT INTO system.zones VALUES (100, '
                                      ^
```

The long-term solution for this particular bit of code is to switch to placeholders. But for now, this should work as well. I tried switching to:
```
 err = runPrettyQuery(db, os.Stdout,
    fmt.Sprintf(`SET syntax = modern; INSERT INTO system.zones VALUES (%d, '''%s'''::bytes)`, id, string(buf)))
```

Which fails with:
```
Query with %s: SET syntax=modern; INSERT INTO system.zones VALUES (100, '''


us-east-1a
ssd


us-east-1b
ssd


us-west-1b
ssd������ "'''::bytes)
Query with %q: "SET syntax=modern; INSERT INTO system.zones VALUES (100, '''\n\x11\n\nus-east-1a\n\x03ssd\n\x11\n\nus-east-1b\n\x03ssd\n\x11\n\nus-west-1b\n\x03ssd\x10\x80\x80\x80\x04\x18\x80\x80\x80 \"\x02\b\x00'''::bytes)"
E0128 15:36:40.896367 21274 cli/zone.go:239  statement error: pq: unterminated string
SET syntax=modern; INSERT INTO system.zones VALUES (100, '''
                                                         ^

```

### PR DESCRIPTION
**Pull request by jordanlewis**
Add support for hexadecimal literals of the form `x'val'` and `X'val'`, where val contains hexadecimal digits. [The reference documentation](https://dev.mysql.com/doc/refman/5.7/en/hexadecimal-literals.html) requires that such literals default to string type, but the hex literals that we already support (of form `0xval`) default to integer type. For consistency, the newly-supported `x'val'` style literals also default to integer type.

Resolves #4017.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7138)

### CODE REVIEW

**Comment by petermattis** [comment]
@nvanbenschoten Seems like `x'val'` should default to string type. Are there difficulties in having `x'val'` and `0xval` have different behaviors?

**Comment by jordanlewis** [comment]
@petermattis @nvanbenschoten I don't think there are major difficulties in doing so. I did it this way because it seemed like since we've changed the behavior of `0xval` from defaulting to string to defaulting to integer, we should also do the same thing for `x'val'`. On the other hand, it makes sense that `0xval` would default to integer so I could understand if we wanted to violate the convention set in the linked documentation just for `0xval`.

**Comment by petermattis** [comment]
`x'val'` looks like a string constant to me. And #4017 was concerned with using hexadecimal string constants. I don't see any confusion treating `x'val'` as a string and `0xval` as an integer. Feel free to argue that I'm mistaken about this.

**Comment by jordanlewis** [comment]
Makes sense to me. I got distracted from the original discussion by trying to follow that documentation. I'll update the patch to produce strings.

**Comment by petermattis** [comment]
@jordanlewis FYI, there was no need to close the PR while you're working on it. Doesn't hurt to have done so, but it wasn't necessary.

**Comment by jordanlewis** [comment]
`x'val'` literals now produce strings by converting each pair of hexadecimal characters in `val` into a byte.

**Comment by nvanbenschoten** [comment]
Nice! Glad to see this change.

<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary>
> `x'val'` literals now produce strings by converting each pair of hexadecimal characters in `val` into a byte.
> 
> 
> 
> One caveat to the approach I took is that the lexer directly converts the value into a string, losing the `x'val'` representation forever. I'm not sure if this is acceptable.
</details>


---

Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[sql/parser/scan.go, line 265 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7138#-KJrB9o-6ArgsbPrts9h:-KJrB9o-6ArgsbPrts9i:-1167235683) ([raw file](https://github.com/cockroachdb/cockroach/blob/92fcc7428966642498d8ec7fc56a53008e771aad/sql/parser/scan.go#L265)):*
> ```Go
> 			// [xX]'[a-f0-9]'
> 			s.pos++
> 			if s.scanString(lval, t, false) {
> ```

Does `scanString` for hex values play correctly with the different Syntaxes?

---

*[sql/parser/scan.go, line 268 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7138#-KJrBTw8EL4s6kZYoL5H:-KJrBTw8EL4s6kZYoL5I:1254365636) ([raw file](https://github.com/cockroachdb/cockroach/blob/92fcc7428966642498d8ec7fc56a53008e771aad/sql/parser/scan.go#L268)):*
> ```Go
> 				stringBytes, err := hex.DecodeString(lval.str)
> 				if err != nil {
> 					// odd number of characters or invalid byte
> ```

https://github.com/golang/go/wiki/CodeReviewComments#comment-sentences

---

*[sql/parser/scan_test.go, line 407 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7138#-KJrAK2xMDCWeUr1RQ2x:-KJrAK2yDSDvIFJrFCf1:-1211980997) ([raw file](https://github.com/cockroachdb/cockroach/blob/92fcc7428966642498d8ec7fc56a53008e771aad/sql/parser/scan_test.go#L407)):*
> ```Go
> 		{`00x0x`, "invalid hexadecimal literal"},
> 		{`08`, "could not make constant int from literal \"08\""},
> 		{`x'zzz'`, "invalid hexadecimal literal"},
> ```

Now that we support hexidecimal strings and numbers, we should split the error code. `invalid hexadecimal string literal` or something.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7138#-:-KJrBr9z3d5qEuzUFmr9:1465554711)*

**Comment by jordanlewis** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[sql/parser/scan.go, line 265 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7138#-KJrB9o-6ArgsbPrts9h:-KJrEATyC_ya0z0Rbm42:1653826106) ([raw file](https://github.com/cockroachdb/cockroach/blob/92fcc7428966642498d8ec7fc56a53008e771aad/sql/parser/scan.go#L265)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Does `scanString` for hex values play correctly with the different Syntaxes?
</details>
I don't know. I'll follow up offline.

---

*[sql/parser/scan.go, line 268 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7138#-KJrBTw8EL4s6kZYoL5H:-KJrDmSHWV0K-ZRJM-2W:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/92fcc7428966642498d8ec7fc56a53008e771aad/sql/parser/scan.go#L268)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> https://github.com/golang/go/wiki/CodeReviewComments#comment-sentences
</details>
Done.

---

*[sql/parser/scan_test.go, line 407 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7138#-KJrAK2xMDCWeUr1RQ2x:-KJrDpeeC4r3yT66FQHD:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/92fcc7428966642498d8ec7fc56a53008e771aad/sql/parser/scan_test.go#L407)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Now that we support hexidecimal strings and numbers, we should split the error code. `invalid hexadecimal string literal` or something.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7138)*

**Comment by jordanlewis** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[sql/parser/scan.go, line 265 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7138#-KJrB9o-6ArgsbPrts9h:-KJrGu9hBbVHkgM6sRTB:1869219370) ([raw file](https://github.com/cockroachdb/cockroach/blob/92fcc7428966642498d8ec7fc56a53008e771aad/sql/parser/scan.go#L265)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary>
> I don't know. I'll follow up offline.
</details>
I talked with Nathan. We concluded that it's probably fine to just let the hex decoding fail if someone passes in syntax-specific characters, especially since we pass in false for `allowEscapes` to scanString.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7138)*

**Comment by tamird** [comment]
Reviewed 4 of 5 files at r3, 1 of 1 files at r4, 1 of 2 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[sql/parser/scan.go, line 265 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7138#-KJrB9o-6ArgsbPrts9h:-KJrInra1LIr4ZhmT3N4:128383400) ([raw file](https://github.com/cockroachdb/cockroach/blob/92fcc7428966642498d8ec7fc56a53008e771aad/sql/parser/scan.go#L265)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary>
> I talked with Nathan. We concluded that it's probably fine to just let the hex decoding fail if someone passes in syntax-specific characters, especially since we pass in false for `allowEscapes` to scanString.
</details>
Can you add a test case to exercise this?

---

*[sql/parser/scan_test.go, line 407 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7138#-KJrAK2xMDCWeUr1RQ2x:-KJrIm1ZfD4dm1wyf0uS:-1452059108) ([raw file](https://github.com/cockroachdb/cockroach/blob/92fcc7428966642498d8ec7fc56a53008e771aad/sql/parser/scan_test.go#L407)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary>
> Done.
</details>
I think you forgot to update the test. Also, the `scanNumber` case probably wants a similar update while you're here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7138)*

**Comment by jordanlewis** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[sql/parser/scan.go, line 265 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7138#-KJrB9o-6ArgsbPrts9h:-KJrJJc5Ilva2IKF7a3r:1085483994) ([raw file](https://github.com/cockroachdb/cockroach/blob/92fcc7428966642498d8ec7fc56a53008e771aad/sql/parser/scan.go#L265)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Can you add a test case to exercise this?
</details>
Will do.

---

*[sql/parser/scan_test.go, line 407 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7138#-KJrAK2xMDCWeUr1RQ2x:-KJrJEB129xHiHs-1lws:1943552792) ([raw file](https://github.com/cockroachdb/cockroach/blob/92fcc7428966642498d8ec7fc56a53008e771aad/sql/parser/scan_test.go#L407)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I think you forgot to update the test. Also, the `scanNumber` case probably wants a similar update while you're here.
</details>
Whoops, thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7138)*

**Comment by tamird** [comment]
:lgtm:

<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Nice! Glad to see this change.
</details>


---

Reviewed 3 of 4 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7138#-:-KJrMdLqxVWEwbxyzEAs:1417088721)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[sql/parser/scan.go, line 265 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7138#-KJrB9o-6ArgsbPrts9h:-KJrofGlmGvji64qBI1c:948389852) ([raw file](https://github.com/cockroachdb/cockroach/blob/92fcc7428966642498d8ec7fc56a53008e771aad/sql/parser/scan.go#L265)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary>
> Will do.
</details>
It's mildly unfortunate for `scanString` to scan into a `buf []byte`, then convert that to a `string` before returning just so it can be assed to `hex.DecodeString`. It might be better to pass an additional flag to `scanString` so that we could call `hex.Decode(buf)` instead, avoiding an allocation and a copy. Also, it looks like `hex.Decode(buf, buf)` works as the writing to the output trails the input. This would avoid an additional allocation. Let's file an issue about this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7138)*

**Comment by jordanlewis** [comment]
@petermattis Good point. I've opened #7156 to address this.

**Comment by jseldess** [comment]
Docs updated with PR #https://github.com/cockroachdb/docs/pull/392

**Pull request merged**
