### PR TITLE
roachtest: add README to `mixedversion` package

### PR DESCRIPTION
**Pull request by renatolabs**
This documentation covers an overview of the testing infrastructure, walkthrough of a working example, some of the best practices, debugging guidance, among other things.

Epic: CRDB-19321

Release note: None

### CODE REVIEW

**Comment by renatolabs** [comment]
Probably more pleasant to read/review the rendered Markdown directly:

https://github.com/renatolabs/cockroach/tree/rc/mixedversion-readme/pkg/cmd/roachtest/roachtestutil/mixedversion

**Review by srosenberg — APPROVED** [review]
This PR is on fire, terrific `README`! I am going to add a couple more external reviewers to eliminate my own bias :)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106332#-:-NZhu32N9bzt8VPOVPzl:b65tvia)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, and @smg260)

___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/README.md` line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106332#-NZhtKeK2IJtBg1gEmpp:-NZhtKeK2IJtBg1gEmpq:b-4j8ceh) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac79bc0750e6737b84a3d32a65353b801e33c7ea/pkg/cmd/roachtest/roachtestutil/mixedversion/README.md#L116)):*
> ```Markdown
> 
> 			// Drops _all_ tables  created thus far.
> 			dropAllTables := func(ctx context.Context, l *logger.Logger, rng *rand.Rand, h *mixedversion.Helper) error {
> ```

I'd suffix this and the others with `Step` to reinforce API concepts and disambiguate `dropTables`, which isn't consequential since it's only a helper function.

**Comment by THardy98** [comment]
Nice `README`, thank you for this. I'm positive this will help people migrate toward using this framework for mixed version testing.

Not sure if this is just my own interpretation:

> a downgrade may happen -- that is, nodes are once again restarted, and the newer binary is replaced by an older binary. This simulates the need for the operator to perform a downgrade in case the cluster cannot be upgraded for some reason. **This only happens if the `cluster.preserve_downgrade_option` cluster setting has been set appropriately prior to any node being upgraded;**

To me, this implies that the user of the framework needs to set the cluster setting value to test (or not test) how their feature works with downgrades.

**Review by knz — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106332)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @herkolategan, @msbutler, @renatolabs, and @smg260)

___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/README.md` line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106332#-NZlJUaL1dlokM7RjLPG:-NZlJUaMASLO9NTY3Aza:b51xago) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac79bc0750e6737b84a3d32a65353b801e33c7ea/pkg/cmd/roachtest/roachtestutil/mixedversion/README.md#L24)):*
> ```Markdown
> Before we dive into the example, it's useful to define some terms used by the `mixedversion` API:
> 
> * **Test plan**: `mixedversion` tests are _randomized_: each run of the same test will exercise a different ordering of certain events, represented by a different test plan. Before the cluster is set up, a test plan is generated that outlines the _steps_ the test will take. The test plan is printed at the beginning of execution.
> ```

this is the best part for UX IMHO :100: 

(Another part I'm expecting—but I haven't tried yet—is that the current binary version and logical version get printed in logs at every step and in case of failure.)
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/README.md` line 317 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106332#-NZlK4Yg-58ueDlrovoc:-NZlK4Yg-58ueDlrovod:b-ubpzzc) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac79bc0750e6737b84a3d32a65353b801e33c7ea/pkg/cmd/roachtest/roachtestutil/mixedversion/README.md#L317)):*
> ```Markdown
> That said, there are measures we can take to make failures _more likely_ to be reproducible. When a [failure occurs](#understanding-the-test-failure), the `mixedversion` framework logs the _random seed_ used in that particular run. By re-running the test with the same seed, we guarantee that:
> 
> * the same test plan is generated (i.e., ordering of events, as performed by the test, is the same);
> ```

Technically we'd be in an even more comfortable place if there was a way to serialize the plan and re-run with the specific plan data as input.

This would help when we evolve the test framework  over time: if I have a failure in version X and some seed N is printed, then the framework is modified in version Y, and then someone else tries to reproduce the failure with the seed N they would get a different plan than what X had produced.

By pinning the plan itself instead of the seed, we'd facilitate testing across SHAs.

**Review by renatolabs — COMMENTED** [review]
> To me, this implies that the user of the framework needs to set the cluster setting value to test (or not test) how their feature works with downgrades.

I can see how this can ambiguous. I reworded that sentence to make it clearer that the framework does this automatically, let me know if you have thoughts.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106332#-:-N_5I8Lq30BYlinBZVzg:bb1tscf)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @herkolategan, @knz, @msbutler, @smg260, and @srosenberg)

___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/README.md` line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106332#-NZlJUaL1dlokM7RjLPG:-N_5IK1j1JF38jkOuBDq:bygqm79) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac79bc0750e6737b84a3d32a65353b801e33c7ea/pkg/cmd/roachtest/roachtestutil/mixedversion/README.md#L24)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

this is the best part for UX IMHO :100: 

(Another part I'm expecting—but I haven't tried yet—is that the current binary version and logical version get printed in logs at every step and in case of failure.)
</blockquote></details>

It's not mentioned in the README, but the logs for each step include a "header" like the one below:

```
[mixed-version-test/21_run-plan-and-run-backups] 07:54:39 runner.go:348: ---------- STARTING (21): run "plan and run backups" ----------
[mixed-version-test/21_run-plan-and-run-backups] 07:54:39 runner.go:362: binary versions: [1: 23.1, 2: 23.1-10, 3: 23.1, 4: 23.1-10]
[mixed-version-test/21_run-plan-and-run-backups] 07:54:39 runner.go:363: cluster versions: [1: 23.1, 2: 23.1, 3: 23.1, 4: 23.1]
```
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/README.md` line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106332#-NZhtKeK2IJtBg1gEmpp:-N_5I3Jx6ecGvLwKj4ce:b-9jj02m) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac79bc0750e6737b84a3d32a65353b801e33c7ea/pkg/cmd/roachtest/roachtestutil/mixedversion/README.md#L116)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

I'd suffix this and the others with `Step` to reinforce API concepts and disambiguate `dropTables`, which isn't consequential since it's only a helper function.
</blockquote></details>

Makes sense, added the `Step` suffix.
___
*[`pkg/cmd/roachtest/roachtestutil/mixedversion/README.md` line 317 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106332#-NZlK4Yg-58ueDlrovoc:-N_5JNlX57Rjj_NaOpeD:b-1ywa3q) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac79bc0750e6737b84a3d32a65353b801e33c7ea/pkg/cmd/roachtest/roachtestutil/mixedversion/README.md#L317)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Technically we'd be in an even more comfortable place if there was a way to serialize the plan and re-run with the specific plan data as input.

This would help when we evolve the test framework  over time: if I have a failure in version X and some seed N is printed, then the framework is modified in version Y, and then someone else tries to reproduce the failure with the seed N they would get a different plan than what X had produced.

By pinning the plan itself instead of the seed, we'd facilitate testing across SHAs.
</blockquote></details>

Good observation, this is definitely something I've been thinking about. Serializing the plan and taking that as input would be an option here. Something else that I wish was possible when debugging these failures is being able to say "reuse all the same random choices as this failed run, except for this one random choice -- use another value instead".

More concretely, if (say) a test picked a random node (1-4) at a certain point, I wish it was possible to change just that one decision and have the test behave the same otherwise. This could involve a similar serialization + input mechanism, though I haven't spent a lot of time designing how this could work.

For now, if the test or framework have changed such that the same seed no longer produces the same test, the recommendation is to use the same roachtest SHA. Presumably most of the debugging will happen on cockroach (not in the test itself), so I think this is acceptable in most cases. I want to better understand when / how this becomes a limiting factor so that any solutions we design solve the actual problems with this approach.

**Pull request merged**
