### PR TITLE
ui: fix stmt not being found

### PR DESCRIPTION
**Pull request by maryliag**
When creating a transaction fingerprint text based on
statement ids, if the statement was not found, it was
crashing and making the Transactions Page to not load.
This commit handles the case.

Release note (bug fix): Transaction page no longer crashes when
a statement is not found.

### CODE REVIEW

**Review by Azhng — APPROVED** [review]
Oof 😅

**Review by jaylim-crl — APPROVED** [review]
:lgtm: Do we know why the statement was not found in the first place? :thinking: I wonder if the statement being not found is expected.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71596#-:-Mm0b8Qk46Bl4vSu78tO:b-6suckg)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag)

**Review by maryliag — COMMENTED** [review]
I don't know for sure, could be a situation where the statement was cleared (or not persisted properly) after the transaction was finished but before the UI needed the info for calculating the text on that particular function (which may explain why sometimes the page was loading normally for me and sometimes not). Once I cleared the stats on that cluster the page loaded normally. It's not something that should be happening (the reason why we never saw this before), so we will continue to investigate but at least this fix makes it so the page doesn't crash

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71596#-:-Mm0eUZhBkxSNxTAHHrE:b-sslvd7)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag)

**Pull request merged**
