### PR TITLE
parser, backupccl: adds logic to support RESTORE of KMS encrypted BACKUPs

### PR DESCRIPTION
**Pull request by adityamaru**
Commit 1: adds the KMS option to RESTORE grammar.

Commit 2: adds logic to RESTORE from encrypted BACKUPs. Adds redaction logic for BACKUP/RESTORE job descriptions written to system.jobs.

Informs: #50937

### CODE REVIEW

**Comment by adityamaru** [comment]
Built on top of #52302 so once I get a stamp on that I shall rebase.

**Comment by adityamaru** [comment]
Rebased and ready for review @miretskiy!

**Review by miretskiy — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52434)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @dt)

___
*[pkg/ccl/backupccl/backup_test.go, line 3449 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52434#-MEXf-Hg7gPTP9rTXMUk:-MEXf-Hg7gPTP9rTXMUl:b-3uya1f) ([raw file](https://github.com/cockroachdb/cockroach/blob/0456b8adc24dcb7db36c084910ac58b2898f2292/pkg/ccl/backupccl/backup_test.go#L3449)):*
> ```Go
> 	var multiRegionKMSURIs []string
> 	for i, _ := range regionEnvVariables {
> 		kmsURI, _ := getAWSKMSURI(t, regionEnvVariables[i], keyIDEnvVariables[i])
> ```

should we error if variable not set?
___
*[pkg/ccl/backupccl/restore_planning.go, line 883 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52434#-MEXfr1AETbn2SpKpJ0C:-MEXfr1AETbn2SpKpJ0D:b2m5ppb) ([raw file](https://github.com/cockroachdb/cockroach/blob/0456b8adc24dcb7db36c084910ac58b2898f2292/pkg/ccl/backupccl/restore_planning.go#L883)):*
> ```Go
> // redactKMSURI redacts the Master Key ID and the ExternalStorage secret
> // credentials.
> func redactKMSURI(kmsURI string) (string, error) {
> ```

do you think it makes sense to move this to a util like file (looks like it's called from both backup and restore)?
___
*[pkg/sql/parser/sql.y, line 2426 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52434#-MEXdIH75wVFJ_sCSjWm:-MEXdIH75wVFJ_sCSjWn:bvsb6pn) ([raw file](https://github.com/cockroachdb/cockroach/blob/0456b8adc24dcb7db36c084910ac58b2898f2292/pkg/sql/parser/sql.y#L2426)):*
> ```Yacc
> 	{
>     $$.val = &tree.RestoreOptions{DecryptionKMSURI: $3.stringOrPlaceholderOptList()}
> 	}
> ```

nit: reviewable shows tabs here.  Can you double check?
___
*[pkg/sql/sem/tree/backup.go, line 377 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52434#-MEXdaxz0kFhF8Gn9NLZ:-MEXdaxz0kFhF8Gn9NL_:bsp2rra) ([raw file](https://github.com/cockroachdb/cockroach/blob/0456b8adc24dcb7db36c084910ac58b2898f2292/pkg/sql/sem/tree/backup.go#L377)):*
> ```Go
> 		cmp.Equal(o.DecryptionKMSURI, options.DecryptionKMSURI) &&
> 		o.EncryptionPassphrase == options.EncryptionPassphrase &&
> 		o.IntoDB == options.IntoDB
> ```

these URIs make me sad.  I wish we used pointer instead of the list here so that we don't have to spell out every field.

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52434)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @miretskiy)

___
*[pkg/ccl/backupccl/backup_test.go, line 3449 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52434#-MEXf-Hg7gPTP9rTXMUk:-MEYBeL_EXlfYNecKK--:bp508b6) ([raw file](https://github.com/cockroachdb/cockroach/blob/0456b8adc24dcb7db36c084910ac58b2898f2292/pkg/ccl/backupccl/backup_test.go#L3449)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

should we error if variable not set?
</blockquote></details>

we already do in `getAWSKMSURI`. We check if we can os.GetEnv(...) for both the region and keyID.
___
*[pkg/ccl/backupccl/restore_planning.go, line 883 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52434#-MEXfr1AETbn2SpKpJ0C:-MEYERJ08YPNBBs2YBsq:b-dzkabo) ([raw file](https://github.com/cockroachdb/cockroach/blob/0456b8adc24dcb7db36c084910ac58b2898f2292/pkg/ccl/backupccl/restore_planning.go#L883)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

do you think it makes sense to move this to a util like file (looks like it's called from both backup and restore)?
</blockquote></details>

done, introduced a cloudimpl/kms.go file similar to external_storage.go which holds some util methods.
___
*[pkg/sql/parser/sql.y, line 2426 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52434#-MEXdIH75wVFJ_sCSjWm:-MEYCCBo00ftZlIXkej1:bmq96fn) ([raw file](https://github.com/cockroachdb/cockroach/blob/0456b8adc24dcb7db36c084910ac58b2898f2292/pkg/sql/parser/sql.y#L2426)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

nit: reviewable shows tabs here.  Can you double check?
</blockquote></details>

Checked, it is spaces in the editor.
___
*[pkg/sql/sem/tree/backup.go, line 377 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/52434#-MEXdaxz0kFhF8Gn9NLZ:-MEYJ3A43ZN96ltiFfMX:b-venat2) ([raw file](https://github.com/cockroachdb/cockroach/blob/0456b8adc24dcb7db36c084910ac58b2898f2292/pkg/sql/sem/tree/backup.go#L377)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

these URIs make me sad.  I wish we used pointer instead of the list here so that we don't have to spell out every field.
</blockquote></details>

i agree, I will do a follow up which changes this for both BACKUP/RESTORE because its a problem in both places.

**Comment by adityamaru** [comment]
TFTR!

bors r=miretskiy

**Pull request merged**
