### PR TITLE
vecstore: add encoding and decoding functions

### PR DESCRIPTION
**Pull request by DrewKimball**
This commit adds a set of functions for encoding and decoding the metadata and vectors of a partition. It also adds a test to ensure that round-trip encoding and decoding a partition results in an equivalent partition.

Epic: CRDB-42943

Release note: None

### CODE REVIEW

**Review by mw5h — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136776#-:-ODJG8xo-baxhf1WflN8:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @DrewKimball)

___
*[`pkg/sql/vecindex/vecstore/encoding.go` line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136776#-ODJDkzK3sF0SB7C9-EZ:-ODJDkzK3sF0SB7C9-E_:bez1j5v) ([raw file](https://github.com/cockroachdb/cockroach/blob/f993593e820d44c9750866b0478f122d08512fcc/pkg/sql/vecindex/vecstore/encoding.go#L16)):*
> ```Go
> // EncodePartitionMetadata encodes the metadata for a partition.
> func EncodePartitionMetadata(level Level, centroid vector.T) ([]byte, error) {
> 	// The encoding consists of 8 bytes for the level, and a 4-byte length,
> ```

I know we don't want to change this after release, but 64bits of level is a lot.

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136776)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @mw5h)

___
*[`pkg/sql/vecindex/vecstore/encoding.go` line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136776#-ODJDkzK3sF0SB7C9-EZ:-ODK7C804zDPTGMhHLyo:b564cmx) ([raw file](https://github.com/cockroachdb/cockroach/blob/f993593e820d44c9750866b0478f122d08512fcc/pkg/sql/vecindex/vecstore/encoding.go#L16)):*
<details><summary><i>Previously, mw5h (Matt White) wrote…</i></summary><blockquote>

I know we don't want to change this after release, but 64bits of level is a lot.
</blockquote></details>

I have no objection to us switching Level to be a uint32.
___
*[`pkg/util/vector/vector_set.go` line 195 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136776#-ODKB6il-nETwmDlIkZT:-ODKB6il-nETwmDlIkZU:b-q2rut8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f993593e820d44c9750866b0478f122d08512fcc/pkg/util/vector/vector_set.go#L195)):*
> ```Go
> }
> 
> // Equal returns true if this set is equal to the other set. Two sets are equal
> ```

Can you add a unit test for this?
___
*[`pkg/sql/vecindex/vecstore/encoding.go` line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136776#-ODK87Fm6WPYMAaQmzqr:-ODK87Fm6WPYMAaQmzqs:b-3fbhkp) ([raw file](https://github.com/cockroachdb/cockroach/blob/f993593e820d44c9750866b0478f122d08512fcc/pkg/sql/vecindex/vecstore/encoding.go#L37)):*
> ```Go
> }
> 
> // EncodeFullVector encodes a full vector into the given byte slice.
> ```

I think should be named `EncodeUnquantizedVector`, because it's encoding a quantized vector, albeit a trivial quantization algorithm. This makes the naming symmetric with `EncodeRaBitQVector`.
___
*[`pkg/sql/vecindex/vecstore/encoding.go` line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136776#-ODK8p5y46EIO45LMP0j:-ODK8p5y46EIO45LMP0k:b-r2j7bg) ([raw file](https://github.com/cockroachdb/cockroach/blob/f993593e820d44c9750866b0478f122d08512fcc/pkg/sql/vecindex/vecstore/encoding.go#L52)):*
> ```Go
> 
> // DecodePartitionMetadata decodes the metadata for a partition.
> func DecodePartitionMetadata(encMetadata []byte) (Level, vector.T, error) {
> ```

NIT: might be nice to give names to the return values: `(level Level, centroid vector.T, err error)`, to make it more clear that the vector is the centroid.
___
*[`pkg/sql/vecindex/vecstore/encoding.go` line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136776#-ODK9AdS7jueH3SL3Apx:-ODK9AdS7jueH3SL3Apy:bd8a65i) ([raw file](https://github.com/cockroachdb/cockroach/blob/f993593e820d44c9750866b0478f122d08512fcc/pkg/sql/vecindex/vecstore/encoding.go#L64)):*
> ```Go
> // RaBitQuantizedVectorSet. The vector set must have been initialized with the
> // correct number of dimensions.
> func DecodeRaBitQVectorToSet(encVector []byte, vectorSet *quantize.RaBitQuantizedVectorSet) error {
> ```

Do we want to go into a vector set in contexts where this is used? Should we be defining a `quantize.RaBitQuantizedVector` type along with method(s) to use that directly? Or do we expect that we'll call this multiple times with the same vector set, such that we're always just appending to the same set?
___
*[`pkg/sql/vecindex/vecstore/encoding.go` line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136776#-ODK9awrCZzp-Qeb22qL:-ODK9awrCZzp-Qeb22qM:blohbdw) ([raw file](https://github.com/cockroachdb/cockroach/blob/f993593e820d44c9750866b0478f122d08512fcc/pkg/sql/vecindex/vecstore/encoding.go#L86)):*
> ```Go
> 			return err
> 		}
> 		vectorSet.Codes.Data = append(vectorSet.Codes.Data, codeWord)
> ```

I think we should preallocate capacity for `vectorSet.Codes.Data`, so that it will never need to resize multiple times. We can do that using slices.Grow.
___
*[`pkg/sql/vecindex/vecstore/encoding.go` line 143 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136776#-ODKAzPpEOSZ6mp9wxGJ:-ODKAzPqAEPitv8npTPK:b-hgy48r) ([raw file](https://github.com/cockroachdb/cockroach/blob/f993593e820d44c9750866b0478f122d08512fcc/pkg/sql/vecindex/vecstore/encoding.go#L143)):*
> ```Go
> }
> 
> // GetFullVectorChildKeyOffset returns the offset of the child key in an encoded
> ```

Similar to above, I think we should call this `GetUnquantizedVectorChildKeyOffset`.

**Review by DrewKimball — COMMENTED** [review]
TFTRs

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136776#-:-ODQBHmyCZWSf6A3gBZJ:b-814g6a)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @mw5h)

___
*[`pkg/sql/vecindex/vecstore/encoding.go` line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136776#-ODJDkzK3sF0SB7C9-EZ:-ODQBDX4CWWk-aKRcujL:b-h2cna7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f993593e820d44c9750866b0478f122d08512fcc/pkg/sql/vecindex/vecstore/encoding.go#L16)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I have no objection to us switching Level to be a uint32.
</blockquote></details>

I added a commit to swap it to `uint32`.
___
*[`pkg/sql/vecindex/vecstore/encoding.go` line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136776#-ODK87Fm6WPYMAaQmzqr:-ODQ5HDGCz2C4i5Iwk7e:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f993593e820d44c9750866b0478f122d08512fcc/pkg/sql/vecindex/vecstore/encoding.go#L37)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I think should be named `EncodeUnquantizedVector`, because it's encoding a quantized vector, albeit a trivial quantization algorithm. This makes the naming symmetric with `EncodeRaBitQVector`.
</blockquote></details>

Done.
___
*[`pkg/sql/vecindex/vecstore/encoding.go` line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136776#-ODK8p5y46EIO45LMP0j:-ODQ7UBL-Y2GXVljWOrT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f993593e820d44c9750866b0478f122d08512fcc/pkg/sql/vecindex/vecstore/encoding.go#L52)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: might be nice to give names to the return values: `(level Level, centroid vector.T, err error)`, to make it more clear that the vector is the centroid.
</blockquote></details>

Done.
___
*[`pkg/sql/vecindex/vecstore/encoding.go` line 64 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136776#-ODK9AdS7jueH3SL3Apx:-ODQ7iAw58XCZlZNbtlQ:b-upsqpe) ([raw file](https://github.com/cockroachdb/cockroach/blob/f993593e820d44c9750866b0478f122d08512fcc/pkg/sql/vecindex/vecstore/encoding.go#L64)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Do we want to go into a vector set in contexts where this is used? Should we be defining a `quantize.RaBitQuantizedVector` type along with method(s) to use that directly? Or do we expect that we'll call this multiple times with the same vector set, such that we're always just appending to the same set?
</blockquote></details>

The expectation for now is that we'd be calling this on the same vector set. We might want to change that for the distance-estimation code path in the future, but I think it's fine to defer that until we have benchmarks indicating it'll be useful.
___
*[`pkg/sql/vecindex/vecstore/encoding.go` line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136776#-ODK9awrCZzp-Qeb22qL:-ODQ95pfBKEhrEsXCKI8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f993593e820d44c9750866b0478f122d08512fcc/pkg/sql/vecindex/vecstore/encoding.go#L86)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I think we should preallocate capacity for `vectorSet.Codes.Data`, so that it will never need to resize multiple times. We can do that using slices.Grow.
</blockquote></details>

Done.
___
*[`pkg/sql/vecindex/vecstore/encoding.go` line 143 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136776#-ODKAzPpEOSZ6mp9wxGJ:-ODQ5Kbm8lLH8utKwJBe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f993593e820d44c9750866b0478f122d08512fcc/pkg/sql/vecindex/vecstore/encoding.go#L143)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Similar to above, I think we should call this `GetUnquantizedVectorChildKeyOffset`.
</blockquote></details>

Done.
___
*[`pkg/util/vector/vector_set.go` line 195 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/136776#-ODKB6il-nETwmDlIkZT:-ODQ7BqZDlRJ3oonDfYU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f993593e820d44c9750866b0478f122d08512fcc/pkg/util/vector/vector_set.go#L195)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Can you add a unit test for this?
</blockquote></details>

Done.

**Review by mw5h — APPROVED** [review]
> Reviewed 1 of 7 files at r2, 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136776)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball)

**Comment by DrewKimball** [comment]
I'm making two changes:
* As discussed internally [here](https://cockroachlabs.slack.com/archives/C07RZC56423/p1733519165731099?thread_ts=1733450505.161719&cid=C07RZC56423), it makes most sense to use the `ChildKey` as the suffix of the key for a vector. Therefore, the test no longer adds the `ChildKey` entries to the values, and instead tracks them separately. We can also remove `GetRaBitQChildKeyOffset` and `GetUnquantizedVectorChildKeyOffset`, which is a nice simplification.
* Since the primary key for a leaf vector is already encoded into a byte slice, we don't need to use `EncodeBytesAscending`, and can just append the bytes directly.

**Review by andy-kimball — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136776#-:-ODT86Qe-HYjNKQJRAGq:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mw5h)

**Pull request merged**
