### PR TITLE
bazel: upgrade `rules_go`, `go_googleapis`

### PR DESCRIPTION
**Pull request by rickystewart**
Epic: none

Release note: None

### CODE REVIEW

**Comment by rickystewart** [comment]
#94090 for taking care of that deprecation.

**Review by healthy-pod — APPROVED** [review]

**Comment by rickystewart** [comment]
bors r=healthy-pod

**Comment by rickystewart** [comment]
Ah, the unused lint is still not fully functional yet. I'll need to make a tweak upstream probably, give me a second.

**Comment by rickystewart** [comment]
bors r=healthy-pod

**Pull request merged**
