### PR TITLE
sql,security: add parsing and validation of SUBJECT role option

### PR DESCRIPTION
**Pull request by rafiss**
See individual commits.

informs https://github.com/cockroachdb/cockroach/issues/110616
fixes CRDB-35939
Epic CRDB-34126

Release note (enterprise change): Added a new SUBJECT role option. This
role option can be set to a subject distinguished name in RFC2253 or
RFC4514 format. If set, then during client certificate authentication,
a certificate with the given distinguished name can be used to
authenticate the role whose SUBJECT was configured. The root user cannot
have its SUBJECT configured.

### CODE REVIEW

**Review by bdarnell — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, 29 of 30 files at r2, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119135)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`-- commits` line 12 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119135#-Nqa57c0Bs76rAdPwSKB):*
This gets the sense of the change backwards: it's already true by default that a cert can be used (matching only on the CN and ignoring the rest of the DN). The change is that when a subject is set, certs that don't match the subject DN will be rejected. 
___
*[`-- commits` line 14 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119135#-Nqa5oOW2m0d_x1rR6fk):*
I would leave out any mention of the root user for now. "cannot have its subject configured" is unclear. In context of the rest of the message as written it implies that root cannot log in with a cert, when in fact it can use a cert with fewer checks than regular users. That's an unacceptable outcome so we're going to have to do something about it but we haven't settled on the design yet, so we can wait to mention root until we've decided that. 
___
*[`pkg/security/distinguishedname/parse.go` line 18 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119135#-Nqa5U1x-6e3iFuYBIAy:-Nqa5U1x-6e3iFuYBIAz:b-bfq7n3) ([raw file](https://github.com/cockroachdb/cockroach/blob/16c455f07a0e855fa992cd4cf22586834b87f4dc/pkg/security/distinguishedname/parse.go#L18)):*
> ```Go
> )
> 
> // ValidateDN validates a distinguished name string to verify that it is
> ```

As discussed on slack, we want an additional validation that the CN field matches the user name, so we'll need either a more complicated interface here or do that part of the validation at a different level. 
___
*[`pkg/sql/user.go` line 88 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/119135#-Nqa4whPE6b_W2HkeJJU:-Nqa4whPE6b_W2HkeJJV:bfe4uxd) ([raw file](https://github.com/cockroachdb/cockroach/blob/194a59595bf144f3fbb1eba8cc671d236a5d4211/pkg/sql/user.go#L88)):*
> ```Go
> 	isSuperuser bool,
> 	defaultSettings []sessioninit.SettingsCacheEntry,
> 	subject *ldap.DN,
> ```

Should probably be a separate PR, but this function's return values are overdue for a refactoring into a struct.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119135)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @bdarnell)

___
*[`-- commits` line 12 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119135#-Nqa57c0Bs76rAdPwSKB):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This gets the sense of the change backwards: it's already true by default that a cert can be used (matching only on the CN and ignoring the rest of the DN). The change is that when a subject is set, certs that don't match the subject DN will be rejected.
</blockquote></details>

done
___
*[`-- commits` line 14 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119135#-Nqa5oOW2m0d_x1rR6fk):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I would leave out any mention of the root user for now. "cannot have its subject configured" is unclear. In context of the rest of the message as written it implies that root cannot log in with a cert, when in fact it can use a cert with fewer checks than regular users. That's an unacceptable outcome so we're going to have to do something about it but we haven't settled on the design yet, so we can wait to mention root until we've decided that.
</blockquote></details>

that makes sense, done
___
*[`pkg/security/distinguishedname/parse.go` line 18 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/119135#-Nqa5U1x-6e3iFuYBIAy:-NqdCP2_42pWKGM60BQe:b-1lqoaz) ([raw file](https://github.com/cockroachdb/cockroach/blob/16c455f07a0e855fa992cd4cf22586834b87f4dc/pkg/security/distinguishedname/parse.go#L18)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

As discussed on slack, we want an additional validation that the CN field matches the user name, so we'll need either a more complicated interface here or do that part of the validation at a different level.
</blockquote></details>

i'll add the SQLUsername to the parameters here.
___
*[`pkg/sql/user.go` line 88 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/119135#-Nqa4whPE6b_W2HkeJJU:-NqdCct85CskpVskCNgW:b-t77xc3) ([raw file](https://github.com/cockroachdb/cockroach/blob/194a59595bf144f3fbb1eba8cc671d236a5d4211/pkg/sql/user.go#L88)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Should probably be a separate PR, but this function's return values are overdue for a refactoring into a struct.
</blockquote></details>

agreed

**Review by bdarnell — APPROVED** [review]
> Reviewed 1 of 37 files at r4, 27 of 31 files at r5, 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119135)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @BabuSrithar and @rafiss)

___
*[`pkg/security/distinguishedname/parse.go` line 37 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/119135#-NqzhTWY4jmWtrVM1puq:-NqzhTWY4jmWtrVM1pur:b-twh1x7) ([raw file](https://github.com/cockroachdb/cockroach/blob/748c9725d716545b5283435fb0cc8b6e85ba828b/pkg/security/distinguishedname/parse.go#L37)):*
> ```Go
> 				}
> 				sawCN = true
> 				if attr.Value != u.Normalized() {
> ```

Do we want to normalize (lowercase?) the attr.Value too?

**Review by rafiss — COMMENTED** [review]
tftr!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119135#-:-NrqiMaF0tZNIGEj7bIR:bjpalj3)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @BabuSrithar and @bdarnell)

___
*[`pkg/security/distinguishedname/parse.go` line 37 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/119135#-NqzhTWY4jmWtrVM1puq:-NrqgVEP1CWA39ppzSK7:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/748c9725d716545b5283435fb0cc8b6e85ba828b/pkg/security/distinguishedname/parse.go#L37)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Do we want to normalize (lowercase?) the attr.Value too?
</blockquote></details>

done

**Pull request merged**
