### PR TITLE
[release-21.2] Revert dropping traces from kv to tenant

### PR DESCRIPTION
**Pull request by dhartunian**
This reverts commit fc95ad84dd207165b59d1d37ff5f47c3da07133a.
---
This PR restores the ability for tenant traces to see unstructured recordings from the KV layer.

Please see note in #71694: https://github.com/cockroachdb/cockroach/issues/71694#issuecomment-983113997

The need to enforce such strict redaction of traces for tenant queries is not necessary. Customer views into the KV layer will be necessary in order to debug query execution in multi-tenant settings. Redaction is certainly needed at this boundary but must be configured more carefully. Further PRs as necessitated by #58610 and #71694 will tackle these issues on `master` (where trace redaction is still available) and will be backported to the release branch as needed.

This PR restores tracing into KV for tenants and unblocks the ability for serverless to use the `release-21.2` branch.

Release note: Tracing queries from tenants will now include unstructured log messages from the kv layer.

### CODE REVIEW

**Review by abarganier — COMMENTED** [review]
Looks good - this seems like the right approach for undoing this work while we find a better solution.

Do we need to revert the associated test that was added to trace redaction as well? See https://github.com/cockroachdb/cockroach/pull/70562/commits/e0acedad5e71899cd1ff6afcb4dd5cead0756bdc

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73320#-:-MpqoqDG5SrK4hxcJvCD:b-ffqpcq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @knz, and @tbg)

**Comment by dhartunian** [comment]
Yep, thx for the link @abarganier I'll add that revert to this PR.

**Review by abarganier — APPROVED** [review]
:lgtm:!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73320#-:-MpqtcAv8QikULpYO4Ga:bg7igkw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei, @knz, and @tbg)

**Comment by dhartunian** [comment]
As discussed with @abarganier and @rimadeodhar, closing this in favor of going back to #73117 with additional tweaks. Sorry for the churn.

**Pull request closed without merging**
