### PR TITLE
rfc: add vectorized external storage RFC

### PR DESCRIPTION
**Pull request by asubiotto**
Release note: None

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42546)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @danhhz, @jordanlewis, @petermattis, and @yuzefovich)

___
*[docs/RFCS/20191113_vectorized_external_storage.md, line 118 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42546#-Lu0X06kA7eB177fx7KR:-Lu0X06kA7eB177fx7KS:b-x31h0q) ([raw file](https://github.com/cockroachdb/cockroach/blob/9266dfd43bedfbd5034ee945d81252109f5dfbb3/docs/RFCS/20191113_vectorized_external_storage.md#L118)):*
> ```Markdown
> The flat file `Queue` implementation will have knobs to configure
> the in-memory buffer size to amortize write overhead, and the maximum
> size of a file, after which it will roll over to a new file. Different
> ```

Can you elaborate on how the files for a particular `Queue` will be structured? Are they going to be named in some way, or will they have random names with all of the indexing from `Queue` to list of files kept in memory? While there isn't a need for this data to be persistent, there is an argument for having some on disk structure for observability. 
___
*[docs/RFCS/20191113_vectorized_external_storage.md, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42546#-Lu0WR4gBymb6Ks43E1h:-Lu0WR4gBymb6Ks43E1i:bx3l08l) ([raw file](https://github.com/cockroachdb/cockroach/blob/9266dfd43bedfbd5034ee945d81252109f5dfbb3/docs/RFCS/20191113_vectorized_external_storage.md#L151)):*
> ```Markdown
> 
> The benchmark used to test the performance of both queue implementations is
> a simple write-everything then read-everything benchmark run on a personal
> ```

Sync performance on the Mac laptops is very very bad. Were you periodically syncing the file for the file-based queue implementation? If not, you might have been testing the performance of the OS buffer cache. 
___
*[docs/RFCS/20191113_vectorized_external_storage.md, line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42546#-Lu0VsMN9TNniXPJHg6X:-Lu0VsMN9TNniXPJHg6Y:bv7u2mo) ([raw file](https://github.com/cockroachdb/cockroach/blob/9266dfd43bedfbd5034ee945d81252109f5dfbb3/docs/RFCS/20191113_vectorized_external_storage.md#L163)):*
> ```Markdown
> Find
> 
> Given these graphs, a fixed file size of `512MiB` was chosen for the flat queue
> ```

`512MiB` is quite large. What is the trade off for using a smaller size? Does the file need to be read in its entirety?

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42546)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz, @jordanlewis, @petermattis, and @yuzefovich)

___
*[docs/RFCS/20191113_vectorized_external_storage.md, line 118 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42546#-Lu0X06kA7eB177fx7KR:-Lu3hT7a03LrLvoDtlaw:b-vtw6pu) ([raw file](https://github.com/cockroachdb/cockroach/blob/9266dfd43bedfbd5034ee945d81252109f5dfbb3/docs/RFCS/20191113_vectorized_external_storage.md#L118)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Can you elaborate on how the files for a particular `Queue` will be structured? Are they going to be named in some way, or will they have random names with all of the indexing from `Queue` to list of files kept in memory? While there isn't a need for this data to be persistent, there is an argument for having some on disk structure for observability. 
</blockquote></details>

Updated with a naming scheme. What  sort of observability do you have in mind?
___
*[docs/RFCS/20191113_vectorized_external_storage.md, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42546#-Lu0WR4gBymb6Ks43E1h:-Lu3YC142mTF7DY1I-6k:b-66jnwt) ([raw file](https://github.com/cockroachdb/cockroach/blob/9266dfd43bedfbd5034ee945d81252109f5dfbb3/docs/RFCS/20191113_vectorized_external_storage.md#L151)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Sync performance on the Mac laptops is very very bad. Were you periodically syncing the file for the file-based queue implementation? If not, you might have been testing the performance of the OS buffer cache. 
</blockquote></details>

I wasn't syncing the file-based queue implementation, but I assume this is fine since we disable the WAL and commit batches with the `pebble.NoSync` option. Is that not equivalent? I'll call this out in the meantime.
___
*[docs/RFCS/20191113_vectorized_external_storage.md, line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42546#-Lu0VsMN9TNniXPJHg6X:-Lu3YRTJAijABQv5mC1g:b-eziupb) ([raw file](https://github.com/cockroachdb/cockroach/blob/9266dfd43bedfbd5034ee945d81252109f5dfbb3/docs/RFCS/20191113_vectorized_external_storage.md#L163)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`512MiB` is quite large. What is the trade off for using a smaller size? Does the file need to be read in its entirety?
</blockquote></details>

Based on the graphs, there isn't much of a tradeoff and I chose this simply because it was the amount of data to store. I was hoping to have a discussion about this to increase my understanding about the tradeoffs here, because even though the benchmark only shows a slight improvement for larger files, this only captures the cost of rolling over to another file in the benchmark, so there might be things I'm missing because I'm not thinking about the problem correctly.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42546)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @danhhz, @jordanlewis, and @yuzefovich)

___
*[docs/RFCS/20191113_vectorized_external_storage.md, line 118 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42546#-Lu0X06kA7eB177fx7KR:-Lu5QLlq6TouI7k-CLsC:b-5rwy6q) ([raw file](https://github.com/cockroachdb/cockroach/blob/9266dfd43bedfbd5034ee945d81252109f5dfbb3/docs/RFCS/20191113_vectorized_external_storage.md#L118)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Updated with a naming scheme. What  sort of observability do you have in mind?
</blockquote></details>

I was imagining observability of where space is going on disk. The very first step is what you've done here: provided a common prefix to all of the files for a particular flow. Is it easy to go from flow ID to txn ID?
___
*[docs/RFCS/20191113_vectorized_external_storage.md, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42546#-Lu0WR4gBymb6Ks43E1h:-Lu5RLI33GtYmVVRcqZ1:bfimvqe) ([raw file](https://github.com/cockroachdb/cockroach/blob/9266dfd43bedfbd5034ee945d81252109f5dfbb3/docs/RFCS/20191113_vectorized_external_storage.md#L151)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I wasn't syncing the file-based queue implementation, but I assume this is fine since we disable the WAL and commit batches with the `pebble.NoSync` option. Is that not equivalent? I'll call this out in the meantime.
</blockquote></details>

Pebble (and RocksDB) sync sstables while writing them to avoid building up a large amount of dirty data. This is desirable because Linux tends to behave poorly when there is a lot of dirty data in the OS buffer pool. Poorly being it tends to clean all of the dirty buffers at once which can lead to large latency spikes. The Pebble/RocksDB heuristic is to sync an sstable after every 512kb have been written.

The Pebble code to do this is a wrapper around around `vfs.File`: `vfs.NewSyncingFile`. I think you should use this wrapper for the file-based queue. I suspect it will have some impact on the file-based queue benchmark performance, though I expect the file-based queue will still vastly outperform Pebble/RocksDB.
___
*[docs/RFCS/20191113_vectorized_external_storage.md, line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42546#-Lu0VsMN9TNniXPJHg6X:-Lu5TqZZ7PHEKeMNgIuH:bm1w31d) ([raw file](https://github.com/cockroachdb/cockroach/blob/9266dfd43bedfbd5034ee945d81252109f5dfbb3/docs/RFCS/20191113_vectorized_external_storage.md#L163)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Based on the graphs, there isn't much of a tradeoff and I chose this simply because it was the amount of data to store. I was hoping to have a discussion about this to increase my understanding about the tradeoffs here, because even though the benchmark only shows a slight improvement for larger files, this only captures the cost of rolling over to another file in the benchmark, so there might be things I'm missing because I'm not thinking about the problem correctly.
</blockquote></details>

As you note elsewhere, smaller files may result in more files which may result in having to open more files simultaneously. The number of open file descriptors is limited on some systems (i.e. Windows). Smaller files do give the opportunity for finer granularity in reclaiming space, but I'm not sure if that matters for the use case here.

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42546)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz, @jordanlewis, @petermattis, and @yuzefovich)

___
*[docs/RFCS/20191113_vectorized_external_storage.md, line 118 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42546#-Lu0X06kA7eB177fx7KR:-Lu9V7mQCQYc_YReGmDY:bl8sk4o) ([raw file](https://github.com/cockroachdb/cockroach/blob/9266dfd43bedfbd5034ee945d81252109f5dfbb3/docs/RFCS/20191113_vectorized_external_storage.md#L118)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I was imagining observability of where space is going on disk. The very first step is what you've done here: provided a common prefix to all of the files for a particular flow. Is it easy to go from flow ID to txn ID?
</blockquote></details>

There is currently no way to connect a flow `ID` back to a txn `ID`. In terms of understanding where the space is going on disk, we'll be using the same temporary storage monitors used by external storage in the row execution engine to limit disk usage. The monitors will also be used to displayed disk used per operator through `EXPLAIN ANALYZE`. There is currently no extra observability work planned but I think we would probably reuse information supplied by monitors rather than relying on this naming scheme. Will update the RFC with this.
___
*[docs/RFCS/20191113_vectorized_external_storage.md, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42546#-Lu0WR4gBymb6Ks43E1h:-Lu9uRVn9l0vHLKPcop9:b-ohcdkv) ([raw file](https://github.com/cockroachdb/cockroach/blob/9266dfd43bedfbd5034ee945d81252109f5dfbb3/docs/RFCS/20191113_vectorized_external_storage.md#L151)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Pebble (and RocksDB) sync sstables while writing them to avoid building up a large amount of dirty data. This is desirable because Linux tends to behave poorly when there is a lot of dirty data in the OS buffer pool. Poorly being it tends to clean all of the dirty buffers at once which can lead to large latency spikes. The Pebble/RocksDB heuristic is to sync an sstable after every 512kb have been written.

The Pebble code to do this is a wrapper around around `vfs.File`: `vfs.NewSyncingFile`. I think you should use this wrapper for the file-based queue. I suspect it will have some impact on the file-based queue benchmark performance, though I expect the file-based queue will still vastly outperform Pebble/RocksDB.
</blockquote></details>

Doing this blindly caused the file-based implementation to take a huge hit (4x slower than Pebble). I have some vague ideas why, but I'll discuss this offline with you to get a better understanding.
___
*[docs/RFCS/20191113_vectorized_external_storage.md, line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42546#-Lu0VsMN9TNniXPJHg6X:-Lu9tg49C-p7vFn1k6DL:b-ykczx6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9266dfd43bedfbd5034ee945d81252109f5dfbb3/docs/RFCS/20191113_vectorized_external_storage.md#L163)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

As you note elsewhere, smaller files may result in more files which may result in having to open more files simultaneously. The number of open file descriptors is limited on some systems (i.e. Windows). Smaller files do give the opportunity for finer granularity in reclaiming space, but I'm not sure if that matters for the use case here.
</blockquote></details>

Based on this, it looks like using a larger file size is slightly more beneficial due to a reduced number of file descriptors and rolling over files less frequently (although this cost seems very small).

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42546)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @danhhz, @jordanlewis, @petermattis, and @yuzefovich)

___
*[docs/RFCS/20191113_vectorized_external_storage.md, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42546#-Lu0WR4gBymb6Ks43E1h:-LuCyfTPEtx82SuTLVKa:bkxiwil) ([raw file](https://github.com/cockroachdb/cockroach/blob/9266dfd43bedfbd5034ee945d81252109f5dfbb3/docs/RFCS/20191113_vectorized_external_storage.md#L151)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Doing this blindly caused the file-based implementation to take a huge hit (4x slower than Pebble). I have some vague ideas why, but I'll discuss this offline with you to get a better understanding.
</blockquote></details>

I expected a slow down, but slower than Pebble is completely unexpected.

**Review by asubiotto — COMMENTED** [review]
Updated the RFC with new benchmark numbers after adding syncing PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42546#-:-LveOVBIDpg2gBJoVDjZ:b-p3bs24)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz, @jordanlewis, @petermattis, and @yuzefovich)

___
*[docs/RFCS/20191113_vectorized_external_storage.md, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42546#-Lu0WR4gBymb6Ks43E1h:-LvKoGLr4zvEfFRHOWM_:b50jjfq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9266dfd43bedfbd5034ee945d81252109f5dfbb3/docs/RFCS/20191113_vectorized_external_storage.md#L151)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I expected a slow down, but slower than Pebble is completely unexpected.
</blockquote></details>

For those following along, I opened up a PR with the benchmarks (https://github.com/cockroachdb/cockroach/pull/42647) and resolved the issue, it was due to Pebble using compression and therefore syncing less. The RFC has been updated with the latest numbers.
___
*[docs/RFCS/20191113_vectorized_external_storage.md, line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42546#-Lu0VsMN9TNniXPJHg6X:-LvQrQc3EZsNqR2c3zl6:b-midfxf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9266dfd43bedfbd5034ee945d81252109f5dfbb3/docs/RFCS/20191113_vectorized_external_storage.md#L163)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Based on this, it looks like using a larger file size is slightly more beneficial due to a reduced number of file descriptors and rolling over files less frequently (although this cost seems very small).
</blockquote></details>

After adding syncing, it seems like smaller files are more performant due to syncing less (the last 1MB of a file is not synced, decreasing the total number of syncs for the same amount of data stored in many small files vs a few big ones). Performance-wise, it seems like smaller files are the way to go. Open file descriptors are not really linked to the maximum file size unless we have multiple read positions (like in the case of reading from multiple partitions in an external merge sort) and choose to implement storing multiple partitions in a single file. Since a partition is 64MB by default (it's the work memory of operators like the sorter), we'd need to have pretty large files to see any improvement. I think we should just implement partitions as separate queues and ensure we only keep a maximum number of file descriptors open.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42546)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @danhhz, @jordanlewis, @petermattis, and @yuzefovich)

___
*[docs/RFCS/20191113_vectorized_external_storage.md, line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42546#-Lu0VsMN9TNniXPJHg6X:-LvfxfNi2j75_rbthnmv:b-ou9w0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/9266dfd43bedfbd5034ee945d81252109f5dfbb3/docs/RFCS/20191113_vectorized_external_storage.md#L163)):*
> After adding syncing, it seems like smaller files are more performant due to syncing less (the last 1MB of a file is not synced, decreasing the total number of syncs for the same amount of data stored in many small files vs a few big ones)

Is it intentional that you don't sync the last 1MB of file data? Yes, you'd have to do this outside of `NewSyncingFile`, or we'd need to change `syncingFile.Close`. Not syncing the last 1MB of file data could allow a large amount of dirty filesystem data to build up which can be problematic for other disk operations. On the other hand, if we delete the data quickly enough perhaps there isn't a problem.

To make sure your comparisons are apples-to-apples, it would be good to make sure you're syncing the same amount of data for small files and large files.

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42546)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz, @jordanlewis, @petermattis, and @yuzefovich)

___
*[docs/RFCS/20191113_vectorized_external_storage.md, line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42546#-Lu0VsMN9TNniXPJHg6X:-LvjC52b0hCj98quljpA:b-harf56) ([raw file](https://github.com/cockroachdb/cockroach/blob/9266dfd43bedfbd5034ee945d81252109f5dfbb3/docs/RFCS/20191113_vectorized_external_storage.md#L163)):*
> Is it intentional that you don't sync the last 1MB of file data?

This is an implementation detail of `syncingFile` to avoid flushing the 1MB closest to the write offset in case data is being overwritten. I assumed that the a `Sync` occurred on `Close`, but not sure why. This might be best achieved through an addition to `SyncingFileOptions` to enable/disable the distance to write offset check as well as ensuring a `Sync` on `Close`. After doing this it seems like a `32MB` file is the smallest size at which performance is unchanged, going larger doesn't change much. This seems like a good default choice:

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42546)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @danhhz, @jordanlewis, @petermattis, and @yuzefovich)

___
*[docs/RFCS/20191113_vectorized_external_storage.md, line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42546#-Lu0VsMN9TNniXPJHg6X:-LvkFCmC58YZSHVAEh9X:bgwfe9o) ([raw file](https://github.com/cockroachdb/cockroach/blob/9266dfd43bedfbd5034ee945d81252109f5dfbb3/docs/RFCS/20191113_vectorized_external_storage.md#L163)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

> Is it intentional that you don't sync the last 1MB of file data?

This is an implementation detail of `syncingFile` to avoid flushing the 1MB closest to the write offset in case data is being overwritten. I assumed that the a `Sync` occurred on `Close`, but not sure why. This might be best achieved through an addition to `SyncingFileOptions` to enable/disable the distance to write offset check as well as ensuring a `Sync` on `Close`. After doing this it seems like a `32MB` file is the smallest size at which performance is unchanged, going larger doesn't change much. This seems like a good default choice:

</blockquote></details>

I believe the `syncingFile` logic was made to match the logic for the similar structure in RocksDB. In Pebble, `syncingFile` is always coupled with a `Sync` before `Close`. I suppose we could change that so that the `Sync` is implicit upon `Close`.

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42546)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz, @jordanlewis, @petermattis, and @yuzefovich)

___
*[docs/RFCS/20191113_vectorized_external_storage.md, line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42546#-Lu0VsMN9TNniXPJHg6X:-LvkVgTf0PL85lW2m6q9:b-bcsqn6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9266dfd43bedfbd5034ee945d81252109f5dfbb3/docs/RFCS/20191113_vectorized_external_storage.md#L163)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I believe the `syncingFile` logic was made to match the logic for the similar structure in RocksDB. In Pebble, `syncingFile` is always coupled with a `Sync` before `Close`. I suppose we could change that so that the `Sync` is implicit upon `Close`. 
</blockquote></details>

I have a patch ready but I'm wondering if it should just be the caller's responsibility to `Sync` before `Close` as you say Pebble does. Also adding an option to ignore the proximity to the write offset seems kind of scary given this comment: `(2) for older version of OS, write can block while writing out [...] the page.`

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42546)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @danhhz, @jordanlewis, @petermattis, and @yuzefovich)

___
*[docs/RFCS/20191113_vectorized_external_storage.md, line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42546#-Lu0VsMN9TNniXPJHg6X:-LvkWwvMBdYXJhbZvgoy:b7fftfx) ([raw file](https://github.com/cockroachdb/cockroach/blob/9266dfd43bedfbd5034ee945d81252109f5dfbb3/docs/RFCS/20191113_vectorized_external_storage.md#L163)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I have a patch ready but I'm wondering if it should just be the caller's responsibility to `Sync` before `Close` as you say Pebble does. Also adding an option to ignore the proximity to the write offset seems kind of scary given this comment: `(2) for older version of OS, write can block while writing out [...] the page.`
</blockquote></details>

I think we can make the semantics of `syncingFile` such that it always `Syncs` on `Close`. I'm not sure why you'd need to add an option to ignore the proximity to the write offset. Where is that comment you quoted coming from?

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42546)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz, @jordanlewis, @petermattis, and @yuzefovich)

___
*[docs/RFCS/20191113_vectorized_external_storage.md, line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42546#-Lu0VsMN9TNniXPJHg6X:-LvoTBI_6i3-xC6pYT-J:bowxc81) ([raw file](https://github.com/cockroachdb/cockroach/blob/9266dfd43bedfbd5034ee945d81252109f5dfbb3/docs/RFCS/20191113_vectorized_external_storage.md#L163)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think we can make the semantics of `syncingFile` such that it always `Syncs` on `Close`. I'm not sure why you'd need to add an option to ignore the proximity to the write offset. Where is that comment you quoted coming from?
</blockquote></details>

OK, submitted a PR (https://github.com/cockroachdb/pebble/pull/424). The option was to reduce dirty data in the os buffer cache in an append-only use case. The comment is from https://github.com/cockroachdb/pebble/blob/382a403837cb2edfc5d60d4a4476e61c17ac435e/vfs/syncing_file.go#L114

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42546)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @danhhz, @jordanlewis, @petermattis, and @yuzefovich)

___
*[docs/RFCS/20191113_vectorized_external_storage.md, line 4 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42546#-LwFkSzr13Hwp-n9RZLB:-LwFkSzr13Hwp-n9RZLC:b-k7xscl) ([raw file](https://github.com/cockroachdb/cockroach/blob/c720a2ad44d3a6e6796e5207ce73886ab67f6f4b/docs/RFCS/20191113_vectorized_external_storage.md#L4)):*
> ```Markdown
> - Status: draft
> - Start Date: 2019-11-13
> - Authors: Alfonso Subiotto Marqués and Yahor Yuzefovich
> ```

[nit]: I'd definitely not give myself any credit here :)

**Review by asubiotto — COMMENTED** [review]
Implemented snappy compression in the file-based queue which results in a 50% improvement over pebble in the best case. This RFC should be ready for a final look.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42546#-:-LwIDKcSDEN-a41eD3G9:b-w0vlld)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz, @jordanlewis, @petermattis, and @yuzefovich)

___
*[docs/RFCS/20191113_vectorized_external_storage.md, line 4 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42546#-LwFkSzr13Hwp-n9RZLB:-LwIDa2D1UKAGZoZObtj:b-7srelt) ([raw file](https://github.com/cockroachdb/cockroach/blob/c720a2ad44d3a6e6796e5207ce73886ab67f6f4b/docs/RFCS/20191113_vectorized_external_storage.md#L4)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: I'd definitely not give myself any credit here :)
</blockquote></details>

Even though the RFC focuses on the file-based queue, you're a key part of implementing external storage! I think it's useful to keep you as an author for future readers.

**Comment by asubiotto** [comment]
Friendly ping

**Review by yuzefovich — COMMENTED** [review]
LGTM, but my opinion here isn't worth much.

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42546#-:-LwZ5uBQ6gpOioBYgzic:ba2fbcm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @danhhz, @jordanlewis, @petermattis, and @yuzefovich)

___
*[docs/RFCS/20191113_vectorized_external_storage.md, line 118 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42546#-Lu0X06kA7eB177fx7KR:-LwZ431w6EJ8wgo2PjHj:bh08q42) ([raw file](https://github.com/cockroachdb/cockroach/blob/9266dfd43bedfbd5034ee945d81252109f5dfbb3/docs/RFCS/20191113_vectorized_external_storage.md#L118)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

There is currently no way to connect a flow `ID` back to a txn `ID`. In terms of understanding where the space is going on disk, we'll be using the same temporary storage monitors used by external storage in the row execution engine to limit disk usage. The monitors will also be used to displayed disk used per operator through `EXPLAIN ANALYZE`. There is currently no extra observability work planned but I think we would probably reuse information supplied by monitors rather than relying on this naming scheme. Will update the RFC with this.
</blockquote></details>

I think it's worth mentioning Alfonso's last comment in the RFC itself.
___
*[docs/RFCS/20191113_vectorized_external_storage.md, line 13 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42546#-LwZ-vK030uk_Z-KX8YV:-LwZ-vK15qCEQOrtc7Yi:bb1jpf9) ([raw file](https://github.com/cockroachdb/cockroach/blob/bec0c3060c3e5818551fc5c1dd3612a64ddfb372/docs/RFCS/20191113_vectorized_external_storage.md#L13)):*
> ```Markdown
> to disk when these are too large to fit in main memory by adding an
> on-disk queue abstraction. Without this ability, queries that use these
> vectorized operators will encounter an out of memory error and not be
> ```

[nit]: `s/and not/and will not/g`.

**Review by jordanlewis — APPROVED** [review]
LGTM! Nice RFC.

**Review by asubiotto — COMMENTED** [review]
TFTRs! Also thanks for the guidance @petermattis.

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42546#-:-LwcRBgL3KOFfybRVTcC:bmip83y)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz, @petermattis, and @yuzefovich)

___
*[docs/RFCS/20191113_vectorized_external_storage.md, line 118 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42546#-Lu0X06kA7eB177fx7KR:-LwcRA9x3d6Vl1mSjLvO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9266dfd43bedfbd5034ee945d81252109f5dfbb3/docs/RFCS/20191113_vectorized_external_storage.md#L118)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think it's worth mentioning Alfonso's last comment in the RFC itself.
</blockquote></details>

Done.
___
*[docs/RFCS/20191113_vectorized_external_storage.md, line 13 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/42546#-LwZ-vK030uk_Z-KX8YV:-LwcPx0QCfhhAHRbIy5y:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bec0c3060c3e5818551fc5c1dd3612a64ddfb372/docs/RFCS/20191113_vectorized_external_storage.md#L13)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: `s/and not/and will not/g`.
</blockquote></details>

Done.

**Pull request merged**
