### PR TITLE
colexec: fix closing of parallel unordered sync inputs

### LINKED ISSUE #51470: colflow: flow cleanup can occur before all closers are actually closed
While working on #51430, I ran into assertion failures because the vectorized flow was being cleaned up before all expected closers have been closed (see https://github.com/cockroachdb/cockroach/pull/51430#issuecomment-658393932). In one of the failures @asubiotto hit the failure with the following logs:
```
I200715 16:11:01.840318 3038 sql/colflow/vectorized_flow.go:1004  [n1,client=127.0.0.1:58503,hostssl,user=root] *colexec.externalSorter closed, now numClosed=1
I200715 16:11:01.840366 3038 sql/colflow/vectorized_flow.go:1004  [n1,client=127.0.0.1:58503,hostssl,user=root] *colexec.externalSorter closed, now numClosed=2
E200715 16:11:01.842663 2670 sql/conn_executor.go:782  [n1,client=127.0.0.1:58503,hostssl,user=root] a SQL panic has occurred while executing the following statement:
SELECT o.x, t.y FROM onecolumn AS o INNER JOIN twocolumn AS t ON ((o.x = t.x) AND (t.y = 53))
I200715 16:11:01.843227 3038 sql/colflow/vectorized_flow.go:1004  [n1,client=127.0.0.1:58503,hostssl,user=root] *colexec.externalHashJoiner closed, now numClosed=3
E200715 16:11:01.843264 2670 util/log/log.go:50  [n1,client=127.0.0.1:58503,hostssl,user=root] a panic has occurred!
```
which look like the final closing occurred after the check.

I think the issue here is that we're not blocking on the corresponding goroutines to be finished in the parallel unordered synchronizer before we clean up things. I'll make the corresponding change.

### PR DESCRIPTION
**Pull request by yuzefovich**
The responsibility of closing all `Closer`s within the synchronizer
input's tree lies on the goroutine that's handling that input.
Previously, we were mistakenly calling `Close` after we have notified
the wait groups that the handler-goroutine is done. This can result in
races between vectorized flow cleanup and cleaning up those closers.
This is now fixed.

Fixes: #51470.

Release note: None

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
LGTM

**Review by jordanlewis — APPROVED** [review]

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by yuzefovich** [comment]
Seems like unrelated flake.

bors r+ p=999

**Comment by yuzefovich** [comment]
Haha, yet another flake.

bors r+

**Comment by yuzefovich** [comment]
Jeez, now linter failed.

bors r+

**Comment by yuzefovich** [comment]
It's going to fail with version-upgrade flake, so canceling it and lowering the priority.

bors r-

**Comment by jordanlewis** [comment]
Rebased on top of master, which hopefully now contains a fix for the stats test failures.

bors r+

**Pull request merged**
