### PR TITLE
Fix new version message. Fixes #6706

### LINKED ISSUE #6706: server: bad messages about new beta version
I'm starting a version of the server from a few days ago, and I get badly formatted messages in the log about a new beta version. And I get two of them!

```
I160516 13:50:21.082105 server/updates.go:208  A new version is available: %s
	%sbeta-20160505https://www.cockroachlabs.com/docs/beta-20160505.html
I160516 13:50:21.082123 server/updates.go:208  A new version is available: %s
	%sbeta-20160512https://www.cockroachlabs.com/docs/beta-20160512.html
```

I'm also pretty impressed that these messages exist.

### PR DESCRIPTION
**Pull request by mberhault**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6709)

### CODE REVIEW

**Comment by andreimatei** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[server/updates.go, line 208 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6709#-KHuju4NmySazocrc-e8:-KHuju4NmySazocrc-e9:-682980943) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c34aab5dcd1a366d145cd33f2be3891a62046cc/server/updates.go#L208)):*
> ```Go
> 
> 	for _, v := range r.Details {
> 		log.Infof("A new version is available: %s, details: %s", v.Version, v.Details)
> ```

do we need to show all these messages?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6709)*

**Comment by mberhault** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[server/updates.go, line 208 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6709#-KHuju4NmySazocrc-e8:-KHukTnY_Ky8_LjOZWVn:1554651325) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c34aab5dcd1a366d145cd33f2be3891a62046cc/server/updates.go#L208)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> do we need to show all these messages?</details>
the server controls what is sent back. it's only supposed to send newer versions, and if it sends only one, that's fine too. I think it's safe to leave as is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6709)*

**Comment by dt** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[server/updates.go, line 208 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6709#-KHuju4NmySazocrc-e8:-KHukYkERvI9LAdXC6ME:1375215164) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c34aab5dcd1a366d145cd33f2be3891a62046cc/server/updates.go#L208)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary>
> do we need to show all these messages?</details>
It should only  do it once a day per cluster in production.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6709)*

**Comment by dt** [comment]
:lgtm:

<details><summary><i>Previously, mberhault (marc) wrote…</i></summary>
> #### Fix new version message\. Fixes \#6706
> 
> 
> 
> 
> </details>


---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6709#-:-KHul5HhrSFy6QgF9uNh:1417088721)*

**Comment by andreimatei** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[server/updates.go, line 208 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6709#-KHuju4NmySazocrc-e8:-KHukyQjn3mHfScUB8Rp:75788235) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c34aab5dcd1a366d145cd33f2be3891a62046cc/server/updates.go#L208)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary>
> the server controls what is sent back. it's only supposed to send newer versions, and if it sends only one, that's fine too. I think it's safe to leave as is.</details>
well then it should indeed only send one, no? Do you know whom to bug? :) @maxlang ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6709)*

**Comment by andreimatei** [comment]
LGTM

<details><summary><i>Previously, mberhault (marc) wrote…</i></summary>
> #### Fix new version message\. Fixes \#6706
> 
> 
> 
> 
> </details>


---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6709#-:-KHul8WYVvWxdg_CfE3g:676834233)*

**Comment by tamird** [comment]
`vet` does take a `-printfuncs` argument

**Comment by bdarnell** [comment]
If the server only returns one new version then you'll only see the the latest release notes, and may miss important warnings about backwards-compatibility or which versions require stop-the-world upgrades. I think that at our current stage of development it's better to show all the intermediate versions.

**Comment by mberhault** [comment]
@tamird: right. apparently I can't read.

I've added `Info:0` to the list of printfuncs for `go tool vet` and fixed the calls that triggered it.

**Comment by tamird** [comment]
Nice. LGTM

**Comment by mberhault** [comment]
Sorry, one more: `Warning:0`. Error and Fatal are already in the hard-coded list.

**Comment by tamird** [comment]
You might want to add Infof:1 and Warningf:1 for the type checking bits

**Comment by mberhault** [comment]
I was going to, but have a too many things failing.
fyi: it's still `Infof:0,Warningf:0`, the argument is the position of the first printing argument (eg: use `:1` for something like `Fprintf(stdout, "format", <optional args>)`)

**Comment by tamird** [comment]
Ah, neat.

**Comment by mberhault** [comment]
ok, done afterall. it was really the name reuse that was spamming failing this check. I'm not crazy about `VInfof` either, but at least it's different.

**Comment by tamird** [comment]
LGTM

**Pull request merged**
