### PR TITLE
storage/engine: fix sstIterator.Seek

### PR DESCRIPTION
**Pull request by dt**
The SSTs we iterate are assumed to be created by Rocks and thus contain
rocksdb's "internal" keys. Indeed, the sstIterator already reflects this
assumption in `Next` where it checks and removes the internal key suffix
before returning the user-key prefix.

However, in Seek and thus the configured Compare, we previously were
mixing user and internal keys.

Previously sstIterator.Seek was passing an encoded MVCC key -- i.e. a
user key -- to leveldb's `Find` method. However as mentioned above, the
low-level iterator is dealing in terms of internal keys. This subtle
distinction was easy to miss since user keys are a prefix of internal
keys, but is nontheless incorrect. Consider an SST to which the single
key 'A' is added via RocksDB. For the sake of example, say that RocksDB
appends `1` to make the internal key in the SST `A1`. If we to Seek to
`A0`, since the only key is `A`, we should seek past it and find nothing
but if our Seek method is operating on internal keys but is passing a
user key, we may mistakenly compare `A1` to `A0` and stop at A1 since it
appears greater than A0.

Padding the key passed to seek with a dummy internal key suffix should
ensure that it compares correctly to the internal keys on which Find is
operating.

In looking at this, I also realized that we made the same mistake in the
Comparer implementation. We directly copied the logic we use in the one
we pass to RocksDB, but again, in the levelDB case, it is operating on
the keys actually in the SST, which in this case are the interrnal keys
that RocksDB put there. Since the Comparer is only used in the SST
iterator and it is only used to iterate rocksdb's SSTs, it should assume
it is always operating on internal keys, and remove their internal
suffix before applying the user-key comparison logic.

This bugs underline the fact that we're using a lower-level tool -- the
LevelDB reader -- vs a higher-level tool -- the RocksDB writer -- and
making sure we correctly account for the differences is tricky. Using
LevelDB was a win as it let us avoid CGO for in-memory iteration, but
using something like Pebble for both reading and writing could make this
code more coherent.

Release note: none.

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36810)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz, @dt, and @petermattis)

___
*[pkg/storage/engine/batch.go, line 306 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36810#-LcHfnaD-SW8r_kRVkm9:-LcHfnaEAISCcFfy_2ii:b-6k6jaj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8d0b648b5c721ebb895e03bb9b97e88f168d2d3/pkg/storage/engine/batch.go#L306)):*
> ```Go
> // representation and adds padding to the end such that it compares correctly
> // with rocksdb "internal" keys which have an 8b suffix.
> func EncodeInternalSeekKey(key MVCCKey) []byte {
> ```

I'd prefer to keep this method out of `storage/engine`. Is is an implementation detail of RocksDB which shouldn't be leaking here. Let's make this a private method next to the `sstIterator` code. 
___
*[pkg/storage/engine/sst_iterator.go, line 224 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36810#-LcHgH9O8XY3qaPVmhJ3:-LcHgH9O8XY3qaPVmhJ4:b-xcyi0h) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8d0b648b5c721ebb895e03bb9b97e88f168d2d3/pkg/storage/engine/sst_iterator.go#L224)):*
> ```Go
> 	}
> 	a = a[:len(a)-8]
> 	b = b[:len(b)-8]
> ```

Are there ever duplicate "user" keys in these sstables? I ask because this comparison routine won't handle them correctly as technically you're also supposed to use the trailing bytes for comparison.

**Comment by dt** [comment]
To be more explicit, the manifestation of this bug is that `Seek` may land on an earlier key than it was supposed to. I started auditing where we use `Seek` to try to figure out impact.

- Seek is used to in `evalAddSSTable` to 1) jump to the beginning of the SST (according to the header) and check the lower-bound, then iterate to compute stats, then again to jump to the end and check the upper bound. Since we're always doing the whole file, there isn't an earlier key to stop on so the lower-bound check and stats iteration should be fine. The upper bound check was actually where we caught this -- we'd added what should have been a spurious extra check of UnsafeKey to the Seek key and removing it is how I found this. However, with the check, that call was safe too. Thus **I don't think the bug impacts `evalAddSSTable`**.

- Seek is used in `evalImport` to jump to the beginning of the assigned span in one or more backup SSTs and then begin iterating to build an SST to ingest. With range merges (and maybe even without), it seems likely that the spans in different layers of incremental backup would have different boundaries, so we are likely seeking mid-SST often. If we land on an earlier key, I think it'd *probably* be harmless: if the key belongs in the restore anyway (just in a different import span), I think it'll we'd emit it in multiple SSTs and be harmless. If it it didn't belong in the restore at all because it was too new, the time bound will discard it.  If it didn't belong in the restore because belongs to a different table I'm pretty sure it would be in a different SST (and if it wasn't the rewriter would reject it) ** I don't think it is likely to impact RESTORE**

- Seek is used in creating the split right and left sides of a an original SST when it tries to add over a split. This can happen repeatedly and we, as of recent changes, refuse the single iterator over the original SST and `Seek` to the beginning of the subspan we've learned maps to a given target range.  In this case if `Seek` landed on an earlier key... I think it could be bad. We return the first key actually added to the SST as is bounds, and if that key belongs to the prior span, we'd still be spanning a split. **I think this could mean we get stuck re-adding the same SST?**

I'm going to do another pass over that last one to try to see if that actually looks plausible. I maybe it isn't because Seek doesn't land on just any earlier key, but only one where there is an earlier user key that is a strict prefix of the seek key.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36810)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz, @dt, and @petermattis)

___
*[pkg/storage/engine/sst_iterator.go, line 224 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36810#-LcHgH9O8XY3qaPVmhJ3:-LcHmz5K9sD_K6Dmr7yL:b-p90iqh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8d0b648b5c721ebb895e03bb9b97e88f168d2d3/pkg/storage/engine/sst_iterator.go#L224)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Are there ever duplicate "user" keys in these sstables? I ask because this comparison routine won't handle them correctly as technically you're also supposed to use the trailing bytes for comparison. 
</blockquote></details>

I don't think there are: I thought the builder rejected duplicate keys with `Invalid argument: Keys must be added in order`?

**Review by petermattis — COMMENTED** [review]
> Seek is used to in evalAddSSTable to 1) jump to the beginning of the SST (according to the header) and check the lower-bound, then iterate to compute stats, then again to jump to the end and check the upper bound. Since we're always doing the whole file, there isn't an earlier key to stop on so the lower-bound check and stats iteration should be fine. The upper bound check was actually where we caught this -- we'd added what should have been a spurious extra check of UnsafeKey to the Seek key and removing it is how I found this. However, with the check, that call was safe too. Thus I don't think the bug impacts evalAddSSTable.

How were the keys being used for stats computation? If you weren't trimming off the sequence number I would think the stats would be systematically incorrect.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36810#-:-LcHyIXSEKtyRrLz9yYL:b9yxcc3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz and @dt)

___
*[pkg/storage/engine/sst_iterator.go, line 224 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36810#-LcHgH9O8XY3qaPVmhJ3:-LcHxrBxE-mhsIhmRcql:b-jtfso8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8d0b648b5c721ebb895e03bb9b97e88f168d2d3/pkg/storage/engine/sst_iterator.go#L224)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I don't think there are: I thought the builder rejected duplicate keys with `Invalid argument: Keys must be added in order`?
</blockquote></details>

Duplicate user keys are allowed in an sstable, but they need to have different sequence numbers or different types. I'm not sure if the builder code allows that or not.

**Comment by dt** [comment]
On a closer read, I think the splitting sstable adder is fine too the since the split keys it seeks to have a zero timestamp component, while the keys in the SST have a non-zero timestamp on the ends of them, so it seems very unlikely the earlier user key could be a strict prefix of the seek key.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36810)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz and @petermattis)

___
*[pkg/storage/engine/batch.go, line 306 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36810#-LcHfnaD-SW8r_kRVkm9:-LcHzz8S8pBssaWLRgIz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8d0b648b5c721ebb895e03bb9b97e88f168d2d3/pkg/storage/engine/batch.go#L306)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'd prefer to keep this method out of `storage/engine`. Is is an implementation detail of RocksDB which shouldn't be leaking here. Let's make this a private method next to the `sstIterator` code. 
</blockquote></details>

Done.
___
*[pkg/storage/engine/sst_iterator.go, line 224 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/36810#-LcHgH9O8XY3qaPVmhJ3:-LcHzzps0zHFwCo9lF2M:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8d0b648b5c721ebb895e03bb9b97e88f168d2d3/pkg/storage/engine/sst_iterator.go#L224)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Duplicate user keys are allowed in an sstable, but they need to have different sequence numbers or different types. I'm not sure if the builder code allows that or not. 
</blockquote></details>

Done.

**Review by petermattis — APPROVED** [review]
:lgtm: 

I see that `sstIterator.Next` already strips off the sequence number. So ignore my question about stats computation.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36810#-:-LcI-mIc2x5waMJDJozO:b-owd8vz)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz and @petermattis)

**Comment by dt** [comment]
One more small change in the Comparer since it can't assume all keys are >8b if some keys are nil.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36810)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @danhhz, @dt, and @petermattis)

___
*[pkg/storage/engine/sst_iterator.go, line 231 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36810#-LcSpDq7AaDoeyKqiiwQ:-LcSpDq8-kM3p6E56Gxp:bakuzhs) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5027d7047f5d2cc254addec998aec5b5196bf4b/pkg/storage/engine/sst_iterator.go#L231)):*
> ```Go
> 	if len(a) < 8 || len(b) < 8 {
> 		// Special case: either key is empty, so bytes.Compare should work.
> 		if len(a) == 0 || len(b) == 0 {
> ```

In what context do empty / nil keys arise?

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36810)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @danhhz and @petermattis)

___
*[pkg/storage/engine/sst_iterator.go, line 231 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36810#-LcSpDq7AaDoeyKqiiwQ:-LcX16B79KjpCABjfVB_:b-1imnkx) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5027d7047f5d2cc254addec998aec5b5196bf4b/pkg/storage/engine/sst_iterator.go#L231)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

In what context do empty / nil keys arise?
</blockquote></details>

I saw it while doing iteration. It looks like leveldb does it internally: in `Next` it looks like it calls `if !i.nextBlock(nil, nil) {`to load the next block, passing `nil` to start it at the first key.

**Review by petermattis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36810)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @danhhz and @petermattis)

___
*[pkg/storage/engine/sst_iterator.go, line 231 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/36810#-LcSpDq7AaDoeyKqiiwQ:-LcXHyKDAktkU7dn8B0k:bxnofki) ([raw file](https://github.com/cockroachdb/cockroach/blob/a5027d7047f5d2cc254addec998aec5b5196bf4b/pkg/storage/engine/sst_iterator.go#L231)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I saw it while doing iteration. It looks like leveldb does it internally: in `Next` it looks like it calls `if !i.nextBlock(nil, nil) {`to load the next block, passing `nil` to start it at the first key.
</blockquote></details>

Ok. Thanks.

**Comment by dt** [comment]
This seems like it might be a good idea to backport at some point, just in case I'm wrong about an incorrect `Seek` position not actually surfacing as a user-visible issue in the current callers, but given that I don't currently see such a case, I'm thinking I'd prefer to to hold off on that until it has some time to bake on master.

cc @danhhz @lucy-zhang

**Comment by dt** [comment]
looks like bors dropped this one too.

bors r+

**Pull request merged**
