### PR TITLE
sql: introduce PREPARE AS OPT PLAN

### PR DESCRIPTION
**Pull request by RaduBerinde**
This commit introduces a way to run a "canned" optimizer plan (using
exprgen). A predefined plan can be prepared as in the following
example:

```
SET allow_prepare_as_opt_plan = ON;
PREPARE a AS OPT PLAN '
(Root
  (Scan [ (Table "t") (Cols "k,str") ])
  (Presentation "k,str")
  (NoOrdering)
)';
EXECUTE a;
```

We don't support placeholders inside the canned plan. The main hurdle
is that the parser keeps track of the number of placeholders, and it
doesn't have visibility inside the plan.

This is a testing facility and should not be documented. It is
disabled by default, and must be enabled using the (hidden) session
setting `allow_prepare_as_opt_plan`.

The commit also contains some fixes and cleanup to exprgen.

Release note: None

Informs #30273.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
CC @knz for the grammar change.

**Review by justinj — COMMENTED** [review]
Love it! :lgtm:

> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34910#-:-LYgni_j9hVz6NTON8Mj:bpnmou7)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @rytaft)

**Review by knz — APPROVED** [review]
Maybe explain in the commit message why you stopped short of supporting placeholders (what makes it difficult) and outline what would be needed to go that extra mile.

:lgtm: otherwise.

> Reviewed 12 of 14 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34910#-:-LYgwWbE1B2GhIgTOpYN:b-9lup0m)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball, @RaduBerinde, and @rytaft)

___
*[pkg/sql/plan_opt.go, line 266 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34910#-LYgvjOw-bm_yQHMhpfr:-LYgvjOx07Jdjil2pvJA:b-dj90o3) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b0ee1385e80368c1e739711b5b61fd6584f1630/pkg/sql/plan_opt.go#L266)):*
> ```Go
> 	if _, isCanned := opc.p.stmt.AST.(*tree.CannedOptPlan); isCanned {
> 		if f.Memo().HasPlaceholders() {
> 			return nil, false, errors.Errorf("placeholders are not supported with PREPARE AS OPT PLAN")
> ```

Maybe add a comment to explain what makes placeholders difficult to support? 
The PREPARE/EXECUTE syntax would make it syntactically easy to use.

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/plan_opt.go, line 266 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/34910#-LYgvjOw-bm_yQHMhpfr:-LYh1tc17tg510CsQ4WQ:b-kq6ti0) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b0ee1385e80368c1e739711b5b61fd6584f1630/pkg/sql/plan_opt.go#L266)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Maybe add a comment to explain what makes placeholders difficult to support? 
The PREPARE/EXECUTE syntax would make it syntactically easy to use.
</blockquote></details>

I'll add a comment. The main problems are:
 - `PlaceholderExpr` (for some reason) stores a `TypedExpr` (a `tree.Placeholder`) instead of just storing the placeholder index and type. It's not possible to build a `TypedExpr` with the exprgen syntax. This should be fixable.

 - the parser counts how many placeholders it sees and that info is used by the sql layer. If we put placeholders in the plan inside exprgen, that would be invisible to the parser.

**Comment by RaduBerinde** [comment]
Added a hidden session variable that enables this functionality.

**Review by rytaft — APPROVED** [review]
:lgtm_strong: 

> Reviewed 10 of 14 files at r1, 6 of 6 files at r2, 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34910#-:-LYmDK7-0dDL-MnPRRCU:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @andy-kimball, @knz, and @RaduBerinde)

___
*[pkg/sql/opt/optgen/exprgen/custom_funcs.go, line 64 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34910#-LYmAriZA30afi_DLmhT:-LYmAriZA30afi_DLmhU:b1dvjo1) ([raw file](https://github.com/cockroachdb/cockroach/blob/defddadf5bd6ec0c040c6b56934bfacbbda5a385/pkg/sql/opt/optgen/exprgen/custom_funcs.go#L64)):*
> ```Go
> }
> 
> // ColList creates a ColList from a comma-separated list of columns, looking up
> ```

[nit] maybe specify that it's a list of column names
___
*[pkg/sql/opt/optgen/exprgen/custom_funcs.go, line 75 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34910#-LYmB0vgA-3x2eLKwBmv:-LYmB0vgA-3x2eLKwBmw:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/defddadf5bd6ec0c040c6b56934bfacbbda5a385/pkg/sql/opt/optgen/exprgen/custom_funcs.go#L75)):*
> ```Go
> }
> 
> // ColSet creates a ColSet from a comma-separated list of columns, looking up
> ```

ditto

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34910)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @andy-kimball, @knz, and @rytaft)

___
*[pkg/sql/opt/optgen/exprgen/custom_funcs.go, line 64 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34910#-LYmAriZA30afi_DLmhT:-LYmQYKo7uEo4tdmm8MX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/defddadf5bd6ec0c040c6b56934bfacbbda5a385/pkg/sql/opt/optgen/exprgen/custom_funcs.go#L64)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] maybe specify that it's a list of column names
</blockquote></details>

Done.
___
*[pkg/sql/opt/optgen/exprgen/custom_funcs.go, line 75 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/34910#-LYmB0vgA-3x2eLKwBmv:-LYmQYqO3hjeILW8ANO4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/defddadf5bd6ec0c040c6b56934bfacbbda5a385/pkg/sql/opt/optgen/exprgen/custom_funcs.go#L75)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/34910)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @andy-kimball and @knz)

**Pull request merged**
