### PR TITLE
multitenant: implement a fallback rate

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### tenantcostclient: maintain a "buffer" of RUs

This change adjusts the tenant cost controller logic to try to
maintain a "buffer" of 5000 RUs. This is useful to prevent waiting for
more RUs if an otherwise lightly loaded pod suddenly gets a spike of
traffic.

Release note: None

#### multitenant: implement a "backup" rate

This change implements a "backup" (fallback) throttling rate that a
SQL pod can use if it stops being able to complete token bucket
requests.

The goal is keep tenants without burst RUs throttled and tenants with
lots of RUs unthrottled (or throttled at a high rate). To achieve
this, we calculate a rate at which the tenant would burn through all
their available RUs within 1 hour. The premise here is that if we have
some kind of infrastructure problem, 1 hour is a reasonable time frame
to address it. Beyond 1 hour, the tenant will continue at the same
rate, consuming more RUs than they had available.

Informs #68479.

Release note: None

Release justification: Necessary fix for the distributed rate limiting
functionality, which is vital for the upcoming Serverless MVP release.
It allows CRDB to throttle clusters that have run out of free or paid
request units (which measure CPU and I/O usage). This functionality is
only enabled in multi-tenant scenarios and should have no impact on
our dedicated customers.

### CODE REVIEW

**Review by andy-kimball — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70163#-:-MjWcAhV4jihZUmkjj64:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Review by ajwerner — COMMENTED** [review]
If I had a nit it's that I don't like the word `backup` as much as I like `fallback`. How come you chose backup, which very much is a term in cockroach, and, probably something users can initiate?

> Reviewed 1 of 5 files at r1, 9 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70163#-:-MjX-6S5AJTgDENzWJN0:bnlymak)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go, line 366 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70163#-MjWze8N3MlXQlaSOWZz:-MjWze8OBQescO3lBlvF:b9v93ai) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a829cdaec7244e2b99da049e77e5f01b1b2d70c/pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go#L366)):*
> ```Go
> 	ctx context.Context, resp *roachpb.TokenBucketResponse,
> ) {
> 	if log.V(1) {
> ```

drive-by: this should be `log.ExpensiveLogEnabled(ctx, 1)`

**Comment by RaduBerinde** [comment]
Yeah I agree. I thought of "fallback" after I wrote most of the code. I will rename.

**Comment by RaduBerinde** [comment]
I fell back to the backup word `fallback`.

**Review by ajwerner — APPROVED** [review]
:lgtm_strong: 

> Reviewed 1 of 5 files at r1, 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70163#-:-Mj_9mzT2Omk50gSK2VU:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

**Pull request merged**
