### PR TITLE
server,storage: breakdown byte counts in SpanStats by backing storage

### PR DESCRIPTION
**Pull request by dt**
Release note: none.
Epic: none.

### CODE REVIEW

**Comment by dt** [comment]
This won't compile until I get the corresponding pebble change in and include a dep bump to pick it up, but just throwing this up for an initial look.

**Review by RaduBerinde — COMMENTED** [review]
Do we really only care about the file counts? I'd think we care more about how many bytes are in external files vs local files

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107120#-:-N_fpsWkDSIcOZSgFdtS:b2q2h6c)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @ericharmeling, @itsbilal, @sumeerbhola, and @zachlite)

___
*[`pkg/roachpb/span_stats.proto` line 50 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107120#-N_fpd9q4w71J8AOdBm0:-N_fpd9q4w71J8AOdBm1:b-eooaw4) ([raw file](https://github.com/cockroachdb/cockroach/blob/68f993dfa321c1b5723087200e7653ebb2fd3bb4/pkg/roachpb/span_stats.proto#L50)):*
> ```proto
> 
>   int64 file_count = 4;
>   int64 remote_file_count = 5;
> ```

These need documentation.
___
*[`pkg/storage/engine.go` line 993 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107120#-N_fpL-pDID_3Tcea-9f:-N_fpL-pDID_3Tcea-9g:boyisi2) ([raw file](https://github.com/cockroachdb/cockroach/blob/68f993dfa321c1b5723087200e7653ebb2fd3bb4/pkg/storage/engine.go#L993)):*
> ```Go
> 	// ApproximateDiskBytesAndFiles returns an approximation of the on-disk size
> 	// and file counts for the given key span.
> 	ApproximateDiskBytes(from, to roachpb.Key) (uint64, int64, int64, int64, error)
> ```

ApproximateDiskBytesAndFiles. These returns should be named and be documented (even better would be a separate struct)

**Comment by dt** [comment]
> Do we really only care about the file counts? I'd think we care more about how many bytes are in external files vs local files

Yeah, came to this conclusion a couple hours ago in https://github.com/cockroachdb/pebble/pull/2748, just hadn't pushed the rebased version of the crdb side yet.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107120)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @itsbilal, @RaduBerinde, @sumeerbhola, and @zachlite)

___
*[`pkg/roachpb/span_stats.proto` line 50 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107120#-N_fpd9q4w71J8AOdBm0:-N_gGFqF9DSSxyHR3cG-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/68f993dfa321c1b5723087200e7653ebb2fd3bb4/pkg/roachpb/span_stats.proto#L50)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

These need documentation.
</blockquote></details>

Done.
___
*[`pkg/storage/engine.go` line 993 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107120#-N_fpL-pDID_3Tcea-9f:-N_gG2mO9kzeKDTqXNuO:b-nrjqw7) ([raw file](https://github.com/cockroachdb/cockroach/blob/68f993dfa321c1b5723087200e7653ebb2fd3bb4/pkg/storage/engine.go#L993)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

ApproximateDiskBytesAndFiles. These returns should be named and be documented (even better would be a separate struct)
</blockquote></details>

I started down the struct path, particularly when I was doing file count and total size, but since switch to just 3 sizes it felt like it was back to fitting more naturally into just the three named returns, but I did extend the comment to mention them.

**Comment by dt** [comment]
converting to draft since this is using a branch on a fork for the pebble changes until they land upstream so it won't be ready to merge until that lands.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107120)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @itsbilal, @sumeerbhola, and @zachlite)

___
*[`pkg/roachpb/span_stats.proto` line 50 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/107120#-N_fpd9q4w71J8AOdBm0:-N_j-IDC5qd0eyk1cgLW:b-wdj8zi) ([raw file](https://github.com/cockroachdb/cockroach/blob/68f993dfa321c1b5723087200e7653ebb2fd3bb4/pkg/roachpb/span_stats.proto#L50)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nice, thanks!

**Comment by dt** [comment]
Rebased on the pebble bump, so this is RFAL

**Review by RaduBerinde — APPROVED** [review]

**Comment by dt** [comment]
TFTR!

bors r+

**Pull request merged**
