### PR TITLE
tenantcapabilities: introduce a decoder for tenant capabilities

### PR DESCRIPTION
**Pull request by arulajmani**
This patch introduces a decoder, which takes raw KVs from the
system.tenants table and decodes them into
(TenantID, TenantCapability) pairs.

This is currently unusued. In a future commit, we'll establish a
rangefeed over the `system.tenants` table to maintain a cached view
of the global capabilities state. This decoder will be used to parse the
rangefeed output. Looking towards such a watcher component, the decoder
is placed in the `tenantcapabilitieswatcher` package.

References https://github.com/cockroachdb/cockroach/issues/94643

Epic: [CRDB-18503](https://cockroachlabs.atlassian.net/browse/CRDB-18503)

Release note: None

### CODE REVIEW

**Review by knz — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94722#-:-NL1CwG2AplJ7tesGs2B:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ecwall)

**Comment by arulajmani** [comment]
Rebased on top of master now that the PR with the first commit landed. TFTR! 

bors r+

**Comment by arulajmani** [comment]
flaked. 

bors r=knz

**Comment by arulajmani** [comment]
bors retry

**Pull request merged**
