### PR TITLE
kvserver: add chart tracking QPS for follower reads

### PR DESCRIPTION
**Pull request by aayushshah15**
This commit adds an Admin UI chart that tracks the count of total
successful read-only batch requests along with the count of requests
served via follower reads.

This provides some much-needed observability into the efficacy of a
cluster topology as it pertains to leveraging non-leaseholder replicas
to serve historical `AS OF SYSTEM TIME` queries. This also paves the way
for potentially demonstrating use cases / cluster configurations for the
upcoming non-voting replicas.

For instance, running the `follower-reads/nodes=3` roachtest with this
change:
Screenshot from 2020-10-09 02-08-06
Screenshot from 2020-10-09 02-07-18

Release note (admin ui change): Added a chart to track follower read
requests successfully served per second by a store.

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
What's the thinking on introducing this new long-term average versus the existing `follower_reads.success_count` ?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51917#-:-MDFycqNEVJsjlV2zk6t:b6uayq3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

**Comment by aayushshah15** [comment]
Mostly just consistency with `AverageQueriesPerSecond` and `AverageWritesPerSecond`. The current `FollowerReadCount` metric is not directly comparable to these two.

**Comment by aayushshah15** [comment]
I'm in favor of removing the existing counter and just keeping the average, curious to know what you think.

**Comment by andreimatei** [comment]
What are `AverageQueriesPerSecond` and `AverageWritesPerSecond` used for? Do we show them in any dashboards? Are they used for anything? The metrics' names are `rebalancing.{queries,writes}persecond` so presumably they were introduced to be used by the rebalancer, but I don't seem to see them used at all. 
In any case, these seem like weird metrics to me. It's not easy to tell what they even measure exactly. Counters are a much more common metric type; you can use them to compute rates which is what our dashboards usually show. You can also in priciple compute moving averages easily although I don't know if our dashboards let us do it.

**Comment by aayushshah15** [comment]
They are used for rebalancing and one of them is exposed to the dashboard: the `Average Queries per Store` metric. 

Another thing I didn't realize before was that, when making load based splitting decisions (especially after learner replicas are long-lived), we might want to take this newly added metric into account as well. A counter is probably less useful in this case as well.

**Comment by aayushshah15** [comment]
Discussed offline: We've decided that while we should keep the newly added metric around for future use in rebalancing heuristics, we should not expose it alongside the `Average Queries per Store` metrics as the resulting value is hard to interpret (and a bit of a misnomer as its not a simple mean). We've decided to instead start tracking a new metric to the effect of `LeaseholderReadsCount` (alongside the existing `FollowerReadsCount`) and introduce a new chart that graphs reads served by the leaseholder alongside the ones served by followers.

I'll ping here when this is done.

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51917)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @nvanbenschoten)

___
*[pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/distributed.tsx, line 20 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51917#-MJCznj53i2byb-ggjDr:-MJCznj6-6NfbcHi9Iug:b-xqgf4h) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc60fecaa5a59acffa44a3e9f50d82168a5f2556/pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/distributed.tsx#L20)):*
> ```XML
> 
> export default function (props: GraphDashboardProps) {
>   const { nodeIDs, nodesSummary, nodeSources, storeSources } = props;
> ```

Frontend changes LGTM

@taroface want to make sure you have :eyes: on changes in the Distributed dashboard.

**Comment by taroface** [comment]
> @taroface want to make sure you have 👀 on changes in the Distributed dashboard.

Thanks! This should be picked up as a release-note issue since it has an annotation.

**Comment by aayushshah15** [comment]
Friendly ping. Not urgent at all, but I wanted to make sure we get this (or something like this) into 21.1.

**Pull request closed without merging**
