### PR TITLE
sql: enable interleaved tables

### LINKED ISSUE #2972: sql: support interleaved tables
Support F1/Spanner-style interleaved tables where the descendent table's data is interleaved in the parent table allowing for much faster joins when joining on the interleaving key.

### PR DESCRIPTION
**Pull request by danhhz**
There is more performance tuning to do and joins between interleaved tables are
not optimized, but the format version changes are done.

This commit and after are incompatible with releases prior to beta-20160721.

Closes #2972.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7985)

### CODE REVIEW

**Comment by paperstreet** [comment]
When you get back, let's chat about at what point we're okay with merging this.

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/sqlbase/structured.go, line 272 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7985#-KNmZiz8kcHM-J1Brgvx:-KNmZiz8kcHM-J1Brgvy:300906383) ([raw file](https://github.com/cockroachdb/cockroach/blob/097831a92c706ea3ea0e3b1792fd4fcf978c0c57/sql/sqlbase/structured.go#L272)):*
> ```Go
> // were made.
> func (desc *TableDescriptor) MaybeUpgradeFormatVersion() bool {
> 	if desc.FormatVersion == InterleavedFormatVersion {
> ```

Should this be `>=`? (same below)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7985#-:-KNmZpJ9af6tQawhLJk8:1417088721)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/sqlbase/structured.go, line 272 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7985#-KNmZiz8kcHM-J1Brgvx:-KNm_-UIXNY92-_Q0o1U:-1682309352) ([raw file](https://github.com/cockroachdb/cockroach/blob/097831a92c706ea3ea0e3b1792fd4fcf978c0c57/sql/sqlbase/structured.go#L272)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Should this be `>=`? (same below)
</details>
Actually this is interesting - if we update the format version and we have an older host, will it try to upgrade the column family things because it sees `InterleavedFormatVersion` which is `!= FamilyFormatVersion`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7985)*

**Comment by paperstreet** [comment]
A month later (I was waiting on a new beta to fix that ReferenceTest), RFAL

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/sqlbase/structured.go, line 272 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7985#-KNmZiz8kcHM-J1Brgvx:-KR04uY0QbP68LE3Oc4U:b-vz45j4) ([raw file](https://github.com/cockroachdb/cockroach/blob/097831a92c706ea3ea0e3b1792fd4fcf978c0c57/sql/sqlbase/structured.go#L272)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Actually this is interesting - if we update the format version and we have an older host, will it try to upgrade the column family things because it sees `InterleavedFormatVersion` which is `!= FamilyFormatVersion`?
</details>
Yeah, that's exactly what would happen and it's bad news. Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7985#-:-KR05pfayR-iNbUzhtlE:b-2jk3cn)*

**Comment by dt** [comment]
:lgtm:

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7985#-:-KR0IjMsC3f3JmiySDJc:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/sqlbase/structured.go, line 272 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7985#-KNmZiz8kcHM-J1Brgvx:-KR0M4COJpEa05WZ7hjx:b-hdah0q) ([raw file](https://github.com/cockroachdb/cockroach/blob/097831a92c706ea3ea0e3b1792fd4fcf978c0c57/sql/sqlbase/structured.go#L272)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> Yeah, that's exactly what would happen and it's bad news. Fixed
</details>
It's fixed now, but any existing older host still has the strict `FamilyFormatVersion` check.. Ideally we would ship at least a beta with the updated check for `FamilyFormatVersion` before adding a new version.. I would check with Ben or Peter before a final decision here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7985)*

**Comment by paperstreet** [comment]
Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[sql/sqlbase/structured.go, line 272 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7985#-KNmZiz8kcHM-J1Brgvx:-KR0OFMF4tDrU9s3d_Yt:b-i1a4sh) ([raw file](https://github.com/cockroachdb/cockroach/blob/097831a92c706ea3ea0e3b1792fd4fcf978c0c57/sql/sqlbase/structured.go#L272)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> It's fixed now, but any existing older host still has the strict `FamilyFormatVersion` check.. Ideally we would ship at least a beta with the updated check for `FamilyFormatVersion` before adding a new version.. I would check with Ben or Peter before a final decision here.
</details>
We did, actually. beta-20160829 has the correct check for FamilyFormatVersion

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7985)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/sqlbase/structured.go, line 272 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7985#-KNmZiz8kcHM-J1Brgvx:-KR0Q8ZYRTXaq6sgwQRo:bgmwa5z) ([raw file](https://github.com/cockroachdb/cockroach/blob/097831a92c706ea3ea0e3b1792fd4fcf978c0c57/sql/sqlbase/structured.go#L272)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> We did, actually. beta-20160829 has the correct check for FamilyFormatVersion
</details>
Nice! You rock. That explains this: https://github.com/Reviewable/Reviewable/issues/394 haha

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7985)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7985#-:-KR0Q_vhQsFqwTz4yReQ:bnfp4nl)*

**Comment by paperstreet** [comment]
TFTRs

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[sql/sqlbase/structured.go, line 272 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7985#-KNmZiz8kcHM-J1Brgvx:-KR0b3Teu3tLj6HRGhvY:b-8hm3ak) ([raw file](https://github.com/cockroachdb/cockroach/blob/097831a92c706ea3ea0e3b1792fd4fcf978c0c57/sql/sqlbase/structured.go#L272)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Nice! You rock. That explains this: https://github.com/Reviewable/Reviewable/issues/394 haha
</details>
:flushed: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7985#-:-KR0bFudiWRKl7nEWk1C:b-814g6a)*

**Pull request merged**
