### PR TITLE
*: assorted test fixes (continued)

### PR DESCRIPTION
**Pull request by knz**
Informs #100477.
Includes #100490.
Rebased on top of #100487.

Epic: CRDB-28893

### CODE REVIEW

**Review by stevendanna — APPROVED** [review]

**Comment by knz** [comment]
TFYR!

bors r=stevendanna

**Comment by knz** [comment]
oops

bors r-

**Comment by knz** [comment]
bors r=stevendanna

**Comment by knz** [comment]
bors r=stevendanna

**Comment by knz** [comment]
bors r=stevendanna p=99 single on

**Comment by knz** [comment]
bors r=stevendanna p=99 single on

**Pull request merged**
