### PR TITLE
roachtest: prevent backup-restore deadlock

### PR DESCRIPTION
**Pull request by msbutler**
Previously, if the main backup-restore goroutine early exited due to an error,
the workload goroutine would never cancel, causing the test to hang on m.Wait()
until the test timeout. This patch prevents this.

Informs: #111890

Release note: none

### CODE REVIEW

**Comment by msbutler** [comment]
first commit tracked in https://github.com/cockroachdb/cockroach/pull/114797

**Comment by renatolabs** [comment]
Is there an easy way for me to reproduce the original deadlock? Wanted to understand the issue a little better.

**Comment by msbutler** [comment]
you could run the `backup-restore/mock` roachtest off of this [draft PR](https://github.com/cockroachdb/cockroach/pull/115062)  after removing the sha that fixes the race condition. 

(I could also close this PR, and we could review everything in my draft PR)

**Comment by msbutler** [comment]
ah, and you'll have to delete this insert line as well
https://github.com/cockroachdb/cockroach/blob/7042d9c7ca8c71433bced790b7cfa75d087ce0b9/pkg/cmd/roachtest/tests/backup_restore_roundtrip.go#L237

**Comment by renatolabs** [comment]
> if the main backup-restore goroutine early exited due to an error, the workload goroutine would never cancel, causing the test to hang on m.Wait() until the test timeout

Maybe there's some nuance I'm missing (let me know), but in that case, wouldn't be enough to call call the `stopBackgroundCommands` func on a `defer`?

**Comment by msbutler** [comment]
@renatolabs your idea for simplifying `workloadWithCancel` works!

**Review by renatolabs — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114816#-:-NkQakua26tO4fikXTRv:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru and @msbutler)

___
*[`pkg/cmd/roachtest/tests/backup_restore_roundtrip.go` line 334 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/114816#-NkQafio0y_GCiF-2NXE:-NkQafio0y_GCiF-2NXF:b-rsizmf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b5f85a69b58f5c76e8f9bac349383f82f994a9f/pkg/cmd/roachtest/tests/backup_restore_roundtrip.go#L334)):*
> ```Go
> 
> 	return func() {
> 		cancelWorkload()
> ```

Nit: `return cancelWorkload`.

**Comment by msbutler** [comment]
TFTR!

bors r=renatolabs

**Comment by renatolabs** [comment]
> first commit tracked in https://github.com/cockroachdb/cockroach/pull/114797

Don't we want to review / merge that first, then?

**Pull request merged**
