### PR TITLE
scripts: move drtprod to bin/

### PR DESCRIPTION
**Pull request by dt**
We previously held off on doing this as it was unclear if this was a script like bump_pebble.sh that people expect to run from scripts, or a utility tool, like roachprod, which people expect to run from the PATH, which typically is configured to include bin. Hands-on experience says it is the latter, with its unusual location in scripts causing mild confusion.

Release note: none.
Epic: none.

### CODE REVIEW

**Review by itsbilal — COMMENTED** [review]
LGTM

**Comment by dt** [comment]
TFTR!

bors r+

**Review by itsbilal — APPROVED** [review]
My bad

**Comment by dt** [comment]
once more with feeling

bors r+

**Pull request merged**
