### PR TITLE
roachtest: add test to exercise multiple upgrades in a single test

### PR DESCRIPTION
**Pull request by renatolabs**
All of our existing mixed-version roachtests only test that a node
running the previous version can be upgraded to the current one. In
order to expand the coverage of upgrade-related paths, this commit
introduces a new roachtest (`tpcc/mixed-headroom/multiple-upgrades`)
that starts off 2 releases prior to the current one, and upgrades a
cluster all the way to the current cockroach version.

The test is a variation of the existing `tpcc/mixed-headroom` test,
and uses the same structure: a large bank dataset is imported, and the
upgrade happens while a `tpcc` workload is running.

Note that currently failures that happen during the upgrade from two
releases prior to the previous release will still fail the test and
create a GitHub issue for the Test Eng team to investigate. In the
future, we may consider only creating issues if the upgrade is related
to the "final" upgrade in the test, when the cluster is being upgraded
to the current version. Upgrades to older releases should already be
covered by roachtests in release branches, and such failures would
mostly just add noise.

Epic: CRDB-19321
Jira issue: [CRDB-20907](https://cockroachlabs.atlassian.net/browse/CRDB-20907)
Release note: None

### CODE REVIEW

**Comment by renatolabs** [comment]
If you're planning to review this PR, please take a look at https://github.com/cockroachdb/cockroach/pull/90399 first, please. It's a small PR and I want to get that merged first and incorporate that change into this test.

**Review by srosenberg — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90654)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, and @smg260)

___
*[`pkg/cmd/roachtest/tests/acceptance.go` line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90654#-NFGWH5a5GmC1aG8Vbuo:-NFGWH5b82hAGDSEG3aw:b-65oqcu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5decaeb69155399647909163451f3d8ca7858b6/pkg/cmd/roachtest/tests/acceptance.go#L46)):*
> ```Go
> 			{
> 				name: "many-splits", fn: runManySplits,
> 				minVersion:        "v19.2.0", // SQL syntax unsupported on 19.1.x
> ```

Thanks for removing; it misled me at least once before.
___
*[`pkg/cmd/roachtest/tests/predecessor_version.go` line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90654#-NFGWXc08vkhR3Hhomjt:-NFGWXc08vkhR3Hhomju:b-qzc4xy) ([raw file](https://github.com/cockroachdb/cockroach/blob/0158e2a800216987485185f75200445de4216e8b/pkg/cmd/roachtest/tests/predecessor_version.go#L45)):*
> ```Go
> }
> 
> // PredecessorHistory returns the last `n` releases that precede the
> ```

Nit: maybe it's best to reserve `k` to denote an offset relative to the version number, if only because our current terminology
uses `n` to denote an absolute version number; `n +/- k` typically refers to a previous/future version.
___
*[`pkg/cmd/roachtest/tests/predecessor_version.go` line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90654#-NFGXpPr4z18c7ota4Fn:-NFGXpPr4z18c7ota4Fo:b-j9hvi2) ([raw file](https://github.com/cockroachdb/cockroach/blob/0158e2a800216987485185f75200445de4216e8b/pkg/cmd/roachtest/tests/predecessor_version.go#L45)):*
> ```Go
> }
> 
> // PredecessorHistory returns the last `n` releases that precede the
> ```

Nit: comment description can be made more precise, 

```
PredecessorHistory returns the last consecutive `k` release versions that precede the given buildVersion, 
in the upgrade order. E.g., if buildVersion=22.2, k=2, then ["21.12.7", "22.1.6"] is returned.
```
___
*[`pkg/cmd/roachtest/tests/tpcc.go` line 453 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90654#-NFGaj-x7UB1Nc5wQdkS:-NFGaj-x7UB1Nc5wQdkT:b-5z3936) ([raw file](https://github.com/cockroachdb/cockroach/blob/0158e2a800216987485185f75200445de4216e8b/pkg/cmd/roachtest/tests/tpcc.go#L453)):*
> ```Go
> 			// to get a better idea of what errors come back here, if any.
> 			// This will block until the long-running migrations have run.
> 			allowAutoUpgradeStep(randomCRDBNode()),
> ```

Nice! `n1` has been given too much bias :)

**Review by renatolabs — COMMENTED** [review]
This is RFAL.

* Tests changed here ran successfully on this branch last night
* I incorporated #90399 back, this time properly passing the ramp duration to the `workload` command.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90654#-:-NFO_EJWC8f_PjJmNev5:b-theq7x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan, @smg260, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/predecessor_version.go` line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90654#-NFGWXc08vkhR3Hhomjt:-NFO_9xODcSeyGyIbiJC:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/0158e2a800216987485185f75200445de4216e8b/pkg/cmd/roachtest/tests/predecessor_version.go#L45)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Nit: maybe it's best to reserve `k` to denote an offset relative to the version number, if only because our current terminology
uses `n` to denote an absolute version number; `n +/- k` typically refers to a previous/future version.
</blockquote></details>

Updated.
___
*[`pkg/cmd/roachtest/tests/predecessor_version.go` line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90654#-NFGXpPr4z18c7ota4Fn:-NFO_Akq3qER3mWvykj9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0158e2a800216987485185f75200445de4216e8b/pkg/cmd/roachtest/tests/predecessor_version.go#L45)):*
<details><summary><i>Previously, srosenberg (Stan Rosenberg) wrote…</i></summary><blockquote>

Nit: comment description can be made more precise, 

```
PredecessorHistory returns the last consecutive `k` release versions that precede the given buildVersion, 
in the upgrade order. E.g., if buildVersion=22.2, k=2, then ["21.12.7", "22.1.6"] is returned.
```
</blockquote></details>

Done.

**Review by srosenberg — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90654#-:-NFPJYFrCS5VK4lBInem:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @renatolabs, and @smg260)

**Comment by renatolabs** [comment]
bors r=srosenberg

TFTR!

**Pull request merged**
