### PR TITLE
ui: General Query Manager Saga

### PR DESCRIPTION
**Pull request by mrtracy**
Infrastructure for a general query manager saga - manages limited
dispatch, timed refresh and error retries for arbitrary queries
expressed as sagas. This is intended to replace the thunk-based
infrastructure for all current queries, excepting the metrics queries
(which are already handled in a saga).

Has the following features:

+ Each query is an object with a unique ID, a saga function which
  expresses the body of the query, and optional refresh and retry delays.
+ Queries can be dispatched with one of two actions:
  + "Refresh", which refreshes the query immediately.
  + "AutoRefresh", which refreshes it periodically on a interval.
  AutoRefresh is reference counted, and is paired with "StopAutoRefresh".
  The intention is that these would be fired in react components when they
  mount and unmount.
+ Only one instance of a query can be running at a time.
+ Error results are stored in a central location by the query manager.
  Individual queries are responsible for storing results in the redux
  store, giving greater flexibility for more complicated queries in the
  future.

Release note: None.

### CODE REVIEW

**Review by couchand — CHANGES_REQUESTED** [review]
This looks really good generally.  I think it's much clearer than the current code, particularly in the tests.

I haven't run it locally or gone over the tests with a fine-tooth comb yet.  I'll do that after the below discussions (and any that @vilterp might start) seem relatively settled.

> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27661#-:-LIlkTgS2K80K7pXwWlG:bjqkmco)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ui/src/redux/queryManager/saga.ts, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27661#-LIlhwuQ1q_zXoV4pwxi:-LIlhwuQ1q_zXoV4pwxj:b-vausw2) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d18dc5abb5cdd2cc361e7d6b0504ccf37550daf/pkg/ui/src/redux/queryManager/saga.ts#L47)):*
> ```XML
> interface QueryRefreshAction extends Action {
>     type: typeof QUERY_REFRESH;
>     query: ManagedQuery;
> ```

I think for my part I'd prefer if the actions just had the query id, and all the specific configuration was limited to a single config call at application start-up.  Passing all the details in each action just encourages the wrong sort of ad-hoc usage. (I recognize that realistically they'll always be wrapped up in an action creator anyway).  I'm imagining that the main saga becomes a factory method accepting a map of ManagedQuery config objects and returning the main saga.
___
*[pkg/ui/src/redux/queryManager/saga.ts, line 216 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27661#-LIlj9tj0FBzPtHigAf5:-LIlj9tj0FBzPtHigAf6:banm7vi) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d18dc5abb5cdd2cc361e7d6b0504ccf37550daf/pkg/ui/src/redux/queryManager/saga.ts#L216)):*
> ```XML
>         yield race({
>             finished: join(queryTask),
>             nextAction: call(processQueryManagementAction, state),
> ```

Could you reasonably pull this and the other race against `processQueryManagementAction` up into a higher level?  It seems like that could always be running on the side while the refresh and/or delay loop runs in the other coprocess.  Does that make sense?
___
*[pkg/ui/src/redux/queryManager/saga.ts, line 244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27661#-LIlkD0I9RKaQNVLvGk1:-LIlkD0I9RKaQNVLvGk2:b-1kcp9x) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d18dc5abb5cdd2cc361e7d6b0504ccf37550daf/pkg/ui/src/redux/queryManager/saga.ts#L244)):*
> ```XML
>         // If a request comes in to run the query immediately, or if the
>         // auto-refresh count drops to zero, cancel the delay task.
>         if (state.shouldRefreshQuery || state.autoRefreshCount === 0) {
> ```

should this condition be `state.autoRefreshCount <= 0` out of an abundance of caution?

**Review by mrtracy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27661)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ui/src/redux/queryManager/saga.ts, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27661#-LIlhwuQ1q_zXoV4pwxi:-LJCnbAqC4V6z6nowDTf:bcw98jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d18dc5abb5cdd2cc361e7d6b0504ccf37550daf/pkg/ui/src/redux/queryManager/saga.ts#L47)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

I think for my part I'd prefer if the actions just had the query id, and all the specific configuration was limited to a single config call at application start-up.  Passing all the details in each action just encourages the wrong sort of ad-hoc usage. (I recognize that realistically they'll always be wrapped up in an action creator anyway).  I'm imagining that the main saga becomes a factory method accepting a map of ManagedQuery config objects and returning the main saga.
</blockquote></details>

Hmm, i'll think about that.  However, I think the ad-hoc nature is part of the appeal of this design, it's very easy to just create a query and have it run.
___
*[pkg/ui/src/redux/queryManager/saga.ts, line 216 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27661#-LIlj9tj0FBzPtHigAf5:-LJCgxTH4iIcrfgcFMw5:bhpibq4) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d18dc5abb5cdd2cc361e7d6b0504ccf37550daf/pkg/ui/src/redux/queryManager/saga.ts#L216)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

Could you reasonably pull this and the other race against `processQueryManagementAction` up into a higher level?  It seems like that could always be running on the side while the refresh and/or delay loop runs in the other coprocess.  Does that make sense?
</blockquote></details>

That might be acceptable given the current, simple design of `refreshQuery` where it is not cancellable, but it does not work for `waitForNextRefresh`. The issue is that, depending on the results of `processQueryManagementAction`, we sometimes cancel the delay and immediately run the query (or stop refreshing the query at all).

If processQueryManagementAction was structured as a forked, persistent loop, we would need to store a reference to the `waitForNextRefresh` task in order to do a `yield cancel()`, and that would also necessarily make processQueryManagementAction much more complex. 

By structuring it as a race with processQueryManagementAction, instead `processQueryManagementAction` is a simple one-time function.

To underscore this, your suggestion was somewhat similar to the original way I structured this, and it was not very clean; it actually had me questioning the utility of the library. However, this very clean structure (and mostly the body of `managedQuerySaga`) are what convinced me that this was the way to go.
___
*[pkg/ui/src/redux/queryManager/saga.ts, line 244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27661#-LIlkD0I9RKaQNVLvGk1:-LJCnZiAANTZGaxx4vv9:b-xh2uwm) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d18dc5abb5cdd2cc361e7d6b0504ccf37550daf/pkg/ui/src/redux/queryManager/saga.ts#L244)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

should this condition be `state.autoRefreshCount <= 0` out of an abundance of caution?
</blockquote></details>

Hmm, I don't see why not. Done.

**Review by couchand — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27661)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ui/src/redux/queryManager/saga.ts, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27661#-LIlhwuQ1q_zXoV4pwxi:-LKNAE_4-FtErHASrZck:b-25ax9x) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d18dc5abb5cdd2cc361e7d6b0504ccf37550daf/pkg/ui/src/redux/queryManager/saga.ts#L47)):*
> the ad-hoc nature is part of the appeal of this design

Oh?  I'm curious to hear more.  As a general rule I think ad-hoc architecture leads to confusion, so I'm interested why it's appealing to you in this case.
___
*[pkg/ui/src/redux/queryManager/saga.ts, line 216 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27661#-LIlj9tj0FBzPtHigAf5:-LKNA16I0zPKcvq6g8q1:b-i9aqvp) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d18dc5abb5cdd2cc361e7d6b0504ccf37550daf/pkg/ui/src/redux/queryManager/saga.ts#L216)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

That might be acceptable given the current, simple design of `refreshQuery` where it is not cancellable, but it does not work for `waitForNextRefresh`. The issue is that, depending on the results of `processQueryManagementAction`, we sometimes cancel the delay and immediately run the query (or stop refreshing the query at all).

If processQueryManagementAction was structured as a forked, persistent loop, we would need to store a reference to the `waitForNextRefresh` task in order to do a `yield cancel()`, and that would also necessarily make processQueryManagementAction much more complex. 

By structuring it as a race with processQueryManagementAction, instead `processQueryManagementAction` is a simple one-time function.

To underscore this, your suggestion was somewhat similar to the original way I structured this, and it was not very clean; it actually had me questioning the utility of the library. However, this very clean structure (and mostly the body of `managedQuerySaga`) are what convinced me that this was the way to go.
</blockquote></details>

I think there's a way to do it without holding a reference to the task, but I don't want to dive into it yet, because:

When looking into this, I noticed this line from the docs: "Another useful feature of race is that it automatically cancels the loser Effects."  Is that the behavior we want in this case?  If any other query action comes in we'll cancel the outstanding request?

**Review by mrtracy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27661)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ui/src/redux/queryManager/saga.ts, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27661#-LIlhwuQ1q_zXoV4pwxi:-LKNcwuUALMHDNoAVDpK:b12u5s9) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d18dc5abb5cdd2cc361e7d6b0504ccf37550daf/pkg/ui/src/redux/queryManager/saga.ts#L47)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

> the ad-hoc nature is part of the appeal of this design

Oh?  I'm curious to hear more.  As a general rule I think ad-hoc architecture leads to confusion, so I'm interested why it's appealing to you in this case.
</blockquote></details>

Ad-hoc architecture can also lead to ease of development; for example, consider all of the people developing debug pages who just want to run a one-off query for data.  They could write that query but still get all the benefits of query management (error management, eliminating duplicate queries, auto-refresh if desired) without having to register anything. It eliminates boilerplate considerably.

The confusion only arises if someone accidentally duplicates an ID, but you have to ask yourself - 1. what is the chance that this would occur in a project this size, and 2. how difficult would that bug be to detect? Would it be subtle, or would it be obvious?
___
*[pkg/ui/src/redux/queryManager/saga.ts, line 216 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27661#-LIlj9tj0FBzPtHigAf5:-LKNceVa8ATWqQTFjI0H:bua64la) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d18dc5abb5cdd2cc361e7d6b0504ccf37550daf/pkg/ui/src/redux/queryManager/saga.ts#L216)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

I think there's a way to do it without holding a reference to the task, but I don't want to dive into it yet, because:

When looking into this, I noticed this line from the docs: "Another useful feature of race is that it automatically cancels the loser Effects."  Is that the behavior we want in this case?  If any other query action comes in we'll cancel the outstanding request?
</blockquote></details>

No it won't, that's why we use the `join` instead of just racing on the task itself.  That means the join "task" gets cancelled instead of the query - very explicitly, only one query is allowed at a time.

Now, it is *possible* to write this so that in-progress queries get cancelled; in fact, that could be an option of the query, and is a straightforward extension of this. However, we have no use case for it currently, so I left that out.

**Review by mrtracy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27661)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ui/src/redux/queryManager/saga.ts, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27661#-LIlhwuQ1q_zXoV4pwxi:-LKNds1E43Mc6dKYY98C:b-bbfjnn) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d18dc5abb5cdd2cc361e7d6b0504ccf37550daf/pkg/ui/src/redux/queryManager/saga.ts#L47)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

Ad-hoc architecture can also lead to ease of development; for example, consider all of the people developing debug pages who just want to run a one-off query for data.  They could write that query but still get all the benefits of query management (error management, eliminating duplicate queries, auto-refresh if desired) without having to register anything. It eliminates boilerplate considerably.

The confusion only arises if someone accidentally duplicates an ID, but you have to ask yourself - 1. what is the chance that this would occur in a project this size, and 2. how difficult would that bug be to detect? Would it be subtle, or would it be obvious?
</blockquote></details>

In regards to those questions, I believe a duplicate ID is unlikely and that it wouldn't be very hard to debug.

**Comment by couchand** [comment]
:LGTM:

Per IRL conversation, I still have some disagreement about the specifics but they aren't blockers.

**Comment by mrtracy** [comment]
bors r=couchand

**Review by couchand — APPROVED** [review]

**Comment by couchand** [comment]
:lgtm_strong:

**Comment by mrtracy** [comment]
bors r=couchand

**Pull request merged**
