### PR TITLE
acceptance: avoid closing stderr on running cluster

### PR DESCRIPTION
**Pull request by danhhz**
Before this, an interrupted ssh connection would panic the remote
cockroach instances because they could no longer write to stdout/stderr.
Instead, redirect it to a file on the remote machine.

### CODE REVIEW

**Comment by tamird** [comment]
Hm, why is the (parent) cockroach process (which was started with `--background`) doing anything at all after the `--listening-url` file has been written?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17967#-:-KseIR7Mf1Puufu6xCre:bf6r581)*

**Comment by benesch** [comment]
I'm not sure I understand your question. The child proc gets a copy of the parent's file descriptors, and stdout/stderr are magic SSH file descriptors unless redirected.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17967#-:-KseJ_qzjWu7L_CI0K9_:b-g83d15)*

**Comment by tamird** [comment]
But isn't the child logging to files by default? What's going out to stdout/stderr?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17967#-:-KseK1Vce8a0edwS2kdj:b-27rmcq)*

**Comment by benesch** [comment]
`log.Shout` will try to write to stderr, and it's real confusing if it panics while reporting a panic. I'll bet the specific case we saw, though, was a `fmt.Printf` that was introduced for debugging.

Either way, it's nice to have stdout and stderr saved somewhere more durable than the acceptance test's binary's address space. I frequently lose my network connection while running these five hour 2TB restore tests, and there's no getting stdout/stderr back after that.

**Comment by cuongdo** [comment]
:lgtm:

Have you tested this by also running an allocator test? I think it's sufficient to run it for 10-15 minutes after initial VM setup completes.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17967#-:-KsehDOqql7ty-TUByeQ:b-pxfy26)*

**Comment by tamird** [comment]
:lgtm:

would be nice to have some of this detail in the commit message or in a code comment.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/acceptance/terrafarm/farmer.go, line 504 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17967#-Ksfa2S3Yb7tlIVhWaci:-Ksfa2S46uX9O6ddR0DS:bkv7dys) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd325b1f254ce575d07bd9ad83df9a7c1517c4c6/pkg/acceptance/terrafarm/farmer.go#L504)):*
> ```Go
> 			err := s.Wait()
> 			const logMsg = `see logs/cockroach.stdout and logs/cockroach.stderr on the remote server for details`
> 			done <- errors.Wrapf(err, "failed: %s\n\n(%s)", cmd, logMsg)
> ```

`cmd` now includes the redirects, so i dunno that `logMsg` is needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17967#-:-Ksfa8Y3GZbHelfMo5no:bcqcbfy)*

**Comment by danhhz** [comment]
@tamird captured some of the above discussion

@cuongdo Running an allocator test now. I'll update if there are any issues

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/acceptance/terrafarm/farmer.go, line 504 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17967#-Ksfa2S3Yb7tlIVhWaci:-KsinVnT7QeaMMv_Qjmr:b-7qmo62) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd325b1f254ce575d07bd9ad83df9a7c1517c4c6/pkg/acceptance/terrafarm/farmer.go#L504)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

`cmd` now includes the redirects, so i dunno that `logMsg` is needed.
</blockquote></details>

Good point. Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17967#-:-KsiueOH_j4l_hrDXdTx:b-axt86l)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/acceptance/terrafarm/farmer.go, line 487 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17967#-Ksixh3_dU9ek_gPatbY:-Ksixh3_dU9ek_gPatbZ:b6zo1sm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef2c0b62b365a1307a55669eeabc28c630860347/pkg/acceptance/terrafarm/farmer.go#L487)):*
> ```Go
> 	// panicing.
> 	//
> 	// It's also nice to have stderr and stdout collected on the cluster
> ```

:100: thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17967)*

**Comment by benesch** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17967#-:-KsixoDlN-SAGzUgNqS_:bnfp4nl)*

**Comment by danhhz** [comment]
My allocator test has been running for 20 minutes. I was going to wait it out, but from interpolating the admin ui graphs, looks like that won't be soon. @cuongdo said 10-15 minutes was enough, so I'm going to go ahead and merge.

Thanks for the reviews, all!

**Pull request merged**
