### PR TITLE
storage/concurrency: add support for non-transactional writes to

### PR DESCRIPTION
**Pull request by sumeerbhola**
lockTable.
And updated the datadriven and randomized tests to exercise
non-transactional writes.

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44975)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/storage/concurrency/lock_table.go, line 556 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44975#-M-q_7HL9_4_ls6RDvzM:-M-q_7HM7yH6JygEaudc:b-9tp9i4) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a484c122548dfab48cfe0cec5a6ef914fff2fe8/pkg/storage/concurrency/lock_table.go#L556)):*
> ```Go
> 		waitForTxn = l.reservation.txn
> 		waitForTs = l.reservation.ts
> 		if !findDistinguished && l.distinguishedWaiter.txn != nil &&
> ```

Consider adding the following method to avoid all of these new nil-txn checks:
```
func (g *lockTableGuardImpl) isTxn(txn *enginepb.TxnMeta) bool { 
	return g.txn != nil && g.txn.ID == txn.ID
}
```
You could probably eliminate a few existing checks as well.
___
*[pkg/storage/concurrency/lock_table.go, line 716 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44975#-M-q_qA8-ZStvrsqhngV:-M-q_qA8-ZStvrsqhngW:bmpxxaj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a484c122548dfab48cfe0cec5a6ef914fff2fe8/pkg/storage/concurrency/lock_table.go#L716)):*
> ```Go
> 		waitForTs = l.reservation.ts
> 		reservedBySelfTxn = g.txn != nil && g.txn.ID == waitForTxn.ID
> 		if g.txn == nil && sa == spanset.SpanReadWrite && l.reservation.seqNum > g.seqNum {
> ```

The `sa == spanset.SpanReadWrite` is interesting. Is it needed? Is the corresponding `sa == spanset.SpanReadOnly` case already doing the same thing below (i.e. ignoring the reservation). Should it?
___
*[pkg/storage/concurrency/testdata/lock_table, line 1569 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44975#-M-qcaLCBn-sBsji_GNn:-M-qcaLD-Nip4k8gB7iP:blh9bdr) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a484c122548dfab48cfe0cec5a6ef914fff2fe8/pkg/storage/concurrency/testdata/lock_table#L1569)):*
> ```
>   res: req: 28, txn: 00000000-0000-0000-0000-000000000003, ts: 0.000000010,0
> local: num=0
> ```

Could you call `guard-state r=req27` and `guard-state r=req28` here and then `print` again?

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44975)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/storage/concurrency/lock_table.go, line 556 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44975#-M-q_7HL9_4_ls6RDvzM:-M-uBH987Ysdrx1dSrr3:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a484c122548dfab48cfe0cec5a6ef914fff2fe8/pkg/storage/concurrency/lock_table.go#L556)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Consider adding the following method to avoid all of these new nil-txn checks:
```
func (g *lockTableGuardImpl) isTxn(txn *enginepb.TxnMeta) bool { 
	return g.txn != nil && g.txn.ID == txn.ID
}
```
You could probably eliminate a few existing checks as well.
</blockquote></details>

Done
___
*[pkg/storage/concurrency/lock_table.go, line 716 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44975#-M-q_qA8-ZStvrsqhngV:-M-uCEWr3Z8CX-77ChaK:bts6rux) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a484c122548dfab48cfe0cec5a6ef914fff2fe8/pkg/storage/concurrency/lock_table.go#L716)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The `sa == spanset.SpanReadWrite` is interesting. Is it needed? Is the corresponding `sa == spanset.SpanReadOnly` case already doing the same thing below (i.e. ignoring the reservation). Should it?
</blockquote></details>

It isn't needed for correctness, but non-transactional and transactional reads are handled in the same way later. So this piece of code is meant to only handle non-transactional writes since they have specialized behavior related to not making reservations and only waiting for reservations in some cases. I've added a code comment.
___
*[pkg/storage/concurrency/testdata/lock_table, line 1569 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44975#-M-qcaLCBn-sBsji_GNn:-M-uCrFOB-fYsq6tnCMn:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a484c122548dfab48cfe0cec5a6ef914fff2fe8/pkg/storage/concurrency/testdata/lock_table#L1569)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Could you call `guard-state r=req27` and `guard-state r=req28` here and then `print` again?
</blockquote></details>

Done

**Review by nvb — APPROVED** [review]
:lgtm: this will need to be rebased on https://github.com/cockroachdb/cockroach/pull/45010, and I think you'll probably want to pull the new test cases into a `testdata/lock_table/non_txn` file. Once that's done, feel free to merge and I'll rebase https://github.com/cockroachdb/cockroach/pull/44885 on top of this.

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44975#-:-M-uNZFW5yr6m2wV3AMH:b-2rvok8)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by sumeerbhola — COMMENTED** [review]
> this will need to be rebased on #45010, and I think you'll probably want to pull the new test cases into a testdata/lock_table/non_txn file.

Done

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44975#-:-M-ubOHy1E3QPg_K4aJN:b-9vi80r)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

**Pull request merged**
