### PR TITLE
kvserver,storage: plumbing for CategoryAndQoS for categorized iterato…

### PR DESCRIPTION
**Pull request by sumeerbhola**
…r stats

Informs https://github.com/cockroachdb/pebble/issues/3014

Epic: none

Release note: None

### CODE REVIEW

**Comment by sumeerbhola** [comment]
Running this on CockroachDB with 

./workload run kv --init --histograms=perf/stats.json --concurrency=500 --splits=1000 --duration=120m0s --read-percent=50 --min-block-bytes=1024 --max-block-bytes=1024  --tolerate-errors --max-rate=9000 {pgurl:1-1}

and then starting at 23:11
./workload run kv --init --histograms=perf/stats.json --concurrency=50 --splits=1000 --duration=120m0s --span-percent=50 --span-limit=1 --min-block-bytes=1024 --max-block-bytes=1024  --tolerate-errors --max-rate=5000 --background-qos=true {pgurl:1-1}

Screenshot 2023-11-21 at 6 26 55 PM

**Review by jbowens — APPROVED** [review]
Exciting!

:lgtm_strong: 

> Reviewed 66 of 67 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114868#-:-Njs_YYR-MAVonnCcBoi:bdnmhsz)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by sumeerbhola** [comment]
TFTR!

**Comment by sumeerbhola** [comment]
bors r=jbowens

**Comment by sumeerbhola** [comment]
bors r=jbowens

**Pull request merged**
