### PR TITLE
sql: support INVERTED when creating indexes

### PR DESCRIPTION
**Pull request by m-schneider**
Adding parsing support for CREATE INVERTED INDEX...

### CODE REVIEW

**Comment by justinj** [comment]
What was the outcome of also supporting `...USING GIN`? I thought the plan was to support it but not talk it up too much?

---

Review status: 0 of 5 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[pkg/sql/create.go, line 192 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172#-KzQ4dlhbMC5-XCCRMqe:-KzQ4dlhbMC5-XCCRMqf:b-byhxn4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1d549dd9135cc4face24c5591691762b305e9ce/pkg/sql/create.go#L192)):*
> ```Go
> 	}
> 
> 	if n.n.Inverted == true {
> ```

nit: `s/ == true//`

---

*[pkg/sql/create.go, line 193 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172#-KzQ4TL7WRTPfa2yQWm4:-KzQ4TL7WRTPfa2yQWm5:b-wfm3dm) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1d549dd9135cc4face24c5591691762b305e9ce/pkg/sql/create.go#L193)):*
> ```Go
> 
> 	if n.n.Inverted == true {
> 		return errors.New("inverted indexes are not supported yet")
> ```

`pgerror.NewError(pgerror.CodeFeatureNotSupportedError, ...` is slightly more semantic

---

*[pkg/sql/logictest/testdata/logic_test/inverted_index, line 15 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172#-KzQ4m__jLLOGFMznmnH:-KzQ4m__jLLOGFMznmnI:b-lpd63g) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1d549dd9135cc4face24c5591691762b305e9ce/pkg/sql/logictest/testdata/logic_test/inverted_index#L15)):*
> ```
> CREATE INDEX foo ON t (b)
> 
> statement error pq: inverted indexes are not supported yet
> ```

nit: we usually leave off the `pq:` prefix (this message is a regex). Can you also include a test of specifying said inverted index on the `create table` statement?

---

*[pkg/sql/logictest/testdata/logic_test/inverted_index, line 16 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172#-KzQ673w3sS4TzG7oyDM:-KzQ673xn96StbSILiND:b-e7lmpc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1d549dd9135cc4face24c5591691762b305e9ce/pkg/sql/logictest/testdata/logic_test/inverted_index#L16)):*
> ```
> 
> statement error pq: inverted indexes are not supported yet
> CREATE INVERTED INDEX fooInv ON t (b)
> ```

super nit: I think we usually use `snake_case` for identifiers in logic tests.

---

*[pkg/sql/parser/parse_test.go, line 91 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172#-KzQ5qRa2hFZ0p8UjTPD:-KzQ5qRa2hFZ0p8UjTPE:b2zi3r8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1d549dd9135cc4face24c5591691762b305e9ce/pkg/sql/parser/parse_test.go#L91)):*
> ```Go
> 		{`CREATE INVERTED INDEX a ON b (c) INTERLEAVE IN PARENT d (e, f)`},
> 		{`CREATE INVERTED INDEX a ON b (c) INTERLEAVE IN PARENT d.e (f, g)`},
> 		{`CREATE INVERTED INDEX a ON b.c (d)`},
> ```

Same here, some tests of its use in the create table statement would be good.

---

*[pkg/sql/parser/sql.y, line 3356 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172#-KzQ5QqFqqZbdx1iMErO:-KzQ5QqFqqZbdx1iMErP:bjcm7vh) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1d549dd9135cc4face24c5591691762b305e9ce/pkg/sql/parser/sql.y#L3356)):*
> ```Yacc
>     }
>   }
> | CREATE INVERTED INDEX IF NOT EXISTS name ON qualified_name '(' index_params ')' opt_storing opt_interleave
> ```

huh, I wonder why we don't make `IF NOT EXISTS` its own rule elsewhere? this is fine since it matches the other patterns but seems a bit non-DRY to me.

---

*[pkg/sql/sem/tree/create.go, line 105 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172#-KzQ5eWysQjejKL1_NSA:-KzQ5eWysQjejKL1_NSB:b-d1pt6g) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1d549dd9135cc4face24c5591691762b305e9ce/pkg/sql/sem/tree/create.go#L105)):*
> ```Go
> 	Table       NormalizableTableName
> 	Unique      bool
> 	Inverted    bool
> ```

Might it make sense for this to be its own node, rather than a field on the existing struct? How many of the fields used by `CreateIndex` will also be relevant to inverted indexes? If it does make sense for them to share the struct, maybe we could make the "kind" of index an enum rather than having a `bool` for both Unique and Inverted.

---

*[pkg/sql/sem/tree/create.go, line 527 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172#-KzQ6n-evoikkxp7iB4e:-KzQ6n-evoikkxp7iB4f:b-ib54sy) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1d549dd9135cc4face24c5591691762b305e9ce/pkg/sql/sem/tree/create.go#L527)):*
> ```Go
> type InvertedConstraintTableDef struct {
> 	IndexTableDef
> 	PrimaryKey bool
> ```

An inverted index can never be the primary index, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172#-:-KzQ4yKOm_7KOfcQgZYR:btumikd)*

**Comment by m-schneider** [comment]
I added USING GIN.

---

Review status: 0 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[pkg/sql/create.go, line 192 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172#-KzQ4dlhbMC5-XCCRMqe:-KzQYMDGfRfNI6cv2lS3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1d549dd9135cc4face24c5591691762b305e9ce/pkg/sql/create.go#L192)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

nit: `s/ == true//`
</blockquote></details>

Done.

---

*[pkg/sql/create.go, line 193 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172#-KzQ4TL7WRTPfa2yQWm4:-KzQ98buvy_6tpIZMpov:bkrncjk) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1d549dd9135cc4face24c5591691762b305e9ce/pkg/sql/create.go#L193)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

`pgerror.NewError(pgerror.CodeFeatureNotSupportedError, ...` is slightly more semantic
</blockquote></details>

Ah thanks for that!

---

*[pkg/sql/logictest/testdata/logic_test/inverted_index, line 15 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172#-KzQ4m__jLLOGFMznmnH:-KzQ9CzaIJN-rm5AzRvK:bbed1vz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1d549dd9135cc4face24c5591691762b305e9ce/pkg/sql/logictest/testdata/logic_test/inverted_index#L15)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

nit: we usually leave off the `pq:` prefix (this message is a regex). Can you also include a test of specifying said inverted index on the `create table` statement?
</blockquote></details>

Jordan and I talked about it and we're not going to support that in v1.

---

*[pkg/sql/logictest/testdata/logic_test/inverted_index, line 16 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172#-KzQ673w3sS4TzG7oyDM:-KzQYNEPnEiSQ9KW1SsD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1d549dd9135cc4face24c5591691762b305e9ce/pkg/sql/logictest/testdata/logic_test/inverted_index#L16)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

super nit: I think we usually use `snake_case` for identifiers in logic tests.
</blockquote></details>

Done.

---

*[pkg/sql/parser/parse_test.go, line 91 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172#-KzQ5qRa2hFZ0p8UjTPD:-KzQ9N-tlh2MepQQl4QZ:b2nreh6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1d549dd9135cc4face24c5591691762b305e9ce/pkg/sql/parser/parse_test.go#L91)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Same here, some tests of its use in the create table statement would be good.
</blockquote></details>

Same as above.

---

*[pkg/sql/sem/tree/create.go, line 527 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172#-KzQ6n-evoikkxp7iB4e:-KzQ9_eALs5oL0jVMjSw:b2nhky0) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1d549dd9135cc4face24c5591691762b305e9ce/pkg/sql/sem/tree/create.go#L527)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

An inverted index can never be the primary index, right?
</blockquote></details>

No.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172#-:-KzQYBrhl6eQdAQSfIUr:b3gc462)*

**Comment by justinj** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/sql/logictest/testdata/logic_test/inverted_index, line 15 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172#-KzQ4m__jLLOGFMznmnH:-KzUYBKjfsxNVQvgOYUQ:b1kdzzg) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1d549dd9135cc4face24c5591691762b305e9ce/pkg/sql/logictest/testdata/logic_test/inverted_index#L15)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

Jordan and I talked about it and we're not going to support that in v1.
</blockquote></details>

This commit includes an implementation of that though, doesn't it? That's the modification to the `index_def` rule?

---

*[pkg/sql/sem/tree/create.go, line 527 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172#-KzQ6n-evoikkxp7iB4e:-KzUYPpa0By4zknl_yBf:bta74jk) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1d549dd9135cc4face24c5591691762b305e9ce/pkg/sql/sem/tree/create.go#L527)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

No.
</blockquote></details>

So is there any reason to have this field in the struct?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172)*

**Comment by m-schneider** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/sql/logictest/testdata/logic_test/inverted_index, line 15 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172#-KzQ4m__jLLOGFMznmnH:-KzUe0k4UkYL7RCwMWAu:b-krx7zl) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1d549dd9135cc4face24c5591691762b305e9ce/pkg/sql/logictest/testdata/logic_test/inverted_index#L15)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

This commit includes an implementation of that though, doesn't it? That's the modification to the `index_def` rule?
</blockquote></details>

It doesn't parse. I added a test.

---

*[pkg/sql/parser/sql.y, line 3356 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172#-KzQ5QqFqqZbdx1iMErO:-KzUibEUR0M1a1m8fJLy:be1plwg) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1d549dd9135cc4face24c5591691762b305e9ce/pkg/sql/parser/sql.y#L3356)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

huh, I wonder why we don't make `IF NOT EXISTS` its own rule elsewhere? this is fine since it matches the other patterns but seems a bit non-DRY to me.
</blockquote></details>

I'm not sure but other recent PRs touching this code have used it like this.

---

*[pkg/sql/sem/tree/create.go, line 105 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172#-KzQ5eWysQjejKL1_NSA:-KzUhlVk3oa-tnu6wt7K:bcuwlft) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1d549dd9135cc4face24c5591691762b305e9ce/pkg/sql/sem/tree/create.go#L105)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Might it make sense for this to be its own node, rather than a field on the existing struct? How many of the fields used by `CreateIndex` will also be relevant to inverted indexes? If it does make sense for them to share the struct, maybe we could make the "kind" of index an enum rather than having a `bool` for both Unique and Inverted.
</blockquote></details>

I don't think we should touch unique to be honest, because if we add some new type of index we might support unique <new index> ... For Inverted I guess we could make an enum. However we're also not supporting things like interleaved indexes and stored columns so the options do diverge quite a bit at this point.

---

*[pkg/sql/sem/tree/create.go, line 527 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172#-KzQ6n-evoikkxp7iB4e:-KzUin4xaQtBBtcNfXYA:bdcv6kv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1d549dd9135cc4face24c5591691762b305e9ce/pkg/sql/sem/tree/create.go#L527)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

So is there any reason to have this field in the struct?
</blockquote></details>

Good point!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172)*

**Comment by justinj** [comment]
Reviewed 5 of 5 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/logictest/testdata/logic_test/inverted_index, line 15 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172#-KzQ4m__jLLOGFMznmnH:-KzV0r_ISPRxBx17lHGQ:b-aila53) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1d549dd9135cc4face24c5591691762b305e9ce/pkg/sql/logictest/testdata/logic_test/inverted_index#L15)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

It doesn't parse. I added a test.
</blockquote></details>

I think it doesn't parse because of the trailing comma, not because of the inverted index declaration.

---

*[pkg/sql/parser/sql.y, line 3356 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172#-KzQ5QqFqqZbdx1iMErO:-KzV0z38YKt8oyWEQz5o:bqfr6zq) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1d549dd9135cc4face24c5591691762b305e9ce/pkg/sql/parser/sql.y#L3356)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

I'm not sure but other recent PRs touching this code have used it like this.
</blockquote></details>

yeah agreed this definitely matches the going pattern, and is fine

---

*[pkg/sql/sem/tree/create.go, line 105 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172#-KzQ5eWysQjejKL1_NSA:-KzV1SE5TFwpclXK0qIc:bs9vld3) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1d549dd9135cc4face24c5591691762b305e9ce/pkg/sql/sem/tree/create.go#L105)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

I don't think we should touch unique to be honest, because if we add some new type of index we might support unique <new index> ... For Inverted I guess we could make an enum. However we're also not supporting things like interleaved indexes and stored columns so the options do diverge quite a bit at this point.
</blockquote></details>

Yeah sounds fine to me. I guess it's not obvious that those two should be considered the same concept.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172)*

**Comment by jordanlewis** [comment]
Reviewed 3 of 5 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/sql/logictest/testdata/logic_test/inverted_index, line 19 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172#-KzV2-H0sY2Ol3uPBbCy:-KzV2-H0sY2Ol3uPBbCz:b79ivdj) ([raw file](https://github.com/cockroachdb/cockroach/blob/baac03e7a36e83c12f80b749831390a7afc2f40b/pkg/sql/logictest/testdata/logic_test/inverted_index#L19)):*
> ```
> 
> statement error pq: inverted indexes are not supported yet
> CREATE INVERTED INDEX foo_inv2 ON t(b) USING GIN
> ```

Wait this seems wrong. USING GIN should be a modifier on an ordinary CREATE INDEX statement. It's for PostgreSQL compatibility.

---

*[pkg/sql/logictest/testdata/logic_test/inverted_index, line 22 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172#-KzV28NWXHurRzWcE5SI:-KzV28NWXHurRzWcE5SJ:b-b86f88) ([raw file](https://github.com/cockroachdb/cockroach/blob/baac03e7a36e83c12f80b749831390a7afc2f40b/pkg/sql/logictest/testdata/logic_test/inverted_index#L22)):*
> ```
> 
> 
> statement error pq: syntax error at or near \"\)\"
> ```

This test should succeed if you remove the trailing comment. Doesn't it?

---

*[pkg/sql/parser/parse_test.go, line 1306 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172#-KzV2FO0yhqAIoDreZVT:-KzV2FO0yhqAIoDreZVU:b-sr42ti) ([raw file](https://github.com/cockroachdb/cockroach/blob/baac03e7a36e83c12f80b749831390a7afc2f40b/pkg/sql/parser/parse_test.go#L1306)):*
> ```Go
> 		{
> 			`CREATE INVERTED INDEX a ON b (c) USING GIN`,
> 			`CREATE INVERTED INDEX a ON b (c)`,
> ```

What about CREATE INDEX ON ... USING gin?

---

*[pkg/sql/sem/tree/create.go, line 105 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172#-KzQ5eWysQjejKL1_NSA:-KzV2TMUbfS0Y2DLo-kI:bigapvq) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1d549dd9135cc4face24c5591691762b305e9ce/pkg/sql/sem/tree/create.go#L105)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Yeah sounds fine to me. I guess it's not obvious that those two should be considered the same concept.
</blockquote></details>

This reminds me that we should make sure to error if someone tries to CREATE UNIQUE INVERTED INDEX.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172)*

**Comment by m-schneider** [comment]
Review status: 1 of 5 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/sql/logictest/testdata/logic_test/inverted_index, line 15 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172#-KzQ4m__jLLOGFMznmnH:-KzZOSp4BF_lV32lLF3H:b-886gsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1d549dd9135cc4face24c5591691762b305e9ce/pkg/sql/logictest/testdata/logic_test/inverted_index#L15)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

I think it doesn't parse because of the trailing comma, not because of the inverted index declaration.
</blockquote></details>

Fixed

---

*[pkg/sql/logictest/testdata/logic_test/inverted_index, line 19 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172#-KzV2-H0sY2Ol3uPBbCy:-KzZOU7qTGinFNlW9g6h:bqzgl6z) ([raw file](https://github.com/cockroachdb/cockroach/blob/baac03e7a36e83c12f80b749831390a7afc2f40b/pkg/sql/logictest/testdata/logic_test/inverted_index#L19)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Wait this seems wrong. USING GIN should be a modifier on an ordinary CREATE INDEX statement. It's for PostgreSQL compatibility.
</blockquote></details>

Added that correcly

---

*[pkg/sql/logictest/testdata/logic_test/inverted_index, line 22 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172#-KzV28NWXHurRzWcE5SI:-KzZOWyCnqiHkg6onVHs:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/baac03e7a36e83c12f80b749831390a7afc2f40b/pkg/sql/logictest/testdata/logic_test/inverted_index#L22)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This test should succeed if you remove the trailing comment. Doesn't it?
</blockquote></details>

Fixed.

---

*[pkg/sql/parser/parse_test.go, line 1306 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172#-KzV2FO0yhqAIoDreZVT:-KzyIbGkio2g-fyLHxSq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/baac03e7a36e83c12f80b749831390a7afc2f40b/pkg/sql/parser/parse_test.go#L1306)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

What about CREATE INDEX ON ... USING gin?
</blockquote></details>

Done.

---

*[pkg/sql/sem/tree/create.go, line 105 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172#-KzQ5eWysQjejKL1_NSA:-KzyKnCW6kwWWgAd4xGn:bqmjwcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1d549dd9135cc4face24c5591691762b305e9ce/pkg/sql/sem/tree/create.go#L105)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This reminds me that we should make sure to error if someone tries to CREATE UNIQUE INVERTED INDEX.
</blockquote></details>

Added.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172)*

**Comment by jordanlewis** [comment]
:lgtm: mod last comment and if justin's happy!

---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/logictest/testdata/logic_test/inverted_index, line 38 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172#-L-2rOaDBDzDC_HeYIzt:-L-2rOaDBDzDC_HeYIzu:bqqyg6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/61c00e76e0570832b37ff7d0dec2f3bad4ea3121/pkg/sql/logictest/testdata/logic_test/inverted_index#L38)):*
> ```
> CREATE TABLE t1 (id1 INT PRIMARY KEY, id2 INT, id3 INT);
> 
> statement error pq: inverted indexes don't support interleaved columns
> ```

What about storing + inverted? Should that work? Maybe make a test for it on its own.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172#-:-L-2rmu5MVu8hx5vdTus:byv5lns)*

**Comment by m-schneider** [comment]
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/logictest/testdata/logic_test/inverted_index, line 38 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172#-L-2rOaDBDzDC_HeYIzt:-L-Y-ltv6uDbXXZisFq_:bqmjwcz) ([raw file](https://github.com/cockroachdb/cockroach/blob/61c00e76e0570832b37ff7d0dec2f3bad4ea3121/pkg/sql/logictest/testdata/logic_test/inverted_index#L38)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

What about storing + inverted? Should that work? Maybe make a test for it on its own.
</blockquote></details>

Added.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172)*

**Comment by justinj** [comment]
:lgtm:

---

Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172#-:-L-Y2_DW8NUB1xO6KdJ_:bnfp4nl)*

**Comment by m-schneider** [comment]
TFTR!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20172#-:-L-YHFQZbgB89vtHK8L3:b-814g8k)*

**Pull request merged**
