### PR TITLE
sql: simplify generic query plans

### LINKED ISSUE #132963: sql: invalid query plan reuse with `plan_cache_mode=auto` and `plan_cache_mode=force_generic_plan`
When `plan_cache_mode` is set to `auto` or `force_generic_plan`, query plans that should never be reused, e.g., those for DDL statements, can be cached. This can produce incorrect results in future invocations of the query.

Here's an example:

```sql
CREATE TABLE a (a INT PRIMARY KEY);

SET plan_cache_mode = 'auto';

PREPARE p AS SELECT create_statement FROM [SHOW CREATE TABLE a];

EXECUTE p;
--               create_statement
-- ---------------------------------------------
--   CREATE TABLE public.a (
--       a INT8 NOT NULL,
--       CONSTRAINT a_pkey PRIMARY KEY (a ASC)
--   )
-- (1 row)

ALTER TABLE a RENAME TO b;

-- This succeeds, but it should error with:
--
--   ERROR: relation "a" does not exist
--   SQLSTATE: 42P01
EXECUTE p;
--               create_statement
-- ---------------------------------------------
--   CREATE TABLE public.b (
--       a INT8 NOT NULL,
--       CONSTRAINT a_pkey PRIMARY KEY (a ASC)
--   )
-- (1 row)
```

Jira issue: CRDB-43364

### PR DESCRIPTION
**Pull request by mgartner**
#### sql: do not cache non-reusable plans

Fixes #132963

Release note (bug fix): A bug has been fixed that caused non-reusable
query plans, e.g., plans for DDL and `SHOW ...` statements, to be cached
and reused in future executions, possibly causing stale results to be
returned. This bug only occurred when `plan_cache_mode` was set to
`auto` or `force_generic_plan`, both of which are not currently the
default settings.

#### sql: remove legacy planning code path

An optimization code path from before the introduction of generic query
plans has been removed. This code path remained in the codebase to
de-risk the generic query plans backports. It is not needed in future
versions.

Release note: None

#### sql: remove unused context parameter in `reuseMemo`

Release note: None

#### sql: simplify generic query plans

All fully-optimized memos that can be reused without re-optimization are
now stored in `PreparedStatement.GenericMemo`. Prior to this commit,
some fully-optimized memos were stored in `PreparedStatement.BaseMemo`.

Release note: None

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
The changes :lgtm:, just one question about the existing logic.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131791#-:-O8FN7vn182L0FMJAzJv:bpaqqee)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/plan_opt.go` line 657 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131791#-O8FLj7H3L02vr2LaNXQ:-O8FLj7H3L02vr2LaNXR:b5t4y28) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6e732a141a693db888d8f6225d55557dbf5fb98/pkg/sql/plan_opt.go#L657)):*
> ```Go
> 		// could drastically change the cost of generic and custom plans, so
> 		// we should re-consider which to use.
> 		prep.Costs.ClearGeneric()
> ```

I know it wasn't added here, but should we also clear the custom costs in this case? Could we end up comparing a generic plan against the costs of stale custom plans? Maybe similar question for the other case, when we find a stale custom plan.

**Comment by mgartner** [comment]
*[`pkg/sql/plan_opt.go` line 657 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131791#-O8FLj7H3L02vr2LaNXQ:-O8cehZQ13oKfc-cwna-:b-pbhcpf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e6e732a141a693db888d8f6225d55557dbf5fb98/pkg/sql/plan_opt.go#L657)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

I know it wasn't added here, but should we also clear the custom costs in this case? Could we end up comparing a generic plan against the costs of stale custom plans? Maybe similar question for the other case, when we find a stale custom plan.
</blockquote></details>

Ya, good point. This is similar to #127826. I'll think some more about this.

**Comment by mgartner** [comment]
@DrewKimball Can you please take another look? The first commit is new and fixes a bug that was lurking here.

**Review by DrewKimball — APPROVED** [review]
:lgtm: Nice find with that bug fix.

> Reviewed 3 of 3 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131791#-:-O9WPDeO1Tguxv9s1Fc4:b-tff05l)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by mgartner** [comment]
TFTR!

bors r+

**Comment by mgartner** [comment]
FYI I create #132968 to track the cost issue described above.

**Pull request merged**
