### PR TITLE
keyvisualizer: pre-aggregate ranges

### LINKED ISSUE #96740: keyvisualizer: Pre-aggregate boundaries propagated to the collectors
Currently in the `SpanStatsConsumer`, the boundaries sent to the collector are taken from the system tenant's ranges from `[Min, Max)`.  This is implemented [here](https://github.com/cockroachdb/cockroach/blob/master/pkg/keyvisualizer/spanstatsconsumer/span_stats_consumer.go#L92).

More than 10,000 boundaries should be pre-aggregated so the cost of propagating and storing them stays negligible.

A possible implementation could be as follows:
As an example, If there's 100,000 ranges, every 10 ranges would be combined into one.

```
[a, b), [b,c), ... [i, j)  combines to [a, j)
[k, l), [m, n), ... [s, t) combines to [k, t)

etc
```

So the boundaries communicated to the collector would be `[a, j), [k, t), ... etc`

Jira issue: CRDB-24304

### PR DESCRIPTION
**Pull request by zachlite**
Previously, there was no bound on the number of ranges that could be propagated to the collectors. After collection, data was downsampled using a simple heurstic to decide if a bucket was worth keeping or if it should be aggregated with its neighbor.

In this commit, I've introduced a function, `maybeAggregateBoundaries`, to prevent more than `keyvisualizer.max_buckets` from being propagated to collectors. This pre-aggregation takes the place of the post-collection downsampling. For the first stable release of the key visualizer, I am intentionally sacrificing dynamic resolution and prioritizing boundary stability instead. This trade-off means that the key visualizer will demand less network, memory, and storage resources from the cluster while operating.

Additionally, this PR drops the sample retention time from 14 days to 7 days, and ensures that `keyvisualizer.max_buckets` is bounded between [1, 1024].

Resolves: #96740
Epic: None
Release note: None

### CODE REVIEW

**Review by Santamaura — COMMENTED** [review]
Some small comments

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98707#-:-NQawZeK8y3PZ0jYPSl7:by8h178)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @zachlite)

___
*[`pkg/keyvisualizer/spanstatsconsumer/span_stats_consumer.go` line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98707#-NQaug0w99TGAygZwGWh:-NQaug0x2J019oXnKw95:b-osulo6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0d612b4a37c476df42acfde8670709af615c34e/pkg/keyvisualizer/spanstatsconsumer/span_stats_consumer.go#L91)):*
> ```Go
> 	}
> 
> 	// combineFactor is factor that boundaries length is reduced by. For example,
> ```

nit: is a factor
___
*[`pkg/keyvisualizer/spanstatsconsumer/span_stats_consumer.go` line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98707#-NQavrdwEIK-ule3ykZ7:-NQavrdwEIK-ule3ykZ8:bobwk7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0d612b4a37c476df42acfde8670709af615c34e/pkg/keyvisualizer/spanstatsconsumer/span_stats_consumer.go#L100)):*
> ```Go
> 	// Iterate through boundaries, incrementing by combineFactor.
> 	for i := 0; i < combinedLength; i++ {
> 		startSpan := boundaries[i*combineFactor]
> ```

There is no situation where we will end up with an index out of bound error right?
___
*[`pkg/ui/workspaces/db-console/src/views/keyVisualizer/index.tsx` line 170 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98707#-NQawK2C6THyZSC7sdcs:-NQawK2C6THyZSC7sdct:bl8z9we) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0d612b4a37c476df42acfde8670709af615c34e/pkg/ui/workspaces/db-console/src/views/keyVisualizer/index.tsx#L170)):*
> ```XML
>     return (
>       <div style={{ position: "relative" }}>
>         <KeyVisualizerTimeWindow />
> ```

If retention period is now only 7 days do we want to remove the two week option?

**Review by zachlite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98707)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Santamaura)

___
*[`pkg/keyvisualizer/spanstatsconsumer/span_stats_consumer.go` line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98707#-NQaug0w99TGAygZwGWh:-NQb9D235mKuP7asxDig:b-qssebl) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0d612b4a37c476df42acfde8670709af615c34e/pkg/keyvisualizer/spanstatsconsumer/span_stats_consumer.go#L91)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

nit: is a factor
</blockquote></details>

fixed.
___
*[`pkg/keyvisualizer/spanstatsconsumer/span_stats_consumer.go` line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98707#-NQavrdwEIK-ule3ykZ7:-NQb5ZsC8tpnwJ663F-U:bu6lr0g) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0d612b4a37c476df42acfde8670709af615c34e/pkg/keyvisualizer/spanstatsconsumer/span_stats_consumer.go#L100)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

There is no situation where we will end up with an index out of bound error right?
</blockquote></details>

Correct, but I'll put a check for good measure.
___
*[`pkg/ui/workspaces/db-console/src/views/keyVisualizer/index.tsx` line 170 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/98707#-NQawK2C6THyZSC7sdcs:-NQb9A-498Kby5sKYhY7:bxw8nej) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0d612b4a37c476df42acfde8670709af615c34e/pkg/ui/workspaces/db-console/src/views/keyVisualizer/index.tsx#L170)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

If retention period is now only 7 days do we want to remove the two week option?
</blockquote></details>

No we don't. thanks.

**Review by zachlite — COMMENTED** [review]
addressed!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98707#-:-NQbA8J05ROsyjOFge4G:b-1db39p)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Santamaura)

**Review by Santamaura — APPROVED** [review]
> Reviewed 3 of 4 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/98707)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @zachlite)

**Pull request merged**
