### PR TITLE
vendor: Bump pebble to 12ffb4e9273f, propagate FD in encryptedFile

### PR DESCRIPTION
**Pull request by itsbilal**
Changes pulled in:
```
12ffb4e9273fd532fd1a2fe5807a6ba3a5335a0d *: Remove TODO in sampleRead, remove unused var
4419cc6fcc3f5438d836452f9ad07cca0be33f38 compaction: Don't call maybeThrottle if nilPacer passed in.
6c981576bc1e97b46c3cf437570c8c3d5d5ed9a4 docs: add an option to toggle per-chart scaling
6110b03a8a852e0d2343dc090c568e48766e4937 db: change random generator for read sampling
dbe38cf9cbdc79a71cc6a54fc6d0680842006b0f docs: show insert-only workload in nightly benchmarks
a1a66c28682d542d9b7c7cfdef8b854adb0bc6ec db: fix docs for WriteOptions.Sync
825649d60d9fa6dc072049f3ec61ae3e22fc0d49 vfs: fix error return by MemFS.Remove for non-empty dir
d844cafbba5a2b207b95fdc4a5761ad9848e1769 vfs: Add fdFileWrapper to re-implement Fd() method on file wrappers
```

The FD needs to be propagated through file wrappers for some
optimizations (eg. WAL preallocation, readahead) to work correctly.
Pebble's own file wrappers already call vfs.WithFd to take
this into account, so the same needs to be done for
wrappers implemented in Cockroach. This change does that for
`encryptedFile`.

### CODE REVIEW

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59774#-:-MSdrDom8aBP7Ym44563:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal, @jbowens, and @miretskiy)

___
*[go.mod, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59774#-MSdqw6S-w9mCym0jMT9:-MSdqw6TCOt_oMDo2mNk:b-9p5wk3) ([raw file](https://github.com/cockroachdb/cockroach/blob/614323229514f307e98029c1b0b1b8740889e2af/go.mod#L151)):*
> ```XML
> 	go.etcd.io/etcd/raft/v3 v3.0.0-20201109164711-01844fd28560
> 	golang.org/x/crypto v0.0.0-20201221181555-eec23a3978ad
> 	golang.org/x/exp v0.0.0-20210201131500-d352d2db2ceb
> ```

are these non pebble changes needed by pebble, or could be reverted?

**Review by itsbilal — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59774#-:-MSdsglz837CDe2eneJz:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens, @miretskiy, and @sumeerbhola)

___
*[go.mod, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59774#-MSdqw6S-w9mCym0jMT9:-MSdshpx0muhSNlprn7t:b-eid6of) ([raw file](https://github.com/cockroachdb/cockroach/blob/614323229514f307e98029c1b0b1b8740889e2af/go.mod#L151)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

are these non pebble changes needed by pebble, or could be reverted?
</blockquote></details>

They're unrelated, but we seem to keep them around most of the time (unless it breaks tests) as it's a bump that's going to happen sooner or later.

**Comment by itsbilal** [comment]
bors r=sumeerbhola

**Comment by jbowens** [comment]
Should the `encryptedFile` `Fd()` change be backported to 20.2? IIRC, the original `Fd`-obscuring issue was not present in 20.2, but it seems like for encrypted file systems it would be?

**Comment by itsbilal** [comment]
@jbowens That's a good question. I think `syncingFile` is the other one that'd obscure it too, so I think it'd be pretty worth backporting this to 20.2.

**Pull request merged**
