### PR TITLE
release-22.2: sql: output RU estimate for EXPLAIN ANALYZE on tenants

### PR DESCRIPTION
**Pull request by DrewKimball**
Backport:
  * 1/1 commits from "sql: output RU estimate for EXPLAIN ANALYZE on tenants" (#89256)
  * 1/1 commits from "sql: add cluster setting to disable RU estimation" (#92968)

Please see individual PRs for details.

/cc @cockroachdb/release

---

Release justification: low-risk, high-benefit change to existing functionality

### CODE REVIEW

**Comment by DrewKimball** [comment]
I've left the cluster setting as default-on - should it be off by default for the backport?

Also, while the backport was mostly clean, I had to make a few changes to `planNodeToRowSource` vs the original PR since there have been changes to context-passing and span collection for that processor after 22.2. Instead of using `execstats.ShouldCollectStats` when deciding whether to set the `ExecStatsForTrace` callback, we only check `flowCtx.CollectStats`, and make the same check when deciding whether to record a span. @yuzefovich does this seem safe to you?

**Review by rytaft — APPROVED** [review]
:lgtm: (although would be good to get sign off from @yuzefovich regarding your question above)

I think it's ok to leave the setting defaulted to on for backporting to 22.2. I think we'll get this PR into 22.2.1, and presumably serverless clusters will start on 22.2.1 or later. If we want to backport to 22.1 it should probably be defaulted to off.

> Reviewed 37 of 37 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93179#-:-NIh0Alh754WOmP5-BDE:b-su2tyw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @yuzefovich)

**Comment by andy-kimball** [comment]
We don't need to backport this to 22.1.

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 37 of 37 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93179)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @DrewKimball)

___
*[`pkg/sql/plan_node_to_row_source.go` line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93179#-NIipdeq2AQLLdlcM5Rn:-NIipdeq2AQLLdlcM5Ro:b-pkosjk) ([raw file](https://github.com/cockroachdb/cockroach/blob/682fe34e92da51407c137bcfdf32625338d97e38/pkg/sql/plan_node_to_row_source.go#L126)):*
> ```Go
> 	// We can't use execstats.ShouldCollectStats here because the context isn't
> 	// passed to InitWithOutput.
> 	if flowCtx.CollectStats {
> ```

This is safe, but we should use `execstats.ShouldCollectStats(flowCtx.EvalCtx.Ctx(), flowCtx.CollectStats)` for consistency with other places on 22.2 branch.
___
*[`pkg/sql/plan_node_to_row_source.go` line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93179#-NIiqwVj70Irqi8r-gNt:-NIiqwVj70Irqi8r-gNu:bkf5dp6) ([raw file](https://github.com/cockroachdb/cockroach/blob/682fe34e92da51407c137bcfdf32625338d97e38/pkg/sql/plan_node_to_row_source.go#L163)):*
> ```Go
> func (p *planNodeToRowSource) Start(ctx context.Context) {
> 	if p.FlowCtx.CollectStats {
> 		ctx = p.StartInternal(ctx, nodeName(p.node))
> ```

I think we should just always call `StartInternal` here (we did this in 7291e4d860275078703d57d045efcb3efba47792 on master). The only thing I would check is whether there are any regressions in `BenchmarkSQL/Insert\$\$` in `pkg/bench`, but I don't expect them to be there.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93179)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @yuzefovich)

___
*[`pkg/sql/plan_node_to_row_source.go` line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93179#-NIipdeq2AQLLdlcM5Rn:-NIitabI8WA_PSlfygJY:bc0lt1d) ([raw file](https://github.com/cockroachdb/cockroach/blob/682fe34e92da51407c137bcfdf32625338d97e38/pkg/sql/plan_node_to_row_source.go#L126)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

This is safe, but we should use `execstats.ShouldCollectStats(flowCtx.EvalCtx.Ctx(), flowCtx.CollectStats)` for consistency with other places on 22.2 branch.
</blockquote></details>

In the tests I did, `flowCtx.EvalCtx.Ctx()` didn't necessarily have a span set even when I added the `StartInternal` call to `Start` - I guess maybe the difference is because there are more `StartInternal` calls on master now? Maybe this check should go in a different place to ensure the span is set?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93179)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @DrewKimball)

___
*[`pkg/sql/plan_node_to_row_source.go` line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93179#-NIipdeq2AQLLdlcM5Rn:-NIj3uFyAtlGUIt7zhS6:b-hsf8ms) ([raw file](https://github.com/cockroachdb/cockroach/blob/682fe34e92da51407c137bcfdf32625338d97e38/pkg/sql/plan_node_to_row_source.go#L126)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

In the tests I did, `flowCtx.EvalCtx.Ctx()` didn't necessarily have a span set even when I added the `StartInternal` call to `Start` - I guess maybe the difference is because there are more `StartInternal` calls on master now? Maybe this check should go in a different place to ensure the span is set?
</blockquote></details>

Hm, this is surprising to me - what was the reproduction that you ran into this with?

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93179)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @yuzefovich)

___
*[`pkg/sql/plan_node_to_row_source.go` line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93179#-NIipdeq2AQLLdlcM5Rn:-NIjE4AUBG7zh3DNjFHU:b-hoftvo) ([raw file](https://github.com/cockroachdb/cockroach/blob/682fe34e92da51407c137bcfdf32625338d97e38/pkg/sql/plan_node_to_row_source.go#L126)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Hm, this is surprising to me - what was the reproduction that you ran into this with?
</blockquote></details>

It wasn't anything special - I just did an insert on a table like this:
```
CREATE TABLE xy (x INT, y INT);
EXPLAIN ANALYZE INSERT INTO xy (SELECT t, t FROM generate_series(1, 10000) g(t));
```

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93179)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @DrewKimball)

___
*[`pkg/sql/plan_node_to_row_source.go` line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93179#-NIipdeq2AQLLdlcM5Rn:-NIjIx-iCEkbQWwm4zvO:b-uineqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/682fe34e92da51407c137bcfdf32625338d97e38/pkg/sql/plan_node_to_row_source.go#L126)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

It wasn't anything special - I just did an insert on a table like this:
```
CREATE TABLE xy (x INT, y INT);
EXPLAIN ANALYZE INSERT INTO xy (SELECT t, t FROM generate_series(1, 10000) g(t));
```
</blockquote></details>

Hm, I just tried these two queries in `demo --multitenant=true` with cockroach binary built on this branch plus
```
diff --git a/pkg/sql/plan_node_to_row_source.go b/pkg/sql/plan_node_to_row_source.go
index 18401059a5..c7789a88d3 100644
--- a/pkg/sql/plan_node_to_row_source.go
+++ b/pkg/sql/plan_node_to_row_source.go
@@ -123,7 +123,7 @@ func (p *planNodeToRowSource) InitWithOutput(
        }
        // We can't use execstats.ShouldCollectStats here because the context isn't
        // passed to InitWithOutput.
-       if flowCtx.CollectStats {
+       if execstats.ShouldCollectStats(flowCtx.EvalCtx.Ctx(), flowCtx.CollectStats) {
                p.ExecStatsForTrace = p.execStatsForTrace
        }
        return nil
```
and it worked
```
root@127.0.0.1:26257/defaultdb> EXPLAIN ANALYZE INSERT INTO xy (SELECT t, t FROM generate_series(1, 10000) g(t));
                 info
--------------------------------------
  planning time: 171µs
  execution time: 325ms
  distribution: local
  vectorized: true
  maximum memory usage: 70 KiB
  network usage: 0 B (0 messages)
  estimated RUs consumed: 10,291
...
```

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93179)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @DrewKimball)

___
*[`pkg/sql/plan_node_to_row_source.go` line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93179#-NIipdeq2AQLLdlcM5Rn:-NIjJWKM4D5kzcQK-Bfl:b-4xx73g) ([raw file](https://github.com/cockroachdb/cockroach/blob/682fe34e92da51407c137bcfdf32625338d97e38/pkg/sql/plan_node_to_row_source.go#L126)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Hm, I just tried these two queries in `demo --multitenant=true` with cockroach binary built on this branch plus
```
diff --git a/pkg/sql/plan_node_to_row_source.go b/pkg/sql/plan_node_to_row_source.go
index 18401059a5..c7789a88d3 100644
--- a/pkg/sql/plan_node_to_row_source.go
+++ b/pkg/sql/plan_node_to_row_source.go
@@ -123,7 +123,7 @@ func (p *planNodeToRowSource) InitWithOutput(
        }
        // We can't use execstats.ShouldCollectStats here because the context isn't
        // passed to InitWithOutput.
-       if flowCtx.CollectStats {
+       if execstats.ShouldCollectStats(flowCtx.EvalCtx.Ctx(), flowCtx.CollectStats) {
                p.ExecStatsForTrace = p.execStatsForTrace
        }
        return nil
```
and it worked
```
root@127.0.0.1:26257/defaultdb> EXPLAIN ANALYZE INSERT INTO xy (SELECT t, t FROM generate_series(1, 10000) g(t));
                 info
--------------------------------------
  planning time: 171µs
  execution time: 325ms
  distribution: local
  vectorized: true
  maximum memory usage: 70 KiB
  network usage: 0 B (0 messages)
  estimated RUs consumed: 10,291
...
```
</blockquote></details>

Or was the problem that RUs estimation was wrong?

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93179)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @yuzefovich)

___
*[`pkg/sql/plan_node_to_row_source.go` line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93179#-NIipdeq2AQLLdlcM5Rn:-NIjKNZP02R9lVbJA-WM:b4mx7ni) ([raw file](https://github.com/cockroachdb/cockroach/blob/682fe34e92da51407c137bcfdf32625338d97e38/pkg/sql/plan_node_to_row_source.go#L126)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Or was the problem that RUs estimation was wrong?
</blockquote></details>

Hm, maybe I tested that before changing to use `StartInternal` or something. Reverted to use `ShouldCollectStats`. Done.
___
*[`pkg/sql/plan_node_to_row_source.go` line 163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93179#-NIiqwVj70Irqi8r-gNt:-NIjLYCnDBAVQbxZCdo3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/682fe34e92da51407c137bcfdf32625338d97e38/pkg/sql/plan_node_to_row_source.go#L163)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I think we should just always call `StartInternal` here (we did this in 7291e4d860275078703d57d045efcb3efba47792 on master). The only thing I would check is whether there are any regressions in `BenchmarkSQL/Insert\$\$` in `pkg/bench`, but I don't expect them to be there.
</blockquote></details>

Done.

**Review by yuzefovich — APPROVED** [review]
> Reviewed 10 of 10 files at r3, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93179)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball)

**Comment by DrewKimball** [comment]
TFTRs!

**Review by yuzefovich — APPROVED** [review]
LGTM, although it probably would have been cleaner to backport the whole 7291e4d860275078703d57d045efcb3efba47792 without modifying the commit for RU estimation. I'm ok with merging either way.

> Reviewed 18 of 18 files at r5, 9 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93179#-:-NIt47R2Aix8Ry3aO38t:b-y3xnp8)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @DrewKimball)

___
*[`pkg/sql/opt/exec/execbuilder/testdata/select` line 24 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93179#-NIt3wL86qutDSeckmp-:-NIt3wL86qutDSeckmp0:b-yiiokj) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe7b8557269658f6a0a86ab3c133e1ff840d6a72/pkg/sql/opt/exec/execbuilder/testdata/select#L24)):*
> ```
> query ITT
> SELECT
>   span, split_part(regexp_replace(message, 'pos:[0-9]*', 'pos:?'), E'\n', 1), operation
> ```

Why did we need to modify this? Looks like 7291e4d860275078703d57d045efcb3efba47792 didn't do it.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93179)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @yuzefovich)

___
*[`pkg/sql/opt/exec/execbuilder/testdata/select` line 24 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93179#-NIt3wL86qutDSeckmp-:-NIt8VpCEifRYuC8Decp:b-urotpy) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe7b8557269658f6a0a86ab3c133e1ff840d6a72/pkg/sql/opt/exec/execbuilder/testdata/select#L24)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Why did we need to modify this? Looks like 7291e4d860275078703d57d045efcb3efba47792 didn't do it.
</blockquote></details>

The `SPAN START: values` lines started including the flow ID, which made the test non-deterministic... it's not clear to me what's changed since 22.2 to cause this

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93179)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball and @DrewKimball)

___
*[`pkg/sql/opt/exec/execbuilder/testdata/select` line 24 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/93179#-NIt3wL86qutDSeckmp-:-NItIGI_EyYN8Y0pZElp:b-xvlhmi) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe7b8557269658f6a0a86ab3c133e1ff840d6a72/pkg/sql/opt/exec/execbuilder/testdata/select#L24)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

The `SPAN START: values` lines started including the flow ID, which made the test non-deterministic... it's not clear to me what's changed since 22.2 to cause this
</blockquote></details>

Those were removed on master in ae24dd9d2360371df394af9db1e51f780a485235. I think we should just backport all three commits from #87317, and then just keep the original two commits here. Will do that now.

**Review by yuzefovich — APPROVED** [review]
> Reviewed 21 of 22 files at r7, 16 of 16 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93179)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andy-kimball)

**Comment by DrewKimball** [comment]
TFTRs!

**Pull request merged**
