### PR TITLE
kvserver: perform initial upreplication of non-voters synchronously

### LINKED ISSUE #63199: kvserver: merging of ranges with non-voters can be extremely disruptive to foreground traffic
Non-voting replicas are not upreplicated through a [synchronous snapshot the way learners](https://github.com/cockroachdb/cockroach/blob/34904ed0c1f7f52bc9394597a6e2a25bcedd7636/pkg/kv/kvserver/replica_command.go#L1658) are. [We queue up new non-voters into the raft snapshot queue](https://github.com/cockroachdb/cockroach/blob/34904ed0c1f7f52bc9394597a6e2a25bcedd7636/pkg/kv/kvserver/replica_command.go#L1075-L1082) and rely on it to initialize newly added / rebalanced non-voters.

A range merge [will try to collocate replica sets](https://github.com/cockroachdb/cockroach/blob/d7a7a49a6ca48758fb979c98a2aa04e358effab2/pkg/kv/kvserver/merge_queue.go#L323) for the LHS and RHS, which may require rebalancing one or more non-voting replicas from the right hand side range to stores that have replicas for the left hand side range. An `AdminMerge` will then send a `SubsumeRequest` to the RHS and wait until all replicas have [caught up to the LAI of the subsume](https://github.com/cockroachdb/cockroach/blob/34904ed0c1f7f52bc9394597a6e2a25bcedd7636/pkg/kv/kvserver/replica_command.go#L726-L731). 

At this point, non-voting replicas that were _just_ rebalanced for the sake of the merge are very likely to still be waiting for, or be in the process of receiving, their initial snapshot from the raft snapshot queue (once the snapshot queue starts sending these newly rebalanced non-voters their initial snapshots, it will take roughly ~64 seconds _per replica_ if we assume default settings for range size and snapshot rates)

So, [the `AdminMerge` will hit this 5-second timeout](https://github.com/cockroachdb/cockroach/blob/34904ed0c1f7f52bc9394597a6e2a25bcedd7636/pkg/kv/kvserver/replica_command.go#L792) and the merge will fail. This will prompt the merge queue to [log an error and try again after about 10 minutes](https://github.com/cockroachdb/cockroach/blob/d7a7a49a6ca48758fb979c98a2aa04e358effab2/pkg/kv/kvserver/merge_queue.go#L353-L355). Now, notice that we’re waiting for those 5 seconds _after_ we’ve sent the subsume request. This means that RHS will not serve any traffic for those 5 seconds.

The expected high-level consequence of all this interaction is that all foreground traffic on a range that has non-voting replicas could experience seemingly random 5 second blips, where all requests to such a range are blocked for those 5 seconds.

### PR DESCRIPTION
**Pull request by aayushshah15**
Resolves https://github.com/cockroachdb/cockroach/issues/63199

Before this commit, we relied on the raft snapshot queue to
asynchronously perform the initial upreplication of non-voting replicas.
This meant that by the time `AdminChangeReplicas` (and consequently,
`AdminRelocateRange`) returned to its client, non-voters were not
guaranteed to have been initialized. This was a deliberate decision and
was, thus far, believed to be copacetic. However, this decision subtly
made range merges (of ranges that have any number of non-voters)
extremely unlikely to suceed, while causing severe disruption on
foreground traffic on the right hand side of a merge. This was because
the `mergeQueue` will first call `AdminRelocateRange` on the right hand
side range in order to collocate its replicas with the replicas of the
left hand side range.  If the `mergeQueue` happened to relocate any
non-voting replicas, they were likely to still be waiting for their
initial snapshot by the time the `AdminMerge` attempted to subsume the
RHS. Essentially, this meant that we were subsuming the RHS of a merge
while some of its replicas weren't even initialized. This would cause
the merge to fail and, in the interim, block all traffic over the RHS
range for a 5 second window.

This commit fixes the unfortunate sequence of events described above by
making the behavior of `AdminChangeReplicas` more symmetric for voting
and non-voting replicas. Now, if `AdminChangeReplicas` successfully
returns, its client can safely assume that all new replicas have at
least been upreplicated via an initial snapshot.

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
Nice job on this. It looks like an overall simplification.

> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63215#-:-MXiMW578m8ukqoenfXw:bewvzqt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @andreimatei)

___
*[pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go, line 581 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63215#-MXiHnAtAUV3NCYy9CWy:-MXiHnAtAUV3NCYy9CWz:bmi8ppe) ([raw file](https://github.com/cockroachdb/cockroach/blob/651184b3cfbd7c6d336bb49e7152e3d48ea06416/pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go#L581)):*
> ```Go
> 	n1.Exec(t, `ALTER TABLE test EXPERIMENTAL_RELOCATE NON_VOTERS VALUES (ARRAY[3], 1)`)
> 
> 	// Wait until the new non-voter is upreplicated to n3.
> ```

:100: 
___
*[pkg/kv/kvserver/client_merge_test.go, line 4517 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63215#-MXiMONv-fMhDbT03clN:-MXiMONv-fMhDbT03clO:b-smkeqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/419b98577f992b9b6531640eefc9bb32031b709e/pkg/kv/kvserver/client_merge_test.go#L4517)):*
> ```Go
> 	// We're controlling merge queue operation via
> 	// `store.SetMergeQueueActive`, so enable the cluster setting here.
> 	_, err := tc.ServerConn(0).Exec(`SET CLUSTER SETTING kv.range_merge.queue_enabled=true`)
> ```

Do we need this? Doesn't this default to true?
___
*[pkg/kv/kvserver/merge_queue.go, line 358 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63215#-MXiIGOv--1UgYYu7p1V:-MXiIGOv--1UgYYu7p1W:b-ib0l9p) ([raw file](https://github.com/cockroachdb/cockroach/blob/419b98577f992b9b6531640eefc9bb32031b709e/pkg/kv/kvserver/merge_queue.go#L358)):*
> ```Go
> 		// TODO(aayush): Merges are indeed stable now, we can be smarter here about
> 		// which errors should be marked as purgatory-worthy.
> 		log.Warningf(ctx, "%v", err)
> ```

Don't we already log on non-benign queue errors in `baseQueue.finishProcessingReplica`?
___
*[pkg/kv/kvserver/raft_snapshot_queue.go, line 113 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63215#-MXiMdOW7lTfQrKFx_6U:-MXiMdOW7lTfQrKFx_6V:b6k0n6m) ([raw file](https://github.com/cockroachdb/cockroach/blob/419b98577f992b9b6531640eefc9bb32031b709e/pkg/kv/kvserver/raft_snapshot_queue.go#L113)):*
> ```Go
> 	snapType := SnapshotRequest_VIA_SNAPSHOT_QUEUE
> 
> 	if typ := repDesc.GetType(); typ == roachpb.LEARNER || typ == roachpb.NON_VOTER {
> ```

Can you think of anything problematic that could come out of this new ability for the snapshot queue to skip NON_VOTER snapshots? I want to make sure we aren't accidentally introducing any new starvation conditions which could prevent an initialized NON_VOTER that has fallen behind and needs a snapshot from receiving one.
___
*[pkg/kv/kvserver/replica_command.go, line 1047 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63215#-MXiKros2hU0OtYfyTrl:-MXiKros2hU0OtYfyTrm:bg9iq4) ([raw file](https://github.com/cockroachdb/cockroach/blob/419b98577f992b9b6531640eefc9bb32031b709e/pkg/kv/kvserver/replica_command.go#L1047)):*
> ```Go
> 			reason,
> 			details,
> 			targets.voterAdditions,
> ```

`adds`?
___
*[pkg/kv/kvserver/replica_command.go, line 1061 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63215#-MXiKYKz0LZk4fAjgJp3:-MXiKYKz0LZk4fAjgJp4:boeh75l) ([raw file](https://github.com/cockroachdb/cockroach/blob/419b98577f992b9b6531640eefc9bb32031b709e/pkg/kv/kvserver/replica_command.go#L1061)):*
> ```Go
> 			}
> 			for _, target := range adds {
> 				r.tryRollBackLearnerReplica(ctx, r.Desc(), target, reason, details)
> ```

We discussed over a call that we're going to do this for NON_VOTERS as well, so we can pull this logic back inside `addAndInitializeRaftLearners`.
___
*[pkg/kv/kvserver/replica_command.go, line 1112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63215#-MXiKtpO8FG5rh-3F1Sl:-MXiKtpO8FG5rh-3F1Sm:bg9iq4) ([raw file](https://github.com/cockroachdb/cockroach/blob/419b98577f992b9b6531640eefc9bb32031b709e/pkg/kv/kvserver/replica_command.go#L1112)):*
> ```Go
> 			reason,
> 			details,
> 			targets.nonVoterAdditions,
> ```

`adds`?
___
*[pkg/kv/kvserver/replica_command.go, line 1544 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63215#-MXiNMru5SF_4FoBy1YM:-MXiNMru5SF_4FoBy1YN:bz0q79f) ([raw file](https://github.com/cockroachdb/cockroach/blob/419b98577f992b9b6531640eefc9bb32031b709e/pkg/kv/kvserver/replica_command.go#L1544)):*
> ```Go
> // addAndInitializeRaftLearners adds etcd learners (LEARNERs or NON_VOTERs) to
> // the given replication targets and synchronously sends them an initial
> // snapshot to upreplicate.
> ```

Could you mention what a caller can expect when this method returns? Something about how the targets will all be initialized.

**Review by nvb — COMMENTED** [review]
The latest patch looks good, though I'm not sure it addressed all of the comments.

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63215#-:-MXmi9YH3F07_k3kzTt7:b-4c8ty7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @andreimatei)

**Comment by aayushshah15** [comment]
I was going to write a test for this comment of yours before updating the PR:
> I want to make sure we aren't accidentally introducing any new starvation conditions which could prevent an initialized NON_VOTER that has fallen behind and needs a snapshot from receiving one.

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63215)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/kvserver/client_merge_test.go, line 4517 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63215#-MXiMONv-fMhDbT03clN:-MXo21xd6_Slkfv3E55B:b-8kt7v4) ([raw file](https://github.com/cockroachdb/cockroach/blob/419b98577f992b9b6531640eefc9bb32031b709e/pkg/kv/kvserver/client_merge_test.go#L4517)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we need this? Doesn't this default to true?
</blockquote></details>

For some reason, I thought that `ReplicationManual` disables the merge `queue_enabled` cluster setting. Removed.
___
*[pkg/kv/kvserver/merge_queue.go, line 358 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63215#-MXiIGOv--1UgYYu7p1V:-MXo1H6O4i9PTt1In-jD:bftds33) ([raw file](https://github.com/cockroachdb/cockroach/blob/419b98577f992b9b6531640eefc9bb32031b709e/pkg/kv/kvserver/merge_queue.go#L358)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Don't we already log on non-benign queue errors in `baseQueue.finishProcessingReplica`?
</blockquote></details>

We do in general, but not for purgatory errors. I'm not sure why, though, since it seems like in most cases we do want these errors in the logs. See: https://github.com/cockroachdb/cockroach/blob/ea9074ba76a842a928b18c403ec78ec362fcb4bd/pkg/kv/kvserver/queue.go#L1084-L1094
___
*[pkg/kv/kvserver/raft_snapshot_queue.go, line 113 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63215#-MXiMdOW7lTfQrKFx_6U:-MXo25JU4rOlGDMOiw6A:b7pw0k) ([raw file](https://github.com/cockroachdb/cockroach/blob/419b98577f992b9b6531640eefc9bb32031b709e/pkg/kv/kvserver/raft_snapshot_queue.go#L113)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can you think of anything problematic that could come out of this new ability for the snapshot queue to skip NON_VOTER snapshots? I want to make sure we aren't accidentally introducing any new starvation conditions which could prevent an initialized NON_VOTER that has fallen behind and needs a snapshot from receiving one.
</blockquote></details>

Added a test for this scenario. LMK if you dislike.
___
*[pkg/kv/kvserver/replica_command.go, line 1047 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63215#-MXiKros2hU0OtYfyTrl:-MXjkLpa1zj7QJ9G8xFR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/419b98577f992b9b6531640eefc9bb32031b709e/pkg/kv/kvserver/replica_command.go#L1047)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`adds`?
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replica_command.go, line 1061 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63215#-MXiKYKz0LZk4fAjgJp3:-MXjkKSg7rNbF1o5p80n:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/419b98577f992b9b6531640eefc9bb32031b709e/pkg/kv/kvserver/replica_command.go#L1061)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We discussed over a call that we're going to do this for NON_VOTERS as well, so we can pull this logic back inside `addAndInitializeRaftLearners`.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replica_command.go, line 1112 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63215#-MXiKtpO8FG5rh-3F1Sl:-MXjkMYADnXpup_rd5KC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/419b98577f992b9b6531640eefc9bb32031b709e/pkg/kv/kvserver/replica_command.go#L1112)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`adds`?
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replica_command.go, line 1544 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63215#-MXiNMru5SF_4FoBy1YM:-MXjkNi68EFmXAPjfGt9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/419b98577f992b9b6531640eefc9bb32031b709e/pkg/kv/kvserver/replica_command.go#L1544)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Could you mention what a caller can expect when this method returns? Something about how the targets will all be initialized.
</blockquote></details>

Done.

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63215)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/kvserver/client_merge_test.go, line 4517 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63215#-MXiMONv-fMhDbT03clN:-MXoF3t-1ArS_BMthx8e:bcxay0b) ([raw file](https://github.com/cockroachdb/cockroach/blob/419b98577f992b9b6531640eefc9bb32031b709e/pkg/kv/kvserver/client_merge_test.go#L4517)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

For some reason, I thought that `ReplicationManual` disables the merge `queue_enabled` cluster setting. Removed.
</blockquote></details>

I kept missing this, but turns out `ReplicationManual` does disable the merge_queue. See: https://github.com/cockroachdb/cockroach/blob/55f3a9d48537e019905b34b90e628d9ecfd4ddb8/pkg/testutils/testcluster/testcluster.go#L315-L325

**Review by nvb — APPROVED** [review]
:lgtm: other than one comment.

> Reviewed 11 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63215#-:-MXoxRMo70lpYbt_B95P:bb8784p)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15 and @andreimatei)

___
*[pkg/kv/kvserver/merge_queue.go, line 358 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63215#-MXiIGOv--1UgYYu7p1V:-MXovRv1DEZ9gqIRlF3s:bmdn7rw) ([raw file](https://github.com/cockroachdb/cockroach/blob/419b98577f992b9b6531640eefc9bb32031b709e/pkg/kv/kvserver/merge_queue.go#L358)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

We do in general, but not for purgatory errors. I'm not sure why, though, since it seems like in most cases we do want these errors in the logs. See: https://github.com/cockroachdb/cockroach/blob/ea9074ba76a842a928b18c403ec78ec362fcb4bd/pkg/kv/kvserver/queue.go#L1084-L1094
</blockquote></details>

Ack. Thanks for the explanation.
___
*[pkg/kv/kvserver/replica_learner_test.go, line 387 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63215#-MXow0CsANA4moUBLl1h:-MXow0CsANA4moUBLl1i:b4jlgro) ([raw file](https://github.com/cockroachdb/cockroach/blob/e975a19708856dd270cbeec4b6c835df9cabbfba/pkg/kv/kvserver/replica_learner_test.go#L387)):*
> ```Go
> 	scratchStartKey := tc.ScratchRange(t)
> 	atomic.StoreInt64(&skipInitialSnapshot, 1)
> 	_, err := tc.AddNonVoters(scratchStartKey, false, tc.Target(1))
> ```

The `waitForInit` argument seems really unfortunate. It's semantics aren't particularly easy to understand and it's only needed in this very specific case. Ideally, we wouldn't bloat the `TestCluster` API to accommodate this one test, placing the burden on every other test to understand what this argument means. Instead, we'd be able to accomplish what it wants through some combination of testing knobs and maybe with some concurrency. For instance, could we put this in a goroutine, have some waiting mechanism in the main goroutine, manually enqueue, and then ensure that this eventually returns?

**Review by aayushshah15 — COMMENTED** [review]
Thanks for the reviews on this. I'll hold off on merging this until tomorrow in case you wanted one more look.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63215#-:-MXp7RJq1K4swqiDluWK:b6nbflm)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15, @andreimatei, and @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_learner_test.go, line 387 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63215#-MXow0CsANA4moUBLl1h:-MXoy8DW0xFGNOgDCEOy:b-vt690j) ([raw file](https://github.com/cockroachdb/cockroach/blob/e975a19708856dd270cbeec4b6c835df9cabbfba/pkg/kv/kvserver/replica_learner_test.go#L387)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The `waitForInit` argument seems really unfortunate. It's semantics aren't particularly easy to understand and it's only needed in this very specific case. Ideally, we wouldn't bloat the `TestCluster` API to accommodate this one test, placing the burden on every other test to understand what this argument means. Instead, we'd be able to accomplish what it wants through some combination of testing knobs and maybe with some concurrency. For instance, could we put this in a goroutine, have some waiting mechanism in the main goroutine, manually enqueue, and then ensure that this eventually returns?
</blockquote></details>

Heh, I was worried you wouldn't be a fan of this.  Thanks for that suggestion!

**Review by nvb — APPROVED** [review]
:lgtm_strong: 

> Reviewed 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63215#-:-MXpBGB5Bl9k0sAj4aTO:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15 and @andreimatei)

___
*[pkg/testutils/testcluster/testcluster.go, line 623 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/63215#-MXpAiorEJVpAcPJvDP_:-MXpAios9rVsPuyh2F6f:b-czdjov) ([raw file](https://github.com/cockroachdb/cockroach/blob/651184b3cfbd7c6d336bb49e7152e3d48ea06416/pkg/testutils/testcluster/testcluster.go#L623)):*
> ```Go
> 	}
> 
> 	if err := tc.waitForNewReplicas(startKey, false /* waitForVoter */, targets...); err != nil {
> ```

We seem to have lost a pair of comments in this file.

**Pull request merged**
