### PR TITLE
sql: parallelize TestLogic

### PR DESCRIPTION
**Pull request by jordanlewis**
Use Go's [`t.Parallel()`](https://golang.org/pkg/testing/#T.Parallel) functionality to run each configuration of the logic tests in parallel when `-show-sql` is disabled. This decreases the running time of the logic tests to about 20 seconds on my machine.

Also, clean up some test logging to make the output more readable in the parallel case.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
:lgtm_strong:  Nice!

---

Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/logic_test.go, line 1388 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14872#-KhZmKqWtm-9yIQ883iq:-KhZmKqX_ZKyBT7ptqpy:b-uhzm7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/61af96622948584de5a77ae4b150400502c0e672/pkg/sql/logic_test.go#L1388)):*
> ```Go
> 	sql.StmtStatsEnable = true
> 
> 	var mu syncutil.Mutex
> ```

[nit] add a comment explaining which variables are protected by the mutex, or `var total, totalFail, totalUnsupported int  // protected by mu`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14872#-:-KhZmeiLVhw1iLPgX6gZ:b-t3mbzd)*

**Comment by jordanlewis** [comment]
PTAAL - I had to change some more things to avoid races.

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/server/status/runtime.go, line 116 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14872#-KhbpNwikcbpf2gLma8T:-KhbpNwikcbpf2gLma8U:bjyn9l0) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9a5ddd8a211cec2e845cf3cba79b6432087d1f4/pkg/server/status/runtime.go#L116)):*
> ```Go
> 	// Build information.
> 	metaBuildTimestamp := metric.Metadata{Name: "build.timestamp", Help: "Build information"}
> 	metaBuildTimestamp.AddLabel("tag", info.Tag)
> ```

can't this all be done at init? not sure why any of it is done at startup.

---

*[pkg/sql/logic_test.go, line 1386 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/14872#-KhbrF5FG_TqoByxJHrn:-KhbrF5FG_TqoByxJHro:b-hxfzdg) ([raw file](https://github.com/cockroachdb/cockroach/blob/51eebcd4600567b5ab64e4b9cca5063a9f0863e5/pkg/sql/logic_test.go#L1386)):*
> ```Go
> 	// mu protects the following vars, which all get updated from within the
> 	// possibly parallel subtests.
> 	var mu = &syncutil.Mutex{}
> ```

why not use an anonymous struct? also, why the unusual initialization style? finally, why a pointer?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14872)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/logic_test.go, line 1409 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/14872#-KhbwH4ek2ur2oeN4erv:-KhbwH4ek2ur2oeN4erw:bs5x5i0) ([raw file](https://github.com/cockroachdb/cockroach/blob/51eebcd4600567b5ab64e4b9cca5063a9f0863e5/pkg/sql/logic_test.go#L1409)):*
> ```Go
> 		t.Run(cfg.name, func(t *testing.T) {
> 			var cleanupFuncs []func()
> 			if cfg.defaultDistSQLMode != "" {
> ```

This looks good but please double check that the distsql tests actually use distsql. Run `COCKROACH_DISTSQL_LOG_PLAN=1 make test PKG=./pkg/sql TESTS='Logic/distsql/aggregate' TESTFLAGS='-v -show-logs'  and make sure there are plan URLS in the logs (grep for raduberinde.github.io)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14872)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/logic_test.go, line 1409 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/14872#-KhbwH4ek2ur2oeN4erv:-Khc-RQfM37aO7i6e0aM:bt6d93e) ([raw file](https://github.com/cockroachdb/cockroach/blob/51eebcd4600567b5ab64e4b9cca5063a9f0863e5/pkg/sql/logic_test.go#L1409)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This looks good but please double check that the distsql tests actually use distsql. Run `COCKROACH_DISTSQL_LOG_PLAN=1 make test PKG=./pkg/sql TESTS='Logic/distsql/aggregate' TESTFLAGS='-v -show-logs'  and make sure there are plan URLS in the logs (grep for raduberinde.github.io)
</blockquote></details>

We should move this into a testing knob rather than mucking with a global, maybe it's worth doing now since we moved this code around a couple of times recently.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14872)*

**Comment by jordanlewis** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/server/status/runtime.go, line 116 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14872#-KhbpNwikcbpf2gLma8T:-Khc41gJyHr33tS0FcXM:bh7s1gt) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9a5ddd8a211cec2e845cf3cba79b6432087d1f4/pkg/server/status/runtime.go#L116)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

can't this all be done at init? not sure why any of it is done at startup.
</blockquote></details>

Great question - I'm not sure. I'll let this get resolved in a different PR though.

---

*[pkg/sql/logic_test.go, line 1388 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14872#-KhZmKqWtm-9yIQ883iq:-Khc46XZQ-FzliiMd0Z3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/61af96622948584de5a77ae4b150400502c0e672/pkg/sql/logic_test.go#L1388)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] add a comment explaining which variables are protected by the mutex, or `var total, totalFail, totalUnsupported int  // protected by mu`
</blockquote></details>

Done.

---

*[pkg/sql/logic_test.go, line 1386 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/14872#-KhbrF5FG_TqoByxJHrn:-Khc478tKz7BT8E6eEJ0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/51eebcd4600567b5ab64e4b9cca5063a9f0863e5/pkg/sql/logic_test.go#L1386)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why not use an anonymous struct? also, why the unusual initialization style? finally, why a pointer?
</blockquote></details>

Done.

---

*[pkg/sql/logic_test.go, line 1409 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/14872#-KhbwH4ek2ur2oeN4erv:-Khc47iemrlLFQODHzd8:bpjg0px) ([raw file](https://github.com/cockroachdb/cockroach/blob/51eebcd4600567b5ab64e4b9cca5063a9f0863e5/pkg/sql/logic_test.go#L1409)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

We should move this into a testing knob rather than mucking with a global, maybe it's worth doing now since we moved this code around a couple of times recently.
</blockquote></details>

Thanks for the tip - it in fact was broken since the reset didn't wait for all the parallel tests to finish. It's fixed now. I'll send another PR for moving that into a testing knob.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14872)*

**Comment by tamird** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/server/status/runtime.go, line 116 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/14872#-KhbpNwikcbpf2gLma8T:-Khc7-tk-L4PPUlO5lzQ:b-vzy9ml) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9a5ddd8a211cec2e845cf3cba79b6432087d1f4/pkg/server/status/runtime.go#L116)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Great question - I'm not sure. I'll let this get resolved in a different PR though.
</blockquote></details>

cc @mberhault 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14872)*

**Comment by knz** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r4, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14872#-:-KhfaLH8kt5sfu6S17nF:bnfp4nl)*

**Pull request merged**
