### PR TITLE
libroach: Port export stats collection to c++

### PR DESCRIPTION
**Pull request by adityamaru27**
The stats collection for an `ExportRequest` previously required
an additional iteration over the newly created SSTable, once the
data had been exported. This was because the RowCounter used in
this process only existed on the go side.
This migration pushes the `RowCounter` to C++ enabling us to
accumulate statistics on the fly while exporting data.

### CODE REVIEW

**Comment by adityamaru27** [comment]
@ajkr @dt have rebased with the base branch merged.

**Comment by adityamaru27** [comment]
friendly ping

**Review by dt — APPROVED** [review]
Go side LGTM. C++ side is a little outside my expertise so I'll defer to @ajkr there.

> Reviewed 1 of 11 files at r1, 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37887#-:-Lha1EY2BOq7oLCLOX1I:b9gng5s)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru27, @ajkr, and @dt)

___
*[c-deps/libroach/row_counter.cc, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37887#-Lha0ZB82yMcdNRfURGB:-Lha0ZB82yMcdNRfURGC:bb6ht2j) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc44c4475c3dc734cb94ef0c2212817bc440e77c/c-deps/libroach/row_counter.cc#L1)):*
> ```cpp
> // Copyright 2016 The Cockroach Authors.
> ```

2019

**Review by ajkr — APPROVED** [review]
Nice work. Glad we can drop the table scan in Go.

> Reviewed 10 of 11 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37887#-:-LjHU3EC7FTzmop6Ntxz:bwwf7ev)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru27)

___
*[c-deps/libroach/row_counter.cc, line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37887#-LjHR78K5DrKMiTEN8wp:-LjHR78L-dg-NguAedzD:bts21pd) ([raw file](https://github.com/cockroachdb/cockroach/blob/4eba9c0ce2036865c7a3c4ce05f9c65e6d89ff40/c-deps/libroach/row_counter.cc#L50)):*
> ```cpp
>     // then we bail. Note that we don't consider this an error because
>     // EnsureSafeSplitKey can be called on keys that look like table
>     // keys but which do not have a column ID length suffix (e.g
> ```

Does it matter that keys without a column ID length might happen to end with a byte that is a valid column ID length?
___
*[c-deps/libroach/row_counter.cc, line 86 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37887#-LjHShdL0qkfrSn9oJhH:-LjHShdL0qkfrSn9oJhI:b-bj1bwn) ([raw file](https://github.com/cockroachdb/cockroach/blob/4eba9c0ce2036865c7a3c4ce05f9c65e6d89ff40/c-deps/libroach/row_counter.cc#L86)):*
> ```cpp
> 
>   size_t key_size = decoded_key.size();
>   EnsureSafeSplitKey(&decoded_key);
> ```

Is the point of removing the column ID before doing key comparisons to save on key comparison cost? It is a bit surprising since it looks like it strips off only a few bytes. Or maybe I'm missing the true purpose.

**Review by adityamaru27 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37887)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru27 and @dt)

___
*[c-deps/libroach/row_counter.cc, line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37887#-LjHR78K5DrKMiTEN8wp:-LjI4xNt3aZgFOQK2Hgf:b-axiutp) ([raw file](https://github.com/cockroachdb/cockroach/blob/4eba9c0ce2036865c7a3c4ce05f9c65e6d89ff40/c-deps/libroach/row_counter.cc#L50)):*
<details><summary><i>Previously, ajkr (Andrew Kryczka) wrote…</i></summary><blockquote>

Does it matter that keys without a column ID length might happen to end with a byte that is a valid column ID length?
</blockquote></details>

i'll let @dt answer this, i'm not sure about the circumstances this could happen in.
___
*[c-deps/libroach/row_counter.cc, line 86 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37887#-LjHShdL0qkfrSn9oJhH:-LjI1uBj6h5NKpisAwTr:b-oiwblo) ([raw file](https://github.com/cockroachdb/cockroach/blob/4eba9c0ce2036865c7a3c4ce05f9c65e6d89ff40/c-deps/libroach/row_counter.cc#L86)):*
<details><summary><i>Previously, ajkr (Andrew Kryczka) wrote…</i></summary><blockquote>

Is the point of removing the column ID before doing key comparisons to save on key comparison cost? It is a bit surprising since it looks like it strips off only a few bytes. Or maybe I'm missing the true purpose.
</blockquote></details>

The reason `EnsureSafeSplitKey` strips of everything but the row prefix is to be able to use the bytes as an indicator of whether the key we are processing was added to a new row or not. This is because, the row prefix is unique to all the keys in that row and so it helps when deciding whether or not to increment the number of rows seen.
Again, i'll let @dt confirm this.

**Review by adityamaru27 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37887)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr and @dt)

___
*[c-deps/libroach/row_counter.cc, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37887#-Lha0ZB82yMcdNRfURGB:-LjI8I-v2nJiY--A7NOw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc44c4475c3dc734cb94ef0c2212817bc440e77c/c-deps/libroach/row_counter.cc#L1)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

2019
</blockquote></details>

Done.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37887)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @danhhz, and @dt)

___
*[c-deps/libroach/row_counter.cc, line 50 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37887#-LjHR78K5DrKMiTEN8wp:-LjIFVPW7fvY_aPIlm9v:b7hutiv) ([raw file](https://github.com/cockroachdb/cockroach/blob/4eba9c0ce2036865c7a3c4ce05f9c65e6d89ff40/c-deps/libroach/row_counter.cc#L50)):*
<details><summary><i>Previously, adityamaru27 (Aditya Maru) wrote…</i></summary><blockquote>

i'll let @dt answer this, i'm not sure about the circumstances this could happen in.
</blockquote></details>

I'm honestly not sure. 

I think that in our usage (ingesting table data in RESTORE and IMPORT) we only use this on table keys, but I didn't write the initial version of this so I might be wrong. @danhhz might know more than I do about col families and the low-level encodings?
___
*[c-deps/libroach/row_counter.cc, line 86 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37887#-LjHShdL0qkfrSn9oJhH:-LjIG63aB2J5medIygGw:bor5a05) ([raw file](https://github.com/cockroachdb/cockroach/blob/4eba9c0ce2036865c7a3c4ce05f9c65e6d89ff40/c-deps/libroach/row_counter.cc#L86)):*
<details><summary><i>Previously, adityamaru27 (Aditya Maru) wrote…</i></summary><blockquote>

The reason `EnsureSafeSplitKey` strips of everything but the row prefix is to be able to use the bytes as an indicator of whether the key we are processing was added to a new row or not. This is because, the row prefix is unique to all the keys in that row and so it helps when deciding whether or not to increment the number of rows seen.
Again, i'll let @dt confirm this. 
</blockquote></details>

Exactly: `EnsureSafeSplitKey` is being (ab)used here to determine if this KV key is part of a different SQL "row" than the last KV key we saw, since one of the rules of splits that core obeys when picking them is that they cannot happen in the middle of a SQL row, so we're assuming that we're looking at a new row iff the EnsureSafeSplitKey version is different.

I debated suggesting giving it a more accurate name, but opted against saying that given that it is a c++ analog of a Go function and keeping the name the same should make it easier to realize they're intended to be kept in sync (though maybe there should be a comment added to the Go one saying this one is here and to this one saying it should be kept up-to-date with the Go one).

**Comment by adityamaru27** [comment]
TFTR.
bors r+

**Pull request merged**
