### PR TITLE
storage: smarten GC of orphaned replicas of subsumed ranges

### PR DESCRIPTION
**Pull request by benesch**
When a range is subsumed, there are two paths by which its replicas can
be cleaned up. The first path is that the subsuming replica, when it
applies the merge trigger, removes the subsumed replica. This is the
common case, as all replicas are collocated when the merge transaction
starts.

The second path is that the subumed replica is later cleaned up by the
replica GC queue. This occurs when the subsuming range is rebalanced
away shortly after the merge and so never applies the merge trigger,
"orphaning" the subsuming replica.

The replica GC queue must be careful to never to GC a replica that could
be subsumed. If it discovers that a merge occurred, it needs to "prove"
that the replica is actually orphaned. It does so by checking whether
the left neighbor's local descriptor matches the meta2 descriptor; if it
does not, the left neighbor is out of date and could possibly still
apply a merge trigger, so the replica cannot be GC'd.

Unfortunately, the replica GC queue tried to be too clever: it assumed
such a proof was not necessary if the store was still a member of the
subsuming range. Concretely, suppose adjacent ranges A and B merge, and
store 2's replica of B is orphaned. When the replica GC queue looks
up B's descriptor in meta2, it will get the descriptor for the combined
range AB instead and correctly infer that a merge occurred. It also
assumed that, because AB is listed as having a replica on store2, that
the merge must be applying soon.

This assumption was wrong. Suppose the merged range AB immediately
splits back into A and B. The replica GC queue, considering store 2's
replica of the new B, will, again, correctly infer that a merge took
place (even though the descriptor it fetches from meta2 will have the
same start and end key as its local descriptor, it will have a new range
ID), but now its assumption that a replica of A must exist on the store
is incorrect! A may have been rebalanced away, in which case we *must*
GC the old copy of B, or the store will never be able to accept a
snapshot for the new copy of B.

This scenario was observed in several real clusters, and easily
reproduces when restoring TPC-C.

The fix is simple: teach the replica GC queue to always perform the
proof when a range has been merged away. Attempting to be clever just to
save one meta2 lookup was a bad idea.

Touches #31409.

Release note: None

/cc @andreimatei

### CODE REVIEW

**Review by tbg — APPROVED** [review]
:lgtm_strong: :

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31570#-:-LP5wjTOE8_GqNC9nbG_:b-yncq55)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/storage/replica_gc_queue.go, line 264 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31570#-LP5wQGM3BcS2RJqWrlu:-LP5wQGM3BcS2RJqWrlv:bahnw60) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac0fd2dc2e7aabec44b0aec9e4caaf5ff85f3a0d/pkg/storage/replica_gc_queue.go#L264)):*
> ```Go
> 			}
> 			if leftReplyDesc := rs[0]; !leftDesc.Equal(leftReplyDesc) {
> 				if log.V(1) {
> ```

While you're here, can you make all the `V(x)`s here into `VEventf`s so that Alex' queue endpoint gets better output?

**Review by benesch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31570)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/storage/replica_gc_queue.go, line 264 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/31570#-LP5wQGM3BcS2RJqWrlu:-LP7dWOgBq-nIJ9lyj9P:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac0fd2dc2e7aabec44b0aec9e4caaf5ff85f3a0d/pkg/storage/replica_gc_queue.go#L264)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

While you're here, can you make all the `V(x)`s here into `VEventf`s so that Alex' queue endpoint gets better output?
</blockquote></details>

Done.
___
*[pkg/storage/store_snapshot.go, line 453 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31570#-LP7dXR4187s004XEg8t:-LP7dXR4187s004XEg8u:bgh35t5) ([raw file](https://github.com/cockroachdb/cockroach/blob/79191aafceb0b7c6126f48780ec01ffce65ce97e/pkg/storage/store_snapshot.go#L453)):*
> ```Go
> 				} else {
> 					msg += "; initiated GC:"
> 				}
> ```

PTAL at this. I had to remove this to get the test to not be flaky. (See the commit message for details.) But this isn't just for tests: I've observed this stuck snapshot loop on real clusters. 

I'm very comfortable backporting the change to the GC queue, but I'm a little bit more nervous about backporting this change. Thoughts?

**Review by tbg — APPROVED** [review]
> Reviewed 3 of 3 files at r2, 2 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31570)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/storage/store_snapshot.go, line 453 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31570#-LP7dXR4187s004XEg8t:-LP7mbtYA3mapHwXcheg:b-ufngoa) ([raw file](https://github.com/cockroachdb/cockroach/blob/79191aafceb0b7c6126f48780ec01ffce65ce97e/pkg/storage/store_snapshot.go#L453)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

PTAL at this. I had to remove this to get the test to not be flaky. (See the commit message for details.) But this isn't just for tests: I've observed this stuck snapshot loop on real clusters. 

I'm very comfortable backporting the change to the GC queue, but I'm a little bit more nervous about backporting this change. Thoughts?
</blockquote></details>

LGTM. My context for these checks is that we are just always very careful to avoid a meta2 hotspot, but always based on principle, not because we knew it was a problem. Seeing how poorly this "careful" logic has performed it seems better to do something less careful but more effective.

My only concern is with how often this code path can get hit. Can a tight snapshot loop starve out other replica GC attempts because of the higher priority here? ISTM that we should lower the priority to standard, at least after the first attempt (or based on a heuristic that would work for non-quiesced replicas).

BTW, there's another place in the code where we add to the GC queue with its own heuristic (raft precandidate/candidate state, I think). Mind checking that location as well to make sure it works as intended?

Also, a comment could be valuable here for future readers -- in what situations are we expected to overlap an existing replica, and which of those actually *don't* eventually result in that replica to be gc'ed?

You're right that this is an unfortunate change at this point in the cycle, but on the other hand, now that we know how broken the existing heuristic is, what good is keeping that one? Perhaps you can soften the impact by keeping the old heuristic for the higher priority and using the default priority instead otherwise. Along with a comment to improve further at a later point.

**Review by benesch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31570)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/storage/store_snapshot.go, line 453 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31570#-LP7dXR4187s004XEg8t:-LP7tMhW9LWQIWliANGt:bhir5u) ([raw file](https://github.com/cockroachdb/cockroach/blob/79191aafceb0b7c6126f48780ec01ffce65ce97e/pkg/storage/store_snapshot.go#L453)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

LGTM. My context for these checks is that we are just always very careful to avoid a meta2 hotspot, but always based on principle, not because we knew it was a problem. Seeing how poorly this "careful" logic has performed it seems better to do something less careful but more effective.

My only concern is with how often this code path can get hit. Can a tight snapshot loop starve out other replica GC attempts because of the higher priority here? ISTM that we should lower the priority to standard, at least after the first attempt (or based on a heuristic that would work for non-quiesced replicas).

BTW, there's another place in the code where we add to the GC queue with its own heuristic (raft precandidate/candidate state, I think). Mind checking that location as well to make sure it works as intended?

Also, a comment could be valuable here for future readers -- in what situations are we expected to overlap an existing replica, and which of those actually *don't* eventually result in that replica to be gc'ed?

You're right that this is an unfortunate change at this point in the cycle, but on the other hand, now that we know how broken the existing heuristic is, what good is keeping that one? Perhaps you can soften the impact by keeping the old heuristic for the higher priority and using the default priority instead otherwise. Along with a comment to improve further at a later point.
</blockquote></details>

Downgrading the priority is a good idea. There are two ways we can decide to downgrade (which you mentioned in passing above). The first is to downgrade if the replica has been GC'd in the last, say, ten seconds. This will require another tiny refactor to the replica GC queue, since it doesn't record that a GC has occurred in all cases. (Sigh.) The other is to use some as-yet unknown inactivity heuristic. I'm not sure what that would be. Do you or @ben have a suggestion?

**Review by bdarnell — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31570)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/storage/store_snapshot.go, line 453 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31570#-LP7dXR4187s004XEg8t:-LP845SyEa6Bq9XZRkV0:bz1owow) ([raw file](https://github.com/cockroachdb/cockroach/blob/79191aafceb0b7c6126f48780ec01ffce65ce97e/pkg/storage/store_snapshot.go#L453)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Downgrading the priority is a good idea. There are two ways we can decide to downgrade (which you mentioned in passing above). The first is to downgrade if the replica has been GC'd in the last, say, ten seconds. This will require another tiny refactor to the replica GC queue, since it doesn't record that a GC has occurred in all cases. (Sigh.) The other is to use some as-yet unknown inactivity heuristic. I'm not sure what that would be. Do you or @ben have a suggestion?
</blockquote></details>

I'd tie the priority to the `inactive` check that was there: If it is inactive, enqueue the range at `replicaGCPriorityCandidate`. If it's not, use a lower priority.

**Review by tbg — APPROVED** [review]
> Reviewed 3 of 3 files at r5, 2 of 2 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31570)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/storage/store_snapshot.go, line 453 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/31570#-LP7dXR4187s004XEg8t:-LPAWVYZD2IRVdf3_rW3:b-pbdqz3) ([raw file](https://github.com/cockroachdb/cockroach/blob/79191aafceb0b7c6126f48780ec01ffce65ce97e/pkg/storage/store_snapshot.go#L453)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I'd tie the priority to the `inactive` check that was there: If it is inactive, enqueue the range at `replicaGCPriorityCandidate`. If it's not, use a lower priority. 
</blockquote></details>

Agreed.

**Review by benesch — COMMENTED** [review]
Well fixing that flaky test was miserable. Making the unreliable Raft handler a little more unreliable did the trick. Now the test is the only thing that tries to GC the replica since it doesn't get a ReplicaTooOld error from the remaining members of the range.

bors r=tschottdorf,bdarnell

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/31570#-:-LPERkVVB4OdqIgsR9Cr:bdocjna)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
