### PR TITLE
util/alloc: extract ChunkAllocator to a reusable package

### PR DESCRIPTION
**Pull request by danhhz**
One commit with a pure move and one with changes for ease of review. I'll squash them before merging.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7223)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[util/alloc/allocator.go, line 47 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7223#-KKFV_SS73D4yS-PLaUD:-KKFV_SS73D4yS-PLaUE:-556923390) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5b511bf804e0e8f278cac7caad21261785a8628/util/alloc/allocator.go#L47)):*
> ```Go
> // indicates additional zero bytes that will be present in the returned []byte,
> // but not part of the length.
> func (a ChunkAllocator) Alloc(n int, extraCap int) (ChunkAllocator, []byte) {
> ```

This could be `n, extraCap int`.

---

*[util/alloc/allocator.go, line 60 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7223#-KKFaSwNnzZiYyOHy2Oh:-KKFaSwOcRC_8wRnpKo9:-1859139120) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5b511bf804e0e8f278cac7caad21261785a8628/util/alloc/allocator.go#L60)):*
> ```Go
> // extraCap indicates additional zero bytes that will be present in the returned
> // []byte, but not part of the length.
> func (a ChunkAllocator) AllocAndCopy(src []byte, extraCap int) (ChunkAllocator, []byte) {
> ```

I'm not terribly fond of the name `AllocAndCopy`, but I have nothing better. `New` seems too terse.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7223#-:-KKFaZP86ygDQXUa4wc6:1417088721)*

**Comment by paperstreet** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[util/alloc/allocator.go, line 60 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7223#-KKFaSwNnzZiYyOHy2Oh:-KKFbUtUytWYhwq_DiwC:-151870301) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5b511bf804e0e8f278cac7caad21261785a8628/util/alloc/allocator.go#L60)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I'm not terribly fond of the name `AllocAndCopy`, but I have nothing better. `New` seems too terse.
</details>
Same. I was also considering AllocAndInit or Copy. Do either of those sound better?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7223)*

**Comment by dt** [comment]
:lgtm:

Some naming bike shed nits (feel free to ignore): I'd not crazy about `calloc` local, and might call the pkg `bufalloc`.

---

Reviewed 2 of 2 files at r1.
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[util/alloc/allocator.go, line 60 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7223#-KKFaSwNnzZiYyOHy2Oh:-KKFbzcnhvWw08A9qfzN:973376411) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5b511bf804e0e8f278cac7caad21261785a8628/util/alloc/allocator.go#L60)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> Same. I was also considering AllocAndInit or Copy. Do either of those sound better?
</details>
+1 to `Copy`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7223#-:-KKFc4kvc7wjW4BEl1We:-1242528687)*

**Comment by petermattis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[util/alloc/allocator.go, line 60 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7223#-KKFaSwNnzZiYyOHy2Oh:-KKFctkv_2HBFVDzzFZh:-524195427) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5b511bf804e0e8f278cac7caad21261785a8628/util/alloc/allocator.go#L60)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> +1 to `Copy`
</details>
`Copy` SGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7223)*

**Comment by paperstreet** [comment]
Thanks for the reviews!

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[util/bufalloc/byte_allocator.go, line 47 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7223#-KKFV_SS73D4yS-PLaUD:-KKFfzfQKyHUPpmcd5xB:1741239295) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5b511bf804e0e8f278cac7caad21261785a8628/util/bufalloc/byte_allocator.go#L47)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> This could be `n, extraCap int`.
</details>
I only like doing that when they're _very_ closely related (`start, end int`). This is borderline, but my preference is to keep it as is

---

*[util/bufalloc/byte_allocator.go, line 60 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7223#-KKFaSwNnzZiYyOHy2Oh:-KKFfzNml53ptga3dMni:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/d5b511bf804e0e8f278cac7caad21261785a8628/util/bufalloc/byte_allocator.go#L60)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> `Copy` SGTM
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7223#-:-KKFgDVDnl12TS-E9TzU:-1063767586)*

**Comment by dt** [comment]
Reviewed 1 of 3 files at r1, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7223)*

**Pull request merged**
