### PR TITLE
roachtest: create admin role for roachtests run on secure cluster

### PR DESCRIPTION
**Pull request by msbutler**
When a roachtest run on a secure roachprod cluster starts the cluster, the clusterImpl will now create an Admin role "roach" with password "secure". The roachtest user can then use these credentials to easily log into the db console.

Informs #112120

Release note: none

### CODE REVIEW

**Comment by renatolabs** [comment]
Thank you! Now that I think of it, I believe we should extend this behaviour to virtual clusters as well. I can work on that soon; there's a PR being merged right now to unify shared/external process tenants (#111533).

I'll wait for that to merge first then I'll open a follow-up PR starting from this diff. Does that sound good to you?

**Comment by msbutler** [comment]
sounds good! I'll leave this PR for you to pickup.

**Comment by renatolabs** [comment]
> I believe we should extend this behaviour to virtual clusters as well

I created a PR to do this -- #112765.

**Comment by msbutler** [comment]
closing in favor of https://github.com/cockroachdb/cockroach/pull/112765

**Pull request closed without merging**
