### PR TITLE
kvtenant: fetch ID of cluster during tenant startup

### PR DESCRIPTION
**Pull request by andy-kimball**
Previously, the ClusterID was not available to SQL tenants. Calling the
crdb_internal.cluster_id method returned a Nil UUID. However, the ClusterID
is needed for logging and metrics for SQL tenants. This commit fetchs the
ClusterID during tenant startup by subscribing to the "cluster-id" gossip
value. That value is then stored in the rpc.Context.ClusterID field, which
is used throughout the code when the ClusterID is needed.

Release note (sql change): The crdb_internal.cluster_id method now returns
the ID of the underlying KV cluster in multi-tenant scenarios rather than
the Nil UUID.

### CODE REVIEW

**Comment by andy-kimball** [comment]
NOTE: I plan to backport this to a 20.2 patch release, so also verify that it's safe according to our [backport policy](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/1043235321/Proposal+Database+Patch+Policy). This PR only changes code that runs in multi-tenant scenarios, so there should be zero impact to production clusters.

**Comment by andy-kimball** [comment]
The other possibility we might discuss is generating a unique `ClusterID` for every logical tenant cluster, and reporting that instead. However, I think that'd be quite a bit more difficult due to assumptions that are likely scattered across the code, and I don't see much benefit to doing so. Would be interested to hear other opinions.

**Review by knz — COMMENTED** [review]
No objection on the end result, but I don't know how to review the code change.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58317#-:-MPiZFzV8aD8dNPCCHyc:b-3mczax)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @asubiotto, and @tbg)

**Review by tbg — APPROVED** [review]
:lgtm:

This regresses us in a sense: prior to this change we were in principle (finally) able to make the clusterID known before instantiation of the rpcContext; now it is dynamic again (which cements a bit of code we've wanted to get rid of). However, I took a look and it does not seem worth addressing at this point - benefit outweighs cost.

> Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58317#-:-MQBWQA_AmIE-hXx5-sN:bkv2ce2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @asubiotto)

**Pull request merged**
