### PR TITLE
storageccl,cloud: plumb ctx to external file Readers

### PR DESCRIPTION
**Pull request by andreimatei**
This patch changes the interface implemented by all the cloud-specific
file readers to take a ctx for their Read() and Close() methods. Before,
some implementations were capturing a ctx at construction time, which is
generally a bad thing to do - operations should generally run in the
caller's ctx, rather than in some ctx captured in the past. Besides
being generally bad, it's also dangeroursd: in two instances,
cloud.ResumingReader was capturing a ctx that was immediately becoming
invalid because the tracing span in it was being closed[1] (so when the
ResumingReader was trying to use the captured ctx, that was a
use-after-finish of the respective tracing span). A stack trace show
such a use-after-Finish is captured in [2].

This patch improves the situation by plumbing ctxs to the Read()s. Now,
ResumingReader no longer captures a ctx. The plumbing has not spread
anywhere because of practical reasons. Unfortunately, I had to make
storageccl.sstReader capture a ctx (the sstReader wraps file readers
such as cloud.ResumingReader). If contexts are to be used at all,
someone needs to capture one since the sstReader is used through the
pebble.sstable.Reader interface which does not plumb contexts.
This lifting up of the context capture from ResumingReader to sstReader
is a good thing since sstReader is not a broadly used type and the
capturing of the context is now more visible; it's no longer hidden many
layers down. Also, the use-after-Finish in the ResumingReader is fixed
because the higher-level ctx captured by the sstReader (a DistSQL
processor ctx) lives long enough.

[1]
https://github.com/cockroachdb/cockroach/blob/3be8121ad9e96416c49c27947facfa18831794b9/pkg/cloud/gcp/gcs_storage.go#L186
and also
https://github.com/cockroachdb/cockroach/blob/0a6b7427603c268b41e39d7acba917c1227859ca/pkg/cloud/amazon/s3_storage.go#L497

[2] https://gist.github.com/andreimatei/7b86d414a93c81cf93ffe68fe2788ec6

Release note: None

### CODE REVIEW

**Review by adityamaru — APPROVED** [review]
Thanks for doing this, I've been through it once and it looks good to me.

**Comment by dt** [comment]
I sorta liked implementing io.Reader/io.Writer/etc -- I doubt `sstable.Reader` will be the last thing we want to pass an `io.Reader` to? I suppose a little utility that explicitly captures a ctx to turn a ReaderCtx into an io.Reader or whatever could mitigate that / generalize the pattern we use for the sst reader, so I'm potentially able to be convinced this change is the way, but let me briefly entertain the alternative: asking an external storage for a reader or writer captures the passed context. The caller who asks for that reader or writer must close the reader/writer before returning, un-capturing the ctx. Would a usage contract like that mitigate the captured ctx woes?

**Comment by dt** [comment]
> How come you like implementing io.Reader?

As you point out, go stdlib [set] this interface in stone, so and it is ubiquitous now, so implementing it makes it easier to plug in code, like pebble's sstable.Reader, that was written to the same interface. We used to _not_ implement Writer and put some effort into getting to that. That said, the presence of the adaptors mostly mitigates this, I think: _somebody_ has to capture a context to implement that interface, so making the caller do it explicitly is nice too.

I'm convinced, and echo @adityamaru's thanks for doing this.

>  I thought about moving it to a util package

Yeah, I'd prefer that. perhaps the interfaces and adaptors could all go to util/ioctx ?

**Comment by andreimatei** [comment]
> I'm convinced by your point about doing it explicitly makes it easier to do it in the scope where the lifetime actually matches vs doing it in the current reader/writer creators, and then echo @adityamaru's thanks for doing all the work here for us.

Thanks you sir.

> Yeah, I'd prefer that. perhaps the interfaces and adaptors could all go to util/ioctx ?

done

**Comment by andreimatei** [comment]
TFTRs!

bors r+

**Pull request merged**
