### PR TITLE
opt: fix incorrect ordering of partial index DEL cols in DELETE

### LINKED ISSUE #99630: sqlsmith: invalid datum type given: bool, expected date during DELETE USING
roachtest.sqlsmith/setup=rand-tables/setting=no-ddl [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/9262923?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/9262923?buildTab=artifacts#/sqlsmith/setup=rand-tables/setting=no-ddl) on master @ [2bd2c806ab3044569b09e0a205b5bc0452ad4e2b](https://github.com/cockroachdb/cockroach/commits/2bd2c806ab3044569b09e0a205b5bc0452ad4e2b):

```
test artifacts and logs in: /artifacts/sqlsmith/setup=rand-tables/setting=no-ddl/run_1
(sqlsmith.go:244).func3: error: pq: internal error: invalid datum type given: bool, expected date
stmt:
WITH
	with3617 (col25095)
		AS (
			SELECT
				*
			FROM
				(VALUES (e'\U00002603':::STRING), (e'\x17':::STRING), (NULL), ('$':::STRING)) AS tab12083 (col25095)
		),
	"with3618" (col25096)
		AS (
			SELECT
				*
			FROM
				(VALUES ('-':::STRING), ('^':::STRING), (COALESCE('u':::STRING, 't':::STRING)), ('D':::STRING))
					AS "tAb12084" (col25096)
		)
SELECT
	cte_ref1018.col25095 AS c😻ol25097, ret36 AS col25098
FROM
	[
		DELETE FROM
			defaultdb.public." table2" AS t͙ab12085
		USING
			defaultdb.public." table2" AS tab12086,
			defaultdb.public." table2" AS tab12087,
			defaultdb.public.tabl̲e3 AS "t""ab12088"
		RETURNING
			"col3_2" AS ret36
	],
	with3617 AS cte_ref1018
WHERE
	false
LIMIT
	31:::INT8;
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sqlsmith/setup=rand-tables/setting=no-ddl.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-25992

### PR DESCRIPTION
**Pull request by mgartner**
This commit fixes a bug in the optimizer that incorrectly ordered
partial index DEL columns in input rows of delete nodes. Previously, the
optimizer put these columns before passthrough columns, which are used
when the `RETURNING` clause contains columns from one of the tables in
the USING clause. However, `execFactory.ConstructDelete` assumes that
the partial index DEL columns come after the passthrough columns when
calculating the partial index column offset in the input row. These
conflicting assumptions could cause internal errors and corrupt partial
indexes. The bug is fixed by putting the passthrough columns before the
partial index DEL columns in the input rows of delete nodes.

Fixes #99630

Release note (bug fix): A bug has been fixed that could cause internal
errors and corrupt partial indexes when deleting rows with the
`DELETE FROM .. USING` syntax. This bug is only present in alpha
versions of v23.1.0.

#### sql: remove `deleteRun.partialIndexDelValsOffset`

The `partialIndexDelValsOffset` field of the `deleteRun` struct is not
necessary because it can be computed from other fields. It has been
removed.

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
I'll backport just the first commit to 23.1.

**Review by michae2 — APPROVED** [review]
:lgtm: Nice!

> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100301#-:-NRsYB_48yL2ZIIhoiBj:b-8gk8uj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100301#-NRsWjNfEvRLp8KszUld):*
nit: extra space before comma
___
*[`pkg/sql/opt/exec/execbuilder/mutation.go` line 496 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100301#-NRsXS8dCBgrYY2Czqx1:-NRsXS8dCBgrYY2Czqx2:b-wajn0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/17b27b94773349b2905058d0eefa7aa17716e20a/pkg/sql/opt/exec/execbuilder/mutation.go#L496)):*
> ```Go
> 	// TODO(andyk): Using ensureColumns here can result in an extra Render.
> 	// Upgrade execution engine to not require this.
> 	colList := make(opt.ColList, 0, len(del.FetchCols)+len(del.PartialIndexDelCols)+len(del.PassthroughCols))
> ```

nit: I know it doesn't matter, but it might be nice to put these in the same order.
___
*[`pkg/sql/logictest/testdata/logic_test/delete` line 567 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100301#-NRsXBuW3xQVcRThs49q:-NRsXBuW3xQVcRThs49r:bx4vblq) ([raw file](https://github.com/cockroachdb/cockroach/blob/17b27b94773349b2905058d0eefa7aa17716e20a/pkg/sql/logictest/testdata/logic_test/delete#L567)):*
> ```
> query I
> SELECT a FROM t99630a@idx WHERE a > 0
> ----
> ```

Nice corruption example!

**Review by rytaft — APPROVED** [review]
:lgtm: good find!

> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100301#-:-NRsiQb93Wyzv2wQ-nnd:bbxruok)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`-- commits` line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100301#-NRshm5qBgIBGPkcBeEk):*
Isn't it in an alpha version? I think we still want release notes for that

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100301)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @michae2 and @rytaft)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100301#-NRsWjNfEvRLp8KszUld):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: extra space before comma
</blockquote></details>

Done.
___
*[`pkg/sql/opt/exec/execbuilder/mutation.go` line 496 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100301#-NRsXS8dCBgrYY2Czqx1:-NRsidulAWmNapfgE4Hl:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/17b27b94773349b2905058d0eefa7aa17716e20a/pkg/sql/opt/exec/execbuilder/mutation.go#L496)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: I know it doesn't matter, but it might be nice to put these in the same order.
</blockquote></details>

Good idea. Done.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100301)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @michae2 and @rytaft)

___
*[`-- commits` line 18 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100301#-NRshm5qBgIBGPkcBeEk):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Isn't it in an alpha version? I think we still want release notes for that
</blockquote></details>

I've added one, but this is news to me. If it is something we want, I don't think we're very consistent with it.

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
