### PR TITLE
sql: add a clarifying comment about flow cleanup in distsql_running

### PR DESCRIPTION
**Pull request by yuzefovich**
Release note: None

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41306#-:-LrEnSkA5KBuXQO8DkIK:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by yuzefovich** [comment]
The failure is definitely not caused by this PR. Let's try one more time.

bors r+

**Pull request merged**
