### PR TITLE
physicalplan: remove no longer used field

### PR DESCRIPTION
**Pull request by yuzefovich**
Release note: None

Release justification: low-risk pure cleanup.

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69329#-:-Mhu64ib6UB9J5AyNXff:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
Radu, thoughts on merging this during the stability period? I'm on the fence - it seems like almost non-production code change, yet it doesn't really fix anything.

**Comment by RaduBerinde** [comment]
I'd merge it, it's pretty clearly just cleanup.

**Comment by yuzefovich** [comment]
Sounds good, TFTR!

bors r+

**Comment by yuzefovich** [comment]
Actually, let me adjust the release justification.

bors r-

**Pull request merged**
