### PR TITLE
ui: replace PhantomJS with JSDom

### LINKED ISSUE #12094: teamcity: failed tests on master: PhantomJS crashed
The following tests appear to have failed:

[#82285](https://teamcity.cockroachdb.com/viewLog.html?buildId=82285):

```

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by jordanlewis**
JSDom is a lighter-weight replacement for PhantomJS. It's missing a lot
of the features of PhantomJS, as it's just a virtual DOM without any of
the other headless browser features, but it doesn't seem like we need
those features.

JSDom is much faster at running our tests as well and doesn't seem to
crash ツ

Fixes #12094

cc @a-robinson 

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14240)

### CODE REVIEW

**Comment by a-robinson** [comment]
I'm not qualified to review the change, but I give the gif two thumbs up 👍👍

**Comment by dt** [comment]
> doesn't seem to crash
:plause: :

**Comment by tamird** [comment]
:lgtm:

We should remove travis_retry and the associated hackery while we're at it, and don't forget to add "Fixes ...".

---

Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14240#-:-KfSwIyeDr4MHNK_Kkcq:b3uq3l)*

**Comment by tamird** [comment]
Er, travis_retry is used elsewhere, but should be removed from the UI bits.

**Comment by benesch** [comment]
:lgtm:

This is wonderful.

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14240#-:-KfT40LabXSJs8jdiTmx:bljxur5)*

**Comment by mrtracy** [comment]
Isn't there a reason we were using PhantomJS in the first place?

We originally were running these tests on node directly, and we stopped doing that because of differences in the execution environment (ByteBuffers or something) which are different in the node and browser execution environment.  I'm assuming that JSDom has all of these differences accounted for?

For the record, I was completely fine with testing on node directly, so this gets my :LGTM: even if the differences aren't accounted for.

**Comment by tamird** [comment]
Yeah, the reason was a difference between `fetch` in node and `fetch` in the browser; this is why we were originally using [`isomorphic-fetch`](https://github.com/matthew-andrews/isomorphic-fetch). Since this change didn't require `fetch`-in-node, it seems that JSDom is exercising the browser code path.

Indeed, [JSDom implements XMLHttpRequest](https://github.com/tmpvar/jsdom/blob/master/lib/jsdom/living/xmlhttprequest.js), which is used by [`whatwg-fetch`](https://github.com/github/fetch).

**Comment by tamird** [comment]
Heh, seems like we could have been using JSDom from the start https://github.com/tmpvar/jsdom/commit/a530723c63940c1415c268810337171112da6d6a.

**Comment by jordanlewis** [comment]
I wasn't aware of the differences you mention, but it sounds like we are ok to merge. TFTRs!

**Pull request merged**
