### PR TITLE
roachtest: fail tpcdsvec test with an error

### PR DESCRIPTION
**Pull request by yuzefovich**
In `tpcdsvec` test we run all the queries even we hit an error.
Previously if an error occurred, we would just fail the test, and now we
will be failing with an error that is a "combination" of all occurred
errors.

Addresses: #47889.

Release note: None

### CODE REVIEW

**Review by asubiotto — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47974)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/cmd/roachtest/tpcdsvec.go, line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47974#-M5vsxlE1RGg9fQmjUzM:-M5vsxlE1RGg9fQmjUzN:b-94vv5p) ([raw file](https://github.com/cockroachdb/cockroach/blob/aac4472c828d2d1348af8ac29847e070b2457d4e/pkg/cmd/roachtest/tpcdsvec.go#L202)):*
> ```Go
> 		}
> 		if lastErr != nil {
> 			t.Fatal(lastErr)
> ```

Can we somehow accumulate errors and display them all?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47974)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/cmd/roachtest/tpcdsvec.go, line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47974#-M5vsxlE1RGg9fQmjUzM:-M5wRyG2CfpTqUHqfYCd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aac4472c828d2d1348af8ac29847e070b2457d4e/pkg/cmd/roachtest/tpcdsvec.go#L202)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Can we somehow accumulate errors and display them all?
</blockquote></details>

Done.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47974#-:-M5zvEdX4IEbeinzhGUp:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
