### PR TITLE
storage: avoid map lookup in raftRcvdMessages, replace with array

### PR DESCRIPTION
**Pull request by nvb**
Drive by cleanup with small perf impact.

Release note: None

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41573#-:-LrAT0Zp731nDIyeROj3:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/storage/raft.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41573#-LrASqQh2gBmvI9wiWP2:-LrASqQh2gBmvI9wiWP3:b1ygw65) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1d14cd01d1c8acd0d28e13067592dcb902546d4/pkg/storage/raft.go#L28)):*
> ```Go
> 
> func init() {
> 	if numRaftMsgTypes != len(raftpb.MessageType_name) {
> ```

I wonder if this should instead look for the max-raft-message-type in `raftpb.MessageType_name`. The current code will fail if a new message type is added and an old one is removed.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41573)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @petermattis)

___
*[pkg/storage/raft.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41573#-LrASqQh2gBmvI9wiWP2:-LrAiXOK6X9lrop1juwy:b-2yt6da) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1d14cd01d1c8acd0d28e13067592dcb902546d4/pkg/storage/raft.go#L28)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I wonder if this should instead look for the max-raft-message-type in `raftpb.MessageType_name`. The current code will fail if a new message type is added and an old one is removed.
</blockquote></details>

Is that really a concern? The order of the message types in the array doesn't need to be stable across builds, as long as all of the references to the message types remain. And if not, we'll already hit a compilation error elsewhere.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41573)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/storage/raft.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41573#-LrASqQh2gBmvI9wiWP2:-LrAjPFSBjnC1KWjH0JG:b3suhug) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1d14cd01d1c8acd0d28e13067592dcb902546d4/pkg/storage/raft.go#L28)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is that really a concern? The order of the message types in the array doesn't need to be stable across builds, as long as all of the references to the message types remain. And if not, we'll already hit a compilation error elsewhere.
</blockquote></details>

The `MessageType` enum values are encoded in the proto. My point was what happens if someone adds `MsgBuyMeABeer = 19` and removes `MsgCheckQuorum`. The number of elements in `MessageType_name` remains at `19`, but `raftRcvdMessages[MsgBuyMeABeer]` is an out-of-bounds slice access.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41573)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @petermattis)

___
*[pkg/storage/raft.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41573#-LrASqQh2gBmvI9wiWP2:-LrB8x1d17-YVLSA6W9t:b-kco9d3) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1d14cd01d1c8acd0d28e13067592dcb902546d4/pkg/storage/raft.go#L28)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The `MessageType` enum values are encoded in the proto. My point was what happens if someone adds `MsgBuyMeABeer = 19` and removes `MsgCheckQuorum`. The number of elements in `MessageType_name` remains at `19`, but `raftRcvdMessages[MsgBuyMeABeer]` is an out-of-bounds slice access.
</blockquote></details>

Ok, I see what you mean. How's that?

**Review by petermattis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41573)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/storage/raft.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41573#-LrASqQh2gBmvI9wiWP2:-LrBXdYqBboHZno9VfIg:b-8a64xk) ([raw file](https://github.com/cockroachdb/cockroach/blob/c1d14cd01d1c8acd0d28e13067592dcb902546d4/pkg/storage/raft.go#L28)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Ok, I see what you mean. How's that?
</blockquote></details>

Looks good to me. Thanks.

**Pull request merged**
