### PR TITLE
roachpb, enginepb: better pretty-printing for Transaction, TxnMeta, MVCCMetadata

### PR DESCRIPTION
**Pull request by knz**
Previously, only roachpb.Transaction had a custom pretty-printer.
For TxnMeta and MVCCMetadata the job was given to the protobuf default
printer.

This was inadequate because the output of the protobuf printer v3 is
not really compact, and the v2 printer (used for MVCCMetadata) is
missing labels entirely.

This patch corrects this by adding the missing printers to
TxnMeta and MVCCMetadata.

Additionally, the code also separates formatting via
`String()`/`%v`/`%s`, and formatting via `%+v`. The latter
now prints more details for the TxnMeta including the embedded
raw value and, soon, the ignored seqnum list. For MVCCMetadata, `%+v`
also spells out the intent history.

Finally, the patch also adds some missing fields from the
roachpb.Transaction formatter.

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42249#-:-Lt2DEIa09b2srDvJQFn:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @tbg)

___
*[pkg/roachpb/data.go, line 1124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42249#-Lt2Be683lXRZWpUUQht:-Lt2Be683lXRZWpUUQhu:b-6vq42x) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ce593ac63a5c48742f54fb34b7247b58e481be1/pkg/roachpb/data.go#L1124)):*
> ```Go
> 		fmt.Fprintf(&buf, "%q ", t.Name)
> 	}
> 	fmt.Fprintf(&buf, "{%s} rw=%t stat=%s orig=%s max=%s rts=%s wto=%t",
> ```

Is there a reason to wrap the TxnMeta string in curly brackets? I can't think of any.
___
*[pkg/storage/engine/enginepb/mvcc.go, line 201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42249#-Lt2BnlH0q4KUAy5rSn0:-Lt2BnlH0q4KUAy5rSn1:b-k051yb) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ce593ac63a5c48742f54fb34b7247b58e481be1/pkg/storage/engine/enginepb/mvcc.go#L201)):*
> ```Go
> // String implements the fmt.Stringer interface.
> func (m *MVCCMetadata_SequencedIntent) String() string {
> 	var buf bytes.Buffer
> ```

`strings.Builder` throughout
___
*[pkg/storage/engine/enginepb/mvcc.go, line 236 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42249#-Lt2CQzZ03LMFEbISeDS:-Lt2CQzZ03LMFEbISeDT:b-8ec903) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ce593ac63a5c48742f54fb34b7247b58e481be1/pkg/storage/engine/enginepb/mvcc.go#L236)):*
> ```Go
> func (meta *MVCCMetadata) FormatW(buf io.Writer, expand bool) {
> 	fmt.Fprintf(buf, "{%s} ts=%s del=%t klen=%d vlen=%d",
> 		meta.Txn.String(),
> ```

nit: do you need `.String()`?
___
*[pkg/storage/engine/enginepb/mvcc.go, line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42249#-Lt2D5p19cw7ZxzSYfKY:-Lt2D5p2-nvt9Yyz7GxM:b-sod8u1) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ce593ac63a5c48742f54fb34b7247b58e481be1/pkg/storage/engine/enginepb/mvcc.go#L252)):*
> ```Go
> 		if expand {
> 			fmt.Fprint(buf, " ih={")
> 			for i := range meta.IntentHistory {
> ```

Do you have a preference about whether these should be separated by commas or not?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42249)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @tbg)

___
*[pkg/roachpb/data.go, line 1124 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42249#-Lt2Be683lXRZWpUUQht:-Lt570vF7lYLhmH5XWgI:b294bfp) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ce593ac63a5c48742f54fb34b7247b58e481be1/pkg/roachpb/data.go#L1124)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is there a reason to wrap the TxnMeta string in curly brackets? I can't think of any.
</blockquote></details>

I have a reason - that's it's a separate piece of data that gets copied on its own in other places (in particular mvccmetadata).
Also this was missing the `meta=` prefix, which I now added.
___
*[pkg/storage/engine/enginepb/mvcc.go, line 201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42249#-Lt2BnlH0q4KUAy5rSn0:-Lt57D2jDuwHpJhE9Sl6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ce593ac63a5c48742f54fb34b7247b58e481be1/pkg/storage/engine/enginepb/mvcc.go#L201)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`strings.Builder` throughout
</blockquote></details>

Done.
___
*[pkg/storage/engine/enginepb/mvcc.go, line 236 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42249#-Lt2CQzZ03LMFEbISeDS:-Lt57DuG5BoqDqwwNYuV:b-7y6x4c) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ce593ac63a5c48742f54fb34b7247b58e481be1/pkg/storage/engine/enginepb/mvcc.go#L236)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: do you need `.String()`?
</blockquote></details>

Not it was just a reminder to myself to care about this when implementing SafeMessage underneath. Removed.
___
*[pkg/storage/engine/enginepb/mvcc.go, line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42249#-Lt2D5p19cw7ZxzSYfKY:-Lt57INk44YupYTWbpJT:b-p67q6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ce593ac63a5c48742f54fb34b7247b58e481be1/pkg/storage/engine/enginepb/mvcc.go#L252)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do you have a preference about whether these should be separated by commas or not?
</blockquote></details>

I have a preference for not, until/unless we have a reason (the code is simpler in this way).

**Comment by knz** [comment]
TFYR!

bors r+

**Comment by knz** [comment]
UI unit test flake due to some fluke.

bors r+

**Pull request merged**
