### PR TITLE
vendor: upgrade honnef.co/go/tools

### PR DESCRIPTION
**Pull request by otan**
Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
> Reviewed 36 of 36 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56721)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @otan)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 769 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56721#-MMFObHr4zcpIm34y1Nj:-MMFObHr4zcpIm34y1Nk:b-am60d1) ([raw file](https://github.com/cockroachdb/cockroach/blob/0238317795b082a969e8e96dae3099171ba01079/pkg/sql/opt/memo/statistics_builder.go#L769)):*
> ```Go
> 	}
> 	// Add any not-null columns from the predicate constraints.
> 	for i := range pred {
> ```

The old code couldn't have been some perf optimization, right?

**Comment by otan** [comment]
___
*[pkg/sql/opt/memo/statistics_builder.go, line 769 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56721#-MMFObHr4zcpIm34y1Nj:-MMFQ3xK4CVVbAfjcGk6:b-biuacs) ([raw file](https://github.com/cockroachdb/cockroach/blob/0238317795b082a969e8e96dae3099171ba01079/pkg/sql/opt/memo/statistics_builder.go#L769)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

The old code couldn't have been some perf optimization, right?
</blockquote></details>

i wonder, but i think it'd be somewhat amusing if this pred check was an optimisation

**Comment by tbg** [comment]
I also doubt it, especially without a comment, merge ahead

**Comment by otan** [comment]
yolo try whilst everyone is asleep

bors r=tbg

**Comment by otan** [comment]
bors r=tbg

**Comment by otan** [comment]
noooo vendor conflict
bors r-

**Comment by otan** [comment]
bors r=tbg

**Pull request merged**
