### PR TITLE
roachtest/cdc: fix cdc/kafka-auth

### LINKED ISSUE #118525: roachtest: cdc/kafka-auth failed
roachtest.cdc/kafka-auth [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13762710?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/13762710?buildTab=artifacts#/cdc/kafka-auth) on master @ [ed3a25e3c9459cede2f80babbfc9d44a836b6c12](https://github.com/cockroachdb/cockroach/commits/ed3a25e3c9459cede2f80babbfc9d44a836b6c12):

```
(cdc.go:1079).runCDCKafkaAuth: create changefeed with insecure TLS transport and no auth: pq: kafka: client has run out of available brokers to talk to
(cluster.go:2293).Run: context canceled
test artifacts and logs in: /artifacts/cdc/kafka-auth/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-13762710/cdc-kafka-auth/1706687928530/1706688129083)

</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/kafka-auth.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-35771

### PR DESCRIPTION
**Pull request by wenyihu6**
From [kafka
2.0](https://kafka.apache.org/20/documentation.html#security_confighostname)
onwards, host name verification of servers is enabled by default.

Previously, the self-signed test certificate we generated for kafka-auth only
included “localhost” in the list of subject alternative names. However, kafka
appears to make internal connections using the fully qualified domain name. As a
result, some inter-broker communication has been failing with a hostname
verification error for some time. But the failure wasn’t raised to the user
until the sarama upgrade happened. This patch fixes the failure by adding the
proper hostname of the kafka node to the certificate.

We don’t believe this represents a meaningful customer-facing issue. The
misconfiguration of the test kafka cluster would have surfaced even with older
sarama versions if the test had involved more than just connecting to the kafka
cluster.

Fixes: https://github.com/cockroachdb/cockroach/issues/118525
Release note: none

### CODE REVIEW

**Comment by wenyihu6** [comment]
Possible solutions: 
1. Add hostname to certificates by running hostname -f on the kafka node and adding the hostname to certificates generated.
2. Turn off hostname verification inside kafka using `ssl.endpoint.identification.algorithm`
3. Change our Kakfa configuration to change the inter-broker configuration to use a non TLS listener.
4. Instead of using golang to generate fake certificates, we could try using keytool commands https://kafka.apache.org/20/documentation.html#security_configcerthstname here. 

I tried doing 1, but the test was still failing. The changes I made was here: https://github.com/cockroachdb/cockroach/compare/master...wenyihu6:cockroach:newfixtest?expand=1. I also added log lines and confirmed that DNSNames field was populated correctly. https://github.com/cockroachdb/cockroach/blob/9bcf906cd3bc94190ac4a65d8e6cac2f8e46eddc/pkg/cmd/roachtest/tests/cdc.go#L1775. 

```
hostname is wenyihu-1707708434-01-n1cpu4-0001.c.cockroach-ephemeral.internal
```

Hostname was added to certificate, but we are still getting 
```
Caused by: java.security.cert.CertificateException: No subject alternative DNS name matching wenyihu-1707708434-01-n1cpu4-0001.c.cockroach-ephemeral.internal found.
```

I think we sort of discussed this in our meeting. My guess is that kafka started so many brokers for their inter-communication and might be using a different certificate from the one we passed in here. So I went with the second option here.

**Comment by stevendanna** [comment]
@wenyihu6 Apologies for the delay.  For your attempt to add the host name to the certificate.  

https://github.com/cockroachdb/cockroach/compare/master...wenyihu6:cockroach:newfixtest?expand=1#diff-7276eae775645763129d898332c5c5b40465682ae914ff892ea48d2efe89532aR2354-R2359

Can you try calling `strings.TrimSpace` on the output of the command? I wouldn't be surprised if the output of the command had a newline as it's final character since the hostname was intended for a terminal. That final newline isn't part of the actual hostname.

**Comment by wenyihu6** [comment]
Ahh that fixed it. Thank you!

**Review by stevendanna — COMMENTED** [review]
Nice. I left a couple of nitpicks but nothing major.

Below I've left some commit message suggestions. Take them or leave them.



> This means that the "fake" certificate we generate and use for kafka-auth is no
longer valid and missing the `DNSNames` field. 

Perhaps "The self-signed test certificate we generate for the kafka-auth test previously only included "localhost" in the list of subject alternative names. Kafka appears to make internal connections using the fully qualified domain name. As a result, some inter-broker communication fails with a hostname verification error"

> Test history
> 
> 1. Kafka-auth was working as expected. In this test, we generate and pass "fake"
certificates for inter-broker communication within the Kafka cluster.
> 2. Some changes were made in the java environment or kafka cluster
(https://kafka.apache.org/20/documentation.html#security_confighostname),
resulting in hostname verification which wasn't previously enforced. This means
that the "fake" certificate we generated before is no longer valid and missing
the `DNSNames` field. Since then, we’ve always been getting an error message in
our kafka server logs. But this error was never surfaced up in sarama code
during Dial() AND kafka-auth only checks the success of the CREATE stmt but not
emitting messages. So our test has always been passing.
> 3. Sarama upgrade changed how Dial() works and is now invoking some untouched
kafka code and surfacing the error.

This is partially speculation. I would consider just removing it as I think your preceding paragraph covers the situation nicely: This has been failing for some time, but the failure wasn't raised to the user until the sarama upgrade.

> Overall, this issue pertains to test misconfiguration and not directly
user-facing. But the sarama upgrade may lead to similar issues for customers due
to the wide possibilities of kafka configurations. In this case, we don't think
a release note is necessary because customers should have encountered this error
message. This issue has been around for a while and should be surfaced once the
customer uses anything beyond Dial() - when they try to emit messages to kafka
sink.

I would maybe simplify this to:  We don't believe this represents a meaningful customer-facing issue. The test kafka cluster was misconfigured, which would have likely become obvious even on older sarama versions if the test tried to do more than simply connect to the cluster.

**Comment by wenyihu6** [comment]
Thanks for providing such thorough feedback! Just made the changes, lmk if you have any other comments.

**Comment by wenyihu6** [comment]
*[`pkg/cmd/roachtest/tests/cdc.go` line 1779 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119077#gh-1491063715:-NqhFyf5BV_4ekWW4vp1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/91824e861cb1f772ecfe6fa07b0ef39fe7a1aed0/pkg/cmd/roachtest/tests/cdc.go#L1779)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Might avoid future problems by keeping localhost in this array. We could do something like:

```
append([]string{"localhost"}, dnsNames...)
```
</blockquote></details>

Done.

**Comment by wenyihu6** [comment]
*[`pkg/cmd/roachtest/tests/cdc.go` line 2357 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119077#gh-1491065968:-NqhFzHB9hRe99RdSQB_:b-wyemm3) ([raw file](https://github.com/cockroachdb/cockroach/blob/91824e861cb1f772ecfe6fa07b0ef39fe7a1aed0/pkg/cmd/roachtest/tests/cdc.go#L2357)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

You could probably remove this Printf if you wanted. I leave that to your judgement.

But, if we do keep it, I think we should log the trimmed hostname so that we don't get confused later.
</blockquote></details>

I kept the print stmt for future test failures but updated it to log the trimmed hostname instead.

**Review by stevendanna — APPROVED** [review]

**Comment by wenyihu6** [comment]
Thanks again for the code review and your help with this issue! I learned a lot : ) 

bors r=stevendanna

**Pull request merged**
