### PR TITLE
engine: return ErrNotExist from DeleteFile on Windows

### LINKED ISSUE #32593: IO error: Failed to delete while purging index
**Describe the problem**

We have a 3 node (version 2.1.0) cluster.  One of the nodes (n1) crashed running goroutine 97.  The only databases on the cluster are the system database and the StarTrek database.  No real activity yet.  The crash appeared to occur around 5:00 am during some maintenance routine.

**To Reproduce**

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster (3 nodes.  2 Windows Server 2016 and 1 Debian 9 Linux all on same ESXi host).  The only databases in the cluster are the system database and the Startrek DB.

**Expected behavior**
Node should not crash when trying to purge an index.

**Additional data / screenshots**
The problem is not SQL-related.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

```
C:\ustreem>cockroach start --certs-dir=certs --advertise-host=epu2016srv2 --join=epu2016srv1:26257,epud9srv1:26257
*
* WARNING: [n?] listen address "::" not in node certificate (IP=10.10.30.142; DNS=epu2016srv2; CN=node)
* Secure node-node and SQL connections are likely to fail.
* Consider extending the node certificate or tweak --listen-addr/--advertise-addr.
*
CockroachDB node starting at 2018-11-16 14:13:06.5341643 +0000 UTC (took 10.4s)
build:               CCL v2.1.0 @ 2018/10/30 12:40:27 (go1.10.3)
webui:               https://epu2016srv2:8080
sql:                 postgresql://root@epu2016srv2:26257?sslcert=certs%5Cclient.root.crt&sslkey=certs%5Cclient.root.key&sslmode=verify-full&sslrootcert=certs%5Cca.crt
client flags:        cockroach <client cmd> --host=epu2016srv2:26257 --certs-dir=certs
logs:                C:\ustreem\cockroach-data\logs
temp dir:            C:\ustreem\cockroach-data\cockroach-temp188306383
external I/O path:   C:\ustreem\cockroach-data\extern
store[0]:            path=C:\ustreem\cockroach-data
status:              restarted pre-existing node
clusterID:           223a9c54-4f04-46a0-8cb1-eff7b4f84c42
nodeID:              1
*
* ERROR: [n1,s1,r3/1:/System/NodeLiveness{-Max}] Reported as error b4ac1cb3e78542c5b3eb887375cd99df
*
F181119 11:32:36.364675 97 storage/replica.go:4511  [n1,s1,r3/1:/System/NodeLiveness{-Max}] while purging index %d: while purging index 580532: IO error: Failed to delete: C:\ustreem\cockroach-data\auxiliary\sideloading\3\3.1\i580532.t16: The system cannot find the path specified.
goroutine 97 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc042080d00, 0xc042080de0, 0x36f5900, 0x12)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:997 +0xd6
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x44f7c00, 0xc000000004, 0x36f59bc, 0x12, 0x119f, 0xc047eb03c0, 0xe7)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:864 +0x905
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x28a3140, 0xc04a66d170, 0x4, 0x2, 0x2348fbd, 0x6, 0xc04a2e5c00, 0x2, 0x2)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:85 +0x2ec
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x28a3140, 0xc04a66d170, 0x1, 0x4, 0x2348fbd, 0x6, 0xc04a2e5c00, 0x2, 0x2)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:69 +0x93
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(0x28a3140, 0xc04a66d170, 0x2348fbd, 0x6, 0xc04a2e5c00, 0x2, 0x2)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:172 +0x85
github.com/cockroachdb/cockroach/pkg/storage.fatalOnRaftReadyErr(0x28a3140, 0xc04a66d170, 0x236ec61, 0x16, 0x2878e00, 0xc04bb45420)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:4511 +0x1cd
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRequestQueue.func1(0x28a3140, 0xc04a66d170, 0xc042382e00, 0x28a3140)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3853 +0x17e
github.com/cockroachdb/cockroach/pkg/storage.(*Store).withReplicaForRequest(0xc0424ed080, 0x28a3140, 0xc04a66d170, 0xc04784f380, 0xc04a2e5ed0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3502 +0x13c
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRequestQueue(0xc0424ed080, 0x28a3140, 0xc0429b2090, 0x3)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3840 +0x230
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc042786600, 0x28a3140, 0xc0429b2090)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:225 +0x222
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x28a3140, 0xc0429b2090)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:165 +0x45
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc04232ea20, 0xc0421b34d0, 0xc04232ea10)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:199 +0xf0
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:192 +0xb4


****************************************************************************

This node experienced a fatal error (printed above), and as a result the
process is terminating.

Fatal errors can occur due to faulty hardware (disks, memory, clocks) or a
problem in CockroachDB. With your help, the support team at Cockroach Labs
will try to determine the root cause, recommend next steps, and we can
improve CockroachDB based on your report.

Please submit a crash report by following the instructions here:

    https://github.com/cockroachdb/cockroach/issues/new/choose

If you would rather not post publicly, please contact us directly at:

    support@cockroachlabs.com

The Cockroach Labs team appreciates your feedback.

C:\ustreem>
```

**Environment:**
 - CockroachDB version 2.1.0
 - Server OS: Windows Server 2016
 - Client app: None

**Additional context**
The one node was marked as dead, but the other two nodes continued functioning.

### PR DESCRIPTION
**Pull request by tbg**
Fixes #32593.

Release note (bug fix): Fixed a crash that could occur during or after a
data import on Windows.

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
This is quite ugly.

**Comment by tbg** [comment]
Definitely. Let me know if you think we can do better. But ISTM that RocksDB doesn't even have any useful structure in their IOError:

https://github.com/cockroachdb/rocksdb/blob/0a3db28d98e5f057a732cf0f636d8470fc11ee71/include/rocksdb/status.h#L47-L77

**Comment by tbg** [comment]
bors r=petermattis

**Comment by tim-o** [comment]
Zendesk ticket #[3234](https://cockroachdb.zendesk.com/agent/tickets/3234) has been linked to this issue.

**Pull request merged**
