### PR TITLE
sql: Support CREATE DATABASE WITH SUPER REGION

### PR DESCRIPTION
**Pull request by e-mbrown**
Informs #77454

Release note (sql change): Users can now add a super region when creating a database.

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
thanks for picking this up! could you add tests in `pkg/sql/parser/testdata/create_database` (similar to how there are PRIMARY REGION tests)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93939#-:-NLM_-8T0Dv_xAmnKmPH:b-7xcga2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown)

___
*[`pkg/sql/create_database.go` line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93939#-NLMamf2-zQDrGkVz_ZI:-NLMamf2-zQDrGkVz_ZJ:b-xojknj) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0bd4de20f3587e3892fe2485a73a57a9231ce77/pkg/sql/create_database.go#L191)):*
> ```Go
> 
> func (n *createDatabaseNode) addSuperRegionOnNewDB(params runParams, desc *dbdesc.Mutable) error {
> 	if n.n.SuperRegion.Name != "" {
> ```

can this logic be done inside of `func (p *planner) createDatabase`, either right after `maybeInitializeMultiRegionDatabase` or inside of `maybeInitializeMultiRegionDatabase`?

**Review by e-mbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93939)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/create_database.go` line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/93939#-NLMamf2-zQDrGkVz_ZI:-NLQ4Kkf1rBLcZCEIWs0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d0bd4de20f3587e3892fe2485a73a57a9231ce77/pkg/sql/create_database.go#L191)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

can this logic be done inside of `func (p *planner) createDatabase`, either right after `maybeInitializeMultiRegionDatabase` or inside of `maybeInitializeMultiRegionDatabase`?
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
lgtm! nice

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93939#-:-NLSop79DLEoMYJB9zbC:bef8vlh)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by rafiss — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93939)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @e-mbrown)

___
*[`pkg/sql/create_database.go` line 164 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/93939#-NLSp5Iw0itp1qM9GO9z:-NLSp5Iw0itp1qM9GOA-:bj3f91e) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5fd4a0c0651c35deda0beb761b8154e2dae6bda/pkg/sql/create_database.go#L164)):*
> ```Go
> 	}
> 	if created {
> 		if err := n.addSuperRegionOnNewDB(params, desc); err != nil {
> ```

nit: this should be removed now

**Comment by e-mbrown** [comment]
TFTR! 

bors r=rafiss

**Comment by e-mbrown** [comment]
bors r=rafiss

**Pull request merged**
