### PR TITLE
release-23.1: go.mod: bump Pebble to c03eda9c82d0

### PR DESCRIPTION
**Pull request by jbowens**
```
c03eda9c db: synchronize ingests with flushes of later memtables
11c9b6d0 vfs: mark file basename as safe to avoid log redaction
e599d0d6 vfs: include size of write in DiskSlowInfo
c84aae9e db: allow locking directory before Open
4b0d06ec sstable: print magic number when encountering corruptiona
```

Epic: none
Release note: none
Release justification: low-risk ranges and bug fixes for high severity issues.

### CODE REVIEW

**Review by itsbilal — APPROVED** [review]
LGTM

**Comment by jbowens** [comment]
Looks like there was a backwards-incompatible interface change backported to the release branch. Need to fix it up.

**Review by nicktrav — APPROVED** [review]
LGTM. Apologies for the breaking change. That was me.

**Comment by jbowens** [comment]
no worries, TFTRs!

**Pull request merged**
