### PR TITLE
upgrade grpc to v.1.49.0

### LINKED ISSUE #81881: gossip: TestGossipOrphanedStallDetection failed
gossip.TestGossipOrphanedStallDetection [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/5280563?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/5280563?buildTab=artifacts#/) on master @ [7a17498a9679853612cb88d82a4a3952d1015f94](https://github.com/cockroachdb/cockroach/commits/7a17498a9679853612cb88d82a4a3952d1015f94):

```
=== RUN   TestGossipOrphanedStallDetection
    gossip_test.go:658: condition failed to evaluate within 45s: n2 not yet connected
--- FAIL: TestGossipOrphanedStallDetection (45.17s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
Parameters in this failure:

- TAGS=bazel,gss
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestGossipOrphanedStallDetection.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-16105

### PR DESCRIPTION
**Pull request by pav-kv**
Fixes #81881
Touches #72083

Release note: upgraded grpc to v1.49.0 to fix a few panics that the old version caused

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]
LGTM

**Comment by pavelkalinnikov** [comment]
Failing to build some cloud storage files, same error locally.

**Comment by erikgrinaker** [comment]
>Failing to build some cloud storage files, same error locally.

Did you do `go get` or `go get -u` here when upgrading? The former won't pull in transitive deps unless necessary.

**Comment by pavelkalinnikov** [comment]
I did `-u`, and all per instruction [here](https://github.com/cockroachdb/cockroach/blob/2cbad9139a4a02b426610f776c487d656c256224/build/README.md#working-locally-with-dependencies).

Locally, I can build with `./dev build short`, but `make buildshort` fails with this error.

**Comment by erikgrinaker** [comment]
Well, we have two options: either try without `-u` and hope it won't pull in the breaking dep, or go ask the DR team to upgrade their code first (or do it for them if it's trivial).

**Comment by pavelkalinnikov** [comment]
Trying without `-u`.

**Comment by pavelkalinnikov** [comment]
bors r=erikgrinaker

**Comment by pavelkalinnikov** [comment]
bors retry

**Comment by pavelkalinnikov** [comment]
Someone updated another dependency. Rebased.

**Comment by pavelkalinnikov** [comment]
bors r=erikgrinaker

**Pull request merged**
