### PR TITLE
storage: remove unnecessary ctx annotation

### PR DESCRIPTION
**Pull request by andreimatei**
cc @RaduBerinde

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/replica_range_lease.go, line 445 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16416#-Km92Xon78IiraqdHAaU:-Km92XooZ1ziNsc2JNje:b1f6xut) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e507b4e35dbd5dfda748530d635d13cd29d287d/pkg/storage/replica_range_lease.go#L445)):*
> ```Go
> // same replica. Otherwise, a NotLeaseHolderError is returned.
> func (r *Replica) AdminTransferLease(ctx context.Context, target roachpb.StoreID) error {
> 	// Depending on the caller, the context might not have been annotated by the
> ```

Might be helpful to elaborate on this. Which callers do not annotate the context? Why don't they? Presumably, they could, since they must have a reference to the replica

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16416#-:-Km92MRJ4HERmczqyaUZ:bnfp4nl)*

**Comment by andreimatei** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/replica_range_lease.go, line 445 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16416#-Km92Xon78IiraqdHAaU:-Km93w8S3vjtMGfEtE66:benn9ez) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e507b4e35dbd5dfda748530d635d13cd29d287d/pkg/storage/replica_range_lease.go#L445)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Might be helpful to elaborate on this. Which callers do not annotate the context? Why don't they? Presumably, they could, since they must have a reference to the replica
</blockquote></details>

yeah, I wanted to get y'alls opinion on this. It's the `replicaQueue` that I believe currently doesn't annotate.
The question is generally who should annotate - the caller or the callee? I think I prefer the callee.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16416)*

**Comment by RaduBerinde** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16416#-:-Km95v_22V5zrVezYRdh:bg7igkv)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/replica_range_lease.go, line 445 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16416#-Km92Xon78IiraqdHAaU:-Km9OpPd_lxQVUCBuXHT:btft1is) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e507b4e35dbd5dfda748530d635d13cd29d287d/pkg/storage/replica_range_lease.go#L445)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

yeah, I wanted to get y'alls opinion on this. It's the `replicaQueue` that I believe currently doesn't annotate.
The question is generally who should annotate - the caller or the callee? I think I prefer the callee.
</blockquote></details>

All the queues annotate. See `baseQueue.processReplica`. Probably worth pulling on this a bit more @andreimatei, to see here the unannotated context is coming from. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16416)*

**Comment by andreimatei** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/replica_range_lease.go, line 445 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16416#-Km92Xon78IiraqdHAaU:-Km9hshXZnP8uEjcZbFx:b-3daz6c) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e507b4e35dbd5dfda748530d635d13cd29d287d/pkg/storage/replica_range_lease.go#L445)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

All the queues annotate. See `baseQueue.processReplica`. Probably worth pulling on this a bit more @andreimatei, to see here the unannotated context is coming from. 
</blockquote></details>

Ah, I didn't see `baseQueue`. I was just guessing the context was not annotated because I didn't see code for it. Thanks :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16416)*

**Pull request merged**
