### PR TITLE
colexec: fully support distinct spec

### LINKED ISSUE #61411: colexec: fully support unordered distinct
Currently, the unordered distinct doesn't support the distinct spec in which `NullsAreDistinct` is `true` or `ErrorOnDup` is set. This comes up with UPSERTs.

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexechash: do not template on AllowNullEquality in the hash table**

Previously, we would generate different code based on AllowNullEquality
value. However, for the upcoming work on supporting distinct nulls in
the unordered distinct, it is a big burden to make the templating work
(namely, it would result in a lot of basically duplicated code). This
commit removes the template based on this value which reduces the amount
of the generated code and - to be confirmed - doesn't give us noticeable
performance hit.

Release note: None

**colexecbase: mark distinctChainOps as unexplainable**

`distinctChainOps` is a utility operator that converts a series of
single column distincters into an "ordered distinct" resettable
operator. It is also used by several other components (like ordered
aggregator to know the boundaries of the aggregation groups). This
commit marks this utility operator as "non-explainable", so it'll be
omitted from the EXPLAIN (VEC) diagrams (in non-verbose setting). The
follow up commit will introduce separate `orderedDistinct` operator that
will be "explainable".

Release note: None

**colexec: fully support distinct spec**

This commit adds the remaining support of Distinct spec to the
vectorized engine. Previously, we couldn't support cases when nulls
should be treated as distinct or when an error should be returned when
a duplicate is detected. These cases are needed for UPSERT queries.

This change required some modifications to treat nulls as distinct in
several components (the hash table used by the unordered distinct, sort
partitioners since they are used by the fallback strategy of the
external sort, valuesDiffer used by sort chunks). This commit also
introduced a helper struct to emit an error on duplicates. This also
required some changes to track whether duplicates were detected in
a batch.

Fixes: #61411.

Release note (sql change): Previously, in some special cases (UPSERTs,
as documented by cockroachdb/docs#9922), the
support of the distinct operations was missing in the vectorized
engine. Now it is added, and such operations will be able to spill to
disk if necessary.

**colexec: add a unit test for errorOnDup for distinct operator**

This commit adds some unit tests for `errorOnDup` case of the distinct
operators. That required a bit of plumbing because the expected error is
propagated as a panic, so we augment `RunTests` test harness with
special error handler functions and panic catchers.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
I think this is RFAL. Tagging @michae2 as the main reviewer, but it'd be great if @jordanlewis could take a quick look too.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61582)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2)

___
*[pkg/sql/logictest/testdata/logic_test/unique, line 334 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61582#-MZ_yosx0F42g1J3S9Fl:-MZ_yosx0F42g1J3S9Fm:bvv8q1o) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbf037bb56624b2bf3066f029c230347fb80420d/pkg/sql/logictest/testdata/logic_test/unique#L334)):*
> ```
> # Only rows (9, 9) and (9, -9) are inserted.
> statement ok
> INSERT INTO uniq_partial VALUES (1, 9), (9, 9), (9, 10), (9, -9) ON CONFLICT DO NOTHING
> ```

This change was needed because the order in which rows are inserted is not guaranteed, and with `fakedist-disk` config (when the unordered distinct spills to disk) it was possible for `(9, 10)` to be inserted sometimes.

**Comment by yuzefovich** [comment]
The benchmarks of all packages in `colexec` directory are [here](https://gist.github.com/yuzefovich/0bcc5e01fa00195cca97c475c807d3fa). There are some regressions which I will look into:
```
Distinct/Unordered/hasNulls=true/newTupleProbability=0.100/rows=4096/ordCols=0/type=bytes-24                  56.6MB/s ±11%  51.2MB/s ± 7%   -9.55%  (p=0.001 n=10+9)
ExternalDistinct/spilled=true/ordering=false/newTupleProbability=0.001/rows=65536/ordCols=0/type=bytes-24     74.6MB/s ± 4%  60.6MB/s ±24%  -18.80%  (p=0.001 n=8+10)
Distinct/Unordered/hasNulls=false/newTupleProbability=0.001/rows=262144/ordCols=0/type=bytes-24                182MB/s ±28%   145MB/s ±31%  -20.35%  (p=0.010 n=10+9)
```
but nothing too concerning.

Also it looks like some other unit tests will need to be made deterministic.

**Comment by yuzefovich** [comment]
Fixed a bug in the first commit and made another logic test deterministic. Still need to look into the regression on microbenchmarks (possibly the bug in the first commit is to blame).

**Comment by yuzefovich** [comment]
I reran the benchmarks, and I don't see anything concerning (in some cases I do see an improvement). I believe there is just too much variance for some reason for distinct benchmark of `bytes` type, and I filed #64762 to look into that. So I'm happy with this PR performance-wise.

**Comment by yuzefovich** [comment]
Friendly ping @michae2

**Review by michae2 — COMMENTED** [review]
Ok, I'll TAL :slightly_smiling_face:

> Reviewed 1 of 25 files at r3, 30 of 30 files at r5, 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61582#-:-MblRpfE30wzNLa9uH3i:bel4340)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2)

**Review by michae2 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 30 files at r5, 3 of 3 files at r7, 3 of 3 files at r8, 26 of 26 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61582)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @yuzefovich)

___
*[pkg/sql/colexec/colexecbase/distinct.go, line 154 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/61582#-Mbrlmwl9LZPvMlFVKv2:-Mbrlmwl9LZPvMlFVKv3:bfg3lvp) ([raw file](https://github.com/cockroachdb/cockroach/blob/86666f6553c502c32ae34059754e0f7c062e2833/pkg/sql/colexec/colexecbase/distinct.go#L154)):*
> ```Go
> // (after the distinct operation).
> func (h *UpsertDistinctHelper) MaybeEmitErrorOnDup(origLen, updatedLen int) {
> 	if h.ErrorOnDup != "" && origLen > updatedLen {
> ```

It feels a little weird that a spec-level condition (whether `ErrorOnDup` is an empty string) becomes a batch-level check, but this is so lightweight I can't really complain. And a spec-level implementation (another operator in the chain I suppose) would probably be more expensive anyway.
___
*[pkg/sql/colexec/colexechash/hashtable_tmpl.go, line 159 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/61582#-Mc2qYOc0PcWLNM6iXyC:-Mc2qYOc0PcWLNM6iXyD:b1gqgsm) ([raw file](https://github.com/cockroachdb/cockroach/blob/86666f6553c502c32ae34059754e0f7c062e2833/pkg/sql/colexec/colexechash/hashtable_tmpl.go#L159)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> 				// {{if or (.SelectDistinct) (.ProbingAgainstItself)}}
> 				ht.ProbeScratch.distinct[toCheck] = true
> 				ht.ProbeScratch.GroupID[toCheck] = toCheck + 1
> 				// {{else}}
> 				ht.ProbeScratch.GroupID[toCheck] = 0
> 				// {{end}}
> ```
</details>


Could you explain this section a bit? I understand that this is a short-circuit, since no key is ever going to be equal to this key. And `ht.ProbeScratch.GroupID[toCheck] = 0` makes sense to me (jump straight to the end of the chain). But I don't understand the new assignments. Is `ht.ProbeScratch.distinct[toCheck] = true` fixing a bug? (Perhaps we needed to set `ht.ProbeScratch.differs[toCheck] = true` here before?)
___
*[pkg/sql/logictest/testdata/logic_test/unique, line 334 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61582#-MZ_yosx0F42g1J3S9Fl:-Mbw6DLD4nYyRRaJIab_:b-jlxsw8) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbf037bb56624b2bf3066f029c230347fb80420d/pkg/sql/logictest/testdata/logic_test/unique#L334)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

This change was needed because the order in which rows are inserted is not guaranteed, and with `fakedist-disk` config (when the unordered distinct spills to disk) it was possible for `(9, 10)` to be inserted sometimes.
</blockquote></details>

Thanks for pointing this out. Was there a possibility of out-of-order inserts before this PR? (I'm guessing not, since presumably the test was always passing before this? Or maybe there was, and this PR just increases the possibility?)

This is giving me deja vu. :sweat_smile: Some customers will need the insert order to be guaranteed, due to their ORM or application making assumptions based on the behavior of legacy databases. Especially for statements like `INSERT INTO ... SELECT FROM ... ORDER BY ... ON CONFLICT UPDATE ...` (with or without `LIMIT`). If this is the first time out-of-order insertion is possible, it may trip up some customers, even if the docs explicitly say there is no ordering guarantee.

The scary part for customers is that the behavior is "silent" to them, and nondeterministic as well. After the insert, the table will sometimes have different rows than their application expected, with no errors raised.

I'm not saying we have to change this PR. But I do think we should mention this in the release note. One day soon we may need to add some optional ordering guarantees to insert statements if customers need it or PMs ask for it (speaking from experience :smile_cat:). Hopefully it would be as simple as adding an ordering requirement to a few nodes in the plan.

**Review by yuzefovich — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61582#-:-Mc7i_f83jPdIbBr50qw:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @michae2, and @RaduBerinde)

___
*[pkg/sql/colexec/colexecbase/distinct.go, line 154 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/61582#-Mbrlmwl9LZPvMlFVKv2:-Mc7UiYv5Ry2ZXnaKHAD:b3c93xs) ([raw file](https://github.com/cockroachdb/cockroach/blob/86666f6553c502c32ae34059754e0f7c062e2833/pkg/sql/colexec/colexecbase/distinct.go#L154)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

It feels a little weird that a spec-level condition (whether `ErrorOnDup` is an empty string) becomes a batch-level check, but this is so lightweight I can't really complain. And a spec-level implementation (another operator in the chain I suppose) would probably be more expensive anyway.
</blockquote></details>

I agree that it is a bit weird, and we could template this out. Left a TODO for this.

However, I'm not sure what you mean by a spec-level implementation - like there would be an operator that counts all input tuples and all output tuples, and then emits an error if the latter is smaller than the former? I think it'd be unfortunate performance-wise in case a duplicate is detected early, so having the check at the batch-level makes sense to me. What could be improved is that we could generate different distinct operators for regular and for "error on dup" cases.
___
*[pkg/sql/colexec/colexechash/hashtable_tmpl.go, line 159 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/61582#-Mc2qYOc0PcWLNM6iXyC:-Mc7gJj7-EOLDMZrQ_-b:bom039o) ([raw file](https://github.com/cockroachdb/cockroach/blob/86666f6553c502c32ae34059754e0f7c062e2833/pkg/sql/colexec/colexechash/hashtable_tmpl.go#L159)):*
Huh, I don't remember where this came from lol. I tried debugging it a bit right now to gain some context and added a template comment for future reference, but I can't say I fully understand it atm either.

> Is `ht.ProbeScratch.distinct[toCheck] = true` fixing a bug?

No, I think this part comes from the new use case when "nulls are distinct". Previously, we only supported "nulls are equal", so we never got to this point (`allowNullEquality` is handled above); however, when we treat nulls as distinct, in case of the distinct operator we want to remember the fact that the current probing tuple is distinct.

> Perhaps we needed to set `ht.ProbeScratch.differs[toCheck] = true` here before?

I believe `differs` has different semantics from what we want - `differs` is used to indicate that the probing tuple is different from the current build tuple **and** we need to continue probing the current probing tuple against the next build tuple in the chain (in case there is a hash collision in the build table). However, we don't want such behavior - we already know that the current tuple will be distinct from all tuples in the build table, so we want to mark it as such.

Overall, this code hurts my brain, and at this point I'm the one who wrote most of it. My only hope is that the current extension is the last we need, and if we get this code just right, then we won't have to look at it again :)
___
*[pkg/sql/logictest/testdata/logic_test/unique, line 334 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61582#-MZ_yosx0F42g1J3S9Fl:-Mc7Y5M9-sK_AWMI-Cnd:bu82tk0) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbf037bb56624b2bf3066f029c230347fb80420d/pkg/sql/logictest/testdata/logic_test/unique#L334)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Thanks for pointing this out. Was there a possibility of out-of-order inserts before this PR? (I'm guessing not, since presumably the test was always passing before this? Or maybe there was, and this PR just increases the possibility?)

This is giving me deja vu. :sweat_smile: Some customers will need the insert order to be guaranteed, due to their ORM or application making assumptions based on the behavior of legacy databases. Especially for statements like `INSERT INTO ... SELECT FROM ... ORDER BY ... ON CONFLICT UPDATE ...` (with or without `LIMIT`). If this is the first time out-of-order insertion is possible, it may trip up some customers, even if the docs explicitly say there is no ordering guarantee.

The scary part for customers is that the behavior is "silent" to them, and nondeterministic as well. After the insert, the table will sometimes have different rows than their application expected, with no errors raised.

I'm not saying we have to change this PR. But I do think we should mention this in the release note. One day soon we may need to add some optional ordering guarantees to insert statements if customers need it or PMs ask for it (speaking from experience :smile_cat:). Hopefully it would be as simple as adding an ordering requirement to a few nodes in the plan.
</blockquote></details>

I think it is possible only in `-disk` configs, and previously we didn't actually spill to disk in those configs (the vectorized engine didn't support this case altogether, and in the row-by-row engine we don't have disk spilling for distinct at all). I was confused the first time I saw this behavior, and I asked in slack [here](https://cockroachlabs.slack.com/archives/CJGSARZJR/p1606963773435400). It appears that values from `INSERT` clause are allowed to be actually inserted in an arbitrary order, and `ORDER BY` is actually totally ignored.

I agree that this behavior is totally unintuitive, and I've updated the release note accordingly. I'm curious what other folks think about this behavior, cc @jordanlewis @raduberinde

**Review by michae2 — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r10, 3 of 3 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61582#-:-McIbocTCG2yMPnAH_WP:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @RaduBerinde)

___
*[pkg/sql/colexec/colexecbase/distinct.go, line 154 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/61582#-Mbrlmwl9LZPvMlFVKv2:-McAJ5x3Az_qw0ANMaUc:bj204re) ([raw file](https://github.com/cockroachdb/cockroach/blob/86666f6553c502c32ae34059754e0f7c062e2833/pkg/sql/colexec/colexecbase/distinct.go#L154)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I agree that it is a bit weird, and we could template this out. Left a TODO for this.

However, I'm not sure what you mean by a spec-level implementation - like there would be an operator that counts all input tuples and all output tuples, and then emits an error if the latter is smaller than the former? I think it'd be unfortunate performance-wise in case a duplicate is detected early, so having the check at the batch-level makes sense to me. What could be improved is that we could generate different distinct operators for regular and for "error on dup" cases.
</blockquote></details>

Ah, yes, generating different distinct operators makes more sense than a separate operator. But a TODO is also more than enough!
___
*[pkg/sql/colexec/colexechash/hashtable_tmpl.go, line 159 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/61582#-Mc2qYOc0PcWLNM6iXyC:-McGu2QUDEdV66Nan87X:b-kqm2tz) ([raw file](https://github.com/cockroachdb/cockroach/blob/86666f6553c502c32ae34059754e0f7c062e2833/pkg/sql/colexec/colexechash/hashtable_tmpl.go#L159)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Huh, I don't remember where this came from lol. I tried debugging it a bit right now to gain some context and added a template comment for future reference, but I can't say I fully understand it atm either.

> Is `ht.ProbeScratch.distinct[toCheck] = true` fixing a bug?

No, I think this part comes from the new use case when "nulls are distinct". Previously, we only supported "nulls are equal", so we never got to this point (`allowNullEquality` is handled above); however, when we treat nulls as distinct, in case of the distinct operator we want to remember the fact that the current probing tuple is distinct.

> Perhaps we needed to set `ht.ProbeScratch.differs[toCheck] = true` here before?

I believe `differs` has different semantics from what we want - `differs` is used to indicate that the probing tuple is different from the current build tuple **and** we need to continue probing the current probing tuple against the next build tuple in the chain (in case there is a hash collision in the build table). However, we don't want such behavior - we already know that the current tuple will be distinct from all tuples in the build table, so we want to mark it as such.

Overall, this code hurts my brain, and at this point I'm the one who wrote most of it. My only hope is that the current extension is the last we need, and if we get this code just right, then we won't have to look at it again :)
</blockquote></details>

Thank you for the comment!

Finally, I understand! This is needed because when this is reached from `CheckProbeForDistinct`, this case is the only way for `GroupID` to "fall off" the end of the chain. Normally, when called from `CheckProbeForDistinct` the check will always stop before reaching the end of the chain (because the probe key will at least be equal to itself, if not some other key as well). But when nulls are distinct, probe keys containing null do not equal themselves, and so we need this special case to set them equal to themselves. And then we also need the special case in `_CHECK_BODY` because `differs` is true.
___
*[pkg/sql/logictest/testdata/logic_test/unique, line 334 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61582#-MZ_yosx0F42g1J3S9Fl:-McGr3dn1QAyY8f-J_sU:b-gqqhn9) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbf037bb56624b2bf3066f029c230347fb80420d/pkg/sql/logictest/testdata/logic_test/unique#L334)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I think it is possible only in `-disk` configs, and previously we didn't actually spill to disk in those configs (the vectorized engine didn't support this case altogether, and in the row-by-row engine we don't have disk spilling for distinct at all). I was confused the first time I saw this behavior, and I asked in slack [here](https://cockroachlabs.slack.com/archives/CJGSARZJR/p1606963773435400). It appears that values from `INSERT` clause are allowed to be actually inserted in an arbitrary order, and `ORDER BY` is actually totally ignored.

I agree that this behavior is totally unintuitive, and I've updated the release note accordingly. I'm curious what other folks think about this behavior, cc @jordanlewis @raduberinde 
</blockquote></details>

Thanks for updating the release note. I'm satisfied with that (but glad we're checking with more people).

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61582#-:-McMLp5lBgs6zF23qoiV:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @RaduBerinde)

___
*[pkg/sql/logictest/testdata/logic_test/unique, line 334 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/61582#-MZ_yosx0F42g1J3S9Fl:-McMLQqb71aPmHLzP-hP:bats8cu) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbf037bb56624b2bf3066f029c230347fb80420d/pkg/sql/logictest/testdata/logic_test/unique#L334)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Thanks for updating the release note. I'm satisfied with that (but glad we're checking with more people).
</blockquote></details>

I filed #66570 to track some subtle cases around this. I now think that the problem is a bit smaller than before - namely, that we don't push the required ordering through mutations (it's an open question whether that required ordering exists) and whether we want to preserve the ordering of rows in `VALUES` clauses.

**Pull request merged**
