### PR TITLE
server: fix handleVModule to not return an error and a success message

### PR DESCRIPTION
**Pull request by BramGruneir**

### CODE REVIEW

**Review by tamird — APPROVED** [review]
Do you think this is worth a test? Shouldn't be very difficult. LGTM

**Comment by BramGruneir** [comment]
Bah, hold off on reviewing this.  TrimLeft is the wrong function to use.

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/server/debug.go, line 101 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17824#-KsEmhsqQqAY86aCFN7t:-KsEmhsqQqAY86aCFN7u:bcfndlj) ([raw file](https://github.com/cockroachdb/cockroach/blob/59ec42ccdb3f3f37a270c5a428c6d3a70882c2d0/pkg/server/debug.go#L101)):*
the comment in net/http does say:
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>
>     // RequestURI is the unmodified Request-URI of the
>     // Request-Line (RFC 2616, Section 5.1) as sent by the client
>     // to a server. Usually the URL field should be used instead.
>     // It is an error to set this field in an HTTP client request.
</details>

So it seems good to be using r.URL :+1:

---

*[pkg/server/debug_test.go, line 40 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17824#-KsEmvfR79giAkfc4gwg:-KsEmvfR79giAkfc4gwh:bvd7gk0) ([raw file](https://github.com/cockroachdb/cockroach/blob/7700e31b36eb33137b217759c41670c89f8b880c/pkg/server/debug_test.go#L40)):*
> ```Go
> 		{false, "storage=something", http.StatusForbidden},
> 	} {
> 		t.Run("", func(t *testing.T) {
> ```

consider `fmt.Sprintf("vmodule=%t/%s", vmodule, path)` as the subtest name.

---

*[pkg/server/debug_test.go, line 47 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17824#-KsEnFBH_VYqRXArYjz_:-KsEnFBH_VYqRXArYjza:bau11pj) ([raw file](https://github.com/cockroachdb/cockroach/blob/7700e31b36eb33137b217759c41670c89f8b880c/pkg/server/debug_test.go#L47)):*
> ```Go
> 			}
> 			rr := httptest.NewRecorder()
> 			http.HandlerFunc(handleVModule).ServeHTTP(rr, req)
> ```

Hm, can you help me understand why you don't want to stand up a real server? My guess is that this is also the reason that `.RequestURI` wasn't populated in your tests; you're not using a real http client, so only whatever `http.NewRequest` populates is what you get.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17824)*

**Comment by BramGruneir** [comment]
Ok, good to go.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/server/debug_test.go, line 40 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17824#-KsEmvfR79giAkfc4gwg:-KsEolufukL1nB_fJyZx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7700e31b36eb33137b217759c41670c89f8b880c/pkg/server/debug_test.go#L40)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

consider `fmt.Sprintf("vmodule=%t/%s", vmodule, path)` as the subtest name.
</blockquote></details>

Done.

---

*[pkg/server/debug_test.go, line 47 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17824#-KsEnFBH_VYqRXArYjz_:-KsEonLwimoYHq09wsZh:ba98thf) ([raw file](https://github.com/cockroachdb/cockroach/blob/7700e31b36eb33137b217759c41670c89f8b880c/pkg/server/debug_test.go#L47)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Hm, can you help me understand why you don't want to stand up a real server? My guess is that this is also the reason that `.RequestURI` wasn't populated in your tests; you're not using a real http client, so only whatever `http.NewRequest` populates is what you get.
</blockquote></details>

Just seemed like overkill for the unit test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17824#-:-KsEozVPQp32DzHKO4Y-:b-ux0301)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/server/debug_test.go, line 44 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17824#-KsF5qgHNa3CnNBJ5Y1F:-KsF5qgIvFHOBzspjP2p:ba6l383) ([raw file](https://github.com/cockroachdb/cockroach/blob/a858400999837bf50ca8827089dc3a38c8e38311/pkg/server/debug_test.go#L44)):*
> ```Go
> 		t.Run(fmt.Sprintf("vmodule=%t/%s", tc.vmodule, tc.path), func(t *testing.T) {
> 			ClusterSettings.DebugVModule.Override(tc.vmodule)
> 			req, err := http.NewRequest("GET", vmodulePrefix+tc.path, nil)
> ```

I think you want to use httptest.NewRequest to get the correct behaviour, since you're not using a real http client - see the documentation https://godoc.org/net/http/httptest#NewRequest.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17824#-:-KsF6Fj8HicIDE-knqLy:bnfp4nl)*

**Comment by BramGruneir** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/server/debug_test.go, line 44 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17824#-KsF5qgHNa3CnNBJ5Y1F:-KsFA89TbkMmGQrkTei3:b-8yqsvj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a858400999837bf50ca8827089dc3a38c8e38311/pkg/server/debug_test.go#L44)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I think you want to use httptest.NewRequest to get the correct behaviour, since you're not using a real http client - see the documentation https://godoc.org/net/http/httptest#NewRequest.
</blockquote></details>

Perfect, that fixed the requestURI and simplified the test code a little.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17824)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17824)*

**Pull request merged**
