### PR TITLE
optbuilder: move insert fast path test to optbuilder

### PR DESCRIPTION
**Pull request by msirek**
This commit moves an insert fast path uniqueness check test case involving a volatile expression to a more applicable BuilderTest.

Epic: CRDB-26290
Informs: #58047

Release note: None

### CODE REVIEW

**Review by michae2 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112074)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

**Review by michae2 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112074#-:-NgPDGUtAiHIgZZPqdev:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Review by mgartner — APPROVED** [review]
Thanks for moving this! :lgtm: 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112074#-:-NgPEC8k1NwsD-VpfVSJ:b-801do2)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @msirek)

**Comment by msirek** [comment]
TFTRs!
bors r+

**Pull request merged**
