### PR TITLE
server: Convert the remaining /_status/ endpoints to be provided over gRPC

### PR DESCRIPTION
**Pull request by d4l3k**
Some of the GRPC endpoints can't be converted to protocol buffers currently so this serializes them to JSON and wraps them in a `JSONResponse` message.

See #5530.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6788)

### CODE REVIEW

**Comment by tamird** [comment]
what's the story with grpc-gateway for these endpoints?

<details><summary><i>Previously, d4l3k (Tristan Rice) wrote…</i></summary>
> #### Convert the remaining /\_status/ endpoints to be provided over gRPC
> 
> Some of the GRPC endpoints can't be converted to protocol buffers currently so this serializes them to JSON and wraps them in a `JSONResponse` message.
> 
> 
> 
> See #5530.
> 
> 
> 
</details>


---

Reviewed 5 of 5 files at r1, 3 of 3 files at r2, 3 of 3 files at r3, 4 of 4 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[server/status.go, line 670 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6788#-KI6QeH5xl6DZ1GM7MUi:-KI6QeH5xl6DZ1GM7MUj:657216972) ([raw file](https://github.com/cockroachdb/cockroach/blob/7661efb7a16f1456ad1453f4641535f6dbe70a2f/server/status.go#L670)):*
> ```Go
> // marshalJSONResponse converts an arbitrary value into a JSONResponse protobuf
> // that can be sent via grpc.
> func marshalJSONResponse(value interface{}) (*JSONResponse, error) {
> ```

this unfortunately duplicates code from util. perhaps it's possible avoid that?

---

*[server/status.go, line 540 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6788#-KI6PHHYqmNhqU57PTl3:-KI6PHHYqmNhqU57PTl4:2048686907) ([raw file](https://github.com/cockroachdb/cockroach/blob/baf107ac0be32fa7e92d8607daf7add2ecd13dfb/server/status.go#L540)):*
> ```Go
> 
> // handleStacksLocal handles GET requests for goroutine stack traces.
> func (s *statusServer) handleStacks(w http.ResponseWriter, r *http.Request, ps httprouter.Params) {
> ```

so we're not using grpc-gateway for this?

---

*[server/status.go, line 620 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6788#-KI6PLO-frDbWTQrQEXz:-KI6PLO0fhSKuEnLlhlj:1408188976) ([raw file](https://github.com/cockroachdb/cockroach/blob/30f263e818c11eab2e0e50659b092d78ca861933/server/status.go#L620)):*
> ```Go
> }
> 
> func (s *statusServer) handleMetrics(w http.ResponseWriter, r *http.Request, ps httprouter.Params) {
> ```

no grpc-gateway?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6788#-:-KI6Q3qc-aaLHdt2eain:-6899989)*

**Comment by d4l3k** [comment]
grpc-gateway requires that all of the endpoints be returning protobufs. Since these endpoints don't use protobufs this seemed like the easiest way to maintain previous compatibility with the web requests. I'm happy to convert everything to use protobufs internally/serialize to protobufs but this seemed like the easiest intermediate step.

<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> what's the story with grpc-gateway for these endpoints?
</details>


---

Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[server/status.go, line 670 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6788#-KI6QeH5xl6DZ1GM7MUi:-KI9AtiYEVTgHXUpoOae:1137640390) ([raw file](https://github.com/cockroachdb/cockroach/blob/7661efb7a16f1456ad1453f4641535f6dbe70a2f/server/status.go#L670)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> this unfortunately duplicates code from util. perhaps it's possible avoid that?
</details>
Fixed by adding a MarshalToJSON func in util that are used in both places.

---

*[server/status.go, line 540 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6788#-KI6PHHYqmNhqU57PTl3:-KI96WXy7Uk68I-oJiAQ:160383816) ([raw file](https://github.com/cockroachdb/cockroach/blob/baf107ac0be32fa7e92d8607daf7add2ecd13dfb/server/status.go#L540)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> so we're not using grpc-gateway for this?
</details>
No.

---

*[server/status.go, line 620 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6788#-KI6PLO-frDbWTQrQEXz:-KI96Ym3Mm3c8G1NiIbP:160383816) ([raw file](https://github.com/cockroachdb/cockroach/blob/30f263e818c11eab2e0e50659b092d78ca861933/server/status.go#L620)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> no grpc-gateway?
</details>
No.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6788#-:-KI963RG7CDlFu8bLsZm:-1659400152)*

**Comment by tamird** [comment]
Oh, I didn't notice that you were stripping off the JSONResponse proto before rendering the responses.

:lgtm:

<details><summary><i>Previously, d4l3k (Tristan Rice) wrote…</i></summary>
> grpc-gateway requires that all of the endpoints be returning protobufs. Since these endpoints don't use protobufs this seemed like the easiest way to maintain previous compatibility with the web requests. I'm happy to convert everything to use protobufs internally/serialize to protobufs but this seemed like the easiest intermediate step.
</details>


---

Reviewed 6 of 6 files at r7, 1 of 4 files at r10, 1 of 1 files at r11, 1 of 1 files at r12.
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[util/http.go, line 253 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6788#-KIA8fgf9c5FGGPm2t6c:-KIA8fgf9c5FGGPm2t6d:-771084498) ([raw file](https://github.com/cockroachdb/cockroach/blob/05df0298f7b7308b1237d9313dfc25b83684b44d/util/http.go#L253)):*
> ```Go
> 
> // MarshalToJSON marshals the given value into nicely indented JSON. If the
> // value is an interface it is wrapped in JSONWrapper and then marshalled.
> ```

if it's an interface?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6788#-:-KIA8AUZGw-a_TkhBNs8:1073346117)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r8, 3 of 3 files at r9, 3 of 4 files at r10.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6788)*

**Comment by d4l3k** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[util/http.go, line 253 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6788#-KIA8fgf9c5FGGPm2t6c:-KIDfKJKHeSa89JokKrS:-2046332485) ([raw file](https://github.com/cockroachdb/cockroach/blob/05df0298f7b7308b1237d9313dfc25b83684b44d/util/http.go#L253)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> if it's an interface?
</details>
Whoops, that should be an array or slice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6788)*

**Comment by tamird** [comment]
Reviewed 6 of 6 files at r13, 3 of 3 files at r14, 3 of 3 files at r15, 4 of 4 files at r16, 1 of 1 files at r17, 1 of 1 files at r18.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6788)*

**Pull request merged**
