### PR TITLE
colfetcher: remove a redundant slice

### PR DESCRIPTION
**Pull request by yuzefovich**
Inspired by #42259.

This commit refactors the cFetcher a little in order to remove a slice
of "needed columns". This is done by repurposing the map from ColumnIDs
to ordinals to contain only the needed columns. Note that when the
tracing is enabled, all columns are needed.

Release note: None

### CODE REVIEW

**Review by cucaroach — APPROVED** [review]
:LGTM:  Although I gotta say it seems crazy to me that we don't have a sorted map abstraction that can store the key/value pairs together which results in better access patterns (maybe generics will save us some day).   colIdxMap could be implemented as a slice of {descpb.ColumnIDs, ords} tuples if this is really a performance sensitive area couldn't it?   Although ColumnIDs is an int32 and ords is an int so it wouldn't pack as well (although it could probably be an uint32, 4 billion sounds like a reasonable column limit).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71305#-:-MlV3Su68KITymjwIGrZ:bwadrcf)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Review by jordanlewis — COMMENTED** [review]
This looks good to me, nice idea. But, a lot of tests failed :) Probably, something was not done quite right?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71305#-:-MlX3n3l-955-_Lxz3jQ:b-p3118e)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
This doesn't yet work, and I think I want to clean up more things - hold off on reviewing for now.

**Comment by yuzefovich** [comment]
I'm going to abandon this PR in favor of much larger refactor. The first part is in #71356. My goal is to refactor the cFetcher to only work with the columns that are actually needed which will make many things faster and - hopefully - make the code easier to reason about too. If that idea succeeds, then I imagine that Tommy's concern about not having the sorted map for the ordinals will be at least partially alleviated.

**Pull request closed without merging**
