### PR TITLE
sql: Implement ALTER TABLE from REGIONAL BY TABLE to GLOBAL

### PR DESCRIPTION
**Pull request by ajstorm**
Implement ALTER TABLE ... SET LOCALITY GLOBAL for tables starting as
REGIONAL BY ROW.

Release note (sql change): Implement ALTER TABLE ... SET LOCALITY GLOBAL
for tables starting as REGIONAL BY ROW.

### CODE REVIEW

**Review by arulajmani — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59256)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/sql/alter_table_locality.go, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59256#-MRa84tq-3c0RRyFBVHH:-MRa84tq-3c0RRyFBVHI:baxax0g) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c77671df284281ba24df51d2cbae51258f1d263/pkg/sql/alter_table_locality.go#L80)):*
> ```Go
> 
> func (n *alterTableSetLocalityNode) alterTableLocalityRegionalByTableToGlobal(
> 	params runParams, desc *dbdesc.Immutable,
> ```

nit: Could you please remove these unused parameters from these functions? I know in this case the implementations are coming shortly and they'll use these params, but in general I think its good practice to add these as part of the commit that uses them. 
___
*[pkg/sql/alter_table_locality.go, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59256#-MRaA81G0jhsBjfGk0JA:-MRaA81G0jhsBjfGk0JB:b44j618) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c77671df284281ba24df51d2cbae51258f1d263/pkg/sql/alter_table_locality.go#L83)):*
> ```Go
> ) error {
> 	const operation string = "alter table locality REGIONAL BY TABLE to GLOBAL"
> 	if err := assertIsMultiRegionDatabase(desc, operation); err != nil {
> ```

I would recommend moving a check like this in the Validate method instead. I think this specific check may already be implemented, so we can just get rid of this method call.
___
*[pkg/sql/alter_table_locality.go, line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59256#-MRaCwCuDvj3S4JBmCda:-MRaCwCuDvj3S4JBmCdb:bp4m8j8) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c77671df284281ba24df51d2cbae51258f1d263/pkg/sql/alter_table_locality.go#L86)):*
> ```Go
> 		return err
> 	}
> 	if err := assertCorrectTablePattern(
> ```

I like the idea of this assertion but it seems slightly verbose to construct these nested table locality patterns to pass to the function. I would suggest creating interface methods on `TableDescriptor` like `isRegionalByTable()`, `isGlobalTable()`, and `isRegionalByRow()` and call those here (and in the function below) instead.
___
*[pkg/sql/alter_table_locality.go, line 123 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59256#-MRaEVmH8IpBldMKgWwS:-MRaEVmH8IpBldMKgWwT:b-6v8slx) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c77671df284281ba24df51d2cbae51258f1d263/pkg/sql/alter_table_locality.go#L123)):*
> ```Go
> 	}
> 
> 	// Update the zone configuration
> ```

nit: fullstop
___
*[pkg/sql/region_util.go, line 391 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59256#-MRaEGlhEkiXKWFZtWiL:-MRaEGlhEkiXKWFZtWiM:b-vmmtes) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c77671df284281ba24df51d2cbae51258f1d263/pkg/sql/region_util.go#L391)):*
> ```Go
> // dropZoneConfigForTable drops the zone configuration for a table if one exists.
> func (p *planner) dropZoneConfigForTable(ctx context.Context, name tree.TableName) error {
> 	// TODO(#multiregion): We should check to see if the zone configuration has been updated
> ```

Is there an issue for tracking this?

**Review by otan — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59256)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @arulajmani)

___
*[pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality, line 344 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59256#-MRacFBaDqoaO4SwgJI2:-MRacFBaDqoaO4SwgJI3:b-nz9dt2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e8700f004202347cc4939e66129ed96bef566ba/pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality#L344)):*
> ```
>                                            lease_preferences = '[[+region=ca-central-1]]'
> 
> # drop table and recreate to get back to original state (required because alter from global to
> ```

nit: full sentences preferred
___
*[pkg/sql/alter_table_locality.go, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59256#-MRaA81G0jhsBjfGk0JA:-MRacr5Y1f5a-sdJExJ2:bqnk4rn) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c77671df284281ba24df51d2cbae51258f1d263/pkg/sql/alter_table_locality.go#L83)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I would recommend moving a check like this in the Validate method instead. I think this specific check may already be implemented, so we can just get rid of this method call.
</blockquote></details>

it's worth checking up front though, because validate only runs at the end.
i could run "ALTER TABLE .... LOCALITY GLOBAL" in a no-region db, in which this should be upfront.
___
*[pkg/sql/alter_table_locality.go, line 96 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59256#-MRacgEh1wUhvX2UL73n:-MRacgEh1wUhvX2UL73o:b-12vxev) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e8700f004202347cc4939e66129ed96bef566ba/pkg/sql/alter_table_locality.go#L96)):*
> ```Go
> 	}
> 
> 	// Set LocalityConfig to GLOBAL
> ```

nit: full stop
___
*[pkg/sql/alter_table_locality.go, line 104 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59256#-MRachig3DIai2JUXaZ4:-MRachig3DIai2JUXaZ5:b4boxz8) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e8700f004202347cc4939e66129ed96bef566ba/pkg/sql/alter_table_locality.go#L104)):*
> ```Go
> 
> 	// Validate the new locality before updating the table descriptor.
> 	tableName := tree.MakeTableName(tree.Name(desc.Name), tree.Name(n.tableDesc.GetName()))
> ```

please use `MakeTableNameWithSchema`
___
*[pkg/sql/alter_table_locality.go, line 184 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59256#-MRadDS96aj4YOEjWQ-e:-MRadDS96aj4YOEjWQ-f:b-oa517o) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e8700f004202347cc4939e66129ed96bef566ba/pkg/sql/alter_table_locality.go#L184)):*
> ```Go
> 
> 	// Validate the new locality before updating the table descriptor.
> 	tableName := tree.MakeTableName(tree.Name(desc.Name), tree.Name(n.tableDesc.GetName()))
> ```

(also use MakeTableNameWithSchema here)

**Review by ajstorm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59256)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @otan)

___
*[pkg/sql/alter_table_locality.go, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59256#-MRa84tq-3c0RRyFBVHH:-MRaTaLv-1lF-1WGLWo1:bxc7zxw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c77671df284281ba24df51d2cbae51258f1d263/pkg/sql/alter_table_locality.go#L80)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: Could you please remove these unused parameters from these functions? I know in this case the implementations are coming shortly and they'll use these params, but in general I think its good practice to add these as part of the commit that uses them. 
</blockquote></details>

Sure, but I'll be using them later today or next week at the latest.
___
*[pkg/sql/alter_table_locality.go, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59256#-MRaA81G0jhsBjfGk0JA:-MRaSh2r0rsPoh283guZ:b-rj9ojw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c77671df284281ba24df51d2cbae51258f1d263/pkg/sql/alter_table_locality.go#L83)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

it's worth checking up front though, because validate only runs at the end.
i could run "ALTER TABLE .... LOCALITY GLOBAL" in a no-region db, in which this should be upfront.
</blockquote></details>

In addition to what @otan said, what this check is meant to catch is calls that don't come through the currently envisioned stack.  I know that's not the case today, but if someone starts calling this in a non-envisioned way, we could silently do something bad.
___
*[pkg/sql/region_util.go, line 391 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59256#-MRaEGlhEkiXKWFZtWiL:-MRaTN5iAwP9cwkSRnan:b-lpy3kp) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c77671df284281ba24df51d2cbae51258f1d263/pkg/sql/region_util.go#L391)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Is there an issue for tracking this?
</blockquote></details>

Yup, #57668.  You jonsin' for me including that here with the comment?

**Review by ajstorm — COMMENTED** [review]
I think I've addressed everything.  PTAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59256#-:-MRb1A047s7JnJv5xwUa:b-9uxdvq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @otan)

___
*[pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality, line 344 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59256#-MRacFBaDqoaO4SwgJI2:-MRarQ0P6akR9fK2iBht:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e8700f004202347cc4939e66129ed96bef566ba/pkg/ccl/logictestccl/testdata/logic_test/alter_table_locality#L344)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nit: full sentences preferred
</blockquote></details>

done
___
*[pkg/sql/alter_table_locality.go, line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59256#-MRaCwCuDvj3S4JBmCda:-MRb1-Zm9_i8h4_jd-GX:b-nwuqem) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c77671df284281ba24df51d2cbae51258f1d263/pkg/sql/alter_table_locality.go#L86)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I like the idea of this assertion but it seems slightly verbose to construct these nested table locality patterns to pass to the function. I would suggest creating interface methods on `TableDescriptor` like `isRegionalByTable()`, `isGlobalTable()`, and `isRegionalByRow()` and call those here (and in the function below) instead.
</blockquote></details>

Done.  Thanks for this comment, it's much cleaner now.  If also added a TODO for you, but didn't know if we had an issue number yet.
___
*[pkg/sql/alter_table_locality.go, line 96 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59256#-MRacgEh1wUhvX2UL73n:-MRakAWHC2UDlh-wpG8V:btv90nr) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e8700f004202347cc4939e66129ed96bef566ba/pkg/sql/alter_table_locality.go#L96)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

nit: full stop
</blockquote></details>

I think we need to start a full stop jar.  We can use it to fund the American military budget.
___
*[pkg/sql/alter_table_locality.go, line 104 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59256#-MRachig3DIai2JUXaZ4:-MRaquNTCLW6dQ5w1j5v:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e8700f004202347cc4939e66129ed96bef566ba/pkg/sql/alter_table_locality.go#L104)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

please use `MakeTableNameWithSchema`
</blockquote></details>

Done.
___
*[pkg/sql/alter_table_locality.go, line 184 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59256#-MRadDS96aj4YOEjWQ-e:-MRaqvDK4VKVTkITAQFI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7e8700f004202347cc4939e66129ed96bef566ba/pkg/sql/alter_table_locality.go#L184)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

(also use MakeTableNameWithSchema here)
</blockquote></details>

Done.

**Review by otan — APPROVED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59256)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @otan)

**Review by arulajmani — APPROVED** [review]
A few more full stop nits to brighten up the afternoon, but other than that :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59256#-:-MRf1yBA8icti1RbHCU-:b-a2d0yr)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/sql/alter_table_locality.go, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59256#-MRa84tq-3c0RRyFBVHH:-MRf1IUPBVsepeAOWET3:bkt8n6d) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c77671df284281ba24df51d2cbae51258f1d263/pkg/sql/alter_table_locality.go#L80)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Sure, but I'll be using them later today or next week at the latest.
</blockquote></details>

Yeah, I know this specific case makes my request seem rather pedantic but I think in general we should avoid checking in unused parameters. Your call. 
___
*[pkg/sql/alter_table_locality.go, line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59256#-MRaA81G0jhsBjfGk0JA:-MRezrEf7YKt-wIMACBA:b-bhtgic) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c77671df284281ba24df51d2cbae51258f1d263/pkg/sql/alter_table_locality.go#L83)):*
> i could run "ALTER TABLE .... LOCALITY GLOBAL" in a no-region db, in which this should be upfront.

This is caught in the PlanNode though, is it not? Regardless, I don't feel too strongly about this comment. 
___
*[pkg/sql/alter_table_locality.go, line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59256#-MRaCwCuDvj3S4JBmCda:-MReyAH24WMTgBXP3_Ua:bd3bmcb) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c77671df284281ba24df51d2cbae51258f1d263/pkg/sql/alter_table_locality.go#L86)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Done.  Thanks for this comment, it's much cleaner now.  If also added a TODO for you, but didn't know if we had an issue number yet.
</blockquote></details>

Yeah, I like the way this looks now, thanks for making the change! I don't have an issue yet, but I'll address that TODO as part of my current PR if this goes in before it.
___
*[pkg/sql/region_util.go, line 391 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59256#-MRaEGlhEkiXKWFZtWiL:-MRexqcG4EU7OR3FyO7l:brb0e9i) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c77671df284281ba24df51d2cbae51258f1d263/pkg/sql/region_util.go#L391)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Yup, #57668.  You jonsin' for me including that here with the comment?
</blockquote></details>

Not sure what jonsin' means haha, but FWIW I do find it useful to clean up TODO's while working on an issue if I can just grep for the issue number! 
___
*[pkg/sql/catalog/tabledesc/structured.go, line 4153 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59256#-MRf1w8jDl5VQbp_4-IO:-MRf1w8jDl5VQbp_4-IP:b-12vxev) ([raw file](https://github.com/cockroachdb/cockroach/blob/5898f276144622720e36e8c25b3ec91f620de8a1/pkg/sql/catalog/tabledesc/structured.go#L4153)):*
> ```Go
> }
> 
> // IsLocalityRegionalByRow returns whether or not the table is REGIONAL BY ROW table
> ```

nit: full stop
___
*[pkg/sql/catalog/tabledesc/structured.go, line 4158 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59256#-MRf1sW6CIQwi94jiMQT:-MRf1sW6CIQwi94jiMQU:b-xhhrrt) ([raw file](https://github.com/cockroachdb/cockroach/blob/5898f276144622720e36e8c25b3ec91f620de8a1/pkg/sql/catalog/tabledesc/structured.go#L4158)):*
> ```Go
> }
> 
> // IsLocalityRegionalByTable returns whether or not the table is REGIONAL BY TABLE table
> ```

nit: full stop 
___
*[pkg/sql/catalog/tabledesc/structured.go, line 4159 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59256#-MRey55fAkiYzyzE3mOM:-MRey55fAkiYzyzE3mON:b32vin) ([raw file](https://github.com/cockroachdb/cockroach/blob/5898f276144622720e36e8c25b3ec91f620de8a1/pkg/sql/catalog/tabledesc/structured.go#L4159)):*
> ```Go
> 
> // IsLocalityRegionalByTable returns whether or not the table is REGIONAL BY TABLE table
> // TODO (arulajmani): We can pull out this first check once all multi-region tables contain a LocalityConfig.
> ```

:D
___
*[pkg/sql/catalog/tabledesc/structured.go, line 4165 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/59256#-MRf1uwi2MIvtp3Jor0o:-MRf1uwi2MIvtp3Jor0p:b-12vxev) ([raw file](https://github.com/cockroachdb/cockroach/blob/5898f276144622720e36e8c25b3ec91f620de8a1/pkg/sql/catalog/tabledesc/structured.go#L4165)):*
> ```Go
> }
> 
> // IsLocalityGlobal returns whether or not the table is GLOBAL table
> ```

nit: full stop

**Review by ajstorm — COMMENTED** [review]
TFTR all!

bors r=arulajmani,otan

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59256#-:-MRfsos97SSv8McJDYuj:b-mwwiz8)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, and @otan)

___
*[pkg/sql/alter_table_locality.go, line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59256#-MRa84tq-3c0RRyFBVHH:-MRfrkFrEcPefu_daQ4Z:b-tnja3t) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c77671df284281ba24df51d2cbae51258f1d263/pkg/sql/alter_table_locality.go#L80)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Yeah, I know this specific case makes my request seem rather pedantic but I think in general we should avoid checking in unused parameters. Your call. 
</blockquote></details>

Already removed.  All good.
___
*[pkg/sql/region_util.go, line 391 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59256#-MRaEGlhEkiXKWFZtWiL:-MRfs5LP2L7a3j-KSOIT:b-g64o4x) ([raw file](https://github.com/cockroachdb/cockroach/blob/9c77671df284281ba24df51d2cbae51258f1d263/pkg/sql/region_util.go#L391)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Not sure what jonsin' means haha, but FWIW I do find it useful to clean up TODO's while working on an issue if I can just grep for the issue number! 
</blockquote></details>

https://www.urbandictionary.com/define.php?term=jonesing

I've added the issue number

**Pull request merged**
