### PR TITLE
colexec: inline datum conversion in EncDatumRowsToColVec

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: remove error return parameter for GetDatumToPhysicalFn**

GetDatumToPhysicalFn returns a function for converting a datum of the given
ColumnType to the corresponding Go type. Now the signature of the return
function no longer contains an error since we assume that the conversion
must succeed. If for some reason it fails, a panic will be emitted and will
be caught by the panic-catcher mechanism of the vectorized engine and will
be propagated as an error accordingly.

The removal of the error return parameter seems to give some performance
improvement.

Release note: None

**colexec: inline datum conversion in EncDatumRowsToColVec**

Previously, `EncDatumRowsToColVec` function internally used another
converter function which doesn't get inlined. This commit adjusts the
template to remove one level of funciton "indirection" giving some
performance improvement.

Additionally, this commit reuses infrastructure of `rowsToVec` template
to generate GetDatumToPhysicalFn. This allows us to have the conversion
defined in a single place.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Benchmark of the first commit against master:
```
name                       old time/op    new time/op    delta
Columnarize-16                475µs ± 1%     453µs ± 2%  -4.59%  (p=0.000 n=10+10)
ColumnarizeMaterialize-16     790µs ± 1%     757µs ± 1%  -4.13%  (p=0.000 n=10+9)

name                       old speed      new speed      delta
Columnarize-16              337MB/s ± 1%   353MB/s ± 2%  +4.81%  (p=0.000 n=10+10)
ColumnarizeMaterialize-16   203MB/s ± 1%   211MB/s ± 1%  +4.31%  (p=0.000 n=10+9)

name                       old alloc/op   new alloc/op   delta
Columnarize-16                161kB ± 0%     161kB ± 0%  -0.02%  (p=0.000 n=10+9)
ColumnarizeMaterialize-16     357kB ± 0%     357kB ± 0%  -0.01%  (p=0.000 n=10+10)

name                       old allocs/op  new allocs/op  delta
Columnarize-16                20.0k ± 0%     20.0k ± 0%  -0.00%  (p=0.000 n=9+8)
ColumnarizeMaterialize-16     21.3k ± 0%     21.3k ± 0%  -0.00%  (p=0.046 n=8+10)
```

Benchmark of both commits against master:
```
name                       old time/op    new time/op    delta
Columnarize-16                476µs ± 1%     430µs ± 2%   -9.70%  (p=0.000 n=10+10)
ColumnarizeMaterialize-16     790µs ± 1%     722µs ± 0%   -8.61%  (p=0.000 n=10+10)

name                       old speed      new speed      delta
Columnarize-16              336MB/s ± 1%   372MB/s ± 2%  +10.75%  (p=0.000 n=10+10)
ColumnarizeMaterialize-16   202MB/s ± 1%   222MB/s ± 0%   +9.42%  (p=0.000 n=10+10)

name                       old alloc/op   new alloc/op   delta
Columnarize-16                161kB ± 0%     161kB ± 0%   -0.04%  (p=0.000 n=10+10)
ColumnarizeMaterialize-16     357kB ± 0%     357kB ± 0%   -0.03%  (p=0.000 n=10+10)

name                       old allocs/op  new allocs/op  delta
Columnarize-16                20.0k ± 0%     20.0k ± 0%   -0.00%  (p=0.000 n=9+9)
ColumnarizeMaterialize-16     21.3k ± 0%     21.3k ± 0%   -0.01%  (p=0.000 n=10+10)
```

**Review by asubiotto — COMMENTED** [review]
> Reviewed 12 of 12 files at r1, 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50920)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/utils_tmpl.go, line 36 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50920#-MBcUAkeCkEKi6bLYwzk:-MBcUAkeCkEKi6bLYwzl:b-te99oi) ([raw file](https://github.com/cockroachdb/cockroach/blob/1093ce84fd54110b0350ed74f9ed53309756b45a/pkg/sql/colexec/utils_tmpl.go#L36)):*
> ```Go
> // be caught by the panic-catcher mechanism of the vectorized engine and will
> // be propagated as an error accordingly.
> func GetDatumToPhysicalFn(ct *types.T) func(tree.Datum) interface{} {
> ```

Can you write this using @jordanlewis' template changes?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50920)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/colexec/utils_tmpl.go, line 36 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/50920#-MBcUAkeCkEKi6bLYwzk:-MBeH_Bg8LwukeHtNxaZ:b-j6hfjt) ([raw file](https://github.com/cockroachdb/cockroach/blob/1093ce84fd54110b0350ed74f9ed53309756b45a/pkg/sql/colexec/utils_tmpl.go#L36)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Can you write this using @jordanlewis' template changes?
</blockquote></details>

After taking a quick look, I think new `execgen` is not powerful enough for this template, so probably we can't do it yet, but Jordan would know better.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50920#-:-MBidzaa5cCQu4f7nvMn:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
