### PR TITLE
sql: permit using set-returning functions in render list

### LINKED ISSUE #11215: sql: extract DTable-typed render expressions as cross-join
Assuming here #11214 has been merged.

If the clause `SELECT e` is used and `e` is an expression of type `DTable`, then the query should be transposed to `SELECT * FROM e`. 

Needed to support `SELECT generate_series(...)` and `SELECT unnest(...)`.

Reported in https://github.com/cockroachdb/cockroach/issues/5582#issuecomment-261254147.

### PR DESCRIPTION
**Pull request by jordanlewis**
Using set-returning functions in the render list is now supported, by cross-joining their result with the rest of the query. For example, `SELECT generate_series(1, 2);` will output `1` and `2` in two separate rows.

Resolves #11215.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13140)

### CODE REVIEW

**Comment by knz** [comment]
Very good work. A few nits left.

---

Reviewed 3 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/data_source.go, line 527 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13140#-KbLibGktmTWzOB64oKn:-KbLibGktmTWzOB64oKo:b-ov7ilh) ([raw file](https://github.com/cockroachdb/cockroach/blob/e13d6c5e78c369eb028855e5b01fe87dbf700893/pkg/sql/data_source.go#L527)):*
> ```Go
> 	}
> 	return planDataSource{
> 		info: newSourceInfoForSingleTable(parser.TableName{}, plan.Columns()),
> ```

use `anonymousTable` here.

---

*[pkg/sql/render.go, line 322 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13140#-KbLiuV3Kn6SLBYiTmw3:-KbLiuV3Kn6SLBYiTmw4:badhibd) ([raw file](https://github.com/cockroachdb/cockroach/blob/61d1fdff89ecc63266208eaad174fd9a8f386bcb/pkg/sql/render.go#L322)):*
> ```Go
> 		// it up to the sources list as a cross join with an alias and replace it
> 		// with a star select on that alias.
> 		if len(exprs) == 1 {
> ```

0) extract this code to a separate function to increase legibility

1) Can you add a test to check that `select t.*, u.*, generate_series(1,3), generate_series(1,2) FROM t, u` is equivalent to `select t.*, a.*, b.* from t, u, generate_series(1,3) as a, generate_series(1,2) as b`

2) there's a TODO / follow-up issue missing for handling `select x+generate_series(1,3)` - that's equivalent to `select x+y from generate_series(1,3) as a(y)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13140#-:-KbLkI8WzcMy0RKvTcYQ:b8tize1)*

**Comment by jordanlewis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/data_source.go, line 527 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13140#-KbLibGktmTWzOB64oKn:-KbLldq-MuGBiNFIUkX0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e13d6c5e78c369eb028855e5b01fe87dbf700893/pkg/sql/data_source.go#L527)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

use `anonymousTable` here.
</blockquote></details>

Done.

---

*[pkg/sql/render.go, line 322 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13140#-KbLiuV3Kn6SLBYiTmw3:-KbLya5qywHw7XXTEdNm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/61d1fdff89ecc63266208eaad174fd9a8f386bcb/pkg/sql/render.go#L322)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

0) extract this code to a separate function to increase legibility

1) Can you add a test to check that `select t.*, u.*, generate_series(1,3), generate_series(1,2) FROM t, u` is equivalent to `select t.*, a.*, b.* from t, u, generate_series(1,3) as a, generate_series(1,2) as b`

2) there's a TODO / follow-up issue missing for handling `select x+generate_series(1,3)` - that's equivalent to `select x+y from generate_series(1,3) as a(y)`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13140)*

**Comment by knz** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13140#-:-KbMBiI60D3QxMp-57lj:bnfp4nl)*

**Comment by jordanlewis** [comment]
TFTR!

**Pull request merged**
