### PR TITLE
intentresolver: use caller's context deadline in intent resolution

### PR DESCRIPTION
**Pull request by ajwerner**
Having a single timeout value for all batches sent by a request batcher has
proven problematic. The first commit changes the behavior to respect the latest
deadline for a request in a batch. If any request has no deadline, the batch
uses no deadline. The second commit deadline sets a timeout using the previous
value applied to all batches to asynchronous intent resolution calls.

This change isn't exactly equivalent to the prior behavior for async intent
resolution. In particular, the timeout applies to all of the requests rather than
to individual requests. Given the timeout, this seems reasonable. If we fail
to resolve all of the intents we want to within 30s, something else is probably
wrong or we're doing too much work.

### CODE REVIEW

**Review by nvb — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37103)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/internal/client/requestbatcher/batcher.go, line 442 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37103#-LdHueX94vxrQB80DCz_:-LdHueX94vxrQB80DCza:bl1wq91) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca88a83902f358581b4f87626aa651924e4ba560/pkg/internal/client/requestbatcher/batcher.go#L442)):*
> ```Go
> 
> 	// sendDeadline is the latest deadline reported by a request's context.
> 	// It will be zero valued if any request does not	contain a deadline.
> ```

weird spacing here
___
*[pkg/internal/client/requestbatcher/batcher_test.go, line 329 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37103#-LdHtwfP9PJdXcDRLb0D:-LdHtwfP9PJdXcDRLb0E:busukpk) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa9bc9edc80a92b24990feda76d34e354c0f24fc/pkg/internal/client/requestbatcher/batcher_test.go#L329)):*
> ```Go
> 		// This test attempts to verify that a batch with two requests where one
> 		// carries a timeout leads to the batch being sent without a timeout.
> 		// There is a hazard that the goroutines to do the send to not happen
> ```

"do not happen"

Can we reduce the frequency of this hazard by bumping up the timeout a little bit?
___
*[pkg/internal/client/requestbatcher/batcher_test.go, line 347 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37103#-LdHuJ8BAVvCjiIZZRhg:-LdHuJ8BAVvCjiIZZRhh:b-wljn6p) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa9bc9edc80a92b24990feda76d34e354c0f24fc/pkg/internal/client/requestbatcher/batcher_test.go#L347)):*
> ```Go
> 			s.respChan <- batchResp{}
> 		case <-ctx1.Done():
> 			return
> ```

Is this the hazard? If so, let's leave a `t.Log` so that we have at least a minor chance of catching any regression in the test.

EDIT from r2: yes it looks like it is.
___
*[pkg/storage/intentresolver/intent_resolver.go, line 59 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37103#-LdHv4w37zFJUgt2-W2E:-LdHv4w37zFJUgt2-W2F:bq4ulgb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca88a83902f358581b4f87626aa651924e4ba560/pkg/storage/intentresolver/intent_resolver.go#L59)):*
> ```Go
> 
> 	// asyncIntentResolutionTimeout is the timeout when processing a group of
> 	// intents asynchronously. The timeout prevents intent async intent
> ```

"intent async intent"
___
*[pkg/storage/intentresolver/intent_resolver.go, line 207 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37103#-LdHvMYV9dx77WdGwIep:-LdHvMYV9dx77WdGwIeq:b-i7leh2) ([raw file](https://github.com/cockroachdb/cockroach/blob/d386a157a1ab1f75cb014e66043d2eea641218d7/pkg/storage/intentresolver/intent_resolver.go#L207)):*
> ```Go
> 		Stopper:         c.Stopper,
> 		Sender:          c.DB.NonTransactionalSender(),
> 		BatchTimeout:    gcTimeout,
> ```

Does this build after the first commit? If not, we should fix that. Having a failing build, even in intermediate commits, can mess up git bisects.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37103)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/internal/client/requestbatcher/batcher_test.go, line 329 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37103#-LdHtwfP9PJdXcDRLb0D:-LdJXXuJDo1Mi9DYLuwb:b-3lz3u) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa9bc9edc80a92b24990feda76d34e354c0f24fc/pkg/internal/client/requestbatcher/batcher_test.go#L329)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

"do not happen"

Can we reduce the frequency of this hazard by bumping up the timeout a little bit?
</blockquote></details>

Sure done.
___
*[pkg/internal/client/requestbatcher/batcher_test.go, line 347 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37103#-LdHuJ8BAVvCjiIZZRhg:-LdJX_tSDubPrmwG58UP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa9bc9edc80a92b24990feda76d34e354c0f24fc/pkg/internal/client/requestbatcher/batcher_test.go#L347)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this the hazard? If so, let's leave a `t.Log` so that we have at least a minor chance of catching any regression in the test.

EDIT from r2: yes it looks like it is.
</blockquote></details>

Done.
___
*[pkg/storage/intentresolver/intent_resolver.go, line 207 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37103#-LdHvMYV9dx77WdGwIep:-LdJXe2f8ws-Z5D0XAg1:b-o1pgck) ([raw file](https://github.com/cockroachdb/cockroach/blob/d386a157a1ab1f75cb014e66043d2eea641218d7/pkg/storage/intentresolver/intent_resolver.go#L207)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Does this build after the first commit? If not, we should fix that. Having a failing build, even in intermediate commits, can mess up git bisects.
</blockquote></details>

Fixed to remove the setting in the first commit.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37103#-:-LdKmS508nL5ORPDRvnV:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

**Comment by ajwerner** [comment]
bors r=nvanbenschoten

**Pull request merged**
