### PR TITLE
sql: add final projection during physical plan's finalization

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit updates the contract between `DistSQLReceiver` and
`FinalizePlan` method so that the latter adds a projection which allows
the DistSQL receiver to get the rows with the desired schema. This
shouldn't have any effect on the performance, but it seems like a
cleaner approach.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50973#-:-MBUaSsS3KLaRmPun3is:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/distsql_physical_planner.go, line 3394 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50973#-MBUa9G_4d4lZmtbNB3y:-MBUa9G_4d4lZmtbNB3z:b-ducxh3) ([raw file](https://github.com/cockroachdb/cockroach/blob/836b50b04c2b0e9fcc63d03f9cb7fc06b4c0fa6f/pkg/sql/distsql_physical_planner.go#L3394)):*
> ```Go
> 	// Add a final projection so that DistSQLReceiver gets the rows of the
> 	// desired schema. Note that we don't need to update PlanToStreamColMap
> 	// since it is no longer necessary.
> ```

[nit] maybe set `PlanToStreamColMap` to `nil` just in case

**Review by yuzefovich — COMMENTED** [review]
I had to make several changes to fix a few things, so I'd appreciate another quick look before merging this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50973#-:-MBa7fSpA8XjBflY0KiG:bfjsriy)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @pbardea)

___
*[pkg/sql/distsql_physical_planner.go, line 3394 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50973#-MBUa9G_4d4lZmtbNB3y:-MBa7_zeEXffcNv6RODQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/836b50b04c2b0e9fcc63d03f9cb7fc06b4c0fa6f/pkg/sql/distsql_physical_planner.go#L3394)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] maybe set `PlanToStreamColMap` to `nil` just in case
</blockquote></details>

Done.

**Review by RaduBerinde — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50973#-:-MBaEr3aDImGqt39-9UY:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @pbardea)

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50973#-:-MBaF5ZwCKnQRvlvOAIx:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @pbardea)

**Pull request merged**
