### PR TITLE
datapathutils: extract TestDataPath and RewritableDataPath into new pkg

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit extracts `testutils.TestDataPath` and
`testutils.RewritableDataPath` into a new `testutils/datapathutils` package. This is needed in order to break an upcoming import cycle when we add dependency on `sql/catalog/fetchpb` into `roachpb`.

Epic: None

Release note: None

### CODE REVIEW

**Review by srosenberg — COMMENTED** [review]
`TestLogic_distsql_enum` failed; is this a flake or related?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94347#-:-NKQsbiu1vu5oKuPAyNI:b-8915wt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @smg260)

**Comment by yuzefovich** [comment]
A flake, I had a speculative fix in #94350.

**Review by srosenberg — APPROVED** [review]
:lgtm:

I took only a quick (sanity) pass. CI is green, and these changes were (likely) mechanized.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94347#-:-NKQyYPzAUkpVn7OiLMc:b-w28wf7)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @herkolategan and @smg260)

**Comment by yuzefovich** [comment]
Indeed, fully mechanical change.

TFTR!

bors r+

**Pull request merged**
