### PR TITLE
colexec: add external sort

### LINKED ISSUE #42409: colexec: get started with a dummy (in-memory) on-disk sorter
This issue is dependent on figuring out an interface for the use of partitions on disk as outlined in #42407. Once we have that interface, we can proceed to start implementing what an on-disk sort strategy would be without actually having any disk spilling with an in-memory implementation of the partitioned queue interface that would then be later switched out for an on-disk implementation.

This would allow us to write the sort strategy and tests without having the partitioned queue interface ready. This could also inform how #42408 is implemented.

### PR DESCRIPTION
**Pull request by yuzefovich**
**execinfra: minor refactor of getting working memory limit**

This commit introduces a helper method for getting the working memory
limit in bytes from a combination of testing knobs and a cluster
setting.

Release note: None

**colexec: add simple implementation of an external sort**

This commit adds a simple implementation of external sort that works
in two stages:
1. it will use a combination of a newly introduced input partitioner
and in-memory sorter to divide up all batches from the input into
partitions, sort each partition in memory, and write sorted partitions
to disk
2. it will use OrderedSynchronizer to merge the partitions.

Closes: #42409.

Release note: None

**colexec: refactor all spooler to not require allocator when exporting**

This commit modifies 'spooler' interface to add a method that allows
accessing spooled tuples as "windowed batches" so that when exporting
buffered tuples an allocator is not required and no copying is not
necessary. Instead, windowed batches are returned which are safe to use
until the next call and need to be copied somewhere else. Such behavior
is acceptable because these batches will be spilled to disk.

Release note: None

**cmd: increase timeout and make TESTS regex more specific in pull-request-make**

This commit increases the timeout from 5 to 10 minutes (I ran into
a situation where the CI `testrace` was timing out). Also, it adds `$$`
symbols to the end of each test so that full length matching occurred
instead of prefix matching (e.g. `TestSort` also matches
`TestSortedDistinct` which could be not modified in the PR to run
`testrace` for).

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
First three commits are in separate PRs which should be merged first (#43822 and #43834), and I don't see any other low hanging fruit in terms of improving the performance of the external sort.

Here are the current benchmarks:
```
BenchmarkExternalSort/rows=2048/cols=1/spilled=false-16         	   43872	     25683 ns/op	 637.94 MB/s
BenchmarkExternalSort/rows=2048/cols=1/spilled=true-16          	    8649	    145529 ns/op	 112.58 MB/s
BenchmarkExternalSort/rows=2048/cols=2/spilled=false-16         	    6403	    162593 ns/op	 201.53 MB/s
BenchmarkExternalSort/rows=2048/cols=2/spilled=true-16          	    3396	    343119 ns/op	  95.50 MB/s
BenchmarkExternalSort/rows=2048/cols=4/spilled=false-16         	    5002	    241202 ns/op	 271.71 MB/s
BenchmarkExternalSort/rows=2048/cols=4/spilled=true-16          	    2325	    510937 ns/op	 128.27 MB/s
BenchmarkExternalSort/rows=16384/cols=1/spilled=false-16        	    5745	    193377 ns/op	 677.80 MB/s
BenchmarkExternalSort/rows=16384/cols=1/spilled=true-16         	    1074	   1088140 ns/op	 120.46 MB/s
BenchmarkExternalSort/rows=16384/cols=2/spilled=false-16        	     812	   1392241 ns/op	 188.29 MB/s
BenchmarkExternalSort/rows=16384/cols=2/spilled=true-16         	     399	   3011356 ns/op	  87.05 MB/s
BenchmarkExternalSort/rows=16384/cols=4/spilled=false-16        	     583	   1978698 ns/op	 264.97 MB/s
BenchmarkExternalSort/rows=16384/cols=4/spilled=true-16         	     270	   4435968 ns/op	 118.19 MB/s
BenchmarkExternalSort/rows=262144/cols=1/spilled=false-16       	     364	   3450197 ns/op	 607.84 MB/s
BenchmarkExternalSort/rows=262144/cols=1/spilled=true-16        	      61	  18272551 ns/op	 114.77 MB/s
BenchmarkExternalSort/rows=262144/cols=2/spilled=false-16       	      46	  25273556 ns/op	 165.96 MB/s
BenchmarkExternalSort/rows=262144/cols=2/spilled=true-16        	      25	  45849850 ns/op	  91.48 MB/s
BenchmarkExternalSort/rows=262144/cols=4/spilled=false-16       	      33	  37037708 ns/op	 226.49 MB/s
BenchmarkExternalSort/rows=262144/cols=4/spilled=true-16        	      16	  65720895 ns/op	 127.64 MB/s
```
The majority of the time is spend in either sorting or merging.
screencapture-file-private-var-folders-9s-y2m91fyd5vj09d19mf4g8p6w0000gp-T-pprof001-svg-2020-01-08-20_28_51

**Comment by asubiotto** [comment]
I think I've taken a look at all PR dependencies, is that right? Let me know when those are merged and this is RFAL.

**Comment by yuzefovich** [comment]
The dependencies have been merged, and I rebased this PR, so it is RFAL.

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, 7 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43786)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/execplan.go, line 791 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43786#-LydYex1BSQ2aN6Iy4h6:-LydYex1BSQ2aN6Iy4h7:b-vsde17) ([raw file](https://github.com/cockroachdb/cockroach/blob/bad32cf0ce6163e5b37fbe2e1de462770bcb6fd9/pkg/sql/colexec/execplan.go#L791)):*
> ```Go
> 					diskSpillerMemAccount = streamingMemAccount
> 				} else {
> 					diskSpillerMemAccount = result.createBufferingUnlimitedMemAccount(
> ```

Add a comment about why it's an unlimited account
___
*[pkg/sql/colexec/execplan.go, line 800 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43786#-Lydd7xNBHflZsEW6962:-Lydd7xNBHflZsEW6963:b2dhj5z) ([raw file](https://github.com/cockroachdb/cockroach/blob/bad32cf0ce6163e5b37fbe2e1de462770bcb6fd9/pkg/sql/colexec/execplan.go#L800)):*
> ```Go
> 					input, inMemorySorter.(bufferingInMemoryOperator),
> 					sorterMemMonitorName,
> 					func(input Operator) Operator {
> ```

I don't think we should actually create this in-memory external sorter on master, it should currently only be enabled for tests until we add the `Partition`er
___
*[pkg/sql/colexec/external_sort.go, line 24 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43786#-Ly_x30-2q6pX0cahf5K:-Ly_x30-2q6pX0cahf5L:bvz1nfe) ([raw file](https://github.com/cockroachdb/cockroach/blob/bad32cf0ce6163e5b37fbe2e1de462770bcb6fd9/pkg/sql/colexec/external_sort.go#L24)):*
> ```Go
> 
> // Queue is the abstraction for on-disk storage.
> type Queue interface {
> ```

I think you should use the `Partitioner` interface we created in that issue, since I'll need to write an implementation that manages open file descriptors across queues.
___
*[pkg/sql/colexec/external_sort.go, line 57 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43786#-LydZQxj8dFSNzarqurb:-LydZQxj8dFSNzarqurc:b-1er1jf) ([raw file](https://github.com/cockroachdb/cockroach/blob/bad32cf0ce6163e5b37fbe2e1de462770bcb6fd9/pkg/sql/colexec/external_sort.go#L57)):*
> ```Go
> )
> 
> // externalSorter is an Operator that performs external merge sort. It works in
> ```

Love the detailed comments!
___
*[pkg/sql/colexec/external_sort.go, line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43786#-LydZYIm-2nfjR05Nw-l:-LydZYIm-2nfjR05Nw-m:b6n9q36) ([raw file](https://github.com/cockroachdb/cockroach/blob/bad32cf0ce6163e5b37fbe2e1de462770bcb6fd9/pkg/sql/colexec/external_sort.go#L63)):*
> ```Go
> // memory, and write sorted partitions to disk
> // 2. it will use OrderedSynchronizer to merge the partitions.
> // TODO(yuzefovich): we probably want to have a maximum number of partitions at
> ```

I think you already know this given the comment, but to be clear: the maximum number of partitions is to be determined by how much work memory is available. I can't remember off the top of my head, but each partition will have a maximum amount of memory used at any one point (it's a configuration parameter). Since we need to read from all partitions to perform a merge sort, the maximum number of partitions should be: `work memory/amount of memory used per queue`. If we don't reach the end of the input by the time we have reached that number of partitions, we should pause reading from the input and perform a merge sort of all the current partitions we have and write the output to a single, new partition. This is the "recursive" partitioning I was talking about. As we discussed, I don't think it's a requirement to merge this PR, but we will probably need that behavior at some point.
___
*[pkg/sql/colexec/external_sort.go, line 114 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43786#-LyddJbl3eNnssgsdo6I:-LyddJbl3eNnssgsdo6J:b4aftkl) ([raw file](https://github.com/cockroachdb/cockroach/blob/bad32cf0ce6163e5b37fbe2e1de462770bcb6fd9/pkg/sql/colexec/external_sort.go#L114)):*
> ```Go
> 
> // newExternalSorter returns a disk-backed general sort operator.
> // - inMemSorterUnlimitedAllocator must have been created with a memory account
> ```

I'm unsure we need this many monitors. I'd like to talk offline about this just to be able to wrap my head around these.
___
*[pkg/sql/colexec/external_sort.go, line 156 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43786#-Lydg0IL3OJ3oYauJhbw:-Lydg0IM0ddJCX_ERUCg:b-cvqss9) ([raw file](https://github.com/cockroachdb/cockroach/blob/bad32cf0ce6163e5b37fbe2e1de462770bcb6fd9/pkg/sql/colexec/external_sort.go#L156)):*
> ```Go
> }
> 
> func (s *externalSorter) Next(ctx context.Context) coldata.Batch {
> ```

This is very elegant and easy to read, well done
___
*[pkg/sql/colexec/external_sort.go, line 298 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43786#-LydiIt58_IRQljbBVBd:-LydiIt58_IRQljbBVBe:b-5bpb7k) ([raw file](https://github.com/cockroachdb/cockroach/blob/bad32cf0ce6163e5b37fbe2e1de462770bcb6fd9/pkg/sql/colexec/external_sort.go#L298)):*
> ```Go
> 
> func (q *queueToOperator) Next(context.Context) coldata.Batch {
> 	b, err := q.queue.Dequeue()
> ```

One thing we might want to do here is to `Close` the queue once there are no more elements, this will relieve disk space pressure and keep open file descriptors to a minimal level. I think this might be part of what I do when writing the `Partitioner` though, so I think it's fine as is as well.
___
*[pkg/sql/colexec/external_sort_test.go, line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43786#-LydiicL8YMsPm9Og7Oy:-LydiicL8YMsPm9Og7Oz:bf8n0ip) ([raw file](https://github.com/cockroachdb/cockroach/blob/bad32cf0ce6163e5b37fbe2e1de462770bcb6fd9/pkg/sql/colexec/external_sort_test.go#L97)):*
> ```Go
> 	nTups := int(coldata.BatchSize()*4 + 1)
> 	maxCols := 3
> 	// TODO(yuzefovich): randomize types as well.
> ```

Just a note that this TODO is still here.
___
*[pkg/sql/colexec/sort.go, line 255 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43786#-LydkcBCDsJZyCdQFGWN:-LydkcBCDsJZyCdQFGWO:b-vv6n5p) ([raw file](https://github.com/cockroachdb/cockroach/blob/bad32cf0ce6163e5b37fbe2e1de462770bcb6fd9/pkg/sql/colexec/sort.go#L255)):*
> ```Go
> 		}
> 		if p.output == nil {
> 			p.output = p.allocator.NewMemBatch(p.inputTypes)
> ```

Maybe export these couple of lines to a small helper function
___
*[pkg/sql/colexec/sort_test.go, line 165 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43786#-Lydkq781xMZK-fHECRs:-Lydkq781xMZK-fHECRt:b-xn09nq) ([raw file](https://github.com/cockroachdb/cockroach/blob/bad32cf0ce6163e5b37fbe2e1de462770bcb6fd9/pkg/sql/colexec/sort_test.go#L165)):*
> ```Go
> 	k := uint16(rng.Intn(nTups)) + 1
> 	maxCols := 3
> 	// TODO(yuzefovich): randomize types as well.
> ```

Didn't realize this TODO was here as well. Should we address this?
___
*[pkg/sql/distsql/columnar_operators_test.go, line 141 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43786#-LydlTAX0WYFB6OA9_DG:-LydlTAX0WYFB6OA9_DH:b-6mvlrs) ([raw file](https://github.com/cockroachdb/cockroach/blob/bad32cf0ce6163e5b37fbe2e1de462770bcb6fd9/pkg/sql/distsql/columnar_operators_test.go#L141)):*
> ```Go
> 	// - 30720 - the in-memory sorter will hit the memory limit after spooling
> 	//   several batches, so the external sort will take over.
> 	for _, memoryLimit := range []int64{0, 3 * mon.DefaultPoolAllocationSize} {
> ```

Do we want to use 1 here instead? Maybe we should add some way to verify that an external sort actually spilled
___
*[pkg/sql/distsql/columnar_utils_test.go, line 101 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43786#-LydmXdo-aryjQeIRDP6:-LydmXdo-aryjQeIRDP7:bli92zm) ([raw file](https://github.com/cockroachdb/cockroach/blob/bad32cf0ce6163e5b37fbe2e1de462770bcb6fd9/pkg/sql/distsql/columnar_utils_test.go#L101)):*
> ```Go
> 		// "real-world" scenario of creating separate memory accounts. This is
> 		// needed to trigger spilling to disk.
> 		UseStreamingMemAccountForBuffering: memoryLimit == 0,
> ```

I can't remember what this knob was used for. Could you add a comment to the args that explains what the different scenarios are?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43786)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/execplan.go, line 791 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43786#-LydYex1BSQ2aN6Iy4h6:-LygW9qkAoDwWvE_JIVe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bad32cf0ce6163e5b37fbe2e1de462770bcb6fd9/pkg/sql/colexec/execplan.go#L791)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Add a comment about why it's an unlimited account
</blockquote></details>

Done.
___
*[pkg/sql/colexec/execplan.go, line 800 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43786#-Lydd7xNBHflZsEW6962:-LygWAyvCBNsjR6CZIry:bg4sliw) ([raw file](https://github.com/cockroachdb/cockroach/blob/bad32cf0ce6163e5b37fbe2e1de462770bcb6fd9/pkg/sql/colexec/execplan.go#L800)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I don't think we should actually create this in-memory external sorter on master, it should currently only be enabled for tests until we add the `Partition`er
</blockquote></details>

I think it is ok as is because we still have `result.Streaming == false` meaning this disk spilling infrastructure is used only with `experimental_on` and `experimental_always`.
___
*[pkg/sql/colexec/external_sort.go, line 24 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43786#-Ly_x30-2q6pX0cahf5K:-LygWOmH36Oiqt0yLxeJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bad32cf0ce6163e5b37fbe2e1de462770bcb6fd9/pkg/sql/colexec/external_sort.go#L24)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think you should use the `Partitioner` interface we created in that issue, since I'll need to write an implementation that manages open file descriptors across queues.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/external_sort.go, line 57 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43786#-LydZQxj8dFSNzarqurb:-LygWQFb3h8DbQ0rS3em:bbuk57q) ([raw file](https://github.com/cockroachdb/cockroach/blob/bad32cf0ce6163e5b37fbe2e1de462770bcb6fd9/pkg/sql/colexec/external_sort.go#L57)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Love the detailed comments!
</blockquote></details>

:awthanks:
___
*[pkg/sql/colexec/external_sort.go, line 63 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43786#-LydZYIm-2nfjR05Nw-l:-LygW_cr6QqhLKzXnieE:beifk9j) ([raw file](https://github.com/cockroachdb/cockroach/blob/bad32cf0ce6163e5b37fbe2e1de462770bcb6fd9/pkg/sql/colexec/external_sort.go#L63)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think you already know this given the comment, but to be clear: the maximum number of partitions is to be determined by how much work memory is available. I can't remember off the top of my head, but each partition will have a maximum amount of memory used at any one point (it's a configuration parameter). Since we need to read from all partitions to perform a merge sort, the maximum number of partitions should be: `work memory/amount of memory used per queue`. If we don't reach the end of the input by the time we have reached that number of partitions, we should pause reading from the input and perform a merge sort of all the current partitions we have and write the output to a single, new partition. This is the "recursive" partitioning I was talking about. As we discussed, I don't think it's a requirement to merge this PR, but we will probably need that behavior at some point.
</blockquote></details>

Yeah, this belongs in the follow up work.

I think I also had a different model about this: I imagined that we can create as many partitions as we want, but we might not be able to read from all of them at the same time due to memory / number of files restrictions. I thought then we would have several layers of "mergers":
```
//   | partition1     partition2 ... partitionN-1 partitionN 
//   |     |              |              |            |
//   |     ↓              ↓              ↓            ↓
//   |         merger1           ...         mergerM
//   |           |                              |
//   |           ↓                              ↓
//   |                      final merger            
```
(The intermediate mergers would write to separate partitions).

But I see your point about "merging-as-we-go". We can decide later which way to go (I think it'll be fairly easy to add either).
___
*[pkg/sql/colexec/external_sort.go, line 114 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43786#-LyddJbl3eNnssgsdo6I:-Lyg_69BC5sDl2mvSCOD:b-ddbvkv) ([raw file](https://github.com/cockroachdb/cockroach/blob/bad32cf0ce6163e5b37fbe2e1de462770bcb6fd9/pkg/sql/colexec/external_sort.go#L114)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I'm unsure we need this many monitors. I'd like to talk offline about this just to be able to wrap my head around these.
</blockquote></details>

I removed one of the allocators - I realized that `inMemSorter` and `merger` unlimited allocators are used in different states of the external sort, so we can "combine" them.
___
*[pkg/sql/colexec/external_sort.go, line 298 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43786#-LydiIt58_IRQljbBVBd:-Lyg_Vo06n232CBaQI7a:b-3a548w) ([raw file](https://github.com/cockroachdb/cockroach/blob/bad32cf0ce6163e5b37fbe2e1de462770bcb6fd9/pkg/sql/colexec/external_sort.go#L298)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

One thing we might want to do here is to `Close` the queue once there are no more elements, this will relieve disk space pressure and keep open file descriptors to a minimal level. I think this might be part of what I do when writing the `Partitioner` though, so I think it's fine as is as well.
</blockquote></details>

I agree that it should be up to the `Partitioner` to do so.
___
*[pkg/sql/colexec/external_sort_test.go, line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43786#-LydiicL8YMsPm9Og7Oy:-Lyf9jHTDHhNVnaHpvGC:bwiluo7) ([raw file](https://github.com/cockroachdb/cockroach/blob/bad32cf0ce6163e5b37fbe2e1de462770bcb6fd9/pkg/sql/colexec/external_sort_test.go#L97)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Just a note that this TODO is still here.
</blockquote></details>

This was copied from `TestSortRandomized`. We have `TestSorterAgainstProcessor` which randomizes types which I think gives us sufficient coverage.

I opened an issue (#44044) as a reminder to address TODOs of this kind before the release since we have quite a few of these.
___
*[pkg/sql/colexec/sort.go, line 255 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43786#-LydkcBCDsJZyCdQFGWN:-LygVElEAjj-FuFaY8z9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bad32cf0ce6163e5b37fbe2e1de462770bcb6fd9/pkg/sql/colexec/sort.go#L255)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Maybe export these couple of lines to a small helper function
</blockquote></details>

Done.
___
*[pkg/sql/colexec/sort_test.go, line 165 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43786#-Lydkq781xMZK-fHECRs:-LygVGnQ5w8ab0frT-9T:b-8ubzc6) ([raw file](https://github.com/cockroachdb/cockroach/blob/bad32cf0ce6163e5b37fbe2e1de462770bcb6fd9/pkg/sql/colexec/sort_test.go#L165)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Didn't realize this TODO was here as well. Should we address this?
</blockquote></details>

I think we can do it later.
___
*[pkg/sql/distsql/columnar_operators_test.go, line 141 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43786#-LydlTAX0WYFB6OA9_DG:-Lyg_pED6DGVa5Oa6_5C:b-3n5tn1) ([raw file](https://github.com/cockroachdb/cockroach/blob/bad32cf0ce6163e5b37fbe2e1de462770bcb6fd9/pkg/sql/distsql/columnar_operators_test.go#L141)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Do we want to use 1 here instead? Maybe we should add some way to verify that an external sort actually spilled
</blockquote></details>

I wanted to use a different memory limit here so that we test a scenario when we have to spill after buffering several batches in the in-memory sorter. If we use 1, then always only a single batch will be buffered.

Added a callback to verify that the spilling occurs (in unit tests it's pretty hard to plumb the callback).
___
*[pkg/sql/distsql/columnar_utils_test.go, line 101 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43786#-LydmXdo-aryjQeIRDP6:-Lygf2ma4VlEviG4DUW0:bstlha7) ([raw file](https://github.com/cockroachdb/cockroach/blob/bad32cf0ce6163e5b37fbe2e1de462770bcb6fd9/pkg/sql/distsql/columnar_utils_test.go#L101)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I can't remember what this knob was used for. Could you add a comment to the args that explains what the different scenarios are?
</blockquote></details>

Actually we can just leave that knob as `false`. The idea behind that flag was reducing the number of memory accounts and monitors we need to close, so we plumbed that `useStreamingMemAccountForBuffering` knob so that planning code doesn't create extra memory monitoring infrastructure (so that we could use `testMemAccount` defined in `main_test.go`). But we are already cleaning up that infra here, so we don't need to set that knob to `true`.

**Review by asubiotto — COMMENTED** [review]
> Reviewed 10 of 10 files at r3, 10 of 10 files at r4, 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43786)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/disk_spiller.go, line 153 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/43786#-LyihYQfAPg5c-yekQNt:-LyihYQfAPg5c-yekQNu:bx9l8ey) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7568dc3a5bef999682968579fc04eb445d69654/pkg/sql/colexec/disk_spiller.go#L153)):*
> ```Go
> 			strings.Contains(err.Error(), d.inMemoryMemMonitorName) {
> 			d.spilled = true
> 			d.spillingCallbackFn()
> ```

Shouldn't we only call it if `spillingCallbackFn != nil`?
___
*[pkg/sql/colexec/execplan.go, line 102 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/43786#-LyihlkM-2Udrn6NVN2V:-LyihlkM-2Udrn6NVN2W:b-n32kfg) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7568dc3a5bef999682968579fc04eb445d69654/pkg/sql/colexec/execplan.go#L102)):*
> ```Go
> 	// SpillingCallbackFn will be called when the spilling from an in-memory to
> 	// disk-backed operator occurs. It should only be set in tests.
> 	SpillingCallbackFn func()
> ```

Because we now have two `TestingKnob`s, what do you think of putting these in a `TestingKnobs` struct?:
```
type NewColOperatorArgs struct {
    TestingKnobs struct {
        UseStreaming...
        SpillingCallbackFn...
    }
}
```
___
*[pkg/sql/colexec/sort.go, line 88 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/43786#-LyilUX933Hk9qQgUUMj:-LyilUXACETMi1wjaWWK:b-7ahwks) ([raw file](https://github.com/cockroachdb/cockroach/blob/f11c4365b75e59465ab4323cd31f4610ea324d5c/pkg/sql/colexec/sort.go#L88)):*
> ```Go
> 	// getWindowedBatch returns a batch that is a "window" into all Vecs of the
> 	// already spooled data, with tuples in range [startIdx, endIdx). This batch
> 	// is not allowed to be modified and is only safe to use until the next call
> ```

One idea we might want to implement at some point is adding a wrapper on top of a `coldata.Batch` that is `coldata.ImmutableBatch` that returns `coldata.ImmutableVecs` to enforce this
___
*[pkg/sql/colexec/sort.go, line 441 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/43786#-Lyilm2n2dyElufpIXWL:-Lyilm2n2dyElufpIXWM:bnor3qg) ([raw file](https://github.com/cockroachdb/cockroach/blob/f11c4365b75e59465ab4323cd31f4610ea324d5c/pkg/sql/colexec/sort.go#L441)):*
> ```Go
> 		newExported = p.input.getNumTuples()
> 	}
> 	b := p.input.getWindowedBatch(p.exported, newExported)
> ```

How does this commit affect the benchmarks?
___
*[pkg/sql/distsql/columnar_utils_test.go, line 101 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43786#-LydmXdo-aryjQeIRDP6:-Lyikkia8Lelp-X-4CFG:b-sc10as) ([raw file](https://github.com/cockroachdb/cockroach/blob/bad32cf0ce6163e5b37fbe2e1de462770bcb6fd9/pkg/sql/distsql/columnar_utils_test.go#L101)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Actually we can just leave that knob as `false`. The idea behind that flag was reducing the number of memory accounts and monitors we need to close, so we plumbed that `useStreamingMemAccountForBuffering` knob so that planning code doesn't create extra memory monitoring infrastructure (so that we could use `testMemAccount` defined in `main_test.go`). But we are already cleaning up that infra here, so we don't need to set that knob to `true`.
</blockquote></details>

Thanks! I think it would be worth it to put this explanation as part of the comment on `UseStreamingMemAccountForBuffering` in the struct definition.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43786)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/disk_spiller.go, line 153 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/43786#-LyihYQfAPg5c-yekQNt:-LyjBmhT9C9Ajw4m8J1b:b-v8rhpa) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7568dc3a5bef999682968579fc04eb445d69654/pkg/sql/colexec/disk_spiller.go#L153)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Shouldn't we only call it if `spillingCallbackFn != nil`?
</blockquote></details>

Oopsie, yes, thanks.
___
*[pkg/sql/colexec/execplan.go, line 102 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/43786#-LyihlkM-2Udrn6NVN2V:-LyjBZ-W8NsakDYFmb1M:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/e7568dc3a5bef999682968579fc04eb445d69654/pkg/sql/colexec/execplan.go#L102)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Because we now have two `TestingKnob`s, what do you think of putting these in a `TestingKnobs` struct?:
```
type NewColOperatorArgs struct {
    TestingKnobs struct {
        UseStreaming...
        SpillingCallbackFn...
    }
}
```
</blockquote></details>

Good point, done.
___
*[pkg/sql/colexec/sort.go, line 88 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/43786#-LyilUX933Hk9qQgUUMj:-LyjP2ibBrUhFbLG-pWe:bso2go9) ([raw file](https://github.com/cockroachdb/cockroach/blob/f11c4365b75e59465ab4323cd31f4610ea324d5c/pkg/sql/colexec/sort.go#L88)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

One idea we might want to implement at some point is adding a wrapper on top of a `coldata.Batch` that is `coldata.ImmutableBatch` that returns `coldata.ImmutableVecs` to enforce this
</blockquote></details>

I like this idea, added a TODO.
___
*[pkg/sql/colexec/sort.go, line 441 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/43786#-Lyilm2n2dyElufpIXWL:-LyjP6Dg6bqY-zFznB6N:b8x4m5a) ([raw file](https://github.com/cockroachdb/cockroach/blob/f11c4365b75e59465ab4323cd31f4610ea324d5c/pkg/sql/colexec/sort.go#L441)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

How does this commit affect the benchmarks?
</blockquote></details>

I was always running the benchmarks *with* this commit. I just checked what difference does this commit make and it seems to be on the order of 3-5% improvement, so the bottleneck is still sorting and merging.
___
*[pkg/sql/distsql/columnar_utils_test.go, line 101 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43786#-LydmXdo-aryjQeIRDP6:-LyjBlbG4TpWPdX-EqRC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bad32cf0ce6163e5b37fbe2e1de462770bcb6fd9/pkg/sql/distsql/columnar_utils_test.go#L101)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Thanks! I think it would be worth it to put this explanation as part of the comment on `UseStreamingMemAccountForBuffering` in the struct definition.
</blockquote></details>

Done.

**Review by asubiotto — APPROVED** [review]
:lgtm: great work

> Reviewed 16 of 16 files at r6, 5 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43786#-:-LykNjgR-BsHmd1xqfxy:b-g4vwjx)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
cc @knz @tbg please take a look at the fourth commit

**Comment by knz** [comment]
Last commit LGTM

Although have you checked that the behavior is OK when a test has sub-tests?
IIRC a sub-test will be like `TestXXX/Y/Z` and I'm afraid that `TestXXX$` will prevent the sub-tests from running. (But maybe `TestXXX$` does include sub-tests. I just don't know.)

**Comment by yuzefovich** [comment]
Good point, I didn't think about it at all.

I've just run `make test PKG=./pkg/col/coldata TESTS='(TestBytes$$)' TESTFLAGS='-test.v'` (`TestBytes` has several subtests within), and I got:
```
=== RUN   TestBytes
=== RUN   TestBytes/Simple
=== RUN   TestBytes/Append
=== RUN   TestBytes/Copy
=== RUN   TestBytes/Window
=== RUN   TestBytes/String
=== RUN   TestBytes/InvariantSimple
--- PASS: TestBytes (0.00s)
    --- PASS: TestBytes/Simple (0.00s)
    --- PASS: TestBytes/Append (0.00s)
    --- PASS: TestBytes/Copy (0.00s)
    --- PASS: TestBytes/Window (0.00s)
    --- PASS: TestBytes/String (0.00s)
    --- PASS: TestBytes/InvariantSimple (0.00s)
PASS
```
so it seems that subtests run ok with dollar signs in the regex.

**Comment by knz** [comment]
nice thanks for checking!

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

**Pull request merged**
