### PR TITLE
sql,roachtest: fix sqlsmith setup to return multiple stmts

### LINKED ISSUE #77887: roachtest: sqlsmith/setup=tpcc/setting=ddl-nodrop failed
roachtest.sqlsmith/setup=tpcc/setting=ddl-nodrop [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4583052&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4583052&tab=artifacts#/sqlsmith/setup=tpcc/setting=ddl-nodrop) on master @ [2f051c95ebb991e18134d2454807f992b05e4929](https://github.com/cockroachdb/cockroach/commits/2f051c95ebb991e18134d2454807f992b05e4929):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /artifacts/sqlsmith/setup=tpcc/setting=ddl-nodrop/run_1
	sqlsmith.go:118,sqlsmith.go:297,test_runner.go:866: pq: RESTORE cannot be used inside a multi-statement transaction without DETACHED option
```
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sqlsmith/setup=tpcc/setting=ddl-nodrop.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### LINKED ISSUE #77902: roachtest: cancel/tpch/local/queries=7,9,20,21,nodes=3 failed
roachtest.cancel/tpch/local/queries=7,9,20,21,nodes=3 [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4583052&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4583052&tab=artifacts#/cancel/tpch/local/queries=7,9,20,21,nodes=3) on master @ [2f051c95ebb991e18134d2454807f992b05e4929](https://github.com/cockroachdb/cockroach/commits/2f051c95ebb991e18134d2454807f992b05e4929):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /artifacts/cancel/tpch/local/queries=7_9_20_21_nodes=3/run_1
	cancel.go:53,monitor.go:105,errgroup.go:57: pq: a database named "tpch" needs to exist to restore table "region"

	monitor.go:127,cancel.go:120,cancel.go:149,test_runner.go:866: monitor failure: monitor task failed: t.Fatal() was called
		(1) attached stack trace
		  -- stack trace:
		  | main.(*monitorImpl).WaitE
		  | 	main/pkg/cmd/roachtest/monitor.go:115
		  | main.(*monitorImpl).Wait
		  | 	main/pkg/cmd/roachtest/monitor.go:123
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerCancel.func1
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cancel.go:120
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerCancel.func3
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/cancel.go:149
		  | main.(*testRunner).runTest.func2
		  | 	main/pkg/cmd/roachtest/test_runner.go:866
		Wraps: (2) monitor failure
		Wraps: (3) attached stack trace
		  -- stack trace:
		  | main.(*monitorImpl).wait.func2
		  | 	main/pkg/cmd/roachtest/monitor.go:171
		Wraps: (4) monitor task failed
		Wraps: (5) attached stack trace
		  -- stack trace:
		  | main.init
		  | 	main/pkg/cmd/roachtest/monitor.go:80
		  | runtime.doInit
		  | 	GOROOT/src/runtime/proc.go:6498
		  | runtime.main
		  | 	GOROOT/src/runtime/proc.go:238
		  | runtime.goexit
		  | 	GOROOT/src/runtime/asm_amd64.s:1581
		Wraps: (6) t.Fatal() was called
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.withPrefix (5) *withstack.withStack (6) *errutil.leafError
```
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cancel/tpch/local/queries=7,9,20,21,nodes=3.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-13827

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/77902
fixes https://github.com/cockroachdb/cockroach/issues/77887

Rather than doing the setup in one large batch, it now returns multiple
strings. This is because batch statements are now treated as an implicit
txn, which is not always desired.

Release note: None

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
Thanks! :lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77956#-:-MyIqYxE67I05O99psfR:b-ftzx47)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss)

**Comment by rafiss** [comment]
flake was https://github.com/cockroachdb/cockroach/issues/76391

bors r=yuzefovich

**Review by mgartner — APPROVED** [review]
Thanks!!

> Reviewed 6 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77956#-:-MyJUXoLEgsDjOltCoQg:b-hay2ia)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @stevendanna)

**Comment by rafiss** [comment]
tftr!

bors r=yuzefovich,mgartner

**Comment by rafiss** [comment]
bors r=yuzefovich,mgartner

**Pull request merged**
