### PR TITLE
changefeedccl: add support for multiple sinks in cdc roachtests

### PR DESCRIPTION
**Pull request by asg0451**
Add support for multiple sinks in cdc roachtests. Currently only Kafka is supported.

Epic: [CRDB-38755](https://cockroachlabs.atlassian.net/browse/CRDB-38755)

Release note: none

### CODE REVIEW

**Comment by asg0451** [comment]
TODO: this hits some issue in the chaos test which it can't recover from. fix me

**Review by rharding6373 — APPROVED** [review]
:lgtm: assuming the TODO above is addressed (looks like the tests are passing?)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126572#-:-O1ZEILz4G4EUy-qqTgv:b-fqqy41)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andyyang890, @asg0451, @DarrylWong, @herkolategan, and @wenyihu6)

___
*[`pkg/cmd/roachtest/tests/cdc.go` line 121 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126572#-O1ZDrW6ADi9cNmIYyRs:-O1ZDrW6ADi9cNmIYyRt:bfklwrk) ([raw file](https://github.com/cockroachdb/cockroach/blob/69f777e45fdd5b125d39fbfe9267ea7fdb3dd978/pkg/cmd/roachtest/tests/cdc.go#L121)):*
> ```Go
> // The nodes on which the webhook sink will be installed and run.
> func (ct *cdcTester) webhookSinkNodes() option.NodeListOption {
> 	return ct.cluster.Range(ct.cluster.Spec().NodeCount-ct.numSinkNodes+1, ct.cluster.Spec().NodeCount)
> ```

nit: `ct.cluster.Spec().NodeCount-ct.numSinkNodes` should get refactored out into a helper function since it's reused so much and hard to understand

**Review by asg0451 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126572)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andyyang890, @DarrylWong, @herkolategan, @rharding6373, and @wenyihu6)

___
*[`pkg/cmd/roachtest/tests/cdc.go` line 121 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126572#-O1ZDrW6ADi9cNmIYyRs:-O1bV8WE2fNykDzpjk6r:b-kyrk6f) ([raw file](https://github.com/cockroachdb/cockroach/blob/69f777e45fdd5b125d39fbfe9267ea7fdb3dd978/pkg/cmd/roachtest/tests/cdc.go#L121)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

nit: `ct.cluster.Spec().NodeCount-ct.numSinkNodes` should get refactored out into a helper function since it's reused so much and hard to understand
</blockquote></details>

i'm not sure I agree. it's only used 3 times and each of those times it's already inside very small helper functions. i'll add a comment to explain the logic instead

**Review by andyyang890 — APPROVED** [review]
:lgtm: Nice!

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126572#-:-O1cObbF5bxHanUhAcaU:b-8gk8uj)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DarrylWong, @herkolategan, @rharding6373, and @wenyihu6)

**Comment by asg0451** [comment]
bors r=rharding6373,andyyang890

**Pull request merged**
