### PR TITLE
pgwire: support decoding binary regXXX types

### LINKED ISSUE #94353: sql: v22.2.1: error in argument for ×: unsupported OID 2206
This issue was autofiled by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry link: https://sentry.io/organizations/cockroach-labs/issues/3839460375/?referrer=webhooks_plugin

Panic message:

>encoding.go:853: error in argument for ×: unsupported OID 2206 with format code FormatBinary
(1) candidate pg code: 08P01
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execBind.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:429
  | [...repeated from below...]
Wraps: (3) error in argument for ×
Wraps: (4) assertion failure
Wraps: (5) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire/pgwirebase.DecodeDatum
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/pgwirebase/encoding.go:853
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execBind.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:422
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execBind
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:438
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2037
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1854
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:832
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:728
  | runtime.goexit
  | 	src/runtime/asm_arm64.s:1172
Wraps: (6) unsupported OID 2206 with format code FormatBinary
Error types: (1) *pgerror.withCandidateCode (2) *withstack.withStack (3) *errutil.withPrefix (4) *assert.withAssertionFailure (5) *withstack.withStack (6) *errutil.leafError
-- report composition:
*errutil.leafError: unsupported OID 2206 with format code FormatBinary
encoding.go:853: *withstack.withStack (top exception)
*assert.withAssertionFailure
*errutil.withPrefix: error in argument for ×
conn_executor_prepare.go:429: *withstack.withStack (1)
*pgerror.withCandidateCode: 08P01
(check the extra data payloads)

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

https://github.com/cockroachdb/cockroach/blob/cf1e7e6bc6ef9e55510b9ed13bd068bb3894cd92/pkg/sql/conn_executor_prepare.go#L428-L430 in pkg/sql.(*connExecutor).execBind.func2
https://github.com/cockroachdb/cockroach/blob/cf1e7e6bc6ef9e55510b9ed13bd068bb3894cd92/pkg/sql/conn_executor_prepare.go#L437-L439 in pkg/sql.(*connExecutor).execBind
https://github.com/cockroachdb/cockroach/blob/cf1e7e6bc6ef9e55510b9ed13bd068bb3894cd92/pkg/sql/conn_executor.go#L2036-L2038 in pkg/sql.(*connExecutor).execCmd
https://github.com/cockroachdb/cockroach/blob/cf1e7e6bc6ef9e55510b9ed13bd068bb3894cd92/pkg/sql/conn_executor.go#L1853-L1855 in pkg/sql.(*connExecutor).run
https://github.com/cockroachdb/cockroach/blob/cf1e7e6bc6ef9e55510b9ed13bd068bb3894cd92/pkg/sql/conn_executor.go#L831-L833 in pkg/sql.(*Server).ServeConn
https://github.com/cockroachdb/cockroach/blob/cf1e7e6bc6ef9e55510b9ed13bd068bb3894cd92/pkg/sql/pgwire/conn.go#L727-L729 in pkg/sql/pgwire.(*conn).processCommandsAsync.func1
src/runtime/asm_arm64.s#L1171-L1173 in runtime.goexit
</details>

```
pkg/sql/conn_executor_prepare.go in pkg/sql.(*connExecutor).execBind.func2 at line 429
pkg/sql/conn_executor_prepare.go in pkg/sql.(*connExecutor).execBind at line 438
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2037
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 1854
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 832
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 728
src/runtime/asm_arm64.s in runtime.goexit at line 1172
```

| Tag | Value |
|---|---|
| Cockroach Release | `v22.2.1` |
| Cockroach SHA: | cf1e7e6bc6ef9e55510b9ed13bd068bb3894cd92 |
| Platform | linux arm64 |
| Distribution | CCL |
| Environment | v22.2.1 |
| Command | start-single-node |
| Go Version | ``|
| # of CPUs ||
| # of Goroutines ||

Jira issue: CRDB-22843

### PR DESCRIPTION
**Pull request by jordanlewis**
Fixes #94353

Epic: None

Release note (bug fix): support receiving regXXX type values in binary extended protocol

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
can you add a test? either `pkg/sql/pgwire/testdata/pgtest` or `pkg/sql/pgwire/testdata/encodings.json`

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94355#-:-NKTfuM592aDoZkZ0FrF:b-bufz1y)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[`pkg/sql/pgwire/pgwirebase/encoding.go` line 846 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94355#-NKTfbcW4g0Ob0NnXasu:-NKTfbcW4g0Ob0NnXasv:b-lu4p63) ([raw file](https://github.com/cockroachdb/cockroach/blob/31b882d9c27d6e632fda978fd51ecd0d1cba7520/pkg/sql/pgwire/pgwirebase/encoding.go#L846)):*
> ```Go
> 			if typ.Family() == types.ArrayFamily {
> 				return decodeBinaryArray(ctx, evalCtx, typ.ArrayContents(), b, code)
> 			}
> ```

up to you, but you could instead add a `if typ.Family() == types.OidFamily` here, so that there's less of a chance of missing a `case`

**Review by rafiss — APPROVED** [review]
bors r+

**Comment by jordanlewis** [comment]
Argh sorry I never got to responding to your comment 😭 thank you for fixing and merging

**Comment by rafiss** [comment]
wait i didn't respond to my own comment either, since i forgot to add a test :D 

bors r-

**Pull request merged**
