### PR TITLE
storage: add sanity check in RangeLookup

### PR DESCRIPTION
**Pull request by tamird**
@cockroachdb/stability

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9359)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm: but let @spencerkimball or @tschottdorf weigh in as well.

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, 1 of 1 files at r5.
Review status: 4 of 7 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[keys/keys.go, line 408 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/9359#-KRe90jfCT5U0E1BcsUe:-KRe90jg8P28iO6QYaqm:ba917fj) ([raw file](https://github.com/cockroachdb/cockroach/blob/32df163d0b8ccd01de035b5e18b1e0477b342887/keys/keys.go#L408)):*
> ```Go
> 	case Meta1Prefix[0]:
> 		return roachpb.KeyMin
> 	case Meta2Prefix[0]:
> ```

I seem to recall that this was done for efficiency. Take a look at where these changes arose and perhaps revert your changes and add a comment.

---

*[storage/replica_command.go, line 1126 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/9359#-KRe9M3RX1ToOsAFUC-Y:-KRe9M3RX1ToOsAFUC-Z:b-dh5ljo) ([raw file](https://github.com/cockroachdb/cockroach/blob/da28fdc058381e5700849d8bc2b68d4698447aee/storage/replica_command.go#L1126)):*
> ```Go
> 	for _, rd := range reply.Ranges {
> 		if !containsFn(rd, userKey) {
> 			log.Fatalf(ctx, "range lookup of meta key %q resulted in descriptor %s which does not contain non-meta key %q", key, rd, userKey)
> ```

I think you can use `%s` instead of `%q` above. More specifically, I don't think the `%q` has any effect due to the way we format keys.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9359#-:-KRe9beC5iEfNIpXB_Js:b-teny5b)*

**Comment by petermattis** [comment]
Review status: 4 of 7 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[keys/keys.go, line 408 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/9359#-KRe90jfCT5U0E1BcsUe:-KReCAhJEaSfyMkI5rTE:b8zozft) ([raw file](https://github.com/cockroachdb/cockroach/blob/32df163d0b8ccd01de035b5e18b1e0477b342887/keys/keys.go#L408)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> The change was made in d5e06c8d27d42c2d68ed09027fb27abeb9c05c2f. Sadly, there is no rationale listed here.
</details>
Hmm, unfortunate. I'd prefer you revert your changes here.

---

*[storage/replica_command.go, line 1126 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/9359#-KRe9M3RX1ToOsAFUC-Y:-KReCTD7o_D0OPoZDIvN:bpsbqwu) ([raw file](https://github.com/cockroachdb/cockroach/blob/da28fdc058381e5700849d8bc2b68d4698447aee/storage/replica_command.go#L1126)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> See 9dc8c5ce38ed17a908e85c4dc54b1438c58b3c42
</details>
Seems like we should fix `PrettyPrintKey`. The fact that `%q` differs from `%s` here is inconsistent with the behavior of `roachpb.Key`. We might also want to define `roachpb.RKey.Format`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9359)*

**Comment by tamird** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[keys/keys.go, line 408 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/9359#-KRe90jfCT5U0E1BcsUe:-KReJVHjj-rG92_c0rXo:b-39a1uk) ([raw file](https://github.com/cockroachdb/cockroach/blob/32df163d0b8ccd01de035b5e18b1e0477b342887/keys/keys.go#L408)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Hmm, unfortunate. I'd prefer you revert your changes here.
</details>
Done. Added some constants to clarify the intent.

---

*[storage/replica_command.go, line 1126 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/9359#-KRe9M3RX1ToOsAFUC-Y:-KReJYqYQKI6YFUcoKR8:bmfck81) ([raw file](https://github.com/cockroachdb/cockroach/blob/da28fdc058381e5700849d8bc2b68d4698447aee/storage/replica_command.go#L1126)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Seems like we should fix `PrettyPrintKey`. The fact that `%q` differs from `%s` here is inconsistent with the behavior of `roachpb.Key`. We might also want to define `roachpb.RKey.Format`. 
</details>
I'll file an issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9359)*

**Comment by petermattis** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[keys/keys.go, line 404 at r12](https://reviewable.io:443/reviews/cockroachdb/cockroach/9359#-KReMQ1TACGetMAH_wH9:-KReMQ1TACGetMAH_wHA:b34hlt9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c67956bf32b149d31e58d50d021ce123d0583ce6/keys/keys.go#L404)):*
> ```Go
> // - For RKeyMin, KeyMin is returned.
> func RangeMetaKey(key roachpb.RKey) roachpb.Key {
> 	if key.Equal(roachpb.RKeyMin) {
> ```

Does this change matter? Perhaps leave the previous code but add `// key.Equal(roachpb.RKeyMin)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9359)*

**Comment by tamird** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[keys/keys.go, line 404 at r12](https://reviewable.io:443/reviews/cockroachdb/cockroach/9359#-KReMQ1TACGetMAH_wH9:-KReMheWhyLunZsmkTyz:b7gwyx7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c67956bf32b149d31e58d50d021ce123d0583ce6/keys/keys.go#L404)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Does this change matter? Perhaps leave the previous code but add `// key.Equal(roachpb.RKeyMin)`
</details>
It doesn't matter -- long ago I tried to distinguish between KeyMin and the absence of a key (empty slice vs nil slice), so this is a reflex. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9359)*

**Comment by tamird** [comment]
This change actually reproduces #9265 almost instantly under stress on my machine when running `storage. TestStoreRangeSystemSplits`. Unfortunately, I'm still reproducing something after applying #9374. Investigating.

**Comment by spencerkimball** [comment]
We discovered this doesn't reproduce #9265. It's a case where `RangeLookup` simply can't return an non-intent range descriptor which contains the requested key because intents have been resolved out of order and it won't return the intents directly.

@tamird is addressing this by returning intents if no ranges are committed which contain the key, but there is an intent which does.

**Comment by tamird** [comment]
Updated.

**Comment by spencerkimball** [comment]
LGTM

**Comment by tamird** [comment]
After staring at this code a bunch, I have one lingering question: why do we not _always_ consider intents in RangeLookup? According to @nvanbenschoten this is an ancient decision made by @tschottdorf...will revisit after this PR.

**Comment by tschottdorf** [comment]
Likely historical baggage.

:LGTM:

---

Reviewed 7 of 7 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, 3 of 3 files at r10, 1 of 2 files at r11, 3 of 3 files at r13, 3 of 3 files at r14.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[keys/keys.go, line 430 at r14](https://reviewable.io:443/reviews/cockroachdb/cockroach/9359#-KRewSz9FNTCfJlczMo2:-KRewSz9FNTCfJlczMo3:b-6ky2xc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6af8967f568143512e202a3587928f693b7b3a3/keys/keys.go#L430)):*
> ```Go
> // - For a meta2 key, an ordinary key is returned.
> // - For a meta1 key, a meta2 key is returned.
> // - For RKeyMin, a meta1 key is returned.
> ```

s/a meta1 key/Meta1Prefix/ and that case should be first since RKeyMin is also an "ordinary key" (at least unless that is better defined).

---

*[storage/replica_command.go, line 1095 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/9359#-KRexDdGmd6yRpl1RGCm:-KRexDdH88S3BN33exKd:b3j8qv3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffe38ee718f1f313fefc35a15df165f28b91dca5/storage/replica_command.go#L1095)):*
> ```Go
> 				return reply, nil, err
> 			}
> 			// If this is a descriptor we're allowed to return, add that
> ```

We agreed to remove this comment.

---

*[storage/replica_test.go, line 4712 at r14](https://reviewable.io:443/reviews/cockroachdb/cockroach/9359#-KRexvtSGg8UxARl1-VD:-KRexvtTSR9PKTIsNrb9:bi91hjl) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6af8967f568143512e202a3587928f693b7b3a3/storage/replica_test.go#L4712)):*
> ```Go
> 	splitRangeBefore := roachpb.RangeDescriptor{RangeID: 3, StartKey: roachpb.RKey("c"), EndKey: roachpb.RKey("h")}
> 	splitRangeLHS := roachpb.RangeDescriptor{RangeID: 3, StartKey: roachpb.RKey("c"), EndKey: roachpb.RKey("f")}
> 	splitRangeRHS := roachpb.RangeDescriptor{RangeID: 5, StartKey: roachpb.RKey("f"), EndKey: roachpb.RKey("h")}
> ```

Is there a similar test without the reverse?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9359#-:-KRez4LnrDbKbluG5e5A:b-rcqjd3)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[keys/keys.go, line 430 at r14](https://reviewable.io:443/reviews/cockroachdb/cockroach/9359#-KRewSz9FNTCfJlczMo2:-KRfJSXCbJiajY6vRLEm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6af8967f568143512e202a3587928f693b7b3a3/keys/keys.go#L430)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> s/a meta1 key/Meta1Prefix/ and that case should be first since RKeyMin is also an "ordinary key" (at least unless that is better defined).
</details>
Done.

---

*[storage/replica_command.go, line 1095 at r13](https://reviewable.io:443/reviews/cockroachdb/cockroach/9359#-KRexDdGmd6yRpl1RGCm:-KRfKybI2t0HpdO3enhA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffe38ee718f1f313fefc35a15df165f28b91dca5/storage/replica_command.go#L1095)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> We agreed to remove this comment.
</details>
Done.

---

*[storage/replica_test.go, line 4712 at r14](https://reviewable.io:443/reviews/cockroachdb/cockroach/9359#-KRexvtSGg8UxARl1-VD:-KRfKzO86wxSVqOcpTgI:bcpmm65) ([raw file](https://github.com/cockroachdb/cockroach/blob/b6af8967f568143512e202a3587928f693b7b3a3/storage/replica_test.go#L4712)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Is there a similar test without the reverse?
</details>
The forward test is much simpler and isn't guilty of manual meta2 manipulation, so does not need this correction.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9359)*

**Comment by bdarnell** [comment]
:lgtm:

I'm also unaware of a non-historical reason why we don't always consider intents. Probably just fear of the strange consistency semantics, but it's pretty solid these days. 

---

Reviewed 1 of 1 files at r17, 3 of 3 files at r18, 1 of 2 files at r19, 3 of 3 files at r20.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[keys/keys.go, line 431 at r20](https://reviewable.io:443/reviews/cockroachdb/cockroach/9359#-KRiE-4i1XaZ-EtzugC8:-KRiE-4k6qf8ySgih0KC:bjow9nq) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed16a7339ba66c8f45ffb2128548f91414198ed0/keys/keys.go#L431)):*
> ```Go
> // - For a meta2 key, an ordinary key is returned.
> // - For an ordinary key, the input key is returned.
> func UserKey(key roachpb.RKey) roachpb.RKey {
> ```

This function could use a test. I don't love the name `UserKey`, but don't have a better suggestion (except something awkward like `UnMetaKey`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9359#-:-KRiFs0GYMtH2G_rpNWa:beb0nvw)*

**Comment by tamird** [comment]
Review status: 0 of 9 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[keys/keys.go, line 431 at r20](https://reviewable.io:443/reviews/cockroachdb/cockroach/9359#-KRiE-4i1XaZ-EtzugC8:-KRiMIUHTNII5dfVOh71:b-n6aka9) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed16a7339ba66c8f45ffb2128548f91414198ed0/keys/keys.go#L431)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> This function could use a test. I don't love the name `UserKey`, but don't have a better suggestion (except something awkward like `UnMetaKey`)
</details>
Added a test. I don't love the name either, but I'm going to leave it as-is because I can't think of anything better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9359)*

**Pull request merged**
