### PR TITLE
storage: reinstate snapshot status reporting

### LINKED ISSUE #9592: storage: Replica.reportSnapshotStatus not called for streaming snapshots?
We don't seem to be calling `Replica.reportSnapshotStatus` for Raft generated streaming snapshots. See `Replica.sendRaftMessage`.

Cc @cockroachdb/stability

### PR DESCRIPTION
**Pull request by jordanlewis**
Streaming snapshots inadvertently removed Raft-initiated snapshot status
reporting. This is a feature that allows Raft to perform some IO
optimizations, according to the etcd Raft README, so we'd like to
continue using it.

Fixes #9592.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9606)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/replica.go, line 2386 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9606#-KSmLAQe4jGag15ZQHPN:-KSmLAQe4jGag15ZQHPO:b-pavhla) ([raw file](https://github.com/cockroachdb/cockroach/blob/98634c7993c4abd1568773c22bde3546e1c7f7d1/storage/replica.go#L2386)):*
> ```Go
> 				// Report the snapshot status to Raft, which expects us to do this once
> 				// we finish attempting to send the snapshot.
> 				r.reportSnapshotStatus(msg.To, err)
> ```

there's a TODO on the method that you should remove as part of this change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9606)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9606#-:-KSmNzQsRjgiaQNgGjRC:bnfp4nl)*

**Comment by jordanlewis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[storage/replica.go, line 2386 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9606#-KSmLAQe4jGag15ZQHPN:-KSmOoIMDiLKDQFjwobw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/98634c7993c4abd1568773c22bde3546e1c7f7d1/storage/replica.go#L2386)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> there's a TODO on the method that you should remove as part of this change.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9606)*

**Comment by tamird** [comment]
:lgtm: modulo ongoing discussion in #9592.

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9606#-:-KSmPa5Fp7rzQoxmLHcr:b-oj652f)*

**Pull request merged**
