### PR TITLE
c-deps: bump RocksDB from 5.13 to 5.17.2

### PR DESCRIPTION
**Pull request by petermattis**
Pass `USE_RTTI=1` to the RocksDB build. 5.13 was built with rtti
enabled (there was no way to disable it), but 5.17.2 defaults to
disabling rtti. Unfortunately, the rest of our C++ dependencies build
with rtti enabled and C++ requires consistently specifying `-fno-rtti`
for all compilation, otherwise you get strange `undefined reference to
typeinfo` errors at link time. At least one of our C++
dependencies (cryptopp) does not allow easily disabling usage of rtti.

Verified that the `RocksDBDeleteRangeIterate` benchmark was unchanged
which indicates the RocksDB delete range patches are in effect.

Release note: None

### CODE REVIEW

**Review by benesch — APPROVED** [review]

**Comment by petermattis** [comment]
@benesch Disabling rtti everywhere might be a small size / perf win. I didn't pull hard on the `cryptopp` thread. Looks straightforward to disable rtti for `protobuf`.

**Comment by benesch** [comment]
Ack. We should ditch cryptopp anyway. We can’t upgrade it because they dropped support for CMake builds in the next version, and their non-CMake build system doesn’t support out of tree builds.

**Comment by petermattis** [comment]
> We should ditch cryptopp anyway. 

What would replace it?

**Comment by benesch** [comment]
OpenSSL/LibreSSL would be my pick.

**Comment by petermattis** [comment]
bors r=benesch

**Pull request merged**
