### PR TITLE
util/protoutil: remove fuzzing mechanism

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit removes the fuzzing mechanism from `protoutil` package that
could randomly set fields of protobufs that have
`cockroachdb:randnullable` tag to null. This also removes all the usage
of this tag from the proto definitions.

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48238)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/roachpb/data.proto, line 617 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48238#-M6BeOLnCgZuSahyibUU:-M6BeOLnCgZuSahyibUV:b-xqxs4c) ([raw file](https://github.com/cockroachdb/cockroach/blob/c2668dc242a70343cb877d2b5cc5f4d2f22cdde7/pkg/roachpb/data.proto#L617)):*
> ```protobuf
>   // The expiration is a timestamp at which the lease expires. This means that
>   // a new lease can be granted for a later timestamp.
>   util.hlc.Timestamp expiration = 2 [(gogoproto.moretags) = "cockroachdb:\"randnullable\""];
> ```

I assume the removal of the tags doesn't introduce compatibility problems, right?

**Review by tbg — APPROVED** [review]
Removing these extra tags is harmless. They don't affect the marshaled representation of the structs.

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by andreimatei** [comment]
This patch has no justification in the commit message...
Should this have gone away with it? https://github.com/cockroachdb/cockroach/blob/master/pkg/roachpb/data.go#L1727-L1736

**Comment by yuzefovich** [comment]
By "justification" do you mean "release justification"? Or explaining why this patch was opened up in the first place? The answer to the former is that it merged after 20.1 branch was cut and release justification was no longer necessary.

The answer to the latter: for some context I was trying to cleanup dependencies, and this fuzzing mechanism had a single call to `util/log` (if I'm not mistaken) which was bringing in a lot of other stuff, and I wanted to get rid off it. I did that in #47583, but I had a typo which I tried to fix with #48232. However, on slack there was a discussion that we should probably remove the whole randnullability thing altogether (which Tobi suggested), so I did that in this PR. I think it was no longer useful, so we got rid off it.

I don't anything know about `BootstrapLease` thing, maybe @tbg would know.

**Comment by andreimatei** [comment]
I was asking about the latter. It's generally good to know both why something was in your way, but more importantly why it was considered a good idea to have it removed (cause, like, 2 years prior it seemed like a good idea to add that mechanism). Helps with archeology. 
Anyway, https://github.com/cockroachdb/cockroach/pull/50568 for removing that `BootstrapLease()`. It's a thing that was added together with the fuzzer, and now that's in my way.

**Pull request merged**
