### PR TITLE
storage: less clobbering and better readability in NodeLiveness

### PR DESCRIPTION
**Pull request by tbg**
See #18219 for context. Needs testing, but I wanted to get this out for review as
I'm hoping that it can go into 1.1.2. or 1.1.3.

----

Investigated the decommissioning problems some users have faced, which are essentially
that sometimes `NodeLiveness` gets stuck with a liveness record that doesn't have
`Decommissioning == true` even though `./cockroach debug gossip-values` indicates that
Gossip did receive the correct record. This appears to be happening mostly (always?)
when the target node is dead.

Unfortunately, I couldn't come up with a conclusive scenario since the users presumably
initiated these commands long after the target node was dead (and so `IncrementEpoch`
*should* not be directed at this node, though perhaps it is?) but I decided to simplify
and harden the code against some of the known issues. Precisely,

1. Update the stored liveness when setting the decommissioning status. This alone would
   prevent the decommissioning command from getting stuck (since the wrong state would be
   expunged).
2. Pass all code which updates any cached liveness through a method which decides whether
   to update, namely when the epoch or expiration are newer (or, if neither has
   changed, update if there are any other changes). This should do the "right
   thing" for Epoch/Expiration, but may clobber for `Draining/Decommissioning`,
   though that problem should have gotten less frequent in this change since we
   previously didn't use this criterion for more than breaking ties.
3. Remove `(NodeLiveness).mu.self`. It was odd to have both that and an entry in `mu.nodes`,
   and the original motivation (avoiding late gossip updates to "wind back" the
   state) does not seem to apply any more. This change is logically disconnected from the
   initial issue, but clarifying the code to make it easier to reason about seemed like a
   clear win.

I'm mildly nervous that something here might introduce a silly bug, but if it did and we
don't discover it in review, it's a signal that we should introduce a sequence number as
described in #18219.

### CODE REVIEW

**Comment by bdarnell** [comment]
:lgtm: 

The fourth commit is more refactoring than I'd like to do in a patch release. OTOH, if we don't backport it then we'll be left with divergence between 1.1.2 and master (and we'll have to make sure we test the 1.1.2 version without the backport before it is released)

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/storage/node_liveness.go, line 732 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19279#-KwfYdJCteUk_7gxJama:-KwfYdJCteUk_7gxJamb:b-f3wxpd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4bc322352cf76e2792ca2c785c3cb10939afbe2/pkg/storage/node_liveness.go#L732)):*
> ```Go
> 		// decommissioning field changed.
> 		//
> 		// This has false positives (in which case we're clobbering the
> ```

Doesn't it also have false negatives when the draining/decomissioning flag is updated at the same time as expiration or epoch?

---

*[pkg/storage/node_liveness.go, line 779 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/19279#-Kwf_-yZKJT0yWI0nFAV:-Kwf_-yZKJT0yWI0nFAW:bh2wdy4) ([raw file](https://github.com/cockroachdb/cockroach/blob/3285ec8f47f3a9efdfd04e1faf078c926720f15c/pkg/storage/node_liveness.go#L779)):*
> ```Go
> 	}
> 	if err != nil {
> 		log.Warningf(ctx, "looking up own liveness: %s", err)
> ```

Return here instead of continuing. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19279#-:-Kwf_VjW5miTxJmUmdac:b-h5gq1i)*

**Comment by a-robinson** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/storage/node_liveness.go, line 741 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19279#-Kwewg9cwdfY_JbUJX2p:-Kwewg9cwdfY_JbUJX2q:btl0i65) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4bc322352cf76e2792ca2c785c3cb10939afbe2/pkg/storage/node_liveness.go#L741)):*
> ```Go
> 
> 	// Accept an update if it moves either expiration or epoch forward.
> 	return old.Expiration.Less(new.Expiration) || old.Epoch < new.Epoch
> ```

The serialization of writes to the KV layer might prevent this from ever being an issue, but what happens if an update increases one of these and decreases the other? I'd feel a little safer if the logic was something like `return (old.Expiration.Less(new.Expiration) && old.Epoch <= new.Epoch) || (old.Epoch < new.Epoch && (old.Expiration.Less(new.Expiration) || old.Expiration.Equals(new.Expiration)))`, or if it consistently chose one type of update to prefer in the conflicting case -- e.g. prefer the version with the higher epoch over the one with the higher expiration

---

*[pkg/storage/node_liveness.go, line 774 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/19279#-KwfdK3NwBZomzWxZjSY:-KwfdK3NwBZomzWxZjSZ:byf1jl0) ([raw file](https://github.com/cockroachdb/cockroach/blob/3285ec8f47f3a9efdfd04e1faf078c926720f15c/pkg/storage/node_liveness.go#L774)):*
> ```Go
> 	}
> 
> 	self, err := nl.Self()
> ```

Minor, but we could avoid an extra lock-unlock if we just took the lock up here and called `nl.getLivenessLocked(selfID)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19279#-:-KwfdSP_vBpWGnabXfcj:bnfp4nl)*

**Comment by nvanbenschoten** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/storage/node_liveness.go, line 497 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/19279#-KwgLLaRUMHIE00OA09v:-KwgLLaRUMHIE00OA09w:b-7fe8m1) ([raw file](https://github.com/cockroachdb/cockroach/blob/22147f9d81f0f126a014afaf39d2b1d08b6882de/pkg/storage/node_liveness.go#L497)):*
> ```Go
> 	// NB: shouldReplaceLiveness should always be true
> 	// since setSelf is only ever called for non-overlapping
> 	// liveness updated serialized through a single semaphore.
> ```

If it should always be true, should we panic if it's not instead of silently ignoring the probable logic error?

EDIT: never mind. If we keep commit 4 then this all goes away.

---

*[pkg/storage/node_liveness.go, line 774 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/19279#-KwfdK3NwBZomzWxZjSY:-KwgM66JY7m6pWXwN7zO:bqf3ww) ([raw file](https://github.com/cockroachdb/cockroach/blob/3285ec8f47f3a9efdfd04e1faf078c926720f15c/pkg/storage/node_liveness.go#L774)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Minor, but we could avoid an extra lock-unlock if we just took the lock up here and called `nl.getLivenessLocked(selfID)`
</blockquote></details>

I wouldn't say minor, since your suggestion reduces the chance of weird races here. A single critical section would also improve clarity.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19279#-:-KwgMuM3gVwMo8dW2u_-:bnfp4nl)*

**Comment by tschottdorf** [comment]
@bdarnell there's always the option of withholding the last commit, but I'd prefer to have this exercised rather sooner than later (we could also omit it in 1.1 initially if we remember to add it in a later patch, or when conflicts arise). Your call.

Added a unit test, will merge later today if things look good.

---

Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/storage/node_liveness.go, line 732 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19279#-KwfYdJCteUk_7gxJama:-Kwg3m_7hDOOgIhpIVSr:b-i8k9fu) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4bc322352cf76e2792ca2c785c3cb10939afbe2/pkg/storage/node_liveness.go#L732)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Doesn't it also have false negatives when the draining/decomissioning flag is updated at the same time as expiration or epoch?
</blockquote></details>

Not sure I understand, if both are updated at the same time, the decommissioning/draining update doesn't matter because we update anyway. Are you worried about something like setting decommissioning and immediately after bumping the epoch, and then seeing the gossip updates out of order? That would be fine too, because the epoch bump result would also have decommissioning set (since everything gets serialized through CPuts).

---

*[pkg/storage/node_liveness.go, line 741 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19279#-Kwewg9cwdfY_JbUJX2p:-Kwg6QyPsB6_Y3guE2Ba:b-ame6zm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4bc322352cf76e2792ca2c785c3cb10939afbe2/pkg/storage/node_liveness.go#L741)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

The serialization of writes to the KV layer might prevent this from ever being an issue, but what happens if an update increases one of these and decreases the other? I'd feel a little safer if the logic was something like `return (old.Expiration.Less(new.Expiration) && old.Epoch <= new.Epoch) || (old.Epoch < new.Epoch && (old.Expiration.Less(new.Expiration) || old.Expiration.Equals(new.Expiration)))`, or if it consistently chose one type of update to prefer in the conflicting case -- e.g. prefer the version with the higher epoch over the one with the higher expiration
</blockquote></details>

That's a good point. In practice this shouldn't happen (Epoch never goes down, and Expiration, too, though I'm less convinced there if we're in clockless mode and things are *really* set up to fail). Preferring the one with higher Epoch now.

---

*[pkg/storage/node_liveness.go, line 774 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/19279#-KwfdK3NwBZomzWxZjSY:-KwiXseRpbZeOdxui-uh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3285ec8f47f3a9efdfd04e1faf078c926720f15c/pkg/storage/node_liveness.go#L774)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I wouldn't say minor, since your suggestion reduces the chance of weird races here. A single critical section would also improve clarity.
</blockquote></details>

Done.

---

*[pkg/storage/node_liveness.go, line 779 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/19279#-Kwf_-yZKJT0yWI0nFAV:-KwiXy0SIw7WCztSGjNg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3285ec8f47f3a9efdfd04e1faf078c926720f15c/pkg/storage/node_liveness.go#L779)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Return here instead of continuing. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19279#-:-Kwg3Vwqr0Yasvjyl1A6:b-avgksq)*

**Comment by a-robinson** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r5, 1 of 2 files at r8, 1 of 2 files at r9.
Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/storage/node_liveness.go, line 792 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/19279#-KwjXTRAIsO3hVjI_UKY:-KwjXTRAIsO3hVjI_UKZ:b-1f1zge) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0c63834d888e2ecb0ec8e1b736721680737d942/pkg/storage/node_liveness.go#L792)):*
> ```Go
> 		return 0
> 	}
> 	if err != nil {
> ```

Why check the error *after* using the `self` value? It looks like a mistake

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19279#-:-KwjXcQvDVVTr6YdTaM2:bnfp4nl)*

**Comment by tschottdorf** [comment]
Review status: 2 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/storage/node_liveness.go, line 792 at r9](https://reviewable.io:443/reviews/cockroachdb/cockroach/19279#-KwjXTRAIsO3hVjI_UKY:-Kwk6h9Zw5ZdpQzZmLtQ:b1kqolf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0c63834d888e2ecb0ec8e1b736721680737d942/pkg/storage/node_liveness.go#L792)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Why check the error *after* using the `self` value? It looks like a mistake
</blockquote></details>

Definitely a mistake, at least one of the two of us is awake.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19279)*

**Comment by bdarnell** [comment]
I'm fine including all the commits in 1.1.2.

---

Review status: 1 of 3 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/storage/node_liveness.go, line 732 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19279#-KwfYdJCteUk_7gxJama:-Kwkkxy9p_mwfEe1lqW0:b-eafitl) ([raw file](https://github.com/cockroachdb/cockroach/blob/e4bc322352cf76e2792ca2c785c3cb10939afbe2/pkg/storage/node_liveness.go#L732)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Not sure I understand, if both are updated at the same time, the decommissioning/draining update doesn't matter because we update anyway. Are you worried about something like setting decommissioning and immediately after bumping the epoch, and then seeing the gossip updates out of order? That would be fine too, because the epoch bump result would also have decommissioning set (since everything gets serialized through CPuts).
</blockquote></details>

Yeah, I was worried about out-of-order gossip updates. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19279#-:-Kwkl4ka7c9Y1Wwrceft:bskhxas)*

**Comment by tschottdorf** [comment]
> I'm fine including all the commits in 1.1.2.

Ack, thanks. I'll wait for a few days since I introduced some flakiness that I just fixed.

**Pull request merged**
