### PR TITLE
test: turn on invariants in Pebble for crdb tests

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### go.mod: bump Pebble to 8b6a9571dd31

Changes:

 * [`8b6a9571`](https://github.com/cockroachdb/pebble/commit/8b6a9571) turn on invariants all the time (test only)

Release note: none.
Epic: none.

### CODE REVIEW

**Review by jbowens — APPROVED** [review]
Looks like we need some changes for the KeySchema pointer commit


:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133113#-:-O9kkzQp4J_mEtSYNXlU:bb2e47t)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Comment by rickystewart** [comment]
We can discuss how to make this work in a way that will work with the build system. tldr is that we'll have to apply a `select` like you can find in `pkg/storage/pebbleiter/BUILD.bazel`.

```
select({
        "//build/toolchains:crdb_test": [":gen-crdb-test-on"],
        "//conditions:default": [":gen-crdb-test-off"],
    }),
```

**Comment by RaduBerinde** [comment]
Thanks. Let me try a big hammer (invariants always on) since this is just a test run for now.

**Comment by RaduBerinde** [comment]
Observed just one failure, filed an issue for it https://github.com/cockroachdb/cockroach/issues/133142

**Pull request closed without merging**
