### PR TITLE
sql: Implement a more verbose EXPLAIN for SELECT nodes.

### PR DESCRIPTION
**Pull request by knz**
This is motivated by a few factors:
- the select node is responsible for filters and computations.  When there are multiple stages, it clarifies matter to see where in the plan these operations take place. Consider for example `UPDATE t SET x  = y + 1` on a table with columns `x` and `y`. Is the UPDATE node responsible to compute `y+1`?

Compare the outputs:

```
explain update t set x=y+1;
+-------+--------+------------------------+
| Level |  Type  |      Description       |
+-------+--------+------------------------+
|     0 | update | set t (x) returning () |
|     1 | scan   | t@primary              |
+-------+--------+------------------------+
```

and

```
explain update t set x=y+1;
+-------+--------+------------------------+
| Level |  Type  |      Description       |
+-------+--------+------------------------+
|     0 | update | set t (x) returning () |
|     1 | select | (x, y, rowid, y + 1)@t |
|     2 | scan   | t@primary              |
+-------+--------+------------------------+
```

This shows that the computation is not performed by the `update` node itself.
- it is desirable to know which columns are being manipulated at each stage of the query plan: aren't there too many? Where is an intermediate result computed?

For example:

```
explain select max(x) from t group by x order by x+10;
+-------+--------+-----------------------+
| Level |  Type  |      Description      |
+-------+--------+-----------------------+
|     0 | sort   | +x + 10               |
|     1 | group  | max(x), x             |
|     2 | scan   | t@primary             |
+-------+--------+-----------------------+
```

This suggests (wrongly) that the sort node is computing the expression x+1. However once we display the select node:

```
explain select max(x) from t group by x order by x+10;
+-------+--------+-----------------------+
| Level |  Type  |      Description      |
+-------+--------+-----------------------+
|     0 | sort   | +x + 10               |
|     1 | group  | max(x), x             |
|     2 | select | (max(x), x + 10, x)@t |
|     3 | scan   | t@primary             |
+-------+--------+-----------------------+
```

it becomes clear where each expression is computed.

cc @RaduBerinde

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6057)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Thanks for the separate PR!  The change itself LGTM. I have my reservations (posted in #5903) about whether we should include this info in EXPLAIN. Maybe we want to introduce a more detailed EXPLAIN mode (`EXPLAIN (VERBOSE)` ?) - there is a bunch of other information we could put in there for various nodes that might be useful during development.

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6057#-:-KFKq_t7EGa-ExNC5zTF:1036969134)*

**Comment by petermattis** [comment]
I'm also not sure if we should change the default `EXPLAIN`, but I would be perfectly fine with an additional `EXPLAIN (VERBOSE)`. Note that this has precedence in the postgres `EXPLAIN` statement: http://www.postgresql.org/docs/9.5/static/sql-explain.html

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6057#-:-KFMJDDWjvrF1oM2X0d5:-717719503)*

**Comment by tamird** [comment]
There is a lot of text in this PR description that is absent from the commit message. Please include it all in the commit message.

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6057#-:-KFPJFX3_xYqPzsgGIsT:658244325)*

**Comment by knz** [comment]
I have refactored the code in 2 commits, one of which adds support for `EXPLAIN (VERBOSE)` and the other to expose the select node. Comments welcome.

**Comment by RaduBerinde** [comment]
Nice! This looks great! Thanks for adding it as a new mode, it will be useful - we can now add more stuff (like `orderingInfo`, `valNeededForCol`) without making the regular plans too heavy.
:lgtm: 

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6057#-:-KFdg3AAmlSO6SVWXz_d:-1803749104)*

**Comment by tamird** [comment]
Reviewed 23 of 23 files at r2, 2 of 2 files at r3, 3 of 3 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/explain.go, line 62 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6057#-KFdlcnfRQLR0a7YOn3x:-KFdlcng9rOUYIi4Ol9g:-280557519) ([raw file](https://github.com/cockroachdb/cockroach/blob/87ce4b5c386d17950decc6f744af77a81dbbe846/sql/explain.go#L62)):*
i think you need to log both - this error is currently lacking information. also, this needs a test (in this commit).

I also think this logic is incorrect - won't it currently allow nonsense like `EXPLAIN (TRACE, TRACE)`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6057)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/explain.go, line 62 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6057#-KFdlcnfRQLR0a7YOn3x:-KFdo7-gE1bAr-JI7lSR:336208325) ([raw file](https://github.com/cockroachdb/cockroach/blob/87ce4b5c386d17950decc6f744af77a81dbbe846/sql/explain.go#L62)):*
It fails if `mode` and `newMode` are not `explainNone`. In that case `mode` will be `explainTrace` and `newMode` will also be `explainTrace`.

The error in this case could be the generic `"invalid EXPLAIN options: %s", n` we had before

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6057)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/explain.go, line 62 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6057#-KFdlcnfRQLR0a7YOn3x:-KFfDuY69R9InGwLfDm9:-1809856391) ([raw file](https://github.com/cockroachdb/cockroach/blob/87ce4b5c386d17950decc6f744af77a81dbbe846/sql/explain.go#L62)):*
I clarified the error message.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6057)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/explain.go, line 62 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6057#-KFdlcnfRQLR0a7YOn3x:-KFfEcH4meu8n0yqdGOP:-1203997007) ([raw file](https://github.com/cockroachdb/cockroach/blob/87ce4b5c386d17950decc6f744af77a81dbbe846/sql/explain.go#L62)):*
Doesn't look like this changed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6057)*

**Comment by knz** [comment]
Yeah sorry the push was late. It's there now.

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r6, 2 of 2 files at r7, 2 of 2 files at r8, 3 of 3 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/explain.go, line 62 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6057#-KFdlcnfRQLR0a7YOn3x:-KFjBOsntkNcsMvn1GL4:-633218800) ([raw file](https://github.com/cockroachdb/cockroach/blob/87ce4b5c386d17950decc6f744af77a81dbbe846/sql/explain.go#L62)):*
Yeah, this still doesn't look right. It still allows nonsense like `(TRACE, TRACE)` and this error case is entirely untested.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6057)*

**Comment by knz** [comment]
Review status: 1 of 17 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/explain.go, line 62 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6057#-KFdlcnfRQLR0a7YOn3x:-KFkaLnfNACIhwa540gn:-922171206) ([raw file](https://github.com/cockroachdb/cockroach/blob/87ce4b5c386d17950decc6f744af77a81dbbe846/sql/explain.go#L62)):*
I have added a test. The test passes, so the logic seems correct. What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6057)*

**Comment by tamird** [comment]
Reviewed 13 of 16 files at r10, 3 of 3 files at r11.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/explain.go, line 62 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6057#-KFdlcnfRQLR0a7YOn3x:-KFkbKl17qfGh_HQdsj1:676834233) ([raw file](https://github.com/cockroachdb/cockroach/blob/87ce4b5c386d17950decc6f744af77a81dbbe846/sql/explain.go#L62)):*
LGTM

---

*[sql/testdata/explain, line 44 \[r10\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6057#-KFkbG4LG31xKkc4Wg4z:-KFkbG4LG31xKkc4Wg5-:-1764199180) ([raw file](https://github.com/cockroachdb/cockroach/blob/a402c001b16614dc9f71e1b195d13ae94bfe0c26/sql/testdata/explain#L44)):*
needs another case `EXPLAIN (DEBUG, TRACE) SELECT 1`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6057)*

**Comment by knz** [comment]
Review status: 14 of 17 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/testdata/explain, line 44 \[r10\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6057#-KFkbG4LG31xKkc4Wg4z:-KFkdmahsKYQiMT1l9bJ:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/a402c001b16614dc9f71e1b195d13ae94bfe0c26/sql/testdata/explain#L44)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6057)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r12.
Review status: 14 of 17 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6057#-:-KFoJvF8tAAY4qc3s5yY:1417088721)*

**Pull request merged**
