### PR TITLE
pkg/cli: Improve the latency impact of debug zip

### PR DESCRIPTION
**Pull request by sean-**
Release note (cli change): Use a new debug endpoint for obtaining stack information when running debug zip.

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
We are discussing an alternate approach that would get rid of `stacks.txt` (from `?debug=2`) but keep `stacks_with_labels.txt` (from `?debug=1`) over in [slack](https://cockroachlabs.slack.com/archives/C05VAJ5H3QS/p1699471492039549).

**Comment by sean-** [comment]
@nvanbenschoten PTAL

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114088#-:-NiqNyXi-68J7d-lh-e6:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier)

**Comment by dhartunian** [comment]
Tracking follow-up for cli flag here: https://github.com/cockroachdb/cockroach/issues/114215

**Review by dhartunian — APPROVED** [review]
:lgtm: thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114088#-:-Nirbkoy5YeKRyzey8_T:brfqlux)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @abarganier)

**Comment by nvanbenschoten** [comment]
@sean- do we want to get this merged and backported?

**Comment by sean-** [comment]
@nvanbenschoten Yes, we should.  I think there are going to be multiple steps and flags required to get `debug zip` down to zero impact, and we should take those steps as we encounter them.

**Comment by rickystewart** [comment]
bors r-

Many failing tests

**Comment by dt** [comment]
Err, we use `stacks.txt` pretty heavily in escalations. This will be pretty rough to remove unconditionally. Can we _at the very least_ make this an option, preferably defaulting on?

**Review by dt — CHANGES_REQUESTED** [review]
I think we need to vet a change like this with TSE and every team's L2s since getting a multi-gb debug.zip just to realize it doesn't contain something you needed is pretty bad.

**Comment by nvanbenschoten** [comment]
> We use `stacks.txt` pretty heavily in escalations

Is `stacks_with_labels.txt` insufficient for these use cases? Is that because we rely on the goroutine waiting durations in the stack dump?

**Comment by dt** [comment]
> Is that because we rely on the goroutine waiting durations in the stack dump?

yeah, the waiting durations are the big one; if we know, say, a job got stuck 27mins ago, often it is stuck on a request, i.e. it is just in distsender / grpc.waitOnHeader for 290 minutes. We usually then correlate that with some other stack in store.go or something that is also 290 minutes to find the other side of that rpc.

with_labels.txt also doesn't have the goroutine IDs which we often line up with log lines, or changes between two captures (to see if it moved). The infinite loop in upgrades for example we were able to see the same goroutine was spinning in the same txn a day later which told us we were stuck in that loop.

**Pull request closed without merging**
