### PR TITLE
coltypes: don't shallow copy decimals

### LINKED ISSUE #39540: sql: panic: runtime error: index out of range
```
CREATE TABLE IF NOT EXISTS tab_orig AS
	SELECT
		g % 2 = 0 AS _bool, g::DECIMAL AS _decimal
	FROM
		generate_series(0, 5) AS g;

SET vectorize = experimental_on;

SELECT
	tab_426212._decimal - tab_426216._decimal
FROM
	tab_orig AS tab_426212,
	tab_orig AS tab_426214,
	tab_orig
	RIGHT JOIN tab_orig AS tab_426216 ON true
ORDER BY
	tab_426214._bool ASC;
```

```
panic: runtime error: index out of range [recovered]
	panic: panic while executing 1 statements: SELECT _._ - _._ FROM _ AS _, _ AS _, _ RIGHT JOIN _ AS _ ON _ ORDER BY _._ ASC; caused by runtime error: index out of range

goroutine 554 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc001877b00, 0x4599760, 0xc00191c700, 0x38922e0, 0x6656f00)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:727 +0x330
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc001877b00, 0x4599760, 0xc00191c700)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:440 +0x61
panic(0x38922e0, 0x6656f00)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
math/big.nat.itoa(0xc000398b20, 0x1, 0x1, 0xc0004c2a00, 0xa, 0x0, 0xc0003660a0, 0x2)
	/usr/local/go/src/math/big/natconv.go:332 +0x562
math/big.(*Int).Text(...)
	/usr/local/go/src/math/big/intconv.go:24
math/big.(*Int).String(...)
	/usr/local/go/src/math/big/intconv.go:37
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/apd.(*Decimal).Append(0xc00110a000, 0xc0003660c0, 0x1, 0xa, 0x47, 0x0, 0x2, 0xa)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/apd/format.go:60 +0x1d3
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/apd.(*Decimal).Text(...)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/apd/format.go:30
github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/apd.(*Decimal).String(...)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/apd/format.go:36
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*DDecimal).Format(0xc00110a000, 0xc001924240)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/datum.go:1012 +0xcd
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FmtCtx).formatNodeOrHideConstants(0xc001924240, 0x45253a0, 0xc00110a000)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/hide_constants.go:43 +0xab
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FmtCtx).FormatNode(0xc001924240, 0x45253a0, 0xc00110a000)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/format.go:345 +0x95
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*writeBuffer).writeLengthPrefixedDatum(0xc001a087c0, 0x45fa120, 0xc00110a000)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/write_buffer.go:121 +0x78
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*writeBuffer).writeTextDatum(0xc001a087c0, 0x4599820, 0xc0016c8b40, 0x45fa120, 0xc00110a000, 0x6679a60, 0x0, 0x2)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/types.go:123 +0xee0
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).bufferRow(0xc001a08000, 0x4599820, 0xc0016c8b40, 0xc00162c000, 0x1, 0x1, 0x0, 0x0, 0x0, 0x6679a60, ...)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:1095 +0x315
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*commandResult).AddRow(0xc001a08668, 0x4599820, 0xc0016c8b40, 0xc00162c000, 0x1, 0x1, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/command_result.go:179 +0x1b4
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLReceiver).Push(0xc0015d6000, 0xc0017e2ae0, 0x1, 0x1, 0x0, 0xc000000000)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:672 +0xa67
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.Run(0x4599760, 0xc001596880, 0x45ac120, 0xc000b8f100, 0x45742a0, 0xc0015d6000)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:174 +0x5e
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run(0xc000b8f100, 0x4599760, 0xc001596880)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:793 +0x92
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Run(0xc001628a20, 0x4599820, 0xc0017e2480, 0x3e55f80, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:584 +0x1ec
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc0002883c0, 0xc001599620, 0xc000c505a0, 0xc001aac870, 0xc0015d6000, 0xc001877f28, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:333 +0x381
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc0002883c0, 0x4599820, 0xc0016c8b40, 0xc001877f28, 0xc001599620, 0xc000c505a0, 0x459b5e0, 0xc0016287e0, 0xc0015d6000, 0xc001877cd8)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:942 +0x20a
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc001877b00, 0x4599820, 0xc0016c8b40, 0xc001877e50, 0x3, 0x7f1b0bd7d4c8, 0xc001a08668, 0xc001aaca01, 0x0, 0x0, ...)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:812 +0x370
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc001877b00, 0x4599820, 0xc0016c8b40, 0xc001877e50, 0x7f1b0bd7d4c8, 0xc001a08668, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:700 +0x75b
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc001877b00, 0x4599820, 0xc0016c8b40, 0x45a5a20, 0xc00102fe00, 0xc0017a7533, 0xbc, 0x0, 0x4, 0x0, ...)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:416 +0xb64
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc001877b00, 0x4599820, 0xc0016c8b40, 0x45a5a20, 0xc00102fe00, 0xc0017a7533, 0xbc, 0x0, 0x4, 0x0, ...)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:98 +0x4ec
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc001877b00, 0x4599760, 0xc00102fe40, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1211 +0x1aba
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc001877b00, 0x4599760, 0xc00191c700, 0xc000500e80, 0x5400, 0x15000, 0xc000500f18, 0xc0018ee6f0, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1140 +0x1a3
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc000832d80, 0x4599760, 0xc00191c700, 0xc001877b00, 0x5400, 0x15000, 0xc000500f18, 0xc0018ee6f0, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:442 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1(0xc00186120f, 0xc0018e94e0, 0x4599760, 0xc00191c700, 0xc0018ee6f0, 0xc000832d80, 0xc001a08000, 0x45a3fa0, 0xc0018e94c0, 0xc001924300, ...)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:584 +0x21c
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:513 +0x17b
```

### LINKED ISSUE #39777: exec: make sure decimal copies, appends and sets don't just shallow copy the object.
@jordanlewis

### PR DESCRIPTION
**Pull request by jordanlewis**
This commit fixes a correctness bug caused by illegal shallow copy of
decimals. To copy a decimal, you must use the .Set method on it, and its
memory must already be distinct from the source decimal.

To facilitate this and generally simplify things, the "safe" GET method
is removed and replaced by COPYVAL, which copies a scalar value to
another scalar value safely. There were fewer than 5 users of GET, so
this wasn't particularly disruptive.

Closes #39777.
Closes #39540.

Release note: None

### CODE REVIEW

**Review by madelynnblue — APPROVED** [review]

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40335)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/col/coltypes/types.go, line 201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40335#-LnTfFJG2LMjjQ3nsWEh:-LnTfFJG2LMjjQ3nsWEi:b-90d2kn) ([raw file](https://github.com/cockroachdb/cockroach/blob/b60e87696df5304c83a488a8b701a511f3c39105/pkg/col/coltypes/types.go#L201)):*
> ```Go
> tmp.Set(&%[1]s[%[2]s])
> %[1]s[%[2]s].Set(&%[1]s[%[3]s])
> %[1]s[%[3]s].Set(&%[1]s[%[2]s])`, target, i, j)
> ```

not sure if this is terribly readable -- you could consider using the inline templating idea that you have me for overloads.go

also, i think for the multiline ones it would be nicer to have some consistent indentation -- like:

```
return fmt.Sprintf(`
  var tmp apd.Decimal
  tmp.Set(&%[1]s[%[2]s])
  %[1]s[%[2]s].Set(&%[1]s[%[3]s])
`
```
___
*[pkg/col/coltypes/types.go, line 221 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40335#-LnTfR632QFzPt3R1DTm:-LnTfR632QFzPt3R1DTn:bb3j8m8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b60e87696df5304c83a488a8b701a511f3c39105/pkg/col/coltypes/types.go#L221)):*
> ```Go
> 	case Decimal:
> 		return fmt.Sprintf(`
> __tgt_slice := %[1]s[%[2]s:]
> ```

i guess it's fine that these variables share the outer scope? in overloads.go i had been introducing a new scope for all the cases where i defined a new variable, just to be safe, but maybe that's overkill?

**Review by jordanlewis — COMMENTED** [review]
Okay, I redid this to be better with the templates.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40335#-:-LnUrYSE5DVNVaCFpiEG:bo8tlow)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @yuzefovich)

___
*[pkg/col/coltypes/types.go, line 201 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40335#-LnTfFJG2LMjjQ3nsWEh:-LnUrXk87vqsfPGPaqyp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b60e87696df5304c83a488a8b701a511f3c39105/pkg/col/coltypes/types.go#L201)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

not sure if this is terribly readable -- you could consider using the inline templating idea that you have me for overloads.go

also, i think for the multiline ones it would be nicer to have some consistent indentation -- like:

```
return fmt.Sprintf(`
  var tmp apd.Decimal
  tmp.Set(&%[1]s[%[2]s])
  %[1]s[%[2]s].Set(&%[1]s[%[3]s])
`
```
</blockquote></details>

Done.
___
*[pkg/col/coltypes/types.go, line 221 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40335#-LnTfR632QFzPt3R1DTm:-LnUrX6K44rqKSNnSZDN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b60e87696df5304c83a488a8b701a511f3c39105/pkg/col/coltypes/types.go#L221)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i guess it's fine that these variables share the outer scope? in overloads.go i had been introducing a new scope for all the cases where i defined a new variable, just to be safe, but maybe that's overkill?
</blockquote></details>

Done.

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 8 of 9 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40335)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rafiss)

___
*[pkg/col/coltypes/types.go, line 196 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40335#-LnZMNiNCUspJe--oRty:-LnZMNiNCUspJe--oRtz:b-7duevl) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fde2d80177e4672f3f2192f17b173dde63b6390/pkg/col/coltypes/types.go#L196)):*
> ```Go
> 
> // Swap is a function that should only be used in templates.
> func (t T) Swap(target, i, j string) string {
> ```

I'm proposing to remove this function in the `cleanup-vec` PR.
___
*[pkg/sql/logictest/testdata/logic_test/vectorize, line 705 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40335#-LnZNYwd7ANbvdAIkZ_F:-LnZNYwd7ANbvdAIkZ_G:b9zwiu8) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fde2d80177e4672f3f2192f17b173dde63b6390/pkg/sql/logictest/testdata/logic_test/vectorize#L705)):*
> ```
> 	tab_426214._bool ASC
> ----
> 1296 values hashing to cad02075a867c3c0564bf80fe665eed6
> ```

Huh, what is this output?

**Comment by jordanlewis** [comment]
> Huh, what is this output?

You can have logic test compare the hash of the output to avoid having to write all of the rows, since in this case there are many.

**Comment by jordanlewis** [comment]
PTAL - I think this is ready to go.

**Review by rafiss — APPROVED** [review]
> Reviewed 12 of 12 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40335)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rafiss)

**Comment by jordanlewis** [comment]
Thanks for the reviews!

bors r+

**Pull request merged**
