### PR TITLE
coldata: minor tweak of flat bytes

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit changes `maybeBackfillOffsets` to update `maxSetIndex`
accordingly (this might be a minor performance improvement). In a sense,
when we're backfilling offsets, we *are* setting indices to point to
empty `[]byte` slices. Also, the logic for `Set` method is slightly
refactored.

Release note: None

### CODE REVIEW

**Review by asubiotto — COMMENTED** [review]
Not sure I understand the justification for this change. Doesn't this unnecessarily restrict `Sets`?

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45426#-:-M11SR4qAMnwvY2tyzcO:b-vr71ep)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by yuzefovich — COMMENTED** [review]
Restrict in what way? I don't think that there is any actual change in behavior, but the code seems cleaner.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45426#-:-M11Soxq5tq2DUY95nIU:bwo07mj)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45426#-:-M1CXTzHDACirIa5bVC4:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
