### PR TITLE
cli/demo: fix enterprise features for multitenancy

### LINKED ISSUE #40434: cli: update demo error message for expired license
Demo now uses enterprise licenses by default. It comes with a one hour limit. If you attempt to use a feature that requires an enterprise license, you will receive this message:
```
pq: Use of replication zones on indexes or partitions requires an enterprise license. Your evaluation license expired on September 3, 2019. If you're interested in getting a new license, please contact subscriptions@cockroachlabs.com and we can help you out.
```

This may be confusing to demo users since they do not expressly get a license and its confusing that the license message will be for the same day. 

We should enhance this message to say something like this for demo:
```
Your enterprise license for Cockroach Demo expired after 1 hour. To obtain a full trial license click here or reach out to subscriptions@cockroachlabs.com and we can help you out.
```

Jira issue: CRDB-6341

### LINKED ISSUE #80270: cockroach demo  --geo-partitioned-replicas fails with license error
```
[andrei:~/src/github.com/cockroachdb/cockroach] park+ ± ./cockroach demo  --geo-partitioned-replicas
...
# Partitioning the demo database, please wait...
*
* ERROR: partitioning the demo database: pq: license for cluster(s) a97a31f4-71ef-4a2e-ad11-b76eaccc81e3 is not valid for cluster a97a31f4-71ef-4a2e-55d9-ada0d4e6b842
```

Notice that the two cluster IDs start the same.

(Btw, is --geo-partitioned-replicas how I'm supposed to get a multi-region demo these days)?

### PR DESCRIPTION
**Pull request by knz**
First commit from #81762.

Fixes #80270.
Fixes #40434.

This patch achieves two things:

- it ensures that enterprise features work properly in multi-tenant `cockroach
  demo` when `--disable-demo-license` is not passed as argument.
- it ensures `cockroach demo` does not require a working licensing
  endpoint to run (by not retrieving a license over the network on startup).

The net result will be less spurious failures in CI, as well as
avoiding startup delays/errors during interactive uses, which provide
poor UX.

Release note: None

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
this is great! do you think the change is backportable? the field teams have said that the call to the license server is a problem for them, since we don't have good SLAs for that license server and it has gone down in the past.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81737#-:-N2wBwerEeBgMh7xrmzV:brqyldx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

**Comment by knz** [comment]
Yes this is backportable. As-is to 22.1, and then with a new custom patch to 21.2 and earlier.

**Comment by knz** [comment]
bors r=rafiss

**Comment by rafiss** [comment]
sounds good -- FWIW, there are no more scheduled 21.1.x releases.

**Pull request merged**
