### PR TITLE
[2.1 backport] rocksdb: Include fix on improving SST IDs used in cache keys

### PR DESCRIPTION
**Pull request by itsbilal**
Bumps up commit of RocksDB fork to pick up
https://github.com/cockroachdb/rocksdb/pull/63 . This should resolve
some issues observed around out-of-order insertion of keys in SSTables.

Release note (bug fix): Fix a rare data corruption bug in RocksDB
caused by newer Linux kernel's handling of i_generation on certain
filesystems

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
LGTM

**Comment by garvitjuniwal** [comment]
thanks for the fix @itsbilal  and @petermattis 

does this bug also affect release-2.0? i'm wondering if a backport to 2.0 is also necessary or not.

**Comment by petermattis** [comment]
@garvitjuniwal Yes, I believe this bug affects all versions of RocksDB, so 2.0 as well. @itsbilal Can you backport to 2.0? @garvitjuniwal We're not currently making new 2.0 releases, but I believe that is ok in your case, correct?

**Comment by garvitjuniwal** [comment]
Yes @petermattis. We can merge your 2.0 backport into our internal branch and use it. We don't need a new release. Thank you!

**Comment by itsbilal** [comment]
@garvitjuniwal 2.0 backport is in progress: https://github.com/cockroachdb/rocksdb/pull/65

Once this is in, I'll push a commit to update the rocksdb ref in `release-2.0` in the cockroach repo to point to the patched version. You should then be able to merge that in.

**Comment by garvitjuniwal** [comment]
Thanks @itsbilal

**Pull request merged**
