### PR TITLE
cli: add comment, simplify tests

### PR DESCRIPTION
**Pull request by spencerkimball**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14526)

### CODE REVIEW

**Review by tamird — APPROVED** [review]
Could you add a test?

**Comment by spencerkimball** [comment]
Added.

**Comment by tamird** [comment]
:lgtm: with optional suggestions

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/cli/cli.go, line 104 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14526#-KgaxHAIpob2wwAjNsmF:-KgaxHAIpob2wwAjNsmG:b-wq37dj) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fa6f5378593bdb11b14e01e7ff6d5636e665649/pkg/cli/cli.go#L104)):*
> ```Go
> 			return err
> 		}
> 		fmt.Fprintf(c.OutOrStderr(), "\n") // provide a line break between usage and error
> ```

TIL.

Also FYI there is [`fmt.Fprintln`](https://godoc.org/fmt#Fprintln)

---

*[pkg/cli/cli_test.go, line 1160 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14526#-Kgaxctn8YVX4oQ5lhQi:-Kgaxctn8YVX4oQ5lhQj:b-yj7maw) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fa6f5378593bdb11b14e01e7ff6d5636e665649/pkg/cli/cli_test.go#L1160)):*
> ```Go
> 	for _, test := range testCases {
> 		t.Run(strings.Join(test.flags, ","), func(t *testing.T) {
> 			// Override os.Stdout or os.Stderr with our own.
> ```

while you're here, looks like you can avoid all these shenanigans by using [`cockroachCmd.SetOutput`](https://godoc.org/github.com/spf13/cobra#Command.SetOutput) rather than overriding os.Stdout/Stderr. I noticed that was possible thanks to your use of `OutOrStderr()` above.

---

*[pkg/cli/cli_test.go, line 1183 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14526#-KgayH2pucaQaoYDiy_M:-KgayH2pucaQaoYDiy_N:bq517pl) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fa6f5378593bdb11b14e01e7ff6d5636e665649/pkg/cli/cli_test.go#L1183)):*
> ```Go
> 			go func() {
> 				// Copy reads 'r' until EOF is reached.
> 				_, _ = io.Copy(&buf, r)
> ```

while you're here, it would be good to check the error, since it's never `io.EOF`. `done` can be `chan error`.

---

*[pkg/cli/cli_test.go, line 1188 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14526#-KgayQNHGzwN87UX_2ws:-KgayQNHGzwN87UX_2wt:bf9mu2q) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fa6f5378593bdb11b14e01e7ff6d5636e665649/pkg/cli/cli_test.go#L1188)):*
> ```Go
> 
> 			if err := Run(test.flags); err != nil && !test.expErr {
> 				fmt.Fprintf(w, "%s\n", err)
> ```

optional: `Fprintln`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14526#-:-KgayWtSMOnET7aTXsWC:b1k1k8q)*

**Comment by spencerkimball** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/cli/cli.go, line 104 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14526#-KgaxHAIpob2wwAjNsmF:-KgfPV5FLjs5n7y_Eee4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fa6f5378593bdb11b14e01e7ff6d5636e665649/pkg/cli/cli.go#L104)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

TIL.

Also FYI there is [`fmt.Fprintln`](https://godoc.org/fmt#Fprintln)
</blockquote></details>

Done.

---

*[pkg/cli/cli_test.go, line 1160 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14526#-Kgaxctn8YVX4oQ5lhQi:-KgfPuX7GXLpFnUgFM0q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fa6f5378593bdb11b14e01e7ff6d5636e665649/pkg/cli/cli_test.go#L1160)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

while you're here, looks like you can avoid all these shenanigans by using [`cockroachCmd.SetOutput`](https://godoc.org/github.com/spf13/cobra#Command.SetOutput) rather than overriding os.Stdout/Stderr. I noticed that was possible thanks to your use of `OutOrStderr()` above.
</blockquote></details>

Done.

---

*[pkg/cli/cli_test.go, line 1183 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14526#-KgayH2pucaQaoYDiy_M:-KgfQ3ad9D2OARPyolUe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fa6f5378593bdb11b14e01e7ff6d5636e665649/pkg/cli/cli_test.go#L1183)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

while you're here, it would be good to check the error, since it's never `io.EOF`. `done` can be `chan error`.
</blockquote></details>

Done.

---

*[pkg/cli/cli_test.go, line 1188 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14526#-KgayQNHGzwN87UX_2ws:-KgfQ8RosNaYZ3qMjl48:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fa6f5378593bdb11b14e01e7ff6d5636e665649/pkg/cli/cli_test.go#L1188)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

optional: `Fprintln`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14526)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/cli/cli_test.go, line 1160 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14526#-Kgaxctn8YVX4oQ5lhQi:-KgfRNgCp6OmCNy_Ou7Z:b-83sjo4) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fa6f5378593bdb11b14e01e7ff6d5636e665649/pkg/cli/cli_test.go#L1160)):*
<details><summary><i>Previously, spencerkimball (Spencer Kimball) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nice.

---

*[pkg/cli/cli_test.go, line 1161 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14526#-KgfRqUKw2UpvsbvNpDg:-KgfRqULOwnIf-xSZXLA:bti40nq) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a1d29eb9a90332754a0e021e19ccb60ce59e1e2/pkg/cli/cli_test.go#L1161)):*
> ```Go
> 		t.Run(strings.Join(test.flags, ","), func(t *testing.T) {
> 			// Override os.Stdout or os.Stderr with our own.
> 			r, w, _ := os.Pipe()
> ```

check this error? (not your code - sorry)

---

*[pkg/cli/cli_test.go, line 1162 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14526#-KgfRIdsFDRC5ds4eaPh:-KgfRIdsFDRC5ds4eaPi:b-frbr6l) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a1d29eb9a90332754a0e021e19ccb60ce59e1e2/pkg/cli/cli_test.go#L1162)):*
> ```Go
> 			// Override os.Stdout or os.Stderr with our own.
> 			r, w, _ := os.Pipe()
> 			cockroachCmd.SetOutput(w)
> ```

do you need to undo this at the end of the test? if yes, you can `defer cockroachCmd.SetOutput(nil)`

---

*[pkg/cli/cli_test.go, line 1174 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14526#-KgfRiTp5fnN1gpg_G-n:-KgfRiTp5fnN1gpg_G-o:b6ytrxq) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a1d29eb9a90332754a0e021e19ccb60ce59e1e2/pkg/cli/cli_test.go#L1174)):*
> ```Go
> 
> 			if err := Run(test.flags); err != nil && !test.expErr {
> 				fmt.Fprintln(w, "%s", err)
> ```

shouldn't this `t.Fatal`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14526)*

**Comment by spencerkimball** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/cli/cli_test.go, line 1161 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14526#-KgfRqUKw2UpvsbvNpDg:-KgfXX-3OEexZpyEgCPh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a1d29eb9a90332754a0e021e19ccb60ce59e1e2/pkg/cli/cli_test.go#L1161)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

check this error? (not your code - sorry)
</blockquote></details>

Done.

---

*[pkg/cli/cli_test.go, line 1162 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14526#-KgfRIdsFDRC5ds4eaPh:-KgfXW_9AxZUyuU44Zpk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a1d29eb9a90332754a0e021e19ccb60ce59e1e2/pkg/cli/cli_test.go#L1162)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

do you need to undo this at the end of the test? if yes, you can `defer cockroachCmd.SetOutput(nil)`
</blockquote></details>

Done.

---

*[pkg/cli/cli_test.go, line 1174 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14526#-KgfRiTp5fnN1gpg_G-n:-KgfXWGDJlU3FKj-L4fz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a1d29eb9a90332754a0e021e19ccb60ce59e1e2/pkg/cli/cli_test.go#L1174)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

shouldn't this `t.Fatal`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14526)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14526)*

**Pull request merged**
