### PR TITLE
ui: move shared graph components to cluster-ui

### PR DESCRIPTION
**Pull request by xinhaoz**
Part of #74516

This commit moves shared graph functions and components to
cluster-ui package. This is to enable the new bar chart
component to share axes utilities and containers with
the older line graph component in db-console.

Release note: None

### CODE REVIEW

**Review by maryliag — APPROVED** [review]
:lgtm: 

> Reviewed 5 of 11 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80197#-:-N02pTzR588swFBPYd55:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag)

**Review by jocrl — COMMENTED** [review]
Small nit, otherwise :lgtm: !

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80197#-:-N02q1x159AQAjTcI1W0:b-7i93s)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @jocrl, @maryliag, and @xinhaoz)

___
*[pkg/ui/workspaces/cluster-ui/src/graphs/visualization/index.tsx, line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80197#-N02ox0Z76qHs4FuxL-d:-N02ox0Z76qHs4FuxL-e:b-6dyiuh) ([raw file](https://github.com/cockroachdb/cockroach/blob/eeacd4b8e2953fff80cbb59294767e0e6fb5d572/pkg/ui/workspaces/cluster-ui/src/graphs/visualization/index.tsx#L37)):*
> ```XML
>  * as a title and a tooltip icon.
>  */
> export const Visualization: React.FC<VisualizationProps> = ({
> ```

Thanks for the clean up!
___
*[pkg/ui/workspaces/db-console/src/views/cluster/util/graphs.ts, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80197#-N02lcRwCggM146TXrZu:-N02lcRwCggM146TXrZv:b-va0llh) ([raw file](https://github.com/cockroachdb/cockroach/blob/996f52c2c411df0191ddb97628ef30e5e76a5751/pkg/ui/workspaces/db-console/src/views/cluster/util/graphs.ts#L31)):*
> ```XML
>   MetricProps,
>   QueryTimeInfo,
> } from "src/views/shared/components/metricQuery";
> ```

nit: Should the db console copy of `AxisUnits` be deleted, and have the existing usages import from cluster-ui?

**Comment by xinhaoz** [comment]
*[pkg/ui/workspaces/db-console/src/views/cluster/util/graphs.ts, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80197#-N02lcRwCggM146TXrZu:-N073kyw3aed33JP3vHx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/996f52c2c411df0191ddb97628ef30e5e76a5751/pkg/ui/workspaces/db-console/src/views/cluster/util/graphs.ts#L31)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

nit: Should the db console copy of `AxisUnits` be deleted, and have the existing usages import from cluster-ui?
</blockquote></details>

Done.

**Comment by jocrl** [comment]
*[pkg/ui/workspaces/db-console/src/views/cluster/util/graphs.ts, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80197#-N02lcRwCggM146TXrZu:-N078HJL5PWWu4L2kpvv:bsycgsa) ([raw file](https://github.com/cockroachdb/cockroach/blob/996f52c2c411df0191ddb97628ef30e5e76a5751/pkg/ui/workspaces/db-console/src/views/cluster/util/graphs.ts#L31)):*
<details><summary><i>Previously, xinhaoz (Xin Hao Zhang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Mmm is this just me/reviewable, or does it seem like these changes weren't done/pushed?

**Comment by xinhaoz** [comment]
*[pkg/ui/workspaces/db-console/src/views/cluster/util/graphs.ts, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80197#-N02lcRwCggM146TXrZu:-N07At-DCuYYM45I7EVg:b-92upca) ([raw file](https://github.com/cockroachdb/cockroach/blob/996f52c2c411df0191ddb97628ef30e5e76a5751/pkg/ui/workspaces/db-console/src/views/cluster/util/graphs.ts#L31)):*
<details><summary><i>Previously, jocrl (Josephine) wrote…</i></summary><blockquote>

Mmm is this just me/reviewable, or does it seem like these changes weren't done/pushed?
</blockquote></details>

Oh my bad, didn't push. Done!

**Review by jocrl — APPROVED** [review]
Thanks! :lgtm: :)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80197#-:-N07BSRL9hzmwcqIo37d:br9b95i)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @jocrl and @maryliag)

**Comment by xinhaoz** [comment]
TFTR!
bors r=jocrl,maryliag

**Pull request merged**
