### PR TITLE
gossip: remove groups!

### PR DESCRIPTION
**Pull request by tamird**
Turns out we're not using this. Thoughts?

### CODE REVIEW

**Comment by thschroeter** [comment]
@tamird, turns out I also had a branch without groups to simplify.

Since every node in the cluster can make it's own local observation of the state of the world, and these observations can be combined and captured in groups, groups will probably be necessary for failure detection in some form (if gossip will be used). Also, being able to observe global minima and maxima (e.g. disk and CPU load) is useful. Therefore, I didn't propose group removal. But it might be a good idea to remove groups now and potentially re-enable them later.

**Comment by mrtracy** [comment]
Group functionality was created a year and a half ago, before almost anything else in the system, and they still haven't been used.  As far as I can tell, there's also no near-term demand to start using them.

Gossip code is badly in need of a refactoring. It's the oldest package in cockroach, but it's never received  a refactoring; most other packages have been majorly refactored, some multiple times. This indicates that the majority of the functionality in the package is simply not being used.

I'm in favor of stripping it down to the central core, refactoring that (to something more consistent with the quality of our other packages), and adding features back as they are needed.

**Comment by tschottdorf** [comment]
yeah, rip it out. Whatever goes now can be rewritten later. The code isn't gone, just not in master any more.

**Comment by tamird** [comment]
@spencerkimball WDYT?

**Comment by spencerkimball** [comment]
I have no immediate plans for their use. The idea behind them was to support decisions in the face of truly large clusters, but no sense in having complexity where it's not necessary [yet].

**Pull request merged**
