### PR TITLE
distsql: fix join expression in planning 

### PR DESCRIPTION
**Pull request by RaduBerinde**
Forgot to remap ordinal references in the join expression. Logic tests with `COCKROACH_DISTSQL_MODE=on` pass again.

Any thoughts on making a `Logic` test run in DISTSQL mode as part of the tests? I didn't do it because I hate to add 20-30s to `make test`, I think it might be time to put tests into groups (e.g. must-run vs only-run-if-you-changed-this-package).

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12423)

### CODE REVIEW

**Comment by irfansharif** [comment]
:lgtm: was running into both these thinking I broke something. Have little to no context into what test groups look like but I assume if you're introducing `ARRAY_AGG` for e.g. something should break in your PR and you `t.Skip()` *only* `distsql` execution.

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12423#-:-KZ31GHYPt30pxOHRwRw:b8wvpso)*

**Comment by irfansharif** [comment]
wait, ignore my `t.Skip()` comment. Evidently I've already forgotten how TestLogic works.

**Comment by RaduBerinde** [comment]
Merged with @irfansharif's changes. There is a huge join testcase that we now try to run with DistSQL and it times out (we don't yet do memory accounting).

**Comment by irfansharif** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12423#-:-KZ8AcN_QSXBtk4UI7qI:bnfp4nl)*

**Pull request merged**
