### PR TITLE
distsql: add support for semijoins in HashJoiner

### PR DESCRIPTION
**Pull request by pbardea**
Part of issue #19450

Semi join is an operation which given a left and right relation L and R,
returns 'the set of all tuples in L for which there is a tuple in R that
is equal on their common attribute names.'[1]

When the semi join hashes the left side, the marked rows are iterate
through again at the end and selected.When doing the scan of
the right input, if a marked row is seen it can just skip it. [2]

It would be used for queries such as:
```
CREATE t1 (a int, b int); CREATE t2 (c int, d int);
SELECT a FROM t1 WHERE a IN (SELECT c FROM t2);
```
which would translate to something like `semiJoin(t1, t2, ON a = c)`

[1] https://en.wikipedia.org/wiki/Relational_algebra#Semijoin
[2] https://en.wikipedia.org/wiki/Hash_join#Hash_right_semi-join

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
@pbardea Generally looks good. I've left a few small comments below and still need to look at the new test cases. The `Release note` is a bit inaccurate. This isn't a performance improvement (yet). It isn't user visible because we never plan semi-joins. I don't know if we have a policy about what to include in the release notes for a non-visible change, but I'd err on the side of `Release note: none`.

---

Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 547 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-L30KwnRZmZwBu1Z8_ew:-L30KwnRZmZwBu1Z8_ex:b72ccwd) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0dadd3a6fc36d9a7e819e2996074464e056204/pkg/sql/distsqlrun/hashjoiner.go#L547)):*
> ```Go
> 			probeMatched = true
> 			shouldEmit := true
> 			if shouldMark(h.storedSide, h.joinType) {
> ```

The proliferation of special cases here is unfortunate. I don't have a concrete suggestion for a better approach, only an instinct that there is a better approach. Can you add a `TODO(peter): figure out a way to reduce this special casing below`?

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 551 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-L30NUsNaD-ztvBBVU-0:-L30NUsNaD-ztvBBVU-1:b-drjsfl) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0dadd3a6fc36d9a7e819e2996074464e056204/pkg/sql/distsqlrun/hashjoiner.go#L551)):*
> ```Go
> 					shouldEmit = false
> 				}
> 				// Mark the row on the stored side. The marked rows
> ```

Should this be in an `else` block? If `i.IsMarked(ctx)` is true, we don't need to mark the row again.

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 660 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-L30JHEMPecLJA4bF6hl:-L30JHEMPecLJA4bF6hm:b-i63psm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0dadd3a6fc36d9a7e819e2996074464e056204/pkg/sql/distsqlrun/hashjoiner.go#L660)):*
> ```Go
> 
> // Some types of joins need to mark rows that matched.
> func shouldMark(side joinSide, joinType joinType) bool {
> ```

I think `s/side/storedSide/g` would make this clearer.  I had to check a few times what `side` referred to.

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 663 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-L30KU4yLrx-yRv0sfSJ:-L30KU4yLrx-yRv0sfSK:bir79bn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0dadd3a6fc36d9a7e819e2996074464e056204/pkg/sql/distsqlrun/hashjoiner.go#L663)):*
> ```Go
> 	switch {
> 	case joinType == semiJoin && side == leftSide:
> 		fallthrough
> ```

Is there a reason to `fallthrough` vs `return true` here? 

---

*[pkg/sql/distsqlrun/joinerbase.go, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-L3-WNILTunllQMjnzxK:-L3-WNILTunllQMjnzxL:bdyknrs) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0dadd3a6fc36d9a7e819e2996074464e056204/pkg/sql/distsqlrun/joinerbase.go#L137)):*
> ```Go
> // For certain types of joins, such as SemiJoins, since the right input
> // may not be fully scanned, so the rows selected from the right relation are
> // non-deterministic and it doesn't make sense to output these columns.
> ```

This comment is confusing to me. We're not emitting the right columns for semi-join because that is the definition of semi-join (you only output the left columns). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-:-L30OBf5wPa8onY_e-i4:b-v5t7ye)*

**Comment by RaduBerinde** [comment]
Good work!

The distsqlrun tests in general are vary basic (because they're very tedious to write); we generally relied on `sql/logictest` for coverage. My suggestion is to consider (as a follow-up to this PR) implementing custom syntax to allow running semi-joins from logic tests (maybe SELECT x LEFT SEMI JOIN y`). Adding the planning code might be more work than it's worth, but we should at least consider it.

---

Review status: 0 of 7 files reviewed at latest revision, 13 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/base.go, line 40 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-L312fohUccKAbLHDQOo:-L312fohUccKAbLHDQOp:b-umwb9h) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc2c03575cd440d8a6eb2137d4613e289ddd2486/pkg/sql/distsqlrun/base.go#L40)):*
> ```Go
> 	rightOuter
> 	fullOuter
> 	semiJoin
> ```

This should be `leftSemiJoin` (i.e. ⋉ as opposed to ⋊)

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 547 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-L316Jgwd-LqlUeJI3_M:-L316JgxMvkie8Uoldp5:b-fnucht) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc2c03575cd440d8a6eb2137d4613e289ddd2486/pkg/sql/distsqlrun/hashjoiner.go#L547)):*
> ```Go
> 			probeMatched = true
> 			shouldEmit := true
> 			if shouldMark(h.storedSide, h.joinType) {
> ```

A comment explaining the logic as it pertains to semi-joins would be helpful.

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 554 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-L317KwrxyTW-94YJ50c:-L317KwrxyTW-94YJ50d:bj9djrx) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc2c03575cd440d8a6eb2137d4613e289ddd2486/pkg/sql/distsqlrun/hashjoiner.go#L554)):*
> ```Go
> 				// can then be iterated over for {right, left} outer joins
> 				// (depending on storedSide), full outer joins and the
> 				// unmarked rows for semi joins.
> ```

This doesn't sound right. We shouldn't need to iterate unmarked rows (that would be for an anti join).

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 673 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-L314-nB5NfrHECqM135:-L314-nB5NfrHECqM136:b1id9e2) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc2c03575cd440d8a6eb2137d4613e289ddd2486/pkg/sql/distsqlrun/hashjoiner.go#L673)):*
> ```Go
> // Some joins don't need to visit all possible tuples in the cross product
> // of the relations and can terminate early.
> func shouldShortCircuit(side joinSide, joinType joinType) bool {
> ```

The comment should be more explicit as to where the "side" fits into the short circuiting. Also, "terminate early" is misleading. 

---

*[pkg/sql/distsqlrun/joinerbase.go, line 73 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-L314eBP8Ho_3iE6lRZ5:-L314eBP8Ho_3iE6lRZ6:bxbuvvz) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc2c03575cd440d8a6eb2137d4613e289ddd2486/pkg/sql/distsqlrun/joinerbase.go#L73)):*
> ```Go
> 	size := len(leftTypes) + len(rightTypes) + jb.numMergedEqualityColumns
> 	if !shouldIncludeRight(jb.joinType) {
> 		size -= len(rightTypes)
> ```

[nit] reverse the condition instead of adding and then substracting

---

*[pkg/sql/distsqlrun/joinerbase.go, line 148 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-L314tm1XvpMdP-LDZGk:-L314tm1XvpMdP-LDZGl:b-tilxqs) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc2c03575cd440d8a6eb2137d4613e289ddd2486/pkg/sql/distsqlrun/joinerbase.go#L148)):*
> ```Go
> 	switch joinType {
> 	case semiJoin:
> 		fallthrough
> ```

[nit] just do `semiJoin, innerJoin: return false`

---

*[pkg/sql/distsqlrun/joinerbase.go, line 152 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-L314zcpJaVCuHxA1ZAN:-L314zcpJaVCuHxA1ZAO:b-92bzg1) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc2c03575cd440d8a6eb2137d4613e289ddd2486/pkg/sql/distsqlrun/joinerbase.go#L152)):*
> ```Go
> 		return false
> 	case rightOuter:
> 		if side == leftSide {
> ```

`return side == rightSide` is more straightforward

---

*[pkg/sql/distsqlrun/processors.proto, line 242 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-L315EJUEIfwL4KC4bS3:-L315EJUEIfwL4KC4bS4:b-a5mabj) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc2c03575cd440d8a6eb2137d4613e289ddd2486/pkg/sql/distsqlrun/processors.proto#L242)):*
> ```protobuf
>   FULL_OUTER = 3;
>   SEMI = 4;
> }
> ```

LEFT_SEMI

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-:-L312brVb7fF5WELMO0l:bv9wz4m)*

**Comment by pbardea** [comment]
Thanks for the review! I've updated the release notes as well as addressed the comments that were brought up.

---

Review status: 0 of 7 files reviewed at latest revision, 13 unresolved discussions.

---

*[pkg/sql/distsqlrun/base.go, line 40 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-L312fohUccKAbLHDQOo:-L33cp9fAswwuk33EiF8:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc2c03575cd440d8a6eb2137d4613e289ddd2486/pkg/sql/distsqlrun/base.go#L40)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This should be `leftSemiJoin` (i.e. ⋉ as opposed to ⋊)
</blockquote></details>

Updated.

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 663 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-L30KU4yLrx-yRv0sfSJ:-L33cfoii0r6fqrlKMVc:b-k1vh8h) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0dadd3a6fc36d9a7e819e2996074464e056204/pkg/sql/distsqlrun/hashjoiner.go#L663)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is there a reason to `fallthrough` vs `return true` here? 
</blockquote></details>

Nope. Updated to `return true`.

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 547 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-L316Jgwd-LqlUeJI3_M:-L33Xtob-EmJI8mltvx4:bx5s6sa) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc2c03575cd440d8a6eb2137d4613e289ddd2486/pkg/sql/distsqlrun/hashjoiner.go#L547)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

A comment explaining the logic as it pertains to semi-joins would be helpful.
</blockquote></details>

I've updated the comment in the if-statement below to explain the marking and emitting logic with respect to semi-joins.

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 554 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-L317KwrxyTW-94YJ50c:-L33apX1FCja9COCuq-O:b-bw8e14) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc2c03575cd440d8a6eb2137d4613e289ddd2486/pkg/sql/distsqlrun/hashjoiner.go#L554)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This doesn't sound right. We shouldn't need to iterate unmarked rows (that would be for an anti join).
</blockquote></details>

Updated.

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 673 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-L314-nB5NfrHECqM135:-L33auQixLAgigOxbXEO:b7cenfy) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc2c03575cd440d8a6eb2137d4613e289ddd2486/pkg/sql/distsqlrun/hashjoiner.go#L673)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The comment should be more explicit as to where the "side" fits into the short circuiting. Also, "terminate early" is misleading. 
</blockquote></details>

Updated the comment to explicit mention how the `storedSide` relates to short circuiting, as well as adding why it's necessary. I also explain more explicitly what "terminate early" means.

---

*[pkg/sql/distsqlrun/joinerbase.go, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-L3-WNILTunllQMjnzxK:-L33b5r80mbEkUXmqNiD:b-flsylk) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0dadd3a6fc36d9a7e819e2996074464e056204/pkg/sql/distsqlrun/joinerbase.go#L137)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This comment is confusing to me. We're not emitting the right columns for semi-join because that is the definition of semi-join (you only output the left columns). 
</blockquote></details>

Done. Simplified this comment to make it more clear.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-:-L33XTvhAOAg1Aetue5U:b3svudw)*

**Comment by pbardea** [comment]
Review status: 0 of 7 files reviewed at latest revision, 13 unresolved discussions.

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 547 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-L30KwnRZmZwBu1Z8_ew:-L33f9T5uoNz3I_4ETrb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0dadd3a6fc36d9a7e819e2996074464e056204/pkg/sql/distsqlrun/hashjoiner.go#L547)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The proliferation of special cases here is unfortunate. I don't have a concrete suggestion for a better approach, only an instinct that there is a better approach. Can you add a `TODO(peter): figure out a way to reduce this special casing below`?
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 551 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-L30NUsNaD-ztvBBVU-0:-L33fAu_0c7XGWMuqrPx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0dadd3a6fc36d9a7e819e2996074464e056204/pkg/sql/distsqlrun/hashjoiner.go#L551)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Should this be in an `else` block? If `i.IsMarked(ctx)` is true, we don't need to mark the row again.
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 660 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-L30JHEMPecLJA4bF6hl:-L33fC_3kTHEdC9NIQAC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec0dadd3a6fc36d9a7e819e2996074464e056204/pkg/sql/distsqlrun/hashjoiner.go#L660)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think `s/side/storedSide/g` would make this clearer.  I had to check a few times what `side` referred to.
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/joinerbase.go, line 73 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-L314eBP8Ho_3iE6lRZ5:-L33fFhJoa94ahUK2cGD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc2c03575cd440d8a6eb2137d4613e289ddd2486/pkg/sql/distsqlrun/joinerbase.go#L73)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] reverse the condition instead of adding and then substracting
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/joinerbase.go, line 148 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-L314tm1XvpMdP-LDZGk:-L33fGqPKu5hmnG9LcsA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc2c03575cd440d8a6eb2137d4613e289ddd2486/pkg/sql/distsqlrun/joinerbase.go#L148)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] just do `semiJoin, innerJoin: return false`
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/joinerbase.go, line 152 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-L314zcpJaVCuHxA1ZAN:-L33fHKa2fD4JGCqA8do:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc2c03575cd440d8a6eb2137d4613e289ddd2486/pkg/sql/distsqlrun/joinerbase.go#L152)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

`return side == rightSide` is more straightforward
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/processors.proto, line 242 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-L315EJUEIfwL4KC4bS3:-L33fI0spWOoMc-eWSuv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc2c03575cd440d8a6eb2137d4613e289ddd2486/pkg/sql/distsqlrun/processors.proto#L242)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

LEFT_SEMI
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479)*

**Comment by petermattis** [comment]
Review status: 0 of 7 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 553 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-L33rJqhX7pmLtMFYUrB:-L33rJqhX7pmLtMFYUrC:b-yj72k7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3734a7429670db08c479ec15f57c8b679ed1a0c/pkg/sql/distsqlrun/hashjoiner.go#L553)):*
> ```Go
> 				// rows from the right may match to the same row on the left.
> 				// Only the first match should be emitted, then is marked as to
> 				// not be emitted again.
> ```

Is the second reason correct? I thought semi-join was defined as a projection on the result of an inner-join. So if we were going to emit the row for an inner join we'd emit if for the semi-join as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 553 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-L33rJqhX7pmLtMFYUrB:-L33rt236iZd0IqXGvek:b-d65nde) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3734a7429670db08c479ec15f57c8b679ed1a0c/pkg/sql/distsqlrun/hashjoiner.go#L553)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is the second reason correct? I thought semi-join was defined as a projection on the result of an inner-join. So if we were going to emit the row for an inner join we'd emit if for the semi-join as well.
</blockquote></details>

"left semi-joins". It should be clarified that we emit the left row here. "We should emit the left row only the first time it matches a row on the right (note that an alternative would be to forget the row altogether, but our containers don't support that today)."

@petermattis it's not just a projection, it's kind-of a projection + distinct (though that doesn't quite work if the left input already has duplicates).

---

*[pkg/sql/distsqlrun/joinerbase.go, line 152 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-L314zcpJaVCuHxA1ZAN:-L33ssWRnGaCD0MKBhKX:b-mrp6yr) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc2c03575cd440d8a6eb2137d4613e289ddd2486/pkg/sql/distsqlrun/joinerbase.go#L152)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

[nit] same below

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-:-L33sxiYszucPulISlTz:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 553 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-L33rJqhX7pmLtMFYUrB:-L33v0Hkcbu9Q9sxYneN:b-7qq1xy) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3734a7429670db08c479ec15f57c8b679ed1a0c/pkg/sql/distsqlrun/hashjoiner.go#L553)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

"left semi-joins". It should be clarified that we emit the left row here. "We should emit the left row only the first time it matches a row on the right (note that an alternative would be to forget the row altogether, but our containers don't support that today)."

@petermattis it's not just a projection, it's kind-of a projection + distinct (though that doesn't quite work if the left input already has duplicates).
</blockquote></details>

@raduberinde Where does the `distinct` come in? I take back my question, though. I think I was just misunderstanding the comment. The output from a left semi-join can include the left-side at most once and that's what this is doing. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-:-L33vSTOsdd_ocRpc-TO:bnfp4nl)*

**Comment by pbardea** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 553 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-L33rJqhX7pmLtMFYUrB:-L33u-mb9zD9GFqDy3ra:bobmidl) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3734a7429670db08c479ec15f57c8b679ed1a0c/pkg/sql/distsqlrun/hashjoiner.go#L553)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

@raduberinde Where does the `distinct` come in? I take back my question, though. I think I was just misunderstanding the comment. The output from a left semi-join can include the left-side at most once and that's what this is doing. 
</blockquote></details>

Re-reading the comment, I think it could be improved by specifying that the left row is emitted. I've updated the comment to reflect that the left row is emitted here and that the "first match" refers to the first time that a row is matched on the left side.

---

*[pkg/sql/distsqlrun/joinerbase.go, line 152 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-L314zcpJaVCuHxA1ZAN:-L33uiCiUxlZthvwz4T1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/cc2c03575cd440d8a6eb2137d4613e289ddd2486/pkg/sql/distsqlrun/joinerbase.go#L152)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] same below
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479)*

**Comment by pbardea** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 553 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-L33rJqhX7pmLtMFYUrB:-L34-eSk1Px0VX_GJ6GB:bkbyctj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3734a7429670db08c479ec15f57c8b679ed1a0c/pkg/sql/distsqlrun/hashjoiner.go#L553)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Re-reading the comment, I think it could be improved by specifying that the left row is emitted. I've updated the comment to reflect that the left row is emitted here and that the "first match" refers to the first time that a row is matched on the left side.
</blockquote></details>

@petermattis the `distinct` aspect is referring to the fact that the left semi-join can include the left-side at most once, which can appear as an operation similar to a `distinct` shown below:

With the tables:
```
t1                 t2
a | b            c | d
------           -----
1 | 2            1 | 4
2 | 3            1 | 5
```

Inner join `SELECT t1.a, t1.b FROM t1 JOIN t2 ON a = c;` gives: (1, 2), (1, 2)
however
Semi join `SELECT t1.a, t1.b FROM t1 SEMI JOIN t2 ON a = c;` gives: (1, 2)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479)*

**Comment by petermattis** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/distsqlrun/hashjoiner.go, line 553 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-L33rJqhX7pmLtMFYUrB:-L342s8CYbYiObjY2_FC:b-rhgqz5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3734a7429670db08c479ec15f57c8b679ed1a0c/pkg/sql/distsqlrun/hashjoiner.go#L553)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

@petermattis the `distinct` aspect is referring to the fact that the left semi-join can include the left-side at most once, which can appear as an operation similar to a `distinct` shown below:

With the tables:
```
t1                 t2
a | b            c | d
------           -----
1 | 2            1 | 4
2 | 3            1 | 5
```

Inner join `SELECT t1.a, t1.b FROM t1 JOIN t2 ON a = c;` gives: (1, 2), (1, 2)
however
Semi join `SELECT t1.a, t1.b FROM t1 SEMI JOIN t2 ON a = c;` gives: (1, 2)
</blockquote></details>

Ah, thanks for the clarification @pbardea. I thought Radu was referring to `distinct` on the left-side, but he was referring to `distinct` on the right-side which makes sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/distsqlrun/hashjoiner.go, line 553 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479#-L33rJqhX7pmLtMFYUrB:-L343Y4MCaauNBVfx9OU:b-vys7sd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3734a7429670db08c479ec15f57c8b679ed1a0c/pkg/sql/distsqlrun/hashjoiner.go#L553)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Ah, thanks for the clarification @pbardea. I thought Radu was referring to `distinct` on the left-side, but he was referring to `distinct` on the right-side which makes sense.
</blockquote></details>

I was referring to a distinct after the projection. The semi-join above is (if there are no duplicates in `t1`) equivalent to `SELECT DISTINCT t1.a, t1.b FROM t1 JOIN t2 ON a = c`. Anyway, I'm splitting hairs here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21479)*

**Pull request merged**
