### PR TITLE
*: remove loop variables copies

### PR DESCRIPTION
**Pull request by renatolabs**
To quote from Go 1.22's release notes:

> Previously, the variables declared by a “for” loop were created once
> and updated by each iteration. In Go 1.22, each iteration of the loop
> creates new variables, to avoid accidental sharing bugs.

This makes the `loopvarcapture` unnecessary and removes unnecessary
loop variable copies.

Epic: none

Release note: None

### CODE REVIEW

**Comment by rickystewart** [comment]
Set the label as I believe this will benefit from being backported to `release-24.1`. If that is an error on my part, feel free to un-do it.

**Review by fqazi — APPROVED** [review]
:lgtm:

> Reviewed 13 of 13 files at r1, 34 of 34 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126229#-:-O0Jkr0UDSTfr7bB4Fv9:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @michae2, @msbutler, @nameisbhaskar, @vidit-bhat, and @xinhaoz)

**Review by RaduBerinde — APPROVED** [review]
:lgtm:  It's so.. beautiful!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126229#-:-O0JnHM39N-FiCe_7KWo:bpmx8m4)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @michae2, @msbutler, @nameisbhaskar, @vidit-bhat, and @xinhaoz)

**Review by msbutler — APPROVED** [review]
DR changes look good!

**Review by rickystewart — APPROVED** [review]

**Review by aadityasondhi — APPROVED** [review]

**Comment by renatolabs** [comment]
TFTRs!

bors r=fqazi,RaduBerinde,msbutler,rickystewart,aadityasondhi

**Pull request merged**
