### PR TITLE
distsql: annotate processors with a stage ID

### PR DESCRIPTION
**Pull request by RaduBerinde**
Adding a "stage identifier" that can be used to correlate processors that are
part of the same stage. A change in the plan viewer will highlight all
processors in a stage when you hover over one of them.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
image

**Comment by arjunravinarayan** [comment]
:lgtm:

Interesting choice in keeping the stage identifiers separate for plans that have left and right plans, I would have thought you'd have kept the stage identifies the same somehow, and increment by the max of the two plans. But this works too, we will have to see how it looks in the commit that actually changes the plan viewer, but I'm looking forward to it!

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/testdata/logic_test/distsql_agg, line 45 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15905#-KkCFcGLwIHJp4mJHROp:-KkCFcGLwIHJp4mJHROq:b-even7v) ([raw file](https://github.com/cockroachdb/cockroach/blob/599ee7074f6f2e1c5594ef26d3b19459a4c26d60/pkg/sql/testdata/logic_test/distsql_agg#L45)):*
> ```
> # We hardcode the plan for the testcase that follows to make it easier to debug
> # errors caused by changing planning logic.
> query T
> ```

Oof, this change is really revealing how brittle our `SELECT url` testcases are.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15905#-:-KkCFiJPLnZ6ywdXJ90t:bfn15uc)*

**Comment by arjunravinarayan** [comment]
(previous comment is about plans that have a different number of processors in the left side and the right side, your picture has them have the same depth on either side).

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15905#-:-KkCGZXenXia2zzS-GKJ:b-3lm84a)*

**Comment by RaduBerinde** [comment]
TFTR!

The point of this is to identify the set of processors that correspond to a logical node. Stage 1 in the left side and stage 1 in the right side are not parallel copies of the same computation; they can be completely different things.

In the case of a symmetric tree, what you suggest would mean that we highlight the entire level (which is not very useful; it's not too hard to visually see the depth in these cases, e.g. the picture above).

The change on the reader side is in, the new URLs should have this hovering feature.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/testdata/logic_test/distsql_agg, line 45 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15905#-KkCFcGLwIHJp4mJHROp:-KkCib_v1GQBqLCw2tYU:b97ynwv) ([raw file](https://github.com/cockroachdb/cockroach/blob/599ee7074f6f2e1c5594ef26d3b19459a4c26d60/pkg/sql/testdata/logic_test/distsql_agg#L45)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

Oof, this change is really revealing how brittle our `SELECT url` testcases are.
</blockquote></details>

Right, I think the key is always separating changes that affect the diagram json from changes that modify some runtime behavior. Because in the former case it should be fine to look at just a few cases and use `--rewrite-results-in-testfiles` to update everything.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15905#-:-KkChgrUTJtz8N_t-L4X:b-3osbkn)*

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15905#-:-KkDJH_KJZ0M643Au6vQ:bnfp4nl)*

**Pull request merged**
