### PR TITLE
sql: Add per replica locality information to show ranges.

### LINKED ISSUE #39793: sql: Make SHOW RANGES return all localities per range
Currently on `master`, `SHOW RANGES` returns the locality of the leaseholder replica of each range:

```
root@10.142.0.87:26257/movr> show ranges from table users;
        start_key       |        end_key        | range_id | replicas | lease_holder |                    locality
+-----------------------+-----------------------+----------+----------+--------------+-------------------------------------------------+
  NULL                  | /"chicago"            |       21 | {1,5,7}  |            7 | cloud=gce,region=us-west1,zone=us-west1-a
  /"chicago"            | /"chicago"/PrefixEnd  |       63 | {1,6,7}  |            6 | cloud=gce,region=us-central1,zone=us-central1-c
  /"chicago"/PrefixEnd  | /"new york"           |       64 | {2,5,7}  |            2 | cloud=gce,region=us-east1,zone=us-east1-c
  /"new york"           | /"new york"/PrefixEnd |       61 | {1,5,9}  |            1 | cloud=gce,region=us-east1,zone=us-east1-b
  /"new york"/PrefixEnd | /"seattle"            |       62 | {2,6,9}  |            2 | cloud=gce,region=us-east1,zone=us-east1-c
  /"seattle"            | /"seattle"/PrefixEnd  |       65 | {2,5,9}  |            9 | cloud=gce,region=us-west1,zone=us-west1-c
  /"seattle"/PrefixEnd  | NULL                  |       66 | {2,6,9}  |            9 | cloud=gce,region=us-west1,zone=us-west1-c
(7 rows)
```

Key:
1-3 = us-east1
4-6 = us-central1
7-9 = us-west1

It'd be great to return the locality of each replica in the same sequence as the `replicas` field. This would be a convenient way to understand how CockroachDB is balancing replicas of a range and check whether zone configs are being respected.

### PR DESCRIPTION
**Pull request by rohany**
Fixes #39793.

Release note (sql change): Show ranges now displays per replica
locality information.

### CODE REVIEW

**Review by solongordon — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39813)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany and @solongordon)

___
*[pkg/sql/crdb_internal.go, line 1855 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39813#-LnIYoDaAZG8zGRdFQwE:-LnIYoDaAZG8zGRdFQwF:bucgnza) ([raw file](https://github.com/cockroachdb/cockroach/blob/47ecc9fee03261e1984cad40a9b90c9ab71730e6/pkg/sql/crdb_internal.go#L1855)):*
> ```Go
>   index_name           STRING NOT NULL,
> 	replicas             INT[] NOT NULL,	
>   replica_localities   STRING[] NOT NULL,
> ```

Whitespace weirdness
___
*[pkg/sql/crdb_internal.go, line 1943 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39813#-LnSWSU7CSEQf-oXwOWK:-LnSWSU7CSEQf-oXwOWL:b9vyrzm) ([raw file](https://github.com/cockroachdb/cockroach/blob/47ecc9fee03261e1984cad40a9b90c9ab71730e6/pkg/sql/crdb_internal.go#L1943)):*
> ```Go
> 			}
> 
> 			var voterReplicaLocalities []string
> ```

Nit: This slice seems unnecessary. You can just append to `replicaLocalityArr` as you iterate through `voterReplicas`.
___
*[pkg/sql/show_ranges_test.go, line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39813#-LnSWvy8AhGFPsy6pquI:-LnSWvy8AhGFPsy6pquJ:b-69blg5) ([raw file](https://github.com/cockroachdb/cockroach/blob/47ecc9fee03261e1984cad40a9b90c9ab71730e6/pkg/sql/show_ranges_test.go#L53)):*
> ```Go
> 		expected := "{"
> 		for i, replica := range replicas {
> 			expected = expected + fmt.Sprintf("\"region=test,dc=dc%d\"", replica)
> ```

Nit: You can use `+=` here. (In general `strings.Builder` is better but unnecessary in a unit test.)

Also, you can use the backtick to avoid escaping double quotes: `` `"region=test,dc=dc%d"` ``

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39813)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @solongordon)

___
*[pkg/sql/crdb_internal.go, line 1855 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39813#-LnIYoDaAZG8zGRdFQwE:-LnT4ANRDZZJufQ2tkqN:b-y5yqc6) ([raw file](https://github.com/cockroachdb/cockroach/blob/47ecc9fee03261e1984cad40a9b90c9ab71730e6/pkg/sql/crdb_internal.go#L1855)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Whitespace weirdness
</blockquote></details>

what is the rule for this -- is it always supposed to be spaces?? I get this wrong on every PR i send.
___
*[pkg/sql/crdb_internal.go, line 1943 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39813#-LnSWSU7CSEQf-oXwOWK:-LnT4tRb6w3M7lgUGe2j:b6zrrkh) ([raw file](https://github.com/cockroachdb/cockroach/blob/47ecc9fee03261e1984cad40a9b90c9ab71730e6/pkg/sql/crdb_internal.go#L1943)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Nit: This slice seems unnecessary. You can just append to `replicaLocalityArr` as you iterate through `voterReplicas`.
</blockquote></details>

Good catch.
___
*[pkg/sql/show_ranges_test.go, line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39813#-LnSWvy8AhGFPsy6pquI:-LnTH0i2DEYFGFEmzn7C:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/47ecc9fee03261e1984cad40a9b90c9ab71730e6/pkg/sql/show_ranges_test.go#L53)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Nit: You can use `+=` here. (In general `strings.Builder` is better but unnecessary in a unit test.)

Also, you can use the backtick to avoid escaping double quotes: `` `"region=test,dc=dc%d"` ``
</blockquote></details>

Done

**Comment by rohany** [comment]
RFAL

**Review by solongordon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39813)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany and @solongordon)

___
*[pkg/sql/crdb_internal.go, line 1855 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39813#-LnIYoDaAZG8zGRdFQwE:-LntKCynBQLWIzH2GFTO:bxacag) ([raw file](https://github.com/cockroachdb/cockroach/blob/47ecc9fee03261e1984cad40a9b90c9ab71730e6/pkg/sql/crdb_internal.go#L1855)):*
<details><summary><i>Previously, rohany (Rohan Yadav) wrote…</i></summary><blockquote>

what is the rule for this -- is it always supposed to be spaces?? I get this wrong on every PR i send.
</blockquote></details>

Yeah, I think spaces in strings, tabs for code. I always just match whatever the surrounding lines do. GoLand seems to get it right for me.

**Comment by rohany** [comment]
lol every error with spacing i have looks fine in goland :(

**Comment by rohany** [comment]
bors r=solongordon

**Pull request merged**
