### PR TITLE
tabledesc: validate that primary key columns are not stored in an index

### LINKED ISSUE #115293: validation: Add validation for corruptions in #115214
In #115214, we discovered a bug that can cause corrupted descriptors. As a follow up, it's probably a good idea to add some validation logic for such corruption.

basically, the new validation should assert that "for any secondary index, any primary key column will either be its key column or its key suffix column", and that "for any secondary index, no stored columns should be in primary key columns".

We should only add this validation if we also are able to add an automatic repair for it using a PostDeserializationChange. Otherwise, upgrades will be blocked when the FirstUpgradePrecondition check is executed.

Jira issue: CRDB-33961

Epic CRDB-30352

### PR DESCRIPTION
**Pull request by Xiang-Gu**
Fixes #115293

Previously, we encountered bugs (#115214) that lead to corrupted index
descriptor where it stores a primary key column. This commit added a
validation logic to ensure such corruption is caught.

Release note: None

### CODE REVIEW

**Review by fqazi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115558)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Xiang-Gu)

___
*[`pkg/sql/catalog/tabledesc/structured.go` line 744 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/115558#-Nl4XkrWBVH5rbAiagoo:-Nl4XkrWBVH5rbAiagop:b-k6ggth) ([raw file](https://github.com/cockroachdb/cockroach/blob/72ba6481e0c90f54803665090f169be12737bbf5/pkg/sql/catalog/tabledesc/structured.go#L744)):*
> ```Go
> 				// If the primary index contains a stored column, we don't need to
> 				// store it - it's already part of the index.
> 				err = errors.WithDetailf(
> ```

Just a concern here will this block schema changes on tables with this problem and how are we planning on getting customers to repair descriptors in this state?

**Comment by Xiang-Gu** [comment]
@fqazi This will indeed block upgrade if they have such corruption. IMO, such corruption is severe and they should be escalated to us oncall. We need to determine whether potential data corruption exists  -- I felt like just repairing the corrupted descriptor isn't enough -- bc we might need to re-backfill data to ensure data is consistent with the repaired query.

Even if it turns out that re-backfilling isn't necessary, I am still reluctant to repair this type of corruption automatically because of the lesson/best practice that we agreed on that "we're going to be conservative to adding automatic repair logic once we actually see it in escalations and understood its root cause". As of now, I felt that we know one of the ways to end up with this corruption and we certainly haven't seen it at all in escalation so I'd not want to add the auto repair now, out of caution.

**Review by fqazi — COMMENTED** [review]
Just as a sanity check I'm okay if this blocks finalization or schema changes, but can you confirm that data is still readable / writable (i.e. this change won't block the insert / select code paths)?  Lets minimize risk of causing an outage on problematic tables, its okay to prevent operations like schema changes / finalization if things are wrong.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115558#-:-Nl59lU83uPt-qI67Ad6:bst1a8p)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @Xiang-Gu)

**Comment by Xiang-Gu** [comment]
@fqazi I made several changes to address the safety concerns of this newly added validation. Namely, 
 - make the validation "cluster version aware" so that if the cluster version is not on V24.1, the validation is disabled
 - make `invalid_objects` vtable supply the *latest* cluster version to validation logic (so that the corruptions will still be reported even in a mixed version state)
 - added a test for the mixed version state scenario where the corrupted table continues to be operable, upgrade is blocked, and `invalid_objects` reports the corruption.

**Review by fqazi — APPROVED** [review]
:lgtm:

This looks good, nice work!

> Reviewed 2 of 7 files at r1, 3 of 3 files at r3, 1 of 1 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115558#-:-NlUzb_93rHmKbBiD8xS:b2a8j23)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @Xiang-Gu)

**Comment by Xiang-Gu** [comment]
TFTR!

bors r+

**Comment by Xiang-Gu** [comment]
PS: the reason that we didn't add a repair to such corruption is simply repairing the descriptor would make this index unreadable (bc the data is written with the old descriptor info and it does not know how to interpret/read data with this updated descriptor). The workaround, if this corruption happens in the wild, is to drop and re-create the index.

**Pull request merged**
