### PR TITLE
logictest: move most of EXPLAIN tests into opt tests

### LINKED ISSUE #65032: logictest: move EXPLAIN (DISTSQL) into execbuilder tests
It is annoying to have to update the url of `EXPLAIN (DISTSQL)` and `EXPLAIN ANALYZE (DISTSQL)` queries in the regular logic tests. We should move all such things into the execbuilder folder since `make testoptlogic TESTFLAGS='-rewrite'` has a much more reasonable runtime.

### PR DESCRIPTION
**Pull request by yuzefovich**
Fixes: #65032.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
Awesome, thanks for doing this!

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70899#-:-MkoAj2k2Ud99kpT9ErX:bb0tnpy)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by yuzefovich** [comment]
Will move `explain_analyze_plans` too.

bors r-

**Pull request merged**
