### PR TITLE
Normalize shell scripts to spaces rather than tabs

### PR DESCRIPTION
**Pull request by tamird**
Tested with `ag --sh "\t"`.

@bdarnell removed this from #1833

### CODE REVIEW

**Comment by bdarnell** [comment]
LGTM

**Comment by BramGruneir** [comment]
Can we enforce this with a linter?

**Comment by tamird** [comment]
Can you suggest something specific? I don't think we can depend on `ag` in our build environment and I'm loath to implement the `--sh` magic in grepisms.

**Comment by bdarnell** [comment]
`find . -name '*.sh' |xargs grep '\t'`

**Comment by bdarnell** [comment]
The problem isn't just tabs, though - we're inconsistent in our use of two-space versus four-space indents in shell scripts, and this is harder to validate.

**Comment by tamird** [comment]
Added the naive tab check.

**Pull request merged**
