### PR TITLE
sql: Preserve constraint names in table descriptors

### LINKED ISSUE #6692: sql: Constraint names are ignored at the column level
When a primary key constraint is specified at the column level, it always gets the name "primary" even if another name was given. The name is used as expected when the constraint is specified at the table level.

From cockroachdb/docs#280

```
root@:26257> create table t (c1 int constraint t_pk primary key not null);
CREATE TABLE
root@:26257> show indexes from t;
+-------+---------+--------+-----+--------+-----------+---------+
| Table |  Name   | Unique | Seq | Column | Direction | Storing |
+-------+---------+--------+-----+--------+-----------+---------+
| t     | primary | true   |   1 | c1     | ASC       | false   |
+-------+---------+--------+-----+--------+-----------+---------+
root@:26257> drop table t;
^[[ADROP TABLE
root@:26257> create table t (c1 int not null, constraint t_pk primary key (c1));
CREATE TABLE
root@:26257> show indexes from t;
+-------+------+--------+-----+--------+-----------+---------+
| Table | Name | Unique | Seq | Column | Direction | Storing |
+-------+------+--------+-----+--------+-----------+---------+
| t     | t_pk | true   |   1 | c1     | ASC       | false   |
+-------+------+--------+-----+--------+-----------+---------+
```

### PR DESCRIPTION
**Pull request by dt**
Any column qualification or table contraint can be declared
with a name in the syntax but currently we are ignoring that
name. #7164 started capturing those names in the parsed
SQL statements -- this follows up on that by actually
copying the parsed names into the descriptors and then
showing those names in `SHOW CREATE TABLE`.

Fixes #6692.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7271)

### CODE REVIEW

**Comment by knz** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7271#-:-KKOJI41tFQuDHByjqnZ:1417088721)*

**Comment by mjibson** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/testdata/table, line 191 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7271#-KKPH9Qe3l09aUPkTZjr:-KKPH9Qe3l09aUPkTZjs:2138701569) ([raw file](https://github.com/cockroachdb/cockroach/blob/06327597d8b4d95a941661b089b0c64f72ff79d4/sql/testdata/table#L191)):*
> ```
>   CHECK (LENGTH(nickname) < LENGTH(name)),
>   CHECK (LENGTH(nickname) < 10)
> )
> ```

Need to test syntax for `CONSTRAINT uniq UNIQUE (id)`

---

*[sql/testdata/table, line 222 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7271#-KKPGD1dnQVTC9J4So-9:-KKPGD1dnQVTC9J4So-A:-422672640) ([raw file](https://github.com/cockroachdb/cockroach/blob/06327597d8b4d95a941661b089b0c64f72ff79d4/sql/testdata/table#L222)):*
> ```
>                         CONSTRAINT ck2 CHECK (LENGTH(nickname) < LENGTH(name)),
>                         CONSTRAINT ck1 CHECK (LENGTH(nickname) < 10)
>                         )
> ```

Need newline at EOF

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7271)*

**Comment by dt** [comment]
Review status: 6 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/testdata/table, line 191 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7271#-KKPH9Qe3l09aUPkTZjr:-KKPJbLSEadaUUvrBnmD:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/06327597d8b4d95a941661b089b0c64f72ff79d4/sql/testdata/table#L191)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> Need to test syntax for `CONSTRAINT uniq UNIQUE (id)`
</details>
Done.

---

*[sql/testdata/table, line 222 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7271#-KKPGD1dnQVTC9J4So-9:-KKPJb6fTJsfuCaa5b_s:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/06327597d8b4d95a941661b089b0c64f72ff79d4/sql/testdata/table#L222)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> Need newline at EOF
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7271)*

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 6 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7271#-:-KKPKIFrCWg0MRUJYA0F:1417088721)*

**Pull request merged**
