### PR TITLE
sql: add telemetry for non-atomic copy usage

### PR DESCRIPTION
**Pull request by cucaroach**
Keep account of customers switching back to non-atomic COPY, one day we
hope to remove non-atomic COPY so this is important data.

Release note: None

Epic: CRDB-18892

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
Probably want to backport to 22.2, right?

:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94938#-:-NLOA51_8OkLktW9rqvH:b-p8qmfz)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by cucaroach** [comment]
Yes thanks!

bors r+

**Review by mgartner — APPROVED** [review]
LGTM. Is it possible to test this in telemetry tests? https://github.com/cockroachdb/cockroach/tree/93e620eccaa48387e57ecb1587df736164d6f69c/pkg/sql/testdata/telemetry

**Comment by cucaroach** [comment]
> LGTM. Is it possible to test this in telemetry tests? [`93e620e`/pkg/sql/testdata/telemetry](https://github.com/cockroachdb/cockroach/tree/93e620eccaa48387e57ecb1587df736164d6f69c/pkg/sql/testdata/telemetry)

It would be nice to test it but it would be non-trivial to get the telemetry test to run a COPY command, I mean it could be done but it would to invent a syntax for slurping up the COPY data and switch from gosql to pgx, probably the end doesn't justify the means...

**Pull request merged**
