### PR TITLE
lint: unparallelize TestVet

### PR DESCRIPTION
**Pull request by knz**
... to reduce the overall RAM usage of `make lint`.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
LGTM, it's worth a shot but there might be something else going on because locally I found that it doesn't use much memory (I can run `make testshort` even if I restrict it to <1GB memory).

**Comment by knz** [comment]
Hmm on my machine TestVet finishes in 9 seconds and does not even use 1GB of RAM.

So I don't think that's really the problem.

**Comment by RaduBerinde** [comment]
I think what's going on is that all the Parallel tests are paused waiting for the parent (and thus all non-parallel tests) to run first. As that's happening we run out of memory (because of one of the big tests) and teamcity confusingly shows the `PAUSE TestLint/TestVet` line which just means the test is waiting to start.

**Comment by knz** [comment]
all right, not using this pr then

**Pull request closed without merging**
