### PR TITLE
sql: normalize function names

### PR DESCRIPTION
**Pull request by knz**
AS THIS SENTENCE DEMONSTRATES, HUMANS ARE NOT WELL TRAINED TO READ
CAPITALIZED COMMON WORDS.

SQL function names are common words (not keywords) and thus need not
be capitalized. In addition, when searching for all uses of a built-in
function, it is inconvenient for the search to have some uses
capitalized and some uses not.

This patch corrects the existing tests to ensure that
function names are not capitalized.

This patch also adds a linter so that future changes/additions are
reminded of this.

Release note: None

### CODE REVIEW

**Comment by BramGruneir** [comment]
OK,  I looked over every file.  

:lgtm:  Just one weird spacing issue.

Please add some context for the special handling of FAMILY to the commit message.

What do you think about adding the opposite linter, to ensure keywords are indeed capitalized.  

---

Reviewed 1 of 1 files at r1, 178 of 178 files at r2.
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/logictest/testdata/logic_test/function_lookup, line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26588#-LEjPuo59AmmEyGcPK04:-LEjPuo6BZqVl_zZNmiI:bo77g7w) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab9ffd288267f4e898bc2e37345dde978e6f6895/pkg/sql/logictest/testdata/logic_test/function_lookup#L39)):*
> ```
> # CockroachDB is case-preserving for quoted identifiers like pg, and
> # function names only exist in lowercase.
> query error unknown function: PG_TYPEOF()
> ```

For this case, perhaps we can add to the error message that they need to use the lowercase one.  Just returning unknown function might be a little frustrating.

---

*[pkg/testutils/lint/lint_test.go, line 251 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26588#-LEjYbTVCFiBIYSpN3Id:-LEjYbTW3ZTwhO48Lz9T:b3d0n6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab9ffd288267f4e898bc2e37345dde978e6f6895/pkg/testutils/lint/lint_test.go#L251)):*
> ```Go
> 			if err := stream.ForEach(filter, func(s string) {
> 				t.Errorf(`
> %s <- forbidden; use "envutil" instead`, s)
> ```

Why do all of these start on the next line? 

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26588#-:-LEjZS5G3ZsUNbuiHh0A:b-7cqbjv)*

**Comment by knz** [comment]
> Please add some context for the special handling of FAMILY to the commit message.

Done.

> What do you think about adding the opposite linter, to ensure keywords are indeed capitalized.

That's a good idea but much more hard to implement: plenty of SQL keywords are legitimate words in English that appear all the time in comments, variable names, etc. I'll think about it for a different PR.

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/logictest/testdata/logic_test/function_lookup, line 39 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26588#-LEjPuo59AmmEyGcPK04:-LEk0BHT7kG1byaEaGbK:b-r0wp3v) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab9ffd288267f4e898bc2e37345dde978e6f6895/pkg/sql/logictest/testdata/logic_test/function_lookup#L39)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

For this case, perhaps we can add to the error message that they need to use the lowercase one.  Just returning unknown function might be a little frustrating.
</blockquote></details>

Good idea. Done.

---

*[pkg/testutils/lint/lint_test.go, line 251 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26588#-LEjYbTVCFiBIYSpN3Id:-LEj_ar256P1DwgqkgfG:bsrcagz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab9ffd288267f4e898bc2e37345dde978e6f6895/pkg/testutils/lint/lint_test.go#L251)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Why do all of these start on the next line? 
</blockquote></details>

This is because IDEs and text editor recognize file name + lineno location at the beginning of the line, but not (reliably) after that. These newline characters ensure that the relevant file name + lineno are listed on their own line.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26588#-:-LEk0DuWDZA_zKXLauYu:baznrm3)*

**Comment by BramGruneir** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/testutils/lint/lint_test.go, line 251 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26588#-LEjYbTVCFiBIYSpN3Id:-LEk0pTg3rvHQv3A5wDL:b-dnioq4) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab9ffd288267f4e898bc2e37345dde978e6f6895/pkg/testutils/lint/lint_test.go#L251)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This is because IDEs and text editor recognize file name + lineno location at the beginning of the line, but not (reliably) after that. These newline characters ensure that the relevant file name + lineno are listed on their own line.
</blockquote></details>

Then why not add the newline control character instead?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26588)*

**Comment by knz** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/testutils/lint/lint_test.go, line 251 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26588#-LEjYbTVCFiBIYSpN3Id:-LEk2htj6inWUtWrP9sv:b594koy) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab9ffd288267f4e898bc2e37345dde978e6f6895/pkg/testutils/lint/lint_test.go#L251)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Then why not add the newline control character instead?
</blockquote></details>

Oh good idea. Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26588)*

**Comment by knz** [comment]
thanks for the review.

bors r+

**Pull request merged**
