### PR TITLE
release-23.2: sql: collect table statistics on virtual computed columns

### PR DESCRIPTION
**Pull request by michae2**
Backport:
  * 2/2 commits from "sql: collect table statistics on virtual computed columns" (#118241)
  * 1/1 commits from "sql: guard against non-public mutation columns in CREATE STATISTICS" (#118930)

Please see individual PRs for details.

/cc @cockroachdb/release

Release justification: high priority business need for the functionality which cannot wait until the next release.

### CODE REVIEW

**Comment by michae2** [comment]
> Are all of the changes protected via a flag or option, new syntax, an environment variable or default-disabled cluster setting?

Yes, all of the changes are behind cluster setting `sql.stats.virtual_computed_columns.enabled` which is disabled by default in these backports.

> What are the risks to backporting this change? Can the risks of backporting be mitigated?

Main risk is that with `sql.stats.virtual_computed_columns.enabled` turned on we build an invalid distsql plan for stats collection, which could prevent statistics collection on some tables if it were to happen.

> What are the risks to not backporting?

Statistics estimates for queries on indexed virtual computed columns will continue to be inaccurate, possibly prohibiting creation of indexes on virtual computed columns.

> Does this change really need to be backported? Or can it reasonably wait until the next major release to be addressed?

It cannot wait.

**Comment by michae2** [comment]
The backport was clean, there were only minor differences from master:
- `sql.stats.virtual_computed_columns.enabled` is false by default
- had to add `SET CLUSTER SETTING sql.stats.virtual_computed_columns.enabled = true` to distsql_stats and distsql_misc logic tests

**Comment by michae2** [comment]
One failure is unrelated flake https://github.com/cockroachdb/cockroach/issues/120817. I'll look into the other failure this morning.

**Comment by michae2** [comment]
Extended CI failure is a flake, this is RFAL.

**Review by mgartner — APPROVED** [review]

**Pull request merged**
