### PR TITLE
storage: use sync.Map in RaftTransport

### LINKED ISSUE #16820: storage: replace RaftTransport.{mu,recvMu} maps with sync.Map
A `sync.Map` is an order of magnitude faster than a mutex protected map under contention. The replacement of `RaftTransport.recvMu.handlers` should be straightforward. `RaftTransport.mu.Mutex` is mildly more complicated because it protects multiple members, but I'm not seeing any issue with using separate `sync.Maps` for each member.

### PR DESCRIPTION
**Pull request by petermattis**
Fixes #16820

### CODE REVIEW

**Comment by tamird** [comment]
Is there a relevant benchmark? Please include the description of #16820 in this commit message to the extent that it is useful.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/storage/raft_transport.go, line 202 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16822#-KnuQ43SR97aRkSydKaI:-KnuQ43SR97aRkSydKaJ:b-4soyzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d067b8c5a05a52cdf62719551f637989726d9a1/pkg/storage/raft_transport.go#L202)):*
> ```Go
> 					t.stats.Range(func(k, v interface{}) bool {
> 						s := v.(*raftTransportStats)
> 						s.queue = 0
> ```

is it ok that this is now unsynchronized?

---

*[pkg/storage/raft_transport.go, line 209 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16822#-KnuPzYcoD0K-vba35Pk:-KnuPzYcoD0K-vba35Pl:b-4soyzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d067b8c5a05a52cdf62719551f637989726d9a1/pkg/storage/raft_transport.go#L209)):*
> ```Go
> 					t.queues.Range(func(k, v interface{}) bool {
> 						ch := v.(chan *RaftMessageRequest)
> 						t.getStats(k.(roachpb.NodeID)).queue += len(ch)
> ```

is it ok that this is now unsynchronized?

---

*[pkg/storage/raft_transport.go, line 264 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16822#-KnuPSMS7fbYB__U7QRx:-KnuPSMS7fbYB__U7QRy:bjofdh7) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d067b8c5a05a52cdf62719551f637989726d9a1/pkg/storage/raft_transport.go#L264)):*
> ```Go
> }
> 
> func (t *RaftTransport) getHandler(storeID roachpb.StoreID) (RaftMessageHandler, bool) {
> ```

can you try removing this method? i think the various patterns of `lock(); foo, ok := ...; unlock(); if !ok {` can be pretty simple now that locking isn't needed and that it will be cleaner without this method.

---

*[pkg/storage/raft_transport.go, line 305 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16822#-KnuP64YALTOJSOX5CVw:-KnuP64YALTOJSOX5CVx:b-4ptw7c) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d067b8c5a05a52cdf62719551f637989726d9a1/pkg/storage/raft_transport.go#L305)):*
> ```Go
> 	if !ok {
> 		stats := &raftTransportStats{nodeID: nodeID}
> 		value, _ = t.stats.LoadOrStore(nodeID, stats)
> ```

it's really unfortunate that you can't just use `LoadOrStore` without allocating.

---

*[pkg/storage/raft_transport.go, line 546 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16822#-KnuQTqpW_vC5fio74eF:-KnuQTqpW_vC5fio74eG:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d067b8c5a05a52cdf62719551f637989726d9a1/pkg/storage/raft_transport.go#L546)):*
> ```Go
> // getQueue returns the queue for the specified node ID and a boolean
> // indicating whether the queue already exists (true) or was created (false).
> func (t *RaftTransport) getQueue(nodeID roachpb.NodeID) (chan *RaftMessageRequest, bool) {
> ```

ditto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16822#-:-KnuO9QxWvlitCO-SI6_:b-fgrboo)*

**Comment by petermattis** [comment]
No benchmark. Do you think it is worthwhile adding one? I'm pretty sure it will show something similar to what we saw in  #16807. 

---

Review status: 1 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/storage/raft_transport.go, line 202 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16822#-KnuQ43SR97aRkSydKaI:-KnuS9U1FT6veLbJr0bW:b4lhs3o) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d067b8c5a05a52cdf62719551f637989726d9a1/pkg/storage/raft_transport.go#L202)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

is it ok that this is now unsynchronized?
</blockquote></details>

Yes. It was unsynchronized before. Note that `raftTransportStats.queue` is only mutated by the current goroutine. I've added a comment to that effect.

---

*[pkg/storage/raft_transport.go, line 209 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16822#-KnuPzYcoD0K-vba35Pk:-KnuSGItOIozMEcE4vCW:bb77ufg) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d067b8c5a05a52cdf62719551f637989726d9a1/pkg/storage/raft_transport.go#L209)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

is it ok that this is now unsynchronized?
</blockquote></details>

Yes.

---

*[pkg/storage/raft_transport.go, line 264 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16822#-KnuPSMS7fbYB__U7QRx:-KnuSIo1RfO9zcOveZss:b81b04) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d067b8c5a05a52cdf62719551f637989726d9a1/pkg/storage/raft_transport.go#L264)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

can you try removing this method? i think the various patterns of `lock(); foo, ok := ...; unlock(); if !ok {` can be pretty simple now that locking isn't needed and that it will be cleaner without this method.
</blockquote></details>

I originally started with that approach, but the type assertion of `value.(RaftMessageHandler)` was a bit annoying given that we call this in several places.

---

*[pkg/storage/raft_transport.go, line 305 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16822#-KnuP64YALTOJSOX5CVw:-KnuSQv5OmLnLnyhWfYl:b2d1ffx) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d067b8c5a05a52cdf62719551f637989726d9a1/pkg/storage/raft_transport.go#L305)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

it's really unfortunate that you can't just use `LoadOrStore` without allocating.
</blockquote></details>

Agreed. I think there was some discussion of an alternative `LoadOrStore` interface, but nothing came of it.

---

*[pkg/storage/raft_transport.go, line 546 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16822#-KnuQTqpW_vC5fio74eF:-KnuSVJAsd9Lw1HJHdLM:b-e8jkpd) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d067b8c5a05a52cdf62719551f637989726d9a1/pkg/storage/raft_transport.go#L546)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

While this is only used from a single location, I added it for consistency with the other `get*` methods. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16822#-:-KnuTuydH7yDwY2Edbx2:b-yngpmm)*

**Comment by tamird** [comment]
I was imagining a higher level benchmark, but perhaps that's more trouble than it's worth.

:lgtm: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/raft_transport.go, line 202 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16822#-KnuQ43SR97aRkSydKaI:-KnuiFqe-M4_AR64np5h:b-ih81nf) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d067b8c5a05a52cdf62719551f637989726d9a1/pkg/storage/raft_transport.go#L202)):*
> It was unsynchronized before.

Looks like it was under `t.mu` before.

---

*[pkg/storage/raft_transport.go, line 267 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16822#-KnuiWnHtGzZFk69YBH0:-KnuiWnIHgHNGhmuPJ7R:bdto17f) ([raw file](https://github.com/cockroachdb/cockroach/blob/09cd05cf7a648409021d0b133f190ebef429f2e8/pkg/storage/raft_transport.go#L267)):*
> ```Go
> 
> func (t *RaftTransport) getHandler(storeID roachpb.StoreID) (RaftMessageHandler, bool) {
> 	value, ok := t.handlers.Load(storeID)
> ```

nit: `if value, ok := ...;ok {`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16822#-:-KnuWkLVJVrCFPZj16ml:b-loj5nq)*

**Comment by petermattis** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/storage/raft_transport.go, line 202 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16822#-KnuQ43SR97aRkSydKaI:-Knuzi4rXEVdcU4kz_5E:bl66z7a) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d067b8c5a05a52cdf62719551f637989726d9a1/pkg/storage/raft_transport.go#L202)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

> It was unsynchronized before.

Looks like it was under `t.mu` before.
</blockquote></details>

Yes, you're correct, but `t.mu` wasn't providing necessary protecting of `raftTransportStats.queue`, only have `t.mu.stats`.

---

*[pkg/storage/raft_transport.go, line 267 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16822#-KnuiWnHtGzZFk69YBH0:-KnuzyQLAqX4vB8mR1GO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/09cd05cf7a648409021d0b133f190ebef429f2e8/pkg/storage/raft_transport.go#L267)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

nit: `if value, ok := ...;ok {`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16822)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16822)*

**Pull request merged**
