### PR TITLE
kvclient: skip `TestLargeKeys`

### PR DESCRIPTION
**Pull request by rickystewart**
See #75180.

Release note: None

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75181#-:-MtoX9kKAs-vZhBtqnNA:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rickystewart)

**Comment by rickystewart** [comment]
bors r=yuzefovich

**Comment by yuzefovich** [comment]
Per my [comment](https://github.com/cockroachdb/cockroach/issues/75180#issuecomment-1017079459), I don't think we need it (at least for now).

bors r-

**Comment by rickystewart** [comment]
Thank you @yuzefovich!

**Pull request closed without merging**
