### PR TITLE
sql: delete db zone config after GC TTL

### LINKED ISSUE #24179: sql: Inconsistent zone config behavior when dropping database or table
As "discovered" in #24154, we handle zone configs differently when dropping partitions/tables/databases.

1. When you drop a table, we keep the corresponding zone config around until the table's descriptor is deleted, which is supposed to happen after the configured GC TTL period.
2. I haven't tested dropping a partition, so I won't speak on it.
3. When you drop a database, we delete the corresponding zone config immediately.

The behavior when dropping a database is concerning. If (a) there's data in a table in the database (b) the table doesn't have a table-level zone config (c) the database does have a database-level zone config, then dropping the database (e.g. `DROP DATABASE ... CASCADE`) has the effect of changing the zone config that applies to the data in the table. Before dropping the database, the databases's zone config applies to the table. After dropping the database, the global `.default` zone config is all that applies to the table.

This means that when we drop a database, it can actually cause a lot of rebalancing if the database had different constraints on it than the `.default` zone. Even if the database was constrained to certain regions for sovereignty reasons, the yet-to-be-GC'ed data will likely get moved elsewhere.

For example, I created a 6 node local cluster with 3 nodes in locality `a=1` and 3 in `a=2`. I created a table, split it 20 times, and constrained all its replicas to `a=1` around 16:07 in the below screenshot. At 16:09 I ran `DROP DATABASE ... CASCADE` on the database, and suddenly all the data got spread around across both localities because the constraint I had specified no longer existed.

screen shot 2018-03-23 at 12 13 46 pm

There may also be a similar problem with us deleting a table's zone config before all the data has been GC'ed. I'm not an expert in that area, though, so I'll let @benesch speak to that.

### PR DESCRIPTION
**Pull request by eriktrinh**
Previously the database's zone config would be deleted immediately when
a DROP DATABASE is initiated, including if there are tables that the
drop cascades down to. This causes dropped tables waiting for the GC
period without a table zone config to have values from the default
config to be applied (which can cause unnecessary data movement).

This change removes the database's zone config once all the cascaded
table data is completely removed, using the dropped table status in the
job details.

Fixes #24179.

### CODE REVIEW

**Review by benesch — COMMENTED** [review]
🎉 🙇  this is huge!

**Review by BramGruneir — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30666)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/jobs/jobspb/jobs.proto, line 139 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30666#-LOTQNzK4QD_8Mi55ga0:-LOTQNzK4QD_8Mi55ga1:bwskis8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c850388b4ed9f49572817acdb4cac6b14c87a33e/pkg/jobs/jobspb/jobs.proto#L139)):*
> ```protobuf
>   repeated DroppedTableDetails dropped_tables = 3 [(gogoproto.nullable) = false];
>   // The descriptor ID of the dropped database which created this job.
>   uint32 drop_database_id = 4 [
> ```

please call this `dropped_database_id` instead of `drop_database_id` to match the `dropped_tables`.
___
*[pkg/sql/drop_database.go, line 175 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30666#-LOTUe12EajrXeCpULJJ:-LOTUe13Cb3jnmG5tJI9:b-ea4iht) ([raw file](https://github.com/cockroachdb/cockroach/blob/c850388b4ed9f49572817acdb4cac6b14c87a33e/pkg/sql/drop_database.go#L175)):*
> ```Go
> 			return err
> 		}
> 		details := job.Details().(jobspb.SchemaChangeDetails)
> ```

Why do you need to set the details after creating the job?  Why not do it within `createDropTableJob()`?
___
*[pkg/sql/drop_database.go, line 180 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30666#-LOTTo4BBQV8gnCFZLGM:-LOTTo4BBQV8gnCFZLGN:b9zcogx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c850388b4ed9f49572817acdb4cac6b14c87a33e/pkg/sql/drop_database.go#L180)):*
> ```Go
> 			return errors.Wrapf(err, "failed to set drop database ID %d for job", n.dbDesc.ID)
> 		}
> 	} else {
> ```

Why would the jobID be 0?  Could you add a comment about it?

Also, do you test this code path?
___
*[pkg/sql/drop_test.go, line 214 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30666#-LOTUs1dA_Gxq4iGwLbC:-LOTUs1dA_Gxq4iGwLbD:b-yr7093) ([raw file](https://github.com/cockroachdb/cockroach/blob/c850388b4ed9f49572817acdb4cac6b14c87a33e/pkg/sql/drop_test.go#L214)):*
> ```Go
> 		t.Fatal(err)
> 	}
> 	// Database zone config is removed once all table data and zone configs are removed.
> ```

Can you add a check to make sure that after the job is created, but before it is finished that the zone config still exists?

**Review by eriktrinh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30666)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/jobs/jobspb/jobs.proto, line 139 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30666#-LOTQNzK4QD_8Mi55ga0:-LOTvY7c1dI3O8XQ1i7F:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c850388b4ed9f49572817acdb4cac6b14c87a33e/pkg/jobs/jobspb/jobs.proto#L139)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

please call this `dropped_database_id` instead of `drop_database_id` to match the `dropped_tables`.
</blockquote></details>

Done.
___
*[pkg/sql/drop_database.go, line 175 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30666#-LOTUe12EajrXeCpULJJ:-LOTvZ5P-OUP9RjN6aM4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c850388b4ed9f49572817acdb4cac6b14c87a33e/pkg/sql/drop_database.go#L175)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Why do you need to set the details after creating the job?  Why not do it within `createDropTableJob()`?
</blockquote></details>

Done.
___
*[pkg/sql/drop_database.go, line 180 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30666#-LOTTo4BBQV8gnCFZLGM:-LOTyLclB_9xMYWmXBCa:b-fzlaul) ([raw file](https://github.com/cockroachdb/cockroach/blob/c850388b4ed9f49572817acdb4cac6b14c87a33e/pkg/sql/drop_database.go#L180)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Why would the jobID be 0?  Could you add a comment about it?

Also, do you test this code path?
</blockquote></details>

Done. Also added a test that goes down this code path when the database is empty
___
*[pkg/sql/drop_test.go, line 214 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30666#-LOTUs1dA_Gxq4iGwLbC:-LOTzHROBQFXd2ocfJiR:b-y38d9w) ([raw file](https://github.com/cockroachdb/cockroach/blob/c850388b4ed9f49572817acdb4cac6b14c87a33e/pkg/sql/drop_test.go#L214)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Can you add a check to make sure that after the job is created, but before it is finished that the zone config still exists? 
</blockquote></details>

`TestDropDatabaseDeleteData` should already be testing this.

**Review by BramGruneir — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30666#-:-LOUIuN9C_maWN9zSqFX:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/drop_database.go, line 133 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30666#-LOUI75f78M66hHOy0Ee:-LOUI75g-CRnE7nC01nA:b-wdhcf5) ([raw file](https://github.com/cockroachdb/cockroach/blob/681e9fb74b1927d5db6c5da76280a0f9822ba5a6/pkg/sql/drop_database.go#L133)):*
> ```Go
> 	}
> 
> 	jobID, err := p.createDropTablesJob(ctx, tableDescs, droppedTableDetails, tree.AsStringWithFlags(n.n,
> ```

nit: for readability, please you put the tree.AsStringWithFlags(..) all on one line
___
*[pkg/sql/drop_test.go, line 242 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30666#-LOUIOg2CM4Iw_FzqkMJ:-LOUIOg2CM4Iw_FzqkMK:b-nrbixj) ([raw file](https://github.com/cockroachdb/cockroach/blob/681e9fb74b1927d5db6c5da76280a0f9822ba5a6/pkg/sql/drop_test.go#L242)):*
> ```Go
> }
> 
> func TestDropDatabaseEmpty(t *testing.T) {
> ```

Please add a comment as to what this test is doing.  It helps others that are not familiar with the code.  For the other one as well.
___
*[pkg/sql/truncate.go, line 89 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30666#-LOUIiHN9-4K8SQdGwv_:-LOUIiHN9-4K8SQdGwva:b-y690ap) ([raw file](https://github.com/cockroachdb/cockroach/blob/681e9fb74b1927d5db6c5da76280a0f9822ba5a6/pkg/sql/truncate.go#L89)):*
> ```Go
> 	}
> 
> 	dropJobID, err := p.createDropTablesJob(ctx, stmtTableDescs, droppedTableDetails, tree.AsStringWithFlags(n,
> ```

nit: Please keep  the asstringwithflags() call all on one line

**Comment by BramGruneir** [comment]
with some small nits

**Comment by vivekmenezes** [comment]
I'll just take a quick look at this. Hold on

**Review by BramGruneir — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30666)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by vivekmenezes — APPROVED** [review]
Nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30666#-:-LOVr7S--xwKZQPh15D_:bdtx8r6)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/drop_test.go, line 388 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30666#-LOVqz-_DbP4CU2DLitP:-LOVqz-_DbP4CU2DLitQ:b-u3iez) ([raw file](https://github.com/cockroachdb/cockroach/blob/d38c10ff161f75f1198776cb8087fdf5cecb51d2/pkg/sql/drop_test.go#L388)):*
> ```Go
> 	if _, err := addDefaultZoneConfig(sqlDB, dbDesc.ID); err != nil {
> 		t.Fatal(err)
> 	}
> ```

perhaps add the zone config before dropping the database above.
___
*[pkg/sql/drop_test.go, line 402 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30666#-LOVqr6o9Q55gmI15-Qw:-LOVqr6o9Q55gmI15-Qx:b-dz9887) ([raw file](https://github.com/cockroachdb/cockroach/blob/d38c10ff161f75f1198776cb8087fdf5cecb51d2/pkg/sql/drop_test.go#L402)):*
> ```Go
> 	tests.CheckKeyCount(t, kvDB, table2Span, 6)
> 
> 	// Database zone config is removed once all table data and zone configs are removed.
> ```

this comment is more appropriate for the check done at the end.

**Review by eriktrinh — COMMENTED** [review]
Thanks for the review!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30666#-:-LOYOLj9AOLm_mBDyM6T:b-9qdoz3)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/drop_test.go, line 242 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30666#-LOUIOg2CM4Iw_FzqkMJ:-LOUQIKa7uSrm4lGb0Mv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/681e9fb74b1927d5db6c5da76280a0f9822ba5a6/pkg/sql/drop_test.go#L242)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Please add a comment as to what this test is doing.  It helps others that are not familiar with the code.  For the other one as well.
</blockquote></details>

Done.
___
*[pkg/sql/drop_test.go, line 388 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30666#-LOVqz-_DbP4CU2DLitP:-LOYOVrE40B_9w3QQkOE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d38c10ff161f75f1198776cb8087fdf5cecb51d2/pkg/sql/drop_test.go#L388)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

perhaps add the zone config before dropping the database above.
</blockquote></details>

Done.
___
*[pkg/sql/drop_test.go, line 402 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/30666#-LOVqr6o9Q55gmI15-Qw:-LOYOXib0M7rBSqgX2mS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d38c10ff161f75f1198776cb8087fdf5cecb51d2/pkg/sql/drop_test.go#L402)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

this comment is more appropriate for the check done at the end.
</blockquote></details>

Done.

**Comment by knz** [comment]
This needs a backport.  @benesch @BramGruneir please assist Erik if this is his first, our window for backporting is only 2 days from today.

**Comment by vivekmenezes** [comment]
This is for 2.2

**Pull request merged**
