### PR TITLE
clusterversion,sql: remove ClusterLocksVirtualTable

### PR DESCRIPTION
**Pull request by celiala**
This commit removes the 22.1 `ClusterLocksVirtualTable` version gate.

Cleanup was done following guidance from [21.2 cleanup](https://github.com/cockroachdb/cockroach/pull/74270#issuecomment-1000693734):

> For the most part, if the gates were just simple if !version.IsActive { return x } or something, I just removed the block, and even if it was a little more complicated, like args = [x]; if version { args = append(args, y) }; foo(args) I still tried to mostly inline it such that it looked natural (i.e. remove that append and make it args = [x, y]).

> However for just a couple more complicated cases that were referring to <21.2 versions that needed to be replaced when those were deleted, I added a placeholder clusterversion.TODOPre21_2 alias for 21.2. Replacing those calls with this alias shouldn't change their behavior -- it was already always true, since the code today should never run in a <21.2 cluster -- but means we can delete those older versions in the meantime and then the owners of these bits can decide how to update them.

Partially addresses https://github.com/cockroachdb/cockroach/issues/80663

Release note: none
Release justification: remove old version gates.

### CODE REVIEW

**Review by AlexTalks — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85938#-:-N9A-icLDExhUe-mpSl6:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by celiala** [comment]
TFTR!

FYI @AlexTalks that I'm going to remove `TestAutoStatsTableSettingsDisallowedOnOldCluster` -- please scream and shout if this should be kept!

Removing `TestAutoStatsTableSettingsDisallowedOnOldCluster` since:
- it was failing (expected "feature not available yet" error but instead got nil)
- it depended on both `ClusterLocksVirtualTable` and `AutoStatsTableSettings` --  both of which are 22.1 version gates

**Comment by celiala** [comment]
`TestLogic_external_connection_privileges` is failing, but same test is also failing in https://github.com/cockroachdb/cockroach/pull/85937, so I'm going to assume that it's not related to changes in this commit?

```
off_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/external_connection_privileges:24: SELECT * FROM system.privileges
        expected:
            root      /externalconn/foo  {ALL}         {}
            testuser  /externalconn/foo  {DROP,USAGE}  {}
        but found (query options: "") :
            testuser  /externalconn/foo  {DROP,USAGE}  {}
            root      /externalconn/foo  {ALL}         {}
```

**Comment by celiala** [comment]
TFTR!

bors r=AlexTalks

**Pull request merged**
