### PR TITLE
Makefile: fail upon unrecognized command-line variables

### PR DESCRIPTION
**Pull request by benesch**
Our Make incantations (e.g. `make test TESTS=SomeTestName`) are heavy on command-line specified variables. It's far too easy to fat-finger or misremember a variable name (`make test TEST=SomeTestName`) and have Make silently do the wrong thing. This commit adds some sed magic to automatically determine which variables are used by the Makefile and print a warning if the user specifies a variable on the command line that's not present in the Makefile.

----

I'm 50/50 on this change, but thought I'd throw it up here to see what others think. On the one hand, this is a hideous `sed` invocation; on the other, I've already wasted too much of my life waiting on mistyped commands like e.g. `make stress TESTFLAG=-v...` only to find out 30m later I'm not getting the debugging output I need because the variable is `TESTFLAGS`.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14301)

### CODE REVIEW

**Comment by jordanlewis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[grep, line 0 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14301#-KfqXiKZztzMAjX8kqBu:-KfqXiKZztzMAjX8kqBv:btcc0ao) ([raw file](https://github.com/cockroachdb/cockroach/blob/69521f9b2a9ce4c40c43eca60196637ff7808d8d/grep#L0)):*
What is this file?

---

*[Makefile, line 374 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14301#-KfqXrgCHL_vKCAQluqN:-KfqXrgCHL_vKCAQluqO:bnlypiq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b546284b1060fce53c01a58a0dc193713ff3da46/Makefile#L374)):*
> ```Makefile
> 	@echo '# DO NOT EDIT!' >> $@
> 	@echo 'define VALID_VARS' >> $@
> 	@sed -nE 's!(^|^[^	].*:)(override|export|define)?[ ]*([^ ]+)[ ]*[:?+]?=.*!  \3!p' $^ | sort -u >> $@
> ```

Brief comment on what this is doing would be good - I can kind of gather but I think an explainer would be helpful.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14301)*

**Comment by bdarnell** [comment]
If this goes in you're going to own that regex for the rest of your life :) If you're OK with that, this change LGTM (except for that mistaken (?) grep file). It would even be reasonable to maintain the list of valid variables by hand if the regex becomes too onerous.

**Comment by benesch** [comment]
Yup, that `grep` file was sludge from a Make rule gone wrong. More than happy to own that regex :)

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[Makefile, line 374 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14301#-KfqXrgCHL_vKCAQluqN:-Kfviy_JlyoZIvncDa6u:bv00fxg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b546284b1060fce53c01a58a0dc193713ff3da46/Makefile#L374)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Brief comment on what this is doing would be good - I can kind of gather but I think an explainer would be helpful.
</blockquote></details>

How's that look? (It's above the rule because Make makes it awkward to put comments inline in recipes.)

---

*[grep, line  at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14301#-KfqXiKZztzMAjX8kqBu:-Kfvj852tOgjfg_P0TyP:b-c7elrz) ([raw file](https://github.com/cockroachdb/cockroach/blob/69521f9b2a9ce4c40c43eca60196637ff7808d8d/grep#L)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

What is this file?
</blockquote></details>

Good catch, thanks. Deleted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14301#-:-Kfvixs3mQae50Z6W7Qo:b34582k)*

**Comment by jordanlewis** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14301#-:-KfvupEEJVWt_A_nYASr:bnfp4nl)*

**Comment by jordanlewis** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14301)*

**Pull request merged**
