### PR TITLE
*: windows fixes

### PR DESCRIPTION
**Pull request by tamird**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14582)

### CODE REVIEW

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/pgwire/pgwire_test.go, line 1445 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14582#-KgpnmjEKl0nV8SkTxPR:-KgpnmjEKl0nV8SkTxPS:b-411g3s) ([raw file](https://github.com/cockroachdb/cockroach/blob/15853e10736e547ec30333a0aeafadf1ce73cf80/pkg/sql/pgwire/pgwire_test.go#L1445)):*
> ```Go
> 			}
> 		}()
> 		if err := os.Unsetenv(unixEnvKey); err != nil {
> ```

Mutating process-wide state is a clumsy way to handle this. And this test gets skipped on windows in the next commit, so it doesn't matter whether this part is cross-platform or not. I'd just drop this commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14582#-:-KgpoTCzFYtBEZQcNKxz:bnfp4nl)*

**Comment by tamird** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/pgwire/pgwire_test.go, line 1445 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14582#-KgpnmjEKl0nV8SkTxPR:-KgpobIonHHcS8V7o6Xv:b23m4wm) ([raw file](https://github.com/cockroachdb/cockroach/blob/15853e10736e547ec30333a0aeafadf1ce73cf80/pkg/sql/pgwire/pgwire_test.go#L1445)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Mutating process-wide state is a clumsy way to handle this. And this test gets skipped on windows in the next commit, so it doesn't matter whether this part is cross-platform or not. I'd just drop this commit.
</blockquote></details>

I'd prefer to keep it as documentation of what's actually being done here, in case it gets cargo culted around.

I agree that it's clumsy, but it's also the most precise way without introducing more build tags, and the test will clean up. Neverthelss, I'm open to suggestions (other than removing this, preferably).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14582)*

**Comment by bdarnell** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/pgwire/pgwire_test.go, line 1445 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14582#-KgpnmjEKl0nV8SkTxPR:-KgppyfQBKpYiuXhZk70:bax58jl) ([raw file](https://github.com/cockroachdb/cockroach/blob/15853e10736e547ec30333a0aeafadf1ce73cf80/pkg/sql/pgwire/pgwire_test.go#L1445)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I'd prefer to keep it as documentation of what's actually being done here, in case it gets cargo culted around.

I agree that it's clumsy, but it's also the most precise way without introducing more build tags, and the test will clean up. Neverthelss, I'm open to suggestions (other than removing this, preferably).
</blockquote></details>

Cargo culting is exactly my concern - this is valid in a non-parallel test, but it would be a mistake to copy this into `sdnotify.go` which is run in real code when other things are going on.

If you insist on changing something here, I'd rather call `ioutil.TempDir("")`, check the length of the returned string, and fall back to `ioutil.TempDir("/tmp")` if the default is too long (adjusting for the amount of stuff we have to append to it below to meet the postgres driver's weird naming conventions. Would shortening `cockroach-unix` and the "port" buy us enough space to get under the limit?). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14582)*

**Comment by tamird** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/pgwire/pgwire_test.go, line 1445 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14582#-KgpnmjEKl0nV8SkTxPR:-Kgq4weloPUAJPmcn68V:b-yfx5w3) ([raw file](https://github.com/cockroachdb/cockroach/blob/15853e10736e547ec30333a0aeafadf1ce73cf80/pkg/sql/pgwire/pgwire_test.go#L1445)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Cargo culting is exactly my concern - this is valid in a non-parallel test, but it would be a mistake to copy this into `sdnotify.go` which is run in real code when other things are going on.

If you insist on changing something here, I'd rather call `ioutil.TempDir("")`, check the length of the returned string, and fall back to `ioutil.TempDir("/tmp")` if the default is too long (adjusting for the amount of stuff we have to append to it below to meet the postgres driver's weird naming conventions. Would shortening `cockroach-unix` and the "port" buy us enough space to get under the limit?). 
</blockquote></details>

It's hard to tell statically, but I've shortened all the constants for now to avoid the environment variable dance. LGTY?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14582)*

**Review by bdarnell — APPROVED** [review]

**Pull request merged**
