### PR TITLE
jobs: refactor job details UI to be uniform with statement insights

### PR DESCRIPTION
**Pull request by adityamaru**
This change tweaks the job details page to look more like our statement insights page in the DB console. At the moment there is only one "Overview" tab but a follow up will add a "Profiler" and "DistSQL Diagram" tag that will surface more advanced debugging information about the job.

Informs: #102735
Release note (ui change): the job details page now has a tabbed UI that will allow users to toggle between the "Overview" and other future views for advanced debugging and observability

### CODE REVIEW

**Comment by adityamaru** [comment]
Screenshot 2023-05-02 at 5 35 00 PM
Screenshot 2023-05-03 at 10 09 25 AM

**Review by maryliag — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102737)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru)

___
*[`pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx` line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102737#-NUvhSkh-Z86RiwN80CX:-NUvhSkh-Z86RiwN80CY:bs1o8jx) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f3497617f528359c99087dfe87d94f71a80c3e2/pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx#L100)):*
> ```XML
>   prevPage = (): void => this.props.history.goBack();
> 
>   render(): React.ReactElement {
> ```

when having a lot of tabs, it can be a lot of info (confusing) to render everything in a single function, so just to improve clarity you can create the tabs on this render and then specific render functions for each of the tab content (even if right now is just one)
e.g.:
```
<TabPane tab="Overview" key="overview">
          {this.renderOverviewTabContent(hasTimeout, hasData)}
        </TabPane>
        <TabPane tab="Explain Plans" key="explain-plan">
          {this.renderExplainPlanTabContent(hasTimeout, hasData)}
        </TabPane>
```
___
*[`pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx` line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102737#-NUvhGof1nsZDFgRotLS:-NUvhGogE3qOPHXtET4k:b-qa8b5n) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f3497617f528359c99087dfe87d94f71a80c3e2/pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx#L146)):*
> ```XML
>                   defaultActiveKey={TabKeysEnum.OVERVIEW}
>                 >
>                   <Tabs.TabPane tab={TabKeysEnum.OVERVIEW} key="overview">
> ```

nit: you can do `const { TabPane } = Tabs;` and use just `<TabPane>...`

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102737)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx` line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/102737#-NUvhSkh-Z86RiwN80CX:-NUwDnzI1PxqJMvW9fcj:b-14kldh) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f3497617f528359c99087dfe87d94f71a80c3e2/pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx#L100)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

when having a lot of tabs, it can be a lot of info (confusing) to render everything in a single function, so just to improve clarity you can create the tabs on this render and then specific render functions for each of the tab content (even if right now is just one)
e.g.:
```
<TabPane tab="Overview" key="overview">
          {this.renderOverviewTabContent(hasTimeout, hasData)}
        </TabPane>
        <TabPane tab="Explain Plans" key="explain-plan">
          {this.renderExplainPlanTabContent(hasTimeout, hasData)}
        </TabPane>
```
</blockquote></details>

yup makes sense! done.

**Review by maryliag — APPROVED** [review]
Great!
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/102737#-:-NUwEVNUArbipaBAua-t:b-wvjzc3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru)

**Comment by adityamaru** [comment]
TFTR!

bors r=maryliag

**Pull request merged**
