### PR TITLE
colexec: add support for IS NULL and IS NOT NULL

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit adds IS NULL projection and selection operators which
adds support for IS NULL and IS NOT NULL operators by the vectorized
engine.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
I’ve just realized that current unit tests are not fully useful, and I’ll update the PR tomorrow.

**Comment by yuzefovich** [comment]
Updated the unit tests, RFAL.

**Review by asubiotto — COMMENTED** [review]
Thanks for the quick turnaround

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42016#-:-LsXv4V97gGoK7N4N2lb:b-afqup7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/is_op.go, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42016#-LsXrGfx0Edt1Bn2T_bT:-LsXrGfyAM7w54JZcexI:b-xwfon5) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dfc3adbd92034bc660250858b506516e41947bb/pkg/sql/colexec/is_op.go#L46)):*
> ```Go
> }
> 
> func (o *isNullProjOperator) Next(ctx context.Context) coldata.Batch {
> ```

It would be great to template this out if it isn't too much trouble.
___
*[pkg/sql/colexec/is_op_test.go, line 164 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42016#-LsXs86u-Zm7qW95Q2Xg:-LsXs86u-Zm7qW95Q2Xh:b-cgf1c) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dfc3adbd92034bc660250858b506516e41947bb/pkg/sql/colexec/is_op_test.go#L164)):*
> ```Go
> 			negate:       false,
> 			// The input contains only NULLs already.
> 			skipAllNullsInjection: true,
> ```

I feel like we could put this `skipAllNullsInjection` into the test harness itself, i.e. only inject nulls if there is at least one non-nil in the input. What do you think?
___
*[pkg/sql/logictest/testdata/logic_test/vectorize, line 944 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42016#-LsXsTCMA4pyP9YfhxqW:-LsXsTCMA4pyP9YfhxqX:be0j7yl) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dfc3adbd92034bc660250858b506516e41947bb/pkg/sql/logictest/testdata/logic_test/vectorize#L944)):*
> ```
> sql.exec.query.is-vectorized
> 
> # Test IS NULL (and alike) projections.
> ```

We should probably add some queries from the email as well, e.g. `CASE ... WHEN IS [NOT] NULL`

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42016)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/logictest/testdata/logic_test/vectorize, line 944 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42016#-LsXsTCMA4pyP9YfhxqW:-LsYJoQwEEqScxlxTztf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dfc3adbd92034bc660250858b506516e41947bb/pkg/sql/logictest/testdata/logic_test/vectorize#L944)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

We should probably add some queries from the email as well, e.g. `CASE ... WHEN IS [NOT] NULL`
</blockquote></details>

Done.
___
*[pkg/sql/colexec/is_op.go, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42016#-LsXrGfx0Edt1Bn2T_bT:-LsYJrV1E-GO-G3jQnIP:bo0pdbc) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dfc3adbd92034bc660250858b506516e41947bb/pkg/sql/colexec/is_op.go#L46)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

It would be great to template this out if it isn't too much trouble.
</blockquote></details>

I looked into this for half an hour, and I think there is no benefits in templating here. The template is a lot harder to comprehend, and it doesn't remove any of the repetition.

I refactored the code slightly to remove some of the repetition.
___
*[pkg/sql/colexec/is_op_test.go, line 164 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42016#-LsXs86u-Zm7qW95Q2Xg:-LsY7dev8xlw8u62rUbp:b-qy06w2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dfc3adbd92034bc660250858b506516e41947bb/pkg/sql/colexec/is_op_test.go#L164)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I feel like we could put this `skipAllNullsInjection` into the test harness itself, i.e. only inject nulls if there is at least one non-nil in the input. What do you think?
</blockquote></details>

Actually test harness already knows about this (which I forgot about), and for this particular case, we can just use `runTests`.

However, there are cases when the input is not all NULLs, but the output is the same as if it were all NULLs, so, in general, we do need to keep this `skipAllNullInjection`. Take a look at `and_or_projection_test.go`: for example, `true AND NULL` evaluates to `NULL` which is the same as `NULL AND NULL`.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42016#-:-LsY_AC19Stin5eqOrBQ:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/logictest/testdata/logic_test/vectorize, line 955 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42016#-LsYZYQZ1NeZFQufhFJW:-LsYZYQZ1NeZFQufhFJX:b590peo) ([raw file](https://github.com/cockroachdb/cockroach/blob/31ff6490e24bff0b84af4071ce307563fa68662d/pkg/sql/logictest/testdata/logic_test/vectorize#L955)):*
> ```
> # Test IS NULL (and alike) selections.
> query II rowsort
> SELECT a, b FROM nulls WHERE a IS NULL
> ```

Not related just to this PR but it would be nice if 1) we could split these tests up further, this file is nearly 1000 lines long testing many different things 2) We should find a way to run all reads using `experimental_always` to double check that the statements are actually run through the vectorized engine.

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42016#-:-LsYdY4uED_5tt3zUlDj:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/logictest/testdata/logic_test/vectorize, line 955 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42016#-LsYZYQZ1NeZFQufhFJW:-LsYdPiA73kzsfZlwGfl:b2e34ar) ([raw file](https://github.com/cockroachdb/cockroach/blob/31ff6490e24bff0b84af4071ce307563fa68662d/pkg/sql/logictest/testdata/logic_test/vectorize#L955)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Not related just to this PR but it would be nice if 1) we could split these tests up further, this file is nearly 1000 lines long testing many different things 2) We should find a way to run all reads using `experimental_always` to double check that the statements are actually run through the vectorized engine.
</blockquote></details>

I agree, I'll file an issue so that we don't forget about this.

**Pull request merged**
