### PR TITLE
storageccl: add a cgo-free sstable iterator and use it in Import & AddSSTable

### PR DESCRIPTION
**Pull request by danhhz**
The cgo calls involved in iterating an sstable to rekey it and validate
it in AddSSTable are now showing up as significant in pprof (especially
when run with the in-progress sideloading work). This drastically
improves our benchmarks, see next commit.

This uses the github.com/golang/leveldb package, which has a big
"work-in-progress" warning, but the sstable parsing part seems finished.
At very worst, we can always fork it if we need any fixes.

We still need the old one for now to compute mvcc stats. I'm quite
surprised at how much of a difference computing the stats makes,
commenting it out changes the AddSSTable benchmark radically
(100/1000/10000 are ~15/30/46 MB/s).

```
name                         old time/op    new time/op    delta
AddSSTable/100-8               2.14ms ± 2%    2.17ms ± 2%     ~     (p=0.200 n=4+4)
AddSSTable/1000-8              6.68ms ± 9%    6.91ms ±14%     ~     (p=0.690 n=5+5)
AddSSTable/10000-8             52.8ms ± 3%    50.1ms ± 3%   -5.02%  (p=0.016 n=5+5)
Import/AddSSTable/1-8          2.51ms ± 1%    1.80ms ± 1%  -28.39%  (p=0.008 n=5+5)
Import/AddSSTable/100-8        3.72ms ± 1%    2.84ms ± 2%  -23.78%  (p=0.016 n=4+5)
Import/AddSSTable/10000-8      93.4ms ± 6%    81.3ms ± 4%  -13.05%  (p=0.008 n=5+5)
Import/AddSSTable/100000-8      540ms ± 6%     430ms ± 9%  -20.35%  (p=0.008 n=5+5)
ClusterRestore/AddSSTable-8    6.25µs ± 3%    5.51µs ± 6%  -11.84%  (p=0.008 n=5+5)

name                         old speed      new speed      delta
AddSSTable/100-8             8.71MB/s ± 2%  8.55MB/s ± 2%     ~     (p=0.200 n=4+4)
AddSSTable/1000-8            25.8MB/s ± 8%  25.1MB/s ±13%     ~     (p=0.690 n=5+5)
AddSSTable/10000-8           32.4MB/s ± 3%  34.1MB/s ± 3%   +5.24%  (p=0.016 n=5+5)
Import/AddSSTable/1-8         450kB/s ± 0%   626kB/s ± 1%  +39.11%  (p=0.016 n=4+5)
Import/AddSSTable/100-8      4.66MB/s ±10%  6.29MB/s ± 2%  +34.92%  (p=0.008 n=5+5)
Import/AddSSTable/10000-8    17.5MB/s ± 6%  20.1MB/s ± 4%  +14.96%  (p=0.008 n=5+5)
Import/AddSSTable/100000-8   30.2MB/s ± 6%  38.0MB/s ± 8%  +25.61%  (p=0.008 n=5+5)
ClusterRestore/AddSSTable-8  35.8MB/s ± 3%  40.7MB/s ± 6%  +13.62%  (p=0.008 n=5+5)
```

cc @petermattis in case you want to look at the storage/engine changes

### CODE REVIEW

**Comment by tschottdorf** [comment]
Beautifully self-contained commits! No substantial comments. :lgtm_strong: 

---

Reviewed 4 of 4 files at r1, 5 of 5 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/storageccl/import.go, line 301 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16614#-Kn4sWPVbSeo9xDLaEP6:-Kn4sWPVbSeo9xDLaEP7:b-gf6of0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a03c1ebf7f59441bf2b94314381b3e1b98e16b24/pkg/ccl/storageccl/import.go#L301)):*
> ```Go
> 			break
> 		}
> 		if err != nil {
> ```

Doesn't this need to be checked before you `break`?

---

*[pkg/ccl/storageccl/engineccl/multi_iterator_test.go, line 114 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16614#-Kn4syOXQVdNB9TwqQ9y:-Kn4syOXQVdNB9TwqQ9z:bolip50) ([raw file](https://github.com/cockroachdb/cockroach/blob/a03c1ebf7f59441bf2b94314381b3e1b98e16b24/pkg/ccl/storageccl/engineccl/multi_iterator_test.go#L114)):*
> ```Go
> 							break
> 						}
> 						if !testutils.IsError(err, test.errRE) {
> ```

Same here, with `err != nil`  you'll always have `!ok` so don't think you'd ever reach this.

---

*[pkg/ccl/storageccl/engineccl/sst_iterator.go, line 88 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16614#-Kn4u0cxEqyoVUw77Vzg:-Kn4u0cxEqyoVUw77Vzh:bxc6xg2) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7c7d11d8a89bb7f46e42b19162e1054dd18b9b8/pkg/ccl/storageccl/engineccl/sst_iterator.go#L88)):*
> ```Go
> 		r.err = r.iter.Close()
> 	}
> 	if err := r.iter.Close(); err != nil && r.err == nil {
> ```

The double-close is not a problem?

---

*[pkg/ccl/storageccl/engineccl/sst_iterator.go, line 164 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16614#-Kn4v2o5yEP5S6KRU0fw:-Kn4v2o5yEP5S6KRU0fx:bjwlgo6) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7c7d11d8a89bb7f46e42b19162e1054dd18b9b8/pkg/ccl/storageccl/engineccl/sst_iterator.go#L164)):*
> ```Go
> 		// This should never happen unless there is some sort of corruption of
> 		// the keys.
> 		return bytes.Compare(a, b)
> ```

Yet, you don't want to error out?

---

*[pkg/ccl/storageccl/engineccl/sst_iterator_test.go, line 31 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16614#-Kn4wTA4tg0bf78-xLZr:-Kn4wTA4tg0bf78-xLZs:b9kpat) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7c7d11d8a89bb7f46e42b19162e1054dd18b9b8/pkg/ccl/storageccl/engineccl/sst_iterator_test.go#L31)):*
> ```Go
> 		ok, err := iter.Valid()
> 		if err != nil {
> 			t.Fatalf("%+v", err)
> ```

here and below: why not just `t.Fatal(err)`?

---

*[pkg/ccl/storageccl/engineccl/sst_iterator_test.go, line 46 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16614#-Kn4woHanKskDoIpwXYg:-Kn4woHbEEd9aXJjV5ar:b639ch6) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7c7d11d8a89bb7f46e42b19162e1054dd18b9b8/pkg/ccl/storageccl/engineccl/sst_iterator_test.go#L46)):*
> ```Go
> 	}
> 	iter.Close()
> 	if _, err := iter.Valid(); err != nil {
> ```

don't wanna check that it returns `false, nil`?

---

*[pkg/ccl/storageccl/engineccl/sst_iterator_test.go, line 68 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16614#-Kn4x0g9Mul8Fxk0mNjd:-Kn4x0gATkgfMtRy1c6G:b4rnat7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7c7d11d8a89bb7f46e42b19162e1054dd18b9b8/pkg/ccl/storageccl/engineccl/sst_iterator_test.go#L68)):*
> ```Go
> 			Key: engine.MVCCKey{
> 				Key:       []byte{i},
> 				Timestamp: hlc.Timestamp{WallTime: int64(i + 2)},
> ```

why `i+2`? Intentionally avoiding `WallTime==0`?

---

*[pkg/ccl/storageccl/engineccl/sst_iterator_test.go, line 75 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16614#-Kn4x_pWoPzLgz1FgJ9v:-Kn4x_pXvWFmN_8qLCLb:b-skhhbz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7c7d11d8a89bb7f46e42b19162e1054dd18b9b8/pkg/ccl/storageccl/engineccl/sst_iterator_test.go#L75)):*
> ```Go
> 			t.Fatalf("%+v", err)
> 		}
> 		kv.Key.Timestamp.WallTime = int32(i + 1)
> ```

I don't understand why it's `i+1` here but `i+2` above. Perhaps some comments would help.

---

*[pkg/ccl/storageccl/engineccl/sst_iterator_test.go, line 126 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16614#-Kn4xAN99uRs4QUsboeQ:-Kn4xAN99uRs4QUsboeR:b-nnz5hf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7c7d11d8a89bb7f46e42b19162e1054dd18b9b8/pkg/ccl/storageccl/engineccl/sst_iterator_test.go#L126)):*
> ```Go
> 	c := cockroachComparer{}
> 	if x := c.Compare(keyAIntent, keyA1); x != -1 {
> 		t.Errorf("expected intent to sort first got: %d", x)
> ```

I don't 100% remember the MVCC encoding, but is this really an intent? I thought we mostly stored the latest version inlined in the metadata key (which includes intents, but still).

---

*[pkg/storage/engine/batch.go, line 250 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16614#-Kn4yHm-JJBTwENlcnZx:-Kn4yHm0no2lecMWEWPE:b-qle4ja) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7c7d11d8a89bb7f46e42b19162e1054dd18b9b8/pkg/storage/engine/batch.go#L250)):*
> ```Go
> 	timestampLength := 0
> 	if key.Timestamp != (hlc.Timestamp{}) {
> 		timestampLength = 1 + 8
> ```

Comment on the `1` and `8`.

---

*[pkg/storage/engine/batch.go, line 256 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16614#-Kn4yLvscftWyR73KiRT:-Kn4yLvscftWyR73KiRU:b-isjr86) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7c7d11d8a89bb7f46e42b19162e1054dd18b9b8/pkg/storage/engine/batch.go#L256)):*
> ```Go
> 	}
> 
> 	dbKey := make([]byte, len(key.Key)+timestampLength+1)
> ```

Comment on the `+1`.

---

*[pkg/storage/engine/batch.go, line 270 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16614#-Kn4zDUmJKLNd9D_IOGn:-Kn4zDUmJKLNd9D_IOGo:b67kowf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7c7d11d8a89bb7f46e42b19162e1054dd18b9b8/pkg/storage/engine/batch.go#L270)):*
> ```Go
> 		}
> 	}
> 	dbKey[pos] = byte(timestampLength)
> ```

`pos` is now `len(dbKey)-1`, no? Might be more illuminating to call it that (ok, perhaps slower).

---

*[pkg/storage/engine/engine.go, line 34 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16614#-Kn4tFFv8zpWGHVDZrpN:-Kn4tFFv8zpWGHVDZrpO:b-ai0vk8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a03c1ebf7f59441bf2b94314381b3e1b98e16b24/pkg/storage/engine/engine.go#L34)):*
> ```Go
> // engine. SimpleIterator implementations are thread safe unless otherwise
> // noted. SimpleIterator is a subset of the functionality offered by Iterator.
> type SimpleIterator interface {
> ```

Initially thought a good name would be `ForwardIterator`, but then some other methods are also absent, so `SimpleIterator` seems fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16614#-:-Kn4zy1e5qjgm9s6raeF:b-1ng7yn)*

**Comment by danhhz** [comment]
Wow, there were some brain farts in here. Thanks for the close review!

---

Review status: 2 of 10 files reviewed at latest revision, 13 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/storageccl/import.go, line 301 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16614#-Kn4sWPVbSeo9xDLaEP6:-Kn5V3gvM3XyntkNf8Ti:b-wmx3it) ([raw file](https://github.com/cockroachdb/cockroach/blob/a03c1ebf7f59441bf2b94314381b3e1b98e16b24/pkg/ccl/storageccl/import.go#L301)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Doesn't this need to be checked before you `break`?
</blockquote></details>

Yup. Done.

---

*[pkg/ccl/storageccl/engineccl/multi_iterator_test.go, line 114 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16614#-Kn4syOXQVdNB9TwqQ9y:-Kn5V9yF6v2sBwvOkZ2t:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a03c1ebf7f59441bf2b94314381b3e1b98e16b24/pkg/ccl/storageccl/engineccl/multi_iterator_test.go#L114)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Same here, with `err != nil`  you'll always have `!ok` so don't think you'd ever reach this.
</blockquote></details>

Done.

---

*[pkg/ccl/storageccl/engineccl/sst_iterator.go, line 88 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16614#-Kn4u0cxEqyoVUw77Vzg:-Kn5VIPHX3zI2W53ADsg:b-meubbr) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7c7d11d8a89bb7f46e42b19162e1054dd18b9b8/pkg/ccl/storageccl/engineccl/sst_iterator.go#L88)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

The double-close is not a problem?
</blockquote></details>

Oh whoops. Supposed to be sst

---

*[pkg/ccl/storageccl/engineccl/sst_iterator.go, line 164 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16614#-Kn4v2o5yEP5S6KRU0fw:-Kn5VPEpluw2TtxMNnHW:b60fjz2) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7c7d11d8a89bb7f46e42b19162e1054dd18b9b8/pkg/ccl/storageccl/engineccl/sst_iterator.go#L164)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Yet, you don't want to error out?
</blockquote></details>

Added to the comment.

---

*[pkg/ccl/storageccl/engineccl/sst_iterator_test.go, line 31 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16614#-Kn4wTA4tg0bf78-xLZr:-Kn5Vbx_wumo8zzxsILE:br11oxt) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7c7d11d8a89bb7f46e42b19162e1054dd18b9b8/pkg/ccl/storageccl/engineccl/sst_iterator_test.go#L31)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

here and below: why not just `t.Fatal(err)`?
</blockquote></details>

I like stacktraces in my errors. t.Fatal(err) just prints the error message, no?

---

*[pkg/ccl/storageccl/engineccl/sst_iterator_test.go, line 46 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16614#-Kn4woHanKskDoIpwXYg:-Kn5W8C6vmk8RsOFLtXY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7c7d11d8a89bb7f46e42b19162e1054dd18b9b8/pkg/ccl/storageccl/engineccl/sst_iterator_test.go#L46)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

don't wanna check that it returns `false, nil`?
</blockquote></details>

Done.

---

*[pkg/ccl/storageccl/engineccl/sst_iterator_test.go, line 68 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16614#-Kn4x0g9Mul8Fxk0mNjd:-Kn5W92nHPZh1rHbvWhL:bchzff1) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7c7d11d8a89bb7f46e42b19162e1054dd18b9b8/pkg/ccl/storageccl/engineccl/sst_iterator_test.go#L68)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

why `i+2`? Intentionally avoiding `WallTime==0`?
</blockquote></details>

Whoops. Started doing something complicated here and realized it wasn't necessary. Apparently I forgot to back it out? who knows

---

*[pkg/ccl/storageccl/engineccl/sst_iterator_test.go, line 75 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16614#-Kn4x_pWoPzLgz1FgJ9v:-Kn5WBObm18BSMVkZxyc:b-89a4l7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7c7d11d8a89bb7f46e42b19162e1054dd18b9b8/pkg/ccl/storageccl/engineccl/sst_iterator_test.go#L75)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

I don't understand why it's `i+1` here but `i+2` above. Perhaps some comments would help.
</blockquote></details>

Ditto

---

*[pkg/ccl/storageccl/engineccl/sst_iterator_test.go, line 126 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16614#-Kn4xAN99uRs4QUsboeQ:-Kn5WNJOiGPP-1h17Ju9:b-pty5ab) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7c7d11d8a89bb7f46e42b19162e1054dd18b9b8/pkg/ccl/storageccl/engineccl/sst_iterator_test.go#L126)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

I don't 100% remember the MVCC encoding, but is this really an intent? I thought we mostly stored the latest version inlined in the metadata key (which includes intents, but still).
</blockquote></details>

1) Ah yes, metadata is more correct 2) It's sometimes stored inline, but I can't say I know when. see (MVCCMetadata).IsInline and its use in MVCCIterate. BACKUP explicitly errors on inline metadata (via a check in MVCCIncrementalIterator), so I think it's just the timeseries data or something

---

*[pkg/storage/engine/batch.go, line 250 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16614#-Kn4yHm-JJBTwENlcnZx:-Kn5YySFxCpqvFW6tAIH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7c7d11d8a89bb7f46e42b19162e1054dd18b9b8/pkg/storage/engine/batch.go#L250)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Comment on the `1` and `8`.
</blockquote></details>

Done.

---

*[pkg/storage/engine/batch.go, line 256 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16614#-Kn4yLvscftWyR73KiRT:-Kn5Yy4KC3cf5RRjSap7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7c7d11d8a89bb7f46e42b19162e1054dd18b9b8/pkg/storage/engine/batch.go#L256)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Comment on the `+1`.
</blockquote></details>

Done.

---

*[pkg/storage/engine/batch.go, line 270 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16614#-Kn4zDUmJKLNd9D_IOGn:-Kn5Yx_3BfjUTvWLYUp4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7c7d11d8a89bb7f46e42b19162e1054dd18b9b8/pkg/storage/engine/batch.go#L270)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

`pos` is now `len(dbKey)-1`, no? Might be more illuminating to call it that (ok, perhaps slower).
</blockquote></details>

Done.

---

*[pkg/storage/engine/engine.go, line 34 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16614#-Kn4tFFv8zpWGHVDZrpN:-Kn5YzdhFJ4vQ_MhIff2:b-61etcq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a03c1ebf7f59441bf2b94314381b3e1b98e16b24/pkg/storage/engine/engine.go#L34)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Initially thought a good name would be `ForwardIterator`, but then some other methods are also absent, so `SimpleIterator` seems fine.
</blockquote></details>

Yeah, I also omitted Key, Value, ValueProto, and Less since they're entirely derivable from UnsafeKey and UnsafeValue

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16614#-:-Kn5ciBKuWgzJ3Yeslbt:bk88rp2)*

**Comment by tschottdorf** [comment]
Make sure you rebase when the write skew on `master` is fixed.

---

Reviewed 8 of 8 files at r4, 5 of 5 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/storageccl/engineccl/sst_iterator.go, line 89 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/16614#-Kn5ey4yZX4a9duY6lau:-Kn5ey4zC6ZasJSV0Wib:b-b7xzew) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a48fd6130c7bf619456e07159964d001d2eb5b/pkg/ccl/storageccl/engineccl/sst_iterator.go#L89)):*
> ```Go
> 	}
> 	if err := r.sst.Close(); err != nil && r.err == nil {
> 		r.err = err
> ```

Just a suggestion, but you could liberally use `errors.Wrap` here because once `r.err` is read it's absolutely not clear who wrote it; something like `errors.Wrap(err, "while closing sst")` could go a long way.

---

*[pkg/ccl/storageccl/engineccl/sst_iterator_test.go, line 31 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16614#-Kn4wTA4tg0bf78-xLZr:-Kn5fHIVgKNDf863CWcB:b-atezrs) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7c7d11d8a89bb7f46e42b19162e1054dd18b9b8/pkg/ccl/storageccl/engineccl/sst_iterator_test.go#L31)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I like stacktraces in my errors. t.Fatal(err) just prints the error message, no?
</blockquote></details>

Yeah, that's what it would do - I suppose now that we use the better `errors` package, this makes some sense.

---

*[pkg/ccl/storageccl/engineccl/sst_iterator_test.go, line 72 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/16614#-Kn5fW0DJWOrGV_Jg4ag:-Kn5fW0EVh76VdeJTpwl:b-y3gm9j) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a48fd6130c7bf619456e07159964d001d2eb5b/pkg/ccl/storageccl/engineccl/sst_iterator_test.go#L72)):*
> ```Go
> 				Timestamp: hlc.Timestamp{WallTime: int64(i)},
> 			},
> 			Value: []byte{i, i},
> ```

Just curious, why two bytes?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16614#-:-Kn5frXohdcpdBFHSoWt:b7j16k2)*

**Comment by danhhz** [comment]
Whoops. I was so excited to merge I forgot to post my responses

---

Review status: 3 of 10 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/storageccl/engineccl/sst_iterator.go, line 89 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/16614#-Kn5ey4yZX4a9duY6lau:-Kn6ANXPUl9wxciUDWMv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a48fd6130c7bf619456e07159964d001d2eb5b/pkg/ccl/storageccl/engineccl/sst_iterator.go#L89)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Just a suggestion, but you could liberally use `errors.Wrap` here because once `r.err` is read it's absolutely not clear who wrote it; something like `errors.Wrap(err, "while closing sst")` could go a long way.
</blockquote></details>

Done.

---

*[pkg/ccl/storageccl/engineccl/sst_iterator_test.go, line 72 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/16614#-Kn5fW0DJWOrGV_Jg4ag:-Kn6AQipvhJrPXeiqizM:bz3pmqj) ([raw file](https://github.com/cockroachdb/cockroach/blob/86a48fd6130c7bf619456e07159964d001d2eb5b/pkg/ccl/storageccl/engineccl/sst_iterator_test.go#L72)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Just curious, why two bytes?
</blockquote></details>

Just to make it different than the key. But if you thought this was notable and it's not, it's bound to be more confusing than helpful. Switched back.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16614#-:-Kn6Igp17p01MVRvFks5:bqa7r43)*

**Pull request merged**
