### PR TITLE
clusterversion: add PebbleFormatSplitUserKeysMarked

### PR DESCRIPTION
**Pull request by jbowens**
See cockroachdb/pebble#1495.

Add a new 22.1 cluster version that ratchets the Pebble format major version to
FormatSplitUserKeysMarked, performing an internal Pebble migration to mark
split user keys for compaction.

Release justification: high-priority migration
Release note: None

### CODE REVIEW

**Review by nicktrav — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77634#-:-MxpZts_DXhCuvHzgywY:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens)

**Review by nicktrav — COMMENTED** [review]
I was thinking .. is it worth writing a roachtest that writes a bunch of "split" sstables (would have to be on an older binary, and I'm not sure if we have a way to ensure such a thing?) and then starts up with a new version of the binary and asserts that the migration completes, and that there are no more split keys? Perhaps with cheks={true,false}. 

Maybe it's overkill, given we have test coverage in the single store case (via the Pebble tests). Happy to look into that if you think it adds value.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77634#-:-MxpZwTKCMAr5Ef-7mw4:b-wr8ba5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens)

**Review by nicktrav — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77634)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jbowens)

**Review by jbowens — COMMENTED** [review]
That would be cool. I think there are some mixed-version roachtests that pull prebuilt older binaries to test upgrade flows, and those might provide prior art for doing something like that. But I'm not sure how to get CockroachDB to actually construct these "split" sstables though. I'd expect them to be exceedingly rare in practice. They require:

* A key to be written twice. I'm not sure under what circumstances CockroachDB will even ever write a key multiple times, other than GC laying down a point tombstone or maybe keys within the range-local keyspace?
* A LSM snapshot to be open between the two keys when the sstable is written.
* The two or more identical keys need to happen to fall into the boundary of the sstables during a compaction.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77634#-:-MxpmK2uBCjD57su6dW_:bbicx4l)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jbowens)

**Review by jbowens — COMMENTED** [review]
TFTR!

bors r=nicktrav

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77634#-:-Mxq5wabEXd13_zPET3_:b1zv9gn)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jbowens)

**Pull request merged**
