### PR TITLE
cli: add signal handler to launch pprof endpoints

### PR DESCRIPTION
**Pull request by dt**
If we come across a stuck cockroach command that isn't a server, sometimes it is
is very difficult to debug it, as these non-server commands do not default to starting
a server on which to serve the usual pprof endpoints. These endpoints are enormously
helpful in debugging stuck processes, memory usage or performance, but at the same time
we do not want to just always start an http server in every shell command execution.
We could conditionally start a server on some flag or env var, but in many cases by the
time we realize we need to investigate the state of a stuck process, it is already running.

Instead, this change introduces a signal handler so that any cockroach process can be sent a
SIGUSR2 signal that will cuase it to start an http server bound to localhost that serves the
pprof inspection endpoints (heap, cpu, goroutine, etc).

Release note (ops change): sending a cockroach process, including one running a client command, a SIGUSR2 signal now causes it to open an http port that is serving the basic go performance inspection endpoints for use with pprof.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
LGTM on the idea/direction but please add a context cancellation to this, we need to ensure that no goroutines are leaked when we run all these CLI commands in unit tests.

> Reviewed 3 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75678#-:-MujiWOWE5vWsqZ2uFfr:b3zd3qt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

**Review by knz — APPROVED** [review]
> Reviewed 3 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75678)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt)

**Comment by dt** [comment]
Oh, good point, added a shutdown to them. Though now I'm not sure why the existing sigquit handler in `start` was OK before without it?

**Comment by dt** [comment]
@knz Is there anyone else on the security who you think should review this? I don't believe there's a problem, since you have to already own the process (or be root) to signal it, but want to make sure security is on same page too.

**Comment by knz** [comment]
> Though now I'm not sure why the existing sigquit handler in start was OK before

:thinking: 

Here's why:

```go
// pkg/util/leaktest/leaktest.go

func interestingGoroutines(...) {
   ...
   strings.Contains(stack, "signal.signal_recv") ||
   ...
```

What you have here is fine though. Maybe we can remove the leaktest exemption now, but I wouldn't care about it now.

> Is there anyone else on the security who you think should review this? I don't believe there's a problem, since you have to already own the process (or be root) to signal it, but want to make sure security is on same page too.

Agreed - I don't think there's anything special here. Cheers

**Review by knz — APPROVED** [review]
:lgtm: ready to go :shipit: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75678#-:-MulWV9i6CWYhA9skpsy:b-ce2v5k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

**Comment by dt** [comment]
Thanks for the fixes! Will bors on green.

**Comment by dt** [comment]
TFTR!

bors r+

**Pull request merged**
