### PR TITLE
*: allow go-1.7*

### PR DESCRIPTION
**Pull request by petermattis**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10125)

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM

nit: `*: allow go-1.7*`

**Comment by petermattis** [comment]
That's a pretty nitty-nit. Are we overly getting overly nitty?

**Comment by tschottdorf** [comment]
I was thinking about your categorization tool, but (at least my) nits are always strictly optional anyway.

**Comment by petermattis** [comment]
That tool only applies to issues, not PRs.

**Comment by andreimatei** [comment]
LGTM

**Pull request merged**
