### PR TITLE
storage/storageccl: Add an option to break export mid key

### LINKED ISSUE #68231: Allow ExportRequest to resume exports on timestamp boundary
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when export request can not return back an SST because size of all versions for the key in backup exceeds kv.bulk_sst.max_allowed_overage.

**Describe the solution you'd like**
Export request should return next key timestamp together with resume span and accept it as an optional argument so that export can have finer grained control over export boundaries. This is also needed to make export batches smaller and provide more efficient export throttling control.

**Additional context**
Part of #66486

### PR DESCRIPTION
**Pull request by aliher1911**
Previously when exporting ranges with very large number of versions
export could hit the situation where single key export would exceed
maximum export byte limit. To resolve this, safety threshold has to
be raised which could cause nodes going out of memory.

To address this, this patch adds an ability to stop and resume on
the arbitrary key timestamp so that it could be stopped mid key and
resumed later.

Release note: None

Fixes #68231

### CODE REVIEW

**Comment by aliher1911** [comment]
Want to get feedback on this before I add any client side code from backup_processor to the mix.
Currently split into 2 commits, one on the pebble side and another on request/response for export.

**Review by pbardea — COMMENTED** [review]
> Reviewed 2 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68102)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911 and @sumeerbhola)

___
*[pkg/ccl/storageccl/export.go, line 183 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68102#-MgBTSKmAuXKDo7yciGw:-MgBTSKn12AXI3gxRhHc:bzexa4b) ([raw file](https://github.com/cockroachdb/cockroach/blob/5aa02cceb8902ff8dc8e7c1a23f72b24c083dad0/pkg/ccl/storageccl/export.go#L183)):*
> ```Go
> 	// Only use resume timestamp if splitting mid key is enabled.
> 	resumeKeyTs := hlc.Timestamp{}
> 	if args.SplitMidKey {
> ```

Can we only permit SplitMidKey be set if `args.ReturnSST` is set? Backup/restore's accounting of these SSTs treats them as covering a complete span, so if we do split and ExportRequest mid SST, the backup processor should have a chance to stitch it together at the callsite. (We don't want to add a timestamp field to `BackupManifest_File`.)

We'll soon want to move to all requests setting `args.ReturnSST` to true so I don't think that this is a big limitation.
___
*[pkg/roachpb/api.proto, line 1368 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68102#-MgBVUAF2_67-oSlI_Bl:-MgBVUAF2_67-oSlI_Bm:b-a5ppgv) ([raw file](https://github.com/cockroachdb/cockroach/blob/5aa02cceb8902ff8dc8e7c1a23f72b24c083dad0/pkg/roachpb/api.proto#L1368)):*
> ```protobuf
>   // different from start_time.
>   util.hlc.Timestamp resume_key_ts = 12 [(gogoproto.nullable) = false];
>   util.hlc.Timestamp start_time = 3 [(gogoproto.nullable) = false];
> ```

With serveral timestamps in the request, perhaps it'd be worthwhile to add a comment saying that `StartTime` is meaningful only with `MVCCFilter` set to all revisions, and that it is the lower bound on MVCCVersions of exported keys?
___
*[pkg/roachpb/api.proto, line 1445 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68102#-MgBV4tf8qYifc0Fw-Gx:-MgBV4tf8qYifc0Fw-Gy:b-gy2ikh) ([raw file](https://github.com/cockroachdb/cockroach/blob/5aa02cceb8902ff8dc8e7c1a23f72b24c083dad0/pkg/roachpb/api.proto#L1445)):*
> ```protobuf
>   message File {
>     Span span = 1 [(gogoproto.nullable) = false];
>     util.hlc.Timestamp resume_key_ts = 9 [(gogoproto.nullable) = false];
> ```

Does `resumeKeyTS` semantically make sense to describe the contents of the file? Perhaps something like `endKeyTS`?

Also nit: `(gogoproto.customname) = "ResumeKeyTS"` (for here and the change to exportrequest above)
___
*[pkg/storage/pebble_batch.go, line 136 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68102#-MgBWZRl7-Jhc5jXq13B:-MgBWZRl7-Jhc5jXq13C:bo0tief) ([raw file](https://github.com/cockroachdb/cockroach/blob/b66324d9ffde310213ebe76853f255996a10f49a/pkg/storage/pebble_batch.go#L136)):*
> ```Go
> 	startKey, endKey roachpb.Key,
> 	startTS, endTS hlc.Timestamp,
> 	firstKeyTs hlc.Timestamp,
> ```

nit: `s/firstKeyTs/firstKeyTS/g` and `s/resumeTs/resumeTS/g`

**Review by aliher1911 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68102)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911, @pbardea, and @sumeerbhola)

___
*[pkg/ccl/storageccl/export.go, line 183 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68102#-MgBTSKmAuXKDo7yciGw:-MgBh5bvB9ZqO-jLPMwE:b-4dyo9u) ([raw file](https://github.com/cockroachdb/cockroach/blob/5aa02cceb8902ff8dc8e7c1a23f72b24c083dad0/pkg/ccl/storageccl/export.go#L183)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Can we only permit SplitMidKey be set if `args.ReturnSST` is set? Backup/restore's accounting of these SSTs treats them as covering a complete span, so if we do split and ExportRequest mid SST, the backup processor should have a chance to stitch it together at the callsite. (We don't want to add a timestamp field to `BackupManifest_File`.)

We'll soon want to move to all requests setting `args.ReturnSST` to true so I don't think that this is a big limitation.
</blockquote></details>

I think we can't just remove the option because of mixed version clusters to retain ability to still do non-split exports, but we can check that this option can't be set if ReturnSST is false and fail.
Does that make sense?

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68102)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911 and @sumeerbhola)

___
*[pkg/ccl/storageccl/export.go, line 183 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68102#-MgBTSKmAuXKDo7yciGw:-MgBiXAw-lyWlPv-2Q-Y:b-8f8ogp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5aa02cceb8902ff8dc8e7c1a23f72b24c083dad0/pkg/ccl/storageccl/export.go#L183)):*
> but we can check that this option can't be set if ReturnSST is false and fail

Yes, that sounds good

Sorry, I didn't meant to remove any option, just that we expect almost all requests (the exception being mixed-version requests) to set args.ReturnSST to true.

**Review by sumeerbhola — COMMENTED** [review]
The `storage` changes look fine. 
- `MVCCIncrementalIterator.SeekGE` has a code comment that says "startKey should be a metadata key to ensure ..." that needs tweaking.
- is the logic in`pebbleExportToSst` adequately tested using `export_test.go` -- could you look at the code coverage?

:lgtm: 

> Reviewed 8 of 9 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68102#-:-MgCLmvP4AjTsnG-_MVn:b-7u1jwq)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aliher1911 and @sumeerbhola)

___
*[pkg/storage/engine.go, line 410 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68102#-MgCJgm-7ps5G14dMluj:-MgCJgm-7ps5G14dMluk:bu0hw8z) ([raw file](https://github.com/cockroachdb/cockroach/blob/b66324d9ffde310213ebe76853f255996a10f49a/pkg/storage/engine.go#L410)):*
> ```Go
> 	//
> 	// This function looks at MVCC versions and intents, and returns an error if an
> 	// intent is found.
> ```

can you add stuff to the function comment about firstKeyTs and stopMidKey.

**Review by aliher1911 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68102)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aliher1911, @pbardea, and @sumeerbhola)

___
*[pkg/ccl/storageccl/export.go, line 183 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68102#-MgBTSKmAuXKDo7yciGw:-MgLxHUF0CG5xfxE1VUV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5aa02cceb8902ff8dc8e7c1a23f72b24c083dad0/pkg/ccl/storageccl/export.go#L183)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

> but we can check that this option can't be set if ReturnSST is false and fail

Yes, that sounds good

Sorry, I didn't meant to remove any option, just that we expect almost all requests (the exception being mixed-version requests) to set args.ReturnSST to true.
</blockquote></details>

Done.
___
*[pkg/roachpb/api.proto, line 1368 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68102#-MgBVUAF2_67-oSlI_Bl:-MgLxIN0EGdY2WRKCuB_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5aa02cceb8902ff8dc8e7c1a23f72b24c083dad0/pkg/roachpb/api.proto#L1368)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

With serveral timestamps in the request, perhaps it'd be worthwhile to add a comment saying that `StartTime` is meaningful only with `MVCCFilter` set to all revisions, and that it is the lower bound on MVCCVersions of exported keys?
</blockquote></details>

Done.
___
*[pkg/roachpb/api.proto, line 1445 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/68102#-MgBV4tf8qYifc0Fw-Gx:-MgLepxTEb8fxUehacs4:b-bt38ou) ([raw file](https://github.com/cockroachdb/cockroach/blob/5aa02cceb8902ff8dc8e7c1a23f72b24c083dad0/pkg/roachpb/api.proto#L1445)):*
> resumeKeyTS
Yeah you are absolutely right! endKeyTS would be more consistent with how it is named in the Span where we have start and end keys.

**Review by aliher1911 — COMMENTED** [review]
@sumeerbhola can you elaborate on `SeekGE`, is it no longer the case that we can seek intents and keys separately because of how we store them now? Our current resume usage didn't change much here.

Test coverage look fine, I just added new tests there and wrapped that as a table test to cover different cases.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68102#-:-MgMmy5qDc6EjQjD3RzX:bmmlmtp)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @pbardea and @sumeerbhola)

___
*[pkg/storage/engine.go, line 410 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68102#-MgCJgm-7ps5G14dMluj:-MgMmvL07jkcZ7L2kIdH:b8tmtoq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b66324d9ffde310213ebe76853f255996a10f49a/pkg/storage/engine.go#L410)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can you add stuff to the function comment about firstKeyTs and stopMidKey.
</blockquote></details>

Seems like comment went a bit out of date since writer was added. Does it also make sense to wrap it in a struct later, since not all of them are always applicable.

**Review by sumeerbhola — COMMENTED** [review]
The fact that they are separate is hidden from the user of `MVCCIncrementalIterator`, so I didn't mean to refer to the separated intents stuff. The comment currently says
```
startKey should be a metadata key to ensure that the iterator has a chance to observe any intents on the key if they are there.
```
and now we are not necessarily passing in a metadata key because we may have already observed the intent and are resuming from a particular version.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68102#-:-MgMyRT540oySMhvz2kE:b-3j1b97)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @pbardea and @sumeerbhola)

**Review by aliher1911 — COMMENTED** [review]
Updated comments on MVCCIncrementalIterator!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68102#-:-MgPlnj-4kDs9Y-fotwJ:b48qk8x)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @pbardea and @sumeerbhola)

**Review by sumeerbhola — COMMENTED** [review]
> Reviewed 1 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68102)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aliher1911, @pbardea, and @sumeerbhola)

___
*[pkg/storage/engine.go, line 410 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68102#-MgCJgm-7ps5G14dMluj:-MgQi1k0B9fSQfzbgZEl:bb557xj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b66324d9ffde310213ebe76853f255996a10f49a/pkg/storage/engine.go#L410)):*
<details><summary><i>Previously, aliher1911 (Oleg) wrote…</i></summary><blockquote>

Seems like comment went a bit out of date since writer was added. Does it also make sense to wrap it in a struct later, since not all of them are always applicable.
</blockquote></details>

wrapping in an options struct sounds good.
___
*[pkg/storage/engine.go, line 394 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68102#-MgQhHkv7Vv7c0GVJhmo:-MgQhHkv7Vv7c0GVJhmp:b-7lmm4h) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fc4ce2fba0da911a3f393ee788bb583fad6fc0a/pkg/storage/engine.go#L394)):*
> ```Go
> 	// If stopMidKey is used, firstKeyTS would serve as the timestamp for export to
> 	// resume together with a startKey. firstKeyTs doesn't necessarily need to be
> 	// between startTS and endTS.
> ```

what is the case in which it won't be in (startTS, endTS]?
also, it looks like firstKeyTS is unilaterally used. Maybe say that:
firstKeyTS is either empty, which represents starting from the potential intent and continuing to the versions, or non-empty, which represents starting from a particular version. firstKeyTS will always be empty when !stopMidKey.

**Review by aliher1911 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68102)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aliher1911, @pbardea, and @sumeerbhola)

___
*[pkg/storage/engine.go, line 394 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68102#-MgQhHkv7Vv7c0GVJhmo:-MgQvMpL9sxQbPvYyx_a:b-km5wzf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0fc4ce2fba0da911a3f393ee788bb583fad6fc0a/pkg/storage/engine.go#L394)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

what is the case in which it won't be in (startTS, endTS]?
also, it looks like firstKeyTS is unilaterally used. Maybe say that:
firstKeyTS is either empty, which represents starting from the potential intent and continuing to the versions, or non-empty, which represents starting from a particular version. firstKeyTS will always be empty when !stopMidKey.

</blockquote></details>

Currently it is always empty or within (startTS, endTS] but there's another PR that would break this assumption if that change sounds feasible. Idea is to stop iterating after we hit certain underlying iteration limits https://github.com/cockroachdb/cockroach/pull/68467. In that case iterator could stop while skipping outside the (startTS, endTS] range and resuming it from that point will either bring us to start of interval or next key depending on where we stopped.

**Review by aliher1911 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68102)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @pbardea and @sumeerbhola)

___
*[pkg/storage/engine.go, line 410 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68102#-MgCJgm-7ps5G14dMluj:-MgjHxmcEp-i8Cwhjpnv:b5kr1ae) ([raw file](https://github.com/cockroachdb/cockroach/blob/b66324d9ffde310213ebe76853f255996a10f49a/pkg/storage/engine.go#L410)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

wrapping in an options struct sounds good.
</blockquote></details>

I'll do that with separate PR

**Review by pbardea — APPROVED** [review]
Looks good to me

**Comment by aliher1911** [comment]
@sumeerbhola just checking if you have any more comments on that beside what was addressed. Before I rebase past breakages and merge that.

**Comment by aliher1911** [comment]
bors r=pbardea,sumeerbhola

**Pull request merged**
