### PR TITLE
doc:fix link

### PR DESCRIPTION
**Pull request by EamonZhang**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13550)

### CODE REVIEW

**Comment by tamird** [comment]
@EamonZhang looks like there are a bunch of commits here, including an entire translation of the design doc. I believe we decided that since none of the core team members are fluent in Chinese, that we would not include that translation in this repository.

Could you rebase those additional commits out and keep only the link fix? I'd be happy to merge this then.

**Comment by EamonZhang** [comment]
@tamird 

#13445 The question has been discussed! :)

**Comment by tamird** [comment]
Ah, thanks, I couldn't find that! Anyhow, could you rebase this to include just the link fix?

**Comment by EamonZhang** [comment]
OK，no problem.

https://bodani.github.io/docs/cockroach/design.html

**Pull request closed without merging**
