### PR TITLE
sql: return timestamps with offsets in session offset

### PR DESCRIPTION
**Pull request by dt**
#6165 introduced a separate type for timestamps that include offsets when rendered, but didn't actually change the contents of those offsets -- just whether or not they are rendered.

This plumbs the actual session offset through so that it is used to render time stamps with offsets in the session offset rather than UTC.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6183)

### CODE REVIEW

**Comment by vivekmenezes** [comment]
Review status: 0 of 9 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[sql/session.go, line 112 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6183#-KFtU2frvPUKpNRxZw4H:-KFtU2frvPUKpNRxZw4I:-1263598620) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3eb09302914d59b63f1a5f57ea50b5e1f528310/sql/session.go#L112)):*
you could also always initialize the timezone to UTC

---

*[sql/set.go, line 116 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6183#-KFtUgBSkbozRlIWroc4:-KFtUgBSkbozRlIWroc5:-983651609) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3eb09302914d59b63f1a5f57ea50b5e1f528310/sql/set.go#L116)):*
I can see this error happening all the time because the time zone file loaded by the database might not contain the named time zone. 

---

*[sql/set.go, line 117 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6183#-KFtV1xO9g9wywlT7sxb:-KFtV1xO9g9wywlT7sxc:-1556447599) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a92e8e79ab55cd7daa395126eeb697ef9f901a1/sql/set.go#L117)):*
Do we still need the SessionLocation type?

---

*[sql/set.go, line 143 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6183#-KFtVINe0xFYuTAdom5A:-KFtVINe0xFYuTAdom5B:1285742052) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a92e8e79ab55cd7daa395126eeb697ef9f901a1/sql/set.go#L143)):*
and SessionOffset?

---

*[sql/pgwire/types.go, line 171 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6183#-KFtWqGDBsKTxhxozqmB:-KFtWqGDBsKTxhxozqmC:1341428203) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a92e8e79ab55cd7daa395126eeb697ef9f901a1/sql/pgwire/types.go#L171)):*
 Much nicer to create a formatTsWithZone(t)?

---

*[sql/pgwire/types_test.go, line 54 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6183#-KFtXTxJwk9cyXr20Gz6:-KFtXTxK09kVwBN-GiVx:-47513741) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3eb09302914d59b63f1a5f57ea50b5e1f528310/sql/pgwire/types_test.go#L54)):*
What is this test doing?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6183)*

**Comment by dt** [comment]
Review status: 0 of 9 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[sql/session.go, line 112 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6183#-KFtU2frvPUKpNRxZw4H:-KFtcb91aZ5pWvbTh3o8:-635461603) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3eb09302914d59b63f1a5f57ea50b5e1f528310/sql/session.go#L112)):*
Done.

`EvalContext`s get created in a few more places so there's still an accessor there that handles `Location` being nil.

---

*[sql/set.go, line 116 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6183#-KFtUgBSkbozRlIWroc4:-KFtY--FCvZa04eyhfKn:-1279927678) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3eb09302914d59b63f1a5f57ea50b5e1f528310/sql/set.go#L116)):*
AFAIK, this change doesn't alter the behavior of _setting the timezone_, it just saves the result when successful so that the same error can't _also happen again) at render time.

---

*[sql/set.go, line 117 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6183#-KFtV1xO9g9wywlT7sxb:-KFtYIQr1xbdsFi-CccC:-815813372) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a92e8e79ab55cd7daa395126eeb697ef9f901a1/sql/set.go#L117)):*
Nope, deleted.

---

*[sql/set.go, line 143 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6183#-KFtVINe0xFYuTAdom5A:-KFtYJJ4vMP8WDR9PWwW:-815813372) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a92e8e79ab55cd7daa395126eeb697ef9f901a1/sql/set.go#L143)):*
Nope, deleted.

---

*[sql/pgwire/types.go, line 171 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6183#-KFtWqGDBsKTxhxozqmB:-KFtYUi3UihG0YIoEUtR:197765701) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a92e8e79ab55cd7daa395126eeb697ef9f901a1/sql/pgwire/types.go#L171)):*
The bulk of `formatTz` is around handling "BC", which would be duplicated if they were totally separate methods... could make a wrapper for it that just passes nil for the no-offset case but not sure that makes a big difference.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6183)*

**Comment by vivekmenezes** [comment]
:lgtm:

---

Review status: 0 of 9 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[sql/pgwire/types.go, line 171 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6183#-KFtWqGDBsKTxhxozqmB:-KFu0ExXCXh2vedrIPwR:640556639) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a92e8e79ab55cd7daa395126eeb697ef9f901a1/sql/pgwire/types.go#L171)):*
I'd prefer the wrapper approach I think because I hate using booleans as function parameters. But it's okay as is, the only problem now is you need to add a /* parameter-name */ comment after each boolean passed in for readability

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6183#-:-KFu13R4d54ahVpZeCK3:1417088721)*

**Comment by dt** [comment]
Review status: 0 of 9 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[sql/pgwire/types.go, line 171 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6183#-KFtWqGDBsKTxhxozqmB:-KFu727uGiPpwAamxRuB:1213668906) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a92e8e79ab55cd7daa395126eeb697ef9f901a1/sql/pgwire/types.go#L171)):*
huh? this removed the bool.

---

*[sql/pgwire/types_test.go, line 54 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6183#-KFtXTxJwk9cyXr20Gz6:-KFtgCq_B85iWoKbLegg:1275977107) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3eb09302914d59b63f1a5f57ea50b5e1f528310/sql/pgwire/types_test.go#L54)):*
This was a test that we can parse the timestamps we send.
since we now (correctly) send two forms of timestamp, I wanted to make sure we can parse both.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6183)*

**Comment by vivekmenezes** [comment]
:lgtm:

---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/pgwire/types.go, line 171 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6183#-KFtWqGDBsKTxhxozqmB:-KFu8yJQiK5_J4b5pDAg:-676098001) ([raw file](https://github.com/cockroachdb/cockroach/blob/6a92e8e79ab55cd7daa395126eeb697ef9f901a1/sql/pgwire/types.go#L171)):*
nevermind :-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6183#-:-KFu9QI3KhuFJVWAJ-EE:1417088721)*

**Pull request merged**
