### PR TITLE
distsql: partial planNode tree wrapping

### PR DESCRIPTION
**Pull request by jordanlewis**
Previously, when DistSQL didn't support a planNode, it would wrap the
entire tree starting from that planNode, leaving potentially
DistSQL-enabled planNodes in that tree to execute via the local
execution pathway.

This commit changes that behavior. When wrapping a planNode, the planner
now searches the planNode tree for all DistSQL-enabled children, resumes
DistSQL planning at those points, and hooks the result up to the wrapped
subtree.

In addition, processors that can be used as sources to mutations now need to optionally be able to read columns that have an active schema change. That information is now plumbed through the system.

Release note: None

### CODE REVIEW

**Review by asubiotto — APPROVED** [review]
Great stuff. @knz, could you take a look at `walk.go` if you have a moment?

> Reviewed 9 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28509#-:-LJp-pKU1Xq0SzHkI2nb:b-qhmh9o)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsql_physical_planner.go, line 2404 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28509#-LJonbUoAJEx0MPEhdw8:-LJonbUoAJEx0MPEhdw9:bz9vcoj) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ac7d47dcbdd085f62ec7246140d9a68bf8636a9/pkg/sql/distsql_physical_planner.go#L2404)):*
> ```Go
> 		},
> 	})
> 	if nParents > 1 {
> ```

Is this ever `> 1`? It seems to me that you return `false` after incrementing the first time which would result in the `planObserver` stopping, right?
___
*[pkg/sql/distsql_physical_planner.go, line 2405 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28509#-LJomzPD7PeCe_f2JDnN:-LJomzPD7PeCe_f2JDnO:b-ge3qgk) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ac7d47dcbdd085f62ec7246140d9a68bf8636a9/pkg/sql/distsql_physical_planner.go#L2405)):*
> ```Go
> 	})
> 	if nParents > 1 {
> 		return PhysicalPlan{}, errors.Errorf("Can't wrap plan %v %T with more than one input", n, n)
> ```

`s/Can't/can't`
___
*[pkg/sql/distsql_physical_planner.go, line 2457 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28509#-LJorV5G1VRCpznQDzxG:-LJorV5G1VRCpznQDzxH:blb5gbs) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ac7d47dcbdd085f62ec7246140d9a68bf8636a9/pkg/sql/distsql_physical_planner.go#L2457)):*
> ```Go
> 	pIdx := p.AddProcessor(proc)
> 	p.ResultTypes = wrapper.outputTypes
> 	p.PlanToStreamColMap = identityMapInPlace(make([]int, len(p.ResultTypes)))
> ```

Please add a comment here, I'm not quite sure what's going on.
___
*[pkg/sql/plan_node_to_row_source.go, line 131 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28509#-LJovO_lBFQQ3mI_hUph:-LJovO_lBFQQ3mI_hUpi:bjoekac) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ac7d47dcbdd085f62ec7246140d9a68bf8636a9/pkg/sql/plan_node_to_row_source.go#L131)):*
> ```Go
> 		p.node.Close(p.params.ctx)
> 		p.running = false
> 		p.started = true
> ```

Why is `p.started` being set here?
___
*[pkg/sql/row_source_to_plan_node.go, line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28509#-LJoy318DgjW2fv0zrD2:-LJoy318DgjW2fv0zrD3:bepuz59) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ac7d47dcbdd085f62ec7246140d9a68bf8636a9/pkg/sql/row_source_to_plan_node.go#L78)):*
> ```Go
> 				return false, p.Err
> 			}
> 			if p.TraceData != nil {
> ```

Should we get rid of this if statement and hit the error below? I think I prefer that to silently skipping over trace data.
___
*[pkg/sql/distsqlrun/flow_diagram.go, line 337 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28509#-LJp-MezAQ7i6idSEQ9u:-LJp-MezAQ7i6idSEQ9v:b-ve3yvb) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ac7d47dcbdd085f62ec7246140d9a68bf8636a9/pkg/sql/distsqlrun/flow_diagram.go#L337)):*
> ```Go
> // summary implements the diagramCellType interface.
> func (r *LocalPlanNodeSpec) summary() (string, []string) {
> 	return fmt.Sprintf("local %s %d", *r.Name, *r.RowSourceIdx), []string{}
> ```

:smile:

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28509)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsql_physical_planner.go, line 2404 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28509#-LJonbUoAJEx0MPEhdw8:-LJpAMJH9cSRJ-i_3mX4:b-kz9ib0) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ac7d47dcbdd085f62ec7246140d9a68bf8636a9/pkg/sql/distsql_physical_planner.go#L2404)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Is this ever `> 1`? It seems to me that you return `false` after incrementing the first time which would result in the `planObserver` stopping, right?
</blockquote></details>

Yeah, it can be greater than one. Returning `false` will prevent further recursion into the current node you're looking at - but the parent of that node could be a node with multiple children.

This error shouldn't ever happen in practice, as all nodes with multiple chilrden (joins) are plannable via distsql.
___
*[pkg/sql/plan_node_to_row_source.go, line 131 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28509#-LJovO_lBFQQ3mI_hUph:-LJpA_iU1uu8-FiFt2Ea:b-losign) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ac7d47dcbdd085f62ec7246140d9a68bf8636a9/pkg/sql/plan_node_to_row_source.go#L131)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why is `p.started` being set here?
</blockquote></details>

If you close this node before it started, it needs to be marked as started so that it doesn't do its startExec initialization, which will read values from its source.
___
*[pkg/sql/row_source_to_plan_node.go, line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28509#-LJoy318DgjW2fv0zrD2:-LJpAhXl0rV4hXgZB4rz:b-x0e049) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ac7d47dcbdd085f62ec7246140d9a68bf8636a9/pkg/sql/row_source_to_plan_node.go#L78)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Should we get rid of this if statement and hit the error below? I think I prefer that to silently skipping over trace data.
</blockquote></details>

Oh yeah we can fix this now that we have the metadata sink. Will do.
___
*[pkg/sql/distsqlrun/flow_diagram.go, line 337 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28509#-LJp-MezAQ7i6idSEQ9u:-LJpAjoi7g2sVQkn74Xs:bt1yrkx) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ac7d47dcbdd085f62ec7246140d9a68bf8636a9/pkg/sql/distsqlrun/flow_diagram.go#L337)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

:smile: 
</blockquote></details>

Yeah! It's still not perfect though - if we wrap more than one node at time, you only get the name of the top node... which leaves out a lot of info.

**Review by jordanlewis — COMMENTED** [review]
Had to rebase this on top of #28551, since nodes potentially expect that the TableReader returns non-public columns now.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28509#-:-LJpgu5jCd1vcwZWAY6K:b-yzx3rj)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsql_physical_planner.go, line 2405 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28509#-LJomzPD7PeCe_f2JDnN:-LJpgidW7i_Hvh57Pcg5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ac7d47dcbdd085f62ec7246140d9a68bf8636a9/pkg/sql/distsql_physical_planner.go#L2405)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

`s/Can't/can't`
</blockquote></details>

Done.
___
*[pkg/sql/distsql_physical_planner.go, line 2457 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28509#-LJorV5G1VRCpznQDzxG:-LJpghaA9DzM6BukWDaW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ac7d47dcbdd085f62ec7246140d9a68bf8636a9/pkg/sql/distsql_physical_planner.go#L2457)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Please add a comment here, I'm not quite sure what's going on.
</blockquote></details>

Done.
___
*[pkg/sql/row_source_to_plan_node.go, line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28509#-LJoy318DgjW2fv0zrD2:-LJpgqlfAFeKUoXS12nG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ac7d47dcbdd085f62ec7246140d9a68bf8636a9/pkg/sql/row_source_to_plan_node.go#L78)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Oh yeah we can fix this now that we have the metadata sink. Will do.
</blockquote></details>

Done.

**Review by knz — CHANGES_REQUESTED** [review]
so yeah the walk thing doesn't work well for me. I have made a suggestion for an alternative see below.

> Reviewed 2 of 6 files at r1, 12 of 13 files at r3, 10 of 10 files at r4, 10 of 10 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28509#-:-LJrxvyC3NiGMzEX3z02:bq1t504)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsql_physical_planner.go, line 807 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28509#-LJrvdaL5L40b5J5UA3Q:-LJrvdaL5L40b5J5UA3R:byjh9fr) ([raw file](https://github.com/cockroachdb/cockroach/blob/45aa9b9f5b63c80410804bee748a38b63db58728/pkg/sql/distsql_physical_planner.go#L807)):*
> ```Go
> 	n *scanNode, evalCtx *tree.EvalContext, indexVarMap []int,
> ) (distsqlrun.TableReaderSpec, distsqlrun.PostProcessSpec, error) {
> 	var visibility distsqlrun.ScanVisibility
> ```

This function would benefit from being either split up in sub-function or more extensively commented in-line to provide some human insight about the different things happening and why they are important.

Especially this here.
___
*[pkg/sql/walk.go, line 39 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28509#-LJrwjreDlCEZzFKlasr:-LJrwjreDlCEZzFKlass:b-ccj2v5) ([raw file](https://github.com/cockroachdb/cockroach/blob/111302cde7bedbb2f2480be6d0ab280d218705b1/pkg/sql/walk.go#L39)):*
> ```Go
> 	// stop the recursion, and isn't invoked on planNodes that are stored in
> 	// their parents as concrete types.
> 	replaceNode func(ctx context.Context, nodeName string, plan *planNode) (bool, error)
> ```

```go
replaceNode func(ctx context.Context, nodeName string, plan planNode) (recurse bool, newPlan planNode, err  error)
```

Also if I'm reading the rest of this patch right, the `recurse` bool is never used so perhaps you can remove it.
___
*[pkg/sql/walk.go, line 79 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28509#-LJrxbzQ2aNQ9jnNvcCT:-LJrxbzQ2aNQ9jnNvcCU:b-wvvdq7) ([raw file](https://github.com/cockroachdb/cockroach/blob/111302cde7bedbb2f2480be6d0ab280d218705b1/pkg/sql/walk.go#L79)):*
> ```Go
> 
> // visit is the recursive function that supports walkPlan().
> func (v *planVisitor) visit(planPtr *planNode) {
> ```

`visit(plan planNode)`
___
*[pkg/sql/walk.go, line 88 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28509#-LJrwvV_A_3Y0kt0X-en:-LJrwvV_A_3Y0kt0X-eo:b-3w6i4l) ([raw file](https://github.com/cockroachdb/cockroach/blob/111302cde7bedbb2f2480be6d0ab280d218705b1/pkg/sql/walk.go#L88)):*
> ```Go
> 	recurse := true
> 	if v.observer.replaceNode != nil {
> 		recurse, v.err = v.observer.replaceNode(v.ctx, name, planPtr)
> ```

```go
recurse, newPlan, err := v.observer.replaceNode(plan)
if err != nil {
    v.err = err
    return plan
}
v.visitInternal(newPlan, ...)
if v.err != nil {
   return plan
}
return newPlan
```
___
*[pkg/sql/walk.go, line 191 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28509#-LJrxYTL-6yrobnej2gI:-LJrxYTL-6yrobnej2gJ:b-e6d156) ([raw file](https://github.com/cockroachdb/cockroach/blob/111302cde7bedbb2f2480be6d0ab280d218705b1/pkg/sql/walk.go#L191)):*
> ```Go
> 			v.expr(name, "filter", -1, n.filter)
> 		}
> 		v.visit(&n.source.plan)
> ```

`n.source.plan = v.visit(n.source.plan)`

here and below
___
*[pkg/sql/distsqlrun/tablereader.go, line 69 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28509#-LJrvuYQ6S8XU6xvp_vG:-LJrvuYQ6S8XU6xvp_vH:b5jpumn) ([raw file](https://github.com/cockroachdb/cockroach/blob/45aa9b9f5b63c80410804bee748a38b63db58728/pkg/sql/distsqlrun/tablereader.go#L69)):*
> ```Go
> 	tr.limitHint = limitHint(spec.LimitHint, post)
> 
> 	numCols := len(spec.Table.Columns)
> ```

ditto comments

**Review by jordanlewis — COMMENTED** [review]
Great suggestion. I took it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28509#-:-LJu7a1e3G1sMeWjjPid:bmnb19b)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsql_physical_planner.go, line 807 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28509#-LJrvdaL5L40b5J5UA3Q:-LJu9VniDcdJtP2De87e:b-xi8ky8) ([raw file](https://github.com/cockroachdb/cockroach/blob/45aa9b9f5b63c80410804bee748a38b63db58728/pkg/sql/distsql_physical_planner.go#L807)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This function would benefit from being either split up in sub-function or more extensively commented in-line to provide some human insight about the different things happening and why they are important.

Especially this here.
</blockquote></details>

Moved this elsewhere.
___
*[pkg/sql/row_source_to_plan_node.go, line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28509#-LJoy318DgjW2fv0zrD2:-LJqVqYwEaiXyphY1Bby:b8seui6) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ac7d47dcbdd085f62ec7246140d9a68bf8636a9/pkg/sql/row_source_to_plan_node.go#L78)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Er, actually, we need this because of the Distinct local implementation. Once that's erased, we can erase this too. This doesn't swallow tracing data in normal wrapping operaiton.
___
*[pkg/sql/walk.go, line 39 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28509#-LJrwjreDlCEZzFKlasr:-LJu7YeR0d3CB8Qt_DZf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/111302cde7bedbb2f2480be6d0ab280d218705b1/pkg/sql/walk.go#L39)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

```go
replaceNode func(ctx context.Context, nodeName string, plan planNode) (recurse bool, newPlan planNode, err  error)
```

Also if I'm reading the rest of this patch right, the `recurse` bool is never used so perhaps you can remove it.

</blockquote></details>

Done.
___
*[pkg/sql/walk.go, line 79 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28509#-LJrxbzQ2aNQ9jnNvcCT:-LJu7Z8oAVmkU6dtfiHv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/111302cde7bedbb2f2480be6d0ab280d218705b1/pkg/sql/walk.go#L79)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`visit(plan planNode)`
</blockquote></details>

Done.
___
*[pkg/sql/walk.go, line 88 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28509#-LJrwvV_A_3Y0kt0X-en:-LJu7VEt11To9GsYoV8_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/111302cde7bedbb2f2480be6d0ab280d218705b1/pkg/sql/walk.go#L88)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

```go
recurse, newPlan, err := v.observer.replaceNode(plan)
if err != nil {
    v.err = err
    return plan
}
v.visitInternal(newPlan, ...)
if v.err != nil {
   return plan
}
return newPlan
```

</blockquote></details>

Done.
___
*[pkg/sql/walk.go, line 191 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/28509#-LJrxYTL-6yrobnej2gI:-LJu7Uu57I23A2LEzCCn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/111302cde7bedbb2f2480be6d0ab280d218705b1/pkg/sql/walk.go#L191)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`n.source.plan = v.visit(n.source.plan)`

here and below

</blockquote></details>

Done.

**Comment by jordanlewis** [comment]
PTAL.
@solongordon, turns out index_join needed to understand about mutation columns too, so I plumbed that through.

**Review by knz — APPROVED** [review]
:lgtm: for what I reviewed earlier. thanks

> Reviewed 5 of 17 files at r6, 1 of 2 files at r7, 10 of 10 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28509#-:-LJxu19bAYviZ88Ag-4E:b-8j9y69)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/walk.go, line 92 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/28509#-LJxtX8MC0Y38ajnfAgj:-LJxtX8N-ja91SA12uv-:b66xz8f) ([raw file](https://github.com/cockroachdb/cockroach/blob/d21dc6bebf214dd35d2f86d11e1ea927d593e01f/pkg/sql/walk.go#L92)):*
> ```Go
> 		if newNode != nil {
> 			return newNode
> 		}
> ```

In your first version you were recursing into the new node. Now you aren't. Is that intentional?

**Review by solongordon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28509)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/processors.proto, line 279 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/28509#-LJyBSIQ7wptQ9Niu_yM:-LJyBSIQ7wptQ9Niu_yN:b9ufo28) ([raw file](https://github.com/cockroachdb/cockroach/blob/d21dc6bebf214dd35d2f86d11e1ea927d593e01f/pkg/sql/distsqlrun/processors.proto#L279)):*
> ```protobuf
>   optional sqlbase.JoinType type = 6 [(gogoproto.nullable) = false];
> 
>   optional ScanVisibility visibility = 7 [(gogoproto.nullable) = false];
> ```

Feels a little funny that this new field is ignored by joinReader. Would it be worth adding an assertion in `newJoinReader` that this is `PUBLIC`?

**Review by solongordon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28509)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/sqlbase/structured.go, line 1818 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/28509#-LJyK5kl3vsEkApkX_0F:-LJyK5kl3vsEkApkX_0G:b-ggt16a) ([raw file](https://github.com/cockroachdb/cockroach/blob/d21dc6bebf214dd35d2f86d11e1ea927d593e01f/pkg/sql/sqlbase/structured.go#L1818)):*
> ```Go
> // ColumnIdxMap returns a map from Column ID to the ordinal position of that
> // column.
> func (desc *TableDescriptor) ColumnIdxMap() map[ColumnID]int {
> ```

Minor: Could just call `ColumnIdxMapWithMutations(false)` to avoid redundant code. Or just make this function take the `mutations` argument and ditch the other.
___
*[pkg/sql/sqlbase/structured.go, line 2126 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/28509#-LJyKPYr9tThjY8EYJNP:-LJyKPYr9tThjY8EYJNQ:b-k04x3o) ([raw file](https://github.com/cockroachdb/cockroach/blob/d21dc6bebf214dd35d2f86d11e1ea927d593e01f/pkg/sql/sqlbase/structured.go#L2126)):*
> ```Go
> 
> // ColumnTypes returns the types of all columns.
> func (desc *TableDescriptor) ColumnTypes() []ColumnType {
> ```

Ditto above.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28509)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/walk.go, line 92 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/28509#-LJxtX8MC0Y38ajnfAgj:-LJyj8xz5-65g9QuBNXY:b-3sg9mc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d21dc6bebf214dd35d2f86d11e1ea927d593e01f/pkg/sql/walk.go#L92)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

In your first version you were recursing into the new node. Now you aren't. Is that intentional?
</blockquote></details>

No, i wasn't recursing into the new node - at least not intentionally. We returned false when changing the node.
___
*[pkg/sql/distsqlrun/processors.proto, line 279 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/28509#-LJyBSIQ7wptQ9Niu_yM:-LJyj7exAar7ECUGvfJ5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d21dc6bebf214dd35d2f86d11e1ea927d593e01f/pkg/sql/distsqlrun/processors.proto#L279)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Feels a little funny that this new field is ignored by joinReader. Would it be worth adding an assertion in `newJoinReader` that this is `PUBLIC`?
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/structured.go, line 2126 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/28509#-LJyKPYr9tThjY8EYJNP:-LJyjHz630TZqy3f1q7s:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d21dc6bebf214dd35d2f86d11e1ea927d593e01f/pkg/sql/sqlbase/structured.go#L2126)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Ditto above.
</blockquote></details>

Done.

**Comment by jordanlewis** [comment]
TFTRs!

bors r+

**Comment by jordanlewis** [comment]
Flake

bors r+

**Pull request merged**
