### PR TITLE
release-2.0: builder: upgrade to go1.10.7

### LINKED ISSUE #33169: build: Update to Go 1.10.6
The newly released go 1.10.6 has a fix for quadratic behavior in certificate validation. This is a potential DoS vector for CRDB clusters exposed to hostile networks. We should use this version of go in our next patch releases.

### PR DESCRIPTION
**Pull request by petermattis**
Backport 1/1 commits from #33178.

/cc @cockroachdb/release

---

Fixes #33169

Release note: None

### CODE REVIEW

**Review by bdarnell — APPROVED** [review]
This is a new builder image built from the 2.0 branch, not just the same one in the other PRs, right?

**Comment by petermattis** [comment]
Hmm, no, this is the same builder image from the other PRs. I was thinking that would be ok. Clearly it isn't.

**Comment by petermattis** [comment]
Hmm, `build/builder.sh init` is failing on one of the first steps:

```
Sending build context to Docker daemon  17.41kB
Step 1/25 : FROM ubuntu:xenial-20170915
 ---> 2d696327ab2e
Step 2/25 : RUN apt-get update && apt-get install -y --no-install-recommends     apt-transport-https     autoconf     bison     bzip2     ca-certificates     curl     file     flex     g++     gawk     git     gperf     help2man     libncurses-dev     make     patch     texinfo     xz-utils  && apt-get clean
 ---> Using cache
 ---> b70dd883de25
Step 3/25 : RUN mkdir crosstool-ng  && curl -fsSL http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-1.23.0.tar.xz | tar --strip-components=1 -C crosstool-ng -xJ  && cd crosstool-ng  && ./configure --prefix /usr/local/ct-ng  && make -j$(nproc)  && make install  && cp ct-ng.comp /etc/bash_completion.d/  && cd ..  && rm -rf crosstool-ng
 ---> Using cache
 ---> 6692ac787037
Step 4/25 : COPY x86_64-unknown-linux-gnu.defconfig x86_64-unknown-linux-musl.defconfig x86_64-w64-mingw.defconfig aarch64-unknown-linux-gnueabi.defconfig ./
COPY failed: stat /var/lib/docker/tmp/docker-builder923194406/aarch64-unknown-linux-gnueabi.defconfig: no such file or directory
```

**Comment by petermattis** [comment]
Turns out I have no idea what is going on here. Should we leave 2.0 on go1.10?

**Comment by bdarnell** [comment]
Yeah, I'm OK with leaving 2.0 as-is instead of debugging this.

**Pull request closed without merging**
