### PR TITLE
sql: add unimplemented errors for trigrams

### LINKED ISSUE #51137: sql: add unimplemented errors for trigram indexes and functions
Similarity
```SQL
root@127.0.0.1:60727/movr> SELECT similarity('word', 'two words');
ERROR: unknown function: similarity()
SQLSTATE: 42883
```
Using show_trgm() function:
```SQL
#
root@127.0.0.1:60727/movr> SELECT show_trgm('hello');
ERROR: unknown function: show_trgm()
SQLSTATE: 42883
```
Word_similarity
```SQL
root@127.0.0.1:60727/movr> SELECT word_similarity('word', 'two words');
ERROR: unknown function: word_similarity()
SQLSTATE: 42883
```
Strict_world_similarity
```SQL
root@127.0.0.1:60727/movr> SELECT strict_word_similarity('word', 'two words');
ERROR: unknown function: strict_word_similarity()
SQLSTATE: 42883
```

Creating an index:
```SQL
root@127.0.0.1:60727/movr> CREATE INDEX CONCURRENTLY index_vehicles_on_vehicle_name_trigram
ON vehicles
USING gin (ext gin_trgm_ops);
invalid syntax: statement ignored: at or near "gin_trgm_ops": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
CREATE INDEX CONCURRENTLY index_vehicles_on_vehicle_name_trigram
ON vehicles
USING gin (ext gin_trgm_ops)
               ^
HINT: try \h CREATE INDEX
```
or
```
root@127.0.0.1:60727/movr> CREATE INDEX trgm_idx ON test_trgm USING GIST (t gist_trgm_ops);
invalid syntax: statement ignored: at or near "gist": syntax error: unimplemented: this syntax
SQLSTATE: 0A000
DETAIL: source SQL:
CREATE INDEX trgm_idx ON test_trgm USING GIST (t gist_trgm_ops)
                                         ^
HINT: You have attempted to use a feature that is not yet implemented.

Please check the public issue tracker to check whether this problem is
already tracked. If you cannot find it there, please report the error
with details by creating a new issue.

If you would rather not post publicly, please contact us directly
using the support form.

We appreciate your feedback.
```
We also need:
```SQL
show_limit()
set_limit(real)
```
https://www.postgresql.org/docs/12/pgtrgm.html

Relates to https://github.com/cockroachdb/cockroach/issues/41285

### PR DESCRIPTION
**Pull request by otan**
Resolves #51137 

**sql: add unimplemented errors for index with operator classes**

* Amend lexing to do lookahead for NULLS FIRST / NULLS LAST to avoid
  shift/reduce conflicts.
* Amend index_params support to be Postgre-compatible. Doing a_exprs
  inside indexes now require surrounding braces.
* Add operator_class argument to index_params.
* Add unimplemented error for operator class support.

Release note: None

**builtins: add unimplemented notices around trigram builtins**

Release note: None

### CODE REVIEW

**Review by solongordon — APPROVED** [review]
> Amend index_params support to be Postgre-compatible. Doing a_exprs inside indexes now require surrounding braces.

This only affects unsupported syntax, right?

**Comment by otan** [comment]
yep!

TFTR!

bors r=solongordon

**Comment by arulajmani** [comment]
You're merging PRs too fast here mate 😂

**Comment by otan** [comment]
push push push push

**Comment by otan** [comment]
bors r=solongordon

:D

**Pull request merged**
