### PR TITLE
roachtest: add SQLAlchemy roachtest

### LINKED ISSUE #41296: sql: create blacklist for sqlalchemy tests
Add a blacklist for the sqlalchemy tests so they can be included in the aggregation added in #41252.

### PR DESCRIPTION
**Pull request by solongordon**
I added a roachtest which runs the SQLAlchemy dialect test suite and
checks the results against a blacklist.

Fixex #40716
Fixes #41296

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41614)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany and @solongordon)

___
*[pkg/cmd/roachtest/sqlalchemy.go, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41614#-LrFaF-GEQkGRrpL1dKD:-LrFaF-HDoHgeOBjSxqP:b-oi4b2d) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb3a45cac5d3b935462c788aef60e862a946f519/pkg/cmd/roachtest/sqlalchemy.go#L22)):*
> ```Go
> )
> 
> var sqlalchemyResultRegex = regexp.MustCompile(`^(?P<test>test.*::.*::[^ ]*) (?P<result>.*)$`)
> ```

[nit]: I'd `s/sqlalchemy/sqlAlchemy/g`
___
*[pkg/cmd/roachtest/sqlalchemy.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41614#-LrFaNO81lryTkBRUZp9:-LrFaNO81lryTkBRUZpA:b8odrc1) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb3a45cac5d3b935462c788aef60e862a946f519/pkg/cmd/roachtest/sqlalchemy.go#L28)):*
> ```Go
> // node.
> 
> func registerSqlalchemy(r *testRegistry) {
> ```

[nit]: `s/Sqlalchemy/SQLAlchemy/g` (and throughout the file).
___
*[pkg/cmd/roachtest/sqlalchemy.go, line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41614#-LrFapSn4Milj0hOMTg1:-LrFapSn4Milj0hOMTg2:b7zn6x) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb3a45cac5d3b935462c788aef60e862a946f519/pkg/cmd/roachtest/sqlalchemy.go#L126)):*
> ```Go
> 		}
> 
> 		version, err := fetchCockroachVersion(ctx, c, node[0])
> ```

Rafi suggested adding this code snippet:
```
		version, err := fetchCockroachVersion(ctx, c, node[0])
		if err != nil {
			t.Fatal(err)
		}

		if err := alterZoneConfigAndClusterSettings(ctx, version, c, node[0]); err != nil {
			t.Fatal(err)
		}
```
right after `c.Start` in the beginning of the test.
___
*[pkg/cmd/roachtest/sqlalchemy.go, line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41614#-LrFbBznB0fm2DYEjbMh:-LrFbBznB0fm2DYEjbMi:bt5rirp) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb3a45cac5d3b935462c788aef60e862a946f519/pkg/cmd/roachtest/sqlalchemy.go#L142)):*
> ```Go
> 		rawResults, _ := c.RunWithBuffer(ctx, t.l, node,
> 			`cd /mnt/data1/sqlalchemy/ && pytest -s --maxfail=0 `+
> 				`--dburi=cockroachdb://root@localhost:26257/defaultdb?sslmode=disable `+
> ```

[super nit]: the indentation seems to be slightly off.
___
*[pkg/cmd/roachtest/sqlalchemy.go, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41614#-LrFbLqm7n3KXqxQhVUO:-LrFbLqm7n3KXqxQhVUP:b-13nwps) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb3a45cac5d3b935462c788aef60e862a946f519/pkg/cmd/roachtest/sqlalchemy.go#L151)):*
> ```Go
> 		results := newORMTestsResults()
> 
> 		scanner := bufio.NewScanner(bytes.NewReader(rawResults))
> ```

I think Rohan extracted this parsing code into a function in his django roachtest PR. It probably makes sense to wait for that to go in and reuse the function.

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41614)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany and @solongordon)

___
*[pkg/cmd/roachtest/sqlalchemy_blacklist.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41614#-LrFzU872J5hZVoGg9gJ:-LrFzU8843HhdBA8VhYR:b-cagfbx) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb3a45cac5d3b935462c788aef60e862a946f519/pkg/cmd/roachtest/sqlalchemy_blacklist.go#L72)):*
> ```Go
> 	"test/dialect/test_suite.py::HasTableTest_cockroachdb+psycopg2_9_5_0::test_has_table_schema":                              "26443",
> 	"test/dialect/test_suite.py::LastrowidTest_cockroachdb+psycopg2_9_5_0::test_autoincrement_on_insert":                      "expects SERIAL to start at 1",
> 	"test/dialect/test_suite.py::ReturningTest_cockroachdb+psycopg2_9_5_0::test_autoincrement_on_insert_implicit_returning":   "expects SERIAL to start at 1",
> ```

i think a github issue should be made for this and referenced here
___
*[pkg/cmd/roachtest/sqlalchemy_blacklist.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41614#-LrFylSsCaLI3QaWNTP-:-LrFylSt1alL636u3IP0:bz0msp6) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb3a45cac5d3b935462c788aef60e862a946f519/pkg/cmd/roachtest/sqlalchemy_blacklist.go#L73)):*
> ```Go
> 	"test/dialect/test_suite.py::LastrowidTest_cockroachdb+psycopg2_9_5_0::test_autoincrement_on_insert":                      "expects SERIAL to start at 1",
> 	"test/dialect/test_suite.py::ReturningTest_cockroachdb+psycopg2_9_5_0::test_autoincrement_on_insert_implicit_returning":   "expects SERIAL to start at 1",
> 	"test/dialect/test_suite.py::ServerSideCursorsTest_cockroachdb+psycopg2_9_5_0::test_aliases_and_ss":                       "unknown",
> ```

do we have any idea what the unknown reasons could be?

**Review by solongordon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41614)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss, @rohany, and @yuzefovich)

___
*[pkg/cmd/roachtest/sqlalchemy.go, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41614#-LrFaF-GEQkGRrpL1dKD:-LrKJHUl7uGdYpP7laAi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb3a45cac5d3b935462c788aef60e862a946f519/pkg/cmd/roachtest/sqlalchemy.go#L22)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: I'd `s/sqlalchemy/sqlAlchemy/g`
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/sqlalchemy.go, line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41614#-LrFaNO81lryTkBRUZp9:-LrKJIIjBMBN6Ygt1Yej:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb3a45cac5d3b935462c788aef60e862a946f519/pkg/cmd/roachtest/sqlalchemy.go#L28)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: `s/Sqlalchemy/SQLAlchemy/g` (and throughout the file).
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/sqlalchemy.go, line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41614#-LrFapSn4Milj0hOMTg1:-LrKJg7v9ledfmHo8PP0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb3a45cac5d3b935462c788aef60e862a946f519/pkg/cmd/roachtest/sqlalchemy.go#L126)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Rafi suggested adding this code snippet:
```
		version, err := fetchCockroachVersion(ctx, c, node[0])
		if err != nil {
			t.Fatal(err)
		}

		if err := alterZoneConfigAndClusterSettings(ctx, version, c, node[0]); err != nil {
			t.Fatal(err)
		}
```
right after `c.Start` in the beginning of the test.
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/sqlalchemy.go, line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41614#-LrFbBznB0fm2DYEjbMh:-LrKJr8k0Id85DKJQ2Te:b-be8b5f) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb3a45cac5d3b935462c788aef60e862a946f519/pkg/cmd/roachtest/sqlalchemy.go#L142)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[super nit]: the indentation seems to be slightly off.
</blockquote></details>

This is what crlfmt wants for whatever reason.
___
*[pkg/cmd/roachtest/sqlalchemy.go, line 151 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41614#-LrFbLqm7n3KXqxQhVUO:-LrKKZAe7rRk-cFxe677:bvfcysj) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb3a45cac5d3b935462c788aef60e862a946f519/pkg/cmd/roachtest/sqlalchemy.go#L151)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think Rohan extracted this parsing code into a function in his django roachtest PR. It probably makes sense to wait for that to go in and reuse the function.
</blockquote></details>

Good idea though it seems like it doesn't work in this case because these unit tests use pytest, which as a different output format.
___
*[pkg/cmd/roachtest/sqlalchemy_blacklist.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41614#-LrFzU872J5hZVoGg9gJ:-LrQ03Ev5sWoJzNWysck:bz1a36h) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb3a45cac5d3b935462c788aef60e862a946f519/pkg/cmd/roachtest/sqlalchemy_blacklist.go#L72)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think a github issue should be made for this and referenced here
</blockquote></details>

I'm not sure we really need one because this is just a deficiency in the test, not in SQLAlchemy proper or Cockroach. Does that make sense? I also moved these to the ignore list since we never really expect them to pass unless the test changes.
___
*[pkg/cmd/roachtest/sqlalchemy_blacklist.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41614#-LrFylSsCaLI3QaWNTP-:-LrPzcWy9izIqGJowMkk:bklj9uv) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb3a45cac5d3b935462c788aef60e862a946f519/pkg/cmd/roachtest/sqlalchemy_blacklist.go#L73)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

do we have any idea what the unknown reasons could be?
</blockquote></details>

The unknown has become known. I dug into this more and figured out there was a minor bug on the `cockroach-python` side which was making this fail with a mysterious error. Now that I fixed it, the tests still fail but with a reasonable error. Updated to reference the relevant Github issue.

**Review by solongordon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41614)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss, @rohany, and @yuzefovich)

___
*[pkg/cmd/roachtest/sqlalchemy_blacklist.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41614#-LrFzU872J5hZVoGg9gJ:-LrQ27R_13Olq7Bl1HO4:b-za2oi2) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb3a45cac5d3b935462c788aef60e862a946f519/pkg/cmd/roachtest/sqlalchemy_blacklist.go#L72)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

I'm not sure we really need one because this is just a deficiency in the test, not in SQLAlchemy proper or Cockroach. Does that make sense? I also moved these to the ignore list since we never really expect them to pass unless the test changes.
</blockquote></details>

Oh, Rohan pointed out we have the test issue catch-all ticket now so I just pointed to that.

**Review by rafiss — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41614)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss, @rohany, and @yuzefovich)

**Pull request merged**
