### PR TITLE
distsql: reduce allocations in setupFlow 

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### go.mod: bump cockroachdb/logtags

Incorporate https://github.com/cockroachdb/logtags/pull/5

Epic: none
Release note: None

#### distsql: reduce allocations in setupFlow

Reduce allocations related to adding tags to the ambient context for a
non-local flow.

Informs: #135904
Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
I saw these taking about 0.1% in a recent profile.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137515#-:-OEBcLtc03mKjbTcuJ7n:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @aa-joshi, @arjunmahishi, and @dhartunian)

**Review by mgartner — APPROVED** [review]
Nice!

**Comment by RaduBerinde** [comment]
TFTR!

bors r+

**Pull request merged**
