### PR TITLE
sql: parse and validate out/inout parameter modes in udfs and sps

### PR DESCRIPTION
**Pull request by rharding6373**
sql: parser support for udf argument classes
    
    Adds support to the parser for INOUT, IN OUT, and OUT parameters.

    Also changes CreateRoutine.ReturnType to a pointer, in order to
    distinguish between unspecified RETURNS clauses and RETURNS VOID.
    
    Epic: CRDB-30611
    Informs: #100405
    
    Release note: None

----

    sql: add out/inout udf parameter validation for sql
    
    This commit validates OUT and INOUT parameter types for SQL language
    UDFs.
    
    Epic: CRDB-30611
    Informs: #100405
    
    Release note: None

----

    sql/ccl: add plpgsql testing for out/inout udf param validation
    
    Epic: CRDB-30611
    Informs: #100405
    
    Release note: None

----

    sql: add support for OUT/INOUT stored procedure param validation
    
    Epic: CRDB-30611
    Informs: #100405
    
    Release note: None

### CODE REVIEW

**Review by DrewKimball — COMMENTED** [review]
Looks great! Just some nits on the initial pass.

> Reviewed 9 of 9 files at r1, 33 of 33 files at r2, 3 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117999#-:-NomoiZz8v_nPtekniwZ:b-kqih0c)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117999#-NomWwN37SR8Im4E28Tr):*
Why is this necessary? Isn't there already a `VOID` type we can use? `types.Void`?
___
*[`pkg/sql/opt/optbuilder/create_function.go` line 171 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117999#-Nomaruj6K0mUG5qHOkF:-Nomaruj6K0mUG5qHOkG:b-calb0h) ([raw file](https://github.com/cockroachdb/cockroach/blob/21e23edbe38267c5cdadb90ff132093a8dbe7788/pkg/sql/opt/optbuilder/create_function.go#L171)):*
> ```Go
> 			} else {
> 				if !types.IsRecordType(outParamType) {
> 					outParamType = types.MakeTuple([]*types.T{outParamType, typ})
> ```

[nit] It might be more clear to just append to a slice here, and set the return type based on the length of that slice. Then, most of the logic could happen outside the loop. What do you think?
___
*[`pkg/sql/opt/testutils/testcat/function.go` line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117999#-NomcHje9OhxZdUmYZtW:-NomcHje9OhxZdUmYZtX:bmlp2et) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f8a384c2e0b1228a13724fb99d65e0febaf6d5d/pkg/sql/opt/testutils/testcat/function.go#L16)):*
> ```Go
> 	"context"
> 	"fmt"
> 	"github.com/cockroachdb/cockroach/pkg/sql/types"
> ```

Looks like this file in this commit needs to be formatted.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/udf_params` line 3 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/117999#-NommzBP3R4L39Nn4DzR:-NommzBP3R4L39Nn4DzS:bvwwl0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3c19c0cf0d7c240054ead0418f1728f074ebd26/pkg/ccl/logictestccl/testdata/logic_test/udf_params#L3)):*
> ```
> # LogicTest: !local-mixed-23.1
> 
> subtest types
> ```

We should also have a test where the body assigns to the OUT param.

**Review by DrewKimball — APPROVED** [review]
:lgtm: on second pass. Great work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117999#-:-Non2f2Y7g5F_W00E2Wj:b-98qv40)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rharding6373)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117999#-NomWwN37SR8Im4E28Tr):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Why is this necessary? Isn't there already a `VOID` type we can use? `types.Void`?
</blockquote></details>

Nevermind this, I think it makes sense with the rest of the changes.

**Review by rharding6373 — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117999#-:-NonT_BL-Q2ca5H6bk_v:b-814g8k)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @mgartner)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117999#-NomWwN37SR8Im4E28Tr):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Nevermind this, I think it makes sense with the rest of the changes.
</blockquote></details>

Let me know if this should be more clear. Initially I tried to use types.Unknown instead, but ran into the same issue as with types.Void, which is that you could specify a returns clause with type VOID or type UNKNOWN or have no returns clause at all, and we need to distinguish all these cases.
___
*[`pkg/sql/opt/optbuilder/create_function.go` line 171 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/117999#-Nomaruj6K0mUG5qHOkF:-NompQns5V1FU3-8ABb7:bkoke9u) ([raw file](https://github.com/cockroachdb/cockroach/blob/21e23edbe38267c5cdadb90ff132093a8dbe7788/pkg/sql/opt/optbuilder/create_function.go#L171)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] It might be more clear to just append to a slice here, and set the return type based on the length of that slice. Then, most of the logic could happen outside the loop. What do you think?
</blockquote></details>

I like it. Done.
___
*[`pkg/sql/opt/testutils/testcat/function.go` line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117999#-NomcHje9OhxZdUmYZtW:-NompGvN4SNrxkrsxQXX:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f8a384c2e0b1228a13724fb99d65e0febaf6d5d/pkg/sql/opt/testutils/testcat/function.go#L16)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Looks like this file in this commit needs to be formatted.
</blockquote></details>

Fixed.
___
*[`pkg/ccl/logictestccl/testdata/logic_test/udf_params` line 3 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/117999#-NommzBP3R4L39Nn4DzR:-NonScYo4x6xobfnlDdD:bz3v0fi) ([raw file](https://github.com/cockroachdb/cockroach/blob/a3c19c0cf0d7c240054ead0418f1728f074ebd26/pkg/ccl/logictestccl/testdata/logic_test/udf_params#L3)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

We should also have a test where the body assigns to the OUT param.
</blockquote></details>

Done. Note that this PR doesn't include support for resolving the functions or actually making assignments, so we don't call the functions or test that the assignments are done correctly. But this does test that it parses.

**Comment by rharding6373** [comment]
Thanks again for the review!

bors r+

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 5 of 9 files at r1, 31 of 31 files at r5, 29 of 34 files at r6, 2 of 4 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117999)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[`pkg/sql/opt/optbuilder/create_function.go` line 397 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/117999#-NpXDHx25p4tLQ0SGXjz:-NpXDHx25p4tLQ0SGXk-:b-8sn910) ([raw file](https://github.com/cockroachdb/cockroach/blob/16e8eeb6df9e6a42f28f36fd14940ce6545f27c9/pkg/sql/opt/optbuilder/create_function.go#L397)):*
> ```Go
> 	}
> 
> 	// If return type is RECORD and the tuple content types unspecified by OUT
> ```

@rharding6373 I'm a bit confused by the change to the comment here: `expected` here is `funcReturnType` from the outer context, which can be set both based on the OUT parameters and - in absence of OUT parameters - based on the RETURNS. Do I understand it correctly that `types.AnyTuple` (what this check is really about) cannot be specified by the OUT parameters, so it must be based on the RETURNS?

**Review by rharding6373 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117999)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[`pkg/sql/opt/optbuilder/create_function.go` line 397 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/117999#-NpXDHx25p4tLQ0SGXjz:-NpXnihJ13x0i9aEAVAF:b-6n60f8) ([raw file](https://github.com/cockroachdb/cockroach/blob/16e8eeb6df9e6a42f28f36fd14940ce6545f27c9/pkg/sql/opt/optbuilder/create_function.go#L397)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

@rharding6373 I'm a bit confused by the change to the comment here: `expected` here is `funcReturnType` from the outer context, which can be set both based on the OUT parameters and - in absence of OUT parameters - based on the RETURNS. Do I understand it correctly that `types.AnyTuple` (what this check is really about) cannot be specified by the OUT parameters, so it must be based on the RETURNS?
</blockquote></details>

Yes, you're right, and the comment makes some logical jumps that could probably be better explained. OUT params must have a type specified (as all params do), so if there were OUT params specified it can't be types.AnyTuple. This check is here because if we have only a RETURNS RECORD without OUT params, we don't need to check the types below.

**Pull request merged**
