### PR TITLE
admission: remove `DiskName` from `StoreSpec.ProvisionedRateSpec`

### PR DESCRIPTION
**Pull request by CheranMahalingam**
This commit cleans up changes from #119885. There is no longer a need for users to specify a disk name when specifying the provisioned bandwidth since we can now automatically infer disk names from the `StoreSpec.Path` and the underlying block device.

Informs: #86857.

Epic: None.
Release note (ops change): The provisioned-rate field, if specified, should no longer accept a disk-name or an optional bandwidth field. To use the disk bandwidth constraint the store-spec must contain provisioned-rate=bandwidth=<bandwidth-bytes/s>, otherwise the cluster setting kv.store.admission.provisioned_bandwidth will be used.

### CODE REVIEW

**Review by CheranMahalingam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120895)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained

___
*[`pkg/base/store_spec.go` line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120895#-Ntaxua_23nklB0VEDTs:-Ntaxua_23nklB0VEDTt:b-cg2piw) ([raw file](https://github.com/cockroachdb/cockroach/blob/06733b748fac3dc0929cae829358325b764a4449/pkg/base/store_spec.go#L167)):*
> ```Go
> type ProvisionedRateSpec struct {
> 	// ProvisionedBandwidth is the bandwidth provisioned for this store in bytes/s.
> 	ProvisionedBandwidth int64
> ```

Optionally, the `ProvisionedBandwidth` could be moved out of this struct since it is now the only field. I have left it as is because I am unsure of whether AC will ever extend this struct to include additional options (i.e. read or write bandwidth).
___
*[`pkg/base/store_spec.go` line 309 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120895#-NtayTV8BIWIWJGO8wSo:-NtayTV8BIWIWJGO8wSp:bgpxodt) ([raw file](https://github.com/cockroachdb/cockroach/blob/06733b748fac3dc0929cae829358325b764a4449/pkg/base/store_spec.go#L309)):*
> ```Go
> //   - 0.2             -> 20% of the available space
> //   - attrs=xxx:yyy:zzz A colon separated list of optional attributes.
> //   - provisioned-rate=<bandwidth-bytes/s> The provisioned-rate can be used for
> ```

Optionally, it makes sense to rename `provisioned-rate` to `provisioned-bandwidth` but I have left it as is to avoid confusion for any users that already use `provisioned-rate`.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120895)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi and @CheranMahalingam)

___
*[`pkg/base/store_spec.go` line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120895#-Ntaxua_23nklB0VEDTs:-NtqsAAI3B1FRNUgkogP:b-broq57) ([raw file](https://github.com/cockroachdb/cockroach/blob/06733b748fac3dc0929cae829358325b764a4449/pkg/base/store_spec.go#L167)):*
<details><summary><i>Previously, CheranMahalingam wrote…</i></summary><blockquote>

Optionally, the `ProvisionedBandwidth` could be moved out of this struct since it is now the only field. I have left it as is because I am unsure of whether AC will ever extend this struct to include additional options (i.e. read or write bandwidth).
</blockquote></details>

struct is fine for now. We'll probably extend it to include IOPS in the future. In that sense "rate" (in `ProvisionedRateSpec`)  is also an ok-ish term since it doesn't specify whether the rate is bandwidth or IOPS or ...
___
*[`pkg/base/store_spec.go` line 309 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/120895#-NtayTV8BIWIWJGO8wSo:-NtqrvNSDU3zyskjPSN4:btjgobd) ([raw file](https://github.com/cockroachdb/cockroach/blob/06733b748fac3dc0929cae829358325b764a4449/pkg/base/store_spec.go#L309)):*
<details><summary><i>Previously, CheranMahalingam wrote…</i></summary><blockquote>

Optionally, it makes sense to rename `provisioned-rate` to `provisioned-bandwidth` but I have left it as is to avoid confusion for any users that already use `provisioned-rate`.
</blockquote></details>

Let's make this `"provisioned-rate=bandwidth=<bandwidth-bytes/s>`
___
*[`pkg/base/store_spec.go` line 309 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120895#-NtqDYA72hT6aOjBLajF:-NtqDYA72hT6aOjBLajG:b65ev4m) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7f7e03d322017b40735ae02064629a5031c34df/pkg/base/store_spec.go#L309)):*
> ```Go
> //   - 0.2             -> 20% of the available space
> //   - attrs=xxx:yyy:zzz A colon separated list of optional attributes.
> //   - provisioned-rate=<bandwidth-bytes/s> The provisioned-rate can be used for
> ```

since we've made it easier to configure disk bandwidth tokens for AC, we've also made it easier to accidentally turn it on. Can you add a comment in https://github.com/cockroachdb/cockroach/blob/d0c33174dbcc334fe3fb3b20b1a2ad276cf74da2/pkg/kv/kvserver/kvadmission/kvadmission.go#L99-L106 that setting `kvadmission.store.provisioned_bandwidth` to a positive value will enable disk bandwidth based admission control, since `admission.disk_bandwidth_tokens.elastic.enabled` defaults to true.

**Review by CheranMahalingam — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120895#-:-NtrEd2V8c-03OhFJijX:b-814g8k)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi and @sumeerbhola)

___
*[`pkg/base/store_spec.go` line 309 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/120895#-NtqDYA72hT6aOjBLajF:-NtrEbAi7iZeHBe9aLeF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7f7e03d322017b40735ae02064629a5031c34df/pkg/base/store_spec.go#L309)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

since we've made it easier to configure disk bandwidth tokens for AC, we've also made it easier to accidentally turn it on. Can you add a comment in https://github.com/cockroachdb/cockroach/blob/d0c33174dbcc334fe3fb3b20b1a2ad276cf74da2/pkg/kv/kvserver/kvadmission/kvadmission.go#L99-L106 that setting `kvadmission.store.provisioned_bandwidth` to a positive value will enable disk bandwidth based admission control, since `admission.disk_bandwidth_tokens.elastic.enabled` defaults to true.
</blockquote></details>

Done.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/120895#-:-NtsTdiVA9qe6PkP1B50:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi)

**Comment by CheranMahalingam** [comment]
bors r=sumeerbhola

**Pull request merged**
