### PR TITLE
*: bump some core dependencies

### PR DESCRIPTION
**Pull request by rickystewart**
Unfortunately we're still getting `nogo` crashes. Try bumping these
dependencies even further.

Informs https://github.com/cockroachdb/cockroach/issues/99988.

Epic: none
Release note: None

### CODE REVIEW

**Comment by knz** [comment]
@rickystewart I'll look at those manually, but in the future would it be possible to have the dep generator also list a markdown table that links to the repos with the diff?

Something like:

| Package | Link to Diff |
|---|---|
| golang.org/x/net | auto-generated link to diff between old and new SHA on github |

**Comment by rickystewart** [comment]
Hmm, you mean like as a blathers comment or something? Or where else would this table be.

**Comment by knz** [comment]
yes blathers

**Comment by knz** [comment]
- [x] x/net - OK, nice to pick up the fix for https://github.com/golang/go/issues/58804
- [x] x/crypto - OK, nice to pick up https://github.com/golang/go/issues/57792 for when we want to start using it.
- [x] x/sys - OK
- [x] x/term - OK
- [x] x/sync - OK, nice to pick up https://github.com/golang/go/issues/59355
- [x] x/text - OK
- [x] x/tools - OK, didn't look in details because I'm assuming we don't use this in prod code.

**Review by knz — APPROVED** [review]

**Comment by rickystewart** [comment]
TFTR!

bors r=knz

**Comment by rickystewart** [comment]
blathers backport 23.1

**Pull request merged**
