### PR TITLE
sql: implement IntervalStyle

### LINKED ISSUE #61167: sql: support IntervalStyle session parameter
We should add support for the IntervalStyle session parameter, which describes how an `interval` type is formatted in output.

See official docs here: https://www.postgresql.org/docs/9.4/datatype-datetime.html#INTERVAL-STYLE-OUTPUT-TABLE
See a tutorial here: https://www.postgresqltutorial.com/postgresql-interval/

Epic CRDB-2508

### LINKED ISSUE #65724: sql: Allow session variables to be passed into FmtCtx
This will allow us to implement DateStyle and IntervalStyle session params

Epic CRDB-2508

### PR DESCRIPTION
**Pull request by otan**
See individual commits for details.

This is supremely messy, and I hope one day we clean this up. We do conversions differently for casts, pgwire and JSON. `ctx.Location` and `sessiondatapb.DataConversionConfig` should probably be unified, and be universally applies from the FmtCtx instead of ad-hocly applied throughout the stack (`extra_float_digits` and `bytes_encode_format ` suffers the same problem and is probably incorrect in a few places). I'll file an issue for this after it merges.

Supercedes #62313
Resolves #65724
Resolves #61167

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
my comments are all pretty minor. this is great work navigating the maze!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67000#-:-MdTCRC-8xERsYuju2YQ:b-jr0dto)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/vars.go, line 802 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67000#-MdT8ydu6LEy5kKCXS-y:-MdT8ydu6LEy5kKCXS-z:b-8ux5q5) ([raw file](https://github.com/cockroachdb/cockroach/blob/20a8c1fb4fe52d4df1194c60fdebec9c33c6b0e3/pkg/sql/vars.go#L802)):*
> ```Go
> 
> 	// See https://www.postgresql.org/docs/10/static/runtime-config-client.html#GUC-INTERVALSTYLE
> 	`intervalstyle`: {
> ```

are the session var names case insensitive?
___
*[pkg/sql/sem/tree/casts.go, line 903 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67000#-MdTCEH53axUmXGPNv5o:-MdTCEH53axUmXGPNv5p:b-fi7tds) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5a3eae6a88e0e31cb2174ec9b80d606b0b1166d/pkg/sql/sem/tree/casts.go#L903)):*
> ```Go
> 				FmtDataConversionConfig(ctx.SessionData.DataConversionConfig),
> 			)
> 		case *DInterval:
> ```

i didn't even realize that casts were affected. nice catch
___
*[pkg/sql/sessiondatapb/session_data.proto, line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67000#-MdTBwuz-bvB0gCJBvo6:-MdTBwuz-bvB0gCJBvo7:bkzbm20) ([raw file](https://github.com/cockroachdb/cockroach/blob/20a8c1fb4fe52d4df1194c60fdebec9c33c6b0e3/pkg/sql/sessiondatapb/session_data.proto#L66)):*
> ```protobuf
> 
> // DataConversionConfig contains the parameters that influence the conversion
> // between SQL data types and strings/byte arrays.
> ```

maybe update this comment?
___
*[pkg/sql/sessiondatapb/session_data.proto, line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67000#-MdTBtHU6EMK3kWrnHLg:-MdTBtHU6EMK3kWrnHLh:bb0xvjc) ([raw file](https://github.com/cockroachdb/cockroach/blob/20a8c1fb4fe52d4df1194c60fdebec9c33c6b0e3/pkg/sql/sessiondatapb/session_data.proto#L76)):*
> ```protobuf
>   int32 extra_float_digits = 2;
>   // IntervalStyle indicates the style to display intervals as.
>   util.duration.IntervalStyle interval_style = 13;
> ```

why is it `= 13`?
___
*[pkg/util/duration/duration.go, line 596 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67000#-MdT8ONE6WQhZgmgp3Ew:-MdT8ONOC3Ld777ioHhQ:b-f1oelg) ([raw file](https://github.com/cockroachdb/cockroach/blob/39e9697913b1b21fce7243d8724b97730c9a31aa/pkg/util/duration/duration.go#L596)):*
> ```Go
> }
> 
> // extractAbsTime returns signed amount of hours, minutes, seconds,
> ```

nit: comment is for extractTime
___
*[pkg/util/duration/duration.proto, line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67000#-MdT8dwX8GsY6O1uK7PB:-MdT8dwX8GsY6O1uK7PC:b-odjv88) ([raw file](https://github.com/cockroachdb/cockroach/blob/39e9697913b1b21fce7243d8724b97730c9a31aa/pkg/util/duration/duration.proto#L16)):*
> ```protobuf
> 
> // IntervalStyle matches the PostgreSQL IntervalStyle session parameter.
> enum IntervalStyle {
> ```

dumb Q: why did we want this in a proto?
___
*[pkg/util/duration/duration_test.go, line 605 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67000#-MdTADhr11DruCQ6_sdk:-MdTADhr11DruCQ6_sdl:bkqrujq) ([raw file](https://github.com/cockroachdb/cockroach/blob/39e9697913b1b21fce7243d8724b97730c9a31aa/pkg/util/duration/duration_test.go#L605)):*
> ```Go
> }
> 
> func TestFormat(t *testing.T) {
> ```

great test -- is there a way we can confirm that this matches the postgres output?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67000)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mneverov and @rafiss)

___
*[pkg/sql/vars.go, line 802 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67000#-MdT8ydu6LEy5kKCXS-y:-MdU476fACkEAiPdoP7S:bb7s9xe) ([raw file](https://github.com/cockroachdb/cockroach/blob/20a8c1fb4fe52d4df1194c60fdebec9c33c6b0e3/pkg/sql/vars.go#L802)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

are the session var names case insensitive?
</blockquote></details>

yep!
___
*[pkg/sql/sem/tree/casts.go, line 903 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/67000#-MdTCEH53axUmXGPNv5o:-MdU48eu4mzDt1BSLIhk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5a3eae6a88e0e31cb2174ec9b80d606b0b1166d/pkg/sql/sem/tree/casts.go#L903)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i didn't even realize that casts were affected. nice catch
</blockquote></details>

Done.
___
*[pkg/sql/sessiondatapb/session_data.proto, line 66 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67000#-MdTBwuz-bvB0gCJBvo6:-MdU4Wix4do5zdEUgopB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/20a8c1fb4fe52d4df1194c60fdebec9c33c6b0e3/pkg/sql/sessiondatapb/session_data.proto#L66)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

maybe update this comment?
</blockquote></details>

Done.
___
*[pkg/sql/sessiondatapb/session_data.proto, line 76 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/67000#-MdTBtHU6EMK3kWrnHLg:-MdU4VvY4xjngMRaBtWx:b-7lj86y) ([raw file](https://github.com/cockroachdb/cockroach/blob/20a8c1fb4fe52d4df1194c60fdebec9c33c6b0e3/pkg/sql/sessiondatapb/session_data.proto#L76)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

why is it `= 13`?
</blockquote></details>

oops.
___
*[pkg/util/duration/duration.proto, line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67000#-MdT8dwX8GsY6O1uK7PB:-MdU4CAnBkmvvev03ylr:bamw0sx) ([raw file](https://github.com/cockroachdb/cockroach/blob/39e9697913b1b21fce7243d8724b97730c9a31aa/pkg/util/duration/duration.proto#L16)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

dumb Q: why did we want this in a proto?
</blockquote></details>

for storing this into the SessionData proto, which can be serialized.
___
*[pkg/util/duration/duration_test.go, line 605 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67000#-MdTADhr11DruCQ6_sdk:-MdU5Sjb4ZLp5z8GgX1U:b-qnte4y) ([raw file](https://github.com/cockroachdb/cockroach/blob/39e9697913b1b21fce7243d8724b97730c9a31aa/pkg/util/duration/duration_test.go#L605)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

great test -- is there a way we can confirm that this matches the postgres output?
</blockquote></details>

credits go to @mneverov for this - i only improved the readability.
i've verified these cases to match, but outside of randomised testing it's hard

**Review by rafiss — APPROVED** [review]
lgtm!

what do you think about writing a CompareTest that is just focused on comparing IntervalStyle? it would mean adding a new test to the `configs` in compare_test.go, then a sqlsmith.SmitherOption that just generates `SELECT interval` and `SET intervalstyle` queries. Can be a later PR or a backlog issue if you think it's a reasonable idea!

bigger priority than that would be to implement DateStyle next: https://github.com/cockroachdb/cockroach/issues/41773 

> Reviewed 4 of 5 files at r1, 31 of 31 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67000#-:-MdZNoAY7j1xYELj-YJ2:btk96sq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mneverov and @rafiss)

**Comment by otan** [comment]
> bigger priority than that would be to implement DateStyle next: #41773

that one is going to be an even bigger PITA ...

> what do you think about writing a CompareTest that is just focused on comparing IntervalStyle? it would mean adding a new test to the configs in compare_test.go, then a sqlsmith.SmitherOption that just generates SELECT interval and SET intervalstyle queries. Can be a later PR or a backlog issue if you think it's a reasonable idea!

i think it's a fine idea. will write an issue.

**Comment by otan** [comment]
bors r=rafiss

**Pull request merged**
