### PR TITLE
rpc: clock offset metrics, narrower offset tolerance

### PR DESCRIPTION
**Pull request by tamird**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10185)

### CODE REVIEW

**Comment by spencerkimball** [comment]
LGTM. I wonder if there's any risk that this will foul up aphyr's tests which might use the configured max offset to play around the boundary. With the 80% threshold, this will definitely result in potentially unexpected node suicides. Something to keep in mind.

+cc @knz

**Comment by knz** [comment]
Yes this will run "afoul" of the test in that it will reduce the number of problems found by the test :)

**Comment by knz** [comment]
LGTM otherwise

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10185#-:-KUswmmymQpNy4xLwqwG:bou78ct)*

**Comment by petermattis** [comment]
This will only help with clocks the skew slowly, right? This won't help if we have a sudden multi-second clock jump, right?

---

Reviewed 3 of 3 files at r1, 2 of 2 files at r2.
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/rpc/clock_offset.go, line 176 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10185#-KUtEdlcPvVr6eGdQ6_e:-KUtEdlcPvVr6eGdQ6_f:b-1p8iwj) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2177081a7b1c1b7b8b571cb392b90c391b40c96/pkg/rpc/clock_offset.go#L176)):*
> ```Go
> 
> func (r RemoteOffset) isHealthy(ctx context.Context, maxOffset time.Duration) bool {
> 	// Tolerate up to 80% of the maximum offset.
> ```

Is the `80%` value inspired by anything? Should this be configurable (at least via an environment variable)? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10185#-:-KUtErT7aRpeLvzTLsB9:b-xxqsmn)*

**Comment by tamird** [comment]
Yes, a determined clock-manipulating adversary won't be thwarted by this change.

cc @aphyr for when this merges.

---

Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/rpc/clock_offset.go, line 176 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10185#-KUtEdlcPvVr6eGdQ6_e:-KUtYaoOObEz5C5EpXg2:b-kz6ywu) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2177081a7b1c1b7b8b571cb392b90c391b40c96/pkg/rpc/clock_offset.go#L176)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Is the `80%` value inspired by anything? Should this be configurable (at least via an environment variable)? 
</details>
Nope, I pulled it straight out of you-know-where. @spencerkimball and I discussed and agreed that make it configurable was overkill, but I can revisit if you feel strongly?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10185#-:-KUtYoSK_j8m7x0JfU03:b-2a99dj)*

**Comment by spencerkimball** [comment]
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/rpc/clock_offset.go, line 176 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10185#-KUtEdlcPvVr6eGdQ6_e:-KUtZpkLvQZKoQnQx0NG:b-55c2dz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2177081a7b1c1b7b8b571cb392b90c391b40c96/pkg/rpc/clock_offset.go#L176)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Nope, I pulled it straight out of you-know-where. @spencerkimball and I discussed and agreed that make it configurable was overkill, but I can revisit if you feel strongly?
</details>
I'm strongly opposed to making this configurable. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10185)*

**Comment by petermattis** [comment]
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/rpc/clock_offset.go, line 176 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10185#-KUtEdlcPvVr6eGdQ6_e:-KUw5WZbDXKnqGUnk-hD:b-4zunr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2177081a7b1c1b7b8b571cb392b90c391b40c96/pkg/rpc/clock_offset.go#L176)):*
<details><summary><i>Previously, spencerkimball (Spencer Kimball) wrote…</i></summary>
> I'm strongly opposed to making this configurable. 
</details>
I don't particularly care about making this configurable. I am worried that this isn't going go help much. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10185)*

**Comment by mberhault** [comment]
LGTM. Just add a todo mentioning that we can switch to histograms/summaries if mean/stddev are not enough.

---

Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10185#-:-KUwSFSvdr169nazVQwp:b-82asl9)*

**Comment by tamird** [comment]
Meh, I'm going to leave the TODO out for now; it's not like that idea won't be obvious when the need arises.

---

Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/rpc/clock_offset.go, line 176 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10185#-KUtEdlcPvVr6eGdQ6_e:-KUwTnldCd6mgbJFQaXD:b31w0bm) ([raw file](https://github.com/cockroachdb/cockroach/blob/a2177081a7b1c1b7b8b571cb392b90c391b40c96/pkg/rpc/clock_offset.go#L176)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I don't particularly care about making this configurable. I am worried that this isn't going go help much. 
</details>
I think it's going to help plenty when clocks skew slowly (which is the typical case). That it won't help against a determined adversary like jepsen is a different story, but we should be considering realistic scenarios as well as adversarial tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10185#-:-KUwThkPKn0lB-0laDwv:b-1y0vvr)*

**Pull request merged**
