### PR TITLE
sql: introduce box2d type

### PR DESCRIPTION
**Pull request by otan**
Representation: box2d reuses the CartesianBoundingBox struct we already
have in the geo package, which has the necessary primitives.

Encoding: box2d is encoded as LoX, HiX, LoY, HiY, similar to empirical
experiments with PostGIS.

Parsing/Display: box2d is parsed strictly as `BOX(%f %f,%f %f)`.

Release note (sql change): Introduce the box2d data type to be used for
geospatial comparators with GEOMETRY/GEOGRAPHY.

### CODE REVIEW

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 52 of 52 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52771#-:-MEhhJqm7o2kH7mqD5fk:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @miretskiy and @otan)

___
*[pkg/geo/bbox.go, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52771#-MEhYRp0A-IeTATF6ssa:-MEhYRp0A-IeTATF6ssb:biqzerd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a1c333a4ecf98512425c74cebbc1058e272fcd7/pkg/geo/bbox.go#L46)):*
> ```Go
> // Repr is the string representation of the CartesianBoundingBox.
> func (b *CartesianBoundingBox) Repr() string {
> 	// Using %f is not possible as it does not truncate leading zeroes.
> ```

did you mean truncate trailing zeroes, which is what the -1 parameter allows for?
https://play.golang.org/p/J5lR-6ID5VO
___
*[pkg/sql/sem/tree/datum.go, line 2940 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52771#-MEhdNToD4IiEahjWk_T:-MEhdNToD4IiEahjWk_U:b7rlk64) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a1c333a4ecf98512425c74cebbc1058e272fcd7/pkg/sql/sem/tree/datum.go#L2940)):*
> ```Go
> // DBox2D is the Datum representation of the Box2D type.
> type DBox2D struct {
> 	*geo.CartesianBoundingBox
> ```

The implementation of `Datum` is `*DBox2D`, so why do we have another level of pointer indirection, instead of doing
```
type DBox2D struct {
	geo.CartesianBoundingBox
}
```
Same question applies for `DGeometry` and `DGeography`.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/52771)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @miretskiy and @sumeerbhola)

___
*[pkg/geo/bbox.go, line 46 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52771#-MEhYRp0A-IeTATF6ssa:-MEhlyk6-oxeF8o6MRzm:bx1t6ie) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a1c333a4ecf98512425c74cebbc1058e272fcd7/pkg/geo/bbox.go#L46)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

did you mean truncate trailing zeroes, which is what the -1 parameter allows for?
https://play.golang.org/p/J5lR-6ID5VO

</blockquote></details>

Yep -- %f does not though, which is what the comment says. I've clarified this a bit.
___
*[pkg/sql/sem/tree/datum.go, line 2940 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/52771#-MEhdNToD4IiEahjWk_T:-MEhn15lDF4fBJqWmycp:b-a1j009) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a1c333a4ecf98512425c74cebbc1058e272fcd7/pkg/sql/sem/tree/datum.go#L2940)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

The implementation of `Datum` is `*DBox2D`, so why do we have another level of pointer indirection, instead of doing
```
type DBox2D struct {
	geo.CartesianBoundingBox
}
```
Same question applies for `DGeometry` and `DGeography`.
</blockquote></details>

I got a lot of annoying `method not on pointer receiver` messages last time I tried this. I think I can give it another go, but I'll save it for the stability period.

**Comment by otan** [comment]
bors r=sumeerbhola

**Comment by otan** [comment]
bors r=sumeerbhola

**Pull request merged**
