### PR TITLE
admission: smooth ioloadlistener token generation

### PR DESCRIPTION
**Pull request by bananabrick**
We add a new range of load called "Low load" which
split the previous "Underload" range. For scores between
0.5 and 1, we limit compaction tokens rather generating
unlimited compaction tokens for this range. This prevents
bursty behaviour.

Epic: none
Release note: None

### CODE REVIEW

**Comment by bananabrick** [comment]
Looks fine. `kv0/enc=false/nodes=3/cpu=32` run.

With new smoothing:
ultra_smooth_1

Without new smoothing:
medium_smooth

grafana with new smoothing: https://grafana.testeng.crdb.io/d/ngnKs_j7x/admission-control?orgId=1&from=1688593584703&to=1688595702443&var-cluster=arjunnair-1688593469-01-n4cpu32&var-instances=All

grafana master: https://grafana.testeng.crdb.io/d/ngnKs_j7x/admission-control?orgId=1&from=1688593967816&to=1688596153291&var-cluster=arjunnair-1688593922-01-n4cpu32&var-instances=All

new ops/sec: 
```
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
 1800.0s        0       11539851         6411.0     29.9     19.9     92.3    167.8   1409.3  
```

old ops/sec
```
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
 1800.0s        0       11751533         6528.6     29.4     18.9     92.3    167.8    872.4  write
```

**Review by sumeerbhola — APPROVED** [review]
Do you know (roughly) how frequently we transition to unlimited tokens?

:lgtm: 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106208#-:-N_-vpgi6wqwRqOoUKQV:b-xb3ybm)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bananabrick)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106208#-N_-w01m1AxKnkP739Lv):*
nit: splits
___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106208#-N_-w2bT5raBr4wkJiyN):*
nit: rather than generating

**Review by bananabrick — COMMENTED** [review]
Looking at the graph linked here: https://github.com/cockroachdb/cockroach/pull/106208#issuecomment-1622656105, it looks like we have ~30 spikes over a 1800s workload, so maybe once every minute?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106208#-:-N_1oWbz4qM7h5n89ASJ:btree4f)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @bananabrick)

**Pull request merged**
