### PR TITLE
importccl: add experimental_save_rejected option to CSV IMPORT 

### PR DESCRIPTION
**Pull request by spaskob**
This was promised to a client and will be backported to 19.2.1.
The feature should stay undocumented for now since the semantics
and UX are still not well understood.

To make the change work, we had to remove the parsing workers from
`conv.start` and move them to `readFile` which means that for each
file a separate set of workers will be brought up and down. Also the
tally for all total number of rejected rows was moved to `read_import_base.go`.

Touches #40374.

Release note (sql change): add undocumented experimental_save_rejected
option to CSV IMPORT.

### CODE REVIEW

**Review by dt — APPROVED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42112)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @spaskob)

___
*[pkg/ccl/importccl/import_processor_test.go, line 140 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42112#-LscPLdR2jP40mksx7It:-LscPLdS5eQ5Vo-PMhAP:b-hy3ocd) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c22e38d95a77f077cec3e9fe855ab9bee743d24/pkg/ccl/importccl/import_processor_test.go#L140)):*
> ```Go
> 					defer close(kvCh)
> 					if err := conv.readFiles(ctx, testCase.inputs, converterSpec.Format, externalStorage); err != nil {
> 						t.Fatalf("Conversion failed: %v", err)
> ```

If only this worked! Sadly you can't `t.Fatal` across goroutines -- you need to use something to pass the error back to the main goroutine and `Fatal` it there, either the way it was using a group before or with  a channel (or var if you can ensure ordered access otherwise). I suspect the group (the way it was) is the easiest.
___
*[pkg/ccl/importccl/import_stmt.go, line 239 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42112#-LscOpHH5uf-GHzVlMZ4:-LscOpHH5uf-GHzVlMZ5:bh3yurg) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c22e38d95a77f077cec3e9fe855ab9bee743d24/pkg/ccl/importccl/import_stmt.go#L239)):*
> ```Go
> 			format.Format = roachpb.IOFileFormat_CSV
> 			// Set the default CSV separator for the cases when it is not overwritten.
> 			format.Csv.Comma = ','
> ```

curious if something specific motivated this? I don't recall exactly why but for some reason I thought we liked using the zero value for "let the decoder pick the default". That said, I don't feel strongly either way.
___
*[pkg/ccl/importccl/read_import_base.go, line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42112#-LscRNeW65zhcIoH9le4:-LscRNeW65zhcIoH9le5:byz6c3g) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c22e38d95a77f077cec3e9fe855ab9bee743d24/pkg/ccl/importccl/read_import_base.go#L167)):*
> ```Go
> 
> 			var rejected chan string
> 			if (format.Format == roachpb.IOFileFormat_CSV && format.Csv.SaveRejected) ||
> ```

I'd rather add a `format.SaveRejected` field, that is independent of the file format (like format.Compression), so we don't need to keep adding cases here. 
___
*[pkg/ccl/importccl/read_import_csv.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42112#-LscSH80Bf0hE8jVSrFy:-LscSH80Bf0hE8jVSrFz:bswum5c) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc7b64ee56e95a36d9c2ccd93cfa65d0cb421e4d/pkg/ccl/importccl/read_import_csv.go#L73)):*
> ```Go
> 
> func (c *csvInputReader) start(group ctxgroup.Group) {
> 	group.GoCtx(func(ctx context.Context) error {
> ```

weak preference: I'd move these changes, to the worker pool setup/mgmt, to a standalone commit before the rejected support stuff, since I think that'd make it much easier, below, to see the _logic_ changes in loop for the rejected diff.
___
*[pkg/ccl/importccl/read_import_csv.go, line 234 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42112#-LscSvxn8NNEGYDE6q7y:-LscSvxn8NNEGYDE6q7z:bvm6or) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c22e38d95a77f077cec3e9fe855ab9bee743d24/pkg/ccl/importccl/read_import_csv.go#L234)):*
> ```Go
> 							log.Error(ctx, err)
> 							batch.rejected <- strings.Join(record, string(c.opts.Comma)) + "\n"
> 							continue OUTER
> ```

nit: on first read I thought this was skipping the remainder of the rows in the batch, since I read "for.. record :=" as "record" being a synonym for "row", when it is actually, I think, "field". renaming the loop var and/or commenting at the label about what it means might help.
___
*[pkg/roachpb/io-formats.proto, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42112#-LscTeAjDU4q00m0_acJ:-LscTeAjDU4q00m0_acK:b-h9meqo) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c22e38d95a77f077cec3e9fe855ab9bee743d24/pkg/roachpb/io-formats.proto#L58)):*
> ```protobuf
>   optional bool strict_quotes = 5 [(gogoproto.nullable) = false];
>   // If true, don't abort on failures but instead save the offending row and keep on.
>   optional bool save_rejected = 6 [(gogoproto.nullable) = false];
> ```

see above: now that we're supporting multiple formats, I really think this should move out a level and be a common flag.

**Review by spaskob — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42112)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @spaskob)

___
*[pkg/ccl/importccl/import_processor_test.go, line 140 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42112#-LscPLdR2jP40mksx7It:-Lscb_iJ4Yj5GdxBLVl1:bhy9oss) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c22e38d95a77f077cec3e9fe855ab9bee743d24/pkg/ccl/importccl/import_processor_test.go#L140)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

If only this worked! Sadly you can't `t.Fatal` across goroutines -- you need to use something to pass the error back to the main goroutine and `Fatal` it there, either the way it was using a group before or with  a channel (or var if you can ensure ordered access otherwise). I suspect the group (the way it was) is the easiest.
</blockquote></details>

Will do 
___
*[pkg/ccl/importccl/import_stmt.go, line 239 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42112#-LscOpHH5uf-GHzVlMZ4:-LscbpYaDUeuVrhe5eGp:bebrt1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c22e38d95a77f077cec3e9fe855ab9bee743d24/pkg/ccl/importccl/import_stmt.go#L239)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

curious if something specific motivated this? I don't recall exactly why but for some reason I thought we liked using the zero value for "let the decoder pick the default". That said, I don't feel strongly either way.
</blockquote></details>

Will do
___
*[pkg/ccl/importccl/read_import_base.go, line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42112#-LscRNeW65zhcIoH9le4:-LscbwFH1IkqSa7mA_po:b6zrf4q) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c22e38d95a77f077cec3e9fe855ab9bee743d24/pkg/ccl/importccl/read_import_base.go#L167)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

I'd rather add a `format.SaveRejected` field, that is independent of the file format (like format.Compression), so we don't need to keep adding cases here. 
</blockquote></details>

I agree, this would require a fairly substantial refactor to do right across a bunch of shared options across modes. And also re-thinking the UX - do we need different names in DELIMITED and CSV for the fields separators?
Since this is a backport PR, should we leave this for a future PR?
___
*[pkg/ccl/importccl/read_import_csv.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42112#-LscSH80Bf0hE8jVSrFy:-LsccNpP2RkCEzz__RxB:bebrt1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc7b64ee56e95a36d9c2ccd93cfa65d0cb421e4d/pkg/ccl/importccl/read_import_csv.go#L73)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

weak preference: I'd move these changes, to the worker pool setup/mgmt, to a standalone commit before the rejected support stuff, since I think that'd make it much easier, below, to see the _logic_ changes in loop for the rejected diff.
</blockquote></details>

Will do
___
*[pkg/ccl/importccl/read_import_csv.go, line 234 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42112#-LscSvxn8NNEGYDE6q7y:-LsccQ1nAjKfrCz-N4dv:bebrt1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c22e38d95a77f077cec3e9fe855ab9bee743d24/pkg/ccl/importccl/read_import_csv.go#L234)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

nit: on first read I thought this was skipping the remainder of the rows in the batch, since I read "for.. record :=" as "record" being a synonym for "row", when it is actually, I think, "field". renaming the loop var and/or commenting at the label about what it means might help.
</blockquote></details>

Will do
___
*[pkg/roachpb/io-formats.proto, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42112#-LscTeAjDU4q00m0_acJ:-LsccSZm0nJUNShuzq92:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c22e38d95a77f077cec3e9fe855ab9bee743d24/pkg/roachpb/io-formats.proto#L58)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

see above: now that we're supporting multiple formats, I really think this should move out a level and be a common flag.
</blockquote></details>

ditto

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42112)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @spaskob)

___
*[pkg/ccl/importccl/read_import_base.go, line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42112#-LscRNeW65zhcIoH9le4:-LsccmWF4VgU8j2-LB8i:bcbsh96) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c22e38d95a77f077cec3e9fe855ab9bee743d24/pkg/ccl/importccl/read_import_base.go#L167)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

I agree, this would require a fairly substantial refactor to do right across a bunch of shared options across modes. And also re-thinking the UX - do we need different names in DELIMITED and CSV for the fields separators?
Since this is a backport PR, should we leave this for a future PR?
</blockquote></details>

we're adding a *new field* to the photo in this change though, so I think we can add it where we want it to live in the future, even if for now the only write to that field is still just the one you have above in the CSV case in import_stmt.go -- I don't think that significantly changes the scope of the changes for back ports, but it does future-proof the proto for when we generalize later, no?

**Review by spaskob — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42112)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @spaskob)

___
*[pkg/ccl/importccl/read_import_base.go, line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42112#-LscRNeW65zhcIoH9le4:-Lsci1eW2NN4pUxP_X6p:b-zdq7k4) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c22e38d95a77f077cec3e9fe855ab9bee743d24/pkg/ccl/importccl/read_import_base.go#L167)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

we're adding a *new field* to the photo in this change though, so I think we can add it where we want it to live in the future, even if for now the only write to that field is still just the one you have above in the CSV case in import_stmt.go -- I don't think that significantly changes the scope of the changes for back ports, but it does future-proof the proto for when we generalize later, no?
</blockquote></details>

that is true in read_import_base.go however each individual reader gets passed only its options, see https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/importccl/read_import_csv.go#L35

so adding global option will require refactoring of the structs that are passed.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42112)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @spaskob)

___
*[pkg/ccl/importccl/read_import_base.go, line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42112#-LscRNeW65zhcIoH9le4:-LscjBQXC8dZKq4U7lpX:b-bmcnyd) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c22e38d95a77f077cec3e9fe855ab9bee743d24/pkg/ccl/importccl/read_import_base.go#L167)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

that is true in read_import_base.go however each individual reader gets passed only its options, see https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/importccl/read_import_csv.go#L35

so adding global option will require refactoring of the structs that are passed.
</blockquote></details>

That's true, though I think until we do broader refactoring, we could just condition on `rejected != nil` so the only place we need to check the options is in base, when deciding to initialize the chan, and then the chan pointer arg is already passed into the read func, so the read func doesn't really need to go back to the options at that point?

**Review by spaskob — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42112)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @spaskob)

___
*[pkg/ccl/importccl/import_processor_test.go, line 140 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42112#-LscPLdR2jP40mksx7It:-Lsr-Qr7DSJTygxsP8D9:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c22e38d95a77f077cec3e9fe855ab9bee743d24/pkg/ccl/importccl/import_processor_test.go#L140)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

Will do 
</blockquote></details>

Done
___
*[pkg/ccl/importccl/import_stmt.go, line 239 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42112#-LscOpHH5uf-GHzVlMZ4:-Lsr-bpf0ISC37lhj0Ci:b-kte89a) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c22e38d95a77f077cec3e9fe855ab9bee743d24/pkg/ccl/importccl/import_stmt.go#L239)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

Will do
</blockquote></details>

The problem is that we need to recreate the the line for rejected and for that we are using the separator.
___
*[pkg/ccl/importccl/read_import_base.go, line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42112#-LscRNeW65zhcIoH9le4:-Lsr-nkPCg1mAKhbNWXG:bkjxpv0) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c22e38d95a77f077cec3e9fe855ab9bee743d24/pkg/ccl/importccl/read_import_base.go#L167)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

That's true, though I think until we do broader refactoring, we could just condition on `rejected != nil` so the only place we need to check the options is in base, when deciding to initialize the chan, and then the chan pointer arg is already passed into the read func, so the read func doesn't really need to go back to the options at that point?
</blockquote></details>

alright
___
*[pkg/ccl/importccl/read_import_csv.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42112#-LscSH80Bf0hE8jVSrFy:-Lsr04CpBdlyYGbePb0E:btym4ne) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc7b64ee56e95a36d9c2ccd93cfa65d0cb421e4d/pkg/ccl/importccl/read_import_csv.go#L73)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

Will do
</blockquote></details>

I'd leave them if you don't mind
___
*[pkg/ccl/importccl/read_import_csv.go, line 234 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42112#-LscSvxn8NNEGYDE6q7y:-Lsr0DuP3PRwn6-bvwtZ:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c22e38d95a77f077cec3e9fe855ab9bee743d24/pkg/ccl/importccl/read_import_csv.go#L234)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

Will do
</blockquote></details>

done
___
*[pkg/roachpb/io-formats.proto, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42112#-LscTeAjDU4q00m0_acJ:-Lsr0jP9DJZOt-bWpBVn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c22e38d95a77f077cec3e9fe855ab9bee743d24/pkg/roachpb/io-formats.proto#L58)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Comment by spaskob** [comment]
PTAL

**Review by dt — APPROVED** [review]
LGTM!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42112#-:-Lsr8J5eBU-TcDhrb42e:b-85i648)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @spaskob)

___
*[pkg/ccl/importccl/read_import_csv.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42112#-LscSH80Bf0hE8jVSrFy:-Lsr7m2K9FcpzdRJLAtR:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc7b64ee56e95a36d9c2ccd93cfa65d0cb421e4d/pkg/ccl/importccl/read_import_csv.go#L73)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

I'd leave them if you don't mind
</blockquote></details>

:thumbsup: 
___
*[pkg/ccl/importccl/read_import_csv.go, line 111 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42112#-Lsr7dEpB9Ph-d3pmEm7:-Lsr7dEpB9Ph-d3pmEm8:b-mqdkwo) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca899e2050e2fab71904b737197b445b1496c623/pkg/ccl/importccl/read_import_csv.go#L111)):*
> ```Go
> 	cr.Comment = c.opts.Comment
> 
> 	c.recordCh = make(chan csvRecord)
> ```

nit: I'd have made this a local in this func instead of modifying state on `c`
___
*[pkg/ccl/importccl/read_import_csv.go, line 125 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42112#-Lsr7u9K3c05w5PVVqKH:-Lsr7u9K3c05w5PVVqKI:b-4ueya2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ca899e2050e2fab71904b737197b445b1496c623/pkg/ccl/importccl/read_import_csv.go#L125)):*
> ```Go
> 		defer tracing.FinishSpan(span)
> 		return ctxgroup.GroupWorkers(ctx, c.parallelism, func(ctx context.Context) error {
> 			return c.convertRecordWorker(ctx)
> ```

IMO it'd be _slightly_ cleaner to have `convertRecordWroker` take `recordCh` and `rejected` as arguments than to put them on `c`/in the batches, but I'm fine with it this way particular for now if it minimizes scope of patch for backports.

**Pull request merged**
