### PR TITLE
storage/engine: add pebbleIterator support for time-bound iterators

### LINKED ISSUE #41743: storage/engine: add pebbleIterator support for time-bound iteration
`pebbleIterator` currently ignores `IterOptions.{Min,Max}TimestampHint`. Those options are used for time-bound iteration. Currently that functionality looks like it is only used by `ExportRequest` (used for backup).

### PR DESCRIPTION
**Pull request by petermattis**
Fixes #41743

Release note: None

### CODE REVIEW

**Review by itsbilal — APPROVED** [review]
:lgtm:

Doing string comparisons on big endian encoded timestamps seems a bit unintuitive at first but I assume it's worth it for avoiding two extra timestamp decodes for every table.

> Reviewed 2 of 2 files at r1, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41854#-:-LruBS755xzRyvyQoSK1:bmfy2wp)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajkr and @sumeerbhola)

**Review by petermattis — COMMENTED** [review]
TFTR!

> Doing string comparisons on big endian encoded timestamps seems a bit unintuitive at first but I assume it's worth it for avoiding two extra timestamp decodes for every table.

I was confused about this as well initially, but decided to stick with this approach as it mirrors what we do on the C++ side.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41854#-:-LruDFs2ALPKjyh7SjpB:b4ue035)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajkr and @sumeerbhola)

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41854)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajkr and @petermattis)

___
*[pkg/storage/engine/pebble.go, line 97 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41854#-LrxozzyB6xCzmJOOk93:-Lrxozzz6yR5aEBZ_saW:b-sh7we) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fd5533761a429e6569905ec372ed2eeefd3a2ce/pkg/storage/engine/pebble.go#L97)):*
> ```Go
> 
> func (t *pebbleTimeBoundPropCollector) Add(key pebble.InternalKey, value []byte) error {
> 	_, ts, ok := enginepb.SplitMVCCKey(key.UserKey)
> ```

are we not doing the write intent metadata handling that is done by TimeBoundTblPropCollector?  I remember you had said it was buggy but I can't reconstruct the reason. We won't accurately account for deletions of the metadata so it won't be as tight as it could be but it still seems tighter than using the 0 timestamp. What am I missing?

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41854)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajkr and @sumeerbhola)

___
*[pkg/storage/engine/pebble.go, line 97 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41854#-LrxozzyB6xCzmJOOk93:-LrxrwMxDy-OITAwYsL_:b-euw3u0) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fd5533761a429e6569905ec372ed2eeefd3a2ce/pkg/storage/engine/pebble.go#L97)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

are we not doing the write intent metadata handling that is done by TimeBoundTblPropCollector?  I remember you had said it was buggy but I can't reconstruct the reason. We won't accurately account for deletions of the metadata so it won't be as tight as it could be but it still seems tighter than using the 0 timestamp. What am I missing?
</blockquote></details>

Good catch. Tat seems to be missing. This was all just code movement in this PR and I didn't check that this property collector was identical to the C++ one. I'll file an issue.

**Pull request merged**
