### PR TITLE
storage: add a test for stale range descriptor during replica GC

### PR DESCRIPTION
**Pull request by tamird**
I've confirmed this instantly panics with #11699 reverted.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/11798)

### CODE REVIEW

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/client_raft_test.go, line 2106 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/11798#-KY1ofGogujhnD9OmKNb:-KY1ofGogujhnD9OmKNc:b-wht2l9) ([raw file](https://github.com/cockroachdb/cockroach/blob/22bb3ad5501b1802308f124b3df30bffc3f6ee62/pkg/storage/client_raft_test.go#L2106)):*
> ```Go
> 	fromTransport.Listen(fromStore.StoreID(), errChan)
> 
> 	// Send the heartbeat. Boom.
> ```

Link to the issue explaining the failure we previously saw here. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11798#-:-KY1oo_PthbXVHiqNO3I:bnfp4nl)*

**Comment by tamird** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/storage/client_raft_test.go, line 2106 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/11798#-KY1ofGogujhnD9OmKNb:-KY1rOqNJjUZMGUkOxBL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/22bb3ad5501b1802308f124b3df30bffc3f6ee62/pkg/storage/client_raft_test.go#L2106)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Link to the issue explaining the failure we previously saw here. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11798)*

**Comment by bdarnell** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/client_test.go, line 205 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11798#-KY1w2VkAEuznbYhb0_4:-KY1w2VkAEuznbYhb0_5:bp083pn) ([raw file](https://github.com/cockroachdb/cockroach/blob/9814b45c57de646b743de4db3e3b458123e09061/pkg/storage/client_test.go#L205)):*
> ```Go
> 	// test individually. transportStopper is for 'transport', and the
> 	// 'stoppers' slice corresponds to the 'stores'.
> 	// TODO(bdarnell): now that there are multiple transports, do we
> ```

Remove this TODO. (For reference, I moved from a single transport to multiple transports in #4926. Comments from that time indicate that it was necessary in order to move to multiple grpcServers, although that appears to no longer be the case)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11798)*

**Comment by tamird** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/client_test.go, line 205 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11798#-KY1w2VkAEuznbYhb0_4:-KY1xv9UlXt4ulLdwQMa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9814b45c57de646b743de4db3e3b458123e09061/pkg/storage/client_test.go#L205)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Remove this TODO. (For reference, I moved from a single transport to multiple transports in #4926. Comments from that time indicate that it was necessary in order to move to multiple grpcServers, although that appears to no longer be the case)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11798)*

**Pull request merged**
