### PR TITLE
dist_sender: check rudimentary validation of batch

### PR DESCRIPTION
**Pull request by kkaneda**
This is a revised version of #4529

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6349)

### CODE REVIEW

**Comment by tschottdorf** [comment]
LGTM

**Comment by kkaneda** [comment]
Thanks, @tschottdorf ! Could you merge? I don't have the write access..

**Comment by tschottdorf** [comment]
Oh, thought you did. We must've changed something.

**Comment by kkaneda** [comment]
Thx! Yeah, looks like it is tied to project collaborators (https://github.com/orgs/cockroachdb/people)..

**Comment by tschottdorf** [comment]
Hmm, says you have write access here: https://github.com/orgs/cockroachdb/people/kkaneda
We'll see what that's about.

**Comment by bdarnell** [comment]
@kkaneda I've removed your write access and re-added you, so we'll see if that fixes things for your next PR.

**Comment by kkaneda** [comment]
Thanks, @tschottdorf , @bdarnell !

**Pull request merged**
