### PR TITLE
kvserver: expose a more user friendly protected ts error

### PR DESCRIPTION
**Pull request by adityamaru**
We have seen several support issues related to BACKUPs where the gc.ttl
being too short for the backup cadence results in the protected ts
record failing to be "verified". The error bubbled up in this scenario
is a proto dump of the rangedescs and protected ts record we are
attempting to verify. While this has most information, it is not very
parseable. Further, in the case where the gc is the reason for failure
to verify, the error does not expose information about where the
threshold currently is.

This change strips out relevant information, and bubbles up a more
informative error message. The change in tandem with docs about possible
bakcup failure modes, should help reduce the number of support
escalations.

Informs: #57064

### CODE REVIEW

**Comment by adityamaru** [comment]
I'll add the relevant changes to backup/import, along with a test in a follow-up PR!

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61610)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @ajwerner)

___
*[pkg/kv/kvserver/replica_command.go, line 3140 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61610#-MVHruBg7KRfZm_ZM5WZ:-MVHruBg7KRfZm_ZM5W_:b-1al9bd) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3da94a278655517561f7f3e5a6e364e6c785d46/pkg/kv/kvserver/replica_command.go#L3140)):*
> ```Go
> 	// executeAdminBatch adds the response to the batch, thereby allowing us to
> 	// construct a more informative error at the sender.
> 	if errors.Is(err, errGCThreshold) {
> ```

This would be easier for me to ensure that we're returning errors in the right spot by butting the errGCThreshold checks together like:
```
if err != nil {
    if errors.Is(err, errGCThreshold) {
        // We do not want to bubble up ...
        resp.RangeIdToFailedReason[int64(r.Desc().RangeID)] = err.Error()
    } else {
        return resp, err
    }
}
```
___
*[pkg/kv/kvserver/replica_protected_timestamp.go, line 204 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61610#-MVHsQNVBMeTUml3TwY4:-MVHsQNVBMeTUml3TwY5:b6eis17) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3da94a278655517561f7f3e5a6e364e6c785d46/pkg/kv/kvserver/replica_protected_timestamp.go#L204)):*
> ```Go
> 	defer r.protectedTimestampMu.Unlock()
> 	if args.Protected.Less(r.protectedTimestampMu.pendingGCThreshold) {
> 		return false, false, errors.Mark(errors.Newf(
> ```

Can we separate out the `errors.Newf`and `errors.Mark`. There's a lot going on here. :)
___
*[pkg/roachpb/api.proto, line 1559 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61610#-MVHtR4j4p2WKG7-BHk2:-MVHtR4j4p2WKG7-BHk3:bgcjyue) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3da94a278655517561f7f3e5a6e364e6c785d46/pkg/roachpb/api.proto#L1559)):*
> ```protobuf
> 
>   repeated RangeDescriptor failed_ranges = 3 [(gogoproto.nullable) = false];
>   map<int64, string> range_id_to_failed_reason = 4 [(gogoproto.nullable) = false];
> ```

I'm not yet sure if this is a good idea, but I get a bit nervous when I see fields that can store some weird state. In this case, we're relying on failed_ranges and range_id_to_failed_reason for synchronization. Would it make sense to deprecated field 3, and set it for backwards compatibility. And then field 4 would be `repeated FailedRange` where `FailedRange` would be a message containing a range descriptor and also the failed reason?

It's a bit of replication and more steps to deal with in terms of ensuring nice-behaviour in mixed-version clusters but it may be worth it to have a nicer schema down the road?

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61610)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @pbardea)

___
*[pkg/kv/kvserver/replica_protected_timestamp.go, line 204 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61610#-MVHsQNVBMeTUml3TwY4:-MVIKAQu46F5wqL3FLpH:b2ngthx) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3da94a278655517561f7f3e5a6e364e6c785d46/pkg/kv/kvserver/replica_protected_timestamp.go#L204)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Can we separate out the `errors.Newf`and `errors.Mark`. There's a lot going on here. :)
</blockquote></details>

+1 
___
*[pkg/roachpb/api.proto, line 1559 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61610#-MVHtR4j4p2WKG7-BHk2:-MVIKY1m34AY7DPFXYn2:blidbit) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3da94a278655517561f7f3e5a6e364e6c785d46/pkg/roachpb/api.proto#L1559)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

I'm not yet sure if this is a good idea, but I get a bit nervous when I see fields that can store some weird state. In this case, we're relying on failed_ranges and range_id_to_failed_reason for synchronization. Would it make sense to deprecated field 3, and set it for backwards compatibility. And then field 4 would be `repeated FailedRange` where `FailedRange` would be a message containing a range descriptor and also the failed reason?

It's a bit of replication and more steps to deal with in terms of ensuring nice-behaviour in mixed-version clusters but it may be worth it to have a nicer schema down the road?
</blockquote></details>

What really are we learning here? It feels to me like the only things we didn't know before were: 

a) whether the gc threshold was pending or committed (I don't think this is very important to know)
b) the actual gc threshold value

Is knowing `b)` very useful? If so, is knowing all of the values of `b)` useful? Could we just store one value here that's a range ID and its threshold and just store one of them? 

To that point, I wonder if I regret storing all of the range descriptors here. It could be something of a memory leak. Perhaps we should only store a subset of them when we merge.

**Comment by adityamaru** [comment]
> What really are we learning here? It feels to me like the only things we didn't know before were:
> 
> a) whether the gc threshold was pending or committed (I don't think this is very important to know)
> b) the actual gc threshold value
> 
> Is knowing `b)` very useful? If so, is knowing all of the values of `b)` useful? Could we just store one value here that's a range ID and its threshold and just store one of them?
> 
- iiuc the value in combining the errors across ranges is that during a BACKUP spanning multiple ranges, we could return an error with information about all the ranges that are failing with the gc error, so that the user can do a sweep of those tables and adjust the ttl if required.
- I don't think the actual gc threshold value is as important as conveying to the user that the error was caused because of the gc threshold being past our pts. If we're special-casing such an error, why not stick the timestamps in there 🤷 

> To that point, I wonder if I regret storing all of the range descriptors here. It could be something of a memory leak. Perhaps we should only store a subset of them when we merge.

For my understanding you mean, that in the response `combine()` we should dedup the range descriptors in failed_ranges? I don't follow why this could be a memory leak. 

How do you feel about deprecating `failed_ranges`, and making a leaner nested message as Paul suggests, instead of saving the range descriptors. Something like:
```
message FailedRange {
 rangeID ID
 span string
 gcThreshold hlc.Timestamp // which will only be set if the error is because of the thresh > pts.
}
```
which would allow us to construct the error message in the verifier.

**Comment by adityamaru** [comment]
@ajwerner putting this on your radar for a some feedback before I clean it up. Thanks!

**Review by ajwerner — COMMENTED** [review]
> For my understanding you mean, that in the response combine() we should dedup the range descriptors in failed_ranges? I don't follow why this could be a memory leak.

Like, today we just make a slice with all of the range descriptors. Each range descriptors may (sort of) be arbitrarily big. 

> message FailedRange {
> rangeID ID
> span string
> gcThreshold hlc.Timestamp // which will only be set if the error is because of the thresh > pts.
> }

This is fine, however, my question about what we want to do on `combine` still stands. Do we care about having more than one range's span captured? A single range's span can give you a table at least.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61610#-:-MVqIcR59SQ2GbzxSxX8:b-p645iz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @pbardea)

**Comment by adityamaru** [comment]
> This is fine, however, my question about what we want to do on `combine` still stands. Do we care about having more than one range's span captured? A single range's span can give you a table at least.

If we aggregate the failed range information across verify requests, with the gc error, the user can do a single sweep of those tables and adjust all the suspect ttls before re-running the backup? That's the only reason that makes combining worth it, in my opinion.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61610)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @pbardea)

___
*[pkg/kv/kvserver/replica_protected_timestamp.go, line 29 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/61610#-MW-CEVO-z5zCf6YAXIY:-MW-CEVO-z5zCf6YAXIZ:b-vij7qd) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf8a128a5ce4a3a693edf63cda606fe93b2e89b7/pkg/kv/kvserver/replica_protected_timestamp.go#L29)):*
> ```Go
> // timestamp record could not be verified. It is primarily used to bubble up a
> // more useful error to users of protected timestamps eg: BACKUP.
> var errFailedToVerify = errors.New("unable to verify protected ts record")
> ```

I'm worried you're not doing enough to make sure that this error is going to properly cross rpc boundaries. please make sure to test this on multi-node clusters where you're sure that you're hitting a different node

**Comment by adityamaru** [comment]
I spoke to @ajwerner offline and switched from returning a sentinel error to returning an additional return value when we want to construct a user facing reason. This should be RFAL!

**Review by pbardea — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61610)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @ajwerner, and @pbardea)

___
*[pkg/kv/kvserver/replica_command.go, line 3150 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61610#-MWPdC2cBR4TEZSjDbHE:-MWPdC2d535e73l5B32A:b-1abego) ([raw file](https://github.com/cockroachdb/cockroach/blob/166e062e393cd9021b51055ec339f82a4d154de2/pkg/kv/kvserver/replica_command.go#L3150)):*
> ```Go
> 			}
> 			resp.VerificationFailedRanges = append(resp.VerificationFailedRanges, failedRange)
> 			resp.DeprecatedFailedRanges = append(resp.DeprecatedFailedRanges, *r.Desc())
> ```

nit: we could consider putting this under a cluster version check if we wanted to stop sending the entire range descriptor sooner. Let's at least add a comment to remove this in 21.2 to help us not forget it here for too long

**Review by ajwerner — COMMENTED** [review]
I'm fine with this. When paul is happy, I'm happy. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61610#-:-MWPie0sCegb673QNBHS:b-y4b55)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @pbardea)

___
*[pkg/kv/kvserver/replica_protected_timestamp.go, line 77 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61610#-MWPim-U6-t4Sk3nKUyY:-MWPim-U6-t4Sk3nKUyZ:b-wqaun9) ([raw file](https://github.com/cockroachdb/cockroach/blob/166e062e393cd9021b51055ec339f82a4d154de2/pkg/kv/kvserver/replica_protected_timestamp.go#L77)):*
> ```Go
> func (r *Replica) protectedTimestampRecordApplies(
> 	ctx context.Context, args *roachpb.AdminVerifyProtectedTimestampRequest,
> ) (willApply bool, doesNotApplyReason string, _ error) {
> ```

I could have seen this return value being more structured and let the higher level generate the string but I don't feel too strongly.

**Review by pbardea — APPROVED** [review]

**Comment by adityamaru** [comment]
TFTRs!

bors r=pbardea,ajwerner

**Pull request merged**
