### PR TITLE
sql: Create placeholderAnnotationVisitor to process placeholder annotations

### PR DESCRIPTION
**Pull request by nvb**
This visitor performs an order-independent global traversal of the provided
Statement, annotating all placeholders with a type in either of the
following situations.
- the placeholder is the subject of an explicit type annotation in at least one
  of its occurrences. If it is subject to multiple explicit type annotations where
  the types are not all in agreement, and error will be thrown. _(not implemented yet)_
- the placeholder is the subject to an implicit type annotation, meaning that it
  is not subject to an explicit type annotation, and that in all occurrences of the
  placeholder, it is subject to a cast to the same type. If it is subject to casts
  of multiple types, no error will be thrown, but the placeholder will not be
  annotated.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6504)

### CODE REVIEW

**Comment by knz** [comment]
I do not understand the word "symmetric" and I think it's not a common term in our industry nor compiler construction. Please clarify.

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/parser/constant.go, line 209 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6504#-KGxBBFrKtQOdQ7JOJ3f:-KGxBBFtA3mPAgWuxo8h:1004920308) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b7ee2dda9d2a0c3e954c650c8be7eb3c656d47c/sql/parser/constant.go#L209)):*
This belongs to a different PR. Please split.

---

*[sql/parser/eval.go, line 1509 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6504#-KGxBG2-P3PNBrGcgrNB:-KGxBG20I2L8pWWd02Hi:2115068626) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b7ee2dda9d2a0c3e954c650c8be7eb3c656d47c/sql/parser/eval.go#L1509)):*
Also a different PR.

---

*[sql/parser/type_check.go, line 844 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6504#-KGxBQ6j6YfHa6QhRdQz:-KGxBQ6k2K7-yWK5B0rz:-1609079955) ([raw file](https://github.com/cockroachdb/cockroach/blob/667b864416b1969794fc33b5142cf36364263f43/sql/parser/type_check.go#L844)):*
See my previous comment about the word "symmetric".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6504#-:-KGxAqNZQ5mb7eyX7Vh-:1594286408)*

**Comment by nvanbenschoten** [comment]
What I mean by “symmetric" is that the order and structure of statements/expressions within the statement tree will not affect the result of the traversal. For instance the algorithm will work the same on `$1::INT * ($1 + $2)` as it will on `($2 + $1) * $1::INT`. Do you know of a more commonly used term to describe this trait in an algorithm?

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sql/parser/eval.go, line 1509 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6504#-KGxBG2-P3PNBrGcgrNB:-KGzbng0Fun4UCz4x12X:-701528961) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b7ee2dda9d2a0c3e954c650c8be7eb3c656d47c/sql/parser/eval.go#L1509)):*
Removing a stray empty line in a related method deserves an entire PR?

---

*[sql/parser/constant.go, line 209 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6504#-KGxBBFrKtQOdQ7JOJ3f:-KGzdg6nGgtIic7CoSzp:-16225058) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b7ee2dda9d2a0c3e954c650c8be7eb3c656d47c/sql/parser/constant.go#L209)):*
Done. #6518.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6504#-:-KGzdm1vtp84A4Zoizfg:-469084373)*

**Comment by knz** [comment]
Then the right word is order-independent but I'm even tempted to call it context-free.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/parser/eval.go, line 1509 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6504#-KGxBG2-P3PNBrGcgrNB:-KGzoQyRfXqZxlPpJGlz:-1919082570) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b7ee2dda9d2a0c3e954c650c8be7eb3c656d47c/sql/parser/eval.go#L1509)):*
See d6338576f5d577ee2351e9764a4dee54cc7f490a, 3c2e31f9525f983e086cc2f6eb6b28e49a6a8ccc, 29e8f81acbf630de83094cef78548b9bfb221690 and others.

I probably would be OK with a different commit in this PR too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6504#-:-KGznyP2I9qK8ZHE4d3Y:-505241555)*

**Comment by knz** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6504)*

**Comment by nvanbenschoten** [comment]
Ok I went with "order-independent". I just wish there was a term that better captured the algorithm's agnostic nature not only w.r.t order, but also to general structure of the tree. Anyway, thanks for the review.

---

Review status: 2 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[sql/parser/eval.go, line 1509 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6504#-KGxBG2-P3PNBrGcgrNB:-KH0aJMDAdlZOrEsDsw1:-393799616) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b7ee2dda9d2a0c3e954c650c8be7eb3c656d47c/sql/parser/eval.go#L1509)):*
If you insist :) Done.

---

*[sql/parser/type_check.go, line 844 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6504#-KGxBQ6j6YfHa6QhRdQz:-KH0byMiNsjdrYimwM1y:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/667b864416b1969794fc33b5142cf36364263f43/sql/parser/type_check.go#L844)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6504#-:-KH0_biXBZQ8QA8MpIcR:1207216385)*

**Comment by knz** [comment]
:lgtm:  modulo rebase

<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Ok I went with "order-independent". I just wish there was a term that better captured the algorithm's agnostic nature not only w.r.t order, but also to general structure of the tree. Anyway, thanks for the review.</details>


---

Reviewed 5 of 6 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6504#-:-KHLJlnYOZBcHJwD-3pW:-1756543619)*

**Pull request merged**
