### PR TITLE
sql: add nodes for each EXPLAIN ANALYZE operator

### PR DESCRIPTION
**Pull request by RaduBerinde**
Show the cluster nodes involved in the execution of each operator.

Note that this info does not show up in the non-analyze EXPLAIN. It is
technically much more challenging to do that because of the indirect
way we do distsql planning. Once we have the new DistSQL exec factory,
we will be able to add it.

Note on the implementation: I started by trying to make execution set
`ComponentID.NodeID` in all cases, but I got stuck in `ProcessorBase`
where we only have a `SQLIDContainer` available. I don't fully
understand the new abstraction and whether the distsql components and
flows should really use SQLIDs instead of NodeIDs.

Unfortunately, there is not much we can do to test this currently
(other than manual testing). I will investigate making the
"deterministic" flag more fine-grained, so that we can hide truly
non-deterministic values (like timings) separately from those that
just vary with the configuration (query distribution).

Example:
```
movr> EXPLAIN ANALYZE SELECT * FROM rides JOIN vehicles ON rides.vehicle_id = vehicles.id;
                    info
--------------------------------------------
  planning time: 158µs
  execution time: 7ms
  distribution: full
  vectorized: true

   hash join
  │ cluster nodes: n1, n2, n3
  │ actual row count: 500
  │ equality: (vehicle_id) = (id)
  │
  ├──  scan
  │     cluster nodes: n1, n2, n3
  │     actual row count: 500
  │     KV rows read: 500
  │     KV bytes read: 86 KiB
  │     missing stats
  │     table: rides@primary
  │     spans: FULL SCAN
  │
  └──  scan
        cluster nodes: n1, n2, n3
        actual row count: 15
        KV rows read: 15
        KV bytes read: 2.3 KiB
        missing stats
        table: vehicles@primary
        spans: FULL SCAN
```

Release note (sql change): EXPLAIN ANALYZE now includes the nodes
which were involved in the execution of each operator in the tree.

Informs #59860.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
CC @awoods187

**Review by asubiotto — COMMENTED** [review]
> Note on the implementation: I started by trying to make execution set
> ComponentID.NodeID in all cases, but I got stuck in ProcessorBase
> where we only have a SQLIDContainer available. I don't fully
> understand the new abstraction and whether the distsql components and
> flows should really use SQLIDs instead of NodeIDs.

SQLIDContainer is just the node ID and you can treat it as such (by casting). The end goal is to remove all notion of NodeIDs and just have sql instance IDs (https://github.com/cockroachdb/cockroach/issues/49596).

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60550#-:-MTemqxH6YZ1r_QhT2wq:b-wra5nb)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by RaduBerinde** [comment]
I see. I tried working on it some more but the change is getting pretty big, we need to plumb the node ID in other places (e.g. diagram data). I think I'd rather merge this as-is for now.

**Comment by awoods187** [comment]
This looks great and I'll take it in explain analyze for now. We can add to explain in the future as you said.

**Comment by asubiotto** [comment]
LGTM

**Comment by RaduBerinde** [comment]
Actually, I think I figured out the NodeID stuff, PTAL.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 14 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60550#-:-MTjfpLA92l22qyhTzR2:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/execinfra/flow_context.go, line 120 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60550#-MTjfI66ExRUdMU0U6ih:-MTjfI674fiEHbtyYpEG:b-pawcud) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a74e20cfd80726e34c55b25ecee7d673bd43c89/pkg/sql/execinfra/flow_context.go#L120)):*
> ```Go
> // The stream must originate from the node associated with this FlowCtx.
> func (ctx *FlowCtx) StreamComponentID(streamID execinfrapb.StreamID) execinfrapb.ComponentID {
> 	// TODO(radu): the component stats should store SQLInstanceID instead.
> ```

nit: Could we do the inverse and create a sql instance ID from places where we have a nodeID?
___
*[pkg/sql/flowinfra/outbox_test.go, line 570 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60550#-MTjfbptByciMYJ427bL:-MTjfbptByciMYJ427bM:b-8cr0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a74e20cfd80726e34c55b25ecee7d673bd43c89/pkg/sql/flowinfra/outbox_test.go#L570)):*
> ```Go
> 					NodeDialer: nodedialer.New(clientRPC, staticAddressResolver(addr)),
> 				},
> 				NodeID: base.NewSQLIDContainer(1, nil /* nodeID */),
> ```

nit: maybe make a `TestingSQLIDContainer` function with no args that returns this to avoid repeating these calls

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60550#-:-MTlV2or87uTwFQwZ09g:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

___
*[pkg/sql/execinfra/flow_context.go, line 120 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60550#-MTjfI66ExRUdMU0U6ih:-MTlSemQ0W5aHn3Ot9Sq:b-wcbhfd) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a74e20cfd80726e34c55b25ecee7d673bd43c89/pkg/sql/execinfra/flow_context.go#L120)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: Could we do the inverse and create a sql instance ID from places where we have a nodeID?
</blockquote></details>

Sorry, I'm not sure I follow.. The TODO is saying that ComponentID should store SQLInstanceID, so that we would need to obtain or pass that instead of NodeID; this does mean that in some places, at least until all the SQLInstanceID plumbing is done, we'd need to create the sql instance ID from the node ID.
___
*[pkg/sql/flowinfra/outbox_test.go, line 570 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60550#-MTjfbptByciMYJ427bL:-MTlTwdXDHqQlttQjmMQ:b-vz6fie) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a74e20cfd80726e34c55b25ecee7d673bd43c89/pkg/sql/flowinfra/outbox_test.go#L570)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: maybe make a `TestingSQLIDContainer` function with no args that returns this to avoid repeating these calls
</blockquote></details>

Done, apparently there was already one defined :)

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60550)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto and @RaduBerinde)

___
*[pkg/sql/execinfra/flow_context.go, line 120 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60550#-MTjfI66ExRUdMU0U6ih:-MTotCig3wfUAyvRC1ZU:b-ihogeo) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a74e20cfd80726e34c55b25ecee7d673bd43c89/pkg/sql/execinfra/flow_context.go#L120)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Sorry, I'm not sure I follow.. The TODO is saying that ComponentID should store SQLInstanceID, so that we would need to obtain or pass that instead of NodeID; this does mean that in some places, at least until all the SQLInstanceID plumbing is done, we'd need to create the sql instance ID from the node ID.
</blockquote></details>

Sorry the thought wasn't complete. What I meant is that we could already make `ComponentID` store `SQLInstanceID` and instead of converting instance ids to node ids like we do here, convert node ids to instance ids in the other sites. Just a thought to make the future plumbing easier.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60550)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

___
*[pkg/sql/execinfra/flow_context.go, line 120 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60550#-MTjfI66ExRUdMU0U6ih:-MTqJa368TVyevxCUOBA:b-8xisk1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1a74e20cfd80726e34c55b25ecee7d673bd43c89/pkg/sql/execinfra/flow_context.go#L120)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Sorry the thought wasn't complete. What I meant is that we could already make `ComponentID` store `SQLInstanceID` and instead of converting instance ids to node ids like we do here, convert node ids to instance ids in the other sites. Just a thought to make the future plumbing easier.
</blockquote></details>

Oh, that's exactly what the TODO said. Done (as a separate commit).

**Pull request merged**
