### PR TITLE
changefeedccl: show topic name(s) for a created changefeed

### LINKED ISSUE #74468: cdc: show topic name(s) for a created changefeed
Due to special character escaping, the topic name isn't always obvious for a created changefeed, and the user often needs to immediately know it (e.g. to subscribe to the topic).
This could be a return value, a pgnotice, and/or a column in `SHOW CHANGEFEED JOBS`.

### PR DESCRIPTION
**Pull request by sherman-grewal**
changefeedccl: show topic name(s) for a created changefeed

Resolves #74468

Release note (enterprise change): Changefeeds will now
output the topic name(s) created by the Kafka sink.
Furthermore, these topic name(s) will be displayed in
the SHOW CHANGEFEED JOBS query.

### CODE REVIEW

**Review by sherman-grewal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75223)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @shermanCRL)

___
*[pkg/ccl/changefeedccl/show_changefeed_jobs_test.go, line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75223#-MttEhnWDr1NXgG1onAu:-MttEhnWDr1NXgG1onAv:ba5mxyb) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b36d0d11892efa5520fa4ab2a0922d4fb62ff4c/pkg/ccl/changefeedccl/show_changefeed_jobs_test.go#L119)):*
> ```Go
> 	sqlDB.QueryRow(t, query).Scan(&singleChangefeedID)
> 
> 	// Cannot use kafka for tests right now because of leaked goroutine issue
> ```

I was hoping to extend this test so that we can ensure that topic names are displayed in the SHOW CHANGEFEED JOB query for Kafka sinks, but I came across this comment in the test. Is this still an issue? If not, I could extend this test to also include Kafka sinks.

**Review by HonoreDB — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75223)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sherman-grewal and @shermanCRL)

___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 404 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75223#-MuCQzRZ-blZuVcufLT0:-MuCQzRZ-blZuVcufLT1:b-mo215v) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b36d0d11892efa5520fa4ab2a0922d4fb62ff4c/pkg/ccl/changefeedccl/changefeed_stmt.go#L404)):*
> ```Go
> 				var topics []string
> 				for _, topic := range sink.topics {
> 					p.BufferClientNotice(ctx, pgnotice.Newf(`topic %s created`, topic))
> ```

I think `changefeed will emit to topic %s` might be a bit clearer since for some Kafkas, there's a distinction between "creating" a topic and writing to an existing one, and we don't know yet which one we're doing.
___
*[pkg/ccl/changefeedccl/show_changefeed_jobs_test.go, line 119 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75223#-MttEhnWDr1NXgG1onAu:-MuCSmzt7X5kPIvL6iGU:b-ppp7mu) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b36d0d11892efa5520fa4ab2a0922d4fb62ff4c/pkg/ccl/changefeedccl/show_changefeed_jobs_test.go#L119)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

I have no idea what this comment means. It's definitely not true in general that we can't use Kafka for tests, there might be something specific to this test but that'd be weird.
</blockquote></details>

You can also use the `expectNotice` test helper function to test the pgnotice part; it'd be nice to confirm that the weird escaping shows up properly in this format (we have a few tests using a table whose name is the unicode snowman character).

**Review by sherman-grewal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75223)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @shermanCRL)

___
*[pkg/ccl/changefeedccl/changefeed_stmt.go, line 404 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75223#-MuCQzRZ-blZuVcufLT0:-MuIGGAh8XJ1JDmRLls5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b36d0d11892efa5520fa4ab2a0922d4fb62ff4c/pkg/ccl/changefeedccl/changefeed_stmt.go#L404)):*
<details><summary><i>Previously, HonoreDB (Aaron Zinger) wrote…</i></summary><blockquote>

I think `changefeed will emit to topic %s` might be a bit clearer since for some Kafkas, there's a distinction between "creating" a topic and writing to an existing one, and we don't know yet which one we're doing.
</blockquote></details>

Done.

**Review by HonoreDB — APPROVED** [review]
Thanks for the extra test coverage! Looks great.

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75223#-:-MuLyL6N6jammxHf3qt1:b-dc7ofa)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @shermanCRL)

**Review by HonoreDB — APPROVED** [review]
> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75223)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @HonoreDB and @shermanCRL)

**Pull request merged**
