### PR TITLE
colexec: fix vector unwrapping in merge joiner

### LINKED ISSUE #38994: exec: tracking issue for known logic tests failures for vectorize "experimental_on"
I ran logic tests on top of #38992 with vectorized set to "on." Here are the failures:
 - [x] #38919 (`explain_analyze`, `optimizer`, `subquery` files were skipped due to this issue)
 - [x] `aggregate` (#38858)
 - [x] `order_by`, `window`, `float`, `distinct_on`, `lookup_join`, `distsql_join`, `create_as` (#36880)
 - [x] `join` (#40371)
 - [x] `aggregate` (~#39240~)
 - [x] `select_index` (#38807)
 - [x] `ordinality` (#38995)
 - [x] `edge` (#38775)
 - [x] `postgresjoin`, `cascade`, and `cascade_opt` (#42670)
 - [x] #43269
 - [x] #43656

### LINKED ISSUE #43357: sql/logictest: TestLogic failed
[(sql/logictest).TestLogic failed](https://viewLog.html?buildId=1655563&tab=buildLog) on [master@47de313ba8c3026476ab928a3fa19f2c5b972191](https://github.com/cockroachdb/cockroach/commits/47de313ba8c3026476ab928a3fa19f2c5b972191):

```
=== RUN   TestLogic
--- FAIL: TestLogic (638.73s)
    test_log_scope.go:77: test logs captured to: /tmp/logTestLogic706898202
    test_log_scope.go:58: use -show-logs to present logs inline
=== RUN   TestLogic/fakedist-vec-off
    --- FAIL: TestLogic/fakedist-vec-off (0.82s)
=== RUN   TestLogic/fakedist-vec-off/schema_change_in_txn/delete_index_and_table_in_txn
rewrote:
CREATE TABLE x (a INT8 PRIMARY KEY, b INT8, c INT8 AS (b + 1) STORED, d INT8 AS (b - 1) STORED, FAMILY (c), FAMILY (d), FAMILY (b));


            --- FAIL: TestLogic/fakedist-vec-off/schema_change_in_txn/delete_index_and_table_in_txn (0.42s)
                logic.go:1891: 
                    
                    testdata/logic_test/schema_change_in_txn:1742: 
                    expected success, but found
                    (40001) restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE): "sql txn" meta={id=6d0062d3 key=/Table/SystemConfigSpan/Start pri=0.01281095 epo=0 ts=1576774383.185245872,1 min=1576774383.163685859,0 seq=29} rw=true stat=PENDING rts=1576774383.163685859,0 wto=false max=1576774383.163685859,0
                logic.go:1304: 
                     pq: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE): "sql txn" meta={id=6d0062d3 key=/Table/SystemConfigSpan/Start pri=0.01281095 epo=0 ts=1576774383.185245872,1 min=1576774383.163685859,0 seq=29} rw=true stat=PENDING rts=1576774383.163685859,0 wto=false max=1576774383.163685859,0
=== RUN   TestLogic/fakedist-vec-off/schema_change_in_txn
=== PAUSE TestLogic/fakedist-vec-off/schema_change_in_txn
=== CONT  TestLogic/fakedist-vec-off/schema_change_in_txn
        --- FAIL: TestLogic/fakedist-vec-off/schema_change_in_txn (31.37s)
```

<details><summary>Repro</summary><p>
Parameters:

- GOFLAGS=-json

```
make stressrace TESTS=TestLogic PKG=./pkg/sql/logictest TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: fix vector unwrapping in merge joiner**

Previously, merge joiner would check the width of the batch to
understand whether we have a source colvec to unwrap into its physical
representation (i.e. from coldata.Vec to []int64). This was added when
we introduced coldata.ZeroBatch. The assumption was that
coldata.ZeroBatch is never modified, so checking the width would have
been sufficient. However, as it turns out in some cases we are appending
columns to the zero batch, so its width is not a good indicator. This
commit switches to looking at the length of the batch to decide whether
there is anything to unwrap. The complication (and why we didn't use it
in the first place) is because merge joiner works with regular batches
and buffered batches, and the latter have length is uint64. Previously,
we would panic if Length() method was called on it. Now it is allowed,
but we have to be careful to use it only in a check whether buffered
batch is of zero length.

Fixes: #43357.

Release note: None

**sql: partial revert "sql: skip over a couple of logic tests"**

This partially reverts commit 912feef.
The ability to easily skip a logic test is kept.

Release note: None

**logictest: add vec on configs to default ones**

`srfs` logic test needed to be modified to become deterministic.

Fixes: #38994.

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44094)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/buffered_batch.go, line 44 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44094#-LylyCvlE2qfbd1F3t0e:-LylyCvlE2qfbd1F3t0f:b70tj1g) ([raw file](https://github.com/cockroachdb/cockroach/blob/f484174e681858c02b1702d1577f85361241e3dd/pkg/sql/colexec/buffered_batch.go#L44)):*
> ```Go
> // Length method should *only* be used to check whether the batch has a zero
> // length.
> func (b *bufferedBatch) Length() uint16 {
> ```

I was thinking that we should probably just change `coldata.Batch` interface to operate with `uint64` lengths, and then we can delete `bufferedBatch` entirely. In a separate PR, we - hopefully - will remove `selectionBatch`, so we'll have only `MemBatch` implementation with a special `zeroBatch` that prohibits calls to some of the functions.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1, 3 of 4 files at r2, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44094#-:-Lz7T42GBfx8_UEkobqD:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/buffered_batch.go, line 44 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44094#-LylyCvlE2qfbd1F3t0e:-Lz7S5HZ04Srw-wpfK_t:b-pbdqz3) ([raw file](https://github.com/cockroachdb/cockroach/blob/f484174e681858c02b1702d1577f85361241e3dd/pkg/sql/colexec/buffered_batch.go#L44)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I was thinking that we should probably just change `coldata.Batch` interface to operate with `uint64` lengths, and then we can delete `bufferedBatch` entirely. In a separate PR, we - hopefully - will remove `selectionBatch`, so we'll have only `MemBatch` implementation with a special `zeroBatch` that prohibits calls to some of the functions.
</blockquote></details>

Agreed.
___
*[pkg/sql/logictest/logic.go, line 1708 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44094#-Lz7SqzEAFCfANalT9TC:-Lz7SqzEAFCfANalT9TD:bs5o9us) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c7d75908f7aefb81637a2d0540d94d0efc27775/pkg/sql/logictest/logic.go#L1708)):*
> ```Go
> 			defer cleanupUserFunc()
> 
> 		case "skip":
> ```

It might be good to leave this in so that "skip" may be added to future tests that need to be skipped quickly.

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44094#-:-Lz8AKzX9Eq_IVEQHQGG:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/logictest/logic.go, line 1708 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/44094#-Lz7SqzEAFCfANalT9TC:-Lz8AGtFEBRDIdoCpk_N:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c7d75908f7aefb81637a2d0540d94d0efc27775/pkg/sql/logictest/logic.go#L1708)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

It might be good to leave this in so that "skip" may be added to future tests that need to be skipped quickly.
</blockquote></details>

Done.

**Comment by yuzefovich** [comment]
Flake #42558

bors r+

**Pull request merged**
