### PR TITLE
server,ccl: ldap authentication for db console

### LINKED ISSUE #129666: ldap: allow users to authenticate via LDAP to DB Console
We should extend ldap authentication to work with DB Console

Jira issue: CRDB-41654

Epic CRDB-33829

### PR DESCRIPTION
**Pull request by souravcrl**
server,ccl: ldap authentication for db console

fixes https://github.com/cockroachdb/cockroach/issues/129666
fixes CRDB-41654
Epic CRDB-33829

Currently, we lack the ability to perform LDAP based authentication for login
attempts for DB console. We already support password(SCRAM) based login for sql
passwords as credentials for DB console. We will extend the LDAP interfaces for
sql shell login to DB console in the PR.

Release note(enterprise, ui, security): A new LDAP authentication method has
been added to complement password based login for db console if HBA
configuration has an entry for LDAP for the user attempting login, along with
other matching criteria (like the requests originating IP address) for
authentication to db console.

### CODE REVIEW

**Comment by souravcrl** [comment]
Please review only the 2nd commit in the PR titled: `server,ccl: ldap authentication for db console` which corresponds to the issue https://github.com/cockroachdb/cockroach/issues/129666

**Review by pritesh-lahoti — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130418)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @souravcrl)

___
*[`pkg/server/server_sql.go` line 2161 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130418#-O6Wpd9P2ymzCaOZGPJo:-O6Wpd9P2ymzCaOZGPJp:b-o2l448) ([raw file](https://github.com/cockroachdb/cockroach/blob/989b11841dc9b32cedf916e4d60ae2b38931069b/pkg/server/server_sql.go#L2161)):*
> ```Go
> 
> // PgServer returns an pgwire server for accessing authentication interfaces.
> func (s *SQLServer) PgServer() *pgwire.Server {
> ```

Looks like this is redundant, in favor of `PGServer()`.
___
*[`pkg/server/authserver/authentication.go` line 162 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130418#-O6Ws7kCEzVq37vE98BP:-O6Ws7kCEzVq37vE98BQ:bxnon9h) ([raw file](https://github.com/cockroachdb/cockroach/blob/989b11841dc9b32cedf916e4d60ae2b38931069b/pkg/server/authserver/authentication.go#L162)):*
> ```Go
> 	hbaConf, identMap := s.sqlServer.PGServer().GetAuthenticationConfiguration()
> 
> 	authMethod, hbaEntry, _ := s.lookupAuthenticationMethodUsingRules(hba.ConnHostSSL, hbaConf, username, originIP)
> ```

Shouldn't we handle the error here?
___
*[`pkg/server/authserver/authentication.go` line 170 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130418#-O6WsYyE1Xlk7XF39d-w:-O6WsYyE1Xlk7XF39d-x:b-cod1jc) ([raw file](https://github.com/cockroachdb/cockroach/blob/989b11841dc9b32cedf916e4d60ae2b38931069b/pkg/server/authserver/authentication.go#L170)):*
> ```Go
> 		ldapManager.Do(func() {
> 			if ldapManager.m == nil {
> 				ldapManager.m = pgwire.ConfigureLDAPAuth(ctx, s.sqlServer.ExecutorConfig().AmbientCtx, s.sqlServer.ExecutorConfig().Settings, s.sqlServer.ExecutorConfig().NodeInfo.LogicalClusterID())
> ```

nit: could `s.sqlServer.ExecutorConfig()` be exported into a local var (say, `execCfg`), and then be reused throughout?



_Suggestion:_
```Go
execCfg.AmbientCtx
```
___
*[`pkg/server/authserver/authentication.go` line 489 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130418#-O6WrFB47k4EYtCbCDt6:-O6WrFB47k4EYtCbCDt7:bol9kpz) ([raw file](https://github.com/cockroachdb/cockroach/blob/989b11841dc9b32cedf916e4d60ae2b38931069b/pkg/server/authserver/authentication.go#L489)):*
> ```Go
> }
> 
> func (s *authenticationServer) lookupIncomingRequestOriginIP(ctx context.Context) net.IP {
> ```

Could we reuse `GetPublicPeerIP` within `pkg/utils/grpc.go` instead?

**Review by souravcrl — COMMENTED** [review]
PTAL. I have updated as per review comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130418#-:-O6_7lmg5ruRVRHuS8sb:b-uz0kql)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @pritesh-lahoti)

___
*[`pkg/server/server_sql.go` line 2161 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130418#-O6Wpd9P2ymzCaOZGPJo:-O6Zv7An4W_LLFD5S8Cv:b-xtt48b) ([raw file](https://github.com/cockroachdb/cockroach/blob/989b11841dc9b32cedf916e4d60ae2b38931069b/pkg/server/server_sql.go#L2161)):*
<details><summary><i>Previously, pritesh-lahoti wrote…</i></summary><blockquote>

Looks like this is redundant, in favor of `PGServer()`.
</blockquote></details>

updated to remove  the redundant function.
___
*[`pkg/server/authserver/authentication.go` line 162 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130418#-O6Ws7kCEzVq37vE98BP:-O6ZvDfg6uSMfjA90hkD:b10shd2) ([raw file](https://github.com/cockroachdb/cockroach/blob/989b11841dc9b32cedf916e4d60ae2b38931069b/pkg/server/authserver/authentication.go#L162)):*
<details><summary><i>Previously, pritesh-lahoti wrote…</i></summary><blockquote>

Shouldn't we handle the error here?
</blockquote></details>

handling error for HBA entry retrieval separately.
___
*[`pkg/server/authserver/authentication.go` line 170 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130418#-O6WsYyE1Xlk7XF39d-w:-O6ZvJyE8umrl2dXEZSe:b548yxj) ([raw file](https://github.com/cockroachdb/cockroach/blob/989b11841dc9b32cedf916e4d60ae2b38931069b/pkg/server/authserver/authentication.go#L170)):*
<details><summary><i>Previously, pritesh-lahoti wrote…</i></summary><blockquote>

nit: could `s.sqlServer.ExecutorConfig()` be exported into a local var (say, `execCfg`), and then be reused throughout?
</blockquote></details>

updated to use `execCfg` separately
___
*[`pkg/server/authserver/authentication.go` line 489 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130418#-O6WrFB47k4EYtCbCDt6:-O6_4CmTBA6zHCuO_Q_V:bu5bhzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/989b11841dc9b32cedf916e4d60ae2b38931069b/pkg/server/authserver/authentication.go#L489)):*
<details><summary><i>Previously, pritesh-lahoti wrote…</i></summary><blockquote>

Could we reuse `GetPublicPeerIP` within `pkg/utils/grpc.go` instead?
</blockquote></details>

This is not available here, part of `managed-service` utils: https://github.com/cockroachlabs/managed-service/blob/450666a6d34fe942560f93ff8f89091d00fd61fd/pkg/utils/grpc.go#L120

I have a basic implementation which looks for the `"x-forwarded-for"` tag in the ctx metadata and tries to reconstruct the IP. The utils implementation is more robust and handles more cases but would need us to add all of the logic. Added a TODO for this.

**Review by pritesh-lahoti — APPROVED** [review]
> Reviewed 6 of 6 files at r1, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130418)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @souravcrl)

___
*[`pkg/server/authserver/authentication.go` line 489 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130418#-O6WrFB47k4EYtCbCDt6:-O6_9by5D2w4eVaeUIOT:b-oq9dp) ([raw file](https://github.com/cockroachdb/cockroach/blob/989b11841dc9b32cedf916e4d60ae2b38931069b/pkg/server/authserver/authentication.go#L489)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

This is not available here, part of `managed-service` utils: https://github.com/cockroachlabs/managed-service/blob/450666a6d34fe942560f93ff8f89091d00fd61fd/pkg/utils/grpc.go#L120

I have a basic implementation which looks for the `"x-forwarded-for"` tag in the ctx metadata and tries to reconstruct the IP. The utils implementation is more robust and handles more cases but would need us to add all of the logic. Added a TODO for this.
</blockquote></details>

Ohh, looks like I was searching in the wrong window :-|
___
*[`pkg/server/authserver/authentication.go` line 501 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/130418#-O6_9v7899Ulk53oqeI4:-O6_9v7899Ulk53oqeI5:b2ni8l0) ([raw file](https://github.com/cockroachdb/cockroach/blob/08b5451ef817f280cf0b3073c216e0889d727c9e/pkg/server/authserver/authentication.go#L501)):*
> ```Go
> func (s *authenticationServer) lookupIncomingRequestOriginIP(ctx context.Context) net.IP {
> 	const XForwardedFor = "x-forwarded-for"
> 	const Localhost = "127.0.0.1"
> ```

nit



_Suggestion:_
```Go
	const xForwardedFor = "x-forwarded-for"
	const localhost = "127.0.0.1"
```

**Review by pritesh-lahoti — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130418)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @souravcrl)

___
*[`pkg/server/authserver/authentication.go` line 496 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/130418#-O6_AGUM-uM29daKKG_x:-O6_AGUM-uM29daKKG_y:b-edus56) ([raw file](https://github.com/cockroachdb/cockroach/blob/08b5451ef817f280cf0b3073c216e0889d727c9e/pkg/server/authserver/authentication.go#L496)):*
> ```Go
> // metadata, specifically looking for the `x-forwarded-for` tag.
> //
> // TODO(souravcrl): update the implementation to use managed-service util
> ```

Actually, we don't need the TODO to point to managed-service.

**Review by pritesh-lahoti — COMMENTED** [review]
The changes look good to me!

> Reviewed 2 of 3 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130418#-:-O6b0wz_9Zilll82ya_m:buta1jr)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @souravcrl)

**Review by dhartunian — APPROVED** [review]
:lgtm: just some minor comments from me.

> Reviewed 6 of 6 files at r1, 4 of 4 files at r3, 2 of 4 files at r4, 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130418#-:-O6cJqQM-zBI9BC131La:b-o6rug6)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @souravcrl)

___
*[`pkg/server/authserver/authentication.go` line 186 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/130418#-O6cCyDy96B7gP934go1:-O6cCyDy96B7gP934go2:byhe08y) ([raw file](https://github.com/cockroachdb/cockroach/blob/d35b9d683349b2240d9928754b48268166bc500b/pkg/server/authserver/authentication.go#L186)):*
> ```Go
> 		})
> 		ldapUserDN, detailedErrors, authError := ldapManager.m.FetchLDAPUserDN(ctx, execCfg.Settings, username, hbaEntry, identMap)
> 		if log.V(1) {
> ```

Is there a missing `authError != nil` here? It seems like otherwise we always log the message.
___
*[`pkg/server/authserver/authentication.go` line 191 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/130418#-O6cCylY7_-KGxvwwQ08:-O6cCylY7_-KGxvwwQ09:bd6obff) ([raw file](https://github.com/cockroachdb/cockroach/blob/d35b9d683349b2240d9928754b48268166bc500b/pkg/server/authserver/authentication.go#L191)):*
> ```Go
> 		if authError == nil {
> 			detailedErrors, authError = ldapManager.m.ValidateLDAPLogin(ctx, execCfg.Settings, ldapUserDN, username, req.Password, hbaEntry, identMap)
> 			if log.V(1) {
> ```

same here, check for non-nil error, I think even if verbosity is up, we don't want to imply there's an error in the logs.
___
*[`pkg/server/authserver/authentication.go` line 474 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/130418#-O6cEjUp7EnoHtDsLFYq:-O6cEjUp7EnoHtDsLFYr:bjccdza) ([raw file](https://github.com/cockroachdb/cockroach/blob/d35b9d683349b2240d9928754b48268166bc500b/pkg/server/authserver/authentication.go#L474)):*
> ```Go
> 	ctx context.Context, userName username.SQLUsername,
> ) (
> 	valid bool,
> ```

nit: `verified` since you use it everywhere else
___
*[`pkg/server/authserver/authentication_test.go` line 338 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/130418#-O6cBU6o9usm39pBeV7n:-O6cBU6o9usm39pBeV7o:b-w18ddn) ([raw file](https://github.com/cockroachdb/cockroach/blob/d35b9d683349b2240d9928754b48268166bc500b/pkg/server/authserver/authentication_test.go#L338)):*
> ```Go
> 						tc.shouldAuthenticate,
> 					)
> 				}
> ```

should there be a `t.Fatalf` if we return invalid?

**Review by souravcrl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130418)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian and @pritesh-lahoti)

___
*[`pkg/server/authserver/authentication.go` line 496 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/130418#-O6_AGUM-uM29daKKG_x:-O6dt2To-WLuHBcpRMw9:bsomrdz) ([raw file](https://github.com/cockroachdb/cockroach/blob/08b5451ef817f280cf0b3073c216e0889d727c9e/pkg/server/authserver/authentication.go#L496)):*
<details><summary><i>Previously, pritesh-lahoti wrote…</i></summary><blockquote>

Actually, we don't need the TODO to point to managed-service.
</blockquote></details>

I still feel the implementation might break if request comes in via load balancer and x-forwarded-for might contain other formats of client IP like
```
// X-Forwarded-For: <client-ip>,<load-balancer-ip>
// X-Forwarded-For: <supplied-value>,<client-ip>,<load-balancer-ip>
```
X-forwarded-for might also be missing when we need the X-real-ip tag for client IP address. Since the solution is for SH customers, this might not be important but I have added a TODO incase we want to take a look into this later.
___
*[`pkg/server/authserver/authentication.go` line 501 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/130418#-O6_9v7899Ulk53oqeI4:-O6duZBcCxes5tJrRLxL:b1n1pt0) ([raw file](https://github.com/cockroachdb/cockroach/blob/08b5451ef817f280cf0b3073c216e0889d727c9e/pkg/server/authserver/authentication.go#L501)):*
<details><summary><i>Previously, pritesh-lahoti wrote…</i></summary><blockquote>

nit
</blockquote></details>

updated  the constants.
___
*[`pkg/server/authserver/authentication.go` line 186 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/130418#-O6cCyDy96B7gP934go1:-O6dsH_23T1jkQ7DvE_9:b-mdg5tj) ([raw file](https://github.com/cockroachdb/cockroach/blob/d35b9d683349b2240d9928754b48268166bc500b/pkg/server/authserver/authentication.go#L186)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Is there a missing `authError != nil` here? It seems like otherwise we always log the message.
</blockquote></details>

added a condition around the log for `if authError != nil {`
___
*[`pkg/server/authserver/authentication.go` line 191 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/130418#-O6cCylY7_-KGxvwwQ08:-O6dsQYq1juvLYN_Tq1p:b9hix95) ([raw file](https://github.com/cockroachdb/cockroach/blob/d35b9d683349b2240d9928754b48268166bc500b/pkg/server/authserver/authentication.go#L191)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

same here, check for non-nil error, I think even if verbosity is up, we don't want to imply there's an error in the logs.
</blockquote></details>

addressed with a condition for logging, same as above
___
*[`pkg/server/authserver/authentication.go` line 474 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/130418#-O6cEjUp7EnoHtDsLFYq:-O6dsbZ0BYZ1xO1tEBIK:bjzjt8r) ([raw file](https://github.com/cockroachdb/cockroach/blob/d35b9d683349b2240d9928754b48268166bc500b/pkg/server/authserver/authentication.go#L474)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

nit: `verified` since you use it everywhere else
</blockquote></details>

updated to `verified`. VerifyPasswordDBConsole had a `valid` tag which was general purpose but I feel `verified` makes much more sense here.
___
*[`pkg/server/authserver/authentication_test.go` line 338 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/130418#-O6cBU6o9usm39pBeV7n:-O6dulGr2_kFiWeF2-wA:b-2arzi9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d35b9d683349b2240d9928754b48268166bc500b/pkg/server/authserver/authentication_test.go#L338)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

should there be a `t.Fatalf` if we return invalid?
</blockquote></details>

for `VerifyUserSessionDBConsole` invalid(verified = false) can mean sql.GetUserSessionInitInfo() did not return error but the user actually does not exist or cannot do DB console login ( canLoginDBConsole = false)

similarly for `VerifyPasswordDBConsole` invalid(valid=false) can mean password is expired other than being wrong password, for these case, we want to explicitly check if password is valid (not error and not expired) and whether this is consistent with test requirement that shouldAuthenticate value is as expected.

I have added some more validation to check for invalid credentials specifically which tests both both for invalid user which does not do DB console login or invalid(expired password) in line with the review comment.

**Review by pritesh-lahoti — COMMENTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130418)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian and @souravcrl)

___
*[`pkg/server/authserver/authentication.go` line 496 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/130418#-O6_AGUM-uM29daKKG_x:-O6e4xbO4trIG5DyaFdG:bt8ugtg) ([raw file](https://github.com/cockroachdb/cockroach/blob/08b5451ef817f280cf0b3073c216e0889d727c9e/pkg/server/authserver/authentication.go#L496)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

I still feel the implementation might break if request comes in via load balancer and x-forwarded-for might contain other formats of client IP like
```
// X-Forwarded-For: <client-ip>,<load-balancer-ip>
// X-Forwarded-For: <supplied-value>,<client-ip>,<load-balancer-ip>
```
X-forwarded-for might also be missing when we need the X-real-ip tag for client IP address. Since the solution is for SH customers, this might not be important but I have added a TODO incase we want to take a look into this later.
</blockquote></details>

Having a TODO is fine, but I don't think we need to point to managed-service (private repo) here.
___
*[`pkg/server/authserver/authentication_test.go` line 279 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/130418#-O6e6243EaijDMEJCybO:-O6e6243EaijDMEJCybP:brh5ji6) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2f8c20ca3d20db526a1bb4e7c4952e629c8fd4b/pkg/server/authserver/authentication_test.go#L279)):*
> ```Go
> 		username           string
> 		password           string
> 		invalidCredentials bool
> ```

Could we have done with `shouldAuthenticate` alone, as the value of `invalidCredentials` is always `!shouldAuthenticate`?

**Review by souravcrl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130418)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian and @pritesh-lahoti)

___
*[`pkg/server/authserver/authentication.go` line 496 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/130418#-O6_AGUM-uM29daKKG_x:-O6eyFyhDeZ1WVPXjYKO:b-kysjnd) ([raw file](https://github.com/cockroachdb/cockroach/blob/08b5451ef817f280cf0b3073c216e0889d727c9e/pkg/server/authserver/authentication.go#L496)):*
<details><summary><i>Previously, pritesh-lahoti wrote…</i></summary><blockquote>

Having a TODO is fine, but I don't think we need to point to managed-service (private repo) here.
</blockquote></details>

Removed the repo link from here and added in the details.
___
*[`pkg/server/authserver/authentication_test.go` line 279 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/130418#-O6e6243EaijDMEJCybO:-O6eyPMf3mKCJC8NsJmN:bax4ucd) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2f8c20ca3d20db526a1bb4e7c4952e629c8fd4b/pkg/server/authserver/authentication_test.go#L279)):*
<details><summary><i>Previously, pritesh-lahoti wrote…</i></summary><blockquote>

Could we have done with `shouldAuthenticate` alone, as the value of `invalidCredentials` is always `!shouldAuthenticate`?
</blockquote></details>

I realized I might have defined a tautology here, with invalidCredentials meaning exactly the same as !shouldAuthenticate. This is because of the design of the tests and there cannot be a case where credentials are valid but shouldAuthenticate is false and vice versa. I have hence updated my implementation to get rid of invalidCredentials test var.

**Review by pritesh-lahoti — APPROVED** [review]
I am guessing we plan to get to these TODOs sooner than later (at least before 24.3), so that we don't leave backlogs behind.

> Reviewed 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130418#-:-O6fBAtPCGfb-foA0_Nq:birlvak)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian)

**Pull request merged**
