### PR TITLE
sql: add waiting stmt info to transaction_contention_events

### PR DESCRIPTION
**Pull request by j82w**
This adds the 'waiting_stmt_id' and 'waiting_stmt_fingerprint_id' to the transaction_contention_events. This makes it easier for users to figure out what the issue is when dealing with large transactions.

part of: #91665

Release note: sql: adds the 'waiting_stmt_id' and
'waiting_stmt_fingerprint_id' to the transaction_contention_events

### CODE REVIEW

**Review by gtr — COMMENTED** [review]
> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95061)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @msirek)

___
*[`pkg/sql/contentionpb/contention.go` line 95 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95061#-NLWlBfZEeqQUFE8KmIj:-NLWlBf_D7yEh0iteoKe:b-95dcpo) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2ba04e597a49d3fc930e73d9b7bc6c37bf66e4b/pkg/sql/contentionpb/contention.go#L95)):*
> ```Go
> // since uint64 is 8-byte. This is why we decode the byte array twice and add
> // the resulting uint64 into the fnv each time.
> func hashClusterUniqueID(id clusterunique.ID, hash *util.FNV64) {
> ```

You might want to update the comment for this function. It looks like it was copied over from `hashUUID()`.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95061)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @msirek)

___
*[`-- commits` line 11 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95061#-NLWxu8uBcFaGHFKjF49):*
nit: the format should be `Release note (sql change): adds ...`. IIUC the format matters because we have an automated script that docs writers use to populate the release notes that we send out, and if a release note in the commit message doesn't match the expected format, then the docs writer will need to do more manual stuff.
___
*[`pkg/sql/crdb_internal.go` line 6348 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95061#-NLWyKTPE-Vj1qG9JVw2:-NLWyKTPE-Vj1qG9JVw3:bnzc93k) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b20035041f52c27c1989bd8cbe1d53a97c8b53a/pkg/sql/crdb_internal.go#L6348)):*
> ```Go
>     contention_duration          INTERVAL NOT NULL,
>     contending_key               BYTES NOT NULL,
>     
> ```

nit: looks like dangling spaces.

**Review by gtr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95061)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @msirek)

___
*[`pkg/sql/contentionpb/contention_test.go` line 19 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95061#-NLX1objEd4nOV-ZkYdK:-NLX1objEd4nOV-ZkYdL:b9k5z30) ([raw file](https://github.com/cockroachdb/cockroach/blob/3b20035041f52c27c1989bd8cbe1d53a97c8b53a/pkg/sql/contentionpb/contention_test.go#L19)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/util/uuid"
> 	"github.com/stretchr/testify/require"
> 	"testing"
> ```

nit: Re-order "testing" import to the top of import list.

**Review by msirek — COMMENTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95061)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w)

___
*[`pkg/sql/contentionpb/contention.go` line 93 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95061#-NLadPLLD5sKWpf02os0:-NLadPLM7oxpDazjDHOl:b-jfyaac) ([raw file](https://github.com/cockroachdb/cockroach/blob/988b6f961867d1e3c7b366c0039fa759daf858c9/pkg/sql/contentionpb/contention.go#L93)):*
> ```Go
> // hashClusterUniqueID adds the hash of the clusterunique.ID into the fnv.
> // A clusterunique.ID is an uint128. To hash we treat it as two uint64 integers,
> // since uint128 is has a lo and hi uint64.
> ```

"since uint128 is has" -> "since uint128 has"

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 2 of 6 files at r1, 3 of 4 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95061#-:-NM4kJwA2zc736YksAJv:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @j82w)

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95061)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @gtr, @j82w, @maryliag, @msirek, and @yuzefovich)

___
*[`-- commits` line 11 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95061#-NLWxu8uBcFaGHFKjF49):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: the format should be `Release note (sql change): adds ...`. IIUC the format matters because we have an automated script that docs writers use to populate the release notes that we send out, and if a release note in the commit message doesn't match the expected format, then the docs writer will need to do more manual stuff.
</blockquote></details>

Also, if you are to have a release note, please make it a fuller sentence that a user can understand and make use of.
I would not add a note.
___
*[`-- commits` line 4 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/95061#-NMAF7ZGBaK-TsI7Ti4x):*
what's the difference between a statement ID and a fingerprint ID ?
___
*[`pkg/sql/clusterunique/id.go` line 96 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/95061#-NMAFdlz1gMKfksLdlXh:-NMAFdlz1gMKfksLdlXi:b6t4vyk) ([raw file](https://github.com/cockroachdb/cockroach/blob/2805a5cea315ee6907394013f6b3cc58e62f55e7/pkg/sql/clusterunique/id.go#L96)):*
> ```Go
> 		return err
> 	}
> 	id.Hi = uint128.Hi
> ```

`*id.Uint128 = uint128` ?

**Comment by j82w** [comment]
*[`-- commits` line 4 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/95061#-NMAF7ZGBaK-TsI7Ti4x):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

what's the difference between a statement ID and a fingerprint ID ?
</blockquote></details>

A statement fingerprint represents one or more SQL statements by replacing literal values (e.g., numbers and strings) with underscores (_). This can help you quickly identify frequently executed SQL statements and their latencies. https://www.cockroachlabs.com/docs/stable/ui-statements-page.html#sql-statement-fingerprints

Statement ID is a unique identifier for the specific statement execution.

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95061)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @gtr, @j82w, @maryliag, and @yuzefovich)

___
*[`pkg/sql/crdb_internal_test.go` line 1002 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/95061#-NMaqdqm5hYYEz_yG6kU:-NMaqdqm5hYYEz_yG6kV:b-hm113m) ([raw file](https://github.com/cockroachdb/cockroach/blob/2805a5cea315ee6907394013f6b3cc58e62f55e7/pkg/sql/crdb_internal_test.go#L1002)):*
> ```Go
> 			const defaultIdString = "0x0000000000000000"
> 			if blockingTxnId == defaultIdString {
> 				return fmt.Errorf("transaction_contention_events had default txn id %s, waiting txn id %s", blockingTxnId, waitingTxnId)
> ```

Change to: "transaction_contention_events had default blocking txn id..."

**Review by j82w — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95061)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei, @gtr, @maryliag, @msirek, and @yuzefovich)

___
*[`-- commits` line 11 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/95061#-NLWxu8uBcFaGHFKjF49):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Also, if you are to have a release note, please make it a fuller sentence that a user can understand and make use of.
I would not add a note.

</blockquote></details>

I removed the note as suggested.
___
*[`pkg/sql/clusterunique/id.go` line 96 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/95061#-NMAFdlz1gMKfksLdlXh:-NMjUa0X0MBPFTR_32Q3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2805a5cea315ee6907394013f6b3cc58e62f55e7/pkg/sql/clusterunique/id.go#L96)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

`*id.Uint128 = uint128` ?
</blockquote></details>

Done.
___
*[`pkg/sql/contentionpb/contention.go` line 95 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/95061#-NLWlBfZEeqQUFE8KmIj:-NLXRuusEiThrTveCIdF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2ba04e597a49d3fc930e73d9b7bc6c37bf66e4b/pkg/sql/contentionpb/contention.go#L95)):*
<details><summary><i>Previously, gtr (Gerardo Torres Castro) wrote…</i></summary><blockquote>

You might want to update the comment for this function. It looks like it was copied over from `hashUUID()`.
</blockquote></details>

Done.
___
*[`pkg/sql/contentionpb/contention.go` line 93 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/95061#-NLadPLLD5sKWpf02os0:-NMjO1m5-2xBujPjn05r:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/988b6f961867d1e3c7b366c0039fa759daf858c9/pkg/sql/contentionpb/contention.go#L93)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

"since uint128 is has" -> "since uint128 has"
</blockquote></details>

Done.
___
*[`pkg/sql/crdb_internal_test.go` line 1002 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/95061#-NMaqdqm5hYYEz_yG6kU:-NMjUTHBCQqyWyjKeaeC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2805a5cea315ee6907394013f6b3cc58e62f55e7/pkg/sql/crdb_internal_test.go#L1002)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Change to: "transaction_contention_events had default blocking txn id..."
</blockquote></details>

Done.

**Pull request merged**
