### PR TITLE
storage: remove obsolete encryption-at-rest code

### LINKED ISSUE #72520: storage: remove monolith encryption-at-rest registry
The 21.2 release introduced an incremental file registry format to replace the previous registry file that stored a single `FileRegistry` protocol buffer. When the 21.2 cluster version is finalized, the incremental file registry becomes the source of truth and the old registry may be deleted. In the 22.1 release cycle, we should remove all the code for managing the old, obsolete registry format and managing the upgrade process to the incremental file registry.

### PR DESCRIPTION
**Pull request by jbowens**
Remove encryption-at-rest code that handles the upgrade process to the 21.2
encryption-at-rest formats and all code that reads the 21.1 and earlier
formats.

Fix #72520.

Release note: None

### CODE REVIEW

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74314)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/pebble_file_registry.go, line 397 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74314#-Ms6qxfEE4wvB33IZhHO:-Ms6qxfEE4wvB33IZhHP:b-yopoyw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a56b813d6c313c1d645cabd2b062bf23eeff0b94/pkg/storage/pebble_file_registry.go#L397)):*
> ```Go
> 			}
> 			r.mu.entries[update.Filename] = update.Entry
> 		}
> ```

This logic is moved from the `enginepb.FileRegistry` type, because we no longer need the indirection of holding a `enginepb.FileRegistry` on `PebbleFileRegistry`. Instead we maintain just the `map[string]*enginepb.FileEntry` map directly.

**Comment by jbowens** [comment]
Will need to rebase once #74270 lands.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

I didn't look carefully at the testdata files

> Reviewed 6 of 14 files at r1, 1 of 5 files at r2, 9 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74314#-:-MuqfZ7e4EHqIzjzMeqb:b-lna5wb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal and @jbowens)

___
*[pkg/ccl/storageccl/engineccl/pebble_key_manager.go, line 239 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74314#-MuqcrRo5BK_1vyvdX8q:-MuqcrRo5BK_1vyvdX8r:b3fezg6) ([raw file](https://github.com/cockroachdb/cockroach/blob/999ab85a7f0e7a1cbf3bab3422bbe6e256956c3d/pkg/ccl/storageccl/engineccl/pebble_key_manager.go#L239)):*
> ```Go
> 			return err
> 		}
> 	}
> ```

// Else there is no DataKeysRegistry file yet.
___
*[pkg/storage/pebble_file_registry.go, line 397 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74314#-Ms6qxfEE4wvB33IZhHO:-MuqePNlEcOACoTUxsgY:b2nhysk) ([raw file](https://github.com/cockroachdb/cockroach/blob/a56b813d6c313c1d645cabd2b062bf23eeff0b94/pkg/storage/pebble_file_registry.go#L397)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

This logic is moved from the `enginepb.FileRegistry` type, because we no longer need the indirection of holding a `enginepb.FileRegistry` on `PebbleFileRegistry`. Instead we maintain just the `map[string]*enginepb.FileEntry` map directly.
</blockquote></details>

ack

**Review by jbowens — COMMENTED** [review]
TFTR!

bors r=sumeerbhola

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74314#-:-Mv-NkrL6tq0rorJZkVB:b-6zs9ju)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @itsbilal, @jbowens, and @sumeerbhola)

___
*[pkg/ccl/storageccl/engineccl/pebble_key_manager.go, line 239 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/74314#-MuqcrRo5BK_1vyvdX8q:-Mv-Njwf6EgZBamp516o:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/999ab85a7f0e7a1cbf3bab3422bbe6e256956c3d/pkg/ccl/storageccl/engineccl/pebble_key_manager.go#L239)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

// Else there is no DataKeysRegistry file yet.
</blockquote></details>

Done.

**Pull request merged**
