### PR TITLE
storage: Write HardState atomically with committing splits

### LINKED ISSUE #20494: jepsen: `PSQLException: The connection attempt failed` `Caused by: java.io.EOFException: null`
```
[12:29:44][/subcritical-skews+start-kill-2] ERROR [2017-11-21 12:29:43,623] main - jepsen.cli Oh jeez, I'm sorry, Jepsen broke. Here's why:
[12:29:44][/subcritical-skews+start-kill-2] org.postgresql.util.PSQLException: The connection attempt failed.
[12:29:44][/subcritical-skews+start-kill-2] 	at org.postgresql.Driver$ConnectThread.getResult(Driver.java:358) ~[postgresql-9.4.1211.jar:9.4.1211]
[12:29:44][/subcritical-skews+start-kill-2] 	at org.postgresql.Driver.connect(Driver.java:282) ~[postgresql-9.4.1211.jar:9.4.1211]
[12:29:44][/subcritical-skews+start-kill-2] 	at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[na:1.8.0_151]
[12:29:44][/subcritical-skews+start-kill-2] 	at java.sql.DriverManager.getConnection(DriverManager.java:208) ~[na:1.8.0_151]
[12:29:44][/subcritical-skews+start-kill-2] 	at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:272) ~[classes/:na]
[12:29:44][/subcritical-skews+start-kill-2] 	at clojure.java.jdbc$get_connection.invoke(jdbc.clj:193) ~[classes/:na]
[12:29:44][/subcritical-skews+start-kill-2] 	at jepsen.cockroach.client$client$open__1314$fn__1315.invoke(client.clj:90) ~[classes/:na]
[12:29:44][/subcritical-skews+start-kill-2] 	at clojure.core$binding_conveyor_fn$fn__4676.invoke(core.clj:1938) ~[clojure-1.8.0.jar:na]
[12:29:44][/subcritical-skews+start-kill-2] 	at clojure.lang.AFn.call(AFn.java:18) ~[clojure-1.8.0.jar:na]
[12:29:44][/subcritical-skews+start-kill-2] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_151]
[12:29:44][/subcritical-skews+start-kill-2] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_151]
[12:29:44][/subcritical-skews+start-kill-2] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_151]
[12:29:44][/subcritical-skews+start-kill-2] 	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]
[12:29:44][/subcritical-skews+start-kill-2] Caused by: java.io.EOFException: null
[12:29:44][/subcritical-skews+start-kill-2] 	at org.postgresql.core.PGStream.receiveChar(PGStream.java:285) ~[postgresql-9.4.1211.jar:9.4.1211]
[12:29:44][/subcritical-skews+start-kill-2] 	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:424) ~[postgresql-9.4.1211.jar:9.4.1211]
[12:29:44][/subcritical-skews+start-kill-2] 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:220) ~[postgresql-9.4.1211.jar:9.4.1211]
[12:29:44][/subcritical-skews+start-kill-2] 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:55) ~[postgresql-9.4.1211.jar:9.4.1211]
[12:29:44][/subcritical-skews+start-kill-2] 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:219) ~[postgresql-9.4.1211.jar:9.4.1211]
[12:29:44][/subcritical-skews+start-kill-2] 	at org.postgresql.Driver.makeConnection(Driver.java:407) ~[postgresql-9.4.1211.jar:9.4.1211]
[12:29:44][/subcritical-skews+start-kill-2] 	at org.postgresql.Driver.access$100(Driver.java:55) ~[postgresql-9.4.1211.jar:9.4.1211]
[12:29:44][/subcritical-skews+start-kill-2] 	at org.postgresql.Driver$ConnectThread.run(Driver.java:317) ~[postgresql-9.4.1211.jar:9.4.1211]
[12:29:44][/subcritical-skews+start-kill-2] 	... 1 common frames omitted
```

### LINKED ISSUE #20629: storage: panic in `raft.campaign`
From #20494 (this has been seen in jepsen runs with multiple nemeses including strobe-skews and majority-ring):

```
W171209 08:51:50.342206 413 storage/replica_range_lease.go:418  can't determine lease status due to node liveness error: node not in the liveness table
W171209 08:51:50.518491 102 storage/store.go:1289  [n1,s1,r7/1:/Table/{SystemCon…-11}] could not gossip system config: [NotLeaseHolderError] r7: replica (n1,s1):1 not lease holder; lease holder unknown
E171209 08:51:51.089407 472 util/log/crash_reporting.go:119  [n1,s1,r31/1:/{Table/50-Max}] a panic has occurred!
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1261959]

goroutine 472 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc42076a2d0, 0x312fb00, 0xc425724380)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:181 +0x136
panic(0x1e890a0, 0x30e36f0)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*Progress).maybeUpdate(...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/progress.go:116
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*raft).appendEntry(0xc4207523c0, 0xc4256ee5a0, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go:547 +0xd9
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*raft).becomeLeader(0xc4207523c0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go:648 +0x287
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*raft).campaign(0xc4207523c0, 0x20d5e4a, 0x10)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go:671 +0x668
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*raft).Step(0xc4207523c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go:783 +0x33a
github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*RawNode).Campaign(0xc4256fc2c0, 0xc420496d80, 0x3)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/rawnode.go:140 +0x71
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).withRaftGroupLocked(0xc420161b00, 0x14fe9438e254d601, 0x21b2a38, 0x0, 0x200000002)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:594 +0x38e
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).maybeInitializeRaftGroup(0xc420161b00, 0x312fbc0, 0xc4256e93b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1849 +0x185
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).Send(0xc420161b00, 0x312fbc0, 0xc4256e93b0, 0x14fe943c314d23c9, 0x0, 0x0, 0x0, 0x1f, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1873 +0x136
github.com/cockroachdb/cockroach/pkg/storage.(*pendingLeaseRequest).requestLeaseAsync.func2(0x312fb00, 0xc425724380)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_range_lease.go:274 +0x577
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc42076a2d0, 0x312fb00, 0xc425724380, 0xc4207d0500, 0x35, 0x0, 0x0, 0xc4207b9b80)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:267 +0xe6
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:262 +0x133
```

### PR DESCRIPTION
**Pull request by bdarnell**
Prior to this change, an ill-timed crash (between applying the raft
command and calling splitPostApply) would leave the replica in a
persistently broken state (no HardState).

Found via jepsen.

Fixes #20629
Fixes #20494

Release note (bugfix): Fixed a replica corruption that could occur if
a process crashed in the middle of a range split.

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica.go, line 4615 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20704#-L0LC8YB3Qcma-FW07xd:-L0LC8YB3Qcma-FW07xe:bg87q71) ([raw file](https://github.com/cockroachdb/cockroach/blob/8496576fffe389228dedbe70782108986c325bbe/pkg/storage/replica.go#L4615)):*
> ```Go
> 			// on each replica (votes may have already been cast on the
> 			// uninitialized replica). Transform the write batch to add the
> 			// updated HardState.
> ```

Consider linking to the issue here.

---

*[pkg/storage/replica.go, line 4616 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20704#-L0LC46ylx9fdelOBqRa:-L0LC46ylx9fdelOBqRb:b67rtpe) ([raw file](https://github.com/cockroachdb/cockroach/blob/8496576fffe389228dedbe70782108986c325bbe/pkg/storage/replica.go#L4616)):*
> ```Go
> 			// uninitialized replica). Transform the write batch to add the
> 			// updated HardState.
> 			tmpBatch := r.store.engine.NewBatch()
> ```

Would using `NewWriteOnlyBatch` make a difference here?

---

*[pkg/storage/replica.go, line 4617 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20704#-L0LBiz0OIAn9NPic5eL:-L0LBiz1XRLSg_34qDLy:b-w2p062) ([raw file](https://github.com/cockroachdb/cockroach/blob/8496576fffe389228dedbe70782108986c325bbe/pkg/storage/replica.go#L4617)):*
> ```Go
> 			// updated HardState.
> 			tmpBatch := r.store.engine.NewBatch()
> 			if err := tmpBatch.ApplyBatchRepr(writeBatch.Data, false); err != nil {
> ```

Is there any performance concern with this `BatchRepr` copy? This is only done on splits, so probably not.

---

*[pkg/storage/store.go, line 1801 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20704#-L0LAu9fhVk496ivZJyj:-L0LAu9fhVk496ivZJyk:bccinj8) ([raw file](https://github.com/cockroachdb/cockroach/blob/8496576fffe389228dedbe70782108986c325bbe/pkg/storage/store.go#L1801)):*
> ```Go
> }
> 
> // splitPreApply is called when the raft command is applied. Any
> ```

Is there a reason why these functions are in `store.go` instead of with the other pre and post apply functions in `replica_proposal.go`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20704)*

**Comment by bdarnell** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/storage/replica.go, line 4615 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20704#-L0LC8YB3Qcma-FW07xd:-L0LEU37tQKTa28k_FUo:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/8496576fffe389228dedbe70782108986c325bbe/pkg/storage/replica.go#L4615)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Consider linking to the issue here.
</blockquote></details>

Done

---

*[pkg/storage/replica.go, line 4616 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20704#-L0LC46ylx9fdelOBqRa:-L0LEUocmHpATh_mB6In:b-jpnx5k) ([raw file](https://github.com/cockroachdb/cockroach/blob/8496576fffe389228dedbe70782108986c325bbe/pkg/storage/replica.go#L4616)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Would using `NewWriteOnlyBatch` make a difference here?
</blockquote></details>

Perhaps, but that means encoding knowledge-at-a-distance that splitPreApply doesn't need to read anything else that may have been written in the batch.

---

*[pkg/storage/replica.go, line 4617 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20704#-L0LBiz0OIAn9NPic5eL:-L0LEpibH03x4Zi_iCFr:bqtuoam) ([raw file](https://github.com/cockroachdb/cockroach/blob/8496576fffe389228dedbe70782108986c325bbe/pkg/storage/replica.go#L4617)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is there any performance concern with this `BatchRepr` copy? This is only done on splits, so probably not.
</blockquote></details>

Yeah, splits are uncommon enough (and small enough) that I'm not concerned. Added a comment.

---

*[pkg/storage/store.go, line 1801 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20704#-L0LAu9fhVk496ivZJyj:-L0LEw3IPvOJqdmcp0Sg:b-io5ti9) ([raw file](https://github.com/cockroachdb/cockroach/blob/8496576fffe389228dedbe70782108986c325bbe/pkg/storage/store.go#L1801)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is there a reason why these functions are in `store.go` instead of with the other pre and post apply functions in `replica_proposal.go`?
</blockquote></details>

Historical reasons (and adjacency with Store.SplitRange, from which splitPostApply was extracted). I figure we'll gather all the split-related code into one place as a part of #18779. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20704)*

**Comment by nvanbenschoten** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20704#-:-L0LZfpSRzcetVpWrS8d:bnfp4nl)*

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/replica.go, line 33 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/20704#-L0QzdeWljdIsF72l4av:-L0QzdeX92zannfBpDSB:b-d3u4i7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2b0f7b777345fd55ae78e102d675def9354fe06/pkg/storage/replica.go#L33)):*
> ```Go
> 	"github.com/google/btree"
> 	"github.com/kr/pretty"
> 	opentracing "github.com/opentracing/opentracing-go"
> ```

I remember having that problem back when I used `vim`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20704#-:-L0QzgyirZKcvW8il6gU:bnfp4nl)*

**Pull request merged**
