### PR TITLE
util/log: report log flushes and TLS rotations on the ops channels

### LINKED ISSUE #57889: server: file operational notable events for TLS cert rotations
Today it is not easy to recognize in logs when TLS certificates are rotated as a side effect of sending a signal to a server.

To ensure that cert rotation is visible to an external IDS, we need to introduce structured events for this case.

cc @aaron-crl @thtruo

### PR DESCRIPTION
**Pull request by knz**
Fixes #57889.

Release note (cli change): the notification that SIGHUP was received
and that log files are flushed to disk as a result, is now sent to the
OPS logging channel.

Release note (cli change): the notification that SIGHUP was received
and that TLS certificates are reloaded from disk as a result, is now
sent to the OPS logging channel as a structured event. Refer to the
reference docs for details about the event payload.

### CODE REVIEW

**Comment by knz** [comment]
@aaron-crl would like you to review this one.

cc @thtruo

**Comment by knz** [comment]
friendly ping to the reviewers

**Review by aaron-crl — APPROVED** [review]
Minor nit on test, otherwise :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59345#-:-MSF8DN-DqMQSHgNCn1-:b-awjo94)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal and @knz)

___
*[pkg/security/certs_rotation_test.go, line 192 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59345#-MSF7CpyBlWAdHFP03T4:-MSF7CpyBlWAdHFP03T5:b-25g946) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d40438292d184ea1102414f971b0d5d40b75e2f/pkg/security/certs_rotation_test.go#L192)):*
> ```Go
> 	log.Flush()
> 	entries, err := log.FetchEntriesFromFiles(beforeReload.UnixNano(),
> 		math.MaxInt64, 10000, cmLogRe, log.WithMarkedSensitiveData)
> ```

Apologies if this is an ignorant question but I don't have a good grasp of our test infrastructure.

Is there any (reasonable) chance this test will flake? I recall a conversation recently about testing in parallel and I'm not sure if we might hammer the same log from another test?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59345)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aaron-crl and @itsbilal)

___
*[pkg/security/certs_rotation_test.go, line 192 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59345#-MSF7CpyBlWAdHFP03T4:-MSRws7DEc5VUNheLhXn:b-jt3nu8) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d40438292d184ea1102414f971b0d5d40b75e2f/pkg/security/certs_rotation_test.go#L192)):*
<details><summary><i>Previously, aaron-crl wrote…</i></summary><blockquote>

Apologies if this is an ignorant question but I don't have a good grasp of our test infrastructure.

Is there any (reasonable) chance this test will flake? I recall a conversation recently about testing in parallel and I'm not sure if we might hammer the same log from another test?
</blockquote></details>

It's a good question, you're probably one of the 10000 today.

Go's test runner only run tests concurrently that have opted into it by calling `t.Parallel()`; and then these tests only run concurrently with each other. So a test that did not opt in is guaranteed to not overlap with other tests.

FWIW we have quite a few other tests that use this pattern: log.Flush, FetchEntriesFromFiles, assert entries.

**Comment by knz** [comment]
bors r=aaron-crl

**Comment by aaron-crl** [comment]
> Go's test runner only run tests concurrently that have opted into it by calling t.Parallel(); and then these tests only run concurrently with each other. So a test that did not opt in is guaranteed to not overlap with other tests.

> FWIW we have quite a few other tests that use this pattern: log.Flush, FetchEntriesFromFiles, assert entries.

Thanks for the explanation!

**Comment by knz** [comment]
bors r=aaron-crl

**Pull request merged**
