### PR TITLE
kv/storage: expose metrics on asynchronous concurrency limits

### LINKED ISSUE #26841: kv/storage: expose metrics on asynchronous concurrency limits
Uses of [`RunLimitedAsyncTask`](https://github.com/cockroachdb/cockroach/blob/b21c8ef22ec0227d1f42d0f56d2273a4ef0ab947/pkg/util/stop/stopper.go#L270) specify a bounded amount of concurrency permitted before they begin running tasks synchronously. This introduces a form of non-linear behavior where all operations will hit the asynchronous path until a cluster reaches a certain threshold of concurrent load. Once this threshold is reached, all additional load will begin running the tasks synchronously. It's likely that this has implications on the graceful degredation of a cluster's performance.

We should expose metrics for the percentage of requests across a node that succesfully hit the asynchronous path for each of these tasks. The most important of these are [parallel DistSender transmission](https://github.com/cockroachdb/cockroach/blob/b21c8ef22ec0227d1f42d0f56d2273a4ef0ab947/pkg/kv/dist_sender.go#L916) and [asynchronous intent resolution](https://github.com/cockroachdb/cockroach/blob/b21c8ef22ec0227d1f42d0f56d2273a4ef0ab947/pkg/storage/intent_resolver.go#L608).

### PR DESCRIPTION
**Pull request by nvb**
Fixes #26841.

This change creates three new metrics:
- `distsender.batches.async.sent`
- `distsender.batches.async.throttled`
- `intentresolver.async.throttled`

The first two will allow us to track the number of batches sent asynchronously
through DistSender, along with the number of failed attempts to send
a batch asynchronously due to throttling.

The last will allow us to track the number of intent resolution attempts
that fell back to performing resolution synchronously due to throttling.

### CODE REVIEW

**Comment by tschottdorf** [comment]
:lgtm: curious to see whether the throttled ones fire in the 16core perf degradation.

---

Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/kv/dist_sender.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26903#-LFaaAFg5KN83c3Z6qmN:-LFaaAFh4oWlRN0aK0DQ:b-wsycoa) ([raw file](https://github.com/cockroachdb/cockroach/blob/815db54c65e7284d7c0c2a331fc17741bb4a928a/pkg/kv/dist_sender.go#L52)):*
> ```Go
> 	metaDistSenderPartialBatchCount = metric.Metadata{
> 		Name: "distsender.batches.partial",
> 		Help: "Number of partial batches processed"}
> ```

While you're here.. I've always felt this explanation lacking.

---

*[pkg/storage/intent_resolver.go, line 620 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26903#-LFaaOKU01EUnYzG_l3_:-LFaaOKU01EUnYzG_l3a:bajzy39) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7ee3e0cfe30d8370eba503812d17e05a83d5688/pkg/storage/intent_resolver.go#L620)):*
> ```Go
> 		// A limited task was not available. Rather than waiting for one, we
> 		// reuse the current goroutine.
> 		ir.store.metrics.IntentResolverAsyncThrottled.Inc(1)
> ```

Shouldn't you do this regardless of the value of `allowSyncProcessing`?

---

*[pkg/storage/metrics.go, line 463 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26903#-LFaaUCK-uDr2qC0BzaU:-LFaaUCL1I96ITcOHCrj:b-tiv4ed) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7ee3e0cfe30d8370eba503812d17e05a83d5688/pkg/storage/metrics.go#L463)):*
> ```Go
> 	metaIntentResolverAsyncThrottled = metric.Metadata{
> 		Name: "intents.resolver.async.throttled",
> 		Help: "Number of intent resolution attempts that were run synchronously"}
> ```

Why not establish parity with the distsender sibling? "... that were not run asynchronously".

Also not sure about `intents.resolver` vs `distsender`. I'd just `intentresolver` this.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26903#-:-LFaaq647LN0PdaWwb_y:bqmx0r3)*

**Comment by nvanbenschoten** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/kv/dist_sender.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26903#-LFaaAFg5KN83c3Z6qmN:-LFuA2dP2jciE8izhAWv:b8xh2ij) ([raw file](https://github.com/cockroachdb/cockroach/blob/815db54c65e7284d7c0c2a331fc17741bb4a928a/pkg/kv/dist_sender.go#L52)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

While you're here.. I've always felt this explanation lacking.
</blockquote></details>

Done. How's that?

---

*[pkg/storage/intent_resolver.go, line 620 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26903#-LFaaOKU01EUnYzG_l3_:-LFuCIXY30Rnf0wXIag_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7ee3e0cfe30d8370eba503812d17e05a83d5688/pkg/storage/intent_resolver.go#L620)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Shouldn't you do this regardless of the value of `allowSyncProcessing`?
</blockquote></details>

Done.

---

*[pkg/storage/metrics.go, line 463 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26903#-LFaaUCK-uDr2qC0BzaU:-LFuAe8F3ra1KuH_UacB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7ee3e0cfe30d8370eba503812d17e05a83d5688/pkg/storage/metrics.go#L463)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Why not establish parity with the distsender sibling? "... that were not run asynchronously".

Also not sure about `intents.resolver` vs `distsender`. I'd just `intentresolver` this.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26903)*

**Comment by tschottdorf** [comment]
Reviewed 3 of 3 files at r3, 2 of 2 files at r4.
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26903)*

**Pull request merged**
