### PR TITLE
roachtest: add mixed version test for RAC

### PR DESCRIPTION
**Pull request by pav-kv**
The test exercises RACv1 and v2 behaviours in a mixed-version cluster, and after the upgrade is finalized.

Part of #132778

### CODE REVIEW

**Review by kvoli — APPROVED** [review]
:lgtm: -- See comment about moving the splits to init, I don't feel strongly enough about the suggestion to request changes, however it would be preferable.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134014#-:-OA_0uL11MwPU7GWSDyp:bcjber4)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist, @herkolategan, @pav-kv, @sumeerbhola, and @vidit-bhat)

___
*[`pkg/cmd/roachtest/tests/admission_control_mixed_version.go` line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134014#-OAZzaci1pSQpipggOQp:-OAZzacj9EuhBjRkv1Y6:b-kvxckz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b931e811be08de282566e23bedb2dcffd440262/pkg/cmd/roachtest/tests/admission_control_mixed_version.go#L35)):*
> ```Go
> // used bandwidth much higher than the provisioned one, AC paces the traffic at
> // the set bandwidth limit, and favours regular writes. This behaviour does not
> // regress after the cluster is upgraded to v24.3.
> ```

Rather concise and precise.
___
*[`pkg/cmd/roachtest/tests/admission_control_mixed_version.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134014#-OAZzlp3APscnOt73WgU:-OAZzlp3APscnOt73WgV:blned14) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b931e811be08de282566e23bedb2dcffd440262/pkg/cmd/roachtest/tests/admission_control_mixed_version.go#L38)):*
> ```Go
> func registerAdmissionMixedVersion(r registry.Registry) {
> 	r.Add(registry.TestSpec{
> 		Name:             "admission-control/mixed-version",
> ```

nit: we could do this later, however mapping the test name will be a pain, consider adding `.../elastic-workload`.
___
*[`pkg/cmd/roachtest/tests/admission_control_mixed_version.go` line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134014#-OA_02e4EvXZHyTkoUfl:-OA_02e4EvXZHyTkoUfm:bowpf5j) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b931e811be08de282566e23bedb2dcffd440262/pkg/cmd/roachtest/tests/admission_control_mixed_version.go#L89)):*
> ```Go
> 				cmd := roachtestutil.NewCommand("./cockroach workload run kv "+
> 					"--histograms=perf/stats.json --concurrency=500 "+
> 					"--max-rate=5000 --splits=1000 --read-percent=5 "+
> ```

I would specify the splits in the `initKV` function instead, the benefit of having it here is that it also stresses splits while the elastic workload is running -- however it is simpler to include them in the setup, where they would traditionally be found.
___
*[`pkg/cmd/roachtest/tests/admission_control_mixed_version.go` line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134014#-OA_-UruCiAWPj4JZz3y:-OA_-UruCiAWPj4JZz3z:bw6xwm9) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b931e811be08de282566e23bedb2dcffd440262/pkg/cmd/roachtest/tests/admission_control_mixed_version.go#L92)):*
> ```Go
> 					"--min-block-bytes=512 --max-block-bytes=1024 "+
> 					"--txn-qos='regular' --tolerate-errors "+
> 					"--duration=%v {pgurl%s}", duration, c.CRDBNodes())
> ```

Does `pgurl%s` run the workload against every node? I've commonly seen something like `"...{pgurl:1-%d}", c.Spec().NodeCount-1`. Assuming it likely does, feel free to ignore this comment as the method here is cleaner.
___
*[`pkg/cmd/roachtest/tests/admission_control_mixed_version.go` line 131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134014#-OA_0Vwy0IYsVOxLOLck:-OA_0Vwy0IYsVOxLOLcl:bw95b7h) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b931e811be08de282566e23bedb2dcffd440262/pkg/cmd/roachtest/tests/admission_control_mixed_version.go#L131)):*
> ```Go
> 				})
> 
> 			mvt.Run()
> ```

Are the assertions going to be added in a later PR? I imagined that there'd be some assertion on the regular workload throughput (although tricky to strike the right balance between a tight assertion and a flaky test, also would need to occur after some ramp).

**Review by andrewbaptist — CHANGES_REQUESTED** [review]
Thanks for getting this in!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134014#-:-OArXi82ElGGrDQ9PpIf:b-hw43tt)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @herkolategan, @kvoli, @pav-kv, @sumeerbhola, and @vidit-bhat)

___
*[`pkg/cmd/roachtest/tests/admission_control_mixed_version.go` line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134014#-OArXEPICRdGrMHbIxBM:-OArXEPICRdGrMHbIxBN:b-2r9mml) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b931e811be08de282566e23bedb2dcffd440262/pkg/cmd/roachtest/tests/admission_control_mixed_version.go#L49)):*
> ```Go
> 
> 			startOpts := option.NewStartOpts(option.NoBackupSchedule)
> 			roachtestutil.SetDefaultAdminUIPort(c, &startOpts.RoachprodOpts)
> ```

nit: Is there a reason to set this port? Otherwise I'd remove this call based on #111052.
___
*[`pkg/cmd/roachtest/tests/admission_control_mixed_version.go` line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134014#-OArWXhm59fUmJiaC-YT:-OArWXhm59fUmJiaC-YU:bmwq8gt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b931e811be08de282566e23bedb2dcffd440262/pkg/cmd/roachtest/tests/admission_control_mixed_version.go#L74)):*
> ```Go
> 				t.Status(fmt.Sprintf("limiting disk bandwidth to %d bytes/s", diskBand))
> 				for n := 1; n <= 3; n++ {
> 					require.NoError(t, setBandwidthLimit(ctx, t, c, c.Node(n),
> ```

IIt would be better to use the `roachtestutil.DiskStaller` rather than this call. Ideally we should deprecate that function. There is already a TODO to do that. In general it is hard to get this right.
___
*[`pkg/cmd/roachtest/tests/admission_control_mixed_version.go` line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134014#-OArVj-K1mB3tgcgoMmZ:-OArVj-K1mB3tgcgoMm_:b78520u) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b931e811be08de282566e23bedb2dcffd440262/pkg/cmd/roachtest/tests/admission_control_mixed_version.go#L83)):*
> ```Go
> 				return c.RunE(ctx, option.WithNodes(c.WorkloadNode()), fmt.Sprintf(
> 					"%s workload init kv --drop --insert-count=400 "+
> 						"--max-block-bytes=1024 --min-block-bytes=1024 {pgurl%s}",
> ```

nit: I haven't run with an --insert-count during the init phase, but I'd recommend to make the `min/max-block-bytes` consistent between this call and the ones below. Right now there are three different values which could be confusing to interpret later. 
___
*[`pkg/cmd/roachtest/tests/admission_control_mixed_version.go` line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134014#-OArWsHf9DshhVl7Kjk0:-OArWsHf9DshhVl7Kjk1:bvpk6o8) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b931e811be08de282566e23bedb2dcffd440262/pkg/cmd/roachtest/tests/admission_control_mixed_version.go#L100)):*
> ```Go
> 					"--max-rate=10000 --read-percent=0 "+
> 					"--min-block-bytes=2048 --max-block-bytes=4096 "+
> 					"--txn-qos='background' --tolerate-errors "+
> ```

nit: Does this fail without the tolerate-errors. With tolerate errors things as severe as a node crash can be missed.
___
*[`pkg/cmd/roachtest/tests/admission_control_mixed_version.go` line 131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134014#-OA_0Vwy0IYsVOxLOLck:-OArXy199A4IUDxNbGbG:bg8fabq) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b931e811be08de282566e23bedb2dcffd440262/pkg/cmd/roachtest/tests/admission_control_mixed_version.go#L131)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Are the assertions going to be added in a later PR? I imagined that there'd be some assertion on the regular workload throughput (although tricky to strike the right balance between a tight assertion and a flaky test, also would need to occur after some ramp).
</blockquote></details>

You might want to either call `validateTokensReturned` https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/tests/admission_control_latency.go#L919 or do something similar.

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134014)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist, @herkolategan, @kvoli, @sumeerbhola, and @vidit-bhat)

___
*[`pkg/cmd/roachtest/tests/admission_control_mixed_version.go` line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134014#-OAZzaci1pSQpipggOQp:-OAbMt-HDqUuP2wSYWqF:bd6sb3l) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b931e811be08de282566e23bedb2dcffd440262/pkg/cmd/roachtest/tests/admission_control_mixed_version.go#L35)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Rather concise and precise.
</blockquote></details>

Inspired by `registerDiskBandwidthOverload`.
___
*[`pkg/cmd/roachtest/tests/admission_control_mixed_version.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134014#-OAZzlp3APscnOt73WgU:-OAbKegCEGOTDrAhjQHu:b-qj5k1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b931e811be08de282566e23bedb2dcffd440262/pkg/cmd/roachtest/tests/admission_control_mixed_version.go#L38)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: we could do this later, however mapping the test name will be a pain, consider adding `.../elastic-workload`.
</blockquote></details>

Renamed to `admission-control/elastic-workload/mixed-version`, both the file and func as well.
___
*[`pkg/cmd/roachtest/tests/admission_control_mixed_version.go` line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134014#-OArXEPICRdGrMHbIxBM:-OAwqbLs9_0LQOaU21A0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b931e811be08de282566e23bedb2dcffd440262/pkg/cmd/roachtest/tests/admission_control_mixed_version.go#L49)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: Is there a reason to set this port? Otherwise I'd remove this call based on #111052.
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/tests/admission_control_mixed_version.go` line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134014#-OArWXhm59fUmJiaC-YT:-OAwt7iJEoim3WasLfnI:biozj6f) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b931e811be08de282566e23bedb2dcffd440262/pkg/cmd/roachtest/tests/admission_control_mixed_version.go#L74)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

IIt would be better to use the `roachtestutil.DiskStaller` rather than this call. Ideally we should deprecate that function. There is already a TODO to do that. In general it is hard to get this right.
</blockquote></details>

Done. Thanks for the tip.
___
*[`pkg/cmd/roachtest/tests/admission_control_mixed_version.go` line 83 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134014#-OArVj-K1mB3tgcgoMmZ:-OAwtb3qAv_75xDlZleR:b-u0re7e) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b931e811be08de282566e23bedb2dcffd440262/pkg/cmd/roachtest/tests/admission_control_mixed_version.go#L83)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: I haven't run with an --insert-count during the init phase, but I'd recommend to make the `min/max-block-bytes` consistent between this call and the ones below. Right now there are three different values which could be confusing to interpret later.
</blockquote></details>

Made the block bytes params the same as in the "foreground" workload (added a comment above saying this much). Leaving the "background" one with larger block sizes intentionally (emulating some kind of batch operation).
___
*[`pkg/cmd/roachtest/tests/admission_control_mixed_version.go` line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134014#-OA_02e4EvXZHyTkoUfl:-OAbL6NG3FXuXkpaa_Ez:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b931e811be08de282566e23bedb2dcffd440262/pkg/cmd/roachtest/tests/admission_control_mixed_version.go#L89)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

I would specify the splits in the `initKV` function instead, the benefit of having it here is that it also stresses splits while the elastic workload is running -- however it is simpler to include them in the setup, where they would traditionally be found.
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/tests/admission_control_mixed_version.go` line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134014#-OA_-UruCiAWPj4JZz3y:-OAbL7Ss8yEQZlj-OcB5:b-7szgut) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b931e811be08de282566e23bedb2dcffd440262/pkg/cmd/roachtest/tests/admission_control_mixed_version.go#L92)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Does `pgurl%s` run the workload against every node? I've commonly seen something like `"...{pgurl:1-%d}", c.Spec().NodeCount-1`. Assuming it likely does, feel free to ignore this comment as the method here is cleaner.
</blockquote></details>

Yes, `c.CRDBNodes()` returns a node list 1-3, and its `String()` func prints the thing you described.
___
*[`pkg/cmd/roachtest/tests/admission_control_mixed_version.go` line 100 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134014#-OArWsHf9DshhVl7Kjk0:-OB12xuf9WJCjZW0bJ9E:b-gbovm0) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b931e811be08de282566e23bedb2dcffd440262/pkg/cmd/roachtest/tests/admission_control_mixed_version.go#L100)):*
<details><summary><i>Previously, andrewbaptist (Andrew Baptist) wrote…</i></summary><blockquote>

nit: Does this fail without the tolerate-errors. With tolerate errors things as severe as a node crash can be missed.
</blockquote></details>

Probably shouldn't fail since the workload is not active during node restarts. Removed the flag for now, and we'll need to reintroduce it if the test ends up flaky.
___
*[`pkg/cmd/roachtest/tests/admission_control_mixed_version.go` line 131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134014#-OA_0Vwy0IYsVOxLOLck:-OAbLhOH5W49VIjhlxK-:b-3y4h39) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b931e811be08de282566e23bedb2dcffd440262/pkg/cmd/roachtest/tests/admission_control_mixed_version.go#L131)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Are the assertions going to be added in a later PR? I imagined that there'd be some assertion on the regular workload throughput (although tricky to strike the right balance between a tight assertion and a flaky test, also would need to occur after some ramp).
</blockquote></details>

Yeah, probably need some assertions. I don't have a good sense how to do it yet. I suppose this is well addressed in `perturbation` tests, so it would be best to integrate with them.

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134014)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andrewbaptist, @herkolategan, @kvoli, @sumeerbhola, and @vidit-bhat)

___
*[`pkg/cmd/roachtest/tests/admission_control_mixed_version.go` line 131 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134014#-OA_0Vwy0IYsVOxLOLck:-OB1C79p66pi8muPGqhn:b-xilris) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b931e811be08de282566e23bedb2dcffd440262/pkg/cmd/roachtest/tests/admission_control_mixed_version.go#L131)):*
<details><summary><i>Previously, pav-kv (Pavel Kalinnikov) wrote…</i></summary><blockquote>

Yeah, probably need some assertions. I don't have a good sense how to do it yet. I suppose this is well addressed in `perturbation` tests, so it would be best to integrate with them.
</blockquote></details>

For now added a second commit, reusing `validateTokensReturned`.

**Review by andrewbaptist — APPROVED** [review]
:lgtm:

Thanks for the changes, it will be good to have this running consistently.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134014#-:-OB23Bw37UbYkV1zDG-w:bg7igkv)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (and 1 stale) (waiting on @andrewbaptist, @herkolategan, @kvoli, @pav-kv, and @vidit-bhat)

___
*[`pkg/cmd/roachtest/tests/admission_control_elastic_mixed_version.go` line 131 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/134014#-OB223KN2BgKto9UdktP:-OB223KN2BgKto9UdktQ:b1wa6m) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2d0d24c89135bf6a83d7683946401af79c70b40/pkg/cmd/roachtest/tests/admission_control_elastic_mixed_version.go#L131)):*
> ```Go
> 
> 			mvt.Run()
> 			validateTokensReturned(ctx, t, c, c.CRDBNodes())
> ```

Could you add a TODO that we should also look at the disk write bandwidth metric and assert that it was kept under control throughout?
Also, do you have a link/screenshot of the disk write bandwidth graph for a recent run? I am curious what happens before, during the mixed version cluster and after the upgrade.

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134014)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 3 stale) (waiting on @andrewbaptist, @herkolategan, @kvoli, @sumeerbhola, and @vidit-bhat)

___
*[`pkg/cmd/roachtest/tests/admission_control_elastic_mixed_version.go` line 131 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/134014#-OB223KN2BgKto9UdktP:-OB2W7o62XPvW9Y2u2PW:buznel8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2d0d24c89135bf6a83d7683946401af79c70b40/pkg/cmd/roachtest/tests/admission_control_elastic_mixed_version.go#L131)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Could you add a TODO that we should also look at the disk write bandwidth metric and assert that it was kept under control throughout?
Also, do you have a link/screenshot of the disk write bandwidth graph for a recent run? I am curious what happens before, during the mixed version cluster and after the upgrade.
</blockquote></details>

Done. Will send a metrics link to slack.

**Comment by pav-kv** [comment]
bors r=kvoli,andrewbaptist,sumeerbhola

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134014)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 3 stale)

___
*[`pkg/cmd/roachtest/tests/admission_control_elastic_mixed_version.go` line 34 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/134014#-OB2f4LA4AZ39BtEEu5a:-OB2f4LA4AZ39BtEEu5b:bx2o1wf) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb08418d3c199665c1382a47a5cbd0eb2d1db5aa/pkg/cmd/roachtest/tests/admission_control_elastic_mixed_version.go#L34)):*
> ```Go
> // that even with a demanding "background" workload that is able to push the
> // used bandwidth much higher than the provisioned one, AC paces the traffic at
> // the set bandwidth limit, and favours regular writes. This behaviour does not
> ```

This is inaccurate in that AC is never pacing the traffic at the "set bandwidth limit" since the `kvadmission.store.provisioned_bandwidth` is not set. And we don't need to either.

Instead of the current "The goal sentence" and remaining stuff in this paragraph, I'd suggest something like:

The bandwidth of the disks in the cluster is artificially constrained so that the stores get overloaded and throttles the elastic writes to a lower value. We expect to see that during the earlier version, the mixed version, and the final version, the overload score of the stores stays within the expected range (around 20% overload, which corresponds to approximately 4 L0 sublevels).


btw, in https://grafana.testeng.crdb.io/d/J-yAVzkVddd/detailed?from=1730928721000&to=1730929976000&var-cluster=pavel-1730928538-01-n4cpu8&orgId=1 the bandwidth is significantly higher than 128MB/s set below. Any idea why?

**Comment by kvoli** [comment]
blathers backport 24.3

**Comment by kvoli** [comment]
@pav-kv we should backport this to 24.3, It might need to be manual, hit when trying to backport https://github.com/cockroachdb/cockroach/pull/134852.

**Comment by pav-kv** [comment]
blathers backport 24.3

**Pull request merged**
