### PR TITLE
kv: simplify handling of refreshed timestamp

### PR DESCRIPTION
**Pull request by andreimatei**
A bunch of code in the span refresher was needlessly passing an extra
timestamp to signify refreshes. Various transactions and batches 
updated needlessly; it was all very confusing. No more - this patch
 converts everybody to use br.Txn.ReadTimestamp as the timestamp at which
 a batch executed after a 
 
Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44936)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/txn_interceptor_span_refresher.go, line 272 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44936#-M-lNNjK2qSnQoCFESyA:-M-lNNjL4xc_tquWxwK3:b-z6jvp0) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bd6bf44522b5d9af8adc2c1056111ae9159eeed/pkg/kv/txn_interceptor_span_refresher.go#L272)):*
> ```Go
> 	log.VEventf(ctx, 2, "retry successful @%s", ba.Txn.WriteTimestamp)
> 	sr.autoRetryCounter.Inc(1)
> 	retryTxn.ReadTimestamp.Forward(retryLargestRefreshTS)
> ```

While you're here, could you make this less confusing by not mutating `retryTxn.ReadTimestamp?`
___
*[pkg/kv/txn_interceptor_span_refresher_test.go, line 261 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44936#-M-lNSOZ5-kFe4zwE7KP:-M-lNSOZ5-kFe4zwE7KQ:b-1nd1qf) ([raw file](https://github.com/cockroachdb/cockroach/blob/4142f4621472b9e0e9abdc00a9bd46e59cab4103/pkg/kv/txn_interceptor_span_refresher_test.go#L261)):*
> ```Go
> 	var ba roachpb.BatchRequest
> 	clonedTxn := txn.Clone()
> 	ba.Header = roachpb.Header{Txn: clonedTxn}
> ```

`ba.Header = roachpb.Header{Txn: txn.Clone()}`?
___
*[pkg/kv/txn_interceptor_span_refresher_test.go, line 261 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44936#-M-lNXcM1RITQhraOrYs:-M-lNXcM1RITQhraOrYt:b1zy44e) ([raw file](https://github.com/cockroachdb/cockroach/blob/4142f4621472b9e0e9abdc00a9bd46e59cab4103/pkg/kv/txn_interceptor_span_refresher_test.go#L261)):*
> ```Go
> 	var ba roachpb.BatchRequest
> 	clonedTxn := txn.Clone()
> 	ba.Header = roachpb.Header{Txn: clonedTxn}
> ```

Do we need to do this again before the next batch is sent?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44936)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/txn_interceptor_span_refresher.go, line 272 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44936#-M-lNNjK2qSnQoCFESyA:-M-qhEOB4RXqP3HmG4C4:bgd4st4) ([raw file](https://github.com/cockroachdb/cockroach/blob/2bd6bf44522b5d9af8adc2c1056111ae9159eeed/pkg/kv/txn_interceptor_span_refresher.go#L272)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

While you're here, could you make this less confusing by not mutating `retryTxn.ReadTimestamp?`
</blockquote></details>

done in a new commit
___
*[pkg/kv/txn_interceptor_span_refresher_test.go, line 261 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44936#-M-lNSOZ5-kFe4zwE7KP:-M-p3Jx5C5r79e58pqKj:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/4142f4621472b9e0e9abdc00a9bd46e59cab4103/pkg/kv/txn_interceptor_span_refresher_test.go#L261)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`ba.Header = roachpb.Header{Txn: txn.Clone()}`?
</blockquote></details>

done
___
*[pkg/kv/txn_interceptor_span_refresher_test.go, line 261 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44936#-M-lNXcM1RITQhraOrYs:-M-qlBZS1ZhtCYr-aqYw:b-zfa0ih) ([raw file](https://github.com/cockroachdb/cockroach/blob/4142f4621472b9e0e9abdc00a9bd46e59cab4103/pkg/kv/txn_interceptor_span_refresher_test.go#L261)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we need to do this again before the next batch is sent?
</blockquote></details>

I've reverted the changes to this test; it was the wrong one.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44936#-:-M-u9blrEBrgFjyBVp76:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/txn_interceptor_span_refresher.go, line 269 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44936#-M-u9KP9AT-SfOUGiryh:-M-u9KP9AT-SfOUGiryi:b-uqiyz0) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5493a9d8514ad7f95c1d6bdfa5469b0861938af/pkg/kv/txn_interceptor_span_refresher.go#L269)):*
> ```Go
> 	log.VEventf(ctx, 2, "retry successful @%s", retryBr.Txn.ReadTimestamp)
> 	sr.autoRetryCounter.Inc(1)
> 	return retryBr, nil
> ```

We should probably just squash the first commit into this one since we're already changing this code.

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44936#-:-M-uLulDB67dknrld49t:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/txn_interceptor_span_refresher.go, line 269 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/44936#-M-u9KP9AT-SfOUGiryh:-M-uLol861HcPb95LkOa:btppipj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5493a9d8514ad7f95c1d6bdfa5469b0861938af/pkg/kv/txn_interceptor_span_refresher.go#L269)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We should probably just squash the first commit into this one since we're already changing this code.
</blockquote></details>

meh, I'll leave it.

**Pull request merged**
