### PR TITLE
Add metrics for Store.processRaft.

### LINKED ISSUE #8175: storage: Monitor `processRaft` goroutine
We should export metrics from `Store.processRaft` to track how this goroutine (which is a bottleneck for many operations) is spending its time. Specifically, we need ~3 metrics:
- `process-raft.waiting`: Time spent blocking in `select`
- `process-raft.working`: Time in the loop before the select (which is mainly spent in `handleRaftReady`)
- `process-raft.ticking`: Time spent in the `ticker` branch of the `select`

### PR DESCRIPTION
**Pull request by jordanlewis**
This commit adds latency histograms for the main 3 phases of work of `Store.processRaft`: time blocking in `select`, time in the loop before `select`, and time spent in the `ticker` branch of the `select`.

Resolves #8175.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8257)

### CODE REVIEW

**Comment by tamird** [comment]
needs tests

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/store.go, line 2528 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8257#-KOBOOtMSBlla5oS_KqG:-KOBOOtMSBlla5oS_KqH:156882681) ([raw file](https://github.com/cockroachdb/cockroach/blob/afbe300c88742907b7b7daaa2804b48720399b94/storage/store.go#L2528)):*
> ```Go
> 			s.processRaftMu.Unlock()
> 
> 			selectStart = timeutil.Now()
> ```

How is this compiling? Don't you need `:=`?

---

*[storage/store.go, line 2562 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8257#-KOBO79EbkM-oPstz48L:-KOBO79EbkM-oPstz48M:-700258781) ([raw file](https://github.com/cockroachdb/cockroach/blob/afbe300c88742907b7b7daaa2804b48720399b94/storage/store.go#L2562)):*
> ```Go
> 				s.pendingRaftGroups.Unlock()
> 				s.mu.Unlock()
> 				s.metrics.raftSelectLatency.RecordValue(timeutil.Since(selectStart).Nanoseconds())
> ```

I'm not sure I see a value in this select latency measurement. Recording the measurement here iis measuring the latency of ticking as well as the select. Can you expand on what you think it will show? Perhaps better to track the latency between ticks. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8257)*

**Comment by bdarnell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[storage/store.go, line 623 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8257#-KOBONlgTpmXLuSBoNI1:-KOBONlgTpmXLuSBoNI2:422802908) ([raw file](https://github.com/cockroachdb/cockroach/blob/afbe300c88742907b7b7daaa2804b48720399b94/storage/store.go#L623)):*
> ```Go
> 
> 	// Raft processing metrics.
> 	raftSelectLatency  metric.Histograms
> ```

I think we want counters, not histograms for these. It's difficult to combine and compare histograms for these events since the frequency is not the same.  (and s/latency/duration/g)

---

*[storage/store.go, line 2530 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8257#-KOBOkEJAitjb1zCFTov:-KOBOkEJAitjb1zCFTow:-2025433845) ([raw file](https://github.com/cockroachdb/cockroach/blob/afbe300c88742907b7b7daaa2804b48720399b94/storage/store.go#L2530)):*
> ```Go
> 			selectStart = timeutil.Now()
> 			select {
> 			case <-s.wakeRaftLoop:
> ```

Every `case` needs to update `raftSelectLatency`, and this needs to happen immediately after the `case` statement before any other work is done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8257)*

**Comment by jordanlewis** [comment]
Do you have a suggestion for the best way to test this?

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[storage/store.go, line 623 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8257#-KOBONlgTpmXLuSBoNI1:-KOBly6tr3_-1rtnh8qb:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/afbe300c88742907b7b7daaa2804b48720399b94/storage/store.go#L623)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> I think we want counters, not histograms for these. It's difficult to combine and compare histograms for these events since the frequency is not the same.  (and s/latency/duration/g)
</details>
Done.

---

*[storage/store.go, line 2528 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8257#-KOBOOtMSBlla5oS_KqG:-KOBlyxQLX5fPYzMNaJn:677251276) ([raw file](https://github.com/cockroachdb/cockroach/blob/afbe300c88742907b7b7daaa2804b48720399b94/storage/store.go#L2528)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> How is this compiling? Don't you need `:=`?
</details>
Yes.

---

*[storage/store.go, line 2530 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8257#-KOBOkEJAitjb1zCFTov:-KOBlztHyNt_0sRYxy5Y:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/afbe300c88742907b7b7daaa2804b48720399b94/storage/store.go#L2530)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Every `case` needs to update `raftSelectLatency`, and this needs to happen immediately after the `case` statement before any other work is done.
</details>
Done.

---

*[storage/store.go, line 2562 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8257#-KOBO79EbkM-oPstz48L:-KOBm-oPtHnHp6X9VL3A:2080640057) ([raw file](https://github.com/cockroachdb/cockroach/blob/afbe300c88742907b7b7daaa2804b48720399b94/storage/store.go#L2562)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I'm not sure I see a value in this select latency measurement. Recording the measurement here iis measuring the latency of ticking as well as the select. Can you expand on what you think it will show? Perhaps better to track the latency between ticks. 
</details>
This was a mistake - I meant to measure just the time waiting in select but forgot as I was writing the code. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8257#-:-KOBluNq_owv_yeiaVup:-1536784345)*

**Comment by tamird** [comment]
I dunno, where is the other stuff on storeRegistry tested?

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[storage/store.go, line 689 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8257#-KOBokz4eMjOp5FzybTo:-KOBokz4eMjOp5FzybTp:1677663773) ([raw file](https://github.com/cockroachdb/cockroach/blob/7279da25a9afc659b7859be740ec83e89f9a5f21/storage/store.go#L689)):*
> ```Go
> 
> 		// Raft processing metrics.
> 		raftSelectDuration:  storeRegistry.Counter("process-raft.waiting"),
> ```

these keys should have "ns" somewhere in their names, i think.

also, s/Duration/DurationNanos/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8257#-:-KOBoega2B0BJhk6Y8RK:1996568413)*

**Comment by bdarnell** [comment]
:lgtm:

The other store metrics aren't well-tested, and these are especially hard metrics to test so I'm fine without one. 

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8257#-:-KODZGEmVA8rcwXkOVCq:271822186)*

**Comment by jordanlewis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[storage/store.go, line 689 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8257#-KOBokz4eMjOp5FzybTo:-KOFz2WAe3-UhnJjF3nF:1259017897) ([raw file](https://github.com/cockroachdb/cockroach/blob/7279da25a9afc659b7859be740ec83e89f9a5f21/storage/store.go#L689)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> these keys should have "ns" somewhere in their names, i think.
> 
> also, s/Duration/DurationNanos/
</details>
Done. I appended "nanos" to the key names to follow the pattern set earlier in this file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8257)*

**Comment by tamird** [comment]
:lgtm: as long as this has been tested manually, at least

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8257#-:-KOGc3mE2bQqjy3aPKDD:74752413)*

**Pull request merged**
