### PR TITLE
release-23.1: sql: fix sql activity cache for large cardinality

### PR DESCRIPTION
**Pull request by maryliag**
Backport 2/2 commits from #112350.
Backport 1/1 commits from #112891.
Backport 1/1 commits from #112975.

/cc @cockroachdb/release

---

tldr: fix activity update job failing from conflict, caching to much info when their is high cardinatlity in the stats, and fix cache to store the correct top stats.

1. Fix activity update failure from upserting same row multiple times. This was caused by 2 nodes having the same statement, but one only executed it 2 or 3 time and the other node executed it enough to generate an index recommendation. The different index recommendation caused duplicate rows based on primary key to be inserted. It now uses index recommendation from the merged stats which uses the latest existing
recommendation (we don't update if there is no recommendation).
2. Customers can have transactions that have over 1k unique statement fingerprint ids. This makes it unreasonable to cache all of the statement information for all the top transactions. This commit removes the logic to cache all the statement information for the top transactions which could cause the table to grow to over 100k for a single hour. This requires the call to go the statistics table to get all the necessary statement information for the txn details.
3. The activity cache logic was not correctly selecting the top CPU json column. It was using the computed index column name instead of the json field name. The values shown on the UI were correct because the endpoint still aggregated several columns using the aggregated stats rather than the separate column.
4. The activity cache logic was using the execution count instead of the statistics count to select the top queries. In most cases this still generates the correct top queries, and the UI uses the aggregated stats which showed the correct value.

Fixes: #111780
Fixes: #111224

Release note (bug fix): Fix the SQL activity update job to avoid conflicts on update, reduces the amount of data cached to just what the overview page requires, and fix the correctess of the top queries.

---

sql: builtin for jsonb array to string array conversion
This commit introduces the function
`jsonb_array_to_string_array` that converts a JSONB array
to a string array format.

Epic: none

Release note (sql change): New builtin `jsonb_array_to_string_array`
that converts JSONB array to string array.

---

sql: fix for crash with null elements on jsonb_array_to_string_array
Fixes https://github.com/cockroachdb/cockroach/issues/112829

The builtin jsonb_array_to_string_array was crashing, when it
had null elements. This commit handles this case, removing them
from the final array.

Release note: None

---

This commit makes the builtin jsonb_array_to_string_array return NULL elements, which were previously being removed. It also adds more testing for different types of elements on the array.

Release note: None

---

Release justification: bug fixes and performance improvement

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm: but I think this now needs an approval from a TL, @mgartner seems like the best choice for that.

> Reviewed 7 of 7 files at r1, 7 of 7 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112864#-:-NhTXCEkBL0xjzvXOn24:bycurt1)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian, @maryliag, and @mgartner)

___
*[`pkg/ccl/kvccl/kvtenantccl/upgradeinterlockccl/BUILD.bazel` line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112864#-NhTWYBpDw3SoN0xzzZI:-NhTWYBq5HHTZzFkQNLa:bf5h8mz) ([raw file](https://github.com/cockroachdb/cockroach/blob/8501829fa46c59eca57aec9664c400d82bfd6b6e/pkg/ccl/kvccl/kvtenantccl/upgradeinterlockccl/BUILD.bazel#L7)):*
> ```Starlark
>     size = "enormous",
>     srcs = [
>         "generated_test.go",
> ```

nit: this shouldn't be introduced in the first commit.

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112864)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian, @mgartner, and @yuzefovich)

___
*[`pkg/ccl/kvccl/kvtenantccl/upgradeinterlockccl/BUILD.bazel` line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/112864#-NhTWYBpDw3SoN0xzzZI:-NhUr9vm9fbRxFuu_kmQ:b-886gsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/8501829fa46c59eca57aec9664c400d82bfd6b6e/pkg/ccl/kvccl/kvtenantccl/upgradeinterlockccl/BUILD.bazel#L7)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: this shouldn't be introduced in the first commit.
</blockquote></details>

Fixed

**Comment by yuzefovich** [comment]
Just wanted to point out if we want to include this fix into 23.1.12, we'll need a separate backport to `23.1.12-rc` branch.

**Comment by ajstorm** [comment]
@maryliag  Since this adds new functionality, it also requires PM approval as per the new changes to the[ BP policy](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/1043235321/Database+Backport+Patch+Policy#Backporting-new-functionality-(including-modifications-to-persisted-state-%26-cross-node-RPCs)).  It may also require a default-off feature flag, OR an exception from VP/CTO, if you feel that a feature flag is not appropriate here.

**Comment by maryliag** [comment]
A feature flag would not make sense for this case, so I will request an exception from VP/CTO

**Comment by yuzefovich** [comment]
This PR introduces some new functionality (a new builtin function), but it is mainly a bug fix + perf fix. I would expect this to not require any special exemption.

**Comment by maryliag** [comment]
From internal slack: we got the approval for the exception

**Review by dhartunian — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112864#-:-Ni0BCMNBhqiqK-Rp4-i:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @kevin-v-ngo, @mgartner, and @yuzefovich)

**Review by yuzefovich — APPROVED** [review]
> Reviewed 1 of 9 files at r5, 11 of 11 files at r7, 8 of 8 files at r8, 2 of 2 files at r9, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/112864)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @kevin-v-ngo and @mgartner)

**Review by mgartner — APPROVED** [review]

**Pull request merged**
