### PR TITLE
sql: parse partial indexes

### PR DESCRIPTION
**Pull request by mgartner**
This commit adds support for parsing partial indexes. The parser can now
parse statements like:

    CREATE TABLE t (a INT, INDEX (a) WHERE a > 3)
    CREATE TABLE t (a INT, UNIQUE INDEX (a) WHERE a > 3)
    CREATE INDEX i ON t (a) WHERE a > 3

Note that these `WHERE` clauses have no effect as of this commit. Until
further work is done, the `WHERE` clauses are ignored and full indexes
are created.

This commit also adds the ability to format the `Predicate` expression
of `tree.CreateIndex` and `tree.IndexTableDef` expressions.

A temporary session setting has been added called `partial_indexes`.
When set to true, it enables the user to create partial indexes. By
default, it is false because partial indexes are not fully supported.
Once partial indexes are fully functional, this setting will be removed.

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49335#-:-M7nZgnDB5nM8lzKK7Tg:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49335#-:-M7oNJJ5DJ_rU6nHPiSc:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[pkg/sql/create_index.go, line 203 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49335#-M7oMrPy7_f_gNJ4iad4:-M7oMrPy7_f_gNJ4iad5:b-heoxgg) ([raw file](https://github.com/cockroachdb/cockroach/blob/49b29303a6698ae3bea533c2a9d82f48400eaabc/pkg/sql/create_index.go#L203)):*
> ```Go
> 	// TODO(mgartner): remove this once partial indexes are fully supported.
> 	if n.Predicate != nil && !params.SessionData().PartialIndexes {
> 		return nil, pgerror.New(pgcode.FeatureNotSupported, "partial indexes are not supported")
> ```

The old error mentioned issue 9683, we should still do that, you can use `unimplemented.NewWithIssue`
___
*[pkg/sql/vars.go, line 608 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49335#-M7oNG4C7vmktUZ-GhS5:-M7oNG4C7vmktUZ-GhS6:b612oho) ([raw file](https://github.com/cockroachdb/cockroach/blob/49b29303a6698ae3bea533c2a9d82f48400eaabc/pkg/sql/vars.go#L608)):*
> ```Go
> 	// CockroachDB extension.
> 	// TODO(mgartner): remove this once partial indexes are fully supported.
> 	`partial_indexes`: {
> ```

make it `experimental_partial_indexes` for now

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49335)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @rytaft)

___
*[pkg/sql/create_index.go, line 203 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49335#-M7oMrPy7_f_gNJ4iad4:-M7tYsuoEf1OvcfqKQIz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/49b29303a6698ae3bea533c2a9d82f48400eaabc/pkg/sql/create_index.go#L203)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The old error mentioned issue 9683, we should still do that, you can use `unimplemented.NewWithIssue`
</blockquote></details>

Done.
___
*[pkg/sql/vars.go, line 608 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49335#-M7oNG4C7vmktUZ-GhS5:-M7tV9SQ32GScs_bLts2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/49b29303a6698ae3bea533c2a9d82f48400eaabc/pkg/sql/vars.go#L608)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

make it `experimental_partial_indexes` for now
</blockquote></details>

Done.

**Review by RaduBerinde — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49335#-:-M7tl8LS-DVtGChB_STh:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

**Pull request merged**
