### PR TITLE
distsqlrun: RowSourcify interleavedReaderJoiner

### LINKED ISSUE #26912: distsqlrun: refactor interleavedJoiner to be a rowSource
The title says it all.

### PR DESCRIPTION
**Pull request by jordanlewis**
The interleavedReaderJoiner now implements RowSource.

Closes #26912.

Release note: None

### CODE REVIEW

**Review by solongordon — DISMISSED** [review]
I'll take a closer look once logic tests are passing.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27641#-:-LHdX0J0E4LciA8KAuiy:b-6u3pnx)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/interleaved_reader_joiner.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27641#-LHdSQXD9ezO_hTEEhY7:-LHdSQXD9ezO_hTEEhY8:b-r8tgzv) ([raw file](https://github.com/cockroachdb/cockroach/blob/3304754d43c5a7e483e59dc02ed50dcf5c7e3132/pkg/sql/distsqlrun/interleaved_reader_joiner.go#L33)):*
> ```Go
> const (
> 	irjStateUnknown irjState = iota
> 	// jrReadingInput means that a batch of rows is being read from the input.
> ```

Copypasta
___
*[pkg/sql/distsqlrun/interleaved_reader_joiner.go, line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27641#-LHdSi6R4wuIT9fq1GCi:-LHdSi6R4wuIT9fq1GCj:bbue5jo) ([raw file](https://github.com/cockroachdb/cockroach/blob/3304754d43c5a7e483e59dc02ed50dcf5c7e3132/pkg/sql/distsqlrun/interleaved_reader_joiner.go#L103)):*
> ```Go
> 	//   output columns, perform a second lookup on the primary index.
> 	// - Join the index rows with the corresponding input rows and buffer the
> 	//   results in jr.toEmit.
> ```

More copypasta
___
*[pkg/sql/distsqlrun/interleaved_reader_joiner.go, line 120 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27641#-LHdWcs26FnCYleXFHjt:-LHdWcs26FnCYleXFHju:b-194lti) ([raw file](https://github.com/cockroachdb/cockroach/blob/3304754d43c5a7e483e59dc02ed50dcf5c7e3132/pkg/sql/distsqlrun/interleaved_reader_joiner.go#L120)):*
> ```Go
> 			irj.runningState, row, meta = irj.nextRow()
> 		case irjUnmatchedChild:
> 			irj.runningState, row, meta = irjReading, irj.unmatchedChild, nil
> ```

Maybe safer to nil out `irj.unmatchedChild` after emitting?
___
*[pkg/sql/distsqlrun/interleaved_reader_joiner.go, line 144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27641#-LHdUfsG0NPdAXkjFjJq:-LHdUfsG0NPdAXkjFjJr:b-mhks5e) ([raw file](https://github.com/cockroachdb/cockroach/blob/3304754d43c5a7e483e59dc02ed50dcf5c7e3132/pkg/sql/distsqlrun/interleaved_reader_joiner.go#L144)):*
> ```Go
> 	for i := range irj.tables {
> 		tInfo = &irj.tables[i]
> 		if desc.ID == tInfo.tableID && index.ID == tInfo.indexID {
> ```

Not your code but it seems dangerous that if these conditions fail every time, the loop will just exit with `tInfo` set to the last table. I would say better to factor this block out into a helper function which returns an error in this case.

**Review by jordanlewis — COMMENTED** [review]
Should be ready for a look now. Man that took a long time to track down. The trouble was that I was closing the producer before the final call to ProcessRow instead of after. I'm not sure why this doesn't get caught by the non-distributed tests.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27641#-:-LHiZGP37LZTdePXir5x:b-9hb0yz)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/interleaved_reader_joiner.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27641#-LHdSQXD9ezO_hTEEhY7:-LHiZEUd-pezPWA9Ta7d:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3304754d43c5a7e483e59dc02ed50dcf5c7e3132/pkg/sql/distsqlrun/interleaved_reader_joiner.go#L33)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Copypasta
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/interleaved_reader_joiner.go, line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27641#-LHdSi6R4wuIT9fq1GCi:-LHiZEv128dF5JzMfmbh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3304754d43c5a7e483e59dc02ed50dcf5c7e3132/pkg/sql/distsqlrun/interleaved_reader_joiner.go#L103)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

More copypasta
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/interleaved_reader_joiner.go, line 120 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27641#-LHdWcs26FnCYleXFHjt:-LHiZFDFDzS_C7B8qrw3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3304754d43c5a7e483e59dc02ed50dcf5c7e3132/pkg/sql/distsqlrun/interleaved_reader_joiner.go#L120)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Maybe safer to nil out `irj.unmatchedChild` after emitting?
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/interleaved_reader_joiner.go, line 144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27641#-LHdUfsG0NPdAXkjFjJq:-LHiZFgB9fsxcaoNjPKu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3304754d43c5a7e483e59dc02ed50dcf5c7e3132/pkg/sql/distsqlrun/interleaved_reader_joiner.go#L144)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Not your code but it seems dangerous that if these conditions fail every time, the loop will just exit with `tInfo` set to the last table. I would say better to factor this block out into a helper function which returns an error in this case.
</blockquote></details>

Done.

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27641)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/interleaved_reader_joiner.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27641#-LHiyBca5WQVYfZk33ar:-LHiyBca5WQVYfZk33as:b-6jlfm2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a02b2eec1822a1ad49cc50679b3d4f532855dcba/pkg/sql/distsqlrun/interleaved_reader_joiner.go#L35)):*
> ```Go
> 	// irjInitializing means the state machine should start its kvFetcher. This
> 	// state occurs just once, at the start of the run.
> 	irjInitializing
> ```

Note that in other cases (like the `tableReader`) we use `Start` to initialize the `kvFetcher`s.
___
*[pkg/sql/distsqlrun/interleaved_reader_joiner.go, line 171 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27641#-LHoDJuo13LnZgzx28XM:-LHoDJuo13LnZgzx28XN:bb6w5bp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a02b2eec1822a1ad49cc50679b3d4f532855dcba/pkg/sql/distsqlrun/interleaved_reader_joiner.go#L171)):*
> ```Go
> 	tInfo, isAncestorRow, err := irj.findTable(desc, index)
> 	if err != nil {
> 		irj.moveToDraining(scrub.UnwrapScrubError(err))
> ```

Why does this error need to be unwrapped? Looking at `findTable` it doesn't seem like a scrub error could be returned.
___
*[pkg/sql/distsqlrun/interleaved_reader_joiner.go, line 452 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27641#-LHoEyX95wBrNTQmWltk:-LHoEyX95wBrNTQmWltl:b-ie9g3b) ([raw file](https://github.com/cockroachdb/cockroach/blob/a02b2eec1822a1ad49cc50679b3d4f532855dcba/pkg/sql/distsqlrun/interleaved_reader_joiner.go#L452)):*
> ```Go
> 
> 		rendered := irj.renderUnmatchedRow(irj.ancestorRow, irj.ancestorJoinSide)
> 		return irj.processRowHelper(rendered)
> ```

Why not extract `processRowHelper` into `Next`? Like this you can always just return a raw row and then you process it before checking if it's `!= nil`

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27641)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/interleaved_reader_joiner.go, line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27641#-LHiyBca5WQVYfZk33ar:-LHoGeIm7WSU0EW121tD:b-jsdk80) ([raw file](https://github.com/cockroachdb/cockroach/blob/a02b2eec1822a1ad49cc50679b3d4f532855dcba/pkg/sql/distsqlrun/interleaved_reader_joiner.go#L35)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Note that in other cases (like the `tableReader`) we use `Start` to initialize the `kvFetcher`s.
</blockquote></details>

Whoops... not sure why I didn't do that. Done.
___
*[pkg/sql/distsqlrun/interleaved_reader_joiner.go, line 171 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27641#-LHoDJuo13LnZgzx28XM:-LHoGgaW2mXMPsnSrwOB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a02b2eec1822a1ad49cc50679b3d4f532855dcba/pkg/sql/distsqlrun/interleaved_reader_joiner.go#L171)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why does this error need to be unwrapped? Looking at `findTable` it doesn't seem like a scrub error could be returned.
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/interleaved_reader_joiner.go, line 452 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27641#-LHoEyX95wBrNTQmWltk:-LHoHiNu6B8ajto1RTJL:b-a3i2wn) ([raw file](https://github.com/cockroachdb/cockroach/blob/a02b2eec1822a1ad49cc50679b3d4f532855dcba/pkg/sql/distsqlrun/interleaved_reader_joiner.go#L452)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why not extract `processRowHelper` into `Next`? Like this you can always just return a raw row and then you process it before checking if it's `!= nil`
</blockquote></details>

That doesn't quite work because of what has to happen in the last row - we've got to mark ourselves as draining before returning to the main loop. But if we do that, then processRowHelper will always filter out the row. It's easier to do it this way, I think.

**Review by solongordon — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27641#-:-LICBD7EBEwllbobNssU:bg7igkv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by jordanlewis** [comment]
TFTRs!

bors r+

**Pull request merged**
