### PR TITLE
sql: create system.mvcc_statistics table and update job

### PR DESCRIPTION
**Pull request by zachlite**
The system.mvcc_statistics table stores historical mvcc data for a tenant's SQL objects. It's purpose it to serve mvcc data for a SQL object quickly - The span stats API is too slow to use in a hot path. Storing data over time unlocks new use cases like showing a table or index's accumulated garbage over time.

The MVCCStatisticsUpdate Job is responsible for managing the contents of the table, decoupled from the read-hotpath.

Both the table and job are baked when a cluster bootstraps itself, or upgrades itself from a previous version.

**Ignoring test fallout for now, so that it can be made available to reviewers**

Epic: CRDB-25491
Release note: None

### CODE REVIEW

**Review by j82w — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111365)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rhu713 and @zachlite)

___
*[`-- commits` line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111365#-NfMzjDg43z2t2_Iya_0):*
Please add a release note
___
*[`pkg/sql/catalog/systemschema/system.go` line 1013 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111365#-NfN1pdQDvEFnTqxTp8n:-NfN1pdQDvEFnTqxTp8o:b-mvhe9p) ([raw file](https://github.com/cockroachdb/cockroach/blob/860aaa4e3e4e522885d4944ff21c664dddd586e1/pkg/sql/catalog/systemschema/system.go#L1013)):*
> ```Go
> 	SystemMVCCStatisticsCacheSchema = `
> CREATE TABLE system.mvcc_statistics_cache (
> 	id INT8 NOT NULL DEFAULT unique_rowid(),
> ```

For the other stats tables we normally start with time. Why is the random id necessary?
___
*[`pkg/sql/catalog/systemschema/system.go` line 1016 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111365#-NfN-cao61h34GnuKDI-:-NfN-cao61h34GnuKDI0:b-pkqol0) ([raw file](https://github.com/cockroachdb/cockroach/blob/860aaa4e3e4e522885d4944ff21c664dddd586e1/pkg/sql/catalog/systemschema/system.go#L1016)):*
> ```Go
> 	database_id INT8 NOT NULL,
> 	table_id INT8 NOT NULL,
> 	index_id INT8 NOT NULL,
> ```

Just confirming it's not possible to have mvcc without an index?
___
*[`pkg/sql/catalog/systemschema/system.go` line 1017 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111365#-NfN0_1gB-mglf4c0Nm1:-NfN0_1gB-mglf4c0Nm2:b-k8wmsl) ([raw file](https://github.com/cockroachdb/cockroach/blob/860aaa4e3e4e522885d4944ff21c664dddd586e1/pkg/sql/catalog/systemschema/system.go#L1017)):*
> ```Go
> 	table_id INT8 NOT NULL,
> 	index_id INT8 NOT NULL,
> 	created_at TIMESTAMP NOT NULL DEFAULT now():::TIMESTAMP,
> ```

Should this be part of the response from the remote node to get a more accurate time?

**Review by koorosh — COMMENTED** [review]
> Reviewed 11 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111365)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rhu713 and @zachlite)

___
*[`pkg/sql/catalog/systemschema/system.go` line 1017 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111365#-NfN18972SRPlnR5HDhU:-NfN18972SRPlnR5HDhV:b-fl9hrw) ([raw file](https://github.com/cockroachdb/cockroach/blob/860aaa4e3e4e522885d4944ff21c664dddd586e1/pkg/sql/catalog/systemschema/system.go#L1017)):*
> ```Go
> 	table_id INT8 NOT NULL,
> 	index_id INT8 NOT NULL,
> 	created_at TIMESTAMP NOT NULL DEFAULT now():::TIMESTAMP,
> ```

Curious if it makes any difference to use TIMESTAMPZ (with time zone)?
___
*[`pkg/sql/sem/catconstants/constants.go` line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111365#-NfN2qKF5B0XVd0iG0bJ:-NfN2qKF5B0XVd0iG0bK:bi0f4mx) ([raw file](https://github.com/cockroachdb/cockroach/blob/860aaa4e3e4e522885d4944ff21c664dddd586e1/pkg/sql/sem/catconstants/constants.go#L101)):*
> ```Go
> 	SpanStatsTenantBoundaries              SystemTableName = "span_stats_tenant_boundaries"
> 	RegionalLiveness                       SystemTableName = "region_liveness"
> 	MVCCStatisticsCache                    SystemTableName = "mvcc_statistics_cache"
> ```

Why table name contains `_cache`?

**Comment by j82w** [comment]
*[`pkg/sql/sem/catconstants/constants.go` line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111365#-NfN2qKF5B0XVd0iG0bJ:-NfNszZJ2yu4jsJZzjXm:b32v57) ([raw file](https://github.com/cockroachdb/cockroach/blob/860aaa4e3e4e522885d4944ff21c664dddd586e1/pkg/sql/sem/catconstants/constants.go#L101)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Why table name contains `_cache`?
</blockquote></details>

+1

**Review by maryliag — COMMENTED** [review]
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111365)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh, @rhu713, and @zachlite)

___
*[`pkg/sql/mvcc_statistics_update_job.go` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111365#-NfRAtMMEw1vqJLzOt8r:-NfRAtMO4gCNi2wJ_hGU:b-ds8ywi) ([raw file](https://github.com/cockroachdb/cockroach/blob/860aaa4e3e4e522885d4944ff21c664dddd586e1/pkg/sql/mvcc_statistics_update_job.go#L1)):*
> ```Go
> package sql
> ```

nit: add copy rights section
___
*[`pkg/sql/mvcc_statistics_update_job.go` line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111365#-NfRAxkd86NEG48u4tXc:-NfRAxkd86NEG48u4tXd:b-z4e19f) ([raw file](https://github.com/cockroachdb/cockroach/blob/860aaa4e3e4e522885d4944ff21c664dddd586e1/pkg/sql/mvcc_statistics_update_job.go#L22)):*
> ```Go
> ) (jobErr error) {
> 
> 	// TODO(zachlite):
> ```

is this going to be part of a follow up PR?
___
*[`pkg/upgrade/upgrades/mvcc_statistics_cache_migration.go` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111365#-NfRBGsn5H7iFAPUenWg:-NfRBGsn5H7iFAPUenWh:b-ds8ywi) ([raw file](https://github.com/cockroachdb/cockroach/blob/860aaa4e3e4e522885d4944ff21c664dddd586e1/pkg/upgrade/upgrades/mvcc_statistics_cache_migration.go#L1)):*
> ```Go
> package upgrades
> ```

nit: add copy rights section
___
*[`pkg/upgrade/upgrades/mvcc_statistics_cache_migration.go` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111365#-NfRBO3B4t7frOUIRALc:-NfRBO3B4t7frOUIRALd:b-3x2ugz) ([raw file](https://github.com/cockroachdb/cockroach/blob/860aaa4e3e4e522885d4944ff21c664dddd586e1/pkg/upgrade/upgrades/mvcc_statistics_cache_migration.go#L1)):*
> ```Go
> package upgrades
> ```

once you remove the `cache` name from the table name, make sure to also update this file name to remove the `cache` from it

**Review by zachlite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111365)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w, @koorosh, @maryliag, and @rhu713)

___
*[`-- commits` line 23 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111365#-NfMzjDg43z2t2_Iya_0):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Please add a release note
</blockquote></details>

I was hesitant to add a release note here, since there's nothing that is intended or expected to be used by end users. 
WDYT?
___
*[`pkg/sql/mvcc_statistics_update_job.go` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111365#-NfRAtMMEw1vqJLzOt8r:-NfRLq4M0vxcXEahwTM2:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/860aaa4e3e4e522885d4944ff21c664dddd586e1/pkg/sql/mvcc_statistics_update_job.go#L1)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: add copy rights section
</blockquote></details>

Done
___
*[`pkg/sql/mvcc_statistics_update_job.go` line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111365#-NfRAxkd86NEG48u4tXc:-NfRMO4r6hgEP4hJtvkx:bkf5dyh) ([raw file](https://github.com/cockroachdb/cockroach/blob/860aaa4e3e4e522885d4944ff21c664dddd586e1/pkg/sql/mvcc_statistics_update_job.go#L22)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

is this going to be part of a follow up PR?
</blockquote></details>

Yes. Since the job should be baked during a cluster upgrade, I needed to set the job up now. But the implementation is not as time sensitive.
___
*[`pkg/sql/catalog/systemschema/system.go` line 1013 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111365#-NfN1pdQDvEFnTqxTp8n:-NfRMmFE6AjzOhA7wYS1:b-44zusj) ([raw file](https://github.com/cockroachdb/cockroach/blob/860aaa4e3e4e522885d4944ff21c664dddd586e1/pkg/sql/catalog/systemschema/system.go#L1013)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

For the other stats tables we normally start with time. Why is the random id necessary?
</blockquote></details>

As far as I can tell, there isn't a way to configure a monotonically increasing ID for an explicitly  when configuring system schema. Another idea is that we can leave out a primary key altogether, so there is an implicit `rowid` primary key. 

Since there will only be 1 writer at a time, I don't think a sequential id is cause for concern, but I also don't think there's harm in a unique_rowid.  WDYT?
___
*[`pkg/sql/catalog/systemschema/system.go` line 1016 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111365#-NfN-cao61h34GnuKDI-:-NfRO1CK7A2cxzyAJMlX:bqvokoy) ([raw file](https://github.com/cockroachdb/cockroach/blob/860aaa4e3e4e522885d4944ff21c664dddd586e1/pkg/sql/catalog/systemschema/system.go#L1016)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Just confirming it's not possible to have mvcc without an index?
</blockquote></details>

Yeah, even for tables created without an explicit primary key, the `rowid` becomes the primary index.


```
create table t (name string);

SELECT index_name, index_id FROM [SHOW RANGES FROM table t WITH INDEXES];
 
 index_name | index_id
-------------+-----------
  t_pkey     |        1

```


Also, the escape hatch is that we can just set the value to 0.
___
*[`pkg/sql/catalog/systemschema/system.go` line 1017 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111365#-NfN0_1gB-mglf4c0Nm1:-NfROeaN1ZVf_IppZAuj:balr49j) ([raw file](https://github.com/cockroachdb/cockroach/blob/860aaa4e3e4e522885d4944ff21c664dddd586e1/pkg/sql/catalog/systemschema/system.go#L1017)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Should this be part of the response from the remote node to get a more accurate time?
</blockquote></details>

Maybe? I don't think it effects our choice of schema here.
___
*[`pkg/sql/catalog/systemschema/system.go` line 1017 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111365#-NfN18972SRPlnR5HDhU:-NfROk7HAUqTt2owY3SJ:b-n4kr80) ([raw file](https://github.com/cockroachdb/cockroach/blob/860aaa4e3e4e522885d4944ff21c664dddd586e1/pkg/sql/catalog/systemschema/system.go#L1017)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

Curious if it makes any difference to use TIMESTAMPZ (with time zone)?
</blockquote></details>

Updated. Thanks!
___
*[`pkg/sql/sem/catconstants/constants.go` line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111365#-NfN2qKF5B0XVd0iG0bJ:-NfROlsW6K5GidVCjcWA:bt1b19c) ([raw file](https://github.com/cockroachdb/cockroach/blob/860aaa4e3e4e522885d4944ff21c664dddd586e1/pkg/sql/sem/catconstants/constants.go#L101)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Renamed!
___
*[`pkg/upgrade/upgrades/mvcc_statistics_cache_migration.go` line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111365#-NfRBO3B4t7frOUIRALc:-NfROoml-zS_zsXDjlto:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/860aaa4e3e4e522885d4944ff21c664dddd586e1/pkg/upgrade/upgrades/mvcc_statistics_cache_migration.go#L1)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

once you remove the `cache` name from the table name, make sure to also update this file name to remove the `cache` from it
</blockquote></details>

Done.

**Review by koorosh — COMMENTED** [review]
> Reviewed 3 of 15 files at r1, 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111365)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w, @maryliag, @rhu713, and @zachlite)

___
*[`pkg/sql/catalog/systemschema/system.go` line 4135 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111365#-NfSQUY3ECo7nTkZgwp4:-NfSQUY3ECo7nTkZgwp5:boizih9) ([raw file](https://github.com/cockroachdb/cockroach/blob/952a66eb1634b694bcd94f9353847c9d4ff363be/pkg/sql/catalog/systemschema/system.go#L4135)):*
> ```Go
> 				{Name: "index_id", ID: 4, Type: types.Int},
> 				{Name: "created_at", ID: 5, Type: types.TimestampTZ,
> 					DefaultExpr: &nowString},
> ```

should be also changed `&nowString` to `&nowTZString`

**Review by j82w — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111365)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @koorosh, @maryliag, @rhu713, and @zachlite)

___
*[`pkg/sql/catalog/systemschema/system.go` line 1020 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111365#-NfSZ6IG7IxHAmFHmGNt:-NfSZ6IG7IxHAmFHmGNu:bchn1jp) ([raw file](https://github.com/cockroachdb/cockroach/blob/fc4c0ddf42d6ce58394f0fecddbc3dcc7d4a36dd/pkg/sql/catalog/systemschema/system.go#L1020)):*
> ```Go
> 	statistics JSONB NOT NULL,
> 	CONSTRAINT mvcc_statistics_pkey PRIMARY KEY (id ASC),
> 	INDEX mvcc_statistics_idx_db_table_idx_created_at (database_id ASC, table_id ASC, index_id ASC, created_at ASC),
> ```

I think we just need one index like: 
`INDEX mvcc_statistics_idx_db_table_idx_created_at (created_at ASC, database_id ASC, table_id ASC, index_id ASC),`

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111365)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w, @maryliag, @rhu713, and @zachlite)

___
*[`pkg/sql/catalog/systemschema/system.go` line 4162 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/111365#-NfuYF_N2THeo8JlSTmw:-NfuYF_N2THeo8JlSTmx:b-6ozf8) ([raw file](https://github.com/cockroachdb/cockroach/blob/541f9d4f39bd67bef21803d0a74e5be170857c9f/pkg/sql/catalog/systemschema/system.go#L4162)):*
> ```Go
> 				KeyColumnNames: []string{
> 					"created_at_hash",
> 					"created_at",
> ```

Should `created_at_hash` and `created_at` keys be specified in column names? Having them here requires to specify them in `WHERE` clause to use the index.

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111365)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w, @maryliag, @rhu713, and @zachlite)

___
*[`pkg/sql/catalog/systemschema/system.go` line 1045 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/111365#-Nfuex_HDLaNcPsFWyIc:-Nfuex_HDLaNcPsFWyId:bgw1bb4) ([raw file](https://github.com/cockroachdb/cockroach/blob/541f9d4f39bd67bef21803d0a74e5be170857c9f/pkg/sql/catalog/systemschema/system.go#L1045)):*
> ```Go
> 	sqlStmtHashComputeExpr   = `mod(fnv32(crdb_internal.datums_to_bytes(aggregated_ts, app_name, fingerprint_id, node_id, plan_hash, transaction_fingerprint_id)), 8:::INT8)`
> 	sqlTxnHashComputeExpr    = `mod(fnv32(crdb_internal.datums_to_bytes(aggregated_ts, app_name, fingerprint_id, node_id)), 8:::INT8)`
> 	timestampHashComputeExpr = `mod(fnv32(crdb_internal.datums_to_bytes(created_at)), 8:::INT8)`
> ```

Should it be `16:::INT8` to match the same number of shards as below:
``` go
ShardBuckets: 16, // Cluster setting default.
```

**Pull request closed without merging**
