### PR TITLE
sql: fix createrole privilege check

### LINKED ISSUE #45857: sql: CREATEROLE is inconsistently implemented
The following works half-way:

1. `CREATE USER blah WITH CREATEROLE` -- works without error *but also without a license* (whereas `CREATE ROLE ... WITH CREATEROLE` fails with a license rror)

2. after the above succeeds, if I log in with user `blah`, then `CREATE USER foo` fails with `user blah does not have CREATEROLE privilege` (which is not true at this point)

### PR DESCRIPTION
**Pull request by RichardJCai**
Fixes #45857 

Fix issue where privileges would only be checked for roles that the user
is a member of but not the user itself.

Release note: none

Release justification: Bugfix: fixing bug where HasRoleOption doesn't check if the user itself has the role option. Added tests.

### CODE REVIEW

**Comment by knz** [comment]
please add the adequate "Release justification" line.

**Review by knz — APPROVED** [review]
oh nvm I didn't see it it's in the commit message.

Thanks

> Reviewed 1 of 1 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45910#-:-M24d3s-7y4r0mAq5ICh:b-l58on4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis)

**Comment by RichardJCai** [comment]
Yeah - sorry forgot to update the PR body after adding the release note to the commit

**Comment by RichardJCai** [comment]
bors r=knz

**Pull request merged**
