### PR TITLE
opt: support more SHOW statements

### PR DESCRIPTION
**Pull request by RaduBerinde**
These are all the SHOW statements I could move to `delegate` without adding more infrastructure. Others implement specific planNodes, or require more Catalog functionality.

#### opt: support SHOW JOBS

Release note: None

#### opt: support SHOW QUERIES

Release note: None

#### opt: support SHOW ROLE GRANTS

Release note: None

#### opt: support SHOW SCHEMAS

Release note: None

#### opt: support SHOW SEQUENCES

Also, some cleanup in the delegate package.

Release note: None

#### opt: support SHOW SESSIONS

Release note: None

#### opt: support SHOW SYNTAX

Also fixing the incorrect column name when used inside a query.

Release note: None

#### opt: support SHOW USERS

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: Nice work!

> Reviewed 4 of 4 files at r1, 15 of 15 files at r2, 3 of 3 files at r3, 7 of 7 files at r4, 9 of 9 files at r5, 3 of 3 files at r6, 7 of 7 files at r7, 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36955#-:-LcrlKCe-CnhTRD-mIwS:bcmw7ss)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz and @RaduBerinde)

___
*[pkg/sql/delegate/show_schemas.go, line 1 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/36955#-Lcrf7yyBKRyi_2tuXS_:-Lcrf7yyBKRyi_2tuXSa:bb6ht2j) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe877510a3e2d9f02cc5bd39465c45bbe4fb9f2/pkg/sql/delegate/show_schemas.go#L1)):*
> ```Go
> // Copyright 2018 The Cockroach Authors.
> ```

2019
___
*[pkg/sql/delegate/show_syntax.go, line 1 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/36955#-Lcrk9XjCxBOGhLZYvci:-Lcrk9XjCxBOGhLZYvcj:bb6ht2j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2ceb574050f8bf904507ec78ec174fb217f6368/pkg/sql/delegate/show_syntax.go#L1)):*
> ```Go
> // Copyright 2017 The Cockroach Authors.
> ```

2019
___
*[pkg/sql/delegate/show_syntax.go, line 28 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/36955#-LcrkClu9UWPlQHe7YiU:-LcrkClu9UWPlQHe7YiV:btlzppe) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2ceb574050f8bf904507ec78ec174fb217f6368/pkg/sql/delegate/show_syntax.go#L28)):*
> ```Go
> )
> 
> // delegateShowSyntax implements for SHOW SYNTAX. This statement is
> ```

[nit] implements for -> implements

**Review by knz — APPROVED** [review]
:lgtm: I concur

> Reviewed 3 of 4 files at r1, 14 of 15 files at r2, 3 of 3 files at r3, 7 of 7 files at r4, 9 of 9 files at r5, 3 of 3 files at r6, 7 of 7 files at r7, 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36955#-:-Ld-jodW3BEETmM0ROrt:b-o1k7z0)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Review by RaduBerinde — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36955#-:-Ld14HvzAevMr4hdiPp8:bz5mair)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/delegate/show_schemas.go, line 1 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/36955#-Lcrf7yyBKRyi_2tuXS_:-Ld12K0NAH_NSVU4ucz_:bnyuzf1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ebe877510a3e2d9f02cc5bd39465c45bbe4fb9f2/pkg/sql/delegate/show_schemas.go#L1)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

2019
</blockquote></details>

Updated (though this was a moved file and I think it's fine to keep as is when moving code).
___
*[pkg/sql/delegate/show_syntax.go, line 1 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/36955#-Lcrk9XjCxBOGhLZYvci:-Ld12h-x3WKnUeClRK79:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2ceb574050f8bf904507ec78ec174fb217f6368/pkg/sql/delegate/show_syntax.go#L1)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

2019
</blockquote></details>

Done.
___
*[pkg/sql/delegate/show_syntax.go, line 28 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/36955#-LcrkClu9UWPlQHe7YiU:-Ld12hMh9sw-y9A3GodN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f2ceb574050f8bf904507ec78ec174fb217f6368/pkg/sql/delegate/show_syntax.go#L28)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] implements for -> implements 
</blockquote></details>

Done.

**Pull request merged**
