### PR TITLE
roachtest: skip jepsen/multi-register

### PR DESCRIPTION
**Pull request by nvb**
There's no use running this every night until #36431 is fixed.

Release note: None

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
why not use `t.Skip(...)` ?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38743#-:-LjIRsV27zVKUo1259PU:bb7jyvm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

**Comment by nvanbenschoten** [comment]
Because it would require something like:
```
if testName == "multi-register" {
    t.Skip(...)
}
```
Do you prefer that? Happy to change it if so.

**Review by andreimatei — COMMENTED** [review]
I would... It's more like God intended.

LGTM either way

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38743#-:-LjM7zyG0m5NsMacN9zx:b-gzwl8j)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by nvanbenschoten** [comment]
Done.

bors r=god

**Pull request merged**
