### PR TITLE
storage: optimize replicaRaftStorage.Term

### PR DESCRIPTION
**Pull request by petermattis**
replicaRaftStorage.Term() is called frequently by the Raft code to retrieve
the term for the last index. Optimize this case by caching the term of the
last index in Replica.mu similar to the way we cache the last index itself.

Add raftEntryCache.getTerm() for retrieving the term for a particular log
entry. This code path is hit during Raft log truncation.

Use a read-only engine instead of a RocksDB snapshot for
replicaRaftStorage.{Term,Entries}. Both these methods are called from Raft
with Replica.mu held meaning there is no danger of the underlying data
changing. This avoids 2 cgo calls (to create and destroy the snapshot) in
the common case that the snapshot isn't even used because we've hit the
Raft entries cache.

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/replica_raftstorage.go, line 243 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16945#-KoZmzX6lXxTnftVX7Uu:-KoZmzX7FR4TBec1-smY:b7atkaz) ([raw file](https://github.com/cockroachdb/cockroach/blob/61d0ca8d2d1ef126a3c76ccf46325dec858d6e1d/pkg/storage/replica_raftstorage.go#L243)):*
> ```Go
> 	}
> 	// Try to retrieve the term for the desired entry from the entry cache.
> 	if term, ok := r.store.raftEntryCache.getTerm(r.RangeID, i); ok {
> ```

@bdarnell I'm mildly confused why we hit this code path when called from `evalTruncateLog`. In that case, I always see that `r.mu.lastIndex == i+1` and yet the entry is in the cache. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16945)*

**Comment by petermattis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/replica_raftstorage.go, line 243 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16945#-KoZmzX6lXxTnftVX7Uu:-KoZq0uhMiitIuW_T3ar:b-cgjpc8) ([raw file](https://github.com/cockroachdb/cockroach/blob/61d0ca8d2d1ef126a3c76ccf46325dec858d6e1d/pkg/storage/replica_raftstorage.go#L243)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

@bdarnell I'm mildly confused why we hit this code path when called from `evalTruncateLog`. In that case, I always see that `r.mu.lastIndex == i+1` and yet the entry is in the cache. 
</blockquote></details>

Ah, silly me, I was misreading my logging. When I'm seeing is that `r.mu.lastIndex > i`. Usually 1 or 2 indexes larger. I suppose we could keep track of the first index we know for a term (terms change rarely). On the other hand, this case mainly happens during Raft log truncation so it isn't that important to optimize.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16945)*

**Comment by bdarnell** [comment]
:lgtm:

Any benchmark numbers?

---

Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/storage/entry_cache.go, line 61 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16945#-Kohk1f79j8PUqynEfwp:-Kohk1f79j8PUqynEfwq:bne8ybt) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d321178d941c387fc18d7ea21d9b98fd78c6a7/pkg/storage/entry_cache.go#L61)):*
> ```Go
> 	bytes          uint64              // total size of the cache in bytes
> 	cache          *cache.OrderedCache // LRU cache of log entries, keyed by rangeID / log index
> 	fromKey        entryCacheKey
> ```

Comment that these are reused to avoid allocations. 

---

*[pkg/storage/entry_cache_test.go, line 60 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16945#-KohkVBbYdEo5LMvYbZQ:-KohkVBbYdEo5LMvYbZR:b7g8fxj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d321178d941c387fc18d7ea21d9b98fd78c6a7/pkg/storage/entry_cache_test.go#L60)):*
> ```Go
> 	}
> 	for _, e := range ents {
> 		term, ok := rec.getTerm(rangeID, e.Index)
> ```

This should also have a test where the entry is not found. 

---

*[pkg/storage/replica.go, line 292 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16945#-KohklUvJhue19605IML:-KohklUvJhue19605IMM:b-apz9dc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d321178d941c387fc18d7ea21d9b98fd78c6a7/pkg/storage/replica.go#L292)):*
> ```Go
> 		lastAssignedLeaseIndex uint64
> 		// Last index persisted to the raft log (not necessarily committed).
> 		lastIndex, lastTerm uint64
> ```

Comment that `lastTerm` may be zero even when `lastIndex` is non-zero (in which case the term will need to be retrieved from disk)

---

*[pkg/storage/replica_raftstorage.go, line 238 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16945#-KohmCtyIQd8E7r7Hbze:-KohmCtyIQd8E7r7Hbzf:b-us0l4s) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d321178d941c387fc18d7ea21d9b98fd78c6a7/pkg/storage/replica_raftstorage.go#L238)):*
> ```Go
> // Term implements the raft.Storage interface.
> func (r *replicaRaftStorage) Term(i uint64) (uint64, error) {
> 	if r.mu.lastIndex == i && r.mu.lastTerm != 0 {
> ```

Is the special-case caching of `lastTerm` still worth it now that we've gotten rid of the cgo calls and have the raftEntryCache? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16945#-:-KohmqCOVf3Bbocmvp7V:b-nwsk6b)*

**Comment by petermattis** [comment]
I don't have benchmark numbers, but I do have a profile. Prior to this change, `Term()` was consuming 500ms of time over a 10s profile. After this change it isn't visible. 

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/storage/entry_cache.go, line 61 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16945#-Kohk1f79j8PUqynEfwp:-KohtyxG3ZBwaYUsdNsH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d321178d941c387fc18d7ea21d9b98fd78c6a7/pkg/storage/entry_cache.go#L61)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Comment that these are reused to avoid allocations. 
</blockquote></details>

Done.

---

*[pkg/storage/entry_cache_test.go, line 60 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16945#-KohkVBbYdEo5LMvYbZQ:-KohuJg_DhJx13XDro8P:b-qz2be9) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d321178d941c387fc18d7ea21d9b98fd78c6a7/pkg/storage/entry_cache_test.go#L60)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This should also have a test where the entry is not found. 
</blockquote></details>

Added another test case down in `TestEntryCache`.

---

*[pkg/storage/replica.go, line 292 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16945#-KohklUvJhue19605IML:-Kohu_WDLsYwp3MYI7gP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d321178d941c387fc18d7ea21d9b98fd78c6a7/pkg/storage/replica.go#L292)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Comment that `lastTerm` may be zero even when `lastIndex` is non-zero (in which case the term will need to be retrieved from disk)
</blockquote></details>

Done.

---

*[pkg/storage/replica_raftstorage.go, line 238 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16945#-KohmCtyIQd8E7r7Hbze:-KohuqZ5fMajXYnzKG12:bvh24nd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2d321178d941c387fc18d7ea21d9b98fd78c6a7/pkg/storage/replica_raftstorage.go#L238)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Is the special-case caching of `lastTerm` still worth it now that we've gotten rid of the cgo calls and have the raftEntryCache? 
</blockquote></details>

Yes. This is the common case when appending entries. Retrieval from the entry cache was still showing up on profiles, even with `getTerm`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16945#-:-Kohvta4zZ5Uds8IOu_n:bdjjs5h)*

**Comment by petermattis** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica_state.go, line 644 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/16945#-Koi6x-NXM9euzphl6KN:-Koi6x-NXM9euzphl6KO:b-o58erd) ([raw file](https://github.com/cockroachdb/cockroach/blob/201abd147206f12b74c146561c6b2f881ece0895/pkg/storage/replica_state.go#L644)):*
> ```Go
> func (rec ReplicaEvalContext) Term(i uint64) (uint64, error) {
> 	rec.repl.mu.RLock()
> 	defer rec.repl.mu.RUnlock()
> ```

@bdarnell This appears to have been an oversight that wasn't affecting anything prior to this change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16945)*

**Comment by bdarnell** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica_state.go, line 644 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/16945#-Koi6x-NXM9euzphl6KN:-Koi8vKAo23dr_MEfzWE:b-qp44zq) ([raw file](https://github.com/cockroachdb/cockroach/blob/201abd147206f12b74c146561c6b2f881ece0895/pkg/storage/replica_state.go#L644)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

@bdarnell This appears to have been an oversight that wasn't affecting anything prior to this change.
</blockquote></details>

LGTM, but is it safe to use RLock instead of Lock (e.g. does it populate the cache in a way that would need a write lock)? It doesn't look like it does, but in that case the method should be renamed to raftTermRLocked.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16945)*

**Comment by bdarnell** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/storage/replica_state.go, line 644 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/16945#-Koi6x-NXM9euzphl6KN:-Koi9bWoyjd9_YnPqBhu:bl4wdrc) ([raw file](https://github.com/cockroachdb/cockroach/blob/201abd147206f12b74c146561c6b2f881ece0895/pkg/storage/replica_state.go#L644)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

LGTM, but is it safe to use RLock instead of Lock (e.g. does it populate the cache in a way that would need a write lock)? It doesn't look like it does, but in that case the method should be renamed to raftTermRLocked.
</blockquote></details>

Now that I look at it, I don't see why the current implementation would need any lock at all. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16945)*

**Comment by petermattis** [comment]
Review status: 0 of 6 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/storage/replica_state.go, line 644 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/16945#-Koi6x-NXM9euzphl6KN:-Koi9v6jo_n5x_OaYMlq:bly052k) ([raw file](https://github.com/cockroachdb/cockroach/blob/201abd147206f12b74c146561c6b2f881ece0895/pkg/storage/replica_state.go#L644)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Now that I look at it, I don't see why the current implementation would need any lock at all. 
</blockquote></details>

The current implementation doesn't. My changes do because we're accessing `Replica.mu.last{Index,Term}`.  

Renamed `raftTermLocked` to `raftTermRLocked`. Note that the entry cache contains its own synchronization. I bet `raftTermLocked` was named as such because it is usually called from Raft where we're holding `Replica.mu` locked for writing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16945)*

**Pull request merged**
