### PR TITLE
Replace the default golang stress with our fork of it

### PR DESCRIPTION
**Pull request by BramGruneir**
stress now has the ability to run
- X number of times
- for X time
- until X failures

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4072)

### CODE REVIEW

**Comment by vivekmenezes** [comment]
LGTM

**Comment by bdarnell** [comment]
You also need to update the other line that mentions `stress` (and gives the revision id)

**Comment by BramGruneir** [comment]
updated

**Comment by petermattis** [comment]
LGTM

**Pull request merged**
