### PR TITLE
*: Update crlfmt version and fix improperly formatted functions

### PR DESCRIPTION
**Pull request by a-robinson**
Pull in fix from https://github.com/cockroachdb/crlfmt/pull/3

@jordanlewis

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9735)

### CODE REVIEW

**Comment by tamird** [comment]
LGTM

**Review by jordanlewis — COMMENTED** [review]
LGTM

**Review by jordanlewis — APPROVED** [review]

**Comment by andreimatei** [comment]
I think this change triggered this check error for me:
```
-func (s *Store) maybeMergeTimestampCaches(
-	subsumingRng *Replica,
-	subsumedRng *Replica,
-) error {
+func (s *Store) maybeMergeTimestampCaches(subsumingRng *Replica, subsumedRng *Replica) error {
```

So it's forcing me to fill the line up to 100 chars. Was this intended? Can we relax this? I think it's way too prescriptive.

**Comment by andreimatei** [comment]
Oops, sorry, this hasn't been merged. But then maybe someone here what else changed recently?

**Comment by a-robinson** [comment]
@jordanlewis added it yesterday in #8823. The idea is to automatically enforce the style choice just like gofmt does for everything else, so relaxing it would kind of defeat the purpose.

**Pull request merged**
