### PR TITLE
sql/tenant: add idle detection and exit flag

### PR DESCRIPTION
**Pull request by darinpp**
Previosuly `mt start-sql` will keep cockraochdb running indefinitelly
regardless of the sql clients connected to the server.
This PR adds a flag `--idle-exit-after` that can be used to monitor the
active SQL connections and terminate the server if there are no more
clients. The flag specifies the duration of the initial interval during
which the monitoring will not be active. Once that interval is over the
monitor will activate. When the number of active connections drops to
zero, the monitor will start a 30sec countdown timer and will terminate
the server once the timer reaches zero. If a new connection comes before
the countdown timer reaches zero, the countdown will reset and the
monitor will agian wait for the number of active connections to drop to
zero.

Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Question about the use case: what is the plan to deal with SQL *idle* connections? That's pretty common when client drivers use connection pools: they establish TCP connections then do nothing with them.

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59743#-:-MSb9OEk7s3t2KBDLsDW:b-xesigj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @alyshanjahani-crl, @andy-kimball, @darinpp, and @spaskob)

___
*[pkg/server/idle_monitor.go, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59743#-MSb7wXY8PVTtL2F4gQ8:-MSb7wXY8PVTtL2F4gQ9:b9muodx) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b70b2aeddd2336d761dc31835bedc481825ab62/pkg/server/idle_monitor.go#L42)):*
> ```Go
> 	} else {
> 		// Default if there isn't an overwrite
> 		monitor.countdownDuration = 30 * time.Second
> ```

please extract this constant into a global scope go constant, give it a name, 
and remind the reader of the code in a comment that they need to update the explanation in cli/cliflags/flags.go  if they ever change the value.
___
*[pkg/server/idle_monitor.go, line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59743#-MSb7N0I0CPYL0QHIOu6:-MSb7N0J-ejhx2c6so4H:bm7g1pv) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b70b2aeddd2336d761dc31835bedc481825ab62/pkg/server/idle_monitor.go#L45)):*
> ```Go
> 	}
> 	log.VEventf(ctx, 2,
> 		"Create with warmup %s and countdown %s durations", warmupDuration,
> ```

nit: no capital at the start of logging
___
*[pkg/server/idle_monitor.go, line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59743#-MSb7OfD4QbFQEeBcKBX:-MSb7OfD4QbFQEeBcKBY:b4qm2zr) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b70b2aeddd2336d761dc31835bedc481825ab62/pkg/server/idle_monitor.go#L51)):*
> ```Go
> 	// countdown timer if the number of active connections is zero.
> 	time.AfterFunc(warmupDuration, func() {
> 		log.VEventf(ctx, 2, "Warmup duration is over")
> ```

ditto, here and throughout this file
___
*[pkg/server/testserver.go, line 639 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59743#-MSb8BUWC48wbbcMRs6T:-MSb8BUWC48wbbcMRs6U:b-xv8kpu) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b70b2aeddd2336d761dc31835bedc481825ab62/pkg/server/testserver.go#L639)):*
> ```Go
> 
> // SetupIdleMonitor will monitor the active connections and if there are none,
> // will activate a 30sec countdown timer and terminate the application. The
> ```

you can refer to the name of the constant in the comment here - otherwise the duration will become stale.
___
*[pkg/server/testserver.go, line 646 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59743#-MSb8PZTC_kjLAW1Ui0A:-MSb8PZTC_kjLAW1Ui0B:b-2v6awp) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b70b2aeddd2336d761dc31835bedc481825ab62/pkg/server/testserver.go#L646)):*
> ```Go
> ) *IdleMonitor {
> 	if warmupDuration != 0 {
> 		log.VEventf(ctx, 2, "Idle exit will activate after warmup duration of %s\n", warmupDuration)
> ```

nit: as before, no capitals at the start of logs, here and below
___
*[pkg/server/testserver.go, line 658 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59743#-MSb9-EU-grPPkNI04nH:-MSb9-EU-grPPkNI04nI:b-b2wnej) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b70b2aeddd2336d761dc31835bedc481825ab62/pkg/server/testserver.go#L658)):*
> ```Go
> 			} else if state == http.StateClosed {
> 				oldConnStateHandler(conn, state)
> 				idleMonitor.CloseConnection(ctx)
> ```

you likely need to invoke this with a `defer` before calling the old handler, otherwise you won't get the right behavior in case there's a panic
___
*[pkg/server/testserver_test.go, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59743#-MSb9C5G0aEEn8VOb8YJ:-MSb9C5G0aEEn8VOb8YK:b-gx3xa7) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b70b2aeddd2336d761dc31835bedc481825ab62/pkg/server/testserver_test.go#L99)):*
> ```Go
> 
> 	require.True(t, monitor.activated)
> }
> ```

Can you also create a new test (you'll probably need a new file with `package server_test`), which establishes a SQL client connection and checks that the idle checker fires.

**Review by andy-kimball — COMMENTED** [review]
Darin has already implemented logic in the SQLProxy to disconnect connections that have been idle for too long (I believe 5 minutes). So if a user stops interacting with the database, all connections will eventually be disconnected, and then the SQL tenant pod(s) will shut themselves down.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59743#-:-MScgBHK5wvtR91k0FB8:b-slsxew)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @alyshanjahani-crl, @darinpp, and @spaskob)

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59743)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @alyshanjahani-crl, @darinpp, and @spaskob)

___
*[pkg/base/config.go, line 235 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59743#-MScgcRqEhGqvzz37lVA:-MScgcRqEhGqvzz37lVB:bnd49s6) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b70b2aeddd2336d761dc31835bedc481825ab62/pkg/base/config.go#L235)):*
> ```Go
> 	AutoInitializeCluster bool
> 
> 	// idleExistAfter, If nonzero, will cause the server to run normally for the
> ```

NIT: Should be `IdleExitAfter` (capitalize and spelling)

**Review by darinpp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59743)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @alyshanjahani-crl, @andy-kimball, @knz, and @spaskob)

___
*[pkg/base/config.go, line 235 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59743#-MScgcRqEhGqvzz37lVA:-MStEW9S8Ql807nZSxXx:b-7ql1td) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b70b2aeddd2336d761dc31835bedc481825ab62/pkg/base/config.go#L235)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: Should be `IdleExitAfter` (capitalize and spelling)
</blockquote></details>

fixed
___
*[pkg/server/idle_monitor.go, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59743#-MSb7wXY8PVTtL2F4gQ8:-MStEZeWDszWQTaBlsNA:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b70b2aeddd2336d761dc31835bedc481825ab62/pkg/server/idle_monitor.go#L42)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

please extract this constant into a global scope go constant, give it a name, 
and remind the reader of the code in a comment that they need to update the explanation in cli/cliflags/flags.go  if they ever change the value.
</blockquote></details>

done
___
*[pkg/server/idle_monitor.go, line 45 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59743#-MSb7N0I0CPYL0QHIOu6:-MStEcVa8eGAFXCkYfTW:b-7ql1td) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b70b2aeddd2336d761dc31835bedc481825ab62/pkg/server/idle_monitor.go#L45)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: no capital at the start of logging
</blockquote></details>

fixed
___
*[pkg/server/idle_monitor.go, line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59743#-MSb7OfD4QbFQEeBcKBX:-MStEdel5qDAgZjU5GOz:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b70b2aeddd2336d761dc31835bedc481825ab62/pkg/server/idle_monitor.go#L51)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto, here and throughout this file
</blockquote></details>

done
___
*[pkg/server/testserver.go, line 639 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59743#-MSb8BUWC48wbbcMRs6T:-MStElgX-Ts5uRwffYJ1:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b70b2aeddd2336d761dc31835bedc481825ab62/pkg/server/testserver.go#L639)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

you can refer to the name of the constant in the comment here - otherwise the duration will become stale.
</blockquote></details>

done
___
*[pkg/server/testserver.go, line 646 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59743#-MSb8PZTC_kjLAW1Ui0A:-MStFWXj1NJskAhbRLld:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b70b2aeddd2336d761dc31835bedc481825ab62/pkg/server/testserver.go#L646)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

nit: as before, no capitals at the start of logs, here and below
</blockquote></details>

done
___
*[pkg/server/testserver.go, line 658 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59743#-MSb9-EU-grPPkNI04nH:-MStFYiB8p9r305gSo9n:bc8boik) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b70b2aeddd2336d761dc31835bedc481825ab62/pkg/server/testserver.go#L658)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

you likely need to invoke this with a `defer` before calling the old handler, otherwise you won't get the right behavior in case there's a panic
</blockquote></details>

changed it
___
*[pkg/server/testserver_test.go, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59743#-MSb9C5G0aEEn8VOb8YJ:-MStFc5gBQyr8s88G3a_:b1u26lj) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b70b2aeddd2336d761dc31835bedc481825ab62/pkg/server/testserver_test.go#L99)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Can you also create a new test (you'll probably need a new file with `package server_test`), which establishes a SQL client connection and checks that the idle checker fires.
</blockquote></details>

I added a new test that is in `server_test`

**Review by knz — APPROVED** [review]
:lgtm: after you fix the copyright date on the two new files

> Reviewed 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59743#-:-MT0dEoU-cIhdapNBrQN:bh2ov5q)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball and @darinpp)

___
*[pkg/server/idle_monitor.go, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59743#-MT0d1GqCjlrqEcxFtZx:-MT0d1GqCjlrqEcxFtZy:bb6ht36) ([raw file](https://github.com/cockroachdb/cockroach/blob/931d80336f288bb86c68a10cc5f086033e426d6f/pkg/server/idle_monitor.go#L1)):*
> ```Go
> // Copyright 2014 The Cockroach Authors.
> ```

2021
___
*[pkg/server/idle_monitor_test.go, line 1 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/59743#-MT0d57J7MtAsemGJeLf:-MT0d57J7MtAsemGJeLg:bb6ht36) ([raw file](https://github.com/cockroachdb/cockroach/blob/931d80336f288bb86c68a10cc5f086033e426d6f/pkg/server/idle_monitor_test.go#L1)):*
> ```Go
> // Copyright 2014 The Cockroach Authors.
> ```

2021

**Pull request merged**
