### PR TITLE
sqlsmith: round 3

### PR DESCRIPTION
**Pull request by madelynnblue**
Release note: None

### CODE REVIEW

**Review by justinj — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35728#-:-L_wbZ-61KQcqnFKSmMu:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mjibson)

___
*[pkg/internal/sqlsmith/relational.go, line 429 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/35728#-L_wb9Hs68CURXXCcgRR:-L_wb9Hs68CURXXCcgRS:b-9xti9q) ([raw file](https://github.com/cockroachdb/cockroach/blob/edb2d65c3d1ef4b4e4f3c5fe7d4e37fb18543ee2/pkg/internal/sqlsmith/relational.go#L429)):*
> ```Go
> }
> 
> func (s *scope) makeUpdate(refs colRefs) (*tree.Update, *tableRef, bool) {
> ```

I think `refs` is ignored in this function, so these will never refer to any parent scoped columns.
___
*[pkg/internal/sqlsmith/relational.go, line 442 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/35728#-L_wah53DK18e_vTtEZK:-L_wah53DK18e_vTtEZL:bexxjxd) ([raw file](https://github.com/cockroachdb/cockroach/blob/edb2d65c3d1ef4b4e4f3c5fe7d4e37fb18543ee2/pkg/internal/sqlsmith/relational.go#L442)):*
> ```Go
> 		Returning: &tree.NoReturningClause{},
> 	}
> 	upRefs := colRefs.extend()
> ```

Maybe comment that this is doing a copy so that the individual updates can refer to the columns too. Or add a `copy` method or something?
___
*[pkg/internal/sqlsmith/relational.go, line 447 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/35728#-L_w_Dd55vD1yhEJSN50:-L_w_Dd55vD1yhEJSN51:b-du0mgu) ([raw file](https://github.com/cockroachdb/cockroach/blob/edb2d65c3d1ef4b4e4f3c5fe7d4e37fb18543ee2/pkg/internal/sqlsmith/relational.go#L447)):*
> ```Go
> 		ref := upRefs[n]
> 		upRefs = append(upRefs[:n], upRefs[n+1:]...)
> 		update.Exprs = append(update.Exprs, &tree.UpdateExpr{
> ```

If you want to avoid errors, I think this needs to take care to not write into computed columns (or write `NULL` into non-nullable columns).
___
*[pkg/internal/sqlsmith/relational.go, line 449 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/35728#-L_wb03eEjEkxllVM0wN:-L_wb03eEjEkxllVM0wO:b32vuk) ([raw file](https://github.com/cockroachdb/cockroach/blob/edb2d65c3d1ef4b4e4f3c5fe7d4e37fb18543ee2/pkg/internal/sqlsmith/relational.go#L449)):*
> ```Go
> 		update.Exprs = append(update.Exprs, &tree.UpdateExpr{
> 			Names: tree.NameList{ref.item.ColumnName},
> 			Expr:  makeScalar(s, ref.typ, colRefs),
> ```

I 
___
*[pkg/internal/sqlsmith/scalar.go, line 220 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/35728#-L_wZgL92iSe5pCUFkk6:-L_wZgLA6w7WflksuG43:b6816u1) ([raw file](https://github.com/cockroachdb/cockroach/blob/6683be4597ae250d2dc8f755c81e6eab3bde9cfc/pkg/internal/sqlsmith/scalar.go#L220)):*
> ```Go
> }
> 
> var compareOps = [...]tree.ComparisonOperator{
> ```

There's others too, maybe add a TODO to handle these like we handle bin ops? (since there can be special ones like `@>`, `?`, etc).

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35728)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj and @mjibson)

___
*[pkg/internal/sqlsmith/relational.go, line 449 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/35728#-L_wb03eEjEkxllVM0wN:-L_y1mwu5hDSBDXGUB-5:b9rb3il) ([raw file](https://github.com/cockroachdb/cockroach/blob/edb2d65c3d1ef4b4e4f3c5fe7d4e37fb18543ee2/pkg/internal/sqlsmith/relational.go#L449)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

I 
</blockquote></details>

Did you have a comment about this line?

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35728)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj and @mjibson)

___
*[pkg/internal/sqlsmith/relational.go, line 442 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/35728#-L_wah53DK18e_vTtEZK:-L_zF0Db2K43dlGojCfW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/edb2d65c3d1ef4b4e4f3c5fe7d4e37fb18543ee2/pkg/internal/sqlsmith/relational.go#L442)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

Maybe comment that this is doing a copy so that the individual updates can refer to the columns too. Or add a `copy` method or something?
</blockquote></details>

Done.
___
*[pkg/internal/sqlsmith/relational.go, line 447 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/35728#-L_w_Dd55vD1yhEJSN50:-L_zI88X8O68ZZtBg3RW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/edb2d65c3d1ef4b4e4f3c5fe7d4e37fb18543ee2/pkg/internal/sqlsmith/relational.go#L447)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

If you want to avoid errors, I think this needs to take care to not write into computed columns (or write `NULL` into non-nullable columns).
</blockquote></details>

Done.

**Pull request merged**
