### PR TITLE
storage: remove getQuorumIndex from computeTruncateDecision

### PR DESCRIPTION
**Pull request by irfansharif**
Some lineage here: `getQuorumIndex` was initially `getBehindIndex`, and was changed to getQuorumIndex to incorporate pending snapshots (https://github.com/cockroachdb/cockroach/commit/561398f0cace0885cde037be17d5eb23e80fb45b).  Previous to this we started off computeTruncateDecision using raft.Status.Commit. As of (https://github.com/cockroachdb/cockroach/commit/b64bdc99f2236c1d26f3043d376689cd6af69be2), we refactored log truncation decision making and pulled out pending snapshot logic back out of getQuorumIndex. `getQuorumIndex` was then far too similar to raft.Status.Commit but not quite. Given that we already use raft.Status.Progress in `computeTruncateDecision` to track lagging, yet recently active followers, we can get rid of `getQuorumIndex` altogether to simplify things.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
I looked through this but I don't feel confident giving it an :lgtm:. 

It seems like the case where this change might take effect is the case where there aren't a quorum of replicas which are recently active. That seems like a strange case to me. I agree that if all replicas are recently active then we'll protect to their `Match` in `raft.Status.Progress`.

This is a treacherous place to make code changes so I'm going to be cautious. This change makes me personally uncomfortable without clear motivation on why we should do it or concrete cases where it helps. Maybe @nvanbenschoten or @tbg will have more concrete thoughts. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43136#-:-Lw-ZP6r1dc3iyxv9kW8:b5ej74)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @irfansharif, and @nvanbenschoten)

___
*[pkg/storage/raft_log_queue.go, line 393 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43136#-Lw-YckN36L0GMrqB3dE:-Lw-YckN36L0GMrqB3dF:b-nsx0ud) ([raw file](https://github.com/cockroachdb/cockroach/blob/94daed5a794b1d62c82be1a418f6be3837044790/pkg/storage/raft_log_queue.go#L393)):*
> ```Go
> func computeTruncateDecision(input truncateDecisionInput) truncateDecision {
> 	decision := truncateDecision{Input: input}
> 	// XXX: RecentlyActive is used as "RecentlyActive", confirm via commit
> ```

I haven't seen `XXX` in comments before. Usually we use either `NB` for notes and `TODO` for things to address.

**Review by irfansharif — COMMENTED** [review]
TFTR. I agree it's treacherous, and I also think the API around `getQuorumIndex` is terribly confusing. The assertions I added towards the end of `computeTruncateDecision` (as of https://github.com/cockroachdb/cockroach/pull/42495) were problematic because of this. I had listed the invariant that `NewFirstIndex <= QuorumIndex (if != 0)` but this was incorrect. Copying over from elsewhere:

> QuorumIndex could actually be less than FirstIndex. Consider a Raft group with first-last indexes [(100-112), (116-124), (116-124)], when a new replica is added it starts off with a match index of 0, i.e. [(0,0), (100-112), (116-124), (116-124)]. Naively, we'd expect the quorum index to be 116, but it's 100. The FirstIndex at the leaseholder will be 116, and thus we have QuorumIndex < FirstIndex <= NewFirstIndex. How do we think about the invariants in this situation? We don't want to truncate past the "quorum index", but new replicas muddle our computation of this "quorum index".

This was the motivation for the change.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43136#-:-Lw4qLAR2gjF6XwWoq-K:b-bmya21)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/storage/raft_log_queue.go, line 393 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43136#-Lw-YckN36L0GMrqB3dE:-Lw4q9Ng4zfGclvA-2XR:b-h49okr) ([raw file](https://github.com/cockroachdb/cockroach/blob/94daed5a794b1d62c82be1a418f6be3837044790/pkg/storage/raft_log_queue.go#L393)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I haven't seen `XXX` in comments before. Usually we use either `NB` for notes and `TODO` for things to address. 
</blockquote></details>

These aren't going to go in, they're open questions I had for reviewers.

**Review by nvb — COMMENTED** [review]
This change seems sane to me. `getQuorumIndex` is confusing and it's nice that this gets rid of it. I also appreciate you digging through the history and writing up how we got to this state.

I think @bdarnell should give this a pass as well.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43136#-:-LwKCknh2dKvwbOKR3yG:b-ytiy20)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @irfansharif, and @nvanbenschoten)

___
*[pkg/storage/raft_log_queue.go, line 394 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43136#-LwJgn_Q5Yl4N_o9wN7L:-LwJgn_Q5Yl4N_o9wN7M:bevhhs5) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8b8dfe24084da62f5b5f8aea9f45d7e30b402f2/pkg/storage/raft_log_queue.go#L394)):*
> ```Go
> 	// XXX: (Ask about this during review) We're using progress.RecentActive to
> 	// determine recent activity, and only care about lagging followers that
> 	// were recently active. Is this proper usage of RecentActive?
> ```

I'm not sure about `RecentActive`. It looks to only ever be set to false when using CheckQuorum, which we don't use anymore, and on leader elections. I wonder if we should be using the `lastUpdateTimes` here instead? @bdarnell do you know anything about this?
___
*[pkg/storage/raft_log_queue.go, line 410 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43136#-LwJiALx4B5fKv4gzLc7:-LwJiALx4B5fKv4gzLc8:b-21ccxj) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8b8dfe24084da62f5b5f8aea9f45d7e30b402f2/pkg/storage/raft_log_queue.go#L410)):*
> ```Go
> 	// RaftStatus.Commit is updated at propose time.
> 	//
> 	// XXX: (Ask about this during review) Is the comment above still applicable?
> ```

We call `maybeCommit` in `raft.appendEntry`, which immediately makes its way to the `HardState` for single-replica raft groups. However, the lastIndex is only updated when the entries are actually appended to the replica's raft log (in a handleRaftReady call). So I think this is still applicable.

**Review by bdarnell — COMMENTED** [review]
LGTM. I agree this seems like a nice simplification. I can't see any problem with it, although I'm not sure how exactly we'd test this change to make sure of that. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43136#-:-LwKjfHP6QS1MpmcQ5kI:bxv4tqs)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @irfansharif, and @nvanbenschoten)

___
*[pkg/storage/raft_log_queue.go, line 394 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43136#-LwJgn_Q5Yl4N_o9wN7L:-LwKXgXHEAEtd6Dkll3E:b-yy7tpp) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8b8dfe24084da62f5b5f8aea9f45d7e30b402f2/pkg/storage/raft_log_queue.go#L394)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm not sure about `RecentActive`. It looks to only ever be set to false when using CheckQuorum, which we don't use anymore, and on leader elections. I wonder if we should be using the `lastUpdateTimes` here instead? @bdarnell do you know anything about this?
</blockquote></details>

You're right that raft always sets RecentActive to true for us, but we override it in updateRaftProgressFromActivity. Overwriting the raft field is ugly, but that means it's doing what we want here: as long as followers are active, we don't want to truncate in a way that will force a snapshot.

**Review by irfansharif — COMMENTED** [review]
TFTRs, I'm not sure how to test this either but I'm made more comfortable given it's early-ish in the release cycle. I'll keep a look out for any resulting flakiness.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43136#-:-LwPJRyH-twWA_gsPc9k:b-81q4q9)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @bdarnell, and @nvanbenschoten)

___
*[pkg/storage/raft_log_queue.go, line 394 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43136#-LwJgn_Q5Yl4N_o9wN7L:-LwPJMyK4MVesyKJLsnL:bdiq3cw) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8b8dfe24084da62f5b5f8aea9f45d7e30b402f2/pkg/storage/raft_log_queue.go#L394)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

You're right that raft always sets RecentActive to true for us, but we override it in updateRaftProgressFromActivity. Overwriting the raft field is ugly, but that means it's doing what we want here: as long as followers are active, we don't want to truncate in a way that will force a snapshot. 
</blockquote></details>

Cool, thanks for confirming.

**Comment by irfansharif** [comment]
bors r=bdarnell

**Comment by irfansharif** [comment]
@sumeerbhola this may be of passing interest to you.

**Pull request merged**
