### PR TITLE
tenantcapabilities: gate tenant access to node metadata and tsdb

### LINKED ISSUE #96975: server: add tenant capability gating to Node and TSDB queries for DB Console
Non-system tenants should access Node-level metadata and TSDB via separate tenant capabilities granted by the system tenant.
These endpoints should use SQL-level permissioning if necessary, but delegate to the KV layer to fulfill the request.

Epic: CRDB-12100

Jira issue: CRDB-24442

### PR DESCRIPTION
**Pull request by dhartunian**
Previously, tenants were given access via the kv connector, to node level
metrics and metadata. This ability should be gated behind a capability in order
to give operators control over what cluster-level information their application
tenants would have access to.

This commit adds authorization checks using tenant capabilities for the node
metadata query RPC and the TSDB query RPC.

The connection between the specific capability in the RPC it enables, is
encoded in the auth_tenant.go file within the `tenantAuthorizer`. The
capability `Authorizer` type simply provides per-capability check utility
methods.

The `NodesUI` endpoint contains an additional SQL permission gate, which is
honored by checking at the tenant-level, and then delegating (via capability
gate) to a system tenant level `NodesTenant` endpoint that does no additional
SQL gating. Delegating to a system tenant `NodesUI` implementation would fail
since the tenant does not have system-level SQL permissions. The liveness and
TSDB endpoints do no additional checking at time of writing, hence no changes
are made there.

Resolves https://github.com/cockroachdb/cockroach/issues/96975

Epic: CRDB-12100

Release note: None

### CODE REVIEW

**Comment by dhartunian** [comment]
First commit is by @arulajmani and being reviewed in #96390. 
Please only review commit #2.

**Review by abarganier — APPROVED** [review]
Nice work! It's great to see this coming together. 

Only a small nit and clarifying question, but otherwise :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96319#-:-NNgpZHA1xJXuM8yeTex:b-7gxpmq)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian)

___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiestestutils/testutils.go` line 126 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96319#-NNgmCE8Dqc26jLn1l4q:-NNgmCE8Dqc26jLn1l4r:bxfisce) ([raw file](https://github.com/cockroachdb/cockroach/blob/18d10f686b115e9531e6e2a89fde8ed09ec06101/pkg/multitenant/tenantcapabilities/tenantcapabilitiestestutils/testutils.go#L126)):*
> ```Go
> 
> func parseTenantCapability(t *testing.T, input string) tenantcapabilitiespb.TenantCapabilities {
> 	var cap = tenantcapabilitiespb.TenantCapabilities{}
> ```

nit: do we need the `var x = ...` syntax here?



_Code quote:_
```Go
var cap =
```
___
*[`pkg/server/status.go` line 1581 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96319#-NNgnnpR6GyBmnwv29vb:-NNgnnpS69RNjlf6rf5J:b-n7u51v) ([raw file](https://github.com/cockroachdb/cockroach/blob/18d10f686b115e9531e6e2a89fde8ed09ec06101/pkg/server/status.go#L1581)):*
> ```Go
> 	if err != nil {
> 		if !grpcutil.IsAuthError(err) {
> 			return nil, err
> ```

I *think* I understand this piece, but just to check my own understanding...

I know the tenant connector validates the tenant capability in its own authorization step. Is that tenant capability a subset of the `ViewClusterMetadataPermission` we're checking for here, meaning that an auth error of the broader permission doesn't necessarily mean we don't have the specific tenant capability? 



_Code quote:_
```Go
		if !grpcutil.IsAuthError(err) {
			return nil, err
		}
```

**Review by knz — COMMENTED** [review]
> Reviewed 24 of 24 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96319)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @abarganier and @dhartunian)

___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer.go` line 109 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96319#-NNgpTXV9WQpmNIGhPVS:-NNgpTXV9WQpmNIGhPVT:b5dj299) ([raw file](https://github.com/cockroachdb/cockroach/blob/18d10f686b115e9531e6e2a89fde8ed09ec06101/pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer.go#L109)):*
> ```Go
> 		)
> 	}
> 	if !cp.CanViewTsdbMetrics {
> ```

Q: is there a way to filter out timeseries queries to only allow to timeseries from the storage layer, but _forbid access to timeseries for other tenants_. 
___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer.go` line 110 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96319#-NNgpQPV1P9fzWwNEr7c:-NNgpQPV1P9fzWwNEr7d:b-yyh2xk) ([raw file](https://github.com/cockroachdb/cockroach/blob/18d10f686b115e9531e6e2a89fde8ed09ec06101/pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer.go#L110)):*
> ```Go
> 	}
> 	if !cp.CanViewTsdbMetrics {
> 		return errors.Newf("tenant %s does not have capability to query timseries data", tenID)
> ```

nit: timseries -> timeseries
___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiespb/capabilities.proto` line 37 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96319#-NNgpqsr2Th8jnJi8Bvi:-NNgpqsr2Th8jnJi8Bvj:b-4qvrq4) ([raw file](https://github.com/cockroachdb/cockroach/blob/18d10f686b115e9531e6e2a89fde8ed09ec06101/pkg/multitenant/tenantcapabilities/tenantcapabilitiespb/capabilities.proto#L37)):*
> ```protobuf
>   bool can_view_node_info = 2;
> 
>   // CanViewTSDBMetrics, if set to true,
> ```

can you add more words? And mention something like "does not give access to timeseries _from other tenants_" in there.
___
*[`pkg/rpc/context.go` line 427 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96319#-NNgq15JBUHTMMkeTc0A:-NNgq15JBUHTMMkeTc0B:bwol7fv) ([raw file](https://github.com/cockroachdb/cockroach/blob/18d10f686b115e9531e6e2a89fde8ed09ec06101/pkg/rpc/context.go#L427)):*
> ```Go
> 	loopbackDialFn func(context.Context) (net.Conn, error)
> 
> 	TenantCapabilitiesAuthorizer tenantcapabilities.Authorizer
> ```

Please add an explanatory comment.
___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer_test.go` line 74 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96319#-NNgqSBUDJnLEi9jMqTu:-NNgqSBUDJnLEi9jMqTv:b-oxc4o2) ([raw file](https://github.com/cockroachdb/cockroach/blob/18d10f686b115e9531e6e2a89fde8ed09ec06101/pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer_test.go#L74)):*
> ```Go
> 				}
> 				return err.Error()
> 			case "has-capability-for-tsdb-metrics":
> ```

nit: add an empty line above

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96319)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi, @abarganier, and @knz)

___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer.go` line 109 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96319#-NNgpTXV9WQpmNIGhPVS:-NNhvyOuE-qHZjOqsoxx:b-2yq1b5) ([raw file](https://github.com/cockroachdb/cockroach/blob/18d10f686b115e9531e6e2a89fde8ed09ec06101/pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer.go#L109)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Q: is there a way to filter out timeseries queries to only allow to timeseries from the storage layer, but _forbid access to timeseries for other tenants_. 
</blockquote></details>

Currently no, but the storage of per-tenant metrics doesn't exist yet either. @aadityasondhi is working on the code to tag metrics per-tenant that will allow us to serve tenant-scoped metrics.
___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer.go` line 110 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96319#-NNgpQPV1P9fzWwNEr7c:-NNhw8X455C5at8pn0Oe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/18d10f686b115e9531e6e2a89fde8ed09ec06101/pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer.go#L110)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: timseries -> timeseries
</blockquote></details>

Done.
___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiespb/capabilities.proto` line 37 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96319#-NNgpqsr2Th8jnJi8Bvi:-NNhwFXSEPsMuOYfZrBo:b-hilcqu) ([raw file](https://github.com/cockroachdb/cockroach/blob/18d10f686b115e9531e6e2a89fde8ed09ec06101/pkg/multitenant/tenantcapabilities/tenantcapabilitiespb/capabilities.proto#L37)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

can you add more words? And mention something like "does not give access to timeseries _from other tenants_" in there.
</blockquote></details>

Adding message, but it will say the opposite if what you're requesting for now as discussed in earlier thread.
___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiestestutils/testutils.go` line 126 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96319#-NNgmCE8Dqc26jLn1l4q:-NNhwcFX2T8gQlW5jap6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/18d10f686b115e9531e6e2a89fde8ed09ec06101/pkg/multitenant/tenantcapabilities/tenantcapabilitiestestutils/testutils.go#L126)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

nit: do we need the `var x = ...` syntax here?
</blockquote></details>

Done.
___
*[`pkg/rpc/context.go` line 427 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96319#-NNgq15JBUHTMMkeTc0A:-NNhwoPl3xNN0gxTgklA:bkbmxpv) ([raw file](https://github.com/cockroachdb/cockroach/blob/18d10f686b115e9531e6e2a89fde8ed09ec06101/pkg/rpc/context.go#L427)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Please add an explanatory comment.
</blockquote></details>

Thx for flagging. Removed. Unnecessary field given the work that Arul has done in prior commit.
___
*[`pkg/server/status.go` line 1581 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96319#-NNgnnpR6GyBmnwv29vb:-NNhxctB4foHCdtpCYqX:b-olvlm3) ([raw file](https://github.com/cockroachdb/cockroach/blob/18d10f686b115e9531e6e2a89fde8ed09ec06101/pkg/server/status.go#L1581)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

I *think* I understand this piece, but just to check my own understanding...

I know the tenant connector validates the tenant capability in its own authorization step. Is that tenant capability a subset of the `ViewClusterMetadataPermission` we're checking for here, meaning that an auth error of the broader permission doesn't necessarily mean we don't have the specific tenant capability? 
</blockquote></details>

Short answer: SQL Perms and Tenant capabilities are **completely disjoint and unrelated** and must be checked independently.

The request has to pass through the tenant connector for app tenants, but does not for system tenants. In both cases we need to do a SQL permission check given the request gRPC context that comes from the HTTP cookie. This validates that the SQL user that's currently logged in has the permission to view Node data.

Once that's done on the system tenant (see implementation of `(s *systemStatusServer) NodesUI(...` below right under `NodesTenant` impl.) we just serve the data and we're done.

On the app tenant, it's a bit different since we have to go through the connector to serve the data from the underlying kv node (aka system tenant) so the connector checks the tenant capability before retrieving the data directly from KV (without an additional SQL permission check!) via `NodesTenant`.
___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer_test.go` line 74 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96319#-NNgqSBUDJnLEi9jMqTu:-NNhx2Pu-t0KvdGvtY7u:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/18d10f686b115e9531e6e2a89fde8ed09ec06101/pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer_test.go#L74)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: add an empty line above
</blockquote></details>

Done.

**Comment by dhartunian** [comment]
@arulajmani can you take a quick look to see if I screwed up the intent of your tests?

**Review by arulajmani — COMMENTED** [review]
Looks good overall, my comments are pretty minor. 

> Reviewed 11 of 57 files at r3, 1 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96319#-:-NOLe0HYBRfALgP7Eglz:b-yn0a1c)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aadityasondhi, @abarganier, @dhartunian, @dt, and @knz)

___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/noop.go` line 41 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96319#-NOLKiXu5vDpQRdDIedw:-NOLKiXu5vDpQRdDIedx:bs25dc4) ([raw file](https://github.com/cockroachdb/cockroach/blob/51fc43b71910612a79f126dd581e3a7403cf0393/pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/noop.go#L41)):*
> ```Go
> }
> 
> func (n *NoopAuthorizer) HasNodeStatusCapability(
> ```

Here, and below, missing comment. 
___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiestestutils/testutils.go` line 97 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96319#-NOLcPsXAwCIiQpXyp24:-NOLcPsXAwCIiQpXyp25:b9bve9j) ([raw file](https://github.com/cockroachdb/cockroach/blob/a24b178cf9cceb12d5f4e8a6ddf6227b3166d5d9/pkg/multitenant/tenantcapabilities/tenantcapabilitiestestutils/testutils.go#L97)):*
> ```Go
> // tenantcapabilities.Update, allowing data-driven tests to assert on the
> // output.
> func PrintTenantCapabilityUpdate(update tenantcapabilities.Update) string {
> ```

How do you feel about keeping some form of this function around? Disambiguating between an update and a delete is nice when reading the test files. 

If this printing feels extra and cumbersome to work with as new capabilities are added, maybe we could get rid of just `PrintTenantCapability` instead? 
___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer_test.go` line 34 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96319#-NOL_tMe6seLfJDnQUYf:-NOL_tMe6seLfJDnQUYg:b-412m0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/51fc43b71910612a79f126dd581e3a7403cf0393/pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer_test.go#L34)):*
> ```Go
> // Example:
> //
> //	update-state
> ```

nit: should we update this as well with the changes we're making?
___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer_test.go` line 65 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96319#-NOL_Bo850_WDf2PQECJ:-NOL_Bo850_WDf2PQECK:b-xl639r) ([raw file](https://github.com/cockroachdb/cockroach/blob/51fc43b71910612a79f126dd581e3a7403cf0393/pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer_test.go#L65)):*
> ```Go
> 				update := tenantcapabilitiestestutils.ParseTenantCapabilityDelete(t, d)
> 				mockReader.updateState([]*tenantcapabilities.Update{update})
> 			case "has-capability":
> ```

nit: instead of this "cap" argument, could we instead have add `has-capability-for-batch`, `has-capability-for-node-status`... etc.? That way, the test file maps nicely to the interface. 

Separately, if we do this, we might not need the `cmds` argument? 
___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer_test.go` line 70 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96319#-NOL_XTL5vZLgqjfGF31:-NOL_XTL5vZLgqjfGF32:b-oru7r7) ([raw file](https://github.com/cockroachdb/cockroach/blob/51fc43b71910612a79f126dd581e3a7403cf0393/pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer_test.go#L70)):*
> ```Go
> 				d.ScanArgs(t, "cap", &cap)
> 				switch cap {
> 				case "can_admin_split":
> ```

(Superseded by the comment above), should this be "for_batch" instead? I don't think this matters now, but in the future we're going to introduce capabilities for other batch requests (eg. AdminRelocateRange etc.).

**Review by dhartunian — COMMENTED** [review]
@arulajmani Thx for the helpful comments. Tests are updated.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96319#-:-NOM5Lkw9n09vhqDUhy_:b-ds5d75)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aadityasondhi, @abarganier, @arulajmani, @dt, and @knz)

___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/noop.go` line 41 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96319#-NOLKiXu5vDpQRdDIedw:-NOLzwv0BoFbssxbFWNu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/51fc43b71910612a79f126dd581e3a7403cf0393/pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/noop.go#L41)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Here, and below, missing comment. 
</blockquote></details>

Done.
___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiestestutils/testutils.go` line 97 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96319#-NOLcPsXAwCIiQpXyp24:-NOM363tEmwgz8JQSOAn:b56zkch) ([raw file](https://github.com/cockroachdb/cockroach/blob/a24b178cf9cceb12d5f4e8a6ddf6227b3166d5d9/pkg/multitenant/tenantcapabilities/tenantcapabilitiestestutils/testutils.go#L97)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

How do you feel about keeping some form of this function around? Disambiguating between an update and a delete is nice when reading the test files. 

If this printing feels extra and cumbersome to work with as new capabilities are added, maybe we could get rid of just `PrintTenantCapability` instead? 
</blockquote></details>

Done. Implemented Stringer on `Update` and `Entry` structs that does the prefix thing.
___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer_test.go` line 34 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96319#-NOL_tMe6seLfJDnQUYf:-NOM3HQeAtMf1OPZoPEH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/51fc43b71910612a79f126dd581e3a7403cf0393/pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer_test.go#L34)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: should we update this as well with the changes we're making?
</blockquote></details>

Done.
___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer_test.go` line 65 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96319#-NOL_Bo850_WDf2PQECJ:-NOM5Gux41scBcDOH5Qw:b-ue90gz) ([raw file](https://github.com/cockroachdb/cockroach/blob/51fc43b71910612a79f126dd581e3a7403cf0393/pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer_test.go#L65)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: instead of this "cap" argument, could we instead have add `has-capability-for-batch`, `has-capability-for-node-status`... etc.? That way, the test file maps nicely to the interface. 

Separately, if we do this, we might not need the `cmds` argument? 
</blockquote></details>

agreed. done.
___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer_test.go` line 70 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96319#-NOL_XTL5vZLgqjfGF31:-NOM3a478Do5fKGZx08J:b-7gxi0k) ([raw file](https://github.com/cockroachdb/cockroach/blob/51fc43b71910612a79f126dd581e3a7403cf0393/pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer_test.go#L70)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

(Superseded by the comment above), should this be "for_batch" instead? I don't think this matters now, but in the future we're going to introduce capabilities for other batch requests (eg. AdminRelocateRange etc.).  
</blockquote></details>

Ah I see the authorizer doesn't expose the granular capability just an interface that operates on the Batch as a whole. Renamed the cmd.

**Review by arulajmani — APPROVED** [review]
Everything around the capabilities package and tests :lgtm: 

> Reviewed 1 of 24 files at r2, 1 of 57 files at r3, 1 of 14 files at r4, 7 of 10 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96319#-:-NOPnHdu1f-Osvxq1-th:bk8grk2)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @aadityasondhi, @abarganier, @dhartunian, @dt, and @knz)

___
*[`pkg/multitenant/tenantcapabilities/capabilities.go` line 87 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96319#-NOPm_ZYCWxcqP7EMBXj:-NOPm_ZYCWxcqP7EMBXk:b6mtrwp) ([raw file](https://github.com/cockroachdb/cockroach/blob/e360cdd92bf5936358e0983cd5cfe05f6461c593/pkg/multitenant/tenantcapabilities/capabilities.go#L87)):*
> ```Go
> func (u Update) String() string {
> 	if u.Deleted {
> 		return fmt.Sprintf("delete: %+v", u.Entry)
> ```

nit: for deleted updates, can we just print the tenant ID instead of the entire entry? I should've written a comment about this, but the capability isn't meaningful when an update corresponds to a delete. 
___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiestestutils/testutils.go` line 97 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/96319#-NOLcPsXAwCIiQpXyp24:-NOPn6rr0L4NHSwN57Ce:b-ndo84s) ([raw file](https://github.com/cockroachdb/cockroach/blob/a24b178cf9cceb12d5f4e8a6ddf6227b3166d5d9/pkg/multitenant/tenantcapabilities/tenantcapabilitiestestutils/testutils.go#L97)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Done. Implemented Stringer on `Update` and `Entry` structs that does the prefix thing.
</blockquote></details>

I like it! :100: 
___
*[`pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer_test.go` line 46 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/96319#-NOPm2h3CDpXekBcqhij:-NOPm2h3CDpXekBcqhik:b-74ops8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e360cdd92bf5936358e0983cd5cfe05f6461c593/pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer_test.go#L46)):*
> ```Go
> //
> //	has-capability-for-batch ten=10 cmds=(split)
> //	----
> ```

nit: should we add the `has-tsdb-query-capability` and `has-node-status-capability` here as well?

**Comment by dhartunian** [comment]
TFTRs. Last nits done.

bors r=arulajmani,knz,abarganier

**Pull request merged**
