### PR TITLE
[dnm] kv: expose (and use) byte batch response size limit 

### PR DESCRIPTION
**Pull request by tbg**
Not much to see here in terms of code, but this is a good venue to ask the question: any reason to *not* be doing this?

First commit is https://github.com/cockroachdb/cockroach/pull/44339

----

This is a (very rough) prototype for allowing consumers of the KV API to
restrict the size of result sets returned from spans. It does so
by simply plumbing through a byte hint from the kvfetcher to the
ultimate MVCC scan.

I mostly wanted to see that this all works, and it does. In the below,
the `kv` table contains ~10k 1mb rows:

This PR:
```
root@:26257/defaultdb> select sum(length(v)) from kv;
      sum
---------------
  10538188800
(1 row)

Time: 39.029189s
```

Before:
```
root@:26257/defaultdb ?> select sum(length(v)) from kv;
      sum
---------------
  10538188800
(1 row)

Time: 56.87552s
```

12:58 is this PR, ~13:00 is master.

image

Finished up, this work should already de-flake #33660.

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
> Not much to see here in terms of code, but this is a good venue to ask the question: any reason to not be doing this?

I can't think of anything. Seems like pure goodness in terms of both speed and memory usage.

**Review by nvb — COMMENTED** [review]
I'm glad this was as straightforward as we had though. The approach looks good and the results in your experiment are very promising. Have you gotten a chance to run this with `hotspotsplits/nodes=4`?

> Reviewed 7 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44341#-:-LzeRQGI6tEMrZ9p1gM_:b-p53f4a)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @knz, @nvanbenschoten, and @tbg)

___
*[pkg/kv/dist_sender.go, line 1226 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44341#-LzeOgnj1GIfhnv5oPJB:-LzeOgnj1GIfhnv5oPJC:bibuge6) ([raw file](https://github.com/cockroachdb/cockroach/blob/793d4a880340f647d273e2b3b002df08127dc8ff/pkg/kv/dist_sender.go#L1226)):*
> ```Go
> 			}
> 
> 			mightStopEarly := ba.MaxSpanRequestKeys > 0 || ba.MaxSpanResponseBytes > 0
> ```

nit: can this be pulled up above `canParallelize` and only computed once? I think it can also be set as the initial value of `canParallelize`.
___
*[pkg/sql/row/kv_batch_fetcher.go, line 229 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44341#-LzePETh6yELdlFyxrcJ:-LzePETi7NjUvnOc3Nko:b89vni8) ([raw file](https://github.com/cockroachdb/cockroach/blob/793d4a880340f647d273e2b3b002df08127dc8ff/pkg/sql/row/kv_batch_fetcher.go#L229)):*
> ```Go
> 	var ba roachpb.BatchRequest
> 	ba.Header.MaxSpanRequestKeys = f.getBatchSize()
> 	ba.Header.MaxSpanResponseBytes = 1 << 20 // 1MB
> ```

I'm assuming this isn't going to stay constant like this. If not, what were you envisioning as the policy to use for setting the byte limit on these requests?
1. pull out a constant like we have with `kvBatchSize`?
2. pull out a cluster setting?
3. dynamically grow the response size like we do in `getBatchSizeForIdx`? (I don't think this makes sense because there's no concept of soft row-size limits)
4. use the optimizer to make size estimates using histograms and pass that in here?
5. something else?
___
*[pkg/storage/batcheval/cmd_scan.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44341#-LzeQcfv2fr_Rds6YDa4:-LzeQcfv2fr_Rds6YDa5:b-1g58f1) ([raw file](https://github.com/cockroachdb/cockroach/blob/793d4a880340f647d273e2b3b002df08127dc8ff/pkg/storage/batcheval/cmd_scan.go#L47)):*
> ```Go
> 		var kvData [][]byte
> 		var numKvs int64
> 		opts := engine.MVCCScanOptions{
> ```

Are we not planning on supporting byte limits for the `roachpb.KEY_VALUES` response format? We probably don't want to get into the business of estimating the additional overhead of the `KeyValue` protos when we inflate the batch representation, but even just using the same mechanism to provide a limit would be useful.
___
*[pkg/storage/batcheval/cmd_scan.go, line 53 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44341#-LzeRAPC87XqKlSmnKHM:-LzeRAPC87XqKlSmnKHN:b-ck4uuh) ([raw file](https://github.com/cockroachdb/cockroach/blob/793d4a880340f647d273e2b3b002df08127dc8ff/pkg/storage/batcheval/cmd_scan.go#L53)):*
> ```Go
> 		}
> 		kvData, numKvs, resumeSpan, intents, err = engine.MVCCScanToBytes(
> 			ctx, reader, args.Key, args.EndKey, cArgs.MaxKeys, h.Timestamp,
> ```

This seems to indicate that the `max` arg belongs in the `MVCCScanOptions` struct as well.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44341)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @knz, @nvanbenschoten, and @tbg)

___
*[pkg/storage/batcheval/cmd_scan.go, line 47 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44341#-LzeQcfv2fr_Rds6YDa4:-LzgBc5b3-hbqTQjz8VU:bz8fjs8) ([raw file](https://github.com/cockroachdb/cockroach/blob/793d4a880340f647d273e2b3b002df08127dc8ff/pkg/storage/batcheval/cmd_scan.go#L47)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Are we not planning on supporting byte limits for the `roachpb.KEY_VALUES` response format? We probably don't want to get into the business of estimating the additional overhead of the `KeyValue` protos when we inflate the batch representation, but even just using the same mechanism to provide a limit would be useful.
</blockquote></details>

I think we should support `MaxSpanResponseBytes` with the `KEY_VALUES` format. And agree that we shouldn't try to estimate the additional overhead of the `KeyValue` protos. Simply passing through the `MaxSpanResponseBytes` setting to `MVCCScan` seems sufficient.

**Comment by ajwerner** [comment]
@tbg is this going to make it into this release? I'm working on paginating `ExportRequest`s right now. I think that'd I would like to utilize this logic or something like it. When it comes to `ExportRequest` there's two different parameters (1) How big should an individual file be (2) How much total data should be exported. 

Given this is coming soon I think I'm going to just do (1) above and leave (2) to adopt this. In the short term I'm going to leave a TODO in CDC backfills to adopt the byte limit code rather than implementing something of my own. Relates to #44482 and the CDC portion of https://github.com/cockroachdb/cockroach/issues/39717#issuecomment-565576033.

**Comment by knz** [comment]
It is planned for this release yes (whether it makes it will depend on how happy we are with the results)

**Comment by tbg** [comment]
@ajwerner this is going to be my must have for the coming milestone, so yes (and I'm planning to get it done early, too). Mind linking me to the pagination issue?

**Comment by tbg** [comment]
Nevermind, found the issue: https://github.com/cockroachdb/cockroach/issues/43356

**Comment by jordanlewis** [comment]
Very excited for this!

**Comment by tbg** [comment]
https://github.com/cockroachdb/cockroach/pull/45319

**Pull request closed without merging**
