### PR TITLE
execinfrapb: include complete component ID in stats proto

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### execinfrapb: minor improvement to TestMakeDeterministic

Test that MakeDeterminstic is a no-op if called a second time.

Release note: None

#### execinfrapb: include complete component ID in stats proto

This change adds a ComponentStats field that fully identifies a
component: it includes the flow ID, the component type, and an id
within those types.

This simplifies a lot the use of these stats: we no longer have to
parse back span tags to get the component information and keep track
of the association. More simplification is possible in the trace
analyzer.

In addition, this will make it much easier to add different types of
components (e.g. synchronizers).

One wrinkle is that in some cases, the vectorized engine emits two
(mostly disjoint) sets of stats for the same processor. We address
this by adding support for merging two ComponentStats (at analysis
time). This is still a bit hacky, but it's an improvement from the way
we currently do it (we plumb a flag to avoid duplicate stats, and
merge the string stats). The statistics now show up in the correct
order (this explains the diffs in the URLs).

Release note: None

### CODE REVIEW

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, 11 of 21 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57768#-:-MOBNrUu6ppShnz7AnbA:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/colexec/stats.go, line 134 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57768#-MOBMZuD7ldplM4riZiH:-MOBMZuD7ldplM4riZiI:b-j3lu9w) ([raw file](https://github.com/cockroachdb/cockroach/blob/c41a2ed503cd31d95bc3ee4365663811772c8bd3/pkg/sql/colexec/stats.go#L134)):*
> ```Go
> 	id int32,
> 	idTagKey string,
> 	omitNumTuples bool,
> ```

So was this basically not working? :thinking: I see the num tuples tag on a joinreader's EXPLAIN ANALYZE before this change...

**Review by yuzefovich — APPROVED** [review]
Nice! :lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57768#-:-MOCTgZxD4iEdS802GIH:be8rotp)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/stats.go, line 134 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57768#-MOBMZuD7ldplM4riZiH:-MOCTi2h0gKM3fbeHKUr:b-b5jqez) ([raw file](https://github.com/cockroachdb/cockroach/blob/c41a2ed503cd31d95bc3ee4365663811772c8bd3/pkg/sql/colexec/stats.go#L134)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

So was this basically not working? :thinking: I see the num tuples tag on a joinreader's EXPLAIN ANALYZE before this change...
</blockquote></details>

I think it was working - are you talking about the change in the logic tests? `tuples output` doesn't repeat there. The tag is supposed to be present once, but because of the columnarizer it could have been present twice.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57768)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/stats.go, line 134 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57768#-MOBMZuD7ldplM4riZiH:-MOCbYF88OXQDdZupxv8:bbusirm) ([raw file](https://github.com/cockroachdb/cockroach/blob/c41a2ed503cd31d95bc3ee4365663811772c8bd3/pkg/sql/colexec/stats.go#L134)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I think it was working - are you talking about the change in the logic tests? `tuples output` doesn't repeat there. The tag is supposed to be present once, but because of the columnarizer it could have been present twice.
</blockquote></details>

Correct, without this flag it would show up twice, because we were just appending all the string stats. Now the `Union` function is basically deduplicating it.

**Comment by RaduBerinde** [comment]
acceptance/bank/node-restart flake.

bors r+

**Pull request merged**
