### PR TITLE
sql: clean up and stabilize the output of SHOW CONSTRAINTS

### PR DESCRIPTION
**Pull request by knz**
Requested by @jseldess. cc @bdarnell since this is technically "backward-incompatible" (although the previous code was documented as "in dev" / "experimental").

This also uses the same `showTableDetails` code as many other `SHOW`
statements and thus simplifies the implementation.

Prior to this patch:

```
root@:26257/defaultdb> show constraints from kv;
+-------+------------+---------------------+-----------+---------+
| Table |    Name    |        Type         | Column(s) | Details |
+-------+------------+---------------------+-----------+---------+
| kv    | kv_v_k_key | UNIQUE              | v, k      | NULL    |
| kv    | primary    | PRIMARY KEY         | k         | NULL    |
| kv    | v          | CHECK (UNVALIDATED) | v         | v > 3   |
+-------+------------+---------------------+-----------+---------+
```

Several problems:

- capitals in name mandate quoting
- silly parentheses in the columns column may confuse clients
- hard to connect the information in the columns/details columns to
  the definition of the constraint in CREATE TABLE
- the validation state is not easily queryable.

After this patch:

```
root@:26257/defaultdb> show constraints from kv;
+-------+------------+-------------+-----------------------+-----------+
| table |    name    |    type     |        details        | validated |
+-------+------------+-------------+-----------------------+-----------+
| kv    | kv_v_k_key | UNIQUE      | UNIQUE (v ASC, k ASC) |   true    |
| kv    | primary    | PRIMARY KEY | PRIMARY KEY (k ASC)   |   true    |
| kv    | v          | CHECK       | CHECK (v > 3)         |   false   |
+-------+------------+-------------+-----------------------+-----------+
```

- simple column names
- details column uses same syntax as CREATE TABLE
- validated column is boolean

Release note (backward-incompatible change): The output columns for
the statement `SHOW CONSTRAINTS`, which was previously experimental,
was changed. The new interface will now be considered stable.

### CODE REVIEW

**Comment by bdarnell** [comment]
I'm fine with this from a backwards-compatibility perspective.

**Comment by knz** [comment]
friendly ping

**Comment by jseldess** [comment]
:lgtm:! Thank you for this, and very sorry for the delay.

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26478#-:-LEgYSCQ88c2xKJ1xbe3:bobktlx)*

**Comment by jordanlewis** [comment]
LGTM

**Comment by knz** [comment]
thank you :sparkling_heart: 

bors r+

**Pull request merged**
