### PR TITLE
release-21.1: backport 21.2's backup processor, streaming file writes

### PR DESCRIPTION
**Pull request by dt**
see commits.

Release justification: intended to be low risk as it is backported behind an opt-in experimental flag and is only additive, and is considered to potentially be high impact if it can help customers with larger clusters avoid OOMs related to large backup metadata.

### CODE REVIEW

**Review by miretskiy — APPROVED** [review]
Just had some minor nits -- mostly probably against the master;

I remember majority of that code; so I didn't go through it w/ "fine comb".  It looks okay.  Looks safe enough since its version gated.

Perhaps it makes sense to make that version gate flag metamorphic in tests?  Don't know how involved that maybe.
Regardless, I think the potential impact of this backport outweighs the dangers of such large backport; 

:lgtm: 

> Reviewed 16 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71830#-:-MmcQBAPDTDqBonGrq1X:b-ltums3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt and @stevendanna)

___
*[pkg/ccl/backupccl/backup_processor.go, line 489 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71830#-MmcOtrL8L7NM62Bv-nX:-MmcOtrL8L7NM62Bv-nY:b7gacoj) ([raw file](https://github.com/cockroachdb/cockroach/blob/2cfdfc10b95947005138f291f36a4286d513fef6/pkg/ccl/backupccl/backup_processor.go#L489)):*
> ```Go
> 
> 	totalSpans := len(spec.Spans) + len(spec.IntroducedSpans)
> 	todo := make(chan spanAndTime, totalSpans)
> ```

This is another O(large number) -- probably should avoid making channel w/ potentially large buffer.
___
*[pkg/ccl/storageccl/encryption.go, line 229 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71830#-MmcOgKFEkL0hVdX1I4V:-MmcOgKFEkL0hVdX1I4W:b-o3tzpy) ([raw file](https://github.com/cockroachdb/cockroach/blob/2cfdfc10b95947005138f291f36a4286d513fef6/pkg/ccl/storageccl/encryption.go#L229)):*
> ```Go
> 	// finished was the end of it, but sealing the (empty) remainder in a final
> 	// chunk maintains the invariant that a chunked file always ends in a sealed
> 	// chunk of less than chunk size, thus making tuncation, even along a chunk
> ```

s/tuncation/truncation/?

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71830)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dt, @miretskiy, and @stevendanna)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/71830#-MmrFEavDMXcDVo1tgA6:-MmrFEavDMXcDVo1tgA7:b-dt5y0z) (no related file):*
Overall looks good to me, although   I wonder if we could add a test without too much backport pain.  Perhaps we could re-use an existing roachperf test and set this option at startup?

---
___
*[pkg/ccl/backupccl/backup_processor.go, line 473 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71830#-MmrFbMGCApqmxrcRf0V:-MmrFbMGCApqmxrcRf0W:btdoih1) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c2ef89ea393999ca2dbd507c93439af87c7c801/pkg/ccl/backupccl/backup_processor.go#L473)):*
> ```Go
> 	targetFileSize = settings.RegisterByteSizeSetting(
> 		"bulkio.backup.file_size",
> 		"target file size",
> ```

Should we make it clear that these options only apply to the 21.2 mode?
___
*[pkg/ccl/backupccl/backup_processor.go, line 498 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71830#-MmrDQ2l8ve4v7gXAAln:-MmrDQ2l8ve4v7gXAAlo:b-p6jsds) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c2ef89ea393999ca2dbd507c93439af87c7c801/pkg/ccl/backupccl/backup_processor.go#L498)):*
> ```Go
> }
> 
> func runNewBackupProcessor(
> ```

[your call] I think it is sometimes nice to put the alternate implementation in completely different files so it is more immediately clear in stack traces/logs that we are in the alternate implementation.

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71830)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @miretskiy and @stevendanna)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/71830#-MmrFEavDMXcDVo1tgA6:-Mo-7XfZ7V8kXPttiWZd:b-pyy48w) (no related file):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Overall looks good to me, although   I wonder if we could add a test without too much backport pain.  Perhaps we could re-use an existing roachperf test and set this option at startup?
</blockquote></details>

TFTRs!

Added a unit test that backs up and restores with the setting enabled.

---
___
*[pkg/ccl/backupccl/backup_processor.go, line 489 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71830#-MmcOtrL8L7NM62Bv-nX:-Mmd2EnIE8PtEmRDam82:b-jrwc19) ([raw file](https://github.com/cockroachdb/cockroach/blob/2cfdfc10b95947005138f291f36a4286d513fef6/pkg/ccl/backupccl/backup_processor.go#L489)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

This is another O(large number) -- probably should avoid making channel w/ potentially large buffer.
</blockquote></details>

yeah, but this is how it is in 21.2/master so I don't want to go changing it here until we change and test it there.
___
*[pkg/ccl/backupccl/backup_processor.go, line 473 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71830#-MmrFbMGCApqmxrcRf0V:-Mo-7_r2-FWykqU8NlcX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c2ef89ea393999ca2dbd507c93439af87c7c801/pkg/ccl/backupccl/backup_processor.go#L473)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Should we make it clear that these options only apply to the 21.2 mode?
</blockquote></details>

Done.
___
*[pkg/ccl/backupccl/backup_processor.go, line 498 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71830#-MmrDQ2l8ve4v7gXAAln:-Mo-7a2x64B0AixGDbUt:bqli701) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c2ef89ea393999ca2dbd507c93439af87c7c801/pkg/ccl/backupccl/backup_processor.go#L498)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

[your call] I think it is sometimes nice to put the alternate implementation in completely different files so it is more immediately clear in stack traces/logs that we are in the alternate implementation. 
</blockquote></details>

Eh. I think I prefer the helpers, settings, etc all together. The line numbers are all > any old line so I'm not _too_ worried about telling what a stack is up to? 
___
*[pkg/ccl/storageccl/encryption.go, line 229 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71830#-MmcOgKFEkL0hVdX1I4V:-Mmd2sQO4IiTaySF-GzQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2cfdfc10b95947005138f291f36a4286d513fef6/pkg/ccl/storageccl/encryption.go#L229)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

s/tuncation/truncation/?
</blockquote></details>

Done.

**Review by stevendanna — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71830)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dt, @miretskiy, and @stevendanna)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/71830#-Mo3JEhV2eaubNyj1ggU:-Mo3JEhV2eaubNyj1ggV:b-lthnu0) (no related file):*
Thanks for adding the unit test!

---
___
*[pkg/ccl/backupccl/backup_processor.go, line 498 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/71830#-MmrDQ2l8ve4v7gXAAln:-Mo3FPuc0HOvi_MKPvTn:b-ra74ya) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c2ef89ea393999ca2dbd507c93439af87c7c801/pkg/ccl/backupccl/backup_processor.go#L498)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Eh. I think I prefer the helpers, settings, etc all together. The line numbers are all > any old line so I'm not _too_ worried about telling what a stack is up to? 
</blockquote></details>

Fine by me.

**Pull request merged**
