### PR TITLE
cli: Attempt to remove race causing `cockroach quit` flakes

### LINKED ISSUE #14184: teamcity: failed tests on master: acceptance/TestDockerMigration_7429
The following tests appear to have failed:

[#182457](https://teamcity.cockroachdb.com/viewLog.html?buildId=182457):

```
--- FAIL: acceptance/TestDockerMigration_7429 (6.190s)
reference_test.go:41: non-zero exit code: 1

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by a-robinson**
I can't say for sure because I haven't been able to reproduce the issue locally, but I believe this fixes #14184.

Suggestions welcome. I know you've dug much farther into this before than me, @tamird

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14587)

### CODE REVIEW

**Comment by tamird** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/cli/start.go, line 629 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14587#-KgpzuQ3cmpz9vTteIg5:-KgpzuQ3cmpz9vTteIg6:b-fmyn6c) ([raw file](https://github.com/cockroachdb/cockroach/blob/be43b8a492601d8c1c204e1daf0fb19faf48ebfe/pkg/cli/start.go#L629)):*
> ```Go
> 					return nil
> 				}
> 				if grpcutil.IsClosingConnection(err) {
> ```

This seems like an unlikely race - isn't it the case that the server's closing of the connection is noticed thanks to a RST being sent on this connection? If there are other bytes sitting on the connection ahead of this RST (i.e. the response, which is always sent before shutdown), I would expect this clause to never be hit.

@bdarnell thoughts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14587)*

**Comment by tamird** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/util/grpcutil/grpc_util.go, line 41 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14587#-Kgq-w0mUrJ3HkHh3nnI:-Kgq-w0mUrJ3HkHh3nnJ:bi21idj) ([raw file](https://github.com/cockroachdb/cockroach/blob/be43b8a492601d8c1c204e1daf0fb19faf48ebfe/pkg/util/grpcutil/grpc_util.go#L41)):*
> ```Go
> 		grpc.ErrorDesc(err) == grpc.ErrClientConnClosing.Error() ||
> 		strings.Contains(err.Error(), "is closing") ||
> 		strings.Contains(err.Error(), "use of closed network connection") ||
> ```

are you sure this change, without the rest, isn't enough to fix the flakes?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14587)*

**Comment by a-robinson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/util/grpcutil/grpc_util.go, line 41 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14587#-Kgq-w0mUrJ3HkHh3nnI:-KgqlRsGa5tWWnZxOzEg:b-fb65ya) ([raw file](https://github.com/cockroachdb/cockroach/blob/be43b8a492601d8c1c204e1daf0fb19faf48ebfe/pkg/util/grpcutil/grpc_util.go#L41)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

are you sure this change, without the rest, isn't enough to fix the flakes?
</blockquote></details>

I'm pretty sure, since about half of the flakes we have the logs for are with the "transport is closing" error that should be caught by the "is closing" string comparison on the above line.

On the plus side, you made me realize that I had copy/pasted the line that uses `grpc.ErrClientConnClosing` rather than using `transport`ErrConnClosing`, which is what I really wanted to check for.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14587)*

**Comment by bdarnell** [comment]
:lgtm: 

`cockroach quit` has fundamental flaws that make it difficult to implement in a bulletproof way. Wherever possible we should be terminating processes by communicating with their parent, instead of the process itself. 

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/cli/start.go, line 629 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14587#-KgpzuQ3cmpz9vTteIg5:-KgqtFsQ4scX2cn1eYqM:b-5dws27) ([raw file](https://github.com/cockroachdb/cockroach/blob/be43b8a492601d8c1c204e1daf0fb19faf48ebfe/pkg/cli/start.go#L629)):*
>  (i.e. the response, which is always sent before shutdown)

Is it guaranteed that the response makes it to the socket send buffer before shutdown? HTTP/2 implementations tend to have enough layers that I wouldn't be surprised if the response was occasionally delayed long enough that the connection is closed first. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14587#-:-Kgqu4rIjW8EjkR_qyrZ:b-5oeagb)*

**Comment by tamird** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/cli/start.go, line 629 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14587#-KgpzuQ3cmpz9vTteIg5:-KgsgMn05yj0j7uxLkyO:b1qlgyo) ([raw file](https://github.com/cockroachdb/cockroach/blob/be43b8a492601d8c1c204e1daf0fb19faf48ebfe/pkg/cli/start.go#L629)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

>  (i.e. the response, which is always sent before shutdown)

Is it guaranteed that the response makes it to the socket send buffer before shutdown? HTTP/2 implementations tend to have enough layers that I wouldn't be surprised if the response was occasionally delayed long enough that the connection is closed first. 
</blockquote></details>

I wonder if we should confirm that another connection attempt results in a connection refused, here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14587)*

**Comment by a-robinson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/cli/start.go, line 629 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14587#-KgpzuQ3cmpz9vTteIg5:-KgtHr4HUFQGEN834zeG:b-7mcgcn) ([raw file](https://github.com/cockroachdb/cockroach/blob/be43b8a492601d8c1c204e1daf0fb19faf48ebfe/pkg/cli/start.go#L629)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I wonder if we should confirm that another connection attempt results in a connection refused, here.
</blockquote></details>

That might make incorrectly printing success less likely, but in what cases would this connection be closing that wouldn't cause another connection attempt to get a "closed" error? Similarly, in what cases other than server shutdown would this client connection get a closing error?

I'm inclined to just submit this as is and see how it affects the flake rate. It could be barking up the wrong tree entirely, but shouldn't hurt anything.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14587)*

**Comment by tamird** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/cli/start.go, line 629 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14587#-KgpzuQ3cmpz9vTteIg5:-KgtJ7rfaqa8UyYTbGE5:b-ia23zl) ([raw file](https://github.com/cockroachdb/cockroach/blob/be43b8a492601d8c1c204e1daf0fb19faf48ebfe/pkg/cli/start.go#L629)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

That might make incorrectly printing success less likely, but in what cases would this connection be closing that wouldn't cause another connection attempt to get a "closed" error? Similarly, in what cases other than server shutdown would this client connection get a closing error?

I'm inclined to just submit this as is and see how it affects the flake rate. It could be barking up the wrong tree entirely, but shouldn't hurt anything.
</blockquote></details>

Well, if you want to submit this as is, just remove the `hasResp` logic entirely (and replace the IsClosedConnection call with your new IsClosingConnection). This feels quite messy to me as-is, with two near-identical checks in place.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14587)*

**Comment by a-robinson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/cli/start.go, line 629 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14587#-KgpzuQ3cmpz9vTteIg5:-KgtKxvSXRejmigNj3nb:b-76duqe) ([raw file](https://github.com/cockroachdb/cockroach/blob/be43b8a492601d8c1c204e1daf0fb19faf48ebfe/pkg/cli/start.go#L629)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Well, if you want to submit this as is, just remove the `hasResp` logic entirely (and replace the IsClosedConnection call with your new IsClosingConnection). This feels quite messy to me as-is, with two near-identical checks in place.
</blockquote></details>

It's messy, but at least it's tightly contained in a single place that not much depends on. Removing the `hasResp` logic seems worse from a correctness perspective, so I don't really want to do so just to make the code a little less ugly. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14587)*

**Comment by a-robinson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/cli/start.go, line 629 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14587#-KgpzuQ3cmpz9vTteIg5:-KgtsMthnJwcCCJFPjYC:be0kbsb) ([raw file](https://github.com/cockroachdb/cockroach/blob/be43b8a492601d8c1c204e1daf0fb19faf48ebfe/pkg/cli/start.go#L629)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

What do you mean? This is already essentially ignoring `hasResp` - the difference between IsClosedConnection and IsClosingConnection is
``
grpc.Code(err) == codes.Unavailable ||
grpc.ErrorDesc(err) == grpc.ErrClientConnClosing.Error() ||
``
neither of which is possible here.
</blockquote></details>

Also context cancellation, but sure. Removed the `hasResp` logic.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14587)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14587#-:-KgttSkDHbCcGVUmYZLP:bnfp4nl)*

**Pull request merged**
