### PR TITLE
cli: add `debug sstables`

### PR DESCRIPTION
**Pull request by petermattis**
Added periodic logging of the sstable info for a store.

See #7552.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7558)

### CODE REVIEW

**Comment by cuongdo** [comment]
1st pass review. I'm rusty on my C++, so I need a second pass.

---

Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[storage/store.go, line 2465 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLX-g5YUqGLEcDbq7pD:-KLX-g5YUqGLEcDbq7pE:2070986427) ([raw file](https://github.com/cockroachdb/cockroach/blob/3635b1dad667666d5fcfba5f86ae8db250bf858d/storage/store.go#L2465)):*
> ```Go
> 	// If we're using RocksDB log the sstable overview.
> 	if rocksdb, ok := s.engine.(*engine.RocksDB); ok {
> 		log.Infof("store %d sstables\n%s", s.StoreID(), rocksdb.GetSSTables())
> ```

This will be pretty noisy, as `ComputeMetrics` is called from `(*Store).Reserve()`. Maybe move to `V(1)`?

---

*[storage/engine/rocksdb.go, line 507 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLX1wmz11ZPop1KA4Ve:-KLX1wn-QiVw2R5hTRZ1:342066699) ([raw file](https://github.com/cockroachdb/cockroach/blob/3635b1dad667666d5fcfba5f86ae8db250bf858d/storage/engine/rocksdb.go#L507)):*
> ```Go
> 	// from it.
> 	const maxLen = 0x7fffffff
> 	tableSlice := (*[maxLen]C.DBSSTable)(unsafe.Pointer(tables))[:n:n]
> ```

Why is the second `:n` needed? How can the slice have greater than `n` elements when you reslice with the first `:n`?

---

*[storage/engine/rocksdb.go, line 515 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLX7CBRtRLak4sxhTFX:-KLX7CBSK9i0YtdozmXQ:-1086941835) ([raw file](https://github.com/cockroachdb/cockroach/blob/3635b1dad667666d5fcfba5f86ae8db250bf858d/storage/engine/rocksdb.go#L515)):*
> ```Go
> 		res[i].Start = cToGoKey(tableSlice[i].start_key)
> 		res[i].End = cToGoKey(tableSlice[i].end_key)
> 		C.free(unsafe.Pointer(tableSlice[i].start_key.key.data))
> ```

is it possible that `tableSlice[i].start_key` is `NULL`, because in `DBEngine::GetSSTables()`, `DecodeKey` returns false, so `tableSlice[i].start_key` is never assigned to?

---

*[storage/engine/rocksdb/db.cc, line 302 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLX6OHUjuNahWFTHvsO:-KLX6OHUjuNahWFTHvsP:-1646351286) ([raw file](https://github.com/cockroachdb/cockroach/blob/3635b1dad667666d5fcfba5f86ae8db250bf858d/storage/engine/rocksdb/db.cc#L302)):*
> ```cpp
> 
> DBKey ToDBKey(const rocksdb::Slice& s) {
>   DBKey key = {{nullptr, 0}, 0, 0};
> ```

Is it safer to use `memset(&key, 0, sizeof(key))`? I'm thinking of the case where someone adds a field to `DBKey`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-:-KLX7_czbcYv7nlxQZ_L:-310902303)*

**Comment by tschottdorf** [comment]
Reviewed 5 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[storage/store.go, line 2465 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLX-g5YUqGLEcDbq7pD:-KLXFojzrOvTM1SIu7Gb:-849652102) ([raw file](https://github.com/cockroachdb/cockroach/blob/3635b1dad667666d5fcfba5f86ae8db250bf858d/storage/store.go#L2465)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary>
> This will be pretty noisy, as `ComputeMetrics` is called from `(*Store).Reserve()`. Maybe move to `V(1)`?
</details>
Should this be plumbed up somewhere? Timeseries? StoreInfo?

---

*[storage/engine/rocksdb.go, line 96 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLXGAgC8dxA_qtdaZXJ:-KLXGAgC8dxA_qtdaZXK:1518583886) ([raw file](https://github.com/cockroachdb/cockroach/blob/3635b1dad667666d5fcfba5f86ae8db250bf858d/storage/engine/rocksdb.go#L96)):*
> ```Go
> 
> func (s SSTableInfos) String() string {
> 	const (
> ```

```go
const (
  MB = 1 << 10*(1+iota)
  MB
  GB
  TB
)
```

if you wanna get fancy (ok if not).

---

*[storage/engine/rocksdb.go, line 507 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLX1wmz11ZPop1KA4Ve:-KLXGshd2YQwL4O54N4P:-1138980242) ([raw file](https://github.com/cockroachdb/cockroach/blob/3635b1dad667666d5fcfba5f86ae8db250bf858d/storage/engine/rocksdb.go#L507)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary>
> Why is the second `:n` needed? How can the slice have greater than `n` elements when you reslice with the first `:n`?
</details>
The last `:n` sets the capacity of the slice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558)*

**Comment by tamird** [comment]
Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

*[storage/store.go, line 2463 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLWz1XrLq9sWyqoCX7w:-KLWz1XrLq9sWyqoCX7x:-470517520) ([raw file](https://github.com/cockroachdb/cockroach/blob/3635b1dad667666d5fcfba5f86ae8db250bf858d/storage/store.go#L2463)):*
> ```Go
> 	s.metrics.updateRocksDBStats(*stats)
> 
> 	// If we're using RocksDB log the sstable overview.
> ```

comma

---

*[storage/engine/rocksdb.go, line 507 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLX1wmz11ZPop1KA4Ve:-KLXFFRP1SS_Nviykfxj:1094682415) ([raw file](https://github.com/cockroachdb/cockroach/blob/3635b1dad667666d5fcfba5f86ae8db250bf858d/storage/engine/rocksdb.go#L507)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary>
> Why is the second `:n` needed? How can the slice have greater than `n` elements when you reslice with the first `:n`?
</details>
the second `:n` slices the capacity, so the returned slice will have a capacity of `n`, rather than the original slice's capacity.

---

*[storage/engine/rocksdb.go, line 515 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLX7CBRtRLak4sxhTFX:-KLXGvZSyIHWaJ8TPzdX:1164089119) ([raw file](https://github.com/cockroachdb/cockroach/blob/3635b1dad667666d5fcfba5f86ae8db250bf858d/storage/engine/rocksdb.go#L515)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary>
> is it possible that `tableSlice[i].start_key` is `NULL`, because in `DBEngine::GetSSTables()`, `DecodeKey` returns false, so `tableSlice[i].start_key` is never assigned to?
</details>
`tableSlice[i].start_key` can't be NULL, but `tableSlice[i].start_key.key.data` can, I think.

---

*[storage/engine/rocksdb.go, line 65 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLXGc_jKDQi4L9eXw3t:-KLXGc_jKDQi4L9eXw3u:-960242956) ([raw file](https://github.com/cockroachdb/cockroach/blob/15d50e7b888f41520d9a828157b9a72507f570e6/storage/engine/rocksdb.go#L65)):*
> ```Go
> }
> 
> // SSTableInfo contains metadata about a single RocksDB sstable.
> ```

should this comment mention the structure on the c++ that this mirrors?

---

*[storage/engine/rocksdb.go, line 95 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLXHaYAilKMIgDxKUVk:-KLXHaYAilKMIgDxKUVl:25141044) ([raw file](https://github.com/cockroachdb/cockroach/blob/15d50e7b888f41520d9a828157b9a72507f570e6/storage/engine/rocksdb.go#L95)):*
> ```Go
> }
> 
> func (s SSTableInfos) String() string {
> ```

can you write a simple test for this?

---

*[storage/engine/rocksdb.go, line 112 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLXHV4FrEtjmENeKQCt:-KLXHV4FrEtjmENeKQCu:-1881125347) ([raw file](https://github.com/cockroachdb/cockroach/blob/15d50e7b888f41520d9a828157b9a72507f570e6/storage/engine/rocksdb.go#L112)):*
> ```Go
> 		switch {
> 		case size < MB:
> 			return fmt.Sprintf("%dK", roundTo(size, KB))
> ```

can you still use humanize to do the printing after you've rounded?

---

*[storage/engine/rocksdb/db.cc, line 1341 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLXGEXqBIIYEuTmyOJG:-KLXGEXqBIIYEuTmyOJH:-1222970467) ([raw file](https://github.com/cockroachdb/cockroach/blob/15d50e7b888f41520d9a828157b9a72507f570e6/storage/engine/rocksdb/db.cc#L1341)):*
> ```cpp
>     if (DecodeKey(metadata[i].smallestkey, &tmp,
>                   &tables[i].start_key.wall_time, &tables[i].start_key.logical)) {
>       // This is a bit ugly because we want DBKey.key to be allocated
> ```

s/allocated/copied/?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558)*

**Comment by cuongdo** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions, all commit checks successful.

---

*[cli/debug.go, line 719 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLXFJS3d3z33WL0nOjS:-KLXFJS3d3z33WL0nOjT:1755566695) ([raw file](https://github.com/cockroachdb/cockroach/blob/3635b1dad667666d5fcfba5f86ae8db250bf858d/cli/debug.go#L719)):*
> ```Go
> 
> func (s sstableSlice) Less(i, j int) bool {
> 	switch {
> ```

replace with `return s[i].Level < s[j].Level || (s[i].Level == s[j].Level && s[i].Start.Less(s[j].Start)`?

---

*[storage/engine/rocksdb.go, line 515 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLX7CBRtRLak4sxhTFX:-KLXJQU7kZA1X98gEOfR:-2116344967) ([raw file](https://github.com/cockroachdb/cockroach/blob/3635b1dad667666d5fcfba5f86ae8db250bf858d/storage/engine/rocksdb.go#L515)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> `tableSlice[i].start_key` can't be NULL, but `tableSlice[i].start_key.key.data` can, I think.
</details>
yes, I meant `start_key.key.data`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558)*

**Comment by petermattis** [comment]
Review status: 3 of 6 files reviewed at latest revision, 11 unresolved discussions, some commit checks pending.

---

*[cli/debug.go, line 719 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLXFJS3d3z33WL0nOjS:-KLXXOoLd4WOIHgXoH7c:1908261082) ([raw file](https://github.com/cockroachdb/cockroach/blob/3635b1dad667666d5fcfba5f86ae8db250bf858d/cli/debug.go#L719)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary>
> replace with `return s[i].Level < s[j].Level || (s[i].Level == s[j].Level && s[i].Start.Less(s[j].Start)`?
</details>
That consumes fewer lines, but is it any clearer?

---

*[storage/store.go, line 2463 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLWz1XrLq9sWyqoCX7w:-KLXZAdGBqxMpTJJnUt1:591371877) ([raw file](https://github.com/cockroachdb/cockroach/blob/3635b1dad667666d5fcfba5f86ae8db250bf858d/storage/store.go#L2463)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> comma
</details>
Not sure where you want the comma.

---

*[storage/store.go, line 2465 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLX-g5YUqGLEcDbq7pD:-KLX8mjmWNUmYdAy2gqz:392371954) ([raw file](https://github.com/cockroachdb/cockroach/blob/3635b1dad667666d5fcfba5f86ae8db250bf858d/storage/store.go#L2465)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Should this be plumbed up somewhere? Timeseries? StoreInfo?
</details>
Seems like that is only done if the metrics haven't already been computed. Am I missing something? In practice this doesn't appear to be noisy.

@tschottdorf Cuong is going to do that in a separate PR.

---

*[storage/engine/rocksdb.go, line 96 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLXGAgC8dxA_qtdaZXJ:-KLXXYgPiOEnaj5sqb4G:-204078725) ([raw file](https://github.com/cockroachdb/cockroach/blob/3635b1dad667666d5fcfba5f86ae8db250bf858d/storage/engine/rocksdb.go#L96)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> ```go
> const (
>   MB = 1 << 10*(1+iota)
>   MB
>   GB
>   TB
> )
> ```
> 
> if you wanna get fancy (ok if not).
</details>
I'm going to leave as-is.

---

*[storage/engine/rocksdb.go, line 507 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLX1wmz11ZPop1KA4Ve:-KLX8v8TuM5MNdUdD-NM:959542342) ([raw file](https://github.com/cockroachdb/cockroach/blob/3635b1dad667666d5fcfba5f86ae8db250bf858d/storage/engine/rocksdb.go#L507)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary>
> Why is the second `:n` needed? How can the slice have greater than `n` elements when you reslice with the first `:n`?
</details>
The second `:n` limits the capacity of the slice. When you slice an array, the capacity of the slice would be the array length (`maxLen`). We're never appending to the slice so it doesn't really matter, but it is good practice.

---

*[storage/engine/rocksdb.go, line 515 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLX7CBRtRLak4sxhTFX:-KLX93H3L__ON7WzuiYR:1740142724) ([raw file](https://github.com/cockroachdb/cockroach/blob/3635b1dad667666d5fcfba5f86ae8db250bf858d/storage/engine/rocksdb.go#L515)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary>
> is it possible that `tableSlice[i].start_key` is `NULL`, because in `DBEngine::GetSSTables()`, `DecodeKey` returns false, so `tableSlice[i].start_key` is never assigned to?
</details>
Good point. I'll add a conditional.

---

*[storage/engine/rocksdb.go, line 65 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLXGc_jKDQi4L9eXw3t:-KLXZIL3P8tXlyEfdAbo:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/15d50e7b888f41520d9a828157b9a72507f570e6/storage/engine/rocksdb.go#L65)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> should this comment mention the structure on the c++ that this mirrors?
</details>
Done.

---

*[storage/engine/rocksdb.go, line 95 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLXHaYAilKMIgDxKUVk:-KLXa9t74YPyG7MntGFG:2109517944) ([raw file](https://github.com/cockroachdb/cockroach/blob/15d50e7b888f41520d9a828157b9a72507f570e6/storage/engine/rocksdb.go#L95)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can you write a simple test for this?
</details>
Yes. Done.

---

*[storage/engine/rocksdb.go, line 112 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLXHV4FrEtjmENeKQCt:-KLXXcAod1Ye8IgdNFea:-1276840612) ([raw file](https://github.com/cockroachdb/cockroach/blob/15d50e7b888f41520d9a828157b9a72507f570e6/storage/engine/rocksdb.go#L112)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can you still use humanize to do the printing after you've rounded?
</details>
Humanize prints at `2 MiB` and all of that suffix information becomes overwhelming. Compare:

```
0 [   7M]: 7M
4 [  11M]: 11M
5 [  52M]: 36M 15M 332K
6 [ 781M]: 129M 129M 129M 129M 129M 129M 6M
```

vs

```
0 [   7M]: 7 MiB
4 [  11M]: 11 MiB
5 [  52M]: 36 MiB 15 MiB 332 KiB
6 [ 781M]: 129 MiB 129 MiB 129 MiB 129 MiB 129 MiB 129 MiB 6 MiB
```

I'm happy to hear other suggestions for how to format this data concisely.

---

*[storage/engine/rocksdb/db.cc, line 302 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLX6OHUjuNahWFTHvsO:-KLXYvDjnidwLTWdojtI:1197698557) ([raw file](https://github.com/cockroachdb/cockroach/blob/3635b1dad667666d5fcfba5f86ae8db250bf858d/storage/engine/rocksdb/db.cc#L302)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary>
> Is it safer to use `memset(&key, 0, sizeof(key))`? I'm thinking of the case where someone adds a field to `DBKey`.
</details>
Yes, it is. `DBKey` has to be a C struct. 

---

*[storage/engine/rocksdb/db.cc, line 1341 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLXGEXqBIIYEuTmyOJG:-KLXZ74DyGNarVlW1KKK:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/15d50e7b888f41520d9a828157b9a72507f570e6/storage/engine/rocksdb/db.cc#L1341)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> s/allocated/copied/?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[storage/store.go, line 2463 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLWz1XrLq9sWyqoCX7w:-KLXdaMs5gKdPizVa90o:1996796716) ([raw file](https://github.com/cockroachdb/cockroach/blob/3635b1dad667666d5fcfba5f86ae8db250bf858d/storage/store.go#L2463)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Not sure where you want the comma.
</details>
Before the subordinate clause "...RocksDB, log the sstable overview."

---

*[storage/engine/rocksdb.go, line 112 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLXHV4FrEtjmENeKQCt:-KLXd1TVIz8vyVKHgdhK:1656550602) ([raw file](https://github.com/cockroachdb/cockroach/blob/15d50e7b888f41520d9a828157b9a72507f570e6/storage/engine/rocksdb.go#L112)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Humanize prints at `2 MiB` and all of that suffix information becomes overwhelming. Compare:
> 
> ```
> 0 [   7M]: 7M
> 4 [  11M]: 11M
> 5 [  52M]: 36M 15M 332K
> 6 [ 781M]: 129M 129M 129M 129M 129M 129M 6M
> ```
> 
> vs
> 
> ```
> 0 [   7M]: 7 MiB
> 4 [  11M]: 11 MiB
> 5 [  52M]: 36 MiB 15 MiB 332 KiB
> 6 [ 781M]: 129 MiB 129 MiB 129 MiB 129 MiB 129 MiB 129 MiB 6 MiB
> ```
> 
> I'm happy to hear other suggestions for how to format this data concisely.
</details>
Your story checks out, carry on.

---

*[storage/engine/rocksdb_test.go, line 344 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLXdUnAqoUqScR3Jm1C:-KLXdUnAqoUqScR3Jm1D:508273354) ([raw file](https://github.com/cockroachdb/cockroach/blob/be837a2aee66391d364f449028edfaf0adcf94ae/storage/engine/rocksdb_test.go#L344)):*
> ```Go
> 2 [ 110M]: 10M 8M 13M 31M 13M 30M 5M
> 3 [   2G]: 129M 129M 129M 9M 129M 129M 129M 93M 129M 129M 122M 129M 129M 129M 129M 129M 129M 24M 18M
> `
> ```

can this not end in a trailing newline? seems unexpected.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558)*

**Comment by tschottdorf** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558)*

**Comment by tschottdorf** [comment]
:lgtm: (without C++)

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-:-KLXfoVCUrQIN_HTLzKZ:645909783)*

**Comment by petermattis** [comment]
Review status: 4 of 6 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[storage/store.go, line 2463 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLWz1XrLq9sWyqoCX7w:-KLXe-t1L0e2lI1RU_ej:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/3635b1dad667666d5fcfba5f86ae8db250bf858d/storage/store.go#L2463)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Before the subordinate clause "...RocksDB, log the sstable overview."
</details>
Done.

---

*[storage/engine/rocksdb_test.go, line 344 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLXdUnAqoUqScR3Jm1C:-KLXeVvQnlVFavYtnKXe:-1548588855) ([raw file](https://github.com/cockroachdb/cockroach/blob/be837a2aee66391d364f449028edfaf0adcf94ae/storage/engine/rocksdb_test.go#L344)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can this not end in a trailing newline? seems unexpected.
</details>
Do you mean for `SSTableInfos.String` to not end in a newline? That seems strange.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[storage/store.go, line 2463 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLWz1XrLq9sWyqoCX7w:-KLXkh9F5fHo7e88w46K:166874) ([raw file](https://github.com/cockroachdb/cockroach/blob/3635b1dad667666d5fcfba5f86ae8db250bf858d/storage/store.go#L2463)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Done.
</details>
?

---

*[storage/engine/rocksdb_test.go, line 344 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLXdUnAqoUqScR3Jm1C:-KLXkip-gUrI82iIfClM:-1178757735) ([raw file](https://github.com/cockroachdb/cockroach/blob/be837a2aee66391d364f449028edfaf0adcf94ae/storage/engine/rocksdb_test.go#L344)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Do you mean for `SSTableInfos.String` to not end in a newline? That seems strange.
</details>
That's exactly what I mean - why is that strange? `log.Infof` throws in a newline, so you're currently double-newline-ing this at the caller.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[storage/store.go, line 2463 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLWz1XrLq9sWyqoCX7w:-KLXlPNNz_pi1j8i3f6z:-1516472177) ([raw file](https://github.com/cockroachdb/cockroach/blob/3635b1dad667666d5fcfba5f86ae8db250bf858d/storage/store.go#L2463)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> ?
</details>
Forgot to push the commit.

---

*[storage/engine/rocksdb_test.go, line 344 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLXdUnAqoUqScR3Jm1C:-KLXla71GVPl7AGReyhR:-536334476) ([raw file](https://github.com/cockroachdb/cockroach/blob/be837a2aee66391d364f449028edfaf0adcf94ae/storage/engine/rocksdb_test.go#L344)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> That's exactly what I mean - why is that strange? `log.Infof` throws in a newline, so you're currently double-newline-ing this at the caller.
</details>
FYI, `log.Infof` only adds a trailing newline if one isn't already present. See https://github.com/cockroachdb/cockroach/blob/master/util/log/clog.go#L582-L584.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[storage/engine/rocksdb_test.go, line 344 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLXdUnAqoUqScR3Jm1C:-KLXmlifkpsGtvoMlg8g:-507027125) ([raw file](https://github.com/cockroachdb/cockroach/blob/be837a2aee66391d364f449028edfaf0adcf94ae/storage/engine/rocksdb_test.go#L344)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> FYI, `log.Infof` only adds a trailing newline if one isn't already present. See https://github.com/cockroachdb/cockroach/blob/master/util/log/clog.go#L582-L584.
</details>
TIL. Still, why is it expected that String() ends in a newline?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[storage/engine/rocksdb_test.go, line 344 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLXdUnAqoUqScR3Jm1C:-KLXn0DIA5HGNP7q2tpe:-625895778) ([raw file](https://github.com/cockroachdb/cockroach/blob/be837a2aee66391d364f449028edfaf0adcf94ae/storage/engine/rocksdb_test.go#L344)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> TIL. Still, why is it expected that String() ends in a newline?
</details>
I'm on the fence. I can see your argument, but it seems strange to return a series of lines where the last line omits the newline. My preference is to leave as-is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[storage/engine/rocksdb_test.go, line 344 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLXdUnAqoUqScR3Jm1C:-KLXrlW-qx4O5CqkOG_s:-1899060368) ([raw file](https://github.com/cockroachdb/cockroach/blob/be837a2aee66391d364f449028edfaf0adcf94ae/storage/engine/rocksdb_test.go#L344)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I'm on the fence. I can see your argument, but it seems strange to return a series of lines where the last line omits the newline. My preference is to leave as-is.
</details>
What can I say? That seems to violate least-surprise.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[storage/engine/rocksdb_test.go, line 344 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558#-KLXdUnAqoUqScR3Jm1C:-KLXsDUkbnoBRbOXiUhP:-981386772) ([raw file](https://github.com/cockroachdb/cockroach/blob/be837a2aee66391d364f449028edfaf0adcf94ae/storage/engine/rocksdb_test.go#L344)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> What can I say? That seems to violate least-surprise.
</details>
Violates your least-surprise. I don't think it is obvious which choice causes the least surprise. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7558)*

**Pull request merged**
