### PR TITLE
kv: improve Raft scheduler behavior under CPU starvation

### LINKED ISSUE #56851: kvserver: default raft scheduler concurrency can cause cascading failures on beefy machines
The default number of worker goroutines in the Raft scheduler is `8*runtime.NumCPUs()`. We have observed that, at least on v20.1, this can cause pathological behavior that is most likely to occur when the CPU and range count are both "high" (32 CPUs and 55k ranges did it in one recent example).

The pathological behavior entails a full breakdown of the system. The UI and all ranges stop working. It becomes nearly impossible to extract debugging information from the system.

From a goroutine dump (via `kill -ABRT`), we see many of the worker goroutines with the following stack:

```
sync.(*Mutex).Lock(...)
    /usr/local/go/src/sync/mutex.go:81
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).enqueueN(0xc0011ea900, 0x8, 0xc041aea000, 0x844d, 0x9800, 0xc038b821c0)
```

(`enqueue1` similarly shows up). These are contending on a mutex, which is thought to be the root cause of the pathological behavior. This all looks like https://github.com/golang/go/issues/33747, which was fixed in go1.14. CRDB v20.1 and v20.2 are both built with go1.13, which makes them susceptible to this bug. v21.1 will be built with go1.15, which has the fix.

Following the contention in the scheduler, we see outgoing raft message streams that are backed up because the recipient’s raft scheduler is unable to keep up. These have been seen stuck for dozens of minutes ([select, 17 minutes] etc):

```
goroutine 2707 [select]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/internal/transport.(*writeQuota).get(0xc014642600, 0xc000000052, 0x4d, 0x5)
        /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/internal/transport/flowcontrol.go:59 +0xaa
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/internal/transport.(*http2Client).Write(0xc0120461c0, 0xc0042dab00, 0xc02dbaa480, 0x5, 0x60, 0xc01dd44a80, 0x4d, 0xbb, 0xc03e70ecf5, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/internal/transport/http2_client.go:840 +0x1ae
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*csAttempt).sendMsg(0xc013e8cd80, 0x416e3e0, 0xc014642700, 0xc03e70ecf0, 0x5, 0x5, 0xc01dd44a80, 0x4d, 0xbb, 0xc00bf3ccc0, ...)
        /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:828 +0x128
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*clientStream).SendMsg.func2(0xc013e8cd80, 0x4d, 0xbb)
        /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:693 +0xb3
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*clientStream).withRetry(0xc000139e60, 0xc018462c30, 0xc019b036f0, 0xc000263840, 0x0)
        /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:573 +0x360
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*clientStream).SendMsg(0xc000139e60, 0x416e3e0, 0xc014642700, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:699 +0x399
```

To resolve the gridlock, we added the environment variable `COCKROACH_SCHEDULER_CONCURRENCY=64` to all nodes in the cluster and restarted.
We verifed the problem was solved by letting the cluster come together, watch the metrics for Raft leaders to be elected on all ranges, gradually add load back to the cluster and keep monitoring.

We need to set better defaults for the Raft scheduler worker pool. Additionally, we should understand whether the extent of the degradation was expected given the misconfiguration or whether there are more improvements to resilience we need to make. This will likely entail reproducing the problem locally.

gz#8824

### PR DESCRIPTION
**Pull request by nvb**
Fixes #56851.

This PR contains 3 commits that should improve the health of a cluster under CPU starvation and with many Ranges. I ran a series of experiments (see https://github.com/cockroachdb/cockroach/pull/56860#issuecomment-729958996) which demonstrate that the combination of these commits improves the health of a cluster with many ranges dramatically, ensuring that liveness never falls over and that liveness heartbeat latency stays constant even as all other ranges become overloaded.

#### kv: cap COCKROACH_SCHEDULER_CONCURRENCY at 96

In investigations like #56851, we've seen the mutex in the Raft scheduler collapse due to too much concurrency. To address this, we needed to drop the scheduler's goroutine pool size to bound the amount of contention on the mutex to ensure that the scheduler was able to schedule any goroutines.

This commit caps this concurrency to 96, instead of letting it grow unbounded as a function of the number of cores on the system.

#### kv: batch enqueue Ranges in Raft scheduler for coalesced heartbeats

In #56851, we saw that all of the Raft transport's receiving goroutines were stuck in the Raft scheduler, attempting to enqueue Ranges in response to coalesced heartbeats. We saw this in stacktraces like:
```
goroutine 321096 [semacquire]:
sync.runtime_SemacquireMutex(0xc00007099c, 0xc005822a00, 0x1)
	/usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc000070998)
	/usr/local/go/src/sync/mutex.go:138 +0xfc
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:81
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).enqueue1(0xc000070980, 0x4, 0x19d8cb, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/scheduler.go:261 +0xb0
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).EnqueueRaftRequest(0xc000070980, 0x19d8cb)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/scheduler.go:299 +0x3e
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).HandleRaftUncoalescedRequest(0xc001136700, 0x4becc00, 0xc019f31b60, 0xc01288e5c0, 0x4ba44c0, 0xc014ff2b40, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/store_raft.go:175 +0x201
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).uncoalesceBeats(0xc001136700, 0x4becc00, 0xc019f31b60, 0xc035790a80, 0x37, 0x43, 0x100000001, 0x29b00000000, 0x0, 0x400000004, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/store_raft.go:110 +0x33b
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).HandleRaftRequest(0xc001136700, 0x4becc00, 0xc019f31b60, 0xc02be585f0, 0x4ba44c0, 0xc014ff2b40, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/store_raft.go:130 +0x1be
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*RaftTransport).handleRaftRequest(0xc000188780, 0x4becc00, 0xc019f31b60, 0xc02be585f0, 0x4ba44c0, 0xc014ff2b40, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/raft_transport.go:299 +0xab
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*RaftTransport).RaftMessageBatch.func1.1.1(0x4c3fac0, 0xc00d3ccdf0, 0xc000188780, 0x4becc00, 0xc019f31b60, 0x95fe98, 0x40c5720)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/raft_transport.go:370 +0x199
```

In that issue, we also saw that too much concurrency on the Raft scheduler's Mutex had caused the mutex to collapse (get stuck in the slow path, in the OS kernel) and hundreds of goroutines to pile up on it.

We suspect that part of the problem here was that each of the coalesced heartbeats was locking the Raft scheduler once per Range. So a coalesced heartbeat that contained 10k ranges would lock the scheduler 10k times on the receiver.

The commit attempts to alleviate this issue by batch enqueuing Ranges in the Raft scheduler in response to coalesced heartbeats. This has a slight fixed overhead (i.e. the need for a slice) but in response, reduces the load that coalesced heartbeats place on the Raft scheduler's mutex by a factor of 128 (`enqueueChunkSize`). This should reduce the impact that a large number of Ranges have on contention in the Raft scheduler.

#### kv: prioritize NodeLiveness Range in Raft scheduler

In #56851 and in many other investigations, we've seen cases where the NodeLiveness Range has a hard time performing writes when a system is under heavy load. We [already split RPC traffic into two classes](https://github.com/cockroachdb/cockroach/pull/39172), ensuring that NodeLiveness traffic does not get stuck behind traffic on user ranges. However, to this point, it was still possible for the NodeLiveness range to get stuck behind other Ranges in the Raft scheduler, leading to high scheduling latency for Raft operations.

This commit addresses this by prioritizing the NodeLiveness range above all others in the Raft scheduler. This prioritization mechanism is naive, but should be effective. It should also not run into any issues with fairness or starvation of other ranges, as such starvation is not possible as long as the scheduler concurrency (8*num_cpus) is above the number of high priority ranges (1).

@ajwerner I'm adding you here specifically because we've talked about the need for something like the last commit a few times.

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
I ran some experiments and found this to work very well – even better than I was expecting. Here are the steps I took, along with the results:
```
Run 3 node roachprod cluster with n1-standard-4 instances.
Disable quiescence using `COCKROACH_DISABLE_QUIESCENCE=true`.
Disable range merges using `set cluster setting kv.range_merge.queue_enabled=false;`.
Create 300k ranges using `workload init kv --splits=300000`.

Restart cluster without anything in this PR.
Run: `SELECT count(*) from kv.kv;`.
Monitor: `liveness.heartbeatlatency.p90` and `liveness.livenodes`.

Restart cluster with heartbeat batching but no liveness prioritization.
Run: `SELECT count(*) from kv.kv;`.
Monitor: `liveness.heartbeatlatency.p90` and `liveness.livenodes`.

Restart cluster with heartbeat batching and liveness prioritization.
Run: `SELECT count(*) from kv.kv;`.
Monitor: `liveness.heartbeatlatency.p90` and `liveness.livenodes`.
```

#### Trial 1: `master` with nothing from this PR.

During this trial, liveness heartbeat latency grew and the cluster lost liveness and fell over in about 6 minutes. This is what we've become accustomed to seeing.

The following graphs show:
```
pane 1: liveness.heartbeatlatency-p99
pane 2: replicas + replicas.quiescent
pane 3: liveness.livenodes
```
Screen Shot 2020-11-18 at 2 22 33 PM

#### Trial 2: only commit 2 from this PR – `batch enqueue Ranges in Raft scheduler for coalesced heartbeats`.

During this trial, liveness heartbeat latency grew much more gradually and the cluster never completely fell over. However, we did see transient liveness failures as the liveness latency neared and surpassed 4.5 seconds. This improvement indicates that the scheduler contention was hurting things on master, but that even with reduced contention, the FIFO queueing policy in the Raft scheduler eventually leads to such long scheduler latency for the node liveness range that the cluster can't sustain liveness.

Screen Shot 2020-11-18 at 3 24 50 PM

#### Trial 3: everything from this PR.

During this trial, we saw things dramatically improve again. Node liveness latency remained steady the entire time, at well below 1s in the tail, and all 300k ranges were eventually able to unquiesce after about an hour. The other ranges in the cluster were still not super happy because scheduler latency (a metric I'm going to write an issue about adding) for all non-liveness ranges was very high. However, we never lost liveness and the cluster never fell over, which was the major focus of this PR.

Screen Shot 2020-11-18 at 2 21 42 PM

We can also see that CPU was completely saturated throughout the entire run.

Screen Shot 2020-11-18 at 2 23 59 PM

**Comment by nvanbenschoten** [comment]
@tbg what do you think about backporting the second commit (`batch enqueue Ranges in Raft scheduler for coalesced heartbeats`)? The other commits seem a little risky for a backport because they change behavior, but that one seems like a clear win.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56860)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvserver/scheduler.go, line 67 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56860#-MMSD_GR36s2uG2GqY2s:-MMSD_GR36s2uG2GqY2t:b2rpdto) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a9c99118494986c6c83242a5ea68fd5955fee0b/pkg/kv/kvserver/scheduler.go#L67)):*
> ```Go
> // part, it implements a FIFO queueing policy with no prioritization of some
> // ranges over others. However, the queue can be configured with up to one
> // high-priority range, which will always be placed at the front when added.
> ```

Did you consider having a dedicated Raft scheduler goroutine for the node liveness range? This code has long since left my memory, so that might be a much larger lift. This simple priority mechanism seems relatively contained and your test results are quite compelling.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56860)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvserver/replica_init.go, line 350 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56860#-MMSEvqdDcD4WH2HTNzA:-MMSEvqdDcD4WH2HTNzB:b-xo3iuk) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a9c99118494986c6c83242a5ea68fd5955fee0b/pkg/kv/kvserver/replica_init.go#L350)):*
> ```Go
> 	// Ranges to ensure that liveness never sees high Raft scheduler latency.
> 	if bytes.HasPrefix(desc.StartKey, keys.NodeLivenessPrefix) {
> 		r.store.scheduler.SetPriorityID(desc.RangeID)
> ```

Once `SetPriorityID` is called, it is never cleared. Could this be done in the store initialization code?

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56860)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @petermattis, and @tbg)

___
*[pkg/kv/kvserver/replica_init.go, line 350 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56860#-MMSEvqdDcD4WH2HTNzA:-MMSfj4i-C-Fg6aOnjYn:b-1nlvm8) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a9c99118494986c6c83242a5ea68fd5955fee0b/pkg/kv/kvserver/replica_init.go#L350)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Once `SetPriorityID` is called, it is never cleared. Could this be done in the store initialization code?
</blockquote></details>

The challenge is that we don't have a constant ID for the node liveness Range, though I think in practice it always ends up being 2 today. I'm not sure how to cleanly determine this ID in store initialization code without doing a meta range lookup.
___
*[pkg/kv/kvserver/scheduler.go, line 67 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56860#-MMSD_GR36s2uG2GqY2s:-MMSgUP3-YvW3Yjusmf-:bjckmmu) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a9c99118494986c6c83242a5ea68fd5955fee0b/pkg/kv/kvserver/scheduler.go#L67)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Did you consider having a dedicated Raft scheduler goroutine for the node liveness range? This code has long since left my memory, so that might be a much larger lift. This simple priority mechanism seems relatively contained and your test results are quite compelling.
</blockquote></details>

I didn't consider it when writing this, but it is a valid alternative. It probably would be a larger lift though and has the downside of requiring a goroutine per node even for nodes that don't have a replica for the liveness range. Are there upsides that you think outweigh this?

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56860)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @nvanbenschoten, and @tbg)

___
*[pkg/kv/kvserver/replica_init.go, line 350 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56860#-MMSEvqdDcD4WH2HTNzA:-MMSsoYg5ViWl5WNJLli:b7m07mw) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a9c99118494986c6c83242a5ea68fd5955fee0b/pkg/kv/kvserver/replica_init.go#L350)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

The challenge is that we don't have a constant ID for the node liveness Range, though I think in practice it always ends up being 2 today. I'm not sure how to cleanly determine this ID in store initialization code without doing a meta range lookup.
</blockquote></details>

Ack. I had been mistakenly thinking that the node liveness range had a fixed ID.
___
*[pkg/kv/kvserver/scheduler.go, line 67 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56860#-MMSD_GR36s2uG2GqY2s:-MMStFnP6I_zrg-ZO613:b-bum004) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a9c99118494986c6c83242a5ea68fd5955fee0b/pkg/kv/kvserver/scheduler.go#L67)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I didn't consider it when writing this, but it is a valid alternative. It probably would be a larger lift though and has the downside of requiring a goroutine per node even for nodes that don't have a replica for the liveness range. Are there upsides that you think outweigh this? 
</blockquote></details>

The possible upside is that you'd be guaranteed to not queue processing of the node liveness range behind processing of any other range. With the priority approach here, if the node liveness range needs processing, it still has to wait for a worker to grab it. I suspect that will happen quickly, though.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56860#-:-MMT8pusAm1eQ_r2Cp4U:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten, @petermattis, and @tbg)

___
*[pkg/kv/kvserver/replica_init.go, line 350 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56860#-MMSEvqdDcD4WH2HTNzA:-MMT7eOhCFRnGYjP-U8v:by05b63) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a9c99118494986c6c83242a5ea68fd5955fee0b/pkg/kv/kvserver/replica_init.go#L350)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Ack. I had been mistakenly thinking that the node liveness range had a fixed ID.
</blockquote></details>

The node liveness range may move to a node after it starts up. This method will be called on every existing replica during store startup anyway. 
___
*[pkg/kv/kvserver/store_raft.go, line 116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56860#-MMT89KL9nq-DTa4bj7l:-MMT89KL9nq-DTa4bj7m:bsulqzn) ([raw file](https://github.com/cockroachdb/cockroach/blob/82eb4881de697a8a7aec1b38cfaa0c3e0ac33c74/pkg/kv/kvserver/store_raft.go#L116)):*
> ```
> 	if len(toEnqueue) > 0 {
> 		s.scheduler.EnqueueRaftRequests(toEnqueue...)
> 	}
> ```
nit: push the 0 len optimization down into `EnqueueRaftRequests`

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56860)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @petermattis, and @tbg)

___
*[pkg/kv/kvserver/scheduler.go, line 67 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/56860#-MMSD_GR36s2uG2GqY2s:-MMTUelYBzub6yxkw6bH:boxu7z2) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a9c99118494986c6c83242a5ea68fd5955fee0b/pkg/kv/kvserver/scheduler.go#L67)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The possible upside is that you'd be guaranteed to not queue processing of the node liveness range behind processing of any other range. With the priority approach here, if the node liveness range needs processing, it still has to wait for a worker to grab it. I suspect that will happen quickly, though. 
</blockquote></details>

That's a good point. The change here will ensure that the liveness range is quickly processed regardless of the queue size, but don't ensure that the range will be quickly processed if the workers are all very slow in processing other ranges. But I tend to agree that such cases should be rare, and in those cases, we must be hitting serious slowness below this level. This would imply that getting node liveness through the Raft scheduler is probably still not enough to ensure it makes progress.
___
*[pkg/kv/kvserver/store_raft.go, line 116 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56860#-MMT89KL9nq-DTa4bj7l:-MMTW--c0ybHdqiab8BO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/82eb4881de697a8a7aec1b38cfaa0c3e0ac33c74/pkg/kv/kvserver/store_raft.go#L116)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 	if len(toEnqueue) > 0 {
> 		s.scheduler.EnqueueRaftRequests(toEnqueue...)
> 	}
> ```
nit: push the 0 len optimization down into `EnqueueRaftRequests` 
</blockquote></details>

Done.

**Review by tbg — APPROVED** [review]
Please add a release note, probably even link to #56851 from it.

The experiments were run with the default raft scheduler concurrency, right (i.e. 32 workers per node)?

The quiescence test here:

https://github.com/cockroachdb/cockroach/blob/44de8d82fdbfe2be7e4c04d8720fcb8453fbdf27/pkg/cmd/roachtest/kv.go#L475

should work much better now, shouldn't it? We had neutered it quite a bit (dropped the range count lower and lower), but I think you may have just fixed the issues with it. See if you can set it up to roughly match your experiment and run it a few times, it will be very nice to have confidence that CRDB can support a vastly larger range count with your changes. (This doesn't need to hold up this PR, I imagine we want to run these tests a bunch after making them more aggressive, which takes time).

I'm on board with backporting the second commit. I would even entertain backporting the third after some bake time. The only way in which I could see this commit backfire (without a bug) is that the liveness range could starve out processing for other ranges, which seems improbable.

> Reviewed 1 of 1 files at r1, 4 of 4 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56860#-:-MMUaj2l1bliVW7029Dr:b-gu9271)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten and @petermattis)

___
*[pkg/kv/kvserver/replica_init.go, line 350 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/56860#-MMUd9i26CfgqSdoxpNT:-MMUd9i26CfgqSdoxpNU:bps0gty) ([raw file](https://github.com/cockroachdb/cockroach/blob/d48f59787131891a573cc50bf7b3a680442d493e/pkg/kv/kvserver/replica_init.go#L350)):*
> ```Go
> 	// Ranges to ensure that liveness never sees high Raft scheduler latency.
> 	if bytes.HasPrefix(desc.StartKey, keys.NodeLivenessPrefix) {
> 		r.store.scheduler.SetPriorityID(desc.RangeID)
> ```

Looks like this isn't tested, isn't that relatively easy to add? Start a server, look up the liveness range, get the range id, pull the priority ID from the scheduler (via a helper in helpers_test.go) and that's it?
Of course this works, as indicated by your experiments, but a more direct proof would be nice.
___
*[pkg/kv/kvserver/scheduler.go, line 123 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/56860#-MMUcdvM6hWbxMUfEgwf:-MMUcdvM6hWbxMUfEgwg:blh7zhu) ([raw file](https://github.com/cockroachdb/cockroach/blob/d48f59787131891a573cc50bf7b3a680442d493e/pkg/kv/kvserver/scheduler.go#L123)):*
> ```Go
> 	if q.priorityID != 0 && q.priorityID != id {
> 		panic(fmt.Sprintf(
> 			"priority range ID already set: old=%d, new=%d",
> ```

This is a bit odd, there's nothing about SetPriorityID "externally" that indicates that this is not allowed. Perhaps a comment on the method is enough.
___
*[pkg/kv/kvserver/store.go, line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56860#-MMUbYTlC-p24rXlsVeu:-MMUbYTlC-p24rXlsVev:b-qmigyj) ([raw file](https://github.com/cockroachdb/cockroach/blob/d94ed9e0bea2f15d525fa1a3de8c2b3edd30e4b3/pkg/kv/kvserver/store.go#L103)):*
> ```Go
> 
> var storeSchedulerConcurrency = envutil.EnvOrDefaultInt(
> 	"COCKROACH_SCHEDULER_CONCURRENCY", min(8*runtime.NumCPU(), 96))
> ```

A comment here wouldn't hurt - the `8*runtime.NumCPU()` was determined to show peak performance on a particular benchmarking setup using some variant of a KV workload (@petermattis might remember particulars) and the cap arises from observations of severe mutex contention at high scheduler concurrency.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56860)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten, @petermattis, and @tbg)

___
*[pkg/kv/kvserver/store.go, line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56860#-MMUbYTlC-p24rXlsVeu:-MMVc4ff670eSgeQY9VT:b93n1bm) ([raw file](https://github.com/cockroachdb/cockroach/blob/d94ed9e0bea2f15d525fa1a3de8c2b3edd30e4b3/pkg/kv/kvserver/store.go#L103)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

A comment here wouldn't hurt - the `8*runtime.NumCPU()` was determined to show peak performance on a particular benchmarking setup using some variant of a KV workload (@petermattis might remember particulars) and the cap arises from observations of severe mutex contention at high scheduler concurrency.
</blockquote></details>

My recollection is somewhat hazy. I recall doing some `kv` workload performance tests and `8*runtime.NumCPU()` appeared to be a reasonable value. I don't recall this testing being particularly rigorous and it is possibly something that could be fruitfully revisited.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56860)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten, @petermattis, and @tbg)

___
*[pkg/kv/kvserver/store.go, line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56860#-MMUbYTlC-p24rXlsVeu:-MMVcjh11XM99G1GpaXO:b-j6zkgt) ([raw file](https://github.com/cockroachdb/cockroach/blob/d94ed9e0bea2f15d525fa1a3de8c2b3edd30e4b3/pkg/kv/kvserver/store.go#L103)):*
Git history tells us that the testing wasn't particularly rigorous: 9a68241bc81cee4719d2a0e49d79d0fa7cc23934

> The COCKROACH_SCHEDULER_CONCURRENCY env var controls the number of
scheduler goroutines used for Raft processing. In testing, the previous
default of 2**NumCPU proved to be too low to achieve good parallelization
of batch commits. Even with proposer-evalued-KV landing, we want lots of
concurrent batch commits so they can be grouped and written to RocksDB
more efficiently. The new default of 8*NumCPU was determined
experimentally on 8 CPU machines.

Notice that this was done way back in April, 2017. The stone ages. 

Btw, nightly performance tests on higher CPU machines tends to flatline above 32 CPUs. I wonder if this will PR will have an effect.

**Review by nvb — COMMENTED** [review]
> Please add a release note, probably even link to #56851 from it.

Done.

> The experiments were run with the default raft scheduler concurrency, right (i.e. 32 workers per node)?

Right.

> The quiescence test here should work much better now, shouldn't it? 

Yes, it should be able to handle many more ranges without falling over. That doesn't mean that these ranges will be able to handle much traffic when none are quiesced, as Raft scheduler latency (see https://github.com/cockroachdb/cockroach/pull/56943) will still be quite large for all non-liveness ranges.

I'll experiment with updating that roachtest in a follow-up PR.

> I'm on board with backporting the second commit. I would even entertain backporting the third after some bake time.

That plan sounds good to me.

> The only way in which I could see this commit backfire (without a bug) is that the liveness range could starve out processing for other ranges, which seems improbable.

I'm not even sure that this is possible. I touched a bit on it in the commit message, but I think we're safe from any theoretical starvation as long as the scheduler concurrency (8*num_cpus) is above the number of high priority ranges (1), which it always will be.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56860#-:-MMYXnOH4QX-4ZM-TT5f:bvlpxoy)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @petermattis, and @tbg)

___
*[pkg/kv/kvserver/replica_init.go, line 350 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/56860#-MMUd9i26CfgqSdoxpNT:-MMYzMo4BUti3JmduQ1f:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d48f59787131891a573cc50bf7b3a680442d493e/pkg/kv/kvserver/replica_init.go#L350)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Looks like this isn't tested, isn't that relatively easy to add? Start a server, look up the liveness range, get the range id, pull the priority ID from the scheduler (via a helper in helpers_test.go) and that's it?
Of course this works, as indicated by your experiments, but a more direct proof would be nice.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/scheduler.go, line 123 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/56860#-MMUcdvM6hWbxMUfEgwf:-MMYuiUgCjuiV8DB-A--:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d48f59787131891a573cc50bf7b3a680442d493e/pkg/kv/kvserver/scheduler.go#L123)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

This is a bit odd, there's nothing about SetPriorityID "externally" that indicates that this is not allowed. Perhaps a comment on the method is enough.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/store.go, line 103 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56860#-MMUbYTlC-p24rXlsVeu:-MMYtkOn64ShPqIAtlRz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d94ed9e0bea2f15d525fa1a3de8c2b3edd30e4b3/pkg/kv/kvserver/store.go#L103)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Git history tells us that the testing wasn't particularly rigorous: 9a68241bc81cee4719d2a0e49d79d0fa7cc23934

> The COCKROACH_SCHEDULER_CONCURRENCY env var controls the number of
scheduler goroutines used for Raft processing. In testing, the previous
default of 2**NumCPU proved to be too low to achieve good parallelization
of batch commits. Even with proposer-evalued-KV landing, we want lots of
concurrent batch commits so they can be grouped and written to RocksDB
more efficiently. The new default of 8*NumCPU was determined
experimentally on 8 CPU machines.

Notice that this was done way back in April, 2017. The stone ages. 

Btw, nightly performance tests on higher CPU machines tends to flatline above 32 CPUs. I wonder if this will PR will have an effect.
</blockquote></details>

Done.

**Review by petermattis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56860)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @tbg)

**Comment by nvanbenschoten** [comment]
`acceptance/bank/node-restart` seems to be hitting `pq: query execution canceled due to statement timeout` across a number of PRs. I'm not sure when or why that became flaky, but it's not due to this so I'm going to merge.

bors r+

**Comment by jordanlewis** [comment]
Courtesy rebors r+

**Pull request merged**
