### PR TITLE
server, sql: add VIEWCLUSTERSETTING user privilege

### LINKED ISSUE #74692: A non-admin user is incorrectly able to see Cluster Settings from DB Console
**Describe the problem**

1. A non-admin user running `SHOW CLUSTER SETTINGS;` will be hit with an error that they need the `MODIFYCLUSTERSETTING` privilege to access cluster settings.
2. However, the same non-admin user can go into the DB Console, load the `/reports/settings` link, and see all cluster settings

**Expected behavior**
Access to Cluster Settings should be gated by the same `MODIFYCLUSTERSETTING` privilege. So that a non-admin user who: 
* Loads the `reports/settings` link from DB Console's Advanced Debug page will not see Cluster Settings. They should see the same error text that you need `MODIFYCLUSTERSETTING` to load that page

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

**Environment:**
 - Affects all versions of CRDB (e.g. 21.1, 21.2, 22.1)

### PR DESCRIPTION
**Pull request by koorosh**
Before, only users with `admin` role or `MODIFYCLUSTERSETTING`
permission could view cluster settings.
Now, new role is added to provide users view-only permission
to view cluster settings from SQL shell and in Db Console (in
Advanced debugging > Cluster settings).
This change doesn't change behavior for `MODIFYCLUSTERSETTING`
option, it also allows view and modify cluster settings.

Release note (sql change): new user privileges are added: `VIEWCLUSTERSETTING`
and `NOVIEWCLUSTERSETTING` that allows users to view cluster settings
only.

Resolves: https://github.com/cockroachdb/cockroach/issues/74692

### CODE REVIEW

**Review by Santamaura — COMMENTED** [review]
> Reviewed 8 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76012)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @koorosh, and @zachlite)

___
*[pkg/server/admin.go, line 1702 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76012#-MvJuCvM-3GBRBd7pG86:-MvJuCvN8OuKG_52_1MH:bbgvcuv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c07ac067d38aff455b273922bd5924e215876765/pkg/server/admin.go#L1702)):*
> ```Go
> 	}
> 
> 	if !hasModify && !hasView {
> ```

Perhaps here it would be better to check if there's no modify first so we can skip the no view check if they do have the role:



_Code snippet:_
```Go
if !hasModify {
	if !hasView {
		...
	}	
}
```
___
*[pkg/sql/crdb_internal.go, line 1467 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76012#-MvJwJkZ2az0-SA0him1:-MvJwJk_DYvt9HyUfmuD:bllie16) ([raw file](https://github.com/cockroachdb/cockroach/blob/c07ac067d38aff455b273922bd5924e215876765/pkg/sql/crdb_internal.go#L1467)):*
> ```Go
> 				return err
> 			}
> 			if !hasModify && !hasView {
> ```

same as above if you think it's worth the change.
___
*[pkg/sql/set_cluster_setting.go, line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76012#-MvJwb7h69ywtXQZ4SiY:-MvJwb7h69ywtXQZ4SiZ:b-7q6ads) ([raw file](https://github.com/cockroachdb/cockroach/blob/c07ac067d38aff455b273922bd5924e215876765/pkg/sql/set_cluster_setting.go#L79)):*
> ```Go
> 		return err
> 	}
> 	if action == "show" && !(hasModify || hasView) {
> ```

logic here is slightly tricky to wrap one's head around maybe refactor to do the action check first:



_Code snippet:_
```Go
if action == "show" {
	...
}
```

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76012)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @Santamaura, and @zachlite)

___
*[pkg/server/admin.go, line 1702 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76012#-MvJuCvM-3GBRBd7pG86:-MvJzG4sE0QlW2KwOEtA:b3qwvhy) ([raw file](https://github.com/cockroachdb/cockroach/blob/c07ac067d38aff455b273922bd5924e215876765/pkg/server/admin.go#L1702)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

Perhaps here it would be better to check if there's no modify first so we can skip the no view check if they do have the role:
</blockquote></details>

 `&&` logical operator does the same optimization. It doesn't check next condition if previous one returns `false`
___
*[pkg/sql/crdb_internal.go, line 1467 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76012#-MvJwJkZ2az0-SA0him1:-MvK0I8yEYMjDz7gG68M:b-hko186) ([raw file](https://github.com/cockroachdb/cockroach/blob/c07ac067d38aff455b273922bd5924e215876765/pkg/sql/crdb_internal.go#L1467)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

same as above if you think it's worth the change.
</blockquote></details>

That will work in the same way
___
*[pkg/sql/set_cluster_setting.go, line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76012#-MvJwb7h69ywtXQZ4SiY:-MvK0fDs5Bhb9rQQrR0u:by6zqwp) ([raw file](https://github.com/cockroachdb/cockroach/blob/c07ac067d38aff455b273922bd5924e215876765/pkg/sql/set_cluster_setting.go#L79)):*
<details><summary><i>Previously, Santamaura (Alex Santamaura) wrote…</i></summary><blockquote>

logic here is slightly tricky to wrap one's head around maybe refactor to do the action check first:
</blockquote></details>

I would try to avoid nested conditions as well, because it introduces additional "empty" conditional branches and might be confusing as well.
Probably it can be fixed with a good comment to describe this condition :)

**Review by Santamaura — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76012#-:-MvK3bIs890NI0DAf8OL:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian and @zachlite)

**Review by dhartunian — COMMENTED** [review]
> Reviewed 3 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76012)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @koorosh, @Santamaura, and @zachlite)

___
*[pkg/server/admin.go, line 1700 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76012#-MvQEi0fAm1eCrTr6nVe:-MvQEi0fAm1eCrTr6nVf:bbp746v) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc1f3a9ba916ad209f0bda71ee7a8ca2f2b11c9c/pkg/server/admin.go#L1700)):*
> ```Go
> 	if err != nil {
> 		return nil, err
> 	}
> ```

consider creating a helper like `requireViewOrModifyClusterSetting()`.  although now that I look at other usages it seems tough to re-use the helper since the other code areas have their own implementations. maybe best to keep the PR simple.
___
*[pkg/sql/logictest/testdata/logic_test/cluster_settings, line 100 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76012#-MvQWTbx9TTBD62OKMXC:-MvQWTbx9TTBD62OKMXD:b8h6b94) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc1f3a9ba916ad209f0bda71ee7a8ca2f2b11c9c/pkg/sql/logictest/testdata/logic_test/cluster_settings#L100)):*
> ```
> WHERE variable IN ('sql.defaults.default_int_size')
> ----
> sql.defaults.default_int_size  4
> ```

I'm a bit confused about this test and the one below...is the user root here? how is it able to see the clusters settings without `VIEWCLUSTERSETTING` being applied? is it there by default?

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76012)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @dhartunian, @Santamaura, and @zachlite)

___
*[pkg/server/admin.go, line 1700 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76012#-MvQEi0fAm1eCrTr6nVe:-MvSgT4qDmS__dRHLac-:blfh1kf) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc1f3a9ba916ad209f0bda71ee7a8ca2f2b11c9c/pkg/server/admin.go#L1700)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

consider creating a helper like `requireViewOrModifyClusterSetting()`.  although now that I look at other usages it seems tough to re-use the helper since the other code areas have their own implementations. maybe best to keep the PR simple.
</blockquote></details>

I'm inclined to keep it simple because it doesn't allow to verify presence of single role.
___
*[pkg/sql/logictest/testdata/logic_test/cluster_settings, line 100 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76012#-MvQWTbx9TTBD62OKMXC:-MvSNN8g68q48I4tI3DA:bwfj0fx) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc1f3a9ba916ad209f0bda71ee7a8ca2f2b11c9c/pkg/sql/logictest/testdata/logic_test/cluster_settings#L100)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

I'm a bit confused about this test and the one below...is the user root here? how is it able to see the clusters settings without `VIEWCLUSTERSETTING` being applied? is it there by default?
</blockquote></details>

User has `VIEWCLUSTERSETTING` privilege + `NOMODIFYCLUSTERSETTING` (removed privilege to modify settings). It is done to ensure that user has only `VIEWCLUSTERSETTING` role.



_Code quote:_
```
user root

statement ok
ALTER USER testuser NOMODIFYCLUSTERSETTING

statement ok
ALTER USER testuser VIEWCLUSTERSETTING

user testuser
```
___
*[pkg/sql/logictest/testdata/logic_test/cluster_settings, line 111 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76012#-MvSNt6QDB2WV_x75Hyr:-MvSNt6QDB2WV_x75Hys:b-7seg1w) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc1f3a9ba916ad209f0bda71ee7a8ca2f2b11c9c/pkg/sql/logictest/testdata/logic_test/cluster_settings#L111)):*
> ```
> 
> statement ok
> ALTER USER testuser NOVIEWCLUSTERSETTING
> ```

@dhartunian , Tests below validate that user without `VIEWCLUSTERSETTING` cannot query settings.

**Review by dhartunian — APPROVED** [review]
:lgtm:

> Reviewed 3 of 9 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76012#-:-MvsqLzJ74EwzT-V1TdX:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @koorosh, @Santamaura, and @zachlite)

___
*[pkg/sql/logictest/testdata/logic_test/cluster_settings, line 100 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/76012#-MvQWTbx9TTBD62OKMXC:-MvsqEowC3nUkZ9cFoju:bt9498n) ([raw file](https://github.com/cockroachdb/cockroach/blob/dc1f3a9ba916ad209f0bda71ee7a8ca2f2b11c9c/pkg/sql/logictest/testdata/logic_test/cluster_settings#L100)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

User has `VIEWCLUSTERSETTING` privilege + `NOMODIFYCLUSTERSETTING` (removed privilege to modify settings). It is done to ensure that user has only `VIEWCLUSTERSETTING` role.
</blockquote></details>

ah! I got confused. you need to be root user to set the other privileges. thanks for clarifying

**Pull request merged**
