### PR TITLE
server: return authoritative span statistics for db details endpoint

### LINKED ISSUE #96163: ccl/multiregionccl: TestMultiRegionDatabaseStats failed
ccl/multiregionccl.TestMultiRegionDatabaseStats [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/8501116?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/8501116?buildTab=artifacts#/) on master @ [69dd453d0e61e258f402c5751de310405743cd18](https://github.com/cockroachdb/cockroach/commits/69dd453d0e61e258f402c5751de310405743cd18):

```
=== RUN   TestMultiRegionDatabaseStats
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/e558fc8050776f4c54ea39ba371b49da/logTestMultiRegionDatabaseStats3303760444
    test_log_scope.go:79: use -show-logs to present logs inline
    region_test.go:66: condition failed to evaluate within 45s: expected node-ids=[4 5 6], got [1 2 3 5 6]
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/e558fc8050776f4c54ea39ba371b49da/logTestMultiRegionDatabaseStats3303760444
--- FAIL: TestMultiRegionDatabaseStats (97.91s)
```
<p>Parameters: <code>TAGS=bazel,gss,deadlock</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/multiregion
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestMultiRegionDatabaseStats.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-23975

### PR DESCRIPTION
**Pull request by THardy98**
Resolves: #96163

This change makes the admin API endpoint getting database statistics scan KV for span statistics instead of using the range descriptor cache. This provides authoritative output, helping deflake `TestMultiRegionDatabaseStats`.

Release note (sql change): admin API database details endpoint now returns authoritative range statistics.

### CODE REVIEW

**Review by j82w — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108037)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @THardy98)

___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108037#-Nar_UvW5MqZEaKDqKlS):*
Is there any concern about the additional overhead and perf impact of not using the cache? Would it not be better to just reset the stats for the test?

**Review by THardy98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108037)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w)

___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/108037#-Nar_UvW5MqZEaKDqKlS):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Is there any concern about the additional overhead and perf impact of not using the cache? Would it not be better to just reset the stats for the test?
</blockquote></details>

I think this makes more sense for the endpoint generally. Using the descriptor cache to measure size seems odd. There's no guarantee the cache holds all the database/table's ranges (i.e. we could be missing ranges or reading old ranges that no longer correspond to the database/table) and there's also no guarantee that the cache at some point will be up-to-date either.

I do agree that there is a concern about the additional overhead/perf impact but we also use the same logic already for the status server which we use for the console. I think the alignment between the two is also good.

**Comment by knz** [comment]
I agree with Thomas.

Additionally, if we find that performance is a concern, I would welcome a caching layer _for the computed stats_ in the o11y service, separate from the range cache.

**Review by maryliag — COMMENTED** [review]
Just wanna see that the tests are passing before approval, to make sure this change is working as expected, since some of the failed ones are related to retrieving database details

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108037#-:-NavhKGX0yCd4XdlHXIS:b-us0914)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w)

**Comment by THardy98** [comment]
IIUC, the test failures are due to tenant KV scans without using proper tenant precautions (i.e. `tenantConnect` iiuc).

Ideally, I'd like to reuse the span stats endpoint from status server here, but it doesn't return node IDs. Extending it means a proto change. The thought/discussion at the time was that returning node IDs in a potentially serverless env doesn't make a ton of sense, but I guess its something we want to support here?

**Comment by THardy98** [comment]
Tests were failing due to directly accessing meta2 keyspace which would fail in tenant scenarios.

Added a conditional to use the range iterator from `tenantConnect` if it was populated. Not sure if the `if sqlServer.tenantConnect != nil` pattern is one we want to adopt but thought it was a simple solution here.

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/108037#-:-NboMsJ4-L33qI2reIUD:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @j82w)

**Pull request merged**
