### PR TITLE
storage: add the ability to set/adjust zone configs for system ranges

### LINKED ISSUE #10692: storage: add the ability to set/adjust zone configs for system ranges
We need to be able to set the zone configs for all system ranges.  Unlike other ranges, if any range that contains metadata is unavailable, the entire cluster can become unavailable.

In the future, it might be nice to automatically do so, based on a combination of locality and the size of the cluster.

### PR DESCRIPTION
**Pull request by a6802739**
Fixes #10692.

cc @BramGruneir, @petermattis.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12335)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 6 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[pkg/cli/zone.go, line 179 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12335#-KYxmzWO56YfvwADC6r4:-KYxmzWO56YfvwADC6r5:b-7nyn7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/78443824420978d0a8b881339a8a47f59a52bf1d/pkg/cli/zone.go#L179)):*
> ```Go
> 	case ".system":
> 		return []sqlbase.ID{keys.NormalSystemID}, nil
> 	default:
> ```

No need for this `default` case.

---

*[pkg/cli/zone.go, line 193 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12335#-KYxnP4tuHqZS8VPerPN:-KYxnP4tuHqZS8VPerPO:b4za576) ([raw file](https://github.com/cockroachdb/cockroach/blob/78443824420978d0a8b881339a8a47f59a52bf1d/pkg/cli/zone.go#L193)):*
> ```Go
> 
> func parseZoneName(s string) ([]string, error) {
> 	if strings.ToLower(s) == ".default" || strings.ToLower(s) == ".meta" || strings.ToLower(s) == ".identifier" || strings.ToLower(s) == ".system" {
> ```

Would be better to call `strings.ToLower(s)` once:

```
switch t := strings.ToLower(s); s {
case ".default", ".meta", ".identifier", ".system":
  return []string{t}, nil
}
```

---

*[pkg/cli/zone.go, line 262 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12335#-KYxnBSMx1xqCKfmIPgP:-KYxnBSMx1xqCKfmIPgQ:b-6tfd0i) ([raw file](https://github.com/cockroachdb/cockroach/blob/78443824420978d0a8b881339a8a47f59a52bf1d/pkg/cli/zone.go#L262)):*
> ```Go
> 
> 	switch id {
> 	case 0:
> ```

Let's use the values from `keys/constants.go` here.

---

*[pkg/cli/zone.go, line 352 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12335#-KYxnFkMVGsx584IrNZd:-KYxnFkMVGsx584IrNZe:bjnkwej) ([raw file](https://github.com/cockroachdb/cockroach/blob/78443824420978d0a8b881339a8a47f59a52bf1d/pkg/cli/zone.go#L352)):*
> ```Go
> 	sort.Strings(output)
> 	// Ensure the default zone is always printed first.
> 	if _, ok := zones[0]; ok {
> ```

Ditto about using the values from `keys/constants.go` here.

---

*[pkg/cli/zone.go, line 410 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12335#-KYxnlQ0q5WG03B6ix5J:-KYxnlQ0q5WG03B6ix5K:b-au7n48) ([raw file](https://github.com/cockroachdb/cockroach/blob/78443824420978d0a8b881339a8a47f59a52bf1d/pkg/cli/zone.go#L410)):*
> ```Go
> 	}
> 	id := path[len(path)-1]
> 	if id == keys.RootNamespaceID || id == keys.MetaSystemID || id == keys.IdentifierSystemID || id == keys.NormalSystemID {
> ```

I think this would be more readable as a `switch`:

```
switch id {
case keys.RootNamespaceID, keys.MetaSystemID, keys.IdentifierSystemID, NormalSystemID:
  return ...
}
```

---

*[pkg/config/config.go, line 60 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12335#-KYxo-F39YR7kJUEWxDv:-KYxo-F4kSR9DyJAhDPn:biu5cwp) ([raw file](https://github.com/cockroachdb/cockroach/blob/78443824420978d0a8b881339a8a47f59a52bf1d/pkg/config/config.go#L60)):*
> ```Go
> 	// config has been specified.
> 	metaZoneConfig = ZoneConfig{
> 		NumReplicas:   15,
> ```

Let's leave the default `NumReplicas` at `3`. We haven't done significant testing with higher numbers of replicas and its better to make that change in a separate step.

---

*[pkg/config/config.go, line 68 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12335#-KYxoIkp1ALiniXTjwSQ:-KYxoIkp1ALiniXTjwSR:ba5fi9r) ([raw file](https://github.com/cockroachdb/cockroach/blob/78443824420978d0a8b881339a8a47f59a52bf1d/pkg/config/config.go#L68)):*
> ```Go
> 	}
> 
> 	// identifierZoneConfig is default zone configuration for system key which has
> ```

`s/is default/is the default/g`

---

*[pkg/config/config.go, line 80 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12335#-KYxoO8QZAh5CCrGTyCI:-KYxoO8QZAh5CCrGTyCJ:ba5fi9r) ([raw file](https://github.com/cockroachdb/cockroach/blob/78443824420978d0a8b881339a8a47f59a52bf1d/pkg/config/config.go#L80)):*
> ```Go
> 	}
> 
> 	// systemZoneConfig is default zone configuration for other system keys
> ```

`s/is default/is the default/g`

---

*[pkg/config/config.go, line 244 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12335#-KYxq3uz2Ams_inxHNlc:-KYxq3v-KupVf4ZRi1ag:bhei4qz) ([raw file](https://github.com/cockroachdb/cockroach/blob/78443824420978d0a8b881339a8a47f59a52bf1d/pkg/config/config.go#L244)):*
> ```Go
> 			return keys.NormalSystemID, true
> 		}
> 		return keys.IdentifierSystemID, true
> ```

Changing `ObjectIDForKey` like this will likely mess up `ComputeSplitKeys` which expects the lexicographic order of keys to match the order of IDs returned by `ObjectIDForKey`. I think this logic needs to go in `GetZoneConfigForKey` and `ComputeSplitKeys` needs additional logic add split points at the boundaries of the `meta`, `identifier` and `system` spans. 

---

*[pkg/keys/constants.go, line 274 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12335#-KYxovOi8NAGwHG5hDb5:-KYxovOi8NAGwHG5hDb6:bwqxs9j) ([raw file](https://github.com/cockroachdb/cockroach/blob/78443824420978d0a8b881339a8a47f59a52bf1d/pkg/keys/constants.go#L274)):*
> ```Go
> 	MetaSystemID       = 7
> 	IdentifierSystemID = 8
> 	NormalSystemID     = 9
> ```

Is there a reason these are the range `7-9` and not `6-8`? Actually, it might be better to use the range `15-17` as object IDs less than `10` are a bit more precious as they correspond to objects in the "system config" span.

---

*[pkg/sql/sqlbase/system.go, line 487 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12335#-KYxpX6WvvFx8_DIQaDg:-KYxpX6WvvFx8_DIQaDh:boz941m) ([raw file](https://github.com/cockroachdb/cockroach/blob/78443824420978d0a8b881339a8a47f59a52bf1d/pkg/sql/sqlbase/system.go#L487)):*
> ```Go
> 	target.otherKV = append(target.otherKV, createMetaZoneConfig()...)
> 	target.otherKV = append(target.otherKV, createIdentifierZoneConfig()...)
> 	target.otherKV = append(target.otherKV, createSystemZoneConfig()...)
> ```

The `meta`, `identifier` and `system` zone config entries will only be created when a cluster starts. @a-robinson This seems like a candidate for the new cluster upgrade infrastructure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12335)*

**Comment by a-robinson** [comment]
Review status: 0 of 6 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[pkg/sql/sqlbase/system.go, line 487 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12335#-KYxpX6WvvFx8_DIQaDg:-KYzJp2chrnCKWr5ODH1:bl4o22j) ([raw file](https://github.com/cockroachdb/cockroach/blob/78443824420978d0a8b881339a8a47f59a52bf1d/pkg/sql/sqlbase/system.go#L487)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The `meta`, `identifier` and `system` zone config entries will only be created when a cluster starts. @a-robinson This seems like a candidate for the new cluster upgrade infrastructure.
</blockquote></details>

Yeah, this seems like a very good candidate. Want me to do it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12335)*

**Comment by petermattis** [comment]
Review status: 0 of 6 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[pkg/sql/sqlbase/system.go, line 487 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12335#-KYxpX6WvvFx8_DIQaDg:-KZ-B1qe3_0IFE2BhuLL:bb77ufg) ([raw file](https://github.com/cockroachdb/cockroach/blob/78443824420978d0a8b881339a8a47f59a52bf1d/pkg/sql/sqlbase/system.go#L487)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Yeah, this seems like a very good candidate. Want me to do it?
</blockquote></details>

Yes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12335)*

**Comment by a6802739** [comment]
Review status: 0 of 6 files reviewed at latest revision, 11 unresolved discussions, some commit checks pending.

---

*[pkg/cli/zone.go, line 179 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12335#-KYxmzWO56YfvwADC6r4:-KZ-UkOw_C4urq3Y1N3Z:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/78443824420978d0a8b881339a8a47f59a52bf1d/pkg/cli/zone.go#L179)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

No need for this `default` case.
</blockquote></details>

Done.

---

*[pkg/cli/zone.go, line 193 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12335#-KYxnP4tuHqZS8VPerPN:-KZ-UmiBtxhZq27VgW0m:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/78443824420978d0a8b881339a8a47f59a52bf1d/pkg/cli/zone.go#L193)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Would be better to call `strings.ToLower(s)` once:

```
switch t := strings.ToLower(s); s {
case ".default", ".meta", ".identifier", ".system":
  return []string{t}, nil
}
```
</blockquote></details>

Done.

---

*[pkg/cli/zone.go, line 262 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12335#-KYxnBSMx1xqCKfmIPgP:-KZ-UtoGROCYxVWZ_5Gc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/78443824420978d0a8b881339a8a47f59a52bf1d/pkg/cli/zone.go#L262)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Let's use the values from `keys/constants.go` here.
</blockquote></details>

Done.

---

*[pkg/cli/zone.go, line 352 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12335#-KYxnFkMVGsx584IrNZd:-KZ-VBYiZ_vyB40KPAse:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/78443824420978d0a8b881339a8a47f59a52bf1d/pkg/cli/zone.go#L352)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Ditto about using the values from `keys/constants.go` here.
</blockquote></details>

Done.

---

*[pkg/cli/zone.go, line 410 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12335#-KYxnlQ0q5WG03B6ix5J:-KZ-VF82jtxPYGJBolB7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/78443824420978d0a8b881339a8a47f59a52bf1d/pkg/cli/zone.go#L410)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I think this would be more readable as a `switch`:

```
switch id {
case keys.RootNamespaceID, keys.MetaSystemID, keys.IdentifierSystemID, NormalSystemID:
  return ...
}
```
</blockquote></details>

Done.

---

*[pkg/config/config.go, line 60 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12335#-KYxo-F39YR7kJUEWxDv:-KZ-VGE96ncle140uD1q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/78443824420978d0a8b881339a8a47f59a52bf1d/pkg/config/config.go#L60)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Let's leave the default `NumReplicas` at `3`. We haven't done significant testing with higher numbers of replicas and its better to make that change in a separate step.
</blockquote></details>

Done.

---

*[pkg/config/config.go, line 68 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12335#-KYxoIkp1ALiniXTjwSQ:-KZ-VGwnwSQkdVZdF2h5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/78443824420978d0a8b881339a8a47f59a52bf1d/pkg/config/config.go#L68)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/is default/is the default/g`
</blockquote></details>

Done.

---

*[pkg/config/config.go, line 80 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12335#-KYxoO8QZAh5CCrGTyCI:-KZ-VHRLcx3hWXho8zEN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/78443824420978d0a8b881339a8a47f59a52bf1d/pkg/config/config.go#L80)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`s/is default/is the default/g`
</blockquote></details>

Done.

---

*[pkg/config/config.go, line 244 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12335#-KYxq3uz2Ams_inxHNlc:-KZ-VIByB7fCsOYh45jJ:b-8spw8t) ([raw file](https://github.com/cockroachdb/cockroach/blob/78443824420978d0a8b881339a8a47f59a52bf1d/pkg/config/config.go#L244)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Changing `ObjectIDForKey` like this will likely mess up `ComputeSplitKeys` which expects the lexicographic order of keys to match the order of IDs returned by `ObjectIDForKey`. I think this logic needs to go in `GetZoneConfigForKey` and `ComputeSplitKeys` needs additional logic add split points at the boundaries of the `meta`, `identifier` and `system` spans. 
</blockquote></details>

I have moved the logic from `ObjectIDForKey` to `GetZoneConfigForKey`. But I still can not understand `dditional logic add split points at the boundaries of the meta, identifier and system spans for ComputeSplitKeys ` 

---

*[pkg/keys/constants.go, line 274 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12335#-KYxovOi8NAGwHG5hDb5:-KZ-VeBn1VXhs8gP99K-:bof0qrv) ([raw file](https://github.com/cockroachdb/cockroach/blob/78443824420978d0a8b881339a8a47f59a52bf1d/pkg/keys/constants.go#L274)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is there a reason these are the range `7-9` and not `6-8`? Actually, it might be better to use the range `15-17` as object IDs less than `10` are a bit more precious as they correspond to objects in the "system config" span.
</blockquote></details>

No special reason. I just found it hasn't been used.

---

*[pkg/sql/sqlbase/system.go, line 487 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12335#-KYxpX6WvvFx8_DIQaDg:-KZ-Vp6LtlBNS9aYmGOf:b41nbeq) ([raw file](https://github.com/cockroachdb/cockroach/blob/78443824420978d0a8b881339a8a47f59a52bf1d/pkg/sql/sqlbase/system.go#L487)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Yes.
</blockquote></details>

sorry, I cann't understand what do you mean here? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12335)*

**Comment by BramGruneir** [comment]
*[pkg/sql/sqlbase/system.go, line 487 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12335#-KYxpX6WvvFx8_DIQaDg:-KZ03kCSWv7aLENxYKli:b-7ri0yr) ([raw file](https://github.com/cockroachdb/cockroach/blob/78443824420978d0a8b881339a8a47f59a52bf1d/pkg/sql/sqlbase/system.go#L487)):*
<details><summary><i>Previously, a6802739 (songhao) wrote…</i></summary><blockquote>

sorry, I cann't understand what do you mean here? 
</blockquote></details>

Already running clusters that update their binaries to include this change will require a migration.  Alex is working on a system to perform these migrations.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12335)*

**Comment by a6802739** [comment]
Review status: 0 of 6 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[pkg/sql/sqlbase/system.go, line 487 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12335#-KYxpX6WvvFx8_DIQaDg:-KZ2DkaF-_n74nm4kWYB:b-r8bqif) ([raw file](https://github.com/cockroachdb/cockroach/blob/78443824420978d0a8b881339a8a47f59a52bf1d/pkg/sql/sqlbase/system.go#L487)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Already running clusters that update their binaries to include this change will require a migration.  Alex is working on a system to perform these migrations.
</blockquote></details>

got it.  Thanks a lot.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12335)*

**Comment by petermattis** [comment]
Review status: 0 of 6 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/cli/zone.go, line 356 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12335#-KZ2SILbjghrZxrANkh-:-KZ2SILbjghrZxrANkh0:bpnb31y) ([raw file](https://github.com/cockroachdb/cockroach/blob/05f28c637a076262284640bebd3feccbe42af296/pkg/cli/zone.go#L356)):*
> ```Go
> 		keys.IdentifierSystemID: ".identifier",
> 		keys.NormalSystemID:     ".system",
> 	}
> ```

This mapping from ID to name could be shared with `runGetZone` via a small helper function.

---

*[pkg/config/config.go, line 244 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12335#-KYxq3uz2Ams_inxHNlc:-KZ2TEMO49VCTquUufoa:biu08bw) ([raw file](https://github.com/cockroachdb/cockroach/blob/78443824420978d0a8b881339a8a47f59a52bf1d/pkg/config/config.go#L244)):*
<details><summary><i>Previously, a6802739 (songhao) wrote…</i></summary><blockquote>

I have moved the logic from `ObjectIDForKey` to `GetZoneConfigForKey`. But I still can not understand `dditional logic add split points at the boundaries of the meta, identifier and system spans for ComputeSplitKeys ` 
</blockquote></details>

We need to force splits at the boundaries of the different key spans used by the zone configs you're introducing. Without doing that, all of the data that is before `keys.SystemConfigTableDataMax` will reside in one range until that range is split because it is too big. The mechanism for forcing splits is `ComputeSplitKeys` which forces splits at table boundaries. In particular, you'll need to enhance the code at the very beginning:

```
	tableStart := roachpb.RKey(keys.SystemConfigTableDataMax)
	if !tableStart.Less(endKey) {
		// This range is before the user tables span: no required splits.
		return nil
	}
```

The above conditional will fire for all of the system keys and you'll need to add logic to split at the correct point. I think there can be a hardcoded list of split points and you need to return the correct subset that lie between `startKey` and `endKey`.

Note that this code is very unit testable, so be sure to add tests covering all of the new logic. 

---

*[pkg/config/config.go, line 72 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12335#-KZ2ScwCHkUYE5jaQkMs:-KZ2ScwCHkUYE5jaQkMt:b-9zfxlg) ([raw file](https://github.com/cockroachdb/cockroach/blob/05f28c637a076262284640bebd3feccbe42af296/pkg/config/config.go#L72)):*
> ```Go
> 	// 'RangeIDGenerator', 'StoreIDGenerator' etc.
> 	identifierZoneConfig = ZoneConfig{
> 		NumReplicas:   5,
> ```

Set the default number of replicas to `3` here as well.

---

*[pkg/config/config.go, line 408 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/12335#-KZ2SpsT4r87JV7qkKlz:-KZ2SpsT4r87JV7qkKm-:b-yatpjm) ([raw file](https://github.com/cockroachdb/cockroach/blob/05f28c637a076262284640bebd3feccbe42af296/pkg/config/config.go#L408)):*
> ```Go
> 			objectID = keys.NormalSystemID
> 		}
> 		objectID = keys.IdentifierSystemID
> ```

I think if you added a test for this new functionality you'd see a bug here: `keys.NormalSystemID` can never be returned.

---

*[pkg/keys/constants.go, line 274 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/12335#-KYxovOi8NAGwHG5hDb5:-KZ2Uf3Z3tJUQbIpUZf2:b-jielv7) ([raw file](https://github.com/cockroachdb/cockroach/blob/78443824420978d0a8b881339a8a47f59a52bf1d/pkg/keys/constants.go#L274)):*
<details><summary><i>Previously, a6802739 (songhao) wrote…</i></summary><blockquote>

No special reason. I just found it hasn't been used.
</blockquote></details>

Ok. That range of values is better. Can you move it down below `UITableID` so that the order of definition matches the numbering?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12335)*

**Comment by a-robinson** [comment]
Closing in favor of #14740.

**Pull request closed without merging**
