### PR TITLE
roachtest: add roachtest for snapshot ingest with excises

### PR DESCRIPTION
**Pull request by aadityasondhi**
This patch adds a roachtest for running snapshots with excises enabled. In this workload, when splits and excises are disabled, we see an inverted LSM and degraded p99 latencies.

The test asserts that the LSM stays healthy while doing the snapshot ingest, and p99 latencies don't spike over a threshold.

Informs #80607.

Release note: None

### CODE REVIEW

**Comment by aadityasondhi** [comment]
Charts for this roachtest can be found in this [internal thread](https://cockroachlabs.slack.com/archives/C01SRKWGHG8/p1716391876312919).

**Comment by aadityasondhi** [comment]
I will hold the backport until this test bakes in master for a while.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124591#-:-Nyf2QGd7_bJiEynymLO:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi, @DarrylWong, and @herkolategan)

___
*[`pkg/cmd/roachtest/tests/admission_control_snapshot_overload_excise.go` line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124591#-Nyf0lkk1f9PRFy7HPa_:-Nyf0lkk1f9PRFy7HPaa:b-hnx0y8) ([raw file](https://github.com/cockroachdb/cockroach/blob/765053a42c51052078fd528c008770f11e19330e/pkg/cmd/roachtest/tests/admission_control_snapshot_overload_excise.go#L57)):*
> ```Go
> 				t.Fatalf("expected at least 4 nodes, found %d", c.Spec().NodeCount)
> 			}
> ```

Worth adding a comment like:
```
// COCKROACH_CONCURRENT_COMPACTIONS is set to 1 since we want to ensure that snapshot ingests don't result in LSM inversion even with a very low compaction rate. With Pebble's IngestAndExcise all the ingested sstables should ingest into L6.
// COCKROACH_CONCURRENT_SNAPSHOT* is increased so that the rate of snapshot application is high.
// COCKROACH_RAFT_LOG_TRUNCATION_THRESHOLD is reduced so that there is certainty that the restarted node will be caught up via snapshots, and not via raft log replay.
```
___
*[`pkg/cmd/roachtest/tests/admission_control_snapshot_overload_excise.go` line 186 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124591#-Nyf2HU-1wK4-KloiOn5:-Nyf2HU-1wK4-KloiOn6:bmfyjyf) ([raw file](https://github.com/cockroachdb/cockroach/blob/765053a42c51052078fd528c008770f11e19330e/pkg/cmd/roachtest/tests/admission_control_snapshot_overload_excise.go#L186)):*
> ```Go
> 				// Assert on l0 sublevel count and p99 latencies.
> 				latencyMetric := divQuery("histogram_quantile(0.99, sum by(le) (rate(sql_service_latency_bucket[2m])))", 1<<20 /* 1ms */)
> 				const latencyThreshold = 100
> ```

So 100ms because of the `divQuery`. Worth adding a code comment.

**Review by aadityasondhi — COMMENTED** [review]
TFTR!

bors r=sumeerbhola

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124591#-:-Nyf6D6104WkefueQPI0:b-6zs9ju)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DarrylWong, @herkolategan, and @sumeerbhola)

___
*[`pkg/cmd/roachtest/tests/admission_control_snapshot_overload_excise.go` line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124591#-Nyf0lkk1f9PRFy7HPa_:-Nyf6C821gCOxn_65HpE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/765053a42c51052078fd528c008770f11e19330e/pkg/cmd/roachtest/tests/admission_control_snapshot_overload_excise.go#L57)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Worth adding a comment like:
```
// COCKROACH_CONCURRENT_COMPACTIONS is set to 1 since we want to ensure that snapshot ingests don't result in LSM inversion even with a very low compaction rate. With Pebble's IngestAndExcise all the ingested sstables should ingest into L6.
// COCKROACH_CONCURRENT_SNAPSHOT* is increased so that the rate of snapshot application is high.
// COCKROACH_RAFT_LOG_TRUNCATION_THRESHOLD is reduced so that there is certainty that the restarted node will be caught up via snapshots, and not via raft log replay.
```
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/tests/admission_control_snapshot_overload_excise.go` line 186 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124591#-Nyf2HU-1wK4-KloiOn5:-Nyf6BOT1yq9UBG0A-ds:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/765053a42c51052078fd528c008770f11e19330e/pkg/cmd/roachtest/tests/admission_control_snapshot_overload_excise.go#L186)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

So 100ms because of the `divQuery`. Worth adding a code comment.
</blockquote></details>

Done.

**Comment by aadityasondhi** [comment]
lint failure 🫤 will wait on branch passing before merging

**Pull request merged**
