### PR TITLE
sql: `tree.ParseJSON` should not ignore trailing data

### PR DESCRIPTION
**Pull request by miretskiy**
`tree.ParseJSON` uses `Decoder.More()` method to determine if the input contains trailing data.  The implementation made incorrect assumptions as to the reason why `Decoder.More()` allows input to contain `]` or `}` characters, even when JSON object has been consumed.

This PR fixes and comments those faulty assumptions, and fixes multiple existing tests that seemed to rely on those faulty assumptions.

In particular, prior to this PR, the following input would be allowed (i.e. extra end of object character `}`):
```
demo@127.0.0.1:26257/movr> select '{"longKey1":"longValue1"}}'::jsonb;
            jsonb
------------------------------
  {"longKey1": "longValue1"}
(1 row)
```

But so would the following be allowed:
```
demo@127.0.0.1:26257/movr> select '{"longKey1":"longValue1"}} should this data be ignored?'::jsonb;
            jsonb
------------------------------
  {"longKey1": "longValue1"}
(1 row)
```

So, the  issue is: if above conversion was executed to insert JSONB into the database, we would silently
truncate (corrupt) JSON input, and instead of returning an error, we would return success.

This behavior is wrong, and this PR fixes it so that an error is returned:
```
select '{"longKey1":"longValue1"}} should this data be ignored?'::jsonb;
ERROR: could not parse JSON: trailing characters after JSON document
SQLSTATE: 22P02
```

Release note (bug fix): Do not silently truncate trailing characters when attempting to convert corrupt JSON string input into JSONb.
Release note (backward-incompatible change): This change may be backward incompatible to the applications
that previously might have been able to insert corrupt JSON data, but now will receive an error.

### CODE REVIEW

**Comment by miretskiy** [comment]
I've discovered this issue while working on https://github.com/cockroachdb/cockroach/pull/89884

I'm sure there are other logic/regular tests that may have those faulty assumptions.  Going to wait for CI to shake those out.

**Comment by miretskiy** [comment]
Also note: postgressql rejects those inputs (correctly)

**Comment by jordanlewis** [comment]
Nice find... Could you create an issue to track the bad behavior that this PR closes? Thanks!

**Comment by miretskiy** [comment]
Fixes #https://github.com/cockroachdb/cockroach/issues/89911

**Comment by miretskiy** [comment]
> Nice find... Could you create an issue to track the bad behavior that this PR closes? Thanks!

done.  I put this PR as fixing above issue; but it's up to queries team to decide
of more actions are needed around this bug.

**Review by mgartner — APPROVED** [review]
:lgtm: Nice find!

I'm a bit concerned about backporting this fix that would break any application that relies on the previous behavior. But I think it'd be good to get this fix into 22.2.0. I'll add the backport labels.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89910#-:-NEGlKLeBK7Xg8C5Qld_:b-mt21f0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[`pkg/util/json/json.go` line 851 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/89910#-NEGkDpw-kOO-UTkumXs:-NEGkDpw-kOO-UTkumXt:bqmt0rx) ([raw file](https://github.com/cockroachdb/cockroach/blob/8fc8a56577272f7b6900858b85f7fbcc2b8c3697/pkg/util/json/json.go#L851)):*
> ```Go
> 	// Note: a better way to unmarshal a single JSON value would be to use
> 	// json.Unmarshal; however, we cannot do that because we want to get numbers
> 	// as strings; Alas,  json.Unmarshal does not support that, and so, we have
> ```

nit: remove extra space after `Alas,`.

**Comment by miretskiy** [comment]
> nit: remove extra space after `Alas,`.

done.

**Review by mgartner — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89910)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @miretskiy)

**Review by michae2 — CHANGES_REQUESTED** [review]
Nice fix!

But isn't this going to break any application depending on this behavior?

It seems like this is the kind of thing that should be behind a setting. For example, MySQL has [sql_mode](https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html) for fixes like this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89910#-:-NEH19qe4DA7wQwFPW9I:b-gd8h0n)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @miretskiy)

**Comment by mgartner** [comment]
That's why I suggested not backporting to 22.1 or prior versions. We are free to make breaking changes in major releases, correct?

**Comment by miretskiy** [comment]
> But isn't this going to break any application depending on this behavior?
> 
> It seems like this is the kind of thing that should be behind a setting. For example, MySQL has [sql_mode](https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html) for fixes like this.

Of course, the decision on backports is up to @mgartner ; I would prefer not to add knobs for 
broken behavior.  I think it's better to break applications that send corrupt data and erroneously
think that data was ingested, than to silently truncate data.

**Review by michae2 — COMMENTED** [review]
I guess it's within our [API support policy](https://www.cockroachlabs.com/docs/stable/api-support-policy.html#support-policies) that major versions can have backward-incompatible changes. Ok, I take it back. Maybe just a more explicit release note would be fine.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89910#-:-NEH5Ho072jCQsw6MiV7:b-v2vfsh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @miretskiy)

___
*[`-- commits` line 45 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/89910#-NEH5Mh0EL2vJn6o7EwM):*
Instead of `bug fix` can we use the new `backward-incompatible change` category here?

**Review by michae2 — APPROVED** [review]
:lgtm: thank you!

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/89910#-:-NEH6CqVDSUrj_GRMA8_:bro3093)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @miretskiy)

**Comment by michae2** [comment]
> Release note (backward incompatible fix)

@miretskiy I think this specifically needs to be `backward-incompatible change` or `backwards-incompatible change` to work with doc automation. There are some examples in the [wiki article](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/186548364/Release+notes#Backward-incompatible-change).

**Comment by mgartner** [comment]
The additional release note was a great idea. Thanks for adding that!

**Pull request merged**
