### PR TITLE
colfetcher: fix kvtrace logic test option for inverted index scans

### PR DESCRIPTION
**Pull request by mgartner**
#### rowenc: fix kvtrace logic test option for JSON inverted index scans

Previously, `kvtrace` logic tests of queries that performed JSON
inverted index scans would error if the scan output any rows. When
`cFetcher` attempted to decode the JSON portion of the key,
`rowenc.DecodeTableKey` returned an empty `[]byte` as the portion of the
key remaining after the JSON value. Attempting to decode this empty
`[]byte` as the primary key value caused an error.

Now, `rowenc.DecodeTableKey` will correctly return the remaining bytes
of the key after the JSON value. Note that this function still does not
actually decode the JSON value.

Release note: None

#### encoding: fix typos in DecodeVarintAscending and DecodeVarintDescending

Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57506)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/colfetcher/cfetcher.go, line 467 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57506#-MNeZM3x8E_OzIXXnVvp:-MNeZM3x8E_OzIXXnVvq:b-b7u60j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d383810c4c090414083538adcc4df45d7faf2f54/pkg/sql/colfetcher/cfetcher.go#L467)):*
> ```Go
> 		// value in the index key does not encode the full column value and it
> 		// cannot be decoded.
> 		if table.index.Type == descpb.IndexDescriptor_INVERTED && id == table.index.ColumnIDs[len(table.index.ColumnIDs)-1] {
> ```

The second part of the conditional seems complicated, can we extract a helper method for fetching the ID of the inverted column or add some comments?

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57506)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde and @yuzefovich)

___
*[pkg/sql/colfetcher/cfetcher.go, line 467 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57506#-MNeZM3x8E_OzIXXnVvp:-MNe_aWe27MXvYrK1L4Y:b-rza9h3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d383810c4c090414083538adcc4df45d7faf2f54/pkg/sql/colfetcher/cfetcher.go#L467)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

The second part of the conditional seems complicated, can we extract a helper method for fetching the ID of the inverted column or add some comments?
</blockquote></details>

Heh, there already was a helper function available. LMK if this still is too complicated.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1, 2 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57506#-:-MNear6B-wZs-GzgoIKY:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @yuzefovich)

**Review by yuzefovich — APPROVED** [review]
:lgtm:

Curious why the row execution doesn't have this problem - in `row/fetcher.go` we do seem to be decoding the datums when `traceKV` is `true`.

> Reviewed 2 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57506#-:-MNeaWDM48PjjjeKPGHs:bja1d80)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Comment by mgartner** [comment]
> Curious why the row execution doesn't have this problem - in row/fetcher.go we do seem to be decoding the datums when traceKV is true.

`cfetcher` calls `colencoding.DecodeIndexKeyToCols` which ultimately calls `rowenc.DecodeTableKey`, while `Fetcher.ReadIndexKey` calls `rowenc.DecodeKeyVals` instead. While `rowend.DecodeTableKey` actually decodes keys into `Datum`s, `rowenc.DecodeKeyVals` creates `EncDatum` which aren't really decoded:

```
// EncDatum represents a datum that is "backed" by an encoding and/or by a
// tree.Datum. It allows "passing through" a Datum without decoding and
// reencoding.
```

**Comment by mgartner** [comment]
And now that I think about this more, maybe this isn't the right fix. Maybe we can't decode the inverted column (or shouldn't), but we can still find the remaining bytes and return them [here](https://github.com/cockroachdb/cockroach/blob/3fa5db8777e3a44a1372b51be161498a7526498c/pkg/sql/rowenc/column_type_encoding.go#L283-L284) instead of returning an empty `[]byte`.

**Comment by mgartner** [comment]
@yuzefovich @rytaft PTAL, I think this is a better solution.

**Review by yuzefovich — APPROVED** [review]
I agree, this looks better. :lgtm:

> Reviewed 1 of 3 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57506#-:-MNf4UUo0PaML_yiJYlb:br5axyw)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
