### PR TITLE
cli: add `debug send-kv-batch` command to run arbitrary `BatchRequest`

### LINKED ISSUE #66829: kvserver: admin functionality to manipulate KV data
It would be useful to have functionality to manipulate KV entries, e.g. to get rid of stale node status entries as seen in a recent customer escalation.

This should be implemented as an admin RPC endpoint or separate RPC service that is only available with node certs (i.e. not via gRPC gateway); we don't want this to be too easily accessible.

The endpoint should take an arbitrary gRPC `BatchRequest` and pass it through a local sender stack (including at least `DistSender` but probably also `TxnCoordSender`), effectively proxying the request for the caller. Transaction support is not necessary, using a single atomic `BatchRequest` would be sufficient for most uses.

The `cockroach debug` CLI should at the very least take a Protobuf-encoded BatchRequest, but we may want additional tooling to generate this e.g. from JSON data or CLI command args/flags.

### LINKED ISSUE #67001: kvcoord: add RPC endpoint to issue BatchRequest through TxnCoordSender
**Is your feature request related to a problem? Please describe.**

Unforeseen things happen and sometimes they require a mutation to the KV store that cannot be achieved through SQL. We currently don't have a way to run a "one-off" BatchRequest against a deployed cluster - this requires rebooting the cluster into a custom binary.

**Describe the solution you'd like**

I'd like an endpoint that is reachable via the inter-node certs (i.e. never reachable by anyone but the operator) that accepts a `BatchRequest`, which it then executes through a `TxnCoordSender`.

**Describe alternatives you've considered**

We could "just" use the already existing `Node.Batch` endpoint. However, this requires that the `BatchRequest` already addresses the leaseholder `Replica`, and does not allow cross-range requests. This is quite cumbersome.

We could also provide access to `DistSender` instead of `TxnCoordSender`, but some operations require wrapping in a txn (when ranges are spanned) which the `TxnCoordSender` carries out. (I might be wrong here since that might've changed, still, I don't see a benefit in skipping TxnCoordSender).

A good benchmark should be that it should be possible to send a multi-range scan and a multi-range ClearRange. This will indicate that range-spanning txn'al and non-txn'al operations work well enough.

**Additional context**

### PR DESCRIPTION
**Pull request by erikgrinaker**
This patch adds a CLI command `debug send-kv-batch` that takes a JSON
`BatchRequest` as input, proxies it into KV via the connected node's
admin server, and outputs a JSON `BatchResponse`. An admin user is
required, typically the root user, and the request is logged to the
system event log for auditability.

This is a useful backdoor to access arbitrary KV functionality for
debugging and surgery, e.g. during support escalations.

Resolves #66829.
Resolves #67001.

Release note: None

---

@knz It does not seem like admin commands generally allow specifying a user (e.g. via `--user`), and implicitly require the root user, so I followed that convention here as well. Let me know if we need to extend this.

### CODE REVIEW

**Review by tbg — COMMENTED** [review]
Nice, LGTM and I'll defer to @knz about making sure this is documented and set up in the right way.

I did poke around a bit and ended up rewriting the test a bit, pushed this as a separate commit. Take it or leave it, fine either way.

> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72732#-:-MoYiwT38Ap0QImCZ5yV:b-w0hmby)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @erikgrinaker, @knz, and @tbg)

___
*[docs/generated/eventlog.md, line 168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72732#-MoYYStz3FwTXC7Pq8fI:-MoYYStz3FwTXC7Pq8fJ:bi9d12j) ([raw file](https://github.com/cockroachdb/cockroach/blob/66e0052903c6e7411a65afb6e4cb7c33ae4ac6c5/docs/generated/eventlog.md#L168)):*
> ```Markdown
> | `Timestamp` | The timestamp of the event. Expressed as nanoseconds since the Unix epoch. | no |
> | `EventType` | The type of the event. | no |
> | `NodeID` | The node ID where the event was originated. | no |
> ```

where the event originated
___
*[pkg/cli/debug.go, line 1505 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72732#-MoYi26L8RQYTcW8sdgk:-MoYi26L8RQYTcW8sdgl:b-2xckxi) ([raw file](https://github.com/cockroachdb/cockroach/blob/66e0052903c6e7411a65afb6e4cb7c33ae4ac6c5/pkg/cli/debug.go#L1505)):*
> ```Go
> }
> 
> var debugSendKVBatchCmd = &cobra.Command{
> ```

mind putting this and the impl + tests in a new files `debug_send_kv_batch{,_test}.go`?
___
*[pkg/cli/debug.go, line 1511 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72732#-MoYiSAVAiNxqQhDkWa0:-MoYiSAVAiNxqQhDkWa1:b-k02gtc) ([raw file](https://github.com/cockroachdb/cockroach/blob/66e0052903c6e7411a65afb6e4cb7c33ae4ac6c5/pkg/cli/debug.go#L1511)):*
> ```Go
> 	RunE:  runSendKVBatch,
> 	Long: `
> 	Submits a JSON-formatted roachpb.BatchRequest, given as a file or via stdin,
> ```

The spaces at the beginning of each line shouldn't be there IMO
___
*[pkg/cli/debug_test.go, line 522 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72732#-MoYYvbh9x4JYPuX9o2F:-MoYYvbh9x4JYPuX9o2G:b3kqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/66e0052903c6e7411a65afb6e4cb7c33ae4ac6c5/pkg/cli/debug_test.go#L522)):*
> ```Go
> 	require.Contains(t, output, "ERROR: invalid JSON")
> 
> 	// Unknown JSON field should error
> ```

.
___
*[pkg/server/admin.go, line 2627 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72732#-MoYZ5QEDVVl2fKTGwuM:-MoYZ5QEDVVl2fKTGwuN:bosi01g) ([raw file](https://github.com/cockroachdb/cockroach/blob/66e0052903c6e7411a65afb6e4cb7c33ae4ac6c5/pkg/server/admin.go#L2627)):*
> ```Go
> 	}
> 	nodeID := int32(s.server.NodeID())
> 	event := &eventpb.DebugSendKvBatch{
> ```

customname `DebugSendKVBatch`?
___
*[pkg/server/admin.go, line 2644 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72732#-MoYZBs85VeZdbij_ALC:-MoYZBs974ssOpu1n7T6:b-ek75m0) ([raw file](https://github.com/cockroachdb/cockroach/blob/66e0052903c6e7411a65afb6e4cb7c33ae4ac6c5/pkg/server/admin.go#L2644)):*
> ```Go
> 	})
> 	if err != nil {
> 		log.Warningf(ctx, "failed to log SendKVBatch to event log, emitting below: %v", err)
> ```

I think structured events are unlikely to hit the same log as a Warning, so the "below" may not make sense. Maybe "emitting as structured event"?
___
*[pkg/util/log/eventpb/debug_events.proto, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72732#-MoYZUDdBvjZXw3pjXoW:-MoYZUDdBvjZXw3pjXoX:bb6g3z5) ([raw file](https://github.com/cockroachdb/cockroach/blob/66e0052903c6e7411a65afb6e4cb7c33ae4ac6c5/pkg/util/log/eventpb/debug_events.proto#L32)):*
> ```protobuf
> // CommonDebugEventDetails contains the fields common to all debugging events.
> message CommonDebugEventDetails {
>   // The node ID where the event was originated.
> ```

-was

**Review by erikgrinaker — COMMENTED** [review]
Heh, your test hit what I expect will be a common mistake: Protobuf structs cannot be (un)marshalled using the standard Golang JSON marshaller. You must use the JSON marshaller that's shipped with the Protobuf library, e.g. https://pkg.go.dev/github.com/gogo/protobuf/jsonpb.

I'll update the test to use this, with a big fat warning to anyone following its example.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72732#-:-MoZ023UEowU4xAv1KFf:b-byxbyx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @knz, and @tbg)

___
*[pkg/cli/debug.go, line 1505 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72732#-MoYi26L8RQYTcW8sdgk:-MoZBP8wBTa_gssdPrwt:b9izszt) ([raw file](https://github.com/cockroachdb/cockroach/blob/66e0052903c6e7411a65afb6e4cb7c33ae4ac6c5/pkg/cli/debug.go#L1505)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

mind putting this and the impl + tests in a new files `debug_send_kv_batch{,_test}.go`?
</blockquote></details>

Yup, done.
___
*[pkg/cli/debug.go, line 1511 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72732#-MoYiSAVAiNxqQhDkWa0:-MoZAIsG9JIt3AnmHp8c:bg2pdno) ([raw file](https://github.com/cockroachdb/cockroach/blob/66e0052903c6e7411a65afb6e4cb7c33ae4ac6c5/pkg/cli/debug.go#L1511)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

The spaces at the beginning of each line shouldn't be there IMO
</blockquote></details>

Ah, my bad -- thought I'd seen other commands indent it.
___
*[pkg/server/admin.go, line 2627 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72732#-MoYZ5QEDVVl2fKTGwuM:-MoZ1lePEIAwA5vLt6TT:b-8seiol) ([raw file](https://github.com/cockroachdb/cockroach/blob/66e0052903c6e7411a65afb6e4cb7c33ae4ac6c5/pkg/server/admin.go#L2627)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

customname `DebugSendKVBatch`?
</blockquote></details>

I don't think `customname` can be applied to messages, only fields. Unfortunately, we need the `Kv` here to get the snake-cased event type generated correctly.
___
*[pkg/server/admin.go, line 2644 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72732#-MoYZBs85VeZdbij_ALC:-MoZAlZQ8NS1ZG4788l2:b-sza905) ([raw file](https://github.com/cockroachdb/cockroach/blob/66e0052903c6e7411a65afb6e4cb7c33ae4ac6c5/pkg/server/admin.go#L2644)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I think structured events are unlikely to hit the same log as a Warning, so the "below" may not make sense. Maybe "emitting as structured event"?
</blockquote></details>

Right, good catch.

**Review by knz — COMMENTED** [review]
> Reviewed 14 of 15 files at r1, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72732)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @erikgrinaker, and @tbg)

___
*[pkg/server/admin.go, line 2637 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72732#-MoYxaCI1k-r3T8tdaCT:-MoYxaCI1k-r3T8tdaCU:b-iio948) ([raw file](https://github.com/cockroachdb/cockroach/blob/66e0052903c6e7411a65afb6e4cb7c33ae4ac6c5/pkg/server/admin.go#L2637)):*
> ```Go
> 		BatchRequest: string(baJSON),
> 	}
> 	err = contextutil.RunWithTimeout(ctx, "log-event", 10*time.Second, func(ctx context.Context) error {
> ```

Can you explain to me the wisdom of using system.eventlog here, while we're generally trying to get away from using this table (also, observing that if one finds themselves in need to reach out to this debug facility, chances are this write may be impossible).
___
*[pkg/server/admin.go, line 2645 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72732#-MoYxnq9C60nZcAqhRFm:-MoYxnq9C60nZcAqhRFn:b-8lzy3b) ([raw file](https://github.com/cockroachdb/cockroach/blob/66e0052903c6e7411a65afb6e4cb7c33ae4ac6c5/pkg/server/admin.go#L2645)):*
> ```Go
> 	if err != nil {
> 		log.Warningf(ctx, "failed to log SendKVBatch to event log, emitting below: %v", err)
> 		log.StructuredEvent(ctx, event)
> ```

The structured event should be logged in any case.
I think you're relying on the idea that InsertEventRecord will also call log.StructuredEvent above? But then that needs to be clarified.
(I'd argue all this could be simplified by _only_ calling log.StructuredEvent here.)

Also, the structured logging needs a test.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72732)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @erikgrinaker, @knz, and @tbg)

___
*[pkg/server/admin.go, line 2637 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72732#-MoYxaCI1k-r3T8tdaCT:-Moc51Zj8g7KZrOmltK0:b-eoyka8) ([raw file](https://github.com/cockroachdb/cockroach/blob/66e0052903c6e7411a65afb6e4cb7c33ae4ac6c5/pkg/server/admin.go#L2637)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Can you explain to me the wisdom of using system.eventlog here, while we're generally trying to get away from using this table (also, observing that if one finds themselves in need to reach out to this debug facility, chances are this write may be impossible).
</blockquote></details>

I was under the impression that system.eventlog is part of our event/audit logging facilities. You seem to be saying that it's unnecessary or deprecated here, so I'll remove it.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72732)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @knz, and @tbg)

___
*[pkg/server/admin.go, line 2645 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72732#-MoYxnq9C60nZcAqhRFm:-MocUC3p7bJc0_vXrCK9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/66e0052903c6e7411a65afb6e4cb7c33ae4ac6c5/pkg/server/admin.go#L2645)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

The structured event should be logged in any case.
I think you're relying on the idea that InsertEventRecord will also call log.StructuredEvent above? But then that needs to be clarified.
(I'd argue all this could be simplified by _only_ calling log.StructuredEvent here.)

Also, the structured logging needs a test.
</blockquote></details>

Done.

**Comment by erikgrinaker** [comment]
@knz Any further thoughts on this?

**Review by knz — APPROVED** [review]
Sorry for the tardiness!

:lgtm_strong: 

> Reviewed 18 of 18 files at r4, 17 of 17 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72732#-:-MpNJtR7AT7iSX13Knwj:b-40zw90)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt)

**Comment by erikgrinaker** [comment]
TFTRs!

bors r=knz,tbg

**Comment by tbg** [comment]
Btw, demo about this on next weekly? This is cool stuff.

(sent from mobile, please excuse my brevity)

**Comment by erikgrinaker** [comment]
>Btw, demo about this on next weekly? This is cool stuff.

Sure thing. It's pretty trivial tbh, but extremely useful.

**Pull request merged**
