### PR TITLE
rac2: fix token return behaviour

### PR DESCRIPTION
**Pull request by pav-kv**
This PR converts the raw `index, term` pairs in `rac2` package to ones that carry raft log semantics:

- `AdmittedVector` is per leader term, and should be passed around wholesale.
- The entries in `Tracker` are identified by log entry ID, which should be passed around wholesale, to carry the appropriate semantics. These should not be confused with `LogMark`.

---

The last commit fixes premature flow token returns in the token tracker.

Our log (at leader `term`) is:
```
prefix=[other term entries] + suffix=[entryID.term == term]
```

The old code, in the common case (receiving `AdmittedVector` for the current leader `term`), would return tokens for the entire `prefix`, and everything from the `suffix` up to the corresponding admitted index. The problem with this is when the admitted index is in the `prefix` part. Regardless of how low the index is, we will return everything from the
`prefix`. This effectively turns RACv2 into no-op after a leader change. We would "recover" only when admitted indices reach the leader's own entries.

On a stale `AdmittedVector.Term`, we similarly would return a whole prefix of entries < `av.Term`, and maybe a suffix of `av.Term` entries if the index is high enough.

---

Epic: CRDB-37515

### CODE REVIEW

**Comment by pav-kv** [comment]
@kvoli @sumeerbhola The last commit fixes the token return bug. PTAL.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 3 files at r3, 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132173#-:-O8hNcyp93AdFpYqBice:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 387 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/132173#-O8hKMjZ6FeXtf9H3Bom:-O8hKMjZ6FeXtf9H3Bon:bpezl4o) ([raw file](https://github.com/cockroachdb/cockroach/blob/837080c7c6cedc21e5545cb8b112404302f242e1/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L387)):*
> ```Go
> // RangeControllerInitState is the initial state at the time of creation.
> type RangeControllerInitState struct {
> 	// Term is the raft term of the leader who runs this RangeController.
> ```

Consider adding
// This will also never change in the lifetime of the RangeController.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 402 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/132173#-O8hKUnlCWSj-8vi0oJx:-O8hKUnmERMJ2b9zup97:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/837080c7c6cedc21e5545cb8b112404302f242e1/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L402)):*
> ```Go
> type rangeController struct {
> 	opts       RangeControllerOptions
> 	term       uint64
> ```

ditto
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go` line 102 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/132173#-O8hMPGR0tBkHwxfNG2I:-O8hMPGR0tBkHwxfNG2J:b4jbhgh) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1246c186a4912c661f57f6fe1a752ab61c32169/pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go#L102)):*
> ```Go
> 		for n := len(t.tracked[pri]); untracked < n; untracked++ {
> 			deduction := t.tracked[pri][untracked]
> 			if deduction.term > term || (deduction.term == term && deduction.index > uptoIndex) {
> ```

since we were incorrectly using the AdmittedVector term here, it would cause early return because of the AdmittedVector from a stale leader, yes? That is, for the parts of the log that were not overrwritten.
But it seems it can't delay return since the AdmittedVector from the latest leader should have a higher term. Am I missing something?

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132173)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go` line 102 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/132173#-O8hMPGR0tBkHwxfNG2I:-O8hXskXD7LxPPOFSrX8:bgmykb7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1246c186a4912c661f57f6fe1a752ab61c32169/pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go#L102)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

since we were incorrectly using the AdmittedVector term here, it would cause early return because of the AdmittedVector from a stale leader, yes? That is, for the parts of the log that were not overrwritten.
But it seems it can't delay return since the AdmittedVector from the latest leader should have a higher term. Am I missing something?
</blockquote></details>

Our log (at leader `term`) is:

```
prefix=[entries with older terms] + suffix=[entries with entryID.term == term]
```

The old code, in the common case (receiving `AdmittedVector` for the current leader `term`), would return tokens for the entire `prefix`, and everything from the `suffix` up to the `uptoIndex`. The problem with this is when `uptoIndex` is in the `prefix` part. Regardless of how low the index is, we will return everything. This effectively turns RACv2 into no-op at leader change situations. We would "recover" only when admitted indices reach the leader's own entries.

On a stale `AdmittedVector.Term`, we similarly would return a whole prefix of entries < `av.Term`, and maybe a suffix of `av.Term` entries if the index is high enough.

Yeah, seemingly there is not admission delay issues. This is because the leader term >= entry terms.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132173)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go` line 102 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/132173#-O8hMPGR0tBkHwxfNG2I:-O8hcK4P6zpW23MNGnex:b-rauxdx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1246c186a4912c661f57f6fe1a752ab61c32169/pkg/kv/kvserver/kvflowcontrol/rac2/token_tracker.go#L102)):*
> Yeah, seemingly there is not admission delay issues. This is because the leader term >= entry terms.

Ack

**Review by kvoli — APPROVED** [review]
:lgtm_strong: 

> Reviewed 3 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132173#-:-O8mGrIoA4xBjYz-FeF1:b-uwkowd)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @pav-kv)

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132173)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 387 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/132173#-O8hKMjZ6FeXtf9H3Bom:-O8nBimE41GIzxwR0hu9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/837080c7c6cedc21e5545cb8b112404302f242e1/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L387)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Consider adding
// This will also never change in the lifetime of the RangeController.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 402 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/132173#-O8hKUnlCWSj-8vi0oJx:-O8nBxgP-0jEiVdq3tHx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/837080c7c6cedc21e5545cb8b112404302f242e1/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L402)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Comment by pav-kv** [comment]
bors r=sumeerbhola,kvoli

**Comment by pav-kv** [comment]
bors cancel

**Comment by pav-kv** [comment]
bors retry

**Pull request merged**
