### PR TITLE
ccl/sqlproxyccl: rename tenant.Resolver to tenant.DirectoryCache 

### PR DESCRIPTION
**Pull request by jaylim-crl**
Informs #76000.

#### ccl/sqlproxyccl: move the TenantResolver interface to the tenant package 

Previously, the TenantResolver interface lived in the base sqlproxyccl package,
and there was no way to enforce that the tenant.Directory struct implements
this interface since that would result in a cyclic dependency. This commit
moves the TenantResolver interface into the tenant package, and enforced that
the tenant.Directory struct implements that.

This would then allow us to rename the tenant.Directory struct to
tenant.directoryCache, and the tenant.Resolver interface to
tenant.DirectoryCache.

Release note: None

#### ccl/sqlproxyccl: rename tenant.Resolver to tenant.DirectoryCache 

This commit renames the tenant.Resolver interface to tenant.DirectoryCache.
The existing Directory struct was also renamed to directoryCache to prevent
confusions since there were previously two definitions of a "directory": one
pointing to the cache of entries, whereas another referring to the actual
directory server.

Release note: None

### CODE REVIEW

**Review by jeffswenson — APPROVED** [review]
LGTM

**Review by andy-kimball — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78276#-:-MympsHF--apHtOncez2:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by jaylim-crl** [comment]
TFTR! 

bors r=JeffSwenson,andy-kimball

**Comment by jaylim-crl** [comment]
blathers backport 22.1

**Pull request merged**
