### PR TITLE
sql: function and schema hydration

### PR DESCRIPTION
**Pull request by chengxiong-ruan**
This commit generalizes the hydrated table cache to handle
`HydratableDescriptor`s (table, function, schema). Type
hydration function are added for functions and schema.

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
If you're going this far, we probably ought to hydrate type descriptors too in the case of the alias types. This has been a wart in the past. I could see one day also doing the database descriptors with regards to their reference to the region type. What do you think?

> Reviewed 5 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85323#-:-N8Oj0ce8HgC52eYKHVv:bua1gl0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @chengxiong-ruan)

___
*[`pkg/sql/catalog/descriptor.go` line 235 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85323#-N8OiUbSDigPKZW2sM7z:-N8OiUbTAJu4jP0_rjPe:bsm9hgh) ([raw file](https://github.com/cockroachdb/cockroach/blob/48d7b7725f9c549afc3a2ba48f834011a596e1a5/pkg/sql/catalog/descriptor.go#L235)):*
> ```Go
> 	// user defined types. For example, a table column table can use user defined
> 	// type and a function can use user defined type as an argument type.
> 	ContainsUserDefinedTypes() bool
> ```

thoughts on just lifting this up to the `Descriptor` interface?

**Comment by chengxiong-ruan** [comment]
sorry, chatted offline but forget to comment here.
Given the timeline, I won't go further than this pr. I'd love to do it when needs come up.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85323#-:-N8RZxeSDUfj2-wpj9go:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @chengxiong-ruan)

**Comment by chengxiong-ruan** [comment]
TFTR!
bors r+

**Pull request merged**
