### PR TITLE
opt: prevent overflow when normalizing comparison with constants

### PR DESCRIPTION
**Pull request by mgartner**
#### opt: prevent overflow when normalizing comparison with constants

Previously, the `NormalizeCmpPlusConst`, `NormalizeCmpMinusConst`, and
`NormalizeCmpMinusConst` would normalize expressions in the form
`var +/- const1 ? const2` and `const1 - var ? const2`, where `const1`
and `const2` were const constants and `?` is any comparison operator, to
attempt to isolate the variable on one side of the comparison. Below are
some examples of the transformations these rules made:

    a+1 > 10 =>  a > 10-1
    a-1 > 10 =>  a > 10+1
    1-a > 10 =>  1-10 > a

However, these transformations were invalid when the newly created
addition or subtraction operators overflowed. In the case of an
expression involving TIME and INTERVAL types, this could cause incorrect
query results. For example:

    t-'2 hr'::INTERVAL < '23:00:00'::TIME
    =>
    t < '23:00:00'::TIME+'2 hr'::INTERVAL
    =>
    t < '01:00:00'::TIME

The first expression and last expression have different semantic meaning
because the addition of the constant TIME and constant INTERVAL
overflowed.

This commit prevents the rules from transforming expressions if they
would cause an overflow/underflow. In order to detect overflow, there
are new restrictions that prevent these rules from firing in some cases.
Notably, the datum on the RHS of the newly constructed +/- operator must
be an integer, float, decimal, or interval. Also, the result type of the
newly constructed +/- operator must be equivalent to the LHS of the
operator. Both of these restrictions are required in order to detect
overflow/underflow.

Informs #88128

Release note (bug fix): A bug has been fixed that caused incorrect
evaluation of expressions in the form `col +/- const1 ? const2`, where
`const1` and `const2` are constant values and `?` is any comparison
operator. The bug was caused by operator overflow when the optimizer
attempted to simplify these expressions to have a single constant value.

#### normalize: remove invalid normalizations

It was recently discovered that normalization rules in the optimizer
were invalid (see #88128). These rules were adapted from the heuristic
optimizer several years ago, and they still remain in the `normalize`
package even though the heuristic optimizer no longer exists. The
`normalize` package is still used to normalize expressions during
backfilling, so the invalid rules can cause incorrect computed column
values and corrupt indexes. This commit removes these rules entirely.

Informs #88128

Release note: None

### CODE REVIEW

**Review by msirek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88199)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @michae2)

___
*[`pkg/sql/logictest/testdata/logic_test/time` line 566 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88199#-NCNCk404QpQieQjoayL:-NCNCk404QpQieQjoayM:b-doo1ir) ([raw file](https://github.com/cockroachdb/cockroach/blob/18168e060ae5dc845ad020a6b8d71b852a6ae8df/pkg/sql/logictest/testdata/logic_test/time#L566)):*
> ```
> SELECT t + '02:00:00'::INTERVAL < '01:00:00'::TIME FROM t88128
> ----
> false
> ```

We may need to check for overflow and underflow for both `+` and `-`, for example this test still shows incorrect results:
```
query B
SELECT t + '-18:00:00'::INTERVAL < '07:00:00'::TIME FROM t88128
----
true
```

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88199)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @michae2)

___
*[`pkg/sql/opt/norm/comp_funcs.go` line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88199#-NCNFq4v1WtJEFJDDfON:-NCNFq4v1WtJEFJDDfOO:bcrowfq) ([raw file](https://github.com/cockroachdb/cockroach/blob/18168e060ae5dc845ad020a6b8d71b852a6ae8df/pkg/sql/opt/norm/comp_funcs.go#L44)):*
> ```Go
> //  1. An overload function for the given operator and input types exists and
> //     has an appropriate volatility.
> //  2. The result type of the overload is equivalent to the type of left. This
> ```

Why is this condition necessary? I don't think the datum comparison functions require the same type, at least in general.

**Comment by mgartner** [comment]
*[`pkg/sql/opt/norm/comp_funcs.go` line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88199#-NCNFq4v1WtJEFJDDfON:-NCQ5MiZ4Q1EQE5Zplqh:b8p3uqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/18168e060ae5dc845ad020a6b8d71b852a6ae8df/pkg/sql/opt/norm/comp_funcs.go#L44)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Why is this condition necessary? I don't think the datum comparison functions require the same type, at least in general.
</blockquote></details>

They must be comparable in order to check for overflow. For example, consider:

```sql
CREATE TABLE t (i INTERVAL);
SELECT '1:00:00'::TIME + i >= '2:00:00'::TIME;
```

With this tranformation, we try to compute `'2:00:00'::TIME - '1:00:00'::TIME`, which results in an `INTERVAL`, not a `TIME`. Because an `INTERVAL` cannot be compared with a `TIME`, the overflow detection won't work.

Perhaps when a subtraction yields a different type than the operands, it is guaranteed there is no overflow? I didn't spend too much time thinking through if this is true generally, but if you have any insight, let me know. I thought for now I'd err on the side of overly restrictive (I even considered removing these rules entirely since I don't believe it's common to write expressions in this form and I'm weary of other bugs lurking here). I could leave a TODO mentioning that this restriction might be able to be lifted, if you'd like.

**Review by DrewKimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88199)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @michae2)

___
*[`pkg/sql/opt/norm/comp_funcs.go` line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88199#-NCNFq4v1WtJEFJDDfON:-NCSNuFt8OUxBvbrN1vX:b-lyppnu) ([raw file](https://github.com/cockroachdb/cockroach/blob/18168e060ae5dc845ad020a6b8d71b852a6ae8df/pkg/sql/opt/norm/comp_funcs.go#L44)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

They must be comparable in order to check for overflow. For example, consider:

```sql
CREATE TABLE t (i INTERVAL);
SELECT '1:00:00'::TIME + i >= '2:00:00'::TIME;
```

With this tranformation, we try to compute `'2:00:00'::TIME - '1:00:00'::TIME`, which results in an `INTERVAL`, not a `TIME`. Because an `INTERVAL` cannot be compared with a `TIME`, the overflow detection won't work.

Perhaps when a subtraction yields a different type than the operands, it is guaranteed there is no overflow? I didn't spend too much time thinking through if this is true generally, but if you have any insight, let me know. I thought for now I'd err on the side of overly restrictive (I even considered removing these rules entirely since I don't believe it's common to write expressions in this form and I'm weary of other bugs lurking here). I could leave a TODO mentioning that this restriction might be able to be lifted, if you'd like.
</blockquote></details>

Oh, I didn't realize `INTERVAL` and `TIME` are incomparable. I think it's fine to leave as is, in that case. Thanks for explaining.

**Review by mgartner — COMMENTED** [review]
I added a new commit which fixes the same bug in the `normalize` package (a remnant of the old heuristic optimizer that is still used during backfills). PTAL!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88199#-:-NCW7M7y0HF_o1SrZuUt:b-tin46v)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, and @msirek)

___
*[`pkg/sql/logictest/testdata/logic_test/time` line 566 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88199#-NCNCk404QpQieQjoayL:-NCRmBQM93SS0iu68-YU:b9i1put) ([raw file](https://github.com/cockroachdb/cockroach/blob/18168e060ae5dc845ad020a6b8d71b852a6ae8df/pkg/sql/logictest/testdata/logic_test/time#L566)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

We may need to check for overflow and underflow for both `+` and `-`, for example this test still shows incorrect results:
```
query B
SELECT t + '-18:00:00'::INTERVAL < '07:00:00'::TIME FROM t88128
----
true
```
</blockquote></details>

Woof, good catch!

I think the only way to detect underflow and overflow in these cases is to know if the RHS of the new `+/-` expression is `> 0` or `< 0`. I've added in logic to detect overflow and underflow for all three rules, but I had to add the additional restriction that the RHS of the new `+/-` expression is an integer, float, decimal, or interval - because its easy to create zero values for those types. It may be possible to expand this set of valid types in the future, but I think this is good enough for now.

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 2 of 7 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88199#-:-NCWVum004VPDNj2QYBW:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner, @michae2, and @msirek)

**Review by msirek — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88199#-:-NCX65IMCAjWroHoB16W:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @mgartner, @michae2, and @msirek)

___
*[`pkg/sql/opt/norm/testdata/rules/comp` line 132 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88199#-NCX5gzK8MA3eeBzpjOf:-NCX5gzK8MA3eeBzpjOg:b-b6xdyk) ([raw file](https://github.com/cockroachdb/cockroach/blob/c074c683ebfc0754ff67eeaa049fb7817ec57432/pkg/sql/opt/norm/testdata/rules/comp#L132)):*
> ```
>       └── (s:4::DATE + '02:00:00') = '2000-01-01 02:00:00' [outer=(4), stable]
> 
> # The rule should not apply if the type of RHS the created Minus operator is a
> ```

nit: 'is a' -> 'is'

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88199)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @DrewKimball, @michae2, and @msirek)

___
*[`pkg/sql/opt/norm/comp_funcs.go` line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88199#-NCNFq4v1WtJEFJDDfON:-ND-0S_14AnoljgfpSjt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/18168e060ae5dc845ad020a6b8d71b852a6ae8df/pkg/sql/opt/norm/comp_funcs.go#L44)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Oh, I didn't realize `INTERVAL` and `TIME` are incomparable. I think it's fine to leave as is, in that case. Thanks for explaining.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/norm/testdata/rules/comp` line 132 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/88199#-NCX5gzK8MA3eeBzpjOf:-ND-0V0uB6UWlQAZ5jRT:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/c074c683ebfc0754ff67eeaa049fb7817ec57432/pkg/sql/opt/norm/testdata/rules/comp#L132)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

nit: 'is a' -> 'is'
</blockquote></details>

Done

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88199#-:-ND-7ghj7DmN34RF3SM0:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @michae2, and @msirek)

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
