### PR TITLE
release-19.1: revert recent error-handling changes

### PR DESCRIPTION
**Pull request by RaduBerinde**
Reverting the following backports:

- release-19.1: error handling fixes deemed necessary from nightlies #36064
  - 1/1 commits from "sql: ensure errors are unwrapped before their type is tested" (#35962)
  - 1/1 commits from "sql: avoid wrapping the special lease expiration error object" (#36011)

- release-19.1: pgerror: avoid wrapping special roachpb errors #35939
  * 1/1 commits from “pgerror: avoid wrapping special roachpb errors” #35937
  * 1/1 commits from “distsqlpb,importccl: fix a regression in IMPORT” #35944

- release-19.1: sql*: use pgerror in more places
  * 2/2 commits from “sql*: use pgerror in more places” #35845.

 - 1 commit from pre-fork PR #35821:
   * Revert "sql*: use pgerror.{Wrapf,NewAssertionError*} where appropriate" 8cfcbb436ef73dcec03b23b91d41ee430a960ce9.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
To provide some context here, we (Jordan, Andrei, myself) are considering reverting the recent error changes from 19.1 rather than moving forward with #36023 because these add up to a lot of code changes so late in the release.

For now this is just a first try to see what failures we get in CI. `make test` passed locally.

**Comment by andreimatei** [comment]
lo and behold, it passed TC.

LGTM

**Comment by RaduBerinde** [comment]
I tested that an assertion error still gets a stack trace, and gets sent to sentry.

**Comment by RaduBerinde** [comment]
CCing @knz so you are aware of this. I hope I chose the right subset of commits to get us into a stable state.

**Comment by jordanlewis** [comment]
LGTM. This was good work and it is unfortunate we need to revert it, but the risk of instability in the release was too high. I think the right time for this kind of necessary, sweeping refactor is after the release goes out.

**Pull request merged**
