### PR TITLE
ui: Update colors and typography

### LINKED ISSUE #45471: ui: update colors and fonts across admin ui
Update old Admin UI colors and fonts to our new design system. 
I've mapped the [color and font updates here](https://www.figma.com/file/TqjqzNz8WpGJCTy0UBFxHB/obsrv-design-components-v1?node-id=1295%3A25)

Let me know if there are any colors or fonts missing or if there is a better way to do this.

Here is the full [design system](https://www.figma.com/file/B5AtEGdRbW3VxiBdg62TB8Xw/CRDB-Design-System_V2?node-id=0%3A1) for reference 

Frame 1
Frame 2

### PR DESCRIPTION
**Pull request by koorosh**
Resolves: #45471

Current change is intended to:
- unify styles across entire app (fonts, sizes, colors)
- remove dependency on redundant styles in `palette.styl`

Before, the main source of design tokens was located in `palette.styl` and `pkg/ui/styl/base` dir. 
These styles in general don't match to new changed designs and have to be replaced with a new ones, which now are stored in `src/components/core` (colors and typography).
Also a lot of styles were hardcoded across entire app in different style files.

To make styles more unified and make one step forward to get rid of old styles, following
changes were made:
- Hardcoded values in component styles were replaced to appropriate design tokens;
- Defined tokens in `palette.styl` which exactly match to new designs are re-referenced to new designs (so the act like aliases so it doesn't break existing code)
- Remapped colors and font styles according to rules defined in #45471 

~~What is not included:~~
- ~~Current which required total redesign of particular components~~
- ~~or changes which might affect/break page layouts.~~

Release note (admin ui change): 
- Update colors according to new designs
-  Use new SourceSansPro
font across all Admin UI
- Update font styles for monospace text
(sql statements, etc)

Release justification: bug fixes and low-risk updates to new functionality

### CODE REVIEW

**Review by dhartunian — CHANGES_REQUESTED** [review]
Looks good @koorosh can you add a release note + justification about the changes?

Also, this PR will not resolve all the parts of the issue so just reference the issue without "resolves".

> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45979#-:-M3gNQuF7_3njlG2PMRU:be1e3n7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

**Comment by koorosh** [comment]
> Looks good @koorosh can you add a release note + justification about the changes?
> 
> Also, this PR will not resolve all the parts of the issue so just reference the issue without "resolves".
> 
> > Reviewed 13 of 13 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45979#-:-M3gNQuF7_3njlG2PMRU:be1e3n7)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

Done. (updated commit messages where changes affect UI and PR message as well)

**Comment by koorosh** [comment]
> Also, this PR will not resolve all the parts of the issue so just reference the issue without "resolves".
🤔hm, it is supposed to resolve this issue, it covers changes for colors and typography.
The remaining part of changes discussed in thread (for login page, and network latency colors) have their own issues. Maybe I missed something?

**Comment by dhartunian** [comment]
@koorosh my concern was your mention of "What is not included". Did I misread? I assumed that meant there are some changes in the issue that are not addressed.

**Comment by koorosh** [comment]
> @koorosh my concern was your mention of "What is not included". Did I misread? I assumed that meant there are some changes in the issue that are not addressed.

Ah, you're right, that was mentioned initially, and then in issues thread (https://github.com/cockroachdb/cockroach/issues/45471#issuecomment-597721463) where Anne pointed  out that we already have created issues for components which `is not included in this change`.
> I created an issue that Vlad worked on here #45447 to address headers and back arrow links. Let me know if that covers what you are referring to. It would be great the have the two headers as stand alone components to be reused.

> Good point about the login page. I think it's okay for now but will create a new issue and designs to update.

Then only this PR resolves the issue.

**Review by dhartunian — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45979#-:-M4R1Lb48ofZn4dj2gH7:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian)

**Pull request merged**
