### PR TITLE
streamingccl: add minimum flush interval cluster setting

### PR DESCRIPTION
**Pull request by pbardea**
Previously, the stream ingestion processor would flush on every resolved
timestamp event it received, regardless of the frequency of those
events. Now, the processor will flush at most `minFlushInterval` due to
resolved timestamp events. It may still flush more often if the
in-memory buffer is full.

We want to flush less often because larger batches are more efficient to
ingest. Ingesting a batch of 100 keys is much faster than ingesting 100
batches of 1 key each due to the overhead of each request.

Release note: None

### CODE REVIEW

**Comment by pbardea** [comment]
@adityamaru , looks like some test is still failing, but tagging you as a reviewer if you wanted to get an early look. I'll ping you again when I get CI green and this rebased.

**Review by adityamaru — APPROVED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60160)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea)

___
*[pkg/ccl/streamingccl/streamclient/random_stream_client.go, line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60160#-MTGWgx39zKAF7dj-fLp:-MTGWgx39zKAF7dj-fLq:bxvnmxr) ([raw file](https://github.com/cockroachdb/cockroach/blob/28e7f285329cef97eab6076dfc3272aa6cd77f77/pkg/ccl/streamingccl/streamclient/random_stream_client.go#L176)):*
> ```Go
> 
> 			if numKVEventsSinceLastResolved == m.config.kvsPerCheckpoint {
> 				// Emit a CheckpointEvent
> ```

nit: missing full stop
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go, line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60160#-MTGSD9B1C6KOjcP1xsp:-MTGSD9B1C6KOjcP1xsq:b9uyejs) ([raw file](https://github.com/cockroachdb/cockroach/blob/28e7f285329cef97eab6076dfc3272aa6cd77f77/pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go#L171)):*
> ```
> read
> ```
nit: Read
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go, line 294 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60160#-MTGU1y-Cl8E6CWOB9-d:-MTGU1y-Cl8E6CWOB9-e:bxvnmxr) ([raw file](https://github.com/cockroachdb/cockroach/blob/28e7f285329cef97eab6076dfc3272aa6cd77f77/pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go#L294)):*
> ```Go
> 		case event, ok := <-events:
> 			if !ok {
> 				// Done consuming events
> ```

nit: missing full stop
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go, line 308 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60160#-MTGYgvE6KGzH-FGSVeQ:-MTGYgvFD75-qGXrO440:b-3ym65n) ([raw file](https://github.com/cockroachdb/cockroach/blob/28e7f285329cef97eab6076dfc3272aa6cd77f77/pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go#L308)):*
> ```Go
> 				}
> 
> 				minFlushInterval := 5 * time.Millisecond
> ```

should this use the cluster setting instead?
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go, line 318 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60160#-MTGYl-V4K5w1izqO7uw:-MTGYl-V4K5w1izqO7ux:bhdz06l) ([raw file](https://github.com/cockroachdb/cockroach/blob/28e7f285329cef97eab6076dfc3272aa6cd77f77/pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go#L318)):*
> ```Go
> 				}
> 
> 				if err := sip.flush(); err != nil {
> ```

probably not a big deal but say the next eligible flush time is t1. We receive a ts event at t0 and so we reset the timer to fire at t1. We receive another ts event at t1 so we reach this code and flush. The next time we loop around we might flush again because the <-timer.C might be picked?

Should we reset the timer after this flush?

**Comment by pbardea** [comment]
@adityamaru This should be RFAL. I went back to processing the events in the same goroutine as `Next`, which really simplifies thinking about how we clean up resources (like the batcher).

**Review by adityamaru — COMMENTED** [review]
> Reviewed 4 of 6 files at r2, 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60160)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @pbardea)

___
*[pkg/ccl/streamingccl/streamclient/random_stream_client.go, line 294 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/60160#-MTN6P0YEl6xa_ZjLbnB:-MTN6P0YEl6xa_ZjLbnC:buf3axz) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cfe4c2062da98e298f9282a574d0d026b5b9ea9/pkg/ccl/streamingccl/streamclient/random_stream_client.go#L294)):*
> ```
> and update its timestamp to now()
> ```
don't think we're updating it to now() anymore.
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go, line 174 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/60160#-MTNBNV26iiUDNJ4IR4Q:-MTNBNV3478BYuXFz7I6:b-rg1iok) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cfe4c2062da98e298f9282a574d0d026b5b9ea9/pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go#L174)):*
> ```Go
> 		eventCh, err := sip.client.ConsumePartition(ctx, partitionAddress, startTime)
> 		if err != nil {
> 			sip.ingestionErr = errors.Wrapf(err, "consuming partition %v", partitionAddress)
> ```

I might be missing something but should we not be `sip.MoveToDraining` if setting up one of the partitions fails. Currently, if we were to set this error and not teardown, we would only check sip.ingestionErr after we have potentially consumed several events from the other partitions. Is this expected, or should we be falling fast?

**Review by pbardea — COMMENTED** [review]
Addressed comments -- was also getting a bunch of races/timeouts during creating a test cluster. Rebased to see if something like that has been fixed on master recently. Hopefully CI should be happy with this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60160#-:-MTNPQIf4V_OlMX-xm3p:bystlaw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru)

___
*[pkg/ccl/streamingccl/streamclient/random_stream_client.go, line 176 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60160#-MTGWgx39zKAF7dj-fLp:-MTNM_sS1e5jkkrPfSSH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/28e7f285329cef97eab6076dfc3272aa6cd77f77/pkg/ccl/streamingccl/streamclient/random_stream_client.go#L176)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

nit: missing full stop
</blockquote></details>

Done.
___
*[pkg/ccl/streamingccl/streamclient/random_stream_client.go, line 294 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/60160#-MTN6P0YEl6xa_ZjLbnB:-MTNMaSJ6Zk4gGRf86s_:bbcosmr) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cfe4c2062da98e298f9282a574d0d026b5b9ea9/pkg/ccl/streamingccl/streamclient/random_stream_client.go#L294)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

> ```
> and update its timestamp to now()
> ```
don't think we're updating it to now() anymore.
</blockquote></details>

It looks like we stopped before this diff. Updated the comment.
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go, line 294 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60160#-MTGU1y-Cl8E6CWOB9-d:-MTNNaXj8PwH1GEO2l_B:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/28e7f285329cef97eab6076dfc3272aa6cd77f77/pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go#L294)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

nit: missing full stop
</blockquote></details>

Done.
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go, line 308 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60160#-MTGYgvE6KGzH-FGSVeQ:-MTNNbHh9uGIuTyoqoI_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/28e7f285329cef97eab6076dfc3272aa6cd77f77/pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go#L308)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

should this use the cluster setting instead?
</blockquote></details>

Done.
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go, line 318 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60160#-MTGYl-V4K5w1izqO7uw:-MTNNdUX4wCo1mwXa9iI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/28e7f285329cef97eab6076dfc3272aa6cd77f77/pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go#L318)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

probably not a big deal but say the next eligible flush time is t1. We receive a ts event at t0 and so we reset the timer to fire at t1. We receive another ts event at t1 so we reach this code and flush. The next time we loop around we might flush again because the <-timer.C might be picked?

Should we reset the timer after this flush? 
</blockquote></details>

Done.
___
*[pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go, line 174 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/60160#-MTNBNV26iiUDNJ4IR4Q:-MTNGOsx6e1x87X_3Mok:b213yzh) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cfe4c2062da98e298f9282a574d0d026b5b9ea9/pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go#L174)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

I might be missing something but should we not be `sip.MoveToDraining` if setting up one of the partitions fails. Currently, if we were to set this error and not teardown, we would only check sip.ingestionErr after we have potentially consumed several events from the other partitions. Is this expected, or should we be falling fast?
</blockquote></details>

Yep, updated. It also made me realize that we shouldn't be creating the batcher in `newStreamIngestionProcessor` since we don't have a context there yet. Updated that too and added a test case for this case.

Nice catch!

**Comment by pbardea** [comment]
This was updated a bit and should be RFAL.

**Review by adityamaru — APPROVED** [review]
> Reviewed 1 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60160)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru)

**Comment by pbardea** [comment]
TFTR
bors r=adityamaru

**Comment by dankinder** [comment]
Hey @pbardea I recently tested out v21.1.0-rc1 (upgrading from v21.1.0-alpha3) and noticed large IMPORT jobs started failing with `context canceled`. However when I `set cluster setting bulkio.stream_ingestion.minimum_flush_interval = '0.1s'` instead of the default `5s` it started succeeding again. Maybe this change caused it? I pasted the logs below that led me to this theory. If you think this is a reasonable theory I can file a new issue.

This particular cluster has 44 nodes, ~8TB of data, 140k ranges.

```
I210507 13:05:04.266767 11175754 jobs/registry.go:1175 ⋮ [n1] 237667  IMPORT job ‹656415064518164481›: stepping through state reverting with error: communication error: ‹rpc error: code = Canceled desc = context canceled›
I210507 13:05:04.266767 11175754 jobs/registry.go:1175 ⋮ [n1] 237667 +(1) candidate pg code: 58C01
I210507 13:05:04.266767 11175754 jobs/registry.go:1175 ⋮ [n1] 237667 +Wraps: (2) attached stack trace
I210507 13:05:04.266767 11175754 jobs/registry.go:1175 ⋮ [n1] 237667 +  -- stack trace:
I210507 13:05:04.266767 11175754 jobs/registry.go:1175 ⋮ [n1] 237667 +  | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.processInboundStreamHelper.func2
I210507 13:05:04.266767 11175754 jobs/registry.go:1175 ⋮ [n1] 237667 +  |   /go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/inbound.go:139
I210507 13:05:04.266767 11175754 jobs/registry.go:1175 ⋮ [n1] 237667 +  | runtime.goexit
I210507 13:05:04.266767 11175754 jobs/registry.go:1175 ⋮ [n1] 237667 +  |   /usr/local/go/src/runtime/asm_amd64.s:1374
I210507 13:05:04.266767 11175754 jobs/registry.go:1175 ⋮ [n1] 237667 +Wraps: (3) secondary error attachment
I210507 13:05:04.266767 11175754 jobs/registry.go:1175 ⋮ [n1] 237667 +  | ‹rpc error: code = Canceled desc = context canceled›
I210507 13:05:04.266767 11175754 jobs/registry.go:1175 ⋮ [n1] 237667 +  | (1) ‹rpc error: code = Canceled desc = context canceled›
I210507 13:05:04.266767 11175754 jobs/registry.go:1175 ⋮ [n1] 237667 +  | Error types: (1) *status.Error
I210507 13:05:04.266767 11175754 jobs/registry.go:1175 ⋮ [n1] 237667 +Wraps: (4) communication error: ‹rpc error: code = Canceled desc = context canceled›
I210507 13:05:04.266767 11175754 jobs/registry.go:1175 ⋮ [n1] 237667 +Error types: (1) *pgerror.withCandidateCode (2) *withstack.withStack (3) *secondary.withSecondaryError (4) *errutil.leafError
```

**Comment by pbardea** [comment]
Hi @dankinder, sorry for the delay in getting back to you! Is the import consistently failing when this setting is set? The cluster setting you mentioned should be totally unrelated to IMPORT's flow and is referring to a different "stream ingestion" than the one in the stack trace you provided. Does changing the cluster setting reliably correlate with the IMPORT failing?

It looks like the IMPORT could be failing due to connection issues between nodes during the IMPORT, which could be likely given the relatively large size of the cluster. So what you could be seeing is https://github.com/cockroachdb/cockroach/issues/50732, which we're working on improving (e.g. https://github.com/cockroachdb/cockroach/pull/60947).

**Comment by dankinder** [comment]
Thanks @pbardea sorry I was out on PTO for quite a while. I have not tried changing `bulkio.stream_ingestion.minimum_flush_interval` back to the default at this point. Before I changed it to `0.1s` I remember it consistently failing.

I could go back and try `5s` again to see if that brings the failures back, but I'm not too eager at this moment since doing this seemed to get me past the issue, and I'm dealing with https://github.com/cockroachdb/cockroach/issues/62799#issuecomment-852255277 still so it's costly to introduce potential job failures right now.

https://github.com/cockroachdb/cockroach/pull/60947 looks super helpful.

**Pull request merged**
