### PR TITLE
workload: support per-table range splits

### PR DESCRIPTION
**Pull request by danhhz**
Plumb this from the `kv` workload to the `workload` cmd.

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/testutils/workload/workload.go, line 95 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21830#-L3oN3Be2budrzlGuOKf:-L3oN3Be2budrzlGuOKg:b9coea6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cdab5fee30ce1fa04bcaa15a40dfd37dabbd4e4/pkg/testutils/workload/workload.go#L95)):*
> ```Go
> 	InitialRowFn func(int) []string
> 	SplitCount   int
> 	SplitFn      func(int) []string
> ```

Can you document the parameter and return value here?

---

*[pkg/testutils/workload/workload.go, line 213 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21830#-L3oLw-nT8D6fJa09cWV:-L3oLw-nT8D6fJa09cWW:b2h39rc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cdab5fee30ce1fa04bcaa15a40dfd37dabbd4e4/pkg/testutils/workload/workload.go#L213)):*
> ```Go
> 	}
> 	// TODO(dan): Sort the split points.
> 	// sort.Sort(stringStringSlice(splitPoints))
> ```

The code below is recursively splitting each range. Not having the split keys in sorted order is mildly problematic as it will slow down the splits. I'm pretty sure I measured this at one point with `kv` and it was significant enough to care about. Should be easy to re-verify with `kv` by disabling the sorting of the split points.

Perhaps `table.SplitFn` should return all of the split points in whatever order the specific workload desires.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21830)*

**Comment by danhhz** [comment]
Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/testutils/workload/workload.go, line 95 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21830#-L3oN3Be2budrzlGuOKf:-L42_3fHqUfKWtIkxvMx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cdab5fee30ce1fa04bcaa15a40dfd37dabbd4e4/pkg/testutils/workload/workload.go#L95)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Can you document the parameter and return value here?
</blockquote></details>

Done.

---

*[pkg/testutils/workload/workload.go, line 213 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21830#-L3oLw-nT8D6fJa09cWV:-L42Y7o8IwRrXEk1S9wc:b6a6fq2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cdab5fee30ce1fa04bcaa15a40dfd37dabbd4e4/pkg/testutils/workload/workload.go#L213)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

The code below is recursively splitting each range. Not having the split keys in sorted order is mildly problematic as it will slow down the splits. I'm pretty sure I measured this at one point with `kv` and it was significant enough to care about. Should be easy to re-verify with `kv` by disabling the sorting of the split points.

Perhaps `table.SplitFn` should return all of the split points in whatever order the specific workload desires.
</blockquote></details>

My intuition was that the splits weren't necessary, expect in byzantine cases. It turns out that's almost right, but the splits/sec has a tendency to stall out without it, so I did the TODO.

Wow was this quite the rabbit hole. Turns out we weren't matching the way kv was doing things and it was slower for some reason. I kept trying to bisect what the difference was, but the iteration cycle is long and I decided other things need to take precedence. This is now much closer to how kv works.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21830)*

**Comment by benesch** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r2, 8 of 8 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/cmd/workload/teamcity-nightlies.go, line 44 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21830#-L431-eiIP_pu5cUXGLS:-L431-eiIP_pu5cUXGLT:b-1wt2ms) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4d5702353b7bc6e986d616ea46faec7d2789a64/pkg/cmd/workload/teamcity-nightlies.go#L44)):*
> ```Go
> 	`kv0`:  `./workload run kv --read-percent=0 --splits=1000 --concurrency=384 --duration=10m`,
> 	`kv95`: `./workload run kv --read-percent=95 --splits=1000 --concurrency=384 --duration=10m`,
> 	// `splits`: `./workload run kv --read-percent=0 --splits=100000 --concurrency=384 --max-ops=1`,
> ```

Intentionally still commented out?

---

*[pkg/sql/scatter.go, line 112 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21830#-L42sIS1o_eufkVBSper:-L42sIS2ByvZJ9YrWXve:b-1tp4q5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9ffce0e3652271330fedf2fbf32026a5c5002e6/pkg/sql/scatter.go#L112)):*
> ```Go
> 		if span.Key.Compare(span.EndKey) > 0 {
> 			span.Key, span.EndKey = span.EndKey, span.Key
> 		}
> ```

optional nit:

```
if c := span.Key.Compare(span.EndKey); c > 0 {
    span.Key, span.EndKey = span.EndKey, span.Key
} else if c == 0 {
  // Key == EndKey is invalid...
   span.EndKey = span.EndKey.Next()
}
```

---

*[pkg/testutils/workload/workload.go, line 108 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21830#-L435_nIkoDjAF7Q8bBm:-L435_nIkoDjAF7Q8bBn:bi29rw7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4d5702353b7bc6e986d616ea46faec7d2789a64/pkg/testutils/workload/workload.go#L108)):*
> ```Go
> 	// of the table's initial splits given its index. They are returned as
> 	// strings and must be pre-escaped for use directly in SQL/CSVs.
> 	SplitFn func(int) []string
> ```

Since you end up invoking `SplitFn` for `1..SplitCount`, seems like you might just have SplitFn return a `[][]string` of the right length. Are you keeping this interface for flexibility down the line?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21830#-:-L435WI38MNGgkOY_ERS:bg7igk9)*

**Comment by danhhz** [comment]
TFTRs!

---

Review status: 1 of 10 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/cmd/workload/teamcity-nightlies.go, line 44 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21830#-L431-eiIP_pu5cUXGLS:-L438IqGG2gvkisiGNFO:b-j6zuel) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4d5702353b7bc6e986d616ea46faec7d2789a64/pkg/cmd/workload/teamcity-nightlies.go#L44)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Intentionally still commented out?
</blockquote></details>

it was in the other one. let's uncomment. yolo

---

*[pkg/sql/scatter.go, line 112 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21830#-L42sIS1o_eufkVBSper:-L438I8t5u7hZxQdHo2v:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9ffce0e3652271330fedf2fbf32026a5c5002e6/pkg/sql/scatter.go#L112)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

optional nit:

```
if c := span.Key.Compare(span.EndKey); c > 0 {
    span.Key, span.EndKey = span.EndKey, span.Key
} else if c == 0 {
  // Key == EndKey is invalid...
   span.EndKey = span.EndKey.Next()
}
```
</blockquote></details>

Done.

---

*[pkg/testutils/workload/workload.go, line 108 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/21830#-L435_nIkoDjAF7Q8bBm:-L438CQKlEkt3tvdqLpA:b1ff8a9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4d5702353b7bc6e986d616ea46faec7d2789a64/pkg/testutils/workload/workload.go#L108)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Since you end up invoking `SplitFn` for `1..SplitCount`, seems like you might just have SplitFn return a `[][]string` of the right length. Are you keeping this interface for flexibility down the line?
</blockquote></details>

Yeah, flexibility and consistency with the other one

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21830#-:-L43E1auOwIPcbLasdL_:bz5mair)*

**Comment by petermattis** [comment]
Review status: 1 of 10 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/testutils/workload/workload.go, line 229 at r5](https://reviewable.io:443/reviews/cockroachdb/cockroach/21830#-L43cnF7rAXHIaMJxyEY:-L43cnF7rAXHIaMJxyEZ:btk9nnw) ([raw file](https://github.com/cockroachdb/cockroach/blob/a22c8272f11993a2a8f530808bce272dc56e7ea6/pkg/testutils/workload/workload.go#L229)):*
> ```Go
> 		splitPoints[splitIdx] = table.SplitFn(splitIdx)
> 	}
> 	sort.Sort(stringStringSlice(splitPoints))
> ```

This is not the same ordering that `kv` uses. `kv` is sorting ints while this is sorting strings containing decimal ints. Consider the split points `3, 20, 100` will be sorted as `"100", "20", "3"`. Not sure if this is a problem or not.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21830)*

**Comment by danhhz** [comment]
Review status: 1 of 10 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/testutils/workload/workload.go, line 229 at r5](https://beta.reviewable.io/reviews/cockroachdb/cockroach/21830#-L43cnF7rAXHIaMJxyEY:-L4I2t-O66JXuPJaw9Uc:b-32fi2f) ([raw file](https://github.com/cockroachdb/cockroach/blob/a22c8272f11993a2a8f530808bce272dc56e7ea6/pkg/testutils/workload/workload.go#L229)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This is not the same ordering that `kv` uses. `kv` is sorting ints while this is sorting strings containing decimal ints. Consider the split points `3, 20, 100` will be sorted as `"100", "20", "3"`. Not sure if this is a problem or not.
</blockquote></details>

This got fixed in https://github.com/cockroachdb/cockroach/pull/22276

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/21830)*

**Pull request merged**
