### PR TITLE
Revert "sql: Add support for timestamp objects with precision"

### PR DESCRIPTION
**Pull request by jordanlewis**
This reverts commit 824ec01e030bf869c509c6907a41c35b8dd57dbc.

Release note (bug fix): revert ability to create second-precision
(0-precision) timestamp datatypes, which inadvertently caused a backward
compatibility issue that automatically made previously-existing
timestamp columns from 19.1 into second-precision columns.

### CODE REVIEW

**Comment by rohany** [comment]
@ericharmeling we'll need to revert this PR -- https://github.com/cockroachdb/docs/pull/5535

**Comment by rohany** [comment]
lgtm

**Comment by lucy-zhang** [comment]
Confirming that this PR does fix the issue (I used the same script for testing as in #42283).

**Pull request merged**
