### PR TITLE
opt: disable optimizations when constructing range lookup expressions

### PR DESCRIPTION
**Pull request by DrewKimball**
This commit disbles optimization rules when constructing the lookup
filters for range lookup joins, as was done for equalities in #81104.
This is necessary because optimization could potentially transform the
filters into non-canonical form, which would cause an error during
execution.

References #80525

Release justification: bug fix for new functionality

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Will this fix #85504? Or is it only applicable to the new code on 22.2 branch?

**Comment by DrewKimball** [comment]
This is only for the new changes in 22.2.

**Review by mgartner — APPROVED** [review]
:lgtm: I guess we don't have a regression test for this because it hasn't caused any known problems yet?

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86793#-:-NAGUPTnCXH6hQWPC4Ih:b-8uooaf)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

**Comment by DrewKimball** [comment]
>I guess we don't have a regression test for this because it hasn't caused any known problems yet?

Yeah. I can try and find a failing test if you think it's important, but I think it's a safe change as-is.

**Comment by mgartner** [comment]
I wouldn't worry about it.

**Comment by DrewKimball** [comment]
TFTRs!

bors r+

**Pull request merged**
