### PR TITLE
storage: disable range key masking for `MVCCGet`

### LINKED ISSUE #86086: storage: perf regression with block filters for range key masking
`MVCCGet` took a pretty bad hit with #85576, but `MVCCScan` seems to be doing better. The former uses a prefix iterator. Something to fix in Pebble, or should we disable range key masking for point lookups?

```
name                                                                   old time/op    new time/op    delta
MVCCScan_Pebble/rows=1/versions=1/valueSize=64/numRangeKeys=0-24         5.61µs ± 1%    5.74µs ± 0%    +2.37%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=1/versions=1/valueSize=64/numRangeKeys=1-24         17.7µs ± 1%    17.9µs ± 1%    +1.03%  (p=0.032 n=5+5)
MVCCScan_Pebble/rows=1/versions=10/valueSize=64/numRangeKeys=0-24        7.73µs ± 1%    7.82µs ± 1%    +1.16%  (p=0.016 n=5+5)
MVCCScan_Pebble/rows=1/versions=10/valueSize=64/numRangeKeys=1-24        47.9µs ± 0%    48.5µs ± 1%    +1.20%  (p=0.016 n=4+5)
MVCCScan_Pebble/rows=100/versions=1/valueSize=64/numRangeKeys=0-24       40.9µs ± 2%    41.6µs ± 1%      ~     (p=0.056 n=5+5)
MVCCScan_Pebble/rows=100/versions=1/valueSize=64/numRangeKeys=1-24       80.5µs ± 1%    81.7µs ± 1%    +1.50%  (p=0.008 n=5+5)
MVCCScan_Pebble/rows=100/versions=10/valueSize=64/numRangeKeys=0-24       125µs ± 1%     124µs ± 1%      ~     (p=0.548 n=5+5)
MVCCScan_Pebble/rows=100/versions=10/valueSize=64/numRangeKeys=1-24       246µs ± 1%     248µs ± 1%      ~     (p=0.151 n=5+5)
MVCCScan_Pebble/rows=10000/versions=1/valueSize=64/numRangeKeys=0-24     2.90ms ± 0%    2.91ms ± 1%      ~     (p=0.222 n=5+5)
MVCCScan_Pebble/rows=10000/versions=1/valueSize=64/numRangeKeys=1-24     5.58ms ± 1%    5.62ms ± 0%    +0.66%  (p=0.016 n=5+5)
MVCCScan_Pebble/rows=10000/versions=10/valueSize=64/numRangeKeys=0-24    10.5ms ± 1%    10.5ms ± 1%      ~     (p=0.841 n=5+5)
MVCCScan_Pebble/rows=10000/versions=10/valueSize=64/numRangeKeys=1-24    18.7ms ± 1%    18.8ms ± 0%      ~     (p=0.095 n=5+5)
MVCCGet_Pebble/batch=true/versions=1/valueSize=8/numRangeKeys=0-24       2.85µs ± 1%    3.62µs ± 1%   +26.98%  (p=0.008 n=5+5)
MVCCGet_Pebble/batch=true/versions=1/valueSize=8/numRangeKeys=1-24       3.62µs ± 1%    8.92µs ± 1%  +146.02%  (p=0.008 n=5+5)
MVCCGet_Pebble/batch=true/versions=10/valueSize=8/numRangeKeys=0-24      4.10µs ± 0%    4.63µs ± 1%   +13.01%  (p=0.008 n=5+5)
MVCCGet_Pebble/batch=true/versions=10/valueSize=8/numRangeKeys=1-24      5.22µs ± 1%   15.04µs ± 1%  +188.01%  (p=0.008 n=5+5)

```

Jira issue: CRDB-18564

Epic CRDB-2624

### PR DESCRIPTION
**Pull request by erikgrinaker**
**storage: fix range key detection in `pebbleMVCCScanner.get()`**

`RangeKeyChanged()` did not appear to fire properly when `MVCCGet` was
changed to disable range key masking and the prefix iterator was reused
from the batch (as seen by `BenchmarkMVCCGet` in the `batch=true` case).

This patch adds a workaround in `pebbleMVCCScanner.get()` that checks
`HasPointAndRange()` after seeking the iterator rather than before.

Release note: None
  
**storage: disable range key masking for `MVCCGet`**

This patch disables range key masking for `MVCCGet`, and disallows using
it with prefix iterators in general, due to the significant performance
overhead.

```
name                                                                   old time/op    new time/op    delta
MVCCGet_Pebble/batch=true/versions=1/valueSize=8/numRangeKeys=0-24       3.31µs ± 1%    2.48µs ± 1%   -24.97%  (p=0.000 n=10+9)
MVCCGet_Pebble/batch=true/versions=1/valueSize=8/numRangeKeys=1-24       6.72µs ± 1%    3.15µs ± 1%   -53.12%  (p=0.000 n=10+10)
MVCCGet_Pebble/batch=true/versions=1/valueSize=8/numRangeKeys=100-24     78.5µs ± 2%    75.1µs ± 2%    -4.41%  (p=0.000 n=10+10)
MVCCGet_Pebble/batch=true/versions=10/valueSize=8/numRangeKeys=0-24      4.19µs ± 2%    3.70µs ± 0%   -11.51%  (p=0.000 n=10+10)
MVCCGet_Pebble/batch=true/versions=10/valueSize=8/numRangeKeys=1-24      9.22µs ± 1%    7.25µs ± 3%   -21.39%  (p=0.000 n=9+10)
MVCCGet_Pebble/batch=true/versions=10/valueSize=8/numRangeKeys=100-24    81.6µs ± 1%    79.0µs ± 1%    -3.22%  (p=0.000 n=10+10)
```

Resolves #86086.

Release note: None

### CODE REVIEW

**Comment by erikgrinaker** [comment]
@jbowens The first commit here is a bit concerning. It appears that `RangeKeyChanged` doesn't trigger when reusing the prefix iterator via a batch and disabling range key masking. To reproduce, apply this PR, revert the first patch, and then run `BenchmarkMVCCGet_Pebble` -- it will fail to detect the range key and enable range key masking, instead failing because it thought it found an invalid intent. I'll write up a test case for this later.

**Comment by erikgrinaker** [comment]
Heading to bed, feel free to bors if green.

**Review by tbg — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86111)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens)

**Comment by tbg** [comment]
bors r=tbg

**Pull request merged**
