### PR TITLE
sqlbase: add sqlliveness table and columns to system.jobs

### PR DESCRIPTION
**Pull request by spaskob**
Touches #47892.

Add `sqlliveness_name` and `slqliveness_epoch` columns in a new column family together
These two values specify the current claim by a job registry on this job row.
The current live claims will live in a new table `system.sqlliveness` along with
an expiration deadline which will need to be extended to keep the claims alive.

Add sql migration code to migrate old definitions to the new one and for the new
system table.

The new job adoption logic is implemented in `claimAndProcessJobs` in
`registry.go`.  It gets a live epoch, potentially steals jobs from other
registries and lays claim on them and finally it processes all claimed
jobs.

The main steps of `claimAndProcessJobs` are implemented in `adopt.go`
and they on purpose circumvent the flawed `update.go` jobs API opting
for direct interaction with the jobs table. I think their implementation
illustrates the simplicity of this approach.

The currently claimed and resumed on the node jobs are kept in a new map
`adoptedJobs` that keeps track of their epoch at the time of the claim
so that they can be easily canceled if the epoch is bumped.

Migration to 20.2 probably needs some more work but is also sketched here:
1. In mixed-version cluster we use the legacy adoption mechanism as
before.
2. Once the cluster is detected to be finalized, the old adoption does
not get triggered any more.
3. The new adoption kicks in, kills all legacy jobs and starts adopting
using the new epoch based mechanism.

Release note: none.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
Yeah, this looks totally like what I had in mind.

One thing I'd love to see in this PR just so that we're darn sure we're happy with this is some code which, in a test, writes into this column family, does some modifications to jobs, using the jobs apis, and makes sure that everything works well. I have no reason to doubt that it will but it just feels like there's no reason not to, you'll need that code anyway and introducing some of the key construction helpers with the new table feels like the right time. Better to have that before we merge a version and migration.

You'll probably need to run some logic tests with rewrite to get the tests to pass. Maybe try:

```
make test PKG=./pkg/sql/logictest TESTS='TestLogic/local$$' TESTFLAGS='--rewrite'
```

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49883#-:-M91FN0m9818Y_AuayN4:b-flu7xa)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @spaskob)

___
*[pkg/sql/sqlbase/system.go, line 174 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49883#-M91FBYU61lNFXf1ru09:-M91FBYV-RypLR8HxLO-:b-fim0nj) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd83249af351224a1ea7dec57ea19d9387a145a7/pkg/sql/sqlbase/system.go#L174)):*
> ```Go
> 	created_by_type   STRING,
> 	created_by_id     INT,
> 	lease							BYTES,
> ```

nit indentation.

**Review by spaskob — COMMENTED** [review]
I added a second commit that tests the new column. Apart from fixing `acceptance/version-upgrade` this is ready for review; in the meanwhile I will fix the roachtest,

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49883#-:-M9Jc-9PBtDbMKl5-g_E:b-pxs0co)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @spaskob)

**Review by ajwerner — COMMENTED** [review]
very close, thanks for writing the test. 

> Reviewed 4 of 4 files at r2, 4 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49883#-:-M9KB_Gy6PPzqjPhh2TN:b-ffro9u)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @spaskob)

___
*[pkg/jobs/registry.go, line 1299 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49883#-M9KAUeDALwPTSZzCGYm:-M9KAUeFD0OSK-CdCol6:b-lgim35) ([raw file](https://github.com/cockroachdb/cockroach/blob/203fdb3e3587541ee91373d79bdc45cdbe4d338b/pkg/jobs/registry.go#L1299)):*
> ```Go
> func (r *Registry) makeJobLeaseKey(jobID int64) roachpb.Key {
> 	const leaseFamilyID = 2
> 	prefix := r.codec.IndexPrefix(keys.JobsTableID, 1)
> ```

This is nitpicky but my feeling is that this shouldn't be a method on the registry but rather should be a function that takes a codec and an ID. It's pure data function of those two arguments. In general in go I prefer unexported functions over methods. There's a lot of room for leeway in the style I'm proposing here. The way I see it structs can either be pure data or they can encapsulate some sort of stateful actor. The registry is much more the latter. When dealing with stateful actors, keeping their method set slim is nice. 
___
*[pkg/jobs/registry.go, line 1305 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49883#-M9KB0SY2xecLM6fGT2C:-M9KB0SY2xecLM6fGT2D:b-etuir3) ([raw file](https://github.com/cockroachdb/cockroach/blob/203fdb3e3587541ee91373d79bdc45cdbe4d338b/pkg/jobs/registry.go#L1305)):*
> ```Go
> }
> 
> // AcquireLease acquires a new lease for the job with given id.
> ```

For now put this method in an `_test.go` file. We don't want to expose lease acquisitions to other users of the `Registry` outside of tests.
___
*[pkg/sql/logictest/testdata/logic_test/partial_index, line 128 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49883#-M9KBME11QEqp60TwWXB:-M9KBME26FEGk1mciXY5:bxs54ep) ([raw file](https://github.com/cockroachdb/cockroach/blob/685194e2b53a89ea0c5191f454708a8772c414f8/pkg/sql/logictest/testdata/logic_test/partial_index#L128)):*
> ```
>     FAMILY "primary" (a, rowid)
> )
> ```

nit: why?

**Review by spaskob — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49883)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/jobs/registry.go, line 1305 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49883#-M9KB0SY2xecLM6fGT2C:-M9KJegZ7eMraPSnxskN:b-5kxzp4) ([raw file](https://github.com/cockroachdb/cockroach/blob/203fdb3e3587541ee91373d79bdc45cdbe4d338b/pkg/jobs/registry.go#L1305)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

For now put this method in an `_test.go` file. We don't want to expose lease acquisitions to other users of the `Registry` outside of tests.
</blockquote></details>

Well the test does not have access to the lease manager field. I understand your worry about this method being used for other purposes but if we added a comment instead this should be very low risk since I am the one mostly likely to touch this file anyway. WDYT?

I am also almost done with a follow up PR that will actually use the new leasing mechanism.gg
___
*[pkg/sql/logictest/testdata/logic_test/partial_index, line 128 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49883#-M9KBME11QEqp60TwWXB:-M9KJJfW7FkF4kYmJTsH:b-tzqtg8) ([raw file](https://github.com/cockroachdb/cockroach/blob/685194e2b53a89ea0c5191f454708a8772c414f8/pkg/sql/logictest/testdata/logic_test/partial_index#L128)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: why?
</blockquote></details>

I don't know -- I used the `rewrite` option and this was auto-generated.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49883)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @spaskob)

___
*[pkg/jobs/registry.go, line 1305 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/49883#-M9KB0SY2xecLM6fGT2C:-M9KMpmXDDMYBj360mwF:bwuxq7w) ([raw file](https://github.com/cockroachdb/cockroach/blob/203fdb3e3587541ee91373d79bdc45cdbe4d338b/pkg/jobs/registry.go#L1305)):*
<details><summary><i>Previously, spaskob (Spas Bojanov) wrote…</i></summary><blockquote>

Well the test does not have access to the lease manager field. I understand your worry about this method being used for other purposes but if we added a comment instead this should be very low risk since I am the one mostly likely to touch this file anyway. WDYT?

I am also almost done with a follow up PR that will actually use the new leasing mechanism.gg

</blockquote></details>

Are you familiar with `helpers_test.go` methods you put there are available in jobs testing packages `package jobs_test`  but not outside of the `jobs` package

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r4, 4 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49883#-:-M9Piln1BIaceOjBKHiF:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Review by ajwerner — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49883)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @spaskob)

___
*[pkg/jobs/registry.go, line 408 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/49883#-MB-gJ2LCDiMr7MDxuuQ:-MB-gJ2LCDiMr7MDxuuR:b-8urwsn) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7a00197d42c0bd68612de6bb56fb724a2f68edc/pkg/jobs/registry.go#L408)):*
> ```Go
> 	}
> 
> 	// TODO(spaskob): get epoch and write job in same txn?
> ```

I think this is critical for correctness. 
___
*[pkg/jobs/registry.go, line 409 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/49883#-MB-gBb7542gPsv8OF1e:-MB-gBb8ANH2MrpJ_EyF:b-71hp72) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7a00197d42c0bd68612de6bb56fb724a2f68edc/pkg/jobs/registry.go#L409)):*
> ```Go
> 
> 	// TODO(spaskob): get epoch and write job in same txn?
> 	// TODO(spaskob): the interval should be a tad longer than the adoption cycle.
> ```

Perhaps it should be some multiple so that you can fail and then try again. 
___
*[pkg/jobs/registry.go, line 414 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/49883#-MB-gR6V7Qmib203kkJm:-MB-gR6V7Qmib203kkJn:bdyu98y) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7a00197d42c0bd68612de6bb56fb724a2f68edc/pkg/jobs/registry.go#L414)):*
> ```Go
> 		return nil, errors.Wrap(err, "error getting live epoch")
> 	}
> 	jobID := r.makeJobID()
> ```

Doesn't the job have to already exist with an ID given the above code where you wrote the lease which already wrote into the jobs table?

Why now do you have to populate all of the fields here? This seems pretty messy to retain all of the logic which updates the jobs table using the `(*Job).update` function and its callers plus also doing it here. 
___
*[pkg/sql/sqlliveness/sqlliveness.go, line 11 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/49883#-MB-gtRU4DmUB65BqD_j:-MB-gtRU4DmUB65BqD_k:b-jkrjif) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7a00197d42c0bd68612de6bb56fb724a2f68edc/pkg/sql/sqlliveness/sqlliveness.go#L11)):*
> ```Go
> // licenses/APL.txt.
> 
> package sqlliveness
> ```

this package sorely needs commentary
___
*[pkg/sql/sqlliveness/sqlliveness.go, line 30 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/49883#-MB-gqsLCUVAJDAgXuHF:-MB-gqsLCUVAJDAgXuHG:b-i6bx) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7a00197d42c0bd68612de6bb56fb724a2f68edc/pkg/sql/sqlliveness/sqlliveness.go#L30)):*
> ```
> // OptionalNodeLivenessI is the interface used in OptionalNodeLiveness.
> type ClaimManager interface {
> ```
nit name mismatch
___
*[pkg/sql/sqlliveness/sqlliveness.go, line 32 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/49883#-MB-gyYL7TQWBQgystAV:-MB-gyYL7TQWBQgystAW:blz0x4w) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7a00197d42c0bd68612de6bb56fb724a2f68edc/pkg/sql/sqlliveness/sqlliveness.go#L32)):*
> ```Go
> // OptionalNodeLivenessI is the interface used in OptionalNodeLiveness.
> type ClaimManager interface {
> 	GetLiveEpoch(context.Context, string, time.Duration) (int64, error)
> ```

My sense is this package needs to be clear about the invariants it provides given proper usage and the expectations around proper usage. It seems to me that `GetLiveEpoch` probably should take a transaction as it's hard to imagine a correct usage where `GetLiveEpoch` is not observed transactionally either when writing a claim or when deleting one.

**Review by ajwerner — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49883)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @spaskob)

___
*[pkg/sql/sqlliveness/sqlliveness.go, line 32 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/49883#-MB-gyYL7TQWBQgystAV:-MB-hLfpDtCBJ8L_6VBI:bulpqbl) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7a00197d42c0bd68612de6bb56fb724a2f68edc/pkg/sql/sqlliveness/sqlliveness.go#L32)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

My sense is this package needs to be clear about the invariants it provides given proper usage and the expectations around proper usage. It seems to me that `GetLiveEpoch` probably should take a transaction as it's hard to imagine a correct usage where `GetLiveEpoch` is not observed transactionally either when writing a claim or when deleting one.
</blockquote></details>

I suppose if one had a proof that a certain epoch is over, then you could delete a previous claim. I think this leaves us with a problem whereby we'll never be allowed to remove an entry from this table unless we know nothing points to it. That's a pretty big burden.

**Pull request closed without merging**
