### PR TITLE
ui: right align stats on node list

### PR DESCRIPTION
**Pull request by vilterp**
Not as good as a bar graph, but still makes it easier to compare quantities.

Before:
image

After:
image

### CODE REVIEW

**Review by BramGruneir — APPROVED** [review]
LGTM, but I didn't know we were adding in specialty styles at this granularity.  Why not add right-alighted-stat to the same style file where sort-table__cell is defined?

Also, might want to right align uptime as well. 

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28545#-:-LJqeth77MGeN2aFNTSj:bdgqy93)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by vilterp** [comment]
Good point. Knew there was a better place for this. Moved it.

bors r+

**Comment by couchand** [comment]
sure, the full text is right-aligned, but only the percentage is truly right-aligned.  kind of frustrating that the values jump around based on the width of the percentages...

**Comment by vilterp** [comment]
Yeah, this was a quick fix which makes it better but not great. Filed #29373 to revisit this with a better solution.

**Pull request merged**
