### PR TITLE
security: allow separate certificate and CA for Admin UI.

### PR DESCRIPTION
**Pull request by mberhault**
Part of #26630

This introduces two new optional certificates:
- `ca-ui.crt`: used by HTTP client to the admin UI to verify the
  server certificates, falls back on `ca.crt` if missing
- `ui.crt`: used by the HTTP server's `tls.Config`, falls back on
  `node.crt` if missing.

Default behavior has changed: the Admin UI `tls.Config` is now separate
from the GRPC/SQL `tls.Config`: it does not ask for client certificates.

This would prevent issues like #18961 (certs being asked in browser)
from occuring in older browsers.

We still do not allow the system pool in our `tls.Config`, we must have
one CA, with `ca.crt` being the fallback when others are missing.
However, the system pool will obviously be used by browsers to verify
the Admin UI certificate, making it possible to use publicly-issued
certificates (eg: using Let's Encrypt is just a matter of symlinking to
the cert and key with the appropriate names and permissions).

Other notes:
- metrics for ui.crt and ca-ui.crt expiration
- list ui.crt and ca-ui.crt on `cockroach list` and certificate report
  page
- no `cockroach cert` commands for UI certs, there's not much point in
  having self-signed UI certificates
- there's basic testing, but we'll need much better coverage for the
  many possible setups. I'll need to find a good way to do tests once we
  allow the system pool

Release note (general change): allow separate certificate and CA for
the Admin UI.

### CODE REVIEW

**Comment by mberhault** [comment]
And I'll just leave this here:
public_ui_certificate

**Comment by mberhault** [comment]
This is all becoming a bit mad. I have basic tests for this, but especially with the upcoming PRs to allow the system pool, I'll need to figure out a better way to test this exhaustively (ie: most/all combinations of certificates)

**Comment by mberhault** [comment]
FYI: I'm intentionally not adding `cert create-ui-ca` and `cert create-ui` commands. There's little point in having a self-signed UI certificate.

**Review by bdarnell — APPROVED** [review]
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27916)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Pull request merged**
