### PR TITLE
server: react to decommissioning nodes by proactively enqueuing their replicas

### LINKED ISSUE #79453: kvserver: proactively enqueue replicas for a decommissioning node
Came up in a conversation with, and proposed by, @lidorcarmel. 

Today, the `replicaScanner` on each store in the [cluster keeps pacing through its replicas](https://github.com/cockroachdb/cockroach/blob/89d5d471bfabe510e9c84d50b33914aca9d7f890/pkg/kv/kvserver/scanner.go#L277-L283) (such that it processes each replica once roughly every 10 mins). The `replicaScanner` keeps optionally queuing these replicas into [each of the store's queues](https://github.com/cockroachdb/cockroach/blob/6f9fadd92b8e6ab6059540df49031c2658dfd7c4/pkg/kv/kvserver/store.go#L713-L723). 

When a node is decommissioning, this status gets broadcast to other nodes in the cluster via gossip. So when the replicateQueue encounters a replica _that is the leaseholder_ for a range that has a [replica on a decommissioning node](https://github.com/cockroachdb/cockroach/blob/6f9fadd92b8e6ab6059540df49031c2658dfd7c4/pkg/kv/kvserver/allocator.go#L739-L746), it decides to take action to move that decommissioning replica away. 

The issue here is that this discovery of decommissioning replicas is limited by the `replicaScanner`s 10 min scanning interval. This means that, generally, even the _discovery_ of all replicas belonging to a decommissioning node will take ~10 mins. Furthermore, if there are any errors [processing any of these decommissioning replicas](https://github.com/cockroachdb/cockroach/issues/79266), they will not be re-processed for another 10 mins. 

This issue proposes that we should actively enqueue all replicas belonging to a decommissioning node, into the `replicateQueue`s of all of a node's stores the moment it learns that a node's liveness record has changed from `LIVE` to `DECOMMISSIONING`. Care will need to be taken to ensure that we're only enqueuing these replicas exactly once when the status of a node changes to `DECOMMISSIONING`. Doing this should considerably cut down on how long it takes to decommission nodes in almost all scenarios, and, anecdotally, it also seems like the behaviour that operators intuitively expect. 

cc @cockroachdb/kv-notifications 

Jira issue: CRDB-14873

Epic: CRDB-14621

### PR DESCRIPTION
**Pull request by aayushshah15**
Note: This patch implements a subset of https://github.com/cockroachdb/cockroach/pull/80836

Previously, when a node was marked `DECOMMISSIONING`, other nodes in the
system would learn about it via gossip but wouldn't do much in the way
of reacting to it. They'd rely on their `replicaScanner` to gradually
run into the decommissioning node's ranges and rely on their
`replicateQueue` to then rebalance them.

This meant that even when decommissioning a mostly empty node, our worst
case lower bound for marking that node fully decommissioned was _one
full scanner interval_ (which is 10 minutes by default).

This patch improves this behavior by installing an idempotent callback
that is invoked every time a node is detected to be `DECOMMISSIONING`.
When it is run, the callback enqueues all the replicas on the local
stores that are on ranges that also have replicas on the decommissioning
node. Note that when nodes in the system restart, they'll re-invoke this callback
for any already `DECOMMISSIONING` node. 

Resolves https://github.com/cockroachdb/cockroach/issues/79453

Release note (performance improvement): Decommissioning should now be
substantially faster, particularly for small to moderately loaded nodes.

### CODE REVIEW

**Review by AlexTalks — COMMENTED** [review]
Thanks for doing this!  This mostly looks good but I would like to take another quick glance tomorrow - will stamp then.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80993#-:-N1HHsis4MdLsOZBR3Lm:bhfzvzw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15, @kvoli, and @nvanbenschoten)

___
*[`pkg/kv/kvserver/store.go` line 3432 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80993#-N1HHH5E8Jfxy3kaazDt:-N1HHH5E8Jfxy3kaazDu:b-s4ieff) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a62c9d66436fb6122c15ced45b38f6ecc44d231/pkg/kv/kvserver/store.go#L3432)):*
> ```Go
> 		// to ensure that these replicas are priority-ordered first.
> 		if skipShouldQueue {
> 			queue.AddAsync(ctx, repl, 1e6 /* prio */)
> ```

Nit: can we make this a constant if we don't have one already?

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80993)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @nvanbenschoten)

___
*[`pkg/kv/kvserver/store.go` line 3432 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80993#-N1HHH5E8Jfxy3kaazDt:-N1KhWjUBcyVm_AOOQ0v:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8a62c9d66436fb6122c15ced45b38f6ecc44d231/pkg/kv/kvserver/store.go#L3432)):*
<details><summary><i>Previously, AlexTalks (Alex Sarkesian) wrote…</i></summary><blockquote>

Nit: can we make this a constant if we don't have one already?
</blockquote></details>

Done.

**Review by kvoli — APPROVED** [review]
Nice, looks good to me! Just one comment on adding obs if it doesn't already exist - perhaps a separate patch.

> Reviewed 15 of 15 files at r1, 6 of 7 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80993#-:-N1a1v3Q3H6M3W6BvM44:b8frbdj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @nvanbenschoten)

___
*[`pkg/server/decommission.go` line 71 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/80993#-N1a08Yq5Y2y6rz_1PiT:-N1a08Yq5Y2y6rz_1PiU:b-id5ahh) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f8dc261e5ac10f0b02c985d6ae92a847105e77/pkg/server/decommission.go#L71)):*
> ```Go
> 						return true /* wantMore */
> 					}
> 					_, processErr, enqueueErr := store.Enqueue(
> ```

It would be nice to also have a metric that tracks the count of replicas that are currently being decommissioned by leaseholders on this store. This could be reported per store and incremented when queued, decremented on success (assuming this doesn't already exist).  onNodeDecomissioned could hard clear the counter if there were remainders.

You could also tag it with the NodeID that is being decommissioned, in the case where there are multiple and it may be necessary to distinguish.

I think a gauge would work here, backed by an atomic counter?

**Review by kvoli — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80993#-:-N1a2FQJ1RSKU6HknZYu:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15 and @nvanbenschoten)

**Review by AlexTalks — APPROVED** [review]
Taking another look a this after today's discussion and everything seems pretty sane to me.  Let me know if you have any benchmarks already, but otherwise I'd like to take a look at benchmarking decommissions without vs. with this patch.
:lgtm: 

> Reviewed 15 of 15 files at r1, 6 of 7 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80993#-:-N2EnDZc3PtYHjmt37cy:b-egjwya)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @aayushshah15 and @nvanbenschoten)

**Comment by aayushshah15** [comment]
>Let me know if you have any benchmarks already

It's similar to the numbers presented in https://github.com/cockroachdb/cockroach/pull/80836 but I ran the numbers again just to confirm:

Without this patch:
```
rp ssh $CS:1 -- "./cockroach node decommission --insecure --self"  0.64s user 0.46s system 0% cpu 12:36.49 total
```

With this patch:
```
rp ssh $CS:1 -- "./cockroach node decommission --insecure --self"  0.26s user 0.23s system 0% cpu 5:35.54 total
```

Repro steps are laid out here: https://github.com/cockroachdb/cockroach/pull/80836#issuecomment-1115164214

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80993)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @AlexTalks, @kvoli, and @nvanbenschoten)

___
*[`pkg/server/decommission.go` line 71 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/80993#-N1a08Yq5Y2y6rz_1PiT:-N2N3RvM6ku0UO3Gzp9b:b6b9v9u) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2f8dc261e5ac10f0b02c985d6ae92a847105e77/pkg/server/decommission.go#L71)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

It would be nice to also have a metric that tracks the count of replicas that are currently being decommissioned by leaseholders on this store. This could be reported per store and incremented when queued, decremented on success (assuming this doesn't already exist).  onNodeDecomissioned could hard clear the counter if there were remainders.

You could also tag it with the NodeID that is being decommissioned, in the case where there are multiple and it may be necessary to distinguish.

I think a gauge would work here, backed by an atomic counter? 


</blockquote></details>

I do think it would be really nice to have store-level metrics for how many ranges they're supposed to rebalance for any given decommissioning node, but I don't think this callback should be the place where we do that. It would be easy for a gauge maintained here to become inaccurate, for at least the following 2 reasons:

1. This callback doesn't "cover all cases" -- i.e. we're not guaranteed to enqueue all ranges that have a replica on the decommissioning node because any of the ranges enqueued here could get split by the time we get around to processing them. Similarly, any ranges enqueued here could get their lease transferred away to a different store by the time this store gets around to processing them. 
2. This callback also only enqueues these replicas async, and doesn't wait for them to be processed. 

We should think about the sort of metrics collection you're referring to inside the `replicateQueue` itself, and I think it deserves its own patch.

What do you think?

**Comment by aayushshah15** [comment]
Merging this to close this out and not affect @AlexTalks' benchmarking + future work.

TFTRs!

bors r+

**Pull request merged**
