### PR TITLE
colexec: enqueue zero batches when finishing partitions in external sort

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: fix testing knob usage in the external sort**

Previously, we incorrectly implemented the "forced merging" testing knob
in the external sort, and this is now fixed.

Release note: None

**colexec: enqueue zero batches when finishing partitions in external sort**

Previously, we forgot to enqueue zero-length batches as the last ones in
each partition in the external sort. That is required by the contract of
the disk queue (used by the partitioned queue) and is now fixed.

Additionally, FDs are now acquired before the first call to Enqueue
(previously it would have been done before the second call).

Release note: None

### CODE REVIEW

**Review by asubiotto — APPROVED** [review]
:lgtm: 
What was the impact of not enqueuing the zero batch?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60296#-:-MTAZEP047GMb-02rZe6:btunt00)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
Enqueueing zero batch somehow exposed a bug with a testing knob implementation, so I added another commit. PTAL.

I think you might know the impact of not enqueueing zero batch better than me since it comes from the `DiskQueue` contract. My guess it's something about flushing the write cache, so possibly some performance hit if the contract is not respected.

**Comment by asubiotto** [comment]
I think it's just a question of when the underlying queue frees up its open resources. It looks like something that made sense when the queue was first written, but has become a little murkier since then since callers manage more resources.

**Review by asubiotto — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60296#-:-MTFWephDwfU5wlJ9eo7:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
