### PR TITLE
rowexec: fix handling of needed cols by zigzag joiner

### PR DESCRIPTION
**Pull request by yuzefovich**
We recently merged a fix so that the ON expr is handled correctly by the
zigzag joiner. However, that commit had a problem: namely, we forgot to
check that a particular IndexedVar is used, so we could include columns
that aren't actually needed (or even in the index) to be decoded. This
is now fixed.

Additionally, I originally thought that we had a similar problem in the
join reader, but everything turned out to be correct there. This commit
refactors the code there a bit to make things more clear (previously,
we were relying on the IndexedVar's ordinal to be 0 when the indexed var
is unused, so that when we shift down the ordinal by a positive number,
we get a negative ordinal, and we wouldn't include the corresponding
column into the "needed cols" set).

Fixes: #71271.

Release note: None (no release with this bug)

### CODE REVIEW

**Review by cucaroach — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71289)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft and @yuzefovich)

___
*[pkg/sql/rowexec/joinerbase.go, line 225 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71289#-MlUvj_P9vr2ymWzX3LK:-MlUvj_P9vr2ymWzX3LL:bnnghbb) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf7c9ebec78ed9b8cb95115e6e033d556c0c4b3e/pkg/sql/rowexec/joinerbase.go#L225)):*
> ```Go
> func (jb *joinerBase) addColumnsNeededByOnExpr(neededCols *util.FastIntSet, startIdx, endIdx int) {
> 	for _, v := range jb.onCond.Vars.GetIndexedVars() {
> 		if v.Used && v.Idx >= startIdx && v.Idx < endIdx {
> ```

What would an example be where Used is false and can we construct/demonstrate that with a test?

**Review by rytaft — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71289)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/rowexec/joinreader.go, line 558 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71289#-MlVJy5n9gVjHQN8R7cY:-MlVJy5n9gVjHQN8R7cZ:bxhst0i) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf7c9ebec78ed9b8cb95115e6e033d556c0c4b3e/pkg/sql/rowexec/joinreader.go#L558)):*
> ```Go
> // neededRightCols returns the set of column indices which need to be fetched
> // from the right side of the join (jr.desc).
> func (jr *joinReader) neededRightCols(numRightTypes int) util.FastIntSet {
> ```

can't you get `numRightTypes` from one of the data members of `joinReader`?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71289)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @rytaft)

___
*[pkg/sql/rowexec/joinerbase.go, line 225 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71289#-MlUvj_P9vr2ymWzX3LK:-MlVyoP-0_Cw-28FUPJc:b-6yokey) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf7c9ebec78ed9b8cb95115e6e033d556c0c4b3e/pkg/sql/rowexec/joinerbase.go#L225)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

What would an example be where Used is false and can we construct/demonstrate that with a test?
</blockquote></details>

The way things work is that we allocate `IndexedVar`s for all columns, and then we process the ON expr to find all columns actually referenced by the expression. The corresponding `IndexedVar`s will be marked as "used" for those referenced columns, everything else remains in the default state (i.e. unused and with `Idx` 0). The fact that `Idx` is zero is what made the join reader code work correctly before this change - we would subtract the column offset (`len(leftTypes)`) and get a negative number which would indicate the "unused" property.

I added a unit test to exercise the newly added method.
___
*[pkg/sql/rowexec/joinreader.go, line 558 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71289#-MlVJy5n9gVjHQN8R7cY:-MlVr6HD8xuqnIneX0LN:b-3ei05i) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf7c9ebec78ed9b8cb95115e6e033d556c0c4b3e/pkg/sql/rowexec/joinreader.go#L558)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

can't you get `numRightTypes` from one of the data members of `joinReader`?
</blockquote></details>

I think it's possible (maybe `jr.colIdxMap.Len()`), but it seems more brittle than explicitly propagating it (and we don't store the column types from the right side directly). So I'd prefer to keep it this way if you don't feel strongly.

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71289#-:-MllGAQk98PattrmCita:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @yuzefovich)

___
*[pkg/sql/rowexec/joinerbase_test.go, line 86 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71289#-MllFr9fBAtdOTOvtiV7:-MllFr9fBAtdOTOvtiV8:be6a7ft) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d512ecd813e42642131fd38c7e9f01dd938306f/pkg/sql/rowexec/joinerbase_test.go#L86)):*
> ```Go
> 			tc.onExpr,
> 			nil,   /* leftEqColumns */
> 			nil,   /* leftEqColumns */
> ```

leftEqColumns -> rightEqColumns
___
*[pkg/sql/rowexec/joinreader.go, line 558 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71289#-MlVJy5n9gVjHQN8R7cY:-MllG6A0AxhYjLyMTMh3:b2ni9b4) ([raw file](https://github.com/cockroachdb/cockroach/blob/cf7c9ebec78ed9b8cb95115e6e033d556c0c4b3e/pkg/sql/rowexec/joinreader.go#L558)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I think it's possible (maybe `jr.colIdxMap.Len()`), but it seems more brittle than explicitly propagating it (and we don't store the column types from the right side directly). So I'd prefer to keep it this way if you don't feel strongly.
</blockquote></details>

ok!

**Review by yuzefovich — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71289#-:-MllKI5zAVsnQI-2D_eG:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @rytaft)

___
*[pkg/sql/rowexec/joinerbase_test.go, line 86 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71289#-MllFr9fBAtdOTOvtiV7:-MllKGlgD_SJGiYO_H8Y:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d512ecd813e42642131fd38c7e9f01dd938306f/pkg/sql/rowexec/joinerbase_test.go#L86)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

leftEqColumns -> rightEqColumns
</blockquote></details>

Done.

**Pull request merged**
