### PR TITLE
engine: pass a struct to NewIterator

### PR DESCRIPTION
**Pull request by tbg**
This is a plumbing-only PR in preparation for adding a second field to
said struct.

See #24543.

Release note: None

### CODE REVIEW

**Comment by tschottdorf** [comment]
@petermattis this is just the plumbing from #24543. I should've landed that separately in the first place.

**Comment by petermattis** [comment]
Review status: 0 of 35 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24730#-L9v2K804PVhgRMZU1r8:-L9v2K804PVhgRMZU1r9:b-q52k7y) (no related file):*
:lgtm: I'm going to trust that this is the same code I reviewed in #24543. Specifically, that you specified `Prefix: true` correctly in all places. Did you automate that work?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24730)*

**Comment by tschottdorf** [comment]
Review status: 0 of 35 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24730#-L9v2K804PVhgRMZU1r8:-L9v5gJW9XI5RmySXMYN:b-lhrmpk) (no related file):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

:lgtm: I'm going to trust that this is the same code I reviewed in #24543. Specifically, that you specified `Prefix: true` correctly in all places. Did you automate that work?
</blockquote></details>

TFTR! I "automated" this with search-replace, but I also did another manual pass when I opened this PR and all looked well :crossed_fingers: 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24730)*

**Pull request merged**
