### PR TITLE
roachtest: remove engine switch roachtest

### PR DESCRIPTION
**Pull request by nicktrav**
The existing roachtest that exercises switching engines is currently
skipped, but is effectively obsolete given that Pebble is the only
engine.

Remove the obsolete roachtest.

Release note: None.

### CODE REVIEW

**Review by srosenberg — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81791#-:-N2tQ5h8-22m_wZ7awmy:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

**Review by srosenberg — COMMENTED** [review]
Thanks for the clean-up!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81791#-:-N2tQ7R19zpvk8VhMVc7:b-6dq80m)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

**Review by jbowens — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81791#-:-N2vOzMIBFO1XnkqT5fR:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @tbg)

**Comment by nicktrav** [comment]
Test failure looks unrelated.

TFTRs!

bors r=srosenberg,jbowens

**Comment by nicktrav** [comment]
bors retry

**Pull request merged**
