### PR TITLE
ppc64le - fix geoindex/TestS2GeometryIndexBasic failure

### PR DESCRIPTION
**Pull request by prashantkhoje**
Related #82456
Release note: None

### CODE REVIEW

**Comment by otan** [comment]
i'm not sure this fix changes the operation; at least, it looks like CI linter thinks not either.

```

=== RUN   TestLint/TestRoachVet
    lint_test.go:91: 
        pkg/geo/geo.go:759:14: unnecessary conversion
        pkg/geo/geo.go:759:37: unnecessary conversion
        pkg/geo/geo.go:760:3: unnecessary conversion
        pkg/geo/geo.go:760:26: unnecessary conversion
        pkg/geo/geo.go:761:3: unnecessary conversion
        pkg/geo/geo.go:761:26: unnecessary conversion
    --- FAIL: TestLint/TestRoachVet (183.11s)
```

(schema change test is a flake)
could you elaborate? thanks!

**Comment by prashantkhoje** [comment]
Platforms like ppc64le and aarch64, use "fused multiply and add" (FMA) instruction that results into rounding differences. The [go specification](https://go.dev/ref/spec#Floating_point_operators) suggests using explicit type conversion to avoid those differences.
Also see https://github.com/disintegration/gift/issues/20#issuecomment-524551797

**Comment by otan** [comment]
you'll probably need to add to this to suppress the linter.
please also add a comment about what you just said
https://github.com/cockroachdb/cockroach/blob/e9ee21860458d997a8155734dc608cfcd050ef24/pkg/testutils/lint/lint_test.go#L2151

**Comment by prashantkhoje** [comment]
If you can point to some document/example to get me started, it'll be helpful.
I'll also explore linter further.

**Review by otan — APPROVED** [review]
bors r+

**Pull request merged**
