### PR TITLE
build: update README on glide, vendor, submodules, etc

### PR DESCRIPTION
**Pull request by dt**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13518)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[build/README.md, line 49 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13518#-KcZK8kZ_Qxu9z1ciw5W:-KcZK8k_bpsifKbO5BmD:bp42q8s) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d8d061e84bfe8dc64e5977918ee576b55b53e7a/build/README.md#L49)):*
> ```Markdown
> 
> Get or update glide with `go get -u github.com/Masterminds/glide`
> - Versions in `brew` or elsehwere are sometimes missing recent fixes.
> ```

elsewhere

also this sentence should start with "Note that", I think.

---

*[build/README.md, line 87 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13518#-KcZKdu0LBt_R8MVrATs:-KcZKdu1N2CfAiUrTBmi:bwofiqo) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d8d061e84bfe8dc64e5977918ee576b55b53e7a/build/README.md#L87)):*
> ```Markdown
> section of `glide.yaml`, run `update`, then restore the pins with their new revisions.
> 
> ### Working with Sub-modules
> ```

s/ub-module/submodule/g

---

*[build/README.md, line 108 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13518#-KcZM6_wrJHu8yJg-IfN:-KcZM6_wrJHu8yJg-IfO:boa7qr) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d8d061e84bfe8dc64e5977918ee576b55b53e7a/build/README.md#L108)):*
> ```Markdown
>   and need wait for it to merge before they will be able to use it in a `cockroachdb/cockroach` PR.
> 
> #### `master` Branch Pointer in Vendor Repo
> ```

Vendored?

---

*[build/README.md, line 114 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13518#-KcZMEJG0AHhVLmX5cG2:-KcZMEJHe1nqtwWFU0EE:b-pkkrml) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d8d061e84bfe8dc64e5977918ee576b55b53e7a/build/README.md#L114)):*
> ```Markdown
> commit that is referenced in `cockroachdb/cockroach` to be garbage collected, so if you opt to
> delete your named branch from `vendored` after your PR merges, you should update the `master` branch
> pointer to ensure your commit is forever reachable.
> ```

i think we should encourage this practice more strongly. avoiding proliferation of branches is good.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13518#-:-KcZMNsJVAMToUy6on-s:bnfp4nl)*

**Comment by dt** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[build/README.md, line 49 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13518#-KcZK8kZ_Qxu9z1ciw5W:-KcZUT7kFKNxdOlNTry5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d8d061e84bfe8dc64e5977918ee576b55b53e7a/build/README.md#L49)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

elsewhere

also this sentence should start with "Note that", I think.
</blockquote></details>

Done.

---

*[build/README.md, line 87 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13518#-KcZKdu0LBt_R8MVrATs:-KcZUYAcqq2BJTjw7e64:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d8d061e84bfe8dc64e5977918ee576b55b53e7a/build/README.md#L87)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

s/ub-module/submodule/g
</blockquote></details>

Done.

---

*[build/README.md, line 108 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13518#-KcZM6_wrJHu8yJg-IfN:-KcZUbJNMAVNDu0SPwgl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d8d061e84bfe8dc64e5977918ee576b55b53e7a/build/README.md#L108)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Vendored?
</blockquote></details>

Done.

---

*[build/README.md, line 114 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13518#-KcZMEJG0AHhVLmX5cG2:-KcZYW8Ukp8ugSRsdP_A:b-896fig) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d8d061e84bfe8dc64e5977918ee576b55b53e7a/build/README.md#L114)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

i think we should encourage this practice more strongly. avoiding proliferation of branches is good.
</blockquote></details>

Done?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13518)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[build/README.md, line 40 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13518#-KcZ_x6APrJsIlMuAfP-:-KcZ_x6BbkY8899J-LkP:b-8nnt89) ([raw file](https://github.com/cockroachdb/cockroach/blob/64fc5f55bc26ec47f6f911f8b95f51b1da242589/build/README.md#L40)):*
> ```Markdown
> 
> A snapshot of CockroachDB's dependencies is maintained at https://github.com/cockroachdb/vendored
> and checked out as a sub-module at `./vendor`.
> ```

submodule

---

*[build/README.md, line 96 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13518#-KcZ_zQnxUEA-u3HZV0A:-KcZ_zQnxUEA-u3HZV0B:b-8nnt89) ([raw file](https://github.com/cockroachdb/cockroach/blob/64fc5f55bc26ec47f6f911f8b95f51b1da242589/build/README.md#L96)):*
> ```Markdown
> 
> - After using glide as described above to add or update dependencies and making related code changes,
> `git status` in `cockroachdb/cockroach` checkout will report that the `vendor` sub-module has
> ```

submodule

---

*[build/README.md, line 131 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13518#-KcZa-dnSWMLdVhMDe55:-KcZa-dnSWMLdVhMDe56:bsjkst8) ([raw file](https://github.com/cockroachdb/cockroach/blob/64fc5f55bc26ec47f6f911f8b95f51b1da242589/build/README.md#L131)):*
> ```Markdown
> 
> We only want the vendor directory used by builds when it is explicitly checked out *and managed* as a
> sub-module at `./vendor`.
> ```

submodule (and other instances in this doc while you're here)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13518)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[build/README.md, line 40 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13518#-KcZ_x6APrJsIlMuAfP-:-KcZekyldOg2Pa7I2uEH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/64fc5f55bc26ec47f6f911f8b95f51b1da242589/build/README.md#L40)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

submodule
</blockquote></details>

Done.

---

*[build/README.md, line 96 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13518#-KcZ_zQnxUEA-u3HZV0A:-KcZemJrOq9C4V2PDUIj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/64fc5f55bc26ec47f6f911f8b95f51b1da242589/build/README.md#L96)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

submodule
</blockquote></details>

Done.

---

*[build/README.md, line 131 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13518#-KcZa-dnSWMLdVhMDe55:-KcZengIfA02LawrI3L5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/64fc5f55bc26ec47f6f911f8b95f51b1da242589/build/README.md#L131)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

submodule (and other instances in this doc while you're here)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13518)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13518)*

**Comment by dt** [comment]
TFTR!

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13518#-:-KcZfW6m3uOhRkOLGEom:b-814g8k)*

**Pull request merged**
