### PR TITLE
build: refactor the Jepsen test scripts

### PR DESCRIPTION
**Pull request by knz**
Needed to investigate #14171.

### CODE REVIEW

**Comment by tschottdorf** [comment]
idea (ignore if you think it's silly): we could file an issue as #easy #helpwanted to refactor that into a Go script. Only problem is that the person doing that would probably have to be able to run the scripts in the first place...

**Comment by knz** [comment]
Yeah so "help wanted internally" :)

**Comment by knz** [comment]
Ok, this is ready to review.
Note this is just a refactoring, I left all the test settings as-is. We'll follow-up with fixes/improvements in different PRs to address the issues outlined in  #15738.

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[build/jepsen-common.sh, line 31 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15717#-KjdmxSRiNx_HsfP5wRU:-KjdmxSSJiueKdeXIrJN:b-9go7bj) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e4723a05f73539938e3ee87a4dc5ca3b137747e/build/jepsen-common.sh#L31)):*
> ```Shell
>     printf "##%s[test%s name='Jepsen%s']\\n" teamcity "$1" "$2"
>     case $1 in
> 	Started) currentTestName=$2 ;;
> ```

Looks like you're mixing tabs and spaces here (and in several other of the new files)

---

*[build/teamcity-jepsen-run-one.sh, line 20 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15717#-Kjdne0XZCD-oIDo42-v:-Kjdne0XZCD-oIDo42-w:b-cqaat6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e4723a05f73539938e3ee87a4dc5ca3b137747e/build/teamcity-jepsen-run-one.sh#L20)):*
> ```Shell
> 
> # Prepare the command to run the test.
> # We use "dd" as a poor man's progress bar.
> ```

I don't see this use of `dd` anywhere. 

---

*[build/teamcity-jepsen-run-one.sh, line 45 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15717#-Kjdo0nuPiE_JxxH18wU:-Kjdo0nuPiE_JxxH18wV:bxawv5m) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e4723a05f73539938e3ee87a4dc5ca3b137747e/build/teamcity-jepsen-run-one.sh#L45)):*
> ```Shell
> ';
> 	   # The following loop displays a TC message every 10 seconds
> 	   # with an exceirpt from the jepsen log.
> ```

s/exceirpt/excerpt/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15717#-:-KjdotcTnRjP8kzrf-J0:bnfp4nl)*

**Comment by knz** [comment]
TFYR

---

Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[build/jepsen-common.sh, line 31 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15717#-KjdmxSRiNx_HsfP5wRU:-Kjx3Zyk2sRekVcb_QnW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e4723a05f73539938e3ee87a4dc5ca3b137747e/build/jepsen-common.sh#L31)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Looks like you're mixing tabs and spaces here (and in several other of the new files)
</blockquote></details>

Done.

---

*[build/teamcity-jepsen-run-one.sh, line 20 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15717#-Kjdne0XZCD-oIDo42-v:-Kjx3jt78pSRnbsTGGWJ:b-7loeh9) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e4723a05f73539938e3ee87a4dc5ca3b137747e/build/teamcity-jepsen-run-one.sh#L20)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I don't see this use of `dd` anywhere. 
</blockquote></details>

Stale comment. Removed.

---

*[build/teamcity-jepsen-run-one.sh, line 45 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15717#-Kjdo0nuPiE_JxxH18wU:-Kjx3mE5Qmw2jDGSi7yW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e4723a05f73539938e3ee87a4dc5ca3b137747e/build/teamcity-jepsen-run-one.sh#L45)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

s/exceirpt/excerpt/
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15717#-:-Kjx41BjcbpojweahO0Z:bb73zww)*

**Comment by jordanlewis** [comment]
:lgtm: thanks! this is nice.

---

Reviewed 4 of 7 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15717#-:-Kjx8l7auJhTO9VR4rCX:b-8k2kxm)*

**Pull request merged**
