### PR TITLE
opt: rename logic test configs

### PR DESCRIPTION
**Pull request by RaduBerinde**
The logic test config names are misleading: `default` means distsql=off, which is not the default; also, distsql configs have the fake resolver and others don't).

Just a proposal for now - I will go through and update the testfiles once we settle on the names.

I am also considering renaming from `xx-opt` to `opt-xx` since using the optimizer or not seems like a bigger difference than local vs dist.

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
works for me. thanks!

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26131#-:-LDSQoJY4QhGQQfpcgaP:b4eci38)*

**Comment by andy-kimball** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26131#-:-LDcjWN5AxuSly_81p6c:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Ok, I renamed the configs in all the test files and in the nightly bigtest runs. I hope I haven't missed something.

I also set the `-disk` configs to be skipped when the short flag is passed.

**Comment by andy-kimball** [comment]
Looks fine.

---

Review status: 0 of 239 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26131#-:-LEFv-L41qfE1GWfFBj9:b-vspczh)*

**Pull request merged**
