### PR TITLE
colexec: make sure that parallel unordered sync closes everything

### LINKED ISSUE #64248: colflow: unexpectedly not all closers were closed before Flow.Cleanup
Extracted from #60824.

sql/logictest.TestLogic [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2925863&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=2925863&tab=artifacts#/) on master @ [05880958efb6fda9ab80ed16495d98922de3fbf6](https://github.com/cockroachdb/cockroach/commits/05880958efb6fda9ab80ed16495d98922de3fbf6):

Fatal error:

```
panic: expected 2 components to be closed, but found that only 0 were

```
Stack: 

```
goroutine 9453985 [running]:
github.com/cockroachdb/cockroach/pkg/sql/colexecerror.InternalError(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:192
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Cleanup(0xc146920aa0, 0x51d5e40, 0xc037fcf240)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:285 +0x505
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run.func8()
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:373 +0x82
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc0c811c600, 0x51f4140, 0xc05fff0318, 0xc0c811cae0, 0x3, 0x5243ee0, 0xc08e468c00, 0xc109496401, 0xc0b0f19078, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1055 +0x4cc
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc0c811c600, 0x51f4140, 0xc05fff0318, 0xc0c811cae0, 0x5243ee0, 0xc08e468c00, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:915 +0x75b
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc0c811c600, 0x51f4140, 0xc05fff0318, 0x5200700, 0xc02c975f90, 0xc0979d1bc0, 0x3c, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:659 +0xf86
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc0c811c600, 0x51d5e40, 0xc0ce4d52c0, 0x5200700, 0xc02c975f90, 0xc0979d1bc0, 0x3c, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:122 +0xb14
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1(0x5200700, 0xc02c975f90, 0xc0979d1bc0, 0x3c, 0x0, 0x0, 0xad5db37, 0xed8193acf, 0x0, 0xad5db37, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1527 +0x225
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc0c811c600, 0x51d5e40, 0xc0ce4d52c0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1529 +0x1457
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc0c811c600, 0x51d5f00, 0xc08e468870, 0xc081bf7e00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1450 +0x228
github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).initConnEx.func1(0xc0c811c600, 0x51d5f00, 0xc08e468870, 0xc0b0f18960, 0xc08e4689c0, 0x5188200, 0xc0ce4d5140, 0xc02ad0a630, 0xc17f462d20)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:202 +0x65
created by github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).initConnEx
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:201 +0x2f2
```
<details><summary>Log preceding fatal error</summary>
<p>

```
=== RUN   TestLogic/fakedist-disk/serial/serial_virtual_sequence
E210426 22:50:55.106794 9444974 jobs/adopt.go:260  [n1] 954  job 653417037656260609: adoption completed with error failed to ingest index entries during backfill: duplicate key value violates unique constraint "bar"
```
</p>
</details>
<details><summary>Reproduce</summary>
<p>
<p>To reproduce, try:

```bash
make stressrace TESTS=TestLogic PKG=./pkg/sql/logictest TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```
</p>
<p>Parameters in this failure:

- GOFLAGS=-json
</p>
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #63262 sql/logictest: TestLogic failed [C-test-failure O-robot branch-release-20.2]
- #61657 sql/logictest: TestLogic failed [C-test-failure O-robot branch-release-21.1]
- #58269 sql/logictest: TestLogic failed [C-test-failure O-robot branch-release-20.1]
</p>
</details>
/cc @jordanlewis
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestLogic.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: make sure that parallel unordered sync closes everything**

Previously, it was possible for the parallel unordered synchronizer to
not close some of the `Closer`s from its input trees. Namely, if `Next`
or `DrainMeta` is never called on the synchronizer, the input goroutines
are never spawned up, so no components actually get closed. This could
be problematic when the synchronizer was `Init`ialized but then never
used. This is now fixed by making the parallel unordered synchronizer
implements `Closer` interface and handle this scenario gracefully.

I can't think of any "happy" scenarios when such situation would arise,
but one possibility is when the synchronizer was able to initialize some
of its inputs (which started using resources and, thus, need to be
closed), but then encountered a panic upon initialization another input.
From the perspective of the consumer of the synchronizer, the
initialization wasn't successful, so it won't try to call `Next` or
`DrainMeta`.

The issue has been present for a couple of releases now. The impact of
not properly closing some components is that temp disk resources might
not be released (like files not closed) or tracing spans not finished.
I'm a bit on the fence about backporting this change.

Fixes: #64248.

Release note: None

**colflow: use crdb_test build tag to enable a testing assertion**

Previously, we had a custom testing knob that would enable a testing
assertion that all `Closer`s are actually closed when the vectorized
flow is cleaned up. The knob was only set in the logic tests. This
commit switches the assertion to be checked whenever `crdb_test` build
tag is used (which is a superset of the logic tests) giving us better
coverage.

Release note: None

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
> Coming up with a regression test for this is pretty hard, so none is added. 

Is it possible to inject a panic as part of a fake initialization?

> Reviewed 2 of 2 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64340#-:-MZV0sY80C2eukQWZbme:b-bt1cw2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/parallel_unordered_synchronizer.go, line 428 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64340#-MZV-v_wCAfPSEp3Sy6U:-MZV-v_wCAfPSEp3Sy6V:busi75g) ([raw file](https://github.com/cockroachdb/cockroach/blob/778adcfdb7cd5b9b97aabdeca3a2e25725bdd6a2/pkg/sql/colexec/parallel_unordered_synchronizer.go#L428)):*
> ```Go
> 	}
> 	// If the synchronizer is in "uninitialized" state, it means that the
> 	// goroutines for each input haven't been started, so they won't be able to
> ```

is it possible that some have been started but not others? Is it safe to close them anyway here?

**Review by yuzefovich — COMMENTED** [review]
> Is it possible to inject a panic as part of a fake initialization?

Good point, I guess I was being lazy, added.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64340#-:-MZYpV5Y9lT0sQjAZZu-:b-ganw60)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/colexec/parallel_unordered_synchronizer.go, line 428 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64340#-MZV-v_wCAfPSEp3Sy6U:-MZYnBvO7IZPhwEM_XSJ:b-ot8q8v) ([raw file](https://github.com/cockroachdb/cockroach/blob/778adcfdb7cd5b9b97aabdeca3a2e25725bdd6a2/pkg/sql/colexec/parallel_unordered_synchronizer.go#L428)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

is it possible that some have been started but not others? Is it safe to close them anyway here?
</blockquote></details>

Yeah, currently it's always safe to close things. Added a comment and a TODO.

**Review by rytaft — APPROVED** [review]
:lgtm: Very nice!

> Reviewed 7 of 7 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64340#-:-MZZDFHF835kOhTDoeRx:b-kerl87)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexecop/testutils.go, line 155 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64340#-MZZD-7nB6CFkb0iOsiV:-MZZD-7nB6CFkb0iOsiW:bf5cqla) ([raw file](https://github.com/cockroachdb/cockroach/blob/ff029a896601d519d0afe606d7f08ede94ca18c8/pkg/sql/colexecop/testutils.go#L155)):*
> ```Go
> 	if o.InitCb == nil {
> 		return
> ```

nit: extra line

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64340#-:-MZZjR503yL_8Wa6IHeC:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

**Pull request merged**
