### PR TITLE
gossip: fix race during shutdown

### LINKED ISSUE #8905: gossip: data race in TestClientGossip
Appears to have been introduced by dc05dffaa8d83745559f9e70e84fd722367e5ae4.

CI didn't auto-file an issue because it only does so on `master`.

https://circleci.com/gh/cockroachdb/cockroach/21936

### PR DESCRIPTION
**Pull request by RaduBerinde**
Reproduced and verified with:

```
make stressrace PKG=./gossip TESTS=TestClientGossip TESTFLAGS='--verbosity 2'
```

Fixes #8905.

CC @tamird @tschottdorf 
I am not sure about this pattern (with the `retErr`).. Should Stopper have a `RunTask` version that takes a `func() error`?

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8910)

### CODE REVIEW

**Comment by tamird** [comment]
This fix seems like a bit of a band-aid. We now have things inside the context that are quite likely to race with shutdown - perhaps the solution is to include the stopper when embedding the event log in the context?

**Comment by RaduBerinde** [comment]
This is a loop that is supposed to end when the stopper stops (we are listening on ShouldQuiesce). In general shouldn't the stopper be aware of these loops (and wait for them)? If it doesn't, couldn't the goroutine leak checker complain (at least in theory)?

Can you expand a bit on your proposal? Would we use stopper.RunTask somewhere inside `log.Event`?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8910#-:-KQMr4bNEbFDWkVW5f1I:bgmtiov)*

**Comment by tamird** [comment]
> This is a loop that is supposed to end when the stopper stops (we are listening on ShouldQuiesce). In general shouldn't the stopper be aware of these loops (and wait for them)? If it doesn't, couldn't the goroutine leak checker complain (at least in theory)?

Maybe, but in that case the way this is written is not right - the loop should be in another `RunWorker` which communicates with the outer using a channel (instead of `retErr`). Currently, the blocking part is in RunTask, which holds things up more than necessary.

> Can you expand a bit on your proposal? Would we use stopper.RunTask somewhere inside log.Event?

Yeah, exactly - instead of passing a `trace.EventLog` to `log.WithEventLog`, you'd pass a struct which contains a stopper and an EventLog.

**Comment by RaduBerinde** [comment]
I think `RunTask` may be too heavyweight to run on every event, but I can achieve the same with just a mutex. Assuming I do that, should I leave this code as-is? (the fact that we're doing just the 'RunWorker' inside a task seems dubious  to me).

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8910#-:-KQN15UFNsB37kpu26Oz:b-qmem9i)*

**Comment by tamird** [comment]
> Assuming I do that, should I leave this code as-is? (the fact that we're doing just the 'RunWorker' inside a task seems dubious to me).

Something of a judgement call. I wouldn't be opposed to adding a second RunWorker to encapsulate the loop.

**Comment by RaduBerinde** [comment]
PR #8913

**Pull request closed without merging**
