### PR TITLE
schemachanger: enable ALTER COLUMN DROP DEFAULT 

### LINKED ISSUE #118250: schemachanger: ALTER TABLE x ALTER COLUMN y DROP DEFAULT
Support `ALTER TABLE x ALTER COLUMN y DROP DEFAULT` in the declarative schema changer.

Jira issue: CRDB-35640

Epic CRDB-31283

### PR DESCRIPTION
**Pull request by annrpom**
### This PR is stacked on top of another one!

Please consider reviewing that PR first. This message will be removed once the prerequisite PR is merged and this one is rebased.

* 248375eef0efc6a8f3723249600271ae6bca6a7e is from #116697
* 9b1e9bebea8ae15dd30c6fe105612b7db895bce9 is from #116697

---

This patch enables ALTER TABLE ... ALTER COLUMN ...
DROP DEFAULT in the declarative schema changer.

Fixes: https://github.com/cockroachdb/cockroach/issues/118250
Epic: [CRDB-31283](https://cockroachlabs.atlassian.net/browse/CRDB-31283)

Release note: None

### CODE REVIEW

**Comment by annrpom** [comment]
Most work is done in SET DEFAULT PR since SET DEFAULT NULL should behave the same way as DROP DEFAULT. I'll rewrite tests after that PR Is in a good shape so I don't have to rewrite multiple times

**Review by fqazi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 127 of 127 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118900)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @annrpom)

___
*[`pkg/sql/schemachanger/testdata/end_to_end/alter_table_alter_column_drop_default/alter_table_alter_column_drop_default.explain` line 6 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/118900#-NrGZCvZ00etf4vYAz3n:-NrGZCvZ00etf4vYAz3o:b-6nidc8) ([raw file](https://github.com/cockroachdb/cockroach/blob/2eb55844626bba215dcd05649961150c3b804c19/pkg/sql/schemachanger/testdata/end_to_end/alter_table_alter_column_drop_default/alter_table_alter_column_drop_default.explain#L6)):*
> ```
> 
> /* test */
> EXPLAIN (DDL) ALTER TABLE t ALTER COLUMN j SET DEFAULT 4;
> ```

Shouldn't be NULL?

**Comment by annrpom** [comment]
> Shouldn't be NULL?

oops - It should be DROP DEFAULT; thanks for catching

**Review by fqazi — APPROVED** [review]
:lgtm:

Before merging lets add one more test where we ADD and DROP in a single transaction to make sure everything is concrete. It should just work.

> Reviewed 8 of 8 files at r4, 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118900#-:-NrGcL5-9Zsfls8Z2zvO:bom5mcm)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @annrpom)

**Comment by annrpom** [comment]
> Before merging lets add one more test where we ADD and DROP in a single transaction to make sure everything is concrete. It should just work.


Done - works like magic 🪄.
TFTR! ('-')7
bors r=fqazi

**Pull request merged**
