### PR TITLE
sql: lease acquisition of OFFLINE descs may starve bulk operations

### LINKED ISSUE #61798: sql/catalog/lease: high priority reads in lease acquisition of OFFLINE descs may starve bulk operations
**Describe the problem**

In (#46170, #46384) we made changes to use high priority read transaction in lease acquisitions in order to break deadlocks. This solution isn't wonderful: if users use `PRIORITY HIGH` on their DDL transactions, they can still hit these deadlocks. Given people tend not to do that, this proved to be a pretty good and pragmatic solution to a very serious problem. 

When code attempts to resolve descriptors it goes through the leasing mechanism. This is true even if the descriptor does not exist. This is made much worse in a case where you've got a multi-region cluster.

The scenario that causes specific pain is when you've got an application running and trying to hit some tables but you're in the process of restoring those tables. As part of the restore, we need to update the descriptors. If the restore job is far from the descriptor table leaseholder, then there's a long period of time for interceding queries to push the intent. After getting pushed, the query will need to refresh. If the pushing is happening more frequently than the refresh's duration, we'll get stuck in livelock. 

For what it's worth, all of this is modestly speculative. We saw the pushing but I don't know that we've captured enough data.

**To Reproduce**

In theory, start a restore in a global cluster and get the leaseholder on the system config span in a different region than the restore coordinator. Then spam the database being restored and see if you can hold off the restore.

**Some ideas**

* We could lease and cache the offline descriptor. This is probably the most compelling choice. It's not too hard. 
* We could make the lease acquisition low priority and fall back to reading from the store (probably not a good idea).
* We could get rid of the high priority hack altogether with some work involving child transactions (see #54633).

**Expected behavior**

The restore finishes.

### PR DESCRIPTION
**Pull request by fqazi**
Fixes: #61798

Previously, offline descriptors would never have their leases
cached and they would be released once the reference count hit zero.
This was inadequate because when attempting to online these tables
again the lease acquisition could be pushed back by other operations,
leading to starvation / live locks. To address this, this patch will
allow the leases of offline descriptors to be cached.

Release note (bug fix): Lease acquisitions of descriptor in a
offline state may starve out bulk operations (backup / restore)

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62959#-:-MXCwGWtAMP3tEa6pe7L:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @fqazi and @pbardea)

___
*[pkg/sql/catalog/lease/lease.go, line 1418 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62959#-MXCw1fXASqrir3Y66vA:-MXCw1fXASqrir3Y66vB:b-dnujjh) ([raw file](https://github.com/cockroachdb/cockroach/blob/12fd474d1cb5f296a1263d4a0d3985a5afb2db2b/pkg/sql/catalog/lease/lease.go#L1418)):*
> ```
> 				err2 := m.Release(desc)
> 				if err2 != nil {
> ```
nit: I'd prefere `releaseErr` to `err2`

**Comment by fqazi** [comment]
bors r=ajwerner

**Comment by fqazi** [comment]
bors r=ajwerner

**Comment by knz** [comment]
this one may need a backport on the 21.1 branch as well

**Comment by mikeCRL** [comment]
I further summarized the release note text. Can anyone please +1 or edit this? @ajwerner @fqazi

> Allow the leases of offline descriptors to be cached, preventing issues with lease acquisitions during bulk operations (backup and restore operations). [#63558][#63558]

**Pull request merged**
