### PR TITLE
roachprod: upgrade AWS VM

### PR DESCRIPTION
**Pull request by RaduBerinde**
Upgrading the VM image for AWS roachprod VMs from ubuntu 16.04 to
20.04. This fixes problems recently introduced in the start command.

Steps, recorded here in case someone in the future wants to do the
same and looks at git history:
  1. Found a new image using the AWS web console, under AMIs.
  2. Modified the image_name in `vm/aws/terraform/aws-region/main.tf`.
  3. Installed terraform 0.11; `inside vm/aws/terraform` I ran:
    - `terraform init`
    - `terraform apply`
    - `terraform output --json > ../config.json`
  4. Regenerated `embedded.go` using `make generate PKG=./pkg/cmd/roachprod/...`

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Thanks @ajwerner for holding my hand through this 😂

**Review by ajwerner — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64436#-:-MZUo1nz7OyHUsRVc0LC:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

**Review by andreimatei — COMMENTED** [review]
:lgtm: :dog: 
thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64436#-:-MZUsPDy9plDfJ1Vqfeo:b-8kmr0b)* status: :shipit: complete! 2 of 0 LGTMs obtained

**Pull request merged**
