### PR TITLE
sql: ensure that pgwire is informed of EXPLAIN's result columns.

### LINKED ISSUE #14238: sql: node crash with explain
The node serving the request crashed if I try to explain a query on beta-20170309
```sql
CREATE TABLE Test (ID serial PRIMARY KEY, Date TimeStampTZ,INDEX date_idx (Date));
insert into Test (Date) values ('2017-03-17 15:33:00'::timestamptz);

explain select * from Test where Date >='2017-01-01 00:00:00'::TimeStamp;
```

The node will crash and in the log, I see
```
panic: runtime error: index out of range [recovered]
        panic: runtime error: index out of range [recovered]
        panic: runtime error: index out of range

goroutine 26996 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc4203634a0)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:198 +0x6e
panic(0x1ab98e0, 0x2878ec0)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve.func1(0xc42209c200, 0x7f614d43acc0, 0xc4398842a0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:340 +0x74
panic(0x1ab98e0, 0x2878ec0)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).sendResponse(0xc42209c200, 0x7f614d43acc0, 0xc4398842a0, 0xc421790aa0, 0x1, 0x1, 0x2dd4cd8, 0x0, 0x0, 0xc4348a3600, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:961 +0x497
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).executeStatements(0xc42209c200, 0x7f614d43acc0, 0xc4398842a0, 0xc4348a364d, 0x48, 0xc42683b518, 0x2dd4cd8, 0x0, 0x0, 0x1acd900, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:828 +0x202
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleExecute(0xc42209c200, 0x7f614d43acc0, 0xc4398842a0, 0xc42209c228, 0x9, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:805 +0x19d
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc42209c200, 0x7f614d43acc0, 0xc4398842a0, 0xc429460620, 0x5400, 0xc4202e0160, 0x7f614d43ada0, 0xc42942d300, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:442 +0xa7b
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc4202e0000, 0x7f614d43ada0, 0xc42942d300, 0x28bed80, 0xc4261a2140, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:415 +0x917
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func8.1(0x28bed80, 0xc4261a2140)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:544 +0x106
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc4203634a0, 0xc42000e040, 0x28bed80, 0xc4261a2140, 0xc421194240)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:136 +0x95
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
        /go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:138 +0x239
```

### PR DESCRIPTION
**Pull request by knz**
Fixes #14238.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14244)

### CODE REVIEW

**Comment by jordanlewis** [comment]
:lgtm: mod some minor comment typos

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/plan.go, line 369 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14244#-KfTCfx0mf63GBVc2s8h:-KfTCfx0mf63GBVc2s8i:b-l6our9) ([raw file](https://github.com/cockroachdb/cockroach/blob/aea35e839a21b636b1a3c4213f2164c752108a99/pkg/sql/plan.go#L369)):*
> ```Go
> 
> // prepare constructs the logical plan for the statement.  This is
> // needed both to type placeholders and inform pgwire of the types of
> ```

s/and inform/and to inform/ in order to preserve the analogous clauses - "needed both to x and to y"

---

*[pkg/sql/plan.go, line 371 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14244#-KfTCdz0gQSluoyg4x0B:-KfTCdz0gQSluoyg4x0C:b54ndgl) ([raw file](https://github.com/cockroachdb/cockroach/blob/aea35e839a21b636b1a3c4213f2164c752108a99/pkg/sql/plan.go#L371)):*
> ```Go
> // needed both to type placeholders and inform pgwire of the types of
> // the result columns. All statements that support either placeholders
> // of have result columns must be handled here.
> ```

s/of/or/? also probably should say 'that either support placeholders or have result columns', not 'that support either placeholders or have result columns'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14244#-:-KfTD47yzVU0OTyedtGG:b-w9ci1o)*

**Comment by knz** [comment]
TFYR

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/plan.go, line 369 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14244#-KfTCfx0mf63GBVc2s8h:-KfTDqJOdH3zSNTJ3B5M:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aea35e839a21b636b1a3c4213f2164c752108a99/pkg/sql/plan.go#L369)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

s/and inform/and to inform/ in order to preserve the analogous clauses - "needed both to x and to y"
</blockquote></details>

Done.

---

*[pkg/sql/plan.go, line 371 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14244#-KfTCdz0gQSluoyg4x0B:-KfTDqcJqbRJD_1P6LpU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/aea35e839a21b636b1a3c4213f2164c752108a99/pkg/sql/plan.go#L371)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

s/of/or/? also probably should say 'that either support placeholders or have result columns', not 'that support either placeholders or have result columns'
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14244#-:-KfTE2at0Fa64mlW8Rty:bb73zww)*

**Comment by jordanlewis** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14244#-:-KfTHSMKIXzDuV7HFcHC:bnfp4nl)*

**Comment by mjibson** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14244#-:-KfTL6ssgcpIlhuJLsZO:bnfp4nl)*

**Comment by knz** [comment]
TFYRs!

**Pull request merged**
