### PR TITLE
storage/engine: RocksDB clear range hack

### PR DESCRIPTION
**Pull request by petermattis**
Whenever we perform a ClearRange operation, also Clear the first key and
"last" key covered by the range tombstone. This allows the RocksDB
compaction code to generate better boundaries for sstables containing
range tombstones and avoids generating sstables which cover an
excessively large portion of the key space.

See #24029

Release note: None

### CODE REVIEW

**Comment by benesch** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[pkg/storage/engine/rocksdb.go, line 2438 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26576#-LEgLd0J5B3PF8pzGiP0:-LEgLd0J5B3PF8pzGiP1:bsrm66v) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b83c29adf4d939d8623c4cfbeb04712d0c10504/pkg/storage/engine/rocksdb.go#L2438)):*
> ```Go
> 	}
> 	if start.Key.Compare(prev) < 0 {
> 		if err := dbClear(rdb, MVCCKey{Key: prev}); err != nil {
> ```

Meta-question: is this raw creation of an `MVCCKey` preferred to `MakeMVCCMetadataKey`? If so I would like to someday delete that function on the grounds that it is an unnecessary level of indirection.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26576#-:-LEgMSqu5joa_gil1Pmm:bnfp4nl)*

**Comment by petermattis** [comment]
@bdarnell and @tschottdorf How do you feel about merging this change? It clearly works around a problem in RockDB, yet we're not seeing a benefit on the `clearrange` roachtest. It is possible there is yet another problem that `clearrange` is hitting. 

---

Review status: :shipit: complete! 1 of 0 LGTMs obtained

---

*[pkg/storage/engine/rocksdb.go, line 2438 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26576#-LEgLd0J5B3PF8pzGiP0:-LEj1lNW62cIQKznxIDr:bqhd61l) ([raw file](https://github.com/cockroachdb/cockroach/blob/7b83c29adf4d939d8623c4cfbeb04712d0c10504/pkg/storage/engine/rocksdb.go#L2438)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Meta-question: is this raw creation of an `MVCCKey` preferred to `MakeMVCCMetadataKey`? If so I would like to someday delete that function on the grounds that it is an unnecessary level of indirection.
</blockquote></details>

I prefer `MakeMVCCMetadataKey` to make it clear what is being done. The raw creation here was incidental. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26576#-:-LEj200jAOFmO-Gf4mJj:b-89xwgk)*

**Comment by tschottdorf** [comment]
:lgtm:

I feel good about merging this. Even if the drop test still wedges, we're pretty sure this eliminates one of its problems (just as it happens not the last remaining one).

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26576#-:-LEjHe9sE_2KIDYTy6tq:bpiscsv)*

**Comment by bdarnell** [comment]
LGTM. I'm fine with merging this since it is low risk and removes one known problem.

**Comment by petermattis** [comment]
bors r=benesch

**Comment by petermattis** [comment]
We should back-port this to 2.0 after it has baked on master for a bit.

**Pull request merged**
