### PR TITLE
authors: add alexyarosh to authors

### PR DESCRIPTION
**Pull request by alexyarosh**
@irfansharif from the "First commit" session

### CODE REVIEW

**Review by irfansharif — APPROVED** [review]
Sweet! Be sure to sign the CLA agreement and "bors r+" it once done.

**Comment by irfansharif** [comment]
Looks like `acceptance/reset-quorum` failed [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=2534311&buildTypeId=Cockroach_UnitTests). @TheSamHuang, do you mind investigating? Or if not, mind skipping the test while it's flaky? It's blocking builds.

bors retry

**Comment by TheSamHuang** [comment]
> Looks like `acceptance/reset-quorum` failed [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=2534311&buildTypeId=Cockroach_UnitTests). @TheSamHuang, do you mind investigating? Or if not, mind skipping the test while it's flaky? It's blocking builds.
> 
> bors retry

Definitely, looking into this now.

**Pull request merged**
