### PR TITLE
util/log: misc fixes

### LINKED ISSUE #56936: logs: log redaction broken
At master, `98fc9b3c760b56dcd4324ecb1da6aadb3d794f39`, no matter how I set `--redactable-logs`, the log files contain unredactable messages. If I use `--logtostderr`, stderr gets redactable messages.
I think this broken @ https://github.com/cockroachdb/cockroach/pull/56336; before it seems to work.

Another thing I observed, both on master and before the patch above, is that the stderr logs are redactable no matter the value of `--redactable-logs={true,false}`. Is that expected?

### PR DESCRIPTION
**Pull request by knz**
This somehow slipped through the review of #56336 
Helps towards #51987
Fixes #56936

### CODE REVIEW

**Review by itsbilal — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56897#-:-MMW8pqpE07XYd6LxBL4:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by knz** [comment]
@itsbilal would welcome your review on the two additional commits thx

**Comment by knz** [comment]
Nevermind - I opened a separate PR #57000 with the additional commits.
Will rewind and merge this.

**Comment by knz** [comment]
bors r=itsbilal

**Comment by knz** [comment]
bors r=itsbilal

**Comment by knz** [comment]
bors r=itsbilal

**Pull request merged**
