### PR TITLE
release-21.2: server: get rid of end-user mechanism to enable span configs

### PR DESCRIPTION
**Pull request by irfansharif**
Backport 2/2 commits from #69658, 1/1 commits from #70232, 1/1 commits from
#70436, + another partially reverting #69658 to disallow end-users from
enabling this infrastructure (though leaving the feature gates intact for
tests).

/cc @cockroachdb/release

---

It was previously possible for single-tenant clusters to enable the span
configs infrastructure by setting COCKROACH_EXPERIMENTAL_SPAN_CONFIGS.  For
secondary tenants, we actually enabled it by default. We've since decided that
the serverless offering intending to use this infrastructure will not be run
using the 21.2 release, instead favoring a 22.1 alpha. There's no reason then
to leave infrastructure wired up to anything in 21.2.

We'll still leave intact the testing knobs enabling this infrastructure, but
they're just that -- testing knobs. A more invasive variant of this PR could've
deleted all span configs code altogether, but that seems unnecessary (and
probably prone to bugs).

Release justification: non-production code changes
Release note: Non-production code

### CODE REVIEW

**Comment by irfansharif** [comment]
(Bump.)

**Review by nvb — COMMENTED** [review]
> Reviewed 11 of 11 files at r1, 18 of 18 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70341)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, and @irfansharif)

___
*[pkg/spanconfig/spanconfigmanager/manager.go, line 157 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70341#-Mk2rY-iE9FglRPdyg7B:-Mk2rY-iE9FglRPdyg7C:brt3mqc) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fa95927fdeb8443c80a95ba0b858a8c6e8470a5/pkg/spanconfig/spanconfigmanager/manager.go#L157)):*
> ```Go
> 		select {
> 		case <-jobCheckCh:
> 			timer.Read = true
> ```

Is this correct? Why set `.Read` in this case?
___
*[pkg/sql/logictest/logic.go, line 463 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70341#-Mk2ryKoCzKzJ6P-IATi:-Mk2ryKoCzKzJ6P-IATj:bp71ke7) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fa95927fdeb8443c80a95ba0b858a8c6e8470a5/pkg/sql/logictest/logic.go#L463)):*
> ```Go
> 	// cluster. Connections on behalf of the logic test will go to that tenant.
> 	useTenant bool
> 	// If true, XXX:
> ```

Did you mean to add a comment here?

**Review by irfansharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70341)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, and @nvanbenschoten)

___
*[pkg/spanconfig/spanconfigmanager/manager.go, line 157 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70341#-Mk2rY-iE9FglRPdyg7B:-Mk2ue1F0iqMZRaizqky:b-rpw6zr) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fa95927fdeb8443c80a95ba0b858a8c6e8470a5/pkg/spanconfig/spanconfigmanager/manager.go#L157)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this correct? Why set `.Read` in this case?
</blockquote></details>

Hm, looks like I'd misunderstood the timer interface. Sent #70436 and backported here for posterity. All that aside -- this is all non-executable code as of the last commit in this PR.
___
*[pkg/sql/logictest/logic.go, line 463 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/70341#-Mk2ryKoCzKzJ6P-IATi:-Mk2uWox3kTTyXG6x7PM:bwqpzqj) ([raw file](https://github.com/cockroachdb/cockroach/blob/3fa95927fdeb8443c80a95ba0b858a8c6e8470a5/pkg/sql/logictest/logic.go#L463)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Did you mean to add a comment here?
</blockquote></details>

Yup, tacked on #70232 here.

**Review by nvb — APPROVED** [review]
> Reviewed 1 of 7 files at r4, 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70341)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @arulajmani)

**Pull request merged**
