### PR TITLE
sql: fix savepoints release note

### PR DESCRIPTION
**Pull request by knz**
These release notes were missing in #45566

Release note (sql change): CockroachDB supports a new statement `SHOW
SAVEPOINT STATUS` which reveals the current stack of active
savepoints. This can be used to teach savepoint usage.

Release note (sql change): CockroachDB now provides preliminary
support for SQL savepoints: the SAVEPOINT, ROLLBACK TO SAVEPOINT and
RELEASE SAVEPOINT statements. The support is limited in the following
ways:
1) certain retry errors cannot be erased by ROLLBACK TO
SAVEPOINT if the corresponding savepoint was not taken at the very
begin of the transaction.
2) ROLLBACK TO SAVEPOINT cannot be used to
cancel the effects of a DDL statement unless the savepoint was taken
at the very begin of the transaction.

### CODE REVIEW

**Comment by knz** [comment]
cc @rmloveland please ignore the release note from #45566

**Comment by rmloveland** [comment]
> cc @rmloveland please ignore the release note from #45566

ack

**Comment by andreimatei** [comment]
Mmmm I don't know about this practice of empty commits just with release notes. I think it pollutes the git history without much benefit. Let's just call Rich warned and leave it at that.
But also I think my release notes were fine. I don't think the DDL thing necessarily needs to be called out in the release notes, and for the retriable errors is pretty good. Or rather, it's unclear if it can be improved to the point where the warning about it can go away. I'd rather leave it all for the docs.

**Comment by knz** [comment]
Release notes *are* docs and the release note stream in the git log *is* the communication channel to push this information to the right place.

**Pull request merged**
