### PR TITLE
pgwire: log session start and end unconditionally

### LINKED ISSUE #122684: Capture logs for successful SQL connections by default
We lack out of the box observability to troubleshoot SQL connections that can be correlated with and reflect abnormal cluster behavior and issues (e.g., degraded service latency).

For instance, a flow is correlating high-level SQL connection metrics with logs for deeper analysis. 

Today, logs for SQL connections are guarded by "server.auth_log.sql_connections.enabled" and "server.auth_log.sql_sessions.enabled" defaulted to false (due to failed authentications attempts that can DDoS the cluster). 

This issue tracks logging **successful** connections by default. We can try logging the following unconditionally:
- successful auth attempts
- connection closed after successful auth

and change the `server.*_log.sql_connections.enabled` setting names to indicate that it only controls "verbose" logging.

See: https://cockroachlabs.slack.com/archives/C0168LW5THS/p1713209175269229

Jira issue: CRDB-38025

Epic CRDB-38033

### PR DESCRIPTION
**Pull request by rafiss**
### pgwire: remove redundant log for JWT auth

This already gets logged in the processCommands function, right before
the server enters the main command processing loop.

### pgwire: log auth info message as redactable string

Previously, the entire info text would be redacted, which made
debugging harder. This improves it so we use the built in
redaction facilities in order to get more detail.

### pgwire: log session start and end unconditionally

Release note (ops change): The client_authentication_ok and
client_session_end messages are now logged to the SESSIONS log channel
unconditionally. Previously, these would only be logged if the
server.auth_log.sql_sessions.enabled cluster setting was changed to
true. All other SESSIONS log messages are still only logged if
server.auth_log.sql_sessions.enabled or
server.auth_log.sql_connections.enabled are set to true.

If you do not want to see client_authentication_ok or client_session_end
messages, then the SESSIONS log channel can be disabled entirely.

fixes https://github.com/cockroachdb/cockroach/issues/122684

### CODE REVIEW

**Review by souravcrl — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124254)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @BabuSrithar, @fqazi, @nkodali, and @rafiss)

___
*[`pkg/sql/pgwire/auth.go` line 538 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124254#-Ny2WpCGB7c2JlF3vdJT:-Ny2WpCGB7c2JlF3vdJU:b-rb6cvw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1008285e2f6c7df11c58ffc22ee110578fe1469/pkg/sql/pgwire/auth.go#L538)):*
> ```Go
> 			CommonConnectionDetails: p.connDetails,
> 			CommonSessionDetails:    p.authDetails,
> 			Info:                    redact.Sprintf(format, args...),
> ```

Why don't we want to use built in redaction for all `SESSIONS` channel logs? Post this we re redacting again here:
https://github.com/cockroachdb/cockroach/blob/446e3a34669a3ddbb9a6383d07b53e9965e38c07/pkg/util/log/clog.go#L354-L355 
which depends on the channel configuration
___
*[`pkg/sql/pgwire/auth.go` line 553 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/124254#-Ny2YZDSEkrVPli19Lyl:-Ny2YZDSEkrVPli19Lym:b2cwkbb) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb91281f00a031021502e7fa29bf2516e6c433e6/pkg/sql/pgwire/auth.go#L553)):*
> ```Go
> 		CommonEventDetails:      logpb.CommonEventDetails{Timestamp: endTime.UnixNano()},
> 		CommonConnectionDetails: p.connDetails,
> 		Duration:                endTime.Sub(p.c.startTime).Nanoseconds(),
> ```

We are assuming connection start and session start times to be same here. What is the reason behind this?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124254)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @BabuSrithar, @fqazi, @nkodali, and @souravcrl)

___
*[`pkg/sql/pgwire/auth.go` line 538 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124254#-Ny2WpCGB7c2JlF3vdJT:-Ny3E6M20OPeJzvxUiZV:b-frjmwm) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1008285e2f6c7df11c58ffc22ee110578fe1469/pkg/sql/pgwire/auth.go#L538)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

Why don't we want to use built in redaction for all `SESSIONS` channel logs? Post this we re redacting again here:
https://github.com/cockroachdb/cockroach/blob/446e3a34669a3ddbb9a6383d07b53e9965e38c07/pkg/util/log/clog.go#L354-L355 
which depends on the channel configuration
</blockquote></details>

that part won't change . `maybeRedactEntry` is the function that will actually perform redaction. `redact.Sprintf` doesn't perform redaction; what it does is make a string "redactable", meaning that the sensitive parts of the string are enclosed in `‹` and `›` markers. (see my screenshot below from splunk for an example)

this page provides a good overview of redaction and the various helper functions: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/1824817806/Log+and+error+redactability


___
*[`pkg/sql/pgwire/auth.go` line 553 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/124254#-Ny2YZDSEkrVPli19Lyl:-Ny3Eyiq6473w9ONvidG:b-zatog7) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb91281f00a031021502e7fa29bf2516e6c433e6/pkg/sql/pgwire/auth.go#L553)):*
<details><summary><i>Previously, souravcrl wrote…</i></summary><blockquote>

We are assuming connection start and session start times to be same here. What is the reason behind this?
</blockquote></details>

a session always starts when a connection starts. in fact, i would just define a "SQL session" as "a SQL connection that has successfully authenticated." there is no way for a session to end, but the connection remain open and get used again for another session.

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124254)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @BabuSrithar, @fqazi, @nkodali, and @souravcrl)

___
*[`pkg/sql/pgwire/auth.go` line 538 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124254#-Ny2WpCGB7c2JlF3vdJT:-Ny3FogWDdfZDQkdXFWv:b-6lz4vi) ([raw file](https://github.com/cockroachdb/cockroach/blob/b1008285e2f6c7df11c58ffc22ee110578fe1469/pkg/sql/pgwire/auth.go#L538)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

that part won't change . `maybeRedactEntry` is the function that will actually perform redaction. `redact.Sprintf` doesn't perform redaction; what it does is make a string "redactable", meaning that the sensitive parts of the string are enclosed in `‹` and `›` markers. (see my screenshot below from splunk for an example)

this page provides a good overview of redaction and the various helper functions: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/1824817806/Log+and+error+redactability


</blockquote></details>

compare that screenshot to this one of a `client_authentication_failed` message. note that the `Detail` field is only partially redacted, so rather than the entire string being removed, only the sensitive part (i.e., the user name) is removed.

the code change i've made here is the same as what `client_authentication_failed` already is doing. i actually made that change earlier in 1ca745071030a5bf93262638bb82f91cc7fdc578

**Review by souravcrl — APPROVED** [review]
> Reviewed 2 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124254)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @BabuSrithar, @fqazi, and @nkodali)

**Comment by rafiss** [comment]
thanks for the review!

bors r+

**Pull request merged**
