### PR TITLE
opt: telemetry improvements (index hints, joins, FKs)

### LINKED ISSUE #43765: sql: add foreign keys to features table
Foreign key telemetry isnt available via the features table and therefore is somewhat inaccurate from the statements table. We should add it to the features table.

### LINKED ISSUE #43794: sql: improve the index hint telemetry
Index hints on update/delete do not trigger telemetry currently.

We should add counters for these index hints.

In addition, I think we should separate out the index hints into mutually exclusive and collectively exhaustive buckets that cover each type of index hints (e.g., delete, update, select). That way we can tell if a certain type is used more than others and make changes as needed.

### LINKED ISSUE #46188: sql: hash join not present in telemetry
We don't have telemetry for hash joins (although we do have merge and lookup). We should add this for 20.1.

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: better telemetry for index hints

The index hint telemetry now relfects hint usage for update/delete.
The existing counter is triggered by all cases, and more specific
counters are added depending on the statement type.

Fixes #43794.

Release note: None

#### opt: improved telemetry for joins

Currently, we emit telemetry for each join operator in the final plan (e.g.
`sql.plan.node.merge-join`. This data is hard to work with because it doesn't
cleanly separate the algorithm from the join type. In particular, merge/lookup
joins emit the same telemetry regardless of join type.

This change removes the existing counters and replaces them with two sets of
counters, one for the join type and one for the join algorithm (which now
includes hash and cross).

Fixes #46188.

Release note: None

#### opt: telemetry for FK planning

This change adds the following telemetry counters:
 - sql.plan.fk.checks: incremented when a statement has FK checks
   planned through the optimizer.
 - sql.plan.fk.cascades: incremented when a statement involves
   cascades.
 - sql.plan.fk.legacy: incremented when the legacy path is used
   (including the cascades case).

Fixes #43765.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Note: I ran some manual tests. I plan to add test cases once we have a proper testing framework (#46730).

**Comment by RaduBerinde** [comment]
Gentle ping.

**Review by andy-kimball — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46749#-:-M3qQ87n8_7JGO8YvT7W:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andy-kimball, @RaduBerinde, and @rytaft)

___
*[pkg/sql/sqltelemetry/planning.go, line 80 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/46749#-M3qPoyp7Ybno4kp1Nj6:-M3qPoyp7Ybno4kp1Nj7:b-9khxqt) ([raw file](https://github.com/cockroachdb/cockroach/blob/0046dfccc6c64a0b50fee45c6220df43c7dedb3c/pkg/sql/sqltelemetry/planning.go#L80)):*
> ```Go
> var IndexHintUpdateUseCounter = telemetry.GetCounterOnce("sql.plan.hints.index.update")
> 
> //
> ```

NIT: Remove blank comment line.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46749)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/sqltelemetry/planning.go, line 80 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/46749#-M3qPoyp7Ybno4kp1Nj6:-M3qQnUd-7LKDgK0_xdv:bexegmu) ([raw file](https://github.com/cockroachdb/cockroach/blob/0046dfccc6c64a0b50fee45c6220df43c7dedb3c/pkg/sql/sqltelemetry/planning.go#L80)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: Remove blank comment line.
</blockquote></details>

Done, TFTR!

**Review by rytaft — COMMENTED** [review]
Sorry for the delay!

> Reviewed 2 of 3 files at r1, 7 of 7 files at r4, 6 of 6 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46749#-:-M3qVlzr3OVLSWQAXi0U:b2c5wy4)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

___
*[pkg/sql/opt/ops/relational.opt, line 386 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/46749#-M3qUsUwDqsRZwweMaFC:-M3qUsUwDqsRZwweMaFD:b-je0v1i) ([raw file](https://github.com/cockroachdb/cockroach/blob/2254bc5be1a6a9dbf243334332c5109b41448044/pkg/sql/opt/ops/relational.opt#L386)):*
> ```
> # TODO(itsbilal): Add support for representing multi-way zigzag joins.
> [Relational]
> define ZigzagJoin {
> ```

Are we still getting telemetry for zig zag join?
___
*[pkg/sql/sqltelemetry/planning.go, line 66 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/46749#-M3qUBvDDjP67qUAujAj:-M3qUBvEAAPOfL5mH-56:b-wza1eg) ([raw file](https://github.com/cockroachdb/cockroach/blob/914dc25313e4018bcc892e4bf8e8e16e1bcdd612/pkg/sql/sqltelemetry/planning.go#L66)):*
> ```Go
> 
> // IndexHintDeleteUseCounter is to be incremented whenever a query specifies an
> // index hint in an UPDATE.
> ```

UPDATE -> DELETE
___
*[pkg/sql/sqltelemetry/planning.go, line 125 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/46749#-M3qV7unELwPu-etYc3p:-M3qV7unELwPu-etYc3q:b-2bwj0m) ([raw file](https://github.com/cockroachdb/cockroach/blob/2254bc5be1a6a9dbf243334332c5109b41448044/pkg/sql/sqltelemetry/planning.go#L125)):*
> ```Go
> 
> // JoinTypeLeftUseCounter is to be incremented whenever a left outer join node is
> // planned.
> ```

want to also mention that this includes right join?

**Review by RaduBerinde — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46749#-:-M3q_6gA9pqPG3UmYSX9:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

___
*[pkg/sql/opt/ops/relational.opt, line 386 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/46749#-M3qUsUwDqsRZwweMaFC:-M3qZVds4OtjWbaM-sje:baq8oar) ([raw file](https://github.com/cockroachdb/cockroach/blob/2254bc5be1a6a9dbf243334332c5109b41448044/pkg/sql/opt/ops/relational.opt#L386)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Are we still getting telemetry for zig zag join?
</blockquote></details>

Oops, good catch! Another datapoint for why we need an actual testing framework for this. Fixed.
___
*[pkg/sql/sqltelemetry/planning.go, line 66 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/46749#-M3qUBvDDjP67qUAujAj:-M3qZuIF3QxwD0706gwd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/914dc25313e4018bcc892e4bf8e8e16e1bcdd612/pkg/sql/sqltelemetry/planning.go#L66)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

UPDATE -> DELETE
</blockquote></details>

Done.
___
*[pkg/sql/sqltelemetry/planning.go, line 125 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/46749#-M3qV7unELwPu-etYc3p:-M3q_5H3CgGMtwz68n8y:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2254bc5be1a6a9dbf243334332c5109b41448044/pkg/sql/sqltelemetry/planning.go#L125)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

want to also mention that this includes right join?
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
:lgtm: 

> Reviewed 5 of 6 files at r8, 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46749#-:-M3rTHo0ELW3irxrMZnW:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

___
*[pkg/sql/sqltelemetry/planning.go, line 81 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/46749#-M3rT01u6hV7VythqBlQ:-M3rT01u6hV7VythqBlR:b1c55dd) ([raw file](https://github.com/cockroachdb/cockroach/blob/770aa10ee17af0c15d0f607c4674b53cb7973cdc/pkg/sql/sqltelemetry/planning.go#L81)):*
> ```Go
> 
> // IndexHintDeleteUseCounter is to be incremented whenever a query specifies an
> // index hint in an DELETE.
> ```

[nit] an DELETE -> a DELETE

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46749)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @rytaft)

___
*[pkg/sql/sqltelemetry/planning.go, line 81 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/46749#-M3rT01u6hV7VythqBlQ:-M3rUL3H-SjNbfrUX83D:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/770aa10ee17af0c15d0f607c4674b53cb7973cdc/pkg/sql/sqltelemetry/planning.go#L81)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

[nit] an DELETE -> a DELETE
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 5 of 6 files at r11, 2 of 2 files at r12.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46749)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Comment by awoods187** [comment]
awesome work!

**Pull request merged**
