### PR TITLE
sql: refactor FKs to derive back-references from forward references.

### PR DESCRIPTION
**Pull request by dt**
the backrefs are derivable from the forward refs alone, and doing so, rather than accumulating that state in `fkTargets`, paves the way for doing so in a schema change rather than during the initial execution of CREATE.

This also changes table creation to use the pre-reserved table ID, rather than waiting until `createDescriptor` reserves and assigns one. This is so that self-referencing FKs can include the correct ID up front. As a special-case for self-referencing FKs, their back-references can be installed up-front rather than during the finalize step.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8336)

### CODE REVIEW

**Comment by vivekmenezes** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[sql/create.go, line 319 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8336#-KOQYXp3c8KtkAf1o_ov:-KOQYXp3c8KtkAf1o_ow:b-rh3sp4) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b163cb06143ca4c0d790ff2806c31bcae818461/sql/create.go#L319)):*
> ```Go
> 
> 	// FKs are resolved after the descriptor is otherwise complete and IDs have
> 	// been allocated since the FKs will reference those IDs.
> ```

Is this comment still relevant?

---

*[sql/create.go, line 360 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8336#-KOQYnUbqHUz9OhgAzfz:-KOQYnUbqHUz9OhgAzg-:bb7s76d) ([raw file](https://github.com/cockroachdb/cockroach/blob/85573ea6aa6184e17a89459a5fe823cc45338a6c/sql/create.go#L360)):*
> ```Go
> 	if desc.ID == 0 {
> 		desc.ID = keys.MaxReservedDescID + 1
> 	}
> ```

yay!

---

*[sql/create.go, line 537 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8336#-KOQakGXnF29js4ISKsG:-KOQakGXnF29js4ISKsH:b40i2hy) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b163cb06143ca4c0d790ff2806c31bcae818461/sql/create.go#L537)):*
> ```Go
> 	// waiting for the finalize step, and do not need to use the ADD table state.
> 	if target == tbl {
> 		ref.Name = ""
> ```

why not use the name of the table?

---

*[sql/create.go, line 659 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8336#-KOQbfle4fijX9BlCoH2:-KOQbfle4fijX9BlCoH3:b-3jmovf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b163cb06143ca4c0d790ff2806c31bcae818461/sql/create.go#L659)):*
> ```Go
> 			backref := sqlbase.ForeignKeyReference{Table: desc.ID, Index: idx.ID}
> 			targetIdx.ReferencedBy = append(targetIdx.ReferencedBy, backref)
> 			save[targetTable.ID] = targetTable
> ```

add to save in the !ok

---

*[sql/descriptor.go, line 98 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8336#-KOQcLi8_sIvpQAWW7lm:-KOQcLi8_sIvpQAWW7ln:b-ed5ax4) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b163cb06143ca4c0d790ff2806c31bcae818461/sql/descriptor.go#L98)):*
> ```Go
> }
> 
> func (p *planner) incDescID() (sqlbase.ID, error) {
> ```

generateUniqueDescID()

---

*[sql/testdata/fk, line 31 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8336#-KOQaLudjpWMwrXkf6P5:-KOQaLudjpWMwrXkf6P6:b-bai7sd) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b163cb06143ca4c0d790ff2806c31bcae818461/sql/testdata/fk#L31)):*
> ```
> CREATE TABLE mismatch (customer INT REFERENCES customers (email))
> 
> statement error column\(s\) cannot be used by multiple foreign key constraints
> ```

Can you add a test for both the errors that happen to have the same message?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8336)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[sql/descriptor.go, line 133 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8336#-KORIi2tdt5J9Hm9rMIZ:-KORIi2tdt5J9Hm9rMI_:bwcc6vf) ([raw file](https://github.com/cockroachdb/cockroach/blob/547b871b323906709576e16686f9c5bb9441e0f3/sql/descriptor.go#L133)):*
> ```Go
> 		if ifNotExists {
> 			// Noop.
> 			return false, nil
> ```

In this case, where whatever we're creating exists already (and we're ok with that), we will have incremented the descriptor key for no reason. I think `createDescriptorWithID` cannot support this case correctly, only `createDescriptor` can.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8336)*

**Comment by dt** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[sql/create.go, line 319 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8336#-KOQYXp3c8KtkAf1o_ov:-KORd-6OZ5pn5OVSbSX1:b-t7k25x) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b163cb06143ca4c0d790ff2806c31bcae818461/sql/create.go#L319)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> Is this comment still relevant?
</details>
Yes, you still need AllocateIDs to have been called so the indexes have IDs, since self-referencing FKs need those.

---

*[sql/create.go, line 537 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8336#-KOQakGXnF29js4ISKsG:-KORbl1O20Z0OQ13frLV:b-kfg9yc) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b163cb06143ca4c0d790ff2806c31bcae818461/sql/create.go#L537)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> why not use the name of the table?
</details>
use the name for what?

---

*[sql/create.go, line 659 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8336#-KOQbfle4fijX9BlCoH2:-KOReFNbpuNVtD_M8Ze0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b163cb06143ca4c0d790ff2806c31bcae818461/sql/create.go#L659)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> add to save in the !ok
</details>
Done.

---

*[sql/descriptor.go, line 133 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8336#-KORIi2tdt5J9Hm9rMIZ:-KORZBficaoPcCvHXdKc:b-zelcjt) ([raw file](https://github.com/cockroachdb/cockroach/blob/547b871b323906709576e16686f9c5bb9441e0f3/sql/descriptor.go#L133)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> In this case, where whatever we're creating exists already (and we're ok with that), we will have incremented the descriptor key for no reason. I think `createDescriptorWithID` cannot support this case correctly, only `createDescriptor` can.
</details>
Yeah, that wasn't great. Fixed now: `createDescriptorWithID` uses the passed ID _if it is non-zero_ now, otherwise it calls the generation function, but only after the possible early if-exists return.

---

*[sql/descriptor.go, line 98 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8336#-KOQcLi8_sIvpQAWW7lm:-KOReG3QonmWuLOBoGbC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b163cb06143ca4c0d790ff2806c31bcae818461/sql/descriptor.go#L98)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> generateUniqueDescID()
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8336)*

**Comment by dt** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[sql/testdata/fk, line 31 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8336#-KOQaLudjpWMwrXkf6P5:-KORjc24KWpePUHV_jT-:bghb3z0) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b163cb06143ca4c0d790ff2806c31bcae818461/sql/testdata/fk#L31)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> Can you add a test for both the errors that happen to have the same message?
</details>
This will be getting fixed up in #8345 anyway along with that test case so I'd rather punt in this CL unless you feel strongly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8336)*

**Comment by vivekmenezes** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[sql/create.go, line 537 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8336#-KOQakGXnF29js4ISKsG:-KOS7WT5BxVk2GHqdNL8:b-po7x3x) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b163cb06143ca4c0d790ff2806c31bcae818461/sql/create.go#L537)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> use the name for what?
</details>
I was referring to the ```ref.Name = ""``` below

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8336#-:-KOS7rXNISBjl8AjRnm-:bnfp4nl)*

**Comment by dt** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[sql/create.go, line 537 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8336#-KOQakGXnF29js4ISKsG:-KOS8A6IrRDLhnasqOpI:bakudm2) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b163cb06143ca4c0d790ff2806c31bcae818461/sql/create.go#L537)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary>
> I was referring to the ```ref.Name = ""``` below
</details>
The name field is only used on the referencing table, where it provides the constraint name (for use in ALTER or whatever) -- it isn't used on the back-reference side at all. The back ref has the table's ID in `.Table` anyway, which is the part that we actually use, so I was just blanking it here to save a few useless bytes in the referenced tabledescriptor.

I was also avoiding using table names and just sticking with IDs, so I didn't have to worry about transactional edits across tables for renames.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8336)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r4, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[sql/create.go, line 277 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8336#-KOSCNHQoXDaGD_XfGZR:-KOSCNHQoXDaGD_XfGZS:b-g1eiob) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab1f9f7ee5d7b942a7500d8a4ed4d16c33c046f0/sql/create.go#L277)):*
> ```Go
> 	}
> 
> 	tableKey := tableKey{n.dbDesc.ID, n.n.Table.Table()}
> ```

nit: can you use a keyed literal?

---

*[sql/create.go, line 523 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8336#-KOSIW7JBbm-yaNYmRPf:-KOSIW7KksCj_RoNxieJ:bkp9m1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab1f9f7ee5d7b942a7500d8a4ed4d16c33c046f0/sql/create.go#L523)):*
> ```Go
> 	if matchesIndex(srcCols, tbl.PrimaryIndex, matchPrefix) {
> 		if tbl.PrimaryIndex.ForeignKey.IsSet() {
> 			return fmt.Errorf("column(s) cannot be used by multiple foreign key constraints")
> ```

no longer includes the column name(s)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8336)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[sql/create.go, line 277 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8336#-KOSCNHQoXDaGD_XfGZR:-KOSLQ8I2RqFdakAvDVh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab1f9f7ee5d7b942a7500d8a4ed4d16c33c046f0/sql/create.go#L277)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit: can you use a keyed literal?
</details>
Done.

---

*[sql/create.go, line 523 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8336#-KOSIW7JBbm-yaNYmRPf:-KOSJtIA2Gs6IMCG1EYf:b1vzzi5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab1f9f7ee5d7b942a7500d8a4ed4d16c33c046f0/sql/create.go#L523)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> no longer includes the column name(s)?
</details>
yeah, it was previously incorrectly over-reporting multi-used cols related to the issue described in #8345. Until #8345 gets fixed, this is less specific but also less incorrect.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8336)*

**Pull request merged**
