### PR TITLE
kvserver: record batch requests with no gateway

### LINKED ISSUE #85157: kvserver: account for no node id in leaseholder stats
### Problem

Currently `replica_send`, which is the point at where load is accounted, then used in load based rebalancing, does not record QPS when `GatewayNodeID=0` (default value). 

https://github.com/cockroachdb/cockroach/blob/4df883bc0c0fb81c313981f6919316a53120800f/pkg/kv/kvserver/replica_send.go#L140-L142

This means that `dist_sender` requests that do not set a `GatewayNodeID`, will not be accounted for and not considered as load on the receiving store, despite still using resources.

A secondary tenant will currently never populate this value

https://github.com/cockroachdb/cockroach/blob/cc155a1efe057be7d9432d160744186059767140/pkg/kv/kvclient/kvcoord/dist_sender.go#L564-L568

### Solution

The solution is to account for QPS, when `GatewayNodeID=0` regardless and then modify the semantics of the user of the locality based load counts to not consider these "untagged" load counts.

https://github.com/cockroachdb/cockroach/blob/d7b901d7d28ceb4900dd60c5c73b2180089a3e3a/pkg/kv/kvserver/allocator/allocatorimpl/allocator.go#L1980-L1980

Jira issue: CRDB-18068

### PR DESCRIPTION
**Pull request by kvoli**
Previously, batch requests with no `GatewayNodeID` would not be
accounted for on the QPS of a replica. By extension, the store QPS would
also not aggregate this missing QPS over replicas it holds. This patch
introduces tracking for all requests, regardless of the `GatewayNodeID`.

This was done to as follow the workload lease transfers consider the
per-locality counts, therefore untagged localities were not useful. This
has since been updated to ignore filter out localities directly, so it
is not necessary to exclude them anymore.

`leaseholderStats`, which previously tracked the QPS, and `writeStats`
tracking the mvcc keys written, have also been removed. They are
duplicated in `batchRequest` and `writeKeys` respectively, within the
`loadStats` of a replica.

resolves https://github.com/cockroachdb/cockroach/issues/85157

Release note: None

### CODE REVIEW

**Review by lidorcarmel — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85178)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/replica_application_state_machine.go` line 1014 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85178#-N8AKoe95J7qixguXdz7:-N8AKoe95J7qixguXdz8:bxgzr7k) ([raw file](https://github.com/cockroachdb/cockroach/blob/04b43de496bd98ff8d6e6ec3a175c1f6db0b9181/pkg/kv/kvserver/replica_application_state_machine.go#L1014)):*
> ```Go
> 	// Record the write activity, passing a 0 nodeID because replica.writeStats
> 	// intentionally doesn't track the origin of the writes.
> 	b.r.loadStats.writeKeys.RecordCount(float64(b.mutations), 0)
> ```

is it guaranteed that loadStats cannot be nil here?



_Code quote:_
```Go
b.r.loadStats.writeKeys.RecordCount(float64(b.mutations), 0
```
___
*[`pkg/kv/kvserver/replica_send.go` line 1006 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85178#-N8AGz2p04s761rcFqOh:-N8AGz2p04s761rcFqOi:b-idkrih) ([raw file](https://github.com/cockroachdb/cockroach/blob/04b43de496bd98ff8d6e6ec3a175c1f6db0b9181/pkg/kv/kvserver/replica_send.go#L1006)):*
> ```Go
> func (r *Replica) recordBatchRequestLoad(ctx context.Context, ba *roachpb.BatchRequest) {
> 	if r.loadStats == nil {
> 		log.Eventf(
> ```

when would this happen? only in tests maybe? if in prod, will it spam the log? if yes then either move this to be a level N log (vmodule) or log every N messages or something like that..



_Code quote:_
```Go
r.loadStats == nil {
```
___
*[`pkg/kv/kvserver/replica_send.go` line 1017 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85178#-N8AIUOIDgCsb3qIRXZs:-N8AIUOIDgCsb3qIRXZt:bq2ifaf) ([raw file](https://github.com/cockroachdb/cockroach/blob/04b43de496bd98ff8d6e6ec3a175c1f6db0b9181/pkg/kv/kvserver/replica_send.go#L1017)):*
> ```Go
> 	// estimate of a BatchRequest. See getBatchRequestQPS() for the
> 	// calculation.
> 	scaledQPS := r.getBatchRequestQPS(ctx, ba)
> ```

nit: `adjustedQPS` maybe? when I see scale I think of other things, sorry :(



_Code quote:_
```Go
scaledQPS
```
___
*[`pkg/kv/kvserver/replica_send.go` line 1023 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85178#-N8AI_xl7eJIV5gh2eeb:-N8AI_xl7eJIV5gh2eec:b-7eegrv) ([raw file](https://github.com/cockroachdb/cockroach/blob/04b43de496bd98ff8d6e6ec3a175c1f6db0b9181/pkg/kv/kvserver/replica_send.go#L1023)):*
> ```Go
> 	// requests, for follow the workload lease transfers. We now record these
> 	// regardless of the gateway node id, as the only user of this information
> 	// does not consider untagged localities. See
> ```

I'm wondering whether this really has value here? definitely this should be in the PR/commit description, and it is, but do readers a year from now would need to know this info? feel free to keep it if you think it has any value..



_Code quote:_
```Go
	// NB: Previously, we would ignore batch requests which had no gateway node
	// id. This was in order to retrieve accurate per-locality counts of
	// requests, for follow the workload lease transfers. We now record these
	// regardless of the gateway node id, as the only user of this information
	// does not consider untagged localities. See
	// allocator.shouldTransferLeaseForAccessLocality() .
```
___
*[`pkg/kv/kvserver/store_merge.go` line 149 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85178#-N8AMVKYEJQcMh4xhX_H:-N8AMVKYEJQcMh4xhX_I:b-absa7x) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b5a2b7b37b1f0648161d967ee8046d27ea96915/pkg/kv/kvserver/store_merge.go#L149)):*
> ```Go
> 
> 	if leftRepl.leaseholderStats != nil {
> 		leftRepl.leaseholderStats.ResetRequestCounts()
> ```

question: what does this change mean? that we used to reset qps stats here and now we don't how will it affect the behavior after merge? I'll try to look later.



_Code quote:_
```Go
	if leftRepl.leaseholderStats != nil {
		leftRepl.leaseholderStats.ResetRequestCounts()
	}
	if leftRepl.writeStats != nil {
		// Note: this could be drastically improved by adding a replicaStats method
		// that merges stats. Resetting stats is typically bad for the rebalancing
		// logic that depends on them.
		leftRepl.writeStats.ResetRequestCounts()
	}
```

**Review by kvoli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85178)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lidorcarmel)

___
*[`pkg/kv/kvserver/replica_application_state_machine.go` line 1014 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85178#-N8AKoe95J7qixguXdz7:-N8OgtE-E77-bs-BdKst:bs4zto8) ([raw file](https://github.com/cockroachdb/cockroach/blob/04b43de496bd98ff8d6e6ec3a175c1f6db0b9181/pkg/kv/kvserver/replica_application_state_machine.go#L1014)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

is it guaranteed that loadStats cannot be nil here?
</blockquote></details>

Yes, it cannot be nil. This is more of a cleanup - this guard was added initially out of caution but its redundant.

The only case where it could be nil is in some tests which manually create a store, then never pass in the store pool config - which is checked when creating an unloaded replica, in deciding to initialize the load stats.
___
*[`pkg/kv/kvserver/replica_send.go` line 1006 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85178#-N8AGz2p04s761rcFqOh:-N8OhZq_EdEJsQP3XeML:b-xph46t) ([raw file](https://github.com/cockroachdb/cockroach/blob/04b43de496bd98ff8d6e6ec3a175c1f6db0b9181/pkg/kv/kvserver/replica_send.go#L1006)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

when would this happen? only in tests maybe? if in prod, will it spam the log? if yes then either move this to be a level N log (vmodule) or log every N messages or something like that..
</blockquote></details>

Only in tests. However i updated to 3.
___
*[`pkg/kv/kvserver/replica_send.go` line 1017 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85178#-N8AIUOIDgCsb3qIRXZs:-N8OhrAH3KxqIHc5lhh-:b-cypxrc) ([raw file](https://github.com/cockroachdb/cockroach/blob/04b43de496bd98ff8d6e6ec3a175c1f6db0b9181/pkg/kv/kvserver/replica_send.go#L1017)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

nit: `adjustedQPS` maybe? when I see scale I think of other things, sorry :(
</blockquote></details>

updated.
___
*[`pkg/kv/kvserver/replica_send.go` line 1023 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85178#-N8AI_xl7eJIV5gh2eeb:-N8Ohuw8E1FSuVUQBczj:bnghns) ([raw file](https://github.com/cockroachdb/cockroach/blob/04b43de496bd98ff8d6e6ec3a175c1f6db0b9181/pkg/kv/kvserver/replica_send.go#L1023)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

I'm wondering whether this really has value here? definitely this should be in the PR/commit description, and it is, but do readers a year from now would need to know this info? feel free to keep it if you think it has any value..
</blockquote></details>

Fair point - removed.
___
*[`pkg/kv/kvserver/store_merge.go` line 149 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85178#-N8AMVKYEJQcMh4xhX_H:-N8Oi2mHAq1MPRrBkbFY:bgui8x8) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b5a2b7b37b1f0648161d967ee8046d27ea96915/pkg/kv/kvserver/store_merge.go#L149)):*
<details><summary><i>Previously, lidorcarmel (Lidor Carmel) wrote…</i></summary><blockquote>

question: what does this change mean? that we used to reset qps stats here and now we don't how will it affect the behavior after merge? I'll try to look later.
</blockquote></details>

The previous behavior was a relic of before having a "merge stats" function.

It would wipe the lhs - before merging in the rhs.

However this is illogical - the whole point of merging is to combine both the lhs and rhs. 

This is updated to be correct. I don't think it will have much effect on behavior because they are being merged for low size/qps reason.

**Review by lidorcarmel — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85178)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lidorcarmel)

**Pull request merged**
