### PR TITLE
tree: mark IsOperator on ComparisonExpr

### PR DESCRIPTION
**Pull request by otan**
The last nugget of work for OPERATOR! This commit makes ComparisonExpr
aware of OPERATOR, which means it formats correctly during the pretty
print work.

Release note: None

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
lgtm!

**Review by mgartner — APPROVED** [review]
:lgtm: 

> Reviewed 41 of 41 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67348#-:-Me6Wk4o9ZiVV8om9xBs:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/sql/sem/tree/expr.go, line 359 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67348#-Me6VOso0Edjn_4-MD7X:-Me6VOspACJ5IF-rsENG:b-5xnh2z) ([raw file](https://github.com/cockroachdb/cockroach/blob/2413beb1599f33d1a25d01dfedaf1cc16e44552b/pkg/sql/sem/tree/expr.go#L359)):*
> ```Go
> 	Symbol ComparisonOperatorSymbol
> 	// IsOperator is true if OPERATOR(symbol) is used.
> 	IsOperator bool
> ```

Since all `ComparisonOperators` are "operators", would this field be better named `IsQualifiedOperator`? That's what the PG docs seem to call it: https://www.postgresql.org/docs/current/sql-expressions.html#SQL-EXPRESSIONS-OPERATOR-CALLS

Or is it only "qualified" if it is in the form `OPERATOR(schema.operator_name)` and it's possible to just have `OPERATOR(operator_name)`? In that case, maybe `IsExplicitOperator` or `IsWrappedByOperator` or something would be ok?

Apologies if there has already been a discussion on nomenclature for this that I missed.

**Comment by otan** [comment]
___
*[pkg/sql/sem/tree/expr.go, line 359 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/67348#-Me6VOso0Edjn_4-MD7X:-Me72pyQCw35sBbA1dq2:bg8qd2w) ([raw file](https://github.com/cockroachdb/cockroach/blob/2413beb1599f33d1a25d01dfedaf1cc16e44552b/pkg/sql/sem/tree/expr.go#L359)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Since all `ComparisonOperators` are "operators", would this field be better named `IsQualifiedOperator`? That's what the PG docs seem to call it: https://www.postgresql.org/docs/current/sql-expressions.html#SQL-EXPRESSIONS-OPERATOR-CALLS

Or is it only "qualified" if it is in the form `OPERATOR(schema.operator_name)` and it's possible to just have `OPERATOR(operator_name)`? In that case, maybe `IsExplicitOperator` or `IsWrappedByOperator` or something would be ok?

Apologies if there has already been a discussion on nomenclature for this that I missed.
</blockquote></details>

Renamed to `IsExplicitOperator`, it does not need a schema name

**Comment by otan** [comment]
bors r=rafiss,mgartner

**Pull request merged**
