### PR TITLE
sql,mon: expose the memory monitors as virtual table

### LINKED ISSUE #90551: memory: make memory monitor trees observable
A debug feature that would be helpful in the console, debug.zips and many even statement bundles would be reporting around the memory monitor tree.   This is the various BytesMonitors and BoundAccounts created from pkg/util/mon that track memory usage.  There's a natural tree with a "sql" can "conn" roots that have branches for each connection/session/transaction/statement.   A complete implementation would also include internal jobs sessions and distsql flows.
 

Jira issue: CRDB-20833

Epic CRDB-20791

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit adjusts our memory monitors to be able to traverse the whole
monitor tree starting at the root monitor. In particular, this commit
introduces a doubly-linked list of "siblings" and stores the reference
to the head in the parent. Whenever a monitor is `Start`ed, it is
included as the new head of its parent's children list, whenever a monitor
is `Stop`ped, it is removed from that list. The overhead of this
additional tracking should be negligible since only the parent's lock
needs to be acquired twice throughout the lifetime of a monitor (thus,
assuming relatevily long-lived sessions, this wouldn't affect the root
monitor) and the increase in allocations is minor.

This required clarification on how locks on a parent and a child can be
held at the same time. In particular, since the main code path is
acquiring locks "upwards" (meaning when growing the child's budget we
might need to grow the parent's budget, and "growing" locks the
corresponding monitor), whenever we want to traverse the tree from the
root down, we have to unlock the parent's monitor before recursing into
the children. As a result, the traversal might give us an inconsistent
view (where a recently stopped child can contribute to the usage of the
parent while we don't recurse into that child). This seems acceptable.

This ability to traverse the whole monitor tree is now exposed as a new
virtual table `crdb_internal.node_memory_monitors` which includes a line
for each monitor active at the time of table generation (subject to
possible inconsistency mentioned above). The table includes the name of
the monitors which can be suggestive about the activity on the cluster,
thus, access to this table is gated on the "view activity" permissions.
The usage of the virtual table to expose the memory monitors information
results in flattening of the tree; however, one of the fields is
a "level" (or "generation") in relation to the root, plus the ordering
of rows is very specific, so we can still format the output to see the
hierarchy. We also assign IDs to the monitors (which is their pointer
address). Exposing this information as a virtual table allows us to use
SQL to analyze it.

Here is one example of visualizing it:
```
root@127.0.0.1:26257/defaultdb> SELECT repeat('    ', level) || name || ' ' || crdb_internal.humanize_bytes(used) FROM crdb_internal.node_memory_monitors;
                             ?column?
-------------------------------------------------------------------
  root 0 B
      internal-planner.‹root›.‹resume-job-101› 0 B
      internal-planner.‹node›.‹resume-job-100› 0 B
      internal-planner.‹node›.‹resume-job-842810460057567233› 0 B
      sql 900 KiB
          session root 20 KiB
              txn 10 KiB
                  flow e595eb80 10 KiB
              session 0 B
              txn-fingerprint-id-cache 0 B
          internal SQL executor 0 B
          internal SQL executor 0 B
          internal sql executor 0 B
          conn 105 KiB
          internal SQL executor 70 KiB
          internal SQL executor 60 KiB
          SQLStats 540 KiB
          SQLStats 0 B
      distsql 0 B
      server-cache-mon 0 B
      bulk-mon 0 B
          backup-mon 0 B
          backfill-mon 0 B
      pre-conn 105 KiB
      closed-session-cache 190 KiB
      timeseries-results 0 B
      timeseries-workers 0 B
      kv-mem 20 KiB
          rangefeed-monitor 0 B
          rangefeed-system-monitor 0 B
(30 rows)
```

There are a couple of additional minor improvements:
- we now include the short FlowID into the flow's memory monitor name.
Combined with the distsql_flows virtual table we'll be able to get the
stmt fingerprint for the remote flows running on a node.
- new `crdb_internal.humanize_bytes` builtin function is introduced.

Note that the corresponding `cluster_memory_monitors` virtual table is
not introduced out of caution. In particular, this would lead to RPCs
issued to all nodes in the cluster, and since each node can have on the
order of hundreds of thousands monitors, the response to each RPC could
have non-trivial network cost. We can revisit this decision later if we
find that a cluster level view of the memory monitors is desirable, but
for now a node level view seems like a big improvement on its own.

Addresses: #35097.
Fixes: #90551.

Release note (sql change): New internal virtual table
`crdb_internal.memory_monitors` is introduced. It exposes all of the
current reservations with the memory accounting system on a single node.
Access to the table requires VIEWACTIVITY or VIEWACTIVITYREDACTED
permissions.

### CODE REVIEW

**Comment by yuzefovich** [comment]
I ended up exposing the data as the virtual table, thanks @michae2 for the idea! I didn't run any performance benchmarks cause I'm pretty confident the overhead should be negligible, however, I can do that if someone thinks it'd be worth it. Also it seems pretty safe for a backport (perhaps after a short baking period on master).

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97657)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @michae2, and @rharding6373)

___
*[`-- commits` line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97657#-NPInVwYD8SdpX9FYIQa):*
I initially included the requirement for VIEWACTIVITY permissions mainly out of performance considerations (in a previous iteration, when traversing the tree we'd hold the parent's lock until all children are fully traversed, which can be quite costly since it would lock the root monitor; however, that turned out to lead to deadlocks, so I refactored the logic), so I'm curious what others think whether this is necessary or not. Names of the monitors don't contain any PII but can contain things like "sort" or "hashjoiner" which is suggestive about the type of activity.

**Review by rharding6373 — APPROVED** [review]
Very nice work! :lgtm: 

> Reviewed 25 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97657#-:-NPJLdhg538xILZbZORg:b-hi67zu)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball, @michae2, and @yuzefovich)

___
*[`-- commits` line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97657#-NPInVwYD8SdpX9FYIQa):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I initially included the requirement for VIEWACTIVITY permissions mainly out of performance considerations (in a previous iteration, when traversing the tree we'd hold the parent's lock until all children are fully traversed, which can be quite costly since it would lock the root monitor; however, that turned out to lead to deadlocks, so I refactored the logic), so I'm curious what others think whether this is necessary or not. Names of the monitors don't contain any PII but can contain things like "sort" or "hashjoiner" which is suggestive about the type of activity.
</blockquote></details>

This seems like a reasonable permission to have.
___
*[`pkg/util/mon/bytes_usage.go` line 280 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97657#-NPJA9o71LaS_bDWBu9O:-NPJA9o71LaS_bDWBu9P:bz1ojaj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b75027964b76aa5f0f3d3ec93bb180cacf4e8247/pkg/util/mon/bytes_usage.go#L280)):*
> ```Go
> }
> 
> // ExportTree exports the current state of the tree of monitors rooted in mm.
> ```

nit: s/mm/this BytesMonitor

(imo other uses of `mm` in the comments are fine, but this one was confusing)
___
*[`pkg/util/mon/bytes_usage.go` line 319 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97657#-NPJCQRb3y3MBNQFZin5:-NPJCQRb3y3MBNQFZin6:b-th2p6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/b75027964b76aa5f0f3d3ec93bb180cacf4e8247/pkg/util/mon/bytes_usage.go#L319)):*
> ```Go
> 	entries := append([]ExportEntry{}, entry)
> 	for _, c := range children {
> 		entries = append(entries, c.exportTree(level+1)...)
> ```

If one of the children is stopped, then we'll append nil here, is that desired behavior? It might make more sense to check if nil and only append non-nil values to `entries`.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97657)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @michae2, and @rharding6373)

___
*[`-- commits` line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97657#-NPInVwYD8SdpX9FYIQa):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

This seems like a reasonable permission to have.
</blockquote></details>

Ack, let's keep this gate then.
___
*[`pkg/util/mon/bytes_usage.go` line 319 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97657#-NPJCQRb3y3MBNQFZin5:-NPKNVmkCZy9hojAQRtq:b5b6g8y) ([raw file](https://github.com/cockroachdb/cockroach/blob/b75027964b76aa5f0f3d3ec93bb180cacf4e8247/pkg/util/mon/bytes_usage.go#L319)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

If one of the children is stopped, then we'll append nil here, is that desired behavior? It might make more sense to check if nil and only append non-nil values to `entries`.
</blockquote></details>

If a child is stopped, then `exportTree` will return a `nil` slice, so this `append` will become a no-op. I added some more comments and expanded the test to ensure that only non-empty `ExportEntry` objects are returned by `ExportTree`.

**Review by michae2 — COMMENTED** [review]
This is great! I think this will make a huge difference for observability of memory usage. Really nice.

> Reviewed 1 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97657#-:-NPLdfRsEIvTgNGnnoFQ:b-hnm0ag)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @rharding6373, and @yuzefovich)

___
*[`pkg/sql/crdb_internal.go` line 7503 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97657#-NPLZSAj21EPEje-Lon1:-NPLZSAj21EPEje-Lon2:b-mux3ap) ([raw file](https://github.com/cockroachdb/cockroach/blob/9439e6c282fea63625c3c933e9d1bbc33222bce8/pkg/sql/crdb_internal.go#L7503)):*
> ```Go
> 	comment: `node-level table listing all currently active memory monitors`,
> 	schema: `
> CREATE TABLE crdb_internal.memory_monitors (
> ```

random thought: should this be `node_memory_monitors`? (And should there be a corresponding `cluster_memory_monitors`?)
___
*[`pkg/sql/sem/builtins/builtins.go` line 7782 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97657#-NPLU7DF9KrkEQ63u4U1:-NPLU7DF9KrkEQ63u4U2:b-rk4hv5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9439e6c282fea63625c3c933e9d1bbc33222bce8/pkg/sql/sem/builtins/builtins.go#L7782)):*
> ```Go
> 				return tree.NewDString(string(humanizeutil.IBytes(int64(b)))), nil
> 			},
> 			Info:       "Converts integer memory size (in bytes) into the human-readable form.",
> ```

nit: remove "memory" (this could be used for disk space or network usage or anything else measured in bytes).
___
*[`pkg/util/mon/bytes_usage.go` line 319 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97657#-NPJCQRb3y3MBNQFZin5:-NPLQrEU88bNo-93xNoB:big2xwu) ([raw file](https://github.com/cockroachdb/cockroach/blob/b75027964b76aa5f0f3d3ec93bb180cacf4e8247/pkg/util/mon/bytes_usage.go#L319)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

If a child is stopped, then `exportTree` will return a `nil` slice, so this `append` will become a no-op. I added some more comments and expanded the test to ensure that only non-empty `ExportEntry` objects are returned by `ExportTree`.
</blockquote></details>

Because this is recursive, it will end up copying each entry `level` times to build the final level-0 slice. And we don't really need the full slice at once to create the virtual table anyway, we just need something to iterate over. For these reasons it might be worth changing `ExportTree` to take a closure instead of returning a slice, and that closure could be called with each `ExportEntry`.
___
*[`pkg/util/mon/bytes_usage.go` line 206 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97657#-NPLTfX40yqn6qcE3Sop:-NPLTfX40yqn6qcE3Soq:b6zrrk4) ([raw file](https://github.com/cockroachdb/cockroach/blob/9439e6c282fea63625c3c933e9d1bbc33222bce8/pkg/util/mon/bytes_usage.go#L206)):*
> ```Go
> 		// code path (reserveBytes() and releaseBytes()) might acquire the
> 		// parent's lock, so only locking "upwards" is allowed while keeping the
> 		// current monitor's lock.
> ```

Good catch!
___
*[`pkg/util/mon/bytes_usage.go` line 308 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97657#-NPLXm-q7FynBJF3neDW:-NPLXm-q7FynBJF3neDX:bk8hzlx) ([raw file](https://github.com/cockroachdb/cockroach/blob/9439e6c282fea63625c3c933e9d1bbc33222bce8/pkg/util/mon/bytes_usage.go#L308)):*
> ```Go
> 	entry := ExportEntry{
> 		Level:            level,
> 		Name:             string(mm.name),
> ```

suggestion: It might be nice to more formally expose the hierarchy using an ID and a parent ID, so that we could use recursive CTEs when querying `crdb_internal.memory_monitors`. (Maybe these IDs could be the addresses of the monitors cast to `uint64`?)

**Review by michae2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97657)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @rharding6373, and @yuzefovich)

___
*[`pkg/util/mon/bytes_usage.go` line 207 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97657#-NPLfNji8_NIzuIsizyN:-NPLfNji8_NIzuIsizyO:b-vdgm8l) ([raw file](https://github.com/cockroachdb/cockroach/blob/9439e6c282fea63625c3c933e9d1bbc33222bce8/pkg/util/mon/bytes_usage.go#L207)):*
> ```Go
> 		// parent's lock, so only locking "upwards" is allowed while keeping the
> 		// current monitor's lock.
> 		head *BytesMonitor
> ```

random trivia: You might already know about this, but if you like linked lists, Linux has a [really nice implementation](https://github.com/torvalds/linux/blob/master/include/linux/list.h) of an intrusive, circular doubly-linked list which you might enjoy. Because it is circular (and because of [various tricks](https://medium.com/@funfoolsuzi/doubly-linked-list-in-linux-source-and-the-container-of-macro-460442ce7215) possible in C) it doesn't need any conditionals for most list operations.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97657)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @michae2, and @rharding6373)

___
*[`pkg/sql/crdb_internal.go` line 7503 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97657#-NPLZSAj21EPEje-Lon1:-NPP2fCl1ychRYH6iHCA:b-ssy8ab) ([raw file](https://github.com/cockroachdb/cockroach/blob/9439e6c282fea63625c3c933e9d1bbc33222bce8/pkg/sql/crdb_internal.go#L7503)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

random thought: should this be `node_memory_monitors`? (And should there be a corresponding `cluster_memory_monitors`?)
</blockquote></details>

Renamed, but I'm a bit afraid of introducing the cluster level table. In particular, since each query can have dozens of monitors, a single node can have on the order of hundreds of thousands of them. Traversing that tree locally is cheap (especially so given the callback implementation of the traversal), but for the cluster level view we'd have to materialize all monitors into a single RPC response (or we'd need to implement some pagination scheme) for each remote node, so the network cost can be substantial. I want this to be backported, so I'm leaning on the side of caution here. In the future if we see that the cluster level view is desirable, we can still add it, but for now node level view seems like a big improvement on its own.
___
*[`pkg/util/mon/bytes_usage.go` line 319 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/97657#-NPJCQRb3y3MBNQFZin5:-NPOj4BDDIhSqhe-dLUg:bpzfrlx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b75027964b76aa5f0f3d3ec93bb180cacf4e8247/pkg/util/mon/bytes_usage.go#L319)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Because this is recursive, it will end up copying each entry `level` times to build the final level-0 slice. And we don't really need the full slice at once to create the virtual table anyway, we just need something to iterate over. For these reasons it might be worth changing `ExportTree` to take a closure instead of returning a slice, and that closure could be called with each `ExportEntry`.
</blockquote></details>

That's a very good point. I briefly thought about this too but decided it wasn't a big deal. I just wrote a microbenchmark, and these allocations do add up - the exponential growth in the number of monitors in a tree can make it huge! I like your idea about the callback, thanks, done.
___
*[`pkg/util/mon/bytes_usage.go` line 207 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97657#-NPLfNji8_NIzuIsizyN:-NPOE4E4AbPstzn_5ojb:bl5rvvl) ([raw file](https://github.com/cockroachdb/cockroach/blob/9439e6c282fea63625c3c933e9d1bbc33222bce8/pkg/util/mon/bytes_usage.go#L207)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

random trivia: You might already know about this, but if you like linked lists, Linux has a [really nice implementation](https://github.com/torvalds/linux/blob/master/include/linux/list.h) of an intrusive, circular doubly-linked list which you might enjoy. Because it is circular (and because of [various tricks](https://medium.com/@funfoolsuzi/doubly-linked-list-in-linux-source-and-the-container-of-macro-460442ce7215) possible in C) it doesn't need any conditionals for most list operations.
</blockquote></details>

Wow, I couldn't decipher the code without the second link, that was an interesting read, thanks!
___
*[`pkg/util/mon/bytes_usage.go` line 308 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97657#-NPLXm-q7FynBJF3neDW:-NPOrIJr5mk3MSyjisZS:b-uyq2dh) ([raw file](https://github.com/cockroachdb/cockroach/blob/9439e6c282fea63625c3c933e9d1bbc33222bce8/pkg/util/mon/bytes_usage.go#L308)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

suggestion: It might be nice to more formally expose the hierarchy using an ID and a parent ID, so that we could use recursive CTEs when querying `crdb_internal.memory_monitors`. (Maybe these IDs could be the addresses of the monitors cast to `uint64`?)
</blockquote></details>

Thanks, I like it, done (only with minor modification is that it's exposed as `int64` since the virtual table has `INT8` type, so it seems cleaner to just always use the corresponding `int64` Go type).
___
*[`pkg/util/mon/bytes_usage.go` line 479 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97657#-NPP6jLS6UM4iyPsHbD1:-NPP6jLS6UM4iyPsHbD2:b-hkyi4q) ([raw file](https://github.com/cockroachdb/cockroach/blob/1af565f6777fd970832e70d8ee97a65c87e383ae/pkg/util/mon/bytes_usage.go#L479)):*
> ```Go
> 	mm.mu.maxAllocated = 0
> 	mm.mu.curBudget = pool.MakeBoundAccount()
> 	mm.mu.stopped = false
> ```

This line is why during the demo earlier today the active queries weren't showing up. `"txn"` monitor is stopped and then started for each txn.

**Review by michae2 — CHANGES_REQUESTED** [review]
Looks good, just a few comments

> Reviewed 8 of 25 files at r1, 15 of 17 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97657#-:-NPQmOsE0vnxW479wbcQ:b-ffjigj)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @rharding6373, and @yuzefovich)

___
*[`pkg/cli/zip_table_registry.go` line 672 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97657#-NPQfUYc8vRhhU5SMoZA:-NPQfUYc8vRhhU5SMoZB:bj1mvgj) ([raw file](https://github.com/cockroachdb/cockroach/blob/1af565f6777fd970832e70d8ee97a65c87e383ae/pkg/cli/zip_table_registry.go#L672)):*
> ```Go
> 			"reserved_reserved",
> 		},
> 	},
> ```

This is going to be so useful!!
___
*[`pkg/sql/crdb_internal.go` line 7503 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97657#-NPLZSAj21EPEje-Lon1:-NPQc3AkBpymhdIgbUD6:b-1ygmrx) ([raw file](https://github.com/cockroachdb/cockroach/blob/9439e6c282fea63625c3c933e9d1bbc33222bce8/pkg/sql/crdb_internal.go#L7503)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Renamed, but I'm a bit afraid of introducing the cluster level table. In particular, since each query can have dozens of monitors, a single node can have on the order of hundreds of thousands of them. Traversing that tree locally is cheap (especially so given the callback implementation of the traversal), but for the cluster level view we'd have to materialize all monitors into a single RPC response (or we'd need to implement some pagination scheme) for each remote node, so the network cost can be substantial. I want this to be backported, so I'm leaning on the side of caution here. In the future if we see that the cluster level view is desirable, we can still add it, but for now node level view seems like a big improvement on its own.
</blockquote></details>

Thank you! Makes sense. (Yes, this is definitely a big improvement on its own!)

It looks like most other `node_` tables start with a `node_id` column. I think we should follow that convention, too.
___
*[`pkg/util/mon/bytes_usage.go` line 340 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97657#-NPQkV5sBw5s6F_6XrTZ:-NPQkV5sBw5s6F_6XrT_:b-7jdmvw) ([raw file](https://github.com/cockroachdb/cockroach/blob/1af565f6777fd970832e70d8ee97a65c87e383ae/pkg/util/mon/bytes_usage.go#L340)):*
> ```Go
> 	mm.mu.Unlock()
> 	if err := monitorStateCb(monitorState); err != nil {
> 		return err
> ```

smart
___
*[`pkg/sql/logictest/testdata/logic_test/table` line 602 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97657#-NPQgE-yCqZE_ZYwH3Fl:-NPQgE-z-R0kQnXoGHg9:b-f1pjhd) ([raw file](https://github.com/cockroachdb/cockroach/blob/1af565f6777fd970832e70d8ee97a65c87e383ae/pkg/sql/logictest/testdata/logic_test/table#L602)):*
> ```
> leases                                 NULL
> lost_descriptors_with_data             NULL
> memory_monitors                        NULL
> ```

node_memory_monitors

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97657)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @michae2, and @rharding6373)

___
*[`pkg/sql/crdb_internal.go` line 7503 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97657#-NPLZSAj21EPEje-Lon1:-NPT4tBGECSTiUlAkDS-:b-4dlakg) ([raw file](https://github.com/cockroachdb/cockroach/blob/9439e6c282fea63625c3c933e9d1bbc33222bce8/pkg/sql/crdb_internal.go#L7503)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Thank you! Makes sense. (Yes, this is definitely a big improvement on its own!)

It looks like most other `node_` tables start with a `node_id` column. I think we should follow that convention, too.
</blockquote></details>

`node_id` seems redundant now since we only have node level view. We can always change the schema later if/ when adding the cluster level view. Do you see any benefits from having this column before that?

I think in other cases where we have node and cluster level views, we just kept the schema the same for both variants by default even though we don't need the `node_id` column in the node level view case. I'm a big fan of consistency with existing precedents, but for some reason I'm leaning towards not following this particular convention since it doesn't make much sense to me and is not fully applicable to this virtual table. Thoughts?
___
*[`pkg/sql/logictest/testdata/logic_test/table` line 602 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97657#-NPQgE-yCqZE_ZYwH3Fl:-NPT6E_RBWBWb-ZdWVVA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1af565f6777fd970832e70d8ee97a65c87e383ae/pkg/sql/logictest/testdata/logic_test/table#L602)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

node_memory_monitors
</blockquote></details>

Done.

**Review by michae2 — APPROVED** [review]
:lgtm_strong: Nice work!

> Reviewed 1 of 17 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97657#-:-NPTFius3VMYCAIm_UDT:b-8m3k00)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @rharding6373)

___
*[`pkg/sql/crdb_internal.go` line 7503 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/97657#-NPLZSAj21EPEje-Lon1:-NPTEB070Nm3uMD_ezhk:boly5nz) ([raw file](https://github.com/cockroachdb/cockroach/blob/9439e6c282fea63625c3c933e9d1bbc33222bce8/pkg/sql/crdb_internal.go#L7503)):*
>  We can always change the schema later if/ when adding the cluster level view. Do you see any benefits from having this column before that?

Good point. The only benefit I see is consistency with other `node_` tables. We can leave it.

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

**Pull request merged**
