### PR TITLE
storage: place k:v pairs with floating points into another consistency checksum

### PR DESCRIPTION
**Pull request by vivekmenezes**
closes #5525 

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5525)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
> closes #5525 

you put the PR number instead of the issue number

So the plan is to ignore any hash mismatches for floating point values? Then why even bother computing a hash for them?

It also seems wrong that on the one hand, we want to tolerate systems having different representations for `float64` but on the other hand we still allow them to read from each other's representations..

Maybe the correct solution would be to not store floats at all. TimeSeriesDatapoint could use a `int64` `integer` and a `uint64` `fraction` to represent the number `integer + fraction / 2^64`.

---

Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[roachpb/api.proto, line 556 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5525#-KDdTy3YkkfG5TjeilJq:-KDdTy3YkkfG5TjeilJr:-504954776) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3dc4a3b09bd62b4536188193b0986c227dc2ca4/roachpb/api.proto#L556)):*
Checksum

---

*[roachpb/api.proto, line 559 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5525#-KDdU1Ud0QQaQbeXXJsu:-KDdU1Ud0QQaQbeXXJsv:-901504306) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3dc4a3b09bd62b4536188193b0986c227dc2ca4/roachpb/api.proto#L559)):*
differences across

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5525#-:-KDdTia_ipepwrPVSvVk:-1994615367)*

**Comment by RaduBerinde** [comment]
Hm, don't we encode using `math.Float64bits` which is documented to return the `IEEE 754 binary representation`? Why would it vary from system to system? Plus all Intel CPUs use that same format anyway..

---

Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5525#-:-KDdZ5-Szu2o3sPD6xja:-491766890)*

**Comment by vivekmenezes** [comment]
After discussing this with folks I feel I should just convert the protobufs
to not use doubles. Let me take a shot at that.

**Comment by tamird** [comment]
I think we need to have a discussion about what we are solving with this
(or another) solution.

**Comment by vivekmenezes** [comment]
I'm looking at IEEE 754 standard to see if it meets our expectations. The
Go compiler supports that standard.

**Comment by vivekmenezes** [comment]
Closing this for now.

**Pull request closed without merging**
