### PR TITLE
sql: skip flaky TestSQLStatsCompactor

### PR DESCRIPTION
**Pull request by j82w**
Informs: https://github.com/cockroachdb/cockroach/issues/102750

Release note: None

### CODE REVIEW

**Review by maryliag — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103113#-:-NVAJFJI42VA4zx49pLz:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/103113)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @j82w)

___
*[`pkg/sql/sqlstats/persistedsqlstats/compaction_test.go` line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/103113#-NVAJLrt61YXqJAeIBnv:-NVAJLrt61YXqJAeIBnw:b-o6lw3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/7dbd3e14f63ef2508fc561992fbf1cf293795c48/pkg/sql/sqlstats/persistedsqlstats/compaction_test.go#L16)):*
> ```Go
> 	"context"
> 	"fmt"
> 	"github.com/cockroachdb/cockroach/pkg/testutils/skip"
> ```

you might get a lint error with the location of this import

**Comment by j82w** [comment]
backport -r 23.1

**Comment by j82w** [comment]
blathers backport 23.1

**Pull request merged**
