### PR TITLE
row: Avoid allocations when using ConsumeKVProvider

### PR DESCRIPTION
**Pull request by miretskiy**
There is no need to allocate new KVFetcher when calling
ConsumeKVProvider repeatedly.

Issues: None
Epic: None
Release note: None

### CODE REVIEW

**Comment by miretskiy** [comment]
```
Executed 1 out of 1 test: 1 test passes.
name             old time/op    new time/op    delta
EventDecoder-10     874ns ±13%     835ns ±11%     ~     (p=0.247 n=10+10)

name             old alloc/op   new alloc/op   delta
EventDecoder-10      595B ± 1%      450B ± 1%  -24.44%  (p=0.000 n=10+10)

name             old allocs/op  new allocs/op  delta
EventDecoder-10      9.00 ± 0%      8.00 ± 0%  -11.11%  (p=0.000 n=10+10)
```

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106536#-:-N_-wE8NAm3nzxcsT5NK:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @HonoreDB, @mgartner, and @miretskiy)

___
*[`pkg/sql/row/kv_fetcher.go` line 342 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106536#-N_-w0TP0VLqwm07eURK:-N_-w0TP0VLqwm07eURL:brxtfa1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c113c131a73be4e66cff9c0172a3ad41357e61d3/pkg/sql/row/kv_fetcher.go#L342)):*
> ```Go
> 
> func (f *KVFetcher) reset(b KVBatchFetcher) {
> 	f.KVBatchFetcher = b
> ```

nit: it'be more bullet-proof to do this resetting as `*f = KVFetcher{KVBatchFetcher: b}` (in case other fields are added to the struct).

**Comment by miretskiy** [comment]
> nit: it'be more bullet-proof to do this resetting as `*f = KVFetcher{KVBatchFetcher: b}` (in case other fields are added to the struct).

done

**Review by HonoreDB — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 3 of 3 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106536)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @miretskiy)

**Pull request merged**
