### PR TITLE
roachtest: test that in a multi pod MT cluster distsql works

### PR DESCRIPTION
**Pull request by cucaroach**
Add support for creating multiple SQL instances for a tenant in
roachtest. Test that distsql properly utilizes all these instances and
that statement_timeout and statement bundles work. Also ensure that
table statistics are created.

Release justification: non-production code
Release note: None

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
Nice work! I only have minor comments, but it'd be good for @stevendanna to take a look too.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88604#-:-ND-mDIJDHVpcDWnJw16:b563ah7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @stevendanna)

___
*[`pkg/cmd/roachtest/tests/multitenant_distsql.go` line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88604#-ND-hKvTDLt2Ox7yf1lN:-ND-hKvTDLt2Ox7yf1lO:bqie5nn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffac627e4c8881f390c97c89512915b6ea79905a/pkg/cmd/roachtest/tests/multitenant_distsql.go#L37)):*
> ```Go
> 			to := timeout
> 			r.Add(registry.TestSpec{
> 				Name:    fmt.Sprintf("multitenant/distsql/instances=%d/bundle=%s/timeout=%d", numInstances, b, to),
> ```

nit: maybe `s/timeout=%d/timeout=%dms/`?
___
*[`pkg/cmd/roachtest/tests/multitenant_distsql.go` line 38 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88604#-ND-h0Hp0lwmanBuUfnT:-ND-h0Hp0lwmanBuUfnU:b-97hzzi) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffac627e4c8881f390c97c89512915b6ea79905a/pkg/cmd/roachtest/tests/multitenant_distsql.go#L38)):*
> ```Go
> 			r.Add(registry.TestSpec{
> 				Name:    fmt.Sprintf("multitenant/distsql/instances=%d/bundle=%s/timeout=%d", numInstances, b, to),
> 				Owner:   registry.OwnerKV,
> ```

nit: should we be the owners?
___
*[`pkg/cmd/roachtest/tests/multitenant_distsql.go` line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88604#-ND-ibTu2QP7aBrycn_S:-ND-ibTu2QP7aBrycn_T:b-vafkdf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffac627e4c8881f390c97c89512915b6ea79905a/pkg/cmd/roachtest/tests/multitenant_distsql.go#L107)):*
> ```Go
> 	}
> 
> 	m := c.NewMonitor(ctx, c.Node(1))
> ```

Should we monitor all nodes?
___
*[`pkg/cmd/roachtest/tests/multitenant_distsql.go` line 114 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88604#-ND-ht3f-zHgjkh6oBAg:-ND-ht3f-zHgjkh6oBAh:b-yh8gxm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffac627e4c8881f390c97c89512915b6ea79905a/pkg/cmd/roachtest/tests/multitenant_distsql.go#L114)):*
> ```Go
> 	require.NoError(t, err)
> 
> 	// Test takes too long and too much resources with default range sizes.
> ```

nit: maybe add another sentence before this one explaining that we want the table to have multiple ranges, but we don't have an easy way to do that in tenants, so instead we'll use many INSERTs below to populate the data set and rely on the reduced range sizes to speed the test up.
___
*[`pkg/cmd/roachtest/tests/multitenant_distsql.go` line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88604#-ND-jso47XMEKiEqzT4u:-ND-jQHB41_fOEHsM2w8:bxp6y0g) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffac627e4c8881f390c97c89512915b6ea79905a/pkg/cmd/roachtest/tests/multitenant_distsql.go#L146)):*
> ```Go
> 	for {
> 		time.Sleep(time.Second)
> 		res, err := inst1Conn.Query("EXPLAIN (VEC,VERBOSE) SELECT DISTINCT i FROM t")
> ```

nit: `VERBOSE` shouldn't be needed.
___
*[`pkg/cmd/roachtest/tests/multitenant_distsql.go` line 188 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88604#-ND-kdLq03seEApdPkfH:-ND-kdLq03seEApdPkfI:b-dyyktz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffac627e4c8881f390c97c89512915b6ea79905a/pkg/cmd/roachtest/tests/multitenant_distsql.go#L188)):*
> ```Go
> 	}
> 
> 	{
> ```

This block doesn't seem to be checking much - is this a leftover?
___
*[`pkg/cmd/roachtest/tests/multitenant_distsql.go` line 222 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88604#-ND-lGnv8RFwcnpVLm6b:-ND-lGnv8RFwcnpVLm6c:b-891zqy) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffac627e4c8881f390c97c89512915b6ea79905a/pkg/cmd/roachtest/tests/multitenant_distsql.go#L222)):*
> ```Go
> 			t.L().Printf(str)
> 		}
> 		// TODO(cucaroach): should we try to open bundle and verify its contents?
> ```

I think it would be nice. I remember adding a stmt bundle download step in #50253. Probably specifying the exact contents (i.e. listing all of the files) could become a little annoying in case we add more things to the bundle, but it would be great to ensure that files like `plan.txt`, `statement.sql`, `env.sql`, `schema.sql`, as well as the stats file are present.

**Comment by cucaroach** [comment]
RFAL!   Thanks!

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88604)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @stevendanna, and @yuzefovich)

___
*[`pkg/cmd/roachtest/tests/multitenant_distsql.go` line 37 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88604#-ND-hKvTDLt2Ox7yf1lN:-NDhjDbsDSzicUMfnHvh:bcoa9bh) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffac627e4c8881f390c97c89512915b6ea79905a/pkg/cmd/roachtest/tests/multitenant_distsql.go#L37)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: maybe `s/timeout=%d/timeout=%dms/`?
</blockquote></details>

@cucaroach looks like you missed this one
___
*[`pkg/cmd/roachtest/tests/multitenant_distsql.go` line 146 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88604#-ND-jso47XMEKiEqzT4u:-NDhjRBz-gZMmr2KmwDx:bcoa9bh) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffac627e4c8881f390c97c89512915b6ea79905a/pkg/cmd/roachtest/tests/multitenant_distsql.go#L146)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: `VERBOSE` shouldn't be needed.
</blockquote></details>

@cucaroach looks like you missed this one

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88604#-:-NDj54yP5zszzGvO3J3u:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @stevendanna)

___
*[`pkg/cmd/roachtest/tests/multitenant_distsql.go` line 222 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88604#-ND-lGnv8RFwcnpVLm6b:-NDj4BzpAxyqFTT8OCjk:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffac627e4c8881f390c97c89512915b6ea79905a/pkg/cmd/roachtest/tests/multitenant_distsql.go#L222)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I think it would be nice. I remember adding a stmt bundle download step in #50253. Probably specifying the exact contents (i.e. listing all of the files) could become a little annoying in case we add more things to the bundle, but it would be great to ensure that files like `plan.txt`, `statement.sql`, `env.sql`, `schema.sql`, as well as the stats file are present.
</blockquote></details>

Thanks!
___
*[`pkg/cmd/roachtest/tests/multitenant_distsql.go` line 34 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/88604#-NDj4exKCeXVTlw4JISe:-NDj4exLAZKYEq6NzxPF:bl7fuea) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6ce916358b045daf18b35c91a043680674a9697/pkg/cmd/roachtest/tests/multitenant_distsql.go#L34)):*
> ```Go
> 
> func registerMultiTenantDistSQL(r registry.Registry) {
> 	const numInstances = 2
> ```

What's the rationale for reducing the number of instances below the node count? Is it to speed up the test?

**Review by stevendanna — APPROVED** [review]
LGTM! Apologies for the delayed review.

**Review by cucaroach — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/88604#-:-NE1Jxfd8cVxie5gnM0s:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

___
*[`pkg/cmd/roachtest/tests/multitenant_distsql.go` line 107 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88604#-ND-ibTu2QP7aBrycn_S:-NE1Jc6M3eNhFjRgN9y5:b4uncx3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffac627e4c8881f390c97c89512915b6ea79905a/pkg/cmd/roachtest/tests/multitenant_distsql.go#L107)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Should we monitor all nodes?
</blockquote></details>

Last I talked to @tbg he said we only want to monitor nodes running kvstores and not MT nodes. 
___
*[`pkg/cmd/roachtest/tests/multitenant_distsql.go` line 222 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/88604#-ND-lGnv8RFwcnpVLm6b:-NE1Jvm94jVz4Kik2Trt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ffac627e4c8881f390c97c89512915b6ea79905a/pkg/cmd/roachtest/tests/multitenant_distsql.go#L222)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Thanks!
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/tests/multitenant_distsql.go` line 34 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/88604#-NDj4exKCeXVTlw4JISe:-NDowDYtC6Xrf6y3sd_C:bdb8b0r) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6ce916358b045daf18b35c91a043680674a9697/pkg/cmd/roachtest/tests/multitenant_distsql.go#L34)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

What's the rationale for reducing the number of instances below the node count? Is it to speed up the test?
</blockquote></details>

Scapel left in patient!   Was testing out the bundle stuff, thanks for catching!

**Pull request merged**
