### PR TITLE
schemachanger,scbuild: add transient constraint to validate computed column 

### LINKED ISSUE #81698: sql: computed columns are not validated on existing data
**Describe the problem**

We don't currently evaluate computed expressions for new virtual computed columns to ensure that they
are indeed valid for all of the data in the table. This is a major oversight.

**To Reproduce**

```sql
CREATE TABLE t (i INT PRIMARY KEY);
INSERT INTO t VALUES (1);
```

```sql
ALTER TABLE t ADD COLUMN s VARCHAR(2) AS ('stored') STORED;
ALTER TABLE t ADD COLUMN v VARCHAR(2) AS ('virtual') VIRTUAL;
```

```sql
SELECT * FROM t;
```
```
  i |   s    |    v
----+--------+----------
  1 | stored | virtual
```

```sql
INSERT INTO t VALUES (2);
ERROR: value too long for type VARCHAR(2)
SQLSTATE: 22001
```

**Expected behavior**

We should fail to add these columns.

Jira issue: CRDB-16484

Epic CRDB-31282

### PR DESCRIPTION
**Pull request by rafiss**
fixes #81698

### schemaexpr: add assignment cast to computed column if types differ

In 4235a7a we changed default
expressions to use an assignment cast if the type differs. This made it
so values that are inserted during a backfill are validated to fit
within the size constraint of the data type (e.g. VARCHAR(2)).

This patch does the same for computed columns, which also need the same
validation.

Release note (bug fix): Previously, if a STORED computed column was
added and it was a fixed-size type such as VARCHAR(2), the computed
values would not be checked to make sure they were not too large for the
type. Now this validation is performed, which prevents an invalid
computed column definition from being added to a table.

###  scbuild: add transient constraint to validate comoputed column

This is implemented using the same approach we took to validate type
changes in ALTER COLUMN TYPE when the size of the type changed.

Release note (bug fix): Previously, if a VIRTUAL computed column was
added and it was a fixed-size type such as VARCHAR(2), the computed
values would not be checked to make sure they were not too large for the
type. Now this validation is performed, which prevents an invalid
computed column definition from being added to a table.

###  optbuilder: use assignment cast for computed columns

This resolves a TODO that required logic to validate computed columns to
be in place.

### CODE REVIEW

**Review by spilchen — COMMENTED** [review]
I like the approach you've taken—just had a couple of minor questions.

> Reviewed 2 of 2 files at r1, 3 of 3 files at r2, 16 of 34 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137299#-:-OE-UHi-6YJHwSdIe9g9:b-y0lk8t)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @rafiss)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go` line 202 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/137299#-OE-S2QH-LemK_UaZQuL:-OE-S2QH-LemK_UaZQuM:b-y7utx7) ([raw file](https://github.com/cockroachdb/cockroach/blob/d75099a425a175c7e0321f9a27c1a66c06e4aeab/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go#L202)):*
> ```Go
> 		}
> 		checkExpr, err := parser.ParseExpr(fmt.Sprintf(
> 			"CASE WHEN (crdb_internal.assignment_cast(%s, NULL::%s)) IS NULL THEN TRUE ELSE TRUE END",
> ```

The `THEN TRUE ELSE TRUE END` construct seems unusual. Are there scenarios where the call to `assignment_cast` might return a value other than `NULL`? 

I assume that if the constraint is violated, the expression would fail with an error. It might be worthwhile to point out that behaviour in a comment.
___
*[`pkg/sql/catalog/schemaexpr/computed_column.go` line 259 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137299#-OE-Q-5YBvagf1oFzi5J:-OE-Q-5YBvagf1oFzi5K:bw56jx9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7c5dc0afaf854bee1438731386c4b3eee594337/pkg/sql/catalog/schemaexpr/computed_column.go#L259)):*
> ```Go
> 		// If the expression has a type that is not identical to the
> 		// column's type, wrap the computed column expression in an assignment cast.
> 		if !typedExpr.ResolvedType().Identical(col.GetType()) {
> ```

nit: this looks like it's an exact duplicate of the code in `default_exprs.go`. Perhaps maybe modularize that to cut down on the duplication?
___
*[`pkg/sql/catalog/schemaexpr/computed_column.go` line 259 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137299#-OE-Qz118ZeHNGJsEJQ7:-OE-Qz118ZeHNGJsEJQ8:b6d93ct) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7c5dc0afaf854bee1438731386c4b3eee594337/pkg/sql/catalog/schemaexpr/computed_column.go#L259)):*
> ```Go
> 		// If the expression has a type that is not identical to the
> 		// column's type, wrap the computed column expression in an assignment cast.
> 		if !typedExpr.ResolvedType().Identical(col.GetType()) {
> ```

I was looking for similar code for the `ON UPDATE` expressions, but I couldn't find it. Is it needed for that too?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137299)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @spilchen)

___
*[`pkg/sql/catalog/schemaexpr/computed_column.go` line 259 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137299#-OE-Q-5YBvagf1oFzi5J:-OE0UOi7BEZWrer0LVVd:b-a3xfdq) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7c5dc0afaf854bee1438731386c4b3eee594337/pkg/sql/catalog/schemaexpr/computed_column.go#L259)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

nit: this looks like it's an exact duplicate of the code in `default_exprs.go`. Perhaps maybe modularize that to cut down on the duplication?
</blockquote></details>

good idea. i'll add that as an additional commit.
___
*[`pkg/sql/catalog/schemaexpr/computed_column.go` line 259 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137299#-OE-Qz118ZeHNGJsEJQ7:-OE0V1GKB3Hyy4cC9qKZ:b-lldzc4) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7c5dc0afaf854bee1438731386c4b3eee594337/pkg/sql/catalog/schemaexpr/computed_column.go#L259)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

I was looking for similar code for the `ON UPDATE` expressions, but I couldn't find it. Is it needed for that too?
</blockquote></details>

i don't think so, since those don't cause a backfill. we only need to check those while running an `UPDATE`. I will add a test case for it to make sure it's blocked correctly.
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go` line 202 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/137299#-OE-S2QH-LemK_UaZQuL:-OE0TfMWATbS7vZv698N:b-ei1xzi) ([raw file](https://github.com/cockroachdb/cockroach/blob/d75099a425a175c7e0321f9a27c1a66c06e4aeab/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go#L202)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

The `THEN TRUE ELSE TRUE END` construct seems unusual. Are there scenarios where the call to `assignment_cast` might return a value other than `NULL`? 

I assume that if the constraint is violated, the expression would fail with an error. It might be worthwhile to point out that behaviour in a comment.
</blockquote></details>

The behavior of assignment casts is that they error is the value doesn't fit in the given reference type. E.g.:
```
root@localhost:26257/defaultdb> select crdb_internal.assignment_cast('abc', null::varchar(2));
ERROR: value too long for type VARCHAR(2)
SQLSTATE: 22001
```

I went with the `THEN TRUE ELSE TRUE END` just because i wanted an expression that would return true for every row (since CHECK constraint expressions must be a boolean), but would also run the assignment cast for every row.

I'll rephrase the above comment to:
```
		// To validate, we add a transient check constraint. It uses an assignment
		// cast to verify that the computed column expression fits in to the column
		// type. This constraint is temporary and doesn't need to persist beyond the
		// ALTER operation. The CHECK expression returns true for every row, but since
		// it uses `assignment_cast`, the expression will fail with an error if a row is invalid. 
```

**Review by spilchen — APPROVED** [review]
:lgtm: Thanks for revising.

> Reviewed 41 of 41 files at r6, 34 of 34 files at r7, 6 of 6 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137299#-:-OE0n7OE5iKCCdDMytwd:b-wu8612)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball)

**Comment by rafiss** [comment]
TFTR!

bors r+

**Pull request merged**
