### PR TITLE
sqlccl: support INCREMENTAL BACKUP of added/changed tables

### PR DESCRIPTION
**Pull request by dt**
Require that a table be present in a previous backup to include it in a new backup or that the parent of a table is included in the completely backed up DBs.
This means that 'BACKUP a TO x' + 'BACKUP a, b TO y INCREMENTAL FROM x' is still not allowed, but the expected case of, say, periodic 'BACKUP DATABASE' should handle a new table being added or an index on an existing table.

When checking for span coverage from previous backups, if a span is uncovered from time zero, instead of returning an error we mark it as a needing to be *non*-incrementally backed up.
Non-incremental spans are exported from time zero to the start time (in addtition to the usual start to end time) and are tracked in a new, separate field to allow them to be injected when determining the covering.

Finally, we never want to appear to successfully generate a backup that someone later discovers cannot be used to RESTORE, so we add a sanity check, after determining what spans (including these new non-incremental spans) a backup will cover, that uses the RESTORE logic to check that that backup, along with any previous backups, cover as required by RESTORE.

Release note: Allow INCREMENTAL backup of a database after a table or index is added.

### CODE REVIEW

**Comment by dt** [comment]
I have a couple follow-up changes for `AS OF SYSTEM` time that use some of the changes here, so if anyone gets a chance to look at this, would be appreciated. In particular, if anyone has suggestions for more test cases.

**Comment by mjibson** [comment]
I see there's already a test with TRUNCATE. Why did that work before this change?

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/ccl/sqlccl/restore.go, line 421 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21170#-L2MD54eE9bftjxr2UKW:-L2MD54eE9bftjxr2UKX:b-2sxfsg) ([raw file](https://github.com/cockroachdb/cockroach/blob/276c16e13dd72dc704c76951e113c93bb962536a/pkg/ccl/sqlccl/restore.go#L421)):*
> ```Go
> func errOnMissingRange(span intervalccl.Range, start, end hlc.Timestamp) error {
> 	return errors.Errorf(
> 		"no backup covers time [%s,%s) for range [%s,%s) (or backups out of order)",
> ```

I'm not exactly sure what "out of order" means. Does the user have to specify backups in a restore in the correct order?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21170#-:-L2ME4ARNdXbEh3AuTZq:b-tgilxh)*

**Comment by dt** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/sqlccl/backup_test.go, line 2464 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21170#-L2MQx2NN22K9MeFwaza:-L2MQx2OmYZTymdLj0fc:b-ank95m) ([raw file](https://github.com/cockroachdb/cockroach/blob/84cf799f4ddece757614e5eb9708a0069315d9ef/pkg/ccl/sqlccl/backup_test.go#L2464)):*
> ```Go
> 
> 	if _, err := sqlDB.DB.Exec("BACKUP DATABASE data TO $1 INCREMENTAL FROM $2", inc, full); !testutils.IsError(
> 		err, "a new full backup may be required",
> ```

After truncate was returning an error right here, which went away after this change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21170)*

**Comment by dt** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/sqlccl/restore.go, line 421 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21170#-L2MD54eE9bftjxr2UKW:-L2R9Rg8QuFTjne8LQct:bo510za) ([raw file](https://github.com/cockroachdb/cockroach/blob/276c16e13dd72dc704c76951e113c93bb962536a/pkg/ccl/sqlccl/restore.go#L421)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

I'm not exactly sure what "out of order" means. Does the user have to specify backups in a restore in the correct order?
</blockquote></details>

Yep. More specifically, our docs say "Lists of incremental backups must be sorted from oldest to newest."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21170)*

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21170#-:-L2Rf3GRkm9zonfh8zJG:bnfp4nl)*

**Pull request merged**
