### PR TITLE
storage/rangefeed: strip incompatible information from RangeFeedEvents

### LINKED ISSUE #43967: rangefeed: missing data after merge
When I enable merges in the new kvnemeses test (#43565), it complains that some of the committed puts didn't come out of rangefeed. The test is still new so it's possibly an issue in the test, but the more I look into this, the more it looks like a bug in RangeFeed, so I want to get some more eyeballs on it. Here's a history with some additional logging:

A range merges at some key "77ee96b8" and both halves of the rangefeed disconnect

```
I200114 16:11:13.919750 1291 kv/dist_sender_rangefeed.go:223  [n1] WIP disconnected /Table/50/"ae4022a9"-/Table/51: retry rangefeed (REASON_RANGE_MERGED)
I200114 16:11:13.919906 1350 kv/dist_sender_rangefeed.go:223  [n1] WIP disconnected /Table/50/"77ee96b8"-/Table/50/"ae4022a9": retry rangefeed (REASON_RANGE_MERGED)
```

Both halves attempt to reconnect, the previous-rhs fails with "r29 not found on s1" but the previous-lhs succeeds. The previous-rhs is not tried again.

```
I200114 16:11:13.920050 1265 kv/dist_sender_rangefeed.go:221  [n1] WIP connecting /Table/50/"ae4022a9"-/Table/51
I200114 16:11:13.920095 1265 kv/dist_sender_rangefeed.go:223  [n1] WIP disconnected /Table/50/"ae4022a9"-/Table/51: r29 was not found on s1
I200114 16:11:13.920257 1379 kv/dist_sender_rangefeed.go:221  [n1] WIP connecting /Table/50/"77ee96b8"-/Table/50/"ae4022a9"
```

A change is not emitted because it doesn't overlap with the args.Span in the RangeFeed request (the previous-lhs), which is used in the RangeFeed registration

```
I200114 16:11:13.925278 1381 storage/rangefeed/registry.go:449  WIP key /Table/50/"de94d5bc" 1579018273.905537000,0 didn't overlap registered spans: /Table/50/"77ee96b8"-/Table/50/"ae4022a9"
```

A resolved timestamp is emitted for the entire keyspace of the new range to the RangeFeed that's only registered for the span of the previous-lhs

```
I200114 16:11:13.934671 1379 kv/dist_sender_rangefeed.go:281  WIP got resolved /Table/50/"77ee96b8"-/Max from rangefeed /Table/50/"77ee96b8"-/Table/50/"ae4022a9"
```

I think the bug here is that the resolved timestamp spans should be trimmed to the registration span they're being emitted to. I'm not sure yet why we haven't seen this in the changefeed nemeses test, but it seems to reproduce much more readily when `kv.closed_timestamp.target_duration` is set to 1ms, which we can't do in that test.

### PR DESCRIPTION
**Pull request by nvb**
Fixes #43967.

This commit adds a step before publishing RangeFeedEvents to RangeFeed registrations where incompatible information in the events is stripped from the event. There are two cases where this comes up at the moment:

The first is with previous values. If no registrations for the current Range are requesting previous values, then we won't even retrieve them on the Raft goroutine. However, if any are and they overlap with an update then the previous value on the corresponding events will be populated. If we're in this case and any other registrations don't want previous values then we'll need to strip them.

The second is with the key spans in checkpoint events. Checkpoint events are always created spanning the entire Range. However, a registration might not be listening on updates over the entire Range. If this is the case then we need to constrain the checkpoint events published to that registration to just the span that it's listening on. This is more than just a convenience to consumers - it would be incorrect to say that a rangefeed has observed all values up to the checkpoint timestamp over a given key span if any updates to that span have been filtered out.

Release note (bug fix): CDC is no longer susceptible to a bug where a resolved timestamp might be published before all events that precede it have been published in the presence of a Range merge.

### CODE REVIEW

**Review by danhhz — COMMENTED** [review]
:lgtm: thanks for the fix!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44035#-:-LyfDOxR75YH3xp0RigK:b-rsz3om)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz and @nvanbenschoten)

___
*[pkg/roachpb/api.go, line 1185 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44035#-LyfClG0CRwyAp1ot_hk:-LyfClG0CRwyAp1ot_hl:b2beiwi) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0e99d24701c30e2ab632b6e08ef3394d5f26eea/pkg/roachpb/api.go#L1185)):*
> ```Go
> // ShallowCopy returns a shallow copy of the receiver and its variant type.
> func (e *RangeFeedEvent) ShallowCopy() *RangeFeedEvent {
> 	copy := *e
> ```

nit: should we call this something other than copy (go predeclared identifier seems to mess with reviewable highlighting and possible others)? 
___
*[pkg/storage/rangefeed/registry.go, line 197 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44035#-LyfCYSL42CIH0c1WrjE:-LyfCYSL42CIH0c1WrjF:b-ixrghb) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0e99d24701c30e2ab632b6e08ef3394d5f26eea/pkg/storage/rangefeed/registry.go#L197)):*
> ```Go
> 			}
> 			t = copyOnWrite().(*roachpb.RangeFeedCheckpoint)
> 			t.Span = r.span
> ```

wanna throw a mention in processor.newCheckpointEvent that the span gets trimmed here (if necessary)?

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44035)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/roachpb/api.go, line 1185 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44035#-LyfClG0CRwyAp1ot_hk:-LyfF2GT0SsBkCovAWrI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0e99d24701c30e2ab632b6e08ef3394d5f26eea/pkg/roachpb/api.go#L1185)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

nit: should we call this something other than copy (go predeclared identifier seems to mess with reviewable highlighting and possible others)? 
</blockquote></details>

Done.
___
*[pkg/storage/rangefeed/registry.go, line 197 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/44035#-LyfCYSL42CIH0c1WrjE:-LyfFeIBCtJXnPdiSS-O:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0e99d24701c30e2ab632b6e08ef3394d5f26eea/pkg/storage/rangefeed/registry.go#L197)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

wanna throw a mention in processor.newCheckpointEvent that the span gets trimmed here (if necessary)?
</blockquote></details>

Done.

**Comment by danhhz** [comment]
Do you want to do the backport or shall I?

**Comment by nvanbenschoten** [comment]
> Do you want to do the backport or shall I?

I'll take care of the backport. Thanks for the reminder.

**Pull request merged**
