### PR TITLE
fix MVCCStats age computations

### LINKED ISSUE #3234: {GCBytes,Intent}Age calculations are broken
In `MergeMVCCStats` function, we have:
```
	diffSeconds := nowNanos/1E9 - rs.LastUpdateNanos/1E9
	ms.LastUpdateNanos = nowNanos
	ms.IntentAge += rs.IntentCount * diffSeconds
	ms.GCBytesAge += engine.MVCCComputeGCBytesAge(rs.KeyBytes+rs.ValBytes-rs.LiveBytes, diffSeconds)
	rs.MVCCStats.Add(ms)
```
And in `rs.MVCCStats.Add(ms)` we have:
```
...
	if oms.LastUpdateNanos > ms.LastUpdateNanos {
		ms.LastUpdateNanos = oms.LastUpdateNanos
	}
```
So, when update `ms.LastUpdateNanos`, we check whether `oms.LastUpdateNanos` greater than `ms.LastUpdateNanos`. But when calculate `diffSeconds`, we don't make any check. (`rs.LastUpdateNanos` and `ms.LastUpdateNanos` in `rs.MVCCStats.Add(ms)` is the same variable)
As a result, I often see minus `diffSeconds` in my test, then ms.IntentAge will be minus(can be smaller than -10000 in busy range, because `rs.IntentCount * diffSeconds` will amplify minus diffSeconds again and again).

I'm not sure whether it is a problem, because after a long time, it can turn to positive number based on `elapsedSeconds`. But if I want to make intent GC start in a short time rather than very long time(24 hours currently), it will be a obstacle.

### PR DESCRIPTION
**Pull request by tbg**
Previously, stats objects were mostly treated as additive ad-hoc,
though the age components can only be added or subtracted
if they correspond to the same LastUpdateNanos. This wasn't
the case in various locations.
To mitigate this, added an `AgeTo` method which performs this,
and am now calling it in `Add` and `Subtract` appropriately.

Also fixed a bug in the C++ code (which unfortunately duplicates
much of the logic for a (slightly) special case). The code is
potentially still incorrect, though - I have to revisit the
assumptions. Basically, we need the guarantee that whichever
timestamp ComputeStats is called with is also larger than any
MVCC timestamp in the scanned range. I'll send a separate fix
for that when this one is done.

Converted the low-level MVCC operations to correctly compute MVCCStats.
Instead of the old strategy (compute ad-hoc ages everywhere and trust
that someone would update LastUpdateNanos in the right places), use
the AgeTo helper. For each type of update, identify the various time
intervals over which the contributions need to be accounted for, and
use AgeTo to adjust the GC and intent ages automatically. This is a
pleasant simplification, and also has the side effect that the existing
test coverage now has to deal with more realistic aging of values
(on top of having simplified as well).

For MVCCResolve{,Range}, don't use the batch request's timestamp.
All that matters is the timestamp of the transaction involved.
Previously, the batch timestamp was used for MVCCStats computations,
which is incorrect. Its absence also lends more clarity to the code
as such.

Commit-by-commit is recommended.

Fixes #3234.

@petermattis, assigning you since you've looked at #3234.
@spencerkimball, your eyeballs also appreciated. I don't want to have
to revisit this again for a while.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3867)

### CODE REVIEW

**Comment by petermattis** [comment]
Wow, this looked super painful. I'm glad you tackled it. 

---

Reviewed 1 of 1 files at r1, 6 of 6 files at r2, 17 of 17 files at r3, 4 of 4 files at r4, 1 of 1 files at r5, 5 of 5 files at r6.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[storage/engine/mvcc.go, line 143 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K84XkA8Z7g8frNClHK9:-K84XkA8Z7g8frNClHKA:1316334394) ([raw file](https://github.com/cockroachdb/cockroach/blob/9657e9d5e4f2692c2f5d91328ac7e3aaf12712e9/storage/engine/mvcc.go#L143)):*
`oms` can be a value instead of a pointer.

---

*[storage/engine/mvcc.go, line 161 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K84Y-yLAbAMM5s_KIKA:-K84Y-yLAbAMM5s_KIKB:-1691934314) ([raw file](https://github.com/cockroachdb/cockroach/blob/9657e9d5e4f2692c2f5d91328ac7e3aaf12712e9/storage/engine/mvcc.go#L161)):*
`MVCCComputeGCBytesAge` isn't too interesting now. I think this code would appear more symmetric with:

```
ms.GCBytes += ms.GCBytes() * diffSeconds
```

Alternately, use a common function for both `GCBytesAge` and `IntentAge` calculation.

---

*[storage/engine/mvcc.proto, line 54 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K84YOR32Ij2tty7B42N:-K84YOR32Ij2tty7B42O:959725586) ([raw file](https://github.com/cockroachdb/cockroach/blob/9657e9d5e4f2692c2f5d91328ac7e3aaf12712e9/storage/engine/mvcc.proto#L54)):*
`s/GCable/GC-able/g` (otherwise I see the word "cable")

---

*[storage/engine/mvcc.proto, line 66 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K84YiRYlqqhN-bb09oe:-K84YiRYlqqhN-bb09of:-205190033) ([raw file](https://github.com/cockroachdb/cockroach/blob/9657e9d5e4f2692c2f5d91328ac7e3aaf12712e9/storage/engine/mvcc.proto#L66)):*
Love the additional commenting in this file.

---

*[storage/engine/rocksdb.go, line 599 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K84XHW-f-xOuCVNCJ07:-K84XHW-f-xOuCVNCJ08:1072192398) ([raw file](https://github.com/cockroachdb/cockroach/blob/36a4a63438b5be2253bcb9624a8c36c23ccfbab1/storage/engine/rocksdb.go#L599)):*
Is this comment correct? Since `MVCCStats` is guaranteed empty I think all of these `+=` can be `=`.

Heh, and I see the next commit fixes this.

---

*[storage/engine/rocksdb/db.cc, line 1548 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K84YwKnYpUHWz4FZqIL:-K84YwKnYpUHWz4FZqIM:-1675756801) ([raw file](https://github.com/cockroachdb/cockroach/blob/9657e9d5e4f2692c2f5d91328ac7e3aaf12712e9/storage/engine/rocksdb/db.cc#L1548)):*
This is a subtle change. Add a comment so that it doesn't get accidentally reverted. And perhaps add a helper function for use in the similar computation below.

---

*[storage/engine/rocksdb_test.go, line 465 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K84adYkziBOYFCK3CjY:-K84adYl7ihwf1DuE6Hl:753395594) ([raw file](https://github.com/cockroachdb/cockroach/blob/005d7430e4f63aa5b92175f63b963046826d8ea2/storage/engine/rocksdb_test.go#L465)):*
Why this change?

---

*[storage/replica_command.go, line 1353 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K84XQ7uTRRryd-3JH5X:-K84XQ7uTRRryd-3JH5Y:945476707) ([raw file](https://github.com/cockroachdb/cockroach/blob/36a4a63438b5be2253bcb9624a8c36c23ccfbab1/storage/replica_command.go#L1353)):*
Does `MVCCStats.Add` need to take an `*MVCCStats` argument, or can it take an `MVCCStats`?

Again, I see you fixed this in the next commit.

---

*[storage/stats.go, line 112 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K84ZNwA2a2DO8ta-SdA:-K84ZNwA2a2DO8ta-SdB:668755920) ([raw file](https://github.com/cockroachdb/cockroach/blob/9657e9d5e4f2692c2f5d91328ac7e3aaf12712e9/storage/stats.go#L112)):*
This mutates `rangeStats`. Would it be safer to make a copy?

---

*[storage/stats.go, line 123 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K84ZX2rx8mjbs1R_iNS:-K84ZX2rx8mjbs1R_iNT:-789512290) ([raw file](https://github.com/cockroachdb/cockroach/blob/9657e9d5e4f2692c2f5d91328ac7e3aaf12712e9/storage/stats.go#L123)):*
See above comment about `GetAvgIntentAge`.

---

*[util/testing.go, line 213 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K84_2e5ol3ZS8H2gKpu:-K84_2e5ol3ZS8H2gKpv:-1055674585) ([raw file](https://github.com/cockroachdb/cockroach/blob/388c509d4a2ad166133b205aec27d6b6c1ef90da/util/testing.go#L213)):*
Is this used outside of testing code? Perhaps it should go in `testutils` instead.

---

*[util/testing.go, line 216 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K84_FPpFl41lkS1Tfn4:-K84_FPpFl41lkS1Tfn5:-35825141) ([raw file](https://github.com/cockroachdb/cockroach/blob/388c509d4a2ad166133b205aec27d6b6c1ef90da/util/testing.go#L216)):*
I'm curious why you have to compare each field separately. I would think you could create a zero value of the struct underlying the interface and use `reflect.DeepEqual(v, zero.Interface())`. Perhaps add a `TODO(peter)` to investigate simplifying here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-:-K84amaJE61N9gilBJh9:-2074973847)*

**Comment by spencerkimball** [comment]
LGTM

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1, 6 of 6 files at r2, 17 of 17 files at r3, 4 of 4 files at r4, 1 of 1 files at r5, 5 of 5 files at r6.
Review status: all files reviewed at latest revision, 31 unresolved discussions.

---

*[roachpb/data.go, line 818 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K85jXnOs1_3hr0sXevy:-K85jXnOs1_3hr0sXevz:-1535811150) ([raw file](https://github.com/cockroachdb/cockroach/blob/52edbe411e2257b39ab6a34fa768e3e88ca9e8e3/roachpb/data.go#L818)):*
how come this is no longer a problem?

---

*[storage/engine/mvcc.go, line 138 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K85b3lKxk_4-fnCTdQX:-K85b3lKxk_4-fnCTdQY:123985261) ([raw file](https://github.com/cockroachdb/cockroach/blob/9657e9d5e4f2692c2f5d91328ac7e3aaf12712e9/storage/engine/mvcc.go#L138)):*
`ms` can be a value instead of a pointer

---

*[storage/engine/mvcc.go, line 144 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K85bCRA1H9-1GtudNj7:-K85bCRA1H9-1GtudNj8:-451424159) ([raw file](https://github.com/cockroachdb/cockroach/blob/9657e9d5e4f2692c2f5d91328ac7e3aaf12712e9/storage/engine/mvcc.go#L144)):*
`ms` can be a value instead of a pointer.

---

*[storage/engine/mvcc.go, line 154 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K85bL-5qZTRoBwkII2i:-K85bL-5qZTRoBwkII2j:-158104217) ([raw file](https://github.com/cockroachdb/cockroach/blob/9657e9d5e4f2692c2f5d91328ac7e3aaf12712e9/storage/engine/mvcc.go#L154)):*
s/LastUpdateNanos/ms.LastUpdateNanos/

---

*[storage/engine/mvcc.go, line 159 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K85dAjD0mrN8JbUPy3a:-K85dAjD0mrN8JbUPy3b:-878373283) ([raw file](https://github.com/cockroachdb/cockroach/blob/9657e9d5e4f2692c2f5d91328ac7e3aaf12712e9/storage/engine/mvcc.go#L159)):*
nit: does it matter if this is `(nowNanos - ms.LastUpdateNanos)/1E9` instead? minor rounding difference.

Ah, I see this is called out in the proto comment.

---

*[storage/engine/mvcc.go, line 161 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K84Y-yLAbAMM5s_KIKA:-K85d4ssJ7lCBKjE5_3h:5172523) ([raw file](https://github.com/cockroachdb/cockroach/blob/9657e9d5e4f2692c2f5d91328ac7e3aaf12712e9/storage/engine/mvcc.go#L161)):*
+1

---

*[storage/engine/mvcc.go, line 168 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K85dSkEVtoHYtbOJKZI:-K85dSkEVtoHYtbOJKZJ:-1716544824) ([raw file](https://github.com/cockroachdb/cockroach/blob/9657e9d5e4f2692c2f5d91328ac7e3aaf12712e9/storage/engine/mvcc.go#L168)):*
Following the example of e.g. `time.Time`, I think `ms` should be a value, not a pointer, and that this method should return an `MVCCStats`. WDYT?

---

*[storage/engine/mvcc.go, line 189 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K85dgrzRZJya4S_hCs7:-K85dgrzRZJya4S_hCs8:281304340) ([raw file](https://github.com/cockroachdb/cockroach/blob/9657e9d5e4f2692c2f5d91328ac7e3aaf12712e9/storage/engine/mvcc.go#L189)):*
Subtract probably doesn't add!

---

*[storage/engine/mvcc.go, line 191 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K85dje4jUTn05hCmn8H:-K85dje4jUTn05hCmn8I:1157921616) ([raw file](https://github.com/cockroachdb/cockroach/blob/9657e9d5e4f2692c2f5d91328ac7e3aaf12712e9/storage/engine/mvcc.go#L191)):*
ditto re value receiver

---

*[storage/engine/mvcc.go, line 213 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K85lN76dQN7GlIftElW:-K85lN76dQN7GlIftElX:1855069106) ([raw file](https://github.com/cockroachdb/cockroach/blob/005d7430e4f63aa5b92175f63b963046826d8ea2/storage/engine/mvcc.go#L213)):*
is keys.LocalMax not itself local?

---

*[storage/engine/mvcc.proto, line 51 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K85dq1lxbcvDVFA4T0P:-K85dq1lxbcvDVFA4T0Q:-2084706644) ([raw file](https://github.com/cockroachdb/cockroach/blob/9657e9d5e4f2692c2f5d91328ac7e3aaf12712e9/storage/engine/mvcc.proto#L51)):*
nit: oxford comma?

---

*[storage/engine/mvcc_test.go, line 121 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K85k0EXjegedYfWbush:-K85k0EYarGZKs52a5Zk:-489548808) ([raw file](https://github.com/cockroachdb/cockroach/blob/6641bdf5a657247d26585924ffe9f085d26ba2cd/storage/engine/mvcc_test.go#L121)):*
I think this would read nicer if it were checking `goldMS` and followed its declaration.

---

*[storage/engine/mvcc_test.go, line 151 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K85kGzvgmba0lLuuUpU:-K85kGzvgmba0lLuuUpV:-524567357) ([raw file](https://github.com/cockroachdb/cockroach/blob/6641bdf5a657247d26585924ffe9f085d26ba2cd/storage/engine/mvcc_test.go#L151)):*
It would be nice to log some extra numbers here - `ns`, at least. also, i think this could be an `Errorf`.

---

*[storage/engine/mvcc_test.go, line 153 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K85kWe3Wg25Sa-1s6dj:-K85kWe3Wg25Sa-1s6dk:-613709644) ([raw file](https://github.com/cockroachdb/cockroach/blob/6641bdf5a657247d26585924ffe9f085d26ba2cd/storage/engine/mvcc_test.go#L153)):*
nit: mirror what this code looks like elsewhere with `shouldAge := (ns/1E9 - oldDelta.LastUpdateNanos/1E9) > 0

---

*[storage/engine/mvcc_test.go, line 154 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K85kl-WnwT5bTWyOe4R:-K85kl-WnwT5bTWyOe4S:-1789038815) ([raw file](https://github.com/cockroachdb/cockroach/blob/6641bdf5a657247d26585924ffe9f085d26ba2cd/storage/engine/mvcc_test.go#L154)):*
yikes, this is hard to read. can you add a `didAge` local?

---

*[storage/engine/rocksdb.go, line 591 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K85ftwGZjX3y_sWbDSF:-K85ftwGZjX3y_sWbDSG:327826849) ([raw file](https://github.com/cockroachdb/cockroach/blob/9657e9d5e4f2692c2f5d91328ac7e3aaf12712e9/storage/engine/rocksdb.go#L591)):*
nit: maybe a literal would read nicer here. I don't feel strongly.

---

*[storage/engine/rocksdb/db.cc, line 1548 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K84YwKnYpUHWz4FZqIL:-K85g3kQtmvL9J2SD8Xi:854996989) ([raw file](https://github.com/cockroachdb/cockroach/blob/9657e9d5e4f2692c2f5d91328ac7e3aaf12712e9/storage/engine/rocksdb/db.cc#L1548)):*
This is called out in the proto comment, but I agree that there should be an "N.B." here and in `AgeTo`

---

*[storage/engine/rocksdb_test.go, line 572 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K85adOMfRkXj518MGC9:-K85adOMfRkXj518MGCA:-1235520626) ([raw file](https://github.com/cockroachdb/cockroach/blob/36a4a63438b5be2253bcb9624a8c36c23ccfbab1/storage/engine/rocksdb_test.go#L572)):*
does this provide any value? if not, you can make `stats, err =` -> `stats, err :=` above

---

*[storage/gc_queue.go, line 113 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K85gN2eAn-oZWFywNWe:-K85gN2eAn-oZWFywNWf:1313663657) ([raw file](https://github.com/cockroachdb/cockroach/blob/9657e9d5e4f2692c2f5d91328ac7e3aaf12712e9/storage/gc_queue.go#L113)):*
what's this about?

---

*[storage/gc_queue_test.go, line 65 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K85gat1_atBCSXDui65:-K85gat1_atBCSXDui66:1440424981) ([raw file](https://github.com/cockroachdb/cockroach/blob/9657e9d5e4f2692c2f5d91328ac7e3aaf12712e9/storage/gc_queue_test.go#L65)):*
FYI this can also be nil (and I have seen it happen in various stress tests, though I don't know why that would be racy).

---

*[storage/replica.go, line 1388 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K85hEaGpW_kg9A27ZFF:-K85hEaGpW_kg9A27ZFG:-1963178899) ([raw file](https://github.com/cockroachdb/cockroach/blob/9657e9d5e4f2692c2f5d91328ac7e3aaf12712e9/storage/replica.go#L1388)):*
Is it intended that this mutates `ms`? ISTM that `ms` should be passed in as a value.

---

*[storage/stats.go, line 112 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K84ZNwA2a2DO8ta-SdA:-K85hypdvM5KgfY0S2YG:677917432) ([raw file](https://github.com/cockroachdb/cockroach/blob/9657e9d5e4f2692c2f5d91328ac7e3aaf12712e9/storage/stats.go#L112)):*
Perhaps make the receiver a value.

---

*[storage/stats.go, line 123 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K84ZX2rx8mjbs1R_iNS:-K85i0rwMR-34rD5cYqX:58274876) ([raw file](https://github.com/cockroachdb/cockroach/blob/9657e9d5e4f2692c2f5d91328ac7e3aaf12712e9/storage/stats.go#L123)):*
value receiver perhaps

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---

*[roachpb/data.go, line 818 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K85jXnOs1_3hr0sXevy:-K862cqWD3dQhHyxvkG7:133900879) ([raw file](https://github.com/cockroachdb/cockroach/blob/52edbe411e2257b39ab6a34fa768e3e88ca9e8e3/roachpb/data.go#L818)):*
A `Span` is just a key range and it seems unlikely to have further fields added.

---

*[storage/engine/mvcc.go, line 168 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K85dSkEVtoHYtbOJKZI:-K861n3Lf1sGpIyuhV--:-537901167) ([raw file](https://github.com/cockroachdb/cockroach/blob/9657e9d5e4f2692c2f5d91328ac7e3aaf12712e9/storage/engine/mvcc.go#L168)):*
I'd like to keep it as is. Returning a value creates opportunity for still calling `ms.Add(y)` without using the return value, and unlike `time.Time`, my impression is that mutation is welcome most of the time here.

---

*[storage/engine/mvcc.go, line 213 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K85lN76dQN7GlIftElW:-K862DX6NbFqwcM5gesB:-1552727095) ([raw file](https://github.com/cockroachdb/cockroach/blob/005d7430e4f63aa5b92175f63b963046826d8ea2/storage/engine/mvcc.go#L213)):*
Good question, but `localPrefix` is `\x01` and `\localMax` is `\x02`, so my guess would be that it's not local (i.e. exclusive end key as usual for ranges). @petermattis?

---

*[storage/engine/mvcc_test.go, line 151 \[r5\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K85kGzvgmba0lLuuUpU:-K863U07vsNIImJZbr6V:-1118284903) ([raw file](https://github.com/cockroachdb/cockroach/blob/6641bdf5a657247d26585924ffe9f085d26ba2cd/storage/engine/mvcc_test.go#L151)):*
I'm a fan of `Fatalf` everywhere unless that which follows can be correct. Since these test cases are all connected, best to stop before going through more garbage.

---

*[storage/engine/rocksdb.go, line 591 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K85ftwGZjX3y_sWbDSF:-K863nrYeqJr1RIJ8e-j:534496945) ([raw file](https://github.com/cockroachdb/cockroach/blob/9657e9d5e4f2692c2f5d91328ac7e3aaf12712e9/storage/engine/rocksdb.go#L591)):*
Both kind of awkward, unfortunately. Would be good to somehow use the proto, but Pete already crushed my hopes on that front. Going to leave as is.

---

*[storage/engine/rocksdb_test.go, line 572 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K85adOMfRkXj518MGC9:-K866NcPebLofzSeu0R5:1405348849) ([raw file](https://github.com/cockroachdb/cockroach/blob/36a4a63438b5be2253bcb9624a8c36c23ccfbab1/storage/engine/rocksdb_test.go#L572)):*
Probably useful to see that the benchmark's doing some work. I'll leave this alone.

---

*[storage/engine/rocksdb_test.go, line 465 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K84adYkziBOYFCK3CjY:-K8665_3bL5TiscHNXth:129704550) ([raw file](https://github.com/cockroachdb/cockroach/blob/005d7430e4f63aa5b92175f63b963046826d8ea2/storage/engine/rocksdb_test.go#L465)):*
Touched this diff during a rebase with one of Spencer's PRs. No semantics changed.

---

*[storage/gc_queue.go, line 113 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K85gN2eAn-oZWFywNWe:-K866cE178YJRtdIF9dT:1616455777) ([raw file](https://github.com/cockroachdb/cockroach/blob/9657e9d5e4f2692c2f5d91328ac7e3aaf12712e9/storage/gc_queue.go#L113)):*
it's nice in tests to hit the gcScore exactly and to see something happen.

---

*[storage/replica.go, line 1388 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K85hEaGpW_kg9A27ZFF:-K867FR1uk2YELI17sO0:-565271811) ([raw file](https://github.com/cockroachdb/cockroach/blob/9657e9d5e4f2692c2f5d91328ac7e3aaf12712e9/storage/replica.go#L1388)):*
Yes, this was intended (previously, `MergeMVCCStats` did this ad-hoc and I removed that, thus the move to the call site). The comment actually doesn't relate to that line, it refers to deleted code. There's no reason to keep this `AgeTo` call though, so I've removed it. Stats can be fed in at any timestamp, and we age them to where we want to have them when we read them out.

---

*[storage/replica_command.go, line 1353 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K84XQ7uTRRryd-3JH5X:-K867bo4334x4MUPimTV:-1796810653) ([raw file](https://github.com/cockroachdb/cockroach/blob/36a4a63438b5be2253bcb9624a8c36c23ccfbab1/storage/replica_command.go#L1353)):*
sorry about the churn. I'll squash the two main commits.

---

*[storage/stats.go, line 112 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K84ZNwA2a2DO8ta-SdA:-K867hV7dh97tqIovCfn:1931168856) ([raw file](https://github.com/cockroachdb/cockroach/blob/9657e9d5e4f2692c2f5d91328ac7e3aaf12712e9/storage/stats.go#L112)):*
I want it to mutate (at least for now, since that's the current intention). The only case in which this would be bad is if someone calls this function with outlandishly future timestamps. But really the `nowNanos` arguments on various functions here seem to be mostly a substitute for having a clock on this structure.

---

*[util/testing.go, line 213 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K84_2e5ol3ZS8H2gKpu:-K868QVmhfisuyFK08hK:1838248145) ([raw file](https://github.com/cockroachdb/cockroach/blob/388c509d4a2ad166133b205aec27d6b6c1ef90da/util/testing.go#L213)):*
Good question, but a bunch of the other utils here are more like `NoZeroField` than the stuff in`testutils`. Might be time for some consolidation. I'll leave it for this PR.

---

*[util/testing.go, line 216 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K84_FPpFl41lkS1Tfn4:-K868LZdigK1S8rZB3Gr:-2048743009) ([raw file](https://github.com/cockroachdb/cockroach/blob/388c509d4a2ad166133b205aec27d6b6c1ef90da/util/testing.go#L216)):*
but I don't want to figure out whether the whole thing's zero, I want to make sure that no individual field is zero.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867)*

**Comment by tschottdorf** [comment]
I realized that I forgot to "upgrade" `updateStatsOnGC`. I'm heading out to the DR soon, so I'd like to get this merged and fix up the rest later.

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---

*[storage/engine/mvcc.go, line 213 \[r6\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K85lN76dQN7GlIftElW:-K86AoQzhrRMn36VAHrk:1157375068) ([raw file](https://github.com/cockroachdb/cockroach/blob/005d7430e4f63aa5b92175f63b963046826d8ea2/storage/engine/mvcc.go#L213)):*
`LocalMax` is `\x02` which is the same as the `keys.Meta1Prefix`. Definitely not local.

---

*[storage/engine/rocksdb/db.cc, line 1548 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K84YwKnYpUHWz4FZqIL:-K86AysFbNRG2_Ru6f9l:-1387682731) ([raw file](https://github.com/cockroachdb/cockroach/blob/9657e9d5e4f2692c2f5d91328ac7e3aaf12712e9/storage/engine/rocksdb/db.cc#L1548)):*
Thinking about this more, I wonder if it would be better for `MVCCStats` to store `LastUpdateSecs` and to pass around `now_secs` instead of `now_nanos`. This would make it more obvious that calculations need to be done in secs.

---

*[storage/engine/rocksdb_test.go, line 572 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K85adOMfRkXj518MGC9:-K86BHzf9v4U4fFjHXcX:67560459) ([raw file](https://github.com/cockroachdb/cockroach/blob/36a4a63438b5be2253bcb9624a8c36c23ccfbab1/storage/engine/rocksdb_test.go#L572)):*
This was useful to debug that the benchmark was operating on reasonably sized data. 

---

*[storage/stats.go, line 112 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K84ZNwA2a2DO8ta-SdA:-K86BWZu86hUbafqSD09:-1685246691) ([raw file](https://github.com/cockroachdb/cockroach/blob/9657e9d5e4f2692c2f5d91328ac7e3aaf12712e9/storage/stats.go#L112)):*
And yet the previous code did not mutate `rangeStats`. 

---

*[storage/stats.go, line 123 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K84ZX2rx8mjbs1R_iNS:-K86Bdc73V-6oPS0CTm4:2092731500) ([raw file](https://github.com/cockroachdb/cockroach/blob/9657e9d5e4f2692c2f5d91328ac7e3aaf12712e9/storage/stats.go#L123)):*
Can't have a value receiver on a structure containing a lock.

---

*[util/testing.go, line 213 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K84_2e5ol3ZS8H2gKpu:-K86Bh1_70EuWSrizfVs:261484790) ([raw file](https://github.com/cockroachdb/cockroach/blob/388c509d4a2ad166133b205aec27d6b6c1ef90da/util/testing.go#L213)):*
Sure. A follow-up PR is fine. `testutils` is slightly nicer than `util` because it is only linked into tests (we should probably enforce that).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867)*

**Comment by petermattis** [comment]
PS If the tests are passing, this is good to go. It is absolutely an improvement over the current state. Let's just plan on a follow-up PR to address some if the nits.

---

Review status: all files reviewed at latest revision, 16 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-:-K86C05b2Hwn6kt-kYdp:-1274135327)*

**Comment by tschottdorf** [comment]
Review status: 18 of 24 files reviewed at latest revision, 16 unresolved discussions, some commit checks failed.

---

*[storage/stats.go, line 112 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K84ZNwA2a2DO8ta-SdA:-K86PIOBXbAhA93F_trB:-1257324698) ([raw file](https://github.com/cockroachdb/cockroach/blob/9657e9d5e4f2692c2f5d91328ac7e3aaf12712e9/storage/stats.go#L112)):*
that's true, but it also didn't produce correct results. The internal LastUpdateNanos is always the most in the future observed, so it makes some sense to do that here as well. Aging back in time is going to be weird.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867)*

**Comment by tamird** [comment]
Reviewed 7 of 7 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[storage/engine/mvcc.go, line 188 \[r7\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867#-K86zLgC3MmyIPnHlEXn:-K86zLgC3MmyIPnHlEXo:-124637678) ([raw file](https://github.com/cockroachdb/cockroach/blob/87f6c8ecd6a6bfa62e49613dd4a8b7be81dd34ad/storage/engine/mvcc.go#L188)):*
s/to/from/

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3867)*

**Pull request merged**
