### PR TITLE
geos: partially handle POINT EMPTY output from GEOS

### PR DESCRIPTION
**Pull request by otan**
There is technically no valid way to encode POINT EMPTY in WKB, so GEOS
freaks out and returns an error. We can mitigate this by making it
return the GeoPackage spec compatible version by posting the raw NaNs
instead. This partially resolves the POINT EMPTY problem from the GEOS
perspective.

Release note: None

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49988)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/geo/encode.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49988#-M9ORjzc8-PU7aQENm7i:-M9ORjzc8-PU7aQENm7j:bur0amw) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b641aeb29781d7d9044d4de6a09ded2dfc31973/pkg/geo/encode.go#L31)):*
> ```Go
> func EWKBToWKT(b geopb.EWKB) (geopb.WKT, error) {
> 	// twpayne/go-geom doesn't seem to handle POINT EMPTY just yet. Add this hack in.
> 	// Remove after #49209 is resolved.
> ```

I'm missing something here. There are issues with empty inputs and empty output from GEOS. This PR seems to handle the output. Why are we referring to #49209 which deals with empty inputs.
And why was this code removed?
And there are other places like `linear_reference.go` that have removed the empty case from the input.
___
*[pkg/geo/geos/geos.cc, line 348 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49988#-M9OPxDU8CE8Hd_qFxjZ:-M9OPxDV-34y2G6lzkyy:b-sqzbbe) ([raw file](https://github.com/cockroachdb/cockroach/blob/91a11ae3c2c6099f458f9e0016b9bd8172aa853e/pkg/geo/geos/geos.cc#L348)):*
> ```cpp
>       CR_GEOS_PushLittleEndianUint32(buf, uint32_t(srid));
>     }
>     for (auto i = 0; i < 2; i++) {
> ```

can you add a comment about what this for loop is doing.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49988)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/geo/encode.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49988#-M9ORjzc8-PU7aQENm7i:-M9OV2spAxRXu2Q5oMFU:b-diibnj) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b641aeb29781d7d9044d4de6a09ded2dfc31973/pkg/geo/encode.go#L31)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I'm missing something here. There are issues with empty inputs and empty output from GEOS. This PR seems to handle the output. Why are we referring to #49209 which deals with empty inputs.
And why was this code removed?
And there are other places like `linear_reference.go` that have removed the empty case from the input.
</blockquote></details>

This is removed because GEOS can now return EMPTY points to the caller, but twpayne/go-geom cannot parse it (blocked on https://github.com/twpayne/go-geom/pull/170).
We've put a stopgap in in geo.go:spatialObjectFromGeom, where NaNs for coordinates become an EMPTY point.
 
___
*[pkg/geo/geos/geos.cc, line 348 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49988#-M9OPxDU8CE8Hd_qFxjZ:-M9OVS2S8-pxh0QRZ7b0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/91a11ae3c2c6099f458f9e0016b9bd8172aa853e/pkg/geo/geos/geos.cc#L348)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

can you add a comment about what this for loop is doing.
</blockquote></details>

Done.

**Review by sumeerbhola — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49988)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[pkg/geo/encode.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49988#-M9ORjzc8-PU7aQENm7i:-M9OlBziAbobzhrbekPa:b-kykynf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b641aeb29781d7d9044d4de6a09ded2dfc31973/pkg/geo/encode.go#L31)):*
> We've put a stopgap in in geo.go:spatialObjectFromGeom, where NaNs for coordinates become an EMPTY point.

The stopgap seems to be for a bounding box computation and seems local to a function that is not doing any parsing.
And the parsing function is this one where the removal of the special case means we will call `ewkb.Unmarshal` for parsing, which you said is awaiting merge of your other PR.
So I still don't understand.

**Comment by otan** [comment]
___
*[pkg/geo/encode.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49988#-M9ORjzc8-PU7aQENm7i:-M9Ome7qBX0VRIWgEr1o:bn5ztmk) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b641aeb29781d7d9044d4de6a09ded2dfc31973/pkg/geo/encode.go#L31)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

> We've put a stopgap in in geo.go:spatialObjectFromGeom, where NaNs for coordinates become an EMPTY point.

The stopgap seems to be for a bounding box computation and seems local to a function that is not doing any parsing.
And the parsing function is this one where the removal of the special case means we will call `ewkb.Unmarshal` for parsing, which you said is awaiting merge of your other PR.
So I still don't understand.

</blockquote></details>

The comment is wrong I'll fix it - it actually creates an empty point instead of what I said it would do.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49988)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[pkg/geo/encode.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49988#-M9ORjzc8-PU7aQENm7i:-M9PAYRWC7CwbACCpmwo:b-ompipn) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b641aeb29781d7d9044d4de6a09ded2dfc31973/pkg/geo/encode.go#L31)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

The comment is wrong I'll fix it - it actually creates an empty point instead of what I said it would do. 
</blockquote></details>

But `t` is only used for the bounding box computation.

**Comment by otan** [comment]
___
*[pkg/geo/encode.go, line 31 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49988#-M9ORjzc8-PU7aQENm7i:-M9PArn76y-2ggYtgRgF:b-72rg5y) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b641aeb29781d7d9044d4de6a09ded2dfc31973/pkg/geo/encode.go#L31)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

But `t` is only used for the bounding box computation.
</blockquote></details>

haha oops, i guess i am missing the second piece. i'll abandon this for now then ^_^

**Pull request closed without merging**
