### PR TITLE
vendor: update petermattis/goid to support fast access on arm64

### PR DESCRIPTION
**Pull request by nvb**
This commit updates the `github.com/petermattis/goid` dependency to pick
up https://github.com/petermattis/goid/pull/11. This speeds up access to
a goroutine's ID on arm64 systems.

I originally noticed the need for this when running microbenchmarks in
`pkg/util/tracing`. Here is the effect of this change on those
benchmarks when run on an M1 Mac (goos: darwin, goarch: arm64):

```
name                                           old time/op    new time/op    delta
SpanCreation/detached-child=false-10             73.6µs ± 3%     2.1µs ± 4%  -97.10%  (p=0.000 n=10+10)
SpanCreation/detached-child=true-10              73.3µs ± 3%     2.5µs ± 4%  -96.62%  (p=0.000 n=10+10)
Tracer_StartSpanCtx/opts=real-10                 6.51µs ± 3%    0.35µs ± 4%  -94.69%  (p=0.000 n=10+9)
Tracer_StartSpanCtx/opts=none-10                 6.53µs ± 3%    0.35µs ± 3%  -94.68%  (p=0.000 n=10+10)
Tracer_StartSpanCtx/opts=real,logtag-10          6.54µs ± 5%    0.37µs ± 5%  -94.34%  (p=0.000 n=10+10)
RecordingWithStructuredEvent-10                  13.8µs ± 1%     0.9µs ± 4%  -93.46%  (p=0.000 n=9+10)
Tracer_StartSpanCtx/opts=real,autoparent-10      6.62µs ± 3%    0.46µs ± 9%  -93.12%  (p=0.000 n=10+9)
Tracer_StartSpanCtx/opts=real,manualparent-10    6.64µs ± 3%    0.48µs ± 5%  -92.73%  (p=0.000 n=10+9)
Span_GetRecording/root-only-10                   16.8ns ± 2%    16.8ns ± 4%     ~     (p=0.810 n=10+10)
Span_GetRecording/child-only-10                  16.7ns ± 2%    16.8ns ± 2%     ~     (p=0.342 n=10+10)
Span_GetRecording/root-child-10                  26.6ns ± 4%    26.3ns ± 1%     ~     (p=0.529 n=10+8)

name                                           old alloc/op   new alloc/op   delta
RecordingWithStructuredEvent-10                  1.68kB ± 0%    1.54kB ± 0%   -8.17%  (p=0.000 n=10+10)
SpanCreation/detached-child=false-10             5.01kB ± 0%    4.61kB ± 0%   -8.02%  (p=0.000 n=10+10)
Tracer_StartSpanCtx/opts=none-10                   834B ± 0%      768B ± 0%   -7.91%  (p=0.000 n=10+10)
Tracer_StartSpanCtx/opts=real-10                   834B ± 0%      768B ± 0%   -7.91%  (p=0.000 n=9+10)
Tracer_StartSpanCtx/opts=real,logtag-10            834B ± 0%      768B ± 0%   -7.91%  (p=0.000 n=9+10)
Tracer_StartSpanCtx/opts=real,autoparent-10        834B ± 0%      768B ± 0%   -7.91%  (p=0.000 n=10+10)
Tracer_StartSpanCtx/opts=real,manualparent-10      834B ± 0%      768B ± 0%   -7.91%  (p=0.000 n=10+10)
SpanCreation/detached-child=true-10              5.49kB ± 0%    5.09kB ± 0%   -7.36%  (p=0.002 n=8+10)
Span_GetRecording/root-only-10                    0.00B          0.00B          ~     (all equal)
Span_GetRecording/child-only-10                   0.00B          0.00B          ~     (all equal)
Span_GetRecording/root-child-10                   0.00B          0.00B          ~     (all equal)

name                                           old allocs/op  new allocs/op  delta
Tracer_StartSpanCtx/opts=none-10                   3.00 ± 0%      1.00 ± 0%  -66.67%  (p=0.000 n=10+10)
Tracer_StartSpanCtx/opts=real-10                   3.00 ± 0%      1.00 ± 0%  -66.67%  (p=0.000 n=9+10)
Tracer_StartSpanCtx/opts=real,logtag-10            3.00 ± 0%      1.00 ± 0%  -66.67%  (p=0.000 n=9+10)
Tracer_StartSpanCtx/opts=real,autoparent-10        3.00 ± 0%      1.00 ± 0%  -66.67%  (p=0.000 n=10+10)
Tracer_StartSpanCtx/opts=real,manualparent-10      3.00 ± 0%      1.00 ± 0%  -66.67%  (p=0.000 n=10+10)
RecordingWithStructuredEvent-10                    6.00 ± 0%      2.00 ± 0%  -66.67%  (p=0.000 n=10+10)
SpanCreation/detached-child=false-10               18.0 ± 0%       6.0 ± 0%  -66.67%  (p=0.000 n=10+10)
SpanCreation/detached-child=true-10                28.0 ± 0%      16.0 ± 0%  -42.86%  (p=0.000 n=10+10)
Span_GetRecording/root-only-10                     0.00           0.00          ~     (all equal)
Span_GetRecording/child-only-10                    0.00           0.00          ~     (all equal)
Span_GetRecording/root-child-10                    0.00           0.00          ~     (all equal)
```

### CODE REVIEW

**Review by andreimatei — APPROVED** [review]
:LGTM: respect

Unrelated, do you know if there's a faster way to get a dump of an arbitrary goroutine (as opposed to the current goroutine) than parsing the dump of *all* goroutines?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74354#-:-Msf2KJQA83wGAlh3Rdy:bl3f02y)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by nvb — COMMENTED** [review]
TFTR!

bors r=andreimatei

> Unrelated, do you know if there's a faster way to get a dump of an arbitrary goroutine (as opposed to the current goroutine) than parsing the dump of all goroutines?

~Are you aware of [`runtime.Stack`](https://pkg.go.dev/runtime#Stack)? It takes an `all` param, which dictates whether all goroutines are included or not. [`debug.Stack` wraps this](https://cs.opensource.google/go/go/+/refs/tags/go1.17.5:src/runtime/debug/stack.go;l=24) and sets `all` to `false`.~

Actually, I misread your question. If you're not looking for the current goroutine, then no, I'm not aware of any such function.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74354#-:-MsjwM335b5-icgAulJf:b2304cy)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by nvanbenschoten** [comment]
bor r-

**Pull request merged**
