### PR TITLE
ui/sql: show summarized statements in the statements table

### LINKED ISSUE #27021: ui: Statements screen hides too much information
screen shot 2018-06-26 at 8 39 04 pm

When trying to track down a slow query, it was a bit frustrating to have to hover over many rows (and wait half a second for the pop up on each one) just to find the one I was looking for. In the image above we show `select from rides` many times but its not clear what is what. I get that a full fingerprint may be very long, but perhaps there is a design solution to further disambiguate? 

How do other tools solve for this?

cc @piyush-singh

### PR DESCRIPTION
**Pull request by lindseyjin**
Resolves #27021

Previously, statements on the statements page hid too much information.
There were complaints that it was difficult to disambiguate between
statements without having to view the full query on the tooltips.

The first commit in this patch implemented back-end changes to add a new
metadata field for summarized queries, as well as formatting functions.
This second commit implements additional logic to pass that new metadata
to the front-end and display it in the Statements Table.

Currently, we only create summaries of SELECT, INSERT/UPSERT, and UPDATE
statements in the back-end. For all other statement types, we will
continue to use the existing summary system.

image

Release note (ui change): Show new statement summaries on the Statements
page. This applies for SELECT, INSERT/UPSERT, and UPDATE statements, and
will enable them to be more detailed and less ambiguous than our
previous formats.

### CODE REVIEW

**Review by lindseyjin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71534)* status: :shipit: complete! 0 of 0 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/71534#-Mluzjed9ONtGxHgHUIa:-Mluzjed9ONtGxHgHUIb:bci5q7e) (no related file):*
@annebirzin 

Btw, this is what the Statements page looks like with the table character limit set to 30 instead:


 
Let me know if you prefer this to the current 15 character limit, or if you need a larger screenshot!

---

**Review by Annebirzin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71534)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Annebirzin and @lindseyjin)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/71534#-Mluzjed9ONtGxHgHUIa:-MlvBAJq8UZ6HbUFzZsD:b-mq5821) (no related file):*
<details><summary><i>Previously, lindseyjin (Lindsey Jin) wrote…</i></summary><blockquote>

@annebirzin 

Btw, this is what the Statements page looks like with the table character limit set to 30 instead:


 
Let me know if you prefer this to the current 15 character limit, or if you need a larger screenshot!
</blockquote></details>

@lindseyjin For a simple SELECT I think we could leave at 30 characters (since there is nothing after the db.table name to show). But wondering if for SELECT + JOIN, we should shorten the db.table name to 15 characters so that users could see that there is a JOIN. Does that make sense? 

---

**Review by lindseyjin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71534)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Annebirzin)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/71534#-Mluzjed9ONtGxHgHUIa:-MlvFBMO0wB60lS3H552:bhpn0zv) (no related file):*
<details><summary><i>Previously, Annebirzin (Anne Birzin) wrote…</i></summary><blockquote>

@lindseyjin For a simple SELECT I think we could leave at 30 characters (since there is nothing after the db.table name to show). But wondering if for SELECT + JOIN, we should shorten the db.table name to 15 characters so that users could see that there is a JOIN. Does that make sense? 
</blockquote></details>

I haven't actually implemented the JOIN formatting logic, since I thought based on our last discussion we would just show everything after FROM up to 30 characters (which would likely cover the first JOIN and maybe the ON clause as well)

Would it be ok to keep that system for SELECT + JOINs, or would you like me to implement JOIN formatting rules? It might be a little complicated, but I can look into it if you think it's important UX wise

---

**Review by Annebirzin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71534)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Annebirzin and @lindseyjin)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/71534#-Mluzjed9ONtGxHgHUIa:-MlvIjwp2mzz41GT3SrH:b-8l2nhf) (no related file):*
<details><summary><i>Previously, lindseyjin (Lindsey Jin) wrote…</i></summary><blockquote>

I haven't actually implemented the JOIN formatting logic, since I thought based on our last discussion we would just show everything after FROM up to 30 characters (which would likely cover the first JOIN and maybe the ON clause as well)

Would it be ok to keep that system for SELECT + JOINs, or would you like me to implement JOIN formatting rules? It might be a little complicated, but I can look into it if you think it's important UX wise
</blockquote></details>

ah right, I see now. Let's stick to the 30 characters for now (if we see that a lot of tables have long names we could introduce the JOIN logic) thanks for clarifying! 

---

**Review by Azhng — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71534)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Annebirzin, @Azhng, and @lindseyjin)

___
*[pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go, line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71534#-MlzZpxU5BfQWQSclnaS:-MlzZpxU5BfQWQSclnaT:b-to0kyx) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9480c2d818acb9e53d34f981555efdcbfb4fd64/pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go#L52)):*
> ```Go
> 	implicitTxn           bool
> 	database              string
> 	anonymizedStmtSummary string
> ```

I don't think we should add the `anonymizedStmtSummary` into the `planKey`, the plan is determined independent of the the summary text. We can easily look up whether if we have sampled the explain plan for a statement without the summary text.

Also I'm expecting we will be working towards shrinking down this struct in the future since it's rather bloated right now. Ideally this would just be a simple `uint64` hash, but welp :shrug:

**Review by Annebirzin — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71534#-:-Mm-9Ri-AUcU22rPS1jF:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Annebirzin, @Azhng, and @lindseyjin)

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71534)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Annebirzin, @Azhng, and @lindseyjin)

___
*[pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go, line 285 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71534#-Mm-KWua0o8fQUasMlIW:-Mm-KWua0o8fQUasMlIX:bs8d16u) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9480c2d818acb9e53d34f981555efdcbfb4fd64/pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go#L285)):*
> ```Go
> 		stmtStats.mu.distSQLUsed = statistics[i].Key.KeyData.DistSQL
> 		stmtStats.mu.fullScan = statistics[i].Key.KeyData.FullScan
> 		stmtStats.mu.database = statistics[i].Key.KeyData.Database
> ```

The issue where the new field is not surfaced in the frontend when it is removed from the `planKey` is probably because it is not explicitly added here. There's a lot of metadata we don't have in the `planKey` so we just add them in the `stmtStats` object here. 

Let me know if you have more troubles surfacing this metadata to the frontend.

**Review by lindseyjin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71534)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Annebirzin and @Azhng)

___
*[pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go, line 52 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71534#-MlzZpxU5BfQWQSclnaS:-Mm-bPbw6e6bUln2lLZo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9480c2d818acb9e53d34f981555efdcbfb4fd64/pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go#L52)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

I don't think we should add the `anonymizedStmtSummary` into the `planKey`, the plan is determined independent of the the summary text. We can easily look up whether if we have sampled the explain plan for a statement without the summary text.

Also I'm expecting we will be working towards shrinking down this struct in the future since it's rather bloated right now. Ideally this would just be a simple `uint64` hash, but welp :shrug: 
</blockquote></details>

Done.
___
*[pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go, line 285 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/71534#-Mm-KWua0o8fQUasMlIW:-Mm-bQ7s3-W1KD_2XG9X:bp8tzhj) ([raw file](https://github.com/cockroachdb/cockroach/blob/d9480c2d818acb9e53d34f981555efdcbfb4fd64/pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go#L285)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

The issue where the new field is not surfaced in the frontend when it is removed from the `planKey` is probably because it is not explicitly added here. There's a lot of metadata we don't have in the `planKey` so we just add them in the `stmtStats` object here. 

Let me know if you have more troubles surfacing this metadata to the frontend.
</blockquote></details>

Done, thanks for the advice!

**Review by Azhng — COMMENTED** [review]
This is awesome! Just few more minor nits from me 

> Reviewed 2 of 23 files at r2, 8 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71534#-:-Mm9VPzZEWhBghZEPQwp:b1yse5x)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Annebirzin, @Azhng, and @lindseyjin)

___
*[pkg/ui/workspaces/db-console/src/views/statements/statementDetails.tsx, line 101 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71534#-Mm9ULasCvqkWIcI_7nC:-Mm9ULau2Wy87P5pBQDX:b28q0xd) ([raw file](https://github.com/cockroachdb/cockroach/blob/07f92d8d26594e2605e85c725e3f3944542cc337/pkg/ui/workspaces/db-console/src/views/statements/statementDetails.tsx#L101)):*
> ```XML
>     return {
>       label: stmt.nodeId.toString(),
>       summary: stmt.nodeId.toString(),
> ```

Hmm, why are we assigning `nodeId` to `summary`?
___
*[pkg/ui/workspaces/db-console/src/views/statements/statementsPage.fixture.ts, line 477 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71534#-Mm9UdF85k56rxuzHUG0:-Mm9UdF85k56rxuzHUG1:b7wrrtp) ([raw file](https://github.com/cockroachdb/cockroach/blob/07f92d8d26594e2605e85c725e3f3944542cc337/pkg/ui/workspaces/db-console/src/views/statements/statementsPage.fixture.ts#L477)):*
> ```XML
>         "CREATE TABLE IF NOT EXISTS users (id UUID NOT NULL, city VARCHAR NOT NULL, name VARCHAR NULL, address VARCHAR NULL, credit_card VARCHAR NULL, PRIMARY KEY (city ASC, id ASC))",
>       summary:
>         "CREATE TABLE IF NOT EXISTS users (id UUID NOT NULL, city VARCHAR NOT NULL, name VARCHAR NULL, address VARCHAR NULL, credit_card VARCHAR NULL, PRIMARY KEY (city ASC, id ASC))",
> ```

Hmm, is this summary correct for the label? It seems it's a bit too long

**Review by lindseyjin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71534)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Annebirzin, @Azhng, and @lindseyjin)

___
*[pkg/ui/workspaces/db-console/src/views/statements/statementsPage.fixture.ts, line 477 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71534#-Mm9UdF85k56rxuzHUG0:-MmJ5gfKDKffEprsjE7B:b-n05luc) ([raw file](https://github.com/cockroachdb/cockroach/blob/07f92d8d26594e2605e85c725e3f3944542cc337/pkg/ui/workspaces/db-console/src/views/statements/statementsPage.fixture.ts#L477)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm, is this summary correct for the label? It seems it's a bit too long 
</blockquote></details>

Currently, the back-end formatter returns the default statement as the summary if we don't have specific summary rules (aka same as the label). I account for this in the front-end by using the old summary function (regex) if it's not a supported statement type.

Not sure if it would be better to return a null type in this case?

**Review by Azhng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71534)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Annebirzin, @Azhng, and @lindseyjin)

___
*[pkg/ui/workspaces/db-console/src/views/statements/statementsPage.fixture.ts, line 477 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71534#-Mm9UdF85k56rxuzHUG0:-MmJDG8fA0VBn0u3KXQb:bbcufml) ([raw file](https://github.com/cockroachdb/cockroach/blob/07f92d8d26594e2605e85c725e3f3944542cc337/pkg/ui/workspaces/db-console/src/views/statements/statementsPage.fixture.ts#L477)):*
<details><summary><i>Previously, lindseyjin (Lindsey Jin) wrote…</i></summary><blockquote>

Currently, the back-end formatter returns the default statement as the summary if we don't have specific summary rules (aka same as the label). I account for this in the front-end by using the old summary function (regex) if it's not a supported statement type.

Not sure if it would be better to return a null type in this case? 
</blockquote></details>

Ah I see. I didn't realize we are only doing summary for a subset of statements. Do we have plans on expending the summary to support other statement types ?

**Review by lindseyjin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71534)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Annebirzin, @Azhng, and @lindseyjin)

___
*[pkg/ui/workspaces/db-console/src/views/statements/statementDetails.tsx, line 101 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71534#-Mm9ULasCvqkWIcI_7nC:-MmJD_dH6DiQTzm86SYf:b-qsseby) ([raw file](https://github.com/cockroachdb/cockroach/blob/07f92d8d26594e2605e85c725e3f3944542cc337/pkg/ui/workspaces/db-console/src/views/statements/statementDetails.tsx#L101)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Hmm, why are we assigning `nodeId` to `summary`?
</blockquote></details>

fixed!

**Review by maryliag — COMMENTED** [review]
> Reviewed 13 of 23 files at r2, 3 of 3 files at r3, 4 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71534)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Annebirzin, @Azhng, @lindseyjin, and @maryliag)

___
*[-- commits, line 19 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71534#-MmJBLg62n11URHuZwA9):*
nit: you don't need to go in details of how you made the change on the release note. This part is used to created the docs later on and the part needed here is just explaining what are the ui change the user will notice, so it can skip the beginning you added, e.g.
Release note (ui change): Update statements summaries on the Statements.... and so on
___
*[pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.fixture.ts, line 459 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71534#-MmJCP2Y3rO-iebKAHZ0:-MmJCP2Y3rO-iebKAHZ1:b-azmoe5) ([raw file](https://github.com/cockroachdb/cockroach/blob/07f92d8d26594e2605e85c725e3f3944542cc337/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.fixture.ts#L459)):*
> ```XML
>         'CREATE TABLE IF NOT EXISTS user_promo_codes (city VARCHAR NOT NULL, user_id UUID NOT NULL, code VARCHAR NOT NULL, "timestamp" TIMESTAMP NULL, usage_count INT8 NULL, PRIMARY KEY (city ASC, user_id ASC, code ASC))',
>       summary:
>         'CREATE TABLE IF NOT EXISTS user_promo_codes (city VARCHAR NOT NULL, user_id UUID NOT NULL, code VARCHAR NOT NULL, "timestamp" TIMESTAMP NULL, usage_count INT8 NULL, PRIMARY KEY (city ASC, user_id ASC, code ASC))',
> ```

is this one this long because we don't have summaries for CREATE stataments?
___
*[pkg/ui/workspaces/cluster-ui/src/statementsTable/statementsTable.tsx, line 206 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71534#-MmJCbn29R2Qq9ujYX0u:-MmJCbn29R2Qq9ujYX0v:baz5m6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/07f92d8d26594e2605e85c725e3f3944542cc337/pkg/ui/workspaces/cluster-ui/src/statementsTable/statementsTable.tsx#L206)):*
> ```XML
>   // label is either shortStatement (StatementsPage) or nodeId (StatementDetails).
>   label: string;
>   summary: string;
> ```

nit: the comment about label is also valid for summary, update it accordingly 
___
*[pkg/ui/workspaces/cluster-ui/src/statementsTable/statementsTableContent.tsx, line 184 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71534#-MmJCuwUDJLaw0r0TNYh:-MmJCuwUDJLaw0r0TNYi:b-7uzzoo) ([raw file](https://github.com/cockroachdb/cockroach/blob/07f92d8d26594e2605e85c725e3f3944542cc337/pkg/ui/workspaces/cluster-ui/src/statementsTable/statementsTableContent.tsx#L184)):*
> ```XML
>   const summary = summarize(statement);
>   // current statements that we support summaries for from the backend.
>   const summarizedStmts = new Set(["select", "insert", "upsert", "update"]);
> ```

make sure to create a new issue or update the current one detailing the supported statement types, so the remaining can be addressed too
___
*[pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.spec.ts, line 129 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71534#-MmJDECB75F9HvSbc5nn:-MmJDECB75F9HvSbc5no:b-11ek6s) ([raw file](https://github.com/cockroachdb/cockroach/blob/07f92d8d26594e2605e85c725e3f3944542cc337/pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.spec.ts#L129)):*
> ```XML
>           key_data: {
>             query: "UPDATE foobar SET name = 'baz' WHERE id = 42",
>             query_summary: "UPDATE foobar SET name = 'baz' WHERE id = 42",
> ```

can you add a few more examples with statement that would actually have changed on the summary compared to the query itself

**Review by lindseyjin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71534)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Annebirzin, @Azhng, @lindseyjin, and @maryliag)

___
*[pkg/ui/workspaces/db-console/src/views/statements/statementsPage.fixture.ts, line 477 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71534#-Mm9UdF85k56rxuzHUG0:-MmJDcr592djEin5Vpkh:blcs2h9) ([raw file](https://github.com/cockroachdb/cockroach/blob/07f92d8d26594e2605e85c725e3f3944542cc337/pkg/ui/workspaces/db-console/src/views/statements/statementsPage.fixture.ts#L477)):*
<details><summary><i>Previously, Azhng (Archer Zhang) wrote…</i></summary><blockquote>

Ah I see. I didn't realize we are only doing summary for a subset of statements. Do we have plans on expending the summary to support other statement types ? 
</blockquote></details>

I think eventually we might support more summarized formats (cc: @annebirzin correct me if I'm wrong?)

But for now we're just supporting select, insert/upsert, and update summaries!

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71534)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Annebirzin, @Azhng, @lindseyjin, and @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts, line 67 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71534#-MmJE65bAmlBY6rVRT4m:-MmJE65c3o8ksgrSFnci:bfkdppj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c259c5b2f31472732cf6e12ea0129e1bb18dc585/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts#L67)):*
> ```XML
>     return {
>       label: stmt.nodeId.toString(),
>       summary: stmt.nodeId.toString(),
> ```

shouldn't this be stmt.statement_summary ?

**Review by lindseyjin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71534)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Annebirzin, @Azhng, @lindseyjin, and @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.fixture.ts, line 459 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71534#-MmJCP2Y3rO-iebKAHZ0:-MmJECLwExaw-6Ld_Wua:bhquwi5) ([raw file](https://github.com/cockroachdb/cockroach/blob/07f92d8d26594e2605e85c725e3f3944542cc337/pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.fixture.ts#L459)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

is this one this long because we don't have summaries for CREATE stataments?
</blockquote></details>

Yup, I'm passing in the default statement if we don't have a summary format, and then replacing it with the old summary from the front-end if that's the case

**Review by lindseyjin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71534)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Annebirzin, @Azhng, @lindseyjin, and @maryliag)

___
*[-- commits, line 19 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71534#-MmJBLg62n11URHuZwA9):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: you don't need to go in details of how you made the change on the release note. This part is used to created the docs later on and the part needed here is just explaining what are the ui change the user will notice, so it can skip the beginning you added, e.g.
Release note (ui change): Update statements summaries on the Statements.... and so on
</blockquote></details>

Done!
___
*[pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts, line 67 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/71534#-MmJE65bAmlBY6rVRT4m:-MmJV-mK89j3xU-8nqoe:bhcihu1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c259c5b2f31472732cf6e12ea0129e1bb18dc585/pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts#L67)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

shouldn't this be stmt.statement_summary ?
</blockquote></details>

Fixed, thanks for pointing that out!
___
*[pkg/ui/workspaces/cluster-ui/src/statementsTable/statementsTable.tsx, line 206 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71534#-MmJCbn29R2Qq9ujYX0u:-MmJV2IM-_6qnF05kgkU:b-hg240u) ([raw file](https://github.com/cockroachdb/cockroach/blob/07f92d8d26594e2605e85c725e3f3944542cc337/pkg/ui/workspaces/cluster-ui/src/statementsTable/statementsTable.tsx#L206)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: the comment about label is also valid for summary, update it accordingly 
</blockquote></details>

Er, I'm not sure if that comment also applies for summary since we don't use nodeId (at least now that I've fixed that). I have added a more descriptive comment though, so let me know if that works!
___
*[pkg/ui/workspaces/cluster-ui/src/statementsTable/statementsTableContent.tsx, line 184 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71534#-MmJCuwUDJLaw0r0TNYh:-MmJVIiuBDmXQzkkVFsL:b-luj7rm) ([raw file](https://github.com/cockroachdb/cockroach/blob/07f92d8d26594e2605e85c725e3f3944542cc337/pkg/ui/workspaces/cluster-ui/src/statementsTable/statementsTableContent.tsx#L184)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

make sure to create a new issue or update the current one detailing the supported statement types, so the remaining can be addressed too
</blockquote></details>

Not sure if you meant a github or Jira issue, or both? But I've created a new github issue here: https://github.com/cockroachdb/cockroach/issues/71667 

Let me know if that looks good and if there's anything I should change!

**Review by lindseyjin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71534)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Annebirzin, @Azhng, @lindseyjin, and @maryliag)

___
*[-- commits, line 19 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71534#-MmJBLg62n11URHuZwA9):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: you don't need to go in details of how you made the change on the release note. This part is used to created the docs later on and the part needed here is just explaining what are the ui change the user will notice, so it can skip the beginning you added, e.g.
Release note (ui change): Update statements summaries on the Statements.... and so on
</blockquote></details>

Done!

**Review by lindseyjin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71534)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Annebirzin, @Azhng, and @maryliag)

___
*[pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.spec.ts, line 129 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71534#-MmJDECB75F9HvSbc5nn:-MmJVsFL23EN_r07333L:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/07f92d8d26594e2605e85c725e3f3944542cc337/pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.spec.ts#L129)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

can you add a few more examples with statement that would actually have changed on the summary compared to the query itself
</blockquote></details>

Done.

**Review by maryliag — APPROVED** [review]
great work on this! :lgtm: 

> Reviewed 2 of 11 files at r4, 1 of 1 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71534#-:-MmJbEGk7bz00YhBSo0o:bt6fyb1)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @Annebirzin, @Azhng, and @lindseyjin)

___
*[pkg/ui/workspaces/cluster-ui/src/statementsTable/statementsTable.tsx, line 206 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71534#-MmJCbn29R2Qq9ujYX0u:-MmJaSdE2xtXfP-01oL9:b-nde0s2) ([raw file](https://github.com/cockroachdb/cockroach/blob/07f92d8d26594e2605e85c725e3f3944542cc337/pkg/ui/workspaces/cluster-ui/src/statementsTable/statementsTable.tsx#L206)):*
<details><summary><i>Previously, lindseyjin (Lindsey Jin) wrote…</i></summary><blockquote>

Er, I'm not sure if that comment also applies for summary since we don't use nodeId (at least now that I've fixed that). I have added a more descriptive comment though, so let me know if that works!
</blockquote></details>

I wrote that before realizing the change and actually retracted, so it was indeed no longer valid, but your new comment was very much welcome and helpful :D 
___
*[pkg/ui/workspaces/cluster-ui/src/statementsTable/statementsTableContent.tsx, line 184 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/71534#-MmJCuwUDJLaw0r0TNYh:-MmJaoPc-yeAOM-CzuYj:b-rmk1d6) ([raw file](https://github.com/cockroachdb/cockroach/blob/07f92d8d26594e2605e85c725e3f3944542cc337/pkg/ui/workspaces/cluster-ui/src/statementsTable/statementsTableContent.tsx#L184)):*
<details><summary><i>Previously, lindseyjin (Lindsey Jin) wrote…</i></summary><blockquote>

Not sure if you meant a github or Jira issue, or both? But I've created a new github issue here: https://github.com/cockroachdb/cockroach/issues/71667 

Let me know if that looks good and if there's anything I should change!
</blockquote></details>

github is enough, thanks!

**Review by Azhng — APPROVED** [review]
:fire:

**Pull request merged**
