### PR TITLE
distsql: add network stats collection

### PR DESCRIPTION
**Pull request by solongordon**
When stats collection is enabled, the number of bytes transferred by
distsql outboxes is now collected and outputted in the flow diagram
data. Presenting this data will be handled on the Javascript side in
the cockroachdb.github.io project.

Refers #26646

Release note: None

### CODE REVIEW

**Review by rjnn — DISMISSED** [review]
:lgtm_strong: 

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27332#-:-LH3kIy59YPxNCn-82bu:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/logictest/testdata/planner_test/distsql_lookup_join, line 229 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27332#-LH3jmfW6HOIEqUVRtZe:-LH3jmfW6HOIEqUVRtZf:bg9r2pd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a89ca9bcbd38d670749fc58a7539b63416384b9/pkg/sql/logictest/testdata/planner_test/distsql_lookup_join#L229)):*
> ```
> SELECT "URL" FROM [EXPLAIN ANALYZE (DISTSQL) SELECT t1.c, t2.c FROM multiples t1 LEFT JOIN multiples@bc t2 ON t1.c = t2.b]
> ----
> https://cockroachdb.github.io/distsqlplan/decode.html?eJzclU9r4zwQxu_vpxBz1kst20lTnXLpQkpJlpA9LT441lC062iMJLMNJd99sb1QOzSye2gOOerPo-c3egbmDQwpXOcHdCB_ggAOMXBIgEMKHGaQcagsFegc2eZKJ1ipV5ARB22q2jfbGYeCLIJ8A699iSBhl-9L3GKu0N5FwEGhz3XZ2lRWH3J7XB7q0uuqRAccLP1xzGKuJGtuO5-XJfP6gJJFzfmm9pItE8hOHKj2777O5y8IUpz4dLYn0uYf2myItjtWKNnz47cd2_zYPW7Z02a1Bg77YkD7TPS7rtgv0oaRkWwpJpSgjcJXdnar27xQruDL9GLF8cWK3wutDVmFFtWgyuz0wZ-s6X-q7kR0dvNj72TgLaZ3grh2J4yw9TphfiOdEE9PI752GiNsvTTubySNZHoaybXTGGHrpbG4kTTS6Wmk105jhK2XxsONpDEypbfoKjIOJ02kqJlpqF6wG4COalvgd0tFa9MtN62u3VDofHcqusXKdEcNYF8sguJ4IBbn4jjsPGKdBNVpWJx-hrv9xfZDYX_06JhD4yWL502Qw3dnwXfnYaj5F0HdB99dhKEWXwT1EA4_Gum7cNd-Ais7_fc3AAD__zu620M=
> ```

For any other readers confused by this change, there's invisible edge statistics which will be visible only when https://github.com/cockroachdb/cockroachdb.github.io/pull/5 is merged

**Review by solongordon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27332)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/logictest/testdata/planner_test/distsql_lookup_join, line 229 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/27332#-LH3jmfW6HOIEqUVRtZe:-LH43CLLDaJuChVfpImv:bcj1wqs) ([raw file](https://github.com/cockroachdb/cockroach/blob/3a89ca9bcbd38d670749fc58a7539b63416384b9/pkg/sql/logictest/testdata/planner_test/distsql_lookup_join#L229)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

For any other readers confused by this change, there's invisible edge statistics which will be visible only when https://github.com/cockroachdb/cockroachdb.github.io/pull/5 is merged
</blockquote></details>

Thanks, meant to link that. The changes should be visible now (on mouseover).

**Review by asubiotto — DISMISSED** [review]
Nice! You can also auto-close #26646 in the commit message

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27332#-:-LH45_2S7EZzA4NxdDRT:b-d42qdk)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/outbox.go, line 194 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27332#-LH4GTfJ1adhxb5ZoxWS:-LH4GTfJ1adhxb5ZoxWT:bk41lje) ([raw file](https://github.com/cockroachdb/cockroach/blob/52bfa838b1389160874686683ca09212466afe3d/pkg/sql/distsqlrun/outbox.go#L194)):*
> ```Go
> 	var span opentracing.Span
> 	ctx, span = processorSpan(ctx, "outbox")
> 	if span != nil {
> ```

Is this correct? I'm thinking of the case where we `span != nil` but that span is not recording. You might have to check `tracing.IsRecording(span)`.
___
*[pkg/sql/distsqlrun/outbox.go, line 263 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27332#-LH4H9WL7TvWs7kHP4RL:-LH4H9WL7TvWs7kHP4RM:b-cfapbx) ([raw file](https://github.com/cockroachdb/cockroach/blob/52bfa838b1389160874686683ca09212466afe3d/pkg/sql/distsqlrun/outbox.go#L263)):*
> ```Go
> 					}
> 				}
> 				return m.flush(ctx)
> ```

I think this `flush` call needs to go above the above code otherwise you might miss some bytes.

**Comment by solongordon** [comment]
@vilterp, check out https://github.com/cockroachdb/cockroachdb.github.io/pull/5. Currently we're rendering it as a tooltip when you mouseover an edge.

**Review by solongordon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27332)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/distsqlrun/outbox.go, line 194 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27332#-LH4GTfJ1adhxb5ZoxWS:-LH9vM9x0hlPzjj5M4dr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/52bfa838b1389160874686683ca09212466afe3d/pkg/sql/distsqlrun/outbox.go#L194)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Is this correct? I'm thinking of the case where we `span != nil` but that span is not recording. You might have to check `tracing.IsRecording(span)`.
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/outbox.go, line 263 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27332#-LH4H9WL7TvWs7kHP4RL:-LH9vUAu7ZDT2UmPf4ZB:b-inin2b) ([raw file](https://github.com/cockroachdb/cockroach/blob/52bfa838b1389160874686683ca09212466afe3d/pkg/sql/distsqlrun/outbox.go#L263)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think this `flush` call needs to go above the above code otherwise you might miss some bytes.
</blockquote></details>

Ah good call. I guess it has to be both before and after so the stats metadata will also be flushed.

**Pull request merged**
