### PR TITLE
Include grunning for s390x.

### PR DESCRIPTION
**Pull request by yasiribmcon**
PR https://github.com/cockroachdb/cockroach/pull/95291 excluded grunning from s390x as patched Go runtime is not available. 

Since we can refer go patch from [here](https://github.com/cockroachdb/cockroach/blob/master/build/teamcity/internal/release/build-and-publish-patched-go/diff.patch), we can manually patch go runtime for s390x so that grunning works for s390x.

Hence enabling back this library for s390x.

### CODE REVIEW

**Comment by sumeerbhola** [comment]
> Since we can refer go patch from [here](https://github.com/cockroachdb/cockroach/blob/master/build/teamcity/internal/release/build-and-publish-patched-go/diff.patch), we can manually patch go runtime for s390x so that grunning works for s390x.

Are you saying the existing patch works for s390x and all we need to do is remove s390x from the disabled list?

@rickystewart, since I am unsure of the build subtleties of the patched runtime.

**Comment by yasiribmcon** [comment]
Yes @sumeerbhola, go patch works fine for s390x machines, we only need to remove s390x from disabled list.
I have tested and found no regression on intel and s390x w.r.t these changes.

On a side note, we had also raised an issue previously to add s390x artifacts [here](https://github.com/cockroachdb/cockroach/issues/92393) fyi.

**Review by rickystewart — APPROVED** [review]

**Review by rickystewart — CHANGES_REQUESTED** [review]
Please do `bazel run :gazelle` to clean up `BUILD.bazel`

**Comment by yasiribmcon** [comment]
@rickystewart Done!

**Review by rickystewart — APPROVED** [review]

**Pull request merged**
