### PR TITLE
storage: optimize MVCCValueMerger

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### go.mod: bump gogoproto dep

Incorporate improvements to marshaling and unmarshaling.

Epic: none
Release note: None

#### storage: optimize MVCCValueMerger

We use a sync.Pool to speed up allocation of `MVCCValueMerger` and to
reuse internal slices. We use updated gogoproto marshalling and
unmarshaling code for which avoids unnecessary allocations and allows
reuse of slices.

```
name               old time/op    new time/op    delta
MVCCValueMerger-4    15.4µs ± 3%     7.6µs ± 1%  -50.67%  (p=0.000 n=8+8)

name               old alloc/op   new alloc/op   delta
MVCCValueMerger-4    86.2kB ± 0%    13.6kB ± 0%  -84.25%  (p=0.000 n=8+8)

name               old allocs/op  new allocs/op  delta
MVCCValueMerger-4      37.0 ± 0%       1.0 ± 0%  -97.30%  (p=0.000 n=8+8)
```

Informs: #133313
Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
I will try to see if I can find a way that is cleaner than copy/pasting .pb.go code. Perhaps a patch to `internal.pg.go`. Unfortunately we don't have control over the marshalling code generation - I tried to switch to using our `gogoproto` fork but it was impossible without also forking a lot of dependencies which also use `gogoproto`.

**Comment by RaduBerinde** [comment]
*[`pkg/roachpb/internal_optimized_pb.go` line 11 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/134481#-OBC8UlTCPuOh2BYyfQ9:-OBC8UlU9y7src-_v8vb:b-1h3cqj) ([raw file](https://github.com/cockroachdb/cockroach/blob/53fba58bd6045e76c54107612b16dd17c3bc1168/pkg/roachpb/internal_optimized_pb.go#L11)):*
> ```Go
> // InternalTimeSeriesData in internal.pb.go.
> //
> // The best way to look at the code in this file is to run `./dev gen protobuf`
> ```

Here is the diff from internal.pg.go: https://editor.mergely.com/bpbicztM

**Comment by RaduBerinde** [comment]
> Moving to draft for now. I will add functionality to protoc-gen-cockroach to apply a patch to an output file.

That turned to be way more messy. I moved the "semi-generated" code to its own file which is exempt from lint checks like `.pb.go` files are.

**Comment by jbowens** [comment]
should we consider moving away from protocol buffers in these low-level contexts (eg, something akin to flatbuffers)?

**Comment by RaduBerinde** [comment]
Yeah, it would make sense, unfortun

**Comment by RaduBerinde** [comment]
I think this is an ok solution for the time being. I will work on switching to our gogoproto fork (#129182) and incorporating these improvements so we generate better code.

**Comment by tbg** [comment]
@RaduBerinde I took the liberty to rework the commits in this PR so that the diffs in the optimized generated code could be reviewed (the original [diff](https://gist.github.com/tbg/4cf72c9a8cadac56f84b07b418a4d31b) couldn't meaningfully be inspected). There only diff between what I pushed and what you had is that I updated the comment at the top of `internal_optimized_pb.go` to say that the commit history has the diffs (vs. suggesting it could be inspected from diffing the files). Hope that was ok.

**Review by tbg — COMMENTED** [review]
> Reviewed 4 of 11 files at r4, 7 of 7 files at r7, 2 of 2 files at r8, 2 of 2 files at r10, 5 of 5 files at r11, 1 of 1 files at r12, 1 of 1 files at r13, 1 of 1 files at r14, 1 of 1 files at r15, 1 of 1 files at r16, 1 of 1 files at r17, 4 of 4 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134481)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @jbowens, @nvanbenschoten, and @RaduBerinde)

___
*[`pkg/roachpb/internal_optimized_pb.go` line 95 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/134481#-OBU_fGI31pqZ1RDfM_i:-OBU_fGJ-D-yqHS0GULQ:b2ni9gh) ([raw file](https://github.com/cockroachdb/cockroach/blob/53933a6bb6b5e9be2ac992e8f11a70c59c3bf37a/pkg/roachpb/internal_optimized_pb.go#L95)):*
> ```Go
> 	}
> 	if len(m.Count) > 0 {
> 		dAtA7 := make([]byte, len(m.Count)*10)
> ```

oof
___
*[`pkg/storage/pebble_merge.go` line 204 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/134481#-OBUavBH6hsR0I6ot9wa:-OBUavBH6hsR0I6ot9wb:b-sl0n8l) ([raw file](https://github.com/cockroachdb/cockroach/blob/90b4bf0e0ea60145c9d759897f612ef7a277d113/pkg/storage/pebble_merge.go#L204)):*
> ```Go
> }
> 
> func (t *MVCCValueMerger) returnToPool() {
> ```

Is there a convenient place to add a comment that anyone adding a field would notice?
___
*[`pkg/storage/pebble_merge.go` line 304 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/134481#-OBUbUgK7h_TE5Qscmod:-OBUbUgK7h_TE5Qscmoe:b-x0570x) ([raw file](https://github.com/cockroachdb/cockroach/blob/90b4bf0e0ea60145c9d759897f612ef7a277d113/pkg/storage/pebble_merge.go#L304)):*
> ```Go
> // format. When deduplicating, only the latest sample for a given offset is retained.
> func (t *MVCCValueMerger) Finish(includesBase bool) ([]byte, io.Closer, error) {
> 	if t.inPool {
> ```

Should these assertions be on in the production builds?
___
*[`pkg/storage/pebble_merge.go` line 320 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/134481#-OBUbnKU0O2ZTny85g0E:-OBUbnKU0O2ZTny85g0F:bxo7z23) ([raw file](https://github.com/cockroachdb/cockroach/blob/90b4bf0e0ea60145c9d759897f612ef7a277d113/pkg/storage/pebble_merge.go#L320)):*
> ```Go
> 		}
> 		// See the motivating comment in mvcc.proto.
> 		meta := &t.metaSubset // avoid allocation
> ```

is `t.metaSubset` zero (i.e. ready for reuse) at this point? The old code cleared it.
___
*[`pkg/storage/pebble_merge.go` line 368 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/134481#-OBUc5t37-kkpFVJ5GpM:-OBUc5t37-kkpFVJ5GpN:b54r17l) ([raw file](https://github.com/cockroachdb/cockroach/blob/90b4bf0e0ea60145c9d759897f612ef7a277d113/pkg/storage/pebble_merge.go#L368)):*
> ```Go
> 	marshaller := roachpb.MakeInternalTimeSeriesDataMarshaller(merged)
> 
> 	meta := &t.metaSubset // avoid allocation
> ```

same question about clearing.
___
*[`pkg/roachpb/internal_optimized_pb.go` line 10 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/134481#-OBUZqCt8goBeK8sxD66:-OBUZqCt8goBeK8sxD67:b-1zcpat) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7d61871adcbf1e3561fb5250157adcf0102f0e4/pkg/roachpb/internal_optimized_pb.go#L10)):*
> ```Go
> // ResetRetainingSlices clears all fields in the InternalTimeSeriesData, but
> // retains any backing slices.
> func (m *InternalTimeSeriesData) ResetRetainingSlices() {
> ```

Add comments on `InternalTimeSeriesData` to mention that changing this proto must take into account the existence of this new file. For example, adding a field would lead to bugs if updates weren't propagated manually.
___
*[`pkg/roachpb/internal_optimized_pb_test.go` line 17 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/134481#-OBUcBqk6KHbt3LiGqr_:-OBUcBqk6KHbt3LiGqra:b-4wz0u8) ([raw file](https://github.com/cockroachdb/cockroach/blob/90b4bf0e0ea60145c9d759897f612ef7a277d113/pkg/roachpb/internal_optimized_pb_test.go#L17)):*
> ```Go
> 
> func TestInternalSeriesDataMarshaller(t *testing.T) {
> 	rng := rand.New(rand.NewSource(timeutil.Now().UnixNano()))
> ```

no need to change anything, just mentioning `testing/quick.Check` in case you're not aware.
___
*[`pkg/roachpb/internal_optimized_pb_test.go` line 60 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/134481#-OBUcVYtE1aLMPCs1Nj8:-OBUcVYtE1aLMPCs1Nj9:bbbrin7) ([raw file](https://github.com/cockroachdb/cockroach/blob/90b4bf0e0ea60145c9d759897f612ef7a277d113/pkg/roachpb/internal_optimized_pb_test.go#L60)):*
> ```Go
> 		var i int
> 		m = InternalTimeSeriesData{}
> 		require.Zero(t, int(testing.AllocsPerRun(1000, func() {
> ```

oh, very cool. Didn't know about `AllocsPerRun`.

**Comment by tbg** [comment]
> should we consider moving away from protocol buffers in these low-level contexts (eg, something akin to flatbuffers)?

Yes, that would ultimately be desirable. However, we've been living for years with gogoproto and its unlikely that we'll manage to pull off a successful migration. It would have to be a priority, we'd need to support both for a while, and deal with the upgrades.
Raft traffic is another place where we'd prefer flatbuffers. Encoding overhead is very high in that area as well, and it doesn't help that we're using nested protobufs.

Forking gogoproto can potentially help us resolve the gridlock we're in w.r.t. protobuf upgrades, while also letting us make some very decent performance gains (as demonstrated here) without going all-in on the strategy in this PR.

**Comment by RaduBerinde** [comment]
Thank you Tobi! If we switch to the fork (https://github.com/cockroachdb/cockroach/pull/134918), I will move the optimizations into `gogoproto` so the generated code includes them by default. I will change this back to draft for now.

**Review by RaduBerinde — COMMENTED** [review]
Updated to use the most recent gogoproto PRs. I believe I addressed all your comments, PTAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134481#-:-OBbI0sq4XN6BeQq_Ir-:b83lya6)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @jbowens, @nvanbenschoten, and @tbg)

___
*[`pkg/storage/pebble_merge.go` line 204 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/134481#-OBUavBH6hsR0I6ot9wa:-OBanHJRB5dq9w25E_ri:bfa8js1) ([raw file](https://github.com/cockroachdb/cockroach/blob/90b4bf0e0ea60145c9d759897f612ef7a277d113/pkg/storage/pebble_merge.go#L204)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Is there a convenient place to add a comment that anyone adding a field would notice?
</blockquote></details>

Done, added inside the struct.
___
*[`pkg/storage/pebble_merge.go` line 304 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/134481#-OBUbUgK7h_TE5Qscmod:-OBanQHtC4-ED4Kp2Pjp:b125hxd) ([raw file](https://github.com/cockroachdb/cockroach/blob/90b4bf0e0ea60145c9d759897f612ef7a277d113/pkg/storage/pebble_merge.go#L304)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Should these assertions be on in the production builds?
</blockquote></details>

I don't think this causes much overhead since it's one check per merge. I think an error would be preferable to some kind of unpredictable behavior.
___
*[`pkg/storage/pebble_merge.go` line 320 at r18](https://reviewable.io/reviews/cockroachdb/cockroach/134481#-OBUbnKU0O2ZTny85g0E:-OBanmmV36zRp0f4D1AT:b9jmgxk) ([raw file](https://github.com/cockroachdb/cockroach/blob/90b4bf0e0ea60145c9d759897f612ef7a277d113/pkg/storage/pebble_merge.go#L320)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

is `t.metaSubset` zero (i.e. ready for reuse) at this point? The old code cleared it.
</blockquote></details>

We do clear it in returnToPool. I made that code a bit more robust.
___
*[`pkg/roachpb/internal_optimized_pb.go` line 10 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/134481#-OBUZqCt8goBeK8sxD66:-OBan2482H8AuhGGE32V:b-vpw6sc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d7d61871adcbf1e3561fb5250157adcf0102f0e4/pkg/roachpb/internal_optimized_pb.go#L10)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Add comments on `InternalTimeSeriesData` to mention that changing this proto must take into account the existence of this new file. For example, adding a field would lead to bugs if updates weren't propagated manually.
</blockquote></details>

Done, and updated the code so we always clear everything regardless.

**Comment by RaduBerinde** [comment]
Updated to reuse `t.meta.RawBytes` as well (the `Unmarshal` generated code already tries to reuse it).

**Review by tbg — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r21, 5 of 5 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134481#-:-OC-8COb9i7VkonH5B0A:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @jbowens and @nvanbenschoten)

**Pull request merged**
