### PR TITLE
sql: refactor unimplemented statements into one file pkg/sql/unimplem…

### LINKED ISSUE #137615: sql: refactor unimplemented statements into one file pkg/sql/unimplemented.go
Move the files mentioned in this comment to a new file  pkg/sql/unimplemented.go, the unimplemented comment on type code can be moved here also.

https://github.com/cockroachdb/cockroach/pull/137105#pullrequestreview-2509272955

Also move `dropOwnedByNode` from pkg/sql/drop_owned_by.go.

Jira issue: CRDB-45671

### PR DESCRIPTION
**Pull request by Dedej-Bergin**
…ented.go

Moved files with unimplemented stubs into just 1 file unimplemented.go. These unimplemented stubs work in DSC only and we will not implement them on the legacy schema changer.

Fixes: #137615
Release note: none

### CODE REVIEW

**Comment by Dedej-Bergin** [comment]
Wanted to point out that I removed `telemetry.Inc(sqltelemetry.CreateDropOwnedByCounter())` from DropOwnedBy. This has me thinking if we should add telemetry to all our unimplemented legacy statements to let us know how much demand there is for explicit DDL transactions.

**Review by rafiss — APPROVED** [review]
this lgtm! except the PR says `Fixes: #45671`, but that looks like the wrong link.

**Review by Dedej-Bergin — COMMENTED** [review]
Thanks for the review! I accidentally put the jira issue number instead of the github one. Just updated it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137795#-:-OEVmJr_Bj_fSLr8JoUG:bumvub2)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained

**Pull request merged**
