### PR TITLE
kvfollowerreadsccl: plug bounded staleness into the execution engine

### LINKED ISSUE #67556: sql: plumb min_timestamp_bound to TableReader
Part of #66020.
Needed for **stage 1**.

See https://github.com/cockroachdb/cockroach/blob/025c53decd8eb00cb70a1d410692026c9f8614dc/docs/RFCS/20210519_bounded_staleness_reads.md#sql-execution.
Prototyped in #62239.

### PR DESCRIPTION
**Pull request by otan**
See individual commits for details.

Resolves #67556.

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
This all looks very good! I imagine #68969 will be the more contention part of all of this.

> Reviewed 2 of 2 files at r5, 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68967#-:-MhFXCXJCQPNvt9Cw5O6:b1qglxs)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan, @rhu713, @rytaft, and @stevendanna)

___
*[pkg/ccl/kvccl/kvfollowerreadsccl/boundedstaleness_test.go, line 129 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68967#-MhFSj_c-AuNt3LLftlz:-MhFSj_c-AuNt3LLftm-:b-92o3ys) ([raw file](https://github.com/cockroachdb/cockroach/blob/5702d74f37efe1c632e5448f2882baac5a3db4f3/pkg/ccl/kvccl/kvfollowerreadsccl/boundedstaleness_test.go#L129)):*
> ```Go
> func (bse *boundedStalenessEvents) String() string {
> 	var sb strings.Builder
> 	sb.WriteString(fmt.Sprintf("events (%d found):\n", len(bse.events)))
> ```

`fmt.Fprintf(&sb, ...` here and below.
___
*[pkg/ccl/kvccl/kvfollowerreadsccl/testdata/boundedstaleness/single_row, line 14 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68967#-MhFTvug8YCB5RUrdRwh:-MhFTvug8YCB5RUrdRwi:bmf4f3d) ([raw file](https://github.com/cockroachdb/cockroach/blob/5702d74f37efe1c632e5448f2882baac5a3db4f3/pkg/ccl/kvccl/kvfollowerreadsccl/testdata/boundedstaleness/single_row#L14)):*
> ```
> ----
> 
> # If we try read a timestamp that is impossible to satisfy with a follower read,
> ```

"try to read"
___
*[pkg/ccl/kvccl/kvfollowerreadsccl/testdata/boundedstaleness/single_row, line 18 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68967#-MhFVBjX-VLgWl4kUvCc:-MhFVBjX-VLgWl4kUvCd:b-y1s4ol) ([raw file](https://github.com/cockroachdb/cockroach/blob/5702d74f37efe1c632e5448f2882baac5a3db4f3/pkg/ccl/kvccl/kvfollowerreadsccl/testdata/boundedstaleness/single_row#L18)):*
> ```
> # We always do bounded staleness reads from node_idx 2, as node_idx 0 in a
> # TestCluster is always the leaseholder.
> query idx=2 show-events
> ```

Do we ever run `query` without `show-events`? If not, should we just bake in the directive into `query`?
___
*[pkg/ccl/kvccl/kvfollowerreadsccl/testdata/boundedstaleness/single_row, line 22 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68967#-MhFU8NvCuph4udTUQeq:-MhFU8NvCuph4udTUQer:b-2que9f) ([raw file](https://github.com/cockroachdb/cockroach/blob/5702d74f37efe1c632e5448f2882baac5a3db4f3/pkg/ccl/kvccl/kvfollowerreadsccl/testdata/boundedstaleness/single_row#L22)):*
> ```
> ----
> 1
> events (1 found):
> ```

Is the idea that future improvements to bounded staleness reads will allow for multiple events?
___
*[pkg/ccl/kvccl/kvfollowerreadsccl/testdata/boundedstaleness/single_row, line 64 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68967#-MhFUelr3eE_VQNtow-V:-MhFUelr3eE_VQNtow-W:b-f2d0zl) ([raw file](https://github.com/cockroachdb/cockroach/blob/5702d74f37efe1c632e5448f2882baac5a3db4f3/pkg/ccl/kvccl/kvfollowerreadsccl/testdata/boundedstaleness/single_row#L64)):*
> ```
> # Note we have to wait until a match here, in case a follower read reads an
> # older version of the data.
> query idx=2 show-events wait-until-follower-read wait-until-match
> ```

Do we need `wait-until-follower-read` if we're also including `wait-until-match`? Doesn't the latter encompass the role of the former?
___
*[pkg/ccl/kvccl/kvfollowerreadsccl/testdata/boundedstaleness/single_row, line 72 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68967#-MhFUnsa5k4TV1kARb6m:-MhFUnsa5k4TV1kARb6n:b-unqu6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5702d74f37efe1c632e5448f2882baac5a3db4f3/pkg/ccl/kvccl/kvfollowerreadsccl/testdata/boundedstaleness/single_row#L72)):*
> ```
> 
> query idx=2 show-events
> SELECT * FROM t AS OF SYSTEM TIME with_min_timestamp(now() - '10s') WHERE pk = 1
> ```

Is the clock frozen in these tests? If not, isn't it possible for the follower to catch up to exactly `now()-10s` (and no further) in the `wait-until-match` query and then fall progressively further behind?
___
*[pkg/ccl/kvccl/kvfollowerreadsccl/testdata/boundedstaleness/single_row, line 108 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68967#-MhFVUlmCoarfKZ-46Og:-MhFVUlmCoarfKZ-46Oh:b-55b36h) ([raw file](https://github.com/cockroachdb/cockroach/blob/5702d74f37efe1c632e5448f2882baac5a3db4f3/pkg/ccl/kvccl/kvfollowerreadsccl/testdata/boundedstaleness/single_row#L108)):*
> ```
> # Set a super high closed bounded staleness target and execute a schema change.
> exec
> SET CLUSTER SETTING kv.closed_timestamp.target_duration = '1hr';
> ```

I'm a bit concerned about the async nature of cluster setting propagation here. Could this cause flakiness? How do we deal with this in standard SQL logic tests?
___
*[pkg/sql/pgwire/pgcode/codes.go, line 362 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68967#-MhFJ_ZaCJqdz2ZkkV7u:-MhFJ_ZaCJqdz2ZkkV7v:b-hbgvkg) ([raw file](https://github.com/cockroachdb/cockroach/blob/583e51dd294365fdbefe0db99045d7909e27a241/pkg/sql/pgwire/pgcode/codes.go#L362)):*
> ```Go
> 	// Section: Class 54 - Program Limit Exceeded (Cockroach extension)
> 
> 	// UnsatisfiableBoundedStaleness signals that the bounded staleness query
> ```

Out of curiosity, which PG code do you think we should use for when a query runs below the MVCC GC timestamp? Right now, it returns a raw `BatchTimestampBeforeGCError` with no PG code.

```
➜ ./cockroach demo

demo@127.0.0.1:26257/movr> alter table rides configure zone using gc.ttlseconds = 1;
CONFIGURE ZONE 1

demo@127.0.0.1:26257/movr> select * from rides as of system time '-2s';
ERROR: batch timestamp 1629140312.708334000,0 must be after replica GC threshold 1629140313.709146000,0
```

I ask because I imagine these two errors should be in the same class.
___
*[pkg/sql/row/errors.go, line 93 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68967#-MhFKISCEl1vDe_2b0Pu:-MhFKISCEl1vDe_2b0Pv:bsx6996) ([raw file](https://github.com/cockroachdb/cockroach/blob/583e51dd294365fdbefe0db99045d7909e27a241/pkg/sql/row/errors.go#L93)):*
> ```Go
> // key-value fetch to a user friendly SQL error.
> func ConvertFetchError(ctx context.Context, descForKey KeyToDescTranslator, err error) error {
> 	var wiErr *roachpb.WriteIntentError
> ```

This is kind of an interesting pattern that we don't have much precedent for because of how new `errors.As` is. I wonder if it should look more like:
```go
var wiErr *roachpb.WriteIntentError
var bsErr *roachpb.MinTimestampBoundUnsatisfiableError
switch {
case errors.As(err, &wiErr):
    key := wiErr.Intents[0].Key
    desc, _ := descForKey.KeyToDesc(key)
    return NewLockNotAvailableError(ctx, desc, key, wiErr.Reason)
case errors.As(err, &bsErr):
    return pgerror.WithCandidateCode(
        err,
        pgcode.UnsatisfiableBoundedStaleness,
    )
}
return err
```

Or even better, to batch the heap allocations:
```go
var errs struct {
    wi *roachpb.WriteIntentError
    bs *roachpb.MinTimestampBoundUnsatisfiableError
}
switch {
case errors.As(err, &errs.wi):
    key := errs.wi.Intents[0].Key
    desc, _ := descForKey.KeyToDesc(key)
    return NewLockNotAvailableError(ctx, desc, key, errs.wi.Reason)
case errors.As(err, &errs.bs):
    return pgerror.WithCandidateCode(
        err,
        pgcode.UnsatisfiableBoundedStaleness,
    )
}
return err
```
___
*[pkg/sql/row/kv_fetcher.go, line 60 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68967#-MhFWgeFC_SUn-UjjTC3:-MhFWgeFC_SUn-UjjTC4:b-204twa) ([raw file](https://github.com/cockroachdb/cockroach/blob/5702d74f37efe1c632e5448f2882baac5a3db4f3/pkg/sql/row/kv_fetcher.go#L60)):*
> ```Go
> 	forceProductionKVBatchSize bool,
> ) (*KVFetcher, error) {
> 	sendFn := makeKVBatchFetcherDefaultSendFunc(txn)
> ```

Consider only calling `makeKVBatchFetcherDefaultSendFunc` on the `else` branch to avoid an unnecessary heap allocation on the bounded staleness path.

Or better, continue to also accept the `txn` in `makeKVBatchFetcher` so that you can pass static function references with the following signature instead of having to create a closure here:
```
func(ctx context.Context, txn *kv.Txn, ba roachpb.BatchRequest) (*roachpb.BatchResponse, error)
```

**Review by otan — COMMENTED** [review]
> This all looks very good! I imagine #68969 will be the more contention part of all of this.

Yeah, there's a reason why I made it a separate PR :D

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68967#-:-MhFyZetDG9uTR8l6I2h:bdc1123)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten, @rhu713, @rytaft, and @stevendanna)

___
*[pkg/ccl/kvccl/kvfollowerreadsccl/boundedstaleness_test.go, line 129 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68967#-MhFSj_c-AuNt3LLftlz:-MhFuIyB29JcqIWpkIM_:b-oqcalq) ([raw file](https://github.com/cockroachdb/cockroach/blob/5702d74f37efe1c632e5448f2882baac5a3db4f3/pkg/ccl/kvccl/kvfollowerreadsccl/boundedstaleness_test.go#L129)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`fmt.Fprintf(&sb, ...` here and below.
</blockquote></details>

have to handle the error or the linter cries (yuck), it's a test so i prefer to leave it as is.
___
*[pkg/ccl/kvccl/kvfollowerreadsccl/testdata/boundedstaleness/single_row, line 18 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68967#-MhFVBjX-VLgWl4kUvCc:-MhFxWuz6bEIZcnpb8xP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5702d74f37efe1c632e5448f2882baac5a3db4f3/pkg/ccl/kvccl/kvfollowerreadsccl/testdata/boundedstaleness/single_row#L18)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we ever run `query` without `show-events`? If not, should we just bake in the directive into `query`?
</blockquote></details>

Done.
___
*[pkg/ccl/kvccl/kvfollowerreadsccl/testdata/boundedstaleness/single_row, line 22 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68967#-MhFU8NvCuph4udTUQeq:-MhFxY4z5lIgdG1kEhHX:bb77uci) ([raw file](https://github.com/cockroachdb/cockroach/blob/5702d74f37efe1c632e5448f2882baac5a3db4f3/pkg/ccl/kvccl/kvfollowerreadsccl/testdata/boundedstaleness/single_row#L22)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is the idea that future improvements to bounded staleness reads will allow for multiple events?
</blockquote></details>

Yep!
___
*[pkg/ccl/kvccl/kvfollowerreadsccl/testdata/boundedstaleness/single_row, line 64 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68967#-MhFUelr3eE_VQNtow-V:-MhFxZ3P4vFw7LFmyE7O:b-m2zlt6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5702d74f37efe1c632e5448f2882baac5a3db4f3/pkg/ccl/kvccl/kvfollowerreadsccl/testdata/boundedstaleness/single_row#L64)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we need `wait-until-follower-read` if we're also including `wait-until-match`? Doesn't the latter encompass the role of the former?
</blockquote></details>

We want `--rewrite` to not `wait-until-match`, but still `wait-until-follower-read` so it rewrites with correct output. i've added a comment in the test codes.
___
*[pkg/ccl/kvccl/kvfollowerreadsccl/testdata/boundedstaleness/single_row, line 72 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68967#-MhFUnsa5k4TV1kARb6m:-MhFyKJu0xcz5S49Cf_a:b-n47206) ([raw file](https://github.com/cockroachdb/cockroach/blob/5702d74f37efe1c632e5448f2882baac5a3db4f3/pkg/ccl/kvccl/kvfollowerreadsccl/testdata/boundedstaleness/single_row#L72)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is the clock frozen in these tests? If not, isn't it possible for the follower to catch up to exactly `now()-10s` (and no further) in the `wait-until-match` query and then fall progressively further behind?
</blockquote></details>

Clock is not frozen (how do i do that?), but the rest of these tests don't really care if we don't catch up past now()-10s.
unless i'm missing something and we should!
___
*[pkg/ccl/kvccl/kvfollowerreadsccl/testdata/boundedstaleness/single_row, line 108 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68967#-MhFVUlmCoarfKZ-46Og:-MhFvlfp2x_nlGT9YEjy:b6jsr91) ([raw file](https://github.com/cockroachdb/cockroach/blob/5702d74f37efe1c632e5448f2882baac5a3db4f3/pkg/ccl/kvccl/kvfollowerreadsccl/testdata/boundedstaleness/single_row#L108)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm a bit concerned about the async nature of cluster setting propagation here. Could this cause flakiness? How do we deal with this in standard SQL logic tests?
</blockquote></details>

i don't think we do, looks like the tests are alright though? i've seen lots of CLUSTER SETTING sets throughout code.
is there a wait-for-cluster-setting-propagate in tests i should use?
___
*[pkg/sql/pgwire/pgcode/codes.go, line 362 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68967#-MhFJ_ZaCJqdz2ZkkV7u:-MhFvbIe1Uni577qstTx:b-ef3yjh) ([raw file](https://github.com/cockroachdb/cockroach/blob/583e51dd294365fdbefe0db99045d7909e27a241/pkg/sql/pgwire/pgcode/codes.go#L362)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Out of curiosity, which PG code do you think we should use for when a query runs below the MVCC GC timestamp? Right now, it returns a raw `BatchTimestampBeforeGCError` with no PG code.

```
➜ ./cockroach demo

demo@127.0.0.1:26257/movr> alter table rides configure zone using gc.ttlseconds = 1;
CONFIGURE ZONE 1

demo@127.0.0.1:26257/movr> select * from rides as of system time '-2s';
ERROR: batch timestamp 1629140312.708334000,0 must be after replica GC threshold 1629140313.709146000,0
```

I ask because I imagine these two errors should be in the same class.
</blockquote></details>

it's probably worth making a new custom error under this class (it looks like `XXC`  where XX = class is reserved for our own internal usage)
___
*[pkg/sql/row/kv_fetcher.go, line 60 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68967#-MhFWgeFC_SUn-UjjTC3:-MhFw-Nm0W0ETw5yaPj1:b-ycmc1c) ([raw file](https://github.com/cockroachdb/cockroach/blob/5702d74f37efe1c632e5448f2882baac5a3db4f3/pkg/sql/row/kv_fetcher.go#L60)):*
> Or better, continue to also accept the txn in makeKVBatchFetcher so that you can pass static function references with the following signature instead of having to create a closure here:

That required going down deep into the stack, and passing `txn` to the `txnKVFetcher` stuff, so i'm going to do the if right now (this is ~ the same as before).

**Review by rytaft — APPROVED** [review]
SQL stuff :lgtm:

> Reviewed 1 of 18 files at r1, 3 of 3 files at r4, 1 of 2 files at r5, 1 of 11 files at r7, 8 of 10 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68967#-:-MhHCvFh0xKZ7u9EF-kK:b3ce3z)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten, @otan, @rhu713, and @stevendanna)

___
*[-- commits, line 109 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/68967#-MhHCTi4BWK3oShi8YXm:-MhHCTi4BWK3oShi8YXn:b53f44y) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab4691aa62dc9c45312a6c0a8e984499d7ada643/-- commits#L109)):*
nit: keep track of?

**Review by nvb — APPROVED** [review]
:lgtm:

This should be good to rebase now, as the kv stuff just landed.

> Reviewed 1 of 11 files at r7, 9 of 10 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68967#-:-MhHOqEe2SCL7M3poXy_:b-twtajf)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten, @otan, @rhu713, @rytaft, and @stevendanna)

___
*[pkg/ccl/kvccl/kvfollowerreadsccl/testdata/boundedstaleness/single_row, line 72 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68967#-MhFUnsa5k4TV1kARb6m:-MhHMzofER15EOTCCQcY:bv721f6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5702d74f37efe1c632e5448f2882baac5a3db4f3/pkg/ccl/kvccl/kvfollowerreadsccl/testdata/boundedstaleness/single_row#L72)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

Clock is not frozen (how do i do that?), but the rest of these tests don't really care if we don't catch up past now()-10s.
unless i'm missing something and we should!
</blockquote></details>

Well they pass a min_timestamp of now()-10s, so if now() keeps advancing with the clock but the closed timestamp freezes, they may be unable to be served locally. But maybe that's such a rare possibility that we're ok with how this is written.
___
*[pkg/ccl/kvccl/kvfollowerreadsccl/testdata/boundedstaleness/single_row, line 108 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68967#-MhFVUlmCoarfKZ-46Og:-MhHNP1GAN6no3UXh91R:be2gcsz) ([raw file](https://github.com/cockroachdb/cockroach/blob/5702d74f37efe1c632e5448f2882baac5a3db4f3/pkg/ccl/kvccl/kvfollowerreadsccl/testdata/boundedstaleness/single_row#L108)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

i don't think we do, looks like the tests are alright though? i've seen lots of CLUSTER SETTING sets throughout code.
is there a wait-for-cluster-setting-propagate in tests i should use?
</blockquote></details>

I'm not quite sure. I thought we had code to read the cluster setting from each other node in the cluster to make sure it's gone into effect. But now that I think of it, that may actually be part of `SET CLUSTER SETTING` itself. If this isn't flaky, I wouldn't worry about it.
___
*[pkg/sql/pgwire/pgcode/codes.go, line 362 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68967#-MhFJ_ZaCJqdz2ZkkV7u:-MhHOvtW52hKJl0VOYXQ:b-44ad0) ([raw file](https://github.com/cockroachdb/cockroach/blob/583e51dd294365fdbefe0db99045d7909e27a241/pkg/sql/pgwire/pgcode/codes.go#L362)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

it's probably worth making a new custom error under this class (it looks like `XXC`  where XX = class is reserved for our own internal usage)
</blockquote></details>

But I guess the question I'm asking is whether you think this is the right class for that error code as well. The reason why I ask is that I'm not entirely sure that `Program Limit Exceeded` is the right class for `UnsatisfiableBoundedStaleness` (though I don't see a better one), but I am pretty sure that `UnsatisfiableBoundedStaleness` and BatchTimestampBeforeGCError's eventual code should be in the same class. So does `Program Limit Exceeded` also sound right to you for the GC timestamp error code? If so, I'm happy with this.
___
*[pkg/sql/row/kv_fetcher.go, line 60 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68967#-MhFWgeFC_SUn-UjjTC3:-MhHOECy7MSNEW9SKoM2:brid659) ([raw file](https://github.com/cockroachdb/cockroach/blob/5702d74f37efe1c632e5448f2882baac5a3db4f3/pkg/sql/row/kv_fetcher.go#L60)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

> Or better, continue to also accept the txn in makeKVBatchFetcher so that you can pass static function references with the following signature instead of having to create a closure here:

That required going down deep into the stack, and passing `txn` to the `txnKVFetcher` stuff, so i'm going to do the if right now (this is ~ the same as before).
</blockquote></details>

:thumbsup: I guess I also missed the fact that we were capturing `bsHeader`, so it would be even harder to avoid the allocation on the bounded staleness path.

nit: any reason to pull `makeKVBatchFetcherDefaultSendFunc` out instead of inlining it here? Or conversely, any reason not to pull out a constructor for the bounded staleness `sendFunc`? The asymmetry is a bit odd to me, given that there's only one use of each.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68967)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @nvanbenschoten, @otan, @rhu713, @rytaft, and @stevendanna)

___
*[pkg/sql/pgwire/pgcode/codes.go, line 362 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/68967#-MhFJ_ZaCJqdz2ZkkV7u:-MhHhVpPDqZ-4WrzIdru:bdjdocg) ([raw file](https://github.com/cockroachdb/cockroach/blob/583e51dd294365fdbefe0db99045d7909e27a241/pkg/sql/pgwire/pgcode/codes.go#L362)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

But I guess the question I'm asking is whether you think this is the right class for that error code as well. The reason why I ask is that I'm not entirely sure that `Program Limit Exceeded` is the right class for `UnsatisfiableBoundedStaleness` (though I don't see a better one), but I am pretty sure that `UnsatisfiableBoundedStaleness` and BatchTimestampBeforeGCError's eventual code should be in the same class. So does `Program Limit Exceeded` also sound right to you for the GC timestamp error code? If so, I'm happy with this.
</blockquote></details>

as discussed offline, `CDB` is a new class for these errors.
___
*[pkg/sql/row/kv_fetcher.go, line 60 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/68967#-MhFWgeFC_SUn-UjjTC3:-MhHggjY4exLken62Tg_:b-iqyw9k) ([raw file](https://github.com/cockroachdb/cockroach/blob/5702d74f37efe1c632e5448f2882baac5a3db4f3/pkg/sql/row/kv_fetcher.go#L60)):*
> nit: any reason to pull makeKVBatchFetcherDefaultSendFunc out instead of inlining it here? 

it's used in another place :)

```
pkg/sql/row/fetcher.go
583:		makeKVBatchFetcherDefaultSendFunc(txn),
```

but bounded staleness is only one.

**Comment by otan** [comment]
bors r=nvanbenschoten,rytaft

tftrs!

**Comment by otan** [comment]
lost a commit during rebase, woops!

bors r=nvanbenschoten,rytaft

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68967)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

___
*[pkg/sql/colfetcher/colbatch_scan.go, line 237 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/68967#-Mv-dqdzAFTNQ_n83V6n:-Mv-dqdzAFTNQ_n83V6o:b9x1h2f) ([raw file](https://github.com/cockroachdb/cockroach/blob/edf5dafc98fcddf5cb8afb7145aa4156c4253add/pkg/sql/colfetcher/colbatch_scan.go#L237)):*
> ```Go
> 		// schema.
> 		if aost.Timestamp.Less(table.GetModificationTime()) {
> 			ts = table.GetModificationTime()
> ```

AFAICT, there is no corresponding code in the row execution engine.. I don't think we are setting the bounded staleness header at all in the row engine?  CC @yuzefovich

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/colfetcher/colbatch_scan.go, line 237 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/68967#-Mv-dqdzAFTNQ_n83V6n:-Mv-gR6AE0-LnB02upBm:b-jdgtdq) ([raw file](https://github.com/cockroachdb/cockroach/blob/edf5dafc98fcddf5cb8afb7145aa4156c4253add/pkg/sql/colfetcher/colbatch_scan.go#L237)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

AFAICT, there is no corresponding code in the row execution engine.. I don't think we are setting the bounded staleness header at all in the row engine?  CC @yuzefovich 
</blockquote></details>

Also, can't we make this timestamp adjustment at planning time? Feels strange that we do it in the bowels of execution code.

**Comment by otan** [comment]
___
*[pkg/sql/colfetcher/colbatch_scan.go, line 237 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/68967#-Mv-dqdzAFTNQ_n83V6n:-Mv0WOHj0xhgteBeAW3Z:b-lshhyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/edf5dafc98fcddf5cb8afb7145aa4156c4253add/pkg/sql/colfetcher/colbatch_scan.go#L237)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Also, can't we make this timestamp adjustment at planning time? Feels strange that we do it in the bowels of execution code.
</blockquote></details>

yeah this wasn't done for the row exec engine and was an assumed limitation.
ah didn't think about doing it at planning time! if we could that'd be better, this seemed like the best place at the time as it was the least hoops to jump, but open to it going elsewhere

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/colfetcher/colbatch_scan.go, line 237 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/68967#-Mv-dqdzAFTNQ_n83V6n:-Mv1Baym-Jhndvip6g5H:b-2kd3lz) ([raw file](https://github.com/cockroachdb/cockroach/blob/edf5dafc98fcddf5cb8afb7145aa4156c4253add/pkg/sql/colfetcher/colbatch_scan.go#L237)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

yeah this wasn't done for the row exec engine and was an assumed limitation.
ah didn't think about doing it at planning time! if we could that'd be better, this seemed like the best place at the time as it was the least hoops to jump, but open to it going elsewhere
</blockquote></details>

I might play with it a bit. Is there a test for this case, where we have to adjust the timestamp because of the descriptor modification time?

**Comment by otan** [comment]
___
*[pkg/sql/colfetcher/colbatch_scan.go, line 237 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/68967#-Mv-dqdzAFTNQ_n83V6n:-Mv1luxD10hiofVTtE_J:b-xri8je) ([raw file](https://github.com/cockroachdb/cockroach/blob/edf5dafc98fcddf5cb8afb7145aa4156c4253add/pkg/sql/colfetcher/colbatch_scan.go#L237)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I might play with it a bit. Is there a test for this case, where we have to adjust the timestamp because of the descriptor modification time?
</blockquote></details>

yes! checkout `TestBoundedStalenessDataDriven`

**Comment by otan** [comment]
___
*[pkg/sql/colfetcher/colbatch_scan.go, line 237 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/68967#-Mv-dqdzAFTNQ_n83V6n:-Mv1mCnKCCGMCje7atYp:b-vrh9e7) ([raw file](https://github.com/cockroachdb/cockroach/blob/edf5dafc98fcddf5cb8afb7145aa4156c4253add/pkg/sql/colfetcher/colbatch_scan.go#L237)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

yes! checkout `TestBoundedStalenessDataDriven`
</blockquote></details>

https://github.com/cockroachdb/cockroach/blob/fa193c3277de67408c6507bf0e2ef036ab6f070b/pkg/ccl/kvccl/kvfollowerreadsccl/testdata/boundedstaleness/single_row#L137

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/colfetcher/colbatch_scan.go, line 237 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/68967#-Mv-dqdzAFTNQ_n83V6n:-Mv5Qr7R8j-UWD3LR-qj:b-661ucn) ([raw file](https://github.com/cockroachdb/cockroach/blob/edf5dafc98fcddf5cb8afb7145aa4156c4253add/pkg/sql/colfetcher/colbatch_scan.go#L237)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

https://github.com/cockroachdb/cockroach/blob/fa193c3277de67408c6507bf0e2ef036ab6f070b/pkg/ccl/kvccl/kvfollowerreadsccl/testdata/boundedstaleness/single_row#L137
</blockquote></details>

I assume that when using bounded staleness, we still read everything at the same timestamp correct? So it's not useful to set the MinTimestampBound to different values for different table scans, it should be equivalent to set it to the max value, is this right?

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/colfetcher/colbatch_scan.go, line 237 at r17](https://reviewable.io/reviews/cockroachdb/cockroach/68967#-Mv-dqdzAFTNQ_n83V6n:-Mv5UUch5XkBTLVTAG6p:b-6lazwh) ([raw file](https://github.com/cockroachdb/cockroach/blob/edf5dafc98fcddf5cb8afb7145aa4156c4253add/pkg/sql/colfetcher/colbatch_scan.go#L237)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I assume that when using bounded staleness, we still read everything at the same timestamp correct? So it's not useful to set the MinTimestampBound to different values for different table scans, it should be equivalent to set it to the max value, is this right?
</blockquote></details>

I tried to do this instead:
```diff
--- a/pkg/sql/distsql_physical_planner.go
+++ b/pkg/sql/distsql_physical_planner.go
@@ -1260,6 +1260,15 @@ func (dsp *DistSQLPlanner) CheckInstanceHealthAndVersion(
 func (dsp *DistSQLPlanner) createTableReaders(
        planCtx *PlanningCtx, n *scanNode,
 ) (*PhysicalPlan, error) {
+       // If the descriptor's modification time is after the bounded staleness min bound,
+       // we have to increase the min bound.
+       // Otherwise, we would have table data which would not correspond to the correct
+       // schema.
+       if aost := planCtx.EvalContext().AsOfSystemTime; aost != nil && aost.BoundedStaleness {
+               if mTime := n.desc.GetModificationTime(); aost.Timestamp.Less(mTime) {
+                       aost.Timestamp = mTime
+               }
+       }
```

But this test fails to return any events: https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/kvccl/kvfollowerreadsccl/testdata/boundedstaleness/single_row#L173

Any ideas? Shouldn't this be equivalent, given that we're scanning a single table?

The context here is that I'm trying to remove the table descriptor from TableReader (and replace it with a much smaller proto that describes the index encoding). I'd rather not include the modification timestamp in this smaller proto just for this usecase. But I don't know much about this feature so I'm not sure what I'm doing wrong.

**Comment by otan** [comment]
On my phone and the weekend, but I'd take a look at the kv traces and see what changed. We only log events in the tests if

`if sp.Operation == "dist sender send" && spans[sp.ParentSpanID].Operation == "colbatchscan"`.

so did something change?

Your assumption looks right to me but it's been a while and I won't have a chance to double check for a bit. 

Can take a closer look next week.

**Comment by RaduBerinde** [comment]
If you have a bit of time to look at it, it would be awesome. Otherwise I think I will move forward with my change and include the modification time in the new spec for now (with a TODO to remove later).

**Pull request merged**
