### PR TITLE
storage: fix NPE in RaftTransport

### LINKED ISSUE #26995: panic: stopper.go:176: runtime.errorString: runtime error: invalid memory address or nil pointer derefer...
https://sentry.io/cockroach-labs/cockroachdb/issues/591033321/

```
*log.safeError: stopper.go:176: runtime.errorString: runtime error: invalid memory address or nil pointer dereference
  File "github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go", line 583, in 1
  File "github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go", line 426, in processQueue
  File "github.com/cockroachdb/cockroach/pkg/storage/raft_transport.go", line 589, in func1
  File "github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go", line 193, in func1
...
(7 additional frame(s) were not displayed)

stopper.go:176: runtime.errorString: runtime error: invalid memory address or nil pointer dereference
```

### PR DESCRIPTION
**Pull request by tbg**
A recent refactor left the RaftTransport vulnerable to an NPE if the
underlying connection closed. Fixed the bug and added a regression test
that randomly closes the underlying listener and/or context to shake out
similar bugs.

Fixes #26995.

Release note: None

### CODE REVIEW

**Comment by tschottdorf** [comment]
TFTR!

bors r=bdarnell

**Comment by RaduBerinde** [comment]
```
lint_test.go:907: /go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport_unit_test.go:89:2: this value of resolver is never used (SA4006)
lint_test.go:907: /go/src/github.com/cockroachdb/cockroach/pkg/storage/raft_transport_unit_test.go:39:6: type dummyMultiRaftServer is unused (U1000)
```

**Comment by tschottdorf** [comment]
Argh, sorry for the failed bors run. I fixed the previous lint errors and had hoped for the best. Fixing.

**Comment by tschottdorf** [comment]
bors r=bdarnell

**Pull request merged**
