### PR TITLE
roachtest: add minimal secure support to multitenant

### LINKED ISSUE #79844: multitenant: add certificates to roachtest multitenant support
Currently roachtest starts up mt server using "-insecure" so when they connect to the server there is no ssl certificate which is where we find the tenant id so all the sql pods appear to the KV server as the "system" tenant.  This makes it impossible to do any real admission control performance testing with roachtest.

### PR DESCRIPTION
**Pull request by cucaroach**
The existing multitenant roachtests operated in insecure mode which
means to the kvserver they looked like any other CRDB node, the tenant
id is transfered in the certificate so secure mode must be used to
really test multitenant support.

A more ambitious task will be to take this further and move all the
multitenant stuff into roachprod.

Fixes: #79844

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> Reviewed 3 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79960)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach and @erikgrinaker)

___
*[pkg/cmd/roachtest/cluster.go, line 2355 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79960#-N-hfe0e7ekfZTnsKK_8:-N-hfe0e7ekfZTnsKK_9:b-pb9bue) ([raw file](https://github.com/cockroachdb/cockroach/blob/500092ce88ca4128995738149ee6fade8684eb1a/pkg/cmd/roachtest/cluster.go#L2355)):*
> ```Go
> 
> func (c *clusterImpl) IsLocal() bool {
> 	// FIXME: I think radu made local more flexible and local is a prefix?
> ```

indeed
___
*[pkg/cmd/roachtest/tests/multitenant_utils.go, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79960#-N-hhEU01eugSwX4XLuF:-N-hhEU01eugSwX4XLuG:bqnwvwh) ([raw file](https://github.com/cockroachdb/cockroach/blob/500092ce88ca4128995738149ee6fade8684eb1a/pkg/cmd/roachtest/tests/multitenant_utils.go#L82)):*
> ```Go
> 		names = append(names, ip)
> 	}
> 	require.NoError(t, err)
> ```

shouldn't this error check be above the loop?
___
*[pkg/cmd/roachtest/tests/multitenant_utils.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79960#-N-hhKvh3RRzEnTYMkJX:-N-hhKvh3RRzEnTYMkJY:b-psdlqv) ([raw file](https://github.com/cockroachdb/cockroach/blob/500092ce88ca4128995738149ee6fade8684eb1a/pkg/cmd/roachtest/tests/multitenant_utils.go#L90)):*
> ```Go
> 
> 	names = append(names, "localhost")
> 	names = append(names, "127.0.0.1")
> ```

nit: consider pulling this out into a helper



_Code quote:_
```Go
	var names []string
	eips, err := c.ExternalIP(ctx, t.L(), c.Node(tn.node))
	for _, ip := range eips {
		names = append(names, ip)
	}
	require.NoError(t, err)
	iips, err := c.InternalIP(ctx, t.L(), c.Node(tn.node))
	require.NoError(t, err)
	for _, ip := range iips {
		names = append(names, ip)
	}

	names = append(names, "localhost")
	names = append(names, "127.0.0.1")
```
___
*[pkg/cmd/roachtest/tests/multitenant_utils.go, line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79960#-N-hhTX58D6uK-6_1hW4:-N-hgy06CTE991RQEAqr:bxs5bac) ([raw file](https://github.com/cockroachdb/cockroach/blob/500092ce88ca4128995738149ee6fade8684eb1a/pkg/cmd/roachtest/tests/multitenant_utils.go#L92)):*
> ```Go
> 	names = append(names, "127.0.0.1")
> 
> 	cmd := fmt.Sprintf("%s cert create-tenant-client --certs-dir=certs --ca-key=certs/ca.key %d %s", binary, tn.tenantID, strings.Join(names, " "))
> ```

nit: wrap
___
*[pkg/cmd/roachtest/tests/multitenant_utils.go, line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79960#-N-hjdI80CfiwKQ9QlDr:-N-hjdI80CfiwKQ9QlDs:bhcn0pp) ([raw file](https://github.com/cockroachdb/cockroach/blob/500092ce88ca4128995738149ee6fade8684eb1a/pkg/cmd/roachtest/tests/multitenant_utils.go#L115)):*
> ```Go
> 	// to the KV layer, and it won't open the SQL port until
> 	// it has.
> 	if err := retry.ForDuration(45*time.Second, func() error {
> ```

testutils.SucceedsSoon works with `t` here I believe
___
*[pkg/cmd/roachtest/tests/smoketest_secure.go, line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79960#-N-hgUzNAASw_pzT9qD9:-N-hgUzNAASw_pzT9qDA:btcp740) ([raw file](https://github.com/cockroachdb/cockroach/blob/500092ce88ca4128995738149ee6fade8684eb1a/pkg/cmd/roachtest/tests/smoketest_secure.go#L55)):*
> ```Go
> }
> 
> func multitenantSmokeTest(ctx context.Context, t test.Test, c cluster.Cluster) {
> ```

nit: comment a high-level sketch of what this test does?
___
*[pkg/cmd/roachtest/tests/smoketest_secure.go, line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79960#-N-hjJmE3ZHP1HkUPuRo:-N-hjJmE3ZHP1HkUPuRp:b-ig8j9m) ([raw file](https://github.com/cockroachdb/cockroach/blob/500092ce88ca4128995738149ee6fade8684eb1a/pkg/cmd/roachtest/tests/smoketest_secure.go#L86)):*
> ```Go
> 	err = c.RunE(ctx, c.Node(1), cmd)
> 	require.NoError(t, err)
> 	time.Sleep(1 * time.Second)
> ```

would it be better to just run the kv workload for a second?
___
*[pkg/cmd/roachtest/tests/smoketest_secure.go, line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79960#-N-hiOE74EGuX30E9Nc6:-N-hiOE74EGuX30E9Nc7:bdv2ekb) ([raw file](https://github.com/cockroachdb/cockroach/blob/500092ce88ca4128995738149ee6fade8684eb1a/pkg/cmd/roachtest/tests/smoketest_secure.go#L108)):*
> ```Go
> 			}
> 		}
> 		return err
> ```

consider:
```go
sqlutils.MakeSQLRunner(db).CheckQueryResultsRetry(t, fmt.Sprintf(`
    SELECT count(*) > 0
      FROM crdb_internal.ranges
     WHERE start_pretty LIKE '/Tenant/%d/%%';
`, tenID), [][]string{{"true"}})
```



_Code quote:_
```Go
	// The appearance of the tenant in the range system table isn't immediate.
	if err := retry.ForDuration(time.Minute, func() error {
		select {
		case <-ctx.Done():
			t.Fatal(ctx.Err())
		case err := <-ten.errCh:
			t.Fatal(err)
		default:
		}

		rows, err := db.Query(fmt.Sprintf("SELECT start_pretty FROM crdb_internal.ranges WHERE start_pretty LIKE '/Tenant/%d/%%'", tenID))
		if err == nil {
			for rows.Next() {
				cnt++
			}
			if cnt == 0 {
				return fmt.Errorf("no results")
			}
		}
		return err
```

**Review by cucaroach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79960)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @cucaroach, and @erikgrinaker)

___
*[pkg/cmd/roachtest/tests/multitenant_utils.go, line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79960#-N-hjdI80CfiwKQ9QlDr:-N-iOvbF7L9G-MpCp0gB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/500092ce88ca4128995738149ee6fade8684eb1a/pkg/cmd/roachtest/tests/multitenant_utils.go#L115)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

testutils.SucceedsSoon works with `t` here I believe
</blockquote></details>

Done.
___
*[pkg/cmd/roachtest/tests/smoketest_secure.go, line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79960#-N-hjJmE3ZHP1HkUPuRo:-N-iP6B82Doie9-0CjXk:b3hw1jf) ([raw file](https://github.com/cockroachdb/cockroach/blob/500092ce88ca4128995738149ee6fade8684eb1a/pkg/cmd/roachtest/tests/smoketest_secure.go#L86)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

would it be better to just run the kv workload for a second?
</blockquote></details>

Yeah I think that's overkill for what this test is trying to do.   Oh you mean the sleep, I meant to remove that, sorry!
___
*[pkg/cmd/roachtest/tests/smoketest_secure.go, line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79960#-N-hiOE74EGuX30E9Nc6:-N-iPufP5q-9KVmX9ZMY:bk999eg) ([raw file](https://github.com/cockroachdb/cockroach/blob/500092ce88ca4128995738149ee6fade8684eb1a/pkg/cmd/roachtest/tests/smoketest_secure.go#L108)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

consider:
```go
sqlutils.MakeSQLRunner(db).CheckQueryResultsRetry(t, fmt.Sprintf(`
    SELECT count(*) > 0
      FROM crdb_internal.ranges
     WHERE start_pretty LIKE '/Tenant/%d/%%';
`, tenID), [][]string{{"true"}})
```
</blockquote></details>

Ohh, very nice!

**Review by ajwerner — APPROVED** [review]
:lgtm: mod bazel generation

> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79960#-:-N0BpUH85a-Uz7yHi8G7:bq8aern)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @cucaroach, and @erikgrinaker)

**Pull request merged**
