### PR TITLE
storage: removed redundant activeVersion argument

### PR DESCRIPTION
**Pull request by irfansharif**
Clean up all comments/plumbed instances of the activeVersion passed
through.

Release note: None

### CODE REVIEW

**Comment by irfansharif** [comment]
Flaked on https://github.com/cockroachdb/cockroach/issues/42978, rebased.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43011#-:-LvfYJ3BAuMEjrhtH1hd:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by irfansharif** [comment]
bors retry

**Pull request merged**
