### PR TITLE
sql: add SHOW USERS stmt

### PR DESCRIPTION
**Pull request by asubiotto**
@knz @mjibson

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10088)

### CODE REVIEW

**Comment by mjibson** [comment]
Review status: 0 of 12 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/sql/pgwire_test.go, line 424 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10088#-KUT0TFOGs-MVbOyZhck:-KUT0TFOGs-MVbOyZhcl:boi1pbb) ([raw file](https://github.com/cockroachdb/cockroach/blob/89b43a918ef71f6620a339db257ffa6ec3e5c6ab/pkg/sql/pgwire_test.go#L424)):*
> ```Go
> 			baseTest.Results("UTC"),
> 		},
> 		"SHOW USERS": {},
> ```

Should give this a baseTest and some results if we're going to test it.

---

*[pkg/sql/planner.go, line 219 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10088#-KUT0gOaGI2H9xREW-jK:-KUT0gObUdFcmJndJlz2:b9f6ucu) ([raw file](https://github.com/cockroachdb/cockroach/blob/89b43a918ef71f6620a339db257ffa6ec3e5c6ab/pkg/sql/planner.go#L219)):*
> ```Go
> }
> 
> // query initializes a planNode from a SQL statement string. Close() should
> ```

Why did this comment get changed? Was it inaccurate?

---

*[pkg/sql/show.go, line 665 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10088#-KUT9QC0T01aJlGi4IMs:-KUT9QC0T01aJlGi4IMt:b-h30jq6) ([raw file](https://github.com/cockroachdb/cockroach/blob/89b43a918ef71f6620a339db257ffa6ec3e5c6ab/pkg/sql/show.go#L665)):*
> ```Go
> 		columns: columns,
> 		constructor: func(p *planner) (planNode, error) {
> 			resultsNode, err := p.query("SELECT username FROM system.users")
> ```

Two other ways to do this would be to use a select node directly or have a common queryNode type that does exactly this kind of "return the results of a query as my planNode". Have either of those been considered? I'm fine not using them, just want to make sure we've thought about the best pattern to use for cases like this.

---

*[pkg/sql/testdata/user, line 7 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10088#-KUT98nUegMJ7v6bZLy5:-KUT98nVX3uVSElxTTYY:b-qtxot2) ([raw file](https://github.com/cockroachdb/cockroach/blob/89b43a918ef71f6620a339db257ffa6ec3e5c6ab/pkg/sql/testdata/user#L7)):*
> ```
> 
> statement ok
> INSERT INTO system.users VALUES ('a','a')
> ```

Does it make more sense to use `CREATE USER` instead of a direct insert?

---

*[pkg/sql/testdata/user, line 16 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10088#-KUT9AJOB15mYr4KsQl8:-KUT9AJOB15mYr4KsQl9:btpe3rl) ([raw file](https://github.com/cockroachdb/cockroach/blob/89b43a918ef71f6620a339db257ffa6ec3e5c6ab/pkg/sql/testdata/user#L16)):*
> ```
> 
> statement ok
> INSERT INTO system.users VALUES ('b','a')
> ```

space after `,`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10088)*

**Comment by asubiotto** [comment]
Review status: 0 of 12 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/sql/pgwire_test.go, line 424 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10088#-KUT0TFOGs-MVbOyZhck:-KUTA4WbyGhraYYQAoSp:b7a499q) ([raw file](https://github.com/cockroachdb/cockroach/blob/89b43a918ef71f6620a339db257ffa6ec3e5c6ab/pkg/sql/pgwire_test.go#L424)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> Should give this a baseTest and some results if we're going to test it.
</details>
Wasn't too sure I should add this in. The expected behavior in this case is that no rows are returned.

---

*[pkg/sql/planner.go, line 219 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10088#-KUT0gOaGI2H9xREW-jK:-KUTALyKXooSBa8hLlSv:bm7f8ro) ([raw file](https://github.com/cockroachdb/cockroach/blob/89b43a918ef71f6620a339db257ffa6ec3e5c6ab/pkg/sql/planner.go#L219)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> Why did this comment get changed? Was it inaccurate?
</details>
Because I use it directly in ShowUsers in show.go and I didn't see why I shouldn't use it directly to get multiple rows. I might have missed something though.

---

*[pkg/sql/show.go, line 665 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10088#-KUT9QC0T01aJlGi4IMs:-KUTDGjXJPSZX6Y6_6xw:bkui2bb) ([raw file](https://github.com/cockroachdb/cockroach/blob/89b43a918ef71f6620a339db257ffa6ec3e5c6ab/pkg/sql/show.go#L665)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> Two other ways to do this would be to use a select node directly or have a common queryNode type that does exactly this kind of "return the results of a query as my planNode". Have either of those been considered? I'm fine not using them, just want to make sure we've thought about the best pattern to use for cases like this.
</details>
They have not. Only using an executor and the current implementation have been considered. I am very open to discussing the best solution. As I understand it, using a select node directly would kind of look like what's going on in ```execStmt``` in ```pkg/sql/executor.go```, is that right? If so I would be inclined to follow that pattern since what I am doing now doesn't seem to have a precedent (according to the comment on ```parser.query(...)```). Generalizing this also seems to be a good idea. Would this then be specific to Rows queries?

---

*[pkg/sql/testdata/user, line 7 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10088#-KUT98nUegMJ7v6bZLy5:-KUTCk7jWASocJVqbG4D:b-g8n8zc) ([raw file](https://github.com/cockroachdb/cockroach/blob/89b43a918ef71f6620a339db257ffa6ec3e5c6ab/pkg/sql/testdata/user#L7)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> Does it make more sense to use `CREATE USER` instead of a direct insert?
</details>
The CREATE USER pr has not been merged yet but that's what I'm going to change it to as soon as I can.

---

*[pkg/sql/testdata/user, line 16 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10088#-KUT9AJOB15mYr4KsQl8:-KUTIoXI9Y_zJkzS5Ft9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/89b43a918ef71f6620a339db257ffa6ec3e5c6ab/pkg/sql/testdata/user#L16)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> space after `,`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10088)*

**Comment by knz** [comment]
Review status: 0 of 12 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/sql/planner.go, line 219 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10088#-KUT0gOaGI2H9xREW-jK:-KUTMH-6r76g6NHOSfzd:blqabx7) ([raw file](https://github.com/cockroachdb/cockroach/blob/89b43a918ef71f6620a339db257ffa6ec3e5c6ab/pkg/sql/planner.go#L219)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary>
> Because I use it directly in ShowUsers in show.go and I didn't see why I shouldn't use it directly to get multiple rows. I might have missed something though.
</details>
@mjibson the initial author of query() thought that one would only use this via exec() or queryRow(). However now there is a legitimate additional user I proposed that we make it more clear how to use it.

---

*[pkg/sql/show.go, line 665 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10088#-KUT9QC0T01aJlGi4IMs:-KUTMR5zTRm2yByXJdIw:b-7elw6k) ([raw file](https://github.com/cockroachdb/cockroach/blob/89b43a918ef71f6620a339db257ffa6ec3e5c6ab/pkg/sql/show.go#L665)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary>
> They have not. Only using an executor and the current implementation have been considered. I am very open to discussing the best solution. As I understand it, using a select node directly would kind of look like what's going on in ```execStmt``` in ```pkg/sql/executor.go```, is that right? If so I would be inclined to follow that pattern since what I am doing now doesn't seem to have a precedent (according to the comment on ```parser.query(...)```). Generalizing this also seems to be a good idea. Would this then be specific to Rows queries?
</details>
You're making this sound too complicated.
```go
func (p *planner) ShowUsers(...) (planNode, error) {
   stmt, err := parser.ParseOneTraditional("SELECT ... ")
   if err != nil { return nil, err }
   return p.makePlan(stmt, true)
}
```

bam, done. No need for more.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10088)*

**Comment by mjibson** [comment]
Review status: 0 of 12 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/sql/pgwire_test.go, line 424 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10088#-KUT0TFOGs-MVbOyZhck:-KUTVxxNvTAV-czALMIR:bmzqmzv) ([raw file](https://github.com/cockroachdb/cockroach/blob/89b43a918ef71f6620a339db257ffa6ec3e5c6ab/pkg/sql/pgwire_test.go#L424)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary>
> Wasn't too sure I should add this in. The expected behavior in this case is that no rows are returned.
</details>
Then you can just put in an empty baseTest, since it defaults to 0 expected rows.

---

*[pkg/sql/show.go, line 665 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10088#-KUT9QC0T01aJlGi4IMs:-KUTW2kN_HQMuB50FG6t:b-uq3qqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/89b43a918ef71f6620a339db257ffa6ec3e5c6ab/pkg/sql/show.go#L665)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> You're making this sound too complicated.
> ```go
> func (p *planner) ShowUsers(...) (planNode, error) {
>    stmt, err := parser.ParseOneTraditional("SELECT ... ")
>    if err != nil { return nil, err }
>    return p.makePlan(stmt, true)
> }
> ```
> 
> bam, done. No need for more.
</details>
Oh nice. Yeah do this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10088)*

**Comment by asubiotto** [comment]
Review status: 0 of 12 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/sql/pgwire_test.go, line 424 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10088#-KUT0TFOGs-MVbOyZhck:-KUXUyvyKNFRT5h8YoEo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/89b43a918ef71f6620a339db257ffa6ec3e5c6ab/pkg/sql/pgwire_test.go#L424)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> Then you can just put in an empty baseTest, since it defaults to 0 expected rows.
</details>
Done.

---

*[pkg/sql/show.go, line 665 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10088#-KUT9QC0T01aJlGi4IMs:-KUXUYqxvttHDl4Siqx1:b-k6m72c) ([raw file](https://github.com/cockroachdb/cockroach/blob/89b43a918ef71f6620a339db257ffa6ec3e5c6ab/pkg/sql/show.go#L665)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> Oh nice. Yeah do this.
</details>
Done. Used newPlan instead of makePlan since it doesn't call expandPlan on the new planNode.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10088)*

**Comment by knz** [comment]
Review status: 0 of 12 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/sql/show.go, line 665 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10088#-KUT9QC0T01aJlGi4IMs:-KUXVJrCeJKaPRIccD1m:b-v5916b) ([raw file](https://github.com/cockroachdb/cockroach/blob/89b43a918ef71f6620a339db257ffa6ec3e5c6ab/pkg/sql/show.go#L665)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary>
> Done. Used newPlan instead of makePlan since it doesn't call expandPlan on the new planNode.
</details>
Yes, sorry I had meant `newPlan`. Good move.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10088)*

**Comment by knz** [comment]
Review status: 0 of 12 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/sql/show.go, line 665 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10088#-KUT9QC0T01aJlGi4IMs:-KUXVQo6yYE1omSpktb4:bg7vhsg) ([raw file](https://github.com/cockroachdb/cockroach/blob/89b43a918ef71f6620a339db257ffa6ec3e5c6ab/pkg/sql/show.go#L665)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Yes, sorry I had meant `newPlan`. Good move.
</details>
Also I think you can pre-parse the statement in an init() function and reuse it as constant instead of reparsing every time. I am 99% confident it's not modified when executed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10088)*

**Comment by tamird** [comment]
Reviewed 8 of 12 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/sql/planner.go, line 219 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10088#-KUXa8coxWVcxiz3bPfD:-KUXa8cpdGaS-_84xotj:bjdlu8k) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd38793c8e025d05d25f546a53ac0bbc94a31088/pkg/sql/planner.go#L219)):*
> ```Go
> }
> 
> // query initializes a planNode from a SQL statement string. Close() should
> ```

s/should/must/?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10088)*

**Comment by asubiotto** [comment]
Review status: 10 of 12 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/sql/planner.go, line 219 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10088#-KUXa8coxWVcxiz3bPfD:-KUXenfajtEM-32BV9Jv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd38793c8e025d05d25f546a53ac0bbc94a31088/pkg/sql/planner.go#L219)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> s/should/must/?
</details>
Done.

---

*[pkg/sql/show.go, line 665 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10088#-KUT9QC0T01aJlGi4IMs:-KUXeStR-uiIuSRBCYOu:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/89b43a918ef71f6620a339db257ffa6ec3e5c6ab/pkg/sql/show.go#L665)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Also I think you can pre-parse the statement in an init() function and reuse it as constant instead of reparsing every time. I am 99% confident it's not modified when executed.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10088)*

**Comment by mjibson** [comment]
:lgtm:, but read my comment

---

Review status: 10 of 12 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/show.go, line 665 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10088#-KUT9QC0T01aJlGi4IMs:-KUgu57Y5bHBY53RPOWX:bgx9ule) ([raw file](https://github.com/cockroachdb/cockroach/blob/89b43a918ef71f6620a339db257ffa6ec3e5c6ab/pkg/sql/show.go#L665)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary>
> Done.
</details>
I am of the opinion that we should not be doing that work in the init block. It increases the startup time of anything using this package and permanently holds some memory. If this were a frequent operation I think it might be worth it, but for a rarely used statement that is trivial to parse, I'd prefer to keep the runtime overhead lower. However I don't feel strong enough about this to block merging this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10088#-:-KUguxd4vRmxMFrHwLiF:b-6c493j)*

**Comment by knz** [comment]
:lgtm: but I concur with matt, the idea I was selling you should probably only apply for statements used more often than "show users". Your call.

---

Reviewed 1 of 12 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/show.go, line 665 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10088#-KUT9QC0T01aJlGi4IMs:-KUhwh6N_anmID_ObMUv:b-9gk9a) ([raw file](https://github.com/cockroachdb/cockroach/blob/89b43a918ef71f6620a339db257ffa6ec3e5c6ab/pkg/sql/show.go#L665)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> I am of the opinion that we should not be doing that work in the init block. It increases the startup time of anything using this package and permanently holds some memory. If this were a frequent operation I think it might be worth it, but for a rarely used statement that is trivial to parse, I'd prefer to keep the runtime overhead lower. However I don't feel strong enough about this to block merging this PR.
</details>
Ok I think there is wisdom in matt's words, namely the part about that statement not being used often.
The general idea of keeping a pre-parsed statement in a global is useful indeed only for often-used statements. For example I believe firmly we should do this more for the lease manager and the logging manager (that both reuse the same statement over and over) but this would be a separate issue/PR.

Now you've got the point perhaps your previous version of the code was better after all :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10088#-:-KUhxGpngpTcZu0Js7Pw:bfy9k3u)*

**Comment by asubiotto** [comment]
Thanks for the reviews, I'm going to remove the change to parse the statement in init(). I'm just waiting for #9794 to go in to not add more changes on that PR (wrt pkg/sql/testdata/user)

**Comment by asubiotto** [comment]
Modified tests to use CREATE USER and moved the statement parsing back. PTAL.

**Comment by knz** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10088#-:-KVW4FMLWGftjkY1tL3z:bnfp4nl)*

**Comment by tamird** [comment]
Reviewed 10 of 10 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10088)*

**Comment by knz** [comment]
:shipit:

**Pull request merged**
