### PR TITLE
sql: add is_temporary and is_virtual columns to crdb_internal.create_statements

### PR DESCRIPTION
**Pull request by RichardJCai**
These columns are useful for filtering for generating output for
SHOW CREATE ALL TABLES.

Release justification: None, change to internal table.
Release note: None

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
lgtm!

`crdb_internal_tenant` logic test needs to be updated too

**Comment by otan** [comment]
should we do something like pg_tables where 's' = sequence, 'v' = view, 'm' = materialised view, 't' = table instead?

**Comment by RichardJCai** [comment]
> should we do something like pg_tables where 's' = sequence, 'v' = view, 'm' = materialised view, 't' = table instead?

Yeah I quite like this, reduce # of columns and seems more scalable.

**Comment by RichardJCai** [comment]
> should we do something like pg_tables where 's' = sequence, 'v' = view, 'm' = materialised view, 't' = table instead?

Update, nvm not sure this is actually actually better, we can join with the `pg_catalog.pg_class` table if we want this. We still need a separate `is_virtual` column and the `is_temporary` is equivalent to the `relpersistence` we can add another table kind column if necessary in the future.

Going to move forward with this.

**Comment by otan** [comment]
ah woops misread this. Sgtm.

**Comment by RichardJCai** [comment]
Thanks for the review!
bors r=rafiss

**Pull request merged**
