### PR TITLE
sql: check for substr overflow

### LINKED ISSUE #8041: sql: panic: runtime error: slice bounds out of range
SQL:

```
SELECT SUBSTR('string', 4827075662841736053, 5123273972570225659);
```

Found with the random syntax generator.

### PR DESCRIPTION
**Pull request by madelynnblue**
Fixes #8041

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8078)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/parser/builtins.go, line 1033 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8078#-KNksNH1AzDLZ-EbXcS5:-KNksNH1AzDLZ-EbXcS6:1219234463) ([raw file](https://github.com/cockroachdb/cockroach/blob/559589de0cf96f900233e0aecda520b2527a63c2/sql/parser/builtins.go#L1033)):*
> ```Go
> 			end := start + length
> 			// Check for integer overflow.
> 			if start > math.MaxInt64-length {
> ```

isn't this more naturally `end < start`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8078)*

**Comment by RaduBerinde** [comment]
LGTM

**Comment by mjibson** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/parser/builtins.go, line 1033 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8078#-KNksNH1AzDLZ-EbXcS5:-KNrt0Yt2pUT1nH0nL5i:33484446) ([raw file](https://github.com/cockroachdb/cockroach/blob/559589de0cf96f900233e0aecda520b2527a63c2/sql/parser/builtins.go#L1033)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> isn't this more naturally `end < start`?
</details>
I tested both and couldn't find any differences. Will switch to end < start.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8078)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8078#-:-KNrvggI_8G0IbeO2Tjy:1417088721)*

**Pull request merged**
