### PR TITLE
go.mod: bump Pebble to 90c810757fe6

### PR DESCRIPTION
**Pull request by nvb**
```
90c81075 cmd/pebble: add bench replay command
1e862340 db: scan a readState during format major version upgrades
dac60ce1 Revert "sstable: skip two known test flakes on windows"
78933282 ci: renable linux race
5bad2c1a sstable: avoid allocating up to maximum block size in valueBlockWriter
a4481627 deflake TestCompactionTombstones
06fbe6ae db: add DB.ApplyNoSyncWait for asynchronous apply
a60e75cf db: misc LazyValue tweaks, for testing, and simpler Clone invariant
ba575119 doc: fix
326549f0 db: metrics and stats for value blocks and lazy values
cc913bad db: don't validate version edits during a panic
```

Release note: None
Epic: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]

**Review by nicktrav — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95172#-:-NLc8CnD93XB5_7fHkzT:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Comment by healthy-pod** [comment]
bors r-
[check generated code is failing / failed on the original PR build]

**Pull request merged**
