### PR TITLE
builtins: implement pg_options_to_table

### PR DESCRIPTION
**Pull request by otan**
Release note (sql change): implemented the pg_options_to_table builtin.

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77883)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rafiss)

___
*[pkg/sql/sem/builtins/generator_builtins.go, line 635 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77883#-MyIO2h66pWCTwHWxR9l:-MyIO2h66pWCTwHWxR9m:b-vrwi7l) ([raw file](https://github.com/cockroachdb/cockroach/blob/9eb7b936b2b12530ae7aee101012d4d8abd92a83/pkg/sql/sem/builtins/generator_builtins.go#L635)):*
> ```Go
> 	}
> 	s := string(tree.MustBeDString(elem))
> 	split := strings.SplitN(s, "=", 2)
> ```

oo nice. how do you feel about making a `sql/pgoptionsarray` package (or a better name) that has this parsing logic? so it can be shared with https://github.com/cockroachdb/cockroach/blob/905eae9e3c5e25c1e45ad2a0841464e5540aaa0f/pkg/sql/pgwire/auth.go#L184-L192

(optional comment)
___
*[pkg/sql/logictest/testdata/logic_test/pg_builtins, line 590 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77883#-MyIOeDS1mUXSlRB8cb4:-MyIOeDS1mUXSlRB8cb5:b-6efo1o) ([raw file](https://github.com/cockroachdb/cockroach/blob/9eb7b936b2b12530ae7aee101012d4d8abd92a83/pkg/sql/logictest/testdata/logic_test/pg_builtins#L590)):*
> ```
> ----
> option_name  option_value
> ```

could you add a test for
```
rafiss@127:postgres> SELECT * FROM pg_options_to_table(null)
+-------------+--------------+
| option_name | option_value |
|-------------+--------------|
+-------------+--------------+
```
___
*[pkg/sql/logictest/testdata/logic_test/pg_builtins, line 592 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77883#-MyINjt0Cz-EymSWyXLS:-MyINjt0Cz-EymSWyXLT:b8ozvwq) ([raw file](https://github.com/cockroachdb/cockroach/blob/9eb7b936b2b12530ae7aee101012d4d8abd92a83/pkg/sql/logictest/testdata/logic_test/pg_builtins#L592)):*
> ```
> 
> query TT colnames
> SELECT * FROM pg_options_to_table(array['a', 'b=c', '=d', 'e=f=g']::text[]);
> ```

could you add a test using the array literal syntax?
```
SELECT * FROM pg_options_to_table('{a, b=c, =d, e=f=g}')
```

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77883)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/sem/builtins/generator_builtins.go, line 635 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77883#-MyIO2h66pWCTwHWxR9l:-MyJVizfBGrq5IwumKGe:b-t8xsz1) ([raw file](https://github.com/cockroachdb/cockroach/blob/9eb7b936b2b12530ae7aee101012d4d8abd92a83/pkg/sql/sem/builtins/generator_builtins.go#L635)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

oo nice. how do you feel about making a `sql/pgoptionsarray` package (or a better name) that has this parsing logic? so it can be shared with https://github.com/cockroachdb/cockroach/blob/905eae9e3c5e25c1e45ad2a0841464e5540aaa0f/pkg/sql/pgwire/auth.go#L184-L192

(optional comment)
</blockquote></details>

there's really only one shared line here, so i'm going to say nah
___
*[pkg/sql/logictest/testdata/logic_test/pg_builtins, line 590 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77883#-MyIOeDS1mUXSlRB8cb4:-MyJVmlc7hWxmiT9IECL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9eb7b936b2b12530ae7aee101012d4d8abd92a83/pkg/sql/logictest/testdata/logic_test/pg_builtins#L590)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

could you add a test for
```
rafiss@127:postgres> SELECT * FROM pg_options_to_table(null)
+-------------+--------------+
| option_name | option_value |
|-------------+--------------|
+-------------+--------------+
```
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/pg_builtins, line 592 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77883#-MyINjt0Cz-EymSWyXLS:-MyJVo684HXdEk6GOiSz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9eb7b936b2b12530ae7aee101012d4d8abd92a83/pkg/sql/logictest/testdata/logic_test/pg_builtins#L592)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

could you add a test using the array literal syntax?
```
SELECT * FROM pg_options_to_table('{a, b=c, =d, e=f=g}')
```
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77883)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

**Comment by otan** [comment]
bors r=rafiss

**Pull request merged**
