### PR TITLE
sql: fix displaying second zone offsets

### LINKED ISSUE #54294: Incorrect time zone handling before 1883
**Describe the problem**

Time zone handling for dates before some time in 1883 or so ([perhaps November 18, 1883 when standard time began](https://en.wikipedia.org/wiki/Standard_time_in_the_United_States)) is incorrect (or at least differs from PostgreSQL).

**To Reproduce**
```sql
CREATE TABLE test (foo timestamptz);
INSERT INTO test VALUES ('1882-05-23T00:00:00-05:51'::timestamptz);
INSERT INTO test VALUES ('1883-05-23T00:00:00-05:51'::timestamptz);
INSERT INTO test VALUES ('1884-05-23T00:00:00-05:51'::timestamptz);
INSERT INTO test VALUES ('1885-05-23T00:00:00-05:51'::timestamptz);

> SELECT foo FROM test;
             foo
-----------------------------
  1882-05-23 05:51:00+00:00
  1883-05-23 05:51:00+00:00
  1884-05-23 05:51:00+00:00
  1885-05-23 05:51:00+00:00

> SET TIME ZONE 'America/Chicago';

> SELECT foo FROM test;
             foo
-----------------------------
  1882-05-23 00:00:24-05:50
  1883-05-23 00:00:24-05:50
  1884-05-22 23:51:00-06:00
  1885-05-22 23:51:00-06:00
```
**Expected behavior**

The first two results of the last query doesn't match PostgreSQL:

"1882-05-23 00:00:24-05:50:36"
"1883-05-23 00:00:24-05:50:36"
"1884-05-22 23:51:00-06"
"1885-05-22 23:51:00-06"

They include a seconds offset in the time zone so that the result is correct.

**Environment:**
 - CockroachDB version 20.1.5

**Additional context**

I discovered this issue in the Django test suite:
```
======================================================================
FAIL: test_unicode_date (gis_tests.geoapp.test_regress.GeoRegressionTests)
Testing dates are converted properly, even on SpatiaLite. See #16408.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tim/code/django/tests/gis_tests/geoapp/test_regress.py", line 56, in test_unicode_date
    self.assertEqual(founded, PennsylvaniaCity.objects.aggregate(Min('founded'))['founded__min'])
AssertionError: datetime.datetime(1857, 5, 23, 0, 0) != datetime.datetime(1857, 5, 23, 0, 0, 24)
```

### PR DESCRIPTION
**Pull request by otan**
For casting timestamptz->text, only display the second offset if there
is one for timestamptz, to maintain compatibility with older versions.

Otherwise, for other outputs (e.g. CLI, pgwire), always show the full
zone offset including the seconds. Note the timezone zone offset doesn't
actually fully appear in the CRDB CLI due to lib/pq, but will
successfully display on postgresql connecting to CockroachDB.

Resolves https://github.com/cockroachdb/cockroach/issues/54294.

Release note (bug fix): Fix a bug where the seconds offset zone offset of
a timestamptz was not displayed.

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55071)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @otan, and @rafiss)

___
*[pkg/sql/sem/tree/datum.go, line 2168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55071#-MJY2FAjE_qe81z6M2Ai:-MJY2FAjE_qe81z6M2Aj:b9vtu3i) ([raw file](https://github.com/cockroachdb/cockroach/blob/07219f63fa19e8c3811541d65166496f41d61753/pkg/sql/sem/tree/datum.go#L2168)):*
> ```Go
> 	// Note the second offset is missing here -- this is to maintain
> 	// backward compatibility with casting timestamptz to strings.
> 	timestampTZOutputFormat = "2006-01-02 15:04:05.999999-07:00"
> ```

this format would also be used if a timestamp appears in a partial index or check constraint right? idk if there's much we can do about that, but just checking.
___
*[pkg/sql/sem/tree/datum.go, line 2519 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55071#-MJY08mM9iKE4yQIBi4D:-MJY08mM9iKE4yQIBi4E:b-giln7g) ([raw file](https://github.com/cockroachdb/cockroach/blob/07219f63fa19e8c3811541d65166496f41d61753/pkg/sql/sem/tree/datum.go#L2519)):*
> ```Go
> 	// This is to maintain backward compatibility with older CRDB versions,
> 	// where we only output HH:MM.
> 	if secondOffset := offsetSecs % 60; secondOffset != 0 {
> ```

do you feel this would be easier if we included the second offset in `timestampTZOutputFormat` and made the logic here strip it off if it ends with `:00`? i guess it'd be nice since then we could get rid of `FullTimeFormat`. up to you. 
___
*[pkg/util/timeutil/timeutil.go, line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55071#-MJY1jP11r6Irnchuvhd:-MJY1jP11r6Irnchuvhe:b-yx2zp5) ([raw file](https://github.com/cockroachdb/cockroach/blob/07219f63fa19e8c3811541d65166496f41d61753/pkg/util/timeutil/timeutil.go#L11)):*
> ```Go
> // licenses/APL.txt.
> 
> package timeutil
> ```

curious: why make a separate package for this?

**Review by rafiss — APPROVED** [review]
lgtm -- my comments are just suggestions/questions

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55071)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @otan, and @rafiss)

___
*[pkg/sql/sem/tree/datum.go, line 2168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55071#-MJY2FAjE_qe81z6M2Ai:-MJY2f8h8QlWYFk29F1B:b-l9d33u) ([raw file](https://github.com/cockroachdb/cockroach/blob/07219f63fa19e8c3811541d65166496f41d61753/pkg/sql/sem/tree/datum.go#L2168)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this format would also be used if a timestamp appears in a partial index or check constraint right? idk if there's much we can do about that, but just checking.
</blockquote></details>

i really don't enjoy stripping logic (and sometimes Golang ends +00:00 with Z, which makes it harder), so rather do it this way around.
___
*[pkg/util/timeutil/timeutil.go, line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55071#-MJY1jP11r6Irnchuvhd:-MJY2_UkAyoXzqCia4kd:bnm5fqd) ([raw file](https://github.com/cockroachdb/cockroach/blob/07219f63fa19e8c3811541d65166496f41d61753/pkg/util/timeutil/timeutil.go#L11)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

curious: why make a separate package for this?
</blockquote></details>

package already existed, just didnt' have an appropriate place to put this!

**Comment by otan** [comment]
tftr!

bors r=rafiss

**Pull request merged**
