### PR TITLE
kv: consider intent in uncertainty interval to be uncertain, not a write-read conflict

### PR DESCRIPTION
**Pull request by nvb**
This PR is a partial revert of #40600 and #46830. It solves the same problem that those PRs were solving, but in a different way.

Those two PRs were handling the case where a reading transaction observes an intent in its uncertainty interval. Before those fixes, we were not considering intents in a scan's uncertainty interval to be uncertain. This had the potential to cause stale reads because an unresolved intent doesn't indicate that its transaction hasn’t been committed and is not a causal ancestor of the scan.

The approach the first PR took was to throw a WriteIntentError on intents in a scan's uncertainty interval. Effectively, it made scans consider intents in their uncertainty interval to be write-read conflicts. This had the benefit that the scan would push the intent and eventually resolve the conflict, either by aborting the intent, pushing it out of the read's uncertainty interval, or waiting for it to commit. In this last case (which is by the far the most common), the scan would then throw an uncertainty error, because it now had a committed value in its uncertainty interval.

The second PR introduced some awkward code to deal with the fallout from this decision. Once we started trying to keep the lock table in sync with the MVCC state, we needed to use latches to ensure proper synchronization between any operations that could conflict because such conflicts would influence the state of the lock table. This meant that we needed to start holding latches across a read's uncertainty interval, because intent writes in this interval were considered write-read conflicts. This led to some moderately gross code and always felt a little wrong.

Now that we are complicating the logic around uncertainty intervals even further, this becomes even more of a burden. This motivates a reworking of these interactions. This commit replaces the logic that considers intents in a transaction's uncertainty interval to be write-read conflicts for logic that considers such intents to be... uncertain. Doing so means that a transaction will immediately refresh/restart above the uncertain timestamp and will only then begin conflicting with the intent.

This has a number of nice benefits:
1. it keeps all considerations of read uncertainty intervals down in MVCC iteration logic. The lock table no longer needs to be aware of it. This is a big win now and an even bigger win once we introduce synthetic timestamps.
2. readers that are almost certainly bound to hit an uncertainty error and need to restart will now do so sooner. In rare cases, this may result in wasted work. In the vast majority of cases, this will allow the reader to be more responsive to the commit of its conflict.
3. uncertainty errors will only be thrown for locks in the uncertainty interval of a read that are protecting a provisional write (intents). Before, any form of a lock in a read's uncertainty interval would be considered a write-read conflict, which was pessimistic and not needed for correctness.

   In a future with a fully segregated lock table, the change in semantic meaning here becomes even more clear. Instead of detecting the lock associated with an intent in a read's uncertainty interval and declaring a write-read conflict, the read will instead pass through the lock table untouched and will detect the provisional value associated with an intent and declaring uncertainty. This seems closer to what were actually trying to say about these interactions.

Before making this change, I intend to validate the hypothesis that it will not affect performance (or may even slightly improve performance) by running it on the YCSB benchmark suite.

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
Nice!
And when I read this explanation, it sounds so obvious, that I am scratching my head on why we did it the other complicated way to begin with.

> Reviewed 8 of 8 files at r6, 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57136#-:-MNPYH6G7zoZEGzoVDDS:bwyn9yq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @sumeerbhola)

___
*[pkg/storage/pebble_mvcc_scanner.go, line 388 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/57136#-MNPXMhSCTeZjjDoHGgG:-MNPXMhSCTeZjjDoHGgH:b7o5tjg) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d07110aa5e862f3726d6f6d7f1ca2c3f1dc34a4/pkg/storage/pebble_mvcc_scanner.go#L388)):*
> ```Go
> 	ownIntent := p.txn != nil && p.meta.Txn.ID.Equal(p.txn.ID)
> 	otherIntentVisible := metaTS.LessEq(p.ts) ||
> 		(p.checkUncertainty && p.isUncertainValue(metaTS)) ||
> ```

why this change in meaning of `otherIntentVisible` and the associated change below?

**Comment by sumeerbhola** [comment]
This code is delaying discovery of the uncertainty until the MVCC scan: wouldn't it be beneficial in the future, with the separated lock table, to discover these early? We are already going to be iterating over the lock table key space to find locks with timestamp < read timestamp -- we may as well also inform the reader about the uncertainty so it can push itself right away.

**Review by nvb — COMMENTED** [review]
Thanks for the review! I've split this off from #57077 so we can push this ahead.

I did need to make one small change here. I had hoped that this change would allow us to no longer declare read latches all the way up to a read's uncertainty interval, but this doesn't actually appear to be true. Reads still need to continue declaring latches up through their uncertainty interval so that they are properly synchronized with earlier writes that may have a happened-before relationship with the read. These writes could not have completed and returned to the client until they were durable in the Range's Raft log. However, they may not have been applied to the replica's state machine by the time the write was acknowledged, because Raft entry application occur be asynchronously with respect to the writer (see `AckCommittedEntriesBeforeApplication`). Latching is the only mechanism that ensures that any observers of the write wait for the write apply before reading.

> This code is delaying discovery of the uncertainty until the MVCC scan: wouldn't it be beneficial in the future, with the separated lock table, to discover these early? We are already going to be iterating over the lock table key space to find locks with timestamp < read timestamp -- we may as well also inform the reader about the uncertainty so it can push itself right away.

Yeah, I think that's a good point. I had hoped that we wouldn't need to introduce any of the complications of #57077 into the lockTable, but this might be reason enough to do so.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57136#-:-MQK0Z5c-ejbV9Bh1iuy:b-36jg0o)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/storage/pebble_mvcc_scanner.go, line 388 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/57136#-MNPXMhSCTeZjjDoHGgG:-MQK1Df_1VsjclmMxKY9:bti7c1h) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d07110aa5e862f3726d6f6d7f1ca2c3f1dc34a4/pkg/storage/pebble_mvcc_scanner.go#L388)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why this change in meaning of `otherIntentVisible` and the associated change below?
</blockquote></details>

We're no longer considering an intent in a read's uncertainty interval to be "visible", for some meaning of "visible". Instead, we consider ourselves reading below the intent even if it is in our uncertainty interval, but then later check that it's not. I renamed this variable to `intentVisible` because "other" wasn't quite correct. I'm thinking of renaming it again to `conflictingIntent` to avoid the ambiguity of the term "visible". What do you think?

**Comment by nvanbenschoten** [comment]
I still owe this change some YCSB numbers. I'll try to collect those tonight.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 25 of 31 files at r1, 26 of 26 files at r8, 3 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57136#-:-MQOUhbV9jLkJvHNzEz7:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvserver/batcheval/declare.go, line 63 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/57136#-MQO50nqEpMtccEzSLDD:-MQO50nqEpMtccEzSLDE:b9cqz45) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c037e659d75679066589b39a8bac4299aac6f86/pkg/kv/kvserver/batcheval/declare.go#L63)):*
> ```Go
> 			// However, they may not have been applied to the replica's state
> 			// machine by the time the write was acknowledged, because Raft
> 			// entry application occur be asynchronously with respect to the
> ```

... occurs asynchronously ...
___
*[pkg/storage/pebble_mvcc_scanner.go, line 388 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/57136#-MNPXMhSCTeZjjDoHGgG:-MQOCB_GCyOc9q3Fpm2X:bfnsg8h) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d07110aa5e862f3726d6f6d7f1ca2c3f1dc34a4/pkg/storage/pebble_mvcc_scanner.go#L388)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We're no longer considering an intent in a read's uncertainty interval to be "visible", for some meaning of "visible". Instead, we consider ourselves reading below the intent even if it is in our uncertainty interval, but then later check that it's not. I renamed this variable to `intentVisible` because "other" wasn't quite correct. I'm thinking of renaming it again to `conflictingIntent` to avoid the ambiguity of the term "visible". What do you think?
</blockquote></details>

conflictingIntent sounds fine.
___
*[pkg/storage/pebble_mvcc_scanner.go, line 390 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/57136#-MQOBrf29AVu0n0O9UX7:-MQOBrf318npq-uHYPVQ:b-c4hkxx) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c037e659d75679066589b39a8bac4299aac6f86/pkg/storage/pebble_mvcc_scanner.go#L390)):*
> ```Go
> 				return p.uncertaintyError(metaTS)
> 			}
> ```

nit: can you remove the empty line

This could use a comment, such as
// The intent is not within the uncertainty, but there could be an uncertain committed value, so seek and check uncertainty using MaxTimestamp.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57136)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @sumeerbhola)

___
*[pkg/kv/kvserver/batcheval/declare.go, line 63 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/57136#-MQO50nqEpMtccEzSLDD:-MR2u8a-8yXvX6jmVZ1M:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c037e659d75679066589b39a8bac4299aac6f86/pkg/kv/kvserver/batcheval/declare.go#L63)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

... occurs asynchronously ...
</blockquote></details>

Done.
___
*[pkg/storage/pebble_mvcc_scanner.go, line 388 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/57136#-MNPXMhSCTeZjjDoHGgG:-MR2uEj3CRfbVNIS3KGz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4d07110aa5e862f3726d6f6d7f1ca2c3f1dc34a4/pkg/storage/pebble_mvcc_scanner.go#L388)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

conflictingIntent sounds fine.
</blockquote></details>

Done.
___
*[pkg/storage/pebble_mvcc_scanner.go, line 390 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/57136#-MQOBrf29AVu0n0O9UX7:-MR2uMkN3TMyipg07Qs_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c037e659d75679066589b39a8bac4299aac6f86/pkg/storage/pebble_mvcc_scanner.go#L390)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

nit: can you remove the empty line

This could use a comment, such as
// The intent is not within the uncertainty, but there could be an uncertain committed value, so seek and check uncertainty using MaxTimestamp.
</blockquote></details>

Done.

**Comment by nvanbenschoten** [comment]
bors r=sumeerbhola

**Comment by sumeerbhola** [comment]
> I still owe this change some YCSB numbers. I'll try to collect those tonight.

did you happen to collect the YCSB numbers?

**Comment by nvanbenschoten** [comment]
I did, but I see that I forgot to post them. There wasn't much movement. The largest statistically significant change was a 4% regression in throughput on `ycsb/B/nodes=3`, but then there was also a statistically significant 1.4% speedup in `ycsb/B/nodes=3/cpu=32`, the same workload but on larger machines. That lines up with my prior experience with YCSB - that there is so much contention on certain keys that small changes in the interactions between txns can cause performance to vary, often unpredictably. Since there was no clear positive or negative trend, this didn't seem to warrant further investigation.
```
name                   old ops/s    new ops/s    delta
ycsb/A/nodes=3          15.4k ± 2%   14.9k ±10%     ~     (p=0.165 n=10+10)
ycsb/B/nodes=3          32.3k ± 1%   31.0k ±10%   -4.02%  (p=0.017 n=9+10)
ycsb/C/nodes=3          45.9k ± 1%   44.6k ± 4%     ~     (p=0.075 n=10+10)
ycsb/D/nodes=3          34.8k ± 1%   33.8k ± 7%     ~     (p=0.165 n=10+10)
ycsb/E/nodes=3            824 ± 4%     805 ± 4%   -2.36%  (p=0.035 n=10+10)
ycsb/F/nodes=3          7.07k ± 3%   7.27k ± 4%   +2.88%  (p=0.010 n=9+10)
ycsb/A/nodes=3/cpu=32   27.1k ± 3%   26.6k ± 5%     ~     (p=0.123 n=10+10)
ycsb/B/nodes=3/cpu=32   90.1k ± 3%   91.4k ± 5%   +1.39%  (p=0.040 n=9+9)
ycsb/C/nodes=3/cpu=32    122k ± 2%    122k ± 2%     ~     (p=0.280 n=10+10)
ycsb/D/nodes=3/cpu=32   91.0k ± 4%   91.2k ± 5%     ~     (p=0.684 n=10+10)
ycsb/E/nodes=3/cpu=32   1.13k ± 6%   1.13k ± 5%     ~     (p=0.971 n=10+10)
ycsb/F/nodes=3/cpu=32   14.3k ± 7%   14.9k ± 6%     ~     (p=0.190 n=10+10)

name                   old avg(ms)  new avg(ms)  delta
ycsb/A/nodes=3           6.26 ± 3%    6.38 ± 4%     ~     (p=0.307 n=10+9)
ycsb/B/nodes=3           4.48 ± 3%    4.81 ± 9%   +7.37%  (p=0.026 n=10+10)
ycsb/C/nodes=3           3.13 ± 2%    3.23 ± 4%   +3.19%  (p=0.021 n=10+10)
ycsb/D/nodes=3           2.77 ± 3%    2.83 ± 6%     ~     (p=0.196 n=10+10)
ycsb/E/nodes=3            116 ± 4%     119 ± 4%   +2.42%  (p=0.035 n=10+10)
ycsb/F/nodes=3           13.6 ± 4%    13.2 ± 4%   -2.95%  (p=0.010 n=9+10)
ycsb/A/nodes=3/cpu=32    5.31 ± 4%    5.43 ± 4%     ~     (p=0.089 n=10+10)
ycsb/B/nodes=3/cpu=32    2.10 ± 0%    2.10 ± 0%     ~     (all equal)
ycsb/C/nodes=3/cpu=32    1.60 ± 0%    1.60 ± 0%     ~     (all equal)
ycsb/D/nodes=3/cpu=32    1.56 ± 4%    1.57 ± 8%     ~     (p=1.000 n=10+10)
ycsb/E/nodes=3/cpu=32     127 ± 6%     127 ± 5%     ~     (p=0.955 n=10+10)
ycsb/F/nodes=3/cpu=32    10.1 ± 7%     9.7 ± 6%     ~     (p=0.155 n=10+10)

name                   old p99(ms)  new p99(ms)  delta
ycsb/A/nodes=3           43.5 ±23%    41.1 ±13%     ~     (p=0.112 n=9+8)
ycsb/B/nodes=3           29.0 ± 9%    31.8 ±17%   +9.66%  (p=0.015 n=10+10)
ycsb/C/nodes=3           12.9 ± 3%    13.4 ± 6%     ~     (p=0.061 n=10+10)
ycsb/D/nodes=3           14.4 ± 2%    14.6 ± 7%     ~     (p=0.344 n=10+10)
ycsb/E/nodes=3            580 ± 8%     587 ± 3%     ~     (p=0.714 n=10+10)
ycsb/F/nodes=3            110 ±29%     129 ±37%     ~     (p=0.202 n=9+10)
ycsb/A/nodes=3/cpu=32    71.9 ±11%    72.5 ±10%     ~     (p=0.792 n=10+9)
ycsb/B/nodes=3/cpu=32    15.9 ±10%    15.6 ± 6%     ~     (p=0.497 n=9+9)
ycsb/C/nodes=3/cpu=32    7.57 ± 4%    7.51 ± 3%     ~     (p=0.720 n=10+10)
ycsb/D/nodes=3/cpu=32    8.80 ± 7%    8.62 ± 9%     ~     (p=0.439 n=10+10)
ycsb/E/nodes=3/cpu=32     671 ± 0%     671 ± 0%     ~     (all equal)
ycsb/F/nodes=3/cpu=32     154 ±20%     148 ±19%     ~     (p=0.535 n=10+10)
```
This also seems to indicate that reducing maximum clock uncertainty would positively impact YCSB throughput. That would be an interesting experiment to run.

**Pull request merged**
