### PR TITLE
backport-21.2: fix node drain when using the v22.1 CLI

### LINKED ISSUE #85455: When 22.1 binary is used to decommission 21.x node, gateway node is drained instead of target one.
**Describe the problem**

When 22.1 binary is used to decommission cluster running 21.x resulting state is not what it should be.
In the past decommission for one node could be done by another because it only updates liveness record to isolate it.

With newer binary however, cli will first ask gateway node to mark target node as decommissioning, then ask gateway node to drain target node and finally ask gateway node to mark target as decommissioned.

This doesn't work with older clusters as older clusters can't forward drain requests, but will instead drain themselves. So what happens is cluster is left in a state where target node is decommissioned, but gateway node is drained and doesn't serve SQL traffic and has no leases.

**To Reproduce**

Run 21.2 cluster with 5 nodes.
Run `cockroach node decommission 3` on node 5 or provide cli with url for node 5.
Observe that node 5 is now drained, node 3 is decommissioned.

**Additional context**
It may be unsafe to perform decommission old cluster (21.2-) with a new (22.1+) binary as it is left with less available nodes than expected even if no data is immediately lost.

Jira issue: CRDB-18253

### PR DESCRIPTION
**Pull request by knz**
Fixes #85455.

Backport 2/2 commits from #73991.

/cc @cockroachdb/release

Release justification: bug fix

---

### CODE REVIEW

**Comment by knz** [comment]
@mwang1026 we're fixing the bug by backporting (part of) a 22.1 PR to 21.2. To prevent users from encountering the issue, they'd need to upgrade their 21.2 cluster to the latest version of 21.2 containing this patch. Is this acceptable?

**Comment by mwang1026** [comment]
> To prevent users from encountering the issue, they'd need to upgrade their 21.2 cluster to the latest version of 21.2 containing this patch. Is this acceptable?

I think it's it's strictly better than nothing so I think we should backport regardless. My more general question is what alternatives we had?

**Comment by knz** [comment]
> My more general question is what alternatives we had?

Change 22.1 to refuse to connect to 21.2 clusters.

**Review by aliher1911 — APPROVED** [review]
👍

**Pull request merged**
