### PR TITLE
raft: re-enable config change safety

### PR DESCRIPTION
**Pull request by pav-kv**
Config changes in this `raft` implementation require a safety constraint: the leader must not append a config change if it hasn't applied all config changes in its log.

The `DisableConfChangeValidation` flag disables this check under the assumption that the state machine layer provides the equivalent guarantee. However, it is hard to argue that this is true in split leaseholder/leader scenarios.

This commit re-enables this check, to bring the safety back. The other two state-machine-level checks concerned with entering and leaving joint configs can still be disabled.

Related to #105797, https://github.com/etcd-io/raft/pull/81, #106515 (https://github.com/cockroachdb/cockroach/pull/106515#issuecomment-2071371853)

Epic: CRDB-37617
Release note: none

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124804#-:-Nz4B29ACFQtlwIViWz_:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pav-kv)

___
*[`pkg/raft/testdata/confchange_disable_validation.txt` line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124804#-Nz4B8WhBet4YySWktvu:-Nz4B8WhBet4YySWktvv:bd5kzzk) ([raw file](https://github.com/cockroachdb/cockroach/blob/182fabfe28342abd8f623fd70f10cbe740863920/pkg/raft/testdata/confchange_disable_validation.txt#L59)):*
> ```help
>   1->3 MsgApp Term:1 Log:1/4 Commit:5 Entries:[1/5 EntryConfChangeV2 l2 l3]
> 
> # Propose new config change. Note how it isn't rejected,
> ```

Do we want to adjust this test to demonstrate the new behavior where even with `DisableConfChangeValidation=true`, a new config change is rejected if the previous has not been applied yet?

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124804)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[`pkg/raft/testdata/confchange_disable_validation.txt` line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124804#-Nz4B8WhBet4YySWktvu:-Nz4Q91mD0ZRa7mWeO67:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/182fabfe28342abd8f623fd70f10cbe740863920/pkg/raft/testdata/confchange_disable_validation.txt#L59)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we want to adjust this test to demonstrate the new behavior where even with `DisableConfChangeValidation=true`, a new config change is rejected if the previous has not been applied yet?
</blockquote></details>

Done

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124804#-:-Nz4QHFN2FcSvSz3al54:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pav-kv)

**Comment by pav-kv** [comment]
bors r=nvanbenschoten

**Pull request merged**
