### PR TITLE
serverutils: improve the initialization of TestServer

### PR DESCRIPTION
**Pull request by knz**
The primary purpose of this patch is to tease out a `StartServerOnly()` function that doesn't return a `*gosql.DB` and `*kv.DB`, to improve readability in those tests that don't need them.

In doing so however, this patch also fixes two bugs:

- the advertised behavior of  `StartServer()` was to return `.ApplicationLayer().DB()` in the second return value. However, the code was effectively returning `.SystemLayer().DB()` instead. This patch fixes it.

- in case a binary version override was set in the parameters, the expectation is to upgrade both the storage layer and the application layer to the specified version. The code was only upgrading the application layer. This patch fixes it.

Release note: None
Epic: CRDB-28893

### CODE REVIEW

**Review by stevendanna — APPROVED** [review]
LGTM.  Good catch.

**Review by yuzefovich — APPROVED** [review]
Nice find! :lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107808#-:-NaSaq4DBCHQluRiQRGK:boyyrm)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @healthy-pod and @knz)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107808#-NaSafEf85ZbFKnMWsQD):*
nit: s/second/third/.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107808)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @healthy-pod and @yuzefovich)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107808#-NaSafEf85ZbFKnMWsQD):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: s/second/third/.
</blockquote></details>

Fixed.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107808)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @healthy-pod, @herkolategan, @knz, @miretskiy, @msirek, @Santamaura, and @srosenberg)

___
*[`pkg/testutils/lint/lint_test.go` line 595 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/107808#-NaSsjfw0-Jt3-n0N6Ds:-NaSsjfw0-Jt3-n0N6Dt:bxfb0r7) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c4ab43887ced1eee0836791ffbc364bf585e37b/pkg/testutils/lint/lint_test.go#L595)):*
> ```Go
> 			"grep",
> 			"-nE",
> 			`, _, _ := serverutils\.StartServer\(`,
> ```

nit: perhaps make colon optional, i.e. `, _, _ :?= serverutils\.StartServer\(`.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107808)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @healthy-pod, @herkolategan, @miretskiy, @msirek, @Santamaura, @srosenberg, and @yuzefovich)

___
*[`pkg/testutils/lint/lint_test.go` line 595 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/107808#-NaSsjfw0-Jt3-n0N6Ds:-NaT--Xl0qhY5a5JGjsn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5c4ab43887ced1eee0836791ffbc364bf585e37b/pkg/testutils/lint/lint_test.go#L595)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: perhaps make colon optional, i.e. `, _, _ :?= serverutils\.StartServer\(`.
</blockquote></details>

Done.

**Comment by knz** [comment]
TFYRs!

bors r=stevendanna,yuzefovich

**Comment by knz** [comment]
bors r=stevendanna,yuzefovich

**Comment by knz** [comment]
bors r-

There's a merge conflict with #107757 which is in the bors queue already.

**Comment by knz** [comment]
bors r=stevendanna,yuzefovich

**Pull request merged**
