### PR TITLE
opt: rename `build` to `execbuilder` and `optbuilder`

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### opt: rename `exec/build` to `exec/execbuilder`

Release note: None

#### opt: rename `build` to `optbuilder`

Release note: None

#### opt: rename NewBuilder to New

Now that the package names contain `builder`, remove the
stuttering from the constructor.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Ah, I thought I merged my other PR. I'll merge that and redo this PR.

**Comment by RaduBerinde** [comment]
Updated.

**Comment by andy-kimball** [comment]
:lgtm:

I also had another thought to consider: should we also rename `Builder` to `B`, so that we have `execbuilder.B` and `optbuilder.B`, similar to `types.T` and `testing.T`?

---

Review status: 0 of 22 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22544#-:-L4vncmOY9zqdV8mPzam:b-embkt9)*

**Comment by RaduBerinde** [comment]
Not crazy about it, we don't really do that in other places. In any case, AFAICT we never actually have `xxbuilder.Builder` anywhere in the code, so there's not much benefit (and it would just make the internal code a bit more cryptic).

---

Review status: 0 of 22 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22544#-:-L4vpaYAGIjRvC5PeChw:bnmwro4)*

**Comment by andy-kimball** [comment]
ok, sounds fine to me

---

Review status: 0 of 22 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22544#-:-L4vqjQ4NCs8X38mxr2R:b5vy8bi)*

**Pull request merged**
