### PR TITLE
sql: do not acquire a table lease using a users transaction

### PR DESCRIPTION
**Pull request by vivekmenezes**

### CODE REVIEW

**Comment by vivekmenezes** [comment]
@andreimatei the second commit needs more work so don't consider it part of this PR. Is the first commit looking okay?

**Comment by vivekmenezes** [comment]
removed the second commit from this PR

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

*[pkg/sql/helpers_test.go, line 112 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17307#-KqU8CjMkNddlIBwmWiN:-KqU8CjMkNddlIBwmWiO:btbe86r) ([raw file](https://github.com/cockroachdb/cockroach/blob/661e700cd5e93e764e75b44f7a97d420d64904e9/pkg/sql/helpers_test.go#L112)):*
> ```Go
> // The lease is grabbed on the latest version if >= specified version.
> // It returns a table descriptor and an expiration time.
> // A transaction is allowed to use the table descriptor as long as the txn
> ```

stale comment

---

*[pkg/sql/lease.go, line 136 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17307#-KqU9oROBdSfPmy6rkmK:-KqU9oROBdSfPmy6rkmL:b-bom1ta) ([raw file](https://github.com/cockroachdb/cockroach/blob/661e700cd5e93e764e75b44f7a97d420d64904e9/pkg/sql/lease.go#L136)):*
> ```Go
> 	ctx context.Context,
> 	tableID sqlbase.ID,
> 	minVersion sqlbase.DescriptorVersion,
> ```

Does `minVersion` still make sense in this interface? If a version check is really needed somewhere, the client can do it.

---

*[pkg/sql/lease.go, line 147 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17307#-KqU8Uh2krTwiYQeTKdK:-KqU8Uh2krTwiYQeTKdL:btbe86r) ([raw file](https://github.com/cockroachdb/cockroach/blob/661e700cd5e93e764e75b44f7a97d420d64904e9/pkg/sql/lease.go#L147)):*
> ```Go
> 		}
> 
> 		// Use the supplied (user) transaction to look up the descriptor because the
> ```

stale comment

---

*[pkg/sql/lease.go, line 198 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17307#-KqU9B4pWAye9tFQaksL:-KqU9B4pWAye9tFQaksM:b-m94ex8) ([raw file](https://github.com/cockroachdb/cockroach/blob/661e700cd5e93e764e75b44f7a97d420d64904e9/pkg/sql/lease.go#L198)):*
> ```Go
> 			s.testingKnobs.LeaseAcquiredEvent(table.TableDescriptor, err)
> 		} else {
> 			s.testingKnobs.LeaseAcquiredEvent(sqlbase.TableDescriptor{}, err)
> ```

this seems funky to me - what can a test do with an empty descriptor? It doesn't even know what the failed lease acquisition was for. If we really need to call this for failures, at least pass a table id.

---

*[pkg/sql/lease.go, line 576 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17307#-KqUAiqiU7gqelhKap4w:-KqUAiqiU7gqelhKap4x:btbe86r) ([raw file](https://github.com/cockroachdb/cockroach/blob/661e700cd5e93e764e75b44f7a97d420d64904e9/pkg/sql/lease.go#L576)):*
> ```Go
> 
> // acquire returns a version of the table appropriate for the timestamp
> // of the transaction. The table will have its refcount incremented,
> ```

stale comment

---

*[pkg/sql/lease.go, line 810 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17307#-KqUB14-tMwR-ia6f8d1:-KqUB14-tMwR-ia6f8d2:bz1aht3) ([raw file](https://github.com/cockroachdb/cockroach/blob/661e700cd5e93e764e75b44f7a97d420d64904e9/pkg/sql/lease.go#L810)):*
> ```Go
> func (t *tableState) acquireNodeLease(
> 	ctx context.Context,
> 	minVersion sqlbase.DescriptorVersion,
> ```

does `minVersion` still make sense?

---

*[pkg/sql/lease.go, line 945 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17307#-KqUBb6Xeaf49fHpk8uN:-KqUBb6Xeaf49fHpk8uO:b-zaegpw) ([raw file](https://github.com/cockroachdb/cockroach/blob/661e700cd5e93e764e75b44f7a97d420d64904e9/pkg/sql/lease.go#L945)):*
> ```Go
> 	// active lease, so that it doesn't get released when removeInactives()
> 	// is called below. Release this lease after calling removeInactives().
> 	table, err := t.acquire(ctx, m.clock.Now(), m)
> ```

this doesn't seem great to me: the `acquire` call might actually acquire a lease from the store, but we don't want that; we just want an existing lease, if not expired, to not be removed. I think we should find some other solution.

---

*[pkg/sql/lease.go, line 1157 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17307#-KqUCeW1axZYldq23cUs:-KqUCeW1axZYldq23cUt:b-pa15pa) ([raw file](https://github.com/cockroachdb/cockroach/blob/661e700cd5e93e764e75b44f7a97d420d64904e9/pkg/sql/lease.go#L1157)):*
> ```Go
> 
> // AcquireByName acquires a read lease for the specified table.
> // The lease is grabbed for the most recent version of the descriptor that the
> ```

 stale comment?

---

*[pkg/sql/lease.go, line 1270 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17307#-KqUDR1gkRdXl-5SkJPI:-KqUDR1gkRdXl-5SkJPJ:b-el7ntg) ([raw file](https://github.com/cockroachdb/cockroach/blob/661e700cd5e93e764e75b44f7a97d420d64904e9/pkg/sql/lease.go#L1270)):*
> ```Go
> 
> // Acquire acquires a read lease for the specified table ID. A lease is
> // grabbed for the most recent version of the descriptor that the lease manager
> ```

stale comment?

---

*[pkg/sql/lease.go, line 1273 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17307#-KqUCvVRb_l4ddNd8YxB:-KqUCvVSzCQDsexqtkBQ:b-1z0ns0) ([raw file](https://github.com/cockroachdb/cockroach/blob/661e700cd5e93e764e75b44f7a97d420d64904e9/pkg/sql/lease.go#L1273)):*
> ```Go
> // knows about. It returns a table descriptor and an expiration time.
> // A transaction is allowed to use the table descriptor as long as the txn
> // timestamp < expiration time.
> ```

which expiration time? Let's say something about the return value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17307#-:-KqUF0Le_JdjOEVU2kTg:bnfp4nl)*

**Comment by vivekmenezes** [comment]
Review status: 0 of 7 files reviewed at latest revision, 10 unresolved discussions.

---

*[pkg/sql/helpers_test.go, line 112 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17307#-KqU8CjMkNddlIBwmWiN:-KqUGR1BCGCvQsyDDe8T:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/661e700cd5e93e764e75b44f7a97d420d64904e9/pkg/sql/helpers_test.go#L112)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

stale comment
</blockquote></details>

Done.

---

*[pkg/sql/lease.go, line 136 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17307#-KqU9oROBdSfPmy6rkmK:-KqUP4otcpwqGGCZPZ8r:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/661e700cd5e93e764e75b44f7a97d420d64904e9/pkg/sql/lease.go#L136)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Does `minVersion` still make sense in this interface? If a version check is really needed somewhere, the client can do it.
</blockquote></details>

Done.

---

*[pkg/sql/lease.go, line 147 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17307#-KqU8Uh2krTwiYQeTKdK:-KqUH16RwEUVULl01B2P:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/661e700cd5e93e764e75b44f7a97d420d64904e9/pkg/sql/lease.go#L147)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

stale comment
</blockquote></details>

Done.

---

*[pkg/sql/lease.go, line 198 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17307#-KqU9B4pWAye9tFQaksL:-KqUHYvOtlMDxSj1Zt1w:b-fnqzi) ([raw file](https://github.com/cockroachdb/cockroach/blob/661e700cd5e93e764e75b44f7a97d420d64904e9/pkg/sql/lease.go#L198)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

this seems funky to me - what can a test do with an empty descriptor? It doesn't even know what the failed lease acquisition was for. If we really need to call this for failures, at least pass a table id.
</blockquote></details>

Made this less funky by calling it only in the non-error case.

---

*[pkg/sql/lease.go, line 576 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17307#-KqUAiqiU7gqelhKap4w:-KqUHuSc5usBwmIAU3nV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/661e700cd5e93e764e75b44f7a97d420d64904e9/pkg/sql/lease.go#L576)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

stale comment
</blockquote></details>

Done.

---

*[pkg/sql/lease.go, line 810 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17307#-KqUB14-tMwR-ia6f8d1:-KqUP86xgOYkrfjg4uf9:b-hfpv0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/661e700cd5e93e764e75b44f7a97d420d64904e9/pkg/sql/lease.go#L810)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

does `minVersion` still make sense?
</blockquote></details>

removed

---

*[pkg/sql/lease.go, line 945 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17307#-KqUBb6Xeaf49fHpk8uN:-KqUK0gzWoS-_fZ2nf2w:b-maskk) ([raw file](https://github.com/cockroachdb/cockroach/blob/661e700cd5e93e764e75b44f7a97d420d64904e9/pkg/sql/lease.go#L945)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

this doesn't seem great to me: the `acquire` call might actually acquire a lease from the store, but we don't want that; we just want an existing lease, if not expired, to not be removed. I think we should find some other solution.
</blockquote></details>

actually ensureVersion() above guarantees that the system already has a lease with a version >= minVersion, so it's unlikely that acquire() will acquire a new lease from the store.

---

*[pkg/sql/lease.go, line 1157 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17307#-KqUCeW1axZYldq23cUs:-KqUIWTk8UUXswFTb84_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/661e700cd5e93e764e75b44f7a97d420d64904e9/pkg/sql/lease.go#L1157)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

 stale comment?
</blockquote></details>

Done.

---

*[pkg/sql/lease.go, line 1270 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17307#-KqUDR1gkRdXl-5SkJPI:-KqUJKMytoWCoTsu8305:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/661e700cd5e93e764e75b44f7a97d420d64904e9/pkg/sql/lease.go#L1270)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

stale comment?
</blockquote></details>

Done.

---

*[pkg/sql/lease.go, line 1273 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17307#-KqUCvVRb_l4ddNd8YxB:-KqUJNDexoy-GV8n4DYX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/661e700cd5e93e764e75b44f7a97d420d64904e9/pkg/sql/lease.go#L1273)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

which expiration time? Let's say something about the return value.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17307)*

**Comment by andreimatei** [comment]
LGTM

What I think would be nice is a test on a descriptor with many versions, doing transactions at different timestamps and seeing that the right descriptor is used.

---

Review status: 0 of 7 files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17307#-:-KqUi0YxNhlrDCY_KzZ6:buq9jdc)*

**Comment by vivekmenezes** [comment]
I'm gonna leave that for another day. We have some testing here and my next PR adds another test.

---

Review status: 0 of 7 files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17307#-:-KqVPAOZWLdi0SkSEVVx:bzgwdu4)*

**Comment by andreimatei** [comment]
should this PR remove this:
https://github.com/cockroachdb/cockroach/blob/562ed9650be0aa4534b4dcc11d384b8fe0a96628/pkg/sql/executor.go#L781

---

Review status: 0 of 7 files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17307#-:-KqVPxMuYc9XIhXDLVbO:b-x3win8)*

**Pull request merged**
