### PR TITLE
workload: whitelist allowable dependencies

### PR DESCRIPTION
**Pull request by danhhz**
We want pkg/workload to be lightweight and go gettable, mostly common
interfaces and data structures.

This commit adds a test to lint the transitive dependency graph of
pkg/workload against a whitelist. It also moves out some helpers to a
new package to keep this whitelist sane.

In this case, the helpers take in workload structs and use them on a
CockroachDB instance via SQL. By a similar argument, we should move the
CSV stuff out and perhaps even split up workload's ideas of dataset and
queryload generators, but for now we make a compromise between
invasiveness and dep health.

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
:lgtm:

Didn't review the (what I assumed to be) code movement into `workloadsql`.

> Reviewed 23 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38209#-:-Lhf6I674UkINTM-RL2C:bey4pz3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz)

___
*[pkg/testutils/buildutil/build.go, line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38209#-Lhf5l3G74njJHR6sEU0:-Lhf5l3G74njJHR6sEU1:brp6pvr) ([raw file](https://github.com/cockroachdb/cockroach/blob/88887f46cd06e1679c3d858c3ec3c04c1bae64f5/pkg/testutils/buildutil/build.go#L137)):*
> ```Go
> 		}
> 		for _, imp := range pkg.Imports {
> 			if !strings.HasPrefix(imp, "github.com/cockroachdb/cockroach/") {
> ```

Shouldn't an import that's neither stdlib nor vendored fail this also? Unclear how easy this is though and whether it'll ever catch anything meaningful.

**Review by danhhz — COMMENTED** [review]
Yeah, just code movement, updated the commit text to mention that

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38209#-:-LhfZvH68sBiOwEpYp7T:b-nash62)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @tbg)

___
*[pkg/testutils/buildutil/build.go, line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38209#-Lhf5l3G74njJHR6sEU0:-LhfZzO-72ve2hZrsvrV:b-ykor20) ([raw file](https://github.com/cockroachdb/cockroach/blob/88887f46cd06e1679c3d858c3ec3c04c1bae64f5/pkg/testutils/buildutil/build.go#L137)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Shouldn't an import that's neither stdlib nor vendored fail this also? Unclear how easy this is though and whether it'll ever catch anything meaningful.
</blockquote></details>

Wait do we have those? I thought every non-stdlib dep was vendored, otherwise we wouldn't be hermetic (or even less hermetic than we are). IMO catching violations of that should happen at a different level

**Review by tbg — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38209)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @danhhz)

___
*[pkg/testutils/buildutil/build.go, line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38209#-Lhf5l3G74njJHR6sEU0:-Lhg4zj7A1xd9_-LZhkR:bp1fh6c) ([raw file](https://github.com/cockroachdb/cockroach/blob/88887f46cd06e1679c3d858c3ec3c04c1bae64f5/pkg/testutils/buildutil/build.go#L137)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Wait do we have those? I thought every non-stdlib dep was vendored, otherwise we wouldn't be hermetic (or even less hermetic than we are). IMO catching violations of that should happen at a different level
</blockquote></details>

I don't think we have those, but I'm also not sure if anything really catches it. I guess our CI builds on a blank gopath frequently enough... or maybe we really have a lint against this but I'm not sure. I don't think we run `dep` as part of CI?

**Review by danhhz — COMMENTED** [review]
TFTR!

bors r=tbg

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38209#-:-Lhg6zA-02HWULgw-qEa:b-kg5fnc)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @tbg)

___
*[pkg/testutils/buildutil/build.go, line 137 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38209#-Lhf5l3G74njJHR6sEU0:-Lhg6f_k3RBRqf-9nb6V:b7xssrv) ([raw file](https://github.com/cockroachdb/cockroach/blob/88887f46cd06e1679c3d858c3ec3c04c1bae64f5/pkg/testutils/buildutil/build.go#L137)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I don't think we have those, but I'm also not sure if anything really catches it. I guess our CI builds on a blank gopath frequently enough... or maybe we really have a lint against this but I'm not sure. I don't think we run `dep` as part of CI?
</blockquote></details>

Gotcha. I still think that if we decide we care about it, it should be done once in some higher level test rather than have each user of this method check some subset of the dep graph

**Pull request merged**
