### PR TITLE
sql,gcjob: enable declarative schema changer in drop tests

### LINKED ISSUE #78030: sql: enable declarative schema changer in unit tests which test DROP behaviour
Currently we only test the legacy schema changer in `drop_tests.go` and `gc_job_test.go`:

https://github.com/cockroachdb/cockroach/blob/5d63be11bbbce3fc64a2fc1284a887e26c3011c8/pkg/sql/drop_test.go#L119
https://github.com/cockroachdb/cockroach/blob/5d63be11bbbce3fc64a2fc1284a887e26c3011c8/pkg/sql/drop_test.go#L281
https://github.com/cockroachdb/cockroach/blob/5d63be11bbbce3fc64a2fc1284a887e26c3011c8/pkg/sql/drop_test.go#L630
https://github.com/cockroachdb/cockroach/blob/5d63be11bbbce3fc64a2fc1284a887e26c3011c8/pkg/sql/drop_test.go#L723
https://github.com/cockroachdb/cockroach/blob/5d63be11bbbce3fc64a2fc1284a887e26c3011c8/pkg/sql/drop_test.go#L968
https://github.com/cockroachdb/cockroach/blob/5d63be11bbbce3fc64a2fc1284a887e26c3011c8/pkg/sql/drop_test.go#L1288
https://github.com/cockroachdb/cockroach/blob/5d63be11bbbce3fc64a2fc1284a887e26c3011c8/pkg/sql/drop_test.go#L1340

https://github.com/cockroachdb/cockroach/blob/c4f5c5703d16a95c9203e93bd4987dbcffbd3586/pkg/sql/gcjob_test/gc_job_test.go#L290-L291
https://github.com/cockroachdb/cockroach/blob/c4f5c5703d16a95c9203e93bd4987dbcffbd3586/pkg/sql/gcjob_test/gc_job_test.go#L461-L462

There doesn't seem to be any reason why we shouldn't have equivalent unit tests for the declarative schema changer. Let's add these.

Epic: CRDB-2356

Jira issue: CRDB-13930

### PR DESCRIPTION
**Pull request by ajwerner**
A couple of these tests were just fully rotted. A lot of them are close but
easy enough to carry along.

Fixes #78030.

Release note: None

### CODE REVIEW

**Review by postamar — APPROVED** [review]
:lgtm: 

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79119#-:-MzVPRZkDADQk5M2uw8E:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by postamar** [comment]
Most if not all these CI test failures are the result of the changes to the statement formatting.

**Review by postamar — COMMENTED** [review]
> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79119)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner)

___
*[pkg/sql/schemachanger/scplan/internal/opgen/opgen_view.go, line 79 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79119#-MzW6eDIEDLTwKGT4LMm:-MzW6eDIEDLTwKGT4LMn:b-6nkqp9) ([raw file](https://github.com/cockroachdb/cockroach/blob/f7e7c85c9cb169b484b40b7b5b5a8828cf8cfc23/pkg/sql/schemachanger/scplan/internal/opgen/opgen_view.go#L79)):*
> ```Go
> 					if !this.IsMaterialized {
> 						return nil
> ```

nit: superfluous newline
___
*[pkg/sql/logictest/testdata/logic_test/fk, line 1009 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79119#-MzW6uNc8yUdB_wC8EhL:-MzW6uNc8yUdB_wC8EhM:bvfbsnh) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a6b0b6b6b744ff3407877b629dcc60cf56e9e5c/pkg/sql/logictest/testdata/logic_test/fk#L1009)):*
> ```
>   description = 'GC for DROP TABLE a');
> ----
> SCHEMA CHANGE GC
> ```

Is this legit? It doesn't seem like the expected query results should be empty here.

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Comment by ajwerner** [comment]
blathers backport 22.1

**Pull request merged**
