### PR TITLE
sql: add AST annotations

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### sql: add AST annotations

This change adds infrastructure for annotating AST nodes. Only certain
nodes can be annotated (currently `UnresolvedObjectName`). The parser
sets up annotation indices for these nodes, and the annotations are
stored in a separate Annotation container. The annotations will allow
us to stop modifying the AST during type and semantic checking.

The annotation for an `UnresolvedObjectName` will contain the resolved
`*TableName`.

See #34240 and #22847 for more context.

Release note: None

#### sql: use UnresolvedObjectName in AlterTable

Change AlterTable to contain an `UnresolvedObjectName`.

Release note: None

### CODE REVIEW

**Review by jordanlewis — CHANGES_REQUESTED** [review]
I love this idea, but I'm nervous it's going to make it easy to accidentally cause bugs by using the wrong format method. Is it feasible to switch everybody to have annotations available and have just one format method, or just too much work?

> Reviewed 31 of 31 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37484#-:-LeqPJA8-g4WLW1jQX1G:b-2uavg2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @knz, and @RaduBerinde)

___
*[pkg/sql/plan.go, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37484#-LeqM2HZ4W0T6Pzjpjtv:-LeqM2HZ4W0T6Pzjpjtw:bp3axc3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a759452847bed66c4a9af0668ccf15a051ef972b/pkg/sql/plan.go#L101)):*
> ```Go
> }
> 
> // FormatAST is a convenience wrapper for tree.AsStringWithFlagsEx.
> ```

Could you improve this comment to explain what the method does as well? A reader might not be familiar with tree.AsStringWithFlagsEx.
___
*[pkg/sql/sem/tree/format.go, line 380 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37484#-LeqMT7F9zrLTdWq5Ezu:-LeqMT7F9zrLTdWq5Ezv:b1furbi) ([raw file](https://github.com/cockroachdb/cockroach/blob/a759452847bed66c4a9af0668ccf15a051ef972b/pkg/sql/sem/tree/format.go#L380)):*
> ```Go
> 
> // AsStringWithFlagsEx pretty prints a node to a string given specific flags.
> func AsStringWithFlagsEx(n NodeFormatter, fl FmtFlags, ann *Annotations) string {
> ```

I find the naming of these methods confusing. What is `Ex`? Would it be cleaner to always require an `*Annotations` pointer in `AsStringWithFlags`? I'm essentially nervous that people will forget to use `Ex` when necessary - what happens when you try to prettyprint something that needs an annotation but don't pass any annotations?
___
*[pkg/sql/sem/tree/name_part.go, line 273 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37484#-LeqP0oEBh6om2-71Rqu:-LeqP0oEBh6om2-71Rqv:bx94ndi) ([raw file](https://github.com/cockroachdb/cockroach/blob/a759452847bed66c4a9af0668ccf15a051ef972b/pkg/sql/sem/tree/name_part.go#L273)):*
> ```Go
> 	// annotation.
> 	if ctx.HasFlags(FmtAlwaysQualifyTableNames) || ctx.tableNameFormatter != nil {
> 		if n := u.Resolved(ctx.ann); n != nil {
> ```

Does this panic if nobody set `ctx.ann`?  It seems unsafe, since there's 2 paths to get here - one via Format with the annotations, with via the format without annotations (which I think will panic).

**Review by RaduBerinde — COMMENTED** [review]
That would be nice, but I think the surface area is huge. In particular, `String()` methods.

Note that it's a panic to try to set up a fmt ctx with the AlwaysQualify flag and no annotations, so any erroneous usage will be obvious. I grepped for the flag across the code base and made sure to pass annotations.

In the future I can look at creating separate infrastructure for this kind of stuff, so that normal formatting never looks at annotations. Replacing names with fully qualified names doesn't really fall under "formatting" IMO
If we had an easy way to deep-copy an AST, we would do that and rewrite the unresolved names, and format the copy. The code paths that need this aren't perf sensitive I don't think.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37484#-:-LeqVxfz7NO5u01WDx_N:b-3w4af7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @knz, and @RaduBerinde)

___
*[pkg/sql/sem/tree/format.go, line 380 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37484#-LeqMT7F9zrLTdWq5Ezu:-LeqXujiA7JgvhcsEq9t:b-2zok94) ([raw file](https://github.com/cockroachdb/cockroach/blob/a759452847bed66c4a9af0668ccf15a051ef972b/pkg/sql/sem/tree/format.go#L380)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I find the naming of these methods confusing. What is `Ex`? Would it be cleaner to always require an `*Annotations` pointer in `AsStringWithFlags`? I'm essentially nervous that people will forget to use `Ex` when necessary - what happens when you try to prettyprint something that needs an annotation but don't pass any annotations?
</blockquote></details>

If you don't pass annotations and the flags require it, you get a panic right away.

I could change the existing method but allow passing `nil` for annotations. 
___
*[pkg/sql/sem/tree/name_part.go, line 273 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37484#-LeqP0oEBh6om2-71Rqu:-LeqWe0qAuulGMGXhg62:b-m4ba0i) ([raw file](https://github.com/cockroachdb/cockroach/blob/a759452847bed66c4a9af0668ccf15a051ef972b/pkg/sql/sem/tree/name_part.go#L273)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Does this panic if nobody set `ctx.ann`?  It seems unsafe, since there's 2 paths to get here - one via Format with the annotations, with via the format without annotations (which I think will panic).
</blockquote></details>

But we can't have `FmtAlwaysQualifyTableNames` set and no annotations. We would have paniced when we tried to create the ctx.

I think you're right for the case where we set `tableNameFormatter` and not the flag though, I'll make that require annotations.

**Review by knz — COMMENTED** [review]
This PR fills me with joy. This represents a clear and successful move towards the "SQL leaf data" proposal/RFC from a little more than a year ago. I just can't wait until we put more data in annotations - subquery metadata, placeholders, and eventually ... types, syntax locations, etc.

I appreciate that the formatting API might become a bit unsatisfying/janky until we figure out the ergonomics. OTOH, this area of the code base has been pretty stable in the last year and a half, and I don't feel that a little back and forth over multiple PRs will impede progress of some other team members.

Jordan I support your comments to ensure we are careful to avoid brittleness - it should become hard to crash the thing by accident. This will be also my little moment to shake my fists at the air and say 'we should be using panics as exceptions and catch them'. I left one comment in that direction below. Other than that, I think the design overall is sound (and we had all the high level discussions last year, so i'm confident the approach is good). 

> Reviewed 31 of 31 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37484#-:-Leqaq82B4HcSTp0ibuc:b-gh5ynw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @RaduBerinde)

___
*[pkg/sql/sem/tree/format.go, line 211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37484#-LeqaF5r7y-oFHbx7mkt:-LeqaF5s2ReUH0dG23Sk:b-4hb5op) ([raw file](https://github.com/cockroachdb/cockroach/blob/a759452847bed66c4a9af0668ccf15a051ef972b/pkg/sql/sem/tree/format.go#L211)):*
> ```Go
> func NewFmtCtxEx(f FmtFlags, ann *Annotations) *FmtCtx {
> 	if f&flagsRequiringAnnotations != 0 && ann == nil {
> 		panic("no Annotations provided")
> ```

you could throw a pgerror.NewAssertionError here and below - this way if this happens on a code path where we catch panics, we'll get decent behavior.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37484)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @knz, and @RaduBerinde)

___
*[pkg/sql/sem/tree/format.go, line 211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37484#-LeqaF5r7y-oFHbx7mkt:-LesAC5k5CM0Dq0ItuEb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a759452847bed66c4a9af0668ccf15a051ef972b/pkg/sql/sem/tree/format.go#L211)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

you could throw a pgerror.NewAssertionError here and below - this way if this happens on a code path where we catch panics, we'll get decent behavior.
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/name_part.go, line 273 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37484#-LeqP0oEBh6om2-71Rqu:-LesAGu95K_1PTUTMWLd:b-9pmtm0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a759452847bed66c4a9af0668ccf15a051ef972b/pkg/sql/sem/tree/name_part.go#L273)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

But we can't have `FmtAlwaysQualifyTableNames` set and no annotations. We would have paniced when we tried to create the ctx.

I think you're right for the case where we set `tableNameFormatter` and not the flag though, I'll make that require annotations.
</blockquote></details>

The `tableNameFormatter` stuff is more problematic. In most cases it is not used with resolved names. It is also abused as a way to change the `*TableNames` in place (this could in the future be replaced with a loop over the annotations). For now I added a special case that converts the unresolved object name to a table name to keep things working while we transition.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37484)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @knz)

___
*[pkg/sql/plan.go, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37484#-LeqM2HZ4W0T6Pzjpjtv:-Levlscs-JluG3Dk1G9V:b-kux3m9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a759452847bed66c4a9af0668ccf15a051ef972b/pkg/sql/plan.go#L101)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Could you improve this comment to explain what the method does as well? A reader might not be familiar with tree.AsStringWithFlagsEx.
</blockquote></details>

Removed this wrapper, I made a shorthand method for the annotations instead.
___
*[pkg/sql/sem/tree/format.go, line 380 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37484#-LeqMT7F9zrLTdWq5Ezu:-LevlggN7deFyV6PfZE8:b-cbw16c) ([raw file](https://github.com/cockroachdb/cockroach/blob/a759452847bed66c4a9af0668ccf15a051ef972b/pkg/sql/sem/tree/format.go#L380)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

If you don't pass annotations and the flags require it, you get a panic right away.

I could change the existing method but allow passing `nil` for annotations. 
</blockquote></details>

I replaced this "extended" version with a more specific version for the flag (`AsStringWithFQNames`). I think it's more clear now.

**Review by jordanlewis — APPROVED** [review]
:lgtm:, thanks for making the changes. I still think that having a variant with FQNames vs not is kind of confusing... but it seems like there's nothing we can do it about it just yet.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37484#-:-Levums14gSWTkmla-ML:bna9hfq)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @knz)

**Comment by RaduBerinde** [comment]
TFTRs!

bors r+

**Pull request merged**
