### PR TITLE
kvserver: change issue assertion into regular assertion

### PR DESCRIPTION
**Pull request by erikgrinaker**
This assertion used to be a `log.Fatalf`, but was downgraded to a user
error with Sentry report in c1b1189, as we got reports of violations in
the wild.

The bug now appears to be fixed, as there are no reports of this in
Sentry, so this patch changes the error to a regular
`errors.AssertionFailedf`.

Release note: None

### CODE REVIEW

**Comment by erikgrinaker** [comment]
No, I agree -- changed it into an `errors.AssertionFailedf`.

**Review by knz — APPROVED** [review]

**Comment by erikgrinaker** [comment]
bors r=knz

**Comment by erikgrinaker** [comment]
bors r=knz

**Pull request merged**
