### PR TITLE
sql: fix show create table after altering col type of col with comment

### PR DESCRIPTION
**Pull request by chengxiong-ruan**
Previously `SHOW CREATE TABLE` use `sub_id` from `system.comments`
as a column id to find a column. However we actually use `PGAttributeNum`
when creating a column comment. So things will break if a column's id
has changed such as when type is altered.

Release note (sql change): Previously, if a column in a table has a comment,
`SHOW CREATE TABLE` would fail after the column type is changed.
Now this is fixed.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79998)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan)

___
*[pkg/sql/catalog/descriptor.go, line 533 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79998#-N-hRM5DBMCtcOKgxov9:-N-hRM5DBMCtcOKgxovA:b-83dqmw) ([raw file](https://github.com/cockroachdb/cockroach/blob/98e2fa34797e67ed412a990890640e1312577a81/pkg/sql/catalog/descriptor.go#L533)):*
> ```Go
> 	// PGAttributeNum (if set, otherwise ID) matches the provider id.
> 	// Error is returned if no column is found.
> 	FindColumnWithPGAttributeNum(id uint32) (Column, error)
> ```

how do you feel about giving this a proper type in `catid` and making the proto use a `casttype`?
___
*[pkg/sql/comment_on_column_test.go, line 190 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79998#-N-hRZGg8bI6B4Ro4Tww:-N-hRZGg8bI6B4Ro4Twx:b-oaqwkg) ([raw file](https://github.com/cockroachdb/cockroach/blob/98e2fa34797e67ed412a990890640e1312577a81/pkg/sql/comment_on_column_test.go#L190)):*
> ```Go
> }
> 
> func TestCommentOnAlteredColumn(t *testing.T) {
> ```

this feels like it could have been a logic test, no?

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79998)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/catalog/descriptor.go, line 533 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79998#-N-hRM5DBMCtcOKgxov9:-N-hhMRO6NUXRtuXqYfh:b-9pecxa) ([raw file](https://github.com/cockroachdb/cockroach/blob/98e2fa34797e67ed412a990890640e1312577a81/pkg/sql/catalog/descriptor.go#L533)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

how do you feel about giving this a proper type in `catid` and making the proto use a `casttype`?
</blockquote></details>

I think it's a good idea.
___
*[pkg/sql/comment_on_column_test.go, line 190 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79998#-N-hRZGg8bI6B4Ro4Tww:-N-hhPaSE5H5nlAb9Ubh:bnldnhq) ([raw file](https://github.com/cockroachdb/cockroach/blob/98e2fa34797e67ed412a990890640e1312577a81/pkg/sql/comment_on_column_test.go#L190)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

this feels like it could have been a logic test, no?
</blockquote></details>

you're absolutely right.

**Comment by chengxiong-ruan** [comment]
*[pkg/sql/schemachanger/scdecomp/decomp.go, line 313 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79998#-N-hvy7rA5esVT2G8DGj:-N-hvy7rA5esVT2G8DGk:b2e2i4q) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1c2498201971f9504f8e3b1bf28cc5c98b48bd6/pkg/sql/schemachanger/scdecomp/decomp.go#L313)):*
> ```Go
> 		GeneratedAsIdentityType:           col.GetGeneratedAsIdentityType(),
> 		GeneratedAsIdentitySequenceOption: col.GetGeneratedAsIdentitySequenceOption(),
> 		PgAttributeNum:                    catid.PGAttributeNum(col.ColumnDesc().GetPGAttributeNum()),
> ```

probably some declarative schema changer test would fail because of this, because it seems wrong to access `PGAttributeNum` directly instead of calling `GetPGAttributeNum()` :(
will fix test later..

**Review by ajwerner — CHANGES_REQUESTED** [review]
Are there ever going to be problems whereby the `PGAttributeNum` is not set on a schema change and we're sad about it? Is this a migration? 

> Reviewed 10 of 23 files at r2, 5 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79998#-:-N-xWfk09-eprj3CfF6w:b-j7391p)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @chengxiong-ruan)

___
*[pkg/sql/catalog/descpb/structured.go, line 123 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/79998#-N-xXBBb0OOrcbIaYv01:-N-xXBBcDBfZOfCC2TvN:bs335ej) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dcdfdeee859079d2057f076698e780230a5481c/pkg/sql/catalog/descpb/structured.go#L123)):*
> ```Go
> 
> // PGAttributeNum is a custom type for ColumnDescriptor's PGAttributeNum field.
> type PGAttributeNum catid.PGAttributeNum
> ```

I think this should be `type PGAttributeNum = catid.PGAttributeNum`. It's subtly but importantly different.

**Review by chengxiong-ruan — COMMENTED** [review]
> Are there ever going to be problems whereby the PGAttributeNum is not set on a schema change and we're sad about it?
Not that I know of. I went through the all the `Read` usage of PGAttributeNum, and the only place it's read is this function `GetPGAttributeNum` which is the correct way to accessing PGAttributeNum: http://github.com/cockroachdb/cockroach/blob/master/pkg/sql/catalog/descpb/column.go#L102-L102 
And we did a good job on setting the value when swapping columns : http://github.com/cockroachdb/cockroach/blob/master/pkg/sql/catalog/tabledesc/structured.go#L1872-L1872

In new schema changer, as long as we set `PgAttributeNum` in a column op correctly, then we should be fine, and it's fixed in this PR : http://github.com/cockroachdb/cockroach/blob/master/pkg/sql/schemachanger/scexec/scmutationexec/column.go#L35-L35

> Is this a migration?
Do think so since the underlying type is still `uint32` and we're handling it correctly as far as I can tell. But I do agree that this is kinda error prone if we are not careful enough and access value without calling `GetPGAttributeNum()`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79998#-:-N-xj3bh-VJSy5P1Ab2G:b-t5g1y5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/catalog/descpb/structured.go, line 123 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/79998#-N-xXBBb0OOrcbIaYv01:-N-xloWZ89uodaFU6wvN:b1m0g73) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dcdfdeee859079d2057f076698e780230a5481c/pkg/sql/catalog/descpb/structured.go#L123)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think this should be `type PGAttributeNum = catid.PGAttributeNum`. It's subtly but importantly different.
</blockquote></details>

Good catch! and fixed.

**Comment by chengxiong-ruan** [comment]
Sorry about my terrible formatting in the comment above... reformatted it here..
>Are there ever going to be problems whereby the PGAttributeNum is not set on a schema change and we're sad about it?

Not that I know of. I went through the all the Read usage of PGAttributeNum, and the only place it's read is this function GetPGAttributeNum which is the correct way to accessing PGAttributeNum: http://github.com/cockroachdb/cockroach/blob/master/pkg/sql/catalog/descpb/column.go#L102-L102
And we did a good job on setting the value when swapping columns : http://github.com/cockroachdb/cockroach/blob/master/pkg/sql/catalog/tabledesc/structured.go#L1872-L1872

In new schema changer, as long as we set PgAttributeNum in a column op correctly, then we should be fine, and it's fixed in this PR : http://github.com/cockroachdb/cockroach/blob/master/pkg/sql/schemachanger/scexec/scmutationexec/column.go#L35-L35

> Is this a migration?

Do think so since the underlying type is still uint32 and we're handling it correctly as far as I can tell. But I do agree that this is kinda error prone if we are not careful enough and access value without calling GetPGAttributeNum().

**Review by ajwerner — APPROVED** [review]
> Do think so since the underlying type is still uint32 and we're handling it correctly as far as I can tell. But I do agree that this is kinda error prone if we are not careful enough and access value without calling GetPGAttributeNum().

Sorry, all my talk of migrations was about the difference in handling between 22.1 and 22.2. I think I realize now that we didn't have any cases of using this field in a meaningful way in 22.1. Sorry for the noise.


:lgtm: though you might need to generate some code file 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79998#-:-N-y9orU5TI0yLYpUfjA:b-4wmzka)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @chengxiong-ruan)

___
*[pkg/sql/schemachanger/scdecomp/decomp.go, line 313 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79998#-N-hvy7rA5esVT2G8DGj:-N-yAAYi9FEcDQWTzg5S:bn5a9z6) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1c2498201971f9504f8e3b1bf28cc5c98b48bd6/pkg/sql/schemachanger/scdecomp/decomp.go#L313)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

probably some declarative schema changer test would fail because of this, because it seems wrong to access `PGAttributeNum` directly instead of calling `GetPGAttributeNum()` :(
will fix test later..
</blockquote></details>

Should this method be invoked on `col` directly and not the underlying `ColumnDesc`? Part of me would love to delete the `ColumnDesc()` method.

**Comment by chengxiong-ruan** [comment]
*[pkg/sql/schemachanger/scdecomp/decomp.go, line 313 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79998#-N-hvy7rA5esVT2G8DGj:-N-ycMw76b8Bj-iXm3M-:bhwdv43) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1c2498201971f9504f8e3b1bf28cc5c98b48bd6/pkg/sql/schemachanger/scdecomp/decomp.go#L313)):*
Good catch! updated to call it from `col` directly.
> Part of me would love to delete the ColumnDesc() method.

It just seems annoying to refactor cases where doing writes on the descriptor returned, such as :( http://github.com/cockroachdb/cockroach/blob/master/pkg/sql/alter_table.go#L1025-L1025

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79998)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @chengxiong-ruan)

___
*[pkg/sql/schemachanger/scdecomp/decomp.go, line 313 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79998#-N-hvy7rA5esVT2G8DGj:-N-yhLbkDnHXzq3PNi8t:b-8kbri7) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1c2498201971f9504f8e3b1bf28cc5c98b48bd6/pkg/sql/schemachanger/scdecomp/decomp.go#L313)):*
> It just seems annoying to refactor cases where doing writes on the descriptor returned, such as :( http://github.com/cockroachdb/cockroach/blob/master/pkg/sql/alter_table.go#L1025-L1025

I don't envision deleting that method until after we delete all of the legacy schema changer :). It's nice to keep the north star in sight.

**Comment by chengxiong-ruan** [comment]
TFTR!
bors r+

**Comment by chengxiong-ruan** [comment]
retrying...
bors r+

**Pull request merged**
