### PR TITLE
kvserver: improve the delegate snapshot code

### PR DESCRIPTION
**Pull request by andreimatei**
See individual commits.

### CODE REVIEW

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82490)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[`pkg/kv/kvserver/raft_transport.go` line 468 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/82490#-N43GCRX59MW_MlshGg7:-N43GCRX59MW_MlshGg8:b-t2nxso) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed14ef6a27123d7118fce0d3bcadc213ce136c76/pkg/kv/kvserver/raft_transport.go#L468)):*
> ```Go
> 
> // RaftSnapshot handles incoming streaming snapshot requests.
> func (t *RaftTransport) RaftSnapshot(stream MultiRaft_RaftSnapshotServer) error {
> ```

We should update this handler as well right?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82490)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @nvanbenschoten)

___
*[`pkg/kv/kvserver/raft_transport.go` line 468 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/82490#-N43GCRX59MW_MlshGg7:-N43tk8C05aN2HlsAj44:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ed14ef6a27123d7118fce0d3bcadc213ce136c76/pkg/kv/kvserver/raft_transport.go#L468)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

We should update this handler as well right?
</blockquote></details>

done

**Review by aayushshah15 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82490#-:-N440Wm64zZSuQLfDQ6W:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15 and @nvanbenschoten)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82490#-:-N44JukcAQqi_7JzpMhn:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15 and @nvanbenschoten)

**Pull request merged**
