### PR TITLE
kvserver: default `kv.rangefeed.closed_timestamp_refresh_interval` to 3s

### LINKED ISSUE #108656: kvserver: consider increasing closed timestamp interval defaults
Currently, we publish rangefeed closed timestamp updates every 200ms. This is controlled by two settings:

* `kv.rangefeed.closed_timestamp_refresh_interval = 0` (defaults to `kv.closed_timestamp.side_transport_interval`)
* `kv.closed_timestamp.side_transport_interval = '200ms'`

For the purposes of rangefeeds, this is overly aggressive, and can lead to excessive load with large numbers of ranges (see #96395). The target duration `kv.closed_timestamp.target_duration = '3s'` is one order of magnitude larger than the refresh interval, and the default changefeed `min_checkpoint_frequency = '30s'` is two orders of magnitude larger.

We should increase the default of either `kv.rangefeed.closed_timestamp_refresh_interval` or `kv.closed_timestamp.side_transport_interval` to e.g. 1 second, which is still sufficient for rangefeeds, and can significantly reduce CPU usage on nodes with many replicas.

Preferably `kv.closed_timestamp.side_transport_interval`, since users may already have set this higher (e.g. to 30 seconds), and defaulting `kv.rangefeed.closed_timestamp_refresh_interval` to e.g. 1 second instead of the side transport interval can cause significant load increases when the effective default changes from 30 seconds to 1 second.

Jira issue: CRDB-30568

Epic CRDB-26372

### PR DESCRIPTION
**Pull request by erikgrinaker**
This patch sets `kv.rangefeed.closed_timestamp_refresh_interval` to 3s by default. Previously, it defaulted to 0, which fell back to `kv.closed_timestamp.side_transport_interval` at 200ms by default.

The setting is also made public, since users may often have to tune this. It is also made TenantReadOnly, since tenants need to access the host's setting, and the only current option is to set an explicit setting for the tenant since they can't directly access host settings.

Frequent rangefeed closed timestamp processing can have a significant cost with many ranges, and the 200ms interval was far lower than the default target lag (3s) and changefeed checkpoint interval (30s), so this work was for little benefit.

`kv.closed_timestamp.side_transport_interval` has not been modified, since this would affect the latency of follower reads and global tables.

Resolves #108656.

Release note (ops change): The rangefeed closed timestamp interval controlled by `kv.rangefeed.closed_timestamp_refresh_interval` now defaults to 3 second. This affects how often rangefeeds emit resolved timestamps, and thus how often changefeeds can emit checkpoints. Previously, its default value of 0 would fall back to `kv.closed_timestamp.side_transport_interval`, which defaults to 200 milliseconds. Users who rely on the setting
`kv.closed_timestamp.side_transport_interval` to control the rangefeed closed timestamp interval should make sure they either set `kv.rangefeed.closed_timestamp_refresh_interval` to 0 to retain the old behavior (preferably before upgrading), or to an appropriate value.

### CODE REVIEW

**Comment by erikgrinaker** [comment]
I could also be convinced to set this to 2s. Wdyt @miretskiy?

**Comment by erikgrinaker** [comment]
Getting a bunch of test failures here because `kv.rangefeed.closed_timestamp_refresh_interval` can't be set from tenants. This makes sense, but the same call sites successfully set `kv.closed_timestamp.side_transport_interval` from tenants, which doesn't make sense and is misleading. I'm going to clean this up separately.

**Comment by erikgrinaker** [comment]
Decided to bump this to 3 seconds instead of 1 second, considering the changefeed checkpoint default is 30 seconds.

**Review by miretskiy — APPROVED** [review]

**Review by aliher1911 — APPROVED** [review]

**Pull request merged**
