### PR TITLE
sql: wip: add partial indexes

### PR DESCRIPTION
**Pull request by jordanlewis**
Based on #45157.

This commit adds part of the optimizer and execution support for partial
indexes.

Specifically, backfills, inserts, deletes, upserts, and updates now
only add or remove entries from a partial index if the row they're
operating over should be contained in that partial index.

There's at least two bugs right now:

1. updates always add and remove entries from partial indexes, even when
   they shouldn't
2. ditto for upserts

The glaring missing piece is that the optimizer is blind to the fact
that an index is partial on the selection side, which will manifest as
incorrect results for scans in the presence of partial indexes.

### CODE REVIEW

**Comment by bobvawter** [comment]
[CLA assistant check](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=45555) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=45555) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.crdb.dev/check/cockroachdb/cockroach?pullRequest=45555) it.</sub>

**Comment by jordanlewis** [comment]
Hey all, this was my partial index work in progress. I'm going to hand it off to Marcus. I rebased it, and I think the comments in the PR are pretty much up to date - there's 2 missing execution pieces, and then a major missing piece in the optimizer of deducing when a partial index can be used. I think the second commit in this PR was a beginning stab at that, but it's very much incomplete.

**Comment by jordanlewis** [comment]
Realistically, this giant PR will need to be split up. Maybe we should talk about how to split off the execution parts from the optimizer parts.

**Comment by mgartner** [comment]
@jordanlewis going to close this now that partial indexes have been implemented. Thanks for putting together—it was a useful guide to follow!

**Comment by jordanlewis** [comment]
Congrats on merging the real thing! 👏 👏

**Pull request closed without merging**
