### PR TITLE
sql: support the `GRANT ON SCHEMA` command

### LINKED ISSUE #50879: sql: support the `GRANT .. TO SCHEMA` command
Schemas have an associate permission set, and these permissions can be changed. Fixing this issue should also add testing around different permissions uses with schemas.

### PR DESCRIPTION
**Pull request by rohany**
Fixes #50879.

This commit adds support for the `GRANT ... ON SCHEMA ... TO ...`
command and adds the necessary permissions checks that were missing.
Note that the `USAGE` permission is not implemented and will be done as
a follow up (#53342).

Release note (sql change): Add support for the `GRANT ... ON SCHEMA
command`.

### CODE REVIEW

**Review by solongordon — CHANGES_REQUESTED** [review]
Generally LGTM. It would be nice if @ajwerner or @lucy-zhang could have a look at the `resolver.go` changes.

Random thought: we have that wildcard GRANT syntax for tables (`GRANT SELECT ON TABLE db.*` TO user`). Do we want to support that for schemas too? It's kind of weird and non-standard so I think it's ok if the answer is no.

> Reviewed 7 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53344#-:-MFWv9Wl-F6IMg36P9y6:b-hfvmr8)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @lucy-zhang, @rohany, and @solongordon)

___
*[pkg/sql/resolver.go, line 308 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53344#-MFWtsW3EZh2bkBmswt-:-MFWtsW3EZh2bkBmswt0:bo6t8zv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0c87b20894cb82d2fc45d9f4b7899ceb2ab24e0/pkg/sql/resolver.go#L308)):*
> ```Go
> 		}
> 
> 		if len(descs) == 0 {
> ```

How can `descs` be empty here? We just iterated over a non-empty `Databases` slice and appended a descriptor for each. Doesn't hurt anything I guess but I was confused by it. I think this applies below as well.
___
*[pkg/sql/logictest/testdata/logic_test/schema, line 246 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53344#-MFWut10-n-IPsIyLkR-:-MFWut10-n-IPsIyLkR0:bceg4fx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0c87b20894cb82d2fc45d9f4b7899ceb2ab24e0/pkg/sql/logictest/testdata/logic_test/schema#L246)):*
> ```
> 
> # Test privilege interactions with schemas.
> subtest privileges
> ```

Could you test REVOKE FROM SCHEMA as well?

**Comment by rohany** [comment]
> Random thought: we have that wildcard GRANT syntax for tables (GRANT SELECT ON TABLE db.* TO user`). Do we want to support that for schemas too? It's kind of weird and non-standard so I think it's ok if the answer is no.

No, I don't think so. There are some postgres extensions for this that we should adopt instead (like grant.. on all tables in schema`)

**Review by rohany — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53344)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @lucy-zhang, and @solongordon)

___
*[pkg/sql/resolver.go, line 308 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53344#-MFWtsW3EZh2bkBmswt-:-MFWzOrl5OXjJvZBmAjz:b-pq2tlz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0c87b20894cb82d2fc45d9f4b7899ceb2ab24e0/pkg/sql/resolver.go#L308)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

How can `descs` be empty here? We just iterated over a non-empty `Databases` slice and appended a descriptor for each. Doesn't hurt anything I guess but I was confused by it. I think this applies below as well.
</blockquote></details>

Not sure, I was just cargo culting from the other cases. Removed
___
*[pkg/sql/logictest/testdata/logic_test/schema, line 246 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53344#-MFWut10-n-IPsIyLkR-:-MFWzS7B0Uu6pPkvlqWv:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/c0c87b20894cb82d2fc45d9f4b7899ceb2ab24e0/pkg/sql/logictest/testdata/logic_test/schema#L246)):*
<details><summary><i>Previously, solongordon (Solon) wrote…</i></summary><blockquote>

Could you test REVOKE FROM SCHEMA as well?
</blockquote></details>

Done

**Review by solongordon — APPROVED** [review]
That sounds right to me, thanks.

> Reviewed 1 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53344#-:-MFX-YqA-MJr-j1FwBOJ:b7i23fk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @lucy-zhang, and @solongordon)

**Review by ajwerner — CHANGES_REQUESTED** [review]
We should add docs to clarify what `GRANT ... ON <db>.*` means now.

@ericharmeling is this your domain?

> Reviewed 1 of 16 files at r1, 4 of 8 files at r2, 1 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53344#-:-MFXqJFuCs1pVx7xDxAi:b1dh8au)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @lucy-zhang, and @rohany)

___
*[pkg/sql/logictest/testdata/logic_test/grant_database, line 104 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/53344#-MFXrrLn7GqLkT52VIzU:-MFXrrLn7GqLkT52VIzV:b-yyf9ls) ([raw file](https://github.com/cockroachdb/cockroach/blob/c29cd1f00bc782aa9701b1b81174f4f3769c0302/pkg/sql/logictest/testdata/logic_test/grant_database#L104)):*
> ```
> SHOW GRANTS ON DATABASE a
> ----
> a  crdb_internal       admin      ALL
> ```

I'm not clear on what part of this PR changed this set of privileges

**Review by ajwerner — COMMENTED** [review]
err didn't mean to block, just want to see how this plays into the information schema better

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53344#-:-MFXrwvV3fEZGjs_0Zzo:b-6b1lno)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @lucy-zhang, and @rohany)

**Comment by rohany** [comment]
Yeah, grant * really means grant on all tables.

Those tests changed because I adjusted what privileges schemas are allowed to have — the entries removed correspond to privileges no longer allowed on schemas

**Review by ajwerner — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53344#-:-MFXv6l79SxrXiHHiBse:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @lucy-zhang and @rohany)

**Review by thoszhang — APPROVED** [review]
Oops, I started with #53358 and looked at it all at once without noticing that this was the parent.

> Reviewed 9 of 16 files at r1, 8 of 8 files at r2, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53344#-:-MFYD5kr1yol43all05t:bocp581)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rohany)

**Comment by rohany** [comment]
TFTRs!

bors r+

**Pull request merged**
