### PR TITLE
changefeedccl: add roachtesting for network metrics

### PR DESCRIPTION
**Pull request by asg0451**
Add a roachtest helper that checks that the new
cdc network metrics are being emitted. For now it
simply checks that they are > 0.

Part of: #130097

Release note: None

### CODE REVIEW

**Review by rharding6373 — COMMENTED** [review]
Nice verifier! I have only one concern.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130522#-:-O6ax7a29OfkBRX3u2qm:b-l7w2ia)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @asg0451, @DarrylWong, and @renatolabs)

___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1659 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130522#-O6avG_kEeuA4vSHCqvK:-O6avG_kEeuA4vSHCqvL:b-zkp2g) ([raw file](https://github.com/cockroachdb/cockroach/blob/793e2c7ff7bccc0b300298979853fe311eb268bf/pkg/cmd/roachtest/tests/cdc.go#L1659)):*
> ```Go
> 				steadyLatency:      5 * time.Minute,
> 			})
> 			ct.runMetricsVerifier(verifyChangefeedBytesInOutMetricsPresent("changefeed_network_bytes_in", "changefeed_network_bytes_out"))
> ```

What do you think about moving this after `ct.waitForWorkload()`. Although the changefeed has a job id at this point, it's not guaranteed that it has been scheduled, planned, and is processing events even with the 5s grace period as part of `runMetricsVerifier`. It will likely be less flaky if called at the end of the test, but that depends on if we're reading the metrics live or if we can get historical metrics.

Alternatively, could use `testutils.SucceedsSoon` to provide a longer grace period to `runMetricsVerifier`
___
*[`pkg/cmd/roachtest/tests/cdc.go` line 3712 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130522#-O6aupnN2nOjw68caBYu:-O6aupnN2nOjw68caBYv:bvc57qo) ([raw file](https://github.com/cockroachdb/cockroach/blob/793e2c7ff7bccc0b300298979853fe311eb268bf/pkg/cmd/roachtest/tests/cdc.go#L3712)):*
> ```Go
> }
> 
> func verifyChangefeedBytesInOutMetricsPresent(
> ```

nit: this function that checks metrics seems agnostic to bytes in/out. Might be better named something like verifyMetricNonZero.

**Review by asg0451 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130522)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @DarrylWong, @renatolabs, and @rharding6373)

___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1659 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130522#-O6avG_kEeuA4vSHCqvK:-O6b0f2B7Fj95bzioSJg:b-9d4ef3) ([raw file](https://github.com/cockroachdb/cockroach/blob/793e2c7ff7bccc0b300298979853fe311eb268bf/pkg/cmd/roachtest/tests/cdc.go#L1659)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

What do you think about moving this after `ct.waitForWorkload()`. Although the changefeed has a job id at this point, it's not guaranteed that it has been scheduled, planned, and is processing events even with the 5s grace period as part of `runMetricsVerifier`. It will likely be less flaky if called at the end of the test, but that depends on if we're reading the metrics live or if we can get historical metrics.

Alternatively, could use `testutils.SucceedsSoon` to provide a longer grace period to `runMetricsVerifier`
</blockquote></details>

Fixed. The way i had it before was more convenient for testing it but this should work too and as you say be less flaky.

**Review by rharding6373 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130522#-:-O6b3HB30CX_lO76YODt:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @DarrylWong and @renatolabs)

**Comment by asg0451** [comment]
bors r=rharding6373

**Pull request merged**
