### PR TITLE
ui,metric,server: fix custom chart to include histogram metrics

### LINKED ISSUE #136939: ui: custom chart metrics dropdown doesn't have histogram percentile metrics
A recent change to the custom chart component, https://github.com/cockroachdb/cockroach/pull/135705, changed how it populated the metric names dropdown. As a result, computed histogram metrics (`<name>-p50`, `<name>-p95`, `<name>-p99`, etc.) stopped appearing. 

to fix, the recordedNames field of the `admin/metricmetadata` response should include computed histogram metrics.

Jira issue: CRDB-45307

### PR DESCRIPTION
**Pull request by kyle-a-wong**
PR https://github.com/cockroachdb/cockroach/pull/135705 made changes to the `admin/metricmetadata` api to include tsdb recorded names and custom charts to be powered by this api instead of `_status/nodes_ui`. This introduced a bug where computed histogram metrics stopped appearing in custom charts. This is because these metrics are computed at record time and are not metrics that exist in the metrics registries.

Now, `admin/metricmetadata` recorded names should include all computed histogram metrics.

Benchmarks:
```
building benchmark binaries for 87e0d85: ui,metric,server: fix custom chart to include hist [bazel=true] 1/1 -

  pkg=1/1 iter=10/10 cockroachdb/cockroach/pkg/server/status |

name                   old time/op    new time/op    delta
ExtractValueAllocs-12    8.19µs ± 2%    8.09µs ± 0%  -1.17%  (p=0.000 n=10+8)

name                   old alloc/op   new alloc/op   delta
ExtractValueAllocs-12    17.3kB ± 0%    17.3kB ± 0%    ~     (all equal)

name                   old allocs/op  new allocs/op  delta
ExtractValueAllocs-12       566 ± 0%       566 ± 0%    ~     (all equal)
```

Fixes: https://github.com/cockroachdb/cockroach/issues/136939
Epic: None
Release note: None

### CODE REVIEW

**Review by dhartunian — COMMENTED** [review]
Can you file a bug for this and link just to track the issue.
Also, add backport tag for release-23.1

I apprciate the refactor but I think the approach here should be reconsidered because we need to backport a fix to `release-23.1`. 

Can we have a targeted fix for easy backport that doesn't touch `recorder.go`? That code runs on every metrics persistence loop so it's sensitive to both new bugs being introduced and performance regressions. I ran the `BenchmarkExtractValueAllocs` benchmark and saw a huge jump in allocations and cpu time.

If you want to keep the refactor on `master` it will need some more iteration to reduce impact.

> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136900#-:-ODSX6k39QbnQjKR5vjI:b-1oe173)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aa-joshi, @angles-n-daemons, and @arjunmahishi)

**Review by kyle-a-wong — COMMENTED** [review]
Yeah I can make a ticket and link, but why backport to release-23.1?  The bug that this is fixing (introduced in the PR in the commit message) is only in master. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136900#-:-ODSbqsK0XkoQS1sYL7o:bu5hk5e)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aa-joshi, @angles-n-daemons, and @arjunmahishi)

**Comment by dhartunian** [comment]
Gah sorry I meant 24.3 but was wrong regardless 😳 . I was under the incorrect impression that we backported the `nodes_ui` size improvements which introduced the bug. Please disregard! That said, you can iterate on this and see if you can get the perf impact managed, or reduce scope to just fix the bug. Up to you.

**Review by kyle-a-wong — COMMENTED** [review]
Ahh np. Nice catch on the performance regression, I didnt realize how expensive `WindowedSnapshot()` was. The regression should be fixed now

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136900#-:-ODT9R0H9bnOEx1dN_AF:b-1odcw9)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aa-joshi, @angles-n-daemons, and @arjunmahishi)

**Review by dhartunian — COMMENTED** [review]
> Reviewed 2 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136900)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aa-joshi, @angles-n-daemons, @arjunmahishi, and @kyle-a-wong)

___
*[`pkg/util/metric/metric.go` line 1118 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/136900#-ODvHK7w7Mr8_OnzPlyj:-ODvHK7w7Mr8_OnzPlyk:b-ph9tyh) ([raw file](https://github.com/cockroachdb/cockroach/blob/23c27faa9bb03ad394747a621e19dcbbc8975fec/pkg/util/metric/metric.go#L1118)):*
> ```Go
> 		IsSummaryMetric: true,
> 		ComputedMetric: func(h HistogramSnapshot) float64 {
> 			return h.ValueAtQuantile(90)
> ```

change 90 to 50. The fact that there's no test failing for this signals that there's a missing test.

**Review by kyle-a-wong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136900)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aa-joshi, @angles-n-daemons, @arjunmahishi, and @dhartunian)

___
*[`pkg/util/metric/metric.go` line 1118 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/136900#-ODvHK7w7Mr8_OnzPlyj:-ODwIkRq9NsReyvpkeE8:b-3h3wg6) ([raw file](https://github.com/cockroachdb/cockroach/blob/23c27faa9bb03ad394747a621e19dcbbc8975fec/pkg/util/metric/metric.go#L1118)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

change 90 to 50. The fact that there's no test failing for this signals that there's a missing test.
</blockquote></details>

Oh wow...nice catch. Added test coverage for this

**Review by dhartunian — APPROVED** [review]
:lgtm: 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/136900#-:-ODx8T2oCKCLMeJiZib_:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @aa-joshi, @angles-n-daemons, and @arjunmahishi)

**Comment by kyle-a-wong** [comment]
Tftr 

bors r+

**Comment by kyle-a-wong** [comment]
Bors r-

**Comment by kyle-a-wong** [comment]
Bors r+

**Pull request merged**
