### PR TITLE
ui: Add Segment Analytics to Admin UI

### PR DESCRIPTION
**Pull request by mrtracy**
Adds the ability for the Admin UI to send anonymous page-tracking
analytics to Segment. This is currently *NOT* enabled; we will add a
mechanism to enable it only if the user has not opted out of data
collection.

+ Adds 'analytics.ts' which abstracts away analytics calls to segment in
a way that is easily usable by the rest of the Admin UI.
+ Added tests for AnalyticsSync object.
+ Track a 'page' event whenever the user accesses a new URL path by
attaching a listener to the `history` object used by the Admin UI.
+ Fixed a small issue in the Routes table (added a leading slash to one
route to prevent an unnecessary redirect.

### CODE REVIEW

**Comment by dianasaur323** [comment]
Awesome, awesome. Thank you! Regarding enabling and disabling, we probably want the user experience to match that of turning off general diagnostic reporting. I remember someone mentioning that there is some risk to adding another setting to the cluster setting table, so the lowest risk approach might just be to enable or turn off all diagnostics based on the cluster setting. Also, we want to make sure to document whatever approach you choose.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17937#-:-KsZFgt48Apr-eTi2Bbt:b-k615y7)*

**Comment by dianasaur323** [comment]
Matt, I linked this up into Mixpanel, and was hoping you could make a small edit. Currently, all the pages show up as a "loaded page" event, and I'm able to slice and dice, but it would be nice if we could change how those page views are interpreted by tracking named pages in Mixpanel (option 3) in the below image. Could we swap that over, and also create events for the button clicks? Everything looks to be working as expected, so let's finish this feature out.

https://segment.com/docs/destinations/mixpanel/



---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17937#-:-KsikK_2vKUD3XmqDmBb:b-x6u9m4)*

**Comment by dianasaur323** [comment]
I'm sorry - last follow-up. It also appears that it doesn't work on Chrome, but does work on Safari. Perhaps it's some odd caching issue...

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17937#-:-Ksim8QZQlReREbEdJHm:b-r9qxri)*

**Comment by dianasaur323** [comment]
Ah!! Last note. So sorry for publishing so many times. Could we add the cockroach version as a trait? That way we can figure out which events are coming from which version. Finally, I realized that both Chrome and Safari work - it's just that events only get sent to segment after I close out of the tab.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17937#-:-Ksisv-qnHK_8QNGiAXH:btvwk5k)*

**Comment by dianasaur323** [comment]
Sorry... =.= Let's also add enterprise or not as a trait. It might be nice to also see what browser they are using. Finally, is there any way to pass how long the cluster has been up as a trait?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17937#-:-KsitKPETnFr17_-GoDN:b7e4208)*

**Comment by BramGruneir** [comment]
:lgtm: with just a few nits.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/ui/package.json, line 34 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17937#-Ksiqj-K7O5A58J5SM2F:-Ksiqj-MeTeY6pcSv-QA:b-wamuf9) ([raw file](https://github.com/cockroachdb/cockroach/blob/0302a189e6f56e7bc93b5c30d130fd8f7af0e1d7/pkg/ui/package.json#L34)):*
> ```JSON
>     "@types/react-sticky": "^5.0.1",
>     "@types/redux-thunk": "^2.1.0",
>     "@types/sinon": "2.1.0",
> ```

This downgrade of sinon is expected?

---

*[pkg/ui/src/index.tsx, line 27 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17937#-Ksir18egenj4fRlFohG:-Ksir18egenj4fRlFohH:bk5msvi) ([raw file](https://github.com/cockroachdb/cockroach/blob/0302a189e6f56e7bc93b5c30d130fd8f7af0e1d7/pkg/ui/src/index.tsx#L27)):*
> ```XML
> import "src/redux/analytics";
> import { store, history } from "src/redux/state";
> ```

While you're messing around in here, care to split this into external and internal import sections and alphabetize them? 

---

*[pkg/ui/src/redux/analytics.spec.ts, line 3 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17937#-Ksito2B9F7BUmfaKjv8:-Ksito2Db0yl4ZaPjuWS:b-38y0lv) ([raw file](https://github.com/cockroachdb/cockroach/blob/0302a189e6f56e7bc93b5c30d130fd8f7af0e1d7/pkg/ui/src/redux/analytics.spec.ts#L3)):*
> ```XML
> import { assert } from "chai";
> import * as sinon from "sinon";
> ```

Split this into two section, other import and our import and alphabetize please.

---

*[pkg/ui/src/redux/analytics.ts, line 76 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17937#-KsisY0jK3fswFAH3FM_:-KsisY0jK3fswFAH3FMa:bwpq885) ([raw file](https://github.com/cockroachdb/cockroach/blob/0302a189e6f56e7bc93b5c30d130fd8f7af0e1d7/pkg/ui/src/redux/analytics.ts#L76)):*
> ```XML
>         const id = this.getCluster();
>         if (id === null) {
>             this.queuedPages.push(location);
> ```

How about redacting now, instead of waiting until the cluster id is present?

Not sure if that's better.  Just a slightly different approach.

---

*[pkg/ui/src/redux/analytics.ts, line 98 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17937#-KsisLPwqqMmw9AY7xRV:-KsisLPxc6sNs4UD7SZv:b-pewpr4) ([raw file](https://github.com/cockroachdb/cockroach/blob/0302a189e6f56e7bc93b5c30d130fd8f7af0e1d7/pkg/ui/src/redux/analytics.ts#L98)):*
> ```XML
>         // Do nothing if cluster ID has not been loaded.
>         const cluster = state.cachedData.cluster;
>         if (!cluster || !cluster.data) {
> ```

`_.isNil(cluster.data)`

---

*[pkg/ui/src/redux/analytics.ts, line 132 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17937#-KsitLIH9zAjFpMPFxXX:-KsitLIId2vYYQLtwPih:bgjhel3) ([raw file](https://github.com/cockroachdb/cockroach/blob/0302a189e6f56e7bc93b5c30d130fd8f7af0e1d7/pkg/ui/src/redux/analytics.ts#L132)):*
> ```XML
>  * List of current redactions needed for the Admin UI.
>  */
> const defaultRedactions = [
> ```

Nit: Move this to the top, since it's the most important part of this file.  

---

*[pkg/ui/src/redux/analytics.ts, line 134 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17937#-Ksiu32msPsonwuhYkhd:-Ksiu32msPsonwuhYkhe:b-h4e1n6) ([raw file](https://github.com/cockroachdb/cockroach/blob/0302a189e6f56e7bc93b5c30d130fd8f7af0e1d7/pkg/ui/src/redux/analytics.ts#L134)):*
> ```XML
> const defaultRedactions = [
>     // When viewing a specific database, the database name and table are part of
>     // the URL path.
> ```

Add a note about adding a appropriate tests as well for all entries.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17937#-:-KsithaDJ4WlMI1-Fgzg:bx7jpz8)*

**Comment by mrtracy** [comment]
@dianasaur323 We talked in person, I will address some of these in the subsequent PRs.

**Comment by mrtracy** [comment]
Review status: 3 of 8 files reviewed at latest revision, 7 unresolved discussions.

---

*[pkg/ui/package.json, line 34 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17937#-Ksiqj-K7O5A58J5SM2F:-KsjUhd2Bd1Qd2DJ4BFG:b-mk2y6g) ([raw file](https://github.com/cockroachdb/cockroach/blob/0302a189e6f56e7bc93b5c30d130fd8f7af0e1d7/pkg/ui/package.json#L34)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

This downgrade of sinon is expected?
</blockquote></details>

Yes, I was working with sinon and discovered that our types were mismatched with the version of sinon we are using (2.1.0).

I don't want to upgrade sinon to keep this PR focused, but I did decide to match the version of types with our version of sinon.

---

*[pkg/ui/src/index.tsx, line 27 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17937#-Ksir18egenj4fRlFohG:-KsjQi29nv76bYGNnDkH:bq07vh0) ([raw file](https://github.com/cockroachdb/cockroach/blob/0302a189e6f56e7bc93b5c30d130fd8f7af0e1d7/pkg/ui/src/index.tsx#L27)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

While you're messing around in here, care to split this into external and internal import sections and alphabetize them? 
</blockquote></details>

We're really close to code 1.1 freeze, and this overdue refactoring work can be done after that deadline.  I rather keep this PR focused on whats being changed; I feel iffy enough about that sinon types version change, but at least I'm directly using that library in this PR.

---

*[pkg/ui/src/redux/analytics.spec.ts, line 3 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17937#-Ksito2B9F7BUmfaKjv8:-KsjR67ZYTogfRa-VToD:b-cuekry) ([raw file](https://github.com/cockroachdb/cockroach/blob/0302a189e6f56e7bc93b5c30d130fd8f7af0e1d7/pkg/ui/src/redux/analytics.spec.ts#L3)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Split this into two section, other import and our import and alphabetize please.
</blockquote></details>

It's already split into three sections, "test libraries", "external", "internal".  The internal section was not alphabetized correctly, done.

---

*[pkg/ui/src/redux/analytics.ts, line 76 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17937#-KsisY0jK3fswFAH3FM_:-KsjRIV0E6K7WV4FX6im:b3249ez) ([raw file](https://github.com/cockroachdb/cockroach/blob/0302a189e6f56e7bc93b5c30d130fd8f7af0e1d7/pkg/ui/src/redux/analytics.ts#L76)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

How about redacting now, instead of waiting until the cluster id is present?

Not sure if that's better.  Just a slightly different approach.

</blockquote></details>

All pages go through "pushPage", whether they are queued or not.  pushPage is the correct place to redact.

---

*[pkg/ui/src/redux/analytics.ts, line 98 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17937#-KsisLPwqqMmw9AY7xRV:-KsjRo_TQb3Sn9FJO5av:b-m72swg) ([raw file](https://github.com/cockroachdb/cockroach/blob/0302a189e6f56e7bc93b5c30d130fd8f7af0e1d7/pkg/ui/src/redux/analytics.ts#L98)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

`_.isNil(cluster.data)`
</blockquote></details>

That throws an exception if cluster itself is null or undefined.

Additionally, "_.isNil" is only necessary when you must distinguish null and undefined from other falsy states (`0`, `false`, empty string).  It's more succinct than `x !== null && x !== undefined`.  

However, cluster.data is an object, so any defined value will be truthy, and thus `!` is correct and succinct.

---

*[pkg/ui/src/redux/analytics.ts, line 132 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17937#-KsitLIH9zAjFpMPFxXX:-KsjTHLnyamcd9pQ2NCb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0302a189e6f56e7bc93b5c30d130fd8f7af0e1d7/pkg/ui/src/redux/analytics.ts#L132)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Nit: Move this to the top, since it's the most important part of this file.  
</blockquote></details>

Done.

---

*[pkg/ui/src/redux/analytics.ts, line 134 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17937#-Ksiu32msPsonwuhYkhd:-KsjTHnAZUjXS2JX4aFd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/0302a189e6f56e7bc93b5c30d130fd8f7af0e1d7/pkg/ui/src/redux/analytics.ts#L134)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Add a note about adding a appropriate tests as well for all entries.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17937)*

**Comment by BramGruneir** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/ui/src/redux/analytics.ts, line 98 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17937#-KsisLPwqqMmw9AY7xRV:-Ksj_Oa0LslYz2sz-8l9:bt67j03) ([raw file](https://github.com/cockroachdb/cockroach/blob/0302a189e6f56e7bc93b5c30d130fd8f7af0e1d7/pkg/ui/src/redux/analytics.ts#L98)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

That throws an exception if cluster itself is null or undefined.

Additionally, "_.isNil" is only necessary when you must distinguish null and undefined from other falsy states (`0`, `false`, empty string).  It's more succinct than `x !== null && x !== undefined`.  

However, cluster.data is an object, so any defined value will be truthy, and thus `!` is correct and succinct.
</blockquote></details>

I thought it was supposed to walk the object for you.  It doesn't. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17937#-:-Ksj_vlZuR8Gq8YFrKI8:bnfp4nl)*

**Comment by mrtracy** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/ui/src/redux/analytics.ts, line 98 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17937#-KsisLPwqqMmw9AY7xRV:-KsjdOiXF3J9xdgZkn9p:b-rfkzxj) ([raw file](https://github.com/cockroachdb/cockroach/blob/0302a189e6f56e7bc93b5c30d130fd8f7af0e1d7/pkg/ui/src/redux/analytics.ts#L98)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

I thought it was supposed to walk the object for you.  It doesn't. 
</blockquote></details>

If the method accepts a path *string*, such as `_.get()`,  that allows deep checking; however, `isNil` does not accept a path string, it just accepts an object.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17937)*

**Comment by a-robinson** [comment]
@mrtracy @BramGruneir this seems to have broken `proxy.js` for me, and I'm wondering if it's only broken on my machine (and thus I just need to update something) or if it's broken for you guys as well. `proxy.js` runs into this error for me now:

```
ERROR in ./~/browserify-cipher/browser.js
Module not found: Error: Can't resolve 'browserify-aes/browser' in '/Users/alex/go/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/browserify-cipher'
 @ ./~/browserify-cipher/browser.js 2:10-43
 @ ./~/crypto-browserify/index.js
 @ ./~/crypto-token/lib/index.js
 @ ./~/analytics-node/index.js
 @ ./src/redux/analytics.ts
 @ ./src/index.tsx
```

**Comment by mrtracy** [comment]
proxy.js is still working on my machine; you should try running `make` in the UI directory, i'm not sure proxy.js runs yarn automatically.

**Comment by 0xbaadf00d** [comment]
It is an admin / stats panel, not a public website who need to collect data and Integrate marketing and analytics stack.

If this feature is usefull for some peoples, why use this "hardcoded" provider, why not just allow injection of custom html/js tag taken from the configuration ?

**Comment by couchand** [comment]
Hi @0xbaadf00d, I'd like to clarify the purpose of this change. The Segment integration provides anonymized analytics to Cockroach Labs to help us understand what features are useful and how to prioritize our development efforts. It plays the same role as that of our query statistics and other [diagnostic reporting] (https://www.cockroachlabs.com/docs/stable/diagnostics-reporting.html).

As described in the documentation I linked to, you can turn this feature off if it's unacceptable to send this anonymous usage information to us.

**Comment by 0xbaadf00d** [comment]
Hi @couchand, thanks for your answer.

**Pull request merged**
