### PR TITLE
kv,client,storage: rationalize TxnCoordSender/client.Txn redundant states

### PR DESCRIPTION
**Pull request by andreimatei**
client.Txn and TCS try to maintain a bunch of logically-redundant state
about whether a transaction is "writing" - essentially whether an
EndTransaction needs to be sent to cleanup up the TCS heartbeat loop and
the server's txn record.
The logic that both parties used for this was complex (e.g. it involved
updates in both Txn and TCS both on the outgoing path and on the
returning path of a batch) and not in sync - sometimes the TCS would
consider the txn as "writing" and the client.Txn wouldn't (e.g. in case
the first writing batch got an ambiguous error).

This patch simplifies things: the idea is that, if a BeginTxn has been
sent, an EndTransaction needs to be sent, period. The client.Txn thus
only keeps track of whether a BeginTxn was sent (except for a 1PC
batch), and it takes charge of starting the TCS' heartbeat loop (by
instructing it explicitly directly to start it before the BeginTxn is
sent). The TCS is no longer burdened with maintaining any state about
whether there is a txn record or not.

As a byproduct, the proto Transaction.Writing flag, which used to have
an unclear meaning, becomes straight forward: if set, the server needs
to check batches against the abort cache. The client is the only one
setting it, the server is the only one checking it. It used to be used
for different purposeses by both the client and server.

Release note: none

### CODE REVIEW

**Comment by andreimatei** [comment]
I think you're right; I've added back the server-side code setting that flag gated by a new version not being active.
PTAL

---

Review status: 17 of 26 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/internal/client/txn.go, line 658 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25541#-LCeXTzk6tW6BtAcy-hu:-LCepnqgCcKJZq9yC1CW:bbp8jx0) ([raw file](https://github.com/cockroachdb/cockroach/blob/033c6e8552856f97299c66575ec337d8abb408eb/pkg/internal/client/txn.go#L658)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Should we just reuse the `txnState` enum for this? If we do need a new enum, we should give them all a common prefix - `writing` is a pretty generic name to use at package scope. And a value of `writing` for `readOnlyRes` is an odd name. 
</blockquote></details>

ok, shuffled things around and this is gone

---

*[pkg/sql/sem/tree/stmt.go, line 652 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25541#-LCeRZqHEJefBCPQ4-pK:-LCezZDNA-_9Pji9AGoh:bd05s7h) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f4e9b215f9a3284a39d507b3b0ddd310a0f87da/pkg/sql/sem/tree/stmt.go#L652)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Removing this from `ShowCreateTable` without also removing it from `ShowCreateView` and other statements seems like a bad idea. @nvanbenschoten should weigh in on why the show statements were exempted here. 
</blockquote></details>

ok, added a commit removing most of these

---

*[pkg/storage/batcheval/cmd_begin_transaction.go, line 134 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25541#-LCeS-zt5baJ3U1ZUMIr:-LCevUKk1s406PGiddVP:b31m5v9) ([raw file](https://github.com/cockroachdb/cockroach/blob/6f4e9b215f9a3284a39d507b3b0ddd310a0f87da/pkg/storage/batcheval/cmd_begin_transaction.go#L134)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I don't think it's safe to remove this without a cluster version check. Won't 2.0 nodes rely on this flag being set in BeginTransaction?
</blockquote></details>

put it back behind a version check

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25541#-:-LCeli1N-wr10oFceQw9:b-k02nr0)*

**Comment by andreimatei** [comment]
Review status: 22 of 26 files reviewed at latest revision, 13 unresolved discussions.

---

*[pkg/internal/client/sender.go, line 112 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25541#-LCjHVkrBIMBZw93ppG8:-LCjLSmRDMqR4jN0jy4h:b-knnoqy) ([raw file](https://github.com/cockroachdb/cockroach/blob/af47ad8d928f98ed7c12c9dfe57866ce53bdcfd7/pkg/internal/client/sender.go#L112)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'd keep this as is and add a second `TxnSenderStruct` type (maybe with a different name). The `<InterfaceName>Func` pattern is very common.
</blockquote></details>

renamed to `TxnSenderAdapter`

---

*[pkg/internal/client/txn.go, line 72 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25541#-LCj72Sb34biTGMuREhA:-LCjOwFXERvW8xYCE39y:bhl8arg) ([raw file](https://github.com/cockroachdb/cockroach/blob/af47ad8d928f98ed7c12c9dfe57866ce53bdcfd7/pkg/internal/client/txn.go#L72)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Did you look into merging this status into the `txnState` enum?
</blockquote></details>

I looked now. Unfortunately this sucker doesn't match with any of the states. It means "has any request ever been sent". It's not a very important field... I'll leave it for another cleanup :)

---

*[pkg/internal/client/txn.go, line 952 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25541#-LCj8cAX-vts8f7lHMl0:-LCjM-Gw91DqXVvswLby:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/af47ad8d928f98ed7c12c9dfe57866ce53bdcfd7/pkg/internal/client/txn.go#L952)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`s/we're/we've/`
</blockquote></details>

Done.

---

*[pkg/internal/client/txn.go, line 953 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25541#-LCj8nai0xl9kgkFK5AG:-LCjM-Z49mJIVJAO1eJt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/af47ad8d928f98ed7c12c9dfe57866ce53bdcfd7/pkg/internal/client/txn.go#L953)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: flip this around so that it's easier to read and compare to the previous line:

```
needEndTxn := haveTxnWrite || (txn.mu.state != txnReadOnly)
```
</blockquote></details>

Done.

---

*[pkg/kv/dist_sender_server_test.go, line 2529 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25541#-LCjDF-BCraYVOYeVkTb:-LCjMD5G4hde1SJXG8Vy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/af47ad8d928f98ed7c12c9dfe57866ce53bdcfd7/pkg/kv/dist_sender_server_test.go#L2529)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.

---

*[pkg/kv/txn_coord_sender.go, line 979 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25541#-LCjG8dm3VsJUq3pHSNy:-LCjMLkl0kMb7oDfVxE-:b-u8774y) ([raw file](https://github.com/cockroachdb/cockroach/blob/af47ad8d928f98ed7c12c9dfe57866ce53bdcfd7/pkg/kv/txn_coord_sender.go#L979)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why do we suddenly need this?
</blockquote></details>

I think we always needed it. I forgot why I added it here exactly; it could be that I just noticed some error while debugging.
In any case, luckily ctx.Done() is going away from here.

---

*[pkg/roachpb/batch.go, line 409 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25541#-LCjGeWG0FK9dbdrAUpY:-LCjNIupCGnixhKLuBO_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/af47ad8d928f98ed7c12c9dfe57866ce53bdcfd7/pkg/roachpb/batch.go#L409)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Will an EndTransactionRequest ever have an `EndKey`?
</blockquote></details>

Done.

---

*[pkg/roachpb/data.proto, line 338 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25541#-LCjGvag3oYnGQ8pGwnv:-LCjOAyUAcT1l-elkpfb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/af47ad8d928f98ed7c12c9dfe57866ce53bdcfd7/pkg/roachpb/data.proto#L338)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This first sentence is no longer accurate.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25541)*

**Comment by nvanbenschoten** [comment]
Review status: 12 of 26 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/internal/client/sender.go, line 112 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25541#-LCjHVkrBIMBZw93ppG8:-LCjl8CH5n3uAvfag-dz:b-cda72s) ([raw file](https://github.com/cockroachdb/cockroach/blob/af47ad8d928f98ed7c12c9dfe57866ce53bdcfd7/pkg/internal/client/sender.go#L112)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

renamed to `TxnSenderAdapter`
</blockquote></details>

Sorry, I also meant that you should leave `TxnSenderFunc` alone and have the call to `StartTracking` panic (or return nil, I don't have a strong opinion).

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25541)*

**Comment by andreimatei** [comment]
I've hit a snag here, surfaced by TestClientRunConcurrentTransaction:

- A txn send a `BeginTxn`
- While the `BeginTxn` is in flight, the txn gets aborted by a pusher (say the txn managed to concurrently lay down an intent and then a pusher ran into that intent and pushed the txn like butter cause there's no transaction record still)
- With the `BeginTxn` still in flight, another concurrent request from the txn figures out that the txn has been aborted (by hitting the `AbortSpan`) and returns a `TransactionAbortedError` (which is retriable).
- Upon seeing the `TransactionAbortedError`, the coordinator switches to a new txn proto and sends an `EndTransaction` for the old one.
- The `EndTransaction` executes and populates the timestamp cache. 
- The `BeginTxn` finally executes and hits the timestamp cache, so it looks like a replay. It generates a `TransactionReplayError`.
- When the client receives the `TransactionReplayError`, it moves the `client.Txn` object to the `TxnError` state.
- Now, the txn can't do any more requests because it's in the `TxnError` state. Even though it should be allowed to perform more requests, as it would like to retry the txn.

Everything here was true before this PR too, up until the move to the `TxnError` state which starts rejecting everything. I need to figure out what to do - maybe it's as simple as not moving to the `TxnError` state if the request was part of a different txn id / epoch.

One question I have for the group is: is it surprising that the `EndTxn` and `BeginTxn` get reordered relatively reliably (the `EndTxn` is sent after the `Begin`, but executes first)? Would the command queue order the two if the `Begin` made it to the command queue)?

---

Review status: 8 of 31 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25541#-:-LCpZYEXAp35je-HxXuy:bw9vfnq)*

**Comment by bdarnell** [comment]
> I need to figure out what to do - maybe it's as simple as not moving to the TxnError state if the request was part of a different txn id / epoch.

I think TransactionReplayError is special and should not move the txn to the TxnError state. We make this an error to guard against BeginTransactions being reordered after a *committing* EndTransaction, but in this case we know that there could not have been a committing ET (with matching epoch) because only this client.Txn could have sent it. Therefore we can safely restart the txn (at a higher timestamp) without going into the error state.

**Comment by andreimatei** [comment]
The problem shown here by the `TransactionReplayError` is more general - any error received by requests that were in flight when the transaction restarts would have the unfortunate effect of moving the txn to the `TxnError` state.
I've added a small commit to the beginning that generally short-circuits the handling of responses for such requests that straddle the restart of the txn. I think that's a sane thing to do.
With that in place, I don't think any special treatment of `TransactionReplayError` is warranted. Tell me if you feel otherwise.

@nvanbenschoten PTAL at the first commit.

---

Review status: 7 of 34 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25541#-:-LDrYuAS7BBy3Ax6w3rY:b-x3ttgp)*

**Comment by andreimatei** [comment]
Added one more commit that I was telling you about @nvanbenschoten for binding the TCS to a txn early. PTAL

---

Review status: 0 of 33 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25541#-:-LDsYyYT6R0-2wYBmpes:bpb3ubo)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/settings/cluster/cockroach_versions.go, line 56 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/25541#-LDvml6N5xRJudPjv5bm:-LDvml6N5xRJudPjv5bn:bikotdk) ([raw file](https://github.com/cockroachdb/cockroach/blob/24f2801a50e0760f54806afe255416de9ee08419/pkg/settings/cluster/cockroach_versions.go#L56)):*
> ```Go
> 	VersionImportFormats
> 	VersionSecondaryLookupJoins
> 	VersionClientsideWritingFlag
> ```

Capitalize `side`

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25541)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/internal/client/db.go, line 205 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/25541#-LDw3t_w-U_28KyadIUw:-LDw3t_w-U_28KyadIUx:bcqqb7m) ([raw file](https://github.com/cockroachdb/cockroach/blob/a912f05c0cf05ba9e1331ca279200da8ed1107e5/pkg/internal/client/db.go#L205)):*
> ```Go
> 	// That's why this method says to not use the Sender for transactional
> 	// requests, plus the fact that if a Sender is used directly, the caller needs
> 	// to be mindful of the need to start a heartbeat loop when writing.
> ```

I'm still a little confused about why anyone would need to use this over `db.factory.WrappedSender()`. Do tests really rely on the intent tracking?

---

*[pkg/internal/client/sender.go, line 112 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25541#-LCjHVkrBIMBZw93ppG8:-LDw4XPg8Jf9f-vDRapD:b-u8jbya) ([raw file](https://github.com/cockroachdb/cockroach/blob/af47ad8d928f98ed7c12c9dfe57866ce53bdcfd7/pkg/internal/client/sender.go#L112)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Sorry, I also meant that you should leave `TxnSenderFunc` alone and have the call to `StartTracking` panic (or return nil, I don't have a strong opinion).
</blockquote></details>

You don't think it's worth having a `TxnSenderFunc` type as well for all the cases where `StarTrackingWrapped` is left as nil?

---

*[pkg/storage/replica.go, line 2949 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/25541#-LDw5x-a85vpqfsIIrbY:-LDw5x-a85vpqfsIIrbZ:b-pworud) ([raw file](https://github.com/cockroachdb/cockroach/blob/a203b6af3f766865e39b26ec0a67b134f3da850a/pkg/storage/replica.go#L2949)):*
> ```Go
> 			log.Fatalf(ctx, "error had a txn but batch is non-transactional. Err txn: %s", txn)
> 		}
> 		if txn != nil && !r.ClusterSettings().Version.IsActive(cluster.VersionClientsideWritingFlag) {
> ```

To confirm, 2.1 binaries will still work properly in all cases if this server-side `Writing` handling is present, right? In other words, you didn't have to make any changes to `replica.go` or `cmd_begin_transaction.go` for correctness, right?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25541)*

**Comment by andreimatei** [comment]
First 3 commits sprucing up tests are other PRs.

---

Review status: 0 of 35 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[pkg/internal/client/db.go, line 205 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/25541#-LDw3t_w-U_28KyadIUw:-LDx96JF4u4ZEDB0RbkV:b-cyh2q1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a912f05c0cf05ba9e1331ca279200da8ed1107e5/pkg/internal/client/db.go#L205)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm still a little confused about why anyone would need to use this over `db.factory.WrappedSender()`. Do tests really rely on the intent tracking?
</blockquote></details>

as we discussed, it's more the wrapping of cross-range requests than the intent handling. Explained in the comment.

So this will stay, but the situation has improved otherwise - an unbound TCS now refuses to handle transactional requests and various tests have been updated in other PRs.

---

*[pkg/internal/client/sender.go, line 112 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25541#-LCjHVkrBIMBZw93ppG8:-LDx9hm_ADFVF_dnIi9n:bf88149) ([raw file](https://github.com/cockroachdb/cockroach/blob/af47ad8d928f98ed7c12c9dfe57866ce53bdcfd7/pkg/internal/client/sender.go#L112)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

You don't think it's worth having a `TxnSenderFunc` type as well for all the cases where `StarTrackingWrapped` is left as nil?
</blockquote></details>

Probably not... I'll leave it as is for the moment.

---

*[pkg/settings/cluster/cockroach_versions.go, line 56 at r14](https://reviewable.io/reviews/cockroachdb/cockroach/25541#-LDvml6N5xRJudPjv5bm:-LDx9mh2-zM755VdfGzJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/24f2801a50e0760f54806afe255416de9ee08419/pkg/settings/cluster/cockroach_versions.go#L56)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Capitalize `side`
</blockquote></details>

Done.

---

*[pkg/storage/replica.go, line 2949 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/25541#-LDw5x-a85vpqfsIIrbY:-LDxDoND6PGd5JsGJ_t9:bm7g47r) ([raw file](https://github.com/cockroachdb/cockroach/blob/a203b6af3f766865e39b26ec0a67b134f3da850a/pkg/storage/replica.go#L2949)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

To confirm, 2.1 binaries will still work properly in all cases if this server-side `Writing` handling is present, right? In other words, you didn't have to make any changes to `replica.go` or `cmd_begin_transaction.go` for correctness, right?
</blockquote></details>

yes, that's correct.
Modulo the change to declare the abort span key as being read by `BeginTxn` that we talked about - 2.0 servers are going to start checking the abort span without that key being declared, but that's only a problem in race builds which enforce that all accessed keys are declared. Conflicting requests are serialized through the command queue because of the transaction key regardless of whether the abort span key is declared or not.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25541#-:-LDxF_AgA51jxC0d6mCm:bnsp56q)*

**Comment by andreimatei** [comment]
I believe I have LGTM's here, right?

---

Review status: 0 of 34 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25541#-:-LEBOd7n9yH7IMwJOEJy:bvf1vgu)*

**Comment by nvanbenschoten** [comment]
Yes, LGTM

**Comment by andreimatei** [comment]
As I was telling Nathan, I've made a change to r11 adding copying of a few fields from a requests's Txn to the TxnCoordSender's copy of the proto, which proved to be necessary. This is to compensate for the effects of the previous cloning of the requests's proto on the first `TxnCoordSender.Send()` call that has now gone away.

---

Review status: 0 of 34 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25541#-:-LECRR7SBR3AGSTss9JV:bkwn1wp)*

**Comment by andreimatei** [comment]
bors r+

---

Review status: 0 of 34 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25541#-:-LEFGfWk8bLOt41VYgCa:b-ydi9ay)*

**Pull request merged**
