### PR TITLE
sql: require super user return status

### LINKED ISSUE #32662: sql: RequireSuperUser() swallows errors
**Describe the problem**

The function `RequiresSuperUser()` returns `err` both to indicate errors in the underlying logic / SQL queries, and to indicate the current user is not a superuser.

Subsequently, callers that which simply to know *whether* the current user is an admin will test the error return and **silently drop it on the floor** if non-nil.

Instead the function should return `(bool, error)` with the boolean indicating the admin status.

### PR DESCRIPTION
**Pull request by Gurio**
Resolves #32662 as discussed with @knz (hopefully correctly)
First commit is taken from https://github.com/cockroachdb/cockroach/pull/38124 which helped to find all the necessary places where code should be changed
I didn’t check if it builds with the last fix-commit, so please don’t review until TeamCity succeeds.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Thanks the end result looks about right.

You're missing a piece though; as-is the code does not compile.

Then after that ensure the PR contains just your commit (instead of appending to the previous author's commit).
I could also recommend squashing the commits into one, there is no need for the intermediate situation which modifies many files to change the return values of RequireSuperUser. 

> Reviewed 3 of 20 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38454#-:-LiMSeGa4lz_A2eElp5l:b-owzrhx)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by Gurio** [comment]
@knz I've updated it and run test locally, should be fine now, lets see what CI says.
two open things:

1. I've included @mgm702 's commit, to give kudos to his work. But as there is a problem with CLA, i will probably squash it into mine.
2. I've updated RFCS/20171220_sql_role_based_access_control.md, according to the current AuthorizationAccessor interface. But I am really unsure if it is the right thing to do, because old RFCs probably should stay as they were. What do you think

**Comment by Gurio** [comment]
Ok build still fails, I’ll take a look

**Comment by knz** [comment]
RFC change is OK.

You can mention the name of the other contributor in the commit message, no need to include the commit itself.

**Comment by Gurio** [comment]
@knz: I think PR is ready. Could you check/merge?

**Review by knz — APPROVED** [review]
> Reviewed 3 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38454)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by knz** [comment]
Thank you for your contribution!

bors r+

**Pull request merged**
