### PR TITLE
sql: bust some allocations in conn_executor

### PR DESCRIPTION
**Pull request by jordanlewis**
Lots of closures = lots of unnecessary allocations. Let's get rid of
these!

Release note: None

### CODE REVIEW

**Comment by jordanlewis** [comment]
Ping!

**Review by andreimatei — CHANGES_REQUESTED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28476#-:-LKyACtm6ewjsKcfqUQT:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/conn_executor_exec.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28476#-LKy9_6LAHhFHXbjGCXa:-LKy9_6LAHhFHXbjGCXb:btgwp69) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b6beecfbd9068e00aa9c7636fb0767e8ff385ae/pkg/sql/conn_executor_exec.go#L111)):*
> ```Go
> }
> 
> func (ex *connExecutor) queryDone(
> ```

this method needs a comment now
___
*[pkg/sql/conn_executor_exec.go, line 143 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28476#-LKy9ksbEIXglRfWEjeH:-LKy9ksbEIXglRfWEjeI:b753zdu) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b6beecfbd9068e00aa9c7636fb0767e8ff385ae/pkg/sql/conn_executor_exec.go#L143)):*
> ```Go
> }
> 
> func (ex *connExecutor) makeErrEventWithCurStmt(err error) (fsm.Event, fsm.EventPayload, error) {
> ```

was this closure really causing an allocation? Do all closure require an allocation?
Cause it was nicer as a closure - now the signature seems nonsensical since there's never an `error` returned

**Review by andreimatei — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28476#-:-LKyAEly4OgjzShD_oWv:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by jordanlewis** [comment]
This rotted and is probably not that important anyway.

**Pull request closed without merging**
