### PR TITLE
sql: remove duplicated code in pgwire decoding

### PR DESCRIPTION
**Pull request by jordanlewis**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13658)

### CODE REVIEW

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/pgwire/types.go, line 733 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13658#-KdD9ni_8-YTp7rtn6LJ:-KdD9ni_8-YTp7rtn6LK:b8ns3yw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b42c63728e950fa6d61c6cdeef0c6fc1e66598a5/pkg/sql/pgwire/types.go#L733)):*
> ```Go
> 			}
> 			return d, nil
> 		case formatBinary:
> ```

this is the kind of thing that makes me apprehensive about this change - this construction is now more fragile.

what about inverting this construct? currently we switch on the oid first, which gives us 1 + len(oids) `default` clauses. If we switched on the format first, we would get 1 + len(formats) `default` clauses without loss of robustness.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13658)*

**Comment by jordanlewis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/pgwire/types.go, line 733 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13658#-KdD9ni_8-YTp7rtn6LJ:-KdDBXG0AXXojCnUscK-:b-w8tetz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b42c63728e950fa6d61c6cdeef0c6fc1e66598a5/pkg/sql/pgwire/types.go#L733)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this is the kind of thing that makes me apprehensive about this change - this construction is now more fragile.

what about inverting this construct? currently we switch on the oid first, which gives us 1 + len(oids) `default` clauses. If we switched on the format first, we would get 1 + len(formats) `default` clauses without loss of robustness.
</blockquote></details>

Meh... the few lines of saved code doesn't warrant that amount of code movement IMO. If you're adamant about this I'll just drop the change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13658)*

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/pgwire/types.go, line 733 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13658#-KdD9ni_8-YTp7rtn6LJ:-KdDC7Vq-PJEjT8fss8s:bb967bq) ([raw file](https://github.com/cockroachdb/cockroach/blob/b42c63728e950fa6d61c6cdeef0c6fc1e66598a5/pkg/sql/pgwire/types.go#L733)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Meh... the few lines of saved code doesn't warrant that amount of code movement IMO. If you're adamant about this I'll just drop the change.
</blockquote></details>

Yep, I prefer the explicitness of the status quo over the suggested change here. If only we had the technology to do exhaustiveness checking.

https://doc.rust-lang.org/book/match.html

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13658)*

**Comment by jordanlewis** [comment]
We have the technology

**Pull request closed without merging**
