### PR TITLE
sql: deflake `TestTrace`

### LINKED ISSUE #98971: sql: TestTrace failed
sql.TestTrace [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9133641?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/9133641?buildTab=artifacts#/) on master @ [53dbb86acb1d48309530181b94838faf937084d3](https://github.com/cockroachdb/cockroach/commits/53dbb86acb1d48309530181b94838faf937084d3):

```
=== RUN   TestTrace
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/b287de7194e17a0386ee1775f0d198ba/logTestTrace3285791219
    test_log_scope.go:79: use -show-logs to present logs inline
=== CONT  TestTrace
    trace_test.go:412: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/b287de7194e17a0386ee1775f0d198ba/logTestTrace3285791219
--- FAIL: TestTrace (5.18s)
=== RUN   TestTrace/ShowTraceFor
    --- FAIL: TestTrace/ShowTraceFor (0.12s)
=== RUN   TestTrace/ShowTraceFor/TracingOn
        --- FAIL: TestTrace/ShowTraceFor/TracingOn (0.07s)
=== RUN   TestTrace/ShowTraceFor/TracingOn/node-1
    trace_test.go:386: expected span: "session recording", got: "pendingLeaseRequest: requesting lease"
    trace_test.go:397: remaining span: "session recording"
    trace_test.go:397: remaining span: "sql query"
    trace_test.go:397: remaining span: "sql txn"
    trace_test.go:397: remaining span: "table reader"
    trace_test.go:397: remaining span: "txn coordinator send"
            --- FAIL: TestTrace/ShowTraceFor/TracingOn/node-1 (0.02s)
```
<p>Parameters: <code>TAGS=bazel,gss</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestTrace.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-25634

### PR DESCRIPTION
**Pull request by erikgrinaker**
This has been seen to flake in CI:

```
=== RUN   TestTrace/ShowTraceForVectorized/TracingOff/node-1
    trace_test.go:386: expected span: "session recording", got: "pendingLeaseRequest: requesting lease"
    trace_test.go:397: remaining span: "session recording"
    trace_test.go:397: remaining span: "sql query"
    trace_test.go:397: remaining span: "sql txn"
    trace_test.go:397: remaining span: "txn coordinator send"
            --- FAIL: TestTrace/ShowTraceForVectorized/TracingOff/node-1 (0.02s)
```

There was already an exception for this span, but with a `storage.` prefix. This patch removes the prefix, and makes it match on substrings.

This flake has possibly been made worse with the introduction of a metamorphic setting to only use expiration-based leases in ecc931be.

Resolves #98971.

Epic: none
Release note: None

### CODE REVIEW

**Review by rharding6373 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99062#-:-NR-lyoI8rekghqom43J:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @erikgrinaker)

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99062)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @erikgrinaker)

___
*[`-- commits` line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99062#-NR-lp5E7Z9DiEOOX46F):*
This suggests that the flake was possible before but it was made more likely recently, right?
___
*[`pkg/sql/trace_test.go` line 385 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99062#-NR-li001JIa3vyy2_yL:-NR-li001JIa3vyy2_yM:b-cuz1sx) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bc72550522110bb9023aa192cf3c7e178e56155/pkg/sql/trace_test.go#L385)):*
> ```Go
> 									t.Errorf("extra span: %s", op)
> 									remainingErr = true
> 								} else if op != test.expSpans[r] {
> ```

I wonder whether we should change this comparison from exact equality to `strings.Contains` and perhaps also remove `storage.Store` prefix from one of other always optional spans.

**Comment by erikgrinaker** [comment]
Yes.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99062)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

___
*[`-- commits` line 16 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99062#-NR-lp5E7Z9DiEOOX46F):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

This suggests that the flake was possible before but it was made more likely recently, right?
</blockquote></details>

No idea, but presumably the ignore rule is there for a reason.
___
*[`pkg/sql/trace_test.go` line 385 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99062#-NR-li001JIa3vyy2_yL:-NR-q6xR8Iip1VHpQfEs:bqewso5) ([raw file](https://github.com/cockroachdb/cockroach/blob/8bc72550522110bb9023aa192cf3c7e178e56155/pkg/sql/trace_test.go#L385)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

I wonder whether we should change this comparison from exact equality to `strings.Contains` and perhaps also remove `storage.Store` prefix from one of other always optional spans.
</blockquote></details>

Yeah, may as well, done. Let's see what CI says.

**Comment by erikgrinaker** [comment]
I'm calling it a night -- feel free to bors this for me on green CI.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

bors r+

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99062#-:-NR0-4OP009LiRz45f2D:b5abyu2)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @erikgrinaker)

**Review by abarganier — APPROVED** [review]
:lgtm: - looking into CI failures.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99062#-:-NR0ESW00378mcrDfSuE:b-a0h7pw)* status: :shipit: complete! 2 of 0 LGTMs obtained (and 1 stale) (waiting on @erikgrinaker)

**Comment by abarganier** [comment]
`TestTenantUpgradeInterlock` is failing on this PR. 

I see [this was merged 7 hours ago](https://github.com/cockroachdb/cockroach/pull/98997) - a fix to increase the timeout with a specific mention of `TestTenantUpgradeInterlock` in the PR description.

I'm going to check to see if this SHA is included on this branch. If not, I'll push a rebase.

**Comment by yuzefovich** [comment]
No need to push the rebase to this branch - bors automatically picks up the newest changes and rebases on top of them the batch that it attempts to merge. Thus, although the CI is red on this PR (because this branch doesn't contain the fix), but the fix has already been merged, then the CI run when borsing should succeed.

**Comment by abarganier** [comment]
@yuzefovich I see, thanks for clarifying. I didn't realize a `bors` would bypass CI failures - TIL!

**Comment by yuzefovich** [comment]
Just to clarify a bit further - the way bors works is as follows:
- pick one or more "borsed" PRs into a batch
- checkout the tip of master and cherry-pick all PRs from the batch onto that branch
- if there is a merge conflict, then the batch fails
- if there are no merge conflicts, then bors kicks off the Bazel Essential CI run on `staging` branch
- whether that CI run succeeds or fails determines whether the batch of PRs is merged to master.

With such setup it doesn't matter whether CI runs on the PRs on their own were successful or not (they are not marked as "required"). (The only required are currently two things: 1) there is at least one GitHub approval on the PR, and 2) the PR is "borsed".)

**Pull request merged**
