### PR TITLE
build: give craig an avatar

### PR DESCRIPTION
**Pull request by couchand**
At present, when GitHub apps create commits, they don't show up
with the app's avatar.  A workaround is to commit with an e-mail
address that has an associated gravatar.

Release note: None

### CODE REVIEW

**Comment by couchand** [comment]
trying to see if it works:

bors try

**Comment by couchand** [comment]
bors try

**Comment by couchand** [comment]
hmmm, I would have expected the avatar to show up there, maybe it's a caching thing....

**Comment by couchand** [comment]
screen shot 2018-04-09 at 1 48 35 pm

**Review by jordanlewis — APPROVED** [review]

**Pull request merged**
