### PR TITLE
storage: fail commands outside the replica GC threshold

### PR DESCRIPTION
**Pull request by madelynnblue**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6992)

### CODE REVIEW

**Comment by mjibson** [comment]
This is blocked on a decision by #6985.

**Comment by bdarnell** [comment]
#6985 was decided in favor of allowing the inconsistency, on the grounds that it is self-healing. This change could introduce non-self-healing inconsistencies. However, queries near the GC cutoff would be so buggy prior to this change that I'm not sure if we care. 

LGTM

<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> This is blocked on a decision by #6985.
</details>


---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[storage/replica_test.go, line 5640 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6992#-KJMUtAohSI1Xh3r5plO:-KJMUtAp78aJdeOh7mVD:916010306) ([raw file](https://github.com/cockroachdb/cockroach/blob/098e09a8ae7ce71348ae3d2c45076af63f6655db/storage/replica_test.go#L5640)):*
> ```Go
> 	// Verify a later Get works.
> 	if _, err := tc.SendWrappedWith(roachpb.Header{
> 		Timestamp: makeTS(3, 0),
> ```

Put the timestamp(3,0) in a variable to make sure it's the same both times it's used.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6992#-:-KJMTYyTETm8eI0eHVBL:-1023844020)*

**Comment by tschottdorf** [comment]
:lgtm:

<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> #6985 was decided in favor of allowing the inconsistency, on the grounds that it is self-healing. This change could introduce non-self-healing inconsistencies. However, queries near the GC cutoff would be so buggy prior to this change that I'm not sure if we care. 
> 
> LGTM
</details>


---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[storage/replica_test.go, line 5642 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6992#-KJMhTKboWy-Le0JJI2H:-KJMhTKboWy-Le0JJI2I:-455008935) ([raw file](https://github.com/cockroachdb/cockroach/blob/098e09a8ae7ce71348ae3d2c45076af63f6655db/storage/replica_test.go#L5642)):*
> ```Go
> 		Timestamp: makeTS(3, 0),
> 	}, &gArgs); err != nil {
> 		t.Fatalf("could not get data: %s", err)
> ```

Add similar tests for a `ConditionalPut`. I expect this to work (since executeBatch is called from executeWriteBatch), but it should be asserted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6992#-:-KJMhmPLiESf4HV_PtzD:1417088721)*

**Comment by tschottdorf** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6992)*

**Comment by mjibson** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/replica_test.go, line 5640 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6992#-KJMUtAohSI1Xh3r5plO:-KJMm1Oc-OW3FSic_5oG:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/098e09a8ae7ce71348ae3d2c45076af63f6655db/storage/replica_test.go#L5640)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Put the timestamp(3,0) in a variable to make sure it's the same both times it's used.
</details>
Done.

---

*[storage/replica_test.go, line 5642 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6992#-KJMhTKboWy-Le0JJI2H:-KJMmhg6eOHEqJ92jkOM:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/098e09a8ae7ce71348ae3d2c45076af63f6655db/storage/replica_test.go#L5642)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Add similar tests for a `ConditionalPut`. I expect this to work (since executeBatch is called from executeWriteBatch), but it should be asserted.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6992)*

**Comment by tschottdorf** [comment]
:lgtm:

<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> :lgtm:
</details>


---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6992#-:-KJNInREYMD5sFmRzRlR:1417088721)*

**Pull request merged**
