### PR TITLE
sql: fix a possible race between Flow.Cleanup and Flow.Cancel

### LINKED ISSUE #95527: pkg/sql/logictest/tests/fakedist-disk/fakedist-disk_test: TestLogic_datetime failed
pkg/sql/logictest/tests/fakedist-disk/fakedist-disk_test.TestLogic_datetime [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/8375867?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UnitTests/8375867?buildTab=artifacts#/) on master @ [f27fa9d4c56e4654939e772d857027da00feb7d5](https://github.com/cockroachdb/cockroach/commits/f27fa9d4c56e4654939e772d857027da00feb7d5):

```
=== RUN   TestLogic_datetime
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/f70ceff7ba074534c17c8b5bbdfe4516/logTestLogic_datetime3399248907
    test_log_scope.go:79: use -show-logs to present logs inline
[18:06:26] setting distsql_workmem='97583B';
=== RUN   TestLogic_datetime/regression_41663
=== RUN   TestLogic_datetime/regression_42244
=== RUN   TestLogic_datetime/tz_utc_normalization
=== RUN   TestLogic_datetime/infinity_time
=== RUN   TestLogic_datetime/interval_math
=== RUN   TestLogic_datetime/regression_35255
=== RUN   TestLogic_datetime/regression_36146
=== RUN   TestLogic_datetime/datestyle_order
[18:06:28] --- done: /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/11410/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/sql/logictest/tests/fakedist-disk/fakedist-disk_test_/fakedist-disk_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/datetime with config fakedist-disk: 334 tests, 0 failures
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1a8 pc=0x2158288]

goroutine 31492 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).recover(0x400663ed48?, {0x59e2008, 0x4002053470})
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:229 +0x68
panic({0x3ee0ba0, 0x8103e60})
	GOROOT/src/runtime/panic.go:884 +0x20c
github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Cancel(0x400411b880?)
	github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:527 +0x18
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).setupFlows.func5({0x4003ba7000?, 0x464cf0?})
	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:625 +0x1f0
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470 +0x128
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:461 +0x358
=== RUN   TestLogic_datetime/regression_36557
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestLogic_datetime.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-23570

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit fixes a possible race that could occur when `Flow.Cleanup`
is called by the main goroutine concurrently with `Flow.Cancel` by the
listener goroutine (which is not allowed). We already had
synchronization in place, but it was insufficient. In particular, the
following scenario could lead to a nil pointer crash:
- the listener checks whether `Cleanup` has been called, it hasn't, and
the mutex is unlocked;
- the listener is preemptied;
- the main goroutine proceeds to perform the `Cleanup`. At the very end
the flow object is unset (including `ctxCancel` overwritten to `nil`);
- the listener resumes its execution, proceeds to call `Cancel` on the
already-unset `Flow` object, leading to a nil pointer on `ctxCancel`
call.

This is now fixed by holding the mutex through the call to `Cancel` in
the listener goroutine, ensuring that the `Flow` object is not unset
from under the listener. Additionally, this commit clarifies the
callbacks that are performed at the very beginning and very end of
`Cleanup` method.

Fixes: #95527.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
I added another commit that fixes another (although less frequent) race. RFAL.

**Review by msirek — APPROVED** [review]
Very nice!
:lgtm: 

> Reviewed 1 of 1 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95522#-:-NMAysq91LJxWySpEpEE:b-z5m9g7)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

**Review by andreimatei — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95522#-:-NMBC8o_6WzgT_CcDND0:bg7igkv)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

**Pull request merged**
