### PR TITLE
build,ui: add support for protobuf WKTs

### PR DESCRIPTION
**Pull request by tamird**
See individual commits.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14396)

### CODE REVIEW

**Comment by mrtracy** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 58 of 58 files at r3, 1 of 1 files at r5, 60 of 60 files at r6.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[build/protobuf.mk, line 51 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14396#-KgGiUaDr2BqqCv456y3:-KgGiUaEftbvZFlkVrjn:b-sauwc6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b07001491fbc41a98945caf9313aa2dc8494dabf/build/protobuf.mk#L51)):*
> ```Makefile
> # Map protobuf includes to the Go package containing the generated Go code.
> MAPPINGS :=
> MAPPINGS := $(MAPPINGS)Mgoogle/api/annotations.proto=$(GRPC_GATEWAY_GOOGLEAPIS_PACKAGE)/google/api,
> ```

Is that weird M necessary after $(MAPPINGS)?  Just looks off to me, assuming this all works finen

---

*[pkg/server/status/status.proto, line 40 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14396#-KgGjGWLjDE2WE_bqwD6:-KgGjGWLjDE2WE_bqwD7:bwghzg4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b07001491fbc41a98945caf9313aa2dc8494dabf/pkg/server/status/status.proto#L40)):*
> ```protobuf
>   repeated StoreStatus store_statuses = 6 [(gogoproto.nullable) = false];
>   repeated string args = 7;
>   repeated string env = 8;
> ```

Why did these change?

---

*[pkg/ui/src/containers/events.spec.tsx, line 42 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14396#-KgGlCqEVGftEieFBAhn:-KgGlCqEVGftEieFBAho:b-11lyqz) ([raw file](https://github.com/cockroachdb/cockroach/blob/99e0d3da51125a14c7b0afa7590bc7e7d5af5147/pkg/ui/src/containers/events.spec.tsx#L42)):*
> ```XML
>       events: [
>         {
>           target_id: Long.fromString("1"),
> ```

well this was a bizarre choice

---

*[pkg/ui/src/containers/metricsDataProvider.spec.tsx, line 45 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14396#-KgGlc7-I8fFI76BgPA0:-KgGlc7-I8fFI76BgPA1:bb7oipv) ([raw file](https://github.com/cockroachdb/cockroach/blob/b07001491fbc41a98945caf9313aa2dc8494dabf/pkg/ui/src/containers/metricsDataProvider.spec.tsx#L45)):*
> ```XML
>         name: "test.metric.1",
>         sources: sources,
>         downsampler: protos.cockroach.ts.tspb.TimeSeriesQueryAggregator.AVG,
> ```

sick

---

*[pkg/ui/src/util/api.spec.ts, line 377 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14396#-KgGpYY5pEi3KscEuS6Q:-KgGpYY5pEi3KscEuS6R:b-lkjoro) ([raw file](https://github.com/cockroachdb/cockroach/blob/b07001491fbc41a98945caf9313aa2dc8494dabf/pkg/ui/src/util/api.spec.ts#L377)):*
> ```XML
>           }).finish();
>           return {
>             body: encodedResponse.buffer.slice(encodedResponse.byteOffset, encodedResponse.byteOffset + encodedResponse.byteLength),
> ```

Couldn't at least the slice part be made into a common method?

```
interface EncodedResponseBuffer {
   buffer: string;
   byteOffset: number;
   byteLength: number;
}

export function trimResponse(response: EncodedResponseBuffer) {
   return response.buffer.slice(response.byteOffset, response.byteOffset + response.byteLength)
}

```

Or is there a subtle difference between these?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14396)*

**Comment by mrtracy** [comment]
LGTM mostly, but you are right that the buffer slicing is annoying and i'm wondering if it shouldn't be extracted to a common method.  There may be no good way to get the "encode().finish()" bit due to the various types involved, but the slicing can almost certainly be extracted and does involve some difficult-to-grok parameters.

**Comment by tamird** [comment]
Extracted!

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[build/protobuf.mk, line 51 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14396#-KgGiUaDr2BqqCv456y3:-KgGvAzQ39bwTwn2dnDU:b9qhs3s) ([raw file](https://github.com/cockroachdb/cockroach/blob/b07001491fbc41a98945caf9313aa2dc8494dabf/build/protobuf.mk#L51)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

Is that weird M necessary after $(MAPPINGS)?  Just looks off to me, assuming this all works finen
</blockquote></details>

Yeah, it's necessary. Note that it was there before this change as well.

---

*[pkg/server/status/status.proto, line 40 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14396#-KgGjGWLjDE2WE_bqwD6:-KgGvFIeDX_IGU9mMrzL:b-hvl0k3) ([raw file](https://github.com/cockroachdb/cockroach/blob/b07001491fbc41a98945caf9313aa2dc8494dabf/pkg/server/status/status.proto#L40)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

Why did these change?
</blockquote></details>

Because `nullable = false` doesn't do anything for repeat primitives in proto3. The commit message calls this out.

---

*[pkg/ui/src/containers/events.spec.tsx, line 42 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14396#-KgGlCqEVGftEieFBAhn:-KgGvLZKgBc9UuK_Otmc:bb7867m) ([raw file](https://github.com/cockroachdb/cockroach/blob/99e0d3da51125a14c7b0afa7590bc7e7d5af5147/pkg/ui/src/containers/events.spec.tsx#L42)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

well this was a bizarre choice
</blockquote></details>

Yup!

---

*[pkg/ui/src/containers/metricsDataProvider.spec.tsx, line 45 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14396#-KgGlc7-I8fFI76BgPA0:-KgGvOQmXdqYvq5Qamt7:br4fkav) ([raw file](https://github.com/cockroachdb/cockroach/blob/b07001491fbc41a98945caf9313aa2dc8494dabf/pkg/ui/src/containers/metricsDataProvider.spec.tsx#L45)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

sick
</blockquote></details>

:confetti_ball: 

---

*[pkg/ui/src/util/api.spec.ts, line 377 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14396#-KgGpYY5pEi3KscEuS6Q:-KgGvRHwQgDcM8PGVLim:bj5mdbc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b07001491fbc41a98945caf9313aa2dc8494dabf/pkg/ui/src/util/api.spec.ts#L377)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

Couldn't at least the slice part be made into a common method?

```
interface EncodedResponseBuffer {
   buffer: string;
   byteOffset: number;
   byteLength: number;
}

export function trimResponse(response: EncodedResponseBuffer) {
   return response.buffer.slice(response.byteOffset, response.byteOffset + response.byteLength)
}

```

Or is there a subtle difference between these?
</blockquote></details>

No, you're absolutely right. Pulled out a util function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14396#-:-KgGwRfYQMHU4MnKH6En:bluklye)*

**Comment by mrtracy** [comment]
:lgtm:

---

Reviewed 1 of 59 files at r4, 14 of 14 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/ui/src/components/graphs.tsx, line 361 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/14396#-KgH-219pif5_sGu3yGS:-KgH-219pif5_sGu3yGT:b-7mq0be) ([raw file](https://github.com/cockroachdb/cockroach/blob/e43af828ff145773d9cb9bab97eba1ed1f88e034/pkg/ui/src/components/graphs.tsx#L361)):*
> ```XML
> }
> 
> type formattedDatum = {
> ```

why this syntax instead of `interface formattedDatum`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14396#-:-KgH0lHhHad9jwSMVlOY:bnfp4nl)*

**Pull request merged**
