### PR TITLE
sql: allow to EXPLAIN on CREATE, DROP and ALTER TABLE.

### PR DESCRIPTION
**Pull request by knz**
This enables using EXPLAIN(TRACE) to investigate database internals
during schema updates.

Requested by @WillHaack.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7269)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
LGTM assuming `EXPLAIN (TRACE)` was tested manually.

**Comment by knz** [comment]
Yes I did test it. Unfortunately since tracing is non-deterministic I could not embed a test for it.

**Comment by tschottdorf** [comment]
You can still write tests, just not in the logictest framework. See
`TestExplainTrace`.

On Thu, Jun 16, 2016 at 9:26 AM kena <notifications@github.com> wrote:

> Merged #7269 <https://github.com/cockroachdb/cockroach/pull/7269>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/pull/7269#event-694621358>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AE135OugP-XcxurO4POQ1D3kGUxUTB_Yks5qMU8MgaJpZM4I3UsX>
> .
>
-- 

-- Tobias

**Comment by andreimatei** [comment]
Well that was easy! Do you get a trace from the "schema change" async part of the command too?

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7269#-:-KKOog60Avm-rpJA53YF:-161592375)*

**Comment by RaduBerinde** [comment]
Writing stuff like TestExplainTrace is pretty clumsy, I think in the long term it might be easier if we added some basic regexp capabilities to logictest (e.g. to match any timing values for that column)

**Pull request merged**
