### PR TITLE
.gitignore cleanup

### PR DESCRIPTION
**Pull request by jordanlewis**
Fix a TODO; improve the global gitignore advice.

### CODE REVIEW

**Comment by tamird** [comment]
I have a stale branch with more changes you might consider:
```diff
commit bad527e32dcdce4670623c3f5409fc42c76fd0ec
Author: Tamir Duberstein <tamird@gmail.com>
Date:   Mon May 1 19:33:50 2017 -0400

    .gitignore: remove stale entries

diff --git a/.gitignore b/.gitignore
index aa41f52f2..b05ee4758 100644
--- a/.gitignore
+++ b/.gitignore
@@ -14,21 +14,12 @@
 artifacts
 /bin
 /bin.*
-# TeamCity sometimes creates this file during builds.
-builds.xml
 .buildinfo
 # cockroach-data, cockroach{,.race}-{darwin,linux,windows}-*
 /cockroach*
 /certs
 # make stress, acceptance produce stress.test, acceptance.test
 *.test*
-# Various `sed -i~` invocations in our scripts.
-*~
-
-# TODO(benesch): the .bootstrap file has moved into the bin directory; remove
-# this entry once it's unlikely developers have branches that straddle this
-# change (a few weeks after 4/7/2017).
-.bootstrap
 
 # Custom or private env vars (e.g. internal keys, access tokens, etc).
 customenv.mk

```

(we no longer do `sed -i~` and the teamcity thing turned out not to be necessary.

**Comment by benesch** [comment]
Something still creates ~ backup files. `add-leaktest.sh`, perhaps?

**Comment by benesch** [comment]
@tschottdorf, just a heads up: I think this is your advice we're removing.

**Review by benesch — APPROVED** [review]

**Comment by tamird** [comment]
> Something still creates ~ backup files. add-leaktest.sh, perhaps?

I haven't seen this - can you confirm?

**Review by bdarnell — APPROVED** [review]

**Comment by bdarnell** [comment]
Yes, `add-leaktest.sh` still does `sed -i~`

**Comment by bdarnell** [comment]
And in case we want to retain some advice about what to put in `.gitignore_global`, we could link to https://github.com/github/gitignore/tree/master/Global which has recommended gitignore entries for different tools.

**Pull request merged**
