### PR TITLE
descs: reduce heap usage in getNonVirtualDescriptorID

### PR DESCRIPTION
**Pull request by msirek**
The Go compiler is not able to use stack memory in the
`lookupStoreCacheID` closure, even if the functions calls within it are
changed to pass the locally-built `descpb.NameInfo` by value, resulting
in hundreds of MiB of allocated space for tests which look up a table
thousands of times.

The solution is to refactor the code to call the inner functions
directly, preventing the `descpb.NameInfo` argument from leaking
to the heap.

**Benchmark Results**
```
dev bench //pkg/sql/catalog/descs -f='BenchmarkDescriptorCache' --bench-mem \
          --ignore-cache --stream-output --count 10 -v --bench-time=3s
```
**without fix:**
```
BenchmarkDescriptorCache/immutable_table_descriptor
BenchmarkDescriptorCache/immutable_table_descriptor-10         	 3689557	       966.8 ns/op	     167 B/op	      11 allocs/op
BenchmarkDescriptorCache/immutable_table_descriptor-10         	 3713419	       968.9 ns/op	     164 B/op	      11 allocs/op
BenchmarkDescriptorCache/immutable_table_descriptor-10         	 3696469	       965.9 ns/op	     167 B/op	      11 allocs/op
BenchmarkDescriptorCache/immutable_table_descriptor-10         	 3708067	       967.7 ns/op	     164 B/op	      11 allocs/op
BenchmarkDescriptorCache/immutable_table_descriptor-10         	 3700088	       966.2 ns/op	     172 B/op	      11 allocs/op
BenchmarkDescriptorCache/immutable_table_descriptor-10         	 3724609	       969.4 ns/op	     164 B/op	      11 allocs/op
BenchmarkDescriptorCache/immutable_table_descriptor-10         	 3712176	       988.4 ns/op	     172 B/op	      11 allocs/op
BenchmarkDescriptorCache/immutable_table_descriptor-10         	 3321098	      1019 ns/op	     164 B/op	      11 allocs/op
BenchmarkDescriptorCache/immutable_table_descriptor-10         	 3717261	       966.6 ns/op	     172 B/op	      11 allocs/op
BenchmarkDescriptorCache/immutable_table_descriptor-10         	 3699794	       964.6 ns/op	     164 B/op	      11 allocs/op
BenchmarkDescriptorCache/mutable_table_descriptor
BenchmarkDescriptorCache/mutable_table_descriptor-10           	 2013207	      1781 ns/op	    1065 B/op	      20 allocs/op
BenchmarkDescriptorCache/mutable_table_descriptor-10           	 2011074	      1776 ns/op	    1050 B/op	      20 allocs/op
BenchmarkDescriptorCache/mutable_table_descriptor-10           	 2025692	      1816 ns/op	    1326 B/op	      21 allocs/op
BenchmarkDescriptorCache/mutable_table_descriptor-10           	 2012298	      1788 ns/op	    1050 B/op	      20 allocs/op
BenchmarkDescriptorCache/mutable_table_descriptor-10           	 2017578	      1773 ns/op	    1050 B/op	      20 allocs/op
BenchmarkDescriptorCache/mutable_table_descriptor-10           	 2009506	      1777 ns/op	    1050 B/op	      20 allocs/op
BenchmarkDescriptorCache/mutable_table_descriptor-10           	 2025168	      1769 ns/op	    1050 B/op	      20 allocs/op
BenchmarkDescriptorCache/mutable_table_descriptor-10           	 2029318	      1793 ns/op	    1058 B/op	      20 allocs/op
BenchmarkDescriptorCache/mutable_table_descriptor-10           	 2013554	      1781 ns/op	    1051 B/op	      20 allocs/op
BenchmarkDescriptorCache/mutable_table_descriptor-10           	 2030397	      1772 ns/op	    1063 B/op	      20 allocs/op
```
**with fix:**
```
BenchmarkDescriptorCache/immutable_table_descriptor
BenchmarkDescriptorCache/immutable_table_descriptor-10         	 4082704	       876.3 ns/op	      70 B/op	       7 allocs/op
BenchmarkDescriptorCache/immutable_table_descriptor-10         	 4107186	       880.0 ns/op	      68 B/op	       7 allocs/op
BenchmarkDescriptorCache/immutable_table_descriptor-10         	 4112974	       874.7 ns/op	      68 B/op	       7 allocs/op
BenchmarkDescriptorCache/immutable_table_descriptor-10         	 4124313	       867.7 ns/op	      68 B/op	       7 allocs/op
BenchmarkDescriptorCache/immutable_table_descriptor-10         	 4128722	       869.9 ns/op	      80 B/op	       7 allocs/op
BenchmarkDescriptorCache/immutable_table_descriptor-10         	 4130685	       871.0 ns/op	      69 B/op	       7 allocs/op
BenchmarkDescriptorCache/immutable_table_descriptor-10         	 4094190	       876.8 ns/op	      75 B/op	       7 allocs/op
BenchmarkDescriptorCache/immutable_table_descriptor-10         	 4120947	       870.4 ns/op	      68 B/op	       7 allocs/op
BenchmarkDescriptorCache/immutable_table_descriptor-10         	 4100317	       873.1 ns/op	      75 B/op	       7 allocs/op
BenchmarkDescriptorCache/immutable_table_descriptor-10         	 4103818	       868.9 ns/op	      68 B/op	       7 allocs/op
BenchmarkDescriptorCache/mutable_table_descriptor
BenchmarkDescriptorCache/mutable_table_descriptor-10           	 2380312	      1515 ns/op	     966 B/op	      16 allocs/op
BenchmarkDescriptorCache/mutable_table_descriptor-10           	 2351344	      1524 ns/op	     954 B/op	      16 allocs/op
BenchmarkDescriptorCache/mutable_table_descriptor-10           	 2367862	      1550 ns/op	    1109 B/op	      17 allocs/op
BenchmarkDescriptorCache/mutable_table_descriptor-10           	 2311496	      1514 ns/op	     954 B/op	      16 allocs/op
BenchmarkDescriptorCache/mutable_table_descriptor-10           	 2354755	      1543 ns/op	     968 B/op	      16 allocs/op
BenchmarkDescriptorCache/mutable_table_descriptor-10           	 2339215	      1514 ns/op	     954 B/op	      16 allocs/op
BenchmarkDescriptorCache/mutable_table_descriptor-10           	 2367279	      1512 ns/op	     966 B/op	      16 allocs/op
BenchmarkDescriptorCache/mutable_table_descriptor-10           	 2380909	      1508 ns/op	     954 B/op	      16 allocs/op
BenchmarkDescriptorCache/mutable_table_descriptor-10           	 2380462	      1513 ns/op	     967 B/op	      16 allocs/op
BenchmarkDescriptorCache/mutable_table_descriptor-10           	 2373717	      1514 ns/op	     954 B/op	      16 allocs/op
```
**benchstat:**
```
                                              │ without_fix │              with_fix               │
                                              │   sec/op    │   sec/op     vs base                │
DescriptorCache/immutable_table_descriptor-10   967.2n ± 2%   872.0n ± 1%   -9.84% (p=0.000 n=10)
DescriptorCache/mutable_table_descriptor-10     1.779µ ± 1%   1.514µ ± 2%  -14.90% (p=0.000 n=10)
geomean                                         1.312µ        1.149µ       -12.41%

                                              │ without_fix │              with_fix              │
                                              │    B/op     │    B/op     vs base                │
DescriptorCache/immutable_table_descriptor-10   165.50 ± 4%   68.50 ± 9%  -58.61% (p=0.000 n=10)
DescriptorCache/mutable_table_descriptor-10     1050.5 ± 1%   960.0 ± 1%   -8.61% (p=0.001 n=10)
geomean                                          417.0        256.4       -38.50%

                                              │ without_fix │              with_fix              │
                                              │  allocs/op  │ allocs/op   vs base                │
DescriptorCache/immutable_table_descriptor-10   11.000 ± 0%   7.000 ± 0%  -36.36% (p=0.000 n=10)
DescriptorCache/mutable_table_descriptor-10      20.00 ± 0%   16.00 ± 0%  -20.00% (p=0.000 n=10)
geomean                                          14.83        10.58       -28.65%
```

Informs #105867

Release note (performance improvement): This patch optimizes memory
usage when performing cached table descriptor lookups, which could
speed up workloads with many point queries.

----
catalog: eliminate allocations in MaybeRequiresHydration

This commit eliminates heap allocations in function
`MaybeRequiresHydration`  when looking up descriptors by name by
changing the closure, passed as a function argument, into a function.

**Benchmark Results**
```
dev bench //pkg/sql/catalog/descs -f='BenchmarkDescriptorCache' --bench-mem \
          --ignore-cache --stream-output --count 10 -v --bench-time=3s
```
```
BenchmarkDescriptorCache/immutable_table_descriptor
BenchmarkDescriptorCache/immutable_table_descriptor-10         	 4515679	       795.9 ns/op	      19 B/op	       1 allocs/op
BenchmarkDescriptorCache/immutable_table_descriptor-10         	 4551014	       794.1 ns/op	      17 B/op	       1 allocs/op
BenchmarkDescriptorCache/immutable_table_descriptor-10         	 4512546	       796.8 ns/op	      16 B/op	       1 allocs/op
BenchmarkDescriptorCache/immutable_table_descriptor-10         	 4493860	       794.5 ns/op	      16 B/op	       1 allocs/op
BenchmarkDescriptorCache/immutable_table_descriptor-10         	 4513683	       793.7 ns/op	      23 B/op	       1 allocs/op
BenchmarkDescriptorCache/immutable_table_descriptor-10         	 4428988	       797.5 ns/op	      18 B/op	       1 allocs/op
BenchmarkDescriptorCache/immutable_table_descriptor-10         	 4505838	       791.3 ns/op	      23 B/op	       1 allocs/op
BenchmarkDescriptorCache/immutable_table_descriptor-10         	 4539226	       791.8 ns/op	      16 B/op	       1 allocs/op
BenchmarkDescriptorCache/immutable_table_descriptor-10         	 4539788	       792.4 ns/op	      23 B/op	       1 allocs/op
BenchmarkDescriptorCache/immutable_table_descriptor-10         	 4510224	       792.2 ns/op	      16 B/op	       1 allocs/op
BenchmarkDescriptorCache/mutable_table_descriptor
BenchmarkDescriptorCache/mutable_table_descriptor-10           	 2504500	      1436 ns/op	     902 B/op	      10 allocs/op
BenchmarkDescriptorCache/mutable_table_descriptor-10           	 2501647	      1431 ns/op	     902 B/op	      10 allocs/op
BenchmarkDescriptorCache/mutable_table_descriptor-10           	 2516917	      1444 ns/op	     902 B/op	      10 allocs/op
BenchmarkDescriptorCache/mutable_table_descriptor-10           	 2395996	      1441 ns/op	     940 B/op	      10 allocs/op
BenchmarkDescriptorCache/mutable_table_descriptor-10           	 2505079	      1430 ns/op	     901 B/op	      10 allocs/op
BenchmarkDescriptorCache/mutable_table_descriptor-10           	 2502846	      1429 ns/op	     902 B/op	      10 allocs/op
BenchmarkDescriptorCache/mutable_table_descriptor-10           	 2512407	      1430 ns/op	     914 B/op	      10 allocs/op
BenchmarkDescriptorCache/mutable_table_descriptor-10           	 2501658	      1428 ns/op	     902 B/op	      10 allocs/op
BenchmarkDescriptorCache/mutable_table_descriptor-10           	 2507274	      1437 ns/op	     912 B/op	      10 allocs/op
BenchmarkDescriptorCache/mutable_table_descriptor-10           	 2505388	      1433 ns/op	     902 B/op	      10 allocs/op
```
**benchstat results compared to the first commit**
```
                                              │ getNonVirtualDescriptorID_fix │ maybe_requires_hydration_plus_getNonVirtualDescriptorID_fix │
                                              │            sec/op             │                sec/op                 vs base               │
DescriptorCache/immutable_table_descriptor-10                     872.0n ± 1%                            793.9n ± 0%  -8.96% (p=0.000 n=10)
DescriptorCache/mutable_table_descriptor-10                       1.514µ ± 2%                            1.432µ ± 1%  -5.42% (p=0.000 n=10)
geomean                                                           1.149µ                                 1.066µ       -7.21%

                                              │ getNonVirtualDescriptorID_fix │ maybe_requires_hydration_plus_getNonVirtualDescriptorID_fix │
                                              │             B/op              │                B/op                  vs base                │
DescriptorCache/immutable_table_descriptor-10                      68.50 ± 9%                           17.50 ± 31%  -74.45% (p=0.000 n=10)
DescriptorCache/mutable_table_descriptor-10                        960.0 ± 1%                           902.0 ±  1%   -6.04% (p=0.000 n=10)
geomean                                                            256.4                                125.6        -51.01%

                                              │ getNonVirtualDescriptorID_fix │ maybe_requires_hydration_plus_getNonVirtualDescriptorID_fix │
                                              │           allocs/op           │              allocs/op               vs base                │
DescriptorCache/immutable_table_descriptor-10                      7.000 ± 0%                            1.000 ± 0%  -85.71% (p=0.000 n=10)
DescriptorCache/mutable_table_descriptor-10                        16.00 ± 0%                            10.00 ± 0%  -37.50% (p=0.000 n=10)
geomean                                                            10.58                                 3.162       -70.12%
```

Informs #105867

Release note (performance improvement): This patch optimizes memory
usage when performing table descriptor lookups, which could speed up
workloads with many point queries.

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
:lgtm: Nice improvements!

> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106468#-:-NZrHal97kc4-tk8mwKd:bdyovjk)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek and @rharding6373)

___
*[`pkg/sql/catalog/descriptor.go` line 1079 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106468#-NZrHZjt1b7DMth6jwGC:-NZrHZjt1b7DMth6jwGD:bz2hr7l) ([raw file](https://github.com/cockroachdb/cockroach/blob/6b3482c5b35462de5f3918704e00d76286e2cf0e/pkg/sql/catalog/descriptor.go#L1079)):*
> ```Go
> }
> 
> func stopIteration(t *types.T) error {
> ```

This is clever!
___
*[`pkg/sql/catalog/nstree/catalog.go` line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106468#-NZrGS3t2lEdMlRXuTHj:-NZrGS3uAigfcg_AkWAN:bdlr1x) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac08067d69758c53c888d4e2b48120ca23b86735/pkg/sql/catalog/nstree/catalog.go#L191)):*
> ```Go
> // LookupNameEntry looks up a descriptor ID by parentID, parentSchemaID and
> // name.
> func (c Catalog) LookupNameEntry(
> ```

[nit] Could we make the method name more descriptive to differentiate it from `LookupNamespaceEntry`? Struggling to think of something, but maybe `WithParent` or `WithParentID`?

**Comment by DrewKimball** [comment]
Out of curiosity, have you tried running kv0 2KB with and without these changes to see the impact on heap profile?

**Comment by msirek** [comment]
> Out of curiosity, have you tried running kv0 2KB with and without these changes to see the impact on heap profile?

Nope. I don't think I've run that before. Will have to look it up.

**Comment by DrewKimball** [comment]
`workload run kv --read-percent 0 --min-block-bytes 2000 --max-block-bytes 2000` should do the trick if you're interested. I saw the same `IsStale` allocations running that.

**Comment by rafiss** [comment]
Nice improvement! Can we make sure this gets a SQL Foundations review before merging?

**Comment by msirek** [comment]
**overall improvement of both commits combined**
```
                                              │ without_fix │ maybe_requires_hydration_plus_getNonVirtualDescriptorID_fix │
                                              │   sec/op    │               sec/op                 vs base                │
DescriptorCache/immutable_table_descriptor-10   967.2n ± 2%                           793.9n ± 0%  -17.92% (p=0.000 n=10)
DescriptorCache/mutable_table_descriptor-10     1.779µ ± 1%                           1.432µ ± 1%  -19.51% (p=0.000 n=10)
geomean                                         1.312µ                                1.066µ       -18.72%

                                              │ without_fix │ maybe_requires_hydration_plus_getNonVirtualDescriptorID_fix │
                                              │    B/op     │                B/op                  vs base                │
DescriptorCache/immutable_table_descriptor-10   165.50 ± 4%                           17.50 ± 31%  -89.43% (p=0.000 n=10)
DescriptorCache/mutable_table_descriptor-10     1050.5 ± 1%                           902.0 ±  1%  -14.14% (p=0.000 n=10)
geomean                                          417.0                                125.6        -69.87%

                                              │ without_fix │ maybe_requires_hydration_plus_getNonVirtualDescriptorID_fix │
                                              │  allocs/op  │              allocs/op               vs base                │
DescriptorCache/immutable_table_descriptor-10   11.000 ± 0%                            1.000 ± 0%  -90.91% (p=0.000 n=10)
DescriptorCache/mutable_table_descriptor-10      20.00 ± 0%                            10.00 ± 0%  -50.00% (p=0.000 n=10)
geomean                                          14.83                                 3.162       -78.68%
```

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106468)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @postamar, and @rharding6373)

___
*[`pkg/sql/catalog/nstree/catalog.go` line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106468#-NZrGS3t2lEdMlRXuTHj:-NZrmreX-yjfHujhCJ-D:buy58lb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ac08067d69758c53c888d4e2b48120ca23b86735/pkg/sql/catalog/nstree/catalog.go#L191)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Could we make the method name more descriptive to differentiate it from `LookupNamespaceEntry`? Struggling to think of something, but maybe `WithParent` or `WithParentID`?
</blockquote></details>

Sure. It may be a little wordy, but `LookupNameEntryUsingUnwrappedNameKeyFields` is more descriptive.

**Comment by msirek** [comment]
kv0 2KB seems to have regressed, so no need to review this further right now.
`workload run kv --read-percent 0 --min-block-bytes 2048 --max-block-bytes 2048 --ramp=1m --duration=10m`
old:
```
_elapsed___errors__ops/sec(inst)___ops/sec(cum)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
  581.0s        0         1881.9         1899.0      9.4     16.3     35.7     35.7 write
  582.0s        0         1979.5         1899.1      9.4     14.2     15.2     16.3 write
  583.0s        0         2047.4         1899.3      8.9     14.2     18.9     21.0 write
  584.0s        0         2033.1         1899.6      9.4     15.2     16.8     17.8 write
  585.0s        0         1822.7         1899.4     10.5     15.2     28.3     33.6 write
  586.0s        0         2035.7         1899.7      8.9     14.7     17.8     18.9 write
  587.0s        0         1844.8         1899.6     10.0     16.3     23.1     28.3 write
  588.0s        0         1515.6         1898.9     10.5     21.0     88.1    142.6 write
  589.0s        0         1962.4         1899.0      9.4     15.2     21.0     23.1 write
  590.0s        0         1881.6         1899.0     10.0     15.2     22.0     23.1 write
  591.0s        0         2059.5         1899.3      8.9     15.2     17.8     17.8 write
  592.0s        0         2079.9         1899.6      8.4     14.2     15.7     16.3 write
  593.0s        0         2076.9         1899.9      8.4     14.2     16.8     18.9 write
  594.0s        0         2059.4         1900.2      8.4     15.2     17.8     22.0 write
  595.0s        0         1348.4         1899.2     13.1     33.6     71.3    117.4 write
  596.0s        0         1979.4         1899.4      9.4     14.7     18.9     19.9 write
  597.0s        0         1978.8         1899.5      9.4     14.7     15.7     17.8 write
  598.0s        0         1994.8         1899.7      9.4     14.7     17.8     21.0 write
  599.0s        0         1960.7         1899.8      9.4     15.7     18.9     18.9 write
  600.0s        0         2005.9         1899.9      9.4     14.2     16.3     25.2 write
Write sequence could be resumed by passing --write-seq=R1211381 to the next run.

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0        1139959         1899.9     10.5      9.4     16.3     25.2    176.2  write

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
  600.0s        0        1139959         1899.9     10.5      9.4     16.3     25.2    176.2
```
new:
```
_elapsed___errors__ops/sec(inst)___ops/sec(cum)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
  581.0s        0         1578.3         1628.8     11.0     19.9     29.4     29.4 write
  582.0s        0         1623.4         1628.8     11.0     19.9     24.1     27.3 write
  583.0s        0         1630.2         1628.8     10.5     21.0     24.1     25.2 write
  584.0s        0         1637.4         1628.8     11.0     21.0     26.2     27.3 write
  585.0s        0         1539.3         1628.6     11.0     21.0     39.8     50.3 write
  586.0s        0         1288.2         1628.0     14.2     31.5     48.2     75.5 write
  587.0s        0         1749.8         1628.2     10.5     18.9     21.0     25.2 write
  588.0s        0         1727.4         1628.4     10.5     17.8     35.7     41.9 write
  589.0s        0         1727.1         1628.6     10.5     18.9     33.6     33.6 write
  590.0s        0         1541.8         1628.4     11.5     22.0     27.3     27.3 write
  591.0s        0         1665.4         1628.5     10.5     18.9     23.1     23.1 write
  592.0s        0         1700.3         1628.6     10.5     18.9     27.3     29.4 write
  593.0s        0         1584.4         1628.5     10.5     23.1     25.2     26.2 write
  594.0s        0         1506.1         1628.3     12.1     22.0     29.4     35.7 write
  595.0s        0         1303.3         1627.8     15.2     27.3     39.8    117.4 write
  596.0s        0         1664.8         1627.9     10.5     19.9     23.1     26.2 write
  597.0s        0         1440.4         1627.5     11.5     21.0     88.1    167.8 write
  598.0s        0         1549.9         1627.4     11.5     19.9     54.5     56.6 write
  599.0s        0         1446.6         1627.1     10.5     19.9    134.2    167.8 write
  600.0s        0         1812.0         1627.4     10.5     18.9     27.3     28.3 write
Write sequence could be resumed by passing --write-seq=R1034865 to the next run.

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0         976451         1627.4     12.3     11.0     19.9     26.2    201.3  write

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
  600.0s        0         976451         1627.4     12.3     11.0     19.9     26.2    201.3
```

**Comment by DrewKimball** [comment]
>kv0 2KB seems to have regressed

That's strange. Were both runs done with a fresh store?

**Comment by msirek** [comment]
> > kv0 2KB seems to have regressed
> 
> That's strange. Were both runs done with a fresh store?

Yes

**Comment by postamar** [comment]
LGTM!

**Review by postamar — APPROVED** [review]

**Comment by msirek** [comment]
A 1-hour run of `kv0/2KB` also shows a regression. Memory is likely not be the limiting factor here.  

`workload run kv --read-percent 0 --min-block-bytes 2048 --max-block-bytes 2048 --ramp=1m --duration=60m`

old:
```
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
 3600.0s        0        5970583         1658.5     12.0     10.5     18.9     29.4    234.9
```
new:
```
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
 3600.0s        0        5524045         1534.5     13.0     11.5     22.0     32.5   1342.2
```

**Comment by nvanbenschoten** [comment]
Nice improvements! Memory is not the limiting factor in `kv0/2kb`, especially without compressible data. Have you looked at `pkg/sql/tests`? The `BenchmarkKV/./SQL` microbenchmark suite is a good mid-level benchmark to test optimizations like this.

**Pull request closed without merging**
