### PR TITLE
Move call to SetNewRequest in dist_sender outside inner send loop

### PR DESCRIPTION
**Pull request by spencerkimball**
Previously, we would always increment the txn sequence number on
calls from the dist sender to a store. In the event of a send error,
this would potentially replay requests using new sequence numbers.
While this wouldn't necessarily cause any errors (mutations in txns
yield write too old errors), on a replay of BeginTransaction, we'd
get an error because the epoch wasn't incremented but the txn record
already exists.

Removed additional extraneous calls to SetNewRequest for clarity.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5360)

### CODE REVIEW

**Comment by spencerkimball** [comment]
Fixes #4443

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[kv/dist_sender.go, line 567 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5360#-KD75Rsxd-sDzuap0euj:-KD75Rsxd-sDzuap0euk:-1889736555) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5aee4f8da8af27c7e9a58fa397229d4b7091bc3/kv/dist_sender.go#L567)):*
This isn't doing what the comment claims - this increases for each descriptor addressed (so it can't hit the same range with the same number). I think you want to move it out of the for loop. The wording is a bit confusing, how about

> Increase the sequence counter only once before sending RPCs to the ranges
involved in this chunk of the batch (as opposed to for each RPC individually).
On RPC errors, there's no guarantee that the request hasn't made its way to
the target regardless of the error; we'd like the second execution to be
caught by the sequence cache if that happens.
There is a small chance that that we address a range twice in this chunk
(stale/suboptimal descriptors due to splits/merges) which leads to a
transaction retry.

Add a TODO/file an issue - if this does happen, we must make sure that the descriptors update accordingly or we'll spin in a busy loop.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5360#-:-KD78EVJyhG70gvmX3pY:1417088721)*

**Comment by spencerkimball** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[kv/dist_sender.go, line 567 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5360#-KD75Rsxd-sDzuap0euj:-KD7Y0cT3Hl3uoswJ0c0:546297925) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5aee4f8da8af27c7e9a58fa397229d4b7091bc3/kv/dist_sender.go#L567)):*
There's actually a unittest in kv/dist_sender_test.go which specifically verifies we increment the sequence number between ranges in a batch chunk. I took most of the verbiage of your comment but I'm not feeling comfortable dropping this test given my level of understanding.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5360)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[kv/dist_sender.go, line 567 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5360#-KD75Rsxd-sDzuap0euj:-KD7ZcFHkORf0IVk6flB:-2146168766) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5aee4f8da8af27c7e9a58fa397229d4b7091bc3/kv/dist_sender.go#L567)):*
Ah, yeah. That's the busy loop I mentioned above. I suppose we could improve the logic - we update the sequence number every time we see a new descriptor (should be able to check that by only holding on to the previous descriptor and comparing to the current). But I'm ok with leaving that as a TODO. In any case, the comment should reflect the reality - if this is where the update stays, then this seeing-one-range-as-two anomaly doesn't cause a retry because we do increment the counter in between.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5360)*

**Comment by tschottdorf** [comment]
Needs a rebase.

**Pull request merged**
