### PR TITLE
tabledesc: improve view validation

### LINKED ISSUE #63147: catalog/tabledesc: improve view validation in `ValidateCrossReferences`
**Is your feature request related to a problem? Please describe.**

We don't currently validate the cross references. This is a bummer. We won't want to enforce validation of them on read because of existing bugs but we would like to prevent new errors from being created.

See https://github.com/cockroachdb/cockroach/blob/bd62e2cbb32070f3b0be2b757de6dd2a2cbb352b/pkg/sql/catalog/tabledesc/validate_test.go#L93-L98

**Describe the solution you'd like**

We should validate the cross references.

**Additional context**

Relates to https://github.com/cockroachdb/cockroach/issues/63065

Epic: CRDB-1519

### PR DESCRIPTION
**Pull request by postamar**
Previously, we did not validate the DependsOn and DependedOnBy
cross-references. This commit adds this validation and also fixes a bug
in which privileges were not validated for non-physical tables.

Fixes #63147.

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70632)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)

___
*[pkg/sql/catalog/tabledesc/validate.go, line 161 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70632#-MkJfGvY7Q8rcXXEuCst:-MkJfGvY7Q8rcXXEuCsu:bx6xtx6) ([raw file](https://github.com/cockroachdb/cockroach/blob/7de5ac7b9e98d9f812043f27a96a017dc930fb00/pkg/sql/catalog/tabledesc/validate.go#L161)):*
> ```Go
> 		vea.Report(desc.validateOutboundTableRef(id, vdg))
> 	}
> 	for _, by := range desc.DependedOnBy {
> ```

FWIW this also affects regular tables (and sequences!) which are depended on by views.

Consider
```sql
CREATE SEQUENCE s;
CREATE TABLE t (i INT PRIMARY KEY DEFAULT (nextval('s')));
CREATE VIEW v AS SELECT nextval('s') FROM t;
```

`v` will depend on both `t` and `s`.
`s` will be depended on by `t` and `v`.

Now for the gross part:
`t` will depend on depended on by `v` but, it does not mark it self as depending on for `s`, that will only show up in the `UsesSequenceIDs` of the column.

So, yeah, not sure this totally works.

**Comment by postamar** [comment]
Thanks, that explains at least some of these errors. Back to the drawing board.

**Comment by ajwerner** [comment]
> Back to the drawing board.

I don’t think it's so bad. It does highlight the complete lack of consistency we have on some of these fields.

**Comment by postamar** [comment]
It's moderately bad, in fact. I'd like to draw your attention to the logic test I added, which is failing due to a quirky bug: 

```
statement ok
CREATE SEQUENCE s63147

statement ok
CREATE TABLE t63147 (a INT PRIMARY KEY)

statement ok
INSERT INTO t63147 (a) VALUES (1), (2)

statement error pgcode 0A000 cannot evaluate scalar expressions containing sequence operations in this context
ALTER TABLE t63147 ADD b INT DEFAULT nextval('s63147')
```

The backfiller rightfully throws an error because the table already has data in it. Unfortunately, while the forward reference in the sequence's descriptor is removed, the back-reference to the sequence in the table's descriptor is not. This bug has presumably been around for a while.

**Comment by postamar** [comment]
`TestCleanupSchemaObjects` is still failing and I'm stumped as to why. For some reason, the descriptor collection is seeing an old version of the sequence descriptor when the validation failure happens. There might be something else at play here.

**Comment by ajwerner** [comment]
>```
> statement error pgcode 0A000 cannot evaluate scalar expressions containing sequence operations in this context
>ALTER TABLE t63147 ADD b INT DEFAULT nextval('s63147')
>```

This has nothing to do with the table having data. This is just https://github.com/cockroachdb/cockroach/issues/42508

**Comment by postamar** [comment]
I'm not sure what changed but the tests pass now that I've rebased.

**Review by ajwerner — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70632)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @postamar)

___
*[pkg/sql/schema_changer.go, line 1322 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70632#-MpI3FnO-yzZnZ1dZy47:-MpI3FnP3eny8N9H6IIG:b-wghkbt) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f2d2723c4b73e8f0daaad47b17afb9dc4ea21d4/pkg/sql/schema_changer.go#L1322)):*
<details><summary><i alt="summary">Quoted 25 lines of code…</i></summary>

> ```
> 			// Update the set of back references.
> 			for id := range referencedSequenceIDs {
> 				tbl, err := descsCol.GetMutableTableVersionByID(ctx, id, txn)
> 				if err != nil {
> 					return err
> 				}
> 				tbl.RemoveDependedOnBy(scTable.ID)
> 				if err := descsCol.WriteDescToBatch(ctx, kvTrace, tbl, b); err != nil {
> 					return err
> 				}
> 			}
> 			for id, colIDs := range newReferencedSequenceIDs {
> 				tbl, err := descsCol.GetMutableTableVersionByID(ctx, id, txn)
> 				if err != nil {
> 					return err
> 				}
> 				tbl.AddDependedOnBy(descpb.TableDescriptor_Reference{
> 					ID:        scTable.ID,
> 					ColumnIDs: colIDs,
> 					ByID:      true,
> 				})
> 				if err := descsCol.WriteDescToBatch(ctx, kvTrace, tbl, b); err != nil {
> 					return err
> 				}
> 			}
> ```
</details>

something smells here. These sets can overlap, can't they? Can we do a little set math and only remove the now removed ones and only add the now added ones? Otherwise we're going to potentially put the delete and write into the same batch and that feels bizarre to me. 
___
*[pkg/sql/logictest/testdata/logic_test/sequences, line 1938 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70632#-MpI3sOx6rVAGczNpLdy:-MpI3sOy21wwCDD0Toz6:b-hsqyz8) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f2d2723c4b73e8f0daaad47b17afb9dc4ea21d4/pkg/sql/logictest/testdata/logic_test/sequences#L1938)):*
> ```
> SELECT count(*) FROM crdb_internal.invalid_objects;
> ----
> 0
> ```

did you also want to do some dropping and make sure things were still okay?

**Comment by postamar** [comment]
> something smells here

Indeed. I copied it a bit too hastily from the type references. I shouldn't have, it's all a bit dodgy. I've got something better in the works but then I found the validation lacking... There's a lot here that needs to be covered by tests and just because of how obscure this all is, it really deserves proper treatment. I'm on it.

**Comment by postamar** [comment]
Well, this took longer than expected. As it turns out, the meaning of `ColumnIDs` in `DependedOnBy` is different depending on whether the table it's in is a sequence or not 🤮 

The validation I added covers what _is_ instead of what _should be_. For instance, views referencing types will have their IDs in `DependsOnTypes` all right, but the types don't have back-references to the view for some reason. In time, all references should have corresponding back-references. However, doing so involves a cluster migration. It would in some ways be less bad than the FK representation migration from 20.1 because we're better at this kind of thing these days. In some other ways it would be worse: at least the old FK representation had the references present, in this case we have to add back-references when they're entirely missing, making this probably worse than `O(n)` with `n` the number of descriptors. Doing so would also require making it possible to version-gate validation checks, which is probably something that we want to be able to do regardless.

I also noticed a bunch of things wrong in the declarative schema changer, which we mostly get away with because DROPs don't bother removing sequence references piecemeal. I think ADD COLUMN might be broken, though.

**Review by postamar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70632)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/sql/schema_changer.go, line 1322 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70632#-MpI3FnO-yzZnZ1dZy47:-MulNGkK9PYd6otybH8e:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f2d2723c4b73e8f0daaad47b17afb9dc4ea21d4/pkg/sql/schema_changer.go#L1322)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 			// Update the set of back references.
> 			for id := range referencedSequenceIDs {
> 				tbl, err := descsCol.GetMutableTableVersionByID(ctx, id, txn)
> 				if err != nil {
> 					return err
> 				}
> 				tbl.RemoveDependedOnBy(scTable.ID)
> 				if err := descsCol.WriteDescToBatch(ctx, kvTrace, tbl, b); err != nil {
> 					return err
> 				}
> 			}
> 			for id, colIDs := range newReferencedSequenceIDs {
> 				tbl, err := descsCol.GetMutableTableVersionByID(ctx, id, txn)
> 				if err != nil {
> 					return err
> 				}
> 				tbl.AddDependedOnBy(descpb.TableDescriptor_Reference{
> 					ID:        scTable.ID,
> 					ColumnIDs: colIDs,
> 					ByID:      true,
> 				})
> 				if err := descsCol.WriteDescToBatch(ctx, kvTrace, tbl, b); err != nil {
> 					return err
> 				}
> 			}
> ```
something smells here. These sets can overlap, can't they? Can we do a little set math and only remove the now removed ones and only add the now added ones? Otherwise we're going to potentially put the delete and write into the same batch and that feels bizarre to me. 
</blockquote></details>

Fixed.
___
*[pkg/sql/catalog/tabledesc/validate.go, line 161 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70632#-MkJfGvY7Q8rcXXEuCst:-MulNJ6u4rnMK71GbMo0:b-d2pxzl) ([raw file](https://github.com/cockroachdb/cockroach/blob/7de5ac7b9e98d9f812043f27a96a017dc930fb00/pkg/sql/catalog/tabledesc/validate.go#L161)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

FWIW this also affects regular tables (and sequences!) which are depended on by views.

Consider
```sql
CREATE SEQUENCE s;
CREATE TABLE t (i INT PRIMARY KEY DEFAULT (nextval('s')));
CREATE VIEW v AS SELECT nextval('s') FROM t;
```

`v` will depend on both `t` and `s`.
`s` will be depended on by `t` and `v`.

Now for the gross part:
`t` will depend on depended on by `v` but, it does not mark it self as depending on for `s`, that will only show up in the `UsesSequenceIDs` of the column.

So, yeah, not sure this totally works. 
</blockquote></details>

In the end, I had to relax a lot of the validation checks. What we actually end up doing to the descriptors right now doesn't make a whole lot of sense, and straightening that out is going to be quite a big deal, out of scope for this PR.
___
*[pkg/sql/logictest/testdata/logic_test/sequences, line 1938 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70632#-MpI3sOx6rVAGczNpLdy:-MulNxl10-F-LslX0mah:bna6arf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f2d2723c4b73e8f0daaad47b17afb9dc4ea21d4/pkg/sql/logictest/testdata/logic_test/sequences#L1938)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

did you also want to do some dropping and make sure things were still okay?
</blockquote></details>

Done, I think. I added a lot more testing since you last looked at this, but most of it is in the `tabledesc` unit tests. Please lmk what kind of test cases would be useful to add here, if applicable. I'm a bit out of touch as I'm typing this.

**Review by ajwerner — APPROVED** [review]
:lgtm:

Filed https://github.com/cockroachdb/cockroach/issues/76137 because I was curious and turns out it's buggy. 

> Reviewed 6 of 12 files at r5, 18 of 18 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70632#-:-MvHTu5w5BJk2MxXuTLn:b8tcwxs)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @postamar)

___
*[pkg/sql/catalog/descs/validate.go, line 107 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/70632#-MvHRzk84X_1ZDbZJ664:-MvHRzk84X_1ZDbZJ665:b-nxff4) ([raw file](https://github.com/cockroachdb/cockroach/blob/be17ab9b583077577a22c1853124f3fdd82cffae/pkg/sql/catalog/descs/validate.go#L107)):*
> ```Go
> 	ctx context.Context, id descpb.ID,
> ) (catalog.Descriptor, error) {
> 	if uc := c.tc.uncommitted.getByID(id); uc != nil {
> ```

heh I saw this the other day and thought the same thing

**Review by ajwerner — APPROVED** [review]
Should we file more issues to follow up on some of this? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70632#-:-MvHTxMF2ibX2QN0Z9Wu:bo45gnr)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @postamar)

**Comment by postamar** [comment]
Thanks for the review.

There's a whole epic's worth of issues, which I'll file shortly, it's in my TODO list. Fixing these will involve a migration, which we won't be doing in this release anyway.

**Pull request merged**
