### PR TITLE
tsearch: add stemming and stopword elimination for several languages

### PR DESCRIPTION
**Pull request by jordanlewis**
Updates: #41288
Epic: CRDB-22357
First commit is #92966.

    This commit adds stopword elimination for text search. The languages
    supported are the same ones that Postgres does. The stopword lists were
    copied from Postgres commit e757080e041214cf6983e3e77ef01e83f1371d72.

    Also, add snowball stemming provided by the blevesearch snowball
    stemming library.

    Release note (sql change): add stemming and stopword eliminating text
    search configurations for English, Danish, Dutch, Finnish, French,
    German, Hungarian, Italian, Norwegian, Portuguese, Russian, Spanish,
    Swedish, and Turkish.

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
Nice!

> Reviewed 9 of 9 files at r1, 2 of 2 files at r2, 25 of 25 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97677#-:-NPJax_h1kMaYhdU-AZl:b-83sjoh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rafiss)

___
*[`-- commits` line 24 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97677#-NPJVyauBO6N-yZk845M):*
Did you check whether they were updated since then?
___
*[`pkg/util/tsearch/tsquery.go` line 505 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97677#-NPJZXag9iTqahktNFzQ:-NPJZXag9iTqahktNFzR:b-gqgbhk) ([raw file](https://github.com/cockroachdb/cockroach/blob/abdc96e10d6f5c721a306236788f8b11646878a2/pkg/util/tsearch/tsquery.go#L505)):*
> ```Go
> 				foundStopwords = true
> 				lexeme = ""
> 			}
> ```

`lexeme` should already be "", right?
___
*[`pkg/util/tsearch/tsquery.go` line 531 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97677#-NPJak5N9KS_JiFbLcDr:-NPJak5N9KS_JiFbLcDs:b-gbnux7) ([raw file](https://github.com/cockroachdb/cockroach/blob/abdc96e10d6f5c721a306236788f8b11646878a2/pkg/util/tsearch/tsquery.go#L531)):*
> ```Go
> }
> 
> func cleanupStopword(node *tsNode) (ret *tsNode, lAdd int, rAdd int) {
> ```

Can you add a comment to explain what this function is doing?
___
*[`pkg/util/tsearch/tsquery.go` line 548 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97677#-NPJ__He05WKuskfMHo9:-NPJ__He05WKuskfMHoA:b-h3tgty) ([raw file](https://github.com/cockroachdb/cockroach/blob/abdc96e10d6f5c721a306236788f8b11646878a2/pkg/util/tsearch/tsquery.go#L548)):*
> ```Go
> 	}
> 
> 	var llAdd, lrAdd, rlAdd, rrAdd int
> ```

These rights and lefts are confusing .. any opportunity for some ascii art to make this clearer?
___
*[`pkg/util/tsearch/tsvector.go` line 327 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97677#-NPJYPFg-vfVibN33HLB:-NPJYPFg-vfVibN33HLC:b-96c5ak) ([raw file](https://github.com/cockroachdb/cockroach/blob/abdc96e10d6f5c721a306236788f8b11646878a2/pkg/util/tsearch/tsvector.go#L327)):*
> ```Go
> // routines like to_tsvector and to_tsquery.
> // It can return false in the second parameter to indicate a stopword was found.
> func TSLexize(config string, token string) (lexeme string, ok bool, err error) {
> ```

How about changing `ok` to something more self-documenting? e.g. `hasStopwords`? (or `hasNoStopwords`)
___
*[`pkg/util/tsearch/tsvector.go` line 362 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97677#-NPJZBtaBlcaJ12UhezQ:-NPJZBtaBlcaJ12UhezR:b5yomfc) ([raw file](https://github.com/cockroachdb/cockroach/blob/abdc96e10d6f5c721a306236788f8b11646878a2/pkg/util/tsearch/tsvector.go#L362)):*
> ```Go
> 
> 		term := tsTerm{lexeme: lexeme}
> 		term.lexeme = lexeme
> ```

I don't think you need this line anymore
___
*[`pkg/sql/sem/eval/testdata/eval/tsearch` line 346 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97677#-NPJaYul-Id8DujZEMe2:-NPJaYul-Id8DujZEMe3:b-fgrc2p) ([raw file](https://github.com/cockroachdb/cockroach/blob/abdc96e10d6f5c721a306236788f8b11646878a2/pkg/sql/sem/eval/testdata/eval/tsearch#L346)):*
> ```
> to_tsquery('english', 'foo <-> a <-> the <-> bar')
> ----
> 'foo' <3> 'bar'
> ```

how about adding a few tests for other languages besides English?

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97677)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @rytaft)

___
*[`-- commits` line 24 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97677#-NPJVyauBO6N-yZk845M):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Did you check whether they were updated since then?
</blockquote></details>

Yes, these are up to date. That commit is a very recent one off of their main branch that I used for this purpose.
___
*[`pkg/util/tsearch/tsquery.go` line 505 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97677#-NPJZXag9iTqahktNFzQ:-NQXk8cMDHZr3Z9gBPAS:beu4u9y) ([raw file](https://github.com/cockroachdb/cockroach/blob/abdc96e10d6f5c721a306236788f8b11646878a2/pkg/util/tsearch/tsquery.go#L505)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

`lexeme` should already be "", right?
</blockquote></details>

Good point, Done.
___
*[`pkg/util/tsearch/tsquery.go` line 531 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97677#-NPJak5N9KS_JiFbLcDr:-NQXkmUk9GaXqW2IvC5R:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/abdc96e10d6f5c721a306236788f8b11646878a2/pkg/util/tsearch/tsquery.go#L531)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Can you add a comment to explain what this function is doing?
</blockquote></details>

Done.
___
*[`pkg/util/tsearch/tsquery.go` line 548 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97677#-NPJ__He05WKuskfMHo9:-NQXnb3h4I3wUcwVqWHj:b8lktij) ([raw file](https://github.com/cockroachdb/cockroach/blob/abdc96e10d6f5c721a306236788f8b11646878a2/pkg/util/tsearch/tsquery.go#L548)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

These rights and lefts are confusing .. any opportunity for some ascii art to make this clearer?
</blockquote></details>

I augmented the function with the corresponding comments from the Postgres source code, which I think is as good as we're going to get. I'll be honest, I don't completely understand how this logic works. The purpose of this code is to propagate changes to the followedby number (the `n` in `<n>`, indicating # of tokens separating the left from the right) after removing a stopword. So the llAdd and lrAdd are the left and right adjustments propagated from the left child, likewise for the rlAdd rrAdd. I think the new comments should help.
___
*[`pkg/util/tsearch/tsvector.go` line 327 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97677#-NPJYPFg-vfVibN33HLB:-NQXo7Xs9Yy_LuNNiRKw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/abdc96e10d6f5c721a306236788f8b11646878a2/pkg/util/tsearch/tsvector.go#L327)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

How about changing `ok` to something more self-documenting? e.g. `hasStopwords`? (or `hasNoStopwords`)
</blockquote></details>

Done.
___
*[`pkg/util/tsearch/tsvector.go` line 362 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97677#-NPJZBtaBlcaJ12UhezQ:-NQXoK_E6ku4yHu-rY__:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/abdc96e10d6f5c721a306236788f8b11646878a2/pkg/util/tsearch/tsvector.go#L362)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I don't think you need this line anymore
</blockquote></details>

Done.
___
*[`pkg/sql/sem/eval/testdata/eval/tsearch` line 346 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/97677#-NPJaYul-Id8DujZEMe2:-NQXoP1_4uUhtrjQF6QW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/abdc96e10d6f5c721a306236788f8b11646878a2/pkg/sql/sem/eval/testdata/eval/tsearch#L346)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

how about adding a few tests for other languages besides English?
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
:lgtm: thanks!

> Reviewed 31 of 31 files at r4, 31 of 31 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97677#-:-NR-VQgYDdBtDSlYqefx:brfqlux)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss)

**Comment by jordanlewis** [comment]
Woohoo, TFTR!

bors r+

**Pull request merged**
