### PR TITLE
util/tracer: Add DISABLE_TRACER env variable.

### PR DESCRIPTION
**Pull request by petermattis**
Tracing every operation has a very noticeable performance impact. This
is a hammer to disble it. We need to either optimize tracing, or make it
sample only a fraction of operations or both.

```
name                   old time/op  new time/op  delta
Insert1_Cockroach-8     584µs ± 1%   492µs ± 1%  -15.86%    (p=0.000 n=9+7)
Insert10_Cockroach-8    965µs ± 1%   883µs ± 1%   -8.46%   (p=0.000 n=9+10)
Insert100_Cockroach-8  4.61ms ± 1%  4.52ms ± 1%   -1.95%  (p=0.000 n=10+10)
Update1_Cockroach-8    1.37ms ± 1%  1.19ms ± 1%  -13.63%  (p=0.000 n=10+10)
Update10_Cockroach-8   8.48ms ± 1%  6.85ms ± 1%  -19.24%   (p=0.000 n=9+10)
Update100_Cockroach-8  80.4ms ± 1%  64.8ms ± 0%  -19.39%   (p=0.000 n=10+9)
Delete1_Cockroach-8    1.53ms ± 4%  1.51ms ± 1%   -1.85%  (p=0.004 n=10+10)
Delete10_Cockroach-8   2.64ms ± 1%  2.39ms ± 1%   -9.65%   (p=0.000 n=9+10)
Delete100_Cockroach-8  11.9ms ± 3%  11.8ms ± 1%   -1.27%   (p=0.028 n=10+9)
Scan1_Cockroach-8       375µs ± 2%   303µs ± 0%  -19.13%   (p=0.000 n=10+9)
Scan10_Cockroach-8      432µs ± 1%   356µs ± 1%  -17.48%  (p=0.000 n=10+10)
Scan100_Cockroach-8     866µs ± 1%   773µs ± 1%  -10.77%  (p=0.000 n=10+10)
```

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4043)

### CODE REVIEW

**Comment by petermattis** [comment]
FYI, @dt actually found this performance problem.

**Comment by tamird** [comment]
LGTM

**Comment by dt** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[util/tracer/tracer.go, line 143 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4043#-K9SbjiM0UQwWwhvBYTk:-K9SbjiM0UQwWwhvBYTl:538227962) ([raw file](https://github.com/cockroachdb/cockroach/blob/796ee762c7efdb09618b9eb723df5e0e3aa63f69/util/tracer/tracer.go#L143)):*
There's a nil-check and return just below this too -- for my benchmarking I just moved the defer below that one, rather than checking twice.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4043)*

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[util/tracer/tracer.go, line 143 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4043#-K9SbjiM0UQwWwhvBYTk:-K9SmeXoOIwVlpulInP4:-262486151) ([raw file](https://github.com/cockroachdb/cockroach/blob/796ee762c7efdb09618b9eb723df5e0e3aa63f69/util/tracer/tracer.go#L143)):*
Ah, didn't notice. Will fix.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4043)*

**Pull request merged**
