### PR TITLE
ts: remove all the pointers

### PR DESCRIPTION
**Pull request by tamird**
This changes nullability of `repeated` proto fields, but that doesn't affect how they are marshalled.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5803)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm:

Was this motivated by anything?

---

Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[ts/timeseries.go, line 68 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5803#-KEHSh_CuKSlI0GAPqEf:-KEHSh_CuKSlI0GAPqEg:1520153282) ([raw file](https://github.com/cockroachdb/cockroach/blob/d085ea550c328e54832a4d64e869d91f732a58af/ts/timeseries.go#L68)):*
Add: `because we maintain pointers to its elements in the result  and resultByKeyTime maps`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5803#-:-KEHSsgEC65cOj7T_yZ6:236157405)*

**Comment by tamird** [comment]
Came upon it while auditing some other protos.

---

Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[ts/timeseries.go, line 68 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5803#-KEHSh_CuKSlI0GAPqEf:-KEHXADW8cwGjzHM5XC0:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/d085ea550c328e54832a4d64e869d91f732a58af/ts/timeseries.go#L68)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5803#-:-KEHXBQGuk8cye5MJubA:83946781)*

**Comment by tamird** [comment]
merging on red because only failure was acceptance `rejecting command with timestamp in the future: 1459526723128924882 (382.524958ms ahead)`

**Comment by tschottdorf** [comment]
... and because you don't overlook other build errors in the logs (which is
something that happens regularly). Just putting this out there so that
others don't routinely do this as well. Letting the tests run again is
always an option.

**Comment by tamird** [comment]
Yes, I checked that only one container actually had any failures.

**Pull request merged**
