### PR TITLE
opt: eliminate assignment casts with identical source and target types

### LINKED ISSUE #73450: sql: do not elide casts
We elide casts during type checking and with the `EliminateCast` normalization rule. This is invalid because we perform no validation to ensure that the width of a placeholder's value fits in the placeholder's type. As a result, this elision causes incorrect behavior.

In Postgres:

```
marcus=# CREATE TABLE t (c CHAR);
CREATE TABLE

marcus=# INSERT INTO t VALUES ('f');
INSERT 0 1

marcus=# SELECT * FROM t WHERE c = 'foo'::CHAR;
 c
---
 f
(1 row)

marcus=# PREPARE s AS SELECT * FROM t WHERE c = $1::CHAR;
PREPARE

marcus=# EXECUTE s('foo');
 c
---
 f
(1 row)
```

In CRDB:

```
defaultdb> CREATE TABLE t (c CHAR);
CREATE TABLE

defaultdb> INSERT INTO t VALUES ('f');
INSERT 1

defaultdb> SELECT * FROM t WHERE c = 'foo'::CHAR;
  c
-----
  f
(1 row)

defaultdb> PREPARE s AS SELECT * FROM t WHERE c = $1::CHAR;
PREPARE

defaultdb> EXECUTE s('foo');
  c
-----
(0 rows)
```

### PR DESCRIPTION
**Pull request by mgartner**
#### sql: remove type modifiers from placeholder types

The width and precision of placeholder values are not known during
PREPARE, therefore we remove any type modifiers from placeholder types
during type checking so that a value of any width will fit within the
palceholder type.

Note that this change is similar to the changes made in #70722 to
placeholder type checking that were later reverted in #72793. In #70722
the type OIDs of placeholders could be altered, e.g., a placeholder
originally with type `INT2` would be converted to an `INT`. In this
commit, type OIDs of placeholders are not changing, only type modifiers
are.

This commit should allow some logic added in #72793 to be simplified or
removed entirely.

Release note: None

#### opt: eliminate assignment casts with identical source and target types

The `EliminateAssignmentCast` rule has been combined with the
`EliminateCast` rule. Now an assignment cast is eliminated if the source
and target type are identical. This now possible thanks to some changes
to type resolution, including:

  1. Placeholder types are resolved with unspecified type modifiers.
     This ensures that assignment casts won't be eliminated if the a
     placeholder value does not conform to the target type's modifiers.

  2. When constant integer `NumVal`s are resolved as a typed-value,
     they are validated to ensure they fit within their type's width.
     There may be more types we need to perform similar validation for,
     such as floats (see #73743).

  3. Columns in values expressions with values that have non-identical
     types but the same type OID will be typed with type modifiers. For
     example, if a values expression has a CHAR(1) value and a CHAR(3)
     value in the same column, the column will be typed as a CHAR
     without an explicit width.

  4. Type modifiers are now correctly omitted from array content types
     when arrays contain constants.

Fixes #73450

Release note (bug fix): A bug has been fixed that caused incorrect
evaluation of placeholder values in EXECUTE statements. The bug
presented when the PREPARE statement cast a placeholder value, for
example `PREPARE s AS SELECT $1::INT2`. If the assigned value for `$1`
exceeded the maximum width value of the cast target type, the result
value of the cast could be incorrect. This bug has been present since
version 19.1 or earlier.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
Fingers crossed this works without issues :)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73762#-:-MqusK0K391SjWitWpi6:b-kkcfmv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @otan)

___
*[pkg/sql/opt/norm/rules/scalar.opt, line 80 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73762#-MqusGJ911W55mHQDKuu:-MqusGJ911W55mHQDKuv:bqgvjmn) ([raw file](https://github.com/cockroachdb/cockroach/blob/d411bd0cb167370b394c5e3a70ad201d0b951a61/pkg/sql/opt/norm/rules/scalar.opt#L80)):*
> ```
>     $targetTyp:* &
>         (HasColType $input $targetTyp) &
>         (AssignmentCastIsNoop $targetTyp)
> ```

[nit] We should remove this function
___
*[pkg/sql/sem/tree/type_check.go, line 1621 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73762#-MquqiBDAg6aTke9Z2hs:-MquqiBDAg6aTke9Z2ht:b-suh9as) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4596bf9e000c600b4cd891923101cd9e8e935f3/pkg/sql/sem/tree/type_check.go#L1621)):*
> ```Go
> 			// later, we cast the input value (whose type is the expected type) to the
> 			// desired type here.
> 			typ = desired
> ```

This seems sketchy - do you think this still makes sense? Does the cast the comment mentions still exist? (AFAICT no, it used to exist in the old equivalent of `AssignPlaceholders`)    By the way, I'm surprised `AssignPlaceholders` doesn't make any assertions w.r.t the type.
___
*[pkg/sql/sem/tree/type_check.go, line 1549 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73762#-MqurwkP3QHVHovW0QfR:-MqurwkQ3txBenlhAJC6:b-x2ubh7) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a13053ebef71837bee89215ed09256ce80f6eab/pkg/sql/sem/tree/type_check.go#L1549)):*
> ```Go
> 	desiredParam := types.Any
> 	if desired.Family() == types.ArrayFamily {
> 		desiredParam = desired.ArrayContents().WithoutTypeModifiers()
> ```

This seems random, can you explain in a comment?

**Review by otan — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, 1 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73762)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @otan, and @RaduBerinde)

___
*[pkg/sql/sem/tree/type_check.go, line 1549 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73762#-MqurwkP3QHVHovW0QfR:-MqvNfQa1jdGfLS67tPJ:by8yy0n) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a13053ebef71837bee89215ed09256ce80f6eab/pkg/sql/sem/tree/type_check.go#L1549)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This seems random, can you explain in a comment?
</blockquote></details>

mmm yes +1
___
*[pkg/sql/types/types.go, line 1266 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73762#-MqvLp9U6H0bsYHDlvtn:-MqvLp9U6H0bsYHDlvto:bke3rdu) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4596bf9e000c600b4cd891923101cd9e8e935f3/pkg/sql/types/types.go#L1266)):*
> ```Go
> 			return t
> 		}
> 		newT := *t
> ```

my fear here is that we'll miss something when adding a new type. should we explicitly either catch all other families and panic otherwise, and/or use `MakeScalar`/some mapping from `Oid` to "default type" (e.g. types.Int, types.TimestampTZ) which should make the "empty" versions of these types?

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73762)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @RaduBerinde)

___
*[pkg/sql/opt/norm/rules/scalar.opt, line 80 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73762#-MqusGJ911W55mHQDKuu:-Mqz2lQVBBjyVxb96hSk:boj1qgt) ([raw file](https://github.com/cockroachdb/cockroach/blob/d411bd0cb167370b394c5e3a70ad201d0b951a61/pkg/sql/opt/norm/rules/scalar.opt#L80)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] We should remove this function
</blockquote></details>

Good catch. Done.
___
*[pkg/sql/sem/tree/type_check.go, line 1621 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73762#-MquqiBDAg6aTke9Z2hs:-Mqz493O22nuykyMM0de:b-gyrd4q) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4596bf9e000c600b4cd891923101cd9e8e935f3/pkg/sql/sem/tree/type_check.go#L1621)):*

> This seems sketchy - do you think this still makes sense? Does the cast the comment mentions still exist?

I believe this comment refers to the cast added in [`Placeholder.Eval`](https://github.com/cockroachdb/cockroach/blob/7780e1e085dbfa849defcef63b5138e80c18a17b/pkg/sql/sem/tree/eval.go#L4731-L4740). I'm not convinced it's necessary anymore, and in some cases may not be valid (notice the TODO). I can explore removing in a future commit.

> By the way, I'm surprised AssignPlaceholders doesn't make any assertions w.r.t the type.

The assertions happen earlier on in [`planner.fillInPlaceholders`](https://github.com/cockroachdb/cockroach/blob/01ca1e53e2c84049abcf0f3d3acefa4bbbdb0db9/pkg/sql/execute.go#L55-L57). `schemaexpr.SanitizeVarFreeExpr` calls `tree.TypeCheck` which eventually calls `Constant.ResolveAsType` on the placeholder values. Notice the change in the second commit to `NumVal.ResolveAsType` which adds missing assertions for integer constants.

I get the feeling all this type-related logic at the conn_executor level is from pre-CBO times and it doesn't really belong there anymore. But I don't have enough experience with the conn_executor to have strong opinions yet.
___
*[pkg/sql/sem/tree/type_check.go, line 1549 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73762#-MqurwkP3QHVHovW0QfR:-Mr-huOf5cCyL1rNfV4L:b8bxk5v) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a13053ebef71837bee89215ed09256ce80f6eab/pkg/sql/sem/tree/type_check.go#L1549)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

mmm yes +1
</blockquote></details>

I've reverted this in favor of a change in `typeCheckSameTypedConsts`, where I've explained with a comment. The goal is to correctly type the literal array below as `DECIMAL[]`, and not `DECIMAL(10,0)[]` which causes an assignment cast to be elided and an incorrect value inserted.

```sql
CREATE TABLE t (a DECIMAL(10,0)[]);
INSERT INTO t VALUES (ARRAY[2.88, NULL, 15]);
```
___
*[pkg/sql/types/types.go, line 1266 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73762#-MqvLp9U6H0bsYHDlvtn:-Mr-O9zj1KJeLdFPohmm:b-vv3rhi) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4596bf9e000c600b4cd891923101cd9e8e935f3/pkg/sql/types/types.go#L1266)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

my fear here is that we'll miss something when adding a new type. should we explicitly either catch all other families and panic otherwise, and/or use `MakeScalar`/some mapping from `Oid` to "default type" (e.g. types.Int, types.TimestampTZ) which should make the "empty" versions of these types?
</blockquote></details>

Good point. I don't think catching all families is sufficient - if a type were added to a family we'd have a similar problem. I've change this function to use type OIDs, let me know what you think.

**Review by otan — APPROVED** [review]
> Reviewed 11 of 19 files at r3, 1 of 18 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73762)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @RaduBerinde)

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73762)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @RaduBerinde)

___
*[pkg/sql/types/types.go, line 1266 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73762#-MqvLp9U6H0bsYHDlvtn:-Mr3M5YC5ZiJszdklBcK:b-qlpoqc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4596bf9e000c600b4cd891923101cd9e8e935f3/pkg/sql/types/types.go#L1266)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Good point. I don't think catching all families is sufficient - if a type were added to a family we'd have a similar problem. I've change this function to use type OIDs, let me know what you think.
</blockquote></details>

It already caught the new void type :wink:

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
