### PR TITLE
cli: debug zip for in-process tenants

### PR DESCRIPTION
**Pull request by aadityasondhi**
This patch changes debug.zip to support querying debug data for multiple
in-process tenants. It relies on a newly defined `ListTenants` rpc
endpoint defined on the system admin server. It then individually
queries the rpc and sql endpoints of all tenants returned by that
endpoint.

The new directory structure now includes a tenants sub-directory in tghe
root debug directory. This directory contains a seperate sub-directory
for each non-system tenant:
```
debug/tenants/[tenant-name]/...
```
The system tenant files remain in the root directory to allow for
backwards compatibility with any scripts that depend on the debug zip
output.

Currently this works with in-process app tenants having seperate rpc
ports as the system tenant. In the future when these ports are unified,
debug.zip will need to be changed to follow the new connection process.

Epic: CRDB-18407

Release note (cli change): The debug zip command now supports querying
data from clusters running in-process tenants. Data from these tenants
is dumped into a new `tenants` sub-directory in the root directory. The
files for the system tenant remain unchanged and are still dumped into
the root-level `debug` directory. The UX of the command remains
unchanged. If the target cluster contains multiple tenants, debug zip
will automatically discover these tenants and query them for data.

### CODE REVIEW

**Review by dhartunian — COMMENTED** [review]
> Reviewed 3 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96393)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi and @knz)

___
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96393#-NNHmOyT8OQmJ_VrvDZs):*
is the tenant-name nesting omitted when running on a non-multitenant server? I'd like to make sure we preserve existing debug.zip functionality with no changes since people script against these files.
___
*[`pkg/cli/zip_cluster_wide.go` line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96393#-NNHnwPa76hfovt93222:-NNHnwPa76hfovt93223:b-qadvdg) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6a32ed664a3cb6eb542277b867ddc4ce25d53d4/pkg/cli/zip_cluster_wide.go#L122)):*
> ```Go
> 		})
> 		if ni.nodesStatusResponse != nil {
> 			if cErr := zc.z.createJSONOrError(s, debugBase+"/nodes.json", ni.nodesStatusResponse, err); cErr != nil {
> ```

why don't we use the node status response here anymore?
___
*[`pkg/cli/zip_cluster_wide.go` line 198 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96393#-NNHo6PV8sJqoS1lZTGn:-NNHo6PV8sJqoS1lZTGo:bi7lrfj) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fefc3f16b08cc3742b02e6f5dcab234682a4ccb/pkg/cli/zip_cluster_wide.go#L198)):*
> ```Go
> // For regular storage servers, the more detailed NodesResponse is
> // returned along with the nodesListResponse.
> func (zc *debugZipContext) nodesInfo(ctx context.Context) (ni nodesInfo, _ error) {
> ```

similar to above, the use of the `NodesRequest` should stay. if the app tenant throws an error that's fine, but the system tenant should include that info.

**Review by aadityasondhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96393)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @knz)

___
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96393#-NNHmOyT8OQmJ_VrvDZs):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

is the tenant-name nesting omitted when running on a non-multitenant server? I'd like to make sure we preserve existing debug.zip functionality with no changes since people script against these files.
</blockquote></details>

I see. I can make that change. So if the list contains only one tenant (the system tenant), you are suggesting we omit the system tenant from the dir structure?
___
*[`pkg/cli/zip_cluster_wide.go` line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96393#-NNHnwPa76hfovt93222:-NNHrZ7wDrTNm-Dlhqvy:b5zj5fa) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6a32ed664a3cb6eb542277b867ddc4ce25d53d4/pkg/cli/zip_cluster_wide.go#L122)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

why don't we use the node status response here anymore?
</blockquote></details>

The discussion for this decision is here: https://cockroachlabs.slack.com/archives/C02HWA24541/p1674164811376769
___
*[`pkg/cli/zip_cluster_wide.go` line 198 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96393#-NNHo6PV8sJqoS1lZTGn:-NNHrbqj9F4ssYi-q4Id:b-q64pkt) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fefc3f16b08cc3742b02e6f5dcab234682a4ccb/pkg/cli/zip_cluster_wide.go#L198)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

similar to above, the use of the `NodesRequest` should stay. if the app tenant throws an error that's fine, but the system tenant should include that info.
</blockquote></details>

See above.

**Review by abarganier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96393)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @dhartunian, and @knz)

___
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96393#-NNHmOyT8OQmJ_VrvDZs):*
> suggesting we omit the system tenant from the dir structure?
That's how I'd do it - so if there's just the system tenant it would be...
```
debug/...
```

Otherwise, use the `debug/<tenant name>/` structure. This makes it so the structure only changes if necessary.
___
*[`pkg/cli/zip_cluster_wide.go` line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96393#-NNHnwPa76hfovt93222:-NNI4x_PDwdT4TZL4IqJ:b-760m8i) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6a32ed664a3cb6eb542277b867ddc4ce25d53d4/pkg/cli/zip_cluster_wide.go#L122)):*
<details><summary><i>Previously, aadityasondhi (Aaditya Sondhi) wrote…</i></summary><blockquote>

The discussion for this decision is here: https://cockroachlabs.slack.com/archives/C02HWA24541/p1674164811376769
</blockquote></details>

I don't think I understand the reasoning based on this thread. The `NodesResponse` contained a *lot* of information relevant to the system tenant/KV layer for each node that would end up in `nodes.json`, such as:
- Node descriptors
- A full dump of node metrics & their values
- Store statuses
- Env vars

I expect that TSE would see this removal as a loss in observability. 

IIRC, `NodesList` was added back when we originally made the debug.zip work for multi-tenant (at the time, those tenants had their own processes). `Nodes` wasn't implemented for these tenants and we needed a new endpoint to get some basic information about each active SQL instance (instance ID, RPC addr, SQL addr) so we knew where to request data from for the tenant. 

This is why the local `nodesInfo` struct was created - we would attempt one request to `Nodes()` for node information, and if that failed due to a `codes.Unimplemented` error, we'd try `NodesList()` instead since such an error likely indicated that the debug zip was being run against a secondary tenant. 

So while it may be acceptable to consolidate how we fetch the necessary information (instance ID, RPC/SQL addresses) to make requests to, I'm not so sure all this information in `nodes.json` is something TSE's are willing to part ways with when it comes to the system tenant's debug.zip bundle. 

---

I'd like to better understand the problem - can you help clarify a couple things for me?

Based on the thread, it sounds like `NodesList()` was returning incomplete information for the app tenant, right? Meanwhile, the system tenant was able to return a full response from `NodesList()`. A couple questions I have are:

1. Can the system tenant not make use of the `Nodes()` endpoint anymore? The way the code was structured, the `Nodes()` endpoint is preferred, and we fall back to `NodesList()` if `Nodes()` is unimplemented. Were we hitting this `codes.Unimplemented` error for the system tenant for the `Nodes()` endpoint nowadays?
2. Do we know *why* `NodesList()` was returning incomplete data for the secondary app tenant?  
3. The thread's OP mentions that `NodesList()` returned incomplete data for the secondary app tenant, but in the end, we make use of it anyway. What changed that caused `NodesList()` to now return sufficient data for the app tenant? You mention that removing the dependency on `Nodes()` fixed the issue, but I don't think I understand how these two separate gRPC requests impact each other.
___
*[`pkg/cli/testdata/zip/partial1` line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96393#-NNI2xoODX9NP5aBdtFy:-NNI2xoP6g9q-Qq5XvQe:baefeq4) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fefc3f16b08cc3742b02e6f5dcab234682a4ccb/pkg/cli/testdata/zip/partial1#L81)):*
> ```
> [node 1 - tenant system] retrieving SQL data for crdb_internal.active_range_feeds... writing output: debug/system/nodes/1/crdb_internal.active_range_feeds.txt... done
> [node 1 - tenant system] retrieving SQL data for crdb_internal.feature_usage... writing output: debug/system/nodes/1/crdb_internal.feature_usage.txt... done
> [node 1 - tenant system] retrieving SQL data for crdb_internal.gossip_alerts... writing output: debug/system/nodes/1/crdb_internal.gossip_alerts.txt... done
> ```

Is it possible to update some of these tests to run against a cluster with an in-process app tenant? Or is the test infra not there yet? 



_Code quote:_
```
[node 1 - tenant system]
```

**Review by knz — COMMENTED** [review]
Overall I think this is excellent work.

> Reviewed 3 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96393#-:-NNN33A10-o9htVn0l4W:bb24kzm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @abarganier, and @dhartunian)

___
*[`pkg/cli/zip.go` line 254 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96393#-NNN1iag-29eJRDv25_T:-NNN1iag-29eJRDv25_U:bejx99c) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fefc3f16b08cc3742b02e6f5dcab234682a4ccb/pkg/cli/zip.go#L254)):*
> ```Go
> 				firstNodeSQLConn: sqlConn,
> 				sem:              semaphore.New(zipCtx.concurrency),
> 				prefix:           debugBase + "/" + tenant.TenantName,
> ```

As mentioned at top, only add the tenant prefix if not looking at the system tenant.
___
*[`pkg/cli/zip_cluster_wide.go` line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96393#-NNHnwPa76hfovt93222:-NNN1z567EdnFh3poyCY:b6ijcei) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6a32ed664a3cb6eb542277b867ddc4ce25d53d4/pkg/cli/zip_cluster_wide.go#L122)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

I don't think I understand the reasoning based on this thread. The `NodesResponse` contained a *lot* of information relevant to the system tenant/KV layer for each node that would end up in `nodes.json`, such as:
- Node descriptors
- A full dump of node metrics & their values
- Store statuses
- Env vars

I expect that TSE would see this removal as a loss in observability. 

IIRC, `NodesList` was added back when we originally made the debug.zip work for multi-tenant (at the time, those tenants had their own processes). `Nodes` wasn't implemented for these tenants and we needed a new endpoint to get some basic information about each active SQL instance (instance ID, RPC addr, SQL addr) so we knew where to request data from for the tenant. 

This is why the local `nodesInfo` struct was created - we would attempt one request to `Nodes()` for node information, and if that failed due to a `codes.Unimplemented` error, we'd try `NodesList()` instead since such an error likely indicated that the debug zip was being run against a secondary tenant. 

So while it may be acceptable to consolidate how we fetch the necessary information (instance ID, RPC/SQL addresses) to make requests to, I'm not so sure all this information in `nodes.json` is something TSE's are willing to part ways with when it comes to the system tenant's debug.zip bundle. 

---

I'd like to better understand the problem - can you help clarify a couple things for me?

Based on the thread, it sounds like `NodesList()` was returning incomplete information for the app tenant, right? Meanwhile, the system tenant was able to return a full response from `NodesList()`. A couple questions I have are:

1. Can the system tenant not make use of the `Nodes()` endpoint anymore? The way the code was structured, the `Nodes()` endpoint is preferred, and we fall back to `NodesList()` if `Nodes()` is unimplemented. Were we hitting this `codes.Unimplemented` error for the system tenant for the `Nodes()` endpoint nowadays?
2. Do we know *why* `NodesList()` was returning incomplete data for the secondary app tenant?  
3. The thread's OP mentions that `NodesList()` returned incomplete data for the secondary app tenant, but in the end, we make use of it anyway. What changed that caused `NodesList()` to now return sufficient data for the app tenant? You mention that removing the dependency on `Nodes()` fixed the issue, but I don't think I understand how these two separate gRPC requests impact each other.

</blockquote></details>

Let's make this thread simpler.

1) I was the one requesting to use only one code path in any case to *enumerate* the nodes, using `NodesList()`.  Enumerating the cluster using `NodesList()`  *should* always be correct (both on system tenant and secondary server). If this is not true, we need to work tomake it true. To me, `NodesList()` is valid on system tenant and returns a subset of the information returned by `Nodes()`. 

   The call to `NodesList()` should be done early, and a failure is severe - no enumeration, no debug zip fanout.

2) *Separately*, we should consider the `Nodes()` RPC as one of the many cluster-wide RPCs that zip *attempts* to retrieve data from, alongside rangelog / cluster settings etc. For this reason, that RPC should be included in the set of results from `makeClusterWideZipRequests` above.

   For some tenants, the result of these "best effort" RPCs will be an error; for others (most likely system tenant) it retrieves some data. This will ensure we still retrieve the node metrics etc that Alex cares about.

**Review by aadityasondhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96393)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier, @dhartunian, and @knz)

___
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96393#-NNHmOyT8OQmJ_VrvDZs):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

> suggesting we omit the system tenant from the dir structure?
That's how I'd do it - so if there's just the system tenant it would be...
```
debug/...
```

Otherwise, use the `debug/<tenant name>/` structure. This makes it so the structure only changes if necessary.
</blockquote></details>

Done.
___
*[`pkg/cli/zip.go` line 254 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96393#-NNN1iag-29eJRDv25_T:-NNwioFEBy_0g_9WtucY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fefc3f16b08cc3742b02e6f5dcab234682a4ccb/pkg/cli/zip.go#L254)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

As mentioned at top, only add the tenant prefix if not looking at the system tenant.
</blockquote></details>

Done.
___
*[`pkg/cli/zip_cluster_wide.go` line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96393#-NNHnwPa76hfovt93222:-NNwipdIB2FBjeAdT4wM:b9kdzy9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6a32ed664a3cb6eb542277b867ddc4ce25d53d4/pkg/cli/zip_cluster_wide.go#L122)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Let's make this thread simpler.

1) I was the one requesting to use only one code path in any case to *enumerate* the nodes, using `NodesList()`.  Enumerating the cluster using `NodesList()`  *should* always be correct (both on system tenant and secondary server). If this is not true, we need to work tomake it true. To me, `NodesList()` is valid on system tenant and returns a subset of the information returned by `Nodes()`. 

   The call to `NodesList()` should be done early, and a failure is severe - no enumeration, no debug zip fanout.

2) *Separately*, we should consider the `Nodes()` RPC as one of the many cluster-wide RPCs that zip *attempts* to retrieve data from, alongside rangelog / cluster settings etc. For this reason, that RPC should be included in the set of results from `makeClusterWideZipRequests` above.

   For some tenants, the result of these "best effort" RPCs will be an error; for others (most likely system tenant) it retrieves some data. This will ensure we still retrieve the node metrics etc that Alex cares about.
</blockquote></details>

Done. Debug zip now used `NodesList` for node discovery and `Nodes` as one of the many cluster-wide rpc it queries. It is expected to not work for non-system tenants and it will print the error in the file in those cases.
___
*[`pkg/cli/testdata/zip/partial1` line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96393#-NNI2xoODX9NP5aBdtFy:-NNwjJqm85yjgo2A554J:bkyn2bj) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fefc3f16b08cc3742b02e6f5dcab234682a4ccb/pkg/cli/testdata/zip/partial1#L81)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

Is it possible to update some of these tests to run against a cluster with an in-process app tenant? Or is the test infra not there yet? 
</blockquote></details>

There seems to be a known issue that I can look at separately from this PR: https://github.com/cockroachdb/cockroach/issues/77173. The tenant zip test is currently being skipped as of https://github.com/cockroachdb/cockroach/issues/89192.

**Review by abarganier — APPROVED** [review]
:lgtm: - thanks for hearing & addressing all our concerns! It's much appreciated & this turned out great. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96393#-:-NOGIIr49onxq5_ZYZgw:b-20cq4y)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi, @dhartunian, and @knz)

___
*[`pkg/cli/zip_cluster_wide.go` line 122 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96393#-NNHnwPa76hfovt93222:-NOGHzpa3kPw_Mtdtt9H:b-nkvom9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6a32ed664a3cb6eb542277b867ddc4ce25d53d4/pkg/cli/zip_cluster_wide.go#L122)):*
<details><summary><i>Previously, aadityasondhi (Aaditya Sondhi) wrote…</i></summary><blockquote>

Done. Debug zip now used `NodesList` for node discovery and `Nodes` as one of the many cluster-wide rpc it queries. It is expected to not work for non-system tenants and it will print the error in the file in those cases.
</blockquote></details>

Sounds good, thanks for addressing this @aadityasondhi! 
___
*[`pkg/cli/testdata/zip/partial1` line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96393#-NNI2xoODX9NP5aBdtFy:-NOGI6iR36fMsyWBjeXK:b-ygclc1) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fefc3f16b08cc3742b02e6f5dcab234682a4ccb/pkg/cli/testdata/zip/partial1#L81)):*
<details><summary><i>Previously, aadityasondhi (Aaditya Sondhi) wrote…</i></summary><blockquote>

There seems to be a known issue that I can look at separately from this PR: https://github.com/cockroachdb/cockroach/issues/77173. The tenant zip test is currently being skipped as of https://github.com/cockroachdb/cockroach/issues/89192.
</blockquote></details>

Ah yes, I should have been aware since I'm the one who filed the issue :sweat_smile: 

SGTM - let's leave handling of this to a separate PR.

**Review by aadityasondhi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96393)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dhartunian and @knz)

___
*[`pkg/cli/testdata/zip/partial1` line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/96393#-NNI2xoODX9NP5aBdtFy:-NOGU0830Wv8AbojZcmZ:b-gpjhvt) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fefc3f16b08cc3742b02e6f5dcab234682a4ccb/pkg/cli/testdata/zip/partial1#L81)):*
<details><summary><i>Previously, abarganier (Alex Barganier) wrote…</i></summary><blockquote>

Ah yes, I should have been aware since I'm the one who filed the issue :sweat_smile: 

SGTM - let's leave handling of this to a separate PR. 
</blockquote></details>

Based on https://github.com/cockroachdb/cockroach/pull/96553, it seems that @knz will be fixing this in a later PR.

**Comment by aadityasondhi** [comment]
TFTR!

bors r=abarganier

**Pull request merged**
