### PR TITLE
kvserver: improve slow ready message

### PR DESCRIPTION
**Pull request by tbg**
This has become significantly more informative, and notably includes a
breakdown of SSTs versus regular entries appended to the log, as well as
timings for the append/apply/commit/snap stages.

The one thing that is missing here that I think would be helpful would
be a sst/regular breakdown for entry *application*, perhaps with timings
for SST ingestion delays. However, these are rare in practice and have
their own logging, so this is more trouble than it's worth. Just knowing
what enters the raft log and at which rate entries are applied should
be more than enough to make an educated guess as to what's going on.

Real-world example from overloading a local cluster:

```
raft ready handling: 0.82s [append=0.00s, apply=0.22s, commit-batch-sync=0.59s, other=0.01s], wrote 30 KiB sync [append-ent=30 KiB (3), apply=3.0 MiB (313 in 3 batches)]; node might be overloaded
```

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
bazel [failure](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_Tests_Acceptance/5013136?buildTab=artifacts#%2Facceptance%2FTestDockerCLI) in `test_demo_node_cmds.tcl`:

```
root@127.114.70.216:26257/movr> \demo shutdown 6
node is draining... remaining: 23
node is draining... remaining: 12
node is draining... remaining: 12
node is draining... remaining: 12
node is draining... 
.220426 16:43:02.493178403 EXPECT TEST: TIMEOUT WAITING FOR "node 6 has been shutdown"
non-zero exit code: 1
```

**Review by erikgrinaker — APPROVED** [review]
Nice!

**Comment by tbg** [comment]
bors r=erikgrinaker

**Comment by tbg** [comment]
blathers backport 22.1

**Pull request merged**
