### PR TITLE
opt: refactor and test lookup join key column and expr generation

### PR DESCRIPTION
**Pull request by mgartner**
#### opt: simplify fetching outer column in CustomFuncs.findComputedColJoinEquality

Previously, `CustomFuncs.findComputedColJoinEquality` used
`CustomFuncs.OuterCols` to retrieve the outer columns of computed column
expressions. `CustomFuncs.OuterCols` returns the cached outer columns in
the expression if it is a `memo.ScalarPropsExpr`, and falls back to
calculating the outer columns with `memo.BuildSharedProps` otherwise.
Computed column expressions are never `memo.ScalarPropsExpr`s, so we use
just use `memo.BuildSharedProps` directly.

Release note: None

#### opt: make RemapCols a method on Factory instead of CustomFuncs

Release note: None

#### opt: use partial-index-reduced filters when building lookup expressions

This commit makes a minor change to `generateLookupJoinsImpl`.
Previously, equality filters were extracted from the original `ON`
filters. Now they are extracted from filters that have been reduced by
partial index implication. This has no effect on behavior because
equality filters that reference columns in two tables cannot exist in
partial index predicates, so they will never be eliminated during
partial index implication.

Release note: None

#### opt: moves some lookup join generation logic to lookup join package

This commit adds a new `lookupjoin` package. Logic for determining the
key columns and lookup expressions for lookup joins has been moved to
`lookupJoin.ConstraintBuilder`. The code was moved with as few changes
as possible, and the behavior does not change in any way. This move will
make it easier to test this code in isolation in the future, and allow
for further refactoring.

Release note: None

#### opt: generalize lookupjoin.ConstraintBuilder API

This commit makes the lookupjoin.ConstraintBuilder API more general to
make unit testing easier in a future commit.

Release note: None

#### opt: add data-driven tests for lookupjoin.ConstraintBuilder

Release note: None

#### opt: add lookupjoin.Constraint struct

The `lookupjoin.Constraint` struct has been added to encapsulate
multiple data structures that represent a strategy for constraining a
lookup join.

Release note: None

### CODE REVIEW

**Review by msirek — APPROVED** [review]
Excellent refactoring and new unit tests!   
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79911#-:-N-hxY72-W96Rm6MeaKe:bxj1352)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/lookupjoin/constraint_builder.go, line 80 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/79911#-N-hhZVg6N3rPPt_HYIk:-N-hhZVg6N3rPPt_HYIl:b-wuk091) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb70471d9106253de7ea62a4033f05fbf5c59043/pkg/sql/opt/lookupjoin/constraint_builder.go#L80)):*
> ```Go
> // return values:
> //
> //   keyCols          - A list of columns to be used as lookup join key columns.
> ```

nit: maybe indicate these are left table columns and that this is an ordered list, with columns corresponding the those in rightSideCols.
___
*[pkg/sql/opt/lookupjoin/constraint_builder_test.go, line 53 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/79911#-N-hz4ab1ZqqNvh5f2hq:-N-hz4ab1ZqqNvh5f2hr:b-143n0r) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb70471d9106253de7ea62a4033f05fbf5c59043/pkg/sql/opt/lookupjoin/constraint_builder_test.go#L53)):*
> ```Go
> //       Information about the left columns.
> //
> //     - index=(<column> [asc|desc], ...)
> ```

Since this supports `[asc|desc]` ordering, maybe a test with a range condition on a descending column would be useful.

**Review by rytaft — COMMENTED** [review]
Very nice! 

> Reviewed 1 of 1 files at r1, 5 of 5 files at r2, 1 of 1 files at r3, 8 of 8 files at r4, 3 of 3 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79911#-:-N0ETkABCElQvXp3OJ2S:b-rez0m7)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/opt/lookupjoin/constraint_builder.go, line 85 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/79911#-N0EQKh3570w3q26Sm9S:-N0EQKh3570w3q26Sm9T:b-n2qmi4) ([raw file](https://github.com/cockroachdb/cockroach/blob/73c212946dc2a5a7a4e3064e8612778c3112257f/pkg/sql/opt/lookupjoin/constraint_builder.go#L85)):*
> ```Go
> // both. If both keyCols and lookupExpr are nil, then the index cannot be used
> // for a lookup join.
> func (b *ConstraintBuilder) Build(
> ```

Any chance you can split this into two commits that will be squashed before merging? One that literally just moves code with no changes from the original lookup join code, and one that makes the remaining changes?
___
*[pkg/sql/opt/lookupjoin/constraint_builder.go, line 92 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/79911#-N0ERyuP1NJCiaQlvr8I:-N0ERyuQ7yejQMHHQxEd:b1j77po) ([raw file](https://github.com/cockroachdb/cockroach/blob/73c212946dc2a5a7a4e3064e8612778c3112257f/pkg/sql/opt/lookupjoin/constraint_builder.go#L92)):*
> ```Go
> 	inputProjections memo.ProjectionsExpr,
> 	constFilters memo.FiltersExpr,
> 	rightSideCols opt.ColList,
> ```

Do you think it's worth packaging this stuff into a new struct, `lookupjoin.Constraint`, or something like that? You could also save that for a future PR...
___
*[pkg/sql/opt/xform/join_funcs.go, line 374 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/79911#-N0ES_S97AdpcLFJuY4i:-N0ES_S97AdpcLFJuY4j:b-2bsm3m) ([raw file](https://github.com/cockroachdb/cockroach/blob/73c212946dc2a5a7a4e3064e8612778c3112257f/pkg/sql/opt/xform/join_funcs.go#L374)):*
> ```Go
> 		keyCols, lookupExpr, inputProjections, constFilters, rightSideCols :=
> 			cb.Build(index, onFilters, optionalFilters)
> 		if len(keyCols) == 0 && len(lookupExpr) == 0 {
> ```

If you make a new struct for `lookupjoin.Constraint`, this check could become a method on that struct.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79911)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/lookupjoin/constraint_builder.go, line 85 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/79911#-N0EQKh3570w3q26Sm9S:-N0Gx1ry6-JzEU6jdPFu:b-8lv5cp) ([raw file](https://github.com/cockroachdb/cockroach/blob/73c212946dc2a5a7a4e3064e8612778c3112257f/pkg/sql/opt/lookupjoin/constraint_builder.go#L85)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Any chance you can split this into two commits that will be squashed before merging? One that literally just moves code with no changes from the original lookup join code, and one that makes the remaining changes?
</blockquote></details>

I really tried to make no changes to the logic here. The logic inside `Build` is the same as the logic removed in `generateLookupJoinsImpl`, except for referencing the ConstraintBuilder fields rather than CustomFuncs fields and some additional comments. There was an intertwined section of code that created a memo.LookupJoin that I did not move here. All the helper functions are the same, except for the receiver type. I'm not really sure how to move the logic in a way that makes few changes, but I know we've been bitten by moving code in the past. Did you have a specific idea in mind? I suppose I could try doing the work in these N commits:

1. Move the core key column and lookupExpr logic into a function rather than a struct method into a separate file in the xform package. Move the helper function to the separate file too.
2. Add the ConstraintBuilder struct, adding Init, Build, and turning the helpers into methods of that struct.
3. Move the ConstraintBuilder to a separate package.
___
*[pkg/sql/opt/lookupjoin/constraint_builder.go, line 92 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/79911#-N0ERyuP1NJCiaQlvr8I:-N0GuZNr0rhnk4EomSBM:btu7dz4) ([raw file](https://github.com/cockroachdb/cockroach/blob/73c212946dc2a5a7a4e3064e8612778c3112257f/pkg/sql/opt/lookupjoin/constraint_builder.go#L92)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Do you think it's worth packaging this stuff into a new struct, `lookupjoin.Constraint`, or something like that? You could also save that for a future PR...
</blockquote></details>

Yes, there's lots of refactoring I want to do here. The first step was to extract it before changing too much.
___
*[pkg/sql/opt/xform/join_funcs.go, line 374 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/79911#-N0ES_S97AdpcLFJuY4i:-N0Gv48UEIk3NO9BQZVW:b-z8l7fs) ([raw file](https://github.com/cockroachdb/cockroach/blob/73c212946dc2a5a7a4e3064e8612778c3112257f/pkg/sql/opt/xform/join_funcs.go#L374)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

If you make a new struct for `lookupjoin.Constraint`, this check could become a method on that struct.
</blockquote></details>

Good idea. I'll explore that in a future PR.

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79911)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[`pkg/sql/opt/lookupjoin/constraint_builder.go` line 85 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/79911#-N0EQKh3570w3q26Sm9S:-N0XFtH3589lrVE4qv6N:b1rtf67) ([raw file](https://github.com/cockroachdb/cockroach/blob/73c212946dc2a5a7a4e3064e8612778c3112257f/pkg/sql/opt/lookupjoin/constraint_builder.go#L85)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I really tried to make no changes to the logic here. The logic inside `Build` is the same as the logic removed in `generateLookupJoinsImpl`, except for referencing the ConstraintBuilder fields rather than CustomFuncs fields and some additional comments. There was an intertwined section of code that created a memo.LookupJoin that I did not move here. All the helper functions are the same, except for the receiver type. I'm not really sure how to move the logic in a way that makes few changes, but I know we've been bitten by moving code in the past. Did you have a specific idea in mind? I suppose I could try doing the work in these N commits:

1. Move the core key column and lookupExpr logic into a function rather than a struct method into a separate file in the xform package. Move the helper function to the separate file too.
2. Add the ConstraintBuilder struct, adding Init, Build, and turning the helpers into methods of that struct.
3. Move the ConstraintBuilder to a separate package.
</blockquote></details>

I'm suggesting that one of the commits should be literally just copy-paste with no changes, so it will not even compile, and is only for the purpose of making reviewing easier -- it will need to be squashed with the following commit before merging.

I think this is only needed for cases like this where there are large chunks of code moving, and as a reviewer, you want to be able to see the small changes that were made.

Does that make sense?

**Review by mgartner — COMMENTED** [review]
Added a new `lookupjoin.Constraint` struct in the last commit.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79911#-:-N0g1-sX3EF72k58PDOZ:b-mlv6h5)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @msirek and @rytaft)

___
*[`pkg/sql/opt/lookupjoin/constraint_builder.go` line 85 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/79911#-N0EQKh3570w3q26Sm9S:-N0frtTE-iqmrDdUAyVG:b-m3bwq8) ([raw file](https://github.com/cockroachdb/cockroach/blob/73c212946dc2a5a7a4e3064e8612778c3112257f/pkg/sql/opt/lookupjoin/constraint_builder.go#L85)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I'm suggesting that one of the commits should be literally just copy-paste with no changes, so it will not even compile, and is only for the purpose of making reviewing easier -- it will need to be squashed with the following commit before merging.

I think this is only needed for cases like this where there are large chunks of code moving, and as a reviewer, you want to be able to see the small changes that were made.

Does that make sense?
</blockquote></details>

I see. I wasn't thinking of making a commit that doesn't compile. The diff between the `SQUASH BEFORE MERGING ` commit and the `opt: moves some lookup join generation logic to lookup join package` commit should be an easier read now.
___
*[`pkg/sql/opt/lookupjoin/constraint_builder.go` line 80 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/79911#-N-hhZVg6N3rPPt_HYIk:-N0fujHU4oPMBGATaw9-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb70471d9106253de7ea62a4033f05fbf5c59043/pkg/sql/opt/lookupjoin/constraint_builder.go#L80)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

nit: maybe indicate these are left table columns and that this is an ordered list, with columns corresponding the those in rightSideCols.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/lookupjoin/constraint_builder_test.go` line 53 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/79911#-N-hz4ab1ZqqNvh5f2hq:-N0fu46k5tVIZsAvx1Lv:b-tiu1jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb70471d9106253de7ea62a4033f05fbf5c59043/pkg/sql/opt/lookupjoin/constraint_builder_test.go#L53)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Since this supports `[asc|desc]` ordering, maybe a test with a range condition on a descending column would be useful.
</blockquote></details>

I don't think it really matters for this lookup constraint code but I added one test for thoroughness.

**Review by cucaroach — APPROVED** [review]
> Reviewed 16 of 16 files at r7, 5 of 5 files at r8, 1 of 1 files at r9, 2 of 2 files at r10, 9 of 9 files at r11, 3 of 3 files at r12, 6 of 6 files at r13, 1 of 3 files at r14.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79911)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach, @msirek, and @rytaft)

**Comment by mgartner** [comment]
Friendly ping @rytaft. If it's still too hard to review or too risky of a move, let me know and I'll take another shot at it.

**Review by rytaft — APPROVED** [review]
Sorry for the delay! :lgtm: 

> Reviewed 16 of 16 files at r7, 4 of 5 files at r8, 9 of 9 files at r11, 3 of 3 files at r12, 6 of 6 files at r13, 3 of 3 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79911#-:-N0mD8Iq06isLtgdr0tz:b-q8dtds)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @msirek)

___
*[`pkg/sql/opt/lookupjoin/constraint_builder.go` line 85 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/79911#-N0EQKh3570w3q26Sm9S:-N0mD4RH4JTFAXZ8EXYc:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/73c212946dc2a5a7a4e3064e8612778c3112257f/pkg/sql/opt/lookupjoin/constraint_builder.go#L85)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I see. I wasn't thinking of making a commit that doesn't compile. The diff between the `SQUASH BEFORE MERGING ` commit and the `opt: moves some lookup join generation logic to lookup join package` commit should be an easier read now.
</blockquote></details>

Thanks!
___
*[`pkg/sql/opt/lookupjoin/constraint_builder.go` line 41 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/79911#-N0m2LG03ZilUTbMunnd:-N0m2LG03ZilUTbMunne:bcivedf) ([raw file](https://github.com/cockroachdb/cockroach/blob/82c05bd56c2a05dacf7412fd21d0a0b22e1c3734/pkg/sql/opt/lookupjoin/constraint_builder.go#L41)):*
> ```Go
> 	// KeyCols is an ordered list of columns from the left side of the join to
> 	// be used as lookup join key columns. This list corresponds to the columns
> 	// in RightSideCols. It will be nil if LookupExpr is nil.
> ```

nit: if LookupExpr is non-nil

**Review by mgartner — COMMENTED** [review]
TFTRs!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79911#-:-N0phHREAbKSHHWM54tR:b-tlx7ko)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @cucaroach, @msirek, and @rytaft)

___
*[`pkg/sql/opt/lookupjoin/constraint_builder.go` line 41 at r15](https://reviewable.io/reviews/cockroachdb/cockroach/79911#-N0m2LG03ZilUTbMunnd:-N0phFDtEMMtqffo2Z4O:bs7x2mx) ([raw file](https://github.com/cockroachdb/cockroach/blob/82c05bd56c2a05dacf7412fd21d0a0b22e1c3734/pkg/sql/opt/lookupjoin/constraint_builder.go#L41)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: if LookupExpr is non-nil
</blockquote></details>

Donne.

**Pull request merged**
