### PR TITLE
sql: clear target table before backfilling CREATE…AS

### PR DESCRIPTION
**Pull request by dt**
Since the backfill can be retried -- either at the schema change level or at the txn closure level -- it is possible that the backfill may start with some data already present in the target key space. This is can then manifest as incorrect results -- CREATE TABLE … AS is supposed to generate a new table with the results of the execution of the supplied query, not a mix of results of partial results of multiple executions of said query. Since source queries may not have order or may be impure, there is no general way to 'resume' a prior backfill --
so the only correct behavior is to start fresh eash time until a backfill succeeds in ingesting exectly one execution of the source query.

Release note (bug fix): Fix bug where interrupted CREATE TABLE ... AS execution could yield duplicate rows.

### CODE REVIEW

**Review by miretskiy — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43780)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @lucy-zhang, and @miretskiy)

___
*[pkg/sql/schema_changer.go, line 598 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43780#-Ly-cBdP1Ss5zVl-6MA9:-Ly-cBdP1Ss5zVl-6MAA:b-ht8lb) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f7eddd6ecc655cbaf1ee7750079c26ebf336121/pkg/sql/schema_changer.go#L598)):*
> ```Go
> 			// and our contract is that the created table contains the results of, and
> 			// only of, one execution, we need to ensure each attempt to backfill
> 			// starts with empty target keyspace.
> ```

Nice comment
___
*[pkg/sql/schema_changer.go, line 606 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43780#-Ly-dOsy0M4ycviKQzfu:-Ly-dOsy0M4ycviKQzfv:b-dj5cae) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f7eddd6ecc655cbaf1ee7750079c26ebf336121/pkg/sql/schema_changer.go#L606)):*
> ```Go
> 				},
> 			})
> 			sc.db.Run(ctx, b)
> ```

Should we check for error result here?
Do you think you could add a test that tests this behavior?

**Review by dt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43780)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @lucy-zhang, and @miretskiy)

___
*[pkg/sql/schema_changer.go, line 606 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43780#-Ly-dOsy0M4ycviKQzfu:-Ly-jiAT0rvwMa_cBCzz:b-yb3pbh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f7eddd6ecc655cbaf1ee7750079c26ebf336121/pkg/sql/schema_changer.go#L606)):*
<details><summary><i>Previously, miretskiy (Yevgeniy Miretskiy) wrote…</i></summary><blockquote>

Should we check for error result here?
Do you think you could add a test that tests this behavior?
</blockquote></details>

Done.

Yeah, I'm spinning up a roachprod cluster when I get in today to see if this fixes the repro in #43752. If that ends up working, i'll try to figure out how best to inject a restart (i still don't know if it was a txn vs schema-change restart).

**Review by miretskiy — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43780#-:-Ly-kNND-DK3fsjS6oQM:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt, @lucy-zhang, and @miretskiy)

**Review by thoszhang — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43780)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @dt)

___
*[pkg/sql/schema_changer.go, line 589 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43780#-Ly-zIxH3FwfPJY1_qX7:-Ly-zIxICIdXsP3Zdjd8:b9c2n9k) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcfc5b942d4ff80be6f396b7e566048f08ab5d7c/pkg/sql/schema_changer.go#L589)):*
> ```Go
> 	if table.Adding() && table.IsAs() {
> 		if err := sc.db.Txn(ctx, func(ctx context.Context, txn *client.Txn) error {
> ```

nit: Is this an extra newline?
___
*[pkg/sql/schema_changer.go, line 594 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/43780#-Ly-zR_n8_b6VPhhXmTg:-Ly-zR_n8_b6VPhhXmTh:ban5w1g) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcfc5b942d4ff80be6f396b7e566048f08ab5d7c/pkg/sql/schema_changer.go#L594)):*
> ```Go
> 			// This is a new table and should be empty, so this ClearRange should be a
> 			// noop. However, if there _is_ anything already there, we need to clear
> 			// it before backfilling. One such case is if this backfill was restarted:
> ```

Is there anything else that would cause the range to not be empty?

**Comment by dt** [comment]
I finally managed to test this and it isn't enough -- it isn't actually retries that are hitting me but concurrent execution. more details over on https://github.com/cockroachdb/cockroach/issues/43752#issuecomment-572288528

**Comment by dt** [comment]
this didn't end up being the issue -- not holding the lease was -- but it might still be a good idea? I donno, might be more of a question for schema folks.

**Pull request closed without merging**
