### PR TITLE
sql: add stubs for multiregion DATABASE and SHOW REGIONS

### PR DESCRIPTION
**Pull request by otan**
I've allowed the plural forms for REGION(S) for CREATE/ALTER
DATABASE...REGIONS, which I think makes it nice. Not too hesitant on
committing this as is, because we can always change our minds later.

Release note (sql change): Added stubs for the following syntaxes:
 * CREATE DATABASE d ... REGIONS regiona, regionb, ....
 * CREATE DATABASE d ... SURVIVE {AVAILABILITY ZONE FAILURE / REGION
   FAILURE / DEFAULT}
 * SHOW REGIONS / SHOW REGIONS FOR DATABASE d
 * ALTER DATABASE d ADD/DROP REGION(S) regiona, regionb, ...
 * ALTER DATABASE d SURVIVE ....

### CODE REVIEW

**Review by ajstorm — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55644)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[docs/generated/sql/bnf/create_database_stmt.bnf, line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55644#-MK07U-F2dIPwej12Q8u:-MK07U-F2dIPwej12Q8v:bojqeyl) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e47830219af8ac717fc854be6b0882a64320c72/docs/generated/sql/bnf/create_database_stmt.bnf#L2)):*
> ```
> create_database_stmt ::=
> 	'CREATE' 'DATABASE' database_name opt_with opt_template_clause 'ENCODING' opt_equal non_reserved_word_or_sconst opt_lc_collate_clause opt_lc_ctype_clause opt_connection_limit opt_create_database_regions_name_list opt_survive_clause
> ```

Nit: Could we use opt_regions_list instead of opt_create_database_regions_name_list?  Or is database specificity required here?
___
*[docs/generated/sql/bnf/stmt_block.bnf, line 1739 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55644#-MK08y8O2VLZL-LYml3a:-MK08y8O2VLZL-LYml3b:b-xkgn5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e47830219af8ac717fc854be6b0882a64320c72/docs/generated/sql/bnf/stmt_block.bnf#L1739)):*
> ```
> 
> opt_create_database_regions_name_list ::=
> 	region_or_regions opt_equal name_list
> ```

There was some debate early on about whether or not to include the "=" here.  I'm interested in your opinion (as well as others' @solongordon @arulajmani) as to what better fits our standard.  More of a Nit that we can iterate on afterwards, but thought it was worth mentioning here anyway.
___
*[docs/generated/sql/bnf/stmt_block.bnf, line 2090 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55644#-MK09XEE4D2sHJy_01Mq:-MK09XEE4D2sHJy_01Mr:b-ev5e7o) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e47830219af8ac717fc854be6b0882a64320c72/docs/generated/sql/bnf/stmt_block.bnf#L2090)):*
> ```
> survive_clause ::=
> 	'SURVIVE' 'REGION' 'FAILURE'
> 	| 'SURVIVE' 'AVAILABILITY' 'ZONE' 'FAILURE'
> ```

Might just be me, but if I was a DBA I would really want a "SURVIVE AZ FAILURE" shortcut too, just because "AVAILABILITY ZONE" is soooo long :).  The only catch is that I'm not sure if this will complicate the docs/help.  Thoughts?
___
*[docs/generated/sql/bnf/stmt_block.bnf, line 2091 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55644#-MK0A7jO1RrMyQaQP9NB:-MK0A7jO1RrMyQaQP9NC:b-rym0zx) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e47830219af8ac717fc854be6b0882a64320c72/docs/generated/sql/bnf/stmt_block.bnf#L2091)):*
> ```
> 	'SURVIVE' 'REGION' 'FAILURE'
> 	| 'SURVIVE' 'AVAILABILITY' 'ZONE' 'FAILURE'
> 	| 'SURVIVE' 'DEFAULT'
> ```

Nit - I'm somewhat of the opinion that we shouldn't allow a DEFAULT here.  Survivability is too important a concept for people to set it to the default without explicitly knowing what that default is.  
___
*[pkg/sql/parser/parse_test.go, line 1734 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55644#-MK0M676368NZGgFmu7G:-MK0M676368NZGgFmu7H:b3kuvdg) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e47830219af8ac717fc854be6b0882a64320c72/pkg/sql/parser/parse_test.go#L1734)):*
> ```Go
> 		},
> 		{
> 			`CREATE DATABASE a REGION "us-west-1"`,
> ```

I was under the impression that TestParse2 should only contain statements which don't generate the same SQL statement via the syntax tree.  Is that not the case with these tests?  
___
*[pkg/sql/sem/tree/alter_database.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55644#-MK0YN88B79pdFNsdwdP:-MK0YN89-qao3Bsy9wdY:bx1qeyc) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e47830219af8ac717fc854be6b0882a64320c72/pkg/sql/sem/tree/alter_database.go#L29)):*
> ```Go
> // AlterDatabaseAddRegion represents a ALTER DATABASE ADD REGION(S) statement.
> type AlterDatabaseAddRegion struct {
> 	Name    Name
> ```

Nit - Not sure if there's a convention in CRDB, but most members of a struct that I've seen start with a lowercase letter.  Also the fact that we're using the same name as a reserved type just looks odd to me.  I could be the only one though.  Actually, looking below at create.go I see that there are capitals use there.  Is there a convention as to when to use which?
___
*[pkg/sql/sem/tree/show.go, line 283 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55644#-MK0_hMvBD6D_WrFDbJX:-MK0_hMwDoVF0z3BFfOR:b-u0n7sd) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e47830219af8ac717fc854be6b0882a64320c72/pkg/sql/sem/tree/show.go#L283)):*
> ```Go
> // ShowRegions represents a SHOW REGIONS statement
> type ShowRegions struct {
> 	Database Name
> ```

Nit- Any reason why use used "Database" here instead of "Name"?  I prefer Database, but just curious as you've used Name above for database name.

**Review by ajstorm — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55644)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/55644#-MK0cgx95qIOf8iVVeRS:-MK0cgx95qIOf8iVVeRT:b-fraput) (no related file):*
One general comment - does it make sense to add a testcase for the unimplemented syntax to validate that it fails?  That way if someone implements them, they'd be prompted to add testcases in the corresponding locations.

---

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55644)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm, @arulajmani, @otan, and @solongordon)

___
*[docs/generated/sql/bnf/create_database_stmt.bnf, line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55644#-MK07U-F2dIPwej12Q8u:-MK0gV5K3hI8hV1Mh7ZU:b-bk14u6) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e47830219af8ac717fc854be6b0882a64320c72/docs/generated/sql/bnf/create_database_stmt.bnf#L2)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Nit: Could we use opt_regions_list instead of opt_create_database_regions_name_list?  Or is database specificity required here?
</blockquote></details>

Nop,e done!
___
*[docs/generated/sql/bnf/stmt_block.bnf, line 1739 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55644#-MK08y8O2VLZL-LYml3a:-MK0gWRtARHPpJv3Ns_O:bqdl7zm) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e47830219af8ac717fc854be6b0882a64320c72/docs/generated/sql/bnf/stmt_block.bnf#L1739)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

There was some debate early on about whether or not to include the "=" here.  I'm interested in your opinion (as well as others' @solongordon @arulajmani) as to what better fits our standard.  More of a Nit that we can iterate on afterwards, but thought it was worth mentioning here anyway.
</blockquote></details>

I think we should keep it in line with postgres's CREATE DATABASE syntax, where all `=` is optional.
https://www.postgresql.org/docs/9.0/sql-createdatabase.html

(note postgres allows random ordering too!)
___
*[docs/generated/sql/bnf/stmt_block.bnf, line 2090 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55644#-MK09XEE4D2sHJy_01Mq:-MK0gg9u3L2tZUih1DWF:br4lnf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e47830219af8ac717fc854be6b0882a64320c72/docs/generated/sql/bnf/stmt_block.bnf#L2090)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Might just be me, but if I was a DBA I would really want a "SURVIVE AZ FAILURE" shortcut too, just because "AVAILABILITY ZONE" is soooo long :).  The only catch is that I'm not sure if this will complicate the docs/help.  Thoughts?
</blockquote></details>

i think that's something we can iterate on later :) 
___
*[docs/generated/sql/bnf/stmt_block.bnf, line 2091 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55644#-MK0A7jO1RrMyQaQP9NB:-MK0glPB-GUWlexdzUdY:bjgu6zi) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e47830219af8ac717fc854be6b0882a64320c72/docs/generated/sql/bnf/stmt_block.bnf#L2091)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Nit - I'm somewhat of the opinion that we shouldn't allow a DEFAULT here.  Survivability is too important a concept for people to set it to the default without explicitly knowing what that default is.  
</blockquote></details>

This is a placeholder for what happens when someone does not specify one at all. What is the default behavior anyway? Should this always display in CREATE DATABASE syntax?
___
*[pkg/sql/parser/parse_test.go, line 1734 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55644#-MK0M676368NZGgFmu7G:-MK0gtWcAxvJP3KqUrIs:bdd7htz) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e47830219af8ac717fc854be6b0882a64320c72/pkg/sql/parser/parse_test.go#L1734)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

I was under the impression that TestParse2 should only contain statements which don't generate the same SQL statement via the syntax tree.  Is that not the case with these tests?  
</blockquote></details>

Yes, tehre's an extra `=` with the pretty prints.
___
*[pkg/sql/sem/tree/alter_database.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55644#-MK0YN88B79pdFNsdwdP:-MK0gx2QD1FnEs6ihLvv:b-1y4d9f) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e47830219af8ac717fc854be6b0882a64320c72/pkg/sql/sem/tree/alter_database.go#L29)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Nit - Not sure if there's a convention in CRDB, but most members of a struct that I've seen start with a lowercase letter.  Also the fact that we're using the same name as a reserved type just looks odd to me.  I could be the only one though.  Actually, looking below at create.go I see that there are capitals use there.  Is there a convention as to when to use which?
</blockquote></details>

Yes, for Go, public members MUST begin with capital case.
If lowercased, it means it can only be seen from within the same package.
I think name is typical  for database, e.g. AlterDatabaseOwner.
___
*[pkg/sql/sem/tree/show.go, line 283 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55644#-MK0_hMvBD6D_WrFDbJX:-MK0hI0i5QGSEurm6pDP:b-k5aalt) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e47830219af8ac717fc854be6b0882a64320c72/pkg/sql/sem/tree/show.go#L283)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Nit- Any reason why use used "Database" here instead of "Name"?  I prefer Database, but just curious as you've used Name above for database name.
</blockquote></details>

Yeah -- in line with other `show` items, if we decide, e.g. `SHOW REGIONS FOR SCHEMA`, it's more obvious which one it's referring to. Form following `SHOW GRANTS` here!

**Comment by otan** [comment]
*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/55644#-MK0cgx95qIOf8iVVeRS:-MK0hmZV0RN8SZixZzmq:bggkdbp) (no related file):*
> One general comment - does it make sense to add a testcase for the unimplemented syntax to validate that it fails? That way if someone implements them, they'd be prompted to add testcases in the corresponding locations.

I haven't done this yet because I'm not sure yet where they will all go. We can add some to `logic_test/multiregion` if we wanted to, but I'm not sure it's required (yet).

---

**Review by ajstorm — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55644)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/55644#-MK0cgx95qIOf8iVVeRS:-MK0ouej55T1iGt0sG3o:b9u49ka) (no related file):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

> One general comment - does it make sense to add a testcase for the unimplemented syntax to validate that it fails? That way if someone implements them, they'd be prompted to add testcases in the corresponding locations.

I haven't done this yet because I'm not sure yet where they will all go. We can add some to `logic_test/multiregion` if we wanted to, but I'm not sure it's required (yet).
</blockquote></details>

That's fair.  I agree that this is a nice-to-have at this point.

---
___
*[docs/generated/sql/bnf/stmt_block.bnf, line 2091 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55644#-MK0A7jO1RrMyQaQP9NB:-MK0pD-T4eOf96xJI9Hi:bdvtsqy) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e47830219af8ac717fc854be6b0882a64320c72/docs/generated/sql/bnf/stmt_block.bnf#L2091)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

This is a placeholder for what happens when someone does not specify one at all. What is the default behavior anyway? Should this always display in CREATE DATABASE syntax?
</blockquote></details>

The suggested default is AZ.  The current thinking is that it won't have to be specified.
___
*[pkg/sql/parser/parse_test.go, line 1734 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55644#-MK0M676368NZGgFmu7G:-MK0pVvT5C5yGbxYInaL:bxjirby) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e47830219af8ac717fc854be6b0882a64320c72/pkg/sql/parser/parse_test.go#L1734)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

Yes, tehre's an extra `=` with the pretty prints.
</blockquote></details>

Ahh, thanks for clarifying
___
*[pkg/sql/sem/tree/alter_database.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55644#-MK0YN88B79pdFNsdwdP:-MK0pdVpDhDlSotL2XI2:b-jng8m) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e47830219af8ac717fc854be6b0882a64320c72/pkg/sql/sem/tree/alter_database.go#L29)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

Yes, for Go, public members MUST begin with capital case.
If lowercased, it means it can only be seen from within the same package.
I think name is typical  for database, e.g. AlterDatabaseOwner.
</blockquote></details>

Ahh right.  I did know that, but had forgotten.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55644)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/55644#-MK0cgx95qIOf8iVVeRS:-MK0jMbsBSMvhaKqhUcd:b-1epjbm) (no related file):*
> I haven't done this yet because I'm not sure yet where they will all go. We can add some to logic_test/multiregion if we wanted to, but I'm not sure it's required (yet).

done this for now.

---
___
*[docs/generated/sql/bnf/stmt_block.bnf, line 2091 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55644#-MK0A7jO1RrMyQaQP9NB:-MK0jBJQ9r2ld4ZYsclc:bw7c4ui) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e47830219af8ac717fc854be6b0882a64320c72/docs/generated/sql/bnf/stmt_block.bnf#L2091)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

The suggested default is AZ.  The current thinking is that it won't have to be specified.
</blockquote></details>

(fwiw, the CREATE DATABASE pretty print at the moment only includes the SURVIVE clause if it's not DEFAULT. we also have to think of backwards compatibility here)
we can come back to this -- there's also a debate about whether this should pop up when looking at CREATE DATABASE syntax. i will keep it around for now. I feel as though it's nice to keep a separate value for "not specified"

**Comment by otan** [comment]
___
*[pkg/sql/sem/tree/alter_database.go, line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55644#-MK0YN88B79pdFNsdwdP:-MK0sauE0feXLqnB-fSj:bv4gnwc) ([raw file](https://github.com/cockroachdb/cockroach/blob/1e47830219af8ac717fc854be6b0882a64320c72/pkg/sql/sem/tree/alter_database.go#L29)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Ahh right.  I did know that, but had forgotten.  
</blockquote></details>

My first time using go, i named my test `testSomething` instead of `TestSomething`. the tests never ran and it took me 3 hours to figure out why ;~;

**Comment by otan** [comment]
bors r=ajstorm

**Pull request merged**
