### PR TITLE
sql: Move isAgg visitor to parser, disallow aggregates in CHECK and DEFAULT

### PR DESCRIPTION
**Pull request by dt**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7221)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/planner.go, line 56 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7221#-KKFdeAnF67EYYjuF30U:-KKFdeAnF67EYYjuF30V:890811039) ([raw file](https://github.com/cockroachdb/cockroach/blob/347976b4efa903b4d02798b21f94ec2b8e2870fb/sql/planner.go#L56)):*
> ```Go
> 
> 	// Avoid allocations by embedding commonly used visitors.
> 	isAggregateVisitor          isAggregateVisitor
> ```

what does this do to allocations? probably not a serious problem, but likely worse.

---

*[sql/parser/aggregate_builtins.go, line 44 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7221#-KKFdqt1yXc4r59FuMdN:-KKFdqt1yXc4r59FuMdO:-1443713923) ([raw file](https://github.com/cockroachdb/cockroach/blob/030949d63f69a16d0b6a7be30353dd1580a8b1be/sql/parser/aggregate_builtins.go#L44)):*
> ```Go
> var _ Visitor = &IsAggregateVisitor{}
> 
> // IsAggregateVisitor checks if walked expressions contain aggregate functions.
> ```

belongs to the previous commit

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7221#-:-KKFe1UHQLxF2BQIAwGl:1417088721)*

**Comment by dt** [comment]
Review status: 8 of 11 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/planner.go, line 56 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7221#-KKFdeAnF67EYYjuF30U:-KKFeTHsa31jIwTBlS_e:1534967132) ([raw file](https://github.com/cockroachdb/cockroach/blob/347976b4efa903b4d02798b21f94ec2b8e2870fb/sql/planner.go#L56)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> what does this do to allocations? probably not a serious problem, but likely worse.
</details>
it just moved to be field of `parser` instead of `planner` but should still get allocated along with the containing struct (since planner embeds parser).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7221)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/planner.go, line 56 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7221#-KKFdeAnF67EYYjuF30U:-KKFfjTvkO7ToPkA5zKb:-1410593474) ([raw file](https://github.com/cockroachdb/cockroach/blob/347976b4efa903b4d02798b21f94ec2b8e2870fb/sql/planner.go#L56)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> it just moved to be field of `parser` instead of `planner` but should still get allocated along with the containing struct (since planner embeds parser).
</details>
Oh, I didn't realize `parser` is a local. Good times with the shadowing =/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7221)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/planner.go, line 56 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7221#-KKFdeAnF67EYYjuF30U:-KKFj2V1qjjBvN2QhqQ9:-804097859) ([raw file](https://github.com/cockroachdb/cockroach/blob/347976b4efa903b4d02798b21f94ec2b8e2870fb/sql/planner.go#L56)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Oh, I didn't realize `parser` is a local. Good times with the shadowing =/
</details>
I mean `parser` is a field of `planner` of type `parser.Parser` -- not technically shadowing, but I see where it got confusing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7221)*

**Pull request merged**
