### PR TITLE
roachtest: update TeamCity links to the new UI.

### LINKED ISSUE #80852: test-eng: artifacts links in roachtest issues no longer works
The artifacts link

should open like this:

image

but it no longer does this auto-expand, so the user has to manually click through the tree which is error prone (since lots of test names are similar) and slow.

The link in the issue is

```
https://teamcity.cockroachdb.com/viewLog.html?buildId=5032926&tab=artifacts#/transfer-leases/drain
```

but the actual expanded link is

```
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/5032926?buildTab=artifacts#%2Ftransfer-leases%2Fdrain
```

We should update the link. This is mildly annoying since the "Build configuration ID" is now part of the URL and wasn't before, so it needs to be made available to the artifacts URL construction, which begins in

https://github.com/cockroachdb/cockroach/blob/185e479042a08c2af1e4c62547cc6cb067d21019/pkg/cmd/roachtest/test_runner.go#L1050

(and may need to be chased down into the `issues` package.

### PR DESCRIPTION
**Pull request by renatolabs**
In 2019, TeamCity released a new "experimental UI" that changed not
only the look and feel of the app, but also the URLs where pages are
located. Notably, information about a build used to be under the
/viewLog.html page in the old UI, but was moved to
/buildConfiguration/{buildTypeID}/{buildID} in the new UI.

If the user enabled the new UI locally, TeamCity will automatically
redirect requests from the old URLs to the new ones; however, the URL
fragments are not preserved. This is quite bad for roachtest, since
the links generated in failed test reports relies on the fragments in
order to expand the relevant folders in a potentially long list of
artifacts.

This commit updates TeamCity links generated by roachtest when
reporting failed tests to always use the new UI. It has the drawback
of forcing the new UI on everyone, but the benefit of always expanding
the correct folder.

A new environment variable, `TC_BUILDTYPE_ID`, was added to TeamCity
builds to support this use case; it contains the ID of the
corresponding build type (also known as "build configuration").

Resolves: #80852.

Release note: None.

*****

@tbg: I also saw that [slack.go](https://github.com/cockroachdb/cockroach/blob/40d8803af38fd89ee7728a3081814d15c6068a3f/pkg/cmd/roachtest/slack.go#L94-L96) generates a link to the old UI. Is that code being used at the moment? It seems to try to send notifications to the `#production` Slack channel, but the notifications I see there don't seem to match what the code in that file is doing.

### CODE REVIEW

**Review by tbg — APPROVED** [review]
:lgtm: thank you! Just to double check, you added the env var to all TeamCity builds, right? There should be five of them, namely the four combinations of {AWS,GCE}{Bazel,DEPRECATED} and the weekly roachtest. Possibly they all draw from the same template. Just giving you a sanity check of how many updates I'm expecting.
If we're missing one it's not the end of the world.

----

Good question about slack.go. It is still being "plumbed around":

```
$ git grep slack-token -- build/
build/teamcity-nightly-roachtest.sh:  --slack-token="${SLACK_TOKEN}" \
build/teamcity/cockroach/nightlies/pebble_nightly_write_throughput_impl.sh:  --slack-token "${SLACK_TOKEN-}" \
build/teamcity/cockroach/nightlies/pebble_nightly_ycsb_impl.sh:  --slack-token "${SLACK_TOKEN-}" \
build/teamcity/cockroach/nightlies/pebble_nightly_ycsb_race_impl.sh:  --slack-token "${SLACK_TOKEN-}" \
build/teamcity/cockroach/nightlies/roachtest_nightly_impl.sh:  --slack-token="${SLACK_TOKEN}" \
```

But I agree - what's going on in `#production` indicates that this isn't actually posting from any job (and if it did, it would be useless).

I think we could ignore this for now, and possibly even remove the slack support (though we have to be careful with that, since if we remove the flag without also updating all scripts that call into roachtest, the invocations will fail). I have not heard anyone clamor for being notified, in Slack, of failures of individual tests; folks are struggling enough to keep up with the issues.

This seems lower priority though. If you're not sure what to pick up next, and find that cleanup satisfying, I would be happy to review it.

> Reviewed 26 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81103#-:-N1PqfyS794_3IlnuXDW:b-2zfhxm)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nicktrav)

**Review by nicktrav — APPROVED** [review]
TIL about the "new" TC interface.

Deferring to Tobi for the "official" LGTM, but :lgtm: from me!

> Reviewed 26 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81103#-:-N1PzAoyCj_RlULCCHK-:bf19fik)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @renatolabs)

**Review by srosenberg — APPROVED** [review]
:lgtm:

> Reviewed 26 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81103#-:-N1Q4ag87A94S0kqrwOa:bnfp4nl)* status: :shipit: complete! 3 of 0 LGTMs obtained (waiting on @renatolabs)

**Comment by renatolabs** [comment]
> Just to double check, you added the env var to all TeamCity builds, right? There should be five of them, namely the four combinations of {AWS,GCE}{Bazel,DEPRECATED} and the weekly roachtest.

It's been added to all builds under "Cockroach" on TeamCity ([commit](https://github.com/cockroachlabs/teamcity-config/commit/279c199a3d3fb0394c939e0559adca2ea19585df)).

**Comment by renatolabs** [comment]
bors r=tbg,nicktrav,srosenberg

**Pull request merged**
