### PR TITLE
builtins: handle unavailable ranges in `crdb_internal.ranges`

### LINKED ISSUE #128088: sql: make `crdb_internal.ranges` resilient to unavailability
Querying `crdb_internal.ranges` will currently fail if any of the ranges in the system are unavailable. This is because the virtual table runs `crdb_internal.lease_holder` and `crdb_internal.range_stats` against each range. This can be a hindrance to debugging struggling clusters.

We should fix this by making sure that the query does not fail on any unavailable range, but instead returns incomplete information for those ranges.

Jira issue: CRDB-40793

### PR DESCRIPTION
**Pull request by miraradeva**
Previously, when querying crdb_internal.{lease_holder, range_stats} (e.g. as part of querying crdb_internal.ranges), a single unavailable range would result in the entire query failing. This is problematic when investigating clusters with unavailable ranges as it fails to show information even for the available ranges.

This commit adds new variants of `crdb_internal.
{lease_holder, range_stats}`, `crdb_internal.
{lease_holder, range_stats}_with_errors`, that include any encountered errors in the JSON output instead of failing the entire query. These are then used in `crdb_internal.ranges`, which now includes the errors encountered while fetching the leaseholder and range stats.

Fixes: #128088

Release note (sql change): Two new builtins, crdb_internal. {lease_holder, range_stats}_with_errors, include errors encountered while fetching lease holder and range stats. These new builtins are used by `crdb_internal.ranges`, which includes a new column, `errors`, that combines the errors from the builtins.

----

Example output of `select range_id, lease_holder, range_size, errors from crdb_internal.ranges;`

Screenshot 2024-09-23 at 2 37 24 PM

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
Nice! Is there any way to add a test that injects an error so we can see the output (beyond the picture you included above)?

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131232#-:-O82dJYE4YqB22AGF7Rb:b-c3x01y)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @miraradeva)

___
*[`pkg/sql/catalog/colinfo/result_columns.go` line 370 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131232#-O82Zp2C-PEQIWco5dHq:-O82Zp2C-PEQIWco5dHr:bwud6tx) ([raw file](https://github.com/cockroachdb/cockroach/blob/120ebaa8fcde01ee8ab258502a6738d991995477/pkg/sql/catalog/colinfo/result_columns.go#L370)):*
> ```Go
> 	coalesce((crdb_internal.range_stats_with_errors(start_key)->'RangeStats'->>'range_key_bytes')::INT, 0) +
> 	coalesce((crdb_internal.range_stats_with_errors(start_key)->'RangeStats'->>'range_val_bytes')::INT, 0) AS range_size,
> 	concat(crdb_internal.lease_holder_with_errors(start_key)->>'Error', crdb_internal.range_stats_with_errors(start_key)->>'Error') AS errors
> ```

nit: maybe add a space between the two errors so it's more readable in case both err
___
*[`pkg/sql/colexec/range_stats.go` line 155 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131232#-O82bO1w84myg1XX-NUo:-O82bO1w84myg1XX-NUp:bw68l7v) ([raw file](https://github.com/cockroachdb/cockroach/blob/120ebaa8fcde01ee8ab258502a6738d991995477/pkg/sql/colexec/range_stats.go#L155)):*
> ```Go
> 				// in fetcher.RangeStats and r.withErrors = true).
> 				if r.withErrors && i >= len(res) {
> 					rswe.Error = rangeStatsErr.Error()
> ```

why not just include this on every row? Also do you need to check if `rangeStatsErr != nil`?
___
*[`pkg/sql/sem/builtins/builtins.go` line 5870 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131232#-O82cPpI68gb2z-Z8lmH:-O82cPpI68gb2z-Z8lmI:bhmguza) ([raw file](https://github.com/cockroachdb/cockroach/blob/120ebaa8fcde01ee8ab258502a6738d991995477/pkg/sql/sem/builtins/builtins.go#L5870)):*
> ```Go
> 				if evalCtx.Txn == nil { // can occur during backfills
> 					return nil, pgerror.Newf(pgcode.FeatureNotSupported,
> 						"cannot use crdb_internal.lease_holder in this context")
> ```

nit: update function name

**Review by miraradeva — COMMENTED** [review]
I agree this would be nice to test, but I'm having trouble navigating the test frameworks. I was hoping to be able to inject an error and then add a query with the expected output in `pkg/sql/logictest/testdata/logic_test/crdb_internal`. But the only example of an injected error I see there is `SET inject_retry_errors_enabled=true`, which, from what I understand, is something we expose to developers to test their app's retry logic.

Looking more into the builtins, I see this comment `add unit tests that use the `colexectestutils.RunTests` test  harness` in `range_stats.go`. I could play around with the framework more but that wouldn't help with seeing the exact output of querying `crdb_internal.ranges`. 

Do you have any pointers for the best place to test this?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131232#-:-O88SezRChOwgyU9lR1M:b-4d5otp)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/catalog/colinfo/result_columns.go` line 370 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131232#-O82Zp2C-PEQIWco5dHq:-O87d7W7A5DPtlteB4cS:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/120ebaa8fcde01ee8ab258502a6738d991995477/pkg/sql/catalog/colinfo/result_columns.go#L370)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: maybe add a space between the two errors so it's more readable in case both err
</blockquote></details>

Done
___
*[`pkg/sql/colexec/range_stats.go` line 155 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131232#-O82bO1w84myg1XX-NUo:-O87dsr-6fgBnrRO8LYx:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/120ebaa8fcde01ee8ab258502a6738d991995477/pkg/sql/colexec/range_stats.go#L155)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

why not just include this on every row? Also do you need to check if `rangeStatsErr != nil`?
</blockquote></details>

Done
___
*[`pkg/sql/sem/builtins/builtins.go` line 5870 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131232#-O82cPpI68gb2z-Z8lmH:-O87cuE1089DsMce2My8:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/120ebaa8fcde01ee8ab258502a6738d991995477/pkg/sql/sem/builtins/builtins.go#L5870)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: update function name
</blockquote></details>

Done

**Review by rytaft — COMMENTED** [review]
I'm not sure about `inject_retry_errors_enabled` or similar... you could probably use `TestCluster.StopServer` after scattering ranges to make an unavailable range in a unit test, or you could add a logictest directive that does the same thing if you wanted to add the test to `pkg/sql/logictest/testdata/logic_test/crdb_internal`.

Otherwise this is looking good!

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131232#-:-O8CZVyQ5kY4_tJQ7JnX:bswn3ll)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

**Review by mgartner — APPROVED** [review]
:lgtm: Once Becca's comments have been addressed.

> Reviewed 6 of 10 files at r1, 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131232#-:-O9AmlSo50ugKmHWtiI5:b93wt5p)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @miraradeva and @rytaft)

___
*[`pkg/sql/catalog/colinfo/result_columns.go` line 367 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131232#-O9AkmGZ26-NP9zGaq3x:-O9AkmGZ26-NP9zGaq3y:b-5wyznd) ([raw file](https://github.com/cockroachdb/cockroach/blob/19ff8e3938550561c286d04c17452691a7eb8a33/pkg/sql/catalog/colinfo/result_columns.go#L367)):*
> ```Go
> 	(crdb_internal.lease_holder_with_errors(start_key)->>'Leaseholder')::INT AS lease_holder,
> 	(crdb_internal.range_stats_with_errors(start_key)->'RangeStats'->>'key_bytes')::INT +
> 	(crdb_internal.range_stats_with_errors(start_key)->'RangeStats'->>'val_bytes')::INT +
> ```

How expensive are these functions? The optimizer does not currently optimize duplicate invocations to the same function with the same arguments into a single invocation. For example, for each `start_key`, `range_stats_with_errors` will be invoked 5 times.

To invoke it only once, you'd have to manually rewrite the query to something like:

```sql
SELECT
  (lease_holder_with_errors->>'Leaseholder')::INT AS lease_holder,
  (range_stats->'RangeStats'->>'key_bytes')::INT +
  (range_stats->'RangeStats'->>'val_bytes')::INT +
  coalesce(range_stats->'RangeStats'->>'range_key_bytes')::INT, 0) +
  coalesce(range_stats->'RangeStats'->>'range_val_bytes')::INT, 0) AS range_size,
  concat(lease_holder_with_errors(start_key)->>'Error', ' ', range_stats->>'Error') AS errors
FROM (
  SELECT 
    crdb_internal.range_stats_with_errors(start_key) AS range_stats,
    crdb_internal.lease_holder_with_errors(start_key) AS lease_holder_with_errors
  FROM ...
)
```

**Review by miraradeva — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131232)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[`pkg/sql/catalog/colinfo/result_columns.go` line 367 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131232#-O9AkmGZ26-NP9zGaq3x:-O9GsLF_9WO9HskcmU3C:bwx7jz) ([raw file](https://github.com/cockroachdb/cockroach/blob/19ff8e3938550561c286d04c17452691a7eb8a33/pkg/sql/catalog/colinfo/result_columns.go#L367)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

How expensive are these functions? The optimizer does not currently optimize duplicate invocations to the same function with the same arguments into a single invocation. For example, for each `start_key`, `range_stats_with_errors` will be invoked 5 times.

To invoke it only once, you'd have to manually rewrite the query to something like:

```sql
SELECT
  (lease_holder_with_errors->>'Leaseholder')::INT AS lease_holder,
  (range_stats->'RangeStats'->>'key_bytes')::INT +
  (range_stats->'RangeStats'->>'val_bytes')::INT +
  coalesce(range_stats->'RangeStats'->>'range_key_bytes')::INT, 0) +
  coalesce(range_stats->'RangeStats'->>'range_val_bytes')::INT, 0) AS range_size,
  concat(lease_holder_with_errors(start_key)->>'Error', ' ', range_stats->>'Error') AS errors
FROM (
  SELECT 
    crdb_internal.range_stats_with_errors(start_key) AS range_stats,
    crdb_internal.lease_holder_with_errors(start_key) AS lease_holder_with_errors
  FROM ...
)
```
</blockquote></details>

That's a great point, and I did spend some time trying to improve the performance. I really didn't want to redefine the entire `crdb_internal.ranges` view, and only make changes within `colinfo.RangesExtraRenders` (because `colinfo.RangesExtraRenders` is also used in `SHOW RANGES WITH DETAILS`). I tried this:

```
const RangesExtraRenders = `
(
  SELECT 
    (lh->>'Leaseholder')::INT AS lease_holder,
    (rs->'RangeStats'->>'key_bytes')::INT +
    (rs->'RangeStats'->>'val_bytes')::INT +
    COALESCE((rs->'RangeStats'->>'range_key_bytes')::INT, 0) +
    COALESCE((rs->'RangeStats'->>'range_val_bytes')::INT, 0) AS range_size,
    CONCAT(lh->>'Error', ' ', rs->>'Error') AS errors
  FROM 
    crdb_internal.lease_holder_with_errors(start_key) AS lh,
    crdb_internal.range_stats_with_errors(start_key) AS rs
)
`
```

But that doesn't work because `subquery must return only one column, found 3`. And I couldn't find a way to circumvent that while keeping the changes contained to `colinfo.RangesExtraRenders`. Happy to try something else if you have ideas.  Alternatively, we'd need to refactor the `SHOW RANGES WITH DETAILS` logic.

**Review by rytaft — APPROVED** [review]
:lgtm: nice work getting this over the finish line!

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131232#-:-O9oZ8CSCaEMBsgWIXlf:b-qesys0)* status: <span>:shipit:</span> complete! 2 of 0 LGTMs obtained (waiting on @mgartner and @miraradeva)

___
*[`pkg/sql/show_ranges_test.go` line 243 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/131232#-O9oZ2EuDLciIQTQcDEH:-O9oZ2Ev0y1UgGftYQWj:bds3i29) ([raw file](https://github.com/cockroachdb/cockroach/blob/19ff8e3938550561c286d04c17452691a7eb8a33/pkg/sql/show_ranges_test.go#L243)):*
> ```Go
> // error if it encounters an unavailable range. Moreover, crdb_internal.ranges
> // includes the encountered error.
> func TestShowRangesUnavailableReplicas(t *testing.T) {
> ```

Nice test!

**Comment by miraradeva** [comment]
bors r=rytaft,mgartner

**Pull request merged**
