### PR TITLE
server, security: Token-based add/join TLS functionality 

### LINKED ISSUE #61624: cli: TLS certs generated via `connect` cause one-way connectivity problem
Here is what I used:

1) on machine `192.168.2.10` I ran the following command:

   `./cockroach connect --num-expected-initial-nodes 2 --init-token abc --listen-addr=192.168.2.10  --join=192.168.2.19:26258`

2) on machine `192.168.2.19` I ran the following:

   `./cockroach connect --num-expected-initial-nodes 2 --init-token abc --join=192.168.2.10:26257 --listen-addr=192.168.2.19:26258  --http-addr=:8081`

This made the connect command complete successfully.

Note: beware of mentioning the port number in `--join` (because of issue #61620) and explicit IP addresses in `--listen-addr` (because of issues  #61619 and #61616) 

3) Then as recommended by the `connect` command I ran the following, which worked:

   `./cockroach cert create-client root --ca-key=~/.cockroach-certs/ca-client.key`

Then I started my CockroachDB nodes:

4) on machine `192.168.2.10`:

   `./cockroach start --join=192.168.2.19:26258 --listen-addr=192.168.2.10`

5) on machine `192.168.2.19`:

   `./cockroach start  --join=192.168.2.10:26257 --listen-addr=192.168.2.19:26258 --http-addr=:8081`

6) Here I start observing in logs something that is unexpected / undesirable (**first symptom of the problem**):

   - on 192.168.2.10 logs are fine:

     `I210308 15:50:28.243256 206 server/init.go:420 ⋮ [n?] 28  ‹192.168.2.19:26258› is itself waiting for init, will retry`

     This indicates that this server is able to establish an outgoing RPC conn to the other one.

   - on 192.168.2.19, we see the problem:

     `W210308 16:05:46.896090 150 server/init.go:422 ⋮ [n?] 41  outgoing join rpc to ‹192.168.2.10:26257› unsuccessful: ‹rpc error: code = Unauthenticated desc = TLSInfo is not a
vailable in request context›`

     **This indicates that this server is unable to establish its outgoing RPC conn to the other one.**

7) at this point I was suspecting that maybe the `init` RPC is special and uses a different TLS configuration that an already-initialized server. So I ran the following, which worked without errors:

   - on 192.168.2.10: `./cockroach start --join=192.168.2.19:26258 --listen-addr=192.168.2.10 --insecure`
   - on 192.168.2.19: `./cockroach start  --join=192.168.2.10:26257 --listen-addr=192.168.2.19:26258 --http-addr=:8081 --insecure`
   - anywhere: `./cockroach init --host=... --port=... --insecure`

   This initializes the cluster and assigns node ID without connectivity errors.

8) Then I re-start the already-initialized servers, using the same commands as previously. Then ISee:

   - on 192.168.2.10 I see the following errors:

```
E210308 16:09:11.689777 446 kv/kvserver/consistency_queue.go:191 ⋮ [n1,consistencyChecker,s1,r22/1:‹/Table/2{6-7}›] 123  computing own checksum: could not dial node ID 1: u
nable to dial n1: ‹breaker open›
E210308 16:09:11.689856 446 kv/kvserver/queue.go:1093 ⋮ [n1,consistencyChecker,s1,r22/1:‹/Table/2{6-7}›] 124  computing own checksum: could not dial node ID 1: unable to di
al n1: ‹breaker open›
E210308 16:09:13.688958 1331 kv/kvserver/consistency_queue.go:191 ⋮ [n1,consistencyChecker,s1,r7/1:‹/Table/1{1-2}›] 125  computing own checksum: could not dial node ID 1: f
ailed to connect to n1 at ‹192.168.2.10:26257›: ‹initial connection heartbeat failed›: ‹rpc error: code = Unauthenticated desc = TLSInfo is not available in request context
›
```

   - on 192.168.2.19 I see the following errors:

```
W210308 16:08:49.464792 132 vendor/google.golang.org/grpc/internal/channelz/logging.go:73 ⋮ [-] 55  ‹grpc: addrConn.createTransport failed to connect to {192.168.2.10:26257
  <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing cannot reuse client connection". Reconnecting...›
I210308 16:08:51.678239 257 1@vendor/github.com/cockroachdb/circuitbreaker/circuitbreaker.go:322 ⋮ [n2] 56  circuitbreaker: ‹rpc 192.168.2.19:26258 [n1]› tripped: failed to
 connect to n1 at ‹192.168.2.10:26257›: ‹initial connection heartbeat failed›: ‹rpc error: code = Unauthenticated desc = TLSInfo is not available in request context›
I210308 16:08:51.678323 257 1@vendor/github.com/cockroachdb/circuitbreaker/circuitbreaker.go:447 ⋮ [n2] 57  circuitbreaker: ‹rpc 192.168.2.19:26258 [n1]› event: ‹BreakerTri
pped›
I210308 16:08:51.678351 257 2@rpc/nodedialer/nodedialer.go:160 ⋮ [ct-client] 58  unable to connect to n1: failed to connect to n1 at ‹192.168.2.10:26257›: ‹initial connecti
on heartbeat failed›: ‹rpc error: code = Unauthenticated desc = TLSInfo is not available in request context›
I210308 16:08:51.766654 76 1@vendor/github.com/cockroachdb/circuitbreaker/circuitbreaker.go:322 ⋮ [n2] 59  circuitbreaker: ‹rpc 192.168.2.19:26258 [n1]› tripped: failed to
connect to n1 at ‹192.168.2.10:26257›: ‹initial connection heartbeat failed›: ‹rpc error: code = Unauthenticated desc = TLSInfo is not available in request context›
I210308 16:08:51.766737 76 1@vendor/github.com/cockroachdb/circuitbreaker/circuitbreaker.go:447 ⋮ [n2] 60  circuitbreaker: ‹rpc 192.168.2.19:26258 [n1]› event: ‹BreakerTrip
ped›
I210308 16:08:51.766759 76 2@rpc/nodedialer/nodedialer.go:160 ⋮ [n2,ts-poll,range-lookup=‹/Meta2/System/tsd/cr.node.build.timestamp/2/10s/2021-03-08T16:00:00Z›] 61  unable
to connect to n1: failed to connect to n1 at ‹192.168.2.10:26257›: ‹initial connection heartbeat failed›: ‹rpc error: code = Unauthenticated desc = TLSInfo is not available
 in request context›
```

Related to #60632

cc @aaron-crl @itsbilal

### PR DESCRIPTION
**Pull request by itsbilal**
Informs  #60632.
Epic: CRDB-6663

This change adds a new CLI command, `connect join`, that lets a new
node retrieve CA certificates off of an existing secure cluster
and bootstrap its own TLS certificates for joining that cluster.
This is achieved through the consumption of a join token
stored in the join_tokens table. Join tokens can be created
using the `create_join_tokens()` sql builtin function, added
in a previous change.

The previous `connect` command has now been renamed to
`connect init`.

A new set of GRPC endpoints have been created to handle the
server side of this change; to support retrieval of CAs as well
as entire initialization cert bundles. The cert bundles with
CAs and private keys aren't sent over the wire until a
node join token has been verified and consumed. The receiving
node (the one running `connect join`) then stores them in its
SSLCertsDir and bootstraps its own certificates off of it.

This feature is hidden behind a feature flag.

A couple other changes in this commit to clean up related code
in the `security` package:
 - Capitalize CA consistently in protobuf structs and method names
 - Write all CAs/certs from the right places in InitializeFromConfig
   instead of writing the InterNode one everywhere
 - Pass around raw byte certificates in auto_tls_init.go instead of
   doing excess PEM encodings and decodings.
 - Create a `client.node.crt` signed by `ca-client.crt`, otherwise
   nodes wouldn't be able to connect to each other. Fixes cockroachdb#61624.

Release note (cli change): Rename `connect` to `connect init`,
and add `connect join` command to retrieve certificates from
an existing secure cluster and setup a new node to connect with
it.

Co-authored-by: Aaron Blum <aaron@cockroachlabs.com>
Co-authored-by: Bilal Akhtar <bilal@cockroachlabs.com>

### CODE REVIEW

**Comment by itsbilal** [comment]
This PR also "takes over" #61265. @aaron-crl happy to listen to your feedback about anything!

**Comment by aaron-crl** [comment]
Thank you for picking this up @itsbilal ! I'll pick this up after breather week.

**Comment by itsbilal** [comment]
I've added a test and rebased / fixed up some issues. This is ready for a look!

**Review by knz — COMMENTED** [review]
Discussed separately:

Overall design seems copacetic.  Good confidence about the approach.
-> We'll want to circle back on the RFC and align the RFC to the approaches taken in code.
(Who: knz with support from bilal & aaron)

Code review: knz primary, Ben secondary.

Code duplication from the security package: this is creating tech debt.
-> File an issue to reduce that duplication (bilal)

The code is now using both CertLocator and CertManager: this creating another layer of tech debt.
-> File an issue to coalesce them into one (and perhaps mention reuse what Darin built in the sub-package) (bilal)

Testing confidence: 3/5
- need to add a version number to the join token (bilal: best effort, otherwise file follow-up issue, link it to the meta-issue about integration)
- testing work is end-to-end; want some additional failure tests (bilal: this PR).
- some of the sub-components do not have unit tests. We may want to punt on this (maybe file a followup issue)
- want unit tests where the join token is consumed (bilal: this PR)
These aspects would raise test coverage from 3/5 to 4/5.

> Reviewed 5 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63492#-:-MZrdILd0jiw8G6bc-5E:b-ofd630)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl and @knz)

**Comment by itsbilal** [comment]
Thanks for that summary, @knz ! I've addressed the parts of testing that I mentioned I'd address in this PR, in the latest push. I'll start to file the follow-up issues soon.

**Review by knz — COMMENTED** [review]
Ok I went through a more in-depth review of this PR,
taking over Aaron's role in that regard.

I think the work here is indeed quite well polished already.
I have a few suggestions below in addition to the summary above. Mostly the error checks need to be enhanced for correctness.

A lot of the follow up work can be discretized in follow-up issues, so they are not blocking this PR from merging.

> Reviewed 5 of 13 files at r1, 7 of 7 files at r2, 3 of 3 files at r3, 1 of 1 files at r4, 15 of 15 files at r5, 7 of 9 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63492#-:-M_1B0jEAh_Ixt9j9fI7:be2dqiy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl, @itsbilal, and @knz)

___
*[pkg/cli/addjoin.go, line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63492#-M_118wrAmWlgM-fSsxK:-M_118wrAmWlgM-fSsxL:b-59s07b) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c10fc3cfc96e3c090265abc9a1e84c172aa313b/pkg/cli/addjoin.go#L30)):*
> ```Go
> 
> var nodeJoinCmd = &cobra.Command{
> 	Use:   "node-join <remote-addr>",
> ```

(1st commit) Could we make this `cockroach node join`, i.e. a subcommand to `node`, instead of `cockroach node-join`
Or alternatively `cockroach connect join`
___
*[pkg/cli/addjoin.go, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63492#-M_12TCH8GQegBCDpVVD:-M_12TCH8GQegBCDpVVE:b-snp76l) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b0a888733551dda97c1699c8b841f82494942a4/pkg/cli/addjoin.go#L31)):*
> ```Go
> 	Use:   "node-join <remote-addr>",
> 	Short: "request the TLS certs for a new node from an existing node",
> 	Args:  cobra.MinimumNArgs(1),
> ```

r2: this needs to be bumped to 2, as per usage of the args below.

Also update the `Use` string above to mention the token.

(I see you change this in r5. Do you plan to squash? If yes, you can dismiss the above; if no, we'll want each individual commit to work)
___
*[pkg/cli/addjoin.go, line 34 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/63492#-M_15rPv8t6cAV0m0hxM:-M_15rPv8t6cAV0m0hxN:b-488ig7) ([raw file](https://github.com/cockroachdb/cockroach/blob/9725eefe1a4cd3d650b6946ef6da6e0309c9725d/pkg/cli/addjoin.go#L34)):*
> ```Go
> )
> 
> const nodeJoinTimeout = 1 * time.Minute
> ```

This needs to be configurable IMHO. If not here, please file a followup issue and add a link here.

You can perhaps reuse `cliCtx.cmdTimeout` which is already configurable, and add a reference to the `--timeout` flags for the new join cmd in flags.go.
___
*[pkg/cli/addjoin_test.go, line 117 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/63492#-M_16PU11rL5wX3lt9Zq:-M_16PU11rL5wX3lt9Zr:bbojxvo) ([raw file](https://github.com/cockroachdb/cockroach/blob/9725eefe1a4cd3d650b6946ef6da6e0309c9725d/pkg/cli/addjoin_test.go#L117)):*
> ```Go
> 
> 	err = runNodeJoin(nil, []string{token})
> 	require.Error(t, err)
> ```

can you assert a more specific error, so we get more confidence that the server is in fact rejecting the join token (and not failing for an unrelated reason) thanks
___
*[pkg/server/addjoin.go, line 67 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63492#-M_1AszW0DPcBwSNLoWF:-M_1AszW0DPcBwSNLoWG:b3dlrvz) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c10fc3cfc96e3c090265abc9a1e84c172aa313b/pkg/server/addjoin.go#L67)):*
> ```Go
> 	ctx context.Context, req *serverpb.BundleRequest,
> ) (*serverpb.BundleResponse, error) {
> 	// Validate Add/Join token sharedSecret.
> ```

I would recommend a cluster setting to entirely disable these two API endpoints, in case we discover after the fact that they had a security issue.
If not here, please file an issue.
___
*[pkg/server/addjoin.go, line 57 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/63492#-M_16YZjCjlrIxMwE9ZY:-M_16YZjCjlrIxMwE9ZZ:buwz25r) ([raw file](https://github.com/cockroachdb/cockroach/blob/9725eefe1a4cd3d650b6946ef6da6e0309c9725d/pkg/server/addjoin.go#L57)):*
> ```Go
> 		if err != nil {
> 			return err
> 		} else if row == nil {
> ```

`len(row) != 1`?
___
*[pkg/server/addjoin_test.go, line 87 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/63492#-M_16dPE5DdmaWZ0dTTv:-M_16dPE5DdmaWZ0dTTw:b-970fr2) ([raw file](https://github.com/cockroachdb/cockroach/blob/9725eefe1a4cd3d650b6946ef6da6e0309c9725d/pkg/server/addjoin_test.go#L87)):*
> ```Go
> 	// Try consuming the token a second time. This should fail.
> 	_, err = adminClient.RequestCertBundle(ctx, &cbReq)
> 	require.Error(t, err)
> ```

ditto, please check the specific error is indeed an invalid token error.

**Comment by knz** [comment]
(there's also a CI failure that's trying to tell you something)

**Review by itsbilal — COMMENTED** [review]
TFTR! I made my changes as an additional commit. Also helps that way as the most recent commit changes some CLI commands around (`connect` is now `connect init`, `node join` is now `connect join`). If it's good and tests pass, I'll squash everything then re-push it here. Will also add a release note for the CLI changes.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63492#-:-M_1jVmT1XDqVWFu1kiS:b-37mltx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aaron-crl and @knz)

___
*[pkg/server/addjoin.go, line 67 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63492#-M_1AszW0DPcBwSNLoWF:-M_1QU6j-RqUg4n1rd08:b-866beg) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c10fc3cfc96e3c090265abc9a1e84c172aa313b/pkg/server/addjoin.go#L67)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I would recommend a cluster setting to entirely disable these two API endpoints, in case we discover after the fact that they had a security issue.
If not here, please file an issue.
</blockquote></details>

Done. I'm just piggy-backing on the feature flag at the moment.
___
*[pkg/server/addjoin.go, line 57 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/63492#-M_16YZjCjlrIxMwE9ZY:-M_1P6cp5yKhS5oraSKs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9725eefe1a4cd3d650b6946ef6da6e0309c9725d/pkg/server/addjoin.go#L57)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`len(row) != 1`?
</blockquote></details>

Done.
___
*[pkg/server/addjoin_test.go, line 87 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/63492#-M_16dPE5DdmaWZ0dTTv:-M_1QY8a5Rhm0q4HEJZk:b-2n9xdd) ([raw file](https://github.com/cockroachdb/cockroach/blob/9725eefe1a4cd3d650b6946ef6da6e0309c9725d/pkg/server/addjoin_test.go#L87)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto, please check the specific error is indeed an invalid token error.
</blockquote></details>

The next line does this!
___
*[pkg/cli/addjoin.go, line 30 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63492#-M_118wrAmWlgM-fSsxK:-M_1SomD5mdW9jTqrKB7:b-ksf6pb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8c10fc3cfc96e3c090265abc9a1e84c172aa313b/pkg/cli/addjoin.go#L30)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

(1st commit) Could we make this `cockroach node join`, i.e. a subcommand to `node`, instead of `cockroach node-join`
Or alternatively `cockroach connect join`
</blockquote></details>

Done. I also moved `cockroach connect` to `cockroach connect init`. 
___
*[pkg/cli/addjoin.go, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63492#-M_12TCH8GQegBCDpVVD:-M_1TLcC32lxUQLZigan:b45m00s) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b0a888733551dda97c1699c8b841f82494942a4/pkg/cli/addjoin.go#L31)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

r2: this needs to be bumped to 2, as per usage of the args below.

Also update the `Use` string above to mention the token.

(I see you change this in r5. Do you plan to squash? If yes, you can dismiss the above; if no, we'll want each individual commit to work)
</blockquote></details>

Yes, I'll squash them all.
___
*[pkg/cli/addjoin.go, line 34 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/63492#-M_15rPv8t6cAV0m0hxM:-M_1Skf_B-J-QcdfCW1s:b5u6jm) ([raw file](https://github.com/cockroachdb/cockroach/blob/9725eefe1a4cd3d650b6946ef6da6e0309c9725d/pkg/cli/addjoin.go#L34)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This needs to be configurable IMHO. If not here, please file a followup issue and add a link here.

You can perhaps reuse `cliCtx.cmdTimeout` which is already configurable, and add a reference to the `--timeout` flags for the new join cmd in flags.go.
</blockquote></details>

Sure, will file a follow-up issue. Looks like `cockroach connect` also has the same issue. 
___
*[pkg/cli/addjoin_test.go, line 117 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/63492#-M_16PU11rL5wX3lt9Zq:-M_1QZyVAwu_1FKzeg7h:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9725eefe1a4cd3d650b6946ef6da6e0309c9725d/pkg/cli/addjoin_test.go#L117)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

can you assert a more specific error, so we get more confidence that the server is in fact rejecting the join token (and not failing for an unrelated reason) thanks
</blockquote></details>

Done.

**Review by knz — APPROVED** [review]
:lgtm: modulo squash and release note(s)

when you file the followup issues, can you ping this PR from each issue's description, and also link these issues to the meta-issue #60632

> Reviewed 8 of 15 files at r10, 4 of 9 files at r11, 9 of 9 files at r12.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63492#-:-M_1mllU9t4dJpBax_fh:b-4fb5dr)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aaron-crl and @itsbilal)

___
*[pkg/server/addjoin.go, line 40 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/63492#-M_1maUd-hV6FOSCBb0d:-M_1maUd-hV6FOSCBb0e:bo9b4wj) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbfc22fc5f530448d1d1e66c68ae4d07ac7ef3/pkg/server/addjoin.go#L40)):*
> ```Go
> 	settings := s.server.ClusterSettings()
> 	if settings == nil {
> 		return nil, errors.New("could not look up cluster settings")
> ```

`errors.AssertionFailedf` I think?
___
*[pkg/server/addjoin.go, line 96 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/63492#-M_1mf404vVHRC9E8z3x:-M_1mf404vVHRC9E8z3y:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbfc22fc5f530448d1d1e66c68ae4d07ac7ef3/pkg/server/addjoin.go#L96)):*
> ```Go
> 	settings := s.server.ClusterSettings()
> 	if settings == nil {
> 		return nil, errors.New("could not look up cluster settings")
> ```

ditto

**Review by itsbilal — COMMENTED** [review]
TFTR! Finished the squash and added release note.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63492#-:-M_1uwlI0ofagwIKWZGf:b-ydavq6)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aaron-crl and @knz)

___
*[pkg/server/addjoin.go, line 40 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/63492#-M_1maUd-hV6FOSCBb0d:-M_1v0maEtXv60KLFkcN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbfc22fc5f530448d1d1e66c68ae4d07ac7ef3/pkg/server/addjoin.go#L40)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`errors.AssertionFailedf` I think?
</blockquote></details>

Done.
___
*[pkg/server/addjoin.go, line 96 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/63492#-M_1mf404vVHRC9E8z3x:-M_1v11PBSvN5cUpFDMo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/04fbfc22fc5f530448d1d1e66c68ae4d07ac7ef3/pkg/server/addjoin.go#L96)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Comment by itsbilal** [comment]
bors r=knz

**Comment by itsbilal** [comment]
Follow-up issues:

* Configurable timeouts in connect cli commands: #64878 
* Code duplication: #64883
* Using CertificateManager instead of CertsLocator: #64884
* Versioned join tokens: #64885

**Pull request merged**
