### PR TITLE
roachtest: add unoptimized-query-oracle test to validate query results

### LINKED ISSUE #83090: roachtest: create a test to validate query results by disabling the optimizer and vectorized engine
We should build a test to disable all non-essential transformation rules in the optimizer to build a “default” plan and execute it with the row-based engine as an oracle. Compare the result to the fully optimized plan executed with the vectorized engine.

Epic: CRDB-14020
Jira issue: CRDB-16857

### PR DESCRIPTION
**Pull request by rytaft**
Add a new roachtest that leverages SQLSmith statement generation as well as
the optimizer's ability to disable all non-essential rules. The test repeatedly
creates a random statement, runs it first with the optimizer rules and
vectorized execution disabled, then runs it with one or both enabled as normal.
If the results of the two executions are not identical, it likely indicates a
bug in the optimizer or execution engine.

This test is similar in structure to the costfuzz test, and much of the code is
copied from the costfuzz test.

Closes https://github.com/cockroachdb/cockroach/issues/83090

Release note: None

### CODE REVIEW

**Comment by rytaft** [comment]
I've been running this test on my local machine, and it's already found https://github.com/cockroachdb/cockroach/issues/83091, https://github.com/cockroachdb/cockroach/issues/83093, and https://github.com/cockroachdb/cockroach/issues/83094.

**Comment by petermattis** [comment]
This is really neat!

Is there any benefit to disabling a random subset of the non-essential optimizer rules rather than completely disabling them?

**Review by rytaft — COMMENTED** [review]
Thanks!

> Is there any benefit to disabling a random subset of the non-essential optimizer rules rather than completely disabling them?

I think there is value in doing both -- I've added a second test config that does this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83095#-:-N5272hhBEbkETRmtKoL:b5rvdz6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @msirek)

**Review by msirek — CHANGES_REQUESTED** [review]
Very cool! I have a feeling this will uncover more than a few bugs.
Should we add more rewrites to the list in `Optimizer.disableRules` to get more varied plans, or maybe create an issue for this?

> Reviewed 11 of 11 files at r3, 12 of 12 files at r4, 12 of 12 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83095#-:-N5648OYCT5UGxs1A6WF:bl3ghwi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @michae2 and @rytaft)

___
*[`pkg/sql/opt/xform/optimizer.go` line 133 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/83095#-N562HYM-sWfZqiaIOma:-N562HYM-sWfZqiaIOmb:b-rbrlcr) ([raw file](https://github.com/cockroachdb/cockroach/blob/58b094f98bcb48b40fde2706f6c8e06db211818a/pkg/sql/opt/xform/optimizer.go#L133)):*
> ```Go
> 		o.rng = rand.New(rand.NewSource(seed))
> 	}
> 	if perturbation := evalCtx.SessionData().TestingOptimizerCostPerturbation; perturbation != 0 {
> ```

For this flag and the one below, we should set `evalCtx.TestingKnobs` even if `perturbation` or `probability` is zero, otherwise we won't be able to reset these to their default values after setting them to non-default values.

**Review by michae2 — CHANGES_REQUESTED** [review]
Nice!

This is just a thought, not even a nit, but it seems like we could push the factoring of common code even further. `runCostFuzzQuery` and `runUnoptimizedQueryOracleImpl` are both roughly:
1. generate query
2. execute setup statements
3. execute oracle query
4. execute more setup statements
5. execute test query
6. compare results of oracle and test
7. execute teardown statements

And come to think of it, `runTLPQuery` also follows this pattern (with no-ops for steps 2, 4, and 7).

But I'm not sure how important more factoring is. This is just roachtest, after all.

(This similarity does mean that `reduce -costfuzz` will work for unoptimized-query-oracle, too, with a tweak: instead of counting three queries at the end of the log, we should log some sentinel comments / `SELECT` statements around steps 3 and 5 in both costfuzz and unoptimized-query-oracle and look for those in `reduce`. But that can be another PR.)

> Reviewed 11 of 11 files at r3, 12 of 12 files at r4, 12 of 12 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83095#-:-N58n3a83Jft-GvsGknB:b-qbiyw2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[`pkg/sql/vars.go` line 2044 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/83095#-N57h65v-E7pLvZJsonc:-N57h65v-E7pLvZJsond:bp5uehf) ([raw file](https://github.com/cockroachdb/cockroach/blob/50c8055cea2dda108fb257922fe96308f84bc120/pkg/sql/vars.go#L2044)):*
> ```Go
> 			if err != nil {
> 				return err
> 			}
> ```

nit: We should check that f >= 0 here.
___
*[`pkg/sql/vars.go` line 2065 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/83095#-N58oGYEDc4R8mtuXfd1:-N58oGYEDc4R8mtuXfd2:b-qz8yea) ([raw file](https://github.com/cockroachdb/cockroach/blob/58b094f98bcb48b40fde2706f6c8e06db211818a/pkg/sql/vars.go#L2065)):*
> ```Go
> 			if err != nil {
> 				return err
> 			}
> ```

nit: We should check that f >= 0 and f <= 1 here.
___
*[`pkg/sql/opt/xform/optimizer.go` line 141 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/83095#-N57iEa9E1NuZYuC3N_J:-N57iEa9E1NuZYuC3N_K:b-x3up70) ([raw file](https://github.com/cockroachdb/cockroach/blob/50c8055cea2dda108fb257922fe96308f84bc120/pkg/sql/opt/xform/optimizer.go#L141)):*
> ```Go
> 	if o.rng == nil && (evalCtx.TestingKnobs.OptimizerCostPerturbation != 0 ||
> 		evalCtx.TestingKnobs.DisableOptimizerRuleProbability != 0) {
> 		o.rng, _ = randutil.NewPseudoRand()
> ```

Calling `randutil.NewPseudoRand` in this function is how I ended up causing #81519.

Do we need to assign `o.rng` here? I believe cost perturbation will still work with a nil `o.rng`, thanks to this code: https://github.com/cockroachdb/cockroach/blob/13cb2f6c40e3146fed8d931f65f89da9b42ce2c1/pkg/sql/opt/xform/coster.go#L563-L567

Maybe we need similar checks in `disableRules`?

**Review by mgartner — APPROVED** [review]
Very cool!

> Reviewed 11 of 11 files at r3, 12 of 12 files at r4, 12 of 12 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83095#-:-N5ATOSpCM5cOIXLDCRC:b-jdo7t9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[`pkg/sql/opt/xform/optimizer.go` line 102 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/83095#-N5ASWwX1z6oO82jxy2H:-N5ASWwX1z6oO82jxy2I:bp77mmc) ([raw file](https://github.com/cockroachdb/cockroach/blob/50c8055cea2dda108fb257922fe96308f84bc120/pkg/sql/opt/xform/optimizer.go#L102)):*
> ```Go
> 	jb JoinOrderBuilder
> 
> 	// rng is used to deterministically perturb costs.
> ```

nit: update this comment to say that it is also used to disable rules.
___
*[`pkg/sql/opt/xform/optimizer.go` line 141 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/83095#-N5ASkIADlI7qZNY1ZwX:-N5ASkIADlI7qZNY1ZwY:b-jzrfz6) ([raw file](https://github.com/cockroachdb/cockroach/blob/50c8055cea2dda108fb257922fe96308f84bc120/pkg/sql/opt/xform/optimizer.go#L141)):*
> ```Go
> 	if o.rng == nil && (evalCtx.TestingKnobs.OptimizerCostPerturbation != 0 ||
> 		evalCtx.TestingKnobs.DisableOptimizerRuleProbability != 0) {
> 		o.rng, _ = randutil.NewPseudoRand()
> ```

Shouldn't this use the provided seed?

**Review by rytaft — COMMENTED** [review]
TFTRs! Updated.

@michae2 I did a bit more refactoring... I'm sure I could do more but not sure it's worth it at this point. Let me know what you think. I'll wait for a future PR to incorporate TLP into this model. And thanks for the pointer about reduce -- I tweaked the reduce code in this PR so I wouldn't break the `costfuzz` option, but I'll add support for `unoptimized-query-oracle` in a separate PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83095#-:-N61ilCq5gav_I3Z-3ud:b-yzu7af)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @michae2, and @msirek)

___
*[`pkg/sql/vars.go` line 2044 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/83095#-N57h65v-E7pLvZJsonc:-N61f30L7hOYFCYd7CJ_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/50c8055cea2dda108fb257922fe96308f84bc120/pkg/sql/vars.go#L2044)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: We should check that f >= 0 here.
</blockquote></details>

Done.
___
*[`pkg/sql/vars.go` line 2065 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/83095#-N58oGYEDc4R8mtuXfd1:-N61g5pXERLja_Ds4_XU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/58b094f98bcb48b40fde2706f6c8e06db211818a/pkg/sql/vars.go#L2065)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: We should check that f >= 0 and f <= 1 here.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/xform/optimizer.go` line 102 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/83095#-N5ASWwX1z6oO82jxy2H:-N61e-Md2UGLTWHmW1gk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/50c8055cea2dda108fb257922fe96308f84bc120/pkg/sql/opt/xform/optimizer.go#L102)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: update this comment to say that it is also used to disable rules.
</blockquote></details>

Done.
___
*[`pkg/sql/opt/xform/optimizer.go` line 141 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/83095#-N5ASkIADlI7qZNY1ZwX:-N61dKRDDDW6hcFNU9OT:bc251a0) ([raw file](https://github.com/cockroachdb/cockroach/blob/50c8055cea2dda108fb257922fe96308f84bc120/pkg/sql/opt/xform/optimizer.go#L141)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Shouldn't this use the provided seed?
</blockquote></details>

`o.rng` is only `nil` here if `seed` is 0
___
*[`pkg/sql/opt/xform/optimizer.go` line 141 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/83095#-N57iEa9E1NuZYuC3N_J:-N61eTAC1CnRZCixxH6y:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/50c8055cea2dda108fb257922fe96308f84bc120/pkg/sql/opt/xform/optimizer.go#L141)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Calling `randutil.NewPseudoRand` in this function is how I ended up causing #81519.

Do we need to assign `o.rng` here? I believe cost perturbation will still work with a nil `o.rng`, thanks to this code: https://github.com/cockroachdb/cockroach/blob/13cb2f6c40e3146fed8d931f65f89da9b42ce2c1/pkg/sql/opt/xform/coster.go#L563-L567

Maybe we need similar checks in `disableRules`?
</blockquote></details>

Done.
___
*[`pkg/sql/opt/xform/optimizer.go` line 133 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/83095#-N562HYM-sWfZqiaIOma:-N61eMrVAg3JeePYIadT:b-u94w4b) ([raw file](https://github.com/cockroachdb/cockroach/blob/58b094f98bcb48b40fde2706f6c8e06db211818a/pkg/sql/opt/xform/optimizer.go#L133)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

For this flag and the one below, we should set `evalCtx.TestingKnobs` even if `perturbation` or `probability` is zero, otherwise we won't be able to reset these to their default values after setting them to non-default values.
</blockquote></details>

Fixed this so we don't override the values of `evalCtx.TestingKnobs` at all

**Review by michae2 — APPROVED** [review]
:lgtm: Very nice. This is going to catch a ton of bugs. :fishing_pole_and_fish:

> Reviewed 15 of 15 files at r6, 13 of 13 files at r7, 15 of 15 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83095#-:-N6KgNAA36X1Y5_Ln5Pq:brfivlm)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek and @rytaft)

___
*[`pkg/cmd/roachtest/tests/query_comparison_util.go` line 105 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/83095#-N6KStsI9bYnBxrTL9AJ:-N6KStsI9bYnBxrTL9AK:bpoj3x9) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a051c81253c49e03efc1b437de67c98e0e2ac58/pkg/cmd/roachtest/tests/query_comparison_util.go#L105)):*
> ```Go
> 			return
> 		}
> 		fmt.Fprint(costFuzzLog, stmt)
> ```

Thank you for catching this!
___
*[`pkg/cmd/roachtest/tests/unoptimized_query_oracle.go` line 160 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/83095#-N6KfGEI43aIbqDx1SuD:-N6KfGEI43aIbqDx1SuE:b-vf5yjg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b32e027db388674106ca3113af3085f04a23c327/pkg/cmd/roachtest/tests/unoptimized_query_oracle.go#L160)):*
> ```Go
> 	}
> 
> 	return nil
> ```

nit: It might be worth ensuring all variables have been `RESET` at the very end, in case we follow this with one of the occasional mutation statements in `runOneRoundQueryComparison`.
___
*[`pkg/sql/vars.go` line 2063 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/83095#-N6Ka2be5DaOTPkHME8k:-N6Ka2be5DaOTPkHME8l:briww8r) ([raw file](https://github.com/cockroachdb/cockroach/blob/b32e027db388674106ca3113af3085f04a23c327/pkg/sql/vars.go#L2063)):*
> ```Go
> 			}
> 			if f < 0 {
> 				return errors.New("testing_optimizer_cost_perturbation must be non-negative")
> ```

nit: I think calling `pgerror.Newf` or `newVarValueError` would be a little nicer.
___
*[`pkg/sql/vars.go` line 2087 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/83095#-N6KbsqG-W1ipquMIQi6:-N6KbsqG-W1ipquMIQi7:btru7fi) ([raw file](https://github.com/cockroachdb/cockroach/blob/b32e027db388674106ca3113af3085f04a23c327/pkg/sql/vars.go#L2087)):*
> ```Go
> 			}
> 			if f < 0 || f > 1 {
> 				return errors.New("testing_optimizer_disable_rule_probability must be in the range [0.0,1.0]")
> ```

nit: Same comment about `pgerror.Newf` or `newVarValueError`.

**Review by rytaft — COMMENTED** [review]
TFTRs! I'm guessing I'll need to skip this test until we fix the bugs this has already found, but I'm going to go ahead and merge this and see what happens. If it fails on the next nightly with a bug we already know about I'll open another PR to skip it.

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83095#-:-N6LcVn_CW1bAdLdiRQ0:b-ddr0mz)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @michae2, and @msirek)

___
*[`pkg/cmd/roachtest/tests/query_comparison_util.go` line 105 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/83095#-N6KStsI9bYnBxrTL9AJ:-N6LZ20-4FZ4c70ECDb0:b2ni8oq) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a051c81253c49e03efc1b437de67c98e0e2ac58/pkg/cmd/roachtest/tests/query_comparison_util.go#L105)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

Thank you for catching this!
</blockquote></details>

np!
___
*[`pkg/cmd/roachtest/tests/unoptimized_query_oracle.go` line 160 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/83095#-N6KfGEI43aIbqDx1SuD:-N6LZXms7JIdb_oV3C2R:b-yh16l6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b32e027db388674106ca3113af3085f04a23c327/pkg/cmd/roachtest/tests/unoptimized_query_oracle.go#L160)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: It might be worth ensuring all variables have been `RESET` at the very end, in case we follow this with one of the occasional mutation statements in `runOneRoundQueryComparison`.
</blockquote></details>

Done. Good call.
___
*[`pkg/sql/vars.go` line 2063 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/83095#-N6Ka2be5DaOTPkHME8k:-N6LYw7rAnJRTDZGMSAy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b32e027db388674106ca3113af3085f04a23c327/pkg/sql/vars.go#L2063)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: I think calling `pgerror.Newf` or `newVarValueError` would be a little nicer.
</blockquote></details>

Done.
___
*[`pkg/sql/vars.go` line 2087 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/83095#-N6KbsqG-W1ipquMIQi6:-N6LYx6r0Xqt3pdaP4le:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b32e027db388674106ca3113af3085f04a23c327/pkg/sql/vars.go#L2087)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: Same comment about `pgerror.Newf` or `newVarValueError`.
</blockquote></details>

Done.

**Pull request merged**
