### PR TITLE
sql: add ULID entropy to eval context

### LINKED ISSUE #115666: Significant performance difference between gen_random_ulid() and gen_random_uuid()
Hi there! This is not so much a bug or crash report as it is an observed difference in performance when generating ULIDs vs UUID V4s. I would really like to use the ULID functionality introduced in https://github.com/cockroachdb/cockroach/pull/62440, but I got a bit curious around about performance vs other mechanisms and decided to run some benchmarking. It turned out that generating a single ULID takes 2ms! When I benchmarked a sequence of 10 million operations, I saw that generating a UUIDs is something like 16.8x faster than generating ULIDs.

As someone who isn't yet familiar with all the intricacies, I'm curious whether this is simply the nature of ULID, or if we perhaps have a sub-optimal routine for generation. Could anyone who knows more about this topic please weigh in?

#### UUIDv4: 748µs
```sql
explain analyze select gen_random_uuid();
              info
---------------------------------
 planning time: 280µs
 execution time: 748µs
 distribution: local
 vectorized: true
 maximum memory usage: 10 KiB
 network usage: 0 B (0 messages)
 sql cpu time: 62µs

 • values
   nodes: n1
   actual row count: 1
   sql cpu time: 62µs
   size: 1 column, 1 row
(13 rows)
```
#### ULID: 2ms
```sql
explain analyze select gen_random_ulid();
              info
---------------------------------
 planning time: 470µs
 execution time: 2ms
 distribution: local
 vectorized: true
 maximum memory usage: 10 KiB
 network usage: 0 B (0 messages)
 sql cpu time: 1ms

 • values
   nodes: n1
   actual row count: 1
   sql cpu time: 1ms
   size: 1 column, 1 row
(13 rows)
```

#### UUIDv4: 4.7s
```sql
explain analyze select gen_random_uuid() from generate_series(1, 10e6);
                info
------------------------------------
 planning time: 703µs
 execution time: 4.7s
 distribution: local
 vectorized: true
 maximum memory usage: 160 KiB
 network usage: 0 B (0 messages)
 sql cpu time: 2s

 • render
 │
 └── • project set
     │ nodes: n1
     │ actual row count: 10,000,000
     │ sql cpu time: 2s
     │ estimated row count: 10
     │
     └── • emptyrow
           nodes: n1
           actual row count: 1
           sql cpu time: 2µs
(20 rows)
```

#### ULID: 1m19s
```sql
explain analyze select gen_random_ulid() from generate_series(1, 10e6);
                info
------------------------------------
 planning time: 859µs
 execution time: 1m19s
 distribution: local
 vectorized: true
 maximum memory usage: 160 KiB
 network usage: 0 B (0 messages)
 sql cpu time: 8.7s

 • render
 │
 └── • project set
     │ nodes: n1
     │ actual row count: 10,000,000
     │ sql cpu time: 8.7s
     │ estimated row count: 10
     │
     └── • emptyrow
           nodes: n1
           actual row count: 1
           sql cpu time: 2µs
(20 rows)
```

**Environment:**
 - CockroachDB version: v23.1.12
 - Server OS: Official CockroachDB Docker Image
 - Client app: `psql` command

### PR DESCRIPTION
**Pull request by rafiss**
Rather than making a new entropy source for each invocation, now it is
shared for all usages of the same eval context.

```
goos: darwin
goarch: arm64
                                        │    old.txt    │               new.txt                │
                                        │    sec/op     │    sec/op     vs base                │
GenerateID/gen_random_uuid/rows=1-10        82.94µ ± 1%   82.97µ ±  1%        ~ (p=0.870 n=10)
GenerateID/gen_random_uuid/rows=10-10       91.06µ ± 1%   91.22µ ±  1%        ~ (p=0.631 n=10)
GenerateID/gen_random_uuid/rows=100-10      164.8µ ± 3%   164.9µ ±  1%        ~ (p=1.000 n=10)
GenerateID/gen_random_uuid/rows=1000-10     926.2µ ± 3%   926.7µ ±  5%        ~ (p=0.529 n=10)
GenerateID/gen_random_ulid/rows=1-10       101.88µ ± 1%   80.07µ ±  1%  -21.41% (p=0.000 n=10)
GenerateID/gen_random_ulid/rows=10-10      223.72µ ± 9%   85.15µ ± 33%  -61.94% (p=0.000 n=10)
GenerateID/gen_random_ulid/rows=100-10     1174.6µ ± 1%   120.5µ ± 39%  -89.74% (p=0.000 n=10)
GenerateID/gen_random_ulid/rows=1000-10   10386.2µ ± 1%   464.5µ ±  8%  -95.53% (p=0.000 n=10)
geomean                                     365.8µ        160.5µ        -56.11%

                                        │    old.txt     │                new.txt                │
                                        │      B/op      │     B/op       vs base                │
GenerateID/gen_random_uuid/rows=1-10       32.27Ki ±  6%   32.28Ki ±  7%        ~ (p=1.000 n=10)
GenerateID/gen_random_uuid/rows=10-10      34.57Ki ±  6%   34.55Ki ±  6%        ~ (p=0.529 n=10)
GenerateID/gen_random_uuid/rows=100-10     49.94Ki ±  0%   49.91Ki ±  0%        ~ (p=0.382 n=10)
GenerateID/gen_random_uuid/rows=1000-10    318.9Ki ± 46%   319.3Ki ± 61%        ~ (p=0.796 n=10)
GenerateID/gen_random_ulid/rows=1-10       40.52Ki ±  0%   32.16Ki ±  0%  -20.63% (p=0.000 n=10)
GenerateID/gen_random_ulid/rows=10-10      80.37Ki ±  7%   34.46Ki ±  5%  -57.12% (p=0.000 n=10)
GenerateID/gen_random_ulid/rows=100-10    470.89Ki ±  0%   49.81Ki ±  0%  -89.42% (p=0.000 n=10)
GenerateID/gen_random_ulid/rows=1000-10   4489.5Ki ±  0%   318.4Ki ±  4%  -92.91% (p=0.000 n=10)
geomean                                    136.7Ki         64.84Ki        -52.59%

                                        │    old.txt    │               new.txt                │
                                        │   allocs/op   │  allocs/op    vs base                │
GenerateID/gen_random_uuid/rows=1-10        405.0 ±  9%    405.0 ±  9%        ~ (p=0.940 n=10)
GenerateID/gen_random_uuid/rows=10-10       480.0 ±  1%    480.0 ±  0%        ~ (p=0.463 n=10)
GenerateID/gen_random_uuid/rows=100-10      975.0 ±  0%    975.0 ±  0%        ~ (p=0.685 n=10)
GenerateID/gen_random_uuid/rows=1000-10    7.041k ± 18%   7.041k ± 17%        ~ (p=0.639 n=10)
GenerateID/gen_random_ulid/rows=1-10        411.0 ±  0%    405.0 ±  0%   -1.46% (p=0.000 n=10)
GenerateID/gen_random_ulid/rows=10-10       513.5 ± 18%    480.0 ±  8%   -6.52% (p=0.006 n=10)
GenerateID/gen_random_ulid/rows=100-10     1281.5 ±  0%    975.0 ±  0%  -23.92% (p=0.000 n=10)
GenerateID/gen_random_ulid/rows=1000-10   10.062k ±  0%   7.040k ±  3%  -30.03% (p=0.000 n=10)
geomean                                    1.175k         1.075k         -8.52%
```

fixes https://github.com/cockroachdb/cockroach/issues/115666
Release note (performance improvement): Improved the performance of the gen_random_ulid builtin function.

### CODE REVIEW

**Review by fqazi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 10 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115737#-:-Nl1LrUNC3AXiRFp3GoH:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by rafiss** [comment]
tftr!

bors r+

**Review by yuzefovich — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/115737#-:-Nl4EUQhBg4DCZjbTH_K:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained

___
*[`pkg/sql/sem/builtins/builtins.go` line 793 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/115737#-Nl4EAy14BXGX-ptW2xU:-Nl4EAy14BXGX-ptW2xV:bok7sx2) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d3e198aab01530824c19032d6928d859b86cfe8/pkg/sql/sem/builtins/builtins.go#L793)):*
> ```Go
> 			ReturnType: tree.FixedReturnType(types.Uuid),
> 			Fn: func(_ context.Context, evalCtx *eval.Context, _ tree.Datums) (tree.Datum, error) {
> 				uv := ulid.MustNew(ulid.Now(), evalCtx.ULIDEntropy)
> ```

nit: just a drive-by: should we do `s/MustNew/New/` since the former can panic in theory?

**Review by mgartner — COMMENTED** [review]
Nice find!

**Pull request merged**
