### PR TITLE
kvserver: avoid unprotected keyspace during MergeRange

### PR DESCRIPTION
**Pull request by tbg**
In #73721 we saw the following assertion fire:

> kv/kvserver/replica_raftstorage.go:932  [n4,s4,r46/3:{-}] 1  unable to
> remove placeholder: corrupted replicasByKey map: <nil> and [...]

This is because `MergeRange` removes from the Store's in-memory map the
right-hand side Replica before extending the left-hand side, leaving a
gap for a snapshot to sneak in. A similar problem exists when a snapshot
widens the existing range (i.e. the snapshot reflects the results of a
merge). This commit closes both gaps.

I verified the fix by calling the newly-introduced (but promptly
disabled, see comment within) `(*Store).maybeAssertNoHole` from
both `(*Store).MergeRange` and `applySnapshot`.

The bug reproduced via this assertion, before this fix, in
`TestStoreRangeMergeTimestampCache` and
`TestChangeReplicasLeaveAtomicRacesWithMerge`, covering both the
snapshot and merge trigger cases. I'm not too happy to merge this
without the same kind of active test coverage, but since this will
require a backport, it's better not to rattle the cage too much.
I filed #74384 to clean this up fully.

Release note (bug fix): A bug was fixed that, in very rare cases, could
result in a node terminating with fatal error "unable to remove
placeholder: corrupted replicasByKey map". To avoid potential data
corruption, users affected by this crash should not restart the node,
but instead decommission it in absentia and have it rejoin the cluster
under a new NodeID.

### CODE REVIEW

**Comment by tbg** [comment]
I'm sure CI will find some reason to fail, but this is RFAL.

**Comment by tbg** [comment]
(Note that the last commit isn't intended to be merged, but I'm taking ideas on how to incorporate the testing in it)

**Comment by tbg** [comment]
Friendly ping.

**Review by erikgrinaker — COMMENTED** [review]
I share your dissatisfaction with the complexity here, this all seems pretty brittle. Your suggestions seem fine on the face of it, but I'm not familiar enough with the details here to say whether there are better options.

Also, sorry for the late review -- this fell through the cracks somehow.

**Review by tbg — COMMENTED** [review]
Filed https://github.com/cockroachdb/cockroach/issues/74384 to improve the overall locking story.
RFAL.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73734#-:-MsV5lhbBWgB34xH25N6:btrmmty)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

___
*[pkg/kv/kvserver/store_remove_replica.go, line 85 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73734#-Mr6gaaJY4iCYbTI1dn2-r2-85:-MsUorOV9rNTBzOrBV9B:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d1c09dd84a6237acaafff50af1b653a8cd98c4b/pkg/kv/kvserver/store_remove_replica.go#L85)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Do we even need to check this, since the method is explicitly only for initialized replicas? We could even just assert that outside the `InsertPlaceholder` branch, but I get why we're only checking it here. Your call.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/helpers_test.go, line 208 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73734#-Mr7fH1P7IW30sSPswut-r2-208:-MsUsFLo4mlIwsBIRUdA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d1c09dd84a6237acaafff50af1b653a8cd98c4b/pkg/kv/kvserver/helpers_test.go#L208)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

This could use a comment explaining that it runs async and the caller needs to call the returned function to stop the task.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/helpers_test.go, line 218 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/73734#-Mr7fH1P7IW30sSPswut-r2-218:-MsVHK6R14VnFb5KTDU3:bfyzzba) ([raw file](https://github.com/cockroachdb/cockroach/blob/3d1c09dd84a6237acaafff50af1b653a8cd98c4b/pkg/kv/kvserver/helpers_test.go#L218)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Yeah, this needs to be conditional for non-production builds. Checking `buildutil.CrdbTestBuild`, as you mention, seems reasonable here -- it might turn out that the tight mutex acquisition is expensive enough that we should only do it for race builds.
</blockquote></details>

After I made the assertion actually check what it says and should check (there is no hole, vs what it does now which is check that there's at least some item within the monitored keyspan) I've been getting intermittent deadlocks. This isn't very surprising since iterating through the btree calls `.Desc()`; this has always been deadlock prone. I'll leave the code in (it's useful for manual spot checks as I've done so far) and hope to arm it after #74384.

**Review by erikgrinaker — APPROVED** [review]
Sounds good, LGTM.

**Comment by tbg** [comment]
bors r=erikgrinaker

**Comment by rafiss** [comment]
does this PR still need a backport?

**Comment by tbg** [comment]
Yes, but see https://github.com/cockroachdb/cockroach/issues/73721#issuecomment-1004775880 for the timing of the backport.

**Pull request merged**
