### PR TITLE
storage: add roachpb.InternalTimeSeriesData to below-raft-protos whitelist

### PR DESCRIPTION
**Pull request by petermattis**
`roachpb.InternalTimeSeriesData` is marshalled below Raft by the Pebble
merge operator. The Pebble merge operator can be called below Raft
whenever a Pebble Iterator is used.

See #42353

Release note: None

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42458)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @tbg)

___
*[pkg/storage/track_raft_protos.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42458#-LtaVQt3DqgWgY-gPM6E:-LtaVQt3DqgWgY-gPM6F:b-m1a4q9) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c5dfa13954f088e108d59fd618839a29c3abc41/pkg/storage/track_raft_protos.go#L59)):*
> ```Go
> 		// needed to marshal roachpb.InternalTimeSeriesData. The Pebble merge
> 		// operator can be called below Raft whenever a Pebble Iterator is used.
> 		funcName((*engine.MVCCValueMerger).Finish),
> ```

Is this the right approach, or am I supposed to add to `belowRaftGoldenProtos`?

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42458)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @tbg)

___
*[pkg/storage/track_raft_protos.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42458#-LtaVQt3DqgWgY-gPM6E:-LtaaQ0dBjukdo9mPfEF:b-nj5y9k) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c5dfa13954f088e108d59fd618839a29c3abc41/pkg/storage/track_raft_protos.go#L59)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is this the right approach, or am I supposed to add to `belowRaftGoldenProtos`?
</blockquote></details>

Looking at this more, I think `belowRaftGoldenProtos` is the right approach. I've pushed a new commit.

**Review by tbg — APPROVED** [review]

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42458#-:-LtkfSa918RMdFMXxVC3:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @petermattis)

___
*[pkg/storage/track_raft_protos.go, line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42458#-LtaVQt3DqgWgY-gPM6E:-LtkfRSP-xvX13o_Rugq:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/2c5dfa13954f088e108d59fd618839a29c3abc41/pkg/storage/track_raft_protos.go#L59)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Looking at this more, I think `belowRaftGoldenProtos` is the right approach. I've pushed a new commit.
</blockquote></details>

:thumbsup:

**Comment by petermattis** [comment]
Gah. CI is failing because without `COCKROACH_STORAGE_ENGINE=pebble`: `*roachpb.InternalTimeSeriesData: not observed below raft!`.

**Comment by tbg** [comment]
Make the addition to the golden proto list conditional on the env var?

**Comment by petermattis** [comment]
> Make the addition to the golden proto list conditional on the env var?

Yeah, that looks workable. Done.

**Comment by petermattis** [comment]
TFTR!

bors r+

**Comment by petermattis** [comment]
Bors failed on some UI dependency weirdness.

bors r+

**Comment by petermattis** [comment]
Test timeout in the `cli` package. Unrelated to this change.

bors r+

**Comment by tbg** [comment]
TestDockerCLI again

bors r+

**Pull request merged**
