### PR TITLE
opt: wire up table statistics

### PR DESCRIPTION
**Pull request by RaduBerinde**
Setting up the statistics cache in the `ExecutorConfig` and
implementing the statistics part of the catalog.

Release note: None

### CODE REVIEW

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24724#-:-L9uWg0LAjtxDRh8ivHX:bnfp4nl)*

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24724#-:-L9uZhtK6M-FukyKPOVu:bnfp4nl)*

**Comment by andy-kimball** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[pkg/sql/opt_catalog.go, line 181 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24724#-L9uj1U70CqXEAz6Eq5_:-L9uj1U70CqXEAz6Eq5a:b-2bheml) ([raw file](https://github.com/cockroachdb/cockroach/blob/7856be2a31aa667c34517f0c2048dce8eab43ffa/pkg/sql/opt_catalog.go#L181)):*
> ```Go
> }
> 
> func (ot *optTable) initColMap() {
> ```

NIT: I often call a method like this `ensureColMap` rather than `initColMap`, to make it clear that we're just making sure it's initialized, since often it will already be initialized. I don't feel strongly about this, though.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24724#-:-L9ukJE8C6f4NpnobFAO:bnfp4nl)*

**Comment by RaduBerinde** [comment]
TFTRs!

bors r+

---

Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/opt_catalog.go, line 181 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24724#-L9uj1U70CqXEAz6Eq5_:-L9uuBmCBN8-KG0uU-nH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7856be2a31aa667c34517f0c2048dce8eab43ffa/pkg/sql/opt_catalog.go#L181)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: I often call a method like this `ensureColMap` rather than `initColMap`, to make it clear that we're just making sure it's initialized, since often it will already be initialized. I don't feel strongly about this, though.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24724#-:-L9uuCPJ30wWtXUSE12r:b-tlx7ko)*

**Pull request merged**
