### PR TITLE
Handle WriteIntentErrors in Range.Snapshot.

### LINKED ISSUE #1187: crash in raft.sendAppend: error from range_raftstorage.go:245
```
E0528 20:47:12.818151       1 queue.go:262] failure processing range range=1 (""-"\xff\xff") from replicate queue: allocator.go:207: unable to allocate a target store for {[] }
I0528 20:47:12.849569       1 client.go:150] client roach1.local:8080 connected
I0528 20:47:12.849768       1 client.go:224] client roach1.local:8080 starting heartbeat
E0528 20:47:13.210226       1 queue.go:262] failure processing range range=1 (""-"\xff\xff") from replicate queue: allocator.go:207: unable to allocate a target store for {[] }
E0528 20:47:13.622575       1 queue.go:262] failure processing range range=1 (""-"\xff\xff") from replicate queue: allocator.go:207: unable to allocate a target store for {[] }
E0528 20:47:14.024363       1 queue.go:262] failure processing range range=1 (""-"\xff\xff") from replicate queue: allocator.go:207: unable to allocate a target store for {[] }
E0528 20:47:14.428034       1 queue.go:262] failure processing range range=1 (""-"\xff\xff") from replicate queue: allocator.go:207: unable to allocate a target store for {[] }
I0528 20:47:14.563834       1 server.go:111] gossip: received 7 info(s) from 172.17.0.191:8080
I0528 20:47:14.901081       1 client.go:150] client roach2.local:8080 connected
I0528 20:47:14.901209       1 client.go:224] client roach2.local:8080 starting heartbeat
panic: range_raftstorage.go:245: failed to get desc: conflicting write intents [{Key:"\x00\x00\x00k\x00\x01rdsc" Txn:"change replicas of 1" {id=d751d638-91ea-41f4-88a2-e946d05ebe02 pri=1579927167, iso=SERIALIZABLE, stat=PENDING, epo=0, ts=1432846034.852988720,0 orig=1432846034.852988720,0 max=1432846035.102988482,0} XXX_unrecognized:[]}]: resolved? false

goroutine 19 [running]:
github.com/coreos/etcd/raft.(*raft).sendAppend(0xc208182000, 0x300000003)
	/go/src/github.com/coreos/etcd/raft/raft.go:250 +0x159
github.com/coreos/etcd/raft.stepLeader(0xc208182000, 0x4, 0x100000001, 0x300000003, 0x7, 0x0, 0xa3, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/coreos/etcd/raft/raft.go:523 +0x6f3
github.com/coreos/etcd/raft.(*raft).Step(0xc208182000, 0x4, 0x100000001, 0x300000003, 0x7, 0x0, 0xa3, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/coreos/etcd/raft/raft.go:487 +0x259
github.com/coreos/etcd/raft.(*multiNode).run(0xc208112840)
	/go/src/github.com/coreos/etcd/raft/multinode.go:236 +0xd0b
created by github.com/coreos/etcd/raft.StartMultiNode
	/go/src/github.com/coreos/etcd/raft/multinode.go:56 +0xb6
```
full log: https://gist.github.com/tamird/b4cdde131fe7aa464e92

discovered when running PutTest with 5 nodes.

### PR DESCRIPTION
**Pull request by bdarnell**
This fixes a panic when Snapshot runs concurrently with a transaction on
the range descriptor, such as AdminSplit.

Parse values in MVCCGetProto when a WriteIntentError occurs; document
and test this behavior.

Fixes #1187.

### CODE REVIEW

**Comment by tschottdorf** [comment]
This pattern of returning a valid value for WriteIntentErrors looks like it could cause problems (since you always have to check this when reading inconsistently). I think it would be cleaner to instead move from the `optional` bool to having three valid options:

* consistent read
* inconsistent read, ignoring WriteIntentErrors
* inconsistent read, but return WriteIntentErrors

That seems more stable for future uses, where the casual user of MVCCGet may not be aware of all the special casing.

Other than that, LGTM.

**Comment by bdarnell** [comment]
That was my first thought, but I think it ends up complicating things: you now have more possible code paths in this critical function. I don't think there are "casual" uses of MVCCGet, especially in inconsistent mode.

**Comment by tschottdorf** [comment]
Ok, works for me.

**Comment by tamird** [comment]
LGTM

**Pull request merged**
