### PR TITLE
storage: add replica pointer tag

### PR DESCRIPTION
**Pull request by petermattis**
Debugging aid for #11591.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/11683)

### CODE REVIEW

**Review by a-robinson — APPROVED** [review]
LGTM, although is this intended to be kept permanently?

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/storage/replica.go, line 576 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11683#-KXk_0Hcnhfw2FSAw5kd:-KXk_0Hcnhfw2FSAw5ke:b-bc9mm) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa229e81a9fd2cab9fb411f6a8b2e80f37df5aa2/pkg/storage/replica.go#L576)):*
> ```Go
> 	r.AmbientContext.AddLogTag("r", &r.rangeStr)
> 	// Add replica pointer value.
> 	r.AmbientContext.AddLogTagStr("@", fmt.Sprintf("%x", r))
> ```

not %p?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11683#-:-KXk_-MxiRsIQi-CeyhG:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/storage/replica.go, line 576 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11683#-KXk_0Hcnhfw2FSAw5kd:-KXk_5gAjRB_h_e_AHWF:byr8dgn) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa229e81a9fd2cab9fb411f6a8b2e80f37df5aa2/pkg/storage/replica.go#L576)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

not %p?
</blockquote></details>

I don't want the `0x` prefix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11683)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/storage/replica.go, line 576 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11683#-KXk_0Hcnhfw2FSAw5kd:-KXk_Smcasf0PWxQrtEr:b-3abtdl) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa229e81a9fd2cab9fb411f6a8b2e80f37df5aa2/pkg/storage/replica.go#L576)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I don't want the `0x` prefix.
</blockquote></details>

OK. https://golang.org/pkg/fmt/ doesn't seem to document the behaviour of `%x` wrt pointers.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11683)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[pkg/storage/replica.go, line 576 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/11683#-KXk_0Hcnhfw2FSAw5kd:-KXk_nNBq1DlA_0PYer8:b-wh95sv) ([raw file](https://github.com/cockroachdb/cockroach/blob/aa229e81a9fd2cab9fb411f6a8b2e80f37df5aa2/pkg/storage/replica.go#L576)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

OK. https://golang.org/pkg/fmt/ doesn't seem to document the behaviour of `%x` wrt pointers.
</blockquote></details>

Hmm. It definitely works (I tested it).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/11683)*

**Comment by mberhault** [comment]
LGTM.
We can move things to vlog at some point, but let's keep it simple.

**Pull request merged**
