### PR TITLE
sql: include non-voters in crdb_internal.ranges{_no_leases}

### PR DESCRIPTION
**Pull request by aayushshah15**
Before this commit, the `replicas` column of
`crdb_internal.ranges_no_leases` would only included voting replicas.
This commit makes it such that it includes voting as well as non-voting
replicas.

Additionally, this commit also adds two new columns: `voting_replicas`
and `non_voting_replicas`.

Release justification: observability improvements for new functionality.

Release note: the `replicas` column of
`crdb_internal.ranges{_no_leases}` now includes both voting and
non-voting replicas and `crdb_internal.ranges{_no_leases}` include two
new columns: `voting_replicas` and `non_voting_replicas` which work as
labelled.

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Do you think we should also extend the table so that users can distinguish between voting and non-voting replicas? Maybe with `voting_replicas` and `non_voting_replicas` columns?

**Comment by aayushshah15** [comment]
>Do you think we should also extend the table so that users can distinguish between voting and non-voting replicas? Maybe with voting_replicas and non_voting_replicas columns?

Done.

**Review by andreimatei — APPROVED** [review]
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

Consider adding a check for this function to some unit test that configures non-voters.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59839#-:-MVbD02607ISyuLjiJvG:b-w3hvij)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15 and @nvanbenschoten)

___
*[pkg/sql/crdb_internal.go, line 2669 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59839#-MVbCqBuBtfWAx5XqAvw:-MVbCqBuBtfWAx5XqAvx:b-w7llvq) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6ecf8eb871e699df8ea858b904a8747fcc57992/pkg/sql/crdb_internal.go#L2669)):*
> ```Go
>   table_name           STRING NOT NULL,
>   index_name           STRING NOT NULL,
>   replicas             INT[] NOT NULL,
> ```

comment that this is the same as `voting_replicas` + `non_voting_replicas`, and highlight that it doesn't include learners. Right?
Also say that the values are store ids.
___
*[pkg/sql/logictest/testdata/logic_test/create_statements, line 769 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59839#-MVbAnrG0GPucteFo3et:-MVbAnrG0GPucteFo3eu:b-ayfoov) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6ecf8eb871e699df8ea858b904a8747fcc57992/pkg/sql/logictest/testdata/logic_test/create_statements#L769)):*
> ```
> )  {}  {}
> CREATE TABLE crdb_internal.predefined_comments (
>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             type INT8 NULL,
> ```

what happened here? some spaces? was that on purpose?


<!-- Sent from Reviewable.io -->

**Review by aayushshah15 — COMMENTED** [review]
>Consider adding a check for this function to some unit test that configures non-voters.

Done.

TFTR! 

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59839#-:-MVcL8VY3lxAqtNqWiun:be81cyj)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/sql/crdb_internal.go, line 2669 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59839#-MVbCqBuBtfWAx5XqAvw:-MVc6Lt-8hYEtbo1THmo:b-7rl0jd) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6ecf8eb871e699df8ea858b904a8747fcc57992/pkg/sql/crdb_internal.go#L2669)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

comment that this is the same as `voting_replicas` + `non_voting_replicas`, and highlight that it doesn't include learners. Right?
Also say that the values are store ids.
</blockquote></details>

done.
___
*[pkg/sql/logictest/testdata/logic_test/create_statements, line 769 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/59839#-MVbAnrG0GPucteFo3et:-MVc5XkD0RzWW-573bW2:b-i9k303) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6ecf8eb871e699df8ea858b904a8747fcc57992/pkg/sql/logictest/testdata/logic_test/create_statements#L769)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

what happened here? some spaces? was that on purpose?
</blockquote></details>

I think `-rewrite` converted the indentation to spaces from tabs or something like that.  Reverted.

**Pull request merged**
