### PR TITLE
sql: add unordered unique row id as builtin and serial_normalization option

### PR DESCRIPTION
**Pull request by jameswsj10**
See [#54675](https://github.com/cockroachdb/cockroach/pull/54675). Previously, there were only ordered unique
row ids generated which incurs write hot-spots.
    
The introduction of unordered unique row ids enable distributed
row ids to avoid hotspots while maintaining the 64-bit integer
data type. Basic testing proving distribution of row insertions provided.
    
Release note (sql change): Added a new sql builtin 'unordered_unique_rowid' 
and serial_normalization case 'unordered_rowid' which generates a globally 
unique 64-bit integer that does not have ordering.

### CODE REVIEW

**Comment by jameswsj10** [comment]
Fixed CI fail due to go test broken in bazel; reduced number of row insertions in TestSerialNormalizationWithUniqueUnorderedID to 1000 to withstand stress tests.

**Review by ajwerner — COMMENTED** [review]
Sorry for the late review! This is close. 

> Reviewed 1 of 1 files at r1, 4 of 8 files at r2, 2 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70338#-:-MkCKk4r6Fv7mmhMAoti:buz730z)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @jameswsj10)

___
*[pkg/sql/sem/builtins/builtins.go, line 7652 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70338#-MkCKB45DcENBzCqNmPS:-MkCKB45DcENBzCqNmPT:b-xca05c) ([raw file](https://github.com/cockroachdb/cockroach/blob/fae6d9de7ee09ad8023a711258ffb4f6e9e63bf7/pkg/sql/sem/builtins/builtins.go#L7652)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 	// ts is [16 bits of 0][48 bits of ts]
> 	ts := (orig & ((uint64(math.MaxUint64) >> 16) << 15)) >> 15
> 	// v is [0][48 bits of reversed ts][15 bits of node id]
> 	v := (bits.Reverse64(ts) >> 1) | (orig & (1<<15 - 1))
> ```
</details>

this might feel silly but it will make me feel a lot better, can you pull just the middle two lines (and the comment on the top line) into a little helper and then, in a unit test, in a for loop, generate random uint64 values, do this little bit manipulation dance, and then confirm that `bits.OnesCount64` is the same for the input and output. It'll make me feel better that we aren't clobbering any bits. 
___
*[pkg/sql/sem/builtins/builtins_test.go, line 109 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/70338#-MkCKcIw3m9hxg5NNRnq:-MkCKcIw3m9hxg5NNRnr:bknvrq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/fae6d9de7ee09ad8023a711258ffb4f6e9e63bf7/pkg/sql/sem/builtins/builtins_test.go#L109)):*
> ```
> 	fmt.Println("Key counts in each split range")
> 	for i, keyCount := range keyCounts {
> 		fmt.Printf("range %d: %d\n", i, keyCount)
> ```
this isn't actually checking anything, it's just printing things. Can we update this test to make some assertion?

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70338)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @fqazi, and @jameswsj10)

___
*[pkg/sql/sem/builtins/builtins_test.go, line 73 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/70338#-MkFRC5_2eOIb3yPBOSk:-MkFRC5_2eOIb3yPBOSl:b-lpx8dv) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1432affa5426eeb2f2e31e428d6b451fcf426c6/pkg/sql/sem/builtins/builtins_test.go#L73)):*
> ```Go
> }
> 
> // TestMapToUniqueUnorderedID verifies that the mapping preserves the ones count
> ```

nit: period. 
___
*[pkg/sql/sem/builtins/builtins_test.go, line 84 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/70338#-MkFRCuH5PDAFWOd8PpG:-MkFRCuH5PDAFWOd8PpH:b2zh56m) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1432affa5426eeb2f2e31e428d6b451fcf426c6/pkg/sql/sem/builtins/builtins_test.go#L84)):*
> ```Go
> 		outputOnesCount := bits.OnesCount64(output)
> 		if inputOnesCount != outputOnesCount {
> 			t.Errorf("input: %b, output %b\nExpected: %d, got: %d", randInput, output, inputOnesCount, outputOnesCount)
> ```

nit: wrap
nit: `require.Equalf`
___
*[pkg/sql/sem/builtins/builtins_test.go, line 111 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/70338#-MkFRMK-5Rmv7hXOZD-G:-MkFRMK-5Rmv7hXOZD-H:b-32vbet) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1432affa5426eeb2f2e31e428d6b451fcf426c6/pkg/sql/sem/builtins/builtins_test.go#L111)):*
> ```Go
> 
> 	// testing configurations
> 	const numberOfRows = 1000
> ```

for the number of rows, if you wanted, you could do something like:
```go
numberOfRows := 10000
if util.RaceEnabled {
    numberOfRows = 100
}
```

Please comment briefly that you want to use a relatively small number of rows because inserting them under race is slow. 
___
*[pkg/sql/sem/builtins/builtins_test.go, line 115 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/70338#-MkFRfAVB1C80fJ9QpfJ:-MkFRfAW6tY_-RyTn6hg:b-2bqm5b) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1432affa5426eeb2f2e31e428d6b451fcf426c6/pkg/sql/sem/builtins/builtins_test.go#L115)):*
> ```
> 	// enforce range splits to collect range statistics after row insertions
> 	// 3 bits worth of splits in the high order
> ```
nit: comment should be sentences 
___
*[pkg/sql/sem/builtins/builtins_test.go, line 128 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/70338#-MkFOKXrDDc4VY0NLgVX:-MkFOKXrDDc4VY0NLgVY:b-ljrxbj) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1432affa5426eeb2f2e31e428d6b451fcf426c6/pkg/sql/sem/builtins/builtins_test.go#L128)):*
> ```Go
> 		"='t'::regclass;").Scan(&keyCounts)
> 
> 	// Calculate mean and variance using NumericStat
> ```

let's get a little bit mathier here. What we want to know is whether this distribution over the ranges is not uniform. A nice tool for that is [chi-squared](https://en.wikipedia.org/wiki/Pearson%27s_chi-squared_test).  Fortunately for this sort of thing it's really easy to compute. The null hypothesis distribution says that each range should have the same probability. We want to see if we can reject that at a pretty high p-value. Maybe .00001 or something like that\*. So, here's what I think this looks like. We need to pick our failing statistic value based on the p value we want. If we look at https://www.fourmilab.ch/rpkp/experiments/analysis/chiCalc.html, a very conservative choice seems like `19.5114` which gives us a p value of `.00001` that things really are uniform and we saw what we saw. 

From then, we just need to compute the stat. Consider:

```
func discreteUniformChiSquared(counts []int64) float64 {
	var n int64
	for _, c := range counts {
		n += c
	}
	p := float64(1) / float64(len(counts))
	var stat float64
	for _, c := range counts {
		oSubE := float64(c)/float64(n) - p
		stat += (oSubE * oSubE) / p
	}
	stat *= float64(n)
	return stat
}
```

For the failing example of `[]int64{127, 136, 107, 118, 108, 142, 127, 135}` we get the value `9.44` which is below our threshold. If we were to, say, move the counts from the last bucket to the first one, we'd get `[]int64{262, 136, 107, 118, 108, 142, 127, 0}` which gives us `283.76` as our stat, which seems good because that's not very uniform. 
___
*[pkg/sql/sem/builtins/builtins_test.go, line 137 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/70338#-MkFR3F57uzaHeqx_5zn:-MkFOPP53vuKY2pi_uY_:b9veium) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1432affa5426eeb2f2e31e428d6b451fcf426c6/pkg/sql/sem/builtins/builtins_test.go#L137)):*
> ```Go
> 	mean := stats.Mean
> 	variance := stats.GetVariance(count)
> 	fmt.Printf("Mean: %f Variance: %f\n", mean, variance)
> ```

if you want to log something from the test, use `t.Logf`

**Review by ajwerner — APPROVED** [review]
Name the builtin and `serial_normalization` value in the release note for the docs team.

Other than that, :lgtm_strong:.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70338#-:-MkIMDBs8p0AdDx7Mzdh:b-mg18mr)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @fqazi, and @jameswsj10)

**Review by ajwerner — COMMENTED** [review]
Oh, wait, actually, can you rework the git history to be a bit more sane here? Namely, remove the `[dnm]` and put the release note about the new builtin in the first commit and then remove the new builtin from the second release note? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70338#-:-MkIMMaE8pxaZQtEjzSy:b-k8k6h0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @fqazi, and @jameswsj10)

**Comment by jameswsj10** [comment]
> nit: period.

Resolved. 



> nit: wrap
> nit: `require.Equalf`

Resolved.

> Please comment briefly that you want to use a relatively small number of rows because inserting them under race is slow.

Done. 


> nit: comment should be sentences

Resolved. Double-checked comments to adhere to engineering guidelines. 

> let's get a little bit mathier here. What we want to know is whether this distribution over the ranges is not uniform. A nice tool for that is [chi-squared](https://en.wikipedia.org/wiki/Pearson%27s_chi-squared_test). Fortunately for this sort of thing it's really easy to compute. The null hypothesis distribution says that each range should have the same probability. We want to see if we can reject that at a pretty high p-value. Maybe .00001 or something like that*. So, here's what I think this looks like. We need to pick our failing statistic value based on the p value we want. If we look at https://www.fourmilab.ch/rpkp/experiments/analysis/chiCalc.html, a very conservative choice seems like `19.5114` which gives us a p value of `.00001` that things really are uniform and we saw what we saw.

I've replaced the existing method of checking variance not exceeding a hard-coded threshold to the chi-squared goodness of fit test against the uniform distribution null hypothesis. Let me know if the comments are descriptive enough!

> if you want to log something from the test, use `t.Logf`

Removed all fmt.Prints and logged only the range distributions. Let me know if you'd like me to remove this log as well. 

> Oh, wait, actually, can you rework the git history to be a bit more sane here? Namely, remove the `[dnm]` and put the release note about the new builtin in the first commit and then remove the new builtin from the second release note?

Modified commit descriptions and release notes for both commits. 


Thanks for the feedback! 👍

**Review by ajwerner — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 8 files at r2, 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70338#-:-MkIp68zAUTYhiCTGQon:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

**Review by fqazi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 9 of 9 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70338)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @fqazi and @jameswsj10)

___
*[-- commits, line 5 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70338#-MkIvAJ54J4GU-SPy3Ge):*
probably should say hot spot was a side effect of the distribution somehow
___
*[-- commits, line 7 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70338#-MkIvFgu9FIzT1VHuBZm):*
May be a bit clearer and say that a new builtin without ordering avoids that problem.

**Review by jameswsj10 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70338)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @fqazi)

___
*[-- commits, line 5 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70338#-MkIvAJ54J4GU-SPy3Ge):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

probably should say hot spot was a side effect of the distribution somehow
</blockquote></details>

Done.
___
*[-- commits, line 7 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/70338#-MkIvFgu9FIzT1VHuBZm):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

May be a bit clearer and say that a new builtin without ordering avoids that problem.
</blockquote></details>

Done.

**Review by fqazi — APPROVED** [review]
> Reviewed 9 of 9 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70338)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @fqazi)

**Pull request merged**
