### PR TITLE
kvcoord: simplify rangeCache.clearOlderOverlapping

### PR DESCRIPTION
**Pull request by andreimatei**
This method had too much code - it was traversing the tree twice for no
good reason.
Also added some more tests for it.

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51227)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 953 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51227#-MBuXpd9-xdAZSffz1i8:-MBuXpd9-xdAZSffz1i9:b-qdk8wi) ([raw file](https://github.com/cockroachdb/cockroach/blob/a38ebfb3b5ebb120a4dc6e7fa0633b5a3def7199/pkg/kv/kvclient/kvcoord/range_cache.go#L953)):*
> ```Go
> 	// ["b", "c"), we should not evict ["a", "b").
> 	var newerFound *kvbase.RangeCacheEntry
> 	rdc.rangeCache.cache.DoRangeEntry(func(e *cache.Entry) bool {
> ```

s/bool/(exit bool)/
___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 966 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51227#-MBuYemg0d-9bQqrdMTv:-MBuYemg0d-9bQqrdMTw:bbzogvk) ([raw file](https://github.com/cockroachdb/cockroach/blob/a38ebfb3b5ebb120a4dc6e7fa0633b5a3def7199/pkg/kv/kvclient/kvcoord/range_cache.go#L966)):*
> ```Go
> 			newest = false
> 			if descsCompatible(&cached.Desc, &newEntry.Desc) {
> 				newerFound = cached
> ```

Is this "newer" or just "not older" than the provided entry?
___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 975 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51227#-MBuYOhO9c0umXhVTL-h:-MBuYOhO9c0umXhVTL-i:bsgm218) ([raw file](https://github.com/cockroachdb/cockroach/blob/a38ebfb3b5ebb120a4dc6e7fa0633b5a3def7199/pkg/kv/kvclient/kvcoord/range_cache.go#L975)):*
> ```Go
> 		}
> 		return false // continue iterating
> 	}, rangeCacheKey(startMeta.Next()), rangeCacheKey(roachpb.RKeyMax))
> ```

Can we statically allocate `var maxCacheKey interface{} = rangeCacheKey(roachpb.RKeyMax)`?
___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 986 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51227#-MBuYlafBUHY9ZUgLQCi:-MBuYlafBUHY9ZUgLQCj:b-t68kwv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a38ebfb3b5ebb120a4dc6e7fa0633b5a3def7199/pkg/kv/kvclient/kvcoord/range_cache.go#L986)):*
> ```Go
> }
> 
> // all returns all the entries in the cache.
> ```

Should this go in `range_cache_test.go`?
___
*[pkg/kv/kvclient/kvcoord/range_cache_test.go, line 1066 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51227#-MBuXAqv6iR8vUkKdRq2:-MBuXAqv6iR8vUkKdRq3:b-fti4n3) ([raw file](https://github.com/cockroachdb/cockroach/blob/160bcc9cc27a55d857f8baae0f114785d3eaf213/pkg/kv/kvclient/kvcoord/range_cache_test.go#L1066)):*
> ```Go
> 		defer func() {
> 			if r := recover(); r != nil {
> 				t.Fatalf("invocation of clearOlderOverlappingLocked panicked: %v", r)
> ```

Did you want this diff?
___
*[pkg/kv/kvclient/kvcoord/range_iter.go, line 200 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51227#-MBowEk6-OQIQS6y3Q4Q:-MBowEk6-OQIQS6y3Q4R:b-yejlsl) ([raw file](https://github.com/cockroachdb/cockroach/blob/9357cc6388058402d6b65ffa9d3bdec6e928112b/pkg/kv/kvclient/kvcoord/range_iter.go#L200)):*
> ```Go
> 		ri.err = deducedErr
> 	} else {
> 		ri.err = errors.Wrapf(err, "RangeIterator failed to seek to %s", key)
> ```

Are we guaranteed that `err != nil` at this point?

EDIT: I tested. No, we are not. See https://github.com/cockroachdb/cockroach/pull/51310.
___
*[pkg/roachpb/data.go, line 93 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51227#-MBuXHMUE-fKHzeQSlH5:-MBuXHMUE-fKHzeQSlH6:boa6p5y) ([raw file](https://github.com/cockroachdb/cockroach/blob/a38ebfb3b5ebb120a4dc6e7fa0633b5a3def7199/pkg/roachpb/data.go#L93)):*
> ```Go
> }
> 
> func (rk RKey) Compare(other RKey) int {
> ```

Give this a comment.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51227)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 953 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51227#-MBuXpd9-xdAZSffz1i8:-MBuesiz6UXSKx9GvhFB:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a38ebfb3b5ebb120a4dc6e7fa0633b5a3def7199/pkg/kv/kvclient/kvcoord/range_cache.go#L953)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

s/bool/(exit bool)/
</blockquote></details>

done
___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 966 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51227#-MBuYemg0d-9bQqrdMTv:-MBuf1K55vKnbyp7sxna:b71qzwg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a38ebfb3b5ebb120a4dc6e7fa0633b5a3def7199/pkg/kv/kvclient/kvcoord/range_cache.go#L966)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this "newer" or just "not older" than the provided entry?
</blockquote></details>

well it's technically "newerOrIdentical". But I'd keep `newerFound`.
___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 975 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51227#-MBuYOhO9c0umXhVTL-h:-MBufxQECJWN7Vq9r8LT:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a38ebfb3b5ebb120a4dc6e7fa0633b5a3def7199/pkg/kv/kvclient/kvcoord/range_cache.go#L975)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can we statically allocate `var maxCacheKey interface{} = rangeCacheKey(roachpb.RKeyMax)`?
</blockquote></details>

done
___
*[pkg/kv/kvclient/kvcoord/range_cache.go, line 986 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51227#-MBuYlafBUHY9ZUgLQCi:-MBufzNx9JixTC70AXjJ:bh0ccju) ([raw file](https://github.com/cockroachdb/cockroach/blob/a38ebfb3b5ebb120a4dc6e7fa0633b5a3def7199/pkg/kv/kvclient/kvcoord/range_cache.go#L986)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should this go in `range_cache_test.go`?
</blockquote></details>

I would keep it here cause it's a reasonable method. It might come in handy for debugging, or even for production.
___
*[pkg/kv/kvclient/kvcoord/range_cache_test.go, line 1066 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51227#-MBuXAqv6iR8vUkKdRq2:-MBuei5C4_Sj-LgXhnut:b-hfpv0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/160bcc9cc27a55d857f8baae0f114785d3eaf213/pkg/kv/kvclient/kvcoord/range_cache_test.go#L1066)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Did you want this diff?
</blockquote></details>

removed
___
*[pkg/kv/kvclient/kvcoord/range_iter.go, line 200 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51227#-MBowEk6-OQIQS6y3Q4Q:-MBueN749a3BLoRwc4BA:b-q4qdwu) ([raw file](https://github.com/cockroachdb/cockroach/blob/9357cc6388058402d6b65ffa9d3bdec6e928112b/pkg/kv/kvclient/kvcoord/range_iter.go#L200)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Are we guaranteed that `err != nil` at this point?

EDIT: I tested. No, we are not. See https://github.com/cockroachdb/cockroach/pull/51310.
</blockquote></details>

nice, so I'll wait for #51310 to merge
___
*[pkg/roachpb/data.go, line 93 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/51227#-MBuXHMUE-fKHzeQSlH5:-MBugG8s2C2DHB940upx:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a38ebfb3b5ebb120a4dc6e7fa0633b5a3def7199/pkg/roachpb/data.go#L93)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Give this a comment.
</blockquote></details>

done

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51227)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/kv/kvclient/kvcoord/range_iter.go, line 200 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51227#-MBowEk6-OQIQS6y3Q4Q:-MC84IkN6zlmgrNjrYUt:bvkiig8) ([raw file](https://github.com/cockroachdb/cockroach/blob/9357cc6388058402d6b65ffa9d3bdec6e928112b/pkg/kv/kvclient/kvcoord/range_iter.go#L200)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nice, so I'll wait for #51310 to merge
</blockquote></details>

#51310 got merged

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51227#-:-MC9MSx6-t6Lxc0dLXBk:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51227#-:-MC9OZaT7-Lmhi8gVZ8J:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
