### PR TITLE
roachtest: update pg_regress diffs

### LINKED ISSUE #127556: roachtest: pg_regress failed
roachtest.pg_regress [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyBazel/16162366?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyBazel/16162366?buildTab=artifacts#/pg_regress) on master @ [7a8ce2447eb023e855cb85b3ce65a07a70a39334](https://github.com/cockroachdb/cockroach/commits/7a8ce2447eb023e855cb85b3ce65a07a70a39334):

```
  --
  prepare ps1 as
    select * from mc3p where a = $1 and abs(b) < (select 3);
@@ -261187,7 +261087,7 @@
  explain (costs off)
  select *
  from (
-@@ -3747,19 +3272,11 @@
+@@ -3747,19 +3271,11 @@
        select 1, 1, 1
       ) s(a, b, c)
  where s.a = 1 and s.b = 1 and s.c = (select 1);
@@ -261212,7 +261112,7 @@
  select *
  from (
        select * from p
-@@ -3769,11 +3286,7 @@
+@@ -3769,11 +3285,7 @@
        select 1, 1, 1
       ) s(a, b, c)
  where s.a = 1 and s.b = 1 and s.c = (select 1);
@@ -261225,7 +261125,7 @@
  prepare q (int, int) as
  select *
  from (
-@@ -3784,116 +3297,186 @@
+@@ -3784,116 +3296,186 @@
        select 1, 1, 1
       ) s(a, b, c)
  where s.a = $1 and s.b = $2 and s.c = (select 1);
@@ -261480,7 +261380,7 @@
  -- Like the above but throw some more complexity at the planner by adding
  -- a UNION ALL.  We expect both sides of the union not to scan the
  -- non-required partitions.
-@@ -3901,136 +3484,236 @@
+@@ -3901,136 +3483,236 @@
  'select * from listp where a = (select 1)
    union all
  select * from listp where a = (select 2);');
@@ -261793,7 +261693,7 @@
  --
  -- Check that gen_partprune_steps() detects self-contradiction from clauses
  -- regardless of the order of the clauses (Here we use a custom operator to
-@@ -4043,28 +3726,84 @@
+@@ -4043,28 +3725,84 @@
     commutator = ===,
     hashes
  );
If the diff is expected, copy regression.diffs from the test artifacts to pkg/cmd/roachtest/testdata/regression.diffs
test artifacts and logs in: /artifacts/pg_regress/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-16162366/pg-regress/1721455131439/1721455885495)

</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*pg_regress.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/bazci/githubpost/issues)
</sub>

Jira issue: CRDB-40474

### PR DESCRIPTION
**Pull request by rytaft**
Fixes #127556

Release note: None

### CODE REVIEW

**Comment by rytaft** [comment]
To review this PR, you can look at the test logs here that show the difference between the previous and new version of regression.diffs: https://teamcity.cockroachdb.com/repository/download/Cockroach_Nightlies_RoachtestWeeklyBazel/16507545:id/pg_regress/run_1/artifacts.zip!/test.log

I think a lot of the changes are due to new parser support for triggers.

**Comment by rytaft** [comment]
In addition to new parser support for triggers, other changes include lots of things like:
```
-+See: https://go.crdb.dev/issue-v/43299/v24.2
++See: https://go.crdb.dev/issue-v/43299/dev
```
new parser support for <->:
```
-+ERROR:  at or near "-": syntax error
-+DETAIL:  source SQL:
-+SELECT 'a' <-> 'b & d'::tsquery
-+            ^
++ERROR:  unsupported binary operator: <string> <-> <tsquery>
```
OID changes, line number changes, better support for concat.... etc etc

I skimmed through the test output and didn't notice anything concerning. I strongly recommend not attempting to review this diff in detail. I think we should probably just apply these diffs and try to be more on top of fixing pg_regress failures promptly going forward.

**Review by mw5h — APPROVED** [review]
I looked through the diffs and did not see anything glaringly wrong. There are 2500+ lines of diff even after the very mechanical stuff is removed, so it's always possible that I missed something.

:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129414#-:-O4q8YNN72Mgit0NbN_c:b-rb5cy9)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @nameisbhaskar and @vidit-bhat)

**Review by rytaft — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129414#-:-O4qLO7xEDOssNmlbnDu:b-oduykh)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @nameisbhaskar and @vidit-bhat)

**Pull request merged**
