### PR TITLE
storage: Add settings for allocator environment variables

### PR DESCRIPTION
**Pull request by a-robinson**
@dt is there a pattern for doing validation of settings values yet? In this case, it'd be nice to check whether a float is non-negative.

### CODE REVIEW

**Comment by a-robinson** [comment]
And should I just be getting getting rid of the old environment variables?

**Comment by petermattis** [comment]
:lgtm:

> And should I just be getting getting rid of the old environment variables?

If they are not being used, yes.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/allocator.go, line 50 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15394#-Kih7cCEsx8L89MWzdzu:-Kih7cCEsx8L89MWzdzv:bm0ljiw) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a431d5f41054c601bc4cf37d90d9efac8e5647/pkg/storage/allocator.go#L50)):*
> ```Go
> 	// the mean range/lease count that permits rebalances/lease-transfers away from
> 	// that store.
> 	baseRebalanceThreshold = 0.05
> ```

Should this be a setting? I've never fiddled with it. Just asking.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15394#-:-Kih7VDOL4ka72K382S5:b-h77aen)*

**Comment by dt** [comment]
So far validation has been in the form of adding additional settings types that wrap the simpler ones, and then the type match in `set.go` switches on them.

That said, non-negative seems very common, so I would also be fine with a flag on the int/float setting.

I believe @knz's most recent tech notes on settings usage says that we should *avoid* mixing env and settings, including a default value read from env, as it is confusing what wins and when.

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15394#-:-Kih6sPl-IyQ0cUEiCQ6:b-5sfved)*

**Comment by a-robinson** [comment]
I don't *think* there's anyone out there using them, but we may want to include their removal in the release notes. Consider them removed, though.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/allocator.go, line 50 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15394#-Kih7cCEsx8L89MWzdzu:-Kih8VorSmsfTCfIA-K5:b-4rohp2) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a431d5f41054c601bc4cf37d90d9efac8e5647/pkg/storage/allocator.go#L50)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Should this be a setting? I've never fiddled with it. Just asking.
</blockquote></details>

I don't think so, which is why I made it a const rather than a setting.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15394#-:-Kih8g33udLhl1Ipg-SD:b-eqc405)*

**Comment by dt** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/storage/allocator.go, line 72 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15394#-Kihcho8-E84l6zdMUhG:-Kihcho8-E84l6zdMUhH:bp2w3od) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a431d5f41054c601bc4cf37d90d9efac8e5647/pkg/storage/allocator.go#L72)):*
> ```Go
> 		"kv.allocator.load_based_lease_rebalancing.enabled",
> 		"set to enable rebalancing of range leases based on load and latency",
> 		envutil.EnvOrDefaultBool("COCKROACH_ENABLE_LOAD_BASED_LEASE_REBALANCING", true))
> ```

Here's the guiding rules @knz wrote up on env vs settings: https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/settings_table.md#settings-vs-env-vars

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15394)*

**Comment by petermattis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/storage/allocator.go, line 50 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15394#-Kih7cCEsx8L89MWzdzu:-KijPkfwco4fodSc64vT:ba0v0f1) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a431d5f41054c601bc4cf37d90d9efac8e5647/pkg/storage/allocator.go#L50)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

I don't think so, which is why I made it a const rather than a setting.
</blockquote></details>

Ok. This value was pulled out of thin air. I don't think I ever tested it significantly. If we made this a setting it would also give a knob for disabling rebalancing in a cluster.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15394)*

**Comment by a-robinson** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/storage/allocator.go, line 50 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15394#-Kih7cCEsx8L89MWzdzu:-KijfJGc-lJmPax6mzcq:bofg3o) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a431d5f41054c601bc4cf37d90d9efac8e5647/pkg/storage/allocator.go#L50)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Ok. This value was pulled out of thin air. I don't think I ever tested it significantly. If we made this a setting it would also give a knob for disabling rebalancing in a cluster.
</blockquote></details>

Fairly indirectly, though. If we want a knob to disable rebalancing in a cluster, that should be something that we add more directly. The current value for this has worked well in our experience, and I don't foresee anyone (not even us) feeling a need to tweak it.

---

*[pkg/storage/allocator.go, line 72 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15394#-Kihcho8-E84l6zdMUhG:-Kijf76M0UTeL95Vt54F:be17u8d) ([raw file](https://github.com/cockroachdb/cockroach/blob/66a431d5f41054c601bc4cf37d90d9efac8e5647/pkg/storage/allocator.go#L72)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Here's the guiding rules @knz wrote up on env vs settings: https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/settings_table.md#settings-vs-env-vars
</blockquote></details>

Ack, thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15394)*

**Comment by a-robinson** [comment]
I've also removed the `EnvOrDefaultFloat` method since it's now unused and `make check` doesn't like that.

**Comment by knz** [comment]
Reviewed 2 of 3 files at r1, 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15394)*

**Pull request merged**
