### PR TITLE
fs,kvserver: fix categorized disk stats metric

### LINKED ISSUE #129159: storage: per-category metrics not displaying in the db console
In 24.2, we have per-category disk write metrics.

However, on `master`, these metrics no longer display.

24.2 (from a production cluster running `v24.2.0-beta.1`):

Screenshot 2024-08-16 at 3 18 55 PM

From a DRT cluster, running 2f0b0399a5c9656bdf8a417d0ab57e4eb1ae0f64, we don't see any metrics:

Screenshot 2024-08-16 at 3 33 52 PM

On `master` (446bc365f4c24230ed36c3e3202d47e5adbd6f69), only the log file writes seem to display:

Screenshot 2024-08-16 at 3 32 50 PM

Jira issue: CRDB-41404

### PR DESCRIPTION
**Pull request by aadityasondhi**
This patch fixes a bug where the `vfs.DiskWriteStatsCollector` was incorrectly being passed into the disk health check FS in pebble.

Fixes #129159.

Release note: None

### CODE REVIEW

**Comment by aadityasondhi** [comment]
image

**Review by jbowens — APPROVED** [review]
:lgtm_strong: 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129412#-:-O4q8YTo9Vvq7pja2033:b-uwkowd)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi)

**Review by aadityasondhi — COMMENTED** [review]
TFTR!

bors r=jbowens

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129412#-:-O4qN72dBoPtcNs54nRR:bn097h5)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi)

**Comment by aadityasondhi** [comment]
bors r=jbowens

**Pull request merged**
