### PR TITLE
storage: filter abort span during split copy

### PR DESCRIPTION
**Pull request by tbg**
We are suspecting that some workloads create a sufficient number of
abort span records to cause split commands that are too large to be
proposed to Raft, in effect rendering the range permanently
unsplittable. This is a problem since the range will at some point
start to backpressure writes (and even without that, it's a resource
hog). Most of the problematic abort span records would very likely
be removed during garbage collection; however, abort span records
aren't counted in any quantity that triggers GC.

Instead of copying the entirety of the abort span, restrict to the
entries that would not be removed by a GC operation. In practice,
this means that unless a high number of abort span records are
created every hour, very few records will actually be copied, and
in return the split command size should be small.

See #26830.

Release note (bug fix): Avoid a situation in which ranges repeatedly
fail to perform a split.

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
:lgtm: the approach looks good, just a few comments about re-organizing the code.

---

Reviewed 1 of 3 files at r1.
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/storage/client_split_test.go, line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26934#-LFjBd6q6eQl1FLd-zNA:-LFjBd6q6eQl1FLd-zNB:bdq20od) ([raw file](https://github.com/cockroachdb/cockroach/blob/a17c7b82c1952a32365052548ff3d82d0dd70bf1/pkg/storage/client_split_test.go#L102)):*
> ```Go
> }
> 
> func TestStoreSplitAbortSpan(t *testing.T) {
> ```

Leave a comment about what this is testing.

---

*[pkg/storage/replica_command.go, line 1148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26934#-LFjBBWM50Y7zx-CKPMB:-LFjBBWM50Y7zx-CKPMC:bb6dx4d) ([raw file](https://github.com/cockroachdb/cockroach/blob/a17c7b82c1952a32365052548ff3d82d0dd70bf1/pkg/storage/replica_command.go#L1148)):*
> ```Go
> 	}
> 
> 	// Initialize the RHS range's AbortSpan by copying the LHS's. Put a little extra
> ```

Do you think this should all be moved into a `AbortSpan.CopyIntoWithFilter` method (with a better name, if you can think of one)?

---

*[pkg/storage/replica_command.go, line 1163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26934#-LFjAg6kCpa80pDFXIe1:-LFjAg6kCpa80pDFXIe2:bo7om7f) ([raw file](https://github.com/cockroachdb/cockroach/blob/a17c7b82c1952a32365052548ff3d82d0dd70bf1/pkg/storage/replica_command.go#L1163)):*
> ```Go
> 		var scratch [64]byte
> 		rec.AbortSpan().Iterate(ctx, batch, func(k []byte, entry roachpb.AbortSpanEntry) {
> 			if err != nil {
> ```

We should add an `error` return value to `Iterate`'s closure, terminate iteration if it's not nil, and return an error from the funtion.

---

*[pkg/storage/abortspan/abortspan.go, line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26934#-LFjAU3k3aW3lKrwsVrj:-LFjAU3k3aW3lKrwsVrk:b-23zccz) ([raw file](https://github.com/cockroachdb/cockroach/blob/a17c7b82c1952a32365052548ff3d82d0dd70bf1/pkg/storage/abortspan/abortspan.go#L110)):*
> ```Go
> // each unmarshaled entry with the MVCC key and the decoded entry.
> func (sc *AbortSpan) Iterate(
> 	ctx context.Context, e engine.Reader, f func([]byte, roachpb.AbortSpanEntry),
> ```

Not your change, but why does `f` pass a `[]byte` instead of a `roachpb.Key`? Does changing that break anything?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26934#-:-LFjBhkg0OFnyULkkqW_:bs7mb1t)*

**Comment by tschottdorf** [comment]
TFTR!

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/storage/client_split_test.go, line 102 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26934#-LFjBd6q6eQl1FLd-zNA:-LFmaGTO9nbJLktPWBxf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a17c7b82c1952a32365052548ff3d82d0dd70bf1/pkg/storage/client_split_test.go#L102)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Leave a comment about what this is testing.
</blockquote></details>

Done.

---

*[pkg/storage/replica_command.go, line 1148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26934#-LFjBBWM50Y7zx-CKPMB:-LFmbljC3ZGCXwBRrzXo:b-d2li0z) ([raw file](https://github.com/cockroachdb/cockroach/blob/a17c7b82c1952a32365052548ff3d82d0dd70bf1/pkg/storage/replica_command.go#L1148)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do you think this should all be moved into a `AbortSpan.CopyIntoWithFilter` method (with a better name, if you can think of one)?
</blockquote></details>

I removed the Copy methods. We're only going to copy in two places, splits and merges. Left a TODO for @benesch in the merge code (removing a copy that apparently had no test coverage) and removed the impl of `CopyInto` and `CopyFrom` which ... wasn't great code anyway.

---

*[pkg/storage/replica_command.go, line 1163 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26934#-LFjAg6kCpa80pDFXIe1:-LFmdSYO5_kKAu4RAbpz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a17c7b82c1952a32365052548ff3d82d0dd70bf1/pkg/storage/replica_command.go#L1163)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We should add an `error` return value to `Iterate`'s closure, terminate iteration if it's not nil, and return an error from the funtion.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26934#-:-LFmdUds55SYa5VYJQvN:b-814g8k)*

**Comment by tschottdorf** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/storage/abortspan/abortspan.go, line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26934#-LFjAU3k3aW3lKrwsVrj:-LFmdpx67JJWHziBfAuC:bycz7kq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a17c7b82c1952a32365052548ff3d82d0dd70bf1/pkg/storage/abortspan/abortspan.go#L110)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Not your change, but why does `f` pass a `[]byte` instead of a `roachpb.Key`? Does changing that break anything?
</blockquote></details>

No that works beautifully, done. Maybe there was an import problem at some distant point in the past? Not sure.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26934)*

**Comment by tschottdorf** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/storage/abortspan/abortspan.go, line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26934#-LFjAU3k3aW3lKrwsVrj:-LFme1oL1s3V4zmZq3x-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a17c7b82c1952a32365052548ff3d82d0dd70bf1/pkg/storage/abortspan/abortspan.go#L110)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

No that works beautifully, done. Maybe there was an import problem at some distant point in the past? Not sure.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26934)*

**Comment by tschottdorf** [comment]
bors r=nvanbenschoten

**Pull request merged**
