### PR TITLE
opt: clean up internal planner after exec

### LINKED ISSUE #21482: sql: executor_opt_interface doesn't cleanup after the planner
`executor_opt_interface:NewExecFactory()` creates an "internal planner" but never calls `finishInternalPlanner()` with it. No biggie, but it should be called after the user of said planner is done with it. It's unclear to me what that point is, though.

Shortly I'll send a PR where I'm changing the `makeInternalPlanner()` function to return the cleanup function explicitly - among others to prevent this mistake. I'm going to continue ignoring the cleanup; I hope you can take over then :)

### PR DESCRIPTION
**Pull request by RaduBerinde**
Fixes #21482.

Release note: None

### CODE REVIEW

**Comment by andreimatei** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/opt/exec.go, line 49 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21487#-L3-lW4mXSjgHmFKujuX:-L3-lW4mXSjgHmFKujuY:b-d4uc7l) ([raw file](https://github.com/cockroachdb/cockroach/blob/34d6becf5dac75ba745c4d69307975690339f091/pkg/sql/opt/exec.go#L49)):*
> ```Go
> 	ConstructFilter(n ExecNode, filter tree.TypedExpr) (ExecNode, error)
> 
> 	// Close cleans up any state associated with the factory.
> ```

we should say that `Close()` needs to be called *after* the client is done with `ExecNodes` created above, right?. But then doesn't it become a weird interface?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21487)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/opt/exec.go, line 49 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21487#-L3-lW4mXSjgHmFKujuX:-L305rTvY1N_dfgSb0pv:b-orjk81) ([raw file](https://github.com/cockroachdb/cockroach/blob/34d6becf5dac75ba745c4d69307975690339f091/pkg/sql/opt/exec.go#L49)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

we should say that `Close()` needs to be called *after* the client is done with `ExecNodes` created above, right?. But then doesn't it become a weird interface?
</blockquote></details>

Done. Yes, it's a bit weird but it's a prototype at this point. At a high level the problem is that we don't have a good separation between planning and execution (we shouldn't need the planner to run a plan).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21487)*

**Comment by andreimatei** [comment]
I'll take this over and make it part of #21486. Thanks.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21487#-:-L34eaaQXvjXeI1Dkzv4:b-g8vj63)*

**Comment by RaduBerinde** [comment]
Great, thanks

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21487#-:-L34tCDZ1ztiq4R0iO_I:b-4so2ez)*

**Pull request closed without merging**
