### PR TITLE
gossip: periodically log gossip status

### PR DESCRIPTION
**Pull request by petermattis**
Log gossip status once per minute. The status currently contains whether
we're connected to the gossip network, the number of nodes gossip nows
about and the client and server connections.

See #7668.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7716)

### CODE REVIEW

**Comment by petermattis** [comment]
I'm not sure if this is useful or sufficient logging. I was unsuccessfully attempting to reproduce #7668 and the gossip problems in #7693.

**Comment by BramGruneir** [comment]
I like the concept, by why not make this as part of node stats?  Would be really cool to see this info in the dashboard.
Or at least use the same metrics system that we already use for node and store stats.  It has threadsafe counters already built in.

**Comment by petermattis** [comment]
If gossip is having trouble (such as in #7668 and #7693), we're not going to be able to access the normal metrics system.

**Comment by BramGruneir** [comment]
Of course not.  But it doesn't hurt to save the state when its doing well (and starting to see failures).  Also, this doesn't preclude also logging (instead of only saving to the db).
Plus the metrics should still work locally.  If you can hit the node directly you should be able to see the currents stats without having to parse the logs.  Assuming the status endpoint is still working.

**Comment by petermattis** [comment]
You're correct that it doesn't hurt to do both. We should definitely add metrics to gossip. That seems separate from this PR, though. I thought we actually had an issue about this, but can't find one. Just filed #7719.

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[gossip/server.go, line 50 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7716#-KMHfrZvlGRT-2Wf7QAA:-KMHfrZw2Rs-fASo_6_h:-178175521) ([raw file](https://github.com/cockroachdb/cockroach/blob/11564dc824bbb4c51aee54244c1db502212669a6/gossip/server.go#L50)):*
> ```Go
> 	is       *infoStore                         // The backing infostore
> 	incoming nodeSet                            // Incoming client node IDs
> 	nodeMap  map[util.UnresolvedAddr]serverInfo // Incoming client's local address -> serverConn
> ```

s/serverConn/serverInfo/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7716#-:-KMHgF3dRYmG28xcEP-j:1417088721)*

**Comment by petermattis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[gossip/server.go, line 50 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7716#-KMHfrZvlGRT-2Wf7QAA:-KMJy6AihJ-TmRmWE_ND:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/11564dc824bbb4c51aee54244c1db502212669a6/gossip/server.go#L50)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> s/serverConn/serverInfo/
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7716)*

**Pull request merged**
