### PR TITLE
cloud/kubernetes: Fix use of deprecated start command in k8s README

### PR DESCRIPTION
**Pull request by a-robinson**
And add the useful --logtostderr while I'm here.

### CODE REVIEW

**Review by DuskEagle — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45365)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @a-robinson and @joshimhoff)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/45365#-M0wuj3O35s_2-eJS9fO:-M0wuj3O35s_2-eJS9fP:b-85i648) (no related file):*
LGTM!

---

**Review by DuskEagle — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45365)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @joshimhoff)

**Comment by a-robinson** [comment]
Thanks!

bors r+

**Comment by nvanbenschoten** [comment]
👋 @a-robinson. Thanks for the fix! I noticed that this didn't merge.

bors r+

**Comment by DuskEagle** [comment]
Merging manually since bors is disabled.

**Pull request merged**
