### PR TITLE
kvserver: add kv.replica_batch_sequence.latency metric

### PR DESCRIPTION
**Pull request by tbg**
We already have a metric for evaluating the batch. This PR adds one for
latching.

The benefit of this metric is that it closes over evaluation and overlapping
commands' replication, but not over contention, so it is a useful proxy for
non-contention related slowness. In other words, if end to end p99s are
"large", but this metric's are "small", then it's likely that KV performs well
but there is contention. If this metric's p99 is elevated, there are likely
write hotspots in the system (i.e. operations are waiting for prior writing
operations to be replicated) or the leaseholder is slow (= evaluation takes a
long time and blocks a writer's latch). We can likely cobble together the same
information from other sources, but I'd like to give this metric a try regard-
less.

Touches https://github.com/cockroachdb/cockroach/issues/93982.
Touches https://github.com/cockroachdb/cockroach/issues/82200.
Touches https://github.com/cockroachdb/cockroach/issues/83262.

Epic: none
Release note: None

### CODE REVIEW

**Review by arulajmani — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105045)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten and @tbg)

___
*[`pkg/kv/kvserver/replica_send.go` line 468 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105045#-NYd5OVE-t2EVTZlqkJD:-NYd5OVE-t2EVTZlqkJE:b-bw4sdh) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb42ebb22dc9a08a0df26e2e62d076d17c3be9c7/pkg/kv/kvserver/replica_send.go#L468)):*
> ```Go
> 		var resp []kvpb.ResponseUnion
> 		tBegin := timeutil.Now()
> 		g, resp, pErr = r.concMgr.SequenceReq(ctx, g, concurrency.Request{
> ```

In addition to waiting on and acquiring latches, this method will also sequence through the lock table. The measurement here would include any time spent waiting on contended intents (i.e intents that have been pulled into the lock table by a different request) + unreplicated locks. The commit message says we want to use this metric for non-contention related slowness, so I'm wondering if this is intentional? 

Alternatively, could we instead measure latch acquisition latency more directly in the latch manager?

**Review by nvb — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/105045)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/kv/kvserver/replica_send.go` line 468 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/105045#-NYd5OVE-t2EVTZlqkJD:-NYs1aJDCxCXn7GQSZXJ:b-lj28ip) ([raw file](https://github.com/cockroachdb/cockroach/blob/eb42ebb22dc9a08a0df26e2e62d076d17c3be9c7/pkg/kv/kvserver/replica_send.go#L468)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

In addition to waiting on and acquiring latches, this method will also sequence through the lock table. The measurement here would include any time spent waiting on contended intents (i.e intents that have been pulled into the lock table by a different request) + unreplicated locks. The commit message says we want to use this metric for non-contention related slowness, so I'm wondering if this is intentional? 

Alternatively, could we instead measure latch acquisition latency more directly in the latch manager? 
</blockquote></details>

This is a good point. It does feel like we want to push this histogram into `spanlatch.Manager.wait`.

**Comment by tbg** [comment]
Thanks for the reviews! I tend to forget that intent resolution is under this call. Closing over it is in fact not what I wanted. I'll see if I will have some time to adjust this PR, will ping in case that happens.

**Comment by tbg** [comment]
Closing, filed https://github.com/cockroachdb/cockroach/issues/106500 against KV in case you want to pick this up at some point. I'm not 100% sure it's a useful metric, so probably some discussion to be had.

**Pull request closed without merging**
