### PR TITLE
*: introduce an abstraction for a set of ReplicaDescriptors

### LINKED ISSUE #37499: roachpb: abstraction over []ReplicaDescriptor
Currently, the replicas field of the `RangeDescriptor` proto is a slice of `ReplicaDescriptor` protos. This slice ends up being copied around in a number of places, particularly the allocator. We're about to introduce learner replicas, which will add a field to ReplicaDescriptor to indicate what kind of replica it is. In the learners PR, the various users of `[]ReplicaDescriptor` will all need to decide whether to include or exclude learners from whatever they were doing with the replicas.

Most places will likely include them, but things like computing quorum counts will want to exclude. There are O(100)s of these callsites, so auditing them without help from the compiler will be hard. As a result, this seems like a good time to introduce a bit of abstraction.

(Note: This is still a bit of a WIP)

Option 1:
```
type ReplicaDescriptors []ReplicaDescriptor
```
- pros: Least invasive change
- cons: Doesn't get us much. A range loop over a field that has changed from `[]ReplicaDescriptor` to `ReplicaDescriptors` will still compile, so we'd miss it in the audit.

Option 2:
```
type ReplicaDescriptors struct {
    replicas []ReplicaDescriptor
}
```
- pros: Every usage of a field/arg/value that changes from `[]ReplicaDescriptor` to `ReplicaDescriptors` will break, causing us to consider each of them.
- cons: I've prototyped this and the normal code changes are pretty clean, we can likely develop a minimal set of methods that cover what we need. However, the tests are going to be a nightmare, they do all sorts of manual setup on and changes directly to the `RangeDescriptor.Replicas` field.

I don't think this is worth doing unless we go with Option 2.

Happily, most (all?) of these `[]ReplicaDescriptor` slices come from the `Replicas` field on `RangeDescriptor` and there is a small-ish set of functions that take them as args, so switching `[]ReplicaDescriptor` references to `ReplicaDescriptors` should be tractable, modulo the following.

Ideally, we'd be able to use something like the `gogoproto.customtype` option to make this field on the generated `RangeDescriptor` struct directly into a `ReplicaDescriptors`. Unfortunately, customtype looks to only work with the elements in a generated repeated field and doesn't let you replace the generated field wholesale. Here are the remaining options as I see them.

Option 2A:
Rename the proto field in `RangeDescriptor` from Replicas to InternalReplicas. Add a `Replicas()` method to `RangeDescriptor` that returns the `ReplicaDescriptors` wrapper.
- pros: Works pretty well for reading the field.
- cons: Any construction of a`RangeDescriptor` breaks the abstraction. This happens all the time in tests. Perhaps this could be broken into a two step process where the second step takes the `RangeDescriptor` and adds the `ReplicaDescriptors`.
- todo: Is there a limited set of mutations we need to support? The allocator currently does all sorts of stuff directly to the slices.

Option 2B:
Rename `RangeDescriptor` to `InternalRangeDescriptor` and embed it in a new `RangeDescriptor` struct. This new struct would also have a `Replicas ReplicaDescriptors` field and implement the proto marshal/unmarshal methods necessary to use it as a `gogoproto.customtype` in other protos that use a `RangeDescriptor`. This is very similar to (and inspired by) what andyk did with `pkg/sql/types.T` and `pkg/sql/types.InternalType`.
- pros: Maintains the `ReplicaDescriptors` abstraction.
- cons: Seems like overkill. `RangeDescriptor`s are manually constructed in tests all over the place and these will all have to be updated to reflect the embedded InternalRangeDescriptor struct, which then leaks the RangeDescriptor abstraction. `pkg/sql/types` has the benefit of a much more limited set of ways they need to be constructed. Maybe there's a way to work through this?

Option 2C:
Add a `customslice` option to gogoproto that does what I say we want above.
- pros: Seems like the ideal option.
- cons: Currently unknown difficultly and complexity. Blocks on an external project (or forces us to fork).

I'm leaning toward 2A.

Open questions:
- What's the perf impact?
- Is there a small-ish set of `ReplicaDescriptors` constructors we could provide that would cover most/all of the current test usage?

### PR DESCRIPTION
**Pull request by danhhz**
Closes #37499

Release note: None

### CODE REVIEW

**Comment by danhhz** [comment]
Okay @tbg there's some broken tests, WIPs, and polish left, but you can see the general direction I'm thinking of here if you want to take a peek. Turned out simpler than I was thinking it would

**Review by tbg — COMMENTED** [review]
Looks good!

> Reviewed 58 of 58 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37537#-:-Lf0JlMq77QEAhSe-yzt:b-vs1prh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz)

___
*[pkg/roachpb/metadata_replicas.go, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37537#-Lf0J5NbCDrRyFk6XbRZ:-Lf0J5Nc1cfp1bCWV8qu:b-f08fx7) ([raw file](https://github.com/cockroachdb/cockroach/blob/bda4592546abbcc55d1bddd3db3f9de4df1e1e74/pkg/roachpb/metadata_replicas.go#L1)):*
> ```Go
> // Copyright 2014 The Cockroach Authors.
> ```

19 (btw I have a thing in my editor that auto-generates this with the right year, I'll never go back)
___
*[pkg/roachpb/metadata_replicas.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37537#-Lf0JJfgEF1MF7l8vUC_:-Lf0JJfgEF1MF7l8vUCa:b-mr9ob9) ([raw file](https://github.com/cockroachdb/cockroach/blob/bda4592546abbcc55d1bddd3db3f9de4df1e1e74/pkg/roachpb/metadata_replicas.go#L33)):*
> ```Go
> // point, all uses of Wrapped will be migrated to All/Voters/Learners.
> //
> // WIP should I name this TODO to match the context one?
> ```

What would that be? What context one?
___
*[pkg/roachpb/metadata_replicas.go, line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37537#-Lf0JZ8W3iwnIesh16M7:-Lf0JZ8W3iwnIesh16M8:b-5zctv) ([raw file](https://github.com/cockroachdb/cockroach/blob/bda4592546abbcc55d1bddd3db3f9de4df1e1e74/pkg/roachpb/metadata_replicas.go#L78)):*
> ```Go
> // group consisting of this set of replicas.
> func (d ReplicaDescriptors) QuorumSize() int {
> 	return (len(d.wrapped) / 2) + 1
> ```

You might as well write `return (len(d.Voters() / 2) + 1` already.

**Review by danhhz — COMMENTED** [review]
Okay, besides measuring any perf impact, this is ready to go. I ended up removing some of the code simplifications to focus this PR on being as mechanical as possible. A fast follow will alter usages to be more idiomatic of the new abstraction

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37537#-:-LfLTt0H9V5TBuPvMmGl:b-pj7lov)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/roachpb/metadata_replicas.go, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37537#-Lf0J5NbCDrRyFk6XbRZ:-LfL95Lr4k2SI8gE6bWF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bda4592546abbcc55d1bddd3db3f9de4df1e1e74/pkg/roachpb/metadata_replicas.go#L1)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

19 (btw I have a thing in my editor that auto-generates this with the right year, I'll never go back)
</blockquote></details>

Done.
___
*[pkg/roachpb/metadata_replicas.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37537#-Lf0JJfgEF1MF7l8vUC_:-LfL96mMBnV0qId2v208:bobedig) ([raw file](https://github.com/cockroachdb/cockroach/blob/bda4592546abbcc55d1bddd3db3f9de4df1e1e74/pkg/roachpb/metadata_replicas.go#L33)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

What would that be? What context one?
</blockquote></details>

I was talking about context.TODO(). I tried it but it just doesn't read well. The best I've come up with in a bit of thinking is Unwrap, which sounds vaguely scary enough to hopefully make what's going on clear. The plan is that this method goes away soon-ish anyway, so hopefully that's good enough.
___
*[pkg/roachpb/metadata_replicas.go, line 78 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37537#-Lf0JZ8W3iwnIesh16M7:-LfL9Qdh1PrnP5FfORy3:b-qbdnb3) ([raw file](https://github.com/cockroachdb/cockroach/blob/bda4592546abbcc55d1bddd3db3f9de4df1e1e74/pkg/roachpb/metadata_replicas.go#L78)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

You might as well write `return (len(d.Voters() / 2) + 1` already.
</blockquote></details>

Done. :itshappening:

**Review by tbg — APPROVED** [review]
:lgtm:

> Reviewed 36 of 36 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37537#-:-LfPacVxEgY7GZkfsda1:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz)

___
*[pkg/roachpb/metadata.go, line 142 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37537#-LfPaHUGEsxVmpWt760I:-LfPaHUHDJx5Fn94bXle:b-8n19ke) ([raw file](https://github.com/cockroachdb/cockroach/blob/71d2d0751b8bf4bf4957b73c4b4c4711e3e10c66/pkg/roachpb/metadata.go#L142)):*
> ```Go
> 
> // AddReplica adds the given replica to this range's set.
> func (r *RangeDescriptor) AddReplica(toAdd ReplicaDescriptor) {
> ```

There's never any kind of feedback loop about the replica already being present?

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37537)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/roachpb/metadata.go, line 142 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37537#-LfPaHUGEsxVmpWt760I:-LfQiZXF4cqeJWN8zpTI:bo0g7tz) ([raw file](https://github.com/cockroachdb/cockroach/blob/71d2d0751b8bf4bf4957b73c4b4c4711e3e10c66/pkg/roachpb/metadata.go#L142)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

There's never any kind of feedback loop about the replica already being present?
</blockquote></details>

There never was before, apparently. This was always done in contexts where it knew. Do you think it's worth adding one for symmetry with RemoveReplica?

**Review by tbg — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37537)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @danhhz and @tbg)

___
*[pkg/roachpb/metadata.go, line 142 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37537#-LfPaHUGEsxVmpWt760I:-LfR0FfL5L8Fz561OVdb:b-mcd1lm) ([raw file](https://github.com/cockroachdb/cockroach/blob/71d2d0751b8bf4bf4957b73c4b4c4711e3e10c66/pkg/roachpb/metadata.go#L142)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

There never was before, apparently. This was always done in contexts where it knew. Do you think it's worth adding one for symmetry with RemoveReplica?
</blockquote></details>

No, I think that's fine.

**Comment by danhhz** [comment]
TFTRs! I sanity checked the KV/Insert family of benchmarks and there was no diff.

bors r=tbg

**Comment by danhhz** [comment]
Thought I fixed all the UI references but my grepping was bad

bors=tbg

**Comment by danhhz** [comment]
bors r=tbg

**Pull request merged**
