### PR TITLE
[DO NOT MERGE] cli,ts: add tsdump command

### PR DESCRIPTION
**Pull request by petermattis**
Added a `debug tsdump` command which allows dumping all of the raw
timeseries data from a cluster. This is being used for some
experimentation into whether we can dump all of the timeseries data from
a baseline run of a test and then compare that against a new run to look
for anomalies or unexpected behavior.

There are currently 421 metrics captured for a single server containing
a single store. Samples are taken every 10s which translates into 2.3
MiB of data per server per hour or 55.5 MiB per server per day. The
resulting text output is slightly larger, but compresses in excess of
10:1. So if we want to keep around the baseline metrics for a 10-node
cluster for a day we're looking at something close to 555 MiB of raw
data, or ~50 MiB compressed.

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
@mrtracy The `TimeSeries.Dump` stuff is experimental, but it does point to how we could grab the timeseries for a cluster and later import it into another cluster for viewing.

**Comment by mrtracy** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/cli/debug.go, line 1027 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21833#-L42on35WxR3rMdsJOHm:-L42oX81YANmD-ZsJL_o:bc5tr0w) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd62bdbbebc89c47fc3505b411193dba50caf746/pkg/cli/debug.go#L1027)):*
> ```Go
> 			return nil
> 		}
> 		if name != data.Name || source != data.Source {
> ```

The stream output here is going to match the data layout from the engine, which is ordered by:

[series name][timestamp][source]

On a multi-node cluster, I would thus expect this would output the "name, source" line on every single iteration of this loop.  I'm not sure if this is what you expected, or if you were expecting all of the data for each time series to be in a single contiguous space.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21833)*

**Comment by petermattis** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/cli/debug.go, line 1027 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21833#-L42on35WxR3rMdsJOHm:-L42wXKTiXl9bhV0oc6O:b-a8ne3h) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd62bdbbebc89c47fc3505b411193dba50caf746/pkg/cli/debug.go#L1027)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

The stream output here is going to match the data layout from the engine, which is ordered by:

[series name][timestamp][source]

On a multi-node cluster, I would thus expect this would output the "name, source" line on every single iteration of this loop.  I'm not sure if this is what you expected, or if you were expecting all of the data for each time series to be in a single contiguous space.
</blockquote></details>

No, I wasn't expecting all of the data for a given series/source to be contiguous. I think the consumer (this code) can take care of it. I'm trying to dump the all of the raw time series data as quickly as possible for later analysis. Bonus points if I can dump the data since a particular timestamp so that a test can "tail" the time series data. That seems a bit more challenging on the server side. Perhaps you have some thoughts on how that can be done efficiently. Note that with the current implementation, the server side is trivial and efficient in terms of scan calls and memory usage. I'm not sure how to achieve that with a dump-since-timestamp operation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21833)*

**Comment by mrtracy** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/cli/debug.go, line 1027 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21833#-L42on35WxR3rMdsJOHm:-L42yA7RfhlcCmQSs2DZ:b-mhnjzu) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd62bdbbebc89c47fc3505b411193dba50caf746/pkg/cli/debug.go#L1027)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

No, I wasn't expecting all of the data for a given series/source to be contiguous. I think the consumer (this code) can take care of it. I'm trying to dump the all of the raw time series data as quickly as possible for later analysis. Bonus points if I can dump the data since a particular timestamp so that a test can "tail" the time series data. That seems a bit more challenging on the server side. Perhaps you have some thoughts on how that can be done efficiently. Note that with the current implementation, the server side is trivial and efficient in terms of scan calls and memory usage. I'm not sure how to achieve that with a dump-since-timestamp operation.
</blockquote></details>

This is the same problem we had with pruning time series; the data in question is not contiguous. The simplest solution is to maintain a list of time series which need to be queried, but it still requires multiple queries.

That said, if you don't particularly case about the ordering of the output, and are leaving it to the consumer to assemble the data correctly, then you could dump the results of the per-series queries onto the stream. That means your memory consumption won't increase much.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21833)*

**Comment by petermattis** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/cli/debug.go, line 1027 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21833#-L42on35WxR3rMdsJOHm:-L434nAS-qnXWrqIJr6Y:bqjlye) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd62bdbbebc89c47fc3505b411193dba50caf746/pkg/cli/debug.go#L1027)):*
Maintaining the list of time series is onerous. 

> That said, if you don't particularly case about the ordering of the output, and are leaving it to the consumer to assemble the data correctly, then you could dump the results of the per-series queries onto the stream. That means your memory consumption won't increase much.

Not sure how your suggestion here differs from what is being done in this PR. Can you elaborate?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21833)*

**Comment by mrtracy** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/cli/debug.go, line 1027 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21833#-L42on35WxR3rMdsJOHm:-L436c-i4bwLygdfw4jG:b-6v0838) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd62bdbbebc89c47fc3505b411193dba50caf746/pkg/cli/debug.go#L1027)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Maintaining the list of time series is onerous. 

> That said, if you don't particularly case about the ordering of the output, and are leaving it to the consumer to assemble the data correctly, then you could dump the results of the per-series queries onto the stream. That means your memory consumption won't increase much.

Not sure how your suggestion here differs from what is being done in this PR. Can you elaborate?
</blockquote></details>

I'm only saying that if you have the list of time series names, it shouldn't increase your max memory usage that much to issue multiple queries, since you won't have to assemble the data.

If maintaining a list of time series is not an option (and i'm assuming that includes maintaining any sort of index in the CRDB key space), I think your only option is to scan the entire key space but only read values from keys that decode later than the requested timestamp.

Other than that, we're either going to need to change the layout of the keyspace, or create a data structure *somewhere* to help identify the data that needs to be queried.  Options would include:

* The aforementioned list of time series names
* A secondary index which arranges TS data by time
* Implement time series data pushing.  We support prometheus scraping, but there's no reason we couldn't configure the nodes to push time series data somewhere. In this design, your tail becomes a push target.
* As a twist on the above, push TS data from each node onto some kind of queue.
* Maintain some time series data for each node in-memory, maybe an RRD style memory-limited dataset, and then fan-out to all of the nodes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21833)*

**Comment by petermattis** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/cli/debug.go, line 1027 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21833#-L42on35WxR3rMdsJOHm:-L43Xb8uhJnAu7DTE8rN:bhsr6ji) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd62bdbbebc89c47fc3505b411193dba50caf746/pkg/cli/debug.go#L1027)):*
<details><summary><i>Previously, mrtracy (Matt Tracy) wrote…</i></summary><blockquote>

I'm only saying that if you have the list of time series names, it shouldn't increase your max memory usage that much to issue multiple queries, since you won't have to assemble the data.

If maintaining a list of time series is not an option (and i'm assuming that includes maintaining any sort of index in the CRDB key space), I think your only option is to scan the entire key space but only read values from keys that decode later than the requested timestamp.

Other than that, we're either going to need to change the layout of the keyspace, or create a data structure *somewhere* to help identify the data that needs to be queried.  Options would include:

* The aforementioned list of time series names
* A secondary index which arranges TS data by time
* Implement time series data pushing.  We support prometheus scraping, but there's no reason we couldn't configure the nodes to push time series data somewhere. In this design, your tail becomes a push target.
* As a twist on the above, push TS data from each node onto some kind of queue.
* Maintain some time series data for each node in-memory, maybe an RRD style memory-limited dataset, and then fan-out to all of the nodes
</blockquote></details>

Got it. To respond: we don't have the time series names and adding some sort of index seems like overkill. I'm not too worried about the performance of what this PR is currently doing. Pushing time series data elsewhere wouldn't necessarily help my use case. What I want to do is to get the time series data after a multi-{hour,day} test and then compare it against a baseline. The math suggests that the volume of this data will be reasonable. I'm a bit anxious about over-designing something for this use case because it is still unknown if it will actually work. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21833)*

**Comment by petermattis** [comment]
@mrtracy This is the PR I mentioned last week. I'm not at all tied to the approach done in this PR, though I do have the requirement that we can retrieve all of the raw timeseries data efficiently. I tried using the existing timeseries APIs and retrieving all of the timeseries data was quite slow. Maybe I was just doing something wrong.

**Pull request closed without merging**
