### PR TITLE
intentresolver: Add byte pagination to RequestBatcher and IntentResolver

### PR DESCRIPTION
**Pull request by KaiSun314**
Informs: #77228
    
Intent resolution batches are sequenced on raft and each batch can
consist of 100-200 intents. If an intent key or even value in some cases
are large, it is possible that resolving all intents in the batch would
result in a raft command size exceeding the max raft command size
kv.raft.command.max_size.

In PR #94814, we added support for TargetBytes for resolve intent and
resolve intent range raft commands.

In this PR, we set the TargetBytes field in the resolve intent and
resolve intent range requests in the RequestBatcher and IntentResolver
to 4MB. This allows us to stop resolving intents in the batch before we
get close to the max raft command size to lower the chance we exceed
this limit.

Release note: None

### CODE REVIEW

**Comment by KaiSun314** [comment]
The third commit "[intentresolver: Add byte pagination to RequestBatcher and IntentResolver](https://github.com/cockroachdb/cockroach/pull/92268/commits/f182533657438ac5e61bbea2320542733342c356)" is rebased on top of the second commit "storage: Add support for TargetBytes for resolve intent + range cmd". Please only review the third commit. Thank you so much in advance!

**Review by nvb — COMMENTED** [review]
> Reviewed 3 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92268)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @KaiSun314)

___
*[`-- commits` line 52 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/92268#-NI3gS8a0jC04vSVmIL9):*
I don't think we want this limit to be so large. This is a background operation and we don't want to risk head-of-line blocking by sticking a 62MB entry in the Raft log. I also don't think we want it directly tied to `kv.raft.command.max_size`, because changing that setting should not change workload dynamics.

I'd suggest setting it at something much lower, like 4MB.

If we make that change, we can then simplify the rest of this commit.

**Review by nvb — COMMENTED** [review]
Thanks @KaiSun314!

> Reviewed 1 of 8 files at r1, 1 of 36 files at r7, 4 of 6 files at r8, 29 of 29 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92268#-:-NNmbDEg1ECB7hrJywD0:brgi3si)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @KaiSun314)

___
*[`pkg/internal/client/requestbatcher/batcher.go` line 322 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/92268#-NNmXnFV3v64siDvs1Hi:-NNmXnFV3v64siDvs1Hj:bxycy2n) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d01c39a912b0fe4082382493f538d6daebd486/pkg/internal/client/requestbatcher/batcher.go#L322)):*
> ```Go
> 					// For response types that do not implement the combinable interface,
> 					// the resume span will be lost after roachpb.CombineResponses and
> 					// resp = prevResp below, so extract the resume span now.
> ```

Should we make `ResolveIntentRequest` and `ResolveIntentRangeRequest` implement the combinable interface? Do they not already due to the embedded `ResponseHeader`?
___
*[`pkg/kv/kvserver/intentresolver/intent_resolver.go` line 234 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/92268#-NNmZOARB3ll40L9d1fY:-NNmZOARB3ll40L9d1fZ:bwzeom9) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d01c39a912b0fe4082382493f538d6daebd486/pkg/kv/kvserver/intentresolver/intent_resolver.go#L234)):*
> ```Go
> 		intentResolutionRangeBatchSize = c.TestingKnobs.MaxIntentResolutionBatchSize
> 	}
> 	targetBytesPerBatchReq := int64(intentResolverRequestTargetBytes)
> ```

Why is this declaration and cast needed?
___
*[`pkg/kv/kvserver/intentresolver/intent_resolver_integration_test.go` line 73 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/92268#-NNmaV5ECJzPfDlj6N8Z:-NNmaV5ECJzPfDlj6N8_:bds3i29) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d01c39a912b0fe4082382493f538d6daebd486/pkg/kv/kvserver/intentresolver/intent_resolver_integration_test.go#L73)):*
> ```Go
> // the max raft command size resulting in an error and not all intents will be
> // resolved, unless byte size pagination is implemented.
> func TestAsyncIntentResolutionByteSizePagination(t *testing.T) {
> ```

Nice test!
___
*[`pkg/kv/kvserver/intentresolver/intent_resolver_integration_test.go` line 104 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/92268#-NNmaZFV2otjN1E1eP_c:-NNmaZFV2otjN1E1eP_d:b-kryts8) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d01c39a912b0fe4082382493f538d6daebd486/pkg/kv/kvserver/intentresolver/intent_resolver_integration_test.go#L104)):*
> ```Go
> 
> 	// Create 2 tables t1 and t2 and wait for t1 to be replicated on store 1 and
> 	// t2 to be replicated on store 2.
> ```

Does this need to be a multi-store test? Would a manual split point have been enough to reproduce the issue?
___
*[`pkg/kv/kvserver/intentresolver/intent_resolver_integration_test.go` line 181 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/92268#-NNmb3oE5bie9wmJ-PPz:-NNmb3oE5bie9wmJ-PQ-:b2dz82v) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d01c39a912b0fe4082382493f538d6daebd486/pkg/kv/kvserver/intentresolver/intent_resolver_integration_test.go#L181)):*
> ```Go
> 
> 	// Check that all intents have been resolved to ensure async intent
> 	//resolution did not exceed the max raft command size, which can only happen
> ```

nit: space after the `//`

**Review by KaiSun314 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92268)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/internal/client/requestbatcher/batcher.go` line 322 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/92268#-NNmXnFV3v64siDvs1Hi:-NOruXiv48EddCSBHJGg:b-l9uyeu) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d01c39a912b0fe4082382493f538d6daebd486/pkg/internal/client/requestbatcher/batcher.go#L322)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we make `ResolveIntentRequest` and `ResolveIntentRangeRequest` implement the combinable interface? Do they not already due to the embedded `ResponseHeader`?
</blockquote></details>

Currently, when `CombineResponses` is called with `ResolveIntentResponse` arguments, both the left and right responses cannot be casted into a `Combinable` type because `ResolveIntentResponse` does not implement the combinable interface and `CombineResponses` immediately returns and the resume span is lost.

Done. I changed the approach into `ResolveIntentResponse` implementing the combinable interface (`ResolveIntentRangeResponse` already implements the combinable interface).
___
*[`pkg/kv/kvserver/intentresolver/intent_resolver.go` line 234 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/92268#-NNmZOARB3ll40L9d1fY:-NOrvlAPER11b_5c3tpk:b-l5bp9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d01c39a912b0fe4082382493f538d6daebd486/pkg/kv/kvserver/intentresolver/intent_resolver.go#L234)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Why is this declaration and cast needed?
</blockquote></details>

`targetBytesPerBatchReq` is an `int64` type due to

```
if cfg.TargetBytesPerBatchReq > 0 {
	req.TargetBytes = cfg.TargetBytesPerBatchReq
}
```

But `intentResolverRequestTargetBytes` is initialized to 4<<20 (4MB) and is thus an `int` by default.

Thus, casting from `int` to `int64` needs to occur somewhere (alternatively we can do `intentResolverRequestTargetBytes = int64(4<<20)`), but I think casting here might look better?

We declare `targetBytesPerBatchReq` because it is used in both the ir batcher and range batcher configs.
___
*[`pkg/kv/kvserver/intentresolver/intent_resolver_integration_test.go` line 73 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/92268#-NNmaV5ECJzPfDlj6N8Z:-NOrwx2S5gxLLI8kWteK:bzcotf5) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d01c39a912b0fe4082382493f538d6daebd486/pkg/kv/kvserver/intentresolver/intent_resolver_integration_test.go#L73)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Nice test!
</blockquote></details>

Thank you Nathan!
___
*[`pkg/kv/kvserver/intentresolver/intent_resolver_integration_test.go` line 104 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/92268#-NNmaZFV2otjN1E1eP_c:-NOrx0aKBosgCSWUrsyu:b-p13zkc) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d01c39a912b0fe4082382493f538d6daebd486/pkg/kv/kvserver/intentresolver/intent_resolver_integration_test.go#L104)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Does this need to be a multi-store test? Would a manual split point have been enough to reproduce the issue?
</blockquote></details>

Ah great point, used a manual split point + only one table / store, the test is much cleaner now

**Review by nvb — APPROVED** [review]
:lgtm: once the remaining two items are resolved.

> Reviewed 7 of 32 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92268#-:-NOv4n1P-5Ote4Ry_Nh2:bu7h46l)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @KaiSun314)

___
*[`pkg/kv/kvserver/intentresolver/intent_resolver.go` line 234 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/92268#-NNmZOARB3ll40L9d1fY:-NOv3jqL3tflTZwYorz9:bia8ajs) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d01c39a912b0fe4082382493f538d6daebd486/pkg/kv/kvserver/intentresolver/intent_resolver.go#L234)):*
<details><summary><i>Previously, KaiSun314 (Kai Sun) wrote…</i></summary><blockquote>

`targetBytesPerBatchReq` is an `int64` type due to

```
if cfg.TargetBytesPerBatchReq > 0 {
	req.TargetBytes = cfg.TargetBytesPerBatchReq
}
```

But `intentResolverRequestTargetBytes` is initialized to 4<<20 (4MB) and is thus an `int` by default.

Thus, casting from `int` to `int64` needs to occur somewhere (alternatively we can do `intentResolverRequestTargetBytes = int64(4<<20)`), but I think casting here might look better?

We declare `targetBytesPerBatchReq` because it is used in both the ir batcher and range batcher configs.
</blockquote></details>

`intentResolverRequestTargetBytes` is an untyped numeric constant, right? So isn't the following possible as long as you don't introduce the intermediate (typed) `targetBytesPerBatchReq`:
```
diff --git a/pkg/kv/kvserver/intentresolver/intent_resolver.go b/pkg/kv/kvserver/intentresolver/intent_resolver.go
index f9592287c4a..0f4507e84f9 100644
--- a/pkg/kv/kvserver/intentresolver/intent_resolver.go
+++ b/pkg/kv/kvserver/intentresolver/intent_resolver.go
@@ -78,7 +78,7 @@ const (
        // write batch resulting from an intent resolution request. When exceeded,
        // the response will include a ResumeSpan and the batcher will send a new
        // intent resolution request.
-       intentResolverRequestTargetBytes = 4 << 20 // 4MB.
+       intentResolverRequestTargetBytes = 4 << 20 // 4 MB

        // MaxTxnsPerIntentCleanupBatch is the number of transactions whose
        // corresponding intents will be resolved at a time. Intents are batched
@@ -232,12 +232,11 @@ func New(c Config) *IntentResolver {
                intentResolutionBatchSize = c.TestingKnobs.MaxIntentResolutionBatchSize
                intentResolutionRangeBatchSize = c.TestingKnobs.MaxIntentResolutionBatchSize
        }
-       targetBytesPerBatchReq := int64(intentResolverRequestTargetBytes)
        ir.irBatcher = requestbatcher.New(requestbatcher.Config{
                AmbientCtx:             c.AmbientCtx,
                Name:                   "intent_resolver_ir_batcher",
                MaxMsgsPerBatch:        intentResolutionBatchSize,
-               TargetBytesPerBatchReq: targetBytesPerBatchReq,
+               TargetBytesPerBatchReq: intentResolverRequestTargetBytes,
                MaxWait:                c.MaxIntentResolutionBatchWait,
                MaxIdle:                c.MaxIntentResolutionBatchIdle,
                Stopper:                c.Stopper,
@@ -248,7 +247,7 @@ func New(c Config) *IntentResolver {
                Name:                   "intent_resolver_ir_range_batcher",
                MaxMsgsPerBatch:        intentResolutionRangeBatchSize,
                MaxKeysPerBatchReq:     intentResolverRangeRequestSize,
-               TargetBytesPerBatchReq: targetBytesPerBatchReq,
+               TargetBytesPerBatchReq: intentResolverRequestTargetBytes,
                MaxWait:                c.MaxIntentResolutionBatchWait,
                MaxIdle:                c.MaxIntentResolutionBatchIdle,
                Stopper:                c.Stopper,
```
___
*[`pkg/kv/kvserver/intentresolver/intent_resolver_integration_test.go` line 140 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/92268#-NOv4OqB0fDjd76y1V2R:-NOv4OqB0fDjd76y1V2S:b95hxi3) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5e7e1108c3b81ec9c21b6bfdf259de5c5647558/pkg/kv/kvserver/intentresolver/intent_resolver_integration_test.go#L140)):*
> ```Go
> 	// happen if byte size pagination was implemented.
> 	testutils.SucceedsSoon(t, func() error {
> 		result, err := storage.MVCCScanToBytes(ctx, store.TODOEngine(), startKey, endKey,
> ```

nit: you can replace `MVCCScanToBytes` with the more standard `MVCCScan`, since you aren't using the KV data anyway.

**Review by KaiSun314 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92268)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/intentresolver/intent_resolver.go` line 234 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/92268#-NNmZOARB3ll40L9d1fY:-NOwYStr49Gl5fOgGv2d:b-lye4pr) ([raw file](https://github.com/cockroachdb/cockroach/blob/37d01c39a912b0fe4082382493f538d6daebd486/pkg/kv/kvserver/intentresolver/intent_resolver.go#L234)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`intentResolverRequestTargetBytes` is an untyped numeric constant, right? So isn't the following possible as long as you don't introduce the intermediate (typed) `targetBytesPerBatchReq`:
```
diff --git a/pkg/kv/kvserver/intentresolver/intent_resolver.go b/pkg/kv/kvserver/intentresolver/intent_resolver.go
index f9592287c4a..0f4507e84f9 100644
--- a/pkg/kv/kvserver/intentresolver/intent_resolver.go
+++ b/pkg/kv/kvserver/intentresolver/intent_resolver.go
@@ -78,7 +78,7 @@ const (
        // write batch resulting from an intent resolution request. When exceeded,
        // the response will include a ResumeSpan and the batcher will send a new
        // intent resolution request.
-       intentResolverRequestTargetBytes = 4 << 20 // 4MB.
+       intentResolverRequestTargetBytes = 4 << 20 // 4 MB

        // MaxTxnsPerIntentCleanupBatch is the number of transactions whose
        // corresponding intents will be resolved at a time. Intents are batched
@@ -232,12 +232,11 @@ func New(c Config) *IntentResolver {
                intentResolutionBatchSize = c.TestingKnobs.MaxIntentResolutionBatchSize
                intentResolutionRangeBatchSize = c.TestingKnobs.MaxIntentResolutionBatchSize
        }
-       targetBytesPerBatchReq := int64(intentResolverRequestTargetBytes)
        ir.irBatcher = requestbatcher.New(requestbatcher.Config{
                AmbientCtx:             c.AmbientCtx,
                Name:                   "intent_resolver_ir_batcher",
                MaxMsgsPerBatch:        intentResolutionBatchSize,
-               TargetBytesPerBatchReq: targetBytesPerBatchReq,
+               TargetBytesPerBatchReq: intentResolverRequestTargetBytes,
                MaxWait:                c.MaxIntentResolutionBatchWait,
                MaxIdle:                c.MaxIntentResolutionBatchIdle,
                Stopper:                c.Stopper,
@@ -248,7 +247,7 @@ func New(c Config) *IntentResolver {
                Name:                   "intent_resolver_ir_range_batcher",
                MaxMsgsPerBatch:        intentResolutionRangeBatchSize,
                MaxKeysPerBatchReq:     intentResolverRangeRequestSize,
-               TargetBytesPerBatchReq: targetBytesPerBatchReq,
+               TargetBytesPerBatchReq: intentResolverRequestTargetBytes,
                MaxWait:                c.MaxIntentResolutionBatchWait,
                MaxIdle:                c.MaxIntentResolutionBatchIdle,
                Stopper:                c.Stopper,
```
</blockquote></details>

Done.

Ah sorry about that, didn't know Golang had untyped types. I thought `intentResolverRequestTargetBytes` was type `int`, but it's of type `untyped int`.

**Review by nvb — APPROVED** [review]
:lgtm: will merge on green. Thanks @KaiSun314!

> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/92268#-:-NOwbn-e-71D58T-waEK:b-p9rp2w)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by nvanbenschoten** [comment]
bors r=nvanbenschoten

**Comment by KaiSun314** [comment]
Thank you so much for the review Nathan!

**Pull request merged**
