### PR TITLE
docs: Add ui ARCHITECTURE.md doc

### PR DESCRIPTION
**Pull request by dhartunian**
Add an ARCHITECTURE doc to /pkg/ui to help developers onboard to the
project.

The doc contains pointers on general React and Redux knowledge and links
on where best to acquire it as well as a dataflow diagram and some FAQs
on how data flows through the application, which is likely the part
that's hardest to currently understand.

Release note: None

### CODE REVIEW

**Comment by dhartunian** [comment]
@jordanlewis is this the kind of documentation that you're looking for w/r/t DB Console?

**Review by nanduu04 — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60823)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @dhartunian, and @jordanlewis)

___
*[pkg/ui/ARCHITECTURE.md, line 5 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60823#-MU9FjvqEb3ZqpQRewtf:-MU9FjvqEb3ZqpQRewtg:b2nikay) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa6b300876c8c2f15139f9e43709b1cc7676955f/pkg/ui/ARCHITECTURE.md#L5)):*
> ```Markdown
> ## Language, Tools, and Frameworks
> 
> This repostory uses the Typescipt language and the React, and Redux libraries to
> ```

nit: repository and Typescript

**Review by nathanstilwell — APPROVED** [review]
These docs look dope. LGTM

**Comment by asubiotto** [comment]
This is great, thanks!

**Review by nkodali — APPROVED** [review]
So helpful! Thanks David!

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60823#-:-MUFQJHJ0tmT5cfcGNVk:bh69jrc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @dhartunian, and @jordanlewis)

**Review by nathanstilwell — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60823)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @dhartunian, and @jordanlewis)

**Pull request merged**
