### PR TITLE
parser: add more unimplemented errors for PG 10/11/12

### LINKED ISSUE #51424: sql: review postgres features and add unimplemented errors
Postgres has added a number of features since version 9 that are users are interested in CockroachDB supporting, for example Trigrams (https://github.com/cockroachdb/cockroach/issues/51137). Unfortunately, we don't have unimplemented errors for these features so we return syntax errors to users which can be confusing. Further, we don't collect telemetry to inform us of where we should next spend our time. Let's spend some time auditing the difference and adding important unimplemented errors.

### PR DESCRIPTION
**Pull request by otan**
Resolves #51424 

parser: add unimplemented for CREATE TABLESPACE

Release note: None

parser: add unimplemented for INHERITS / NO INHERITS

Release note: None

### CODE REVIEW

**Review by arulajmani — APPROVED** [review]
:shipit: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55061#-:-MIUssJ13l1Vw1eoDFic:bizlbj6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

**Comment by otan** [comment]
don't think the failure was me
bors r=arulajmani

**Comment by otan** [comment]
bors r=arulajmani

**Pull request merged**
