### PR TITLE
dev: filter out possibily unbuildable targets when `dev build`ing

### LINKED ISSUE #74213: dev: recognize multi-package builds
**Is your feature request related to a problem? Please describe.**

I very often run `make XXX  PKG=./pkg/a/b/c/...`
notice the `/...` at the end - this is recognized automatically by `go` (`build` / `test`) to recurse.
I can use this with `build`, `testbuild`, `test`, etc.

Unfortunately, neither `bazel` nor `dev` recognize this.

Would it be possible to extend `dev` to recognize `/...` patterns or something equivalent?

**Describe the solution you'd like**

```
dev testbuild //pkg/a/b/c....
dev test //pkg/a/b/c/...
```

etc

Epic CRDB-8036

### PR DESCRIPTION
**Pull request by rickystewart**
Closes #74213.

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
nice, but I don't understand this code enough to review your pr

**Review by irfansharif — APPROVED** [review]

**Comment by rickystewart** [comment]
TFTR!

bors r=irfansharif

**Comment by knz** [comment]
@rickystewart for my education, what is the `dev` syntax to do a recursive build?

**Comment by irfansharif** [comment]
`dev build pkg/spanconfig/...` should build all test/non-test targets recursively.

**Comment by knz** [comment]
how can I build _only_ the test binaries (without running them)?

**Comment by rickystewart** [comment]
> how can I build _only_ the test binaries (without running them)?

`bazel query 'kind(go_test, pkg/whatever/...)' | xargs dev build` would do it. If this isn't sufficient and you'd prefer that `dev` have an analogue to `make testbuild`, you can file a feature request.

**Comment by knz** [comment]
Thanks ricky, this is good for now, but I use this command sufficiently often that it's going to be worth an alias in `dev`. I'll file that issue. 

(Generally, I think most of the short commands we've built in the Makefile were built to simplify existing workflows. I think extending `dev` to support at least those targets would have been good strategy from the start.)

**Comment by irfansharif** [comment]
Thanks for filing. 

>  I think most of the short commands we've built in the Makefile were built to simplify existing workflows. I think extending dev to support at least those targets would have been good strategy from the start.

It was, probably I missed it because `make testbuild` does not show up in `make help` and I've never used it. I agree it's useful to have.

**Comment by knz** [comment]
fwiw it's `buildtest` not `testbuild` :)

**Pull request merged**
