### PR TITLE
roachtest/cdc: fix cdc/kafka-topics

### LINKED ISSUE #119509: roachtest: cdc/kafka-topics failed
roachtest.cdc/kafka-topics [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/14107820?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/14107820?buildTab=artifacts#/cdc/kafka-topics) on master @ [04f0416d526a43741d22fd03966758dcccdeb79f](https://github.com/cockroachdb/cockroach/commits/04f0416d526a43741d22fd03966758dcccdeb79f):

```
(cdc.go:1661).func17: expected fetching metadata for warehouse but did not
(cluster.go:2298).Run: context canceled
(cdc.go:380).Close: error shutting down prometheus/grafana: context canceled
test artifacts and logs in: /artifacts/cdc/kafka-topics/run_1
```

Parameters:
 - <code>ROACHTEST_arch=amd64</code>
 - <code>ROACHTEST_cloud=gce</code>
 - <code>ROACHTEST_coverageBuild=false</code>
 - <code>ROACHTEST_cpu=4</code>
 - <code>ROACHTEST_encrypted=false</code>
 - <code>ROACHTEST_fs=ext4</code>
 - <code>ROACHTEST_localSSD=true</code>
 - <code>ROACHTEST_metamorphicBuild=false</code>
 - <code>ROACHTEST_ssd=0</code>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

See: [Grafana](https://go.crdb.dev/roachtest-grafana/teamcity-14107820/cdc-kafka-topics/1708600678199/1708601013067)

</p>
</details>
/cc @cockroachdb/cdc
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*cdc/kafka-topics.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by wenyihu6**
cdc/kafka-topics tests that sarama clients only fetches metadata for topics that
changefeeds need but not for all topics on the kafka cluster. The test verifies
the work by 1. creating lots of random kafka topics on the kafka cluster 2.
running some tpcc workload with a changefeed configured to watch all tpcc tables
(note that cdc creates kafka topics for every target tables internally) 3.
assert that changefeed only fetches metadata for tpcc tables but not for other
random topics created in 1.

We check the behavior by checking the logs output from sarama. Previously, we
check logs on every node and asserted that they passed the check. But some nodes
were not part of the nodes running changefeeds and outputting to sarama sinks.

This patch fixes this by giving some time for the test to run and asserting that
at least one node (running changefeed) passes the check.

Fixes: https://github.com/cockroachdb/cockroach/issues/119509
Release note: None

### CODE REVIEW

**Review by andyyang890 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119644)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava, @rharding6373, and @wenyihu6)

___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1631 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119644#-NriDqvp1RrTqVa5kSfz:-NriDqvp1RrTqVa5kSg-:b-qv59u8) ([raw file](https://github.com/cockroachdb/cockroach/blob/903e2fc5e8286ecff775bd7407bd399889ca97ce/pkg/cmd/roachtest/tests/cdc.go#L1631)):*
> ```Go
> 				sinkType: kafkaSink,
> 				targets:  allTpccTargets,
> 				opts:     map[string]string{"initial_scan": "'only'"},
> ```

I would think that deleting this would cause the`feed.waitForCompletion()` call below to hang forever, which seems to be what happens when I run this test on my gceworker. 
___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1643 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119644#-NriJSKq-zKusqlTbz1a:-NriJSKr4emOEtVFyeb9:bmcdby) ([raw file](https://github.com/cockroachdb/cockroach/blob/c884f113c7b23a55b227086a8d67a7819ba6a21d/pkg/cmd/roachtest/tests/cdc.go#L1643)):*
> ```Go
> 			})
> 			feed.waitForCompletion()
> 			ct.waitForWorkload()
> ```

This call should probably happen before you create the changefeed right? Otherwise there would be a race condition.
___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1649 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119644#-NriEVhs76PVhrDT8-8_:-NriEVhs76PVhrDT8-8a:b-s0c0gc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c884f113c7b23a55b227086a8d67a7819ba6a21d/pkg/cmd/roachtest/tests/cdc.go#L1649)):*
> ```Go
> 				// and kafka). We are looking for logs that begin with "client/metadata
> 				// fetching metadata for". This is a log line outputted from
> 				// sarama/client.go.tryRefreshMetadata which tells us what topics are
> ```

Could you include a GitHub snippet URL?
___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1680 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119644#-NriFiRF8yOprstBK-PP:-NriFiRF8yOprstBK-PQ:bvf9xy7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c884f113c7b23a55b227086a8d67a7819ba6a21d/pkg/cmd/roachtest/tests/cdc.go#L1680)):*
> ```Go
> 				}
> 
> 				if len(results) != 3 {
> ```

Is this assertion necessary?

**Review by andyyang890 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119644)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava, @rharding6373, and @wenyihu6)

___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1620 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119644#-NriPv6e39AWNqMMZO4H:-NriPv6e39AWNqMMZO4I:bfc24v4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c884f113c7b23a55b227086a8d67a7819ba6a21d/pkg/cmd/roachtest/tests/cdc.go#L1620)):*
> ```Go
> 
> 			// Run minimal level of tpcc workload and changefeed.
> 			ct.runTPCCWorkload(tpccArgs{warehouses: 1, duration: "1m"})
> ```

Is it necessary to make the TPCC workload run longer? I'd think that as long as it runs at all, it should be enough.

**Comment by wenyihu6** [comment]
*[`pkg/cmd/roachtest/tests/cdc.go` line 1631 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119644#-NriDqvp1RrTqVa5kSfz:-NrjwuaJEkaURZEFJf6x:bdj5zme) ([raw file](https://github.com/cockroachdb/cockroach/blob/903e2fc5e8286ecff775bd7407bd399889ca97ce/pkg/cmd/roachtest/tests/cdc.go#L1631)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

I would think that deleting this would cause the`feed.waitForCompletion()` call below to hang forever, which seems to be what happens when I run this test on my gceworker.
</blockquote></details>

Ahh you are right. I thought I deleted `feed.waitForCompletion()`.

**Comment by wenyihu6** [comment]
*[`pkg/cmd/roachtest/tests/cdc.go` line 1620 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119644#-NriPv6e39AWNqMMZO4H:-NrjwSTr-qPJlwsrcaUb:b-xd3h8b) ([raw file](https://github.com/cockroachdb/cockroach/blob/c884f113c7b23a55b227086a8d67a7819ba6a21d/pkg/cmd/roachtest/tests/cdc.go#L1620)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Is it necessary to make the TPCC workload run longer? I'd think that as long as it runs at all, it should be enough.
</blockquote></details>

I changed it a bit longer to make sure changefeed is emitting messages for the topics.

**Review by wenyihu6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119644)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @andyyang890, @jayshrivastava, and @rharding6373)

___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1643 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119644#-NriJSKq-zKusqlTbz1a:-Nrjx2zJ6iIMw0UMSy5G:byj4hja) ([raw file](https://github.com/cockroachdb/cockroach/blob/c884f113c7b23a55b227086a8d67a7819ba6a21d/pkg/cmd/roachtest/tests/cdc.go#L1643)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

This call should probably happen before you create the changefeed right? Otherwise there would be a race condition.
</blockquote></details>

I meant to delete `feed.waitForCompletion()` here. Done.
___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1649 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119644#-NriEVhs76PVhrDT8-8_:-NrjxE3V7w7befdNwmW0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c884f113c7b23a55b227086a8d67a7819ba6a21d/pkg/cmd/roachtest/tests/cdc.go#L1649)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Could you include a GitHub snippet URL?
</blockquote></details>

Done.
___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1680 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119644#-NriFiRF8yOprstBK-PP:-NrjxEqq7qHbCpD890jN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c884f113c7b23a55b227086a8d67a7819ba6a21d/pkg/cmd/roachtest/tests/cdc.go#L1680)):*
<details><summary><i>Previously, andyyang890 (Andy Yang) wrote…</i></summary><blockquote>

Is this assertion necessary?
</blockquote></details>

Done.

**Review by andyyang890 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119644)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava, @rharding6373, and @wenyihu6)

___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1643 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119644#-NriJSKq-zKusqlTbz1a:-NrkT1M82pKeQp-iHYGV:b-go8git) ([raw file](https://github.com/cockroachdb/cockroach/blob/c884f113c7b23a55b227086a8d67a7819ba6a21d/pkg/cmd/roachtest/tests/cdc.go#L1643)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

I meant to delete `feed.waitForCompletion()` here. Done.
</blockquote></details>

Wouldn't that make the test more flaky? If you use an initial scan and wait for it to complete then we'd be guaranteed that we should see all the expected messages. If you rely on the changefeed to run for some arbitrary length of time, then there would be a race between the changefeed emitting the expected message and us grepping for it.

I feel like what we want is to have an initial scan only changefeed and waiting for it to complete like before, and also waiting for the workload to complete before we start the changefeed.

**Comment by wenyihu6** [comment]
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119644)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava, @rharding6373, and @wenyihu6)
> 
> _[`pkg/cmd/roachtest/tests/cdc.go` line 1643 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119644#-NriJSKq-zKusqlTbz1a:-NrkT1M82pKeQp-iHYGV:b-go8git) ([raw file](https://github.com/cockroachdb/cockroach/blob/c884f113c7b23a55b227086a8d67a7819ba6a21d/pkg/cmd/roachtest/tests/cdc.go#L1643)):_
> 
> Previously, wenyihu6 (Wenyi Hu) wrote…
> > I meant to delete `feed.waitForCompletion()` here. Done.
> 
> Wouldn't that make the test more flaky? If you use an initial scan and wait for it to complete then we'd be guaranteed that we should see all the expected messages. If you rely on the changefeed to run for some arbitrary length of time, then there would be a race between the changefeed emitting the expected message and us grepping for it.
> 
> I feel like what we want is to have an initial scan only changefeed and waiting for it to complete like before, and also waiting for the workload to complete before we start the changefeed.

I'm happy with either way. I think the route I was going was: initial_scan="yes" and make changfeeds run for one minute here for changefeed to emit more messages. We can change it to initial_scan only here as well. Done.

**Review by andyyang890 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119644)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava, @rharding6373, and @wenyihu6)

___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1643 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/119644#-NriJSKq-zKusqlTbz1a:-NrkYBfi8W7wskDwSHtk:b-2x8sxf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c884f113c7b23a55b227086a8d67a7819ba6a21d/pkg/cmd/roachtest/tests/cdc.go#L1643)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

I'm happy with either way. I think the route I was going was: initial_scan="yes" and make changfeeds run for one minute here for changefeed to emit more messages. We can change it to initial_scan only here as well. Done.
</blockquote></details>

We discussed offline that the number of messages don't actually matter right? The metadata refresh function will be called in `Dial`, which will happen once at startup.

Can you move the `ct.waitForWorkload` before the `ct.newChangefeed`?

**Review by andyyang890 — APPROVED** [review]
:lgtm: Thanks for all the comments!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119644#-:-NrktC1o6YEDiVKr_FOW:b-c8zs0)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @jayshrivastava and @rharding6373)

**Review by rharding6373 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119644)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andyyang890, @jayshrivastava, and @wenyihu6)

___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1686 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/119644#-NrlF1te47Dm53UdabqP:-NrlF1te47Dm53UdabqQ:b6yobeb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e184332b2f860b8ffc5fc8ea4e510baee0c0bace/pkg/cmd/roachtest/tests/cdc.go#L1686)):*
> ```Go
> 				for _, res := range results {
> 					// Note that we are not sure which node is running the changefeed, so
> 					// we assert that at least one node passes the check.
> ```

It seems like we want something slightly different for these checks. If any node has metadata for ignoreTopicPrefix or all topics, the test should always fail regardless if a subsequent node passes. Currently, a node may have these but the test could still pass, as long as one node does not but has all the tpcc targets.

**Comment by wenyihu6** [comment]
*[`pkg/cmd/roachtest/tests/cdc.go` line 1686 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/119644#-NrlF1te47Dm53UdabqP:-Nrlq2Q0DOqZIbQDFRwQ:bsfvz40) ([raw file](https://github.com/cockroachdb/cockroach/blob/e184332b2f860b8ffc5fc8ea4e510baee0c0bace/pkg/cmd/roachtest/tests/cdc.go#L1686)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

It seems like we want something slightly different for these checks. If any node has metadata for ignoreTopicPrefix or all topics, the test should always fail regardless if a subsequent node passes. Currently, a node may have these but the test could still pass, as long as one node does not but has all the tpcc targets.
</blockquote></details>

Ack. I changed the passing condition to 1. one condition required for all nodes 2. one condition required for just one node.

**Comment by wenyihu6** [comment]
Confirmed that the new test still passes on gce: 

```
22:28:55 test_runner.go:982: metrics: https://go.crdb.dev/roachtest-grafana/wenyihu-1709159065/cdc-kafka-topics/1709159181387/1709159438706
22:28:55 test_runner.go:1043: [w0] --- PASS: cdc/kafka-topics (137.32s)
--- PASS: cdc/kafka-topics (137.32s)
22:28:55 test_runner.go:838: [w0] test passed: cdc/kafka-topics (run 1)
```

**Review by rharding6373 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119644)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andyyang890, @jayshrivastava, and @wenyihu6)

___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1663 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/119644#-NrlvTHP9ltJfA4FznyE:-NrlvTHP9ltJfA4FznyF:bf5vaup) ([raw file](https://github.com/cockroachdb/cockroach/blob/2874efbdb98ffe0d1c15f0d0e799b4e4b075ce00/pkg/cmd/roachtest/tests/cdc.go#L1663)):*
> ```Go
> 				}
> 
> 				requiredForAllNodes := func(str string) error {
> ```

nit: s/requiredForAllNodes/hasUnexpectedMetadata (or something similarly descriptive)
___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1676 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/119644#-NrlvEeLEKaTBoOB7sg2:-NrlvEeLEKaTBoOB7sg3:b9es6jf) ([raw file](https://github.com/cockroachdb/cockroach/blob/2874efbdb98ffe0d1c15f0d0e799b4e4b075ce00/pkg/cmd/roachtest/tests/cdc.go#L1676)):*
> ```Go
> 					return nil
> 				}
> 				requiredForOneNodeOnly := func(str string) bool {
> ```

nit: s/requiredForOneNodeOnly/hasTPCCTargets
___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1677 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/119644#-NrlyJqq22u3sV4U4Kxl:-NrlyJqq22u3sV4U4Kxm:b-a4kkww) ([raw file](https://github.com/cockroachdb/cockroach/blob/2874efbdb98ffe0d1c15f0d0e799b4e4b075ce00/pkg/cmd/roachtest/tests/cdc.go#L1677)):*
> ```Go
> 				}
> 				requiredForOneNodeOnly := func(str string) bool {
> 					for _, target := range allTpccTargets {
> ```

If we have one node with all the tpcc targets and another node with only a subset, should that be a test failure?
___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1687 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/119644#-NrlxH6f57Uf8Bxwe3O6:-NrlxH6f57Uf8Bxwe3O7:bdny8up) ([raw file](https://github.com/cockroachdb/cockroach/blob/2874efbdb98ffe0d1c15f0d0e799b4e4b075ce00/pkg/cmd/roachtest/tests/cdc.go#L1687)):*
> ```Go
> 				}
> 
> 				conditionForOneNodeOnly := false
> ```

nit: s/conditionForOneNodeOnly/hasExpectedTargets (or something similarly descriptive)
___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1696 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/119644#-NrlyYFS2bdAmKKzaK_o:-NrlyYFS2bdAmKKzaK_p:bb7lbs2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2874efbdb98ffe0d1c15f0d0e799b4e4b075ce00/pkg/cmd/roachtest/tests/cdc.go#L1696)):*
> ```Go
> 					}
> 					if checkForAllNodes := requiredForAllNodes(res.Stdout); checkForAllNodes != nil {
> 						err = errors.CombineErrors(err, errors.Wrapf(checkForAllNodes, "node %d", i+1))
> ```

nice

**Review by wenyihu6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119644)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andyyang890, @jayshrivastava, and @rharding6373)

___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1677 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/119644#-NrlyJqq22u3sV4U4Kxl:-Nrm4AdN7vtAcIrk4dLJ:bk4pe2o) ([raw file](https://github.com/cockroachdb/cockroach/blob/2874efbdb98ffe0d1c15f0d0e799b4e4b075ce00/pkg/cmd/roachtest/tests/cdc.go#L1677)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

If we have one node with all the tpcc targets and another node with only a subset, should that be a test failure?
</blockquote></details>

I think that is unexpected as well. I would expect a node to either have the log line including all tpcc targets or not at all. The test currently doesn't fail in this case, but I would prefer to skip the complexity now. This test just checks to make sure we are only fetching metadata for tpcc targets but not other random topics. If a node fetches metadata for some tpcc tables but not all, I think it's unexpected but not what the test is trying to test here. What do you think?

**Review by rharding6373 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119644)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @andyyang890, @jayshrivastava, and @wenyihu6)

___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1677 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/119644#-NrlyJqq22u3sV4U4Kxl:-Nrm82g8CWfFvGpr4krs:bm6xuan) ([raw file](https://github.com/cockroachdb/cockroach/blob/2874efbdb98ffe0d1c15f0d0e799b4e4b075ce00/pkg/cmd/roachtest/tests/cdc.go#L1677)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

I think that is unexpected as well. I would expect a node to either have the log line including all tpcc targets or not at all. The test currently doesn't fail in this case, but I would prefer to skip the complexity now. This test just checks to make sure we are only fetching metadata for tpcc targets but not other random topics. If a node fetches metadata for some tpcc tables but not all, I think it's unexpected but not what the test is trying to test here. What do you think?
</blockquote></details>

I'm worried that we're going to miss a class of bugs where sarama doesn't get metadata for all of the tables that it should, either because of a bug in sarama or we didn't provide it all the right tables. How do you think we can get test coverage for this? Or why is this not a concern?

I realize that this code was here before this PR, but this seems like an opportunity to make this test, and therefore quality and confidence in our product, better.

**Comment by wenyihu6** [comment]
*[`pkg/cmd/roachtest/tests/cdc.go` line 1677 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/119644#-NrlyJqq22u3sV4U4Kxl:-Nrmahmo6UbB3wwgnPyX:b-ixdin2) ([raw file](https://github.com/cockroachdb/cockroach/blob/2874efbdb98ffe0d1c15f0d0e799b4e4b075ce00/pkg/cmd/roachtest/tests/cdc.go#L1677)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

I'm worried that we're going to miss a class of bugs where sarama doesn't get metadata for all of the tables that it should, either because of a bug in sarama or we didn't provide it all the right tables. How do you think we can get test coverage for this? Or why is this not a concern?

I realize that this code was here before this PR, but this seems like an opportunity to make this test, and therefore quality and confidence in our product, better.
</blockquote></details>

Sounds good. I changed the logic to add this check and confirmed that the test still passes on gce worker. 

```
02:02:54 test_runner.go:1043: [w0] --- PASS: cdc/kafka-topics (143.10s)
--- PASS: cdc/kafka-topics (143.10s)
02:02:54 test_runner.go:838: [w0] test passed: cdc/kafka-topics (run 1)
02:02:54 cluster.go:1069: [w0] saving cluster wenyihu-1709171888-01-n4cpu4 [tag:] (4 nodes) for debugging (--debug specified)
02:02:54 test_runner.go:641: [w0] No work remaining; runWorker is bailing out...
No work remaining; runWorker is bailing out...
02:02:54 test_runner.go:549: [w0] Worker exiting; no cluster to destroy.
02:02:54 test_runner.go:382: PASS
PASS
```

**Review by rharding6373 — APPROVED** [review]
:lgtm: Nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119644#-:-Nrpatbr4M4bxMco05sm:bcmw7ss)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @andyyang890, @jayshrivastava, and @wenyihu6)

___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1677 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/119644#-NrlyJqq22u3sV4U4Kxl:-Nrpax9d1YAain6dd8E-:bpnun65) ([raw file](https://github.com/cockroachdb/cockroach/blob/2874efbdb98ffe0d1c15f0d0e799b4e4b075ce00/pkg/cmd/roachtest/tests/cdc.go#L1677)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

Sounds good. I changed the logic to add this check and confirmed that the test still passes on gce worker. 

```
02:02:54 test_runner.go:1043: [w0] --- PASS: cdc/kafka-topics (143.10s)
--- PASS: cdc/kafka-topics (143.10s)
02:02:54 test_runner.go:838: [w0] test passed: cdc/kafka-topics (run 1)
02:02:54 cluster.go:1069: [w0] saving cluster wenyihu-1709171888-01-n4cpu4 [tag:] (4 nodes) for debugging (--debug specified)
02:02:54 test_runner.go:641: [w0] No work remaining; runWorker is bailing out...
No work remaining; runWorker is bailing out...
02:02:54 test_runner.go:549: [w0] Worker exiting; no cluster to destroy.
02:02:54 test_runner.go:382: PASS
PASS
```
</blockquote></details>

Thank you, looks good.
___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1690 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/119644#-NrpaZ0I3Ec63hb-KI6k:-NrpaZ0I3Ec63hb-KI6l:b-3nex6k) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfaf669c2f7c82c8462189bac2e9313065753867/pkg/cmd/roachtest/tests/cdc.go#L1690)):*
> ```Go
> 					}
> 
> 					if !hasSomeTpccTargets && hasAllTpccTargets {
> ```

I think you can get rid of this condition and the panic, since this can only happen if there are no tpcc targets (so it should never happen).

**Comment by wenyihu6** [comment]
Thanks for the thorough PR reviews!!

bors r=rharding6373,andyyang890

**Review by wenyihu6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/119644)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @andyyang890, @jayshrivastava, and @rharding6373)

___
*[`pkg/cmd/roachtest/tests/cdc.go` line 1690 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/119644#-NrpaZ0I3Ec63hb-KI6k:-NrqC1Fn7fDqOaQwU4o7:b-rmyq84) ([raw file](https://github.com/cockroachdb/cockroach/blob/cfaf669c2f7c82c8462189bac2e9313065753867/pkg/cmd/roachtest/tests/cdc.go#L1690)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

I think you can get rid of this condition and the panic, since this can only happen if there are no tpcc targets (so it should never happen).
</blockquote></details>

Ack. Removed.

**Pull request merged**
