### PR TITLE
ci: add script for compose nightly, dev support

### LINKED ISSUE #67151: ci: add bazel `Nightlies / Compose Tests` for CI
Epic CRDB-8306

### LINKED ISSUE #70893: dev: teach `dev` how to do `compose` tests
Epic CRDB-8036

### PR DESCRIPTION
**Pull request by rickystewart**
Closes #67151.
Closes #70893.

Release note: None

### CODE REVIEW

**Comment by rickystewart** [comment]
sample run for compose nightly: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_ComposeTestsBazel/4206881?buildTab=log&focusLine=85045&linesState=4597.4617.85042.85043

**Review by rail — APPROVED** [review]
:lgtm: with a small fix in`BUILD.bazel`

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75472#-:-MuLqHJ08a4N9fL_kEuX:bo4ktmz)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rickystewart)

___
*[pkg/compose/compare/compare/BUILD.bazel, line 24 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75472#-MuLoJYZ3x75jNdDcNFt:-MuLoJYZ3x75jNdDcNFu:b-wzt80k) ([raw file](https://github.com/cockroachdb/cockroach/blob/34f4a1d0d7b2cf6f68ae67ee5e7a08f10acaf4d2/pkg/compose/compare/compare/BUILD.bazel#L24)):*
> ```Starlark
>         "@com_github_jackc_pgx_v4//:pgx",
>     ],
>     visibility = ["//pkg/compose:__subpackages__"],
> ```

need to move this a bit up to make the CI happy.
___
*[pkg/compose/compose_test.go, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75472#-MuLopgb6lv-dSq1GmHz:-MuLopgb6lv-dSq1GmI-:bpou4t3) ([raw file](https://github.com/cockroachdb/cockroach/blob/34f4a1d0d7b2cf6f68ae67ee5e7a08f10acaf4d2/pkg/compose/compose_test.go#L40)):*
> ```Go
> 
> func copyBin(src, dst string) error {
> 	srcContents, err := ioutil.ReadFile(src)
> ```

Shouldn't be an issue here, because we don't deal with huge files, but ideally you can use `io.Copy()`, which copies files in chunks.

**Comment by rickystewart** [comment]
bors r=rail

**Comment by rickystewart** [comment]
bors r=rail

**Pull request merged**
