### PR TITLE
sql: fix confupdtype, confdeltype, confmatchtype in pg_constraint

### LINKED ISSUE #34862: foreign key update and delete actions are not reflected in pg_constraint table
FK's update and delete actions works fine, but not reflected in `pg_constraint` table.

Steps to reproduce:

```sql
CREATE TABLE "foo" ("id" INT PRIMARY KEY)

CREATE TABLE "bar" ("id" INT PRIMARY KEY, "fooId" INT)

CREATE INDEX "idx_fooId" ON "bar" ("fooId") 

ALTER TABLE "bar" 
     ADD CONSTRAINT "fk_foo_bar" 
     FOREIGN KEY ("fooId") REFERENCES "foo"("id") 
     ON UPDATE SET NULL
     ON DELETE SET NULL

SELECT "conname", "confupdtype", "confdeltype" FROM "pg_constraint"
```
results:

conname	| confupdtype	| confdeltype
-----------|----------------|-------------
fk_foo_bar |	a  |	a

from the postgres [docs](https://www.postgresql.org/docs/current/catalog-pg-constraint.html):
`confupdtype` - Foreign key update action code: a = no action, r = restrict, c = cascade, n = set null, d = set default
`confdeltype` - Foreign key deletion action code: a = no action, r = restrict, c = cascade, n = set null, d = set default

### PR DESCRIPTION
**Pull request by knz**
Fixes #34862. For TypeORM compat. cc @awoods187

### CODE REVIEW

**Review by BramGruneir — APPROVED** [review]
:lgtm: with minor fixes

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35052#-:-LZ5bVHmATcgbIBuykf7:b-92g5ub)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @bobvawter and @knz)

___
*[pkg/sql/pg_catalog.go, line 646 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35052#-LZ5MJ4_1oL5CXzvWd1V:-LZ5MJ4_1oL5CXzvWd1W:bfdtgu2) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ea5603ebee00fb7e4d99b70f1afae6108c3bb15/pkg/sql/pg_catalog.go#L646)):*
> ```Go
> 		sqlbase.ForeignKeyReference_FULL:   fkMatchTypeFull,
> 		// TODO(knz,bram): add when partial is supported.
> 		// sqlbase.ForeignKeyReferenc_PARTIAL: fkMatchTypeSimple,
> ```

might as well put in it even if it's not supported and just leave a note that it's not
___
*[pkg/sql/pg_catalog.go, line 649 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35052#-LZ5MWBiBuXBAmgowPcj:-LZ5MWBiBuXBAmgowPck:b-9dttjb) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ea5603ebee00fb7e4d99b70f1afae6108c3bb15/pkg/sql/pg_catalog.go#L649)):*
> ```Go
> 	}
> 	// Avoid unused warning for constants.
> 	_ = fkMatchTypePartial
> ```

remove this.
___
*[pkg/sql/logictest/testdata/logic_test/pg_catalog, line 1720 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35052#-LZ5b4by-DdOyHlc-8lz:-LZ5b4by-DdOyHlc-8m-:bn65umj) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ea5603ebee00fb7e4d99b70f1afae6108c3bb15/pkg/sql/logictest/testdata/logic_test/pg_catalog#L1720)):*
> ```
>     i INT DEFAULT 123 REFERENCES t(x) ON UPDATE SET DEFAULT,
>     j INT REFERENCES t(x) ON UPDATE CASCADE
>   );
> ```

Please add one tests case that has both a delete and updated to ensure that both paths are always followed.
___
*[pkg/sql/sqlbase/structured.proto, line 219 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35052#-LZ5bHwbEujxUQtK46Ks:-LZ5bHwbEujxUQtK46Kt:bona1qr) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ea5603ebee00fb7e4d99b70f1afae6108c3bb15/pkg/sql/sqlbase/structured.proto#L219)):*
> ```protobuf
>     SIMPLE = 0;
>     FULL = 1;
>     // TODO(knz/bram): Update pg_constraint when PARTIAL is supported.
> ```

Just a note that the chance of us supporting it is pretty low.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/35052)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @bobvawter and @BramGruneir)

___
*[pkg/sql/pg_catalog.go, line 646 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35052#-LZ5MJ4_1oL5CXzvWd1V:-LZ8Yjda24shwo3FPmEj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ea5603ebee00fb7e4d99b70f1afae6108c3bb15/pkg/sql/pg_catalog.go#L646)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

might as well put in it even if it's not supported and just leave a note that it's not
</blockquote></details>

Done.
___
*[pkg/sql/pg_catalog.go, line 649 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35052#-LZ5MWBiBuXBAmgowPcj:-LZ8Yk2g6wLh-daXCYLr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ea5603ebee00fb7e4d99b70f1afae6108c3bb15/pkg/sql/pg_catalog.go#L649)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

remove this.
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/pg_catalog, line 1720 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35052#-LZ5b4by-DdOyHlc-8lz:-LZ8YklE0_p3vLzYJtzy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ea5603ebee00fb7e4d99b70f1afae6108c3bb15/pkg/sql/logictest/testdata/logic_test/pg_catalog#L1720)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Please add one tests case that has both a delete and updated to ensure that both paths are always followed.
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/structured.proto, line 219 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/35052#-LZ5bHwbEujxUQtK46Ks:-LZ8Yl_r10XLFGWMfgjt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ea5603ebee00fb7e4d99b70f1afae6108c3bb15/pkg/sql/sqlbase/structured.proto#L219)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Just a note that the chance of us supporting it is pretty low.
</blockquote></details>

Done.

**Comment by knz** [comment]
TFYR!

bors r+

**Pull request merged**
