### PR TITLE
pkg/jobs: Scheduled jobs

### PR DESCRIPTION
**Pull request by miretskiy**
Informs #49346

Add initial implementation of scheduled jobs framework.
Scheduled job is an extension of the system job, which can run
periodically.

Release notes: None

### CODE REVIEW

**Review by pbardea — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 3 of 3 files at r2, 2 of 2 files at r3, 7 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49599)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @pbardea)

___
*[pkg/jobs/executor_impl.go, line 31 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49599#-M8k5ir4CCxwOiwX9Wur:-M8k5ir4CCxwOiwX9Wus:b-xhwj31) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5e1e5e3a2674edd2a52a151904332c43ae5ea06/pkg/jobs/executor_impl.go#L31)):*
> ```Go
> 
> // inlineScheduledJobExecutor implements ScheduledJobExecutor interface.
> // this executor runs SQL statement "inline" -- that is, it executes statement
> ```

nit: capitalization for "this"
___
*[pkg/jobs/executor_impl.go, line 41 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49599#-M8k6_Mc-yfmG6ZR2NEJ:-M8k6_Mc-yfmG6ZR2NEK:b-bi57nv) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5e1e5e3a2674edd2a52a151904332c43ae5ea06/pkg/jobs/executor_impl.go#L41)):*
> ```Go
> const retryFailedJobAfter = time.Minute
> 
> func (e *inlineScheduledJobExecutor) ExecuteJob(
> ```

It may be useful to add a comment here pointing to the `ScheduledJobExecutor` interface which may provide more documentation about this API in general. I've seen the format `// ExecuteJob is part of the jobs.ScheduledJobExecutor interface.`
___
*[pkg/jobs/executor_impl_test.go, line 30 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49599#-M8k7K4O-3GA0d7gk88t:-M8k7K4O-3GA0d7gk88u:b73tffm) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5e1e5e3a2674edd2a52a151904332c43ae5ea06/pkg/jobs/executor_impl_test.go#L30)):*
> ```Go
> 
> 	var tests = []struct {
> 		onerror jobspb.ScheduleDetails_ErrorHandlingBehavior
> ```

nit: s/onerror/onError/
___
*[pkg/jobs/executor_impl_test.go, line 31 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49599#-M8k91ZLB9xRJoBNx8gO:-M8k91ZLB9xRJoBNx8gP:b1p6j6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5e1e5e3a2674edd2a52a151904332c43ae5ea06/pkg/jobs/executor_impl_test.go#L31)):*
> ```Go
> 	var tests = []struct {
> 		onerror jobspb.ScheduleDetails_ErrorHandlingBehavior
> 		nextRun time.Time
> ```

nit: I think it may be useful to name this `expectedNextRun` for readability.
___
*[pkg/jobs/job_scheduler.go, line 47 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49599#-M8kAQ_C4m2WJeM7KW-_:-M8kAQ_C4m2WJeM7KW-a:bi811d1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5e1e5e3a2674edd2a52a151904332c43ae5ea06/pkg/jobs/job_scheduler.go#L47)):*
> ```Go
> var prodJobSchedulerEnv jobSchedulerEnv = &prodJobSchedulerEnvImpl{}
> 
> const createdByName = "schedule"
> ```

I think it would be good to prefix this with crdb or something of the sort.
___
*[pkg/jobs/job_scheduler.go, line 101 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49599#-M8kAmxC09BqBIotX6vi:-M8kAmxC09BqBIotX6vj:b2000d6) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5e1e5e3a2674edd2a52a151904332c43ae5ea06/pkg/jobs/job_scheduler.go#L101)):*
> ```Go
> }
> 
> // unmarshalScheduledJOb is a helper to desiralize a row returned by
> ```

nit: s/JOb/job/
___
*[pkg/jobs/job_scheduler.go, line 166 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49599#-M8kBYUF8OnaYUfW2POv:-M8kBYUF8OnaYUfW2POw:b-z8ymao) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5e1e5e3a2674edd2a52a151904332c43ae5ea06/pkg/jobs/job_scheduler.go#L166)):*
> ```Go
> }
> 
> func (s *jobScheduler) findJobs(ctx context.Context, txn *kv.Txn) error {
> ```

The name of this method feels a bit off to me. I would not really expect `findJobs` to go ahead and execute the job.
___
*[pkg/jobs/job_scheduler_test.go, line 53 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49599#-M8kEwwu5B39KgxVd-us:-M8kEwwu5B39KgxVd-ut:b1lpk5q) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5e1e5e3a2674edd2a52a151904332c43ae5ea06/pkg/jobs/job_scheduler_test.go#L53)):*
> ```Go
> 	} {
> 		t.Run(wait.String(), func(t *testing.T) {
> 			// Create job that with target wait behavior.
> ```

I think the'ers an extra "that" in here? 
___
*[pkg/jobs/scheduled_job.go, line 304 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49599#-M8kGggxE7-lkhe4EhRr:-M8kGggy2k6R1ftIHjfO:b-xmh7qc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5e1e5e3a2674edd2a52a151904332c43ae5ea06/pkg/jobs/scheduled_job.go#L304)):*
> ```Go
> }
> 
> // marhalChanges marshals all changes in the in-memory representation and returns
> ```

nit: s/marhalChanges/marshalChanges
___
*[pkg/sql/sqlbase/system.go, line 319 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49599#-M8k4ggg12aRkk0uAHRE:-M8k4gghEQ8NpfE2gSRk:bclx7uj) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f0561539f4e52d88e5ff700e3b7bfc6f6124515/pkg/sql/sqlbase/system.go#L319)):*
> ```Go
>     executor_type    STRING NOT NULL,
>     execution_args    BYTES NOT NULL,
>     schedule_changes BYTES,
> ```

nit: Alignment here and above

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49599)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @pbardea)

___
*[pkg/jobs/executor_impl.go, line 41 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49599#-M8k6_Mc-yfmG6ZR2NEJ:-M8l9oDB8DgVLELFHwNp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5e1e5e3a2674edd2a52a151904332c43ae5ea06/pkg/jobs/executor_impl.go#L41)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

It may be useful to add a comment here pointing to the `ScheduledJobExecutor` interface which may provide more documentation about this API in general. I've seen the format `// ExecuteJob is part of the jobs.ScheduledJobExecutor interface.`
</blockquote></details>

Done.
___
*[pkg/jobs/job_scheduler.go, line 47 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49599#-M8kAQ_C4m2WJeM7KW-_:-M8lAHdDEkvkbme4dCg1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5e1e5e3a2674edd2a52a151904332c43ae5ea06/pkg/jobs/job_scheduler.go#L47)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

I think it would be good to prefix this with crdb or something of the sort.
</blockquote></details>

Done.
___
*[pkg/jobs/job_scheduler.go, line 166 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49599#-M8kBYUF8OnaYUfW2POv:-M8lB1G_BIOFSCdoAWYJ:brythjh) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5e1e5e3a2674edd2a52a151904332c43ae5ea06/pkg/jobs/job_scheduler.go#L166)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

The name of this method feels a bit off to me. I would not really expect `findJobs` to go ahead and execute the job.
</blockquote></details>

renamed.
___
*[pkg/jobs/job_scheduler_test.go, line 53 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/49599#-M8kEwwu5B39KgxVd-us:-M8lB7V92u-1Fb52-a0b:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5e1e5e3a2674edd2a52a151904332c43ae5ea06/pkg/jobs/job_scheduler_test.go#L53)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

I think the'ers an extra "that" in here? 
</blockquote></details>

Done.
___
*[pkg/sql/sqlbase/system.go, line 319 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/49599#-M8k4ggg12aRkk0uAHRE:-M8kUZnb9yXRDrZoTFoJ:byxrise) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f0561539f4e52d88e5ff700e3b7bfc6f6124515/pkg/sql/sqlbase/system.go#L319)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

nit: Alignment here and above
</blockquote></details>

Addressed in https://github.com/cockroachdb/cockroach/pull/49765

**Comment by miretskiy** [comment]
@pbardea  Rebased; CI is now green. PTAL.

**Review by pbardea — APPROVED** [review]
> Reviewed 9 of 11 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49599)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt, @miretskiy, and @pbardea)

___
*[pkg/jobs/jobspb/schedule.proto, line 64 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49599#-M9JlOD3-FapbUf4JiGH:-M9JlOD3-FapbUf4JiGI:bcfbrik) ([raw file](https://github.com/cockroachdb/cockroach/blob/71027ef4da4f6acd84d0f09bf92cda3b7b192cb0/pkg/jobs/jobspb/schedule.proto#L64)):*
> ```protobuf
> }
> 
> // Message representing sql statement to executo.
> ```

Missing 'r' at the end.
___
*[pkg/jobs/jobspb/schedule.proto, line 67 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49599#-M9JlQRv9C4pBV85TGWM:-M9JlQRv9C4pBV85TGWN:bn7evgy) ([raw file](https://github.com/cockroachdb/cockroach/blob/71027ef4da4f6acd84d0f09bf92cda3b7b192cb0/pkg/jobs/jobspb/schedule.proto#L67)):*
> ```protobuf
> message SqlStatementExecutionArg {
>   string statement = 1;
> }
> ```

Reviewable doesn't seem happy about this line - is it missing a newline?

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49599)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @pbardea)

___
*[pkg/jobs/jobspb/schedule.proto, line 64 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49599#-M9JlOD3-FapbUf4JiGH:-M9KeBJA4ScIUVlAq1zi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/71027ef4da4f6acd84d0f09bf92cda3b7b192cb0/pkg/jobs/jobspb/schedule.proto#L64)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Missing 'r' at the end.
</blockquote></details>

Done.
___
*[pkg/jobs/jobspb/schedule.proto, line 67 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/49599#-M9JlQRv9C4pBV85TGWM:-M9KeDhc7tV1Ce9IXdmO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/71027ef4da4f6acd84d0f09bf92cda3b7b192cb0/pkg/jobs/jobspb/schedule.proto#L67)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Reviewable doesn't seem happy about this line - is it missing a newline?
</blockquote></details>

Done.

**Pull request merged**
