### PR TITLE
kv: wait on latches on each key in reverse acquisition order

### PR DESCRIPTION
**Pull request by nvb**
This commit allocates latch IDs from the top of the uint64 space and in reverse order. This is done to order latches in the tree on the same key in reverse order of acquisition. Doing so ensures that when we iterate over the tree and see a key with many conflicting latches, we visit the latches on that key in the reverse order that they will be released. In doing so, we minimize the number of open channels that we wait on (calls to `waitForSignal`) and minimize the number of goroutine scheduling points. This is important to avoid spikes in runnable goroutine after each request completes, which can negatively affect node health.

See [experiments below](https://github.com/cockroachdb/cockroach/pull/109349#issuecomment-1690386251).

Epic: None
Release note (performance improvement): The impact of high concurrency blind writes to the same key on goroutine scheduling latency was reduced.

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
The following test demonstrates the expected improvement from this PR. I ran the following test, which spins up 512 concurrent workload threads to UPSERT the same key.
```sh
roachprod create local -n1
roachprod put    local cockroach
roachprod start  local
roachprod run    local -- ./cockroach workload run kv --init --cycle-length=1 --concurrency=51 --duration=5m
```
For the first 5 minutes, I ran with `master`. For the next 5, I ran with this patch. We see a large improvement in `Goroutine Scheduling Latency: 99th percentile` and `Runnable Goroutines per CPU` with this patch.

Screenshot 2023-08-23 at 1 45 55 PM

Screenshot 2023-08-23 at 1 46 01 PM

**Comment by nvanbenschoten** [comment]
Adding the `backport-23.1.x` label, but I'll let this bake on master for a few weeks before landing the backport.

**Review by arulajmani — APPROVED** [review]
:shipit: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/109349#-:-NcYsmimDVeb_M7q1HyN:bizlbj6)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif and @kvoli)

**Review by kvoli — APPROVED** [review]
Nice!

**Comment by nvanbenschoten** [comment]
TFTR!

bors r=arulajmani,kvoli

**Pull request merged**
