### PR TITLE
kvclient: misc range cache cleanups

### PR DESCRIPTION
**Pull request by andrewbaptist**
Numerous small cleanups to the range cache. 

After these changes, The RangeCache and related classes have a much simpler interface with some nice usability benefits:

1) CacheEntry is no longer public. This is good because it is intended to be immutable and it is now easier to audit its usage.
2) Test only methods are more clearly changed to designate them that way. This will prevent new code from using them incorrectly
3) Unused methods are removed from the interface.

### CODE REVIEW

**Comment by andrewbaptist** [comment]
Let me know if you'd prefer me to split this into smaller commits. This is one of the last changes I'm going to make to the RC and will be focusing on the server side next week.

**Review by arulajmani — APPROVED** [review]
:lgtm: modulo comments. Feel free to ignore the nits. 

> Reviewed 11 of 11 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, 3 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118329#-:-Nq-aojTD54j4U4KOUL0:b-mzhldt)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @andrewbaptist, @DrewKimball, and @dt)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118329#-Npzz_wQ39WemHU1cvrY):*
Should we make it private (in another commit) by renaming to `cacheEntry`?

Edit: I see you've done this in commit 2. Nice!
___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118329#-NpzvpRICKFh-iL3Wnix):*
"menthod"
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 1035 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118329#-Npzw2rC0zd0copqr7WC:-Npzw2rC0zd0copqr7WD:b-qq7643) ([raw file](https://github.com/cockroachdb/cockroach/blob/e364719525b53dba62f00a9156486d6dd54f73ff/pkg/kv/kvclient/rangecache/range_cache.go#L1035)):*
> ```Go
> // and `key` is the EndKey and StartKey of two adjacent ranges, the first range
> // is returned instead of the second (which technically contains the given key).
> // This is only used by tests.
> ```

Instead of the comment, prefix the method name with "Testing instead"
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 1036 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118329#-Npzx0I19eZTLlt-OcJg:-Npzx0I19eZTLlt-OcJh:bprliv7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e364719525b53dba62f00a9156486d6dd54f73ff/pkg/kv/kvclient/rangecache/range_cache.go#L1036)):*
> ```Go
> // is returned instead of the second (which technically contains the given key).
> // This is only used by tests.
> // TODO(baptist): return an err instead of an empty RangeInfo
> ```

Until then, maybe return a pointer here? That way, you can return nil instead of having callers check if the range descriptor is initialized or not.
___
*[`pkg/ccl/multiregionccl/roundtrips_test.go` line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118329#-NpzxHry1cPkFtNehWW8:-NpzxHry1cPkFtNehWW9:b-8jkbwl) ([raw file](https://github.com/cockroachdb/cockroach/blob/0baf22a03d5f55e2611701bc723e3e0b713ab051/pkg/ccl/multiregionccl/roundtrips_test.go#L126)):*
> ```Go
> 			// Check that the cache was indeed populated.
> 			cache := tc.Server(i).DistSenderI().(*kvcoord.DistSender).RangeDescriptorCache()
> 			entry := cache.GetCached(context.Background(), tablePrefix, false /* inverted */)
> ```

s/entry/rangeInfo/g 
___
*[`pkg/kv/bulk/sst_batcher_test.go` line 297 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118329#-NpzzhEgBLVq4UvTp7WS:-NpzzhEgBLVq4UvTp7WT:b-df0htc) ([raw file](https://github.com/cockroachdb/cockroach/blob/0baf22a03d5f55e2611701bc723e3e0b713ab051/pkg/kv/bulk/sst_batcher_test.go#L297)):*
> ```Go
> 				ent, err := ds.RangeDescriptorCache().Lookup(ctx, keys.MustAddr(key(k)))
> 				require.NoError(t, err)
> 				mockCache.Insert(ctx, roachpb.RangeInfo{Desc: *ent.Desc()})
> ```

Was this meant to be a part of this commit?
___
*[`pkg/kv/kvclient/rangecache/range_cache_test.go` line 514 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118329#-Npzzu_X1HjT1bKeHxsg:-Npzzu_X1HjT1bKeHxsh:b-nuq5kk) ([raw file](https://github.com/cockroachdb/cockroach/blob/0baf22a03d5f55e2611701bc723e3e0b713ab051/pkg/kv/kvclient/rangecache/range_cache_test.go#L514)):*
> ```Go
> 
> 	entNext := cache.GetCached(ctx, roachpb.RKeyMin.Next(), false /* inverted */)
> 	require.True(t, entMin == entNext)
> ```

nit: technically these don't belong in this commit.
___
*[`pkg/kv/kvclient/rangecache/range_cache_test.go` line 1078 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118329#-Nq--UPD0-0E21FB25Yg:-Nq--UPD0-0E21FB25Yh:b-up8rks) ([raw file](https://github.com/cockroachdb/cockroach/blob/e364719525b53dba62f00a9156486d6dd54f73ff/pkg/kv/kvclient/rangecache/range_cache_test.go#L1078)):*
> ```Go
> 	require.True(t, clearOlderOverlapping(ctx, cache, bToCDesc))
> 	cache.addEntryLocked(&CacheEntry{desc: *bToCDesc})
> 	ri, _ = cache.getCachedRLocked(ctx, roachpb.RKey("c"), true)
> ```

Given this is a RLocked method, we shouldn't call it without locking the mutex. Maybe consider creating a private version of `getCached` that wrapps around `getCachedRLocked`? Or, something local to this test.
___
*[`pkg/kv/kvclient/rangecache/range_cache_test.go` line 1156 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/118329#-Nq-_yBI2Nj_CDJ41Ls7:-Nq-_yBI2Nj_CDJ41Ls8:b-xqdb5o) ([raw file](https://github.com/cockroachdb/cockroach/blob/a14eb1da8e77d29cfa5c4cee964007a367aa25b0/pkg/kv/kvclient/rangecache/range_cache_test.go#L1156)):*
> ```Go
> 		// If expNewest is false, expNewer indicates the expected 2nd ret val of
> 		// clearOlderOverlapping().
> 		expNewer *roachpb.RangeDescriptor
> ```

nit: technically unrelated to this commit.

**Comment by arulajmani** [comment]
By the way, the PR title here needs changing. Maybe something like "kvclient: misc range cache cleanups"

**Review by andrewbaptist — COMMENTED** [review]
TFTR!

Title changed. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118329#-:-Nq2pe2MDeh-bGVdbTgO:botvvua)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani, @DrewKimball, and @dt)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118329#-Npzz_wQ39WemHU1cvrY):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Should we make it private (in another commit) by renaming to `cacheEntry`?

Edit: I see you've done this in commit 2. Nice!
</blockquote></details>

Thanks!
___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118329#-NpzvpRICKFh-iL3Wnix):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

"menthod"
</blockquote></details>

Fixed
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 1035 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118329#-Npzw2rC0zd0copqr7WC:-Nq2z-3z7xEos0-C1Nn6:bq1wnys) ([raw file](https://github.com/cockroachdb/cockroach/blob/e364719525b53dba62f00a9156486d6dd54f73ff/pkg/kv/kvclient/rangecache/range_cache.go#L1035)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Instead of the comment, prefix the method name with "Testing instead"
</blockquote></details>

Changed to add the prefix
___
*[`pkg/kv/kvclient/rangecache/range_cache.go` line 1036 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118329#-Npzx0I19eZTLlt-OcJg:-Nq2z1NS43jXlUDpg2q5:blm3qo6) ([raw file](https://github.com/cockroachdb/cockroach/blob/e364719525b53dba62f00a9156486d6dd54f73ff/pkg/kv/kvclient/rangecache/range_cache.go#L1036)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Until then, maybe return a pointer here? That way, you can return nil instead of having callers check if the range descriptor is initialized or not.
</blockquote></details>

I changed to return an err. Since it is test only it was straightforward, and actually fixed some wrong nil checks.
___
*[`pkg/ccl/multiregionccl/roundtrips_test.go` line 126 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118329#-NpzxHry1cPkFtNehWW8:-Nq2zJXh7-YtOZqmYd5Q:bwvxct9) ([raw file](https://github.com/cockroachdb/cockroach/blob/0baf22a03d5f55e2611701bc723e3e0b713ab051/pkg/ccl/multiregionccl/roundtrips_test.go#L126)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

s/entry/rangeInfo/g
</blockquote></details>

changed to `ri`
___
*[`pkg/kv/bulk/sst_batcher_test.go` line 297 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118329#-NpzzhEgBLVq4UvTp7WS:-Nq2zUzj30qD-1nCbb1s:b28l7pw) ([raw file](https://github.com/cockroachdb/cockroach/blob/0baf22a03d5f55e2611701bc723e3e0b713ab051/pkg/kv/bulk/sst_batcher_test.go#L297)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Was this meant to be a part of this commit?
</blockquote></details>

Yes - this was a simplification since it now returns the RangeInfo directly. 
___
*[`pkg/kv/kvclient/rangecache/range_cache_test.go` line 514 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118329#-Npzzu_X1HjT1bKeHxsg:-Nq3-UAnEZzwNv5Mc99V:b-o6ac55) ([raw file](https://github.com/cockroachdb/cockroach/blob/0baf22a03d5f55e2611701bc723e3e0b713ab051/pkg/kv/kvclient/rangecache/range_cache_test.go#L514)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: technically these don't belong in this commit.
</blockquote></details>

They became required because RangeInfo doesn't support `==`. I'd have to restructure things a little to pull these out.
___
*[`pkg/kv/kvclient/rangecache/range_cache_test.go` line 1078 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118329#-Nq--UPD0-0E21FB25Yg:-Nq30Udt7yAomzPDXL5L:b9tg3r2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e364719525b53dba62f00a9156486d6dd54f73ff/pkg/kv/kvclient/rangecache/range_cache_test.go#L1078)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Given this is a RLocked method, we shouldn't call it without locking the mutex. Maybe consider creating a private version of `getCached` that wrapps around `getCachedRLocked`? Or, something local to this test.
</blockquote></details>

This test was already mixing locked and unlocked methods. I added a `TODO` for now, but didn't address in this commit.
___
*[`pkg/kv/kvclient/rangecache/range_cache_test.go` line 1156 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/118329#-Nq-_yBI2Nj_CDJ41Ls7:-Nq3i5-i5NwWCD3pHehf:b-zjri2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a14eb1da8e77d29cfa5c4cee964007a367aa25b0/pkg/kv/kvclient/rangecache/range_cache_test.go#L1156)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: technically unrelated to this commit.
</blockquote></details>

Yes slightly unrelated, but due to the way that we are now returning a pointer in the RangeInfo

**Comment by andrewbaptist** [comment]
bors r=arulajmani

**Pull request merged**
