### PR TITLE
release-2.1: client: restore txn.mu acquisition in OrigTimestamp et al.

### PR DESCRIPTION
**Pull request by benesch**
Backport 1/1 commits from #28907.

/cc @cockroachdb/release

---

This locking was removed in 69fa9f7cf, but I can't see how the resulting
code could be safe. Updates to txn.mu.sender can occur concurrently with
Txn.OrigTimestamp, Txn.CommitTimestamp, and Txn.CommitTimestampFixed, as
any concurrently-executing request that receives a
TransactionAbortedError will install a new sender.

It is arguably a usage error to be calling Txn.SetSystemConfigTrigger or
Txn.DisablePipelining in parallel with a request on the transaction, so
it would probably be safe not to acquire txn.mu in those methods, but
why take the risk?

Fix #28907.

Release note: None

### CODE REVIEW

**Comment by andreimatei** [comment]
LGTM

**Comment by benesch** [comment]
Ok, this is updated with the fix from #28907 to avoid deadlock.

**Comment by andreimatei** [comment]
LGTM

**Comment by benesch** [comment]
bors r=andreimatei

**Pull request merged**
