### PR TITLE
types: remove no longer used version gate

### LINKED ISSUE #77234: execgen: large dependency tree causes lots of recompilation under bazel
**Describe the problem**

Bazel builds can some times be slower than corresponding make builds for the same files changed. I tried the following experiment:
1. `make buildshort` and `dev build short` first, on a clean checkout (to priming both caches). 
2. Applied this random (buggy) diff to one of our base go packages:
```diff
$ git diff
diff --git i/pkg/roachpb/api.go w/pkg/roachpb/api.go
index f4d0b4c8aa..5b42b71539 100644
--- i/pkg/roachpb/api.go
+++ w/pkg/roachpb/api.go
@@ -143,7 +143,7 @@ func IsTransactional(args Request) bool {
 // IsLocking returns true if the request acquires locks when used within
 // a transaction.
 func IsLocking(args Request) bool {
-       return (args.flags() & isLocking) != 0
+       return (isLocking) != 0
 }
```
3. Re-run `make buildshort` and `dev build short`, timing each run:
```
$ time make buildshort
[...]
________________________________________________________
Executed in   70.72 secs    fish           external
   usr time  174.42 secs   40.00 micros  174.42 secs
   sys time   24.85 secs  537.00 micros   24.85 secs

$ dev build short -- --profile=experiment.tar.gz
[...]
INFO: Elapsed time: 97.947s, Critical Path: 91.80s
INFO: 312 processes: 23 remote cache hit, 1 internal, 288 darwin-sandbox.
INFO: Build completed successfully, 312 total actions
```

When looking at the bazel profile (chrome://tracing), I observed that we re-compiled execgen, which forced recompilation of all package targets that depended on execgen output. How come make doesn’t go and rebuild execgen + re-run execgen + recompile all dependants? Looking at our Makefile, we only re-compile `bin/execgen` when [proto files change](https://github.com/cockroachdb/cockroach/blob/bfe8164448ee78c76381be3d6a5a5b3eda9a4fbb/Makefile#L1763). And we don't (re-)generate `.eg.go` files unless explicitly running `make generate`. In short: we've not fully specified execgen dependencies in Make and things are faster because of it. Bazel builds by contrast are fully specified and will re-compile + re-gen execgen output when any of execgen's go dependencies are updated. It's more "correct" but slower because of it.

**To Reproduce**

See above. To see the dependency chain between execgen and roachpb:
```
$  bazel query "allpaths(//pkg/sql/colexec/execgen/cmd/execgen, //pkg/roachpb)"
```

To see the full set of dependencies execgen has (any of which, if changed, would cause slower builds than Make):
```
$ bazel query "deps(//pkg/sql/colexec/execgen/cmd/execgen)" --output package | grep -v '^@' | grep -v '^build/bazelutil'
```

**Expected behavior**

I'm only filing this issue to later point people to for one possible reason for the observed slowdown. We should revisit transitive dependencies execgen has given its position in our build system -- any trim down would drastically help.

Epic CRDB-8036

Jira issue: CRDB-13494

### PR DESCRIPTION
**Pull request by yuzefovich**
This is done to break the dependency of `sql/types` on `roachpb` (which
is a part of the effort to clean up the dependencies of `execgen`). This
commit brings the dependencies of `execgen` to a much more reasonable
set.

Although there is an ask in place to not remove this code even if it's
not used at the moment (so that we have the necessary infra in place
if/when the need arises), in order to keep the functionality we would
need to pull out `roachpb.Version` out of `roachpb`, and I don't want
to embark on that since we're in stability period.

Fixes: #77234.

Release note: None

Release justification: low risk change to clean up the dependencies.

### CODE REVIEW

**Comment by yuzefovich** [comment]
Sorry, the last commit breaks the bazel build, edited above.

**Comment by rickystewart** [comment]
Yeah, that change was necessary but not sufficient. I am able to build `cockroach` with all of the following changes:

```
diff --git a/pkg/roachpb/BUILD.bazel b/pkg/roachpb/BUILD.bazel
index 192965a550..76bcf880e7 100644
--- a/pkg/roachpb/BUILD.bazel
+++ b/pkg/roachpb/BUILD.bazel
@@ -177,6 +177,7 @@ go_proto_library(
     proto = ":roachpb_proto",
     visibility = ["//visibility:public"],
     deps = [
+        "//pkg/keysbase",
         "//pkg/kv/kvserver/concurrency/lock",
         "//pkg/kv/kvserver/readsummary/rspb",
         "//pkg/settings",
diff --git a/pkg/sql/alter_tenant.go b/pkg/sql/alter_tenant.go
index 57d0f85fa7..4fd7d6be4b 100644
--- a/pkg/sql/alter_tenant.go
+++ b/pkg/sql/alter_tenant.go
@@ -14,7 +14,7 @@ import (
 	"context"
 	"strings"
 
-	"github.com/cockroachdb/cockroach/pkg/roachpb"
+	"github.com/cockroachdb/cockroach/pkg/keysbase"
 	"github.com/cockroachdb/cockroach/pkg/settings"
 	"github.com/cockroachdb/cockroach/pkg/settings/cluster"
 	"github.com/cockroachdb/cockroach/pkg/sql/pgwire/pgcode"
@@ -28,7 +28,7 @@ import (
 // ALTER TENANT ... SET CLUSTER SETTING statement.
 type alterTenantSetClusterSettingNode struct {
 	name      string
-	tenantID  roachpb.TenantID
+	tenantID  keysbase.TenantID
 	tenantAll bool
 	st        *cluster.Settings
 	setting   settings.NonMaskedSetting
diff --git a/pkg/sql/parser/BUILD.bazel b/pkg/sql/parser/BUILD.bazel
index 37c4db40da..3d88e76bcc 100644
--- a/pkg/sql/parser/BUILD.bazel
+++ b/pkg/sql/parser/BUILD.bazel
@@ -22,7 +22,7 @@ go_library(
     deps = [
         "//pkg/docs",
         "//pkg/geo/geopb",  # keep
-        "//pkg/roachpb",  # keep
+        "//pkg/keysbase",  # keep
         "//pkg/security",  # keep
         "//pkg/sql/lexbase",
         "//pkg/sql/pgwire/pgcode",
diff --git a/pkg/sql/parser/sql.y b/pkg/sql/parser/sql.y
index 9a3433b213..5f44cc7689 100644
--- a/pkg/sql/parser/sql.y
+++ b/pkg/sql/parser/sql.y
@@ -30,7 +30,7 @@ import (
     "go/constant"
 
     "github.com/cockroachdb/cockroach/pkg/geo/geopb"
-    "github.com/cockroachdb/cockroach/pkg/roachpb"
+    "github.com/cockroachdb/cockroach/pkg/keysbase"
     "github.com/cockroachdb/cockroach/pkg/security"
     "github.com/cockroachdb/cockroach/pkg/sql/lexbase"
     "github.com/cockroachdb/cockroach/pkg/sql/privilege"
@@ -4967,7 +4967,7 @@ alter_tenant_csetting_stmt:
     $$.val = &tree.AlterTenantSetClusterSetting{
       Name: strings.Join($7.strs(), "."),
       Value: $9.expr(),
-      TenantID: roachpb.MakeTenantID(tenID),
+      TenantID: keysbase.MakeTenantID(tenID),
     }
   }
 | ALTER TENANT ALL SET CLUSTER SETTING var_name to_or_eq var_value
@@ -4987,7 +4987,7 @@ alter_tenant_csetting_stmt:
     $$.val = &tree.AlterTenantSetClusterSetting{
       Name: strings.Join($7.strs(), "."),
       Value: tree.DefaultVal{},
-      TenantID: roachpb.MakeTenantID(tenID),
+      TenantID: keysbase.MakeTenantID(tenID),
     }
   }
 | ALTER TENANT ALL RESET CLUSTER SETTING var_name
@@ -5728,7 +5728,7 @@ show_csettings_stmt:
     if tenID == 0 {
       return setErr(sqllex, errors.New("invalid tenant ID"))
     }
-    $$.val = &tree.ShowClusterSetting{Name: strings.Join($4.strs(), "."), TenantID: roachpb.MakeTenantID(tenID)}
+    $$.val = &tree.ShowClusterSetting{Name: strings.Join($4.strs(), "."), TenantID: keysbase.MakeTenantID(tenID)}
   }
 | SHOW ALL CLUSTER SETTINGS FOR TENANT iconst64
   {
@@ -5736,7 +5736,7 @@ show_csettings_stmt:
     if tenID == 0 {
       return setErr(sqllex, errors.New("invalid tenant ID"))
     }
-    $$.val = &tree.ShowClusterSettingList{All: true, TenantID: roachpb.MakeTenantID(tenID)}
+    $$.val = &tree.ShowClusterSettingList{All: true, TenantID: keysbase.MakeTenantID(tenID)}
   }
 | SHOW CLUSTER SETTINGS FOR TENANT iconst64
   {
@@ -5744,7 +5744,7 @@ show_csettings_stmt:
     if tenID == 0 {
       return setErr(sqllex, errors.New("invalid tenant ID"))
     }
-    $$.val = &tree.ShowClusterSettingList{TenantID: roachpb.MakeTenantID(tenID)}
+    $$.val = &tree.ShowClusterSettingList{TenantID: keysbase.MakeTenantID(tenID)}
   }
 | SHOW PUBLIC CLUSTER SETTINGS FOR TENANT iconst64
   {
@@ -5752,7 +5752,7 @@ show_csettings_stmt:
     if tenID == 0 {
       return setErr(sqllex, errors.New("invalid tenant ID"))
     }
-    $$.val = &tree.ShowClusterSettingList{TenantID: roachpb.MakeTenantID(tenID)}
+    $$.val = &tree.ShowClusterSettingList{TenantID: keysbase.MakeTenantID(tenID)}
   }
 | SHOW PUBLIC CLUSTER error // SHOW HELP: SHOW CLUSTER SETTING
 
@@ -6750,7 +6750,7 @@ targets:
     if tenID == 0 {
       return setErr(sqllex, errors.New("invalid tenant ID"))
     }
-    $$.val = tree.TargetList{Tenant: roachpb.MakeTenantID(tenID)}
+    $$.val = tree.TargetList{Tenant: keysbase.MakeTenantID(tenID)}
   }
 | DATABASE name_list
   {
diff --git a/pkg/sql/sem/tree/alter_tenant.go b/pkg/sql/sem/tree/alter_tenant.go
index 1ec4485d32..c18f011772 100644
--- a/pkg/sql/sem/tree/alter_tenant.go
+++ b/pkg/sql/sem/tree/alter_tenant.go
@@ -13,7 +13,7 @@ package tree
 import (
 	"fmt"
 
-	"github.com/cockroachdb/cockroach/pkg/roachpb"
+	"github.com/cockroachdb/cockroach/pkg/keysbase"
 )
 
 // AlterTenantSetClusterSetting represents an ALTER TENANT
@@ -21,7 +21,7 @@ import (
 type AlterTenantSetClusterSetting struct {
 	Name      string
 	Value     Expr
-	TenantID  roachpb.TenantID
+	TenantID  keysbase.TenantID
 	TenantAll bool
 }
 
diff --git a/pkg/sql/sem/tree/set.go b/pkg/sql/sem/tree/set.go
index b045ba2b5c..bdcf57e77b 100644
--- a/pkg/sql/sem/tree/set.go
+++ b/pkg/sql/sem/tree/set.go
@@ -19,7 +19,7 @@
 
 package tree
 
-import "github.com/cockroachdb/cockroach/pkg/roachpb"
+import "github.com/cockroachdb/cockroach/pkg/keysbase"
 
 // SetVar represents a SET or RESET statement.
 type SetVar struct {
@@ -69,7 +69,7 @@ func (node *SetVar) Format(ctx *FmtCtx) {
 type SetClusterSetting struct {
 	Name      string
 	Value     Expr
-	TenantID  roachpb.TenantID
+	TenantID  keysbase.TenantID
 	TenantAll bool
 }
 
diff --git a/pkg/sql/sem/tree/show.go b/pkg/sql/sem/tree/show.go
index 1832d799df..3079c5b93b 100644
--- a/pkg/sql/sem/tree/show.go
+++ b/pkg/sql/sem/tree/show.go
@@ -22,7 +22,7 @@ package tree
 import (
 	"fmt"
 
-	"github.com/cockroachdb/cockroach/pkg/roachpb"
+	"github.com/cockroachdb/cockroach/pkg/keysbase"
 	"github.com/cockroachdb/cockroach/pkg/sql/lexbase"
 )
 
@@ -44,7 +44,7 @@ func (node *ShowVar) Format(ctx *FmtCtx) {
 // ShowClusterSetting represents a SHOW CLUSTER SETTING statement.
 type ShowClusterSetting struct {
 	Name     string
-	TenantID roachpb.TenantID
+	TenantID keysbase.TenantID
 }
 
 // Format implements the NodeFormatter interface.
@@ -65,7 +65,7 @@ func (node *ShowClusterSetting) Format(ctx *FmtCtx) {
 type ShowClusterSettingList struct {
 	// All indicates whether to include non-public settings in the output.
 	All      bool
-	TenantID roachpb.TenantID
+	TenantID keysbase.TenantID
 }
 
 // Format implements the NodeFormatter interface.

```

**Comment by rickystewart** [comment]
After you apply that change you may still have to `make generate` or something to pass CI btw, I haven't checked.

**Comment by yuzefovich** [comment]
Thanks Ricky!

**Comment by yuzefovich** [comment]
In the end, the move of `roachpb.TenantID` out of `roachpb` package turned out to be unnecessary - not sure why I thought I needed to do that yesterday. With these four commits the dependency list of `execgen` is as [above](https://github.com/cockroachdb/cockroach/pull/77260#issuecomment-1056233255). All of the commits seem simple enough, so I think we'll be able to merge them during the stability period.

This PR is in a draft mode for the moment in order to not ping many aliases based on the first commit.

**Review by irfansharif — APPROVED** [review]
> there is an ask in place to not remove this code even if it's
not used at the moment (so that we have the necessary infra in place
if/when the need arises)

Could always resurrect it from git history. Last commit LGTM.

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
