### PR TITLE
kvserver: properly close `Engine` snapshot on snapshot error

### PR DESCRIPTION
**Pull request by erikgrinaker**
Since f1cf743757, we would leak an `Engine` snapshot if Raft snapshot
setup failed.

Release note: None

### CODE REVIEW

**Review by jbowens — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84581#-:-N7GvZFw51ybREJetxPV:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aliher1911)

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84581)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aliher1911, @erikgrinaker, and @jbowens)

___
*[`pkg/kv/kvserver/store_snapshot.go` line 1198 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84581#-N7Gx5L48vZIaBKGp0ui:-N7Gx5L48vZIaBKGp0uj:b-amfq1e) ([raw file](https://github.com/cockroachdb/cockroach/blob/872856353bb86d1d132eadc9ca4f2bc8fb79d218/pkg/kv/kvserver/store_snapshot.go#L1198)):*
> ```Go
> 		// Close() is not idempotent, and will be done by outgoingSnap.Close() if
> 		// the snapshot was successfully created.
> 		engSnapshot.Close()
> ```

should we make `Close` idempotent? It seems like it'd be a lot easier to use correctly.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84581)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aliher1911 and @jbowens)

___
*[`pkg/kv/kvserver/store_snapshot.go` line 1198 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84581#-N7Gx5L48vZIaBKGp0ui:-N7Gyq056Wj_b6vkKjoI:bwgim20) ([raw file](https://github.com/cockroachdb/cockroach/blob/872856353bb86d1d132eadc9ca4f2bc8fb79d218/pkg/kv/kvserver/store_snapshot.go#L1198)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

should we make `Close` idempotent? It seems like it'd be a lot easier to use correctly.
</blockquote></details>

Yeah, I generally prefer `Close()` to be idempotent. But I think it usually isn't throughout `storage`, so we should probably make it idempotent everywhere to avoid a footgun.

**Comment by erikgrinaker** [comment]
bors r=jbowens

**Pull request merged**
