### PR TITLE
engine/metamorphic: Split generation and execution of metamorphic tests

### PR DESCRIPTION
**Pull request by itsbilal**
This change splits mvccOp the struct into mvccOp the interface (for
concrete operation runners), and opGenerator struct instances that
generate those mvccOp concrete types for each operation. The generators
are tasked with updating manager state to track open instances, as
well as generating well-formed mvccOps, while mvccOp instances
are tasked with just executing an operation and returning an
output string.

This refactor makes the code easier to understand but increases
its size. This change would also allow for further simplifications,
such as having mvccOp print and parse its arguments the way it makes
sense for that operation specifically, instead of being bound to the
simpler constraints of the test runner.

Release note: None.

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
This is a good improvement, but I think there is more to be done as bits of generation and execution are still merged together. For example, each of the managers has fields that are used for generation and separate fields that are used for execution. Other additional high-level comments below. Let's work through those first, and then I'll do a more detailed pass.

On the plus side, I very much like the concrete `mvccOp` implementations and that you eliminated the use of `interface{}`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45251#-:-M0YUBR8-FjGqkSruVZW:byq1ftt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/metamorphic/generator.go, line 166 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45251#-M0YGfld4Kngw42vfdTH:-M0YGfld4Kngw42vfdTI:b5npeq8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba8444f738bc5fd4064e94fa5853bb6828d0dba4/pkg/storage/engine/metamorphic/generator.go#L166)):*
> ```Go
> 		operandReadWriter,
> 		operandTransaction,
> 	}
> ```

This can be:

```
closingOrder := []operandManager{
  m.iterManager,
  m.rwManager,
  m.txnManager,
}
```

No need for the level of indirection using `operandType`.
___
*[pkg/storage/engine/metamorphic/generator.go, line 291 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45251#-M0YH4IACZsKNY6EAZPK:-M0YH4IACZsKNY6EAZPL:bibfziu) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba8444f738bc5fd4064e94fa5853bb6828d0dba4/pkg/storage/engine/metamorphic/generator.go#L291)):*
> ```Go
> 			name:           opGenerator.name,
> 			op:             opGenerator.generate(m.ctx, m, argStrings...),
> 			args:           argStrings,
> ```

This feels odd to me. You've already passed the args to `op`. I see you have a `TODO` about this. I think adding `op.String()` which formats the op name and args makes sense.
___
*[pkg/storage/engine/metamorphic/generator.go, line 297 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45251#-M0YHFRQ4w02MovQoGKS:-M0YHFRQ4w02MovQoGKT:bljez7g) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba8444f738bc5fd4064e94fa5853bb6828d0dba4/pkg/storage/engine/metamorphic/generator.go#L297)):*
> ```Go
> 	}
> 
> 	for _, op := range m.ops {
> ```

This structure makes a copy of `op` by value. It is a good habit to do:

```
for i := range m.ops {
  op := &m.ops[i]
  ...
}
```

This is only necessary if you're iterating over structs that are "large-ish".
___
*[pkg/storage/engine/metamorphic/operands.go, line 305 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45251#-M0YIKb47-MWWLH2iixt:-M0YIKb47-MWWLH2iixu:b-w3luvy) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba8444f738bc5fd4064e94fa5853bb6828d0dba4/pkg/storage/engine/metamorphic/operands.go#L305)):*
> ```Go
> }
> 
> func (t *txnManager) parse(input txnID) *roachpb.Transaction {
> ```

It is strange that `parse` doesn't actually do any parsing. I feel like there are still seem interwoven abstractions here. 
___
*[pkg/storage/engine/metamorphic/operations.go, line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45251#-M0YTPn4E1WMuaaWrh_9:-M0YTPn4E1WMuaaWrh_A:b-qi1ovf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba8444f738bc5fd4064e94fa5853bb6828d0dba4/pkg/storage/engine/metamorphic/operations.go#L65)):*
> ```Go
> 	name string
> 	// Function to call to generate the operation runner.
> 	generate func(ctx context.Context, m *metaTestRunner, args ...string) mvccOp
> ```

Is there a reason a `metaTestRunner` is being passed to the `generate` function? I see that you're embedding `*metaTestRunner` in each of the `mvccOp` implementations, but that could be fixed by passing that as a parameter. This might also be related to `metaTestRunner` containing the various "managers", but shouldn't that be untangled?
___
*[pkg/storage/engine/metamorphic/operations.go, line 375 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45251#-M0YJ6uf9F-PfP7drTfR:-M0YJ6uf9F-PfP7drTfS:b-sva7zk) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba8444f738bc5fd4064e94fa5853bb6828d0dba4/pkg/storage/engine/metamorphic/operations.go#L375)):*
> ```Go
> func (t txnOpenOp) run(ctx context.Context) string {
> 	txn := t.m.txnManager.open()
> 	if t.id != "" && txn.Name != string(t.id) {
> ```

Rather than requiring the generated transaction have the expected name, I think you should model the IDs as slots. The op generator gave this transaction id X. `txnManager` should expose a routine to get the txn at that slot, which would returning nil. The `txnOpenOp` could then create the txn and set the newly created txn in the `txnManager` slot for `id`. The way this looks in the pebble metamorphic test is:

```
	b := t.db.NewBatch()
	t.setBatch(o.batchID, b)
```

**Review by itsbilal — COMMENTED** [review]
I made most of the changes you suggested. Managers are explicitly a generation-only entity now; they're not used at all in execution anymore.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45251#-:-M0ekIvZ-Q9RBd-LqeP8:bio2rpm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @petermattis and @sumeerbhola)

___
*[pkg/storage/engine/metamorphic/generator.go, line 166 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45251#-M0YGfld4Kngw42vfdTH:-M0eki45BHpuLGR4u_q3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba8444f738bc5fd4064e94fa5853bb6828d0dba4/pkg/storage/engine/metamorphic/generator.go#L166)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This can be:

```
closingOrder := []operandManager{
  m.iterManager,
  m.rwManager,
  m.txnManager,
}
```

No need for the level of indirection using `operandType`.
</blockquote></details>

Done.
___
*[pkg/storage/engine/metamorphic/generator.go, line 291 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45251#-M0YH4IACZsKNY6EAZPK:-M0ekj_x1cw67jieSxDh:b-3v4puj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba8444f738bc5fd4064e94fa5853bb6828d0dba4/pkg/storage/engine/metamorphic/generator.go#L291)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This feels odd to me. You've already passed the args to `op`. I see you have a `TODO` about this. I think adding `op.String()` which formats the op name and args makes sense.
</blockquote></details>

Yeah. The reason why I left it as a TODO is because it's not much of a gain for a bit more effort; the current `opGenerator`s already deal with taking a string and turning it into an `mvccOp`, so you can just hold onto the original string and print that out instead. Plus, that guarantees the output will always be parsable again; if I implement `op.String()`, it'd have to ensure it's always parsable on future runs.
___
*[pkg/storage/engine/metamorphic/generator.go, line 297 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45251#-M0YHFRQ4w02MovQoGKS:-M0elB5q1qNcXiDsGjPo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba8444f738bc5fd4064e94fa5853bb6828d0dba4/pkg/storage/engine/metamorphic/generator.go#L297)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This structure makes a copy of `op` by value. It is a good habit to do:

```
for i := range m.ops {
  op := &m.ops[i]
  ...
}
```

This is only necessary if you're iterating over structs that are "large-ish".
</blockquote></details>

Done.
___
*[pkg/storage/engine/metamorphic/operands.go, line 305 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45251#-M0YIKb47-MWWLH2iixt:-M0elBx_AzpinK4Y399Q:b-hq66cb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba8444f738bc5fd4064e94fa5853bb6828d0dba4/pkg/storage/engine/metamorphic/operands.go#L305)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

It is strange that `parse` doesn't actually do any parsing. I feel like there are still seem interwoven abstractions here. 
</blockquote></details>

Done. No method is called `parse` anymore unless it explicitly does parsing.
___
*[pkg/storage/engine/metamorphic/operations.go, line 65 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45251#-M0YTPn4E1WMuaaWrh_9:-M0elF-60mPYUDmByYoJ:b-izi52f) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba8444f738bc5fd4064e94fa5853bb6828d0dba4/pkg/storage/engine/metamorphic/operations.go#L65)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Is there a reason a `metaTestRunner` is being passed to the `generate` function? I see that you're embedding `*metaTestRunner` in each of the `mvccOp` implementations, but that could be fixed by passing that as a parameter. This might also be related to `metaTestRunner` containing the various "managers", but shouldn't that be untangled?
</blockquote></details>

That's basically it. The managers have been untangled now for execution, but they're still necessary for generation so they're useful to have in here. And while they're here, I just found it cleaner to embed the same metaTestRunner reference into the concrete op structs for execution. If you think passing them to the run() call is more helpful, I could do that too.
___
*[pkg/storage/engine/metamorphic/operations.go, line 375 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45251#-M0YJ6uf9F-PfP7drTfR:-M0elam1B9X3DpYwapFW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba8444f738bc5fd4064e94fa5853bb6828d0dba4/pkg/storage/engine/metamorphic/operations.go#L375)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Rather than requiring the generated transaction have the expected name, I think you should model the IDs as slots. The op generator gave this transaction id X. `txnManager` should expose a routine to get the txn at that slot, which would returning nil. The `txnOpenOp` could then create the txn and set the newly created txn in the `txnManager` slot for `id`. The way this looks in the pebble metamorphic test is:

```
	b := t.db.NewBatch()
	t.setBatch(o.batchID, b)
```
</blockquote></details>

Done.

**Review by petermattis — APPROVED** [review]
:lgtm:

I wonder if you should `s/manager/generator/g` now that managers are solely concerned with generation.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45251#-:-M0sTQW35gJbJ4pzN7nl:b-oa1l2n)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal and @sumeerbhola)

___
*[pkg/storage/engine/metamorphic/generator.go, line 291 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45251#-M0YH4IACZsKNY6EAZPK:-M0sQTlr1YeCw8j9lky_:b-ct0wff) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba8444f738bc5fd4064e94fa5853bb6828d0dba4/pkg/storage/engine/metamorphic/generator.go#L291)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Yeah. The reason why I left it as a TODO is because it's not much of a gain for a bit more effort; the current `opGenerator`s already deal with taking a string and turning it into an `mvccOp`, so you can just hold onto the original string and print that out instead. Plus, that guarantees the output will always be parsable again; if I implement `op.String()`, it'd have to ensure it's always parsable on future runs.
</blockquote></details>

Hmm. Ok. I'm going to continue to think about this, but this is good for now.

**Comment by itsbilal** [comment]
Thanks for the review! I did the manager -> generator rename.  Will merge on green CI.

**Pull request merged**
