### PR TITLE
rpc: always consider the localserver healthy

### PR DESCRIPTION
**Pull request by petermattis**
See #17177

### CODE REVIEW

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17196#-:-KppjmoblYxbpzwJQhz6:bnfp4nl)*

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/rpc/context.go, line 369 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17196#-KppkJXQhzhooBOpUraN:-KppkJXQhzhooBOpUraO:b-pi4n38) ([raw file](https://github.com/cockroachdb/cockroach/blob/071c49df94f3086de0f816e0cd98925a76e6944b/pkg/rpc/context.go#L369)):*
> ```Go
> // to prioritize healthy nodes over unhealthy ones.
> func (ctx *Context) ConnHealth(remoteAddr string) error {
> 	if remoteAddr == ctx.Addr {
> ```

can this use `ctx.GetLocalInternalServerForAddr(remoteAddr) != nil` instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17196#-:-KppkSmnHqolzSzgWcXy:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/rpc/context.go, line 369 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17196#-KppkJXQhzhooBOpUraN:-Kppl3Mk28_zjll3jbfA:bxhsy03) ([raw file](https://github.com/cockroachdb/cockroach/blob/071c49df94f3086de0f816e0cd98925a76e6944b/pkg/rpc/context.go#L369)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

can this use `ctx.GetLocalInternalServerForAddr(remoteAddr) != nil` instead?
</blockquote></details>

Yeah. Not sure it matters. I'm going to leave as-is unless something requires me to re-run CI.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17196)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/rpc/context.go, line 369 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17196#-KppkJXQhzhooBOpUraN:-KpplV3r33JWOODBOgLT:b-i3leia) ([raw file](https://github.com/cockroachdb/cockroach/blob/071c49df94f3086de0f816e0cd98925a76e6944b/pkg/rpc/context.go#L369)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Yeah. Not sure it matters. I'm going to leave as-is unless something requires me to re-run CI.
</blockquote></details>

It might not matter now, but I've been pretty careful about not duplicating this logic - all things being equal, I'd prefer we not break the abstraction here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17196)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/rpc/context.go, line 369 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17196#-KppkJXQhzhooBOpUraN:-KppmMXc5xrZWOUNd_iI:b-82ddbr) ([raw file](https://github.com/cockroachdb/cockroach/blob/071c49df94f3086de0f816e0cd98925a76e6944b/pkg/rpc/context.go#L369)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

It might not matter now, but I've been pretty careful about not duplicating this logic - all things being equal, I'd prefer we not break the abstraction here.
</blockquote></details>

Heh, my merge finger crossed your comment in the ether. Apologies.

I'll have to disagree about the abstraction breakage here. This is internal code to identify the local server. One line of code seems as good as another. Though perhaps not the line you would have written, I'm not seeing a strong reason to change it. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17196)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/rpc/context.go, line 369 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17196#-KppkJXQhzhooBOpUraN:-KppyBtduyLSxMdOKPkU:b-kfrke7) ([raw file](https://github.com/cockroachdb/cockroach/blob/071c49df94f3086de0f816e0cd98925a76e6944b/pkg/rpc/context.go#L369)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Heh, my merge finger crossed your comment in the ether. Apologies.

I'll have to disagree about the abstraction breakage here. This is internal code to identify the local server. One line of code seems as good as another. Though perhaps not the line you would have written, I'm not seeing a strong reason to change it. 
</blockquote></details>

The precedent is the only reason; there's already a call to `GetLocalInternalServerForAddr` used internally (introduced in #16612 as you pointed out in #17177) - there are no internal comparisons to `ctx.Addr` other than the one in `GetLocalInternalServerForAddr`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17196)*

**Pull request merged**
