### PR TITLE
sql/schemachanger: Implement comment on in declarative sc

### PR DESCRIPTION
**Pull request by chengxiong-ruan**
Split out from #78025

This commit implements COMMENT ON with the new schema changer
framework.

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
Let's add some logic tests in the `new_schema_changer` logictest file or a new test file that has the same config. Then, let's try adding some pernicious cases like adding a comment and then dropping the thing it references in the same transaction. Also, let's do a sequence of adding and dropping comments in the same transaction. 

> Reviewed 30 of 30 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80459#-:-N0auAac7fJw1tgMbOlo:b-6t15j5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @chengxiong-ruan and @fqazi)

___
*[`pkg/sql/schemachanger/scbuild/builder_state.go` line 718 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80459#-N0at0Tj5Av7X4WGJPt-:-N0at0Tj5Av7X4WGJPt0:bu7699e) ([raw file](https://github.com/cockroachdb/cockroach/blob/3155daa5213b25e84650e02055ad95258b86c7f5/pkg/sql/schemachanger/scbuild/builder_state.go#L718)):*
> ```Go
> 		}
> 	})
> 	scpb.ForEachColumn(c.ers, func(current scpb.Status, target scpb.TargetStatus, e *scpb.Column) {
> ```

one day, these are going to hurt. We'll probably want to leverage rel indexes here. It's easy to see how this could become quadratic



_Code quote:_
```Go
	scpb.ForEachColumnName(c.ers, func(status scpb.Status, _ scpb.TargetStatus, e *scpb.ColumnName) {
		if e.TableID == relationID && tree.Name(e.Name) == columnName {
			columnID = e.ColumnID
		}
	})
	scpb.ForEachColumn(c.ers, func(current scpb.Status, target scpb.TargetStatus, e *scpb.Column) {
		if e.TableID == relationID && e.ColumnID == columnID {
			pgAttrNum = e.PgAttributeNum
		}
	})
```
___
*[`pkg/sql/schemachanger/scbuild/dependencies.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80459#-N0atrilExAbWwjiv4mb:-N0atrilExAbWwjiv4mc:bc6l541) ([raw file](https://github.com/cockroachdb/cockroach/blob/3155daa5213b25e84650e02055ad95258b86c7f5/pkg/sql/schemachanger/scbuild/dependencies.go#L106)):*
> ```Go
> 	// MayResolveIndex looks up an index using a naked index name with database
> 	// and schema prefix. Resolved prefix, index and the owner table are returned.
> 	MayResolveIndex(ctx context.Context, indexName tree.Name, prefix tree.ObjectNamePrefix) (catalog.ResolvedObjectPrefix, catalog.TableDescriptor, catalog.Index)
> ```

can you use more words to talk about the structure of this name? Namely, this seems to support the @ syntax no? 
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go` line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80459#-N0awpoaAzo6Irjlh7pT:-N0awpoaAzo6Irjlh7pU:b1lipme) ([raw file](https://github.com/cockroachdb/cockroach/blob/3155daa5213b25e84650e02055ad95258b86c7f5/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go#L47)):*
> ```Go
> var supportedStatements = map[reflect.Type]supportedStatement{
> 	// Alter table will have commands individually whitelisted via the
> 	// supportedAlterTableStatements list, so wwe will consider it fully supported
> ```

drive-by: wwe wwe
___
*[`pkg/sql/schemachanger/scdeps/build_deps.go` line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80459#-N0av5CD3C4tof3LL6nd:-N0av5CD3C4tof3LL6ne:b-d6mk8y) ([raw file](https://github.com/cockroachdb/cockroach/blob/3155daa5213b25e84650e02055ad95258b86c7f5/pkg/sql/schemachanger/scdeps/build_deps.go#L142)):*
> ```Go
> 	ctx context.Context, indexName tree.Name, prefix tree.ObjectNamePrefix,
> ) (catalog.ResolvedObjectPrefix, catalog.TableDescriptor, catalog.Index) {
> 	found, resolvedPrefix, err := resolver.ResolveObjectNamePrefix(
> ```

I don't think this universally works, consider:

Setup:
```sql
CREATE DATABASE db;
USE db;
```
```sql
CREATE SCHEMA sc1;
CREATE SCHEMA sc2;
SET search_path = sc1, sc2;
CREATE TABLE sc2.t (i INT PRIMARY KEY, j INT);
CREATE INDEX idx ON sc2.t(j);
```

Things which should work and should apply to sc2.t@idx:
```sql
COMMENT ON INDEX idx IS 'a';
```
```sql
COMMENT ON INDEX t@idx IS 'a';
```
I think the first one is broken today in cockroach but the second one works.

In general, I think this method has the wrong types. I think it should use `tree.TableIndexName` as the parameter. Can you write some logic tests to cover the above cases?
___
*[`pkg/sql/schemachanger/scdeps/helper.go` line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80459#-N0awN5o23IpEC5JIAhl:-N0awN5p1JasUzFO78Zx:blgksjo) ([raw file](https://github.com/cockroachdb/cockroach/blob/3155daa5213b25e84650e02055ad95258b86c7f5/pkg/sql/schemachanger/scdeps/helper.go#L27)):*
> ```Go
> // index. dsNames and dsIDs are parallel slices containing table names and ids,
> // they must have same length.
> func FindTableContainsIndex(
> ```

this belongs elsewhere. I think a reasonable place would be the `resolver` package, then in scdeps, just deal with error translation. 

In general, a principle should be that if you're writing business logic in `scdeps`, you're doing something wrong. Ideally we could factor out some of the existing logic from the `sql` package and leverage it. 
___
*[`pkg/sql/schemachanger/scplan/internal/opgen/opgen_schema_comment.go` line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80459#-N0au_89891_EkM2scAO:-N0au_89891_EkM2scAP:bjj133y) ([raw file](https://github.com/cockroachdb/cockroach/blob/3155daa5213b25e84650e02055ad95258b86c7f5/pkg/sql/schemachanger/scplan/internal/opgen/opgen_schema_comment.go#L29)):*
> ```Go
> 					}
> 				}),
> 				// TODO(Chengxiong): add schema event log (need to add proto for schema
> ```

can you file an issue for this?
___
*[`pkg/sql/schemachanger/scplan/testdata/comment_on` line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80459#-N0arMrY8uy06BUgyqgb:-N0arMrZ3erDO626vw9M:bi24nr9) ([raw file](https://github.com/cockroachdb/cockroach/blob/3155daa5213b25e84650e02055ad95258b86c7f5/pkg/sql/schemachanger/scplan/testdata/comment_on#L150)):*
> ```
>           tableId: 107
>       Statement: COMMENT ON CONSTRAINT ‹t1_amount_gt_10› ON ‹db1›.‹sc1›.‹t1› IS 'this is
>         a rule'
> ```

this line wrap is suspect. How does it happen?



_Code quote:_
```

        a rule'
```

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80459)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, and @fqazi)

___
*[`pkg/sql/schemachanger/scdeps/build_deps.go` line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80459#-N0av5CD3C4tof3LL6nd:-N0b8t5s2TH6CQGfQE0r:b-c06izj) ([raw file](https://github.com/cockroachdb/cockroach/blob/3155daa5213b25e84650e02055ad95258b86c7f5/pkg/sql/schemachanger/scdeps/build_deps.go#L142)):*
> I don't think this universally works, consider:

Yeah, this is weird, I only tested it with one schema on the search path. So looks like we should iterate through all schema on the search path. I'm glad I'm learning something here. I guess it's a broader issue we should fix for crdb to be more compatible with postgres. Do you know if there's an issue tracking this?

> In general, I think this method has the wrong types. I think it should use tree.TableIndexName as the parameter.

My thought was that this function only handle cases where a table name is not given and we try to find an index and a table has this index given whatever prefix we have, this for cases like: `db_name.sc_name.index_name`, `db_name.index_name`, `sc_name.index_name`, so that we can resolve table elements with the table we found, and then get index elements from there.

 For cases where a table name is given, like `tble_name@index` we may just resolve the table first and find an index elements from it.

Does this make sense to you? I assume you're asking having this function handle both categories.
___
*[`pkg/sql/schemachanger/scdeps/helper.go` line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80459#-N0awN5o23IpEC5JIAhl:-N0bBd9S21gVhosQUhZo:bu7g079) ([raw file](https://github.com/cockroachdb/cockroach/blob/3155daa5213b25e84650e02055ad95258b86c7f5/pkg/sql/schemachanger/scdeps/helper.go#L27)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

this belongs elsewhere. I think a reasonable place would be the `resolver` package, then in scdeps, just deal with error translation. 

In general, a principle should be that if you're writing business logic in `scdeps`, you're doing something wrong. Ideally we could factor out some of the existing logic from the `sql` package and leverage it. 
</blockquote></details>

Yes, indeed. Will move it to a more common spot.
___
*[`pkg/sql/schemachanger/scplan/internal/opgen/opgen_schema_comment.go` line 29 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80459#-N0au_89891_EkM2scAO:-N0bCUpOBMNylfHYs9ch:b-en5p9t) ([raw file](https://github.com/cockroachdb/cockroach/blob/3155daa5213b25e84650e02055ad95258b86c7f5/pkg/sql/schemachanger/scplan/internal/opgen/opgen_schema_comment.go#L29)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

can you file an issue for this?
</blockquote></details>

yes, #80576
___
*[`pkg/sql/schemachanger/scplan/testdata/comment_on` line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80459#-N0arMrY8uy06BUgyqgb:-N0bCXej9Gb5U1vq9fXy:b-27gir0) ([raw file](https://github.com/cockroachdb/cockroach/blob/3155daa5213b25e84650e02055ad95258b86c7f5/pkg/sql/schemachanger/scplan/testdata/comment_on#L150)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

this line wrap is suspect. How does it happen?
</blockquote></details>

interesting, you absolutely have good eyes! Will figure this out.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80459)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, and @fqazi)

___
*[`pkg/sql/schemachanger/scdeps/build_deps.go` line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80459#-N0av5CD3C4tof3LL6nd:-N0bEw3Y2m5iAK05-RUJ:b-1gxazb) ([raw file](https://github.com/cockroachdb/cockroach/blob/3155daa5213b25e84650e02055ad95258b86c7f5/pkg/sql/schemachanger/scdeps/build_deps.go#L142)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

> I don't think this universally works, consider:

Yeah, this is weird, I only tested it with one schema on the search path. So looks like we should iterate through all schema on the search path. I'm glad I'm learning something here. I guess it's a broader issue we should fix for crdb to be more compatible with postgres. Do you know if there's an issue tracking this?

> In general, I think this method has the wrong types. I think it should use tree.TableIndexName as the parameter.

My thought was that this function only handle cases where a table name is not given and we try to find an index and a table has this index given whatever prefix we have, this for cases like: `db_name.sc_name.index_name`, `db_name.index_name`, `sc_name.index_name`, so that we can resolve table elements with the table we found, and then get index elements from there.

 For cases where a table name is given, like `tble_name@index` we may just resolve the table first and find an index elements from it.

Does this make sense to you? I assume you're asking having this function handle both categories.
</blockquote></details>

I'm not sure. It feels like `tree.TableIndexName` can store all of the cases. It might be poorly named though. Perhaps we should have some structure which is a combination of the more general `ObjectName` and the index specification. Can you imagine a scenario where we'd ever want to resolve an index and not support all of these syntaxes?

**Comment by chengxiong-ruan** [comment]
*[`pkg/sql/schemachanger/scdeps/build_deps.go` line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80459#-N0av5CD3C4tof3LL6nd:-N0bJXw-0js0OAvcfGoX:b-6qjuez) ([raw file](https://github.com/cockroachdb/cockroach/blob/3155daa5213b25e84650e02055ad95258b86c7f5/pkg/sql/schemachanger/scdeps/build_deps.go#L142)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I'm not sure. It feels like `tree.TableIndexName` can store all of the cases. It might be poorly named though. Perhaps we should have some structure which is a combination of the more general `ObjectName` and the index specification. Can you imagine a scenario where we'd ever want to resolve an index and not support all of these syntaxes?
</blockquote></details>

Ha I'm terrible at naming as well. I do want to support all of the cases and I suppose you're talking about something like this I did in pr (I just copied the code to quote..) , I can push it to a lower layer though: 
```
func CommentOnIndex(b BuildCtx, n *tree.CommentOnIndex) {
	var tableID catid.DescID
	var tableElements ElementResultSet
	if len(n.Index.Table.ObjectName) > 0 {
		tableElements = b.ResolveTable(n.Index.Table.ToUnresolvedObjectName(), commentResolveParams)
	} else {
		tableElements = b.ResolveTableWithIndexBestEffort(n.Index.Table.ObjectNamePrefix, tree.Name(n.Index.Index), commentResolveParams)
	}
```

**Review by chengxiong-ruan — COMMENTED** [review]
Good callouts, I'll add them in a separate pr in which the `fullysupported` will be turned on and this implementation will be guarded behind a version gate.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80459#-:-N1HQmT88u-UMIvTubft:b3enlwc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

___
*[`pkg/sql/schemachanger/scbuild/builder_state.go` line 718 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80459#-N0at0Tj5Av7X4WGJPt-:-N0fwT5c8iCO0pVbR721:b68cmmq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3155daa5213b25e84650e02055ad95258b86c7f5/pkg/sql/schemachanger/scbuild/builder_state.go#L718)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

one day, these are going to hurt. We'll probably want to leverage rel indexes here. It's easy to see how this could become quadratic
</blockquote></details>

yeah, I've decided to make the `ColumnComment` in memory to use column ID to identify it, but use `PgAttributeNum` for reading/updating/deleting. I kinda shoot myself on the feet by using PgAttributeNum as an identifier. With that said, all these logic checking PgAttributeNum is gone.
___
*[`pkg/sql/schemachanger/scbuild/dependencies.go` line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80459#-N0atrilExAbWwjiv4mb:-N1HRA1n9oC_so52XiMc:b-9r9ixm) ([raw file](https://github.com/cockroachdb/cockroach/blob/3155daa5213b25e84650e02055ad95258b86c7f5/pkg/sql/schemachanger/scbuild/dependencies.go#L106)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

can you use more words to talk about the structure of this name? Namely, this seems to support the @ syntax no? 
</blockquote></details>

this is done after the refactoring.

**Comment by chengxiong-ruan** [comment]
*[`pkg/sql/schemachanger/scplan/testdata/comment_on` line 150 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/80459#-N0arMrY8uy06BUgyqgb:-N1HRVdi-ITBnA8zg87j:bo5eebs) ([raw file](https://github.com/cockroachdb/cockroach/blob/3155daa5213b25e84650e02055ad95258b86c7f5/pkg/sql/schemachanger/scplan/testdata/comment_on#L150)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

interesting, you absolutely have good eyes! Will figure this out.
</blockquote></details>

as discussed before, this is a yaml bug: https://github.com/go-yaml/yaml/issues/166

**Review by fqazi — CHANGES_REQUESTED** [review]
Great work, just minor comments, they're not functional, just clean up.

> Reviewed 32 of 32 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80459#-:-N1Jqfvi6QhlEsgDdDG_:b9beu3o)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @chengxiong-ruan)

___
*[`pkg/sql/alter_table.go` line 1383 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80459#-N1JniuG6XIffbo37XZt:-N1JniuHCfytfqSixfca:b-8aiuk6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b205359a502197b1a8b8e995807af25d6605f842/pkg/sql/alter_table.go#L1383)):*
> ```Go
> 		keys.ColumnCommentType,
> 		tableID,
> 		pgAttributeNum)
> ```

As a separate issue do we want a migration to clean up orphan entries? 
___
*[`pkg/sql/catalog/tabledesc/table.go` line 313 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80459#-N1Jo0-wBQ9kb40sQ0ow:-N1Jo0-wBQ9kb40sQ0ox:b-imx6za) ([raw file](https://github.com/cockroachdb/cockroach/blob/b205359a502197b1a8b8e995807af25d6605f842/pkg/sql/catalog/tabledesc/table.go#L313)):*
> ```Go
> 		}
> 	}
> 	return descpb.ConstraintDetail{}, nil
> ```

Tempted to say we should return a pointer and use nil as the canary value, just feels safer.
___
*[`pkg/sql/schemachanger/scbuild/builder_state.go` line 777 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80459#-N1JpMRB4JY63udcFhe0:-N1JpMRB4JY63udcFhe1:b-p17lrk) ([raw file](https://github.com/cockroachdb/cockroach/blob/b205359a502197b1a8b8e995807af25d6605f842/pkg/sql/schemachanger/scbuild/builder_state.go#L777)):*
> ```Go
> 
> 	return c.ers.Filter(func(_ scpb.Status, _ scpb.TargetStatus, e scpb.Element) bool {
> 		idI, _ := screl.Schema.GetAttribute(screl.ConstraintID, e)
> ```

Can we just simplify this down to a filter? On the TableID and ConstraintId attributes? Then check if the element set is empty after only?
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/comment_on.go` line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80459#-N1JptYw41JZdRE_Ag-4:-N1JptYw41JZdRE_Ag-5:bfnf4lv) ([raw file](https://github.com/cockroachdb/cockroach/blob/b205359a502197b1a8b8e995807af25d6605f842/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/comment_on.go#L81)):*
> ```Go
> 
> 	if n.Comment == nil {
> 		tableElements.ForEachElementStatus(func(_ scpb.Status, _ scpb.TargetStatus, e scpb.Element) {
> ```

Replace this with FindTableComment
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/comment_on.go` line 91 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80459#-N1JpvtR6uDlekdUvrJG:-N1JpvtR6uDlekdUvrJH:bhfatro) ([raw file](https://github.com/cockroachdb/cockroach/blob/b205359a502197b1a8b8e995807af25d6605f842/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/comment_on.go#L91)):*
> ```Go
> 			Comment: *n.Comment,
> 		}
> 		tableElements.ForEachElementStatus(func(_ scpb.Status, _ scpb.TargetStatus, e scpb.Element) {
> ```

Replace this with FindTable (similar in other spots where there is only one possibility)
___
*[`pkg/sql/logictest/testdata/logic_test/new_schema_changer` line 430 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80459#-N1JqKDT-M8GLfcCZYy7:-N1JqKDUDJ7SDrYnkJZA:bl4y2vm) ([raw file](https://github.com/cockroachdb/cockroach/blob/b205359a502197b1a8b8e995807af25d6605f842/pkg/sql/logictest/testdata/logic_test/new_schema_changer#L430)):*
> ```
> DROP TABLE foo
> 
> subtest multi_table
> ```

Wait, were these tests nuked or am I reading the diff wrong?

**Review by chengxiong-ruan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80459)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @fqazi)

___
*[`pkg/sql/alter_table.go` line 1383 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80459#-N1JniuG6XIffbo37XZt:-N1JriL-BGU8JmlR6wIl:b4g8wvf) ([raw file](https://github.com/cockroachdb/cockroach/blob/b205359a502197b1a8b8e995807af25d6605f842/pkg/sql/alter_table.go#L1383)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

As a separate issue do we want a migration to clean up orphan entries? 
</blockquote></details>

Yeah, good call. I created #81053, but I think the odds that a column is commented on, then altered, then dropped is pretty pretty low haha.
___
*[`pkg/sql/catalog/tabledesc/table.go` line 313 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80459#-N1Jo0-wBQ9kb40sQ0ow:-N1JtwP7-Xu1CnKTZPSL:b8fltf1) ([raw file](https://github.com/cockroachdb/cockroach/blob/b205359a502197b1a8b8e995807af25d6605f842/pkg/sql/catalog/tabledesc/table.go#L313)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Tempted to say we should return a pointer and use nil as the canary value, just feels safer.
</blockquote></details>

sound good, fixed
___
*[`pkg/sql/schemachanger/scbuild/builder_state.go` line 777 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80459#-N1JpMRB4JY63udcFhe0:-N1Jzq9t4KW-1RcocDxa:bnhl6do) ([raw file](https://github.com/cockroachdb/cockroach/blob/b205359a502197b1a8b8e995807af25d6605f842/pkg/sql/schemachanger/scbuild/builder_state.go#L777)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Can we just simplify this down to a filter? On the TableID and ConstraintId attributes? Then check if the element set is empty after only?
</blockquote></details>

Hmm, not sure I understand here. The main task here is actually to find the constraintID by constraint/index name :)
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/comment_on.go` line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80459#-N1JptYw41JZdRE_Ag-4:-N1Jw2hx4MFF9QrhkJcI:b4kckvv) ([raw file](https://github.com/cockroachdb/cockroach/blob/b205359a502197b1a8b8e995807af25d6605f842/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/comment_on.go#L81)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Replace this with FindTableComment
</blockquote></details>

nice, didn't know this existed
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/comment_on.go` line 91 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80459#-N1JpvtR6uDlekdUvrJG:-N1Jw59z3Cv8cvPw5dHn:b-r18wir) ([raw file](https://github.com/cockroachdb/cockroach/blob/b205359a502197b1a8b8e995807af25d6605f842/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/comment_on.go#L91)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Replace this with FindTable (similar in other spots where there is only one possibility)
</blockquote></details>

done, thanks!
___
*[`pkg/sql/logictest/testdata/logic_test/new_schema_changer` line 430 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80459#-N1JqKDT-M8GLfcCZYy7:-N1JxMdV5QX4tRoNh5MQ:b-by83f7) ([raw file](https://github.com/cockroachdb/cockroach/blob/b205359a502197b1a8b8e995807af25d6605f842/pkg/sql/logictest/testdata/logic_test/new_schema_changer#L430)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Wait, were these tests nuked or am I reading the diff wrong?
</blockquote></details>

looks like `--rewrite` with subtest name in test filter did it... reverted it back.

**Review by fqazi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80459)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, and @fqazi)

___
*[`pkg/sql/schemachanger/scbuild/builder_state.go` line 777 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/80459#-N1JpMRB4JY63udcFhe0:-N1K1VpdCT91Sx4RS9iJ:b-1wgnpy) ([raw file](https://github.com/cockroachdb/cockroach/blob/b205359a502197b1a8b8e995807af25d6605f842/pkg/sql/schemachanger/scbuild/builder_state.go#L777)):*
<details><summary><i>Previously, chengxiong-ruan (Chengxiong Ruan) wrote…</i></summary><blockquote>

Hmm, not sure I understand here. The main task here is actually to find the constraintID by constraint/index name :)
</blockquote></details>

Sorry, this won't work. At best we can filter based on name, but then indexes don't keep constraint IDs with names :(.

**Review by fqazi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/80459#-:-N1K6VzF8L3QtRTxo0Cs:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @chengxiong-ruan, and @fqazi)

**Comment by chengxiong-ruan** [comment]
TFTR!
bors r+

**Pull request merged**
