### PR TITLE
allocator/allocsim: Reduce lease thrashing

### PR DESCRIPTION
**Pull request by a-robinson**
The first two commits are just improving the test tooling, the last reduces our tendency to transfer leases when using load-based lease rebalancing. I assume the most/only controversial thing here will be changing `MinLeaseTransferStatsDuration` from 1 minute to 5, which is meant to avoid making decisions with incomplete information, especially since the magnitude of request counts kind of gets taken into account in decisions. 5 minutes doesn't seem like too long to me, but I could be missing important situations when it is.

Results looked great on all the configs I tried, although they also looked pretty good before. The biggest behavioral change by far was in using multi-level localities for the allocsim configs, which took us from transferring leases in a loop forever to pretty much perfect behavior. As explained in more detail in the first commit message, the severity of the difference makes me think that for 1.1 we may want to be tracking the inter-locality latency even for localities other than ours.

There's also another change that I'll send out separately to make latency cause less aggressiveness at lower latencies and more at higher latencies. I'm pretty confident that we want the former, but not quite so sure about the latter.

### CODE REVIEW

**Comment by BramGruneir** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/cmd/allocsim/main.go, line 63 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15321#-Ki_T98VQDJaN2sFvxKw:-Ki_T98VQDJaN2sFvxKx:b-shhj39) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0b6b5ba8c0e0cefc7d6993f0819e5857cd43b9/pkg/cmd/allocsim/main.go#L63)):*
> ```Go
> type Locality struct {
> 	Name              string `json:"Name"`
> 	LocalityStr				string `json:"LocalityStr"`
> ```

The weird spacing is due to reviewable?  Or did the auto format mess up?

---

*[pkg/storage/allocator.go, line 57 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15321#-Ki_U4sTd2ctmEddMAvL:-Ki_U4sTd2ctmEddMAvM:btlbhvw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab17b07352bd8f2483ab7918ee8dc2e9f4c03ded/pkg/storage/allocator.go#L57)):*
> ```Go
> 	// making decisions based on them.
> 	// Made configurable for the sake of testing.
> 	MinLeaseTransferStatsDuration = 5 * time.Minute
> ```

Is this worth turning into a tunable system wide value?  Or an env variable for more testing?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15321#-:-Ki_UM8k0hMdwKS2tx7Q:bnfp4nl)*

**Comment by a-robinson** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/cmd/allocsim/main.go, line 63 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15321#-Ki_T98VQDJaN2sFvxKw:-Ki_Vev1cBdKMm8Zu0NT:bbz54i) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0b6b5ba8c0e0cefc7d6993f0819e5857cd43b9/pkg/cmd/allocsim/main.go#L63)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

The weird spacing is due to reviewable?  Or did the auto format mess up?
</blockquote></details>

Hm, apparently vim stopped auto-formatting on save for me. I'll have to check out why that broke.

---

*[pkg/storage/allocator.go, line 57 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15321#-Ki_U4sTd2ctmEddMAvL:-Ki_Vmj2gzgVRldjJqQH:bgl0zbp) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab17b07352bd8f2483ab7918ee8dc2e9f4c03ded/pkg/storage/allocator.go#L57)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Is this worth turning into a tunable system wide value?  Or an env variable for more testing?
</blockquote></details>

I can't think of when a user would ever want to set this or why we'd need it to be an env var. I don't know that this meets the bar for tune-ability.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15321)*

**Comment by BramGruneir** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/allocator.go, line 57 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15321#-Ki_U4sTd2ctmEddMAvL:-Ki_WPh8pImjKLdNbfcu:b2h8ra1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab17b07352bd8f2483ab7918ee8dc2e9f4c03ded/pkg/storage/allocator.go#L57)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

I can't think of when a user would ever want to set this or why we'd need it to be an env var. I don't know that this meets the bar for tune-ability.
</blockquote></details>

So by setting this to 5mins, it means that if there's a new range based on a split, it will take a least 5 mins before load base lease rebalancing kicks in right?  Yeah, on second thought, best to just leave it be.  How much more information is missing after one minute that spurred on this change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15321)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/cmd/allocsim/main.go, line 63 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15321#-Ki_T98VQDJaN2sFvxKw:-Ki_hpXqaIvnUSmZILY5:bp8a05h) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0b6b5ba8c0e0cefc7d6993f0819e5857cd43b9/pkg/cmd/allocsim/main.go#L63)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Hm, apparently vim stopped auto-formatting on save for me. I'll have to check out why that broke.
</blockquote></details>

You fixed this formatting in the wrong commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15321)*

**Comment by a-robinson** [comment]
Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/cmd/allocsim/main.go, line 63 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15321#-Ki_T98VQDJaN2sFvxKw:-Ki_kvT15JwGtKa1e-aD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ee0b6b5ba8c0e0cefc7d6993f0819e5857cd43b9/pkg/cmd/allocsim/main.go#L63)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

You fixed this formatting in the wrong commit.
</blockquote></details>

Done.

---

*[pkg/storage/allocator.go, line 57 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15321#-Ki_U4sTd2ctmEddMAvL:-Ki_kvujtMkri6azyA0a:b-c1mb2r) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab17b07352bd8f2483ab7918ee8dc2e9f4c03ded/pkg/storage/allocator.go#L57)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

So by setting this to 5mins, it means that if there's a new range based on a split, it will take a least 5 mins before load base lease rebalancing kicks in right?  Yeah, on second thought, best to just leave it be.  How much more information is missing after one minute that spurred on this change?
</blockquote></details>

Here's one example situation in which it matters:

* Node 1 holds the lease. Node 2 is the next best candidate
* The leases are imbalanced such that node 2 holds more leases, but it's getting more of the requests for most of them.
* At 1 minute in, node 2 has received 50 requests to node 1's zero. However, the resulting 50-to-1 ratio isn't quite enough to motivate a transfer
* At 5 minutes in, node 2 has received 250 requests to node 1's zero. The 250-to-1 ratio is enough to motivate a transfer.
* After node 2 has had the lease for 1 minute, it has a 50-1 ratio, which is back down to low enough to justify balancing the lease back to node 1.

There's some weighted decay of the request counts so the 250 number is an overestimate, but the general idea holds.

However, what I think that example is really arguing for is to consider the average (+ weighted decay) rate of requests to each locality rather than the total count. That'd be a slightly bigger change, and I'd have to figure out the little bit of math involved, but should be more stable. What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15321)*

**Comment by BramGruneir** [comment]
Reviewed 3 of 3 files at r5.
Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/allocator.go, line 57 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15321#-Ki_U4sTd2ctmEddMAvL:-Ki_xAGjXobV_-wHvd9B:b-xtme1q) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab17b07352bd8f2483ab7918ee8dc2e9f4c03ded/pkg/storage/allocator.go#L57)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Here's one example situation in which it matters:

* Node 1 holds the lease. Node 2 is the next best candidate
* The leases are imbalanced such that node 2 holds more leases, but it's getting more of the requests for most of them.
* At 1 minute in, node 2 has received 50 requests to node 1's zero. However, the resulting 50-to-1 ratio isn't quite enough to motivate a transfer
* At 5 minutes in, node 2 has received 250 requests to node 1's zero. The 250-to-1 ratio is enough to motivate a transfer.
* After node 2 has had the lease for 1 minute, it has a 50-1 ratio, which is back down to low enough to justify balancing the lease back to node 1.

There's some weighted decay of the request counts so the 250 number is an overestimate, but the general idea holds.

However, what I think that example is really arguing for is to consider the average (+ weighted decay) rate of requests to each locality rather than the total count. That'd be a slightly bigger change, and I'd have to figure out the little bit of math involved, but should be more stable. What do you think?
</blockquote></details>

So in your scenario, how does extending this to 5 mins change the behaviour besides delaying the decision from happening sometimes between 1 min and 5 mins to after 5 mins?   
 Isn't the 4th point, where things are settling down going to happen with or without this change to 5 mins?  Or am I reading this wrong?

I think you're right about the move to average + weighted decay, but that might be tough to get in before 1.0, just due to the amount of testing required.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15321)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r4, 1 of 1 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/allocator.go, line 57 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15321#-Ki_U4sTd2ctmEddMAvL:-Kia04tWC-9ZAmYUpCAK:b-ix4um6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab17b07352bd8f2483ab7918ee8dc2e9f4c03ded/pkg/storage/allocator.go#L57)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

So in your scenario, how does extending this to 5 mins change the behaviour besides delaying the decision from happening sometimes between 1 min and 5 mins to after 5 mins?   
 Isn't the 4th point, where things are settling down going to happen with or without this change to 5 mins?  Or am I reading this wrong?

I think you're right about the move to average + weighted decay, but that might be tough to get in before 1.0, just due to the amount of testing required.
</blockquote></details>

The change to 5 mins is to make it much larger than `rpc.avgLatencyMeasurementAge * rpc.defaultHeartbeatInterval`, right? We should probably export those constants and define this value in terms of them. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15321#-:-Kia0TP3Aa9BFGEsFhNZ:bnfp4nl)*

**Comment by a-robinson** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/allocator.go, line 57 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15321#-Ki_U4sTd2ctmEddMAvL:-KifVxfAEsyTRofIzizw:b20enxd) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab17b07352bd8f2483ab7918ee8dc2e9f4c03ded/pkg/storage/allocator.go#L57)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

The change to 5 mins is to make it much larger than `rpc.avgLatencyMeasurementAge * rpc.defaultHeartbeatInterval`, right? We should probably export those constants and define this value in terms of them. 
</blockquote></details>

Actually, I primarily chose it to be no smaller than the window size used by `replicaStats`, but there is something to be said for waiting longer than `rpc.avgLatencyMeasurementAge * rpc.defaultHeartbeatInterval`. I've switched it to being defined in terms of that, but am willing to sit down and work out the math to switch to rates if we think it's worth the effort and short-term risk of getting something wrong in the switch. I know that switching from 1 to 5 minutes reduces thrashing, and am having trouble thinking of situations in which 1 minute lease transfers are particularly important.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15321)*

**Comment by bdarnell** [comment]
Reviewed 3 of 3 files at r8.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15321)*

**Comment by a-robinson** [comment]
Any final thoughts, @BramGruneir?

**Comment by BramGruneir** [comment]
Still LGTM

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/storage/allocator.go, line 57 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/15321#-Ki_U4sTd2ctmEddMAvL:-KifkNAIAuiMH8Jj8Oc3:bb73djm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab17b07352bd8f2483ab7918ee8dc2e9f4c03ded/pkg/storage/allocator.go#L57)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Actually, I primarily chose it to be no smaller than the window size used by `replicaStats`, but there is something to be said for waiting longer than `rpc.avgLatencyMeasurementAge * rpc.defaultHeartbeatInterval`. I've switched it to being defined in terms of that, but am willing to sit down and work out the math to switch to rates if we think it's worth the effort and short-term risk of getting something wrong in the switch. I know that switching from 1 to 5 minutes reduces thrashing, and am having trouble thinking of situations in which 1 minute lease transfers are particularly important.
</blockquote></details>

SGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15321#-:-KifkPi-Zvta_gGVH9a_:b-kwu2jz)*

**Comment by a-robinson** [comment]
Thanks!

**Pull request merged**
