### PR TITLE
storage: make queue timeouts controllable, snapshot sending queues dynamic

### PR DESCRIPTION
**Pull request by ajwerner**
In #42686 we made the raft snapshot queue timeout dynamic and based on the
size of the snapshot being sent. We also added an escape hatch to control
the timeout of processing of that queue. This change generalizes that
cluster setting to apply to all of the queues.

It so happens that the replicate queue and the merge queue also sometimes
need to send snapshots. This PR gives them similar treatment to the
raft snapshot queue.

The previous cluster setting was never released and is reserved so it does not
need a release note.

Release note: None

### CODE REVIEW

**Comment by ajwerner** [comment]
@knz this relates to bad behavior we observed in a cluster this week. I'd like to backport both this and #42686 to 19.1 and 19.2.

**Comment by ajwerner** [comment]
Flaked on https://github.com/cockroachdb/cockroach/issues/44789

**Review by knz — COMMENTED** [review]
Minor nit on terminology. Code LGTM otherwise.

What's our testing story around this code? I am surprised to see no test.

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44809#-:-M-QtMfH9_MiL-Bo3GWo:b84uvgb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[pkg/storage/merge_queue.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44809#-M-Qs0bsChd5VgMABrey:-M-Qs0bt0kahrrDNhycD:b-ttv35l) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1d39d0215cab10388d3d158c1c9a02b3cd1a9f9/pkg/storage/merge_queue.go#L106)):*
> ```Go
> 			// sometimes the merge queue needs to send multiple snapshots so perhaps
> 			// it would want even more time than the snapshot queue. That being said
> 			// this timeout give leeway for snapshots to be 10x slower than the
> ```

This sentence is either too long or ungrammatical, I don't understand it.
___
*[pkg/storage/queue.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44809#-M-QsABXAlryu3QiMw2F:-M-QsABY-lOxBwB5sYdf:b-lt8e8f) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1d39d0215cab10388d3d158c1c9a02b3cd1a9f9/pkg/storage/queue.go#L52)):*
> ```Go
> // queue will time out.
> var queueMinimumTimeout = settings.RegisterDurationSetting(
> 	// NB: this setting has a relatively awkward name because the linter does not
> ```

Neither `timeout_minimum` nor `minimum_timeout` are good names. The linter is trying to tell you something. :)

Your description says it - guaranteed latency budget (time allotment without a timeout): `kv.queue.process.guaranteed_latency_budget`.

(English semantics: generally the word "minimum" is not clear if you don't specify what it is the minimum _of_ - there needs to be multiple values to start with.)

**Review by ajwerner — COMMENTED** [review]
Thanks for making write the tests. It needed them. Added a second commit to ensure that our rate settings are always positive. We would have had divide by zero panics both in this code and in the code that used them if they were set to 0.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44809#-:-M-Rn-tL4vxOgvqrXuXS:br7rybi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/storage/merge_queue.go, line 106 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44809#-M-Qs0bsChd5VgMABrey:-M-RpAyo7tP0IbMQFcko:b-avdb4g) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1d39d0215cab10388d3d158c1c9a02b3cd1a9f9/pkg/storage/merge_queue.go#L106)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This sentence is either too long or ungrammatical, I don't understand it.
</blockquote></details>

I reworked this comment. 
___
*[pkg/storage/queue.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44809#-M-QsABXAlryu3QiMw2F:-M-RnCOo-jC6uEJ154sl:bx1b01y) ([raw file](https://github.com/cockroachdb/cockroach/blob/e1d39d0215cab10388d3d158c1c9a02b3cd1a9f9/pkg/storage/queue.go#L52)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Neither `timeout_minimum` nor `minimum_timeout` are good names. The linter is trying to tell you something. :)

Your description says it - guaranteed latency budget (time allotment without a timeout): `kv.queue.process.guaranteed_latency_budget`.

(English semantics: generally the word "minimum" is not clear if you don't specify what it is the minimum _of_ - there needs to be multiple values to start with.)
</blockquote></details>

See how you feel about this.

**Comment by ajwerner** [comment]
@knz friendly ping

**Review by knz — APPROVED** [review]
> Reviewed 2 of 9 files at r4, 7 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44809)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by ajwerner** [comment]
TFTR!

bors r=knz

**Pull request merged**
