### PR TITLE
orm: update asyncpg_blocklist

### LINKED ISSUE #76490: roachtest: asyncpg failed
roachtest.asyncpg [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4368530&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4368530&tab=artifacts#/asyncpg) on master @ [bbb473c8f304ac20fec51ff0a0d04e128383bcf6](https://github.com/cockroachdb/cockroach/commits/bbb473c8f304ac20fec51ff0a0d04e128383bcf6):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /artifacts/asyncpg/run_1
	orm_helpers.go:191,orm_helpers.go:117,asyncpg.go:130,asyncpg.go:141,test_runner.go:779: 
		Tests run on Cockroach v22.1.0-alpha.1-1226-gbbb473c8f3
		Tests run against asyncpg v0.24.0
		134 Total Tests Run
		126 tests passed
		8 tests failed
		34 tests skipped
		96 tests ignored
		0 tests passed unexpectedly
		8 tests failed unexpectedly
		0 tests expected failed but skipped
		0 tests expected failed but not run
		---
		--- FAIL: test_transaction.TestTransaction.test_transaction_interface_errors (unexpected)
		--- FAIL: test_transaction.TestTransaction.test_transaction_regular (unexpected)
		--- FAIL: test_transaction.TestTransaction.test_transaction_nested (unexpected)
		--- FAIL: test_timeout.TestTimeoutCoversPrepare.test_timeout_covers_prepare_01 (unexpected)
		--- FAIL: test_transaction.TestTransaction.test_nested_isolation_level (unexpected)
		--- FAIL: test_transaction.TestTransaction.test_transaction_within_manual_transaction (unexpected)
		--- FAIL: test_transaction.TestTransaction.test_isolation_level (unexpected)
		--- FAIL: test_timeout.TestTimeout.test_timeout_05 (unexpected)
		For a full summary look at the asyncpg artifacts 
		
		An updated blocklist (asyncpgBlocklist22_1) is available in the artifacts' asyncpg log
```
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
/cc @cockroachdb/sql-experience
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*asyncpg.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-13147

### PR DESCRIPTION
**Pull request by RichardJCai**
Release justification: ORM test only change

Release note: None

Fixes #76490

### CODE REVIEW

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77370)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[pkg/cmd/roachtest/tests/asyncpg_blocklist.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77370#-MxH3u3ZElAHmTw2km7e:-MxH3u3ZElAHmTw2km7f:b-8pmnhn) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6581f45197c1bc3ad16a7b80610b956e3f2cdcf/pkg/cmd/roachtest/tests/asyncpg_blocklist.go#L27)):*
> ```Go
> // in the test log.
> var asyncpgBlocklist22_1 = blocklist{
> 	"test_cursor.TestCursor.test_cursor_03": "unknown",
> ```

oh hm, i just noticed that these are apparently passing on 21.2. i think that means it's a regression. do you know the error message behind these?
___
*[pkg/cmd/roachtest/tests/asyncpg_blocklist.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77370#-MxH3iIcA3I3QFuhW43m:-MxH3iIcA3I3QFuhW43n:bg19vyh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6581f45197c1bc3ad16a7b80610b956e3f2cdcf/pkg/cmd/roachtest/tests/asyncpg_blocklist.go#L33)):*
> ```Go
> var asyncpgBlocklist21_2 = blocklist{}
> 
> var asyncpgIgnoreList22_1 = blocklist{
> ```

would you be willing to move these into the main blocklist? that way we will know if any start passing. (the ignore list is meant for flaky tests, not for tests that are expected to fail)

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77370)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/cmd/roachtest/tests/asyncpg_blocklist.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77370#-MxH3u3ZElAHmTw2km7e:-MxLVIi70m3tKVVaxhLi:bxx7hlm) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6581f45197c1bc3ad16a7b80610b956e3f2cdcf/pkg/cmd/roachtest/tests/asyncpg_blocklist.go#L27)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

oh hm, i just noticed that these are apparently passing on 21.2. i think that means it's a regression. do you know the error message behind these?
</blockquote></details>

Here's the error for `test_cursor_03`

```
Traceback (most recent call last):
  File "/mnt/data1/asyncpg/asyncpg/_testbase/__init__.py", line 92, in wrapper
    self.loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/mnt/data1/asyncpg/tests/test_cursor.py", line 142, in test_cursor_03
    async with self.con.transaction():
  File "/mnt/data1/asyncpg/asyncpg/transaction.py", line 62, in __aenter__
    await self.start()
  File "/mnt/data1/asyncpg/asyncpg/transaction.py", line 138, in start
    await self._connection.execute(query)
  File "/mnt/data1/asyncpg/asyncpg/connection.py", line 315, in execute
    return await self._protocol.query(query, timeout)
  File "asyncpg/protocol/protocol.pyx", line 338, in query
    return await waiter
asyncpg.exceptions._base.UnknownPostgresError: there is already a transaction in progress
```

And `test_pool_11`

```
ERROR: test_pool_11 (test_pool.TestPool)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/data1/asyncpg/asyncpg/_testbase/__init__.py", line 92, in wrapper
    self.loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/mnt/data1/asyncpg/tests/test_pool.py", line 210, in test_pool_11
    ps_cur = await ps.cursor()
  File "/mnt/data1/asyncpg/asyncpg/pool.py", line 959, in __aexit__
    await self.pool.release(con)
  File "/mnt/data1/asyncpg/asyncpg/pool.py", line 833, in release
    return await asyncio.shield(ch.release(timeout))
  File "/mnt/data1/asyncpg/asyncpg/pool.py", line 218, in release
    raise ex
  File "/mnt/data1/asyncpg/asyncpg/pool.py", line 208, in release
    await self._con.reset(timeout=budget)
  File "/mnt/data1/asyncpg/asyncpg/connection.py", line 1347, in reset
    await self.execute(reset_query, timeout=timeout)
  File "/mnt/data1/asyncpg/asyncpg/connection.py", line 315, in execute
    return await self._protocol.query(query, timeout)
  File "asyncpg/protocol/protocol.pyx", line 338, in query
    return await waiter
asyncpg.exceptions._base.UnknownPostgresError: there is no transaction in progress
```

Not helpful right now without digging in more but it seems like we do have a regression.

`test_cursor_02` and `test_cursor_04` were already failing before, interesting that `test_cursor_03` was okay before, what was the status of cursor support before this?
___
*[pkg/cmd/roachtest/tests/asyncpg_blocklist.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77370#-MxH3iIcA3I3QFuhW43m:-MxLVlFmE2CUjKviDAtT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6581f45197c1bc3ad16a7b80610b956e3f2cdcf/pkg/cmd/roachtest/tests/asyncpg_blocklist.go#L33)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

would you be willing to move these into the main blocklist? that way we will know if any start passing. (the ignore list is meant for flaky tests, not for tests that are expected to fail)
</blockquote></details>

Done.

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77370)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[pkg/cmd/roachtest/tests/asyncpg_blocklist.go, line 27 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77370#-MxH3u3ZElAHmTw2km7e:-MxeE_O_-Lw2JL-uzUdF:b-827jha) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6581f45197c1bc3ad16a7b80610b956e3f2cdcf/pkg/cmd/roachtest/tests/asyncpg_blocklist.go#L27)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Here's the error for `test_cursor_03`

```
Traceback (most recent call last):
  File "/mnt/data1/asyncpg/asyncpg/_testbase/__init__.py", line 92, in wrapper
    self.loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/mnt/data1/asyncpg/tests/test_cursor.py", line 142, in test_cursor_03
    async with self.con.transaction():
  File "/mnt/data1/asyncpg/asyncpg/transaction.py", line 62, in __aenter__
    await self.start()
  File "/mnt/data1/asyncpg/asyncpg/transaction.py", line 138, in start
    await self._connection.execute(query)
  File "/mnt/data1/asyncpg/asyncpg/connection.py", line 315, in execute
    return await self._protocol.query(query, timeout)
  File "asyncpg/protocol/protocol.pyx", line 338, in query
    return await waiter
asyncpg.exceptions._base.UnknownPostgresError: there is already a transaction in progress
```

And `test_pool_11`

```
ERROR: test_pool_11 (test_pool.TestPool)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/data1/asyncpg/asyncpg/_testbase/__init__.py", line 92, in wrapper
    self.loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/mnt/data1/asyncpg/tests/test_pool.py", line 210, in test_pool_11
    ps_cur = await ps.cursor()
  File "/mnt/data1/asyncpg/asyncpg/pool.py", line 959, in __aexit__
    await self.pool.release(con)
  File "/mnt/data1/asyncpg/asyncpg/pool.py", line 833, in release
    return await asyncio.shield(ch.release(timeout))
  File "/mnt/data1/asyncpg/asyncpg/pool.py", line 218, in release
    raise ex
  File "/mnt/data1/asyncpg/asyncpg/pool.py", line 208, in release
    await self._con.reset(timeout=budget)
  File "/mnt/data1/asyncpg/asyncpg/connection.py", line 1347, in reset
    await self.execute(reset_query, timeout=timeout)
  File "/mnt/data1/asyncpg/asyncpg/connection.py", line 315, in execute
    return await self._protocol.query(query, timeout)
  File "asyncpg/protocol/protocol.pyx", line 338, in query
    return await waiter
asyncpg.exceptions._base.UnknownPostgresError: there is no transaction in progress
```

Not helpful right now without digging in more but it seems like we do have a regression.

`test_cursor_02` and `test_cursor_04` were already failing before, interesting that `test_cursor_03` was okay before, what was the status of cursor support before this?
</blockquote></details>

"cursor" has a few different meanings. is this referring to `DECLARE cursor`? that was only added in v22.1 https://github.com/cockroachdb/cockroach/pull/74006
___
*[pkg/cmd/roachtest/tests/asyncpg_blocklist.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77370#-MxH3iIcA3I3QFuhW43m:-MxeEr1aEtd1P6VKK8nP:b-o0ymfv) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6581f45197c1bc3ad16a7b80610b956e3f2cdcf/pkg/cmd/roachtest/tests/asyncpg_blocklist.go#L33)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

sorry - i meant that all of these tests should be in `asyncpgBlocklist`, and nothing should be in `asyncpgIgnoreList`

**Review by RichardJCai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77370)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[pkg/cmd/roachtest/tests/asyncpg_blocklist.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77370#-MxH3iIcA3I3QFuhW43m:-MxjxDFe3DHsEEHfPi9M:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6581f45197c1bc3ad16a7b80610b956e3f2cdcf/pkg/cmd/roachtest/tests/asyncpg_blocklist.go#L33)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

sorry - i meant that all of these tests should be in `asyncpgBlocklist`, and nothing should be in `asyncpgIgnoreList`
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
lgtm!

i found that my change in https://github.com/cockroachdb/cockroach/pull/76834 actually fixes test_cursor_03 and test_pool_11.

i do want to merge that PR, so if you want, you could remove those two tests from the blocklist

**Pull request merged**
