### PR TITLE
opt: fix autocommit_nonmetamorphic

### PR DESCRIPTION
**Pull request by RaduBerinde**
Another instance of a test that was not updated because it didn't run
in the original CI or bors run.

Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
git bisect points to https://github.com/cockroachdb/cockroach/pull/58897
@irfansharif is it expected to get extra CPuts with that change?

**Comment by RaduBerinde** [comment]
Ah, I guess it's not extra operations, just the same operations that now show up twice in the trace? Seems like a bug? Still, we should get this in ASAP so we can deflake the test.

**Comment by irfansharif** [comment]
Hm, yea definitely not intentional. Now that tracing is always enabled, perhaps it's surfacing an underlying bug that results in doubly capturing the same traces. I'll investigate separately.

**Review by irfansharif — APPROVED** [review]

**Comment by adityamaru** [comment]
I'm not sure this fixed it, I'm still seeing the test flake (with the `expected` output being what was before this change)  - https://teamcity.cockroachdb.com/viewLog.html?buildId=2600096&buildTypeId=Cockroach_UnitTests

**Comment by pbardea** [comment]
@adityamaru I don't think that commit included this change.

**Comment by adityamaru** [comment]
oops, ignore me, sorry!

**Pull request merged**
