### PR TITLE
sql: update `EXPERIMENTAL_RELOCATE` to support relocation of non-voters

### PR DESCRIPTION
**Pull request by aayushshah15**
This PR contains 3 commits:

**sql: stop spuriously removing non-voters on `EXPERIMENTAL_RELOCATE`**

Previously, a call to `EXPERIMENTAL_RELOCATE..` (when relocating
replicas, not the lease) would incorrectly remove all non-voters on the
target range(s). This commit fixes the bug.

Release justification: bug fix
Release note: None

**sql, parser: add `EXPERIMENTAL_RELOCATE VOTERS` as alias of
`EXPERIMENTAL_RELOCATE`**

Release note (sql change): `EXPERIMENTAL_RELOCATE VOTERS` is now an
alias of `EXPERIMENTAL_RELOCATE` (_not_ `EXPERIMENTAL_RELOCATE LEASES`).

**sql, parser: add EXPERIMENTAL_RELOCATE NON_VOTERS**

This commit adds a new variant of the `EXPERIMENTAL_RELOCATE` statement
which enables relocation of non-voting replicas via SQL.

Release note (sql change): `EXPERIMENTAL_RELOCATE` now has a new
variant: `EXPERIMENTAL_RELOCATE NON_VOTERS` which allows users to
relocate non-voting replicas via SQL.

### CODE REVIEW

**Review by nvb — APPROVED** [review]
This all :lgtm:. Is your intention to backport this to the v21.1 release branch?

> Reviewed 1 of 1 files at r1, 5 of 5 files at r2, 15 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62696#-:-MWz1PhCEwv_Wgj9DjIM:b-g4j3bi)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15)

___
*[pkg/sql/relocate.go, line 138 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62696#-MWz-ZUMAii_IlhaSvQ8:-MWz-ZUMAii_IlhaSvQ9:bx1d8fq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e381225bd384f4193a860effe34321b8b43df3b1/pkg/sql/relocate.go#L138)):*
> ```Go
> 	} else {
> 		if err := params.p.ExecCfg().DB.AdminRelocateRange(
> 			params.ctx, rowKey, relocationTargets, rangeDesc.Replicas().NonVoters().ReplicationTargets(),
> ```

nit: consider pulling this into a variable like `existingNonVoters := ...` to make the intention more clear.

Same thing with `existingVoters` later on in this PR.
___
*[pkg/sql/parser/sql.y, line 1697 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62696#-MWz0Mj19lTjPdPj1ANO:-MWz0Mj19lTjPdPj1ANP:b-py5jjd) ([raw file](https://github.com/cockroachdb/cockroach/blob/450369662e900c2f91757051448f236a844c48d0/pkg/sql/parser/sql.y#L1697)):*
> ```Yacc
>     }
>   }
> | ALTER TABLE table_name relocate_kw VOTERS select_stmt
> ```

Should we add a `voters_kw` target that includes `VOTERS` or `| /* EMPTY */`, to avoid needing two targets here and below?
___
*[pkg/sql/sem/tree/split.go, line 89 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62696#-MWz0kUL0h884SNAw-hz:-MWz0kUL0h884SNAw-i-:b-6mi41m) ([raw file](https://github.com/cockroachdb/cockroach/blob/3cfe2a38044b9e0d47b09815658e8634e4f4bfda/pkg/sql/sem/tree/split.go#L89)):*
> ```Go
> 	}
> 	ctx.FormatNode(&node.TableOrIndex)
> 	ctx.WriteString(" EXPERIMENTAL_RELOCATE ")
> ```

nit: Should we keep this, since it's still common among all variants?

**Comment by aayushshah15** [comment]
> Is your intention to backport this to the v21.1 release branch?

Anecdotally speaking, `EXPERIMENTAL_RELOCATE` seems to have come in handy in a bunch of support escalations in order to, say, quickly move a bunch of replicas off of a node for various reasons. Since the blast radius of this change is fairly small (and it's an `experimental` statement to begin with), I was thinking it'd be nice to have it in 21.1.

Do you have any concerns? I'll defer to you for the final call.

**Comment by aayushshah15** [comment]
TFTR! 

bors r+

**Review by aayushshah15 — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62696#-:-MWzNZD3CT1mswZq8V_Y:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[pkg/sql/relocate.go, line 138 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62696#-MWz-ZUMAii_IlhaSvQ8:-MWz4y_S6JOcKYvZCUWL:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e381225bd384f4193a860effe34321b8b43df3b1/pkg/sql/relocate.go#L138)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: consider pulling this into a variable like `existingNonVoters := ...` to make the intention more clear.

Same thing with `existingVoters` later on in this PR.
</blockquote></details>

Done.
___
*[pkg/sql/parser/sql.y, line 1697 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62696#-MWz0Mj19lTjPdPj1ANO:-MWz5TNp1cEcv7pB-aHm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/450369662e900c2f91757051448f236a844c48d0/pkg/sql/parser/sql.y#L1697)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we add a `voters_kw` target that includes `VOTERS` or `| /* EMPTY */`, to avoid needing two targets here and below?
</blockquote></details>

Done.
___
*[pkg/sql/sem/tree/split.go, line 89 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/62696#-MWz0kUL0h884SNAw-hz:-MWz4xFH3a0al_7CYVT3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3cfe2a38044b9e0d47b09815658e8634e4f4bfda/pkg/sql/sem/tree/split.go#L89)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: Should we keep this, since it's still common among all variants?
</blockquote></details>

Done.

**Review by nvb — APPROVED** [review]
> Since the blast radius of this change is fairly small (and it's an experimental statement to begin with), I was thinking it'd be nice to have it in 21.1.

This all checks out for me, so I'm ok backporting it into the release. Thanks for getting it out so quickly.

> Reviewed 15 of 15 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62696#-:-MWzNnSf3N7xMoTYeMzU:b-sw6jkn)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15)

**Pull request merged**
