### PR TITLE
execbuilder: enforce_home_region should only apply to DML

### LINKED ISSUE #88789: opt: consider being less stringent with enforce_home_region on delegated statements
Consider the following interaction on a multi-region cluster:
```
root@localhost:26257/mr> SHOW REGIONS FROM CLUSTER;
    region    |      zones
--------------+------------------
  us-central1 | {us-central1-c}
  us-east4    | {us-east4-a}
  us-west1    | {us-west1-c}
(3 rows)


Time: 172ms total (execution 171ms / network 0ms)

root@localhost:26257/mr> SET enforce_home_region = true;
SET


Time: 0ms total (execution 0ms / network 0ms)

root@localhost:26257/mr> SHOW REGIONS FROM CLUSTER;     
ERROR: Query has no home region. Try adding a LIMIT clause.
SQLSTATE: XCHR2
root@localhost:26257/mr> SELECT * FROM [SHOW REGIONS FROM CLUSTER] LIMIT 10000;
    region    |      zones
--------------+------------------
  us-east4    | {us-east4-a}
  us-west1    | {us-west1-c}
  us-central1 | {us-central1-c}
(3 rows)


Time: 170ms total (execution 170ms / network 0ms)
```
Once we enable `enforce_home_region` variable, then delegated statements (like `SHOW REGIONS` and `SHOW TABLES`) result in errors. I believe this is the desired behavior since these statements under the hood issue queries against non-MR databases, but it might be a better UX to allow these statements to proceed.

Please feel free to close it if this doesn't make sense given that this is effectively my first exposure to multi region stuff.

Jira issue: CRDB-20011

### LINKED ISSUE #89875: Unable to run SHOW CREATE TABLE with enforce_home_region='true' set if the table is GLOBAL.
**Describe the problem**

I am unable to run a `SHOW CREATE TABLE` on a global table with `enforce_home_region` set. However, doing a SELECT from that table works fine without specifying a region.

**To Reproduce**

Create a table:
```
root@localhost:26257/db> CREATE TABLE public.users (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    username STRING NOT NULL,
    crdb_region db.public.crdb_internal_region NOT VISIBLE NOT NULL DEFAULT default_to_database_primary_region(gateway_region())::db.public.crdb_internal_region,
    CONSTRAINT users_pkey PRIMARY KEY (id ASC),
) LOCALITY GLOBAL;
```
Set `enforce_home_region` to true.
```
root@localhost:26257/db> SET enforce_home_region='true';
SET
Time: 0ms total (execution 0ms / network 0ms)
```

Run `SHOW CREATE users;` it fails with a weird message suggesting to add a LIMIT clause on a SHOW:
```
root@localhost:26257/db> SHOW CREATE users;
ERROR: Query has no home region. Try adding a LIMIT clause.
SQLSTATE: XCHR2
```

However doing a `SELECT * FROM users;` works fine.
```
root@localhost:26257/db> SELECT * FROM users;
  id | username
-----+-----------
(0 rows)


Time: 254ms total (execution 254ms / network 0ms)
```

**Expected behavior**
I would expect show create users to work.

**Environment:**
 - CockroachDB version v22.2.0-alpha.3-392-gf7f7466ffe
 - SHA: 1a3a94e3a1ce31b474addaa4bf76e2d13e577d19

Jira issue: CRDB-20475

### PR DESCRIPTION
**Pull request by msirek**
Fixes #89875
Fixes #88789

This fixes a problem where the enforce_home_region session flag might
cause non-DML statements to error out, such as SHOW CREATE, if those
statements utilize scans or joins of multiregion tables.

This also fixes issues with proper erroring out of mutation DML like
UPDATE AND DELETE. For example, the following previously did not error:
```
CREATE TABLE messages_rbr (
    account_id INT NOT NULL,
    message_id   UUID DEFAULT gen_random_uuid(),
    message    STRING NOT NULL,
    PRIMARY KEY (account_id),
    INDEX msg_idx(message)
)
LOCALITY REGIONAL BY ROW;

SET enforce_home_region = true;

DELETE FROM messages_rbr WHERE message = 'Hello World!'
ERROR: Query has no home region. Try adding a filter on messages_rbr.crdb_region and/or on key column (messages_rbr.account_id).
SQLSTATE: XCHR2
```

Release note (bug fix): This patch fixes an issue with the
enforce_home_region session setting which may cause SHOW CREATE TABLE or
other non-DML statements to error out if the optimizer plan for the
statement involves accessing a multiregion table.

### CODE REVIEW

**Comment by yuzefovich** [comment]
Does this also fix #88789?

**Comment by msirek** [comment]
> Does this also fix #88789?

Yes, thanks!

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90007#-:-NEbzkoC1MLihRX-47aF:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek and @yuzefovich)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90007#-NEbwGAc--IRQeQPH5n3):*
Can you give some more details?
___
*[`pkg/sql/region_util.go` line 2364 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90007#-NEbxor5DllrWdc2PNy2:-NEbxor5DllrWdc2PNy3:b-qttj58) ([raw file](https://github.com/cockroachdb/cockroach/blob/921ae5ffe19f90b40cd8a9a6f6b5771cfdc29ba4/pkg/sql/region_util.go#L2364)):*
> ```Go
> 
> // IsANSIDML is part of the eval.Planner interface.
> func (p *planner) IsANSIDML() bool {
> ```

nit: Consider changing this here and everywhere else to just `IsDML`. `IsANSIDML` seems overly verbose...
___
*[`pkg/sql/opt/exec/execbuilder/relational.go` line 1843 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90007#-NEbvhic3DvpzZCg1pjx:-NEbvhic3DvpzZCg1pjy:b-75ywm7) ([raw file](https://github.com/cockroachdb/cockroach/blob/921ae5ffe19f90b40cd8a9a6f6b5771cfdc29ba4/pkg/sql/opt/exec/execbuilder/relational.go#L1843)):*
> ```Go
> 		inputTable := inputTableMeta.Table
> 		if inputTable.ID() == skipID {
> 			continue
> ```

why is this needed?
___
*[`pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error` line 419 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90007#-NEbtvxG7YdjqLEV745G:-NEbtvxG7YdjqLEV745H:byxepv7) ([raw file](https://github.com/cockroachdb/cockroach/blob/921ae5ffe19f90b40cd8a9a6f6b5771cfdc29ba4/pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error#L419)):*
> ```
> AND rbr.crdb_region = 'ap-southeast-2'
> ----
> project
> ```

why does this have an extra project now?

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90007)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft and @yuzefovich)

___
*[`pkg/sql/region_util.go` line 2364 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90007#-NEbxor5DllrWdc2PNy2:-NEbzz99D1zeRiOzmDUR:b-gxiq79) ([raw file](https://github.com/cockroachdb/cockroach/blob/921ae5ffe19f90b40cd8a9a6f6b5771cfdc29ba4/pkg/sql/region_util.go#L2364)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: Consider changing this here and everywhere else to just `IsDML`. `IsANSIDML` seems overly verbose...
</blockquote></details>

The reason I named it this is because DML has a side meaning of covering only mutation operations, e.g. https://cloud.google.com/bigquery/docs/reference/standard-sql/data-manipulation-language

,but formally in ANSI, SELECT is included.  Just trying to clarify this in case someone is confused by SELECT being included. Also, our code base already tags statements which aren't true DML, as `TypeDML`:
https://github.com/cockroachdb/cockroach/blob/a84835ad027802150db07300eb29cb9ac420012b/pkg/sql/sem/tree/stmt.go#L1183-L1184

So, by naming this ANSIDML, perhaps it will be more clear that this covers only the statements considered by ANSI to be DML.

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90007)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft and @yuzefovich)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90007#-NEbwGAc--IRQeQPH5n3):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Can you give some more details?
</blockquote></details>

Added an example.
___
*[`pkg/sql/opt/exec/execbuilder/relational.go` line 1843 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90007#-NEbvhic3DvpzZCg1pjx:-NEcJrOj5d3Y648DCLLn:b-ueuino) ([raw file](https://github.com/cockroachdb/cockroach/blob/921ae5ffe19f90b40cd8a9a6f6b5771cfdc29ba4/pkg/sql/opt/exec/execbuilder/relational.go#L1843)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

why is this needed?
</blockquote></details>

Added the comment:
```
		// Mutation DML errors out with additional information via a call to
		// `filterSuggestionError`, handled by the caller, so skip the target of
		// the mutations if encountered here.
```



_Code quote:_
```Go
if inputTable.ID() == skipID {
```
___
*[`pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error` line 419 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90007#-NEbtvxG7YdjqLEV745G:-NEcNG91648Pg0akhSZj:b-lf4wm2) ([raw file](https://github.com/cockroachdb/cockroach/blob/921ae5ffe19f90b40cd8a9a6f6b5771cfdc29ba4/pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error#L419)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

why does this have an extra project now?
</blockquote></details>

This is due to removal of the explicit non-hidden `crdb_region` column in the `messages_rbr` table. Since it's now hidden, it's no longer part of the `*` column expansion and is projected away.



_Code quote:_
```
EXPLAIN(OPT) SELECT * FROM  messages_rbt rbt INNER LOOKUP JOIN messages_rbr rbr ON rbr.account_id = rbt.account_id
```

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90007#-:-NEgeDAx0fp_0yjfTXpD:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek and @yuzefovich)

___
*[`pkg/sql/region_util.go` line 2364 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90007#-NEbxor5DllrWdc2PNy2:-NEgeEfO2oNms3YN1BQP:b19u9ra) ([raw file](https://github.com/cockroachdb/cockroach/blob/921ae5ffe19f90b40cd8a9a6f6b5771cfdc29ba4/pkg/sql/region_util.go#L2364)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

The reason I named it this is because DML has a side meaning of covering only mutation operations, e.g. https://cloud.google.com/bigquery/docs/reference/standard-sql/data-manipulation-language

,but formally in ANSI, SELECT is included.  Just trying to clarify this in case someone is confused by SELECT being included. Also, our code base already tags statements which aren't true DML, as `TypeDML`:
https://github.com/cockroachdb/cockroach/blob/a84835ad027802150db07300eb29cb9ac420012b/pkg/sql/sem/tree/stmt.go#L1183-L1184

So, by naming this ANSIDML, perhaps it will be more clear that this covers only the statements considered by ANSI to be DML.

</blockquote></details>

ok thanks for the explanation!

**Review by msirek — COMMENTED** [review]
TFTR!
bors r=rytaft

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90007#-:-NEgrWDa2ydoADm42boa:b1yj9cx)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Pull request merged**
