### PR TITLE
reduce: add parallel execution

### PR DESCRIPTION
**Pull request by madelynnblue**

### CODE REVIEW

**Comment by mjibson** [comment]
ping @justinj

**Review by justinj — APPROVED** [review]
:lgtm_strong: thanks for explaining the algorithm to me!

> Reviewed 2 of 2 files at r1, 5 of 5 files at r2, 2 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40093#-:-Lo7Jum_AhxWYsyh_uM5:bdihfum)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by mjibson** [comment]
TFTR

**Pull request merged**
