### PR TITLE
colexecbase: add all remaining casts from strings

### PR DESCRIPTION
**Pull request by yuzefovich**
**tree: minor cleanup**

This commit does a few minor things:
- actually uses the error in a few places when constructing a ParseError
- refactors some of the interval-parsing functions to expose them to be
used in the follow-up commit
- extracts a helper method to construct an error when timestamp exceeds
bounds.

Release note: None

**colexecbase: sort native cast info lexicographically**

This commit sorts the information about natively supported casts
lexicographically so that it is easier to see what is actually
supported. This is simply a mechanical change.

Release note: None

**colexecbase: add all remaining casts from strings**

This commit adds the native casts from strings to all remaining
natively-supported types (dates, decimals, floats, ints, intervals,
timestamps, jsons).

I was inspired to do this because the combination of this
commit and the vectorized rendering on top of the wrapped row-by-row
processors would expose some bugs (e.g. https://github.com/cockroachdb/cockroach/issues/83094).

Addresses: #48135.

Release note: None

### CODE REVIEW

**Review by msirek — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83958)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @msirek, and @yuzefovich)

___
*[`pkg/sql/colexec/execgen/cmd/execgen/cast_gen_util.go` line 474 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/83958#-N6hdtv_CLrhOuXxyKeE:-N6hdtva1akQP97rgp2s:b-lbyt3i) ([raw file](https://github.com/cockroachdb/cockroach/blob/3637d15d300ebac76a686f3f14cb47eccd64d48b/pkg/sql/colexec/execgen/cmd/execgen/cast_gen_util.go#L474)):*
> ```Go
> 		_now := %[3]s.GetRelativeParseTime()
> 		_dateStyle := %[3]s.GetDateStyle()
> 		_t, _, err := pgdate.ParseTimestamp%[5]s(_now, _dateStyle, string(%[2]s))
> ```

What does `%[5]s` represent here?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83958)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball and @msirek)

___
*[`pkg/sql/colexec/execgen/cmd/execgen/cast_gen_util.go` line 474 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/83958#-N6hdtv_CLrhOuXxyKeE:-N6hrBGI5cOG_gcsvlxB:by8agob) ([raw file](https://github.com/cockroachdb/cockroach/blob/3637d15d300ebac76a686f3f14cb47eccd64d48b/pkg/sql/colexec/execgen/cmd/execgen/cast_gen_util.go#L474)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

What does `%[5]s` represent here?
</blockquote></details>

It refers to the fifth argument for the "format" string (which is `parseTimestampKind` in this case). Depending on the type (i.e. timestamp vs timestamptz) we want to use different methods for parsing which differ only in a suffix.

**Review by msirek — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83958#-:-N6hs9Wc26_Wc1sbqcZO:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @yuzefovich)

___
*[`pkg/sql/colexec/execgen/cmd/execgen/cast_gen_util.go` line 474 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/83958#-N6hdtv_CLrhOuXxyKeE:-N6hs4Mn67cu5GpfYKFc:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/3637d15d300ebac76a686f3f14cb47eccd64d48b/pkg/sql/colexec/execgen/cmd/execgen/cast_gen_util.go#L474)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

It refers to the fifth argument for the "format" string (which is `parseTimestampKind` in this case). Depending on the type (i.e. timestamp vs timestamptz) we want to use different methods for parsing which differ only in a suffix.
</blockquote></details>

Thanks!

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by yuzefovich** [comment]
Unrelated flake.

bors r+

**Pull request merged**
