### PR TITLE
sql/pgwire: Add support for Timestamp and TimestampTZ binary format

### PR DESCRIPTION
**Pull request by nvb**
@dt The handling of `TIMESTAMP` is pretty straightforward, but I'm not sure if I'm handling `TIMESTAMPTZ` correctly. It looks like we only worry about the session timezone on encoding, is this correct? That's different than PG's handling, but that's intentional IIRC.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8590)

### CODE REVIEW

**Comment by dt** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/pgwire/types.go, line 632 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8590#-KPJyLf6n-bm7sAbGk8Q:-KPJyLf6n-bm7sAbGk8R:b4mr1c9) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e95e8d8fca1ce08b77ca03c2dce4e3f82a441f3/sql/pgwire/types.go#L632)):*
> ```Go
> 		case formatBinary:
> 			var i int64
> 			err := binary.Read(bytes.NewReader(b), binary.BigEndian, &i)
> ```

Huh, what's the advantage of this over`i := binary.BigEndian.Uint64(b)` (with a `len(b)` check first) ? seems unfortunate to alloc a reader every time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8590)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/pgwire/types.go, line 632 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8590#-KPJyLf6n-bm7sAbGk8Q:-KPKKWwvv7lucetfKzK9:b-7rlrlg) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e95e8d8fca1ce08b77ca03c2dce4e3f82a441f3/sql/pgwire/types.go#L632)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> Huh, what's the advantage of this over`i := binary.BigEndian.Uint64(b)` (with a `len(b)` check first) ? seems unfortunate to alloc a reader every time.
</details>
This `int64` can be negative, so we cant use `binary.BigEndian.Uint64(b)`, and this is how we decode `int64`s above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8590)*

**Comment by dt** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/pgwire/types.go, line 632 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8590#-KPJyLf6n-bm7sAbGk8Q:-KPKO4jSUbjYFVu97j68:bq676hk) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e95e8d8fca1ce08b77ca03c2dce4e3f82a441f3/sql/pgwire/types.go#L632)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> This `int64` can be negative, so we cant use `binary.BigEndian.Uint64(b)`, and this is how we decode `int64`s above.
</details>
Doesn't `Read` internally just call `*data = int64(order.Uint64(bs))` (after reading 8 bytes from the reader into `bs`)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8590)*

**Comment by RaduBerinde** [comment]
:lgtm: Though it feels that there should be some kind of tests

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8590#-:-KPL3al2Z6y31eJ9Cn1F:b6n5xnv)*

**Comment by nvanbenschoten** [comment]
I agree. We really don't have good testing built up around pgwire. I'm not exactly sure how we should test this code though, because its all fairly straightforward (with the exception of numeric, which we're seeing cause issues in https://github.com/cockroachdb/cockroach/issues/8298). The challenge is verifying that we're compatible with the wire protocol, so ideally our acceptance tests should test this. 

The other option is to add tests like @tamird added for [decimal](https://github.com/tamird/cockroach/blob/e8ca065a4fb991eb378dea4fc0642e996ef51689/sql/pgwire/binary_test.go), but that has limited utility for most of the simpler types.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/pgwire/types.go, line 632 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8590#-KPJyLf6n-bm7sAbGk8Q:-KPLxMCw7bWxQygE1Ay0:b-1i6mt7) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e95e8d8fca1ce08b77ca03c2dce4e3f82a441f3/sql/pgwire/types.go#L632)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> Doesn't `Read` internally just call `*data = int64(order.Uint64(bs))` (after reading 8 bytes from the reader into `bs`)?
</details>
Huh yeah you're right. I added a second commit to address this for all data types.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8590#-:-KPLxUMneKQehAQrUuO2:b-4kz5om)*

**Comment by tamird** [comment]
That second commit should mention motivation. If it's the inherent allocation in `NewReader`, there is also https://godoc.org/bytes#Reader.Reset as of 1.7.

**Comment by dt** [comment]
:lgtm:

I've also run into the difficulty of testing here: most of the time, unless you want to just re-implement pgwire in your test, we need some other oracle that can answer correctness, which so far I think has been one of the drivers in an acceptance test. Holy grail would seem to be an off-the-shelf comprehensive suite of wire protocol tests... maybe from libpq?

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8590#-:-KPNY2qXpzNCZpay-jZ1:bww809w)*

**Comment by dt** [comment]
Looks like this should dodge even more allocs in the case of floats, where, if I'm reading this correctly, `Read` falls back to allocating a new reflection based `decoder` every time. https://golang.org/src/encoding/binary/binary.go?s=5036:5099#L235

**Comment by nvanbenschoten** [comment]
@dt should I be using the [session timezone](https://github.com/cockroachdb/cockroach/blob/82cadcb290f87a1d0e2bcdf78666f45245a6cf58/sql/pgwire/types.go#L304) to offset the time when sending back timestamptz microseconds in the binary format like we do for the text format?

**Comment by dt** [comment]
that sounds likely, but I'd verify with a binary client?

**Comment by nvanbenschoten** [comment]
@dt I just made some pretty big modifications to the first commit to get it working without overflowing on large durations. All test cases for the `duration` package were created using code from the [`rust postgres driver`](https://github.com/sfackler/rust-postgres/blob/e350c0512474b2ea2a5de54af832ceef4773405c/src/types/chrono.rs#L16), so they should be solid.

@mjibson I extended your `generate-decimal` script to work for other data types in the third commit and used this to create binary tests for timestamp and timestamptz. Do you mind taking a look at that?

**Comment by mjibson** [comment]
generate-decimal + TestBinary changes :lgtm:

---

Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8590#-:-KPfGu-XbFSf308xy1N7:b-684dep)*

**Comment by dt** [comment]
:lgtm:  nice!

After this merges, might be good to file and issue to hook that up `DiffMicros` to our durations and use it for sql-facing data math too?

---

Reviewed 4 of 6 files at r2, 1 of 1 files at r3, 1 of 5 files at r4.
Review status: 6 of 10 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8590#-:-KPoLpHA3zTBQB_4_8FU:b-kry850)*

**Comment by tamird** [comment]
Six months late to this party, but this change should have enabled the relevant test in acceptance/c_test.go. It seems that this currently produces incorrect results as judged by whatever java stuff @arjunravinarayan is using.

**Pull request merged**
