### PR TITLE
storage/ui: Expose range's maxBytes field to help debug split issues

### PR DESCRIPTION
**Pull request by a-robinson**
Release note: None

This is a pretty natural fit for going in the `RangeInfo`, and would be nice to see in issues like https://github.com/cockroachdb/cockroach/issues/24966

### CODE REVIEW

**Comment by a-robinson** [comment]
example:

screen shot 2018-04-25 at 1 49 12 pm

**Comment by tschottdorf** [comment]
:lgtm:, but if these were printed as human-readable, I would prefer that (perhaps it's somehow important to have the exact bytes though, not sure).

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25072#-:-LAxvXHn4Uc7a17jQ3HF:bre7k5s)*

**Comment by BramGruneir** [comment]
:lgtm:  With one nit and some details on how to the human readable stuff.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[pkg/ui/src/views/reports/containers/range/rangeTable.tsx, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25072#-LAxxvgN43BjIiJ9Divf:-LAxxvgN43BjIiJ9Divg:bxhw40i) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c74825e9ccd2398740db15bbbb113fc2001aaa8/pkg/ui/src/views/reports/containers/range/rangeTable.tsx#L73)):*
> ```XML
>   { variable: "mvccIntentBytesCount", display: "MVCC Intent Bytes/Count", compareToLeader: true },
>   { variable: "mvccSystemBytesCount", display: "MVCC System Bytes/Count", compareToLeader: true },
>   { variable: "rangeMaxBytes", display: "Max Range Size Before Split", compareToLeader: false },
> ```

Compare to leader should be true.  If the value is different, there's a bigger problem.

---

*[pkg/ui/src/views/reports/containers/range/rangeTable.tsx, line 480 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25072#-LAxypA32uLy0ma4zUDo:-LAxypA32uLy0ma4zUDp:b9664w3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c74825e9ccd2398740db15bbbb113fc2001aaa8/pkg/ui/src/views/reports/containers/range/rangeTable.tsx#L480)):*
> ```XML
>         mvccIntentBytesCount: this.contentMVCC(FixLong(mvcc.intent_bytes), FixLong(mvcc.intent_count)),
>         mvccSystemBytesCount: this.contentMVCC(FixLong(mvcc.sys_bytes), FixLong(mvcc.sys_count)),
>         rangeMaxBytes: this.createContent(FixLong(info.state.range_max_bytes)),
> ```

For human readable, look in here: pkg/ui/src/util/format.ts

You could put the raw value in the title, and the humanized on in the value.

You'll just have to add a new contentFunction, similar to the contentTimestamp one:
```javascript
contentTimestamp(timestamp: protos.cockroach.util.hlc.Timestamp$Properties): RangeTableCellContent {
    const humanized = Print.Timestamp(timestamp);
    return {
      value: [humanized],
      title: [humanized, timestamp.wall_time.toString()],
    };
  }
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25072#-:-LAxzc6NA3Dgs-LDoybi:bxcwlp9)*

**Comment by nvanbenschoten** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25072#-:-LAy4n5F9AL-kxUUqSEI:bnfp4nl)*

**Comment by a-robinson** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/ui/src/views/reports/containers/range/rangeTable.tsx, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25072#-LAxxvgN43BjIiJ9Divf:-LAyAt6-7E2bzflMmFze:b3n4kfu) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c74825e9ccd2398740db15bbbb113fc2001aaa8/pkg/ui/src/views/reports/containers/range/rangeTable.tsx#L73)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Compare to leader should be true.  If the value is different, there's a bigger problem.
</blockquote></details>

I don't think that's the case, actually. I intentionally chose `false` here because when a split attempt fails to find a valid range key, we increase `maxBytes` on the replica that tried to do the split, but make no attempt to propagate that anywhere else. The followers will almost always have the zone config's value here, whereas the leaseholder might have a larger value.

I guess you could say it might be valuable to make it easier to notice such situations, but it isn't actually a problem if they differ.

---

*[pkg/ui/src/views/reports/containers/range/rangeTable.tsx, line 480 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25072#-LAxypA32uLy0ma4zUDo:-LAyBUUP8UYVQ8A1QiGS:b-2ap3nq) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c74825e9ccd2398740db15bbbb113fc2001aaa8/pkg/ui/src/views/reports/containers/range/rangeTable.tsx#L480)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

For human readable, look in here: pkg/ui/src/util/format.ts

You could put the raw value in the title, and the humanized on in the value.

You'll just have to add a new contentFunction, similar to the contentTimestamp one:
```javascript
contentTimestamp(timestamp: protos.cockroach.util.hlc.Timestamp$Properties): RangeTableCellContent {
    const humanized = Print.Timestamp(timestamp);
    return {
      value: [humanized],
      title: [humanized, timestamp.wall_time.toString()],
    };
  }
```
</blockquote></details>

Should we do that for the other fields too? The most common use for this field will be to compare it to `MVCC Key Bytes + MVCC Value Bytes`, both of which are just shown as raw byte counts (along with other fields like `Log Size`. It seems awfully weird to just humanize this one.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25072)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/ui/src/views/reports/containers/range/rangeTable.tsx, line 480 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25072#-LAxypA32uLy0ma4zUDo:-LAyGslwDMJxQSDhus0s:b-1aqeag) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c74825e9ccd2398740db15bbbb113fc2001aaa8/pkg/ui/src/views/reports/containers/range/rangeTable.tsx#L480)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

Should we do that for the other fields too? The most common use for this field will be to compare it to `MVCC Key Bytes + MVCC Value Bytes`, both of which are just shown as raw byte counts (along with other fields like `Log Size`. It seems awfully weird to just humanize this one.
</blockquote></details>

Yeah, I'd prefer to look at the humanized ones (with the original in the tooltip, if that's possible). This includes the bytes ages (which have the unit `size * time`, so they might be awkward to normalize -- might just leave the time unit as `s` always). That said, I won't insist on humanizing any of these in this PR. You could just file an issue.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25072)*

**Comment by BramGruneir** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/ui/src/views/reports/containers/range/rangeTable.tsx, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25072#-LAxxvgN43BjIiJ9Divf:-LAyJ33e3ZmdprPoJIqn:b-ldq5tu) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c74825e9ccd2398740db15bbbb113fc2001aaa8/pkg/ui/src/views/reports/containers/range/rangeTable.tsx#L73)):*
<details><summary><i>Previously, a-robinson (Alex Robinson) wrote…</i></summary><blockquote>

I don't think that's the case, actually. I intentionally chose `false` here because when a split attempt fails to find a valid range key, we increase `maxBytes` on the replica that tried to do the split, but make no attempt to propagate that anywhere else. The followers will almost always have the zone config's value here, whereas the leaseholder might have a larger value.

I guess you could say it might be valuable to make it easier to notice such situations, but it isn't actually a problem if they differ.
</blockquote></details>

Makes sense.  So the correct solution here would be to highlight any value that is higher than the lowest one.  To show that a split failed in the past.  Not too hard to do, just requires setting the class to a different value and looking for all other values beforehand.

---

*[pkg/ui/src/views/reports/containers/range/rangeTable.tsx, line 480 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25072#-LAxypA32uLy0ma4zUDo:-LAyJ_N18Y_1ZS1vrAHC:bdllsqu) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c74825e9ccd2398740db15bbbb113fc2001aaa8/pkg/ui/src/views/reports/containers/range/rangeTable.tsx#L480)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Yeah, I'd prefer to look at the humanized ones (with the original in the tooltip, if that's possible). This includes the bytes ages (which have the unit `size * time`, so they might be awkward to normalize -- might just leave the time unit as `s` always). That said, I won't insist on humanizing any of these in this PR. You could just file an issue.
</blockquote></details>

I don't see why not.  Might want to update the condition on row 222 to also check the non-humanized values in the title.

```
const differentFromLeader = !dormant && !_.isNil(leaderCell) && row.compareToLeader && !_.isEqual(cell.value, leaderCell.value);
```

to


```
const differentFromLeader = !dormant && !_.isNil(leaderCell) && row.compareToLeader && (!_.isEqual(cell.value, leaderCell.value) || !_.isEqual(cell.title, leaderCell.title));
```

And hope this doesn't cause other lines to now show erroneous errors.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25072)*

**Comment by couchand** [comment]
Reviewed 3 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/ui/src/views/reports/containers/range/rangeTable.tsx, line 480 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25072#-LAxypA32uLy0ma4zUDo:-LB1a0Gz9GfLFO41b50A:bb6cbyl) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c74825e9ccd2398740db15bbbb113fc2001aaa8/pkg/ui/src/views/reports/containers/range/rangeTable.tsx#L480)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

I don't see why not.  Might want to update the condition on row 222 to also check the non-humanized values in the title.

```
const differentFromLeader = !dormant && !_.isNil(leaderCell) && row.compareToLeader && !_.isEqual(cell.value, leaderCell.value);
```

to


```
const differentFromLeader = !dormant && !_.isNil(leaderCell) && row.compareToLeader && (!_.isEqual(cell.value, leaderCell.value) || !_.isEqual(cell.title, leaderCell.title));
```

And hope this doesn't cause other lines to now show erroneous errors.
</blockquote></details>

I'd prefer that an issue not be created to track this.  If it's worth doing at all (and I think that it is), please just do it on this PR.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25072)*

**Comment by a-robinson** [comment]
TFTRs!

---

Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/ui/src/views/reports/containers/range/rangeTable.tsx, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25072#-LAxxvgN43BjIiJ9Divf:-LB1dYSC-Lczl_5wG3do:b-v200gh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c74825e9ccd2398740db15bbbb113fc2001aaa8/pkg/ui/src/views/reports/containers/range/rangeTable.tsx#L73)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Makes sense.  So the correct solution here would be to highlight any value that is higher than the lowest one.  To show that a split failed in the past.  Not too hard to do, just requires setting the class to a different value and looking for all other values beforehand.
</blockquote></details>

Eh, I decided to just switch `compareToLeader` to true, since it is worth calling our attention to a difference. It's not necessarily a sign that's something wrong, but it is unusual and in most cases is probably correlated with badness.

---

*[pkg/ui/src/views/reports/containers/range/rangeTable.tsx, line 480 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25072#-LAxypA32uLy0ma4zUDo:-LB1iHz13WfRfrTAs2g7:buo9lll) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c74825e9ccd2398740db15bbbb113fc2001aaa8/pkg/ui/src/views/reports/containers/range/rangeTable.tsx#L480)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

I'd prefer that an issue not be created to track this.  If it's worth doing at all (and I think that it is), please just do it on this PR.
</blockquote></details>

Done, including for all the MVCC fields.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25072#-:-LB1j5r54Vz93UwBiV1u:bz5mair)*

**Comment by a-robinson** [comment]
New look of the page:
screen shot 2018-04-26 at 12 11 40 pm

**Comment by tschottdorf** [comment]
:heartbeat: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25072#-:-LB1pfKqEjpMbnSXLMul:b74ws31)*

**Comment by a-robinson** [comment]
I hope you like them, since figuring out how to take a screenshot without losing the tooltip was harder than it should have been.f

screen shot 2018-04-26 at 1 47 57 pm

screen shot 2018-04-26 at 1 48 08 pm

**Comment by BramGruneir** [comment]
:lgtm:  Awesome!  Thanks for taking the time to crop those. :)

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25072#-:-LB254YQEf4UQIyqKGNL:b-phey4k)*

**Comment by tschottdorf** [comment]
Neat, thanks @a-robinson!

**Comment by couchand** [comment]
Thanks @a-robinson!

**Comment by tschottdorf** [comment]
You're probably aware, but a backport for this would be swell.

**Comment by a-robinson** [comment]
I hadn't been planning on it, so thanks for mentioning it.

**Pull request merged**
