### PR TITLE
importccl: refactor some helpers out of read processor

### PR DESCRIPTION
**Pull request by dt**
Should be just code moves in this one.

Release note: none.

### CODE REVIEW

**Review by adityamaru27 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39544)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by dt** [comment]
Initially I assumed that was a real failure since it is in TestImportCSV but it looks like it was a Rocks error during an IngestExternalFile from a pre-emptive snapshot application via SST.

bors r+

**Comment by dt** [comment]
looks like this error is occurring on master builds too https://teamcity.cockroachdb.com/viewLog.html?buildId=1434377&buildTypeId=Cockroach_UnitTests_Testrace&tab=buildChangesDiv

bors r+

**Comment by dt** [comment]
This will probably fail too since master just looks red, but hey, it *might* not: 

bors r+

**Pull request merged**
