### PR TITLE
util/tracing: limit number of child spans per span

### PR DESCRIPTION
**Pull request by ajwerner**
This limit controls both the number of local spans as well as the total
number of remote recorded spans. Given that remote recorded spans are
flattened and that the total number of log entries per span is already
bounded by a constant, this should do an okay job bounding the memory
usage in tracing. In the cases where we've seen memory explode due to
tracing, the spans have numbered in the the millions.

Touches #52106.

Release note (general change): The number of child spans in tracing has
been capped to prevent unbounded memory usage.

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
I was hoping that we'd try to be smarter when the limits are hit, and always keep the last span. You feel like it?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54259#-:-MHCGLPv0Hm-WsTcrKq9:by4xer5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @andreimatei, and @jayshrivastava)

___
*[pkg/util/tracing/tracer.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54259#-MHCDcsi-inWWhq37V-x:-MHCDcsj-sSRAbhqipDX:b-gacq6r) ([raw file](https://github.com/cockroachdb/cockroach/blob/8aca8df698021efe389782e666354d99c9f531e0/pkg/util/tracing/tracer.go#L77)):*
> ```Go
> // unprincipled.
> var maxChildSpansPerSpan = settings.RegisterNonNegativeIntSetting(
> 	"trace.span.max_child_spans",
> ```

how about just `trace.max_child_spans`?
___
*[pkg/util/tracing/tracer_span.go, line 657 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/54259#-MHCFBFV87B6PZkjX1wm:-MHCFBFV87B6PZkjX1wn:b-jokwly) ([raw file](https://github.com/cockroachdb/cockroach/blob/8aca8df698021efe389782e666354d99c9f531e0/pkg/util/tracing/tracer_span.go#L657)):*
> ```Go
> 		s.mu.recording.remoteSpans = append(s.mu.recording.remoteSpans, remoteSpans...)
> 	}
> 	// TODO(ajwerner): Add a log record when totalChildSpans reaches maxChildren.
> ```

let's do this, here and below. Silently missing logs are no bueno. Just add a message with a timestamp just after the start of the last span we add.

**Review by ajwerner — COMMENTED** [review]
I'm trying to parse this apart and I'm not sure exactly what either part means

1)  try to be smarter when the limits are hit

Like what, make it so that once you've reached the limit, you never move back under it, even if the limit changes? I think that's probably a good behavior considering point 2

2) always keep the last span


What do you mean by `last` here? I was thinking (the TODO) that it'd be good to add a log record indicating that the trace was truncated but I'm not sure what else you have in mind. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54259#-:-MHCbPSF-s7mONkYdde9:b-8bx8dl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @jayshrivastava)

**Review by andreimatei — COMMENTED** [review]
What I want is that when the memory limit is hit and more spans come, we start replacing some of the old spans, or at least somehow reserve a spot for the very last span, so that the trace look like

<span 1>
<span 2>
... omitted...
<last span>

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54259#-:-MHCftKn7GBxy3D29GQh:b-e3lj7x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @jayshrivastava)

**Review by andreimatei — COMMENTED** [review]
something ate my comment
I want 
```
<span 1>
<span 2>
... omitted...
<last span(s)>
```

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/54259#-:-MHCh2tO2GHQcDr7NOBQ:btc6nds)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @jayshrivastava)

**Comment by ajwerner** [comment]
Closing as stale.

**Pull request closed without merging**
