### PR TITLE
opt: improve null col extraction from constraints

### PR DESCRIPTION
**Pull request by RaduBerinde**
For constrained scans, we weren't extracting not-null columns from the
constraint. This change fixes that and improves the not-null
extraction to work on descending columns and to look at more than the
first column.

Release note: None

### CODE REVIEW

**Comment by andy-kimball** [comment]
:lgtm:

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/opt/constraint/constraint.go, line 470 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26759#-LFAXi0J6ZtT-aEuf6OK:-LFAXi0J6ZtT-aEuf6OL:b-cl3062) ([raw file](https://github.com/cockroachdb/cockroach/blob/a29dad182670038112577bb1cf2674828f435311/pkg/sql/opt/constraint/constraint.go#L470)):*
> ```Go
> 	// has prefix 2. Only these columns and the first following column can be
> 	// known to be not-null.
> 	prefix := 0
> ```

Did you consider calling `ExactPrefix` where, and then re-looping over cols to check for the `hasNull` case? Logic might be cleaner.

---

*[pkg/sql/opt/constraint/testutils.go, line 110 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26759#-LFAZEXwCwGDjzYvnh9d:-LFAZEXwCwGDjzYvnh9e:b-tynbyt) ([raw file](https://github.com/cockroachdb/cockroach/blob/a29dad182670038112577bb1cf2674828f435311/pkg/sql/opt/constraint/testutils.go#L110)):*
> ```Go
> }
> 
> // parseIntPath parses a span key string like "/1/2/3".
> ```

NIT: parseIntPath -> parseDatumPath

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26759#-:-LFAZiIG-VBNYsIXnCKo:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: :shipit: complete! 1 of 0 LGTMs obtained

---

*[pkg/sql/opt/constraint/constraint.go, line 470 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26759#-LFAXi0J6ZtT-aEuf6OK:-LFCcCqP-2KTN4kyrSwg:b-fois7j) ([raw file](https://github.com/cockroachdb/cockroach/blob/a29dad182670038112577bb1cf2674828f435311/pkg/sql/opt/constraint/constraint.go#L470)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Did you consider calling `ExactPrefix` where, and then re-looping over cols to check for the `hasNull` case? Logic might be cleaner.
</blockquote></details>

`ExactPrefix` is more strict - it wants all spans to have the *same* values on the prefix. For example, the ExactPrefix of the example here `[/1/1/1 - /1/1/2] [/3/3/3 - /3/3/4]` is 0.
I added an example to `ExactPrefix` to make this clearer.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26759)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 10 of 15 files at r1, 5 of 5 files at r2.
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26759#-:-LFHaOz65oRIJdRlwikD:bnfp4nl)*

**Pull request merged**
