### PR TITLE
release-23.2: ttljob: fix job to handle composite PKs

### PR DESCRIPTION
**Pull request by rafiss**
Backport 2/2 commits from #116988 and #117510

/cc @cockroachdb/release

Release justification: high priority bug fix

---

Certain types, like decimals and collated strings, store their contents in the value of the encoded KeyValue. The ttljob code that decodes the span bounds into datums for the purpose of creating SQL query bounds previously did not take this into account.

fixes https://github.com/cockroachdb/cockroach/issues/116845
Release note (bug fix): Fixed a bug in the row-level TTL job that would
cause it to skip expired rows if the primary key of the table included
columns of the collated string type. This bug was present since the
initial release of row-level TTL in v22.2.0.

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117512#-:-NnepUvO4-qVhCnfwU-J:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @adityamaru, @rafiss, and @yuzefovich)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117512#-Nnep-mpAFpyyQ8cZ26L):*
Do you think it would be worth removing the mention of decimal here, since it shouldn't actually cause skipped rows?

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 6 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117512)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @adityamaru and @DrewKimball)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117512#-Nnep-mpAFpyyQ8cZ26L):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

Do you think it would be worth removing the mention of decimal here, since it shouldn't actually cause skipped rows?
</blockquote></details>

Also perhaps mention that the bug was introduced when TTL feature was added (with concrete version).

**Comment by rafiss** [comment]
I agree, I was planning to wait a bit

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117512)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru, @DrewKimball, and @mgartner)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/117512#-Nnep-mpAFpyyQ8cZ26L):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Also perhaps mention that the bug was introduced when TTL feature was added (with concrete version).
</blockquote></details>

updated on both accounts

**Review by mgartner — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/117512#-:-NoHmo2EAPSQeDiTIWen:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru and @DrewKimball)

**Pull request merged**
