### PR TITLE
build: avoid spurious recompiles

### PR DESCRIPTION
**Pull request by benesch**
See individual commits for details. Only the first one is necessary to avoid spurious recompiles; the latter just makes a bare `go build` not print mountains of garbage.

### CODE REVIEW

**Comment by tamird** [comment]
> This commit teaches Make to stop sharing its package cache with non-Make
> builds by passing the `-pkgdir` option to `go build`.

This description makes it sound like much less of a hammer than it is - you're essentially moving all the build suffix logic from the go tool to our Makefiles, right? The commit message should definitely call that out.

Just reviewing the first commit for now.

---

Reviewed 3 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

*[Makefile, line 129 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16907#-KoOZ-TU9XOuJsUU4TTk:-KoOZ-TU9XOuJsUU4TTl:b37lt1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f32f71a12fd61ae7984d33add1c2eaca2f856a83/Makefile#L129)):*
> ot

to

---

*[Makefile, line 133 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16907#-KoOZ4GmQBEk8Ix9KReu:-KoOZ4GmQBEk8Ix9KRev:b5skddf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f32f71a12fd61ae7984d33add1c2eaca2f856a83/Makefile#L133)):*
> a NATIVE_TAG

s/a //

---

*[Makefile, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16907#-KoOZ9_oAqQpzdMdEb6b:-KoOZ9_oAqQpzdMdEb6c:bw5930j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f32f71a12fd61ae7984d33add1c2eaca2f856a83/Makefile#L137)):*
> ```Makefile
> # that -pkgdir completely overrides the automatic -installsuffix, so we're
> # careful to include _race and _msan in NATIVE_TAG when GOFLAGS contains -race
> # or -msan, respectively.
> ```

s,or|and,and/or/g

---

*[build/common.mk, line 236 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16907#-KoOXI6FPeJZdi-atXaA:-KoOXI6FPeJZdi-atXaB:bycq2ze) ([raw file](https://github.com/cockroachdb/cockroach/blob/f32f71a12fd61ae7984d33add1c2eaca2f856a83/build/common.mk#L236)):*
> ```Makefile
> override RACE_TAG := $(if $(findstring -race,$(GOFLAGS)),_race)
> override MSAN_TAG := $(if $(findstring -msan,$(GOFLAGS)),_msan)
> override STDMALLOC_TAG := $(if $(findstring stdmalloc,$(TAGS)),_msan)
> ```

s/_msan/_stdmalloc/?

---

*[build/common.mk, line 237 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16907#-KoOXPt4gKd5JrCaI5PX:-KoOXPt4gKd5JrCaI5PY:b-rl3oi4) ([raw file](https://github.com/cockroachdb/cockroach/blob/f32f71a12fd61ae7984d33add1c2eaca2f856a83/build/common.mk#L237)):*
> ```Makefile
> override MSAN_TAG := $(if $(findstring -msan,$(GOFLAGS)),_msan)
> override STDMALLOC_TAG := $(if $(findstring stdmalloc,$(TAGS)),_msan)
> override DEADLOCK_TAG := $(if $(findstring deadlock,$(TAGS)),_deadlock)
> ```

this is also new, and should be called out in the commit message (in other words, adding this doesn't have much to do with `go`/`make` flip-flopping)

perhaps it could even easily be in its own commit

---

*[build/common.mk, line 242 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16907#-KoOXaT4Ly9QHnkPm-BO:-KoOXaT4Ly9QHnkPm-BP:b-uneq6b) ([raw file](https://github.com/cockroachdb/cockroach/blob/f32f71a12fd61ae7984d33add1c2eaca2f856a83/build/common.mk#L242)):*
> ```Makefile
> # assertions enabled. Roll this into race builds for now; race builds are a)
> # already slow, so the overhead of RocksDB assertions is negligible, and b)
> # already run on TeamCity.
> ```

s/on TeamCity/in CI/

No need for this specificity.

---

*[build/common.mk, line 291 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16907#-KoOY-3aHR3f3hVgMV2C:-KoOY-3aHR3f3hVgMV2D:bmuae49) ([raw file](https://github.com/cockroachdb/cockroach/blob/f32f71a12fd61ae7984d33add1c2eaca2f856a83/build/common.mk#L291)):*
> ```Makefile
> endif
> 
> JEMALLOC_DIR := $(BUILD_DIR)/jemalloc$(MSAN_TAG)
> ```

is this better? the knowledge that all native dependencies are sensitive to msan was previously contained in one place - now it's duplicated everywhere and has no explanation.

---

*[build/common.mk, line 302 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16907#-KoOYDGVzO2hvpK0BtVi:-KoOYDGVzO2hvpK0BtVj:bb7r2e5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f32f71a12fd61ae7984d33add1c2eaca2f856a83/build/common.mk#L302)):*
> ```Makefile
> 
> # Go does not permit dashes in build tags. This is undocumented. Fun!
> NATIVE_TAG := $(subst -,_,$(TARGET_TRIPLE))$(RACE_TAG)$(MSAN_TAG)$(STDMALLOC_TAG)$(DEADLOCK_TAG)
> ```

why 

---

*[build/common.mk, line 318 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16907#-KoOYI1qABHqgC-cVJa-:-KoOYI1qABHqgC-cVJa0:byozivy) ([raw file](https://github.com/cockroachdb/cockroach/blob/f32f71a12fd61ae7984d33add1c2eaca2f856a83/build/common.mk#L318)):*
> ```Makefile
> # invoked with.
> #
> # Suffixed flags files (e.g. zcgo_flags_{NATIVE_TAG}.go) have the build
> ```

this should be "i.e" now, not "e.g."

---

*[build/common.mk, line 321 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16907#-KoOYTqQMJoLy3wvQB7Z:-KoOYTqQMJoLy3wvQB7_:bud7jdq) ([raw file](https://github.com/cockroachdb/cockroach/blob/f32f71a12fd61ae7984d33add1c2eaca2f856a83/build/common.mk#L321)):*
> This build tag is not set when invoking
> # the Go toolchain directly, so these files are only compiled when building with
> # Make.

Previous wording was better - this new passive voice makes me wonder how I should run the go toolchain directly through this makefile (....?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16907#-:-KoOWuH4gVBrujiO4Z2L:bhzq92b)*

**Comment by benesch** [comment]
Done.

---

Review status: 1 of 3 files reviewed at latest revision, 10 unresolved discussions.

---

*[Makefile, line 129 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16907#-KoOZ-TU9XOuJsUU4TTk:-KoO_Ar2emWybQrOSvBa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f32f71a12fd61ae7984d33add1c2eaca2f856a83/Makefile#L129)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

> ot

to
</blockquote></details>

Done.

---

*[Makefile, line 133 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16907#-KoOZ4GmQBEk8Ix9KReu:-KoO_BBi4kAjbKABqRMB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f32f71a12fd61ae7984d33add1c2eaca2f856a83/Makefile#L133)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

> a NATIVE_TAG

s/a //
</blockquote></details>

Done.

---

*[Makefile, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16907#-KoOZ9_oAqQpzdMdEb6b:-KoO_Xicj_BBJyN_oPRf:bsuycm1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f32f71a12fd61ae7984d33add1c2eaca2f856a83/Makefile#L137)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

s,or|and,and/or/g
</blockquote></details>

Oof, that was hard to decipher. Don't you mean:

```
s,or|and,and/or,g
```

Anyway, done.

---

*[build/common.mk, line 236 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16907#-KoOXI6FPeJZdi-atXaA:-KoO_hHSz3gUkiU928k0:by60ukr) ([raw file](https://github.com/cockroachdb/cockroach/blob/f32f71a12fd61ae7984d33add1c2eaca2f856a83/build/common.mk#L236)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

s/_msan/_stdmalloc/?
</blockquote></details>

Eek, thanks.

---

*[build/common.mk, line 237 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16907#-KoOXPt4gKd5JrCaI5PX:-KoOeY9UE2D3kdpVrCYi:b67uvq8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f32f71a12fd61ae7984d33add1c2eaca2f856a83/build/common.mk#L237)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this is also new, and should be called out in the commit message (in other words, adding this doesn't have much to do with `go`/`make` flip-flopping)

perhaps it could even easily be in its own commit
</blockquote></details>

Removed. I'll leave it for you when you reenable deadlock builds.

---

*[build/common.mk, line 242 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16907#-KoOXaT4Ly9QHnkPm-BO:-KoO_nBEoQ2GkUNx-wqQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f32f71a12fd61ae7984d33add1c2eaca2f856a83/build/common.mk#L242)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

s/on TeamCity/in CI/

No need for this specificity.
</blockquote></details>

Done.

---

*[build/common.mk, line 291 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16907#-KoOY-3aHR3f3hVgMV2C:-KoObIAmI7UW-Khyl7vM:bn36nw9) ([raw file](https://github.com/cockroachdb/cockroach/blob/f32f71a12fd61ae7984d33add1c2eaca2f856a83/build/common.mk#L291)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

is this better? the knowledge that all native dependencies are sensitive to msan was previously contained in one place - now it's duplicated everywhere and has no explanation.
</blockquote></details>

Well, the alternative is that build tags appear in two places in the directory hierarchy, which is pretty weird:

```
$GOPATH/native/x86_64-apple-darwin16.6.0/jemalloc
$GOPATH/native/x86_64-apple-darwin16.6.0/protobuf
$GOPATH/native/x86_64-apple-darwin16.6.0/rocksdb
$GOPATH/native/x86_64-apple-darwin16.6.0/rocksdb_stdmalloc
$GOPATH/native/x86_64-apple-darwin16.6.0/rocksdb_stdmalloc_assert
$GOPATH/native/x86_64-apple-darwin16.6.0/rocksdb_assert
$GOPATH/native/x86_64-apple-darwin16.6.0/snappy
$GOPATH/native/x86_64-apple-darwin16.6.0_msan/jemalloc
$GOPATH/native/x86_64-apple-darwin16.6.0_msan/protobuf
$GOPATH/native/x86_64-apple-darwin16.6.0_msan/rocksdb
$GOPATH/native/x86_64-apple-darwin16.6.0_msan/rocksdb_stdmalloc
$GOPATH/native/x86_64-apple-darwin16.6.0_msan/rocksdb_stdmalloc_assert
$GOPATH/native/x86_64-apple-darwin16.6.0_msan/rocksdb_assert
$GOPATH/native/x86_64-apple-darwin16.6.0_msan/snappy
```

---

*[build/common.mk, line 302 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16907#-KoOYDGVzO2hvpK0BtVi:-KoOaA3YT4dFMY0USZYS:b-dj2nmr) ([raw file](https://github.com/cockroachdb/cockroach/blob/f32f71a12fd61ae7984d33add1c2eaca2f856a83/build/common.mk#L302)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why 
</blockquote></details>

Er, why what?

---

*[build/common.mk, line 318 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16907#-KoOYI1qABHqgC-cVJa-:-KoOa9InQRDKvbnOS6iM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f32f71a12fd61ae7984d33add1c2eaca2f856a83/build/common.mk#L318)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this should be "i.e" now, not "e.g."
</blockquote></details>

Done.

---

*[build/common.mk, line 321 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16907#-KoOYTqQMJoLy3wvQB7Z:-KoObEpqKdFvinG3pbgh:b9sl6ol) ([raw file](https://github.com/cockroachdb/cockroach/blob/f32f71a12fd61ae7984d33add1c2eaca2f856a83/build/common.mk#L321)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

> This build tag is not set when invoking
> # the Go toolchain directly, so these files are only compiled when building with
> # Make.

Previous wording was better - this new passive voice makes me wonder how I should run the go toolchain directly through this makefile (....?)
</blockquote></details>

Mk, done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16907#-:-KoOecz1uGA8VoNmByyd:b-896fix)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[Makefile, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16907#-KoOZ9_oAqQpzdMdEb6b:-KoOex9XsqMrMCfkqsfi:b-kdeywe) ([raw file](https://github.com/cockroachdb/cockroach/blob/f32f71a12fd61ae7984d33add1c2eaca2f856a83/Makefile#L137)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Oof, that was hard to decipher. Don't you mean:

```
s,or|and,and/or,g
```

Anyway, done.
</blockquote></details>

Ha, yeah; last slash was wrong. Good thing you're not a computer.

---

*[build/common.mk, line 291 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16907#-KoOY-3aHR3f3hVgMV2C:-KoOfA47dTKgT0_ZhBVs:b-yqk585) ([raw file](https://github.com/cockroachdb/cockroach/blob/f32f71a12fd61ae7984d33add1c2eaca2f856a83/build/common.mk#L291)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Well, the alternative is that build tags appear in two places in the directory hierarchy, which is pretty weird:

```
$GOPATH/native/x86_64-apple-darwin16.6.0/jemalloc
$GOPATH/native/x86_64-apple-darwin16.6.0/protobuf
$GOPATH/native/x86_64-apple-darwin16.6.0/rocksdb
$GOPATH/native/x86_64-apple-darwin16.6.0/rocksdb_stdmalloc
$GOPATH/native/x86_64-apple-darwin16.6.0/rocksdb_stdmalloc_assert
$GOPATH/native/x86_64-apple-darwin16.6.0/rocksdb_assert
$GOPATH/native/x86_64-apple-darwin16.6.0/snappy
$GOPATH/native/x86_64-apple-darwin16.6.0_msan/jemalloc
$GOPATH/native/x86_64-apple-darwin16.6.0_msan/protobuf
$GOPATH/native/x86_64-apple-darwin16.6.0_msan/rocksdb
$GOPATH/native/x86_64-apple-darwin16.6.0_msan/rocksdb_stdmalloc
$GOPATH/native/x86_64-apple-darwin16.6.0_msan/rocksdb_stdmalloc_assert
$GOPATH/native/x86_64-apple-darwin16.6.0_msan/rocksdb_assert
$GOPATH/native/x86_64-apple-darwin16.6.0_msan/snappy
```
</blockquote></details>

Perhaps thinking about these path bits as build tags isn't the right mental model, in the context of native dependencies?

Anyway, I think "weird" is preferable to "error prone". Note that this PR already made that mistake (which you just fixed).

---

*[build/common.mk, line 302 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16907#-KoOYDGVzO2hvpK0BtVi:-KoOfVAJU1gNOu52Hp2P:b-um7j65) ([raw file](https://github.com/cockroachdb/cockroach/blob/f32f71a12fd61ae7984d33add1c2eaca2f856a83/build/common.mk#L302)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Er, why what?
</blockquote></details>

Eh, I think this comment was errant.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16907)*

**Comment by tamird** [comment]
:lgtm: mod "weird" vs "error prone" bit

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[Makefile, line 145 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16907#-KoOg3PsH4g5wV1hnuHO:-KoOg3PsH4g5wV1hnuHP:bbn4249) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef6b84ddc4a6067ec21c3b7e9757661859b3681f/Makefile#L145)):*
> ```Makefile
> # https://github.com/jemalloc/jemalloc/issues/494.
> ifdef MACOS
> export MACOSX_DEPLOYMENT_TARGET ?= $(shell sw_vers -productVersion | grep -oE '[0-9]+\.[0-9]+')
> ```

any reason not to use `\d`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16907#-:-KoOfo86Ik53XW9A9lFg:bhfcrso)*

**Comment by benesch** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[Makefile, line 145 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16907#-KoOg3PsH4g5wV1hnuHO:-KoQBVJvbpo-oZT2ibb2:bmind6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef6b84ddc4a6067ec21c3b7e9757661859b3681f/Makefile#L145)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

any reason not to use `\d`?
</blockquote></details>

It's not POSIX-compliant. `[[:digit:]]` and `[0-9]` are, but the latter is shorter.

More practically, I'll bet you $10 that OpenBSD's grep doesn't support `\d`.

---

*[build/common.mk, line 291 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16907#-KoOY-3aHR3f3hVgMV2C:-KoQEGUpBo1tEjPL5LAt:b-t1qcw5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f32f71a12fd61ae7984d33add1c2eaca2f856a83/build/common.mk#L291)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Perhaps thinking about these path bits as build tags isn't the right mental model, in the context of native dependencies?

Anyway, I think "weird" is preferable to "error prone". Note that this PR already made that mistake (which you just fixed).
</blockquote></details>

Thinking about this more, I still think I'd prefer a clean separation between target triples and build tags/"variants". How about this compromise?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16907)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[build/common.mk, line 291 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16907#-KoOY-3aHR3f3hVgMV2C:-KoRYthoFj9M5eKaR4mZ:b-kpfiva) ([raw file](https://github.com/cockroachdb/cockroach/blob/f32f71a12fd61ae7984d33add1c2eaca2f856a83/build/common.mk#L291)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Thinking about this more, I still think I'd prefer a clean separation between target triples and build tags/"variants". How about this compromise?
</blockquote></details>

I still think it's error prone, but OK.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16907)*

**Comment by dt** [comment]
spurious recompiles seem to be gone! yay! fwiw, i'm getting a page of warnings from `ld` about OS X version now though -- e.g.:
```
ld: warning: object file (/Users/david/go/native/x86_64-apple-darwin16.6.0/jemalloc/lib/libjemalloc.a(mutex_pool.o)) was built for newer OSX version (10.12.5) than being linked (10.12)
ld: warning: object file (/Users/david/go/native/x86_64-apple-darwin16.6.0/jemalloc/lib/libjemalloc.a(nstime.o)) was built for newer OSX version (10.12.5) than being linked (10.12)
```

**Comment by benesch** [comment]
@dt :tada:! The page of warnings is fixed by the second commit, but you'll need to `make clean` to pick it up. (Didn't seem like it was worth forcing everyone to rebuild, since the only change is suppressing the warning.)

This is unfortunately blocked because there is LITERALLY NO WAY to tell `go tool vet` to use a pkgdir other than `$GOPATH/pkg`. :cry:

**Comment by benesch** [comment]
We'll probably just want to wait until Go 1.9, which allows vetting from source via `go vet -source`, is released mid-August.

**Comment by tamird** [comment]
@benesch this PR should address this TODO, right? https://github.com/cockroachdb/cockroach/blob/116c87d/build/builder.sh#L150

**Comment by benesch** [comment]
Yep, it definitely should!

**Comment by benesch** [comment]
Ok, this is all set and ready to merge the day Go 1.9 comes up.

**Comment by tamird** [comment]
@benesch this is unblocked now, correct? Did you want to address that TODO in build/builder.sh?

**Comment by benesch** [comment]
Indeed it is. Holding off for a week or two, though, when I'm less busy. This stuff tends to cause all sorts of weird build failures that take forever to diagnose.

**Comment by benesch** [comment]
The vet/stringer from source half of this has already landed, and the other half is more or less part of #15337. Closing!

**Pull request closed without merging**
