### PR TITLE
kv: fix bugs with interaction between locking scans and deferred WriteTooOldErrors

### PR DESCRIPTION
**Pull request by nvb**
#### kv/kvserver: don't defer WriteTooOld errors for "read-only" requests

This commit fixes a bug where WriteTooOld errors could be deferred for FOR UPDATE locking ScanRequests. These requests can return WriteTooOld errors because they serve as the initial read for an upcoming write. The issue was that we were checking for "read-write" requests to determine whether the errors _must_ be returned instead of checking for "blind-write" requests to determine whether the errors _can_ be deferred.

For these read-only requests that encounter a WriteTooOldError, we don't have the option of returning a response with the WriteTooOld flag set because a response is not even generated in tandem with the WriteTooOldError. We could fix this and then allow WriteTooOldErrors to be deferred in these cases, but doing so would buy more into the extremely error-prone approach of retuning responses and errors together throughout the MVCC read path. Doing so it not desirable as it has repeatedly caused bugs in the past. Instead, we'd like to get rid of this pattern entirely and instead buy in to speculatively evaluation.

Release justification: Avoids a bug where locking scan requests could defer their WriteTooOld error and then not return a valid response.

#### kv/kvserver: don't allow server-side refresh with bounded read latches

This commit prevents an error-prone situation where requests that acquire read-latches at bounded timestamps are retried at higher timestamps without re-acquiring new latches. This could allow the request to read at an unprotected timestamp and forgo proper synchronization with writes with respect to its lock-table scan and timestamp cache update.

It's not clear whether this could ever actually materialize as a bug because we try not to mix read-only and read-write requests. Regardless, it's better to be cautious here.

Release justification: fixes a potential source of bugs.

#### kv/kvclient: support generalized server-side refreshes

This commit generalizes the concept of a server-side transaction refresh for any request issued by a transaction before it has accumulated refresh spans. Server-side refreshes were previously only possible for batches that contained an EndTxn, but this was limiting for no particularly strong reason.

The commit supports this new functionality by adding a new flag to the BatchRequest header called `CanForwardReadTimestamp`. This flag indicates that the batch can be evaluated at a higher timestamp than the transaction's read timestamp. It is set by the client if the transaction has not performed any reads that must be refreshed prior to sending this current batch. When set, it allows the server to handle pushes and write too old conditions locally.

In the future, we'd like to remove the EndTxn.CanCommitAtHigherTimestamp flag entirely in favor of this more general mechanism.

While adding support for this new form of server-side refresh, the commit also adds a retry loop on the read-only request evaluation path. This is almost never exercised because most read-only requests acquire MVCC read latches and also don't throw WriteTooOld errors, but it can be exercised for locking scans, which acquire MVCC write latches and do occasionally throw WriteTooOld errors.

Release justification: necessary to avoid a performance regression due to implicit SELECT FOR UPDATE in certain cases where UPDATEs are heavily contended. Before implicit SFU, a heavily contended UPDATE statement would always eventually commit after 3 retries:
epoch 1: {Scan} succeeds, {Put, EndTxn} hits WriteTooOld
epoch 2: {Scan} succeeds, {Put} defers WriteTooOld and writes intent, {EndTxn} fails
epoch 3: {Scan} succeeds, {Put} rewrites intent, {EndTxn} succeeds

After SFU but before this change we could get cases where the {Scan} continues to hit WriteTooOld errors and has no bound on the number of attempts it will make.

After SFU and this change the UPDATE will always commit after exactly 1 retry:
epoch 1: {Scan} hits WriteTooOld and server-side refreshes, {Put, EndTxn} succeeds.

### CODE REVIEW

**Review by andreimatei — APPROVED** [review]
LGTM but see comment about checking against a "max timestamp" at which evaluations are allowed rather than what you're checking.

first commit message is off. s/are/at ?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46004#-:-M2FA05Z8atIybrczhL0:b397gqc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_evaluate.go, line 295 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46004#-M2FB_qR4Lxrl7x0hdgc:-M2FB_qS0DGbUsYtzhdi:bv43u0d) ([raw file](https://github.com/cockroachdb/cockroach/blob/f81e88a554c8864895460a00ab58393ac2bf3834/pkg/kv/kvserver/replica_evaluate.go#L295)):*
> ```Go
> 				// WriteTooOldError. We could fix this and then allow WriteTooOldErrors
> 				// to be deferred in these cases, but doing so would buy more into the
> 				// extremely error-prone approach of retuning responses and errors
> ```

retuning
___
*[pkg/kv/kvserver/replica_evaluate.go, line 296 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46004#-M2FBcO92N5YfZyPYZD8:-M2FBcO92N5YfZyPYZD9:b-sdwltz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f81e88a554c8864895460a00ab58393ac2bf3834/pkg/kv/kvserver/replica_evaluate.go#L296)):*
> ```Go
> 				// to be deferred in these cases, but doing so would buy more into the
> 				// extremely error-prone approach of retuning responses and errors
> 				// together throughout the MVCC read path. Doing so it not desirable as
> ```

s/it/si
___
*[pkg/kv/kvserver/replica_evaluate.go, line 302 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46004#-M2FBiWO6usJTTvGrznG:-M2FBiWO6usJTTvGrznH:bvrdm96) ([raw file](https://github.com/cockroachdb/cockroach/blob/f81e88a554c8864895460a00ab58393ac2bf3834/pkg/kv/kvserver/replica_evaluate.go#L302)):*
> ```Go
> 				// TODO(andrei): What we really want to do here is either speculatively
> 				// evaluate the request at the bumped timestamp and return that
> 				// speculative result, or leave behind a type of lock that wouldn't
> ```

maybe now you can replace "a type of lock" with better words
___
*[pkg/kv/kvserver/replica_evaluate.go, line 305 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46004#-M2FC-vJDl9DAq_Mid72:-M2FC-vK0hHJdZGhpR1i:b-uoipna) ([raw file](https://github.com/cockroachdb/cockroach/blob/f81e88a554c8864895460a00ab58393ac2bf3834/pkg/kv/kvserver/replica_evaluate.go#L305)):*
> ```Go
> 				// prevent the request for evaluating again at the same sequence number
> 				// but at a bumped timestamp.
> 				if !roachpb.IsBlindWrite(args) {
> ```

would it be possible to put an assertion here somewhere that reads without the locking flag set don't encounter `WriteTooOldErrors`?
___
*[pkg/kv/kvserver/replica_evaluate.go, line 547 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/46004#-M2FFOeZEBdkmIP6urP4:-M2FFOe_56Usq8qwyJlJ:bk2ijze) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdc298016794fba74ac7f75f84e8bf07c7377a26/pkg/kv/kvserver/replica_evaluate.go#L547)):*
> ```Go
> 			et := etArg.(*roachpb.EndTxnRequest)
> 			canFwdCTS := batcheval.CanForwardCommitTimestampWithoutRefresh(ba.Txn, et)
> 			if canFwdRTS && !canFwdCTS {
> ```

can't we simply test `canCTS == canRTS` ?
___
*[pkg/kv/kvserver/replica_test.go, line 9706 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/46004#-M2FDjp04gSbk3I8SHYh:-M2FDjp04gSbk3I8SHYi:b-bl09w0) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f066fe086b594ac6d6baff7367469c36a0ae39e/pkg/kv/kvserver/replica_test.go#L9706)):*
> ```Go
> 				get := getArgs(roachpb.Key("a"))
> 				put := putArgs(roachpb.Key("a"), []byte("put2"))
> 				ba.Add(&get, &put)
> ```

leave a note here that this batch is unusual in that it combines a read and a write
___
*[pkg/kv/kvserver/replica_write.go, line 581 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/46004#-M2FDA9N8xIPd6oryUiq:-M2FDA9N8xIPd6oryUir:b-e2gre7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f066fe086b594ac6d6baff7367469c36a0ae39e/pkg/kv/kvserver/replica_write.go#L581)):*
> ```Go
> 		// and re-acquiring those latches. Doing so could allow the request to
> 		// read at an unprotected timestamp.
> 		// TODO(nvanbenschoten): we could consider adding a retry-loop above the
> ```

nit: remove the todo. Switch to NOTE, if anything.
___
*[pkg/kv/kvserver/spanset/spanset.go, line 210 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46004#-M2FA7TLBHIcrtwvSxwv:-M2FA7TLBHIcrtwvSxww:b-r0x82o) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d48c9db91a940a579eca6273705df18c51011ba/pkg/kv/kvserver/spanset/spanset.go#L210)):*
> ```Go
> 
> // CheckAllowedAt is like CheckAllowed, except it returns an error if the access
> // is not allowed at over the given keyspan at the given timestamp.
> ```

something's off about this comment
___
*[pkg/kv/kvserver/spanset/spanset.go, line 211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46004#-M2FGD7BCcixff--xjtD:-M2FGD7BCcixff--xjtE:bmbae49) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d48c9db91a940a579eca6273705df18c51011ba/pkg/kv/kvserver/spanset/spanset.go#L211)):*
> ```Go
> // CheckAllowedAt is like CheckAllowed, except it returns an error if the access
> // is not allowed at over the given keyspan at the given timestamp.
> func (s *SpanSet) CheckAllowedAt(
> ```

I assume this `SpanSet` is tracking the latches acquire by a request, and then checking refers to asserting that we're having the right latch?
I'd find a way to explain this, I guess spread across the definition of the struct and `CheckAllowed`. Maybe even call the struct `LatchSet`?

On first read I thought that we're checking requests against latches acquired by *other* requests.
___
*[pkg/kv/kvserver/spanset/spanset.go, line 232 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46004#-M2FAFCs6qV_CNPQpArk:-M2FAFCs6qV_CNPQpArl:bou9uip) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d48c9db91a940a579eca6273705df18c51011ba/pkg/kv/kvserver/spanset/spanset.go#L232)):*
> ```Go
> 			case SpanReadWrite:
> 				// NB: should not get here, see checkAllowed.
> 				panic("unexpected SpanReadWrite access")
> ```

put the span and timestamp in the message
___
*[pkg/kv/kvserver/spanset/spanset.go, line 234 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46004#-M2FAL0H0yjTfCWBfdJb:-M2FAL0I4FQGtib-v2Vl:b-d46vrv) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d48c9db91a940a579eca6273705df18c51011ba/pkg/kv/kvserver/spanset/spanset.go#L234)):*
> ```Go
> 				panic("unexpected SpanReadWrite access")
> 			default:
> 				panic("unexpected span access")
> ```

put `access` in the msg
___
*[pkg/kv/kvserver/spanset/spanset.go, line 241 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46004#-M2FAwqg85TdIzv5Prki:-M2FAwqg85TdIzv5Prkj:b2tx35) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d48c9db91a940a579eca6273705df18c51011ba/pkg/kv/kvserver/spanset/spanset.go#L241)):*
> ```Go
> 				// Write spans acquired at a specific timestamp allow reads at
> 				// any timestamp. Non-MVCC access is not allowed.
> 				return !timestamp.IsEmpty()
> ```

how about a `nonMVCC := timestamp.IsEmpty()` in the beginning of the method?
___
*[pkg/kv/kvserver/spanset/spanset.go, line 184 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/46004#-M2FDTMq84cp6vJ0_6vC:-M2FDTMq84cp6vJ0_6vD:b-c25i1a) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f066fe086b594ac6d6baff7367469c36a0ae39e/pkg/kv/kvserver/spanset/spanset.go#L184)):*
> ```Go
> // provided access has a bounded timestamps then the zero value timestamp will
> // be returned.
> func (s *SpanSet) MinTimestamp(access SpanAccess) hlc.Timestamp {
> ```

Is it a minimum timestamp, or is it a maximum one? `MaxProtectedTimestamp` (or just `ProtectedTimestamp`? And return +inf when appropriate.
And then turn the check in `canDoServerSideRetry()` to check the timestamp of the potential retry against the protected one. I think this was the plan; any particular reason you moved away from it?
___
*[pkg/roachpb/api.go, line 121 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46004#-M2FCOoA2p3XBb7yQJui:-M2FCOoA2p3XBb7yQJuj:blt08kc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f81e88a554c8864895460a00ab58393ac2bf3834/pkg/roachpb/api.go#L121)):*
> ```Go
> // state when modifying the state and may base their modifications off
> // of this existing state (such as conditional puts and increments). As
> // a result of being "blind", blind-writes are allowed to be more freely
> ```

Not new, but what's this thing about re-ordering more freely (hope it wasn't me who wrote it :P) ? 
If it refers to this server-side refresh thing, let's say something more specific.
___
*[pkg/roachpb/api.proto, line 1870 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/46004#-M2FEX-e7UGj9bU-VUlj:-M2FEX-e7UGj9bU-VUlk:b5ngf51) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdc298016794fba74ac7f75f84e8bf07c7377a26/pkg/roachpb/api.proto#L1870)):*
> ```protobuf
>   // NOTE: this flag is a generalization of EndTxn.CanCommitAtHigherTimestamp.
>   // That flag should be deprecated in favor of this one.
>   // TODO(nvanbenschoten): perform this migration.
> ```

I'd put a TODO on the definition of that other flag. We can just remove that other flag in 20.2, right?

**Review by nvb — COMMENTED** [review]
> first commit message is off. s/are/at ?

Done.

TFTR! I think I addressed everything.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46004#-:-M2FSgU42CbCSb62tLMl:bw5p512)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/kvserver/replica_evaluate.go, line 295 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46004#-M2FB_qR4Lxrl7x0hdgc:-M2FVd2H83g_kQ_ecsY7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f81e88a554c8864895460a00ab58393ac2bf3834/pkg/kv/kvserver/replica_evaluate.go#L295)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

retuning
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replica_evaluate.go, line 296 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46004#-M2FBcO92N5YfZyPYZD8:-M2FVdHs3Yge_uCi1R1r:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f81e88a554c8864895460a00ab58393ac2bf3834/pkg/kv/kvserver/replica_evaluate.go#L296)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

s/it/si
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replica_evaluate.go, line 302 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46004#-M2FBiWO6usJTTvGrznG:-M2FVt7vBZ2H2PPRwfn6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f81e88a554c8864895460a00ab58393ac2bf3834/pkg/kv/kvserver/replica_evaluate.go#L302)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

maybe now you can replace "a type of lock" with better words
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replica_evaluate.go, line 305 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46004#-M2FC-vJDl9DAq_Mid72:-M2FVvfk1XF9zmvS2mon:baezxs8) ([raw file](https://github.com/cockroachdb/cockroach/blob/f81e88a554c8864895460a00ab58393ac2bf3834/pkg/kv/kvserver/replica_evaluate.go#L305)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

would it be possible to put an assertion here somewhere that reads without the locking flag set don't encounter `WriteTooOldErrors`?
</blockquote></details>

I wouldn't. It seems like a pretty heavyweight assertion (we'd have to match against multiple types of requests and then check their fields) without much benefit. And nothing would break if that wasn't the case.
___
*[pkg/kv/kvserver/replica_evaluate.go, line 547 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/46004#-M2FFOeZEBdkmIP6urP4:-M2FaqKS8IDf2It1zQCA:bvy6rn8) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdc298016794fba74ac7f75f84e8bf07c7377a26/pkg/kv/kvserver/replica_evaluate.go#L547)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

can't we simply test `canCTS == canRTS` ?
</blockquote></details>

No, to remain backward compatible we need to allow for `!canFwdRTS && canFwdCTS`. This is tested in `TestReplicaServersideRefreshes/serverside-refresh_of_write_too_old_on_1PC_txn`.
___
*[pkg/kv/kvserver/replica_test.go, line 9706 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/46004#-M2FDjp04gSbk3I8SHYh:-M2FXki-7QuL8RRYGP71:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f066fe086b594ac6d6baff7367469c36a0ae39e/pkg/kv/kvserver/replica_test.go#L9706)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

leave a note here that this batch is unusual in that it combines a read and a write
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/replica_write.go, line 581 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/46004#-M2FDA9N8xIPd6oryUiq:-M2FXvtv-6gCwlWlwH4J:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f066fe086b594ac6d6baff7367469c36a0ae39e/pkg/kv/kvserver/replica_write.go#L581)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: remove the todo. Switch to NOTE, if anything.
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/spanset/spanset.go, line 210 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46004#-M2FA7TLBHIcrtwvSxwv:-M2FTMmkB5W6I6OTG-n3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d48c9db91a940a579eca6273705df18c51011ba/pkg/kv/kvserver/spanset/spanset.go#L210)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

something's off about this comment
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/spanset/spanset.go, line 211 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46004#-M2FGD7BCcixff--xjtD:-M2FTY-BEsW-66oPIL4L:b-wu95g0) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d48c9db91a940a579eca6273705df18c51011ba/pkg/kv/kvserver/spanset/spanset.go#L211)):*
> I assume this SpanSet is tracking the latches acquire by a request, and then checking refers to asserting that we're having the right latch?

Yes, this is how this is used.

> I'd find a way to explain this, I guess spread across the definition of the struct and CheckAllowed. Maybe even call the struct LatchSet?

Done.

Done, in combination with the existing comment on `NewReadWriterAt`, which says:
```
// NewReadWriterAt returns an engine.ReadWriter that asserts access of the
// underlying ReadWriter against the given SpanSet at a given timestamp.
// If zero timestamp is provided, accesses are considered non-MVCC.
```
___
*[pkg/kv/kvserver/spanset/spanset.go, line 232 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46004#-M2FAFCs6qV_CNPQpArk:-M2FUfcIA4SUa8cP873N:b598m7x) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d48c9db91a940a579eca6273705df18c51011ba/pkg/kv/kvserver/spanset/spanset.go#L232)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

put the span and timestamp in the message
</blockquote></details>

Meh, I'd rather not have them escape to the heap.
___
*[pkg/kv/kvserver/spanset/spanset.go, line 234 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46004#-M2FAL0H0yjTfCWBfdJb:-M2FUakP4uHOrTKoA4X7:b5q2gtx) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d48c9db91a940a579eca6273705df18c51011ba/pkg/kv/kvserver/spanset/spanset.go#L234)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

put `access` in the msg
</blockquote></details>

Same thing.
___
*[pkg/kv/kvserver/spanset/spanset.go, line 241 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46004#-M2FAwqg85TdIzv5Prki:-M2FUyhD1a42k2dZtsx5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7d48c9db91a940a579eca6273705df18c51011ba/pkg/kv/kvserver/spanset/spanset.go#L241)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

how about a `nonMVCC := timestamp.IsEmpty()` in the beginning of the method?
</blockquote></details>

Done.
___
*[pkg/kv/kvserver/spanset/spanset.go, line 184 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/46004#-M2FDTMq84cp6vJ0_6vC:-M2F_1xi2X0nJEWYzG23:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f066fe086b594ac6d6baff7367469c36a0ae39e/pkg/kv/kvserver/spanset/spanset.go#L184)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Is it a minimum timestamp, or is it a maximum one? `MaxProtectedTimestamp` (or just `ProtectedTimestamp`? And return +inf when appropriate.
And then turn the check in `canDoServerSideRetry()` to check the timestamp of the potential retry against the protected one. I think this was the plan; any particular reason you moved away from it?
</blockquote></details>

Done.
___
*[pkg/roachpb/api.go, line 121 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/46004#-M2FCOoA2p3XBb7yQJui:-M2FWnSI-oZsTihYL3nv:b-8ex44c) ([raw file](https://github.com/cockroachdb/cockroach/blob/f81e88a554c8864895460a00ab58393ac2bf3834/pkg/roachpb/api.go#L121)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Not new, but what's this thing about re-ordering more freely (hope it wasn't me who wrote it :P) ? 
If it refers to this server-side refresh thing, let's say something more specific.
</blockquote></details>

Done. Don't worry, I think it was me :smiley: 
___
*[pkg/roachpb/api.proto, line 1870 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/46004#-M2FEX-e7UGj9bU-VUlj:-M2FaoP5BJ3mT8x729CS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdc298016794fba74ac7f75f84e8bf07c7377a26/pkg/roachpb/api.proto#L1870)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'd put a TODO on the definition of that other flag. We can just remove that other flag in 20.2, right?
</blockquote></details>

Done.

**Review by andreimatei — COMMENTED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46004#-:-M2FtPf77eIkOkMFi4tT:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

**Comment by nvanbenschoten** [comment]
Bors didn't like that the release justifications in the PR description were bold.

bors r+

**Comment by nvanbenschoten** [comment]
Spelling fix.

bors r+

**Comment by nvanbenschoten** [comment]
Build flake.

bors r+

**Pull request merged**
