### PR TITLE
storage: move off dead/decommissioning stores via atomic swaps

### PR DESCRIPTION
**Pull request by tbg**
This is the last known work item for #12768. Previously, the replicate
queue would use an add-and-remove strategy to get replicas off
decommissioning or dead stores. Now it uses swaps whenever it can,
subject to the usual restrictions around single-replica groups and
cluster versions.

Release justification: feature completes atomic replication changes.

Release note: None

### CODE REVIEW

**Review by danhhz — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41190#-:-Lq1wGIM2fa03RiWu7aR:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @danhhz and @tbg)

___
*[pkg/storage/client_raft_test.go, line 2933 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41190#-Lq1rQcB5A7uwIiEoM6H:-Lq1rQcB5A7uwIiEoM6I:bfaekes) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3de4dc06730ad8d34d77c696167216a57422533/pkg/storage/client_raft_test.go#L2933)):*
> ```Go
> }
> 
> func requireOnlyAtomicChanges(
> ```

worth deduping this with the one in replicate_queue_test.go?
___
*[pkg/storage/client_raft_test.go, line 3044 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41190#-Lq1w0w298tlR8ZZDWq8:-Lq1w0w298tlR8ZZDWq9:b-qyo67n) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3de4dc06730ad8d34d77c696167216a57422533/pkg/storage/client_raft_test.go#L3044)):*
> ```Go
> 	const single = 1
> 
> 	// The range should drop down to one replica, neither of which is on a decommissioning store.
> ```

nit: "neither of which" doesn't sound right to me here
___
*[pkg/storage/replicate_queue.go, line 347 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41190#-Lq1ns4F7BXiMQfk7YXK:-Lq1ns4F7BXiMQfk7YXL:bkc6iqs) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3de4dc06730ad8d34d77c696167216a57422533/pkg/storage/replicate_queue.go#L347)):*
> ```Go
> 			return false, nil
> 		}
> 		removeIdx := -1 // guaranteed to be changed below
> ```

worth being defensive and putting an AssertionFailedf to verify this below (esp in case it rots)?
___
*[pkg/storage/replicate_queue.go, line 358 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41190#-Lq1oF_QBiX9NKHq37TE:-Lq1oF_QBiX9NKHq37TF:b42okoe) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3de4dc06730ad8d34d77c696167216a57422533/pkg/storage/replicate_queue.go#L358)):*
> ```Go
> 		decommissioningReplicas := rq.allocator.storePool.decommissioningReplicas(
> 			desc.RangeID, voterReplicas)
> 		if len(decommissioningReplicas) == 0 {
> ```

nit: slightly more clear (to me at least) if you move this below the for/range and make the condition `removeIdx == -1`
___
*[pkg/storage/replicate_queue.go, line 390 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41190#-Lq1oShJ-T3HVYzMCmbQ:-Lq1oShJ-T3HVYzMCmbR:b-ipst6b) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3de4dc06730ad8d34d77c696167216a57422533/pkg/storage/replicate_queue.go#L390)):*
> ```Go
> 		return true, err
> 	default:
> 		log.Fatalf(ctx, "unknown allocator action %v", action)
> ```

log.Fatal seems excessive? thoughts on returning an error instead?
___
*[pkg/storage/replicate_queue.go, line 455 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41190#-Lq1msWbCBTG2XA4tLEL:-Lq1msWbCBTG2XA4tLEM:b-1222fx) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3de4dc06730ad8d34d77c696167216a57422533/pkg/storage/replicate_queue.go#L455)):*
> ```Go
> 	}
> 	if removeIdx >= 0 && newStore.StoreID == existingReplicas[removeIdx].StoreID {
> 		return false, errors.Errorf("allocator suggested to replace replica on s%d with itself", newStore.StoreID)
> ```

AssertionFailedf? (this is borderline, but i like the documentation of intent that it gives)

**Review by tbg — COMMENTED** [review]
TFTR! I had to skip the test under stressrace and I remembered to delete the test I wanted to delete in place of the new one (it used mtc, and was also skipped under stress).

Going to stress this a bit on my gceworker to make sure we're not immediately eating a flake. BTW this test can take a long time, presumably for the same reason as in https://github.com/cockroachdb/cockroach/pull/41122.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41190#-:-Lq2dNxU-5wUVRzibIx_:biba9jg)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @danhhz)

___
*[pkg/storage/client_raft_test.go, line 2933 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41190#-Lq1rQcB5A7uwIiEoM6H:-Lq2aqFj2_qY4akBiduC:bqxrzsl) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3de4dc06730ad8d34d77c696167216a57422533/pkg/storage/client_raft_test.go#L2933)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

worth deduping this with the one in replicate_queue_test.go?
</blockquote></details>

Hmm, not an unreasonable ask, but I'm going to leave as is if you don't mind. I don't think the duplication does any harm and I have few cycles left this release.
___
*[pkg/storage/replicate_queue.go, line 358 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41190#-Lq1oF_QBiX9NKHq37TE:-Lq2cRFC5w3f3XWG6fAh:b-zhybog) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3de4dc06730ad8d34d77c696167216a57422533/pkg/storage/replicate_queue.go#L358)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

nit: slightly more clear (to me at least) if you move this below the for/range and make the condition `removeIdx == -1`
</blockquote></details>

But then I have to guard the access to `decommissioningReplicas[0]`?
___
*[pkg/storage/replicate_queue.go, line 390 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41190#-Lq1oShJ-T3HVYzMCmbQ:-Lq2cY2W3IVE4kxVcQGN:b-7pkxxz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3de4dc06730ad8d34d77c696167216a57422533/pkg/storage/replicate_queue.go#L390)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

log.Fatal seems excessive? thoughts on returning an error instead?
</blockquote></details>

Hmm, this should really never happen and if it did, probably the queue wouldn't work very well? Errors here tend to not show up on clients. I made this an error anyway since it's near impossible to imagine that an action would just not be implemented and that passing tests.
___
*[pkg/storage/replicate_queue.go, line 456 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41190#-Lq2cwF40uxtOqaPfpZj:-Lq2cwF40uxtOqaPfpZk:b6abfaz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3de4dc06730ad8d34d77c696167216a57422533/pkg/storage/replicate_queue.go#L456)):*
> ```
> allocator suggested to replace repl
> ```

**Comment by danhhz** [comment]
FYI I’m not going to get a chance to look at this again today so feel free to merge before I do. Everything I had was minor, so if I do find something on a second pass we can do a followup PR

**Comment by tbg** [comment]
TFTR! CI was red because I left an unused method around. My gceworker:

> 1715 runs completed, 0 failures, over 37m44

bors r=danhhz

**Comment by tbg** [comment]
Ugh, had another unreachable code path. Fixed now and verified that `make lint` passes on gceworker.

bors r=danhhz

**Review by danhhz — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41190#-:-Lq6wy5zDgW78UQjd-Nk:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @danhhz and @tbg)

___
*[pkg/storage/client_raft_test.go, line 2933 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41190#-Lq1rQcB5A7uwIiEoM6H:-Lq6wXvc7UbyR-J7Iq3V:b-o64mcu) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3de4dc06730ad8d34d77c696167216a57422533/pkg/storage/client_raft_test.go#L2933)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Hmm, not an unreasonable ask, but I'm going to leave as is if you don't mind. I don't think the duplication does any harm and I have few cycles left this release.
</blockquote></details>

Yup, totally fine. Worth a TODO if you have to touch this again, but don't eat a CI cycle over it
___
*[pkg/storage/replicate_queue.go, line 358 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41190#-Lq1oF_QBiX9NKHq37TE:-Lq6wmkLC62K_xBnBgnG:bq5bhtf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d3de4dc06730ad8d34d77c696167216a57422533/pkg/storage/replicate_queue.go#L358)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

But then I have to guard the access to `decommissioningReplicas[0]`?
</blockquote></details>

Sorry, brain fart

**Pull request merged**
