### PR TITLE
kvserver: improve logging for follower reads

### PR DESCRIPTION
**Pull request by andreimatei**
Release note: None

### CODE REVIEW

**Review by aayushshah15 — APPROVED** [review]
LGTM

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51523#-:-MCOgnZ_AL7kNHWYElQl:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_follower_read.go, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51523#-MCOYj8V0Ig6WRviT2FP:-MCOYj8V0Ig6WRviT2FQ:bf4vw5w) ([raw file](https://github.com/cockroachdb/cockroach/blob/e242fb224b4431e369c6dcd3f89727d364ebcfe9/pkg/kv/kvserver/replica_follower_read.go#L101)):*
> ```Go
> 	// TODO(tschottdorf): once a read for a timestamp T has been served, the replica may
> 	// serve reads for that and smaller timestamps forever.
> 	log.Eventf(ctx, "serving via follower read; query timestamp below closed timestamp by %s", -tsDiff)
> ```

nit: `s/-tsDiff/tsDiff` given that we're talking about an absolute time difference, reading something like `query timestamp below closed timestamp by -1.0s` seems incorrect & potentially confusing.

**Review by nvb — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51523#-:-MCT9KN1AMBa2j3Pmvtd:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15 and @andreimatei)

___
*[pkg/kv/kvserver/replica_follower_read.go, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51523#-MCT8CnC2KpaeQ_hNxEB:-MCT8CnC2KpaeQ_hNxEC:b-nwzfjf) ([raw file](https://github.com/cockroachdb/cockroach/blob/e242fb224b4431e369c6dcd3f89727d364ebcfe9/pkg/kv/kvserver/replica_follower_read.go#L44)):*
> ```Go
> ) *roachpb.Error {
> 	canServeFollowerRead := false
> 	var tsDiff time.Duration
> ```

nit: is the structure of this function strange to you? It's currently:
```go
ok := false
if x && y && z && more {
    ok = predicate()
    if !ok {
        // do something
    }
}

if !ok {
    return false
}
return true
```

Wouldn't it be easier to read and avoid the need for these awkwardly scoped variables if it was written like:
```go
reqEligible := x && y && z && more
if !reqEligible {
    return false
}

reqServable := predicate()
if !reqServable {
    // do something
    return false
}
return true
```
___
*[pkg/kv/kvserver/replica_follower_read.go, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51523#-MCOYj8V0Ig6WRviT2FP:-MCT91a71qn6WjUg0we6:bt2qu8f) ([raw file](https://github.com/cockroachdb/cockroach/blob/e242fb224b4431e369c6dcd3f89727d364ebcfe9/pkg/kv/kvserver/replica_follower_read.go#L101)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

nit: `s/-tsDiff/tsDiff` given that we're talking about an absolute time difference, reading something like `query timestamp below closed timestamp by -1.0s` seems incorrect & potentially confusing.
</blockquote></details>

`tsDiff` will be negative on this path though, right? So I think the code is trying to do what you're saying.

**Comment by aayushshah15** [comment]
___
*[pkg/kv/kvserver/replica_follower_read.go, line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51523#-MCOYj8V0Ig6WRviT2FP:-MCT9w-mA8YA5utYSTmN:b-ana9ph) ([raw file](https://github.com/cockroachdb/cockroach/blob/e242fb224b4431e369c6dcd3f89727d364ebcfe9/pkg/kv/kvserver/replica_follower_read.go#L101)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`tsDiff` will be negative on this path though, right? So I think the code is trying to do what you're saying.
</blockquote></details>

Right, :+1:

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51523)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @aayushshah15 and @nvanbenschoten)

___
*[pkg/kv/kvserver/replica_follower_read.go, line 44 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51523#-MCT8CnC2KpaeQ_hNxEB:-MCrnlV31R3rMbAfL4pD:b8dr1wr) ([raw file](https://github.com/cockroachdb/cockroach/blob/e242fb224b4431e369c6dcd3f89727d364ebcfe9/pkg/kv/kvserver/replica_follower_read.go#L44)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: is the structure of this function strange to you? It's currently:
```go
ok := false
if x && y && z && more {
    ok = predicate()
    if !ok {
        // do something
    }
}

if !ok {
    return false
}
return true
```

Wouldn't it be easier to read and avoid the need for these awkwardly scoped variables if it was written like:
```go
reqEligible := x && y && z && more
if !reqEligible {
    return false
}

reqServable := predicate()
if !reqServable {
    // do something
    return false
}
return true
```
</blockquote></details>

done in a prepended commit

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51523#-:-MCrpFin5DPTedZsjHmr:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51523#-:-MCsT3O-9-h-GWC4I81j:b-ydi9ay)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
If I'm not mistaken, this PR has a valid CI failure on `TestStoreRangeMergeTimestampCacheCausality`.

bors r-

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51523#-:-MCwKkGq5mw4VRHh5xa3:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51523#-:-MCxyjw-8kvEsZskL33e:b-616sc)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

**Pull request merged**
