### PR TITLE
storage: smarten logic to wait for split trigger

### PR DESCRIPTION
**Pull request by tbg**
We previously "waited" for the split trigger quite literally, by
dropping an outgoing rejecting MsgAppResp for a few seconds. The
downside of doing so was that it would also artificially delay Raft
snapshots that were actually required. With the introduction of a
mechanism that delays split that would cause Raft snapshots this is a
lesser problem than before, but it's still ugly.

The revamped mechanism in this commit goes the extra mile to make
an informed decision on whether a split trigger is expected to apply:

1. when sending MsgApp to a follower that is being probed, send the
start key along with the message
2. when receiving said MsgApp on an uninitialized replica, check whether
the store has a replica that currently owns the start key. This replica
is the one in charge of applying the split trigger,
3. unless it's waiting for GC (so trigger a check for that).

There's also a time-based escape hatch to avoid delaying snapshots
indefinitely should there be a flaw in the above logic.

Release note: None

### CODE REVIEW

**Review by nvb — CHANGES_REQUESTED** [review]
Very happy to see this! With this extra information, we'll be able to make much more informed decisions on the follower side.

> Reviewed 1 of 7 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32782#-:-LSokGI_1A0H3aMs2BkD:b-yfi8yx)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica.go, line 5214 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32782#-LSod2TM7gVUbKjUY7RZ:-LSod2TM7gVUbKjUY7R_:b-kkmsdd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1d3052149dc637386f6ab310ce1816035ca2d56/pkg/storage/replica.go#L5214)):*
> ```Go
> 		_ = maybeDropMsgApp
> 		if status := r.raftStatusRLocked(); status != nil {
> 			if pr, ok := status.Progress[msg.To]; ok && pr.State == raft.ProgressStateProbe {
> ```

How often do we expect a follower to be in this state? I'd hate for this to blow up Raft message sizes in cases where we're not even going to use the key.

This does get me wondering about whether this is the right place to pass this information. I'm out of the loop with these change so I'm probably off, but what happens if we add similar logic to ignore/reject snapshots. Is the idea that once we reject a MsgApp (and enter `ProgressStateSnapshot`) it's hard to get back to the right state without an eventual snapshot?
___
*[pkg/storage/replica.go, line 5218 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32782#-LSoiUDe9kOmyRnq9heH:-LSoiUDe9kOmyRnq9heI:btpfgao) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1d3052149dc637386f6ab310ce1816035ca2d56/pkg/storage/replica.go#L5218)):*
> ```Go
> 					log.Fatalf(ctx, "msg.Context nonempty for MsgApp: %v", msg.Context)
> 				}
> 				msg.Context = r.descRLocked().StartKey
> ```

Should we make the `Context` a structured message so we can extend it later without compatibility concerns?
___
*[pkg/storage/split_trigger_helper.go, line 58 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32782#-LSogzEKACUCehltiEA7:-LSogzEKACUCehltiEA8:badlrzi) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1d3052149dc637386f6ab310ce1816035ca2d56/pkg/storage/split_trigger_helper.go#L58)):*
> ```Go
> func maybeDropMsgApp(
> 	ctx context.Context,
> 	r interface {
> ```

This is pretty fragile. I would pull it into a named interface.
___
*[pkg/storage/split_trigger_helper.go, line 86 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32782#-LSoizHH07HaJj82NYjI:-LSoizHH07HaJj82NYjJ:b-9bfrw4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1d3052149dc637386f6ab310ce1816035ca2d56/pkg/storage/split_trigger_helper.go#L86)):*
> ```Go
> 	// replica):
> 	//
> 	// sender  (leader)    [a--lhs--b)[b---rhs----c)
> ```

Nice diagram!
___
*[pkg/storage/split_trigger_helper.go, line 124 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32782#-LSojaZc1d7lG26fUsFo:-LSojaZc1d7lG26fUsFp:bs9ih6g) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1d3052149dc637386f6ab310ce1816035ca2d56/pkg/storage/split_trigger_helper.go#L124)):*
> ```Go
> 	// message, resulting in a snapshot, as intended.
> 
> 	verbose := verboseRaftLoggingEnabled()
> ```

nit: this all seems a little verbose (unintended pun). You're only using `eventf` twice below, which doesn't really justify the cost of creating it.
___
*[pkg/storage/split_trigger_helper.go, line 145 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32782#-LSok2iW29YSknjbj_Ki:-LSok2iW29YSknjbj_Kj:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1d3052149dc637386f6ab310ce1816035ca2d56/pkg/storage/split_trigger_helper.go#L145)):*
> ```Go
> 		// the above analysis) in which a split trigger just isn't coming. If
> 		// there are, the idea is that we notice this log message and improve
> 		// the heuristics.
> ```

:thumbsup:

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32782)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica.go, line 5214 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32782#-LSo-oje2A-GeIOsrOgb:-LSo-oje2A-GeIOsrOgc:b-492uoa) ([raw file](https://github.com/cockroachdb/cockroach/blob/54fac7363148996637f903b4f9c7e800ba02d3d2/pkg/storage/replica.go#L5214)):*
> ```Go
> 		// below for more context:
> 		_ = maybeDropMsgApp
> 		if status := r.raftStatusRLocked(); status != nil {
> ```

@nvanbenschoten I'm unhappy about the allocation here and I know you've disliked this kind of thing as well. On `master` I'm planning to solve this problem with a change in `etcd/raft`, though that likely won't be backportable (and I'd like to at least be able to consider this change for a backport, for we've backported its predecessor). How bad is this allocation in the meantime (and on 2.1)?

edit: noticed I hadn't actually sent this comment earlier.
___
*[pkg/storage/replica.go, line 5214 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32782#-LSod2TM7gVUbKjUY7RZ:-LSosCLD0MWl2pFxnPc0:b-nay5rr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1d3052149dc637386f6ab310ce1816035ca2d56/pkg/storage/replica.go#L5214)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

How often do we expect a follower to be in this state? I'd hate for this to blow up Raft message sizes in cases where we're not even going to use the key.

This does get me wondering about whether this is the right place to pass this information. I'm out of the loop with these change so I'm probably off, but what happens if we add similar logic to ignore/reject snapshots. Is the idea that once we reject a MsgApp (and enter `ProgressStateSnapshot`) it's hard to get back to the right state without an eventual snapshot?
</blockquote></details>

Yeah, we don't want to enter the snapshot queue erroneously. It may be possible to get Raft out of that state cleanly (at least after appropriate upstream changes), but I want `raftsnapshot.pending` to be a flat line at some point. We'll send at most one MsgApp per heartbeat interval to a follower that is being probed, so perf shouldn't be a concern here. (in steady state, followers are never expected to be in that state, this only occurs around cluster restarts and replication changes and such).

I morally also want to send something along in MsgAppResp instead, but it's tricky. The uninitialized follower is really dumb and doesn't know anything about itself and the world, so in particular it has no idea where in the key space it should be. The leader (who is the right-hand-side) on the other hand doesn't know about the left-hand-side's bound (and in particular I've often seen its corresponding left-hand-side replica not be leader any more in a rebalancing unit test I have laying around in a WIP that attempted to go this route).

Let me know if you see something I missed. As far as I can tell, we'll need information to go from the leader to the follower and back (the "back" being the rejection in this PR, we could also send an explicit context if we find a reason for it).
___
*[pkg/storage/replica.go, line 5218 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32782#-LSoiUDe9kOmyRnq9heH:-LSouTsI3-ViDQMO1HSQ:buknrlg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1d3052149dc637386f6ab310ce1816035ca2d56/pkg/storage/replica.go#L5218)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we make the `Context` a structured message so we can extend it later without compatibility concerns?
</blockquote></details>

That sounds like a good idea.

**Review by tbg — COMMENTED** [review]
Updated, PTAL.

> Dismissed @nvanbenschoten from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32782#-:-LStgRMB51r98h_1YUa_:b-rr168b)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica.go, line 5218 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32782#-LSoiUDe9kOmyRnq9heH:-LStfdGjBO4YZlCkecG0:b-d3db57) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1d3052149dc637386f6ab310ce1816035ca2d56/pkg/storage/replica.go#L5218)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

That sounds like a good idea.
</blockquote></details>

Done, sort of. I actually took a step back and reconsidered where I was putting this information. The reason I chose the `Context` field is because it was there and so there wasn't any migration headache. However, it's a bit of a wart especially since it gets passed into Raft and we'd have to put protos inside protos. So what I've done instead is put it on `RaftMessageRequest` (as `StartKey`). Old versions receiving the hint simply won't use it, and since RaftMessageRequest doesn't inform any downstream-of-Raft-logic, there shouldn't be a problem.
___
*[pkg/storage/split_trigger_helper.go, line 58 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32782#-LSogzEKACUCehltiEA7:-LStYuXZ75AiwcoX3C71:bzdwq4d) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1d3052149dc637386f6ab310ce1816035ca2d56/pkg/storage/split_trigger_helper.go#L58)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This is pretty fragile. I would pull it into a named interface.
</blockquote></details>

I don't understand why it's fragile, but I understand that you didn't like the looks of it. Done.
___
*[pkg/storage/split_trigger_helper.go, line 124 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32782#-LSojaZc1d7lG26fUsFo:-LStZICNEx06JB_eUYEX:b20wkf1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1d3052149dc637386f6ab310ce1816035ca2d56/pkg/storage/split_trigger_helper.go#L124)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: this all seems a little verbose (unintended pun). You're only using `eventf` twice below, which doesn't really justify the cost of creating it.
</blockquote></details>

Yeah, there were more at some point. Done.

**Review by nvb — DISMISSED** [review]
Gave it another pass. One question I'm left with is wondering how you expect this to interact with repeated chains of splits and merges. I think it should all be fine, but it's worth exploring that and writing down a comment somewhere.

> Reviewed 2 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32782#-:-LSu6J2W0i-JwdMcTI-C:b-iuyu3v)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica.go, line 5214 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32782#-LSod2TM7gVUbKjUY7RZ:-LSu4_0J3W2r0weOXUXd:btcuuzg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1d3052149dc637386f6ab310ce1816035ca2d56/pkg/storage/replica.go#L5214)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Yeah, we don't want to enter the snapshot queue erroneously. It may be possible to get Raft out of that state cleanly (at least after appropriate upstream changes), but I want `raftsnapshot.pending` to be a flat line at some point. We'll send at most one MsgApp per heartbeat interval to a follower that is being probed, so perf shouldn't be a concern here. (in steady state, followers are never expected to be in that state, this only occurs around cluster restarts and replication changes and such).

I morally also want to send something along in MsgAppResp instead, but it's tricky. The uninitialized follower is really dumb and doesn't know anything about itself and the world, so in particular it has no idea where in the key space it should be. The leader (who is the right-hand-side) on the other hand doesn't know about the left-hand-side's bound (and in particular I've often seen its corresponding left-hand-side replica not be leader any more in a rebalancing unit test I have laying around in a WIP that attempted to go this route).

Let me know if you see something I missed. As far as I can tell, we'll need information to go from the leader to the follower and back (the "back" being the rejection in this PR, we could also send an explicit context if we find a reason for it).
</blockquote></details>

Thanks for the explanation. I'd leave a comment pointing at https://github.com/etcd-io/etcd/blob/7f450bf6967638673dd88fd4e730b01d1303d5ff/raft/progress.go#L41, which backs up what you said about a single message per heartbeat interval.
___
*[pkg/storage/replica.go, line 5218 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32782#-LSoiUDe9kOmyRnq9heH:-LSu5dN21TFGy35qa-bq:bn12z0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1d3052149dc637386f6ab310ce1816035ca2d56/pkg/storage/replica.go#L5218)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Done, sort of. I actually took a step back and reconsidered where I was putting this information. The reason I chose the `Context` field is because it was there and so there wasn't any migration headache. However, it's a bit of a wart especially since it gets passed into Raft and we'd have to put protos inside protos. So what I've done instead is put it on `RaftMessageRequest` (as `StartKey`). Old versions receiving the hint simply won't use it, and since RaftMessageRequest doesn't inform any downstream-of-Raft-logic, there shouldn't be a problem.
</blockquote></details>

:thumbsup: that's much better.
___
*[pkg/storage/split_trigger_helper.go, line 58 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32782#-LSogzEKACUCehltiEA7:-LSu5lFb98QSMoghRLMN:b-2uvic1) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1d3052149dc637386f6ab310ce1816035ca2d56/pkg/storage/split_trigger_helper.go#L58)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I don't understand why it's fragile, but I understand that you didn't like the looks of it. Done.
</blockquote></details>

Fragile in that we can't perform static implementation assertions and can't "talk" about the type outside of using it.
___
*[pkg/storage/split_trigger_helper.go, line 66 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32782#-LSu66C383QnBIUp_L5g:-LSu66C383QnBIUp_L5h:b6k46kt) ([raw file](https://github.com/cockroachdb/cockroach/blob/52f9234d26498119747e4b31edc384e088d827c3/pkg/storage/split_trigger_helper.go#L66)):*
> ```Go
> 	// Run the cheapest check first. If the leader doesn't think this replica is
> 	// probing, it won't set msg.Context (the common case).
> 	if msg.Type != raftpb.MsgApp || startKey == nil {
> ```

nit: `len(startKey) == 0` feels a little safer since we're pulling this out of a proto.

**Review by tbg — COMMENTED** [review]
Will add the comment tomorrow. I think I managed to address the rest.

> Dismissed @nvanbenschoten from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32782#-:-LSv94OpCLGSfCOFmbbU:b-l3hli2)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica.go, line 5214 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32782#-LSo-oje2A-GeIOsrOgb:-LSv6kFn-l97_fNi3qa7:b-e4ev6v) ([raw file](https://github.com/cockroachdb/cockroach/blob/54fac7363148996637f903b4f9c7e800ba02d3d2/pkg/storage/replica.go#L5214)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

@nvanbenschoten I'm unhappy about the allocation here and I know you've disliked this kind of thing as well. On `master` I'm planning to solve this problem with a change in `etcd/raft`, though that likely won't be backportable (and I'd like to at least be able to consider this change for a backport, for we've backported its predecessor). How bad is this allocation in the meantime (and on 2.1)?

edit: noticed I hadn't actually sent this comment earlier.
</blockquote></details>

Ping @nvanbenschoten 
___
*[pkg/storage/replica.go, line 5214 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32782#-LSod2TM7gVUbKjUY7RZ:-LSv6m0aD_IIyI83ZS1S:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a1d3052149dc637386f6ab310ce1816035ca2d56/pkg/storage/replica.go#L5214)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Thanks for the explanation. I'd leave a comment pointing at https://github.com/etcd-io/etcd/blob/7f450bf6967638673dd88fd4e730b01d1303d5ff/raft/progress.go#L41, which backs up what you said about a single message per heartbeat interval.
</blockquote></details>

Done.
___
*[pkg/storage/split_trigger_helper.go, line 66 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32782#-LSu66C383QnBIUp_L5g:-LSv71O3-z7A-hN1AP_2:bvgz1l5) ([raw file](https://github.com/cockroachdb/cockroach/blob/52f9234d26498119747e4b31edc384e088d827c3/pkg/storage/split_trigger_helper.go#L66)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: `len(startKey) == 0` feels a little safer since we're pulling this out of a proto.
</blockquote></details>

But if this is happening to the first range, the start key will intentionally be empty. Does TestProtoZeroNilSlice (added in this revision) address your concern?

**Comment by tbg** [comment]
Ok, all set. PTAL.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32782)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica.go, line 5214 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32782#-LSo-oje2A-GeIOsrOgb:-LSzMyty2VLi5nA-tKuU:bcz1m11) ([raw file](https://github.com/cockroachdb/cockroach/blob/54fac7363148996637f903b4f9c7e800ba02d3d2/pkg/storage/replica.go#L5214)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Ping @nvanbenschoten 
</blockquote></details>

I was thinking that we would only hit the allocation when we need to add the start key, but you're right that we'll hit it for every Raft message. That seems like a pretty big issue. `RawNode.Status` allocates at least three times and we regularly see it come up on allocation profiles. Calling it this frequently is likely to have a measurable performance impact. We would either need to prove that this is not the case or make that upstream change (`RawNode.UnsafeStatus()`?) before merging this one. I'd strongly lean towards the latter.

I'm not sure about the backport problem. Seems the like the work we're doing here is much more tricky than whatever accessor you add to `etcd/raft`, so I don't expect to see this backported. If it is though, I'd push to backport that change as well.
___
*[pkg/storage/split_trigger_helper.go, line 66 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32782#-LSu66C383QnBIUp_L5g:-LSzOYac8qu5W9lHZ0tL:b-af183f) ([raw file](https://github.com/cockroachdb/cockroach/blob/52f9234d26498119747e4b31edc384e088d827c3/pkg/storage/split_trigger_helper.go#L66)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

But if this is happening to the first range, the start key will intentionally be empty. Does TestProtoZeroNilSlice (added in this revision) address your concern?
</blockquote></details>

Yep, thanks!

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32782)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/replica.go, line 5214 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32782#-LSo-oje2A-GeIOsrOgb:-LT2EN9sB7cTMQn_V1en:b53hydy) ([raw file](https://github.com/cockroachdb/cockroach/blob/54fac7363148996637f903b4f9c7e800ba02d3d2/pkg/storage/replica.go#L5214)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I was thinking that we would only hit the allocation when we need to add the start key, but you're right that we'll hit it for every Raft message. That seems like a pretty big issue. `RawNode.Status` allocates at least three times and we regularly see it come up on allocation profiles. Calling it this frequently is likely to have a measurable performance impact. We would either need to prove that this is not the case or make that upstream change (`RawNode.UnsafeStatus()`?) before merging this one. I'd strongly lean towards the latter.

I'm not sure about the backport problem. Seems the like the work we're doing here is much more tricky than whatever accessor you add to `etcd/raft`, so I don't expect to see this backported. If it is though, I'd push to backport that change as well.
</blockquote></details>

Ok, I sent a PR upstream: https://github.com/etcd-io/etcd/pull/10309

Once this (or whatever its final form is) is in, I'll bump the dep and update this PR.

**Comment by tbg** [comment]
@nvanbenschoten yep

**Review by nvb — APPROVED** [review]
:lgtm: thanks for following through with this. Two minor nits but otherwise ready to merge.

> Reviewed 6 of 6 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32782#-:-LTd5UX9Dj6nL05-URGr:b-7uliwj)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/storage/raft.proto, line 73 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32782#-LTd4pn19OJXpnl0rdM3:-LTd4pn19OJXpnl0rdM4:b67khcg) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a1cd215392a4767e27355a374d3b5ff7d996dae/pkg/storage/raft.proto#L73)):*
> ```protobuf
>   repeated RaftHeartbeat heartbeat_resps = 7 [(gogoproto.nullable) = false];
> 
>   // Optionally, the start key of the sending replica. This is only populated
> ```

nit (take it or leave it) now that I'm reading over this again: name this `range_start_key` and move it right below `range_id`.
___
*[pkg/storage/replica.go, line 315 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/32782#-LTd5Rjz2V_b_Ow8JbY5:-LTd5Rjz2V_b_Ow8JbY6:b-i40ait) ([raw file](https://github.com/cockroachdb/cockroach/blob/7329f96e3350ed97159ce62f63c6b976d7a5ab22/pkg/storage/replica.go#L315)):*
> ```Go
> 	// aren't held up by this latch, which could result in reads on the RHS
> 	// executed through the LHS after this is valid. For more detail, see:
> 	// https://github.com/cockroachdb/cockroach/issues/32583
> ```

nit: period at end.

**Review by tbg — COMMENTED** [review]
TFTR! Going to wait for TC to green this before I merge.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32782#-:-LThRticDVSPfQGwYpLm:bvwn99w)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/raft.proto, line 73 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32782#-LTd4pn19OJXpnl0rdM3:-LThQQpR55OqOYJEGQZZ:bfvbqoc) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a1cd215392a4767e27355a374d3b5ff7d996dae/pkg/storage/raft.proto#L73)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit (take it or leave it) now that I'm reading over this again: name this `range_start_key` and move it right below `range_id`.
</blockquote></details>

No bother at all, done.

**Comment by tbg** [comment]
bors r=nvanbenschoten

**Pull request merged**
